OrcaSlicer: src/qhull/src/libqhullcpp/QhullQh.cpp File Reference
QhullQh.cpp File Reference
#include "libqhullcpp/QhullQh.h"
#include "libqhullcpp/QhullError.h"
#include "libqhullcpp/QhullStat.h"
#include <sstream>
#include <iostream>
#include <stdarg.h>
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
void qh_fprintf (qhT *qh, FILE *fp, int msgcode, const char *fmt,...)
Function Documentation
qh_fprintf()
void qh_fprintf (qhT * qh, FILE * fp, int msgcode, const char * fmt, ...)
{
    va_list args;
    using namespace orgQhull;
    if(!qh->ISqhullQh){
        qh_fprintf_stderr(10025, "Qhull error: qh_fprintf called from a Qhull instance without QhullQh defined\n");
        qh_exit(10025);
    }
    QhullQh *qhullQh= static_cast<QhullQh *>(qh);
    va_start(args, fmt);
    if(msgcode<MSG_OUTPUT || fp == qh_FILEstderr){
        if(msgcode>=MSG_ERROR && msgcode<MSG_WARNING){
            if(qhullQh->qhull_status<MSG_ERROR || qhullQh->qhull_status>=MSG_WARNING){
                qhullQh->qhull_status= msgcode;
            }
        }
        char newMessage[MSG_MAXLEN];
        // RoadError will add the message tag
        vsnprintf(newMessage, sizeof(newMessage), fmt, args);
        qhullQh->appendQhullMessage(newMessage);
        va_end(args);
        return;
    }
    if(qhullQh->output_stream && qhullQh->use_output_stream){
        char newMessage[MSG_MAXLEN];
        vsnprintf(newMessage, sizeof(newMessage), fmt, args);
        *qhullQh->output_stream << newMessage;
        va_end(args);
        return;
    }
    // FIXUP QH11008: how do users trap messages and handle input?  A callback?
    char newMessage[MSG_MAXLEN];
    vsnprintf(newMessage, sizeof(newMessage), fmt, args);
    qhullQh->appendQhullMessage(newMessage);
    va_end(args);
} /* qh_fprintf */
References orgQhull::QhullQh::appendQhullMessage(), MSG_ERROR, MSG_MAXLEN, MSG_OUTPUT, MSG_WARNING, orgQhull::QhullQh::output_stream, qh, qh_exit(), qh_FILEstderr, qh_fprintf_stderr(), orgQhull::QhullQh::qhull_status, and orgQhull::QhullQh::use_output_stream.