OrcaSlicer: Slic3r::ExtrusionMultiPath Class Reference
Slic3r::ExtrusionMultiPath Class Reference
#include <src/libslic3r/ExtrusionEntity.hpp>
Public Member Functions
ExtrusionMultiPath ()
ExtrusionMultiPath (const ExtrusionMultiPath &rhs)
ExtrusionMultiPath (ExtrusionMultiPath &&rhs)
ExtrusionMultiPath (const ExtrusionPaths &paths)
ExtrusionMultiPath (const ExtrusionPath &path)
ExtrusionMultiPath & operator= (const ExtrusionMultiPath &rhs)
ExtrusionMultiPath & operator= (ExtrusionMultiPath &&rhs)
bool is_loop () const override
bool can_reverse () const override
void set_reverse () override
ExtrusionEntity * clone () const override
ExtrusionEntity * clone_move () override
void reverse () override
const Point & first_point () const override
const Point & last_point () const override
size_t size () const
bool empty () const
double length () const override
ExtrusionRole role () const override
void polygons_covered_by_width (Polygons &out, const float scaled_epsilon) const override
void polygons_covered_by_spacing (Polygons &out, const float scaled_epsilon) const override
Polygons polygons_covered_by_width (const float scaled_epsilon=0.f) const
Polygons polygons_covered_by_spacing (const float scaled_epsilon=0.f) const
double min_mm3_per_mm () const override
Polyline as_polyline () const override
void collect_polylines (Polylines &dst) const override
void collect_points (Points &dst) const override
double total_volume () const override
virtual bool is_collection () const
virtual bool can_sort () const
virtual Polylines as_polylines () const
Static Public Member Functions
static std::string role_to_string (ExtrusionRole role)
static ExtrusionRole string_to_role (const std::string_view role)
Public Attributes
ExtrusionPaths paths
Private Attributes
bool m_can_reverse = true
Detailed Description
Constructor & Destructor Documentation
ExtrusionMultiPath() [1/5]
Slic3r::ExtrusionMultiPath::ExtrusionMultiPath () inline
{}
Referenced by clone(), and clone_move().
ExtrusionMultiPath() [2/5]
Slic3r::ExtrusionMultiPath::ExtrusionMultiPath (const ExtrusionMultiPath & rhs) inline
: paths(rhs.paths), m_can_reverse(rhs.m_can_reverse) {}
ExtrusionMultiPath() [3/5]
Slic3r::ExtrusionMultiPath::ExtrusionMultiPath (ExtrusionMultiPath && rhs) inline
: paths(std::move(rhs.paths)), m_can_reverse(rhs.m_can_reverse) {}
ExtrusionMultiPath() [4/5]
Slic3r::ExtrusionMultiPath::ExtrusionMultiPath (const ExtrusionPaths & paths) inline
: paths(paths) {}
ExtrusionMultiPath() [5/5]
Slic3r::ExtrusionMultiPath::ExtrusionMultiPath (const ExtrusionPath & path) inline
{this->paths.push_back(path); m_can_reverse = path.can_reverse(); }
References Slic3r::ExtrusionPath::can_reverse(), and m_can_reverse.
Member Function Documentation
as_polyline()
Polyline Slic3r::ExtrusionMultiPath::as_polyline () const override virtual
Implements Slic3r::ExtrusionEntity.
{
    Polyline out;
    if (! paths.empty()) {
        size_t len = 0;
        for (size_t i_path = 0; i_path < paths.size(); ++ i_path) {
            assert(! paths[i_path].polyline.points.empty());
            assert(i_path == 0 || paths[i_path - 1].polyline.points.back() == paths[i_path].polyline.points.front());
            len += paths[i_path].polyline.points.size();
        }
        // The connecting points between the segments are equal.
        len -= paths.size() - 1;
        assert(len > 0);
        out.points.reserve(len);
        out.points.push_back(paths.front().polyline.points.front());
        for (size_t i_path = 0; i_path < paths.size(); ++ i_path)
            out.points.insert(out.points.end(), paths[i_path].polyline.points.begin() + 1, paths[i_path].polyline.points.end());
    }
    return out;
}
References out, and paths.
Referenced by collect_polylines().
as_polylines()
virtual Polylines Slic3r::ExtrusionEntity::as_polylines () const inline virtual inherited
{ Polylines dst; this->collect_polylines(dst); return dst; }
References Slic3r::ExtrusionEntity::collect_polylines().
Referenced by Slic3r::SupportMaterialInternal::remove_bridges_from_contacts().
can_reverse()
bool Slic3r::ExtrusionMultiPath::can_reverse () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ return m_can_reverse; }
References m_can_reverse.
can_sort()
virtual bool Slic3r::ExtrusionEntity::can_sort () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return true; }//BBS: only used in ExtrusionEntityCollection
clone()
ExtrusionEntity * Slic3r::ExtrusionMultiPath::clone () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return new ExtrusionMultiPath(*this); }
References ExtrusionMultiPath().
clone_move()
ExtrusionEntity * Slic3r::ExtrusionMultiPath::clone_move () inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return new ExtrusionMultiPath(std::move(*this)); }
References ExtrusionMultiPath().
collect_points()
void Slic3r::ExtrusionMultiPath::collect_points (Points & dst) const inline override virtual
Implements Slic3r::ExtrusionEntity.
{
        size_t n = std::accumulate(paths.begin(), paths.end(), 0, [](const size_t n, const ExtrusionPath &p){ return n + p.polyline.size(); });
        dst.reserve(dst.size() + n);
        for (const ExtrusionPath &p : this->paths)
            append(dst, p.polyline.points);
    }
References Slic3r::append(), n, paths, Slic3r::MultiPoint::points, and Slic3r::ExtrusionPath::polyline.
collect_polylines()
void Slic3r::ExtrusionMultiPath::collect_polylines (Polylines & dst) const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ Polyline pl = this->as_polyline(); if (! pl.empty()) dst.emplace_back(std::move(pl)); }
References as_polyline(), and Slic3r::MultiPoint::empty().
empty()
bool Slic3r::ExtrusionMultiPath::empty () const inline
{ return this->paths.empty(); }
Referenced by Slic3r::extrusion_entities_append_paths_with_wipe().
first_point()
const Point & Slic3r::ExtrusionMultiPath::first_point () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->paths.front().polyline.points.front(); }
is_collection()
virtual bool Slic3r::ExtrusionEntity::is_collection () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return false; }
is_loop()
bool Slic3r::ExtrusionMultiPath::is_loop () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ return false; }
last_point()
const Point & Slic3r::ExtrusionMultiPath::last_point () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->paths.back().polyline.points.back(); }
length()
double Slic3r::ExtrusionMultiPath::length () const override virtual
Implements Slic3r::ExtrusionEntity.
{
    double len = 0;
    for (const ExtrusionPath &path : this->paths)
        len += path.polyline.length();
    return len;
}
References paths.
min_mm3_per_mm()
double Slic3r::ExtrusionMultiPath::min_mm3_per_mm () const override virtual
Implements Slic3r::ExtrusionEntity.
{
    double min_mm3_per_mm = std::numeric_limits<double>::max();
    for (const ExtrusionPath &path : this->paths)
        min_mm3_per_mm = std::min(min_mm3_per_mm, path.mm3_per_mm);
    return min_mm3_per_mm;
}
References min_mm3_per_mm(), and paths.
Referenced by min_mm3_per_mm().
operator=() [1/2]
ExtrusionMultiPath & Slic3r::ExtrusionMultiPath::operator= (const ExtrusionMultiPath & rhs) inline
    {
        this->paths   = rhs.paths;
        m_can_reverse = rhs.m_can_reverse;
        return *this;
    }
References m_can_reverse, and paths.
operator=() [2/2]
ExtrusionMultiPath & Slic3r::ExtrusionMultiPath::operator= (ExtrusionMultiPath && rhs) inline
    {
        this->paths   = std::move(rhs.paths);
        m_can_reverse = rhs.m_can_reverse;
        return *this;
    }
References m_can_reverse.
polygons_covered_by_spacing() [1/2]
Polygons Slic3r::ExtrusionMultiPath::polygons_covered_by_spacing (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_spacing(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_spacing().
polygons_covered_by_spacing() [2/2]
void Slic3r::ExtrusionMultiPath::polygons_covered_by_spacing (Polygons & out, const float scaled_epsilon) const override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (const ExtrusionPath &path : this->paths)
        path.polygons_covered_by_spacing(out, scaled_epsilon);
}
References out, and paths.
Referenced by polygons_covered_by_spacing().
polygons_covered_by_width() [1/2]
Polygons Slic3r::ExtrusionMultiPath::polygons_covered_by_width (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_width(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_width().
polygons_covered_by_width() [2/2]
void Slic3r::ExtrusionMultiPath::polygons_covered_by_width (Polygons & out, const float scaled_epsilon) const override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (const ExtrusionPath &path : this->paths)
        path.polygons_covered_by_width(out, scaled_epsilon);
}
References out, and paths.
Referenced by polygons_covered_by_width().
reverse()
void Slic3r::ExtrusionMultiPath::reverse () override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (ExtrusionPath &path : this->paths)
        path.reverse();
    std::reverse(this->paths.begin(), this->paths.end());
}
References paths.
role()
ExtrusionRole Slic3r::ExtrusionMultiPath::role () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->paths.empty() ? erNone : this->paths.front().role(); }
References Slic3r::erNone.
role_to_string()
std::string Slic3r::ExtrusionEntity::role_to_string (ExtrusionRole role) static inherited
{
    switch (role) {
        case erNone                         : return L("Undefined");
        case erPerimeter                    : return L("Inner wall");
        case erExternalPerimeter            : return L("Outer wall");
        case erOverhangPerimeter            : return L("Overhang wall");
        case erInternalInfill               : return L("Sparse infill");
        case erSolidInfill                  : return L("Internal solid infill");
        case erTopSolidInfill               : return L("Top surface");
        case erBottomSurface                : return L("Bottom surface");
        case erIroning                      : return L("Ironing");
        case erBridgeInfill                 : return L("Bridge");
        case erInternalBridgeInfill         : return L("Internal Bridge");
        case erGapFill                      : return L("Gap infill");
        case erSkirt                        : return ("Skirt");
        case erBrim                         : return ("Brim");
        case erSupportMaterial              : return L("Support");
        case erSupportMaterialInterface     : return L("Support interface");
        case erSupportTransition            : return L("Support transition");
        case erWipeTower                    : return L("Prime tower");
        case erCustom                       : return L("Custom");
        case erMixed                        : return L("Multiple");
        default                             : assert(false);
    }
    return "";
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and Slic3r::ExtrusionEntity::role().
Referenced by Slic3r::WipeTowerWriter::WipeTowerWriter(), Slic3r::GCode::_do_export(), and Slic3r::GUI::GCodeViewer::render_legend().
set_reverse()
void Slic3r::ExtrusionMultiPath::set_reverse () inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ m_can_reverse = false; }
References m_can_reverse.
size()
size_t Slic3r::ExtrusionMultiPath::size () const inline
{ return this->paths.size(); }
string_to_role()
ExtrusionRole Slic3r::ExtrusionEntity::string_to_role (const std::string_view role) static inherited
{
    if (role == L("Inner wall"))
        return erPerimeter;
    else if (role == L("Outer wall"))
        return erExternalPerimeter;
    else if (role == L("Overhang wall"))
        return erOverhangPerimeter;
    else if (role == L("Sparse infill"))
        return erInternalInfill;
    else if (role == L("Internal solid infill"))
        return erSolidInfill;
    else if (role == L("Top surface"))
        return erTopSolidInfill;
    else if (role == L("Bottom surface"))
        return erBottomSurface;
    else if (role == L("Ironing"))
        return erIroning;
    else if (role == L("Bridge"))
        return erBridgeInfill;
    else if (role == L("Internal Bridge"))
        return erInternalBridgeInfill;
    else if (role == L("Gap infill"))
        return erGapFill;
    else if (role == ("Skirt"))
        return erSkirt;
    else if (role == ("Brim"))
        return erBrim;
    else if (role == L("Support"))
        return erSupportMaterial;
    else if (role == L("Support interface"))
        return erSupportMaterialInterface;
    else if (role == L("Support transition"))
        return erSupportTransition;
    else if (role == L("Prime tower"))
        return erWipeTower;
    else if (role == L("Custom"))
        return erCustom;
    else if (role == L("Multiple"))
        return erMixed;
    else
        return erNone;
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and Slic3r::ExtrusionEntity::role().
Referenced by Slic3r::FanMover::_process_gcode_line(), and Slic3r::GCodeProcessor::process_tags().
total_volume()
double Slic3r::ExtrusionMultiPath::total_volume () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ double volume =0.; for (const auto& path : paths) volume += path.total_volume(); return volume; }
References paths.
Member Data Documentation
m_can_reverse
bool Slic3r::ExtrusionMultiPath::m_can_reverse = true private
Referenced by ExtrusionMultiPath(), can_reverse(), operator=(), operator=(), and set_reverse().
paths
ExtrusionPaths Slic3r::ExtrusionMultiPath::paths
Referenced by as_polyline(), collect_points(), Slic3r::convert_extrusion_from_json(), Slic3r::convert_extrusion_to_json(), Slic3r::GCode::extrude_multi_path(), Slic3r::extrusion_entities_append_paths_with_wipe(), Slic3r::extrusionentity_extents(), Slic3r::_3DScene::extrusionentity_to_verts(), length(), min_mm3_per_mm(), Slic3r::modulate_extrusion_by_overlapping_layers(), operator=(), polygons_covered_by_spacing(), polygons_covered_by_width(), reverse(), Slic3r::LayerRegion::simplify_multi_path(), Slic3r::Layer::simplify_support_multi_path(), total_volume(), and Slic3r::traverse_extrusions().
The documentation for this class was generated from the following files:
src/libslic3r/ExtrusionEntity.hpp
src/libslic3r/ExtrusionEntity.cpp