OrcaSlicer: Slic3r::Skirt Namespace Reference
Slic3r::Skirt Namespace Reference
Functions
static void skirt_loops_per_extruder_all_printing (const Print &print, const LayerTools &layer_tools, std::map< unsigned int, std::pair< size_t, size_t > > &skirt_loops_per_extruder_out)
static std::map< unsigned int, std::pair< size_t, size_t > > make_skirt_loops_per_extruder_1st_layer (const Print &print, const LayerTools &layer_tools, std::vector< coordf_t > &skirt_done)
static std::map< unsigned int, std::pair< size_t, size_t > > make_skirt_loops_per_extruder_other_layers (const Print &print, const LayerTools &layer_tools, std::vector< coordf_t > &skirt_done)
Function Documentation
make_skirt_loops_per_extruder_1st_layer()
static std::map< unsigned int, std::pair< size_t, size_t > > Slic3r::Skirt::make_skirt_loops_per_extruder_1st_layer (const Print & print, const LayerTools & layer_tools, std::vector< coordf_t > & skirt_done) static
    {
        // Extrude skirt at the print_z of the raft layers and normal object layers
        // not at the print_z of the interlaced support material layers.
        std::map<unsigned int, std::pair<size_t, size_t>> skirt_loops_per_extruder_out;
        //For sequential print, the following test may fail when extruding the 2nd and other objects.
        // assert(skirt_done.empty());
        if (skirt_done.empty() && print.has_skirt() && ! print.skirt().entities.empty() && layer_tools.has_skirt) {
            skirt_loops_per_extruder_all_printing(print, layer_tools, skirt_loops_per_extruder_out);
            skirt_done.emplace_back(layer_tools.print_z);
        }
        return skirt_loops_per_extruder_out;
    }
References Slic3r::ExtrusionEntityCollection::entities, Slic3r::LayerTools::has_skirt, Slic3r::Print::has_skirt(), make_skirt_loops_per_extruder_1st_layer(), Slic3r::LayerTools::print_z, Slic3r::Print::skirt(), and skirt_loops_per_extruder_all_printing().
Referenced by make_skirt_loops_per_extruder_1st_layer().
make_skirt_loops_per_extruder_other_layers()
static std::map< unsigned int, std::pair< size_t, size_t > > Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers (const Print & print, const LayerTools & layer_tools, std::vector< coordf_t > & skirt_done) static
    {
        // Extrude skirt at the print_z of the raft layers and normal object layers
        // not at the print_z of the interlaced support material layers.
        std::map<unsigned int, std::pair<size_t, size_t>> skirt_loops_per_extruder_out;
        if (print.has_skirt() && ! print.skirt().entities.empty() && layer_tools.has_skirt &&
            // Not enough skirt layers printed yet.
            //FIXME infinite or high skirt does not make sense for sequential print!
            (skirt_done.size() < (size_t)print.config().skirt_height.value || print.has_infinite_skirt())) {
            bool valid = ! skirt_done.empty() && skirt_done.back() < layer_tools.print_z - EPSILON;
            assert(valid);
            // This print_z has not been extruded yet (sequential print)
            // FIXME: The skirt_done should not be empty at this point. The check is a workaround
            if (valid) {
#if 0
                // Prime just the first printing extruder. This is original Slic3r's implementation.
                skirt_loops_per_extruder_out[layer_tools.extruders.front()] = std::pair<size_t, size_t>(0, print.config().skirt_loops.value);
#else
                // Prime all extruders planned for this layer, see
                skirt_loops_per_extruder_all_printing(print, layer_tools, skirt_loops_per_extruder_out);
#endif
                assert(!skirt_done.empty());
                skirt_done.emplace_back(layer_tools.print_z);
            }
        }
        return skirt_loops_per_extruder_out;
    }
References Slic3r::Print::config(), Slic3r::ExtrusionEntityCollection::entities, EPSILON, Slic3r::LayerTools::extruders, Slic3r::Print::has_infinite_skirt(), Slic3r::LayerTools::has_skirt, Slic3r::Print::has_skirt(), make_skirt_loops_per_extruder_other_layers(), Slic3r::LayerTools::print_z, Slic3r::Print::skirt(), and skirt_loops_per_extruder_all_printing().
Referenced by make_skirt_loops_per_extruder_other_layers().
skirt_loops_per_extruder_all_printing()
static void Slic3r::Skirt::skirt_loops_per_extruder_all_printing (const Print & print, const LayerTools & layer_tools, std::map< unsigned int, std::pair< size_t, size_t > > & skirt_loops_per_extruder_out) static
    {
        // Prime all extruders printing over the 1st layer over the skirt lines.
        size_t n_loops = print.skirt().entities.size();
        size_t n_tools = layer_tools.extruders.size();
        size_t lines_per_extruder = (n_loops + n_tools - 1) / n_tools;
        // BBS. Extrude skirt with first extruder if min_skirt_length is zero
        const PrintConfig &config = print.config();
        if (Print::min_skirt_length < EPSILON) {
            skirt_loops_per_extruder_out[layer_tools.extruders.front()] = std::pair<size_t, size_t>(0, n_loops);
        } else {
            for (size_t i = 0; i < n_loops; i += lines_per_extruder)
                skirt_loops_per_extruder_out[layer_tools.extruders[i / lines_per_extruder]] = std::pair<size_t, size_t>(i, std::min(i + lines_per_extruder, n_loops));
        }
    }
References Slic3r::Print::config(), Slic3r::ExtrusionEntityCollection::entities, EPSILON, Slic3r::LayerTools::extruders, Slic3r::Print::skirt(), and skirt_loops_per_extruder_all_printing().
Referenced by make_skirt_loops_per_extruder_1st_layer(), make_skirt_loops_per_extruder_other_layers(), and skirt_loops_per_extruder_all_printing().