OrcaSlicer: Slic3r::PrusaFileParser Class Reference
Slic3r::PrusaFileParser Class Reference
#include <src/libslic3r/Format/3mf.hpp>
Public Member Functions
PrusaFileParser ()
~PrusaFileParser ()
bool check_3mf_from_prusa (const std::string filename)
void _start_element_handler (const char *name, const char **attributes)
void _characters_handler (const XML_Char *s, int len)
Private Member Functions
const char * get_attribute_value_charptr (const char **attributes, unsigned int attributes_size, const char *attribute_key)
std::string get_attribute_value_string (const char **attributes, unsigned int attributes_size, const char *attribute_key)
Static Private Member Functions
static void XMLCALL start_element_handler (void *userData, const char *name, const char **attributes)
static void XMLCALL characters_handler (void *userData, const XML_Char *s, int len)
Private Attributes
bool m_from_prusa = false
bool m_is_application_key = false
XML_Parser m_parser
Detailed Description
Constructor & Destructor Documentation
PrusaFileParser()
Slic3r::PrusaFileParser::PrusaFileParser () inline
{}
~PrusaFileParser()
Slic3r::PrusaFileParser::~PrusaFileParser () inline
{}
Member Function Documentation
_characters_handler()
void Slic3r::PrusaFileParser::_characters_handler (const XML_Char * s, int len)
{
    if (m_is_application_key) {
        std::string str(s, len);
        if (!str.empty() && str.find("PrusaSlicer") != std::string::npos) m_from_prusa = true;
    }
}
References m_from_prusa, and m_is_application_key.
Referenced by characters_handler().
_start_element_handler()
void Slic3r::PrusaFileParser::_start_element_handler (const char * name, const char ** attributes)
{
    if (::strcmp(name, "metadata") == 0) {
        unsigned int num_attributes = (unsigned int) XML_GetSpecifiedAttributeCount(m_parser);
        std::string str_name = get_attribute_value_string(attributes, num_attributes, "name");
        if (!str_name.empty() && str_name.find("Application") != std::string::npos) { m_is_application_key = true; }
    }
}
References get_attribute_value_string(), int, m_is_application_key, m_parser, and XML_GetSpecifiedAttributeCount().
Referenced by start_element_handler().
characters_handler()
void XMLCALL Slic3r::PrusaFileParser::characters_handler (void * userData, const XML_Char * s, int len) static private
{
    PrusaFileParser *prusa_parser = (PrusaFileParser *) userData;
    if (prusa_parser != nullptr) { prusa_parser->_characters_handler(s, len); }
}
References _characters_handler(), and userData.
Referenced by check_3mf_from_prusa().
check_3mf_from_prusa()
bool Slic3r::PrusaFileParser::check_3mf_from_prusa (const std::string filename)
{
    mz_zip_archive archive;
    mz_zip_zero_struct(&archive);
    if (!open_zip_reader(&archive, filename)) {
        // throw Slic3r::RuntimeError("Loading 3mf file failed.");
        return false;
    }
    const std::string sub_relationship_file = "3D/_rels/3dmodel.model.rels";
    int               sub_index             = mz_zip_reader_locate_file(&archive, sub_relationship_file.c_str(), nullptr, 0);
    if (sub_index == -1) {
        const std::string model_file       = "3D/3dmodel.model";
        int               model_file_index = mz_zip_reader_locate_file(&archive, model_file.c_str(), nullptr, 0);
        if (model_file_index != -1) {
            int depth = 0;
            m_parser  = XML_ParserCreate(nullptr);
            XML_SetUserData(m_parser, (void *) this);
            XML_SetElementHandler(m_parser, start_element_handler, nullptr);
            XML_SetCharacterDataHandler(m_parser, characters_handler);
            mz_zip_archive_file_stat stat;
            if (!mz_zip_reader_file_stat(&archive, model_file_index, &stat)) goto EXIT;
            void *parser_buffer = XML_GetBuffer(m_parser, (int) stat.m_uncomp_size);
            if (parser_buffer == nullptr) goto EXIT;
            mz_bool res = mz_zip_reader_extract_file_to_mem(&archive, stat.m_filename, parser_buffer, (size_t) stat.m_uncomp_size, 0);
            if (res == 0) goto EXIT;
            XML_ParseBuffer(m_parser, (int) stat.m_uncomp_size, 1);
        }
    }
EXIT:
    close_zip_reader(&archive);
    return m_from_prusa;
}
References characters_handler(), Slic3r::close_zip_reader(), mz_zip_archive_file_stat::m_filename, m_from_prusa, m_parser, mz_zip_archive_file_stat::m_uncomp_size, mz_zip_reader_extract_file_to_mem(), mz_zip_reader_file_stat(), mz_zip_reader_locate_file(), mz_zip_zero_struct(), Slic3r::open_zip_reader(), start_element_handler(), XML_GetBuffer(), XML_ParseBuffer(), XML_ParserCreate(), XML_SetCharacterDataHandler(), XML_SetElementHandler(), and XML_SetUserData().
Referenced by Slic3r::Model::read_from_archive().
get_attribute_value_charptr()
const char * Slic3r::PrusaFileParser::get_attribute_value_charptr (const char ** attributes, unsigned int attributes_size, const char * attribute_key) private
{
    if ((attributes == nullptr) || (attributes_size == 0) || (attributes_size % 2 != 0) || (attribute_key == nullptr)) return nullptr;
    for (unsigned int a = 0; a < attributes_size; a += 2) {
        if (::strcmp(attributes[a], attribute_key) == 0) return attributes[a + 1];
    }
    return nullptr;
}
Referenced by get_attribute_value_string().
get_attribute_value_string()
std::string Slic3r::PrusaFileParser::get_attribute_value_string (const char ** attributes, unsigned int attributes_size, const char * attribute_key) private
{
    const char *text = get_attribute_value_charptr(attributes, attributes_size, attribute_key);
    return (text != nullptr) ? text : "";
}
References get_attribute_value_charptr().
Referenced by _start_element_handler().
start_element_handler()
void XMLCALL Slic3r::PrusaFileParser::start_element_handler (void * userData, const char * name, const char ** attributes) static private
{
    PrusaFileParser *prusa_parser = (PrusaFileParser *) userData;
    if (prusa_parser != nullptr) { prusa_parser->_start_element_handler(name, attributes); }
}
References _start_element_handler(), and userData.
Referenced by check_3mf_from_prusa().
Member Data Documentation
m_from_prusa
bool Slic3r::PrusaFileParser::m_from_prusa = false private
Referenced by _characters_handler(), and check_3mf_from_prusa().
m_is_application_key
bool Slic3r::PrusaFileParser::m_is_application_key = false private
Referenced by _characters_handler(), and _start_element_handler().
m_parser
XML_Parser Slic3r::PrusaFileParser::m_parser private
Referenced by _start_element_handler(), and check_3mf_from_prusa().
The documentation for this class was generated from the following files:
src/libslic3r/Format/3mf.hpp
src/libslic3r/Format/3mf.cpp