OrcaSlicer: Slic3r::GUI::View3D Class Reference
Slic3r::GUI::View3D Class Reference
#include <src/slic3r/GUI/GUI_Preview.hpp>
Public Member Functions
View3D (wxWindow *parent, Bed3D &bed, Model *model, DynamicPrintConfig *config, BackgroundSlicingProcess *process)
virtual ~View3D ()
wxGLCanvas * get_wxglcanvas ()
GLCanvas3D * get_canvas3d ()
void set_as_dirty ()
void bed_shape_changed ()
void plates_count_changed ()
void select_view (const std::string &direction)
void select_curr_plate_all ()
void remove_curr_plate_all ()
void select_all ()
void deselect_all ()
void delete_selected ()
void center_selected ()
void mirror_selection (Axis axis)
bool is_layers_editing_enabled () const
bool is_layers_editing_allowed () const
void enable_layers_editing (bool enable)
bool is_dragging () const
bool is_reload_delayed () const
void reload_scene (bool refresh_immediately, bool force_full_scene_refresh=false)
void render ()
Private Member Functions
bool init (wxWindow *parent, Bed3D &bed, Model *model, DynamicPrintConfig *config, BackgroundSlicingProcess *process)
Private Attributes
wxGLCanvas * m_canvas_widget
GLCanvas3D * m_canvas
Detailed Description
Constructor & Destructor Documentation
View3D()
Slic3r::GUI::View3D::View3D (wxWindow * parent, Bed3D & bed, Model * model, DynamicPrintConfig * config, BackgroundSlicingProcess * process)
    : m_canvas_widget(nullptr)
    , m_canvas(nullptr)
{
    init(parent, bed, model, config, process);
}
References init().
~View3D()
Slic3r::GUI::View3D::~View3D () virtual
{
    delete m_canvas;
    delete m_canvas_widget;
}
References m_canvas, and m_canvas_widget.
Member Function Documentation
bed_shape_changed()
void Slic3r::GUI::View3D::bed_shape_changed ()
{
    if (m_canvas != nullptr)
        m_canvas->bed_shape_changed();
}
References Slic3r::GUI::GLCanvas3D::bed_shape_changed(), and m_canvas.
center_selected()
void Slic3r::GUI::View3D::center_selected ()
{
    if (m_canvas != nullptr)
        m_canvas->do_center();
}
References Slic3r::GUI::GLCanvas3D::do_center(), and m_canvas.
delete_selected()
void Slic3r::GUI::View3D::delete_selected ()
{
    if (m_canvas != nullptr)
        m_canvas->delete_selected();
}
References Slic3r::GUI::GLCanvas3D::delete_selected(), and m_canvas.
deselect_all()
void Slic3r::GUI::View3D::deselect_all ()
{
    if (m_canvas != nullptr)
        m_canvas->deselect_all();
}
References Slic3r::GUI::GLCanvas3D::deselect_all(), and m_canvas.
enable_layers_editing()
void Slic3r::GUI::View3D::enable_layers_editing (bool enable)
{
    if (m_canvas != nullptr)
        m_canvas->enable_layers_editing(enable);
}
References Slic3r::GUI::GLCanvas3D::enable_layers_editing(), and m_canvas.
get_canvas3d()
GLCanvas3D * Slic3r::GUI::View3D::get_canvas3d () inline
{ return m_canvas; }
References m_canvas.
Referenced by Slic3r::GUI::Plater::priv::are_view3D_labels_shown(), Slic3r::GUI::Plater::priv::is_view3D_layers_editing_enabled(), Slic3r::GUI::Plater::priv::is_view3D_overhang_shown(), Slic3r::GUI::Plater::priv::show_view3D_labels(), and Slic3r::GUI::Plater::priv::show_view3D_overhang().
get_wxglcanvas()
wxGLCanvas * Slic3r::GUI::View3D::get_wxglcanvas () inline
{ return m_canvas_widget; }
References m_canvas_widget.
init()
bool Slic3r::GUI::View3D::init (wxWindow * parent, Bed3D & bed, Model * model, DynamicPrintConfig * config, BackgroundSlicingProcess * process) private
{
    if (!Create(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0 /* disable wxTAB_TRAVERSAL */))
        return false;
    m_canvas_widget = OpenGLManager::create_wxglcanvas(*this);
    if (m_canvas_widget == nullptr)
        return false;
    m_canvas = new GLCanvas3D(m_canvas_widget, bed);
    m_canvas->set_context(wxGetApp().init_glcontext(*m_canvas_widget));
    m_canvas->allow_multisample(OpenGLManager::can_multisample());
    // XXX: If have OpenGL
    m_canvas->enable_picking(true);
    m_canvas->enable_moving(true);
    // XXX: more config from 3D.pm
    m_canvas->set_model(model);
    m_canvas->set_process(process);
    m_canvas->set_type(GLCanvas3D::ECanvasType::CanvasView3D);
    m_canvas->set_config(config);
    m_canvas->enable_gizmos(true);
    m_canvas->enable_selection(true);
    m_canvas->enable_main_toolbar(true);
    //BBS: GUI refactor: GLToolbar
    m_canvas->enable_select_plate_toolbar(false);
    m_canvas->enable_assemble_view_toolbar(true);
    m_canvas->enable_separator_toolbar(true);
    m_canvas->enable_labels(true);
    m_canvas->enable_slope(true);
    wxBoxSizer* main_sizer = new wxBoxSizer(wxVERTICAL);
    main_sizer->Add(m_canvas_widget, 1, wxALL | wxEXPAND, 0);
    SetSizer(main_sizer);
    SetMinSize(GetSize());
    GetSizer()->SetSizeHints(this);
    return true;
}
References Slic3r::GUI::GLCanvas3D::allow_multisample(), Slic3r::GUI::OpenGLManager::can_multisample(), Slic3r::GUI::GLCanvas3D::CanvasView3D, Slic3r::GUI::OpenGLManager::create_wxglcanvas(), Slic3r::GUI::GLCanvas3D::enable_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::enable_gizmos(), Slic3r::GUI::GLCanvas3D::enable_labels(), Slic3r::GUI::GLCanvas3D::enable_main_toolbar(), Slic3r::GUI::GLCanvas3D::enable_moving(), Slic3r::GUI::GLCanvas3D::enable_picking(), Slic3r::GUI::GLCanvas3D::enable_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::enable_selection(), Slic3r::GUI::GLCanvas3D::enable_separator_toolbar(), Slic3r::GUI::GLCanvas3D::enable_slope(), m_canvas, m_canvas_widget, Slic3r::GUI::GLCanvas3D::set_config(), Slic3r::GUI::GLCanvas3D::set_context(), Slic3r::GUI::GLCanvas3D::set_model(), Slic3r::GUI::GLCanvas3D::set_process(), and Slic3r::GUI::GLCanvas3D::set_type().
Referenced by View3D().
is_dragging()
bool Slic3r::GUI::View3D::is_dragging () const
{
    return (m_canvas != nullptr) ? m_canvas->is_dragging() : false;
}
References Slic3r::GUI::GLCanvas3D::is_dragging(), and m_canvas.
is_layers_editing_allowed()
bool Slic3r::GUI::View3D::is_layers_editing_allowed () const
{
    return (m_canvas != nullptr) ? m_canvas->is_layers_editing_allowed() : false;
}
References Slic3r::GUI::GLCanvas3D::is_layers_editing_allowed(), and m_canvas.
is_layers_editing_enabled()
bool Slic3r::GUI::View3D::is_layers_editing_enabled () const
{
    return (m_canvas != nullptr) ? m_canvas->is_layers_editing_enabled() : false;
}
References Slic3r::GUI::GLCanvas3D::is_layers_editing_enabled(), and m_canvas.
is_reload_delayed()
bool Slic3r::GUI::View3D::is_reload_delayed () const
{
    return (m_canvas != nullptr) ? m_canvas->is_reload_delayed() : false;
}
References Slic3r::GUI::GLCanvas3D::is_reload_delayed(), and m_canvas.
mirror_selection()
void Slic3r::GUI::View3D::mirror_selection (Axis axis)
{
    if (m_canvas != nullptr)
        m_canvas->mirror_selection(axis);
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::mirror_selection().
plates_count_changed()
void Slic3r::GUI::View3D::plates_count_changed ()
{
    if (m_canvas != nullptr)
        m_canvas->plates_count_changed();
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::plates_count_changed().
reload_scene()
void Slic3r::GUI::View3D::reload_scene (bool refresh_immediately, bool force_full_scene_refresh = false)
{
    if (m_canvas != nullptr)
        m_canvas->reload_scene(refresh_immediately, force_full_scene_refresh);
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::reload_scene().
remove_curr_plate_all()
void Slic3r::GUI::View3D::remove_curr_plate_all ()
{
    if (m_canvas != nullptr)
        m_canvas->remove_curr_plate_all();
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::remove_curr_plate_all().
render()
void Slic3r::GUI::View3D::render ()
{
    if (m_canvas != nullptr)
        //m_canvas->render();
        m_canvas->set_as_dirty();
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::set_as_dirty().
Referenced by Slic3r::GUI::Plater::priv::set_current_panel().
select_all()
void Slic3r::GUI::View3D::select_all ()
{
    if (m_canvas != nullptr)
        m_canvas->select_all();
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::select_all().
select_curr_plate_all()
void Slic3r::GUI::View3D::select_curr_plate_all ()
{
    if (m_canvas != nullptr)
        m_canvas->select_curr_plate_all();
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::select_curr_plate_all().
select_view()
void Slic3r::GUI::View3D::select_view (const std::string & direction)
{
    if (m_canvas != nullptr)
        m_canvas->select_view(direction);
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::select_view().
set_as_dirty()
void Slic3r::GUI::View3D::set_as_dirty ()
{
    if (m_canvas != nullptr) {
        m_canvas->set_as_dirty();
    }
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::set_as_dirty().
Member Data Documentation
m_canvas
GLCanvas3D* Slic3r::GUI::View3D::m_canvas private
Referenced by ~View3D(), bed_shape_changed(), center_selected(), delete_selected(), deselect_all(), enable_layers_editing(), get_canvas3d(), init(), is_dragging(), is_layers_editing_allowed(), is_layers_editing_enabled(), is_reload_delayed(), mirror_selection(), plates_count_changed(), reload_scene(), remove_curr_plate_all(), render(), select_all(), select_curr_plate_all(), select_view(), and set_as_dirty().
m_canvas_widget
wxGLCanvas* Slic3r::GUI::View3D::m_canvas_widget private
Referenced by ~View3D(), get_wxglcanvas(), and init().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_Preview.hpp
src/slic3r/GUI/GUI_Preview.cpp