OrcaSlicer: libnest2d::selections::_FirstFitSelection< RawShape > Class Template Reference
libnest2d::selections::_FirstFitSelection< RawShape > Class Template Reference
#include <src/libnest2d/include/libnest2d/selections/firstfit.hpp>
Public Types
using Config = int
using Item = _Item< RawShape >
using ShapeType = RawShape
using PackGroup = _PackGroup< RawShape >
Public Member Functions
void configure (const Config &)
template<class TPlacer , class TIterator , class TBin = typename PlacementStrategyLike<TPlacer>::BinType, class PConfig = typename PlacementStrategyLike<TPlacer>::Config>
void packItems (TIterator first, TIterator last, TBin &&bin, PConfig &&pconfig=PConfig())
const PackGroup & getResult () const
int lastPackedBinId () const
void progressIndicator (ProgressFunction fn)
void stopCondition (StopCondition cond)
void unfitIndicator (UnfitIndicator fn)
void clear ()
Protected Member Functions
template<class Placer , class Container , class Bin , class PCfg >
void remove_unpackable_items (Container &c, const Bin &bin, const PCfg &pcfg)
Protected Attributes
ProgressFunction progress_ = [](unsigned){}
StopCondition stopcond_ = []() { return false; }
UnfitIndicator unfitindicator_
int last_packed_bin_id_ = -1
Private Types
using Base = SelectionBoilerplate< RawShape >
using Container = ItemGroup
using ItemGroup = _ItemGroup< RawShape >
Private Attributes
Container store_
PackGroup packed_bins_
Detailed Description
template<class RawShape>
class libnest2d::selections::_FirstFitSelection< RawShape >
Member Typedef Documentation
Base
template<class RawShape > using libnest2d::selections::_FirstFitSelection< RawShape >::Base = SelectionBoilerplate<RawShape> private
Config
template<class RawShape > using libnest2d::selections::_FirstFitSelection< RawShape >::Config = int
Container
template<class RawShape > using libnest2d::selections::_FirstFitSelection< RawShape >::Container = ItemGroup private
Item
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::Item = _Item<RawShape>
ItemGroup
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::ItemGroup = _ItemGroup<RawShape> private
PackGroup
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::PackGroup = _PackGroup<RawShape> inherited
ShapeType
template<class RawShape > using libnest2d::selections::SelectionBoilerplate< RawShape >::ShapeType = RawShape inherited
Member Function Documentation
clear()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::clear () inline inherited
{ packed_bins_.clear(); }
References libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_.
configure()
template<class RawShape > void libnest2d::selections::_FirstFitSelection< RawShape >::configure (const Config &) inline
{ }
getResult()
template<class RawShape > const PackGroup & libnest2d::selections::SelectionBoilerplate< RawShape >::getResult () const inline inherited
{
        return packed_bins_;
    }
References libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_.
lastPackedBinId()
template<class RawShape > int libnest2d::selections::SelectionBoilerplate< RawShape >::lastPackedBinId () const inline inherited
{ return last_packed_bin_id_; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::last_packed_bin_id_.
packItems()
template<class RawShape > template<class TPlacer , class TIterator , class TBin = typename PlacementStrategyLike<TPlacer>::BinType, class PConfig = typename PlacementStrategyLike<TPlacer>::Config> void libnest2d::selections::_FirstFitSelection< RawShape >::packItems (TIterator first, TIterator last, TBin && bin, PConfig && pconfig = PConfig()) inline
    {
        using Placer = PlacementStrategyLike<TPlacer>;
        store_.clear();
        store_.reserve(last-first);
        std::vector<Placer> placers;
        placers.reserve(last-first);
        typename Base::PackGroup fixed_bins;
        std::for_each(first, last, [this, &fixed_bins](Item& itm) {
            if (itm.isFixed()) {
                if (itm.binId() < 0) itm.binId(0);
                auto binidx = size_t(itm.binId());
                while (fixed_bins.size() <= binidx)
                    fixed_bins.emplace_back();
                fixed_bins[binidx].emplace_back(itm);
            }
            else {
                store_.emplace_back(itm);
            }
            });
        std::for_each(pconfig.m_excluded_regions.begin(), pconfig.m_excluded_regions.end(), [this, &pconfig](Item& itm) {
            pconfig.m_excluded_items.emplace_back(itm);
            });
#ifdef SVGTOOLS_HPP
        svg::SVGWriter<RawShape> svgwriter;
        std::for_each(first, last, [this,&svgwriter](Item &itm) { svgwriter.writeShape(itm, "none", "blue"); });
        svgwriter.save(boost::filesystem::path("SVG") / "all_items.svg");
#endif
        std::function<bool(Item& i1, Item& i2)> sortfunc;
        if (pconfig.sortfunc)
            sortfunc = pconfig.sortfunc;
        else {
            sortfunc = [](Item& i1, Item& i2) {
                int p1 = i1.priority(), p2 = i2.priority();
                if (p1 != p2)
                    return p1 > p2;
                return i1.bed_temp != i2.bed_temp ? (i1.bed_temp > i2.bed_temp) :
                        (i1.height != i2.height ? (i1.height < i2.height) : (i1.area() > i2.area()));
            };
        }
        std::sort(store_.begin(), store_.end(), sortfunc);
        // debug: write down intitial order
        for (auto it = store_.begin(); it != store_.end(); ++it) {
            std::stringstream ss;
            ss << "initial order: " << it->get().name << ", p=" << it->get().priority() << ", bed_temp=" << it->get().bed_temp << ", height=" << it->get().height
               << ", area=" << it->get().area();
            if (this->unfitindicator_)
                this->unfitindicator_(ss.str());
        }
        int item_id = 0;
        auto makeProgress = [this, &item_id](Placer &placer, size_t bin_idx) {
            packed_bins_[bin_idx] = placer.getItems();
            this->last_packed_bin_id_ = int(bin_idx);
            this->progress_(static_cast<unsigned>(item_id));
        };
        auto& cancelled = this->stopcond_;
        this->template remove_unpackable_items<Placer>(store_, bin, pconfig);
        for (auto it = store_.begin(); it != store_.end() && !cancelled(); ++it) {
            // skip unpackable item
            if (it->get().binId() == BIN_ID_UNFIT)
                continue;
            bool was_packed = false;
            int best_bed_id = -1;
            int bed_id_firstfit = -1;
            double score = LARGE_COST_TO_REJECT+1, best_score = LARGE_COST_TO_REJECT+1;
            double score_all_plates = 0, score_all_plates_best = std::numeric_limits<double>::max();
            typename Placer::PackResult result, result_best, result_firstfit;
            int j = 0;
            while(!was_packed && !cancelled()) {
                for(; j < placers.size() && !was_packed && !cancelled(); j++) {
                    result = placers[j].pack(*it, rem(it, store_));
                    score = result.score();
                    score_all_plates = std::accumulate(placers.begin(), placers.begin() + j, score,
                        [](double sum, const Placer& elem) { return sum + elem.score(); });
                    if (this->unfitindicator_) this->unfitindicator_(it->get().name + " bed_id="+std::to_string(j) + ",score=" + std::to_string(score));
                    if(score >= 0 && score < LARGE_COST_TO_REJECT) {
                        if (bed_id_firstfit == -1) {
                            bed_id_firstfit = j;
                            result_firstfit = result;
                        }
                        if (score_all_plates < score_all_plates_best) {
                            best_score = score;
                            score_all_plates_best = score_all_plates;
                            best_bed_id = j;
                            result_best = result;
                        }
                    }
                }
                if (best_bed_id == MAX_NUM_PLATES) {
                    // item is not fit because we have tried all possible plates to find a good enough fit
                    if (bed_id_firstfit == MAX_NUM_PLATES) {
                        it->get().binId(BIN_ID_UNFIT);
                        if (this->unfitindicator_)
                            this->unfitindicator_(it->get().name + " bed_id_firstfit == MAX_NUM_PLATES" + ",best_score=" + std::to_string(best_score));
                        break;
                    }
                    else {
                        // best bed is invalid, but firstfit bed is OK, use the latter
                        best_bed_id = bed_id_firstfit;
                        result_best = result_firstfit;
                    }
                }
                if(best_bed_id>=0)
                {
                    was_packed = true;
                    j = best_bed_id;
                    it->get().binId(int(j));
                    it->get().itemId(item_id++);
                    placers[j].accept(result_best);
                    makeProgress(placers[j], j);
                }
                if(!was_packed){
                    if (this->unfitindicator_ && !placers.empty())
                        this->unfitindicator_(it->get().name + ", height=" +std::to_string(it->get().height)
                            + " ,plate_id=" + std::to_string(j-1)
                            + ", score=" + std::to_string(score)
                            + ", best_bed_id=" + std::to_string(best_bed_id)
                            + ", score_all_plates=" + std::to_string(score_all_plates)
                            +", overfit=" + std::to_string(result.overfit()));
                    placers.emplace_back(bin);
                    placers.back().plateID(placers.size() - 1);
                    placers.back().configure(pconfig);
                    if (fixed_bins.size() >= placers.size())
                        placers.back().preload(fixed_bins[placers.size() - 1]);
                    //placers.back().preload(pconfig.m_excluded_items);
                    packed_bins_.emplace_back();
                    j = placers.size() - 1;
                }
            }
        }
    }
References libnest2d::_Item< RawShape >::area(), libnest2d::_Item< RawShape >::bed_temp, libnest2d::BIN_ID_UNFIT, libnest2d::_Item< RawShape >::height, int, libnest2d::_Item< RawShape >::isFixed(), LARGE_COST_TO_REJECT, libnest2d::selections::SelectionBoilerplate< RawShape >::last_packed_bin_id_, MAX_NUM_PLATES, libnest2d::selections::_FirstFitSelection< RawShape >::packed_bins_, libnest2d::_Item< RawShape >::priority(), libnest2d::selections::SelectionBoilerplate< RawShape >::progress_, libnest2d::rem(), libnest2d::svg::SVGWriter< RawShape >::save(), libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_, libnest2d::selections::_FirstFitSelection< RawShape >::store_, libnest2d::selections::SelectionBoilerplate< RawShape >::unfitindicator_, and libnest2d::svg::SVGWriter< RawShape >::writeShape().
progressIndicator()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::progressIndicator (ProgressFunction fn) inline inherited
{ progress_ = fn; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::progress_.
remove_unpackable_items()
template<class RawShape > template<class Placer , class Container , class Bin , class PCfg > void libnest2d::selections::SelectionBoilerplate< RawShape >::remove_unpackable_items (Container & c, const Bin & bin, const PCfg & pcfg) inline protected inherited
    {
        // Safety test: try to pack each item into an empty bin. If it fails
        // then it should be removed from the list
        Placer p{ bin };
        p.configure(pcfg);
        //p.preload(pcfg.m_excluded_items);
        auto it = c.begin();
        while (it != c.end() && !stopcond_()) {
            // WARNING: The copy of itm needs to be created before Placer.
            // Placer is working with references and its destructor still
            // manipulates the item this is why the order of stack creation
            // matters here.
            const Item& itm = *it;
            Item cpy{itm};
            auto result = p.pack(cpy);
            if (itm.area() <= 0 || !result) {
                static_cast<Item&>(*it).binId(BIN_ID_UNFIT);
            }
            it++;
        }
    }
References libnest2d::_Item< RawShape >::area(), libnest2d::BIN_ID_UNFIT, libnest2d::_Item< RawShape >::binId(), and libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_.
stopCondition()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::stopCondition (StopCondition cond) inline inherited
{ stopcond_ = cond; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_.
unfitIndicator()
template<class RawShape > void libnest2d::selections::SelectionBoilerplate< RawShape >::unfitIndicator (UnfitIndicator fn) inline inherited
{ unfitindicator_ = fn; }
References libnest2d::selections::SelectionBoilerplate< RawShape >::unfitindicator_.
Member Data Documentation
last_packed_bin_id_
template<class RawShape > int libnest2d::selections::SelectionBoilerplate< RawShape >::last_packed_bin_id_ = -1 protected inherited
Referenced by libnest2d::selections::SelectionBoilerplate< RawShape >::lastPackedBinId(), and libnest2d::selections::_FirstFitSelection< RawShape >::packItems().
packed_bins_
template<class RawShape > PackGroup libnest2d::selections::SelectionBoilerplate< RawShape >::packed_bins_ private
Referenced by libnest2d::selections::_FirstFitSelection< RawShape >::packItems().
progress_
template<class RawShape > ProgressFunction libnest2d::selections::SelectionBoilerplate< RawShape >::progress_ = [](unsigned){} protected inherited
Referenced by libnest2d::selections::_DJDHeuristic< RawShape >::packItems(), libnest2d::selections::_FillerSelection< RawShape >::packItems(), libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), and libnest2d::selections::SelectionBoilerplate< RawShape >::progressIndicator().
stopcond_
template<class RawShape > StopCondition libnest2d::selections::SelectionBoilerplate< RawShape >::stopcond_ = []() { return false; } protected inherited
Referenced by libnest2d::selections::_DJDHeuristic< RawShape >::packItems(), libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), libnest2d::selections::SelectionBoilerplate< RawShape >::remove_unpackable_items(), and libnest2d::selections::SelectionBoilerplate< RawShape >::stopCondition().
store_
template<class RawShape > Container libnest2d::selections::_FirstFitSelection< RawShape >::store_ private
Referenced by libnest2d::selections::_FirstFitSelection< RawShape >::packItems().
unfitindicator_
template<class RawShape > UnfitIndicator libnest2d::selections::SelectionBoilerplate< RawShape >::unfitindicator_ protected inherited
Referenced by libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), and libnest2d::selections::SelectionBoilerplate< RawShape >::unfitIndicator().
The documentation for this class was generated from the following file:
src/libnest2d/include/libnest2d/selections/firstfit.hpp