OrcaSlicer: Slic3r::ExtrusionPath Class Reference
Slic3r::ExtrusionPath Class Reference
#include <src/libslic3r/ExtrusionEntity.hpp>
Public Member Functions
ExtrusionPath ()
ExtrusionPath (ExtrusionRole role)
ExtrusionPath (ExtrusionRole role, double mm3_per_mm, float width, float height, bool no_extrusion=false)
ExtrusionPath (int overhang_degree, int curve_degree, ExtrusionRole role, double mm3_per_mm, float width, float height)
ExtrusionPath (const ExtrusionPath &rhs)
ExtrusionPath (ExtrusionPath &&rhs)
ExtrusionPath (const Polyline &polyline, const ExtrusionPath &rhs)
ExtrusionPath (Polyline &&polyline, const ExtrusionPath &rhs)
ExtrusionPath & operator= (const ExtrusionPath &rhs)
ExtrusionPath & operator= (ExtrusionPath &&rhs)
ExtrusionEntity * clone () const override
ExtrusionEntity * clone_move () override
void reverse () override
const Point & first_point () const override
const Point & last_point () const override
size_t size () const
bool empty () const
bool is_closed () const
void intersect_expolygons (const ExPolygons &collection, ExtrusionEntityCollection *retval) const
void subtract_expolygons (const ExPolygons &collection, ExtrusionEntityCollection *retval) const
void clip_end (double distance)
void simplify (double tolerance)
double length () const override
ExtrusionRole role () const override
void polygons_covered_by_width (Polygons &out, const float scaled_epsilon) const override
void polygons_covered_by_spacing (Polygons &out, const float scaled_epsilon) const override
Polygons polygons_covered_by_width (const float scaled_epsilon=0.f) const
Polygons polygons_covered_by_spacing (const float scaled_epsilon=0.f) const
double min_mm3_per_mm () const override
Polyline as_polyline () const override
void collect_polylines (Polylines &dst) const override
void collect_points (Points &dst) const override
double total_volume () const override
void set_overhang_degree (int overhang)
int get_overhang_degree () const
void set_curve_degree (int curve)
int get_curve_degree () const
void simplify_by_fitting_arc (double tolerance)
bool is_force_no_extrusion () const
void set_force_no_extrusion (bool no_extrusion)
void set_extrusion_role (ExtrusionRole extrusion_role)
void set_reverse () override
bool can_reverse () const override
virtual bool is_collection () const
virtual bool is_loop () const
virtual bool can_sort () const
virtual Polylines as_polylines () const
Static Public Member Functions
static std::string role_to_string (ExtrusionRole role)
static ExtrusionRole string_to_role (const std::string_view role)
Public Attributes
Polyline polyline
int overhang_degree = 0
int curve_degree = 0
double mm3_per_mm
float width
float height
Private Member Functions
void _inflate_collection (const Polylines &polylines, ExtrusionEntityCollection *collection) const
Private Attributes
bool m_can_reverse = true
ExtrusionRole m_role
bool m_no_extrusion = false
Detailed Description
Constructor & Destructor Documentation
ExtrusionPath() [1/8]
Slic3r::ExtrusionPath::ExtrusionPath () inline
: mm3_per_mm(-1), width(-1), height(-1), m_role(erNone), m_no_extrusion(false) {}
Referenced by clone(), and clone_move().
ExtrusionPath() [2/8]
Slic3r::ExtrusionPath::ExtrusionPath (ExtrusionRole role) inline
: mm3_per_mm(-1), width(-1), height(-1), m_role(role), m_no_extrusion(false) {}
ExtrusionPath() [3/8]
Slic3r::ExtrusionPath::ExtrusionPath (ExtrusionRole role, double mm3_per_mm, float width, float height, bool no_extrusion = false) inline
: mm3_per_mm(mm3_per_mm), width(width), height(height), m_role(role), m_no_extrusion(no_extrusion) {}
ExtrusionPath() [4/8]
Slic3r::ExtrusionPath::ExtrusionPath (int overhang_degree, int curve_degree, ExtrusionRole role, double mm3_per_mm, float width, float height) inline
: overhang_degree(overhang_degree), curve_degree(curve_degree), mm3_per_mm(mm3_per_mm), width(width), height(height), m_role(role) {}
ExtrusionPath() [5/8]
Slic3r::ExtrusionPath::ExtrusionPath (const ExtrusionPath & rhs) inline
        : polyline(rhs.polyline)
        , overhang_degree(rhs.overhang_degree)
        , curve_degree(rhs.curve_degree)
        , mm3_per_mm(rhs.mm3_per_mm)
        , width(rhs.width)
        , height(rhs.height)
        , m_can_reverse(rhs.m_can_reverse)
        , m_role(rhs.m_role)
        , m_no_extrusion(rhs.m_no_extrusion)
    {}
ExtrusionPath() [6/8]
Slic3r::ExtrusionPath::ExtrusionPath (ExtrusionPath && rhs) inline
        : polyline(std::move(rhs.polyline))
        , overhang_degree(rhs.overhang_degree)
        , curve_degree(rhs.curve_degree)
        , mm3_per_mm(rhs.mm3_per_mm)
        , width(rhs.width)
        , height(rhs.height)
        , m_can_reverse(rhs.m_can_reverse)
        , m_role(rhs.m_role)
        , m_no_extrusion(rhs.m_no_extrusion)
    {}
ExtrusionPath() [7/8]
Slic3r::ExtrusionPath::ExtrusionPath (const Polyline & polyline, const ExtrusionPath & rhs) inline
        : polyline(polyline)
        , overhang_degree(rhs.overhang_degree)
        , curve_degree(rhs.curve_degree)
        , mm3_per_mm(rhs.mm3_per_mm)
        , width(rhs.width)
        , height(rhs.height)
        , m_can_reverse(rhs.m_can_reverse)
        , m_role(rhs.m_role)
        , m_no_extrusion(rhs.m_no_extrusion)
    {}
ExtrusionPath() [8/8]
Slic3r::ExtrusionPath::ExtrusionPath (Polyline && polyline, const ExtrusionPath & rhs) inline
        : polyline(std::move(polyline))
        , overhang_degree(rhs.overhang_degree)
        , curve_degree(rhs.curve_degree)
        , mm3_per_mm(rhs.mm3_per_mm)
        , width(rhs.width)
        , height(rhs.height)
        , m_can_reverse(rhs.m_can_reverse)
        , m_role(rhs.m_role)
        , m_no_extrusion(rhs.m_no_extrusion)
    {}
Member Function Documentation
_inflate_collection()
void Slic3r::ExtrusionPath::_inflate_collection (const Polylines & polylines, ExtrusionEntityCollection * collection) const private
{
    for (const Polyline &polyline : polylines)
        collection->entities.emplace_back(new ExtrusionPath(polyline, *this));
}
References Slic3r::ExtrusionEntityCollection::entities, and polyline.
Referenced by intersect_expolygons(), and subtract_expolygons().
as_polyline()
Polyline Slic3r::ExtrusionPath::as_polyline () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->polyline; }
References polyline.
as_polylines()
virtual Polylines Slic3r::ExtrusionEntity::as_polylines () const inline virtual inherited
{ Polylines dst; this->collect_polylines(dst); return dst; }
References Slic3r::ExtrusionEntity::collect_polylines().
Referenced by Slic3r::SupportMaterialInternal::remove_bridges_from_contacts().
can_reverse()
bool Slic3r::ExtrusionPath::can_reverse () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ return m_can_reverse; }
References m_can_reverse.
Referenced by Slic3r::ExtrusionMultiPath::ExtrusionMultiPath().
can_sort()
virtual bool Slic3r::ExtrusionEntity::can_sort () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return true; }//BBS: only used in ExtrusionEntityCollection
clip_end()
void Slic3r::ExtrusionPath::clip_end (double distance)
{
    this->polyline.clip_end(distance);
}
References Slic3r::Polyline::clip_end(), and polyline.
clone()
ExtrusionEntity * Slic3r::ExtrusionPath::clone () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return new ExtrusionPath(*this); }
References ExtrusionPath().
clone_move()
ExtrusionEntity * Slic3r::ExtrusionPath::clone_move () inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return new ExtrusionPath(std::move(*this)); }
References ExtrusionPath().
collect_points()
void Slic3r::ExtrusionPath::collect_points (Points & dst) const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ append(dst, this->polyline.points); }
References Slic3r::append(), and Slic3r::MultiPoint::points.
collect_polylines()
void Slic3r::ExtrusionPath::collect_polylines (Polylines & dst) const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ if (! this->polyline.empty()) dst.emplace_back(this->polyline); }
References Slic3r::MultiPoint::empty().
empty()
bool Slic3r::ExtrusionPath::empty () const inline
{ return this->polyline.empty(); }
References Slic3r::MultiPoint::empty().
Referenced by is_closed().
first_point()
const Point & Slic3r::ExtrusionPath::first_point () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->polyline.points.front(); }
References Slic3r::MultiPoint::points.
Referenced by Slic3r::GCode::_extrude().
get_curve_degree()
int Slic3r::ExtrusionPath::get_curve_degree () const inline
{
        return curve_degree;
    };
References curve_degree.
get_overhang_degree()
int Slic3r::ExtrusionPath::get_overhang_degree () const inline
{
        // only perimeter has overhang degree. Other return 0;
        if (is_perimeter(m_role) || is_bridge(m_role))
            return overhang_degree;
        return 0;
    };
References Slic3r::is_bridge(), Slic3r::is_perimeter(), m_role, and overhang_degree.
Referenced by Slic3r::GCode::_extrude().
intersect_expolygons()
void Slic3r::ExtrusionPath::intersect_expolygons (const ExPolygons & collection, ExtrusionEntityCollection * retval) const
{
    this->_inflate_collection(intersection_pl(Polylines{ polyline }, collection), retval);
}
References _inflate_collection(), Slic3r::intersection_pl(), and polyline.
is_closed()
bool Slic3r::ExtrusionPath::is_closed () const inline
{ return ! this->empty() && this->polyline.points.front() == this->polyline.points.back(); }
References empty(), and Slic3r::MultiPoint::points.
is_collection()
virtual bool Slic3r::ExtrusionEntity::is_collection () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return false; }
is_force_no_extrusion()
bool Slic3r::ExtrusionPath::is_force_no_extrusion () const inline
{ return m_no_extrusion; }
References m_no_extrusion.
Referenced by Slic3r::GCode::_extrude(), and Slic3r::to_json().
is_loop()
virtual bool Slic3r::ExtrusionEntity::is_loop () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionMultiPath, and Slic3r::ExtrusionLoop.
{ return false; }
Referenced by Slic3r::chain_extrusion_entities().
last_point()
const Point & Slic3r::ExtrusionPath::last_point () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->polyline.points.back(); }
References Slic3r::MultiPoint::points.
Referenced by Slic3r::GCode::_extrude(), and Slic3r::CurveAnalyzer::calculate_curvatures().
length()
double Slic3r::ExtrusionPath::length () const override virtual
Implements Slic3r::ExtrusionEntity.
{
    return this->polyline.length();
}
References Slic3r::MultiPoint::length(), and polyline.
Referenced by Slic3r::ExtrusionLoop::clip_end(), and total_volume().
min_mm3_per_mm()
double Slic3r::ExtrusionPath::min_mm3_per_mm () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->mm3_per_mm; }
References mm3_per_mm.
operator=() [1/2]
ExtrusionPath & Slic3r::ExtrusionPath::operator= (const ExtrusionPath & rhs) inline
{
        m_can_reverse = rhs.m_can_reverse;
        m_role = rhs.m_role;
        m_no_extrusion = rhs.m_no_extrusion;
        this->mm3_per_mm = rhs.mm3_per_mm;
        this->width = rhs.width;
        this->height = rhs.height;
        this->overhang_degree = rhs.overhang_degree;
        this->curve_degree = rhs.curve_degree;
        this->polyline = rhs.polyline;
        return *this;
    }
References curve_degree, height, m_can_reverse, m_no_extrusion, m_role, mm3_per_mm, overhang_degree, polyline, and width.
operator=() [2/2]
ExtrusionPath & Slic3r::ExtrusionPath::operator= (ExtrusionPath && rhs) inline
{
        m_can_reverse = rhs.m_can_reverse;
        m_role = rhs.m_role;
        m_no_extrusion = rhs.m_no_extrusion;
        this->mm3_per_mm = rhs.mm3_per_mm;
        this->width = rhs.width;
        this->height = rhs.height;
        this->overhang_degree = rhs.overhang_degree;
        this->curve_degree = rhs.curve_degree;
        this->polyline = std::move(rhs.polyline);
        return *this;
    }
References m_can_reverse, m_no_extrusion, and m_role.
polygons_covered_by_spacing() [1/2]
Polygons Slic3r::ExtrusionPath::polygons_covered_by_spacing (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_spacing(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_spacing().
polygons_covered_by_spacing() [2/2]
void Slic3r::ExtrusionPath::polygons_covered_by_spacing (Polygons & out, const float scaled_epsilon) const override virtual
Implements Slic3r::ExtrusionEntity.
{
    // Instantiating the Flow class to get the line spacing.
    // Don't know the nozzle diameter, setting to zero. It shall not matter it shall be optimized out by the compiler.
    bool bridge = is_bridge(this->role());
    // SoftFever: TODO Mac trigger assersion errors
//    assert(! bridge || this->width == this->height);
    auto flow = bridge ? Flow::bridging_flow(this->width, 0.f) : Flow(this->width, this->height, 0.f);
    polygons_append(out, offset(this->polyline, 0.5f * float(flow.scaled_spacing()) + scaled_epsilon));
}
References Slic3r::Flow::bridging_flow(), height, Slic3r::is_bridge(), Slic3r::offset(), Slic3r::polygons_append(), polyline, role(), and width.
Referenced by polygons_covered_by_spacing().
polygons_covered_by_width() [1/2]
Polygons Slic3r::ExtrusionPath::polygons_covered_by_width (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_width(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_width().
polygons_covered_by_width() [2/2]
void Slic3r::ExtrusionPath::polygons_covered_by_width (Polygons & out, const float scaled_epsilon) const override virtual
Implements Slic3r::ExtrusionEntity.
{
    polygons_append(out, offset(this->polyline, float(scale_(this->width/2)) + scaled_epsilon));
}
References Slic3r::offset(), out, Slic3r::polygons_append(), polyline, scale_, and width.
Referenced by polygons_covered_by_width().
reverse()
void Slic3r::ExtrusionPath::reverse () inline override virtual
Implements Slic3r::ExtrusionEntity.
{ this->polyline.reverse(); }
References Slic3r::Polyline::reverse().
role()
ExtrusionRole Slic3r::ExtrusionPath::role () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return m_role; }
References m_role.
Referenced by Slic3r::GCode::_extrude(), Slic3r::modulate_extrusion_by_overlapping_layers(), polygons_covered_by_spacing(), Slic3r::LayerRegion::simplify_path(), Slic3r::ExtrusionLoop::split_at(), and Slic3r::to_json().
role_to_string()
std::string Slic3r::ExtrusionEntity::role_to_string (ExtrusionRole role) static inherited
{
    switch (role) {
        case erNone                         : return L("Undefined");
        case erPerimeter                    : return L("Inner wall");
        case erExternalPerimeter            : return L("Outer wall");
        case erOverhangPerimeter            : return L("Overhang wall");
        case erInternalInfill               : return L("Sparse infill");
        case erSolidInfill                  : return L("Internal solid infill");
        case erTopSolidInfill               : return L("Top surface");
        case erBottomSurface                : return L("Bottom surface");
        case erIroning                      : return L("Ironing");
        case erBridgeInfill                 : return L("Bridge");
        case erInternalBridgeInfill         : return L("Internal Bridge");
        case erGapFill                      : return L("Gap infill");
        case erSkirt                        : return ("Skirt");
        case erBrim                         : return ("Brim");
        case erSupportMaterial              : return L("Support");
        case erSupportMaterialInterface     : return L("Support interface");
        case erSupportTransition            : return L("Support transition");
        case erWipeTower                    : return L("Prime tower");
        case erCustom                       : return L("Custom");
        case erMixed                        : return L("Multiple");
        default                             : assert(false);
    }
    return "";
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and Slic3r::ExtrusionEntity::role().
Referenced by Slic3r::WipeTowerWriter::WipeTowerWriter(), Slic3r::GCode::_do_export(), and Slic3r::GUI::GCodeViewer::render_legend().
set_curve_degree()
void Slic3r::ExtrusionPath::set_curve_degree (int curve) inline
{
        curve_degree = (curve < 0)?0:(curve > 10 ? 10 : curve);
    };
References curve_degree.
Referenced by Slic3r::CurveAnalyzer::calculate_curvatures().
set_extrusion_role()
void Slic3r::ExtrusionPath::set_extrusion_role (ExtrusionRole extrusion_role) inline
{ m_role = extrusion_role; }
References m_role.
Referenced by Slic3r::from_json().
set_force_no_extrusion()
void Slic3r::ExtrusionPath::set_force_no_extrusion (bool no_extrusion) inline
{ m_no_extrusion = no_extrusion; }
References m_no_extrusion.
Referenced by Slic3r::from_json().
set_overhang_degree()
void Slic3r::ExtrusionPath::set_overhang_degree (int overhang) inline
{
        if (is_perimeter(m_role) || is_bridge(m_role))
            overhang_degree = (overhang < 0)?0:(overhang > 10 ? 10 : overhang);
    };
References Slic3r::is_bridge(), Slic3r::is_perimeter(), m_role, and overhang_degree.
set_reverse()
void Slic3r::ExtrusionPath::set_reverse () inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ m_can_reverse = false; }
References m_can_reverse.
simplify()
void Slic3r::ExtrusionPath::simplify (double tolerance)
{
    this->polyline.simplify(tolerance);
}
References polyline, and Slic3r::Polyline::simplify().
Referenced by Slic3r::LayerRegion::simplify_path(), and Slic3r::Layer::simplify_support_path().
simplify_by_fitting_arc()
void Slic3r::ExtrusionPath::simplify_by_fitting_arc (double tolerance)
{
    this->polyline.simplify_by_fitting_arc(tolerance);
}
References polyline, and Slic3r::Polyline::simplify_by_fitting_arc().
Referenced by Slic3r::LayerRegion::simplify_path(), and Slic3r::Layer::simplify_support_path().
size()
size_t Slic3r::ExtrusionPath::size () const inline
{ return this->polyline.size(); }
References Slic3r::MultiPoint::size().
string_to_role()
ExtrusionRole Slic3r::ExtrusionEntity::string_to_role (const std::string_view role) static inherited
{
    if (role == L("Inner wall"))
        return erPerimeter;
    else if (role == L("Outer wall"))
        return erExternalPerimeter;
    else if (role == L("Overhang wall"))
        return erOverhangPerimeter;
    else if (role == L("Sparse infill"))
        return erInternalInfill;
    else if (role == L("Internal solid infill"))
        return erSolidInfill;
    else if (role == L("Top surface"))
        return erTopSolidInfill;
    else if (role == L("Bottom surface"))
        return erBottomSurface;
    else if (role == L("Ironing"))
        return erIroning;
    else if (role == L("Bridge"))
        return erBridgeInfill;
    else if (role == L("Internal Bridge"))
        return erInternalBridgeInfill;
    else if (role == L("Gap infill"))
        return erGapFill;
    else if (role == ("Skirt"))
        return erSkirt;
    else if (role == ("Brim"))
        return erBrim;
    else if (role == L("Support"))
        return erSupportMaterial;
    else if (role == L("Support interface"))
        return erSupportMaterialInterface;
    else if (role == L("Support transition"))
        return erSupportTransition;
    else if (role == L("Prime tower"))
        return erWipeTower;
    else if (role == L("Custom"))
        return erCustom;
    else if (role == L("Multiple"))
        return erMixed;
    else
        return erNone;
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and Slic3r::ExtrusionEntity::role().
Referenced by Slic3r::FanMover::_process_gcode_line(), and Slic3r::GCodeProcessor::process_tags().
subtract_expolygons()
void Slic3r::ExtrusionPath::subtract_expolygons (const ExPolygons & collection, ExtrusionEntityCollection * retval) const
{
    this->_inflate_collection(diff_pl(Polylines{ this->polyline }, collection), retval);
}
References _inflate_collection(), Slic3r::diff_pl(), and polyline.
total_volume()
double Slic3r::ExtrusionPath::total_volume () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return mm3_per_mm * unscale<double>(length()); }
References length(), and mm3_per_mm.
Member Data Documentation
curve_degree
int Slic3r::ExtrusionPath::curve_degree = 0
Referenced by Slic3r::from_json(), get_curve_degree(), operator=(), set_curve_degree(), Slic3r::ExtrusionLoop::split_at(), Slic3r::to_json(), and Slic3r::traverse_loops().
height
float Slic3r::ExtrusionPath::height
Referenced by Slic3r::GCode::_extrude(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::from_json(), Slic3r::modulate_extrusion_by_overlapping_layers(), operator=(), polygons_covered_by_spacing(), Slic3r::ExtrusionLoop::split_at(), Slic3r::thick_polyline_to_extrusion_paths(), Slic3r::thick_polyline_to_extrusion_paths_2(), Slic3r::to_json(), and Slic3r::traverse_loops().
m_can_reverse
bool Slic3r::ExtrusionPath::m_can_reverse = true private
Referenced by can_reverse(), operator=(), operator=(), and set_reverse().
m_no_extrusion
bool Slic3r::ExtrusionPath::m_no_extrusion = false private
Referenced by is_force_no_extrusion(), operator=(), operator=(), and set_force_no_extrusion().
m_role
ExtrusionRole Slic3r::ExtrusionPath::m_role private
Referenced by get_overhang_degree(), operator=(), operator=(), role(), set_extrusion_role(), and set_overhang_degree().
mm3_per_mm
double Slic3r::ExtrusionPath::mm3_per_mm
Referenced by Slic3r::GCode::_extrude(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::from_json(), min_mm3_per_mm(), Slic3r::modulate_extrusion_by_overlapping_layers(), operator=(), Slic3r::ExtrusionLoop::split_at(), Slic3r::thick_polyline_to_extrusion_paths(), Slic3r::thick_polyline_to_extrusion_paths_2(), Slic3r::to_json(), total_volume(), and Slic3r::traverse_loops().
overhang_degree
int Slic3r::ExtrusionPath::overhang_degree = 0
Referenced by Slic3r::from_json(), get_overhang_degree(), operator=(), set_overhang_degree(), Slic3r::ExtrusionLoop::split_at(), Slic3r::to_json(), and Slic3r::traverse_loops().
polyline
Polyline Slic3r::ExtrusionPath::polyline
Referenced by Slic3r::GCode::_extrude(), _inflate_collection(), Slic3r::_make_loops(), as_polyline(), Slic3r::CurveAnalyzer::calculate_curvatures(), clip_end(), Slic3r::ExtrusionLoop::clip_end(), Slic3r::ExtrusionMultiPath::collect_points(), Slic3r::ExtrusionLoop::collect_points(), Slic3r::GCode::extrude_path(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::extrusion_entities_append_loops(), Slic3r::extrusion_entities_append_loops_and_paths(), Slic3r::extrusion_entities_append_paths(), Slic3r::extrusion_entities_append_paths(), Slic3r::extrusionentity_extents(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::from_json(), Slic3r::FakeWipeTower::getFakeExtrusionPathsFromWipeTower(), intersect_expolygons(), length(), Slic3r::modulate_extrusion_by_overlapping_layers(), operator=(), polygons_covered_by_spacing(), polygons_covered_by_width(), simplify(), simplify_by_fitting_arc(), Slic3r::ExtrusionLoop::split_at(), Slic3r::ExtrusionLoop::split_at_vertex(), subtract_expolygons(), Slic3r::thick_polyline_to_extrusion_paths(), Slic3r::thick_polyline_to_extrusion_paths_2(), Slic3r::to_json(), and Slic3r::traverse_loops().
width
float Slic3r::ExtrusionPath::width
Referenced by Slic3r::GCode::_extrude(), Slic3r::ExtrusionQualityEstimator::estimate_extrusion_quality(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::extrusionentity_extents(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::from_json(), Slic3r::modulate_extrusion_by_overlapping_layers(), operator=(), polygons_covered_by_spacing(), polygons_covered_by_width(), Slic3r::ExtrusionLoop::split_at(), Slic3r::thick_polyline_to_extrusion_paths(), Slic3r::thick_polyline_to_extrusion_paths_2(), Slic3r::to_json(), and Slic3r::traverse_loops().
The documentation for this class was generated from the following files:
src/libslic3r/ExtrusionEntity.hpp
src/libslic3r/ExtrusionEntity.cpp