OrcaSlicer: Slic3r::sla::_ccr< true > Struct Reference
Slic3r::sla::_ccr< true > Struct Reference
#include <src/libslic3r/SLA/Concurrency.hpp>
Public Types
using SpinningMutex = execution::SpinningMutex< ExecutionTBB >
using BlockingMutex = execution::BlockingMutex< ExecutionTBB >
Static Public Member Functions
template<class It , class Fn >
static void for_each (It from, It to, Fn &&fn, size_t granularity=1)
template<class... Args>
static auto reduce (Args &&...args)
static size_t max_concurreny ()
Detailed Description
Member Typedef Documentation
BlockingMutex
using Slic3r::sla::_ccr< true >::BlockingMutex = execution::BlockingMutex<ExecutionTBB>
SpinningMutex
using Slic3r::sla::_ccr< true >::SpinningMutex = execution::SpinningMutex<ExecutionTBB>
Member Function Documentation
for_each()
template<class It , class Fn > static void Slic3r::sla::_ccr< true >::for_each (It from, It to, Fn && fn, size_t granularity = 1) inline static
    {
        execution::for_each(ex_tbb, from, to, std::forward<Fn>(fn), granularity);
    }
References Slic3r::ex_tbb, and Slic3r::execution::for_each().
Referenced by Slic3r::sla::make_layers(), and Slic3r::sla::SupportPointGenerator::project_onto_mesh().
max_concurreny()
static size_t Slic3r::sla::_ccr< true >::max_concurreny () inline static
    {
        return execution::max_concurrency(ex_tbb);
    }
References Slic3r::ex_tbb, and Slic3r::execution::max_concurrency().
reduce()
template<class... Args> static auto Slic3r::sla::_ccr< true >::reduce (Args &&... args) inline static
    {
        return execution::reduce(ex_tbb, std::forward<Args>(args)...);
    }
References Slic3r::ex_tbb, and Slic3r::execution::reduce().
The documentation for this struct was generated from the following file:
src/libslic3r/SLA/Concurrency.hpp