OrcaSlicer: BitmapChoiceRenderer Class Reference
BitmapChoiceRenderer Class Reference
#include <src/slic3r/GUI/ExtraRenderers.hpp>
Public Member Functions
BitmapChoiceRenderer (wxDataViewCellMode mode=wxDATAVIEW_CELL_EDITABLE, int align=wxALIGN_LEFT|wxALIGN_CENTER_VERTICAL)
bool SetValue (const wxVariant &value) override
bool GetValue (wxVariant &value) const override
virtual bool Render (wxRect cell, wxDC *dc, int state) override
virtual wxSize GetSize () const override
bool HasEditorCtrl () const override
wxWindow * CreateEditorCtrl (wxWindow *parent, wxRect labelRect, const wxVariant &value) override
bool GetValueFromEditorCtrl (wxWindow *ctrl, wxVariant &value) override
void set_can_create_editor_ctrl_function (std::function< bool()> can_create_fn)
void set_default_extruder_idx (std::function< int()> default_extruder_idx_fn)
void set_has_default_extruder (std::function< bool()> has_default_extruder_fn)
Private Attributes
DataViewBitmapText m_value
std::function< bool()> can_create_editor_ctrl { nullptr }
std::function< int()> get_default_extruder_idx { nullptr }
std::function< bool()> has_default_extruder { nullptr }
Detailed Description
Constructor & Destructor Documentation
BitmapChoiceRenderer()
BitmapChoiceRenderer::BitmapChoiceRenderer (wxDataViewCellMode mode = wxDATAVIEW_CELL_EDITABLE, int align = wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL) inline
      : wxDataViewCustomRenderer(wxT("DataViewBitmapText"), mode, align) {}
Member Function Documentation
CreateEditorCtrl()
wxWindow * BitmapChoiceRenderer::CreateEditorCtrl (wxWindow * parent, wxRect labelRect, const wxVariant & value) override
{
    if (can_create_editor_ctrl && !can_create_editor_ctrl())
        return nullptr;
    std::vector<wxBitmap*> icons = get_extruder_color_icons();
    if (icons.empty())
        return nullptr;
    DataViewBitmapText data;
    data << value;
    ::ComboBox *c_editor = new ::ComboBox(parent, wxID_ANY, wxEmptyString,
        labelRect.GetTopLeft(), wxSize(labelRect.GetWidth(), -1),
        0, nullptr, wxCB_READONLY | CB_NO_DROP_ICON | CB_NO_TEXT);
    c_editor->GetDropDown().SetUseContentWidth(true);
    if (has_default_extruder && has_default_extruder())
        c_editor->Append(_L("default"), *get_default_extruder_color_icon());
    for (size_t i = 0; i < icons.size(); i++)
        c_editor->Append(wxString::Format("%d", i+1), *icons[i]);
    if (has_default_extruder && has_default_extruder())
        c_editor->SetSelection(atoi(data.GetText().c_str()));
    else
        c_editor->SetSelection(atoi(data.GetText().c_str()) - 1);
#ifdef __linux__
    c_editor->Bind(wxEVT_COMBOBOX, [this](wxCommandEvent& evt) {
        // to avoid event propagation to other sidebar items
        evt.StopPropagation();
        // FinishEditing grabs new selection and triggers config update. We better call
        // it explicitly, automatic update on KILL_FOCUS didn't work on Linux.
        this->FinishEditing();
    });
#else
    // to avoid event propagation to other sidebar items
    c_editor->Bind(wxEVT_COMBOBOX, [](wxCommandEvent& evt) { evt.StopPropagation(); });
#endif
    return c_editor;
}
References _L, ComboBox::Append(), can_create_editor_ctrl, CB_NO_DROP_ICON, CB_NO_TEXT, get_default_extruder_color_icon(), get_extruder_color_icons(), ComboBox::GetDropDown(), DataViewBitmapText::GetText(), has_default_extruder, ComboBox::SetSelection(), and DropDown::SetUseContentWidth().
GetSize()
wxSize BitmapChoiceRenderer::GetSize () const override virtual
{
    wxSize sz;// = GetTextExtent(m_value.GetText());
    if (m_value.GetBitmap().IsOk()) {
        sz.x += m_value.GetBitmap().GetWidth() + 4;
        sz.y = m_value.GetBitmap().GetHeight() + 4;
    }
    return sz;
}
References DataViewBitmapText::GetBitmap(), and m_value.
GetValue()
bool BitmapChoiceRenderer::GetValue (wxVariant & value) const override
{
    value << m_value;
    return true;
}
References m_value.
GetValueFromEditorCtrl()
bool BitmapChoiceRenderer::GetValueFromEditorCtrl (wxWindow * ctrl, wxVariant & value) override
{
    ::ComboBox*c         = static_cast<::ComboBox *>(ctrl);
    int selection = c->GetSelection();
    if (selection < 0)
        return false;
    DataViewBitmapText bmpText;
    bmpText.SetText(c->GetString(selection));
    bmpText.SetBitmap(c->GetItemBitmap(selection));
    value << bmpText;
    return true;
}
References DataViewBitmapText::SetBitmap(), and DataViewBitmapText::SetText().
HasEditorCtrl()
bool BitmapChoiceRenderer::HasEditorCtrl () const inline override
{ return true; }
Render()
bool BitmapChoiceRenderer::Render (wxRect cell, wxDC * dc, int state) override virtual
{
//    int xoffset = 0;
    const wxBitmap& icon = m_value.GetBitmap();
    if (icon.IsOk())
    {
        dc->DrawBitmap(icon, rect.x, rect.y + (rect.height - icon.GetHeight()) / 2);
//        xoffset = icon.GetWidth() + 4;
        if (rect.height == 0)
          rect.height = icon.GetHeight();
    }
#ifdef _WIN32
    // workaround for Windows DarkMode : Don't respect to the state & wxDATAVIEW_CELL_SELECTED to avoid update of the text color
//    RenderText(m_value.GetText(), xoffset, rect, dc, state & wxDATAVIEW_CELL_SELECTED ? 0 : state);
#else
//    RenderText(m_value.GetText(), xoffset, rect, dc, state);
#endif
    return true;
}
References DataViewBitmapText::GetBitmap(), and m_value.
set_can_create_editor_ctrl_function()
void BitmapChoiceRenderer::set_can_create_editor_ctrl_function (std::function< bool()> can_create_fn) inline
{ can_create_editor_ctrl = can_create_fn; }
References can_create_editor_ctrl.
set_default_extruder_idx()
void BitmapChoiceRenderer::set_default_extruder_idx (std::function< int()> default_extruder_idx_fn) inline
{ get_default_extruder_idx = default_extruder_idx_fn; }
References get_default_extruder_idx.
set_has_default_extruder()
void BitmapChoiceRenderer::set_has_default_extruder (std::function< bool()> has_default_extruder_fn) inline
{ has_default_extruder = has_default_extruder_fn; }
References has_default_extruder.
SetValue()
bool BitmapChoiceRenderer::SetValue (const wxVariant & value) override
{
    m_value << value;
    return true;
}
References m_value.
Member Data Documentation
can_create_editor_ctrl
std::function<bool()> BitmapChoiceRenderer::can_create_editor_ctrl { nullptr } private
Referenced by CreateEditorCtrl(), and set_can_create_editor_ctrl_function().
get_default_extruder_idx
std::function<int()> BitmapChoiceRenderer::get_default_extruder_idx { nullptr } private
Referenced by set_default_extruder_idx().
has_default_extruder
std::function<bool()> BitmapChoiceRenderer::has_default_extruder { nullptr } private
Referenced by CreateEditorCtrl(), and set_has_default_extruder().
m_value
DataViewBitmapText BitmapChoiceRenderer::m_value private
Referenced by GetSize(), GetValue(), Render(), and SetValue().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ExtraRenderers.hpp
src/slic3r/GUI/ExtraRenderers.cpp