OrcaSlicer: Slic3r::GUI::SliceInfoPanel Class Reference
Slic3r::GUI::SliceInfoPanel Class Reference
#include <src/slic3r/GUI/SliceInfoPanel.hpp>
Public Member Functions
SliceInfoPanel (wxWindow *parent, wxBitmap &prediction, wxBitmap &cost, wxBitmap &print, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL, const wxString &name=wxEmptyString)
~SliceInfoPanel ()
void SetImages (wxBitmap &prediction, wxBitmap &cost, wxBitmap &printing)
void on_subtask_print (wxCommandEvent &evt)
void on_thumbnail_enter (wxMouseEvent &event)
void on_thumbnail_leave (wxMouseEvent &event)
void on_mouse_enter (wxMouseEvent &event)
void on_mouse_leave (wxMouseEvent &event)
void on_webrequest_state (wxWebRequestEvent &evt)
void update (BBLSliceInfo *info)
void msw_rescale ()
Protected Attributes
wxWebRequest web_request
std::shared_ptr< ImageTransientPopup > m_thumbnail_popup
std::shared_ptr< SliceInfoPopup > m_slice_info_popup
wxImage m_thumbnail_img
wxBoxSizer * m_item_top_sizer
wxStaticBitmap * m_bmp_item_thumbnail
wxStaticBitmap * m_bmp_item_prediction
wxStaticBitmap * m_bmp_item_print
wxStaticText * m_text_item_prediction
wxStaticBitmap * m_bmp_item_cost
wxStaticText * m_text_item_cost
wxGridSizer * m_filament_info_sizer
wxStaticText * m_text_plate_index
Detailed Description
Constructor & Destructor Documentation
SliceInfoPanel()
Slic3r::GUI::SliceInfoPanel::SliceInfoPanel (wxWindow * parent, wxBitmap & prediction, wxBitmap & cost, wxBitmap & print, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL, const wxString & name = wxEmptyString)
    : wxPanel(parent, id, pos, size, style, name)
{
    this->SetBackgroundColour(*wxWHITE);
    m_item_top_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_bmp_item_thumbnail = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBU_AUTODRAW | 0);
    m_bmp_item_thumbnail->SetMinSize(THUMBNAIL_SIZE);
    m_bmp_item_thumbnail->SetSize(THUMBNAIL_SIZE);
    m_item_top_sizer->Add(m_bmp_item_thumbnail, 0, wxALL, 0);
    wxBoxSizer *m_item_content_sizer;
    m_item_content_sizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_item_info_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_bmp_item_prediction = new wxStaticBitmap(this, wxID_ANY, prediction);
    m_bmp_item_prediction->SetMinSize(ICON_SIZE);
    m_bmp_item_prediction->SetSize(ICON_SIZE);
    m_item_info_sizer->Add(m_bmp_item_prediction, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    m_text_item_prediction = new wxStaticText(this, wxID_ANY, "", wxDefaultPosition, wxSize(FromDIP(60), -1));
    m_text_item_prediction->Wrap(-1);
    m_item_info_sizer->Add(m_text_item_prediction, 1, wxALIGN_CENTER_VERTICAL | wxALL, 0);
    m_bmp_item_cost = new wxStaticBitmap(this, wxID_ANY, cost);
    m_bmp_item_cost->SetMinSize(ICON_SIZE);
    m_bmp_item_cost->SetSize(ICON_SIZE);
    m_item_info_sizer->Add(m_bmp_item_cost, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    m_text_item_cost = new wxStaticText(this, wxID_ANY, "", wxDefaultPosition, wxSize(FromDIP(35), -1));
    m_text_item_cost->Wrap(-1);
    m_item_info_sizer->Add(m_text_item_cost, 1, wxALIGN_CENTER_VERTICAL | wxALL, 0);
    m_item_content_sizer->Add(m_item_info_sizer, 0, wxEXPAND, 0);
    wxGridSizer *m_filament_info_sizer = new wxGridSizer(0, 3, 0, 8);
    m_item_content_sizer->Add(m_filament_info_sizer, 0, wxEXPAND, 0);
    m_item_top_sizer->Add(m_item_content_sizer, 0, wxEXPAND, 0);
    wxBoxSizer *m_item_right_sizer;
    m_item_right_sizer = new wxBoxSizer(wxVERTICAL);
    m_bmp_item_print = new wxStaticBitmap(this, wxID_ANY, print, wxDefaultPosition, wxDefaultSize, wxBU_AUTODRAW | 0);
    m_bmp_item_print->SetMinSize(PRINT_ICON_SIZE);
    m_bmp_item_print->SetSize(PRINT_ICON_SIZE);
    m_item_right_sizer->Add(m_bmp_item_print, 0, wxALL, FromDIP(5));
    m_item_right_sizer->Add(0, 0, 1, wxEXPAND, FromDIP(5));
    m_text_plate_index = new wxStaticText(this, wxID_ANY, "");
    m_text_plate_index->Wrap(-1);
    m_text_plate_index->SetForegroundColour(wxColour(107, 107, 107));
    m_item_right_sizer->Add(m_text_plate_index, 0, wxALIGN_RIGHT | wxALL, FromDIP(5));
    m_item_top_sizer->Add(m_item_right_sizer, 0, wxEXPAND, 0);
    this->SetSizer(m_item_top_sizer);
    this->Layout();
    Bind(wxEVT_WEBREQUEST_STATE, &SliceInfoPanel::on_webrequest_state, this);
    // Connect Events
    m_bmp_item_thumbnail->Connect(wxEVT_ENTER_WINDOW, wxMouseEventHandler(SliceInfoPanel::on_thumbnail_enter), NULL, this);
    m_bmp_item_thumbnail->Connect(wxEVT_LEAVE_WINDOW, wxMouseEventHandler(SliceInfoPanel::on_thumbnail_leave), NULL, this);
    m_bmp_item_print->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(SliceInfoPanel::on_subtask_print), NULL, this);
}
References ICON_SIZE, m_bmp_item_cost, m_bmp_item_prediction, m_bmp_item_print, m_bmp_item_thumbnail, m_filament_info_sizer, m_item_top_sizer, m_text_item_cost, m_text_item_prediction, m_text_plate_index, NULL, on_subtask_print(), on_thumbnail_enter(), on_thumbnail_leave(), on_webrequest_state(), PRINT_ICON_SIZE, Slic3r::THUMBNAIL_SIZE, and wxStaticText.
~SliceInfoPanel()
Slic3r::GUI::SliceInfoPanel::~SliceInfoPanel ()
{
    // Disconnect Events
    m_bmp_item_thumbnail->Disconnect(wxEVT_ENTER_WINDOW, wxMouseEventHandler(SliceInfoPanel::on_thumbnail_enter), NULL, this);
    m_bmp_item_thumbnail->Disconnect(wxEVT_LEAVE_WINDOW, wxMouseEventHandler(SliceInfoPanel::on_thumbnail_leave), NULL, this);
    m_bmp_item_print->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(SliceInfoPanel::on_subtask_print), NULL, this);
}
References m_bmp_item_print, m_bmp_item_thumbnail, NULL, on_subtask_print(), on_thumbnail_enter(), and on_thumbnail_leave().
Member Function Documentation
msw_rescale()
void Slic3r::GUI::SliceInfoPanel::msw_rescale ()
{
    m_bmp_item_prediction->SetMinSize(ICON_SIZE);
    m_bmp_item_prediction->SetSize(ICON_SIZE);
    m_bmp_item_cost->SetMinSize(ICON_SIZE);
    m_bmp_item_cost->SetSize(ICON_SIZE);
    m_bmp_item_print->SetMinSize(PRINT_ICON_SIZE);
    m_bmp_item_print->SetSize(PRINT_ICON_SIZE);
    this->Layout();
}
References ICON_SIZE, m_bmp_item_cost, m_bmp_item_prediction, m_bmp_item_print, and PRINT_ICON_SIZE.
on_mouse_enter()
void Slic3r::GUI::SliceInfoPanel::on_mouse_enter (wxMouseEvent & event)
{ ; }
on_mouse_leave()
void Slic3r::GUI::SliceInfoPanel::on_mouse_leave (wxMouseEvent & event)
{ ; }
on_subtask_print()
void Slic3r::GUI::SliceInfoPanel::on_subtask_print (wxCommandEvent & evt)
{
    ;
}
Referenced by SliceInfoPanel(), and ~SliceInfoPanel().
on_thumbnail_enter()
void Slic3r::GUI::SliceInfoPanel::on_thumbnail_enter (wxMouseEvent & event)
{
    /*
    m_slice_info_popup = std::make_shared<SliceInfoPopup>(this);
    wxWindow *ctrl    = (wxWindow *) event.GetEventObject();
    wxPoint   pos     = ctrl->ClientToScreen(wxPoint(0, 0));
    wxSize    sz      = ctrl->GetSize();
    m_slice_info_popup->Position(pos, sz);
    m_slice_info_popup->Popup();
    */
}
Referenced by SliceInfoPanel(), and ~SliceInfoPanel().
on_thumbnail_leave()
void Slic3r::GUI::SliceInfoPanel::on_thumbnail_leave (wxMouseEvent & event)
{
    if (m_thumbnail_popup) { m_thumbnail_popup->Hide(); }
}
References m_thumbnail_popup.
Referenced by SliceInfoPanel(), and ~SliceInfoPanel().
on_webrequest_state()
void Slic3r::GUI::SliceInfoPanel::on_webrequest_state (wxWebRequestEvent & evt)
{
    BOOST_LOG_TRIVIAL(trace) << "monitor: sub_task_panel web request state = " << evt.GetState();
    switch (evt.GetState()) {
    case wxWebRequest::State_Completed: {
        m_thumbnail_img    = *evt.GetResponse().GetStream();
        wxImage resize_img = m_thumbnail_img.Scale(m_bmp_item_thumbnail->GetSize().x, m_bmp_item_thumbnail->GetSize().y);
        m_bmp_item_thumbnail->SetBitmap(resize_img);
        break;
    }
    case wxWebRequest::State_Failed: {
        break;
    }
    case wxWebRequest::State_Cancelled:
    case wxWebRequest::State_Unauthorized:
    case wxWebRequest::State_Active:
    case wxWebRequest::State_Idle: break;
    default: break;
    }
}
References m_bmp_item_thumbnail, m_thumbnail_img, and Slic3r::trace().
Referenced by SliceInfoPanel().
SetImages()
void Slic3r::GUI::SliceInfoPanel::SetImages (wxBitmap & prediction, wxBitmap & cost, wxBitmap & printing)
{
    m_bmp_item_prediction->SetBitmap(prediction);
    m_bmp_item_cost->SetBitmap(cost);
    m_bmp_item_print->SetBitmap(printing);
}
References m_bmp_item_cost, m_bmp_item_prediction, and m_bmp_item_print.
update()
void Slic3r::GUI::SliceInfoPanel::update (BBLSliceInfo * info)
{
    wxString prediction = wxString::Format("%s", get_bbl_time_dhms(info->prediction));
    m_text_item_prediction->SetLabelText(prediction);
    wxString weight = wxString::Format("%.2fg", info->weight);
    m_text_item_cost->SetLabelText(weight);
    m_text_plate_index->SetLabelText(info->index);
    if (web_request.IsOk()) web_request.Cancel();
    if (!info->thumbnail_url.empty()) {
        web_request = wxWebSession::GetDefault().CreateRequest(this, info->thumbnail_url);
        BOOST_LOG_TRIVIAL(trace) << "slice info: start reqeust thumbnail, url = " << info->thumbnail_url;
        web_request.Start();
    }
    this->Layout();
}
References Slic3r::get_bbl_time_dhms(), Slic3r::BBLSliceInfo::index, m_text_item_cost, m_text_item_prediction, m_text_plate_index, Slic3r::BBLSliceInfo::prediction, Slic3r::BBLSliceInfo::thumbnail_url, Slic3r::trace(), web_request, and Slic3r::BBLSliceInfo::weight.
Member Data Documentation
m_bmp_item_cost
wxStaticBitmap* Slic3r::GUI::SliceInfoPanel::m_bmp_item_cost protected
Referenced by SliceInfoPanel(), msw_rescale(), and SetImages().
m_bmp_item_prediction
wxStaticBitmap* Slic3r::GUI::SliceInfoPanel::m_bmp_item_prediction protected
Referenced by SliceInfoPanel(), msw_rescale(), and SetImages().
m_bmp_item_print
wxStaticBitmap* Slic3r::GUI::SliceInfoPanel::m_bmp_item_print protected
Referenced by SliceInfoPanel(), ~SliceInfoPanel(), msw_rescale(), and SetImages().
m_bmp_item_thumbnail
wxStaticBitmap* Slic3r::GUI::SliceInfoPanel::m_bmp_item_thumbnail protected
Referenced by SliceInfoPanel(), ~SliceInfoPanel(), and on_webrequest_state().
m_filament_info_sizer
wxGridSizer* Slic3r::GUI::SliceInfoPanel::m_filament_info_sizer protected
Referenced by SliceInfoPanel().
m_item_top_sizer
wxBoxSizer* Slic3r::GUI::SliceInfoPanel::m_item_top_sizer protected
Referenced by SliceInfoPanel().
m_slice_info_popup
std::shared_ptr<SliceInfoPopup> Slic3r::GUI::SliceInfoPanel::m_slice_info_popup protected
m_text_item_cost
wxStaticText* Slic3r::GUI::SliceInfoPanel::m_text_item_cost protected
Referenced by SliceInfoPanel(), and update().
m_text_item_prediction
wxStaticText* Slic3r::GUI::SliceInfoPanel::m_text_item_prediction protected
Referenced by SliceInfoPanel(), and update().
m_text_plate_index
wxStaticText* Slic3r::GUI::SliceInfoPanel::m_text_plate_index protected
Referenced by SliceInfoPanel(), and update().
m_thumbnail_img
wxImage Slic3r::GUI::SliceInfoPanel::m_thumbnail_img protected
Referenced by on_webrequest_state().
m_thumbnail_popup
std::shared_ptr<ImageTransientPopup> Slic3r::GUI::SliceInfoPanel::m_thumbnail_popup protected
Referenced by on_thumbnail_leave().
web_request
wxWebRequest Slic3r::GUI::SliceInfoPanel::web_request protected
Referenced by update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SliceInfoPanel.hpp
src/slic3r/GUI/SliceInfoPanel.cpp