OrcaSlicer: Slic3r::Wipe Class Reference
Slic3r::Wipe Class Reference
#include <src/libslic3r/GCode.hpp>
Public Member Functions
Wipe ()
bool has_path () const
void reset_path ()
std::string wipe (GCode &gcodegen, bool toolchange=false, bool is_last=false)
Public Attributes
bool enable
Polyline path
Detailed Description
Constructor & Destructor Documentation
Wipe()
Slic3r::Wipe::Wipe () inline
: enable(false) {}
Member Function Documentation
has_path()
bool Slic3r::Wipe::has_path () const inline
{ return !this->path.points.empty(); }
References Slic3r::MultiPoint::points.
reset_path()
void Slic3r::Wipe::reset_path () inline
{ this->path = Polyline(); }
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), and wipe().
wipe()
std::string Slic3r::Wipe::wipe (GCode & gcodegen, bool toolchange = false, bool is_last = false)
    {
        std::string gcode;
        /*  Reduce feedrate a bit; travel speed is often too high to move on existing material.
            Too fast = ripping of existing material; too slow = short wipe path, thus more blob.  */
        double _wipe_speed = gcodegen.config().get_abs_value("wipe_speed");// gcodegen.writer().config.travel_speed.value * 0.8;
        if(gcodegen.config().role_based_wipe_speed)
            _wipe_speed = gcodegen.writer().get_current_speed() / 60.0;
        if(_wipe_speed < 10)
            _wipe_speed = 10;
        // get the retraction length
        double length = toolchange
            ? gcodegen.writer().extruder()->retract_length_toolchange()
            : gcodegen.writer().extruder()->retraction_length();
        // Shorten the retraction length by the amount already retracted before wipe.
        length *= (1. - gcodegen.writer().extruder()->retract_before_wipe());
        //SoftFever: allow 100% retract before wipe
        if (length >= 0)
        {
            /*  Calculate how long we need to travel in order to consume the required
                amount of retraction. In other words, how far do we move in XY at wipe_speed
                for the time needed to consume retraction_length at retraction_speed?  */
            // BBS
            double wipe_dist = scale_(gcodegen.config().wipe_distance.get_at(gcodegen.writer().extruder()->id()));
            /*  Take the stored wipe path and replace first point with the current actual position
                (they might be different, for example, in case of loop clipping).  */
            Polyline wipe_path;
            wipe_path.append(gcodegen.last_pos());
            wipe_path.append(
                this->path.points.begin() + 1,
                this->path.points.end()
            );
            wipe_path.clip_end(wipe_path.length() - wipe_dist);
            // subdivide the retraction in segments
            if (!wipe_path.empty()) {
                // BBS. Handle short path case.
                if (wipe_path.length() < wipe_dist) {
                    wipe_dist = wipe_path.length();
                    //BBS: avoid to divide 0
                    wipe_dist = wipe_dist < EPSILON ? EPSILON : wipe_dist;
                }
                // add tag for processor
                gcode += ";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Wipe_Start) + "\n";
                //BBS: don't need to enable cooling makers when this is the last wipe. Because no more cooling layer will clean this "_WIPE"
                //Softfever:
                std::string cooling_mark = "";
                if (gcodegen.enable_cooling_markers() && !is_last)
                    cooling_mark = /*gcodegen.config().role_based_wipe_speed ? ";_EXTERNAL_PERIMETER" : */";_WIPE";
                gcode += gcodegen.writer().set_speed(_wipe_speed * 60, "", cooling_mark);
                for (const Line& line : wipe_path.lines()) {
                    double segment_length = line.length();
                    /*  Reduce retraction length a bit to avoid effective retraction speed to be greater than the configured one
                        due to rounding (TODO: test and/or better math for this)  */
                    double dE = length * (segment_length / wipe_dist) * 0.95;
                    //BBS: fix this FIXME
                    //FIXME one shall not generate the unnecessary G1 Fxxx commands, here wipe_speed is a constant inside this cycle.
                    // Is it here for the cooling markers? Or should it be outside of the cycle?
                    //gcode += gcodegen.writer().set_speed(wipe_speed * 60, "", gcodegen.enable_cooling_markers() ? ";_WIPE" : "");
                    gcode += gcodegen.writer().extrude_to_xy(
                        gcodegen.point_to_gcode(line.b),
                        -dE,
                        "wipe and retract"
                    );
                }
                // add tag for processor
                gcode += ";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Wipe_End) + "\n";
                gcodegen.set_last_pos(wipe_path.points.back());
            }
            // prevent wiping again on same path
            this->reset_path();
        }
        return gcode;
    }
References Slic3r::Polyline::append(), Slic3r::Polyline::clip_end(), Slic3r::GCode::config(), Slic3r::MultiPoint::empty(), Slic3r::GCode::enable_cooling_markers(), EPSILON, Slic3r::GCodeWriter::extrude_to_xy(), Slic3r::GCodeWriter::extruder(), Slic3r::GCodeWriter::get_current_speed(), Slic3r::Extruder::id(), Slic3r::GCode::last_pos(), Slic3r::MultiPoint::length(), Slic3r::length(), Slic3r::Polyline::lines(), path, Slic3r::GCode::point_to_gcode(), Slic3r::MultiPoint::points, Slic3r::GCodeProcessor::reserved_tag(), reset_path(), Slic3r::Extruder::retract_before_wipe(), Slic3r::Extruder::retract_length_toolchange(), Slic3r::Extruder::retraction_length(), scale_, Slic3r::segment_length(), Slic3r::GCode::set_last_pos(), Slic3r::GCodeWriter::set_speed(), Slic3r::GCodeProcessor::Wipe_End, Slic3r::GCodeProcessor::Wipe_Start, and Slic3r::GCode::writer().
Member Data Documentation
enable
bool Slic3r::Wipe::enable
path
Polyline Slic3r::Wipe::path
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), and wipe().
The documentation for this class was generated from the following files:
src/libslic3r/GCode.hpp
src/libslic3r/GCode.cpp