OrcaSlicer: hidapi API
hidapi API
Modules
Helpers
triangulator_t Class
Namespaces
namespace cdt::detail
namespace cdt::detail::defaults
Classes
struct cdt::vertex_insertion_order_t
struct cdt::super_geometry_type_t
Enum of what type of geometry used to embed triangulation into.
struct cdt::action_on_intersecting_constraint_edges_t
class cdt::triangulator_t< T, TNearPointLocator >
Typedefs
typedef unsigned short cdt::layer_depth_t
typedef layer_depth_t cdt::boundary_overlap_count_t
Functions
int HID_API_EXPORT HID_API_CALL hid_init (void)
Initialize the HIDAPI library.
int HID_API_EXPORT HID_API_CALL hid_exit (void)
Finalize the HIDAPI library.
struct hid_device_info HID_API_EXPORT *HID_API_CALL hid_enumerate (unsigned short vendor_id, unsigned short product_id)
Enumerate the HID Devices.
void HID_API_EXPORT HID_API_CALL hid_free_enumeration (struct hid_device_info *devs)
Free an enumeration Linked List.
HID_API_EXPORT hid_device *HID_API_CALL hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t *serial_number)
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
HID_API_EXPORT hid_device *HID_API_CALL hid_open_path (const char *path)
Open a HID device by its path name.
int HID_API_EXPORT HID_API_CALL hid_write (hid_device *dev, const unsigned char *data, size_t length)
Write an Output report to a HID device.
int HID_API_EXPORT HID_API_CALL hid_read_timeout (hid_device *dev, unsigned char *data, size_t length, int milliseconds)
Read an Input report from a HID device with timeout.
int HID_API_EXPORT HID_API_CALL hid_read (hid_device *dev, unsigned char *data, size_t length)
Read an Input report from a HID device.
int HID_API_EXPORT HID_API_CALL hid_set_nonblocking (hid_device *dev, int nonblock)
Set the device handle to be non-blocking.
int HID_API_EXPORT HID_API_CALL hid_send_feature_report (hid_device *dev, const unsigned char *data, size_t length)
Send a Feature report to the device.
int HID_API_EXPORT HID_API_CALL hid_get_feature_report (hid_device *dev, unsigned char *data, size_t length)
Get a feature report from a HID device.
void HID_API_EXPORT HID_API_CALL hid_close (hid_device *dev)
Close a HID device.
int HID_API_EXPORT_CALL hid_get_manufacturer_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Manufacturer String from a HID device.
int HID_API_EXPORT_CALL hid_get_product_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Product String from a HID device.
int HID_API_EXPORT_CALL hid_get_serial_number_string (hid_device *dev, wchar_t *string, size_t maxlen)
Get The Serial Number String from a HID device.
int HID_API_EXPORT_CALL hid_get_indexed_string (hid_device *dev, int string_index, wchar_t *string, size_t maxlen)
Get a string from a HID device, based on its string index.
HID_API_EXPORT const wchar_t *HID_API_CALL hid_error (hid_device *dev)
Get a string describing the last error which occurred.
Detailed Description
Contains API for constrained and conforming Delaunay triangulations
Class Documentation
cdt::vertex_insertion_order_t
struct cdt::vertex_insertion_order_t
Enum of strategies specifying order in which a range of vertices is inserted
Note
vertex_insertion_order_t::RANDOM will only randomize order of inserting in triangulation, vertex indices will be preserved as they were specified in the final triangulation
Public Types
enum Enum { RANDOM , AS_GIVEN }
Member Enumeration Documentation
Enum
enum cdt::vertex_insertion_order_t::Enum
The Enum itself
Note
needed to pre c++11 compilers that don't support 'class enum'
Enumerator
RANDOM
vertices will be inserted in random order
AS_GIVEN
vertices will be inserted in the same order as provided
              {
        RANDOM,
        AS_GIVEN,
    };
cdt::super_geometry_type_t
struct cdt::super_geometry_type_t
Enum of what type of geometry used to embed triangulation into.
Public Types
enum Enum { SUPER_TRIANGLE , CUSTOM }
Member Enumeration Documentation
Enum
enum cdt::super_geometry_type_t::Enum
The Enum itself
Note
needed to pre c++11 compilers that don't support 'class enum'
Enumerator
SUPER_TRIANGLE
conventional super-triangle
CUSTOM
user-specified custom geometry (e.g., grid)
              {
        SUPER_TRIANGLE,
        CUSTOM,
    };
cdt::action_on_intersecting_constraint_edges_t
struct cdt::action_on_intersecting_constraint_edges_t
Enum of strategies for treating intersecting constraint edges
Public Types
enum Enum { IGNORE , RESOLVE }
Member Enumeration Documentation
Enum
enum cdt::action_on_intersecting_constraint_edges_t::Enum
The Enum itself
Note
needed to pre c++11 compilers that don't support 'class enum'
Enumerator
IGNORE
constraint edge intersections are not checked
RESOLVE
constraint edge intersections are resolved
              {
        IGNORE,
        RESOLVE,
    };
cdt::triangulator_t
class cdt::triangulator_t
template<typename T, typename TNearPointLocator = locator_kdtree_t<T>>
class cdt::triangulator_t< T, TNearPointLocator >
Data structure representing a 2D constrained Delaunay triangulation
Template Parameters
T type of vertex coordinates (e.g., float, double)
TNearPointLocator class providing locating near point for efficiently inserting new points. Provides methods: 'add_point(vPos, iV)' and 'nearPoint(vPos) -> iV'
Public Member Functions
triangulator_t ()
Default constructor.
triangulator_t (vertex_insertion_order_t::Enum vertexInsertionOrder)
triangulator_t (vertex_insertion_order_t::Enum vertexInsertionOrder, action_on_intersecting_constraint_edges_t::Enum intersectingEdgesStrategy, T minDistToConstraintEdge)
triangulator_t (vertex_insertion_order_t::Enum vertexInsertionOrder, const TNearPointLocator &nearPtLocator, action_on_intersecting_constraint_edges_t::Enum intersectingEdgesStrategy, T minDistToConstraintEdge)
template<typename TVertexIter , typename TGetVertexCoordX , typename TGetVertexCoordY >
void insert_vertices (TVertexIter first, TVertexIter last, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord)
void insert_vertices (const std::vector< vec2_< T > > &vertices)
template<typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd >
void insert_edges (TEdgeIter first, TEdgeIter last, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd)
void insert_edges (const std::vector< edge_t > &edges)
std::tuple< std::uint32_t, std::uint32_t, std::uint32_t > get_intersected_triangle (const std::uint32_t iA, const std::vector< std::uint32_t > &candidates, const vec2_< T > &a, const vec2_< T > &b, const T orientationTolerance) const
std::stack< std::uint32_t > insert_point_on_edge (const std::uint32_t v, const std::uint32_t iT1, const std::uint32_t iT2)
Returns indices of four resulting triangles.
std::array< std::uint32_t, 2 > trianglesAt (const vec2_< T > &pos) const
template<typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd >
void conform_to_edges (TEdgeIter first, TEdgeIter last, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd)
std::tuple< std::uint32_t, std::uint32_t, std::uint32_t > TintersectedTriangle (const std::uint32_t iA, const std::vector< std::uint32_t > &candidates, const vec2_< T > &a, const vec2_< T > &b, const T orientationTolerance=T(0)) const
std::stack< std::uint32_t > insert_point_in_triangle (const std::uint32_t v, const std::uint32_t iT)
Returns indices of three resulting triangles.
std::array< std::uint32_t, 2 > walking_search_triangle_at (const vec2_< T > &pos) const
void conform_to_edges (const std::vector< edge_t > &edges)
void eraseSuperTriangle ()
void erase_outer_triangles ()
Erase triangles outside of constrained boundary using growing.
void erase_outer_triangles_and_holes ()
void initialise_with_custom_supergeometry ()
bool is_finalized () const
std::vector< layer_depth_t > calculate_triangle_depths () const
void do_edgeflip (std::uint32_t iT, std::uint32_t iTopo)
void remove_triangles (const std::unordered_set< std::uint32_t > &removedTriangles)
Public Attributes
std::vector< vec2_< T > > vertices
triangulation's vertices
std::vector< triangle_t > triangles
triangulation's triangles
std::unordered_set< edge_t > fixedEdges
triangulation's constraints (fixed edges)
std::vector< std::vector< std::uint32_t > > vertTris
std::unordered_map< edge_t, boundary_overlap_count_t > overlapCount
std::unordered_map< edge_t, std::vector< edge_t > > pieceToOriginals
Private Member Functions
void add_super_triangle (const box2d_t< T > &box)
void create_vertex (const vec2_< T > &pos, const std::vector< std::uint32_t > &tris)
void insert_vertex (std::uint32_t iVert)
void enforce_delaunay_property_using_edge_flips (const vec2_< T > &v, std::uint32_t iVert, std::stack< std::uint32_t > &triStack)
std::vector< edge_t > insert_vertex_and_flip_fixed_edges (std::uint32_t iVert)
Flip fixed edges and return a list of flipped fixed edges.
void insert_edge (edge_t edge, edge_t originalEdge)
void conform_to_edge (edge_t edge, std::vector< edge_t > originalEdges, boundary_overlap_count_t overlaps)
std::uint32_t walk_triangles (std::uint32_t startVertex, const vec2_< T > &pos) const
bool check_is_edgeflip_needed (const vec2_< T > &v, std::uint32_t iV, std::uint32_t iV1, std::uint32_t iV2, std::uint32_t iV3) const
bool check_is_edgeflip_needed (const vec2_< T > &v, std::uint32_t iT, std::uint32_t iTopo, std::uint32_t iVert) const
void change_neighbour (std::uint32_t iT, std::uint32_t oldNeighbor, std::uint32_t newNeighbor)
void change_neighbour (std::uint32_t iT, std::uint32_t iVedge1, std::uint32_t iVedge2, std::uint32_t newNeighbor)
void add_adjacent_triangle (std::uint32_t iVertex, std::uint32_t iTriangle)
void add_adjacent_triangles (std::uint32_t iVertex, std::uint32_t iT1, std::uint32_t iT2, std::uint32_t iT3)
void add_adjacent_triangles (std::uint32_t iVertex, std::uint32_t iT1, std::uint32_t iT2, std::uint32_t iT3, std::uint32_t iT4)
void remove_adjacent_triangle (std::uint32_t iVertex, std::uint32_t iTriangle)
std::uint32_t triangulate_pseudo_polygon (std::uint32_t ia, std::uint32_t ib, std::vector< std::uint32_t >::const_iterator pointsFirst, std::vector< std::uint32_t >::const_iterator pointsLast)
std::uint32_t find_delaunay_point (std::uint32_t ia, std::uint32_t ib, std::vector< std::uint32_t >::const_iterator pointsFirst, std::vector< std::uint32_t >::const_iterator pointsLast) const
std::uint32_t pseudo_polygon_outer_triangle (std::uint32_t ia, std::uint32_t ib) const
std::uint32_t add_triangle (const triangle_t &t)
std::uint32_t add_triangle ()
void finalise_triangulation (const std::unordered_set< std::uint32_t > &removedTriangles)
std::unordered_set< std::uint32_t > grow_to_boundary (std::stack< std::uint32_t > seeds) const
void fixEdge (const edge_t &edge, const boundary_overlap_count_t overlaps)
void fixEdge (const edge_t &edge)
void fixEdge (const edge_t &edge, const edge_t &originalEdge)
void make_dummies (const std::uint32_t iT)
void erase_dummies ()
std::unordered_map< std::uint32_t, layer_depth_t > peel_layer (std::stack< std::uint32_t > seeds, const layer_depth_t layerDepth, std::vector< layer_depth_t > &triDepths) const
Private Attributes
std::vector< std::uint32_t > m_dummyTris
TNearPointLocator m_nearPtLocator
std::size_t m_nTargetVerts
super_geometry_type_t::Enum m_superGeomType
vertex_insertion_order_t::Enum m_vertexInsertionOrder
action_on_intersecting_constraint_edges_t::Enum m_intersectingEdgesStrategy
T m_minDistToConstraintEdge
Constructor & Destructor Documentation
triangulator_t() [1/4]
template<typename T , typename TNearPointLocator > cdt::triangulator_t< T, TNearPointLocator >::triangulator_t
Default constructor.
    : m_nTargetVerts(detail::defaults::nTargetVerts)
    , m_superGeomType(detail::defaults::superGeomType)
    , m_vertexInsertionOrder(detail::defaults::vertexInsertionOrder)
    , m_intersectingEdgesStrategy(detail::defaults::intersectingEdgesStrategy)
    , m_minDistToConstraintEdge(detail::defaults::minDistToConstraintEdge)
{
}
triangulator_t() [2/4]
template<typename T , typename TNearPointLocator > cdt::triangulator_t< T, TNearPointLocator >::triangulator_t (vertex_insertion_order_t::Enum vertexInsertionOrder)
Constructor
Parameters
vertexInsertionOrder strategy used for ordering vertex insertions
    : m_nTargetVerts(detail::defaults::nTargetVerts)
    , m_superGeomType(detail::defaults::superGeomType)
    , m_vertexInsertionOrder(vertexInsertionOrder)
    , m_intersectingEdgesStrategy(detail::defaults::intersectingEdgesStrategy)
    , m_minDistToConstraintEdge(detail::defaults::minDistToConstraintEdge)
{
}
triangulator_t() [3/4]
template<typename T , typename TNearPointLocator > cdt::triangulator_t< T, TNearPointLocator >::triangulator_t (vertex_insertion_order_t::Enum vertexInsertionOrder, action_on_intersecting_constraint_edges_t::Enum intersectingEdgesStrategy, T minDistToConstraintEdge)
Constructor
Parameters
vertexInsertionOrder strategy used for ordering vertex insertions
intersectingEdgesStrategy strategy for treating intersecting constraint edges
minDistToConstraintEdge distance within which point is considered to be lying on a constraint edge. Used when adding constraints to the triangulation.
    : m_nTargetVerts(detail::defaults::nTargetVerts)
    , m_superGeomType(detail::defaults::superGeomType)
    , m_vertexInsertionOrder(vertexInsertionOrder)
    , m_intersectingEdgesStrategy(intersectingEdgesStrategy)
    , m_minDistToConstraintEdge(minDistToConstraintEdge)
{
}
triangulator_t() [4/4]
template<typename T , typename TNearPointLocator > cdt::triangulator_t< T, TNearPointLocator >::triangulator_t (vertex_insertion_order_t::Enum vertexInsertionOrder, const TNearPointLocator & nearPtLocator, action_on_intersecting_constraint_edges_t::Enum intersectingEdgesStrategy, T minDistToConstraintEdge)
Constructor
Parameters
vertexInsertionOrder strategy used for ordering vertex insertions
nearPtLocator class providing locating near point for efficiently inserting new points
intersectingEdgesStrategy strategy for treating intersecting constraint edges
minDistToConstraintEdge distance within which point is considered to be lying on a constraint edge. Used when adding constraints to the triangulation.
    : m_nTargetVerts(detail::defaults::nTargetVerts)
    , m_nearPtLocator(nearPtLocator)
    , m_superGeomType(detail::defaults::superGeomType)
    , m_vertexInsertionOrder(vertexInsertionOrder)
    , m_intersectingEdgesStrategy(intersectingEdgesStrategy)
    , m_minDistToConstraintEdge(minDistToConstraintEdge)
{
}
Member Function Documentation
add_adjacent_triangle()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::add_adjacent_triangle (std::uint32_t iVertex, std::uint32_t iTriangle) private
{
    vertTris[iVertex].push_back(iTriangle);
}
Referenced by cdt::triangulator_t< T, TNearPointLocator >::insert_point_in_triangle(), and cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge().
add_adjacent_triangles() [1/2]
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::add_adjacent_triangles (std::uint32_t iVertex, std::uint32_t iT1, std::uint32_t iT2, std::uint32_t iT3) private
{
    std::vector<std::uint32_t>& vTris = vertTris[iVertex];
    vTris.reserve(vTris.size() + 3);
    vTris.push_back(iT1);
    vTris.push_back(iT2);
    vTris.push_back(iT3);
}
Referenced by cdt::triangulator_t< T, TNearPointLocator >::insert_point_in_triangle(), and cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge().
add_adjacent_triangles() [2/2]
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::add_adjacent_triangles (std::uint32_t iVertex, std::uint32_t iT1, std::uint32_t iT2, std::uint32_t iT3, std::uint32_t iT4) private
{
    std::vector<std::uint32_t>& vTris = vertTris[iVertex];
    vTris.reserve(vTris.size() + 4);
    vTris.push_back(iT1);
    vTris.push_back(iT2);
    vTris.push_back(iT3);
    vTris.push_back(iT4);
}
add_super_triangle()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::add_super_triangle (const box2d_t< T > & box) private
{
    m_nTargetVerts = 3;
    m_superGeomType = super_geometry_type_t::SUPER_TRIANGLE;
    const vec2_<T> center = {
        (box.min.x() + box.max.x()) / T(2), (box.min.y() + box.max.y()) / T(2)
    };
    const T w = box.max.x() - box.min.x();
    const T h = box.max.y() - box.min.y();
    T r = std::sqrt(w * w + h * h) / T(2); // incircle radius
    r *= T(1.1);
    const T R = T(2) * r; // excircle radius
    const T shiftX = R * std::sqrt(T(3)) / T(2); // R * cos(30 deg)
    const vec2_<T> posV1 = { center.x() - shiftX, center.y() - r };
    const vec2_<T> posV2 = { center.x() + shiftX, center.y() - r };
    const vec2_<T> posV3 = { center.x(), center.y() + R };
    create_vertex(posV1, std::vector<std::uint32_t>(1, std::uint32_t(0)));
    create_vertex(posV2, std::vector<std::uint32_t>(1, std::uint32_t(0)));
    create_vertex(posV3, std::vector<std::uint32_t>(1, std::uint32_t(0)));
    const triangle_t superTri = {
        { std::uint32_t(0), std::uint32_t(1), std::uint32_t(2) },
        { null_neighbour, null_neighbour, null_neighbour }
    };
    add_triangle(superTri);
    m_nearPtLocator.initialize(vertices);
}
References cdt::box2d_t< T >::max, cdt::box2d_t< T >::min, cdt::null_neighbour(), cdt::super_geometry_type_t::SUPER_TRIANGLE, vec2_< T >::x(), and vec2_< T >::y().
add_triangle() [1/2]
template<typename T , typename TNearPointLocator > std::uint32_t cdt::triangulator_t< T, TNearPointLocator >::add_triangle private
{
    if (m_dummyTris.empty()) {
        const triangle_t dummy = {
            { null_vertex, null_vertex, null_vertex },
            { null_neighbour, null_neighbour, null_neighbour }
        };
        triangles.push_back(dummy);
        return std::uint32_t(triangles.size() - 1);
    }
    const std::uint32_t nxtDummy = m_dummyTris.back();
    m_dummyTris.pop_back();
    return nxtDummy;
}
References cdt::null_neighbour(), and cdt::null_vertex().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::insert_point_in_triangle(), and cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge().
add_triangle() [2/2]
template<typename T , typename TNearPointLocator > std::uint32_t cdt::triangulator_t< T, TNearPointLocator >::add_triangle (const triangle_t & t) private
{
    if (m_dummyTris.empty()) {
        triangles.push_back(t);
        return std::uint32_t(triangles.size() - 1);
    }
    const std::uint32_t nxtDummy = m_dummyTris.back();
    m_dummyTris.pop_back();
    triangles[nxtDummy] = t;
    return nxtDummy;
}
calculate_triangle_depths()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::vector< layer_depth_t > cdt::triangulator_t< T, TNearPointLocator >::calculate_triangle_depths () const inline
Calculate depth of each triangle in constraint triangulation. Supports overlapping boundaries.
Perform depth peeling from super triangle to outermost boundary, then to next boundary and so on until all triangles are traversed.
For example depth is:
0 for triangles outside outermost boundary
1 for triangles inside boundary but outside hole
2 for triangles in hole
3 for triangles in island and so on...
Returns
vector where element at index i stores depth of i-th triangle
    {
        std::vector<layer_depth_t> triDepths(
            triangles.size(), std::numeric_limits<layer_depth_t>::max());
        std::stack<std::uint32_t> seeds(std::deque<std::uint32_t>(1, vertTris[0].front()));
        layer_depth_t layerDepth = 0;
        layer_depth_t deepestSeedDepth = 0;
        std::unordered_map<layer_depth_t, std::unordered_set<std::uint32_t>> seedsByDepth;
        do {
            const std::unordered_map<std::uint32_t, layer_depth_t>& newSeeds = peel_layer(seeds, layerDepth, triDepths);
            seedsByDepth.erase(layerDepth);
            typedef std::unordered_map<std::uint32_t, layer_depth_t>::const_iterator Iter;
            for (Iter it = newSeeds.begin(); it != newSeeds.end(); ++it) {
                deepestSeedDepth = std::max(deepestSeedDepth, it->second);
                seedsByDepth[it->second].insert(it->first);
            }
            const std::unordered_set<std::uint32_t>& nextLayerSeeds = seedsByDepth[layerDepth + 1];
            seeds = std::stack<std::uint32_t>(
                std::deque<std::uint32_t>(nextLayerSeeds.begin(), nextLayerSeeds.end()));
            ++layerDepth;
        } while (!seeds.empty() || deepestSeedDepth > layerDepth);
        return triDepths;
    }
References cdt::triangulator_t< T, TNearPointLocator >::peel_layer(), cdt::triangulator_t< T, TNearPointLocator >::triangles, and cdt::triangulator_t< T, TNearPointLocator >::vertTris.
change_neighbour() [1/2]
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::change_neighbour (std::uint32_t iT, std::uint32_t iVedge1, std::uint32_t iVedge2, std::uint32_t newNeighbor) private
{
    triangle_t& t = triangles[iT];
    t.neighbors[opposite_triangle_index(t, iVedge1, iVedge2)] = newNeighbor;
}
References cdt::triangle_t::neighbors, and cdt::opposite_triangle_index().
change_neighbour() [2/2]
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::change_neighbour (std::uint32_t iT, std::uint32_t oldNeighbor, std::uint32_t newNeighbor) private
{
    if (iT == null_neighbour) {
        return;
    }
    triangle_t& t = triangles[iT];
    t.neighbors[get_neighbour_index(t, oldNeighbor)] = newNeighbor;
}
References cdt::get_neighbour_index(), cdt::triangle_t::neighbors, and cdt::null_neighbour().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::insert_point_in_triangle(), cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge(), and cdt::triangulator_t< T, TNearPointLocator >::make_dummies().
check_is_edgeflip_needed() [1/2]
template<typename T , typename TNearPointLocator > bool cdt::triangulator_t< T, TNearPointLocator >::check_is_edgeflip_needed (const vec2_< T > & v, std::uint32_t iT, std::uint32_t iTopo, std::uint32_t iVert) const private
{
    /*
     *                       v3         original edge: (v1, v3)
     *                      /|\   flip-candidate edge: (v,  v2)
     *                    /  |  \
     *                  /    |    \
     *                /      |      \
     * new vertex--> v       |       v2
     *                \      |      /
     *                  \    |    /
     *                    \  |  /
     *                      \|/
     *                       v1
     */
    const triangle_t& tOpo = triangles[iTopo];
    const std::uint32_t i = get_opposite_vertex_index(tOpo, iT);
    const std::uint32_t iV2 = tOpo.vertices[i];
    const std::uint32_t iV1 = tOpo.vertices[cw(i)];
    const std::uint32_t iV3 = tOpo.vertices[ccw(i)];
    // flip not needed if the original edge is fixed
    if (fixedEdges.count(edge_t(iV1, iV3)))
        return false;
    return check_is_edgeflip_needed(v, iV, iV1, iV2, iV3);
}
References cdt::ccw(), cdt::cw(), cdt::get_opposite_vertex_index(), and cdt::triangle_t::vertices.
check_is_edgeflip_needed() [2/2]
template<typename T , typename TNearPointLocator > bool cdt::triangulator_t< T, TNearPointLocator >::check_is_edgeflip_needed (const vec2_< T > & v, std::uint32_t iV, std::uint32_t iV1, std::uint32_t iV2, std::uint32_t iV3) const private
Handles super-triangle vertices. Super-tri points are not infinitely far and influence the input points Three cases are possible:
If one of the opposed vertices is super-tri: no flip needed
One of the shared vertices is super-tri: check if on point is same side of line formed by non-super-tri vertices as the non-super-tri shared vertex
None of the vertices are super-tri: normal circumcircle test
{
    const vec2_<T>& v1 = vertices[iV1];
    const vec2_<T>& v2 = vertices[iV2];
    const vec2_<T>& v3 = vertices[iV3];
    if (m_superGeomType == super_geometry_type_t::SUPER_TRIANGLE) {
        // If flip-candidate edge touches super-triangle in-circumference
        // test has to be replaced with orient2d test against the line
        // formed by two non-artificial vertices (that don't belong to
        // super-triangle)
        if (iV < 3) // flip-candidate edge touches super-triangle
        {
            // does original edge also touch super-triangle?
            if (iV1 < 3)
                return locate_point_wrt_line(v1, v2, v3) == locate_point_wrt_line(v, v2, v3);
            if (iV3 < 3)
                return locate_point_wrt_line(v3, v1, v2) == locate_point_wrt_line(v, v1, v2);
            return false; // original edge does not touch super-triangle
        }
        if (iV2 < 3) // flip-candidate edge touches super-triangle
        {
            // does original edge also touch super-triangle?
            if (iV1 < 3)
                return locate_point_wrt_line(v1, v, v3) == locate_point_wrt_line(v2, v, v3);
            if (iV3 < 3)
                return locate_point_wrt_line(v3, v1, v) == locate_point_wrt_line(v2, v1, v);
            return false; // original edge does not touch super-triangle
        }
        // flip-candidate edge does not touch super-triangle
        if (iV1 < 3)
            return locate_point_wrt_line(v1, v2, v3) == locate_point_wrt_line(v, v2, v3);
        if (iV3 < 3)
            return locate_point_wrt_line(v3, v1, v2) == locate_point_wrt_line(v, v1, v2);
    }
    return check_is_in_circumcircle(v, v1, v2, v3);
}
References cdt::check_is_in_circumcircle(), cdt::locate_point_wrt_line(), and cdt::super_geometry_type_t::SUPER_TRIANGLE.
conform_to_edge()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge (edge_t edge, std::vector< edge_t > originalEdges, boundary_overlap_count_t overlaps) private
Conform Delaunay triangulation to a fixed edge by recursively inserting mid point of the edge and then conforming to its halves
Parameters
edge fixed edge to conform to
originalEdges original edges that new edge is piece of
overlaps count of overlapping boundaries at the edge. Only used when re-introducing edge with overlaps > 0
orientationTolerance tolerance for orient2d predicate, values [-tolerance,+tolerance] are considered as 0.
{
    const std::uint32_t iA = edge.v1();
    std::uint32_t iB = edge.v2();
    if (iA == iB) // edge connects a vertex to itself
        return;
    const std::vector<std::uint32_t>& aTris = vertTris[iA];
    const std::vector<std::uint32_t>& bTris = vertTris[iB];
    const vec2_<T>& a = vertices[iA];
    const vec2_<T>& b = vertices[iB];
    if (check_vertices_share_edge(aTris, bTris)) {
        overlaps > 0 ? fixEdge(edge, overlaps) : fixEdge(edge);
        // avoid marking edge as a part of itself
        if (!originalEdges.empty() && edge != originalEdges.front()) {
            detail::insert_unique(pieceToOriginals[edge], originalEdges);
        }
        return;
    }
    const T distanceTolerance = m_minDistToConstraintEdge == T(0)
        ? T(0)
        : m_minDistToConstraintEdge * distance(a, b);
    std::uint32_t iT;
    std::uint32_t iVleft, iVright;
    std::tie(iT, iVleft, iVright) = get_intersected_triangle(iA, aTris, a, b, distanceTolerance);
    // if one of the triangle vertices is on the edge, move edge start
    if (iT == null_neighbour) {
        const edge_t edgePart(iA, iVleft);
        overlaps > 0 ? fixEdge(edgePart, overlaps) : fixEdge(edgePart);
        detail::insert_unique(pieceToOriginals[edgePart], originalEdges);
        return conform_to_edge(edge_t(iVleft, iB), originalEdges, overlaps);
    }
    std::uint32_t iV = iA;
    triangle_t t = triangles[iT];
    while (std::find(t.vertices.begin(), t.vertices.end(), iB) == t.vertices.end()) {
        const std::uint32_t iTopo = get_opposite_triangle_index(t, iV);
        const triangle_t& tOpo = triangles[iTopo];
        const std::uint32_t iVopo = get_opposed_vertex_index(tOpo, iT);
        const vec2_<T> vOpo = vertices[iVopo];
        // RESOLVE intersection between two constraint edges if needed
        if (m_intersectingEdgesStrategy == action_on_intersecting_constraint_edges_t::RESOLVE && fixedEdges.count(edge_t(iVleft, iVright))) {
            const std::uint32_t iNewVert = static_cast<std::uint32_t>(vertices.size());
            // split constraint edge that already exists in triangulation
            const edge_t splitEdge(iVleft, iVright);
            const edge_t half1(iVleft, iNewVert);
            const edge_t half2(iNewVert, iVright);
            const boundary_overlap_count_t overlaps = overlapCount[splitEdge];
            // remove the edge that will be split
            fixedEdges.erase(splitEdge);
            overlapCount.erase(splitEdge);
            // add split edge's halves
            fixEdge(half1, overlaps);
            fixEdge(half2, overlaps);
            // maintain piece-to-original mapping
            std::vector<edge_t> newOriginals(1, splitEdge);
            const std::unordered_map<edge_t, std::vector<edge_t>>::const_iterator originalsIt = pieceToOriginals.find(splitEdge);
            if (originalsIt != pieceToOriginals.end()) { // edge being split was split before: pass-through originals
                newOriginals = originalsIt->second;
                pieceToOriginals.erase(originalsIt);
            }
            detail::insert_unique(pieceToOriginals[half1], newOriginals);
            detail::insert_unique(pieceToOriginals[half2], newOriginals);
            // add a new point at the intersection of two constraint edges
            const vec2_<T> newV = detail::get_intersection_point_coords(
                vertices[iA],
                vertices[iB],
                vertices[iVleft],
                vertices[iVright]);
            create_vertex(newV, std::vector<std::uint32_t>());
            std::stack<std::uint32_t> triStack = insert_point_on_edge(iNewVert, iT, iTopo);
            enforce_delaunay_property_using_edge_flips(newV, iNewVert, triStack);
            conform_to_edge(edge_t(iA, iNewVert), originalEdges, overlaps);
            conform_to_edge(edge_t(iNewVert, iB), originalEdges, overlaps);
            return;
        }
        iT = iTopo;
        t = triangles[iT];
        const point_to_line_location_t::Enum loc = locate_point_wrt_line(vOpo, a, b, distanceTolerance);
        if (loc == point_to_line_location_t::LEFT_SIDE) {
            iV = iVleft;
            iVleft = iVopo;
        } else if (loc == point_to_line_location_t::RIGHT_SIDE) {
            iV = iVright;
            iVright = iVopo;
        } else // encountered point on the edge
            iB = iVopo;
    }
    // add mid-point to triangulation
    const std::uint32_t iMid = static_cast<std::uint32_t>(vertices.size());
    const vec2_<T>& start = vertices[iA];
    const vec2_<T>& end = vertices[iB];
    create_vertex(
        vec2_<T>::make((start.x() + end.x()) / T(2), (start.y() + end.y()) / T(2)),
        std::vector<std::uint32_t>());
    const std::vector<edge_t> flippedFixedEdges = insert_vertex_and_flip_fixed_edges(iMid);
    conform_to_edge(edge_t(iA, iMid), originalEdges, overlaps);
    conform_to_edge(edge_t(iMid, iB), originalEdges, overlaps);
    // re-introduce fixed edges that were flipped
    // and make sure overlap count is preserved
    for (std::vector<edge_t>::const_iterator it = flippedFixedEdges.begin();
         it != flippedFixedEdges.end();
         ++it) {
        fixedEdges.erase(*it);
        boundary_overlap_count_t prevOverlaps = 0;
        const std::unordered_map<edge_t, boundary_overlap_count_t>::const_iterator
            overlapsIt
            = overlapCount.find(*it);
        if (overlapsIt != overlapCount.end()) {
            prevOverlaps = overlapsIt->second;
            overlapCount.erase(overlapsIt);
        }
        // override overlapping boundaries count when re-inserting an edge
        std::vector<edge_t> prevOriginals(1, *it);
        const std::unordered_map<edge_t, std::vector<edge_t>>::const_iterator originalsIt = pieceToOriginals.find(*it);
        if (originalsIt != pieceToOriginals.end()) {
            prevOriginals = originalsIt->second;
        }
        conform_to_edge(*it, prevOriginals, prevOverlaps);
    }
    if (iB != edge.v2())
        conform_to_edge(edge_t(iB, edge.v2()), originalEdges, overlaps);
}
References cdt::check_vertices_share_edge(), cdt::distance(), end, cdt::detail::get_intersection_point_coords(), cdt::get_opposed_vertex_index(), cdt::get_opposite_triangle_index(), cdt::detail::insert_unique(), cdt::point_to_line_location_t::LEFT_SIDE, cdt::locate_point_wrt_line(), cdt::null_neighbour(), cdt::action_on_intersecting_constraint_edges_t::RESOLVE, cdt::point_to_line_location_t::RIGHT_SIDE, start, cdt::edge_t::v1(), cdt::edge_t::v2(), and cdt::triangle_t::vertices.
conform_to_edges() [1/2]
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::conform_to_edges (const std::vector< edge_t > & edges)
Ensure that triangulation conforms to constraints (fixed edges)
Note
For each fixed edge that is not present in the triangulation its midpoint is recursively added until the original edge is represented by a sequence of its pieces. New vertices are inserted.
If some edge appears more than once the input this means that multiple boundaries overlap at the edge and impacts how hole detection algorithm of triangulator_t::erase_outer_triangles_and_holes works. Make sure there are no erroneous duplicates.
Template Parameters
edges edges to conform to
{
    conform_to_edges(edges.begin(), edges.end(), edge_get_v1, edge_get_v2);
}
References cdt::edge_get_v1(), and cdt::edge_get_v2().
conform_to_edges() [2/2]
template<typename T , typename TNearPointLocator > template<typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd > void cdt::triangulator_t< T, TNearPointLocator >::conform_to_edges (TEdgeIter first, TEdgeIter last, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd)
Ensure that triangulation conforms to constraints (fixed edges)
Note
For each fixed edge that is not present in the triangulation its midpoint is recursively added until the original edge is represented by a sequence of its pieces. New vertices are inserted.
If some edge appears more than once the input this means that multiple boundaries overlap at the edge and impacts how hole detection algorithm of triangulator_t::erase_outer_triangles_and_holes works. Make sure there are no erroneous duplicates.
Template Parameters
TEdgeIter iterator that dereferences to custom edge type
TGetEdgeVertexStart function object getting start vertex index from an edge. Getter signature: const TEdgeIter::value_type& -> std::uint32_t
TGetEdgeVertexEnd function object getting end vertex index from an edge. Getter signature: const TEdgeIter::value_type& -> std::uint32_t
Parameters
first beginning of the range of edges to add
last end of the range of edges to add
getStart getter of edge start vertex index
getEnd getter of edge end vertex index
{
    if (is_finalized()) {
        throw std::runtime_error(
            "triangulator_t was finalized with 'erase...' method. Conforming to "
            "new edges is not possible");
    }
    for (; first != last; ++first) {
        // +3 to account for super-triangle vertices
        const edge_t e(
            std::uint32_t(getStart(*first) + m_nTargetVerts),
            std::uint32_t(getEnd(*first) + m_nTargetVerts));
        conform_to_edge(e, std::vector<edge_t>(1, e), 0);
    }
    erase_dummies();
}
create_vertex()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::create_vertex (const vec2_< T > & pos, const std::vector< std::uint32_t > & tris) private
{
    vertices.push_back(pos);
    vertTris.push_back(tris);
}
enforce_delaunay_property_using_edge_flips()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::enforce_delaunay_property_using_edge_flips (const vec2_< T > & v, std::uint32_t iVert, std::stack< std::uint32_t > & triStack) private
{
    while (!triStack.empty()) {
        const std::uint32_t iT = triStack.top();
        triStack.pop();
        const triangle_t& t = triangles[iT];
        const std::uint32_t iTopo = get_opposite_triangle_index(t, iVert);
        if (iTopo == null_neighbour) {
            continue;
        }
        if (check_is_edgeflip_needed(v, iT, iTopo, iVert)) {
            do_edgeflip(iT, iTopo);
            triStack.push(iT);
            triStack.push(iTopo);
        }
    }
}
References cdt::get_opposite_triangle_index(), and cdt::null_neighbour().
erase_dummies()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> void cdt::triangulator_t< T, TNearPointLocator >::erase_dummies () inline private
Erase all dummy triangles
Note
Advanced method for manually modifying the triangulation from outside. Please call it when you know what you are doing.
    {
        if (m_dummyTris.empty())
            return;
        const std::unordered_set<std::uint32_t> dummySet(m_dummyTris.begin(), m_dummyTris.end());
        std::unordered_map<std::uint32_t, std::uint32_t> triIndMap;
        triIndMap[null_neighbour] = null_neighbour;
        for (std::uint32_t iT(0), iTnew(0); iT < std::uint32_t(triangles.size()); ++iT) {
            if (dummySet.count(iT))
                continue;
            triIndMap[iT] = iTnew;
            triangles[iTnew] = triangles[iT];
            iTnew++;
        }
        triangles.erase(triangles.end() - dummySet.size(), triangles.end());
        // remap adjacent triangle indices for vertices
        typedef typename std::vector<std::vector<std::uint32_t>>::iterator VertTrisIt;
        for (VertTrisIt vTris = vertTris.begin(); vTris != vertTris.end(); ++vTris) {
            for (std::vector<std::uint32_t>::iterator iT = vTris->begin(); iT != vTris->end(); ++iT)
                *iT = triIndMap[*iT];
        }
        // remap neighbor indices for triangles
        for (std::vector<triangle_t>::iterator t = triangles.begin(); t != triangles.end(); ++t) {
            std::array<std::uint32_t, 3>& nn = t->neighbors;
            for (std::array<std::uint32_t, 3>::iterator iN = nn.begin(); iN != nn.end(); ++iN)
                *iN = triIndMap[*iN];
        }
        // clear dummy triangles
        m_dummyTris = std::vector<std::uint32_t>();
    }
References cdt::triangulator_t< T, TNearPointLocator >::m_dummyTris, cdt::null_neighbour(), cdt::triangulator_t< T, TNearPointLocator >::triangles, and cdt::triangulator_t< T, TNearPointLocator >::vertTris.
erase_outer_triangles()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::erase_outer_triangles
Erase triangles outside of constrained boundary using growing.
{
    // make dummy triangles adjacent to super-triangle's vertices
    const std::stack<std::uint32_t> seed(std::deque<std::uint32_t>(1, vertTris[0].front()));
    const std::unordered_set<std::uint32_t> toErase = grow_to_boundary(seed);
    finalise_triangulation(toErase);
}
erase_outer_triangles_and_holes()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::erase_outer_triangles_and_holes
Erase triangles outside of constrained boundary and auto-detected holes
Note
detecting holes relies on layer peeling based on layer depth
supports overlapping or touching boundaries
{
    const std::vector<layer_depth_t> triDepths = calculate_triangle_depths();
    std::unordered_set<std::uint32_t> toErase;
    toErase.reserve(triangles.size());
    for (std::size_t iT = 0; iT != triangles.size(); ++iT) {
        if (triDepths[iT] % 2 == 0){
            toErase.insert(static_cast<std::uint32_t>(iT));
        }
    }
    finalise_triangulation(toErase);
}
eraseSuperTriangle()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::eraseSuperTriangle
Erase triangles adjacent to super triangle
Note
does nothing if custom geometry is used
{
    if (m_superGeomType != super_geometry_type_t::SUPER_TRIANGLE)
        return;
    // find triangles adjacent to super-triangle's vertices
    std::unordered_set<std::uint32_t> toErase;
    toErase.reserve(
        vertTris[0].size() + vertTris[1].size() + vertTris[2].size());
    for (std::uint32_t iT(0); iT < std::uint32_t(triangles.size()); ++iT) {
        triangle_t& t = triangles[iT];
        if (t.vertices[0] < 3 || t.vertices[1] < 3 || t.vertices[2] < 3)
            toErase.insert(iT);
    }
    finalise_triangulation(toErase);
}
References size, cdt::super_geometry_type_t::SUPER_TRIANGLE, and cdt::triangle_t::vertices.
finalise_triangulation()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::finalise_triangulation (const std::unordered_set< std::uint32_t > & removedTriangles) private
Remove super-triangle (if used) and triangles with specified indices. Adjust internal triangulation state accordingly. @removedTriangles indices of triangles to remove
{
    erase_dummies();
    // remove super-triangle
    if (m_superGeomType == super_geometry_type_t::SUPER_TRIANGLE) {
        vertices.erase(vertices.begin(), vertices.begin() + 3);
        if (removedTriangles.empty())
            vertTris.erase(vertTris.begin(), vertTris.begin() + 3);
        // edge_t re-mapping
        { // fixed edges
            std::unordered_set<edge_t> updatedFixedEdges;
            typedef std::unordered_set<edge_t>::const_iterator It;
            for (It e = fixedEdges.begin(); e != fixedEdges.end(); ++e) {
                updatedFixedEdges.insert(remap_no_supertriangle(*e));
            }
            fixedEdges = updatedFixedEdges;
        }
        { // overlap count
            std::unordered_map<edge_t, boundary_overlap_count_t> updatedOverlapCount;
            typedef std::unordered_map<edge_t, boundary_overlap_count_t>::const_iterator
                It;
            for (It it = overlapCount.begin(); it != overlapCount.end(); ++it) {
                updatedOverlapCount.insert(std::make_pair(
                    remap_no_supertriangle(it->first), it->second));
            }
            overlapCount = updatedOverlapCount;
        }
        { // split edges mapping
            std::unordered_map<edge_t, std::vector<edge_t>> updatedPieceToOriginals;
            typedef std::unordered_map<edge_t, std::vector<edge_t>>::const_iterator It;
            for (It it = pieceToOriginals.begin(); it != pieceToOriginals.end();
                 ++it) {
                std::vector<edge_t> ee = it->second;
                for (std::vector<edge_t>::iterator eeIt = ee.begin(); eeIt != ee.end();
                     ++eeIt) {
                    *eeIt = remap_no_supertriangle(*eeIt);
                }
                updatedPieceToOriginals.insert(
                    std::make_pair(remap_no_supertriangle(it->first), ee));
            }
            pieceToOriginals = updatedPieceToOriginals;
        }
    }
    // remove other triangles
    remove_triangles(removedTriangles);
    // adjust triangle vertices: account for removed super-triangle
    if (m_superGeomType == super_geometry_type_t::SUPER_TRIANGLE) {
        for (std::vector<triangle_t>::iterator t = triangles.begin(); t != triangles.end();
             ++t) {
            std::array<std::uint32_t, 3>& vv = t->vertices;
            for (std::array<std::uint32_t, 3>::iterator v = vv.begin(); v != vv.end(); ++v) {
                *v -= 3;
            }
        }
    }
}
References cdt::remap_no_supertriangle(), and cdt::super_geometry_type_t::SUPER_TRIANGLE.
find_delaunay_point()
template<typename T , typename TNearPointLocator > std::uint32_t cdt::triangulator_t< T, TNearPointLocator >::find_delaunay_point (std::uint32_t ia, std::uint32_t ib, std::vector< std::uint32_t >::const_iterator pointsFirst, std::vector< std::uint32_t >::const_iterator pointsLast) const private
{
    MCUT_ASSERT(pointsFirst != pointsLast);
    const vec2_<T>& a = vertices[ia];
    const vec2_<T>& b = vertices[ib];
    std::uint32_t ic = *pointsFirst;
    vec2_<T> c = vertices[ic];
    for (std::vector<std::uint32_t>::const_iterator it = pointsFirst + 1; it != pointsLast; ++it) {
        const vec2_<T> v = vertices[*it];
        if (!check_is_in_circumcircle(v, a, b, c))
        {
            continue;
        }
        ic = *it;
        c = vertices[ic];
    }
    return ic;
}
References cdt::check_is_in_circumcircle(), and MCUT_ASSERT.
fixEdge() [1/3]
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> void cdt::triangulator_t< T, TNearPointLocator >::fixEdge (const edge_t & edge) inline private
    {
        if (!fixedEdges.insert(edge).second) {
            ++overlapCount[edge]; // if edge is already fixed increment the counter
        }
    }
References cdt::triangulator_t< T, TNearPointLocator >::fixedEdges, and cdt::triangulator_t< T, TNearPointLocator >::overlapCount.
fixEdge() [2/3]
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> void cdt::triangulator_t< T, TNearPointLocator >::fixEdge (const edge_t & edge, const boundary_overlap_count_t overlaps) inline private
    {
        fixedEdges.insert(edge);
        overlapCount[edge] = overlaps; // override overlap counter
    }
References cdt::triangulator_t< T, TNearPointLocator >::fixedEdges, and cdt::triangulator_t< T, TNearPointLocator >::overlapCount.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::fixEdge().
fixEdge() [3/3]
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> void cdt::triangulator_t< T, TNearPointLocator >::fixEdge (const edge_t & edge, const edge_t & originalEdge) inline private
    {
        fixEdge(edge);
        if (edge != originalEdge)
            detail::insert_unique(pieceToOriginals[edge], originalEdge);
    }
References cdt::triangulator_t< T, TNearPointLocator >::fixEdge(), cdt::detail::insert_unique(), and cdt::triangulator_t< T, TNearPointLocator >::pieceToOriginals.
get_intersected_triangle()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::tuple< std::uint32_t, std::uint32_t, std::uint32_t > cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle (const std::uint32_t iA, const std::vector< std::uint32_t > & candidates, const vec2_< T > & a, const vec2_< T > & b, const T orientationTolerance) const inline
Returns:
intersected triangle index
index of point on the left of the line
index of point on the right of the line If left point is right on the line: no triangle is intersected:
triangle index is no-neighbor (invalid)
index of point on the line
index of point on the right of the line
    {
        typedef std::vector<std::uint32_t>::const_iterator TriIndCit;
        for (TriIndCit it = candidates.begin(); it != candidates.end(); ++it) {
            const std::uint32_t iT = *it;
            const triangle_t t = triangles[iT];
            const std::uint32_t i = get_vertex_index(t, iA);
            const std::uint32_t iP2 = t.vertices[ccw(i)];
            const T orientP2 = orient2d(vertices[iP2], a, b);
            const point_to_line_location_t::Enum locP2 = classify_orientation(orientP2);
            if (locP2 == point_to_line_location_t::RIGHT_SIDE) {
                const std::uint32_t iP1 = t.vertices[cw(i)];
                const T orientP1 = orient2d(vertices[iP1], a, b);
                const point_to_line_location_t::Enum locP1 = classify_orientation(orientP1);
                if (locP1 == point_to_line_location_t::COLLINEAR) {
                    return std::make_tuple(null_neighbour, iP1, iP1);
                }
                if (locP1 == point_to_line_location_t::LEFT_SIDE) {
                    if (orientationTolerance) {
                        T closestOrient;
                        std::uint32_t iClosestP;
                        if (std::abs(orientP1) <= std::abs(orientP2)) {
                            closestOrient = orientP1;
                            iClosestP = iP1;
                        } else {
                            closestOrient = orientP2;
                            iClosestP = iP2;
                        }
                        if (classify_orientation(
                                closestOrient, orientationTolerance)
                            == point_to_line_location_t::COLLINEAR) {
                            return std::make_tuple(null_neighbour, iClosestP, iClosestP);
                        }
                    }
                    return std::make_tuple(iT, iP1, iP2);
                }
            }
        }
        throw std::runtime_error("Could not find vertex triangle intersected by "
                                 "edge. Note: can be caused by duplicate points.");
    }
References cdt::ccw(), cdt::classify_orientation(), cdt::point_to_line_location_t::COLLINEAR, cdt::cw(), cdt::get_vertex_index(), cdt::point_to_line_location_t::LEFT_SIDE, cdt::null_neighbour(), orient2d(), cdt::point_to_line_location_t::RIGHT_SIDE, cdt::triangulator_t< T, TNearPointLocator >::triangles, cdt::triangulator_t< T, TNearPointLocator >::vertices, and cdt::triangle_t::vertices.
grow_to_boundary()
template<typename T , typename TNearPointLocator > std::unordered_set< std::uint32_t > cdt::triangulator_t< T, TNearPointLocator >::grow_to_boundary (std::stack< std::uint32_t > seeds) const private
{
    std::unordered_set<std::uint32_t> traversed;
    while (!seeds.empty()) {
        const std::uint32_t iT = seeds.top();
        seeds.pop();
        traversed.insert(iT);
        const triangle_t& t = triangles[iT];
        for (std::uint32_t i(0); i < std::uint32_t(3); ++i) {
            const edge_t opEdge(t.vertices[ccw(i)], t.vertices[cw(i)]);
            if (fixedEdges.count(opEdge))
                continue;
            const std::uint32_t iN = t.neighbors[get_opposite_neighbour_from_vertex(i)];
            if (iN != null_neighbour && traversed.count(iN) == 0)
                seeds.push(iN);
        }
    }
    return traversed;
}
References cdt::ccw(), cdt::cw(), cdt::get_opposite_neighbour_from_vertex(), cdt::triangle_t::neighbors, cdt::null_neighbour(), and cdt::triangle_t::vertices.
initialise_with_custom_supergeometry()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::initialise_with_custom_supergeometry
Call this method after directly setting custom super-geometry via vertices and triangles members
{
    m_nearPtLocator.initialize(vertices);
    m_nTargetVerts = vertices.size();
    m_superGeomType = super_geometry_type_t::CUSTOM;
}
References cdt::super_geometry_type_t::CUSTOM.
insert_edge()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::insert_edge (edge_t edge, edge_t originalEdge) private
Insert an edge into constraint Delaunay triangulation
Parameters
edge edge to insert
originalEdge original edge inserted edge is part of
{
    const std::uint32_t iA = edge.v1();
    std::uint32_t iB = edge.v2();
    if (iA == iB) // edge connects a vertex to itself
        return;
    const std::vector<std::uint32_t>& aTris = vertTris[iA];
    const std::vector<std::uint32_t>& bTris = vertTris[iB];
    const vec2_<T>& a = vertices[iA];
    const vec2_<T>& b = vertices[iB];
    if (check_vertices_share_edge(aTris, bTris)) {
        fixEdge(edge, originalEdge);
        return;
    }
    const T distanceTolerance = m_minDistToConstraintEdge == T(0)
        ? T(0)
        : m_minDistToConstraintEdge * distance(a, b);
    std::uint32_t iT;
    std::uint32_t iVleft, iVright;
    std::tie(iT, iVleft, iVright) = get_intersected_triangle(iA, aTris, a, b, distanceTolerance);
    // if one of the triangle vertices is on the edge, move edge start
    if (iT == null_neighbour) {
        const edge_t edgePart(iA, iVleft);
        fixEdge(edgePart, originalEdge);
        return insert_edge(edge_t(iVleft, iB), originalEdge);
    }
    std::vector<std::uint32_t> intersected(1, iT);
    std::vector<std::uint32_t> ptsLeft(1, iVleft);
    std::vector<std::uint32_t> ptsRight(1, iVright);
    std::uint32_t iV = iA;
    triangle_t t = triangles[iT];
    while (std::find(t.vertices.begin(), t.vertices.end(), iB) == t.vertices.end()) {
        const std::uint32_t iTopo = get_opposite_triangle_index(t, iV);
        const triangle_t& tOpo = triangles[iTopo];
        const std::uint32_t iVopo = get_opposed_vertex_index(tOpo, iT);
        const vec2_<T> vOpo = vertices[iVopo];
        // RESOLVE intersection between two constraint edges if needed
        if (m_intersectingEdgesStrategy == action_on_intersecting_constraint_edges_t::RESOLVE && fixedEdges.count(edge_t(iVleft, iVright))) {
            const std::uint32_t iNewVert = static_cast<std::uint32_t>(vertices.size());
            // split constraint edge that already exists in triangulation
            const edge_t splitEdge(iVleft, iVright);
            const edge_t half1(iVleft, iNewVert);
            const edge_t half2(iNewVert, iVright);
            const boundary_overlap_count_t overlaps = overlapCount[splitEdge];
            // remove the edge that will be split
            fixedEdges.erase(splitEdge);
            overlapCount.erase(splitEdge);
            // add split edge's halves
            fixEdge(half1, overlaps);
            fixEdge(half2, overlaps);
            // maintain piece-to-original mapping
            std::vector<edge_t> newOriginals(1, splitEdge);
            const std::unordered_map<edge_t, std::vector<edge_t>>::const_iterator originalsIt = pieceToOriginals.find(splitEdge);
            if (originalsIt != pieceToOriginals.end()) { // edge being split was split before: pass-through originals
                newOriginals = originalsIt->second;
                pieceToOriginals.erase(originalsIt);
            }
            detail::insert_unique(pieceToOriginals[half1], newOriginals);
            detail::insert_unique(pieceToOriginals[half2], newOriginals);
            // add a new point at the intersection of two constraint edges
            const vec2_<T> newV = detail::get_intersection_point_coords(
                vertices[iA],
                vertices[iB],
                vertices[iVleft],
                vertices[iVright]);
            create_vertex(newV, std::vector<std::uint32_t>());
            std::stack<std::uint32_t> triStack = insert_point_on_edge(iNewVert, iT, iTopo);
            enforce_delaunay_property_using_edge_flips(newV, iNewVert, triStack);
            // TODO: is it's possible to re-use pseudo-polygons
            //  for inserting [iA, iNewVert] edge half?
            insert_edge(edge_t(iA, iNewVert), originalEdge);
            insert_edge(edge_t(iNewVert, iB), originalEdge);
            return;
        }
        intersected.push_back(iTopo);
        iT = iTopo;
        t = triangles[iT];
        const point_to_line_location_t::Enum loc = locate_point_wrt_line(vOpo, a, b, distanceTolerance);
        if (loc == point_to_line_location_t::LEFT_SIDE) {
            ptsLeft.push_back(iVopo);
            iV = iVleft;
            iVleft = iVopo;
        } else if (loc == point_to_line_location_t::RIGHT_SIDE) {
            ptsRight.push_back(iVopo);
            iV = iVright;
            iVright = iVopo;
        } else // encountered point on the edge
            iB = iVopo;
    }
    // Remove intersected triangles
    typedef std::vector<std::uint32_t>::const_iterator TriIndCit;
    for (TriIndCit it = intersected.begin(); it != intersected.end(); ++it)
        make_dummies(*it);
    // Triangulate pseudo-polygons on both sides
    const std::uint32_t iTleft = triangulate_pseudo_polygon(iA, iB, ptsLeft.begin(), ptsLeft.end());
    std::reverse(ptsRight.begin(), ptsRight.end());
    const std::uint32_t iTright = triangulate_pseudo_polygon(iB, iA, ptsRight.begin(), ptsRight.end());
    change_neighbour(iTleft, null_neighbour, iTright);
    change_neighbour(iTright, null_neighbour, iTleft);
    if (iB != edge.v2()) // encountered point on the edge
    {
        // fix edge part
        const edge_t edgePart(iA, iB);
        fixEdge(edgePart, originalEdge);
        return insert_edge(edge_t(iB, edge.v2()), originalEdge);
    } else {
        fixEdge(edge, originalEdge);
    }
}
References cdt::check_vertices_share_edge(), cdt::distance(), cdt::detail::get_intersection_point_coords(), cdt::get_opposed_vertex_index(), cdt::get_opposite_triangle_index(), cdt::detail::insert_unique(), cdt::point_to_line_location_t::LEFT_SIDE, cdt::locate_point_wrt_line(), cdt::null_neighbour(), cdt::action_on_intersecting_constraint_edges_t::RESOLVE, cdt::point_to_line_location_t::RIGHT_SIDE, cdt::edge_t::v1(), cdt::edge_t::v2(), and cdt::triangle_t::vertices.
insert_edges() [1/2]
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::insert_edges (const std::vector< edge_t > & edges)
Insert constraint edges into triangulation
Note
Each fixed edge is inserted by deleting the triangles it crosses, followed by the triangulation of the polygons on each side of the edge. No new vertices are inserted.
If some edge appears more than once in the input this means that multiple boundaries overlap at the edge and impacts how hole detection algorithm of triangulator_t::erase_outer_triangles_and_holes works. Make sure there are no erroneous duplicates.
Template Parameters
edges constraint edges
{
    insert_edges(edges.begin(), edges.end(), edge_get_v1, edge_get_v2);
}
References cdt::edge_get_v1(), and cdt::edge_get_v2().
insert_edges() [2/2]
template<typename T , typename TNearPointLocator > template<typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd > void cdt::triangulator_t< T, TNearPointLocator >::insert_edges (TEdgeIter first, TEdgeIter last, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd)
Insert constraints (custom-type fixed edges) into triangulation
Note
Each fixed edge is inserted by deleting the triangles it crosses, followed by the triangulation of the polygons on each side of the edge. No new vertices are inserted.
If some edge appears more than once in the input this means that multiple boundaries overlap at the edge and impacts how hole detection algorithm of triangulator_t::erase_outer_triangles_and_holes works. Make sure there are no erroneous duplicates.
Template Parameters
TEdgeIter iterator that dereferences to custom edge type
TGetEdgeVertexStart function object getting start vertex index from an edge. Getter signature: const TEdgeIter::value_type& -> std::uint32_t
TGetEdgeVertexEnd function object getting end vertex index from an edge. Getter signature: const TEdgeIter::value_type& -> std::uint32_t
Parameters
first beginning of the range of edges to add
last end of the range of edges to add
getStart getter of edge start vertex index
getEnd getter of edge end vertex index
{
    if (is_finalized()) {
        throw std::runtime_error(
            "triangulator_t was finalized with 'erase...' method. Inserting new "
            "edges is not possible");
    }
    for (; first != last; ++first) {
        // +3 to account for super-triangle vertices
        const edge_t edge(
            std::uint32_t(getStart(*first) + m_nTargetVerts),
            std::uint32_t(getEnd(*first) + m_nTargetVerts));
        insert_edge(edge, edge);
    }
    erase_dummies();
}
insert_point_in_triangle()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::stack< std::uint32_t > cdt::triangulator_t< T, TNearPointLocator >::insert_point_in_triangle (const std::uint32_t v, const std::uint32_t iT) inline
Returns indices of three resulting triangles.
    {
        const std::uint32_t iNewT1 = add_triangle();
        const std::uint32_t iNewT2 = add_triangle();
        triangle_t& t = triangles[iT];
        const std::array<std::uint32_t, 3> vv = t.vertices;
        const std::array<std::uint32_t, 3> nn = t.neighbors;
        const std::uint32_t v1 = vv[0], v2 = vv[1], v3 = vv[2];
        const std::uint32_t n1 = nn[0], n2 = nn[1], n3 = nn[2];
        // make two new triangles and convert current triangle to 3rd new
        // triangle
        using detail::arr3;
        triangles[iNewT1] = triangle_t::make(arr3(v2, v3, v), arr3(n2, iNewT2, iT));
        triangles[iNewT2] = triangle_t::make(arr3(v3, v1, v), arr3(n3, iT, iNewT1));
        t = triangle_t::make(arr3(v1, v2, v), arr3(n1, iNewT1, iNewT2));
        // make and add a new vertex
        add_adjacent_triangles(v, iT, iNewT1, iNewT2);
        // adjust lists of adjacent triangles for v1, v2, v3
        add_adjacent_triangle(v1, iNewT2);
        add_adjacent_triangle(v2, iNewT1);
        remove_adjacent_triangle(v3, iT);
        add_adjacent_triangle(v3, iNewT1);
        add_adjacent_triangle(v3, iNewT2);
        // change triangle neighbor's neighbors to new triangles
        change_neighbour(n2, iT, iNewT1);
        change_neighbour(n3, iT, iNewT2);
        // return newly added triangles
        std::stack<std::uint32_t> newTriangles;
        newTriangles.push(iT);
        newTriangles.push(iNewT1);
        newTriangles.push(iNewT2);
        return newTriangles;
    }
References cdt::triangulator_t< T, TNearPointLocator >::add_adjacent_triangle(), cdt::triangulator_t< T, TNearPointLocator >::add_adjacent_triangles(), cdt::triangulator_t< T, TNearPointLocator >::add_triangle(), cdt::detail::arr3(), cdt::triangulator_t< T, TNearPointLocator >::change_neighbour(), cdt::triangle_t::make(), cdt::triangle_t::neighbors, cdt::triangulator_t< T, TNearPointLocator >::remove_adjacent_triangle(), cdt::triangulator_t< T, TNearPointLocator >::triangles, and cdt::triangle_t::vertices.
insert_point_on_edge()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::stack< std::uint32_t > cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge (const std::uint32_t v, const std::uint32_t iT1, const std::uint32_t iT2) inline
Returns indices of four resulting triangles.
    {
        const std::uint32_t iTnew1 = add_triangle();
        const std::uint32_t iTnew2 = add_triangle();
        triangle_t& t1 = triangles[iT1];
        triangle_t& t2 = triangles[iT2];
        std::uint32_t i = get_opposite_vertex_index(t1, iT2);
        const std::uint32_t v1 = t1.vertices[i];
        const std::uint32_t v2 = t1.vertices[ccw(i)];
        const std::uint32_t n1 = t1.neighbors[i];
        const std::uint32_t n4 = t1.neighbors[cw(i)];
        i = get_opposite_vertex_index(t2, iT1);
        const std::uint32_t v3 = t2.vertices[i];
        const std::uint32_t v4 = t2.vertices[ccw(i)];
        const std::uint32_t n3 = t2.neighbors[i];
        const std::uint32_t n2 = t2.neighbors[cw(i)];
        // add new triangles and change existing ones
        using detail::arr3;
        t1 = triangle_t::make(arr3(v1, v2, v), arr3(n1, iTnew2, iTnew1));
        t2 = triangle_t::make(arr3(v3, v4, v), arr3(n3, iTnew1, iTnew2));
        triangles[iTnew1] = triangle_t::make(arr3(v1, v, v4), arr3(iT1, iT2, n4));
        triangles[iTnew2] = triangle_t::make(arr3(v3, v, v2), arr3(iT2, iT1, n2));
        // make and add new vertex
        add_adjacent_triangles(v, iT1, iTnew2, iT2, iTnew1);
        // adjust neighboring triangles and vertices
        change_neighbour(n4, iT1, iTnew1);
        change_neighbour(n2, iT2, iTnew2);
        add_adjacent_triangle(v1, iTnew1);
        add_adjacent_triangle(v3, iTnew2);
        remove_adjacent_triangle(v2, iT2);
        add_adjacent_triangle(v2, iTnew2);
        remove_adjacent_triangle(v4, iT1);
        add_adjacent_triangle(v4, iTnew1);
        // return newly added triangles
        std::stack<std::uint32_t> newTriangles;
        newTriangles.push(iT1);
        newTriangles.push(iTnew2);
        newTriangles.push(iT2);
        newTriangles.push(iTnew1);
        return newTriangles;
    }
References cdt::triangulator_t< T, TNearPointLocator >::add_adjacent_triangle(), cdt::triangulator_t< T, TNearPointLocator >::add_adjacent_triangles(), cdt::triangulator_t< T, TNearPointLocator >::add_triangle(), cdt::detail::arr3(), cdt::ccw(), cdt::triangulator_t< T, TNearPointLocator >::change_neighbour(), cdt::cw(), cdt::get_opposite_vertex_index(), cdt::triangle_t::make(), cdt::triangle_t::neighbors, cdt::triangulator_t< T, TNearPointLocator >::remove_adjacent_triangle(), cdt::triangulator_t< T, TNearPointLocator >::triangles, and cdt::triangle_t::vertices.
insert_vertex()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::insert_vertex (std::uint32_t iVert) private
{
    const vec2_<T>& v = vertices[iVert];
    std::array<std::uint32_t, 2> trisAt = walking_search_triangle_at(v);
    std::stack<std::uint32_t> triStack = (trisAt[1] == null_neighbour)
        ? insert_point_in_triangle(iVert, trisAt[0])
        : insert_point_on_edge(iVert, trisAt[0], trisAt[1]);
    enforce_delaunay_property_using_edge_flips(v, iVert, triStack);
    m_nearPtLocator.add_point(iVert, vertices);
}
References cdt::null_neighbour().
insert_vertex_and_flip_fixed_edges()
template<typename T , typename TNearPointLocator > std::vector< edge_t > cdt::triangulator_t< T, TNearPointLocator >::insert_vertex_and_flip_fixed_edges (std::uint32_t iVert) private
Flip fixed edges and return a list of flipped fixed edges.
{
    std::vector<edge_t> flippedFixedEdges;
    const vec2_<T>& v = vertices[iVert];
    std::array<std::uint32_t, 2> trisAt = walking_search_triangle_at(v);
    std::stack<std::uint32_t> triStack = trisAt[1] == null_neighbour
        ? insert_point_in_triangle(iVert, trisAt[0])
        : insert_point_on_edge(iVert, trisAt[0], trisAt[1]);
    while (!triStack.empty()) {
        const std::uint32_t iT = triStack.top();
        triStack.pop();
        const triangle_t& t = triangles[iT];
        const std::uint32_t iTopo = get_opposite_triangle_index(t, iVert);
        if (iTopo == null_neighbour)
            continue;
        /*
         *                       v3         original edge: (v1, v3)
         *                      /|\   flip-candidate edge: (v,  v2)
         *                    /  |  \
         *                  /    |    \
         *                /      |      \
         * new vertex--> v       |       v2
         *                \      |      /
         *                  \    |    /
         *                    \  |  /
         *                      \|/
         *                       v1
         */
        const triangle_t& tOpo = triangles[iTopo];
        const std::uint32_t i = get_opposite_vertex_index(tOpo, iT);
        const std::uint32_t iV2 = tOpo.vertices[i];
        const std::uint32_t iV1 = tOpo.vertices[cw(i)];
        const std::uint32_t iV3 = tOpo.vertices[ccw(i)];
        if (check_is_edgeflip_needed(v, iVert, iV1, iV2, iV3)) {
            // if flipped edge is fixed, remember it
            const edge_t flippedEdge(iV1, iV3);
            if (fixedEdges.count(flippedEdge))
                flippedFixedEdges.push_back(flippedEdge);
            do_edgeflip(iT, iTopo);
            triStack.push(iT);
            triStack.push(iTopo);
        }
    }
    m_nearPtLocator.add_point(iVert, vertices);
    return flippedFixedEdges;
}
References cdt::ccw(), cdt::cw(), cdt::get_opposite_triangle_index(), cdt::get_opposite_vertex_index(), cdt::null_neighbour(), and cdt::triangle_t::vertices.
insert_vertices() [1/2]
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::insert_vertices (const std::vector< vec2_< T > > & vertices)
Insert vertices into triangulation
Parameters
vertices vector of vertices to insert
{
    return insert_vertices(
        newVertices.begin(), newVertices.end(), get_x_coord_vec2d<T>, get_y_coord_vec2d<T>);
}
insert_vertices() [2/2]
template<typename T , typename TNearPointLocator > template<typename TVertexIter , typename TGetVertexCoordX , typename TGetVertexCoordY > void cdt::triangulator_t< T, TNearPointLocator >::insert_vertices (TVertexIter first, TVertexIter last, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord)
Insert custom point-types specified by iterator range and X/Y-getters
Template Parameters
TVertexIter iterator that dereferences to custom point type
TGetVertexCoordX function object getting x coordinate from vertex. Getter signature: const TVertexIter::value_type& -> T
TGetVertexCoordY function object getting y coordinate from vertex. Getter signature: const TVertexIter::value_type& -> T
Parameters
first beginning of the range of vertices to add
last end of the range of vertices to add
get_x_coord getter of X-coordinate
get_y_coord getter of Y-coordinate
{
    if (is_finalized()) {
        throw std::runtime_error(
            "triangulator_t was finalized with 'erase...' method. Inserting new "
            "vertices is not possible");
    }
    detail::randGenerator.seed(9001); // ensure deterministic behavior
    if (vertices.empty()) {
        add_super_triangle(expand_with_points<T>(first, last, get_x_coord, get_y_coord));
    }
    const std::size_t nExistingVerts = vertices.size();
    vertices.reserve(nExistingVerts + std::distance(first, last));
    for (TVertexIter it = first; it != last; ++it) {
        create_vertex(vec2_<T>::make(get_x_coord(*it), get_y_coord(*it)), std::vector<std::uint32_t>());
    }
    switch (m_vertexInsertionOrder) {
    case vertex_insertion_order_t::AS_GIVEN: {
        for (TVertexIter it = first; it != last; ++it) {
            insert_vertex(std::uint32_t(nExistingVerts + std::distance(first, it)));
        }
        break;
    }
    case vertex_insertion_order_t::RANDOM: {
        std::vector<std::uint32_t> ii(std::distance(first, last));
        typedef std::vector<std::uint32_t>::iterator Iter;
        std::uint32_t value = static_cast<std::uint32_t>(nExistingVerts);
        for (Iter it = ii.begin(); it != ii.end(); ++it, ++value)
            *it = value;
        detail::random_shuffle(ii.begin(), ii.end());
        for (Iter it = ii.begin(); it != ii.end(); ++it)
            insert_vertex(*it);
        break;
    }
    }
}
References cdt::vertex_insertion_order_t::AS_GIVEN, std::distance(), cdt::detail::randGenerator(), cdt::vertex_insertion_order_t::RANDOM, and cdt::detail::random_shuffle().
is_finalized()
template<typename T , typename TNearPointLocator > bool cdt::triangulator_t< T, TNearPointLocator >::is_finalized
Check if the triangulation was finalized with erase... method and super-triangle was removed.
Returns
true if triangulation is finalized, false otherwise
{
    return vertTris.empty() && !vertices.empty();
}
make_dummies()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> void cdt::triangulator_t< T, TNearPointLocator >::make_dummies (const std::uint32_t iT) inline private
Flag triangle as dummy
Note
Advanced method for manually modifying the triangulation from outside. Please call it when you know what you are doing.
Parameters
iT index of a triangle to flag
    {
        const triangle_t& t = triangles[iT];
        typedef std::array<std::uint32_t, 3>::const_iterator VCit;
        for (VCit iV = t.vertices.begin(); iV != t.vertices.end(); ++iV)
            remove_adjacent_triangle(*iV, iT);
        typedef std::array<std::uint32_t, 3>::const_iterator NCit;
        for (NCit iTn = t.neighbors.begin(); iTn != t.neighbors.end(); ++iTn)
            change_neighbour(*iTn, iT, null_neighbour);
        m_dummyTris.push_back(iT);
    }
References cdt::triangulator_t< T, TNearPointLocator >::change_neighbour(), cdt::triangulator_t< T, TNearPointLocator >::m_dummyTris, cdt::triangle_t::neighbors, cdt::null_neighbour(), cdt::triangulator_t< T, TNearPointLocator >::remove_adjacent_triangle(), cdt::triangulator_t< T, TNearPointLocator >::triangles, and cdt::triangle_t::vertices.
peel_layer()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::unordered_map< std::uint32_t, layer_depth_t > cdt::triangulator_t< T, TNearPointLocator >::peel_layer (std::stack< std::uint32_t > seeds, const layer_depth_t layerDepth, std::vector< layer_depth_t > & triDepths) const inline private
Depth-peel a layer in triangulation, used when calculating triangle depths
It takes starting seed triangles, traverses neighboring triangles, and assigns given layer depth to the traversed triangles. Traversal is blocked by constraint edges. Triangles behind constraint edges are recorded as seeds of next layer and returned from the function.
Parameters
seeds indices of seed triangles
layerDepth current layer's depth to mark triangles with
[in,out] triDepths depths of triangles
Returns
triangles of the deeper layers that are adjacent to the peeled layer. To be used as seeds when peeling deeper layers.
    {
        std::unordered_map<std::uint32_t, layer_depth_t> behindBoundary;
        while (!seeds.empty()) {
            const std::uint32_t iT = seeds.top();
            seeds.pop();
            triDepths[iT] = layerDepth;
            behindBoundary.erase(iT);
            const triangle_t& t = triangles[iT];
            for (std::uint32_t i(0); i < std::uint32_t(3); ++i) {
                const edge_t opEdge(t.vertices[ccw(i)], t.vertices[cw(i)]);
                const std::uint32_t iN = t.neighbors[get_opposite_neighbour_from_vertex(i)];
                if (iN == null_neighbour || triDepths[iN] <= layerDepth)
                    continue;
                if (fixedEdges.count(opEdge)) {
                    const std::unordered_map<edge_t, layer_depth_t>::const_iterator cit = overlapCount.find(opEdge);
                    const layer_depth_t triDepth = cit == overlapCount.end()
                        ? layerDepth + 1
                        : layerDepth + cit->second + 1;
                    behindBoundary[iN] = triDepth;
                    continue;
                }
                seeds.push(iN);
            }
        }
        return behindBoundary;
    }
References cdt::ccw(), cdt::cw(), cdt::triangulator_t< T, TNearPointLocator >::fixedEdges, cdt::get_opposite_neighbour_from_vertex(), cdt::triangle_t::neighbors, cdt::null_neighbour(), cdt::triangulator_t< T, TNearPointLocator >::overlapCount, cdt::triangulator_t< T, TNearPointLocator >::triangles, and cdt::triangle_t::vertices.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::calculate_triangle_depths().
pseudo_polygon_outer_triangle()
template<typename T , typename TNearPointLocator > std::uint32_t cdt::triangulator_t< T, TNearPointLocator >::pseudo_polygon_outer_triangle (std::uint32_t ia, std::uint32_t ib) const private
{
    const std::vector<std::uint32_t>& aTris = vertTris[ia];
    const std::vector<std::uint32_t>& bTris = vertTris[ib];
    for (std::vector<std::uint32_t>::const_iterator it = aTris.begin(); it != aTris.end(); ++it)
    {
        if (std::find(bTris.begin(), bTris.end(), *it) != bTris.end())
        {
            return *it;
        }
    }
    return null_neighbour;
}
References cdt::null_neighbour().
remove_adjacent_triangle()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::remove_adjacent_triangle (std::uint32_t iVertex, std::uint32_t iTriangle) private
{
    std::vector<std::uint32_t>& tris = vertTris[iVertex];
    tris.erase(std::find(tris.begin(), tris.end(), iTriangle));
}
Referenced by cdt::triangulator_t< T, TNearPointLocator >::insert_point_in_triangle(), cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge(), and cdt::triangulator_t< T, TNearPointLocator >::make_dummies().
TintersectedTriangle()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::tuple< std::uint32_t, std::uint32_t, std::uint32_t > cdt::triangulator_t< T, TNearPointLocator >::TintersectedTriangle (const std::uint32_t iA, const std::vector< std::uint32_t > & candidates, const vec2_< T > & a, const vec2_< T > & b, const T orientationTolerance = T(0)) const inline
Returns:
intersected triangle index
index of point on the left of the line
index of point on the right of the line If left point is right on the line: no triangle is intersected:
triangle index is no-neighbor (invalid)
index of point on the line
index of point on the right of the line
    {
        typedef std::vector<std::uint32_t>::const_iterator TriIndCit;
        for (TriIndCit it = candidates.begin(); it != candidates.end(); ++it) {
            const std::uint32_t iT = *it;
            const triangle_t t = triangles[iT];
            const std::uint32_t i = get_vertex_index(t, iA);
            const std::uint32_t iP2 = t.vertices[ccw(i)];
            const T orientP2 = orient2D(vertices[iP2], a, b);
            const point_to_line_location_t::Enum locP2 = classify_orientation(orientP2);
            if (locP2 == point_to_line_location_t::RIGHT_SIDE) {
                const std::uint32_t iP1 = t.vertices[cw(i)];
                const T orientP1 = orient2D(vertices[iP1], a, b);
                const point_to_line_location_t::Enum locP1 = classify_orientation(orientP1);
                if (locP1 == point_to_line_location_t::COLLINEAR) {
                    return std::make_tuple(null_neighbour, iP1, iP1);
                }
                if (locP1 == point_to_line_location_t::LEFT_SIDE) {
                    if (orientationTolerance) {
                        T closestOrient;
                        std::uint32_t iClosestP;
                        if (std::abs(orientP1) <= std::abs(orientP2)) {
                            closestOrient = orientP1;
                            iClosestP = iP1;
                        } else {
                            closestOrient = orientP2;
                            iClosestP = iP2;
                        }
                        if (classify_orientation(
                                closestOrient, orientationTolerance)
                            == point_to_line_location_t::COLLINEAR) {
                            return std::make_tuple(null_neighbour, iClosestP, iClosestP);
                        }
                    }
                    return std::make_tuple(iT, iP1, iP2);
                }
            }
        }
        throw std::runtime_error("Could not find vertex triangle intersected by "
                                 "edge. Note: can be caused by duplicate points.");
    }
References cdt::ccw(), cdt::classify_orientation(), cdt::point_to_line_location_t::COLLINEAR, cdt::cw(), cdt::get_vertex_index(), cdt::point_to_line_location_t::LEFT_SIDE, cdt::null_neighbour(), cdt::point_to_line_location_t::RIGHT_SIDE, cdt::triangulator_t< T, TNearPointLocator >::triangles, cdt::triangulator_t< T, TNearPointLocator >::vertices, and cdt::triangle_t::vertices.
trianglesAt()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::array< std::uint32_t, 2 > cdt::triangulator_t< T, TNearPointLocator >::trianglesAt (const vec2_< T > & pos) const inline
    {
        std::array<std::uint32_t, 2> out = { null_neighbour, null_neighbour };
        for (std::uint32_t i = std::uint32_t(0); i < std::uint32_t(triangles.size()); ++i) {
            const triangle_t& t = triangles[i];
            const vec2_<T>& v1 = vertices[t.vertices[0]];
            const vec2_<T>& v2 = vertices[t.vertices[1]];
            const vec2_<T>& v3 = vertices[t.vertices[2]];
            const point_to_triangle_location_t::Enum loc = locate_point_wrt_triangle(pos, v1, v2, v3);
            if (loc == point_to_triangle_location_t::OUTSIDE)
                continue;
            out[0] = i;
            if (check_on_edge(loc))
                out[1] = t.neighbors[edge_neighbour(loc)];
            return out;
        }
        throw std::runtime_error("No triangle was found at position");
    }
References cdt::check_on_edge(), cdt::edge_neighbour(), cdt::locate_point_wrt_triangle(), cdt::triangle_t::neighbors, cdt::null_neighbour(), out, cdt::point_to_triangle_location_t::OUTSIDE, cdt::triangulator_t< T, TNearPointLocator >::triangles, cdt::triangulator_t< T, TNearPointLocator >::vertices, and cdt::triangle_t::vertices.
triangulate_pseudo_polygon()
template<typename T , typename TNearPointLocator > std::uint32_t cdt::triangulator_t< T, TNearPointLocator >::triangulate_pseudo_polygon (std::uint32_t ia, std::uint32_t ib, std::vector< std::uint32_t >::const_iterator pointsFirst, std::vector< std::uint32_t >::const_iterator pointsLast) private
{
    if (pointsFirst == pointsLast)
        return pseudo_polygon_outer_triangle(ia, ib);
    // Find delaunay point
    const std::uint32_t ic = find_delaunay_point(ia, ib, pointsFirst, pointsLast);
    // Find pseudopolygons split by the delaunay point
    std::vector<std::uint32_t>::const_iterator newLast = pointsFirst;
    while (*newLast != ic) {
        ++newLast;
    }
    const std::vector<std::uint32_t>::const_iterator newFirst = newLast + 1;
    // triangulate splitted pseudo-polygons
    const std::uint32_t iT2 = triangulate_pseudo_polygon(ic, ib, newFirst, pointsLast);
    const std::uint32_t iT1 = triangulate_pseudo_polygon(ia, ic, pointsFirst, newLast);
    // add new triangle
    const triangle_t t = { { ia, ib, ic }, { null_neighbour, iT2, iT1 } };
    const std::uint32_t iT = add_triangle(t);
    // adjust neighboring triangles and vertices
    if (iT1 != null_neighbour) {
        if (pointsFirst == newLast) {
            change_neighbour(iT1, ia, ic, iT);
        } else {
            triangles[iT1].neighbors[0] = iT;
        }
    }
    if (iT2 != null_neighbour) {
        if (newFirst == pointsLast) {
            change_neighbour(iT2, ic, ib, iT);
        } else {
            triangles[iT2].neighbors[0] = iT;
        }
    }
    add_adjacent_triangle(ia, iT);
    add_adjacent_triangle(ib, iT);
    add_adjacent_triangle(ic, iT);
    return iT;
}
References cdt::null_neighbour().
walk_triangles()
template<typename T , typename TNearPointLocator > std::uint32_t cdt::triangulator_t< T, TNearPointLocator >::walk_triangles (std::uint32_t startVertex, const vec2_< T > & pos) const private
{
    // begin walk in search of triangle at pos
    std::uint32_t currTri = vertTris[startVertex][0];
    std::unordered_set<std::uint32_t> visited;
    bool found = false;
    while (!found) {
        const triangle_t& t = triangles[currTri];
        found = true;
        // stochastic offset to randomize which edge we check first
        const std::uint32_t offset(detail::randGenerator() % 3);
        for (std::uint32_t i_(0); i_ < std::uint32_t(3); ++i_) {
            const std::uint32_t i((i_ + offset) % 3);
            const vec2_<T>& vStart = vertices[t.vertices[i]];
            const vec2_<T>& vEnd = vertices[t.vertices[ccw(i)]];
            const point_to_line_location_t::Enum edgeCheck = locate_point_wrt_line(pos, vStart, vEnd);
            if (edgeCheck == point_to_line_location_t::RIGHT_SIDE && t.neighbors[i] != null_neighbour && visited.insert(t.neighbors[i]).second) {
                found = false;
                currTri = t.neighbors[i];
                break;
            }
        }
    }
    return currTri;
}
References cdt::ccw(), cdt::locate_point_wrt_line(), cdt::triangle_t::neighbors, cdt::null_neighbour(), cdt::detail::randGenerator(), cdt::point_to_line_location_t::RIGHT_SIDE, and cdt::triangle_t::vertices.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at().
walking_search_triangle_at()
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::array< std::uint32_t, 2 > cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at (const vec2_< T > & pos) const inline
    {
        std::array<std::uint32_t, 2> out = { null_neighbour, null_neighbour };
        // Query  for a vertex close to pos, to start the search
        const std::uint32_t startVertex = m_nearPtLocator.nearPoint(pos, vertices);
        const std::uint32_t iT = walk_triangles(startVertex, pos);
        // Finished walk, locate point in current triangle
        const triangle_t& t = triangles[iT];
        const vec2_<T>& v1 = vertices[t.vertices[0]];
        const vec2_<T>& v2 = vertices[t.vertices[1]];
        const vec2_<T>& v3 = vertices[t.vertices[2]];
        const point_to_triangle_location_t::Enum loc = locate_point_wrt_triangle(pos, v1, v2, v3);
        if (loc == point_to_triangle_location_t::OUTSIDE)
            throw std::runtime_error("No triangle was found at position");
        out[0] = iT;
        if (check_on_edge(loc))
            out[1] = t.neighbors[edge_neighbour(loc)];
        return out;
    }
References cdt::check_on_edge(), cdt::edge_neighbour(), cdt::locate_point_wrt_triangle(), cdt::triangulator_t< T, TNearPointLocator >::m_nearPtLocator, cdt::triangle_t::neighbors, cdt::null_neighbour(), out, cdt::point_to_triangle_location_t::OUTSIDE, cdt::triangulator_t< T, TNearPointLocator >::triangles, cdt::triangulator_t< T, TNearPointLocator >::vertices, cdt::triangle_t::vertices, and cdt::triangulator_t< T, TNearPointLocator >::walk_triangles().
Member Data Documentation
fixedEdges
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::unordered_set<edge_t> cdt::triangulator_t< T, TNearPointLocator >::fixedEdges
triangulation's constraints (fixed edges)
Referenced by cdt::triangulator_t< T, TNearPointLocator >::fixEdge(), cdt::triangulator_t< T, TNearPointLocator >::fixEdge(), and cdt::triangulator_t< T, TNearPointLocator >::peel_layer().
m_dummyTris
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::vector<std::uint32_t> cdt::triangulator_t< T, TNearPointLocator >::m_dummyTris private
Referenced by cdt::triangulator_t< T, TNearPointLocator >::erase_dummies(), and cdt::triangulator_t< T, TNearPointLocator >::make_dummies().
m_intersectingEdgesStrategy
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> action_on_intersecting_constraint_edges_t::Enum cdt::triangulator_t< T, TNearPointLocator >::m_intersectingEdgesStrategy private
m_minDistToConstraintEdge
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> T cdt::triangulator_t< T, TNearPointLocator >::m_minDistToConstraintEdge private
m_nearPtLocator
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> TNearPointLocator cdt::triangulator_t< T, TNearPointLocator >::m_nearPtLocator private
Referenced by cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at().
m_nTargetVerts
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::size_t cdt::triangulator_t< T, TNearPointLocator >::m_nTargetVerts private
m_superGeomType
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> super_geometry_type_t::Enum cdt::triangulator_t< T, TNearPointLocator >::m_superGeomType private
m_vertexInsertionOrder
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> vertex_insertion_order_t::Enum cdt::triangulator_t< T, TNearPointLocator >::m_vertexInsertionOrder private
overlapCount
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::unordered_map<edge_t, boundary_overlap_count_t> cdt::triangulator_t< T, TNearPointLocator >::overlapCount
Stores count of overlapping boundaries for a fixed edge. If no entry is present for an edge: no boundaries overlap.
Note
map only has entries for fixed for edges that represent overlapping boundaries
needed for handling depth calculations and hole-removel in case of overlapping boundaries
Referenced by cdt::triangulator_t< T, TNearPointLocator >::fixEdge(), cdt::triangulator_t< T, TNearPointLocator >::fixEdge(), and cdt::triangulator_t< T, TNearPointLocator >::peel_layer().
pieceToOriginals
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::unordered_map<edge_t, std::vector<edge_t> > cdt::triangulator_t< T, TNearPointLocator >::pieceToOriginals
Stores list of original edges represented by a given fixed edge
Note
map only has entries for edges where multiple original fixed edges overlap or where a fixed edge is a part of original edge created by conforming Delaunay triangulation vertex insertion
Referenced by cdt::triangulator_t< T, TNearPointLocator >::fixEdge().
triangles
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::vector<triangle_t> cdt::triangulator_t< T, TNearPointLocator >::triangles
triangulation's triangles
Referenced by cdt::triangulator_t< T, TNearPointLocator >::calculate_triangle_depths(), cdt::triangulator_t< T, TNearPointLocator >::erase_dummies(), cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle(), cdt::triangulator_t< T, TNearPointLocator >::insert_point_in_triangle(), cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge(), cdt::triangulator_t< T, TNearPointLocator >::make_dummies(), cdt::triangulator_t< T, TNearPointLocator >::peel_layer(), cdt::triangulator_t< T, TNearPointLocator >::TintersectedTriangle(), cdt::triangulator_t< T, TNearPointLocator >::trianglesAt(), and cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at().
vertices
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::vector<vec2_<T> > cdt::triangulator_t< T, TNearPointLocator >::vertices
triangulation's vertices
Referenced by cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle(), cdt::triangulator_t< T, TNearPointLocator >::TintersectedTriangle(), cdt::triangulator_t< T, TNearPointLocator >::trianglesAt(), and cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at().
vertTris
template<typename T , typename TNearPointLocator = locator_kdtree_t<T>> std::vector<std::vector<std::uint32_t> > cdt::triangulator_t< T, TNearPointLocator >::vertTris
triangles adjacent to each vertex
Note
will be reset to empty when super-triangle is removed and triangulation is finalized. To re-calculate adjacent triangles use cdt::get_vertex_to_triangles_map helper
Referenced by cdt::triangulator_t< T, TNearPointLocator >::calculate_triangle_depths(), and cdt::triangulator_t< T, TNearPointLocator >::erase_dummies().
Typedef Documentation
boundary_overlap_count_t
typedef layer_depth_t cdt::boundary_overlap_count_t
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
layer_depth_t
typedef unsigned short cdt::layer_depth_t
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Type used for storing layer depths for triangles
Note
layer_depth_t should support 60K+ layers, which could be to much or too little for some use cases. Feel free to re-define this typedef.
Function Documentation
hid_close()
void HID_API_EXPORT HID_API_CALL hid_close (hid_device * dev)
#include <src/hidapi/include/hidapi.h>
Close a HID device.
Parameters
dev A device handle returned from hid_open().
{
  if (!dev)
    return;
  close(dev->device_handle);
  free(dev);
}
References hid_device_::device_handle, hid_device_::disconnected, free_hid_device(), hid_device_::input_report_buf, hid_device_::input_reports, hid_device_::max_input_report_len, hid_device_::mutex, NULL, pthread_barrier_wait(), return_data(), hid_device_::run_loop, hid_device_::run_loop_mode, hid_device_::shutdown_barrier, hid_device_::shutdown_thread, hid_device_::source, and hid_device_::thread.
Referenced by Slic3r::GUI::Mouse3DController::connect_device(), and Slic3r::GUI::Mouse3DController::disconnect_device().
hid_enumerate()
struct hid_device_info HID_API_EXPORT *HID_API_CALL hid_enumerate (unsigned short vendor_id, unsigned short product_id)
#include <src/hidapi/include/hidapi.h>
Enumerate the HID Devices.
This function returns a linked list of all the HID devices attached to the system which match vendor_id and product_id. If vendor_id is set to 0 then any vendor matches. If product_id is set to 0 then any product matches. If vendor_id and product_id are both set to 0, then all HID devices will be returned.
Parameters
vendor_id The Vendor ID (VID) of the types of device to open.
product_id The Product ID (PID) of the types of device to open.
Returns
This function returns a pointer to a linked list of type struct hid_device_info, containing information about the HID devices attached to the system, or NULL in the case of failure. Free this linked list by calling hid_free_enumeration().
{
  struct udev *udev;
  struct udev_enumerate *enumerate;
  struct udev_list_entry *devices, *dev_list_entry;
  struct hid_device_info *root = NULL; /* return object */
  struct hid_device_info *cur_dev = NULL;
  struct hid_device_info *prev_dev = NULL; /* previous device */
  hid_init();
  /* Create the udev object */
  udev = hid_wrapper_udev_new();
  if (!udev) {
    printf("Can't create udev\n");
    return NULL;
  }
  /* Create a list of the devices in the 'hidraw' subsystem. */
  enumerate = hid_wrapper_udev_enumerate_new(udev);
  hid_wrapper_udev_enumerate_add_match_subsystem(enumerate, "hidraw");
  hid_wrapper_udev_enumerate_scan_devices(enumerate);
  devices = hid_wrapper_udev_enumerate_get_list_entry(enumerate);
  /* For each item, see if it matches the vid/pid, and if so
     create a udev_device record for it */
    for (dev_list_entry = devices; dev_list_entry; dev_list_entry = hid_wrapper_udev_list_entry_get_next(dev_list_entry)) {
    const char *sysfs_path;
    const char *dev_path;
    const char *str;
    struct udev_device *raw_dev; /* The device's hidraw udev node. */
    struct udev_device *hid_dev; /* The device's HID udev node. */
    struct udev_device *usb_dev; /* The device's USB udev node. */
    struct udev_device *intf_dev; /* The device's interface (in the USB sense). */
    unsigned short dev_vid;
    unsigned short dev_pid;
    char *serial_number_utf8 = NULL;
    char *product_name_utf8 = NULL;
    int bus_type;
    int result;
    /* Get the filename of the /sys entry for the device
       and create a udev_device object (dev) representing it */
    sysfs_path = hid_wrapper_udev_list_entry_get_name(dev_list_entry);
    raw_dev = hid_wrapper_udev_device_new_from_syspath(udev, sysfs_path);
    dev_path = hid_wrapper_udev_device_get_devnode(raw_dev);
    hid_dev = hid_wrapper_udev_device_get_parent_with_subsystem_devtype(
      raw_dev,
      "hid",
      NULL);
    if (!hid_dev) {
      /* Unable to find parent hid device. */
      goto next;
    }
    result = parse_uevent_info(
      hid_wrapper_udev_device_get_sysattr_value(hid_dev, "uevent"),
      &bus_type,
      &dev_vid,
      &dev_pid,
      &serial_number_utf8,
      &product_name_utf8);
    if (!result) {
      /* parse_uevent_info() failed for at least one field. */
      goto next;
    }
    if (bus_type != BUS_USB && bus_type != BUS_BLUETOOTH) {
      /* We only know how to handle USB and BT devices. */
      goto next;
    }
    /* Check the VID/PID against the arguments */
    if ((vendor_id == 0x0 || vendor_id == dev_vid) &&
        (product_id == 0x0 || product_id == dev_pid)) {
      struct hid_device_info *tmp;
      /* VID/PID match. Create the record. */
      tmp = malloc(sizeof(struct hid_device_info));
      if (cur_dev) {
        cur_dev->next = tmp;
      }
      else {
        root = tmp;
      }
      prev_dev = cur_dev;
      cur_dev = tmp;
      /* Fill out the record */
      cur_dev->next = NULL;
      cur_dev->path = dev_path? strdup(dev_path): NULL;
      /* VID/PID */
      cur_dev->vendor_id = dev_vid;
      cur_dev->product_id = dev_pid;
      /* Serial Number */
      cur_dev->serial_number = utf8_to_wchar_t(serial_number_utf8);
      /* Release Number */
      cur_dev->release_number = 0x0;
      /* Interface Number */
      cur_dev->interface_number = -1;
      switch (bus_type) {
        case BUS_USB:
          /* The device pointed to by raw_dev contains information about
             the hidraw device. In order to get information about the
             USB device, get the parent device with the
             subsystem/devtype pair of "usb"/"usb_device". This will
             be several levels up the tree, but the function will find
             it. */
          usb_dev = hid_wrapper_udev_device_get_parent_with_subsystem_devtype(
              raw_dev,
              "usb",
              "usb_device");
          if (!usb_dev) {
            /* Free this device */
            free(cur_dev->serial_number);
            free(cur_dev->path);
            free(cur_dev);
            /* Take it off the device list. */
            if (prev_dev) {
              prev_dev->next = NULL;
              cur_dev = prev_dev;
            }
            else {
              cur_dev = root = NULL;
            }
            goto next;
          }
          /* Manufacturer and Product strings */
          cur_dev->manufacturer_string = copy_udev_string(usb_dev, device_string_names[DEVICE_STRING_MANUFACTURER]);
          cur_dev->product_string = copy_udev_string(usb_dev, device_string_names[DEVICE_STRING_PRODUCT]);
          /* Release Number */
          str = hid_wrapper_udev_device_get_sysattr_value(usb_dev, "bcdDevice");
          cur_dev->release_number = (str)? strtol(str, NULL, 16): 0x0;
          /* Get a handle to the interface's udev node. */
          intf_dev = hid_wrapper_udev_device_get_parent_with_subsystem_devtype(
              raw_dev,
              "usb",
              "usb_interface");
          if (intf_dev) {
            str = hid_wrapper_udev_device_get_sysattr_value(intf_dev, "bInterfaceNumber");
            cur_dev->interface_number = (str)? strtol(str, NULL, 16): -1;
          }
          break;
        case BUS_BLUETOOTH:
          /* Manufacturer and Product strings */
          cur_dev->manufacturer_string = wcsdup(L"");
          cur_dev->product_string = utf8_to_wchar_t(product_name_utf8);
          break;
        default:
          /* Unknown device type - this should never happen, as we
           * check for USB and Bluetooth devices above */
          break;
      }
    }
  next:
    free(serial_number_utf8);
    free(product_name_utf8);
    hid_wrapper_udev_device_unref(raw_dev);
    /* hid_dev, usb_dev and intf_dev don't need to be (and can't be)
       unref()d.  It will cause a double-free() error.  I'm not
       sure why.  */
  }
  /* Free the enumerator and udev objects. */
  hid_wrapper_udev_enumerate_unref(enumerate);
  hid_wrapper_udev_unref(udev);
  return root;
}
References BUF_LEN, copy_udev_string(), DEVICE_STRING_MANUFACTURER, device_string_names, DEVICE_STRING_PRODUCT, dup_wcs(), FALSE, get_int_property(), get_manufacturer_string(), get_product_id(), get_product_string(), get_serial_number(), get_vendor_id(), hid_init(), hid_mgr, hid_wrapper_udev_device_get_devnode, hid_wrapper_udev_device_get_parent_with_subsystem_devtype, hid_wrapper_udev_device_get_sysattr_value, hid_wrapper_udev_device_new_from_syspath, hid_wrapper_udev_device_unref, hid_wrapper_udev_enumerate_add_match_subsystem, hid_wrapper_udev_enumerate_get_list_entry, hid_wrapper_udev_enumerate_new, hid_wrapper_udev_enumerate_scan_devices, hid_wrapper_udev_enumerate_unref, hid_wrapper_udev_list_entry_get_name, hid_wrapper_udev_list_entry_get_next, hid_wrapper_udev_new, hid_wrapper_udev_unref, hidapi_IOHIDDeviceGetService(), HidD_FreePreparsedData, HidD_GetAttributes, HidD_GetManufacturerString, HidD_GetPreparsedData, HidD_GetProductString, HidD_GetSerialNumberString, HidP_GetCaps, HIDP_STATUS_SUCCESS, hid_device_info::interface_number, L, hid_device_info::manufacturer_string, memset, hid_device_info::next, NULL, open_device(), parse_uevent_info(), hid_device_info::path, process_pending_events(), hid_device_info::product_id, hid_device_info::product_string, _HIDD_ATTRIBUTES::ProductID, hid_device_info::release_number, hid_device_info::serial_number, _HIDD_ATTRIBUTES::Size, hid_device_info::usage, _HIDP_CAPS::Usage, hid_device_info::usage_page, _HIDP_CAPS::UsagePage, utf8_to_wchar_t(), hid_device_info::vendor_id, _HIDD_ATTRIBUTES::VendorID, _HIDD_ATTRIBUTES::VersionNumber, and WSTR_LEN.
Referenced by Slic3r::GUI::Mouse3DController::connect_device(), and hid_open().
hid_error()
HID_API_EXPORT const wchar_t *HID_API_CALL hid_error (hid_device * dev)
#include <src/hidapi/include/hidapi.h>
Get a string describing the last error which occurred.
Parameters
dev A device handle returned from hid_open().
Returns
This function returns a string containing the last error which occurred or NULL if none has occurred.
{
  return NULL;
}
References hid_device_::last_error_str, and NULL.
hid_exit()
int HID_API_EXPORT HID_API_CALL hid_exit (void)
#include <src/hidapi/include/hidapi.h>
Finalize the HIDAPI library.
This function frees all of the static data associated with HIDAPI. It should be called at the end of execution to avoid memory leaks.
Returns
This function returns 0 on success and -1 on error.
{
  /* Nothing to do for this in the Linux/hidraw implementation. */
  hid_wrapper_udev_close();
  return 0;
}
References FALSE, hid_mgr, hid_wrapper_udev_close(), initialized, lib_handle, and NULL.
Referenced by hid_init(), and Slic3r::GUI::Mouse3DController::run().
hid_free_enumeration()
void HID_API_EXPORT HID_API_CALL hid_free_enumeration (struct hid_device_info * devs)
#include <src/hidapi/include/hidapi.h>
Free an enumeration Linked List.
This function frees a linked list created by hid_enumerate().
Parameters
devs Pointer to a list of struct_device returned from hid_enumerate().
{
  struct hid_device_info *d = devs;
  while (d) {
    struct hid_device_info *next = d->next;
    free(d->path);
    free(d->serial_number);
    free(d->manufacturer_string);
    free(d->product_string);
    free(d);
    d = next;
  }
}
References hid_device_info::next.
Referenced by Slic3r::GUI::Mouse3DController::connect_device(), and hid_open().
hid_get_feature_report()
int HID_API_EXPORT HID_API_CALL hid_get_feature_report (hid_device * dev, unsigned char * data, size_t length)
#include <src/hidapi/include/hidapi.h>
Get a feature report from a HID device.
Set the first byte of data[] to the Report ID of the report to be read. Make sure to allow space for this extra byte in data[]. Upon return, the first byte will still contain the Report ID, and the report data will start in data[1].
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into, including the Report ID. Set the first byte of data[] to the Report ID of the report to be read, or set it to zero if your device does not use numbered reports.
length The number of bytes to read, including an extra byte for the report ID. The buffer can be longer than the actual report.
Returns
This function returns the number of bytes read plus one for the report ID (which is still in the first byte), or -1 on error.
{
  int res;
  res = ioctl(dev->device_handle, HIDIOCGFEATURE(length), data);
  if (res < 0)
    perror("ioctl (GFEATURE)");
  return res;
}
References hid_device_::device_handle, hid_device_::disconnected, HidD_GetFeature, HIDIOCGFEATURE, IOCTL_HID_GET_FEATURE, length(), memset, register_error(), and TRUE.
hid_get_indexed_string()
int HID_API_EXPORT_CALL hid_get_indexed_string (hid_device * dev, int string_index, wchar_t * string, size_t maxlen)
#include <src/hidapi/include/hidapi.h>
Get a string from a HID device, based on its string index.
Parameters
dev A device handle returned from hid_open().
string_index The index of the string to get.
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
{
  return -1;
}
References hid_device_::device_handle, HidD_GetIndexedString, MAX_STRING_WCHARS, MIN, and register_error().
hid_get_manufacturer_string()
int HID_API_EXPORT_CALL hid_get_manufacturer_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <src/hidapi/include/hidapi.h>
Get The Manufacturer String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
{
  return get_device_string(dev, DEVICE_STRING_MANUFACTURER, string, maxlen);
}
References hid_device_::device_handle, DEVICE_STRING_MANUFACTURER, get_device_string(), get_manufacturer_string(), HidD_GetManufacturerString, MAX_STRING_WCHARS, MIN, and register_error().
Referenced by Slic3r::GUI::Mouse3DController::connect_device().
hid_get_product_string()
int HID_API_EXPORT_CALL hid_get_product_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <src/hidapi/include/hidapi.h>
Get The Product String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
{
  return get_device_string(dev, DEVICE_STRING_PRODUCT, string, maxlen);
}
References hid_device_::device_handle, DEVICE_STRING_PRODUCT, get_device_string(), get_product_string(), HidD_GetProductString, MAX_STRING_WCHARS, MIN, and register_error().
Referenced by Slic3r::GUI::Mouse3DController::connect_device().
hid_get_serial_number_string()
int HID_API_EXPORT_CALL hid_get_serial_number_string (hid_device * dev, wchar_t * string, size_t maxlen)
#include <src/hidapi/include/hidapi.h>
Get The Serial Number String from a HID device.
Parameters
dev A device handle returned from hid_open().
string A wide string buffer to put the data into.
maxlen The length of the buffer in multiples of wchar_t.
Returns
This function returns 0 on success and -1 on error.
{
  return get_device_string(dev, DEVICE_STRING_SERIAL, string, maxlen);
}
References hid_device_::device_handle, DEVICE_STRING_SERIAL, get_device_string(), get_serial_number(), HidD_GetSerialNumberString, MAX_STRING_WCHARS, MIN, and register_error().
hid_init()
int HID_API_EXPORT HID_API_CALL hid_init (void)
#include <src/hidapi/include/hidapi.h>
Initialize the HIDAPI library.
This function initializes the HIDAPI library. Calling it is not strictly necessary, as it will be called automatically by hid_enumerate() and any of the hid_open_*() functions if it is needed. This function should be called at the beginning of execution however, if there is a chance of HIDAPI handles being opened by different threads simultaneously.
Returns
This function returns 0 on success and -1 on error.
{
  const char *locale;
  /* Set the locale if it's not set. */
  locale = setlocale(LC_CTYPE, NULL);
  if (!locale)
    setlocale(LC_CTYPE, "");
  kernel_version = detect_kernel_version();
  return hid_wrapper_udev_init();
}
References detect_kernel_version(), hid_exit(), hid_mgr, hid_wrapper_udev_init(), init_hid_manager(), initialized, kernel_version, lookup_functions(), NULL, and TRUE.
Referenced by hid_enumerate(), hid_open_path(), and Slic3r::GUI::Mouse3DController::run().
hid_open()
HID_API_EXPORT hid_device *HID_API_CALL hid_open (unsigned short vendor_id, unsigned short product_id, const wchar_t * serial_number)
#include <src/hidapi/include/hidapi.h>
Open a HID device using a Vendor ID (VID), Product ID (PID) and optionally a serial number.
If serial_number is NULL, the first device with the specified VID and PID is opened.
Parameters
vendor_id The Vendor ID (VID) of the device to open.
product_id The Product ID (PID) of the device to open.
serial_number The Serial Number of the device to open (Optionally NULL).
Returns
This function returns a pointer to a hid_device object on success or NULL on failure.
{
  struct hid_device_info *devs, *cur_dev;
  const char *path_to_open = NULL;
  hid_device *handle = NULL;
  devs = hid_enumerate(vendor_id, product_id);
  cur_dev = devs;
  while (cur_dev) {
    if (cur_dev->vendor_id == vendor_id &&
        cur_dev->product_id == product_id) {
      if (serial_number) {
        if (wcscmp(serial_number, cur_dev->serial_number) == 0) {
          path_to_open = cur_dev->path;
          break;
        }
      }
      else {
        path_to_open = cur_dev->path;
        break;
      }
    }
    cur_dev = cur_dev->next;
  }
  if (path_to_open) {
    /* Open the device */
    handle = hid_open_path(path_to_open);
  }
  hid_free_enumeration(devs);
  return handle;
}
References hid_enumerate(), hid_free_enumeration(), hid_open_path(), hid_device_info::next, NULL, hid_device_info::path, hid_device_info::product_id, hid_device_info::serial_number, and hid_device_info::vendor_id.
Referenced by Slic3r::GUI::Mouse3DController::connect_device().
hid_open_path()
HID_API_EXPORT hid_device *HID_API_CALL hid_open_path (const char * path)
#include <src/hidapi/include/hidapi.h>
Open a HID device by its path name.
The path name be determined by calling hid_enumerate(), or a platform-specific path name can be used (eg: /dev/hidraw0 on Linux).
Parameters
path The path name of the device to open
Returns
This function returns a pointer to a hid_device object on success or NULL on failure.
{
  hid_device *dev = NULL;
  hid_init();
  dev = new_hid_device();
  /* OPEN HERE */
  dev->device_handle = open(path, O_RDWR);
  /* If we have a good handle, return it. */
  if (dev->device_handle > 0) {
    /* Get the report descriptor */
    int res, desc_size = 0;
    struct hidraw_report_descriptor rpt_desc;
    memset(&rpt_desc, 0x0, sizeof(rpt_desc));
    /* Get Report Descriptor Size */
    res = ioctl(dev->device_handle, HIDIOCGRDESCSIZE, &desc_size);
    if (res < 0)
      perror("HIDIOCGRDESCSIZE");
    /* Get Report Descriptor */
    rpt_desc.size = desc_size;
    res = ioctl(dev->device_handle, HIDIOCGRDESC, &rpt_desc);
    if (res < 0) {
      perror("HIDIOCGRDESC");
    } else {
      /* Determine if this device uses numbered reports. */
      dev->uses_numbered_reports =
        uses_numbered_reports(rpt_desc.value,
                              rpt_desc.size);
    }
    return dev;
  }
  else {
    /* Unable to open any devices. */
    free(dev);
    return NULL;
  }
}
References hid_device_::barrier, hid_device_::device_handle, FALSE, free_hid_device(), get_max_report_length(), hid_device_removal_callback(), hid_init(), hid_report_callback(), HidD_FreePreparsedData, HidD_GetPreparsedData, HidD_SetNumInputBuffers, HidP_GetCaps, HIDP_STATUS_SUCCESS, hid_device_::input_report_buf, hid_device_::input_report_length, _HIDP_CAPS::InputReportByteLength, hid_device_::max_input_report_len, memset, new_hid_device(), NULL, open, open_device(), hid_device_::output_report_length, _HIDP_CAPS::OutputReportByteLength, hid_device_info::path, pthread_barrier_wait(), hid_device_::read_buf, read_thread(), register_error(), hid_device_::run_loop_mode, hid_device_::thread, TRUE, hid_device_::uses_numbered_reports, and uses_numbered_reports().
Referenced by Slic3r::GUI::Mouse3DController::connect_device(), and hid_open().
hid_read()
int HID_API_EXPORT HID_API_CALL hid_read (hid_device * dev, unsigned char * data, size_t length)
#include <src/hidapi/include/hidapi.h>
Read an Input report from a HID device.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into.
length The number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
Returns
This function returns the actual number of bytes read and -1 on error. If no packet was available to be read and the handle is in non-blocking mode, this function returns 0.
{
  return hid_read_timeout(dev, data, length, (dev->blocking)? -1: 0);
}
References hid_device_::blocking, hid_read_timeout(), and length().
hid_read_timeout()
int HID_API_EXPORT HID_API_CALL hid_read_timeout (hid_device * dev, unsigned char * data, size_t length, int milliseconds)
#include <src/hidapi/include/hidapi.h>
Read an Input report from a HID device with timeout.
Input reports are returned to the host through the INTERRUPT IN endpoint. The first byte will contain the Report number if the device uses numbered reports.
Parameters
dev A device handle returned from hid_open().
data A buffer to put the read data into.
length The number of bytes to read. For devices with multiple reports, make sure to read an extra byte for the report number.
milliseconds timeout in milliseconds or -1 for blocking wait.
Returns
This function returns the actual number of bytes read and -1 on error. If no packet was available to be read within the timeout period, this function returns 0.
{
  int bytes_read;
  if (milliseconds >= 0) {
    /* Milliseconds is either 0 (non-blocking) or > 0 (contains
       a valid timeout). In both cases we want to call poll()
       and wait for data to arrive.  Don't rely on non-blocking
       operation (O_NONBLOCK) since some kernels don't seem to
       properly report device disconnection through read() when
       in non-blocking mode.  */
    int ret;
    struct pollfd fds;
    fds.fd = dev->device_handle;
    fds.events = POLLIN;
    fds.revents = 0;
    ret = poll(&fds, 1, milliseconds);
    if (ret == -1 || ret == 0) {
      /* Error or timeout */
      return ret;
    }
    else {
      /* Check for errors on the file descriptor. This will
         indicate a device disconnection. */
      if (fds.revents & (POLLERR | POLLHUP | POLLNVAL))
        return -1;
    }
  }
  bytes_read = read(dev->device_handle, data, length);
  if (bytes_read < 0 && (errno == EAGAIN || errno == EINPROGRESS))
    bytes_read = 0;
  if (bytes_read >= 0 &&
      kernel_version != 0 &&
      kernel_version < KERNEL_VERSION(2,6,34) &&
      dev->uses_numbered_reports) {
    /* Work around a kernel bug. Chop off the first byte. */
    memmove(data, data+1, bytes_read);
    bytes_read--;
  }
  return bytes_read;
}
References cond_timedwait(), cond_wait(), hid_device_::condition, input_report::data, hid_device_::device_handle, hid_device_::disconnected, FALSE, hid_device_::input_report_length, hid_device_::input_reports, kernel_version, length(), memcpy, memmove, memset, hid_device_::mutex, NULL, hid_device_::ol, hid_device_::read_buf, hid_device_::read_pending, register_error(), return_data(), hid_device_::shutdown_thread, TRUE, and hid_device_::uses_numbered_reports.
Referenced by Slic3r::GUI::Mouse3DController::collect_input(), and hid_read().
hid_send_feature_report()
int HID_API_EXPORT HID_API_CALL hid_send_feature_report (hid_device * dev, const unsigned char * data, size_t length)
#include <src/hidapi/include/hidapi.h>
Send a Feature report to the device.
Feature reports are sent over the Control endpoint as a Set_Report transfer. The first byte of data[] must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to hid_send_feature_report() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to hid_send_feature_report(): the Report ID (or 0x0, for devices which do not use numbered reports), followed by the report data (16 bytes). In this example, the length passed in would be 17.
Parameters
dev A device handle returned from hid_open().
data The data to send, including the report number as the first byte.
length The length in bytes of the data to send, including the report number.
Returns
This function returns the actual number of bytes written and -1 on error.
{
  int res;
  res = ioctl(dev->device_handle, HIDIOCSFEATURE(length), data);
  if (res < 0)
    perror("ioctl (SFEATURE)");
  return res;
}
References hid_device_::device_handle, HidD_SetFeature, HIDIOCSFEATURE, length(), register_error(), and set_report().
hid_set_nonblocking()
int HID_API_EXPORT HID_API_CALL hid_set_nonblocking (hid_device * dev, int nonblock)
#include <src/hidapi/include/hidapi.h>
Set the device handle to be non-blocking.
In non-blocking mode calls to hid_read() will return immediately with a value of 0 if there is no data to be read. In blocking mode, hid_read() will wait (block) until there is data to read before returning.
Nonblocking can be turned on and off at any time.
Parameters
dev A device handle returned from hid_open().
nonblock enable or not the nonblocking reads
1 to enable nonblocking
0 to disable nonblocking.
Returns
This function returns 0 on success and -1 on error.
{
  /* Do all non-blocking in userspace using poll(), since it looks
     like there's a bug in the kernel in some versions where
     read() will not return -1 on disconnection of the USB device */
  dev->blocking = !nonblock;
  return 0; /* Success */
}
References hid_device_::blocking.
hid_write()
int HID_API_EXPORT HID_API_CALL hid_write (hid_device * dev, const unsigned char * data, size_t length)
#include <src/hidapi/include/hidapi.h>
Write an Output report to a HID device.
The first byte of data[] must contain the Report ID. For devices which only support a single report, this must be set to 0x0. The remaining bytes contain the report data. Since the Report ID is mandatory, calls to hid_write() will always contain one more byte than the report contains. For example, if a hid report is 16 bytes long, 17 bytes must be passed to hid_write(), the Report ID (or 0x0, for devices with a single report), followed by the report data (16 bytes). In this example, the length passed in would be 17.
hid_write() will send the data on the first OUT endpoint, if one exists. If it does not, it will send the data through the Control Endpoint (Endpoint 0).
Parameters
dev A device handle returned from hid_open().
data The data to send, including the report number as the first byte.
length The length in bytes of the data to send.
Returns
This function returns the actual number of bytes written and -1 on error.
{
  int bytes_written;
  bytes_written = write(dev->device_handle, data, length);
  return bytes_written;
}
References input_report::data, hid_device_::device_handle, length(), memcpy, memset, NULL, hid_device_::output_report_length, register_error(), set_report(), and TRUE.