OrcaSlicer: Slic3r::TreeSupportProfiler Class Reference
Slic3r::TreeSupportProfiler Class Reference
Public Member Functions
TreeSupportProfiler ()
void stage_start (TreeSupportStage stage)
void stage_finish (TreeSupportStage stage)
void tic ()
void toc ()
void stage_add (TreeSupportStage stage, bool do_toc=false)
std::string report ()
Public Attributes
uint32_t stage_durations [NUM_STAGES]
uint32_t stage_index = 0
boost::posix_time::ptime tic_time
boost::posix_time::ptime toc_time
Private Attributes
boost::posix_time::ptime m_stage_start_times [NUM_STAGES]
Detailed Description
Constructor & Destructor Documentation
TreeSupportProfiler()
Slic3r::TreeSupportProfiler::TreeSupportProfiler () inline
    {
        for (uint32_t& item : stage_durations) {
            item = 0;
        }
    }
References stage_durations.
Member Function Documentation
report()
std::string Slic3r::TreeSupportProfiler::report () inline
    {
        std::stringstream ss;
        ss << "total overhange cost: " << stage_durations[STAGE_total]
            << "; STAGE_DETECT_OVERHANGS: " << stage_durations[STAGE_DETECT_OVERHANGS]
            << "; STAGE_GENERATE_CONTACT_NODES: " << stage_durations[STAGE_GENERATE_CONTACT_NODES]
            << "; STAGE_DROP_DOWN_NODES: " << stage_durations[STAGE_DROP_DOWN_NODES]
            << "; STAGE_DRAW_CIRCLES: " << stage_durations[STAGE_DRAW_CIRCLES]
            << "; STAGE_GENERATE_TOOLPATHS: " << stage_durations[STAGE_GENERATE_TOOLPATHS]
            << "; STAGE_MinimumSpanningTree: " << stage_durations[STAGE_MinimumSpanningTree]
            << "; STAGE_GET_AVOIDANCE: " << stage_durations[STAGE_GET_AVOIDANCE]
            << "; STAGE_projection_onto_ex: " << stage_durations[STAGE_projection_onto_ex]
            << "; STAGE_get_collision: " << stage_durations[STAGE_get_collision]
            << "; STAGE_intersection_ln: " << stage_durations[STAGE_intersection_ln];
        return ss.str();
    }
References Slic3r::STAGE_DETECT_OVERHANGS, Slic3r::STAGE_DRAW_CIRCLES, Slic3r::STAGE_DROP_DOWN_NODES, stage_durations, Slic3r::STAGE_GENERATE_CONTACT_NODES, Slic3r::STAGE_GENERATE_TOOLPATHS, Slic3r::STAGE_GET_AVOIDANCE, Slic3r::STAGE_get_collision, Slic3r::STAGE_intersection_ln, Slic3r::STAGE_MinimumSpanningTree, Slic3r::STAGE_projection_onto_ex, and Slic3r::STAGE_total.
Referenced by Slic3r::TreeSupport::generate().
stage_add()
void Slic3r::TreeSupportProfiler::stage_add (TreeSupportStage stage, bool do_toc = false) inline
    {
        if (stage > NUM_STAGES)
            return;
        if(do_toc)
            toc_time = boost::posix_time::microsec_clock::local_time();
        stage_durations[stage] += (toc_time - tic_time).total_milliseconds();
    }
References Slic3r::NUM_STAGES, stage_durations, tic_time, and toc_time.
Referenced by Slic3r::TreeSupport::drop_nodes(), Slic3r::TreeSupportData::get_avoidance(), and Slic3r::TreeSupportData::get_collision().
stage_finish()
void Slic3r::TreeSupportProfiler::stage_finish (TreeSupportStage stage) inline
    {
        if (stage > NUM_STAGES)
            return;
        boost::posix_time::ptime time = boost::posix_time::microsec_clock::local_time();
        stage_durations[stage] = (time - m_stage_start_times[stage]).total_milliseconds();
    }
References m_stage_start_times, Slic3r::NUM_STAGES, and stage_durations.
Referenced by Slic3r::TreeSupport::generate().
stage_start()
void Slic3r::TreeSupportProfiler::stage_start (TreeSupportStage stage) inline
    {
        if (stage > NUM_STAGES)
            return;
        m_stage_start_times[stage] = boost::posix_time::microsec_clock::local_time();
    }
References m_stage_start_times, and Slic3r::NUM_STAGES.
Referenced by Slic3r::TreeSupport::generate().
tic()
void Slic3r::TreeSupportProfiler::tic () inline
{ tic_time = boost::posix_time::microsec_clock::local_time(); }
References tic_time.
Referenced by Slic3r::TreeSupport::drop_nodes(), Slic3r::TreeSupportData::get_avoidance(), and Slic3r::TreeSupportData::get_collision().
toc()
void Slic3r::TreeSupportProfiler::toc () inline
{ toc_time = boost::posix_time::microsec_clock::local_time(); }
References toc_time.
Member Data Documentation
m_stage_start_times
boost::posix_time::ptime Slic3r::TreeSupportProfiler::m_stage_start_times[NUM_STAGES] private
Referenced by stage_finish(), and stage_start().
stage_durations
uint32_t Slic3r::TreeSupportProfiler::stage_durations[NUM_STAGES]
Referenced by TreeSupportProfiler(), report(), stage_add(), and stage_finish().
stage_index
uint32_t Slic3r::TreeSupportProfiler::stage_index = 0
tic_time
boost::posix_time::ptime Slic3r::TreeSupportProfiler::tic_time
Referenced by stage_add(), and tic().
toc_time
boost::posix_time::ptime Slic3r::TreeSupportProfiler::toc_time
Referenced by stage_add(), and toc().
The documentation for this class was generated from the following file:
src/libslic3r/TreeSupport.cpp