OrcaSlicer: Slic3r::GUI::RichMessageDialog Class Reference
Slic3r::GUI::RichMessageDialog Class Reference
#include <src/slic3r/GUI/MsgDialog.hpp>
Public Types
using wxMD = wxMessageDialogBase
Public Member Functions
RichMessageDialog (wxWindow *parent, const wxString &message, const wxString &caption=wxEmptyString, long style=wxOK)
RichMessageDialog (RichMessageDialog &&)=delete
RichMessageDialog (const RichMessageDialog &)=delete
RichMessageDialog & operator= (RichMessageDialog &&)=delete
RichMessageDialog & operator= (const RichMessageDialog &)=delete
virtual ~RichMessageDialog ()=default
int ShowModal () override
void ShowCheckBox (const wxString &checkBoxText, bool checked=false)
wxString GetCheckBoxText () const
bool IsCheckBoxChecked () const
virtual bool SetYesNoLabels (const wxMD::ButtonLabel &yes, const wxMD::ButtonLabel &no)
virtual bool SetYesNoCancelLabels (const wxMD::ButtonLabel &yes, const wxMD::ButtonLabel &no, const wxMD::ButtonLabel &cancel)
virtual bool SetOKLabel (const wxMD::ButtonLabel &ok)
virtual bool SetOKCancelLabels (const wxMD::ButtonLabel &ok, const wxMD::ButtonLabel &cancel)
virtual bool SetHelpLabel (const wxMD::ButtonLabel &help)
bool HasCustomLabels () const
wxString GetYesLabel () const
wxString GetNoLabel () const
wxString GetOKLabel () const
wxString GetCancelLabel () const
wxString GetHelpLabel () const
void show_dsa_button (wxString const &title={})
bool get_checkbox_state ()
virtual void on_dpi_changed (const wxRect &suggested_rect)
void SetButtonLabel (wxWindowID btn_id, const wxString &label, bool set_focus=false)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
Protected Types
enum {
BORDER = 20 , LOGO_SPACING = 35 , LOGO_GAP = 20 , CONTENT_WIDTH = 242 ,
CONTENT_MAX_HEIGHT = 60 , BTN_SPACING = 20 , VERT_SPACING = 15
}
Protected Member Functions
void DoSetCustomLabel (wxString &var, const wxMD::ButtonLabel &label)
const wxString & GetCustomYesLabel () const
const wxString & GetCustomNoLabel () const
const wxString & GetCustomOKLabel () const
const wxString & GetCustomHelpLabel () const
const wxString & GetCustomCancelLabel () const
Button * add_button (wxWindowID btn_id, bool set_focus=false, const wxString &label=wxString())
Button * get_button (wxWindowID btn_id)
void apply_style (long style)
void finalize ()
virtual void on_sys_color_changed ()
Protected Attributes
wxFont boldfont
wxBoxSizer * content_sizer
wxBoxSizer * btn_sizer
wxBoxSizer * m_dsa_sizer
wxStaticBitmap * logo
MsgButtonsHash m_buttons
CheckBox * m_checkbox_dsa {nullptr}
Private Member Functions
virtual wxString GetDefaultYesLabel () const
virtual wxString GetDefaultNoLabel () const
virtual wxString GetDefaultOKLabel () const
virtual wxString GetDefaultCancelLabel () const
virtual wxString GetDefaultHelpLabel () const
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
wxCheckBox * m_checkBox { nullptr }
wxString m_checkBoxText
bool m_checkBoxValue { false }
wxString m_yes
wxString m_no
wxString m_ok
wxString m_cancel
wxString m_help
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Member Typedef Documentation
wxMD
using Slic3r::GUI::RichMessageDialog::wxMD = wxMessageDialogBase
Member Enumeration Documentation
anonymous enum
anonymous enum protected inherited
Enumerator
BORDER
LOGO_SPACING
LOGO_GAP
CONTENT_WIDTH
CONTENT_MAX_HEIGHT
BTN_SPACING
VERT_SPACING
       {
    BORDER = 20,
    LOGO_SPACING = 35,
    LOGO_GAP = 20,
    CONTENT_WIDTH = 242,
    CONTENT_MAX_HEIGHT = 60,//TO
    BTN_SPACING = 20,
    VERT_SPACING = 15,//TO
  };
Constructor & Destructor Documentation
RichMessageDialog() [1/3]
Slic3r::GUI::RichMessageDialog::RichMessageDialog (wxWindow * parent, const wxString & message, const wxString & caption = wxEmptyString, long style = wxOK)
    : MsgDialog(parent, caption.IsEmpty() ? wxString::Format(_L("%s info"), SLIC3R_APP_FULL_NAME) : caption, wxEmptyString, style)
{
    add_msg_content(this, content_sizer, message);
    m_checkBox = new wxCheckBox(this, wxID_ANY, m_checkBoxText);
    wxGetApp().UpdateDarkUI(m_checkBox);
    m_checkBox->Bind(wxEVT_CHECKBOX, [this](wxCommandEvent&) { m_checkBoxValue = m_checkBox->GetValue(); });
    btn_sizer->Insert(0, m_checkBox, wxALIGN_CENTER_VERTICAL);
    finalize();
}
References Slic3r::GUI::add_msg_content(), Slic3r::GUI::MsgDialog::btn_sizer, Slic3r::GUI::MsgDialog::content_sizer, Slic3r::GUI::MsgDialog::finalize(), m_checkBox, m_checkBoxText, and m_checkBoxValue.
RichMessageDialog() [2/3]
Slic3r::GUI::RichMessageDialog::RichMessageDialog (RichMessageDialog &&) delete
RichMessageDialog() [3/3]
Slic3r::GUI::RichMessageDialog::RichMessageDialog (const RichMessageDialog &) delete
~RichMessageDialog()
virtual Slic3r::GUI::RichMessageDialog::~RichMessageDialog () virtual default
Member Function Documentation
add_button()
Button * Slic3r::GUI::MsgDialog::add_button (wxWindowID btn_id, bool set_focus = false, const wxString & label = wxString()) protected inherited
{
    Button* btn = new Button(this, label, "", 0, 0, btn_id);
    ButtonSizeType type;
    if (label.length() < 5) {
        type = ButtonSizeNormal;
        btn->SetMinSize(MSG_DIALOG_BUTTON_SIZE); }
    else if (label.length() >= 5 && label.length() < 8) {
        type = ButtonSizeMiddle;
        btn->SetMinSize(MSG_DIALOG_MIDDLE_BUTTON_SIZE);
    }
    else if (label.length() >= 8 && label.length() < 12) {
        type = ButtonSizeMiddle;
        btn->SetMinSize(MSG_DIALOG_LONG_BUTTON_SIZE);
    } else {
        type = ButtonSizeLong;
        btn->SetMinSize(MSG_DIALOG_LONGER_BUTTON_SIZE);
    }
    btn->SetCornerRadius(FromDIP(12));
    StateColor btn_bg_green(
        std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed),
        std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal)
    );
    StateColor btn_bd_green(
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal)
    );
    StateColor btn_text_green(
        std::pair<wxColour, int>(wxColour(255, 255, 254), StateColor::Normal)
    );
    StateColor btn_bg_white(
        std::pair<wxColour, int>(wxColour(206, 206, 206), StateColor::Pressed),
        std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(255, 255, 255), StateColor::Normal)
    );
    StateColor btn_bd_white(
        std::pair<wxColour, int>(wxColour(38, 46, 48), StateColor::Normal)
    );
    StateColor btn_text_white(
        std::pair<wxColour, int>(wxColour(38, 46, 48), StateColor::Normal)
    );
    if (btn_id == wxID_OK || btn_id == wxID_YES) {
        btn->SetBackgroundColor(btn_bg_green);
        btn->SetBorderColor(btn_bd_green);
        btn->SetTextColor(btn_text_green);
    }
    if (btn_id == wxID_CANCEL || btn_id == wxID_NO) {
        btn->SetBackgroundColor(btn_bg_white);
        btn->SetBorderColor(btn_bd_white);
        btn->SetTextColor(btn_text_white);
    }
    if (set_focus)
        btn->SetFocus();
    btn_sizer->Add(btn, 0, wxRIGHT | wxALIGN_CENTER_VERTICAL, BTN_SPACING);
    btn->Bind(wxEVT_BUTTON, [this, btn_id](wxCommandEvent&) { EndModal(btn_id); });
    MsgButton *mb = new MsgButton;
    ButtonData *bd = new ButtonData;
    bd->button = btn;
    bd->type   = type;
    mb->id        = wxString::Format("%d", m_buttons.size());
    mb->buttondata = bd;
    m_buttons[ wxString::Format("%d", m_buttons.size())] = mb;
    return btn;
};
References bd, Slic3r::GUI::MsgDialog::btn_sizer, Slic3r::GUI::MsgDialog::BTN_SPACING, Slic3r::GUI::MsgButton::buttondata, ButtonSizeLong, ButtonSizeMiddle, ButtonSizeNormal, StateColor::Hovered, Slic3r::GUI::MsgButton::id, Slic3r::GUI::MsgDialog::m_buttons, MSG_DIALOG_BUTTON_SIZE, MSG_DIALOG_LONG_BUTTON_SIZE, MSG_DIALOG_LONGER_BUTTON_SIZE, MSG_DIALOG_MIDDLE_BUTTON_SIZE, StateColor::Normal, StateColor::Pressed, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetMinSize(), Button::SetTextColor(), and wxEVT_BUTTON.
Referenced by Slic3r::GUI::DownloadDialog::DownloadDialog(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), and Slic3r::GUI::MsgDialog::apply_style().
apply_style()
void Slic3r::GUI::MsgDialog::apply_style (long style) protected inherited
{
    if (style & wxOK)       add_button(wxID_OK, true, _L("OK"));
    if (style & wxYES)      add_button(wxID_YES, true, _L("Yes"));
    if (style & wxNO)       add_button(wxID_NO, false,_L("No"));
    if (style & wxCANCEL)   add_button(wxID_CANCEL, false, _L("Cancel"));
    logo->SetBitmap( create_scaled_bitmap(style & wxAPPLY        ? "completed" :
                                          style & wxICON_WARNING        ? "obj_warning" :
                                          style & wxICON_INFORMATION    ? "info"        :
                                          style & wxICON_QUESTION       ? "question"    : "OrcaSlicer", this, 64, style & wxICON_ERROR));
}
References _L, Slic3r::GUI::MsgDialog::add_button(), create_scaled_bitmap(), Slic3r::GUI::MsgDialog::logo, and style.
Referenced by Slic3r::GUI::MsgDialog::MsgDialog().
DoSetCustomLabel()
void Slic3r::GUI::RichMessageDialog::DoSetCustomLabel (wxString & var, const wxMD::ButtonLabel & label) inline protected
  {
    var = label.GetAsString();
  }
References Slic3r::var().
Referenced by SetHelpLabel(), SetOKCancelLabels(), SetOKLabel(), SetYesNoCancelLabels(), and SetYesNoLabels().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
finalize()
void Slic3r::GUI::MsgDialog::finalize () protected inherited
{
    wxGetApp().UpdateDlgDarkUI(this);
    Fit();
    CenterOnParent();
}
Referenced by Slic3r::GUI::DownloadDialog::DownloadDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MessageDialog::MessageDialog(), Slic3r::GUI::MsgDataIncompatible::MsgDataIncompatible(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::MsgUpdateSlic3r::MsgUpdateSlic3r(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), RichMessageDialog(), and Slic3r::GUI::WarningDialog::WarningDialog().
get_button()
Button * Slic3r::GUI::MsgDialog::get_button (wxWindowID btn_id) protected inherited
{
    return static_cast<Button*>(FindWindowById(btn_id, this));
}
Referenced by Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), and Slic3r::GUI::MsgDialog::SetButtonLabel().
get_checkbox_state()
bool Slic3r::GUI::MsgDialog::get_checkbox_state () inherited
{
    if (m_checkbox_dsa) {
        return m_checkbox_dsa->GetValue();
    }
    return false;
}
References Slic3r::GUI::MsgDialog::m_checkbox_dsa.
Referenced by Slic3r::GUI::Plater::close_with_confirm(), and Slic3r::GUI::MediaPlayCtrl::ToggleStream().
GetCancelLabel()
wxString Slic3r::GUI::RichMessageDialog::GetCancelLabel () const inline
  {
    return m_cancel.empty() ? GetDefaultCancelLabel() : m_cancel;
  }
References GetDefaultCancelLabel(), and m_cancel.
GetCheckBoxText()
wxString Slic3r::GUI::RichMessageDialog::GetCheckBoxText () const inline
{ return m_checkBoxText; }
References m_checkBoxText.
GetCustomCancelLabel()
const wxString & Slic3r::GUI::RichMessageDialog::GetCustomCancelLabel () const inline protected
{ return m_cancel; }
References m_cancel.
GetCustomHelpLabel()
const wxString & Slic3r::GUI::RichMessageDialog::GetCustomHelpLabel () const inline protected
{ return m_help; }
References m_help.
GetCustomNoLabel()
const wxString & Slic3r::GUI::RichMessageDialog::GetCustomNoLabel () const inline protected
{ return m_no; }
References m_no.
GetCustomOKLabel()
const wxString & Slic3r::GUI::RichMessageDialog::GetCustomOKLabel () const inline protected
{ return m_ok; }
References m_ok.
GetCustomYesLabel()
const wxString & Slic3r::GUI::RichMessageDialog::GetCustomYesLabel () const inline protected
{ return m_yes; }
References m_yes.
GetDefaultCancelLabel()
virtual wxString Slic3r::GUI::RichMessageDialog::GetDefaultCancelLabel () const inline private virtual
{ return wxGetTranslation("Cancel"); }
Referenced by GetCancelLabel().
GetDefaultHelpLabel()
virtual wxString Slic3r::GUI::RichMessageDialog::GetDefaultHelpLabel () const inline private virtual
{ return wxGetTranslation("Help"); }
Referenced by GetHelpLabel().
GetDefaultNoLabel()
virtual wxString Slic3r::GUI::RichMessageDialog::GetDefaultNoLabel () const inline private virtual
{ return wxGetTranslation("No"); }
Referenced by GetNoLabel().
GetDefaultOKLabel()
virtual wxString Slic3r::GUI::RichMessageDialog::GetDefaultOKLabel () const inline private virtual
{ return wxGetTranslation("OK"); }
Referenced by GetOKLabel().
GetDefaultYesLabel()
virtual wxString Slic3r::GUI::RichMessageDialog::GetDefaultYesLabel () const inline private virtual
{ return wxGetTranslation("Yes"); }
Referenced by GetYesLabel().
GetHelpLabel()
wxString Slic3r::GUI::RichMessageDialog::GetHelpLabel () const inline
  {
    return m_help.empty() ? GetDefaultHelpLabel() : m_help;
  }
References GetDefaultHelpLabel(), and m_help.
GetNoLabel()
wxString Slic3r::GUI::RichMessageDialog::GetNoLabel () const inline
  {
    return m_no.empty() ? GetDefaultNoLabel() : m_no;
  }
References GetDefaultNoLabel(), and m_no.
GetOKLabel()
wxString Slic3r::GUI::RichMessageDialog::GetOKLabel () const inline
  {
    return m_ok.empty() ? GetDefaultOKLabel() : m_ok;
  }
References GetDefaultOKLabel(), and m_ok.
GetYesLabel()
wxString Slic3r::GUI::RichMessageDialog::GetYesLabel () const inline
  {
    return m_yes.empty() ? GetDefaultYesLabel() : m_yes;
  }
References GetDefaultYesLabel(), and m_yes.
HasCustomLabels()
bool Slic3r::GUI::RichMessageDialog::HasCustomLabels () const inline
  {
    return !(m_ok.empty() && m_cancel.empty() && m_help.empty() &&
      m_yes.empty() && m_no.empty());
  }
References m_cancel, m_help, m_no, m_ok, and m_yes.
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
IsCheckBoxChecked()
bool Slic3r::GUI::RichMessageDialog::IsCheckBoxChecked () const inline
{ return m_checkBoxValue; }
References m_checkBoxValue.
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_dpi_changed()
void Slic3r::GUI::MsgDialog::on_dpi_changed (const wxRect & suggested_rect) virtual inherited
Implements Slic3r::GUI::DPIAware< P >.
 {
     if (m_buttons.size() > 0) {
         MsgButtonsHash::iterator i = m_buttons.begin();
         while (i != m_buttons.end()) {
             MsgButton *bd   = i->second;
             wxSize     bsize;
             switch (bd->buttondata->type) {
                case ButtonSizeNormal:bsize = MSG_DIALOG_BUTTON_SIZE;break;
                case ButtonSizeMiddle: bsize = MSG_DIALOG_MIDDLE_BUTTON_SIZE; break;
                case ButtonSizeLong: bsize = MSG_DIALOG_LONG_BUTTON_SIZE; break;
                default: break;
             }
             bd->buttondata->button->SetMinSize(bsize);
             i++;
         }
     }
 }
References bd, ButtonSizeLong, ButtonSizeMiddle, ButtonSizeNormal, Slic3r::GUI::MsgDialog::m_buttons, MSG_DIALOG_BUTTON_SIZE, MSG_DIALOG_LONG_BUTTON_SIZE, and MSG_DIALOG_MIDDLE_BUTTON_SIZE.
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
operator=() [1/2]
RichMessageDialog & Slic3r::GUI::RichMessageDialog::operator= (const RichMessageDialog &) delete
operator=() [2/2]
RichMessageDialog & Slic3r::GUI::RichMessageDialog::operator= (RichMessageDialog &&) delete
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
SetButtonLabel()
void Slic3r::GUI::MsgDialog::SetButtonLabel (wxWindowID btn_id, const wxString & label, bool set_focus = false) inherited
{
    if (Button* btn = get_button(btn_id)) {
        btn->SetLabel(label);
        if (set_focus)
            btn->SetFocus();
    }
}
References Slic3r::GUI::MsgDialog::get_button().
Referenced by Slic3r::GUI::ObjectList::del_from_cut_object(), and Slic3r::GUI::Plater::priv::delete_object_from_model().
SetHelpLabel()
virtual bool Slic3r::GUI::RichMessageDialog::SetHelpLabel (const wxMD::ButtonLabel & help) inline virtual
  {
    DoSetCustomLabel(m_help, help);
    return true;
  }
References DoSetCustomLabel(), and m_help.
SetOKCancelLabels()
virtual bool Slic3r::GUI::RichMessageDialog::SetOKCancelLabels (const wxMD::ButtonLabel & ok, const wxMD::ButtonLabel & cancel) inline virtual
  {
    DoSetCustomLabel(m_ok, ok);
    DoSetCustomLabel(m_cancel, cancel);
    return true;
  }
References DoSetCustomLabel(), m_cancel, and m_ok.
SetOKLabel()
virtual bool Slic3r::GUI::RichMessageDialog::SetOKLabel (const wxMD::ButtonLabel & ok) inline virtual
  {
    DoSetCustomLabel(m_ok, ok);
    return true;
}
References DoSetCustomLabel(), and m_ok.
SetYesNoCancelLabels()
virtual bool Slic3r::GUI::RichMessageDialog::SetYesNoCancelLabels (const wxMD::ButtonLabel & yes, const wxMD::ButtonLabel & no, const wxMD::ButtonLabel & cancel) inline virtual
  {
    DoSetCustomLabel(m_yes, yes);
    DoSetCustomLabel(m_no, no);
    DoSetCustomLabel(m_cancel, cancel);
    return true;
  }
References DoSetCustomLabel(), m_cancel, m_no, and m_yes.
SetYesNoLabels()
virtual bool Slic3r::GUI::RichMessageDialog::SetYesNoLabels (const wxMD::ButtonLabel & yes, const wxMD::ButtonLabel & no) inline virtual
  {
    DoSetCustomLabel(m_yes, yes);
    DoSetCustomLabel(m_no, no);
    return true;
  }
References DoSetCustomLabel(), m_no, and m_yes.
Referenced by Slic3r::GUI::Config::take_config_snapshot_cancel_on_error().
show_dsa_button()
void Slic3r::GUI::MsgDialog::show_dsa_button (wxString const & title = {}) inherited
{
    m_checkbox_dsa = new CheckBox(this);
    m_dsa_sizer->Add(m_checkbox_dsa, 0, wxALL | wxALIGN_CENTER, FromDIP(2));
    m_checkbox_dsa->Bind(wxEVT_TOGGLEBUTTON, [this](wxCommandEvent& e) {
        auto event = wxCommandEvent(EVT_CHECKBOX_CHANGE);
        event.SetInt(m_checkbox_dsa->GetValue()?1:0);
        event.SetEventObject(this);
        wxPostEvent(this, event);
        e.Skip();
    });
    auto  m_text_dsa = new wxStaticText(this, wxID_ANY, title.IsEmpty() ? _L("Don't show again") : title, wxDefaultPosition, wxDefaultSize, 0);
    m_dsa_sizer->Add(m_text_dsa, 0, wxALL | wxALIGN_CENTER, FromDIP(2));
    m_text_dsa->SetFont(::Label::Body_13);
    m_text_dsa->SetForegroundColour(StateColor::darkModeColorFor(wxColour("#323A3D")));
    btn_sizer->Layout();
    //Fit();
}
References _L, Label::Body_13, Slic3r::GUI::MsgDialog::btn_sizer, StateColor::darkModeColorFor(), Slic3r::GUI::MsgDialog::m_checkbox_dsa, Slic3r::GUI::MsgDialog::m_dsa_sizer, and wxStaticText.
Referenced by Slic3r::GUI::Plater::close_with_confirm(), and Slic3r::GUI::MediaPlayCtrl::ToggleStream().
ShowCheckBox()
void Slic3r::GUI::RichMessageDialog::ShowCheckBox (const wxString & checkBoxText, bool checked = false) inline
  {
    m_checkBoxText = checkBoxText;
    m_checkBoxValue = checked;
  }
References m_checkBoxText, and m_checkBoxValue.
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
ShowModal()
int Slic3r::GUI::RichMessageDialog::ShowModal () override
{
    if (m_checkBoxText.IsEmpty())
        m_checkBox->Hide();
    else
        m_checkBox->SetLabelText(m_checkBoxText);
    Layout();
    return wxDialog::ShowModal();
}
References m_checkBox, and m_checkBoxText.
Referenced by Slic3r::GUI::GUI_App::on_init_inner(), and Slic3r::GUI::Config::take_config_snapshot_cancel_on_error().
Member Data Documentation
boldfont
wxFont Slic3r::GUI::MsgDialog::boldfont protected inherited
Referenced by Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgUpdateForced::MsgUpdateForced().
btn_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::btn_sizer protected inherited
Referenced by Slic3r::GUI::MsgDialog::MsgDialog(), RichMessageDialog(), Slic3r::GUI::MsgDialog::add_button(), and Slic3r::GUI::MsgDialog::show_dsa_button().
content_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::content_sizer protected inherited
Referenced by Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::InfoDialog::InfoDialog(), Slic3r::GUI::MessageDialog::MessageDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), RichMessageDialog(), Slic3r::GUI::WarningDialog::WarningDialog(), and Slic3r::GUI::DownloadDialog::SetExtendedMessage().
logo
wxStaticBitmap* Slic3r::GUI::MsgDialog::logo protected inherited
Referenced by Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::apply_style().
m_buttons
MsgButtonsHash Slic3r::GUI::MsgDialog::m_buttons protected inherited
Referenced by Slic3r::GUI::MsgDialog::~MsgDialog(), Slic3r::GUI::MsgDialog::add_button(), and Slic3r::GUI::MsgDialog::on_dpi_changed().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_cancel
wxString Slic3r::GUI::RichMessageDialog::m_cancel private
Referenced by GetCancelLabel(), GetCustomCancelLabel(), HasCustomLabels(), SetOKCancelLabels(), and SetYesNoCancelLabels().
m_checkBox
wxCheckBox* Slic3r::GUI::RichMessageDialog::m_checkBox { nullptr } private
Referenced by RichMessageDialog(), and ShowModal().
m_checkbox_dsa
CheckBox* Slic3r::GUI::MsgDialog::m_checkbox_dsa {nullptr} protected inherited
Referenced by Slic3r::GUI::MsgDialog::get_checkbox_state(), and Slic3r::GUI::MsgDialog::show_dsa_button().
m_checkBoxText
wxString Slic3r::GUI::RichMessageDialog::m_checkBoxText private
Referenced by RichMessageDialog(), GetCheckBoxText(), ShowCheckBox(), and ShowModal().
m_checkBoxValue
bool Slic3r::GUI::RichMessageDialog::m_checkBoxValue { false } private
Referenced by RichMessageDialog(), IsCheckBoxChecked(), and ShowCheckBox().
m_dsa_sizer
wxBoxSizer* Slic3r::GUI::MsgDialog::m_dsa_sizer protected inherited
Referenced by Slic3r::GUI::MsgDialog::MsgDialog(), and Slic3r::GUI::MsgDialog::show_dsa_button().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_help
wxString Slic3r::GUI::RichMessageDialog::m_help private
Referenced by GetCustomHelpLabel(), GetHelpLabel(), HasCustomLabels(), and SetHelpLabel().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_no
wxString Slic3r::GUI::RichMessageDialog::m_no private
Referenced by GetCustomNoLabel(), GetNoLabel(), HasCustomLabels(), SetYesNoCancelLabels(), and SetYesNoLabels().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_ok
wxString Slic3r::GUI::RichMessageDialog::m_ok private
Referenced by GetCustomOKLabel(), GetOKLabel(), HasCustomLabels(), SetOKCancelLabels(), and SetOKLabel().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_yes
wxString Slic3r::GUI::RichMessageDialog::m_yes private
Referenced by GetCustomYesLabel(), GetYesLabel(), HasCustomLabels(), SetYesNoCancelLabels(), and SetYesNoLabels().
The documentation for this class was generated from the following files:
src/slic3r/GUI/MsgDialog.hpp
src/slic3r/GUI/MsgDialog.cpp