OrcaSlicer: Clipper2Lib::ClipperD Class Reference
Clipper2Lib::ClipperD Class Reference
#include <src/clipper2/Clipper2Lib/include/clipper2/clipper.engine.h>
Public Member Functions
ClipperD (int precision=2)
void AddSubject (const PathsD &subjects)
void AddOpenSubject (const PathsD &open_subjects)
void AddClip (const PathsD &clips)
bool Execute (ClipType clip_type, FillRule fill_rule, PathsD &closed_paths)
bool Execute (ClipType clip_type, FillRule fill_rule, PathsD &closed_paths, PathsD &open_paths)
bool Execute (ClipType clip_type, FillRule fill_rule, PolyTreeD &polytree)
bool Execute (ClipType clip_type, FillRule fill_rule, PolyTreeD &polytree, PathsD &open_paths)
void Clear ()
Public Attributes
bool PreserveCollinear = true
bool ReverseSolution = false
Protected Member Functions
bool ExecuteInternal (ClipType ct, FillRule ft, bool use_polytrees)
bool DeepCheckOwner (OutRec *outrec, OutRec *owner)
void CleanUp ()
void AddPath (const Path64 &path, PathType polytype, bool is_open)
void AddPaths (const Paths64 &paths, PathType polytype, bool is_open)
Protected Attributes
bool has_open_paths_ = false
bool succeeded_ = true
std::vector< OutRec * > outrec_list_
Private Member Functions
void BuildPathsD (PathsD &solutionClosed, PathsD *solutionOpen)
void BuildTreeD (PolyPathD &polytree, PathsD &open_paths)
void Reset ()
void InsertScanline (int64_t y)
bool PopScanline (int64_t &y)
bool PopLocalMinima (int64_t y, LocalMinima *&local_minima)
void DisposeAllOutRecs ()
void DisposeVerticesAndLocalMinima ()
void DeleteEdges (Active *&e)
void AddLocMin (Vertex &vert, PathType polytype, bool is_open)
bool IsContributingClosed (const Active &e) const
bool IsContributingOpen (const Active &e) const
void SetWindCountForClosedPathEdge (Active &edge)
void SetWindCountForOpenPathEdge (Active &e)
void InsertLocalMinimaIntoAEL (int64_t bot_y)
void InsertLeftEdge (Active &e)
void PushHorz (Active &e)
bool PopHorz (Active *&e)
OutPt * StartOpenPath (Active &e, const Point64 &pt)
void UpdateEdgeIntoAEL (Active *e)
OutPt * IntersectEdges (Active &e1, Active &e2, const Point64 &pt)
void DeleteFromAEL (Active &e)
void AdjustCurrXAndCopyToSEL (const int64_t top_y)
void DoIntersections (const int64_t top_y)
void AddNewIntersectNode (Active &e1, Active &e2, const int64_t top_y)
bool BuildIntersectList (const int64_t top_y)
void ProcessIntersectList ()
void SwapPositionsInAEL (Active &edge1, Active &edge2)
OutPt * AddOutPt (const Active &e, const Point64 &pt)
OutPt * AddLocalMinPoly (Active &e1, Active &e2, const Point64 &pt, bool is_new=false)
OutPt * AddLocalMaxPoly (Active &e1, Active &e2, const Point64 &pt)
void DoHorizontal (Active &horz)
bool ResetHorzDirection (const Active &horz, const Active *max_pair, int64_t &horz_left, int64_t &horz_right)
void DoTopOfScanbeam (const int64_t top_y)
Active * DoMaxima (Active &e)
void JoinOutrecPaths (Active &e1, Active &e2)
void CompleteSplit (OutPt *op1, OutPt *op2, OutRec &outrec)
bool ValidateClosedPathEx (OutPt *&outrec)
void CleanCollinear (OutRec *outrec)
void FixSelfIntersects (OutRec *outrec)
void DoSplitOp (OutRec *outRec, OutPt *splitOp)
Joiner * GetHorzTrialParent (const OutPt *op)
bool OutPtInTrialHorzList (OutPt *op)
void SafeDisposeOutPts (OutPt *&op)
void SafeDeleteOutPtJoiners (OutPt *op)
void AddTrialHorzJoin (OutPt *op)
void DeleteTrialHorzJoin (OutPt *op)
void ConvertHorzTrialsToJoins ()
void AddJoin (OutPt *op1, OutPt *op2)
void DeleteJoin (Joiner *joiner)
void ProcessJoinerList ()
OutRec * ProcessJoin (Joiner *joiner)
Private Attributes
double scale_ = 1.0
double invScale_ = 1.0
ClipType cliptype_ = ClipType::None
FillRule fillrule_ = FillRule::EvenOdd
FillRule fillpos = FillRule::Positive
int64_t bot_y_ = 0
bool minima_list_sorted_ = false
bool using_polytree_ = false
Active * actives_ = nullptr
Active * sel_ = nullptr
Joiner * horz_joiners_ = nullptr
std::vector< LocalMinima * > minima_list_
std::vector< LocalMinima * >::iterator current_locmin_iter_
std::vector< Vertex * > vertex_lists_
std::priority_queue< int64_t > scanline_list_
std::vector< IntersectNode > intersect_nodes_
std::vector< Joiner * > joiner_list_
Detailed Description
Constructor & Destructor Documentation
ClipperD()
Clipper2Lib::ClipperD::ClipperD (int precision = 2) inline explicit
                                         : ClipperBase()
    {
      CheckPrecision(precision);
      // to optimize scaling / descaling precision
      // set the scale to a power of double's radix (2) (#25)
      scale_ = std::pow(std::numeric_limits<double>::radix,
        std::ilogb(std::pow(10, precision)) + 1);
      invScale_ = 1 / scale_;
    }
References Clipper2Lib::CheckPrecision(), invScale_, and scale_.
Member Function Documentation
AddClip()
void Clipper2Lib::ClipperD::AddClip (const PathsD & clips) inline
    {
      AddPaths(ScalePaths<int64_t, double>(clips, scale_), PathType::Clip, false);
    }
References Clipper2Lib::ClipperBase::AddPaths(), Clipper2Lib::Clip, and scale_.
Referenced by Clipper2Lib::BooleanOp(), and Clipper2Lib::BooleanOp().
AddJoin()
void Clipper2Lib::ClipperBase::AddJoin (OutPt * op1, OutPt * op2) private inherited
  {
    if ((op1->outrec == op2->outrec) && ((op1 == op2) ||
      //unless op1.next or op1.prev crosses the start-end divide
      //don't waste time trying to join adjacent vertices
      ((op1->next == op2) && (op1 != op1->outrec->pts)) ||
      ((op2->next == op1) && (op2 != op1->outrec->pts)))) return;
    Joiner* j = new Joiner(op1, op2, nullptr);
    j->idx = static_cast<int>(joiner_list_.size());
    joiner_list_.push_back(j);
  }
References Clipper2Lib::Joiner::idx, Clipper2Lib::ClipperBase::joiner_list_, Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::outrec, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins(), Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::ClipperBase::ProcessIntersectList(), and Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL().
AddLocalMaxPoly()
OutPt * Clipper2Lib::ClipperBase::AddLocalMaxPoly (Active & e1, Active & e2, const Point64 & pt) private inherited
  {
    if (IsFront(e1) == IsFront(e2))
    {
      if (IsOpenEnd(e1))
        SwapFrontBackSides(*e1.outrec);
      else if (IsOpenEnd(e2))
        SwapFrontBackSides(*e2.outrec);
      else
      {
        succeeded_ = false;
        return nullptr;
      }
    }
    OutPt* result = AddOutPt(e1, pt);
    if (e1.outrec == e2.outrec)
    {
      OutRec& outrec = *e1.outrec;
      outrec.pts = result;
      UncoupleOutRec(e1);
      if (!IsOpen(e1)) CleanCollinear(&outrec);
      result = outrec.pts;
      if (using_polytree_ && outrec.owner && !outrec.owner->front_edge)
        outrec.owner = GetRealOutRec(outrec.owner->owner);
    }
    //and to preserve the winding orientation of outrec ...
    else if (IsOpen(e1))
    {
      if (e1.wind_dx < 0)
        JoinOutrecPaths(e1, e2);
      else
        JoinOutrecPaths(e2, e1);
    }
    else if (e1.outrec->idx < e2.outrec->idx)
      JoinOutrecPaths(e1, e2);
    else
      JoinOutrecPaths(e2, e1);
    return result;
  }
References Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::ClipperBase::CleanCollinear(), Clipper2Lib::OutRec::front_edge, Clipper2Lib::GetRealOutRec(), Clipper2Lib::OutRec::idx, Clipper2Lib::IsFront(), Clipper2Lib::IsOpen(), Clipper2Lib::IsOpenEnd(), Clipper2Lib::ClipperBase::JoinOutrecPaths(), Clipper2Lib::Active::outrec, Clipper2Lib::OutRec::owner, Clipper2Lib::OutRec::pts, Clipper2Lib::ClipperBase::succeeded_, Clipper2Lib::SwapFrontBackSides(), Clipper2Lib::UncoupleOutRec(), Clipper2Lib::ClipperBase::using_polytree_, and Clipper2Lib::Active::wind_dx.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), and Clipper2Lib::ClipperBase::IntersectEdges().
AddLocalMinPoly()
OutPt * Clipper2Lib::ClipperBase::AddLocalMinPoly (Active & e1, Active & e2, const Point64 & pt, bool is_new = false) private inherited
  {
    OutRec* outrec = new OutRec();
    outrec->idx = (unsigned)outrec_list_.size();
    outrec_list_.push_back(outrec);
    outrec->pts = nullptr;
    outrec->polypath = nullptr;
    e1.outrec = outrec;
    e2.outrec = outrec;
    //Setting the owner and inner/outer states (above) is an essential
    //precursor to setting edge 'sides' (ie left and right sides of output
    //polygons) and hence the orientation of output paths ...
    if (IsOpen(e1))
    {
      outrec->owner = nullptr;
      outrec->is_open = true;
      if (e1.wind_dx > 0)
        SetSides(*outrec, e1, e2);
      else
        SetSides(*outrec, e2, e1);
    }
    else
    {
      Active* prevHotEdge = GetPrevHotEdge(e1);
      //e.windDx is the winding direction of the **input** paths
      //and unrelated to the winding direction of output polygons.
      //Output orientation is determined by e.outrec.frontE which is
      //the ascending edge (see AddLocalMinPoly).
      if (prevHotEdge)
      {
        outrec->owner = prevHotEdge->outrec;
        if (OutrecIsAscending(prevHotEdge) == is_new)
          SetSides(*outrec, e2, e1);
        else
          SetSides(*outrec, e1, e2);
      }
      else
      {
        outrec->owner = nullptr;
        if (is_new)
          SetSides(*outrec, e1, e2);
        else
          SetSides(*outrec, e2, e1);
      }
    }
    OutPt* op = new OutPt(pt, outrec);
    outrec->pts = op;
    return op;
  }
References Clipper2Lib::GetPrevHotEdge(), Clipper2Lib::OutRec::idx, Clipper2Lib::OutRec::is_open, Clipper2Lib::IsOpen(), Clipper2Lib::Active::outrec, Clipper2Lib::ClipperBase::outrec_list_, Clipper2Lib::OutrecIsAscending(), Clipper2Lib::OutRec::owner, Clipper2Lib::OutRec::polypath, Clipper2Lib::OutRec::pts, Clipper2Lib::SetSides(), and Clipper2Lib::Active::wind_dx.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), and Clipper2Lib::ClipperBase::IntersectEdges().
AddLocMin()
void Clipper2Lib::ClipperBase::AddLocMin (Vertex & vert, PathType polytype, bool is_open) private inherited
  {
    //make sure the vertex is added only once ...
    if ((VertexFlags::LocalMin & vert.flags) != VertexFlags::None) return;
    vert.flags = (vert.flags | VertexFlags::LocalMin);
    minima_list_.push_back(new LocalMinima(&vert, polytype, is_open));
  }
References Clipper2Lib::Vertex::flags, Clipper2Lib::LocalMin, Clipper2Lib::ClipperBase::minima_list_, and Clipper2Lib::None.
Referenced by Clipper2Lib::ClipperBase::AddPaths().
AddNewIntersectNode()
void Clipper2Lib::ClipperBase::AddNewIntersectNode (Active & e1, Active & e2, const int64_t top_y) private inherited
  {
    Point64 pt = GetIntersectPoint(e1, e2);
    //rounding errors can occasionally place the calculated intersection
    //point either below or above the scanbeam, so check and correct ...
    if (pt.y > bot_y_)
    {
      //e.curr.y is still the bottom of scanbeam
      pt.y = bot_y_;
      //use the more vertical of the 2 edges to derive pt.x ...
      if (abs(e1.dx) < abs(e2.dx))
        pt.x = TopX(e1, bot_y_);
      else
        pt.x = TopX(e2, bot_y_);
    }
    else if (pt.y < top_y)
    {
      //top_y is at the top of the scanbeam
      pt.y = top_y;
      if (e1.top.y == top_y)
        pt.x = e1.top.x;
      else if (e2.top.y == top_y)
        pt.x = e2.top.x;
      else if (abs(e1.dx) < abs(e2.dx))
        pt.x = e1.curr_x;
      else
        pt.x = e2.curr_x;
    }
    intersect_nodes_.push_back(IntersectNode(&e1, &e2, pt));
  }
References Clipper2Lib::ClipperBase::bot_y_, Clipper2Lib::Active::curr_x, Clipper2Lib::Active::dx, Clipper2Lib::GetIntersectPoint(), Clipper2Lib::ClipperBase::intersect_nodes_, Clipper2Lib::Active::top, Clipper2Lib::TopX(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::BuildIntersectList().
AddOpenSubject()
void Clipper2Lib::ClipperD::AddOpenSubject (const PathsD & open_subjects) inline
    {
      AddPaths(ScalePaths<int64_t, double>(open_subjects, scale_), PathType::Subject, true);
    }
References Clipper2Lib::ClipperBase::AddPaths(), scale_, and Clipper2Lib::Subject.
AddOutPt()
OutPt * Clipper2Lib::ClipperBase::AddOutPt (const Active & e, const Point64 & pt) private inherited
  {
    OutPt* new_op = nullptr;
    //Outrec.OutPts: a circular doubly-linked-list of POutPt where ...
    //op_front[.Prev]* ~~~> op_back & op_back == op_front.Next
    OutRec* outrec = e.outrec;
    bool to_front = IsFront(e);
    OutPt* op_front = outrec->pts;
    OutPt* op_back = op_front->next;
    if (to_front && (pt == op_front->pt))
      new_op = op_front;
    else if (!to_front && (pt == op_back->pt))
      new_op = op_back;
    else
    {
      new_op = new OutPt(pt, outrec);
      op_back->prev = new_op;
      new_op->prev = op_front;
      new_op->next = op_back;
      op_front->next = new_op;
      if (to_front) outrec->pts = new_op;
    }
    return new_op;
  }
References Clipper2Lib::IsFront(), Clipper2Lib::OutPt::next, Clipper2Lib::Active::outrec, Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::ClipperBase::DoTopOfScanbeam(), Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::ClipperBase::ProcessIntersectList(), and Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL().
AddPath()
void Clipper2Lib::ClipperBase::AddPath (const Path64 & path, PathType polytype, bool is_open) protected inherited
  {
    Paths64 tmp;
    tmp.push_back(path);
    AddPaths(tmp, polytype, is_open);
  }
References Clipper2Lib::ClipperBase::AddPaths().
AddPaths()
void Clipper2Lib::ClipperBase::AddPaths (const Paths64 & paths, PathType polytype, bool is_open) protected inherited
  {
    if (is_open) has_open_paths_ = true;
    minima_list_sorted_ = false;
    Path64::size_type total_vertex_count = 0;
    for (const Path64& path : paths) total_vertex_count += path.size();
    if (total_vertex_count == 0) return;
    Vertex* vertices = new Vertex[total_vertex_count], *v = vertices;
    for (const Path64& path : paths)
    {
      //for each path create a circular double linked list of vertices
      Vertex *v0 = v, *curr_v = v, *prev_v = nullptr;
      v->prev = nullptr;
      int cnt = 0;
      for (const Point64& pt : path)
      {
        if (prev_v)
        {
          if (prev_v->pt == pt) continue; // ie skips duplicates
          prev_v->next = curr_v;
        }
        curr_v->prev = prev_v;
        curr_v->pt = pt;
        curr_v->flags = VertexFlags::None;
        prev_v = curr_v++;
        cnt++;
      }
      if (!prev_v || !prev_v->prev) continue;
      if (!is_open && prev_v->pt == v0->pt)
        prev_v = prev_v->prev;
      prev_v->next = v0;
      v0->prev = prev_v;
      v = curr_v; // ie get ready for next path
      if (cnt < 2 || (cnt == 2 && !is_open)) continue;
      //now find and assign local minima
      bool going_up, going_up0;
      if (is_open)
      {
        curr_v = v0->next;
        while (curr_v != v0 && curr_v->pt.y == v0->pt.y)
          curr_v = curr_v->next;
        going_up = curr_v->pt.y <= v0->pt.y;
        if (going_up)
        {
          v0->flags = VertexFlags::OpenStart;
          AddLocMin(*v0, polytype, true);
        }
        else
          v0->flags = VertexFlags::OpenStart | VertexFlags::LocalMax;
      }
      else // closed path
      {
        prev_v = v0->prev;
        while (prev_v != v0 && prev_v->pt.y == v0->pt.y)
          prev_v = prev_v->prev;
        if (prev_v == v0)
          continue; // only open paths can be completely flat
        going_up = prev_v->pt.y > v0->pt.y;
      }
      going_up0 = going_up;
      prev_v = v0;
      curr_v = v0->next;
      while (curr_v != v0)
      {
        if (curr_v->pt.y > prev_v->pt.y && going_up)
        {
          prev_v->flags = (prev_v->flags | VertexFlags::LocalMax);
          going_up = false;
        }
        else if (curr_v->pt.y < prev_v->pt.y && !going_up)
        {
          going_up = true;
          AddLocMin(*prev_v, polytype, is_open);
        }
        prev_v = curr_v;
        curr_v = curr_v->next;
      }
      if (is_open)
      {
        prev_v->flags = prev_v->flags | VertexFlags::OpenEnd;
        if (going_up)
          prev_v->flags = prev_v->flags | VertexFlags::LocalMax;
        else
          AddLocMin(*prev_v, polytype, is_open);
      }
      else if (going_up != going_up0)
      {
        if (going_up0) AddLocMin(*prev_v, polytype, false);
        else prev_v->flags = prev_v->flags | VertexFlags::LocalMax;
      }
    } // end processing current path
    vertex_lists_.emplace_back(vertices);
  } // end AddPaths
References Clipper2Lib::ClipperBase::AddLocMin(), Clipper2Lib::Vertex::flags, Clipper2Lib::ClipperBase::has_open_paths_, Clipper2Lib::LocalMax, Clipper2Lib::ClipperBase::minima_list_sorted_, Clipper2Lib::Vertex::next, Clipper2Lib::None, Clipper2Lib::OpenEnd, Clipper2Lib::OpenStart, Clipper2Lib::Vertex::prev, Clipper2Lib::Vertex::pt, Clipper2Lib::ClipperBase::vertex_lists_, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::Clipper64::AddClip(), AddClip(), Clipper2Lib::Clipper64::AddOpenSubject(), AddOpenSubject(), Clipper2Lib::ClipperBase::AddPath(), Clipper2Lib::Clipper64::AddSubject(), and AddSubject().
AddSubject()
void Clipper2Lib::ClipperD::AddSubject (const PathsD & subjects) inline
    {
      AddPaths(ScalePaths<int64_t, double>(subjects, scale_), PathType::Subject, false);
    }
References Clipper2Lib::ClipperBase::AddPaths(), scale_, and Clipper2Lib::Subject.
Referenced by Clipper2Lib::BooleanOp(), Clipper2Lib::BooleanOp(), and Clipper2Lib::Union().
AddTrialHorzJoin()
void Clipper2Lib::ClipperBase::AddTrialHorzJoin (OutPt * op) private inherited
  {
    //make sure 'op' isn't added more than once
    if (!op->outrec->is_open && !OutPtInTrialHorzList(op))
      horz_joiners_ = new Joiner(op, nullptr, horz_joiners_);
  }
References Clipper2Lib::ClipperBase::horz_joiners_, Clipper2Lib::OutRec::is_open, Clipper2Lib::ClipperBase::OutPtInTrialHorzList(), and Clipper2Lib::OutPt::outrec.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal().
AdjustCurrXAndCopyToSEL()
void Clipper2Lib::ClipperBase::AdjustCurrXAndCopyToSEL (const int64_t top_y) inline private inherited
  {
    Active* e = actives_;
    sel_ = e;
    while (e)
    {
      e->prev_in_sel = e->prev_in_ael;
      e->next_in_sel = e->next_in_ael;
      e->jump = e->next_in_sel;
      e->curr_x = TopX(*e, top_y);
      e = e->next_in_ael;
    }
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::Active::curr_x, Clipper2Lib::Active::jump, Clipper2Lib::Active::next_in_ael, Clipper2Lib::Active::next_in_sel, Clipper2Lib::Active::prev_in_ael, Clipper2Lib::Active::prev_in_sel, Clipper2Lib::ClipperBase::sel_, and Clipper2Lib::TopX().
Referenced by Clipper2Lib::ClipperBase::BuildIntersectList().
BuildIntersectList()
bool Clipper2Lib::ClipperBase::BuildIntersectList (const int64_t top_y) private inherited
  {
    if (!actives_ || !actives_->next_in_ael) return false;
    //Calculate edge positions at the top of the current scanbeam, and from this
    //we will determine the intersections required to reach these new positions.
    AdjustCurrXAndCopyToSEL(top_y);
    //Find all edge intersections in the current scanbeam using a stable merge
    //sort that ensures only adjacent edges are intersecting. Intersect info is
    //stored in FIntersectList ready to be processed in ProcessIntersectList.
    //Re merge sorts see https://stackoverflow.com/a/46319131/359538
    Active* left = sel_, * right, * l_end, * r_end, * curr_base, * tmp;
    while (left && left->jump)
    {
      Active* prev_base = nullptr;
      while (left && left->jump)
      {
        curr_base = left;
        right = left->jump;
        l_end = right;
        r_end = right->jump;
        left->jump = r_end;
        while (left != l_end && right != r_end)
        {
          if (right->curr_x < left->curr_x)
          {
            tmp = right->prev_in_sel;
            for (; ; )
            {
              AddNewIntersectNode(*tmp, *right, top_y);
              if (tmp == left) break;
              tmp = tmp->prev_in_sel;
            }
            tmp = right;
            right = ExtractFromSEL(tmp);
            l_end = right;
            Insert1Before2InSEL(tmp, left);
            if (left == curr_base)
            {
              curr_base = tmp;
              curr_base->jump = r_end;
              if (!prev_base) sel_ = curr_base;
              else prev_base->jump = curr_base;
            }
          }
          else left = left->next_in_sel;
        }
        prev_base = curr_base;
        left = r_end;
      }
      left = sel_;
    }
    return intersect_nodes_.size() > 0;
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::ClipperBase::AddNewIntersectNode(), Clipper2Lib::ClipperBase::AdjustCurrXAndCopyToSEL(), Clipper2Lib::ExtractFromSEL(), Clipper2Lib::Insert1Before2InSEL(), Clipper2Lib::ClipperBase::intersect_nodes_, Clipper2Lib::Active::jump, Clipper2Lib::Active::next_in_ael, and Clipper2Lib::ClipperBase::sel_.
Referenced by Clipper2Lib::ClipperBase::DoIntersections().
BuildPathsD()
void Clipper2Lib::ClipperD::BuildPathsD (PathsD & solutionClosed, PathsD * solutionOpen) private
  {
    solutionClosed.resize(0);
    solutionClosed.reserve(outrec_list_.size());
    if (solutionOpen)
    {
      solutionOpen->resize(0);
      solutionOpen->reserve(outrec_list_.size());
    }
    for (OutRec* outrec : outrec_list_)
    {
      if (outrec->pts == nullptr) continue;
      PathD path;
      if (solutionOpen && outrec->is_open)
      {
        if (BuildPathD(outrec->pts, ReverseSolution, true, path, invScale_))
          solutionOpen->emplace_back(std::move(path));
      }
      else
      {
        //closed paths should always return a Positive orientation
        if (BuildPathD(outrec->pts, ReverseSolution, false, path, invScale_))
          solutionClosed.emplace_back(std::move(path));
      }
    }
  }
References Clipper2Lib::BuildPathD(), invScale_, Clipper2Lib::ClipperBase::outrec_list_, and Clipper2Lib::ClipperBase::ReverseSolution.
Referenced by Execute().
BuildTreeD()
void Clipper2Lib::ClipperD::BuildTreeD (PolyPathD & polytree, PathsD & open_paths) private
  {
    polytree.Clear();
    open_paths.resize(0);
    if (has_open_paths_)
      open_paths.reserve(outrec_list_.size());
    for (OutRec* outrec : outrec_list_)
    {
      if (!outrec || !outrec->pts) continue;
      if (outrec->is_open)
      {
        PathD path;
        if (BuildPathD(outrec->pts, ReverseSolution, true, path, invScale_))
          open_paths.push_back(path);
        continue;
      }
      if (!BuildPath64(outrec->pts, ReverseSolution, false, outrec->path))
        continue;
      if (outrec->bounds.IsEmpty()) outrec->bounds = GetBounds(outrec->path);
      outrec->owner = GetRealOutRec(outrec->owner);
      if (outrec->owner) DeepCheckOwner(outrec, outrec->owner);
      // swap the order when a child preceeds its owner
      // (because owners must preceed children in polytrees)
      if (outrec->owner && outrec->idx < outrec->owner->idx)
      {
        OutRec* tmp = outrec->owner;
        outrec_list_[outrec->owner->idx] = outrec;
        outrec_list_[outrec->idx] = tmp;
        size_t tmp_idx = outrec->idx;
        outrec->idx = tmp->idx;
        tmp->idx = tmp_idx;
        outrec = tmp;
        outrec->owner = GetRealOutRec(outrec->owner);
        BuildPath64(outrec->pts, ReverseSolution, false, outrec->path);
        if (outrec->bounds.IsEmpty()) outrec->bounds = GetBounds(outrec->path);
        if (outrec->owner) DeepCheckOwner(outrec, outrec->owner);
      }
      PolyPath* owner_polypath;
      if (outrec->owner && outrec->owner->polypath)
        owner_polypath = outrec->owner->polypath;
      else
        owner_polypath = &polytree;
      outrec->polypath = owner_polypath->AddChild(outrec->path);
    }
  }
References Clipper2Lib::PolyPath::AddChild(), Clipper2Lib::BuildPath64(), Clipper2Lib::BuildPathD(), Clipper2Lib::PolyPathD::Clear(), Clipper2Lib::ClipperBase::DeepCheckOwner(), Clipper2Lib::GetBounds(), Clipper2Lib::GetRealOutRec(), Clipper2Lib::ClipperBase::has_open_paths_, Clipper2Lib::OutRec::idx, invScale_, Clipper2Lib::ClipperBase::outrec_list_, Clipper2Lib::OutRec::owner, and Clipper2Lib::ClipperBase::ReverseSolution.
Referenced by Execute().
CleanCollinear()
void Clipper2Lib::ClipperBase::CleanCollinear (OutRec * outrec) private inherited
  {
    outrec = GetRealOutRec(outrec);
    if (!outrec || outrec->is_open ||
      outrec->front_edge || !ValidateClosedPathEx(outrec->pts)) return;
    OutPt* startOp = outrec->pts, * op2 = startOp;
    for (; ; )
    {
      if (op2->joiner) return;
      //NB if preserveCollinear == true, then only remove 180 deg. spikes
      if ((CrossProduct(op2->prev->pt, op2->pt, op2->next->pt) == 0) &&
        (op2->pt == op2->prev->pt ||
          op2->pt == op2->next->pt || !PreserveCollinear ||
          DotProduct(op2->prev->pt, op2->pt, op2->next->pt) < 0))
      {
        if (op2 == outrec->pts) outrec->pts = op2->prev;
        op2 = DisposeOutPt(op2);
        if (!ValidateClosedPathEx(op2))
        {
          outrec->pts = nullptr;
          return;
        }
        startOp = op2;
        continue;
      }
      op2 = op2->next;
      if (op2 == startOp) break;
    }
    FixSelfIntersects(outrec);
  }
References Clipper2Lib::CrossProduct(), Clipper2Lib::DisposeOutPt(), Clipper2Lib::DotProduct(), Clipper2Lib::ClipperBase::FixSelfIntersects(), Clipper2Lib::OutRec::front_edge, Clipper2Lib::GetRealOutRec(), Clipper2Lib::OutRec::is_open, Clipper2Lib::OutPt::next, Clipper2Lib::ClipperBase::PreserveCollinear, Clipper2Lib::OutPt::prev, Clipper2Lib::OutRec::pts, and Clipper2Lib::ClipperBase::ValidateClosedPathEx().
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::CompleteSplit(), Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins(), Clipper2Lib::ClipperBase::ProcessJoin(), and Clipper2Lib::ClipperBase::ProcessJoinerList().
CleanUp()
void Clipper2Lib::ClipperBase::CleanUp () protected inherited
  {
    DeleteEdges(actives_);
    scanline_list_ = std::priority_queue<int64_t>();
    intersect_nodes_.clear();
    DisposeAllOutRecs();
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::ClipperBase::DeleteEdges(), Clipper2Lib::ClipperBase::DisposeAllOutRecs(), Clipper2Lib::ClipperBase::intersect_nodes_, and Clipper2Lib::ClipperBase::scanline_list_.
Referenced by Clipper2Lib::ClipperBase::Clear(), Clipper2Lib::Clipper64::Execute(), Execute(), Clipper2Lib::Clipper64::Execute(), and Execute().
Clear()
void Clipper2Lib::ClipperBase::Clear () inherited
  {
    CleanUp();
    DisposeVerticesAndLocalMinima();
    current_locmin_iter_ = minima_list_.begin();
    minima_list_sorted_ = false;
    has_open_paths_ = false;
  }
References Clipper2Lib::ClipperBase::CleanUp(), Clipper2Lib::ClipperBase::current_locmin_iter_, Clipper2Lib::ClipperBase::DisposeVerticesAndLocalMinima(), Clipper2Lib::ClipperBase::has_open_paths_, Clipper2Lib::ClipperBase::minima_list_, and Clipper2Lib::ClipperBase::minima_list_sorted_.
Referenced by Clipper2Lib::ClipperBase::~ClipperBase().
CompleteSplit()
void Clipper2Lib::ClipperBase::CompleteSplit (OutPt * op1, OutPt * op2, OutRec & outrec) private inherited
  {
    double area1 = Area(op1);
    double area2 = Area(op2);
    bool signs_change = (area1 > 0) == (area2 < 0);
    if (area1 == 0 || (signs_change && std::abs(area1) < 2))
    {
      SafeDisposeOutPts(op1);
      outrec.pts = op2;
    }
    else if (area2 == 0 || (signs_change && std::abs(area2) < 2))
    {
      SafeDisposeOutPts(op2);
      outrec.pts = op1;
    }
    else
    {
      OutRec* newOr = new OutRec();
      newOr->idx = outrec_list_.size();
      outrec_list_.push_back(newOr);
      newOr->polypath = nullptr;
      if (using_polytree_)
      {
        if (!outrec.splits) outrec.splits = new OutRecList();
        outrec.splits->push_back(newOr);
      }
      if (std::abs(area1) >= std::abs(area2))
      {
        outrec.pts = op1;
        newOr->pts = op2;
      }
      else
      {
        outrec.pts = op2;
        newOr->pts = op1;
      }
      if ((area1 > 0) == (area2 > 0))
        newOr->owner = outrec.owner;
      else
        newOr->owner = &outrec;
      UpdateOutrecOwner(newOr);
      CleanCollinear(newOr);
    }
  }
References Clipper2Lib::Area(), Clipper2Lib::ClipperBase::CleanCollinear(), Clipper2Lib::OutRec::idx, Clipper2Lib::ClipperBase::outrec_list_, Clipper2Lib::OutRec::owner, Clipper2Lib::OutRec::polypath, Clipper2Lib::OutRec::pts, Clipper2Lib::ClipperBase::SafeDisposeOutPts(), Clipper2Lib::OutRec::splits, Clipper2Lib::UpdateOutrecOwner(), and Clipper2Lib::ClipperBase::using_polytree_.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin().
ConvertHorzTrialsToJoins()
void Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins () private inherited
  {
    while (horz_joiners_)
    {
      Joiner* joiner = horz_joiners_;
      horz_joiners_ = horz_joiners_->nextH;
      OutPt* op1a = joiner->op1;
      if (op1a->joiner == joiner)
      {
        op1a->joiner = joiner->next1;
      }
      else
      {
        Joiner* joinerParent = FindJoinParent(joiner, op1a);
        if (joinerParent->op1 == op1a)
          joinerParent->next1 = joiner->next1;
        else
          joinerParent->next2 = joiner->next1;
      }
      delete joiner;
      OutPt* op1b;
      if (!GetHorzExtendedHorzSeg(op1a, op1b))
      {
        CleanCollinear(op1a->outrec);
        continue;
      }
      bool joined = false;
      joiner = horz_joiners_;
      while (joiner)
      {
        OutPt* op2a = joiner->op1, * op2b;
        if (GetHorzExtendedHorzSeg(op2a, op2b) &&
          HorzEdgesOverlap(op1a->pt.x, op1b->pt.x, op2a->pt.x, op2b->pt.x))
        {
          //overlap found so promote to a 'real' join
          joined = true;
          if (op1a->pt == op2b->pt)
            AddJoin(op1a, op2b);
          else if (op1b->pt == op2a->pt)
            AddJoin(op1b, op2a);
          else if (op1a->pt == op2a->pt)
            AddJoin(op1a, op2a);
          else if (op1b->pt == op2b->pt)
            AddJoin(op1b, op2b);
          else if (ValueBetween(op1a->pt.x, op2a->pt.x, op2b->pt.x))
            AddJoin(op1a, InsertOp(op1a->pt, op2a));
          else if (ValueBetween(op1b->pt.x, op2a->pt.x, op2b->pt.x))
            AddJoin(op1b, InsertOp(op1b->pt, op2a));
          else if (ValueBetween(op2a->pt.x, op1a->pt.x, op1b->pt.x))
            AddJoin(op2a, InsertOp(op2a->pt, op1a));
          else if (ValueBetween(op2b->pt.x, op1a->pt.x, op1b->pt.x))
            AddJoin(op2b, InsertOp(op2b->pt, op1a));
          break;
        }
        joiner = joiner->nextH;
      }
      if (!joined)
        CleanCollinear(op1a->outrec);
    }
  }
References Clipper2Lib::ClipperBase::AddJoin(), Clipper2Lib::ClipperBase::CleanCollinear(), Clipper2Lib::FindJoinParent(), Clipper2Lib::GetHorzExtendedHorzSeg(), Clipper2Lib::ClipperBase::horz_joiners_, Clipper2Lib::HorzEdgesOverlap(), Clipper2Lib::InsertOp(), Clipper2Lib::OutPt::joiner, Clipper2Lib::Joiner::next1, Clipper2Lib::Joiner::next2, Clipper2Lib::Joiner::nextH, Clipper2Lib::Joiner::op1, Clipper2Lib::OutPt::outrec, Clipper2Lib::OutPt::pt, Clipper2Lib::ValueBetween(), and Clipper2Lib::Point< T >::x.
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
DeepCheckOwner()
bool Clipper2Lib::ClipperBase::DeepCheckOwner (OutRec * outrec, OutRec * owner) protected inherited
  {
    if (owner->bounds.IsEmpty()) owner->bounds = GetBounds(owner->path);
    bool is_inside_owner_bounds = owner->bounds.Contains(outrec->bounds);
    // while looking for the correct owner, check the owner's
    // splits **before** checking the owner itself because
    // splits can occur internally, and checking the owner
    // first would miss the inner split's true ownership
    if (owner->splits)
    {
      for (OutRec* split : *owner->splits)
      {
        split = GetRealOutRec(split);
        if (!split || split->idx <= owner->idx || split == outrec) continue;
        if (split->splits && DeepCheckOwner(outrec, split)) return true;
        if (!split->path.size())
          BuildPath64(split->pts, ReverseSolution, false, split->path);
        if (split->bounds.IsEmpty()) split->bounds = GetBounds(split->path);
        if (split->bounds.Contains(outrec->bounds) &&
          Path1InsidePath2(outrec, split))
        {
          outrec->owner = split;
          return true;
        }
      }
    }
    // only continue past here when not inside recursion
    if (owner != outrec->owner) return false;
    for (;;)
    {
      if (is_inside_owner_bounds && Path1InsidePath2(outrec, outrec->owner))
        return true;
      // otherwise keep trying with owner's owner
      outrec->owner = outrec->owner->owner;
      if (!outrec->owner) return true; // true or false
      is_inside_owner_bounds = outrec->owner->bounds.Contains(outrec->bounds);
    }
  }
References Clipper2Lib::OutRec::bounds, Clipper2Lib::BuildPath64(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::ClipperBase::DeepCheckOwner(), Clipper2Lib::GetBounds(), Clipper2Lib::GetRealOutRec(), Clipper2Lib::OutRec::idx, Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::OutRec::owner, Clipper2Lib::OutRec::path, Clipper2Lib::Path1InsidePath2(), Clipper2Lib::ClipperBase::ReverseSolution, and Clipper2Lib::OutRec::splits.
Referenced by Clipper2Lib::Clipper64::BuildTree64(), BuildTreeD(), and Clipper2Lib::ClipperBase::DeepCheckOwner().
DeleteEdges()
void Clipper2Lib::ClipperBase::DeleteEdges (Active *& e) private inherited
  {
    while (e)
    {
      Active* e2 = e;
      e = e->next_in_ael;
      delete e2;
    }
  }
References Clipper2Lib::Active::next_in_ael.
Referenced by Clipper2Lib::ClipperBase::CleanUp().
DeleteFromAEL()
void Clipper2Lib::ClipperBase::DeleteFromAEL (Active & e) inline private inherited
  {
    Active* prev = e.prev_in_ael;
    Active* next = e.next_in_ael;
    if (!prev && !next && (&e != actives_)) return;  // already deleted
    if (prev)
      prev->next_in_ael = next;
    else
      actives_ = next;
    if (next) next->prev_in_ael = prev;
    delete& e;
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::Active::next_in_ael, and Clipper2Lib::Active::prev_in_ael.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), and Clipper2Lib::ClipperBase::DoMaxima().
DeleteJoin()
void Clipper2Lib::ClipperBase::DeleteJoin (Joiner * joiner) private inherited
  {
    //This method deletes a single join, and it doesn't check for or
    //delete trial horz. joins. For that, use the following method.
    OutPt* op1 = joiner->op1, * op2 = joiner->op2;
    Joiner* parent_joiner;
    if (op1->joiner != joiner)
    {
      parent_joiner = FindJoinParent(joiner, op1);
      if (parent_joiner->op1 == op1)
        parent_joiner->next1 = joiner->next1;
      else
        parent_joiner->next2 = joiner->next1;
    }
    else
      op1->joiner = joiner->next1;
    if (op2->joiner != joiner)
    {
      parent_joiner = FindJoinParent(joiner, op2);
      if (parent_joiner->op1 == op2)
        parent_joiner->next1 = joiner->next2;
      else
        parent_joiner->next2 = joiner->next2;
    }
    else
      op2->joiner = joiner->next2;
    joiner_list_[joiner->idx] = nullptr;
    delete joiner;
  }
References Clipper2Lib::FindJoinParent(), Clipper2Lib::Joiner::idx, Clipper2Lib::OutPt::joiner, Clipper2Lib::ClipperBase::joiner_list_, Clipper2Lib::Joiner::next1, Clipper2Lib::Joiner::next2, Clipper2Lib::Joiner::op1, and Clipper2Lib::Joiner::op2.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin(), and Clipper2Lib::ClipperBase::SafeDeleteOutPtJoiners().
DeleteTrialHorzJoin()
void Clipper2Lib::ClipperBase::DeleteTrialHorzJoin (OutPt * op) private inherited
  {
    if (!horz_joiners_) return;
    Joiner* joiner = op->joiner;
    Joiner* parentH, * parentOp = nullptr;
    while (joiner)
    {
      if (joiner->idx < 0)
      {
        //first remove joiner from FHorzTrials
        if (joiner == horz_joiners_)
          horz_joiners_ = joiner->nextH;
        else
        {
          parentH = horz_joiners_;
          while (parentH->nextH != joiner)
            parentH = parentH->nextH;
          parentH->nextH = joiner->nextH;
        }
        //now remove joiner from op's joiner list
        if (!parentOp)
        {
          //joiner must be first one in list
          op->joiner = joiner->next1;
          delete joiner;
          joiner = op->joiner;
        }
        else
        {
          //the trial joiner isn't first
          if (op == parentOp->op1)
            parentOp->next1 = joiner->next1;
          else
            parentOp->next2 = joiner->next1;
          delete joiner;
          joiner = parentOp;
        }
      }
      else
      {
        //not a trial join so look further along the linked list
        parentOp = FindTrialJoinParent(joiner, op);
        if (!parentOp) break;
      }
      //loop in case there's more than one trial join
    }
  }
References Clipper2Lib::FindTrialJoinParent(), Clipper2Lib::ClipperBase::horz_joiners_, Clipper2Lib::Joiner::idx, Clipper2Lib::OutPt::joiner, Clipper2Lib::Joiner::next1, Clipper2Lib::Joiner::next2, Clipper2Lib::Joiner::nextH, and Clipper2Lib::Joiner::op1.
Referenced by Clipper2Lib::ClipperBase::SafeDeleteOutPtJoiners().
DisposeAllOutRecs()
void Clipper2Lib::ClipperBase::DisposeAllOutRecs () private inherited
  {
    for (auto outrec : outrec_list_)
    {
      if (outrec->pts) DisposeOutPts(*outrec);
      delete outrec;
    }
    outrec_list_.resize(0);
  }
References Clipper2Lib::DisposeOutPts(), and Clipper2Lib::ClipperBase::outrec_list_.
Referenced by Clipper2Lib::ClipperBase::CleanUp().
DisposeVerticesAndLocalMinima()
void Clipper2Lib::ClipperBase::DisposeVerticesAndLocalMinima () private inherited
  {
    for (auto lm : minima_list_) delete lm;
    minima_list_.clear();
    for (auto v : vertex_lists_) delete[] v;
    vertex_lists_.clear();
  }
References Clipper2Lib::ClipperBase::minima_list_, and Clipper2Lib::ClipperBase::vertex_lists_.
Referenced by Clipper2Lib::ClipperBase::Clear().
DoHorizontal()
void Clipper2Lib::ClipperBase::DoHorizontal (Active & horz) private inherited
  {
    Point64 pt;
    bool horzIsOpen = IsOpen(horz);
    int64_t y = horz.bot.y;
    Vertex* vertex_max = nullptr;
    Active* max_pair = nullptr;
    if (!horzIsOpen)
    {
      vertex_max = GetCurrYMaximaVertex(horz);
      if (vertex_max)
      {
        max_pair = GetHorzMaximaPair(horz, vertex_max);
        //remove 180 deg.spikes and also simplify
        //consecutive horizontals when PreserveCollinear = true
        if (vertex_max != horz.vertex_top)
          TrimHorz(horz, PreserveCollinear);
      }
    }
    int64_t horz_left, horz_right;
    bool is_left_to_right =
      ResetHorzDirection(horz, max_pair, horz_left, horz_right);
    if (IsHotEdge(horz))
      AddOutPt(horz, Point64(horz.curr_x, y));
    OutPt* op;
    while (true) // loop through consec. horizontal edges
    {
      if (horzIsOpen && IsMaxima(horz) && !IsOpenEnd(horz))
      {
        vertex_max = GetCurrYMaximaVertex(horz);
        if (vertex_max)
          max_pair = GetHorzMaximaPair(horz, vertex_max);
      }
      Active* e;
      if (is_left_to_right) e = horz.next_in_ael;
      else e = horz.prev_in_ael;
      while (e)
      {
        if (e == max_pair)
        {
          if (IsHotEdge(horz))
          {
            while (horz.vertex_top != e->vertex_top)
            {
              AddOutPt(horz, horz.top);
              UpdateEdgeIntoAEL(&horz);
            }
            op = AddLocalMaxPoly(horz, *e, horz.top);
            if (op && !IsOpen(horz) && op->pt == horz.top)
              AddTrialHorzJoin(op);
          }
          DeleteFromAEL(*e);
          DeleteFromAEL(horz);
          return;
        }
        //if horzEdge is a maxima, keep going until we reach
        //its maxima pair, otherwise check for break conditions
        if (vertex_max != horz.vertex_top || IsOpenEnd(horz))
        {
          //otherwise stop when 'ae' is beyond the end of the horizontal line
          if ((is_left_to_right && e->curr_x > horz_right) ||
            (!is_left_to_right && e->curr_x < horz_left)) break;
          if (e->curr_x == horz.top.x && !IsHorizontal(*e))
          {
            pt = NextVertex(horz)->pt;
            if (is_left_to_right)
            {
              //with open paths we'll only break once past horz's end
              if (IsOpen(*e) && !IsSamePolyType(*e, horz) && !IsHotEdge(*e))
              {
                if (TopX(*e, pt.y) > pt.x) break;
              }
              //otherwise we'll only break when horz's outslope is greater than e's
              else if (TopX(*e, pt.y) >= pt.x) break;
            }
            else
            {
              if (IsOpen(*e) && !IsSamePolyType(*e, horz) && !IsHotEdge(*e))
              {
                if (TopX(*e, pt.y) < pt.x) break;
              }
              else if (TopX(*e, pt.y) <= pt.x) break;
            }
          }
        }
        pt = Point64(e->curr_x, horz.bot.y);
        if (is_left_to_right)
        {
          op = IntersectEdges(horz, *e, pt);
          SwapPositionsInAEL(horz, *e);
          // todo: check if op->pt == pt test is still needed
          // expect op != pt only after AddLocalMaxPoly when horz.outrec == nullptr
          if (IsHotEdge(horz) && op && !IsOpen(horz) && op->pt == pt)
            AddTrialHorzJoin(op);
          if (!IsHorizontal(*e) && TestJoinWithPrev1(*e))
          {
            op = AddOutPt(*e->prev_in_ael, pt);
            OutPt* op2 = AddOutPt(*e, pt);
            AddJoin(op, op2);
          }
          horz.curr_x = e->curr_x;
          e = horz.next_in_ael;
        }
        else
        {
          op = IntersectEdges(*e, horz, pt);
          SwapPositionsInAEL(*e, horz);
          if (IsHotEdge(horz) && op &&
            !IsOpen(horz) && op->pt == pt)
            AddTrialHorzJoin(op);
          if (!IsHorizontal(*e) && TestJoinWithNext1(*e))
          {
            op = AddOutPt(*e, pt);
            OutPt* op2 = AddOutPt(*e->next_in_ael, pt);
            AddJoin(op, op2);
          }
          horz.curr_x = e->curr_x;
          e = horz.prev_in_ael;
        }
      }
      //check if we've finished with (consecutive) horizontals ...
      if (horzIsOpen && IsOpenEnd(horz)) // ie open at top
      {
        if (IsHotEdge(horz))
        {
          AddOutPt(horz, horz.top);
          if (IsFront(horz))
            horz.outrec->front_edge = nullptr;
          else
            horz.outrec->back_edge = nullptr;
          horz.outrec = nullptr;
        }
        DeleteFromAEL(horz);
        return;
      }
      else if (NextVertex(horz)->pt.y != horz.top.y)
        break;
      //still more horizontals in bound to process ...
      if (IsHotEdge(horz))
        AddOutPt(horz, horz.top);
      UpdateEdgeIntoAEL(&horz);
      if (PreserveCollinear && !horzIsOpen && HorzIsSpike(horz))
        TrimHorz(horz, true);
      is_left_to_right =
        ResetHorzDirection(horz, max_pair, horz_left, horz_right);
    }
    if (IsHotEdge(horz))
    {
      op = AddOutPt(horz, horz.top);
      if (!IsOpen(horz))
        AddTrialHorzJoin(op);
    }
    else
      op = nullptr;
    if ((horzIsOpen && !IsOpenEnd(horz)) ||
      (!horzIsOpen && vertex_max != horz.vertex_top))
    {
      UpdateEdgeIntoAEL(&horz); // this is the end of an intermediate horiz.
      if (IsOpen(horz)) return;
      if (is_left_to_right && TestJoinWithNext1(horz))
      {
        OutPt* op2 = AddOutPt(*horz.next_in_ael, horz.bot);
        AddJoin(op, op2);
      }
      else if (!is_left_to_right && TestJoinWithPrev1(horz))
      {
        OutPt* op2 = AddOutPt(*horz.prev_in_ael, horz.bot);
        AddJoin(op2, op);
      }
    }
    else if (IsHotEdge(horz))
      AddLocalMaxPoly(horz, *max_pair, horz.top);
    else
    {
      DeleteFromAEL(*max_pair);
      DeleteFromAEL(horz);
    }
  }
References Clipper2Lib::ClipperBase::AddJoin(), Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::ClipperBase::AddTrialHorzJoin(), Clipper2Lib::OutRec::back_edge, Clipper2Lib::Active::bot, Clipper2Lib::Active::curr_x, Clipper2Lib::ClipperBase::DeleteFromAEL(), Clipper2Lib::OutRec::front_edge, Clipper2Lib::GetCurrYMaximaVertex(), Clipper2Lib::GetHorzMaximaPair(), Clipper2Lib::HorzIsSpike(), Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::IsFront(), Clipper2Lib::IsHorizontal(), Clipper2Lib::IsHotEdge(), Clipper2Lib::IsMaxima(), Clipper2Lib::IsOpen(), Clipper2Lib::IsOpenEnd(), Clipper2Lib::IsSamePolyType(), Clipper2Lib::Active::next_in_ael, Clipper2Lib::NextVertex(), Clipper2Lib::Active::outrec, Clipper2Lib::ClipperBase::PreserveCollinear, Clipper2Lib::Active::prev_in_ael, Clipper2Lib::Vertex::pt, Clipper2Lib::OutPt::pt, Clipper2Lib::ClipperBase::ResetHorzDirection(), Clipper2Lib::ClipperBase::SwapPositionsInAEL(), Clipper2Lib::TestJoinWithNext1(), Clipper2Lib::TestJoinWithPrev1(), Clipper2Lib::Active::top, Clipper2Lib::TopX(), Clipper2Lib::TrimHorz(), Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL(), Clipper2Lib::Active::vertex_top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
DoIntersections()
void Clipper2Lib::ClipperBase::DoIntersections (const int64_t top_y) private inherited
  {
    if (BuildIntersectList(top_y))
    {
      ProcessIntersectList();
      intersect_nodes_.clear();
    }
  }
References Clipper2Lib::ClipperBase::BuildIntersectList(), Clipper2Lib::ClipperBase::intersect_nodes_, and Clipper2Lib::ClipperBase::ProcessIntersectList().
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
DoMaxima()
Active * Clipper2Lib::ClipperBase::DoMaxima (Active & e) private inherited
  {
    Active* next_e, * prev_e, * max_pair;
    prev_e = e.prev_in_ael;
    next_e = e.next_in_ael;
    if (IsOpenEnd(e))
    {
      if (IsHotEdge(e)) AddOutPt(e, e.top);
      if (!IsHorizontal(e))
      {
        if (IsHotEdge(e))
        {
          if (IsFront(e))
            e.outrec->front_edge = nullptr;
          else
            e.outrec->back_edge = nullptr;
          e.outrec = nullptr;
        }
        DeleteFromAEL(e);
      }
      return next_e;
    }
    else
    {
      max_pair = GetMaximaPair(e);
      if (!max_pair) return next_e;  // eMaxPair is horizontal
    }
    //only non-horizontal maxima here.
    //process any edges between maxima pair ...
    while (next_e != max_pair)
    {
      IntersectEdges(e, *next_e, e.top);
      SwapPositionsInAEL(e, *next_e);
      next_e = e.next_in_ael;
    }
    if (IsOpen(e))
    {
      if (IsHotEdge(e))
        AddLocalMaxPoly(e, *max_pair, e.top);
      DeleteFromAEL(*max_pair);
      DeleteFromAEL(e);
      return (prev_e ? prev_e->next_in_ael : actives_);
    }
    //here E.next_in_ael == ENext == EMaxPair ...
    if (IsHotEdge(e))
      AddLocalMaxPoly(e, *max_pair, e.top);
    DeleteFromAEL(e);
    DeleteFromAEL(*max_pair);
    return (prev_e ? prev_e->next_in_ael : actives_);
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::OutRec::back_edge, Clipper2Lib::ClipperBase::DeleteFromAEL(), Clipper2Lib::OutRec::front_edge, Clipper2Lib::GetMaximaPair(), Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::IsFront(), Clipper2Lib::IsHorizontal(), Clipper2Lib::IsHotEdge(), Clipper2Lib::IsOpen(), Clipper2Lib::IsOpenEnd(), Clipper2Lib::Active::next_in_ael, Clipper2Lib::Active::outrec, Clipper2Lib::Active::prev_in_ael, Clipper2Lib::ClipperBase::SwapPositionsInAEL(), and Clipper2Lib::Active::top.
Referenced by Clipper2Lib::ClipperBase::DoTopOfScanbeam().
DoSplitOp()
void Clipper2Lib::ClipperBase::DoSplitOp (OutRec * outRec, OutPt * splitOp) private inherited
  {
    // splitOp.prev -> splitOp &&
    // splitOp.next -> splitOp.next.next are intersecting
    OutPt* prevOp = splitOp->prev;
    OutPt* nextNextOp = splitOp->next->next;
    outrec->pts = prevOp;
    PointD ipD;
    GetIntersectPoint(prevOp->pt,
      splitOp->pt, splitOp->next->pt, nextNextOp->pt, ipD);
    Point64 ip = Point64(ipD);
#ifdef USINGZ
    if (zCallback_)
      zCallback_(prevOp->pt, splitOp->pt, splitOp->next->pt, nextNextOp->pt, ip);
#endif
    double area1 = Area(outrec->pts);
    double absArea1 = std::fabs(area1);
    if (absArea1 < 2)
    {
      SafeDisposeOutPts(outrec->pts);
      // outrec.pts == nil; :)
      return;
    }
    // nb: area1 is the path's area *before* splitting, whereas area2 is
    // the area of the triangle containing splitOp & splitOp.next.
    // So the only way for these areas to have the same sign is if
    // the split triangle is larger than the path containing prevOp or
    // if there's more than one self=intersection.
    double area2 = AreaTriangle(ip, splitOp->pt, splitOp->next->pt);
    double absArea2 = std::fabs(area2);
    // de-link splitOp and splitOp.next from the path
    // while inserting the intersection point
    if (ip == prevOp->pt || ip == nextNextOp->pt)
    {
      nextNextOp->prev = prevOp;
      prevOp->next = nextNextOp;
    }
    else
    {
      OutPt* newOp2 = new OutPt(ip, prevOp->outrec);
      newOp2->prev = prevOp;
      newOp2->next = nextNextOp;
      nextNextOp->prev = newOp2;
      prevOp->next = newOp2;
    }
    SafeDeleteOutPtJoiners(splitOp->next);
    SafeDeleteOutPtJoiners(splitOp);
    if (absArea2 >= 1 &&
      (absArea2 > absArea1 || (area2 > 0) == (area1 > 0)))
    {
      OutRec* newOutRec = new OutRec();
      newOutRec->idx = outrec_list_.size();
      outrec_list_.push_back(newOutRec);
      newOutRec->owner = prevOp->outrec->owner;
      newOutRec->polypath = nullptr;
      splitOp->outrec = newOutRec;
      splitOp->next->outrec = newOutRec;
      OutPt* newOp = new OutPt(ip, newOutRec);
      newOp->prev = splitOp->next;
      newOp->next = splitOp;
      newOutRec->pts = newOp;
      splitOp->prev = newOp;
      splitOp->next->next = newOp;
    }
    else
    {
      delete splitOp->next;
      delete splitOp;
    }
  }
References Clipper2Lib::Area(), Clipper2Lib::AreaTriangle(), Clipper2Lib::GetIntersectPoint(), Clipper2Lib::OutRec::idx, Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::outrec, Clipper2Lib::ClipperBase::outrec_list_, Clipper2Lib::OutRec::owner, Clipper2Lib::OutRec::polypath, Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, Clipper2Lib::OutRec::pts, Clipper2Lib::ClipperBase::SafeDeleteOutPtJoiners(), and Clipper2Lib::ClipperBase::SafeDisposeOutPts().
Referenced by Clipper2Lib::ClipperBase::FixSelfIntersects().
DoTopOfScanbeam()
void Clipper2Lib::ClipperBase::DoTopOfScanbeam (const int64_t top_y) private inherited
  {
    sel_ = nullptr;  // sel_ is reused to flag horizontals (see PushHorz below)
    Active* e = actives_;
    while (e)
    {
      //nb: 'e' will never be horizontal here
      if (e->top.y == y)
      {
        e->curr_x = e->top.x;
        if (IsMaxima(*e))
        {
          e = DoMaxima(*e);  // TOP OF BOUND (MAXIMA)
          continue;
        }
        else
        {
          //INTERMEDIATE VERTEX ...
          if (IsHotEdge(*e)) AddOutPt(*e, e->top);
          UpdateEdgeIntoAEL(e);
          if (IsHorizontal(*e))
            PushHorz(*e);  // horizontals are processed later
        }
      }
      else // i.e. not the top of the edge
        e->curr_x = TopX(*e, y);
      e = e->next_in_ael;
    }
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::Active::curr_x, Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::IsHorizontal(), Clipper2Lib::IsHotEdge(), Clipper2Lib::IsMaxima(), Clipper2Lib::Active::next_in_ael, Clipper2Lib::ClipperBase::PushHorz(), Clipper2Lib::ClipperBase::sel_, Clipper2Lib::Active::top, Clipper2Lib::TopX(), Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
Execute() [1/4]
bool Clipper2Lib::ClipperD::Execute (ClipType clip_type, FillRule fill_rule, PathsD & closed_paths) inline
    {
      PathsD dummy;
      return Execute(clip_type, fill_rule, closed_paths, dummy);
    }
References Execute().
Referenced by Clipper2Lib::BooleanOp(), Clipper2Lib::BooleanOp(), Execute(), Execute(), and Clipper2Lib::Union().
Execute() [2/4]
bool Clipper2Lib::ClipperD::Execute (ClipType clip_type, FillRule fill_rule, PathsD & closed_paths, PathsD & open_paths) inline
    {
#ifdef USINGZ
      CheckCallback();
#endif
      if (ExecuteInternal(clip_type, fill_rule, false))
      {
        BuildPathsD(closed_paths, &open_paths);
      }
      CleanUp();
      return succeeded_;
    }
References BuildPathsD(), Clipper2Lib::ClipperBase::CleanUp(), Clipper2Lib::ClipperBase::ExecuteInternal(), and Clipper2Lib::ClipperBase::succeeded_.
Execute() [3/4]
bool Clipper2Lib::ClipperD::Execute (ClipType clip_type, FillRule fill_rule, PolyTreeD & polytree) inline
    {
      PathsD dummy;
      return Execute(clip_type, fill_rule, polytree, dummy);
    }
References Execute().
Execute() [4/4]
bool Clipper2Lib::ClipperD::Execute (ClipType clip_type, FillRule fill_rule, PolyTreeD & polytree, PathsD & open_paths) inline
    {
#ifdef USINGZ
      CheckCallback();
#endif
      if (ExecuteInternal(clip_type, fill_rule, true))
      {
        polytree.Clear();
        polytree.SetInvScale(invScale_);
        open_paths.clear();
        BuildTreeD(polytree, open_paths);
      }
      CleanUp();
      return succeeded_;
    }
References BuildTreeD(), Clipper2Lib::ClipperBase::CleanUp(), Clipper2Lib::PolyPathD::Clear(), Clipper2Lib::ClipperBase::ExecuteInternal(), invScale_, Clipper2Lib::PolyPathD::SetInvScale(), and Clipper2Lib::ClipperBase::succeeded_.
ExecuteInternal()
bool Clipper2Lib::ClipperBase::ExecuteInternal (ClipType ct, FillRule ft, bool use_polytrees) protected inherited
  {
    cliptype_ = ct;
    fillrule_ = fillrule;
    using_polytree_ = use_polytrees;
    Reset();
    int64_t y;
    if (ct == ClipType::None || !PopScanline(y)) return true;
    while (succeeded_)
    {
      InsertLocalMinimaIntoAEL(y);
      Active* e;
      while (PopHorz(e)) DoHorizontal(*e);
      if (horz_joiners_) ConvertHorzTrialsToJoins();
      bot_y_ = y;  // bot_y_ == bottom of scanbeam
      if (!PopScanline(y)) break;  // y new top of scanbeam
      DoIntersections(y);
      DoTopOfScanbeam(y);
      while (PopHorz(e)) DoHorizontal(*e);
    }
    ProcessJoinerList();
    return succeeded_;
  }
References Clipper2Lib::ClipperBase::bot_y_, Clipper2Lib::ClipperBase::cliptype_, Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins(), Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoIntersections(), Clipper2Lib::ClipperBase::DoTopOfScanbeam(), Clipper2Lib::ClipperBase::fillrule_, Clipper2Lib::ClipperBase::horz_joiners_, Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), Clipper2Lib::None, Clipper2Lib::ClipperBase::PopHorz(), Clipper2Lib::ClipperBase::PopScanline(), Clipper2Lib::ClipperBase::ProcessJoinerList(), Clipper2Lib::ClipperBase::Reset(), Clipper2Lib::ClipperBase::succeeded_, and Clipper2Lib::ClipperBase::using_polytree_.
Referenced by Clipper2Lib::Clipper64::Execute(), Execute(), Clipper2Lib::Clipper64::Execute(), and Execute().
FixSelfIntersects()
void Clipper2Lib::ClipperBase::FixSelfIntersects (OutRec * outrec) private inherited
  {
    OutPt* op2 = outrec->pts;
    for (; ; )
    {
      // triangles can't self-intersect
      if (op2->prev == op2->next->next) break;
      if (SegmentsIntersect(op2->prev->pt,
        op2->pt, op2->next->pt, op2->next->next->pt))
      {
        if (op2 == outrec->pts || op2->next == outrec->pts)
          outrec->pts = outrec->pts->prev;
        DoSplitOp(outrec, op2);
        if (!outrec->pts) break;
        op2 = outrec->pts;
        continue;
      }
      else
        op2 = op2->next;
      if (op2 == outrec->pts) break;
    }
  }
References Clipper2Lib::ClipperBase::DoSplitOp(), Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, Clipper2Lib::OutRec::pts, and Clipper2Lib::SegmentsIntersect().
Referenced by Clipper2Lib::ClipperBase::CleanCollinear().
GetHorzTrialParent()
Joiner * Clipper2Lib::ClipperBase::GetHorzTrialParent (const OutPt * op) private inherited
  {
    Joiner* joiner = op->joiner;
    while (joiner)
    {
      if (joiner->op1 == op)
      {
        if (joiner->next1 && joiner->next1->idx < 0) return joiner;
        else joiner = joiner->next1;
      }
      else
      {
        if (joiner->next2 && joiner->next2->idx < 0) return joiner;
        else joiner = joiner->next1;
      }
    }
    return joiner;
  }
References Clipper2Lib::Joiner::idx, Clipper2Lib::OutPt::joiner, Clipper2Lib::Joiner::next1, Clipper2Lib::Joiner::next2, and Clipper2Lib::Joiner::op1.
Referenced by Clipper2Lib::ClipperBase::OutPtInTrialHorzList().
InsertLeftEdge()
void Clipper2Lib::ClipperBase::InsertLeftEdge (Active & e) private inherited
  {
    Active* e2;
    if (!actives_)
    {
      e.prev_in_ael = nullptr;
      e.next_in_ael = nullptr;
      actives_ = &e;
    }
    else if (!IsValidAelOrder(*actives_, e))
    {
      e.prev_in_ael = nullptr;
      e.next_in_ael = actives_;
      actives_->prev_in_ael = &e;
      actives_ = &e;
    }
    else
    {
      e2 = actives_;
      while (e2->next_in_ael && IsValidAelOrder(*e2->next_in_ael, e))
        e2 = e2->next_in_ael;
      e.next_in_ael = e2->next_in_ael;
      if (e2->next_in_ael) e2->next_in_ael->prev_in_ael = &e;
      e.prev_in_ael = e2;
      e2->next_in_ael = &e;
    }
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::IsValidAelOrder(), Clipper2Lib::Active::next_in_ael, and Clipper2Lib::Active::prev_in_ael.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
InsertLocalMinimaIntoAEL()
void Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL (int64_t bot_y) private inherited
  {
    LocalMinima* local_minima;
    Active* left_bound, * right_bound;
    //Add any local minima (if any) at BotY ...
    //nb: horizontal local minima edges should contain locMin.vertex.prev
    while (PopLocalMinima(bot_y, local_minima))
    {
      if ((local_minima->vertex->flags & VertexFlags::OpenStart) != VertexFlags::None)
      {
        left_bound = nullptr;
      }
      else
      {
        left_bound = new Active();
        left_bound->bot = local_minima->vertex->pt;
        left_bound->curr_x = left_bound->bot.x;
        left_bound->wind_cnt = 0,
        left_bound->wind_cnt2 = 0,
        left_bound->wind_dx = -1,
        left_bound->vertex_top = local_minima->vertex->prev;  // ie descending
        left_bound->top = left_bound->vertex_top->pt;
        left_bound->outrec = nullptr;
        left_bound->local_min = local_minima;
        SetDx(*left_bound);
      }
      if ((local_minima->vertex->flags & VertexFlags::OpenEnd) != VertexFlags::None)
      {
        right_bound = nullptr;
      }
      else
      {
        right_bound = new Active();
        right_bound->bot = local_minima->vertex->pt;
        right_bound->curr_x = right_bound->bot.x;
        right_bound->wind_cnt = 0,
        right_bound->wind_cnt2 = 0,
        right_bound->wind_dx = 1,
        right_bound->vertex_top = local_minima->vertex->next;  // ie ascending
        right_bound->top = right_bound->vertex_top->pt;
        right_bound->outrec = nullptr;
        right_bound->local_min = local_minima;
        SetDx(*right_bound);
      }
      //Currently LeftB is just the descending bound and RightB is the ascending.
      //Now if the LeftB isn't on the left of RightB then we need swap them.
      if (left_bound && right_bound)
      {
        if (IsHorizontal(*left_bound))
        {
          if (IsHeadingRightHorz(*left_bound)) SwapActives(left_bound, right_bound);
        }
        else if (IsHorizontal(*right_bound))
        {
          if (IsHeadingLeftHorz(*right_bound)) SwapActives(left_bound, right_bound);
        }
        else if (left_bound->dx < right_bound->dx)
          SwapActives(left_bound, right_bound);
      }
      else if (!left_bound)
      {
        left_bound = right_bound;
        right_bound = nullptr;
      }
      bool contributing;
      left_bound->is_left_bound = true;
      InsertLeftEdge(*left_bound);
      if (IsOpen(*left_bound))
      {
        SetWindCountForOpenPathEdge(*left_bound);
        contributing = IsContributingOpen(*left_bound);
      }
      else
      {
        SetWindCountForClosedPathEdge(*left_bound);
        contributing = IsContributingClosed(*left_bound);
      }
      if (right_bound)
      {
        right_bound->is_left_bound = false;
        right_bound->wind_cnt = left_bound->wind_cnt;
        right_bound->wind_cnt2 = left_bound->wind_cnt2;
        InsertRightEdge(*left_bound, *right_bound);
        if (contributing)
        {
          AddLocalMinPoly(*left_bound, *right_bound, left_bound->bot, true);
          if (!IsHorizontal(*left_bound) && TestJoinWithPrev1(*left_bound))
          {
            OutPt* op = AddOutPt(*left_bound->prev_in_ael, left_bound->bot);
            AddJoin(op, left_bound->outrec->pts);
          }
        }
        while (right_bound->next_in_ael &&
          IsValidAelOrder(*right_bound->next_in_ael, *right_bound))
        {
          IntersectEdges(*right_bound, *right_bound->next_in_ael, right_bound->bot);
          SwapPositionsInAEL(*right_bound, *right_bound->next_in_ael);
        }
        if (!IsHorizontal(*right_bound) &&
          TestJoinWithNext1(*right_bound))
        {
          OutPt* op = AddOutPt(*right_bound->next_in_ael, right_bound->bot);
          AddJoin(right_bound->outrec->pts, op);
        }
        if (IsHorizontal(*right_bound))
          PushHorz(*right_bound);
        else
          InsertScanline(right_bound->top.y);
      }
      else if (contributing)
      {
        StartOpenPath(*left_bound, left_bound->bot);
      }
      if (IsHorizontal(*left_bound))
        PushHorz(*left_bound);
      else
        InsertScanline(left_bound->top.y);
    }  // while (PopLocalMinima())
  }
References Clipper2Lib::ClipperBase::AddJoin(), Clipper2Lib::ClipperBase::AddLocalMinPoly(), Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::Active::bot, Clipper2Lib::Active::curr_x, Clipper2Lib::Active::dx, Clipper2Lib::Vertex::flags, Clipper2Lib::ClipperBase::InsertLeftEdge(), Clipper2Lib::InsertRightEdge(), Clipper2Lib::ClipperBase::InsertScanline(), Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::Active::is_left_bound, Clipper2Lib::ClipperBase::IsContributingClosed(), Clipper2Lib::ClipperBase::IsContributingOpen(), Clipper2Lib::IsHeadingLeftHorz(), Clipper2Lib::IsHeadingRightHorz(), Clipper2Lib::IsHorizontal(), Clipper2Lib::IsOpen(), Clipper2Lib::IsValidAelOrder(), Clipper2Lib::Active::local_min, Clipper2Lib::Vertex::next, Clipper2Lib::Active::next_in_ael, Clipper2Lib::None, Clipper2Lib::OpenEnd, Clipper2Lib::OpenStart, Clipper2Lib::Active::outrec, Clipper2Lib::ClipperBase::PopLocalMinima(), Clipper2Lib::Vertex::prev, Clipper2Lib::Active::prev_in_ael, Clipper2Lib::Vertex::pt, Clipper2Lib::OutRec::pts, Clipper2Lib::ClipperBase::PushHorz(), Clipper2Lib::SetDx(), Clipper2Lib::ClipperBase::SetWindCountForClosedPathEdge(), Clipper2Lib::ClipperBase::SetWindCountForOpenPathEdge(), Clipper2Lib::ClipperBase::StartOpenPath(), Clipper2Lib::SwapActives(), Clipper2Lib::ClipperBase::SwapPositionsInAEL(), Clipper2Lib::TestJoinWithNext1(), Clipper2Lib::TestJoinWithPrev1(), Clipper2Lib::Active::top, Clipper2Lib::LocalMinima::vertex, Clipper2Lib::Active::vertex_top, Clipper2Lib::Active::wind_cnt, Clipper2Lib::Active::wind_cnt2, Clipper2Lib::Active::wind_dx, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
InsertScanline()
void Clipper2Lib::ClipperBase::InsertScanline (int64_t y) inline private inherited
  {
    scanline_list_.push(y);
  }
References Clipper2Lib::ClipperBase::scanline_list_.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), Clipper2Lib::ClipperBase::Reset(), and Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL().
IntersectEdges()
OutPt * Clipper2Lib::ClipperBase::IntersectEdges (Active & e1, Active & e2, const Point64 & pt) private inherited
  {
    //MANAGE OPEN PATH INTERSECTIONS SEPARATELY ...
    if (has_open_paths_ && (IsOpen(e1) || IsOpen(e2)))
    {
      if (IsOpen(e1) && IsOpen(e2)) return nullptr;
      Active* edge_o, * edge_c;
      if (IsOpen(e1))
      {
        edge_o = &e1;
        edge_c = &e2;
      }
      else
      {
        edge_o = &e2;
        edge_c = &e1;
      }
      if (abs(edge_c->wind_cnt) != 1) return nullptr;
      switch (cliptype_)
      {
      case ClipType::Union:
        if (!IsHotEdge(*edge_c)) return nullptr;
        break;
      default:
        if (edge_c->local_min->polytype == PathType::Subject)
          return nullptr;
      }
      switch (fillrule_)
      {
      case FillRule::Positive: if (edge_c->wind_cnt != 1) return nullptr; break;
      case FillRule::Negative: if (edge_c->wind_cnt != -1) return nullptr; break;
      default: if (std::abs(edge_c->wind_cnt) != 1) return nullptr; break;
      }
      //toggle contribution ...
      if (IsHotEdge(*edge_o))
      {
        OutPt* resultOp = AddOutPt(*edge_o, pt);
#ifdef USINGZ
        if (zCallback_) SetZ(e1, e2, resultOp->pt);
#endif
        if (IsFront(*edge_o)) edge_o->outrec->front_edge = nullptr;
        else edge_o->outrec->back_edge = nullptr;
        edge_o->outrec = nullptr;
        return resultOp;
      }
      //horizontal edges can pass under open paths at a LocMins
      else if (pt == edge_o->local_min->vertex->pt &&
        !IsOpenEnd(*edge_o->local_min->vertex))
      {
        //find the other side of the LocMin and
        //if it's 'hot' join up with it ...
        Active* e3 = FindEdgeWithMatchingLocMin(edge_o);
        if (e3 && IsHotEdge(*e3))
        {
          edge_o->outrec = e3->outrec;
          if (edge_o->wind_dx > 0)
            SetSides(*e3->outrec, *edge_o, *e3);
          else
            SetSides(*e3->outrec, *e3, *edge_o);
          return e3->outrec->pts;
        }
        else
          return StartOpenPath(*edge_o, pt);
      }
      else
        return StartOpenPath(*edge_o, pt);
    }
    //MANAGING CLOSED PATHS FROM HERE ON
    //UPDATE WINDING COUNTS...
    int old_e1_windcnt, old_e2_windcnt;
    if (e1.local_min->polytype == e2.local_min->polytype)
    {
      if (fillrule_ == FillRule::EvenOdd)
      {
        old_e1_windcnt = e1.wind_cnt;
        e1.wind_cnt = e2.wind_cnt;
        e2.wind_cnt = old_e1_windcnt;
      }
      else
      {
        if (e1.wind_cnt + e2.wind_dx == 0)
          e1.wind_cnt = -e1.wind_cnt;
        else
          e1.wind_cnt += e2.wind_dx;
        if (e2.wind_cnt - e1.wind_dx == 0)
          e2.wind_cnt = -e2.wind_cnt;
        else
          e2.wind_cnt -= e1.wind_dx;
      }
    }
    else
    {
      if (fillrule_ != FillRule::EvenOdd)
      {
        e1.wind_cnt2 += e2.wind_dx;
        e2.wind_cnt2 -= e1.wind_dx;
      }
      else
      {
        e1.wind_cnt2 = (e1.wind_cnt2 == 0 ? 1 : 0);
        e2.wind_cnt2 = (e2.wind_cnt2 == 0 ? 1 : 0);
      }
    }
    switch (fillrule_)
    {
    case FillRule::EvenOdd:
    case FillRule::NonZero:
      old_e1_windcnt = abs(e1.wind_cnt);
      old_e2_windcnt = abs(e2.wind_cnt);
      break;
    default:
      if (fillrule_ == fillpos)
      {
        old_e1_windcnt = e1.wind_cnt;
        old_e2_windcnt = e2.wind_cnt;
      }
      else
      {
        old_e1_windcnt = -e1.wind_cnt;
        old_e2_windcnt = -e2.wind_cnt;
      }
      break;
    }
    const bool e1_windcnt_in_01 = old_e1_windcnt == 0 || old_e1_windcnt == 1;
    const bool e2_windcnt_in_01 = old_e2_windcnt == 0 || old_e2_windcnt == 1;
    if ((!IsHotEdge(e1) && !e1_windcnt_in_01) || (!IsHotEdge(e2) && !e2_windcnt_in_01))
    {
      return nullptr;
    }
    //NOW PROCESS THE INTERSECTION ...
    OutPt* resultOp = nullptr;
    //if both edges are 'hot' ...
    if (IsHotEdge(e1) && IsHotEdge(e2))
    {
      if ((old_e1_windcnt != 0 && old_e1_windcnt != 1) || (old_e2_windcnt != 0 && old_e2_windcnt != 1) ||
        (e1.local_min->polytype != e2.local_min->polytype && cliptype_ != ClipType::Xor))
      {
        resultOp = AddLocalMaxPoly(e1, e2, pt);
#ifdef USINGZ
        if (zCallback_ && resultOp) SetZ(e1, e2, resultOp->pt);
#endif
      }
      else if (IsFront(e1) || (e1.outrec == e2.outrec))
      {
        //this 'else if' condition isn't strictly needed but
        //it's sensible to split polygons that ony touch at
        //a common vertex (not at common edges).
        resultOp = AddLocalMaxPoly(e1, e2, pt);
        OutPt* op2 = AddLocalMinPoly(e1, e2, pt);
#ifdef USINGZ
        if (zCallback_ && resultOp) SetZ(e1, e2, resultOp->pt);
        if (zCallback_) SetZ(e1, e2, op2->pt);
#endif
        if (resultOp && resultOp->pt == op2->pt &&
          !IsHorizontal(e1) && !IsHorizontal(e2) &&
          (CrossProduct(e1.bot, resultOp->pt, e2.bot) == 0))
          AddJoin(resultOp, op2);
      }
      else
      {
        resultOp = AddOutPt(e1, pt);
#ifdef USINGZ
        OutPt* op2 = AddOutPt(e2, pt);
        if (zCallback_)
        {
          SetZ(e1, e2, resultOp->pt);
          SetZ(e1, e2, op2->pt);
        }
#else
        AddOutPt(e2, pt);
#endif
        SwapOutrecs(e1, e2);
      }
    }
    else if (IsHotEdge(e1))
    {
      resultOp = AddOutPt(e1, pt);
#ifdef USINGZ
      if (zCallback_) SetZ(e1, e2, resultOp->pt);
#endif
      SwapOutrecs(e1, e2);
    }
    else if (IsHotEdge(e2))
    {
      resultOp = AddOutPt(e2, pt);
#ifdef USINGZ
      if (zCallback_) SetZ(e1, e2, resultOp->pt);
#endif
      SwapOutrecs(e1, e2);
    }
    else
    {
      int64_t e1Wc2, e2Wc2;
      switch (fillrule_)
      {
      case FillRule::EvenOdd:
      case FillRule::NonZero:
        e1Wc2 = abs(e1.wind_cnt2);
        e2Wc2 = abs(e2.wind_cnt2);
        break;
      default:
        if (fillrule_ == fillpos)
        {
          e1Wc2 = e1.wind_cnt2;
          e2Wc2 = e2.wind_cnt2;
        }
        else
        {
          e1Wc2 = -e1.wind_cnt2;
          e2Wc2 = -e2.wind_cnt2;
        }
        break;
      }
      if (!IsSamePolyType(e1, e2))
      {
        resultOp = AddLocalMinPoly(e1, e2, pt, false);
#ifdef USINGZ
        if (zCallback_) SetZ(e1, e2, resultOp->pt);
#endif
      }
      else if (old_e1_windcnt == 1 && old_e2_windcnt == 1)
      {
        resultOp = nullptr;
        switch (cliptype_)
        {
        case ClipType::Union:
          if (e1Wc2 <= 0 && e2Wc2 <= 0)
            resultOp = AddLocalMinPoly(e1, e2, pt, false);
          break;
        case ClipType::Difference:
          if (((GetPolyType(e1) == PathType::Clip) && (e1Wc2 > 0) && (e2Wc2 > 0)) ||
            ((GetPolyType(e1) == PathType::Subject) && (e1Wc2 <= 0) && (e2Wc2 <= 0)))
          {
            resultOp = AddLocalMinPoly(e1, e2, pt, false);
          }
          break;
        case ClipType::Xor:
          resultOp = AddLocalMinPoly(e1, e2, pt, false);
          break;
        default:
          if (e1Wc2 > 0 && e2Wc2 > 0)
            resultOp = AddLocalMinPoly(e1, e2, pt, false);
          break;
        }
#ifdef USINGZ
        if (resultOp && zCallback_) SetZ(e1, e2, resultOp->pt);
#endif
      }
    }
    return resultOp;
  }
References Clipper2Lib::ClipperBase::AddJoin(), Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::AddLocalMinPoly(), Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::OutRec::back_edge, Clipper2Lib::Active::bot, Clipper2Lib::Clip, Clipper2Lib::ClipperBase::cliptype_, Clipper2Lib::CrossProduct(), Clipper2Lib::Difference, Clipper2Lib::EvenOdd, Clipper2Lib::ClipperBase::fillpos, Clipper2Lib::ClipperBase::fillrule_, Clipper2Lib::FindEdgeWithMatchingLocMin(), Clipper2Lib::OutRec::front_edge, Clipper2Lib::GetPolyType(), Clipper2Lib::ClipperBase::has_open_paths_, Clipper2Lib::IsFront(), Clipper2Lib::IsHorizontal(), Clipper2Lib::IsHotEdge(), Clipper2Lib::IsOpen(), Clipper2Lib::IsOpenEnd(), Clipper2Lib::IsSamePolyType(), Clipper2Lib::Active::local_min, Clipper2Lib::Negative, Clipper2Lib::NonZero, Clipper2Lib::Active::outrec, Clipper2Lib::LocalMinima::polytype, Clipper2Lib::Positive, Clipper2Lib::Vertex::pt, Clipper2Lib::OutPt::pt, Clipper2Lib::OutRec::pts, Clipper2Lib::SetSides(), Clipper2Lib::ClipperBase::StartOpenPath(), Clipper2Lib::Subject, Clipper2Lib::SwapOutrecs(), Clipper2Lib::Union, Clipper2Lib::LocalMinima::vertex, Clipper2Lib::Active::wind_cnt, Clipper2Lib::Active::wind_cnt2, Clipper2Lib::Active::wind_dx, and Clipper2Lib::Xor.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), and Clipper2Lib::ClipperBase::ProcessIntersectList().
IsContributingClosed()
bool Clipper2Lib::ClipperBase::IsContributingClosed (const Active & e) const private inherited
  {
    switch (fillrule_)
    {
    case FillRule::EvenOdd:
      break;
    case FillRule::NonZero:
      if (abs(e.wind_cnt) != 1) return false;
      break;
    case FillRule::Positive:
      if (e.wind_cnt != 1) return false;
      break;
    case FillRule::Negative:
      if (e.wind_cnt != -1) return false;
      break;
    }
    switch (cliptype_)
    {
    case ClipType::None:
      return false;
    case ClipType::Intersection:
      switch (fillrule_)
      {
      case FillRule::Positive:
        return (e.wind_cnt2 > 0);
      case FillRule::Negative:
        return (e.wind_cnt2 < 0);
      default:
        return (e.wind_cnt2 != 0);
      }
      break;
    case ClipType::Union:
      switch (fillrule_)
      {
      case FillRule::Positive:
        return (e.wind_cnt2 <= 0);
      case FillRule::Negative:
        return (e.wind_cnt2 >= 0);
      default:
        return (e.wind_cnt2 == 0);
      }
      break;
    case ClipType::Difference:
      bool result;
      switch (fillrule_)
      {
      case FillRule::Positive:
        result = (e.wind_cnt2 <= 0);
        break;
      case FillRule::Negative:
        result = (e.wind_cnt2 >= 0);
        break;
      default:
        result = (e.wind_cnt2 == 0);
      }
      if (GetPolyType(e) == PathType::Subject)
        return result;
      else
        return !result;
      break;
    case ClipType::Xor: return true;  break;
    }
    return false;  // we should never get here
  }
References Clipper2Lib::ClipperBase::cliptype_, Clipper2Lib::Difference, Clipper2Lib::EvenOdd, Clipper2Lib::ClipperBase::fillrule_, Clipper2Lib::GetPolyType(), Clipper2Lib::Intersection, Clipper2Lib::Negative, Clipper2Lib::None, Clipper2Lib::NonZero, Clipper2Lib::Positive, Clipper2Lib::Subject, Clipper2Lib::Union, Clipper2Lib::Active::wind_cnt, Clipper2Lib::Active::wind_cnt2, and Clipper2Lib::Xor.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
IsContributingOpen()
bool Clipper2Lib::ClipperBase::IsContributingOpen (const Active & e) const inline private inherited
  {
    bool is_in_clip, is_in_subj;
    switch (fillrule_)
    {
    case FillRule::Positive:
      is_in_clip = e.wind_cnt2 > 0;
      is_in_subj = e.wind_cnt > 0;
      break;
    case FillRule::Negative:
      is_in_clip = e.wind_cnt2 < 0;
      is_in_subj = e.wind_cnt < 0;
      break;
    default:
      is_in_clip = e.wind_cnt2 != 0;
      is_in_subj = e.wind_cnt != 0;
    }
    switch (cliptype_)
    {
    case ClipType::Intersection: return is_in_clip;
    case ClipType::Union: return (!is_in_subj && !is_in_clip);
    default: return !is_in_clip;
    }
  }
References Clipper2Lib::ClipperBase::cliptype_, Clipper2Lib::ClipperBase::fillrule_, Clipper2Lib::Intersection, Clipper2Lib::Negative, Clipper2Lib::Positive, Clipper2Lib::Union, Clipper2Lib::Active::wind_cnt, and Clipper2Lib::Active::wind_cnt2.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
JoinOutrecPaths()
void Clipper2Lib::ClipperBase::JoinOutrecPaths (Active & e1, Active & e2) private inherited
  {
    //join e2 outrec path onto e1 outrec path and then delete e2 outrec path
    //pointers. (NB Only very rarely do the joining ends share the same coords.)
    OutPt* p1_st = e1.outrec->pts;
    OutPt* p2_st = e2.outrec->pts;
    OutPt* p1_end = p1_st->next;
    OutPt* p2_end = p2_st->next;
    if (IsFront(e1))
    {
      p2_end->prev = p1_st;
      p1_st->next = p2_end;
      p2_st->next = p1_end;
      p1_end->prev = p2_st;
      e1.outrec->pts = p2_st;
      e1.outrec->front_edge = e2.outrec->front_edge;
      if (e1.outrec->front_edge)
        e1.outrec->front_edge->outrec = e1.outrec;
    }
    else
    {
      p1_end->prev = p2_st;
      p2_st->next = p1_end;
      p1_st->next = p2_end;
      p2_end->prev = p1_st;
      e1.outrec->back_edge = e2.outrec->back_edge;
      if (e1.outrec->back_edge)
        e1.outrec->back_edge->outrec = e1.outrec;
    }
    //an owner must have a lower idx otherwise
    //it can't be a valid owner
    if (e2.outrec->owner && e2.outrec->owner->idx < e1.outrec->idx)
    {
      if (!e1.outrec->owner || e2.outrec->owner->idx < e1.outrec->owner->idx)
        e1.outrec->owner = e2.outrec->owner;
    }
    //after joining, the e2.OutRec must contains no vertices ...
    e2.outrec->front_edge = nullptr;
    e2.outrec->back_edge = nullptr;
    e2.outrec->pts = nullptr;
    e2.outrec->owner = e1.outrec;
    if (IsOpenEnd(e1))
    {
      e2.outrec->pts = e1.outrec->pts;
      e1.outrec->pts = nullptr;
    }
    //and e1 and e2 are maxima and are about to be dropped from the Actives list.
    e1.outrec = nullptr;
    e2.outrec = nullptr;
  }
References Clipper2Lib::OutRec::back_edge, Clipper2Lib::OutRec::front_edge, Clipper2Lib::OutRec::idx, Clipper2Lib::IsFront(), Clipper2Lib::IsOpenEnd(), Clipper2Lib::OutPt::next, Clipper2Lib::Active::outrec, Clipper2Lib::OutRec::owner, Clipper2Lib::OutPt::prev, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly().
OutPtInTrialHorzList()
bool Clipper2Lib::ClipperBase::OutPtInTrialHorzList (OutPt * op) private inherited
  {
    return op->joiner && ((op->joiner->idx < 0) || GetHorzTrialParent(op));
  }
References Clipper2Lib::ClipperBase::GetHorzTrialParent(), Clipper2Lib::Joiner::idx, and Clipper2Lib::OutPt::joiner.
Referenced by Clipper2Lib::ClipperBase::AddTrialHorzJoin(), and Clipper2Lib::ClipperBase::SafeDeleteOutPtJoiners().
PopHorz()
bool Clipper2Lib::ClipperBase::PopHorz (Active *& e) inline private inherited
  {
    e = sel_;
    if (!e) return false;
    sel_ = sel_->next_in_sel;
    return true;
  }
References Clipper2Lib::Active::next_in_sel, and Clipper2Lib::ClipperBase::sel_.
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
PopLocalMinima()
bool Clipper2Lib::ClipperBase::PopLocalMinima (int64_t y, LocalMinima *& local_minima) private inherited
  {
    if (current_locmin_iter_ == minima_list_.end() || (*current_locmin_iter_)->vertex->pt.y != y) return false;
    local_minima = (*current_locmin_iter_++);
    return true;
  }
References Clipper2Lib::ClipperBase::current_locmin_iter_, and Clipper2Lib::ClipperBase::minima_list_.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
PopScanline()
bool Clipper2Lib::ClipperBase::PopScanline (int64_t & y) private inherited
  {
    if (scanline_list_.empty()) return false;
    y = scanline_list_.top();
    scanline_list_.pop();
    while (!scanline_list_.empty() && y == scanline_list_.top())
      scanline_list_.pop();  // Pop duplicates.
    return true;
  }
References Clipper2Lib::ClipperBase::scanline_list_.
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
ProcessIntersectList()
void Clipper2Lib::ClipperBase::ProcessIntersectList () private inherited
  {
    //We now have a list of intersections required so that edges will be
    //correctly positioned at the top of the scanbeam. However, it's important
    //that edge intersections are processed from the bottom up, but it's also
    //crucial that intersections only occur between adjacent edges.
    //First we do a quicksort so intersections proceed in a bottom up order ...
    std::sort(intersect_nodes_.begin(), intersect_nodes_.end(), IntersectListSort);
    //Now as we process these intersections, we must sometimes adjust the order
    //to ensure that intersecting edges are always adjacent ...
    std::vector<IntersectNode>::iterator node_iter, node_iter2;
    for (node_iter = intersect_nodes_.begin();
      node_iter != intersect_nodes_.end();  ++node_iter)
    {
      if (!EdgesAdjacentInAEL(*node_iter))
      {
        node_iter2 = node_iter + 1;
        while (!EdgesAdjacentInAEL(*node_iter2)) ++node_iter2;
        std::swap(*node_iter, *node_iter2);
      }
      IntersectNode& node = *node_iter;
      IntersectEdges(*node.edge1, *node.edge2, node.pt);
      SwapPositionsInAEL(*node.edge1, *node.edge2);
      if (TestJoinWithPrev2(*node.edge2, node.pt))
      {
        OutPt* op1 = AddOutPt(*node.edge2->prev_in_ael, node.pt);
        OutPt* op2 = AddOutPt(*node.edge2, node.pt);
        if (op1 != op2) AddJoin(op1, op2);
      }
      else if (TestJoinWithNext2(*node.edge1, node.pt))
      {
        OutPt* op1 = AddOutPt(*node.edge1, node.pt);
        OutPt* op2 = AddOutPt(*node.edge1->next_in_ael, node.pt);
        if (op1 != op2) AddJoin(op1, op2);
      }
    }
  }
References Clipper2Lib::ClipperBase::AddJoin(), Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::IntersectNode::edge1, Clipper2Lib::IntersectNode::edge2, Clipper2Lib::EdgesAdjacentInAEL(), Clipper2Lib::ClipperBase::intersect_nodes_, Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::IntersectListSort(), Clipper2Lib::Active::next_in_ael, Clipper2Lib::Active::prev_in_ael, Clipper2Lib::IntersectNode::pt, Clipper2Lib::ClipperBase::SwapPositionsInAEL(), Clipper2Lib::TestJoinWithNext2(), and Clipper2Lib::TestJoinWithPrev2().
Referenced by Clipper2Lib::ClipperBase::DoIntersections().
ProcessJoin()
OutRec * Clipper2Lib::ClipperBase::ProcessJoin (Joiner * joiner) private inherited
  {
    OutPt* op1 = joiner->op1, * op2 = joiner->op2;
    OutRec* or1 = GetRealOutRec(op1->outrec);
    OutRec* or2 = GetRealOutRec(op2->outrec);
    DeleteJoin(joiner);
    if (or2->pts == nullptr) return or1;
    else if (!IsValidClosedPath(op2))
    {
      SafeDisposeOutPts(op2);
      return or1;
    }
    else if ((or1->pts == nullptr) || !IsValidClosedPath(op1))
    {
      SafeDisposeOutPts(op1);
      return or2;
    }
    else if (or1 == or2 &&
      ((op1 == op2) || (op1->next == op2) || (op1->prev == op2))) return or1;
    CheckDisposeAdjacent(op1, op2, *or1);
    CheckDisposeAdjacent(op2, op1, *or2);
    if (op1->next == op2 || op2->next == op1) return or1;
    OutRec* result = or1;
    for (; ; )
    {
      if (!IsValidPath(op1) || !IsValidPath(op2) ||
        (or1 == or2 && (op1->prev == op2 || op1->next == op2))) return or1;
      if (op1->prev->pt == op2->next->pt ||
        ((CrossProduct(op1->prev->pt, op1->pt, op2->next->pt) == 0) &&
          CollinearSegsOverlap(op1->prev->pt, op1->pt, op2->pt, op2->next->pt)))
      {
        if (or1 == or2)
        {
          //SPLIT REQUIRED
          //make sure op1.prev and op2.next match positions
          //by inserting an extra vertex if needed
          if (op1->prev->pt != op2->next->pt)
          {
            if (PointEqualOrBetween(op1->prev->pt, op2->pt, op2->next->pt))
              op2->next = InsertOp(op1->prev->pt, op2);
            else
              op1->prev = InsertOp(op2->next->pt, op1->prev);
          }
          //current              to     new
          //op1.p[opA] >>> op1   ...    opA \   / op1
          //op2.n[opB] <<< op2   ...    opB /   \ op2
          OutPt* opA = op1->prev, * opB = op2->next;
          opA->next = opB;
          opB->prev = opA;
          op1->prev = op2;
          op2->next = op1;
          CompleteSplit(op1, opA, *or1);
        }
        else
        {
          //JOIN, NOT SPLIT
          OutPt* opA = op1->prev, * opB = op2->next;
          opA->next = opB;
          opB->prev = opA;
          op1->prev = op2;
          op2->next = op1;
          //SafeDeleteOutPtJoiners(op2);
          //DisposeOutPt(op2);
          if (or1->idx < or2->idx)
          {
            or1->pts = op1;
            or2->pts = nullptr;
            if (or1->owner && (!or2->owner ||
              or2->owner->idx < or1->owner->idx))
                or1->owner = or2->owner;
            or2->owner = or1;
          }
          else
          {
            result = or2;
            or2->pts = op1;
            or1->pts = nullptr;
            if (or2->owner && (!or1->owner ||
              or1->owner->idx < or2->owner->idx))
                or2->owner = or1->owner;
            or1->owner = or2;
          }
        }
        break;
      }
      else if (op1->next->pt == op2->prev->pt ||
        ((CrossProduct(op1->next->pt, op2->pt, op2->prev->pt) == 0) &&
          CollinearSegsOverlap(op1->next->pt, op1->pt, op2->pt, op2->prev->pt)))
      {
        if (or1 == or2)
        {
          //SPLIT REQUIRED
          //make sure op2.prev and op1.next match positions
          //by inserting an extra vertex if needed
          if (op2->prev->pt != op1->next->pt)
          {
            if (PointEqualOrBetween(op2->prev->pt, op1->pt, op1->next->pt))
              op1->next = InsertOp(op2->prev->pt, op1);
            else
              op2->prev = InsertOp(op1->next->pt, op2->prev);
          }
          //current              to     new
          //op2.p[opA] >>> op2   ...    opA \   / op2
          //op1.n[opB] <<< op1   ...    opB /   \ op1
          OutPt* opA = op2->prev, * opB = op1->next;
          opA->next = opB;
          opB->prev = opA;
          op2->prev = op1;
          op1->next = op2;
          CompleteSplit(op1, opA, *or1);
        }
        else
        {
          //JOIN, NOT SPLIT
          OutPt* opA = op1->next, * opB = op2->prev;
          opA->prev = opB;
          opB->next = opA;
          op1->next = op2;
          op2->prev = op1;
          //SafeDeleteOutPtJoiners(op2);
          //DisposeOutPt(op2);
          if (or1->idx < or2->idx)
          {
            or1->pts = op1;
            or2->pts = nullptr;
            if (or1->owner && (!or2->owner ||
              or2->owner->idx < or1->owner->idx))
                or1->owner = or2->owner;
            or2->owner = or1;
          }
          else
          {
            result = or2;
            or2->pts = op1;
            or1->pts = nullptr;
            if (or2->owner && (!or1->owner ||
              or1->owner->idx < or2->owner->idx))
                or2->owner = or1->owner;
            or1->owner = or2;
          }
        }
        break;
      }
      else if (PointBetween(op1->next->pt, op2->pt, op2->prev->pt) &&
        DistanceFromLineSqrd(op1->next->pt, op2->pt, op2->prev->pt) < 2.01)
      {
        InsertOp(op1->next->pt, op2->prev);
        continue;
      }
      else if (PointBetween(op2->next->pt, op1->pt, op1->prev->pt) &&
        DistanceFromLineSqrd(op2->next->pt, op1->pt, op1->prev->pt) < 2.01)
      {
        InsertOp(op2->next->pt, op1->prev);
        continue;
      }
      else if (PointBetween(op1->prev->pt, op2->pt, op2->next->pt) &&
        DistanceFromLineSqrd(op1->prev->pt, op2->pt, op2->next->pt) < 2.01)
      {
        InsertOp(op1->prev->pt, op2);
        continue;
      }
      else if (PointBetween(op2->prev->pt, op1->pt, op1->next->pt) &&
        DistanceFromLineSqrd(op2->prev->pt, op1->pt, op1->next->pt) < 2.01)
      {
        InsertOp(op2->prev->pt, op1);
        continue;
      }
      //something odd needs tidying up
      if (CheckDisposeAdjacent(op1, op2, *or1)) continue;
      else if (CheckDisposeAdjacent(op2, op1, *or1)) continue;
      else if (op1->prev->pt != op2->next->pt &&
        (DistanceSqr(op1->prev->pt, op2->next->pt) < 2.01))
      {
        op1->prev->pt = op2->next->pt;
        continue;
      }
      else if (op1->next->pt != op2->prev->pt &&
        (DistanceSqr(op1->next->pt, op2->prev->pt) < 2.01))
      {
        op2->prev->pt = op1->next->pt;
        continue;
      }
      else
      {
        //OK, there doesn't seem to be a way to join after all
        //so just tidy up the polygons
        or1->pts = op1;
        if (or2 != or1)
        {
          or2->pts = op2;
          CleanCollinear(or2);
        }
        break;
      }
    }
    return result;
  }
References Clipper2Lib::CheckDisposeAdjacent(), Clipper2Lib::ClipperBase::CleanCollinear(), Clipper2Lib::CollinearSegsOverlap(), Clipper2Lib::ClipperBase::CompleteSplit(), Clipper2Lib::CrossProduct(), Clipper2Lib::ClipperBase::DeleteJoin(), Clipper2Lib::DistanceFromLineSqrd(), Clipper2Lib::DistanceSqr(), Clipper2Lib::GetRealOutRec(), Clipper2Lib::OutRec::idx, Clipper2Lib::InsertOp(), Clipper2Lib::IsValidClosedPath(), Clipper2Lib::IsValidPath(), Clipper2Lib::OutPt::next, Clipper2Lib::Joiner::op1, Clipper2Lib::Joiner::op2, Clipper2Lib::OutPt::outrec, Clipper2Lib::OutRec::owner, Clipper2Lib::PointBetween(), Clipper2Lib::PointEqualOrBetween(), Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, Clipper2Lib::OutRec::pts, and Clipper2Lib::ClipperBase::SafeDisposeOutPts().
Referenced by Clipper2Lib::ClipperBase::ProcessJoinerList().
ProcessJoinerList()
void Clipper2Lib::ClipperBase::ProcessJoinerList () private inherited
  {
    for (Joiner* j : joiner_list_)
    {
      if (!j) continue;
      if (succeeded_)
      {
        OutRec* outrec = ProcessJoin(j);
        CleanCollinear(outrec);
      }
      else
        delete j;
    }
    joiner_list_.resize(0);
  }
References Clipper2Lib::ClipperBase::CleanCollinear(), Clipper2Lib::ClipperBase::joiner_list_, Clipper2Lib::ClipperBase::ProcessJoin(), and Clipper2Lib::ClipperBase::succeeded_.
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
PushHorz()
void Clipper2Lib::ClipperBase::PushHorz (Active & e) inline private inherited
  {
    e.next_in_sel = (sel_ ? sel_ : nullptr);
    sel_ = &e;
  }
References Clipper2Lib::Active::next_in_sel, and Clipper2Lib::ClipperBase::sel_.
Referenced by Clipper2Lib::ClipperBase::DoTopOfScanbeam(), and Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
Reset()
void Clipper2Lib::ClipperBase::Reset () private inherited
  {
    if (!minima_list_sorted_)
    {
      std::sort(minima_list_.begin(), minima_list_.end(), LocMinSorter());
      minima_list_sorted_ = true;
    }
    std::vector<LocalMinima*>::const_reverse_iterator i;
    for (i = minima_list_.rbegin(); i != minima_list_.rend(); ++i)
      InsertScanline((*i)->vertex->pt.y);
    current_locmin_iter_ = minima_list_.begin();
    actives_ = nullptr;
    sel_ = nullptr;
    succeeded_ = true;
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::ClipperBase::current_locmin_iter_, Clipper2Lib::ClipperBase::InsertScanline(), Clipper2Lib::ClipperBase::minima_list_, Clipper2Lib::ClipperBase::minima_list_sorted_, Clipper2Lib::ClipperBase::sel_, and Clipper2Lib::ClipperBase::succeeded_.
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal().
ResetHorzDirection()
bool Clipper2Lib::ClipperBase::ResetHorzDirection (const Active & horz, const Active * max_pair, int64_t & horz_left, int64_t & horz_right) private inherited
  {
    if (horz.bot.x == horz.top.x)
    {
      //the horizontal edge is going nowhere ...
      horz_left = horz.curr_x;
      horz_right = horz.curr_x;
      Active* e = horz.next_in_ael;
      while (e && e != max_pair) e = e->next_in_ael;
      return e != nullptr;
    }
    else if (horz.curr_x < horz.top.x)
    {
      horz_left = horz.curr_x;
      horz_right = horz.top.x;
      return true;
    }
    else
    {
      horz_left = horz.top.x;
      horz_right = horz.curr_x;
      return false;  // right to left
    }
  }
References Clipper2Lib::Active::bot, Clipper2Lib::Active::curr_x, Clipper2Lib::Active::next_in_ael, Clipper2Lib::Active::top, and Clipper2Lib::Point< T >::x.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal().
SafeDeleteOutPtJoiners()
void Clipper2Lib::ClipperBase::SafeDeleteOutPtJoiners (OutPt * op) private inherited
  {
    Joiner* joiner = op->joiner;
    if (!joiner) return;
    while (joiner)
    {
      if (joiner->idx < 0)
        DeleteTrialHorzJoin(op);
      else if (horz_joiners_)
      {
        if (OutPtInTrialHorzList(joiner->op1))
          DeleteTrialHorzJoin(joiner->op1);
        if (OutPtInTrialHorzList(joiner->op2))
          DeleteTrialHorzJoin(joiner->op2);
        DeleteJoin(joiner);
      }
      else
        DeleteJoin(joiner);
      joiner = op->joiner;
    }
  }
References Clipper2Lib::ClipperBase::DeleteJoin(), Clipper2Lib::ClipperBase::DeleteTrialHorzJoin(), Clipper2Lib::ClipperBase::horz_joiners_, Clipper2Lib::Joiner::idx, Clipper2Lib::OutPt::joiner, Clipper2Lib::Joiner::op1, Clipper2Lib::Joiner::op2, and Clipper2Lib::ClipperBase::OutPtInTrialHorzList().
Referenced by Clipper2Lib::ClipperBase::DoSplitOp(), and Clipper2Lib::ClipperBase::SafeDisposeOutPts().
SafeDisposeOutPts()
void Clipper2Lib::ClipperBase::SafeDisposeOutPts (OutPt *& op) private inherited
  {
    OutRec* outrec = GetRealOutRec(op->outrec);
    if (outrec->front_edge)
      outrec->front_edge->outrec = nullptr;
    if (outrec->back_edge)
      outrec->back_edge->outrec = nullptr;
    op->prev->next = nullptr;
    while (op)
    {
      SafeDeleteOutPtJoiners(op);
      OutPt* tmp = op->next;
      delete op;
      op = tmp;
    }
    outrec->pts = nullptr;
  }
References Clipper2Lib::OutRec::back_edge, Clipper2Lib::OutRec::front_edge, Clipper2Lib::GetRealOutRec(), Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::outrec, Clipper2Lib::Active::outrec, Clipper2Lib::OutPt::prev, Clipper2Lib::OutRec::pts, and Clipper2Lib::ClipperBase::SafeDeleteOutPtJoiners().
Referenced by Clipper2Lib::ClipperBase::CompleteSplit(), Clipper2Lib::ClipperBase::DoSplitOp(), Clipper2Lib::ClipperBase::ProcessJoin(), and Clipper2Lib::ClipperBase::ValidateClosedPathEx().
SetWindCountForClosedPathEdge()
void Clipper2Lib::ClipperBase::SetWindCountForClosedPathEdge (Active & edge) private inherited
  {
    //Wind counts refer to polygon regions not edges, so here an edge's WindCnt
    //indicates the higher of the wind counts for the two regions touching the
    //edge. (NB Adjacent regions can only ever have their wind counts differ by
    //one. Also, open paths have no meaningful wind directions or counts.)
    Active* e2 = e.prev_in_ael;
    //find the nearest closed path edge of the same PolyType in AEL (heading left)
    PathType pt = GetPolyType(e);
    while (e2 && (GetPolyType(*e2) != pt || IsOpen(*e2))) e2 = e2->prev_in_ael;
    if (!e2)
    {
      e.wind_cnt = e.wind_dx;
      e2 = actives_;
    }
    else if (fillrule_ == FillRule::EvenOdd)
    {
      e.wind_cnt = e.wind_dx;
      e.wind_cnt2 = e2->wind_cnt2;
      e2 = e2->next_in_ael;
    }
    else
    {
      //NonZero, positive, or negative filling here ...
      //if e's WindCnt is in the SAME direction as its WindDx, then polygon
      //filling will be on the right of 'e'.
      //NB neither e2.WindCnt nor e2.WindDx should ever be 0.
      if (e2->wind_cnt * e2->wind_dx < 0)
      {
        //opposite directions so 'e' is outside 'e2' ...
        if (abs(e2->wind_cnt) > 1)
        {
          //outside prev poly but still inside another.
          if (e2->wind_dx * e.wind_dx < 0)
            //reversing direction so use the same WC
            e.wind_cnt = e2->wind_cnt;
          else
            //otherwise keep 'reducing' the WC by 1 (ie towards 0) ...
            e.wind_cnt = e2->wind_cnt + e.wind_dx;
        }
        else
          //now outside all polys of same polytype so set own WC ...
          e.wind_cnt = (IsOpen(e) ? 1 : e.wind_dx);
      }
      else
      {
        //'e' must be inside 'e2'
        if (e2->wind_dx * e.wind_dx < 0)
          //reversing direction so use the same WC
          e.wind_cnt = e2->wind_cnt;
        else
          //otherwise keep 'increasing' the WC by 1 (ie away from 0) ...
          e.wind_cnt = e2->wind_cnt + e.wind_dx;
      }
      e.wind_cnt2 = e2->wind_cnt2;
      e2 = e2->next_in_ael;  // ie get ready to calc WindCnt2
    }
    //update wind_cnt2 ...
    if (fillrule_ == FillRule::EvenOdd)
      while (e2 != &e)
      {
        if (GetPolyType(*e2) != pt && !IsOpen(*e2))
          e.wind_cnt2 = (e.wind_cnt2 == 0 ? 1 : 0);
        e2 = e2->next_in_ael;
      }
    else
      while (e2 != &e)
      {
        if (GetPolyType(*e2) != pt && !IsOpen(*e2))
          e.wind_cnt2 += e2->wind_dx;
        e2 = e2->next_in_ael;
      }
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::EvenOdd, Clipper2Lib::ClipperBase::fillrule_, Clipper2Lib::GetPolyType(), Clipper2Lib::IsOpen(), Clipper2Lib::Active::next_in_ael, Clipper2Lib::Active::prev_in_ael, Clipper2Lib::Active::wind_cnt, Clipper2Lib::Active::wind_cnt2, and Clipper2Lib::Active::wind_dx.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
SetWindCountForOpenPathEdge()
void Clipper2Lib::ClipperBase::SetWindCountForOpenPathEdge (Active & e) private inherited
  {
    Active* e2 = actives_;
    if (fillrule_ == FillRule::EvenOdd)
    {
      int cnt1 = 0, cnt2 = 0;
      while (e2 != &e)
      {
        if (GetPolyType(*e2) == PathType::Clip)
          cnt2++;
        else if (!IsOpen(*e2))
          cnt1++;
        e2 = e2->next_in_ael;
      }
      e.wind_cnt = (IsOdd(cnt1) ? 1 : 0);
      e.wind_cnt2 = (IsOdd(cnt2) ? 1 : 0);
    }
    else
    {
      while (e2 != &e)
      {
        if (GetPolyType(*e2) == PathType::Clip)
          e.wind_cnt2 += e2->wind_dx;
        else if (!IsOpen(*e2))
          e.wind_cnt += e2->wind_dx;
        e2 = e2->next_in_ael;
      }
    }
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::Clip, Clipper2Lib::EvenOdd, Clipper2Lib::ClipperBase::fillrule_, Clipper2Lib::GetPolyType(), Clipper2Lib::IsOdd(), Clipper2Lib::IsOpen(), Clipper2Lib::Active::next_in_ael, Clipper2Lib::Active::wind_cnt, Clipper2Lib::Active::wind_cnt2, and Clipper2Lib::Active::wind_dx.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
StartOpenPath()
OutPt * Clipper2Lib::ClipperBase::StartOpenPath (Active & e, const Point64 & pt) inline private inherited
  {
    OutRec* outrec = new OutRec();
    outrec->idx = outrec_list_.size();
    outrec_list_.push_back(outrec);
    outrec->owner = nullptr;
    outrec->is_open = true;
    outrec->pts = nullptr;
    outrec->polypath = nullptr;
    if (e.wind_dx > 0)
    {
      outrec->front_edge = &e;
      outrec->back_edge = nullptr;
    }
    else
    {
      outrec->front_edge = nullptr;
      outrec->back_edge =& e;
    }
    e.outrec = outrec;
    OutPt* op = new OutPt(pt, outrec);
    outrec->pts = op;
    return op;
  }
References Clipper2Lib::OutRec::back_edge, Clipper2Lib::OutRec::front_edge, Clipper2Lib::OutRec::idx, Clipper2Lib::OutRec::is_open, Clipper2Lib::Active::outrec, Clipper2Lib::ClipperBase::outrec_list_, Clipper2Lib::OutRec::owner, Clipper2Lib::OutRec::polypath, Clipper2Lib::OutRec::pts, and Clipper2Lib::Active::wind_dx.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), and Clipper2Lib::ClipperBase::IntersectEdges().
SwapPositionsInAEL()
void Clipper2Lib::ClipperBase::SwapPositionsInAEL (Active & edge1, Active & edge2) private inherited
  {
    //preconditon: e1 must be immediately to the left of e2
    Active* next = e2.next_in_ael;
    if (next) next->prev_in_ael = &e1;
    Active* prev = e1.prev_in_ael;
    if (prev) prev->next_in_ael = &e2;
    e2.prev_in_ael = prev;
    e2.next_in_ael = &e1;
    e1.prev_in_ael = &e2;
    e1.next_in_ael = next;
    if (!e2.prev_in_ael) actives_ = &e2;
  }
References Clipper2Lib::ClipperBase::actives_, Clipper2Lib::Active::next_in_ael, and Clipper2Lib::Active::prev_in_ael.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), and Clipper2Lib::ClipperBase::ProcessIntersectList().
UpdateEdgeIntoAEL()
void Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL (Active * e) inline private inherited
  {
    e->bot = e->top;
    e->vertex_top = NextVertex(*e);
    e->top = e->vertex_top->pt;
    e->curr_x = e->bot.x;
    SetDx(*e);
    if (IsHorizontal(*e)) return;
    InsertScanline(e->top.y);
    if (TestJoinWithPrev1(*e))
    {
      OutPt* op1 = AddOutPt(*e->prev_in_ael, e->bot);
      OutPt* op2 = AddOutPt(*e, e->bot);
      AddJoin(op1, op2);
    }
  }
References Clipper2Lib::ClipperBase::AddJoin(), Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::Active::bot, Clipper2Lib::Active::curr_x, Clipper2Lib::ClipperBase::InsertScanline(), Clipper2Lib::IsHorizontal(), Clipper2Lib::NextVertex(), Clipper2Lib::Active::prev_in_ael, Clipper2Lib::Vertex::pt, Clipper2Lib::SetDx(), Clipper2Lib::TestJoinWithPrev1(), Clipper2Lib::Active::top, Clipper2Lib::Active::vertex_top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), and Clipper2Lib::ClipperBase::DoTopOfScanbeam().
ValidateClosedPathEx()
bool Clipper2Lib::ClipperBase::ValidateClosedPathEx (OutPt *& outrec) private inherited
  {
    if (IsValidClosedPath(outpt)) return true;
    if (outpt) SafeDisposeOutPts(outpt);
    return false;
  }
References Clipper2Lib::IsValidClosedPath(), and Clipper2Lib::ClipperBase::SafeDisposeOutPts().
Referenced by Clipper2Lib::ClipperBase::CleanCollinear().
Member Data Documentation
actives_
Active* Clipper2Lib::ClipperBase::actives_ = nullptr private inherited
Referenced by Clipper2Lib::ClipperBase::AdjustCurrXAndCopyToSEL(), Clipper2Lib::ClipperBase::BuildIntersectList(), Clipper2Lib::ClipperBase::CleanUp(), Clipper2Lib::ClipperBase::DeleteFromAEL(), Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::ClipperBase::DoTopOfScanbeam(), Clipper2Lib::ClipperBase::InsertLeftEdge(), Clipper2Lib::ClipperBase::Reset(), Clipper2Lib::ClipperBase::SetWindCountForClosedPathEdge(), Clipper2Lib::ClipperBase::SetWindCountForOpenPathEdge(), and Clipper2Lib::ClipperBase::SwapPositionsInAEL().
bot_y_
int64_t Clipper2Lib::ClipperBase::bot_y_ = 0 private inherited
Referenced by Clipper2Lib::ClipperBase::AddNewIntersectNode(), and Clipper2Lib::ClipperBase::ExecuteInternal().
cliptype_
ClipType Clipper2Lib::ClipperBase::cliptype_ = ClipType::None private inherited
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal(), Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::ClipperBase::IsContributingClosed(), and Clipper2Lib::ClipperBase::IsContributingOpen().
current_locmin_iter_
std::vector<LocalMinima*>::iterator Clipper2Lib::ClipperBase::current_locmin_iter_ private inherited
Referenced by Clipper2Lib::ClipperBase::Clear(), Clipper2Lib::ClipperBase::PopLocalMinima(), and Clipper2Lib::ClipperBase::Reset().
fillpos
FillRule Clipper2Lib::ClipperBase::fillpos = FillRule::Positive private inherited
Referenced by Clipper2Lib::ClipperBase::IntersectEdges().
fillrule_
FillRule Clipper2Lib::ClipperBase::fillrule_ = FillRule::EvenOdd private inherited
Referenced by Clipper2Lib::ClipperBase::ExecuteInternal(), Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::ClipperBase::IsContributingClosed(), Clipper2Lib::ClipperBase::IsContributingOpen(), Clipper2Lib::ClipperBase::SetWindCountForClosedPathEdge(), and Clipper2Lib::ClipperBase::SetWindCountForOpenPathEdge().
has_open_paths_
bool Clipper2Lib::ClipperBase::has_open_paths_ = false protected inherited
Referenced by Clipper2Lib::ClipperBase::AddPaths(), Clipper2Lib::Clipper64::BuildTree64(), BuildTreeD(), Clipper2Lib::ClipperBase::Clear(), and Clipper2Lib::ClipperBase::IntersectEdges().
horz_joiners_
Joiner* Clipper2Lib::ClipperBase::horz_joiners_ = nullptr private inherited
Referenced by Clipper2Lib::ClipperBase::AddTrialHorzJoin(), Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins(), Clipper2Lib::ClipperBase::DeleteTrialHorzJoin(), Clipper2Lib::ClipperBase::ExecuteInternal(), and Clipper2Lib::ClipperBase::SafeDeleteOutPtJoiners().
intersect_nodes_
std::vector<IntersectNode> Clipper2Lib::ClipperBase::intersect_nodes_ private inherited
Referenced by Clipper2Lib::ClipperBase::AddNewIntersectNode(), Clipper2Lib::ClipperBase::BuildIntersectList(), Clipper2Lib::ClipperBase::CleanUp(), Clipper2Lib::ClipperBase::DoIntersections(), and Clipper2Lib::ClipperBase::ProcessIntersectList().
invScale_
double Clipper2Lib::ClipperD::invScale_ = 1.0 private
Referenced by ClipperD(), BuildPathsD(), BuildTreeD(), and Execute().
joiner_list_
std::vector<Joiner*> Clipper2Lib::ClipperBase::joiner_list_ private inherited
Referenced by Clipper2Lib::ClipperBase::AddJoin(), Clipper2Lib::ClipperBase::DeleteJoin(), and Clipper2Lib::ClipperBase::ProcessJoinerList().
minima_list_
std::vector<LocalMinima*> Clipper2Lib::ClipperBase::minima_list_ private inherited
Referenced by Clipper2Lib::ClipperBase::AddLocMin(), Clipper2Lib::ClipperBase::Clear(), Clipper2Lib::ClipperBase::DisposeVerticesAndLocalMinima(), Clipper2Lib::ClipperBase::PopLocalMinima(), and Clipper2Lib::ClipperBase::Reset().
minima_list_sorted_
bool Clipper2Lib::ClipperBase::minima_list_sorted_ = false private inherited
Referenced by Clipper2Lib::ClipperBase::AddPaths(), Clipper2Lib::ClipperBase::Clear(), and Clipper2Lib::ClipperBase::Reset().
outrec_list_
std::vector<OutRec*> Clipper2Lib::ClipperBase::outrec_list_ protected inherited
Referenced by Clipper2Lib::ClipperBase::AddLocalMinPoly(), Clipper2Lib::Clipper64::BuildPaths64(), BuildPathsD(), Clipper2Lib::Clipper64::BuildTree64(), BuildTreeD(), Clipper2Lib::ClipperBase::CompleteSplit(), Clipper2Lib::ClipperBase::DisposeAllOutRecs(), Clipper2Lib::ClipperBase::DoSplitOp(), and Clipper2Lib::ClipperBase::StartOpenPath().
PreserveCollinear
bool Clipper2Lib::ClipperBase::PreserveCollinear = true inherited
Referenced by Clipper2Lib::BooleanOp64(), Clipper2Lib::BooleanOpD(), Clipper2Lib::BooleanOpPt64(), Clipper2Lib::BooleanOpPtD(), Clipper2Lib::ClipperBase::CleanCollinear(), and Clipper2Lib::ClipperBase::DoHorizontal().
ReverseSolution
bool Clipper2Lib::ClipperBase::ReverseSolution = false inherited
Referenced by Clipper2Lib::BooleanOp64(), Clipper2Lib::BooleanOpD(), Clipper2Lib::BooleanOpPt64(), Clipper2Lib::BooleanOpPtD(), Clipper2Lib::Clipper64::BuildPaths64(), BuildPathsD(), Clipper2Lib::Clipper64::BuildTree64(), BuildTreeD(), and Clipper2Lib::ClipperBase::DeepCheckOwner().
scale_
double Clipper2Lib::ClipperD::scale_ = 1.0 private
Referenced by ClipperD(), AddClip(), AddOpenSubject(), and AddSubject().
scanline_list_
std::priority_queue<int64_t> Clipper2Lib::ClipperBase::scanline_list_ private inherited
Referenced by Clipper2Lib::ClipperBase::CleanUp(), Clipper2Lib::ClipperBase::InsertScanline(), and Clipper2Lib::ClipperBase::PopScanline().
sel_
Active* Clipper2Lib::ClipperBase::sel_ = nullptr private inherited
Referenced by Clipper2Lib::ClipperBase::AdjustCurrXAndCopyToSEL(), Clipper2Lib::ClipperBase::BuildIntersectList(), Clipper2Lib::ClipperBase::DoTopOfScanbeam(), Clipper2Lib::ClipperBase::PopHorz(), Clipper2Lib::ClipperBase::PushHorz(), and Clipper2Lib::ClipperBase::Reset().
succeeded_
bool Clipper2Lib::ClipperBase::succeeded_ = true protected inherited
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::Clipper64::Execute(), Execute(), Clipper2Lib::Clipper64::Execute(), Execute(), Clipper2Lib::ClipperBase::ExecuteInternal(), Clipper2Lib::ClipperBase::ProcessJoinerList(), and Clipper2Lib::ClipperBase::Reset().
using_polytree_
bool Clipper2Lib::ClipperBase::using_polytree_ = false private inherited
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::CompleteSplit(), and Clipper2Lib::ClipperBase::ExecuteInternal().
vertex_lists_
std::vector<Vertex*> Clipper2Lib::ClipperBase::vertex_lists_ private inherited
Referenced by Clipper2Lib::ClipperBase::AddPaths(), and Clipper2Lib::ClipperBase::DisposeVerticesAndLocalMinima().
The documentation for this class was generated from the following files:
src/clipper2/Clipper2Lib/include/clipper2/clipper.engine.h
src/clipper2/Clipper2Lib/src/clipper.engine.cpp