OrcaSlicer: cdt::detail Namespace Reference
cdt::detail Namespace Reference
hidapi API
Namespaces
namespace defaults
Functions
template<typename T >
std::array< T, 3 > arr3 (const T &v0, const T &v1, const T &v2)
Needed for c++03 compatibility (no uniform initialization available)
template<typename T , typename Allocator1 >
void insert_unique (std::vector< T, Allocator1 > &to, const T &elem)
template<typename T , typename Allocator1 , typename Allocator2 >
void insert_unique (std::vector< T, Allocator1 > &to, const std::vector< T, Allocator2 > &from)
static std::mt19937 randGenerator (9001)
template<class RandomIt >
void random_shuffle (RandomIt first, RandomIt last)
template<typename T >
T lerp (const T &a, const T &b, const T t)
template<typename T >
vec2_< T > get_intersection_point_coords (const vec2_< T > &a, const vec2_< T > &b, const vec2_< T > &c, const vec2_< T > &d)
Function Documentation
arr3()
template<typename T > std::array< T, 3 > cdt::detail::arr3 (const T & v0, const T & v1, const T & v2)
Needed for c++03 compatibility (no uniform initialization available)
    {
        const std::array<T, 3> out = { v0, v1, v2 };
        return out;
    }
References out.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::do_edgeflip(), cdt::triangulator_t< T, TNearPointLocator >::insert_point_in_triangle(), and cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge().
get_intersection_point_coords()
template<typename T > vec2_< T > cdt::detail::get_intersection_point_coords (const vec2_< T > & a, const vec2_< T > & b, const vec2_< T > & c, const vec2_< T > & d)
    {
        // interpolate point on the shorter segment
        if (get_square_distance(a, b) < get_square_distance(c, d)) {
            // const T a_cd = orient2d(c.x(), c.y(), d.x(), d.y(), a.x(), a.y());
            // const T b_cd = orient2d(c.x(), c.y(), d.x(), d.y(), b.x(), b.y());
            const T a_cd = orient2d(c, d, a);
            const T b_cd = orient2d(c, d, b);
            const T t = a_cd / (a_cd - b_cd);
            return vec2_<T>::make(lerp(a.x(), b.x(), t), lerp(a.y(), b.y(), t));
        } else {
            // const T c_ab = orient2d(a.x(), a.y(), b.x(), b.y(), c.x(), c.y());
            // const T d_ab = orient2d(a.x(), a.y(), b.x(), b.y(), d.x(), d.y());
            const T c_ab = orient2d(a, b, c);
            const T d_ab = orient2d(a, b, d);
            const T t = c_ab / (c_ab - d_ab);
            return vec2_<T>::make(lerp(c.x(), d.x(), t), lerp(c.y(), d.y(), t));
        }
    }
References cdt::get_square_distance(), lerp(), vec2_< T >::make(), and orient2d().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), and cdt::triangulator_t< T, TNearPointLocator >::insert_edge().
insert_unique() [1/2]
template<typename T , typename Allocator1 , typename Allocator2 > void cdt::detail::insert_unique (std::vector< T, Allocator1 > & to, const std::vector< T, Allocator2 > & from)
    {
        typedef typename std::vector<T, Allocator2>::const_iterator Cit;
        to.reserve(to.size() + from.size());
        for (Cit cit = from.begin(); cit != from.end(); ++cit) {
            insert_unique(to, *cit);
        }
    }
References insert_unique().
insert_unique() [2/2]
template<typename T , typename Allocator1 > void cdt::detail::insert_unique (std::vector< T, Allocator1 > & to, const T & elem)
    {
        if (std::find(to.begin(), to.end(), elem) == to.end()) {
            to.push_back(elem);
        }
    }
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), cdt::triangulator_t< T, TNearPointLocator >::fixEdge(), cdt::triangulator_t< T, TNearPointLocator >::insert_edge(), and insert_unique().
lerp()
template<typename T > T cdt::detail::lerp (const T & a, const T & b, const T t)
    {
        return (T(1) - t) * a + t * b;
    }
Referenced by get_intersection_point_coords().
randGenerator()
static std::mt19937 cdt::detail::randGenerator (9001) static
Referenced by cdt::triangulator_t< T, TNearPointLocator >::insert_vertices(), random_shuffle(), and cdt::triangulator_t< T, TNearPointLocator >::walk_triangles().
random_shuffle()
template<class RandomIt > void cdt::detail::random_shuffle (RandomIt first, RandomIt last)
    {
        typename std::iterator_traits<RandomIt>::difference_type i, n;
        n = last - first;
        for (i = n - 1; i > 0; --i) {
            std::swap(first[i], first[randGenerator() % (i + 1)]);
        }
    }
References n, and randGenerator().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::insert_vertices().