OrcaSlicer: Slic3r::csg::detail_mcut Namespace Reference
Slic3r::csg::detail_mcut Namespace Reference
Functions
void perform_csg (CSGType op, McutMeshPtr &dst, McutMeshPtr &src)
template<class Ex , class It >
std::vector< McutMeshPtr > get_mcutptrs (Ex policy, const Range< It > &csgrange)
Function Documentation
get_mcutptrs()
template<class Ex , class It > std::vector< McutMeshPtr > Slic3r::csg::detail_mcut::get_mcutptrs (Ex policy, const Range< It > & csgrange)
    {
        std::vector<McutMeshPtr> ret(csgrange.size());
        execution::for_each(policy, size_t(0), csgrange.size(),
            [&csgrange, &ret](size_t i) {
                auto it = csgrange.begin();
                std::advance(it, i);
                auto& csgpart = *it;
                ret[i] = get_mcutmesh(csgpart);
            });
        return ret;
    }
References Slic3r::execution::for_each(), and Slic3r::Range< It >::size().
perform_csg()
void Slic3r::csg::detail_mcut::perform_csg (CSGType op, McutMeshPtr & dst, McutMeshPtr & src) inline
    {
        if (!dst && op == CSGType::Union && src) {
            dst = std::move(src);
            return;
        }
        if (!dst || !src)
            return;
        switch (op) {
        case CSGType::Union:
            MeshBoolean::mcut::do_boolean(*dst, *src,"UNION");
            break;
        case CSGType::Difference:
            MeshBoolean::mcut::do_boolean(*dst, *src,"A_NOT_B");
            break;
        case CSGType::Intersection:
            MeshBoolean::mcut::do_boolean(*dst, *src,"INTERSECTION");
            break;
        }
    }
References Slic3r::csg::Difference, Slic3r::MeshBoolean::mcut::do_boolean(), Slic3r::csg::Intersection, and Slic3r::csg::Union.