OrcaSlicer: Slic3r::GUI::CameraPopup Class Reference
Slic3r::GUI::CameraPopup Class Reference
#include <src/slic3r/GUI/CameraPopup.hpp>
Public Types
enum CameraResolution { RESOLUTION_720P = 0 , RESOLUTION_1080P = 1 , RESOLUTION_OPTIONS_NUM = 2 }
Public Member Functions
CameraPopup (wxWindow *parent, MachineObject *obj=nullptr)
virtual ~CameraPopup ()
virtual void Popup (wxWindow *focus=NULL) wxOVERRIDE
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
virtual bool Show (bool show=true) wxOVERRIDE
void sync_vcamera_state (bool show_vcamera)
void check_func_supported ()
void update (bool vcamera_streaming)
void rescale ()
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Protected Member Functions
void on_switch_recording (wxCommandEvent &event)
void on_set_resolution ()
void sdcard_absent_hint ()
wxWindow * create_item_radiobox (wxString title, wxWindow *parent, wxString tooltip, int padding_left)
void select_curr_radiobox (int btn_idx)
void sync_resolution_setting (std::string resolution)
void reset_resolution_setting ()
wxString to_resolution_label_string (CameraResolution resolution)
std::string to_resolution_msg_string (CameraResolution resolution)
Private Member Functions
void start_interval ()
void stop_interval (wxTimerEvent &event)
void OnMouse (wxMouseEvent &event)
void OnSize (wxSizeEvent &event)
void OnSetFocus (wxFocusEvent &event)
void OnKillFocus (wxFocusEvent &event)
void OnLeftUp (wxMouseEvent &event)
wxDECLARE_ABSTRACT_CLASS (CameraPopup)
wxDECLARE_EVENT_TABLE ()
Private Attributes
MachineObject * m_obj { nullptr }
wxTimer * m_interval_timer {nullptr}
bool m_is_in_interval { false }
wxStaticText * m_text_recording
SwitchButton * m_switch_recording
wxStaticText * m_text_vcamera
SwitchButton * m_switch_vcamera
wxStaticText * m_text_resolution
wxWindow * m_resolution_options [RESOLUTION_OPTIONS_NUM]
wxScrolledWindow * m_panel
wxBoxSizer * main_sizer
std::vector< RadioBox * > resolution_rbtns
std::vector< wxStaticText * > resolution_texts
CameraResolution curr_sel_resolution = RESOLUTION_1080P
Label * vcamera_guide_link { nullptr }
wxPanel * link_underline { nullptr }
bool is_vcamera_show = false
bool allow_alter_resolution = false
Detailed Description
Member Enumeration Documentation
CameraResolution
enum Slic3r::GUI::CameraPopup::CameraResolution
Enumerator
RESOLUTION_720P
RESOLUTION_1080P
RESOLUTION_OPTIONS_NUM
    {
        RESOLUTION_720P = 0,
        RESOLUTION_1080P = 1,
        RESOLUTION_OPTIONS_NUM = 2
    };
Constructor & Destructor Documentation
CameraPopup()
Slic3r::GUI::CameraPopup::CameraPopup (wxWindow * parent, MachineObject * obj = nullptr)
   : PopupWindow(parent, wxBORDER_NONE | wxPU_CONTAINS_CONTROLS),
    m_obj(obj)
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif
    m_panel = new wxScrolledWindow(this, wxID_ANY);
    m_panel->SetBackgroundColour(*wxWHITE);
    m_panel->SetMinSize(wxSize(FromDIP(180),-1));
    m_panel->Bind(wxEVT_MOTION, &CameraPopup::OnMouse, this);
    main_sizer = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer* top_sizer = new wxFlexGridSizer(0, 2, 0, FromDIP(50));
    top_sizer->AddGrowableCol(0);
    top_sizer->SetFlexibleDirection(wxBOTH);
    top_sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
    //recording
    m_text_recording = new wxStaticText(m_panel, wxID_ANY, _L("Auto-record Monitoring"));
    m_text_recording->Wrap(-1);
    m_text_recording->SetFont(Label::Head_14);
    m_text_recording->SetForegroundColour(TEXT_COL);
    m_switch_recording = new SwitchButton(m_panel);
    if (obj)
        m_switch_recording->SetValue(obj->camera_recording_when_printing);
    //vcamera
    m_text_vcamera = new wxStaticText(m_panel, wxID_ANY, _L("Go Live"));
    m_text_vcamera->Wrap(-1);
    m_text_vcamera->SetFont(Label::Head_14);
    m_text_vcamera->SetForegroundColour(TEXT_COL);
    m_switch_vcamera = new SwitchButton(m_panel);
    top_sizer->Add(m_text_recording, 0, wxALIGN_CENTER_VERTICAL | wxALIGN_LEFT | wxALL, FromDIP(5));
    top_sizer->Add(m_switch_recording, 0, wxALIGN_CENTER_VERTICAL | wxALIGN_RIGHT | wxALL, FromDIP(5));
    top_sizer->Add(m_text_vcamera, 0, wxALIGN_CENTER_VERTICAL | wxALIGN_LEFT | wxALL, FromDIP(5));
    top_sizer->Add(m_switch_vcamera, 0, wxALIGN_CENTER_VERTICAL | wxALIGN_RIGHT | wxALL, FromDIP(5));
    //resolution
    m_text_resolution = new wxStaticText(m_panel, wxID_ANY, _L("Resolution"));
    m_text_resolution->Wrap(-1);
    m_text_resolution->SetFont(Label::Head_14);
    m_text_resolution->SetForegroundColour(TEXT_COL);
    top_sizer->Add(m_text_resolution, 0, wxALIGN_CENTER_VERTICAL | wxALIGN_LEFT | wxALL, FromDIP(5));
    top_sizer->Add(0, 0, wxALL, 0);
    for (int i = 0; i < (int)RESOLUTION_OPTIONS_NUM; ++i)
    {
        m_resolution_options[i] = create_item_radiobox(to_resolution_label_string(CameraResolution(i)), m_panel, wxEmptyString, FromDIP(10));
        top_sizer->Add(m_resolution_options[i], 0, wxALIGN_CENTER_VERTICAL | wxALIGN_LEFT | wxALL, FromDIP(5));
        top_sizer->Add(0, 0, wxALL, 0);
    }
    if (obj)
        sync_resolution_setting(obj->camera_resolution);
    main_sizer->Add(top_sizer, 0, wxALL, FromDIP(10));
    auto url = wxString::Format(L"https://wiki.bambulab.com/%s/software/bambu-studio/virtual-camera", L"en");
    auto text = _L("Show \"Live Video\" guide page.");
    wxBoxSizer* link_sizer = new wxBoxSizer(wxVERTICAL);
    vcamera_guide_link = new Label(m_panel, text);
    vcamera_guide_link->Wrap(-1);
    vcamera_guide_link->SetForegroundColour(wxColour(0x1F, 0x8E, 0xEA));
    auto text_size = vcamera_guide_link->GetTextExtent(text);
    vcamera_guide_link->Bind(wxEVT_LEFT_DOWN, [this, url](wxMouseEvent& e) {wxLaunchDefaultBrowser(url); });
    link_underline = new wxPanel(m_panel, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    link_underline->SetBackgroundColour(wxColour(0x1F, 0x8E, 0xEA));
    link_underline->SetSize(wxSize(text_size.x, 1));
    link_underline->SetMinSize(wxSize(text_size.x, 1));
    vcamera_guide_link->Hide();
    link_underline->Hide();
    link_sizer->Add(vcamera_guide_link, 0, wxALL, 0);
    link_sizer->Add(link_underline, 0, wxALL, 0);
    main_sizer->Add(link_sizer, 0, wxALL, FromDIP(15));
    m_panel->SetSizer(main_sizer);
    m_panel->Layout();
    main_sizer->Fit(m_panel);
    SetClientSize(m_panel->GetSize());
    m_switch_recording->Connect(wxEVT_LEFT_DOWN, wxCommandEventHandler(CameraPopup::on_switch_recording), NULL, this);
    m_switch_vcamera->Bind(wxEVT_LEFT_DOWN, [this](wxMouseEvent &e) {
        wxMouseEvent evt(EVT_VCAMERA_SWITCH);
        evt.SetEventObject(this);
        GetEventHandler()->ProcessEvent(evt);
        });
    #ifdef __APPLE__
    m_panel->Bind(wxEVT_LEFT_UP, &CameraPopup::OnLeftUp, this);
    #endif //APPLE
    this->Bind(wxEVT_TIMER, &CameraPopup::stop_interval, this);
    m_interval_timer = new wxTimer();
    m_interval_timer->SetOwner(this);
    check_func_supported();
    wxGetApp().UpdateDarkUIWin(this);
}
References _L, Slic3r::MachineObject::camera_recording_when_printing, Slic3r::MachineObject::camera_resolution, check_func_supported(), create_item_radiobox(), Label::Head_14, int, L, link_underline, m_interval_timer, m_panel, m_resolution_options, m_switch_recording, m_switch_vcamera, m_text_recording, m_text_resolution, m_text_vcamera, main_sizer, NULL, on_switch_recording(), OnLeftUp(), OnMouse(), RESOLUTION_OPTIONS_NUM, SwitchButton::SetValue(), stop_interval(), sync_resolution_setting(), Slic3r::GUI::TEXT_COL, to_resolution_label_string(), vcamera_guide_link, Label::Wrap(), Slic3r::GUI::wxMouseEvent, and wxStaticText.
~CameraPopup()
virtual Slic3r::GUI::CameraPopup::~CameraPopup () inline virtual
{}
Member Function Documentation
check_func_supported()
void Slic3r::GUI::CameraPopup::check_func_supported ()
{
    // function supported
    if (m_obj->is_function_supported(PrinterFunction::FUNC_RECORDING) && m_obj->has_ipcam) {
        m_text_recording->Show();
        m_switch_recording->Show();
    } else {
        m_text_recording->Hide();
        m_switch_recording->Hide();
    }
    if (m_obj->is_function_supported(PrinterFunction::FUNC_VIRTUAL_CAMERA) && m_obj->has_ipcam) {
        m_text_vcamera->Show();
        m_switch_vcamera->Show();
        if (is_vcamera_show) {
            vcamera_guide_link->Show();
            link_underline->Show();
        }
    } else {
        m_text_vcamera->Hide();
        m_switch_vcamera->Hide();
        vcamera_guide_link->Hide();
        link_underline->Hide();
    }
    allow_alter_resolution = (m_obj->is_function_supported(PrinterFunction::FUNC_ALTER_RESOLUTION) && m_obj->has_ipcam);
    //check u2 version
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    MachineObject* obj = dev->get_selected_machine();
    if (!obj) return;
    //resolution supported
    std::vector<std::string> resolution_supported = m_obj->get_resolution_supported();
    auto support_count = resolution_supported.size();
    for (int i = 0; i < (int)RESOLUTION_OPTIONS_NUM; ++i){
        auto curr_res = to_resolution_msg_string(CameraResolution(i));
        std::vector <std::string> ::iterator it = std::find(resolution_supported.begin(), resolution_supported.end(), curr_res);
        if ((it == resolution_supported.end())||(support_count <= 1) || !obj->is_support_1080dpi)
            m_resolution_options[i] -> Hide();
    }
    //hide resolution if there is only one choice
    if (support_count <= 1 || !obj->is_support_1080dpi) {
        m_text_resolution->Hide();
    }
}
References allow_alter_resolution, Slic3r::FUNC_ALTER_RESOLUTION, Slic3r::FUNC_RECORDING, Slic3r::FUNC_VIRTUAL_CAMERA, Slic3r::MachineObject::get_resolution_supported(), Slic3r::DeviceManager::get_selected_machine(), Slic3r::MachineObject::has_ipcam, int, Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_support_1080dpi, is_vcamera_show, link_underline, m_obj, m_resolution_options, m_switch_recording, m_switch_vcamera, m_text_recording, m_text_resolution, m_text_vcamera, RESOLUTION_OPTIONS_NUM, to_resolution_msg_string(), and vcamera_guide_link.
Referenced by CameraPopup().
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
create_item_radiobox()
wxWindow * Slic3r::GUI::CameraPopup::create_item_radiobox (wxString title, wxWindow * parent, wxString tooltip, int padding_left) protected
{
    wxWindow *item = new wxWindow(parent, wxID_ANY, wxDefaultPosition, wxSize(-1, FromDIP(20)));
    item->SetBackgroundColour(*wxWHITE);
    RadioBox *radiobox = new RadioBox(item);
    radiobox->SetPosition(wxPoint(padding_left, (item->GetSize().GetHeight() - radiobox->GetSize().GetHeight()) / 2));
    resolution_rbtns.push_back(radiobox);
    int btn_idx = resolution_rbtns.size() - 1;
    radiobox->Bind(wxEVT_LEFT_DOWN, [this, btn_idx](wxMouseEvent &e) {
        if (m_obj && allow_alter_resolution) {
            select_curr_radiobox(btn_idx);
            on_set_resolution();
        }
        });
    wxStaticText *text = new wxStaticText(item, wxID_ANY, title, wxDefaultPosition, wxDefaultSize);
    text->SetForegroundColour(*wxBLACK);
    resolution_texts.push_back(text);
    text->SetPosition(wxPoint(padding_left + radiobox->GetSize().GetWidth() + 10, (item->GetSize().GetHeight() - text->GetSize().GetHeight()) / 2));
    text->SetFont(Label::Body_13);
    text->SetForegroundColour(0x6B6B6B);
    text->Bind(wxEVT_LEFT_DOWN, [this, btn_idx](wxMouseEvent &e) {
        if (m_obj && allow_alter_resolution) {
            select_curr_radiobox(btn_idx);
            on_set_resolution();
        }
        });
    radiobox->SetToolTip(tooltip);
    text->SetToolTip(tooltip);
    return item;
}
References allow_alter_resolution, Label::Body_13, m_obj, on_set_resolution(), resolution_rbtns, resolution_texts, select_curr_radiobox(), Slic3r::GUI::wxMouseEvent, and wxStaticText.
Referenced by CameraPopup().
on_set_resolution()
void Slic3r::GUI::CameraPopup::on_set_resolution () protected
{
    if (!m_obj) return;
    m_obj->command_ipcam_resolution_set(to_resolution_msg_string(curr_sel_resolution));
}
References Slic3r::MachineObject::command_ipcam_resolution_set(), curr_sel_resolution, m_obj, and to_resolution_msg_string().
Referenced by create_item_radiobox().
on_switch_recording()
void Slic3r::GUI::CameraPopup::on_switch_recording (wxCommandEvent & event) protected
{
    if (!m_obj) return;
    if (m_obj->sdcard_state != MachineObject::SdcardState::HAS_SDCARD_NORMAL) {
        sdcard_absent_hint();
        return;
    }
    bool value = m_switch_recording->GetValue();
    m_switch_recording->SetValue(!value);
    m_obj->command_ipcam_record(!value);
}
References Slic3r::MachineObject::command_ipcam_record(), Slic3r::MachineObject::HAS_SDCARD_NORMAL, m_obj, m_switch_recording, sdcard_absent_hint(), Slic3r::MachineObject::sdcard_state, and SwitchButton::SetValue().
Referenced by CameraPopup().
OnDismiss()
void Slic3r::GUI::CameraPopup::OnDismiss () virtual
{
    PopupWindow::OnDismiss();
    this->start_interval();
}
References start_interval().
OnKillFocus()
void Slic3r::GUI::CameraPopup::OnKillFocus (wxFocusEvent & event) private
{
    event.Skip();
}
OnLeftUp()
void Slic3r::GUI::CameraPopup::OnLeftUp (wxMouseEvent & event) private
{
    auto mouse_pos = ClientToScreen(event.GetPosition());
    auto wxscroll_win_pos = m_panel->ClientToScreen(wxPoint(0, 0));
    if (mouse_pos.x > wxscroll_win_pos.x && mouse_pos.y > wxscroll_win_pos.y && mouse_pos.x < (wxscroll_win_pos.x + m_panel->GetSize().x) && mouse_pos.y < (wxscroll_win_pos.y + m_panel->GetSize().y)) {
        //recording
        auto recording_rect = m_switch_recording->ClientToScreen(wxPoint(0, 0));
        if (mouse_pos.x > recording_rect.x && mouse_pos.y > recording_rect.y && mouse_pos.x < (recording_rect.x + m_switch_recording->GetSize().x) && mouse_pos.y < (recording_rect.y + m_switch_recording->GetSize().y)) {
            wxMouseEvent recording_evt(wxEVT_LEFT_DOWN);
            m_switch_recording->GetEventHandler()->ProcessEvent(recording_evt);
            return;
        }
        //vcamera
        auto vcamera_rect = m_switch_vcamera->ClientToScreen(wxPoint(0, 0));
        if (mouse_pos.x > vcamera_rect.x && mouse_pos.y > vcamera_rect.y && mouse_pos.x < (vcamera_rect.x + m_switch_vcamera->GetSize().x) && mouse_pos.y < (vcamera_rect.y + m_switch_vcamera->GetSize().y)) {
            wxMouseEvent vcamera_evt(wxEVT_LEFT_DOWN);
            m_switch_vcamera->GetEventHandler()->ProcessEvent(vcamera_evt);
            return;
        }
        //resolution
        for (int i = 0; i < (int)RESOLUTION_OPTIONS_NUM; ++i){
            auto resolution_rbtn = resolution_rbtns[i];
            auto rbtn_rect = resolution_rbtn->ClientToScreen(wxPoint(0, 0));
            if (mouse_pos.x > rbtn_rect.x && mouse_pos.y > rbtn_rect.y && mouse_pos.x < (rbtn_rect.x + resolution_rbtn->GetSize().x) && mouse_pos.y < (rbtn_rect.y + resolution_rbtn->GetSize().y)) {
                wxMouseEvent resolution_evt(wxEVT_LEFT_DOWN);
                resolution_rbtn->GetEventHandler()->ProcessEvent(resolution_evt);
                return;
            }
            auto resolution_txt = resolution_texts[i];
            auto txt_rect = resolution_txt->ClientToScreen(wxPoint(0, 0));
            if (mouse_pos.x > txt_rect.x && mouse_pos.y > txt_rect.y && mouse_pos.x < (txt_rect.x + resolution_txt->GetSize().x) && mouse_pos.y < (txt_rect.y + resolution_txt->GetSize().y)) {
                wxMouseEvent resolution_evt(wxEVT_LEFT_DOWN);
                resolution_txt->GetEventHandler()->ProcessEvent(resolution_evt);
                return;
            }
        }
        //hyper link
        auto h_rect = vcamera_guide_link->ClientToScreen(wxPoint(0, 0));
        if (mouse_pos.x > h_rect.x && mouse_pos.y > h_rect.y && mouse_pos.x < (h_rect.x + vcamera_guide_link->GetSize().x) && mouse_pos.y < (h_rect.y + vcamera_guide_link->GetSize().y)) {
            auto url = wxString::Format(L"https://wiki.bambulab.com/%s/software/bambu-studio/virtual-camera", L"en");
            wxLaunchDefaultBrowser(url);
        }
    }
}
References int, L, m_panel, m_switch_recording, m_switch_vcamera, RESOLUTION_OPTIONS_NUM, resolution_rbtns, resolution_texts, vcamera_guide_link, and Slic3r::GUI::wxMouseEvent.
Referenced by CameraPopup().
OnMouse()
void Slic3r::GUI::CameraPopup::OnMouse (wxMouseEvent & event) private
{
    event.Skip();
}
Referenced by CameraPopup().
OnSetFocus()
void Slic3r::GUI::CameraPopup::OnSetFocus (wxFocusEvent & event) private
{
    event.Skip();
}
OnSize()
void Slic3r::GUI::CameraPopup::OnSize (wxSizeEvent & event) private
{
    event.Skip();
}
Popup()
void Slic3r::GUI::CameraPopup::Popup (wxWindow * focus = NULL) virtual
{
    wxPoint curr_position = this->GetPosition();
    wxSize win_size = this->GetSize();
    curr_position.x -= win_size.x;
    this->SetPosition(curr_position);
    if (!m_is_in_interval)
        PopupWindow::Popup();
}
References m_is_in_interval.
ProcessLeftDown()
bool Slic3r::GUI::CameraPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
rescale()
void Slic3r::GUI::CameraPopup::rescale ()
{
    m_panel->Layout();
    main_sizer->Fit(m_panel);
    SetClientSize(m_panel->GetSize());
    PopupWindow::Update();
}
References m_panel, and main_sizer.
Referenced by sync_vcamera_state(), and update().
reset_resolution_setting()
void Slic3r::GUI::CameraPopup::reset_resolution_setting () protected
{
    int len = resolution_rbtns.size();
    for (int i = 0; i < len; ++i) {
         resolution_rbtns[i]->SetValue(false);
    }
    curr_sel_resolution = RESOLUTION_OPTIONS_NUM;
}
References curr_sel_resolution, RESOLUTION_OPTIONS_NUM, and resolution_rbtns.
Referenced by sync_resolution_setting().
sdcard_absent_hint()
void Slic3r::GUI::CameraPopup::sdcard_absent_hint () protected
{
    wxCommandEvent evt(EVT_SDCARD_ABSENT_HINT);
    evt.SetEventObject(this);
    GetEventHandler()->ProcessEvent(evt);
}
Referenced by on_switch_recording().
select_curr_radiobox()
void Slic3r::GUI::CameraPopup::select_curr_radiobox (int btn_idx) protected
{
    if (!m_obj) return;
    int len = resolution_rbtns.size();
    for (int i = 0; i < len; ++i) {
        if (i == btn_idx) {
            curr_sel_resolution = CameraResolution(i);
            resolution_rbtns[i]->SetValue(true);
        }
        else {
            resolution_rbtns[i]->SetValue(false);
        }
    }
}
References curr_sel_resolution, m_obj, and resolution_rbtns.
Referenced by create_item_radiobox(), and sync_resolution_setting().
Show()
bool Slic3r::GUI::CameraPopup::Show (bool show = true) virtual
{
    return PopupWindow::Show(show);
}
start_interval()
void Slic3r::GUI::CameraPopup::start_interval () private
{
    m_interval_timer->Start(CAMERAPOPUP_CLICK_INTERVAL);
    m_is_in_interval = true;
}
References CAMERAPOPUP_CLICK_INTERVAL, m_interval_timer, and m_is_in_interval.
Referenced by OnDismiss().
stop_interval()
void Slic3r::GUI::CameraPopup::stop_interval (wxTimerEvent & event) private
{
    m_is_in_interval = false;
    m_interval_timer->Stop();
}
References m_interval_timer, and m_is_in_interval.
Referenced by CameraPopup().
sync_resolution_setting()
void Slic3r::GUI::CameraPopup::sync_resolution_setting (std::string resolution) protected
{
    if (resolution == "") {
        reset_resolution_setting();
        return;
    }
    int res = 0;
    for (CameraResolution i = RESOLUTION_720P; i < RESOLUTION_OPTIONS_NUM; i = CameraResolution(i+1)){
        if (resolution == to_resolution_msg_string(i)) {
            res = int(i);
            break;
        }
    }
    select_curr_radiobox(res);
}
References int, reset_resolution_setting(), RESOLUTION_720P, RESOLUTION_OPTIONS_NUM, select_curr_radiobox(), and to_resolution_msg_string().
Referenced by CameraPopup(), and update().
sync_vcamera_state()
void Slic3r::GUI::CameraPopup::sync_vcamera_state (bool show_vcamera)
{
    is_vcamera_show = show_vcamera;
    if (is_vcamera_show) {
        m_switch_vcamera->SetValue(true);
        vcamera_guide_link->Show();
        link_underline->Show();
    }
    else {
        m_switch_vcamera->SetValue(false);
        vcamera_guide_link->Hide();
        link_underline->Hide();
    }
    rescale();
}
References is_vcamera_show, link_underline, m_switch_vcamera, rescale(), SwitchButton::SetValue(), and vcamera_guide_link.
Referenced by update().
to_resolution_label_string()
wxString Slic3r::GUI::CameraPopup::to_resolution_label_string (CameraResolution resolution) protected
{
    switch (resolution) {
    case RESOLUTION_720P:
        return _L("720p");
    case RESOLUTION_1080P:
        return _L("1080p");
    default:
        return "";
    }
    return "";
}
References _L, RESOLUTION_1080P, and RESOLUTION_720P.
Referenced by CameraPopup().
to_resolution_msg_string()
std::string Slic3r::GUI::CameraPopup::to_resolution_msg_string (CameraResolution resolution) protected
{
    switch (resolution) {
    case RESOLUTION_720P:
        return std::string("720p");
    case RESOLUTION_1080P:
        return std::string("1080p");
    default:
        return "";
    }
    return "";
}
References RESOLUTION_1080P, and RESOLUTION_720P.
Referenced by check_func_supported(), on_set_resolution(), and sync_resolution_setting().
update()
void Slic3r::GUI::CameraPopup::update (bool vcamera_streaming)
{
    if (!m_obj) return;
    m_switch_recording->SetValue(m_obj->camera_recording_when_printing);
    sync_resolution_setting(m_obj->camera_resolution);
    sync_vcamera_state(vcamera_streaming);
    rescale();
}
References Slic3r::MachineObject::camera_recording_when_printing, Slic3r::MachineObject::camera_resolution, m_obj, m_switch_recording, rescale(), SwitchButton::SetValue(), sync_resolution_setting(), and sync_vcamera_state().
wxDECLARE_ABSTRACT_CLASS()
Slic3r::GUI::CameraPopup::wxDECLARE_ABSTRACT_CLASS (CameraPopup) private
wxDECLARE_EVENT_TABLE()
Slic3r::GUI::CameraPopup::wxDECLARE_EVENT_TABLE () private
Member Data Documentation
allow_alter_resolution
bool Slic3r::GUI::CameraPopup::allow_alter_resolution = false private
Referenced by check_func_supported(), and create_item_radiobox().
curr_sel_resolution
CameraResolution Slic3r::GUI::CameraPopup::curr_sel_resolution = RESOLUTION_1080P private
Referenced by on_set_resolution(), reset_resolution_setting(), and select_curr_radiobox().
is_vcamera_show
bool Slic3r::GUI::CameraPopup::is_vcamera_show = false private
Referenced by check_func_supported(), and sync_vcamera_state().
link_underline
wxPanel* Slic3r::GUI::CameraPopup::link_underline { nullptr } private
Referenced by CameraPopup(), check_func_supported(), and sync_vcamera_state().
m_interval_timer
wxTimer* Slic3r::GUI::CameraPopup::m_interval_timer {nullptr} private
Referenced by CameraPopup(), start_interval(), and stop_interval().
m_is_in_interval
bool Slic3r::GUI::CameraPopup::m_is_in_interval { false } private
Referenced by Popup(), start_interval(), and stop_interval().
m_obj
MachineObject* Slic3r::GUI::CameraPopup::m_obj { nullptr } private
Referenced by check_func_supported(), create_item_radiobox(), on_set_resolution(), on_switch_recording(), select_curr_radiobox(), and update().
m_panel
wxScrolledWindow* Slic3r::GUI::CameraPopup::m_panel private
Referenced by CameraPopup(), OnLeftUp(), and rescale().
m_resolution_options
wxWindow* Slic3r::GUI::CameraPopup::m_resolution_options[RESOLUTION_OPTIONS_NUM] private
Referenced by CameraPopup(), and check_func_supported().
m_switch_recording
SwitchButton* Slic3r::GUI::CameraPopup::m_switch_recording private
Referenced by CameraPopup(), check_func_supported(), on_switch_recording(), OnLeftUp(), and update().
m_switch_vcamera
SwitchButton* Slic3r::GUI::CameraPopup::m_switch_vcamera private
Referenced by CameraPopup(), check_func_supported(), OnLeftUp(), and sync_vcamera_state().
m_text_recording
wxStaticText* Slic3r::GUI::CameraPopup::m_text_recording private
Referenced by CameraPopup(), and check_func_supported().
m_text_resolution
wxStaticText* Slic3r::GUI::CameraPopup::m_text_resolution private
Referenced by CameraPopup(), and check_func_supported().
m_text_vcamera
wxStaticText* Slic3r::GUI::CameraPopup::m_text_vcamera private
Referenced by CameraPopup(), and check_func_supported().
main_sizer
wxBoxSizer* Slic3r::GUI::CameraPopup::main_sizer private
Referenced by CameraPopup(), and rescale().
resolution_rbtns
std::vector<RadioBox*> Slic3r::GUI::CameraPopup::resolution_rbtns private
Referenced by create_item_radiobox(), OnLeftUp(), reset_resolution_setting(), and select_curr_radiobox().
resolution_texts
std::vector<wxStaticText*> Slic3r::GUI::CameraPopup::resolution_texts private
Referenced by create_item_radiobox(), and OnLeftUp().
vcamera_guide_link
Label* Slic3r::GUI::CameraPopup::vcamera_guide_link { nullptr } private
Referenced by CameraPopup(), check_func_supported(), OnLeftUp(), and sync_vcamera_state().
The documentation for this class was generated from the following files:
src/slic3r/GUI/CameraPopup.hpp
src/slic3r/GUI/CameraPopup.cpp