OrcaSlicer: cereal Namespace Reference
cereal Namespace Reference
Classes
struct specialize< Archive, Slic3r::DynamicPrintConfig, cereal::specialization::non_member_load_save >
struct specialize< Archive, Slic3r::GUI::GLGizmosManager, cereal::specialization::member_load_save >
struct specialize< Archive, Slic3r::GUI::PartPlate *, cereal::specialization::non_member_load_save >
struct specialize< Archive, Slic3r::GUI::PartPlate, cereal::specialization::member_load_save >
struct specialize< Archive, Slic3r::Model *, cereal::specialization::non_member_load_save >
struct specialize< Archive, Slic3r::Model, cereal::specialization::member_load_save >
struct specialize< Archive, Slic3r::ModelConfigObject, cereal::specialization::member_serialize >
struct specialize< Archive, Slic3r::ModelInstance *, cereal::specialization::non_member_load_save >
struct specialize< Archive, Slic3r::ModelMaterial *, cereal::specialization::non_member_load_save >
struct specialize< Archive, Slic3r::ModelObject *, cereal::specialization::non_member_load_save >
struct specialize< Archive, Slic3r::ModelObject, cereal::specialization::member_load_save >
struct specialize< Archive, Slic3r::ModelVolume *, cereal::specialization::non_member_load_save >
struct specialize< Archive, Slic3r::ModelVolume, cereal::specialization::member_load_save >
struct specialize< Archive, Slic3r::TriangleMesh, cereal::specialization::non_member_load_save >
struct specialize< Archive, std::shared_ptr< Slic3r::TriangleMesh >, cereal::specialization::non_member_load_save >
Functions
template<class Archive >
void serialize (Archive &archive, Slic3r::BoundingBox &bb)
template<class Archive >
void serialize (Archive &archive, Slic3r::BoundingBox3 &bb)
template<class Archive >
void serialize (Archive &archive, Slic3r::BoundingBoxf &bb)
template<class Archive >
void serialize (Archive &archive, Slic3r::BoundingBoxf3 &bb)
template<class T >
void load_optional (BinaryInputArchive &ar, std::shared_ptr< const T > &ptr)
template<class T >
void save_optional (BinaryOutputArchive &ar, const std::shared_ptr< const T > &ptr)
template<class T >
void load_by_value (BinaryInputArchive &ar, T &obj)
template<class T >
void save_by_value (BinaryOutputArchive &ar, const T &obj)
template<class Archive >
void serialize (Archive &archive, Slic3r::Vec2i &v)
template<class Archive >
void load (Archive &archive, Slic3r::Matrix2f &m)
template<class Archive >
void save (Archive &archive, Slic3r::Matrix2f &m)
template<class Archive >
void load (Archive &archive, Slic3r::Transform3d &m)
template<class Archive >
void save (Archive &archive, const Slic3r::Transform3d &m)
template<class Archive >
void load (Archive &archive, Slic3r::DynamicPrintConfig &config)
template<class Archive >
void save (Archive &archive, const Slic3r::DynamicPrintConfig &config)
template<class Archive >
void serialize (Archive &archive, Slic3r::t_layer_height_range &lhr)
template<class Archive >
void load (Archive &archive, Slic3r::TriangleMesh &mesh)
template<class Archive >
void save (Archive &archive, const Slic3r::TriangleMesh &mesh)
template<class T >
void save (BinaryOutputArchive &ar, T *const &ptr)
template<class T >
void load (BinaryInputArchive &ar, T *&ptr)
template<class T >
void save (BinaryOutputArchive &ar, const std::unique_ptr< T > &ptr)
template<class T >
void load (BinaryInputArchive &ar, std::unique_ptr< T > &ptr)
template<class T >
void save (BinaryOutputArchive &ar, const std::shared_ptr< const T > &ptr)
template<class T >
void load (BinaryInputArchive &ar, std::shared_ptr< const T > &ptr)
Class Documentation
cereal::specialize< Archive, Slic3r::DynamicPrintConfig, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, Slic3r::DynamicPrintConfig, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::DynamicPrintConfig, cereal::specialization::non_member_load_save >
cereal::specialize< Archive, Slic3r::GUI::GLGizmosManager, cereal::specialization::member_load_save >
struct cereal::specialize< Archive, Slic3r::GUI::GLGizmosManager, cereal::specialization::member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::GUI::GLGizmosManager, cereal::specialization::member_load_save >
cereal::specialize< Archive, Slic3r::GUI::PartPlate *, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, Slic3r::GUI::PartPlate *, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::GUI::PartPlate *, cereal::specialization::non_member_load_save >
cereal::specialize< Archive, Slic3r::GUI::PartPlate, cereal::specialization::member_load_save >
struct cereal::specialize< Archive, Slic3r::GUI::PartPlate, cereal::specialization::member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::GUI::PartPlate, cereal::specialization::member_load_save >
cereal::specialize< Archive, Slic3r::Model *, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, Slic3r::Model *, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::Model *, cereal::specialization::non_member_load_save >
cereal::specialize< Archive, Slic3r::Model, cereal::specialization::member_load_save >
struct cereal::specialize< Archive, Slic3r::Model, cereal::specialization::member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::Model, cereal::specialization::member_load_save >
cereal::specialize< Archive, Slic3r::ModelConfigObject, cereal::specialization::member_serialize >
struct cereal::specialize< Archive, Slic3r::ModelConfigObject, cereal::specialization::member_serialize >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::ModelConfigObject, cereal::specialization::member_serialize >
cereal::specialize< Archive, Slic3r::ModelInstance *, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, Slic3r::ModelInstance *, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::ModelInstance *, cereal::specialization::non_member_load_save >
cereal::specialize< Archive, Slic3r::ModelMaterial *, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, Slic3r::ModelMaterial *, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::ModelMaterial *, cereal::specialization::non_member_load_save >
cereal::specialize< Archive, Slic3r::ModelObject *, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, Slic3r::ModelObject *, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::ModelObject *, cereal::specialization::non_member_load_save >
cereal::specialize< Archive, Slic3r::ModelObject, cereal::specialization::member_load_save >
struct cereal::specialize< Archive, Slic3r::ModelObject, cereal::specialization::member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::ModelObject, cereal::specialization::member_load_save >
cereal::specialize< Archive, Slic3r::ModelVolume *, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, Slic3r::ModelVolume *, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::ModelVolume *, cereal::specialization::non_member_load_save >
cereal::specialize< Archive, Slic3r::ModelVolume, cereal::specialization::member_load_save >
struct cereal::specialize< Archive, Slic3r::ModelVolume, cereal::specialization::member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::ModelVolume, cereal::specialization::member_load_save >
cereal::specialize< Archive, Slic3r::TriangleMesh, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, Slic3r::TriangleMesh, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::TriangleMesh, cereal::specialization::non_member_load_save >
cereal::specialize< Archive, std::shared_ptr< Slic3r::TriangleMesh >, cereal::specialization::non_member_load_save >
struct cereal::specialize< Archive, std::shared_ptr< Slic3r::TriangleMesh >, cereal::specialization::non_member_load_save >
template<class Archive>
struct cereal::specialize< Archive, std::shared_ptr< Slic3r::TriangleMesh >, cereal::specialization::non_member_load_save >
Function Documentation
load() [1/7]
template<class Archive > void cereal::load (Archive & archive, Slic3r::DynamicPrintConfig & config)
    {
        size_t cnt;
        archive(cnt);
        config.clear();
        for (size_t i = 0; i < cnt; ++ i) {
            size_t serialization_key_ordinal;
            archive(serialization_key_ordinal);
            assert(serialization_key_ordinal > 0);
            auto it = Slic3r::print_config_def.by_serialization_key_ordinal.find(serialization_key_ordinal);
            assert(it != Slic3r::print_config_def.by_serialization_key_ordinal.end());
            config.set_key_value(it->second->opt_key, it->second->load_option_from_archive(archive));
        }
    }
References Slic3r::ConfigDef::by_serialization_key_ordinal, Slic3r::DynamicConfig::clear(), Slic3r::print_config_def, and Slic3r::DynamicConfig::set_key_value().
load() [2/7]
template<class Archive > void cereal::load (Archive & archive, Slic3r::Matrix2f & m)
{ archive.loadBinary((char*)m.data(), sizeof(float) * 4); }
References Eigen::PlainObjectBase< Derived >::data().
load() [3/7]
template<class Archive > void cereal::load (Archive & archive, Slic3r::Transform3d & m)
{ archive.loadBinary((char *) m.data(), sizeof(double) * 16); }
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data().
load() [4/7]
template<class Archive > void cereal::load (Archive & archive, Slic3r::TriangleMesh & mesh)
{
        archive.loadBinary(reinterpret_cast<char*>(const_cast<Slic3r::TriangleMeshStats*>(&mesh.stats())), sizeof(Slic3r::TriangleMeshStats));
        archive(mesh.its.indices, mesh.its.vertices);
    }
References indexed_triangle_set::indices, Slic3r::TriangleMesh::its, Slic3r::TriangleMesh::stats(), and indexed_triangle_set::vertices.
load() [5/7]
template<class T > void cereal::load (BinaryInputArchive & ar, std::shared_ptr< const T > & ptr)
  {
    Slic3r::UndoRedo::StackImpl &stack = cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar);
    size_t id;
    ar(id);
    ptr = stack.load_immutable_object<T>(Slic3r::ObjectID(id), false);
  }
References Slic3r::UndoRedo::StackImpl::load_immutable_object(), and ptr.
load() [6/7]
template<class T > void cereal::load (BinaryInputArchive & ar, std::unique_ptr< T > & ptr)
  {
    Slic3r::UndoRedo::StackImpl& stack = cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar);
    size_t id;
    ar(id);
    ptr.reset(stack.load_mutable_object<T>(Slic3r::ObjectID(id)));
  }
References Slic3r::UndoRedo::StackImpl::load_mutable_object(), and ptr.
load() [7/7]
template<class T > void cereal::load (BinaryInputArchive & ar, T *& ptr)
  {
    Slic3r::UndoRedo::StackImpl& stack = cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar);
    size_t id;
    ar(id);
    ptr = stack.load_mutable_object<T>(Slic3r::ObjectID(id));
  }
References Slic3r::UndoRedo::StackImpl::load_mutable_object(), and ptr.
load_by_value()
template<class T > void cereal::load_by_value (BinaryInputArchive & ar, T & obj)
  {
    Slic3r::UndoRedo::StackImpl& stack = cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar);
    size_t id;
    ar(id);
    stack.load_mutable_object<T>(Slic3r::ObjectID(id), cfg);
  }
References Slic3r::UndoRedo::StackImpl::load_mutable_object().
Referenced by Slic3r::Internal::StaticSerializationWrapper< T >::load(), and Slic3r::ModelVolume::load().
load_optional()
template<class T > void cereal::load_optional (BinaryInputArchive & ar, std::shared_ptr< const T > & ptr)
  {
    Slic3r::UndoRedo::StackImpl &stack = cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar);
    size_t id;
    ar(id);
    ptr = stack.load_immutable_object<T>(Slic3r::ObjectID(id), true);
  }
References Slic3r::UndoRedo::StackImpl::load_immutable_object(), and ptr.
Referenced by Slic3r::ModelVolume::load().
save() [1/7]
template<class Archive > void cereal::save (Archive & archive, const Slic3r::DynamicPrintConfig & config)
    {
        size_t cnt = config.size();
        archive(cnt);
        for (auto it = config.cbegin(); it != config.cend(); ++it) {
            const Slic3r::ConfigOptionDef* optdef = Slic3r::print_config_def.get(it->first);
            assert(optdef != nullptr);
            assert(optdef->serialization_key_ordinal > 0);
            archive(optdef->serialization_key_ordinal);
            optdef->save_option_to_archive(archive, it->second.get());
        }
    }
References Slic3r::DynamicConfig::cbegin(), Slic3r::DynamicConfig::cend(), Slic3r::ConfigDef::get(), Slic3r::print_config_def, Slic3r::ConfigOptionDef::save_option_to_archive(), Slic3r::ConfigOptionDef::serialization_key_ordinal, and Slic3r::DynamicConfig::size().
save() [2/7]
template<class Archive > void cereal::save (Archive & archive, const Slic3r::Transform3d & m)
{ archive.saveBinary((char *) m.data(), sizeof(double) * 16); }
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data().
save() [3/7]
template<class Archive > void cereal::save (Archive & archive, const Slic3r::TriangleMesh & mesh)
{
        archive.saveBinary(reinterpret_cast<const char*>(&mesh.stats()), sizeof(Slic3r::TriangleMeshStats));
        archive(mesh.its.indices, mesh.its.vertices);
    }
References indexed_triangle_set::indices, Slic3r::TriangleMesh::its, Slic3r::TriangleMesh::stats(), and indexed_triangle_set::vertices.
save() [4/7]
template<class Archive > void cereal::save (Archive & archive, Slic3r::Matrix2f & m)
{ archive.saveBinary((char*)m.data(), sizeof(float) * 4); }
References Eigen::PlainObjectBase< Derived >::data().
save() [5/7]
template<class T > void cereal::save (BinaryOutputArchive & ar, const std::shared_ptr< const T > & ptr)
  {
    ar(cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar).save_immutable_object<T>(const_cast<std::shared_ptr<const T>&>(ptr), false));
  }
References ptr.
save() [6/7]
template<class T > void cereal::save (BinaryOutputArchive & ar, const std::unique_ptr< T > & ptr)
  {
    ar(cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar).save_mutable_object<T>(*ptr.get()));
  }
References ptr.
save() [7/7]
template<class T > void cereal::save (BinaryOutputArchive & ar, T *const & ptr)
  {
    ar(cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar).save_mutable_object<T>(*ptr));
  }
References ptr.
save_by_value()
template<class T > void cereal::save_by_value (BinaryOutputArchive & ar, const T & obj)
  {
    ar(cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar).save_mutable_object<T>(cfg));
  }
Referenced by Slic3r::Internal::StaticSerializationWrapper< T >::save(), and Slic3r::ModelVolume::save().
save_optional()
template<class T > void cereal::save_optional (BinaryOutputArchive & ar, const std::shared_ptr< const T > & ptr)
  {
    ar(cereal::get_user_data<Slic3r::UndoRedo::StackImpl>(ar).save_immutable_object<T>(const_cast<std::shared_ptr<const T>&>(ptr), true));
  }
References ptr.
Referenced by Slic3r::ModelVolume::save().
serialize() [1/6]
template<class Archive > void cereal::serialize (Archive & archive, Slic3r::BoundingBox & bb)
{ archive(bb.min, bb.max, bb.defined); }
References Slic3r::BoundingBoxBase< PointClass >::defined, Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::BoundingBoxBase< PointClass >::min.
serialize() [2/6]
template<class Archive > void cereal::serialize (Archive & archive, Slic3r::BoundingBox3 & bb)
{ archive(bb.min, bb.max, bb.defined); }
References Slic3r::BoundingBoxBase< PointClass >::defined, Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::BoundingBoxBase< PointClass >::min.
serialize() [3/6]
template<class Archive > void cereal::serialize (Archive & archive, Slic3r::BoundingBoxf & bb)
{ archive(bb.min, bb.max, bb.defined); }
References Slic3r::BoundingBoxBase< PointClass >::defined, Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::BoundingBoxBase< PointClass >::min.
serialize() [4/6]
template<class Archive > void cereal::serialize (Archive & archive, Slic3r::BoundingBoxf3 & bb)
{ archive(bb.min, bb.max, bb.defined); }
References Slic3r::BoundingBoxBase< PointClass >::defined, Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::BoundingBoxBase< PointClass >::min.
serialize() [5/6]
template<class Archive > void cereal::serialize (Archive & archive, Slic3r::t_layer_height_range & lhr)
{ archive(lhr.first, lhr.second); }
serialize() [6/6]
template<class Archive > void cereal::serialize (Archive & archive, Slic3r::Vec2i & v)
{ archive(v.x(), v.y()); }