OrcaSlicer: Advanced triangulator_t Methods
Advanced triangulator_t Methods
Functions
void cdt::triangulator_t< T, TNearPointLocator >::do_edgeflip (std::uint32_t iT, std::uint32_t iTopo)
void cdt::triangulator_t< T, TNearPointLocator >::remove_triangles (const std::unordered_set< std::uint32_t > &removedTriangles)
Detailed Description
Advanced methods for manually modifying the triangulation from outside. Please only use them when you know what you are doing.
Function Documentation
do_edgeflip()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::do_edgeflip (std::uint32_t iT, std::uint32_t iTopo)
#include <src/mcut/include/mcut/internal/cdt/triangulate.h>
Flip an edge between two triangle.
Note
Advanced method for manually modifying the triangulation from outside. Please call it when you know what you are doing.
Parameters
iT first triangle
iTopo second triangle
{
    triangle_t& t = triangles[iT];
    triangle_t& tOpo = triangles[iTopo];
    const std::array<std::uint32_t, 3>& triNs = t.neighbors;
    const std::array<std::uint32_t, 3>& triOpoNs = tOpo.neighbors;
    const std::array<std::uint32_t, 3>& triVs = t.vertices;
    const std::array<std::uint32_t, 3>& triOpoVs = tOpo.vertices;
    // find vertices and neighbors
    std::uint32_t i = get_opposite_vertex_index(t, iTopo);
    const std::uint32_t v1 = triVs[i];
    const std::uint32_t v2 = triVs[ccw(i)];
    const std::uint32_t n1 = triNs[i];
    const std::uint32_t n3 = triNs[cw(i)];
    i = get_opposite_vertex_index(tOpo, iT);
    const std::uint32_t v3 = triOpoVs[i];
    const std::uint32_t v4 = triOpoVs[ccw(i)];
    const std::uint32_t n4 = triOpoNs[i];
    const std::uint32_t n2 = triOpoNs[cw(i)];
    // change vertices and neighbors
    using detail::arr3;
    t = triangle_t::make(arr3(v4, v1, v3), arr3(n3, iTopo, n4));
    tOpo = triangle_t::make(arr3(v2, v3, v1), arr3(n2, iT, n1));
    // adjust neighboring triangles and vertices
    change_neighbour(n1, iT, iTopo);
    change_neighbour(n4, iTopo, iT);
    // only adjust adjacent triangles if triangulation is not finalized:
    // can happen when called from outside on an already finalized triangulation
    if (!is_finalized()) {
        add_adjacent_triangle(v1, iTopo);
        add_adjacent_triangle(v3, iT);
        remove_adjacent_triangle(v2, iT);
        remove_adjacent_triangle(v4, iTopo);
    }
}
References cdt::detail::arr3(), cdt::ccw(), cdt::cw(), cdt::get_opposite_vertex_index(), cdt::triangle_t::make(), cdt::triangle_t::neighbors, and cdt::triangle_t::vertices.
remove_triangles()
template<typename T , typename TNearPointLocator > void cdt::triangulator_t< T, TNearPointLocator >::remove_triangles (const std::unordered_set< std::uint32_t > & removedTriangles)
#include <src/mcut/include/mcut/internal/cdt/triangulate.h>
Remove triangles with specified indices. Adjust internal triangulation state accordingly.
Parameters
removedTriangles indices of triangles to remove
{
    if (removedTriangles.empty())
        return;
    // remove triangles and calculate triangle index mapping
    std::unordered_map<std::uint32_t, std::uint32_t> triIndMap;
    for (std::uint32_t iT(0), iTnew(0); iT < std::uint32_t(triangles.size()); ++iT) {
        if (removedTriangles.count(iT))
            continue;
        triIndMap[iT] = iTnew;
        triangles[iTnew] = triangles[iT];
        iTnew++;
    }
    triangles.erase(triangles.end() - removedTriangles.size(), triangles.end());
    // adjust triangles' neighbors
    vertTris = std::vector<std::vector<std::uint32_t>>();
    for (std::uint32_t iT = 0; iT < triangles.size(); ++iT) {
        triangle_t& t = triangles[iT];
        // update neighbors to account for removed triangles
        std::array<std::uint32_t, 3>& nn = t.neighbors;
        for (std::array<std::uint32_t, 3>::iterator n = nn.begin(); n != nn.end(); ++n) {
            if (removedTriangles.count(*n)) {
                *n = null_neighbour;
            } else if (*n != null_neighbour) {
                *n = triIndMap[*n];
            }
        }
    }
}
References n, cdt::triangle_t::neighbors, and cdt::null_neighbour().