OrcaSlicer: Slic3r::orientation Namespace Reference
Slic3r::orientation Namespace Reference
Classes
class AutoOrienter
struct CostItems
struct OrientMesh
Input/Output structure for the orient() function. The mesh field will not be modified during orientment. Instead, the translation and rotation fields will mark the needed transformation for the polygon to be in the orientd position. These can also be set to an initial offset and rotation.
struct OrientParams
struct OrientParamsArea
Typedefs
using OrientMeshs = std::vector< OrientMesh >
Functions
void _orient (OrientMeshs &meshs_, const OrientParams &params, std::function< void(unsigned, std::string)> progressfn, std::function< bool()> stopfn)
void orient (OrientMeshs &items, const OrientMeshs &excludes, const OrientParams &params={})
Orients the input polygons.
void orient (ModelObject *obj)
void orient (ModelInstance *instance)
Variables
static const constexpr int UNORIENTD = -1
A logical bed representing an object not being orientd. Either the orient has not yet successfully run on this OrientPolygon or it could not fit the object due to overly large size or invalid geometry.
Typedef Documentation
OrientMeshs
using Slic3r::orientation::OrientMeshs = typedef std::vector<OrientMesh>
Function Documentation
_orient()
void Slic3r::orientation::_orient (OrientMeshs & meshs_, const OrientParams & params, std::function< void(unsigned, std::string)> progressfn, std::function< bool()> stopfn)
{
    if (!params.parallel)
    {
        for (size_t i = 0; i != meshs_.size(); ++i) {
            auto& mesh_ = meshs_[i];
            progressfn(i, mesh_.name);
            //auto progressfn_i = [&](unsigned cnt) {progressfn(cnt, "Orienting " + mesh_.name); };
            AutoOrienter orienter(&mesh_, params, /*progressfn_i*/{}, stopfn);
            mesh_.orientation = orienter.process();
            Geometry::rotation_from_two_vectors(mesh_.orientation, { 0,0,1 }, mesh_.axis, mesh_.angle, &mesh_.rotation_matrix);
            BOOST_LOG_TRIVIAL(info) << std::fixed << std::setprecision(3) << "v,phi: " << mesh_.axis.transpose() << ", " << mesh_.angle;
            //flush_logs();
        }
    }
    else {
        tbb::parallel_for(tbb::blocked_range<size_t>(0, meshs_.size()), [&meshs_, &params, progressfn, stopfn](const tbb::blocked_range<size_t>& range) {
            for (size_t i = range.begin(); i != range.end(); ++i) {
                auto& mesh_ = meshs_[i];
                progressfn(i, mesh_.name);
                AutoOrienter orienter(&mesh_, params, {}, stopfn);
                mesh_.orientation = orienter.process();
                Geometry::rotation_from_two_vectors(mesh_.orientation, { 0,0,1 }, mesh_.axis, mesh_.angle, &mesh_.rotation_matrix);
                mesh_.euler_angles = Geometry::extract_euler_angles(mesh_.rotation_matrix);
                BOOST_LOG_TRIVIAL(debug) << "rotation_from_two_vectors: " << mesh_.orientation << "; " << mesh_.axis << "; " << mesh_.angle << "; euler: " << mesh_.euler_angles.transpose();
            }});
    }
}
References Slic3r::orientation::OrientParams::parallel, Slic3r::orientation::AutoOrienter::process(), Slic3r::range(), and Slic3r::Geometry::rotation_from_two_vectors().
Referenced by orient().
orient() [1/3]
void Slic3r::orientation::orient (ModelInstance * instance)
{
    auto m = instance->get_object()->mesh();
    AutoOrienter orienter(&m);
    Vec3d orientation = orienter.process();
    Vec3d axis;
    double angle;
    Matrix3d rotation_matrix;
    Geometry::rotation_from_two_vectors(orientation, { 0,0,1 }, axis, angle, &rotation_matrix);
    instance->rotate(rotation_matrix);
}
References Slic3r::angle(), Slic3r::ModelInstance::get_object(), Slic3r::ModelObject::mesh(), orient(), Slic3r::orientation::AutoOrienter::process(), Slic3r::ModelInstance::rotate(), and Slic3r::Geometry::rotation_from_two_vectors().
orient() [2/3]
void Slic3r::orientation::orient (ModelObject * obj)
{
    auto m = obj->mesh();
    AutoOrienter orienter(&m);
    Vec3d orientation = orienter.process();
    Vec3d axis;
    double angle;
    Geometry::rotation_from_two_vectors(orientation, { 0,0,1 }, axis, angle);
    obj->rotate(angle, axis);
    obj->ensure_on_bed();
}
References Slic3r::angle(), Slic3r::ModelObject::ensure_on_bed(), Slic3r::ModelObject::mesh(), orient(), Slic3r::orientation::AutoOrienter::process(), Slic3r::ModelObject::rotate(), and Slic3r::Geometry::rotation_from_two_vectors().
orient() [3/3]
void Slic3r::orientation::orient (OrientMeshs & items, const OrientMeshs & excludes, const OrientParams & params = {})
Orients the input polygons.
Parameters
items Input vector of OrientMeshs. The transformation, rotation and bin_idx fields will be changed after the call finished and can be used to apply the result on the input polygon.
{
    auto &cfn = params.stopcondition;
    auto &pri = params.progressind;
    _orient(arrangables, params, pri, cfn);
}
References _orient(), orient(), Slic3r::orientation::OrientParams::progressind, and Slic3r::orientation::OrientParams::stopcondition.
Referenced by orient(), orient(), orient(), Slic3r::GUI::OrientJob::process(), and Slic3r::CLI::run().
Variable Documentation
UNORIENTD
const constexpr int Slic3r::orientation::UNORIENTD = -1 static constexpr
A logical bed representing an object not being orientd. Either the orient has not yet successfully run on this OrientPolygon or it could not fit the object due to overly large size or invalid geometry.