OrcaSlicer: Slic3r::_BBS_3MF_Base Class Reference
Slic3r::_BBS_3MF_Base Class Reference
Public Member Functions
void log_errors ()
Protected Member Functions
void add_error (const std::string &error) const
void clear_errors ()
Private Attributes
boost::mutex mutex
std::vector< std::string > m_errors
Detailed Description
Member Function Documentation
add_error()
void Slic3r::_BBS_3MF_Base::add_error (const std::string & error) const inline protected
{ boost::unique_lock l(mutex); m_errors.push_back(error); }
References error, m_errors, and mutex.
Referenced by Slic3r::_BBS_3MF_Importer::_load_model_from_file(), Slic3r::_BBS_3MF_Importer::ObjectImporter::extract_object_model(), Slic3r::_BBS_3MF_Importer::get_thumbnail(), and Slic3r::_BBS_3MF_Importer::load_gcode_3mf_from_stream().
clear_errors()
void Slic3r::_BBS_3MF_Base::clear_errors () inline protected
{ m_errors.clear(); }
References m_errors.
Referenced by Slic3r::_BBS_3MF_Importer::~_BBS_3MF_Importer(), and Slic3r::_BBS_3MF_Importer::load_model_from_file().
log_errors()
void Slic3r::_BBS_3MF_Base::log_errors () inline
        {
            for (const std::string& error : m_errors)
                BOOST_LOG_TRIVIAL(error) << error;
        }
References error, and m_errors.
Referenced by Slic3r::bbs_3mf_get_thumbnail(), Slic3r::load_bbs_3mf(), Slic3r::load_gcode_3mf_from_stream(), and Slic3r::store_bbs_3mf().
Member Data Documentation
m_errors
std::vector<std::string> Slic3r::_BBS_3MF_Base::m_errors mutable private
Referenced by add_error(), clear_errors(), and log_errors().
mutex
boost::mutex Slic3r::_BBS_3MF_Base::mutex mutable private
Referenced by Slic3r::_BBS_3MF_Importer::_load_model_from_file(), and add_error().
The documentation for this class was generated from the following file:
src/libslic3r/Format/bbs_3mf.cpp