OrcaSlicer: barrier_t Class Reference
barrier_t Class Reference
#include <src/mcut/include/mcut/internal/tpool.h>
Public Member Functions
barrier_t (unsigned count_)
void wait ()
Private Attributes
unsigned const count
std::atomic< unsigned > spaces
std::atomic< unsigned > generation
Detailed Description
Constructor & Destructor Documentation
barrier_t()
barrier_t::barrier_t (unsigned count_) inline explicit
        : count(count_)
        , spaces(count)
        , generation(0)
    {
    }
Member Function Documentation
wait()
void barrier_t::wait () inline
    {
        unsigned const my_generation = generation;
        if (!--spaces) {
            spaces = count;
            ++generation;
        } else {
            while (generation == my_generation)
                std::this_thread::yield();
        }
    }
References count, generation, and spaces.
Referenced by find_element_with_pred(), find_map_element_by_key(), and get_connected_component_data_impl_detail().
Member Data Documentation
count
unsigned const barrier_t::count private
Referenced by wait().
generation
std::atomic<unsigned> barrier_t::generation private
Referenced by wait().
spaces
std::atomic<unsigned> barrier_t::spaces private
Referenced by wait().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/tpool.h