OrcaSlicer: Slic3r::GUI::AboutDialogLogo Class Reference
Slic3r::GUI::AboutDialogLogo Class Reference
#include <src/slic3r/GUI/AboutDialog.hpp>
Public Member Functions
AboutDialogLogo (wxWindow *parent)
Private Member Functions
void onRepaint (wxEvent &event)
Private Attributes
ScalableBitmap logo
Detailed Description
Constructor & Destructor Documentation
AboutDialogLogo()
Slic3r::GUI::AboutDialogLogo::AboutDialogLogo (wxWindow * parent)
    : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize)
{
    this->SetBackgroundColour(*wxWHITE);
    this->logo = ScalableBitmap(this, Slic3r::var("OrcaSlicer_192px.png"), wxBITMAP_TYPE_PNG);
    this->SetMinSize(this->logo.GetBmpSize());
    this->Bind(wxEVT_PAINT, &AboutDialogLogo::onRepaint, this);
}
References ScalableBitmap::GetBmpSize(), logo, onRepaint(), and Slic3r::var().
Member Function Documentation
onRepaint()
void Slic3r::GUI::AboutDialogLogo::onRepaint (wxEvent & event) private
{
    wxPaintDC dc(this);
    dc.SetBackgroundMode(wxTRANSPARENT);
    wxSize size = this->GetSize();
    int logo_w = this->logo.GetBmpWidth();
    int logo_h = this->logo.GetBmpHeight();
    dc.DrawBitmap(this->logo.bmp(), (size.GetWidth() - logo_w)/2, (size.GetHeight() - logo_h)/2, true);
    event.Skip();
}
References ScalableBitmap::bmp(), ScalableBitmap::GetBmpHeight(), ScalableBitmap::GetBmpWidth(), logo, and size.
Referenced by AboutDialogLogo().
Member Data Documentation
logo
ScalableBitmap Slic3r::GUI::AboutDialogLogo::logo private
Referenced by AboutDialogLogo(), and onRepaint().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AboutDialog.hpp
src/slic3r/GUI/AboutDialog.cpp