OrcaSlicer: orgQhull::QhullHyperplane Class Reference
orgQhull::QhullHyperplane Class Reference
#include <src/qhull/src/libqhullcpp/QhullHyperplane.h>
Classes
struct PrintHyperplane
Public Types
Subtypes
typedef const coordT * iterator
typedef const coordT * const_iterator
typedef QhullHyperplane::iterator Iterator
typedef QhullHyperplane::const_iterator ConstIterator
Public Member Functions
Construct
QhullHyperplane ()
QhullHyperplane (const Qhull &q)
QhullHyperplane (const Qhull &q, int hyperplaneDimension, coordT *c, coordT hyperplaneOffset)
QhullHyperplane (QhullQh *qqh)
QhullHyperplane (QhullQh *qqh, int hyperplaneDimension, coordT *c, coordT hyperplaneOffset)
QhullHyperplane (const QhullHyperplane &other)
QhullHyperplane & operator= (const QhullHyperplane &other)
~QhullHyperplane ()
Conversions –
Includes offset at end
std::vector< coordT > toStdVector () const
GetSet
const coordT * coordinates () const
coordT * coordinates ()
void defineAs (int hyperplaneDimension, coordT *c, coordT hyperplaneOffset)
void defineAs (QhullHyperplane &other)
Creates an alias to other using the same qh_qh.
int dimension () const
bool isValid () const
coordT offset () const
bool operator== (const QhullHyperplane &other) const
Return true if equal If qh_qh defined, tests qh.distanceEpsilon and qh.angleEpsilon otherwise, tests equal coordinates and offset.
bool operator!= (const QhullHyperplane &other) const
const coordT & operator[] (int idx) const
coordT & operator[] (int idx)
void setCoordinates (coordT *c)
void setDimension (int hyperplaneDimension)
void setOffset (coordT hyperplaneOffset)
iterator
iterator begin ()
const_iterator begin () const
const_iterator constBegin () const
const_iterator constEnd () const
int count ()
iterator end ()
const_iterator end () const
size_t size ()
Methods
double distance (const QhullPoint &p) const
Return distance from point to hyperplane. If greater than zero, the point is above the facet (i.e., outside).
double hyperplaneAngle (const QhullHyperplane &other) const
double norm () const
IO
PrintHyperplane print (const char *message) const
PrintHyperplane print (const char *message, const char *offsetMessage) const
Private Attributes
Fields
coordT * hyperplane_coordinates
Normal to hyperplane. facetT.normal is normalized to 1.0.
QhullQh * qh_qh
qhT for distanceEpsilon() in operator==
coordT hyperplane_offset
Distance from hyperplane to origin.
int hyperplane_dimension
Dimension of hyperplane.
Detailed Description
Member Typedef Documentation
const_iterator
typedef const coordT* orgQhull::QhullHyperplane::const_iterator
ConstIterator
typedef QhullHyperplane::const_iterator orgQhull::QhullHyperplane::ConstIterator
iterator
typedef const coordT* orgQhull::QhullHyperplane::iterator
Iterator
typedef QhullHyperplane::iterator orgQhull::QhullHyperplane::Iterator
Constructor & Destructor Documentation
QhullHyperplane() [1/6]
orgQhull::QhullHyperplane::QhullHyperplane () inline
: hyperplane_coordinates(0), qh_qh(0), hyperplane_offset(0.0), hyperplane_dimension(0) {}
QhullHyperplane() [2/6]
orgQhull::QhullHyperplane::QhullHyperplane (const Qhull & q) explicit
: hyperplane_coordinates(0)
, qh_qh(q.qh())
, hyperplane_offset(0.0)
, hyperplane_dimension(0)
{
}
QhullHyperplane() [3/6]
orgQhull::QhullHyperplane::QhullHyperplane (const Qhull & q, int hyperplaneDimension, coordT * c, coordT hyperplaneOffset)
: hyperplane_coordinates(c)
, qh_qh(q.qh())
, hyperplane_offset(hyperplaneOffset)
, hyperplane_dimension(hyperplaneDimension)
{
}
QhullHyperplane() [4/6]
orgQhull::QhullHyperplane::QhullHyperplane (QhullQh * qqh) inline explicit
: hyperplane_coordinates(0), qh_qh(qqh), hyperplane_offset(0.0), hyperplane_dimension(0) {}
QhullHyperplane() [5/6]
orgQhull::QhullHyperplane::QhullHyperplane (QhullQh * qqh, int hyperplaneDimension, coordT * c, coordT hyperplaneOffset) inline
: hyperplane_coordinates(c), qh_qh(qqh), hyperplane_offset(hyperplaneOffset), hyperplane_dimension(hyperplaneDimension) {}
QhullHyperplane() [6/6]
orgQhull::QhullHyperplane::QhullHyperplane (const QhullHyperplane & other) inline
: hyperplane_coordinates(other.hyperplane_coordinates), qh_qh(other.qh_qh), hyperplane_offset(other.hyperplane_offset), hyperplane_dimension(other.hyperplane_dimension) {}
~QhullHyperplane()
orgQhull::QhullHyperplane::~QhullHyperplane () inline
{}
Member Function Documentation
begin() [1/2]
iterator orgQhull::QhullHyperplane::begin () inline
{ return hyperplane_coordinates; }
References hyperplane_coordinates.
Referenced by orgQhull::QhullHyperplane_test::t_const_iterator(), orgQhull::QhullHyperplane_test::t_iterator(), and orgQhull::QhullHyperplane_test::t_readonly().
begin() [2/2]
const_iterator orgQhull::QhullHyperplane::begin () const inline
{ return hyperplane_coordinates; }
References hyperplane_coordinates.
constBegin()
const_iterator orgQhull::QhullHyperplane::constBegin () const inline
{ return hyperplane_coordinates; }
References hyperplane_coordinates.
Referenced by orgQhull::QhullHyperplane_test::t_const_iterator().
constEnd()
const_iterator orgQhull::QhullHyperplane::constEnd () const inline
{ return hyperplane_coordinates+hyperplane_dimension; }
References hyperplane_coordinates, and hyperplane_dimension.
Referenced by orgQhull::QhullHyperplane_test::t_const_iterator().
coordinates() [1/2]
coordT * orgQhull::QhullHyperplane::coordinates () inline
{ return hyperplane_coordinates; }
References hyperplane_coordinates.
coordinates() [2/2]
const coordT * orgQhull::QhullHyperplane::coordinates () const inline
{ return hyperplane_coordinates; }
References hyperplane_coordinates.
Referenced by defineAs(), distance(), norm(), operator<<(), orgQhull::QhullHyperplane_test::t_construct(), orgQhull::QhullHyperplane_test::t_construct_qh(), orgQhull::QhullHyperplane_test::t_define(), orgQhull::QhullHyperplane_test::t_operator(), and orgQhull::QhullHyperplane_test::t_readonly().
count()
int orgQhull::QhullHyperplane::count () inline
{ return hyperplane_dimension; }
References hyperplane_dimension.
Referenced by orgQhull::QhullFacet_test::t_getSet(), and orgQhull::QhullHyperplane_test::t_iterator().
defineAs() [1/2]
void orgQhull::QhullHyperplane::defineAs (int hyperplaneDimension, coordT * c, coordT hyperplaneOffset) inline
{ QHULL_ASSERT(hyperplaneDimension>=0); hyperplane_coordinates= c; hyperplane_dimension= hyperplaneDimension; hyperplane_offset= hyperplaneOffset; }
References hyperplane_coordinates, hyperplane_dimension, hyperplane_offset, and QHULL_ASSERT.
Referenced by orgQhull::QhullHyperplane_test::t_define().
defineAs() [2/2]
void orgQhull::QhullHyperplane::defineAs (QhullHyperplane & other) inline
Creates an alias to other using the same qh_qh.
{ hyperplane_coordinates= other.coordinates(); hyperplane_dimension= other.dimension();  hyperplane_offset= other.offset(); }
References coordinates(), dimension(), hyperplane_coordinates, hyperplane_dimension, hyperplane_offset, and offset().
dimension()
int orgQhull::QhullHyperplane::dimension () const inline
{ return hyperplane_dimension; }
References hyperplane_dimension.
Referenced by defineAs(), distance(), norm(), operator<<(), orgQhull::QhullHyperplane_test::t_construct(), orgQhull::QhullHyperplane_test::t_construct_qh(), orgQhull::QhullHyperplane_test::t_define(), orgQhull::QhullHyperplane_test::t_operator(), orgQhull::QhullHyperplane_test::t_qhullHyperplane_iterator(), and orgQhull::QhullHyperplane_test::t_readonly().
distance()
double orgQhull::QhullHyperplane::distance (const QhullPoint & p) const
Return distance from point to hyperplane. If greater than zero, the point is above the facet (i.e., outside).
{
    const coordT *point= p.coordinates();
    int dim= p.dimension();
    QHULL_ASSERT(dim==dimension());
    const coordT *normal= coordinates();
    double dist;
    switch (dim){
  case 2:
      dist= offset() + point[0] * normal[0] + point[1] * normal[1];
      break;
  case 3:
      dist= offset() + point[0] * normal[0] + point[1] * normal[1] + point[2] * normal[2];
      break;
  case 4:
      dist= offset()+point[0]*normal[0]+point[1]*normal[1]+point[2]*normal[2]+point[3]*normal[3];
      break;
  case 5:
      dist= offset()+point[0]*normal[0]+point[1]*normal[1]+point[2]*normal[2]+point[3]*normal[3]+point[4]*normal[4];
      break;
  case 6:
      dist= offset()+point[0]*normal[0]+point[1]*normal[1]+point[2]*normal[2]+point[3]*normal[3]+point[4]*normal[4]+point[5]*normal[5];
      break;
  case 7:
      dist= offset()+point[0]*normal[0]+point[1]*normal[1]+point[2]*normal[2]+point[3]*normal[3]+point[4]*normal[4]+point[5]*normal[5]+point[6]*normal[6];
      break;
  case 8:
      dist= offset()+point[0]*normal[0]+point[1]*normal[1]+point[2]*normal[2]+point[3]*normal[3]+point[4]*normal[4]+point[5]*normal[5]+point[6]*normal[6]+point[7]*normal[7];
      break;
  default:
      dist= offset();
      for (int k=dim; k--; )
          dist += *point++ * *normal++;
      break;
    }
    return dist;
}//distance
References coordinates(), orgQhull::QhullPoint::coordinates(), coordT, dimension(), orgQhull::QhullPoint::dimension(), offset(), and QHULL_ASSERT.
Referenced by orgQhull::QhullFacet::distance(), and orgQhull::QhullHyperplane_test::t_value().
end() [1/2]
iterator orgQhull::QhullHyperplane::end () inline
{ return hyperplane_coordinates+hyperplane_dimension; }
References hyperplane_coordinates, and hyperplane_dimension.
Referenced by orgQhull::QhullHyperplane_test::t_const_iterator(), orgQhull::QhullHyperplane_test::t_iterator(), and orgQhull::QhullHyperplane_test::t_readonly().
end() [2/2]
const_iterator orgQhull::QhullHyperplane::end () const inline
{ return hyperplane_coordinates+hyperplane_dimension; }
References hyperplane_coordinates, and hyperplane_dimension.
hyperplaneAngle()
double orgQhull::QhullHyperplane::hyperplaneAngle (const QhullHyperplane & other) const
{
    volatile realT result= 0.0;
    QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
        result= qh_getangle(qh_qh, hyperplane_coordinates, other.hyperplane_coordinates);
    }
    qh_qh->NOerrexit= true;
    qh_qh->maybeThrowQhullMessage(QH_TRY_status);
    return result;
}//hyperplaneAngle
References hyperplane_coordinates, orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, qh_getangle(), qh_qh, QH_TRY_, and realT.
Referenced by operator==(), and orgQhull::QhullHyperplane_test::t_value().
isValid()
bool orgQhull::QhullHyperplane::isValid () const inline
{ return hyperplane_coordinates!=0 && hyperplane_dimension>0; }
References hyperplane_coordinates, and hyperplane_dimension.
Referenced by orgQhull::QhullHyperplane_test::t_construct(), orgQhull::QhullHyperplane_test::t_construct_qh(), and orgQhull::QhullHyperplane_test::t_readonly().
norm()
double orgQhull::QhullHyperplane::norm () const
             {
    double d= 0.0;
    const coordT *c= coordinates();
    for (int k=dimension(); k--; ){
        d += *c * *c;
        ++c;
    }
    return sqrt(d);
}//norm
References coordinates(), coordT, dimension(), and sqrt().
Referenced by orgQhull::QhullFacet_test::t_getSet(), and orgQhull::QhullHyperplane_test::t_value().
offset()
coordT orgQhull::QhullHyperplane::offset () const inline
{ return hyperplane_offset; }
References hyperplane_offset.
Referenced by defineAs(), distance(), orgQhull::QhullFacet::innerplane(), operator<<(), orgQhull::QhullFacet::outerplane(), orgQhull::QhullHyperplane_test::t_construct(), orgQhull::QhullHyperplane_test::t_construct_qh(), orgQhull::QhullHyperplane_test::t_define(), orgQhull::QhullFacet_test::t_getSet(), and orgQhull::QhullHyperplane_test::t_readonly().
operator!=()
bool orgQhull::QhullHyperplane::operator!= (const QhullHyperplane & other) const inline
{ return !operator==(other); }
References operator==().
operator=()
QhullHyperplane & orgQhull::QhullHyperplane::operator= (const QhullHyperplane & other) inline
{ hyperplane_coordinates= other.hyperplane_coordinates; qh_qh= other.qh_qh; hyperplane_offset= other.hyperplane_offset; hyperplane_dimension= other.hyperplane_dimension; return *this; }
References hyperplane_coordinates, hyperplane_dimension, hyperplane_offset, and qh_qh.
operator==()
bool orgQhull::QhullHyperplane::operator== (const QhullHyperplane & other) const
Return true if equal If qh_qh defined, tests qh.distanceEpsilon and qh.angleEpsilon otherwise, tests equal coordinates and offset.
{
    if(hyperplane_dimension!=other.hyperplane_dimension || !hyperplane_coordinates || !other.hyperplane_coordinates){
        return false;
    }
    double d= fabs(hyperplane_offset-other.hyperplane_offset);
    if(d > (qh_qh ? qh_qh->distanceEpsilon() : 0.0)){
        return false;
    }
    double angle= hyperplaneAngle(other);
    double a= fabs(angle-1.0);
    if(a > (qh_qh ? qh_qh->angleEpsilon() : 0.0)){
        return false;
    }
    return true;
}//operator==
References orgQhull::QhullQh::angleEpsilon(), orgQhull::QhullQh::distanceEpsilon(), hyperplane_coordinates, hyperplane_dimension, hyperplane_offset, hyperplaneAngle(), and qh_qh.
Referenced by operator!=().
operator[]() [1/2]
coordT & orgQhull::QhullHyperplane::operator[] (int idx) inline
{ QHULL_ASSERT(idx>=0 && idx<hyperplane_dimension); return *(hyperplane_coordinates+idx); }
References hyperplane_coordinates, hyperplane_dimension, and QHULL_ASSERT.
operator[]() [2/2]
const coordT & orgQhull::QhullHyperplane::operator[] (int idx) const inline
{ QHULL_ASSERT(idx>=0 && idx<hyperplane_dimension); return *(hyperplane_coordinates+idx); }
References hyperplane_coordinates, hyperplane_dimension, and QHULL_ASSERT.
print() [1/2]
PrintHyperplane orgQhull::QhullHyperplane::print (const char * message) const inline
{ return PrintHyperplane(message, "", *this); }
Referenced by operator<<(), operator<<(), and orgQhull::QhullHyperplane_test::t_io().
print() [2/2]
PrintHyperplane orgQhull::QhullHyperplane::print (const char * message, const char * offsetMessage) const inline
{ return PrintHyperplane(message, offsetMessage, *this); }
setCoordinates()
void orgQhull::QhullHyperplane::setCoordinates (coordT * c) inline
{ hyperplane_coordinates= c; }
References hyperplane_coordinates.
Referenced by orgQhull::QhullHyperplane_test::t_define().
setDimension()
void orgQhull::QhullHyperplane::setDimension (int hyperplaneDimension) inline
{ hyperplane_dimension= hyperplaneDimension; }
References hyperplane_dimension.
Referenced by orgQhull::QhullHyperplane_test::t_define().
setOffset()
void orgQhull::QhullHyperplane::setOffset (coordT hyperplaneOffset) inline
{ hyperplane_offset= hyperplaneOffset; }
References hyperplane_offset.
Referenced by orgQhull::QhullFacet::innerplane(), orgQhull::QhullFacet::outerplane(), and orgQhull::QhullHyperplane_test::t_define().
size()
size_t orgQhull::QhullHyperplane::size () inline
{ return (size_t)hyperplane_dimension; }
References hyperplane_dimension.
Referenced by orgQhull::QhullHyperplane_test::t_iterator().
toStdVector()
std::vector< coordT > orgQhull::QhullHyperplane::toStdVector () const
{
    QhullHyperplaneIterator i(*this);
    std::vector<coordT> fs;
    while(i.hasNext()){
        fs.push_back(i.next());
    }
    fs.push_back(hyperplane_offset);
    return fs;
}//toStdVector
References hyperplane_offset.
Referenced by orgQhull::QhullHyperplane_test::t_convert().
Member Data Documentation
hyperplane_coordinates
coordT* orgQhull::QhullHyperplane::hyperplane_coordinates private
Normal to hyperplane. facetT.normal is normalized to 1.0.
Referenced by begin(), begin(), constBegin(), constEnd(), coordinates(), coordinates(), defineAs(), defineAs(), end(), end(), hyperplaneAngle(), isValid(), operator=(), operator==(), operator[](), operator[](), and setCoordinates().
hyperplane_dimension
int orgQhull::QhullHyperplane::hyperplane_dimension private
Dimension of hyperplane.
Referenced by constEnd(), count(), defineAs(), defineAs(), dimension(), end(), end(), isValid(), operator=(), operator==(), operator[](), operator[](), setDimension(), and size().
hyperplane_offset
coordT orgQhull::QhullHyperplane::hyperplane_offset private
Distance from hyperplane to origin.
Referenced by defineAs(), defineAs(), offset(), operator=(), operator==(), setOffset(), and toStdVector().
qh_qh
QhullQh* orgQhull::QhullHyperplane::qh_qh private
qhT for distanceEpsilon() in operator==
Referenced by hyperplaneAngle(), operator=(), and operator==().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullHyperplane.h
src/qhull/src/libqhullcpp/QhullHyperplane.cpp