OrcaSlicer: orgQhull::Coordinates Class Reference
orgQhull::Coordinates Class Reference
#include <src/qhull/src/libqhullcpp/Coordinates.h>
Classes
class const_iterator
class iterator
Public Types
Subtypes
typedef iterator Iterator
typedef const_iterator ConstIterator
typedef coordT value_type
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef value_type * pointer
typedef value_type & reference
typedef ptrdiff_t difference_type
typedef countT size_type
Public Member Functions
Construct
Coordinates ()
Coordinates (const std::vector< coordT > &other)
Coordinates (const Coordinates &other)
Coordinates & operator= (const Coordinates &other)
Coordinates & operator= (const std::vector< coordT > &other)
~Coordinates ()
Conversion
std::vector< coordT > toStdVector () const
GetSet
countT count () const
coordT * data ()
const coordT * data () const
bool isEmpty () const
bool operator== (const Coordinates &other) const
bool operator!= (const Coordinates &other) const
size_t size () const
Coordinates operator+ (const Coordinates &other) const
Element access
coordT & at (countT idx)
const coordT & at (countT idx) const
coordT & back ()
const coordT & back () const
coordT & first ()
const coordT & first () const
coordT & front ()
const coordT & front () const
coordT & last ()
const coordT & last () const
Coordinates mid (countT idx, countT length=-1) const
coordT & operator[] (countT idx)
const coordT & operator[] (countT idx) const
coordT value (countT idx, const coordT &defaultValue) const
Iterator
iterator begin ()
const_iterator begin () const
const_iterator constBegin () const
const_iterator constEnd () const
iterator end ()
const_iterator end () const
Modify
void append (int pointDimension, coordT *c)
void append (const coordT &c)
void clear ()
iterator erase (iterator idx)
iterator erase (iterator beginIterator, iterator endIterator)
void insert (countT before, const coordT &c)
iterator insert (iterator before, const coordT &c)
void move (countT from, countT to)
Coordinates & operator+= (const Coordinates &other)
Coordinates & operator+= (const coordT &c)
Coordinates & operator<< (const Coordinates &other)
Coordinates & operator<< (const coordT &c)
void pop_back ()
void pop_front ()
void prepend (const coordT &c)
void push_back (const coordT &c)
void push_front (const coordT &c)
void removeAt (countT idx)
void removeFirst ()
void removeLast ()
void replace (countT idx, const coordT &c)
void reserve (countT i)
void swap (countT idx, countT other)
coordT takeAt (countT idx)
coordT takeFirst ()
coordT takeLast ()
Search
bool contains (const coordT &t) const
countT count (const coordT &t) const
countT indexOf (const coordT &t, countT from=0) const
countT lastIndexOf (const coordT &t, countT from=-1) const
void removeAll (const coordT &t)
Private Attributes
Fields
std::vector< coordT > coordinate_array
Detailed Description
Member Typedef Documentation
const_pointer
typedef const value_type* orgQhull::Coordinates::const_pointer
const_reference
typedef const value_type& orgQhull::Coordinates::const_reference
ConstIterator
typedef const_iterator orgQhull::Coordinates::ConstIterator
difference_type
typedef ptrdiff_t orgQhull::Coordinates::difference_type
Iterator
typedef iterator orgQhull::Coordinates::Iterator
pointer
typedef value_type* orgQhull::Coordinates::pointer
reference
typedef value_type& orgQhull::Coordinates::reference
size_type
typedef countT orgQhull::Coordinates::size_type
value_type
typedef coordT orgQhull::Coordinates::value_type
Constructor & Destructor Documentation
Coordinates() [1/3]
orgQhull::Coordinates::Coordinates () inline
{};
Coordinates() [2/3]
orgQhull::Coordinates::Coordinates (const std::vector< coordT > & other) inline explicit
: coordinate_array(other) {}
Coordinates() [3/3]
orgQhull::Coordinates::Coordinates (const Coordinates & other) inline
: coordinate_array(other.coordinate_array) {}
~Coordinates()
orgQhull::Coordinates::~Coordinates () inline
{}
Member Function Documentation
append() [1/2]
void orgQhull::Coordinates::append (const coordT & c) inline
{ push_back(c); }
References push_back().
append() [2/2]
void orgQhull::Coordinates::append (int pointDimension, coordT * c)
{
    if(c){
        coordT *p= c;
        for(int i= 0; i<pointDimension; ++i){
            coordinate_array.push_back(*p++);
        }
    }
}//append dim coordT
References coordinate_array, and coordT.
Referenced by orgQhull::Qhull::feasiblePoint(), and operator+=().
at() [1/2]
coordT & orgQhull::Coordinates::at (countT idx) inline
{ return coordinate_array.at(idx); }
References coordinate_array.
Referenced by data(), data(), swap(), and takeAt().
at() [2/2]
const coordT & orgQhull::Coordinates::at (countT idx) const inline
{ return coordinate_array.at(idx); }
References coordinate_array.
back() [1/2]
coordT & orgQhull::Coordinates::back () inline
{ return coordinate_array.back(); }
References coordinate_array.
Referenced by last(), last(), and orgQhull::Coordinates_test::t_convert().
back() [2/2]
const coordT & orgQhull::Coordinates::back () const inline
{ return coordinate_array.back(); }
References coordinate_array.
begin() [1/2]
iterator orgQhull::Coordinates::begin () inline
{ return iterator(coordinate_array.begin()); }
References coordinate_array.
Referenced by orgQhull::MutableCoordinatesIterator::MutableCoordinatesIterator(), orgQhull::PointCoordinates::beginCoordinates(), orgQhull::PointCoordinates::beginCoordinates(), orgQhull::PointCoordinates::beginCoordinates(), orgQhull::PointCoordinates::beginCoordinates(), constBegin(), indexOf(), orgQhull::Qhull::initializeFeasiblePoint(), insert(), lastIndexOf(), mid(), operator+(), operator+=(), operator<<(), orgQhull::MutableCoordinatesIterator::operator=(), prepend(), push_front(), removeAt(), removeFirst(), takeAt(), and orgQhull::MutableCoordinatesIterator::toFront().
begin() [2/2]
const_iterator orgQhull::Coordinates::begin () const inline
{ return const_iterator(coordinate_array.begin()); }
References coordinate_array.
clear()
void orgQhull::Coordinates::clear () inline
{ coordinate_array.clear(); }
References coordinate_array.
constBegin()
const_iterator orgQhull::Coordinates::constBegin () const inline
{ return begin(); }
References begin().
Referenced by orgQhull::CoordinatesIterator::findPrevious(), orgQhull::MutableCoordinatesIterator::findPrevious(), orgQhull::CoordinatesIterator::hasPrevious(), orgQhull::MutableCoordinatesIterator::hasPrevious(), lastIndexOf(), orgQhull::CoordinatesIterator::operator=(), and orgQhull::CoordinatesIterator::toFront().
constEnd()
const_iterator orgQhull::Coordinates::constEnd () const inline
{ return end(); }
References end().
Referenced by orgQhull::CoordinatesIterator::findNext(), orgQhull::MutableCoordinatesIterator::findNext(), orgQhull::CoordinatesIterator::hasNext(), orgQhull::MutableCoordinatesIterator::hasNext(), indexOf(), orgQhull::MutableCoordinatesIterator::item_exists(), orgQhull::MutableCoordinatesIterator::remove(), orgQhull::MutableCoordinatesIterator::setValue(), and orgQhull::CoordinatesIterator::toBack().
contains()
bool orgQhull::Coordinates::contains (const coordT & t) const
{
    CoordinatesIterator i(*this);
    return i.findNext(t);
}//contains
References orgQhull::CoordinatesIterator::findNext().
count() [1/2]
countT orgQhull::Coordinates::count () const inline
{ return static_cast<countT>(size()); }
References size().
Referenced by indexOf(), orgQhull::PointCoordinates::indexOffset(), lastIndexOf(), orgQhull::PointCoordinates::makeValid(), mid(), operator<<(), orgQhull::Coordinates_test::t_construct(), orgQhull::Coordinates_test::t_element(), orgQhull::Coordinates_test::t_operator(), and value().
count() [2/2]
countT orgQhull::Coordinates::count (const coordT & t) const
{
    CoordinatesIterator i(*this);
    countT result= 0;
    while(i.findNext(t)){
        ++result;
    }
    return result;
}//count
References orgQhull::CoordinatesIterator::findNext().
data() [1/2]
coordT * orgQhull::Coordinates::data () inline
{ return isEmpty() ? 0 : &at(0); }
References at(), and isEmpty().
Referenced by orgQhull::PointCoordinates::makeValid(), and orgQhull::Qhull::origin().
data() [2/2]
const coordT * orgQhull::Coordinates::data () const inline
{ return const_cast<const pointT*>(isEmpty() ? 0 : &at(0)); }
References at(), isEmpty(), and pointT.
end() [1/2]
iterator orgQhull::Coordinates::end () inline
{ return iterator(coordinate_array.end()); }
References coordinate_array.
Referenced by orgQhull::MutableCoordinatesIterator::MutableCoordinatesIterator(), constEnd(), orgQhull::PointCoordinates::endCoordinates(), orgQhull::PointCoordinates::endCoordinates(), orgQhull::MutableCoordinatesIterator::findPrevious(), orgQhull::Qhull::initializeFeasiblePoint(), operator+(), operator+=(), orgQhull::MutableCoordinatesIterator::operator=(), orgQhull::MutableCoordinatesIterator::remove(), removeLast(), orgQhull::MutableCoordinatesIterator::toBack(), and orgQhull::MutableCoordinatesIterator::toFront().
end() [2/2]
const_iterator orgQhull::Coordinates::end () const inline
{ return const_iterator(coordinate_array.end()); }
References coordinate_array.
erase() [1/2]
iterator orgQhull::Coordinates::erase (iterator beginIterator, iterator endIterator) inline
{ return iterator(coordinate_array.erase(beginIterator.base(), endIterator.base())); }
References orgQhull::Coordinates::iterator::base(), and coordinate_array.
erase() [2/2]
iterator orgQhull::Coordinates::erase (iterator idx) inline
{ return iterator(coordinate_array.erase(idx.base())); }
References orgQhull::Coordinates::iterator::base(), and coordinate_array.
Referenced by orgQhull::MutableCoordinatesIterator::remove(), removeAt(), removeFirst(), removeLast(), and takeAt().
first() [1/2]
coordT & orgQhull::Coordinates::first () inline
{ return front(); }
References front().
first() [2/2]
const coordT & orgQhull::Coordinates::first () const inline
{ return front(); }
References front().
front() [1/2]
coordT & orgQhull::Coordinates::front () inline
{ return coordinate_array.front(); }
References coordinate_array.
Referenced by first(), and first().
front() [2/2]
const coordT & orgQhull::Coordinates::front () const inline
{ return coordinate_array.front(); }
References coordinate_array.
indexOf()
countT orgQhull::Coordinates::indexOf (const coordT & t, countT from = 0) const
{
    if(from<0){
        from += count();
        if(from<0){
            from= 0;
        }
    }
    if(from<count()){
        const_iterator i= begin()+from;
        while(i!=constEnd()){
            if(*i==t){
                return (static_cast<countT>(i-begin())); // WARN64 coordinate index
            }
            ++i;
        }
    }
    return -1;
}//indexOf
References begin(), constEnd(), and count().
insert() [1/2]
void orgQhull::Coordinates::insert (countT before, const coordT & c) inline
{ insert(begin()+before, c); }
References begin(), and insert().
Referenced by orgQhull::MutableCoordinatesIterator::insert(), insert(), move(), prepend(), and push_front().
insert() [2/2]
iterator orgQhull::Coordinates::insert (iterator before, const coordT & c) inline
{ return iterator(coordinate_array.insert(before.base(), c)); }
References orgQhull::Coordinates::iterator::base(), and coordinate_array.
isEmpty()
bool orgQhull::Coordinates::isEmpty () const inline
{ return coordinate_array.empty(); }
References coordinate_array.
Referenced by data(), data(), orgQhull::Qhull::initializeFeasiblePoint(), and orgQhull::PointCoordinates_test::t_getset().
last() [1/2]
coordT & orgQhull::Coordinates::last () inline
{ return back(); }
References back().
Referenced by takeLast().
last() [2/2]
const coordT & orgQhull::Coordinates::last () const inline
{ return back(); }
References back().
lastIndexOf()
countT orgQhull::Coordinates::lastIndexOf (const coordT & t, countT from = -1) const
{
    if(from<0){
        from += count();
    }else if(from>=count()){
        from= count()-1;
    }
    if(from>=0){
        const_iterator i= begin()+from+1;
        while(i-- != constBegin()){
            if(*i==t){
                return (static_cast<countT>(i-begin())); // WARN64 coordinate index
            }
        }
    }
    return -1;
}//lastIndexOf
References begin(), constBegin(), and count().
mid()
Coordinates orgQhull::Coordinates::mid (countT idx, countT length = -1) const
{
    countT newLength= length;
    if(length<0 || idx+length > count()){
        newLength= count()-idx;
    }
    Coordinates result;
    if(newLength>0){
        std::copy(begin()+idx, begin()+(idx+newLength), std::back_inserter(result));
    }
    return result;
}//mid
References begin(), count(), and length().
move()
void orgQhull::Coordinates::move (countT from, countT to) inline
{ insert(to, takeAt(from)); }
References insert(), and takeAt().
operator!=()
bool orgQhull::Coordinates::operator!= (const Coordinates & other) const inline
{ return coordinate_array!=other.coordinate_array; }
References coordinate_array.
operator+()
Coordinates orgQhull::Coordinates::operator+ (const Coordinates & other) const
{
    Coordinates result(*this);
    std::copy(other.begin(), other.end(), std::back_inserter(result));
    return result;
}//operator+
References begin(), and end().
operator+=() [1/2]
Coordinates & orgQhull::Coordinates::operator+= (const Coordinates & other)
{
    if(&other==this){
        Coordinates clone(other);
        std::copy(clone.begin(), clone.end(), std::back_inserter(*this));
    }else{
        std::copy(other.begin(), other.end(), std::back_inserter(*this));
    }
    return *this;
}//operator+=
References begin(), and end().
operator+=() [2/2]
Coordinates & orgQhull::Coordinates::operator+= (const coordT & c) inline
{ append(c); return *this; }
References append().
operator<<() [1/2]
Coordinates & orgQhull::Coordinates::operator<< (const Coordinates & other) inline
{ return *this += other; }
operator<<() [2/2]
Coordinates & orgQhull::Coordinates::operator<< (const coordT & c) inline
{ return *this += c; }
operator=() [1/2]
Coordinates & orgQhull::Coordinates::operator= (const Coordinates & other) inline
{ coordinate_array= other.coordinate_array; return *this; }
References coordinate_array.
operator=() [2/2]
Coordinates & orgQhull::Coordinates::operator= (const std::vector< coordT > & other) inline
{ coordinate_array= other; return *this; }
References coordinate_array.
operator==()
bool orgQhull::Coordinates::operator== (const Coordinates & other) const inline
{ return coordinate_array==other.coordinate_array; }
References coordinate_array.
operator[]() [1/2]
coordT & orgQhull::Coordinates::operator[] (countT idx) inline
{ return coordinate_array.operator[](idx); }
References coordinate_array.
operator[]() [2/2]
const coordT & orgQhull::Coordinates::operator[] (countT idx) const inline
{ return coordinate_array.operator[](idx); }
References coordinate_array.
pop_back()
void orgQhull::Coordinates::pop_back () inline
{ coordinate_array.pop_back(); }
References coordinate_array.
pop_front()
void orgQhull::Coordinates::pop_front () inline
{ removeFirst(); }
References removeFirst().
prepend()
void orgQhull::Coordinates::prepend (const coordT & c) inline
{ insert(begin(), c); }
References begin(), and insert().
push_back()
void orgQhull::Coordinates::push_back (const coordT & c) inline
{ coordinate_array.push_back(c); }
References coordinate_array.
Referenced by append(), and orgQhull::PointCoordinates::appendPoints().
push_front()
void orgQhull::Coordinates::push_front (const coordT & c) inline
{ insert(begin(), c); }
References begin(), and insert().
removeAll()
void orgQhull::Coordinates::removeAll (const coordT & t)
{
    MutableCoordinatesIterator i(*this);
    while(i.findNext(t)){
        i.remove();
    }
}//removeAll
References orgQhull::MutableCoordinatesIterator::findNext(), and orgQhull::MutableCoordinatesIterator::remove().
removeAt()
void orgQhull::Coordinates::removeAt (countT idx) inline
{ erase(begin()+idx); }
References begin(), and erase().
removeFirst()
void orgQhull::Coordinates::removeFirst () inline
{ erase(begin()); }
References begin(), and erase().
Referenced by pop_front().
removeLast()
void orgQhull::Coordinates::removeLast () inline
{ erase(--end()); }
References end(), and erase().
Referenced by takeLast().
replace()
void orgQhull::Coordinates::replace (countT idx, const coordT & c) inline
{ (*this)[idx]= c; }
reserve()
void orgQhull::Coordinates::reserve (countT i) inline
{ coordinate_array.reserve(i); }
References coordinate_array.
Referenced by orgQhull::PointCoordinates::reserveCoordinates().
size()
size_t orgQhull::Coordinates::size () const inline
{ return coordinate_array.size(); }
References coordinate_array.
Referenced by count(), orgQhull::Qhull::initializeFeasiblePoint(), orgQhull::PointCoordinates::reserveCoordinates(), and orgQhull::Coordinates_test::t_convert().
swap()
void orgQhull::Coordinates::swap (countT idx, countT other)
{
    coordT c= at(idx);
    at(idx)= at(other);
    at(other)= c;
}//swap
References at(), and coordT.
takeAt()
coordT orgQhull::Coordinates::takeAt (countT idx)
{
    coordT c= at(idx);
    erase(begin()+idx);
    return c;
}//takeAt
References at(), begin(), coordT, and erase().
Referenced by move(), and takeFirst().
takeFirst()
coordT orgQhull::Coordinates::takeFirst () inline
{ return takeAt(0); }
References takeAt().
takeLast()
coordT orgQhull::Coordinates::takeLast ()
{
    coordT c= last();
    removeLast();
    return c;
}//takeLast
References coordT, last(), and removeLast().
toStdVector()
std::vector< coordT > orgQhull::Coordinates::toStdVector () const inline
{ return coordinate_array; }
References coordinate_array.
Referenced by orgQhull::PointCoordinates::toStdVector().
value()
coordT orgQhull::Coordinates::value (countT idx, const coordT & defaultValue) const
{
    return ((idx < 0 || idx >= count()) ? defaultValue : (*this)[idx]);
}//value
References count().
Referenced by orgQhull::Coordinates_test::t_element().
Member Data Documentation
coordinate_array
std::vector<coordT> orgQhull::Coordinates::coordinate_array private
Referenced by append(), at(), at(), back(), back(), begin(), begin(), clear(), end(), end(), erase(), erase(), front(), front(), insert(), isEmpty(), operator!=(), operator=(), operator=(), operator==(), operator[](), operator[](), pop_back(), push_back(), reserve(), size(), and toStdVector().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/Coordinates.h
src/qhull/src/libqhullcpp/Coordinates.cpp