OrcaSlicer: Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType > Class Template Reference
Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType > Class Template Reference
#include <src/libslic3r/ClipperUtils.hpp>
Classes
struct iterator
Public Member Functions
MultiPointsProvider (const std::vector< MultiPointType > &multipoints)
iterator cbegin () const
iterator begin () const
iterator cend () const
iterator end () const
size_t size () const
Private Attributes
const std::vector< MultiPointType > & m_multipoints
Detailed Description
template<typename MultiPointType>
class Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >
Constructor & Destructor Documentation
MultiPointsProvider()
template<typename MultiPointType > Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::MultiPointsProvider (const std::vector< MultiPointType > & multipoints) inline
: m_multipoints(multipoints) {}
Member Function Documentation
begin()
template<typename MultiPointType > iterator Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::begin () const inline
{ return this->cbegin(); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::cbegin().
cbegin()
template<typename MultiPointType > iterator Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::cbegin () const inline
{ return iterator(m_multipoints.begin()); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::m_multipoints.
Referenced by Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::begin().
cend()
template<typename MultiPointType > iterator Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::cend () const inline
{ return iterator(m_multipoints.end()); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::m_multipoints.
Referenced by Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::end().
end()
template<typename MultiPointType > iterator Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::end () const inline
{ return this->cend(); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::cend().
size()
template<typename MultiPointType > size_t Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::size () const inline
{ return m_multipoints.size(); }
References Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::m_multipoints.
Member Data Documentation
m_multipoints
template<typename MultiPointType > const std::vector<MultiPointType>& Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::m_multipoints private
Referenced by Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::cbegin(), Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::cend(), and Slic3r::ClipperUtils::MultiPointsProvider< MultiPointType >::size().
The documentation for this class was generated from the following file:
src/libslic3r/ClipperUtils.hpp