OrcaSlicer: orgQhull::QhullPoints Class Reference
orgQhull::QhullPoints Class Reference
Java-style iterator.
#include <src/qhull/src/libqhullcpp/QhullPoints.h>
Classes
class const_iterator
class iterator
struct PrintPoints
Public Types
Subtypes
typedef QhullPoints::const_iterator ConstIterator
typedef QhullPoints::iterator Iterator
Public Member Functions
Construct
QhullPoint, PointCoordinates, and QhullPoints have similar constructors If Qhull/QhullQh is not initialized, then QhullPoints.dimension() is zero unless explicitly set Cannot define QhullPoints(int pointDimension) since it is ambiguous with QhullPoints(QhullQh *qqh)
QhullPoints ()
QhullPoints (int pointDimension, countT coordinateCount2, coordT *c)
QhullPoints (const Qhull &q)
QhullPoints (const Qhull &q, countT coordinateCount2, coordT *c)
QhullPoints (const Qhull &q, int pointDimension, countT coordinateCount2, coordT *c)
QhullPoints (QhullQh *qqh)
QhullPoints (QhullQh *qqh, countT coordinateCount2, coordT *c)
QhullPoints (QhullQh *qqh, int pointDimension, countT coordinateCount2, coordT *c)
QhullPoints (const QhullPoints &other)
Copy constructor copies pointers but not contents. Needed for return by value and parameter passing.
QhullPoints & operator= (const QhullPoints &other)
~QhullPoints ()
Conversion
std::vector< QhullPoint > toStdVector () const
GetSet
const QhullPoint at (countT idx) const
const QhullPoint back () const
QhullPoint back ()
ConstIterator begin () const
Iterator begin ()
ConstIterator constBegin () const
const coordT * constData () const
ConstIterator constEnd () const
coordT * coordinates () const
countT coordinateCount () const
countT count () const
const coordT * data () const
coordT * data ()
void defineAs (int pointDimension, countT coordinatesCount, coordT *c)
void defineAs (countT coordinatesCount, coordT *c)
void defineAs (const QhullPoints &other)
int dimension () const
ConstIterator end () const
Iterator end ()
coordT * extraCoordinates () const
countT extraCoordinatesCount () const
const QhullPoint first () const
QhullPoint first ()
const QhullPoint front () const
QhullPoint front ()
bool includesCoordinates (const coordT *c) const
bool isEmpty () const
const QhullPoint last () const
QhullPoint last ()
bool operator== (const QhullPoints &other) const
QhullPoints is equal if the same address, or if the coordinates are identical Use QhullPoint.operator==() for DISTround equality.
bool operator!= (const QhullPoints &other) const
QhullPoint operator[] (countT idx) const
QhullQh * qh () const
void resetQhullQh (QhullQh *qqh)
Reset QhullPoints to QhullQh and its hullDimension() Does not free up old qh_qh.
void setDimension (int d)
size_t size () const
QhullPoint value (countT idx) const
QhullPoint value (countT idx, QhullPoint &defaultValue) const
Methods
bool contains (const QhullPoint &t) const
countT count (const QhullPoint &t) const
countT indexOf (const coordT *pointCoordinates) const
countT indexOf (const coordT *pointCoordinates, int noThrow) const
countT indexOf (const QhullPoint &t) const
countT lastIndexOf (const QhullPoint &t) const
QhullPoints mid (countT idx, countT length=-1) const
Returns a subset of the points, not a copy.
IO
PrintPoints print (const char *message) const
PrintPoints printWithIdentifier (const char *message) const
Private Attributes
Fields
coordT * point_first
First coordinate of an array of points of point_dimension.
coordT * point_end
End of point coordinates (end>=first). Trailing coordinates ignored.
QhullQh * qh_qh
Maybe initialized NULL to allow ownership by RboxPoints qh_qh used for QhullPoint() and qh_qh->hull_dim in constructor.
int point_dimension
Dimension, >=0.
Detailed Description
Java-style iterator.
QhullPoints are an array of QhullPoint as pointers into an array of coordinates. For Qhull/QhullQh, QhullPoints must use hull_dim. Can change QhullPoint to input_dim if needed for Delaunay input site
Member Typedef Documentation
ConstIterator
typedef QhullPoints::const_iterator orgQhull::QhullPoints::ConstIterator
Iterator
typedef QhullPoints::iterator orgQhull::QhullPoints::Iterator
Constructor & Destructor Documentation
QhullPoints() [1/9]
orgQhull::QhullPoints::QhullPoints () inline
: point_first(0), point_end(0), qh_qh(0), point_dimension(0) { }
Referenced by mid().
QhullPoints() [2/9]
orgQhull::QhullPoints::QhullPoints (int pointDimension, countT coordinateCount2, coordT * c) inline
: point_first(c), point_end(c+coordinateCount2), qh_qh(0), point_dimension(pointDimension) { QHULL_ASSERT(pointDimension>=0); }
References QHULL_ASSERT.
QhullPoints() [3/9]
orgQhull::QhullPoints::QhullPoints (const Qhull & q) explicit
: point_first(0)
, point_end(0)
, qh_qh(q.qh())
, point_dimension(q.hullDimension())
{
}//QhullPoints Qhull
QhullPoints() [4/9]
orgQhull::QhullPoints::QhullPoints (const Qhull & q, countT coordinateCount2, coordT * c)
: point_first(c)
, point_end(c+coordinateCount2)
, qh_qh(q.qh())
, point_dimension(q.hullDimension())
{
    QHULL_ASSERT(q.hullDimension());
    QHULL_ASSERT(coordinateCount2>=0);
}//QhullPoints Qhull dim
References orgQhull::Qhull::hullDimension(), and QHULL_ASSERT.
QhullPoints() [5/9]
orgQhull::QhullPoints::QhullPoints (const Qhull & q, int pointDimension, countT coordinateCount2, coordT * c)
: point_first(c)
, point_end(c+coordinateCount2)
, qh_qh(q.qh())
, point_dimension(pointDimension)
{
    QHULL_ASSERT(pointDimension>=0);
    QHULL_ASSERT(coordinateCount2>=0);
}//QhullPoints Qhull dim coordT
References QHULL_ASSERT.
QhullPoints() [6/9]
orgQhull::QhullPoints::QhullPoints (QhullQh * qqh) inline explicit
: point_first(0), point_end(0), qh_qh(qqh), point_dimension(qqh ? qqh->hull_dim : 0) { }
QhullPoints() [7/9]
orgQhull::QhullPoints::QhullPoints (QhullQh * qqh, countT coordinateCount2, coordT * c) inline
: point_first(c), point_end(c+coordinateCount2), qh_qh(qqh), point_dimension(qqh ? qqh->hull_dim : 0) { QHULL_ASSERT(qqh && qqh->hull_dim>0); }
References qhT::hull_dim, and QHULL_ASSERT.
QhullPoints() [8/9]
orgQhull::QhullPoints::QhullPoints (QhullQh * qqh, int pointDimension, countT coordinateCount2, coordT * c)
: point_first(c)
, point_end(c+coordinateCount2)
, qh_qh(qqh)
, point_dimension(pointDimension)
{
    QHULL_ASSERT(pointDimension>=0);
    QHULL_ASSERT(coordinateCount2>=0);
}//QhullPoints QhullQh dim coordT
References QHULL_ASSERT.
QhullPoints() [9/9]
orgQhull::QhullPoints::QhullPoints (const QhullPoints & other) inline
Copy constructor copies pointers but not contents. Needed for return by value and parameter passing.
: point_first(other.point_first), point_end(other.point_end), qh_qh(other.qh_qh), point_dimension(other.point_dimension) {}
~QhullPoints()
orgQhull::QhullPoints::~QhullPoints () inline
{}
Member Function Documentation
at()
const QhullPoint orgQhull::QhullPoints::at (countT idx) const inline
{ /* point_first==0 caught by point_end assert */ coordT *p= point_first+idx*point_dimension; QHULL_ASSERT(p<point_end); return QhullPoint(qh_qh, point_dimension, p); }
References coordT, point_dimension, point_end, point_first, qh_qh, and QHULL_ASSERT.
Referenced by operator[](), orgQhull::PointCoordinates_test::t_element(), and orgQhull::QhullPoints_test::t_element().
back() [1/2]
QhullPoint orgQhull::QhullPoints::back () inline
{ return last(); }
References last().
back() [2/2]
const QhullPoint orgQhull::QhullPoints::back () const inline
{ return last(); }
References last().
Referenced by orgQhull::PointCoordinates_test::t_element(), and orgQhull::QhullPoints_test::t_element().
begin() [1/2]
Iterator orgQhull::QhullPoints::begin () inline
{ return Iterator(*this); }
begin() [2/2]
ConstIterator orgQhull::QhullPoints::begin () const inline
{ return ConstIterator(*this); }
Referenced by contains(), count(), indexOf(), lastIndexOf(), operator<<(), operator==(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinates_test::t_foreach(), and orgQhull::QhullPoints_test::t_iterator().
constBegin()
ConstIterator orgQhull::QhullPoints::constBegin () const inline
{ return ConstIterator(*this); }
Referenced by orgQhull::PointCoordinatesIterator::findPrevious(), orgQhull::QhullPointsIterator::findPrevious(), orgQhull::PointCoordinatesIterator::hasPrevious(), orgQhull::QhullPointsIterator::hasPrevious(), orgQhull::PointCoordinatesIterator::operator=(), orgQhull::QhullPointsIterator::operator=(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinatesIterator::toFront(), and orgQhull::QhullPointsIterator::toFront().
constData()
const coordT * orgQhull::QhullPoints::constData () const inline
{ return point_first; }
References point_first.
Referenced by orgQhull::PointCoordinates_test::t_convert(), and orgQhull::QhullPoints_test::t_convert().
constEnd()
ConstIterator orgQhull::QhullPoints::constEnd () const inline
{ return ConstIterator(qh_qh, point_dimension, point_end); }
References point_dimension, point_end, and qh_qh.
Referenced by orgQhull::PointCoordinatesIterator::findNext(), orgQhull::QhullPointsIterator::findNext(), orgQhull::PointCoordinatesIterator::hasNext(), orgQhull::QhullPointsIterator::hasNext(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinates_test::t_foreach(), orgQhull::PointCoordinatesIterator::toBack(), and orgQhull::QhullPointsIterator::toBack().
contains()
bool orgQhull::QhullPoints::contains (const QhullPoint & t) const
{
    const_iterator i= begin();
    while(i != end()){
        if(*i==t){
            return true;
        }
        i++;
    }
    return false;
}//contains
References begin(), and end().
Referenced by orgQhull::PointCoordinates_test::t_search(), and orgQhull::QhullPoints_test::t_search().
coordinateCount()
countT orgQhull::QhullPoints::coordinateCount () const inline
{ return (countT)(point_end-point_first); } // WARN64
References point_end, and point_first.
Referenced by orgQhull::PointCoordinates::append(), orgQhull::PointCoordinates::checkValid(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullPoints_test::t_getset(), and orgQhull::QhullPoints_test::t_search().
coordinates()
coordT * orgQhull::QhullPoints::coordinates () const inline
{ return point_first; }
References point_first.
Referenced by orgQhull::RboxPoints::appendPoints(), orgQhull::Qhull::runQhull(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullPoints_test::t_getset(), and orgQhull::QhullPoints_test::t_iterator().
count() [1/2]
countT orgQhull::QhullPoints::count () const inline
{ return (countT)size(); } // WARN64
References size().
Referenced by orgQhull::RboxPoints::appendPoints(), orgQhull::PointCoordinates::checkValid(), lastIndexOf(), mid(), operator<<(), orgQhull::RboxPoints::reservePoints(), orgQhull::Qhull::runQhull(), orgQhull::PointCoordinates_test::t_append_points(), orgQhull::RboxPoints_test::t_change(), orgQhull::RboxPoints_test::t_construct(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullPoints_test::t_element(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullPoints_test::t_getset(), orgQhull::RboxPoints_test::t_getSet(), orgQhull::PointCoordinates_test::t_modify(), orgQhull::PointCoordinates_test::t_search(), orgQhull::QhullPoints_test::t_search(), value(), and value().
count() [2/2]
countT orgQhull::QhullPoints::count (const QhullPoint & t) const
{
    countT n= 0;
    const_iterator i= begin();
    while(i != end()){
        if(*i==t){
            ++n;
        }
        i++;
    }
    return n;
}//count
References begin(), end(), and n.
data() [1/2]
coordT * orgQhull::QhullPoints::data () inline
{ return point_first; }
References point_first.
data() [2/2]
const coordT * orgQhull::QhullPoints::data () const inline
{ return point_first; }
References point_first.
Referenced by orgQhull::PointCoordinates::append(), orgQhull::PointCoordinates::checkValid(), orgQhull::PointCoordinates_test::t_convert(), orgQhull::QhullPoints_test::t_convert(), orgQhull::QhullPoints_test::t_getset(), and orgQhull::QhullPoints_test::t_search().
defineAs() [1/3]
void orgQhull::QhullPoints::defineAs (const QhullPoints & other) inline
{ point_first= other.point_first; point_end= other.point_end; qh_qh= other.qh_qh; point_dimension= other.point_dimension; }
References point_dimension, point_end, point_first, and qh_qh.
defineAs() [2/3]
void orgQhull::QhullPoints::defineAs (countT coordinatesCount, coordT * c) inline
{ QHULL_ASSERT((point_dimension>0 && coordinatesCount>=0 && c!=0) || (c==0 && coordinatesCount==0)); point_first= c; point_end= c+coordinatesCount; }
References point_dimension, point_end, point_first, and QHULL_ASSERT.
defineAs() [3/3]
void orgQhull::QhullPoints::defineAs (int pointDimension, countT coordinatesCount, coordT * c) inline
{ QHULL_ASSERT(pointDimension>=0 && coordinatesCount>=0 && c!=0); point_first= c; point_end= c+coordinatesCount; point_dimension= pointDimension; }
References point_dimension, point_end, point_first, and QHULL_ASSERT.
Referenced by orgQhull::PointCoordinates::defineAs(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_qh(), and orgQhull::QhullPoints_test::t_getset().
dimension()
int orgQhull::QhullPoints::dimension () const inline
{ return point_dimension; }
References point_dimension.
Referenced by orgQhull::PointCoordinates::append(), orgQhull::PointCoordinates::indexOffset(), operator<<(), orgQhull::RboxPoints::reservePoints(), orgQhull::Qhull::runQhull(), orgQhull::PointCoordinates::setDimension(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::RboxPoints_test::t_construct(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::PointCoordinates_test::t_convert(), orgQhull::QhullPoints_test::t_convert(), orgQhull::QhullPoints_test::t_getset(), orgQhull::RboxPoints_test::t_getSet(), and orgQhull::QhullPoints_test::t_iterator().
end() [1/2]
Iterator orgQhull::QhullPoints::end () inline
{ return Iterator(qh_qh, point_dimension, point_end); }
References point_dimension, point_end, and qh_qh.
end() [2/2]
ConstIterator orgQhull::QhullPoints::end () const inline
{ return ConstIterator(qh_qh, point_dimension, point_end); }
References point_dimension, point_end, and qh_qh.
Referenced by contains(), count(), indexOf(), lastIndexOf(), operator<<(), operator==(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinates_test::t_foreach(), and orgQhull::QhullPoints_test::t_iterator().
extraCoordinates()
coordT * orgQhull::QhullPoints::extraCoordinates () const inline
{ return extraCoordinatesCount() ? (point_end-extraCoordinatesCount()) : 0; }
References extraCoordinatesCount(), and point_end.
Referenced by orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), and orgQhull::QhullPoints_test::t_getset().
extraCoordinatesCount()
countT orgQhull::QhullPoints::extraCoordinatesCount () const
{
    if(point_dimension>0){
        return (countT)((point_end-point_first)%(size_t)point_dimension);
    }
    return 0;
}//extraCoordinatesCount
References point_dimension, point_end, and point_first.
Referenced by orgQhull::RboxPoints::appendPoints(), extraCoordinates(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_getset(), and orgQhull::PointCoordinates_test::t_modify().
first() [1/2]
QhullPoint orgQhull::QhullPoints::first () inline
{ return QhullPoint(qh_qh, point_dimension, point_first); }
References point_dimension, point_first, and qh_qh.
first() [2/2]
const QhullPoint orgQhull::QhullPoints::first () const inline
{ return QhullPoint(qh_qh, point_dimension, point_first); }
References point_dimension, point_first, and qh_qh.
Referenced by front(), front(), orgQhull::PointCoordinates_test::t_element(), orgQhull::QhullPoints_test::t_element(), orgQhull::PointCoordinates_test::t_modify(), and orgQhull::QhullPoints_test::t_search().
front() [1/2]
QhullPoint orgQhull::QhullPoints::front () inline
{ return first(); }
References first().
front() [2/2]
const QhullPoint orgQhull::QhullPoints::front () const inline
{ return first(); }
References first().
Referenced by orgQhull::QhullPoints_test::t_element().
includesCoordinates()
bool orgQhull::QhullPoints::includesCoordinates (const coordT * c) const inline
{ return c>=point_first && c<point_end; }
References point_end, and point_first.
Referenced by orgQhull::PointCoordinates::append(), indexOf(), indexOf(), and orgQhull::QhullPoints_test::t_getset().
indexOf() [1/3]
countT orgQhull::QhullPoints::indexOf (const coordT * pointCoordinates) const
{
    if(!includesCoordinates(pointCoordinates) || point_dimension==0){
        return -1;
    }
    size_t offset= pointCoordinates-point_first;
    countT idx= (countT)(offset/(size_t)point_dimension);
    countT extra= (countT)(offset%(size_t)point_dimension);
    if(extra!=0){
        throw QhullError(10066, "Qhull error: coordinates %x are not at point boundary (extra %d at index %d)", extra, idx, 0.0, pointCoordinates);
    }
    return idx;
}//indexOf coordT
References includesCoordinates(), point_dimension, and point_first.
Referenced by orgQhull::PointCoordinates::append(), indexOf(), orgQhull::PointCoordinates_test::t_search(), and orgQhull::QhullPoints_test::t_search().
indexOf() [2/3]
countT orgQhull::QhullPoints::indexOf (const coordT * pointCoordinates, int noThrow) const
{
    size_t extra= 0;
    if(noThrow){
        if(!includesCoordinates(pointCoordinates) || point_dimension==0){
            return -1;
        }
        extra= (pointCoordinates-point_first)%(size_t)point_dimension;
    }
    return indexOf(pointCoordinates-extra);
}//indexOf coordT noThrow
References includesCoordinates(), indexOf(), point_dimension, and point_first.
indexOf() [3/3]
countT orgQhull::QhullPoints::indexOf (const QhullPoint & t) const
{
    countT j=0;
    const_iterator i= begin();
    while(i!=end()){
        if(*i==t){
            return j;
        }
        ++i;
        ++j;
    }
    return -1;
}//indexOf
References begin(), and end().
isEmpty()
bool orgQhull::QhullPoints::isEmpty () const inline
{ return (point_end==point_first || point_dimension==0); }
References point_dimension, point_end, and point_first.
Referenced by orgQhull::RboxPoints::rboxMessage(), orgQhull::RboxPoints_test::t_construct(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullPoints_test::t_element(), and orgQhull::QhullPoints_test::t_getset().
last() [1/2]
QhullPoint orgQhull::QhullPoints::last () inline
{ QHULL_ASSERT(point_first!=0); return QhullPoint(qh_qh, point_dimension, point_end - point_dimension); }
References point_dimension, point_end, point_first, qh_qh, and QHULL_ASSERT.
last() [2/2]
const QhullPoint orgQhull::QhullPoints::last () const inline
{ QHULL_ASSERT(point_first!=0); return QhullPoint(qh_qh, point_dimension, point_end - point_dimension); }
References point_dimension, point_end, point_first, qh_qh, and QHULL_ASSERT.
Referenced by back(), back(), orgQhull::PointCoordinates_test::t_element(), orgQhull::QhullPoints_test::t_element(), orgQhull::PointCoordinates_test::t_modify(), and orgQhull::QhullPoints_test::t_search().
lastIndexOf()
countT orgQhull::QhullPoints::lastIndexOf (const QhullPoint & t) const
{
    countT j= count();
    const_iterator i= end();
    while(i != begin()){
        --i;
        --j;
        if(*i==t){
            return j;
        }
    }
    return -1;
}//lastIndexOf
References begin(), count(), and end().
Referenced by orgQhull::PointCoordinates_test::t_modify(), orgQhull::PointCoordinates_test::t_search(), and orgQhull::QhullPoints_test::t_search().
mid()
QhullPoints orgQhull::QhullPoints::mid (countT idx, countT length = -1) const
Returns a subset of the points, not a copy.
{
    countT n= count();
    if(idx<0 || idx>=n){
        n= 0;
    }else if(length<0 || idx+length>=n){
        n -= idx;
    }else{
        n -= idx+length;
    }
    return QhullPoints(qh_qh, point_dimension, n*point_dimension, point_first+idx*point_dimension);
}//mid
References QhullPoints(), count(), length(), n, point_dimension, point_first, and qh_qh.
Referenced by orgQhull::PointCoordinates_test::t_element(), and orgQhull::QhullPoints_test::t_element().
operator!=()
bool orgQhull::QhullPoints::operator!= (const QhullPoints & other) const inline
{ return ! operator==(other); }
References operator==().
operator=()
QhullPoints & orgQhull::QhullPoints::operator= (const QhullPoints & other) inline
{ point_first= other.point_first; point_end= other.point_end; qh_qh= other.qh_qh; point_dimension= other.point_dimension; return *this; }
References point_dimension, point_end, point_first, and qh_qh.
Referenced by orgQhull::PointCoordinates::operator=().
operator==()
bool orgQhull::QhullPoints::operator== (const QhullPoints & other) const
QhullPoints is equal if the same address, or if the coordinates are identical Use QhullPoint.operator==() for DISTround equality.
{
    if((point_end-point_first) != (other.point_end-other.point_first)){
        return false;
    }
    if(point_dimension!=other.point_dimension){
        return false;
    }
    if(point_first==other.point_first){
        return true;
    }
    if(!qh_qh || qh_qh->hull_dim==0){
        const coordT *c= point_first;
        const coordT *c2= other.point_first;
        while(c<point_end){
            if(*c++!=*c2++){
                return false;
            }
        }
    }else{
        const_iterator i= begin();
        const_iterator i2= other.begin();
        while(i<end()){
            if(*i++!=*i2++){
                return false;
            }
        }
    }
    return true;
}//operator==
References begin(), coordT, end(), qhT::hull_dim, point_dimension, point_end, point_first, and qh_qh.
Referenced by operator!=().
operator[]()
QhullPoint orgQhull::QhullPoints::operator[] (countT idx) const inline
{ return at(idx); }
References at().
print()
PrintPoints orgQhull::QhullPoints::print (const char * message) const inline
{ return PrintPoints(message, false, *this); }
Referenced by orgQhull::QhullPoints_test::t_io().
printWithIdentifier()
PrintPoints orgQhull::QhullPoints::printWithIdentifier (const char * message) const inline
{ return PrintPoints(message, true, *this); }
Referenced by orgQhull::QhullPoints_test::t_io().
qh()
QhullQh * orgQhull::QhullPoints::qh () const inline
{ return qh_qh; }
References qh_qh.
Referenced by orgQhull::RboxPoints::~RboxPoints(), orgQhull::RboxPoints::appendPoints(), and orgQhull::RboxPoints_test::t_getSet().
resetQhullQh()
void orgQhull::QhullPoints::resetQhullQh (QhullQh * qqh)
Reset QhullPoints to QhullQh and its hullDimension() Does not free up old qh_qh.
{
    qh_qh= qqh;
    point_dimension= (qqh ? qqh->hull_dim : 0);
    point_first= 0;
    point_end= 0;
}//resetQhullQh
References qhT::hull_dim, point_dimension, point_end, point_first, and qh_qh.
Referenced by orgQhull::RboxPoints::~RboxPoints(), and orgQhull::RboxPoints::allocateQhullQh().
setDimension()
void orgQhull::QhullPoints::setDimension (int d) inline
{ point_dimension= d; }
References point_dimension.
Referenced by orgQhull::PointCoordinates::setDimension(), and orgQhull::QhullPoints_test::t_getset().
size()
size_t orgQhull::QhullPoints::size () const inline
{ return point_dimension ? (point_end-point_first)/point_dimension : 0; }
References point_dimension, point_end, and point_first.
Referenced by count(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::PointCoordinates_test::t_convert(), orgQhull::QhullPoints_test::t_convert(), and orgQhull::QhullPoints_test::t_getset().
toStdVector()
std::vector< QhullPoint > orgQhull::QhullPoints::toStdVector () const
{
    QhullPointsIterator i(*this);
    std::vector<QhullPoint> vs;
    while(i.hasNext()){
        vs.push_back(i.next());
    }
    return vs;
}//toStdVector
References orgQhull::QhullPointsIterator::hasNext(), and orgQhull::QhullPointsIterator::next().
Referenced by orgQhull::QhullPoints_test::t_convert().
value() [1/2]
QhullPoint orgQhull::QhullPoints::value (countT idx) const
{
    QhullPoint p(qh_qh);
    if(idx>=0 && idx<count()){
        p.defineAs(point_dimension, point_first+idx*point_dimension);
    }
    return p;
}//value
References count(), orgQhull::QhullPoint::defineAs(), point_dimension, point_first, and qh_qh.
Referenced by orgQhull::PointCoordinates_test::t_element(), and orgQhull::QhullPoints_test::t_element().
value() [2/2]
QhullPoint orgQhull::QhullPoints::value (countT idx, QhullPoint & defaultValue) const
{
    QhullPoint p(qh_qh);
    if(idx>=0 && idx<count()){
        p.defineAs(point_dimension, point_first+idx*point_dimension);
    }else{
        p.defineAs(defaultValue);
    }
    return p;
}//value
References count(), orgQhull::QhullPoint::defineAs(), point_dimension, point_first, and qh_qh.
Member Data Documentation
point_dimension
int orgQhull::QhullPoints::point_dimension private
Dimension, >=0.
Referenced by at(), constEnd(), defineAs(), defineAs(), defineAs(), dimension(), end(), end(), extraCoordinatesCount(), first(), first(), indexOf(), indexOf(), isEmpty(), last(), last(), mid(), operator=(), operator==(), resetQhullQh(), setDimension(), size(), value(), and value().
point_end
coordT* orgQhull::QhullPoints::point_end private
End of point coordinates (end>=first). Trailing coordinates ignored.
Referenced by at(), constEnd(), coordinateCount(), defineAs(), defineAs(), defineAs(), end(), end(), extraCoordinates(), extraCoordinatesCount(), includesCoordinates(), isEmpty(), last(), last(), operator=(), operator==(), resetQhullQh(), and size().
point_first
coordT* orgQhull::QhullPoints::point_first private
First coordinate of an array of points of point_dimension.
Referenced by at(), constData(), coordinateCount(), coordinates(), data(), data(), defineAs(), defineAs(), defineAs(), extraCoordinatesCount(), first(), first(), includesCoordinates(), indexOf(), indexOf(), isEmpty(), last(), last(), mid(), operator=(), operator==(), resetQhullQh(), size(), value(), and value().
qh_qh
QhullQh* orgQhull::QhullPoints::qh_qh private
Maybe initialized NULL to allow ownership by RboxPoints qh_qh used for QhullPoint() and qh_qh->hull_dim in constructor.
Referenced by at(), constEnd(), defineAs(), end(), end(), first(), first(), last(), last(), mid(), operator=(), operator==(), qh(), resetQhullQh(), value(), and value().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullPoints.h
src/qhull/src/libqhullcpp/QhullPoints.cpp