OrcaSlicer: Slic3r::GUI::IMSlider Class Reference
Slic3r::GUI::IMSlider Class Reference
#include <src/slic3r/GUI/IMSlider.hpp>
Public Member Functions
IMSlider (int lowerValue, int higherValue, int minValue, int maxValue, long style=wxSL_VERTICAL)
bool init_texture ()
~IMSlider ()
int GetMinValue () const
int GetMaxValue () const
double GetMinValueD ()
double GetMaxValueD ()
int GetLowerValue () const
int GetHigherValue () const
int GetActiveValue () const
double GetLowerValueD ()
double GetHigherValueD ()
SelectedSlider GetSelection ()
void SetLowerValue (const int lower_val)
void SetHigherValue (const int higher_val)
void SetSelectionSpan (const int lower_val, const int higher_val)
void SetMaxValue (const int max_value)
void SetKoefForLabels (const double koef)
void SetSliderValues (const std::vector< double > &values)
void SetSliderAlternateValues (const std::vector< double > &values)
Info GetTicksValues () const
void SetTicksValues (const Info &custom_gcode_per_print_z)
void SetLayersTimes (const std::vector< float > &layers_times, float total_time)
void SetLayersTimes (const std::vector< double > &layers_times)
void SetDrawMode (bool is_sequential_print)
void SetDrawMode (DrawMode mode)
void SetExtraStyle (long style)
void SetManipulationMode (Mode mode)
Mode GetManipulationMode () const
void SetModeAndOnlyExtruder (const bool is_one_extruder_printed_model, const int only_extruder, bool can_change_color)
void SetExtruderColors (const std::vector< std::string > &extruder_colors)
bool IsNewPrint ()
void set_render_as_disabled (bool value)
bool is_rendering_as_disabled () const
bool is_horizontal () const
bool is_one_layer () const
bool is_lower_at_min () const
bool is_higher_at_max () const
bool is_full_span () const
void UseDefaultColors (bool def_colors_on)
void on_mouse_wheel (wxMouseEvent &evt)
void post_ticks_changed_event (Type type=Unknown)
bool check_ticks_changed_event (Type type)
bool switch_one_layer_mode ()
void show_go_to_layer (bool show)
bool render (int canvas_width, int canvas_height)
bool is_dirty ()
void set_as_dirty (bool dirty=true)
bool is_need_post_tick_event ()
void reset_post_tick_event (bool val=false)
Type get_post_tick_event_type ()
void set_scale (float scale=1.0)
void on_change_color_mode (bool is_dark)
void set_menu_enable (bool enable=true)
Public Attributes
float m_scale = 1.0
Protected Member Functions
void add_custom_gcode (std::string custom_gcode)
void add_code_as_tick (Type type, int selected_extruder=-1)
void delete_tick (const TickCode &tick)
void do_go_to_layer (size_t layer_number)
void correct_lower_value ()
void correct_higher_value ()
bool horizontal_slider (const char *str_id, int *v, int v_min, int v_max, const ImVec2 &size, float scale=1.0)
void render_go_to_layer_dialog ()
void render_input_custom_gcode (std::string custom_gcode="")
void render_menu ()
void render_add_menu ()
void render_edit_menu (const TickCode &tick)
void draw_background_and_groove (const ImRect &bg_rect, const ImRect &groove)
void draw_colored_band (const ImRect &groove, const ImRect &slideable_region)
void draw_ticks (const ImRect &slideable_region)
void show_tooltip (const TickCode &tick)
void show_tooltip (const std::string tooltip)
bool vertical_slider (const char *str_id, int *higher_value, int *lower_value, std::string &higher_label, std::string &lower_label, int v_min, int v_max, const ImVec2 &size, SelectedSlider &selection, bool one_layer_flag=false, float scale=1.0f)
bool is_wipe_tower_layer (int tick) const
Private Member Functions
std::string get_label (int tick, LabelType label_type=ltHeightWithLayer)
double get_double_value (const SelectedSlider &selection)
int get_tick_from_value (double value, bool force_lower_bound=false)
float get_pos_from_value (int v_min, int v_max, int value, const ImRect &rect)
std::string get_color_for_tool_change_tick (std::set< TickCode >::const_iterator it) const
std::array< int, 2 > get_active_extruders_for_tick (int tick) const
Private Attributes
bool m_is_dark = false
bool is_osx {false}
int m_min_value
int m_max_value
int m_lower_value
int m_higher_value
bool m_dirty = false
bool m_render_as_disabled { false }
SelectedSlider m_selection
bool m_is_one_layer = false
bool m_menu_enable = true
bool m_show_menu = false
bool m_show_custom_gcode_window = false
bool m_show_go_to_layer_dialog = false
bool m_force_mode_apply = true
bool m_is_wipe_tower = false
bool m_is_spiral_vase = false
void * m_one_layer_on_id
void * m_one_layer_on_hover_id
void * m_one_layer_off_id
void * m_one_layer_off_hover_id
void * m_one_layer_on_light_id
void * m_one_layer_on_hover_light_id
void * m_one_layer_off_light_id
void * m_one_layer_off_hover_light_id
void * m_one_layer_on_dark_id
void * m_one_layer_on_hover_dark_id
void * m_one_layer_off_dark_id
void * m_one_layer_off_hover_dark_id
void * m_pause_icon_id
void * m_custom_icon_id
void * m_delete_icon_id
DrawMode m_draw_mode = dmRegular
Mode m_mode = SingleExtruder
int m_only_extruder = -1
long m_style
long m_extra_style
float m_label_koef {1.0}
float m_zero_layer_height = 0.0f
std::vector< double > m_values
TickCodeInfo m_ticks
std::vector< double > m_layers_times
std::vector< double > m_layers_values
std::vector< std::string > m_extruder_colors
bool m_can_change_color
std::string m_print_obj_idxs
bool m_is_need_post_tick_changed_event { false }
Type m_tick_change_event_type
std::vector< double > m_alternate_values
char m_custom_gcode [1024] = { 0 }
char m_layer_number [64] = { 0 }
Detailed Description
Constructor & Destructor Documentation
IMSlider()
Slic3r::GUI::IMSlider::IMSlider (int lowerValue, int higherValue, int minValue, int maxValue, long style = wxSL_VERTICAL)
{
    m_lower_value  = lowerValue;
    m_higher_value = higherValue;
    m_min_value    = minValue;
    m_max_value    = maxValue;
    m_style        = style == wxSL_HORIZONTAL || style == wxSL_VERTICAL ? style : wxSL_HORIZONTAL;
    // BBS set to none style by default
    m_extra_style = style == wxSL_VERTICAL ? 0 : 0;
    m_selection   = ssHigher;
    m_is_need_post_tick_changed_event = false;
    m_tick_change_event_type = Type::Unknown;
    m_ticks.set_extruder_colors(&m_extruder_colors);
}
References m_extra_style, m_extruder_colors, m_higher_value, m_is_need_post_tick_changed_event, m_lower_value, m_max_value, m_min_value, m_selection, m_style, m_tick_change_event_type, m_ticks, Slic3r::GUI::TickCodeInfo::set_extruder_colors(), Slic3r::GUI::ssHigher, and style.
~IMSlider()
Slic3r::GUI::IMSlider::~IMSlider () inline
{}
Member Function Documentation
add_code_as_tick()
void Slic3r::GUI::IMSlider::add_code_as_tick (Type type, int selected_extruder = -1) protected
{
    if (m_selection == ssUndef) return;
    const int tick = m_selection == ssLower ? m_lower_value : m_higher_value;
    if (!check_ticks_changed_event(type)) {
        BOOST_LOG_TRIVIAL(trace) << "check ticks change event false";
        return;
    }
    if (type == ColorChange && gcode(ColorChange).empty()) GUI::wxGetApp().plater()->get_notification_manager()->push_notification(GUI::NotificationType::EmptyColorChangeCode);
    const int  extruder = selected_extruder > 0 ? selected_extruder : std::max<int>(1, m_only_extruder);
    const auto it       = m_ticks.ticks.find(TickCode{tick});
    if (it == m_ticks.ticks.end()) {
        // try to add tick
        if (!m_ticks.add_tick(tick, type, extruder, m_values[tick])) return;
    } else if (type == ToolChange || type == ColorChange) {
        // try to switch tick code to ToolChange or ColorChange accordingly
        if (!m_ticks.switch_code_for_tick(it, type, extruder)) return;
    } else
        return;
    post_ticks_changed_event(type);
}
References Slic3r::GUI::TickCodeInfo::add_tick(), check_ticks_changed_event(), Slic3r::CustomGCode::ColorChange, Slic3r::empty(), Slic3r::GUI::EmptyColorChangeCode, Slic3r::GUI::gcode(), m_higher_value, m_lower_value, m_only_extruder, m_selection, m_ticks, m_values, post_ticks_changed_event(), Slic3r::GUI::ssLower, Slic3r::GUI::ssUndef, Slic3r::GUI::TickCodeInfo::switch_code_for_tick(), Slic3r::GUI::TickCodeInfo::ticks, Slic3r::CustomGCode::ToolChange, and Slic3r::trace().
Referenced by render_add_menu(), and render_edit_menu().
add_custom_gcode()
void Slic3r::GUI::IMSlider::add_custom_gcode (std::string custom_gcode) protected
{
    if (m_selection == ssUndef) return;
    const int tick = m_selection == ssLower ? m_lower_value : m_higher_value;
    const auto it = m_ticks.ticks.find(TickCode{ tick });
    if (it != m_ticks.ticks.end()) {
        m_ticks.ticks.erase(it);
    }
    m_ticks.ticks.emplace(TickCode{ tick, Custom, std::max<int>(1, m_only_extruder), "", custom_gcode });
    post_ticks_changed_event(Custom);
}
References Slic3r::CustomGCode::Custom, m_higher_value, m_lower_value, m_only_extruder, m_selection, m_ticks, post_ticks_changed_event(), Slic3r::GUI::ssLower, Slic3r::GUI::ssUndef, and Slic3r::GUI::TickCodeInfo::ticks.
Referenced by render_input_custom_gcode().
check_ticks_changed_event()
bool Slic3r::GUI::IMSlider::check_ticks_changed_event (Type type)
{
    //BBL only support MultiExtruder
    if (m_ticks.mode == m_mode || (type != ColorChange && type != ToolChange) ||
        (m_ticks.mode == SingleExtruder && m_mode == MultiAsSingle) || // All ColorChanges will be applied for 1st extruder
        (m_ticks.mode == MultiExtruder && m_mode == MultiAsSingle))    // Just mark ColorChanges for all unused extruders
        return true;
    if ((m_ticks.mode == SingleExtruder && m_mode == MultiExtruder) || (m_ticks.mode == MultiExtruder && m_mode == SingleExtruder)) {
        if (!m_ticks.has_tick_with_code(ColorChange)) return true;
        /*
        wxString message = (m_ticks.mode == SingleExtruder ? _L("The last color change data was saved for a single extruder printing.") :
                                                             _L("The last color change data was saved for a multi extruder printing.")) +
                           "\n" + _L("Your current changes will delete all saved color changes.") + "\n\n\t" + _L("Are you sure you want to continue?");
        GUI::MessageDialog msg(this, message, _L("Notice"), wxYES_NO);
        if (msg.ShowModal() == wxID_YES) {
            m_ticks.erase_all_ticks_with_code(ColorChange);
            post_ticks_changed_event(ColorChange);
        }
        */
        return false;
    }
    return true;
}
References Slic3r::CustomGCode::ColorChange, Slic3r::GUI::TickCodeInfo::has_tick_with_code(), m_mode, m_ticks, Slic3r::GUI::TickCodeInfo::mode, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::MultiExtruder, Slic3r::CustomGCode::SingleExtruder, and Slic3r::CustomGCode::ToolChange.
Referenced by add_code_as_tick().
correct_higher_value()
void Slic3r::GUI::IMSlider::correct_higher_value () protected
{
    if (m_higher_value > m_max_value)
        m_higher_value = m_max_value;
    else if (m_higher_value < m_min_value)
        m_higher_value = m_min_value;
    if ((m_higher_value <= m_lower_value && m_higher_value >= m_min_value) || m_is_one_layer) m_lower_value = m_higher_value;
}
References m_higher_value, m_is_one_layer, m_lower_value, m_max_value, and m_min_value.
Referenced by get_double_value(), SetHigherValue(), and switch_one_layer_mode().
correct_lower_value()
void Slic3r::GUI::IMSlider::correct_lower_value () protected
{
    if (m_lower_value < m_min_value)
        m_lower_value = m_min_value;
    else if (m_lower_value > m_max_value)
        m_lower_value = m_max_value;
    if ((m_lower_value >= m_higher_value && m_lower_value <= m_max_value) || m_is_one_layer) m_higher_value = m_lower_value;
}
References m_higher_value, m_is_one_layer, m_lower_value, m_max_value, and m_min_value.
Referenced by SetLowerValue(), and switch_one_layer_mode().
delete_tick()
void Slic3r::GUI::IMSlider::delete_tick (const TickCode & tick) protected
{
    m_ticks.ticks.erase(tick);
    post_ticks_changed_event(tick.type);
}
References m_ticks, post_ticks_changed_event(), Slic3r::GUI::TickCodeInfo::ticks, and Slic3r::GUI::TickCode::type.
Referenced by draw_ticks(), and render_edit_menu().
do_go_to_layer()
void Slic3r::GUI::IMSlider::do_go_to_layer (size_t layer_number) protected
{
    clamp((int)layer_number, m_min_value, m_max_value);
    GetSelection() == ssLower ? SetLowerValue(layer_number) : SetHigherValue(layer_number);
}
References clamp(), GetSelection(), m_max_value, m_min_value, SetHigherValue(), SetLowerValue(), and Slic3r::GUI::ssLower.
Referenced by render_go_to_layer_dialog().
draw_background_and_groove()
void Slic3r::GUI::IMSlider::draw_background_and_groove (const ImRect & bg_rect, const ImRect & groove) protected
{
    const ImU32 bg_rect_col = m_is_dark ? BACKGROUND_COLOR_DARK : BACKGROUND_COLOR_LIGHT;
    const ImU32 groove_col = m_is_dark ? GROOVE_COLOR_DARK : GROOVE_COLOR_LIGHT;
    // draw bg of slider
    ImGui::RenderFrame(bg_rect.Min, bg_rect.Max, bg_rect_col, false, 0.5 * bg_rect.GetWidth());
    // draw groove
    ImGui::RenderFrame(groove.Min, groove.Max, groove_col, false, 0.5 * groove.GetWidth());
}
References Slic3r::GUI::BACKGROUND_COLOR_DARK, Slic3r::GUI::BACKGROUND_COLOR_LIGHT, ImRect::GetWidth(), Slic3r::GUI::GROOVE_COLOR_DARK, Slic3r::GUI::GROOVE_COLOR_LIGHT, m_is_dark, ImRect::Max, ImRect::Min, and ImGui::RenderFrame().
Referenced by horizontal_slider(), and vertical_slider().
draw_colored_band()
void Slic3r::GUI::IMSlider::draw_colored_band (const ImRect & groove, const ImRect & slideable_region) protected
{
    if (!m_ticks.has_tick_with_code(ToolChange))
        return;
    ImRect main_band = groove;
    auto draw_band = [this](const ImU32& clr, const ImRect& band_rc)
    {
        if (clr == m_is_dark ? BACKGROUND_COLOR_DARK : BACKGROUND_COLOR_LIGHT) {
            ImRect rc = band_rc;
            rc.Min += ImVec2(1, 1) * m_scale;
            rc.Max -= ImVec2(1, 1) * m_scale;
            ImGui::RenderFrame(band_rc.Min, band_rc.Max, m_is_dark ? GROOVE_COLOR_DARK : GROOVE_COLOR_LIGHT, false, band_rc.GetWidth() * 0.5);
            //cover round corner
            ImGui::RenderFrame(ImVec2(band_rc.Min.x, band_rc.Max.y - band_rc.GetWidth() * 0.5), band_rc.Max, m_is_dark ? GROOVE_COLOR_DARK : GROOVE_COLOR_LIGHT, false);
            ImGui::RenderFrame(rc.Min, rc.Max, clr, false, rc.GetWidth() * 0.5);
            //cover round corner
            ImGui::RenderFrame(ImVec2(rc.Min.x, rc.Max.y - rc.GetWidth() * 0.5), rc.Max, clr, false);
        }
        else {
            ImGui::RenderFrame(band_rc.Min, band_rc.Max, clr, false, band_rc.GetWidth() * 0.5);
            //cover round corner
            ImGui::RenderFrame(ImVec2(band_rc.Min.x, band_rc.Max.y - band_rc.GetWidth() * 0.5), band_rc.Max, clr, false);
        }
    };
    auto draw_main_band = [&main_band, this](const ImU32& clr) {
        if (clr == m_is_dark ? BACKGROUND_COLOR_DARK : BACKGROUND_COLOR_LIGHT) {
            ImRect rc = main_band;
            rc.Min += ImVec2(1, 1) * m_scale;
            rc.Max -= ImVec2(1, 1) * m_scale;
            ImGui::RenderFrame(main_band.Min, main_band.Max, m_is_dark ? GROOVE_COLOR_DARK : GROOVE_COLOR_LIGHT, false, main_band.GetWidth() * 0.5);
            ImGui::RenderFrame(rc.Min, rc.Max, clr, false, rc.GetWidth() * 0.5);
        }
        else {
            ImGui::RenderFrame(main_band.Min, main_band.Max, clr, false, main_band.GetWidth() * 0.5);
        }
    };
    //draw main colored band
    const int default_color_idx = m_mode == MultiAsSingle ? std::max<int>(m_only_extruder - 1, 0) : 0;
    std::array<float, 4>rgba = decode_color_to_float_array(m_extruder_colors[default_color_idx]);
    ImU32 band_clr = IM_COL32(rgba[0] * 255.0f, rgba[1] * 255.0f, rgba[2] * 255.0f, rgba[3] * 255.0f);
    draw_main_band(band_clr);
    static float tick_pos;
    std::set<TickCode>::const_iterator tick_it = m_ticks.ticks.begin();
    while (tick_it != m_ticks.ticks.end())
    {
        //get position from tick
        tick_pos = get_pos_from_value(GetMinValue(), GetMaxValue(), tick_it->tick, slideable_region);
        //draw colored band
        if (tick_it->type == ToolChange) {
            if ((m_mode == SingleExtruder) || (m_mode == MultiAsSingle))
            {
                ImRect band_rect = ImRect(main_band.Min, ImVec2(main_band.Max.x, tick_pos));
                const std::string clr_str = m_mode == SingleExtruder ? tick_it->color : get_color_for_tool_change_tick(tick_it);
                if (!clr_str.empty()) {
                    std::array<float, 4>rgba = decode_color_to_float_array(clr_str);
                    ImU32 band_clr = IM_COL32(rgba[0] * 255.0f, rgba[1] * 255.0f, rgba[2] * 255.0f, rgba[3] * 255.0f);
                    if (tick_it->tick == 0)
                        draw_main_band(band_clr);
                    else
                        draw_band(band_clr, band_rect);
                }
            }
        }
        tick_it++;
    }
}
References Slic3r::GUI::BACKGROUND_COLOR_DARK, Slic3r::GUI::BACKGROUND_COLOR_LIGHT, Slic3r::GUI::decode_color_to_float_array(), get_color_for_tool_change_tick(), get_pos_from_value(), GetMaxValue(), GetMinValue(), ImRect::GetWidth(), Slic3r::GUI::GROOVE_COLOR_DARK, Slic3r::GUI::GROOVE_COLOR_LIGHT, Slic3r::GUI::TickCodeInfo::has_tick_with_code(), IM_COL32, m_extruder_colors, m_is_dark, m_mode, m_only_extruder, m_scale, m_ticks, ImRect::Max, ImRect::Min, Slic3r::CustomGCode::MultiAsSingle, ImGui::RenderFrame(), Slic3r::CustomGCode::SingleExtruder, Slic3r::GUI::TickCodeInfo::ticks, Slic3r::CustomGCode::ToolChange, ImVec2::x, and ImVec2::y.
Referenced by vertical_slider().
draw_ticks()
void Slic3r::GUI::IMSlider::draw_ticks (const ImRect & slideable_region) protected
{
    //if(m_draw_mode != dmRegular)
    //    return;
    //if (m_ticks.empty() || m_mode == MultiExtruder)
    //    return;
    if (m_ticks.empty())
        return;
    ImGuiContext &context       = *GImGui;
    ImVec2 tick_box      = ImVec2(52.0f, 16.0f) * m_scale;
    ImVec2 tick_offset   = ImVec2(22.0f, 14.0f) * m_scale;
    float  tick_width    = 1.0f * m_scale;
    ImVec2 icon_offset   = ImVec2(16.0f, 7.0f) * m_scale;
    ImVec2 icon_size     = ImVec2(14.0f, 14.0f) * m_scale;
    const ImU32 tick_clr = IM_COL32(144, 144, 144, 255);
    const ImU32 tick_hover_box_clr = m_is_dark ? IM_COL32(65, 65, 71, 255) : IM_COL32(219, 253, 231, 255);
    auto get_tick_pos = [this, slideable_region](int tick)
    {
        int v_min = GetMinValue();
        int v_max = GetMaxValue();
        return get_pos_from_value(v_min, v_max, tick, slideable_region);
    };
    std::set<TickCode>::const_iterator tick_it = m_ticks.ticks.begin();
    while (tick_it != m_ticks.ticks.end())
    {
        float tick_pos = get_tick_pos(tick_it->tick);
        //draw tick hover box when hovered
        ImRect tick_hover_box = ImRect(slideable_region.GetCenter().x - tick_box.x / 2, tick_pos - tick_box.y / 2, slideable_region.GetCenter().x + tick_box.x / 2,
                                       tick_pos + tick_box.y / 2);
        if (ImGui::IsMouseHoveringRect(tick_hover_box.Min, tick_hover_box.Max))
        {
            // render left tick box
            ImRect left_hover_box = ImRect(tick_hover_box.Min, { slideable_region.Min.x, tick_hover_box.Max.y });
            ImGui::RenderFrame(left_hover_box.Min, left_hover_box.Max, tick_hover_box_clr, false);
            // render right tick box
            ImRect right_hover_box = ImRect({ slideable_region.Max.x, tick_hover_box.Min.y }, tick_hover_box.Max);
            ImGui::RenderFrame(right_hover_box.Min, right_hover_box.Max, tick_hover_box_clr, false);
            show_tooltip(*tick_it);
            if (context.IO.MouseClicked[0]) {
                m_tick_value = tick_it->tick;
                m_tick_rect = ImVec4(tick_hover_box.Min.x, tick_hover_box.Min.y, tick_hover_box.Max.x, tick_hover_box.Max.y);
            }
        }
        ++tick_it;
    }
    tick_it = m_ticks.ticks.begin();
    while (tick_it != m_ticks.ticks.end())
    {
        float tick_pos = get_tick_pos(tick_it->tick);
        //draw ticks
        ImRect tick_left  = ImRect(slideable_region.GetCenter().x - tick_offset.x, tick_pos - tick_width, slideable_region.GetCenter().x - tick_offset.y, tick_pos);
        ImRect tick_right = ImRect(slideable_region.GetCenter().x + tick_offset.y, tick_pos - tick_width, slideable_region.GetCenter().x + tick_offset.x, tick_pos);
        ImGui::RenderFrame(tick_left.Min, tick_left.Max, tick_clr, false);
        ImGui::RenderFrame(tick_right.Min, tick_right.Max, tick_clr, false);
        //draw pause icon
        if (tick_it->type == PausePrint) {
            ImTextureID pause_icon_id = m_pause_icon_id;
            ImVec2      icon_pos     = ImVec2(slideable_region.GetCenter().x + icon_offset.x, tick_pos - icon_offset.y);
            button_with_pos(pause_icon_id, icon_size, icon_pos);
        }
        if (tick_it->type == Custom || tick_it->type == Template) {
            ImTextureID custom_icon_id = m_custom_icon_id;
            ImVec2      icon_pos = ImVec2(slideable_region.GetCenter().x + icon_offset.x, tick_pos - icon_offset.y);
            button_with_pos(custom_icon_id, icon_size, icon_pos);
        }
        ++tick_it;
    }
    tick_it = GetSelection() == ssHigher ? m_ticks.ticks.find(TickCode{this->GetHigherValue()}) :
              GetSelection() == ssLower  ? m_ticks.ticks.find(TickCode{this->GetLowerValue()}) :
                                           m_ticks.ticks.end();
    if (tick_it != m_ticks.ticks.end()) {
        // draw delete icon
        ImVec2      icon_pos       = ImVec2(slideable_region.GetCenter().x + icon_offset.x, get_tick_pos(tick_it->tick) - icon_offset.y);
        button_with_pos(m_delete_icon_id, icon_size, icon_pos);
        if (ImGui::IsMouseHoveringRect(icon_pos, icon_pos + icon_size)) {
            if (context.IO.MouseClicked[0]) {
                // delete tick
                delete_tick(*tick_it);
            }
        }
    }
}
References Slic3r::GUI::button_with_pos(), Slic3r::CustomGCode::Custom, delete_tick(), Slic3r::GUI::TickCodeInfo::empty(), get_pos_from_value(), ImRect::GetCenter(), GetHigherValue(), GetLowerValue(), GetMaxValue(), GetMinValue(), GetSelection(), GImGui, IM_COL32, ImGuiContext::IO, ImGui::IsMouseHoveringRect(), m_custom_icon_id, m_delete_icon_id, m_is_dark, m_pause_icon_id, m_scale, Slic3r::GUI::m_tick_rect, Slic3r::GUI::m_tick_value, m_ticks, ImRect::Max, ImRect::Min, ImGuiIO::MouseClicked, Slic3r::CustomGCode::PausePrint, ImGui::RenderFrame(), show_tooltip(), Slic3r::GUI::ssHigher, Slic3r::GUI::ssLower, Slic3r::CustomGCode::Template, Slic3r::GUI::TickCodeInfo::ticks, ImVec2::x, and ImVec2::y.
Referenced by vertical_slider().
get_active_extruders_for_tick()
std::array< int, 2 > Slic3r::GUI::IMSlider::get_active_extruders_for_tick (int tick) const private
{
    int                default_initial_extruder = m_mode == MultiAsSingle ? std::max<int>(1, m_only_extruder) : 1;
    std::array<int, 2> extruders                = {default_initial_extruder, -1};
    if (m_ticks.empty()) return extruders;
    auto it = m_ticks.ticks.lower_bound(TickCode{tick});
    if (it != m_ticks.ticks.end() && it->tick == tick) // current tick exists
        extruders[1] = it->extruder;
    while (it != m_ticks.ticks.begin()) {
        --it;
        if (it->type == ToolChange) {
            extruders[0] = it->extruder;
            break;
        }
    }
    return extruders;
}
References Slic3r::GUI::TickCodeInfo::empty(), m_mode, m_only_extruder, m_ticks, Slic3r::CustomGCode::MultiAsSingle, Slic3r::GUI::TickCodeInfo::ticks, and Slic3r::CustomGCode::ToolChange.
get_color_for_tool_change_tick()
std::string Slic3r::GUI::IMSlider::get_color_for_tool_change_tick (std::set< TickCode >::const_iterator it) const private
{
    const int current_extruder = it->extruder == 0 ? std::max<int>(m_only_extruder, 1) : it->extruder;
    auto it_n = it;
    while (it_n != m_ticks.ticks.begin()) {
        --it_n;
        if (it_n->type == ColorChange && it_n->extruder == current_extruder)
            return it_n->color;
    }
    if ((current_extruder > 0 && (current_extruder - 1) < m_extruder_colors.size()))
    {
        return m_extruder_colors[current_extruder - 1]; // return a color for a specific extruder from the colors list
    }
    return "";
}
References Slic3r::CustomGCode::ColorChange, m_extruder_colors, m_only_extruder, m_ticks, and Slic3r::GUI::TickCodeInfo::ticks.
Referenced by draw_colored_band().
get_double_value()
double Slic3r::GUI::IMSlider::get_double_value (const SelectedSlider & selection) private
{
    if (m_values.empty() || m_lower_value < 0) return 0.0;
    if (m_values.size() <= size_t(m_higher_value)) {
        correct_higher_value();
        return m_values.back();
    }
    return m_values[selection == ssLower ? m_lower_value : m_higher_value];
}
References correct_higher_value(), m_higher_value, m_lower_value, m_values, and Slic3r::GUI::ssLower.
Referenced by GetHigherValueD(), and GetLowerValueD().
get_label()
std::string Slic3r::GUI::IMSlider::get_label (int tick, LabelType label_type = ltHeightWithLayer) private
{
    const size_t value = tick;
    if (m_label_koef == 1.0 && m_values.empty()) {
        std::to_string(value);
    }
    if (value >= m_values.size()) return "error";
    auto get_layer_number = [this](int value, LabelType label_type) {
        if (label_type == ltEstimatedTime && m_layers_times.empty()) return size_t(-1);
        double layer_print_z = m_values[is_wipe_tower_layer(value) ? std::max<int>(value - 1, 0) : value];
        auto   it            = std::lower_bound(m_layers_values.begin(), m_layers_values.end(), layer_print_z - epsilon());
        if (it == m_layers_values.end()) {
            it = std::lower_bound(m_values.begin(), m_values.end(), layer_print_z - epsilon());
            if (it == m_values.end()) return size_t(-1);
            return size_t(value);
        }
        return size_t(it - m_layers_values.begin());
    };
    if (m_draw_mode == dmSequentialGCodeView) {
        return std::to_string(tick);
    } else {
        if (label_type == ltEstimatedTime) {
            if (m_is_wipe_tower) {
                size_t layer_number = get_layer_number(value, label_type);
                return (layer_number == size_t(-1) || layer_number == m_layers_times.size()) ? "" : short_and_splitted_time(get_time_dhms(m_layers_times[layer_number]));
            }
            return value < m_layers_times.size() ? short_and_splitted_time(get_time_dhms(m_layers_times[value])) : "";
        }
        char layer_height[64];
        ::sprintf(layer_height, "%.2f", m_values.empty() ? m_label_koef * value : m_values[value]);
        if (label_type == ltHeight) return std::string(layer_height);
        if (label_type == ltHeightWithLayer) {
            char   buffer[64];
            size_t layer_number;
            layer_number = m_draw_mode == dmSequentialFffPrint ? (m_values.empty() ? value : value + 1) : m_is_wipe_tower ? get_layer_number(value, label_type) + 1 : (m_values.empty() ? value : value + 1);
            ::sprintf(buffer, "%5s\n%5s", std::to_string(layer_number).c_str(), layer_height);
            return std::string(buffer);
        }
    }
    return "";
}
References buffer, Slic3r::GUI::dmSequentialFffPrint, Slic3r::GUI::dmSequentialGCodeView, Slic3r::GUI::epsilon(), Slic3r::get_time_dhms(), is_wipe_tower_layer(), Slic3r::GUI::layer_height, Slic3r::GUI::ltEstimatedTime, Slic3r::GUI::ltHeight, Slic3r::GUI::ltHeightWithLayer, m_draw_mode, m_is_wipe_tower, m_label_koef, m_layers_times, m_layers_values, m_values, and Slic3r::GUI::short_and_splitted_time().
Referenced by render().
get_pos_from_value()
float Slic3r::GUI::IMSlider::get_pos_from_value (int v_min, int v_max, int value, const ImRect & rect) private
{
    float pos_ratio = (v_max - v_min) != 0 ? ((float)(value - v_min) / (float)(v_max - v_min)) : 0.0f;
    float handle_pos;
    if (is_horizontal()) {
        handle_pos = rect.Min.x + (rect.Max.x - rect.Min.x) * pos_ratio;
    }
    else {
        pos_ratio = 1.0f - pos_ratio;
        handle_pos = rect.Min.y + (rect.Max.y - rect.Min.y) * pos_ratio;
    }
    return handle_pos;
}
References is_horizontal(), ImRect::Max, ImRect::Min, ImVec2::x, and ImVec2::y.
Referenced by draw_colored_band(), draw_ticks(), horizontal_slider(), and vertical_slider().
get_post_tick_event_type()
Type Slic3r::GUI::IMSlider::get_post_tick_event_type () inline
{ return m_tick_change_event_type; }
References m_tick_change_event_type.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode().
get_tick_from_value()
int Slic3r::GUI::IMSlider::get_tick_from_value (double value, bool force_lower_bound = false) private
{
    std::vector<double>::iterator it;
    if (m_is_wipe_tower && !force_lower_bound)
        it = std::find_if(m_values.begin(), m_values.end(), [value](const double &val) { return fabs(value - val) <= epsilon(); });
    else
        it = std::lower_bound(m_values.begin(), m_values.end(), value - epsilon());
    if (it == m_values.end()) return -1;
    return int(it - m_values.begin());
}
References Slic3r::GUI::epsilon(), int, m_is_wipe_tower, and m_values.
Referenced by SetTicksValues().
GetActiveValue()
int Slic3r::GUI::IMSlider::GetActiveValue () const
{
    return m_selection == ssLower ?
    m_lower_value : m_selection == ssHigher ?
                m_higher_value : -1;
}
References m_higher_value, m_lower_value, m_selection, Slic3r::GUI::ssHigher, and Slic3r::GUI::ssLower.
GetHigherValue()
int Slic3r::GUI::IMSlider::GetHigherValue () const inline
{ return m_higher_value; }
References m_higher_value.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode(), draw_ticks(), Slic3r::GUI::GLCanvas3D::on_key(), on_mouse_wheel(), render(), and render_menu().
GetHigherValueD()
double Slic3r::GUI::IMSlider::GetHigherValueD () inline
{ return get_double_value(ssHigher); }
References get_double_value(), and Slic3r::GUI::ssHigher.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode(), and Slic3r::GUI::Preview::update_layers_slider().
GetLowerValue()
int Slic3r::GUI::IMSlider::GetLowerValue () const inline
{ return m_lower_value; }
References m_lower_value.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode(), draw_ticks(), Slic3r::GUI::GLCanvas3D::on_key(), on_mouse_wheel(), render(), and render_menu().
GetLowerValueD()
double Slic3r::GUI::IMSlider::GetLowerValueD () inline
{ return get_double_value(ssLower); }
References get_double_value(), and Slic3r::GUI::ssLower.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode(), and Slic3r::GUI::Preview::update_layers_slider().
GetManipulationMode()
Mode Slic3r::GUI::IMSlider::GetManipulationMode () const inline
{ return m_mode; }
References m_mode.
GetMaxValue()
int Slic3r::GUI::IMSlider::GetMaxValue () const inline
{ return m_max_value; }
References m_max_value.
Referenced by draw_colored_band(), draw_ticks(), render(), Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::GUI::GCodeViewer::update_moves_slider().
GetMaxValueD()
double Slic3r::GUI::IMSlider::GetMaxValueD () inline
{ return m_values.empty() ? 0. : m_values[m_max_value]; }
References m_max_value, and m_values.
Referenced by Slic3r::GUI::Preview::update_layers_slider().
GetMinValue()
int Slic3r::GUI::IMSlider::GetMinValue () const inline
{ return m_min_value; }
References m_min_value.
Referenced by draw_colored_band(), draw_ticks(), render(), and Slic3r::GUI::Preview::update_layers_slider().
GetMinValueD()
double Slic3r::GUI::IMSlider::GetMinValueD () inline
{ return m_values.empty() ? 0. : m_values[m_min_value]; }
References m_min_value, and m_values.
GetSelection()
SelectedSlider Slic3r::GUI::IMSlider::GetSelection () inline
{ return m_selection; }
References m_selection.
Referenced by do_go_to_layer(), draw_ticks(), Slic3r::GUI::GLCanvas3D::on_key(), and render_menu().
GetTicksValues()
Info Slic3r::GUI::IMSlider::GetTicksValues () const
{
    Info                            custom_gcode_per_print_z;
    std::vector<CustomGCode::Item> &values = custom_gcode_per_print_z.gcodes;
    const int val_size = m_values.size();
    if (!m_values.empty())
        for (const TickCode &tick : m_ticks.ticks) {
            if (tick.tick > val_size) break;
            values.emplace_back(CustomGCode::Item{m_values[tick.tick], tick.type, tick.extruder, tick.color, tick.extra});
        }
    if (m_force_mode_apply) custom_gcode_per_print_z.mode = m_mode;
    return custom_gcode_per_print_z;
}
References Slic3r::custom_gcode_per_print_z, Slic3r::CustomGCode::Info::gcodes, m_force_mode_apply, m_mode, m_ticks, m_values, Slic3r::CustomGCode::Info::mode, and Slic3r::GUI::TickCodeInfo::ticks.
horizontal_slider()
bool Slic3r::GUI::IMSlider::horizontal_slider (const char * str_id, int * v, int v_min, int v_max, const ImVec2 & size, float scale = 1.0) protected
{
    ImGuiWindow* window = ImGui::GetCurrentWindow();
    if (window->SkipItems)
        return false;
    ImGuiContext& context = *GImGui;
    const ImGuiID id = window->GetID(str_id);
    const ImVec2 pos = window->DC.CursorPos;
    const ImRect draw_region(pos, pos + size);
    ImGui::ItemSize(draw_region);
    const float  handle_dummy_width  = 10.0f * m_scale;
    const float  text_right_dummy    = 50.0f * scale * m_scale;
    const float  handle_radius       = 12.0f * m_scale;
    const float  handle_border       = 2.0f * m_scale;
    const float  text_frame_rounding = 2.0f * scale * m_scale;
    const float  text_start_offset   = 8.0f * m_scale;
    const ImVec2 text_padding        = ImVec2(5.0f, 2.0f) * m_scale;
    const float  triangle_offsets[3] = {-3.5f * m_scale, 3.5f * m_scale, -6.06f * m_scale};
    const ImU32 white_bg = m_is_dark ? BACKGROUND_COLOR_DARK : BACKGROUND_COLOR_LIGHT;
    const ImU32 handle_clr = BRAND_COLOR;
    const ImU32 handle_border_clr = m_is_dark ? BACKGROUND_COLOR_DARK : BACKGROUND_COLOR_LIGHT;
    // calculate groove size
    const ImVec2 groove_start = ImVec2(pos.x + handle_dummy_width, pos.y + size.y - ONE_LAYER_MARGIN.y * m_scale - ONE_LAYER_BUTTON_SIZE.y * m_scale * 0.5f - GROOVE_WIDTH * m_scale * 0.5f);
    const ImVec2 groove_size = ImVec2(size.x - 2 * handle_dummy_width - text_right_dummy, GROOVE_WIDTH * m_scale);
    const ImRect groove = ImRect(groove_start, groove_start + groove_size);
    const ImRect bg_rect = ImRect(groove.Min - ImVec2(6.0f, 6.0f) * m_scale, groove.Max + ImVec2(6.0f, 6.0f) * m_scale);
    const float mid_y = groove.GetCenter().y;
    // set mouse active region. active region.
    bool  hovered = ImGui::ItemHoverable(draw_region, id);
    if (hovered && context.IO.MouseDown[0]) {
        ImGui::SetActiveID(id, window);
        ImGui::SetFocusID(id, window);
        ImGui::FocusWindow(window);
    }
    // draw background
    draw_background_and_groove(bg_rect, groove);
    // set scrollable region
    const ImRect slideable_region = ImRect(bg_rect.Min + ImVec2(handle_radius, 0.0f), bg_rect.Max - ImVec2(handle_radius, 0.0f));
    // initialize the handle
    float  handle_pos = get_pos_from_value(v_min, v_max, *value, groove);
    ImRect handle = ImRect(handle_pos - handle_radius, mid_y - handle_radius, handle_pos + handle_radius, mid_y + handle_radius);
    // update handle position and value
    bool   value_changed = slider_behavior(id, slideable_region, (const ImS32) v_min, (const ImS32) v_max, (ImS32 *) value, &handle);
    ImVec2 handle_center = handle.GetCenter();
    // draw scroll line
    ImRect scroll_line = ImRect(groove.Min, ImVec2(handle_center.x, groove.Max.y));
    window->DrawList->AddRectFilled(scroll_line.Min, scroll_line.Max, handle_clr, 0.5f * GROOVE_WIDTH * m_scale);
    // draw handle
    window->DrawList->AddCircleFilled(handle_center, handle_radius, handle_border_clr);
    window->DrawList->AddCircleFilled(handle_center, handle_radius - handle_border, handle_clr);
    // draw label
    auto text_utf8 = into_u8(std::to_string(*value));
    ImVec2 text_content_size = ImGui::CalcTextSize(text_utf8.c_str());
    ImVec2 text_size = text_content_size + text_padding * 2;
    ImVec2 text_start = ImVec2(handle_center.x + handle_radius + text_start_offset, handle_center.y - 0.5 * text_size.y);
    ImRect text_rect(text_start, text_start + text_size);
    ImGui::RenderFrame(text_rect.Min, text_rect.Max, white_bg, false, text_frame_rounding);
    ImVec2 pos_1 = ImVec2(text_rect.Min.x, text_rect.GetCenter().y + triangle_offsets[0]);
    ImVec2 pos_2 = ImVec2(text_rect.Min.x, text_rect.GetCenter().y + triangle_offsets[1]);
    ImVec2 pos_3 = ImVec2(text_rect.Min.x + triangle_offsets[2], text_rect.GetCenter().y);
    window->DrawList->AddTriangleFilled(pos_1, pos_2, pos_3, white_bg);
    ImGui::RenderText(text_start + text_padding, std::to_string(*value).c_str());
    return value_changed;
}
References ImDrawList::AddCircleFilled(), ImDrawList::AddRectFilled(), ImDrawList::AddTriangleFilled(), Slic3r::GUI::BACKGROUND_COLOR_DARK, Slic3r::GUI::BACKGROUND_COLOR_LIGHT, Slic3r::GUI::BRAND_COLOR, ImGui::CalcTextSize(), ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, draw_background_and_groove(), ImGuiWindow::DrawList, ImGui::FocusWindow(), get_pos_from_value(), ImRect::GetCenter(), ImGui::GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, Slic3r::GUI::GROOVE_WIDTH, Slic3r::GUI::into_u8(), ImGuiContext::IO, ImGui::ItemHoverable(), ImGui::ItemSize(), m_is_dark, m_scale, ImRect::Max, ImRect::Min, ImGuiIO::MouseDown, Slic3r::GUI::ONE_LAYER_BUTTON_SIZE, Slic3r::GUI::ONE_LAYER_MARGIN, ImGui::RenderFrame(), ImGui::RenderText(), scale(), ImGui::SetActiveID(), ImGui::SetFocusID(), size, ImGuiWindow::SkipItems, Slic3r::GUI::slider_behavior(), ImVec2::x, and ImVec2::y.
Referenced by render().
init_texture()
bool Slic3r::GUI::IMSlider::init_texture ()
{
    bool result = true;
    if (!is_horizontal()) {
        // BBS init image texture id
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/one_layer_on.svg", 24, 24, m_one_layer_on_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/one_layer_on_hover.svg", 28, 28, m_one_layer_on_hover_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/one_layer_off.svg", 28, 28, m_one_layer_off_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/one_layer_off_hover.svg", 28, 28, m_one_layer_off_hover_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/one_layer_on_dark.svg", 24, 24, m_one_layer_on_dark_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/one_layer_on_hover_dark.svg", 28, 28, m_one_layer_on_hover_dark_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/one_layer_off_dark.svg", 28, 28, m_one_layer_off_dark_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/one_layer_off_hover_dark.svg", 28, 28, m_one_layer_off_hover_dark_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/im_gcode_pause.svg", 14, 14, m_pause_icon_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/im_gcode_custom.svg", 14, 14, m_custom_icon_id);
        result &= IMTexture::load_from_svg_file(Slic3r::resources_dir() + "/images/im_slider_delete.svg", 14, 14, m_delete_icon_id);
    }
    return result;
}
References is_horizontal(), Slic3r::GUI::IMTexture::load_from_svg_file(), m_custom_icon_id, m_delete_icon_id, m_one_layer_off_dark_id, m_one_layer_off_hover_dark_id, m_one_layer_off_hover_id, m_one_layer_off_id, m_one_layer_on_dark_id, m_one_layer_on_hover_dark_id, m_one_layer_on_hover_id, m_one_layer_on_id, m_pause_icon_id, and Slic3r::resources_dir().
Referenced by Slic3r::GUI::GCodeViewer::init().
is_dirty()
bool Slic3r::GUI::IMSlider::is_dirty () inline
{ return m_dirty; }
References m_dirty.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode().
is_full_span()
bool Slic3r::GUI::IMSlider::is_full_span () const inline
{ return this->is_lower_at_min() && this->is_higher_at_max(); }
References is_higher_at_max(), and is_lower_at_min().
is_higher_at_max()
bool Slic3r::GUI::IMSlider::is_higher_at_max () const inline
{ return m_higher_value == m_max_value; }
References m_higher_value, and m_max_value.
Referenced by is_full_span(), and Slic3r::GUI::Preview::update_layers_slider().
is_horizontal()
bool Slic3r::GUI::IMSlider::is_horizontal () const inline
{ return m_style == wxSL_HORIZONTAL; }
References m_style.
Referenced by get_pos_from_value(), init_texture(), on_mouse_wheel(), and render().
is_lower_at_min()
bool Slic3r::GUI::IMSlider::is_lower_at_min () const inline
{ return m_lower_value == m_min_value; }
References m_lower_value, and m_min_value.
Referenced by is_full_span(), and Slic3r::GUI::Preview::update_layers_slider().
is_need_post_tick_event()
bool Slic3r::GUI::IMSlider::is_need_post_tick_event () inline
{ return m_is_need_post_tick_changed_event; }
References m_is_need_post_tick_changed_event.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode().
is_one_layer()
bool Slic3r::GUI::IMSlider::is_one_layer () const inline
{ return m_is_one_layer; }
References m_is_one_layer.
Referenced by Slic3r::GUI::GLCanvas3D::on_key(), on_mouse_wheel(), and render().
is_rendering_as_disabled()
bool Slic3r::GUI::IMSlider::is_rendering_as_disabled () const inline
{ return m_render_as_disabled; }
References m_render_as_disabled.
Referenced by Slic3r::GUI::GCodeViewer::enable_moves_slider().
is_wipe_tower_layer()
bool Slic3r::GUI::IMSlider::is_wipe_tower_layer (int tick) const protected
{
    if (!m_is_wipe_tower || tick >= (int) m_values.size()) return false;
    if (tick == 0 || (tick == (int) m_values.size() - 1 && m_values[tick] > m_values[tick - 1])) return false;
    if ((m_values[tick - 1] == m_values[tick + 1] && m_values[tick] < m_values[tick + 1]) ||
        (tick > 0 && m_values[tick] < m_values[tick - 1])) // if there is just one wiping on the layer
        return true;
    return false;
}
References m_is_wipe_tower, and m_values.
Referenced by get_label().
IsNewPrint()
bool Slic3r::GUI::IMSlider::IsNewPrint ()
{
    const Print &print = GUI::wxGetApp().plater()->fff_print();
    std::string  idxs;
    for (auto object : print.objects()) idxs += std::to_string(object->id().id) + "_";
    if (idxs == m_print_obj_idxs) return false;
    m_print_obj_idxs = idxs;
    return true;
}
References m_print_obj_idxs, and Slic3r::Print::objects().
Referenced by Slic3r::GUI::Preview::update_layers_slider().
on_change_color_mode()
void Slic3r::GUI::IMSlider::on_change_color_mode (bool is_dark)
{
    m_is_dark = is_dark;
}
References m_is_dark.
Referenced by Slic3r::GUI::GLCanvas3D::on_change_color_mode().
on_mouse_wheel()
void Slic3r::GUI::IMSlider::on_mouse_wheel (wxMouseEvent & evt)
{
    auto moves_slider_window = ImGui::FindWindowByName("moves_slider");
    auto layers_slider_window = ImGui::FindWindowByName("laysers_slider");
    if (!moves_slider_window || !layers_slider_window) {
        BOOST_LOG_TRIVIAL(info) << "Couldn't find slider window";
        return;
    }
    float wheel = 0.0f;
    wheel = evt.GetWheelRotation() > 0 ? 1.0f : -1.0f;
    if (wheel == 0.0f)
        return;
#ifdef __WXOSX__
    if (wxGetKeyState(WXK_SHIFT)) {
        wheel *= -5;
    }
    else if (wxGetKeyState(WXK_RAW_CONTROL)) {
        wheel *= 5;
    }
#else
    if (wxGetKeyState(WXK_COMMAND) || wxGetKeyState(WXK_SHIFT))
        wheel *= 5;
#endif
    if (is_horizontal()) {
        if( evt.GetPosition().x > moves_slider_window->Pos.x &&
            evt.GetPosition().x < moves_slider_window->Pos.x + moves_slider_window->Size.x &&
            evt.GetPosition().y > moves_slider_window->Pos.y &&
            evt.GetPosition().y < moves_slider_window->Pos.y + moves_slider_window->Size.y){
            const int new_pos = GetHigherValue() + wheel;
            SetHigherValue(new_pos);
            set_as_dirty();
        }
    }
    else {
        if (evt.GetPosition().x > layers_slider_window->Pos.x &&
            evt.GetPosition().x < layers_slider_window->Pos.x + layers_slider_window->Size.x &&
            evt.GetPosition().y > layers_slider_window->Pos.y &&
            evt.GetPosition().y < layers_slider_window->Pos.y + layers_slider_window->Size.y) {
            if (is_one_layer()) {
                const int new_pos = GetHigherValue() + wheel;
                SetHigherValue(new_pos);
            }
            else {
                const int new_pos = m_selection == ssLower ? GetLowerValue() + wheel : GetHigherValue() + wheel;
                m_selection == ssLower ? SetLowerValue(new_pos) : SetHigherValue(new_pos);
            }
            set_as_dirty();
        }
    }
}
References ImGui::FindWindowByName(), GetHigherValue(), GetLowerValue(), is_horizontal(), is_one_layer(), m_selection, set_as_dirty(), SetHigherValue(), SetLowerValue(), and Slic3r::GUI::ssLower.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse_wheel().
post_ticks_changed_event()
void Slic3r::GUI::IMSlider::post_ticks_changed_event (Type type = Unknown)
{
    m_tick_change_event_type = type;
    m_is_need_post_tick_changed_event = true;
}
References m_is_need_post_tick_changed_event, and m_tick_change_event_type.
Referenced by add_code_as_tick(), add_custom_gcode(), delete_tick(), and SetTicksValues().
render()
bool Slic3r::GUI::IMSlider::render (int canvas_width, int canvas_height)
{
    bool result = false;
    ImGuiWrapper &imgui = *wxGetApp().imgui();
    /* style and colors */
    ImGui::PushStyleVar(ImGuiStyleVar_::ImGuiStyleVar_WindowBorderSize, 0);
    ImGui::PushStyleVar(ImGuiStyleVar_::ImGuiStyleVar_FramePadding, ImVec2(0.0f, 0.0f));
    ImGui::PushStyleVar(ImGuiStyleVar_::ImGuiStyleVar_WindowPadding, ImVec2(0.0f, 0.0f));
    ImGui::PushStyleColor(ImGuiCol_::ImGuiCol_WindowBg, ImVec4(0.0f, 0.0f, 0.0f, 0.0f));
    ImGui::PushStyleColor(ImGuiCol_::ImGuiCol_Text, ImVec4(0, 0.682f, 0.259f, 1.0f));
    int windows_flag = ImGuiWindowFlags_NoTitleBar
                       | ImGuiWindowFlags_NoCollapse
                       | ImGuiWindowFlags_NoMove
                       | ImGuiWindowFlags_NoResize
                       | ImGuiWindowFlags_NoScrollbar
                       | ImGuiWindowFlags_NoScrollWithMouse;
    float scale = (float) wxGetApp().em_unit() / 10.0f;
    if (is_horizontal()) {
        ImVec2 size  = ImVec2(canvas_width - 2 * std::max(LEFT_MARGIN * m_scale, 0.2f * canvas_width), HORIZONTAL_SLIDER_WINDOW_HEIGHT * m_scale);
        imgui.set_next_window_pos(0.5f * static_cast<float>(canvas_width), canvas_height, ImGuiCond_Always, 0.5f, 1.0f);
        imgui.begin(std::string("moves_slider"), windows_flag);
        int value = GetHigherValue();
        if (horizontal_slider("moves_slider", &value, GetMinValue(), GetMaxValue(), size, scale)) {
            result = true;
            SetHigherValue(value);
        }
        imgui.end();
    } else {
        ImVec2 size = ImVec2(VERTICAL_SLIDER_WINDOW_WIDTH * m_scale, 0.8f * canvas_height);
        imgui.set_next_window_pos(canvas_width, 0.5f * static_cast<float>(canvas_height), ImGuiCond_Always, 1.0f, 0.5f);
        imgui.begin(std::string("laysers_slider"), windows_flag);
        render_menu();
        int higher_value = GetHigherValue();
        int lower_value = GetLowerValue();
        std::string higher_label = get_label(m_higher_value);
        std::string lower_label  = get_label(m_lower_value);
        int temp_higher_value    = higher_value;
        int temp_lower_value     = lower_value;
        if (vertical_slider("laysers_slider", &higher_value, &lower_value, higher_label, lower_label, GetMinValue(), GetMaxValue(),
                  size, m_selection, is_one_layer(), scale)) {
            if (temp_higher_value != higher_value)
                SetHigherValue(higher_value);
            if (temp_lower_value != lower_value)
                SetLowerValue(lower_value);
            result = true;
        }
        imgui.end();
        imgui.set_next_window_pos(canvas_width, canvas_height, ImGuiCond_Always, 1.0f, 1.0f);
        ImGui::SetNextWindowSize((ONE_LAYER_BUTTON_SIZE + ONE_LAYER_MARGIN) * m_scale, 0);
        imgui.begin(std::string("one_layer_button"), windows_flag);
        ImTextureID normal_id = m_is_dark ?
            is_one_layer() ? m_one_layer_on_dark_id : m_one_layer_off_dark_id :
            is_one_layer() ? m_one_layer_on_id : m_one_layer_off_id;
        ImTextureID hover_id  = m_is_dark ?
            is_one_layer() ? m_one_layer_on_hover_dark_id : m_one_layer_off_hover_dark_id :
            is_one_layer() ? m_one_layer_on_hover_id : m_one_layer_off_hover_id;
        if (ImGui::ImageButton3(normal_id, hover_id, ONE_LAYER_BUTTON_SIZE * m_scale)) {
            switch_one_layer_mode();
        }
        imgui.end();
    }
    ImGui::PopStyleVar(3);
    ImGui::PopStyleColor(2);
    return result;
}
References Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::end(), get_label(), GetHigherValue(), GetLowerValue(), GetMaxValue(), GetMinValue(), horizontal_slider(), Slic3r::GUI::HORIZONTAL_SLIDER_WINDOW_HEIGHT, ImGui::ImageButton3(), ImGuiCol_Text, ImGuiCol_WindowBg, ImGuiCond_Always, ImGuiStyleVar_FramePadding, ImGuiStyleVar_WindowBorderSize, ImGuiStyleVar_WindowPadding, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImGuiWindowFlags_NoTitleBar, is_horizontal(), is_one_layer(), Slic3r::GUI::LEFT_MARGIN, m_higher_value, m_is_dark, m_lower_value, m_one_layer_off_dark_id, m_one_layer_off_hover_dark_id, m_one_layer_off_hover_id, m_one_layer_off_id, m_one_layer_on_dark_id, m_one_layer_on_hover_dark_id, m_one_layer_on_hover_id, m_one_layer_on_id, m_scale, m_selection, Slic3r::GUI::ONE_LAYER_BUTTON_SIZE, Slic3r::GUI::ONE_LAYER_MARGIN, ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), render_menu(), scale(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), SetHigherValue(), SetLowerValue(), ImGui::SetNextWindowSize(), size, switch_one_layer_mode(), vertical_slider(), and Slic3r::GUI::VERTICAL_SLIDER_WINDOW_WIDTH.
render_add_menu()
void Slic3r::GUI::IMSlider::render_add_menu () protected
{
    int extruder_num = m_extruder_colors.size();
    if (m_show_menu)
        ImGui::OpenPopup("slider_add_menu_popup");
    if (ImGui::BeginPopup("slider_add_menu_popup")) {
        bool menu_item_enable = m_draw_mode != dmSequentialFffPrint;
        bool hovered = false;
        {
            if (menu_item_with_icon(_u8L("Add Pause").c_str(), "", ImVec2(0, 0), 0, false, menu_item_enable, &hovered)) {
                add_code_as_tick(PausePrint);
            }
            if (hovered) { show_tooltip(_u8L("Insert a pause command at the beginning of this layer.")); }
            if (menu_item_with_icon(_u8L("Add Custom G-code").c_str(), "", ImVec2(0, 0), 0, false, menu_item_enable, &hovered)) {
                m_show_custom_gcode_window = true;
            }
            if (hovered) { show_tooltip(_u8L("Insert custom G-code at the beginning of this layer.")); }
            if (!gcode(Template).empty()) {
                if (menu_item_with_icon(_u8L("Add Custom Template").c_str(), "", ImVec2(0, 0), 0, false, menu_item_enable, &hovered)) {
                    add_code_as_tick(Template);
                }
                if (hovered) { show_tooltip(_u8L("Insert template custom G-code at the beginning of this layer.")); }
            }
            if (menu_item_with_icon(_u8L("Jump to Layer").c_str(), "")) {
                m_show_go_to_layer_dialog = true;
            }
        }
        //BBS render this menu item only when extruder_num > 1
        if (extruder_num > 1) {
            if (!m_can_change_color) {
                begin_menu(_u8L("Change Filament").c_str(), false);
            }
            else if (begin_menu(_u8L("Change Filament").c_str())) {
                for (int i = 0; i < extruder_num; i++) {
                    std::array<float, 4> rgba     = decode_color_to_float_array(m_extruder_colors[i]);
                    ImU32                icon_clr = IM_COL32(rgba[0] * 255.0f, rgba[1] * 255.0f, rgba[2] * 255.0f, rgba[3] * 255.0f);
                    if (menu_item_with_icon((_u8L("Filament ") + std::to_string(i + 1)).c_str(), "", ImVec2(14, 14) * m_scale, icon_clr, false, true, &hovered)) add_code_as_tick(ToolChange, i + 1);
                    if (hovered) { show_tooltip(_u8L("Change filament at the beginning of this layer.")); }
                }
                end_menu();
            }
        }
        ImGui::EndPopup();
    }
}
References _u8L, add_code_as_tick(), Slic3r::GUI::begin_menu(), ImGui::BeginPopup(), Slic3r::GUI::decode_color_to_float_array(), Slic3r::GUI::dmSequentialFffPrint, Slic3r::empty(), Slic3r::GUI::end_menu(), ImGui::EndPopup(), Slic3r::GUI::gcode(), IM_COL32, m_can_change_color, m_draw_mode, m_extruder_colors, m_scale, m_show_custom_gcode_window, m_show_go_to_layer_dialog, m_show_menu, Slic3r::GUI::menu_item_with_icon(), ImGui::OpenPopup(), Slic3r::CustomGCode::PausePrint, show_tooltip(), Slic3r::CustomGCode::Template, and Slic3r::CustomGCode::ToolChange.
Referenced by render_menu().
render_edit_menu()
void Slic3r::GUI::IMSlider::render_edit_menu (const TickCode & tick) protected
{
    if (m_show_menu)
        ImGui::OpenPopup("slider_edit_menu_popup");
    if (ImGui::BeginPopup("slider_edit_menu_popup")) {
        switch (tick.type)
        {
        case CustomGCode::PausePrint:
            if (menu_item_with_icon(_u8L("Delete Pause").c_str(), "")) {
                delete_tick(tick);
            }
            break;
        case CustomGCode::Template:
            if (!gcode(Template).empty()) {
                if (menu_item_with_icon(_u8L("Delete Custom Template").c_str(), "")) {
                    delete_tick(tick);
                }
            }
            break;
        case CustomGCode::Custom:
            if (menu_item_with_icon(_u8L("Edit Custom G-code").c_str(), "")) {
                m_show_custom_gcode_window = true;
            }
            if (menu_item_with_icon(_u8L("Delete Custom G-code").c_str(), "")) {
                delete_tick(tick);
            }
            break;
        case CustomGCode::ToolChange: {
            int extruder_num = m_extruder_colors.size();
            if (extruder_num > 1) {
                if (!m_can_change_color) {
                    begin_menu(_u8L("Change Filament").c_str(), false);
                }
                else if (begin_menu(_u8L("Change Filament").c_str())) {
                    for (int i = 0; i < extruder_num; i++) {
                        std::array<float, 4> rgba = decode_color_to_float_array(m_extruder_colors[i]);
                        ImU32                icon_clr = IM_COL32(rgba[0] * 255.0f, rgba[1] * 255.0f, rgba[2] * 255.0f, rgba[3] * 255.0f);
                        if (menu_item_with_icon((_u8L("Filament ") + std::to_string(i + 1)).c_str(), "", ImVec2(14, 14) * m_scale, icon_clr)) add_code_as_tick(ToolChange, i + 1);
                    }
                    end_menu();
                }
                if (menu_item_with_icon(_u8L("Delete Filament Change").c_str(), "")) {
                    delete_tick(tick);
                }
            }
            break;
        }
        case CustomGCode::ColorChange:
        case CustomGCode::Unknown:
        default:
            break;
        }
        ImGui::EndPopup();
    }
}
References _u8L, add_code_as_tick(), Slic3r::GUI::begin_menu(), ImGui::BeginPopup(), Slic3r::CustomGCode::ColorChange, Slic3r::CustomGCode::Custom, Slic3r::GUI::decode_color_to_float_array(), delete_tick(), Slic3r::empty(), Slic3r::GUI::end_menu(), ImGui::EndPopup(), Slic3r::GUI::gcode(), IM_COL32, m_can_change_color, m_extruder_colors, m_scale, m_show_custom_gcode_window, m_show_menu, Slic3r::GUI::menu_item_with_icon(), ImGui::OpenPopup(), Slic3r::CustomGCode::PausePrint, Slic3r::CustomGCode::Template, Slic3r::CustomGCode::ToolChange, Slic3r::GUI::TickCode::type, and Slic3r::CustomGCode::Unknown.
Referenced by render_menu().
render_go_to_layer_dialog()
void Slic3r::GUI::IMSlider::render_go_to_layer_dialog () protected
{
    if (m_show_go_to_layer_dialog)
        ImGui::OpenPopup((_u8L("Jump to Layer")).c_str());
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    ImVec2 center = ImGui::GetMainViewport()->GetCenter();
    ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    static bool set_focus = true;
    imgui.push_menu_style(m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(20, 10) * m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 12.f * m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(10, 3) * m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(10, 7) * m_scale);
    ImGui::PushStyleColor(ImGuiCol_TitleBgActive, m_is_dark ? ImVec4(54 / 255.0f, 54 / 255.0f, 60 / 255.0f, 1.00f) : ImVec4(245 / 255.0f, 245 / 255.0f, 245 / 255.0f, 1.00f));
    ImGui::GetCurrentContext()->DimBgRatio = 1.0f;
    int windows_flag =
        ImGuiWindowFlags_NoCollapse
        | ImGuiWindowFlags_AlwaysAutoResize
        | ImGuiWindowFlags_NoResize
        | ImGuiWindowFlags_NoScrollbar
        | ImGuiWindowFlags_NoScrollWithMouse;
    if (ImGui::BeginPopupModal((_u8L("Jump to layer")).c_str(), NULL, windows_flag))
    {
        imgui.text(_u8L("Please enter the layer number") + " (" + std::to_string(m_min_value + 1) + " - " + std::to_string(m_max_value + 1) + "):");
        if (ImGui::IsMouseClicked(0)) {
            set_focus = false;
        }
        if (set_focus && !ImGui::IsAnyItemActive() && !ImGui::IsMouseClicked(0)) {
            wxGetApp().plater()->get_current_canvas3D()->force_set_focus();
            ImGui::SetKeyboardFocusHere(0);
        }
        ImGui::InputText("##input_layer_number", m_layer_number, sizeof(m_layer_number));
        ImGui::NewLine();
        ImGui::SameLine(GImGui->Style.WindowPadding.x * 8);
        imgui.push_confirm_button_style();
        bool disable_button = false;
        if (strlen(m_layer_number) == 0)
            disable_button = true;
        else {
            for (size_t i = 0; i < strlen(m_layer_number); i++)
                if (!isdigit(m_layer_number[i]))
                    disable_button = true;
            if (!disable_button && (m_min_value > atoi(m_layer_number) - 1 || atoi(m_layer_number) - 1 > m_max_value))
                disable_button = true;
        }
        if (disable_button) {
            ImGui::PushItemFlag(ImGuiItemFlags_Disabled, true);
            imgui.push_button_disable_style();
        }
        if (imgui.bbl_button(_L("OK")) || (!disable_button && ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_Enter)))) {
            do_go_to_layer(atoi(m_layer_number) - 1);
            m_show_go_to_layer_dialog = false;
            ImGui::CloseCurrentPopup();
            set_focus = true;
        }
        if (disable_button) {
            ImGui::PopItemFlag();
            imgui.pop_button_disable_style();
        }
        imgui.pop_confirm_button_style();
        ImGui::SameLine();
        imgui.push_cancel_button_style();
        if (imgui.bbl_button(_L("Cancel")) || ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_Escape))) {
            m_show_go_to_layer_dialog = false;
            ImGui::CloseCurrentPopup();
            set_focus = true;
        }
        imgui.pop_cancel_button_style();
        ImGui::EndPopup();
    }
    ImGui::PopStyleVar(4);
    ImGui::PopStyleColor();
    imgui.pop_menu_style();
}
References _L, _u8L, Slic3r::GUI::ImGuiWrapper::bbl_button(), ImGui::BeginPopupModal(), ImGui::CloseCurrentPopup(), ImGuiContext::DimBgRatio, do_go_to_layer(), ImGui::EndPopup(), ImGuiViewport::GetCenter(), ImGui::GetCurrentContext(), ImGui::GetKeyIndex(), ImGui::GetMainViewport(), GImGui, ImGuiCol_TitleBgActive, ImGuiCond_Appearing, ImGuiItemFlags_Disabled, ImGuiKey_Enter, ImGuiKey_Escape, ImGuiStyleVar_FramePadding, ImGuiStyleVar_FrameRounding, ImGuiStyleVar_ItemSpacing, ImGuiStyleVar_WindowPadding, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImGui::InputText(), ImGui::IsAnyItemActive(), ImGui::IsKeyDown(), ImGui::IsMouseClicked(), m_is_dark, m_layer_number, m_max_value, m_min_value, m_scale, m_show_go_to_layer_dialog, ImGui::NewLine(), NULL, ImGui::OpenPopup(), Slic3r::GUI::ImGuiWrapper::pop_button_disable_style(), Slic3r::GUI::ImGuiWrapper::pop_cancel_button_style(), Slic3r::GUI::ImGuiWrapper::pop_confirm_button_style(), Slic3r::GUI::ImGuiWrapper::pop_menu_style(), ImGui::PopItemFlag(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), Slic3r::GUI::ImGuiWrapper::push_button_disable_style(), Slic3r::GUI::ImGuiWrapper::push_cancel_button_style(), Slic3r::GUI::ImGuiWrapper::push_confirm_button_style(), Slic3r::GUI::ImGuiWrapper::push_menu_style(), ImGui::PushItemFlag(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::SetKeyboardFocusHere(), ImGui::SetNextWindowPos(), ImGuiContext::Style, Slic3r::GUI::ImGuiWrapper::text(), ImGuiStyle::WindowPadding, and ImVec2::x.
Referenced by render_menu().
render_input_custom_gcode()
void Slic3r::GUI::IMSlider::render_input_custom_gcode (std::string custom_gcode = "") protected
{
    if (m_show_custom_gcode_window)
        ImGui::OpenPopup((_u8L("Custom G-code")).c_str());
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    ImVec2 center = ImGui::GetMainViewport()->GetCenter();
    static bool set_focus = true;
    ImGui::SetNextWindowPos(center, ImGuiCond_Appearing, ImVec2(0.5f, 0.5f));
    imgui.push_menu_style(m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(20, 10) * m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 12.f * m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(10, 3) * m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(10, 7) * m_scale);
    ImGui::PushStyleColor(ImGuiCol_TitleBgActive, m_is_dark ? ImVec4(54 / 255.0f, 54 / 255.0f, 60 / 255.0f, 1.00f) : ImVec4(245 / 255.0f, 245 / 255.0f, 245 / 255.0f, 1.00f));
    ImGui::GetCurrentContext()->DimBgRatio = 1.0f;
    int windows_flag =
        ImGuiWindowFlags_NoCollapse
        | ImGuiWindowFlags_AlwaysAutoResize
        | ImGuiWindowFlags_NoResize
        | ImGuiWindowFlags_NoScrollbar
        | ImGuiWindowFlags_NoScrollWithMouse;
    if (ImGui::BeginPopupModal((_u8L("Custom G-code")).c_str(), NULL, windows_flag))
    {
        imgui.text(_u8L("Enter Custom G-code used on current layer:"));
        if (ImGui::IsMouseClicked(0)) {
            set_focus = false;
        }
        if (set_focus && !ImGui::IsAnyItemActive() && !ImGui::IsMouseClicked(0)) {
            wxGetApp().plater()->get_current_canvas3D()->force_set_focus();
            ImGui::SetKeyboardFocusHere(0);
            strcpy(m_custom_gcode, custom_gcode.c_str());
        }
        const int text_height = 6;
        ImGui::InputTextMultiline("##text", m_custom_gcode, sizeof(m_custom_gcode), ImVec2(-1, ImGui::GetTextLineHeight() * text_height), ImGuiInputTextFlags_CallbackAlways, [](ImGuiInputTextCallbackData* data) {
            return data->CursorPos = data->BufTextLen;
            });
        ImGui::NewLine();
        ImGui::SameLine(ImGui::GetStyle().WindowPadding.x * 14);
        imgui.push_confirm_button_style();
        bool disable_button = false;
        if (strlen(m_custom_gcode) == 0)
            disable_button = true;
        if (disable_button) {
            ImGui::PushItemFlag(ImGuiItemFlags_Disabled, true);
            imgui.push_button_disable_style();
        }
        if (imgui.bbl_button(_L("OK"))) {
            add_custom_gcode(m_custom_gcode);
            m_show_custom_gcode_window = false;
            ImGui::CloseCurrentPopup();
            set_focus = true;
        }
        if (disable_button) {
            ImGui::PopItemFlag();
            imgui.pop_button_disable_style();
        }
        imgui.pop_confirm_button_style();
        ImGui::SameLine();
        imgui.push_cancel_button_style();
        if (imgui.bbl_button(_L("Cancel")) || ImGui::IsKeyDown(ImGui::GetKeyIndex(ImGuiKey_Escape))) {
            m_show_custom_gcode_window = false;
            ImGui::CloseCurrentPopup();
            set_focus = true;
        }
        imgui.pop_cancel_button_style();
        ImGui::EndPopup();
    }
    ImGui::PopStyleVar(4);
    ImGui::PopStyleColor();
    imgui.pop_menu_style();
}
References _L, _u8L, add_custom_gcode(), Slic3r::GUI::ImGuiWrapper::bbl_button(), ImGui::BeginPopupModal(), ImGuiInputTextCallbackData::BufTextLen, ImGui::CloseCurrentPopup(), ImGuiInputTextCallbackData::CursorPos, ImGuiContext::DimBgRatio, ImGui::EndPopup(), ImGuiViewport::GetCenter(), ImGui::GetCurrentContext(), ImGui::GetKeyIndex(), ImGui::GetMainViewport(), ImGui::GetStyle(), ImGui::GetTextLineHeight(), ImGuiCol_TitleBgActive, ImGuiCond_Appearing, ImGuiInputTextFlags_CallbackAlways, ImGuiItemFlags_Disabled, ImGuiKey_Escape, ImGuiStyleVar_FramePadding, ImGuiStyleVar_FrameRounding, ImGuiStyleVar_ItemSpacing, ImGuiStyleVar_WindowPadding, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImGui::InputTextMultiline(), ImGui::IsAnyItemActive(), ImGui::IsKeyDown(), ImGui::IsMouseClicked(), m_custom_gcode, m_is_dark, m_scale, m_show_custom_gcode_window, ImGui::NewLine(), NULL, ImGui::OpenPopup(), Slic3r::GUI::ImGuiWrapper::pop_button_disable_style(), Slic3r::GUI::ImGuiWrapper::pop_cancel_button_style(), Slic3r::GUI::ImGuiWrapper::pop_confirm_button_style(), Slic3r::GUI::ImGuiWrapper::pop_menu_style(), ImGui::PopItemFlag(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), Slic3r::GUI::ImGuiWrapper::push_button_disable_style(), Slic3r::GUI::ImGuiWrapper::push_cancel_button_style(), Slic3r::GUI::ImGuiWrapper::push_confirm_button_style(), Slic3r::GUI::ImGuiWrapper::push_menu_style(), ImGui::PushItemFlag(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::SameLine(), ImGui::SetKeyboardFocusHere(), ImGui::SetNextWindowPos(), and Slic3r::GUI::ImGuiWrapper::text().
Referenced by render_menu().
render_menu()
void Slic3r::GUI::IMSlider::render_menu () protected
{
    if (!m_menu_enable)
        return;
    ImGuiWrapper::push_menu_style(m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_::ImGuiStyleVar_ChildRounding, 4.0f * m_scale);
    auto tick_it = GetSelection() == ssHigher ? m_ticks.ticks.find(TickCode{ GetHigherValue() }) :
        GetSelection() == ssLower ? m_ticks.ticks.find(TickCode{ GetLowerValue() }) :
        m_ticks.ticks.end();
    std::string custom_code;
    if (tick_it != m_ticks.ticks.end()) {
        render_edit_menu(*tick_it);
        if (tick_it->type == CustomGCode::Custom)
            custom_code = tick_it->extra;
    }
    else {
        render_add_menu();
    }
    ImGui::PopStyleVar(1);
    ImGuiWrapper::pop_menu_style();
    render_input_custom_gcode(custom_code);
    render_go_to_layer_dialog();
}
References Slic3r::CustomGCode::Custom, GetHigherValue(), GetLowerValue(), GetSelection(), ImGuiStyleVar_ChildRounding, m_menu_enable, m_scale, m_ticks, Slic3r::GUI::ImGuiWrapper::pop_menu_style(), ImGui::PopStyleVar(), Slic3r::GUI::ImGuiWrapper::push_menu_style(), ImGui::PushStyleVar(), render_add_menu(), render_edit_menu(), render_go_to_layer_dialog(), render_input_custom_gcode(), Slic3r::GUI::ssHigher, Slic3r::GUI::ssLower, and Slic3r::GUI::TickCodeInfo::ticks.
Referenced by render().
reset_post_tick_event()
void Slic3r::GUI::IMSlider::reset_post_tick_event (bool val = false) inline
{
        m_is_need_post_tick_changed_event = val;
        m_tick_change_event_type = Type::Unknown;
    }
References m_is_need_post_tick_changed_event, and m_tick_change_event_type.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode().
set_as_dirty()
void Slic3r::GUI::IMSlider::set_as_dirty (bool dirty = true) inline
{ m_dirty = dirty; }
References m_dirty.
Referenced by Slic3r::GUI::GLCanvas3D::_render_gcode(), Slic3r::GUI::GCodeViewer::enable_moves_slider(), Slic3r::GUI::GCodeViewer::load(), Slic3r::GUI::GLCanvas3D::on_key(), on_mouse_wheel(), SetHigherValue(), SetLayersTimes(), SetLowerValue(), SetMaxValue(), SetSelectionSpan(), SetTicksValues(), and switch_one_layer_mode().
set_menu_enable()
void Slic3r::GUI::IMSlider::set_menu_enable (bool enable = true) inline
{ m_menu_enable = enable; }
References m_menu_enable.
Referenced by Slic3r::GUI::GCodeViewer::load().
set_render_as_disabled()
void Slic3r::GUI::IMSlider::set_render_as_disabled (bool value) inline
{ m_render_as_disabled = value; }
References m_render_as_disabled.
Referenced by Slic3r::GUI::GCodeViewer::enable_moves_slider().
set_scale()
void Slic3r::GUI::IMSlider::set_scale (float scale = 1.0)
{
    if(m_scale != scale) m_scale = scale;
}
References m_scale, and scale().
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale().
SetDrawMode() [1/2]
void Slic3r::GUI::IMSlider::SetDrawMode (bool is_sequential_print)
{
    m_draw_mode = is_sequential_print   ? dmSequentialFffPrint  :
                                          dmRegular;
    m_can_change_color = m_can_change_color && !(m_draw_mode == dmSequentialFffPrint);
}
References Slic3r::GUI::dmRegular, Slic3r::GUI::dmSequentialFffPrint, m_can_change_color, and m_draw_mode.
Referenced by Slic3r::GUI::Preview::update_layers_slider().
SetDrawMode() [2/2]
void Slic3r::GUI::IMSlider::SetDrawMode (DrawMode mode) inline
{ m_draw_mode = mode; }
References m_draw_mode.
SetExtraStyle()
void Slic3r::GUI::IMSlider::SetExtraStyle (long style) inline
{ m_extra_style = style; }
References m_extra_style, and style.
SetExtruderColors()
void Slic3r::GUI::IMSlider::SetExtruderColors (const std::vector< std::string > & extruder_colors)
{
    m_extruder_colors = extruder_colors;
}
References m_extruder_colors.
Referenced by Slic3r::GUI::Preview::update_layers_slider().
SetHigherValue()
void Slic3r::GUI::IMSlider::SetHigherValue (const int higher_val)
{
    m_selection    = ssHigher;
    m_higher_value = higher_val;
    correct_higher_value();
    set_as_dirty();
}
References correct_higher_value(), m_higher_value, m_selection, set_as_dirty(), and Slic3r::GUI::ssHigher.
Referenced by do_go_to_layer(), Slic3r::GUI::GLCanvas3D::on_key(), on_mouse_wheel(), render(), switch_one_layer_mode(), and Slic3r::GUI::GCodeViewer::update_moves_slider().
SetKoefForLabels()
void Slic3r::GUI::IMSlider::SetKoefForLabels (const double koef) inline
{ m_label_koef = koef; }
References m_label_koef.
SetLayersTimes() [1/2]
void Slic3r::GUI::IMSlider::SetLayersTimes (const std::vector< double > & layers_times)
{
    m_is_wipe_tower = false;
    m_layers_times  = layers_times;
    for (size_t i = 1; i < m_layers_times.size(); i++) m_layers_times[i] += m_layers_times[i - 1];
}
References m_is_wipe_tower, and m_layers_times.
SetLayersTimes() [2/2]
void Slic3r::GUI::IMSlider::SetLayersTimes (const std::vector< float > & layers_times, float total_time)
{
    m_layers_times.clear();
    if (layers_times.empty()) return;
    m_layers_times.resize(layers_times.size(), 0.0);
    m_layers_times[0] = layers_times[0];
    for (size_t i = 1; i < layers_times.size(); i++) m_layers_times[i] = m_layers_times[i - 1] + layers_times[i];
    // Erase duplicates values from m_values and save it to the m_layers_values
    // They will be used for show the correct estimated time for MM print, when "No sparce layer" is enabled
    if (m_is_wipe_tower && m_values.size() != m_layers_times.size()) {
        m_layers_values = m_values;
        sort(m_layers_values.begin(), m_layers_values.end());
        m_layers_values.erase(unique(m_layers_values.begin(), m_layers_values.end()), m_layers_values.end());
        // When whipe tower is used to the end of print, there is one layer which is not marked in layers_times
        // So, add this value from the total print time value
        if (m_layers_values.size() != m_layers_times.size())
            for (size_t i = m_layers_times.size(); i < m_layers_values.size(); i++) m_layers_times.push_back(total_time);
        set_as_dirty();
        set_as_dirty();
    }
}
References m_is_wipe_tower, m_layers_times, m_layers_values, m_values, and set_as_dirty().
Referenced by Slic3r::GUI::Preview::update_layers_slider().
SetLowerValue()
void Slic3r::GUI::IMSlider::SetLowerValue (const int lower_val)
{
    m_selection   = ssLower;
    m_lower_value = lower_val;
    correct_lower_value();
    set_as_dirty();
}
References correct_lower_value(), m_lower_value, m_selection, set_as_dirty(), and Slic3r::GUI::ssLower.
Referenced by do_go_to_layer(), Slic3r::GUI::GLCanvas3D::on_key(), on_mouse_wheel(), render(), and switch_one_layer_mode().
SetManipulationMode()
void Slic3r::GUI::IMSlider::SetManipulationMode (Mode mode) inline
{ m_mode = mode; }
References m_mode.
SetMaxValue()
void Slic3r::GUI::IMSlider::SetMaxValue (const int max_value)
{
    m_max_value = max_value;
    set_as_dirty();
}
References m_max_value, and set_as_dirty().
Referenced by Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::GUI::GCodeViewer::update_moves_slider().
SetModeAndOnlyExtruder()
void Slic3r::GUI::IMSlider::SetModeAndOnlyExtruder (const bool is_one_extruder_printed_model, const int only_extruder, bool can_change_color)
{
    m_mode = !is_one_extruder_printed_model ? MultiExtruder : only_extruder < 0 ? SingleExtruder : MultiAsSingle;
    if (!m_ticks.mode || (m_ticks.empty() && m_ticks.mode != m_mode)) m_ticks.mode = m_mode;
    m_only_extruder = only_extruder;
    UseDefaultColors(m_mode == SingleExtruder);
    m_is_wipe_tower = m_mode != SingleExtruder;
    auto config = wxGetApp().preset_bundle->full_config();
    m_is_spiral_vase = config.option<ConfigOptionBool>("spiral_mode")->value;
    m_can_change_color = can_change_color && !m_is_spiral_vase;
    // close opened menu window after reslice
    m_show_menu = false;
    m_show_custom_gcode_window = false;
    m_show_go_to_layer_dialog = false;
}
References Slic3r::GUI::TickCodeInfo::empty(), m_can_change_color, m_is_spiral_vase, m_is_wipe_tower, m_mode, m_only_extruder, m_show_custom_gcode_window, m_show_go_to_layer_dialog, m_show_menu, m_ticks, Slic3r::GUI::TickCodeInfo::mode, Slic3r::CustomGCode::MultiAsSingle, Slic3r::CustomGCode::MultiExtruder, Slic3r::CustomGCode::SingleExtruder, and UseDefaultColors().
Referenced by Slic3r::GUI::Preview::update_layers_slider_mode().
SetSelectionSpan()
void Slic3r::GUI::IMSlider::SetSelectionSpan (const int lower_val, const int higher_val)
{
    m_lower_value  = std::max(lower_val, m_min_value);
    m_higher_value = std::max(std::min(higher_val, m_max_value), m_lower_value);
    if (m_lower_value < m_higher_value) m_is_one_layer = false;
    set_as_dirty();
}
References m_higher_value, m_is_one_layer, m_lower_value, m_max_value, m_min_value, and set_as_dirty().
Referenced by Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::GUI::GCodeViewer::update_moves_slider().
SetSliderAlternateValues()
void Slic3r::GUI::IMSlider::SetSliderAlternateValues (const std::vector< double > & values) inline
{ m_alternate_values = values; }
References m_alternate_values.
Referenced by Slic3r::GUI::GCodeViewer::update_moves_slider().
SetSliderValues()
void Slic3r::GUI::IMSlider::SetSliderValues (const std::vector< double > & values)
{
    m_values = values;
}
References m_values.
Referenced by Slic3r::GUI::Preview::update_layers_slider(), and Slic3r::GUI::GCodeViewer::update_moves_slider().
SetTicksValues()
void Slic3r::GUI::IMSlider::SetTicksValues (const Info & custom_gcode_per_print_z)
{
    if (m_values.empty()) {
        m_ticks.mode = m_mode;
        return;
    }
    static bool last_spiral_vase_status = false;
    const bool was_empty = m_ticks.empty();
    m_ticks.ticks.clear();
    const std::vector<CustomGCode::Item> &heights = custom_gcode_per_print_z.gcodes;
    for (auto h : heights) {
        int tick = get_tick_from_value(h.print_z);
        if (tick >= 0) m_ticks.ticks.emplace(TickCode{tick, h.type, h.extruder, h.color, h.extra});
    }
    if (!was_empty && m_ticks.empty())
        // Switch to the "Feature type"/"Tool" from the very beginning of a new object slicing after deleting of the old one
        ;// post_ticks_changed_event();
    if (m_ticks.has_tick_with_code(ToolChange) && !m_can_change_color) {
        m_ticks.erase_all_ticks_with_code(ToolChange);
        post_ticks_changed_event();
    }
    if (last_spiral_vase_status != m_is_spiral_vase) {
        last_spiral_vase_status = m_is_spiral_vase;
        if (!m_ticks.empty()) {
            m_ticks.ticks.clear();
            post_ticks_changed_event();
        }
    }
    //auto has_tick_execpt = [this](CustomGCode::Type type) {
    //    for (const TickCode& tick : m_ticks.ticks)
    //        if (tick.type != type) return true;
    //    return false;
    //};
    if ((!m_ticks.empty() /*&& has_tick_execpt(PausePrint)*/) && m_draw_mode == dmSequentialFffPrint) {
        for (auto it{ m_ticks.ticks.begin() }, end{ m_ticks.ticks.end() }; it != end;) {
            if (true/*it->type != PausePrint*/)
                it = m_ticks.ticks.erase(it);
            else
                ++it;
        }
        post_ticks_changed_event();
    }
    if (custom_gcode_per_print_z.mode && !custom_gcode_per_print_z.gcodes.empty()) m_ticks.mode = custom_gcode_per_print_z.mode;
    set_as_dirty();
}
References Slic3r::custom_gcode_per_print_z, Slic3r::GUI::dmSequentialFffPrint, Slic3r::GUI::TickCodeInfo::empty(), end, Slic3r::GUI::TickCodeInfo::erase_all_ticks_with_code(), Slic3r::CustomGCode::Info::gcodes, get_tick_from_value(), Slic3r::GUI::TickCodeInfo::has_tick_with_code(), m_can_change_color, m_draw_mode, m_is_spiral_vase, m_mode, m_ticks, m_values, Slic3r::CustomGCode::Info::mode, Slic3r::GUI::TickCodeInfo::mode, post_ticks_changed_event(), set_as_dirty(), Slic3r::GUI::TickCodeInfo::ticks, Slic3r::CustomGCode::ToolChange, and Slic3r::GUI::TickCode::type.
Referenced by Slic3r::GUI::Preview::update_layers_slider().
show_go_to_layer()
void Slic3r::GUI::IMSlider::show_go_to_layer (bool show) inline
{ m_show_go_to_layer_dialog = show; }
References m_show_go_to_layer_dialog.
Referenced by Slic3r::GUI::GLCanvas3D::on_key().
show_tooltip() [1/2]
void Slic3r::GUI::IMSlider::show_tooltip (const std::string tooltip) protected
{
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, { 6 * m_scale, 3 * m_scale });
    ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, { 3 * m_scale });
    ImGui::PushStyleColor(ImGuiCol_PopupBg, ImGuiWrapper::COL_WINDOW_BACKGROUND);
    ImGui::PushStyleColor(ImGuiCol_Border, { 0,0,0,0 });
    ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));
    ImGui::BeginTooltip();
    ImGui::TextUnformatted(tooltip.c_str());
    ImGui::EndTooltip();
    ImGui::PopStyleColor(3);
    ImGui::PopStyleVar(2);
}
References ImGui::BeginTooltip(), Slic3r::GUI::ImGuiWrapper::COL_WINDOW_BACKGROUND, ImGui::EndTooltip(), ImGuiCol_Border, ImGuiCol_PopupBg, ImGuiCol_Text, ImGuiStyleVar_WindowPadding, ImGuiStyleVar_WindowRounding, m_scale, ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), and ImGui::TextUnformatted().
show_tooltip() [2/2]
void Slic3r::GUI::IMSlider::show_tooltip (const TickCode & tick) protected
{
    switch (tick.type)
    {
    case CustomGCode::ColorChange:
        break;
    case CustomGCode::PausePrint:
        show_tooltip(_u8L("Pause:") + " \"" + gcode(PausePrint) + "\"");
        break;
    case CustomGCode::ToolChange:
        show_tooltip(_u8L("Change Filament"));
        break;
    case CustomGCode::Template:
        show_tooltip(_u8L("Custom Template:") + " \"" + gcode(Template) + "\"");
        break;
    case CustomGCode::Custom:
        show_tooltip(_u8L("Custom G-code:") + " \"" + tick.extra + "\"");
        break;
    default:
        break;
    }
}
References _u8L, Slic3r::CustomGCode::ColorChange, Slic3r::CustomGCode::Custom, Slic3r::GUI::TickCode::extra, Slic3r::GUI::gcode(), Slic3r::CustomGCode::PausePrint, show_tooltip(), Slic3r::CustomGCode::Template, Slic3r::CustomGCode::ToolChange, and Slic3r::GUI::TickCode::type.
Referenced by draw_ticks(), render_add_menu(), and show_tooltip().
switch_one_layer_mode()
bool Slic3r::GUI::IMSlider::switch_one_layer_mode ()
{
    if (m_show_custom_gcode_window)
        return false;
    m_is_one_layer = !m_is_one_layer;
    if (!m_is_one_layer) {
        SetLowerValue(m_min_value);
        SetHigherValue(m_max_value);
    }
    m_selection == ssLower ? correct_lower_value() : correct_higher_value();
    if (m_selection == ssUndef) m_selection = ssHigher;
    set_as_dirty();
    return true;
}
References correct_higher_value(), correct_lower_value(), m_is_one_layer, m_max_value, m_min_value, m_selection, m_show_custom_gcode_window, set_as_dirty(), SetHigherValue(), SetLowerValue(), Slic3r::GUI::ssHigher, Slic3r::GUI::ssLower, and Slic3r::GUI::ssUndef.
Referenced by render(), and Slic3r::GUI::Preview::update_layers_slider_from_canvas().
UseDefaultColors()
void Slic3r::GUI::IMSlider::UseDefaultColors (bool def_colors_on) inline
{ m_ticks.set_default_colors(def_colors_on); }
References m_ticks, and Slic3r::GUI::TickCodeInfo::set_default_colors().
Referenced by SetModeAndOnlyExtruder().
vertical_slider()
bool Slic3r::GUI::IMSlider::vertical_slider (const char * str_id, int * higher_value, int * lower_value, std::string & higher_label, std::string & lower_label, int v_min, int v_max, const ImVec2 & size, SelectedSlider & selection, bool one_layer_flag = false, float scale = 1.0f) protected
{
    ImGuiWindow* window = ImGui::GetCurrentWindow();
    if (window->SkipItems)
        return false;
    ImGuiContext& context = *GImGui;
    const ImGuiID id = window->GetID(str_id);
    const ImVec2 pos = window->DC.CursorPos;
    const ImRect draw_region(pos, pos + size);
    ImGui::ItemSize(draw_region);
    const float  text_dummy_height   = 30.0f * scale * m_scale;
    const float  handle_radius       = 12.0f * m_scale;
    const float  handle_border       = 2.0f * m_scale;
    const float  line_width          = 1.0f * m_scale;
    const float  line_length         = 12.0f * m_scale;
    const float  one_handle_offset   = 26.0f * m_scale;
    const float  bar_width           = 28.0f * m_scale;
    const float  text_frame_rounding = 2.0f * scale * m_scale;
    const ImVec2 text_padding        = ImVec2(5.0f, 2.0f) * m_scale;
    const ImVec2 triangle_offsets[3] = {ImVec2(2.0f, 0.0f) * m_scale, ImVec2(0.0f, 8.0f) * m_scale, ImVec2(9.0f, 0.0f) * m_scale};
    ImVec2 text_content_size;
    ImVec2 text_size;
    const ImU32 white_bg = m_is_dark ? BACKGROUND_COLOR_DARK : BACKGROUND_COLOR_LIGHT;
    const ImU32 handle_clr = BRAND_COLOR;
    const ImU32 handle_border_clr = m_is_dark ? BACKGROUND_COLOR_DARK : BACKGROUND_COLOR_LIGHT;
    // calculate slider groove size
    const ImVec2 groove_start = ImVec2(pos.x + size.x - ONE_LAYER_MARGIN.x * m_scale - ONE_LAYER_BUTTON_SIZE.x * m_scale * 0.5f - GROOVE_WIDTH * m_scale * 0.5f, pos.y + text_dummy_height);
    const ImVec2 groove_size = ImVec2(GROOVE_WIDTH * m_scale, size.y - 2 * text_dummy_height);
    const ImRect groove = ImRect(groove_start, groove_start + groove_size);
    const ImRect bg_rect = ImRect(groove.Min - ImVec2(6.0f, 6.0f) * m_scale, groove.Max + ImVec2(6.0f, 6.0f) * m_scale);
    const float mid_x = groove.GetCenter().x;
    // set mouse active region.
    const ImRect active_region = ImRect(ImVec2(draw_region.Min.x + 35.0f * m_scale, draw_region.Min.y), draw_region.Max);
    bool hovered = ImGui::ItemHoverable(active_region, id) && !ImGui::ItemHoverable(m_tick_rect, id);
    if (hovered && context.IO.MouseDown[0]) {
        ImGui::SetActiveID(id, window);
        ImGui::SetFocusID(id, window);
        ImGui::FocusWindow(window);
    }
    // draw background
    draw_background_and_groove(bg_rect, groove);
    // Processing interacting
    // set scrollable region
    const ImRect region = ImRect(bg_rect.Min + ImVec2(0.0f, handle_radius), bg_rect.Max - ImVec2(0.0f, handle_radius));
    const ImRect higher_slideable_region = ImRect(region.Min, region.Max - ImVec2(0, handle_radius));
    const ImRect lower_slideable_region = ImRect(region.Min + ImVec2(0, handle_radius), region.Max);
    const ImRect one_slideable_region = region;
    // initialize the handles.
    float higher_handle_pos = get_pos_from_value(v_min, v_max, *higher_value, higher_slideable_region);
    ImRect higher_handle = ImRect(mid_x - handle_radius, higher_handle_pos - handle_radius, mid_x + handle_radius, higher_handle_pos + handle_radius);
    float  lower_handle_pos = get_pos_from_value(v_min, v_max, *lower_value, lower_slideable_region);
    ImRect lower_handle = ImRect(mid_x - handle_radius, lower_handle_pos - handle_radius, mid_x + handle_radius, lower_handle_pos + handle_radius);
    ImRect one_handle = ImRect(higher_handle.Min - ImVec2(one_handle_offset, 0), higher_handle.Max - ImVec2(one_handle_offset, 0));
    bool value_changed = false;
    if (!one_layer_flag)
    {
        // select higher handle by default
        static bool h_selected = (selection == ssHigher);
        if (ImGui::ItemHoverable(higher_handle, id) && context.IO.MouseClicked[0]) {
            selection = ssHigher;
            h_selected = true;
        }
        if (ImGui::ItemHoverable(lower_handle, id) && context.IO.MouseClicked[0]) {
            selection = ssLower;
            h_selected = false;
        }
        // update handle position and value
        if (h_selected)
        {
            value_changed = slider_behavior(id, higher_slideable_region, v_min, v_max,
                higher_value, &higher_handle, ImGuiSliderFlags_Vertical,
                m_tick_value, m_tick_rect);
        }
        if (!h_selected) {
            value_changed = slider_behavior(id, lower_slideable_region, v_min, v_max,
                lower_value, &lower_handle, ImGuiSliderFlags_Vertical,
                m_tick_value, m_tick_rect);
        }
        ImVec2 higher_handle_center = higher_handle.GetCenter();
        ImVec2 lower_handle_center = lower_handle.GetCenter();
        if (higher_handle_center.y + handle_radius > lower_handle_center.y && h_selected)
        {
            lower_handle = higher_handle;
            lower_handle.TranslateY(handle_radius);
            lower_handle_center.y = higher_handle_center.y + handle_radius;
            *lower_value = *higher_value;
        }
        if (higher_handle_center.y + handle_radius > lower_handle_center.y && !h_selected)
        {
            higher_handle = lower_handle;
            higher_handle.TranslateY(-handle_radius);
            higher_handle_center.y = lower_handle_center.y - handle_radius;
            *higher_value = *lower_value;
        }
        // judge whether to open menu
        if (ImGui::ItemHoverable(h_selected ? higher_handle : lower_handle, id) && context.IO.MouseClicked[1])
            m_show_menu = true;
        if ((!ImGui::ItemHoverable(h_selected ? higher_handle : lower_handle, id) && context.IO.MouseClicked[1]) ||
            context.IO.MouseClicked[0])
            m_show_menu = false;
        // draw ticks
        draw_ticks(h_selected ? higher_slideable_region : lower_slideable_region);
        // draw colored band
        draw_colored_band(groove, h_selected ? higher_slideable_region : lower_slideable_region);
        if (!m_ticks.has_tick_with_code(ToolChange)) {
            // draw scroll line
            ImRect scroll_line = ImRect(ImVec2(groove.Min.x, higher_handle_center.y), ImVec2(groove.Max.x, lower_handle_center.y));
            window->DrawList->AddRectFilled(scroll_line.Min, scroll_line.Max, handle_clr);
        }
        // draw handles
        window->DrawList->AddCircleFilled(higher_handle_center, handle_radius, handle_border_clr);
        window->DrawList->AddCircleFilled(higher_handle_center, handle_radius - handle_border, handle_clr);
        window->DrawList->AddCircleFilled(lower_handle_center, handle_radius, handle_border_clr);
        window->DrawList->AddCircleFilled(lower_handle_center, handle_radius - handle_border, handle_clr);
        if (h_selected) {
            window->DrawList->AddCircleFilled(higher_handle_center, handle_radius, handle_border_clr);
            window->DrawList->AddCircleFilled(higher_handle_center, handle_radius - handle_border, handle_clr);
            window->DrawList->AddLine(higher_handle_center + ImVec2(-0.5f * line_length, 0.0f), higher_handle_center + ImVec2(0.5f * line_length, 0.0f), white_bg, line_width);
            window->DrawList->AddLine(higher_handle_center + ImVec2(0.0f, -0.5f * line_length), higher_handle_center + ImVec2(0.0f, 0.5f * line_length), white_bg, line_width);
        }
        if (!h_selected) {
            window->DrawList->AddLine(lower_handle_center + ImVec2(-0.5f * line_length, 0.0f), lower_handle_center + ImVec2(0.5f * line_length, 0.0f), white_bg, line_width);
            window->DrawList->AddLine(lower_handle_center + ImVec2(0.0f, -0.5f * line_length), lower_handle_center + ImVec2(0.0f, 0.5f * line_length), white_bg, line_width);
        }
        // draw higher label
        auto text_utf8 = into_u8(higher_label);
        text_content_size = ImGui::CalcTextSize(text_utf8.c_str());
        text_size = text_content_size + text_padding * 2;
        ImVec2 text_start = ImVec2(higher_handle.Min.x - text_size.x - triangle_offsets[2].x, higher_handle_center.y - text_size.y);
        ImRect text_rect(text_start, text_start + text_size);
        ImGui::RenderFrame(text_rect.Min, text_rect.Max, white_bg, false, text_frame_rounding);
        ImVec2 pos_1 = text_rect.Max - triangle_offsets[0];
        ImVec2 pos_2 = pos_1 - triangle_offsets[1];
        ImVec2 pos_3 = pos_1 + triangle_offsets[2];
        window->DrawList->AddTriangleFilled(pos_1, pos_2, pos_3, white_bg);
        ImGui::RenderText(text_start + text_padding, higher_label.c_str());
        // draw lower label
        text_utf8 = into_u8(lower_label);
        text_content_size = ImGui::CalcTextSize(text_utf8.c_str());
        text_size = text_content_size + text_padding * 2;
        text_start        = ImVec2(lower_handle.Min.x - text_size.x - triangle_offsets[2].x, lower_handle_center.y);
        text_rect = ImRect(text_start, text_start + text_size);
        ImGui::RenderFrame(text_rect.Min, text_rect.Max, white_bg, false, text_frame_rounding);
        pos_1 = ImVec2(text_rect.Max.x, text_rect.Min.y) - triangle_offsets[0];
        pos_2 = pos_1 + triangle_offsets[1];
        pos_3 = pos_1 + triangle_offsets[2];
        window->DrawList->AddTriangleFilled(pos_1, pos_2, pos_3, white_bg);
        ImGui::RenderText(text_start + text_padding, lower_label.c_str());
    }
    if (one_layer_flag)
    {
        // update handle position
        value_changed = slider_behavior(id, one_slideable_region, v_min, v_max,
            higher_value, &one_handle, ImGuiSliderFlags_Vertical,
            m_tick_value, m_tick_rect);
        ImVec2 handle_center = one_handle.GetCenter();
        // judge whether to open menu
        if (ImGui::ItemHoverable(one_handle, id) && context.IO.MouseClicked[1])
            m_show_menu = true;
        if ((!ImGui::ItemHoverable(one_handle, id) && context.IO.MouseClicked[1]) ||
            context.IO.MouseClicked[0])
            m_show_menu = false;
        ImVec2 bar_center = higher_handle.GetCenter();
        // draw ticks
        draw_ticks(one_slideable_region);
        // draw colored band
        draw_colored_band(groove, one_slideable_region);
        // draw handle
        window->DrawList->AddLine(ImVec2(mid_x - 0.5 * bar_width, handle_center.y), ImVec2(mid_x + 0.5 * bar_width, handle_center.y), handle_clr, 2 * line_width);
        window->DrawList->AddCircleFilled(handle_center, handle_radius, handle_border_clr);
        window->DrawList->AddCircleFilled(handle_center, handle_radius - handle_border, handle_clr);
        window->DrawList->AddLine(handle_center + ImVec2(-0.5f * line_length, 0.0f), handle_center + ImVec2(0.5f * line_length, 0.0f), white_bg, line_width);
        window->DrawList->AddLine(handle_center + ImVec2(0.0f, -0.5f * line_length), handle_center + ImVec2(0.0f, 0.5f * line_length), white_bg, line_width);
        // draw label
        auto text_utf8 = into_u8(higher_label);
        text_content_size = ImGui::CalcTextSize(text_utf8.c_str());
        text_size = text_content_size + text_padding * 2;
        ImVec2 text_start = ImVec2(one_handle.Min.x - text_size.x, handle_center.y - 0.5 * text_size.y);
        ImRect text_rect = ImRect(text_start, text_start + text_size);
        ImGui::RenderFrame(text_rect.Min, text_rect.Max, white_bg, false, text_frame_rounding);
        ImGui::RenderText(text_start + text_padding, higher_label.c_str());
    }
    return value_changed;
}
References ImDrawList::AddCircleFilled(), ImDrawList::AddLine(), ImDrawList::AddRectFilled(), ImDrawList::AddTriangleFilled(), Slic3r::GUI::BACKGROUND_COLOR_DARK, Slic3r::GUI::BACKGROUND_COLOR_LIGHT, Slic3r::GUI::BRAND_COLOR, ImGui::CalcTextSize(), ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, draw_background_and_groove(), draw_colored_band(), draw_ticks(), ImGuiWindow::DrawList, ImGui::FocusWindow(), get_pos_from_value(), ImRect::GetCenter(), ImGui::GetCurrentWindow(), ImGuiWindow::GetID(), GImGui, Slic3r::GUI::GROOVE_WIDTH, Slic3r::GUI::TickCodeInfo::has_tick_with_code(), ImGuiSliderFlags_Vertical, Slic3r::GUI::into_u8(), ImGuiContext::IO, ImGui::ItemHoverable(), ImGui::ItemSize(), m_is_dark, m_scale, m_show_menu, Slic3r::GUI::m_tick_rect, Slic3r::GUI::m_tick_value, m_ticks, ImRect::Max, ImRect::Min, ImGuiIO::MouseClicked, ImGuiIO::MouseDown, Slic3r::GUI::ONE_LAYER_BUTTON_SIZE, Slic3r::GUI::ONE_LAYER_MARGIN, ImGui::RenderFrame(), ImGui::RenderText(), scale(), ImGui::SetActiveID(), ImGui::SetFocusID(), size, ImGuiWindow::SkipItems, Slic3r::GUI::slider_behavior(), Slic3r::GUI::ssHigher, Slic3r::GUI::ssLower, Slic3r::CustomGCode::ToolChange, ImRect::TranslateY(), ImVec2::x, and ImVec2::y.
Referenced by render().
Member Data Documentation
is_osx
bool Slic3r::GUI::IMSlider::is_osx {false} private
m_alternate_values
std::vector<double> Slic3r::GUI::IMSlider::m_alternate_values private
Referenced by SetSliderAlternateValues().
m_can_change_color
bool Slic3r::GUI::IMSlider::m_can_change_color private
Referenced by render_add_menu(), render_edit_menu(), SetDrawMode(), SetModeAndOnlyExtruder(), and SetTicksValues().
m_custom_gcode
char Slic3r::GUI::IMSlider::m_custom_gcode[1024] = { 0 } private
Referenced by render_input_custom_gcode().
m_custom_icon_id
void* Slic3r::GUI::IMSlider::m_custom_icon_id private
Referenced by draw_ticks(), and init_texture().
m_delete_icon_id
void* Slic3r::GUI::IMSlider::m_delete_icon_id private
Referenced by draw_ticks(), and init_texture().
m_dirty
bool Slic3r::GUI::IMSlider::m_dirty = false private
Referenced by is_dirty(), and set_as_dirty().
m_draw_mode
DrawMode Slic3r::GUI::IMSlider::m_draw_mode = dmRegular private
Referenced by get_label(), render_add_menu(), SetDrawMode(), SetDrawMode(), and SetTicksValues().
m_extra_style
long Slic3r::GUI::IMSlider::m_extra_style private
Referenced by IMSlider(), and SetExtraStyle().
m_extruder_colors
std::vector<std::string> Slic3r::GUI::IMSlider::m_extruder_colors private
Referenced by IMSlider(), draw_colored_band(), get_color_for_tool_change_tick(), render_add_menu(), render_edit_menu(), and SetExtruderColors().
m_force_mode_apply
bool Slic3r::GUI::IMSlider::m_force_mode_apply = true private
Referenced by GetTicksValues().
m_higher_value
int Slic3r::GUI::IMSlider::m_higher_value private
Referenced by IMSlider(), add_code_as_tick(), add_custom_gcode(), correct_higher_value(), correct_lower_value(), get_double_value(), GetActiveValue(), GetHigherValue(), is_higher_at_max(), render(), SetHigherValue(), and SetSelectionSpan().
m_is_dark
bool Slic3r::GUI::IMSlider::m_is_dark = false private
Referenced by draw_background_and_groove(), draw_colored_band(), draw_ticks(), horizontal_slider(), on_change_color_mode(), render(), render_go_to_layer_dialog(), render_input_custom_gcode(), and vertical_slider().
m_is_need_post_tick_changed_event
bool Slic3r::GUI::IMSlider::m_is_need_post_tick_changed_event { false } private
Referenced by IMSlider(), is_need_post_tick_event(), post_ticks_changed_event(), and reset_post_tick_event().
m_is_one_layer
bool Slic3r::GUI::IMSlider::m_is_one_layer = false private
Referenced by correct_higher_value(), correct_lower_value(), is_one_layer(), SetSelectionSpan(), and switch_one_layer_mode().
m_is_spiral_vase
bool Slic3r::GUI::IMSlider::m_is_spiral_vase = false private
Referenced by SetModeAndOnlyExtruder(), and SetTicksValues().
m_is_wipe_tower
bool Slic3r::GUI::IMSlider::m_is_wipe_tower = false private
Referenced by get_label(), get_tick_from_value(), is_wipe_tower_layer(), SetLayersTimes(), SetLayersTimes(), and SetModeAndOnlyExtruder().
m_label_koef
float Slic3r::GUI::IMSlider::m_label_koef {1.0} private
Referenced by get_label(), and SetKoefForLabels().
m_layer_number
char Slic3r::GUI::IMSlider::m_layer_number[64] = { 0 } private
Referenced by render_go_to_layer_dialog().
m_layers_times
std::vector<double> Slic3r::GUI::IMSlider::m_layers_times private
Referenced by get_label(), SetLayersTimes(), and SetLayersTimes().
m_layers_values
std::vector<double> Slic3r::GUI::IMSlider::m_layers_values private
Referenced by get_label(), and SetLayersTimes().
m_lower_value
int Slic3r::GUI::IMSlider::m_lower_value private
Referenced by IMSlider(), add_code_as_tick(), add_custom_gcode(), correct_higher_value(), correct_lower_value(), get_double_value(), GetActiveValue(), GetLowerValue(), is_lower_at_min(), render(), SetLowerValue(), and SetSelectionSpan().
m_max_value
int Slic3r::GUI::IMSlider::m_max_value private
Referenced by IMSlider(), correct_higher_value(), correct_lower_value(), do_go_to_layer(), GetMaxValue(), GetMaxValueD(), is_higher_at_max(), render_go_to_layer_dialog(), SetMaxValue(), SetSelectionSpan(), and switch_one_layer_mode().
m_menu_enable
bool Slic3r::GUI::IMSlider::m_menu_enable = true private
Referenced by render_menu(), and set_menu_enable().
m_min_value
int Slic3r::GUI::IMSlider::m_min_value private
Referenced by IMSlider(), correct_higher_value(), correct_lower_value(), do_go_to_layer(), GetMinValue(), GetMinValueD(), is_lower_at_min(), render_go_to_layer_dialog(), SetSelectionSpan(), and switch_one_layer_mode().
m_mode
Mode Slic3r::GUI::IMSlider::m_mode = SingleExtruder private
Referenced by check_ticks_changed_event(), draw_colored_band(), get_active_extruders_for_tick(), GetManipulationMode(), GetTicksValues(), SetManipulationMode(), SetModeAndOnlyExtruder(), and SetTicksValues().
m_one_layer_off_dark_id
void* Slic3r::GUI::IMSlider::m_one_layer_off_dark_id private
Referenced by init_texture(), and render().
m_one_layer_off_hover_dark_id
void* Slic3r::GUI::IMSlider::m_one_layer_off_hover_dark_id private
Referenced by init_texture(), and render().
m_one_layer_off_hover_id
void* Slic3r::GUI::IMSlider::m_one_layer_off_hover_id private
Referenced by init_texture(), and render().
m_one_layer_off_hover_light_id
void* Slic3r::GUI::IMSlider::m_one_layer_off_hover_light_id private
m_one_layer_off_id
void* Slic3r::GUI::IMSlider::m_one_layer_off_id private
Referenced by init_texture(), and render().
m_one_layer_off_light_id
void* Slic3r::GUI::IMSlider::m_one_layer_off_light_id private
m_one_layer_on_dark_id
void* Slic3r::GUI::IMSlider::m_one_layer_on_dark_id private
Referenced by init_texture(), and render().
m_one_layer_on_hover_dark_id
void* Slic3r::GUI::IMSlider::m_one_layer_on_hover_dark_id private
Referenced by init_texture(), and render().
m_one_layer_on_hover_id
void* Slic3r::GUI::IMSlider::m_one_layer_on_hover_id private
Referenced by init_texture(), and render().
m_one_layer_on_hover_light_id
void* Slic3r::GUI::IMSlider::m_one_layer_on_hover_light_id private
m_one_layer_on_id
void* Slic3r::GUI::IMSlider::m_one_layer_on_id private
Referenced by init_texture(), and render().
m_one_layer_on_light_id
void* Slic3r::GUI::IMSlider::m_one_layer_on_light_id private
m_only_extruder
int Slic3r::GUI::IMSlider::m_only_extruder = -1 private
Referenced by add_code_as_tick(), add_custom_gcode(), draw_colored_band(), get_active_extruders_for_tick(), get_color_for_tool_change_tick(), and SetModeAndOnlyExtruder().
m_pause_icon_id
void* Slic3r::GUI::IMSlider::m_pause_icon_id private
Referenced by draw_ticks(), and init_texture().
m_print_obj_idxs
std::string Slic3r::GUI::IMSlider::m_print_obj_idxs private
Referenced by IsNewPrint().
m_render_as_disabled
bool Slic3r::GUI::IMSlider::m_render_as_disabled { false } private
Referenced by is_rendering_as_disabled(), and set_render_as_disabled().
m_scale
float Slic3r::GUI::IMSlider::m_scale = 1.0
Referenced by draw_colored_band(), draw_ticks(), horizontal_slider(), render(), render_add_menu(), render_edit_menu(), render_go_to_layer_dialog(), render_input_custom_gcode(), render_menu(), set_scale(), show_tooltip(), and vertical_slider().
m_selection
SelectedSlider Slic3r::GUI::IMSlider::m_selection private
Referenced by IMSlider(), add_code_as_tick(), add_custom_gcode(), GetActiveValue(), GetSelection(), on_mouse_wheel(), render(), SetHigherValue(), SetLowerValue(), and switch_one_layer_mode().
m_show_custom_gcode_window
bool Slic3r::GUI::IMSlider::m_show_custom_gcode_window = false private
Referenced by render_add_menu(), render_edit_menu(), render_input_custom_gcode(), SetModeAndOnlyExtruder(), and switch_one_layer_mode().
m_show_go_to_layer_dialog
bool Slic3r::GUI::IMSlider::m_show_go_to_layer_dialog = false private
Referenced by render_add_menu(), render_go_to_layer_dialog(), SetModeAndOnlyExtruder(), and show_go_to_layer().
m_show_menu
bool Slic3r::GUI::IMSlider::m_show_menu = false private
Referenced by render_add_menu(), render_edit_menu(), SetModeAndOnlyExtruder(), and vertical_slider().
m_style
long Slic3r::GUI::IMSlider::m_style private
Referenced by IMSlider(), and is_horizontal().
m_tick_change_event_type
Type Slic3r::GUI::IMSlider::m_tick_change_event_type private
Referenced by IMSlider(), get_post_tick_event_type(), post_ticks_changed_event(), and reset_post_tick_event().
m_ticks
TickCodeInfo Slic3r::GUI::IMSlider::m_ticks private
Referenced by IMSlider(), add_code_as_tick(), add_custom_gcode(), check_ticks_changed_event(), delete_tick(), draw_colored_band(), draw_ticks(), get_active_extruders_for_tick(), get_color_for_tool_change_tick(), GetTicksValues(), render_menu(), SetModeAndOnlyExtruder(), SetTicksValues(), UseDefaultColors(), and vertical_slider().
m_values
std::vector<double> Slic3r::GUI::IMSlider::m_values private
Referenced by add_code_as_tick(), get_double_value(), get_label(), get_tick_from_value(), GetMaxValueD(), GetMinValueD(), GetTicksValues(), is_wipe_tower_layer(), SetLayersTimes(), SetSliderValues(), and SetTicksValues().
m_zero_layer_height
float Slic3r::GUI::IMSlider::m_zero_layer_height = 0.0f private
The documentation for this class was generated from the following files:
src/slic3r/GUI/IMSlider.hpp
src/slic3r/GUI/IMSlider.cpp