OrcaSlicer: orgQhull::PointCoordinates Class Reference
orgQhull::PointCoordinates Class Reference
#include <src/qhull/src/libqhullcpp/PointCoordinates.h>
Public Types
Subtypes
typedef QhullPoints::const_iterator ConstIterator
typedef QhullPoints::iterator Iterator
Public Member Functions
Construct
Comment describing PointCoordinates
QhullPoint, PointCoordinates, and QhullPoints have similar constructors If Qhull/QhullQh is not initialized, then dimension()==0 PointCoordinates();
PointCoordinates ()
PointCoordinates (const std::string &aComment)
PointCoordinates (int pointDimension, const std::string &aComment)
PointCoordinates (const Qhull &q)
Qhull/QhullQh used for dimension() and QhullPoint equality.
PointCoordinates (const Qhull &q, const std::string &aComment)
PointCoordinates (const Qhull &q, int pointDimension, const std::string &aComment)
PointCoordinates (const Qhull &q, int pointDimension, const std::string &aComment, countT coordinatesCount, const coordT *c)
PointCoordinates (QhullQh *qqh)
Use append() and appendPoints() for Coordinates and vector<coordT>
PointCoordinates (QhullQh *qqh, const std::string &aComment)
PointCoordinates (QhullQh *qqh, int pointDimension, const std::string &aComment)
PointCoordinates (QhullQh *qqh, int pointDimension, const std::string &aComment, countT coordinatesCount, const coordT *c)
PointCoordinates (const PointCoordinates &other)
Use append() and appendPoints() for Coordinates and vector<coordT>
PointCoordinates & operator= (const PointCoordinates &other)
~PointCoordinates ()
Convert
QhullPoints coordinates, constData, data, count, size
void append (const std::vector< coordT > &otherCoordinates)
std::vector< coordT > toStdVector () const
Foreach
See QhullPoints for begin, constBegin, end
Coordinates::ConstIterator beginCoordinates () const
Coordinates::Iterator beginCoordinates ()
Coordinates::ConstIterator beginCoordinates (countT pointIndex) const
Coordinates::Iterator beginCoordinates (countT pointIndex)
Coordinates::ConstIterator endCoordinates () const
Coordinates::Iterator endCoordinates ()
Modify
void append (countT coordinatesCount, const coordT *c)
void append (const coordT &c)
Dimension previously defined.
void append (const QhullPoint &p)
Dimension previously defined.
void append (const Coordinates &c)
See convert for std::vector and QList.
void append (const PointCoordinates &other)
void appendComment (const std::string &s)
void appendPoints (std::istream &in)
Read PointCoordinates from istream. First two numbers are dimension and count. A non-digit starts a rboxCommand. Overwrites describe_points. See qh_readpoints [io.c].
PointCoordinates & operator+= (const PointCoordinates &other)
PointCoordinates & operator+= (const coordT &c)
PointCoordinates & operator+= (const QhullPoint &p)
PointCoordinates & operator<< (const PointCoordinates &other)
PointCoordinates & operator<< (const coordT &c)
PointCoordinates & operator<< (const QhullPoint &p)
void reserveCoordinates (countT newCoordinates)
GetSet
const QhullPoint at (countT idx) const
const QhullPoint back () const
QhullPoint back ()
ConstIterator begin () const
Iterator begin ()
ConstIterator constBegin () const
const coordT * constData () const
ConstIterator constEnd () const
coordT * coordinates () const
countT coordinateCount () const
countT count () const
const coordT * data () const
coordT * data ()
void defineAs (int pointDimension, countT coordinatesCount, coordT *c)
void defineAs (const QhullPoints &other)
int dimension () const
ConstIterator end () const
Iterator end ()
coordT * extraCoordinates () const
countT extraCoordinatesCount () const
const QhullPoint first () const
QhullPoint first ()
const QhullPoint front () const
QhullPoint front ()
bool includesCoordinates (const coordT *c) const
bool isEmpty () const
const QhullPoint last () const
QhullPoint last ()
bool operator== (const QhullPoints &other) const
QhullPoints is equal if the same address, or if the coordinates are identical Use QhullPoint.operator==() for DISTround equality.
bool operator!= (const QhullPoints &other) const
QhullPoint operator[] (countT idx) const
QhullQh * qh () const
void resetQhullQh (QhullQh *qqh)
Reset QhullPoints to QhullQh and its hullDimension() Does not free up old qh_qh.
size_t size () const
QhullPoint value (countT idx) const
QhullPoint value (countT idx, QhullPoint &defaultValue) const
Methods
countT count (const QhullPoint &t) const
bool contains (const QhullPoint &t) const
countT indexOf (const coordT *pointCoordinates) const
countT indexOf (const coordT *pointCoordinates, int noThrow) const
countT indexOf (const QhullPoint &t) const
countT lastIndexOf (const QhullPoint &t) const
QhullPoints mid (countT idx, countT length=-1) const
Returns a subset of the points, not a copy.
IO
PrintPoints print (const char *message) const
PrintPoints printWithIdentifier (const char *message) const
Private Member Functions
Helpers
int indexOffset (int i) const
Private Attributes
Fields
Coordinates point_coordinates
std::string describe_points
std::vector of point coordinates may have extraCoordinates()
Fields
coordT * point_first
First coordinate of an array of points of point_dimension.
coordT * point_end
End of point coordinates (end>=first). Trailing coordinates ignored.
QhullQh * qh_qh
Maybe initialized NULL to allow ownership by RboxPoints qh_qh used for QhullPoint() and qh_qh->hull_dim in constructor.
int point_dimension
Dimension, >=0.
GetSet
void checkValid () const
std::string comment () const
void makeValid ()
const Coordinates & getCoordinates () const
void setComment (const std::string &s)
void setDimension (int i)
PointCoordinates operator+ (const PointCoordinates &other) const
void defineAs (countT coordinatesCount, coordT *c)
disable QhullPoints.defineAs()
Detailed Description
Member Typedef Documentation
ConstIterator
typedef QhullPoints::const_iterator orgQhull::QhullPoints::ConstIterator inherited
Iterator
typedef QhullPoints::iterator orgQhull::QhullPoints::Iterator inherited
Constructor & Destructor Documentation
PointCoordinates() [1/12]
orgQhull::PointCoordinates::PointCoordinates ()
: QhullPoints()
, point_coordinates()
, describe_points()
{
}
PointCoordinates() [2/12]
orgQhull::PointCoordinates::PointCoordinates (const std::string & aComment) explicit
: QhullPoints()
, point_coordinates()
, describe_points(aComment)
{
}
PointCoordinates() [3/12]
orgQhull::PointCoordinates::PointCoordinates (int pointDimension, const std::string & aComment)
: QhullPoints()
, point_coordinates()
, describe_points(aComment)
{
    setDimension(pointDimension);
}
References setDimension().
PointCoordinates() [4/12]
orgQhull::PointCoordinates::PointCoordinates (const Qhull & q) explicit
Qhull/QhullQh used for dimension() and QhullPoint equality.
Qhull and QhullQh constructors are the same.
: QhullPoints(q)
, point_coordinates()
, describe_points()
{
}
PointCoordinates() [5/12]
orgQhull::PointCoordinates::PointCoordinates (const Qhull & q, const std::string & aComment)
: QhullPoints(q)
, point_coordinates()
, describe_points(aComment)
{
}
PointCoordinates() [6/12]
orgQhull::PointCoordinates::PointCoordinates (const Qhull & q, int pointDimension, const std::string & aComment)
: QhullPoints(q)
, point_coordinates()
, describe_points(aComment)
{
    setDimension(pointDimension);
}
References setDimension().
PointCoordinates() [7/12]
orgQhull::PointCoordinates::PointCoordinates (const Qhull & q, int pointDimension, const std::string & aComment, countT coordinatesCount, const coordT * c)
: QhullPoints(q)
, point_coordinates()
, describe_points(aComment)
{
    setDimension(pointDimension);
    append(coordinatesCount, c);
}
References append(), and setDimension().
PointCoordinates() [8/12]
orgQhull::PointCoordinates::PointCoordinates (QhullQh * qqh) explicit
Use append() and appendPoints() for Coordinates and vector<coordT>
: QhullPoints(qqh)
, point_coordinates()
, describe_points()
{
}
PointCoordinates() [9/12]
orgQhull::PointCoordinates::PointCoordinates (QhullQh * qqh, const std::string & aComment)
: QhullPoints(qqh)
, point_coordinates()
, describe_points(aComment)
{
}
PointCoordinates() [10/12]
orgQhull::PointCoordinates::PointCoordinates (QhullQh * qqh, int pointDimension, const std::string & aComment)
: QhullPoints(qqh)
, point_coordinates()
, describe_points(aComment)
{
    setDimension(pointDimension);
}
PointCoordinates() [11/12]
orgQhull::PointCoordinates::PointCoordinates (QhullQh * qqh, int pointDimension, const std::string & aComment, countT coordinatesCount, const coordT * c)
: QhullPoints(qqh)
, point_coordinates()
, describe_points(aComment)
{
    setDimension(pointDimension);
    append(coordinatesCount, c);
}
References append(), and setDimension().
PointCoordinates() [12/12]
orgQhull::PointCoordinates::PointCoordinates (const PointCoordinates & other)
Use append() and appendPoints() for Coordinates and vector<coordT>
: QhullPoints(other)
, point_coordinates(other.point_coordinates)
, describe_points(other.describe_points)
{
    makeValid();  // Update point_first and point_end
}
References makeValid().
~PointCoordinates()
orgQhull::PointCoordinates::~PointCoordinates ()
{ }
Member Function Documentation
append() [1/6]
void orgQhull::PointCoordinates::append (const Coordinates & c) inline
See convert for std::vector and QList.
{ append(c.count(), c.data()); }
References append().
Referenced by append().
append() [2/6]
void orgQhull::PointCoordinates::append (const coordT & c) inline
Dimension previously defined.
{ append(1, &c); }
References append().
Referenced by append().
append() [3/6]
void orgQhull::PointCoordinates::append (const PointCoordinates & other)
{
    setDimension(other.dimension());
    append(other.coordinateCount(), other.data());
}//append PointCoordinates
References append(), orgQhull::QhullPoints::coordinateCount(), orgQhull::QhullPoints::data(), orgQhull::QhullPoints::dimension(), and setDimension().
append() [4/6]
void orgQhull::PointCoordinates::append (const QhullPoint & p)
Dimension previously defined.
{
    setDimension(p.dimension());
    append(p.dimension(), p.coordinates());
}//append QhullPoint
References append(), orgQhull::QhullPoint::coordinates(), orgQhull::QhullPoint::dimension(), and setDimension().
append() [5/6]
void orgQhull::PointCoordinates::append (const std::vector< coordT > & otherCoordinates) inline
{ if(!otherCoordinates.empty()){ append((int)otherCoordinates.size(), &otherCoordinates[0]); } }
References append().
Referenced by PointCoordinates(), PointCoordinates(), append(), append(), append(), operator+=(), operator+=(), operator+=(), orgQhull::RboxPoints_test::t_change(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::PointCoordinates_test::t_getset(), and orgQhull::PointCoordinates_test::t_modify().
append() [6/6]
void orgQhull::PointCoordinates::append (countT coordinatesCount, const coordT * c)
{
    if(coordinatesCount<=0){
        return;
    }
    if(includesCoordinates(c)){
        throw QhullError(10065, "Qhull error: can not append a subset of PointCoordinates to itself.  The coordinates for point %d may move.", indexOf(c, QhullError::NOthrow));
    }
    reserveCoordinates(coordinatesCount);
    std::copy(c, c+coordinatesCount, std::back_inserter(point_coordinates));
    makeValid();
}//append coordT
References orgQhull::QhullPoints::includesCoordinates(), orgQhull::QhullPoints::indexOf(), makeValid(), orgQhull::QhullError::NOthrow, point_coordinates, and reserveCoordinates().
appendComment()
void orgQhull::PointCoordinates::appendComment (const std::string & s)
{
    if(char c= s[0] && describe_points.empty()){
        if(c=='-' || isdigit(c)){
            throw QhullError(10028, "Qhull argument error: comments can not start with a number or minus, %s", 0, 0, 0.0, s.c_str());
        }
    }
    describe_points += s;
}//appendComment
References describe_points.
Referenced by orgQhull::PointCoordinates_test::t_modify().
appendPoints()
void orgQhull::PointCoordinates::appendPoints (std::istream & in)
Read PointCoordinates from istream. First two numbers are dimension and count. A non-digit starts a rboxCommand. Overwrites describe_points. See qh_readpoints [io.c].
{
    int inDimension;
    countT inCount;
    in >> ws >> inDimension >> ws;
    if(!in.good()){
        in.clear();
        string remainder;
        getline(in, remainder);
        throw QhullError(10005, "Qhull error: input did not start with dimension or count -- %s", 0, 0, 0, remainder.c_str());
    }
    char c= (char)in.peek();
    if(c!='-' && !isdigit(c)){         // Comments start with a non-digit
        getline(in, describe_points);
        in >> ws;
    }
    in >> inCount >> ws;
    if(!in.good()){
        in.clear();
        string remainder;
        getline(in, remainder);
        throw QhullError(10009, "Qhull error: input did not start with dimension and count -- %d %s", inDimension, 0, 0, remainder.c_str());
    }
    c= (char)in.peek();
    if(c!='-' && !isdigit(c)){         // Comments start with a non-digit
        getline(in, describe_points);
        in >> ws;
    }
    if(inCount<inDimension){           // Count may precede dimension
        std::swap(inCount, inDimension);
    }
    setDimension(inDimension);
    reserveCoordinates(inCount*inDimension);
    countT coordinatesCount= 0;
    while(!in.eof()){
        realT p;
        in >> p >> ws;
        if(in.fail()){
            in.clear();
            string remainder;
            getline(in, remainder);
            throw QhullError(10008, "Qhull error: failed to read coordinate %d  of point %d\n   %s", coordinatesCount % inDimension, coordinatesCount/inDimension, 0, remainder.c_str());
        }else{
            point_coordinates.push_back(p);
            coordinatesCount++;
        }
    }
    if(coordinatesCount != inCount*inDimension){
        if(coordinatesCount%inDimension==0){
            throw QhullError(10006, "Qhull error: expected %d %d-d PointCoordinates but read %i PointCoordinates", int(inCount), inDimension, 0.0, int(coordinatesCount/inDimension));
        }else{
            throw QhullError(10012, "Qhull error: expected %d %d-d PointCoordinates but read %i PointCoordinates plus %f extra coordinates", inCount, inDimension, float(coordinatesCount%inDimension), coordinatesCount/inDimension);
        }
    }
    makeValid();
}//appendPoints istream
References describe_points, in, makeValid(), point_coordinates, orgQhull::Coordinates::push_back(), realT, reserveCoordinates(), and setDimension().
Referenced by orgQhull::PointCoordinates_test::t_append_points().
at()
const QhullPoint orgQhull::QhullPoints::at (countT idx) const inline inherited
{ /* point_first==0 caught by point_end assert */ coordT *p= point_first+idx*point_dimension; QHULL_ASSERT(p<point_end); return QhullPoint(qh_qh, point_dimension, p); }
References coordT, orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, orgQhull::QhullPoints::point_first, orgQhull::QhullPoints::qh_qh, and QHULL_ASSERT.
Referenced by orgQhull::QhullPoints::operator[](), orgQhull::PointCoordinates_test::t_element(), and orgQhull::QhullPoints_test::t_element().
back() [1/2]
QhullPoint orgQhull::QhullPoints::back () inline inherited
{ return last(); }
References orgQhull::QhullPoints::last().
back() [2/2]
const QhullPoint orgQhull::QhullPoints::back () const inline inherited
{ return last(); }
References orgQhull::QhullPoints::last().
Referenced by orgQhull::PointCoordinates_test::t_element(), and orgQhull::QhullPoints_test::t_element().
begin() [1/2]
Iterator orgQhull::QhullPoints::begin () inline inherited
{ return Iterator(*this); }
begin() [2/2]
ConstIterator orgQhull::QhullPoints::begin () const inline inherited
{ return ConstIterator(*this); }
Referenced by orgQhull::QhullPoints::contains(), orgQhull::QhullPoints::count(), orgQhull::QhullPoints::indexOf(), orgQhull::QhullPoints::lastIndexOf(), operator<<(), orgQhull::QhullPoints::operator==(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinates_test::t_foreach(), and orgQhull::QhullPoints_test::t_iterator().
beginCoordinates() [1/4]
Coordinates::Iterator orgQhull::PointCoordinates::beginCoordinates () inline
{ return point_coordinates.begin(); }
References orgQhull::Coordinates::begin(), and point_coordinates.
beginCoordinates() [2/4]
Coordinates::ConstIterator orgQhull::PointCoordinates::beginCoordinates () const inline
{ return point_coordinates.begin(); }
References orgQhull::Coordinates::begin(), and point_coordinates.
Referenced by operator<<(), orgQhull::RboxPoints_test::t_change(), orgQhull::PointCoordinates_test::t_foreach(), and orgQhull::RboxPoints_test::t_foreach().
beginCoordinates() [3/4]
Coordinates::Iterator orgQhull::PointCoordinates::beginCoordinates (countT pointIndex)
{
    return point_coordinates.begin()+indexOffset(pointIndex);
}
References orgQhull::Coordinates::begin(), indexOffset(), and point_coordinates.
beginCoordinates() [4/4]
Coordinates::ConstIterator orgQhull::PointCoordinates::beginCoordinates (countT pointIndex) const
{
    return point_coordinates.begin()+indexOffset(pointIndex);
}
References orgQhull::Coordinates::begin(), indexOffset(), and point_coordinates.
checkValid()
void orgQhull::PointCoordinates::checkValid () const
{
    if(getCoordinates().data()!=data()
    || getCoordinates().count()!=coordinateCount()){
        throw QhullError(10060, "Qhull error: first point (%x) is not PointCoordinates.data() or count (%d) is not PointCoordinates.count (%d)", coordinateCount(), getCoordinates().count(), 0.0, data());
    }
}//checkValid
References orgQhull::QhullPoints::coordinateCount(), orgQhull::QhullPoints::count(), orgQhull::QhullPoints::data(), and getCoordinates().
Referenced by operator<<(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::PointCoordinates_test::t_getset(), and orgQhull::PointCoordinates_test::t_modify().
comment()
std::string orgQhull::PointCoordinates::comment () const inline
{ return describe_points; }
References describe_points.
Referenced by orgQhull::RboxPoints::appendPoints(), operator<<(), orgQhull::Qhull::runQhull(), orgQhull::RboxPoints_test::t_construct(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::PointCoordinates_test::t_getset(), and orgQhull::PointCoordinates_test::t_modify().
constBegin()
ConstIterator orgQhull::QhullPoints::constBegin () const inline inherited
{ return ConstIterator(*this); }
Referenced by orgQhull::PointCoordinatesIterator::findPrevious(), orgQhull::QhullPointsIterator::findPrevious(), orgQhull::PointCoordinatesIterator::hasPrevious(), orgQhull::QhullPointsIterator::hasPrevious(), orgQhull::PointCoordinatesIterator::operator=(), orgQhull::QhullPointsIterator::operator=(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinatesIterator::toFront(), and orgQhull::QhullPointsIterator::toFront().
constData()
const coordT * orgQhull::QhullPoints::constData () const inline inherited
{ return point_first; }
References orgQhull::QhullPoints::point_first.
Referenced by orgQhull::PointCoordinates_test::t_convert(), and orgQhull::QhullPoints_test::t_convert().
constEnd()
ConstIterator orgQhull::QhullPoints::constEnd () const inline inherited
{ return ConstIterator(qh_qh, point_dimension, point_end); }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, and orgQhull::QhullPoints::qh_qh.
Referenced by orgQhull::PointCoordinatesIterator::findNext(), orgQhull::QhullPointsIterator::findNext(), orgQhull::PointCoordinatesIterator::hasNext(), orgQhull::QhullPointsIterator::hasNext(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinates_test::t_foreach(), orgQhull::PointCoordinatesIterator::toBack(), and orgQhull::QhullPointsIterator::toBack().
contains()
bool orgQhull::QhullPoints::contains (const QhullPoint & t) const inherited
{
    const_iterator i= begin();
    while(i != end()){
        if(*i==t){
            return true;
        }
        i++;
    }
    return false;
}//contains
References orgQhull::QhullPoints::begin(), and orgQhull::QhullPoints::end().
Referenced by orgQhull::PointCoordinates_test::t_search(), and orgQhull::QhullPoints_test::t_search().
coordinateCount()
countT orgQhull::QhullPoints::coordinateCount () const inline inherited
{ return (countT)(point_end-point_first); } // WARN64
References orgQhull::QhullPoints::point_end, and orgQhull::QhullPoints::point_first.
Referenced by append(), checkValid(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullPoints_test::t_getset(), and orgQhull::QhullPoints_test::t_search().
coordinates()
coordT * orgQhull::QhullPoints::coordinates () const inline inherited
{ return point_first; }
References orgQhull::QhullPoints::point_first.
Referenced by orgQhull::RboxPoints::appendPoints(), orgQhull::Qhull::runQhull(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullPoints_test::t_getset(), and orgQhull::QhullPoints_test::t_iterator().
count() [1/2]
countT orgQhull::QhullPoints::count () const inline inherited
{ return (countT)size(); } // WARN64
References orgQhull::QhullPoints::size().
Referenced by orgQhull::RboxPoints::appendPoints(), checkValid(), orgQhull::QhullPoints::lastIndexOf(), orgQhull::QhullPoints::mid(), operator<<(), orgQhull::RboxPoints::reservePoints(), orgQhull::Qhull::runQhull(), orgQhull::PointCoordinates_test::t_append_points(), orgQhull::RboxPoints_test::t_change(), orgQhull::RboxPoints_test::t_construct(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullPoints_test::t_element(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullPoints_test::t_getset(), orgQhull::RboxPoints_test::t_getSet(), orgQhull::PointCoordinates_test::t_modify(), orgQhull::PointCoordinates_test::t_search(), orgQhull::QhullPoints_test::t_search(), orgQhull::QhullPoints::value(), and orgQhull::QhullPoints::value().
count() [2/2]
countT orgQhull::QhullPoints::count (const QhullPoint & t) const inherited
{
    countT n= 0;
    const_iterator i= begin();
    while(i != end()){
        if(*i==t){
            ++n;
        }
        i++;
    }
    return n;
}//count
References orgQhull::QhullPoints::begin(), orgQhull::QhullPoints::end(), and n.
data() [1/2]
coordT * orgQhull::QhullPoints::data () inline inherited
{ return point_first; }
References orgQhull::QhullPoints::point_first.
data() [2/2]
const coordT * orgQhull::QhullPoints::data () const inline inherited
{ return point_first; }
References orgQhull::QhullPoints::point_first.
Referenced by append(), checkValid(), orgQhull::PointCoordinates_test::t_convert(), orgQhull::QhullPoints_test::t_convert(), orgQhull::QhullPoints_test::t_getset(), and orgQhull::QhullPoints_test::t_search().
defineAs() [1/3]
void orgQhull::QhullPoints::defineAs (const QhullPoints & other) inline inherited
{ point_first= other.point_first; point_end= other.point_end; qh_qh= other.qh_qh; point_dimension= other.point_dimension; }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, orgQhull::QhullPoints::point_first, and orgQhull::QhullPoints::qh_qh.
defineAs() [2/3]
void orgQhull::PointCoordinates::defineAs (countT coordinatesCount, coordT * c) inline private
disable QhullPoints.defineAs()
{ QhullPoints::defineAs(coordinatesCount, c); }
References orgQhull::QhullPoints::defineAs().
Referenced by makeValid().
defineAs() [3/3]
void orgQhull::QhullPoints::defineAs (int pointDimension, countT coordinatesCount, coordT * c) inline inherited
{ QHULL_ASSERT(pointDimension>=0 && coordinatesCount>=0 && c!=0); point_first= c; point_end= c+coordinatesCount; point_dimension= pointDimension; }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, orgQhull::QhullPoints::point_first, and QHULL_ASSERT.
Referenced by defineAs(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_qh(), and orgQhull::QhullPoints_test::t_getset().
dimension()
int orgQhull::QhullPoints::dimension () const inline inherited
{ return point_dimension; }
References orgQhull::QhullPoints::point_dimension.
Referenced by append(), indexOffset(), operator<<(), orgQhull::RboxPoints::reservePoints(), orgQhull::Qhull::runQhull(), setDimension(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::RboxPoints_test::t_construct(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::PointCoordinates_test::t_convert(), orgQhull::QhullPoints_test::t_convert(), orgQhull::QhullPoints_test::t_getset(), orgQhull::RboxPoints_test::t_getSet(), and orgQhull::QhullPoints_test::t_iterator().
end() [1/2]
Iterator orgQhull::QhullPoints::end () inline inherited
{ return Iterator(qh_qh, point_dimension, point_end); }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, and orgQhull::QhullPoints::qh_qh.
end() [2/2]
ConstIterator orgQhull::QhullPoints::end () const inline inherited
{ return ConstIterator(qh_qh, point_dimension, point_end); }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, and orgQhull::QhullPoints::qh_qh.
Referenced by orgQhull::QhullPoints::contains(), orgQhull::QhullPoints::count(), orgQhull::QhullPoints::indexOf(), orgQhull::QhullPoints::lastIndexOf(), operator<<(), orgQhull::QhullPoints::operator==(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::PointCoordinates_test::t_foreach(), and orgQhull::QhullPoints_test::t_iterator().
endCoordinates() [1/2]
Coordinates::Iterator orgQhull::PointCoordinates::endCoordinates () inline
{ return point_coordinates.end(); }
References orgQhull::Coordinates::end(), and point_coordinates.
endCoordinates() [2/2]
Coordinates::ConstIterator orgQhull::PointCoordinates::endCoordinates () const inline
{ return point_coordinates.end(); }
References orgQhull::Coordinates::end(), and point_coordinates.
Referenced by orgQhull::PointCoordinates_test::t_foreach(), and orgQhull::RboxPoints_test::t_foreach().
extraCoordinates()
coordT * orgQhull::QhullPoints::extraCoordinates () const inline inherited
{ return extraCoordinatesCount() ? (point_end-extraCoordinatesCount()) : 0; }
References orgQhull::QhullPoints::extraCoordinatesCount(), and orgQhull::QhullPoints::point_end.
Referenced by orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), and orgQhull::QhullPoints_test::t_getset().
extraCoordinatesCount()
countT orgQhull::QhullPoints::extraCoordinatesCount () const inherited
{
    if(point_dimension>0){
        return (countT)((point_end-point_first)%(size_t)point_dimension);
    }
    return 0;
}//extraCoordinatesCount
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, and orgQhull::QhullPoints::point_first.
Referenced by orgQhull::RboxPoints::appendPoints(), orgQhull::QhullPoints::extraCoordinates(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_getset(), and orgQhull::PointCoordinates_test::t_modify().
first() [1/2]
QhullPoint orgQhull::QhullPoints::first () inline inherited
{ return QhullPoint(qh_qh, point_dimension, point_first); }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_first, and orgQhull::QhullPoints::qh_qh.
first() [2/2]
const QhullPoint orgQhull::QhullPoints::first () const inline inherited
{ return QhullPoint(qh_qh, point_dimension, point_first); }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_first, and orgQhull::QhullPoints::qh_qh.
Referenced by orgQhull::QhullPoints::front(), orgQhull::QhullPoints::front(), orgQhull::PointCoordinates_test::t_element(), orgQhull::QhullPoints_test::t_element(), orgQhull::PointCoordinates_test::t_modify(), and orgQhull::QhullPoints_test::t_search().
front() [1/2]
QhullPoint orgQhull::QhullPoints::front () inline inherited
{ return first(); }
References orgQhull::QhullPoints::first().
front() [2/2]
const QhullPoint orgQhull::QhullPoints::front () const inline inherited
{ return first(); }
References orgQhull::QhullPoints::first().
Referenced by orgQhull::QhullPoints_test::t_element().
getCoordinates()
const Coordinates & orgQhull::PointCoordinates::getCoordinates () const inline
{ return point_coordinates; }
References point_coordinates.
Referenced by checkValid(), and orgQhull::PointCoordinates_test::t_getset().
includesCoordinates()
bool orgQhull::QhullPoints::includesCoordinates (const coordT * c) const inline inherited
{ return c>=point_first && c<point_end; }
References orgQhull::QhullPoints::point_end, and orgQhull::QhullPoints::point_first.
Referenced by append(), orgQhull::QhullPoints::indexOf(), orgQhull::QhullPoints::indexOf(), and orgQhull::QhullPoints_test::t_getset().
indexOf() [1/3]
countT orgQhull::QhullPoints::indexOf (const coordT * pointCoordinates) const inherited
{
    if(!includesCoordinates(pointCoordinates) || point_dimension==0){
        return -1;
    }
    size_t offset= pointCoordinates-point_first;
    countT idx= (countT)(offset/(size_t)point_dimension);
    countT extra= (countT)(offset%(size_t)point_dimension);
    if(extra!=0){
        throw QhullError(10066, "Qhull error: coordinates %x are not at point boundary (extra %d at index %d)", extra, idx, 0.0, pointCoordinates);
    }
    return idx;
}//indexOf coordT
References orgQhull::QhullPoints::includesCoordinates(), orgQhull::QhullPoints::point_dimension, and orgQhull::QhullPoints::point_first.
Referenced by append(), orgQhull::QhullPoints::indexOf(), orgQhull::PointCoordinates_test::t_search(), and orgQhull::QhullPoints_test::t_search().
indexOf() [2/3]
countT orgQhull::QhullPoints::indexOf (const coordT * pointCoordinates, int noThrow) const inherited
{
    size_t extra= 0;
    if(noThrow){
        if(!includesCoordinates(pointCoordinates) || point_dimension==0){
            return -1;
        }
        extra= (pointCoordinates-point_first)%(size_t)point_dimension;
    }
    return indexOf(pointCoordinates-extra);
}//indexOf coordT noThrow
References orgQhull::QhullPoints::includesCoordinates(), orgQhull::QhullPoints::indexOf(), orgQhull::QhullPoints::point_dimension, and orgQhull::QhullPoints::point_first.
indexOf() [3/3]
countT orgQhull::QhullPoints::indexOf (const QhullPoint & t) const inherited
{
    countT j=0;
    const_iterator i= begin();
    while(i!=end()){
        if(*i==t){
            return j;
        }
        ++i;
        ++j;
    }
    return -1;
}//indexOf
References orgQhull::QhullPoints::begin(), and orgQhull::QhullPoints::end().
indexOffset()
countT orgQhull::PointCoordinates::indexOffset (int i) const private
{
    countT n= i*dimension();
    countT coordinatesCount= point_coordinates.count();
    if(i<0 || n>coordinatesCount){
        throw QhullError(10061, "Qhull error: point_coordinates is too short (%d) for point %d", coordinatesCount, i);
    }
    return n;
}
References orgQhull::Coordinates::count(), orgQhull::QhullPoints::dimension(), n, and point_coordinates.
Referenced by beginCoordinates(), and beginCoordinates().
isEmpty()
bool orgQhull::QhullPoints::isEmpty () const inline inherited
{ return (point_end==point_first || point_dimension==0); }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, and orgQhull::QhullPoints::point_first.
Referenced by orgQhull::RboxPoints::rboxMessage(), orgQhull::RboxPoints_test::t_construct(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullPoints_test::t_element(), and orgQhull::QhullPoints_test::t_getset().
last() [1/2]
QhullPoint orgQhull::QhullPoints::last () inline inherited
{ QHULL_ASSERT(point_first!=0); return QhullPoint(qh_qh, point_dimension, point_end - point_dimension); }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, orgQhull::QhullPoints::point_first, orgQhull::QhullPoints::qh_qh, and QHULL_ASSERT.
last() [2/2]
const QhullPoint orgQhull::QhullPoints::last () const inline inherited
{ QHULL_ASSERT(point_first!=0); return QhullPoint(qh_qh, point_dimension, point_end - point_dimension); }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, orgQhull::QhullPoints::point_first, orgQhull::QhullPoints::qh_qh, and QHULL_ASSERT.
Referenced by orgQhull::QhullPoints::back(), orgQhull::QhullPoints::back(), orgQhull::PointCoordinates_test::t_element(), orgQhull::QhullPoints_test::t_element(), orgQhull::PointCoordinates_test::t_modify(), and orgQhull::QhullPoints_test::t_search().
lastIndexOf()
countT orgQhull::QhullPoints::lastIndexOf (const QhullPoint & t) const inherited
{
    countT j= count();
    const_iterator i= end();
    while(i != begin()){
        --i;
        --j;
        if(*i==t){
            return j;
        }
    }
    return -1;
}//lastIndexOf
References orgQhull::QhullPoints::begin(), orgQhull::QhullPoints::count(), and orgQhull::QhullPoints::end().
Referenced by orgQhull::PointCoordinates_test::t_modify(), orgQhull::PointCoordinates_test::t_search(), and orgQhull::QhullPoints_test::t_search().
makeValid()
void orgQhull::PointCoordinates::makeValid () inline
{ defineAs(point_coordinates.count(), point_coordinates.data()); }
References orgQhull::Coordinates::count(), orgQhull::Coordinates::data(), defineAs(), and point_coordinates.
Referenced by PointCoordinates(), append(), appendPoints(), operator=(), reserveCoordinates(), and orgQhull::PointCoordinates_test::t_getset().
mid()
QhullPoints orgQhull::QhullPoints::mid (countT idx, countT length = -1) const inherited
Returns a subset of the points, not a copy.
{
    countT n= count();
    if(idx<0 || idx>=n){
        n= 0;
    }else if(length<0 || idx+length>=n){
        n -= idx;
    }else{
        n -= idx+length;
    }
    return QhullPoints(qh_qh, point_dimension, n*point_dimension, point_first+idx*point_dimension);
}//mid
References orgQhull::QhullPoints::QhullPoints(), orgQhull::QhullPoints::count(), length(), n, orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_first, and orgQhull::QhullPoints::qh_qh.
Referenced by orgQhull::PointCoordinates_test::t_element(), and orgQhull::QhullPoints_test::t_element().
operator!=()
bool orgQhull::QhullPoints::operator!= (const QhullPoints & other) const inline inherited
{ return ! operator==(other); }
References orgQhull::QhullPoints::operator==().
operator+()
PointCoordinates orgQhull::PointCoordinates::operator+ (const PointCoordinates & other) const
{
    PointCoordinates pc= *this;
    pc << other;
    return pc;
}//operator+
operator+=() [1/3]
PointCoordinates & orgQhull::PointCoordinates::operator+= (const coordT & c) inline
{ append(c); return *this; }
References append().
operator+=() [2/3]
PointCoordinates & orgQhull::PointCoordinates::operator+= (const PointCoordinates & other) inline
{ append(other); return *this; }
References append().
operator+=() [3/3]
PointCoordinates & orgQhull::PointCoordinates::operator+= (const QhullPoint & p) inline
{ append(p); return *this; }
References append().
operator<<() [1/3]
PointCoordinates & orgQhull::PointCoordinates::operator<< (const coordT & c) inline
{ return *this += c; }
operator<<() [2/3]
PointCoordinates & orgQhull::PointCoordinates::operator<< (const PointCoordinates & other) inline
{ return *this += other; }
operator<<() [3/3]
PointCoordinates & orgQhull::PointCoordinates::operator<< (const QhullPoint & p) inline
{ return *this += p; }
operator=()
PointCoordinates & orgQhull::PointCoordinates::operator= (const PointCoordinates & other)
{
    QhullPoints::operator=(other);
    point_coordinates= other.point_coordinates;
    describe_points= other.describe_points;
    makeValid(); // Update point_first and point_end
    return *this;
}//operator=
References describe_points, makeValid(), orgQhull::QhullPoints::operator=(), and point_coordinates.
operator==()
bool orgQhull::QhullPoints::operator== (const QhullPoints & other) const inherited
QhullPoints is equal if the same address, or if the coordinates are identical Use QhullPoint.operator==() for DISTround equality.
{
    if((point_end-point_first) != (other.point_end-other.point_first)){
        return false;
    }
    if(point_dimension!=other.point_dimension){
        return false;
    }
    if(point_first==other.point_first){
        return true;
    }
    if(!qh_qh || qh_qh->hull_dim==0){
        const coordT *c= point_first;
        const coordT *c2= other.point_first;
        while(c<point_end){
            if(*c++!=*c2++){
                return false;
            }
        }
    }else{
        const_iterator i= begin();
        const_iterator i2= other.begin();
        while(i<end()){
            if(*i++!=*i2++){
                return false;
            }
        }
    }
    return true;
}//operator==
References orgQhull::QhullPoints::begin(), coordT, orgQhull::QhullPoints::end(), qhT::hull_dim, orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, orgQhull::QhullPoints::point_first, and orgQhull::QhullPoints::qh_qh.
Referenced by orgQhull::QhullPoints::operator!=().
operator[]()
QhullPoint orgQhull::QhullPoints::operator[] (countT idx) const inline inherited
{ return at(idx); }
References orgQhull::QhullPoints::at().
print()
PrintPoints orgQhull::QhullPoints::print (const char * message) const inline inherited
{ return PrintPoints(message, false, *this); }
Referenced by orgQhull::QhullPoints_test::t_io().
printWithIdentifier()
PrintPoints orgQhull::QhullPoints::printWithIdentifier (const char * message) const inline inherited
{ return PrintPoints(message, true, *this); }
Referenced by orgQhull::QhullPoints_test::t_io().
qh()
QhullQh * orgQhull::QhullPoints::qh () const inline inherited
{ return qh_qh; }
References orgQhull::QhullPoints::qh_qh.
Referenced by orgQhull::RboxPoints::~RboxPoints(), orgQhull::RboxPoints::appendPoints(), and orgQhull::RboxPoints_test::t_getSet().
reserveCoordinates()
void orgQhull::PointCoordinates::reserveCoordinates (countT newCoordinates)
{
    // vector::reserve is not const
    point_coordinates.reserve((countT)point_coordinates.size()+newCoordinates); // WARN64
    makeValid();
}//reserveCoordinates
References makeValid(), point_coordinates, orgQhull::Coordinates::reserve(), and orgQhull::Coordinates::size().
Referenced by append(), appendPoints(), orgQhull::RboxPoints::reservePoints(), and orgQhull::PointCoordinates_test::t_modify().
resetQhullQh()
void orgQhull::QhullPoints::resetQhullQh (QhullQh * qqh) inherited
Reset QhullPoints to QhullQh and its hullDimension() Does not free up old qh_qh.
{
    qh_qh= qqh;
    point_dimension= (qqh ? qqh->hull_dim : 0);
    point_first= 0;
    point_end= 0;
}//resetQhullQh
References qhT::hull_dim, orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, orgQhull::QhullPoints::point_first, and orgQhull::QhullPoints::qh_qh.
Referenced by orgQhull::RboxPoints::~RboxPoints(), and orgQhull::RboxPoints::allocateQhullQh().
setComment()
void orgQhull::PointCoordinates::setComment (const std::string & s) inline
{ describe_points= s; }
References describe_points.
Referenced by orgQhull::PointCoordinates_test::t_getset().
setDimension()
void orgQhull::PointCoordinates::setDimension (int i)
{
    if(i<0){
        throw QhullError(10062, "Qhull error: can not set PointCoordinates dimension to %d", i);
    }
    int currentDimension=QhullPoints::dimension();
    if(currentDimension!=0 && i!=currentDimension){
        throw QhullError(10063, "Qhull error: can not change PointCoordinates dimension (from %d to %d)", currentDimension, i);
    }
    QhullPoints::setDimension(i);
}//setDimension
References orgQhull::QhullPoints::dimension(), and orgQhull::QhullPoints::setDimension().
Referenced by PointCoordinates(), PointCoordinates(), PointCoordinates(), PointCoordinates(), append(), append(), appendPoints(), orgQhull::RboxPoints_test::t_change(), orgQhull::RboxPoints_test::t_error(), orgQhull::PointCoordinates_test::t_getset(), and orgQhull::RboxPoints_test::t_getSet().
size()
size_t orgQhull::QhullPoints::size () const inline inherited
{ return point_dimension ? (point_end-point_first)/point_dimension : 0; }
References orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_end, and orgQhull::QhullPoints::point_first.
Referenced by orgQhull::QhullPoints::count(), orgQhull::PointCoordinates_test::t_construct_q(), orgQhull::QhullPoints_test::t_construct_q(), orgQhull::PointCoordinates_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::PointCoordinates_test::t_convert(), orgQhull::QhullPoints_test::t_convert(), and orgQhull::QhullPoints_test::t_getset().
toStdVector()
std::vector< coordT > orgQhull::PointCoordinates::toStdVector () const inline
{ return point_coordinates.toStdVector(); }
References point_coordinates, and orgQhull::Coordinates::toStdVector().
Referenced by orgQhull::PointCoordinates_test::t_convert().
value() [1/2]
QhullPoint orgQhull::QhullPoints::value (countT idx) const inherited
{
    QhullPoint p(qh_qh);
    if(idx>=0 && idx<count()){
        p.defineAs(point_dimension, point_first+idx*point_dimension);
    }
    return p;
}//value
References orgQhull::QhullPoints::count(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_first, and orgQhull::QhullPoints::qh_qh.
Referenced by orgQhull::PointCoordinates_test::t_element(), and orgQhull::QhullPoints_test::t_element().
value() [2/2]
QhullPoint orgQhull::QhullPoints::value (countT idx, QhullPoint & defaultValue) const inherited
{
    QhullPoint p(qh_qh);
    if(idx>=0 && idx<count()){
        p.defineAs(point_dimension, point_first+idx*point_dimension);
    }else{
        p.defineAs(defaultValue);
    }
    return p;
}//value
References orgQhull::QhullPoints::count(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoints::point_dimension, orgQhull::QhullPoints::point_first, and orgQhull::QhullPoints::qh_qh.
Member Data Documentation
describe_points
std::string orgQhull::PointCoordinates::describe_points private
std::vector of point coordinates may have extraCoordinates()
Referenced by appendComment(), appendPoints(), comment(), operator=(), and setComment().
point_coordinates
Coordinates orgQhull::PointCoordinates::point_coordinates private
Referenced by append(), appendPoints(), beginCoordinates(), beginCoordinates(), beginCoordinates(), beginCoordinates(), endCoordinates(), endCoordinates(), getCoordinates(), indexOffset(), makeValid(), operator=(), reserveCoordinates(), and toStdVector().
point_dimension
int orgQhull::QhullPoints::point_dimension private inherited
Dimension, >=0.
Referenced by orgQhull::QhullPoints::at(), orgQhull::QhullPoints::constEnd(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::dimension(), orgQhull::QhullPoints::end(), orgQhull::QhullPoints::end(), orgQhull::QhullPoints::extraCoordinatesCount(), orgQhull::QhullPoints::first(), orgQhull::QhullPoints::first(), orgQhull::QhullPoints::indexOf(), orgQhull::QhullPoints::indexOf(), orgQhull::QhullPoints::isEmpty(), orgQhull::QhullPoints::last(), orgQhull::QhullPoints::last(), orgQhull::QhullPoints::mid(), orgQhull::QhullPoints::operator=(), orgQhull::QhullPoints::operator==(), orgQhull::QhullPoints::resetQhullQh(), orgQhull::QhullPoints::setDimension(), orgQhull::QhullPoints::size(), orgQhull::QhullPoints::value(), and orgQhull::QhullPoints::value().
point_end
coordT* orgQhull::QhullPoints::point_end private inherited
End of point coordinates (end>=first). Trailing coordinates ignored.
Referenced by orgQhull::QhullPoints::at(), orgQhull::QhullPoints::constEnd(), orgQhull::QhullPoints::coordinateCount(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::end(), orgQhull::QhullPoints::end(), orgQhull::QhullPoints::extraCoordinates(), orgQhull::QhullPoints::extraCoordinatesCount(), orgQhull::QhullPoints::includesCoordinates(), orgQhull::QhullPoints::isEmpty(), orgQhull::QhullPoints::last(), orgQhull::QhullPoints::last(), orgQhull::QhullPoints::operator=(), orgQhull::QhullPoints::operator==(), orgQhull::QhullPoints::resetQhullQh(), and orgQhull::QhullPoints::size().
point_first
coordT* orgQhull::QhullPoints::point_first private inherited
First coordinate of an array of points of point_dimension.
Referenced by orgQhull::QhullPoints::at(), orgQhull::QhullPoints::constData(), orgQhull::QhullPoints::coordinateCount(), orgQhull::QhullPoints::coordinates(), orgQhull::QhullPoints::data(), orgQhull::QhullPoints::data(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::extraCoordinatesCount(), orgQhull::QhullPoints::first(), orgQhull::QhullPoints::first(), orgQhull::QhullPoints::includesCoordinates(), orgQhull::QhullPoints::indexOf(), orgQhull::QhullPoints::indexOf(), orgQhull::QhullPoints::isEmpty(), orgQhull::QhullPoints::last(), orgQhull::QhullPoints::last(), orgQhull::QhullPoints::mid(), orgQhull::QhullPoints::operator=(), orgQhull::QhullPoints::operator==(), orgQhull::QhullPoints::resetQhullQh(), orgQhull::QhullPoints::size(), orgQhull::QhullPoints::value(), and orgQhull::QhullPoints::value().
qh_qh
QhullQh* orgQhull::QhullPoints::qh_qh private inherited
Maybe initialized NULL to allow ownership by RboxPoints qh_qh used for QhullPoint() and qh_qh->hull_dim in constructor.
Referenced by orgQhull::QhullPoints::at(), orgQhull::QhullPoints::constEnd(), orgQhull::QhullPoints::defineAs(), orgQhull::QhullPoints::end(), orgQhull::QhullPoints::end(), orgQhull::QhullPoints::first(), orgQhull::QhullPoints::first(), orgQhull::QhullPoints::last(), orgQhull::QhullPoints::last(), orgQhull::QhullPoints::mid(), orgQhull::QhullPoints::operator=(), orgQhull::QhullPoints::operator==(), orgQhull::QhullPoints::qh(), orgQhull::QhullPoints::resetQhullQh(), orgQhull::QhullPoints::value(), and orgQhull::QhullPoints::value().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/PointCoordinates.h
src/qhull/src/libqhullcpp/PointCoordinates.cpp