OrcaSlicer: AuxiliaryList Class Reference
AuxiliaryList Class Reference
#include <src/slic3r/GUI/GUI_AuxiliaryList.hpp>
Public Member Functions
AuxiliaryList (wxWindow *parent)
~AuxiliaryList ()
wxSizer * get_top_sizer ()
void init_auxiliary ()
void reload (wxString aux_path)
Private Member Functions
void do_import_file (AuxiliaryModelNode *folder)
void on_create_folder (wxCommandEvent &evt)
void on_import_file (wxCommandEvent &evt)
void on_delete (wxCommandEvent &evt)
void on_context_menu (wxDataViewEvent &evt)
void on_begin_drag (wxDataViewEvent &evt)
void on_drop_possible (wxDataViewEvent &evt)
void on_drop (wxDataViewEvent &evt)
void on_editing_started (wxDataViewEvent &evt)
void on_editing_done (wxDataViewEvent &evt)
void on_left_dclick (wxMouseEvent &evt)
void create_new_folder ()
void handle_key_event (wxKeyEvent &evt)
Private Attributes
wxDataViewItem m_dragged_item
AuxiliaryModel * m_auxiliary_model
wxSizer * m_sizer
wxButton * m_if_btn
wxButton * m_of_btn
wxButton * m_del_btn
Detailed Description
Constructor & Destructor Documentation
AuxiliaryList()
AuxiliaryList::AuxiliaryList (wxWindow * parent)
  : wxDataViewCtrl(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxDV_NO_HEADER)
{
  wxDataViewTextRenderer* tr = new wxDataViewTextRenderer("string", wxDATAVIEW_CELL_INERT);
  wxDataViewColumn* column0 = new wxDataViewColumn("", tr, 0, 200, wxALIGN_LEFT,
    wxDATAVIEW_COL_SORTABLE | wxDATAVIEW_COL_RESIZABLE);
  this->AppendColumn(column0);
  m_auxiliary_model = new AuxiliaryModel();
  this->AssociateModel(m_auxiliary_model);
  m_sizer = new wxBoxSizer(wxVERTICAL);
  m_sizer->Add(this, 1, wxEXPAND | wxALL, 0);
  wxPanel* panel = new wxPanel(parent, wxID_ANY, wxDefaultPosition, wxSize(-1, FromDIP(21)));
  //panel->SetBackgroundColour(*wxLIGHT_GREY);
#if 0
  wxBitmap if_bitmap = create_scaled_bitmap("import_file.png", nullptr, FromDIP(21));
  wxBitmap nf_bitmap = create_scaled_bitmap("new_folder.png", nullptr, FromDIP(21));
  wxBitmap del_bitmap = create_scaled_bitmap("delete.png", nullptr, FromDIP(21));
  wxBitmapButton* m_if_btn = new wxBitmapButton(panel, wxID_OPEN, if_bitmap);
  wxBitmapButton* m_nf_btn = new wxBitmapButton(panel, wxID_NEW, nf_bitmap);
  wxBitmapButton* m_del_btn = new wxBitmapButton(panel, wxID_DELETE, del_bitmap);
#endif
  //m_nf_btn = new wxButton(panel, wxID_NEW, _L("New Folder"));
  m_if_btn = new wxButton(panel, wxID_ADD, _L("Import File"));
  m_of_btn = new wxButton(panel, wxID_OPEN, _("Open File"));
  m_del_btn = new wxButton(panel, wxID_DELETE, _L("Delete"));
  wxBoxSizer* hsizer = new wxBoxSizer(wxHORIZONTAL);
  //hsizer->Add(m_nf_btn, 0, wxRIGHT, 5);
  hsizer->Add(m_if_btn, 0, wxLEFT | wxRIGHT, 5);
  hsizer->Add(m_of_btn, 0, wxLEFT | wxRIGHT, 5);
  hsizer->Add(m_del_btn, 0, wxLEFT | wxRIGHT, 5);
  panel->SetSizer(hsizer);
  m_sizer->Add(panel, 0, wxEXPAND | wxALL, 5);
  EnableDragSource(wxDF_UNICODETEXT);
  EnableDropTarget(wxDF_UNICODETEXT);
  // Keyboard events
  Bind(wxEVT_CHAR, [this](wxKeyEvent& event) { this->handle_key_event(event); });
  // Button events
  //m_nf_btn->Bind(wxEVT_BUTTON, &AuxiliaryList::on_create_folder, this, wxID_NEW);
  m_if_btn->Bind(wxEVT_BUTTON, &AuxiliaryList::on_import_file, this, wxID_ADD);
  m_del_btn->Bind(wxEVT_BUTTON, &AuxiliaryList::on_delete, this, wxID_DELETE);
  m_of_btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent& evt) {
    wxDataViewItem sel_item = this->GetSelection();
    AuxiliaryModelNode* sel = (AuxiliaryModelNode*)sel_item.GetID();
    if (sel != nullptr && !sel->IsContainer()) {
      wxLaunchDefaultApplication(sel->path, 0);
    }
    else {
      evt.Skip();
    }
  }, wxID_OPEN);
  // Dataview events
  this->Bind(wxEVT_DATAVIEW_ITEM_CONTEXT_MENU, &AuxiliaryList::on_context_menu, this);
  this->Bind(wxEVT_DATAVIEW_ITEM_BEGIN_DRAG, &AuxiliaryList::on_begin_drag, this);
  this->Bind(wxEVT_DATAVIEW_ITEM_DROP_POSSIBLE, &AuxiliaryList::on_drop_possible, this);
  this->Bind(wxEVT_DATAVIEW_ITEM_DROP, &AuxiliaryList::on_drop, this);
  this->Bind(wxEVT_DATAVIEW_ITEM_EDITING_STARTED, &AuxiliaryList::on_editing_started, this);
  this->Bind(wxEVT_DATAVIEW_ITEM_EDITING_DONE, &AuxiliaryList::on_editing_done, this);
  // Mouse events
  wxWindow* win = this->GetMainWindow();
  win->Bind(wxEVT_LEFT_DCLICK, &AuxiliaryList::on_left_dclick, this);
  Bind(wxEVT_DATAVIEW_SELECTION_CHANGED, [this](wxDataViewEvent& event) {
    wxDataViewItem sel_item = event.GetItem();
    AuxiliaryModelNode* sel_node = (AuxiliaryModelNode*)sel_item.GetID();
    if (sel_node == nullptr)
      return;
    m_del_btn->Enable(!sel_node->IsContainer());
  });
}
References _, _L, create_scaled_bitmap(), handle_key_event(), AuxiliaryModelNode::IsContainer(), m_auxiliary_model, m_del_btn, m_if_btn, m_of_btn, m_sizer, on_begin_drag(), on_context_menu(), on_delete(), on_drop(), on_drop_possible(), on_editing_done(), on_editing_started(), on_import_file(), on_left_dclick(), AuxiliaryModelNode::path, wxButton, and wxEVT_BUTTON.
~AuxiliaryList()
AuxiliaryList::~AuxiliaryList ()
{
  this->AssociateModel(nullptr);
  delete m_auxiliary_model;
}
References m_auxiliary_model.
Member Function Documentation
create_new_folder()
void AuxiliaryList::create_new_folder () private
{
  wxDataViewItem folder_item = m_auxiliary_model->CreateFolder(wxEmptyString);
  AuxiliaryModelNode* folder = (AuxiliaryModelNode*)folder_item.GetID();
  if (folder == nullptr)
    return;
  Select(folder_item);
  wxDataViewColumn* col = GetColumn(0);
  wxDataViewCellMode mode = col->GetRenderer()->GetMode();
  col->GetRenderer()->SetMode(wxDATAVIEW_CELL_EDITABLE);
  EditItem(folder_item, col);
  col->GetRenderer()->SetMode(mode);
}
References col(), AuxiliaryModel::CreateFolder(), and m_auxiliary_model.
Referenced by on_context_menu(), and on_create_folder().
do_import_file()
void AuxiliaryList::do_import_file (AuxiliaryModelNode * folder) private
{
  if (folder == nullptr || !folder->IsContainer())
    return;
  wxString src_path;
  wxString dst_path;
  wxFileDialog dialog(this, _L("Choose files"), wxEmptyString, wxEmptyString,
    wxFileSelectorDefaultWildcardStr, wxFD_OPEN | wxFD_FILE_MUST_EXIST | wxFD_MULTIPLE);
  if (dialog.ShowModal() == wxID_OK) {
    wxArrayString sel_paths;
    dialog.GetPaths(sel_paths);
    wxDataViewItemArray file_items = m_auxiliary_model->ImportFile(folder, sel_paths);
    if (!file_items.empty()) {
      wxDataViewItem file_item = file_items[0];
      AuxiliaryModelNode* file_node = (AuxiliaryModelNode*)file_item.GetID();
      if (file_node != nullptr) {
        if (!m_auxiliary_model->IsOrphan(file_item)) {
          Expand(wxDataViewItem(file_node->GetParent()));
        }
        Select(file_item);
        m_del_btn->Enable(true);
      }
    }
  }
}
References _L, AuxiliaryModelNode::GetParent(), AuxiliaryModel::ImportFile(), AuxiliaryModelNode::IsContainer(), AuxiliaryModel::IsOrphan(), m_auxiliary_model, and m_del_btn.
Referenced by on_context_menu(), and on_import_file().
get_top_sizer()
wxSizer * AuxiliaryList::get_top_sizer () inline
{ return m_sizer; }
References m_sizer.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog().
handle_key_event()
void AuxiliaryList::handle_key_event (wxKeyEvent & evt) private
{
  if (evt.GetKeyCode() == WXK_DELETE || evt.GetKeyCode() == WXK_BACK)
    m_auxiliary_model->Delete(this->GetSelection());
}
References AuxiliaryModel::Delete(), and m_auxiliary_model.
Referenced by AuxiliaryList().
init_auxiliary()
void AuxiliaryList::init_auxiliary ()
{
  Model& model = wxGetApp().plater()->model();
  std::string aux_path = encode_path(model.get_auxiliary_file_temp_path().c_str());
  m_auxiliary_model->Init(aux_path);
}
References Slic3r::encode_path(), Slic3r::Model::get_auxiliary_file_temp_path(), AuxiliaryModel::Init(), and m_auxiliary_model.
on_begin_drag()
void AuxiliaryList::on_begin_drag (wxDataViewEvent & evt) private
{
  wxDataViewItem sel_item = evt.GetItem();
  AuxiliaryModelNode* sel = (AuxiliaryModelNode*)sel_item.GetID();
  if (sel == nullptr || sel->IsContainer())
    return;
  m_dragged_item = sel_item;
  wxTextDataObject* obj = new wxTextDataObject;
  obj->SetText("Some text");
  evt.SetDataObject(obj);
  evt.SetDragFlags(wxDrag_DefaultMove);
}
References AuxiliaryModelNode::IsContainer(), and m_dragged_item.
Referenced by AuxiliaryList().
on_context_menu()
void AuxiliaryList::on_context_menu (wxDataViewEvent & evt) private
{
  wxMenu* menu = new wxMenu();
  wxDataViewItem item = evt.GetItem();
  AuxiliaryModelNode* node = (AuxiliaryModelNode*)item.GetID();
  if (node == nullptr) {
    append_menu_item(menu, wxID_ANY, _L("New Folder"), wxEmptyString,
      [this](wxCommandEvent&)
      {
        create_new_folder();
      });
  }
  else if (node->IsContainer()) {
    append_menu_item(menu, wxID_ANY, _L("Import File"), wxEmptyString,
      [this, node](wxCommandEvent&)
      {
        do_import_file(node);
      });
    append_menu_item(menu, wxID_ANY, _L("Delete"), wxEmptyString,
      [this, item](wxCommandEvent&)
      {
        m_auxiliary_model->Delete(item);
      });
  }
  else {
    append_menu_item(menu, wxID_ANY, _L("Open"), wxEmptyString,
      [this, node](wxCommandEvent&)
      {
        wxLaunchDefaultApplication(node->path, 0);
      });
    append_menu_item(menu, wxID_ANY, _L("Delete"), wxEmptyString,
      [this, item](wxCommandEvent&)
      {
        m_auxiliary_model->Delete(item);
      });
    append_menu_item(menu, wxID_ANY, _L("Rename"), wxEmptyString,
      [this, item](wxCommandEvent&)
      {
        wxDataViewColumn* col = this->GetColumn(0);
        wxDataViewCellMode mode = col->GetRenderer()->GetMode();
        col->GetRenderer()->SetMode(wxDATAVIEW_CELL_EDITABLE);
        this->EditItem(item, col);
        col->GetRenderer()->SetMode(mode);
      });
  }
  PopupMenu(menu);
}
References _L, append_menu_item(), col(), create_new_folder(), AuxiliaryModel::Delete(), do_import_file(), AuxiliaryModelNode::IsContainer(), m_auxiliary_model, and AuxiliaryModelNode::path.
Referenced by AuxiliaryList().
on_create_folder()
void AuxiliaryList::on_create_folder (wxCommandEvent & evt) private
{
  create_new_folder();
}
References create_new_folder().
on_delete()
void AuxiliaryList::on_delete (wxCommandEvent & evt) private
{
  m_auxiliary_model->Delete(this->GetSelection());
}
References AuxiliaryModel::Delete(), and m_auxiliary_model.
Referenced by AuxiliaryList().
on_drop()
void AuxiliaryList::on_drop (wxDataViewEvent & evt) private
{
  m_auxiliary_model->MoveItem(evt.GetItem(), m_dragged_item);
  Expand(evt.GetItem());
  Select(m_dragged_item);
  m_dragged_item = wxDataViewItem(nullptr);
}
References m_auxiliary_model, m_dragged_item, and AuxiliaryModel::MoveItem().
Referenced by AuxiliaryList().
on_drop_possible()
void AuxiliaryList::on_drop_possible (wxDataViewEvent & evt) private
{
  evt.Allow();
}
Referenced by AuxiliaryList().
on_editing_done()
void AuxiliaryList::on_editing_done (wxDataViewEvent & evt) private
{
  bool is_done = m_auxiliary_model->Rename(evt.GetItem(), evt.GetValue().GetString());
  if (!is_done)
    evt.Veto();
}
References m_auxiliary_model, and AuxiliaryModel::Rename().
Referenced by AuxiliaryList().
on_editing_started()
void AuxiliaryList::on_editing_started (wxDataViewEvent & evt) private
{
}
Referenced by AuxiliaryList().
on_import_file()
void AuxiliaryList::on_import_file (wxCommandEvent & evt) private
{
  wxDataViewItem sel_item = this->GetSelection();
  AuxiliaryModelNode* sel_node = (AuxiliaryModelNode*)sel_item.GetID();
  if (sel_node == nullptr)
    return;
  AuxiliaryModelNode* folder_node = sel_node;
  if (!folder_node->IsContainer()) {
    wxDataViewItem folder_item = m_auxiliary_model->GetParent(sel_item);
    folder_node = (AuxiliaryModelNode*)folder_item.GetID();
    if (folder_node == nullptr)
      return;
  }
  do_import_file(folder_node);
}
References do_import_file(), AuxiliaryModel::GetParent(), AuxiliaryModelNode::IsContainer(), and m_auxiliary_model.
Referenced by AuxiliaryList().
on_left_dclick()
void AuxiliaryList::on_left_dclick (wxMouseEvent & evt) private
{
  wxDataViewItem sel_item = this->GetSelection();
  AuxiliaryModelNode* sel = (AuxiliaryModelNode*)sel_item.GetID();
  if (sel != nullptr && !sel->IsContainer()) {
    wxLaunchDefaultApplication(sel->path, 0);
  }
  else {
    evt.Skip();
  }
}
References AuxiliaryModelNode::IsContainer(), and AuxiliaryModelNode::path.
Referenced by AuxiliaryList().
reload()
void AuxiliaryList::reload (wxString aux_path)
{
  m_auxiliary_model->Reload(aux_path);
  wxDataViewItemArray items;
  m_auxiliary_model->GetChildren(wxDataViewItem(nullptr), items);
  for (wxDataViewItem item : items) {
    Expand(item);
  }
}
References AuxiliaryModel::GetChildren(), m_auxiliary_model, and AuxiliaryModel::Reload().
Member Data Documentation
m_auxiliary_model
AuxiliaryModel* AuxiliaryList::m_auxiliary_model private
Referenced by AuxiliaryList(), ~AuxiliaryList(), create_new_folder(), do_import_file(), handle_key_event(), init_auxiliary(), on_context_menu(), on_delete(), on_drop(), on_editing_done(), on_import_file(), and reload().
m_del_btn
wxButton* AuxiliaryList::m_del_btn private
Referenced by AuxiliaryList(), and do_import_file().
m_dragged_item
wxDataViewItem AuxiliaryList::m_dragged_item private
Referenced by on_begin_drag(), and on_drop().
m_if_btn
wxButton* AuxiliaryList::m_if_btn private
Referenced by AuxiliaryList().
m_of_btn
wxButton* AuxiliaryList::m_of_btn private
Referenced by AuxiliaryList().
m_sizer
wxSizer* AuxiliaryList::m_sizer private
Referenced by AuxiliaryList(), and get_top_sizer().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_AuxiliaryList.hpp
src/slic3r/GUI/GUI_AuxiliaryList.cpp