OrcaSlicer: Slic3r::GUI::RotoptimizeJob Class Reference
Slic3r::GUI::RotoptimizeJob Class Reference
#include <src/slic3r/GUI/Jobs/RotoptimizeJob.hpp>
Classes
struct FindMethod
struct ObjRot
Public Types
enum JobPrepareState { PREPARE_STATE_DEFAULT = 0 , PREPARE_STATE_MENU = 1 }
Public Member Functions
RotoptimizeJob (std::shared_ptr< ProgressIndicator > pri, Plater *plater)
void finalize () override
bool is_finalized () const
void start ()
bool join (int timeout_ms=0)
bool is_running () const
void cancel ()
Static Public Member Functions
static constexpr size_t get_methods_count ()
static std::string get_method_name (size_t i)
static std::string get_method_description (size_t i)
Protected Member Functions
void prepare () override
void process () override
void on_exception (const std::exception_ptr &) override
virtual int status_range () const
void update_status (int st, const wxString &msg="")
void update_percent_finish ()
void show_networking_test (wxString msg)
bool was_canceled () const
Protected Attributes
Plater * m_plater
bool only_on_partplate {false}
Private Types
using FindFn = std::function< Vec2d(const ModelObject &mo, const sla::RotOptimizeParams &params)>
Private Member Functions
void run (std::exception_ptr &)
Private Attributes
size_t m_method_id = 0
float m_accuracy = 0.75
DynamicPrintConfig m_default_print_cfg
std::vector< ObjRot > m_selected_object_ids
int m_range = 100
int m_thread_evt_id = wxID_ANY
boost::thread m_thread
std::atomic< bool > m_running {false}
std::atomic< bool > m_canceled {false}
bool m_finalized = false
bool m_finalizing = false
std::shared_ptr< ProgressIndicator > m_progress
std::exception_ptr m_worker_error = nullptr
Static Private Attributes
static const FindMethod Methods []
Detailed Description
Class Documentation
Slic3r::GUI::RotoptimizeJob::FindMethod
struct Slic3r::GUI::RotoptimizeJob::FindMethod
Class Members
string descr
FindFn findfn
string name
Member Typedef Documentation
FindFn
using Slic3r::GUI::RotoptimizeJob::FindFn = std::function<Vec2d(const ModelObject & mo, const sla::RotOptimizeParams &params)> private
Member Enumeration Documentation
JobPrepareState
enum Slic3r::GUI::Job::JobPrepareState inherited
Enumerator
PREPARE_STATE_DEFAULT
PREPARE_STATE_MENU
{
        PREPARE_STATE_DEFAULT = 0,
        PREPARE_STATE_MENU = 1,
    };
Constructor & Destructor Documentation
RotoptimizeJob()
Slic3r::GUI::RotoptimizeJob::RotoptimizeJob (std::shared_ptr< ProgressIndicator > pri, Plater * plater) inline
        : PlaterJob{std::move(pri), plater}
    {}
Member Function Documentation
cancel()
void Slic3r::GUI::Job::cancel () inline inherited
{ m_canceled.store(true); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::UpgradeNetworkJob::process().
finalize()
void Slic3r::GUI::RotoptimizeJob::finalize () override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (was_canceled()) return;
    for (const ObjRot &objrot : m_selected_object_ids) {
        ModelObject *o = m_plater->model().objects[size_t(objrot.idx)];
        if (!o) continue;
        for(ModelInstance * oi : o->instances) {
            if (objrot.rot)
                oi->set_rotation({objrot.rot->x(), objrot.rot->y(), 0.});
            auto    trmatrix = oi->get_transformation().get_matrix();
            Polygon trchull  = o->convex_hull_2d(trmatrix);
            MinAreaBoundigBox rotbb(trchull, MinAreaBoundigBox::pcConvex);
            double            phi = rotbb.angle_to_X();
            // The box should be landscape
            if(rotbb.width() < rotbb.height()) phi += PI / 2;
            Vec3d rt = oi->get_rotation(); rt(Z) += phi;
            oi->set_rotation(rt);
        }
        // Correct the z offset of the object which was corrupted be
        // the rotation
        o->ensure_on_bed();
//        m_plater->find_new_position(o->instances);
    }
    if (!was_canceled())
        m_plater->update();
    Job::finalize();
}
References Slic3r::MinAreaBoundigBox::angle_to_X(), Slic3r::ModelObject::convex_hull_2d(), Slic3r::ModelObject::ensure_on_bed(), Slic3r::GUI::Job::finalize(), Slic3r::MinAreaBoundigBox::height(), Slic3r::ModelObject::instances, Slic3r::GUI::PlaterJob::m_plater, m_selected_object_ids, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::MinAreaBoundigBox::pcConvex, Slic3r::GUI::PI, Slic3r::GUI::Plater::update(), Slic3r::GUI::Job::was_canceled(), Slic3r::MinAreaBoundigBox::width(), and Slic3r::Z.
get_method_description()
static std::string Slic3r::GUI::RotoptimizeJob::get_method_description (size_t i) inline static
    {
        return _utf8(Methods[i].descr);
    }
References _utf8, and Methods.
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow().
get_method_name()
static std::string Slic3r::GUI::RotoptimizeJob::get_method_name (size_t i) inline static
    {
        return _utf8(Methods[i].name);
    }
References _utf8, and Methods.
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow().
get_methods_count()
static constexpr size_t Slic3r::GUI::RotoptimizeJob::get_methods_count () inline static constexpr
{ return std::size(Methods); }
References Methods.
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow(), Slic3r::GUI::GLGizmoRotate3D::load_rotoptimize_state(), and prepare().
is_finalized()
bool Slic3r::GUI::Job::is_finalized () const inline inherited
{ return m_finalized; }
References Slic3r::GUI::Job::m_finalized.
is_running()
bool Slic3r::GUI::Job::is_running () const inline inherited
{ return m_running.load(); }
References Slic3r::GUI::Job::m_running.
join()
bool Slic3r::GUI::Job::join (int timeout_ms = 0) inherited
{
    if (!m_thread.joinable()) return true;
    if (timeout_ms <= 0)
        m_thread.join();
    else if (!m_thread.try_join_for(boost::chrono::milliseconds(timeout_ms)))
        return false;
    return true;
}
on_exception()
void Slic3r::GUI::PlaterJob::on_exception (const std::exception_ptr & eptr) override protected virtual inherited
Reimplemented from Slic3r::GUI::Job.
Reimplemented in Slic3r::GUI::PrintJob, and Slic3r::GUI::SendJob.
{
    try {
        if (eptr)
            std::rethrow_exception(eptr);
    }  catch (std::exception &e) {
       show_error(m_plater, _(L("Exception")) + ": "+ e.what());
    }
}
References _, L, Slic3r::GUI::PlaterJob::m_plater, and Slic3r::GUI::show_error().
Referenced by Slic3r::GUI::ArrangeJob::on_exception(), Slic3r::GUI::BindJob::on_exception(), Slic3r::GUI::OrientJob::on_exception(), Slic3r::GUI::PrintJob::on_exception(), and Slic3r::GUI::SendJob::on_exception().
prepare()
void Slic3r::GUI::RotoptimizeJob::prepare () override protected virtual
Reimplemented from Slic3r::GUI::Job.
{
    std::string accuracy_str =
        wxGetApp().app_config->get("sla_auto_rotate", "accuracy");
    std::string method_str =
        wxGetApp().app_config->get("sla_auto_rotate", "method_id");
    if (!accuracy_str.empty())
        m_accuracy = std::stof(accuracy_str);
    if (!method_str.empty())
        m_method_id = std::stoi(method_str);
    m_accuracy = std::max(0.f, std::min(m_accuracy, 1.f));
    m_method_id = std::max(size_t(0), std::min(get_methods_count() - 1, m_method_id));
    m_default_print_cfg = wxGetApp().preset_bundle->full_config();
    const auto &sel = m_plater->get_selection().get_content();
    m_selected_object_ids.clear();
    m_selected_object_ids.reserve(sel.size());
    for (const auto &s : sel) {
        int obj_id;
        std::tie(obj_id, std::ignore) = s;
        m_selected_object_ids.emplace_back(obj_id);
    }
}
References Slic3r::GUI::Selection::get_content(), get_methods_count(), Slic3r::GUI::Plater::get_selection(), m_accuracy, m_default_print_cfg, m_method_id, Slic3r::GUI::PlaterJob::m_plater, and m_selected_object_ids.
process()
void Slic3r::GUI::RotoptimizeJob::process () override protected virtual
Implements Slic3r::GUI::Job.
{
    int prev_status = 0;
    auto params =
        sla::RotOptimizeParams{}
            .accuracy(m_accuracy)
            .print_config(&m_default_print_cfg)
            .statucb([this, &prev_status](int s)
        {
            if (s > 0 && s < 100)
                ;
                // update_status(prev_status + s / m_selected_object_ids.size(),
                //               _(L("Searching for optimal orientation...")));
            return !was_canceled();
        });
    for (ObjRot &objrot : m_selected_object_ids) {
        ModelObject *o = m_plater->model().objects[size_t(objrot.idx)];
        if (!o) continue;
        if (Methods[m_method_id].findfn)
            objrot.rot = Methods[m_method_id].findfn(*o, params);
        prev_status += 100 / m_selected_object_ids.size();
        if (was_canceled()) break;
    }
    // update_status(100, was_canceled() ? _(L("Orientation search canceled.")) :
    //                                     _(L("Orientation found.")));
}
References Slic3r::sla::RotOptimizeParams::accuracy(), Slic3r::GUI::RotoptimizeJob::FindMethod::findfn, m_accuracy, m_default_print_cfg, m_method_id, Slic3r::GUI::PlaterJob::m_plater, m_selected_object_ids, Methods, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::sla::RotOptimizeParams::print_config(), Slic3r::sla::RotOptimizeParams::statucb(), and Slic3r::GUI::Job::was_canceled().
run()
void Slic3r::GUI::Job::run (std::exception_ptr & eptr) private inherited
{
    m_running.store(true);
    try {
        process();
    } catch (...) {
        eptr = std::current_exception();
    }
    m_running.store(false);
    // ensure to call the last status to finalize the job
    update_status(status_range(), "");
}
References Slic3r::GUI::Job::m_running, Slic3r::GUI::Job::process(), Slic3r::GUI::Job::status_range(), and Slic3r::GUI::Job::update_status().
show_networking_test()
void Slic3r::GUI::Job::show_networking_test (wxString msg) protected inherited
{
    m_progress->show_networking_test(msg);
}
Referenced by Slic3r::GUI::PrintJob::process().
start()
void Slic3r::GUI::Job::start () inherited
{ // Start the job. No effect if the job is already running
    if (!m_running.load()) {
        prepare();
        // Save the current status indicatior range and push the new one
        m_range = m_progress->get_range();
        m_progress->set_range(status_range());
        // init cancellation flag and set the cancel callback
        m_canceled.store(false);
        m_progress->set_cancel_callback(
                    [this]() { m_canceled.store(true); });
        m_finalized  = false;
        m_finalizing = false;
        // Changing cursor to busy
        wxBeginBusyCursor();
        try { // Execute the job
            m_worker_error = nullptr;
            m_thread = create_thread([this] { this->run(m_worker_error); });
        } catch (std::exception &) {
            update_status(status_range(),
                          _(L("Error! Unable to create thread!")));
        }
        // The state changes will be undone when the process hits the
        // last status value, in the status update handler (see ctor)
    }
}
References _, Slic3r::create_thread(), and L.
Referenced by Slic3r::GUI::OrientJob::process().
status_range()
virtual int Slic3r::GUI::Job::status_range () const inline protected virtual inherited
Reimplemented in Slic3r::GUI::ArrangeJob, Slic3r::GUI::BindJob, Slic3r::GUI::FillBedJob, Slic3r::GUI::PrintJob, Slic3r::GUI::SendJob, and Slic3r::GUI::UpgradeNetworkJob.
{ return 100; }
Referenced by Slic3r::GUI::Job::Job(), and Slic3r::GUI::Job::run().
update_percent_finish()
void Slic3r::GUI::Job::update_percent_finish () protected inherited
{
    m_progress->clear_percent();
}
Referenced by Slic3r::GUI::PrintJob::process().
update_status()
void Slic3r::GUI::Job::update_status (int st, const wxString & msg = "") protected inherited
{
    auto evt = new wxThreadEvent(wxEVT_THREAD, m_thread_evt_id);
    evt->SetInt(st);
    evt->SetString(msg);
    wxQueueEvent(this, evt);
}
Referenced by Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), Slic3r::GUI::Job::run(), Slic3r::GUI::BindJob::update_status(), and Slic3r::GUI::UpgradeNetworkJob::update_status().
was_canceled()
bool Slic3r::GUI::Job::was_canceled () const inline protected inherited
{ return m_canceled.load(); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::BindJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::PrintJob::finalize(), finalize(), Slic3r::GUI::SendJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::UpgradeNetworkJob::finalize(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), and Slic3r::GUI::UpgradeNetworkJob::process().
Member Data Documentation
m_accuracy
float Slic3r::GUI::RotoptimizeJob::m_accuracy = 0.75 private
Referenced by prepare(), and process().
m_canceled
std::atomic<bool> Slic3r::GUI::Job::m_canceled {false} private inherited
Referenced by Slic3r::GUI::Job::cancel(), and Slic3r::GUI::Job::was_canceled().
m_default_print_cfg
DynamicPrintConfig Slic3r::GUI::RotoptimizeJob::m_default_print_cfg private
Referenced by prepare(), and process().
m_finalized
bool Slic3r::GUI::Job::m_finalized = false private inherited
Referenced by Slic3r::GUI::Job::Job(), Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::is_finalized().
m_finalizing
bool Slic3r::GUI::Job::m_finalizing = false private inherited
Referenced by Slic3r::GUI::Job::Job().
m_method_id
size_t Slic3r::GUI::RotoptimizeJob::m_method_id = 0 private
Referenced by prepare(), and process().
m_plater
Plater* Slic3r::GUI::PlaterJob::m_plater protected inherited
Referenced by Slic3r::GUI::ArrangeJob::check_unprintable(), Slic3r::GUI::ArrangeJob::clear_input(), Slic3r::GUI::OrientJob::clear_input(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::ArrangeJob::on_exception(), Slic3r::GUI::PlaterJob::on_exception(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::OrientJob::prepare(), Slic3r::GUI::PrintJob::prepare(), prepare(), Slic3r::GUI::SendJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), process(), Slic3r::GUI::SendJob::process(), and Slic3r::GUI::SLAImportJob::reset().
m_progress
std::shared_ptr<ProgressIndicator> Slic3r::GUI::Job::m_progress private inherited
Referenced by Slic3r::GUI::Job::Job().
m_range
int Slic3r::GUI::Job::m_range = 100 private inherited
Referenced by Slic3r::GUI::Job::Job().
m_running
std::atomic<bool> Slic3r::GUI::Job::m_running {false} private inherited
Referenced by Slic3r::GUI::Job::is_running(), and Slic3r::GUI::Job::run().
m_selected_object_ids
std::vector<ObjRot> Slic3r::GUI::RotoptimizeJob::m_selected_object_ids private
Referenced by finalize(), prepare(), and process().
m_thread
boost::thread Slic3r::GUI::Job::m_thread private inherited
m_thread_evt_id
int Slic3r::GUI::Job::m_thread_evt_id = wxID_ANY private inherited
Referenced by Slic3r::GUI::Job::Job().
m_worker_error
std::exception_ptr Slic3r::GUI::Job::m_worker_error = nullptr private inherited
Referenced by Slic3r::GUI::Job::Job().
Methods
const FindMethod Slic3r::GUI::RotoptimizeJob::Methods[] inline static private
Initial value:
= {{L("Best surface quality"),
            sla::find_best_misalignment_rotation,
            L("Optimize object rotation for best surface quality.")},
           {L("Reduced overhang slopes"),
            sla::find_least_supports_rotation,
            L("Optimize object rotation to have minimum amount of overhangs needing support "
              "structures.\nNote that this method will try to find the best surface of the object "
              "for touching the print bed if no elevation is set.")},
           {L("Lowest Z height"),
            sla::find_min_z_height_rotation,
            L("Rotate the model to have the lowest z height for faster print time.")}}
Referenced by get_method_description(), get_method_name(), get_methods_count(), and process().
only_on_partplate
bool Slic3r::GUI::PlaterJob::only_on_partplate {false} protected inherited
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::OrientJob::prepare(), and Slic3r::GUI::ArrangeJob::prepare_wipe_tower().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/RotoptimizeJob.hpp
src/slic3r/GUI/Jobs/RotoptimizeJob.cpp