OrcaSlicer: Slic3r::sla::_ccr< false > Struct Reference
Slic3r::sla::_ccr< false > Struct Reference
#include <src/libslic3r/SLA/Concurrency.hpp>
Public Types
using SpinningMutex = execution::SpinningMutex< ExecutionSeq >
using BlockingMutex = execution::BlockingMutex< ExecutionSeq >
Static Public Member Functions
template<class It , class Fn >
static void for_each (It from, It to, Fn &&fn, size_t granularity=1)
template<class... Args>
static auto reduce (Args &&...args)
static size_t max_concurreny ()
Detailed Description
Member Typedef Documentation
BlockingMutex
using Slic3r::sla::_ccr< false >::BlockingMutex = execution::BlockingMutex<ExecutionSeq>
SpinningMutex
using Slic3r::sla::_ccr< false >::SpinningMutex = execution::SpinningMutex<ExecutionSeq>
Member Function Documentation
for_each()
template<class It , class Fn > static void Slic3r::sla::_ccr< false >::for_each (It from, It to, Fn && fn, size_t granularity = 1) inline static
    {
        execution::for_each(ex_seq, from, to, std::forward<Fn>(fn), granularity);
    }
References Slic3r::ex_seq, and Slic3r::execution::for_each().
max_concurreny()
static size_t Slic3r::sla::_ccr< false >::max_concurreny () inline static
    {
        return execution::max_concurrency(ex_seq);
    }
References Slic3r::ex_seq, and Slic3r::execution::max_concurrency().
reduce()
template<class... Args> static auto Slic3r::sla::_ccr< false >::reduce (Args &&... args) inline static
    {
        return execution::reduce(ex_seq, std::forward<Args>(args)...);
    }
References Slic3r::ex_seq, and Slic3r::execution::reduce().
The documentation for this struct was generated from the following file:
src/libslic3r/SLA/Concurrency.hpp