OrcaSlicer: Slic3r::GUI::TextCtrl Class Reference
Slic3r::GUI::TextCtrl Class Reference
#include <src/slic3r/GUI/Field.hpp>
Public Member Functions
TextCtrl (const ConfigOptionDef &opt, const t_config_option_key &id)
TextCtrl (wxWindow *parent, const ConfigOptionDef &opt, const t_config_option_key &id)
~TextCtrl ()
void BUILD () override
Finish constructing the Field's wxWidget-related properties, including setting its own sizer, etc.
bool value_was_changed ()
void propagate_value ()
void set_value (const std::string &value, bool change_event=false)
void set_value (const boost::any &value, bool change_event=false) override
Sets a value for this control. subclasses should overload with a specific version Postcondition: Method does not fire the on_change event.
void set_last_meaningful_value () override
void set_na_value () override
boost::any & get_value () override
Gets a boost::any representing this control. subclasses should overload with a specific version.
void msw_rescale () override
void enable () override
void disable () override
wxWindow * getWindow () override
wxTextCtrl * text_ctrl ()
void on_back_to_initial_value ()
Call the attached m_back_to_initial_value method.
void on_back_to_sys_value ()
Call the attached m_back_to_sys_value method.
void toggle (bool en)
Fires the enable or disable function, based on the input.
virtual wxString get_tooltip_text (const wxString &default_string)
void field_changed ()
virtual wxSizer * getSizer ()
If you don't know what you are getting back, check both methods for nullptr.
bool is_matched (const std::string &string, const std::string &pattern)
void get_value_by_opt_type (wxString &str, const bool check_value=true)
bool set_undo_bitmap (const ScalableBitmap *bmp)
bool set_undo_to_sys_bitmap (const ScalableBitmap *bmp)
bool set_label_colour (const wxColour *clr)
bool set_undo_tooltip (const wxString *tip)
bool set_undo_to_sys_tooltip (const wxString *tip)
bool * get_blink_ptr ()
virtual void sys_color_changed ()
bool get_enter_pressed () const
void set_enter_pressed (bool pressed)
const ScalableBitmap * undo_bitmap ()
const wxString * undo_tooltip ()
const ScalableBitmap * undo_to_sys_bitmap ()
const wxString * undo_to_sys_tooltip ()
const wxColour * label_color ()
const bool blink ()
const bool combine_side_text ()
Static Public Member Functions
template<class T >
static t_field Create (wxWindow *parent, const ConfigOptionDef &opt, const t_config_option_key &id)
Factory method for generating new derived classes.
static int def_width ()
static int def_width_wider ()
static int def_width_thinner ()
Public Attributes
wxWindow * window {nullptr}
wxWindow * m_parent {nullptr}
parent wx item, opportunity to refactor (probably not necessary - data duplication)
t_kill_focus m_on_kill_focus {nullptr}
Function object to store callback passed in from owning object.
t_change m_on_change {nullptr}
Function object to store callback passed in from owning object.
t_back_to_init m_back_to_initial_value { nullptr }
Function object to store callback passed in from owning object.
t_back_to_init m_back_to_sys_value { nullptr }
bool m_disable_change_event {false}
bool m_is_modified_value {false}
bool m_is_nonsys_value {true}
const ConfigOptionDef m_opt {ConfigOptionDef()}
Copy of ConfigOption for deduction purposes.
const t_config_option_key m_opt_id
int m_opt_idx = 0
{""};
double opt_height { 0.0 }
bool parent_is_custom_ctrl { false }
Protected Member Functions
virtual void PostInitialize ()
void on_kill_focus ()
Call the attached on_kill_focus method. It's important to use wxEvent instead of wxFocusEvent, in another case we can't unfocused control at all.
void on_change_field ()
Call the attached on_change method.
Protected Attributes
const ScalableBitmap * m_undo_bitmap = nullptr
const wxString * m_undo_tooltip = nullptr
const ScalableBitmap * m_undo_to_sys_bitmap = nullptr
const wxString * m_undo_to_sys_tooltip = nullptr
bool m_blink { false }
const wxColour * m_label_color = nullptr
boost::any m_value
boost::any m_last_meaningful_value
int m_em_unit
bool m_combine_side_text = false
bool bEnterPressed = false
Private Member Functions
Field (const ConfigOptionDef &opt, const t_config_option_key &id)
Field (wxWindow *parent, const ConfigOptionDef &opt, const t_config_option_key &id)
Detailed Description
Constructor & Destructor Documentation
TextCtrl() [1/2]
Slic3r::GUI::TextCtrl::TextCtrl (const ConfigOptionDef & opt, const t_config_option_key & id) inline
: Field(opt,  id) {}
TextCtrl() [2/2]
Slic3r::GUI::TextCtrl::TextCtrl (wxWindow * parent, const ConfigOptionDef & opt, const t_config_option_key & id) inline
: Field(parent, opt, id) {}
~TextCtrl()
Slic3r::GUI::TextCtrl::~TextCtrl () inline
{}
Member Function Documentation
blink()
const bool Slic3r::GUI::Field::blink () inline inherited
{ return m_blink; }
References Slic3r::GUI::Field::m_blink.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
BUILD()
void Slic3r::GUI::TextCtrl::BUILD () override virtual
Finish constructing the Field's wxWidget-related properties, including setting its own sizer, etc.
to allow the default handling
eliminating the g-code pop up text description
Implements Slic3r::GUI::Field.
                     {
    auto size = wxSize(def_width_wider() * m_em_unit, wxDefaultCoord);
    if (m_opt.height >= 0) size.SetHeight(m_opt.height*m_em_unit);
    if (m_opt.width >= 0) size.SetWidth(m_opt.width*m_em_unit);
  wxString text_value = wxString("");
  switch (m_opt.type) {
  case coFloatOrPercent:
  {
    text_value = double_to_string(m_opt.default_value->getFloat());
    if (m_opt.get_default_value<ConfigOptionFloatOrPercent>()->percent)
      text_value += "%";
    break;
  }
  case coPercent:
  {
    text_value = wxString::Format(_T("%i"), int(m_opt.default_value->getFloat()));
    text_value += "%";
    break;
  }
  case coPercents:
  case coFloats:
  case coFloat:
  {
    double val = m_opt.type == coFloats ?
      m_opt.get_default_value<ConfigOptionFloats>()->get_at(m_opt_idx) :
      m_opt.type == coFloat ?
        m_opt.default_value->getFloat() :
        m_opt.get_default_value<ConfigOptionPercents>()->get_at(m_opt_idx);
    text_value = double_to_string(val);
        m_last_meaningful_value = text_value;
    break;
  }
  case coString:
    text_value = m_opt.get_default_value<ConfigOptionString>()->value;
    break;
  case coStrings:
  {
    const ConfigOptionStrings *vec = m_opt.get_default_value<ConfigOptionStrings>();
    if (vec == nullptr || vec->empty()) break; //for the case of empty default value
    text_value = vec->get_at(m_opt_idx);
    break;
  }
    case coPoints:
        text_value = get_thumbnails_string(m_opt.get_default_value<ConfigOptionPoints>()->values);
        break;
  default:
    break;
  }
  // BBS: new param ui style
    // const long style = m_opt.multiline ? wxTE_MULTILINE : wxTE_PROCESS_ENTER/*0*/;
    auto temp = m_opt.multiline
        ? (wxWindow *) new wxTextCtrl(m_parent, wxID_ANY, text_value, wxDefaultPosition, size, wxTE_MULTILINE)
        : new ::TextInput(m_parent, text_value, _L(m_opt.sidetext), "", wxDefaultPosition, size, wxTE_PROCESS_ENTER);
  auto text_ctrl = m_opt.multiline ? (wxTextCtrl *)temp : ((TextInput *) temp)->GetTextCtrl();
    m_combine_side_text = !m_opt.multiline;
    if (parent_is_custom_ctrl && m_opt.height < 0)
        opt_height = (double) text_ctrl->GetSize().GetHeight() / m_em_unit;
    temp->SetFont(m_opt.is_code ?
                    Slic3r::GUI::wxGetApp().code_font() :
                    Slic3r::GUI::wxGetApp().normal_font());
  wxGetApp().UpdateDarkUI(temp);
    if (! m_opt.multiline && !wxOSX)
    // Only disable background refresh for single line input fields, as they are completely painted over by the edit control.
    // This does not apply to the multi-line edit field, where the last line and a narrow frame around the text is not cleared.
    temp->SetBackgroundStyle(wxBG_STYLE_PAINT);
#ifdef __WXOSX__
    text_ctrl->OSXDisableAllSmartSubstitutions(); // BBS
#endif // __WXOSX__
  temp->SetToolTip(get_tooltip_text(text_value));
    if (!m_opt.multiline) {
        text_ctrl->Bind(wxEVT_TEXT_ENTER, ([this, temp](wxEvent &e)
        {
#if !defined(__WXGTK__)
            e.Skip();
            temp->GetToolTip()->Enable(true);
#endif // __WXGTK__
            EnterPressed enter(this);
            propagate_value();
        }), text_ctrl->GetId());
    }
  text_ctrl->Bind(wxEVT_LEFT_DOWN, ([temp](wxEvent &event)
  {
    event.Skip();
    bool flag = false;
#ifdef __WXGTK__
    // I have no idea why, but on GTK flag works in other way
    flag = true;
#endif // __WXGTK__
    temp->GetToolTip()->Enable(flag);
  }), text_ctrl->GetId());
  temp->Bind(wxEVT_KILL_FOCUS, ([this, temp](wxEvent &e)
  {
    e.Skip();
#if !defined(__WXGTK__)
    temp->GetToolTip()->Enable(true);
#endif // __WXGTK__
        if (!bEnterPressed)
            propagate_value();
  }), temp->GetId());
/*
  // select all text using Ctrl+A
  temp->Bind(wxEVT_CHAR, ([temp](wxKeyEvent& event)
  {
    if (wxGetKeyState(wxKeyCode('A')) && wxGetKeyState(WXK_CONTROL))
      temp->SetSelection(-1, -1); //select all
    event.Skip();
  }));
*/
    // recast as a wxWindow to fit the calling convention
    window = dynamic_cast<wxWindow*>(temp);
}
References _L, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coFloats, Slic3r::coPercent, Slic3r::coPercents, Slic3r::coPoints, Slic3r::coString, Slic3r::coStrings, Slic3r::GUI::double_to_string(), Slic3r::ConfigOptionVector< T >::empty(), Slic3r::Enable, Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::GUI::get_thumbnails_string(), Slic3r::ConfigOptionFloatOrPercent::percent, size, Slic3r::ConfigOptionVector< T >::values, and wxOSX.
combine_side_text()
const bool Slic3r::GUI::Field::combine_side_text () inline inherited
{ return m_combine_side_text; } // BBS: new param style
References Slic3r::GUI::Field::m_combine_side_text.
Referenced by Slic3r::GUI::OG_CustomCtrl::get_pos(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
Create()
template<class T > static t_field Slic3r::GUI::Field::Create (wxWindow * parent, const ConfigOptionDef & opt, const t_config_option_key & id) inline static inherited
Factory method for generating new derived classes.
p;
    {
        auto p = Slic3r::make_unique<T>(parent, opt, id);
        p->PostInitialize();
    return std::move(p);
    }
def_width()
int Slic3r::GUI::Field::def_width () static inherited
{ return 8; }
Referenced by Slic3r::GUI::TabFilament::build(), and Slic3r::GUI::TabPrinter::build_kinematics_page().
def_width_thinner()
int Slic3r::GUI::Field::def_width_thinner () static inherited
{ return 4; }
Referenced by Slic3r::GUI::DiamTextCtrl::DiamTextCtrl(), and Slic3r::GUI::OptionsGroup::activate_line().
def_width_wider()
int Slic3r::GUI::Field::def_width_wider () static inherited
{ return 12; }
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
disable()
void Slic3r::GUI::TextCtrl::disable () override virtual
Implements Slic3r::GUI::Field.
{
    window->Disable();
    text_ctrl()->SetEditable(false); // BBS
}
enable()
void Slic3r::GUI::TextCtrl::enable () override virtual
Implements Slic3r::GUI::Field.
{
    window->Enable();
    text_ctrl()->SetEditable(true); // BBS
}
References TextInput::Enable().
Field() [1/2]
Slic3r::GUI::Field::Field (const ConfigOptionDef & opt, const t_config_option_key & id) inline private
: m_opt(opt), m_opt_id(id) {}
Field() [2/2]
Slic3r::GUI::Field::Field (wxWindow * parent, const ConfigOptionDef & opt, const t_config_option_key & id) inline private
: m_parent(parent), m_opt(opt), m_opt_id(id) {}
field_changed()
void Slic3r::GUI::Field::field_changed () inline inherited
{ on_change_field(); }
References Slic3r::GUI::Field::on_change_field().
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
get_blink_ptr()
bool * Slic3r::GUI::Field::get_blink_ptr () inline inherited
{
    return &m_blink;
    }
References Slic3r::GUI::Field::m_blink.
Referenced by Slic3r::GUI::ConfigOptionsGroup::get_custom_ctrl_with_blinking_ptr().
get_enter_pressed()
bool Slic3r::GUI::Field::get_enter_pressed () const inline inherited
{ return bEnterPressed; }
References Slic3r::GUI::Field::bEnterPressed.
get_tooltip_text()
wxString Slic3r::GUI::Field::get_tooltip_text (const wxString & default_string) virtual inherited
{
  wxString tooltip_text("");
#ifdef NDEBUG
  wxString tooltip = _(m_opt.tooltip);
    edit_tooltip(tooltip);
    std::string opt_id = m_opt_id;
    auto hash_pos = opt_id.find("#");
    if (hash_pos != std::string::npos) {
        opt_id.replace(hash_pos, 1,"[");
        opt_id += "]";
    }
  if (tooltip.length() > 0)
        tooltip_text = tooltip + "\n" +
        _(L("parameter name")) + "\t: " + opt_id;
 #endif
  return tooltip_text;
}
References _, edit_tooltip(), and L.
get_value()
boost::any & Slic3r::GUI::TextCtrl::get_value () override virtual
Gets a boost::any representing this control. subclasses should overload with a specific version.
Implements Slic3r::GUI::Field.
{
    wxString ret_str = text_ctrl()->GetValue(); // BBS
  // update m_value
  get_value_by_opt_type(ret_str);
  return m_value;
}
get_value_by_opt_type()
void Slic3r::GUI::Field::get_value_by_opt_type (wxString & str, const bool check_value = true) inherited
{
  switch (m_opt.type) {
    case coInt: {
        long val = 0;
        if (!str.ToLong(&val)) {
            if (!check_value) {
                m_value.clear();
                break;
            }
            show_error(m_parent, _(L("Invalid numeric.")));
            set_value(int(val), true);
        }
        m_value = int(val);
        break;
    }
  case coPercent:
  case coPercents:
  case coFloats:
  case coFloat:{
    if (m_opt.type == coPercent && !str.IsEmpty() &&  str.Last() == '%')
      str.RemoveLast();
    else if (!str.IsEmpty() && str.Last() == '%')
        {
            if (!check_value) {
                m_value.clear();
                break;
            }
      wxString label = m_opt.full_label.empty() ? _(m_opt.label) : _(m_opt.full_label);
            show_error(m_parent, from_u8((boost::format(_utf8(L("%s can't be percentage"))) % into_u8(label)).str()));
      set_value(double_to_string(m_opt.min), true);
      m_value = double(m_opt.min);
      break;
    }
        double val;
        bool is_na_value = m_opt.nullable && str == na_value();
        const char dec_sep = is_decimal_separator_point() ? '.' : ',';
        const char dec_sep_alt = dec_sep == '.' ? ',' : '.';
        // Replace the first incorrect separator in decimal number,
        // if this value doesn't "N/A" value in some language
        if (!is_na_value && str.Replace(dec_sep_alt, dec_sep, false) != 0)
            set_value(str, false);
        if (str == dec_sep)
            val = 0.0;
        else
        {
            if (is_na_value)
                val = ConfigOptionFloatsNullable::nil_value();
            else if (!str.ToDouble(&val))
            {
                if (!check_value) {
                    m_value.clear();
                    break;
                }
                show_error(m_parent, _(L("Invalid numeric.")));
                set_value(double_to_string(val), true);
            }
            if (m_opt.min > val || val > m_opt.max)
            {
                if (!check_value) {
                    m_value.clear();
                    break;
                }
                if (m_opt_id == "filament_flow_ratio") {
                    if (m_value.empty() || boost::any_cast<double>(m_value) != val) {
                        wxString msg_text = format_wxstr(_L("Value %s is out of range, continue?"), str);
//                        wxMessageDialog dialog(m_parent, msg_text, _L("Parameter validation") + ": " + m_opt_id, wxICON_WARNING | wxYES | wxNO);
                        WarningDialog dialog(m_parent, msg_text, _L("Parameter validation") + ": " + m_opt_id, wxYES | wxNO);
                        if (dialog.ShowModal() == wxID_NO) {
                            if (m_value.empty()) {
                                if (m_opt.min > val) val = m_opt.min;
                                if (val > m_opt.max) val = m_opt.max;
                            }
                            else
                                val = boost::any_cast<double>(m_value);
                            set_value(double_to_string(val), true);
                        }
                    }
                }
                else {
                    show_error(m_parent, _L("Value is out of range."));
                    if (m_opt.min > val) val = m_opt.min;
                    if (val > m_opt.max) val = m_opt.max;
                    set_value(double_to_string(val), true);
                }
            }
        }
        m_value = val;
    break; }
  case coString:
  case coStrings:
    case coFloatOrPercent: {
        if (m_opt.type == coFloatOrPercent && !str.IsEmpty() &&  str.Last() != '%')
        {
            double val = 0.;
            const char dec_sep = is_decimal_separator_point() ? '.' : ',';
            const char dec_sep_alt = dec_sep == '.' ? ',' : '.';
            // Replace the first incorrect separator in decimal number.
            if (str.Replace(dec_sep_alt, dec_sep, false) != 0)
                set_value(str, false);
            // remove space and "mm" substring, if any exists
            str.Replace(" ", "", true);
            str.Replace("m", "", true);
            if (!str.ToDouble(&val))
            {
                if (!check_value) {
                    m_value.clear();
                    break;
                }
                show_error(m_parent, _L("Invalid numeric."));
                set_value(double_to_string(val), true);
            }
            else if (((m_opt.sidetext.rfind("mm/s") != std::string::npos && val > m_opt.max) ||
                     (m_opt.sidetext.rfind("mm ") != std::string::npos && val > /*1*/m_opt.max_literal)) &&
                     (m_value.empty() || into_u8(str) != boost::any_cast<std::string>(m_value)))
            {
                if (!check_value) {
                    m_value.clear();
                    break;
                }
                const std::string sidetext = m_opt.sidetext.rfind("mm/s") != std::string::npos ? "mm/s" : "mm";
                const wxString stVal = double_to_string(val, 2);
                const wxString msg_text = from_u8((boost::format(_utf8(L("Is it %s%% or %s %s?\n"
                    "YES for %s%%, \n"
                    "NO for %s %s."))) % stVal % stVal % sidetext % stVal % stVal % sidetext).str());
                WarningDialog dialog(m_parent, msg_text, _L("Parameter validation") + ": " + m_opt_id, wxYES | wxNO);
                if ((val > 100) && dialog.ShowModal() == wxID_YES) {
                    set_value(from_u8((boost::format("%s%%") % stVal).str()), false/*true*/);
                    str += "%%";
                }
        else
          set_value(stVal, false); // it's no needed but can be helpful, when inputted value contained "," instead of "."
            }
        }
        m_value = into_u8(str);
    break; }
    case coPoints: {
        std::vector<Vec2d> out_values;
        str.Replace(" ", wxEmptyString, true);
        if (!str.IsEmpty()) {
            bool invalid_val = false;
            bool out_of_range_val = false;
            wxStringTokenizer thumbnails(str, ",");
            while (thumbnails.HasMoreTokens()) {
                wxString token = thumbnails.GetNextToken();
                double x, y;
                wxStringTokenizer thumbnail(token, "x");
                if (thumbnail.HasMoreTokens()) {
                    wxString x_str = thumbnail.GetNextToken();
                    if (x_str.ToDouble(&x) && thumbnail.HasMoreTokens()) {
                        wxString y_str = thumbnail.GetNextToken();
                        if (y_str.ToDouble(&y) && !thumbnail.HasMoreTokens()) {
                            if (m_opt_id == "bed_exclude_area") {
                                if (0 <= x &&  0 <= y) {
                                    out_values.push_back(Vec2d(x, y));
                                    continue;
                                }
                            }
                            else {
                                if (0 < x && x < 1000 && 0 < y && y < 1000) {
                                    out_values.push_back(Vec2d(x, y));
                                    continue;
                                }
                            }
                            out_of_range_val = true;
                            break;
                        }
                    }
                }
                invalid_val = true;
                break;
            }
            if (out_of_range_val) {
                wxString text_value;
                if (!m_value.empty())
                    text_value = get_thumbnails_string(boost::any_cast<std::vector<Vec2d>>(m_value));
                set_value(text_value, true);
                show_error(m_parent, _L("Value is out of range."));
            }
            else if (invalid_val) {
                wxString text_value;
                if (!m_value.empty())
                    text_value = get_thumbnails_string(boost::any_cast<std::vector<Vec2d>>(m_value));
                set_value(text_value, true);
                show_error(m_parent, format_wxstr(_L("Invalid format. Expected vector format: \"%1%\""),"XxY, XxY, ..." ));
            }
        }
        m_value = out_values;
        break; }
  default:
    break;
  }
}
References _, _L, _utf8, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coFloats, Slic3r::coInt, Slic3r::coPercent, Slic3r::coPercents, Slic3r::coPoints, Slic3r::coString, Slic3r::coStrings, Slic3r::GUI::double_to_string(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_u8(), Slic3r::GUI::get_thumbnails_string(), int, Slic3r::GUI::into_u8(), Slic3r::is_decimal_separator_point(), L, Slic3r::GUI::na_value(), Slic3r::ConfigOptionFloatsTempl< NULLABLE >::nil_value(), Slic3r::GUI::show_error(), Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::thumbnails().
getSizer()
virtual wxSizer * Slic3r::GUI::Field::getSizer () inline virtual inherited
If you don't know what you are getting back, check both methods for nullptr.
Reimplemented in Slic3r::GUI::PointCtrl, and Slic3r::GUI::SliderCtrl.
{ return nullptr; }
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::correct_items_positions(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::render(), and Slic3r::GUI::OG_CustomCtrl::CtrlLine::update_visibility().
getWindow()
wxWindow * Slic3r::GUI::TextCtrl::getWindow () inline override virtual
Reimplemented from Slic3r::GUI::Field.
{ return window; }
References window.
is_matched()
bool Slic3r::GUI::Field::is_matched (const std::string & string, const std::string & pattern) inherited
{
  std::regex regex_pattern(pattern, std::regex_constants::icase); // use ::icase to make the matching case insensitive like /i in perl
  return std::regex_match(string, regex_pattern);
}
label_color()
const wxColour * Slic3r::GUI::Field::label_color () inline inherited
{ return m_label_color; }
References Slic3r::GUI::Field::m_label_color.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
msw_rescale()
void Slic3r::GUI::TextCtrl::msw_rescale () override virtual
Reimplemented from Slic3r::GUI::Field.
{
    Field::msw_rescale();
    auto size = wxSize(def_width_wider() * m_em_unit, wxDefaultCoord);
    if (m_opt.height >= 0)
        size.SetHeight(m_opt.height*m_em_unit);
    else if (parent_is_custom_ctrl && opt_height > 0)
        size.SetHeight(lround(opt_height*m_em_unit));
    if (m_opt.width >= 0) size.SetWidth(m_opt.width*m_em_unit);
    if (size != wxDefaultSize)
    {
        wxTextCtrl *field = text_ctrl(); // BBS
        if (parent_is_custom_ctrl)
            field->SetSize(size);
        else
            field->SetMinSize(size);
        if (field != window) {
            window->SetSize(size);
            window->SetMinSize(size);
            dynamic_cast<::TextInput *>(window)->Rescale();
        }
    }
}
References Slic3r::GUI::Field::msw_rescale(), and size.
on_back_to_initial_value()
void Slic3r::GUI::Field::on_back_to_initial_value () inherited
Call the attached m_back_to_initial_value method.
{
  if (m_back_to_initial_value != nullptr && m_is_modified_value)
    m_back_to_initial_value(m_opt_id);
}
Referenced by Slic3r::GUI::OG_CustomCtrl::OnLeftDown().
on_back_to_sys_value()
void Slic3r::GUI::Field::on_back_to_sys_value () inherited
Call the attached m_back_to_sys_value method.
{
  if (m_back_to_sys_value != nullptr && m_is_nonsys_value)
    m_back_to_sys_value(m_opt_id);
}
Referenced by Slic3r::GUI::OG_CustomCtrl::OnLeftDown().
on_change_field()
void Slic3r::GUI::Field::on_change_field () protected inherited
Call the attached on_change method.
{
//       std::cerr << "calling Field::_on_change \n";
    if (m_on_change != nullptr && !m_disable_change_event)
        m_on_change(m_opt_id, get_value());
}
Referenced by Slic3r::GUI::Field::field_changed().
on_kill_focus()
void Slic3r::GUI::Field::on_kill_focus () protected inherited
Call the attached on_kill_focus method. It's important to use wxEvent instead of wxFocusEvent, in another case we can't unfocused control at all.
{
  // call the registered function if it is available
    if (m_on_kill_focus!=nullptr)
        m_on_kill_focus(m_opt_id);
}
PostInitialize()
void Slic3r::GUI::Field::PostInitialize () protected virtual inherited
{
  auto color = wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW);
  switch (m_opt.type)
  {
  case coPercents:
  case coFloats:
  case coStrings:
  case coBools:
  case coInts:
    // BBS
    case coEnums: {
    auto tag_pos = m_opt_id.find("#");
    if (tag_pos != std::string::npos)
      m_opt_idx = stoi(m_opt_id.substr(tag_pos + 1, m_opt_id.size()));
    break;
  }
  default:
    break;
  }
    // initialize m_unit_value
    m_em_unit = em_unit(m_parent);
    parent_is_custom_ctrl = dynamic_cast<OG_CustomCtrl*>(m_parent) != nullptr;
  BUILD();
  // For the mode, when settings are in non-modal dialog, neither dialog nor tabpanel doesn't receive wxEVT_KEY_UP event, when some field is selected.
  // So, like a workaround check wxEVT_KEY_UP event for the Filed and switch between tabs if Ctrl+(1-4) was pressed
    if (getWindow()) {
        if (m_opt.readonly) getWindow()->Disable();
    getWindow()->Bind(wxEVT_KEY_UP, [](wxKeyEvent& evt) {
        if ((evt.GetModifiers() & wxMOD_CONTROL) != 0) {
          int tab_id = -1;
          switch (evt.GetKeyCode()) {
          case '1': { tab_id = 0; break; }
          case '2': { tab_id = 1; break; }
        case '3': { tab_id = 2; break; }
        case '4': { tab_id = 3; break; }
#ifdef __APPLE__
        case 'f':
#else /* __APPLE__ */
        case WXK_CONTROL_F:
#endif /* __APPLE__ */
                case 'F': {
                    //wxGetApp().plater()->search(false, Preset::TYPE_MODEL, nullptr, nullptr);
                    break;
                }
          default: break;
          }
          if (tab_id >= 0)
          wxGetApp().mainframe->select_tab(tab_id);
        if (tab_id > 0)
          // tab panel should be focused for correct navigation between tabs
            wxGetApp().tab_panel()->SetFocus();
        }
        evt.Skip();
      });
    }
}
References Slic3r::GUI::Field::BUILD(), Slic3r::coBools, Slic3r::coEnums, Slic3r::coFloats, Slic3r::coInts, Slic3r::coPercents, Slic3r::coStrings, em_unit(), Slic3r::GUI::Field::getWindow(), Slic3r::GUI::Field::m_em_unit, Slic3r::GUI::Field::m_opt, Slic3r::GUI::Field::m_opt_id, Slic3r::GUI::Field::m_opt_idx, Slic3r::GUI::Field::m_parent, Slic3r::GUI::Field::parent_is_custom_ctrl, Slic3r::ConfigOptionDef::readonly, and Slic3r::ConfigOptionDef::type.
propagate_value()
void Slic3r::GUI::TextCtrl::propagate_value ()
{
    if (!is_defined_input_value<wxTextCtrl>(text_ctrl(), m_opt.type)) { // BBS
    // on_kill_focus() cause a call of OptionsGroup::reload_config(),
    // Thus, do it only when it's really needed (when undefined value was input)
        if (!m_value.empty()) // BBS: null value
            on_kill_focus();
  } else if (value_was_changed())
        on_change_field();
}
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
set_enter_pressed()
void Slic3r::GUI::Field::set_enter_pressed (bool pressed) inline inherited
{ bEnterPressed = pressed; }
References Slic3r::GUI::Field::bEnterPressed.
Referenced by Slic3r::GUI::Field::EnterPressed::EnterPressed(), and Slic3r::GUI::Field::EnterPressed::~EnterPressed().
set_label_colour()
bool Slic3r::GUI::Field::set_label_colour (const wxColour * clr) inline inherited
{
    if (m_label_color != clr) {
      m_label_color = clr;
    }
    return false;
  }
References Slic3r::GUI::Field::m_label_color.
Referenced by Slic3r::GUI::Tab::decorate(), and Slic3r::GUI::Tab::update_label_colours().
set_last_meaningful_value()
void Slic3r::GUI::TextCtrl::set_last_meaningful_value () override virtual
Reimplemented from Slic3r::GUI::Field.
{
    text_ctrl()->SetValue(boost::any_cast<wxString>(m_last_meaningful_value)); // BBS
    propagate_value();
}
set_na_value()
void Slic3r::GUI::TextCtrl::set_na_value () override virtual
Reimplemented from Slic3r::GUI::Field.
{
    text_ctrl()->SetValue(na_value()); // BBS
    propagate_value();
}
References Slic3r::GUI::na_value().
set_undo_bitmap()
bool Slic3r::GUI::Field::set_undo_bitmap (const ScalableBitmap * bmp) inline inherited
{
      if (m_undo_bitmap != bmp) {
        m_undo_bitmap = bmp;
        return true;
      }
      return false;
    }
References Slic3r::GUI::Field::m_undo_bitmap.
Referenced by Slic3r::GUI::Tab::decorate().
set_undo_to_sys_bitmap()
bool Slic3r::GUI::Field::set_undo_to_sys_bitmap (const ScalableBitmap * bmp) inline inherited
{
      if (m_undo_to_sys_bitmap != bmp) {
        m_undo_to_sys_bitmap = bmp;
        return true;
      }
      return false;
    }
References Slic3r::GUI::Field::m_undo_to_sys_bitmap.
Referenced by Slic3r::GUI::Tab::decorate().
set_undo_to_sys_tooltip()
bool Slic3r::GUI::Field::set_undo_to_sys_tooltip (const wxString * tip) inline inherited
{
    if (m_undo_to_sys_tooltip != tip) {
      m_undo_to_sys_tooltip = tip;
      return true;
    }
    return false;
  }
References Slic3r::GUI::Field::m_undo_to_sys_tooltip.
Referenced by Slic3r::GUI::Tab::decorate().
set_undo_tooltip()
bool Slic3r::GUI::Field::set_undo_tooltip (const wxString * tip) inline inherited
{
    if (m_undo_tooltip != tip) {
      m_undo_tooltip = tip;
      return true;
    }
    return false;
  }
References Slic3r::GUI::Field::m_undo_tooltip.
Referenced by Slic3r::GUI::Tab::decorate().
set_value() [1/2]
void Slic3r::GUI::TextCtrl::set_value (const boost::any & value, bool change_event = false) override virtual
Sets a value for this control. subclasses should overload with a specific version Postcondition: Method does not fire the on_change event.
Implements Slic3r::GUI::Field.
{
    m_disable_change_event = !change_event;
    if (m_opt.nullable) {
        const bool m_is_na_val = boost::any_cast<wxString>(value) == na_value();
        if (!m_is_na_val)
            m_last_meaningful_value = value;
        text_ctrl()->SetValue(m_is_na_val ? na_value() :
                                            boost::any_cast<wxString>(value)); // BBS
    }
    else
        text_ctrl()->SetValue(value.empty() ? "" : boost::any_cast<wxString>(value)); // BBS // BBS: null value
    m_disable_change_event = false;
    if (!change_event) {
        wxString ret_str = text_ctrl()->GetValue();
        /* Update m_value to correct work of next value_was_changed().
         * But after checking of entered value, don't fix the "incorrect" value and don't show a warning message,
         * just clear m_value in this case.
         */
        get_value_by_opt_type(ret_str, false);
    }
}
References Slic3r::GUI::na_value().
set_value() [2/2]
void Slic3r::GUI::TextCtrl::set_value (const std::string & value, bool change_event = false) inline
{
    m_disable_change_event = !change_event;
        dynamic_cast<wxTextCtrl*>(window)->SetValue(wxString(value));
    m_disable_change_event = false;
    }
References Slic3r::GUI::Field::m_disable_change_event, and window.
sys_color_changed()
void Slic3r::GUI::Field::sys_color_changed () virtual inherited
Reimplemented in Slic3r::GUI::ColourPicker, and Slic3r::GUI::PointCtrl.
{
#ifdef _WIN32
  if (wxWindow* win = this->getWindow())
    wxGetApp().UpdateDarkUI(win);
#endif
}
text_ctrl()
wxTextCtrl * Slic3r::GUI::TextCtrl::text_ctrl ()
{
    auto ctrl = dynamic_cast<wxTextCtrl *>(window);
    if (ctrl == nullptr)
        ctrl = dynamic_cast<::TextInput *>(window)->GetTextCtrl();
    return ctrl;
}
References Slic3r::GUI::ctrl.
toggle()
void Slic3r::GUI::Field::toggle (bool en) inherited
Fires the enable or disable function, based on the input.
{ en && !m_opt.readonly ? enable() : disable(); }
Referenced by Slic3r::GUI::TabFilament::add_filament_overrides_page(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::Tab::compatible_widget_reload(), Slic3r::GUI::Tab::toggle_option(), Slic3r::GUI::ObjectTableSettings::update_config_values(), Slic3r::GUI::ObjectSettings::update_config_values(), Slic3r::GUI::TabFilament::update_filament_overrides_page(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
undo_bitmap()
const ScalableBitmap * Slic3r::GUI::Field::undo_bitmap () inline inherited
{ return m_undo_bitmap; }
References Slic3r::GUI::Field::m_undo_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
undo_to_sys_bitmap()
const ScalableBitmap * Slic3r::GUI::Field::undo_to_sys_bitmap () inline inherited
{ return m_undo_to_sys_bitmap; }
References Slic3r::GUI::Field::m_undo_to_sys_bitmap.
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::render().
undo_to_sys_tooltip()
const wxString * Slic3r::GUI::Field::undo_to_sys_tooltip () inline inherited
{ return m_undo_to_sys_tooltip; }
References Slic3r::GUI::Field::m_undo_to_sys_tooltip.
Referenced by Slic3r::GUI::OG_CustomCtrl::OnMotion().
undo_tooltip()
const wxString * Slic3r::GUI::Field::undo_tooltip () inline inherited
{ return m_undo_tooltip; }
References Slic3r::GUI::Field::m_undo_tooltip.
Referenced by Slic3r::GUI::OG_CustomCtrl::OnMotion().
value_was_changed()
bool Slic3r::GUI::TextCtrl::value_was_changed ()
{
    if (m_value.empty())
        return true;
    boost::any val = m_value;
    wxString   ret_str = text_ctrl()->GetValue(); // BBS
    // update m_value!
    // ret_str might be changed inside get_value_by_opt_type
    get_value_by_opt_type(ret_str);
    switch (m_opt.type) {
    case coInt:
        return boost::any_cast<int>(m_value) != boost::any_cast<int>(val);
    case coPercent:
    case coPercents:
    case coFloats:
    case coFloat: {
        if (m_opt.nullable && std::isnan(boost::any_cast<double>(m_value)) &&
                              std::isnan(boost::any_cast<double>(val)))
            return false;
        return boost::any_cast<double>(m_value) != boost::any_cast<double>(val);
    }
    case coString:
    case coStrings:
    case coFloatOrPercent:
        return boost::any_cast<std::string>(m_value) != boost::any_cast<std::string>(val);
    default:
        return true;
    }
}
References Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coFloats, Slic3r::coInt, Slic3r::coPercent, Slic3r::coPercents, Slic3r::coString, and Slic3r::coStrings.
Member Data Documentation
bEnterPressed
bool Slic3r::GUI::Field::bEnterPressed = false protected inherited
Referenced by Slic3r::GUI::Field::get_enter_pressed(), and Slic3r::GUI::Field::set_enter_pressed().
m_back_to_initial_value
t_back_to_init Slic3r::GUI::Field::m_back_to_initial_value { nullptr } inherited
Function object to store callback passed in from owning object.
Referenced by Slic3r::GUI::Field::~Field().
m_back_to_sys_value
t_back_to_init Slic3r::GUI::Field::m_back_to_sys_value { nullptr } inherited
Referenced by Slic3r::GUI::Field::~Field().
m_blink
bool Slic3r::GUI::Field::m_blink { false } protected inherited
Referenced by Slic3r::GUI::Field::blink(), and Slic3r::GUI::Field::get_blink_ptr().
m_combine_side_text
bool Slic3r::GUI::Field::m_combine_side_text = false protected inherited
Referenced by Slic3r::GUI::Field::combine_side_text().
m_disable_change_event
bool Slic3r::GUI::Field::m_disable_change_event {false} inherited
Referenced by Slic3r::GUI::StaticText::set_value(), set_value(), Slic3r::GUI::SpinCtrl::set_value(), Slic3r::GUI::ColourPicker::set_value(), and Slic3r::GUI::StaticText::set_value().
m_em_unit
int Slic3r::GUI::Field::m_em_unit protected inherited
Referenced by Slic3r::GUI::Field::PostInitialize().
m_is_modified_value
bool Slic3r::GUI::Field::m_is_modified_value {false} inherited
Referenced by Slic3r::GUI::Tab::decorate().
m_is_nonsys_value
bool Slic3r::GUI::Field::m_is_nonsys_value {true} inherited
Referenced by Slic3r::GUI::Tab::decorate().
m_label_color
const wxColour* Slic3r::GUI::Field::m_label_color = nullptr protected inherited
Referenced by Slic3r::GUI::Field::label_color(), and Slic3r::GUI::Field::set_label_colour().
m_last_meaningful_value
boost::any Slic3r::GUI::Field::m_last_meaningful_value protected inherited
m_on_change
t_change Slic3r::GUI::Field::m_on_change {nullptr} inherited
Function object to store callback passed in from owning object.
Referenced by Slic3r::GUI::Field::~Field().
m_on_kill_focus
t_kill_focus Slic3r::GUI::Field::m_on_kill_focus {nullptr} inherited
Function object to store callback passed in from owning object.
Referenced by Slic3r::GUI::Field::~Field().
m_opt
const ConfigOptionDef Slic3r::GUI::Field::m_opt {ConfigOptionDef()} inherited
Copy of ConfigOption for deduction purposes.
Referenced by Slic3r::GUI::Field::PostInitialize(), Slic3r::GUI::TabPrint::toggle_options(), and Slic3r::GUI::PhysicalPrinterDialog::update_host_type().
m_opt_id
const t_config_option_key Slic3r::GUI::Field::m_opt_id inherited
Referenced by Slic3r::GUI::Field::PostInitialize().
m_opt_idx
int Slic3r::GUI::Field::m_opt_idx = 0 inherited
{""};
Referenced by Slic3r::GUI::Field::PostInitialize().
m_parent
wxWindow* Slic3r::GUI::Field::m_parent {nullptr} inherited
parent wx item, opportunity to refactor (probably not necessary - data duplication)
Referenced by Slic3r::GUI::Field::PostInitialize().
m_undo_bitmap
const ScalableBitmap* Slic3r::GUI::Field::m_undo_bitmap = nullptr protected inherited
Referenced by Slic3r::GUI::Field::set_undo_bitmap(), and Slic3r::GUI::Field::undo_bitmap().
m_undo_to_sys_bitmap
const ScalableBitmap* Slic3r::GUI::Field::m_undo_to_sys_bitmap = nullptr protected inherited
Referenced by Slic3r::GUI::Field::set_undo_to_sys_bitmap(), and Slic3r::GUI::Field::undo_to_sys_bitmap().
m_undo_to_sys_tooltip
const wxString* Slic3r::GUI::Field::m_undo_to_sys_tooltip = nullptr protected inherited
Referenced by Slic3r::GUI::Field::set_undo_to_sys_tooltip(), and Slic3r::GUI::Field::undo_to_sys_tooltip().
m_undo_tooltip
const wxString* Slic3r::GUI::Field::m_undo_tooltip = nullptr protected inherited
Referenced by Slic3r::GUI::Field::set_undo_tooltip(), and Slic3r::GUI::Field::undo_tooltip().
m_value
boost::any Slic3r::GUI::Field::m_value protected inherited
Referenced by Slic3r::GUI::SpinCtrl::get_value(), and Slic3r::GUI::StaticText::get_value().
opt_height
double Slic3r::GUI::Field::opt_height { 0.0 } inherited
parent_is_custom_ctrl
bool Slic3r::GUI::Field::parent_is_custom_ctrl { false } inherited
Referenced by Slic3r::GUI::Field::PostInitialize().
window
wxWindow* Slic3r::GUI::TextCtrl::window {nullptr}
Referenced by getWindow(), and set_value().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Field.hpp
src/slic3r/GUI/Field.cpp