OrcaSlicer: Slic3r::sla::IndexedMesh::AABBImpl Class Reference
Slic3r::sla::IndexedMesh::AABBImpl Class Reference
Public Member Functions
void init (const indexed_triangle_set &its, bool calculate_epsilon)
void intersect_ray (const indexed_triangle_set &its, const Vec3d &s, const Vec3d &dir, igl::Hit &hit)
void intersect_ray (const indexed_triangle_set &its, const Vec3d &s, const Vec3d &dir, std::vector< igl::Hit > &hits)
double squared_distance (const indexed_triangle_set &its, const Vec3d &point, int &i, Eigen::Matrix< double, 1, 3 > &closest)
Private Attributes
AABBTreeIndirect::Tree3f m_tree
double m_triangle_ray_epsilon
Detailed Description
Member Function Documentation
init()
void Slic3r::sla::IndexedMesh::AABBImpl::init (const indexed_triangle_set & its, bool calculate_epsilon) inline
    {
        m_triangle_ray_epsilon = 0.000001;
        if (calculate_epsilon) {
            // Calculate epsilon from average triangle edge length.
            double l = its_average_edge_length(its);
            if (l > 0)
                m_triangle_ray_epsilon = 0.000001 * l * l;
        }
        m_tree = AABBTreeIndirect::build_aabb_tree_over_indexed_triangle_set(
            its.vertices, its.indices);
    }
References Slic3r::AABBTreeIndirect::build_aabb_tree_over_indexed_triangle_set(), indexed_triangle_set::indices, Slic3r::its_average_edge_length(), m_tree, m_triangle_ray_epsilon, and indexed_triangle_set::vertices.
intersect_ray() [1/2]
void Slic3r::sla::IndexedMesh::AABBImpl::intersect_ray (const indexed_triangle_set & its, const Vec3d & s, const Vec3d & dir, igl::Hit & hit) inline
    {
        AABBTreeIndirect::intersect_ray_first_hit(its.vertices, its.indices,
                                                  m_tree, s, dir, hit, m_triangle_ray_epsilon);
    }
References indexed_triangle_set::indices, Slic3r::AABBTreeIndirect::intersect_ray_first_hit(), m_tree, m_triangle_ray_epsilon, and indexed_triangle_set::vertices.
intersect_ray() [2/2]
void Slic3r::sla::IndexedMesh::AABBImpl::intersect_ray (const indexed_triangle_set & its, const Vec3d & s, const Vec3d & dir, std::vector< igl::Hit > & hits) inline
    {
        AABBTreeIndirect::intersect_ray_all_hits(its.vertices, its.indices,
                                                 m_tree, s, dir, hits, m_triangle_ray_epsilon);
    }
References indexed_triangle_set::indices, Slic3r::AABBTreeIndirect::intersect_ray_all_hits(), m_tree, m_triangle_ray_epsilon, and indexed_triangle_set::vertices.
squared_distance()
double Slic3r::sla::IndexedMesh::AABBImpl::squared_distance (const indexed_triangle_set & its, const Vec3d & point, int & i, Eigen::Matrix< double, 1, 3 > & closest) inline
    {
        size_t idx_unsigned = 0;
        Vec3d  closest_vec3d(closest);
        double dist =
            AABBTreeIndirect::squared_distance_to_indexed_triangle_set(
                its.vertices, its.indices, m_tree, point, idx_unsigned,
                closest_vec3d);
        i       = int(idx_unsigned);
        closest = closest_vec3d;
        return dist;
    }
References indexed_triangle_set::indices, int, m_tree, Slic3r::AABBTreeIndirect::squared_distance_to_indexed_triangle_set(), and indexed_triangle_set::vertices.
Member Data Documentation
m_tree
AABBTreeIndirect::Tree3f Slic3r::sla::IndexedMesh::AABBImpl::m_tree private
Referenced by init(), intersect_ray(), intersect_ray(), and squared_distance().
m_triangle_ray_epsilon
double Slic3r::sla::IndexedMesh::AABBImpl::m_triangle_ray_epsilon private
Referenced by init(), intersect_ray(), and intersect_ray().
The documentation for this class was generated from the following file:
src/libslic3r/SLA/IndexedMesh.cpp