OrcaSlicer: Slic3r::AppConfig Class Reference
Slic3r::AppConfig Class Reference
#include <src/libslic3r/AppConfig.hpp>
Public Types
enum class EAppMode : unsigned char { Editor , GCodeViewer }
typedef std::map< std::string, std::map< std::string, std::set< std::string > > > VendorMap
typedef std::map< std::string, nlohmann::json > MachineSettingMap
Public Member Functions
AppConfig ()
std::string get_language_code ()
std::string get_hms_host ()
void reset ()
void set_defaults ()
std::string load ()
void save ()
bool dirty () const
void set_dirty ()
bool get (const std::string &section, const std::string &key, std::string &value) const
std::string get (const std::string &section, const std::string &key) const
std::string get (const std::string &key) const
void set (const std::string &section, const std::string &key, const std::string &value)
void set_str (const std::string &section, const std::string &key, const std::string &value)
void set (const std::string &section, const std::string &key, bool value)
void set (const std::string &key, const std::string &value)
void set_bool (const std::string &key, const bool &value)
bool has (const std::string &section, const std::string &key) const
bool has (const std::string &key) const
void erase (const std::string &section, const std::string &key)
bool has_section (const std::string &section) const
const std::map< std::string, std::string > & get_section (const std::string &section) const
void set_section (const std::string &section, const std::map< std::string, std::string > &data)
void clear_section (const std::string &section)
bool get_variant (const std::string &vendor, const std::string &model, const std::string &variant) const
void set_variant (const std::string &vendor, const std::string &model, const std::string &variant, bool enable)
void set_vendors (const AppConfig &from)
void set_vendors (const VendorMap &vendors)
void set_vendors (VendorMap &&vendors)
const VendorMap & vendors () const
bool has_printer_settings (std::string printer) const
void clear_printer_settings (std::string printer)
bool has_printer_setting (std::string printer, std::string name)
std::string get_printer_setting (std::string printer, std::string name)
std::string set_printer_setting (std::string printer, std::string name, std::string value)
const std::vector< std::string > & get_filament_presets () const
void set_filament_presets (const std::vector< std::string > &filament_presets)
const std::vector< std::string > & get_filament_colors () const
void set_filament_colors (const std::vector< std::string > &filament_colors)
std::string get_last_dir () const
void update_config_dir (const std::string &dir)
void update_skein_dir (const std::string &dir)
std::string get_last_output_dir (const std::string &alt, const bool removable=false) const
void update_last_output_dir (const std::string &dir, const bool removable=false)
std::string get_last_backup_dir () const
void update_last_backup_dir (const std::string &dir)
std::string get_region ()
std::string get_country_code ()
bool is_engineering_region ()
void reset_selections ()
std::string config_path ()
bool legacy_datadir () const
void set_legacy_datadir (bool value)
std::string version_check_url () const
Semver orig_version () const
bool exists ()
void set_loading_path (const std::string &path)
std::string loading_path ()
std::vector< std::string > get_recent_projects () const
void set_recent_projects (const std::vector< std::string > &recent_projects)
void set_mouse_device (const std::string &name, double translation_speed, double translation_deadzone, float rotation_speed, float rotation_deadzone, double zoom_speed, bool swap_yz)
std::vector< std::string > get_mouse_device_names () const
bool get_mouse_device_translation_speed (const std::string &name, double &speed) const
bool get_mouse_device_translation_deadzone (const std::string &name, double &deadzone) const
bool get_mouse_device_rotation_speed (const std::string &name, float &speed) const
bool get_mouse_device_rotation_deadzone (const std::string &name, float &deadzone) const
bool get_mouse_device_zoom_speed (const std::string &name, double &speed) const
bool get_mouse_device_swap_yz (const std::string &name, bool &swap) const
Static Public Attributes
static const std::string SECTION_FILAMENTS = "filaments"
static const std::string SECTION_MATERIALS = "sla_materials"
Private Member Functions
template<typename T >
bool get_3dmouse_device_numeric_value (const std::string &device_name, const char *parameter_name, T &out) const
Private Attributes
EAppMode m_mode { EAppMode::Editor }
std::map< std::string, std::map< std::string, std::string > > m_storage
VendorMap m_vendors
MachineSettingMap m_printer_settings
bool m_dirty
Semver m_orig_version
bool m_legacy_datadir
std::string m_loading_path
std::vector< std::string > m_filament_presets
std::vector< std::string > m_filament_colors
Detailed Description
Member Typedef Documentation
MachineSettingMap
typedef std::map<std::string, nlohmann::json> Slic3r::AppConfig::MachineSettingMap
VendorMap
typedef std::map<std::string, std::map<std::string, std::set<std::string> > > Slic3r::AppConfig::VendorMap
Member Enumeration Documentation
EAppMode
enum class Slic3r::AppConfig::EAppMode : unsigned char strong
Enumerator
Editor
GCodeViewer
  {
    Editor,
    GCodeViewer
  };
Constructor & Destructor Documentation
AppConfig()
Slic3r::AppConfig::AppConfig () inline explicit
                       :
    m_dirty(false),
    m_orig_version(Semver::invalid()),
    m_mode(EAppMode::Editor),
    m_legacy_datadir(false)
  {
    this->reset();
  }
References reset().
Member Function Documentation
clear_printer_settings()
void Slic3r::AppConfig::clear_printer_settings (std::string printer) inline
{
        m_printer_settings.erase(printer);
        m_dirty = true;
    }
References m_dirty, and m_printer_settings.
Referenced by Slic3r::PresetBundle::export_selections().
clear_section()
void Slic3r::AppConfig::clear_section (const std::string & section) inline
    { m_storage[section].clear(); }
References m_storage.
Referenced by Slic3r::PresetBundle::export_selections(), Slic3r::GUI::Config::Snapshot::export_selections(), Slic3r::GUI::GuideFrame::run(), and Slic3r::GUI::GuideFrame::SaveProfile().
config_path()
std::string Slic3r::AppConfig::config_path ()
{
#ifdef USE_JSON_CONFIG
    std::string path = (m_mode == EAppMode::Editor) ?
        (boost::filesystem::path(Slic3r::data_dir()) / (SLIC3R_APP_KEY ".conf")).make_preferred().string() :
        (boost::filesystem::path(Slic3r::data_dir()) / (GCODEVIEWER_APP_KEY ".conf")).make_preferred().string();
#else
    std::string path = (m_mode == EAppMode::Editor) ?
        (boost::filesystem::path(Slic3r::data_dir()) / (SLIC3R_APP_KEY ".ini")).make_preferred().string() :
        (boost::filesystem::path(Slic3r::data_dir()) / (GCODEVIEWER_APP_KEY ".ini")).make_preferred().string();
#endif
    return path;
}
References Slic3r::data_dir(), Editor, GCODEVIEWER_APP_KEY, and m_mode.
Referenced by exists(), Slic3r::GUI::GUI_App::init_app_config(), loading_path(), and save().
dirty()
bool Slic3r::AppConfig::dirty () const inline
{ return m_dirty; }
References m_dirty.
erase()
void Slic3r::AppConfig::erase (const std::string & section, const std::string & key) inline
  {
    auto it = m_storage.find(section);
    if (it != m_storage.end()) {
      it->second.erase(key);
    }
  }
References m_storage.
Referenced by Slic3r::GUI::GUI_App::load_language(), and set_defaults().
exists()
bool Slic3r::AppConfig::exists ()
{
    return boost::filesystem::exists(config_path());
}
References config_path().
Referenced by Slic3r::GUI::GUI_App::init_app_config().
get() [1/3]
std::string Slic3r::AppConfig::get (const std::string & key) const inline
    { std::string value; this->get("app", key, value); return value; }
References get().
get() [2/3]
std::string Slic3r::AppConfig::get (const std::string & section, const std::string & key) const inline
    { std::string value; this->get(section, key, value); return value; }
References get().
get() [3/3]
bool Slic3r::AppConfig::get (const std::string & section, const std::string & key, std::string & value) const inline
  {
    value.clear();
    auto it = m_storage.find(section);
    if (it == m_storage.end())
      return false;
    auto it2 = it->second.find(key);
    if (it2 == it->second.end())
      return false;
    value = it2->second;
    return true;
  }
References m_storage.
Referenced by Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::ZUserLogin::ZUserLogin(), Slic3r::GUI::GUI_App::check_privacy_update(), Slic3r::GUI::GUI_App::check_track_enable(), Slic3r::GUI::GUI_App::copy_network_if_available(), Slic3r::GUI::PreferencesDialog::create(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_backup_input(), Slic3r::GUI::PreferencesDialog::create_item_checkbox(), Slic3r::GUI::PreferencesDialog::create_item_combobox(), Slic3r::GUI::PreferencesDialog::create_item_darkmode_checkbox(), Slic3r::GUI::PreferencesDialog::create_item_downloads(), Slic3r::GUI::PreferencesDialog::create_item_input(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_loglevel_combobox(), Slic3r::GUI::PreferencesDialog::create_item_multiple_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::PreferencesDialog::create_shortcuts_page(), Slic3r::PresetBundle::export_selections(), get(), get(), Slic3r::GUI::GUI_App::get_extra_header(), get_hms_host(), get_language_code(), Slic3r::GUI::GUI_App::get_mode(), get_region(), Slic3r::MachineObject::get_user_access_code(), Slic3r::GUI::ConnectPrinterDialog::init_bitmap(), Slic3r::GUI::GUI_App::init_download_path(), is_engineering_region(), Slic3r::GUI::Config::SnapshotDB::is_on_snapshot(), Slic3r::MachineObject::is_support_ams_mapping(), load(), Slic3r::GUI::GUI_App::load_language(), Slic3r::PresetBundle::load_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::GUI_App::on_init_network(), Slic3r::GUI::GUI_App::on_user_login_handle(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::GUI_App::post_init(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::GUI::GUI_App::restart_networking(), Slic3r::PresetBundle::save_user_presets(), Slic3r::GUI::Plater::send_gcode(), Slic3r::GUI::SelectMachineDialog::set_default(), set_defaults(), Slic3r::GUI::Config::SnapshotDB::take_snapshot(), Slic3r::GUI::GUI_App::toolbar_icon_scale(), Slic3r::GUI::GUI_App::update_label_colours_from_appconfig(), Slic3r::PresetBundle::update_selections(), version_check_url(), and Slic3r::GUI::GUI_App::window_pos_restore().
get_3dmouse_device_numeric_value()
template<typename T > bool Slic3r::AppConfig::get_3dmouse_device_numeric_value (const std::string & device_name, const char * parameter_name, T & out) const inline private
  {
      std::string key = std::string("mouse_device:") + device_name;
      auto it = m_storage.find(key);
      if (it == m_storage.end())
          return false;
      auto it_val = it->second.find(parameter_name);
      if (it_val == it->second.end())
          return false;
        out = T(string_to_double_decimal_point(it_val->second));
      return true;
  }
References m_storage, out, and Slic3r::string_to_double_decimal_point().
Referenced by get_mouse_device_rotation_deadzone(), get_mouse_device_rotation_speed(), get_mouse_device_swap_yz(), get_mouse_device_translation_deadzone(), get_mouse_device_translation_speed(), and get_mouse_device_zoom_speed().
get_country_code()
std::string Slic3r::AppConfig::get_country_code ()
{
    std::string region = get_region();
// #if !BBL_RELEASE_TO_PUBLIC
//     if (is_engineering_region()) { return region; }
// #endif
    if (region == "CHN" || region == "China")
        return "CN";
    else if (region == "USA")
        return "US";
    else if (region == "Asia-Pacific")
        return "Others";
    else if (region == "Europe")
        return "US";
    else if (region == "North America")
        return "US";
    else
        return "Others";
    return "";
}
References get_region().
Referenced by Slic3r::GUI::GUI_App::check_new_version(), Slic3r::GUI::GUI_App::check_privacy_version(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::GUI_App::download_plugin(), Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::GUI::GUI_App::on_init_network(), Slic3r::GUI::GuideFrame::OnScriptMessage(), Slic3r::GUI::GUI_App::open_mall_page_dialog(), Slic3r::GUI::GUI_App::open_publish_page_dialog(), Slic3r::GUI::GUI_App::post_init(), Slic3r::GUI::NetworkTestDialog::start_test_bambulab(), Slic3r::GUI::NetworkTestDialog::start_test_oss(), Slic3r::GUI::NetworkTestDialog::start_test_oss_download(), and Slic3r::GUI::NetworkTestDialog::start_test_oss_upgrade().
get_filament_colors()
const std::vector< std::string > & Slic3r::AppConfig::get_filament_colors () const inline
{ return m_filament_colors; }
References m_filament_colors.
get_filament_presets()
const std::vector< std::string > & Slic3r::AppConfig::get_filament_presets () const inline
{ return m_filament_presets; }
References m_filament_presets.
get_hms_host()
std::string Slic3r::AppConfig::get_hms_host ()
{
    std::string sel = get("iot_environment");
    std::string host = "";
// #if !BBL_RELEASE_TO_PUBLIC
//     if (sel == ENV_DEV_HOST)
//         host = "e-dev.bambu-lab.com";
//     else if (sel == ENV_QAT_HOST)
//         host = "e-qa.bambu-lab.com";
//     else if (sel == ENV_PRE_HOST)
//         host = "e-pre.bambu-lab.com";
//     else if (sel == ENV_PRODUCT_HOST)
//         host = "e.bambulab.com";
//     return host;
// #else
    return "e.bambulab.com";
// #endif
}
References get().
Referenced by Slic3r::GUI::HMSQuery::download_hms_info(), Slic3r::GUI::get_hms_info_version(), and Slic3r::GUI::get_hms_wiki_url().
get_language_code()
std::string Slic3r::AppConfig::get_language_code ()
{
    std::string get_lang = get("language");
    if (get_lang.empty()) return "";
    if (get_lang == "zh_CN")
    {
        get_lang = "zh-cn";
    }
    else
    {
        if (get_lang.length() >= 2) { get_lang = get_lang.substr(0, 2); }
    }
    return get_lang;
}
References get().
Referenced by Slic3r::GUI::HMSQuery::hms_language_code().
get_last_backup_dir()
std::string Slic3r::AppConfig::get_last_backup_dir () const
{
  const auto it = m_storage.find("app");
  if (it != m_storage.end()) {
    const auto it2 = it->second.find("last_backup_path");
    if (it2 != it->second.end())
      return it2->second;
  }
  return "";
}
References m_storage.
get_last_dir()
std::string Slic3r::AppConfig::get_last_dir () const
{
    const auto it = m_storage.find("recent");
    if (it != m_storage.end()) {
        {
            const auto it2 = it->second.find("last_opened_folder");
            if (it2 != it->second.end() && ! it2->second.empty())
                return it2->second;
        }
        {
            const auto it2 = it->second.find("settings_folder");
            if (it2 != it->second.end() && ! it2->second.empty())
                return it2->second;
        }
    }
    return std::string();
}
References m_storage.
Referenced by get_last_output_dir(), Slic3r::GUI::GUI_App::import_model(), Slic3r::GUI::GUI_App::load_gcode(), and Slic3r::GUI::GUI_App::load_project().
get_last_output_dir()
std::string Slic3r::AppConfig::get_last_output_dir (const std::string & alt, const bool removable = false) const
{
  std::string s1 = ("last_export_path");
  const auto it = m_storage.find("app");
  if (it != m_storage.end()) {
    const auto it2 = it->second.find(s1);
    if (it2 != it->second.end() && !it2->second.empty())
      return it2->second;
  }
  return is_shapes_dir(alt) ? get_last_dir() : alt;
}
References get_last_dir(), Slic3r::is_shapes_dir(), and m_storage.
Referenced by Slic3r::GUI::Plater::export_gcode(), and Slic3r::GUI::Plater::export_gcode_3mf().
get_mouse_device_names()
std::vector< std::string > Slic3r::AppConfig::get_mouse_device_names () const
{
    static constexpr const char   *prefix     = "mouse_device:";
    static const size_t  prefix_len = strlen(prefix);
    std::vector<std::string> out;
    for (const auto& key_value_pair : m_storage)
        if (boost::starts_with(key_value_pair.first, prefix) && key_value_pair.first.size() > prefix_len)
            out.emplace_back(key_value_pair.first.substr(prefix_len));
    return out;
}
References m_storage, and out.
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_rotation_deadzone()
bool Slic3r::AppConfig::get_mouse_device_rotation_deadzone (const std::string & name, float & deadzone) const inline
    { return get_3dmouse_device_numeric_value(name, "rotation_deadzone", deadzone); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_rotation_speed()
bool Slic3r::AppConfig::get_mouse_device_rotation_speed (const std::string & name, float & speed) const inline
    { return get_3dmouse_device_numeric_value(name, "rotation_speed", speed); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_swap_yz()
bool Slic3r::AppConfig::get_mouse_device_swap_yz (const std::string & name, bool & swap) const inline
    { return get_3dmouse_device_numeric_value(name, "swap_yz", swap); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_translation_deadzone()
bool Slic3r::AppConfig::get_mouse_device_translation_deadzone (const std::string & name, double & deadzone) const inline
    { return get_3dmouse_device_numeric_value(name, "translation_deadzone", deadzone); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_translation_speed()
bool Slic3r::AppConfig::get_mouse_device_translation_speed (const std::string & name, double & speed) const inline
    { return get_3dmouse_device_numeric_value(name, "translation_speed", speed); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_mouse_device_zoom_speed()
bool Slic3r::AppConfig::get_mouse_device_zoom_speed (const std::string & name, double & speed) const inline
    { return get_3dmouse_device_numeric_value(name, "zoom_speed", speed); }
References get_3dmouse_device_numeric_value().
Referenced by Slic3r::GUI::Mouse3DController::load_config().
get_printer_setting()
std::string Slic3r::AppConfig::get_printer_setting (std::string printer, std::string name) inline
{
        if (!has_printer_setting(printer, name))
            return "";
        return m_printer_settings[printer][name];
    }
References has_printer_setting(), and m_printer_settings.
Referenced by Slic3r::PresetBundle::load_selections(), and Slic3r::PresetBundle::update_selections().
get_recent_projects()
std::vector< std::string > Slic3r::AppConfig::get_recent_projects () const
{
    std::vector<std::string> ret;
    const auto it = m_storage.find("recent_projects");
    if (it != m_storage.end())
    {
        for (const std::map<std::string, std::string>::value_type& item : it->second)
        {
            ret.push_back(item.second);
        }
    }
    return ret;
}
References m_storage.
get_region()
std::string Slic3r::AppConfig::get_region ()
{
// #if BBL_RELEASE_TO_PUBLIC
    return this->get("region");
// #else
//     std::string sel = get("iot_environment");
//     std::string region;
//     if (sel == ENV_DEV_HOST)
//         region = "ENV_CN_DEV";
//     else if (sel == ENV_QAT_HOST)
//         region = "ENV_CN_QA";
//     else if (sel == ENV_PRE_HOST)
//         region = "ENV_CN_PRE";
//     if (region.empty())
//         return this->get("region");
//     return region;
// #endif
}
References get().
Referenced by get_country_code().
get_section()
const std::map< std::string, std::string > & Slic3r::AppConfig::get_section (const std::string & section) const inline
    { return m_storage.find(section)->second; }
References m_storage.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::GuideFrame::apply_config(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), and Slic3r::Preset::set_visible_from_appconfig().
get_variant()
bool Slic3r::AppConfig::get_variant (const std::string & vendor, const std::string & model, const std::string & variant) const
{
    const auto it_v = m_vendors.find(vendor);
    if (it_v == m_vendors.end()) { return false; }
    const auto it_m = it_v->second.find(model);
    return it_m == it_v->second.end() ? false : it_m->second.find(variant) != it_m->second.end();
}
References m_vendors.
Referenced by Slic3r::GUI::PrinterPicker::PrinterPicker(), Slic3r::GUI::GuideFrame::LoadProfile(), set_variant(), and Slic3r::Preset::set_visible_from_appconfig().
has() [1/2]
bool Slic3r::AppConfig::has (const std::string & key) const inline
    { return this->has("app", key); }
References has().
has() [2/2]
bool Slic3r::AppConfig::has (const std::string & section, const std::string & key) const inline
  {
    auto it = m_storage.find(section);
    if (it == m_storage.end())
      return false;
    auto it2 = it->second.find(key);
    return it2 != it->second.end() && ! it2->second.empty();
  }
References m_storage.
Referenced by Slic3r::GUI::GUI_App::get_mode(), has(), Slic3r::PresetBundle::load_selections(), Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::Config::SnapshotDB::take_snapshot(), Slic3r::GUI::GUI_App::update_label_colours_from_appconfig(), Slic3r::GUI::PageMaterials::update_lists(), Slic3r::PresetBundle::update_selections(), and Slic3r::GUI::GUI_App::window_pos_restore().
has_printer_setting()
bool Slic3r::AppConfig::has_printer_setting (std::string printer, std::string name) inline
{
        if (!has_printer_settings(printer))
            return false;
        if (!m_printer_settings[printer].contains(name))
            return false;
        return true;
    }
References Slic3r::contains(), has_printer_settings(), and m_printer_settings.
Referenced by get_printer_setting(), Slic3r::PresetBundle::load_selections(), and Slic3r::PresetBundle::update_selections().
has_printer_settings()
bool Slic3r::AppConfig::has_printer_settings (std::string printer) const inline
{
        return m_printer_settings.find(printer) != m_printer_settings.end();
    }
References m_printer_settings.
Referenced by has_printer_setting().
has_section()
bool Slic3r::AppConfig::has_section (const std::string & section) const inline
    { return m_storage.find(section) != m_storage.end(); }
References m_storage.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::GuideFrame::apply_config(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::PresetBundle::load_installed_sla_materials(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), and Slic3r::Preset::set_visible_from_appconfig().
is_engineering_region()
bool Slic3r::AppConfig::is_engineering_region ()
{
    std::string sel = get("iot_environment");
    std::string region;
    if (sel == ENV_DEV_HOST
        || sel == ENV_QAT_HOST
        ||sel == ENV_PRE_HOST)
        return true;
    return false;
}
References ENV_DEV_HOST, ENV_PRE_HOST, ENV_QAT_HOST, and get().
legacy_datadir()
bool Slic3r::AppConfig::legacy_datadir () const inline
{ return m_legacy_datadir; }
References m_legacy_datadir.
Referenced by Slic3r::GUI::ConfigWizard::priv::load_vendors().
load()
std::string Slic3r::AppConfig::load ()
{
    json j;
    // 1) Read the complete config file into a boost::property_tree.
    namespace pt = boost::property_tree;
    pt::ptree tree;
    boost::nowide::ifstream ifs;
    bool recovered = false;
    std::string error_message;
    try {
        ifs.open(AppConfig::loading_path());
#ifdef WIN32
        std::stringstream input_stream;
        input_stream << ifs.rdbuf();
        std::string total_string = input_stream.str();
        size_t last_pos = total_string.find_last_of('}');
        std::string left_string = total_string.substr(0, last_pos+1);
        //skip the "\n"
        std::string right_string = total_string.substr(last_pos+2);
        std::string md5_str = appconfig_md5_hash_line({left_string.data()});
        // Verify the checksum of the config file without taking just for debugging purpose.
        if (md5_str != right_string)
            BOOST_LOG_TRIVIAL(info) << "The configuration file " << AppConfig::loading_path() <<
            " has a wrong MD5 checksum or the checksum is missing. This may indicate a file corruption or a harmless user edit.";
        j = json::parse(left_string);
#else
        ifs >> j;
#endif
    }
    catch(nlohmann::detail::parse_error &err) {
#ifdef WIN32
        // The configuration file is corrupted, try replacing it with the backup configuration.
        ifs.close();
        std::string backup_path = (boost::format("%1%.bak") % AppConfig::loading_path()).str();
        if (boost::filesystem::exists(backup_path)) {
            // Compute checksum of the configuration backup file and try to load configuration from it when the checksum is correct.
            boost::nowide::ifstream backup_ifs(backup_path);
            std::stringstream back_input_stream;
            back_input_stream << backup_ifs.rdbuf();
            std::string back_total_string = back_input_stream.str();
            size_t back_last_pos = back_total_string.find_last_of('}');
            std::string back_left_string = back_total_string.substr(0, back_last_pos+1);
            std::string back_right_string = back_total_string.substr(back_last_pos+2);
            std::string back_md5_str = appconfig_md5_hash_line({back_left_string.data()});
            // Verify the checksum of the config file without taking just for debugging purpose.
            if (back_md5_str != back_right_string) {
                BOOST_LOG_TRIVIAL(error) << format("Both \"%1%\" and \"%2%\" are corrupted. It isn't possible to restore configuration from the backup.", AppConfig::loading_path(), backup_path);
                backup_ifs.close();
                boost::filesystem::remove(backup_path);
            }
            else if (std::string error_message; copy_file(backup_path, AppConfig::loading_path(), error_message, false) != SUCCESS) {
                BOOST_LOG_TRIVIAL(error) << format("Configuration file \"%1%\" is corrupted. Failed to restore from backup \"%2%\": %3%", AppConfig::loading_path(), backup_path, error_message);
                backup_ifs.close();
                boost::filesystem::remove(backup_path);
            }
            else {
                BOOST_LOG_TRIVIAL(info) << format("Configuration file \"%1%\" was corrupted. It has been succesfully restored from the backup \"%2%\".", AppConfig::loading_path(), backup_path);
                // Try parse configuration file after restore from backup.
                j = json::parse(back_left_string);
                recovered = true;
            }
        }
        else
#endif // WIN32
            BOOST_LOG_TRIVIAL(info) << format("Failed to parse configuration file \"%1%\": %2%", AppConfig::loading_path(), err.what());
        if (!recovered)
            return err.what();
    }
    try {
        for (auto it = j.begin(); it != j.end(); it++) {
            if (it.key() == MODELS_STR) {
                for (auto& j_model : it.value()) {
                    // This is a vendor section listing enabled model / variants
                    const auto vendor_name = j_model["vendor"].get<std::string>();
                    auto& vendor = m_vendors[vendor_name];
                    const auto model_name = j_model["model"].get<std::string>();
                    std::vector<std::string> variants;
                    if (!unescape_strings_cstyle(j_model["nozzle_diameter"], variants)) { continue; }
                    for (const auto& variant : variants) {
                        vendor[model_name].insert(variant);
                    }
                }
            } else if (it.key() == SECTION_FILAMENTS) {
                json j_filaments = it.value();
                for (auto& element : j_filaments) {
                    m_storage[it.key()][element] = "true";
                }
            } else if (it.key() == "presets") {
                for (auto iter = it.value().begin(); iter != it.value().end(); iter++) {
                    if (iter.key() == "filaments") {
                        int idx = 0;
                        for(auto& element: iter.value()) {
                            if (idx == 0)
                                m_storage[it.key()]["filament"] = element;
                            else {
                                auto n = std::to_string(idx);
                                if (n.length() == 1) n = "0" + n;
                                m_storage[it.key()]["filament_" + n] = element;
                            }
                            idx++;
                        }
                    } else {
                        m_storage[it.key()][iter.key()] = iter.value().get<std::string>();
                    }
                }
            } else if (it.key() == "orca_presets") {
                for (auto& j_model : it.value()) {
                    m_printer_settings[j_model["machine"].get<std::string>()] = j_model;
                }
            }else {
                if (it.value().is_object()) {
                    for (auto iter = it.value().begin(); iter != it.value().end(); iter++) {
                        if (iter.value().is_boolean()) {
                            if (iter.value()) {
                                m_storage[it.key()][iter.key()] = "true";
                            } else {
                                m_storage[it.key()][iter.key()] = "false";
                            }
                        } else if (iter.key() == "filament_presets") {
                            m_filament_presets = iter.value().get<std::vector<std::string>>();
                        } else if (iter.key() == "filament_colors") {
                            m_filament_colors = iter.value().get<std::vector<std::string>>();
                        }
                        else {
                            if (iter.value().is_string())
                                m_storage[it.key()][iter.key()] = iter.value().get<std::string>();
                            else {
                                BOOST_LOG_TRIVIAL(trace) << "load config warning...";
                            }
                        }
                    }
                }
            }
        }
    } catch(std::exception err) {
        BOOST_LOG_TRIVIAL(info) << format("parse app config \"%1%\", error: %2%", AppConfig::loading_path(), err.what());
        return err.what();
    }
    // Figure out if datadir has legacy presets
    auto ini_ver = Semver::parse(get("version"));
    m_legacy_datadir = false;
    if (ini_ver) {
        m_orig_version = *ini_ver;
        ini_ver->set_metadata(boost::none);
        ini_ver->set_prerelease(boost::none);
    }
    // Legacy conversion
    if (m_mode == EAppMode::Editor) {
        // Convert [extras] "physical_printer" to [presets] "physical_printer",
        // remove the [extras] section if it becomes empty.
        if (auto it_section = m_storage.find("extras"); it_section != m_storage.end()) {
            if (auto it_physical_printer = it_section->second.find("physical_printer"); it_physical_printer != it_section->second.end()) {
                m_storage["presets"]["physical_printer"] = it_physical_printer->second;
                it_section->second.erase(it_physical_printer);
            }
            if (it_section->second.empty())
                m_storage.erase(it_section);
        }
    }
    // Override missing or keys with their defaults.
    this->set_defaults();
    m_dirty = false;
    return "";
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), Slic3r::copy_file(), Editor, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, Slic3r::format(), get(), loading_path(), m_dirty, m_filament_colors, m_filament_presets, m_legacy_datadir, m_mode, m_orig_version, m_printer_settings, m_storage, m_vendors, Slic3r::MODELS_STR, n, Slic3r::Semver::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), SECTION_FILAMENTS, set_defaults(), Slic3r::Semver::set_metadata(), Slic3r::SUCCESS, Slic3r::trace(), Slic3r::unescape_strings_cstyle(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value(), and nlohmann::detail::exception::what().
Referenced by Slic3r::GUI::GUI_App::init_app_config().
loading_path()
std::string Slic3r::AppConfig::loading_path () inline
{ return (m_loading_path.empty() ? config_path() : m_loading_path); }
References config_path(), and m_loading_path.
Referenced by load().
orig_version()
Semver Slic3r::AppConfig::orig_version () const inline
{ return m_orig_version; }
References m_orig_version.
Referenced by Slic3r::GUI::GUI_App::check_updates(), and Slic3r::GUI::GUI_App::init_app_config().
reset()
void Slic3r::AppConfig::reset ()
{
    m_storage.clear();
    set_defaults();
};
References m_storage, and set_defaults().
Referenced by AppConfig().
reset_selections()
void Slic3r::AppConfig::reset_selections ()
{
    auto it = m_storage.find("presets");
    if (it != m_storage.end()) {
        it->second.erase(PRESET_PRINT_NAME);
        it->second.erase(PRESET_FILAMENT_NAME);
        it->second.erase("sla_print");
        it->second.erase("sla_material");
        it->second.erase(PRESET_PRINTER_NAME);
        it->second.erase("physical_printer");
        m_dirty = true;
    }
}
References m_dirty, m_storage, PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, and PRESET_PRINTER_NAME.
save()
void Slic3r::AppConfig::save ()
{
    if (! is_main_thread_active())
        throw CriticalException("Calling AppConfig::save() from a worker thread!");
    // The config is first written to a file with a PID suffix and then moved
    // to avoid race conditions with multiple instances of Slic3r
    const auto path = config_path();
    std::string path_pid = (boost::format("%1%.%2%") % path % get_current_pid()).str();
    json j;
    std::stringstream config_ss;
    if (m_mode == EAppMode::Editor)
        j["header"] = Slic3r::header_slic3r_generated();
    else
        j["header"] = Slic3r::header_gcodeviewer_generated();
    // Make sure the "no" category is written first.
    for (const auto& kvp : m_storage["app"]) {
        if (kvp.second == "true") {
            j["app"][kvp.first] = true;
            continue;
        }
        if (kvp.second == "false") {
            j["app"][kvp.first] = false;
            continue;
        }
        j["app"][kvp.first] = kvp.second;
    }
    for (const auto &filament_preset : m_filament_presets) {
        j["app"]["filament_presets"].push_back(filament_preset);
    }
    for (const auto &filament_color : m_filament_colors) {
        j["app"]["filament_colors"].push_back(filament_color);
    }
    // Write the other categories.
    for (const auto& category : m_storage) {
        if (category.first.empty())
            continue;
        if (category.first == SECTION_FILAMENTS) {
            json j_filaments;
            for (const auto& kvp: category.second) {
                j_filaments.push_back(kvp.first);
            }
            j[category.first] = j_filaments;
            continue;
        } else if (category.first == "presets") {
            json j_filament_array;
            for(const auto& kvp : category.second) {
                if (boost::starts_with(kvp.first, "filament") && kvp.first != "filament_colors") {
                    j_filament_array.push_back(kvp.second);
                } else {
                    j[category.first][kvp.first] = kvp.second;
                }
            }
            if(j_filament_array.size() > 0)
                j["presets"]["filaments"] = j_filament_array;
            continue;
        }
        for (const auto& kvp : category.second) {
            if (kvp.second == "true") {
                j[category.first][kvp.first] = true;
                continue;
            }
            if (kvp.second == "false") {
                j[category.first][kvp.first] = false;
                continue;
            }
            j[category.first][kvp.first] = kvp.second;
        }
    }
    // Write vendor sections
    for (const auto& vendor : m_vendors) {
        size_t size_sum = 0;
        for (const auto& model : vendor.second) { size_sum += model.second.size(); }
        if (size_sum == 0) { continue; }
        for (const auto& model : vendor.second) {
            if (model.second.empty()) { continue; }
            const std::vector<std::string> variants(model.second.begin(), model.second.end());
            const auto escaped = escape_strings_cstyle(variants);
            //j[VENDOR_PREFIX + vendor.first][MODEL_PREFIX + model.first] = escaped;
            json j_model;
            j_model["vendor"] = vendor.first;
            j_model["model"] = model.first;
            j_model["nozzle_diameter"] = escaped;
            j[MODELS_STR].push_back(j_model);
        }
    }
    // write machine settings
    for (const auto& preset : m_printer_settings) {
        j["orca_presets"].push_back(preset.second);
    }
    boost::nowide::ofstream c;
    c.open(path_pid, std::ios::out | std::ios::trunc);
    c << std::setw(4) << j << std::endl;
#ifdef WIN32
    // WIN32 specific: The final "rename_file()" call is not safe in case of an application crash, there is no atomic "rename file" API
    // provided by Windows (sic!). Therefore we save a MD5 checksum to be able to verify file corruption. In addition,
    // we save the config file into a backup first before moving it to the final destination.
    c << appconfig_md5_hash_line({j.dump(4)});
#endif
    c.close();
#ifdef WIN32
    // Make a backup of the configuration file before copying it to the final destination.
    std::string error_message;
    std::string backup_path = (boost::format("%1%.bak") % path).str();
    // Copy configuration file with PID suffix into the configuration file with "bak" suffix.
    if (copy_file(path_pid, backup_path, error_message, false) != SUCCESS)
        BOOST_LOG_TRIVIAL(error) << "Copying from " << path_pid << " to " << backup_path << " failed. Failed to create a backup configuration.";
#endif
    // Rename the config atomically.
    // On Windows, the rename is likely NOT atomic, thus it may fail if PrusaSlicer crashes on another thread in the meanwhile.
    // To cope with that, we already made a backup of the config on Windows.
    rename_file(path_pid, path);
    m_dirty = false;
}
References config_path(), Slic3r::copy_file(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), Editor, error, Slic3r::escape_strings_cstyle(), Slic3r::get_current_pid(), Slic3r::header_gcodeviewer_generated(), Slic3r::header_slic3r_generated(), Slic3r::is_main_thread_active(), m_dirty, m_filament_colors, m_filament_presets, m_mode, m_printer_settings, m_storage, m_vendors, Slic3r::MODELS_STR, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::push_back(), Slic3r::rename_file(), SECTION_FILAMENTS, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::size(), and Slic3r::SUCCESS.
Referenced by Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_backup_input(), Slic3r::GUI::PreferencesDialog::create_item_checkbox(), Slic3r::GUI::PreferencesDialog::create_item_darkmode_checkbox(), Slic3r::GUI::PreferencesDialog::create_item_input(), Slic3r::GUI::GuideFrame::SaveProfile(), update_last_backup_dir(), and Slic3r::GUI::GUI_App::window_pos_save().
set() [1/3]
void Slic3r::AppConfig::set (const std::string & key, const std::string & value) inline
    { this->set("app", key, value);  }
References set().
set() [2/3]
void Slic3r::AppConfig::set (const std::string & section, const std::string & key, bool value) inline
  {
    if (value){
      set(section, key, std::string("true"));
    } else {
      set(section, key, std::string("false"));
    }
  }
References set().
set() [3/3]
void Slic3r::AppConfig::set (const std::string & section, const std::string & key, const std::string & value) inline
  {
#ifndef NDEBUG
    {
      std::string key_trimmed = key;
      boost::trim_all(key_trimmed);
      assert(key_trimmed == key);
      assert(! key_trimmed.empty());
    }
#endif // NDEBUG
    std::string &old = m_storage[section][key];
    if (old != value) {
      old = value;
      m_dirty = true;
    }
  }
References m_dirty, and m_storage.
Referenced by Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::GUI_App::copy_network_if_available(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_backup_input(), Slic3r::GUI::PreferencesDialog::create_item_combobox(), Slic3r::GUI::PreferencesDialog::create_item_darkmode_checkbox(), Slic3r::GUI::PreferencesDialog::create_item_downloads(), Slic3r::GUI::PreferencesDialog::create_item_input(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_loglevel_combobox(), Slic3r::GUI::PreferencesDialog::create_item_multiple_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::GUI_App::enable_user_preset_folder(), Slic3r::GUI::PrintHostSendDialog::EndModal(), Slic3r::PresetBundle::export_selections(), Slic3r::GUI::Config::Snapshot::export_selections(), Slic3r::GUI::GUI_App::init_app_config(), Slic3r::GUI::GUI_App::init_download_path(), Slic3r::GUI::Config::SnapshotDB::is_on_snapshot(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::PresetBundle::load_installed_sla_materials(), Slic3r::GUI::GUI_App::load_language(), Slic3r::GUI::GUI_App::on_init_inner(), Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::GUI::GUI_App::save_mode(), Slic3r::GUI::GuideFrame::SaveProfile(), Slic3r::GUI::GUI_App::select_language(), set(), set(), Slic3r::GUI::GUI_App::set_auto_toolbar_icon_scale(), set_bool(), set_defaults(), Slic3r::GUI::GUI_App::set_skip_version(), Slic3r::GUI::GUI_App::show_check_privacy_dlg(), Slic3r::GUI::Plater::priv::undo_redo_to(), update_config_dir(), update_last_backup_dir(), update_last_output_dir(), Slic3r::GUI::PageMaterials::update_lists(), update_skein_dir(), and Slic3r::GUI::GUI_App::window_pos_save().
set_bool()
void Slic3r::AppConfig::set_bool (const std::string & key, const bool & value) inline
    {
      this->set("app", key, value);
    }
References set().
Referenced by Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_checkbox(), set_defaults(), and Slic3r::GUI::GUI_App::show_check_privacy_dlg().
set_defaults()
void Slic3r::AppConfig::set_defaults ()
{
    if (m_mode == EAppMode::Editor) {
#ifdef SUPPORT_AUTO_CENTER
        // Reset the empty fields to defaults.
        if (get("autocenter").empty())
            set_bool("autocenter", true);
#endif
#ifdef SUPPORT_BACKGROUND_PROCESSING
        // Disable background processing by default as it is not stable.
        if (get("background_processing").empty())
            set_bool("background_processing", false);
#endif
#ifdef SUPPORT_SHOW_DROP_PROJECT
        if (get("show_drop_project_dialog").empty())
            set_bool("show_drop_project_dialog", true);
#endif
        if (get("drop_project_action").empty())
            set_bool("drop_project_action", true);
#ifdef _WIN32
        if (get("associate_3mf").empty())
            set_bool("associate_3mf", false);
        if (get("associate_stl").empty())
            set_bool("associate_stl", false);
        if (get("associate_step").empty())
            set_bool("associate_step", false);
#endif // _WIN32
        // remove old 'use_legacy_opengl' parameter from this config, if present
        if (!get("use_legacy_opengl").empty())
            erase("app", "use_legacy_opengl");
#ifdef __APPLE__
        if (get("use_retina_opengl").empty())
            set_bool("use_retina_opengl", true);
#endif
        if (get("single_instance").empty())
            set_bool("single_instance", false);
#ifdef SUPPORT_REMEMBER_OUTPUT_PATH
        if (get("remember_output_path").empty())
            set_bool("remember_output_path", true);
        if (get("remember_output_path_removable").empty())
            set_bool("remember_output_path_removable", true);
#endif
        if (get("toolkit_size").empty())
            set("toolkit_size", "100");
#if ENABLE_ENVIRONMENT_MAP
        if (get("use_environment_map").empty())
            set("use_environment_map", false);
#endif // ENABLE_ENVIRONMENT_MAP
        if (get("use_inches").empty())
            set("use_inches", "0");
    }
    else {
#ifdef _WIN32
        if (get("associate_gcode").empty())
            set_bool("associate_gcode", false);
#endif // _WIN32
    }
    if (get("use_perspective_camera").empty())
        set_bool("use_perspective_camera", true);
#ifdef SUPPORT_FREE_CAMERA
    if (get("use_free_camera").empty())
        set_bool("use_free_camera", false);
#endif
#ifdef SUPPORT_REVERSE_MOUSE_ZOOM
    if (get("reverse_mouse_wheel_zoom").empty())
        set_bool("reverse_mouse_wheel_zoom", false);
#endif
    if (get("zoom_to_mouse").empty())
        set_bool("zoom_to_mouse", false);
//#ifdef SUPPORT_SHOW_HINTS
    if (get("show_hints").empty())
        set_bool("show_hints", true);
//#endif
    if (get("show_gcode_window").empty())
        set_bool("show_gcode_window", true);
#ifdef _WIN32
//#ifdef SUPPORT_3D_CONNEXION
    if (get("use_legacy_3DConnexion").empty())
        set_bool("use_legacy_3DConnexion", true);
//#endif
#ifdef SUPPORT_DARK_MODE
    if (get("dark_color_mode").empty())
        set("dark_color_mode", "0");
#endif
//#ifdef SUPPORT_SYS_MENU
    if (get("sys_menu_enabled").empty())
        set("sys_menu_enabled", "1");
//#endif
#endif // _WIN32
    // BBS
    /*if (get("3mf_include_gcode").empty())
        set_bool("3mf_include_gcode", true);*/
    if (get("developer_mode").empty())
        set_bool("developer_mode", false);
    if (get("enable_ssl_for_mqtt").empty())
        set_bool("enable_ssl_for_mqtt", true);
    if (get("enable_ssl_for_ftp").empty())
        set_bool("enable_ssl_for_ftp", true);
    if (get("severity_level").empty())
        set("severity_level", "info");
    if (get("internal_developer_mode").empty())
        set_bool("internal_developer_mode", false);
    // BBS
    if (get("preset_folder").empty())
        set("preset_folder", "");
    // BBS
    if (get("slicer_uuid").empty()) {
        boost::uuids::uuid uuid = boost::uuids::random_generator()();
        set("slicer_uuid", to_string(uuid));
    }
    if (get("show_model_mesh").empty()) {
        set_bool("show_model_mesh", false);
    }
    if (get("show_model_shadow").empty()) {
        set_bool("show_model_shadow", true);
    }
    if (get("show_build_edges").empty()) {
        set_bool("show_build_edgets", false);
    }
    if (get("show_daily_tips").empty()) {
        set_bool("show_daily_tips", true);
    }
    if (get("show_home_page").empty()) {
        set_bool("show_home_page", true);
    }
    if (get("show_printable_box").empty()) {
        set_bool("show_printable_box", true);
    }
    if (get("units").empty()) {
         set("units", "0");
    }
    if (get("sync_user_preset").empty()) {
        set_bool("sync_user_preset", false);
    }
    if (get("keyboard_supported").empty()) {
        set("keyboard_supported", std::string("none/alt/control/shift"));
    }
    if (get("mouse_supported").empty()) {
        set("mouse_supported", "mouse left/mouse middle/mouse right");
    }
    if (get("privacy_version").empty()) {
        set("privacy_version", "00.00.00.00");
    }
    if (get("rotate_view").empty()) {
        set("rotate_view", "none/mouse left");
    }
    if (get("move_view").empty()) {
        set("move_view", "none/mouse left");
    }
    if (get("zoom_view").empty()) {
        set("zoom_view", "none/mouse left");
    }
    if (get("precise_control").empty()) {
        set("precise_control", "none/mouse left");
    }
    if (get("download_path").empty()) {
        set("download_path", "");
    }
    if (get("mouse_wheel").empty()) {
        set("mouse_wheel", "0");
    }
    if (get("max_recent_count").empty()) {
        set("max_recent_count", "18");
    }
    if (get("sync_system_preset").empty()) {
        set_bool("sync_system_preset", true);
    }
    if (get("backup_switch").empty() || get("version") < "01.06.00.00") {
        set_bool("backup_switch", true);
    }
    if (get("backup_interval").empty()) {
        set("backup_interval", "10");
    }
    if (get("curr_bed_type").empty()) {
        set("curr_bed_type", "1");
    }
// #if BBL_RELEASE_TO_PUBLIC
    if (get("iot_environment").empty()) {
        set("iot_environment", "3");
    }
// #else
//     if (get("iot_environment").empty()) {
//         set("iot_environment", "1");
//     }
// #endif
    if (get("presets", "filament_colors").empty()) {
        set_str("presets", "filament_colors", "#F2754E");
    }
    if (get("print", "bed_leveling").empty()) {
        set_str("print", "bed_leveling", "1");
    }
    if (get("print", "flow_cali").empty()) {
        set_str("print", "flow_cali", "1");
    }
    if (get("print", "timelapse").empty()) {
        set_str("print", "timelapse", "1");
    }
    // Remove legacy window positions/sizes
    erase("app", "main_frame_maximized");
    erase("app", "main_frame_pos");
    erase("app", "main_frame_size");
    erase("app", "object_settings_maximized");
    erase("app", "object_settings_pos");
    erase("app", "object_settings_size");
}
References Editor, Slic3r::empty(), erase(), get(), m_mode, set(), set_bool(), set_str(), and Slic3r::to_string().
Referenced by load(), and reset().
set_dirty()
void Slic3r::AppConfig::set_dirty () inline
{ m_dirty = true; }
References m_dirty.
set_filament_colors()
void Slic3r::AppConfig::set_filament_colors (const std::vector< std::string > & filament_colors) inline
{
        m_filament_colors = filament_colors;
        m_dirty                = true;
    }
References m_dirty, and m_filament_colors.
set_filament_presets()
void Slic3r::AppConfig::set_filament_presets (const std::vector< std::string > & filament_presets) inline
{
        m_filament_presets = filament_presets;
        m_dirty            = true;
    }
References m_dirty, and m_filament_presets.
set_legacy_datadir()
void Slic3r::AppConfig::set_legacy_datadir (bool value) inline
{ m_legacy_datadir = value; }
References m_legacy_datadir.
Referenced by Slic3r::GUI::GuideFrame::run(), and Slic3r::GUI::ConfigWizard::run().
set_loading_path()
void Slic3r::AppConfig::set_loading_path (const std::string & path) inline
{ m_loading_path = path; }
References m_loading_path.
set_mouse_device()
void Slic3r::AppConfig::set_mouse_device (const std::string & name, double translation_speed, double translation_deadzone, float rotation_speed, float rotation_deadzone, double zoom_speed, bool swap_yz)
{
    std::string key = std::string("mouse_device:") + name;
    auto it = m_storage.find(key);
    if (it == m_storage.end())
        it = m_storage.insert(std::map<std::string, std::map<std::string, std::string>>::value_type(key, std::map<std::string, std::string>())).first;
    it->second.clear();
    it->second["translation_speed"] = float_to_string_decimal_point(translation_speed);
    it->second["translation_deadzone"] = float_to_string_decimal_point(translation_deadzone);
    it->second["rotation_speed"] = float_to_string_decimal_point(rotation_speed);
    it->second["rotation_deadzone"] = float_to_string_decimal_point(rotation_deadzone);
    it->second["zoom_speed"] = float_to_string_decimal_point(zoom_speed);
    it->second["swap_yz"] = swap_yz ? "1" : "0";
}
References Slic3r::float_to_string_decimal_point(), and m_storage.
Referenced by Slic3r::GUI::Mouse3DController::save_config().
set_printer_setting()
std::string Slic3r::AppConfig::set_printer_setting (std::string printer, std::string name, std::string value) inline
{
        return m_printer_settings[printer][name] = value;
        m_dirty                = true;
    }
References m_dirty, and m_printer_settings.
Referenced by Slic3r::PresetBundle::export_selections(), and Slic3r::GUI::Plater::priv::on_select_bed_type().
set_recent_projects()
void Slic3r::AppConfig::set_recent_projects (const std::vector< std::string > & recent_projects)
{
    auto it = m_storage.find("recent_projects");
    if (it == m_storage.end())
        it = m_storage.insert(std::map<std::string, std::map<std::string, std::string>>::value_type("recent_projects", std::map<std::string, std::string>())).first;
    it->second.clear();
    for (unsigned int i = 0; i < (unsigned int)recent_projects.size(); ++i)
    {
        auto n = std::to_string(i + 1);
        if (n.length() == 1) n = "0" + n;
        it->second[n] = recent_projects[i];
    }
}
References int, m_storage, and n.
set_section()
void Slic3r::AppConfig::set_section (const std::string & section, const std::map< std::string, std::string > & data) inline
    { m_storage[section] = data; }
References m_storage.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::GuideFrame::apply_config(), Slic3r::GUI::GuideFrame::LoadProfile(), and Slic3r::GUI::GuideFrame::SaveProfile().
set_str()
void Slic3r::AppConfig::set_str (const std::string & section, const std::string & key, const std::string & value) inline
  {
#ifndef NDEBUG
    {
      std::string key_trimmed = key;
      boost::trim_all(key_trimmed);
      assert(key_trimmed == key);
      assert(!key_trimmed.empty());
    }
#endif // NDEBUG
    std::string& old = m_storage[section][key];
    if (old != value) {
      old = value;
      m_dirty = true;
    }
  }
References m_dirty, and m_storage.
Referenced by Slic3r::GUI::SelectMachineDialog::create_item_checkbox(), Slic3r::GUI::GUI_App::install_plugin(), Slic3r::MachineObject::set_access_code(), set_defaults(), and Slic3r::MachineObject::set_user_access_code().
set_variant()
void Slic3r::AppConfig::set_variant (const std::string & vendor, const std::string & model, const std::string & variant, bool enable)
{
    if (enable) {
        if (get_variant(vendor, model, variant)) { return; }
        m_vendors[vendor][model].insert(variant);
    } else {
        auto it_v = m_vendors.find(vendor);
        if (it_v == m_vendors.end()) { return; }
        auto it_m = it_v->second.find(model);
        if (it_m == it_v->second.end()) { return; }
        auto it_var = it_m->second.find(variant);
        if (it_var == it_m->second.end()) { return; }
        it_m->second.erase(it_var);
    }
    // If we got here, there was an update
    m_dirty = true;
}
References get_variant(), m_dirty, and m_vendors.
Referenced by Slic3r::GUI::PagePrinters::PagePrinters(), Slic3r::GUI::GuideFrame::run(), and Slic3r::GUI::GuideFrame::SaveProfile().
set_vendors() [1/3]
void Slic3r::AppConfig::set_vendors (const AppConfig & from)
{
    m_vendors = from.m_vendors;
    m_dirty = true;
}
References m_dirty, and m_vendors.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::GuideFrame::apply_config(), Slic3r::GUI::Config::Snapshot::export_vendor_configs(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), Slic3r::GUI::GuideFrame::LoadProfile(), and Slic3r::GUI::GuideFrame::SaveProfile().
set_vendors() [2/3]
void Slic3r::AppConfig::set_vendors (const VendorMap & vendors) inline
{ m_vendors = vendors; m_dirty = true; }
References m_dirty, m_vendors, and vendors().
set_vendors() [3/3]
void Slic3r::AppConfig::set_vendors (VendorMap && vendors) inline
{ m_vendors = std::move(vendors); m_dirty = true; }
References m_dirty, m_vendors, and vendors().
update_config_dir()
void Slic3r::AppConfig::update_config_dir (const std::string & dir)
{
    this->set("recent", "settings_folder", dir);
}
References set().
update_last_backup_dir()
void Slic3r::AppConfig::update_last_backup_dir (const std::string & dir)
{
  this->set("app", "last_backup_path", dir);
    this->save();
}
References save(), and set().
update_last_output_dir()
void Slic3r::AppConfig::update_last_output_dir (const std::string & dir, const bool removable = false)
{
  this->set("app", ("last_export_path"), dir);
}
References set().
Referenced by Slic3r::GUI::Plater::export_gcode(), and Slic3r::GUI::Plater::export_gcode_3mf().
update_skein_dir()
void Slic3r::AppConfig::update_skein_dir (const std::string & dir)
{
    if (is_shapes_dir(dir))
        return; // do not save "shapes gallery" directory
    this->set("recent", "last_opened_folder", dir);
}
References Slic3r::is_shapes_dir(), and set().
vendors()
const VendorMap & Slic3r::AppConfig::vendors () const inline
{ return m_vendors; }
References m_vendors.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::GuideFrame::apply_config(), Slic3r::PresetUpdater::priv::check_installed_vendor_profiles(), Slic3r::GUI::Config::Snapshot::equal_to_active(), set_vendors(), set_vendors(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
version_check_url()
std::string Slic3r::AppConfig::version_check_url () const
{
    auto from_settings = get("version_check_url");
    return from_settings.empty() ? VERSION_CHECK_URL : from_settings;
}
References get(), and Slic3r::VERSION_CHECK_URL.
Referenced by Slic3r::GUI::GUI_App::check_new_version_sf(), and Slic3r::PresetUpdater::priv::set_download_prefs().
Member Data Documentation
m_dirty
bool Slic3r::AppConfig::m_dirty private
Referenced by clear_printer_settings(), dirty(), load(), reset_selections(), save(), set(), set_dirty(), set_filament_colors(), set_filament_presets(), set_printer_setting(), set_str(), set_variant(), set_vendors(), set_vendors(), and set_vendors().
m_filament_colors
std::vector<std::string> Slic3r::AppConfig::m_filament_colors private
Referenced by get_filament_colors(), load(), save(), and set_filament_colors().
m_filament_presets
std::vector<std::string> Slic3r::AppConfig::m_filament_presets private
Referenced by get_filament_presets(), load(), save(), and set_filament_presets().
m_legacy_datadir
bool Slic3r::AppConfig::m_legacy_datadir private
Referenced by legacy_datadir(), load(), and set_legacy_datadir().
m_loading_path
std::string Slic3r::AppConfig::m_loading_path private
Referenced by loading_path(), and set_loading_path().
m_mode
EAppMode Slic3r::AppConfig::m_mode { EAppMode::Editor } private
Referenced by config_path(), load(), save(), and set_defaults().
m_orig_version
Semver Slic3r::AppConfig::m_orig_version private
Referenced by load(), and orig_version().
m_printer_settings
MachineSettingMap Slic3r::AppConfig::m_printer_settings private
Referenced by clear_printer_settings(), get_printer_setting(), has_printer_setting(), has_printer_settings(), load(), save(), and set_printer_setting().
m_storage
std::map<std::string, std::map<std::string, std::string> > Slic3r::AppConfig::m_storage private
Referenced by clear_section(), erase(), get(), get_3dmouse_device_numeric_value(), get_last_backup_dir(), get_last_dir(), get_last_output_dir(), get_mouse_device_names(), get_recent_projects(), get_section(), has(), has_section(), load(), reset(), reset_selections(), save(), set(), set_mouse_device(), set_recent_projects(), set_section(), and set_str().
m_vendors
VendorMap Slic3r::AppConfig::m_vendors private
Referenced by get_variant(), load(), save(), set_variant(), set_vendors(), set_vendors(), set_vendors(), and vendors().
SECTION_FILAMENTS
const std::string Slic3r::AppConfig::SECTION_FILAMENTS = "filaments" static
Referenced by Slic3r::GUI::Materials::appconfig_section(), Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::GuideFrame::apply_config(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), load(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), Slic3r::GUI::GuideFrame::LoadProfile(), Slic3r::GUI::GuideFrame::run(), save(), Slic3r::GUI::GuideFrame::SaveProfile(), Slic3r::Preset::set_visible_from_appconfig(), and Slic3r::GUI::ConfigWizard::priv::update_presets_in_config().
SECTION_MATERIALS
const std::string Slic3r::AppConfig::SECTION_MATERIALS = "sla_materials" static
Referenced by Slic3r::GUI::Materials::appconfig_section(), Slic3r::PresetBundle::load_installed_sla_materials(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), and Slic3r::Preset::set_visible_from_appconfig().
The documentation for this class was generated from the following files:
src/libslic3r/AppConfig.hpp
src/libslic3r/AppConfig.cpp