OrcaSlicer: Slic3r::CalibPressureAdvanceLine Class Reference
Slic3r::CalibPressureAdvanceLine Class Reference
#include <src/libslic3r/calib.hpp>
Public Member Functions
CalibPressureAdvanceLine (GCode *gcodegen)
~CalibPressureAdvanceLine ()
std::string generate_test (double start_pa=0, double step_pa=0.002, int count=50)
void set_speed (double fast=100.0, double slow=20.0)
const double & line_width ()
bool is_delta () const
bool & draw_numbers ()
Static Public Member Functions
static float find_optimal_PA_speed (const DynamicPrintConfig &config, double line_width, double layer_height, int filament_idx=0)
Protected Types
enum class DrawDigitMode { Left_To_Right , Bottom_To_Top }
Protected Member Functions
void delta_scale_bed_ext (BoundingBoxf &bed_ext) const
std::string move_to (Vec2d pt, GCodeWriter &writer, std::string comment=std::string())
double e_per_mm (double line_width, double layer_height, float nozzle_diameter, float filament_diameter, float print_flow_ratio) const
double speed_adjust (int speed) const
std::string convert_number_to_string (double num) const
double number_spacing () const
std::string draw_digit (double startx, double starty, char c, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, GCodeWriter &writer)
std::string draw_number (double startx, double starty, double value, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, double speed, GCodeWriter &writer)
Protected Attributes
Vec3d m_last_pos
DrawDigitMode m_draw_digit_mode {DrawDigitMode::Left_To_Right}
const double m_digit_segment_len {2}
const double m_digit_gap_len {1}
const std::string::size_type m_max_number_len {5}
Private Member Functions
std::string print_pa_lines (double start_x, double start_y, double start_pa, double step_pa, int num)
void delta_modify_start (double &startx, double &starty, int count)
Private Attributes
GCode * mp_gcodegen
double m_nozzle_diameter
double m_slow_speed
double m_fast_speed
const double m_height_layer {0.2}
const double m_line_width {0.6}
const double m_thin_line_width {0.44}
const double m_number_line_width {0.48}
const double m_space_y {3.5}
double m_length_short {20.0}
double m_length_long {40.0}
bool m_draw_numbers {true}
Detailed Description
Member Enumeration Documentation
DrawDigitMode
enum class Slic3r::CalibPressureAdvance::DrawDigitMode strong protected inherited
Enumerator
Left_To_Right
Bottom_To_Top
{
        Left_To_Right,
        Bottom_To_Top
    };
Constructor & Destructor Documentation
CalibPressureAdvanceLine()
Slic3r::CalibPressureAdvanceLine::CalibPressureAdvanceLine (GCode * gcodegen) inline
                                              :
        mp_gcodegen(gcodegen),
        m_nozzle_diameter(gcodegen->config().nozzle_diameter.get_at(0))
    { };
~CalibPressureAdvanceLine()
Slic3r::CalibPressureAdvanceLine::~CalibPressureAdvanceLine () inline
{ };
Member Function Documentation
convert_number_to_string()
std::string Slic3r::CalibPressureAdvance::convert_number_to_string (double num) const protected inherited
{
    auto sNumber = std::to_string(num);
    sNumber.erase(sNumber.find_last_not_of('0') + 1, std::string::npos);
    sNumber.erase(sNumber.find_last_not_of('.') + 1, std::string::npos);
    return sNumber;
}
Referenced by Slic3r::CalibPressureAdvance::draw_number(), and Slic3r::CalibPressureAdvancePattern::max_numbering_height().
delta_modify_start()
void Slic3r::CalibPressureAdvanceLine::delta_modify_start (double & startx, double & starty, int count) private
{
    startx = -startx;
    starty = -(count * m_space_y) / 2;
}
References count, and m_space_y.
Referenced by generate_test().
delta_scale_bed_ext()
void Slic3r::CalibPressureAdvance::delta_scale_bed_ext (BoundingBoxf & bed_ext) const inline protected inherited
{ bed_ext.scale(1.0f / 1.41421f); }
References Slic3r::BoundingBoxBase< PointClass >::scale().
Referenced by generate_test().
draw_digit()
std::string Slic3r::CalibPressureAdvance::draw_digit (double startx, double starty, char c, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, GCodeWriter & writer) protected inherited
{
    const double len = m_digit_segment_len;
    const double gap = line_width / 2.0;
    const auto dE = e_per_mm * len;
    const auto two_dE = dE * 2;
    Vec2d p0, p1, p2, p3, p4, p5;
    Vec2d p0_5, p4_5;
    Vec2d gap_p0_toward_p3, gap_p2_toward_p3;
    Vec2d dot_direction;
    if (mode == CalibPressureAdvance::DrawDigitMode::Bottom_To_Top) {
        //  1-------2-------5
        //  |       |       |
        //  |       |       |
        //  0-------3-------4
        p0 = Vec2d(startx, starty);
        p0_5 = Vec2d(startx, starty + len / 2);
        p1 = Vec2d(startx, starty + len);
        p2 = Vec2d(startx + len, starty + len);
        p3 = Vec2d(startx + len, starty);
        p4 = Vec2d(startx + len * 2, starty);
        p4_5 = Vec2d(startx + len * 2, starty + len / 2);
        p5 = Vec2d(startx + len * 2, starty + len);
        gap_p0_toward_p3 = p0 + Vec2d(gap, 0);
        gap_p2_toward_p3 = p2 + Vec2d(0, gap);
        dot_direction = Vec2d(-len / 2, 0);
    } else {
        //  0-------1
        //  |       |
        //  3-------2
        //  |       |
        //  4-------5
        p0 = Vec2d(startx, starty);
        p0_5 = Vec2d(startx + len / 2, starty);
        p1 = Vec2d(startx + len, starty);
        p2 = Vec2d(startx + len, starty - len);
        p3 = Vec2d(startx, starty - len);
        p4 = Vec2d(startx, starty - len * 2);
        p4_5 = Vec2d(startx + len / 2, starty - len * 2);
        p5 = Vec2d(startx + len, starty - len * 2);
        gap_p0_toward_p3 = p0 - Vec2d(0, gap);
        gap_p2_toward_p3 = p2 - Vec2d(gap, 0);
        dot_direction = Vec2d(0, len / 2);
    }
    std::stringstream gcode;
    switch (c) {
    case '0':
        gcode << move_to(p0, writer, "Glyph: 0");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(gap_p0_toward_p3, two_dE);
        break;
    case '1':
        gcode << move_to(p0_5, writer, "Glyph: 1");
        gcode << writer.extrude_to_xy(p4_5, two_dE);
        break;
    case '2':
        gcode << move_to(p0, writer, "Glyph: 2");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        break;
    case '3':
        gcode << move_to(p0, writer, "Glyph: 3");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << move_to(gap_p2_toward_p3, writer);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '4':
        gcode << move_to(p0, writer, "Glyph: 4");
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << move_to(p1, writer);
        gcode << writer.extrude_to_xy(p5, two_dE);
        break;
    case '5':
        gcode << move_to(p1, writer, "Glyph: 5");
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        break;
    case '6':
        gcode << move_to(p1, writer, "Glyph: 6");
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p4, two_dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '7':
        gcode << move_to(p0, writer, "Glyph: 7");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        break;
    case '8':
        gcode << move_to(p2, writer, "Glyph: 8");
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p1, two_dE);
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '9':
        gcode << move_to(p5, writer, "Glyph: 9");
        gcode << writer.extrude_to_xy(p1, two_dE);
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        break;
    case '.':
        gcode << move_to(p4_5, writer, "Glyph: .");
        gcode << writer.extrude_to_xy(p4_5 + dot_direction, dE);
        break;
    default:
        break;
    }
    return gcode.str();
}
References Slic3r::CalibPressureAdvance::Bottom_To_Top, Slic3r::CalibPressureAdvance::e_per_mm(), Slic3r::GCodeWriter::extrude_to_xy(), Slic3r::CalibPressureAdvance::m_digit_segment_len, and Slic3r::CalibPressureAdvance::move_to().
Referenced by Slic3r::CalibPressureAdvance::draw_number().
draw_number()
std::string Slic3r::CalibPressureAdvance::draw_number (double startx, double starty, double value, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, double speed, GCodeWriter & writer) protected inherited
{
    auto sNumber = convert_number_to_string(value);
    std::stringstream gcode;
    gcode << writer.set_speed(speed);
    for (std::string::size_type i = 0; i < sNumber.length(); ++i) {
        if (i > m_max_number_len) {
            break;
        }
        switch (mode) {
            case DrawDigitMode::Bottom_To_Top:
                gcode << draw_digit(
                    startx,
                    starty + i * number_spacing(),
                    sNumber[i],
                    mode,
                    line_width,
                    e_per_mm,
                    writer
                );
                break;
            default:
                gcode << draw_digit(
                    startx + i * number_spacing(),
                    starty,
                    sNumber[i],
                    mode,
                    line_width,
                    e_per_mm,
                    writer
                );
        }
    }
    return gcode.str();
}
References Slic3r::CalibPressureAdvance::Bottom_To_Top, Slic3r::CalibPressureAdvance::convert_number_to_string(), Slic3r::CalibPressureAdvance::draw_digit(), Slic3r::CalibPressureAdvance::e_per_mm(), Slic3r::CalibPressureAdvance::m_max_number_len, Slic3r::CalibPressureAdvance::number_spacing(), and Slic3r::GCodeWriter::set_speed().
Referenced by Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and print_pa_lines().
draw_numbers()
bool & Slic3r::CalibPressureAdvanceLine::draw_numbers () inline
{ return m_draw_numbers; }
References m_draw_numbers.
Referenced by Slic3r::GCode::_do_export().
e_per_mm()
double Slic3r::CalibPressureAdvance::e_per_mm (double line_width, double layer_height, float nozzle_diameter, float filament_diameter, float print_flow_ratio) const protected inherited
{
    const Flow line_flow = Flow(line_width, layer_height, nozzle_diameter);
    const double filament_area = M_PI * std::pow(filament_diameter / 2, 2);
    return line_flow.mm3_per_mm() / filament_area * print_flow_ratio;
}
References Slic3r::layer_height(), M_PI, and Slic3r::Flow::mm3_per_mm().
Referenced by Slic3r::CalibPressureAdvance::draw_digit(), Slic3r::CalibPressureAdvancePattern::draw_line(), Slic3r::CalibPressureAdvance::draw_number(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and print_pa_lines().
find_optimal_PA_speed()
float Slic3r::CalibPressureAdvance::find_optimal_PA_speed (const DynamicPrintConfig & config, double line_width, double layer_height, int filament_idx = 0) static inherited
{
    const double general_suggested_min_speed = 100.0;
    double filament_max_volumetric_speed = config.option<ConfigOptionFloats>("filament_max_volumetric_speed")->get_at(0);
    Flow pattern_line = Flow(line_width, layer_height, config.option<ConfigOptionFloats>("nozzle_diameter")->get_at(0));
    auto pa_speed = std::min(std::max(general_suggested_min_speed,config.option<ConfigOptionFloat>("outer_wall_speed")->value), filament_max_volumetric_speed / pattern_line.mm3_per_mm());
    return std::floor(pa_speed);
}
References Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::layer_height(), Slic3r::Flow::mm3_per_mm(), Slic3r::ConfigBase::option(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::Plater::_calib_pa_tower(), and Slic3r::GCode::_do_export().
generate_test()
std::string Slic3r::CalibPressureAdvanceLine::generate_test (double start_pa = 0, double step_pa = 0.002, int count = 50)
{
    BoundingBoxf bed_ext = get_extents(mp_gcodegen->config().printable_area.values);
    if (is_delta()) {
        CalibPressureAdvanceLine::delta_scale_bed_ext(bed_ext);
    }
    auto bed_sizes = mp_gcodegen->config().printable_area.values;
    const auto &w = bed_ext.size().x();
    const auto &h = bed_ext.size().y();
    count = std::min(count, int((h - 10) / m_space_y));
    m_length_long = 40 + std::min(w - 120.0, 0.0);
    auto startx = (w - m_length_short * 2 - m_length_long - 20) / 2;
    auto starty = (h - count * m_space_y) / 2;
    if (is_delta()) {
        CalibPressureAdvanceLine::delta_modify_start(startx, starty, count);
    }
    return print_pa_lines(startx, starty, start_pa, step_pa, count);
}
References Slic3r::GCode::config(), count, delta_modify_start(), Slic3r::CalibPressureAdvance::delta_scale_bed_ext(), Slic3r::get_extents(), is_delta(), m_length_long, m_length_short, m_space_y, mp_gcodegen, print_pa_lines(), and Slic3r::BoundingBoxBase< PointClass >::size().
Referenced by Slic3r::GCode::_do_export().
is_delta()
bool Slic3r::CalibPressureAdvanceLine::is_delta () const
{
    return mp_gcodegen->config().printable_area.values.size() > 4;
}
References Slic3r::GCode::config(), and mp_gcodegen.
Referenced by generate_test().
line_width()
const double & Slic3r::CalibPressureAdvanceLine::line_width () inline
{ return m_line_width; };
References m_line_width.
Referenced by Slic3r::GCode::_do_export().
move_to()
std::string Slic3r::CalibPressureAdvance::move_to (Vec2d pt, GCodeWriter & writer, std::string comment = std::string()) protected inherited
{
    std::stringstream gcode;
    gcode << writer.retract();
    gcode << writer.travel_to_xy(pt, comment);
    gcode << writer.unretract();
    m_last_pos = Vec3d(pt.x(), pt.y(), 0);
    return gcode.str();
}
References Slic3r::CalibPressureAdvance::m_last_pos, Slic3r::GCodeWriter::retract(), Slic3r::GCodeWriter::travel_to_xy(), and Slic3r::GCodeWriter::unretract().
Referenced by Slic3r::CalibPressureAdvancePattern::draw_box(), Slic3r::CalibPressureAdvance::draw_digit(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and print_pa_lines().
number_spacing()
double Slic3r::CalibPressureAdvance::number_spacing () const inline protected inherited
{ return m_digit_segment_len + m_digit_gap_len; };
References Slic3r::CalibPressureAdvance::m_digit_gap_len, and Slic3r::CalibPressureAdvance::m_digit_segment_len.
Referenced by Slic3r::CalibPressureAdvance::draw_number().
print_pa_lines()
std::string Slic3r::CalibPressureAdvanceLine::print_pa_lines (double start_x, double start_y, double start_pa, double step_pa, int num) private
{
    auto& writer = mp_gcodegen->writer();
    const auto& config = mp_gcodegen->config();
    const auto filament_diameter = config.filament_diameter.get_at(0);
    const auto print_flow_ratio = config.print_flow_ratio;
    const double e_per_mm = CalibPressureAdvance::e_per_mm(
        m_line_width,
        m_height_layer,
        m_nozzle_diameter,
        filament_diameter,
        print_flow_ratio
    );
    const double thin_e_per_mm = CalibPressureAdvance::e_per_mm(
        m_thin_line_width,
        m_height_layer,
        m_nozzle_diameter,
        filament_diameter,
        print_flow_ratio
    );
    const double number_e_per_mm = CalibPressureAdvance::e_per_mm(
        m_number_line_width,
        m_height_layer,
        m_nozzle_diameter,
        filament_diameter,
        print_flow_ratio
    );
    const double fast = CalibPressureAdvance::speed_adjust(m_fast_speed);
    const double slow = CalibPressureAdvance::speed_adjust(m_slow_speed);
    std::stringstream gcode;
    gcode << mp_gcodegen->writer().travel_to_z(m_height_layer);
    double y_pos = start_y;
    // prime line
    auto prime_x = start_x - 2;
    gcode << move_to(Vec2d(prime_x, y_pos + (num - 4) * m_space_y), writer);
    gcode << writer.set_speed(slow);
    gcode << writer.extrude_to_xy(Vec2d(prime_x, y_pos + 3 * m_space_y), e_per_mm * m_space_y * num * 1.1);
    for (int i = 0; i < num; ++i) {
        gcode << writer.set_pressure_advance(start_pa + i * step_pa);
        gcode << move_to(Vec2d(start_x, y_pos + i * m_space_y), writer);
        gcode << writer.set_speed(slow);
        gcode << writer.extrude_to_xy(Vec2d(start_x + m_length_short, y_pos + i * m_space_y), e_per_mm * m_length_short);
        gcode << writer.set_speed(fast);
        gcode << writer.extrude_to_xy(Vec2d(start_x + m_length_short + m_length_long, y_pos + i * m_space_y), e_per_mm * m_length_long);
        gcode << writer.set_speed(slow);
        gcode << writer.extrude_to_xy(Vec2d(start_x + m_length_short + m_length_long + m_length_short, y_pos + i * m_space_y), e_per_mm * m_length_short);
    }
    gcode << writer.set_pressure_advance(0.0);
    if (m_draw_numbers) {
        // draw indicator lines
        gcode << writer.set_speed(fast);
        gcode << move_to(Vec2d(start_x + m_length_short, y_pos + (num - 1) * m_space_y + 2), writer);
        gcode << writer.extrude_to_xy(Vec2d(start_x + m_length_short, y_pos + (num - 1) * m_space_y + 7), thin_e_per_mm * 7);
        gcode << move_to(Vec2d(start_x + m_length_short + m_length_long, y_pos + (num - 1) * m_space_y + 7), writer);
        gcode << writer.extrude_to_xy(Vec2d(start_x + m_length_short + m_length_long, y_pos + (num - 1) * m_space_y + 2), thin_e_per_mm * 7);
        for (int i = 0; i < num; i += 2) {
            gcode << draw_number(
                start_x + m_length_short + m_length_long + m_length_short + 3,
                y_pos + i * m_space_y + m_space_y / 2,
                start_pa + i * step_pa,
                m_draw_digit_mode,
                m_number_line_width,
                number_e_per_mm,
                3600,
                writer
            );
        }
    }
    return gcode.str();
}
References Slic3r::GCode::config(), Slic3r::CalibPressureAdvance::draw_number(), Slic3r::CalibPressureAdvance::e_per_mm(), Slic3r::CalibPressureAdvance::m_draw_digit_mode, m_draw_numbers, m_fast_speed, m_height_layer, m_length_long, m_length_short, m_line_width, m_nozzle_diameter, m_number_line_width, m_slow_speed, m_space_y, m_thin_line_width, Slic3r::CalibPressureAdvance::move_to(), mp_gcodegen, Slic3r::CalibPressureAdvance::speed_adjust(), Slic3r::GCodeWriter::travel_to_z(), and Slic3r::GCode::writer().
Referenced by generate_test().
set_speed()
void Slic3r::CalibPressureAdvanceLine::set_speed (double fast = 100.0, double slow = 20.0) inline
{
        m_slow_speed = slow;
        m_fast_speed = fast;
    }
References m_fast_speed, and m_slow_speed.
Referenced by Slic3r::GCode::_do_export().
speed_adjust()
double Slic3r::CalibPressureAdvance::speed_adjust (int speed) const inline protected inherited
{ return speed * 60; };
Referenced by Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and print_pa_lines().
Member Data Documentation
m_digit_gap_len
const double Slic3r::CalibPressureAdvance::m_digit_gap_len {1} protected inherited
Referenced by Slic3r::CalibPressureAdvancePattern::max_numbering_height(), and Slic3r::CalibPressureAdvance::number_spacing().
m_digit_segment_len
const double Slic3r::CalibPressureAdvance::m_digit_segment_len {2} protected inherited
Referenced by Slic3r::CalibPressureAdvance::draw_digit(), Slic3r::CalibPressureAdvancePattern::glyph_length_x(), Slic3r::CalibPressureAdvancePattern::max_numbering_height(), and Slic3r::CalibPressureAdvance::number_spacing().
m_draw_digit_mode
DrawDigitMode Slic3r::CalibPressureAdvance::m_draw_digit_mode {DrawDigitMode::Left_To_Right} protected inherited
Referenced by Slic3r::CalibPressureAdvancePattern::CalibPressureAdvancePattern(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and print_pa_lines().
m_draw_numbers
bool Slic3r::CalibPressureAdvanceLine::m_draw_numbers {true} private
Referenced by draw_numbers(), and print_pa_lines().
m_fast_speed
double Slic3r::CalibPressureAdvanceLine::m_fast_speed private
Referenced by print_pa_lines(), and set_speed().
m_height_layer
const double Slic3r::CalibPressureAdvanceLine::m_height_layer {0.2} private
Referenced by print_pa_lines().
m_last_pos
Vec3d Slic3r::CalibPressureAdvance::m_last_pos protected inherited
Referenced by Slic3r::CalibPressureAdvancePattern::draw_line(), and Slic3r::CalibPressureAdvance::move_to().
m_length_long
double Slic3r::CalibPressureAdvanceLine::m_length_long {40.0} private
Referenced by generate_test(), and print_pa_lines().
m_length_short
double Slic3r::CalibPressureAdvanceLine::m_length_short {20.0} private
Referenced by generate_test(), and print_pa_lines().
m_line_width
const double Slic3r::CalibPressureAdvanceLine::m_line_width {0.6} private
Referenced by line_width(), and print_pa_lines().
m_max_number_len
const std::string::size_type Slic3r::CalibPressureAdvance::m_max_number_len {5} protected inherited
Referenced by Slic3r::CalibPressureAdvance::draw_number(), and Slic3r::CalibPressureAdvancePattern::max_numbering_height().
m_nozzle_diameter
double Slic3r::CalibPressureAdvanceLine::m_nozzle_diameter private
Referenced by print_pa_lines().
m_number_line_width
const double Slic3r::CalibPressureAdvanceLine::m_number_line_width {0.48} private
Referenced by print_pa_lines().
m_slow_speed
double Slic3r::CalibPressureAdvanceLine::m_slow_speed private
Referenced by print_pa_lines(), and set_speed().
m_space_y
const double Slic3r::CalibPressureAdvanceLine::m_space_y {3.5} private
Referenced by delta_modify_start(), generate_test(), and print_pa_lines().
m_thin_line_width
const double Slic3r::CalibPressureAdvanceLine::m_thin_line_width {0.44} private
Referenced by print_pa_lines().
mp_gcodegen
GCode* Slic3r::CalibPressureAdvanceLine::mp_gcodegen private
Referenced by generate_test(), is_delta(), and print_pa_lines().
The documentation for this class was generated from the following files:
src/libslic3r/calib.hpp
src/libslic3r/calib.cpp