OrcaSlicer: Slic3r::GUI::PartPlateList Class Reference
Slic3r::GUI::PartPlateList Class Reference
#include <src/slic3r/GUI/PartPlate.hpp>
Classes
class BedTextureInfo
Public Types
using Timestamp = uint64_t
Public Member Functions
PartPlateList (int width, int depth, int height, Plater *platerObj, Model *modelObj, PrinterTechnology tech=ptFFF)
PartPlateList (Plater *platerObj, Model *modelObj, PrinterTechnology tech=ptFFF)
~PartPlateList ()
void reset_size (int width, int depth, int height, bool reload_objects=true, bool update_shapes=false)
void clear (bool delete_plates=false, bool release_print_list=false, bool except_locked=false, int plate_index=-1)
void reset (bool do_init)
Vec3d compute_origin_using_new_size (int i, int new_width, int new_depth)
void reinit ()
double plate_stride_x ()
double plate_stride_y ()
void get_plate_size (int &width, int &depth, int &height)
int create_plate (bool adjust_position=true)
int destroy_print (int print_index)
int delete_plate (int index)
void delete_selected_plate ()
PartPlate * get_plate (int index)
void get_height_limits (float &height_to_lid, float &height_to_rod)
void set_height_limits_mode (PartPlate::HeightLimitMode mode)
const std::string & get_logo_texture_filename () const
int get_curr_plate_index () const
PartPlate * get_curr_plate ()
const PartPlate * get_curr_plate () const
std::vector< PartPlate * > & get_plate_list ()
PartPlate * get_selected_plate ()
std::vector< PartPlate * > get_nonempty_plate_list ()
std::vector< const GCodeProcessorResult * > get_nonempty_plates_slice_results ()
Vec3d get_current_plate_origin ()
Vec2d get_current_shape_position ()
Pointfs get_exclude_area ()
int select_plate (int index)
int get_plate_count () const
void update_plate_cols ()
void update_all_plates_pos_and_size (bool adjust_position=true, bool with_unprintable_move=true)
int get_plate_cols ()
int move_plate_to_index (int old_index, int new_index)
int lock_plate (int index, bool state)
bool is_locked (int index)
int find_plate_by_print_index (int index)
int find_instance (int obj_id, int instance_id)
int find_instance (BoundingBoxf3 &bounding_box)
int find_instance_belongs (int obj_id, int instance_id)
int notify_instance_update (int obj_id, int instance_id)
int notify_instance_removed (int obj_id, int instance_id)
int add_to_plate (int obj_id, int instance_id, int plate_id)
int reload_all_objects (bool except_locked=false, int plate_index=-1)
int construct_objects_list_for_new_plate (int plate_index)
int compute_plate_index (arrangement::ArrangePolygon &arrange_polygon)
bool preprocess_arrange_polygon (int obj_index, int instance_index, arrangement::ArrangePolygon &arrange_polygon, bool selected)
bool preprocess_arrange_polygon_other_locked (int obj_index, int instance_index, arrangement::ArrangePolygon &arrange_polygon, bool selected)
bool preprocess_exclude_areas (arrangement::ArrangePolygons &unselected, int num_plates=16, float inflation=0)
bool preprocess_nonprefered_areas (arrangement::ArrangePolygons &regions, int num_plates=1, float inflation=0)
void postprocess_bed_index_for_selected (arrangement::ArrangePolygon &arrange_polygon)
void postprocess_bed_index_for_unselected (arrangement::ArrangePolygon &arrange_polygon)
void postprocess_bed_index_for_current_plate (arrangement::ArrangePolygon &arrange_polygon)
void postprocess_arrange_polygon (arrangement::ArrangePolygon &arrange_polygon, bool selected)
void on_change_color_mode (bool is_dark)
void render (bool bottom, bool only_current=false, bool only_body=false, int hover_id=-1, bool render_cali=false)
void render_for_picking_pass ()
void set_render_option (bool bedtype_texture, bool plate_settings)
void set_render_cali (bool value=true)
BoundingBoxf3 & get_bounding_box ()
int select_plate_by_obj (int obj_index, int instance_index)
void calc_bounding_boxes ()
void select_plate_view ()
bool set_shapes (const Pointfs &shape, const Pointfs &exclude_areas, const std::string &custom_texture, float height_to_lid, float height_to_rod)
void set_hover_id (int id)
void reset_hover_id ()
bool intersects (const BoundingBoxf3 &bb)
bool contains (const BoundingBoxf3 &bb)
void update_slice_context_to_current_plate (BackgroundSlicingProcess &process)
Print & get_current_fff_print () const
GCodeProcessorResult * get_current_slice_result () const
int create_plate_from_gcode_file (const std::string &filename)
void invalid_all_slice_result ()
void update_current_slice_result_state (bool valid)
bool is_all_slice_results_valid () const
bool is_all_slice_results_ready_for_print () const
bool is_all_plates_ready_for_slice () const
void print () const
void get_sliced_result (std::vector< bool > &sliced_result, std::vector< std::string > &gcode_paths)
int rebuild_plates_after_deserialize (std::vector< bool > &previous_sliced_result, std::vector< std::string > &previous_gcode_paths)
int rebuild_plates_after_arrangement (bool recycle_plates=true, bool except_locked=false, int plate_index=-1)
int store_to_3mf_structure (PlateDataPtrs &plate_data_list, bool with_slice_info=true, int plate_idx=-1)
int load_from_3mf_structure (PlateDataPtrs &plate_data_list)
int load_gcode_files ()
template<class Archive >
void serialize (Archive &ar)
void init_bed_type_info ()
void load_bedtype_textures ()
void show_cali_texture (bool show=true)
void init_cali_texture_info ()
void load_cali_textures ()
ObjectID id () const
virtual Timestamp timestamp () const
Public Attributes
BedTextureInfo bed_texture_info [btCount]
BedTextureInfo cali_texture_info
Static Public Attributes
static const unsigned int MAX_PLATES_COUNT = MAX_PLATE_COUNT
static GLTexture bed_textures [(unsigned int) btCount]
static bool is_load_bedtype_textures = false
static bool is_load_cali_texture = false
Protected Member Functions
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
void init ()
Vec3d compute_origin (int index, int column_count)
Vec3d compute_origin_for_unprintable ()
Vec2d compute_shape_position (int index, int cols)
void generate_icon_textures ()
void release_icon_textures ()
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
Plater * m_plater
Model * m_model
PrinterTechnology printer_technology
std::vector< PartPlate * > m_plate_list
std::map< int, PrintBase * > m_print_list
std::map< int, GCodeResult * > m_gcode_result_list
std::mutex m_plates_mutex
int m_plate_count
int m_plate_cols
int m_current_plate
int m_print_index
int m_plate_width
int m_plate_depth
int m_plate_height
float m_height_to_lid
float m_height_to_rod
PartPlate::HeightLimitMode m_height_limit_mode {PartPlate::HEIGHT_LIMIT_BOTH}
PartPlate unprintable_plate
Pointfs m_shape
Pointfs m_exclude_areas
BoundingBoxf3 m_bounding_box
bool m_intialized
std::string m_logo_texture_filename
GLTexture m_logo_texture
GLTexture m_del_texture
GLTexture m_del_hovered_texture
GLTexture m_arrange_texture
GLTexture m_arrange_hovered_texture
GLTexture m_orient_texture
GLTexture m_orient_hovered_texture
GLTexture m_locked_texture
GLTexture m_locked_hovered_texture
GLTexture m_lockopen_texture
GLTexture m_lockopen_hovered_texture
GLTexture m_plate_settings_texture
GLTexture m_plate_settings_changed_texture
GLTexture m_plate_settings_hovered_texture
GLTexture m_plate_settings_changed_hovered_texture
GLTexture m_idx_textures [MAX_PLATE_COUNT]
bool render_bedtype_logo = true
bool render_plate_settings = true
bool render_cali_logo = true
bool m_is_dark = false
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class cereal::access
class UndoRedo::StackImpl
class PartPlate
Detailed Description
Class Documentation
Slic3r::GUI::PartPlateList::BedTextureInfo
class Slic3r::GUI::PartPlateList::BedTextureInfo
Class Members
vector< TexturePart > parts
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
PartPlateList() [1/2]
Slic3r::GUI::PartPlateList::PartPlateList (int width, int depth, int height, Plater * platerObj, Model * modelObj, PrinterTechnology tech = ptFFF)
  :m_plate_width(width), m_plate_depth(depth), m_plate_height(height), m_plater(platerObj), m_model(modelObj), printer_technology(tech),
  unprintable_plate(this, Vec3d(0.0 + width * (1. + LOGICAL_PART_PLATE_GAP), 0.0, 0.0), width, depth, height, platerObj, modelObj, false, tech)
{
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":plate_width %1%, plate_depth %2%, plate_height %3%") % width % depth % height;
  init();
}
References init().
PartPlateList() [2/2]
Slic3r::GUI::PartPlateList::PartPlateList (Plater * platerObj, Model * modelObj, PrinterTechnology tech = ptFFF)
  :m_plate_width(0), m_plate_depth(0), m_plate_height(0), m_plater(platerObj), m_model(modelObj), printer_technology(tech),
  unprintable_plate(this, Vec3d(0.0, 0.0, 0.0), m_plate_width, m_plate_depth, m_plate_height, platerObj, modelObj, false, tech)
{
  init();
}
References init().
~PartPlateList()
Slic3r::GUI::PartPlateList::~PartPlateList ()
{
  clear(true, true);
  release_icon_textures();
}
References clear(), and release_icon_textures().
Member Function Documentation
add_to_plate()
int Slic3r::GUI::PartPlateList::add_to_plate (int obj_id, int instance_id, int plate_id)
{
  int ret = 0, index;
  PartPlate* plate = NULL;
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": plate_id %1%, found obj_id %2%, instance_id %3%") % plate_id % obj_id % instance_id;
  index = find_instance(obj_id, instance_id);
  if (index != -1)
  {
    //found it added before
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found it in previous plate %1%") % index;
    if (index != plate_id)
    {
      //remove it from original plate first
      plate = m_plate_list[index];
      plate->remove_instance(obj_id, instance_id);
    }
    else
    {
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": already in this plate, no need to be added");
      return 0;
    }
  }
  else
  {
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": not added to plate before, add it to center");
  }
  plate = get_plate(plate_id);
  if (!plate)
  {
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":can not get plate for index %1%, size %2%") % index % m_plate_list.size();
    return -1;
  }
  ret = plate->add_instance(obj_id, instance_id, true);
  return ret;
}
References Slic3r::GUI::PartPlate::add_instance(), error, find_instance(), get_plate(), m_plate_list, NULL, and Slic3r::GUI::PartPlate::remove_instance().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
calc_bounding_boxes()
void Slic3r::GUI::PartPlateList::calc_bounding_boxes ()
{
  m_bounding_box.reset();
  std::vector<PartPlate*>::iterator it = m_plate_list.begin();
  for (it = m_plate_list.begin(); it != m_plate_list.end(); it++) {
    m_bounding_box.merge((*it)->get_bounding_box(true));
  }
}
References m_bounding_box, m_plate_list, Slic3r::BoundingBox3Base< PointClass >::merge(), and Slic3r::BoundingBoxBase< PointClass >::reset().
Referenced by create_plate(), delete_plate(), reinit(), and set_shapes().
clear()
void Slic3r::GUI::PartPlateList::clear (bool delete_plates = false, bool release_print_list = false, bool except_locked = false, int plate_index = -1)
{
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    assert(plate != NULL);
    if (except_locked && plate->is_locked())
      plate->clear(false);
    else if ((plate_index != -1) && (plate_index != i))
      plate->clear(false);
    else
      plate->clear();
    if (delete_plates)
      delete plate;
  }
  if (delete_plates)
  {
    //also delete print related to the plate
    m_plate_list.clear();
    m_current_plate = 0;
  }
  if (release_print_list)
  {
    for (std::map<int, PrintBase*>::iterator it = m_print_list.begin(); it != m_print_list.end(); ++it)
    {
      PrintBase* print = it->second;
      assert(print != NULL);
      delete print;
    }
    m_print_list.clear();
    for (std::map<int, GCodeResult*>::iterator it = m_gcode_result_list.begin(); it != m_gcode_result_list.end(); ++it)
    {
      GCodeResult* gcode = it->second;
      assert(gcode != NULL);
      delete gcode;
    }
    m_gcode_result_list.clear();
  }
  unprintable_plate.clear();
}
References Slic3r::GUI::PartPlate::clear(), Slic3r::GUI::gcode(), int, Slic3r::GUI::PartPlate::is_locked(), m_current_plate, m_gcode_result_list, m_plate_list, m_print_list, NULL, print(), and unprintable_plate.
Referenced by ~PartPlateList(), Slic3r::GUI::ArrangeJob::finalize(), load_from_3mf_structure(), reinit(), reload_all_objects(), reset(), reset_size(), and Slic3r::CLI::run().
compute_origin()
Vec3d Slic3r::GUI::PartPlateList::compute_origin (int index, int column_count) private
{
  Vec3d origin;
  int row, col;
  row = i / cols;
  col = i % cols;
  origin(0) = col * (m_plate_width * (1. + LOGICAL_PART_PLATE_GAP));
  origin(1) = -row * (m_plate_depth * (1. + LOGICAL_PART_PLATE_GAP));
  origin(2) = 0;
  return origin;
}
References col(), LOGICAL_PART_PLATE_GAP, m_plate_depth, m_plate_width, and row().
Referenced by compute_origin_for_unprintable(), create_plate(), delete_plate(), get_current_plate_origin(), move_plate_to_index(), and update_all_plates_pos_and_size().
compute_origin_for_unprintable()
Vec3d Slic3r::GUI::PartPlateList::compute_origin_for_unprintable () private
{
  int max_count = m_plate_cols * m_plate_cols;
  if (m_plate_count == max_count)
    return compute_origin(max_count + m_plate_cols - 1, m_plate_cols + 1);
  else
    return compute_origin(m_plate_count, m_plate_cols);
}
References compute_origin(), m_plate_cols, and m_plate_count.
Referenced by create_plate(), delete_plate(), reinit(), and update_all_plates_pos_and_size().
compute_origin_using_new_size()
Vec3d Slic3r::GUI::PartPlateList::compute_origin_using_new_size (int i, int new_width, int new_depth)
{
  Vec3d origin;
  int row, col;
  row = i / m_plate_cols;
  col = i % m_plate_cols;
  origin(0) = col * (new_width * (1. + LOGICAL_PART_PLATE_GAP));
  origin(1) = -row * (new_depth * (1. + LOGICAL_PART_PLATE_GAP));
  origin(2) = 0;
  return origin;
}
References col(), LOGICAL_PART_PLATE_GAP, m_plate_cols, and row().
Referenced by Slic3r::CLI::run().
compute_plate_index()
int Slic3r::GUI::PartPlateList::compute_plate_index (arrangement::ArrangePolygon & arrange_polygon)
{
  int row, col;
  float col_value = (unscale<double>(arrange_polygon.translation(X))) / plate_stride_x();
  float row_value = (plate_stride_y() - unscale<double>(arrange_polygon.translation(Y))) / plate_stride_y();
  row = round(row_value);
  col = round(col_value);
  return row * m_plate_cols + col;
}
References col(), m_plate_cols, plate_stride_x(), plate_stride_y(), round(), row(), Slic3r::arrangement::ArrangePolygon::translation, Slic3r::X, and Slic3r::Y.
compute_shape_position()
Vec2d Slic3r::GUI::PartPlateList::compute_shape_position (int index, int cols) private
{
  Vec2d pos;
  int row, col;
  row = index / cols;
  col = index % cols;
  pos(0) = col * plate_stride_x();
  pos(1) = -row * plate_stride_y();
  return pos;
}
References col(), plate_stride_x(), plate_stride_y(), and row().
Referenced by create_plate(), delete_plate(), get_current_shape_position(), rebuild_plates_after_deserialize(), reinit(), select_plate(), and set_shapes().
construct_objects_list_for_new_plate()
int Slic3r::GUI::PartPlateList::construct_objects_list_for_new_plate (int plate_index)
{
  int ret = 0;
  unsigned int i, j, k;
  PartPlate* new_plate = m_plate_list[plate_index];
  bool already_included;
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": m_model->objects.size() is %1%") % m_model->objects.size();
  unprintable_plate.clear();
  //try to find a new plate
  for (i = 0; i < (unsigned int)m_model->objects.size(); ++i)
  {
    ModelObject* object = m_model->objects[i];
    for (j = 0; j < (unsigned int)object->instances.size(); ++j)
    {
      ModelInstance* instance = object->instances[j];
      already_included = false;
      for (k = 0; k < (unsigned int)plate_index; ++k)
      {
        PartPlate* plate = m_plate_list[k];
        if (plate->contain_instance(i, j))
        {
          already_included = true;
          break;
        }
      }
      if (already_included)
        continue;
      BoundingBoxf3 boundingbox = object->instance_convex_hull_bounding_box(j);
      if (new_plate->intersect_instance(i, j, &boundingbox))
      {
        //found a new plate, add it to plate
        ret |= new_plate->add_instance(i, j, false, &boundingbox);
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": added to plate_id %1%, for obj_id %2%, instance_id %3%") % plate_index % i % j;
        continue;
      }
      if ( (unprintable_plate.intersect_instance(i, j, &boundingbox)))
      {
        //found in unprintable plate, add it to plate
        unprintable_plate.add_instance(i, j, false, &boundingbox);
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found in unprintable plate, obj_id %1%, instance_id %2%") % i % j;
      }
    }
  }
  return ret;
}
References Slic3r::GUI::PartPlate::add_instance(), Slic3r::GUI::PartPlate::clear(), Slic3r::GUI::PartPlate::contain_instance(), int, Slic3r::GUI::PartPlate::intersect_instance(), m_model, m_plate_list, Slic3r::Model::objects, and unprintable_plate.
Referenced by create_plate().
contains()
bool Slic3r::GUI::PartPlateList::contains (const BoundingBoxf3 & bb)
{
  bool result = false;
  std::vector<PartPlate*>::iterator it = m_plate_list.begin();
  for (it = m_plate_list.begin(); it != m_plate_list.end(); it++) {
    if ((*it)->contains(bb)) {
      result = true;
    }
  }
  return result;
}
References m_plate_list.
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
create_plate()
int Slic3r::GUI::PartPlateList::create_plate (bool adjust_position = true)
{
  PartPlate* plate = NULL;
  Vec3d origin;
  int new_index;
  new_index = m_plate_list.size();
  if (new_index >= MAX_PLATES_COUNT)
    return -1;
  int cols = compute_colum_count(new_index + 1);
  int old_cols = compute_colum_count(new_index);
  origin = compute_origin(new_index, cols);
  plate = new PartPlate(this, origin, m_plate_width, m_plate_depth, m_plate_height, m_plater, m_model, true, printer_technology);
  assert(plate != NULL);
  if (printer_technology == ptFFF)
  {
    Print* print = new Print();
    GCodeResult* gcode = new GCodeResult();
    m_print_list.emplace(m_print_index, print);
    m_gcode_result_list.emplace(m_print_index, gcode);
    plate->set_print(print, gcode, m_print_index);
    m_print_index++;
  }
  plate->set_index(new_index);
  Vec2d pos = compute_shape_position(new_index, cols);
  plate->set_shape(m_shape, m_exclude_areas, pos, m_height_to_lid, m_height_to_rod);
  m_plate_list.emplace_back(plate);
  update_plate_cols();
  if (old_cols != cols)
  {
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":old_cols %1% -> new_cols %2%") % old_cols % cols;
    //update the origin of each plate
    update_all_plates_pos_and_size(adjust_position, false);
    set_shapes(m_shape, m_exclude_areas, m_logo_texture_filename, m_height_to_lid, m_height_to_rod);
    if (m_plater) {
      Vec2d pos = compute_shape_position(m_current_plate, cols);
      m_plater->set_bed_position(pos);
    }
  }
  else
  {
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": the same cols %1%") % old_cols;
    Vec3d origin2 = compute_origin_for_unprintable();
    unprintable_plate.set_pos_and_size(origin2, m_plate_width, m_plate_depth, m_plate_height, false);
    //update bounding_boxes
    calc_bounding_boxes();
  }
  // update wipe tower config
  if (m_plater) {
    // In GUI mode
    DynamicConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
    ConfigOptionFloats* wipe_tower_x = proj_cfg.opt<ConfigOptionFloats>("wipe_tower_x");
    ConfigOptionFloats* wipe_tower_y = proj_cfg.opt<ConfigOptionFloats>("wipe_tower_y");
    wipe_tower_x->values.resize(m_plate_list.size(), wipe_tower_x->values.front());
    wipe_tower_y->values.resize(m_plate_list.size(), wipe_tower_y->values.front());
  }
  unprintable_plate.set_index(new_index+1);
  //reload all objects here
  if (adjust_position)
    construct_objects_list_for_new_plate(new_index);
  if (m_plater) {
    // In GUI mode
    wxGetApp().obj_list()->on_plate_added(plate);
  }
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":created a new plate %1%") % new_index;
  return new_index;
}
References calc_bounding_boxes(), compute_colum_count(), compute_origin(), compute_origin_for_unprintable(), compute_shape_position(), construct_objects_list_for_new_plate(), Slic3r::GUI::gcode(), m_current_plate, m_exclude_areas, m_gcode_result_list, m_height_to_lid, m_height_to_rod, m_logo_texture_filename, m_model, m_plate_depth, m_plate_height, m_plate_list, m_plate_width, m_plater, m_print_index, m_print_list, m_shape, MAX_PLATES_COUNT, NULL, Slic3r::DynamicConfig::opt(), PartPlate, print(), printer_technology, Slic3r::ptFFF, Slic3r::GUI::Plater::set_bed_position(), Slic3r::GUI::PartPlate::set_index(), Slic3r::GUI::PartPlate::set_pos_and_size(), Slic3r::GUI::PartPlate::set_print(), Slic3r::GUI::PartPlate::set_shape(), set_shapes(), unprintable_plate, update_all_plates_pos_and_size(), update_plate_cols(), Slic3r::ConfigOptionVector< T >::values, and Slic3r::wipe_tower_y().
Referenced by load_from_3mf_structure(), and postprocess_bed_index_for_selected().
create_plate_from_gcode_file()
int Slic3r::GUI::PartPlateList::create_plate_from_gcode_file (const std::string & filename)
{
  int ret = 0;
  return ret;
}
delete_plate()
int Slic3r::GUI::PartPlateList::delete_plate (int index)
{
  int ret = 0;
  PartPlate* plate = NULL;
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":delete plate %1%, count %2%") % index % m_plate_list.size();
  if (index >= m_plate_list.size())
  {
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":can not find plate");
    return -1;
  }
  if (m_plate_list.size() <= 1)
  {
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":only one plate left, can not delete");
    return -1;
  }
  plate = m_plate_list[index];
  if (index != plate->get_index())
  {
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":plate %1%, has an invalid index %2%") % index % plate->get_index();
    return -1;
  }
  if (m_plater) {
    // In GUI mode
    // BBS: add wipe tower logic
    DynamicConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
    ConfigOptionFloats* wipe_tower_x = proj_cfg.opt<ConfigOptionFloats>("wipe_tower_x");
    ConfigOptionFloats* wipe_tower_y = proj_cfg.opt<ConfigOptionFloats>("wipe_tower_y");
    // wipe_tower_x and wip_tower_y may be less than plate count in the following case:
    // 1. wipe_tower is enabled after creating new plates
    // 2. wipe tower is not enabled
    if (index < wipe_tower_x->values.size())
      wipe_tower_x->values.erase(wipe_tower_x->values.begin() + index);
    if (index < wipe_tower_y->values.size())
      wipe_tower_y->values.erase(wipe_tower_y->values.begin() + index);
  }
  int cols = compute_colum_count(m_plate_list.size() - 1);
  int old_cols = compute_colum_count(m_plate_list.size());
  m_plate_list.erase(m_plate_list.begin() + index);
  update_plate_cols();
  //update this plate
  //move this plate's instance to the end
  Vec3d current_origin;
  current_origin = compute_origin_for_unprintable();
  plate->set_pos_and_size(current_origin, m_plate_width, m_plate_depth, m_plate_height, true);
  //update the plates after it
  for (unsigned int i = index; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    assert(plate != NULL);
    plate->set_index(i);
    Vec3d origin = compute_origin(i, m_plate_cols);
    plate->set_pos_and_size(origin, m_plate_width, m_plate_depth, m_plate_height, true);
    //update render shapes
    Vec2d pos = compute_shape_position(i, m_plate_cols);
    plate->set_shape(m_shape, m_exclude_areas, pos, m_height_to_lid, m_height_to_rod);
  }
  //update current_plate if delete current
  if (m_current_plate == index && index == 0) {
    select_plate(0);
  }
  else if (m_current_plate >= index) {
    select_plate(m_current_plate - 1);
  }
  else {
    //delete the plate behind current, just need to update the position of Bed3D
    Vec2d pos = compute_shape_position(m_current_plate, m_plate_cols);
    if (m_plater)
      m_plater->set_bed_position(pos);
  }
  unprintable_plate.set_index(m_plate_list.size());
  if (old_cols != cols)
  {
    //update the origin of each plate
    update_all_plates_pos_and_size();
    set_shapes(m_shape, m_exclude_areas, m_logo_texture_filename, m_height_to_lid, m_height_to_rod);
  }
  else
  {
    //update the position of the unprintable plate
    Vec3d origin2 = compute_origin_for_unprintable();
    unprintable_plate.set_pos_and_size(origin2, m_plate_width, m_plate_depth, m_plate_height, true);
    //update bounding_boxes
    calc_bounding_boxes();
  }
  plate->move_instances_to(*(m_plate_list[m_plate_list.size()-1]), unprintable_plate);
  //destroy the print object
  int print_index;
  plate->get_print(nullptr, nullptr, &print_index);
  destroy_print(print_index);
  delete plate;
    // FIX: context of BackgroundSliceProcess and gcode preview need to be updated before ObjectList::reload_all_plates().
#if 0
  if (m_plater != nullptr) {
    // In GUI mode
    wxGetApp().obj_list()->reload_all_plates();
  }
#endif
  return ret;
}
References calc_bounding_boxes(), compute_colum_count(), compute_origin(), compute_origin_for_unprintable(), compute_shape_position(), destroy_print(), Slic3r::GUI::PartPlate::get_index(), Slic3r::GUI::PartPlate::get_print(), int, m_current_plate, m_exclude_areas, m_height_to_lid, m_height_to_rod, m_logo_texture_filename, m_plate_cols, m_plate_depth, m_plate_height, m_plate_list, m_plate_width, m_plater, m_shape, Slic3r::GUI::PartPlate::move_instances_to(), NULL, Slic3r::DynamicConfig::opt(), select_plate(), Slic3r::GUI::Plater::set_bed_position(), Slic3r::GUI::PartPlate::set_index(), Slic3r::GUI::PartPlate::set_pos_and_size(), Slic3r::GUI::PartPlate::set_shape(), set_shapes(), unprintable_plate, update_all_plates_pos_and_size(), update_plate_cols(), Slic3r::ConfigOptionVector< T >::values, and Slic3r::wipe_tower_y().
Referenced by delete_selected_plate(), and rebuild_plates_after_arrangement().
delete_selected_plate()
void Slic3r::GUI::PartPlateList::delete_selected_plate ()
{
  delete_plate(m_current_plate);
}
References delete_plate(), and m_current_plate.
destroy_print()
int Slic3r::GUI::PartPlateList::destroy_print (int print_index)
{
  int result = 0;
  if (print_index >= 0)
  {
    std::map<int, PrintBase*>::iterator it = m_print_list.find(print_index);
    if (it != m_print_list.end())
    {
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":delete Print %1% for print_index %2%") % it->second % print_index;
      delete it->second;
      m_print_list.erase(it);
    }
    else
    {
      BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":can not find Print for print_index %1%") % print_index;
      result = -1;
    }
    std::map<int, GCodeResult*>::iterator it2 = m_gcode_result_list.find(print_index);
    if (it2 != m_gcode_result_list.end())
    {
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":delete GCodeResult %1% for print_index %2%") % it2->second % print_index;
      delete it2->second;
      m_gcode_result_list.erase(it2);
    }
    else
    {
      BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":can not find GCodeResult for print_index %1%") % print_index;
      result = -1;
    }
  }
  return result;
}
References m_gcode_result_list, and m_print_list.
Referenced by delete_plate(), and rebuild_plates_after_deserialize().
find_instance() [1/2]
int Slic3r::GUI::PartPlateList::find_instance (BoundingBoxf3 & bounding_box)
{
  int ret = -1;
  //update the plates after it
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    assert(plate != NULL);
    if (plate->intersects(bounding_box))
      return i;
  }
  //return -1 for not found
  return ret;
}
References Slic3r::bounding_box(), int, Slic3r::GUI::PartPlate::intersects(), m_plate_list, and NULL.
find_instance() [2/2]
int Slic3r::GUI::PartPlateList::find_instance (int obj_id, int instance_id)
{
  int ret = -1;
  //update the plates after it
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    assert(plate != NULL);
    if (plate->contain_instance(obj_id, instance_id))
      return i;
  }
  //return -1 for not found
  return ret;
}
References Slic3r::GUI::PartPlate::contain_instance(), int, m_plate_list, and NULL.
Referenced by add_to_plate(), Slic3r::GUI::ObjectList::can_drop(), notify_instance_removed(), notify_instance_update(), Slic3r::GUI::ObjectList::OnBeginDrag(), Slic3r::GUI::OrientJob::prepare_selection(), and select_plate_by_obj().
find_instance_belongs()
int Slic3r::GUI::PartPlateList::find_instance_belongs (int obj_id, int instance_id)
{
  int ret = -1;
  //update the plates after it
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    assert(plate != NULL);
    if (plate->contain_instance_totally(obj_id, instance_id))
      return i;
  }
  //return -1 for not found
  return ret;
}
References Slic3r::GUI::PartPlate::contain_instance_totally(), int, m_plate_list, and NULL.
Referenced by Slic3r::GUI::ObjectList::add_object_to_list(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), and Slic3r::GUI::ObjectList::update_plate_values_for_items().
find_plate_by_print_index()
int Slic3r::GUI::PartPlateList::find_plate_by_print_index (int index)
{
  int plate_index = -1;
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    if (plate->m_print_index == print_index)
    {
      plate_index = i;
      break;
    }
  }
  return plate_index;
}
References int, m_plate_list, and Slic3r::GUI::PartPlate::m_print_index.
Referenced by rebuild_plates_after_deserialize().
generate_icon_textures()
void Slic3r::GUI::PartPlateList::generate_icon_textures () private
{
  // use higher resolution images if graphic card and opengl version allow
  GLint max_tex_size = OpenGLManager::get_gl_info().get_max_tex_size(), icon_size = max_tex_size / 8;
  std::string path = resources_dir() + "/images/";
  std::string file_name;
  if (icon_size > 256)
    icon_size = 256;
  //if (m_del_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_close_dark.svg" : "plate_close.svg");
    if (!m_del_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_del_hovered_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_close_hover_dark.svg" : "plate_close_hover.svg");
    if (!m_del_hovered_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_arrange_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_arrange_dark.svg" : "plate_arrange.svg");
    if (!m_arrange_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_arrange_hovered_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_arrange_hover_dark.svg" : "plate_arrange_hover.svg");
    if (!m_arrange_hovered_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_orient_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_orient_dark.svg" : "plate_orient.svg");
    if (!m_orient_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_orient_hovered_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_orient_hover_dark.svg" : "plate_orient_hover.svg");
    if (!m_orient_hovered_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_locked_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_locked_dark.svg" : "plate_locked.svg");
    if (!m_locked_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_locked_hovered_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_locked_hover_dark.svg" : "plate_locked_hover.svg");
    if (!m_locked_hovered_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_lockopen_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_unlocked_dark.svg" : "plate_unlocked.svg");
    if (!m_lockopen_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_lockopen_hovered_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_unlocked_hover_dark.svg" : "plate_unlocked_hover.svg");
    if (!m_lockopen_hovered_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_bedtype_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_settings_dark.svg" : "plate_settings.svg");
    if (!m_plate_settings_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_bedtype_changed_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_settings_changed_dark.svg" : "plate_settings_changed.svg");
    if (!m_plate_settings_changed_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_bedtype_hovered_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_settings_hover_dark.svg" : "plate_settings_hover.svg");
    if (!m_plate_settings_hovered_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  //if (m_bedtype_changed_hovered_texture.get_id() == 0)
  {
    file_name = path + (m_is_dark ? "plate_settings_changed_hover_dark.svg" : "plate_settings_changed_hover.svg");
    if (!m_plate_settings_changed_hovered_texture.load_from_svg_file(file_name, true, false, false, icon_size)) {
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
    }
  }
  std::string text_str = "01";
  wxFont* font = find_font(text_str,32);
  for (int i = 0; i < MAX_PLATE_COUNT; i++) {
    if (m_idx_textures[i].get_id() == 0) {
      //file_name = path + (boost::format("plate_%1%.svg") % (i + 1)).str();
      if ( i < 9 )
        file_name = std::string("0") + std::to_string(i+1);
      else
        file_name = std::to_string(i+1);
      wxColour foreground(0xf2, 0x75, 0x4e, 0xff);
      if (!m_idx_textures[i].generate_from_text_string(file_name, *font, *wxBLACK, foreground)) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":load file %1% failed") % file_name;
      }
    }
  }
}
References error, Slic3r::GUI::find_font(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::get_max_tex_size(), Slic3r::GUI::GLTexture::load_from_svg_file(), m_arrange_hovered_texture, m_arrange_texture, m_del_hovered_texture, m_del_texture, m_idx_textures, m_is_dark, m_locked_hovered_texture, m_locked_texture, m_lockopen_hovered_texture, m_lockopen_texture, m_orient_hovered_texture, m_orient_texture, m_plate_settings_changed_hovered_texture, m_plate_settings_changed_texture, m_plate_settings_hovered_texture, m_plate_settings_texture, MAX_PLATE_COUNT, and Slic3r::resources_dir().
Referenced by render().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_bounding_box()
BoundingBoxf3 & Slic3r::GUI::PartPlateList::get_bounding_box () inline
{ return m_bounding_box; }
References m_bounding_box.
Referenced by Slic3r::GUI::GLCanvas3D::scene_bounding_box().
get_curr_plate() [1/2]
PartPlate * Slic3r::GUI::PartPlateList::get_curr_plate () inline
{ return m_plate_list[m_current_plate]; }
References m_current_plate, and m_plate_list.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::MainFrame::can_export_gcode(), Slic3r::GUI::Plater::export_config_3mf(), Slic3r::GUI::MainFrame::get_enable_print_status(), Slic3r::GUI::MainFrame::get_enable_slice_status(), Slic3r::GUI::init_arrange_params(), Slic3r::GUI::SelectMachineDialog::is_show_timelapse(), Slic3r::GUI::GLCanvas3D::load_gcode_preview(), Slic3r::GUI::SelectMachineDialog::on_ok_btn(), Slic3r::GUI::Plater::priv::on_slicing_update(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::CLI::run(), Slic3r::GUI::Plater::send_gcode(), Slic3r::GUI::SelectMachineDialog::set_default(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
get_curr_plate() [2/2]
const PartPlate * Slic3r::GUI::PartPlateList::get_curr_plate () const inline
{ return m_plate_list[m_current_plate]; }
References m_current_plate, and m_plate_list.
get_curr_plate_index()
int Slic3r::GUI::PartPlateList::get_curr_plate_index () const inline
{ return m_current_plate; }
References m_current_plate.
Referenced by Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::Plater::export_config_3mf(), Slic3r::GUI::Plater::export_gcode_3mf(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), select_plate(), and Slic3r::GUI::Plater::send_gcode().
get_current_fff_print()
Print & Slic3r::GUI::PartPlateList::get_current_fff_print () const
{
  PartPlate* current_plate;
  Print* print;
  current_plate = m_plate_list[m_current_plate];
  //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":m_current_plate %1%, current_plate %2%") % m_current_plate % current_plate;
  assert(current_plate != NULL);
  current_plate->get_print((PrintBase **)&print, nullptr, nullptr);
  return *print;
}
References Slic3r::GUI::PartPlate::get_print(), m_current_plate, m_plate_list, NULL, and print().
Referenced by Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), and Slic3r::GUI::SelectMachineDialog::set_default().
get_current_plate_origin()
Vec3d Slic3r::GUI::PartPlateList::get_current_plate_origin () inline
{ return compute_origin(m_current_plate, m_plate_cols); }
References compute_origin(), m_current_plate, and m_plate_cols.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern().
get_current_shape_position()
Vec2d Slic3r::GUI::PartPlateList::get_current_shape_position () inline
{ return compute_shape_position(m_current_plate, m_plate_cols); }
References compute_shape_position(), m_current_plate, and m_plate_cols.
get_current_slice_result()
GCodeProcessorResult * Slic3r::GUI::PartPlateList::get_current_slice_result () const
{
  PartPlate* current_plate;
  current_plate = m_plate_list[m_current_plate];
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":m_current_plate %1%, current_plate %2%") % m_current_plate % current_plate;
  assert(current_plate != NULL);
  return current_plate->get_slice_result();
}
References Slic3r::GUI::PartPlate::get_slice_result(), m_current_plate, m_plate_list, and NULL.
get_exclude_area()
Pointfs Slic3r::GUI::PartPlateList::get_exclude_area () inline
{ return m_exclude_areas; }
References m_exclude_areas.
get_height_limits()
void Slic3r::GUI::PartPlateList::get_height_limits (float & height_to_lid, float & height_to_rod) inline
    {
        height_to_lid = m_height_to_lid;
        height_to_rod = m_height_to_rod;
    }
References m_height_to_lid, and m_height_to_rod.
get_logo_texture_filename()
const std::string & Slic3r::GUI::PartPlateList::get_logo_texture_filename () const inline
{
        return m_logo_texture_filename;
    }
References m_logo_texture_filename.
get_nonempty_plate_list()
std::vector< PartPlate * > Slic3r::GUI::PartPlateList::get_nonempty_plate_list ()
{
  std::vector<PartPlate*> nonempty_plate_list;
  for (auto plate : m_plate_list){
    if (plate->get_extruders().size() != 0) {
      nonempty_plate_list.push_back(plate);
    }
  }
  return nonempty_plate_list;
}
References m_plate_list.
Referenced by Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::_update_select_plate_toolbar_stats_item(), get_nonempty_plates_slice_results(), and Slic3r::GUI::GCodeViewer::render_all_plates_stats().
get_nonempty_plates_slice_results()
std::vector< const GCodeProcessorResult * > Slic3r::GUI::PartPlateList::get_nonempty_plates_slice_results ()
{
  std::vector<const GCodeProcessorResult*> nonempty_plates_slice_result;
  for (auto plate : get_nonempty_plate_list()) {
    nonempty_plates_slice_result.push_back(plate->get_slice_result());
  }
  return nonempty_plates_slice_result;
}
References get_nonempty_plate_list().
Referenced by Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar().
get_plate()
PartPlate * Slic3r::GUI::PartPlateList::get_plate (int index)
{
  PartPlate* plate = NULL;
  if (index >= m_plate_list.size())
  {
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":can not find index %1%, size %2%") % index % m_plate_list.size();
    return NULL;
  }
  plate = m_plate_list[index];
  assert(plate != NULL);
  return plate;
}
References m_plate_list, and NULL.
Referenced by Slic3r::GUI::GCodeViewer::_render_calibration_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::_update_imgui_select_plate_toolbar(), add_to_plate(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::estimate_wipe_tower_points(), Slic3r::GUI::ObjectDataViewModel::Init(), Slic3r::GUI::Plater::invalid_all_plate_thumbnails(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), lock_plate(), Slic3r::GUI::ObjectList::OnBeginDrag(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::ObjectList::reload_all_plates(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::render_thumbnail_internal(), Slic3r::CLI::run(), and Slic3r::GUI::Plater::update_all_plate_thumbnails().
get_plate_cols()
int Slic3r::GUI::PartPlateList::get_plate_cols () inline
{ return m_plate_cols; }
References m_plate_cols.
Referenced by Slic3r::GUI::FillBedJob::finalize(), and Slic3r::GUI::FillBedJob::prepare().
get_plate_count()
int Slic3r::GUI::PartPlateList::get_plate_count () const
{
  int ret = 0;
  ret = m_plate_list.size();
  return ret;
}
References m_plate_list.
Referenced by Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::_update_imgui_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::estimate_wipe_tower_points(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::ObjectDataViewModel::Init(), Slic3r::GUI::Plater::invalid_all_plate_thumbnails(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::ObjectList::reload_all_plates(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::CLI::run(), and Slic3r::GUI::Plater::update_all_plate_thumbnails().
get_plate_list()
std::vector< PartPlate * > & Slic3r::GUI::PartPlateList::get_plate_list () inline
{ return m_plate_list; };
References m_plate_list.
get_plate_size()
void Slic3r::GUI::PartPlateList::get_plate_size (int & width, int & depth, int & height) inline
{
        width = m_plate_width;
        depth = m_plate_depth;
        height = m_plate_height;
    }
References m_plate_depth, m_plate_height, and m_plate_width.
get_selected_plate()
PartPlate * Slic3r::GUI::PartPlateList::get_selected_plate ()
{
  if (m_current_plate < 0 || m_current_plate >= m_plate_list.size()) {
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":can not find m_current_plate  %1%, size %2%") % m_current_plate % m_plate_list.size();
    return NULL;
  }
  return m_plate_list[m_current_plate];
}
References m_current_plate, m_plate_list, and NULL.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_center(), Slic3r::GUI::MenuFactory::append_menu_item_locked(), and Slic3r::GUI::MenuFactory::create_plate_menu().
get_sliced_result()
void Slic3r::GUI::PartPlateList::get_sliced_result (std::vector< bool > & sliced_result, std::vector< std::string > & gcode_paths)
{
  sliced_result.resize(m_plate_list.size());
  gcode_paths.resize(m_plate_list.size());
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    sliced_result[i] = m_plate_list[i]->m_slice_result_valid;
    gcode_paths[i] = m_plate_list[i]->m_tmp_gcode_path;
  }
}
References int, and m_plate_list.
Referenced by Slic3r::UndoRedo::StackImpl::load_snapshot().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
init()
void Slic3r::GUI::PartPlateList::init () private
{
  m_intialized = false;
  PartPlate* first_plate = NULL;
  first_plate = new PartPlate(this, Vec3d(0.0, 0.0, 0.0), m_plate_width, m_plate_depth, m_plate_height, m_plater, m_model, true, printer_technology);
  assert(first_plate != NULL);
  m_plate_list.push_back(first_plate);
  m_print_index = 0;
  if (printer_technology == ptFFF)
  {
    Print* print = new Print();
    GCodeResult* gcode = new GCodeResult();
    m_print_list.emplace(m_print_index, print);
    m_gcode_result_list.emplace(m_print_index, gcode);
    first_plate->set_print(print, gcode, m_print_index);
    m_print_index++;
  }
  first_plate->set_index(0);
  m_plate_count = 1;
  m_plate_cols = 1;
  m_current_plate = 0;
  select_plate(0);
  unprintable_plate.set_index(1);
  m_intialized = true;
}
References Slic3r::GUI::gcode(), m_current_plate, m_gcode_result_list, m_intialized, m_model, m_plate_cols, m_plate_count, m_plate_depth, m_plate_height, m_plate_list, m_plate_width, m_plater, m_print_index, m_print_list, NULL, PartPlate, print(), printer_technology, Slic3r::ptFFF, select_plate(), Slic3r::GUI::PartPlate::set_index(), Slic3r::GUI::PartPlate::set_print(), and unprintable_plate.
Referenced by PartPlateList(), PartPlateList(), reinit(), and reset().
init_bed_type_info()
void Slic3r::GUI::PartPlateList::init_bed_type_info ()
{
  BedTextureInfo::TexturePart pc_part1(  5, 130,  10, 110, "bbl_bed_pc_left.svg");
  BedTextureInfo::TexturePart pc_part2( 74, -12, 150,  12, "bbl_bed_pc_bottom.svg");
  BedTextureInfo::TexturePart ep_part1(  4,  87,  12, 153, "bbl_bed_ep_left.svg");
  BedTextureInfo::TexturePart ep_part2( 72, -11, 150,  12, "bbl_bed_ep_bottom.svg");
  BedTextureInfo::TexturePart pei_part1( 6,  50,  12, 190, "bbl_bed_pei_left.svg");
  BedTextureInfo::TexturePart pei_part2(72, -11, 150,  12, "bbl_bed_pei_bottom.svg");
  BedTextureInfo::TexturePart pte_part1( 6,  40,  12, 200, "bbl_bed_pte_left.svg");
  BedTextureInfo::TexturePart pte_part2(72, -11, 150,  12, "bbl_bed_pte_bottom.svg");
  bed_texture_info[btPC].parts.push_back(pc_part1);
  bed_texture_info[btPC].parts.push_back(pc_part2);
  bed_texture_info[btEP].parts.push_back(ep_part1);
  bed_texture_info[btEP].parts.push_back(ep_part2);
  bed_texture_info[btPEI].parts.push_back(pei_part1);
  bed_texture_info[btPEI].parts.push_back(pei_part2);
  bed_texture_info[btPTE].parts.push_back(pte_part1);
  bed_texture_info[btPTE].parts.push_back(pte_part2);
  for (int i = 0; i < btCount; i++) {
    for (int j = 0; j < bed_texture_info[i].parts.size(); j++) {
      bed_texture_info[i].parts[j].update_buffer();
    }
  }
}
References bed_texture_info, Slic3r::btCount, Slic3r::btEP, Slic3r::btPC, Slic3r::btPEI, Slic3r::btPTE, and Slic3r::GUI::PartPlateList::BedTextureInfo::parts.
Referenced by load_bedtype_textures().
init_cali_texture_info()
void Slic3r::GUI::PartPlateList::init_cali_texture_info ()
{
  BedTextureInfo::TexturePart cali_line(18, 2, 224, 16, "bbl_cali_lines.svg");
  cali_texture_info.parts.push_back(cali_line);
  for (int j = 0; j < cali_texture_info.parts.size(); j++) {
    cali_texture_info.parts[j].update_buffer();
  }
}
References cali_texture_info, and Slic3r::GUI::PartPlateList::BedTextureInfo::parts.
Referenced by load_cali_textures().
intersects()
bool Slic3r::GUI::PartPlateList::intersects (const BoundingBoxf3 & bb)
{
  bool result = false;
  std::vector<PartPlate*>::iterator it = m_plate_list.begin();
  for (it = m_plate_list.begin(); it != m_plate_list.end(); it++) {
    if ((*it)->intersects(bb)) {
      result = true;
    }
  }
  return result;
}
References m_plate_list.
invalid_all_slice_result()
void Slic3r::GUI::PartPlateList::invalid_all_slice_result ()
{
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": plates count %1%") % m_plate_list.size();
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    m_plate_list[i]->update_slice_result_valid_state(false);
  }
  return;
}
References int, and m_plate_list.
is_all_plates_ready_for_slice()
bool Slic3r::GUI::PartPlateList::is_all_plates_ready_for_slice () const
{
    for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    if (m_plate_list[i]->can_slice())
      return true;
  }
  return false;
}
References int, and m_plate_list.
is_all_slice_results_ready_for_print()
bool Slic3r::GUI::PartPlateList::is_all_slice_results_ready_for_print () const
{
    bool res = false;
    for (unsigned int i = 0; i < (unsigned int) m_plate_list.size(); ++i) {
        if (!m_plate_list[i]->empty()) {
            if (m_plate_list[i]->is_all_instances_unprintable()) {
        continue;
      }
            if (!m_plate_list[i]->is_slice_result_ready_for_print()) {
        return false;
      }
        }
        if (m_plate_list[i]->is_slice_result_ready_for_print()) {
      res = true;
    }
    }
    return res;
}
References Slic3r::empty(), int, and m_plate_list.
Referenced by Slic3r::GUI::MainFrame::can_export_all_gcode(), and Slic3r::GUI::MainFrame::get_enable_print_status().
is_all_slice_results_valid()
bool Slic3r::GUI::PartPlateList::is_all_slice_results_valid () const
{
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    if (!m_plate_list[i]->is_slice_result_valid())
      return false;
  }
  return true;
}
References int, and m_plate_list.
is_locked()
bool Slic3r::GUI::PartPlateList::is_locked (int index) inline
{ return m_plate_list[index]->is_locked();}
References m_plate_list.
Referenced by postprocess_bed_index_for_selected(), postprocess_bed_index_for_unselected(), Slic3r::GUI::OrientJob::prepare_selection(), preprocess_arrange_polygon(), and rebuild_plates_after_arrangement().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
load_bedtype_textures()
void Slic3r::GUI::PartPlateList::load_bedtype_textures ()
{
  if (PartPlateList::is_load_bedtype_textures) return;
  init_bed_type_info();
  GLint max_tex_size = OpenGLManager::get_gl_info().get_max_tex_size();
  GLint logo_tex_size = (max_tex_size < 2048) ? max_tex_size : 2048;
  for (int i = 0; i < (unsigned int)btCount; ++i) {
    for (int j = 0; j < bed_texture_info[i].parts.size(); j++) {
      std::string filename = resources_dir() + "/images/" + bed_texture_info[i].parts[j].filename;
      if (boost::filesystem::exists(filename)) {
        PartPlateList::bed_texture_info[i].parts[j].texture = new GLTexture();
        if (!PartPlateList::bed_texture_info[i].parts[j].texture->load_from_svg_file(filename, true, true, true, logo_tex_size)) {
          BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": load logo texture from %1% failed!") % filename;
        }
      } else {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": load logo texture from %1% failed!") % filename;
      }
    }
  }
  PartPlateList::is_load_bedtype_textures = true;
}
References bed_texture_info, Slic3r::btCount, Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::get_max_tex_size(), init_bed_type_info(), int, is_load_bedtype_textures, Slic3r::GUI::PartPlateList::BedTextureInfo::parts, and Slic3r::resources_dir().
Referenced by Slic3r::GUI::PartPlate::render_logo().
load_cali_textures()
void Slic3r::GUI::PartPlateList::load_cali_textures ()
{
  if (PartPlateList::is_load_cali_texture) return;
  init_cali_texture_info();
  GLint max_tex_size = OpenGLManager::get_gl_info().get_max_tex_size();
  GLint logo_tex_size = (max_tex_size < 2048) ? max_tex_size : 2048;
  for (int i = 0; i < (unsigned int)btCount; ++i) {
    for (int j = 0; j < cali_texture_info.parts.size(); j++) {
      std::string filename = resources_dir() + "/images/" + cali_texture_info.parts[j].filename;
      if (boost::filesystem::exists(filename)) {
        PartPlateList::cali_texture_info.parts[j].texture = new GLTexture();
        if (!PartPlateList::cali_texture_info.parts[j].texture->load_from_svg_file(filename, true, true, true, logo_tex_size)) {
          BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": load cali texture from %1% failed!") % filename;
        }
      }
      else {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": load cali texture from %1% failed!") % filename;
      }
    }
  }
  PartPlateList::is_load_cali_texture = true;
}
References Slic3r::btCount, cali_texture_info, Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::get_max_tex_size(), init_cali_texture_info(), int, is_load_cali_texture, Slic3r::GUI::PartPlateList::BedTextureInfo::parts, and Slic3r::resources_dir().
Referenced by Slic3r::GUI::PartPlate::render_logo().
load_from_3mf_structure()
int Slic3r::GUI::PartPlateList::load_from_3mf_structure (PlateDataPtrs & plate_data_list)
{
  int ret = 0;
  if (plate_data_list.size() <= 0)
  {
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":no plates, should not happen!");
    return -1;
  }
  clear(true, true);
  for (unsigned int i = 0; i < (unsigned int)plate_data_list.size(); ++i)
  {
    int index = create_plate(false);
    m_plate_list[index]->m_locked = plate_data_list[i]->locked;
    m_plate_list[index]->config()->apply(plate_data_list[i]->config);
    m_plate_list[index]->set_plate_name(plate_data_list[i]->plate_name);
    if (plate_data_list[i]->plate_index != index)
    {
      BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":plate index %1% seems invalid, skip it")% plate_data_list[i]->plate_index;
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1%, gcode_file %2%, is_sliced_valid %3%, toolpath_outside %4%, is_support_used %5% is_label_object_enabled %6%")
      %i %plate_data_list[i]->gcode_file %plate_data_list[i]->is_sliced_valid %plate_data_list[i]->toolpath_outside %plate_data_list[i]->is_support_used %plate_data_list[i]->is_label_object_enabled;
    //load object and instance from 3mf
    //just test for file correct or not, we will rebuild later
    /*for (std::vector<std::pair<int, int>>::iterator it = plate_data_list[i]->objects_and_instances.begin(); it != plate_data_list[i]->objects_and_instances.end(); ++it)
      m_plate_list[index]->obj_to_instance_set.insert(std::pair(it->first, it->second));*/
    if (!plate_data_list[i]->gcode_file.empty()) {
      m_plate_list[index]->m_gcode_path_from_3mf = plate_data_list[i]->gcode_file;
    }
    GCodeResult* gcode_result = nullptr;
    PrintBase* fff_print = nullptr;
    m_plate_list[index]->get_print(&fff_print, &gcode_result, nullptr);
    PrintStatistics& ps = (dynamic_cast<Print*>(fff_print))->print_statistics();
    gcode_result->print_statistics.modes[static_cast<size_t>(PrintEstimatedStatistics::ETimeMode::Normal)].time = atoi(plate_data_list[i]->gcode_prediction.c_str());
    ps.total_weight = atof(plate_data_list[i]->gcode_weight.c_str());
    ps.total_used_filament = 0.f;
    for (auto filament_item: plate_data_list[i]->slice_filaments_info)
    {
      ps.total_used_filament += filament_item.used_m;
    }
    ps.total_used_filament *= 1000; //koef
    gcode_result->toolpath_outside = plate_data_list[i]->toolpath_outside;
    gcode_result->label_object_enabled = plate_data_list[i]->is_label_object_enabled;
    m_plate_list[index]->slice_filaments_info = plate_data_list[i]->slice_filaments_info;
    gcode_result->warnings = plate_data_list[i]->warnings;
    if (m_plater && !plate_data_list[i]->thumbnail_file.empty()) {
      BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1%, load thumbnail from %2%.")%(i+1) %plate_data_list[i]->thumbnail_file;
      if (boost::filesystem::exists(plate_data_list[i]->thumbnail_file)) {
        m_plate_list[index]->load_thumbnail_data(plate_data_list[i]->thumbnail_file, m_plate_list[index]->thumbnail_data);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ <<boost::format(": plate %1% after load, width %2%, height %3%, size %4%!")
          %(i+1) %m_plate_list[index]->thumbnail_data.width %m_plate_list[index]->thumbnail_data.height %m_plate_list[index]->thumbnail_data.pixels.size();
      }
    }
    /*if (m_plater && !plate_data_list[i]->pattern_file.empty()) {
      if (boost::filesystem::exists(plate_data_list[i]->pattern_file)) {
        //no need to load pattern data currently
        //m_plate_list[index]->load_pattern_thumbnail_data(plate_data_list[i]->pattern_file);
      }
    }*/
    if (m_plater && !plate_data_list[i]->top_file.empty()) {
      if (boost::filesystem::exists(plate_data_list[i]->top_file)) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1%, load top_thumbnail from %2%.")%(i+1) %plate_data_list[i]->top_file;
        m_plate_list[index]->load_thumbnail_data(plate_data_list[i]->top_file, m_plate_list[index]->top_thumbnail_data);
      }
    }
    if (m_plater && !plate_data_list[i]->pick_file.empty()) {
      if (boost::filesystem::exists(plate_data_list[i]->pick_file)) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1%, load pick_thumbnail from %2%.")%(i+1) %plate_data_list[i]->pick_file;
        m_plate_list[index]->load_thumbnail_data(plate_data_list[i]->pick_file, m_plate_list[index]->pick_thumbnail_data);
      }
    }
    if (m_plater && !plate_data_list[i]->pattern_bbox_file.empty()) {
      if (boost::filesystem::exists(plate_data_list[i]->pattern_bbox_file)) {
        m_plate_list[index]->load_pattern_box_data(plate_data_list[i]->pattern_bbox_file);
      }
    }
  }
  print();
  ret = reload_all_objects();
  print();
  return ret;
}
References clear(), create_plate(), error, int, Slic3r::GCodeProcessorResult::label_object_enabled, m_plate_list, m_plater, Slic3r::PrintEstimatedStatistics::modes, Slic3r::PrintEstimatedStatistics::Normal, print(), Slic3r::GCodeProcessorResult::print_statistics, reload_all_objects(), Slic3r::GCodeProcessorResult::toolpath_outside, Slic3r::PrintStatistics::total_used_filament, Slic3r::PrintStatistics::total_weight, and Slic3r::GCodeProcessorResult::warnings.
Referenced by Slic3r::CLI::run().
load_gcode_files()
int Slic3r::GUI::PartPlateList::load_gcode_files ()
{
  int ret = 0;
  //only do this while m_plater valid for gui mode
  if (!m_plater)
    return ret;
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    if (!m_plate_list[i]->m_gcode_path_from_3mf.empty()) {
      //the same as plater::priv::update_print_volume_state();
      //BoundingBoxf3   print_volume = m_plate_list[i]->get_bounding_box(false);
      //print_volume.max(2) = this->m_plate_height;
      //print_volume.min(2) = -1e10;
      m_model->update_print_volume_state({m_plate_list[i]->get_shape(), (double)this->m_plate_height });
      if (!m_plate_list[i]->load_gcode_from_file(m_plate_list[i]->m_gcode_path_from_3mf))
        ret ++;
    }
  }
  BOOST_LOG_TRIVIAL(trace) << boost::format("totally got %1% gcode files") % ret;
  return ret;
}
References int, m_model, m_plate_height, m_plate_list, m_plater, Slic3r::trace(), and Slic3r::Model::update_print_volume_state().
lock_plate()
int Slic3r::GUI::PartPlateList::lock_plate (int index, bool state)
{
  int ret = 0;
  PartPlate* plate = NULL;
  plate = get_plate(index);
  if (!plate)
  {
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":can not get plate for index %1%, size %2%") % index % m_plate_list.size();
    return -1;
  }
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":lock plate %1%, to state %2%") % index % state;
  plate->lock(state);
  return ret;
}
References error, get_plate(), Slic3r::GUI::PartPlate::lock(), m_plate_list, and NULL.
move_plate_to_index()
int Slic3r::GUI::PartPlateList::move_plate_to_index (int old_index, int new_index)
{
  int ret = 0, delta;
  Vec3d origin;
  if (old_index == new_index)
  {
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(":should not happen, the same index %1%") % old_index;
    return -1;
  }
  if (old_index < new_index)
  {
    delta = 1;
  }
  else
  {
    delta = -1;
  }
  PartPlate* plate = m_plate_list[old_index];
  //update the plates between old_index and new_index
  for (unsigned int i = (unsigned int)old_index; i != (unsigned int)new_index; i = i + delta)
  {
    m_plate_list[i] = m_plate_list[i + delta];
    m_plate_list[i]->set_index(i);
    origin = compute_origin(i, m_plate_cols);
    m_plate_list[i]->set_pos_and_size(origin, m_plate_width, m_plate_depth, m_plate_height, true);
  }
  origin = compute_origin(new_index, m_plate_cols);
  m_plate_list[new_index] = plate;
  plate->set_index(new_index);
  plate->set_pos_and_size(origin, m_plate_width, m_plate_depth, m_plate_height, true);
  //update the new plate index
  m_current_plate = new_index;
  return ret;
}
References compute_origin(), int, m_current_plate, m_plate_cols, m_plate_depth, m_plate_height, m_plate_list, m_plate_width, Slic3r::GUI::PartPlate::set_index(), and Slic3r::GUI::PartPlate::set_pos_and_size().
notify_instance_removed()
int Slic3r::GUI::PartPlateList::notify_instance_removed (int obj_id, int instance_id)
{
  int ret = 0, index, instance_to_delete = instance_id;
  PartPlate* plate = NULL;
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": obj_id %1%, instance_id %2%") % obj_id % instance_id;
  if (instance_id == -1) {
    instance_to_delete = 0;
  }
  index = find_instance(obj_id, instance_to_delete);
  if (index != -1)
  {
    //found it added before
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found it in plate %1%, remove it") % index;
    plate = m_plate_list[index];
    plate->remove_instance(obj_id, instance_to_delete);
    plate->update_slice_result_valid_state();
    plate->thumbnail_data.reset();
    plate->top_thumbnail_data.reset();
    plate->pick_thumbnail_data.reset();
  }
  if (unprintable_plate.contain_instance(obj_id, instance_to_delete))
  {
    //found in unprintable plate, add it to plate
    unprintable_plate.remove_instance(obj_id, instance_to_delete);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found it in unprintable plate, remove it");
  }
  if (instance_id == -1) {
    //update all the obj_ids which is bigger
    for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
    {
      PartPlate* plate = m_plate_list[i];
      assert(plate != NULL);
      plate->update_object_index(obj_id, m_model->objects.size());
    }
    unprintable_plate.update_object_index(obj_id, m_model->objects.size());
  }
  return 0;
}
References Slic3r::GUI::PartPlate::contain_instance(), find_instance(), int, m_model, m_plate_list, NULL, Slic3r::Model::objects, Slic3r::GUI::PartPlate::pick_thumbnail_data, Slic3r::GUI::PartPlate::remove_instance(), Slic3r::ThumbnailData::reset(), Slic3r::GUI::PartPlate::thumbnail_data, Slic3r::GUI::PartPlate::top_thumbnail_data, unprintable_plate, Slic3r::GUI::PartPlate::update_object_index(), and Slic3r::GUI::PartPlate::update_slice_result_valid_state().
notify_instance_update()
int Slic3r::GUI::PartPlateList::notify_instance_update (int obj_id, int instance_id)
{
  int ret = 0, index;
  PartPlate* plate = NULL;
  ModelObject* object = NULL;
  if ((obj_id >= 0) && (obj_id < m_model->objects.size()))
  {
    object = m_model->objects[obj_id];
  }
  else if (obj_id >= 1000 && obj_id < 1000 + m_plate_count) {
    //wipe tower updates
    PartPlate* plate = m_plate_list[obj_id - 1000];
    plate->update_slice_result_valid_state( false );
    plate->thumbnail_data.reset();
    plate->top_thumbnail_data.reset();
    plate->pick_thumbnail_data.reset();
    return 0;
  }
    else
    return -1;
  BoundingBoxf3 boundingbox = object->instance_convex_hull_bounding_box(instance_id);
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": obj_id %1%, instance_id %2%") % obj_id % instance_id;
  index = find_instance(obj_id, instance_id);
  if (index != -1)
  {
    //found it added before
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found it in previous plate %1%") % index;
    plate = m_plate_list[index];
    if (!plate->intersect_instance(obj_id, instance_id, &boundingbox))
    {
      //not include anymore, remove it from original plate
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": not in plate %1% anymore, remove it") % index;
      plate->remove_instance(obj_id, instance_id);
    }
    else
    {
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": still in original plate %1%, no need to be updated") % index;
      plate->update_instance_exclude_status(obj_id, instance_id, &boundingbox);
      plate->update_states();
      plate->update_slice_result_valid_state();
      plate->thumbnail_data.reset();
      plate->top_thumbnail_data.reset();
      plate->pick_thumbnail_data.reset();
      return 0;
    }
    plate->update_slice_result_valid_state();
    plate->thumbnail_data.reset();
    plate->top_thumbnail_data.reset();
    plate->pick_thumbnail_data.reset();
  }
  else if (unprintable_plate.contain_instance(obj_id, instance_id))
  {
    //found it in the unprintable plate
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found it in unprintable plate");
    if (!unprintable_plate.intersect_instance(obj_id, instance_id, &boundingbox))
    {
      //not include anymore, remove it from original plate
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": not in unprintable plate anymore, remove it");
      unprintable_plate.remove_instance(obj_id, instance_id);
    }
    else
    {
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": still in unprintable plate, no need to be updated");
      return 0;
    }
  }
  //try to find a new plate
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    assert(plate != NULL);
    if (plate->intersect_instance(obj_id, instance_id, &boundingbox))
    {
      //found a new plate, add it to plate
      plate->add_instance(obj_id, instance_id, false, &boundingbox);
      plate->update_slice_result_valid_state();
      plate->thumbnail_data.reset();
      plate->top_thumbnail_data.reset();
      plate->pick_thumbnail_data.reset();
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": add it to new plate %1%") % i;
      return 0;
    }
  }
  if (unprintable_plate.intersect_instance(obj_id, instance_id, &boundingbox))
  {
    //found in unprintable plate, add it to plate
    unprintable_plate.add_instance(obj_id, instance_id, false, &boundingbox);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": add it to unprintable plate");
    return 0;
  }
  return 0;
}
References Slic3r::GUI::PartPlate::add_instance(), Slic3r::GUI::PartPlate::contain_instance(), find_instance(), int, Slic3r::GUI::PartPlate::intersect_instance(), m_model, m_plate_count, m_plate_list, NULL, Slic3r::Model::objects, Slic3r::GUI::PartPlate::pick_thumbnail_data, Slic3r::GUI::PartPlate::remove_instance(), Slic3r::ThumbnailData::reset(), Slic3r::GUI::PartPlate::thumbnail_data, Slic3r::GUI::PartPlate::top_thumbnail_data, unprintable_plate, Slic3r::GUI::PartPlate::update_instance_exclude_status(), Slic3r::GUI::PartPlate::update_slice_result_valid_state(), and Slic3r::GUI::PartPlate::update_states().
Referenced by Slic3r::GUI::ObjectList::add_object_to_list(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::ObjectList::fix_through_netfabb(), Slic3r::GUI::Selection::notify_instance_update(), and Slic3r::GUI::ObjectList::notify_instance_updated().
on_change_color_mode()
void Slic3r::GUI::PartPlateList::on_change_color_mode (bool is_dark) inline
{ m_is_dark = is_dark; }
References m_is_dark.
plate_stride_x()
double Slic3r::GUI::PartPlateList::plate_stride_x ()
{
  //const auto plate_shape = Slic3r::Polygon::new_scale(m_shape);
  //double plate_width = plate_shape.bounding_box().size().x();
  //return unscaled<double>((1. + LOGICAL_PART_PLATE_GAP) * plate_width);
  return m_plate_width * (1. + LOGICAL_PART_PLATE_GAP);
}
References LOGICAL_PART_PLATE_GAP, and m_plate_width.
Referenced by compute_plate_index(), compute_shape_position(), postprocess_arrange_polygon(), preprocess_arrange_polygon(), preprocess_arrange_polygon_other_locked(), Slic3r::CLI::run(), and set_shapes().
plate_stride_y()
double Slic3r::GUI::PartPlateList::plate_stride_y ()
{
  //const auto plate_shape = Slic3r::Polygon::new_scale(m_shape);
  //double plate_depth = plate_shape.bounding_box().size().y();
  //return unscaled<double>((1. + LOGICAL_PART_PLATE_GAP) * plate_depth);
  return m_plate_depth * (1. + LOGICAL_PART_PLATE_GAP);
}
References LOGICAL_PART_PLATE_GAP, and m_plate_depth.
Referenced by compute_plate_index(), compute_shape_position(), postprocess_arrange_polygon(), preprocess_arrange_polygon(), preprocess_arrange_polygon_other_locked(), and set_shapes().
postprocess_arrange_polygon()
void Slic3r::GUI::PartPlateList::postprocess_arrange_polygon (arrangement::ArrangePolygon & arrange_polygon, bool selected)
{
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": bed_idx %1%, selected %2%, translation(x) %3%, (y) %4%") % arrange_polygon.bed_idx % selected % unscale<double>(arrange_polygon.translation(X)) % unscale<double>(arrange_polygon.translation(Y));
  if ((selected) || (arrange_polygon.bed_idx != PartPlateList::MAX_PLATES_COUNT))
  {
    if (arrange_polygon.bed_idx == -1)
    {
      // outarea for large object
      arrange_polygon.bed_idx = m_plate_list.size();
      BoundingBox apbox = get_extents(arrange_polygon.poly);
      auto        apbox_size = apbox.size();
      //arrange_polygon.translation(X) = scaled<double>(0.5 * plate_stride_x());
      //arrange_polygon.translation(Y) = scaled<double>(0.5 * plate_stride_y());
      arrange_polygon.translation(X) = 0.5 * apbox_size[0];
      arrange_polygon.translation(Y) = scaled<double>(static_cast<double>(m_plate_depth)) - 0.5 * apbox_size[1];
    }
    arrange_polygon.row = arrange_polygon.bed_idx / m_plate_cols;
    arrange_polygon.col = arrange_polygon.bed_idx % m_plate_cols;
    arrange_polygon.translation(X) += scaled<double>(plate_stride_x() * arrange_polygon.col);
    arrange_polygon.translation(Y) -= scaled<double>(plate_stride_y() * arrange_polygon.row);
  }
  return;
}
References Slic3r::arrangement::ArrangePolygon::bed_idx, Slic3r::arrangement::ArrangePolygon::col, Slic3r::get_extents(), m_plate_cols, m_plate_depth, m_plate_list, MAX_PLATES_COUNT, plate_stride_x(), plate_stride_y(), Slic3r::arrangement::ArrangePolygon::poly, Slic3r::arrangement::ArrangePolygon::row, Slic3r::BoundingBoxBase< PointClass >::size(), Slic3r::arrangement::ArrangePolygon::translation, Slic3r::X, and Slic3r::Y.
Referenced by Slic3r::GUI::ArrangeJob::finalize(), and Slic3r::CLI::run().
postprocess_bed_index_for_current_plate()
void Slic3r::GUI::PartPlateList::postprocess_bed_index_for_current_plate (arrangement::ArrangePolygon & arrange_polygon)
{
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": bed_idx %1%, locked_plate %2%, translation(x) %3%, (y) %4%") % arrange_polygon.bed_idx % arrange_polygon.locked_plate % unscale<double>(arrange_polygon.translation(X)) % unscale<double>(arrange_polygon.translation(Y));
  if (arrange_polygon.bed_idx == -1)
  {
    //outarea for large object
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": can not be arranged inside plate!");
  }
  else if (arrange_polygon.bed_idx == 0)
    arrange_polygon.bed_idx += m_current_plate;
  else
    arrange_polygon.bed_idx = m_plate_list.size();
  return;
}
References Slic3r::arrangement::ArrangePolygon::bed_idx, Slic3r::arrangement::ArrangePolygon::locked_plate, m_current_plate, m_plate_list, Slic3r::arrangement::ArrangePolygon::translation, Slic3r::X, and Slic3r::Y.
Referenced by Slic3r::GUI::ArrangeJob::finalize().
postprocess_bed_index_for_selected()
void Slic3r::GUI::PartPlateList::postprocess_bed_index_for_selected (arrangement::ArrangePolygon & arrange_polygon)
{
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": bed_idx %1%, locked_plate %2%, translation(x) %3%, (y) %4%") % arrange_polygon.bed_idx % arrange_polygon.locked_plate % unscale<double>(arrange_polygon.translation(X)) % unscale<double>(arrange_polygon.translation(Y));
  if (arrange_polygon.bed_idx == -1)
  {
    //outarea for large object, can not process here for the plate number maybe increased later
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": can not be arranged inside plate!");
    return;
  }
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    if (m_plate_list[i]->is_locked())
    {
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found locked_plate %1%, increate index by 1") % i;
      //arrange_polygon.translation(X) += scaled<double>(plate_stride_x());
      arrange_polygon.bed_idx += 1;
      //offset_x += scaled<double>(plate_stride_x());
    }
    else
    {
      //judge whether it is at the left side of the plate border
      if (arrange_polygon.bed_idx <= i)
      {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":found in plate_index %1%, bed_idx %2%") % i % arrange_polygon.bed_idx;
        return;
      }
    }
  }
  //create a new plate which can hold this arrange_polygon
  int plate_index = create_plate(false);
  while (plate_index != -1)
  {
    if (arrange_polygon.bed_idx <= plate_index)
    {
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":new plate_index %1%, matches bed_idx %2%") % plate_index % arrange_polygon.bed_idx;
      break;
    }
    plate_index = create_plate(false);
  }
  return;
}
References Slic3r::arrangement::ArrangePolygon::bed_idx, create_plate(), int, is_locked(), Slic3r::arrangement::ArrangePolygon::locked_plate, m_plate_list, Slic3r::arrangement::ArrangePolygon::translation, Slic3r::X, and Slic3r::Y.
Referenced by Slic3r::GUI::ArrangeJob::finalize(), and Slic3r::CLI::run().
postprocess_bed_index_for_unselected()
void Slic3r::GUI::PartPlateList::postprocess_bed_index_for_unselected (arrangement::ArrangePolygon & arrange_polygon)
{
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": bed_idx %1%, locked_plate %2%, translation(x) %3%, (y) %4%") % arrange_polygon.bed_idx % arrange_polygon.locked_plate % unscale<double>(arrange_polygon.translation(X)) % unscale<double>(arrange_polygon.translation(Y));
  if (arrange_polygon.bed_idx == PartPlateList::MAX_PLATES_COUNT)
    return;
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    if (m_plate_list[i]->is_locked())
    {
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found locked_plate %1%, increate index by 1") % i;
      //arrange_polygon.translation(X) += scaled<double>(plate_stride_x());
      arrange_polygon.bed_idx += 1;
      //offset_x += scaled<double>(plate_stride_x());
    }
    else
    {
      //judge whether it is at the left side of the plate border
      if (arrange_polygon.bed_idx <= i)
      {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":found in plate_index %1%, bed_idx %2%") % i % arrange_polygon.bed_idx;
        return;
      }
    }
  }
  return;
}
References Slic3r::arrangement::ArrangePolygon::bed_idx, int, is_locked(), Slic3r::arrangement::ArrangePolygon::locked_plate, m_plate_list, MAX_PLATES_COUNT, Slic3r::arrangement::ArrangePolygon::translation, Slic3r::X, and Slic3r::Y.
Referenced by Slic3r::GUI::ArrangeJob::finalize().
preprocess_arrange_polygon()
bool Slic3r::GUI::PartPlateList::preprocess_arrange_polygon (int obj_index, int instance_index, arrangement::ArrangePolygon & arrange_polygon, bool selected)
{
  bool locked = false;
  int lockplate_cnt = 0;
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    if (m_plate_list[i]->contain_instance(obj_index, instance_index))
    {
      if (m_plate_list[i]->is_locked())
      {
        locked = true;
        arrange_polygon.bed_idx = i;
        arrange_polygon.row = i / m_plate_cols;
        arrange_polygon.col = i % m_plate_cols;
        arrange_polygon.translation(X) -= scaled<double>(plate_stride_x() * arrange_polygon.col);
        arrange_polygon.translation(Y) += scaled<double>(plate_stride_y() * arrange_polygon.row);
      }
      else
      {
        if (!selected)
        {
          //will be treated as fixeditem later
          arrange_polygon.bed_idx = i - lockplate_cnt;
          arrange_polygon.row = i / m_plate_cols;
          arrange_polygon.col = i % m_plate_cols;
          arrange_polygon.translation(X) -= scaled<double>(plate_stride_x() * arrange_polygon.col);
          arrange_polygon.translation(Y) += scaled<double>(plate_stride_y() * arrange_polygon.row);
        }
      }
      BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": obj_id %1% instance_id %2% already in plate %3%, locked %4%, row %5%, col %6%\n") % obj_index % instance_index % i % locked % arrange_polygon.row % arrange_polygon.col;
      return locked;
    }
    if (m_plate_list[i]->is_locked())
      lockplate_cnt++;
  }
  //not be contained by any plates
  if (!selected)
    arrange_polygon.bed_idx = PartPlateList::MAX_PLATES_COUNT;
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": not in any plates, bed_idx %1%, translation(x) %2%, (y) %3%") % arrange_polygon.bed_idx % unscale<double>(arrange_polygon.translation(X)) % unscale<double>(arrange_polygon.translation(Y));
  return locked;
}
References Slic3r::arrangement::ArrangePolygon::bed_idx, Slic3r::arrangement::ArrangePolygon::col, int, is_locked(), m_plate_cols, m_plate_list, MAX_PLATES_COUNT, plate_stride_x(), plate_stride_y(), Slic3r::arrangement::ArrangePolygon::row, Slic3r::arrangement::ArrangePolygon::translation, Slic3r::X, and Slic3r::Y.
Referenced by Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_selected(), and Slic3r::CLI::run().
preprocess_arrange_polygon_other_locked()
bool Slic3r::GUI::PartPlateList::preprocess_arrange_polygon_other_locked (int obj_index, int instance_index, arrangement::ArrangePolygon & arrange_polygon, bool selected)
{
  bool locked = false;
  if (selected)
  {
    //arrange_polygon.translation(X) -= scaled<double>(plate_stride_x() * m_current_plate);
  }
  else
  {
    locked = true;
    for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
    {
      if (m_plate_list[i]->contain_instance(obj_index, instance_index))
      {
        arrange_polygon.bed_idx = i;
        arrange_polygon.row = i / m_plate_cols;
        arrange_polygon.col = i % m_plate_cols;
        arrange_polygon.translation(X) -= scaled<double>(plate_stride_x() * arrange_polygon.col);
        arrange_polygon.translation(Y) += scaled<double>(plate_stride_y() * arrange_polygon.row);
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": obj_id %1% instance_id %2% in plate %3%, locked %4%, row %5%, col %6%\n") % obj_index % instance_index % i % locked % arrange_polygon.row % arrange_polygon.col;
        return locked;
      }
    }
    arrange_polygon.bed_idx = PartPlateList::MAX_PLATES_COUNT;
  }
  return locked;
}
References Slic3r::arrangement::ArrangePolygon::bed_idx, Slic3r::arrangement::ArrangePolygon::col, int, m_plate_cols, m_plate_list, MAX_PLATES_COUNT, plate_stride_x(), plate_stride_y(), Slic3r::arrangement::ArrangePolygon::row, Slic3r::arrangement::ArrangePolygon::translation, Slic3r::X, and Slic3r::Y.
Referenced by Slic3r::GUI::ArrangeJob::prepare_partplate().
preprocess_exclude_areas()
bool Slic3r::GUI::PartPlateList::preprocess_exclude_areas (arrangement::ArrangePolygons & unselected, int num_plates = 16, float inflation = 0)
{
  bool added = false;
  if (m_exclude_areas.size() > 0)
  {
    //has exclude areas
    PartPlate *plate = m_plate_list[0];
    for (int index = 0; index < plate->m_exclude_bounding_box.size(); index ++)
    {
      Polygon ap({
        {scaled(plate->m_exclude_bounding_box[index].min.x()), scaled(plate->m_exclude_bounding_box[index].min.y())},
        {scaled(plate->m_exclude_bounding_box[index].max.x()), scaled(plate->m_exclude_bounding_box[index].min.y())},
        {scaled(plate->m_exclude_bounding_box[index].max.x()), scaled(plate->m_exclude_bounding_box[index].max.y())},
        {scaled(plate->m_exclude_bounding_box[index].min.x()), scaled(plate->m_exclude_bounding_box[index].max.y())}
        });
      for (int j = 0; j < num_plates; j++)
      {
        arrangement::ArrangePolygon ret;
        ret.poly.contour = ap;
        ret.translation  = Vec2crd(0, 0);
        ret.rotation     = 0.0f;
        ret.is_virt_object = true;
        ret.bed_idx      = j;
        ret.height      = 1;
        ret.name = "ExcludedRegion" + std::to_string(index);
        ret.inflation = inflation;
        unselected.emplace_back(std::move(ret));
      }
      added = true;
    }
  }
  return added;
}
References Slic3r::arrangement::ArrangePolygon::bed_idx, Slic3r::ExPolygon::contour, Slic3r::arrangement::ArrangePolygon::height, Slic3r::arrangement::ArrangePolygon::inflation, Slic3r::arrangement::ArrangePolygon::is_virt_object, m_exclude_areas, Slic3r::GUI::PartPlate::m_exclude_bounding_box, m_plate_list, Slic3r::arrangement::ArrangePolygon::name, Slic3r::arrangement::ArrangePolygon::poly, Slic3r::arrangement::ArrangePolygon::rotation, Slic3r::scaled(), and Slic3r::arrangement::ArrangePolygon::translation.
Referenced by Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), and Slic3r::CLI::run().
preprocess_nonprefered_areas()
bool Slic3r::GUI::PartPlateList::preprocess_nonprefered_areas (arrangement::ArrangePolygons & regions, int num_plates = 1, float inflation = 0)
{
  bool added = false;
  std::vector<BoundingBoxf> nonprefered_regions;
  nonprefered_regions.emplace_back(Vec2d{ 18,0 }, Vec2d{ 240,15 }); // new extrusion & hand-eye calibration region
  //has exclude areas
  PartPlate* plate = m_plate_list[0];
  for (int index = 0; index < nonprefered_regions.size(); index++)
  {
    Polygon ap = scaled(nonprefered_regions[index]).polygon();
    for (int j = 0; j < num_plates; j++)
    {
      arrangement::ArrangePolygon ret;
      ret.poly.contour = ap;
      ret.translation = Vec2crd(0, 0);
      ret.rotation = 0.0f;
      ret.is_virt_object = true;
            ret.is_extrusion_cali_object = true;
      ret.bed_idx = j;
      ret.height = 1;
      ret.name = "NonpreferedRegion" + std::to_string(index);
      ret.inflation = inflation;
      regions.emplace_back(std::move(ret));
    }
    added = true;
  }
  return added;
}
References Slic3r::arrangement::ArrangePolygon::bed_idx, Slic3r::ExPolygon::contour, Slic3r::arrangement::ArrangePolygon::height, Slic3r::arrangement::ArrangePolygon::inflation, Slic3r::arrangement::ArrangePolygon::is_extrusion_cali_object, Slic3r::arrangement::ArrangePolygon::is_virt_object, m_plate_list, Slic3r::arrangement::ArrangePolygon::name, Slic3r::arrangement::ArrangePolygon::poly, Slic3r::BoundingBox::polygon(), Slic3r::arrangement::ArrangePolygon::rotation, Slic3r::scaled(), and Slic3r::arrangement::ArrangePolygon::translation.
print()
void Slic3r::GUI::PartPlateList::print () const
{
  BOOST_LOG_TRIVIAL(trace) << __FUNCTION__ << boost::format("PartPlateList %1%, m_plate_count %2%, current_plate %3%, print_count %4%, current print index %5%, plate cols %6%") % this % m_plate_count % m_current_plate % m_print_list.size() % m_print_index % m_plate_cols;
  BOOST_LOG_TRIVIAL(trace) << boost::format("m_plate_width %1%, m_plate_depth %2%, m_plate_height %3%, plate count %4%\nplate list:") % m_plate_width % m_plate_depth % m_plate_height % m_plate_list.size();
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    BOOST_LOG_TRIVIAL(trace) << boost::format("the %1%th plate") % i;
    m_plate_list[i]->print();
  }
  BOOST_LOG_TRIVIAL(trace) << boost::format("the unprintable plate:");
  unprintable_plate.print();
  flush_logs();
  return;
}
References Slic3r::flush_logs(), int, m_current_plate, m_plate_cols, m_plate_count, m_plate_depth, m_plate_height, m_plate_list, m_plate_width, m_print_index, m_print_list, Slic3r::GUI::PartPlate::print(), Slic3r::trace(), and unprintable_plate.
Referenced by clear(), create_plate(), get_current_fff_print(), init(), load_from_3mf_structure(), Slic3r::UndoRedo::StackImpl::load_snapshot(), rebuild_plates_after_deserialize(), store_to_3mf_structure(), and Slic3r::UndoRedo::StackImpl::take_snapshot().
rebuild_plates_after_arrangement()
int Slic3r::GUI::PartPlateList::rebuild_plates_after_arrangement (bool recycle_plates = true, bool except_locked = false, int plate_index = -1)
{
  int ret = 0;
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":before rebuild, plates count %1%, recycle_plates %2%") % m_plate_list.size() % recycle_plates;
  // sort by arrange_order
  std::sort(m_model->objects.begin(), m_model->objects.end(), [](auto a, auto b) {return a->instances[0]->arrange_order < b->instances[0]->arrange_order; });
  //for (auto object : m_model->objects)
  //  std::sort(object->instances.begin(), object->instances.end(), [](auto a, auto b) {return a->arrange_order < b->arrange_order; });
  ret = reload_all_objects(except_locked, plate_index);
  if (recycle_plates)
  {
    for (unsigned int i = (unsigned int)m_plate_list.size() - 1; i > 0; --i)
    {
      if (m_plate_list[i]->empty()
        || !m_plate_list[i]->has_printable_instances())
      {
        //delete it
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":delete plate %1% for empty") % i;
        delete_plate(i);
      }
      else if (m_plate_list[i]->is_locked()) {
        continue;
      }
      else
      {
        break;
      }
    }
  }
#if 0
  if (m_plater != nullptr) {
    // In GUI mode
    wxGetApp().obj_list()->reload_all_plates();
  }
#endif
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":after rebuild, plates count %1%") % m_plate_list.size();
  return ret;
}
References delete_plate(), Slic3r::empty(), is_locked(), m_model, m_plate_list, m_plater, Slic3r::Model::objects, and reload_all_objects().
Referenced by Slic3r::GUI::ArrangeJob::finalize(), and Slic3r::CLI::run().
rebuild_plates_after_deserialize()
int Slic3r::GUI::PartPlateList::rebuild_plates_after_deserialize (std::vector< bool > & previous_sliced_result, std::vector< std::string > & previous_gcode_paths)
{
  int ret = 0;
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": plates count %1%") % m_plate_list.size();
  // SoftFever: assign plater info first
    for (auto partplate : m_plate_list) {
        partplate->m_plater = this->m_plater;
        partplate->m_partplate_list = this;
        partplate->m_model = this->m_model;
        partplate->printer_technology = this->printer_technology;
    }
  update_plate_cols();
  set_shapes(m_shape, m_exclude_areas, m_logo_texture_filename, m_height_to_lid, m_height_to_rod);
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    bool need_reset_print = false;
    //check the previous sliced result
    if (m_plate_list[i]->m_slice_result_valid) {
      if ((i >= previous_sliced_result.size()) || !previous_sliced_result[i])
        m_plate_list[i]->update_slice_result_valid_state(false);
    }
    if ((i < previous_gcode_paths.size())
      && !previous_gcode_paths[i].empty()
      && (m_plate_list[i]->m_tmp_gcode_path != previous_gcode_paths[i])) {
      if (boost::filesystem::exists(previous_gcode_paths[i])) {
        boost::nowide::remove(previous_gcode_paths[i].c_str());
        need_reset_print = true;
      }
    }
    std::map<int, PrintBase*>::iterator it = m_print_list.find(m_plate_list[i]->m_print_index);
    std::map<int, GCodeResult*>::iterator it2 = m_gcode_result_list.find(m_plate_list[i]->m_print_index);
    if (it != m_print_list.end())
    {
      //find it
      if (it2 == m_gcode_result_list.end())
      {
        //should not happen
        assert(0);
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(":can not find gcode result for plate %1%, print index %2%") % i % m_plate_list[i]->m_print_index;
        delete it->second;
        m_print_list.erase(it);
      }
      else
      {
        m_plate_list[i]->set_print(it->second, it2->second, m_plate_list[i]->m_print_index);
        it->second->set_plate_index(i);
        if (need_reset_print) {
          Print *print = dynamic_cast<Print*>(it->second);
          it2->second->reset();
          print->set_gcode_file_invalidated();
          if ((i == m_current_plate)&&m_plater)
            m_plater->reset_gcode_toolpaths();
        }
        continue;
      }
    }
    //can not find, create a new one
    Print* print = new Print();
    GCodeResult* gcode = new GCodeResult();
    m_print_list.emplace(m_print_index, print);
    m_gcode_result_list.emplace(m_print_index, gcode);
    m_plate_list[i]->set_print(print, gcode, m_print_index);
    print->set_plate_index(i);
    m_print_index++;
  }
  //go through the print list, and delete the one not used by plate
  std::map<int, PrintBase*>::iterator it = m_print_list.begin();
  int print_index;
  std::vector<int> delete_list;
  while (it != m_print_list.end())
  {
    print_index = it->first;
    int plate_index = find_plate_by_print_index(print_index);
    if (plate_index < 0)
    {
      delete_list.push_back(print_index);
    }
    it++;
  }
  for (unsigned int index = 0; index < delete_list.size(); index++)
  {
    destroy_print(delete_list[index]);
  }
  //update the bed's position
  Vec2d pos = compute_shape_position(m_current_plate, m_plate_cols);
  m_plater->set_bed_position(pos);
  //not used
  /*if (m_plate_width == 0)
  {
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": jump to the first init state, need to re-set size!");
    Vec3d max = m_plater->get_bed().get_bounding_box(false).max;
    Vec3d min = m_plater->get_bed().get_bounding_box(false).min;
    double z = m_plater->config()->opt_float("printable_height");
    reset_size(max.x() - min.x(), max.y() - min.y(), z);
  }*/
  return ret;
}
References compute_shape_position(), destroy_print(), error, find_plate_by_print_index(), Slic3r::GUI::gcode(), int, m_current_plate, m_exclude_areas, m_gcode_result_list, m_height_to_lid, m_height_to_rod, m_logo_texture_filename, m_model, m_plate_cols, m_plate_list, m_plater, m_print_index, m_print_list, m_shape, print(), printer_technology, Slic3r::GUI::Plater::reset_gcode_toolpaths(), Slic3r::GUI::Plater::set_bed_position(), set_shapes(), and update_plate_cols().
Referenced by Slic3r::UndoRedo::StackImpl::load_snapshot().
reinit()
void Slic3r::GUI::PartPlateList::reinit ()
{
  clear(true, true);
  init();
  //reset plate 0's position
  Vec2d pos = compute_shape_position(0, m_plate_cols);
  m_plate_list[0]->set_shape(m_shape, m_exclude_areas, pos, m_height_to_lid, m_height_to_rod);
  //reset unprintable plate's position
  Vec3d origin2 = compute_origin_for_unprintable();
  unprintable_plate.set_pos_and_size(origin2, m_plate_width, m_plate_depth, m_plate_height, false);
  //re-calc the bounding boxes
  calc_bounding_boxes();
  return;
}
References calc_bounding_boxes(), clear(), compute_origin_for_unprintable(), compute_shape_position(), init(), m_exclude_areas, m_height_to_lid, m_height_to_rod, m_plate_cols, m_plate_depth, m_plate_height, m_plate_list, m_plate_width, m_shape, Slic3r::GUI::PartPlate::set_pos_and_size(), and unprintable_plate.
release_icon_textures()
void Slic3r::GUI::PartPlateList::release_icon_textures () private
{
  m_logo_texture.reset();
  m_del_texture.reset();
  m_del_hovered_texture.reset();
  m_arrange_texture.reset();
  m_arrange_hovered_texture.reset();
  m_orient_texture.reset();
  m_orient_hovered_texture.reset();
  m_locked_texture.reset();
  m_locked_hovered_texture.reset();
  m_lockopen_texture.reset();
  m_lockopen_hovered_texture.reset();
  m_plate_settings_texture.reset();
  m_plate_settings_texture.reset();
  m_plate_settings_texture.reset();
  m_plate_settings_hovered_texture.reset();
  for (int i = 0;i < MAX_PLATE_COUNT; i++) {
    m_idx_textures[i].reset();
  }
  //reset
  PartPlateList::is_load_bedtype_textures = false;
  PartPlateList::is_load_cali_texture = false;
  for (int i = 0; i < btCount; i++) {
    for (auto& part: bed_texture_info[i].parts) {
      if (part.texture) {
        part.texture->reset();
        delete part.texture;
      }
      if (part.vbo_id != 0) {
        glsafe(::glDeleteBuffers(1, &part.vbo_id));
        part.vbo_id = 0;
      }
      if (part.buffer) {
        delete part.buffer;
      }
    }
  }
}
References bed_texture_info, Slic3r::btCount, glsafe, is_load_bedtype_textures, is_load_cali_texture, m_arrange_hovered_texture, m_arrange_texture, m_del_hovered_texture, m_del_texture, m_idx_textures, m_locked_hovered_texture, m_locked_texture, m_lockopen_hovered_texture, m_lockopen_texture, m_logo_texture, m_orient_hovered_texture, m_orient_texture, m_plate_settings_hovered_texture, m_plate_settings_texture, MAX_PLATE_COUNT, Slic3r::GUI::PartPlateList::BedTextureInfo::parts, and Slic3r::GUI::GLTexture::reset().
Referenced by ~PartPlateList().
reload_all_objects()
int Slic3r::GUI::PartPlateList::reload_all_objects (bool except_locked = false, int plate_index = -1)
{
  int ret = 0;
  unsigned int i, j, k;
  clear(false, false, except_locked, plate_index);
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": m_model->objects.size() is %1%") % m_model->objects.size();
  //try to find a new plate
  for (i = 0; i < (unsigned int)m_model->objects.size(); ++i)
  {
    ModelObject* object = m_model->objects[i];
    for (j = 0; j < (unsigned int)object->instances.size(); ++j)
    {
      ModelInstance* instance = object->instances[j];
      BoundingBoxf3 boundingbox = object->instance_convex_hull_bounding_box(j);
      for (k = 0; k < (unsigned int)m_plate_list.size(); ++k)
      {
        PartPlate* plate = m_plate_list[k];
        assert(plate != NULL);
        if (plate->intersect_instance(i, j, &boundingbox))
        {
          //found a new plate, add it to plate
          plate->add_instance(i, j, false, &boundingbox);
          BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found plate_id %1%, for obj_id %2%, instance_id %3%") % k % i % j;
          //need to judge whether this instance has an outer part
          /*if (plate->check_outside(i, j))
          {
            plate->m_ready_for_slice = false;
          }*/
          break;
        }
      }
      if ((k == m_plate_list.size()) && (unprintable_plate.intersect_instance(i, j, &boundingbox)))
      {
        //found in unprintable plate, add it to plate
        unprintable_plate.add_instance(i, j, false, &boundingbox);
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found in unprintable plate, obj_id %1%, instance_id %2%") % i % j;
      }
    }
  }
  return ret;
}
References Slic3r::GUI::PartPlate::add_instance(), clear(), int, Slic3r::GUI::PartPlate::intersect_instance(), m_model, m_plate_list, NULL, Slic3r::Model::objects, and unprintable_plate.
Referenced by load_from_3mf_structure(), Slic3r::GUI::ObjectList::OnDrop(), rebuild_plates_after_arrangement(), and reset_size().
render()
void Slic3r::GUI::PartPlateList::render (bool bottom, bool only_current = false, bool only_body = false, int hover_id = -1, bool render_cali = false)
{
  const std::lock_guard<std::mutex> local_lock(m_plates_mutex);
  std::vector<PartPlate*>::iterator it = m_plate_list.begin();
  int plate_hover_index = -1;
  int plate_hover_action = -1;
  if (hover_id != -1) {
    plate_hover_index = hover_id / PartPlate::GRABBER_COUNT;
    plate_hover_action = hover_id % PartPlate::GRABBER_COUNT;
  }
  static bool last_dark_mode_status = m_is_dark;
  if (m_is_dark != last_dark_mode_status) {
    last_dark_mode_status = m_is_dark;
    generate_icon_textures();
  }else if(m_del_texture.get_id() == 0)
    generate_icon_textures();
  for (it = m_plate_list.begin(); it != m_plate_list.end(); it++) {
    int current_index = (*it)->get_index();
    if (only_current && (current_index != m_current_plate))
      continue;
    if (current_index == m_current_plate) {
      PartPlate::HeightLimitMode height_mode = (only_current)?PartPlate::HEIGHT_LIMIT_NONE:m_height_limit_mode;
      if (plate_hover_index == current_index)
        (*it)->render(bottom, only_body, false, height_mode, plate_hover_action, render_cali);
      else
        (*it)->render(bottom, only_body, false, height_mode, -1, render_cali);
    }
    else {
      if (plate_hover_index == current_index)
        (*it)->render(bottom, only_body, false, PartPlate::HEIGHT_LIMIT_NONE, plate_hover_action, render_cali);
      else
        (*it)->render(bottom, only_body, false, PartPlate::HEIGHT_LIMIT_NONE, -1, render_cali);
    }
  }
}
References generate_icon_textures(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::PartPlate::GRABBER_COUNT, Slic3r::GUI::PartPlate::HEIGHT_LIMIT_NONE, m_current_plate, m_del_texture, m_height_limit_mode, m_is_dark, m_plate_list, and m_plates_mutex.
render_for_picking_pass()
void Slic3r::GUI::PartPlateList::render_for_picking_pass ()
{
  const std::lock_guard<std::mutex> local_lock(m_plates_mutex);
  std::vector<PartPlate*>::iterator it = m_plate_list.begin();
  for (it = m_plate_list.begin(); it != m_plate_list.end(); it++) {
    (*it)->render_for_picking();
  }
}
References m_plate_list, and m_plates_mutex.
reset()
void Slic3r::GUI::PartPlateList::reset (bool do_init)
{
  clear(true, false);
  //m_plate_list.clear();
  if (do_init)
    init();
  return;
}
References clear(), and init().
Referenced by Slic3r::UndoRedo::StackImpl::load_snapshot().
reset_hover_id()
void Slic3r::GUI::PartPlateList::reset_hover_id ()
{
  const std::lock_guard<std::mutex> local_lock(m_plates_mutex);
  std::vector<PartPlate*>::iterator it = m_plate_list.begin();
  for (it = m_plate_list.begin(); it != m_plate_list.end(); it++) {
    (*it)->set_hover_id(-1);
  }
}
References m_plate_list, and m_plates_mutex.
reset_size()
void Slic3r::GUI::PartPlateList::reset_size (int width, int depth, int height, bool reload_objects = true, bool update_shapes = false)
{
  Vec3d origin1, origin2;
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":before size: plate_width %1%, plate_depth %2%, plate_height %3%") % m_plate_width % m_plate_depth % m_plate_height;
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":after size: plate_width %1%, plate_depth %2%, plate_height %3%") % width % depth % height;
  if ((m_plate_width != width) || (m_plate_depth != depth) || (m_plate_height != height))
  {
    m_plate_width = width;
    m_plate_depth = depth;
    m_plate_height = height;
    update_all_plates_pos_and_size(false, false);
    if (update_shapes) {
      set_shapes(m_shape, m_exclude_areas, m_logo_texture_filename, m_height_to_lid, m_height_to_rod);
    }
    if (reload_objects)
      reload_all_objects();
    else
      clear(false, false, false, -1);
  }
  return;
}
References clear(), m_exclude_areas, m_height_to_lid, m_height_to_rod, m_logo_texture_filename, m_plate_depth, m_plate_height, m_plate_width, m_shape, reload_all_objects(), set_shapes(), and update_all_plates_pos_and_size().
Referenced by Slic3r::CLI::run().
select_plate()
int Slic3r::GUI::PartPlateList::select_plate (int index)
{
  const std::lock_guard<std::mutex> local_lock(m_plates_mutex);
  if (m_plate_list.empty() || index >= m_plate_list.size()) {
    return -1;
  }
  // BBS: erase unnecessary snapshot
  if (get_curr_plate_index() != index && m_intialized) {
    if (m_plater)
      m_plater->take_snapshot("select partplate!");
  }
  std::vector<PartPlate *>::iterator it = m_plate_list.begin();
  for (it = m_plate_list.begin(); it != m_plate_list.end(); it++) {
    (*it)->set_unselected();
  }
  m_current_plate = index;
  m_plate_list[m_current_plate]->set_selected();
  //BBS
  if(m_model)
    m_model->curr_plate_index = index;
  //BBS update bed origin
  if (m_intialized && m_plater) {
    Vec2d pos = compute_shape_position(index, m_plate_cols);
        m_plater->set_bed_position(pos);
    //wxQueueEvent(m_plater, new SimpleEvent(EVT_GLCANVAS_PLATE_SELECT));
  }
  return 0;
}
References compute_shape_position(), Slic3r::Model::curr_plate_index, get_curr_plate_index(), m_current_plate, m_intialized, m_model, m_plate_cols, m_plate_list, m_plater, m_plates_mutex, Slic3r::GUI::Plater::set_bed_position(), and Slic3r::GUI::Plater::take_snapshot().
Referenced by delete_plate(), init(), Slic3r::GUI::Plater::new_project(), and select_plate_by_obj().
select_plate_by_obj()
int Slic3r::GUI::PartPlateList::select_plate_by_obj (int obj_index, int instance_index)
{
  int ret = 0, index;
  PartPlate* plate = NULL;
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": obj_id %1%, instance_id %2%") % obj_index % instance_index;
  index = find_instance(obj_index, instance_index);
  if (index != -1)
  {
    //found it in plate
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found it in plate %1%") % index;
    select_plate(index);
    return 0;
  }
  return -1;
}
References find_instance(), NULL, and select_plate().
Referenced by Slic3r::GUI::FillBedJob::prepare().
select_plate_view()
void Slic3r::GUI::PartPlateList::select_plate_view ()
{
  if (m_current_plate < 0 || m_current_plate >= m_plate_list.size()) return;
  Vec3d target = m_plate_list[m_current_plate]->get_bounding_box(false).center();
  Vec3d position(target.x(), target.y(), m_plater->get_camera().get_distance());
  m_plater->get_camera().look_at(position, target, Vec3d::UnitY());
  m_plater->get_camera().select_view("topfront");
}
References Slic3r::GUI::Plater::get_camera(), Slic3r::GUI::Camera::get_distance(), Slic3r::GUI::Camera::look_at(), m_current_plate, m_plate_list, m_plater, position, and Slic3r::GUI::Camera::select_view().
serialize()
template<class Archive > void Slic3r::GUI::PartPlateList::serialize (Archive & ar) inline
    {
        //ar(cereal::base_class<ObjectBase>(this));
        ar(m_shape, m_plate_width, m_plate_depth, m_plate_height, m_height_to_lid, m_height_to_rod, m_height_limit_mode, m_plate_count, m_current_plate, m_plate_list, unprintable_plate);
        //ar(m_plate_width, m_plate_depth, m_plate_height, m_plate_count, m_current_plate);
    }
References m_current_plate, m_height_limit_mode, m_height_to_lid, m_height_to_rod, m_plate_count, m_plate_depth, m_plate_height, m_plate_list, m_plate_width, m_shape, and unprintable_plate.
set_height_limits_mode()
void Slic3r::GUI::PartPlateList::set_height_limits_mode (PartPlate::HeightLimitMode mode) inline
    {
        m_height_limit_mode = mode;
    }
References m_height_limit_mode.
set_hover_id()
void Slic3r::GUI::PartPlateList::set_hover_id (int id)
{
  int index = id / PartPlate::GRABBER_COUNT;
  int sub_hover_id = id % PartPlate::GRABBER_COUNT;
  m_plate_list[index]->set_hover_id(sub_hover_id);
}
References Slic3r::GUI::PartPlate::GRABBER_COUNT, and m_plate_list.
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_render_cali()
void Slic3r::GUI::PartPlateList::set_render_cali (bool value = true) inline
{ render_cali_logo = value; }
References render_cali_logo.
set_render_option()
void Slic3r::GUI::PartPlateList::set_render_option (bool bedtype_texture, bool plate_settings)
{
    render_bedtype_logo = bedtype_texture;
    render_plate_settings = plate_settings;
}
References render_bedtype_logo, and render_plate_settings.
set_shapes()
bool Slic3r::GUI::PartPlateList::set_shapes (const Pointfs & shape, const Pointfs & exclude_areas, const std::string & custom_texture, float height_to_lid, float height_to_rod)
{
  const std::lock_guard<std::mutex> local_lock(m_plates_mutex);
  m_shape = shape;
  m_exclude_areas = exclude_areas;
  m_height_to_lid = height_to_lid;
  m_height_to_rod = height_to_rod;
  double stride_x = plate_stride_x();
  double stride_y = plate_stride_y();
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    assert(plate != NULL);
    Vec2d pos;
    pos = compute_shape_position(i, m_plate_cols);
    plate->set_shape(shape, exclude_areas, pos, height_to_lid, height_to_rod);
  }
  calc_bounding_boxes();
  auto check_texture = [](const std::string& texture) {
    boost::system::error_code ec; // so the exists call does not throw (e.g. after a permission problem)
    return !texture.empty() && (boost::algorithm::iends_with(texture, ".png") || boost::algorithm::iends_with(texture, ".svg")) && boost::filesystem::exists(texture, ec);
  };
  if (! texture_filename.empty() && ! check_texture(texture_filename)) {
    BOOST_LOG_TRIVIAL(error) << "Unable to load bed texture: " << texture_filename;
  }
  else
    m_logo_texture_filename = texture_filename;
  return true;
}
References calc_bounding_boxes(), compute_shape_position(), error, int, m_exclude_areas, m_height_to_lid, m_height_to_rod, m_logo_texture_filename, m_plate_cols, m_plate_list, m_plates_mutex, m_shape, NULL, plate_stride_x(), plate_stride_y(), and Slic3r::GUI::PartPlate::set_shape().
Referenced by create_plate(), delete_plate(), rebuild_plates_after_deserialize(), reset_size(), and Slic3r::CLI::run().
show_cali_texture()
void Slic3r::GUI::PartPlateList::show_cali_texture (bool show = true)
store_to_3mf_structure()
int Slic3r::GUI::PartPlateList::store_to_3mf_structure (PlateDataPtrs & plate_data_list, bool with_slice_info = true, int plate_idx = -1)
{
  int ret = 0;
  plate_data_list.clear();
  plate_data_list.reserve(m_plate_list.size());
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PlateData* plate_data_item = new PlateData();
    plate_data_item->locked = m_plate_list[i]->m_locked;
    plate_data_item->plate_index = m_plate_list[i]->m_plate_index;
    plate_data_item->plate_name = m_plate_list[i]->get_plate_name();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1% before load, width %2%, height %3%, size %4%!")
      %(i+1) %m_plate_list[i]->thumbnail_data.width %m_plate_list[i]->thumbnail_data.height %m_plate_list[i]->thumbnail_data.pixels.size();
    plate_data_item->plate_thumbnail.load_from(m_plate_list[i]->thumbnail_data);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1% after load, width %2%, height %3%, size %4%!")
      %(i+1) %plate_data_item->plate_thumbnail.width %plate_data_item->plate_thumbnail.height %plate_data_item->plate_thumbnail.pixels.size();
    plate_data_item->config.apply(*m_plate_list[i]->config());
    if (m_plate_list[i]->top_thumbnail_data.is_valid())
      plate_data_item->top_file = "valid_top";
    if (m_plate_list[i]->pick_thumbnail_data.is_valid())
      plate_data_item->pick_file = "valid_pick";
    if (m_plate_list[i]->obj_to_instance_set.size() > 0)
    {
      for (std::set<std::pair<int, int>>::iterator it = m_plate_list[i]->obj_to_instance_set.begin(); it != m_plate_list[i]->obj_to_instance_set.end(); ++it)
        plate_data_item->objects_and_instances.emplace_back(it->first, it->second);
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ <<boost::format(": plate %1%, gcode_filename=%2%, with_slice_info=%3%, slice_valid %4%, object item count %5%.")
      %i %m_plate_list[i]->m_gcode_result->filename % with_slice_info %m_plate_list[i]->is_slice_result_valid()%plate_data_item->objects_and_instances.size();
    if (with_slice_info) {
      if (m_plate_list[i]->get_slice_result() && m_plate_list[i]->is_slice_result_valid()) {
        // BBS only include current palte_idx
        if (plate_idx == i || plate_idx == PLATE_CURRENT_IDX || plate_idx == PLATE_ALL_IDX) {
          //load calibration thumbnail
          //if (m_plate_list[i]->cali_thumbnail_data.is_valid())
          //  plate_data_item->pattern_file = "valid_pattern";
          if (m_plate_list[i]->cali_bboxes_data.is_valid())
            plate_data_item->pattern_bbox_file = "valid_pattern_bbox";
          plate_data_item->gcode_file       = m_plate_list[i]->m_gcode_result->filename;
          plate_data_item->is_sliced_valid  = true;
          plate_data_item->gcode_prediction = std::to_string(
            (int) m_plate_list[i]->get_slice_result()->print_statistics.modes[static_cast<size_t>(PrintEstimatedStatistics::ETimeMode::Normal)].time);
          plate_data_item->toolpath_outside = m_plate_list[i]->m_gcode_result->toolpath_outside;
          plate_data_item->is_label_object_enabled = m_plate_list[i]->m_gcode_result->label_object_enabled;
          Print *print                      = nullptr;
          m_plate_list[i]->get_print((PrintBase **) &print, nullptr, nullptr);
          if (print) {
            const PrintStatistics &ps = print->print_statistics();
            if (ps.total_weight != 0.0) {
              CNumericLocalesSetter locales_setter;
              plate_data_item->gcode_weight =wxString::Format("%.2f", ps.total_weight).ToStdString();
            }
            plate_data_item->is_support_used = print->is_support_used();
          } else {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("print is null!");
          }
          //parse filament info
          plate_data_item->parse_filament_info(m_plate_list[i]->get_slice_result());
        } else {
          BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "slice result = " << m_plate_list[i]->get_slice_result()
                    << ", result valid = " << m_plate_list[i]->is_slice_result_valid();
        }
      }
    }
    plate_data_list.push_back(plate_data_item);
  }
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":stored %1% plates!") % m_plate_list.size();
  return ret;
}
References Slic3r::ConfigBase::apply(), Slic3r::PlateData::config, Slic3r::PlateData::gcode_file, Slic3r::PlateData::gcode_prediction, Slic3r::PlateData::gcode_weight, Slic3r::ThumbnailData::height, int, Slic3r::PlateData::is_label_object_enabled, Slic3r::PlateData::is_sliced_valid, Slic3r::PlateData::is_support_used, Slic3r::ThumbnailData::load_from(), Slic3r::PlateData::locked, m_plate_list, Slic3r::PrintEstimatedStatistics::Normal, Slic3r::PlateData::objects_and_instances, Slic3r::PlateData::parse_filament_info(), Slic3r::PlateData::pattern_bbox_file, Slic3r::PlateData::pick_file, Slic3r::ThumbnailData::pixels, PLATE_ALL_IDX, PLATE_CURRENT_IDX, Slic3r::PlateData::plate_index, Slic3r::PlateData::plate_name, Slic3r::PlateData::plate_thumbnail, print(), Slic3r::PlateData::toolpath_outside, Slic3r::PlateData::top_file, Slic3r::PrintStatistics::total_weight, and Slic3r::ThumbnailData::width.
Referenced by Slic3r::CLI::run().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
update_all_plates_pos_and_size()
void Slic3r::GUI::PartPlateList::update_all_plates_pos_and_size (bool adjust_position = true, bool with_unprintable_move = true)
{
  Vec3d origin1, origin2;
  for (unsigned int i = 0; i < (unsigned int)m_plate_list.size(); ++i)
  {
    PartPlate* plate = m_plate_list[i];
    assert(plate != NULL);
    //compute origin1 for PartPlate
    origin1 = compute_origin(i, m_plate_cols);
    plate->set_pos_and_size(origin1, m_plate_width, m_plate_depth, m_plate_height, adjust_position);
  }
  origin2 = compute_origin_for_unprintable();
  unprintable_plate.set_pos_and_size(origin2, m_plate_width, m_plate_depth, m_plate_height, with_unprintable_move);
}
References compute_origin(), compute_origin_for_unprintable(), int, m_plate_cols, m_plate_depth, m_plate_height, m_plate_list, m_plate_width, NULL, Slic3r::GUI::PartPlate::set_pos_and_size(), and unprintable_plate.
Referenced by create_plate(), delete_plate(), and reset_size().
update_current_slice_result_state()
void Slic3r::GUI::PartPlateList::update_current_slice_result_state (bool valid) inline
{ m_plate_list[m_current_plate]->update_slice_result_valid_state(valid); }
References m_current_plate, and m_plate_list.
update_plate_cols()
void Slic3r::GUI::PartPlateList::update_plate_cols ()
{
  m_plate_count = m_plate_list.size();
  m_plate_cols = compute_colum_count(m_plate_count);
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":m_plate_count %1%, m_plate_cols change to %2%") % m_plate_count % m_plate_cols;
  return;
}
References compute_colum_count(), m_plate_cols, m_plate_count, and m_plate_list.
Referenced by create_plate(), delete_plate(), and rebuild_plates_after_deserialize().
update_slice_context_to_current_plate()
void Slic3r::GUI::PartPlateList::update_slice_context_to_current_plate (BackgroundSlicingProcess & process)
{
  PartPlate* current_plate;
  current_plate = m_plate_list[m_current_plate];
  assert(current_plate != NULL);
  current_plate->update_slice_context(process);
  return;
}
References m_current_plate, m_plate_list, NULL, and Slic3r::GUI::PartPlate::update_slice_context().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
PartPlate
friend class PartPlate friend
Referenced by create_plate(), and init().
UndoRedo::StackImpl
friend class UndoRedo::StackImpl friend
Member Data Documentation
bed_texture_info
BedTextureInfo Slic3r::GUI::PartPlateList::bed_texture_info[btCount]
Referenced by init_bed_type_info(), load_bedtype_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_logo().
bed_textures
GLTexture Slic3r::GUI::PartPlateList::bed_textures[(unsigned int) btCount] static
cali_texture_info
BedTextureInfo Slic3r::GUI::PartPlateList::cali_texture_info
Referenced by init_cali_texture_info(), load_cali_textures(), and Slic3r::GUI::PartPlate::render_logo().
is_load_bedtype_textures
bool Slic3r::GUI::PartPlateList::is_load_bedtype_textures = false static
Referenced by load_bedtype_textures(), and release_icon_textures().
is_load_cali_texture
bool Slic3r::GUI::PartPlateList::is_load_cali_texture = false static
Referenced by load_cali_textures(), and release_icon_textures().
m_arrange_hovered_texture
GLTexture Slic3r::GUI::PartPlateList::m_arrange_hovered_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_arrange_texture
GLTexture Slic3r::GUI::PartPlateList::m_arrange_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_bounding_box
BoundingBoxf3 Slic3r::GUI::PartPlateList::m_bounding_box private
Referenced by calc_bounding_boxes(), and get_bounding_box().
m_current_plate
int Slic3r::GUI::PartPlateList::m_current_plate private
Referenced by clear(), create_plate(), delete_plate(), delete_selected_plate(), get_curr_plate(), get_curr_plate(), get_curr_plate_index(), get_current_fff_print(), get_current_plate_origin(), get_current_shape_position(), get_current_slice_result(), get_selected_plate(), init(), move_plate_to_index(), postprocess_bed_index_for_current_plate(), print(), rebuild_plates_after_deserialize(), render(), select_plate(), select_plate_view(), serialize(), update_current_slice_result_state(), and update_slice_context_to_current_plate().
m_del_hovered_texture
GLTexture Slic3r::GUI::PartPlateList::m_del_hovered_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_del_texture
GLTexture Slic3r::GUI::PartPlateList::m_del_texture private
Referenced by generate_icon_textures(), release_icon_textures(), render(), and Slic3r::GUI::PartPlate::render_icons().
m_exclude_areas
Pointfs Slic3r::GUI::PartPlateList::m_exclude_areas private
Referenced by create_plate(), delete_plate(), get_exclude_area(), preprocess_exclude_areas(), rebuild_plates_after_deserialize(), reinit(), reset_size(), and set_shapes().
m_gcode_result_list
std::map<int, GCodeResult*> Slic3r::GUI::PartPlateList::m_gcode_result_list private
Referenced by clear(), create_plate(), destroy_print(), init(), and rebuild_plates_after_deserialize().
m_height_limit_mode
PartPlate::HeightLimitMode Slic3r::GUI::PartPlateList::m_height_limit_mode {PartPlate::HEIGHT_LIMIT_BOTH} private
Referenced by render(), serialize(), and set_height_limits_mode().
m_height_to_lid
float Slic3r::GUI::PartPlateList::m_height_to_lid private
Referenced by create_plate(), delete_plate(), get_height_limits(), rebuild_plates_after_deserialize(), reinit(), reset_size(), serialize(), and set_shapes().
m_height_to_rod
float Slic3r::GUI::PartPlateList::m_height_to_rod private
Referenced by create_plate(), delete_plate(), get_height_limits(), rebuild_plates_after_deserialize(), reinit(), reset_size(), serialize(), and set_shapes().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_idx_textures
GLTexture Slic3r::GUI::PartPlateList::m_idx_textures[MAX_PLATE_COUNT] private
Referenced by generate_icon_textures(), release_icon_textures(), Slic3r::GUI::PartPlate::render_icons(), and Slic3r::GUI::PartPlate::render_only_numbers().
m_intialized
bool Slic3r::GUI::PartPlateList::m_intialized private
Referenced by init(), and select_plate().
m_is_dark
bool Slic3r::GUI::PartPlateList::m_is_dark = false private
Referenced by generate_icon_textures(), on_change_color_mode(), render(), Slic3r::GUI::PartPlate::render_background(), and Slic3r::GUI::PartPlate::render_grid().
m_locked_hovered_texture
GLTexture Slic3r::GUI::PartPlateList::m_locked_hovered_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_locked_texture
GLTexture Slic3r::GUI::PartPlateList::m_locked_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_lockopen_hovered_texture
GLTexture Slic3r::GUI::PartPlateList::m_lockopen_hovered_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_lockopen_texture
GLTexture Slic3r::GUI::PartPlateList::m_lockopen_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_logo_texture
GLTexture Slic3r::GUI::PartPlateList::m_logo_texture private
Referenced by release_icon_textures(), and Slic3r::GUI::PartPlate::render_logo().
m_logo_texture_filename
std::string Slic3r::GUI::PartPlateList::m_logo_texture_filename private
Referenced by create_plate(), delete_plate(), get_logo_texture_filename(), rebuild_plates_after_deserialize(), Slic3r::GUI::PartPlate::render_logo(), reset_size(), and set_shapes().
m_model
Model* Slic3r::GUI::PartPlateList::m_model private
Referenced by construct_objects_list_for_new_plate(), create_plate(), init(), load_gcode_files(), notify_instance_removed(), notify_instance_update(), rebuild_plates_after_arrangement(), rebuild_plates_after_deserialize(), reload_all_objects(), and select_plate().
m_orient_hovered_texture
GLTexture Slic3r::GUI::PartPlateList::m_orient_hovered_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_orient_texture
GLTexture Slic3r::GUI::PartPlateList::m_orient_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_plate_cols
int Slic3r::GUI::PartPlateList::m_plate_cols private
Referenced by compute_origin_for_unprintable(), compute_origin_using_new_size(), compute_plate_index(), delete_plate(), get_current_plate_origin(), get_current_shape_position(), get_plate_cols(), init(), move_plate_to_index(), postprocess_arrange_polygon(), preprocess_arrange_polygon(), preprocess_arrange_polygon_other_locked(), print(), rebuild_plates_after_deserialize(), reinit(), select_plate(), set_shapes(), update_all_plates_pos_and_size(), and update_plate_cols().
m_plate_count
int Slic3r::GUI::PartPlateList::m_plate_count private
Referenced by compute_origin_for_unprintable(), init(), notify_instance_update(), print(), serialize(), and update_plate_cols().
m_plate_depth
int Slic3r::GUI::PartPlateList::m_plate_depth private
Referenced by compute_origin(), create_plate(), delete_plate(), get_plate_size(), init(), move_plate_to_index(), plate_stride_y(), postprocess_arrange_polygon(), print(), reinit(), reset_size(), serialize(), and update_all_plates_pos_and_size().
m_plate_height
int Slic3r::GUI::PartPlateList::m_plate_height private
Referenced by create_plate(), delete_plate(), get_plate_size(), init(), load_gcode_files(), move_plate_to_index(), print(), reinit(), reset_size(), serialize(), and update_all_plates_pos_and_size().
m_plate_list
std::vector<PartPlate*> Slic3r::GUI::PartPlateList::m_plate_list private
Referenced by add_to_plate(), calc_bounding_boxes(), clear(), construct_objects_list_for_new_plate(), contains(), create_plate(), delete_plate(), find_instance(), find_instance(), find_instance_belongs(), find_plate_by_print_index(), get_curr_plate(), get_curr_plate(), get_current_fff_print(), get_current_slice_result(), get_nonempty_plate_list(), get_plate(), get_plate_count(), get_plate_list(), get_selected_plate(), get_sliced_result(), init(), intersects(), invalid_all_slice_result(), is_all_plates_ready_for_slice(), is_all_slice_results_ready_for_print(), is_all_slice_results_valid(), is_locked(), load_from_3mf_structure(), load_gcode_files(), lock_plate(), move_plate_to_index(), notify_instance_removed(), notify_instance_update(), postprocess_arrange_polygon(), postprocess_bed_index_for_current_plate(), postprocess_bed_index_for_selected(), postprocess_bed_index_for_unselected(), preprocess_arrange_polygon(), preprocess_arrange_polygon_other_locked(), preprocess_exclude_areas(), preprocess_nonprefered_areas(), print(), rebuild_plates_after_arrangement(), rebuild_plates_after_deserialize(), reinit(), reload_all_objects(), render(), render_for_picking_pass(), reset_hover_id(), select_plate(), select_plate_view(), serialize(), set_hover_id(), set_shapes(), store_to_3mf_structure(), update_all_plates_pos_and_size(), update_current_slice_result_state(), update_plate_cols(), and update_slice_context_to_current_plate().
m_plate_settings_changed_hovered_texture
GLTexture Slic3r::GUI::PartPlateList::m_plate_settings_changed_hovered_texture private
Referenced by generate_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_plate_settings_changed_texture
GLTexture Slic3r::GUI::PartPlateList::m_plate_settings_changed_texture private
Referenced by generate_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_plate_settings_hovered_texture
GLTexture Slic3r::GUI::PartPlateList::m_plate_settings_hovered_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_plate_settings_texture
GLTexture Slic3r::GUI::PartPlateList::m_plate_settings_texture private
Referenced by generate_icon_textures(), release_icon_textures(), and Slic3r::GUI::PartPlate::render_icons().
m_plate_width
int Slic3r::GUI::PartPlateList::m_plate_width private
Referenced by compute_origin(), create_plate(), delete_plate(), get_plate_size(), init(), move_plate_to_index(), plate_stride_x(), print(), reinit(), reset_size(), serialize(), and update_all_plates_pos_and_size().
m_plater
Plater* Slic3r::GUI::PartPlateList::m_plater private
Referenced by create_plate(), delete_plate(), init(), load_from_3mf_structure(), load_gcode_files(), rebuild_plates_after_arrangement(), rebuild_plates_after_deserialize(), select_plate(), and select_plate_view().
m_plates_mutex
std::mutex Slic3r::GUI::PartPlateList::m_plates_mutex private
Referenced by render(), render_for_picking_pass(), reset_hover_id(), select_plate(), and set_shapes().
m_print_index
int Slic3r::GUI::PartPlateList::m_print_index private
Referenced by create_plate(), init(), print(), and rebuild_plates_after_deserialize().
m_print_list
std::map<int, PrintBase*> Slic3r::GUI::PartPlateList::m_print_list private
Referenced by clear(), create_plate(), destroy_print(), init(), print(), and rebuild_plates_after_deserialize().
m_shape
Pointfs Slic3r::GUI::PartPlateList::m_shape private
Referenced by create_plate(), delete_plate(), rebuild_plates_after_deserialize(), reinit(), reset_size(), serialize(), and set_shapes().
MAX_PLATES_COUNT
const unsigned int Slic3r::GUI::PartPlateList::MAX_PLATES_COUNT = MAX_PLATE_COUNT static
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::Plater::priv::can_add_plate(), create_plate(), postprocess_arrange_polygon(), postprocess_bed_index_for_unselected(), Slic3r::GUI::FillBedJob::prepare(), preprocess_arrange_polygon(), and preprocess_arrange_polygon_other_locked().
printer_technology
PrinterTechnology Slic3r::GUI::PartPlateList::printer_technology private
Referenced by create_plate(), init(), and rebuild_plates_after_deserialize().
render_bedtype_logo
bool Slic3r::GUI::PartPlateList::render_bedtype_logo = true private
Referenced by Slic3r::GUI::PartPlate::render_logo(), and set_render_option().
render_cali_logo
bool Slic3r::GUI::PartPlateList::render_cali_logo = true private
Referenced by Slic3r::GUI::PartPlate::render(), and set_render_cali().
render_plate_settings
bool Slic3r::GUI::PartPlateList::render_plate_settings = true private
Referenced by Slic3r::GUI::PartPlate::on_render_for_picking(), Slic3r::GUI::PartPlate::render_icons(), and set_render_option().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
unprintable_plate
PartPlate Slic3r::GUI::PartPlateList::unprintable_plate private
Referenced by clear(), construct_objects_list_for_new_plate(), create_plate(), delete_plate(), init(), notify_instance_removed(), notify_instance_update(), print(), reinit(), reload_all_objects(), serialize(), and update_all_plates_pos_and_size().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PartPlate.hpp
src/slic3r/GUI/PartPlate.cpp