OrcaSlicer: Slic3r::GUI::AssembleViewDataPool Class Reference
Slic3r::GUI::AssembleViewDataPool Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
AssembleViewDataPool (GLCanvas3D *canvas)
void update (AssembleViewDataID required)
AssembleViewDataObjects::ModelObjectsInfo * model_objects_info () const
AssembleViewDataObjects::ModelObjectsClipper * model_objects_clipper () const
GLCanvas3D * get_canvas () const
Private Member Functions
bool check_dependencies (AssembleViewDataID required) const
Private Attributes
std::map< AssembleViewDataID, std::unique_ptr< AssembleViewDataBase > > m_data
GLCanvas3D * m_canvas
Detailed Description
Constructor & Destructor Documentation
AssembleViewDataPool()
Slic3r::GUI::AssembleViewDataPool::AssembleViewDataPool (GLCanvas3D * canvas)
    : m_canvas(canvas)
{
    using c = AssembleViewDataID;
    m_data[c::ModelObjectsInfo].reset(new ModelObjectsInfo(this));
    m_data[c::ModelObjectsClipper].reset(new ModelObjectsClipper(this));
}
References m_data.
Member Function Documentation
check_dependencies()
bool Slic3r::GUI::AssembleViewDataPool::check_dependencies (AssembleViewDataID required) const private
{
    // This should iterate over currently required data. Each of them should
    // be asked about its dependencies and it must check that all dependencies
    // are also in required and before the current one.
    for (auto& [id, data] : m_data) {
        // in case we don't use this, the deps are irrelevant
        if (!(int(required) & int(AssembleViewDataID(id))))
            continue;
        AssembleViewDataID deps = data->get_dependencies();
        assert(int(deps) == (int(deps) & int(required)));
    }
return true;
}
References m_data.
Referenced by update().
get_canvas()
GLCanvas3D * Slic3r::GUI::AssembleViewDataPool::get_canvas () const inline
{ return m_canvas; }
References m_canvas.
Referenced by Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::on_update(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::on_update(), and Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::set_position().
model_objects_clipper()
ModelObjectsClipper * Slic3r::GUI::AssembleViewDataPool::model_objects_clipper () const
{
    ModelObjectsClipper* oc = dynamic_cast<ModelObjectsClipper*>(m_data.at(AssembleViewDataID::ModelObjectsClipper).get());
    // ObjectClipper is used from outside the gizmos to report current clipping plane.
    // This function can be called when oc is nullptr.
    return (oc && oc->is_valid()) ? oc : nullptr;
}
References Slic3r::GUI::AssembleViewDataBase::is_valid(), m_data, and Slic3r::GUI::ModelObjectsClipper.
model_objects_info()
ModelObjectsInfo * Slic3r::GUI::AssembleViewDataPool::model_objects_info () const
{
    ModelObjectsInfo* sel_info = dynamic_cast<ModelObjectsInfo*>(m_data.at(AssembleViewDataID::ModelObjectsInfo).get());
    assert(sel_info);
    return sel_info->is_valid() ? sel_info : nullptr;
}
References Slic3r::GUI::AssembleViewDataBase::is_valid(), m_data, and Slic3r::GUI::ModelObjectsInfo.
Referenced by Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::on_update(), and Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::render_cut().
update()
void Slic3r::GUI::AssembleViewDataPool::update (AssembleViewDataID required)
{
    assert(check_dependencies(required));
    for (auto& [id, data] : m_data) {
        if (int(required) & int(AssembleViewDataID(id)))
            data->update();
        else
            if (data->is_valid())
                data->release();
    }
}
References check_dependencies(), int, and m_data.
Member Data Documentation
m_canvas
GLCanvas3D* Slic3r::GUI::AssembleViewDataPool::m_canvas private
Referenced by get_canvas().
m_data
std::map<AssembleViewDataID, std::unique_ptr<AssembleViewDataBase> > Slic3r::GUI::AssembleViewDataPool::m_data private
Referenced by AssembleViewDataPool(), check_dependencies(), model_objects_clipper(), model_objects_info(), and update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp
src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp