OrcaSlicer: orgQhull::QhullSetBase Class Reference
orgQhull::QhullSetBase Class Reference
Base class for QhullSet<T> QhullSet<T> defined below QhullSetIterator<T> defined below.
#include <src/qhull/src/libqhullcpp/QhullSet.h>
Public Member Functions
GetSet
countT count () const
void defineAs (setT *s)
Not type-safe since setT may contain any type.
void forceEmpty ()
setT * getSetT () const
bool isEmpty () const
QhullQh * qh () const
setT ** referenceSetT ()
size_t size () const
Static Public Member Functions
Class methods
static countT count (const setT *set)
static bool isEmpty (const setT *s)
Protected Member Functions
Element
void ** beginPointer () const
void ** elementPointer (countT idx) const
void ** endPointer () const
Always points to 0.
Private Attributes
Fields –
setT * qh_set
QhullQh * qh_qh
Static Private Attributes
Class objects
Provides access to setT memory allocator
static setT s_empty_set
Constructors
Used if setT* is NULL
QhullSetBase (const Qhull &q, setT *s)
QhullSetBase (QhullQh *qqh, setT *s)
QhullSetBase (const QhullSetBase &other)
Copy constructor copies the pointer but not the set. Needed for return by value and parameter passing.
QhullSetBase & operator= (const QhullSetBase &other)
~QhullSetBase ()
QhullSetBase ()
disabled since memory allocation for QhullSet not defined
Detailed Description
Base class for QhullSet<T> QhullSet<T> defined below QhullSetIterator<T> defined below.
See also
QhullPointSet, QhullLinkedList<T> QhullSetBase is a wrapper for Qhull's setT of void* pointers
libqhull_r/qset.h
Constructor & Destructor Documentation
QhullSetBase() [1/4]
orgQhull::QhullSetBase::QhullSetBase (const Qhull & q, setT * s)
: qh_set(s ? s : &s_empty_set)
, qh_qh(q.qh())
{
}
QhullSetBase() [2/4]
orgQhull::QhullSetBase::QhullSetBase (QhullQh * qqh, setT * s) inline
: qh_set(s ? s : &s_empty_set), qh_qh(qqh) {}
QhullSetBase() [3/4]
orgQhull::QhullSetBase::QhullSetBase (const QhullSetBase & other) inline
Copy constructor copies the pointer but not the set. Needed for return by value and parameter passing.
: qh_set(other.qh_set), qh_qh(other.qh_qh) {}
~QhullSetBase()
orgQhull::QhullSetBase::~QhullSetBase () inline
{}
QhullSetBase() [4/4]
orgQhull::QhullSetBase::QhullSetBase () inline private
disabled since memory allocation for QhullSet not defined
{}
Member Function Documentation
beginPointer()
void ** orgQhull::QhullSetBase::beginPointer () const inline protected
{ return &qh_set->e[0].p; }
References setT::e, setelemT::p, and qh_set.
Referenced by orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::constData(), orgQhull::QhullSet< T >::data(), and orgQhull::QhullSet< T >::data().
count() [1/2]
countT orgQhull::QhullSetBase::count () const inline
{ return QhullSetBase::count(qh_set); }
References count(), and qh_set.
Referenced by count(), and size().
count() [2/2]
countT orgQhull::QhullSetBase::count (const setT * set) static
{
    countT size;
    const setelemT *sizep;
    if (!set){
        return(0);
    }
    sizep= SETsizeaddr_(set);
    if ((size= sizep->i)) {
        size--;
        if (size > set->maxsize) {
            // FIXUP QH11022 How to add additional output to a error? -- qh_setprint(qhmem.ferr, "set: ", set);
            throw QhullError(10032, "QhullSet internal error: current set size %d is greater than maximum size %d\n",
                size, set->maxsize);
        }
    }else{
        size= set->maxsize;
    }
    return size;
}//count
References setelemT::i, setT::maxsize, SETsizeaddr_, and size().
defineAs()
void orgQhull::QhullSetBase::defineAs (setT * s) inline
Not type-safe since setT may contain any type.
References qh_set, and s_empty_set.
Referenced by orgQhull::QhullVertexSet::QhullVertexSet(), and orgQhull::QhullVertexSet::QhullVertexSet().
elementPointer()
void ** orgQhull::QhullSetBase::elementPointer (countT idx) const inline protected
{ QHULL_ASSERT(idx>=0 && idx<qh_set->maxsize); return &SETelem_(qh_set, idx); }
References qh_set, QHULL_ASSERT, and SETelem_.
Referenced by orgQhull::QhullSet< T >::operator[](), and orgQhull::QhullSet< T >::operator[]().
endPointer()
void ** orgQhull::QhullSetBase::endPointer () const inline protected
Always points to 0.
{ return qh_setendpointer(qh_set); }
References qh_set, and qh_setendpointer().
Referenced by orgQhull::QhullSet< T >::endData(), and orgQhull::QhullSet< T >::endData().
forceEmpty()
void orgQhull::QhullSetBase::forceEmpty () inline
{ qh_set= &s_empty_set; }
References qh_set, and s_empty_set.
getSetT()
setT * orgQhull::QhullSetBase::getSetT () const inline
{ return qh_set; }
References qh_set.
Referenced by orgQhull::QhullSet< T >::indexOf(), orgQhull::QhullSet< T >::operator==(), and orgQhull::QhullSet_test::t_qhullsetbase().
isEmpty() [1/2]
bool orgQhull::QhullSetBase::isEmpty () const inline
{ return SETempty_(qh_set); }
References qh_set, and SETempty_.
Referenced by orgQhull::QhullSet_test::t_qhullsetbase().
isEmpty() [2/2]
static bool orgQhull::QhullSetBase::isEmpty (const setT * s) inline static
{ return SETempty_(s); }
References SETempty_.
operator=()
QhullSetBase & orgQhull::QhullSetBase::operator= (const QhullSetBase & other) inline
{ qh_set= other.qh_set; qh_qh= other.qh_qh; return *this; }
References qh_qh, and qh_set.
Referenced by orgQhull::QhullSet< T >::operator=().
qh()
QhullQh * orgQhull::QhullSetBase::qh () const inline
{ return qh_qh; }
References qh_qh.
Referenced by orgQhull::QhullVertexSet::QhullVertexSet(), orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::constBegin(), orgQhull::QhullSet< T >::constEnd(), orgQhull::QhullSet< T >::end(), orgQhull::QhullSet< T >::end(), orgQhull::QhullSet< T >::first(), orgQhull::QhullSet< T >::first(), orgQhull::QhullVertexSet::freeQhSetTemp(), orgQhull::QhullSet< T >::last(), orgQhull::QhullSet< T >::last(), operator<<(), orgQhull::QhullSet< T >::operator[](), and orgQhull::QhullSet< T >::operator[]().
referenceSetT()
setT ** orgQhull::QhullSetBase::referenceSetT () inline
{ return &qh_set; }
References qh_set.
Referenced by orgQhull::QhullVertexSet::freeQhSetTemp().
size()
size_t orgQhull::QhullSetBase::size () const inline
{ return QhullSetBase::count(qh_set); }
References count(), and qh_set.
Referenced by count(), operator<<(), orgQhull::QhullPointSet_test::t_construct(), orgQhull::QhullPointSet_test::t_convert(), and orgQhull::QhullSet_test::t_qhullsetbase().
Member Data Documentation
qh_qh
QhullQh* orgQhull::QhullSetBase::qh_qh private
Referenced by operator=(), and qh().
qh_set
setT* orgQhull::QhullSetBase::qh_set private
Referenced by beginPointer(), count(), defineAs(), elementPointer(), endPointer(), forceEmpty(), getSetT(), isEmpty(), operator=(), referenceSetT(), and size().
s_empty_set
setT orgQhull::QhullSetBase::s_empty_set static private
Referenced by defineAs(), and forceEmpty().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullSet.h
src/qhull/src/libqhullcpp/QhullSet.cpp