OrcaSlicer: Slic3r::GUI::GridCellFilamentsRenderer Class Reference
Slic3r::GUI::GridCellFilamentsRenderer Class Reference
#include <src/slic3r/GUI/GUI_ObjectTable.hpp>
Public Member Functions
virtual void Draw (wxGrid &grid, wxGridCellAttr &attr, wxDC &dc, const wxRect &rect, int row, int col, bool isSelected) wxOVERRIDE
virtual wxSize GetBestSize (wxGrid &WXUNUSED(grid), wxGridCellAttr &attr, wxDC &dc, int WXUNUSED(row), int WXUNUSED(col)) wxOVERRIDE
virtual GridCellFilamentsRenderer * Clone () const wxOVERRIDE
Detailed Description
Member Function Documentation
Clone()
GridCellFilamentsRenderer * Slic3r::GUI::GridCellFilamentsRenderer::Clone () const virtual
{ return new GridCellFilamentsRenderer(); }
Draw()
void Slic3r::GUI::GridCellFilamentsRenderer::Draw (wxGrid & grid, wxGridCellAttr & attr, wxDC & dc, const wxRect & rect, int row, int col, bool isSelected) virtual
{
    ObjectGridTable *table     = dynamic_cast<ObjectGridTable *>(grid.GetTable());
    wxRect           text_rect = rect;
    if (table) {
        ObjectGridTable::ObjectGridCol *grid_col   = table->get_grid_col(col);
        ObjectGridTable::ObjectGridRow *grid_row   = table->get_grid_row(row - 1);
        ConfigOptionInt &               cur_option = dynamic_cast<ConfigOptionInt &>((*grid_row)[(ObjectGridTable::GridColType) col]);
        wxBitmap *bitmap        = table->get_color_bitmap((cur_option.value >= 1) ? cur_option.value - 1 : cur_option.value);
        int       bitmap_width  = bitmap->GetWidth();
        int       bitmap_height = bitmap->GetHeight();
        int       offset_x      = grid_cell_border_width;
        int       offset_y      = (rect.height > bitmap_height) ? (rect.height - bitmap_height) / 2 : grid_cell_border_height;
        dc.SetPen(*wxTRANSPARENT_PEN);
        dc.SetBrush(wxBrush(attr.GetBackgroundColour()));
        dc.DrawRectangle(rect);
        if ( grid_row->model_volume_type != ModelVolumeType::NEGATIVE_VOLUME) {
            dc.DrawBitmap(*bitmap, wxPoint(rect.x + offset_x, rect.y + offset_y));
        }
        text_rect.x += bitmap_width + grid_cell_border_width * 2;
        text_rect.width -= (bitmap_width + grid_cell_border_width * 2);
    }
    //wxGridCellChoiceRenderer::Draw(grid, attr, dc, rect, row, col, isSelected);
}
References col(), Slic3r::GUI::ObjectGridTable::get_color_bitmap(), Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), Slic3r::grid(), Slic3r::GUI::grid_cell_border_height, Slic3r::GUI::grid_cell_border_width, Slic3r::GUI::ObjectGridTable::ObjectGridRow::model_volume_type, Slic3r::NEGATIVE_VOLUME, row(), and Slic3r::ConfigOptionSingle< T >::value.
GetBestSize()
wxSize Slic3r::GUI::GridCellFilamentsRenderer::GetBestSize (wxGrid & WXUNUSEDgrid, wxGridCellAttr & attr, wxDC & dc, int WXUNUSEDrow, int WXUNUSEDcol) virtual
{
    wxSize size{48, -1};
    return size;
}
References size.
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTable.hpp
src/slic3r/GUI/GUI_ObjectTable.cpp