OrcaSlicer: Slic3r::GUI::AMSLib Class Reference
Slic3r::GUI::AMSLib Class Reference
#include <src/slic3r/GUI/Widgets/AMSControl.hpp>
Public Member Functions
AMSLib (wxWindow *parent, wxWindowID id, Caninfo info, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
void create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
wxColour GetLibColour ()
void Update (Caninfo info, bool refresh=true)
void UnableSelected ()
void EableSelected ()
void OnSelected ()
void UnSelected ()
bool is_selected ()
void post_event (wxCommandEvent &&event)
void show_kn_value (bool show)
void support_cali (bool sup)
virtual bool Enable (bool enable=true)
Public Attributes
Caninfo m_info
MachineObject * m_obj = {nullptr}
int m_can_index
Protected Member Functions
void on_enter_window (wxMouseEvent &evt)
void on_leave_window (wxMouseEvent &evt)
void on_left_down (wxMouseEvent &evt)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
Protected Attributes
wxStaticBitmap * m_edit_bitmp = {nullptr}
wxStaticBitmap * m_edit_bitmp_light = {nullptr}
ScalableBitmap m_bitmap_editable
ScalableBitmap m_bitmap_editable_light
ScalableBitmap m_bitmap_readonly
ScalableBitmap m_bitmap_readonly_light
bool m_unable_selected = {false}
bool m_enable = {false}
bool m_selected = {false}
bool m_hover = {false}
bool m_show_kn = {false}
bool m_support_cali = {false}
double m_radius = {4}
wxColour m_border_color
wxColour m_road_def_color
wxColour m_lib_color
Detailed Description
Constructor & Destructor Documentation
AMSLib()
Slic3r::GUI::AMSLib::AMSLib (wxWindow * parent, wxWindowID id, Caninfo info, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{
    m_border_color   = (wxColour(130, 130, 128));
    m_road_def_color = AMS_CONTROL_GRAY500;
    wxWindow::SetBackgroundColour(AMS_CONTROL_DEF_BLOCK_BK_COLOUR);
    create(parent, id, pos, size);
    Bind(wxEVT_PAINT, &AMSLib::paintEvent, this);
    Bind(wxEVT_ENTER_WINDOW, &AMSLib::on_enter_window, this);
    Bind(wxEVT_LEAVE_WINDOW, &AMSLib::on_leave_window, this);
    Bind(wxEVT_LEFT_DOWN, &AMSLib::on_left_down, this);
    Update(info, false);
}
References AMS_CONTROL_DEF_BLOCK_BK_COLOUR, AMS_CONTROL_GRAY500, create(), m_border_color, m_road_def_color, on_enter_window(), on_leave_window(), on_left_down(), paintEvent(), and size.
Member Function Documentation
create()
void Slic3r::GUI::AMSLib::create (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{
    wxWindow::Create(parent, id, pos, size);
    SetSize(AMS_CAN_LIB_SIZE);
    SetMinSize(AMS_CAN_LIB_SIZE);
    SetMaxSize(AMS_CAN_LIB_SIZE);
    auto m_sizer_body = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_sizer_edit = new wxBoxSizer(wxHORIZONTAL);
    m_bitmap_editable       = ScalableBitmap(this, "ams_editable", 14);
    m_bitmap_editable_light = ScalableBitmap(this, "ams_editable_light", 14);
    m_bitmap_readonly       = ScalableBitmap(this, "ams_readonly", 14);
    m_bitmap_readonly_light = ScalableBitmap(this, "ams_readonly_light", 14);
    m_sizer_body->Add(0, 0, 1, wxEXPAND, 0);
    m_sizer_body->Add(m_sizer_edit, 0, wxALIGN_CENTER, 0);
    m_sizer_body->Add(0, 0, 0, wxBOTTOM, GetSize().y * 0.12);
    SetSizer(m_sizer_body);
    Layout();
}
References AMS_CAN_LIB_SIZE, m_bitmap_editable, m_bitmap_editable_light, m_bitmap_readonly, m_bitmap_readonly_light, and size.
Referenced by AMSLib().
doRender()
void Slic3r::GUI::AMSLib::doRender (wxDC & dc) protected
{
    wxSize size                   = GetSize();
    auto   tmp_lib_colour         = m_info.material_colour;
    auto   temp_bitmap_third      = m_bitmap_editable_light;
    auto   temp_bitmap_brand      = m_bitmap_readonly_light;
    //draw def background
    dc.SetPen(wxPen(*wxTRANSPARENT_PEN));
    dc.SetBrush(wxBrush(AMS_CONTROL_DEF_LIB_BK_COLOUR));
    dc.DrawRoundedRectangle(FromDIP(4), FromDIP(4), size.x - FromDIP(8), size.y - FromDIP(8), m_radius);
    if (tmp_lib_colour.GetLuminance() < 0.5) {
        temp_bitmap_third = m_bitmap_editable_light;
        temp_bitmap_brand = m_bitmap_readonly_light;
    } else {
        temp_bitmap_third = m_bitmap_editable;
        temp_bitmap_brand = m_bitmap_readonly;
    }
    if (m_info.material_remain < 50) {
        temp_bitmap_third = m_bitmap_editable;
        temp_bitmap_brand = m_bitmap_readonly;
    }
    //if (!wxWindow::IsEnabled()) {
        //tmp_lib_colour   = AMS_CONTROL_DISABLE_COLOUR;
    //}
    // selected
    if (m_selected) {
        // lib
        dc.SetPen(wxPen(tmp_lib_colour, 2, wxSOLID));
        dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
        if (m_radius == 0) {
            dc.DrawRectangle(0, 0, size.x, size.y);
        } else {
            dc.DrawRoundedRectangle(FromDIP(1), FromDIP(1), size.x - FromDIP(1), size.y - FromDIP(1), m_radius);
        }
        dc.SetPen(wxPen(*wxTRANSPARENT_PEN));
        dc.SetBrush(wxBrush(tmp_lib_colour));
        /* if (m_radius == 0) {
             dc.DrawRectangle(0, 0, size.x, size.y);
         } else {
             dc.DrawRoundedRectangle(FromDIP(4), FromDIP(4), size.x - FromDIP(8), size.y - FromDIP(8), m_radius);
         }*/
    }
    if (!m_selected && m_hover) {
        dc.SetPen(wxPen(AMS_CONTROL_BRAND_COLOUR, 2, wxSOLID));
        dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
        if (m_radius == 0) {
            dc.DrawRectangle(0, 0, size.x, size.y);
        }
        else {
            dc.DrawRoundedRectangle(FromDIP(1), FromDIP(1), size.x - FromDIP(1), size.y - FromDIP(1), m_radius);
        }
        dc.SetPen(wxPen(*wxTRANSPARENT_PEN));
        dc.SetBrush(wxBrush(tmp_lib_colour));
       /* if (m_radius == 0) {
            dc.DrawRectangle(0, 0, size.x, size.y);
        } else {
            dc.DrawRoundedRectangle(FromDIP(4), FromDIP(4), size.x - FromDIP(8), size.y - FromDIP(8), m_radius);
        }*/
    } else {
        dc.SetPen(wxPen(tmp_lib_colour, 1, wxSOLID));
        dc.SetBrush(wxBrush(tmp_lib_colour));
        /*if (m_radius == 0) {
            dc.DrawRectangle(0, 0, size.x, size.y);
        } else {
            dc.DrawRoundedRectangle(FromDIP(4), FromDIP(4), size.x - FromDIP(8), size.y - FromDIP(8), m_radius);
        }*/
    }
    //draw remain
    int height = size.y - FromDIP(8);
    int curr_height = height * float(m_info.material_remain * 1.0 / 100.0);
    int top = height - curr_height;
    if (curr_height >= FromDIP(6)) {
        //gradient
        if (m_info.material_cols.size() > 1) {
            int left = FromDIP(4);
            float total_width = size.x - FromDIP(8);
            int gwidth = std::round(total_width / (m_info.material_cols.size() - 1));
            for (int i = 0; i < m_info.material_cols.size() - 1; i++) {
                if ((left + gwidth) > (size.x - FromDIP(8))) {
                    gwidth = (size.x - FromDIP(4)) - left;
                }
                auto rect = wxRect(left, height - curr_height + FromDIP(4), gwidth, curr_height);
                dc.GradientFillLinear(rect, m_info.material_cols[i], m_info.material_cols[i + 1], wxEAST);
                left += gwidth;
            }
        }
        else {
#ifdef __APPLE__
            dc.DrawRoundedRectangle(FromDIP(4), FromDIP(4) + top, size.x - FromDIP(8), curr_height, m_radius);
#else
            dc.DrawRoundedRectangle(FromDIP(4), FromDIP(4) + top, size.x - FromDIP(8), curr_height, m_radius - 1);
#endif
        }
    }
    if (top > 2) {
        if (curr_height >= FromDIP(6)) {
            dc.DrawRectangle(FromDIP(4), FromDIP(4) + top, size.x - FromDIP(8), FromDIP(2));
            if (tmp_lib_colour.Red() > 238 && tmp_lib_colour.Green() > 238 && tmp_lib_colour.Blue() > 238) {
                dc.SetPen(wxPen(wxColour(130, 129, 128), 1, wxSOLID));
                dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
                dc.DrawLine(FromDIP(4), FromDIP(4) + top, size.x - FromDIP(4), FromDIP(4) + top);
            }
        }
        else {
            dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
            if (tmp_lib_colour.Red() > 238 && tmp_lib_colour.Green() > 238 && tmp_lib_colour.Blue() > 238) {
                dc.SetPen(wxPen(wxColour(130, 129, 128), 2, wxSOLID));
            }
            else {
                dc.SetPen(wxPen(tmp_lib_colour, 2, wxSOLID));
            }
#ifdef __APPLE__
            dc.DrawLine(FromDIP(5), FromDIP(4) + height - FromDIP(2), size.x - FromDIP(5), FromDIP(4) + height - FromDIP(2));
            dc.DrawLine(FromDIP(6), FromDIP(4) + height - FromDIP(1), size.x - FromDIP(6), FromDIP(4) + height - FromDIP(1));
#else
            dc.DrawLine(FromDIP(4), FromDIP(4) + height - FromDIP(2), size.x - FromDIP(4), FromDIP(4) + height - FromDIP(2));
            dc.DrawLine(FromDIP(5), FromDIP(4) + height - FromDIP(1), size.x - FromDIP(5), FromDIP(4) + height - FromDIP(1));
#endif
        }
    }
    //border
    dc.SetPen(wxPen(wxColour(130, 130, 128), 1, wxSOLID));
    dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
#ifdef __APPLE__
    dc.DrawRoundedRectangle(FromDIP(4), FromDIP(4), size.x - FromDIP(7), size.y - FromDIP(7), m_radius);
#else
    dc.DrawRoundedRectangle(FromDIP(3), FromDIP(3), size.x - FromDIP(6), size.y - FromDIP(6), m_radius);
#endif
    // edit icon
    if (m_info.material_state != AMSCanType::AMS_CAN_TYPE_EMPTY && m_info.material_state != AMSCanType::AMS_CAN_TYPE_NONE)
    {
        if (m_info.material_state == AMSCanType::AMS_CAN_TYPE_THIRDBRAND || m_info.material_state == AMSCanType::AMS_CAN_TYPE_VIRTUAL)
            dc.DrawBitmap(temp_bitmap_third.bmp(), (size.x - temp_bitmap_third.GetBmpSize().x) / 2, (size.y - FromDIP(10) - temp_bitmap_third.GetBmpSize().y));
        if (m_info.material_state == AMSCanType::AMS_CAN_TYPE_BRAND)
            dc.DrawBitmap(temp_bitmap_brand.bmp(), (size.x - temp_bitmap_brand.GetBmpSize().x) / 2, (size.y - FromDIP(10) - temp_bitmap_brand.GetBmpSize().y));
    }
}
References Slic3r::GUI::AMS_CAN_TYPE_BRAND, Slic3r::GUI::AMS_CAN_TYPE_EMPTY, Slic3r::GUI::AMS_CAN_TYPE_NONE, Slic3r::GUI::AMS_CAN_TYPE_THIRDBRAND, Slic3r::GUI::AMS_CAN_TYPE_VIRTUAL, AMS_CONTROL_BRAND_COLOUR, AMS_CONTROL_DEF_LIB_BK_COLOUR, m_bitmap_editable, m_bitmap_editable_light, m_bitmap_readonly, m_bitmap_readonly_light, m_hover, m_info, m_radius, m_selected, Slic3r::GUI::Caninfo::material_colour, Slic3r::GUI::Caninfo::material_cols, Slic3r::GUI::Caninfo::material_remain, Slic3r::GUI::Caninfo::material_state, and size.
Referenced by render().
EableSelected()
void Slic3r::GUI::AMSLib::EableSelected () inline
{ m_unable_selected = false; };
References m_unable_selected.
Enable()
bool Slic3r::GUI::AMSLib::Enable (bool enable = true) virtual
{ return wxWindow::Enable(enable); }
GetLibColour()
wxColour Slic3r::GUI::AMSLib::GetLibColour ()
{ return m_info.material_colour; }
References m_info, and Slic3r::GUI::Caninfo::material_colour.
Referenced by Slic3r::GUI::AmsCans::GetTagColr(), and Slic3r::GUI::AmsCans::SetAmsStep().
is_selected()
bool Slic3r::GUI::AMSLib::is_selected () inline
{return m_selected;};
References m_selected.
on_enter_window()
void Slic3r::GUI::AMSLib::on_enter_window (wxMouseEvent & evt) protected
{
    m_hover = true;
    Refresh();
}
References m_hover.
Referenced by AMSLib().
on_leave_window()
void Slic3r::GUI::AMSLib::on_leave_window (wxMouseEvent & evt) protected
{
    m_hover = false;
    Refresh();
}
References m_hover.
Referenced by AMSLib().
on_left_down()
void Slic3r::GUI::AMSLib::on_left_down (wxMouseEvent & evt) protected
{
    //dc.DrawBitmap(temp_bitmap, (size.x - m_bitmap_editable.GetSize().x) / 2, ( size.y - FromDIP(10) - temp_bitmap.GetSize().y) );
    if (m_info.material_state != AMSCanType::AMS_CAN_TYPE_EMPTY && m_info.material_state != AMSCanType::AMS_CAN_TYPE_NONE) {
        auto size = GetSize();
        auto pos  = evt.GetPosition();
        if (m_info.material_state == AMSCanType::AMS_CAN_TYPE_THIRDBRAND || m_info.material_state == AMSCanType::AMS_CAN_TYPE_BRAND ||
            m_info.material_state == AMSCanType::AMS_CAN_TYPE_VIRTUAL) {
            auto left = FromDIP(10);
            auto top = (size.y - FromDIP(15) - m_bitmap_editable_light.GetBmpSize().y);
            auto right = size.x - FromDIP(10);;
            auto bottom = size.y - FromDIP(15);
            if (pos.x >= left && pos.x <= right && pos.y >= top && top <= bottom) {
                if (m_selected) {
                    if (m_info.material_state == AMSCanType::AMS_CAN_TYPE_VIRTUAL) {
                        post_event(wxCommandEvent(EVT_VAMS_ON_FILAMENT_EDIT));
                    }
                    else {
                        post_event(wxCommandEvent(EVT_AMS_ON_FILAMENT_EDIT));
                    }
                } else {
                    BOOST_LOG_TRIVIAL(trace) << "current amslib is not selected";
                }
            }
        }
    }
}
References Slic3r::GUI::AMS_CAN_TYPE_BRAND, Slic3r::GUI::AMS_CAN_TYPE_EMPTY, Slic3r::GUI::AMS_CAN_TYPE_NONE, Slic3r::GUI::AMS_CAN_TYPE_THIRDBRAND, Slic3r::GUI::AMS_CAN_TYPE_VIRTUAL, ScalableBitmap::GetBmpSize(), m_bitmap_editable_light, m_info, m_selected, Slic3r::GUI::Caninfo::material_state, post_event(), size, and Slic3r::trace().
Referenced by AMSLib().
OnSelected()
void Slic3r::GUI::AMSLib::OnSelected ()
{
    if (!wxWindow::IsEnabled()) return;
    if (m_unable_selected) return;
    post_event(wxCommandEvent(EVT_AMS_ON_SELECTED));
    m_selected = true;
    Refresh();
}
References m_selected, m_unable_selected, and post_event().
Referenced by Slic3r::GUI::AMSControl::AMSControl(), and Slic3r::GUI::AmsCans::SelectCan().
paintEvent()
void Slic3r::GUI::AMSLib::paintEvent (wxPaintEvent & evt) protected
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by AMSLib().
post_event()
void Slic3r::GUI::AMSLib::post_event (wxCommandEvent && event)
{
    event.SetString(m_info.can_id);
    event.SetEventObject(m_parent);
    wxPostEvent(m_parent, event);
    event.Skip();
}
References Slic3r::GUI::Caninfo::can_id, and m_info.
Referenced by on_left_down(), and OnSelected().
render()
void Slic3r::GUI::AMSLib::render (wxDC & dc) protected
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
    // text
    auto tmp_lib_colour  = m_info.material_colour;
    auto temp_text_colour = AMS_CONTROL_GRAY800;
    if (tmp_lib_colour.GetLuminance() < 0.5) {
        temp_text_colour = AMS_CONTROL_WHITE_COLOUR;
    } else {
        temp_text_colour = AMS_CONTROL_GRAY800;
    }
    if (m_info.material_remain < 50) {
        temp_text_colour = AMS_CONTROL_GRAY800;
    }
    //if (!wxWindow::IsEnabled()) {
        //temp_text_colour = AMS_CONTROL_DISABLE_TEXT_COLOUR;
    //}
    dc.SetFont(::Label::Body_13);
    dc.SetTextForeground(temp_text_colour);
    auto libsize = GetSize();
    if (m_info.material_state == AMSCanType::AMS_CAN_TYPE_THIRDBRAND
        || m_info.material_state == AMSCanType::AMS_CAN_TYPE_BRAND
        || m_info.material_state == AMSCanType::AMS_CAN_TYPE_VIRTUAL) {
        if (m_info.material_name.empty() &&  m_info.material_state != AMSCanType::AMS_CAN_TYPE_VIRTUAL) {
            auto tsize = dc.GetMultiLineTextExtent("?");
            auto pot = wxPoint(0, 0);
            if (m_show_kn) {
                pot = wxPoint((libsize.x - tsize.x) / 2, (libsize.y - tsize.y) / 2 - FromDIP(9));
            } else {
                pot = wxPoint((libsize.x - tsize.x) / 2, (libsize.y - tsize.y) / 2 + FromDIP(3));
            }
            dc.DrawText(L("?"), pot);
        } else {
            auto tsize = dc.GetMultiLineTextExtent(m_info.material_name);
            std::vector<std::string> split_char_arr = {" ", "-"};
            bool has_split = false;
            std::string has_split_char = " ";
            for (std::string split_char : split_char_arr) {
                if (m_info.material_name.find(split_char) != std::string::npos) {
                    has_split = true;
                    has_split_char = split_char;
                }
            }
            if (has_split) {
                dc.SetFont(::Label::Body_12);
                auto line_top    = m_info.material_name.substr(0, m_info.material_name.find(has_split_char));
                auto line_bottom = m_info.material_name.substr(m_info.material_name.find(has_split_char));
                auto line_top_tsize    = dc.GetMultiLineTextExtent(line_top);
                auto line_bottom_tsize = dc.GetMultiLineTextExtent(line_bottom);
                auto pot_top = wxPoint((libsize.x - line_top_tsize.x) / 2, (libsize.y - line_top_tsize.y) / 2 - line_top_tsize.y + FromDIP(6));
                dc.DrawText(line_top, pot_top);
                auto pot_bottom = wxPoint((libsize.x - line_bottom_tsize.x) / 2, (libsize.y - line_bottom_tsize.y) / 2 + FromDIP(6));
                dc.DrawText(line_bottom, pot_bottom);
            } else {
                auto pot = wxPoint(0, 0);
                if (m_obj && m_obj->is_function_supported(PrinterFunction::FUNC_EXTRUSION_CALI)) {
                    pot = wxPoint((libsize.x - tsize.x) / 2, (libsize.y - tsize.y) / 2 - FromDIP(9));
                } else {
                    pot = wxPoint((libsize.x - tsize.x) / 2, (libsize.y - tsize.y) / 2 + FromDIP(3));
                }
                dc.DrawText(m_info.material_name, pot);
            }
        }
        //draw k&n
        if (m_obj && m_obj->is_function_supported(PrinterFunction::FUNC_EXTRUSION_CALI)) {
            if (m_show_kn){
                wxString str_k = wxString::Format("K %1.3f", m_info.k);
                wxString str_n = wxString::Format("N %1.3f", m_info.n);
                dc.SetFont(::Label::Body_11);
                auto tsize = dc.GetMultiLineTextExtent(str_k);
                auto pot_k = wxPoint((libsize.x - tsize.x) / 2, (libsize.y - tsize.y) / 2 - FromDIP(9) + tsize.y);
                dc.DrawText(str_k, pot_k);
            }
        }
    }
    if (m_info.material_state == AMSCanType::AMS_CAN_TYPE_EMPTY) {
        auto tsize = dc.GetMultiLineTextExtent(_L("Empty"));
        auto pot   = wxPoint((libsize.x - tsize.x) / 2, (libsize.y - tsize.y) / 2 + FromDIP(3));
        dc.DrawText(_L("Empty"), pot);
    }
}
References _L, Slic3r::GUI::AMS_CAN_TYPE_BRAND, Slic3r::GUI::AMS_CAN_TYPE_EMPTY, Slic3r::GUI::AMS_CAN_TYPE_THIRDBRAND, Slic3r::GUI::AMS_CAN_TYPE_VIRTUAL, AMS_CONTROL_GRAY800, AMS_CONTROL_WHITE_COLOUR, Label::Body_11, Label::Body_12, Label::Body_13, doRender(), Slic3r::FUNC_EXTRUSION_CALI, Slic3r::MachineObject::is_function_supported(), Slic3r::GUI::Caninfo::k, L, m_info, m_obj, m_show_kn, Slic3r::GUI::Caninfo::material_colour, Slic3r::GUI::Caninfo::material_name, Slic3r::GUI::Caninfo::material_remain, Slic3r::GUI::Caninfo::material_state, Slic3r::GUI::Caninfo::n, and size.
Referenced by paintEvent().
show_kn_value()
void Slic3r::GUI::AMSLib::show_kn_value (bool show) inline
{ m_show_kn = show; };
References m_show_kn.
Referenced by Slic3r::GUI::AmsCans::show_sn_value(), and Slic3r::GUI::AMSControl::show_vams_kn_value().
support_cali()
void Slic3r::GUI::AMSLib::support_cali (bool sup) inline
{ m_support_cali = sup; Refresh(); };
References m_support_cali.
UnableSelected()
void Slic3r::GUI::AMSLib::UnableSelected () inline
{ m_unable_selected = true; };
References m_unable_selected.
UnSelected()
void Slic3r::GUI::AMSLib::UnSelected ()
{
    m_selected = false;
    Refresh();
}
References m_selected.
Referenced by Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsCans::SelectCan(), and Slic3r::GUI::AMSControl::SwitchAms().
Update()
void Slic3r::GUI::AMSLib::Update (Caninfo info, bool refresh = true)
{
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    if (dev->get_selected_machine() && dev->get_selected_machine() != m_obj) {
        m_obj = dev->get_selected_machine();
    }
    m_info = info;
    Layout();
    if (refresh) Refresh();
}
References Slic3r::DeviceManager::get_selected_machine(), m_info, and m_obj.
Referenced by Slic3r::GUI::AmsCans::Update().
Member Data Documentation
m_bitmap_editable
ScalableBitmap Slic3r::GUI::AMSLib::m_bitmap_editable protected
Referenced by create(), and doRender().
m_bitmap_editable_light
ScalableBitmap Slic3r::GUI::AMSLib::m_bitmap_editable_light protected
Referenced by create(), doRender(), and on_left_down().
m_bitmap_readonly
ScalableBitmap Slic3r::GUI::AMSLib::m_bitmap_readonly protected
Referenced by create(), and doRender().
m_bitmap_readonly_light
ScalableBitmap Slic3r::GUI::AMSLib::m_bitmap_readonly_light protected
Referenced by create(), and doRender().
m_border_color
wxColour Slic3r::GUI::AMSLib::m_border_color protected
Referenced by AMSLib().
m_can_index
int Slic3r::GUI::AMSLib::m_can_index
Referenced by Slic3r::GUI::AmsCans::AddCan(), Slic3r::GUI::AmsCans::SelectCan(), and Slic3r::GUI::AmsCans::SetDefSelectCan().
m_edit_bitmp
wxStaticBitmap* Slic3r::GUI::AMSLib::m_edit_bitmp = {nullptr} protected
m_edit_bitmp_light
wxStaticBitmap* Slic3r::GUI::AMSLib::m_edit_bitmp_light = {nullptr} protected
m_enable
bool Slic3r::GUI::AMSLib::m_enable = {false} protected
m_hover
bool Slic3r::GUI::AMSLib::m_hover = {false} protected
Referenced by doRender(), on_enter_window(), and on_leave_window().
m_info
Caninfo Slic3r::GUI::AMSLib::m_info
Referenced by doRender(), GetLibColour(), Slic3r::GUI::AmsCans::GetTagColr(), on_left_down(), post_event(), render(), Slic3r::GUI::AMSControl::reset_vams(), Slic3r::GUI::AmsCans::SelectCan(), Slic3r::GUI::AmsCans::SetAmsStep(), Slic3r::GUI::AmsCans::SetDefSelectCan(), Update(), and Slic3r::GUI::AMSControl::update_vams_kn_value().
m_lib_color
wxColour Slic3r::GUI::AMSLib::m_lib_color protected
m_obj
MachineObject* Slic3r::GUI::AMSLib::m_obj = {nullptr}
Referenced by render(), Update(), and Slic3r::GUI::AMSControl::update_vams_kn_value().
m_radius
double Slic3r::GUI::AMSLib::m_radius = {4} protected
Referenced by doRender().
m_road_def_color
wxColour Slic3r::GUI::AMSLib::m_road_def_color protected
Referenced by AMSLib().
m_selected
bool Slic3r::GUI::AMSLib::m_selected = {false} protected
Referenced by doRender(), is_selected(), on_left_down(), OnSelected(), and UnSelected().
m_show_kn
bool Slic3r::GUI::AMSLib::m_show_kn = {false} protected
Referenced by render(), and show_kn_value().
m_support_cali
bool Slic3r::GUI::AMSLib::m_support_cali = {false} protected
Referenced by support_cali().
m_unable_selected
bool Slic3r::GUI::AMSLib::m_unable_selected = {false} protected
Referenced by EableSelected(), OnSelected(), and UnableSelected().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AMSControl.hpp
src/slic3r/GUI/Widgets/AMSControl.cpp