OrcaSlicer: Slic3r::CutObjectBase Class Reference
Slic3r::CutObjectBase Class Reference
#include <src/libslic3r/ObjectID.hpp>
Public Types
using Timestamp = uint64_t
Public Member Functions
CutObjectBase ()
CutObjectBase (int)
CutObjectBase (ObjectID id, size_t check_sum, size_t connectors_cnt)
virtual ~CutObjectBase ()=default
bool operator< (const CutObjectBase &other) const
bool operator== (const CutObjectBase &other) const
void copy (const CutObjectBase &rhs)
CutObjectBase & operator= (const CutObjectBase &other)
void invalidate ()
void init ()
bool has_same_id (const CutObjectBase &rhs)
bool is_equal (const CutObjectBase &rhs)
size_t check_sum () const
void set_check_sum (size_t cs)
void increase_check_sum (size_t cnt)
size_t connectors_cnt () const
void increase_connectors_cnt (size_t connectors_cnt)
ObjectID id () const
virtual Timestamp timestamp () const
Protected Member Functions
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
size_t m_check_sum {1}
size_t m_connectors_cnt {0}
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class cereal::access
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
CutObjectBase() [1/3]
Slic3r::CutObjectBase::CutObjectBase () inline
: ObjectBase(-1) {}
CutObjectBase() [2/3]
Slic3r::CutObjectBase::CutObjectBase (int) inline
: ObjectBase(-1) {}
CutObjectBase() [3/3]
Slic3r::CutObjectBase::CutObjectBase (ObjectID id, size_t check_sum, size_t connectors_cnt) inline
: ObjectBase(id), m_check_sum(check_sum), m_connectors_cnt(connectors_cnt) {}
~CutObjectBase()
virtual Slic3r::CutObjectBase::~CutObjectBase () virtual default
Member Function Documentation
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
check_sum()
size_t Slic3r::CutObjectBase::check_sum () const inline
{ return m_check_sum; }
References m_check_sum.
Referenced by copy(), and is_equal().
connectors_cnt()
size_t Slic3r::CutObjectBase::connectors_cnt () const inline
{ return m_connectors_cnt; }
References m_connectors_cnt.
Referenced by Slic3r::ModelObject::apply_cut_connectors(), copy(), increase_connectors_cnt(), and is_equal().
copy()
void Slic3r::CutObjectBase::copy (const CutObjectBase & rhs) inline
    {
        this->copy_id(rhs);
        this->m_check_sum      = rhs.check_sum();
        this->m_connectors_cnt = rhs.connectors_cnt();
    }
References check_sum(), connectors_cnt(), Slic3r::ObjectBase::copy_id(), m_check_sum, and m_connectors_cnt.
Referenced by operator=().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by copy().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
has_same_id()
bool Slic3r::CutObjectBase::has_same_id (const CutObjectBase & rhs) inline
{ return this->id() == rhs.id(); }
References Slic3r::ObjectBase::id().
Referenced by Slic3r::GUI::ObjectList::fix_cut_selection().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
increase_check_sum()
void Slic3r::CutObjectBase::increase_check_sum (size_t cnt) inline
{ m_check_sum += cnt; }
References m_check_sum.
Referenced by Slic3r::ModelObject::apply_cut_attributes().
increase_connectors_cnt()
void Slic3r::CutObjectBase::increase_connectors_cnt (size_t connectors_cnt) inline
{ m_connectors_cnt += connectors_cnt; }
References connectors_cnt(), and m_connectors_cnt.
Referenced by Slic3r::ModelObject::apply_cut_connectors().
init()
void Slic3r::CutObjectBase::init () inline
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
Referenced by Slic3r::ModelObject::apply_cut_attributes().
invalidate()
void Slic3r::CutObjectBase::invalidate () inline
    {
        set_invalid_id();
        m_check_sum      = 1;
        m_connectors_cnt = 0;
    }
References m_check_sum, m_connectors_cnt, and Slic3r::ObjectBase::set_invalid_id().
Referenced by Slic3r::ModelObject::invalidate_cut().
is_equal()
bool Slic3r::CutObjectBase::is_equal (const CutObjectBase & rhs) inline
{ return this->id() == rhs.id() && this->check_sum() == rhs.check_sum() && this->connectors_cnt() == rhs.connectors_cnt(); }
References check_sum(), connectors_cnt(), and Slic3r::ObjectBase::id().
Referenced by Slic3r::GUI::ObjectList::delete_all_connectors_for_object(), and Slic3r::GUI::ObjectList::invalidate_cut_info_for_object().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
operator<()
bool Slic3r::CutObjectBase::operator< (const CutObjectBase & other) const inline
{ return other.id() > this->id(); }
References Slic3r::ObjectBase::id().
operator=()
CutObjectBase & Slic3r::CutObjectBase::operator= (const CutObjectBase & other) inline
    {
        this->copy(other);
        return *this;
    }
References copy().
operator==()
bool Slic3r::CutObjectBase::operator== (const CutObjectBase & other) const inline
{ return other.id() == this->id(); }
References Slic3r::ObjectBase::id().
serialize()
template<class Archive > void Slic3r::CutObjectBase::serialize (Archive & ar) inline private
    {
        ar(cereal::base_class<ObjectBase>(this));
        ar(m_check_sum, m_connectors_cnt);
    }
References m_check_sum, and m_connectors_cnt.
set_check_sum()
void Slic3r::CutObjectBase::set_check_sum (size_t cs) inline
{ m_check_sum = cs; }
References m_check_sum.
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
m_check_sum
size_t Slic3r::CutObjectBase::m_check_sum {1} private
Referenced by check_sum(), copy(), increase_check_sum(), invalidate(), serialize(), and set_check_sum().
m_connectors_cnt
size_t Slic3r::CutObjectBase::m_connectors_cnt {0} private
Referenced by connectors_cnt(), copy(), increase_connectors_cnt(), invalidate(), and serialize().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
The documentation for this class was generated from the following file:
src/libslic3r/ObjectID.hpp