OrcaSlicer: Slic3r::GUI::OrientJob Class Reference
Slic3r::GUI::OrientJob Class Reference
#include <src/slic3r/GUI/Jobs/OrientJob.hpp>
Public Types
enum JobPrepareState { PREPARE_STATE_DEFAULT = 0 , PREPARE_STATE_MENU = 1 }
Public Member Functions
OrientJob (std::shared_ptr< ProgressIndicator > pri, Plater *plater)
void process () override
void finalize () override
bool is_finalized () const
void start ()
bool join (int timeout_ms=0)
bool is_running () const
void cancel ()
Static Public Member Functions
static orientation::OrientMesh get_orient_mesh (ModelInstance *instance)
Protected Member Functions
void prepare () override
void on_exception (const std::exception_ptr &) override
virtual int status_range () const
void update_status (int st, const wxString &msg="")
void update_percent_finish ()
void show_networking_test (wxString msg)
bool was_canceled () const
Protected Attributes
Plater * m_plater
bool only_on_partplate {false}
Private Types
using OrientMesh = orientation::OrientMesh
using OrientMeshs = orientation::OrientMeshs
Private Member Functions
void clear_input ()
void prepare_selection (std::vector< bool > obj_sel, bool only_one_plate)
void prepare_selected ()
void prepare_partplate ()
void run (std::exception_ptr &)
Private Attributes
OrientMeshs m_selected
OrientMeshs m_unselected
OrientMeshs m_unprintable
int m_range = 100
int m_thread_evt_id = wxID_ANY
boost::thread m_thread
std::atomic< bool > m_running {false}
std::atomic< bool > m_canceled {false}
bool m_finalized = false
bool m_finalizing = false
std::shared_ptr< ProgressIndicator > m_progress
std::exception_ptr m_worker_error = nullptr
Detailed Description
Member Typedef Documentation
OrientMesh
using Slic3r::GUI::OrientJob::OrientMesh = orientation::OrientMesh private
OrientMeshs
using Slic3r::GUI::OrientJob::OrientMeshs = orientation::OrientMeshs private
Member Enumeration Documentation
JobPrepareState
enum Slic3r::GUI::Job::JobPrepareState inherited
Enumerator
PREPARE_STATE_DEFAULT
PREPARE_STATE_MENU
{
        PREPARE_STATE_DEFAULT = 0,
        PREPARE_STATE_MENU = 1,
    };
Constructor & Destructor Documentation
OrientJob()
Slic3r::GUI::OrientJob::OrientJob (std::shared_ptr< ProgressIndicator > pri, Plater * plater) inline
        : PlaterJob{std::move(pri), plater}
    {}
Member Function Documentation
cancel()
void Slic3r::GUI::Job::cancel () inline inherited
{ m_canceled.store(true); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::UpgradeNetworkJob::process().
clear_input()
void Slic3r::GUI::OrientJob::clear_input () private
{
    const Model &model = m_plater->model();
    size_t count = 0, cunprint = 0; // To know how much space to reserve
    for (auto obj : model.objects)
        for (auto mi : obj->instances)
            mi->printable ? count++ : cunprint++;
    m_selected.clear();
    m_unselected.clear();
    m_unprintable.clear();
    m_selected.reserve(count);
    m_unselected.reserve(count);
    m_unprintable.reserve(cunprint);
}
References count, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unprintable, m_unselected, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by prepare_partplate(), and prepare_selected().
finalize()
void Slic3r::GUI::OrientJob::finalize () override virtual
Reimplemented from Slic3r::GUI::Job.
{
    // Ignore the arrange result if aborted.
    if (was_canceled()) return;
    for (OrientMesh& mesh : m_selected)
    {
        mesh.apply();
    }
    m_plater->update();
    // BBS
    //wxGetApp().obj_manipul()->set_dirty();
    Job::finalize();
}
References Slic3r::GUI::Job::finalize(), Slic3r::GUI::PlaterJob::m_plater, m_selected, Slic3r::GUI::Plater::update(), and Slic3r::GUI::Job::was_canceled().
get_orient_mesh()
orientation::OrientMesh Slic3r::GUI::OrientJob::get_orient_mesh (ModelInstance * instance) static
{
    using OrientMesh = orientation::OrientMesh;
    OrientMesh om;
    auto obj = instance->get_object();
    om.name = obj->name;
    om.mesh = obj->mesh(); // don't know the difference to obj->raw_mesh(). Both seem OK
    if (obj->config.has("support_threshold_angle"))
        om.overhang_angle = obj->config.opt_int("support_threshold_angle");
    else {
        const Slic3r::DynamicPrintConfig& config = wxGetApp().preset_bundle->full_config();
        om.overhang_angle = config.opt_int("support_threshold_angle");
    }
    om.setter = [instance](const OrientMesh& p) {
        instance->rotate(p.rotation_matrix);
        instance->get_object()->ensure_on_bed();
    };
    return om;
}
References Slic3r::ModelObject::ensure_on_bed(), Slic3r::ModelInstance::get_object(), Slic3r::orientation::OrientMesh::mesh, Slic3r::orientation::OrientMesh::name, Slic3r::DynamicConfig::opt_int(), Slic3r::orientation::OrientMesh::overhang_angle, Slic3r::ModelInstance::rotate(), and Slic3r::orientation::OrientMesh::setter.
Referenced by prepare_selection().
is_finalized()
bool Slic3r::GUI::Job::is_finalized () const inline inherited
{ return m_finalized; }
References Slic3r::GUI::Job::m_finalized.
is_running()
bool Slic3r::GUI::Job::is_running () const inline inherited
{ return m_running.load(); }
References Slic3r::GUI::Job::m_running.
join()
bool Slic3r::GUI::Job::join (int timeout_ms = 0) inherited
{
    if (!m_thread.joinable()) return true;
    if (timeout_ms <= 0)
        m_thread.join();
    else if (!m_thread.try_join_for(boost::chrono::milliseconds(timeout_ms)))
        return false;
    return true;
}
on_exception()
void Slic3r::GUI::OrientJob::on_exception (const std::exception_ptr & eptr) override protected virtual
Reimplemented from Slic3r::GUI::Job.
{
    try {
        if (eptr)
            std::rethrow_exception(eptr);
    } catch (std::exception &) {
        PlaterJob::on_exception(eptr);
    }
}
References Slic3r::GUI::PlaterJob::on_exception().
prepare()
void Slic3r::GUI::OrientJob::prepare () override protected virtual
Reimplemented from Slic3r::GUI::Job.
{
    int state = m_plater->get_prepare_state();
    m_plater->get_notification_manager()->bbl_close_plateinfo_notification();
    if (state == Job::JobPrepareState::PREPARE_STATE_DEFAULT) {
        only_on_partplate = false;
        prepare_selected();
    }
    else if (state == Job::JobPrepareState::PREPARE_STATE_MENU) {
        only_on_partplate = true;   // only arrange items on current plate
        prepare_partplate();
    }
}
References Slic3r::GUI::NotificationManager::bbl_close_plateinfo_notification(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::GUI::Plater::get_prepare_state(), Slic3r::GUI::PlaterJob::m_plater, Slic3r::GUI::PlaterJob::only_on_partplate, prepare_partplate(), prepare_selected(), Slic3r::GUI::Job::PREPARE_STATE_DEFAULT, and Slic3r::GUI::Job::PREPARE_STATE_MENU.
prepare_partplate()
void Slic3r::GUI::OrientJob::prepare_partplate () private
{
    clear_input();
    PartPlateList& plate_list = m_plater->get_partplate_list();
    PartPlate* plate = plate_list.get_curr_plate();
    assert(plate != nullptr);
    if (plate->empty())
    {
        //no instances on this plate
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": no instances in current plate!");
        return;
    }
    if (plate->is_locked()) {
        m_plater->get_notification_manager()->push_notification(NotificationType::BBLPlateInfo,
            NotificationManager::NotificationLevel::WarningNotificationLevel, into_u8(_L("This plate is locked,\nWe can not do auto-orient on this plate.")));
        return;
    }
    Model& model = m_plater->model();
    std::vector<bool> obj_sel(model.objects.size(), false);
    // Go through the objects and check if inside the selection
    for (size_t oidx = 0; oidx < model.objects.size(); ++oidx)
    {
        ModelObject* mo = model.objects[oidx];
        for (size_t inst_idx = 0; inst_idx < mo->instances.size(); ++inst_idx)
        {
            obj_sel[oidx] = plate->contain_instance(oidx, inst_idx);
        }
    }
    prepare_selection(obj_sel, true);
}
References _L, Slic3r::GUI::BBLPlateInfo, clear_input(), Slic3r::GUI::PartPlate::contain_instance(), Slic3r::GUI::PartPlate::empty(), Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::ModelObject::instances, Slic3r::GUI::into_u8(), Slic3r::GUI::PartPlate::is_locked(), Slic3r::GUI::PlaterJob::m_plater, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, prepare_selection(), Slic3r::GUI::NotificationManager::push_notification(), and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
Referenced by prepare().
prepare_selected()
void Slic3r::GUI::OrientJob::prepare_selected () private
{
    clear_input();
    Model &model = m_plater->model();
    std::vector<bool> obj_sel(model.objects.size(), false);
    for (auto &s : m_plater->get_selection().get_content())
        if (s.first < int(obj_sel.size()))
            obj_sel[size_t(s.first)] = !s.second.empty();
   //BBS: add only one plate mode
    prepare_selection(obj_sel, false);
}
References clear_input(), Slic3r::GUI::Selection::get_content(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::PlaterJob::m_plater, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, and prepare_selection().
Referenced by prepare().
prepare_selection()
void Slic3r::GUI::OrientJob::prepare_selection (std::vector< bool > obj_sel, bool only_one_plate) private
{
    Model& model = m_plater->model();
    PartPlateList& plate_list = m_plater->get_partplate_list();
    //OrientMeshs selected_in_lock, unselect_in_lock;
    bool selected_is_locked = false;
    // Go through the objects and check if inside the selection
    for (size_t oidx = 0; oidx < obj_sel.size(); ++oidx) {
        bool selected = obj_sel[oidx];
        ModelObject* mo = model.objects[oidx];
        for (size_t inst_idx = 0; inst_idx < mo->instances.size(); ++inst_idx)
        {
            ModelInstance* mi = mo->instances[inst_idx];
            OrientMesh&& om = get_orient_mesh(mi);
            bool locked = false;
            if (!only_one_plate) {
                int plate_index = plate_list.find_instance(oidx, inst_idx);
                if ((plate_index >= 0)&&(plate_index < plate_list.get_plate_count())) {
                    if (plate_list.is_locked(plate_index)) {
                        if (selected) {
                            //selected_in_lock.emplace_back(std::move(om));
                            selected_is_locked = true;
                        }
                        //else
                        //    unselect_in_lock.emplace_back(std::move(om));
                        continue;
                    }
                }
            }
            auto& cont = mo->printable ? (selected ? m_selected : m_unselected) : m_unprintable;
            cont.emplace_back(std::move(om));
        }
    }
    // If the selection was empty orient everything
    if (m_selected.empty()) {
        if (!selected_is_locked) {
            m_selected.swap(m_unselected);
            //m_unselected.insert(m_unselected.begin(), unselect_in_lock.begin(), unselect_in_lock.end());
        }
        else {
            m_plater->get_notification_manager()->push_notification(NotificationType::BBLPlateInfo,
                NotificationManager::NotificationLevel::WarningNotificationLevel, into_u8(_L("All the selected objects are on the locked plate,\nWe can not do auto-orient on these objects.")));
        }
    }
}
References _L, Slic3r::GUI::BBLPlateInfo, Slic3r::GUI::PartPlateList::find_instance(), Slic3r::GUI::Plater::get_notification_manager(), get_orient_mesh(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::PartPlateList::get_plate_count(), Slic3r::ModelObject::instances, Slic3r::GUI::into_u8(), Slic3r::GUI::PartPlateList::is_locked(), Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unprintable, m_unselected, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::ModelObject::printable, Slic3r::GUI::NotificationManager::push_notification(), and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
Referenced by prepare_partplate(), and prepare_selected().
process()
void Slic3r::GUI::OrientJob::process () override virtual
Implements Slic3r::GUI::Job.
{
    auto start = std::chrono::steady_clock::now();
    static const auto arrangestr = _(L("Orienting..."));
    const GLCanvas3D::OrientSettings& settings = m_plater->canvas3D()->get_orient_settings();
    orientation::OrientParams params;
    orientation::OrientParamsArea params_area;
    if (settings.min_area) {
        memcpy(&params, &params_area, sizeof(params));
        params.min_volume = false;
    }
    else {
        params.min_volume = true;
    }
    auto count = unsigned(m_selected.size() + m_unprintable.size());
    params.stopcondition = [this]() { return was_canceled(); };
    params.progressind = [this, count](unsigned st, std::string orientstr) {
        st += m_unprintable.size();
        if (st > 0) update_status(int(st / float(count) * 100), _L("Orienting") + " " + orientstr);
    };
    orientation::orient(m_selected, m_unselected, params);
    auto time_elapsed = std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - start);
    std::stringstream ss;
    if (!m_selected.empty())
        ss << std::fixed << std::setprecision(3) << "Orient " << m_selected.back().name << " in " << time_elapsed.count() << " seconds. "
        << "Orientation: " << m_selected.back().orientation.transpose() << "; v,phi: " << m_selected.back().axis.transpose() << ", " << m_selected.back().angle << "; euler: " << m_selected.back().euler_angles.transpose();
    // finalize just here.
    //update_status(int(count),
    //    was_canceled() ? _(L("Orienting canceled."))
    //    : _(L(ss.str().c_str())));
    wxGetApp().plater()->show_status_message(was_canceled() ? "Orienting canceled." : ss.str());
}
References _, _L, Slic3r::GUI::Plater::canvas3D(), count, Slic3r::GUI::GLCanvas3D::get_orient_settings(), L, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unprintable, m_unselected, memcpy, Slic3r::GUI::GLCanvas3D::OrientSettings::min_area, Slic3r::orientation::OrientParams::min_volume, Slic3r::orientation::orient(), Slic3r::orientation::OrientParams::progressind, Slic3r::GUI::Job::start(), Slic3r::orientation::OrientParams::stopcondition, Slic3r::GUI::Job::update_status(), and Slic3r::GUI::Job::was_canceled().
run()
void Slic3r::GUI::Job::run (std::exception_ptr & eptr) private inherited
{
    m_running.store(true);
    try {
        process();
    } catch (...) {
        eptr = std::current_exception();
    }
    m_running.store(false);
    // ensure to call the last status to finalize the job
    update_status(status_range(), "");
}
References Slic3r::GUI::Job::m_running, Slic3r::GUI::Job::process(), Slic3r::GUI::Job::status_range(), and Slic3r::GUI::Job::update_status().
show_networking_test()
void Slic3r::GUI::Job::show_networking_test (wxString msg) protected inherited
{
    m_progress->show_networking_test(msg);
}
Referenced by Slic3r::GUI::PrintJob::process().
start()
void Slic3r::GUI::Job::start () inherited
{ // Start the job. No effect if the job is already running
    if (!m_running.load()) {
        prepare();
        // Save the current status indicatior range and push the new one
        m_range = m_progress->get_range();
        m_progress->set_range(status_range());
        // init cancellation flag and set the cancel callback
        m_canceled.store(false);
        m_progress->set_cancel_callback(
                    [this]() { m_canceled.store(true); });
        m_finalized  = false;
        m_finalizing = false;
        // Changing cursor to busy
        wxBeginBusyCursor();
        try { // Execute the job
            m_worker_error = nullptr;
            m_thread = create_thread([this] { this->run(m_worker_error); });
        } catch (std::exception &) {
            update_status(status_range(),
                          _(L("Error! Unable to create thread!")));
        }
        // The state changes will be undone when the process hits the
        // last status value, in the status update handler (see ctor)
    }
}
References _, Slic3r::create_thread(), and L.
Referenced by process().
status_range()
virtual int Slic3r::GUI::Job::status_range () const inline protected virtual inherited
Reimplemented in Slic3r::GUI::ArrangeJob, Slic3r::GUI::BindJob, Slic3r::GUI::FillBedJob, Slic3r::GUI::PrintJob, Slic3r::GUI::SendJob, and Slic3r::GUI::UpgradeNetworkJob.
{ return 100; }
Referenced by Slic3r::GUI::Job::Job(), and Slic3r::GUI::Job::run().
update_percent_finish()
void Slic3r::GUI::Job::update_percent_finish () protected inherited
{
    m_progress->clear_percent();
}
Referenced by Slic3r::GUI::PrintJob::process().
update_status()
void Slic3r::GUI::Job::update_status (int st, const wxString & msg = "") protected inherited
{
    auto evt = new wxThreadEvent(wxEVT_THREAD, m_thread_evt_id);
    evt->SetInt(st);
    evt->SetString(msg);
    wxQueueEvent(this, evt);
}
Referenced by Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), Slic3r::GUI::Job::run(), Slic3r::GUI::BindJob::update_status(), and Slic3r::GUI::UpgradeNetworkJob::update_status().
was_canceled()
bool Slic3r::GUI::Job::was_canceled () const inline protected inherited
{ return m_canceled.load(); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::BindJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), finalize(), Slic3r::GUI::PrintJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SendJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::UpgradeNetworkJob::finalize(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), and Slic3r::GUI::UpgradeNetworkJob::process().
Member Data Documentation
m_canceled
std::atomic<bool> Slic3r::GUI::Job::m_canceled {false} private inherited
Referenced by Slic3r::GUI::Job::cancel(), and Slic3r::GUI::Job::was_canceled().
m_finalized
bool Slic3r::GUI::Job::m_finalized = false private inherited
Referenced by Slic3r::GUI::Job::Job(), Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::is_finalized().
m_finalizing
bool Slic3r::GUI::Job::m_finalizing = false private inherited
Referenced by Slic3r::GUI::Job::Job().
m_plater
Plater* Slic3r::GUI::PlaterJob::m_plater protected inherited
Referenced by Slic3r::GUI::ArrangeJob::check_unprintable(), Slic3r::GUI::ArrangeJob::clear_input(), clear_input(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::ArrangeJob::on_exception(), Slic3r::GUI::PlaterJob::on_exception(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::FillBedJob::prepare(), prepare(), Slic3r::GUI::PrintJob::prepare(), Slic3r::GUI::RotoptimizeJob::prepare(), Slic3r::GUI::SendJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), prepare_selected(), prepare_selection(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), and Slic3r::GUI::SLAImportJob::reset().
m_progress
std::shared_ptr<ProgressIndicator> Slic3r::GUI::Job::m_progress private inherited
Referenced by Slic3r::GUI::Job::Job().
m_range
int Slic3r::GUI::Job::m_range = 100 private inherited
Referenced by Slic3r::GUI::Job::Job().
m_running
std::atomic<bool> Slic3r::GUI::Job::m_running {false} private inherited
Referenced by Slic3r::GUI::Job::is_running(), and Slic3r::GUI::Job::run().
m_selected
OrientMeshs Slic3r::GUI::OrientJob::m_selected private
Referenced by clear_input(), finalize(), prepare_selection(), and process().
m_thread
boost::thread Slic3r::GUI::Job::m_thread private inherited
m_thread_evt_id
int Slic3r::GUI::Job::m_thread_evt_id = wxID_ANY private inherited
Referenced by Slic3r::GUI::Job::Job().
m_unprintable
OrientMeshs Slic3r::GUI::OrientJob::m_unprintable private
Referenced by clear_input(), prepare_selection(), and process().
m_unselected
OrientMeshs Slic3r::GUI::OrientJob::m_unselected private
Referenced by clear_input(), prepare_selection(), and process().
m_worker_error
std::exception_ptr Slic3r::GUI::Job::m_worker_error = nullptr private inherited
Referenced by Slic3r::GUI::Job::Job().
only_on_partplate
bool Slic3r::GUI::PlaterJob::only_on_partplate {false} protected inherited
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::ArrangeJob::prepare(), prepare(), and Slic3r::GUI::ArrangeJob::prepare_wipe_tower().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/OrientJob.hpp
src/slic3r/GUI/Jobs/OrientJob.cpp