OrcaSlicer: StaticBambuLib Struct Reference
StaticBambuLib Struct Reference
Static Public Member Functions
static StaticBambuLib & get ()
static int Fake_Bambu_Create (Bambu_Tunnel *, char const *)
Detailed Description
Member Function Documentation
Fake_Bambu_Create()
static int StaticBambuLib::Fake_Bambu_Create (Bambu_Tunnel * , char const *) inline static
{ return -2; }
Referenced by get().
get()
StaticBambuLib & StaticBambuLib::get () static
{
    static StaticBambuLib lib;
    // first load the library
    if (lib.Bambu_Open)
        return lib;
    if (!module) {
        module = Slic3r::NetworkAgent::get_bambu_source_entry();
    }
    if (!module) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", can not Load Library";
    }
    GET_FUNC(Bambu_Create);
    GET_FUNC(Bambu_Open);
    GET_FUNC(Bambu_StartStream);
    GET_FUNC(Bambu_GetStreamCount);
    GET_FUNC(Bambu_GetStreamInfo);
    GET_FUNC(Bambu_SendMessage);
    GET_FUNC(Bambu_ReadSample);
    GET_FUNC(Bambu_Close);
    GET_FUNC(Bambu_Destroy);
    GET_FUNC(Bambu_SetLogger);
    GET_FUNC(Bambu_FreeLogMsg);
    if (!lib.Bambu_Open)
        lib.Bambu_Create = Fake_Bambu_Create;
    return lib;
}
References Bambu_Close(), Bambu_Create(), Bambu_Destroy(), Bambu_FreeLogMsg(), Bambu_GetStreamCount(), Bambu_GetStreamInfo(), Bambu_Open(), Bambu_ReadSample(), Bambu_SendMessage(), Bambu_SetLogger(), Bambu_StartStream(), Fake_Bambu_Create(), Slic3r::NetworkAgent::get_bambu_source_entry(), GET_FUNC, and module.
Referenced by bambulib_get().
The documentation for this struct was generated from the following file:
src/slic3r/GUI/Printer/PrinterFileSystem.cpp