OrcaSlicer: Slic3r::DynamicPrintAndCLIConfig Class Reference
Slic3r::DynamicPrintAndCLIConfig Class Reference
#include <src/libslic3r/PrintConfig.hpp>
Classes
class PrintAndCLIConfigDef
Public Member Functions
DynamicPrintAndCLIConfig ()
DynamicPrintAndCLIConfig (const DynamicPrintAndCLIConfig &other)
const ConfigDef * def () const override
void handle_legacy (t_config_option_key &opt_key, std::string &value) const override
void normalize_fdm (int used_filaments=0)
void normalize_fdm_1 ()
t_config_option_keys normalize_fdm_2 (int num_objects, int used_filaments=0)
void set_num_extruders (unsigned int num_extruders)
void set_num_filaments (unsigned int num_filaments)
std::map< std::string, std::string > validate (bool under_cli=false)
std::string get_filament_type (std::string &displayed_filament_type, int id=0)
bool is_custom_defined ()
DynamicConfig & operator+= (const DynamicConfig &rhs)
DynamicConfig & operator+= (DynamicConfig &&rhs)
bool operator== (const DynamicConfig &rhs) const
bool operator!= (const DynamicConfig &rhs) const
void swap (DynamicConfig &other)
void clear ()
bool erase (const t_config_option_key &opt_key)
size_t remove_nil_options ()
template<class T >
T * opt (const t_config_option_key &opt_key, bool create=false)
template<class T >
const T * opt (const t_config_option_key &opt_key) const
const ConfigOption * optptr (const t_config_option_key &opt_key) const override
ConfigOption * optptr (const t_config_option_key &opt_key, bool create=false) override
t_config_option_keys keys () const override
bool empty () const
bool set_key_value (const std::string &opt_key, ConfigOption *opt)
bool equals (const DynamicConfig &other, const std::set< std::string > *skipped_keys=nullptr) const
bool equals (const ConfigBase &other, const std::set< std::string > *skipped_keys=nullptr) const
t_config_option_keys diff (const DynamicConfig &other) const
t_config_option_keys diff (const ConfigBase &other) const
t_config_option_keys equal (const DynamicConfig &other) const
t_config_option_keys equal (const ConfigBase &other) const
std::string & opt_string (const t_config_option_key &opt_key, bool create=false)
const std::string & opt_string (const t_config_option_key &opt_key) const
std::string & opt_string (const t_config_option_key &opt_key, unsigned int idx)
const std::string & opt_string (const t_config_option_key &opt_key, unsigned int idx) const
double & opt_float (const t_config_option_key &opt_key)
const double & opt_float (const t_config_option_key &opt_key) const
double & opt_float (const t_config_option_key &opt_key, unsigned int idx)
const double & opt_float (const t_config_option_key &opt_key, unsigned int idx) const
int & opt_int (const t_config_option_key &opt_key)
int opt_int (const t_config_option_key &opt_key) const
int & opt_int (const t_config_option_key &opt_key, unsigned int idx)
int opt_int (const t_config_option_key &opt_key, unsigned int idx) const
template<typename ENUM >
ENUM opt_enum (const t_config_option_key &opt_key) const
int opt_enum (const t_config_option_key &opt_key, unsigned int idx) const
bool opt_bool (const t_config_option_key &opt_key) const
bool opt_bool (const t_config_option_key &opt_key, unsigned int idx) const
bool read_cli (int argc, const char *const argv[], t_config_option_keys *extra, t_config_option_keys *keys=nullptr)
std::map< t_config_option_key, std::unique_ptr< ConfigOption > >::const_iterator cbegin () const
std::map< t_config_option_key, std::unique_ptr< ConfigOption > >::const_iterator cend () const
size_t size () const
ConfigOption * option (const t_config_option_key &opt_key, bool create=false)
template<typename TYPE >
TYPE * option (const t_config_option_key &opt_key, bool create=false)
const ConfigOption * option (const t_config_option_key &opt_key) const
template<typename TYPE >
const TYPE * option (const t_config_option_key &opt_key) const
ConfigOption * option_throw (const t_config_option_key &opt_key, bool create=false)
template<typename TYPE >
TYPE * option_throw (const t_config_option_key &opt_key, bool create=false)
const ConfigOption * option_throw (const t_config_option_key &opt_key) const
template<typename TYPE >
const TYPE * option_throw (const t_config_option_key &opt_key) const
void apply (const ConfigBase &other, bool ignore_nonexistent=false)
void apply_only (const ConfigBase &other, const t_config_option_keys &keys, bool ignore_nonexistent=false)
std::string opt_serialize (const t_config_option_key &opt_key) const
void set (const std::string &opt_key, bool value, bool create=false)
void set (const std::string &opt_key, int value, bool create=false)
void set (const std::string &opt_key, double value, bool create=false)
void set (const std::string &opt_key, const char *value, bool create=false)
void set (const std::string &opt_key, const std::string &value, bool create=false)
bool set_deserialize_nothrow (const t_config_option_key &opt_key_src, const std::string &value_src, ConfigSubstitutionContext &substitutions, bool append=false)
void set_deserialize (const t_config_option_key &opt_key, const std::string &str, ConfigSubstitutionContext &config_substitutions, bool append=false)
void set_deserialize (std::initializer_list< SetDeserializeItem > items, ConfigSubstitutionContext &substitutions)
void set_deserialize_strict (const t_config_option_key &opt_key, const std::string &str, bool append=false)
void set_deserialize_strict (std::initializer_list< SetDeserializeItem > items)
double get_abs_value (const t_config_option_key &opt_key) const
double get_abs_value (const t_config_option_key &opt_key, double ratio_over) const
void setenv_ () const
ConfigSubstitutions load (const std::string &file, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load (const boost::property_tree::ptree &tree, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load_string_map (std::map< std::string, std::string > &key_values, ForwardCompatibilitySubstitutionRule compatibility_rule)
int load_from_json (const std::string &file, ConfigSubstitutionContext &substitutions, bool load_inherits_in_config, std::map< std::string, std::string > &key_values, std::string &reason)
ConfigSubstitutions load_from_json (const std::string &file, ForwardCompatibilitySubstitutionRule compatibility_rule, std::map< std::string, std::string > &key_values, std::string &reason)
ConfigSubstitutions load_from_ini (const std::string &file, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load_from_ini_string (const std::string &data, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load_from_ini_string_commented (std::string &&data, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load_from_gcode_file (const std::string &file, ForwardCompatibilitySubstitutionRule compatibility_rule)
void save (const std::string &file) const
void save_to_json (const std::string &file, const std::string &name, const std::string &from, const std::string &version, const std::string is_custom="") const
void null_nullables ()
bool has (const t_config_option_key &opt_key) const
Static Public Member Functions
static DynamicPrintConfig full_print_config ()
static DynamicPrintConfig * new_from_defaults_keys (const std::vector< std::string > &keys)
static size_t load_from_gcode_string_legacy (ConfigBase &config, const char *str, ConfigSubstitutionContext &substitutions)
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
bool set_deserialize_raw (const t_config_option_key &opt_key_src, const std::string &value, ConfigSubstitutionContext &substitutions, bool append)
Private Attributes
std::map< t_config_option_key, std::unique_ptr< ConfigOption > > options
Static Private Attributes
static PrintAndCLIConfigDef s_def
Detailed Description
Constructor & Destructor Documentation
DynamicPrintAndCLIConfig() [1/2]
Slic3r::DynamicPrintAndCLIConfig::DynamicPrintAndCLIConfig () inline
{}
DynamicPrintAndCLIConfig() [2/2]
Slic3r::DynamicPrintAndCLIConfig::DynamicPrintAndCLIConfig (const DynamicPrintAndCLIConfig & other) inline
: DynamicPrintConfig(other) {}
Member Function Documentation
apply()
void Slic3r::ConfigBase::apply (const ConfigBase & other, bool ignore_nonexistent = false) inline inherited
{ this->apply_only(other, other.keys(), ignore_nonexistent); }
References Slic3r::ConfigBase::apply_only(), and Slic3r::ConfigBase::keys().
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::PresetCollection::PresetCollection(), Slic3r::BackgroundSlicingProcess::apply(), Slic3r::GCodeProcessor::apply_config_superslicer(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetBundle::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::PartPlate::load_gcode_from_file(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::GCodeProcessor::process_file(), Slic3r::CalibPressureAdvancePattern::refresh_setup(), Slic3r::GUI::ObjectTableSettings::resetAllValues(), Slic3r::CLI::run(), Slic3r::GUI::TabPrintModel::set_model_config(), Slic3r::GUI::PartPlateList::store_to_3mf_structure(), Slic3r::GUI::PresetComboBox::update_ams_color(), Slic3r::GUI::ObjectSettings::update_config_values(), Slic3r::GUI::TabPrintModel::update_model_config(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
apply_only()
void Slic3r::ConfigBase::apply_only (const ConfigBase & other, const t_config_option_keys & keys, bool ignore_nonexistent = false) inherited
{
    // loop through options and apply them
    for (const t_config_option_key &opt_key : keys) {
        // Create a new option with default value for the key.
        // If the key is not in the parameter definition, or this ConfigBase is a static type and it does not support the parameter,
        // an exception is thrown if not ignore_nonexistent.
        ConfigOption *my_opt = this->option(opt_key, true);
        if (my_opt == nullptr) {
            // opt_key does not exist in this ConfigBase and it cannot be created, because it is not defined by this->def().
            // This is only possible if other is of DynamicConfig type.
            if (ignore_nonexistent)
                continue;
            throw UnknownOptionException(opt_key);
        }
    const ConfigOption *other_opt = other.option(opt_key);
    if (other_opt == nullptr) {
            // The key was not found in the source config, therefore it will not be initialized!
//      printf("Not found, therefore not initialized: %s\n", opt_key.c_str());
    } else
            my_opt->set(other_opt);
    }
}
References Slic3r::ConfigBase::keys(), Slic3r::ConfigBase::option(), and Slic3r::ConfigOption::set().
Referenced by Slic3r::PresetBundle::PresetBundle(), Slic3r::ConfigBase::apply(), Slic3r::ModelConfig::apply(), Slic3r::ModelConfig::apply_only(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_user_preset(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::CLI::run(), Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::PhysicalPrinter::update_from_config(), Slic3r::PhysicalPrinter::update_from_preset(), and Slic3r::GUI::TabPrintModel::update_model_config().
cbegin()
std::map< t_config_option_key, std::unique_ptr< ConfigOption > >::const_iterator Slic3r::DynamicConfig::cbegin () const inline inherited
{ return options.cbegin(); }
References Slic3r::DynamicConfig::options.
Referenced by Slic3r::ModelConfig::cbegin(), Slic3r::dynamic_config_iterate(), and cereal::save().
cend()
std::map< t_config_option_key, std::unique_ptr< ConfigOption > >::const_iterator Slic3r::DynamicConfig::cend () const inline inherited
{ return options.cend(); }
References Slic3r::DynamicConfig::options.
Referenced by Slic3r::ModelConfig::cend(), Slic3r::dynamic_config_iterate(), and cereal::save().
clear()
void Slic3r::DynamicConfig::clear () inline inherited
    {
        this->options.clear();
    }
Referenced by Slic3r::GCode::_do_export(), Slic3r::PlaceholderParser::clear_config(), cereal::load(), Slic3r::DynamicConfig::operator=(), Slic3r::DynamicConfig::operator=(), Slic3r::ModelConfig::reset(), Slic3r::GUI::ObjectList::Clipboard::reset(), and Slic3r::GUI::GLCanvas3D::LayersEditing::set_config().
def()
const ConfigDef * Slic3r::DynamicPrintAndCLIConfig::def () const inline override virtual
Reimplemented from Slic3r::DynamicConfig.
{ return &s_def; }
References s_def.
diff() [1/2]
t_config_option_keys Slic3r::ConfigBase::diff (const ConfigBase & other) const inherited
{
    t_config_option_keys diff;
    for (const t_config_option_key &opt_key : this->keys()) {
        const ConfigOption *this_opt  = this->option(opt_key);
        const ConfigOption *other_opt = other.option(opt_key);
        if (this_opt != nullptr && other_opt != nullptr && *this_opt != *other_opt)
            diff.emplace_back(opt_key);
    }
    return diff;
}
References Slic3r::ConfigBase::diff(), Slic3r::ConfigBase::keys(), and Slic3r::ConfigBase::option().
Referenced by Slic3r::ConfigBase::diff().
diff() [2/2]
t_config_option_keys Slic3r::DynamicConfig::diff (const DynamicConfig & other) const inherited
{
    t_config_option_keys diff;
    dynamic_config_iterate(*this, other,
        [&diff](const t_config_option_key &key, const ConfigOption *l, const ConfigOption *r) {
            if (*l != *r)
                diff.emplace_back(key);
            // Continue iterating.
            return false;
        });
    return diff;
}
References Slic3r::DynamicConfig::diff(), and Slic3r::dynamic_config_iterate().
Referenced by Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::GUI::ConfigManipulation::apply(), Slic3r::DynamicConfig::diff(), Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::dirty_options_without_option_list(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::PresetCollection::load_user_preset(), Slic3r::profile_print_params_same(), Slic3r::Preset::save(), and Slic3r::Preset::set_dirty().
empty()
bool Slic3r::DynamicConfig::empty () const inline inherited
{ return options.empty(); }
References Slic3r::DynamicConfig::options.
Referenced by Slic3r::ModelConfig::empty(), Slic3r::import_sla_archive(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::ObjectList::paste_settings_into_list(), and Slic3r::CLI::run().
equal() [1/2]
t_config_option_keys Slic3r::ConfigBase::equal (const ConfigBase & other) const inherited
{
    t_config_option_keys equal;
    for (const t_config_option_key &opt_key : this->keys()) {
        const ConfigOption *this_opt  = this->option(opt_key);
        const ConfigOption *other_opt = other.option(opt_key);
        if (this_opt != nullptr && other_opt != nullptr && *this_opt == *other_opt)
            equal.emplace_back(opt_key);
    }
    return equal;
}
References Slic3r::ConfigBase::equal(), Slic3r::ConfigBase::keys(), and Slic3r::ConfigBase::option().
Referenced by Slic3r::ConfigBase::equal().
equal() [2/2]
t_config_option_keys Slic3r::DynamicConfig::equal (const DynamicConfig & other) const inherited
{
    t_config_option_keys equal;
    dynamic_config_iterate(*this, other,
        [&equal](const t_config_option_key &key, const ConfigOption *l, const ConfigOption *r) {
            if (*l == *r)
                equal.emplace_back(key);
            // Continue iterating.
            return false;
        });
    return equal;
}
References Slic3r::dynamic_config_iterate(), and Slic3r::DynamicConfig::equal().
Referenced by Slic3r::DynamicConfig::equal(), and Slic3r::GUI::TabPrintModel::update_model_config().
equals() [1/2]
bool Slic3r::ConfigBase::equals (const ConfigBase & other, const std::set< std::string > * skipped_keys = nullptr) const inherited
{
    for (const t_config_option_key &opt_key : this->keys()) {
        if (skipped_keys && (skipped_keys->count(opt_key) != 0))
            continue;
        const ConfigOption *this_opt  = this->option(opt_key);
        const ConfigOption *other_opt = other.option(opt_key);
        if (this_opt != nullptr && other_opt != nullptr && *this_opt != *other_opt)
            return false;
    }
    return true;
}
References Slic3r::ConfigBase::keys(), and Slic3r::ConfigBase::option().
equals() [2/2]
bool Slic3r::DynamicConfig::equals (const DynamicConfig & other, const std::set< std::string > * skipped_keys = nullptr) const inherited
{
    return ! dynamic_config_iterate(*this, other,
        [](const t_config_option_key & /* key */, const ConfigOption *l, const ConfigOption *r) { return *l != *r; },
        skipped_keys);
}
References Slic3r::dynamic_config_iterate().
Referenced by Slic3r::PresetCollection::is_dirty().
erase()
bool Slic3r::DynamicConfig::erase (const t_config_option_key & opt_key) inline inherited
    {
        auto it = this->options.find(opt_key);
        if (it == this->options.end())
            return false;
        this->options.erase(it);
        return true;
    }
Referenced by Slic3r::ModelConfig::erase(), Slic3r::PresetBundle::full_config_secure(), Slic3r::PresetBundle::full_sla_config(), Slic3r::DynamicPrintConfig::normalize_fdm(), Slic3r::DynamicPrintConfig::normalize_fdm_1(), Slic3r::Preset::remove_invalid_keys(), Slic3r::GUI::PartPlate::reset_bed_type(), Slic3r::CLI::run(), Slic3r::GUI::PartPlate::set_bed_type(), Slic3r::GUI::PartPlate::set_print_seq(), and Slic3r::GUI::ObjectTableSettings::ValueChanged().
full_print_config()
DynamicPrintConfig Slic3r::DynamicPrintConfig::full_print_config () static inherited
{
  return DynamicPrintConfig((const PrintRegionConfig&)FullPrintConfig::defaults());
}
References Slic3r::DynamicPrintConfig::DynamicPrintConfig(), and Slic3r::PrintRegionConfig.
get_abs_value() [1/2]
double Slic3r::ConfigBase::get_abs_value (const t_config_option_key & opt_key) const inherited
{
    // Get stored option value.
    const ConfigOption *raw_opt = this->option(opt_key);
    if (raw_opt == nullptr) {
      std::stringstream ss;
      ss << "You can't define an option that need " << opt_key << " without defining it!";
      throw std::runtime_error(ss.str());
    }
    assert(raw_opt != nullptr);
    if (raw_opt->type() == coFloat)
        return static_cast<const ConfigOptionFloat*>(raw_opt)->value;
    if (raw_opt->type() == coInt)
      return static_cast<const ConfigOptionInt *>(raw_opt)->value;
    if (raw_opt->type() == coBool)
      return static_cast<const ConfigOptionBool *>(raw_opt)->value ? 1 : 0;
    const ConfigOptionPercent *cast_opt = nullptr;
    if (raw_opt->type() == coFloatOrPercent) {
        auto cofop = static_cast<const ConfigOptionFloatOrPercent*>(raw_opt);
            if (cofop->value == 0 && boost::ends_with(opt_key, "_line_width")) {
                return this->get_abs_value("line_width");
            }
            if (!cofop->percent)
                return cofop->value;
            cast_opt = cofop;
    }
    if (raw_opt->type() == coPercent) {
      cast_opt = static_cast<const ConfigOptionPercent *>(raw_opt);
    }
    // Get option definition.
    const ConfigDef *def = this->def();
    if (def == nullptr)
        throw NoDefinitionException(opt_key);
    const ConfigOptionDef *opt_def = def->get(opt_key);
    assert(opt_def != nullptr);
    if (opt_def->ratio_over == "")
        return cast_opt->get_abs_value(1);
    // Compute absolute value over the absolute value of the base option.
    //FIXME there are some ratio_over chains, which end with empty ratio_with.
    // For example, XXX_extrusion_width parameters are not handled by get_abs_value correctly.
    return opt_def->ratio_over.empty() ? 0. :
        static_cast<const ConfigOptionFloatOrPercent*>(raw_opt)->get_abs_value(this->get_abs_value(opt_def->ratio_over));
    throw ConfigurationError("ConfigBase::get_abs_value(): Not a valid option type for get_abs_value()");
}
References Slic3r::coBool, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coInt, Slic3r::coPercent, Slic3r::ConfigBase::def(), Slic3r::ConfigDef::get(), Slic3r::ConfigBase::get_abs_value(), Slic3r::ConfigOptionPercent::get_abs_value(), Slic3r::ConfigBase::option(), Slic3r::ConfigOptionDef::ratio_over, Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::ConfigBase::get_abs_value(), Slic3r::ModelConfig::get_abs_value(), Slic3r::ConfigBase::get_abs_value(), Slic3r::CalibPressureAdvancePattern::line_width(), Slic3r::CalibPressureAdvancePattern::line_width_first_layer(), Slic3r::CLI::run(), and Slic3r::GUI::Plater::setPrintSpeedTable().
get_abs_value() [2/2]
double Slic3r::ConfigBase::get_abs_value (const t_config_option_key & opt_key, double ratio_over) const inherited
{
    // Get stored option value.
    const ConfigOption *raw_opt = this->option(opt_key);
    assert(raw_opt != nullptr);
    if (raw_opt->type() != coFloatOrPercent)
        throw ConfigurationError("ConfigBase::get_abs_value(): opt_key is not of coFloatOrPercent");
    // Compute absolute value.
    return static_cast<const ConfigOptionFloatOrPercent*>(raw_opt)->get_abs_value(ratio_over);
}
References Slic3r::coFloatOrPercent, Slic3r::ConfigBase::get_abs_value(), Slic3r::ConfigBase::option(), and Slic3r::ConfigOption::type().
get_filament_type()
std::string Slic3r::DynamicPrintConfig::get_filament_type (std::string & displayed_filament_type, int id = 0) inherited
{
    auto* filament_id = dynamic_cast<const ConfigOptionStrings*>(this->option("filament_id"));
    auto* filament_type = dynamic_cast<const ConfigOptionStrings*>(this->option("filament_type"));
    auto* filament_is_support = dynamic_cast<const ConfigOptionBools*>(this->option("filament_is_support"));
    if (!filament_type)
        return "";
    if (!filament_is_support) {
        if (filament_type) {
            displayed_filament_type = filament_type->get_at(id);
            return filament_type->get_at(id);
        }
        else {
            displayed_filament_type = "";
            return "";
        }
    }
    else {
        bool is_support = filament_is_support ? filament_is_support->get_at(id) : false;
        if (is_support) {
            if (filament_id) {
                if (filament_id->get_at(id) == "GFS00") {
                    displayed_filament_type = "Sup.PLA";
                    return "PLA-S";
                }
                else if (filament_id->get_at(id) == "GFS01") {
                    displayed_filament_type = "Sup.PA";
                    return "PA-S";
                }
                else {
                    if (filament_type->get_at(id) == "PLA") {
                        displayed_filament_type = "Sup.PLA";
                        return "PLA-S";
                    }
                    else if (filament_type->get_at(id) == "PA") {
                        displayed_filament_type = "Sup.PA";
                        return "PA-S";
                    }
                    else {
                        displayed_filament_type = filament_type->get_at(id);
                        return filament_type->get_at(id);
                    }
                }
            }
            else {
                if (filament_type->get_at(id) == "PLA") {
                    displayed_filament_type = "Sup.PLA";
                    return "PLA-S";
                } else if (filament_type->get_at(id) == "PA") {
                    displayed_filament_type = "Sup.PA";
                    return "PA-S";
                } else {
                    displayed_filament_type = filament_type->get_at(id);
                    return filament_type->get_at(id);
                }
            }
        }
        else {
            displayed_filament_type = filament_type->get_at(id);
            return filament_type->get_at(id);
        }
    }
    return "PLA";
}
References Slic3r::ConfigOptionBoolsTempl< NULLABLE >::get_at(), and Slic3r::ConfigBase::option().
Referenced by Slic3r::GUI::Plater::export_3mf(), Slic3r::Preset::get_filament_type(), and Slic3r::CLI::run().
handle_legacy()
void Slic3r::DynamicPrintAndCLIConfig::handle_legacy (t_config_option_key & opt_key, std::string & value) const override virtual
Reimplemented from Slic3r::ConfigBase.
{
    if (cli_actions_config_def  .options.find(opt_key) == cli_actions_config_def  .options.end() &&
        cli_transform_config_def.options.find(opt_key) == cli_transform_config_def.options.end() &&
        cli_misc_config_def     .options.find(opt_key) == cli_misc_config_def     .options.end()) {
        PrintConfigDef::handle_legacy(opt_key, value);
    }
}
References Slic3r::cli_actions_config_def, Slic3r::cli_misc_config_def, Slic3r::cli_transform_config_def, Slic3r::PrintConfigDef::handle_legacy(), Slic3r::ConfigDef::options, and Slic3r::DynamicConfig::options.
has()
bool Slic3r::ConfigOptionResolver::has (const t_config_option_key & opt_key) const inline inherited
{ return this->optptr(opt_key) != nullptr; }
References Slic3r::ConfigOptionResolver::optptr().
Referenced by Slic3r::GUI::change_opt_value(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::Bed3D::detect_type(), Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::dirty_options_without_option_list(), Slic3r::GUI::PartPlate::get_bed_type(), Slic3r::anonymous_namespace{SL1.cpp}::get_cfg_value(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::Preset::get_default_bed_type(), Slic3r::GUI::Plater::get_extruder_colors_from_plater_config(), Slic3r::get_instance_arrange_poly(), Slic3r::GUI::ConfigOptionsGroup::get_option(), Slic3r::GUI::PartPlate::get_print_seq(), Slic3r::GUI::PresetComboBox::get_tooltip(), Slic3r::handle_legacy_project_loaded(), Slic3r::handle_legacy_sla(), Slic3r::ModelConfig::has(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetCollection::is_dirty(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::DynamicPrintConfig::normalize_fdm(), Slic3r::DynamicPrintConfig::normalize_fdm_1(), Slic3r::DynamicConfig::read_cli(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::Preset::remove_invalid_keys(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::GUI::PartPlate::render_logo(), Slic3r::GUI::PartPlate::set_bed_type(), Slic3r::GUI::Plater::setExtruderParams(), Slic3r::GUI::Plater::setPrintSpeedTable(), and Slic3r::PresetBundle::update_compatible().
is_custom_defined()
bool Slic3r::DynamicPrintConfig::is_custom_defined () inherited
{
    auto* is_custom_defined = dynamic_cast<const ConfigOptionStrings*>(this->option("is_custom_defined"));
    if (!is_custom_defined || is_custom_defined->empty())
        return false;
    if (is_custom_defined->get_at(0) == "1")
        return true;
    return false;
}
References Slic3r::DynamicPrintConfig::is_custom_defined(), and Slic3r::ConfigBase::option().
Referenced by Slic3r::DynamicPrintConfig::is_custom_defined().
keys()
t_config_option_keys Slic3r::DynamicConfig::keys () const override virtual inherited
Implements Slic3r::ConfigBase.
{
    t_config_option_keys keys;
    keys.reserve(this->options.size());
    for (const auto &opt : this->options)
        keys.emplace_back(opt.first);
    return keys;
}
References Slic3r::DynamicConfig::keys(), Slic3r::DynamicConfig::opt(), and Slic3r::DynamicConfig::options.
Referenced by Slic3r::DynamicConfig::DynamicConfig(), Slic3r::_3MF_Exporter::_add_print_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_print_config_file_to_archive(), Slic3r::GCode::append_full_config(), Slic3r::Search::OptionsSearcher::append_options(), Slic3r::PlaceholderParser::apply_config(), Slic3r::PlaceholderParser::config_diff(), Slic3r::PresetBundle::full_fff_config(), Slic3r::full_print_config_diffs(), Slic3r::GUI::SettingsFactory::get_bundle(), Slic3r::ModelConfig::keys(), Slic3r::DynamicConfig::keys(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::DynamicPrintConfig::new_from_defaults_keys(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::DynamicConfig::read_cli(), Slic3r::Preset::remove_invalid_keys(), Slic3r::CLI::run(), Slic3r::GUI::ObjectTableSettings::update_config_values(), and Slic3r::GUI::TabPrintModel::update_model_config().
load() [1/2]
ConfigSubstitutions Slic3r::ConfigBase::load (const boost::property_tree::ptree & tree, ForwardCompatibilitySubstitutionRule compatibility_rule) inherited
{
    ConfigSubstitutionContext substitutions_ctxt(compatibility_rule);
    for (const boost::property_tree::ptree::value_type &v : tree) {
        try {
            t_config_option_key opt_key = v.first;
            this->set_deserialize(opt_key, v.second.get_value<std::string>(), substitutions_ctxt);
        } catch (UnknownOptionException & /* e */) {
            // ignore
        }
    }
    return std::move(substitutions_ctxt.substitutions);
}
References Slic3r::ConfigBase::set_deserialize(), and Slic3r::ConfigSubstitutionContext::substitutions.
load() [2/2]
ConfigSubstitutions Slic3r::ConfigBase::load (const std::string & file, ForwardCompatibilitySubstitutionRule compatibility_rule) inherited
{
    std::map<std::string, std::string> key_values;
    if (is_gcode_file(file))
        return this->load_from_gcode_file(file, compatibility_rule);
    else if (is_json_file(file)) {
        std::string reason;
        return this->load_from_json(file, compatibility_rule, key_values, reason);
    }
    else {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "unsupported format for config file" << file;
        return ConfigSubstitutions();
        //return this->load_from_ini(file, compatibility_rule);
    }
}
References error, Slic3r::is_gcode_file(), Slic3r::is_json_file(), Slic3r::ConfigBase::load_from_gcode_file(), and Slic3r::ConfigBase::load_from_json().
Referenced by Slic3r::import_sla_archive(), Slic3r::ConfigBase::load_from_ini(), and Slic3r::ConfigBase::load_from_ini_string().
load_from_gcode_file()
ConfigSubstitutions Slic3r::ConfigBase::load_from_gcode_file (const std::string & file, ForwardCompatibilitySubstitutionRule compatibility_rule) inherited
{
    // Read a 64k block from the end of the G-code.
  boost::nowide::ifstream ifs(file);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":  before parse_file %1%") % file.c_str();
    // Look for Slic3r or OrcaSlicer header.
    // Look for the header across the whole file as the G-code may have been extended at the start by a post-processing script or the user.
    //BBS
    bool has_delimiters = true;
    {
        //BBS
        std::string bambuslicer_gcode_header = "; OrcaSlicer";
        std::string orcaslicer_gcode_header = std::string("; generated by ");
        orcaslicer_gcode_header += SLIC3R_APP_NAME;
        std::string header;
        bool        header_found = false;
        while (std::getline(ifs, header)) {
            // BBS
            const char* line_c = skip_whitespaces(header.c_str());
            if (std::toupper(*line_c) == 'N')
                line_c = skip_word(line_c);
            line_c = skip_whitespaces(line_c);
            // BBS
            if (strncmp(bambuslicer_gcode_header.c_str(), line_c, strlen(bambuslicer_gcode_header.c_str())) == 0 ||
                strncmp(orcaslicer_gcode_header.c_str(), line_c, strlen(orcaslicer_gcode_header.c_str())) == 0) {
                header_found = true;
                break;
            }
        }
        if (!header_found) {
            std::string error_message = "Not a gcode file generated by ";
            error_message += SLIC3R_APP_FULL_NAME;
            error_message += ".";
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << error_message;
            throw Slic3r::RuntimeError(error_message.c_str());
        }
    }
    ConfigSubstitutionContext substitutions_ctxt(compatibility_rule);
    size_t                    key_value_pairs = 0;
    if (has_delimiters)
    {
        //BBS
        // PrusaSlicer starting with 2.4.0-alpha0 delimits the config section stored into G-code with
        // ; CONFIG_BLOCK_START
        // ...
        // ; CONFIG_BLOCK_END
        bool begin_found = false;
        bool end_found   = false;
        std::string line;
        while (std::getline(ifs, line))
            if (line.rfind("; CONFIG_BLOCK_START",0)==0) {
                begin_found = true;
                break;
            }
        if (!begin_found) {
            //BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << format("Configuration block closing tag \"; CONFIG_BLOCK_START\" not found when reading %1%", file);
            throw Slic3r::RuntimeError(format("Config tag \"; CONFIG_BLOCK_START\" not found"));
        }
        std::string key, value;
        while (std::getline(ifs, line)) {
            if (line.rfind("; CONFIG_BLOCK_END",0)==0) {
                end_found = true;
                break;
            }
            // line should be a valid key = value pair.
            auto pos = line.find('=');
            if (pos != std::string::npos && pos > 1 && line.front() == ';') {
                key   = line.substr(1, pos - 1);
                value = line.substr(pos + 1);
                boost::trim(key);
                boost::trim(value);
                try {
                    this->set_deserialize(key, value, substitutions_ctxt);
                    ++ key_value_pairs;
                } catch (UnknownOptionException & /* e */) {
                    // ignore
                }
            }
        }
        if (!end_found) {
            //BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << format("Configuration block opening tag \"; CONFIG_BLOCK_END\" not found when reading %1%", file);
            throw Slic3r::RuntimeError(format("Config tag \"; CONFIG_BLOCK_END\" not found"));
        }
    }
    else
    {
        auto                      header_end_pos = ifs.tellg();
        // Slicer older than 2.4.0-alpha0 do not emit any delimiter.
        // Try a heuristics reading the G-code from back.
        ifs.seekg(0, ifs.end);
        auto file_length = ifs.tellg();
      auto data_length = std::min<std::fstream::pos_type>(65535, file_length - header_end_pos);
      ifs.seekg(file_length - data_length, ifs.beg);
        std::vector<char> data(size_t(data_length) + 1, 0);
        ifs.read(data.data(), data_length);
        ifs.close();
        key_value_pairs = load_from_gcode_string_legacy(*this, data.data(), substitutions_ctxt);
    }
    if (key_value_pairs < 80) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << format("Suspiciously low number of configuration values extracted from %1%: %2%", file, key_value_pairs);
        throw Slic3r::RuntimeError(format("Suspiciously low number of configuration values extracted from %1%: %2%", file, key_value_pairs));
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":  finished to parse_file %1%") % file.c_str();
    return std::move(substitutions_ctxt.substitutions);
}
References error, Slic3r::format(), Slic3r::ConfigBase::load_from_gcode_string_legacy(), Slic3r::ConfigBase::set_deserialize(), Slic3r::skip_whitespaces(), Slic3r::skip_word(), SLIC3R_APP_FULL_NAME, and Slic3r::ConfigSubstitutionContext::substitutions.
Referenced by Slic3r::ConfigBase::load(), Slic3r::PresetBundle::load_config_file(), and Slic3r::GCodeProcessor::process_file().
load_from_gcode_string_legacy()
size_t Slic3r::ConfigBase::load_from_gcode_string_legacy (ConfigBase & config, const char * str, ConfigSubstitutionContext & substitutions) static inherited
{
    if (str == nullptr)
        return 0;
    // BBS. Remove line numbers.
    std::regex match_pattern("\nN[0-9]* *");
    std::string replace_pattern = "\n";
    char* result = (char*)calloc(strlen(str) + 1, 1);
    std::regex_replace(result, str, str + strlen(str), match_pattern, replace_pattern);
    // Walk line by line in reverse until a non-configuration key appears.
    const char *data_start = result;
    data_start = skip_whitespaces(data_start);
    if (std::toupper(*data_start) == 'N')
        data_start = skip_word(data_start);
    // boost::nowide::ifstream seems to cook the text data somehow, so less then the 64k of characters may be retrieved.
    const char *end = data_start + strlen(data_start);
    size_t num_key_value_pairs = 0;
    for (;;) {
        // Extract next line.
        for (--end; end > data_start && (*end == '\r' || *end == '\n'); --end);
        if (end == data_start)
            break;
        const char *start = end ++;
        for (; start > data_start && *start != '\r' && *start != '\n'; --start);
        if (start == data_start)
            break;
        // Extracted a line from start to end. Extract the key = value pair.
        if (end - (++ start) < 10 || start[0] != ';' || start[1] != ' ')
            break;
        const char *key = start + 2;
        if (!((*key >= 'a' && *key <= 'z') || (*key >= 'A' && *key <= 'Z')))
            // A key must start with a letter.
            break;
        const char *sep = key;
        for (; sep != end && *sep != '='; ++ sep) ;
        if (sep == end || sep[-1] != ' ' || sep[1] != ' ')
            break;
        const char *value = sep + 2;
        if (value > end)
            break;
        const char *key_end = sep - 1;
        if (key_end - key < 3)
            break;
        // The key may contain letters, digits and underscores.
        for (const char *c = key; c != key_end; ++ c)
            if (!((*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') || (*c >= '0' && *c <= '9') || *c == '_')) {
                key = nullptr;
                break;
            }
        if (key == nullptr)
            break;
        try {
            config.set_deserialize(std::string(key, key_end), std::string(value, end), substitutions);
            ++num_key_value_pairs;
        }
        catch (UnknownOptionException & /* e */) {
            // ignore
        }
        end = start;
    }
    // BBS
    free(result);
    return num_key_value_pairs;
}
References end, Slic3r::ConfigBase::set_deserialize(), Slic3r::skip_whitespaces(), Slic3r::skip_word(), and start.
Referenced by Slic3r::ConfigBase::load_from_gcode_file(), and Slic3r::load_from_superslicer_gcode_file().
load_from_ini()
ConfigSubstitutions Slic3r::ConfigBase::load_from_ini (const std::string & file, ForwardCompatibilitySubstitutionRule compatibility_rule) inherited
{
    try {
        boost::property_tree::ptree tree;
        boost::nowide::ifstream ifs(file);
        boost::property_tree::read_ini(ifs, tree);
        return this->load(tree, compatibility_rule);
    } catch (const ConfigurationError &e) {
        throw ConfigurationError(format("Failed loading configuration file \"%1%\": %2%", file, e.what()));
    }
}
References Slic3r::format(), and Slic3r::ConfigBase::load().
Referenced by Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive().
load_from_ini_string()
ConfigSubstitutions Slic3r::ConfigBase::load_from_ini_string (const std::string & data, ForwardCompatibilitySubstitutionRule compatibility_rule) inherited
{
    boost::property_tree::ptree tree;
    std::istringstream iss(data);
    boost::property_tree::read_ini(iss, tree);
    return this->load(tree, compatibility_rule);
}
References Slic3r::ConfigBase::load().
Referenced by Slic3r::ConfigBase::load_from_ini_string_commented().
load_from_ini_string_commented()
ConfigSubstitutions Slic3r::ConfigBase::load_from_ini_string_commented (std::string && data, ForwardCompatibilitySubstitutionRule compatibility_rule) inherited
{
    // Convert the "data" string into INI format by removing the semi-colons at the start of a line.
    // Also the "; generated by PrusaSlicer ..." comment line will be removed.
    size_t j = 0;
    for (size_t i = 0; i < data.size();)
        if (i == 0 || data[i] == '\n') {
            // Start of a line.
            if (data[i] == '\n') {
                // Consume LF, don't keep empty lines.
                if (j > 0 && data[j - 1] != '\n')
                    data[j ++] = data[i];
                ++ i;
            }
            // Skip all leading spaces;
            for (; i < data.size() && (data[i] == ' ' || data[i] == '\t'); ++ i) ;
            // Skip the semicolon (comment indicator).
            if (i < data.size() && data[i] == ';')
                ++ i;
            // Skip all leading spaces after semicolon.
            for (; i < data.size() && (data[i] == ' ' || data[i] == '\t'); ++ i) ;
            if (strncmp(data.data() + i, "generated by ", 13) == 0) {
                // Skip the "; generated by ..." line.
                for (; i < data.size() && data[i] != '\n'; ++ i);
            }
        } else if (data[i] == '\r' && i + 1 < data.size() && data[i + 1] == '\n') {
            // Skip CR.
            ++ i;
        } else {
            // Consume the rest of the data.
            data[j ++] = data[i ++];
        }
    data.erase(data.begin() + j, data.end());
    return this->load_from_ini_string(data, compatibility_rule);
}
References Slic3r::ConfigBase::load_from_ini_string().
load_from_json() [1/2]
int Slic3r::ConfigBase::load_from_json (const std::string & file, ConfigSubstitutionContext & substitutions, bool load_inherits_in_config, std::map< std::string, std::string > & key_values, std::string & reason) inherited
{
    json j;
    std::list<std::string> different_settings_append;
    std::string new_support_style;
    bool is_project_settings = false;
    try {
        boost::nowide::ifstream ifs(file);
        ifs >> j;
        const ConfigDef* config_def = this->def();
        if (config_def == nullptr) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ": no config defs!";
            return -1;
        }
        //parse the json elements
        for (auto it = j.begin(); it != j.end(); it++) {
            if (boost::iequals(it.key(),BBL_JSON_KEY_VERSION)) {
                key_values.emplace(BBL_JSON_KEY_VERSION, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_IS_CUSTOM)) {
                key_values.emplace(BBL_JSON_KEY_IS_CUSTOM, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_NAME)) {
                key_values.emplace(BBL_JSON_KEY_NAME, it.value());
                if (it.value() == "project_settings")
                    is_project_settings = true;
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_URL)) {
                key_values.emplace(BBL_JSON_KEY_URL, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_TYPE)) {
                key_values.emplace(BBL_JSON_KEY_TYPE, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_SETTING_ID)) {
                key_values.emplace(BBL_JSON_KEY_SETTING_ID, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_FILAMENT_ID)) {
                key_values.emplace(BBL_JSON_KEY_FILAMENT_ID, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_FROM)) {
                key_values.emplace(BBL_JSON_KEY_FROM, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_INSTANTIATION)) {
                key_values.emplace(BBL_JSON_KEY_INSTANTIATION, it.value());
            }
            else if (!load_inherits_to_config && boost::iequals(it.key(), BBL_JSON_KEY_INHERITS)) {
                key_values.emplace(BBL_JSON_KEY_INHERITS, it.value());
            }
            else {
                t_config_option_key opt_key = it.key();
                std::string value_str;
                if (it.value().is_string()) {
                    //bool test1 = (it.key() == std::string("end_gcode"));
                    this->set_deserialize(opt_key, it.value(), substitution_context);
                    //some logic for special values
                    if (opt_key == "support_type") {
                        //std::string new_value = dynamic_cast<ConfigOptionString*>(this->option(opt_key))->value;
                        if (it.value() == "hybrid(auto)") {
                            different_settings_append.push_back(opt_key);
                            different_settings_append.push_back("support_style");
                            new_support_style = "tree_hybrid";
                        }
                    }
                }
                else if (it.value().is_array()) {
                    t_config_option_key opt_key_src = opt_key;
                    this->handle_legacy(opt_key, value_str);
                    if (opt_key.empty()) {
                        //BBS: record these options
                        substitution_context.unrecogized_keys.push_back(opt_key_src);
                        continue;
                    }
                    bool valid = true, first = true, use_comma = true;
                    //bool test2 = (it.key() == std::string("filament_end_gcode"));
                    const ConfigOptionDef* optdef = config_def->get(opt_key);
                    if (optdef == nullptr) {
                        // If we didn't find an option, look for any other option having this as an alias.
                        for (const auto& opt : config_def->options) {
                            for (const t_config_option_key& opt_key2 : opt.second.aliases) {
                                if (opt_key2 == opt_key) {
                                    opt_key = opt.first;
                                    optdef = &opt.second;
                                    break;
                                }
                            }
                            if (optdef != nullptr)
                                break;
                        }
                    }
                    if (optdef && optdef->type == coStrings) {
                        use_comma = false;
                    }
                    for (auto iter = it.value().begin(); iter != it.value().end(); iter++) {
                        if (iter.value().is_string()) {
                            if (!first) {
                                if (use_comma)
                                    value_str += ",";
                                else
                                    value_str += ";";
                            }
                            else
                                first = false;
                            if (use_comma)
                                value_str += iter.value();
                            else {
                                value_str += "\"";
                                value_str += escape_string_cstyle(iter.value());
                                value_str += "\"";
                            }
                        }
                        else {
                            //should not happen
                            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" error, invalid json array for " << it.key();
                            valid = false;
                            break;
                        }
                    }
                    if (valid)
                        this->set_deserialize(opt_key, value_str, substitution_context);
                }
                else {
                    //should not happen
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" error, invalid json type for " << it.key();
                }
            }
        }
        if (!different_settings_append.empty()) {
            if (!new_support_style.empty()) {
                ConfigOptionEnum<SupportMaterialStyle>* opt = this->option<ConfigOptionEnum<SupportMaterialStyle>>("support_style", true);
                opt->value = smsTreeHybrid;
            }
            if (is_project_settings) {
                std::vector<std::string>& different_settings = this->option<ConfigOptionStrings>("different_settings_to_system", true)->values;
                size_t size = different_settings.size();
                if (size == 0) {
                    size = this->option<ConfigOptionStrings>("filament_settings_id")->values.size() + 2;
                    different_settings.resize(size);
                }
                std::vector<bool> is_first(size, false);
                std::vector<std::vector<std::string>> original_diffs(size);
                for (int index = 0; index < size; index++)
                {
                    if (different_settings[index].empty()) {
                        is_first[index] = true;
                    }
                    else {
                        Slic3r::unescape_strings_cstyle(different_settings[index], original_diffs[index]);
                    }
                }
                for (auto diff_key : different_settings_append)
                {
                    //get the index in the group
                    int index = 0;
                    bool need_insert = true;
                    if (diff_key == "support_type")
                        index = 0;
                    else if (diff_key == "support_style")
                        index = 0;
                    //check whether exist firstly
                    if (!original_diffs[index].empty()) {
                        for (int j = 0; j < original_diffs[index].size(); j++) {
                            if (original_diffs[index][j] == diff_key) {
                                need_insert = false;
                                break;
                            }
                        }
                    }
                    if (!need_insert)
                        continue;
                    //insert this key
                    if (!is_first[index])
                        different_settings[index] += ";";
                    else
                        is_first[index] = false;
                    different_settings[index] += diff_key;
                }
            }
        }
        return 0;
    }
    catch (const std::ifstream::failure &err)  {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" got a ifstream error, reason = " << err.what();
        reason = std::string("ifstreamError: ") + err.what();
        //throw ConfigurationError(format("Failed loading configuration file \"%1%\": %2%", file, e.what()));
    }
    catch(nlohmann::detail::parse_error &err) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" got a nlohmann::detail::parse_error, reason = " << err.what();
        reason = std::string("JsonParseError: ") + err.what();
        //throw ConfigurationError(format("Failed loading configuration file \"%1%\": %2%", file, err.what()));
    }
    catch(std::exception &err) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" got a generic exception, reason = " << err.what();
        reason = std::string("std::exception: ") + err.what();
    }
    return -1;
}
References BBL_JSON_KEY_FILAMENT_ID, BBL_JSON_KEY_FROM, BBL_JSON_KEY_INHERITS, BBL_JSON_KEY_INSTANTIATION, BBL_JSON_KEY_IS_CUSTOM, BBL_JSON_KEY_NAME, BBL_JSON_KEY_SETTING_ID, BBL_JSON_KEY_TYPE, BBL_JSON_KEY_URL, BBL_JSON_KEY_VERSION, Slic3r::coStrings, Slic3r::ConfigBase::def(), Slic3r::empty(), error, Slic3r::escape_string_cstyle(), Slic3r::ConfigDef::get(), Slic3r::ConfigBase::handle_legacy(), Slic3r::ConfigDef::options, Slic3r::ConfigBase::set_deserialize(), size, Slic3r::smsTreeHybrid, Slic3r::ConfigOptionDef::type, Slic3r::unescape_strings_cstyle(), Slic3r::ConfigSubstitutionContext::unrecogized_keys, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::_BBS_3MF_Importer::_extract_project_config_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::PresetBundle::import_presets(), Slic3r::ConfigBase::load(), Slic3r::ConfigBase::load_from_json(), Slic3r::PresetCollection::load_presets(), Slic3r::PhysicalPrinterCollection::load_printers(), and Slic3r::PresetBundle::load_vendor_configs_from_json().
load_from_json() [2/2]
ConfigSubstitutions Slic3r::ConfigBase::load_from_json (const std::string & file, ForwardCompatibilitySubstitutionRule compatibility_rule, std::map< std::string, std::string > & key_values, std::string & reason) inherited
{
    int ret = 0;
    ConfigSubstitutionContext substitutions_ctxt(compatibility_rule);
    ret = load_from_json(file, substitutions_ctxt, true, key_values, reason);
    return std::move(substitutions_ctxt.substitutions);
}
References Slic3r::ConfigBase::load_from_json(), and Slic3r::ConfigSubstitutionContext::substitutions.
load_string_map()
ConfigSubstitutions Slic3r::ConfigBase::load_string_map (std::map< std::string, std::string > & key_values, ForwardCompatibilitySubstitutionRule compatibility_rule) inherited
{
    ConfigSubstitutionContext substitutions_ctxt(compatibility_rule);
    std::map<std::string, std::string>::iterator it;
    for (it = key_values.begin(); it != key_values.end(); it++) {
        try {
            t_config_option_key opt_key = it->first;
            this->set_deserialize(opt_key, it->second, substitutions_ctxt);
        }
        catch (UnknownOptionException& /* e */) {
            // ignore
        }
    }
    return std::move(substitutions_ctxt.substitutions);
}
References Slic3r::ConfigBase::set_deserialize(), and Slic3r::ConfigSubstitutionContext::substitutions.
Referenced by Slic3r::PresetCollection::load_user_preset().
new_from_defaults_keys()
DynamicPrintConfig * Slic3r::DynamicPrintConfig::new_from_defaults_keys (const std::vector< std::string > & keys) static inherited
{
    auto *out = new DynamicPrintConfig();
    out->apply_only(FullPrintConfig::defaults(), keys);
    return out;
}
References Slic3r::DynamicPrintConfig::DynamicPrintConfig(), Slic3r::DynamicConfig::keys(), and out.
Referenced by Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), and Slic3r::GUI::ObjectList::merge().
normalize_fdm()
void Slic3r::DynamicPrintConfig::normalize_fdm (int used_filaments = 0) inherited
{
    if (this->has("extruder")) {
        int extruder = this->option("extruder")->getInt();
        this->erase("extruder");
        if (extruder != 0) {
            if (!this->has("sparse_infill_filament"))
                this->option("sparse_infill_filament", true)->setInt(extruder);
            if (!this->has("wall_filament"))
                this->option("wall_filament", true)->setInt(extruder);
            // Don't propagate the current extruder to support.
            // For non-soluble supports, the default "0" extruder means to use the active extruder,
            // for soluble supports one certainly does not want to set the extruder to non-soluble.
            // if (!this->has("support_filament"))
            //     this->option("support_filament", true)->setInt(extruder);
            // if (!this->has("support_interface_filament"))
            //     this->option("support_interface_filament", true)->setInt(extruder);
        }
    }
    if (!this->has("solid_infill_filament") && this->has("sparse_infill_filament"))
        this->option("solid_infill_filament", true)->setInt(this->option("sparse_infill_filament")->getInt());
    if (this->has("spiral_mode") && this->opt<ConfigOptionBool>("spiral_mode", true)->value) {
        {
            // this should be actually done only on the spiral layers instead of all
            auto* opt = this->opt<ConfigOptionBools>("retract_when_changing_layer", true);
            opt->values.assign(opt->values.size(), false);  // set all values to false
            // Disable retract on layer change also for filament overrides.
            auto* opt_n = this->opt<ConfigOptionBoolsNullable>("filament_retract_when_changing_layer", true);
            opt_n->values.assign(opt_n->values.size(), false);  // Set all values to false.
        }
        {
            this->opt<ConfigOptionInt>("wall_loops", true)->value       = 1;
            this->opt<ConfigOptionInt>("top_shell_layers", true)->value = 0;
            this->opt<ConfigOptionPercent>("sparse_infill_density", true)->value = 0;
        }
    }
    if (auto *opt_gcode_resolution = this->opt<ConfigOptionFloat>("resolution", false); opt_gcode_resolution)
        // Resolution will be above 1um.
        opt_gcode_resolution->value = std::max(opt_gcode_resolution->value, 0.001);
    // BBS
    ConfigOptionBool* ept_opt = this->option<ConfigOptionBool>("enable_prime_tower");
    if (used_filaments > 0 && ept_opt != nullptr) {
        ConfigOptionBool* islh_opt = this->option<ConfigOptionBool>("independent_support_layer_height", true);
        //ConfigOptionBool* alh_opt = this->option<ConfigOptionBool>("adaptive_layer_height");
        ConfigOptionEnum<PrintSequence>* ps_opt = this->option<ConfigOptionEnum<PrintSequence>>("print_sequence");
        ConfigOptionEnum<TimelapseType>* timelapse_opt = this->option<ConfigOptionEnum<TimelapseType>>("timelapse_type");
        bool is_smooth_timelapse = timelapse_opt != nullptr && timelapse_opt->value == TimelapseType::tlSmooth;
        if (!is_smooth_timelapse && (used_filaments == 1 || ps_opt->value == PrintSequence::ByObject)) {
            ept_opt->value = false;
        }
        if (ept_opt->value) {
            if (islh_opt)
                islh_opt->value = false;
            //if (alh_opt)
            //    alh_opt->value = false;
        }
        /* BBS: MusangKing - not sure if this is still valid, just comment it out cause "Independent support layer height" is re-opened.
        else {
            if (islh_opt)
                islh_opt->value = true;
        }
        */
    }
}
References Slic3r::ByObject, Slic3r::DynamicConfig::erase(), Slic3r::ConfigOption::getInt(), Slic3r::ConfigOptionResolver::has(), Slic3r::DynamicConfig::opt(), Slic3r::ConfigBase::option(), Slic3r::ConfigOption::setInt(), Slic3r::tlSmooth, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::CLI::run().
normalize_fdm_1()
void Slic3r::DynamicPrintConfig::normalize_fdm_1 () inherited
{
    if (this->has("extruder")) {
        int extruder = this->option("extruder")->getInt();
        this->erase("extruder");
        if (extruder != 0) {
            if (!this->has("sparse_infill_filament"))
                this->option("sparse_infill_filament", true)->setInt(extruder);
            if (!this->has("wall_filament"))
                this->option("wall_filament", true)->setInt(extruder);
            // Don't propagate the current extruder to support.
            // For non-soluble supports, the default "0" extruder means to use the active extruder,
            // for soluble supports one certainly does not want to set the extruder to non-soluble.
            // if (!this->has("support_filament"))
            //     this->option("support_filament", true)->setInt(extruder);
            // if (!this->has("support_interface_filament"))
            //     this->option("support_interface_filament", true)->setInt(extruder);
        }
    }
    if (!this->has("solid_infill_filament") && this->has("sparse_infill_filament"))
        this->option("solid_infill_filament", true)->setInt(this->option("sparse_infill_filament")->getInt());
    if (this->has("spiral_mode") && this->opt<ConfigOptionBool>("spiral_mode", true)->value) {
        {
            // this should be actually done only on the spiral layers instead of all
            auto* opt = this->opt<ConfigOptionBools>("retract_when_changing_layer", true);
            opt->values.assign(opt->values.size(), false);  // set all values to false
            // Disable retract on layer change also for filament overrides.
            auto* opt_n = this->opt<ConfigOptionBoolsNullable>("filament_retract_when_changing_layer", true);
            opt_n->values.assign(opt_n->values.size(), false);  // Set all values to false.
        }
        {
            this->opt<ConfigOptionInt>("wall_loops", true)->value       = 1;
            this->opt<ConfigOptionInt>("top_shell_layers", true)->value = 0;
            this->opt<ConfigOptionPercent>("sparse_infill_density", true)->value = 0;
        }
    }
    if (auto *opt_gcode_resolution = this->opt<ConfigOptionFloat>("resolution", false); opt_gcode_resolution)
        // Resolution will be above 1um.
        opt_gcode_resolution->value = std::max(opt_gcode_resolution->value, 0.001);
    return;
}
References Slic3r::DynamicConfig::erase(), Slic3r::ConfigOption::getInt(), Slic3r::ConfigOptionResolver::has(), Slic3r::DynamicConfig::opt(), Slic3r::ConfigBase::option(), and Slic3r::ConfigOption::setInt().
Referenced by Slic3r::Print::apply().
normalize_fdm_2()
t_config_option_keys Slic3r::DynamicPrintConfig::normalize_fdm_2 (int num_objects, int used_filaments = 0) inherited
{
    t_config_option_keys changed_keys;
    ConfigOptionBool* ept_opt = this->option<ConfigOptionBool>("enable_prime_tower");
    if (used_filaments > 0 && ept_opt != nullptr) {
        ConfigOptionBool* islh_opt = this->option<ConfigOptionBool>("independent_support_layer_height", true);
        //ConfigOptionBool* alh_opt = this->option<ConfigOptionBool>("adaptive_layer_height");
        ConfigOptionEnum<PrintSequence>* ps_opt = this->option<ConfigOptionEnum<PrintSequence>>("print_sequence");
        ConfigOptionEnum<TimelapseType>* timelapse_opt = this->option<ConfigOptionEnum<TimelapseType>>("timelapse_type");
        bool is_smooth_timelapse = timelapse_opt != nullptr && timelapse_opt->value == TimelapseType::tlSmooth;
        if (!is_smooth_timelapse && (used_filaments == 1 || (ps_opt->value == PrintSequence::ByObject && num_objects > 1))) {
            if (ept_opt->value) {
                ept_opt->value = false;
                changed_keys.push_back("enable_prime_tower");
            }
            //ept_opt->value = false;
        }
        if (ept_opt->value) {
            if (islh_opt) {
                if (islh_opt->value) {
                    islh_opt->value = false;
                    changed_keys.push_back("independent_support_layer_height");
                }
                //islh_opt->value = false;
            }
            //if (alh_opt) {
            //    if (alh_opt->value) {
            //        alh_opt->value = false;
            //        changed_keys.push_back("adaptive_layer_height");
            //    }
            //    //alh_opt->value = false;
            //}
        }
        /* BBSMusangKing - use "global->support->Independent support layer height" widget to replace previous assignment
        else {
            if (islh_opt) {
                if (!islh_opt->value) {
                    islh_opt->value = true;
                    changed_keys.push_back("independent_support_layer_height");
                }
                //islh_opt->value = true;
            }
        }
        */
    }
    return changed_keys;
}
References Slic3r::ByObject, Slic3r::tlSmooth, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::Print::apply().
null_nullables()
void Slic3r::ConfigBase::null_nullables () inherited
{
    for (const std::string &opt_key : this->keys()) {
        ConfigOption *opt = this->optptr(opt_key, false);
        assert(opt != nullptr);
        if (opt->nullable())
          opt->deserialize("nil", ForwardCompatibilitySubstitutionRule::Disable);
    }
}
References Slic3r::ConfigOption::deserialize(), Slic3r::Disable, Slic3r::ConfigBase::keys(), Slic3r::ConfigOption::nullable(), and Slic3r::ConfigBase::optptr().
Referenced by Slic3r::PresetBundle::PresetBundle().
operator!=()
bool Slic3r::DynamicConfig::operator!= (const DynamicConfig & rhs) const inline inherited
{ return ! (*this == rhs); }
operator+=() [1/2]
DynamicConfig & Slic3r::DynamicConfig::operator+= (const DynamicConfig & rhs) inline inherited
    {
        assert(this->def() == nullptr || this->def() == rhs.def());
        for (const auto &kvp : rhs.options) {
            auto it = this->options.find(kvp.first);
            if (it == this->options.end())
                this->options[kvp.first].reset(kvp.second->clone());
            else {
                assert(it->second->type() == kvp.second->type());
                if (it->second->type() == kvp.second->type())
                    *it->second = *kvp.second;
                else
                    it->second.reset(kvp.second->clone());
            }
        }
        return *this;
    }
References Slic3r::DynamicConfig::def(), and Slic3r::DynamicConfig::options.
operator+=() [2/2]
DynamicConfig & Slic3r::DynamicConfig::operator+= (DynamicConfig && rhs) inline inherited
    {
        assert(this->def() == nullptr || this->def() == rhs.def());
        for (auto &kvp : rhs.options) {
            auto it = this->options.find(kvp.first);
            if (it == this->options.end()) {
                this->options.insert(std::make_pair(kvp.first, std::move(kvp.second)));
            } else {
                assert(it->second->type() == kvp.second->type());
                it->second = std::move(kvp.second);
            }
        }
        rhs.options.clear();
        return *this;
    }
References Slic3r::DynamicConfig::def().
operator==()
bool Slic3r::DynamicConfig::operator== (const DynamicConfig & rhs) const inherited
{
    auto it1     = this->options.begin();
    auto it1_end = this->options.end();
    auto it2     = rhs.options.begin();
    auto it2_end = rhs.options.end();
    for (; it1 != it1_end && it2 != it2_end; ++ it1, ++ it2)
    if (it1->first != it2->first || *it1->second != *it2->second)
      // key or value differ
      return false;
    return it1 == it1_end && it2 == it2_end;
}
References Slic3r::DynamicConfig::options.
opt() [1/2]
template<class T > const T * Slic3r::DynamicConfig::opt (const t_config_option_key & opt_key) const inline inherited
        { return dynamic_cast<const T*>(this->option(opt_key)); }
References Slic3r::ConfigBase::option().
opt() [2/2]
template<class T > T * Slic3r::DynamicConfig::opt (const t_config_option_key & opt_key, bool create = false) inline inherited
        { return dynamic_cast<T*>(this->option(opt_key, create)); }
References Slic3r::ConfigBase::option().
Referenced by Slic3r::GUI::PartPlateList::create_plate(), Slic3r::PrinterPresetCollection::default_preset_for(), Slic3r::GUI::PartPlateList::delete_plate(), Slic3r::GUI::Bed3D::detect_type(), Slic3r::gcode_add_line_number(), Slic3r::get_bed_shape(), Slic3r::GUI::Materials::get_filament_type(), Slic3r::GUI::Materials::get_filament_vendor(), Slic3r::GUI::Materials::get_material_type(), Slic3r::GUI::Materials::get_material_vendor(), Slic3r::GUI::get_string_value(), Slic3r::GUI::GLCanvas3D::get_wipe_tower_info(), Slic3r::handle_legacy_sla(), Slic3r::GUI::GCodeViewer::init(), Slic3r::DynamicConfig::keys(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::DynamicPrintConfig::normalize_fdm(), Slic3r::DynamicPrintConfig::normalize_fdm_1(), Slic3r::DynamicConfig::optptr(), Slic3r::CLI::run(), Slic3r::run_post_process_scripts(), Slic3r::GUI::Plater::priv::scaled_bed_shape_bb(), Slic3r::GUI::Plater::set_bed_shape(), Slic3r::DynamicPrintConfig::set_num_extruders(), Slic3r::DynamicPrintConfig::set_num_filaments(), Slic3r::PresetUtils::system_printer_model(), Slic3r::GUI::anonymous_namespace{HintNotification.cpp}::tag_check_material(), Slic3r::GUI::DiffPresetDialog::update_tree(), Slic3r::GUI::UnsavedChangesDialog::update_tree(), and Slic3r::DynamicPrintConfig::validate().
opt_bool() [1/2]
bool Slic3r::DynamicConfig::opt_bool (const t_config_option_key & opt_key) const inline inherited
{ return this->option<ConfigOptionBool>(opt_key)->value != 0; }
Referenced by Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::ConfigOptionsGroup::get_config_value2(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), Slic3r::GLVolumeCollection::get_selection_support_threshold_angle(), Slic3r::GUI::get_string_value(), Slic3r::CLI::has_print_action(), Slic3r::GUI::pad_combo_value_for_config(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::CLI::run(), Slic3r::GUI::support_combo_value_for_config(), Slic3r::GUI::TabFilament::toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::ConfigManipulation::toggle_print_sla_options(), Slic3r::GUI::Plater::priv::update_background_process(), Slic3r::GUI::TabPrinter::update_fff(), and Slic3r::GUI::ConfigManipulation::update_print_fff_config().
opt_bool() [2/2]
bool Slic3r::DynamicConfig::opt_bool (const t_config_option_key & opt_key, unsigned int idx) const inline inherited
{ return this->option<ConfigOptionBools>(opt_key)->get_at(idx) != 0; }
opt_enum() [1/2]
template<typename ENUM > ENUM Slic3r::DynamicConfig::opt_enum (const t_config_option_key & opt_key) const inline inherited
{ return static_cast<ENUM>(this->option(opt_key)->getInt()); }
References Slic3r::ConfigOption::getInt(), and Slic3r::ConfigBase::option().
Referenced by Slic3r::BackgroundSlicingProcess::apply(), Slic3r::GUI::PartPlate::get_bed_type(), Slic3r::get_instance_arrange_poly(), Slic3r::GUI::PartPlate::get_print_seq(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), Slic3r::GUI::Plater::on_config_change(), Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::GUI::PartPlate::render_logo(), Slic3r::GUI::PartPlate::set_bed_type(), Slic3r::GUI::Plater::setExtruderParams(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), and Slic3r::GUI::ConfigManipulation::update_print_fff_config().
opt_enum() [2/2]
int Slic3r::DynamicConfig::opt_enum (const t_config_option_key & opt_key, unsigned int idx) const inline inherited
{ return dynamic_cast<const ConfigOptionEnumsGeneric*>(this->option(opt_key))->get_at(idx); }
References Slic3r::ConfigBase::option().
opt_float() [1/4]
double & Slic3r::DynamicConfig::opt_float (const t_config_option_key & opt_key) inline inherited
{ return this->option<ConfigOptionFloat>(opt_key)->value; }
Referenced by Slic3r::GUI::GLCanvas3D::_get_current_partplate_print_volume(), Slic3r::GUI::change_opt_value(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::ConfigOptionsGroup::get_config_value2(), Slic3r::GUI::get_max_layer_height(), Slic3r::GUI::get_min_layer_height(), Slic3r::GUI::get_string_value(), Slic3r::Slicing::max_layer_height_from_nozzle(), Slic3r::Slicing::min_layer_height_from_nozzle(), Slic3r::ModelConfig::opt_float(), Slic3r::GUI::GLCanvas3D::plate_scene_bounding_box(), Slic3r::CLI::run(), Slic3r::GUI::Selection::scale_to_fit_print_volume(), Slic3r::GUI::Plater::priv::set_bed_shape(), Slic3r::GUI::Plater::setPrintSpeedTable(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::Plater::priv::undo_redo_to(), Slic3r::PresetBundle::update_compatible(), Slic3r::GUI::TabFilament::update_filament_overrides_page(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), and Slic3r::GUI::ConfigManipulation::update_print_sla_config().
opt_float() [2/4]
const double & Slic3r::DynamicConfig::opt_float (const t_config_option_key & opt_key) const inline inherited
{ return dynamic_cast<const ConfigOptionFloat*>(this->option(opt_key))->value; }
References Slic3r::ConfigBase::option().
opt_float() [3/4]
double & Slic3r::DynamicConfig::opt_float (const t_config_option_key & opt_key, unsigned int idx) inline inherited
{ return this->option<ConfigOptionFloats>(opt_key)->get_at(idx); }
opt_float() [4/4]
const double & Slic3r::DynamicConfig::opt_float (const t_config_option_key & opt_key, unsigned int idx) const inline inherited
{ return dynamic_cast<const ConfigOptionFloats*>(this->option(opt_key))->get_at(idx); }
References Slic3r::ConfigBase::option().
opt_int() [1/4]
int & Slic3r::DynamicConfig::opt_int (const t_config_option_key & opt_key) inline inherited
{ return this->option<ConfigOptionInt>(opt_key)->value; }
Referenced by Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::ConfigOptionsGroup::get_config_value2(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::get_instance_arrange_poly(), Slic3r::GUI::OrientJob::get_orient_mesh(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), Slic3r::GLVolumeCollection::get_selection_support_threshold_angle(), Slic3r::GUI::get_string_value(), Slic3r::GUI::PresetComboBox::get_tooltip(), Slic3r::ModelConfig::opt_int(), Slic3r::CLI::run(), Slic3r::GUI::Plater::setExtruderParams(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GLVolumeCollection::update_colors_by_extruder(), and Slic3r::GUI::ConfigManipulation::update_print_fff_config().
opt_int() [2/4]
int Slic3r::DynamicConfig::opt_int (const t_config_option_key & opt_key) const inline inherited
{ return dynamic_cast<const ConfigOptionInt*>(this->option(opt_key))->value; }
References Slic3r::ConfigBase::option().
opt_int() [3/4]
int & Slic3r::DynamicConfig::opt_int (const t_config_option_key & opt_key, unsigned int idx) inline inherited
{ return this->option<ConfigOptionInts>(opt_key)->get_at(idx); }
opt_int() [4/4]
int Slic3r::DynamicConfig::opt_int (const t_config_option_key & opt_key, unsigned int idx) const inline inherited
{ return dynamic_cast<const ConfigOptionInts*>(this->option(opt_key))->get_at(idx); }
References Slic3r::ConfigBase::option().
opt_serialize()
std::string Slic3r::ConfigBase::opt_serialize (const t_config_option_key & opt_key) const inherited
{
    const ConfigOption* opt = this->option(opt_key);
    assert(opt != nullptr);
    return opt->serialize();
}
References Slic3r::ConfigBase::option(), and Slic3r::ConfigOption::serialize().
Referenced by Slic3r::_3MF_Exporter::_add_print_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_print_config_file_to_archive(), Slic3r::GCode::_do_export(), Slic3r::GCode::append_full_config(), Slic3r::anonymous_namespace{SL1.cpp}::fill_slicerconf(), Slic3r::ModelConfig::opt_serialize(), and Slic3r::ConfigBase::save().
opt_string() [1/4]
const std::string & Slic3r::DynamicConfig::opt_string (const t_config_option_key & opt_key) const inline inherited
{ return const_cast<DynamicConfig*>(this)->opt_string(opt_key); }
References Slic3r::DynamicConfig::opt_string().
Referenced by Slic3r::DynamicConfig::opt_string().
opt_string() [2/4]
std::string & Slic3r::DynamicConfig::opt_string (const t_config_option_key & opt_key, bool create = false) inline inherited
{ return this->option<ConfigOptionString>(opt_key, create)->value; }
Referenced by Slic3r::PresetBundle::PresetBundle(), Slic3r::_BBS_3MF_Exporter::_add_custom_gcode_per_print_z_file_to_archive(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::PrinterPresetCollection::find_system_preset_by_model_and_variant(), Slic3r::GUI::Plater::force_filament_colors_update(), Slic3r::GUI::gcode(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::ConfigOptionsGroup::get_config_value2(), Slic3r::Preset::get_current_printer_type(), Slic3r::Preset::get_default_bed_type(), Slic3r::Preset::get_printer_type(), Slic3r::GUI::get_string_value(), Slic3r::Preset::has_lidar(), Slic3r::GUI::ObjectTablePanel::init_filaments_and_colors(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::GUI::MainFrame::load_printer_url(), Slic3r::PhysicalPrinterCollection::load_printers_from_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::PrintBase::output_filename(), Slic3r::CLI::output_filepath(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::CLI::run(), Slic3r::GUI::Plater::priv::set_bed_shape(), Slic3r::Preset::set_visible_from_appconfig(), Slic3r::GUI::Plater::setExtruderParams(), Slic3r::CLI::setup(), Slic3r::GUI::TabSLAMaterial::toggle_options(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::Sidebar::update_all_preset_comboboxes(), Slic3r::GUI::PresetComboBox::update_ams_color(), Slic3r::GLVolumeCollection::update_colors_by_extruder(), Slic3r::PresetBundle::update_compatible(), Slic3r::GUI::PhysicalPrinterDialog::update_printhost_buttons(), and Slic3r::PresetCollection::validate_printers().
opt_string() [3/4]
std::string & Slic3r::DynamicConfig::opt_string (const t_config_option_key & opt_key, unsigned int idx) inline inherited
{ return this->option<ConfigOptionStrings>(opt_key)->get_at(idx); }
opt_string() [4/4]
const std::string & Slic3r::DynamicConfig::opt_string (const t_config_option_key & opt_key, unsigned int idx) const inline inherited
{ return const_cast<DynamicConfig*>(this)->opt_string(opt_key, idx); }
References Slic3r::DynamicConfig::opt_string().
Referenced by Slic3r::DynamicConfig::opt_string().
option() [1/4]
const ConfigOption * Slic3r::ConfigOptionResolver::option (const t_config_option_key & opt_key) const inline inherited
{ return this->optptr(opt_key); }
option() [2/4]
template<typename TYPE > const TYPE * Slic3r::ConfigOptionResolver::option (const t_config_option_key & opt_key) const inline inherited
    {
        const ConfigOption* opt = this->optptr(opt_key);
        return (opt == nullptr || opt->type() != TYPE::static_type()) ? nullptr : static_cast<const TYPE*>(opt);
    }
option() [3/4]
ConfigOption * Slic3r::ConfigBase::option (const t_config_option_key & opt_key, bool create = false) inline inherited
        { return this->optptr(opt_key, create); }
References Slic3r::ConfigBase::optptr().
Referenced by Slic3r::DynamicConfig::DynamicConfig(), Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::PresetBundle::PresetBundle(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::Plater::_calib_pa_tower(), Slic3r::GCode::_do_export(), Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::add_correct_opts_to_diff(), Slic3r::GUI::add_correct_opts_to_options_list(), Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::GUI::ObjectTableSettings::add_missed_options(), Slic3r::GCode::append_full_config(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::Search::OptionsSearcher::append_options(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::ConfigManipulation::apply(), Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GCodeProcessor::apply_config(), Slic3r::PlaceholderParser::apply_config(), Slic3r::GUI::ConfigManipulation::apply_null_fff_config(), Slic3r::ConfigBase::apply_only(), Slic3r::PlaceholderParser::apply_only(), Slic3r::GUI::GLCanvas3D::WipeTowerInfo::apply_wipe_tower(), Slic3r::GUI::ConfigOptionsGroup::back_to_config_value(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::TabPrinter::build_unregular_pages(), Slic3r::GUI::Plater::calib_max_vol_speed(), Slic3r::GUI::Plater::calib_retraction(), Slic3r::GUI::PlaterPresetComboBox::change_extruder_color(), Slic3r::Search::change_opt_key(), Slic3r::GUI::change_opt_value(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::Preset::compatible_printers_condition(), Slic3r::Preset::compatible_prints_condition(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::Tab::compatible_widget_reload(), Slic3r::GUI::Plater::config_change_notification(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::deep_diff(), Slic3r::GUI::Bed3D::detect_type(), Slic3r::ConfigBase::diff(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::CalibPressureAdvancePattern::draw_line(), Slic3r::ConfigBase::equal(), Slic3r::ConfigBase::equals(), Slic3r::GUI::GLCanvas3D::estimate_wipe_tower_points(), Slic3r::GUI::PartPlate::estimate_wipe_tower_size(), Slic3r::GUI::Plater::export_3mf(), Slic3r::PresetBundle::export_selections(), Slic3r::GUI::GUI_App::extruders_cnt(), Slic3r::GUI::TabPrinter::extruders_count_changed(), Slic3r::GUI::GUI_App::extruders_edited_cnt(), Slic3r::CalibPressureAdvance::find_optimal_PA_speed(), Slic3r::GUI::Plater::force_filament_colors_update(), Slic3r::PresetBundle::full_fff_config(), Slic3r::full_print_config_diffs(), Slic3r::PresetBundle::full_sla_config(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), Slic3r::ConfigBase::get_abs_value(), Slic3r::ConfigBase::get_abs_value(), Slic3r::GUI::ExtrusionCalibration::get_bed_temp(), Slic3r::anonymous_namespace{SL1.cpp}::get_cfg_value(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::ModelObject::get_config_value(), Slic3r::GUI::ConfigOptionsGroup::get_config_value2(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::GUI::Plater::get_extruder_colors_from_plater_config(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::DynamicPrintConfig::get_filament_type(), Slic3r::GUI::get_full_label(), Slic3r::get_instance_arrange_poly(), Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::PrintHost::get_print_host(), get_printer_technology(), Slic3r::anonymous_namespace{SL1.cpp}::get_raster_params(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), Slic3r::anonymous_namespace{SL1.cpp}::get_slice_params(), Slic3r::GUI::get_string_from_enum(), Slic3r::GUI::get_string_value(), Slic3r::GUI::ObjectGridTable::get_volume_config_value(), Slic3r::handle_legacy_project_loaded(), Slic3r::CalibPressureAdvancePattern::height_first_layer(), Slic3r::CalibPressureAdvancePattern::height_layer(), Slic3r::PresetBundle::import_presets(), Slic3r::Preset::inherits(), Slic3r::GUI::ObjectTablePanel::init_filaments_and_colors(), Slic3r::is_compatible_with_parent_printer(), Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::is_compatible_with_printer(), Slic3r::DynamicPrintConfig::is_custom_defined(), Slic3r::GUI::is_support_filament(), Slic3r::StaticConfig::keys(), Slic3r::GUI::MainFrame::load_config(), Slic3r::GUI::Tab::load_config(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::PresetCollection::load_external_preset(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::min_object_distance(), Slic3r::Preset::normalize(), Slic3r::DynamicPrintConfig::normalize_fdm(), Slic3r::DynamicPrintConfig::normalize_fdm_1(), Slic3r::GUI::TabPrintLayer::notify_changed(), Slic3r::GUI::ExtruderOptionsGroup::on_change_OG(), Slic3r::GUI::Plater::on_config_change(), Slic3r::GUI::TabPrinter::on_preset_loaded(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::DynamicConfig::opt(), Slic3r::DynamicConfig::opt(), Slic3r::DynamicConfig::opt_enum(), Slic3r::DynamicConfig::opt_enum(), Slic3r::DynamicConfig::opt_float(), Slic3r::DynamicConfig::opt_float(), Slic3r::DynamicConfig::opt_int(), Slic3r::DynamicConfig::opt_int(), Slic3r::ConfigBase::opt_serialize(), Slic3r::PlaceholderParser::option(), Slic3r::ModelConfig::option(), Slic3r::client::MyContext::optptr(), Slic3r::opts_equal(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::BackgroundSlicingProcess::prepare_upload(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::print_config_diffs(), Slic3r::Preset::printer_technology(), Slic3r::PhysicalPrinter::printer_technology(), Slic3r::Preset::printer_technology_ref(), Slic3r::DynamicConfig::read_cli(), Slic3r::CalibPressureAdvancePattern::refresh_setup(), Slic3r::GUI::ObjectGridTable::reload_object_data(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::reset_project_embedded_presets(), Slic3r::CLI::run(), Slic3r::Preset::save(), Slic3r::PresetCollection::save_current_preset(), Slic3r::ConfigBase::save_to_json(), Slic3r::GUI::Selection::scale_to_fit_print_volume(), Slic3r::GUI::Tab::select_preset(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::StaticConfig::set_defaults(), Slic3r::ConfigBase::set_deserialize_raw(), Slic3r::DynamicPrintConfig::set_num_extruders(), Slic3r::PresetBundle::set_num_filaments(), Slic3r::DynamicPrintConfig::set_num_filaments(), Slic3r::CLI::setup(), Slic3r::CalibPressureAdvancePattern::speed_first_layer(), Slic3r::CalibPressureAdvancePattern::speed_perimeter(), Slic3r::PresetBundle::sync_ams_list(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::ConfigManipulation::toggle_field(), Slic3r::GUI::ConfigManipulation::toggle_line(), Slic3r::GUI::TabFilament::toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::Plater::priv::undo_redo_to(), Slic3r::GUI::PhysicalPrinterDialog::update(), Slic3r::GUI::PresetComboBox::update_ams_color(), Slic3r::GLVolumeCollection::update_colors_by_extruder(), Slic3r::PresetBundle::update_compatible(), Slic3r::PresetCollection::update_compatible_internal(), Slic3r::GUI::ObjectTableSettings::update_config_values(), Slic3r::GUI::TabPrintLayer::update_custom_dirty(), Slic3r::GUI::TabPrinter::update_fff(), Slic3r::GUI::Plater::update_filament_colors_in_full_config(), Slic3r::GUI::TabFilament::update_filament_overrides_page(), Slic3r::PhysicalPrinter::update_from_config(), Slic3r::GUI::PhysicalPrinterDialog::update_host_type(), Slic3r::PresetBundle::update_multi_material_filament_presets(), Slic3r::PhysicalPrinter::update_preset_names_in_config(), Slic3r::GUI::Sidebar::update_presets(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::PresetBundle::update_selections(), Slic3r::GUI::ObjectTableSettings::update_settings_list(), Slic3r::DynamicPrintConfig::validate(), Slic3r::PresetBundle::validate_printers(), Slic3r::GUI::ObjectTableSettings::ValueChanged(), and Slic3r::CalibPressureAdvancePattern::wall_count().
option() [4/4]
template<typename TYPE > TYPE * Slic3r::ConfigBase::option (const t_config_option_key & opt_key, bool create = false) inline inherited
    {
        ConfigOption *opt = this->optptr(opt_key, create);
        return (opt == nullptr || opt->type() != TYPE::static_type()) ? nullptr : static_cast<TYPE*>(opt);
    }
References Slic3r::ConfigBase::optptr(), and Slic3r::ConfigOption::type().
option_throw() [1/4]
template<typename TYPE > const TYPE * Slic3r::ConfigOptionResolver::option_throw (const t_config_option_key & opt_key) const inline inherited
    {
        const ConfigOption* opt = this->option_throw(opt_key);
        if (opt->type() != TYPE::static_type())
            throw BadOptionTypeException("Conversion to a wrong type");
        return static_cast<TYPE*>(opt);
    }
option_throw() [2/4]
const ConfigOption * Slic3r::ConfigOptionResolver::option_throw (const t_config_option_key & opt_key) const inline inherited
    {
        const ConfigOption* opt = this->optptr(opt_key);
        if (opt == nullptr)
            throw UnknownOptionException(opt_key);
        return opt;
    }
option_throw() [3/4]
ConfigOption * Slic3r::ConfigBase::option_throw (const t_config_option_key & opt_key, bool create = false) inline inherited
    {
        ConfigOption *opt = this->optptr(opt_key, create);
        if (opt == nullptr)
            throw UnknownOptionException(opt_key);
        return opt;
    }
References Slic3r::ConfigBase::optptr().
Referenced by Slic3r::ConfigBase::option_throw(), Slic3r::ConfigBase::set(), and Slic3r::ConfigBase::set().
option_throw() [4/4]
template<typename TYPE > TYPE * Slic3r::ConfigBase::option_throw (const t_config_option_key & opt_key, bool create = false) inline inherited
    {
        ConfigOption *opt = this->option_throw(opt_key, create);
        if (opt->type() != TYPE::static_type())
            throw BadOptionTypeException("Conversion to a wrong type");
        return static_cast<TYPE*>(opt);
    }
References Slic3r::ConfigBase::option_throw(), and Slic3r::ConfigOption::type().
optptr() [1/2]
const ConfigOption * Slic3r::DynamicConfig::optptr (const t_config_option_key & opt_key) const override virtual inherited
Reimplemented from Slic3r::ConfigBase.
{
    auto it = options.find(opt_key);
    return (it == options.end()) ? nullptr : it->second.get();
}
References Slic3r::DynamicConfig::options.
Referenced by Slic3r::PresetBundle::PresetBundle(), and Slic3r::GUI::get_string_value().
optptr() [2/2]
ConfigOption * Slic3r::DynamicConfig::optptr (const t_config_option_key & opt_key, bool create = false) override virtual inherited
Implements Slic3r::ConfigBase.
{
    auto it = options.find(opt_key);
    if (it != options.end())
        // Option was found.
        return it->second.get();
    if (! create)
        // Option was not found and a new option shall not be created.
        return nullptr;
    // Try to create a new ConfigOption.
    const ConfigDef       *def    = this->def();
    if (def == nullptr)
        throw NoDefinitionException(opt_key);
    const ConfigOptionDef *optdef = def->get(opt_key);
    if (optdef == nullptr)
//        throw ConfigurationError(std::string("Invalid option name: ") + opt_key);
        // Let the parent decide what to do if the opt_key is not defined by this->def().
        return nullptr;
    ConfigOption *opt = optdef->create_default_option();
    this->options.emplace_hint(it, opt_key, std::unique_ptr<ConfigOption>(opt));
    return opt;
}
References Slic3r::ConfigOptionDef::create_default_option(), Slic3r::DynamicConfig::def(), Slic3r::ConfigDef::get(), Slic3r::DynamicConfig::opt(), and Slic3r::DynamicConfig::options.
read_cli()
bool Slic3r::DynamicConfig::read_cli (int argc, const char *const argv[], t_config_option_keys * extra, t_config_option_keys * keys = nullptr) inherited
{
    // cache the CLI option => opt_key mapping
    std::map<std::string,std::string> opts;
    for (const auto &oit : this->def()->options)
        for (const std::string &t : oit.second.cli_args(oit.first))
            opts[t] = oit.first;
    bool parse_options = true;
    for (int i = 1; i < argc; ++ i) {
        std::string token = argv[i];
        // Store non-option arguments in the provided vector.
        if (! parse_options || ! boost::starts_with(token, "-")) {
            extra->push_back(token);
            continue;
        }
#ifdef __APPLE__
        if (boost::starts_with(token, "-psn_"))
            // OSX launcher may add a "process serial number", for example "-psn_0_989382" to the command line.
            // While it is supposed to be dropped since OSX 10.9, we will rather ignore it.
            continue;
#endif /* __APPLE__ */
        // Stop parsing tokens as options when -- is supplied.
        if (token == "--") {
            parse_options = false;
            continue;
        }
        // Remove leading dashes (one or two).
        token.erase(token.begin(), token.begin() + (boost::starts_with(token, "--") ? 2 : 1));
        // Read value when supplied in the --key=value form.
        std::string value;
        {
            size_t equals_pos = token.find("=");
            if (equals_pos != std::string::npos) {
                value = token.substr(equals_pos+1);
                token.erase(equals_pos);
            }
        }
        // Look for the cli -> option mapping.
        auto it = opts.find(token);
        bool no = false;
        if (it == opts.end()) {
            //BBS: don't use 'no-' for boolean options
            boost::nowide::cerr << "Invalid option --" << token.c_str() << std::endl;
            return false;
            /* Remove the "no-" prefix used to negate boolean options.
            std::string yes_token;
            if (boost::starts_with(token, "no-")) {
                yes_token = token.substr(3);
                it = opts.find(yes_token);
                no = true;
            }
            if (it == opts.end()) {
                boost::nowide::cerr << "Invalid option --" << token.c_str() << std::endl;
                return false;
            }
            if (no)
                token = yes_token;*/
        }
        const t_config_option_key &opt_key = it->second;
        const ConfigOptionDef     &optdef  = this->def()->options.at(opt_key);
        // If the option type expects a value and it was not already provided,
        // look for it in the next token.
        if (value.empty() && optdef.type != coBool && optdef.type != coBools) {
            if (i == argc-1) {
                boost::nowide::cerr << "Need values for option --" << token.c_str() << std::endl;
                return false;
            }
            value = argv[++ i];
        }
        /*if (no) {
            assert(optdef.type == coBool || optdef.type == coBools);
            if (! value.empty()) {
                boost::nowide::cerr << "Boolean options negated by the --no- prefix cannot have a value." << std::endl;
                return false;
            }
        }*/
        // Store the option value.
        const bool               existing   = this->has(opt_key);
        if (keys != nullptr && ! existing) {
            // Save the order of detected keys.
            keys->push_back(opt_key);
        }
        ConfigOption            *opt_base   = this->option(opt_key, true);
        ConfigOptionVectorBase  *opt_vector = opt_base->is_vector() ? static_cast<ConfigOptionVectorBase*>(opt_base) : nullptr;
        if (opt_vector) {
      if (! existing)
        // remove the default values
        opt_vector->clear();
            // Vector values will be chained. Repeated use of a parameter will append the parameter or parameters
            // to the end of the value.
            if (opt_base->type() == coBools && value.empty())
                static_cast<ConfigOptionBools*>(opt_base)->values.push_back(!no);
            else
                // Deserialize any other vector value (ConfigOptionInts, Floats, Percents, Points) the same way
                // they get deserialized from an .ini file. For ConfigOptionStrings, that means that the C-style unescape
                // will be applied for values enclosed in quotes, while values non-enclosed in quotes are left to be
                // unescaped by the calling shell.
        opt_vector->deserialize(value, true);
        } else if (opt_base->type() == coBool) {
            if (value.empty())
                static_cast<ConfigOptionBool*>(opt_base)->value = !no;
            else
                opt_base->deserialize(value);
        } else if (opt_base->type() == coString) {
            // Do not unescape single string values, the unescaping is left to the calling shell.
            static_cast<ConfigOptionString*>(opt_base)->value = value;
        } else {
            // Just bail out if the configuration value is not understood.
            ConfigSubstitutionContext context(ForwardCompatibilitySubstitutionRule::Disable);
            // Any scalar value of a type different from Bool and String.
            if (! this->set_deserialize_nothrow(opt_key, value, context, false)) {
        boost::nowide::cerr << "Invalid value for option --" << token.c_str() << std::endl;
        return false;
      }
        }
    }
    return true;
}
References Slic3r::ConfigOptionVectorBase::clear(), Slic3r::coBool, Slic3r::coBools, Slic3r::coString, Slic3r::DynamicConfig::def(), Slic3r::ConfigOption::deserialize(), Slic3r::Disable, Slic3r::ConfigOptionResolver::has(), Slic3r::ConfigOption::is_vector(), Slic3r::DynamicConfig::keys(), Slic3r::ConfigBase::option(), Slic3r::ConfigDef::options, Slic3r::ConfigBase::set_deserialize_nothrow(), Slic3r::ConfigOption::type(), Slic3r::ConfigOptionDef::type, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::CLI::setup().
remove_nil_options()
size_t Slic3r::DynamicConfig::remove_nil_options () inherited
{
  size_t cnt_removed = 0;
  for (auto it = options.begin(); it != options.end();)
    if (it->second->is_nil()) {
      it = options.erase(it);
      ++ cnt_removed;
    } else
      ++ it;
  return cnt_removed;
}
References Slic3r::DynamicConfig::options.
save()
void Slic3r::ConfigBase::save (const std::string & file) const inherited
{
    boost::nowide::ofstream c;
    c.open(file, std::ios::out | std::ios::trunc);
    c << "# " << Slic3r::header_slic3r_generated() << std::endl;
    for (const std::string &opt_key : this->keys())
        c << opt_key << " = " << this->opt_serialize(opt_key) << std::endl;
    c.close();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", saved config to %1%\n")%file;
}
References Slic3r::header_slic3r_generated(), Slic3r::ConfigBase::keys(), and Slic3r::ConfigBase::opt_serialize().
save_to_json()
void Slic3r::ConfigBase::save_to_json (const std::string & file, const std::string & name, const std::string & from, const std::string & version, const std::string is_custom = "") const inherited
{
    json j;
    //record the headers
    j[BBL_JSON_KEY_VERSION] = version;
    j[BBL_JSON_KEY_NAME] = name;
    j[BBL_JSON_KEY_FROM] = from;
    if (!is_custom.empty())
        j[BBL_JSON_KEY_IS_CUSTOM] = is_custom;
    //record all the key-values
    for (const std::string &opt_key : this->keys())
    {
        const ConfigOption* opt = this->option(opt_key);
        if ( opt->is_scalar() ) {
            if (opt->type() == coString && (opt_key != "bed_custom_texture" && opt_key != "bed_custom_model"))
                //keep \n, \r, \t
                j[opt_key] = (dynamic_cast<const ConfigOptionString *>(opt))->value;
            else
                j[opt_key] = opt->serialize();
        }
        else {
            const ConfigOptionVectorBase *vec = static_cast<const ConfigOptionVectorBase*>(opt);
            //if (!vec->empty())
            std::vector<std::string> string_values = vec->vserialize();
            /*for (int i = 0; i < string_values.size(); i++)
            {
                std::string string_value = escape_string_cstyle(string_values[i]);
                j[opt_key][i] = string_value;
            }*/
            json j_array(string_values);
            j[opt_key] = j_array;
        }
    }
    boost::nowide::ofstream c;
    c.open(file, std::ios::out | std::ios::trunc);
    c << std::setw(4) << j << std::endl;
    c.close();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", saved config to %1%\n")%file;
}
References BBL_JSON_KEY_FROM, BBL_JSON_KEY_IS_CUSTOM, BBL_JSON_KEY_NAME, BBL_JSON_KEY_VERSION, Slic3r::coString, Slic3r::ConfigOption::is_scalar(), Slic3r::ConfigBase::keys(), Slic3r::ConfigBase::option(), Slic3r::ConfigOption::serialize(), Slic3r::ConfigOption::type(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value(), and Slic3r::ConfigOptionVectorBase::vserialize().
Referenced by Slic3r::_BBS_3MF_Exporter::_add_project_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive(), Slic3r::CLI::run(), Slic3r::PhysicalPrinter::save(), Slic3r::Preset::save(), and Slic3r::PhysicalPrinter::save().
serialize()
template<class Archive > void Slic3r::DynamicConfig::serialize (Archive & ar) inline private inherited
{ ar(options); }
References Slic3r::DynamicConfig::options.
set() [1/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, bool value, bool create = false) inline inherited
      { this->option_throw<ConfigOptionBool>(opt_key, create)->value = value; }
Referenced by Slic3r::import_sla_archive(), Slic3r::CLI::run(), and Slic3r::ModelConfig::set().
set() [2/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, const char * value, bool create = false) inline inherited
      { this->option_throw<ConfigOptionString>(opt_key, create)->value = value; }
set() [3/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, const std::string & value, bool create = false) inline inherited
      { this->option_throw<ConfigOptionString>(opt_key, create)->value = value; }
set() [4/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, double value, bool create = false) inherited
{
    ConfigOption *opt = this->option_throw(opt_key, create);
    switch (opt->type()) {
      case coFloat:       static_cast<ConfigOptionFloat*>(opt)->value = value; break;
      case coFloatOrPercent:  static_cast<ConfigOptionFloatOrPercent*>(opt)->value = value; static_cast<ConfigOptionFloatOrPercent*>(opt)->percent = false; break;
        case coString:      static_cast<ConfigOptionString*>(opt)->value = float_to_string_decimal_point(value); break;
      default: throw BadOptionTypeException("Configbase::set() - conversion from float not possible");
    }
}
References Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coString, Slic3r::float_to_string_decimal_point(), Slic3r::ConfigBase::option_throw(), and Slic3r::ConfigOption::type().
set() [5/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, int value, bool create = false) inherited
{
    ConfigOption *opt = this->option_throw(opt_key, create);
    switch (opt->type()) {
      case coInt:    static_cast<ConfigOptionInt*>(opt)->value = value; break;
      case coFloat:  static_cast<ConfigOptionFloat*>(opt)->value = value; break;
    case coFloatOrPercent:  static_cast<ConfigOptionFloatOrPercent*>(opt)->value = value; static_cast<ConfigOptionFloatOrPercent*>(opt)->percent = false; break;
    case coString: static_cast<ConfigOptionString*>(opt)->value = std::to_string(value); break;
      default: throw BadOptionTypeException("Configbase::set() - conversion from int not possible");
    }
}
References Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coInt, Slic3r::coString, Slic3r::ConfigBase::option_throw(), and Slic3r::ConfigOption::type().
set_deserialize() [1/2]
void Slic3r::ConfigBase::set_deserialize (const t_config_option_key & opt_key, const std::string & str, ConfigSubstitutionContext & config_substitutions, bool append = false) inherited
{
  if (! this->set_deserialize_nothrow(opt_key_src, value_src, substitutions_ctxt, append))
    throw BadOptionValueException(format("Invalid value provided for parameter %1%: %2%", opt_key_src,  value_src));
}
References Slic3r::append(), Slic3r::format(), and Slic3r::ConfigBase::set_deserialize_nothrow().
Referenced by Slic3r::ConfigBase::load(), Slic3r::ConfigBase::load_from_gcode_file(), Slic3r::ConfigBase::load_from_gcode_string_legacy(), Slic3r::ConfigBase::load_from_json(), Slic3r::ConfigBase::load_string_map(), Slic3r::ModelConfig::set_deserialize(), Slic3r::ConfigBase::set_deserialize(), Slic3r::ConfigBase::set_deserialize_strict(), and Slic3r::ConfigBase::set_deserialize_strict().
set_deserialize() [2/2]
void Slic3r::ConfigBase::set_deserialize (std::initializer_list< SetDeserializeItem > items, ConfigSubstitutionContext & substitutions) inherited
{
  for (const SetDeserializeItem &item : items)
    this->set_deserialize(item.opt_key, item.opt_value, substitutions_ctxt, item.append);
}
References Slic3r::ConfigBase::set_deserialize().
set_deserialize_nothrow()
bool Slic3r::ConfigBase::set_deserialize_nothrow (const t_config_option_key & opt_key_src, const std::string & value_src, ConfigSubstitutionContext & substitutions, bool append = false) inherited
{
    t_config_option_key opt_key = opt_key_src;
    std::string         value   = value_src;
    // Both opt_key and value may be modified by handle_legacy().
    // If the opt_key is no more valid in this version of Slic3r, opt_key is cleared by handle_legacy().
    this->handle_legacy(opt_key, value);
    if (opt_key.empty()) {
        // Ignore the option.
        //BBS: record these options, keep only one repeated opt_key
        auto iter = std::find(substitutions_ctxt.unrecogized_keys.begin(), substitutions_ctxt.unrecogized_keys.end(), opt_key_src);
        if (iter == substitutions_ctxt.unrecogized_keys.end())
            substitutions_ctxt.unrecogized_keys.push_back(opt_key_src);
        return true;
    }
    return this->set_deserialize_raw(opt_key, value, substitutions_ctxt, append);
}
References Slic3r::append(), Slic3r::ConfigBase::handle_legacy(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::ConfigSubstitutionContext::unrecogized_keys.
Referenced by Slic3r::DynamicConfig::read_cli(), and Slic3r::ConfigBase::set_deserialize().
set_deserialize_raw()
bool Slic3r::ConfigBase::set_deserialize_raw (const t_config_option_key & opt_key_src, const std::string & value, ConfigSubstitutionContext & substitutions, bool append) private inherited
{
    t_config_option_key    opt_key = opt_key_src;
    // Try to deserialize the option by its name.
    const ConfigDef       *def     = this->def();
    if (def == nullptr)
        throw NoDefinitionException(opt_key);
    const ConfigOptionDef *optdef  = def->get(opt_key);
    if (optdef == nullptr) {
        // If we didn't find an option, look for any other option having this as an alias.
        for (const auto &opt : def->options) {
            for (const t_config_option_key &opt_key2 : opt.second.aliases) {
                if (opt_key2 == opt_key) {
                    opt_key = opt.first;
                    optdef = &opt.second;
                    break;
                }
            }
            if (optdef != nullptr)
                break;
        }
        if (optdef == nullptr)
            throw UnknownOptionException(opt_key);
    }
    if (! optdef->shortcut.empty()) {
        // Aliasing for example "solid_layers" to "top_shell_layers" and "bottom_shell_layers".
        for (const t_config_option_key &shortcut : optdef->shortcut)
            // Recursive call.
            if (! this->set_deserialize_raw(shortcut, value, substitutions_ctxt, append))
                return false;
        return true;
    }
    ConfigOption *opt = this->option(opt_key, true);
    assert(opt != nullptr);
    bool success     = false;
    bool substituted = false;
    if (optdef->type == coBools && substitutions_ctxt.rule != ForwardCompatibilitySubstitutionRule::Disable) {
        //FIXME Special handling of vectors of bools, quick and not so dirty solution before PrusaSlicer 2.3.2 release.
      bool nullable = opt->nullable();
      ConfigHelpers::DeserializationSubstitution default_value = ConfigHelpers::DeserializationSubstitution::DefaultsToFalse;
      if (optdef->default_value) {
        // Default value for vectors of booleans used in a "per extruder" context, thus the default contains just a single value.
        assert(dynamic_cast<const ConfigOptionVector<unsigned char>*>(optdef->default_value.get()));
      auto &values = static_cast<const ConfigOptionVector<unsigned char>*>(optdef->default_value.get())->values;
      if (values.size() == 1 && values.front() == 1)
        default_value = ConfigHelpers::DeserializationSubstitution::DefaultsToTrue;
    }
      auto result = nullable ?
        static_cast<ConfigOptionBoolsNullable*>(opt)->deserialize_with_substitutions(value, append, default_value) :
        static_cast<ConfigOptionBools*>(opt)->deserialize_with_substitutions(value, append, default_value);
      success     = result != ConfigHelpers::DeserializationResult::Failed;
      substituted = result == ConfigHelpers::DeserializationResult::Substituted;
    } else {
    //bool test = (opt_key == "filament_end_gcode");
    success = opt->deserialize(value, append);
      if (! success && substitutions_ctxt.rule != ForwardCompatibilitySubstitutionRule::Disable &&
          // Only allow substitutions of an enum value by another enum value or a boolean value with an enum value.
          // That means, we expect enum values being added in the future and possibly booleans being converted to enums.
            (optdef->type == coEnum || optdef->type == coEnums || optdef->type == coBool) /*&& ConfigHelpers::looks_like_enum_value(value)*/) {
          // Deserialize failed, try to substitute with a default value.
          //assert(substitutions_ctxt.rule == ForwardCompatibilitySubstitutionRule::Enable || substitutions_ctxt.rule == ForwardCompatibilitySubstitutionRule::EnableSilent);
          if (optdef->type == coBool)
              static_cast<ConfigOptionBool*>(opt)->value = ConfigHelpers::enum_looks_like_true_value(value);
          else
            // Just use the default of the option.
              opt->set(optdef->default_value.get());
            success     = true;
            substituted = true;
      }
  }
    if (substituted && (substitutions_ctxt.rule == ForwardCompatibilitySubstitutionRule::Enable ||
                        substitutions_ctxt.rule == ForwardCompatibilitySubstitutionRule::EnableSystemSilent)) {
        // Log the substitution.
        ConfigSubstitution config_substitution;
        config_substitution.opt_def   = optdef;
        config_substitution.old_value = value;
        config_substitution.new_value = ConfigOptionUniquePtr(opt->clone());
        substitutions_ctxt.substitutions.emplace_back(std::move(config_substitution));
    }
    return success;
}
References Slic3r::append(), Slic3r::ConfigOption::clone(), Slic3r::coBool, Slic3r::coBools, Slic3r::coEnum, Slic3r::coEnums, Slic3r::ConfigBase::def(), Slic3r::ConfigOptionDef::default_value, Slic3r::ConfigHelpers::DefaultsToFalse, Slic3r::ConfigHelpers::DefaultsToTrue, Slic3r::ConfigOption::deserialize(), Slic3r::Disable, Slic3r::Enable, Slic3r::EnableSystemSilent, Slic3r::ConfigHelpers::enum_looks_like_true_value(), Slic3r::ConfigHelpers::Failed, Slic3r::ConfigDef::get(), Slic3r::ConfigSubstitution::new_value, Slic3r::ConfigOption::nullable(), Slic3r::ConfigSubstitution::old_value, Slic3r::ConfigSubstitution::opt_def, Slic3r::ConfigBase::option(), Slic3r::ConfigDef::options, Slic3r::ConfigSubstitutionContext::rule, Slic3r::ConfigOption::set(), Slic3r::ConfigBase::set_deserialize_raw(), Slic3r::ConfigOptionDef::shortcut, Slic3r::ConfigHelpers::Substituted, Slic3r::ConfigSubstitutionContext::substitutions, and Slic3r::ConfigOptionDef::type.
Referenced by Slic3r::ConfigBase::set_deserialize_nothrow(), and Slic3r::ConfigBase::set_deserialize_raw().
set_deserialize_strict() [1/2]
void Slic3r::ConfigBase::set_deserialize_strict (const t_config_option_key & opt_key, const std::string & str, bool append = false) inline inherited
        { ConfigSubstitutionContext ctxt{ ForwardCompatibilitySubstitutionRule::Disable }; this->set_deserialize(opt_key, str, ctxt, append); }
References Slic3r::append(), Slic3r::Disable, and Slic3r::ConfigBase::set_deserialize().
set_deserialize_strict() [2/2]
void Slic3r::ConfigBase::set_deserialize_strict (std::initializer_list< SetDeserializeItem > items) inline inherited
        { ConfigSubstitutionContext ctxt{ ForwardCompatibilitySubstitutionRule::Disable }; this->set_deserialize(items, ctxt); }
References Slic3r::Disable, and Slic3r::ConfigBase::set_deserialize().
set_key_value()
bool Slic3r::DynamicConfig::set_key_value (const std::string & opt_key, ConfigOption * opt) inline inherited
    {
        auto it = this->options.find(opt_key);
        if (it == this->options.end()) {
            this->options[opt_key].reset(opt);
            return true;
        } else {
            it->second.reset(opt);
            return false;
        }
    }
Referenced by Slic3r::PhysicalPrinterCollection::PhysicalPrinterCollection(), Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::_BBS_3MF_Importer::_handle_start_config_metadata(), Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::GUI::ConfigManipulation::apply(), Slic3r::GUI::PageFirmware::apply_custom_config(), Slic3r::GUI::PageBedShape::apply_custom_config(), Slic3r::GUI::PageDiameters::apply_custom_config(), Slic3r::GUI::ConfigManipulation::apply_null_fff_config(), Slic3r::GUI::PlaterPresetComboBox::change_extruder_color(), Slic3r::GUI::change_opt_value(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::PrintStatistics::config(), Slic3r::ProcessLayer::emit_custom_gcode_per_print_z(), Slic3r::is_compatible_with_printer(), cereal::load(), Slic3r::GUI::Sidebar::load_ams_list(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::GUI::Tab::on_value_change(), Slic3r::Print::output_filename(), Slic3r::PrintBase::output_filename(), Slic3r::PrintStatistics::placeholders(), Slic3r::print_config_diffs(), Slic3r::GCode::process_layer(), Slic3r::PlaceholderParser::set(), Slic3r::GUI::PartPlate::set_bed_type(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::GCode::set_extruder(), Slic3r::ModelConfig::set_key_value(), Slic3r::GUI::PartPlate::set_print_seq(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::PresetComboBox::update_ams_color(), Slic3r::PresetCollection::update_compatible_internal(), Slic3r::GUI::PhysicalPrinterDialog::update_host_type(), Slic3r::PrintBase::update_object_placeholders(), Slic3r::update_preset_name_option(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), and Slic3r::PlaceholderParser::update_timestamp().
set_num_extruders()
void Slic3r::DynamicPrintConfig::set_num_extruders (unsigned int num_extruders) inherited
{
    const auto &defaults = FullPrintConfig::defaults();
    for (const std::string &key : print_config_def.extruder_option_keys()) {
        if (key == "default_filament_profile")
            // Don't resize this field, as it is presented to the user at the "Dependencies" page of the Printer profile and we don't want to present
            // empty fields there, if not defined by the system profile.
            continue;
        auto *opt = this->option(key, false);
        assert(opt != nullptr);
        assert(opt->is_vector());
        if (opt != nullptr && opt->is_vector())
            static_cast<ConfigOptionVectorBase*>(opt)->resize(num_extruders, defaults.option(key));
    }
}
References Slic3r::PrintConfigDef::extruder_option_keys(), Slic3r::DynamicConfig::opt(), Slic3r::ConfigBase::option(), and Slic3r::print_config_def.
Referenced by Slic3r::Preset::set_num_extruders().
set_num_filaments()
void Slic3r::DynamicPrintConfig::set_num_filaments (unsigned int num_filaments) inherited
{
    const auto& defaults = FullPrintConfig::defaults();
    for (const std::string& key : print_config_def.filament_option_keys()) {
        if (key == "default_filament_profile")
            // Don't resize this field, as it is presented to the user at the "Dependencies" page of the Printer profile and we don't want to present
            // empty fields there, if not defined by the system profile.
            continue;
        auto* opt = this->option(key, false);
        assert(opt != nullptr);
        assert(opt->is_vector());
        if (opt != nullptr && opt->is_vector())
            static_cast<ConfigOptionVectorBase*>(opt)->resize(num_filaments, defaults.option(key));
    }
}
References Slic3r::PrintConfigDef::filament_option_keys(), Slic3r::DynamicConfig::opt(), Slic3r::ConfigBase::option(), and Slic3r::print_config_def.
Referenced by Slic3r::Preset::normalize().
setenv_()
void Slic3r::ConfigBase::setenv_ () const inherited
{
    t_config_option_keys opt_keys = this->keys();
    for (t_config_option_keys::const_iterator it = opt_keys.begin(); it != opt_keys.end(); ++it) {
        // prepend the SLIC3R_ prefix
        std::ostringstream ss;
        ss << "SLIC3R_";
        ss << *it;
        std::string envname = ss.str();
        // capitalize environment variable name
        for (size_t i = 0; i < envname.size(); ++i)
            envname[i] = (envname[i] <= 'z' && envname[i] >= 'a') ? envname[i]-('a'-'A') : envname[i];
        boost::nowide::setenv(envname.c_str(), this->opt_serialize(*it).c_str(), 1);
    }
}
References Slic3r::ConfigBase::keys().
Referenced by Slic3r::run_post_process_scripts().
size()
size_t Slic3r::DynamicConfig::size () const inline inherited
{ return options.size(); }
References Slic3r::DynamicConfig::options.
Referenced by Slic3r::Print::apply(), cereal::save(), Slic3r::GUI::Plater::setExtruderParams(), and Slic3r::ModelConfig::size().
swap()
void Slic3r::DynamicConfig::swap (DynamicConfig & other) inline inherited
    {
        std::swap(this->options, other.options);
    }
References Slic3r::DynamicConfig::options.
validate()
std::map< std::string, std::string > Slic3r::DynamicPrintConfig::validate (bool under_cli = false) inherited
{
    // Full print config is initialized from the defaults.
    const ConfigOption *opt = this->option("printer_technology", false);
    auto printer_technology = (opt == nullptr) ? ptFFF : static_cast<PrinterTechnology>(dynamic_cast<const ConfigOptionEnumGeneric*>(opt)->value);
    switch (printer_technology) {
    case ptFFF:
    {
        FullPrintConfig fpc;
        fpc.apply(*this, true);
        // Verify this print options through the FullPrintConfig.
        return Slic3r::validate(fpc, under_cli);
    }
    default:
        //FIXME no validation on SLA data?
        return std::map<std::string, std::string>();
    }
}
References Slic3r::DynamicConfig::opt(), Slic3r::ConfigBase::option(), Slic3r::printer_technology(), Slic3r::ptFFF, and Slic3r::validate().
Referenced by Slic3r::GUI::Plater::priv::load_files(), Slic3r::CLI::run(), and Slic3r::CLI::setup().
Member Data Documentation
options
std::map<t_config_option_key, std::unique_ptr<ConfigOption> > Slic3r::DynamicConfig::options private inherited
Referenced by Slic3r::DynamicConfig::DynamicConfig(), Slic3r::DynamicConfig::cbegin(), Slic3r::DynamicConfig::cend(), Slic3r::DynamicConfig::empty(), handle_legacy(), Slic3r::DynamicConfig::keys(), Slic3r::DynamicConfig::operator+=(), Slic3r::DynamicConfig::operator=(), Slic3r::DynamicConfig::operator==(), Slic3r::DynamicConfig::optptr(), Slic3r::DynamicConfig::optptr(), Slic3r::DynamicConfig::remove_nil_options(), Slic3r::DynamicConfig::serialize(), Slic3r::DynamicConfig::size(), and Slic3r::DynamicConfig::swap().
s_def
DynamicPrintAndCLIConfig::PrintAndCLIConfigDef Slic3r::DynamicPrintAndCLIConfig::s_def static private
Referenced by def().
The documentation for this class was generated from the following files:
src/libslic3r/PrintConfig.hpp
src/libslic3r/PrintConfig.cpp