OrcaSlicer: Slic3r::GUI::Page Class Reference
Slic3r::GUI::Page Class Reference
#include <src/slic3r/GUI/Tab.hpp>
Public Member Functions
Page (wxWindow *parent, const wxString &title, int iconID, wxPanel *tab_owner)
~Page ()
wxBoxSizer * vsizer () const
wxWindow * parent () const
const wxString & title () const
size_t iconID () const
void set_config (DynamicPrintConfig *config_in)
void reload_config ()
void update_visibility (ConfigOptionMode mode, bool update_contolls_visibility)
void activate (ConfigOptionMode mode, std::function< void()> throw_if_canceled)
void clear ()
void msw_rescale ()
void sys_color_changed ()
void refresh ()
Field * get_field (const t_config_option_key &opt_key, int opt_index=-1) const
Line * get_line (const t_config_option_key &opt_key)
bool set_value (const t_config_option_key &opt_key, const boost::any &value)
ConfigOptionsGroupShp new_optgroup (const wxString &title, const wxString &icon=wxEmptyString, int noncommon_label_width=-1, bool is_extruder_og=false)
const ConfigOptionsGroupShp get_optgroup (const wxString &title) const
bool set_item_colour (const wxColour *clr)
const wxColour get_item_colour ()
bool get_show () const
Public Attributes
bool m_is_modified_values { false }
bool m_is_nonsys_values { true }
bool m_split_multi_line = false
bool m_option_label_at_right = false
std::vector< ConfigOptionsGroupShp > m_optgroups
DynamicPrintConfig * m_config
Protected Attributes
const wxColour * m_item_color
Private Attributes
wxPanel * m_tab_owner
wxWindow * m_parent
wxString m_title
size_t m_iconID
wxBoxSizer * m_vsizer
wxStaticText * m_page_title
bool m_show = true
Detailed Description
Constructor & Destructor Documentation
Page()
Slic3r::GUI::Page::Page (wxWindow * parent, const wxString & title, int iconID, wxPanel * tab_owner)
                                                                                  :
        m_tab_owner(tab_owner),
        m_parent(parent),
        m_title(title),
        m_iconID(iconID)
{
    m_vsizer = (wxBoxSizer*)parent->GetSizer();
    m_page_title = NULL;
    m_item_color = &wxGetApp().get_label_clr_default();
}
References m_item_color, m_page_title, m_vsizer, NULL, and parent().
~Page()
Slic3r::GUI::Page::~Page () inline
{}
Member Function Documentation
activate()
void Slic3r::GUI::Page::activate (ConfigOptionMode mode, std::function< void()> throw_if_canceled)
{
#if 0 // BBS: page title
    if (m_page_title == NULL) {
        m_page_title = new Label(Label::Head_18, _(m_title), m_parent);
        m_vsizer->AddSpacer(30);
        m_vsizer->Add(m_page_title, 0, wxALIGN_CENTER);
        m_vsizer->AddSpacer(20);
    }
#else
    //m_vsizer->AddSpacer(10);
#endif
#if HIDE_FIRST_SPLIT_LINE
    // BBS: no line spliter for first group
    bool first = true;
#endif
    for (auto group : m_optgroups) {
        if (!group->activate(throw_if_canceled))
            continue;
        m_vsizer->Add(group->sizer, 0, wxEXPAND | (group->is_legend_line() ? (wxLEFT|wxTOP) : wxALL), 5);
        group->update_visibility(mode);
#if HIDE_FIRST_SPLIT_LINE
        if (first) group->stb->Hide();
        first = false;
#endif
        group->reload_config();
        throw_if_canceled();
    }
#ifdef __WXMSW__
    // BBS: fix field control position
    wxTheApp->CallAfter([this]() {
        for (auto group : m_optgroups) {
            if (group->custom_ctrl)
                group->custom_ctrl->fixup_items_positions();
        }
    });
#endif
}
References _, Label::Head_18, m_optgroups, m_page_title, m_parent, m_title, m_vsizer, and NULL.
Referenced by Slic3r::GUI::Tab::activate_selected_page().
clear()
void Slic3r::GUI::Page::clear ()
{
    for (auto group : m_optgroups)
        group->clear();
    m_page_title = NULL;
}
References m_optgroups, m_page_title, and NULL.
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed().
get_field()
Field * Slic3r::GUI::Page::get_field (const t_config_option_key & opt_key, int opt_index = -1) const
{
    Field *field = nullptr;
    for (auto opt : m_optgroups) {
        field = opt->get_fieldc(opt_key, opt_index);
        if (field != nullptr) return field;
    }
    return field;
}
References m_optgroups.
Referenced by Slic3r::GUI::TabPrintModel::activate_selected_page(), and Slic3r::GUI::TabPrintModel::update_model_config().
get_item_colour()
const wxColour Slic3r::GUI::Page::get_item_colour () inline
{
      return *m_item_color;
  }
References m_item_color.
get_line()
Line * Slic3r::GUI::Page::get_line (const t_config_option_key & opt_key)
{
    Line *line = nullptr;
    for (auto opt : m_optgroups) {
        line = opt->get_line(opt_key);
        if (line != nullptr) return line;
    }
    return line;
}
References m_optgroups.
get_optgroup()
const ConfigOptionsGroupShp Slic3r::GUI::Page::get_optgroup (const wxString & title) const
{
    for (ConfigOptionsGroupShp optgroup : m_optgroups) {
        if (optgroup->title == title)
            return optgroup;
    }
    return nullptr;
}
References m_optgroups, and title().
get_show()
bool Slic3r::GUI::Page::get_show () const inline
{ return m_show; }
References m_show.
iconID()
size_t Slic3r::GUI::Page::iconID () const inline
{ return m_iconID; }
References m_iconID.
msw_rescale()
void Slic3r::GUI::Page::msw_rescale ()
{
    for (auto group : m_optgroups)
        group->msw_rescale();
}
References m_optgroups.
new_optgroup()
ConfigOptionsGroupShp Slic3r::GUI::Page::new_optgroup (const wxString & title, const wxString & icon = wxEmptyString, int noncommon_label_width = -1, bool is_extruder_og = false)
config_ have to be "right"
This function will be called from OptionGroup. Using of CallAfter is redundant. And in some cases it causes update() function to be recalled again wxTheApp->CallAfter([this, opt_key, value]() {
});
{
    ConfigOptionsGroupShp optgroup = is_extruder_og ? std::make_shared<ExtruderOptionsGroup>(m_parent, title, m_config, true)
        : std::make_shared<ConfigOptionsGroup>(m_parent, title, icon, m_config, true);
    optgroup->split_multi_line     = this->m_split_multi_line;
    optgroup->option_label_at_right = this->m_option_label_at_right;
    if (noncommon_label_width >= 0)
        optgroup->label_width = noncommon_label_width;
//BBS: GUI refactor
/*#ifdef __WXOSX__
    auto tab = parent()->GetParent()->GetParent();// GetParent()->GetParent();
#else
    auto tab = parent()->GetParent();// GetParent();
#endif*/
    auto tab = m_tab_owner;
    optgroup->set_config_category_and_type(m_title, static_cast<Tab*>(tab)->type());
    optgroup->m_on_change = [tab](t_config_option_key opt_key, boost::any value) {
            static_cast<Tab*>(tab)->update_dirty();
            static_cast<Tab*>(tab)->on_value_change(opt_key, value);
    };
    optgroup->m_get_initial_config = [tab]() {
        DynamicPrintConfig config = static_cast<Tab*>(tab)->m_presets->get_selected_preset().config;
        return config;
    };
    optgroup->m_get_sys_config = [tab]() {
        DynamicPrintConfig config = static_cast<Tab*>(tab)->m_presets->get_selected_preset_parent()->config;
        return config;
    };
    optgroup->have_sys_config = [tab]() {
        return static_cast<Tab*>(tab)->m_presets->get_selected_preset_parent() != nullptr;
    };
    optgroup->rescale_extra_column_item = [](wxWindow* win) {
        auto *ctrl = dynamic_cast<wxStaticBitmap*>(win);
        if (ctrl == nullptr)
            return;
        ctrl->SetBitmap(reinterpret_cast<ScalableBitmap*>(ctrl->GetClientData())->bmp());
    };
    m_optgroups.push_back(optgroup);
    return optgroup;
}
References Slic3r::GUI::ctrl, m_config, m_optgroups, m_option_label_at_right, m_parent, m_split_multi_line, m_tab_owner, m_title, and title().
parent()
wxWindow * Slic3r::GUI::Page::parent () const inline
{ return m_parent; }
References m_parent.
Referenced by Page().
refresh()
void Slic3r::GUI::Page::refresh ()
{
    for (auto group : m_optgroups)
        group->refresh();
}
References m_optgroups.
reload_config()
void Slic3r::GUI::Page::reload_config ()
{
    for (auto group : m_optgroups)
        group->reload_config();
}
References m_optgroups.
set_config()
void Slic3r::GUI::Page::set_config (DynamicPrintConfig * config_in) inline
{ m_config = config_in; }
References m_config.
set_item_colour()
bool Slic3r::GUI::Page::set_item_colour (const wxColour * clr) inline
{
    if (m_item_color != clr) {
      m_item_color = clr;
      return true;
    }
    return false;
  }
References m_item_color.
set_value()
bool Slic3r::GUI::Page::set_value (const t_config_option_key & opt_key, const boost::any & value)
{
    bool changed = false;
    for(auto optgroup: m_optgroups) {
        if (optgroup->set_value(opt_key, value))
            changed = true ;
    }
    return changed;
}
References m_optgroups.
Referenced by Slic3r::GUI::TabPrinter::activate_selected_page(), and Slic3r::GUI::TabPrinter::reload_config().
sys_color_changed()
void Slic3r::GUI::Page::sys_color_changed ()
{
    for (auto group : m_optgroups)
        group->sys_color_changed();
}
References m_optgroups.
title()
const wxString & Slic3r::GUI::Page::title () const inline
{ return m_title; }
References m_title.
Referenced by Slic3r::GUI::TabPrinter::activate_selected_page(), get_optgroup(), new_optgroup(), Slic3r::GUI::TabPrinter::reload_config(), Slic3r::GUI::TabFilament::toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::Tab::update_description_lines(), Slic3r::GUI::TabFilament::update_description_lines(), Slic3r::GUI::TabFilament::update_filament_overrides_page(), and Slic3r::GUI::Tab::validate_custom_gcodes().
update_visibility()
void Slic3r::GUI::Page::update_visibility (ConfigOptionMode mode, bool update_contolls_visibility)
{
    bool ret_val = false;
#if HIDE_FIRST_SPLIT_LINE
    // BBS: no line spliter for first group
    bool first = true;
#endif
    for (auto group : m_optgroups) {
        ret_val = (update_contolls_visibility     ?
                   group->update_visibility(mode) :  // update visibility for all controlls in group
                   group->is_visible(mode)           // just detect visibility for the group
                   ) || ret_val;
#if HIDE_FIRST_SPLIT_LINE
        // BBS: no line spliter for first group
        if (update_contolls_visibility && ret_val && first) {
            if (group->stb) group->stb->Hide();
            first = false;
        }
#endif
    }
    m_show = ret_val;
#ifdef __WXMSW__
    if (!m_show) return;
    // BBS: fix field control position
    wxTheApp->CallAfter([this]() {
        for (auto group : m_optgroups) {
            if (group->custom_ctrl) group->custom_ctrl->fixup_items_positions();
        }
    });
#endif
}
References m_optgroups, and m_show.
Referenced by Slic3r::GUI::Tab::activate_selected_page(), and Slic3r::GUI::TabPrintModel::update_model_config().
vsizer()
wxBoxSizer * Slic3r::GUI::Page::vsizer () const inline
{ return m_vsizer; }
References m_vsizer.
Member Data Documentation
m_config
DynamicPrintConfig* Slic3r::GUI::Page::m_config
Referenced by new_optgroup(), and set_config().
m_iconID
size_t Slic3r::GUI::Page::m_iconID private
Referenced by iconID().
m_is_modified_values
bool Slic3r::GUI::Page::m_is_modified_values { false }
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::update_current_page_in_background().
m_is_nonsys_values
bool Slic3r::GUI::Page::m_is_nonsys_values { true }
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::update_current_page_in_background().
m_item_color
const wxColour* Slic3r::GUI::Page::m_item_color protected
Referenced by Page(), get_item_colour(), and set_item_colour().
m_optgroups
std::vector<ConfigOptionsGroupShp> Slic3r::GUI::Page::m_optgroups
Referenced by activate(), clear(), get_field(), get_line(), get_optgroup(), msw_rescale(), new_optgroup(), refresh(), reload_config(), set_value(), sys_color_changed(), Slic3r::GUI::TabFilament::update_filament_overrides_page(), update_visibility(), and Slic3r::GUI::Tab::validate_custom_gcodes().
m_option_label_at_right
bool Slic3r::GUI::Page::m_option_label_at_right = false
Referenced by new_optgroup().
m_page_title
wxStaticText* Slic3r::GUI::Page::m_page_title private
Referenced by Page(), activate(), and clear().
m_parent
wxWindow* Slic3r::GUI::Page::m_parent private
Referenced by activate(), new_optgroup(), and parent().
m_show
bool Slic3r::GUI::Page::m_show = true private
Referenced by get_show(), and update_visibility().
m_split_multi_line
bool Slic3r::GUI::Page::m_split_multi_line = false
Referenced by new_optgroup().
m_tab_owner
wxPanel* Slic3r::GUI::Page::m_tab_owner private
Referenced by new_optgroup().
m_title
wxString Slic3r::GUI::Page::m_title private
Referenced by activate(), new_optgroup(), and title().
m_vsizer
wxBoxSizer* Slic3r::GUI::Page::m_vsizer private
Referenced by Page(), activate(), and vsizer().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Tab.hpp
src/slic3r/GUI/Tab.cpp