OrcaSlicer: src/mcut/include/mcut/internal/tpool.h File Reference
tpool.h File Reference
#include <algorithm>
#include <atomic>
#include <condition_variable>
#include <future>
#include <memory>
#include <mutex>
#include <thread>
#include <vector>
#include <stack>
#include <functional>
#include <list>
#include <utility>
#include "mcut/internal/utils.h"
Classes
class function_wrapper
struct function_wrapper::impl_base
struct function_wrapper::impl_type< F >
class thread_safe_queue< T >
struct thread_safe_queue< T >::node
class join_threads
class thread_pool
class barrier_t
class threadsafe_list< T >
struct threadsafe_list< T >::node
struct empty_stack
class threadsafe_stack< T >
Functions
static void get_scheduling_parameters (uint32_t &num_threads, uint32_t &max_threads, uint32_t &block_size, const uint32_t length, const uint32_t available_threads, const uint32_t min_per_thread=(1<< 10))
template<typename InputStorageIteratorType , typename OutputStorageType , typename FunctionType >
void parallel_for (thread_pool &pool, const InputStorageIteratorType &first, const InputStorageIteratorType &last, FunctionType &task_func, OutputStorageType &master_thread_output, std::vector< std::future< OutputStorageType > > &futures, const uint32_t min_per_thread=(1<< 10))
template<typename InputStorageIteratorType , typename FunctionType >
void parallel_for (thread_pool &pool, const InputStorageIteratorType &first, const InputStorageIteratorType &last, FunctionType &task_func, const uint32_t min_per_thread=(1<< 10))
template<typename Iterator >
void partial_sum (Iterator first, Iterator last, Iterator d_first)
template<typename Iterator >
void parallel_partial_sum (thread_pool &pool, Iterator first, Iterator last)
template<typename Iterator , typename MatchType >
void find_element (Iterator begin, Iterator end, MatchType match, std::promise< Iterator > *result, std::atomic< bool > *done_flag)
template<typename Iterator , typename MatchType >
Iterator parallel_find (thread_pool &pool, Iterator first, Iterator last, MatchType match)
template<typename Iterator , typename KeyType >
void find_map_element_by_key (Iterator begin, Iterator end, KeyType match, std::promise< Iterator > *result, std::atomic< bool > *done_flag, barrier_t *barrier_ptr)
template<typename Iterator , typename KeyType >
Iterator parallel_find_in_map_by_key (thread_pool &pool, Iterator first, Iterator last, KeyType match)
template<typename Iterator , typename UnaryPredicate >
void find_element_with_pred (Iterator begin, Iterator end, UnaryPredicate pred, std::promise< Iterator > *result, std::atomic< bool > *done_flag, barrier_t *barrier_ptr)
template<typename Iterator , class UnaryPredicate >
Iterator parallel_find_if (thread_pool &pool, Iterator first, Iterator last, UnaryPredicate predicate)
Class Documentation
thread_safe_queue::node
struct thread_safe_queue::node
template<typename T>
struct thread_safe_queue< T >::node
Class Members
shared_ptr< T > data
unique_ptr< node > next
Function Documentation
find_element()
template<typename Iterator , typename MatchType > void find_element (Iterator begin, Iterator end, MatchType match, std::promise< Iterator > * result, std::atomic< bool > * done_flag)
{
    try {
        for (; (begin != end) && !done_flag->load(); ++begin) {
            if (*begin == match) {
                result->set_value(begin);
                done_flag->store(true);
                return;
            }
        }
    } catch (...) {
        try {
            result->set_exception(std::current_exception());
            done_flag->store(true);
        } catch (...) {
        }
    }
}
References end.
find_element_with_pred()
template<typename Iterator , typename UnaryPredicate > void find_element_with_pred (Iterator begin, Iterator end, UnaryPredicate pred, std::promise< Iterator > * result, std::atomic< bool > * done_flag, barrier_t * barrier_ptr)
{
    try {
        for (; (begin != end) && !done_flag->load(); ++begin) {
            const bool found = pred(*begin);
            if (found) {
                result->set_value(begin);
                done_flag->store(true);
                break; // return;
            }
        }
    } catch (...) {
        try {
            result->set_exception(std::current_exception());
            done_flag->store(true);
        } catch (...) {
        }
    }
    barrier_ptr->wait();
}
References end, and barrier_t::wait().
find_map_element_by_key()
template<typename Iterator , typename KeyType > void find_map_element_by_key (Iterator begin, Iterator end, KeyType match, std::promise< Iterator > * result, std::atomic< bool > * done_flag, barrier_t * barrier_ptr)
{
    try {
        for (; (begin != end) && !done_flag->load(); ++begin) {
            if (begin->first == match) {
                result->set_value(begin);
                done_flag->store(true);
                break; // return;
            }
        }
    } catch (...) {
        try {
            result->set_exception(std::current_exception());
            done_flag->store(true);
        } catch (...) {
        }
    }
    barrier_ptr->wait();
}
References end, and barrier_t::wait().
get_scheduling_parameters()
static void get_scheduling_parameters (uint32_t & num_threads, uint32_t & max_threads, uint32_t & block_size, const uint32_t length, const uint32_t available_threads, const uint32_t min_per_thread = (1 << 10)) static
{
    // maximum possible number of threads that can be scheduled to perform the task.
    max_threads = (length + min_per_thread - 1) / min_per_thread;
    // the number of thread that will actually do some computation (including master)
    num_threads = std::min(available_threads != 0 ? available_threads : 2, max_threads);
    // the size of each block of elements assigned to a thread (note: last thread,
    // which is the master thread might have less)
    block_size = length / num_threads;
    // printf("max_threads=%u num_threads=%u block_size=%u\n", max_threads, num_threads, block_size);
    if (num_threads == 0 || num_threads > available_threads) {
        throw std::runtime_error("invalid number of threads (" + std::to_string(num_threads) + ")");
    }
    if (max_threads == 0) {
        throw std::runtime_error("invalid maximum posible number of threads (" + std::to_string(max_threads) + ")");
    }
    if (block_size == 0) {
        throw std::runtime_error("invalid work block-size per thread (" + std::to_string(block_size) + ")");
    }
}
References length().
Referenced by get_connected_component_data_impl_detail(), parallel_find(), parallel_find_if(), parallel_find_in_map_by_key(), parallel_for(), parallel_for(), and parallel_partial_sum().
parallel_find()
template<typename Iterator , typename MatchType > Iterator parallel_find (thread_pool & pool, Iterator first, Iterator last, MatchType match)
{
    unsigned long const length = std::distance(first, last);
    if (!length)
        return last;
    uint32_t max_threads = 0;
    const uint32_t available_threads = pool.get_num_threads() + 1; // workers and master (+1)
    uint32_t num_threads = 0;
    uint32_t block_size = 0;
    get_scheduling_parameters(
        num_threads,
        max_threads,
        block_size,
        length,
        available_threads);
    std::promise<Iterator> result;
    std::atomic<bool> done_flag(false);
    std::vector<std::future<void>> futures;
    futures.resize(num_threads - 1);
    {
        Iterator block_start = first;
        for (unsigned long i = 0; i < (num_threads - 1); ++i) {
            Iterator block_end = block_start;
            std::advance(block_end, block_size);
            // find_element()" handles all synchronisation
            futures[i] = pool.submit(i,
                [&result, &done_flag, block_start, block_end, &match]() {
                    find_element<Iterator, MatchType>,
                        block_start, block_end, match,
                        &result, &done_flag;
                });
            block_start = block_end;
        }
        find_element<Iterator, MatchType>(block_start, last, match, &result, &done_flag);
    }
    if (!done_flag.load()) {
        return last; // if nothing found (by any thread), return "end"
    }
    return result.get_future().get();
}
References std::distance(), thread_pool::get_num_threads(), get_scheduling_parameters(), length(), and thread_pool::submit().
parallel_find_if()
template<typename Iterator , class UnaryPredicate > Iterator parallel_find_if (thread_pool & pool, Iterator first, Iterator last, UnaryPredicate predicate)
{
    unsigned long const length = std::distance(first, last);
    if (!length)
        return last;
    uint32_t max_threads = 0;
    const uint32_t available_threads = pool.get_num_threads() + 1; // workers and master (+1)
    uint32_t num_threads = 0;
    uint32_t block_size = 0;
    get_scheduling_parameters(
        num_threads,
        max_threads,
        block_size,
        length,
        available_threads);
    barrier_t barrier(num_threads);
    std::promise<Iterator> result;
    std::atomic<bool> done_flag(false);
    std::vector<std::future<void>> futures;
    futures.resize(num_threads - 1);
    Iterator block_start = first;
    for (uint32_t i = 0; i < (num_threads - 1); ++i) {
        Iterator block_end = block_start;
        std::advance(block_end, block_size);
        // barrier handles all synchronisation
        futures[i] = pool.submit(i,
            [&result, &done_flag, block_start, block_end, &predicate, &barrier]() {
                find_element_with_pred<Iterator, UnaryPredicate>(
                    block_start, block_end, predicate,
                    &result, &done_flag, &barrier);
            });
        block_start = block_end;
    }
    find_element_with_pred<Iterator, UnaryPredicate>(block_start, last, predicate, &result, &done_flag, &barrier);
    if (!done_flag.load()) {
        return last; // if nothing found (by any thread), return "end"
    }
    return result.get_future().get();
}
References std::distance(), thread_pool::get_num_threads(), get_scheduling_parameters(), length(), and thread_pool::submit().
Referenced by mesh_is_closed().
parallel_find_in_map_by_key()
template<typename Iterator , typename KeyType > Iterator parallel_find_in_map_by_key (thread_pool & pool, Iterator first, Iterator last, KeyType match)
{
    unsigned long const length = std::distance(first, last);
    if (!length)
        return last;
    uint32_t max_threads = 0;
    const uint32_t available_threads = pool.get_num_threads() + 1; // workers and master (+1)
    uint32_t num_threads = 0;
    uint32_t block_size = 0;
    get_scheduling_parameters(
        num_threads,
        max_threads,
        block_size,
        length,
        available_threads);
    barrier_t barrier(num_threads);
    std::promise<Iterator> result;
    std::atomic<bool> done_flag(false);
    {
        std::vector<std::future<void>> futures;
        futures.resize(num_threads - 1);
        Iterator block_start = first;
        for (unsigned long i = 0; i < (num_threads - 1); ++i) {
            Iterator block_end = block_start;
            std::advance(block_end, block_size);
            futures[i] = pool.submit(i,
                [&result, &done_flag, block_start, block_end, &match, &barrier]() {
                    find_map_element_by_key<Iterator, KeyType>(
                        block_start, block_end, match,
                        &result, &done_flag, &barrier);
                });
            block_start = block_end;
        }
        find_map_element_by_key<Iterator, KeyType>(block_start, last, match, &result, &done_flag, &barrier);
        for (uint32_t i = 0; i < (uint32_t)futures.size(); ++i) {
            futures[i].wait();
        }
    }
    if (!done_flag.load()) {
        return last; // if nothing found (by any thread), return "end"
    }
    return result.get_future().get();
}
References std::distance(), thread_pool::get_num_threads(), get_scheduling_parameters(), length(), and thread_pool::submit().
parallel_for() [1/2]
template<typename InputStorageIteratorType , typename FunctionType > void parallel_for (thread_pool & pool, const InputStorageIteratorType & first, const InputStorageIteratorType & last, FunctionType & task_func, const uint32_t min_per_thread = (1 << 10))
{
    uint32_t const length_ = std::distance(first, last);
    MCUT_ASSERT(length_ != 0);
    uint32_t block_size;
    uint32_t max_threads = 0;
    const uint32_t available_threads = pool.get_num_threads() + 1; // workers and master (+1)
    uint32_t num_threads = 0;
    get_scheduling_parameters(
        num_threads,
        max_threads,
        block_size,
        length_,
        available_threads,
        min_per_thread);
    std::vector<std::future<void>> futures;
    futures.resize(num_threads - 1);
    InputStorageIteratorType block_start = first;
    for (uint32_t i = 0; i < (num_threads - 1); ++i) {
        InputStorageIteratorType block_end = block_start;
        std::advance(block_end, block_size);
        futures[i] = pool.submit(i,
            [&, block_start, block_end]() {
                task_func(block_start, block_end);
            });
        block_start = block_end;
    }
    task_func(block_start, last); // master thread work
    for (uint32_t i = 0; i < (uint32_t)futures.size(); ++i) {
        futures[i].wait();
    }
}
References std::distance(), thread_pool::get_num_threads(), get_scheduling_parameters(), MCUT_ASSERT, and thread_pool::submit().
parallel_for() [2/2]
template<typename InputStorageIteratorType , typename OutputStorageType , typename FunctionType > void parallel_for (thread_pool & pool, const InputStorageIteratorType & first, const InputStorageIteratorType & last, FunctionType & task_func, OutputStorageType & master_thread_output, std::vector< std::future< OutputStorageType > > & futures, const uint32_t min_per_thread = (1 << 10))
{
    uint32_t const length_ = std::distance(first, last);
    MCUT_ASSERT(length_ != 0);
    uint32_t block_size = 0;
    uint32_t max_threads = 0;
    const uint32_t available_threads = pool.get_num_threads() + 1; // workers and master (+1)
    uint32_t num_threads = 0;
    get_scheduling_parameters(
        num_threads,
        max_threads,
        block_size,
        length_,
        available_threads,
        min_per_thread);
    futures.resize(num_threads - 1);
    InputStorageIteratorType block_start = first;
    for (uint32_t i = 0; i < (num_threads - 1); ++i) {
        InputStorageIteratorType block_end = block_start;
        std::advance(block_end, block_size);
        futures[i] = pool.submit(i,
            [&, block_start, block_end]() -> OutputStorageType {
                return task_func(block_start, block_end);
            });
        block_start = block_end;
    }
    master_thread_output = task_func(block_start, last);
}
References std::distance(), thread_pool::get_num_threads(), get_scheduling_parameters(), MCUT_ASSERT, and thread_pool::submit().
Referenced by igl::ambient_occlusion(), client_input_arrays_to_hmesh(), dispatch(), igl::doublearea(), extract_connected_components(), find_connected_components(), get_connected_component_data_impl_detail(), igl::internal_angles_using_edge_lengths(), igl::internal_angles_using_squared_edge_lengths(), igl::parallel_for(), preproc(), igl::shape_diameter_function(), igl::signed_distance(), igl::sort3(), igl::squared_edge_lengths(), and igl::unique_simplices().
parallel_partial_sum()
template<typename Iterator > void parallel_partial_sum (thread_pool & pool, Iterator first, Iterator last)
{
    typedef typename Iterator::value_type value_type;
    struct process_chunk {
        void operator()(Iterator begin, Iterator last,
            std::future<value_type>* previous_end_value,
            std::promise<value_type>* end_value)
        {
            try {
                Iterator end = last;
                ++end;
                partial_sum(begin, end, begin);
                if (previous_end_value) {
                    const value_type addend = previous_end_value->get();
                    *last += addend;
                    if (end_value) {
                        end_value->set_value(*last);
                    }
                    std::for_each(begin, last, [addend](value_type& item) {
                        item += addend;
                    });
                } else if (end_value) {
                    end_value->set_value(*last);
                }
            } catch (...) {
                if (end_value) {
                    end_value->set_exception(std::current_exception());
                } else {
                    throw;
                }
            }
        }
    };
    // number of elements in range
    unsigned long const length = std::distance(first, last);
    if (!length)
        return;
    uint32_t max_threads = 0;
    const uint32_t available_threads = pool.get_num_threads() + 1; // workers and master (+1)
    uint32_t num_threads = 0;
    uint32_t block_size = 0;
    get_scheduling_parameters(
        num_threads,
        max_threads,
        block_size,
        length,
        available_threads);
    typedef typename Iterator::value_type value_type;
    // promises holding the value of the last element of a block. Only the
    // first N-1 blocks (i.e. threads) will have to update this value.
    std::vector<std::promise<value_type>> end_values(num_threads - 1);
    // futures that are used to wait for the end value (the last element) of
    // previous block. Only the last N-1 blocks (i.e. threads) will have to wait
    // on this value. That is, the first thread has no "previous" block to wait
    // on,
    std::vector<std::future<value_type>> previous_end_values;
    previous_end_values.reserve(num_threads - 1);
    std::vector<std::future<void>> futures;
    futures.resize(num_threads - 1);
    Iterator block_start = first;
    // for each pool-thread
    for (unsigned long i = 0; i < (num_threads - 1); ++i) {
        Iterator block_last = block_start;
        std::advance(block_last, block_size - 1);
        // process_chunk()" handles all synchronisation
        futures[i] = pool.submit(i,
            [i /*NOTE: capture by-value*/, &previous_end_values, &end_values, block_start, block_last]() {
                process_chunk()(block_start, block_last, (i != 0) ? &previous_end_values[i - 1] : 0, &end_values[i]);
            });
        block_start = block_last;
        ++block_start;
        previous_end_values.push_back(end_values[i].get_future()); // for next thread to wait on
    }
    Iterator final_element = block_start;
    std::advance(final_element, std::distance(block_start, last) - 1);
    // NOTE: this is a blocking call since the master thread has to wait
    // for worker-threads assigned to preceeding chunks to finish before it can
    // process its own chunk.
    process_chunk()(block_start, final_element,
        (num_threads > 1) ? &previous_end_values.back() : 0,
        0);
}
References std::distance(), end, thread_pool::get_num_threads(), get_scheduling_parameters(), length(), partial_sum(), and thread_pool::submit().
Referenced by client_input_arrays_to_hmesh(), and get_connected_component_data_impl_detail().
partial_sum()
template<typename Iterator > void partial_sum (Iterator first, Iterator last, Iterator d_first)
{
    // std::vector<uint32_t>::iterator first = cc_uptr->face_sizes_cache.begin();
    // std::vector<uint32_t>::iterator last = cc_uptr->face_sizes_cache.end();
    // Iterator d_first = first;
    if (first != last) {
        uint32_t sum = *first;
        *d_first = sum;
        while (++first != last) {
            sum = sum + *first;
            *++d_first = sum;
        }
        ++d_first;
    }
}
Referenced by parallel_partial_sum().