OrcaSlicer: orgQhull::Qhull Class Reference
orgQhull::Qhull Class Reference
Interface to Qhull from C++.
#include <src/qhull/src/libqhullcpp/Qhull.h>
Public Member Functions
GetSet
void checkIfQhullInitialized ()
int dimension () const
Dimension of input and result.
void disableOutputStream ()
void enableOutputStream ()
countT facetCount () const
Coordinates feasiblePoint () const
Return feasiblePoint for halfspace intersection If called before runQhull(), then it returns the value from setFeasiblePoint. qh.feasible_string overrides this value if it is defined.
int hullDimension () const
Dimension of the computed hull.
bool hasOutputStream () const
bool initialized () const
const char * inputComment () const
QhullPoint inputOrigin ()
Return origin point for qh.input_dim.
QhullPoint origin ()
non-const due to QhullPoint
QhullQh * qh () const
const char * qhullCommand () const
const char * rboxCommand () const
int rotateRandom () const
Return QRn for repeating QR0 runs.
void setFeasiblePoint (const Coordinates &c)
Sets qh.feasible_point via initializeFeasiblePoint.
countT vertexCount () const
Delegated to QhullQh
double angleEpsilon () const
Epsilon for hyperplane angle equality.
void appendQhullMessage (const std::string &s)
void clearQhullMessage ()
double distanceEpsilon () const
Epsilon for distance to hyperplane.
double factorEpsilon () const
Factor for angleEpsilon and distanceEpsilon.
std::string qhullMessage () const
bool hasQhullMessage () const
int qhullStatus () const
void setErrorStream (std::ostream *os)
void setFactorEpsilon (double a)
void setOutputStream (std::ostream *os)
ForEach
QhullFacet beginFacet () const
QhullVertex beginVertex () const
void defineVertexNeighborFacets ()
Automatically called if merging facets or Voronoi diagram.
QhullFacet endFacet () const
QhullVertex endVertex () const
QhullFacetList facetList () const
QhullFacet firstFacet () const
QhullVertex firstVertex () const
QhullPoints points () const
QhullPointSet otherPoints () const
coordT * pointCoordinateBegin () const
Same as points().coordinates()
coordT * pointCoordinateEnd () const
QhullVertexList vertexList () const
Return vertices of the convex hull.
Methods
double area ()
void outputQhull ()
void outputQhull (const char *outputflags)
void runQhull (const RboxPoints &rboxPoints, const char *qhullCommand2)
For qhull commands, see http://www.qhull.org/html/qhull.htm or html/qhull.htm.
void runQhull (const char *inputComment2, int pointDimension, int pointCount, const realT *pointCoordinates, const char *qhullCommand2)
pointCoordinates is a array of points, input sites ('d' or 'v'), or halfspaces with offset last ('H') Derived from qh_new_qhull [user.c] For rbox commands, see http://www.qhull.org/html/rbox.htm or html/rbox.htm For qhull commands, see http://www.qhull.org/html/qhull.htm or html/qhull.htm
double volume ()
Private Member Functions
Helpers
void initializeFeasiblePoint (int hulldim)
initialize qh.feasible_point for half-space intersection Sets from qh.feasible_string if available, otherwise from Qhull::feasible_point called only once from runQhull(), otherwise it leaks memory (the same as qh_setFeasible)
Private Attributes
Members and friends
QhullQh * qh_qh
Coordinates origin_point
qhT for this instance
bool run_called
origin for qh_qh->hull_dim. Set by runQhull()
Coordinates feasible_point
True at start of runQhull. Errors if call again.
Constructors
feasible point for half-space intersection (alternative to qh.feasible_string for qh.feasible_point)
Qhull ()
call runQhull() next
Qhull (const RboxPoints &rboxPoints, const char *qhullCommand2)
Invokes Qhull on rboxPoints Same as runQhull() For rbox commands, see http://www.qhull.org/html/rbox.htm or html/rbox.htm For qhull commands, see http://www.qhull.org/html/qhull.htm or html/qhull.htm.
Qhull (const char *inputComment2, int pointDimension, int pointCount, const realT *pointCoordinates, const char *qhullCommand2)
Invokes Qhull on a set of input points Same as runQhull() For qhull commands, see http://www.qhull.org/html/qhull.htm or html/qhull.htm.
~Qhull () throw ()
Qhull (const Qhull &)
Disable copy constructor and assignment. Qhull owns QhullQh.
Qhull & operator= (const Qhull &)
void allocateQhullQh ()
Detailed Description
Interface to Qhull from C++.
Constructor & Destructor Documentation
Qhull() [1/4]
orgQhull::Qhull::Qhull ()
call runQhull() next
: qh_qh(0)
, origin_point()
, run_called(false)
, feasible_point()
{
    allocateQhullQh();
}//Qhull
References allocateQhullQh().
Qhull() [2/4]
orgQhull::Qhull::Qhull (const RboxPoints & rboxPoints, const char * qhullCommand2)
Invokes Qhull on rboxPoints Same as runQhull() For rbox commands, see http://www.qhull.org/html/rbox.htm or html/rbox.htm For qhull commands, see http://www.qhull.org/html/qhull.htm or html/qhull.htm.
: qh_qh(0)
, origin_point()
, run_called(false)
, feasible_point()
{
    allocateQhullQh();
    runQhull(rboxPoints, qhullCommand2);
}//Qhull rbox
References allocateQhullQh(), and runQhull().
Qhull() [3/4]
orgQhull::Qhull::Qhull (const char * inputComment2, int pointDimension, int pointCount, const realT * pointCoordinates, const char * qhullCommand2)
Invokes Qhull on a set of input points Same as runQhull() For qhull commands, see http://www.qhull.org/html/qhull.htm or html/qhull.htm.
: qh_qh(0)
, origin_point()
, run_called(false)
, feasible_point()
{
    allocateQhullQh();
    runQhull(inputComment2, pointDimension, pointCount, pointCoordinates, qhullCommand2);
}//Qhull points
References allocateQhullQh(), and runQhull().
~Qhull()
orgQhull::Qhull::~Qhull () throw ()
{
    // Except for cerr, does not throw errors
    if(qh_qh->hasQhullMessage()){
        cerr<< "\nQhull output at end\n"; //FIXUP QH11005: where should error and log messages go on ~Qhull?
        cerr<< qh_qh->qhullMessage();
        qh_qh->clearQhullMessage();
    }
    delete qh_qh;
    qh_qh= 0;
}//~Qhull
References orgQhull::QhullQh::clearQhullMessage(), orgQhull::QhullQh::hasQhullMessage(), qh_qh, and orgQhull::QhullQh::qhullMessage().
Qhull() [4/4]
orgQhull::Qhull::Qhull (const Qhull &) private
Disable copy constructor and assignment. Qhull owns QhullQh.
Member Function Documentation
allocateQhullQh()
void orgQhull::Qhull::allocateQhullQh () private
{
  QHULL_LIB_CHECK /* Check for compatible library */
    qh_qh= new QhullQh;
    void *p= qh_qh;
    void *p2= static_cast<qhT *>(qh_qh);
    char *s= static_cast<char *>(p);
    char *s2= static_cast<char *>(p2);
    if(s!=s2){
        throw QhullError(10074, "Qhull error: QhullQh at a different address than base type QhT (%d bytes).  Please report compiler to qhull.org", int(s2-s));
    }
}//allocateQhullQh
References qh_qh, and QHULL_LIB_CHECK.
Referenced by Qhull(), Qhull(), and Qhull().
angleEpsilon()
double orgQhull::Qhull::angleEpsilon () const inline
Epsilon for hyperplane angle equality.
References orgQhull::QhullQh::angleEpsilon(), and qh_qh.
appendQhullMessage()
void orgQhull::Qhull::appendQhullMessage (const std::string & s) inline
{ qh_qh->appendQhullMessage(s); }
References orgQhull::QhullQh::appendQhullMessage(), and qh_qh.
Referenced by orgQhull::Qhull_test::t_message().
area()
double orgQhull::Qhull::area ()
      {
    checkIfQhullInitialized();
    if(!qh_qh->hasAreaVolume){
        QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
            qh_getarea(qh_qh, qh_qh->facet_list);
        }
        qh_qh->NOerrexit= true;
        qh_qh->maybeThrowQhullMessage(QH_TRY_status);
    }
    return qh_qh->totarea;
}//area
References checkIfQhullInitialized(), qhT::facet_list, qhT::hasAreaVolume, orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, qh_getarea(), qh_qh, QH_TRY_, and qhT::totarea.
Referenced by orgQhull::Qhull_test::t_construct(), and orgQhull::Qhull_test::t_getValue().
beginFacet()
QhullFacet orgQhull::Qhull::beginFacet () const inline
{ return QhullFacet(qh_qh, qh_qh->facet_list); }
References qhT::facet_list, and qh_qh.
Referenced by facetList(), firstFacet(), orgQhull::QhullSet_test::t_const_iterator(), orgQhull::QhullFacetList_test::t_construct_q(), orgQhull::QhullFacetList_test::t_construct_qh(), orgQhull::QhullFacet_test::t_constructConvert(), orgQhull::QhullSet_test::t_convert(), orgQhull::QhullSet_test::t_element(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullFacetList_test::t_foreach(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullFacet_test::t_io(), orgQhull::QhullSet_test::t_io(), orgQhull::QhullSet_test::t_iterator(), orgQhull::QhullSet_test::t_qhullset_iterator(), orgQhull::QhullSet_test::t_qhullsetbase(), and orgQhull::QhullSet_test::t_search().
beginVertex()
QhullVertex orgQhull::Qhull::beginVertex () const inline
{ return QhullVertex(qh_qh, qh_qh->vertex_list); }
References qh_qh, and qhT::vertex_list.
Referenced by firstVertex(), orgQhull::QhullLinkedList_test::t_construct(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullVertex_test::t_constructConvert(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullPoint_test::t_io(), orgQhull::QhullVertex_test::t_io(), and vertexList().
checkIfQhullInitialized()
void orgQhull::Qhull::checkIfQhullInitialized ()
{
    if(!initialized()){ // qh_initqhull_buffers() not called
        throw QhullError(10023, "Qhull error: checkIfQhullInitialized failed.  Call runQhull() first.");
    }
}//checkIfQhullInitialized
References initialized().
Referenced by area(), defineVertexNeighborFacets(), outputQhull(), outputQhull(), and volume().
clearQhullMessage()
void orgQhull::Qhull::clearQhullMessage () inline
{ qh_qh->clearQhullMessage(); }
References orgQhull::QhullQh::clearQhullMessage(), and qh_qh.
Referenced by orgQhull::Qhull_test::t_message(), and user_eg3().
defineVertexNeighborFacets()
void orgQhull::Qhull::defineVertexNeighborFacets ()
Automatically called if merging facets or Voronoi diagram.
Define QhullVertex::neighborFacets(). Automatically called if merging facets or computing the Voronoi diagram. Noop if called multiple times.
{
    checkIfQhullInitialized();
    if(!qh_qh->hasAreaVolume){
        QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
            qh_vertexneighbors(qh_qh);
        }
        qh_qh->NOerrexit= true;
        qh_qh->maybeThrowQhullMessage(QH_TRY_status);
    }
}//defineVertexNeighborFacets
References checkIfQhullInitialized(), qhT::hasAreaVolume, orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, qh_qh, QH_TRY_, and qh_vertexneighbors().
Referenced by orgQhull::QhullVertex_test::t_io().
dimension()
int orgQhull::Qhull::dimension () const inline
Dimension of input and result.
References qhT::input_dim, and qh_qh.
Referenced by orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::Qhull_test::t_construct(), orgQhull::Qhull_test::t_getSet(), and orgQhull::QhullPointSet_test::t_iterator().
disableOutputStream()
void orgQhull::Qhull::disableOutputStream () inline
{ qh_qh->disableOutputStream(); }
References orgQhull::QhullQh::disableOutputStream(), and qh_qh.
Referenced by Slic3r::its_convex_hull().
distanceEpsilon()
double orgQhull::Qhull::distanceEpsilon () const inline
Epsilon for distance to hyperplane.
References orgQhull::QhullQh::distanceEpsilon(), and qh_qh.
Referenced by orgQhull::QhullFacet_test::t_getSet().
enableOutputStream()
void orgQhull::Qhull::enableOutputStream () inline
{ qh_qh->enableOutputStream(); }
References orgQhull::QhullQh::enableOutputStream(), and qh_qh.
endFacet()
QhullFacet orgQhull::Qhull::endFacet () const inline
{ return QhullFacet(qh_qh, qh_qh->facet_tail); }
References qhT::facet_tail, and qh_qh.
Referenced by facetList(), orgQhull::QhullFacetList_test::t_construct_q(), orgQhull::QhullFacetList_test::t_construct_qh(), orgQhull::Qhull_test::t_foreach(), and orgQhull::QhullFacetList_test::t_foreach().
endVertex()
QhullVertex orgQhull::Qhull::endVertex () const inline
{ return QhullVertex(qh_qh, qh_qh->vertex_tail); }
References qh_qh, and qhT::vertex_tail.
Referenced by orgQhull::QhullLinkedList_test::t_construct(), orgQhull::QhullLinkedList_test::t_convert(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullLinkedList_test::t_io(), orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator(), and vertexList().
facetCount()
countT orgQhull::Qhull::facetCount () const inline
{ return qh_qh->num_facets; }
References qhT::num_facets, and qh_qh.
Referenced by orgQhull::Qhull_test::t_construct(), orgQhull::QhullLinkedList_test::t_construct(), orgQhull::QhullLinkedList_test::t_convert(), orgQhull::QhullSet_test::t_convert(), orgQhull::Qhull_test::t_foreach(), orgQhull::Qhull_test::t_getQh(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullRidge_test::t_getSet(), orgQhull::QhullVertex_test::t_getSet(), and orgQhull::QhullSet_test::t_qhullsetbase().
facetList()
QhullFacetList orgQhull::Qhull::facetList () const
                 {
    return QhullFacetList(beginFacet(), endFacet());
}//facetList
References beginFacet(), and endFacet().
Referenced by Slic3r::its_convex_hull(), orgQhull::Qhull_test::t_attribute(), orgQhull::QhullPointSet_test::t_construct(), orgQhull::QhullFacetList_test::t_construct_q(), orgQhull::QhullFacetList_test::t_construct_qh(), orgQhull::QhullFacetList_test::t_convert(), orgQhull::QhullHyperplane_test::t_define(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullFacet_test::t_foreach(), orgQhull::QhullFacetList_test::t_foreach(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullFacetList_test::t_io(), orgQhull::QhullFacetList_test::t_readonly(), orgQhull::QhullHyperplane_test::t_readonly(), orgQhull::QhullFacet_test::t_value(), and user_eg3().
factorEpsilon()
double orgQhull::Qhull::factorEpsilon () const inline
Factor for angleEpsilon and distanceEpsilon.
References orgQhull::QhullQh::factorEpsilon(), and qh_qh.
Referenced by orgQhull::QhullFacet_test::t_getSet().
feasiblePoint()
Coordinates orgQhull::Qhull::feasiblePoint () const
Return feasiblePoint for halfspace intersection If called before runQhull(), then it returns the value from setFeasiblePoint. qh.feasible_string overrides this value if it is defined.
{
    Coordinates result;
    if(qh_qh->feasible_point){
        result.append(qh_qh->hull_dim, qh_qh->feasible_point);
    }else{
        result= feasible_point;
    }
    return result;
}//feasiblePoint
References orgQhull::Coordinates::append(), qhT::feasible_point, feasible_point, qhT::hull_dim, and qh_qh.
Referenced by orgQhull::Qhull_test::t_attribute().
firstFacet()
QhullFacet orgQhull::Qhull::firstFacet () const inline
{ return beginFacet(); }
References beginFacet().
Referenced by orgQhull::QhullHyperplane_test::t_const_iterator(), orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::QhullFacetSet_test::t_construct(), orgQhull::QhullHyperplane_test::t_construct(), orgQhull::QhullRidge_test::t_construct(), orgQhull::QhullVertexSet_test::t_construct(), orgQhull::QhullHyperplane_test::t_construct_qh(), orgQhull::QhullFacetSet_test::t_convert(), orgQhull::QhullHyperplane_test::t_convert(), orgQhull::QhullPointSet_test::t_convert(), orgQhull::QhullSet_test::t_convert(), orgQhull::QhullVertexSet_test::t_convert(), orgQhull::QhullPointSet_test::t_element(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullFacetList_test::t_foreach(), orgQhull::QhullFacetSet_test::t_foreach(), orgQhull::QhullRidge_test::t_foreach(), orgQhull::QhullVertexSet_test::t_foreach(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullRidge_test::t_getSet(), orgQhull::QhullFacetSet_test::t_io(), orgQhull::QhullHyperplane_test::t_io(), orgQhull::QhullPointSet_test::t_io(), orgQhull::QhullRidge_test::t_io(), orgQhull::QhullVertex_test::t_io(), orgQhull::QhullVertexSet_test::t_io(), orgQhull::QhullHyperplane_test::t_iterator(), orgQhull::QhullPointSet_test::t_iterator(), orgQhull::QhullHyperplane_test::t_operator(), orgQhull::QhullPointSet_test::t_pointset_iterator(), orgQhull::QhullHyperplane_test::t_qhullHyperplane_iterator(), orgQhull::QhullFacetList_test::t_readonly(), orgQhull::QhullFacetSet_test::t_readonly(), orgQhull::QhullVertexSet_test::t_readonly(), orgQhull::QhullPointSet_test::t_search(), and orgQhull::QhullHyperplane_test::t_value().
firstVertex()
QhullVertex orgQhull::Qhull::firstVertex () const inline
{ return beginVertex(); }
References beginVertex().
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), orgQhull::QhullPoint_test::t_convert(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullPoint_test::t_iterator(), orgQhull::QhullPoint_test::t_method(), orgQhull::QhullPoint_test::t_operator(), and orgQhull::QhullPoint_test::t_qhullpoint_iterator().
hasOutputStream()
bool orgQhull::Qhull::hasOutputStream () const inline
{ return qh_qh->hasOutputStream(); }
References orgQhull::QhullQh::hasOutputStream(), and qh_qh.
Referenced by user_eg3().
hasQhullMessage()
bool orgQhull::Qhull::hasQhullMessage () const inline
{ return qh_qh->hasQhullMessage(); }
References orgQhull::QhullQh::hasQhullMessage(), and qh_qh.
Referenced by orgQhull::Qhull_test::t_message(), and user_eg3().
hullDimension()
int orgQhull::Qhull::hullDimension () const inline
Dimension of the computed hull.
References qhT::hull_dim, and qh_qh.
Referenced by orgQhull::QhullPoint::QhullPoint(), and orgQhull::QhullPoints::QhullPoints().
initialized()
bool orgQhull::Qhull::initialized () const inline
{ return (qh_qh->hull_dim>0); }
References qhT::hull_dim, and qh_qh.
Referenced by checkIfQhullInitialized(), origin(), and orgQhull::Qhull_test::t_getSet().
initializeFeasiblePoint()
void orgQhull::Qhull::initializeFeasiblePoint (int hulldim) private
initialize qh.feasible_point for half-space intersection Sets from qh.feasible_string if available, otherwise from Qhull::feasible_point called only once from runQhull(), otherwise it leaks memory (the same as qh_setFeasible)
{
    if(qh_qh->feasible_string){
        qh_setfeasible(qh_qh, hulldim);
    }else{
        if(feasible_point.isEmpty()){
            qh_fprintf(qh_qh, qh_qh->ferr, 6209, "qhull error: missing feasible point for halfspace intersection.  Use option 'Hn,n' or Qhull::setFeasiblePoint before runQhull()\n");
            qh_errexit(qh_qh, qh_ERRmem, NULL, NULL);
        }
        if(feasible_point.size()!=(size_t)hulldim){
            qh_fprintf(qh_qh, qh_qh->ferr, 6210, "qhull error: dimension of feasiblePoint should be %d.  It is %u", hulldim, feasible_point.size());
            qh_errexit(qh_qh, qh_ERRmem, NULL, NULL);
        }
        if (!(qh_qh->feasible_point= (coordT*)qh_malloc(hulldim * sizeof(coordT)))) {
            qh_fprintf(qh_qh, qh_qh->ferr, 6202, "qhull error: insufficient memory for feasible point\n");
            qh_errexit(qh_qh, qh_ERRmem, NULL, NULL);
        }
        coordT *t= qh_qh->feasible_point;
        // No qh_... routines after here -- longjmp() ignores destructor
        for(Coordinates::ConstIterator p=feasible_point.begin(); p<feasible_point.end(); p++){
            *t++= *p;
        }
    }
}//initializeFeasiblePoint
References orgQhull::Coordinates::begin(), coordT, orgQhull::Coordinates::end(), qhT::feasible_point, feasible_point, qhT::feasible_string, qhT::ferr, orgQhull::Coordinates::isEmpty(), NULL, qh_errexit(), qh_ERRmem, qh_fprintf(), qh_malloc(), qh_qh, qh_setfeasible(), and orgQhull::Coordinates::size().
Referenced by runQhull().
inputComment()
const char * orgQhull::Qhull::inputComment () const inline
{ return qh_qh->rbox_command; }
References qh_qh, and qhT::rbox_command.
Referenced by runQhull().
inputOrigin()
QhullPoint orgQhull::Qhull::inputOrigin ()
Return origin point for qh.input_dim.
{
    QhullPoint result= origin();
    result.setDimension(qh_qh->input_dim);
    return result;
}//inputOrigin
References qhT::input_dim, origin(), qh_qh, and orgQhull::QhullPoint::setDimension().
Referenced by orgQhull::QhullFacet_test::t_getSet().
operator=()
Qhull & orgQhull::Qhull::operator= (const Qhull &) private
origin()
QhullPoint orgQhull::Qhull::origin () inline
non-const due to QhullPoint
{ QHULL_ASSERT(initialized()); return QhullPoint(qh_qh, origin_point.data()); }
References orgQhull::Coordinates::data(), initialized(), origin_point, qh_qh, and QHULL_ASSERT.
Referenced by inputOrigin(), orgQhull::QhullPoint_test::t_construct(), orgQhull::Qhull_test::t_getSet(), orgQhull::QhullPoint_test::t_method(), orgQhull::QhullFacet_test::t_value(), and orgQhull::QhullHyperplane_test::t_value().
otherPoints()
QhullPointSet orgQhull::Qhull::otherPoints () const
{
    return QhullPointSet(qh_qh, qh_qh->other_points);
}//otherPoints
References qhT::other_points, and qh_qh.
Referenced by orgQhull::Qhull_test::t_foreach().
outputQhull() [1/2]
void orgQhull::Qhull::outputQhull ()
{
    checkIfQhullInitialized();
    QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
        qh_produce_output2(qh_qh);
    }
    qh_qh->NOerrexit= true;
    qh_qh->maybeThrowQhullMessage(QH_TRY_status);
}//outputQhull
References checkIfQhullInitialized(), orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, qh_produce_output2(), qh_qh, and QH_TRY_.
Referenced by orgQhull::Qhull_test::t_attribute(), orgQhull::Qhull_test::t_getSet(), orgQhull::QhullFacet_test::t_io(), orgQhull::Qhull_test::t_modify(), and user_eg3().
outputQhull() [2/2]
void orgQhull::Qhull::outputQhull (const char * outputflags)
{
    checkIfQhullInitialized();
    string cmd(" "); // qh_checkflags skips first word
    cmd += outputflags;
    char *command= const_cast<char*>(cmd.c_str());
    QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
        qh_clear_outputflags(qh_qh);
        char *s = qh_qh->qhull_command + strlen(qh_qh->qhull_command) + 1; //space
        strncat(qh_qh->qhull_command, command, sizeof(qh_qh->qhull_command)-strlen(qh_qh->qhull_command)-1);
        qh_checkflags(qh_qh, command, const_cast<char *>(s_not_output_options));
        qh_initflags(qh_qh, s);
        qh_initqhull_outputflags(qh_qh);
        if(qh_qh->KEEPminArea < REALmax/2
           || (0 != qh_qh->KEEParea + qh_qh->KEEPmerge + qh_qh->GOODvertex
                    + qh_qh->GOODthreshold + qh_qh->GOODpoint + qh_qh->SPLITthresholds)){
            facetT *facet;
            qh_qh->ONLYgood= False;
            FORALLfacet_(qh_qh->facet_list) {
                facet->good= True;
            }
            qh_prepare_output(qh_qh);
        }
        qh_produce_output2(qh_qh);
        if(qh_qh->VERIFYoutput && !qh_qh->STOPpoint && !qh_qh->STOPcone){
            qh_check_points(qh_qh);
        }
    }
    qh_qh->NOerrexit= true;
    qh_qh->maybeThrowQhullMessage(QH_TRY_status);
}//outputQhull
References checkIfQhullInitialized(), qhT::facet_list, False, FORALLfacet_, facetT::good, qhT::GOODpoint, qhT::GOODthreshold, qhT::GOODvertex, qhT::KEEParea, qhT::KEEPmerge, qhT::KEEPminArea, orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, qhT::ONLYgood, qh_check_points(), qh_checkflags(), qh_clear_outputflags(), qh_initflags(), qh_initqhull_outputflags(), qh_prepare_output(), qh_produce_output2(), qh_qh, QH_TRY_, qhT::qhull_command, REALmax, orgQhull::s_not_output_options, qhT::SPLITthresholds, qhT::STOPcone, qhT::STOPpoint, True, and qhT::VERIFYoutput.
pointCoordinateBegin()
coordT * orgQhull::Qhull::pointCoordinateBegin () const inline
Same as points().coordinates()
{ return qh_qh->first_point; }
References qhT::first_point, and qh_qh.
Referenced by orgQhull::Qhull_test::t_foreach().
pointCoordinateEnd()
coordT * orgQhull::Qhull::pointCoordinateEnd () const inline
{ return qh_qh->first_point + qh_qh->num_points*qh_qh->hull_dim; }
References qhT::first_point, qhT::hull_dim, qhT::num_points, and qh_qh.
Referenced by orgQhull::Qhull_test::t_foreach().
points()
QhullPoints orgQhull::Qhull::points () const
{
    return QhullPoints(qh_qh, qh_qh->hull_dim, qh_qh->num_points*qh_qh->hull_dim, qh_qh->first_point);
}//points
References qhT::first_point, qhT::hull_dim, qhT::num_points, and qh_qh.
Referenced by orgQhull::Qhull_test::t_foreach(), and orgQhull::QhullPoints_test::t_io().
qh()
QhullQh * orgQhull::Qhull::qh () const inline
{ return qh_qh; };
References qh_qh.
Referenced by orgQhull::QhullVertexSet::QhullVertexSet(), orgQhull::Qhull_test::t_attribute(), orgQhull::Qhull_test::t_construct(), orgQhull::QhullFacetSet_test::t_construct(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullPointSet_test::t_construct(), orgQhull::QhullVertexSet_test::t_construct(), orgQhull::QhullHyperplane_test::t_construct_qh(), orgQhull::QhullPoints_test::t_construct_qh(), orgQhull::QhullSet_test::t_element(), orgQhull::Qhull_test::t_getQh(), orgQhull::QhullFacet_test::t_io(), orgQhull::QhullSet_test::t_io(), orgQhull::QhullSet_test::t_qhullset_iterator(), orgQhull::QhullSet_test::t_qhullsetbase(), and orgQhull::QhullPoint_test::t_readonly().
qhullCommand()
const char * orgQhull::Qhull::qhullCommand () const inline
{ return qh_qh->qhull_command; }
References qh_qh, and qhT::qhull_command.
Referenced by runQhull(), orgQhull::Qhull_test::t_construct(), and orgQhull::Qhull_test::t_getQh().
qhullMessage()
std::string orgQhull::Qhull::qhullMessage () const inline
{ return qh_qh->qhullMessage(); }
References qh_qh, and orgQhull::QhullQh::qhullMessage().
Referenced by orgQhull::Qhull_test::t_message(), and user_eg3().
qhullStatus()
int orgQhull::Qhull::qhullStatus () const inline
{ return qh_qh->qhullStatus(); }
References qh_qh, and orgQhull::QhullQh::qhullStatus().
Referenced by orgQhull::Qhull_test::t_message().
rboxCommand()
const char * orgQhull::Qhull::rboxCommand () const inline
{ return qh_qh->rbox_command; }
References qh_qh, and qhT::rbox_command.
Referenced by orgQhull::Qhull_test::t_construct(), and orgQhull::Qhull_test::t_getQh().
rotateRandom()
int orgQhull::Qhull::rotateRandom () const inline
Return QRn for repeating QR0 runs.
References qh_qh, and qhT::ROTATErandom.
Referenced by orgQhull::QhullVertexSet_test::t_construct(), orgQhull::QhullVertexSet_test::t_convert(), orgQhull::QhullVertexSet_test::t_foreach(), orgQhull::QhullFacet_test::t_getSet(), and orgQhull::QhullVertexSet_test::t_io().
runQhull() [1/2]
void orgQhull::Qhull::runQhull (const char * inputComment2, int pointDimension, int pointCount, const realT * pointCoordinates, const char * qhullCommand2)
pointCoordinates is a array of points, input sites ('d' or 'v'), or halfspaces with offset last ('H') Derived from qh_new_qhull [user.c] For rbox commands, see http://www.qhull.org/html/rbox.htm or html/rbox.htm For qhull commands, see http://www.qhull.org/html/qhull.htm or html/qhull.htm
{
  /* gcc may issue a "might be clobbered" warning for pointDimension and pointCoordinates [-Wclobbered].
     These parameters are not referenced after a longjmp() and hence not clobbered.
     See http://stackoverflow.com/questions/7721854/what-sense-do-these-clobbered-variable-warnings-make */
    if(run_called){
        throw QhullError(10027, "Qhull error: runQhull called twice.  Only one call allowed.");
    }
    run_called= true;
    string s("qhull ");
    s += qhullCommand;
    char *command= const_cast<char*>(s.c_str());
    /************* Expansion of QH_TRY_ for debugging
    int QH_TRY_status;
    if(qh_qh->NOerrexit){
        qh_qh->NOerrexit= False;
        QH_TRY_status= setjmp(qh_qh->errexit);
    }else{
        QH_TRY_status= QH_TRY_ERROR;
    }
    if(!QH_TRY_status){
    *************/
    QH_TRY_(qh_qh){ // no object creation -- destructors are skipped on longjmp()
        qh_checkflags(qh_qh, command, const_cast<char *>(s_unsupported_options));
        qh_initflags(qh_qh, command);
        *qh_qh->rbox_command= '\0';
        strncat( qh_qh->rbox_command, inputComment, sizeof(qh_qh->rbox_command)-1);
        if(qh_qh->DELAUNAY){
            qh_qh->PROJECTdelaunay= True;   // qh_init_B() calls qh_projectinput()
        }
        pointT *newPoints= const_cast<pointT*>(pointCoordinates);
        int newDimension= pointDimension;
        int newIsMalloc= False;
        if(qh_qh->HALFspace){
            --newDimension;
            initializeFeasiblePoint(newDimension);
            newPoints= qh_sethalfspace_all(qh_qh, pointDimension, pointCount, newPoints, qh_qh->feasible_point);
            newIsMalloc= True;
        }
        qh_init_B(qh_qh, newPoints, pointCount, newDimension, newIsMalloc);
        qh_qhull(qh_qh);
        qh_check_output(qh_qh);
        qh_prepare_output(qh_qh);
        if(qh_qh->VERIFYoutput && !qh_qh->STOPpoint && !qh_qh->STOPcone){
            qh_check_points(qh_qh);
        }
    }
    qh_qh->NOerrexit= true;
    for(int k= qh_qh->hull_dim; k--; ){  // Do not move into QH_TRY block.  It may throw an error
        origin_point << 0.0;
    }
    // BBS: throw up the error to prevent crash
    try {
        qh_qh->maybeThrowQhullMessage(QH_TRY_status);
    }
    catch (QhullError& e) {
        throw e;
    }
}//runQhull
References qhT::DELAUNAY, False, qhT::feasible_point, qhT::HALFspace, qhT::hull_dim, initializeFeasiblePoint(), inputComment(), orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, origin_point, pointT, qhT::PROJECTdelaunay, qh_check_output(), qh_check_points(), qh_checkflags(), qh_init_B(), qh_initflags(), qh_prepare_output(), qh_qh, qh_qhull(), qh_sethalfspace_all(), QH_TRY_, qhullCommand(), qhT::rbox_command, run_called, orgQhull::s_unsupported_options, qhT::STOPcone, qhT::STOPpoint, True, and qhT::VERIFYoutput.
runQhull() [2/2]
void orgQhull::Qhull::runQhull (const RboxPoints & rboxPoints, const char * qhullCommand2)
For qhull commands, see http://www.qhull.org/html/qhull.htm or html/qhull.htm.
{
    runQhull(rboxPoints.comment().c_str(), rboxPoints.dimension(), rboxPoints.count(), &*rboxPoints.coordinates(), qhullCommand2);
}//runQhull, RboxPoints
References orgQhull::PointCoordinates::comment(), orgQhull::QhullPoints::coordinates(), orgQhull::QhullPoints::count(), orgQhull::QhullPoints::dimension(), and runQhull().
Referenced by Qhull(), Qhull(), Slic3r::its_convex_hull(), runQhull(), orgQhull::Qhull_test::t_attribute(), orgQhull::Qhull_test::t_foreach(), orgQhull::Qhull_test::t_getQh(), orgQhull::Qhull_test::t_getSet(), orgQhull::Qhull_test::t_getValue(), orgQhull::Qhull_test::t_message(), and user_eg3().
setErrorStream()
void orgQhull::Qhull::setErrorStream (std::ostream * os) inline
{ qh_qh->setErrorStream(os); }
References qh_qh, and orgQhull::QhullQh::setErrorStream().
Referenced by orgQhull::Qhull_test::t_getSet(), and orgQhull::Qhull_test::t_message().
setFactorEpsilon()
void orgQhull::Qhull::setFactorEpsilon (double a) inline
{ qh_qh->setFactorEpsilon(a); }
References qh_qh, and orgQhull::QhullQh::setFactorEpsilon().
Referenced by orgQhull::QhullFacet_test::t_getSet().
setFeasiblePoint()
void orgQhull::Qhull::setFeasiblePoint (const Coordinates & c) inline
Sets qh.feasible_point via initializeFeasiblePoint.
References feasible_point.
Referenced by orgQhull::Qhull_test::t_attribute().
setOutputStream()
void orgQhull::Qhull::setOutputStream (std::ostream * os) inline
{ qh_qh->setOutputStream(os); }
References qh_qh, and orgQhull::QhullQh::setOutputStream().
Referenced by orgQhull::Qhull_test::t_attribute(), orgQhull::Qhull_test::t_getSet(), orgQhull::Qhull_test::t_message(), orgQhull::Qhull_test::t_modify(), and user_eg3().
vertexCount()
countT orgQhull::Qhull::vertexCount () const inline
{ return qh_qh->num_vertices; }
References qhT::num_vertices, and qh_qh.
Referenced by orgQhull::Qhull_test::t_construct(), orgQhull::Qhull_test::t_foreach(), orgQhull::Qhull_test::t_getQh(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullRidge_test::t_getSet(), and orgQhull::QhullVertex_test::t_getSet().
vertexList()
QhullVertexList orgQhull::Qhull::vertexList () const
Return vertices of the convex hull.
                  {
    return QhullVertexList(beginVertex(), endVertex());
}//vertexList
References beginVertex(), and endVertex().
Referenced by orgQhull::QhullLinkedList_test::t_const_iterator(), orgQhull::QhullLinkedList_test::t_construct(), orgQhull::QhullLinkedList_test::t_convert(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullLinkedList_test::t_element(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullVertex_test::t_foreach(), orgQhull::QhullVertex_test::t_getSet(), orgQhull::QhullLinkedList_test::t_io(), orgQhull::QhullLinkedList_test::t_iterator(), orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator(), orgQhull::QhullPoint_test::t_readonly(), and orgQhull::QhullLinkedList_test::t_search().
volume()
double orgQhull::Qhull::volume ()
        {
    checkIfQhullInitialized();
    if(!qh_qh->hasAreaVolume){
        QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
            qh_getarea(qh_qh, qh_qh->facet_list);
        }
        qh_qh->NOerrexit= true;
        qh_qh->maybeThrowQhullMessage(QH_TRY_status);
    }
    return qh_qh->totvol;
}//volume
References checkIfQhullInitialized(), qhT::facet_list, qhT::hasAreaVolume, orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, qh_getarea(), qh_qh, QH_TRY_, and qhT::totvol.
Referenced by orgQhull::Qhull_test::t_construct(), and orgQhull::Qhull_test::t_getValue().
Member Data Documentation
feasible_point
Coordinates orgQhull::Qhull::feasible_point private
True at start of runQhull. Errors if call again.
Referenced by feasiblePoint(), initializeFeasiblePoint(), and setFeasiblePoint().
origin_point
Coordinates orgQhull::Qhull::origin_point private
qhT for this instance
Referenced by origin(), and runQhull().
qh_qh
QhullQh* orgQhull::Qhull::qh_qh private
Referenced by ~Qhull(), allocateQhullQh(), angleEpsilon(), appendQhullMessage(), area(), beginFacet(), beginVertex(), clearQhullMessage(), defineVertexNeighborFacets(), dimension(), disableOutputStream(), distanceEpsilon(), enableOutputStream(), endFacet(), endVertex(), facetCount(), factorEpsilon(), feasiblePoint(), hasOutputStream(), hasQhullMessage(), hullDimension(), initialized(), initializeFeasiblePoint(), inputComment(), inputOrigin(), origin(), otherPoints(), outputQhull(), outputQhull(), pointCoordinateBegin(), pointCoordinateEnd(), points(), qh(), qhullCommand(), qhullMessage(), qhullStatus(), rboxCommand(), rotateRandom(), runQhull(), setErrorStream(), setFactorEpsilon(), setOutputStream(), vertexCount(), and volume().
run_called
bool orgQhull::Qhull::run_called private
origin for qh_qh->hull_dim. Set by runQhull()
Referenced by runQhull().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/Qhull.h
src/qhull/src/libqhullcpp/Qhull.cpp