OrcaSlicer: WipingDialog Class Reference
WipingDialog Class Reference
#include <src/slic3r/GUI/WipeTowerDialog.hpp>
Public Member Functions
WipingDialog (wxWindow *parent, const std::vector< float > &matrix, const std::vector< float > &extruders, const std::vector< std::string > &extruder_colours, int extra_flush_volume, float flush_multiplier)
std::vector< float > get_matrix () const
std::vector< float > get_extruders () const
wxBoxSizer * create_btn_sizer (long flags)
float get_flush_multiplier ()
Private Attributes
WipingPanel * m_panel_wiping = nullptr
std::vector< float > m_output_matrix
std::vector< float > m_output_extruders
Detailed Description
Constructor & Destructor Documentation
WipingDialog()
WipingDialog::WipingDialog (wxWindow * parent, const std::vector< float > & matrix, const std::vector< float > & extruders, const std::vector< std::string > & extruder_colours, int extra_flush_volume, float flush_multiplier)
: wxDialog(parent, wxID_ANY, _(L("Flushing volumes for filament change")), wxDefaultPosition, wxDefaultSize, wxDEFAULT_DIALOG_STYLE/* | wxRESIZE_BORDER*/)
{
    this->SetBackgroundColour(*wxWHITE);
    this->SetMinSize(wxSize(MIN_WIPING_DIALOG_WIDTH, -1));
    m_panel_wiping = new WipingPanel(this, matrix, extruders, extruder_colours, nullptr, extra_flush_volume, flush_multiplier);
    auto main_sizer = new wxBoxSizer(wxVERTICAL);
    // set min sizer width according to extruders count
    auto sizer_width = (int)((sqrt(matrix.size()) + 2.8)*ITEM_WIDTH());
    sizer_width = sizer_width > MIN_WIPING_DIALOG_WIDTH ? sizer_width : MIN_WIPING_DIALOG_WIDTH;
    main_sizer->SetMinSize(wxSize(sizer_width, -1));
    main_sizer->Add(m_panel_wiping, 1, wxEXPAND | wxALL, 0);
    auto btn_sizer = create_btn_sizer(wxOK | wxCANCEL |wxRESET);
    main_sizer->Add(btn_sizer, 0, wxBOTTOM | wxRIGHT | wxEXPAND, BTN_GAP);
    SetSizer(main_sizer);
    main_sizer->SetSizeHints(this);
    if (this->FindWindowById(wxID_OK, this)) {
        this->FindWindowById(wxID_OK, this)->Bind(wxEVT_BUTTON, [this](wxCommandEvent&) {                 // if OK button is clicked..
            m_output_matrix = m_panel_wiping->read_matrix_values();    // ..query wiping panel and save returned values
            m_output_extruders = m_panel_wiping->read_extruders_values(); // so they can be recovered later by calling get_...()
            EndModal(wxID_OK);
            }, wxID_OK);
    }
    if (this->FindWindowById(wxID_CANCEL, this)) {
        update_ui(static_cast<wxButton*>(this->FindWindowById(wxID_CANCEL, this)));
        this->FindWindowById(wxID_CANCEL, this)->Bind(wxEVT_BUTTON, [this](wxCommandEvent&) { EndModal(wxCANCEL); });
    }
    if (this->FindWindowById(wxID_RESET, this)) {
        this->FindWindowById(wxID_RESET, this)->Bind(wxEVT_BUTTON, [this](wxCommandEvent &) { m_panel_wiping->calc_flushing_volumes(); });
    }
    this->Bind(wxEVT_CLOSE_WINDOW, [this](wxCloseEvent& e) { EndModal(wxCANCEL); });
    this->Bind(wxEVT_CHAR_HOOK, [this](wxKeyEvent& e) {
        if (e.GetKeyCode() == WXK_ESCAPE) {
            if (this->IsModal())
                this->EndModal(wxID_CANCEL);
            else
                this->Close();
        }
        else
            e.Skip();
        });
    wxGetApp().UpdateDlgDarkUI(this);
}
References BTN_GAP, WipingPanel::calc_flushing_volumes(), create_btn_sizer(), int, ITEM_WIDTH(), m_output_extruders, m_output_matrix, m_panel_wiping, MIN_WIPING_DIALOG_WIDTH, WipingPanel::read_extruders_values(), WipingPanel::read_matrix_values(), sqrt(), update_ui(), wxButton, and wxEVT_BUTTON.
Member Function Documentation
create_btn_sizer()
wxBoxSizer * WipingDialog::create_btn_sizer (long flags)
{
    auto btn_sizer = new wxBoxSizer(wxHORIZONTAL);
    btn_sizer->AddStretchSpacer();
    StateColor ok_btn_bg(
        std::pair<wxColour, int>(wxColour(27, 136, 68), StateColor::Pressed),
        std::pair<wxColour, int>(wxColour(61, 203, 115), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal)
    );
    StateColor ok_btn_bd(
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal)
    );
    StateColor ok_btn_text(
        std::pair<wxColour, int>(wxColour(255, 255, 254), StateColor::Normal)
    );
    StateColor cancel_btn_bg(
        std::pair<wxColour, int>(wxColour(206, 206, 206), StateColor::Pressed),
        std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(255, 255, 255), StateColor::Normal)
    );
    StateColor cancel_btn_bd_(
        std::pair<wxColour, int>(wxColour(38, 46, 48), StateColor::Normal)
    );
    StateColor cancel_btn_text(
        std::pair<wxColour, int>(wxColour(38, 46, 48), StateColor::Normal)
    );
    StateColor calc_btn_bg(
        std::pair<wxColour, int>(wxColour(27, 136, 68), StateColor::Pressed),
        std::pair<wxColour, int>(wxColour(61, 203, 115), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal)
    );
    StateColor calc_btn_bd(
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal)
    );
    StateColor calc_btn_text(
        std::pair<wxColour, int>(wxColour(255, 255, 254), StateColor::Normal)
    );
    if (flags & wxRESET) {
        Button *calc_btn = new Button(this, _L("Auto-Calc"));
        calc_btn->SetMinSize(wxSize(FromDIP(75), FromDIP(24)));
        calc_btn->SetCornerRadius(FromDIP(12));
        calc_btn->SetBackgroundColor(calc_btn_bg);
        calc_btn->SetBorderColor(calc_btn_bd);
        calc_btn->SetTextColor(calc_btn_text);
        calc_btn->SetFocus();
        calc_btn->SetId(wxID_RESET);
        btn_sizer->Add(calc_btn, 0, wxRIGHT | wxALIGN_CENTER_VERTICAL, BTN_GAP);
    }
    if (flags & wxOK) {
        Button* ok_btn = new Button(this, _L("OK"));
        ok_btn->SetMinSize(BTN_SIZE);
        ok_btn->SetCornerRadius(FromDIP(12));
        ok_btn->SetBackgroundColor(ok_btn_bg);
        ok_btn->SetBorderColor(ok_btn_bd);
        ok_btn->SetTextColor(ok_btn_text);
        ok_btn->SetFocus();
        ok_btn->SetId(wxID_OK);
        btn_sizer->Add(ok_btn, 0, wxRIGHT | wxALIGN_CENTER_VERTICAL, BTN_GAP);
    }
    if (flags & wxCANCEL) {
        Button* cancel_btn = new Button(this, _L("Cancel"));
        cancel_btn->SetMinSize(BTN_SIZE);
        cancel_btn->SetCornerRadius(FromDIP(12));
        cancel_btn->SetBackgroundColor(cancel_btn_bg);
        cancel_btn->SetBorderColor(cancel_btn_bd_);
        cancel_btn->SetTextColor(cancel_btn_text);
        cancel_btn->SetId(wxID_CANCEL);
        btn_sizer->Add(cancel_btn, 0, wxRIGHT | wxALIGN_CENTER_VERTICAL, BTN_GAP);
    }
    return btn_sizer;
};
References _L, BTN_GAP, BTN_SIZE, StateColor::Hovered, StateColor::Normal, StateColor::Pressed, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetMinSize(), and Button::SetTextColor().
Referenced by WipingDialog().
get_extruders()
std::vector< float > WipingDialog::get_extruders () const inline
{ return m_output_extruders; }
References m_output_extruders.
Referenced by Slic3r::GUI::Sidebar::Sidebar().
get_flush_multiplier()
float WipingDialog::get_flush_multiplier () inline
    {
        if (m_panel_wiping == nullptr)
            return 1.f;
        return m_panel_wiping->get_flush_multiplier();
    }
References WipingPanel::get_flush_multiplier(), and m_panel_wiping.
Referenced by Slic3r::GUI::Sidebar::Sidebar().
get_matrix()
std::vector< float > WipingDialog::get_matrix () const inline
{ return m_output_matrix; }
References m_output_matrix.
Referenced by Slic3r::GUI::Sidebar::Sidebar().
Member Data Documentation
m_output_extruders
std::vector<float> WipingDialog::m_output_extruders private
Referenced by WipingDialog(), and get_extruders().
m_output_matrix
std::vector<float> WipingDialog::m_output_matrix private
Referenced by WipingDialog(), and get_matrix().
m_panel_wiping
WipingPanel* WipingDialog::m_panel_wiping = nullptr private
Referenced by WipingDialog(), and get_flush_multiplier().
The documentation for this class was generated from the following files:
src/slic3r/GUI/WipeTowerDialog.hpp
src/slic3r/GUI/WipeTowerDialog.cpp