OrcaSlicer: Slic3r::sla::Pad Struct Reference
Slic3r::sla::Pad Struct Reference
#include <src/libslic3r/SLA/SupportTreeBuilder.hpp>
Public Member Functions
Pad ()=default
Pad (const indexed_triangle_set &support_mesh, const ExPolygons &model_contours, double ground_level, const PadConfig &pcfg, ThrowOnCancel thr)
bool empty () const
Public Attributes
indexed_triangle_set tmesh
PadConfig cfg
double zlevel = 0
Detailed Description
Constructor & Destructor Documentation
Pad() [1/2]
Slic3r::sla::Pad::Pad () default
Pad() [2/2]
Slic3r::sla::Pad::Pad (const indexed_triangle_set & support_mesh, const ExPolygons & model_contours, double ground_level, const PadConfig & pcfg, ThrowOnCancel thr)
    : cfg(pcfg)
    , zlevel(ground_level + pcfg.full_height() - pcfg.required_elevation())
{
    thr();
    ExPolygons sup_contours;
    float zstart = float(zlevel);
    float zend   = zstart + float(pcfg.full_height() + EPSILON);
    pad_blueprint(support_mesh, sup_contours, grid(zstart, zend, 0.1f), thr);
    create_pad(sup_contours, model_contours, tmesh, pcfg);
    Vec3f offs{.0f, .0f, float(zlevel)};
    for (auto &p : tmesh.vertices) p += offs;
    its_merge_vertices(tmesh);
}
References Slic3r::sla::create_pad(), EPSILON, Slic3r::sla::PadConfig::full_height(), Slic3r::grid(), Slic3r::its_merge_vertices(), Slic3r::sla::pad_blueprint(), tmesh, indexed_triangle_set::vertices, and zlevel.
Member Function Documentation
empty()
bool Slic3r::sla::Pad::empty () const inline
{ return tmesh.indices.size() == 0; }
References indexed_triangle_set::indices, and tmesh.
Member Data Documentation
cfg
PadConfig Slic3r::sla::Pad::cfg
Referenced by Slic3r::sla::SupportTreeBuilder::full_height().
tmesh
indexed_triangle_set Slic3r::sla::Pad::tmesh
Referenced by Pad(), Slic3r::sla::SupportTreeBuilder::add_pad(), empty(), and Slic3r::sla::SupportTreeBuilder::retrieve_mesh().
zlevel
double Slic3r::sla::Pad::zlevel = 0
Referenced by Pad().
The documentation for this struct was generated from the following files:
src/libslic3r/SLA/SupportTreeBuilder.hpp
src/libslic3r/SLA/SupportTreeBuilder.cpp