OrcaSlicer: Slic3r::SL1Host Class Reference
Slic3r::SL1Host Class Reference
#include <src/slic3r/Utils/OctoPrint.hpp>
Public Types
typedef Http::ProgressFn ProgressFn
typedef std::function< void(wxString)> ErrorFn
Public Member Functions
SL1Host (DynamicPrintConfig *config)
~SL1Host () override=default
const char * get_name () const override
wxString get_test_ok_msg () const override
wxString get_test_failed_msg (wxString &msg) const override
PrintHostPostUploadActions get_post_upload_actions () const override
bool test (wxString &curl_msg) const override
bool upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn) const override
bool has_auto_discovery () const override
bool can_test () const override
std::string get_host () const override
const std::string & get_apikey () const
const std::string & get_cafile () const
virtual bool supports_multiple_printers () const
virtual bool get_groups (wxArrayString &) const
virtual bool get_printers (wxArrayString &) const
Static Public Member Functions
static PrintHost * get_print_host (DynamicPrintConfig *config)
Protected Member Functions
bool validate_version_text (const boost::optional< std::string > &version_text) const override
virtual wxString format_error (const std::string &body, const std::string &error, unsigned status) const
Private Member Functions
void set_auth (Http &http) const override
std::string make_url (const std::string &path) const
Private Attributes
AuthorizationType m_authorization_type
std::string m_username
std::string m_password
std::string m_host
std::string m_apikey
std::string m_cafile
bool m_ssl_revoke_best_effort
Detailed Description
Member Typedef Documentation
ErrorFn
typedef std::function<void(wxString)> Slic3r::PrintHost::ErrorFn inherited
ProgressFn
typedef Http::ProgressFn Slic3r::PrintHost::ProgressFn inherited
Constructor & Destructor Documentation
SL1Host()
Slic3r::SL1Host::SL1Host (DynamicPrintConfig * config)
                                           :
    OctoPrint(config),
    m_authorization_type(dynamic_cast<const ConfigOptionEnum<AuthorizationType>*>(config->option("printhost_authorization_type"))->value),
    m_username(config->opt_string("printhost_user")),
    m_password(config->opt_string("printhost_password"))
{
}
~SL1Host()
Slic3r::SL1Host::~SL1Host () override default
Member Function Documentation
can_test()
bool Slic3r::OctoPrint::can_test () const inline override virtual inherited
Implements Slic3r::PrintHost.
{ return true; }
format_error()
wxString Slic3r::PrintHost::format_error (const std::string & body, const std::string & error, unsigned status) const protected virtual inherited
{
    if (status != 0) {
        auto wxbody = wxString::FromUTF8(body.data());
        return wxString::Format("HTTP %u: %s", status, wxbody);
    } else {
        return wxString::FromUTF8(error.data());
    }
}
References error.
Referenced by Slic3r::Duet::connect(), Slic3r::Duet::start_print(), Slic3r::AstroBox::test(), Slic3r::FlashAir::test(), Slic3r::OctoPrint::test(), Slic3r::Repetier::test(), Slic3r::AstroBox::upload(), Slic3r::Duet::upload(), Slic3r::FlashAir::upload(), Slic3r::MKS::upload(), Slic3r::OctoPrint::upload(), and Slic3r::Repetier::upload().
get_apikey()
const std::string & Slic3r::OctoPrint::get_apikey () const inline inherited
{ return m_apikey; }
References Slic3r::OctoPrint::m_apikey.
Referenced by set_auth(), and Slic3r::PrusaLink::set_auth().
get_cafile()
const std::string & Slic3r::OctoPrint::get_cafile () const inline inherited
{ return m_cafile; }
References Slic3r::OctoPrint::m_cafile.
Referenced by set_auth(), and Slic3r::PrusaLink::set_auth().
get_groups()
virtual bool Slic3r::PrintHost::get_groups (wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
get_host()
std::string Slic3r::OctoPrint::get_host () const inline override virtual inherited
Implements Slic3r::PrintHost.
{ return m_host; }
References Slic3r::OctoPrint::m_host.
get_name()
const char * Slic3r::SL1Host::get_name () const override virtual
Reimplemented from Slic3r::OctoPrint.
{ return "SL1Host"; }
get_post_upload_actions()
PrintHostPostUploadActions Slic3r::SL1Host::get_post_upload_actions () const inline override virtual
Reimplemented from Slic3r::OctoPrint.
{ return {}; }
get_print_host()
PrintHost * Slic3r::PrintHost::get_print_host (DynamicPrintConfig * config) static inherited
{
    PrinterTechnology tech = ptFFF;
    {
        const auto opt = config->option<ConfigOptionEnum<PrinterTechnology>>("printer_technology");
        if (opt != nullptr) {
            tech = opt->value;
        }
    }
    if (tech == ptFFF) {
        const auto opt = config->option<ConfigOptionEnum<PrintHostType>>("host_type");
        const auto host_type = opt != nullptr ? opt->value : htOctoPrint;
        switch (host_type) {
            case htOctoPrint: return new OctoPrint(config);
            case htDuet:      return new Duet(config);
            case htFlashAir:  return new FlashAir(config);
            case htAstroBox:  return new AstroBox(config);
            case htRepetier:  return new Repetier(config);
            case htPrusaLink: return new PrusaLink(config);
            case htMKS:       return new MKS(config);
            default:          return nullptr;
        }
    } else {
        return new SL1Host(config);
    }
}
References Slic3r::htAstroBox, Slic3r::htDuet, Slic3r::htFlashAir, Slic3r::htMKS, Slic3r::htOctoPrint, Slic3r::htPrusaLink, Slic3r::htRepetier, Slic3r::ConfigBase::option(), Slic3r::ptFFF, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::PhysicalPrinterDialog::update_printers(), and Slic3r::GUI::PhysicalPrinterDialog::update_printhost_buttons().
get_printers()
virtual bool Slic3r::PrintHost::get_printers (wxArrayString &) const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
get_test_failed_msg()
wxString Slic3r::SL1Host::get_test_failed_msg (wxString & msg) const override virtual
Reimplemented from Slic3r::OctoPrint.
{
    return GUI::from_u8((boost::format("%s: %s")
                    % _utf8(L("Could not connect to Prusa SLA"))
                    % std::string(msg.ToUTF8())).str());
}
References _utf8, Slic3r::GUI::from_u8(), and L.
get_test_ok_msg()
wxString Slic3r::SL1Host::get_test_ok_msg () const override virtual
Reimplemented from Slic3r::OctoPrint.
{
    return _(L("Connection to Prusa SL1 / SL1S works correctly."));
}
References _, and L.
has_auto_discovery()
bool Slic3r::OctoPrint::has_auto_discovery () const inline override virtual inherited
Implements Slic3r::PrintHost.
{ return true; }
make_url()
std::string Slic3r::OctoPrint::make_url (const std::string & path) const private inherited
{
    if (m_host.find("http://") == 0 || m_host.find("https://") == 0) {
        if (m_host.back() == '/') {
            return (boost::format("%1%%2%") % m_host % path).str();
        } else {
            return (boost::format("%1%/%2%") % m_host % path).str();
        }
    } else {
        return (boost::format("http://%1%/%2%") % m_host % path).str();
    }
}
References Slic3r::OctoPrint::m_host.
Referenced by Slic3r::OctoPrint::test(), and Slic3r::OctoPrint::upload().
set_auth()
void Slic3r::SL1Host::set_auth (Http & http) const override private virtual
Reimplemented from Slic3r::OctoPrint.
{
    switch (m_authorization_type) {
    case atKeyPassword:
        http.header("X-Api-Key", get_apikey());
        break;
    case atUserPassword:
        http.auth_digest(m_username, m_password);
        break;
    }
    if (! get_cafile().empty()) {
        http.ca_file(get_cafile());
    }
}
References Slic3r::atKeyPassword, Slic3r::atUserPassword, Slic3r::Http::auth_digest(), Slic3r::Http::ca_file(), Slic3r::empty(), Slic3r::OctoPrint::get_apikey(), Slic3r::OctoPrint::get_cafile(), Slic3r::Http::header(), m_authorization_type, m_password, and m_username.
supports_multiple_printers()
virtual bool Slic3r::PrintHost::supports_multiple_printers () const inline virtual inherited
Reimplemented in Slic3r::Repetier.
{ return false; }
test()
bool Slic3r::OctoPrint::test (wxString & curl_msg) const override virtual inherited
Implements Slic3r::PrintHost.
{
    // Since the request is performed synchronously here,
    // it is ok to refer to `msg` from within the closure
    const char *name = get_name();
    bool res = true;
    auto url = make_url("api/version");
    BOOST_LOG_TRIVIAL(info) << boost::format("%1%: Get version at: %2%") % name % url;
    auto http = Http::get(std::move(url));
    set_auth(http);
    http.on_error([&](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Error getting version: %2%, HTTP %3%, body: `%4%`") % name % error % status % body;
            res = false;
            msg = format_error(body, error, status);
        })
        .on_complete([&, this](std::string body, unsigned) {
            BOOST_LOG_TRIVIAL(debug) << boost::format("%1%: Got version: %2%") % name % body;
            try {
                std::stringstream ss(body);
                pt::ptree ptree;
                pt::read_json(ss, ptree);
                if (! ptree.get_optional<std::string>("api")) {
                    res = false;
                    return;
                }
                const auto text = ptree.get_optional<std::string>("text");
                res = validate_version_text(text);
                if (! res) {
                    msg = GUI::from_u8((boost::format(_utf8(L("Mismatched type of print host: %s"))) % (text ? *text : "OctoPrint")).str());
                }
            }
            catch (const std::exception &) {
                res = false;
                msg = "Could not parse server response";
            }
        })
#ifdef WIN32
        .ssl_revoke_best_effort(m_ssl_revoke_best_effort)
        .on_ip_resolve([&](std::string address) {
            // Workaround for Windows 10/11 mDNS resolve issue, where two mDNS resolves in succession fail.
            // Remember resolved address to be reused at successive REST API call.
            msg = GUI::from_u8(address);
        })
#endif // WIN32
        .perform_sync();
    return res;
}
References _utf8, error, Slic3r::PrintHost::format_error(), Slic3r::GUI::from_u8(), Slic3r::Http::get(), Slic3r::OctoPrint::get_name(), L, Slic3r::OctoPrint::m_ssl_revoke_best_effort, Slic3r::OctoPrint::make_url(), Slic3r::OctoPrint::set_auth(), and Slic3r::OctoPrint::validate_version_text().
Referenced by Slic3r::OctoPrint::upload().
upload()
bool Slic3r::OctoPrint::upload (PrintHostUpload upload_data, ProgressFn prorgess_fn, ErrorFn error_fn) const override virtual inherited
Implements Slic3r::PrintHost.
{
    const char *name = get_name();
    const auto upload_filename = upload_data.upload_path.filename();
    const auto upload_parent_path = upload_data.upload_path.parent_path();
    // If test fails, test_msg_or_host_ip contains the error message.
    // Otherwise on Windows it contains the resolved IP address of the host.
    wxString test_msg_or_host_ip;
    if (! test(test_msg_or_host_ip)) {
        error_fn(std::move(test_msg_or_host_ip));
        return false;
    }
    std::string url;
    bool res = true;
#ifdef WIN32
    // Workaround for Windows 10/11 mDNS resolve issue, where two mDNS resolves in succession fail.
    if (m_host.find("https://") == 0 || test_msg_or_host_ip.empty())
#endif // _WIN32
    {
        // If https is entered we assume signed ceritificate is being used
        // IP resolving will not happen - it could resolve into address not being specified in cert
        url = make_url("api/files/local");
    }
#ifdef WIN32
    else {
        // Workaround for Windows 10/11 mDNS resolve issue, where two mDNS resolves in succession fail.
        // Curl uses easy_getinfo to get ip address of last successful transaction.
        // If it got the address use it instead of the stored in "host" variable.
        // This new address returns in "test_msg_or_host_ip" variable.
        // Solves troubles of uploades failing with name address.
        // in original address (m_host) replace host for resolved ip
        url = substitute_host(make_url("api/files/local"), GUI::into_u8(test_msg_or_host_ip));
        BOOST_LOG_TRIVIAL(info) << "Upload address after ip resolve: " << url;
    }
#endif // _WIN32
    BOOST_LOG_TRIVIAL(info) << boost::format("%1%: Uploading file %2% at %3%, filename: %4%, path: %5%, print: %6%")
        % name
        % upload_data.source_path
        % url
        % upload_filename.string()
        % upload_parent_path.string()
        % (upload_data.post_action == PrintHostPostUploadAction::StartPrint ? "true" : "false");
    auto http = Http::post(std::move(url));
    set_auth(http);
    http.form_add("print", upload_data.post_action == PrintHostPostUploadAction::StartPrint ? "true" : "false")
        .form_add("path", upload_parent_path.string())      // XXX: slashes on windows ???
        .form_add_file("file", upload_data.source_path.string(), upload_filename.string())
        .on_complete([&](std::string body, unsigned status) {
            BOOST_LOG_TRIVIAL(debug) << boost::format("%1%: File uploaded: HTTP %2%: %3%") % name % status % body;
        })
        .on_error([&](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << boost::format("%1%: Error uploading file: %2%, HTTP %3%, body: `%4%`") % name % error % status % body;
            error_fn(format_error(body, error, status));
            res = false;
        })
        .on_progress([&](Http::Progress progress, bool &cancel) {
            prorgess_fn(std::move(progress), cancel);
            if (cancel) {
                // Upload was canceled
                BOOST_LOG_TRIVIAL(info) << "Octoprint: Upload canceled";
                res = false;
            }
        })
#ifdef WIN32
        .ssl_revoke_best_effort(m_ssl_revoke_best_effort)
#endif
        .perform_sync();
    return res;
}
References error, Slic3r::PrintHost::format_error(), Slic3r::OctoPrint::get_name(), Slic3r::GUI::into_u8(), Slic3r::OctoPrint::m_host, Slic3r::OctoPrint::m_ssl_revoke_best_effort, Slic3r::OctoPrint::make_url(), Slic3r::Http::post(), Slic3r::PrintHostUpload::post_action, Slic3r::OctoPrint::set_auth(), Slic3r::PrintHostUpload::source_path, Slic3r::StartPrint, Slic3r::OctoPrint::test(), and Slic3r::PrintHostUpload::upload_path.
validate_version_text()
bool Slic3r::SL1Host::validate_version_text (const boost::optional< std::string > & version_text) const override protected virtual
Reimplemented from Slic3r::OctoPrint.
{
    return version_text ? boost::starts_with(*version_text, "Prusa SLA") : false;
}
Member Data Documentation
m_apikey
std::string Slic3r::OctoPrint::m_apikey private inherited
Referenced by Slic3r::OctoPrint::get_apikey(), and Slic3r::OctoPrint::set_auth().
m_authorization_type
AuthorizationType Slic3r::SL1Host::m_authorization_type private
Referenced by set_auth().
m_cafile
std::string Slic3r::OctoPrint::m_cafile private inherited
Referenced by Slic3r::OctoPrint::get_cafile(), and Slic3r::OctoPrint::set_auth().
m_host
std::string Slic3r::OctoPrint::m_host private inherited
Referenced by Slic3r::OctoPrint::get_host(), Slic3r::OctoPrint::make_url(), and Slic3r::OctoPrint::upload().
m_password
std::string Slic3r::SL1Host::m_password private
Referenced by set_auth().
m_ssl_revoke_best_effort
bool Slic3r::OctoPrint::m_ssl_revoke_best_effort private inherited
Referenced by Slic3r::OctoPrint::test(), and Slic3r::OctoPrint::upload().
m_username
std::string Slic3r::SL1Host::m_username private
Referenced by set_auth().
The documentation for this class was generated from the following files:
src/slic3r/Utils/OctoPrint.hpp
src/slic3r/Utils/OctoPrint.cpp