OrcaSlicer: Slic3r::GCode::LayerToPrint Struct Reference
Slic3r::GCode::LayerToPrint Struct Reference
#include <src/libslic3r/GCode.hpp>
Public Member Functions
LayerToPrint ()
const Layer * layer () const
const PrintObject * object () const
coordf_t print_z () const
Public Attributes
const Layer * object_layer
const SupportLayer * support_layer
const PrintObject * original_object
Detailed Description
Constructor & Destructor Documentation
LayerToPrint()
Slic3r::GCode::LayerToPrint::LayerToPrint () inline
: object_layer(nullptr), support_layer(nullptr), original_object(nullptr) {}
Member Function Documentation
layer()
const Layer * Slic3r::GCode::LayerToPrint::layer () const inline
        {
            if (object_layer != nullptr)
                return object_layer;
            if (support_layer != nullptr)
                return support_layer;
            return nullptr;
        }
References object_layer, and support_layer.
Referenced by Slic3r::GCode::collect_layers_to_print(), object(), and Slic3r::GCode::process_layer().
object()
const PrintObject * Slic3r::GCode::LayerToPrint::object () const inline
        {
            return (this->layer() != nullptr) ? this->layer()->object() : nullptr;
        }
References layer(), and Slic3r::Layer::object().
print_z()
coordf_t Slic3r::GCode::LayerToPrint::print_z () const inline
        {
            coordf_t sum_z = 0.;
            size_t count = 0;
            if (object_layer != nullptr) {
                sum_z += object_layer->print_z;
                count++;
            }
            if (support_layer != nullptr) {
                sum_z += support_layer->print_z;
                count++;
            }
            return sum_z / count;
        }
References count, object_layer, Slic3r::Layer::print_z, and support_layer.
Referenced by Slic3r::GCode::collect_layers_to_print(), and Slic3r::GCode::process_layers().
Member Data Documentation
object_layer
const Layer* Slic3r::GCode::LayerToPrint::object_layer
Referenced by Slic3r::GCode::collect_layers_to_print(), layer(), print_z(), and Slic3r::GCode::process_layer().
original_object
const PrintObject* Slic3r::GCode::LayerToPrint::original_object
Referenced by Slic3r::GCode::collect_layers_to_print(), and Slic3r::GCode::process_layer().
support_layer
const SupportLayer* Slic3r::GCode::LayerToPrint::support_layer
Referenced by Slic3r::GCode::collect_layers_to_print(), layer(), and print_z().
The documentation for this struct was generated from the following file:
src/libslic3r/GCode.hpp