OrcaSlicer: orgQhull::QhullFacetList Class Reference
orgQhull::QhullFacetList Class Reference
#include <src/qhull/src/libqhullcpp/QhullFacetList.h>
Classes
struct PrintFacetList
struct PrintFacets
struct PrintVertices
Public Types
Defined here
typedef const_iterator ConstIterator
typedef iterator Iterator
typedef ptrdiff_t difference_type
typedef countT size_type
typedef QhullFacet value_type
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef value_type * pointer
typedef value_type & reference
Public Member Functions
Conversion
std::vector< QhullFacet > toStdVector () const
std::vector< QhullVertex > vertices_toStdVector () const
Same as PrintVertices.
GetSet
Filtered by facet.isGood(). May be 0 when !isEmpty().
countT count () const
bool contains (const QhullFacet &f) const
countT count (const QhullFacet &f) const
bool isSelectAll () const
QhullQh * qh () const
void selectAll ()
void selectGood ()
operator==() does not depend on isGood()
IO
PrintFacetList print (const char *message) const
PrintFacets printFacets () const
PrintVertices printVertices () const
Search
countT count (const QhullFacet &t) const
bool contains (const QhullFacet &t) const
GetSet
bool isEmpty () const
bool operator== (const QhullLinkedList< QhullFacet > &o) const
bool operator!= (const QhullLinkedList< QhullFacet > &o) const
size_t size () const
Element access
For back() and last(), return T instead of T& (T is computed)
const QhullFacet back () const
QhullFacet back ()
const QhullFacet & first () const
QhullFacet & first ()
const QhullFacet & front () const
QhullFacet & front ()
const QhullFacet last () const
QhullFacet last ()
Iterator
iterator begin ()
const_iterator begin () const
const_iterator constBegin () const
const_iterator constEnd () const
iterator end ()
const_iterator end () const
Private Attributes
Fields
bool select_all
Fields
QhullFacet begin_node
QhullFacet end_node
Constructors
True if include bad facets. Default is false.
QhullFacetList (const Qhull &q, facetT *b, facetT *e)
QhullFacetList (QhullQh *qqh, facetT *b, facetT *e)
QhullFacetList (QhullFacet b, QhullFacet e)
QhullFacetList (const QhullFacetList &other)
QhullFacetList & operator= (const QhullFacetList &other)
~QhullFacetList ()
QhullFacetList ()
Disable default constructor. See QhullLinkedList.
Detailed Description
Member Typedef Documentation
const_pointer
typedef const value_type* orgQhull::QhullLinkedList< QhullFacet >::const_pointer inherited
const_reference
typedef const value_type& orgQhull::QhullLinkedList< QhullFacet >::const_reference inherited
ConstIterator
typedef const_iterator orgQhull::QhullLinkedList< QhullFacet >::ConstIterator inherited
difference_type
typedef ptrdiff_t orgQhull::QhullLinkedList< QhullFacet >::difference_type inherited
Iterator
typedef iterator orgQhull::QhullLinkedList< QhullFacet >::Iterator inherited
pointer
typedef value_type* orgQhull::QhullLinkedList< QhullFacet >::pointer inherited
reference
typedef value_type& orgQhull::QhullLinkedList< QhullFacet >::reference inherited
size_type
typedef countT orgQhull::QhullLinkedList< QhullFacet >::size_type inherited
value_type
typedef QhullFacet orgQhull::QhullLinkedList< QhullFacet >::value_type inherited
Constructor & Destructor Documentation
QhullFacetList() [1/5]
orgQhull::QhullFacetList::QhullFacetList (const Qhull & q, facetT * b, facetT * e)
: QhullLinkedList<QhullFacet>(QhullFacet(q, b), QhullFacet(q, e))
, select_all(false)
{
}
QhullFacetList() [2/5]
orgQhull::QhullFacetList::QhullFacetList (QhullQh * qqh, facetT * b, facetT * e)
QhullFacetList() [3/5]
orgQhull::QhullFacetList::QhullFacetList (QhullFacet b, QhullFacet e) inline
: QhullLinkedList<QhullFacet>(b, e), select_all(false) {}
QhullFacetList() [4/5]
orgQhull::QhullFacetList::QhullFacetList (const QhullFacetList & other) inline
: QhullLinkedList<QhullFacet>(*other.begin(), *other.end()), select_all(other.select_all) {}
~QhullFacetList()
orgQhull::QhullFacetList::~QhullFacetList () inline
{}
QhullFacetList() [5/5]
orgQhull::QhullFacetList::QhullFacetList () private
Disable default constructor. See QhullLinkedList.
Member Function Documentation
back() [1/2]
QhullFacet orgQhull::QhullLinkedList< QhullFacet >::back () inline inherited
{ return last(); }
back() [2/2]
const QhullFacet orgQhull::QhullLinkedList< QhullFacet >::back () const inline inherited
{ return last(); }
begin() [1/2]
iterator orgQhull::QhullLinkedList< QhullFacet >::begin () inline inherited
{ return begin_node; }
begin() [2/2]
const_iterator orgQhull::QhullLinkedList< QhullFacet >::begin () const inline inherited
{ return begin_node; }
constBegin()
const_iterator orgQhull::QhullLinkedList< QhullFacet >::constBegin () const inline inherited
{ return begin_node; }
constEnd()
const_iterator orgQhull::QhullLinkedList< QhullFacet >::constEnd () const inline inherited
{ return end_node; }
contains() [1/2]
bool orgQhull::QhullFacetList::contains (const QhullFacet & f) const
{
    if(isSelectAll()){
        return QhullLinkedList<QhullFacet>::contains(facet);
    }
    for(QhullFacetList::const_iterator i=begin(); i != end(); ++i){
        QhullFacet f= *i;
        if(f==facet && f.isGood()){
            return true;
        }
    }
    return false;
}//contains
References orgQhull::QhullLinkedList< QhullFacet >::begin(), orgQhull::QhullLinkedList< T >::contains(), orgQhull::QhullLinkedList< QhullFacet >::end(), orgQhull::QhullFacet::isGood(), and isSelectAll().
contains() [2/2]
bool orgQhull::QhullLinkedList< QhullFacet >::contains (const QhullFacet & t) const inherited
{
    const_iterator i= begin_node;
    while(i != end_node){
        if(i==t){
            return true;
        }
        i++;
    }
    return false;
}//contains
count() [1/3]
int orgQhull::QhullFacetList::count () const
{
    if(isSelectAll()){
        return QhullLinkedList<QhullFacet>::count();
    }
    int counter= 0;
    for(QhullFacetList::const_iterator i=begin(); i != end(); ++i){
        if((*i).isGood()){
            counter++;
        }
    }
    return counter;
}//count
References orgQhull::QhullLinkedList< QhullFacet >::begin(), orgQhull::QhullLinkedList< T >::count(), orgQhull::QhullLinkedList< QhullFacet >::end(), and isSelectAll().
Referenced by orgQhull::Qhull_test::t_attribute(), orgQhull::QhullFacetList_test::t_construct_q(), orgQhull::QhullFacetList_test::t_construct_qh(), orgQhull::QhullFacetList_test::t_convert(), and orgQhull::Qhull_test::t_foreach().
count() [2/3]
int orgQhull::QhullFacetList::count (const QhullFacet & f) const
{
    if(isSelectAll()){
        return QhullLinkedList<QhullFacet>::count(facet);
    }
    int counter= 0;
    for(QhullFacetList::const_iterator i=begin(); i != end(); ++i){
        QhullFacet f= *i;
        if(f==facet && f.isGood()){
            counter++;
        }
    }
    return counter;
}//count
References orgQhull::QhullLinkedList< QhullFacet >::begin(), orgQhull::QhullLinkedList< T >::count(), orgQhull::QhullLinkedList< QhullFacet >::end(), orgQhull::QhullFacet::isGood(), and isSelectAll().
count() [3/3]
countT orgQhull::QhullLinkedList< QhullFacet >::count (const QhullFacet & t) const inherited
{
    const_iterator i= begin_node;
    countT c= 0;
    while(i != end_node){
        if(i==t){
            c++;
        }
        i++;
    }
    return c;
}//count
end() [1/2]
iterator orgQhull::QhullLinkedList< QhullFacet >::end () inline inherited
{ return end_node; }
end() [2/2]
const_iterator orgQhull::QhullLinkedList< QhullFacet >::end () const inline inherited
{ return end_node; }
first() [1/2]
QhullFacet & orgQhull::QhullLinkedList< QhullFacet >::first () inline inherited
{ QHULL_ASSERT(!isEmpty()); return begin_node; }
first() [2/2]
const QhullFacet & orgQhull::QhullLinkedList< QhullFacet >::first () const inline inherited
{ QHULL_ASSERT(!isEmpty()); return begin_node; }
front() [1/2]
QhullFacet & orgQhull::QhullLinkedList< QhullFacet >::front () inline inherited
{ return first(); }
front() [2/2]
const QhullFacet & orgQhull::QhullLinkedList< QhullFacet >::front () const inline inherited
{ return first(); }
isEmpty()
bool orgQhull::QhullLinkedList< QhullFacet >::isEmpty () const inline inherited
{ return (begin_node==end_node); }
isSelectAll()
bool orgQhull::QhullFacetList::isSelectAll () const inline
{ return select_all; }
References select_all.
Referenced by contains(), count(), count(), orgQhull::QhullFacetList_test::t_convert(), toStdVector(), and vertices_toStdVector().
last() [1/2]
QhullFacet orgQhull::QhullLinkedList< QhullFacet >::last () inline inherited
{ QHULL_ASSERT(!isEmpty()); return *--end(); }
last() [2/2]
const QhullFacet orgQhull::QhullLinkedList< QhullFacet >::last () const inline inherited
{ QHULL_ASSERT(!isEmpty()); return *--end(); }
operator!=()
bool orgQhull::QhullLinkedList< QhullFacet >::operator!= (const QhullLinkedList< QhullFacet > & o) const inline inherited
{ return !operator==(o); }
operator=()
QhullFacetList & orgQhull::QhullFacetList::operator= (const QhullFacetList & other) inline
{ QhullLinkedList<QhullFacet>::operator =(other); select_all= other.select_all; return *this; }
References orgQhull::QhullLinkedList< T >::operator=(), and select_all.
operator==()
bool orgQhull::QhullLinkedList< QhullFacet >::operator== (const QhullLinkedList< QhullFacet > & o) const inherited
{
    if(begin_node==l.begin_node){
        return (end_node==l.end_node);
    }
    T i= begin_node;
    T il= l.begin_node;
    while(i != end_node){
        if(i != il){
            return false;
        }
        i= static_cast<T>(i.next());
        il= static_cast<T>(il.next());
    }
    if(il != l.end_node){
        return false;
    }
    return true;
}//operator==
print()
PrintFacetList orgQhull::QhullFacetList::print (const char * message) const inline
{ return PrintFacetList(*this, message); }
printFacets()
PrintFacets orgQhull::QhullFacetList::printFacets () const inline
{ return PrintFacets(*this); }
printVertices()
PrintVertices orgQhull::QhullFacetList::printVertices () const inline
{ return PrintVertices(*this); }
qh()
QhullQh * orgQhull::QhullFacetList::qh () const inline
{ return first().qh(); }
References orgQhull::QhullLinkedList< QhullFacet >::first(), and orgQhull::QhullFacet::qh().
Referenced by vertices_toStdVector().
selectAll()
void orgQhull::QhullFacetList::selectAll () inline
{ select_all= true; }
References select_all.
Referenced by orgQhull::QhullFacetList_test::t_convert().
selectGood()
void orgQhull::QhullFacetList::selectGood () inline
operator==() does not depend on isGood()
References select_all.
size()
size_t orgQhull::QhullLinkedList< QhullFacet >::size () const inline inherited
{ return count(); }
toStdVector()
std::vector< QhullFacet > orgQhull::QhullFacetList::toStdVector () const
{
    QhullLinkedListIterator<QhullFacet> i(*this);
    std::vector<QhullFacet> vs;
    while(i.hasNext()){
        QhullFacet f= i.next();
        if(isSelectAll() || f.isGood()){
            vs.push_back(f);
        }
    }
    return vs;
}//toStdVector
References orgQhull::QhullLinkedListIterator< T >::hasNext(), orgQhull::QhullFacet::isGood(), isSelectAll(), and orgQhull::QhullLinkedListIterator< T >::next().
Referenced by orgQhull::QhullFacetList_test::t_construct_q(), orgQhull::QhullFacetList_test::t_construct_qh(), and orgQhull::QhullFacetList_test::t_convert().
vertices_toStdVector()
std::vector< QhullVertex > orgQhull::QhullFacetList::vertices_toStdVector () const
Same as PrintVertices.
{
    std::vector<QhullVertex> vs;
    QhullVertexSet qvs(qh(), first().getFacetT(), 0, isSelectAll());
    for(QhullVertexSet::iterator i=qvs.begin(); i!=qvs.end(); ++i){
        vs.push_back(*i);
    }
    return vs;
}//vertices_toStdVector
References orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::end(), orgQhull::QhullLinkedList< QhullFacet >::first(), isSelectAll(), and qh().
Referenced by orgQhull::QhullFacetList_test::t_convert().
Member Data Documentation
begin_node
QhullFacet orgQhull::QhullLinkedList< QhullFacet >::begin_node private inherited
end_node
QhullFacet orgQhull::QhullLinkedList< QhullFacet >::end_node private inherited
select_all
bool orgQhull::QhullFacetList::select_all private
Referenced by isSelectAll(), operator=(), selectAll(), and selectGood().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullFacetList.h
src/qhull/src/libqhullcpp/QhullFacetList.cpp