OrcaSlicer: src/qhull/src/libqhullcpp/QhullHyperplane.cpp File Reference
QhullHyperplane.cpp File Reference
#include "libqhullcpp/QhullHyperplane.h"
#include "libqhullcpp/Qhull.h"
#include "libqhullcpp/QhullPoint.h"
#include <iostream>
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
GetSet<<
ostream & operator<< (ostream &os, const QhullHyperplane &p)
ostream & operator<< (ostream &os, const QhullHyperplane::PrintHyperplane &pr)
Function Documentation
operator<<() [1/2]
ostream & operator<< (ostream & os, const QhullHyperplane & p)
{
    os << p.print("");
    return os;
}
References orgQhull::QhullHyperplane::print().
operator<<() [2/2]
ostream & operator<< (ostream & os, const QhullHyperplane::PrintHyperplane & pr)
{
    os << pr.print_message;
    QhullHyperplane p= *pr.hyperplane;
    const realT *c= p.coordinates();
    for(int k=p.dimension(); k--; ){
        realT r= *c++;
        if(pr.print_message){
            os << " " << r; // FIXUP QH11010 %8.4g
        }else{
            os << " " << r; // FIXUP QH11010 qh_REAL_1
        }
    }
    os << pr.hyperplane_offset_message << " " << p.offset();
    os << std::endl;
    return os;
}//PrintHyperplane
References orgQhull::QhullHyperplane::coordinates(), orgQhull::QhullHyperplane::dimension(), orgQhull::QhullHyperplane::offset(), and realT.