OrcaSlicer: Slic3r::GLVolumeCollection Class Reference
Slic3r::GLVolumeCollection Class Reference
#include <src/slic3r/GUI/3DScene.hpp>
Classes
struct PrintVolume
struct Slope
Public Types
enum class ERenderType : unsigned char { Opaque , Transparent , All }
Public Member Functions
GLVolumeCollection ()
~GLVolumeCollection ()
std::vector< int > load_object (const ModelObject *model_object, int obj_idx, const std::vector< int > &instance_idxs, const std::string &color_by, bool opengl_initialized)
int load_object_volume (const ModelObject *model_object, int obj_idx, int volume_idx, int instance_idx, const std::string &color_by, bool opengl_initialized, bool in_assemble_view=false, bool use_loaded_id=false)
void load_object_auxiliary (const SLAPrintObject *print_object, int obj_idx, const std::vector< std::pair< size_t, size_t > > &instances, SLAPrintObjectStep milestone, size_t timestamp, bool opengl_initialized)
int load_wipe_tower_preview (int obj_idx, float pos_x, float pos_y, float width, float depth, float height, float rotation_angle, bool size_unknown, float brim_width, bool opengl_initialized)
GLVolume * new_toolpath_volume (const std::array< float, 4 > &rgba, size_t reserve_vbo_floats=0)
GLVolume * new_nontoolpath_volume (const std::array< float, 4 > &rgba, size_t reserve_vbo_floats=0)
int get_selection_support_threshold_angle (bool &) const
void render (ERenderType type, bool disable_cullface, const Transform3d &view_matrix, std::function< bool(const GLVolume &)> filter_func=std::function< bool(const GLVolume &)>(), bool with_outline=true) const
void finalize_geometry (bool opengl_initialized)
void release_geometry ()
void clear ()
bool empty () const
void set_range (double low, double high)
void set_print_volume (const PrintVolume &print_volume)
void set_z_range (float min_z, float max_z)
void set_clipping_plane (const double *coeffs)
bool is_slope_GlobalActive () const
bool is_slope_active () const
void set_slope_active (bool active)
void set_slope_GlobalActive (bool active)
float get_slope_normal_z () const
void set_slope_normal_z (float normal_z)
void set_default_slope_normal_z ()
void set_show_sinking_contours (bool show)
bool check_outside_state (const Slic3r::BuildVolume &build_volume, ModelInstanceEPrintVolumeState *out_state) const
void reset_outside_state ()
void update_colors_by_extruder (const DynamicPrintConfig *config, bool is_update_alpha=true)
std::vector< double > get_current_print_zs (bool active_only) const
size_t cpu_memory_used () const
size_t gpu_memory_used () const
size_t total_memory_used () const
std::string log_memory_info () const
Public Attributes
GLVolumePtrs volumes
Private Member Functions
GLVolumeCollection (const GLVolumeCollection &other)
GLVolumeCollection & operator= (const GLVolumeCollection &)
Private Attributes
PrintVolume m_print_volume
PrintVolume m_render_volume
float m_z_range [2]
float m_clipping_plane [4]
Slope m_slope
bool m_show_sinking_contours = false
Detailed Description
Class Documentation
Slic3r::GLVolumeCollection::PrintVolume
struct Slic3r::GLVolumeCollection::PrintVolume
Class Members
array< float, 4 > data
int type { 0 }
array< float, 2 > zs
Slic3r::GLVolumeCollection::Slope
struct Slic3r::GLVolumeCollection::Slope
Class Members
bool active { false }
bool isGlobalActive {false}
float normal_z
Member Enumeration Documentation
ERenderType
enum class Slic3r::GLVolumeCollection::ERenderType : unsigned char strong
Enumerator
Opaque
Transparent
All
    {
        Opaque,
        Transparent,
        All
    };
Constructor & Destructor Documentation
GLVolumeCollection() [1/2]
Slic3r::GLVolumeCollection::GLVolumeCollection () inline
{
        set_default_slope_normal_z();
        //BBS init render volume
        m_render_volume.type = -1;
    }
References m_render_volume, set_default_slope_normal_z(), and Slic3r::GLVolumeCollection::PrintVolume::type.
~GLVolumeCollection()
Slic3r::GLVolumeCollection::~GLVolumeCollection () inline
{ clear(); }
References clear().
GLVolumeCollection() [2/2]
Slic3r::GLVolumeCollection::GLVolumeCollection (const GLVolumeCollection & other) private
Member Function Documentation
check_outside_state()
bool Slic3r::GLVolumeCollection::check_outside_state (const Slic3r::BuildVolume & build_volume, ModelInstanceEPrintVolumeState * out_state) const
{
    if (GUI::wxGetApp().plater() == NULL)
    {
        if (out_state != nullptr)
            *out_state = ModelInstancePVS_Inside;
        return false;
    }
    const Model&        model              = GUI::wxGetApp().plater()->model();
    auto                volume_below       = [](GLVolume& volume) -> bool
        { return volume.object_idx() != -1 && volume.volume_idx() != -1 && volume.is_below_printbed(); };
    // Volume is partially below the print bed, thus a pre-calculated convex hull cannot be used.
    auto                volume_sinking     = [](GLVolume& volume) -> bool
        { return volume.object_idx() != -1 && volume.volume_idx() != -1 && volume.is_sinking(); };
    // Cached bounding box of a volume above the print bed.
    auto                volume_bbox        = [volume_sinking](GLVolume& volume) -> BoundingBoxf3
        { return volume_sinking(volume) ? volume.transformed_non_sinking_bounding_box() : volume.transformed_convex_hull_bounding_box(); };
    // Cached 3D convex hull of a volume above the print bed.
    auto                volume_convex_mesh = [volume_sinking, &model](GLVolume& volume) -> const TriangleMesh&
        { return volume_sinking(volume) ? model.objects[volume.object_idx()]->volumes[volume.volume_idx()]->mesh() : *volume.convex_hull(); };
    ModelInstanceEPrintVolumeState overall_state = ModelInstancePVS_Inside;
    bool contained_min_one = false;
    //BBS: add instance judge logic, besides to original volume judge logic
    std::map<int64_t, ModelInstanceEPrintVolumeState> model_state;
    GUI::PartPlate* curr_plate = GUI::wxGetApp().plater()->get_partplate_list().get_selected_plate();
    const Pointfs& pp_bed_shape = curr_plate->get_shape();
    BuildVolume plate_build_volume(pp_bed_shape, build_volume.printable_height());
    const std::vector<BoundingBoxf3>& exclude_areas = curr_plate->get_exclude_areas();
    for (GLVolume* volume : this->volumes)
    {
        if (! volume->is_modifier && (volume->shader_outside_printer_detection_enabled || (! volume->is_wipe_tower && volume->composite_id.volume_id >= 0))) {
            BuildVolume::ObjectState state;
            const BoundingBoxf3& bb = volume_bbox(*volume);
            if (volume_below(*volume))
                state = BuildVolume::ObjectState::Below;
            else {
                switch (plate_build_volume.type()) {
                case BuildVolume_Type::Rectangle:
                //FIXME this test does not evaluate collision of a build volume bounding box with non-convex objects.
                    state = plate_build_volume.volume_state_bbox(bb);
                    break;
                case BuildVolume_Type::Circle:
                case BuildVolume_Type::Convex:
                //FIXME doing test on convex hull until we learn to do test on non-convex polygons efficiently.
                case BuildVolume_Type::Custom:
                    state = plate_build_volume.object_state(volume_convex_mesh(*volume).its, volume->world_matrix().cast<float>(), volume_sinking(*volume));
                    break;
                default:
                    // Ignore, don't produce any collision.
                    state = BuildVolume::ObjectState::Inside;
                    break;
                }
                assert(state != BuildVolume::ObjectState::Below);
            }
            int64_t comp_id = ((int64_t)volume->composite_id.object_id << 32) | ((int64_t)volume->composite_id.instance_id);
            volume->is_outside = state != BuildVolume::ObjectState::Inside;
            //volume->partly_inside = (state == BuildVolume::ObjectState::Colliding);
            if (volume->printable) {
                if (overall_state == ModelInstancePVS_Inside && volume->is_outside) {
                    overall_state = ModelInstancePVS_Fully_Outside;
                }
                if (overall_state == ModelInstancePVS_Fully_Outside && volume->is_outside && (state == BuildVolume::ObjectState::Colliding))
                {
                    overall_state = ModelInstancePVS_Partly_Outside;
                }
                contained_min_one |= !volume->is_outside;
            }
            ModelInstanceEPrintVolumeState volume_state;
            //if (volume->is_outside && (plate_build_volume.bounding_volume().intersects(volume->bounding_box())))
            if (volume->is_outside && (state == BuildVolume::ObjectState::Colliding))
                volume_state = ModelInstancePVS_Partly_Outside;
            else if (volume->is_outside)
                volume_state = ModelInstancePVS_Fully_Outside;
            else
                volume_state = ModelInstancePVS_Inside;
            if (model_state.find(comp_id) != model_state.end())
            {
                if (model_state[comp_id] != ModelInstancePVS_Partly_Outside)
                {
                    if (volume_state == ModelInstancePVS_Partly_Outside)
                        model_state[comp_id] = ModelInstancePVS_Partly_Outside;
                    else if (model_state[comp_id] != volume_state)
                    {
                        model_state[comp_id] = ModelInstancePVS_Partly_Outside;
                    }
                }
            }
            else
            {
                model_state[comp_id] = volume_state;
            }
            if (model_state[comp_id] == ModelInstancePVS_Partly_Outside) {
                overall_state = ModelInstancePVS_Partly_Outside;
                BOOST_LOG_TRIVIAL(debug) << "instance includes " << volume->name << " is partially outside of bed";
            }
        }
    }
    for (GLVolume* volume : this->volumes)
    {
        if (! volume->is_modifier && (volume->shader_outside_printer_detection_enabled || (! volume->is_wipe_tower && volume->composite_id.volume_id >= 0)))
        {
            int64_t comp_id = ((int64_t)volume->composite_id.object_id << 32) | ((int64_t)volume->composite_id.instance_id);
            if (model_state.find(comp_id) != model_state.end())
            {
                if (model_state[comp_id] == ModelInstancePVS_Partly_Outside) {
                    volume->partly_inside = true;
                }
                else
                    volume->partly_inside = false;
            }
        }
    }
    if (out_state != nullptr)
        *out_state = overall_state;
    return contained_min_one;
}
References Slic3r::BuildVolume::Below, Slic3r::Circle, Slic3r::BuildVolume::Colliding, Slic3r::Convex, Slic3r::Custom, Slic3r::GUI::PartPlate::get_exclude_areas(), Slic3r::GUI::PartPlate::get_shape(), Slic3r::BuildVolume::Inside, Slic3r::ModelInstancePVS_Fully_Outside, Slic3r::ModelInstancePVS_Inside, Slic3r::ModelInstancePVS_Partly_Outside, NULL, Slic3r::BuildVolume::object_state(), Slic3r::Model::objects, Slic3r::BuildVolume::printable_height(), Slic3r::Rectangle, Slic3r::BuildVolume::type(), Slic3r::BuildVolume::volume_state_bbox(), and volumes.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::check_volumes_outside_state(), and Slic3r::GUI::GLCanvas3D::reload_scene().
clear()
void Slic3r::GLVolumeCollection::clear () inline
{ for (auto *v : volumes) delete v; volumes.clear(); }
References volumes.
Referenced by ~GLVolumeCollection(), Slic3r::GUI::GCodeViewer::reset_shell(), and Slic3r::GUI::GLCanvas3D::reset_volumes().
cpu_memory_used()
size_t Slic3r::GLVolumeCollection::cpu_memory_used () const
{
  size_t memsize = sizeof(*this) + this->volumes.capacity() * sizeof(GLVolume);
  for (const GLVolume *volume : this->volumes)
    memsize += volume->cpu_memory_used();
  return memsize;
}
References volumes.
Referenced by log_memory_info(), and total_memory_used().
empty()
bool Slic3r::GLVolumeCollection::empty () const inline
{ return volumes.empty(); }
References volumes.
Referenced by Slic3r::GUI::GLCanvas3D::_render_background(), Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GCodeViewer::render_shells(), and Slic3r::GUI::GLCanvas3D::reset_volumes().
finalize_geometry()
void Slic3r::GLVolumeCollection::finalize_geometry (bool opengl_initialized) inline
{ for (auto* v : volumes) v->finalize_geometry(opengl_initialized); }
References volumes.
Referenced by Slic3r::GUI::GLCanvas3D::init().
get_current_print_zs()
std::vector< double > Slic3r::GLVolumeCollection::get_current_print_zs (bool active_only) const
{
    // Collect layer top positions of all volumes.
    std::vector<double> print_zs;
    for (GLVolume *vol : this->volumes)
    {
        if (!active_only || vol->is_active)
            append(print_zs, vol->print_zs);
    }
    std::sort(print_zs.begin(), print_zs.end());
    // Replace intervals of layers with similar top positions with their average value.
    int n = int(print_zs.size());
    int k = 0;
    for (int i = 0; i < n;) {
        int j = i + 1;
        coordf_t zmax = print_zs[i] + EPSILON;
        for (; j < n && print_zs[j] <= zmax; ++ j) ;
        print_zs[k ++] = (j > i + 1) ? (0.5 * (print_zs[i] + print_zs[j - 1])) : print_zs[i];
        i = j;
    }
    if (k < n)
        print_zs.erase(print_zs.begin() + k, print_zs.end());
    return print_zs;
}
References Slic3r::append(), EPSILON, int, n, volumes, and zmax.
Referenced by Slic3r::GUI::GLCanvas3D::get_volumes_print_zs().
get_selection_support_threshold_angle()
int Slic3r::GLVolumeCollection::get_selection_support_threshold_angle (bool & enable_support) const
{
    const DynamicPrintConfig& glb_cfg        = GUI::wxGetApp().preset_bundle->prints.get_edited_preset().config;
    enable_support =  glb_cfg.opt_bool("enable_support");
    int support_threshold_angle =  glb_cfg.opt_int("support_threshold_angle");
    return  support_threshold_angle ;
}
References Slic3r::DynamicConfig::opt_bool(), and Slic3r::DynamicConfig::opt_int().
Referenced by render().
get_slope_normal_z()
float Slic3r::GLVolumeCollection::get_slope_normal_z () const inline
{ return m_slope.normal_z; }
References m_slope, and Slic3r::GLVolumeCollection::Slope::normal_z.
gpu_memory_used()
size_t Slic3r::GLVolumeCollection::gpu_memory_used () const
{
  size_t memsize = 0;
  for (const GLVolume *volume : this->volumes)
    memsize += volume->gpu_memory_used();
  return memsize;
}
References volumes.
Referenced by log_memory_info(), and total_memory_used().
is_slope_active()
bool Slic3r::GLVolumeCollection::is_slope_active () const inline
{ return m_slope.active; }
References Slic3r::GLVolumeCollection::Slope::active, and m_slope.
Referenced by Slic3r::GUI::GLCanvas3D::Slope::is_used().
is_slope_GlobalActive()
bool Slic3r::GLVolumeCollection::is_slope_GlobalActive () const inline
{ return m_slope.isGlobalActive; }
References Slic3r::GLVolumeCollection::Slope::isGlobalActive, and m_slope.
Referenced by Slic3r::GUI::GLCanvas3D::Slope::is_GlobalUsed().
load_object()
std::vector< int > Slic3r::GLVolumeCollection::load_object (const ModelObject * model_object, int obj_idx, const std::vector< int > & instance_idxs, const std::string & color_by, bool opengl_initialized)
{
    std::vector<int> volumes_idx;
    for (int volume_idx = 0; volume_idx < int(model_object->volumes.size()); ++volume_idx)
        for (int instance_idx : instance_idxs)
            volumes_idx.emplace_back(this->GLVolumeCollection::load_object_volume(model_object, obj_idx, volume_idx, instance_idx, color_by, opengl_initialized));
    return volumes_idx;
}
References int, and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::GLCanvas3D::load_object(), and Slic3r::GUI::GCodeViewer::load_shells().
load_object_auxiliary()
void Slic3r::GLVolumeCollection::load_object_auxiliary (const SLAPrintObject * print_object, int obj_idx, const std::vector< std::pair< size_t, size_t > > & instances, SLAPrintObjectStep milestone, size_t timestamp, bool opengl_initialized)
{
    assert(print_object->is_step_done(milestone));
    Transform3d  mesh_trafo_inv = print_object->trafo().inverse();
    // Get the support mesh.
    TriangleMesh mesh = print_object->get_mesh(milestone);
    mesh.transform(mesh_trafo_inv);
    // Convex hull is required for out of print bed detection.
    TriangleMesh convex_hull = mesh.convex_hull_3d();
    for (const std::pair<size_t, size_t>& instance_idx : instances) {
        const ModelInstance& model_instance = *print_object->model_object()->instances[instance_idx.first];
        this->volumes.emplace_back(new GLVolume((milestone == slaposPad) ? GLVolume::SLA_PAD_COLOR : GLVolume::SLA_SUPPORT_COLOR));
        GLVolume& v = *this->volumes.back();
#if ENABLE_SMOOTH_NORMALS
        v.indexed_vertex_array.load_mesh(mesh, true);
#else
        v.indexed_vertex_array.load_mesh(mesh);
#endif // ENABLE_SMOOTH_NORMALS
        v.indexed_vertex_array.finalize_geometry(opengl_initialized);
        v.composite_id = GLVolume::CompositeID(obj_idx, -int(milestone), (int)instance_idx.first);
        v.geometry_id = std::pair<size_t, size_t>(timestamp, model_instance.id().id);
        // Create a copy of the convex hull mesh for each instance. Use a move operator on the last instance.
        if (&instance_idx == &instances.back())
            v.set_convex_hull(std::move(convex_hull));
        else
            v.set_convex_hull(convex_hull);
        v.is_modifier = false;
        v.shader_outside_printer_detection_enabled = (milestone == slaposSupportTree);
        v.set_instance_transformation(model_instance.get_transformation());
        // Leave the volume transformation at identity.
        // v.set_volume_transformation(model_volume->get_transformation());
    }
}
References Slic3r::GLVolume::composite_id, Slic3r::TriangleMesh::convex_hull_3d(), Slic3r::GLIndexedVertexArray::finalize_geometry(), Slic3r::GLVolume::geometry_id, Slic3r::SLAPrintObject::get_mesh(), Slic3r::ModelInstance::get_transformation(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), Slic3r::GLVolume::indexed_vertex_array, Slic3r::ModelObject::instances, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::is_step_done(), Slic3r::GLIndexedVertexArray::load_mesh(), Slic3r::PrintObjectBase::model_object(), Slic3r::GLVolume::set_convex_hull(), Slic3r::GLVolume::set_instance_transformation(), Slic3r::GLVolume::SLA_PAD_COLOR, Slic3r::GLVolume::SLA_SUPPORT_COLOR, Slic3r::slaposPad, Slic3r::slaposSupportTree, Slic3r::SLAPrintObject::trafo(), Slic3r::TriangleMesh::transform(), and volumes.
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene().
load_object_volume()
int Slic3r::GLVolumeCollection::load_object_volume (const ModelObject * model_object, int obj_idx, int volume_idx, int instance_idx, const std::string & color_by, bool opengl_initialized, bool in_assemble_view = false, bool use_loaded_id = false)
{
    const ModelVolume   *model_volume = model_object->volumes[volume_idx];
    const int            extruder_id  = model_volume->extruder_id();
    const ModelInstance *instance     = model_object->instances[instance_idx];
    const TriangleMesh  &mesh       = model_volume->mesh();
    std::array<float, 4> color = GLVolume::MODEL_COLOR[((color_by == "volume") ? volume_idx : obj_idx) % 4];
    color[3] = model_volume->is_model_part() ? 0.7f : 0.4f;
    this->volumes.emplace_back(new GLVolume(color));
    GLVolume& v = *this->volumes.back();
    v.set_color(color_from_model_volume(*model_volume));
    v.name = model_volume->name;
#if ENABLE_SMOOTH_NORMALS
    v.indexed_vertex_array.load_mesh(mesh, true);
#else
    v.indexed_vertex_array.load_mesh(mesh);
#endif // ENABLE_SMOOTH_NORMALS
    v.indexed_vertex_array.finalize_geometry(opengl_initialized);
    v.composite_id = GLVolume::CompositeID(obj_idx, volume_idx, instance_idx);
    if (model_volume->is_model_part())
    {
        // GLVolume will reference a convex hull from model_volume!
        v.set_convex_hull(model_volume->get_convex_hull_shared_ptr());
        if (extruder_id != -1)
            v.extruder_id = extruder_id;
    }
    v.is_modifier = !model_volume->is_model_part();
    v.shader_outside_printer_detection_enabled = model_volume->is_model_part();
    if (in_assemble_view) {
        v.set_instance_transformation(instance->get_assemble_transformation());
        v.set_offset_to_assembly(instance->get_offset_to_assembly());
    }
    else
        v.set_instance_transformation(instance->get_transformation());
    v.set_volume_transformation(model_volume->get_transformation());
    //use object's instance id
    if (use_loaded_id && (instance->loaded_id > 0))
        v.model_object_ID = instance->loaded_id;
    else
        v.model_object_ID = instance->id().id;
    return int(this->volumes.size() - 1);
}
References Slic3r::color_from_model_volume(), Slic3r::GLVolume::composite_id, Slic3r::ModelVolume::extruder_id(), Slic3r::GLVolume::extruder_id, Slic3r::GLIndexedVertexArray::finalize_geometry(), Slic3r::ModelInstance::get_assemble_transformation(), Slic3r::ModelVolume::get_convex_hull_shared_ptr(), Slic3r::ModelInstance::get_offset_to_assembly(), Slic3r::ModelVolume::get_transformation(), Slic3r::ModelInstance::get_transformation(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), Slic3r::GLVolume::indexed_vertex_array, Slic3r::ModelObject::instances, int, Slic3r::ModelVolume::is_model_part(), Slic3r::GLIndexedVertexArray::load_mesh(), Slic3r::ModelInstance::loaded_id, Slic3r::ModelVolume::mesh(), Slic3r::GLVolume::MODEL_COLOR, Slic3r::GLVolume::model_object_ID, Slic3r::ModelVolume::name, Slic3r::GLVolume::name, Slic3r::GLVolume::set_color(), Slic3r::GLVolume::set_convex_hull(), Slic3r::GLVolume::set_instance_transformation(), Slic3r::GLVolume::set_offset_to_assembly(), Slic3r::GLVolume::set_volume_transformation(), Slic3r::ModelObject::volumes, and volumes.
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene(), and Slic3r::CLI::run().
load_wipe_tower_preview()
int Slic3r::GLVolumeCollection::load_wipe_tower_preview (int obj_idx, float pos_x, float pos_y, float width, float depth, float height, float rotation_angle, bool size_unknown, float brim_width, bool opengl_initialized)
{
    int plate_idx = obj_idx - 1000;
    if (depth < 0.01f)
        return int(this->volumes.size() - 1);
    if (height == 0.0f)
        height = 0.1f;
    std::vector<std::array<float, 4>> extruder_colors = get_extruders_colors();
    std::vector<std::array<float, 4>> colors;
    GUI::PartPlateList& ppl = GUI::wxGetApp().plater()->get_partplate_list();
    std::vector<int> plate_extruders = ppl.get_plate(plate_idx)->get_extruders(true);
    TriangleMesh wipe_tower_shell = make_cube(width, depth, height);
    for (int extruder_id : plate_extruders) {
        if (extruder_id <= extruder_colors.size())
            colors.push_back(extruder_colors[extruder_id - 1]);
        else
            colors.push_back(extruder_colors[0]);
    }
#if 0
    // We'll make another mesh to show the brim (fixed layer height):
    TriangleMesh brim_mesh = make_cube(width + 2.f * brim_width, depth + 2.f * brim_width, 0.2f);
    brim_mesh.translate(-brim_width, -brim_width, 0.f);
    mesh.merge(brim_mesh);
#endif
    volumes.emplace_back(new GLWipeTowerVolume(colors));
    GLWipeTowerVolume& v = *dynamic_cast<GLWipeTowerVolume*>(volumes.back());
    v.iva_per_colors.resize(colors.size());
    for (int i = 0; i < colors.size(); i++) {
        TriangleMesh color_part = make_cube(width, depth / colors.size(), height);
        color_part.translate({ 0.f, depth * i / colors.size(), 0. });
        v.iva_per_colors[i].load_mesh(color_part);
        v.iva_per_colors[i].finalize_geometry(opengl_initialized);
    }
    v.indexed_vertex_array.load_mesh(wipe_tower_shell);
    v.indexed_vertex_array.finalize_geometry(opengl_initialized);
    v.set_convex_hull(wipe_tower_shell);
    v.set_volume_offset(Vec3d(pos_x, pos_y, 0.0));
    v.set_volume_rotation(Vec3d(0., 0., (M_PI / 180.) * rotation_angle));
    v.composite_id = GLVolume::CompositeID(obj_idx, 0, 0);
    v.geometry_id.first = 0;
    v.geometry_id.second = wipe_tower_instance_id().id + (obj_idx - 1000);
    v.is_wipe_tower = true;
    v.shader_outside_printer_detection_enabled = !size_unknown;
    return int(volumes.size() - 1);
}
References Slic3r::GLVolume::composite_id, Slic3r::GLIndexedVertexArray::finalize_geometry(), Slic3r::GLVolume::geometry_id, Slic3r::GUI::PartPlate::get_extruders(), get_extruders_colors(), Slic3r::GUI::PartPlateList::get_plate(), Slic3r::ObjectID::id, Slic3r::GLVolume::indexed_vertex_array, int, Slic3r::GLWipeTowerVolume::iva_per_colors, Slic3r::GLIndexedVertexArray::load_mesh(), M_PI, Slic3r::make_cube(), Slic3r::TriangleMesh::merge(), Slic3r::GLVolume::set_convex_hull(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_rotation(), Slic3r::TriangleMesh::translate(), volumes, and Slic3r::wipe_tower_instance_id().
Referenced by Slic3r::GUI::GCodeViewer::load_shells(), and Slic3r::GUI::GLCanvas3D::reload_scene().
log_memory_info()
std::string Slic3r::GLVolumeCollection::log_memory_info () const
{
  return " (GLVolumeCollection RAM: " + format_memsize_MB(this->cpu_memory_used()) + " GPU: " + format_memsize_MB(this->gpu_memory_used()) + " Both: " + format_memsize_MB(this->gpu_memory_used()) + ")";
}
References cpu_memory_used(), Slic3r::format_memsize_MB(), and gpu_memory_used().
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths().
new_nontoolpath_volume()
GLVolume * Slic3r::GLVolumeCollection::new_nontoolpath_volume (const std::array< float, 4 > & rgba, size_t reserve_vbo_floats = 0)
{
  GLVolume *out = new GLVolume(rgba);
  out->is_extrusion_path = false;
  // Reserving number of vertices (3x position + 3x color)
  out->indexed_vertex_array.reserve(reserve_vbo_floats / 6);
  this->volumes.emplace_back(out);
  return out;
}
References out, and volumes.
Referenced by new_toolpath_volume().
new_toolpath_volume()
GLVolume * Slic3r::GLVolumeCollection::new_toolpath_volume (const std::array< float, 4 > & rgba, size_t reserve_vbo_floats = 0)
{
  GLVolume *out = new_nontoolpath_volume(rgba, reserve_vbo_floats);
  out->is_extrusion_path = true;
  return out;
}
References new_nontoolpath_volume(), and out.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths().
operator=()
GLVolumeCollection & Slic3r::GLVolumeCollection::operator= (const GLVolumeCollection &) private
release_geometry()
void Slic3r::GLVolumeCollection::release_geometry () inline
{ for (auto *v : volumes) v->release_geometry(); }
References volumes.
render()
void Slic3r::GLVolumeCollection::render (GLVolumeCollection::ERenderType type, bool disable_cullface, const Transform3d & view_matrix, std::function< bool(const GLVolume &)> filter_func = std::function<bool(const GLVolume &)>(), bool with_outline = true) const
{
    GLVolumeWithIdAndZList to_render = volumes_to_render(volumes, type, view_matrix, filter_func);
    if (to_render.empty())
        return;
    GLShaderProgram* shader = GUI::wxGetApp().get_current_shader();
    if (shader == nullptr)
        return;
    if (type == ERenderType::Transparent) {
        glsafe(::glEnable(GL_BLEND));
        glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    }
    glsafe(::glCullFace(GL_BACK));
    if (disable_cullface)
        glsafe(::glDisable(GL_CULL_FACE));
    for (GLVolumeWithIdAndZ& volume : to_render) {
#if ENABLE_MODIFIERS_ALWAYS_TRANSPARENT
        if (type == ERenderType::Transparent) {
            volume.first->force_transparent = true;
            //BOOST_LOG_TRIVIAL(info) << boost::format("transparent rendering...");
        }
        //else
        //    BOOST_LOG_TRIVIAL(info) << boost::format("opaque rendering...");
#endif // ENABLE_MODIFIERS_ALWAYS_TRANSPARENT
        volume.first->set_render_color();
#if ENABLE_MODIFIERS_ALWAYS_TRANSPARENT
        if (type == ERenderType::Transparent)
            volume.first->force_transparent = false;
#endif // ENABLE_MODIFIERS_ALWAYS_TRANSPARENT
        // render sinking contours of non-hovered volumes
        if (m_show_sinking_contours)
            if (volume.first->is_sinking() && !volume.first->is_below_printbed() &&
                volume.first->hover == GLVolume::HS_None && !volume.first->force_sinking_contours) {
                shader->stop_using();
                volume.first->render_sinking_contours();
                shader->start_using();
            }
        glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
        glsafe(::glEnableClientState(GL_NORMAL_ARRAY));
        shader->set_uniform("uniform_color", volume.first->render_color);
        shader->set_uniform("z_range", m_z_range, 2);
        shader->set_uniform("clipping_plane", m_clipping_plane, 4);
        //BOOST_LOG_TRIVIAL(info) << boost::format("set uniform_color to {%1%, %2%, %3%, %4%}, with_outline=%5%, selected %6%")
        //    %volume.first->render_color[0]%volume.first->render_color[1]%volume.first->render_color[2]%volume.first->render_color[3]
        //    %with_outline%volume.first->selected;
        //BBS set print_volume to render volume
        //shader->set_uniform("print_volume.type", static_cast<int>(m_render_volume.type));
        //shader->set_uniform("print_volume.xy_data", m_render_volume.data);
        //shader->set_uniform("print_volume.z_data", m_render_volume.zs);
        if (volume.first->partly_inside) {
            //only partly inside volume need to be painted with boundary check
            shader->set_uniform("print_volume.type", static_cast<int>(m_print_volume.type));
            shader->set_uniform("print_volume.xy_data", m_print_volume.data);
            shader->set_uniform("print_volume.z_data", m_print_volume.zs);
        }
        else {
            //use -1 ad a invalid type
            shader->set_uniform("print_volume.type", -1);
        }
        bool  enable_support;
        int   support_threshold_angle = get_selection_support_threshold_angle(enable_support);
        float normal_z  = -::cos(Geometry::deg2rad((float) support_threshold_angle));
        shader->set_uniform("volume_world_matrix", volume.first->world_matrix());
        shader->set_uniform("slope.actived", m_slope.isGlobalActive && !volume.first->is_modifier && !volume.first->is_wipe_tower);
        shader->set_uniform("slope.volume_world_normal_matrix", static_cast<Matrix3f>(volume.first->world_matrix().matrix().block(0, 0, 3, 3).inverse().transpose().cast<float>()));
        shader->set_uniform("slope.normal_z", normal_z);
#if ENABLE_ENVIRONMENT_MAP
        unsigned int environment_texture_id = GUI::wxGetApp().plater()->get_environment_texture_id();
        bool use_environment_texture = environment_texture_id > 0 && GUI::wxGetApp().app_config->get("use_environment_map") == "1";
        shader->set_uniform("use_environment_tex", use_environment_texture);
        if (use_environment_texture)
            glsafe(::glBindTexture(GL_TEXTURE_2D, environment_texture_id));
#endif // ENABLE_ENVIRONMENT_MAP
        glcheck();
        //BBS: add outline related logic
        volume.first->render(with_outline && volume.first->selected);
#if ENABLE_ENVIRONMENT_MAP
        if (use_environment_texture)
            glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
#endif // ENABLE_ENVIRONMENT_MAP
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
        glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
        glsafe(::glDisableClientState(GL_NORMAL_ARRAY));
    }
    if (m_show_sinking_contours) {
        for (GLVolumeWithIdAndZ& volume : to_render) {
            // render sinking contours of hovered/displaced volumes
            if (volume.first->is_sinking() && !volume.first->is_below_printbed() &&
                (volume.first->hover != GLVolume::HS_None || volume.first->force_sinking_contours)) {
                shader->stop_using();
                glsafe(::glDepthFunc(GL_ALWAYS));
                volume.first->render_sinking_contours();
                glsafe(::glDepthFunc(GL_LESS));
                shader->start_using();
            }
        }
    }
    if (disable_cullface)
        glsafe(::glEnable(GL_CULL_FACE));
    if (type == ERenderType::Transparent)
        glsafe(::glDisable(GL_BLEND));
}
References cos(), Slic3r::GLVolumeCollection::PrintVolume::data, Slic3r::Geometry::deg2rad(), get_selection_support_threshold_angle(), glcheck, glsafe, Slic3r::GLVolume::HS_None, Slic3r::GLVolumeCollection::Slope::isGlobalActive, m_clipping_plane, m_print_volume, m_show_sinking_contours, m_slope, m_z_range, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Transparent, Slic3r::GLVolumeCollection::PrintVolume::type, volumes, Slic3r::volumes_to_render(), and Slic3r::GLVolumeCollection::PrintVolume::zs.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects(), and Slic3r::GUI::GCodeViewer::render_shells().
reset_outside_state()
void Slic3r::GLVolumeCollection::reset_outside_state ()
{
    for (GLVolume* volume : this->volumes)
    {
        if (volume != nullptr) {
            volume->is_outside = false;
            volume->partly_inside = false;
        }
    }
}
References volumes.
set_clipping_plane()
void Slic3r::GLVolumeCollection::set_clipping_plane (const double * coeffs) inline
{ m_clipping_plane[0] = coeffs[0]; m_clipping_plane[1] = coeffs[1]; m_clipping_plane[2] = coeffs[2]; m_clipping_plane[3] = coeffs[3]; }
References m_clipping_plane.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
set_default_slope_normal_z()
void Slic3r::GLVolumeCollection::set_default_slope_normal_z () inline
{ m_slope.normal_z = -::cos(Geometry::deg2rad(90.0f - 45.0f)); }
References cos(), Slic3r::Geometry::deg2rad(), m_slope, and Slic3r::GLVolumeCollection::Slope::normal_z.
Referenced by GLVolumeCollection().
set_print_volume()
void Slic3r::GLVolumeCollection::set_print_volume (const PrintVolume & print_volume) inline
{ m_print_volume = print_volume; }
References m_print_volume.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
set_range()
void Slic3r::GLVolumeCollection::set_range (double low, double high) inline
{ for (GLVolume *vol : this->volumes) vol->set_range(low, high); }
References volumes.
Referenced by Slic3r::GUI::GLCanvas3D::set_volumes_z_range().
set_show_sinking_contours()
void Slic3r::GLVolumeCollection::set_show_sinking_contours (bool show) inline
{ m_show_sinking_contours = show; }
References m_show_sinking_contours.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
set_slope_active()
void Slic3r::GLVolumeCollection::set_slope_active (bool active) inline
{ m_slope.active = active; }
References Slic3r::GLVolumeCollection::Slope::active, and m_slope.
Referenced by Slic3r::GUI::GLCanvas3D::Slope::use().
set_slope_GlobalActive()
void Slic3r::GLVolumeCollection::set_slope_GlobalActive (bool active) inline
{ m_slope.isGlobalActive = active; }
References Slic3r::GLVolumeCollection::Slope::isGlobalActive, and m_slope.
Referenced by Slic3r::GUI::GLCanvas3D::Slope::globalUse().
set_slope_normal_z()
void Slic3r::GLVolumeCollection::set_slope_normal_z (float normal_z) inline
{ m_slope.normal_z = normal_z; }
References m_slope, and Slic3r::GLVolumeCollection::Slope::normal_z.
Referenced by Slic3r::GUI::GLCanvas3D::Slope::set_normal_angle().
set_z_range()
void Slic3r::GLVolumeCollection::set_z_range (float min_z, float max_z) inline
{ m_z_range[0] = min_z; m_z_range[1] = max_z; }
References m_z_range.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
total_memory_used()
size_t Slic3r::GLVolumeCollection::total_memory_used () const inline
{ return this->cpu_memory_used() + this->gpu_memory_used(); }
References cpu_memory_used(), and gpu_memory_used().
update_colors_by_extruder()
void Slic3r::GLVolumeCollection::update_colors_by_extruder (const DynamicPrintConfig * config, bool is_update_alpha = true)
{
    static const float inv_255 = 1.0f / 255.0f;
    struct Color
    {
        std::string text;
        unsigned char rgba[4];
        Color()
            : text("")
        {
            rgba[0] = 255;
            rgba[1] = 255;
            rgba[2] = 255;
            rgba[3] = 255;
        }
        void set(const std::string& text, unsigned char* rgba)
        {
            this->text = text;
            ::memcpy((void*)this->rgba, (const void*)rgba, 4 * sizeof(unsigned char));
        }
    };
    if (config == nullptr)
        return;
    unsigned char rgba[4];
    std::vector<Color> colors;
    if (static_cast<PrinterTechnology>(config->opt_int("printer_technology")) == ptSLA)
    {
        const std::string& txt_color = config->opt_string("material_colour").empty() ?
                                       print_config_def.get("material_colour")->get_default_value<ConfigOptionString>()->value :
                                       config->opt_string("material_colour");
        if (Slic3r::GUI::BitmapCache::parse_color4(txt_color, rgba)) {
            colors.resize(1);
            colors[0].set(txt_color, rgba);
        }
    }
    else
    {
        const ConfigOptionStrings* filamemts_opt = dynamic_cast<const ConfigOptionStrings*>(config->option("filament_colour"));
        if (filamemts_opt == nullptr)
            return;
        unsigned int colors_count = (unsigned int)filamemts_opt->values.size();
        if (colors_count == 0)
            return;
        colors.resize(colors_count);
        for (unsigned int i = 0; i < colors_count; ++i) {
            const std::string& txt_color = config->opt_string("filament_colour", i);
            if (Slic3r::GUI::BitmapCache::parse_color4(txt_color, rgba))
                colors[i].set(txt_color, rgba);
        }
    }
    for (GLVolume* volume : volumes) {
        if (volume == nullptr || volume->is_modifier || volume->is_wipe_tower || (volume->volume_idx() < 0))
            continue;
        int extruder_id = volume->extruder_id - 1;
        if (extruder_id < 0 || (int)colors.size() <= extruder_id)
            extruder_id = 0;
        const Color& color = colors[extruder_id];
        if (!color.text.empty()) {
            for (int i = 0; i < 4; ++i) {
                if (is_update_alpha == false) {
                    if (i < 3) {
                        volume->color[i] = (float) color.rgba[i] * inv_255;
                    }
                    continue;
                }
                volume->color[i] = (float) color.rgba[i] * inv_255;
            }
        }
    }
}
References Slic3r::ConfigDef::get(), Slic3r::ConfigOptionDef::get_default_value(), int, memcpy, Slic3r::DynamicConfig::opt_int(), Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), Slic3r::GUI::BitmapCache::parse_color4(), Slic3r::print_config_def, Slic3r::ptSLA, Slic3r::ConfigOptionVector< T >::values, and volumes.
Referenced by Slic3r::GUI::GCodeViewer::update_shells_color_by_extruder(), and Slic3r::GUI::GLCanvas3D::update_volumes_colors_by_extruder().
Member Data Documentation
m_clipping_plane
float Slic3r::GLVolumeCollection::m_clipping_plane[4] private
Referenced by render(), and set_clipping_plane().
m_print_volume
PrintVolume Slic3r::GLVolumeCollection::m_print_volume private
Referenced by render(), and set_print_volume().
m_render_volume
PrintVolume Slic3r::GLVolumeCollection::m_render_volume private
Referenced by GLVolumeCollection().
m_show_sinking_contours
bool Slic3r::GLVolumeCollection::m_show_sinking_contours = false private
Referenced by render(), and set_show_sinking_contours().
m_slope
Slope Slic3r::GLVolumeCollection::m_slope private
Referenced by get_slope_normal_z(), is_slope_active(), is_slope_GlobalActive(), render(), set_default_slope_normal_z(), set_slope_active(), set_slope_GlobalActive(), and set_slope_normal_z().
m_z_range
float Slic3r::GLVolumeCollection::m_z_range[2] private
Referenced by render(), and set_z_range().
volumes
GLVolumePtrs Slic3r::GLVolumeCollection::volumes
Referenced by Slic3r::GUI::GLCanvas3D::GLCanvas3D(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_volumes_for_picking(), Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), check_outside_state(), clear(), cpu_memory_used(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), empty(), Slic3r::GUI::GLCanvas3D::ensure_on_bed(), finalize_geometry(), get_current_print_zs(), Slic3r::GUI::GLCanvas3D::get_volumes_count(), Slic3r::GUI::GLCanvas3D::get_wipe_tower_info(), gpu_memory_used(), Slic3r::GUI::GLCanvas3D::is_object_sinking(), load_object_auxiliary(), load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), load_wipe_tower_preview(), new_nontoolpath_volume(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::on_mouse_wheel(), release_geometry(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::Labels::render(), render(), Slic3r::GUI::GCodeViewer::render_shells(), Slic3r::GUI::GLCanvas3D::render_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_volumes(), reset_outside_state(), Slic3r::CLI::run(), set_range(), Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility(), Slic3r::GUI::GLCanvas3D::toggle_sla_auxiliaries_visibility(), update_colors_by_extruder(), Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_object(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), and Slic3r::GUI::GLCanvas3D::volumes_bounding_box().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DScene.hpp
src/slic3r/GUI/3DScene.cpp