OrcaSlicer: orgQhull::CoordinatesIterator Class Reference
orgQhull::CoordinatesIterator Class Reference
#include <src/qhull/src/libqhullcpp/Coordinates.h>
Public Member Functions
CoordinatesIterator (const Coordinates &container)
CoordinatesIterator & operator= (const Coordinates &container)
~CoordinatesIterator ()
bool findNext (const coordT &t)
bool findPrevious (const coordT &t)
bool hasNext () const
bool hasPrevious () const
const coordT & next ()
const coordT & previous ()
const coordT & peekNext () const
const coordT & peekPrevious () const
void toFront ()
void toBack ()
Private Types
typedef Coordinates::const_iterator const_iterator
Private Attributes
const Coordinates * c
const_iterator i
Detailed Description
Member Typedef Documentation
const_iterator
typedef Coordinates::const_iterator orgQhull::CoordinatesIterator::const_iterator private
Constructor & Destructor Documentation
CoordinatesIterator()
orgQhull::CoordinatesIterator::CoordinatesIterator (const Coordinates & container) inline
: c(&container), i(c->constBegin()) {}
~CoordinatesIterator()
orgQhull::CoordinatesIterator::~CoordinatesIterator () inline
{}
Member Function Documentation
findNext()
bool orgQhull::CoordinatesIterator::findNext (const coordT & t) inline
{ while (i != c->constEnd()) if(*i++ == t){ return true;} return false; }
References c, orgQhull::Coordinates::constEnd(), and i.
Referenced by orgQhull::Coordinates::contains(), orgQhull::Coordinates::count(), and orgQhull::Coordinates_test::t_coord_iterator().
findPrevious()
bool orgQhull::CoordinatesIterator::findPrevious (const coordT & t) inline
{ while (i != c->constBegin())if (*(--i) == t){ return true;} return false;  }
References c, orgQhull::Coordinates::constBegin(), and i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
hasNext()
bool orgQhull::CoordinatesIterator::hasNext () const inline
{ return i != c->constEnd(); }
References c, orgQhull::Coordinates::constEnd(), and i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
hasPrevious()
bool orgQhull::CoordinatesIterator::hasPrevious () const inline
{ return i != c->constBegin(); }
References c, orgQhull::Coordinates::constBegin(), and i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
next()
const coordT & orgQhull::CoordinatesIterator::next () inline
{ return *i++; }
References i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
operator=()
CoordinatesIterator & orgQhull::CoordinatesIterator::operator= (const Coordinates & container) inline
{ c= &container; i= c->constBegin(); return *this; }
References c, orgQhull::Coordinates::constBegin(), and i.
peekNext()
const coordT & orgQhull::CoordinatesIterator::peekNext () const inline
{ return *i; }
References i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
peekPrevious()
const coordT & orgQhull::CoordinatesIterator::peekPrevious () const inline
{ const_iterator p= i; return *--p; }
References i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
previous()
const coordT & orgQhull::CoordinatesIterator::previous () inline
{ return *--i; }
References i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
toBack()
void orgQhull::CoordinatesIterator::toBack () inline
{ i= c->constEnd(); }
References c, orgQhull::Coordinates::constEnd(), and i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
toFront()
void orgQhull::CoordinatesIterator::toFront () inline
{ i= c->constBegin(); }
References c, orgQhull::Coordinates::constBegin(), and i.
Referenced by orgQhull::Coordinates_test::t_coord_iterator().
Member Data Documentation
c
const Coordinates* orgQhull::CoordinatesIterator::c private
Referenced by findNext(), findPrevious(), hasNext(), hasPrevious(), operator=(), toBack(), and toFront().
i
const_iterator orgQhull::CoordinatesIterator::i private
Referenced by findNext(), findPrevious(), hasNext(), hasPrevious(), next(), operator=(), peekNext(), peekPrevious(), previous(), toBack(), and toFront().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/Coordinates.h