OrcaSlicer: Slic3r::GUI::AuFile Class Reference
Slic3r::GUI::AuFile Class Reference
#include <src/slic3r/GUI/Auxiliary.hpp>
Public Member Functions
AuFile (wxWindow *parent, fs::path file_path, wxString file_name, AuxiliaryFolderType type, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void enter_rename_mode ()
void exit_rename_mode ()
void OnPaint (wxPaintEvent &evt)
void PaintBackground (wxDC &dc)
void OnEraseBackground (wxEraseEvent &evt)
void PaintForeground (wxDC &dc)
void on_mouse_enter (wxMouseEvent &evt)
void on_mouse_leave (wxMouseEvent &evt)
void on_input_enter (wxCommandEvent &evt)
void on_dclick (wxMouseEvent &evt)
void on_mouse_left_up (wxMouseEvent &evt)
void on_set_cover ()
void on_set_delete ()
void on_set_rename ()
void on_set_open ()
void set_cover (bool cover)
void msw_rescale ()
~AuFile ()
Public Attributes
AuxiliaryFolderType m_type
bool m_hover {false}
bool m_cover {false}
wxStaticText * m_text_name {nullptr}
::TextInput * m_input_name {nullptr}
fs::path m_file_path
wxString m_add_file
wxString m_file_name
wxString cover_text_left
wxString cover_text_right
wxString cover_text_cover
ScalableBitmap m_file_bitmap
ScalableBitmap m_file_cover
ScalableBitmap m_file_edit_mask
ScalableBitmap m_file_delete
wxStaticBitmap * m_file_exit_rename
ScalableBitmap m_bitmap_excel
ScalableBitmap m_bitmap_pdf
ScalableBitmap m_bitmap_txt
Detailed Description
Constructor & Destructor Documentation
AuFile()
Slic3r::GUI::AuFile::AuFile (wxWindow * parent, fs::path file_path, wxString file_name, AuxiliaryFolderType type, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
{
    m_type      = type;
    m_file_path = file_path;
    m_file_name = file_name;
    wxSize panel_size = m_type == MODEL_PICTURE ? AUFILE_PICTURES_PANEL_SIZE : AUFILE_PANEL_SIZE;
    wxPanel::Create(parent, id, pos, panel_size, style);
    SetBackgroundColour(StateColor::darkModeColorFor(AUFILE_GREY300));
    wxBoxSizer *sizer_body = new wxBoxSizer(wxVERTICAL);
   SetSize(panel_size);
    if (m_type == MODEL_PICTURE) {
        if (m_file_path.empty()) { return; }
        auto image = new wxImage(encode_path(m_file_path.string().c_str()));
        //constrain
        auto size = wxSize(0, 0);
        float proportion = float(image->GetSize().x) / float(image->GetSize().y);
        if (proportion >= 1) {
            size.x = AUFILE_PICTURES_SIZE.x;
            size.y = AUFILE_PICTURES_SIZE.x / proportion;
        } else {
            size.y = AUFILE_PICTURES_SIZE.y;
            size.x = AUFILE_PICTURES_SIZE.y * proportion;
        }
        image->Rescale(size.x, size.y);
        m_file_bitmap.bmp() = wxBitmap(*image);
    } else {
        m_bitmap_excel = ScalableBitmap(this, "placeholder_excel", 168);
        m_bitmap_pdf   = ScalableBitmap(this, "placeholder_pdf", 168);
        m_bitmap_txt   = ScalableBitmap(this, "placeholder_txt", 168);
        if (m_type == OTHERS) {m_file_bitmap = m_bitmap_txt;}
        if (m_type == BILL_OF_MATERIALS) {
            if (m_file_path.extension() == ".xls" || m_file_path.extension() == ".xlsx") {
                m_file_bitmap = m_bitmap_excel;
            }
            if (m_file_path.extension() == ".pdf") { m_file_bitmap = m_bitmap_pdf; }
        }
        if (m_type == ASSEMBLY_GUIDE) {m_file_bitmap = m_bitmap_pdf;}
    }
    m_add_file = _L("Add File");
    cover_text_left  = _L("Set as cover");
    cover_text_right = _L("Rename");
    cover_text_cover = _L("Cover");
    m_file_cover     = ScalableBitmap(this, "auxiliary_cover", 40);
    m_file_edit_mask = ScalableBitmap(this, "auxiliary_edit_mask", 30);
    m_file_delete    = ScalableBitmap(this, "auxiliary_delete", 20);
    auto m_text_panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(panel_size.x, AUFILE_TEXT_HEIGHT), wxTAB_TRAVERSAL);
    m_text_panel->SetBackgroundColour(StateColor::darkModeColorFor(AUFILE_GREY300));
    wxBoxSizer *m_text_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_text_name              = new wxStaticText(m_text_panel, wxID_ANY, m_file_name, wxDefaultPosition, wxSize(panel_size.x, -1), wxST_ELLIPSIZE_END);
    m_text_name->Wrap(panel_size.x - FromDIP(10));
    m_text_name->SetFont(::Label::Body_14);
    m_text_name->SetForegroundColour(StateColor::darkModeColorFor(*wxBLACK));
    m_input_name = new ::TextInput(m_text_panel, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, wxSize(panel_size.x - FromDIP(28), FromDIP(32)), wxTE_PROCESS_ENTER);
    m_input_name->GetTextCtrl()->SetFont(::Label::Body_13);
    m_input_name->SetFont(::Label::Body_14);
    m_input_name->Hide();
    m_file_exit_rename = new wxStaticBitmap(m_text_panel, wxID_ANY, create_scaled_bitmap("auxiliary_delete", this, 20), wxDefaultPosition, wxSize(FromDIP(20), FromDIP(20)), 0);
    m_file_exit_rename->Bind(wxEVT_LEFT_UP, [this](auto& e) {
        exit_rename_mode();
    });
    m_text_sizer->Add(0, 0, 1, wxEXPAND, 0);
    m_text_sizer->Add(m_text_name, 0, wxALIGN_CENTER, 0);
    m_text_sizer->Add(m_input_name, 0, wxALIGN_CENTER, 0);
    m_text_sizer->Add( 0, 0, 1, wxEXPAND, 0 );
    m_text_sizer->Add(m_file_exit_rename, 0, wxALIGN_CENTER, 0);
    m_file_exit_rename->Hide();
    m_text_panel->SetSizer(m_text_sizer);
    m_text_panel->Layout();
    sizer_body->Add(0, 0, 0, wxTOP, panel_size.y - AUFILE_TEXT_HEIGHT);
    sizer_body->Add(m_text_panel, 0, wxALIGN_CENTER, 0);
    SetSizer(sizer_body);
    Layout();
    Fit();
    Bind(wxEVT_PAINT, &AuFile::OnPaint, this);
    Bind(wxEVT_ERASE_BACKGROUND, &AuFile::OnEraseBackground, this);
    Bind(wxEVT_ENTER_WINDOW, &AuFile::on_mouse_enter, this);
    Bind(wxEVT_LEAVE_WINDOW, &AuFile::on_mouse_leave, this);
    Bind(wxEVT_LEFT_UP, &AuFile::on_mouse_left_up, this);
    Bind(wxEVT_LEFT_DCLICK, &AuFile::on_dclick, this);
    m_input_name->Bind(wxEVT_TEXT_ENTER, &AuFile::on_input_enter, this);
}
References _L, ASSEMBLY_GUIDE, AUFILE_GREY300, AUFILE_PANEL_SIZE, AUFILE_PICTURES_PANEL_SIZE, AUFILE_PICTURES_SIZE, AUFILE_TEXT_HEIGHT, BILL_OF_MATERIALS, ScalableBitmap::bmp(), Label::Body_13, Label::Body_14, cover_text_cover, cover_text_left, cover_text_right, create_scaled_bitmap(), StateColor::darkModeColorFor(), Slic3r::encode_path(), exit_rename_mode(), TextInput::GetTextCtrl(), m_add_file, m_bitmap_excel, m_bitmap_pdf, m_bitmap_txt, m_file_bitmap, m_file_cover, m_file_delete, m_file_edit_mask, m_file_exit_rename, m_file_name, m_file_path, m_input_name, m_text_name, m_type, MODEL_PICTURE, on_dclick(), on_input_enter(), on_mouse_enter(), on_mouse_leave(), on_mouse_left_up(), OnEraseBackground(), OnPaint(), OTHERS, size, style, and wxStaticText.
~AuFile()
Slic3r::GUI::AuFile::~AuFile ()
{}
Member Function Documentation
enter_rename_mode()
void Slic3r::GUI::AuFile::enter_rename_mode ()
{
    m_input_name->Show();
    m_file_exit_rename->Show();
    m_text_name->Hide();
    auto name = m_file_name.SubString(0, (m_file_name.Find(".") - 1));
    m_input_name->GetTextCtrl()->SetLabelText(name);
    Layout();
}
References TextInput::GetTextCtrl(), m_file_exit_rename, m_file_name, m_input_name, and m_text_name.
Referenced by on_set_rename().
exit_rename_mode()
void Slic3r::GUI::AuFile::exit_rename_mode ()
{
    m_input_name->Hide();
    m_file_exit_rename->Hide();
    m_text_name->Show();
    Layout();
}
References m_file_exit_rename, m_input_name, and m_text_name.
Referenced by AuFile(), on_input_enter(), and on_mouse_left_up().
msw_rescale()
void Slic3r::GUI::AuFile::msw_rescale ()
{
    m_file_cover     = ScalableBitmap(this, "auxiliary_cover", 40);
    m_file_edit_mask = ScalableBitmap(this, "auxiliary_edit_mask", FromDIP(30));
    m_file_delete    = ScalableBitmap(this, "auxiliary_delete", 20);
    if (m_type == MODEL_PICTURE) {
        if (m_file_path.empty()) { return;}
        auto image = new wxImage(encode_path(m_file_path.string().c_str()));
        // constrain
        auto  size       = wxSize(0, 0);
        float proportion = float(image->GetSize().x) / float(image->GetSize().y);
        if (proportion >= 1) {
            size.x = FromDIP(300);
            size.y = FromDIP(300) / proportion;
        } else {
            size.y = FromDIP(300);
            size.x = FromDIP(300) * proportion;
        }
        image->Rescale(size.x, size.y);
        m_file_bitmap.bmp() = wxBitmap(*image);
    } else {
        m_bitmap_excel = ScalableBitmap(this, "placeholder_excel", 168);
        m_bitmap_pdf   = ScalableBitmap(this, "placeholder_pdf", 168);
        m_bitmap_txt   = ScalableBitmap(this, "placeholder_txt", 168);
        if (m_type == OTHERS) { m_file_bitmap = m_bitmap_txt; }
        if (m_type == BILL_OF_MATERIALS) { m_file_bitmap = m_bitmap_excel; }
        if (m_type == ASSEMBLY_GUIDE) { m_file_bitmap = m_bitmap_pdf; }
    }
    Refresh();
}
References ASSEMBLY_GUIDE, BILL_OF_MATERIALS, ScalableBitmap::bmp(), Slic3r::encode_path(), m_bitmap_excel, m_bitmap_pdf, m_bitmap_txt, m_file_bitmap, m_file_cover, m_file_delete, m_file_edit_mask, m_file_path, m_type, MODEL_PICTURE, OTHERS, and size.
Referenced by Slic3r::GUI::AuFolderPanel::msw_rescale().
on_dclick()
void Slic3r::GUI::AuFile::on_dclick (wxMouseEvent & evt)
{
    if (m_type == AddFileButton)
        return;
    else
        wxLaunchDefaultApplication(m_file_path.wstring(), 0);
}
References AddFileButton, m_file_path, and m_type.
Referenced by AuFile().
on_input_enter()
void Slic3r::GUI::AuFile::on_input_enter (wxCommandEvent & evt)
{
    auto     new_file_name = m_input_name->GetTextCtrl()->GetValue();
    auto     m_valid_type  = Valid;
    wxString info_line;
    const char *unusable_symbols = "<>[]:/\\|?*\"";
    const std::string unusable_suffix = PresetCollection::get_suffix_modified(); //"(modified)";
    for (size_t i = 0; i < std::strlen(unusable_symbols); i++) {
        if (new_file_name.find_first_of(unusable_symbols[i]) != std::string::npos) {
            info_line    = _L("Name is invalid;") + "\n" + _L("illegal characters:") + " " + unusable_symbols;
            m_valid_type = NoValid;
            break;
        }
    }
    if (m_valid_type == Valid && new_file_name.find(unusable_suffix) != std::string::npos) {
        info_line    = _L("Name is invalid;") + "\n" + _L("illegal suffix:") + "\n\t" + from_u8(PresetCollection::get_suffix_modified());
        m_valid_type = NoValid;
    }
    auto     existing  = false;
    auto     dir       = m_file_path.branch_path();
    auto     new_fullname = new_file_name + m_file_path.extension().string();
    wxString new_fullname_path = dir.wstring() + "/" + new_fullname;
    fs::path new_dir_path(new_fullname_path.ToStdWstring());
    if (fs::exists(new_dir_path)) existing = true;
    if (m_valid_type == Valid && existing) {
        info_line    = from_u8((boost::format(_u8L("The name \"%1%\" already exists.")) % new_file_name).str());
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.empty()) {
        info_line    = _L("The name is not allowed to be empty.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.find_first_of(' ') == 0) {
        info_line    = _L("The name is not allowed to start with space character.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.find_last_of(' ') == new_file_name.length() - 1) {
        info_line    = _L("The name is not allowed to end with space character.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid) {
        fs::path oldPath = m_file_path;
        fs::path newPath(new_dir_path);
        fs::rename(oldPath, newPath);
    } else {
        /*MessageDialog msg_wingow(nullptr, info_line, "",
                                 wxICON_WARNING | wxOK);
        if (msg_wingow.ShowModal() == wxID_CANCEL) {
            m_input_name->GetTextCtrl()->SetValue(wxEmptyString);
            return;
        }*/
        return;
    }
    // post event
    auto event = wxCommandEvent(EVT_AUXILIARY_UPDATE_RENAME);
    event.SetString(wxString::Format("%s|%s|%s", s_default_folders[m_type], m_file_path.wstring(), new_dir_path.wstring()));
    event.SetEventObject(m_parent);
    wxPostEvent(m_parent, event);
    // update layout
    m_file_path = new_dir_path.string();
    m_file_name = new_fullname;
    m_text_name->SetLabel(new_fullname);
    exit_rename_mode();
    // evt.Skip();
}
References _L, _u8L, exit_rename_mode(), Slic3r::GUI::from_u8(), Slic3r::PresetCollection::get_suffix_modified(), TextInput::GetTextCtrl(), m_file_name, m_file_path, m_input_name, m_text_name, m_type, NoValid, s_default_folders, and Valid.
Referenced by AuFile().
on_mouse_enter()
void Slic3r::GUI::AuFile::on_mouse_enter (wxMouseEvent & evt)
{
    m_hover = true;
    Refresh();
}
References m_hover.
Referenced by AuFile().
on_mouse_leave()
void Slic3r::GUI::AuFile::on_mouse_leave (wxMouseEvent & evt)
{
    m_hover = false;
    Refresh();
}
References m_hover.
Referenced by AuFile().
on_mouse_left_up()
void Slic3r::GUI::AuFile::on_mouse_left_up (wxMouseEvent & evt)
{
    if (m_type == AddFileButton) {
        return;
    }
    wxSize size = m_type == MODEL_PICTURE ? AUFILE_PICTURES_SIZE : AUFILE_SIZE;
    auto pos = evt.GetPosition();
    // set cover
    auto mask_size    = wxSize(GetSize().x, m_file_edit_mask.GetBmpSize().y);
    auto cover_left   = 0;
    auto cover_top    = size.y - mask_size.y;
    auto cover_right  = mask_size.x / 2;
    auto cover_bottom = size.y;
    if (pos.x > cover_left && pos.x < cover_right && pos.y > cover_top && pos.y < cover_bottom) {
        if(m_type == MODEL_PICTURE)
            on_set_cover();
       /* else
             on_set_rename();*/
        return;
    }
    // rename
    auto rename_left   = mask_size.x / 2;
    auto rename_top    = size.y - mask_size.y;
    auto rename_right  = mask_size.x;
    auto rename_bottom = size.y;
    if (pos.x > rename_left && pos.x < rename_right && pos.y > rename_top && pos.y < rename_bottom) { on_set_rename(); return; }
    // close
    auto close_left   = size.x - m_file_delete.GetBmpSize().x - FromDIP(10);
    auto close_top    = FromDIP(10);
    auto close_right  = size.x - FromDIP(10);
    auto close_bottom = m_file_delete.GetBmpSize().y + FromDIP(10);
    if (pos.x > close_left && pos.x < close_right && pos.y > close_top && pos.y < close_bottom) { on_set_delete(); return; }
    exit_rename_mode();
}
References AddFileButton, AUFILE_PICTURES_SIZE, AUFILE_SIZE, exit_rename_mode(), ScalableBitmap::GetBmpSize(), m_file_delete, m_file_edit_mask, m_type, MODEL_PICTURE, on_set_cover(), on_set_delete(), on_set_rename(), and size.
Referenced by AuFile().
on_set_cover()
void Slic3r::GUI::AuFile::on_set_cover ()
{
    if (wxGetApp().plater()->model().model_info == nullptr) { wxGetApp().plater()->model().model_info = std::make_shared<ModelInfo>(); }
    fs::path path(into_path(m_file_name));
    wxGetApp().plater()->model().model_info->cover_file = path.string();
    //wxGetApp().plater()->model().model_info->cover_file = m_file_name.ToStdString();
    auto full_path          = m_file_path.branch_path();
    auto full_root_path         = full_path.branch_path();
    auto full_root_path_str = encode_path(full_root_path.string().c_str());
    auto dir       = wxString::Format("%s/.thumbnails", full_root_path_str);
    fs::path dir_path(dir.ToStdWstring());
    if (!fs::exists(dir_path)) {
        fs::create_directory(dir_path);
    }
    bool result = true;
    wxImage thumbnail_img;
    result = generate_image(m_file_path.string(), thumbnail_img, _3MF_COVER_SIZE);
    if (result) {
        auto cover_img_path = dir_path.string() + "/thumbnail_3mf.png";
        thumbnail_img.SaveFile(encode_path(cover_img_path.c_str()));
    }
    result = generate_image(m_file_path.string(), thumbnail_img, PRINTER_THUMBNAIL_SMALL_SIZE);
    if (result) {
        auto small_img_path = dir_path.string() + "/thumbnail_small.png";
        thumbnail_img.SaveFile(encode_path(small_img_path.c_str()));
    }
    result = generate_image(m_file_path.string(), thumbnail_img, PRINTER_THUMBNAIL_MIDDLE_SIZE);
    if (result) {
        auto middle_img_path = dir_path.string() + "/thumbnail_middle.png";
        thumbnail_img.SaveFile(encode_path(middle_img_path.c_str()));
    }
    wxGetApp().plater()->set_plater_dirty(true);
    auto evt = wxCommandEvent(EVT_AUXILIARY_UPDATE_COVER);
    evt.SetString(s_default_folders[m_type]);
    evt.SetEventObject(m_parent);
    wxPostEvent(m_parent, evt);
}
References _3MF_COVER_SIZE, Slic3r::encode_path(), Slic3r::GUI::generate_image(), Slic3r::GUI::into_path(), m_file_name, m_file_path, m_type, Slic3r::GUI::plater(), PRINTER_THUMBNAIL_MIDDLE_SIZE, PRINTER_THUMBNAIL_SMALL_SIZE, and s_default_folders.
Referenced by on_mouse_left_up().
on_set_delete()
void Slic3r::GUI::AuFile::on_set_delete ()
{
    fs::path bfs_path = m_file_path;
    auto     is_fine = fs::remove(bfs_path);
    if (m_cover) {
        auto full_path          = m_file_path.branch_path();
        auto full_root_path     = full_path.branch_path();
        auto full_root_path_str = encode_path(full_root_path.string().c_str());
        auto dir                = wxString::Format("%s/.thumbnails", full_root_path_str);
        fs::path dir_path(dir.ToStdWstring());
        auto cover_img_path = dir_path.string() + "/thumbnail_3mf.png";
        auto small_img_path = dir_path.string() + "/thumbnail_small.png";
        auto middle_img_path = dir_path.string() + "/thumbnail_middle.png";
        if (fs::exists(fs::path(cover_img_path))) { fs::remove(fs::path(cover_img_path));}
        if (fs::exists(fs::path(small_img_path))) { fs::remove(fs::path(small_img_path)); }
        if (fs::exists(fs::path(middle_img_path))) { fs::remove(fs::path(middle_img_path)); }
    }
    if (wxGetApp().plater()->model().model_info == nullptr) { wxGetApp().plater()->model().model_info = std::make_shared<ModelInfo>(); }
    if (wxGetApp().plater()->model().model_info->cover_file == m_file_name) { wxGetApp().plater()->model().model_info->cover_file = ""; }
    if (is_fine) {
        auto evt = wxCommandEvent(EVT_AUXILIARY_UPDATE_DELETE);
        evt.SetString(wxString::Format("%s|%s", s_default_folders[m_type], m_file_path.wstring()));
        evt.SetEventObject(m_parent);
        wxPostEvent(m_parent, evt);
    }
}
References Slic3r::encode_path(), m_cover, m_file_name, m_file_path, m_type, Slic3r::GUI::plater(), and s_default_folders.
Referenced by on_mouse_left_up().
on_set_open()
void Slic3r::GUI::AuFile::on_set_open ()
{}
on_set_rename()
void Slic3r::GUI::AuFile::on_set_rename ()
{ enter_rename_mode(); }
References enter_rename_mode().
Referenced by on_mouse_left_up().
OnEraseBackground()
void Slic3r::GUI::AuFile::OnEraseBackground (wxEraseEvent & evt)
{}
Referenced by AuFile().
OnPaint()
void Slic3r::GUI::AuFile::OnPaint (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        PaintBackground(dc2);
        PaintForeground(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    PaintBackground(dc);
    PaintForeground(dc);
#endif
}
References PaintBackground(), PaintForeground(), and size.
Referenced by AuFile().
PaintBackground()
void Slic3r::GUI::AuFile::PaintBackground (wxDC & dc)
{
    wxColour backgroundColour = GetBackgroundColour();
    if (!backgroundColour.Ok()) backgroundColour = AUFILE_GREY300;
    dc.SetBrush(wxBrush(backgroundColour));
    dc.SetPen(wxPen(backgroundColour, 1));
    wxRect windowRect(wxPoint(0, 0), GetClientSize());
    //CalcUnscrolledPosition(windowRect.x, windowRect.y, &windowRect.x, &windowRect.y);
    dc.DrawRectangle(windowRect);
    wxSize size = m_type == MODEL_PICTURE ? AUFILE_PICTURES_SIZE : AUFILE_SIZE;
    if (m_type == AddFileButton)
    {
        auto pen_width = FromDIP(2);
        dc.SetPen(wxPen(AUFILE_GREY500, pen_width));
        dc.SetBrush(StateColor::darkModeColorFor(AUFILE_GREY200));
        dc.DrawRoundedRectangle(pen_width / 2, pen_width / 2, size.x - pen_width / 2, size.y - pen_width / 2, AUFILE_ROUNDING);
        auto line_length = FromDIP(50);
        dc.DrawLine(wxPoint((size.x - line_length) / 2, size.y / 2), wxPoint((size.x + line_length) / 2, size.y / 2));
        dc.DrawLine(wxPoint(size.x / 2, (size.y - line_length) / 2), wxPoint(size.x / 2, (size.y + line_length) / 2));
        dc.SetFont(Label::Body_16);
        auto sizet = dc.GetTextExtent(m_add_file);
        auto pos = wxPoint(0, 0);
        pos.x = (size.x - sizet.x) / 2;
        pos.y = (size.y - 40); // to modify
        dc.SetTextForeground(AUFILE_GREY500);
        dc.DrawText(m_add_file, pos);
    }
    else {
        dc.SetPen(AUFILE_GREY200);
        dc.SetBrush(AUFILE_GREY200);
        dc.DrawRoundedRectangle(0, 0, size.x, size.y, AUFILE_ROUNDING);
        dc.DrawBitmap(m_file_bitmap.bmp(), (size.x - m_file_bitmap.GetBmpWidth()) / 2, (size.y - m_file_bitmap.GetBmpHeight()) / 2);
    }
}
References AddFileButton, AUFILE_GREY200, AUFILE_GREY300, AUFILE_GREY500, AUFILE_PICTURES_SIZE, AUFILE_ROUNDING, AUFILE_SIZE, ScalableBitmap::bmp(), Label::Body_16, StateColor::darkModeColorFor(), ScalableBitmap::GetBmpHeight(), ScalableBitmap::GetBmpWidth(), m_add_file, m_file_bitmap, m_type, MODEL_PICTURE, and size.
Referenced by OnPaint().
PaintForeground()
void Slic3r::GUI::AuFile::PaintForeground (wxDC & dc)
{
    wxSize size = m_type == MODEL_PICTURE ? AUFILE_PICTURES_SIZE : AUFILE_SIZE;
    if (m_hover) {
        if (m_type == AddFileButton) {
            auto pen_width = FromDIP(2);
            dc.SetPen(wxPen(AUFILE_BRAND, pen_width));
            dc.SetBrush(StateColor::darkModeColorFor(AUFILE_BRAND_TRANSPARENT));
            dc.DrawRoundedRectangle(pen_width / 2, pen_width / 2, size.x - pen_width / 2, size.y - pen_width / 2, AUFILE_ROUNDING);
            auto line_length = FromDIP(50);
            dc.DrawLine(wxPoint((size.x - line_length) / 2, size.y / 2), wxPoint((size.x + line_length) / 2, size.y / 2));
            dc.DrawLine(wxPoint(size.x / 2, (size.y - line_length) / 2), wxPoint(size.x / 2, (size.y + line_length) / 2));
            auto sizet = dc.GetTextExtent(m_add_file);
            auto pos = wxPoint(0, 0);
            pos.x = (size.x - sizet.x) / 2;
            pos.y = (size.y - 40); // to modify
            dc.SetTextForeground(AUFILE_BRAND);
            dc.DrawText(m_add_file, pos);
            return;
        }
        if (m_type == MODEL_PICTURE) {
            dc.DrawBitmap(m_file_edit_mask.bmp(), 0, size.y - m_file_edit_mask.GetBmpSize().y);
        }
        dc.SetFont(Label::Body_12);
        dc.SetTextForeground(*wxWHITE);
        if (m_type == MODEL_PICTURE) {
            // left text
            auto sizet = dc.GetTextExtent(cover_text_left);
            auto pos   = wxPoint(0, 0);
            pos.x      = (size.x / 2 - sizet.x) / 2;
            pos.y      = (size.y - (m_file_edit_mask.GetBmpSize().y + sizet.y) / 2);
            dc.DrawText(cover_text_left, pos);
            // right text
            sizet = dc.GetTextExtent(cover_text_right);
            pos   = wxPoint(0, 0);
            pos.x = size.x / 2 + (size.x / 2 - sizet.x) / 2;
            pos.y = (size.y - (m_file_edit_mask.GetBmpSize().y + sizet.y) / 2);
            dc.DrawText(cover_text_right, pos);
            // Split
            dc.SetPen(*wxWHITE);
            dc.SetBrush(*wxWHITE);
            pos   = wxPoint(0, 0);
            pos.x = size.x / 2 - 1;
            pos.y = size.y - FromDIP(24) - (m_file_edit_mask.GetBmpSize().y - FromDIP(24)) / 2;
            dc.DrawRectangle(pos.x, pos.y, 2, FromDIP(24));
        } else {
            // right text
           /* auto sizet = dc.GetTextExtent(cover_text_right);
            auto pos   = wxPoint(0, 0);
            pos.x      = (size.x - sizet.x) / 2;
            pos.y      = (size.y - (m_file_edit_mask.GetBmpSize().y + sizet.y) / 2);
            dc.DrawText(cover_text_right, pos);*/
        }
    }
    if (m_cover) {
        dc.SetTextForeground(*wxWHITE);
        dc.DrawBitmap(m_file_cover.bmp(), size.x - m_file_cover.GetBmpSize().x, 0);
        dc.SetFont(Label::Body_12);
        auto sizet = dc.GetTextExtent(cover_text_cover);
        auto pos   = wxPoint(0, 0);
        pos.x      = size.x - sizet.x - FromDIP(3);
        pos.y      = FromDIP(3);
        dc.DrawText(cover_text_cover, pos);
    }
    if (m_hover) { dc.DrawBitmap(m_file_delete.bmp(), size.x - m_file_delete.GetBmpSize().x - FromDIP(10), FromDIP(10)); }
}
References AddFileButton, AUFILE_BRAND, AUFILE_BRAND_TRANSPARENT, AUFILE_PICTURES_SIZE, AUFILE_ROUNDING, AUFILE_SIZE, ScalableBitmap::bmp(), Label::Body_12, cover_text_cover, cover_text_left, cover_text_right, StateColor::darkModeColorFor(), ScalableBitmap::GetBmpSize(), m_add_file, m_cover, m_file_cover, m_file_delete, m_file_edit_mask, m_hover, m_type, MODEL_PICTURE, and size.
Referenced by OnPaint().
set_cover()
void Slic3r::GUI::AuFile::set_cover (bool cover)
{
    m_cover = cover;
    Refresh();
}
References m_cover.
Referenced by Slic3r::GUI::AuFolderPanel::update_cover().
Member Data Documentation
cover_text_cover
wxString Slic3r::GUI::AuFile::cover_text_cover
Referenced by AuFile(), and PaintForeground().
cover_text_left
wxString Slic3r::GUI::AuFile::cover_text_left
Referenced by AuFile(), and PaintForeground().
cover_text_right
wxString Slic3r::GUI::AuFile::cover_text_right
Referenced by AuFile(), and PaintForeground().
m_add_file
wxString Slic3r::GUI::AuFile::m_add_file
Referenced by AuFile(), PaintBackground(), and PaintForeground().
m_bitmap_excel
ScalableBitmap Slic3r::GUI::AuFile::m_bitmap_excel
Referenced by AuFile(), and msw_rescale().
m_bitmap_pdf
ScalableBitmap Slic3r::GUI::AuFile::m_bitmap_pdf
Referenced by AuFile(), and msw_rescale().
m_bitmap_txt
ScalableBitmap Slic3r::GUI::AuFile::m_bitmap_txt
Referenced by AuFile(), and msw_rescale().
m_cover
bool Slic3r::GUI::AuFile::m_cover {false}
Referenced by on_set_delete(), PaintForeground(), and set_cover().
m_file_bitmap
ScalableBitmap Slic3r::GUI::AuFile::m_file_bitmap
Referenced by AuFile(), msw_rescale(), and PaintBackground().
m_file_cover
ScalableBitmap Slic3r::GUI::AuFile::m_file_cover
Referenced by AuFile(), msw_rescale(), and PaintForeground().
m_file_delete
ScalableBitmap Slic3r::GUI::AuFile::m_file_delete
Referenced by AuFile(), msw_rescale(), on_mouse_left_up(), and PaintForeground().
m_file_edit_mask
ScalableBitmap Slic3r::GUI::AuFile::m_file_edit_mask
Referenced by AuFile(), msw_rescale(), on_mouse_left_up(), and PaintForeground().
m_file_exit_rename
wxStaticBitmap* Slic3r::GUI::AuFile::m_file_exit_rename
Referenced by AuFile(), enter_rename_mode(), and exit_rename_mode().
m_file_name
wxString Slic3r::GUI::AuFile::m_file_name
Referenced by AuFile(), enter_rename_mode(), on_input_enter(), on_set_cover(), on_set_delete(), and Slic3r::GUI::AuFolderPanel::update_cover().
m_file_path
fs::path Slic3r::GUI::AuFile::m_file_path
Referenced by AuFile(), msw_rescale(), on_dclick(), on_input_enter(), on_set_cover(), and on_set_delete().
m_hover
bool Slic3r::GUI::AuFile::m_hover {false}
Referenced by on_mouse_enter(), on_mouse_leave(), and PaintForeground().
m_input_name
::TextInput* Slic3r::GUI::AuFile::m_input_name {nullptr}
Referenced by AuFile(), enter_rename_mode(), exit_rename_mode(), and on_input_enter().
m_text_name
wxStaticText* Slic3r::GUI::AuFile::m_text_name {nullptr}
Referenced by AuFile(), enter_rename_mode(), exit_rename_mode(), and on_input_enter().
m_type
AuxiliaryFolderType Slic3r::GUI::AuFile::m_type
Referenced by AuFile(), msw_rescale(), on_dclick(), on_input_enter(), on_mouse_left_up(), on_set_cover(), on_set_delete(), PaintBackground(), and PaintForeground().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Auxiliary.hpp
src/slic3r/GUI/Auxiliary.cpp