OrcaSlicer: Slic3r::GUI::GLPaintContour Class Reference
Slic3r::GUI::GLPaintContour Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoPainterBase.hpp>
Public Member Functions
GLPaintContour ()=default
void render () const
bool has_VBO () const
void release_geometry ()
void finalize_geometry ()
void clear ()
Public Attributes
std::vector< float > contour_vertices
std::vector< int > contour_indices
size_t contour_indices_size {0}
GLuint m_contour_VBO_id {0}
GLuint m_contour_EBO_id {0}
Detailed Description
Constructor & Destructor Documentation
GLPaintContour()
Slic3r::GUI::GLPaintContour::GLPaintContour () default
Member Function Documentation
clear()
void Slic3r::GUI::GLPaintContour::clear () inline
    {
        this->contour_vertices.clear();
        this->contour_indices.clear();
        this->contour_indices_size = 0;
    }
References contour_indices, contour_indices_size, and contour_vertices.
Referenced by release_geometry().
finalize_geometry()
void Slic3r::GUI::GLPaintContour::finalize_geometry ()
{
    assert(this->m_contour_VBO_id == 0);
    assert(this->m_contour_EBO_id == 0);
    if (!this->contour_vertices.empty()) {
        glsafe(::glGenBuffers(1, &this->m_contour_VBO_id));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, this->m_contour_VBO_id));
        glsafe(::glBufferData(GL_ARRAY_BUFFER, this->contour_vertices.size() * sizeof(float), this->contour_vertices.data(), GL_STATIC_DRAW));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
        this->contour_vertices.clear();
    }
    if (!this->contour_indices.empty()) {
        glsafe(::glGenBuffers(1, &this->m_contour_EBO_id));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->m_contour_EBO_id));
        glsafe(::glBufferData(GL_ELEMENT_ARRAY_BUFFER, this->contour_indices.size() * sizeof(unsigned int), this->contour_indices.data(), GL_STATIC_DRAW));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
        this->contour_indices.clear();
    }
}
References contour_indices, contour_vertices, glsafe, m_contour_EBO_id, and m_contour_VBO_id.
Referenced by Slic3r::GUI::TriangleSelectorGUI::update_render_data(), and Slic3r::GUI::TriangleSelectorPatch::update_render_data().
has_VBO()
bool Slic3r::GUI::GLPaintContour::has_VBO () const inline
{ return this->m_contour_EBO_id != 0; }
References m_contour_EBO_id.
Referenced by Slic3r::GUI::TriangleSelectorGUI::render(), and Slic3r::GUI::TriangleSelectorPatch::render().
release_geometry()
void Slic3r::GUI::GLPaintContour::release_geometry ()
{
    if (this->m_contour_VBO_id) {
        glsafe(::glDeleteBuffers(1, &this->m_contour_VBO_id));
        this->m_contour_VBO_id = 0;
    }
    if (this->m_contour_EBO_id) {
        glsafe(::glDeleteBuffers(1, &this->m_contour_EBO_id));
        this->m_contour_EBO_id = 0;
    }
    this->clear();
}
References clear(), glsafe, m_contour_EBO_id, and m_contour_VBO_id.
Referenced by Slic3r::GUI::TriangleSelectorGUI::update_render_data(), and Slic3r::GUI::TriangleSelectorPatch::update_render_data().
render()
void Slic3r::GUI::GLPaintContour::render () const
{
    assert(this->m_contour_VBO_id != 0);
    assert(this->m_contour_EBO_id != 0);
    glsafe(::glLineWidth(4.0f));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, this->m_contour_VBO_id));
    glsafe(::glVertexPointer(3, GL_FLOAT, 3 * sizeof(float), nullptr));
    glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
    if (this->contour_indices_size > 0) {
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->m_contour_EBO_id));
        glsafe(::glDrawElements(GL_LINES, GLsizei(this->contour_indices_size), GL_UNSIGNED_INT, nullptr));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
    }
    glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
}
References contour_indices_size, glsafe, m_contour_EBO_id, and m_contour_VBO_id.
Referenced by Slic3r::GUI::TriangleSelectorGUI::render(), and Slic3r::GUI::TriangleSelectorPatch::render().
Member Data Documentation
contour_indices
std::vector<int> Slic3r::GUI::GLPaintContour::contour_indices
Referenced by clear(), finalize_geometry(), Slic3r::GUI::TriangleSelectorGUI::update_render_data(), and Slic3r::GUI::TriangleSelectorPatch::update_render_data().
contour_indices_size
size_t Slic3r::GUI::GLPaintContour::contour_indices_size {0}
Referenced by clear(), render(), Slic3r::GUI::TriangleSelectorGUI::update_render_data(), and Slic3r::GUI::TriangleSelectorPatch::update_render_data().
contour_vertices
std::vector<float> Slic3r::GUI::GLPaintContour::contour_vertices
Referenced by clear(), finalize_geometry(), Slic3r::GUI::TriangleSelectorGUI::update_render_data(), and Slic3r::GUI::TriangleSelectorPatch::update_render_data().
m_contour_EBO_id
GLuint Slic3r::GUI::GLPaintContour::m_contour_EBO_id {0}
Referenced by finalize_geometry(), has_VBO(), release_geometry(), and render().
m_contour_VBO_id
GLuint Slic3r::GUI::GLPaintContour::m_contour_VBO_id {0}
Referenced by finalize_geometry(), release_geometry(), and render().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoPainterBase.hpp
src/slic3r/GUI/Gizmos/GLGizmoPainterBase.cpp