OrcaSlicer: Slic3r::GUI::GeometryBuffer Class Reference
Slic3r::GUI::GeometryBuffer Class Reference
#include <src/slic3r/GUI/3DBed.hpp>
Classes
struct Vertex
Public Member Functions
bool set_from_triangles (const std::vector< Vec2f > &triangles, float z)
bool set_from_lines (const Lines &lines, float z)
bool set_from_3d_Lines (const Lines3 &lines)
const float * get_vertices_data () const
unsigned int get_vertices_data_size () const
unsigned int get_vertex_data_size () const
size_t get_position_offset () const
size_t get_tex_coords_offset () const
unsigned int get_vertices_count () const
Private Attributes
std::vector< Vertex > m_vertices
Detailed Description
Class Documentation
Slic3r::GUI::GeometryBuffer::Vertex
struct Slic3r::GUI::GeometryBuffer::Vertex
Class Members
Vec3f position { Vec3f::Zero() }
Vec2f tex_coords { Vec2f::Zero() }
Member Function Documentation
get_position_offset()
size_t Slic3r::GUI::GeometryBuffer::get_position_offset () const inline
{ return 0; }
Referenced by Slic3r::GUI::PartPlate::render_logo_texture(), and Slic3r::GUI::PartPlate::render_plate_name_texture().
get_tex_coords_offset()
size_t Slic3r::GUI::GeometryBuffer::get_tex_coords_offset () const inline
{ return (size_t)(3 * sizeof(float)); }
Referenced by Slic3r::GUI::PartPlate::render_logo_texture(), and Slic3r::GUI::PartPlate::render_plate_name_texture().
get_vertex_data_size()
unsigned int Slic3r::GUI::GeometryBuffer::get_vertex_data_size () const inline
{ return (unsigned int)(5 * sizeof(float)); }
Referenced by get_vertices_data_size(), Slic3r::GUI::PartPlate::render_background(), Slic3r::GUI::Bed3D::render_default(), Slic3r::GUI::PartPlate::render_exclude_area(), Slic3r::GUI::PartPlate::render_grid(), Slic3r::GUI::PartPlate::render_height_limit(), Slic3r::GUI::PartPlate::render_logo_texture(), and Slic3r::GUI::PartPlate::render_plate_name_texture().
get_vertices_count()
unsigned int Slic3r::GUI::GeometryBuffer::get_vertices_count () const inline
{ return (unsigned int)m_vertices.size(); }
References m_vertices.
Referenced by Slic3r::GUI::PartPlate::render_background(), Slic3r::GUI::Bed3D::render_default(), Slic3r::GUI::PartPlate::render_exclude_area(), Slic3r::GUI::PartPlate::render_grid(), Slic3r::GUI::PartPlate::render_height_limit(), Slic3r::GUI::PartPlate::render_logo(), Slic3r::GUI::PartPlate::render_logo_texture(), and Slic3r::GUI::PartPlate::render_plate_name_texture().
get_vertices_data()
const float * Slic3r::GUI::GeometryBuffer::get_vertices_data () const
{
    return (m_vertices.size() > 0) ? (const float*)m_vertices.data() : nullptr;
}
References m_vertices.
Referenced by Slic3r::GUI::PartPlate::render_background(), Slic3r::GUI::Bed3D::render_default(), Slic3r::GUI::PartPlate::render_exclude_area(), Slic3r::GUI::PartPlate::render_grid(), Slic3r::GUI::PartPlate::render_height_limit(), Slic3r::GUI::PartPlate::render_logo(), Slic3r::GUI::PartPlate::render_plate_name_texture(), and Slic3r::GUI::PartPlateList::BedTextureInfo::TexturePart::update_buffer().
get_vertices_data_size()
unsigned int Slic3r::GUI::GeometryBuffer::get_vertices_data_size () const inline
{ return (unsigned int)m_vertices.size() * get_vertex_data_size(); }
References get_vertex_data_size(), and m_vertices.
Referenced by Slic3r::GUI::PartPlate::render_logo(), Slic3r::GUI::PartPlate::render_plate_name_texture(), and Slic3r::GUI::PartPlateList::BedTextureInfo::TexturePart::update_buffer().
set_from_3d_Lines()
bool Slic3r::GUI::GeometryBuffer::set_from_3d_Lines (const Lines3 & lines)
{
    m_vertices.clear();
    unsigned int v_size = 2 * (unsigned int)lines.size();
    if (v_size == 0)
        return false;
    m_vertices = std::vector<Vertex>(v_size, Vertex());
    unsigned int v_count = 0;
    for (const Line3& l : lines) {
        Vertex& v1 = m_vertices[v_count];
        v1.position[0] = unscale<float>(l.a(0));
        v1.position[1] = unscale<float>(l.a(1));
        v1.position[2] = unscale<float>(l.a(2));
        ++v_count;
        Vertex& v2 = m_vertices[v_count];
        v2.position[0] = unscale<float>(l.b(0));
        v2.position[1] = unscale<float>(l.b(1));
        v2.position[2] = unscale<float>(l.b(2));
        ++v_count;
    }
    return true;
}
References int, m_vertices, and Slic3r::GUI::GeometryBuffer::Vertex::position.
Referenced by Slic3r::GUI::PartPlate::calc_height_limit().
set_from_lines()
bool Slic3r::GUI::GeometryBuffer::set_from_lines (const Lines & lines, float z)
{
    m_vertices.clear();
    unsigned int v_size = 2 * (unsigned int)lines.size();
    if (v_size == 0)
        return false;
    m_vertices = std::vector<Vertex>(v_size, Vertex());
    unsigned int v_count = 0;
    for (const Line& l : lines) {
        Vertex& v1 = m_vertices[v_count];
        v1.position[0] = unscale<float>(l.a(0));
        v1.position[1] = unscale<float>(l.a(1));
        v1.position[2] = z;
        ++v_count;
        Vertex& v2 = m_vertices[v_count];
        v2.position[0] = unscale<float>(l.b(0));
        v2.position[1] = unscale<float>(l.b(1));
        v2.position[2] = z;
        ++v_count;
    }
    return true;
}
References int, m_vertices, and Slic3r::GUI::GeometryBuffer::Vertex::position.
Referenced by Slic3r::GUI::PartPlate::calc_gridlines().
set_from_triangles()
bool Slic3r::GUI::GeometryBuffer::set_from_triangles (const std::vector< Vec2f > & triangles, float z)
{
    if (triangles.empty()) {
        m_vertices.clear();
        return false;
    }
    m_vertices.clear();
    assert(triangles.size() % 3 == 0);
    m_vertices = std::vector<Vertex>(triangles.size(), Vertex());
    Vec2f min = triangles.front();
    Vec2f max = min;
    for (size_t v_count = 0; v_count < triangles.size(); ++ v_count) {
        const Vec2f &p = triangles[v_count];
        Vertex      &v = m_vertices[v_count];
        v.position   = Vec3f(p.x(), p.y(), z);
        v.tex_coords = p;
        min = min.cwiseMin(p).eval();
        max = max.cwiseMax(p).eval();
    }
    Vec2f size = max - min;
    if (size.x() != 0.f && size.y() != 0.f) {
        Vec2f inv_size = size.cwiseInverse();
        inv_size.y() *= -1;
        for (Vertex& v : m_vertices) {
            v.tex_coords -= min;
            v.tex_coords.x() *= inv_size.x();
            v.tex_coords.y() *= inv_size.y();
        }
    }
    return true;
}
References m_vertices, max(), min(), Slic3r::GUI::GeometryBuffer::Vertex::position, size, and Slic3r::GUI::GeometryBuffer::Vertex::tex_coords.
Referenced by Slic3r::GUI::PartPlate::calc_exclude_triangles(), Slic3r::GUI::Bed3D::calc_triangles(), Slic3r::GUI::PartPlate::calc_triangles(), Slic3r::GUI::PartPlate::generate_plate_name_texture(), Slic3r::GUI::PartPlate::set_shape(), Slic3r::GUI::Bed3D::update_bed_triangles(), and Slic3r::GUI::PartPlateList::BedTextureInfo::TexturePart::update_buffer().
Member Data Documentation
m_vertices
std::vector<Vertex> Slic3r::GUI::GeometryBuffer::m_vertices private
Referenced by get_vertices_count(), get_vertices_data(), get_vertices_data_size(), set_from_3d_Lines(), set_from_lines(), and set_from_triangles().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DBed.hpp
src/slic3r/GUI/3DBed.cpp