var dir_8b8dc433c42c06eb84efd40d75cf8a5b =
[
    [ "geom2_r.c", "d0/d7e/geom2__r_8c.html", "d0/d7e/geom2__r_8c" ],
    [ "geom_r.c", "d5/d3a/geom__r_8c.html", "d5/d3a/geom__r_8c" ],
    [ "geom_r.h", "d8/dd7/geom__r_8h.html", "d8/dd7/geom__r_8h" ],
    [ "global_r.c", "da/dc8/global__r_8c.html", "da/dc8/global__r_8c" ],
    [ "io_r.c", "d8/d2c/io__r_8c.html", "d8/d2c/io__r_8c" ],
    [ "io_r.h", "de/d42/io__r_8h.html", "de/d42/io__r_8h" ],
    [ "libqhull_r.c", "dd/ddc/libqhull__r_8c.html", "dd/ddc/libqhull__r_8c" ],
    [ "libqhull_r.h", "d2/d25/libqhull__r_8h.html", "d2/d25/libqhull__r_8h" ],
    [ "mem_r.c", "db/d5e/mem__r_8c.html", "db/d5e/mem__r_8c" ],
    [ "mem_r.h", "dd/dca/mem__r_8h.html", "dd/dca/mem__r_8h" ],
    [ "merge_r.c", "d4/daf/merge__r_8c.html", "d4/daf/merge__r_8c" ],
    [ "merge_r.h", "d5/d6e/merge__r_8h.html", "d5/d6e/merge__r_8h" ],
    [ "poly2_r.c", "dd/d98/poly2__r_8c.html", "dd/d98/poly2__r_8c" ],
    [ "poly_r.c", "d0/d75/poly__r_8c.html", "d0/d75/poly__r_8c" ],
    [ "poly_r.h", "de/d56/poly__r_8h.html", "de/d56/poly__r_8h" ],
    [ "qhull_ra.h", "d4/d52/qhull__ra_8h.html", "d4/d52/qhull__ra_8h" ],
    [ "qset_r.c", "d9/d3c/qset__r_8c.html", "d9/d3c/qset__r_8c" ],
    [ "qset_r.h", "d5/de0/qset__r_8h.html", "d5/de0/qset__r_8h" ],
    [ "random_r.c", "df/d2b/random__r_8c.html", "df/d2b/random__r_8c" ],
    [ "random_r.h", "d3/d64/random__r_8h.html", "d3/d64/random__r_8h" ],
    [ "rboxlib_r.c", "d2/dd4/rboxlib__r_8c.html", "d2/dd4/rboxlib__r_8c" ],
    [ "stat_r.c", "d4/d46/stat__r_8c.html", "d4/d46/stat__r_8c" ],
    [ "stat_r.h", "de/d34/stat__r_8h.html", "de/d34/stat__r_8h" ],
    [ "user_r.c", "de/d92/user__r_8c.html", "de/d92/user__r_8c" ],
    [ "user_r.h", "d0/d30/user__r_8h.html", "d0/d30/user__r_8h" ],
    [ "usermem_r.c", "d9/d4c/usermem__r_8c.html", "d9/d4c/usermem__r_8c" ],
    [ "userprintf_r.c", "d5/d03/userprintf__r_8c.html", "d5/d03/userprintf__r_8c" ],
    [ "userprintf_rbox_r.c", "d1/dc6/userprintf__rbox__r_8c.html", "d1/dc6/userprintf__rbox__r_8c" ]
];