OrcaSlicer: Slic3r::PerimeterGenerator Class Reference
Slic3r::PerimeterGenerator Class Reference
#include <src/libslic3r/PerimeterGenerator.hpp>
Public Member Functions
PerimeterGenerator (const SurfaceCollection *slices, double layer_height, Flow flow, const PrintRegionConfig *config, const PrintObjectConfig *object_config, const PrintConfig *print_config, const bool spiral_mode, ExtrusionEntityCollection *loops, ExtrusionEntityCollection *gap_fill, SurfaceCollection *fill_surfaces, ExPolygons *fill_no_overlap)
void process_classic ()
void process_arachne ()
double ext_mm3_per_mm () const
double mm3_per_mm () const
double mm3_per_mm_overhang () const
double smaller_width_ext_mm3_per_mm () const
Polygons lower_slices_polygons () const
Public Attributes
const SurfaceCollection * slices
const ExPolygons * upper_slices
const ExPolygons * lower_slices
double layer_height
int layer_id
Flow perimeter_flow
Flow ext_perimeter_flow
Flow overhang_flow
Flow solid_infill_flow
const PrintRegionConfig * config
const PrintObjectConfig * object_config
const PrintConfig * print_config
ExtrusionEntityCollection * loops
ExtrusionEntityCollection * gap_fill
SurfaceCollection * fill_surfaces
ExPolygons * fill_no_overlap
Flow smaller_ext_perimeter_flow
std::map< int, Polygons > m_lower_polygons_series
std::map< int, Polygons > m_external_lower_polygons_series
std::map< int, Polygons > m_smaller_external_lower_polygons_series
Private Member Functions
std::map< int, Polygons > generate_lower_polygons_series (float width)
void split_top_surfaces (const ExPolygons &orig_polygons, ExPolygons &top_fills, ExPolygons &non_top_polygons, ExPolygons &fill_clip) const
Private Attributes
bool m_spiral_vase
double m_scaled_resolution
double m_ext_mm3_per_mm
double m_mm3_per_mm
double m_mm3_per_mm_overhang
double m_ext_mm3_per_mm_smaller_width
Polygons m_lower_slices_polygons
Detailed Description
Constructor & Destructor Documentation
PerimeterGenerator()
Slic3r::PerimeterGenerator::PerimeterGenerator (const SurfaceCollection * slices, double layer_height, Flow flow, const PrintRegionConfig * config, const PrintObjectConfig * object_config, const PrintConfig * print_config, const bool spiral_mode, ExtrusionEntityCollection * loops, ExtrusionEntityCollection * gap_fill, SurfaceCollection * fill_surfaces, ExPolygons * fill_no_overlap) inline
        : slices(slices), upper_slices(nullptr), lower_slices(nullptr), layer_height(layer_height),
            layer_id(-1), perimeter_flow(flow), ext_perimeter_flow(flow),
            overhang_flow(flow), solid_infill_flow(flow),
            config(config), object_config(object_config), print_config(print_config),
            m_spiral_vase(spiral_mode),
            m_scaled_resolution(scaled<double>(print_config->resolution.value > EPSILON ? print_config->resolution.value : EPSILON)),
            loops(loops), gap_fill(gap_fill), fill_surfaces(fill_surfaces), fill_no_overlap(fill_no_overlap),
            m_ext_mm3_per_mm(-1), m_mm3_per_mm(-1), m_mm3_per_mm_overhang(-1), m_ext_mm3_per_mm_smaller_width(-1)
        {}
Member Function Documentation
ext_mm3_per_mm()
double Slic3r::PerimeterGenerator::ext_mm3_per_mm () const inline
{ return m_ext_mm3_per_mm; }
References m_ext_mm3_per_mm.
Referenced by Slic3r::traverse_loops().
generate_lower_polygons_series()
std::map< int, Polygons > Slic3r::PerimeterGenerator::generate_lower_polygons_series (float width) private
{
    float nozzle_diameter = print_config->nozzle_diameter.get_at(config->wall_filament - 1);
    float start_offset = -0.5 * width;
    float end_offset = 0.5 * nozzle_diameter;
    assert(overhang_sampling_number >= 3);
    // generate offsets
    std::vector<float> offset_series;
    offset_series.reserve(overhang_sampling_number - 1);
    for (int i = 0; i < overhang_sampling_number - 1; i++) {
        offset_series.push_back(start_offset + (i + 0.5) * (end_offset - start_offset) / (overhang_sampling_number - 1));
    }
    // BBS: increase start_offset a little to avoid to calculate 90 degree as overhang
    offset_series[0] = start_offset + 0.5 * (end_offset - start_offset) / (overhang_sampling_number - 1);
    offset_series[overhang_sampling_number - 2] = end_offset;
    offset_series.back() = 0.1 * nozzle_diameter;
    std::map<int, Polygons> lower_polygons_series;
    if (this->lower_slices == NULL) {
        return lower_polygons_series;
    }
    // offset expolygon to generate series of polygons
    for (int i = 0; i < offset_series.size(); i++) {
        lower_polygons_series.insert(std::pair<int, Polygons>(i, offset(*this->lower_slices, float(scale_(offset_series[i])))));
    }
    return lower_polygons_series;
}
References config, lower_slices, NULL, Slic3r::offset(), overhang_sampling_number, print_config, and scale_.
Referenced by process_classic().
lower_slices_polygons()
Polygons Slic3r::PerimeterGenerator::lower_slices_polygons () const inline
{ return m_lower_slices_polygons; }
References m_lower_slices_polygons.
Referenced by Slic3r::traverse_extrusions().
mm3_per_mm()
double Slic3r::PerimeterGenerator::mm3_per_mm () const inline
{ return m_mm3_per_mm; }
References m_mm3_per_mm.
Referenced by Slic3r::traverse_loops().
mm3_per_mm_overhang()
double Slic3r::PerimeterGenerator::mm3_per_mm_overhang () const inline
{ return m_mm3_per_mm_overhang; }
References m_mm3_per_mm_overhang.
Referenced by Slic3r::traverse_loops().
process_arachne()
void Slic3r::PerimeterGenerator::process_arachne ()
{
    // other perimeters
    m_mm3_per_mm = this->perimeter_flow.mm3_per_mm();
    coord_t perimeter_spacing = this->perimeter_flow.scaled_spacing();
    // external perimeters
    m_ext_mm3_per_mm = this->ext_perimeter_flow.mm3_per_mm();
    coord_t ext_perimeter_width = this->ext_perimeter_flow.scaled_width();
    coord_t ext_perimeter_spacing = this->ext_perimeter_flow.scaled_spacing();
    coord_t ext_perimeter_spacing2 = scaled<coord_t>(0.5f * (this->ext_perimeter_flow.spacing() + this->perimeter_flow.spacing()));
    // overhang perimeters
    m_mm3_per_mm_overhang = this->overhang_flow.mm3_per_mm();
    // solid infill
    coord_t solid_infill_spacing = this->solid_infill_flow.scaled_spacing();
    // prepare grown lower layer slices for overhang detection
    if (this->lower_slices != nullptr && this->config->detect_overhang_wall) {
        // We consider overhang any part where the entire nozzle diameter is not supported by the
        // lower layer, so we take lower slices and offset them by half the nozzle diameter used
        // in the current layer
        double nozzle_diameter = this->print_config->nozzle_diameter.get_at(this->config->wall_filament - 1);
        m_lower_slices_polygons = offset(*this->lower_slices, float(scale_(+nozzle_diameter / 2)));
    }
    // BBS: don't simplify too much which influence arc fitting when export gcode if arc_fitting is enabled
    double surface_simplify_resolution = (print_config->enable_arc_fitting && this->config->fuzzy_skin == FuzzySkinType::None) ? 0.2 * m_scaled_resolution : m_scaled_resolution;
    // we need to process each island separately because we might have different
    // extra perimeters for each one
    for (const Surface& surface : this->slices->surfaces) {
        coord_t bead_width_0 = ext_perimeter_spacing;
        if (config->precise_outer_wall)
            bead_width_0 = ext_perimeter_width + this->perimeter_flow.scaled_width() - perimeter_spacing;
        // detect how many perimeters must be generated for this island
        int        loop_number = this->config->wall_loops + surface.extra_perimeters - 1; // 0-indexed loops
        if (this->layer_id == 0 && this->config->only_one_wall_first_layer)
            loop_number = 0;
        // BBS: set the topmost layer to be one wall
        if (loop_number > 0 && config->only_one_wall_top && this->upper_slices == nullptr)
            loop_number = 0;
        ExPolygons last = offset_ex(surface.expolygon.simplify_p(surface_simplify_resolution),
                      config->precise_outer_wall ? -float(ext_perimeter_width / 2. - bead_width_0 / 2.)
                                                 : -float(ext_perimeter_width / 2. - ext_perimeter_spacing / 2.));
        double min_nozzle_diameter = *std::min_element(print_config->nozzle_diameter.values.begin(), print_config->nozzle_diameter.values.end());
        Arachne::WallToolPathsParams input_params;
        {
            if (const auto& min_feature_size_opt = object_config->min_feature_size)
                input_params.min_feature_size = min_feature_size_opt.value * 0.01 * min_nozzle_diameter;
            if (const auto& min_bead_width_opt = object_config->min_bead_width)
                input_params.min_bead_width = min_bead_width_opt.value * 0.01 * min_nozzle_diameter;
            if (const auto& wall_transition_filter_deviation_opt = object_config->wall_transition_filter_deviation)
                input_params.wall_transition_filter_deviation = wall_transition_filter_deviation_opt.value * 0.01 * min_nozzle_diameter;
            if (const auto& wall_transition_length_opt = object_config->wall_transition_length)
                input_params.wall_transition_length = wall_transition_length_opt.value * 0.01 * min_nozzle_diameter;
            input_params.wall_transition_angle = this->object_config->wall_transition_angle.value;
            input_params.wall_distribution_count = this->object_config->wall_distribution_count.value;
        }
        coord_t wall_0_inset = 0;
        //if (config->precise_outer_wall)
        //    wall_0_inset = 0.5 * (ext_perimeter_width + this->perimeter_flow.scaled_width() - ext_perimeter_spacing -
        //                           perimeter_spacing);
        std::vector<Arachne::VariableWidthLines> out_shell;
        ExPolygons top_fills;
        ExPolygons fill_clip;
        if (loop_number > 0 && config->only_one_wall_top && this->upper_slices != nullptr) {
            // Check if current layer has surfaces that are not covered by upper layer (i.e., top surfaces)
            ExPolygons non_top_polygons;
            this->split_top_surfaces(last, top_fills, non_top_polygons, fill_clip);
            if (top_fills.empty()) {
                // No top surfaces, no special handling needed
            } else {
                // First we slice the outer shell
                Polygons last_p = to_polygons(last);
                Arachne::WallToolPaths wallToolPaths(last_p, bead_width_0, perimeter_spacing, coord_t(1),
                                                     wall_0_inset, layer_height, input_params);
                out_shell = wallToolPaths.getToolPaths();
                // Make sure infill not overlap with wall
                top_fills = intersection_ex(top_fills, wallToolPaths.getInnerContour());
                if (!top_fills.empty()) {
                    // Then get the inner part that needs more walls
                    last = intersection_ex(non_top_polygons, wallToolPaths.getInnerContour());
                    loop_number--;
                } else {
                    // Give up the outer shell because we don't have any meaningful top surface
                    out_shell.clear();
                }
            }
        }
        Polygons last_p = to_polygons(last);
        Arachne::WallToolPaths wallToolPaths(last_p, bead_width_0, perimeter_spacing, coord_t(loop_number + 1),
                                             wall_0_inset, layer_height, input_params);
        std::vector<Arachne::VariableWidthLines> perimeters = wallToolPaths.getToolPaths();
        if (!out_shell.empty()) {
            // Combine outer shells
            size_t inset_offset = 0;
            for (auto &p : out_shell) {
                for (auto &l : p) {
                    if (l.inset_idx + 1 > inset_offset) {
                        inset_offset = l.inset_idx + 1;
                    }
                }
            }
             for (auto &p : perimeters) {
                 for (auto &l : p) {
                     l.inset_idx += inset_offset;
                 }
             }
            perimeters.insert(perimeters.begin(), out_shell.begin(), out_shell.end());
        }
        loop_number = int(perimeters.size()) - 1;
#ifdef ARACHNE_DEBUG
        {
            static int iRun = 0;
            export_perimeters_to_svg(debug_out_path("arachne-perimeters-%d-%d.svg", layer_id, iRun++), to_polygons(last), perimeters, union_ex(wallToolPaths.getInnerContour()));
        }
#endif
        // All closed ExtrusionLine should have the same the first and the last point.
        // But in rare cases, Arachne produce ExtrusionLine marked as closed but without
        // equal the first and the last point.
        assert([&perimeters = std::as_const(perimeters)]() -> bool {
            for (const Arachne::VariableWidthLines& perimeter : perimeters)
                for (const Arachne::ExtrusionLine& el : perimeter)
                    if (el.is_closed && el.junctions.front().p != el.junctions.back().p)
                        return false;
            return true;
        }());
        int start_perimeter = int(perimeters.size()) - 1;
        int end_perimeter = -1;
        int direction = -1;
        bool is_outer_wall_first =
            this->config->wall_infill_order == WallInfillOrder::OuterInnerInfill ||
            this->config->wall_infill_order == WallInfillOrder::InfillOuterInner ||
            this->config->wall_infill_order == WallInfillOrder::InnerOuterInnerInfill;
        if (is_outer_wall_first) {
            start_perimeter = 0;
            end_perimeter = int(perimeters.size());
            direction = 1;
        }
        std::vector<Arachne::ExtrusionLine*> all_extrusions;
        for (int perimeter_idx = start_perimeter; perimeter_idx != end_perimeter; perimeter_idx += direction) {
            if (perimeters[perimeter_idx].empty())
                continue;
            for (Arachne::ExtrusionLine& wall : perimeters[perimeter_idx])
                all_extrusions.emplace_back(&wall);
        }
        // Find topological order with constraints from extrusions_constrains.
        std::vector<size_t>              blocked(all_extrusions.size(), 0); // Value indicating how many extrusions it is blocking (preceding extrusions) an extrusion.
        std::vector<std::vector<size_t>> blocking(all_extrusions.size());   // Each extrusion contains a vector of extrusions that are blocked by this extrusion.
        std::unordered_map<const Arachne::ExtrusionLine*, size_t> map_extrusion_to_idx;
        for (size_t idx = 0; idx < all_extrusions.size(); idx++)
            map_extrusion_to_idx.emplace(all_extrusions[idx], idx);
        auto extrusions_constrains = Arachne::WallToolPaths::getRegionOrder(all_extrusions, is_outer_wall_first);
        for (auto [before, after] : extrusions_constrains) {
            auto after_it = map_extrusion_to_idx.find(after);
            ++blocked[after_it->second];
            blocking[map_extrusion_to_idx.find(before)->second].emplace_back(after_it->second);
        }
        std::vector<bool> processed(all_extrusions.size(), false);          // Indicate that the extrusion was already processed.
        Point             current_position = all_extrusions.empty() ? Point::Zero() : all_extrusions.front()->junctions.front().p; // Some starting position.
        std::vector<PerimeterGeneratorArachneExtrusion> ordered_extrusions;         // To store our result in. At the end we'll std::swap.
        ordered_extrusions.reserve(all_extrusions.size());
        while (ordered_extrusions.size() < all_extrusions.size()) {
            size_t best_candidate = 0;
            double best_distance_sqr = std::numeric_limits<double>::max();
            bool   is_best_closed = false;
            std::vector<size_t> available_candidates;
            for (size_t candidate = 0; candidate < all_extrusions.size(); ++candidate) {
                if (processed[candidate] || blocked[candidate])
                    continue; // Not a valid candidate.
                available_candidates.push_back(candidate);
            }
            std::sort(available_candidates.begin(), available_candidates.end(), [&all_extrusions](const size_t a_idx, const size_t b_idx) -> bool {
                return all_extrusions[a_idx]->is_closed < all_extrusions[b_idx]->is_closed;
                });
            for (const size_t candidate_path_idx : available_candidates) {
                auto& path = all_extrusions[candidate_path_idx];
                if (path->junctions.empty()) { // No vertices in the path. Can't find the start position then or really plan it in. Put that at the end.
                    if (best_distance_sqr == std::numeric_limits<double>::max()) {
                        best_candidate = candidate_path_idx;
                        is_best_closed = path->is_closed;
                    }
                    continue;
                }
                const Point candidate_position = path->junctions.front().p;
                double      distance_sqr = (current_position - candidate_position).cast<double>().norm();
                if (distance_sqr < best_distance_sqr) { // Closer than the best candidate so far.
                    if (path->is_closed || (!path->is_closed && best_distance_sqr != std::numeric_limits<double>::max()) || (!path->is_closed && !is_best_closed)) {
                        best_candidate = candidate_path_idx;
                        best_distance_sqr = distance_sqr;
                        is_best_closed = path->is_closed;
                    }
                }
            }
            auto& best_path = all_extrusions[best_candidate];
            ordered_extrusions.push_back({ best_path, best_path->is_contour(), false });
            processed[best_candidate] = true;
            for (size_t unlocked_idx : blocking[best_candidate])
                blocked[unlocked_idx]--;
            if (!best_path->junctions.empty()) { //If all paths were empty, the best path is still empty. We don't upate the current position then.
                if (best_path->is_closed)
                    current_position = best_path->junctions[0].p; //We end where we started.
                else
                    current_position = best_path->junctions.back().p; //Pick the other end from where we started.
            }
        }
        if (this->layer_id > 0 && this->config->fuzzy_skin != FuzzySkinType::None) {
            std::vector<PerimeterGeneratorArachneExtrusion*> closed_loop_extrusions;
            for (PerimeterGeneratorArachneExtrusion& extrusion : ordered_extrusions)
                if (extrusion.extrusion->inset_idx == 0) {
                    if (extrusion.extrusion->is_closed && this->config->fuzzy_skin == FuzzySkinType::External) {
                        closed_loop_extrusions.emplace_back(&extrusion);
                    }
                    else {
                        extrusion.fuzzify = true;
                    }
                }
            if (this->config->fuzzy_skin == FuzzySkinType::External) {
                ClipperLib_Z::Paths loops_paths;
                loops_paths.reserve(closed_loop_extrusions.size());
                for (const auto& cl_extrusion : closed_loop_extrusions) {
                    assert(cl_extrusion->extrusion->junctions.front() == cl_extrusion->extrusion->junctions.back());
                    size_t             loop_idx = &cl_extrusion - &closed_loop_extrusions.front();
                    ClipperLib_Z::Path loop_path;
                    loop_path.reserve(cl_extrusion->extrusion->junctions.size() - 1);
                    for (auto junction_it = cl_extrusion->extrusion->junctions.begin(); junction_it != std::prev(cl_extrusion->extrusion->junctions.end()); ++junction_it)
                        loop_path.emplace_back(junction_it->p.x(), junction_it->p.y(), loop_idx);
                    loops_paths.emplace_back(loop_path);
                }
                ClipperLib_Z::Clipper clipper;
                clipper.AddPaths(loops_paths, ClipperLib_Z::ptSubject, true);
                ClipperLib_Z::PolyTree loops_polytree;
                clipper.Execute(ClipperLib_Z::ctUnion, loops_polytree, ClipperLib_Z::pftEvenOdd, ClipperLib_Z::pftEvenOdd);
                for (const ClipperLib_Z::PolyNode* child_node : loops_polytree.Childs) {
                    // The whole contour must have the same index.
                    coord_t polygon_idx = child_node->Contour.front().z();
                    bool    has_same_idx = std::all_of(child_node->Contour.begin(), child_node->Contour.end(),
                        [&polygon_idx](const ClipperLib_Z::IntPoint& point) -> bool { return polygon_idx == point.z(); });
                    if (has_same_idx)
                        closed_loop_extrusions[polygon_idx]->fuzzify = true;
                }
            }
        }
        if (this->config->wall_infill_order == WallInfillOrder::InnerOuterInnerInfill) {
            if (ordered_extrusions.size() > 2) { // 3 walls minimum needed to do inner outer inner ordering
                int position = 0; // index to run the re-ordering for multiple external perimeters in a single island.
                int arr_i = 0;    // index to run through the walls
                int outer, first_internal, second_internal; // allocate index values
                // run the re-ordering for all wall loops in the same island
                while (position < ordered_extrusions.size()) {
                    outer = first_internal = second_internal = -1; // initialise all index values to -1
                    // run through the walls to get the index values that need re-ordering until the first one for each
                    // is found. Start at "position" index to enable the for loop to iterate for multiple external
                    // perimeters in a single island
                    for (arr_i = position; arr_i < ordered_extrusions.size(); ++arr_i) {
                        switch (ordered_extrusions[arr_i].extrusion->inset_idx) {
                        case 0: // external perimeter
                            if (outer == -1)
                                outer = arr_i;
                            break;
                        case 1: // first internal wall
                            if (first_internal == -1 && arr_i > outer)
                                first_internal = arr_i;
                            break;
                        case 2: // second internal wall
                            if (ordered_extrusions[arr_i].extrusion->inset_idx == 2 && second_internal == -1 &&
                                arr_i > first_internal)
                                second_internal = arr_i;
                            break;
                        }
                        if (second_internal != -1)
                            break; // found all three perimeters to re-order
                    }
                    if (outer > -1 && first_internal > -1 && second_internal > -1) { // found perimeters to re-order?
                        const auto temp = ordered_extrusions[second_internal];
                        ordered_extrusions[second_internal] = ordered_extrusions[first_internal];
                        ordered_extrusions[first_internal] = ordered_extrusions[outer];
                        ordered_extrusions[outer] = temp;
                    } else
                        break; // did not find any more candidates to re-order, so stop the while loop early
                    // go to the next perimeter to continue scanning for external walls in the same island
                    position = arr_i + 1;
                }
            }
        }
        if (ExtrusionEntityCollection extrusion_coll = traverse_extrusions(*this, ordered_extrusions); !extrusion_coll.empty())
            this->loops->append(extrusion_coll);
        ExPolygons    infill_contour = union_ex(wallToolPaths.getInnerContour());
        const coord_t spacing = (perimeters.size() == 1) ? ext_perimeter_spacing2 : perimeter_spacing;
        if (offset_ex(infill_contour, -float(spacing / 2.)).empty())
            infill_contour.clear(); // Infill region is too small, so let's filter it out.
        // create one more offset to be used as boundary for fill
        // we offset by half the perimeter spacing (to get to the actual infill boundary)
        // and then we offset back and forth by half the infill spacing to only consider the
        // non-collapsing regions
        coord_t inset =
            (loop_number < 0) ? 0 :
            (loop_number == 0) ?
            // one loop
            ext_perimeter_spacing :
            // two or more loops?
            perimeter_spacing;
        inset = coord_t(scale_(this->config->infill_wall_overlap.get_abs_value(unscale<double>(inset))));
        // simplify infill contours according to resolution
        Polygons pp;
        for (ExPolygon& ex : infill_contour)
            ex.simplify_p(m_scaled_resolution, &pp);
        ExPolygons not_filled_exp = union_ex(pp);
        // collapse too narrow infill areas
        const auto    min_perimeter_infill_spacing = coord_t(solid_infill_spacing * (1. - INSET_OVERLAP_TOLERANCE));
        ExPolygons infill_exp = offset2_ex(
            not_filled_exp,
            float(-min_perimeter_infill_spacing / 2.),
            float(inset + min_perimeter_infill_spacing / 2.));
        // append infill areas to fill_surfaces
        if (!top_fills.empty()) {
            infill_exp = union_ex(infill_exp, offset_ex(top_fills, double(inset)));
        }
        this->fill_surfaces->append(infill_exp, stInternal);
        // BBS: get the no-overlap infill expolygons
        {
            ExPolygons polyWithoutOverlap;
            polyWithoutOverlap = offset2_ex(
                not_filled_exp,
                float(-min_perimeter_infill_spacing / 2.),
                float(+min_perimeter_infill_spacing / 2.));
            if (!top_fills.empty())
                polyWithoutOverlap = union_ex(polyWithoutOverlap, top_fills);
            this->fill_no_overlap->insert(this->fill_no_overlap->end(), polyWithoutOverlap.begin(), polyWithoutOverlap.end());
        }
    }
}
References Slic3r::ExtrusionEntityCollection::append(), Slic3r::SurfaceCollection::append(), config, Slic3r::debug_out_path(), Slic3r::ExtrusionEntityCollection::empty(), Slic3r::empty(), ext_perimeter_flow, Slic3r::External, fill_no_overlap, fill_surfaces, Slic3r::Arachne::WallToolPaths::getInnerContour(), Slic3r::Arachne::WallToolPaths::getRegionOrder(), Slic3r::Arachne::WallToolPaths::getToolPaths(), Slic3r::InfillOuterInner, Slic3r::InnerOuterInnerInfill, INSET_OVERLAP_TOLERANCE, int, Slic3r::intersection_ex(), layer_height, layer_id, loops, lower_slices, m_ext_mm3_per_mm, m_lower_slices_polygons, m_mm3_per_mm, m_mm3_per_mm_overhang, m_scaled_resolution, Slic3r::Arachne::WallToolPathsParams::min_bead_width, Slic3r::Arachne::WallToolPathsParams::min_feature_size, Slic3r::Flow::mm3_per_mm(), Slic3r::None, object_config, Slic3r::offset(), Slic3r::offset2_ex(), Slic3r::offset_ex(), Slic3r::OuterInnerInfill, overhang_flow, perimeter_flow, print_config, scale_, Slic3r::Flow::scaled_spacing(), Slic3r::Flow::scaled_width(), slices, solid_infill_flow, Slic3r::Flow::spacing(), split_top_surfaces(), Slic3r::stInternal, Slic3r::SurfaceCollection::surfaces, Slic3r::to_polygons(), Slic3r::traverse_extrusions(), Slic3r::union_ex(), Slic3r::Arachne::WallToolPathsParams::wall_distribution_count, Slic3r::Arachne::WallToolPathsParams::wall_transition_angle, Slic3r::Arachne::WallToolPathsParams::wall_transition_filter_deviation, and Slic3r::Arachne::WallToolPathsParams::wall_transition_length.
Referenced by Slic3r::LayerRegion::make_perimeters().
process_classic()
void Slic3r::PerimeterGenerator::process_classic ()
{
    // other perimeters
    m_mm3_per_mm                  = this->perimeter_flow.mm3_per_mm();
    coord_t perimeter_width         = this->perimeter_flow.scaled_width();
    coord_t perimeter_spacing       = this->perimeter_flow.scaled_spacing();
    // external perimeters
    m_ext_mm3_per_mm              = this->ext_perimeter_flow.mm3_per_mm();
    coord_t ext_perimeter_width     = this->ext_perimeter_flow.scaled_width();
    coord_t ext_perimeter_spacing   = this->ext_perimeter_flow.scaled_spacing();
    coord_t ext_perimeter_spacing2;
    if(config->precise_outer_wall)
        ext_perimeter_spacing2 = scaled<coord_t>(0.5f * (this->ext_perimeter_flow.width() + this->perimeter_flow.width()));
    else
        ext_perimeter_spacing2 = scaled<coord_t>(0.5f * (this->ext_perimeter_flow.spacing() + this->perimeter_flow.spacing()));
    // overhang perimeters
    m_mm3_per_mm_overhang         = this->overhang_flow.mm3_per_mm();
    // solid infill
    coord_t solid_infill_spacing    = this->solid_infill_flow.scaled_spacing();
    // Calculate the minimum required spacing between two adjacent traces.
    // This should be equal to the nominal flow spacing but we experiment
    // with some tolerance in order to avoid triggering medial axis when
    // some squishing might work. Loops are still spaced by the entire
    // flow spacing; this only applies to collapsing parts.
    // For ext_min_spacing we use the ext_perimeter_spacing calculated for two adjacent
    // external loops (which is the correct way) instead of using ext_perimeter_spacing2
    // which is the spacing between external and internal, which is not correct
    // and would make the collapsing (thus the details resolution) dependent on
    // internal flow which is unrelated.
    coord_t min_spacing         = coord_t(perimeter_spacing      * (1 - INSET_OVERLAP_TOLERANCE));
    coord_t ext_min_spacing     = coord_t(ext_perimeter_spacing  * (1 - INSET_OVERLAP_TOLERANCE));
    bool    has_gap_fill    = this->config->gap_infill_speed.value > 0;
    // BBS: this flow is for smaller external perimeter for small area
    coord_t ext_min_spacing_smaller = coord_t(ext_perimeter_spacing * (1 - SMALLER_EXT_INSET_OVERLAP_TOLERANCE));
    this->smaller_ext_perimeter_flow = this->ext_perimeter_flow;
    // BBS: to be checked
    this->smaller_ext_perimeter_flow = this->smaller_ext_perimeter_flow.with_width(SCALING_FACTOR *
        (ext_perimeter_width - 0.5 * SMALLER_EXT_INSET_OVERLAP_TOLERANCE * ext_perimeter_spacing));
    m_ext_mm3_per_mm_smaller_width = this->smaller_ext_perimeter_flow.mm3_per_mm();
    // prepare grown lower layer slices for overhang detection
    m_lower_polygons_series = generate_lower_polygons_series(this->perimeter_flow.width());
    if (ext_perimeter_width == perimeter_width)
        m_external_lower_polygons_series = m_lower_polygons_series;
    else
        m_external_lower_polygons_series = generate_lower_polygons_series(this->ext_perimeter_flow.width());
    m_smaller_external_lower_polygons_series = generate_lower_polygons_series(this->smaller_ext_perimeter_flow.width());
    // we need to process each island separately because we might have different
    // extra perimeters for each one
    // BBS: don't simplify too much which influence arc fitting when export gcode if arc_fitting is enabled
    double surface_simplify_resolution = (print_config->enable_arc_fitting && this->config->fuzzy_skin == FuzzySkinType::None) ? 0.2 * m_scaled_resolution : m_scaled_resolution;
    for (const Surface &surface : this->slices->surfaces) {
        // detect how many perimeters must be generated for this island
        int        loop_number = this->config->wall_loops + surface.extra_perimeters - 1;  // 0-indexed loops
        if (this->layer_id == 0 && this->config->only_one_wall_first_layer)
            loop_number = 0;
        //BBS: set the topmost layer to be one wall
        if (loop_number > 0 && config->only_one_wall_top && this->upper_slices == nullptr)
            loop_number = 0;
        ExPolygons last        = union_ex(surface.expolygon.simplify_p(surface_simplify_resolution));
        ExPolygons gaps;
        ExPolygons top_fills;
        ExPolygons fill_clip;
        if (loop_number >= 0) {
            // In case no perimeters are to be generated, loop_number will equal to -1.
            std::vector<PerimeterGeneratorLoops> contours(loop_number+1);    // depth => loops
            std::vector<PerimeterGeneratorLoops> holes(loop_number+1);       // depth => loops
            ThickPolylines thin_walls;
            // we loop one time more than needed in order to find gaps after the last perimeter was applied
            for (int i = 0;; ++ i) {  // outer loop is 0
                // Calculate next onion shell of perimeters.
                ExPolygons offsets;
                ExPolygons offsets_with_smaller_width;
                if (i == 0) {
                    // look for thin walls
                    if (this->config->detect_thin_wall) {
                        // the minimum thickness of a single loop is:
                        // ext_width/2 + ext_spacing/2 + spacing/2 + width/2
                        offsets = offset2_ex(last,
                            -float(ext_perimeter_width / 2. + ext_min_spacing / 2. - 1),
                            +float(ext_min_spacing / 2. - 1));
                        // the following offset2 ensures almost nothing in @thin_walls is narrower than $min_width
                        // (actually, something larger than that still may exist due to mitering or other causes)
                        coord_t min_width = coord_t(scale_(this->ext_perimeter_flow.nozzle_diameter() / 3));
                        ExPolygons expp = opening_ex(
                            // medial axis requires non-overlapping geometry
                            diff_ex(last, offset(offsets, float(ext_perimeter_width / 2.) + ClipperSafetyOffset)),
                            float(min_width / 2.));
                        // the maximum thickness of our thin wall area is equal to the minimum thickness of a single loop
                        for (ExPolygon &ex : expp)
                            ex.medial_axis(min_width, ext_perimeter_width + ext_perimeter_spacing2, &thin_walls);
                    } else {
                        coord_t ext_perimeter_smaller_width = this->smaller_ext_perimeter_flow.scaled_width();
                        for (const ExPolygon& expolygon : last) {
                            // BBS: judge whether it's narrow but not too long island which is hard to place two line
                            ExPolygons expolys;
                            expolys.push_back(expolygon);
                            ExPolygons offset_result = offset2_ex(expolys,
                                -float(ext_perimeter_width / 2. + ext_min_spacing_smaller / 2.),
                                +float(ext_min_spacing_smaller / 2.));
                            if (offset_result.empty() &&
                                expolygon.area() < (double)(ext_perimeter_width + ext_min_spacing_smaller) * scale_(narrow_loop_length_threshold)) {
                                // BBS: for narrow external loop, use smaller line width
                                ExPolygons temp_result = offset_ex(expolygon, -float(ext_perimeter_smaller_width / 2.));
                                offsets_with_smaller_width.insert(offsets_with_smaller_width.end(), temp_result.begin(), temp_result.end());
                            }
                            else {
                                //BBS: for not narrow loop, use normal external perimeter line width
                                ExPolygons temp_result = offset_ex(expolygon, -float(ext_perimeter_width / 2.));
                                offsets.insert(offsets.end(), temp_result.begin(), temp_result.end());
                            }
                        }
                    }
                    if (m_spiral_vase && (offsets.size() > 1 || offsets_with_smaller_width.size() > 1)) {
                        // Remove all but the largest area polygon.
                        keep_largest_contour_only(offsets);
                        //BBS
                        if (offsets.empty())
                            //BBS: only have small width loop, then keep the largest in spiral vase mode
                            keep_largest_contour_only(offsets_with_smaller_width);
                        else
                            //BBS: have large area, clean the small width loop
                            offsets_with_smaller_width.clear();
                    }
                } else {
                    //FIXME Is this offset correct if the line width of the inner perimeters differs
                    // from the line width of the infill?
                    coord_t distance = (i == 1) ? ext_perimeter_spacing2 : perimeter_spacing;
                    //BBS
                    //offsets = this->config->thin_walls ?
                        // This path will ensure, that the perimeters do not overfill, as in
                        // prusa3d/Slic3r GH #32, but with the cost of rounding the perimeters
                        // excessively, creating gaps, which then need to be filled in by the not very
                        // reliable gap fill algorithm.
                        // Also the offset2(perimeter, -x, x) may sometimes lead to a perimeter, which is larger than
                        // the original.
                        //offset2_ex(last,
                        //        - float(distance + min_spacing / 2. - 1.),
                        //        float(min_spacing / 2. - 1.)) :
                        // If "detect thin walls" is not enabled, this paths will be entered, which
                        // leads to overflows, as in prusa3d/Slic3r GH #32
                        //offset_ex(last, - float(distance));
                    //BBS: For internal perimeter, we should "enable" thin wall strategy in which offset2 is used to
                    // remove too closed line, so that gap fill can be used for such internal narrow area in following
                    // handling.
                    offsets = offset2_ex(last,
                        -float(distance + min_spacing / 2. - 1.),
                        float(min_spacing / 2. - 1.));
                    // look for gaps
                    if (has_gap_fill)
                        // not using safety offset here would "detect" very narrow gaps
                        // (but still long enough to escape the area threshold) that gap fill
                        // won't be able to fill but we'd still remove from infill area
                        append(gaps, diff_ex(
                            offset(last,    - float(0.5 * distance)),
                            offset(offsets,   float(0.5 * distance + 10))));  // safety offset
                }
                if (offsets.empty() && offsets_with_smaller_width.empty()) {
                    // Store the number of loops actually generated.
                    loop_number = i - 1;
                    // No region left to be filled in.
                    last.clear();
                    break;
                } else if (i > loop_number) {
                    // If i > loop_number, we were looking just for gaps.
                    break;
                }
                {
                    const bool fuzzify_contours = this->config->fuzzy_skin != FuzzySkinType::None && ((i == 0 && this->layer_id > 0) || this->config->fuzzy_skin == FuzzySkinType::AllWalls);
                    const bool fuzzify_holes = fuzzify_contours && (this->config->fuzzy_skin == FuzzySkinType::All || this->config->fuzzy_skin == FuzzySkinType::AllWalls);
                    for (const ExPolygon& expolygon : offsets) {
                        // Outer contour may overlap with an inner contour,
                        // inner contour may overlap with another inner contour,
                        // outer contour may overlap with itself.
                        //FIXME evaluate the overlaps, annotate each point with an overlap depth,
                        // compensate for the depth of intersection.
                        contours[i].emplace_back(expolygon.contour, i, true, fuzzify_contours);
                        if (!expolygon.holes.empty()) {
                            holes[i].reserve(holes[i].size() + expolygon.holes.size());
                            for (const Polygon& hole : expolygon.holes)
                                holes[i].emplace_back(hole, i, false, fuzzify_holes);
                        }
                    }
                    //BBS: save perimeter loop which use smaller width
                    if (i == 0) {
                        for (const ExPolygon& expolygon : offsets_with_smaller_width) {
                            contours[i].emplace_back(PerimeterGeneratorLoop(expolygon.contour, i, true, fuzzify_contours, true));
                            if (!expolygon.holes.empty()) {
                                holes[i].reserve(holes[i].size() + expolygon.holes.size());
                                for (const Polygon& hole : expolygon.holes)
                                    holes[i].emplace_back(PerimeterGeneratorLoop(hole, i, false, fuzzify_contours, true));
                            }
                        }
                    }
                }
                last = std::move(offsets);
                //BBS: refer to superslicer
                //store surface for top infill if only_one_wall_top
                if (i == 0 && i!=loop_number && config->only_one_wall_top && this->upper_slices != NULL) {
                    this->split_top_surfaces(last, top_fills, last, fill_clip);
                }
                if (i == loop_number && (! has_gap_fill || this->config->sparse_infill_density.value == 0)) {
                  // The last run of this loop is executed to collect gaps for gap fill.
                  // As the gap fill is either disabled or not
                  break;
                }
            }
            // nest loops: holes first
            for (int d = 0; d <= loop_number; ++ d) {
                PerimeterGeneratorLoops &holes_d = holes[d];
                // loop through all holes having depth == d
                for (int i = 0; i < (int)holes_d.size(); ++ i) {
                    const PerimeterGeneratorLoop &loop = holes_d[i];
                    // find the hole loop that contains this one, if any
                    for (int t = d + 1; t <= loop_number; ++ t) {
                        for (int j = 0; j < (int)holes[t].size(); ++ j) {
                            PerimeterGeneratorLoop &candidate_parent = holes[t][j];
                            if (candidate_parent.polygon.contains(loop.polygon.first_point())) {
                                candidate_parent.children.push_back(loop);
                                holes_d.erase(holes_d.begin() + i);
                                -- i;
                                goto NEXT_LOOP;
                            }
                        }
                    }
                    // if no hole contains this hole, find the contour loop that contains it
                    for (int t = loop_number; t >= 0; -- t) {
                        for (int j = 0; j < (int)contours[t].size(); ++ j) {
                            PerimeterGeneratorLoop &candidate_parent = contours[t][j];
                            if (candidate_parent.polygon.contains(loop.polygon.first_point())) {
                                candidate_parent.children.push_back(loop);
                                holes_d.erase(holes_d.begin() + i);
                                -- i;
                                goto NEXT_LOOP;
                            }
                        }
                    }
                    NEXT_LOOP: ;
                }
            }
            // nest contour loops
            for (int d = loop_number; d >= 1; -- d) {
                PerimeterGeneratorLoops &contours_d = contours[d];
                // loop through all contours having depth == d
                for (int i = 0; i < (int)contours_d.size(); ++ i) {
                    const PerimeterGeneratorLoop &loop = contours_d[i];
                    // find the contour loop that contains it
                    for (int t = d - 1; t >= 0; -- t) {
                        for (size_t j = 0; j < contours[t].size(); ++ j) {
                            PerimeterGeneratorLoop &candidate_parent = contours[t][j];
                            if (candidate_parent.polygon.contains(loop.polygon.first_point())) {
                                candidate_parent.children.push_back(loop);
                                contours_d.erase(contours_d.begin() + i);
                                -- i;
                                goto NEXT_CONTOUR;
                            }
                        }
                    }
                    NEXT_CONTOUR: ;
                }
            }
            // at this point, all loops should be in contours[0]
            ExtrusionEntityCollection entities = traverse_loops(*this, contours.front(), thin_walls);
            // if brim will be printed, reverse the order of perimeters so that
            // we continue inwards after having finished the brim
            // TODO: add test for perimeter order
            bool is_outer_wall_first =
                this->config->wall_infill_order == WallInfillOrder::OuterInnerInfill ||
                this->config->wall_infill_order == WallInfillOrder::InfillOuterInner;
            if (is_outer_wall_first ||
                //BBS: always print outer wall first when there indeed has brim.
                (this->layer_id == 0 &&
                    this->object_config->brim_type == BrimType::btOuterOnly &&
                    this->object_config->brim_width.value > 0))
                entities.reverse();
            // SoftFever: sandwich mode
            else if (this->config->wall_infill_order == WallInfillOrder::InnerOuterInnerInfill)
                if (entities.entities.size() > 1){
                    int              last_outer=0;
                    int              outer = 0;
                    for (; outer < entities.entities.size(); ++outer)
                        if (entities.entities[outer]->role() == erExternalPerimeter && outer - last_outer > 1) {
                            std::swap(entities.entities[outer], entities.entities[outer - 1]);
                            last_outer = outer;
                        }
                }
            // append perimeters for this slice as a collection
            if (! entities.empty())
                this->loops->append(entities);
        } // for each loop of an island
        // fill gaps
        if (! gaps.empty()) {
            // collapse
            double min = 0.2 * perimeter_width * (1 - INSET_OVERLAP_TOLERANCE);
            double max = 2. * perimeter_spacing;
            ExPolygons gaps_ex = diff_ex(
                //FIXME offset2 would be enough and cheaper.
                opening_ex(gaps, float(min / 2.)),
                offset2_ex(gaps, - float(max / 2.), float(max / 2. + ClipperSafetyOffset)));
            ThickPolylines polylines;
            for (ExPolygon& ex : gaps_ex) {
                //BBS: Use DP simplify to avoid duplicated points and accelerate medial-axis calculation as well.
                ex.douglas_peucker(surface_simplify_resolution);
                ex.medial_axis(min, max, &polylines);
            }
#ifdef GAPS_OF_PERIMETER_DEBUG_TO_SVG
            {
                static int irun = 0;
                BoundingBox bbox_svg;
                bbox_svg.merge(get_extents(gaps_ex));
                {
                    std::stringstream stri;
                    stri << "debug_gaps_ex_" << irun << ".svg";
                    SVG svg(stri.str(), bbox_svg);
                    svg.draw(to_polylines(gaps_ex), "blue", 0.5);
                    svg.Close();
                }
                ++ irun;
            }
#endif
            // SoftFever: filter out tiny gap fills
            polylines.erase(std::remove_if(polylines.begin(), polylines.end(),
                [&](const ThickPolyline& p) {
                    return p.length() < scale_(config->filter_out_gap_fill.value);
                }), polylines.end());
            if (! polylines.empty()) {
        ExtrusionEntityCollection gap_fill;
        variable_width(polylines, erGapFill, this->solid_infill_flow, gap_fill.entities);
                /*  Make sure we don't infill narrow parts that are already gap-filled
                    (we only consider this surface's gaps to reduce the diff() complexity).
                    Growing actual extrusions ensures that gaps not filled by medial axis
                    are not subtracted from fill surfaces (they might be too short gaps
                    that medial axis skips but infill might join with other infill regions
                    and use zigzag).  */
                //FIXME Vojtech: This grows by a rounded extrusion width, not by line spacing,
                // therefore it may cover the area, but no the volume.
                last = diff_ex(last, gap_fill.polygons_covered_by_width(10.f));
                this->gap_fill->append(std::move(gap_fill.entities));
      }
        }
        // create one more offset to be used as boundary for fill
        // we offset by half the perimeter spacing (to get to the actual infill boundary)
        // and then we offset back and forth by half the infill spacing to only consider the
        // non-collapsing regions
        coord_t inset =
            (loop_number < 0) ? 0 :
            (loop_number == 0) ?
                // one loop
                ext_perimeter_spacing / 2 :
                // two or more loops?
                perimeter_spacing / 2;
        // only apply infill overlap if we actually have one perimeter
        coord_t infill_peri_overlap = 0;
        if (inset > 0) {
            infill_peri_overlap = coord_t(scale_(this->config->infill_wall_overlap.get_abs_value(unscale<double>(inset + solid_infill_spacing / 2))));
            inset -= infill_peri_overlap;
        }
        // simplify infill contours according to resolution
        Polygons pp;
        for (ExPolygon &ex : last)
            ex.simplify_p(m_scaled_resolution, &pp);
        ExPolygons not_filled_exp = union_ex(pp);
        // collapse too narrow infill areas
        coord_t min_perimeter_infill_spacing = coord_t(solid_infill_spacing * (1. - INSET_OVERLAP_TOLERANCE));
        ExPolygons infill_exp = offset2_ex(
            not_filled_exp,
            float(-inset - min_perimeter_infill_spacing / 2.),
            float(min_perimeter_infill_spacing / 2.));
        // append infill areas to fill_surfaces
        //if any top_fills, grow them by ext_perimeter_spacing/2 to have the real un-anchored fill
        ExPolygons top_infill_exp = intersection_ex(fill_clip, offset_ex(top_fills, double(ext_perimeter_spacing / 2)));
        if (!top_fills.empty()) {
            infill_exp = union_ex(infill_exp, offset_ex(top_infill_exp, double(infill_peri_overlap)));
        }
        this->fill_surfaces->append(infill_exp, stInternal);
        // BBS: get the no-overlap infill expolygons
        {
            ExPolygons polyWithoutOverlap;
            if (min_perimeter_infill_spacing / 2 > infill_peri_overlap)
                polyWithoutOverlap = offset2_ex(
                    not_filled_exp,
                    float(-inset - min_perimeter_infill_spacing / 2.),
                    float(min_perimeter_infill_spacing / 2 - infill_peri_overlap));
            else
                polyWithoutOverlap = offset_ex(
                    not_filled_exp,
                    double(-inset - infill_peri_overlap));
            if (!top_fills.empty())
                polyWithoutOverlap = union_ex(polyWithoutOverlap, top_infill_exp);
            this->fill_no_overlap->insert(this->fill_no_overlap->end(), polyWithoutOverlap.begin(), polyWithoutOverlap.end());
        }
    } // for each island
}
References Slic3r::All, Slic3r::AllWalls, Slic3r::ExtrusionEntityCollection::append(), Slic3r::SurfaceCollection::append(), Slic3r::append(), Slic3r::btOuterOnly, Slic3r::PerimeterGeneratorLoop::children, Slic3r::ClipperSafetyOffset, Slic3r::SVG::Close(), config, Slic3r::Polygon::contains(), Slic3r::diff_ex(), Slic3r::SVG::draw(), Slic3r::ExtrusionEntityCollection::empty(), Slic3r::ExtrusionEntityCollection::entities, Slic3r::erExternalPerimeter, Slic3r::erGapFill, ext_perimeter_flow, fill_no_overlap, fill_surfaces, gap_fill, generate_lower_polygons_series(), Slic3r::get_extents(), Slic3r::holes(), Slic3r::InfillOuterInner, Slic3r::InnerOuterInnerInfill, INSET_OVERLAP_TOLERANCE, int, Slic3r::intersection_ex(), Slic3r::keep_largest_contour_only(), layer_id, loops, m_ext_mm3_per_mm, m_ext_mm3_per_mm_smaller_width, m_external_lower_polygons_series, m_lower_polygons_series, m_mm3_per_mm, m_mm3_per_mm_overhang, m_scaled_resolution, m_smaller_external_lower_polygons_series, m_spiral_vase, max(), Slic3r::BoundingBoxBase< PointClass >::merge(), min(), Slic3r::Flow::mm3_per_mm(), narrow_loop_length_threshold, Slic3r::None, Slic3r::Flow::nozzle_diameter(), NULL, object_config, Slic3r::offset(), Slic3r::offset2_ex(), Slic3r::offset_ex(), Slic3r::opening_ex(), Slic3r::OuterInnerInfill, overhang_flow, perimeter_flow, Slic3r::PerimeterGeneratorLoop::polygon, Slic3r::ExtrusionEntityCollection::polygons_covered_by_width(), print_config, Slic3r::ExtrusionEntityCollection::reverse(), scale_, Slic3r::Flow::scaled_spacing(), Slic3r::Flow::scaled_width(), SCALING_FACTOR, size, slices, SMALLER_EXT_INSET_OVERLAP_TOLERANCE, smaller_ext_perimeter_flow, solid_infill_flow, Slic3r::Flow::spacing(), split_top_surfaces(), Slic3r::stInternal, Slic3r::SurfaceCollection::surfaces, Slic3r::to_polylines(), Slic3r::traverse_loops(), Slic3r::union_ex(), Slic3r::variable_width(), Slic3r::Flow::width(), and Slic3r::Flow::with_width().
Referenced by Slic3r::LayerRegion::make_perimeters().
smaller_width_ext_mm3_per_mm()
double Slic3r::PerimeterGenerator::smaller_width_ext_mm3_per_mm () const inline
{ return m_ext_mm3_per_mm_smaller_width; }
References m_ext_mm3_per_mm_smaller_width.
Referenced by Slic3r::traverse_loops().
split_top_surfaces()
void Slic3r::PerimeterGenerator::split_top_surfaces (const ExPolygons & orig_polygons, ExPolygons & top_fills, ExPolygons & non_top_polygons, ExPolygons & fill_clip) const private
{
    // other perimeters
    coord_t perimeter_width = this->perimeter_flow.scaled_width();
    coord_t perimeter_spacing = this->perimeter_flow.scaled_spacing();
    // external perimeters
    coord_t ext_perimeter_width = this->ext_perimeter_flow.scaled_width();
    coord_t ext_perimeter_spacing = this->ext_perimeter_flow.scaled_spacing();
    bool has_gap_fill = this->config->gap_infill_speed.value > 0;
    // split the polygons with top/not_top
    // get the offset from solid surface anchor
    coord_t offset_top_surface =
        scale_(1.5 * (config->wall_loops.value == 0
                          ? 0.
                          : unscaled(double(ext_perimeter_width +
                                            perimeter_spacing * int(int(config->wall_loops.value) - int(1))))));
    // if possible, try to not push the extra perimeters inside the sparse infill
    if (offset_top_surface >
        0.9 * (config->wall_loops.value <= 1 ? 0. : (perimeter_spacing * (config->wall_loops.value - 1))))
        offset_top_surface -=
            coord_t(0.9 * (config->wall_loops.value <= 1 ? 0. : (perimeter_spacing * (config->wall_loops.value - 1))));
    else
        offset_top_surface = 0;
    // don't takes into account too thin areas
    // skip if the exposed area is smaller than "min_width_top_surface"
    double min_width_top_surface = std::max(double(ext_perimeter_spacing / 2 + 10), config->min_width_top_surface.get_abs_value(perimeter_width));
    Polygons grown_upper_slices = offset(*this->upper_slices, min_width_top_surface);
    // get boungding box of last
    BoundingBox last_box = get_extents(orig_polygons);
    last_box.offset(SCALED_EPSILON);
    // get the Polygons upper the polygon this layer
    Polygons upper_polygons_series_clipped =
        ClipperUtils::clip_clipper_polygons_with_subject_bbox(grown_upper_slices, last_box);
    // set the clip to a virtual "second perimeter"
    fill_clip = offset_ex(orig_polygons, -double(ext_perimeter_spacing));
    // get the real top surface
    ExPolygons grown_lower_slices;
    ExPolygons bridge_checker;
    auto nozzle_diameter = this->print_config->nozzle_diameter.get_at(this->config->wall_filament - 1);
    // Check whether surface be bridge or not
    if (this->lower_slices != NULL) {
        // BBS: get the Polygons below the polygon this layer
        Polygons lower_polygons_series_clipped =
            ClipperUtils::clip_clipper_polygons_with_subject_bbox(*this->lower_slices, last_box);
        double bridge_offset = std::max(double(ext_perimeter_spacing), (double(perimeter_width)));
        // SoftFever: improve bridging
        const float bridge_margin =
            std::min(float(scale_(BRIDGE_INFILL_MARGIN)), float(scale_(nozzle_diameter * BRIDGE_INFILL_MARGIN / 0.4)));
        bridge_checker = offset_ex(diff_ex(orig_polygons, lower_polygons_series_clipped, ApplySafetyOffset::Yes),
                                   1.5 * bridge_offset + bridge_margin + perimeter_spacing / 2);
    }
    ExPolygons delete_bridge = diff_ex(orig_polygons, bridge_checker, ApplySafetyOffset::Yes);
    ExPolygons top_polygons = diff_ex(delete_bridge, upper_polygons_series_clipped, ApplySafetyOffset::Yes);
    // get the not-top surface, from the "real top" but enlarged by external_infill_margin (and the
    // min_width_top_surface we removed a bit before)
    ExPolygons temp_gap = diff_ex(top_polygons, fill_clip);
    ExPolygons inner_polygons =
        diff_ex(orig_polygons,
                offset_ex(top_polygons, offset_top_surface + min_width_top_surface - double(ext_perimeter_spacing / 2)),
                ApplySafetyOffset::Yes);
    // get the enlarged top surface, by using inner_polygons instead of upper_slices, and clip it for it to be exactly
    // the polygons to fill.
    top_polygons = diff_ex(fill_clip, inner_polygons, ApplySafetyOffset::Yes);
    // increase by half peri the inner space to fill the frontier between last and stored.
    top_fills = union_ex(top_fills, top_polygons);
    //set the clip to the external wall but go back inside by infill_extrusion_width/2 to be sure the extrusion won't go outside even with a 100% overlap.
    double infill_spacing_unscaled = this->config->sparse_infill_line_width.get_abs_value(nozzle_diameter);
    if (infill_spacing_unscaled == 0) infill_spacing_unscaled = Flow::auto_extrusion_width(frInfill, nozzle_diameter);
    fill_clip = offset_ex(orig_polygons, double(ext_perimeter_spacing / 2) - scale_(infill_spacing_unscaled / 2));
    // ExPolygons oldLast = last;
    non_top_polygons = intersection_ex(inner_polygons, orig_polygons);
    if (has_gap_fill)
        non_top_polygons = union_ex(non_top_polygons, temp_gap);
    //{
    //    std::stringstream stri;
    //    stri << this->layer_id << "_1_"<< i <<"_only_one_peri"<< ".svg";
    //    SVG svg(stri.str());
    //    svg.draw(to_polylines(top_fills), "green");
    //    svg.draw(to_polylines(inner_polygons), "yellow");
    //    svg.draw(to_polylines(top_polygons), "cyan");
    //    svg.draw(to_polylines(oldLast), "orange");
    //    svg.draw(to_polylines(last), "red");
    //    svg.Close();
    //}
}
References Slic3r::Flow::auto_extrusion_width(), BRIDGE_INFILL_MARGIN, Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox(), config, Slic3r::diff_ex(), ext_perimeter_flow, Slic3r::frInfill, Slic3r::get_extents(), Slic3r::intersection_ex(), lower_slices, NULL, Slic3r::offset(), Slic3r::BoundingBoxBase< PointClass >::offset(), Slic3r::offset_ex(), perimeter_flow, print_config, scale_, SCALED_EPSILON, Slic3r::Flow::scaled_spacing(), Slic3r::Flow::scaled_width(), Slic3r::union_ex(), Slic3r::unscaled(), upper_slices, and Slic3r::Yes.
Referenced by process_arachne(), and process_classic().
Member Data Documentation
config
const PrintRegionConfig* Slic3r::PerimeterGenerator::config
Referenced by generate_lower_polygons_series(), process_arachne(), process_classic(), split_top_surfaces(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
ext_perimeter_flow
Flow Slic3r::PerimeterGenerator::ext_perimeter_flow
Referenced by Slic3r::LayerRegion::make_perimeters(), process_arachne(), process_classic(), split_top_surfaces(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
fill_no_overlap
ExPolygons* Slic3r::PerimeterGenerator::fill_no_overlap
Referenced by process_arachne(), and process_classic().
fill_surfaces
SurfaceCollection* Slic3r::PerimeterGenerator::fill_surfaces
Referenced by process_arachne(), and process_classic().
gap_fill
ExtrusionEntityCollection* Slic3r::PerimeterGenerator::gap_fill
Referenced by process_classic().
layer_height
double Slic3r::PerimeterGenerator::layer_height
Referenced by process_arachne(), and Slic3r::traverse_loops().
layer_id
int Slic3r::PerimeterGenerator::layer_id
Referenced by Slic3r::LayerRegion::make_perimeters(), process_arachne(), process_classic(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
loops
ExtrusionEntityCollection* Slic3r::PerimeterGenerator::loops
Referenced by process_arachne(), and process_classic().
lower_slices
const ExPolygons* Slic3r::PerimeterGenerator::lower_slices
Referenced by generate_lower_polygons_series(), Slic3r::LayerRegion::make_perimeters(), process_arachne(), split_top_surfaces(), and Slic3r::traverse_extrusions().
m_ext_mm3_per_mm
double Slic3r::PerimeterGenerator::m_ext_mm3_per_mm private
Referenced by ext_mm3_per_mm(), process_arachne(), and process_classic().
m_ext_mm3_per_mm_smaller_width
double Slic3r::PerimeterGenerator::m_ext_mm3_per_mm_smaller_width private
Referenced by process_classic(), and smaller_width_ext_mm3_per_mm().
m_external_lower_polygons_series
std::map<int, Polygons> Slic3r::PerimeterGenerator::m_external_lower_polygons_series
Referenced by process_classic(), and Slic3r::traverse_loops().
m_lower_polygons_series
std::map<int, Polygons> Slic3r::PerimeterGenerator::m_lower_polygons_series
Referenced by process_classic(), and Slic3r::traverse_loops().
m_lower_slices_polygons
Polygons Slic3r::PerimeterGenerator::m_lower_slices_polygons private
Referenced by lower_slices_polygons(), and process_arachne().
m_mm3_per_mm
double Slic3r::PerimeterGenerator::m_mm3_per_mm private
Referenced by mm3_per_mm(), process_arachne(), and process_classic().
m_mm3_per_mm_overhang
double Slic3r::PerimeterGenerator::m_mm3_per_mm_overhang private
Referenced by mm3_per_mm_overhang(), process_arachne(), and process_classic().
m_scaled_resolution
double Slic3r::PerimeterGenerator::m_scaled_resolution private
Referenced by process_arachne(), and process_classic().
m_smaller_external_lower_polygons_series
std::map<int, Polygons> Slic3r::PerimeterGenerator::m_smaller_external_lower_polygons_series
Referenced by process_classic(), and Slic3r::traverse_loops().
m_spiral_vase
bool Slic3r::PerimeterGenerator::m_spiral_vase private
Referenced by process_classic().
object_config
const PrintObjectConfig* Slic3r::PerimeterGenerator::object_config
Referenced by process_arachne(), process_classic(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
overhang_flow
Flow Slic3r::PerimeterGenerator::overhang_flow
Referenced by Slic3r::LayerRegion::make_perimeters(), process_arachne(), process_classic(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
perimeter_flow
Flow Slic3r::PerimeterGenerator::perimeter_flow
Referenced by process_arachne(), process_classic(), split_top_surfaces(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
print_config
const PrintConfig* Slic3r::PerimeterGenerator::print_config
Referenced by generate_lower_polygons_series(), process_arachne(), process_classic(), and split_top_surfaces().
slices
const SurfaceCollection* Slic3r::PerimeterGenerator::slices
Referenced by process_arachne(), and process_classic().
smaller_ext_perimeter_flow
Flow Slic3r::PerimeterGenerator::smaller_ext_perimeter_flow
Referenced by process_classic(), and Slic3r::traverse_loops().
solid_infill_flow
Flow Slic3r::PerimeterGenerator::solid_infill_flow
Referenced by Slic3r::LayerRegion::make_perimeters(), process_arachne(), and process_classic().
upper_slices
const ExPolygons* Slic3r::PerimeterGenerator::upper_slices
Referenced by Slic3r::LayerRegion::make_perimeters(), and split_top_surfaces().
The documentation for this class was generated from the following files:
src/libslic3r/PerimeterGenerator.hpp
src/libslic3r/PerimeterGenerator.cpp