OrcaSlicer: Slic3r::GUI::OTG_Settings Class Reference
Slic3r::GUI::OTG_Settings Class Reference
#include <src/slic3r/GUI/GUI_ObjectTableSettings.hpp>
Public Member Functions
OTG_Settings (wxWindow *parent, const bool staticbox)
virtual ~OTG_Settings ()
virtual bool IsShown ()
virtual void Show (const bool show)
virtual void Hide ()
virtual void UpdateAndShow (const bool show)
virtual wxSizer * get_sizer ()
ConfigOptionsGroup * get_og ()
wxWindow * parent () const
Protected Attributes
std::shared_ptr< ConfigOptionsGroup > m_og
wxWindow * m_parent
Detailed Description
Constructor & Destructor Documentation
OTG_Settings()
Slic3r::GUI::OTG_Settings::OTG_Settings (wxWindow * parent, const bool staticbox)
                                                                 :
    m_parent(parent)
{
    wxString title = ""; // temporary workaround - #ys_FIXME
    m_og = std::make_shared<ConfigOptionsGroup>(parent, title, (DynamicPrintConfig*)nullptr, true);
}
References m_og, and parent().
~OTG_Settings()
virtual Slic3r::GUI::OTG_Settings::~OTG_Settings () inline virtual
{}
Member Function Documentation
get_og()
ConfigOptionsGroup * Slic3r::GUI::OTG_Settings::get_og () inline
{ return m_og.get(); }
References m_og.
get_sizer()
wxSizer * Slic3r::GUI::OTG_Settings::get_sizer () virtual
{
    return m_og->sizer;
}
References m_og.
Hide()
void Slic3r::GUI::OTG_Settings::Hide () virtual
{
    Show(false);
}
References Show().
IsShown()
bool Slic3r::GUI::OTG_Settings::IsShown () virtual
{
    return m_og->sizer->IsEmpty() ? false : m_og->sizer->IsShown(size_t(0));
}
References m_og.
parent()
wxWindow * Slic3r::GUI::OTG_Settings::parent () const inline
{return m_parent; }
References m_parent.
Referenced by Slic3r::GUI::ObjectTableSettings::ObjectTableSettings(), OTG_Settings(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
Show()
void Slic3r::GUI::OTG_Settings::Show (const bool show) virtual
{
    m_og->Show(show);
}
References m_og.
Referenced by Hide(), Slic3r::GUI::ObjectTableSettings::update_settings_list(), and UpdateAndShow().
UpdateAndShow()
void Slic3r::GUI::OTG_Settings::UpdateAndShow (const bool show) virtual
{
    Show(show);
//    m_parent->Layout();
}
References Show().
Referenced by Slic3r::GUI::ObjectTableSettings::UpdateAndShow().
Member Data Documentation
m_og
std::shared_ptr<ConfigOptionsGroup> Slic3r::GUI::OTG_Settings::m_og protected
Referenced by Slic3r::GUI::ObjectTableSettings::ObjectTableSettings(), OTG_Settings(), get_og(), get_sizer(), IsShown(), Show(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
m_parent
wxWindow* Slic3r::GUI::OTG_Settings::m_parent protected
Referenced by parent(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTableSettings.hpp
src/slic3r/GUI/GUI_ObjectTableSettings.cpp