OrcaSlicer: Slic3r::GUI::Tab::Highlighter Struct Reference
Slic3r::GUI::Tab::Highlighter Struct Reference
#include <src/slic3r/GUI/Tab.hpp>
Public Member Functions
void set_timer_owner (wxEvtHandler *owner, int timerid=wxID_ANY)
void init (std::pair< OG_CustomCtrl *, bool * >)
void blink ()
void invalidate ()
Private Attributes
OG_CustomCtrl * m_custom_ctrl {nullptr}
bool * m_show_blink_ptr {nullptr}
int m_blink_counter {0}
wxTimer m_timer
Detailed Description
Member Function Documentation
blink()
void Slic3r::GUI::Tab::Highlighter::blink ()
{
    if (m_custom_ctrl && m_show_blink_ptr) {
        *m_show_blink_ptr = !*m_show_blink_ptr;
        m_custom_ctrl->Refresh();
    }
    else
        return;
    if ((++m_blink_counter) == 11)
        invalidate();
}
Referenced by Slic3r::GUI::Tab::Tab().
init()
void Slic3r::GUI::Tab::Highlighter::init (std::pair< OG_CustomCtrl *, bool * > params)
{
    if (m_timer.IsRunning())
        invalidate();
    if (!params.first || !params.second)
        return;
    m_timer.Start(300, false);
    m_custom_ctrl = params.first;
    m_show_blink_ptr = params.second;
    *m_show_blink_ptr = true;
    m_custom_ctrl->Refresh();
}
invalidate()
void Slic3r::GUI::Tab::Highlighter::invalidate ()
{
    m_timer.Stop();
    if (m_custom_ctrl && m_show_blink_ptr) {
        *m_show_blink_ptr = false;
        m_custom_ctrl->Refresh();
        m_show_blink_ptr = nullptr;
        m_custom_ctrl = nullptr;
    }
    m_blink_counter = 0;
}
Referenced by Slic3r::GUI::Tab::clear_pages(), and Slic3r::GUI::Tab::update_current_page_in_background().
set_timer_owner()
void Slic3r::GUI::Tab::Highlighter::set_timer_owner (wxEvtHandler * owner, int timerid = wxID_ANY)
{
    m_timer.SetOwner(owner, timerid);
}
References m_timer.
Referenced by Slic3r::GUI::Tab::Tab().
Member Data Documentation
m_blink_counter
int Slic3r::GUI::Tab::Highlighter::m_blink_counter {0} private
m_custom_ctrl
OG_CustomCtrl* Slic3r::GUI::Tab::Highlighter::m_custom_ctrl {nullptr} private
m_show_blink_ptr
bool* Slic3r::GUI::Tab::Highlighter::m_show_blink_ptr {nullptr} private
m_timer
wxTimer Slic3r::GUI::Tab::Highlighter::m_timer private
Referenced by set_timer_owner().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/Tab.hpp
src/slic3r/GUI/Tab.cpp