OrcaSlicer: Slic3r::GUI::DynamicFilamentList Struct Reference
Slic3r::GUI::DynamicFilamentList Struct Reference
Public Member Functions
void apply_on (Choice *c) override
wxString get_value (int index) override
int index_of (wxString value) override
void update (bool force=false)
Public Attributes
std::vector< std::pair< wxString, wxBitmap * > > items
Protected Member Functions
void update ()
Protected Attributes
std::vector< Choice * > m_choices
Private Member Functions
void add_choice (Choice *choice)
void remove_choice (Choice *choice)
Detailed Description
Member Function Documentation
add_choice()
void Slic3r::GUI::DynamicList::add_choice (Choice * choice) private inherited
{
    auto iter = std::find(m_choices.begin(), m_choices.end(), choice);
    if (iter != m_choices.end()) return;
    apply_on(choice);
    m_choices.push_back(choice);
}
apply_on()
void Slic3r::GUI::DynamicFilamentList::apply_on (Choice * c) inline override virtual
Implements Slic3r::GUI::DynamicList.
    {
        if (items.empty())
            update(true);
        auto cb = dynamic_cast<ComboBox *>(c->window);
        auto n  = cb->GetSelection();
        cb->Clear();
        cb->Append(_L("Default"));
        for (auto i : items) {
            cb->Append(i.first, *i.second);
        }
        if (n < cb->GetCount())
            cb->SetSelection(n);
    }
References _L, and n.
get_value()
wxString Slic3r::GUI::DynamicFilamentList::get_value (int index) inline override virtual
Implements Slic3r::GUI::DynamicList.
    {
        wxString str;
        str << index;
        return str;
    }
index_of()
int Slic3r::GUI::DynamicFilamentList::index_of (wxString value) inline override virtual
Implements Slic3r::GUI::DynamicList.
    {
        long n = 0;
        return (value.ToLong(&n) && n <= items.size()) ? int(n) : -1;
    }
References int, and n.
remove_choice()
void Slic3r::GUI::DynamicList::remove_choice (Choice * choice) private inherited
{
    auto iter = std::find(m_choices.begin(), m_choices.end(), choice);
    if (iter != m_choices.end()) m_choices.erase(iter);
}
update() [1/2]
void Slic3r::GUI::DynamicList::update () protected inherited
{
    for (auto c : m_choices) apply_on(c);
}
Referenced by update().
update() [2/2]
void Slic3r::GUI::DynamicFilamentList::update (bool force = false) inline
    {
        items.clear();
        if (!force && m_choices.empty())
            return;
        auto icons = get_extruder_color_icons(true);
        auto presets = wxGetApp().preset_bundle->filament_presets;
        for (int i = 0; i < presets.size(); ++i) {
            wxString str;
            std::string type;
            wxGetApp().preset_bundle->filaments.find_preset(presets[i])->get_filament_type(type);
            str << type;
            items.push_back({str, icons[i]});
        }
        DynamicList::update();
    }
References get_extruder_color_icons(), and Slic3r::GUI::DynamicList::update().
Referenced by Slic3r::GUI::Plater::on_config_change(), Slic3r::GUI::Sidebar::on_filaments_change(), Slic3r::GUI::Plater::priv::on_select_preset(), Slic3r::GUI::Sidebar::sync_ams_list(), and Slic3r::GUI::Sidebar::update_presets().
Member Data Documentation
items
std::vector<std::pair<wxString, wxBitmap *> > Slic3r::GUI::DynamicFilamentList::items
m_choices
std::vector<Choice*> Slic3r::GUI::DynamicList::m_choices protected inherited
The documentation for this struct was generated from the following file:
src/slic3r/GUI/Plater.cpp