OrcaSlicer: Slic3r::GUI::AMSItem Class Reference
Slic3r::GUI::AMSItem Class Reference
#include <src/slic3r/GUI/Widgets/AMSControl.hpp>
Public Member Functions
AMSItem ()
AMSItem (wxWindow *parent, wxWindowID id, AMSinfo amsinfo, const wxSize cube_size=wxSize(14, 14), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
void Open ()
void Close ()
void Update (AMSinfo amsinfo)
void create (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size)
void OnEnterWindow (wxMouseEvent &evt)
void OnLeaveWindow (wxMouseEvent &evt)
void OnSelected ()
void UnSelected ()
void ShowHumidity ()
void HideHumidity ()
void SetHumidity (int humidity)
virtual bool Enable (bool enable=true)
Public Attributes
bool m_open = {false}
AMSinfo m_amsinfo
Protected Member Functions
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
Protected Attributes
wxSize m_cube_size
wxColour m_background_colour = {AMS_CONTROL_DEF_BLOCK_BK_COLOUR}
int m_padding = {6}
int m_space = {5}
bool m_hover = {false}
bool m_selected = {false}
bool m_show_humidity = {false}
int m_humidity = {0}
Detailed Description
Constructor & Destructor Documentation
AMSItem() [1/2]
Slic3r::GUI::AMSItem::AMSItem ()
{}
AMSItem() [2/2]
Slic3r::GUI::AMSItem::AMSItem (wxWindow * parent, wxWindowID id, AMSinfo amsinfo, const wxSize cube_size = wxSize(14, 14), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
                                                                                                                                 : AMSItem()
{
    m_amsinfo   = amsinfo;
    m_cube_size = cube_size;
    create(parent, id, pos, size);
    Bind(wxEVT_PAINT, &AMSItem::paintEvent, this);
    Bind(wxEVT_ENTER_WINDOW, &AMSItem::OnEnterWindow, this);
    Bind(wxEVT_LEAVE_WINDOW, &AMSItem::OnLeaveWindow, this);
}
References create(), m_amsinfo, m_cube_size, OnEnterWindow(), OnLeaveWindow(), paintEvent(), and size.
Member Function Documentation
Close()
void Slic3r::GUI::AMSItem::Close ()
{
    m_open = false;
    Hide();
}
References m_open.
Referenced by Slic3r::GUI::AMSControl::UpdateAms().
create()
void Slic3r::GUI::AMSItem::create (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size)
{
    wxWindow::Create(parent, id, pos, size);
    SetBackgroundColour(AMS_CONTROL_WHITE_COLOUR);
    HideHumidity();
    Refresh();
}
References AMS_CONTROL_WHITE_COLOUR, HideHumidity(), and size.
Referenced by AMSItem().
doRender()
void Slic3r::GUI::AMSItem::doRender (wxDC & dc) protected
{
    wxSize size = GetSize();
    dc.SetPen(wxPen(StateColor::darkModeColorFor(m_background_colour)));
    dc.SetBrush(wxBrush(StateColor::darkModeColorFor(m_background_colour)));
    dc.DrawRoundedRectangle(0, 0, size.x, size.y, 3);
    auto left = m_padding;
    for (std::vector<Caninfo>::iterator iter = m_amsinfo.cans.begin(); iter != m_amsinfo.cans.end(); iter++) {
        dc.SetPen(wxPen(*wxTRANSPARENT_PEN));
        if (wxWindow::IsEnabled()) {
            dc.SetBrush(wxBrush(iter->material_colour));
        } else {
            dc.SetBrush(AMS_CONTROL_DISABLE_COLOUR);
        }
        if (iter->material_cols.size() > 1) {
            int fleft = left;
            float total_width = AMS_ITEM_CUBE_SIZE.x;
            int gwidth = std::round(total_width / (iter->material_cols.size() - 1));
            for (int i = 0; i < iter->material_cols.size() - 1; i++) {
                if ((fleft + gwidth) > (AMS_ITEM_CUBE_SIZE.x)) {
                    gwidth = (fleft + AMS_ITEM_CUBE_SIZE.x) - fleft;
                }
                auto rect = wxRect(fleft, (size.y - AMS_ITEM_CUBE_SIZE.y) / 2, gwidth, AMS_ITEM_CUBE_SIZE.y);
                dc.GradientFillLinear(rect, iter->material_cols[i], iter->material_cols[i + 1], wxEAST);
                fleft += gwidth;
            }
            dc.SetPen(wxPen(StateColor::darkModeColorFor(m_background_colour)));
            dc.SetBrush(*wxTRANSPARENT_BRUSH);
            dc.DrawRoundedRectangle(left - 1, (size.y - AMS_ITEM_CUBE_SIZE.y) / 2 - 1, AMS_ITEM_CUBE_SIZE.x + 2, AMS_ITEM_CUBE_SIZE.y + 2, 2);
        }else {
            dc.DrawRoundedRectangle(left, (size.y - AMS_ITEM_CUBE_SIZE.y) / 2, AMS_ITEM_CUBE_SIZE.x, AMS_ITEM_CUBE_SIZE.y, 2);
        }
        left += AMS_ITEM_CUBE_SIZE.x;
        left += m_space;
    }
    m_show_humidity = false;
    if (m_show_humidity) {
        left = 4 * AMS_ITEM_CUBE_SIZE.x + 6 * m_space;
        dc.SetPen(wxPen(AMS_CONTROL_GRAY500, 1));
        dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
        dc.DrawLine(left, (size.y - AMS_ITEM_CUBE_SIZE.y) / 2, left, ((size.y - AMS_ITEM_CUBE_SIZE.y) / 2) + AMS_ITEM_CUBE_SIZE.y);
        left += m_space + m_space / 2;
        /* dc.SetFont(::Label::Body_13);
         dc.SetTextForeground(AMS_CONTROL_GRAY800);
         auto tsize = dc.GetTextExtent("00% RH");
         auto text  = wxString::Format("%d%% RH", m_humidity);*/
    }
    auto border_colour = AMS_CONTROL_BRAND_COLOUR;
    if (!wxWindow::IsEnabled()) { border_colour = AMS_CONTROL_DISABLE_COLOUR; }
    if (m_hover) {
        dc.SetPen(wxPen(border_colour, 1));
        dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
        dc.DrawRoundedRectangle(0, 0, size.x, size.y, 3);
    }
    if (m_selected) {
        dc.SetPen(wxPen(border_colour, 1));
        dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
        dc.DrawRoundedRectangle(0, 0, size.x, size.y, 3);
    }
}
References AMS_CONTROL_BRAND_COLOUR, AMS_CONTROL_DISABLE_COLOUR, AMS_CONTROL_GRAY500, AMS_ITEM_CUBE_SIZE, Slic3r::GUI::AMSinfo::cans, StateColor::darkModeColorFor(), m_amsinfo, m_background_colour, m_hover, m_padding, m_selected, m_show_humidity, m_space, and size.
Referenced by render().
DoSetSize()
void Slic3r::GUI::AMSItem::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) protected virtual
{ wxWindow::DoSetSize(x, y, width, height, sizeFlags); }
Enable()
bool Slic3r::GUI::AMSItem::Enable (bool enable = true) virtual
{ return wxWindow::Enable(enable); }
Referenced by Slic3r::GUI::AMSControl::Enable().
HideHumidity()
void Slic3r::GUI::AMSItem::HideHumidity ()
{
    m_show_humidity = false;
    SetSize(AMS_ITEM_SIZE);
    SetMinSize(AMS_ITEM_SIZE);
    Refresh();
}
References AMS_ITEM_SIZE, and m_show_humidity.
Referenced by create().
OnEnterWindow()
void Slic3r::GUI::AMSItem::OnEnterWindow (wxMouseEvent & evt)
{
    // m_hover = true;
    // Refresh();
}
Referenced by AMSItem().
OnLeaveWindow()
void Slic3r::GUI::AMSItem::OnLeaveWindow (wxMouseEvent & evt)
{
    // m_hover = false;
    // Refresh();
}
Referenced by AMSItem().
OnSelected()
void Slic3r::GUI::AMSItem::OnSelected ()
{
    if (!wxWindow::IsEnabled()) { return; }
    m_selected = true;
    Refresh();
}
References m_selected.
Referenced by Slic3r::GUI::AMSControl::SwitchAms().
Open()
void Slic3r::GUI::AMSItem::Open ()
{
    m_open = true;
    Show();
}
References m_open.
Referenced by Slic3r::GUI::AMSControl::UpdateAms().
paintEvent()
void Slic3r::GUI::AMSItem::paintEvent (wxPaintEvent & evt) protected
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by AMSItem().
render()
void Slic3r::GUI::AMSItem::render (wxDC & dc) protected
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
SetHumidity()
void Slic3r::GUI::AMSItem::SetHumidity (int humidity)
{
    m_humidity = humidity;
    Refresh();
}
References m_humidity.
Referenced by Slic3r::GUI::AMSControl::SetHumidity().
ShowHumidity()
void Slic3r::GUI::AMSItem::ShowHumidity ()
{
    m_show_humidity = true;
    SetSize(AMS_ITEM_HUMIDITY_SIZE);
    SetMinSize(AMS_ITEM_HUMIDITY_SIZE);
    Refresh();
}
References AMS_ITEM_HUMIDITY_SIZE, and m_show_humidity.
UnSelected()
void Slic3r::GUI::AMSItem::UnSelected ()
{
    m_selected = false;
    Refresh();
}
References m_selected.
Referenced by Slic3r::GUI::AMSControl::SwitchAms().
Update()
void Slic3r::GUI::AMSItem::Update (AMSinfo amsinfo)
{
    m_amsinfo = amsinfo;
}
References m_amsinfo.
Referenced by Slic3r::GUI::AMSControl::UpdateAms().
Member Data Documentation
m_amsinfo
AMSinfo Slic3r::GUI::AMSItem::m_amsinfo
Referenced by AMSItem(), doRender(), Slic3r::GUI::AMSControl::SetHumidity(), Slic3r::GUI::AMSControl::SwitchAms(), and Update().
m_background_colour
wxColour Slic3r::GUI::AMSItem::m_background_colour = {AMS_CONTROL_DEF_BLOCK_BK_COLOUR} protected
Referenced by doRender().
m_cube_size
wxSize Slic3r::GUI::AMSItem::m_cube_size protected
Referenced by AMSItem().
m_hover
bool Slic3r::GUI::AMSItem::m_hover = {false} protected
Referenced by doRender().
m_humidity
int Slic3r::GUI::AMSItem::m_humidity = {0} protected
Referenced by SetHumidity().
m_open
bool Slic3r::GUI::AMSItem::m_open = {false}
Referenced by Close(), and Open().
m_padding
int Slic3r::GUI::AMSItem::m_padding = {6} protected
Referenced by doRender().
m_selected
bool Slic3r::GUI::AMSItem::m_selected = {false} protected
Referenced by doRender(), OnSelected(), and UnSelected().
m_show_humidity
bool Slic3r::GUI::AMSItem::m_show_humidity = {false} protected
Referenced by doRender(), HideHumidity(), and ShowHumidity().
m_space
int Slic3r::GUI::AMSItem::m_space = {5} protected
Referenced by doRender().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AMSControl.hpp
src/slic3r/GUI/Widgets/AMSControl.cpp