OrcaSlicer: Slic3r::GUI::IMReturnToolbar Class Reference
Slic3r::GUI::IMReturnToolbar Class Reference
#include <src/slic3r/GUI/IMToolbar.hpp>
Public Member Functions
IMReturnToolbar ()
bool init ()
bool is_enabled () const
void set_enabled (bool enable)
ImTextureID get_return_texture_id ()
Private Attributes
bool m_enabled { false }
ImTextureID texture_id
GLTexture return_textrue
Detailed Description
Constructor & Destructor Documentation
IMReturnToolbar()
Slic3r::GUI::IMReturnToolbar::IMReturnToolbar () inline
{}
Member Function Documentation
get_return_texture_id()
ImTextureID Slic3r::GUI::IMReturnToolbar::get_return_texture_id () inline
{ return texture_id; }
References texture_id.
Referenced by Slic3r::GUI::GLCanvas3D::_render_return_toolbar().
init()
bool Slic3r::GUI::IMReturnToolbar::init ()
{
    bool compress = false;
    GLint last_texture;
    unsigned m_image_texture{ 0 };
    std::string path = resources_dir() + "/images/";
    std::string file_name;
    file_name = path + "assemble_return.svg";
    ThumbnailData data;
    if (!get_data_from_svg(file_name, 20, data))
        return false;
    unsigned char* pixels = (unsigned char*)(&data.pixels[0]);
    glsafe(::glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture));
    glsafe(::glGenTextures(1, &m_image_texture));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_image_texture));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
    glsafe(::glPixelStorei(GL_UNPACK_ROW_LENGTH, 0));
    if (compress && GLEW_EXT_texture_compression_s3tc)
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, data.width, data.height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels));
    else
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, data.width, data.height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels));
    // Store our identifier
    texture_id = (ImTextureID)(intptr_t)m_image_texture;
    // Restore state
    glsafe(::glBindTexture(GL_TEXTURE_2D, last_texture));
    return true;
}
References compress, Slic3r::GUI::get_data_from_svg(), glsafe, Slic3r::ThumbnailData::height, Slic3r::ThumbnailData::pixels, Slic3r::resources_dir(), texture_id, and Slic3r::ThumbnailData::width.
Referenced by Slic3r::GUI::GLCanvas3D::_init_return_toolbar().
is_enabled()
bool Slic3r::GUI::IMReturnToolbar::is_enabled () const inline
{ return m_enabled; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::_init_return_toolbar(), and Slic3r::GUI::GLCanvas3D::_render_return_toolbar().
set_enabled()
void Slic3r::GUI::IMReturnToolbar::set_enabled (bool enable) inline
{ m_enabled = enable; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::enable_return_toolbar().
Member Data Documentation
m_enabled
bool Slic3r::GUI::IMReturnToolbar::m_enabled { false } private
Referenced by is_enabled(), and set_enabled().
return_textrue
GLTexture Slic3r::GUI::IMReturnToolbar::return_textrue private
texture_id
ImTextureID Slic3r::GUI::IMReturnToolbar::texture_id private
Referenced by get_return_texture_id(), and init().
The documentation for this class was generated from the following files:
src/slic3r/GUI/IMToolbar.hpp
src/slic3r/GUI/IMToolbar.cpp