OrcaSlicer: Slic3r::GUI::CameraItem Class Reference
Slic3r::GUI::CameraItem Class Reference
#include <src/slic3r/GUI/CameraPopup.hpp>
Public Member Functions
CameraItem (wxWindow *parent, std::string normal, std::string hover)
~CameraItem ()
void msw_rescale ()
void on_enter_win (wxMouseEvent &evt)
void on_level_win (wxMouseEvent &evt)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
Public Attributes
MachineObject * m_obj {nullptr}
bool m_hover {false}
ScalableBitmap m_bitmap_normal
ScalableBitmap m_bitmap_hover
Detailed Description
Constructor & Destructor Documentation
CameraItem()
Slic3r::GUI::CameraItem::CameraItem (wxWindow * parent, std::string normal, std::string hover)
    : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize)
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    m_bitmap_normal  = ScalableBitmap(this, normal, 20);
    m_bitmap_hover   = ScalableBitmap(this, hover, 20);
    SetSize(wxSize(FromDIP(20), FromDIP(20)));
    SetMinSize(wxSize(FromDIP(20), FromDIP(20)));
    SetMaxSize(wxSize(FromDIP(20), FromDIP(20)));
    Bind(wxEVT_PAINT, &CameraItem::paintEvent, this);
    Bind(wxEVT_ENTER_WINDOW, &CameraItem::on_enter_win, this);
    Bind(wxEVT_LEAVE_WINDOW, &CameraItem::on_level_win, this);
}
References m_bitmap_hover, m_bitmap_normal, Slic3r::normal(), on_enter_win(), on_level_win(), and paintEvent().
~CameraItem()
Slic3r::GUI::CameraItem::~CameraItem ()
{}
Member Function Documentation
doRender()
void Slic3r::GUI::CameraItem::doRender (wxDC & dc)
{
    if (m_hover) {
        dc.DrawBitmap(m_bitmap_hover.bmp(), wxPoint((GetSize().x - m_bitmap_hover.GetBmpSize().x) / 2, (GetSize().y - m_bitmap_hover.GetBmpSize().y) / 2));
    } else {
        dc.DrawBitmap(m_bitmap_normal.bmp(), wxPoint((GetSize().x - m_bitmap_normal.GetBmpSize().x) / 2, (GetSize().y - m_bitmap_normal.GetBmpSize().y) / 2));
    }
}
References ScalableBitmap::bmp(), ScalableBitmap::GetBmpSize(), m_bitmap_hover, m_bitmap_normal, and m_hover.
Referenced by render().
msw_rescale()
void Slic3r::GUI::CameraItem::msw_rescale ()
{
    m_bitmap_normal.msw_rescale();
    m_bitmap_hover.msw_rescale();
}
References m_bitmap_hover, m_bitmap_normal, and ScalableBitmap::msw_rescale().
Referenced by Slic3r::GUI::StatusPanel::rescale_camera_icons().
on_enter_win()
void Slic3r::GUI::CameraItem::on_enter_win (wxMouseEvent & evt)
{
    m_hover = true;
    Refresh();
}
References m_hover.
Referenced by CameraItem().
on_level_win()
void Slic3r::GUI::CameraItem::on_level_win (wxMouseEvent & evt)
{
    m_hover = false;
    Refresh();
}
References m_hover.
Referenced by CameraItem().
paintEvent()
void Slic3r::GUI::CameraItem::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
    // PrepareDC(buffdc);
    // PrepareDC(dc);
}
References render().
Referenced by CameraItem().
render()
void Slic3r::GUI::CameraItem::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
Member Data Documentation
m_bitmap_hover
ScalableBitmap Slic3r::GUI::CameraItem::m_bitmap_hover
Referenced by CameraItem(), doRender(), and msw_rescale().
m_bitmap_normal
ScalableBitmap Slic3r::GUI::CameraItem::m_bitmap_normal
Referenced by CameraItem(), doRender(), and msw_rescale().
m_hover
bool Slic3r::GUI::CameraItem::m_hover {false}
Referenced by doRender(), on_enter_win(), and on_level_win().
m_obj
MachineObject* Slic3r::GUI::CameraItem::m_obj {nullptr}
The documentation for this class was generated from the following files:
src/slic3r/GUI/CameraPopup.hpp
src/slic3r/GUI/CameraPopup.cpp