OrcaSlicer: src/qhull/src/libqhullcpp/QhullVertexSet.cpp File Reference
QhullVertexSet.cpp File Reference
#include "libqhullcpp/QhullVertexSet.h"
#include "libqhullcpp/QhullVertex.h"
#include "libqhullcpp/QhullPoint.h"
#include "libqhullcpp/QhullRidge.h"
#include "libqhullcpp/Qhull.h"
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global functions
ostream & operator<< (ostream &os, const QhullVertexSet::PrintIdentifiers &pr)
Print Vertex identifiers to stream. Space prefix. From qh_printVertexheader [io_r.c].
ostream & operator<< (ostream &os, const QhullVertexSet::PrintVertexSet &pr)
Duplicate of printvertices [io_r.c].
Function Documentation
operator<<() [1/2]
ostream & operator<< (ostream & os, const QhullVertexSet::PrintIdentifiers & pr)
Print Vertex identifiers to stream. Space prefix. From qh_printVertexheader [io_r.c].
{
    os << pr.print_message;
    for(QhullVertexSet::const_iterator i= pr.vertex_set->begin(); i!=pr.vertex_set->end(); ++i){
        const QhullVertex v= *i;
        os << " v" << v.id();
    }
    os << endl;
    return os;
}//<<QhullVertexSet::PrintIdentifiers
References orgQhull::QhullVertex::id().
operator<<() [2/2]
ostream & operator<< (ostream & os, const QhullVertexSet::PrintVertexSet & pr)
Duplicate of printvertices [io_r.c].
{
    os << pr.print_message;
    const QhullVertexSet *vs= pr.vertex_set;
    QhullVertexSetIterator i= *vs;
    while(i.hasNext()){
        const QhullVertex v= i.next();
        const QhullPoint p= v.point();
        os << " p" << p.id() << "(v" << v.id() << ")";
    }
    os << endl;
    return os;
}//<< PrintVertexSet
References orgQhull::QhullPoint::id(), orgQhull::QhullVertex::id(), orgQhull::QhullVertex::next(), and orgQhull::QhullVertex::point().