OrcaSlicer: Slic3r::GUI::ObjectDataViewModel Class Reference
Slic3r::GUI::ObjectDataViewModel Class Reference
#include <src/slic3r/GUI/ObjectDataViewModel.hpp>
Public Member Functions
ObjectDataViewModel ()
~ObjectDataViewModel ()
void Init ()
wxDataViewItem AddPlate (PartPlate *part_plate, wxString name=wxEmptyString, bool refresh=true)
wxDataViewItem AddObject (ModelObject *model_object, std::string warning_bitmap, bool has_lock=false, bool refresh=true)
wxDataViewItem AddVolumeChild (const wxDataViewItem &parent_item, const wxString &name, const Slic3r::ModelVolumeType volume_type, const std::string &warning_icon_name=std::string(), const int extruder=0, const bool create_frst_child=true)
wxDataViewItem AddSettingsChild (const wxDataViewItem &parent_item)
wxDataViewItem AddInfoChild (const wxDataViewItem &parent_item, InfoItemType info_type)
wxDataViewItem AddInstanceChild (const wxDataViewItem &parent_item, size_t num)
wxDataViewItem AddInstanceChild (const wxDataViewItem &parent_item, const std::vector< bool > &print_indicator, const std::vector< int > &plate_indicator)
wxDataViewItem AddLayersRoot (const wxDataViewItem &parent_item)
wxDataViewItem AddLayersChild (const wxDataViewItem &parent_item, const t_layer_height_range &layer_range, const int extruder=0, const int index=-1)
size_t GetItemIndexForFirstVolume (ObjectDataViewModelNode *node_parent)
wxDataViewItem DeletePlate (const int plate_idx)
wxDataViewItem Delete (const wxDataViewItem &item)
wxDataViewItem DeleteLastInstance (const wxDataViewItem &parent_item, size_t num)
void ResetAll ()
void DeleteChildren (wxDataViewItem &parent)
void DeleteVolumeChildren (wxDataViewItem &parent)
void DeleteSettings (const wxDataViewItem &parent)
wxDataViewItem GetItemByPlateId (int plate_idx)
wxDataViewItem GetItemById (int obj_idx)
wxDataViewItem GetItemById (const int obj_idx, const int sub_obj_idx, const ItemType parent_type)
wxDataViewItem GetItemByVolumeId (int obj_idx, int volume_idx)
wxDataViewItem GetItemByInstanceId (int obj_idx, int inst_idx)
wxDataViewItem GetItemByLayerId (int obj_idx, int layer_idx)
wxDataViewItem GetItemByLayerRange (const int obj_idx, const t_layer_height_range &layer_range)
int GetItemIdByLayerRange (const int obj_idx, const t_layer_height_range &layer_range)
int GetIdByItem (const wxDataViewItem &item) const
int GetIdByItemAndType (const wxDataViewItem &item, const ItemType type) const
int GetObjectIdByItem (const wxDataViewItem &item) const
int GetVolumeIdByItem (const wxDataViewItem &item) const
int GetInstanceIdByItem (const wxDataViewItem &item) const
int GetLayerIdByItem (const wxDataViewItem &item) const
void GetItemInfo (const wxDataViewItem &item, ItemType &type, int &obj_idx, int &idx)
int GetRowByItem (const wxDataViewItem &item) const
bool IsEmpty ()
bool InvalidItem (const wxDataViewItem &item)
wxString GetName (const wxDataViewItem &item) const
wxBitmap & GetBitmap (const wxDataViewItem &item) const
wxString GetExtruder (const wxDataViewItem &item) const
int GetExtruderNumber (const wxDataViewItem &item) const
unsigned int GetColumnCount () const override
wxString GetColumnType (unsigned int col) const override
void GetValue (wxVariant &variant, const wxDataViewItem &item, unsigned int col) const override
bool SetValue (const wxVariant &variant, const wxDataViewItem &item, unsigned int col) override
bool SetValue (const wxVariant &variant, const int item_idx, unsigned int col)
void SetExtruder (const wxString &extruder, wxDataViewItem item)
void OnPlateChange (const int plate_idx, wxDataViewItem item)
void SetPlateIdx (const int plate_idx, wxDataViewItem item)
bool SetName (const wxString &new_name, wxDataViewItem item)
wxDataViewItem ReorganizeChildren (const int cur_volume_id, const int new_volume_id, const wxDataViewItem &parent)
wxDataViewItem ReorganizeObjects (int current_id, int new_id)
bool IsEnabled (const wxDataViewItem &item, unsigned int col) const override
wxDataViewItem GetParent (const wxDataViewItem &item) const override
wxDataViewItem GetObject (const wxDataViewItem &item) const
wxDataViewItem GetTopParent (const wxDataViewItem &item) const
bool IsContainer (const wxDataViewItem &item) const override
unsigned int GetChildren (const wxDataViewItem &parent, wxDataViewItemArray &array) const override
void GetAllChildren (const wxDataViewItem &parent, wxDataViewItemArray &array) const
bool HasContainerColumns (const wxDataViewItem &WXUNUSED(item)) const override
bool HasInfoItem (InfoItemType type) const
ItemType GetItemType (const wxDataViewItem &item) const
InfoItemType GetInfoItemType (const wxDataViewItem &item) const
wxDataViewItem GetItemByType (const wxDataViewItem &parent_item, ItemType type) const
wxDataViewItem GetSettingsItem (const wxDataViewItem &item) const
wxDataViewItem GetInstanceRootItem (const wxDataViewItem &item) const
wxDataViewItem GetLayerRootItem (const wxDataViewItem &item) const
wxDataViewItem GetInfoItemByType (const wxDataViewItem &parent_item, InfoItemType type) const
wxDataViewItem GetObjectItem (const ModelObject *mo) const
wxDataViewItem GetVolumeItem (const wxDataViewItem &parent, int vol_idx) const
bool IsSettingsItem (const wxDataViewItem &item) const
void UpdateSettingsDigest (const wxDataViewItem &item, const std::vector< std::string > &categories)
bool IsPrintable (const wxDataViewItem &item) const
void UpdateObjectPrintable (wxDataViewItem parent_item)
void UpdateInstancesPrintable (wxDataViewItem parent_item)
void SetVolumeType (const wxDataViewItem &item, const Slic3r::ModelVolumeType type)
ModelVolumeType GetVolumeType (const wxDataViewItem &item)
wxDataViewItem SetPrintableState (PrintIndicator printable, int obj_idx, int subobj_idx=-1, ItemType subobj_type=itInstance)
wxDataViewItem SetObjectPrintableState (PrintIndicator printable, wxDataViewItem obj_item)
bool IsColorPainted (wxDataViewItem &item) const
bool IsSupportPainted (wxDataViewItem &item) const
bool IsSinked (wxDataViewItem &item) const
void SetColorPaintState (const bool painted, wxDataViewItem obj_item)
void SetSupportPaintState (const bool painted, wxDataViewItem obj_item)
void SetSinkState (const bool painted, wxDataViewItem obj_item)
void SetAssociatedControl (wxDataViewCtrl *ctrl)
void Rescale ()
wxBitmap GetVolumeIcon (const Slic3r::ModelVolumeType vol_type, const std::string &warning_icon_name=std::string())
void AddWarningIcon (const wxDataViewItem &item, const std::string &warning_name)
void DeleteWarningIcon (const wxDataViewItem &item, const bool unmark_object=false)
void UpdateWarningIcon (const wxDataViewItem &item, const std::string &warning_name)
void UpdateCutObjectIcon (const wxDataViewItem &item, bool has_cut_icon)
bool HasWarningIcon (const wxDataViewItem &item) const
t_layer_height_range GetLayerRangeByItem (const wxDataViewItem &item) const
bool UpdateColumValues (unsigned col)
void UpdateExtruderBitmap (wxDataViewItem item)
void UpdateVolumesExtruderBitmap (wxDataViewItem object_item, bool use_obj_extruder=false)
int GetDefaultExtruderIdx (wxDataViewItem item)
void UpdateItemNames ()
Private Member Functions
wxDataViewItem AddRoot (const wxDataViewItem &parent_item, const ItemType root_type)
wxDataViewItem AddInstanceRoot (const wxDataViewItem &parent_item)
void AddAllChildren (const wxDataViewItem &parent)
wxBitmap & GetWarningBitmap (const std::string &warning_icon_name)
void ReparentObject (ObjectDataViewModelNode *plate, ObjectDataViewModelNode *object)
wxDataViewItem AddOutsidePlate (bool refresh=true)
void UpdateBitmapForNode (ObjectDataViewModelNode *node)
void UpdateBitmapForNode (ObjectDataViewModelNode *node, bool has_lock)
Private Attributes
std::vector< ObjectDataViewModelNode * > m_plates
std::vector< ObjectDataViewModelNode * > m_objects
std::vector< wxBitmap > m_volume_bmps
std::map< InfoItemType, wxBitmap > m_info_bmps
wxBitmap m_empty_bmp
wxBitmap m_warning_bmp
wxBitmap m_warning_manifold_bmp
wxBitmap m_lock_bmp
ObjectDataViewModelNode * m_plate_outside
wxDataViewCtrl * m_ctrl { nullptr }
Detailed Description
Constructor & Destructor Documentation
ObjectDataViewModel()
Slic3r::GUI::ObjectDataViewModel::ObjectDataViewModel ()
{
    m_bitmap_cache = new Slic3r::GUI::BitmapCache;
    m_volume_bmps = MenuFactory::get_volume_bitmaps();
    m_warning_bmp = create_scaled_bitmap(WarningIcon);
    m_warning_manifold_bmp = create_scaled_bitmap(WarningManifoldIcon);
    m_lock_bmp = create_scaled_bitmap(LockIcon);
    for (auto item : INFO_ITEMS)
        m_info_bmps[item.first] = create_scaled_bitmap(item.second.bmp_name);
    m_plate_outside = nullptr;
}
References create_scaled_bitmap(), Slic3r::GUI::MenuFactory::get_volume_bitmaps(), Slic3r::GUI::INFO_ITEMS, Slic3r::GUI::LockIcon, Slic3r::GUI::m_bitmap_cache, m_info_bmps, m_lock_bmp, m_plate_outside, m_volume_bmps, m_warning_bmp, m_warning_manifold_bmp, Slic3r::GUI::WarningIcon, and Slic3r::GUI::WarningManifoldIcon.
~ObjectDataViewModel()
Slic3r::GUI::ObjectDataViewModel::~ObjectDataViewModel ()
{
    for (auto object : m_objects)
      delete object;
    delete m_bitmap_cache;
    m_bitmap_cache = nullptr;
}
References Slic3r::GUI::m_bitmap_cache, and m_objects.
Member Function Documentation
AddAllChildren()
void Slic3r::GUI::ObjectDataViewModel::AddAllChildren (const wxDataViewItem & parent) private
{
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(parent.GetID());
    if (!node || node->GetChildCount() == 0)
        return;
    wxDataViewItemArray array;
    const size_t count = node->GetChildCount();
    for (size_t pos = 0; pos < count; pos++) {
        ObjectDataViewModelNode* child = node->GetChildren().Item(pos);
        array.Add(wxDataViewItem((void*)child));
        ItemAdded(parent, wxDataViewItem((void*)child));
    }
    for (const auto& item : array)
        AddAllChildren(item);
    m_ctrl->Expand(parent);
};
References AddAllChildren(), count, Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), and m_ctrl.
Referenced by AddAllChildren(), ReorganizeChildren(), and ReorganizeObjects().
AddInfoChild()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddInfoChild (const wxDataViewItem & parent_item, InfoItemType info_type)
{
    ObjectDataViewModelNode *root = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    if (!root) return wxDataViewItem(0);
    const auto node = new ObjectDataViewModelNode(root, info_type);
    // The new item should be added according to its order in InfoItemType.
    // Find last info item with lower index and append after it.
    const auto& children = root->GetChildren();
    // If SettingsItem exists, it have to be on the first position always
    bool is_settings_item = children.size() > 0 && children[0]->GetType() == itSettings;
    int idx = is_settings_item ? 0 : -1;
    for (size_t i = is_settings_item ? 1 : 0; i < children.size(); ++i) {
        if (children[i]->GetType() == itInfo && int(children[i]->GetInfoItemType()) < int(info_type) )
            idx = i;
    }
    root->Insert(node, idx+1);
    node->SetBitmap(m_info_bmps.at(info_type));
    // notify control
    const wxDataViewItem child((void*)node);
    ItemAdded(parent_item, child);
    return child;
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), GetInfoItemType(), Slic3r::GUI::ObjectDataViewModelNode::Insert(), int, Slic3r::GUI::itInfo, Slic3r::GUI::itSettings, and m_info_bmps.
Referenced by Slic3r::GUI::ObjectList::update_info_items().
AddInstanceChild() [1/2]
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddInstanceChild (const wxDataViewItem & parent_item, const std::vector< bool > & print_indicator, const std::vector< int > & plate_indicator)
{
    const wxDataViewItem inst_root_item = AddInstanceRoot(parent_item);
    if (!inst_root_item) return wxDataViewItem(0);
    ObjectDataViewModelNode* inst_root_node = static_cast<ObjectDataViewModelNode*>(inst_root_item.GetID());
    // Add instance nodes
    ObjectDataViewModelNode *instance_node = nullptr;
    size_t counter = 0;
    while (counter < print_indicator.size()) {
        instance_node = new ObjectDataViewModelNode(inst_root_node, itInstance, plate_indicator[counter]);
        instance_node->set_printable_icon(print_indicator[counter] ? piPrintable : piUnprintable);
        inst_root_node->Append(instance_node);
        // notify control
        const wxDataViewItem instance_item((void*)instance_node);
        ItemAdded(inst_root_item, instance_item);
        ++counter;
    }
    // update object_node printable property
    UpdateObjectPrintable(parent_item);
    return wxDataViewItem((void*)instance_node);
}
References AddInstanceRoot(), Slic3r::GUI::ObjectDataViewModelNode::Append(), Slic3r::GUI::itInstance, Slic3r::GUI::piPrintable, Slic3r::GUI::piUnprintable, Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon(), and UpdateObjectPrintable().
AddInstanceChild() [2/2]
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddInstanceChild (const wxDataViewItem & parent_item, size_t num)
{
    std::vector<bool> print_indicator(num, true);
    std::vector<int> plate_indicator(num, -1);
    // if InstanceRoot item isn't created for this moment
    if (!GetInstanceRootItem(parent_item).IsOk())
        // use object's printable state to first instance
        print_indicator[0] = IsPrintable(parent_item);
    return wxDataViewItem((void*)AddInstanceChild(parent_item, print_indicator, plate_indicator));
}
References AddInstanceChild(), GetInstanceRootItem(), and IsPrintable().
Referenced by Slic3r::GUI::ObjectList::add_object_to_list(), AddInstanceChild(), and Slic3r::GUI::ObjectList::increase_object_instances().
AddInstanceRoot()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddInstanceRoot (const wxDataViewItem & parent_item) private
{
    return AddRoot(parent_item, itInstanceRoot);
}
References AddRoot(), and Slic3r::GUI::itInstanceRoot.
Referenced by AddInstanceChild().
AddLayersChild()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddLayersChild (const wxDataViewItem & parent_item, const t_layer_height_range & layer_range, const int extruder = 0, const int index = -1)
{
    ObjectDataViewModelNode *parent_node = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    if (!parent_node) return wxDataViewItem(0);
    // BBS
    wxString extruder_str = extruder == 0 ? _(L("default")) : wxString::Format("%d", extruder);
    // get LayerRoot node
    ObjectDataViewModelNode *layer_root_node;
    wxDataViewItem layer_root_item;
    if (parent_node->GetType() & itLayerRoot) {
        layer_root_node = parent_node;
        layer_root_item = parent_item;
    }
    else {
        const int root_idx = get_root_idx(parent_node, itLayerRoot);
        if (root_idx < 0) return wxDataViewItem(0);
        layer_root_node = parent_node->GetNthChild(root_idx);
        layer_root_item = wxDataViewItem((void*)layer_root_node);
    }
    // Add layer node
    ObjectDataViewModelNode *layer_node = new ObjectDataViewModelNode(layer_root_node, layer_range, index, extruder_str);
    if (index < 0)
        layer_root_node->Append(layer_node);
    else
        layer_root_node->Insert(layer_node, index);
    // notify control
    const wxDataViewItem layer_item((void*)layer_node);
    ItemAdded(layer_root_item, layer_item);
    return layer_item;
}
References _, Slic3r::GUI::ObjectDataViewModelNode::Append(), Slic3r::GUI::get_root_idx(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::ObjectDataViewModelNode::GetType(), Slic3r::GUI::ObjectDataViewModelNode::Insert(), Slic3r::GUI::itLayerRoot, and L.
Referenced by Slic3r::GUI::ObjectList::add_layer_item().
AddLayersRoot()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddLayersRoot (const wxDataViewItem & parent_item)
{
    return AddRoot(parent_item, itLayerRoot);
}
References AddRoot(), and Slic3r::GUI::itLayerRoot.
Referenced by Slic3r::GUI::ObjectList::add_layer_root_item().
AddObject()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddObject (ModelObject * model_object, std::string warning_bitmap, bool has_lock = false, bool refresh = true)
{
    // get object node params
    wxString name = from_u8(model_object->name);
    int extruder = model_object->config.has("extruder") ? model_object->config.extruder() : 1;
    int plate_idx = -1;
    ObjectDataViewModelNode* plate_node = nullptr;
    for (auto plate : m_plates) {
        if (plate->m_part_plate != nullptr &&
            plate->m_part_plate->contain_instance_totally(model_object, 0))
        {
            plate_node = plate;
            plate_idx = plate->m_part_plate->get_index();
            break;
        }
    }
    // create object node
    //const wxString extruder_str = extruder == 0 ? _(L("default")) : wxString::Format("%d", extruder);
    const wxString extruder_str = wxString::Format("%d", extruder);
    auto obj_node = new ObjectDataViewModelNode(name, extruder_str, plate_idx, model_object);
    obj_node->SetWarningBitmap(GetWarningBitmap(warning_bitmap), warning_bitmap);
    UpdateBitmapForNode(obj_node, has_lock);
    if (plate_node != nullptr) {
        obj_node->m_parent = plate_node;
    }
    else {
        obj_node->m_parent = m_plate_outside;
        plate_node = m_plate_outside;
    }
    m_objects.push_back(obj_node);
    plate_node->GetChildren().push_back(obj_node);
    // notify control
    wxDataViewItem child((void*)obj_node);
    wxDataViewItem parent((void*)plate_node);
    if (refresh) {
        ItemAdded(parent, child);
    }
    return child;
}
References Slic3r::ModelObject::config, Slic3r::ModelConfig::extruder(), Slic3r::GUI::from_u8(), Slic3r::GUI::PartPlate::get_index(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), GetWarningBitmap(), Slic3r::ModelConfig::has(), m_objects, Slic3r::GUI::ObjectDataViewModelNode::m_parent, Slic3r::GUI::ObjectDataViewModelNode::m_part_plate, m_plate_outside, m_plates, Slic3r::ModelObject::name, and UpdateBitmapForNode().
Referenced by Slic3r::GUI::ObjectList::add_object_to_list().
AddOutsidePlate()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddOutsidePlate (bool refresh = true) private
{
    wxDataViewItem plate_item = AddPlate(nullptr, _L("Outside"));
    m_plate_outside = (ObjectDataViewModelNode*)plate_item.GetID();
    return plate_item;
}
References _L, AddPlate(), and m_plate_outside.
Referenced by Init(), and ResetAll().
AddPlate()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddPlate (PartPlate * part_plate, wxString name = wxEmptyString, bool refresh = true)
{
    int plate_idx = part_plate ? part_plate->get_index() : -1;
    wxString plate_name = name;
    if (plate_name == "") {
        plate_name = _L("Plate");
        plate_name << " " << plate_idx + 1;
    }
    auto plate_node = new ObjectDataViewModelNode(part_plate, plate_name);
    bool is_added = false;
    if (plate_idx >= 0) {
        for (auto iter = m_plates.begin(); iter != m_plates.end(); iter++) {
            if (plate_idx < (*iter)->m_plate_idx || (*iter)->m_plate_idx < 0) {
                m_plates.insert(iter, plate_node);
                is_added = true;
                break;
            }
        }
    }
    if (!is_added) {
        m_plates.push_back(plate_node);
    }
    wxDataViewItem plate_item(plate_node);
    if (refresh) {
        ItemAdded(wxDataViewItem(nullptr), plate_item);
    }
    for (int obj_idx = 0; obj_idx < m_objects.size(); obj_idx++) {
        auto obj_node = m_objects[obj_idx];
        if (part_plate && part_plate->contain_instance_totally(obj_idx, 0)) {
            ReparentObject(plate_node, obj_node);
        }
    }
    return plate_item;
}
References _L, Slic3r::GUI::PartPlate::contain_instance_totally(), Slic3r::GUI::PartPlate::get_index(), m_objects, m_plates, and ReparentObject().
Referenced by AddOutsidePlate(), Init(), Slic3r::GUI::ObjectList::on_plate_added(), and Slic3r::GUI::ObjectList::reload_all_plates().
AddRoot()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddRoot (const wxDataViewItem & parent_item, const ItemType root_type) private
{
    ObjectDataViewModelNode *parent_node = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    if (!parent_node) return wxDataViewItem(0);
    // get InstanceRoot node
    ObjectDataViewModelNode *root_node { nullptr };
    const bool appended = append_root_node(parent_node, &root_node, root_type);
    if (!root_node) return wxDataViewItem(0);
    const wxDataViewItem root_item((void*)root_node);
    if (appended)
        ItemAdded(parent_item, root_item);// notify control
    return root_item;
}
References Slic3r::GUI::append_root_node().
Referenced by AddInstanceRoot(), and AddLayersRoot().
AddSettingsChild()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddSettingsChild (const wxDataViewItem & parent_item)
{
    ObjectDataViewModelNode *root = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    if (!root) return wxDataViewItem(0);
    const auto node = new ObjectDataViewModelNode(root, itSettings);
    root->Insert(node, 0);
    // notify control
    const wxDataViewItem child((void*)node);
    ItemAdded(parent_item, child);
    return child;
}
References Slic3r::GUI::ObjectDataViewModelNode::Insert(), and Slic3r::GUI::itSettings.
Referenced by Slic3r::GUI::ObjectList::add_settings_item().
AddVolumeChild()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::AddVolumeChild (const wxDataViewItem & parent_item, const wxString & name, const Slic3r::ModelVolumeType volume_type, const std::string & warning_icon_name = std::string(), const int extruder = 0, const bool create_frst_child = true)
{
  ObjectDataViewModelNode *root = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
  if (!root) return wxDataViewItem(0);
    // get insertion position according to the existed Layers and/or Instances Items
    int insert_position = get_root_idx(root, itLayerRoot);
    if (insert_position < 0)
        insert_position = get_root_idx(root, itInstanceRoot);
    if (create_frst_child && root->m_volumes_cnt == 0)
    {
        const Slic3r::ModelVolumeType type = Slic3r::ModelVolumeType::MODEL_PART;
        const auto node = new ObjectDataViewModelNode(root, root->m_name, type, GetVolumeIcon(type, root->m_warning_icon_name), root->m_extruder, 0, root->m_warning_icon_name);
        insert_position < 0 ? root->Append(node) : root->Insert(node, insert_position);
    // notify control
    const wxDataViewItem child((void*)node);
    ItemAdded(parent_item, child);
        root->m_volumes_cnt++;
        if (insert_position >= 0) insert_position++;
  }
    // BBS
    wxString extruder_str;
    if (extruder == 0) {
        if (volume_type == ModelVolumeType::PARAMETER_MODIFIER)
            extruder_str = _L("default");
        else
            extruder_str = root->m_extruder;
    }
    else {
        extruder_str = wxString::Format("%d", extruder);
    }
    const auto node = new ObjectDataViewModelNode(root, name, volume_type, GetVolumeIcon(volume_type, warning_icon_name),
        extruder_str, root->m_volumes_cnt, warning_icon_name);
    insert_position < 0 ? root->Append(node) : root->Insert(node, insert_position);
    // if part with errors is added, but object wasn't marked, then mark it
    if (!warning_icon_name.empty() && warning_icon_name != root->m_warning_icon_name &&
        (root->m_warning_icon_name.empty() || root->m_warning_icon_name == WarningManifoldIcon) )
        root->SetWarningBitmap(GetWarningBitmap(warning_icon_name), warning_icon_name);
  // notify control
    const wxDataViewItem child((void*)node);
    ItemAdded(parent_item, child);
    root->m_volumes_cnt++;
  return child;
}
References _L, Slic3r::GUI::ObjectDataViewModelNode::Append(), Slic3r::GUI::get_root_idx(), GetVolumeIcon(), GetWarningBitmap(), Slic3r::GUI::ObjectDataViewModelNode::Insert(), Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itLayerRoot, Slic3r::GUI::ObjectDataViewModelNode::m_extruder, Slic3r::GUI::ObjectDataViewModelNode::m_name, Slic3r::GUI::ObjectDataViewModelNode::m_volumes_cnt, Slic3r::GUI::ObjectDataViewModelNode::m_warning_icon_name, Slic3r::MODEL_PART, Slic3r::PARAMETER_MODIFIER, Slic3r::GUI::ObjectDataViewModelNode::SetWarningBitmap(), and Slic3r::GUI::WarningManifoldIcon.
Referenced by Slic3r::GUI::ObjectList::add_volumes_to_object_in_list(), Slic3r::GUI::ObjectList::reorder_volumes_and_get_selection(), and Slic3r::GUI::ObjectList::split().
AddWarningIcon()
void Slic3r::GUI::ObjectDataViewModel::AddWarningIcon (const wxDataViewItem & item, const std::string & warning_name)
{
    if (!item.IsOk())
        return;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (node->GetType() & itObject) {
        node->SetWarningBitmap(GetWarningBitmap(warning_icon_name), warning_icon_name);
        return;
    }
    if (node->GetType() & itVolume) {
        node->SetWarningBitmap(GetVolumeIcon(node->GetVolumeType(), warning_icon_name), warning_icon_name);
        node->GetParent()->SetWarningBitmap(GetWarningBitmap(warning_icon_name), warning_icon_name);
        return;
    }
}
References Slic3r::GUI::ObjectDataViewModelNode::GetParent(), Slic3r::GUI::ObjectDataViewModelNode::GetType(), GetVolumeIcon(), Slic3r::GUI::ObjectDataViewModelNode::GetVolumeType(), GetWarningBitmap(), Slic3r::GUI::itObject, Slic3r::GUI::itVolume, and Slic3r::GUI::ObjectDataViewModelNode::SetWarningBitmap().
Referenced by UpdateWarningIcon().
Delete()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::Delete (const wxDataViewItem & item)
{
  auto ret_item = wxDataViewItem(0);
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  if (!node)      // happens if item.IsOk()==false
    return ret_item;
  auto node_parent = node->GetParent();
  wxDataViewItem parent(node_parent);
    if (node->m_type & itPlate) {
        for (auto child : node->GetChildren()) {
            assert((child->GetType() & itObject) != 0);
            if (child->m_plate_idx == node->m_plate_idx)
                ReparentObject(m_plate_outside, child);
        }
        // FIX: should remove from children collection soon, or will conflict GetChildren
        m_plates.erase(std::remove(m_plates.begin(), m_plates.end(), node), m_plates.end());
        ItemDeleted(parent, wxDataViewItem(node));
        delete node;
        return parent;
    }
    if (node->m_type & itObject) {
        auto it = find(m_objects.begin(), m_objects.end(), node);
        if (it != m_objects.end())
        {
            // Delete all sub-items
            int i = (*it)->GetChildCount() - 1;
            while (i >= 0) {
                Delete(wxDataViewItem((*it)->GetNthChild(i)));
                i = (*it)->GetChildCount() - 1;
            }
            m_objects.erase(it);
            node_parent->GetChildren().Remove(node);
        }
        ItemDeleted(parent, wxDataViewItem(node));
        delete node;
        return parent;
    }
  // first remove the node from the parent's array of children;
  // NOTE: MyObjectTreeModelNodePtrArray is only an array of _pointers_
  //       thus removing the node from it doesn't result in freeing it
    if (node->m_type & (itInstanceRoot | itLayerRoot))
    {
        // node can be deleted by the Delete, let's check its type while we safely can
        bool is_instance_root = (node->m_type & itInstanceRoot);
        for (int i = int(node->GetChildCount() - 1); i >= (is_instance_root ? 1 : 0); i--)
            Delete(wxDataViewItem(node->GetNthChild(i)));
        return parent;
    }
    auto id = node_parent->GetChildren().Index(node);
    auto idx = node->GetIdx();
    if (node->m_type & (itVolume | itLayer)) {
        node_parent->m_volumes_cnt--;
        DeleteSettings(item);
    }
    node_parent->GetChildren().Remove(node);
    if (id > 0) {
        if (size_t(id) == node_parent->GetChildCount()) id--;
        ret_item = wxDataViewItem(node_parent->GetChildren().Item(id));
    }
    //update idx value for remaining child-nodes
    auto children = node_parent->GetChildren();
    for (size_t i = 0; i < node_parent->GetChildCount() && idx >= 0; i++)
    {
        auto cur_idx = children[i]->GetIdx();
        if (cur_idx > idx)
            children[i]->SetIdx(cur_idx - 1);
    }
    // if there is last instance item, delete both of it and instance root item
    if (node_parent->GetChildCount() == 1 && node_parent->GetNthChild(0)->m_type == itInstance)
    {
        delete node;
        ItemDeleted(parent, item);
        ObjectDataViewModelNode* last_instance_node = node_parent->GetNthChild(0);
        PrintIndicator last_instance_printable = last_instance_node->IsPrintable();
        node_parent->GetChildren().Remove(last_instance_node);
        delete last_instance_node;
        ItemDeleted(parent, wxDataViewItem(last_instance_node));
        ObjectDataViewModelNode* obj_node = node_parent->GetParent();
        obj_node->set_printable_icon(last_instance_printable);
        obj_node->GetChildren().Remove(node_parent);
        delete node_parent;
        ret_item = wxDataViewItem(obj_node);
#ifndef __WXGTK__
        if (obj_node->GetChildCount() == 0)
            obj_node->m_container = false;
#endif //__WXGTK__
        ItemDeleted(ret_item, wxDataViewItem(node_parent));
        return ret_item;
    }
    if (node->m_type & itInstance)
        UpdateObjectPrintable(wxDataViewItem(node_parent->GetParent()));
    // if there was last layer item, delete this one and layers root item
    if (node_parent->GetChildCount() == 0 && node_parent->m_type == itLayerRoot)
    {
        ObjectDataViewModelNode* obj_node = node_parent->GetParent();
        obj_node->GetChildren().Remove(node_parent);
        delete node_parent;
        ret_item = wxDataViewItem(obj_node);
#ifndef __WXGTK__
        if (obj_node->GetChildCount() == 0)
            obj_node->m_container = false;
#endif //__WXGTK__
        ItemDeleted(ret_item, wxDataViewItem(node_parent));
        return ret_item;
    }
    // if there is last volume item after deleting, delete this last volume too
    if (node_parent->GetChildCount() <= 3) // 3??? #ys_FIXME
    {
        int vol_cnt = 0;
        int vol_idx = 0;
        for (size_t i = 0; i < node_parent->GetChildCount(); ++i) {
            if (node_parent->GetNthChild(i)->GetType() == itVolume) {
                vol_idx = i;
                vol_cnt++;
            }
            if (vol_cnt > 1)
                break;
        }
        if (vol_cnt == 1) {
            delete node;
            ItemDeleted(parent, item);
            ObjectDataViewModelNode* last_child_node = node_parent->GetNthChild(vol_idx);
            DeleteSettings(wxDataViewItem(last_child_node));
            node_parent->GetChildren().Remove(last_child_node);
            node_parent->m_volumes_cnt = 0;
            delete last_child_node;
#ifndef __WXGTK__
            if (node_parent->GetChildCount() == 0)
                node_parent->m_container = false;
#endif //__WXGTK__
            ItemDeleted(parent, wxDataViewItem(last_child_node));
            // BBS: Current object is already removed in model.objects,
            // but it is still exists in m_objects at the moment.
            // So the object index calculated here is not valid.
#if 0
            wxCommandEvent event(wxCUSTOMEVT_LAST_VOLUME_IS_DELETED);
            auto it = find(m_objects.begin(), m_objects.end(), node_parent);
            event.SetInt(it == m_objects.end() ? -1 : it - m_objects.begin());
            wxPostEvent(m_ctrl, event);
#endif
            ret_item = parent;
            return ret_item;
        }
    }
    // free the node
    delete node;
    // set m_containet to FALSE if parent has no child
#ifndef __WXGTK__
    if (node_parent->GetChildCount() == 0)
        node_parent->m_container = false;
#endif //__WXGTK__
    ret_item = parent;
  // notify control
  ItemDeleted(parent, item);
  return ret_item;
}
References Slic3r::GUI::Delete, DeleteSettings(), Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetIdx(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::ObjectDataViewModelNode::GetParent(), Slic3r::GUI::ObjectDataViewModelNode::IsPrintable(), Slic3r::GUI::itInstance, Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itLayer, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itObject, Slic3r::GUI::itPlate, Slic3r::GUI::itVolume, Slic3r::GUI::ObjectDataViewModelNode::m_container, m_ctrl, m_objects, Slic3r::GUI::ObjectDataViewModelNode::m_plate_idx, m_plate_outside, m_plates, Slic3r::GUI::ObjectDataViewModelNode::m_type, ReparentObject(), Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon(), and UpdateObjectPrintable().
Referenced by Slic3r::GUI::ObjectList::del_subobject_item(), Slic3r::GUI::ObjectList::delete_all_connectors_for_object(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::ObjectList::delete_instance_from_list(), Slic3r::GUI::ObjectList::delete_object_from_list(), Slic3r::GUI::ObjectList::delete_object_from_list(), Slic3r::GUI::ObjectList::delete_volume_from_list(), Slic3r::GUI::ObjectList::paste_layers_into_list(), Slic3r::GUI::ObjectList::update_info_items(), Slic3r::GUI::ObjectList::update_object_list_by_printer_technology(), and Slic3r::GUI::ObjectList::update_settings_item_and_selection().
DeleteChildren()
void Slic3r::GUI::ObjectDataViewModel::DeleteChildren (wxDataViewItem & parent)
{
    ObjectDataViewModelNode *root = static_cast<ObjectDataViewModelNode*>(parent.GetID());
    if (!root)      // happens if item.IsOk()==false
        return;
    // first remove the node from the parent's array of children;
    // NOTE: MyObjectTreeModelNodePtrArray is only an array of _pointers_
    //       thus removing the node from it doesn't result in freeing it
    auto& children = root->GetChildren();
    for (int id = root->GetChildCount() - 1; id >= 0; --id)
    {
        auto node = children[id];
        auto item = wxDataViewItem(node);
        children.RemoveAt(id);
        if (node->m_type == itVolume)
            root->m_volumes_cnt--;
        // free the node
        delete node;
        // notify control
        ItemDeleted(parent, item);
    }
    // set m_containet to FALSE if parent has no child
#ifndef __WXGTK__
        root->m_container = false;
#endif //__WXGTK__
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), Slic3r::GUI::itVolume, Slic3r::GUI::ObjectDataViewModelNode::m_container, and Slic3r::GUI::ObjectDataViewModelNode::m_volumes_cnt.
Referenced by Slic3r::GUI::ObjectList::edit_layer_range().
DeleteLastInstance()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance (const wxDataViewItem & parent_item, size_t num)
{
    auto ret_item = wxDataViewItem(0);
    ObjectDataViewModelNode *parent_node = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    if (!parent_node) return ret_item;
    const int inst_root_id = get_root_idx(parent_node, itInstanceRoot);
    if (inst_root_id < 0) return ret_item;
    wxDataViewItemArray items;
    ObjectDataViewModelNode *inst_root_node = parent_node->GetNthChild(inst_root_id);
    const wxDataViewItem inst_root_item((void*)inst_root_node);
    const int inst_cnt = inst_root_node->GetChildCount();
    const bool delete_inst_root_item = inst_cnt - num < 2 ? true : false;
    PrintIndicator last_inst_printable = piUndef;
    int stop = delete_inst_root_item ? 0 : inst_cnt - num;
    for (int i = inst_cnt - 1; i >= stop;--i) {
        ObjectDataViewModelNode *last_instance_node = inst_root_node->GetNthChild(i);
        if (i==0) last_inst_printable = last_instance_node->IsPrintable();
        inst_root_node->GetChildren().Remove(last_instance_node);
        delete last_instance_node;
        ItemDeleted(inst_root_item, wxDataViewItem(last_instance_node));
    }
    if (delete_inst_root_item) {
        ret_item = parent_item;
        parent_node->GetChildren().Remove(inst_root_node);
        parent_node->set_printable_icon(last_inst_printable);
        ItemDeleted(parent_item, inst_root_item);
        ItemChanged(parent_item);
#ifndef __WXGTK__
        if (parent_node->GetChildCount() == 0)
            parent_node->m_container = false;
#endif //__WXGTK__
    }
    // update object_node printable property
    UpdateObjectPrintable(parent_item);
    return ret_item;
}
References Slic3r::GUI::get_root_idx(), Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::ObjectDataViewModelNode::IsPrintable(), Slic3r::GUI::itInstanceRoot, Slic3r::GUI::ObjectDataViewModelNode::m_container, Slic3r::GUI::piUndef, Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon(), and UpdateObjectPrintable().
Referenced by Slic3r::GUI::ObjectList::decrease_object_instances().
DeletePlate()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::DeletePlate (const int plate_idx)
{
    wxDataViewItem ret_item(nullptr);
    for (auto plate : m_plates) {
        if (plate->m_plate_idx == plate_idx) {
            ret_item = Delete(wxDataViewItem(plate));
        }
    }
    return ret_item;
}
References Slic3r::GUI::Delete, and m_plates.
Referenced by Slic3r::GUI::ObjectList::on_plate_deleted().
DeleteSettings()
void Slic3r::GUI::ObjectDataViewModel::DeleteSettings (const wxDataViewItem & parent)
{
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(parent.GetID());
    if (!node) return;
#if NEW_OBJECT_SETTING
    node->set_action_icon(false);
    ItemChanged(parent);
#else
    // if volume has a "settings"item, than delete it before volume deleting
    if (node->GetChildCount() > 0 && node->GetNthChild(0)->GetType() == itSettings) {
        auto settings_node = node->GetNthChild(0);
        auto settings_item = wxDataViewItem(settings_node);
        node->GetChildren().RemoveAt(0);
        delete settings_node;
        // BBS
        if (node->GetChildCount() == 0) {
            node->m_container = false;
        }
        ItemDeleted(parent, settings_item);
    }
#endif
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::ObjectDataViewModelNode::GetType(), Slic3r::GUI::itSettings, Slic3r::GUI::ObjectDataViewModelNode::m_container, and Slic3r::GUI::ObjectDataViewModelNode::set_action_icon().
Referenced by Delete(), DeleteVolumeChildren(), and Slic3r::GUI::ObjectList::object_config_options_changed().
DeleteVolumeChildren()
void Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren (wxDataViewItem & parent)
{
    ObjectDataViewModelNode *root = static_cast<ObjectDataViewModelNode*>(parent.GetID());
    if (!root)      // happens if item.IsOk()==false
        return;
    // first remove the node from the parent's array of children;
    // NOTE: MyObjectTreeModelNodePtrArray is only an array of _pointers_
    //       thus removing the node from it doesn't result in freeing it
    auto& children = root->GetChildren();
    for (int id = root->GetChildCount() - 1; id >= 0; --id)
    {
        auto node = children[id];
        if (node->m_type != itVolume)
            continue;
        auto item = wxDataViewItem(node);
        DeleteSettings(item);
        children.RemoveAt(id);
        // free the node
        delete node;
        // notify control
        ItemDeleted(parent, item);
    }
    root->m_volumes_cnt = 0;
    // set m_containet to FALSE if parent has no child
#ifndef __WXGTK__
    root->m_container = false;
#endif //__WXGTK__
}
References DeleteSettings(), Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), Slic3r::GUI::itVolume, Slic3r::GUI::ObjectDataViewModelNode::m_container, and Slic3r::GUI::ObjectDataViewModelNode::m_volumes_cnt.
Referenced by Slic3r::GUI::ObjectList::add_volumes_to_object_in_list(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::ObjectList::reorder_volumes_and_get_selection(), and Slic3r::GUI::ObjectList::split().
DeleteWarningIcon()
void Slic3r::GUI::ObjectDataViewModel::DeleteWarningIcon (const wxDataViewItem & item, const bool unmark_object = false)
{
    if (!item.IsOk())
        return;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node->GetBitmap().IsOk() || !(node->GetType() & (itVolume | itObject)))
        return;
    if (node->GetType() & itVolume) {
        node->SetWarningBitmap(m_volume_bmps[static_cast<int>(node->volume_type())], "");
        return;
    }
    node->SetWarningBitmap(wxNullBitmap, "");
    if (unmark_object)
    {
        wxDataViewItemArray children;
        GetChildren(item, children);
        for (const wxDataViewItem& child : children)
            DeleteWarningIcon(child);
    }
}
References DeleteWarningIcon(), Slic3r::GUI::ObjectDataViewModelNode::GetBitmap(), GetChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetType(), Slic3r::GUI::itObject, Slic3r::GUI::itVolume, m_volume_bmps, Slic3r::GUI::ObjectDataViewModelNode::SetWarningBitmap(), and Slic3r::GUI::ObjectDataViewModelNode::volume_type().
Referenced by DeleteWarningIcon(), and UpdateWarningIcon().
GetAllChildren()
void Slic3r::GUI::ObjectDataViewModel::GetAllChildren (const wxDataViewItem & parent, wxDataViewItemArray & array) const
{
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(parent.GetID());
  if (!node) {
        for (auto plate : m_plates)
            array.Add(wxDataViewItem((void*)plate));
  }
  else if (node->GetChildCount() == 0)
    return;
    else {
        const size_t count = node->GetChildren().GetCount();
        for (size_t pos = 0; pos < count; pos++) {
            ObjectDataViewModelNode *child = node->GetChildren().Item(pos);
            array.Add(wxDataViewItem((void*)child));
        }
    }
    wxDataViewItemArray new_array = array;
    for (const auto& item : new_array)
    {
        wxDataViewItemArray children;
        GetAllChildren(item, children);
        WX_APPEND_ARRAY(array, children);
    }
}
References count, GetAllChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), and m_plates.
Referenced by Slic3r::GUI::ObjectList::fix_multiselection_conflicts(), GetAllChildren(), Rescale(), Slic3r::GUI::ObjectList::update_min_height(), Slic3r::GUI::ObjectList::update_object_list_by_printer_technology(), and UpdateColumValues().
GetBitmap()
wxBitmap & Slic3r::GUI::ObjectDataViewModel::GetBitmap (const wxDataViewItem & item) const
{
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    return node->m_bmp;
}
References Slic3r::GUI::ObjectDataViewModelNode::m_bmp.
GetChildren()
unsigned int Slic3r::GUI::ObjectDataViewModel::GetChildren (const wxDataViewItem & parent, wxDataViewItemArray & array) const override
{
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(parent.GetID());
  if (!node)
  {
        int node_count = 0;
        for (auto plate : m_plates)
            array.Add(wxDataViewItem((void*)plate));
        node_count += m_plates.size();
        /* FIX: should only return first layer children
        for (auto object : m_objects) {
            if (object->GetParent() == nullptr) {
                array.Add(wxDataViewItem((void*)object));
                node_count++;
            }
        }*/
        return node_count++;
  }
  if (node->GetChildCount() == 0)
  {
    return 0;
  }
    unsigned int count = node->GetChildren().GetCount();
    for (unsigned int pos = 0; pos < count; pos++)
    {
        ObjectDataViewModelNode* child = node->GetChildren().Item(pos);
        array.Add(wxDataViewItem((void*)child));
    }
    return count;
}
References count, Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), and m_plates.
Referenced by DeleteWarningIcon(), Slic3r::GUI::ObjectList::fix_multiselection_conflicts(), Slic3r::GUI::ObjectList::on_plate_deleted(), Slic3r::GUI::ObjectList::remove(), Slic3r::GUI::ObjectList::select_item_all_children(), Slic3r::GUI::ObjectList::update_object_list_by_printer_technology(), Slic3r::GUI::update_selection(), and UpdateCutObjectIcon().
GetColumnCount()
unsigned int Slic3r::GUI::ObjectDataViewModel::GetColumnCount () const inline override
{ return 3;}
GetColumnType()
wxString Slic3r::GUI::ObjectDataViewModel::GetColumnType (unsigned int col) const override
{
    if (col == colName || col == colFilament)
        return wxT("DataViewBitmapText");
    // BBS
    if (/*col == colPrint || */col == colEditing)
        return wxT("DataViewBitmap");
    return wxT("string");
}
References col(), Slic3r::GUI::colEditing, Slic3r::GUI::colFilament, and Slic3r::GUI::colName.
GetDefaultExtruderIdx()
int Slic3r::GUI::ObjectDataViewModel::GetDefaultExtruderIdx (wxDataViewItem item)
{
    ItemType type = GetItemType(item);
    if (type == itObject)
        return 0;
    if (type == itVolume && GetVolumeType(item) == ModelVolumeType::MODEL_PART) {
        wxDataViewItem obj_item = GetParent(item);
        int extruder_id = GetExtruderNumber(obj_item);
        if (extruder_id > 0) extruder_id--;
        return extruder_id;
    }
    return -1;
}
References GetExtruderNumber(), GetItemType(), GetParent(), GetVolumeType(), Slic3r::GUI::itObject, Slic3r::GUI::itVolume, and Slic3r::MODEL_PART.
Referenced by Slic3r::GUI::ObjectList::create_objects_ctrl().
GetExtruder()
wxString Slic3r::GUI::ObjectDataViewModel::GetExtruder (const wxDataViewItem & item) const
{
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  if (!node)      // happens if item.IsOk()==false
    return wxEmptyString;
  return node->m_extruder;
}
References Slic3r::GUI::ObjectDataViewModelNode::m_extruder.
GetExtruderNumber()
int Slic3r::GUI::ObjectDataViewModel::GetExtruderNumber (const wxDataViewItem & item) const
{
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  if (!node)      // happens if item.IsOk()==false
    return 0;
  return atoi(node->m_extruder.c_str());
}
References Slic3r::GUI::ObjectDataViewModelNode::m_extruder.
Referenced by Slic3r::GUI::ObjectList::extruder_editing(), GetDefaultExtruderIdx(), and Slic3r::GUI::ObjectList::update_filament_in_config().
GetIdByItem()
int Slic3r::GUI::ObjectDataViewModel::GetIdByItem (const wxDataViewItem & item) const
{
  if(!item.IsOk())
        return -1;
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  auto it = find(m_objects.begin(), m_objects.end(), node);
  if (it == m_objects.end())
    return -1;
  return it - m_objects.begin();
}
References m_objects.
Referenced by Slic3r::GUI::ObjectList::add_layer_root_item(), Slic3r::GUI::ObjectList::can_drop(), Slic3r::GUI::ObjectList::get_selected_item_indexes(), Slic3r::GUI::ObjectList::get_selected_obj_idx(), Slic3r::GUI::ObjectList::get_selection_indexes(), GetObjectIdByItem(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::ObjectList::OnBeginDrag(), Slic3r::GUI::ObjectList::OnDrop(), Slic3r::GUI::ObjectList::remove(), and Slic3r::GUI::ObjectList::update_filament_in_config().
GetIdByItemAndType()
int Slic3r::GUI::ObjectDataViewModel::GetIdByItemAndType (const wxDataViewItem & item, const ItemType type) const
{
  wxASSERT(item.IsOk());
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  if (!node || node->m_type != type)
    return -1;
  return node->GetIdx();
}
References Slic3r::GUI::ObjectDataViewModelNode::GetIdx(), and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by GetInstanceIdByItem(), GetLayerIdByItem(), and GetVolumeIdByItem().
GetInfoItemByType()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType (const wxDataViewItem & parent_item, InfoItemType type) const
{
    if (! parent_item.IsOk())
        return wxDataViewItem(0);
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    for (size_t i = 0; i < node->GetChildCount(); i++) {
        const ObjectDataViewModelNode* child_node = node->GetNthChild(i);
        if (child_node->m_type == itInfo && child_node->m_info_item_type == type)
            return wxDataViewItem((void*)child_node);
    }
    return wxDataViewItem(0); // not found
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::itInfo, Slic3r::GUI::ObjectDataViewModelNode::m_info_item_type, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by Slic3r::GUI::ObjectList::update_info_items(), and Slic3r::GUI::ObjectList::update_selections().
GetInfoItemType()
InfoItemType Slic3r::GUI::ObjectDataViewModel::GetInfoItemType (const wxDataViewItem & item) const
{
    if (!item.IsOk())
        return InfoItemType::Undef;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    return node->m_info_item_type;
}
References Slic3r::GUI::ObjectDataViewModelNode::m_info_item_type, and Slic3r::GUI::Undef.
Referenced by AddInfoChild(), Slic3r::GUI::ObjectList::del_subobject_item(), Slic3r::GUI::ObjectList::is_connectors_item_selected(), Slic3r::GUI::ObjectList::is_connectors_item_selected(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
GetInstanceIdByItem()
int Slic3r::GUI::ObjectDataViewModel::GetInstanceIdByItem (const wxDataViewItem & item) const
{
    return GetIdByItemAndType(item, itInstance);
}
References GetIdByItemAndType(), and Slic3r::GUI::itInstance.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_printable(), Slic3r::GUI::MenuFactory::append_menu_item_set_printable(), Slic3r::GUI::ObjectList::fix_cut_selection(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::ObjectList::OnBeginDrag(), Slic3r::GUI::ObjectList::toggle_printable_state(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
GetInstanceRootItem()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetInstanceRootItem (const wxDataViewItem & item) const
{
    return GetItemByType(item, itInstanceRoot);
}
References GetItemByType(), and Slic3r::GUI::itInstanceRoot.
Referenced by Slic3r::GUI::ObjectList::add_object_to_list(), AddInstanceChild(), UpdateInstancesPrintable(), and UpdateObjectPrintable().
GetItemById() [1/2]
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetItemById (const int obj_idx, const int sub_obj_idx, const ItemType parent_type)
{
    if (size_t(obj_idx) >= m_objects.size()) {
        printf("Error! Out of objects range.\n");
        return wxDataViewItem(0);
    }
    auto item = GetItemByType(wxDataViewItem(m_objects[obj_idx]), parent_type);
    if (!item)
        return wxDataViewItem(0);
    auto parent = static_cast<ObjectDataViewModelNode*>(item.GetID());
    for (size_t i = 0; i < parent->GetChildCount(); i++)
        if (parent->GetNthChild(i)->m_idx == sub_obj_idx)
            return wxDataViewItem(parent->GetNthChild(i));
    return wxDataViewItem(0);
}
References GetItemByType(), and m_objects.
GetItemById() [2/2]
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetItemById (int obj_idx)
{
    if (size_t(obj_idx) >= m_objects.size())
  {
    printf("Error! Out of objects range.\n");
    return wxDataViewItem(0);
  }
  return wxDataViewItem(m_objects[obj_idx]);
}
References m_objects.
Referenced by Slic3r::GUI::ObjectList::add_object_to_list(), Slic3r::GUI::ObjectList::add_volumes_to_object_in_list(), Slic3r::GUI::MenuFactory::append_menu_item_settings(), Slic3r::GUI::ObjectList::decrease_object_instances(), Slic3r::GUI::ObjectList::del_subobject_from_object(), Slic3r::GUI::ObjectList::delete_all_connectors_for_object(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::ObjectList::delete_object_from_list(), Slic3r::GUI::ObjectList::edit_layer_range(), Slic3r::GUI::ObjectList::fix_cut_selection(), GetItemByInstanceId(), GetItemByLayerId(), GetItemByVolumeId(), Slic3r::GUI::ObjectList::increase_object_instances(), Slic3r::GUI::ObjectList::layers_editing(), Slic3r::GUI::ObjectList::load_mesh_part(), Slic3r::GUI::ObjectList::load_subobject(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::ObjectList::paste_layers_into_list(), Slic3r::GUI::ObjectList::paste_objects_into_list(), Slic3r::GUI::ObjectList::reorder_volumes_and_get_selection(), Slic3r::GUI::ObjectList::select_item_all_children(), SetPrintableState(), Slic3r::GUI::ObjectList::update_filament_values_for_items(), Slic3r::GUI::ObjectList::update_info_items(), Slic3r::GUI::ObjectList::update_item_error_icon(), Slic3r::GUI::ObjectList::update_lock_icons_for_model(), Slic3r::GUI::ObjectList::update_plate_values_for_items(), and Slic3r::GUI::ObjectList::update_selections().
GetItemByInstanceId()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetItemByInstanceId (int obj_idx, int inst_idx)
{
    return GetItemById(obj_idx, inst_idx, itInstanceRoot);
}
References GetItemById(), and Slic3r::GUI::itInstanceRoot.
Referenced by Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::ObjectList::delete_instance_from_list(), Slic3r::GUI::ObjectList::fix_cut_selection(), SetPrintableState(), and Slic3r::GUI::ObjectList::update_selections().
GetItemByLayerId()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetItemByLayerId (int obj_idx, int layer_idx)
{
    return GetItemById(obj_idx, layer_idx, itLayerRoot);
}
References GetItemById(), and Slic3r::GUI::itLayerRoot.
Referenced by Slic3r::GUI::ObjectList::update_selections().
GetItemByLayerRange()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetItemByLayerRange (const int obj_idx, const t_layer_height_range & layer_range)
{
    if (size_t(obj_idx) >= m_objects.size()) {
        printf("Error! Out of objects range.\n");
        return wxDataViewItem(0);
    }
    auto item = GetItemByType(wxDataViewItem(m_objects[obj_idx]), itLayerRoot);
    if (!item)
        return wxDataViewItem(0);
    auto parent = static_cast<ObjectDataViewModelNode*>(item.GetID());
    for (size_t i = 0; i < parent->GetChildCount(); i++)
        if (parent->GetNthChild(i)->m_layer_range == layer_range)
            return wxDataViewItem(parent->GetNthChild(i));
    return wxDataViewItem(0);
}
References GetItemByType(), Slic3r::GUI::itLayerRoot, and m_objects.
Referenced by Slic3r::GUI::ObjectList::add_layer_range_after_current(), Slic3r::GUI::ObjectList::del_layer_range(), Slic3r::GUI::ObjectList::edit_layer_range(), and GetItemIdByLayerRange().
GetItemByPlateId()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetItemByPlateId (int plate_idx)
{
    for (auto plate : m_plates) {
        if (plate->m_plate_idx == plate_idx)
            return wxDataViewItem(plate);
    }
    return wxDataViewItem(nullptr);
}
References m_plates.
Referenced by Slic3r::GUI::ObjectList::on_plate_selected(), and Slic3r::GUI::ObjectList::update_selections().
GetItemByType()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetItemByType (const wxDataViewItem & parent_item, ItemType type) const
{
    if (!parent_item.IsOk())
        return wxDataViewItem(0);
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    if (node->GetChildCount() == 0)
        return wxDataViewItem(0);
    for (size_t i = 0; i < node->GetChildCount(); i++) {
        if (node->GetNthChild(i)->m_type == type)
            return wxDataViewItem((void*)node->GetNthChild(i));
    }
    return wxDataViewItem(0);
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by GetInstanceRootItem(), GetItemById(), GetItemByLayerRange(), GetLayerRootItem(), and GetSettingsItem().
GetItemByVolumeId()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetItemByVolumeId (int obj_idx, int volume_idx)
{
    if (size_t(obj_idx) >= m_objects.size()) {
    printf("Error! Out of objects range.\n");
    return wxDataViewItem(0);
  }
    auto parent = m_objects[obj_idx];
    if (parent->GetChildCount() == 0 ||
        (parent->GetChildCount() == 1 && parent->GetNthChild(0)->GetType() & itSettings )) {
        if (volume_idx == 0)
            return GetItemById(obj_idx);
        printf("Error! Object has no one volume.\n");
        return wxDataViewItem(0);
    }
    for (size_t i = 0; i < parent->GetChildCount(); i++) {
        auto child = parent->GetNthChild(i);
        if (child->m_idx == volume_idx && child->GetType() & itVolume)
            return wxDataViewItem(parent->GetNthChild(i));
    }
    return wxDataViewItem(0);
}
References GetItemById(), Slic3r::GUI::itSettings, Slic3r::GUI::itVolume, and m_objects.
Referenced by Slic3r::GUI::ObjectList::can_drop(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::ObjectList::delete_volume_from_list(), SetPrintableState(), Slic3r::GUI::ObjectList::update_filament_values_for_items(), Slic3r::GUI::ObjectList::update_item_error_icon(), and Slic3r::GUI::ObjectList::update_selections().
GetItemIdByLayerRange()
int Slic3r::GUI::ObjectDataViewModel::GetItemIdByLayerRange (const int obj_idx, const t_layer_height_range & layer_range)
{
    wxDataViewItem item = GetItemByLayerRange(obj_idx, layer_range);
    if (!item)
        return -1;
    return GetLayerIdByItem(item);
}
References GetItemByLayerRange(), and GetLayerIdByItem().
Referenced by Slic3r::GUI::ObjectList::add_layer_range_after_current().
GetItemIndexForFirstVolume()
size_t Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume (ObjectDataViewModelNode * node_parent)
{
    assert(node_parent->m_volumes_cnt > 0);
    for (size_t vol_idx = 0; vol_idx < node_parent->GetChildCount(); vol_idx++)
        if (node_parent->GetNthChild(vol_idx)->GetType() == itVolume)
            return vol_idx;
    return -1;
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::ObjectDataViewModelNode::GetType(), Slic3r::GUI::itVolume, and Slic3r::GUI::ObjectDataViewModelNode::m_volumes_cnt.
Referenced by ReorganizeChildren().
GetItemInfo()
void Slic3r::GUI::ObjectDataViewModel::GetItemInfo (const wxDataViewItem & item, ItemType & type, int & obj_idx, int & idx)
{
    wxASSERT(item.IsOk());
    type = itUndef;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node ||
        node->GetIdx() <-1 ||
        ( node->GetIdx() == -1 &&
         !(node->GetType() & (itObject | itSettings | itInstanceRoot | itLayerRoot | itInfo))
        )
       )
        return;
    idx = node->GetIdx();
    type = node->GetType();
    ObjectDataViewModelNode *parent_node = node->GetParent();
    if (!parent_node) return;
    // get top parent (Object) node
    while (parent_node->m_type != itObject)
        parent_node = parent_node->GetParent();
    auto it = find(m_objects.begin(), m_objects.end(), parent_node);
    if (it != m_objects.end())
        obj_idx = it - m_objects.begin();
    else
        type = itUndef;
}
References Slic3r::GUI::ObjectDataViewModelNode::GetIdx(), Slic3r::GUI::ObjectDataViewModelNode::GetParent(), Slic3r::GUI::ObjectDataViewModelNode::GetType(), Slic3r::GUI::itInfo, Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itObject, Slic3r::GUI::itSettings, Slic3r::GUI::itUndef, m_objects, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by Slic3r::GUI::ObjectList::del_subobject_item().
GetItemType()
ItemType Slic3r::GUI::ObjectDataViewModel::GetItemType (const wxDataViewItem & item) const
{
    if (!item.IsOk())
        return itUndef;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    return node->m_type < 0 ? itUndef : node->m_type;
}
References Slic3r::GUI::itUndef, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::MenuFactory::append_menu_item_change_type(), Slic3r::GUI::MenuFactory::append_menu_item_printable(), Slic3r::GUI::MenuFactory::append_menu_item_set_printable(), Slic3r::GUI::MenuFactory::append_menu_item_settings(), Slic3r::GUI::ObjectList::can_drop(), Slic3r::GUI::ObjectList::can_merge_to_multipart_object(), Slic3r::GUI::ObjectList::check_last_selection(), Slic3r::GUI::ObjectList::copy_layers_to_clipboard(), Slic3r::GUI::ObjectList::copy_settings_to_clipboard(), Slic3r::GUI::ObjectList::copy_to_clipboard(), Slic3r::GUI::ObjectList::create_objects_ctrl(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::edit_layer_range(), Slic3r::GUI::ObjectList::extruder_editing(), Slic3r::GUI::ObjectList::fix_cut_selection(), Slic3r::GUI::ObjectList::fix_multiselection_conflicts(), Slic3r::GUI::ObjectList::get_item_config(), Slic3r::GUI::ObjectList::get_selected_item_indexes(), Slic3r::GUI::ObjectList::get_selected_layers_range_idx(), Slic3r::GUI::ObjectList::get_selected_model_volume(), Slic3r::GUI::ObjectList::get_selection_indexes(), Slic3r::GUI::ObjectList::get_volume_by_item(), GetDefaultExtruderIdx(), GetVolumeType(), Slic3r::GUI::ObjectList::is_connectors_item_selected(), Slic3r::GUI::ObjectList::is_connectors_item_selected(), Slic3r::GUI::ObjectList::is_selected(), Slic3r::GUI::ObjectList::is_splittable(), Slic3r::GUI::ObjectList::ItemValueChanged(), Slic3r::GUI::ObjectList::list_manipulation(), Slic3r::GUI::ObjectList::load_mesh_part(), Slic3r::GUI::ObjectList::load_subobject(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::MenuFactory::multi_selection_menu(), Slic3r::GUI::ObjectList::OnBeginDrag(), Slic3r::GUI::ObjectList::part_selection_changed(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::GUI::ObjectList::remove(), Slic3r::GUI::ObjectList::rename_item(), Slic3r::GUI::ObjectList::select_item_all_children(), Slic3r::GUI::ObjectList::select_object_item(), Slic3r::GUI::ObjectList::selected_instances_of_same_object(), Slic3r::GUI::ObjectList::selection_changed(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::ObjectList::set_tooltip_for_item(), SetVolumeType(), Slic3r::GUI::ObjectList::show_context_menu(), Slic3r::GUI::ObjectList::toggle_printable_state(), Slic3r::GUI::ObjectList::update_filament_in_config(), Slic3r::GUI::ObjectLayers::update_layers_list(), Slic3r::GUI::ObjectList::update_name_in_list(), Slic3r::GUI::ObjectList::update_name_in_model(), Slic3r::GUI::ObjectList::update_object_list_by_printer_technology(), Slic3r::GUI::update_selection(), Slic3r::GUI::ObjectList::update_selection_mode(), Slic3r::GUI::ObjectList::update_selections(), Slic3r::GUI::ObjectList::update_selections_on_canvas(), and UpdateVolumesExtruderBitmap().
GetLayerIdByItem()
int Slic3r::GUI::ObjectDataViewModel::GetLayerIdByItem (const wxDataViewItem & item) const
{
    return GetIdByItemAndType(item, itLayer);
}
References GetIdByItemAndType(), and Slic3r::GUI::itLayer.
Referenced by Slic3r::GUI::ObjectList::get_selected_layers_range_idx(), and GetItemIdByLayerRange().
GetLayerRangeByItem()
t_layer_height_range Slic3r::GUI::ObjectDataViewModel::GetLayerRangeByItem (const wxDataViewItem & item) const
{
    wxASSERT(item.IsOk());
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node || node->m_type != itLayer)
        return { 0.0f, 0.0f };
    return node->GetLayerRange();
}
References Slic3r::GUI::ObjectDataViewModelNode::GetLayerRange(), Slic3r::GUI::itLayer, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by Slic3r::GUI::ObjectList::copy_layers_to_clipboard(), Slic3r::GUI::ObjectList::del_subobject_item(), Slic3r::GUI::ObjectList::get_item_config(), Slic3r::GUI::ObjectList::selection_changed(), and Slic3r::GUI::ObjectLayers::update_layers_list().
GetLayerRootItem()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetLayerRootItem (const wxDataViewItem & item) const
{
    return GetItemByType(item, itLayerRoot);
}
References GetItemByType(), and Slic3r::GUI::itLayerRoot.
Referenced by Slic3r::GUI::ObjectList::edit_layer_range(), Slic3r::GUI::ObjectList::layers_editing(), Slic3r::GUI::ObjectList::paste_layers_into_list(), Slic3r::GUI::ObjectList::update_object_list_by_printer_technology(), and Slic3r::GUI::ObjectList::update_selections().
GetName()
wxString Slic3r::GUI::ObjectDataViewModel::GetName (const wxDataViewItem & item) const
{
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  if (!node)      // happens if item.IsOk()==false
    return wxEmptyString;
  return node->m_name;
}
References Slic3r::GUI::ObjectDataViewModelNode::m_name.
Referenced by Slic3r::GUI::ObjectList::add_volumes_to_object_in_list(), Slic3r::GUI::ObjectList::rename_item(), Slic3r::GUI::ObjectList::update_name_in_list(), and Slic3r::GUI::ObjectList::update_name_in_model().
GetObject()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetObject (const wxDataViewItem & item) const
{
    // the invisible root node has no parent
    if (!item.IsOk())
        return wxDataViewItem(0);
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (node->m_type & itPlate)
        return wxDataViewItem(0);
    if (node->m_type & itObject)
        return item;
    ObjectDataViewModelNode* parent_node = node->GetParent();
    while (parent_node->m_type != itObject)
        parent_node = parent_node->GetParent();
    return wxDataViewItem((void*)parent_node);
}
References Slic3r::GUI::ObjectDataViewModelNode::GetParent(), Slic3r::GUI::itObject, Slic3r::GUI::itPlate, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::ObjectList::check_last_selection(), Slic3r::GUI::ObjectList::get_selected_item_indexes(), Slic3r::GUI::ObjectList::get_selected_obj_idx(), Slic3r::GUI::ObjectList::get_selection_indexes(), GetObjectIdByItem(), Slic3r::GUI::ObjectList::layers_editing(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::ObjectList::remove(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::ObjectList::split(), Slic3r::GUI::ObjectList::update_filament_in_config(), Slic3r::GUI::update_selection(), and Slic3r::GUI::ObjectList::update_selections().
GetObjectIdByItem()
int Slic3r::GUI::ObjectDataViewModel::GetObjectIdByItem (const wxDataViewItem & item) const
{
    return GetIdByItem(GetObject(item));
}
References GetIdByItem(), and GetObject().
Referenced by Slic3r::GUI::ObjectList::add_layer_item(), Slic3r::GUI::MenuFactory::append_menu_item_printable(), Slic3r::GUI::MenuFactory::append_menu_item_set_printable(), Slic3r::GUI::ObjectList::can_drop(), Slic3r::GUI::ObjectList::copy_layers_to_clipboard(), Slic3r::GUI::ObjectList::delete_all_connectors_for_selection(), Slic3r::GUI::ObjectList::fix_cut_selection(), Slic3r::GUI::ObjectList::get_item_config(), Slic3r::GUI::ObjectList::get_mesh_errors_info(), Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::ObjectList::invalidate_cut_info_for_selection(), Slic3r::GUI::ObjectList::load_mesh_part(), Slic3r::GUI::ObjectList::load_subobject(), Slic3r::GUI::ObjectList::OnBeginDrag(), Slic3r::GUI::ObjectList::part_selection_changed(), Slic3r::GUI::ObjectList::paste_layers_into_list(), Slic3r::GUI::ObjectList::printable_state_changed(), Slic3r::GUI::ObjectList::selected_instances_of_same_object(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::ObjectList::set_tooltip_for_item(), Slic3r::GUI::ObjectList::toggle_printable_state(), Slic3r::GUI::ObjectList::update_name_in_model(), Slic3r::GUI::ObjectList::update_object_list_by_printer_technology(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
GetObjectItem()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetObjectItem (const ModelObject * mo) const
{
    for (auto object_node : m_objects) {
        if (object_node->m_model_object == mo) {
            return wxDataViewItem(object_node);
        }
    }
    return wxDataViewItem(nullptr);
}
References m_objects.
Referenced by Slic3r::GUI::ObjectList::object_config_options_changed(), Slic3r::GUI::ObjectList::printable_state_changed(), and Slic3r::GUI::ObjectList::select_items().
GetParent()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetParent (const wxDataViewItem & item) const override
{
  // the invisible root node has no parent
  if (!item.IsOk())
    return wxDataViewItem(0);
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  assert(node != nullptr && node->valid());
  // objects nodes has no parent too
    if (node->m_type == itPlate)
    return wxDataViewItem(0);
  return wxDataViewItem((void*)node->GetParent());
}
References Slic3r::GUI::ObjectDataViewModelNode::GetParent(), Slic3r::GUI::itPlate, Slic3r::GUI::ObjectDataViewModelNode::m_type, and Slic3r::GUI::ObjectDataViewModelNode::valid().
Referenced by Slic3r::GUI::ObjectList::add_object_to_list(), Slic3r::GUI::MenuFactory::append_menu_item_settings(), Slic3r::GUI::ObjectList::copy_settings_to_clipboard(), Slic3r::GUI::ObjectList::del_layer_range(), Slic3r::GUI::ObjectList::del_subobject_item(), Slic3r::GUI::ObjectList::delete_object_from_list(), Slic3r::GUI::ObjectList::fix_cut_selection(), Slic3r::GUI::ObjectList::fix_multiselection_conflicts(), Slic3r::GUI::ObjectList::get_selected_layers_range_idx(), Slic3r::GUI::ObjectList::get_selected_model_volume(), Slic3r::GUI::ObjectList::get_selection_indexes(), GetDefaultExtruderIdx(), Slic3r::GUI::ObjectList::is_splittable(), Slic3r::GUI::ObjectList::OnDrop(), Slic3r::GUI::ObjectList::part_selection_changed(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::GUI::ObjectList::remove(), Slic3r::GUI::ObjectList::select_item_all_children(), Slic3r::GUI::ObjectList::select_object_item(), Slic3r::GUI::ObjectList::update_plate_values_for_items(), Slic3r::GUI::update_selection(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
GetRowByItem()
int Slic3r::GUI::ObjectDataViewModel::GetRowByItem (const wxDataViewItem & item) const
{
    if (m_objects.empty())
        return -1;
    int row_num = 0;
    for (size_t i = 0; i < m_objects.size(); i++)
    {
        row_num++;
        if (item == wxDataViewItem(m_objects[i]))
            return row_num;
        for (size_t j = 0; j < m_objects[i]->GetChildCount(); j++)
        {
            row_num++;
            ObjectDataViewModelNode* cur_node = m_objects[i]->GetNthChild(j);
            if (item == wxDataViewItem(cur_node))
                return row_num;
            if (cur_node->m_type == itVolume && cur_node->GetChildCount() == 1)
                row_num++;
            if (cur_node->m_type == itInstanceRoot)
            {
                row_num++;
                for (size_t t = 0; t < cur_node->GetChildCount(); t++)
                {
                    row_num++;
                    if (item == wxDataViewItem(cur_node->GetNthChild(t)))
                        return row_num;
                }
            }
        }
    }
    return -1;
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildCount(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itVolume, m_objects, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
GetSettingsItem()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetSettingsItem (const wxDataViewItem & item) const
{
    return GetItemByType(item, itSettings);
}
References GetItemByType(), and Slic3r::GUI::itSettings.
Referenced by Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::ObjectList::update_settings_item_and_selection().
GetTopParent()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetTopParent (const wxDataViewItem & item) const
{
  // the invisible root node has no parent
  if (!item.IsOk())
    return wxDataViewItem(0);
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (node->m_type == itPlate)
        return item;
    ObjectDataViewModelNode *parent_node = node->GetParent();
    while (parent_node->m_type != itPlate)
        parent_node = parent_node->GetParent();
    return wxDataViewItem((void*)parent_node);
}
References Slic3r::GUI::ObjectDataViewModelNode::GetParent(), Slic3r::GUI::itPlate, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by Slic3r::GUI::ObjectList::select_object_item().
GetValue()
void Slic3r::GUI::ObjectDataViewModel::GetValue (wxVariant & variant, const wxDataViewItem & item, unsigned int col) const override
{
  wxASSERT(item.IsOk());
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  switch (col)
  {
  case colPrint:
    variant << node->m_printable_icon;
    break;
  case colName:
        variant << DataViewBitmapText(node->m_name, node->m_bmp);
    break;
  case colFilament:
    variant << DataViewBitmapText(node->m_extruder, node->m_extruder_bmp);
    break;
    // BBS
    case colSupportPaint:
        variant << node->m_support_icon;
        break;
    case colSinking:
        variant << node->m_sinking_icon;
        break;
    case colColorPaint:
        variant << node->m_color_icon;
        break;
  case colEditing:
    variant << node->m_action_icon;
    break;
  default:
    ;
  }
}
References col(), Slic3r::GUI::colColorPaint, Slic3r::GUI::colEditing, Slic3r::GUI::colFilament, Slic3r::GUI::colName, Slic3r::GUI::colPrint, Slic3r::GUI::colSinking, Slic3r::GUI::colSupportPaint, Slic3r::GUI::ObjectDataViewModelNode::m_action_icon, Slic3r::GUI::ObjectDataViewModelNode::m_bmp, Slic3r::GUI::ObjectDataViewModelNode::m_color_icon, Slic3r::GUI::ObjectDataViewModelNode::m_extruder, Slic3r::GUI::ObjectDataViewModelNode::m_extruder_bmp, Slic3r::GUI::ObjectDataViewModelNode::m_name, Slic3r::GUI::ObjectDataViewModelNode::m_printable_icon, Slic3r::GUI::ObjectDataViewModelNode::m_sinking_icon, and Slic3r::GUI::ObjectDataViewModelNode::m_support_icon.
Referenced by SetName().
GetVolumeIcon()
wxBitmap Slic3r::GUI::ObjectDataViewModel::GetVolumeIcon (const Slic3r::ModelVolumeType vol_type, const std::string & warning_icon_name = std::string())
{
    if (warning_icon_name.empty())
        return m_volume_bmps[static_cast<int>(vol_type)];
    std::string scaled_bitmap_name = warning_icon_name + std::to_string(static_cast<int>(vol_type));
    scaled_bitmap_name += "-em" + std::to_string(wxGetApp().em_unit()) + (wxGetApp().dark_mode() ? "-dm" : "-lm");
    wxBitmap *bmp = m_bitmap_cache->find(scaled_bitmap_name);
    if (bmp == nullptr) {
        std::vector<wxBitmap> bmps;
        bmps.emplace_back(GetWarningBitmap(warning_icon_name));
        bmps.emplace_back(m_volume_bmps[static_cast<int>(vol_type)]);
        bmp = m_bitmap_cache->insert(scaled_bitmap_name, bmps);
    }
    return *bmp;
}
References em_unit(), Slic3r::GUI::BitmapCache::find(), GetWarningBitmap(), Slic3r::GUI::BitmapCache::insert(), Slic3r::GUI::m_bitmap_cache, and m_volume_bmps.
Referenced by AddVolumeChild(), AddWarningIcon(), and Rescale().
GetVolumeIdByItem()
int Slic3r::GUI::ObjectDataViewModel::GetVolumeIdByItem (const wxDataViewItem & item) const
{
    return GetIdByItemAndType(item, itVolume);
}
References GetIdByItemAndType(), and Slic3r::GUI::itVolume.
Referenced by Slic3r::GUI::ObjectList::can_drop(), Slic3r::GUI::ObjectList::get_item_config(), Slic3r::GUI::ObjectList::get_selected_item_indexes(), Slic3r::GUI::ObjectList::get_selected_model_volume(), Slic3r::GUI::ObjectList::get_selection_indexes(), Slic3r::GUI::ObjectList::get_volume_by_item(), Slic3r::GUI::ObjectList::OnBeginDrag(), Slic3r::GUI::ObjectList::OnDrop(), Slic3r::GUI::ObjectList::part_selection_changed(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::ObjectList::set_tooltip_for_item(), Slic3r::GUI::ObjectList::update_filament_in_config(), Slic3r::GUI::ObjectList::update_name_in_model(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
GetVolumeItem()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::GetVolumeItem (const wxDataViewItem & parent, int vol_idx) const
{
    ObjectDataViewModelNode* obj_node = (ObjectDataViewModelNode*)parent.GetID();
    // BBS
    if (obj_node != nullptr) {
        for (auto child : obj_node->GetChildren()) {
            if (child->GetType() == itVolume && child->GetIdx() == vol_idx)
                return wxDataViewItem(child);
        }
    }
    return wxDataViewItem(nullptr);
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), and Slic3r::GUI::itVolume.
Referenced by Slic3r::GUI::ObjectList::object_config_options_changed(), and Slic3r::GUI::ObjectList::select_items().
GetVolumeType()
ModelVolumeType Slic3r::GUI::ObjectDataViewModel::GetVolumeType (const wxDataViewItem & item)
{
    if (!item.IsOk() || GetItemType(item) != itVolume)
        return ModelVolumeType::INVALID;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    return node->GetVolumeType();
}
References GetItemType(), Slic3r::GUI::ObjectDataViewModelNode::GetVolumeType(), Slic3r::INVALID, and Slic3r::GUI::itVolume.
Referenced by Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::MenuFactory::append_menu_item_change_filament(), Slic3r::GUI::ObjectList::can_drop(), Slic3r::GUI::ObjectList::create_objects_ctrl(), and GetDefaultExtruderIdx().
GetWarningBitmap()
wxBitmap & Slic3r::GUI::ObjectDataViewModel::GetWarningBitmap (const std::string & warning_icon_name) private
{
    return warning_icon_name.empty() ? m_empty_bmp : warning_icon_name == WarningIcon ? m_warning_bmp : m_warning_manifold_bmp;
}
References m_empty_bmp, m_warning_bmp, m_warning_manifold_bmp, and Slic3r::GUI::WarningIcon.
Referenced by AddObject(), AddVolumeChild(), AddWarningIcon(), GetVolumeIcon(), and Rescale().
HasContainerColumns()
bool Slic3r::GUI::ObjectDataViewModel::HasContainerColumns (const wxDataViewItem & WXUNUSEDitem) const inline override
{ return true; }
HasInfoItem()
bool Slic3r::GUI::ObjectDataViewModel::HasInfoItem (InfoItemType type) const
{
    for (ObjectDataViewModelNode* obj_node : m_objects)
        for (size_t j = 0; j < obj_node->GetChildCount(); j++)
            if (obj_node->GetNthChild(j)->GetInfoItemType() == type)
                return true;
    return false;
}
References m_objects.
Referenced by Slic3r::GUI::ObjectList::has_paint_on_segmentation().
HasWarningIcon()
bool Slic3r::GUI::ObjectDataViewModel::HasWarningIcon (const wxDataViewItem & item) const
{
    if (!item.IsOk())
        return false;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    return node->has_warning_icon();
}
References Slic3r::GUI::ObjectDataViewModelNode::has_warning_icon().
Referenced by Slic3r::GUI::ObjectList::list_manipulation().
Init()
void Slic3r::GUI::ObjectDataViewModel::Init ()
{
    PartPlateList& list = wxGetApp().plater()->get_partplate_list();
    if (list.get_plate_count() > 0)
        AddPlate(list.get_plate(0));
    AddOutsidePlate();
}
References AddOutsidePlate(), AddPlate(), Slic3r::GUI::PartPlateList::get_plate(), and Slic3r::GUI::PartPlateList::get_plate_count().
Referenced by Slic3r::GUI::ObjectList::init().
InvalidItem()
bool Slic3r::GUI::ObjectDataViewModel::InvalidItem (const wxDataViewItem & item)
{
    if (!item)
        return true;
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node || node->invalid())
        return true;
    return false;
}
References Slic3r::GUI::ObjectDataViewModelNode::invalid().
Referenced by Slic3r::GUI::ObjectList::remove().
IsColorPainted()
bool Slic3r::GUI::ObjectDataViewModel::IsColorPainted (wxDataViewItem & item) const
{
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node)
        return false;
    return node->m_color_enable;
}
References Slic3r::GUI::ObjectDataViewModelNode::m_color_enable.
Referenced by Slic3r::GUI::ObjectList::update_info_items().
IsContainer()
bool Slic3r::GUI::ObjectDataViewModel::IsContainer (const wxDataViewItem & item) const override
{
  // the invisible root node can have children
  if (!item.IsOk())
    return true;
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  return node->IsContainer();
}
References Slic3r::GUI::ObjectDataViewModelNode::IsContainer().
IsEmpty()
bool Slic3r::GUI::ObjectDataViewModel::IsEmpty () inline
{ return m_objects.empty(); }
References m_objects.
IsEnabled()
bool Slic3r::GUI::ObjectDataViewModel::IsEnabled (const wxDataViewItem & item, unsigned int col) const override
{
    bool ret;
    wxASSERT(item.IsOk());
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    // disable extruder selection for the non "itObject|itVolume" item
    ret = !(col == colFilament && node->m_extruder.IsEmpty());
    return ret;
}
References col(), Slic3r::GUI::colFilament, and Slic3r::GUI::ObjectDataViewModelNode::m_extruder.
IsPrintable()
bool Slic3r::GUI::ObjectDataViewModel::IsPrintable (const wxDataViewItem & item) const
{
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node)
        return false;
    return node->IsPrintable() == piPrintable;
}
References Slic3r::GUI::ObjectDataViewModelNode::IsPrintable(), and Slic3r::GUI::piPrintable.
Referenced by AddInstanceChild().
IsSettingsItem()
bool Slic3r::GUI::ObjectDataViewModel::IsSettingsItem (const wxDataViewItem & item) const
{
    if (!item.IsOk())
        return false;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    return node->m_type == itSettings;
}
References Slic3r::GUI::itSettings, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by Slic3r::GUI::ObjectList::add_settings_item().
IsSinked()
bool Slic3r::GUI::ObjectDataViewModel::IsSinked (wxDataViewItem & item) const
{
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode *>(item.GetID());
    if (!node) return false;
    return node->m_sink_enable;
}
References Slic3r::GUI::ObjectDataViewModelNode::m_sink_enable.
Referenced by Slic3r::GUI::ObjectList::update_info_items().
IsSupportPainted()
bool Slic3r::GUI::ObjectDataViewModel::IsSupportPainted (wxDataViewItem & item) const
{
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node)
        return false;
    return node->m_support_enable;
}
References Slic3r::GUI::ObjectDataViewModelNode::m_support_enable.
Referenced by Slic3r::GUI::ObjectList::update_info_items().
OnPlateChange()
void Slic3r::GUI::ObjectDataViewModel::OnPlateChange (const int plate_idx, wxDataViewItem item)
{
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    ObjectDataViewModelNode* parent_plate = m_plate_outside;
    for (auto plate : m_plates) {
        if (plate->m_plate_idx == plate_idx) {
            parent_plate = plate;
        }
    }
    ReparentObject(parent_plate, node);
}
References m_plate_outside, m_plates, and ReparentObject().
Referenced by Slic3r::GUI::ObjectList::update_plate_values_for_items().
ReorganizeChildren()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::ReorganizeChildren (const int cur_volume_id, const int new_volume_id, const wxDataViewItem & parent)
{
    auto ret_item = wxDataViewItem(0);
    if (current_volume_id == new_volume_id)
        return ret_item;
    wxASSERT(parent.IsOk());
    ObjectDataViewModelNode *node_parent = static_cast<ObjectDataViewModelNode*>(parent.GetID());
    if (!node_parent)      // happens if item.IsOk()==false
        return ret_item;
    size_t shift = GetItemIndexForFirstVolume(node_parent);
    ObjectDataViewModelNode *deleted_node = node_parent->GetNthChild(current_volume_id+shift);
    node_parent->GetChildren().Remove(deleted_node);
    ItemDeleted(parent, wxDataViewItem(deleted_node));
    node_parent->Insert(deleted_node, new_volume_id+shift);
    ItemAdded(parent, wxDataViewItem(deleted_node));
    // If some item has a children, just to add a deleted item is not enough on Linux
    // We should to add all its children separately
    AddAllChildren(wxDataViewItem(deleted_node));
    //update volume_id value for child-nodes
    auto children = node_parent->GetChildren();
    int id_frst = current_volume_id < new_volume_id ? current_volume_id : new_volume_id;
    int id_last = current_volume_id > new_volume_id ? current_volume_id : new_volume_id;
    for (int id = id_frst; id <= id_last; ++id)
        children[id+shift]->SetIdx(id);
    return wxDataViewItem(node_parent->GetNthChild(new_volume_id+shift));
}
References AddAllChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), GetItemIndexForFirstVolume(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), and Slic3r::GUI::ObjectDataViewModelNode::Insert().
Referenced by Slic3r::GUI::ObjectList::OnDrop().
ReorganizeObjects()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::ReorganizeObjects (int current_id, int new_id)
{
    if (current_id == new_id)
        return wxDataViewItem(nullptr);
    ObjectDataViewModelNode* deleted_node = m_objects[current_id];
    ObjectDataViewModelNode* new_node = m_objects[new_id];
    ObjectDataViewModelNode* plate_node = deleted_node->m_parent;
    m_objects.erase(m_objects.begin() + current_id);
    plate_node->GetChildren().Remove(deleted_node);
    ItemDeleted(wxDataViewItem(deleted_node->m_parent), wxDataViewItem(deleted_node));
    m_objects.emplace(m_objects.begin() + new_id, deleted_node);
    int plate_child_index = plate_node->GetChildIndex(new_node);
    if (current_id < new_id)
        plate_node->Insert(deleted_node, plate_child_index+1);
    else {
        //should not happen
        plate_node->Insert(deleted_node, plate_child_index);
    }
    ItemAdded(wxDataViewItem(deleted_node->m_parent), wxDataViewItem(deleted_node));
    //ItemChanged(wxDataViewItem(nullptr));
    // If some item has a children, just to add a deleted item is not enough on Linux
    // We should to add all its children separately
    AddAllChildren(wxDataViewItem(deleted_node));
    return wxDataViewItem(deleted_node);
}
References AddAllChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetChildIndex(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), Slic3r::GUI::ObjectDataViewModelNode::Insert(), m_objects, and Slic3r::GUI::ObjectDataViewModelNode::m_parent.
Referenced by Slic3r::GUI::ObjectList::OnDrop().
ReparentObject()
void Slic3r::GUI::ObjectDataViewModel::ReparentObject (ObjectDataViewModelNode * plate, ObjectDataViewModelNode * object) private
{
    assert(plate != nullptr && (plate->m_type & itPlate) != 0);
    assert(object != nullptr && (object->m_type & itObject) != 0);
    ObjectDataViewModelNode* old_plate = object->m_parent;
    assert(old_plate != nullptr && (old_plate->m_type & itPlate) != 0);
    if (old_plate == plate)
        return;
    old_plate->GetChildren().Remove(object);
    ItemDeleted(wxDataViewItem(old_plate), wxDataViewItem(object));
    object->m_plate_idx = plate->m_plate_idx;
    object->m_parent = plate;
    plate->Append(object);
    ItemAdded(wxDataViewItem(plate), wxDataViewItem(object));
}
References Slic3r::GUI::ObjectDataViewModelNode::Append(), Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), Slic3r::GUI::itObject, Slic3r::GUI::itPlate, Slic3r::GUI::ObjectDataViewModelNode::m_parent, Slic3r::GUI::ObjectDataViewModelNode::m_plate_idx, and Slic3r::GUI::ObjectDataViewModelNode::m_type.
Referenced by AddPlate(), Delete(), and OnPlateChange().
Rescale()
void Slic3r::GUI::ObjectDataViewModel::Rescale ()
{
    m_volume_bmps = MenuFactory::get_volume_bitmaps();
    m_warning_bmp = create_scaled_bitmap(WarningIcon);
    m_warning_manifold_bmp = create_scaled_bitmap(WarningManifoldIcon);
    m_lock_bmp = create_scaled_bitmap(LockIcon);
    for (auto item : INFO_ITEMS)
        m_info_bmps[item.first] = create_scaled_bitmap(item.second.bmp_name);
    wxDataViewItemArray all_items;
    GetAllChildren(wxDataViewItem(0), all_items);
    for (wxDataViewItem item : all_items)
    {
        if (!item.IsOk())
            continue;
        ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
        node->msw_rescale();
        switch (node->m_type)
        {
        case itObject:
            if (node->m_bmp.IsOk()) node->m_bmp = GetWarningBitmap(node->m_warning_icon_name);
            break;
        case itVolume:
            node->m_bmp = GetVolumeIcon(node->m_volume_type, node->m_warning_icon_name);
            break;
        case itLayerRoot:
            node->m_bmp = create_scaled_bitmap(LayerRootIcon);
            break;
        case itLayer:
            node->m_bmp = create_scaled_bitmap(LayerIcon);
            break;
        case itInfo:
            node->m_bmp = m_info_bmps.at(node->m_info_item_type);
            break;
        default: break;
        }
        ItemChanged(item);
    }
}
References create_scaled_bitmap(), Slic3r::GUI::MenuFactory::get_volume_bitmaps(), GetAllChildren(), GetVolumeIcon(), GetWarningBitmap(), Slic3r::GUI::INFO_ITEMS, Slic3r::GUI::itInfo, Slic3r::GUI::itLayer, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itObject, Slic3r::GUI::itVolume, Slic3r::GUI::LayerIcon, Slic3r::GUI::LayerRootIcon, Slic3r::GUI::LockIcon, Slic3r::GUI::ObjectDataViewModelNode::m_bmp, m_info_bmps, Slic3r::GUI::ObjectDataViewModelNode::m_info_item_type, m_lock_bmp, Slic3r::GUI::ObjectDataViewModelNode::m_type, m_volume_bmps, Slic3r::GUI::ObjectDataViewModelNode::m_volume_type, m_warning_bmp, Slic3r::GUI::ObjectDataViewModelNode::m_warning_icon_name, m_warning_manifold_bmp, Slic3r::GUI::ObjectDataViewModelNode::msw_rescale(), Slic3r::GUI::WarningIcon, and Slic3r::GUI::WarningManifoldIcon.
Referenced by Slic3r::GUI::ObjectList::msw_rescale().
ResetAll()
void Slic3r::GUI::ObjectDataViewModel::ResetAll ()
{
    // BBS
    // FIX: should remove from children collection soon, or will conflict GetChildren
    while (!m_plates.empty()) {
        auto plate = m_plates.front();
        Delete(wxDataViewItem(plate));
    }
    m_plates.clear();
    m_plate_outside = nullptr;
    m_objects.clear();
    AddOutsidePlate();
}
References AddOutsidePlate(), Slic3r::GUI::Delete, m_objects, m_plate_outside, and m_plates.
Referenced by Slic3r::GUI::ObjectList::reload_all_plates().
SetAssociatedControl()
void Slic3r::GUI::ObjectDataViewModel::SetAssociatedControl (wxDataViewCtrl * ctrl) inline
{ m_ctrl = ctrl; }
References Slic3r::GUI::ctrl, and m_ctrl.
Referenced by Slic3r::GUI::ObjectList::create_objects_ctrl().
SetColorPaintState()
void Slic3r::GUI::ObjectDataViewModel::SetColorPaintState (const bool painted, wxDataViewItem obj_item)
{
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(obj_item.GetID());
    if (!node)
        return;
    node->set_color_icon(painted);
    ItemChanged(obj_item);
}
References Slic3r::GUI::ObjectDataViewModelNode::set_color_icon().
Referenced by Slic3r::GUI::ObjectList::update_info_items().
SetExtruder()
void Slic3r::GUI::ObjectDataViewModel::SetExtruder (const wxString & extruder, wxDataViewItem item)
{
    if (!item.IsOk())
        return;
    // BBS. Don't support to set extruder for plate.
    ObjectDataViewModelNode* node = (ObjectDataViewModelNode*)item.GetID();
    if (node->GetType() & itPlate) {
        return;
    }
    node->UpdateExtruderAndColorIcon(extruder);
    if (node->GetType() == itObject)
        UpdateVolumesExtruderBitmap(item, true);
    // BBS
    ItemChanged(item);
}
References Slic3r::GUI::ObjectDataViewModelNode::GetType(), Slic3r::GUI::itObject, Slic3r::GUI::itPlate, Slic3r::GUI::ObjectDataViewModelNode::UpdateExtruderAndColorIcon(), and UpdateVolumesExtruderBitmap().
Referenced by Slic3r::GUI::ObjectList::del_subobject_from_object(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::ObjectList::extruder_editing(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), and Slic3r::GUI::ObjectList::update_filament_values_for_items().
SetName()
bool Slic3r::GUI::ObjectDataViewModel::SetName (const wxString & new_name, wxDataViewItem item)
{
    if (!item.IsOk())
        return false;
    // The icon can't be edited so get its old value and reuse it.
    wxVariant valueOld;
    GetValue(valueOld, item, colName);
    DataViewBitmapText bmpText;
    bmpText << valueOld;
    // But replace the text with the value entered by user.
    bmpText.SetText(new_name);
    wxVariant value;
    value << bmpText;
    if (SetValue(value, item, colName)) {
        ItemChanged(item);
        return true;
    }
    return false;
}
References Slic3r::GUI::colName, GetValue(), DataViewBitmapText::SetText(), and SetValue().
Referenced by Slic3r::GUI::ObjectList::add_volumes_to_object_in_list(), Slic3r::GUI::ObjectList::rename_item(), and Slic3r::GUI::ObjectList::update_name_in_list().
SetObjectPrintableState()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::SetObjectPrintableState (PrintIndicator printable, wxDataViewItem obj_item)
{
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(obj_item.GetID());
    if (!node)
        return wxDataViewItem(0);
    node->set_printable_icon(printable);
    ItemChanged(obj_item);
    UpdateInstancesPrintable(obj_item);
    return obj_item;
}
References Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon(), and UpdateInstancesPrintable().
Referenced by Slic3r::GUI::ObjectList::printable_state_changed(), and Slic3r::GUI::ObjectList::toggle_printable_state().
SetPlateIdx()
void Slic3r::GUI::ObjectDataViewModel::SetPlateIdx (const int plate_idx, wxDataViewItem item)
SetPrintableState()
wxDataViewItem Slic3r::GUI::ObjectDataViewModel::SetPrintableState (PrintIndicator printable, int obj_idx, int subobj_idx = -1, ItemType subobj_type = itInstance)
{
    wxDataViewItem item = wxDataViewItem(0);
    if (subobj_idx < 0)
        item = GetItemById(obj_idx);
    else
        item =  subobj_type&itInstance ? GetItemByInstanceId(obj_idx, subobj_idx) :
                GetItemByVolumeId(obj_idx, subobj_idx);
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node)
        return wxDataViewItem(0);
    node->set_printable_icon(printable);
    ItemChanged(item);
    if (subobj_idx >= 0)
        UpdateObjectPrintable(GetItemById(obj_idx));
    return item;
}
References GetItemById(), GetItemByInstanceId(), GetItemByVolumeId(), Slic3r::GUI::itInstance, Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon(), and UpdateObjectPrintable().
Referenced by Slic3r::GUI::ObjectList::add_object_to_list(), and Slic3r::GUI::ObjectList::update_printable_state().
SetSinkState()
void Slic3r::GUI::ObjectDataViewModel::SetSinkState (const bool painted, wxDataViewItem obj_item)
{
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode *>(obj_item.GetID());
    if (!node) return;
    node->set_sinking_icon(painted);
    ItemChanged(obj_item);
}
References Slic3r::GUI::ObjectDataViewModelNode::set_sinking_icon().
Referenced by Slic3r::GUI::ObjectList::update_info_items().
SetSupportPaintState()
void Slic3r::GUI::ObjectDataViewModel::SetSupportPaintState (const bool painted, wxDataViewItem obj_item)
{
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(obj_item.GetID());
    if (!node)
        return;
    node->set_support_icon(painted);
    ItemChanged(obj_item);
}
References Slic3r::GUI::ObjectDataViewModelNode::set_support_icon().
Referenced by Slic3r::GUI::ObjectList::update_info_items().
SetValue() [1/2]
bool Slic3r::GUI::ObjectDataViewModel::SetValue (const wxVariant & variant, const int item_idx, unsigned int col)
{
    if (size_t(item_idx) >= m_objects.size())
    return false;
  return m_objects[item_idx]->SetValue(variant, col);
}
References col(), and m_objects.
SetValue() [2/2]
bool Slic3r::GUI::ObjectDataViewModel::SetValue (const wxVariant & variant, const wxDataViewItem & item, unsigned int col) override
{
  wxASSERT(item.IsOk());
  ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
  return node->SetValue(variant, col);
}
References col(), and Slic3r::GUI::ObjectDataViewModelNode::SetValue().
Referenced by SetName().
SetVolumeType()
void Slic3r::GUI::ObjectDataViewModel::SetVolumeType (const wxDataViewItem & item, const Slic3r::ModelVolumeType type)
{
    if (!item.IsOk() || GetItemType(item) != itVolume)
        return;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    node->SetVolumeType(volume_type);
    node->SetBitmap(m_volume_bmps[int(volume_type)]);
    if (volume_type != Slic3r::ModelVolumeType::MODEL_PART && volume_type != Slic3r::ModelVolumeType::PARAMETER_MODIFIER)
        node->SetExtruder("");          // hide extruder
    else if (node->GetExtruder().IsEmpty())
        node->SetExtruder("default");   // show extruder ans set it to default
    node->UpdateExtruderAndColorIcon();
    ItemChanged(item);
}
References Slic3r::GUI::ObjectDataViewModelNode::GetExtruder(), GetItemType(), Slic3r::GUI::itVolume, m_volume_bmps, Slic3r::MODEL_PART, Slic3r::PARAMETER_MODIFIER, Slic3r::GUI::ObjectDataViewModelNode::SetBitmap(), Slic3r::GUI::ObjectDataViewModelNode::SetExtruder(), Slic3r::GUI::ObjectDataViewModelNode::SetVolumeType(), and Slic3r::GUI::ObjectDataViewModelNode::UpdateExtruderAndColorIcon().
UpdateBitmapForNode() [1/2]
void Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode (ObjectDataViewModelNode * node) private
{
    bool is_volume_node = node->GetType() & itVolume;
    int  vol_type       = static_cast<int>(node->GetVolumeType());
    is_volume_node &= (vol_type >= int(ModelVolumeType::MODEL_PART) && vol_type <= int(ModelVolumeType::SUPPORT_ENFORCER));
    if (!node->has_warning_icon() && !node->has_lock()) {
        node->SetBitmap(is_volume_node ? m_volume_bmps.at(vol_type) : m_empty_bmp);
        return;
    }
    std::string scaled_bitmap_name = std::string();
    if (node->has_warning_icon())
        scaled_bitmap_name += node->warning_icon_name();
    if (node->has_lock())
        scaled_bitmap_name += LockIcon;
    if (is_volume_node)
        scaled_bitmap_name += std::to_string(vol_type);
    wxBitmap *bmp = m_bitmap_cache->find(scaled_bitmap_name);
    if (!bmp) {
        std::vector<wxBitmap> bmps;
        if (node->has_warning_icon())
            bmps.emplace_back(node->warning_icon_name() == WarningIcon ? m_warning_bmp : m_warning_manifold_bmp);
        if (node->has_lock())
            bmps.emplace_back(m_lock_bmp);
        if (is_volume_node)
            bmps.emplace_back(m_volume_bmps[vol_type]);
        bmp = m_bitmap_cache->insert(scaled_bitmap_name, bmps);
    }
    node->SetBitmap(*bmp);
}
References Slic3r::GUI::BitmapCache::find(), Slic3r::GUI::ObjectDataViewModelNode::GetType(), Slic3r::GUI::ObjectDataViewModelNode::GetVolumeType(), Slic3r::GUI::ObjectDataViewModelNode::has_lock(), Slic3r::GUI::ObjectDataViewModelNode::has_warning_icon(), Slic3r::GUI::BitmapCache::insert(), int, Slic3r::GUI::itVolume, Slic3r::GUI::LockIcon, Slic3r::GUI::m_bitmap_cache, m_empty_bmp, m_lock_bmp, m_volume_bmps, m_warning_bmp, m_warning_manifold_bmp, Slic3r::MODEL_PART, Slic3r::GUI::ObjectDataViewModelNode::SetBitmap(), Slic3r::SUPPORT_ENFORCER, Slic3r::GUI::ObjectDataViewModelNode::warning_icon_name(), and Slic3r::GUI::WarningIcon.
Referenced by AddObject(), UpdateBitmapForNode(), and UpdateCutObjectIcon().
UpdateBitmapForNode() [2/2]
void Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode (ObjectDataViewModelNode * node, bool has_lock) private
{
    node->SetLock(has_lock);
    UpdateBitmapForNode(node);
}
References Slic3r::GUI::ObjectDataViewModelNode::SetLock(), and UpdateBitmapForNode().
UpdateColumValues()
bool Slic3r::GUI::ObjectDataViewModel::UpdateColumValues (unsigned col)
{
    switch (col)
    {
    case colPrint:
    case colName:
    case colEditing:
        return true;
    case colFilament:
    {
        wxDataViewItemArray items;
        GetAllChildren(wxDataViewItem(nullptr), items);
        if (items.IsEmpty()) return false;
        for (auto item : items)
            UpdateExtruderBitmap(item);
        return true;
    }
    default:
        printf("MyObjectTreeModel::SetValue: wrong column");
    }
    return false;
}
References col(), Slic3r::GUI::colEditing, Slic3r::GUI::colFilament, Slic3r::GUI::colName, Slic3r::GUI::colPrint, GetAllChildren(), and UpdateExtruderBitmap().
Referenced by Slic3r::GUI::ObjectList::update_filament_colors().
UpdateCutObjectIcon()
void Slic3r::GUI::ObjectDataViewModel::UpdateCutObjectIcon (const wxDataViewItem & item, bool has_cut_icon)
{
    if (!item.IsOk())
        return;
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (node->has_lock() == has_lock)
        return;
    node->SetLock(has_lock);
    UpdateBitmapForNode(node);
    if (node->GetType() & itObject) {
        wxDataViewItemArray children;
        GetChildren(item, children);
        for (const wxDataViewItem &child : children)
            UpdateCutObjectIcon(child, has_lock);
    }
    ItemChanged(item);
}
References GetChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetType(), Slic3r::GUI::ObjectDataViewModelNode::has_lock(), Slic3r::GUI::itObject, Slic3r::GUI::ObjectDataViewModelNode::SetLock(), UpdateBitmapForNode(), and UpdateCutObjectIcon().
Referenced by Slic3r::GUI::ObjectList::update_lock_icons_for_model(), and UpdateCutObjectIcon().
UpdateExtruderBitmap()
void Slic3r::GUI::ObjectDataViewModel::UpdateExtruderBitmap (wxDataViewItem item)
{
    if (!item.IsOk())
        return;
    ObjectDataViewModelNode* node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    node->UpdateExtruderAndColorIcon();
}
References Slic3r::GUI::ObjectDataViewModelNode::UpdateExtruderAndColorIcon().
Referenced by UpdateColumValues().
UpdateInstancesPrintable()
void Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable (wxDataViewItem parent_item)
{
    const wxDataViewItem inst_root_item = GetInstanceRootItem(parent_item);
    if (!inst_root_item)
        return;
    ObjectDataViewModelNode* obj_node = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    const PrintIndicator obj_pi = obj_node->IsPrintable();
    ObjectDataViewModelNode* inst_root_node = static_cast<ObjectDataViewModelNode*>(inst_root_item.GetID());
    const size_t child_cnt = inst_root_node->GetChildren().Count();
    for (size_t i=0; i < child_cnt; i++)
    {
        ObjectDataViewModelNode* inst_node = inst_root_node->GetNthChild(i);
        // and set printable state for object_node to piUndef
        inst_node->set_printable_icon(obj_pi);
        ItemChanged(wxDataViewItem((void*)inst_node));
    }
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), GetInstanceRootItem(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::ObjectDataViewModelNode::IsPrintable(), and Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon().
Referenced by SetObjectPrintableState().
UpdateItemNames()
void Slic3r::GUI::ObjectDataViewModel::UpdateItemNames ()
{
    wxDataViewItemArray changed_items;
    for (auto obj_node : m_objects) {
        ModelObject* mo = obj_node->m_model_object;
        wxString new_obj_name = from_u8(mo->name);
        if (obj_node->m_name != new_obj_name) {
            obj_node->m_name = new_obj_name;
            changed_items.push_back(wxDataViewItem(obj_node));
        }
        for (auto child_node : obj_node->GetChildren()) {
            if ((child_node->GetType() & itVolume) == 0)
                continue;
            assert(child_node->GetIdx() < mo->volumes.size());
            ModelVolume* mv = mo->volumes[child_node->GetIdx()];
            wxString new_vol_name = from_u8(mv->name);
            if (child_node->m_name != new_vol_name) {
                child_node->m_name = new_vol_name;
                changed_items.push_back(wxDataViewItem(child_node));
            }
        }
    }
    ItemsChanged(changed_items);
}
References Slic3r::GUI::from_u8(), Slic3r::GUI::itVolume, m_objects, Slic3r::ModelObject::name, Slic3r::ModelVolume::name, and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::ObjectList::update_name_for_items().
UpdateObjectPrintable()
void Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable (wxDataViewItem parent_item)
{
    const wxDataViewItem inst_root_item = GetInstanceRootItem(parent_item);
    if (!inst_root_item)
        return;
    ObjectDataViewModelNode* inst_root_node = static_cast<ObjectDataViewModelNode*>(inst_root_item.GetID());
    const size_t child_cnt = inst_root_node->GetChildren().Count();
    PrintIndicator obj_pi = piUnprintable;
    for (size_t i=0; i < child_cnt; i++)
        if (inst_root_node->GetNthChild(i)->IsPrintable() & piPrintable) {
            obj_pi = piPrintable;
            break;
        }
    // and set printable state for object_node to piUndef
    ObjectDataViewModelNode* obj_node = static_cast<ObjectDataViewModelNode*>(parent_item.GetID());
    obj_node->set_printable_icon(obj_pi);
    ItemChanged(parent_item);
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), GetInstanceRootItem(), Slic3r::GUI::ObjectDataViewModelNode::GetNthChild(), Slic3r::GUI::ObjectDataViewModelNode::IsPrintable(), Slic3r::GUI::piPrintable, Slic3r::GUI::piUnprintable, and Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon().
Referenced by AddInstanceChild(), Delete(), DeleteLastInstance(), and SetPrintableState().
UpdateSettingsDigest()
void Slic3r::GUI::ObjectDataViewModel::UpdateSettingsDigest (const wxDataViewItem & item, const std::vector< std::string > & categories)
{
    if (!item.IsOk()) return;
    ObjectDataViewModelNode *node = static_cast<ObjectDataViewModelNode*>(item.GetID());
    if (!node->update_settings_digest(categories))
        return;
    ItemChanged(item);
}
References Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest().
Referenced by Slic3r::GUI::ObjectList::add_settings_item().
UpdateVolumesExtruderBitmap()
void Slic3r::GUI::ObjectDataViewModel::UpdateVolumesExtruderBitmap (wxDataViewItem object_item, bool use_obj_extruder = false)
{
    if (!obj_item.IsOk() || GetItemType(obj_item) != itObject)
        return;
    ObjectDataViewModelNode* obj_node = static_cast<ObjectDataViewModelNode*>(obj_item.GetID());
    for (auto child : obj_node->GetChildren())
        if (child->GetVolumeType() == ModelVolumeType::MODEL_PART)
            child->UpdateExtruderAndColorIcon(use_obj_extruder ? obj_node->GetExtruder() : "");
}
References Slic3r::GUI::ObjectDataViewModelNode::GetChildren(), Slic3r::GUI::ObjectDataViewModelNode::GetExtruder(), GetItemType(), Slic3r::GUI::itObject, Slic3r::MODEL_PART, and Slic3r::GUI::ObjectDataViewModelNode::UpdateExtruderAndColorIcon().
Referenced by Slic3r::GUI::ObjectList::ItemValueChanged(), and SetExtruder().
UpdateWarningIcon()
void Slic3r::GUI::ObjectDataViewModel::UpdateWarningIcon (const wxDataViewItem & item, const std::string & warning_name)
{
    if (warning_icon_name.empty())
        DeleteWarningIcon(item, true);
    else
        AddWarningIcon(item, warning_icon_name);
}
References AddWarningIcon(), and DeleteWarningIcon().
Referenced by Slic3r::GUI::ObjectList::del_subobject_item(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), and Slic3r::GUI::ObjectList::update_item_error_icon().
Member Data Documentation
m_ctrl
wxDataViewCtrl* Slic3r::GUI::ObjectDataViewModel::m_ctrl { nullptr } private
Referenced by AddAllChildren(), Delete(), and SetAssociatedControl().
m_empty_bmp
wxBitmap Slic3r::GUI::ObjectDataViewModel::m_empty_bmp private
Referenced by GetWarningBitmap(), and UpdateBitmapForNode().
m_info_bmps
std::map<InfoItemType, wxBitmap> Slic3r::GUI::ObjectDataViewModel::m_info_bmps private
Referenced by ObjectDataViewModel(), AddInfoChild(), and Rescale().
m_lock_bmp
wxBitmap Slic3r::GUI::ObjectDataViewModel::m_lock_bmp private
Referenced by ObjectDataViewModel(), Rescale(), and UpdateBitmapForNode().
m_objects
std::vector<ObjectDataViewModelNode*> Slic3r::GUI::ObjectDataViewModel::m_objects private
Referenced by ~ObjectDataViewModel(), AddObject(), AddPlate(), Delete(), GetIdByItem(), GetItemById(), GetItemById(), GetItemByLayerRange(), GetItemByVolumeId(), GetItemInfo(), GetObjectItem(), GetRowByItem(), HasInfoItem(), IsEmpty(), ReorganizeObjects(), ResetAll(), SetValue(), and UpdateItemNames().
m_plate_outside
ObjectDataViewModelNode* Slic3r::GUI::ObjectDataViewModel::m_plate_outside private
Referenced by ObjectDataViewModel(), AddObject(), AddOutsidePlate(), Delete(), OnPlateChange(), and ResetAll().
m_plates
std::vector<ObjectDataViewModelNode*> Slic3r::GUI::ObjectDataViewModel::m_plates private
Referenced by AddObject(), AddPlate(), Delete(), DeletePlate(), GetAllChildren(), GetChildren(), GetItemByPlateId(), OnPlateChange(), and ResetAll().
m_volume_bmps
std::vector<wxBitmap> Slic3r::GUI::ObjectDataViewModel::m_volume_bmps private
Referenced by ObjectDataViewModel(), DeleteWarningIcon(), GetVolumeIcon(), Rescale(), SetVolumeType(), and UpdateBitmapForNode().
m_warning_bmp
wxBitmap Slic3r::GUI::ObjectDataViewModel::m_warning_bmp private
Referenced by ObjectDataViewModel(), GetWarningBitmap(), Rescale(), and UpdateBitmapForNode().
m_warning_manifold_bmp
wxBitmap Slic3r::GUI::ObjectDataViewModel::m_warning_manifold_bmp private
Referenced by ObjectDataViewModel(), GetWarningBitmap(), Rescale(), and UpdateBitmapForNode().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ObjectDataViewModel.hpp
src/slic3r/GUI/ObjectDataViewModel.cpp