OrcaSlicer: TempInput Class Reference
TempInput Class Reference
#include <src/slic3r/GUI/Widgets/TempInput.hpp>
Public Types
enum WarningType { WARNING_TOO_HIGH , WARNING_TOO_LOW , WARNING_UNKNOWN }
Public Member Functions
TempInput ()
TempInput (wxWindow *parent, int type, wxString text, wxString label="", wxString normal_icon="", wxString actice_icon="", const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void Create (wxWindow *parent, wxString text, wxString label="", wxString normal_icon="", wxString actice_icon="", const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
wxString erasePending (wxString &str)
void SetTagTemp (int temp)
void SetTagTemp (wxString temp)
void SetCurrTemp (int temp)
void SetCurrTemp (wxString temp)
bool AllisNum (std::string str)
void SetFinish ()
void Warning (bool warn, WarningType type=WARNING_UNKNOWN)
void SetIconActive ()
void SetIconNormal ()
void SetReadOnly (bool ro)
void SetMaxTemp (int temp)
void SetMinTemp (int temp)
int GetType ()
wxString GetTagTemp ()
wxString GetCurrTemp ()
void SetLabel (const wxString &label)
void SetTextColor (StateColor const &color)
void SetLabelColor (StateColor const &color)
virtual void Rescale ()
virtual bool Enable (bool enable=true) override
virtual void SetMinSize (const wxSize &size) override
wxTextCtrl * GetTextCtrl ()
wxTextCtrl const * GetTextCtrl () const
Public Attributes
wxPopupTransientWindow * wdialog {nullptr}
int temp_type
bool actice = false
Protected Member Functions
virtual void OnEdit ()
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
void DoSetToolTipText (wxString const &tip) override
Private Member Functions
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void messureMiniSize ()
void messureSize ()
void mouseMoved (wxMouseEvent &event)
void mouseWheelMoved (wxMouseEvent &event)
void mouseEnterWindow (wxMouseEvent &event)
void mouseLeaveWindow (wxMouseEvent &event)
void keyPressed (wxKeyEvent &event)
void keyReleased (wxKeyEvent &event)
Private Attributes
bool hover
bool m_read_only {false}
wxSize labelSize
ScalableBitmap normal_icon
ScalableBitmap actice_icon
ScalableBitmap degree_icon
StateColor label_color
StateColor text_color
wxTextCtrl * text_ctrl
wxStaticText * warning_text
int max_temp = 0
int min_temp = 0
bool warning_mode = false
int padding_left = 0
Static Private Attributes
static const int TempInputWidth = 200
static const int TempInputHeight = 50
Detailed Description
Member Enumeration Documentation
WarningType
enum TempInput::WarningType
Enumerator
WARNING_TOO_HIGH
WARNING_TOO_LOW
WARNING_UNKNOWN
                     {
        WARNING_TOO_HIGH,
        WARNING_TOO_LOW,
        WARNING_UNKNOWN,
    };
Constructor & Destructor Documentation
TempInput() [1/2]
TempInput::TempInput ()
    : label_color(std::make_pair(wxColour(0xAC,0xAC,0xAC), (int) StateColor::Disabled),std::make_pair(0x323A3C, (int) StateColor::Normal))
    , text_color(std::make_pair(wxColour(0xAC,0xAC,0xAC), (int) StateColor::Disabled), std::make_pair(0x6B6B6B, (int) StateColor::Normal))
{
    hover  = false;
    radius = 0;
    border_color = StateColor(std::make_pair(*wxWHITE, (int) StateColor::Disabled), std::make_pair(0x009688, (int) StateColor::Focused), std::make_pair(0x009688, (int) StateColor::Hovered),
                 std::make_pair(*wxWHITE, (int) StateColor::Normal));
    background_color = StateColor(std::make_pair(*wxWHITE, (int) StateColor::Disabled), std::make_pair(*wxWHITE, (int) StateColor::Normal));
    SetFont(Label::Body_12);
}
References Label::Body_12, StateColor::Disabled, StateColor::Focused, StateColor::Hovered, and StateColor::Normal.
TempInput() [2/2]
TempInput::TempInput (wxWindow * parent, int type, wxString text, wxString label = "", wxString normal_icon = "", wxString actice_icon = "", const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
    : TempInput()
{
    actice = false;
    temp_type = type;
    Create(parent, text, label, normal_icon, actice_icon, pos, size, style);
}
References actice, actice_icon, Create(), normal_icon, size, style, and temp_type.
Member Function Documentation
AllisNum()
bool TempInput::AllisNum (std::string str)
{
    for (int i = 0; i < str.size(); i++) {
        int tmp = (int) str[i];
        if (tmp >= 48 && tmp <= 57) {
            continue;
        } else {
            return false;
        }
    }
    return true;
}
References int.
Referenced by Create().
Create()
void TempInput::Create (wxWindow * parent, wxString text, wxString label = "", wxString normal_icon = "", wxString actice_icon = "", const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
{
    StaticBox::Create(parent, wxID_ANY, pos, size, style);
    wxWindow::SetLabel(label);
    style &= ~wxALIGN_CENTER_HORIZONTAL;
    state_handler.attach({&label_color, &text_color});
    state_handler.update_binds();
    text_ctrl = new wxTextCtrl(this, wxID_ANY, text, {5, 5}, wxDefaultSize, wxTE_PROCESS_ENTER | wxBORDER_NONE, wxTextValidator(wxFILTER_NUMERIC), wxTextCtrlNameStr);
    text_ctrl->SetBackgroundColour(StateColor::darkModeColorFor(*wxWHITE));
    text_ctrl->SetMaxLength(3);
    state_handler.attach_child(text_ctrl);
    text_ctrl->Bind(wxEVT_SET_FOCUS, [this](auto &e) {
        e.SetId(GetId());
        ProcessEventLocally(e);
        e.Skip();
        if (m_read_only) return;
        // enter input mode
        auto temp = text_ctrl->GetValue();
        if (temp.length() > 0 && temp[0] == (0x5f)) {
            text_ctrl->SetValue(wxEmptyString);
        }
        if (wdialog != nullptr) { wdialog->Dismiss(); }
    });
    text_ctrl->Bind(wxEVT_ENTER_WINDOW, [this](auto &e) {
        if (m_read_only) { SetCursor(wxCURSOR_ARROW); }
    });
    text_ctrl->Bind(wxEVT_KILL_FOCUS, [this](auto &e) {
        e.SetId(GetId());
        ProcessEventLocally(e);
        e.Skip();
        OnEdit();
        auto temp = text_ctrl->GetValue();
        if (temp.ToStdString().empty()) {
            text_ctrl->SetValue(wxString("_"));
            return;
        }
        if (!AllisNum(temp.ToStdString())) return;
        if (max_temp <= 0) return;
       /* auto tempint = std::stoi(temp.ToStdString());
         if ((tempint > max_temp || tempint < min_temp) && !warning_mode) {
             if (tempint > max_temp)
                 Warning(true, WARNING_TOO_HIGH);
             else if (tempint < min_temp)
                 Warning(true, WARNING_TOO_LOW);
             return;
         } else {
             Warning(false);
         }*/
        SetFinish();
    });
    text_ctrl->Bind(wxEVT_TEXT_ENTER, [this](wxCommandEvent &e) {
        OnEdit();
        auto temp = text_ctrl->GetValue();
        if (temp.ToStdString().empty()) return;
        if (!AllisNum(temp.ToStdString())) return;
        if (max_temp <= 0) return;
        auto tempint = std::stoi(temp.ToStdString());
        if (tempint > max_temp) {
            Warning(true, WARNING_TOO_HIGH);
            return;
        } else {
            Warning(false, WARNING_TOO_LOW);
        }
        SetFinish();
        Slic3r::GUI::wxGetApp().GetMainTopWindow()->SetFocus();
    });
    text_ctrl->Bind(wxEVT_RIGHT_DOWN, [this](auto &e) {}); // disable context menu
    text_ctrl->Bind(wxEVT_LEFT_DOWN, [this](auto &e) {
        if (m_read_only) {
            return;
        } else {
            e.Skip();
        }
    });
    text_ctrl->SetFont(Label::Body_13);
    text_ctrl->SetForegroundColour(text_color.colorForStates(StateColor::Normal));
    if (!normal_icon.IsEmpty()) { this->normal_icon = ScalableBitmap(this, normal_icon.ToStdString(), 16); }
    if (!actice_icon.IsEmpty()) { this->actice_icon = ScalableBitmap(this, actice_icon.ToStdString(), 16); }
    this->degree_icon = ScalableBitmap(this, "degree", 16);
    messureSize();
}
References actice_icon, AllisNum(), Label::Body_13, StateColor::colorForStates(), StaticBox::Create(), StateColor::darkModeColorFor(), degree_icon, label_color, m_read_only, max_temp, messureSize(), StateColor::Normal, normal_icon, OnEdit(), SetFinish(), size, style, text_color, text_ctrl, Warning, WARNING_TOO_HIGH, WARNING_TOO_LOW, and wdialog.
Referenced by TempInput().
DoSetSize()
void TempInput::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) protected virtual
{
    wxWindow::DoSetSize(x, y, width, height, sizeFlags);
    if (sizeFlags & wxSIZE_USE_EXISTING) return;
    auto       left = padding_left;
    wxClientDC dc(this);
    if (normal_icon.bmp().IsOk()) {
        wxSize szIcon = normal_icon.GetBmpSize();
        left += szIcon.x;
    }
    // interval
    left += 9;
    // label
    dc.SetFont(::Label::Head_14);
    labelSize = dc.GetMultiLineTextExtent(wxWindow::GetLabel());
    left += labelSize.x;
    // interval
    left += 10;
    // separator
    dc.SetFont(::Label::Body_12);
    auto sepSize = dc.GetMultiLineTextExtent(wxString("/"));
    left += sepSize.x;
    // text text
    auto textSize = text_ctrl->GetTextExtent(wxString("0000"));
    text_ctrl->SetSize(textSize);
    text_ctrl->SetPosition({left, (GetSize().y - text_ctrl->GetSize().y) / 2});
}
References ScalableBitmap::bmp(), Label::Body_12, ScalableBitmap::GetBmpSize(), Label::Head_14, labelSize, normal_icon, padding_left, and text_ctrl.
DoSetToolTipText()
void TempInput::DoSetToolTipText (wxString const & tip) override protected
{
    wxWindow::DoSetToolTipText(tip);
    text_ctrl->SetToolTip(tip);
}
References text_ctrl.
Enable()
bool TempInput::Enable (bool enable = true) override virtual
{
    bool result = wxWindow::Enable(enable);
    if (result) {
        wxCommandEvent e(EVT_ENABLE_CHANGED);
        e.SetEventObject(this);
        GetEventHandler()->ProcessEvent(e);
    }
    return result;
}
Referenced by Slic3r::GUI::StatusBasePanel::reset_temp_misc_control(), Slic3r::GUI::StatusPanel::show_printing_status(), and Slic3r::GUI::StatusPanel::update().
erasePending()
wxString TempInput::erasePending (wxString & str)
{
    wxString tmp   = str;
    int      index = tmp.size() - 1;
    while (index != -1) {
        if (tmp[index] < '0' || tmp[index] > '9') {
            tmp.erase(index, 1);
            index--;
        } else {
            break;
        }
    }
    return tmp;
}
GetCurrTemp()
wxString TempInput::GetCurrTemp () inline
{ return GetLabel(); }
GetTagTemp()
wxString TempInput::GetTagTemp () inline
{ return text_ctrl->GetValue(); }
References text_ctrl.
GetTextCtrl() [1/2]
wxTextCtrl * TempInput::GetTextCtrl () inline
{ return text_ctrl; }
References text_ctrl.
Referenced by Slic3r::GUI::StatusPanel::on_set_bed_temp(), Slic3r::GUI::StatusPanel::on_set_nozzle_temp(), Slic3r::GUI::StatusBasePanel::reset_temp_misc_control(), and Slic3r::GUI::StatusPanel::update().
GetTextCtrl() [2/2]
wxTextCtrl const * TempInput::GetTextCtrl () const inline
{ return text_ctrl; }
References text_ctrl.
GetType()
int TempInput::GetType () inline
{ return temp_type; }
References temp_type.
Referenced by Slic3r::GUI::StatusPanel::StatusPanel().
keyPressed()
void TempInput::keyPressed (wxKeyEvent & event) private
{}
keyReleased()
void TempInput::keyReleased (wxKeyEvent & event) private
{}
messureMiniSize()
void TempInput::messureMiniSize () private
{
    wxSize size = GetMinSize();
    auto width  = 0;
    auto height = 0;
    wxClientDC dc(this);
    if (normal_icon.bmp().IsOk()) {
        wxSize szIcon = normal_icon.GetBmpSize();
        width += szIcon.x;
        height = szIcon.y;
    }
    // interval
    width += 9;
    // label
    dc.SetFont(::Label::Head_14);
    labelSize = dc.GetMultiLineTextExtent(wxWindow::GetLabel());
    width += labelSize.x;
    height = labelSize.y > height ? labelSize.y : height;
    // interval
    width += 10;
    // separator
    dc.SetFont(::Label::Body_12);
    auto sepSize = dc.GetMultiLineTextExtent(wxString("/"));
    width += sepSize.x;
    height = sepSize.y > height ? sepSize.y : height;
    // text text
    auto textSize = text_ctrl->GetTextExtent(wxString("0000"));
    width += textSize.x;
    height = textSize.y > height ? textSize.y : height;
    // flag flag
    auto flagSize = degree_icon.GetBmpSize();
    width += flagSize.x;
    height = flagSize.y > height ? flagSize.y : height;
    if (size.x < width) {
        size.x = width;
    } else {
        padding_left = (size.x - width) / 2;
    }
    if (size.y < height) size.y = height;
    SetSize(size);
}
References ScalableBitmap::bmp(), Label::Body_12, degree_icon, ScalableBitmap::GetBmpSize(), Label::Head_14, labelSize, normal_icon, padding_left, size, and text_ctrl.
Referenced by SetMinSize().
messureSize()
void TempInput::messureSize () private
{
    wxSize size = GetSize();
    auto width  = 0;
    auto height = 0;
    wxClientDC dc(this);
    if (normal_icon.bmp().IsOk()) {
        wxSize szIcon = normal_icon.GetBmpSize();
        width += szIcon.x;
        height = szIcon.y;
    }
    // interval
    width += 9;
    // label
    dc.SetFont(::Label::Head_14);
    labelSize = dc.GetMultiLineTextExtent(wxWindow::GetLabel());
    width += labelSize.x;
    height = labelSize.y > height ? labelSize.y : height;
    // interval
    width += 10;
    // separator
    dc.SetFont(::Label::Body_12);
    auto sepSize = dc.GetMultiLineTextExtent(wxString("/"));
    width += sepSize.x;
    height = sepSize.y > height ? sepSize.y : height;
    // text text
    auto textSize = text_ctrl->GetTextExtent(wxString("0000"));
    width += textSize.x;
    height = textSize.y > height ? textSize.y : height;
    // flag flag
    auto flagSize = degree_icon.GetBmpSize();
    width += flagSize.x;
    height = flagSize.y > height ? flagSize.y : height;
    if (size.x < width) {
        size.x = width;
    } else {
        padding_left = (size.x - width) / 2;
    }
    if (size.y < height) size.y = height;
    wxSize minSize = size;
    minSize.x      = GetMinWidth();
    SetMinSize(minSize);
    SetSize(size);
}
References ScalableBitmap::bmp(), Label::Body_12, degree_icon, ScalableBitmap::GetBmpSize(), Label::Head_14, labelSize, normal_icon, padding_left, SetMinSize(), size, and text_ctrl.
Referenced by Create(), Rescale(), SetLabel(), SetTagTemp(), and SetTagTemp().
mouseEnterWindow()
void TempInput::mouseEnterWindow (wxMouseEvent & event) private
{
    if (!hover) {
        hover = true;
        Refresh();
    }
}
References hover.
mouseLeaveWindow()
void TempInput::mouseLeaveWindow (wxMouseEvent & event) private
{
    if (hover) {
        hover = false;
        Refresh();
    }
}
References hover.
mouseMoved()
void TempInput::mouseMoved (wxMouseEvent & event) private
{}
mouseWheelMoved()
void TempInput::mouseWheelMoved (wxMouseEvent & event) private
{}
OnEdit()
virtual void TempInput::OnEdit () inline protected virtual
{}
Referenced by Create().
paintEvent()
void TempInput::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    render(dc);
}
References render().
render()
void TempInput::render (wxDC & dc) private
{
    StaticBox::render(dc);
    int    states      = state_handler.states();
    wxSize size        = GetSize();
    bool   align_right = GetWindowStyle() & wxRIGHT;
    if (warning_mode) {
        border_color = wxColour(255, 111, 0);
    } else {
        border_color = StateColor(std::make_pair(*wxWHITE, (int) StateColor::Disabled), std::make_pair(0x009688, (int) StateColor::Focused),
                                  std::make_pair(0x009688, (int) StateColor::Hovered), std::make_pair(*wxWHITE, (int) StateColor::Normal));
    }
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    // start draw
    wxPoint pt = {padding_left, 0};
    if (actice_icon.bmp().IsOk() && actice) {
        wxSize szIcon = actice_icon.GetBmpSize();
        pt.y          = (size.y - szIcon.y) / 2;
        dc.DrawBitmap(actice_icon.bmp(), pt);
        pt.x += szIcon.x + 9;
    } else {
        actice = false;
    }
    if (normal_icon.bmp().IsOk() && !actice) {
        wxSize szIcon = normal_icon.GetBmpSize();
        pt.y          = (size.y - szIcon.y) / 2;
        dc.DrawBitmap(normal_icon.bmp(), pt);
        pt.x += szIcon.x + 9;
    }
    // label
    auto text = wxWindow::GetLabel();
    dc.SetFont(::Label::Head_14);
    labelSize = dc.GetMultiLineTextExtent(wxWindow::GetLabel());
    if (!IsEnabled()) {
        dc.SetTextForeground(wxColour(0xAC, 0xAC, 0xAC));
        dc.SetTextBackground(background_color.colorForStates((int) StateColor::Disabled));
    }
    else {
        dc.SetTextForeground(wxColour(0x32, 0x3A, 0x3D));
        dc.SetTextBackground(background_color.colorForStates((int) states));
    }
    /*if (!text.IsEmpty()) {
    }*/
    wxSize textSize = text_ctrl->GetSize();
    if (align_right) {
        if (pt.x + labelSize.x > size.x) text = wxControl::Ellipsize(text, dc, wxELLIPSIZE_END, size.x - pt.x);
        pt.y = (size.y - labelSize.y) / 2;
    } else {
        pt.y = (size.y - labelSize.y) / 2;
    }
    dc.SetTextForeground(StateColor::darkModeColorFor("#323A3C"));
    dc.DrawText(text, pt);
    // separator
    dc.SetFont(::Label::Body_12);
    auto sepSize = dc.GetMultiLineTextExtent(wxString("/"));
    dc.SetTextForeground(text_color.colorForStates(states));
    dc.SetTextBackground(background_color.colorForStates(states));
    pt.x += labelSize.x + 10;
    pt.y = (size.y - sepSize.y) / 2;
    dc.DrawText(wxString("/"), pt);
    // flag
    if (degree_icon.bmp().IsOk()) {
        auto   pos    = text_ctrl->GetPosition();
        wxSize szIcon = degree_icon.GetBmpSize();
        pt.y          = (size.y - szIcon.y) / 2;
        pt.x          = pos.x + text_ctrl->GetSize().x;
        dc.DrawBitmap(degree_icon.bmp(), pt);
    }
}
References actice, actice_icon, ScalableBitmap::bmp(), Label::Body_12, StateColor::colorForStates(), StateColor::darkModeColorFor(), degree_icon, StateColor::Disabled, StateColor::Focused, ScalableBitmap::GetBmpSize(), Label::Head_14, StateColor::Hovered, labelSize, StateColor::Normal, normal_icon, padding_left, StaticBox::render(), size, text_color, text_ctrl, and warning_mode.
Referenced by paintEvent().
Rescale()
void TempInput::Rescale () virtual
{
    if (this->normal_icon.bmp().IsOk()) this->normal_icon.msw_rescale();
    if (this->degree_icon.bmp().IsOk()) this->degree_icon.msw_rescale();
    messureSize();
}
References ScalableBitmap::bmp(), degree_icon, messureSize(), ScalableBitmap::msw_rescale(), and normal_icon.
Referenced by Slic3r::GUI::StatusPanel::msw_rescale().
SetCurrTemp() [1/2]
void TempInput::SetCurrTemp (int temp)
{
    SetLabel(wxString::Format("%d", temp));
}
References SetLabel().
Referenced by Slic3r::GUI::StatusPanel::update_temp_ctrl().
SetCurrTemp() [2/2]
void TempInput::SetCurrTemp (wxString temp)
{
    SetLabel(temp);
}
References SetLabel().
SetFinish()
void TempInput::SetFinish ()
{
    wxCommandEvent event(wxCUSTOMEVT_SET_TEMP_FINISH);
    event.SetInt(temp_type);
    wxPostEvent(this->GetParent(), event);
}
References temp_type.
Referenced by Create().
SetIconActive()
void TempInput::SetIconActive ()
{
    actice = true;
    Refresh();
}
References actice.
Referenced by Slic3r::GUI::StatusPanel::update_temp_ctrl().
SetIconNormal()
void TempInput::SetIconNormal ()
{
    actice = false;
    Refresh();
}
References actice.
Referenced by Slic3r::GUI::StatusPanel::update_temp_ctrl().
SetLabel()
void TempInput::SetLabel (const wxString & label)
{
    wxWindow::SetLabel(label);
    messureSize();
    Refresh();
}
References messureSize().
Referenced by Slic3r::GUI::StatusBasePanel::reset_temp_misc_control(), SetCurrTemp(), SetCurrTemp(), and Slic3r::GUI::StatusPanel::update().
SetLabelColor()
void TempInput::SetLabelColor (StateColor const & color)
{
    label_color = color;
    state_handler.update_binds();
}
References label_color.
SetMaxTemp()
void TempInput::SetMaxTemp (int temp)
{ max_temp = temp; }
References max_temp.
Referenced by Slic3r::GUI::StatusBasePanel::create_temp_control(), and Slic3r::GUI::StatusPanel::update_temp_ctrl().
SetMinSize()
void TempInput::SetMinSize (const wxSize & size) override virtual
{
    wxSize size2 = size;
    if (size2.y < 0) {
#ifdef __WXMAC__
        if (GetPeer()) // peer is not ready in Create on mac
#endif
            size2.y = GetSize().y;
    }
    wxWindow::SetMinSize(size2);
    messureMiniSize();
}
References messureMiniSize(), and size.
Referenced by Slic3r::GUI::StatusBasePanel::create_temp_control(), messureSize(), and Slic3r::GUI::StatusPanel::msw_rescale().
SetMinTemp()
void TempInput::SetMinTemp (int temp)
{ min_temp = temp; }
References min_temp.
Referenced by Slic3r::GUI::StatusBasePanel::create_temp_control().
SetReadOnly()
void TempInput::SetReadOnly (bool ro) inline
{ m_read_only = ro; }
References m_read_only.
Referenced by Slic3r::GUI::StatusBasePanel::create_temp_control().
SetTagTemp() [1/2]
void TempInput::SetTagTemp (int temp)
{
    text_ctrl->SetValue(wxString::Format("%d", temp));
    messureSize();
    Refresh();
}
References messureSize(), and text_ctrl.
Referenced by Slic3r::GUI::StatusPanel::on_set_bed_temp(), and Slic3r::GUI::StatusPanel::update_temp_ctrl().
SetTagTemp() [2/2]
void TempInput::SetTagTemp (wxString temp)
{
    text_ctrl->SetValue(temp);
    messureSize();
    Refresh();
}
References messureSize(), and text_ctrl.
SetTextColor()
void TempInput::SetTextColor (StateColor const & color)
{
    text_color = color;
    state_handler.update_binds();
}
References text_color.
Referenced by Slic3r::GUI::StatusBasePanel::create_temp_control().
Warning()
void TempInput::Warning (bool warn, WarningType type = WARNING_UNKNOWN)
{
    warning_mode = warn;
    //Refresh();
    if (warning_mode) {
        if (wdialog == nullptr) {
            wdialog = new PopupWindow(this);
            wdialog->SetBackgroundColour(wxColour(0xFFFFFF));
            wdialog->SetSizeHints(wxDefaultSize, wxDefaultSize);
            wxBoxSizer *sizer_body = new wxBoxSizer(wxVERTICAL);
            auto body = new wxPanel(wdialog, wxID_ANY, wxDefaultPosition, {this->GetSize().x - 4, -1}, wxTAB_TRAVERSAL);
            body->SetBackgroundColour(wxColour(0xFFFFFF));
            wxBoxSizer *sizer_text;
            sizer_text = new wxBoxSizer(wxHORIZONTAL);
            warning_text = new wxStaticText(body, wxID_ANY,
                                            wxEmptyString,
                                            wxDefaultPosition, wxDefaultSize,
                                            wxALIGN_CENTER_HORIZONTAL);
            warning_text->SetFont(::Label::Body_12);
            warning_text->SetForegroundColour(wxColour(255, 111, 0));
            warning_text->Wrap(-1);
            sizer_text->Add(warning_text, 1, wxEXPAND | wxTOP | wxBOTTOM, 2);
            body->SetSizer(sizer_text);
            body->Layout();
            sizer_body->Add(body, 0, wxEXPAND, 0);
            wdialog->SetSizer(sizer_body);
            wdialog->Layout();
            sizer_body->Fit(wdialog);
        }
        wxPoint pos = this->ClientToScreen(wxPoint(2, 0));
        pos.y += this->GetRect().height - (this->GetSize().y - this->text_ctrl->GetSize().y) / 2 - 2;
        wdialog->SetPosition(pos);
        wxString warning_string;
        if (type == WarningType::WARNING_TOO_HIGH)
             warning_string = _L("The maximum temperature cannot exceed" + wxString::Format("%d", max_temp));
        else if (type == WarningType::WARNING_TOO_LOW)
             warning_string = _L("The minmum temperature should not be less than " + wxString::Format("%d", max_temp));
        warning_text->SetLabel(warning_string);
        wdialog->Popup();
    } else {
        if (wdialog)
            wdialog->Dismiss();
    }
}
References _L, Label::Body_12, max_temp, text_ctrl, warning_mode, warning_text, WARNING_TOO_HIGH, WARNING_TOO_LOW, wdialog, and wxStaticText.
Member Data Documentation
actice
bool TempInput::actice = false
Referenced by TempInput(), render(), SetIconActive(), and SetIconNormal().
actice_icon
ScalableBitmap TempInput::actice_icon private
Referenced by TempInput(), Create(), and render().
degree_icon
ScalableBitmap TempInput::degree_icon private
Referenced by Create(), messureMiniSize(), messureSize(), render(), and Rescale().
hover
bool TempInput::hover private
Referenced by mouseEnterWindow(), and mouseLeaveWindow().
label_color
StateColor TempInput::label_color private
Referenced by Create(), and SetLabelColor().
labelSize
wxSize TempInput::labelSize private
Referenced by DoSetSize(), messureMiniSize(), messureSize(), and render().
m_read_only
bool TempInput::m_read_only {false} private
Referenced by Create(), and SetReadOnly().
max_temp
int TempInput::max_temp = 0 private
Referenced by Create(), SetMaxTemp(), and Warning().
min_temp
int TempInput::min_temp = 0 private
Referenced by SetMinTemp().
normal_icon
ScalableBitmap TempInput::normal_icon private
Referenced by TempInput(), Create(), DoSetSize(), messureMiniSize(), messureSize(), render(), and Rescale().
padding_left
int TempInput::padding_left = 0 private
Referenced by DoSetSize(), messureMiniSize(), messureSize(), and render().
temp_type
int TempInput::temp_type
Referenced by TempInput(), GetType(), and SetFinish().
TempInputHeight
const int TempInput::TempInputHeight = 50 static private
TempInputWidth
const int TempInput::TempInputWidth = 200 static private
text_color
StateColor TempInput::text_color private
Referenced by Create(), render(), and SetTextColor().
text_ctrl
wxTextCtrl* TempInput::text_ctrl private
Referenced by Create(), DoSetSize(), DoSetToolTipText(), GetTagTemp(), GetTextCtrl(), GetTextCtrl(), messureMiniSize(), messureSize(), render(), SetTagTemp(), SetTagTemp(), and Warning().
warning_mode
bool TempInput::warning_mode = false private
Referenced by render(), and Warning().
warning_text
wxStaticText* TempInput::warning_text private
Referenced by Warning().
wdialog
wxPopupTransientWindow* TempInput::wdialog {nullptr}
Referenced by Create(), and Warning().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/TempInput.hpp
src/slic3r/GUI/Widgets/TempInput.cpp