OrcaSlicer: Slic3r::GUI::FanControlPopup Class Reference
Slic3r::GUI::FanControlPopup Class Reference
#include <src/slic3r/GUI/Widgets/FanControl.hpp>
Public Member Functions
FanControlPopup (wxWindow *parent)
~FanControlPopup ()
void update_show_mode (bool support_cham_fun)
void update_fan_data (MachineObject::FanType type, MachineObject *obj)
void on_left_down (wxMouseEvent &evt)
void paintEvent (wxPaintEvent &evt)
void post_event (int fan_type, wxString speed)
void on_show (wxShowEvent &evt)
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Private Attributes
wxBoxSizer * m_sizer_main
FanControl * m_part_fan
FanControl * m_aux_fan
FanControl * m_cham_fan
wxWindow * m_line_top
wxWindow * m_line_bottom
bool m_is_suppt_cham_fun {true}
Detailed Description
Constructor & Destructor Documentation
FanControlPopup()
Slic3r::GUI::FanControlPopup::FanControlPopup (wxWindow * parent)
    :PopupWindow(parent, wxBORDER_NONE)
{
    this->SetSizeHints(wxDefaultSize, wxDefaultSize);
    m_sizer_main = new wxBoxSizer(wxVERTICAL);
    m_part_fan = new FanControl(this, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    m_part_fan->set_type(MachineObject::FanType::COOLING_FAN);
    m_part_fan->set_name(_L("Part"));
    m_aux_fan = new FanControl(this, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    m_aux_fan->set_type(MachineObject::FanType::BIG_COOLING_FAN);
    m_aux_fan->set_name(_L("Aux"));
    m_cham_fan = new FanControl(this, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    m_cham_fan->set_type(MachineObject::FanType::CHAMBER_FAN);
    m_cham_fan->set_name(_L("Cham"));
    m_line_top = new wxWindow(this, wxID_ANY);
    m_line_top->SetSize(wxSize(-1, 1));
    m_line_top->SetBackgroundColour(0xF1F1F1);
    m_line_bottom = new wxWindow(this, wxID_ANY);
    m_line_bottom->SetSize(wxSize(-1, 1));
    m_line_bottom->SetBackgroundColour(0xF1F1F1);
    m_sizer_main->Add(m_part_fan, 0, wxALL, FromDIP(14));
    m_sizer_main->Add(m_line_top, 0, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(8));
    m_sizer_main->Add(m_aux_fan, 0, wxALL, FromDIP(14));
    m_sizer_main->Add(m_line_bottom, 0, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(8));
    m_sizer_main->Add(m_cham_fan, 0, wxALL, FromDIP(14));
    this->SetSizer(m_sizer_main);
    this->Layout();
    m_sizer_main->Fit(this);
    this->Centre(wxBOTH);
    Bind(wxEVT_PAINT, &FanControlPopup::paintEvent, this);
#if __APPLE__
    Bind(wxEVT_LEFT_DOWN, &FanControlPopup::on_left_down, this);
#endif
#ifdef __WXOSX__
    Bind(wxEVT_IDLE, [](wxIdleEvent& evt) {});
#endif
    Bind(wxEVT_SHOW, &FanControlPopup::on_show, this);
    SetBackgroundColour(*wxWHITE);
}
References _L, Slic3r::MachineObject::BIG_COOLING_FAN, Slic3r::MachineObject::CHAMBER_FAN, Slic3r::MachineObject::COOLING_FAN, m_aux_fan, m_cham_fan, m_line_bottom, m_line_top, m_part_fan, m_sizer_main, on_left_down(), on_show(), paintEvent(), Slic3r::GUI::FanControl::set_name(), and Slic3r::GUI::FanControl::set_type().
~FanControlPopup()
Slic3r::GUI::FanControlPopup::~FanControlPopup () inline
{};
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
on_left_down()
void Slic3r::GUI::FanControlPopup::on_left_down (wxMouseEvent & evt)
{
    auto mouse_pos = ClientToScreen(evt.GetPosition());
    auto win_pos =  m_part_fan->m_switch_button->ClientToScreen(wxPoint(0, 0));
    auto size =  m_part_fan->m_switch_button->GetSize();
    if (mouse_pos.x > win_pos.x && mouse_pos.x < (win_pos.x +  m_part_fan->m_switch_button->GetSize().x) && mouse_pos.y > win_pos.y && mouse_pos.y < (win_pos.y +  m_part_fan->m_switch_button->GetSize().y)) {
        m_part_fan->on_swith_fan(evt);
    }
    win_pos =  m_aux_fan->m_switch_button->ClientToScreen(wxPoint(0, 0));
    size =  m_aux_fan->m_switch_button->GetSize();
    if (mouse_pos.x > win_pos.x && mouse_pos.x < (win_pos.x +  m_aux_fan->m_switch_button->GetSize().x) && mouse_pos.y > win_pos.y && mouse_pos.y < (win_pos.y +  m_aux_fan->m_switch_button->GetSize().y)) {
        m_aux_fan->on_swith_fan(evt);
    }
    win_pos =  m_cham_fan->m_switch_button->ClientToScreen(wxPoint(0, 0));
    size =  m_cham_fan->m_switch_button->GetSize();
    if (mouse_pos.x > win_pos.x && mouse_pos.x < (win_pos.x +  m_cham_fan->m_switch_button->GetSize().x) && mouse_pos.y > win_pos.y && mouse_pos.y < (win_pos.y +  m_cham_fan->m_switch_button->GetSize().y)) {
        m_cham_fan->on_swith_fan(evt);
    }
    auto part_tag_pos = m_part_fan->ScreenToClient(mouse_pos);
    evt.SetPosition(part_tag_pos);
    m_part_fan->on_left_down(evt);
    auto aux_tag_pos = m_aux_fan->ScreenToClient(mouse_pos);
    evt.SetPosition(aux_tag_pos);
    m_aux_fan->on_left_down(evt);
    auto cham_tag_pos = m_cham_fan->ScreenToClient(mouse_pos);
    evt.SetPosition(cham_tag_pos);
    m_cham_fan->on_left_down(evt);
    evt.Skip();
}
References m_aux_fan, m_cham_fan, m_part_fan, Slic3r::GUI::FanControl::m_switch_button, Slic3r::GUI::FanControl::on_left_down(), Slic3r::GUI::FanControl::on_swith_fan(), and size.
Referenced by FanControlPopup().
on_show()
void Slic3r::GUI::FanControlPopup::on_show (wxShowEvent & evt)
{
    wxGetApp().UpdateDarkUIWin(this);
}
Referenced by FanControlPopup().
OnDismiss()
void Slic3r::GUI::FanControlPopup::OnDismiss () virtual
{
    m_part_fan->update_obj_state(false);
    m_aux_fan->update_obj_state(false);
    m_cham_fan->update_obj_state(false);
}
References m_aux_fan, m_cham_fan, m_part_fan, and Slic3r::GUI::FanControl::update_obj_state().
paintEvent()
void Slic3r::GUI::FanControlPopup::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRoundedRectangle(0, 0, GetSize().x, GetSize().y, 0);
}
Referenced by FanControlPopup().
post_event()
void Slic3r::GUI::FanControlPopup::post_event (int fan_type, wxString speed)
{
    wxCommandEvent event(EVT_FAN_CHANGED);
    event.SetInt(fan_type);
    event.SetString(speed);
    event.SetEventObject(GetParent());
    wxPostEvent(GetParent(), event);
    event.Skip();
}
Referenced by update_fan_data().
ProcessLeftDown()
bool Slic3r::GUI::FanControlPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
update_fan_data()
void Slic3r::GUI::FanControlPopup::update_fan_data (MachineObject::FanType type, MachineObject * obj)
{
    m_is_suppt_cham_fun = obj->is_function_supported(PrinterFunction::FUNC_CHAMBER_FAN);
    update_show_mode(m_is_suppt_cham_fun);
    if (type ==  MachineObject::FanType::COOLING_FAN && obj->cooling_fan_speed >= 0) {
        m_part_fan->set_fan_speed(obj->cooling_fan_speed);
    }
    if (type ==  MachineObject::FanType::BIG_COOLING_FAN && obj->big_fan1_speed >= 0) {
        m_aux_fan->set_fan_speed(obj->big_fan1_speed);
    }
    if (type ==  MachineObject::FanType::CHAMBER_FAN && obj->big_fan2_speed >= 0) {
        m_cham_fan->set_fan_speed(obj->big_fan2_speed);
    }
    m_part_fan->set_machine_obj(obj);
    m_aux_fan->set_machine_obj(obj);
    m_cham_fan->set_machine_obj(obj);
    Bind(EVT_FAN_CHANGED, [this](wxCommandEvent& e) {
        post_event(e.GetInt(), e.GetString());
    });
}
References Slic3r::MachineObject::BIG_COOLING_FAN, Slic3r::MachineObject::big_fan1_speed, Slic3r::MachineObject::big_fan2_speed, Slic3r::MachineObject::CHAMBER_FAN, Slic3r::MachineObject::COOLING_FAN, Slic3r::MachineObject::cooling_fan_speed, Slic3r::FUNC_CHAMBER_FAN, Slic3r::MachineObject::is_function_supported(), m_aux_fan, m_cham_fan, m_is_suppt_cham_fun, m_part_fan, post_event(), Slic3r::GUI::FanControl::set_fan_speed(), Slic3r::GUI::FanControl::set_machine_obj(), and update_show_mode().
Referenced by Slic3r::GUI::StatusPanel::update_misc_ctrl().
update_show_mode()
void Slic3r::GUI::FanControlPopup::update_show_mode (bool support_cham_fun)
{
    if (support_cham_fun && !m_is_suppt_cham_fun) {
        m_cham_fan->Show();
        m_line_bottom->Show();
        Layout();
        Fit();
    }
    if (!support_cham_fun && m_is_suppt_cham_fun) {
        m_cham_fan->Hide();
        m_line_bottom->Hide();
        Layout();
        Fit();
    }
    m_is_suppt_cham_fun = support_cham_fun;
}
References m_cham_fan, m_is_suppt_cham_fun, and m_line_bottom.
Referenced by Slic3r::GUI::StatusPanel::on_nozzle_fan_switch(), and update_fan_data().
Member Data Documentation
m_aux_fan
FanControl* Slic3r::GUI::FanControlPopup::m_aux_fan private
Referenced by FanControlPopup(), on_left_down(), OnDismiss(), and update_fan_data().
m_cham_fan
FanControl* Slic3r::GUI::FanControlPopup::m_cham_fan private
Referenced by FanControlPopup(), on_left_down(), OnDismiss(), update_fan_data(), and update_show_mode().
m_is_suppt_cham_fun
bool Slic3r::GUI::FanControlPopup::m_is_suppt_cham_fun {true} private
Referenced by update_fan_data(), and update_show_mode().
m_line_bottom
wxWindow* Slic3r::GUI::FanControlPopup::m_line_bottom private
Referenced by FanControlPopup(), and update_show_mode().
m_line_top
wxWindow* Slic3r::GUI::FanControlPopup::m_line_top private
Referenced by FanControlPopup().
m_part_fan
FanControl* Slic3r::GUI::FanControlPopup::m_part_fan private
Referenced by FanControlPopup(), on_left_down(), OnDismiss(), and update_fan_data().
m_sizer_main
wxBoxSizer* Slic3r::GUI::FanControlPopup::m_sizer_main private
Referenced by FanControlPopup().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/FanControl.hpp
src/slic3r/GUI/Widgets/FanControl.cpp