OrcaSlicer: ImageTransientPopup Class Reference
ImageTransientPopup Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
ImageTransientPopup (wxWindow *parent, bool scrolled, wxBitmap bmp)
virtual ~ImageTransientPopup ()
void SetImage (wxBitmap bmp)
virtual void Popup (wxWindow *focus=NULL) wxOVERRIDE
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
virtual bool Show (bool show=true) wxOVERRIDE
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Private Member Functions
void OnMouse (wxMouseEvent &event)
void OnSize (wxSizeEvent &event)
void OnSetFocus (wxFocusEvent &event)
void OnKillFocus (wxFocusEvent &event)
wxDECLARE_ABSTRACT_CLASS (ImageTransientPopup)
wxDECLARE_EVENT_TABLE ()
Private Attributes
wxScrolledWindow * m_panel
wxStaticBitmap * m_image
Detailed Description
Constructor & Destructor Documentation
ImageTransientPopup()
ImageTransientPopup::ImageTransientPopup (wxWindow * parent, bool scrolled, wxBitmap bmp)
~ImageTransientPopup()
ImageTransientPopup::~ImageTransientPopup () virtual
{
}
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
OnDismiss()
void ImageTransientPopup::OnDismiss () virtual
{
    PopupWindow::OnDismiss();
}
OnKillFocus()
void ImageTransientPopup::OnKillFocus (wxFocusEvent & event) private
{
    event.Skip();
}
OnMouse()
void ImageTransientPopup::OnMouse (wxMouseEvent & event) private
{
    event.Skip();
}
Referenced by wxBEGIN_EVENT_TABLE().
OnSetFocus()
void ImageTransientPopup::OnSetFocus (wxFocusEvent & event) private
{
    event.Skip();
}
OnSize()
void ImageTransientPopup::OnSize (wxSizeEvent & event) private
{
    event.Skip();
}
Popup()
void ImageTransientPopup::Popup (wxWindow * focus = NULL) virtual
{
    PopupWindow::Popup();
}
ProcessLeftDown()
bool ImageTransientPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
SetImage()
void ImageTransientPopup::SetImage (wxBitmap bmp)
{
    m_image->SetBitmap(bmp);
    m_panel->Layout();
}
References m_image, and m_panel.
Show()
bool ImageTransientPopup::Show (bool show = true) virtual
{
    return PopupWindow::Show(show);
}
wxDECLARE_ABSTRACT_CLASS()
ImageTransientPopup::wxDECLARE_ABSTRACT_CLASS (ImageTransientPopup) private
wxDECLARE_EVENT_TABLE()
ImageTransientPopup::wxDECLARE_EVENT_TABLE () private
Member Data Documentation
m_image
wxStaticBitmap* ImageTransientPopup::m_image private
Referenced by SetImage().
m_panel
wxScrolledWindow* ImageTransientPopup::m_panel private
Referenced by SetImage().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp