OrcaSlicer: orgQhull::QhullSet< T > Class Template Reference
orgQhull::QhullSet< T > Class Template Reference
QhullSet<T> – A read-only wrapper to Qhull's collection class, setT. QhullSet is similar to STL's <vector> and Qt's QVector QhullSet is unrelated to STL and Qt's set and map types (e.g., QSet and QMap) T is a Qhull type that defines 'base_type' and getBaseT() (e.g., QhullFacet with base_type 'facetT *' A QhullSet does not own its contents – erase(), clear(), removeFirst(), removeLast(), pop_back(), pop_front(), fromStdList() not defined QhullSetIterator is faster than STL-style iterator/const_iterator Qhull's FOREACHelement_() [qset_r.h] maybe more efficient than QhullSet. It uses a NULL terminator instead of an end pointer. STL requires an end pointer. Derived from QhullLinkedList.h and Qt/core/tools/qlist.h w/o QT_STRICT_ITERATORS.
#include <src/qhull/src/libqhullcpp/QhullSet.h>
Classes
class const_iterator
class iterator
Public Types
Defined here
Workaround for no setT allocator. Used if setT* is NULL
typedef QhullSet< T >::iterator Iterator
typedef QhullSet< T >::const_iterator ConstIterator
Public Member Functions
Conversion
std::vector< T > toStdVector () const
Element access
const T at (countT idx) const
const T back () const
T back ()
const T::base_type * constData () const
end element is NULL
T::base_type * data ()
const T::base_type * data () const
T::base_type * endData ()
const T::base_type * endData () const
const T first () const
T first ()
const T front () const
T front ()
const T last () const
T last ()
const T operator[] (countT idx) const
T operator[] (countT idx)
const T second () const
T second ()
T value (countT idx) const
T value (countT idx, const T &defaultValue) const
iterator
iterator begin ()
const_iterator begin () const
const_iterator constBegin () const
const_iterator constEnd () const
iterator end ()
const_iterator end () const
Search
bool contains (const T &t) const
countT count (const T &t) const
countT indexOf (const T &t) const
countT lastIndexOf (const T &t) const
GetSet
void defineAs (setT *s)
Not type-safe since setT may contain any type.
void forceEmpty ()
setT * getSetT () const
QhullQh * qh () const
setT ** referenceSetT ()
size_t size () const
Protected Member Functions
Element
void ** beginPointer () const
void ** elementPointer (countT idx) const
void ** endPointer () const
Always points to 0.
Private Attributes
Fields –
setT * qh_set
QhullQh * qh_qh
Static Private Attributes
Class objects
static setT s_empty_set
Constructors
QhullSet (const Qhull &q, setT *s)
QhullSet (QhullQh *qqh, setT *s)
QhullSet (const QhullSet< T > &other)
QhullSet< T > & operator= (const QhullSet< T > &other)
~QhullSet ()
QhullSet ()
Disable default constructor. See QhullSetBase.
GetSet – see QhullSetBase for count(), empty(), isEmpty(), size()
bool operator== (const QhullSet< T > &other) const
bool operator!= (const QhullSet< T > &other) const
countT count () const
bool isEmpty () const
static countT count (const setT *set)
static bool isEmpty (const setT *s)
Detailed Description
template<typename T>
class orgQhull::QhullSet< T >
QhullSet<T> – A read-only wrapper to Qhull's collection class, setT. QhullSet is similar to STL's <vector> and Qt's QVector QhullSet is unrelated to STL and Qt's set and map types (e.g., QSet and QMap) T is a Qhull type that defines 'base_type' and getBaseT() (e.g., QhullFacet with base_type 'facetT *' A QhullSet does not own its contents – erase(), clear(), removeFirst(), removeLast(), pop_back(), pop_front(), fromStdList() not defined QhullSetIterator is faster than STL-style iterator/const_iterator Qhull's FOREACHelement_() [qset_r.h] maybe more efficient than QhullSet. It uses a NULL terminator instead of an end pointer. STL requires an end pointer. Derived from QhullLinkedList.h and Qt/core/tools/qlist.h w/o QT_STRICT_ITERATORS.
Member Typedef Documentation
ConstIterator
template<typename T > typedef QhullSet<T>::const_iterator orgQhull::QhullSet< T >::ConstIterator
Iterator
template<typename T > typedef QhullSet<T>::iterator orgQhull::QhullSet< T >::Iterator
Constructor & Destructor Documentation
QhullSet() [1/4]
template<typename T > orgQhull::QhullSet< T >::QhullSet (const Qhull & q, setT * s) inline
: QhullSetBase(q, s) { }
QhullSet() [2/4]
template<typename T > orgQhull::QhullSet< T >::QhullSet (QhullQh * qqh, setT * s) inline
: QhullSetBase(qqh, s) { }
QhullSet() [3/4]
template<typename T > orgQhull::QhullSet< T >::QhullSet (const QhullSet< T > & other) inline
: QhullSetBase(other) {}
~QhullSet()
template<typename T > orgQhull::QhullSet< T >::~QhullSet () inline
{}
QhullSet() [4/4]
template<typename T > orgQhull::QhullSet< T >::QhullSet () private
Disable default constructor. See QhullSetBase.
Member Function Documentation
at()
template<typename T > const T orgQhull::QhullSet< T >::at (countT idx) const inline
{ return operator[](idx); }
References orgQhull::QhullSet< T >::operator[]().
Referenced by orgQhull::QhullPointSet_test::t_element(), and orgQhull::QhullHyperplane_test::t_value().
back() [1/2]
template<typename T > T orgQhull::QhullSet< T >::back () inline
{ return last(); }
References orgQhull::QhullSet< T >::last().
back() [2/2]
template<typename T > const T orgQhull::QhullSet< T >::back () const inline
{ return last(); }
References orgQhull::QhullSet< T >::last().
Referenced by orgQhull::QhullPointSet_test::t_element().
begin() [1/2]
template<typename T > iterator orgQhull::QhullSet< T >::begin () inline
{ return iterator(qh(), reinterpret_cast<typename T::base_type *>(beginPointer())); }
References orgQhull::QhullSetBase::beginPointer(), and orgQhull::QhullSetBase::qh().
Referenced by operator<<(), operator<<(), operator<<(), orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::QhullPointSet_test::t_element(), orgQhull::QhullVertexSet_test::t_foreach(), orgQhull::QhullPointSet_test::t_iterator(), orgQhull::QhullSet_test::t_qhullsetbase(), and orgQhull::QhullFacetList::vertices_toStdVector().
begin() [2/2]
template<typename T > const_iterator orgQhull::QhullSet< T >::begin () const inline
{ return const_iterator(qh(), data()); }
References orgQhull::QhullSet< T >::data(), and orgQhull::QhullSetBase::qh().
beginPointer()
void ** orgQhull::QhullSetBase::beginPointer () const inline protected inherited
{ return &qh_set->e[0].p; }
References setT::e, setelemT::p, and orgQhull::QhullSetBase::qh_set.
Referenced by orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::constData(), orgQhull::QhullSet< T >::data(), and orgQhull::QhullSet< T >::data().
constBegin()
template<typename T > const_iterator orgQhull::QhullSet< T >::constBegin () const inline
{ return const_iterator(qh(), data()); }
References orgQhull::QhullSet< T >::data(), and orgQhull::QhullSetBase::qh().
Referenced by orgQhull::QhullPointSet_test::t_iterator().
constData()
template<typename T > const T::base_type * orgQhull::QhullSet< T >::constData () const inline
end element is NULL
{ return reinterpret_cast<const typename T::base_type *>(beginPointer()); }
References orgQhull::QhullSetBase::beginPointer().
constEnd()
template<typename T > const_iterator orgQhull::QhullSet< T >::constEnd () const inline
{ return const_iterator(qh(), endData()); }
References orgQhull::QhullSet< T >::endData(), and orgQhull::QhullSetBase::qh().
Referenced by orgQhull::QhullPointSet_test::t_iterator().
contains()
template<typename T > bool orgQhull::QhullSet< T >::contains (const T & t) const
{
    setT *s= getSetT();
    void *p= t.getBaseT();  // contains() is not inline for better error reporting
    int result= qh_setin(s, p);
    return result!=0;
}//contains
References qh_setin().
Referenced by orgQhull::QhullFacetSet::contains(), orgQhull::QhullRidge_test::t_foreach(), orgQhull::QhullVertex_test::t_foreach(), orgQhull::QhullVertexSet_test::t_foreach(), orgQhull::QhullVertexSet_test::t_readonly(), and orgQhull::QhullPointSet_test::t_search().
count() [1/3]
template<typename T > countT orgQhull::QhullSetBase::count () const inline
{ return QhullSetBase::count(qh_set); }
Referenced by orgQhull::QhullFacetSet::count(), and orgQhull::QhullFacetSet::count().
count() [2/3]
template<typename T > countT orgQhull::QhullSetBase::count (const setT * set) static
{
    countT size;
    const setelemT *sizep;
    if (!set){
        return(0);
    }
    sizep= SETsizeaddr_(set);
    if ((size= sizep->i)) {
        size--;
        if (size > set->maxsize) {
            // FIXUP QH11022 How to add additional output to a error? -- qh_setprint(qhmem.ferr, "set: ", set);
            throw QhullError(10032, "QhullSet internal error: current set size %d is greater than maximum size %d\n",
                size, set->maxsize);
        }
    }else{
        size= set->maxsize;
    }
    return size;
}//count
count() [3/3]
template<typename T > countT orgQhull::QhullSet< T >::count (const T & t) const
{
    countT n= 0;
    const typename T::base_type *i= data();
    const typename T::base_type *e= endData();
    typename T::base_type p= t.getBaseT();
    while(i<e){
        if(*i==p){
            n++;
        }
        i++;
    }
    return n;
}//count
References n.
Referenced by orgQhull::QhullVertexSet::QhullVertexSet(), orgQhull::QhullVertexSet::operator=(), orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::QhullPointSet_test::t_construct(), orgQhull::QhullVertexSet_test::t_construct(), orgQhull::QhullPointSet_test::t_convert(), orgQhull::QhullSet_test::t_convert(), orgQhull::QhullVertexSet_test::t_convert(), orgQhull::QhullPointSet_test::t_element(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullFacet_test::t_foreach(), orgQhull::QhullRidge_test::t_foreach(), orgQhull::QhullPointSet_test::t_io(), orgQhull::QhullPointSet_test::t_iterator(), orgQhull::QhullPointSet_test::t_pointset_iterator(), orgQhull::QhullSet_test::t_qhullsetbase(), orgQhull::QhullVertexSet_test::t_readonly(), and orgQhull::QhullPointSet_test::t_search().
data() [1/2]
template<typename T > T::base_type * orgQhull::QhullSet< T >::data () inline
{ return reinterpret_cast<typename T::base_type *>(beginPointer()); }
References orgQhull::QhullSetBase::beginPointer().
Referenced by orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::constBegin(), orgQhull::QhullSet< T >::first(), orgQhull::QhullSet< T >::first(), and operator<<().
data() [2/2]
template<typename T > const T::base_type * orgQhull::QhullSet< T >::data () const inline
{ return reinterpret_cast<const typename T::base_type *>(beginPointer()); }
References orgQhull::QhullSetBase::beginPointer().
defineAs()
void orgQhull::QhullSetBase::defineAs (setT * s) inline inherited
Not type-safe since setT may contain any type.
References orgQhull::QhullSetBase::qh_set, and orgQhull::QhullSetBase::s_empty_set.
Referenced by orgQhull::QhullVertexSet::QhullVertexSet(), and orgQhull::QhullVertexSet::QhullVertexSet().
elementPointer()
void ** orgQhull::QhullSetBase::elementPointer (countT idx) const inline protected inherited
{ QHULL_ASSERT(idx>=0 && idx<qh_set->maxsize); return &SETelem_(qh_set, idx); }
References orgQhull::QhullSetBase::qh_set, QHULL_ASSERT, and SETelem_.
Referenced by orgQhull::QhullSet< T >::operator[](), and orgQhull::QhullSet< T >::operator[]().
end() [1/2]
template<typename T > iterator orgQhull::QhullSet< T >::end () inline
{ return iterator(qh(), endData()); }
References orgQhull::QhullSet< T >::endData(), and orgQhull::QhullSetBase::qh().
Referenced by operator<<(), operator<<(), operator<<(), orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::QhullVertexSet_test::t_foreach(), orgQhull::QhullPointSet_test::t_iterator(), orgQhull::QhullSet_test::t_qhullsetbase(), and orgQhull::QhullFacetList::vertices_toStdVector().
end() [2/2]
template<typename T > const_iterator orgQhull::QhullSet< T >::end () const inline
{ return const_iterator(qh(), endData()); }
References orgQhull::QhullSet< T >::endData(), and orgQhull::QhullSetBase::qh().
endData() [1/2]
template<typename T > T::base_type * orgQhull::QhullSet< T >::endData () inline
{ return reinterpret_cast<typename T::base_type *>(endPointer()); }
References orgQhull::QhullSetBase::endPointer().
Referenced by orgQhull::QhullSet< T >::constEnd(), orgQhull::QhullSet< T >::end(), orgQhull::QhullSet< T >::end(), orgQhull::QhullSet< T >::last(), orgQhull::QhullSet< T >::last(), operator<<(), orgQhull::QhullSet< T >::operator[](), and orgQhull::QhullSet< T >::operator[]().
endData() [2/2]
template<typename T > const T::base_type * orgQhull::QhullSet< T >::endData () const inline
{ return reinterpret_cast<const typename T::base_type *>(endPointer()); }
References orgQhull::QhullSetBase::endPointer().
endPointer()
void ** orgQhull::QhullSetBase::endPointer () const inline protected inherited
Always points to 0.
{ return qh_setendpointer(qh_set); }
References orgQhull::QhullSetBase::qh_set, and qh_setendpointer().
Referenced by orgQhull::QhullSet< T >::endData(), and orgQhull::QhullSet< T >::endData().
first() [1/2]
template<typename T > T orgQhull::QhullSet< T >::first () inline
{ QHULL_ASSERT(!isEmpty()); return T(qh(), *data()); }
References orgQhull::QhullSet< T >::data(), orgQhull::QhullSet< T >::isEmpty(), orgQhull::QhullSetBase::qh(), and QHULL_ASSERT.
first() [2/2]
template<typename T > const T orgQhull::QhullSet< T >::first () const inline
{ QHULL_ASSERT(!isEmpty()); return T(qh(), *data()); }
References orgQhull::QhullSet< T >::data(), orgQhull::QhullSet< T >::isEmpty(), orgQhull::QhullSetBase::qh(), and QHULL_ASSERT.
Referenced by orgQhull::QhullSet< T >::front(), orgQhull::QhullSet< T >::front(), orgQhull::QhullRidge_test::t_construct(), orgQhull::QhullPointSet_test::t_element(), orgQhull::QhullFacet_test::t_foreach(), orgQhull::QhullRidge_test::t_foreach(), orgQhull::QhullVertexSet_test::t_foreach(), orgQhull::QhullRidge_test::t_io(), orgQhull::QhullVertexSet_test::t_readonly(), and orgQhull::QhullPointSet_test::t_search().
forceEmpty()
void orgQhull::QhullSetBase::forceEmpty () inline inherited
{ qh_set= &s_empty_set; }
References orgQhull::QhullSetBase::qh_set, and orgQhull::QhullSetBase::s_empty_set.
front() [1/2]
template<typename T > T orgQhull::QhullSet< T >::front () inline
{ return first(); }
References orgQhull::QhullSet< T >::first().
front() [2/2]
template<typename T > const T orgQhull::QhullSet< T >::front () const inline
{ return first(); }
References orgQhull::QhullSet< T >::first().
Referenced by orgQhull::QhullPointSet_test::t_element().
getSetT()
setT * orgQhull::QhullSetBase::getSetT () const inline inherited
{ return qh_set; }
References orgQhull::QhullSetBase::qh_set.
Referenced by orgQhull::QhullSet< T >::indexOf(), orgQhull::QhullSet< T >::operator==(), and orgQhull::QhullSet_test::t_qhullsetbase().
indexOf()
template<typename T > countT orgQhull::QhullSet< T >::indexOf (const T & t) const inline
{ /* no qh_qh */ return qh_setindex(getSetT(), t.getBaseT()); }
References orgQhull::QhullSetBase::getSetT(), and qh_setindex().
Referenced by orgQhull::QhullPointSet_test::t_search().
isEmpty() [1/2]
template<typename T > bool orgQhull::QhullSetBase::isEmpty () const inline
{ return SETempty_(qh_set); }
Referenced by orgQhull::QhullSet< T >::first(), orgQhull::QhullSet< T >::first(), orgQhull::QhullSet< T >::last(), orgQhull::QhullSet< T >::last(), operator<<(), operator<<(), orgQhull::QhullFacetSet_test::t_construct(), orgQhull::QhullPointSet_test::t_construct(), orgQhull::QhullRidge_test::t_construct(), orgQhull::QhullVertexSet_test::t_construct(), and orgQhull::QhullSet_test::t_qhullsetbase().
isEmpty() [2/2]
template<typename T > static bool orgQhull::QhullSetBase::isEmpty (const setT * s) inline static
{ return SETempty_(s); }
last() [1/2]
template<typename T > T orgQhull::QhullSet< T >::last () inline
{ QHULL_ASSERT(!isEmpty()); return T(qh(), *(endData()-1)); }
References orgQhull::QhullSet< T >::endData(), orgQhull::QhullSet< T >::isEmpty(), orgQhull::QhullSetBase::qh(), and QHULL_ASSERT.
last() [2/2]
template<typename T > const T orgQhull::QhullSet< T >::last () const inline
{ QHULL_ASSERT(!isEmpty()); return T(qh(), *(endData()-1)); }
References orgQhull::QhullSet< T >::endData(), orgQhull::QhullSet< T >::isEmpty(), orgQhull::QhullSetBase::qh(), and QHULL_ASSERT.
Referenced by orgQhull::QhullSet< T >::back(), orgQhull::QhullSet< T >::back(), operator<<(), orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::QhullPointSet_test::t_element(), orgQhull::QhullVertexSet_test::t_foreach(), orgQhull::QhullPointSet_test::t_iterator(), orgQhull::QhullPointSet_test::t_pointset_iterator(), orgQhull::QhullVertexSet_test::t_readonly(), and orgQhull::QhullPointSet_test::t_search().
lastIndexOf()
template<typename T > countT orgQhull::QhullSet< T >::lastIndexOf (const T & t) const
{
    const typename T::base_type *b= data();
    const typename T::base_type *i= endData();
    typename T::base_type p= t.getBaseT();
    while(--i>=b){
        if(*i==p){
            break;
        }
    }
    return (countT)(i-b); // WARN64
}//lastIndexOf
Referenced by orgQhull::QhullPointSet_test::t_search().
operator!=()
template<typename T > bool orgQhull::QhullSet< T >::operator!= (const QhullSet< T > & other) const inline
{ return !operator==(other); }
References orgQhull::QhullSet< T >::operator==().
operator=()
template<typename T > QhullSet< T > & orgQhull::QhullSet< T >::operator= (const QhullSet< T > & other) inline
{ QhullSetBase::operator=(other); return *this; }
References orgQhull::QhullSetBase::operator=().
Referenced by orgQhull::QhullFacetSet::operator=(), orgQhull::QhullPointSet::operator=(), and orgQhull::QhullVertexSet::operator=().
operator==()
template<typename T > bool orgQhull::QhullSet< T >::operator== (const QhullSet< T > & other) const inline
{ return qh_setequal(getSetT(), other.getSetT()); }
References orgQhull::QhullSetBase::getSetT(), and qh_setequal().
Referenced by orgQhull::QhullSet< T >::operator!=().
operator[]() [1/2]
template<typename T > T orgQhull::QhullSet< T >::operator[] (countT idx) inline
{ typename T::base_type *p= reinterpret_cast<typename T::base_type *>(elementPointer(idx)); QHULL_ASSERT(idx>=0 && p < endData()); return T(qh(), *p); }
References orgQhull::QhullSetBase::elementPointer(), orgQhull::QhullSet< T >::endData(), orgQhull::QhullSetBase::qh(), and QHULL_ASSERT.
operator[]() [2/2]
template<typename T > const T orgQhull::QhullSet< T >::operator[] (countT idx) const inline
{ const typename T::base_type *p= reinterpret_cast<typename T::base_type *>(elementPointer(idx)); QHULL_ASSERT(idx>=0 && p < endData()); return T(qh(), *p); }
References orgQhull::QhullSetBase::elementPointer(), orgQhull::QhullSet< T >::endData(), orgQhull::QhullSetBase::qh(), and QHULL_ASSERT.
Referenced by orgQhull::QhullSet< T >::at(), orgQhull::QhullSet< T >::second(), and orgQhull::QhullSet< T >::second().
qh()
QhullQh * orgQhull::QhullSetBase::qh () const inline inherited
{ return qh_qh; }
References orgQhull::QhullSetBase::qh_qh.
Referenced by orgQhull::QhullVertexSet::QhullVertexSet(), orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::constBegin(), orgQhull::QhullSet< T >::constEnd(), orgQhull::QhullSet< T >::end(), orgQhull::QhullSet< T >::end(), orgQhull::QhullSet< T >::first(), orgQhull::QhullSet< T >::first(), orgQhull::QhullVertexSet::freeQhSetTemp(), orgQhull::QhullSet< T >::last(), orgQhull::QhullSet< T >::last(), operator<<(), orgQhull::QhullSet< T >::operator[](), and orgQhull::QhullSet< T >::operator[]().
referenceSetT()
setT ** orgQhull::QhullSetBase::referenceSetT () inline inherited
{ return &qh_set; }
References orgQhull::QhullSetBase::qh_set.
Referenced by orgQhull::QhullVertexSet::freeQhSetTemp().
second() [1/2]
template<typename T > T orgQhull::QhullSet< T >::second () inline
{ return operator[](1); }
References orgQhull::QhullSet< T >::operator[]().
second() [2/2]
template<typename T > const T orgQhull::QhullSet< T >::second () const inline
{ return operator[](1); }
References orgQhull::QhullSet< T >::operator[]().
Referenced by orgQhull::QhullPointSet_test::t_element().
size()
size_t orgQhull::QhullSetBase::size () const inline inherited
{ return QhullSetBase::count(qh_set); }
References orgQhull::QhullSetBase::count(), and orgQhull::QhullSetBase::qh_set.
Referenced by orgQhull::QhullSetBase::count(), operator<<(), orgQhull::QhullPointSet_test::t_construct(), orgQhull::QhullPointSet_test::t_convert(), and orgQhull::QhullSet_test::t_qhullsetbase().
toStdVector()
template<typename T > std::vector< T > orgQhull::QhullSet< T >::toStdVector
{
  typename QhullSet<T>::const_iterator i = begin();
  typename QhullSet<T>::const_iterator e = end();
    std::vector<T> vs;
    while(i!=e){
        vs.push_back(*i++);
    }
    return vs;
}//toStdVector
References end.
Referenced by orgQhull::QhullPointSet_test::t_convert(), and orgQhull::QhullSet_test::t_convert().
value() [1/2]
template<typename T > T orgQhull::QhullSet< T >::value (countT idx) const
{
    // Avoid call to qh_setsize() and assert in elementPointer()
    const typename T::base_type *p= reinterpret_cast<const typename T::base_type *>(&SETelem_(getSetT(), idx));
    return (idx>=0 && p<endData()) ? T(qh(), *p) : T(qh());
}//value
References qh, and SETelem_.
Referenced by orgQhull::QhullPointSet_test::t_element().
value() [2/2]
template<typename T > T orgQhull::QhullSet< T >::value (countT idx, const T & defaultValue) const
{
    // Avoid call to qh_setsize() and assert in elementPointer()
    const typename T::base_type *p= reinterpret_cast<const typename T::base_type *>(&SETelem_(getSetT(), idx));
    return (idx>=0 && p<endData() ? T(qh(), *p) : defaultValue);
}//value
References qh, and SETelem_.
Member Data Documentation
qh_qh
QhullQh* orgQhull::QhullSetBase::qh_qh private inherited
Referenced by orgQhull::QhullSetBase::operator=(), and orgQhull::QhullSetBase::qh().
qh_set
setT* orgQhull::QhullSetBase::qh_set private inherited
Referenced by orgQhull::QhullSetBase::beginPointer(), orgQhull::QhullSetBase::count(), orgQhull::QhullSetBase::defineAs(), orgQhull::QhullSetBase::elementPointer(), orgQhull::QhullSetBase::endPointer(), orgQhull::QhullSetBase::forceEmpty(), orgQhull::QhullSetBase::getSetT(), orgQhull::QhullSetBase::isEmpty(), orgQhull::QhullSetBase::operator=(), orgQhull::QhullSetBase::referenceSetT(), and orgQhull::QhullSetBase::size().
s_empty_set
template<typename T > setT orgQhull::QhullSet< T >::s_empty_set static private
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullSet.h