OrcaSlicer: CheckBox Class Reference
CheckBox Class Reference
#include <src/slic3r/GUI/Widgets/CheckBox.hpp>
Public Member Functions
CheckBox (wxWindow *parent, int id=wxID_ANY)
void SetValue (bool value) override
void SetHalfChecked (bool value=true)
void Rescale ()
Private Member Functions
void update ()
Private Attributes
ScalableBitmap m_on
ScalableBitmap m_half
ScalableBitmap m_off
ScalableBitmap m_on_disabled
ScalableBitmap m_half_disabled
ScalableBitmap m_off_disabled
ScalableBitmap m_on_focused
ScalableBitmap m_half_focused
ScalableBitmap m_off_focused
bool m_half_checked = false
Detailed Description
Constructor & Destructor Documentation
CheckBox()
CheckBox::CheckBox (wxWindow * parent, int id = wxID_ANY)
    : wxBitmapToggleButton(parent, id, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE)
    , m_on(this, "check_on", 18)
    , m_half(this, "check_half", 18)
    , m_off(this, "check_off", 18)
    , m_on_disabled(this, "check_on_disabled", 18)
    , m_half_disabled(this, "check_half_disabled", 18)
    , m_off_disabled(this, "check_off_disabled", 18)
    , m_on_focused(this, "check_on_focused", 18)
    , m_half_focused(this, "check_half_focused", 18)
    , m_off_focused(this, "check_off_focused", 18)
{
  //SetBackgroundStyle(wxBG_STYLE_TRANSPARENT);
  if (parent)
    SetBackgroundColour(parent->GetBackgroundColour());
  Bind(wxEVT_TOGGLEBUTTON, [this](auto& e) { m_half_checked = false; update(); e.Skip(); });
#ifdef __WXOSX__ // State not fully implement on MacOS
    Bind(wxEVT_SET_FOCUS, &CheckBox::updateBitmap, this);
    Bind(wxEVT_KILL_FOCUS, &CheckBox::updateBitmap, this);
    Bind(wxEVT_ENTER_WINDOW, &CheckBox::updateBitmap, this);
    Bind(wxEVT_LEAVE_WINDOW, &CheckBox::updateBitmap, this);
#endif
  SetSize(m_on.GetBmpSize());
  SetMinSize(m_on.GetBmpSize());
  update();
}
References ScalableBitmap::GetBmpSize(), m_half_checked, m_on, and update().
Member Function Documentation
Rescale()
void CheckBox::Rescale ()
{
    m_on.msw_rescale();
    m_half.msw_rescale();
    m_off.msw_rescale();
    m_on_disabled.msw_rescale();
    m_half_disabled.msw_rescale();
    m_off_disabled.msw_rescale();
    m_on_focused.msw_rescale();
    m_half_focused.msw_rescale();
    m_off_focused.msw_rescale();
    SetSize(m_on.GetBmpSize());
  update();
}
References ScalableBitmap::GetBmpSize(), m_half, m_half_disabled, m_half_focused, m_off, m_off_disabled, m_off_focused, m_on, m_on_disabled, m_on_focused, ScalableBitmap::msw_rescale(), and update().
SetHalfChecked()
void CheckBox::SetHalfChecked (bool value = true)
{
  m_half_checked = value;
  update();
}
References m_half_checked, and update().
SetValue()
void CheckBox::SetValue (bool value) override
{
  wxBitmapToggleButton::SetValue(value);
  update();
}
References update().
update()
void CheckBox::update () private
{
  SetBitmapLabel((m_half_checked ? m_half : GetValue() ? m_on : m_off).bmp());
    SetBitmapDisabled((m_half_checked ? m_half_disabled : GetValue() ? m_on_disabled : m_off_disabled).bmp());
#ifdef __WXMSW__
    SetBitmapFocus((m_half_checked ? m_half_focused : GetValue() ? m_on_focused : m_off_focused).bmp());
#endif
    SetBitmapCurrent((m_half_checked ? m_half_focused : GetValue() ? m_on_focused : m_off_focused).bmp());
#ifdef __WXOSX__
    wxCommandEvent e(wxEVT_UPDATE_UI);
    updateBitmap(e);
#endif
}
References m_half, m_half_checked, m_half_disabled, m_half_focused, m_off, m_off_disabled, m_off_focused, m_on, m_on_disabled, and m_on_focused.
Referenced by CheckBox(), Rescale(), SetHalfChecked(), and SetValue().
Member Data Documentation
m_half
ScalableBitmap CheckBox::m_half private
Referenced by Rescale(), and update().
m_half_checked
bool CheckBox::m_half_checked = false private
Referenced by CheckBox(), SetHalfChecked(), and update().
m_half_disabled
ScalableBitmap CheckBox::m_half_disabled private
Referenced by Rescale(), and update().
m_half_focused
ScalableBitmap CheckBox::m_half_focused private
Referenced by Rescale(), and update().
m_off
ScalableBitmap CheckBox::m_off private
Referenced by Rescale(), and update().
m_off_disabled
ScalableBitmap CheckBox::m_off_disabled private
Referenced by Rescale(), and update().
m_off_focused
ScalableBitmap CheckBox::m_off_focused private
Referenced by Rescale(), and update().
m_on
ScalableBitmap CheckBox::m_on private
Referenced by CheckBox(), Rescale(), and update().
m_on_disabled
ScalableBitmap CheckBox::m_on_disabled private
Referenced by Rescale(), and update().
m_on_focused
ScalableBitmap CheckBox::m_on_focused private
Referenced by Rescale(), and update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/CheckBox.hpp
src/slic3r/GUI/Widgets/CheckBox.cpp