OrcaSlicer: StateHandler Class Reference
StateHandler Class Reference
#include <src/slic3r/GUI/Widgets/StateHandler.hpp>
Public Types
enum State {
Enabled = 1 , Checked = 2 , Focused = 4 , Hovered = 8 ,
Pressed = 16 , Disabled = 1 << 16 , NotChecked = 2 << 16 , NotFocused = 4 << 16 ,
NotHovered = 8 << 16 , NotPressed = 16 << 16
}
Public Member Functions
StateHandler (wxWindow *owner)
~StateHandler ()
void attach (StateColor const &color)
void attach (std::vector< StateColor const * > const &colors)
void attach_child (wxWindow *child)
void remove_child (wxWindow *child)
void update_binds ()
int states () const
void set_state (int state, int mask)
Private Member Functions
StateHandler (StateHandler *parent, wxWindow *owner)
void changed (wxEvent &event)
void changed (int state2)
Private Attributes
wxWindow * owner_
std::vector< StateColor const * > colors_
int bind_states_ = 0
int states_ = 0
int states2_ = 0
std::vector< std::unique_ptr< StateHandler > > children_
StateHandler * parent_ = nullptr
Detailed Description
Member Enumeration Documentation
State
enum StateHandler::State
Enumerator
Enabled
Checked
Focused
Hovered
Pressed
Disabled
NotChecked
NotFocused
NotHovered
NotPressed
               {
        Enabled = 1,
        Checked = 2,
        Focused = 4,
        Hovered = 8,
        Pressed = 16,
        Disabled = 1 << 16,
        NotChecked = 2 << 16,
        NotFocused = 4 << 16,
        NotHovered = 8 << 16,
        NotPressed = 16 << 16,
    };
Constructor & Destructor Documentation
StateHandler() [1/2]
StateHandler::StateHandler (wxWindow * owner)
    : owner_(owner)
{
    owner_->PushEventHandler(this);
    if (owner->IsEnabled())
        states_ |= Enabled;
    if (owner->HasFocus())
        states_ |= Focused;
}
References Enabled, Focused, owner_, and states_.
~StateHandler()
StateHandler::~StateHandler ()
{ owner_->RemoveEventHandler(this); }
References owner_.
StateHandler() [2/2]
StateHandler::StateHandler (StateHandler * parent, wxWindow * owner) private
    : StateHandler(owner)
{
    states_ &= ~Enabled;
    parent_ = parent;
}
References parent_, and states_.
Member Function Documentation
attach() [1/2]
void StateHandler::attach (StateColor const & color)
{
    colors_.push_back(&color);
}
References colors_.
Referenced by AxisCtrlButton::AxisCtrlButton(), DropDown::Create(), Button::Create(), and StaticBox::Create().
attach() [2/2]
void StateHandler::attach (std::vector< StateColor const * > const & colors)
{
    colors_.insert(colors_.end(), colors.begin(), colors.end());
}
References colors_.
attach_child()
void StateHandler::attach_child (wxWindow * child)
{
    auto ch = new StateHandler(this, child);
    children_.emplace_back(ch);
    ch->update_binds();
    states2_ |= ch->states();
}
References children_, and states2_.
changed() [1/2]
void StateHandler::changed (int state2) private
{
    int old = states2_;
    states2_ = 0;
    for (auto &c : children_) states2_ |= c->states();
    if (old != states2_ && (old | states_) != (states_ | states2_)) {
        if (parent_)
            parent_->changed(states_ | states2_);
        else
            owner_->Refresh();
    }
}
References changed(), children_, owner_, parent_, states2_, and states_.
changed() [2/2]
void StateHandler::changed (wxEvent & event) private
{
    event.Skip();
    wxEventType events[] = {EVT_ENABLE_CHANGED, wxEVT_CHECKBOX, wxEVT_SET_FOCUS, wxEVT_ENTER_WINDOW, wxEVT_LEFT_DOWN};
    wxEventType events2[] = {{0}, {0}, wxEVT_KILL_FOCUS, wxEVT_LEAVE_WINDOW, wxEVT_LEFT_UP};
    int old = states_;
    // some events are from another window (ex: text_ctrl of TextInput), save state in states2_ to avoid conflicts
    for (int i = 0; i < 5; ++i) {
        if (events2[i]) {
            if (event.GetEventType() == events[i]) {
                states_ |= 1 << i;
                break;
            } else if (event.GetEventType() == events2[i]) {
                states_ &= ~(1 << i);
                break;
            }
        }
        else {
            if (event.GetEventType() == events[i]) {
                states_ ^= (1 << i);
                break;
            }
        }
    }
    if (old != states_ && (old | states2_) != (states_ | states2_)) {
        if (parent_)
            parent_->changed(states_ | states2_);
        else
            owner_->Refresh();
    }
}
References changed(), owner_, parent_, states2_, and states_.
Referenced by changed(), changed(), set_state(), and update_binds().
remove_child()
void StateHandler::remove_child (wxWindow * child)
{
    children_.erase(std::remove_if(children_.begin(), children_.end(),
            [child](auto &c) { return c->owner_ == child; }), children_.end());
    states2_ = 0;
    for (auto & c : children_) states2_ |= c->states();
}
References children_, and states2_.
set_state()
void StateHandler::set_state (int state, int mask)
{
    if (states_ & mask == state & mask) return;
    int old = states_;
    states_ = states_ & ~mask | state & mask;
    if (old != states_ && (old | states2_) != (states_ | states2_)) {
        if (parent_)
            parent_->changed(states_ | states2_);
        else
            owner_->Refresh();
    }
}
References changed(), owner_, parent_, states2_, and states_.
Referenced by Button::SetValue().
states()
int StateHandler::states () const inline
{ return states_ | states2_; }
References states2_, and states_.
Referenced by StaticBox::doRender(), StepCtrl::doRender(), StepIndicator::doRender(), TabCtrl::doRender(), SideButton::dorender(), Button::GetValue(), AxisCtrlButton::render(), Button::render(), DropDown::render(), ImageSwitchButton::render(), FanSwitchButton::render(), and update_binds().
update_binds()
void StateHandler::update_binds ()
{
    int bind_states = parent_ ? (parent_->bind_states_ & ~Enabled) : 0;
    for (auto c : colors_) {
        bind_states |= c->states();
    }
    bind_states = bind_states | (bind_states >> 16);
    int diff = bind_states ^ bind_states_;
    State       states[] = {Enabled, Checked, Focused, Hovered, Pressed};
    wxEventType events[] = {EVT_ENABLE_CHANGED, wxEVT_CHECKBOX, wxEVT_SET_FOCUS, wxEVT_ENTER_WINDOW, wxEVT_LEFT_DOWN};
    wxEventType events2[] = {{0}, {0}, wxEVT_KILL_FOCUS, wxEVT_LEAVE_WINDOW, wxEVT_LEFT_UP};
    for (int i = 0; i < 5; ++i) {
        int s = states[i];
        if (diff & s) {
            if (bind_states & s) {
                Bind(events[i], &StateHandler::changed, this);
                if (events2[i])
                    Bind(events2[i], &StateHandler::changed, this);
            } else {
                Unbind(events[i], &StateHandler::changed, this);
                if (events2[i])
                    owner_->Unbind(events2[i], &StateHandler::changed, this);
            }
        }
    }
    bind_states_ = bind_states;
    for (auto &c : children_) c->update_binds();
}
References bind_states_, changed(), Checked, children_, colors_, Enabled, Focused, Hovered, owner_, parent_, Pressed, and states().
Referenced by AxisCtrlButton::AxisCtrlButton(), DropDown::Create(), Button::Create(), StaticBox::Create(), AxisCtrlButton::SetBackgroundColor(), SideButton::SetBackgroundColor(), StaticBox::SetBackgroundColor(), StaticBox::SetBackgroundColor2(), SideButton::SetBackgroundColour(), AxisCtrlButton::SetBorderColor(), DropDown::SetBorderColor(), SideButton::SetBorderColor(), StaticBox::SetBorderColor(), SideButton::SetForegroundColor(), SideButton::SetForegroundColour(), AxisCtrlButton::SetInnerBackgroundColor(), DropDown::SetSelectorBackgroundColor(), DropDown::SetSelectorBorderColor(), AxisCtrlButton::SetTextColor(), Button::SetTextColor(), DropDown::SetTextColor(), ImageSwitchButton::SetTextColor(), and FanSwitchButton::SetTextColor().
Member Data Documentation
bind_states_
int StateHandler::bind_states_ = 0 private
Referenced by update_binds().
children_
std::vector<std::unique_ptr<StateHandler> > StateHandler::children_ private
Referenced by attach_child(), changed(), remove_child(), and update_binds().
colors_
std::vector<StateColor const *> StateHandler::colors_ private
Referenced by attach(), attach(), and update_binds().
owner_
wxWindow* StateHandler::owner_ private
Referenced by StateHandler(), ~StateHandler(), changed(), changed(), set_state(), and update_binds().
parent_
StateHandler* StateHandler::parent_ = nullptr private
Referenced by StateHandler(), changed(), changed(), set_state(), and update_binds().
states2_
int StateHandler::states2_ = 0 private
Referenced by attach_child(), changed(), changed(), remove_child(), set_state(), and states().
states_
int StateHandler::states_ = 0 private
Referenced by StateHandler(), StateHandler(), changed(), changed(), set_state(), and states().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/StateHandler.hpp
src/slic3r/GUI/Widgets/StateHandler.cpp