OrcaSlicer: cdt::edge_t Struct Reference
cdt::edge_t Struct Reference
edge_t connecting two vertices: vertex with smaller index is always first
#include <src/mcut/include/mcut/internal/cdt/utils.h>
Public Member Functions
edge_t (std::uint32_t iV1, std::uint32_t iV2)
bool operator== (const edge_t &other) const
bool operator!= (const edge_t &other) const
std::uint32_t v1 () const
std::uint32_t v2 () const
const std::pair< std::uint32_t, std::uint32_t > & verts () const
Private Attributes
std::pair< std::uint32_t, std::uint32_t > m_vertices
Detailed Description
edge_t connecting two vertices: vertex with smaller index is always first
Note
: hash edge_t is specialized at the bottom
Constructor & Destructor Documentation
edge_t()
cdt::edge_t::edge_t (std::uint32_t iV1, std::uint32_t iV2) inline
        : m_vertices(
            iV1 < iV2 ? std::make_pair(iV1, iV2) : std::make_pair(iV2, iV1))
    {
    }
Member Function Documentation
operator!=()
bool cdt::edge_t::operator!= (const edge_t & other) const inline
    {
        return !(this->operator==(other));
    }
References operator==().
operator==()
bool cdt::edge_t::operator== (const edge_t & other) const inline
    {
        return m_vertices == other.m_vertices;
    }
References m_vertices.
Referenced by operator!=().
v1()
std::uint32_t cdt::edge_t::v1 () const inline
    {
        return m_vertices.first;
    }
References m_vertices.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), cdt::edge_get_v1(), cdt::get_edge_to_split_vertices_map(), cdt::triangulator_t< T, TNearPointLocator >::insert_edge(), and cdt::remap_no_supertriangle().
v2()
std::uint32_t cdt::edge_t::v2 () const inline
    {
        return m_vertices.second;
    }
References m_vertices.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), cdt::edge_get_v2(), cdt::get_edge_to_split_vertices_map(), cdt::triangulator_t< T, TNearPointLocator >::insert_edge(), and cdt::remap_no_supertriangle().
verts()
const std::pair< std::uint32_t, std::uint32_t > & cdt::edge_t::verts () const inline
    {
        return m_vertices;
    }
References m_vertices.
Referenced by std::hash< cdt::edge_t >::get_hashed_edge_index().
Member Data Documentation
m_vertices
std::pair<std::uint32_t, std::uint32_t> cdt::edge_t::m_vertices private
Referenced by operator==(), v1(), v2(), and verts().
The documentation for this struct was generated from the following file:
src/mcut/include/mcut/internal/cdt/utils.h