OrcaSlicer: Slic3r::sla::PointRing< N > Class Template Reference
Slic3r::sla::PointRing< N > Class Template Reference
#include <src/libslic3r/SLA/SupportTreeBuildsteps.hpp>
Public Member Functions
PointRing (const Vec3d &n)
Vec3d get (size_t idx, const Vec3d src, double r) const
Static Private Member Functions
static bool constexpr is_one (double val)
Private Attributes
std::array< double, N > m_phis
Vec3d a = {0, 1, 0}
Vec3d b
double m_radius = 0.
Detailed Description
template<size_t N>
class Slic3r::sla::PointRing< N >
Constructor & Destructor Documentation
PointRing()
template<size_t N> Slic3r::sla::PointRing< N >::PointRing (const Vec3d & n) inline
    {
        m_phis = linspace_array<N>(0., 2 * PI);
        // We have to address the case when the direction vector v (same as
        // dir) is coincident with one of the world axes. In this case two of
        // its components will be completely zero and one is 1.0. Our method
        // becomes dangerous here due to division with zero. Instead, vector
        // 'a' can be an element-wise rotated version of 'v'
        if(is_one(n(X)) || is_one(n(Y)) || is_one(n(Z))) {
            a = {n(Z), n(X), n(Y)};
            b = {n(Y), n(Z), n(X)};
        }
        else {
            a(Z) = -(n(Y)*a(Y)) / n(Z); a.normalize();
            b = a.cross(n);
        }
    }
References Slic3r::sla::PointRing< N >::a, Slic3r::sla::PointRing< N >::b, Slic3r::sla::PointRing< N >::is_one(), Slic3r::sla::PointRing< N >::m_phis, n, PI, Slic3r::sla::X, Slic3r::sla::Y, and Slic3r::sla::Z.
Member Function Documentation
get()
template<size_t N> Vec3d Slic3r::sla::PointRing< N >::get (size_t idx, const Vec3d src, double r) const inline
    {
        double phi = m_phis[idx];
        double sinphi = std::sin(phi);
        double cosphi = std::cos(phi);
        double rpscos = r * cosphi;
        double rpssin = r * sinphi;
        // Point on the sphere
        return {src(X) + rpscos * a(X) + rpssin * b(X),
                src(Y) + rpscos * a(Y) + rpssin * b(Y),
                src(Z) + rpscos * a(Z) + rpssin * b(Z)};
    }
References Slic3r::sla::PointRing< N >::a, Slic3r::sla::PointRing< N >::b, Slic3r::sla::PointRing< N >::m_phis, Slic3r::sla::X, Slic3r::sla::Y, and Slic3r::sla::Z.
Referenced by Slic3r::sla::SupportTreeBuildsteps::pinhead_mesh_intersect().
is_one()
template<size_t N> static bool constexpr Slic3r::sla::PointRing< N >::is_one (double val) inline static constexpr private
    {
        return std::abs(std::abs(val) - 1) < 1e-20;
    }
Referenced by Slic3r::sla::PointRing< N >::PointRing().
Member Data Documentation
a
template<size_t N> Vec3d Slic3r::sla::PointRing< N >::a = {0, 1, 0} private
Referenced by Slic3r::sla::PointRing< N >::PointRing(), and Slic3r::sla::PointRing< N >::get().
b
template<size_t N> Vec3d Slic3r::sla::PointRing< N >::b private
Referenced by Slic3r::sla::PointRing< N >::PointRing(), and Slic3r::sla::PointRing< N >::get().
m_phis
template<size_t N> std::array<double, N> Slic3r::sla::PointRing< N >::m_phis private
Referenced by Slic3r::sla::PointRing< N >::PointRing(), and Slic3r::sla::PointRing< N >::get().
m_radius
template<size_t N> double Slic3r::sla::PointRing< N >::m_radius = 0. private
The documentation for this class was generated from the following file:
src/libslic3r/SLA/SupportTreeBuildsteps.hpp