OrcaSlicer: orgQhull::QhullLinkedListIterator< T > Class Template Reference
orgQhull::QhullLinkedListIterator< T > Class Template Reference
#include <src/qhull/src/libqhullcpp/QhullLinkedList.h>
Public Member Functions
QhullLinkedListIterator (const QhullLinkedList< T > &container)
QhullLinkedListIterator & operator= (const QhullLinkedList< T > &container)
bool hasNext () const
bool hasPrevious () const
T next ()
T peekNext () const
T peekPrevious () const
T previous ()
void toFront ()
void toBack ()
QhullLinkedListIterator
bool findNext (const T &t)
bool findPrevious (const T &t)
Private Types
typedef QhullLinkedList< T >::const_iterator const_iterator
Private Attributes
const QhullLinkedList< T > * c
const_iterator i
Detailed Description
template<typename T>
class orgQhull::QhullLinkedListIterator< T >
Member Typedef Documentation
const_iterator
template<typename T > typedef QhullLinkedList<T>::const_iterator orgQhull::QhullLinkedListIterator< T >::const_iterator private
Constructor & Destructor Documentation
QhullLinkedListIterator()
template<typename T > orgQhull::QhullLinkedListIterator< T >::QhullLinkedListIterator (const QhullLinkedList< T > & container) inline
: c(&container), i(c->constBegin()) {}
Member Function Documentation
findNext()
template<typename T > bool orgQhull::QhullLinkedListIterator< T >::findNext (const T & t)
{
    while(i != c->constEnd()){
        if (*i++ == t){
            return true;
        }
    }
    return false;
}//findNext
findPrevious()
template<typename T > bool orgQhull::QhullLinkedListIterator< T >::findPrevious (const T & t)
{
    while(i!=c->constBegin()){
        if(*(--i)==t){
            return true;
        }
    }
    return false;
}//findNext
hasNext()
template<typename T > bool orgQhull::QhullLinkedListIterator< T >::hasNext () const inline
{ return i != c->constEnd(); }
References orgQhull::QhullLinkedListIterator< T >::c, and orgQhull::QhullLinkedListIterator< T >::i.
Referenced by orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullVertex_test::t_getSet(), orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator(), orgQhull::QhullHyperplane_test::t_readonly(), orgQhull::QhullPoint_test::t_readonly(), and orgQhull::QhullFacetList::toStdVector().
hasPrevious()
template<typename T > bool orgQhull::QhullLinkedListIterator< T >::hasPrevious () const inline
{ return i != c->constBegin(); }
References orgQhull::QhullLinkedListIterator< T >::c, and orgQhull::QhullLinkedListIterator< T >::i.
Referenced by orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullVertex_test::t_getSet(), and orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator().
next()
template<typename T > T orgQhull::QhullLinkedListIterator< T >::next () inline
{ return *i++; }
References orgQhull::QhullLinkedListIterator< T >::i.
Referenced by orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullVertex_test::t_getSet(), orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator(), orgQhull::QhullHyperplane_test::t_readonly(), orgQhull::QhullPoint_test::t_readonly(), and orgQhull::QhullFacetList::toStdVector().
operator=()
template<typename T > QhullLinkedListIterator & orgQhull::QhullLinkedListIterator< T >::operator= (const QhullLinkedList< T > & container) inline
{ c= &container; i= c->constBegin(); return *this; }
References orgQhull::QhullLinkedListIterator< T >::c, and orgQhull::QhullLinkedListIterator< T >::i.
peekNext()
template<typename T > T orgQhull::QhullLinkedListIterator< T >::peekNext () const inline
{ return *i; }
References orgQhull::QhullLinkedListIterator< T >::i.
Referenced by orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullVertex_test::t_getSet(), and orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator().
peekPrevious()
template<typename T > T orgQhull::QhullLinkedListIterator< T >::peekPrevious () const inline
{ const_iterator p= i; return *--p; }
References orgQhull::QhullLinkedListIterator< T >::i.
Referenced by orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullVertex_test::t_getSet(), and orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator().
previous()
template<typename T > T orgQhull::QhullLinkedListIterator< T >::previous () inline
{ return *--i; }
References orgQhull::QhullLinkedListIterator< T >::i.
Referenced by orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator().
toBack()
template<typename T > void orgQhull::QhullLinkedListIterator< T >::toBack () inline
{ i= c->constEnd(); }
References orgQhull::QhullLinkedListIterator< T >::c, and orgQhull::QhullLinkedListIterator< T >::i.
Referenced by orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator().
toFront()
template<typename T > void orgQhull::QhullLinkedListIterator< T >::toFront () inline
{ i= c->constBegin(); }
References orgQhull::QhullLinkedListIterator< T >::c, and orgQhull::QhullLinkedListIterator< T >::i.
Referenced by orgQhull::QhullFacet_test::t_getSet(), and orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator().
Member Data Documentation
c
template<typename T > const QhullLinkedList<T>* orgQhull::QhullLinkedListIterator< T >::c private
Referenced by orgQhull::QhullLinkedListIterator< T >::hasNext(), orgQhull::QhullLinkedListIterator< T >::hasPrevious(), orgQhull::QhullLinkedListIterator< T >::operator=(), orgQhull::QhullLinkedListIterator< T >::toBack(), and orgQhull::QhullLinkedListIterator< T >::toFront().
i
template<typename T > const_iterator orgQhull::QhullLinkedListIterator< T >::i private
Referenced by orgQhull::QhullLinkedListIterator< T >::hasNext(), orgQhull::QhullLinkedListIterator< T >::hasPrevious(), orgQhull::QhullLinkedListIterator< T >::next(), orgQhull::QhullLinkedListIterator< T >::operator=(), orgQhull::QhullLinkedListIterator< T >::peekNext(), orgQhull::QhullLinkedListIterator< T >::peekPrevious(), orgQhull::QhullLinkedListIterator< T >::previous(), orgQhull::QhullLinkedListIterator< T >::toBack(), and orgQhull::QhullLinkedListIterator< T >::toFront().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullLinkedList.h