OrcaSlicer: Slic3r::GUI::SelectMachinePopup Class Reference
Slic3r::GUI::SelectMachinePopup Class Reference
#include <src/slic3r/GUI/SelectMachine.hpp>
Public Member Functions
SelectMachinePopup (wxWindow *parent)
~SelectMachinePopup ()
virtual void Popup (wxWindow *focus=NULL) wxOVERRIDE
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
virtual bool Show (bool show=true) wxOVERRIDE
void update_machine_list (wxCommandEvent &event)
void start_ssdp (bool on_off)
bool was_dismiss ()
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Private Member Functions
void OnLeftUp (wxMouseEvent &event)
void on_timer (wxTimerEvent &event)
void update_other_devices ()
void update_user_devices ()
bool search_for_printer (MachineObject *obj)
void on_dissmiss_win (wxCommandEvent &event)
wxWindow * create_title_panel (wxString text)
Private Attributes
int m_my_devices_count {0}
int m_other_devices_count {0}
wxWindow * m_placeholder_panel {nullptr}
wxHyperlinkCtrl * m_hyperlink {nullptr}
wxBoxSizer * m_sizer_body {nullptr}
wxBoxSizer * m_sizer_my_devices {nullptr}
wxBoxSizer * m_sizer_other_devices {nullptr}
wxBoxSizer * m_sizer_search_bar {nullptr}
wxSearchCtrl * m_search_bar {nullptr}
wxScrolledWindow * m_scrolledWindow {nullptr}
wxWindow * m_panel_body {nullptr}
wxTimer * m_refresh_timer {nullptr}
std::vector< MachinePanel * > m_user_list_machine_panel
std::vector< MachinePanel * > m_other_list_machine_panel
boost::thread * get_print_info_thread { nullptr }
std::string m_print_info
bool m_dismiss { false }
std::map< std::string, MachineObject * > m_bind_machine_list
std::map< std::string, MachineObject * > m_free_machine_list
Detailed Description
Constructor & Destructor Documentation
SelectMachinePopup()
Slic3r::GUI::SelectMachinePopup::SelectMachinePopup (wxWindow * parent)
    : PopupWindow(parent, wxBORDER_NONE | wxPU_CONTAINS_CONTROLS), m_dismiss(false)
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    SetSize(SELECT_MACHINE_POPUP_SIZE);
    SetMinSize(SELECT_MACHINE_POPUP_SIZE);
    SetMaxSize(SELECT_MACHINE_POPUP_SIZE);
    Freeze();
    wxBoxSizer *m_sizer_main = new wxBoxSizer(wxVERTICAL);
    SetBackgroundColour(SELECT_MACHINE_GREY400);
    m_scrolledWindow = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, SELECT_MACHINE_LIST_SIZE, wxHSCROLL | wxVSCROLL);
    m_scrolledWindow->SetBackgroundColour(*wxWHITE);
    m_scrolledWindow->SetMinSize(SELECT_MACHINE_LIST_SIZE);
    m_scrolledWindow->SetScrollRate(0, 5);
    auto m_sizxer_scrolledWindow = new wxBoxSizer(wxVERTICAL);
    m_scrolledWindow->SetSizer(m_sizxer_scrolledWindow);
    m_scrolledWindow->Layout();
    m_sizxer_scrolledWindow->Fit(m_scrolledWindow);
#if defined(__WINDOWS__)
  m_sizer_search_bar = new wxBoxSizer(wxVERTICAL);
  m_search_bar = new wxSearchCtrl( this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 );
  m_search_bar->ShowSearchButton( true );
  m_search_bar->ShowCancelButton( false );
  m_sizer_search_bar->Add( m_search_bar, 1, wxALL| wxEXPAND, 1 );
  m_sizer_main->Add(m_sizer_search_bar, 0, wxALL | wxEXPAND, FromDIP(2));
  m_search_bar->Bind( wxEVT_COMMAND_TEXT_UPDATED, &SelectMachinePopup::update_machine_list, this );
#endif
    auto own_title        = create_title_panel(_L("My Device"));
    m_sizer_my_devices    = new wxBoxSizer(wxVERTICAL);
    auto other_title      = create_title_panel(_L("Other Device"));
    m_sizer_other_devices = new wxBoxSizer(wxVERTICAL);
    m_sizxer_scrolledWindow->Add(own_title, 0, wxEXPAND | wxLEFT, FromDIP(15));
    m_sizxer_scrolledWindow->Add(m_sizer_my_devices, 0, wxEXPAND, 0);
    m_sizxer_scrolledWindow->Add(other_title, 0, wxEXPAND | wxLEFT, FromDIP(15));
    m_sizxer_scrolledWindow->Add(m_sizer_other_devices, 0, wxEXPAND, 0);
    m_sizer_main->Add(m_scrolledWindow, 0, wxALL | wxEXPAND, FromDIP(2));
    SetSizer(m_sizer_main);
    Layout();
    Thaw();
    #ifdef __APPLE__
    m_scrolledWindow->Bind(wxEVT_LEFT_UP, &SelectMachinePopup::OnLeftUp, this);
    #endif // __APPLE__
    m_refresh_timer = new wxTimer();
    m_refresh_timer->SetOwner(this);
    Bind(EVT_UPDATE_USER_MACHINE_LIST, &SelectMachinePopup::update_machine_list, this);
    Bind(wxEVT_TIMER, &SelectMachinePopup::on_timer, this);
    Bind(EVT_DISSMISS_MACHINE_LIST, &SelectMachinePopup::on_dissmiss_win, this);
}
References _L, create_title_panel(), m_refresh_timer, m_scrolledWindow, m_search_bar, m_sizer_my_devices, m_sizer_other_devices, m_sizer_search_bar, on_dissmiss_win(), on_timer(), OnLeftUp(), SELECT_MACHINE_GREY400, SELECT_MACHINE_LIST_SIZE, SELECT_MACHINE_POPUP_SIZE, and update_machine_list().
~SelectMachinePopup()
Slic3r::GUI::SelectMachinePopup::~SelectMachinePopup ()
{ delete m_refresh_timer;}
References m_refresh_timer.
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
create_title_panel()
wxWindow * Slic3r::GUI::SelectMachinePopup::create_title_panel (wxString text) private
{
    auto m_panel_title_own = new wxWindow(m_scrolledWindow, wxID_ANY, wxDefaultPosition, SELECT_MACHINE_ITEM_SIZE, wxTAB_TRAVERSAL);
    m_panel_title_own->SetBackgroundColour(*wxWHITE);
    wxBoxSizer *m_sizer_title_own = new wxBoxSizer(wxHORIZONTAL);
    auto m_title_own = new wxStaticText(m_panel_title_own, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, 0);
    m_title_own->Wrap(-1);
    m_sizer_title_own->Add(m_title_own, 0, wxALIGN_CENTER, 0);
    wxBoxSizer *m_sizer_line_own = new wxBoxSizer(wxHORIZONTAL);
    auto m_panel_line_own = new wxPanel(m_panel_title_own, wxID_ANY, wxDefaultPosition, wxSize(SELECT_MACHINE_ITEM_SIZE.x, FromDIP(1)), wxTAB_TRAVERSAL);
    m_panel_line_own->SetBackgroundColour(SELECT_MACHINE_GREY400);
    m_sizer_line_own->Add(m_panel_line_own, 0, wxALIGN_CENTER, 0);
    m_sizer_title_own->Add(0, 0, 0, wxLEFT, FromDIP(10));
    m_sizer_title_own->Add(m_sizer_line_own, 1, wxEXPAND | wxRIGHT, FromDIP(10));
    m_panel_title_own->SetSizer(m_sizer_title_own);
    m_panel_title_own->Layout();
    return m_panel_title_own;
}
References m_scrolledWindow, SELECT_MACHINE_GREY400, SELECT_MACHINE_ITEM_SIZE, and wxStaticText.
Referenced by SelectMachinePopup().
on_dissmiss_win()
void Slic3r::GUI::SelectMachinePopup::on_dissmiss_win (wxCommandEvent & event) private
{
    Dismiss();
}
Referenced by SelectMachinePopup().
on_timer()
void Slic3r::GUI::SelectMachinePopup::on_timer (wxTimerEvent & event) private
{
    BOOST_LOG_TRIVIAL(trace) << "SelectMachinePopup on_timer";
    wxGetApp().reset_to_active();
    wxCommandEvent user_event(EVT_UPDATE_USER_MACHINE_LIST);
    user_event.SetEventObject(this);
    wxPostEvent(this, user_event);
}
References Slic3r::trace().
Referenced by SelectMachinePopup().
OnDismiss()
void Slic3r::GUI::SelectMachinePopup::OnDismiss () virtual
{
    BOOST_LOG_TRIVIAL(trace) << "get_print_info: dismiss";
    start_ssdp(false);
    m_dismiss = true;
    if (m_refresh_timer) {
        m_refresh_timer->Stop();
    }
    if (get_print_info_thread) {
        if (get_print_info_thread->joinable()) {
            get_print_info_thread->join();
            delete get_print_info_thread;
            get_print_info_thread = nullptr;
        }
    }
    wxCommandEvent event(EVT_FINISHED_UPDATE_MACHINE_LIST);
    event.SetEventObject(this);
    wxPostEvent(this, event);
}
References get_print_info_thread, m_dismiss, m_refresh_timer, start_ssdp(), and Slic3r::trace().
OnLeftUp()
void Slic3r::GUI::SelectMachinePopup::OnLeftUp (wxMouseEvent & event) private
{
    auto mouse_pos = ClientToScreen(event.GetPosition());
    auto wxscroll_win_pos = m_scrolledWindow->ClientToScreen(wxPoint(0, 0));
    if (mouse_pos.x > wxscroll_win_pos.x && mouse_pos.y > wxscroll_win_pos.y && mouse_pos.x < (wxscroll_win_pos.x + m_scrolledWindow->GetSize().x) &&
        mouse_pos.y < (wxscroll_win_pos.y + m_scrolledWindow->GetSize().y)) {
        for (MachinePanel* p : m_user_list_machine_panel) {
            auto p_rect = p->mPanel->ClientToScreen(wxPoint(0, 0));
            if (mouse_pos.x > p_rect.x && mouse_pos.y > p_rect.y && mouse_pos.x < (p_rect.x + p->mPanel->GetSize().x) && mouse_pos.y < (p_rect.y + p->mPanel->GetSize().y)) {
                wxMouseEvent event(wxEVT_LEFT_UP);
                auto         tag_pos = p->mPanel->ScreenToClient(mouse_pos);
                event.SetPosition(tag_pos);
                event.SetEventObject(p->mPanel);
                wxPostEvent(p->mPanel, event);
            }
        }
        for (MachinePanel* p : m_other_list_machine_panel) {
            auto p_rect = p->mPanel->ClientToScreen(wxPoint(0, 0));
            if (mouse_pos.x > p_rect.x && mouse_pos.y > p_rect.y && mouse_pos.x < (p_rect.x + p->mPanel->GetSize().x) && mouse_pos.y < (p_rect.y + p->mPanel->GetSize().y)) {
                wxMouseEvent event(wxEVT_LEFT_UP);
                auto         tag_pos = p->mPanel->ScreenToClient(mouse_pos);
                event.SetPosition(tag_pos);
                event.SetEventObject(p->mPanel);
                wxPostEvent(p->mPanel, event);
            }
        }
        //hyper link
        auto h_rect = m_hyperlink->ClientToScreen(wxPoint(0, 0));
        if (mouse_pos.x > h_rect.x && mouse_pos.y > h_rect.y && mouse_pos.x < (h_rect.x + m_hyperlink->GetSize().x) && mouse_pos.y < (h_rect.y + m_hyperlink->GetSize().y)) {
          wxLaunchDefaultBrowser(wxT("https://wiki.bambulab.com/en/software/bambu-studio/failed-to-connect-printer"));
        }
    }
}
References m_hyperlink, m_other_list_machine_panel, m_scrolledWindow, m_user_list_machine_panel, and Slic3r::GUI::wxMouseEvent.
Referenced by SelectMachinePopup().
Popup()
void Slic3r::GUI::SelectMachinePopup::Popup (wxWindow * focus = NULL) virtual
{
    BOOST_LOG_TRIVIAL(trace) << "get_print_info: start";
    start_ssdp(true);
    if (m_refresh_timer) {
        m_refresh_timer->Stop();
        m_refresh_timer->Start(MACHINE_LIST_REFRESH_INTERVAL);
    }
    if (wxGetApp().is_user_login()) {
        if (!get_print_info_thread) {
            get_print_info_thread = new boost::thread(Slic3r::create_thread([&] {
                NetworkAgent* agent = wxGetApp().getAgent();
                unsigned int http_code;
                std::string body;
                int result = agent->get_user_print_info(&http_code, &body);
                if (result == 0) {
                    m_print_info = body;
                } else {
                    m_print_info = "";
                }
                wxCommandEvent event(EVT_UPDATE_USER_MACHINE_LIST);
                event.SetEventObject(this);
                wxPostEvent(this, event);
            }));
        }
    }
    wxPostEvent(this, wxTimerEvent());
    PopupWindow::Popup();
}
References Slic3r::create_thread(), get_print_info_thread, Slic3r::NetworkAgent::get_user_print_info(), m_print_info, m_refresh_timer, MACHINE_LIST_REFRESH_INTERVAL, start_ssdp(), and Slic3r::trace().
Referenced by Slic3r::GUI::MonitorPanel::on_printer_clicked().
ProcessLeftDown()
bool Slic3r::GUI::SelectMachinePopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
search_for_printer()
bool Slic3r::GUI::SelectMachinePopup::search_for_printer (MachineObject * obj) private
{
  std::string search_text = std::string((m_search_bar->GetValue()).mb_str());
  if (search_text.empty()) {
    return true;
  }
  auto name = obj->dev_name;
  auto ip = obj->dev_ip;
  auto name_it = name.find(search_text);
  auto ip_it = ip.find(search_text);
  if ((name_it != std::string::npos)||(ip_it != std::string::npos)) {
    return true;
  }
    return false;
}
References Slic3r::MachineObject::dev_ip, Slic3r::MachineObject::dev_name, and m_search_bar.
Referenced by update_other_devices().
Show()
bool Slic3r::GUI::SelectMachinePopup::Show (bool show = true) virtual
{
    if (show) {
        for (int i = 0; i < m_user_list_machine_panel.size(); i++) {
            m_user_list_machine_panel[i]->mPanel->update_machine_info(nullptr);
            m_user_list_machine_panel[i]->mPanel->Hide();
        }
         for (int j = 0; j < m_other_list_machine_panel.size(); j++) {
            m_other_list_machine_panel[j]->mPanel->update_machine_info(nullptr);
            m_other_list_machine_panel[j]->mPanel->Hide();
        }
    }
    return PopupWindow::Show(show);
}
References m_other_list_machine_panel, and m_user_list_machine_panel.
start_ssdp()
void Slic3r::GUI::SelectMachinePopup::start_ssdp (bool on_off)
{
    return;
    //if (wxGetApp().getAgent()) { wxGetApp().getAgent()->start_discovery(true, start); }
}
Referenced by OnDismiss(), and Popup().
update_machine_list()
void Slic3r::GUI::SelectMachinePopup::update_machine_list (wxCommandEvent & event)
{
    update_user_devices();
    update_other_devices();
    BOOST_LOG_TRIVIAL(trace) << "SelectMachinePopup update_machine_list end";
}
References Slic3r::trace(), update_other_devices(), and update_user_devices().
Referenced by SelectMachinePopup().
update_other_devices()
void Slic3r::GUI::SelectMachinePopup::update_other_devices () private
{
    DeviceManager* dev = wxGetApp().getDeviceManager();
    if (!dev) return;
    m_free_machine_list = dev->get_local_machine_list();
    BOOST_LOG_TRIVIAL(trace) << "SelectMachinePopup update_other_devices start";
    this->Freeze();
    m_scrolledWindow->Freeze();
    int i = 0;
    for (auto &elem : m_free_machine_list) {
        MachineObject *     mobj = elem.second;
        /* do not show printer bind state is empty */
        if (!mobj->is_avaliable()) continue;
        if (!wxGetApp().is_user_login() && !mobj->is_lan_mode_printer())
            continue;
        /* do not show printer in my list */
        auto it = m_bind_machine_list.find(mobj->dev_id);
        if (it != m_bind_machine_list.end())
            continue;
        MachineObjectPanel* op = nullptr;
        if (i < m_other_list_machine_panel.size()) {
            op = m_other_list_machine_panel[i]->mPanel;
            op->Show();
#if defined(__WINDOWS__)
      if (!search_for_printer(mobj)) {
        op->Hide();
      }
#endif
        } else {
            op = new MachineObjectPanel(m_scrolledWindow, wxID_ANY);
            MachinePanel* mpanel = new MachinePanel();
            mpanel->mIndex = wxString::Format("%d", i);
            mpanel->mPanel = op;
            m_other_list_machine_panel.push_back(mpanel);
            m_sizer_other_devices->Add(op, 0, wxEXPAND, 0);
        }
        i++;
        op->update_machine_info(mobj);
        if (mobj->is_lan_mode_printer()) {
            if (mobj->has_access_right()) {
                op->set_printer_state(PrinterState::IN_LAN);
            } else {
                op->set_printer_state(PrinterState::LOCK);
            }
        } else {
            op->show_edit_printer_name(false);
            op->show_printer_bind(true, PrinterBindState::ALLOW_BIND);
            if (mobj->is_in_printing()) {
                op->set_printer_state(PrinterState::BUSY);
            } else {
                op->SetToolTip(_L("Online"));
                op->set_printer_state(IDLE);
            }
        }
        op->Bind(EVT_CONNECT_LAN_PRINT, [this, mobj](wxCommandEvent &e) {
            if (mobj) {
                if (mobj->is_lan_mode_printer()) {
                    ConnectPrinterDialog dlg(wxGetApp().mainframe, wxID_ANY, _L("Input access code"));
                    dlg.set_machine_object(mobj);
                    if (dlg.ShowModal() == wxID_OK) {
                        wxGetApp().mainframe->jump_to_monitor(mobj->dev_id);
                    }
                }
            }
        });
        op->Bind(EVT_BIND_MACHINE, [this, mobj](wxCommandEvent &e) {
            BindMachineDialog dlg;
            dlg.update_machine_info(mobj);
            int dlg_result = wxID_CANCEL;
            dlg_result     = dlg.ShowModal();
            if (dlg_result == wxID_OK) { wxGetApp().mainframe->jump_to_monitor(mobj->dev_id); }
        });
    }
    for (int j = i; j < m_other_list_machine_panel.size(); j++) {
        m_other_list_machine_panel[j]->mPanel->update_machine_info(nullptr);
        m_other_list_machine_panel[j]->mPanel->Hide();
    }
    if (m_placeholder_panel != nullptr) {
        m_scrolledWindow->RemoveChild(m_placeholder_panel);
        m_placeholder_panel->Destroy();
        m_placeholder_panel = nullptr;
    }
    m_placeholder_panel = new wxWindow(m_scrolledWindow, wxID_ANY, wxDefaultPosition, wxSize(-1,FromDIP(26)));
    wxBoxSizer* placeholder_sizer = new wxBoxSizer(wxVERTICAL);
    m_hyperlink = new wxHyperlinkCtrl(m_placeholder_panel, wxID_ANY, _L("Can't find my devices?"), wxT("https://wiki.bambulab.com/en/software/bambu-studio/failed-to-connect-printer"), wxDefaultPosition, wxDefaultSize, wxHL_DEFAULT_STYLE);
    placeholder_sizer->Add(m_hyperlink, 0, wxALIGN_CENTER | wxALL, 5);
    m_placeholder_panel->SetSizer(placeholder_sizer);
    m_placeholder_panel->Layout();
    placeholder_sizer->Fit(m_placeholder_panel);
    m_placeholder_panel->SetBackgroundColour(StateColor::darkModeColorFor(*wxWHITE));
    m_sizer_other_devices->Add(m_placeholder_panel, 0, wxEXPAND, 0);
    //m_sizer_other_devices->Layout();
    if(m_other_devices_count != i) {
    m_scrolledWindow->Fit();
    }
    m_scrolledWindow->Layout();
  m_scrolledWindow->Thaw();
  Layout();
  Fit();
  this->Thaw();
    m_other_devices_count = i;
    BOOST_LOG_TRIVIAL(trace) << "SelectMachinePopup update_other_devices end";
}
References _L, Slic3r::GUI::ALLOW_BIND, Slic3r::GUI::BUSY, Slic3r::MachineObject::dev_id, Slic3r::DeviceManager::get_local_machine_list(), Slic3r::MachineObject::has_access_right(), Slic3r::GUI::IDLE, Slic3r::GUI::IN_LAN, Slic3r::MachineObject::is_avaliable(), Slic3r::MachineObject::is_in_printing(), Slic3r::MachineObject::is_lan_mode_printer(), Slic3r::GUI::LOCK, m_bind_machine_list, m_free_machine_list, m_other_list_machine_panel, m_scrolledWindow, m_sizer_other_devices, Slic3r::GUI::MachinePanel::mIndex, Slic3r::GUI::MachinePanel::mPanel, search_for_printer(), Slic3r::GUI::MachineObjectPanel::set_printer_state(), Slic3r::GUI::MachineObjectPanel::show_edit_printer_name(), Slic3r::GUI::MachineObjectPanel::show_printer_bind(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::trace(), Slic3r::GUI::BindMachineDialog::update_machine_info(), and Slic3r::GUI::MachineObjectPanel::update_machine_info().
Referenced by update_machine_list().
update_user_devices()
void Slic3r::GUI::SelectMachinePopup::update_user_devices () private
{
    Slic3r::DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    if (!m_print_info.empty()) {
        dev->parse_user_print_info(m_print_info);
        m_print_info = "";
    }
    m_bind_machine_list.clear();
    m_bind_machine_list = dev->get_my_machine_list();
    //sort list
    std::vector<std::pair<std::string, MachineObject*>> user_machine_list;
    for (auto& it: m_bind_machine_list) {
        user_machine_list.push_back(it);
    }
    std::sort(user_machine_list.begin(), user_machine_list.end(), [&](auto& a, auto&b) {
            if (a.second && b.second) {
                return a.second->dev_name.compare(b.second->dev_name) < 0;
            }
            return false;
        });
    BOOST_LOG_TRIVIAL(trace) << "SelectMachinePopup update_machine_list start";
    this->Freeze();
    m_scrolledWindow->Freeze();
    int i = 0;
    for (auto& elem : user_machine_list) {
        MachineObject* mobj = elem.second;
        MachineObjectPanel* op = nullptr;
        if (i < m_user_list_machine_panel.size()) {
            op = m_user_list_machine_panel[i]->mPanel;
            op->Show();
#if defined(__WINDOWS__)
      if (!search_for_printer(mobj)) {
        op->Hide();
      }
#endif
        } else {
            op = new MachineObjectPanel(m_scrolledWindow, wxID_ANY);
            MachinePanel* mpanel = new MachinePanel();
            mpanel->mIndex = wxString::Format("%d", i);
            mpanel->mPanel = op;
            m_user_list_machine_panel.push_back(mpanel);
            m_sizer_my_devices->Add(op, 0, wxEXPAND, 0);
        }
        i++;
        op->update_machine_info(mobj, true);
        //set in lan
        if (mobj->is_lan_mode_printer()) {
            if (!mobj->is_online()) {
                continue;
            }
            else {
                op->show_printer_bind(false, PrinterBindState::NONE);
                op->show_edit_printer_name(false);
                if (mobj->has_access_right() && mobj->is_avaliable()) {
                    op->set_printer_state(PrinterState::IN_LAN);
                    op->show_printer_bind(true, PrinterBindState::ALLOW_UNBIND);
                    op->SetToolTip(_L("Online"));
                }
                else {
                    op->set_printer_state(PrinterState::LOCK);
                }
            }
            op->Bind(EVT_UNBIND_MACHINE, [this, dev, mobj](wxCommandEvent& e) {
                dev->set_selected_machine("");
                if (mobj) {
                    mobj->set_access_code("");
                    mobj->set_user_access_code("");
                }
                MessageDialog msg_wingow(nullptr, _L("Log out successful."), "", wxAPPLY | wxOK);
                if (msg_wingow.ShowModal() == wxOK) { return; }
                });
        }
        else {
            op->show_printer_bind(true, PrinterBindState::ALLOW_UNBIND);
            op->Bind(EVT_UNBIND_MACHINE, [this, mobj, dev](wxCommandEvent& e) {
                // show_unbind_dialog
                UnBindMachineDialog dlg;
                dlg.update_machine_info(mobj);
                if (dlg.ShowModal() == wxID_OK) {
                    dev->set_selected_machine("");
                }
                });
            if (!mobj->is_online()) {
                op->SetToolTip(_L("Offline"));
                op->set_printer_state(PrinterState::OFFLINE);
            }
            else {
                op->show_edit_printer_name(true);
                op->show_printer_bind(true, PrinterBindState::ALLOW_UNBIND);
                if (mobj->is_in_printing()) {
                    op->SetToolTip(_L("Busy"));
                    op->set_printer_state(PrinterState::BUSY);
                }
                else {
                    op->SetToolTip(_L("Online"));
                    op->set_printer_state(PrinterState::IDLE);
                }
            }
        }
        op->Bind(EVT_CONNECT_LAN_PRINT, [this, mobj](wxCommandEvent &e) {
            if (mobj) {
                if (mobj->is_lan_mode_printer()) {
                    ConnectPrinterDialog dlg(wxGetApp().mainframe, wxID_ANY, _L("Input access code"));
                    dlg.set_machine_object(mobj);
                    if (dlg.ShowModal() == wxID_OK) {
                        wxGetApp().mainframe->jump_to_monitor(mobj->dev_id);
                    }
                }
            }
        });
         op->Bind(EVT_EDIT_PRINT_NAME, [this, mobj](wxCommandEvent &e) {
            EditDevNameDialog dlg;
            dlg.set_machine_obj(mobj);
            dlg.ShowModal();
         });
    }
    for (int j = i; j < m_user_list_machine_panel.size(); j++) {
        m_user_list_machine_panel[j]->mPanel->update_machine_info(nullptr);
        m_user_list_machine_panel[j]->mPanel->Hide();
    }
    //m_sizer_my_devices->Layout();
    if (m_my_devices_count != i) {
    m_scrolledWindow->Fit();
    }
    m_scrolledWindow->Layout();
    m_scrolledWindow->Thaw();
  Layout();
  Fit();
  this->Thaw();
    m_my_devices_count = i;
}
References Slic3r::DeviceManager::get_my_machine_list(), and Slic3r::DeviceManager::parse_user_print_info().
Referenced by update_machine_list().
was_dismiss()
bool Slic3r::GUI::SelectMachinePopup::was_dismiss () inline
{ return m_dismiss; }
References m_dismiss.
Member Data Documentation
get_print_info_thread
boost::thread* Slic3r::GUI::SelectMachinePopup::get_print_info_thread { nullptr } private
Referenced by OnDismiss(), and Popup().
m_bind_machine_list
std::map<std::string, MachineObject*> Slic3r::GUI::SelectMachinePopup::m_bind_machine_list private
Referenced by update_other_devices().
m_dismiss
bool Slic3r::GUI::SelectMachinePopup::m_dismiss { false } private
Referenced by OnDismiss(), and was_dismiss().
m_free_machine_list
std::map<std::string, MachineObject*> Slic3r::GUI::SelectMachinePopup::m_free_machine_list private
Referenced by update_other_devices().
m_hyperlink
wxHyperlinkCtrl* Slic3r::GUI::SelectMachinePopup::m_hyperlink {nullptr} private
Referenced by OnLeftUp().
m_my_devices_count
int Slic3r::GUI::SelectMachinePopup::m_my_devices_count {0} private
m_other_devices_count
int Slic3r::GUI::SelectMachinePopup::m_other_devices_count {0} private
m_other_list_machine_panel
std::vector<MachinePanel*> Slic3r::GUI::SelectMachinePopup::m_other_list_machine_panel private
Referenced by OnLeftUp(), Show(), and update_other_devices().
m_panel_body
wxWindow* Slic3r::GUI::SelectMachinePopup::m_panel_body {nullptr} private
m_placeholder_panel
wxWindow* Slic3r::GUI::SelectMachinePopup::m_placeholder_panel {nullptr} private
m_print_info
std::string Slic3r::GUI::SelectMachinePopup::m_print_info private
Referenced by Popup().
m_refresh_timer
wxTimer* Slic3r::GUI::SelectMachinePopup::m_refresh_timer {nullptr} private
Referenced by SelectMachinePopup(), ~SelectMachinePopup(), OnDismiss(), and Popup().
m_scrolledWindow
wxScrolledWindow* Slic3r::GUI::SelectMachinePopup::m_scrolledWindow {nullptr} private
Referenced by SelectMachinePopup(), create_title_panel(), OnLeftUp(), and update_other_devices().
m_search_bar
wxSearchCtrl* Slic3r::GUI::SelectMachinePopup::m_search_bar {nullptr} private
Referenced by SelectMachinePopup(), and search_for_printer().
m_sizer_body
wxBoxSizer* Slic3r::GUI::SelectMachinePopup::m_sizer_body {nullptr} private
m_sizer_my_devices
wxBoxSizer* Slic3r::GUI::SelectMachinePopup::m_sizer_my_devices {nullptr} private
Referenced by SelectMachinePopup().
m_sizer_other_devices
wxBoxSizer* Slic3r::GUI::SelectMachinePopup::m_sizer_other_devices {nullptr} private
Referenced by SelectMachinePopup(), and update_other_devices().
m_sizer_search_bar
wxBoxSizer* Slic3r::GUI::SelectMachinePopup::m_sizer_search_bar {nullptr} private
Referenced by SelectMachinePopup().
m_user_list_machine_panel
std::vector<MachinePanel*> Slic3r::GUI::SelectMachinePopup::m_user_list_machine_panel private
Referenced by OnLeftUp(), and Show().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SelectMachine.hpp
src/slic3r/GUI/SelectMachine.cpp