OrcaSlicer: src/Shiny/ShinyManager.h File Reference
ShinyManager.h File Reference
#include "ShinyZone.h"
#include "ShinyNode.h"
#include "ShinyNodePool.h"
#include "ShinyTools.h"
#include "ShinyOutput.h"
#include <stdio.h>
Classes
struct ShinyManager
Functions
SHINY_INLINE void _ShinyManager_appendTicksToCurNode (ShinyManager *self)
SHINY_API ShinyNode * _ShinyManager_lookupNode (ShinyManager *self, ShinyNodeCache *a_cache, ShinyZone *a_zone)
SHINY_API void _ShinyManager_createNodeTable (ShinyManager *self, uint32_t a_count)
SHINY_API void _ShinyManager_resizeNodeTable (ShinyManager *self, uint32_t a_count)
SHINY_API void _ShinyManager_createNodePool (ShinyManager *self, uint32_t a_count)
SHINY_API void _ShinyManager_resizeNodePool (ShinyManager *self, uint32_t a_count)
SHINY_API ShinyNode * _ShinyManager_createNode (ShinyManager *self, ShinyNodeCache *a_cache, ShinyZone *a_pZone)
SHINY_API void _ShinyManager_insertNode (ShinyManager *self, ShinyNode *a_pNode)
SHINY_INLINE void _ShinyManager_init (ShinyManager *self)
SHINY_INLINE void _ShinyManager_uninit (ShinyManager *self)
SHINY_INLINE void _ShinyManager_incLookup (ShinyManager *self)
SHINY_INLINE void _ShinyManager_incLookupSuccess (ShinyManager *self)
SHINY_INLINE float ShinyManager_lookupRate (const ShinyManager *self)
SHINY_API void ShinyManager_resetZones (ShinyManager *self)
SHINY_API void ShinyManager_destroyNodes (ShinyManager *self)
SHINY_INLINE float ShinyManager_tableUsage (const ShinyManager *self)
SHINY_INLINE uint32_t ShinyManager_allocMemInBytes (const ShinyManager *self)
SHINY_INLINE void ShinyManager_beginNode (ShinyManager *self, ShinyNode *a_node)
SHINY_INLINE void ShinyManager_lookupAndBeginNode (ShinyManager *self, ShinyNodeCache *a_cache, ShinyZone *a_zone)
SHINY_INLINE void ShinyManager_endCurNode (ShinyManager *self)
SHINY_API void ShinyManager_preLoad (ShinyManager *self)
SHINY_API void ShinyManager_updateClean (ShinyManager *self)
SHINY_API void ShinyManager_update (ShinyManager *self)
SHINY_API void ShinyManager_clear (ShinyManager *self)
SHINY_API void ShinyManager_destroy (ShinyManager *self)
SHINY_INLINE void ShinyManager_sortZones (ShinyManager *self)
SHINY_API const char * ShinyManager_getOutputErrorString (ShinyManager *self)
SHINY_API int ShinyManager_output (ShinyManager *self, const char *a_filename)
SHINY_API void ShinyManager_outputToStream (ShinyManager *self, FILE *stream)
SHINY_INLINE int ShinyManager_isZoneSelfTimeBelow (ShinyManager *self, ShinyZone *a_zone, float a_percentage)
SHINY_INLINE int ShinyManager_isZoneTotalTimeBelow (ShinyManager *self, ShinyZone *a_zone, float a_percentage)
SHINY_INLINE void ShinyManager_enumerateNodes (ShinyManager *self, void(*a_func)(const ShinyNode *))
SHINY_INLINE void ShinyManager_enumerateZones (ShinyManager *self, void(*a_func)(const ShinyZone *))
Variables
ShinyNode * _ShinyManager_dummyNodeTable []
ShinyManager Shiny_instance
Class Documentation
ShinyManager
struct ShinyManager
Class Members
ShinyNode * _curNode
ShinyNodePool * _firstNodePool
int _firstUpdate
int _initialized
ShinyNodePool * _lastNodePool
shinytick_t _lastTick
ShinyZone * _lastZone
ShinyNodeTable * _nodeTable
uint32_t _tableMask
uint32_t _tableSize
float damping
uint32_t nodeCount
ShinyNode rootNode
ShinyZone rootZone
uint32_t zoneCount
Function Documentation
_ShinyManager_appendTicksToCurNode()
SHINY_INLINE void _ShinyManager_appendTicksToCurNode (ShinyManager * self)
{
  shinytick_t curTick;
  ShinyGetTicks(&curTick);
  ShinyNode_appendTicks(self->_curNode, curTick - self->_lastTick);
  self->_lastTick = curTick;
}
References ShinyManager::_curNode, ShinyManager::_lastTick, ShinyGetTicks(), and ShinyNode_appendTicks().
Referenced by ShinyManager_beginNode(), and ShinyManager_endCurNode().
_ShinyManager_createNode()
SHINY_API ShinyNode * _ShinyManager_createNode (ShinyManager * self, ShinyNodeCache * a_cache, ShinyZone * a_pZone)
_ShinyManager_createNodePool()
SHINY_API void _ShinyManager_createNodePool (ShinyManager * self, uint32_t a_count)
_ShinyManager_createNodeTable()
SHINY_API void _ShinyManager_createNodeTable (ShinyManager * self, uint32_t a_count)
_ShinyManager_incLookup()
SHINY_INLINE void _ShinyManager_incLookup (ShinyManager * self)
{ self = self; }
_ShinyManager_incLookupSuccess()
SHINY_INLINE void _ShinyManager_incLookupSuccess (ShinyManager * self)
{ self = self; }
_ShinyManager_init()
SHINY_INLINE void _ShinyManager_init (ShinyManager * self)
{
  self->_initialized = TRUE;
  self->rootNode._last.entryCount = 1;
  self->rootNode._last.selfTicks = 0;
  ShinyGetTicks(&self->_lastTick);
}
References ShinyManager::_initialized, _ShinyNode::_last, ShinyManager::_lastTick, ShinyLastData::entryCount, ShinyManager::rootNode, ShinyLastData::selfTicks, ShinyGetTicks(), and TRUE.
_ShinyManager_insertNode()
SHINY_API void _ShinyManager_insertNode (ShinyManager * self, ShinyNode * a_pNode)
_ShinyManager_lookupNode()
SHINY_API ShinyNode * _ShinyManager_lookupNode (ShinyManager * self, ShinyNodeCache * a_cache, ShinyZone * a_zone)
Referenced by ShinyManager_lookupAndBeginNode().
_ShinyManager_resizeNodePool()
SHINY_API void _ShinyManager_resizeNodePool (ShinyManager * self, uint32_t a_count)
_ShinyManager_resizeNodeTable()
SHINY_API void _ShinyManager_resizeNodeTable (ShinyManager * self, uint32_t a_count)
_ShinyManager_uninit()
SHINY_INLINE void _ShinyManager_uninit (ShinyManager * self)
{
  self->_initialized = FALSE;
  ShinyNode_clear(&self->rootNode);
  self->rootNode.parent = &self->rootNode;
  self->rootNode.zone = &self->rootZone;
}
References ShinyManager::_initialized, FALSE, _ShinyNode::parent, ShinyManager::rootNode, ShinyManager::rootZone, ShinyNode_clear(), and _ShinyNode::zone.
ShinyManager_allocMemInBytes()
SHINY_INLINE uint32_t ShinyManager_allocMemInBytes (const ShinyManager * self)
{
  return self->_tableSize * sizeof(ShinyNode*)
     + (self->_firstNodePool)? ShinyNodePool_memoryUsageChain(self->_firstNodePool) : 0;
}
References ShinyManager::_firstNodePool, ShinyManager::_tableSize, and ShinyNodePool_memoryUsageChain().
ShinyManager_beginNode()
SHINY_INLINE void ShinyManager_beginNode (ShinyManager * self, ShinyNode * a_node)
{
  ShinyNode_beginEntry(a_node);
  _ShinyManager_appendTicksToCurNode(self);
  self->_curNode = a_node;
}
References ShinyManager::_curNode, _ShinyManager_appendTicksToCurNode(), and ShinyNode_beginEntry().
Referenced by ShinyManager_lookupAndBeginNode().
ShinyManager_clear()
SHINY_API void ShinyManager_clear (ShinyManager * self)
ShinyManager_destroy()
SHINY_API void ShinyManager_destroy (ShinyManager * self)
ShinyManager_destroyNodes()
SHINY_API void ShinyManager_destroyNodes (ShinyManager * self)
ShinyManager_endCurNode()
SHINY_INLINE void ShinyManager_endCurNode (ShinyManager * self)
{
#ifdef SHINY_HAS_ENABLED
  if (!self->enabled) return;
#endif
  _ShinyManager_appendTicksToCurNode(self);
  self->_curNode = self->_curNode->parent;
}
References ShinyManager::_curNode, _ShinyManager_appendTicksToCurNode(), and _ShinyNode::parent.
ShinyManager_enumerateNodes()
SHINY_INLINE void ShinyManager_enumerateNodes (ShinyManager * self, void(*)(const ShinyNode *) a_func)
{
  ShinyNode_enumerateNodes(&self->rootNode, a_func);
}
References ShinyManager::rootNode, and ShinyNode_enumerateNodes().
ShinyManager_enumerateZones()
SHINY_INLINE void ShinyManager_enumerateZones (ShinyManager * self, void(*)(const ShinyZone *) a_func)
{
  ShinyZone_enumerateZones(&self->rootZone, a_func);
}
References ShinyManager::rootZone, and ShinyZone_enumerateZones().
ShinyManager_getOutputErrorString()
SHINY_API const char * ShinyManager_getOutputErrorString (ShinyManager * self)
ShinyManager_isZoneSelfTimeBelow()
SHINY_INLINE int ShinyManager_isZoneSelfTimeBelow (ShinyManager * self, ShinyZone * a_zone, float a_percentage)
{
  return a_percentage * (float) self->rootZone.data.childTicks.cur
    <= (float) a_zone->data.selfTicks.cur;
}
References ShinyData::childTicks, ShinyTickData::cur, _ShinyZone::data, ShinyManager::rootZone, and ShinyData::selfTicks.
ShinyManager_isZoneTotalTimeBelow()
SHINY_INLINE int ShinyManager_isZoneTotalTimeBelow (ShinyManager * self, ShinyZone * a_zone, float a_percentage)
{
  return a_percentage * (float) self->rootZone.data.childTicks.cur
    <= (float) ShinyData_totalTicksCur(&a_zone->data);
}
References ShinyData::childTicks, ShinyTickData::cur, _ShinyZone::data, ShinyManager::rootZone, and ShinyData_totalTicksCur().
ShinyManager_lookupAndBeginNode()
SHINY_INLINE void ShinyManager_lookupAndBeginNode (ShinyManager * self, ShinyNodeCache * a_cache, ShinyZone * a_zone)
{
#ifdef SHINY_HAS_ENABLED
  if (!self->enabled) return;
#endif
  if (self->_curNode != (*a_cache)->parent)
    *a_cache = _ShinyManager_lookupNode(self, a_cache, a_zone);
  ShinyManager_beginNode(self, *a_cache);
}
References ShinyManager::_curNode, _ShinyManager_lookupNode(), _ShinyNode::parent, and ShinyManager_beginNode().
ShinyManager_lookupRate()
SHINY_INLINE float ShinyManager_lookupRate (const ShinyManager * self)
{ self = self; return -1; }
ShinyManager_output()
SHINY_API int ShinyManager_output (ShinyManager * self, const char * a_filename)
ShinyManager_outputToStream()
SHINY_API void ShinyManager_outputToStream (ShinyManager * self, FILE * stream)
ShinyManager_preLoad()
SHINY_API void ShinyManager_preLoad (ShinyManager * self)
ShinyManager_resetZones()
SHINY_API void ShinyManager_resetZones (ShinyManager * self)
ShinyManager_sortZones()
SHINY_INLINE void ShinyManager_sortZones (ShinyManager * self)
{
  if (self->rootZone.next)
    self->_lastZone = ShinyZone_sortChain(&self->rootZone.next);
}
References ShinyManager::_lastZone, _ShinyZone::next, ShinyManager::rootZone, and ShinyZone_sortChain().
ShinyManager_tableUsage()
SHINY_INLINE float ShinyManager_tableUsage (const ShinyManager * self)
{
  return ((float) self->nodeCount) / ((float) self->_tableSize);
}
References ShinyManager::_tableSize, and ShinyManager::nodeCount.
ShinyManager_update()
SHINY_API void ShinyManager_update (ShinyManager * self)
ShinyManager_updateClean()
SHINY_API void ShinyManager_updateClean (ShinyManager * self)
Variable Documentation
_ShinyManager_dummyNodeTable
ShinyNode* _ShinyManager_dummyNodeTable[] extern
Shiny_instance
ShinyManager Shiny_instance extern