OrcaSlicer: orgQhull::QhullPoint_test Class Reference
orgQhull::QhullPoint_test Class Reference
Public Member Functions
Helper
void recordFailedTest ()
Static Public Member Functions
Class functions
static void deleteTests ()
static int runTests (QStringList arguments)
Static Protected Attributes
Class globals
static QList< RoadTest * > s_testcases
static int s_test_count = 0
! List of testcases to execute. Initialized via add_...()
static int s_test_fail = 0
! Total number of tests executed
static QStringList s_failed_tests
! Number of failed tests
Private Slots
Test slots
void cleanup ()
void t_construct ()
void t_convert ()
void t_readonly ()
void t_define ()
void t_operator ()
void t_iterator ()
void t_const_iterator ()
void t_qhullpoint_iterator ()
void t_method ()
void t_io ()
Detailed Description
Member Function Documentation
cleanup
void orgQhull::QhullPoint_test::cleanup () private slot
{
    RoadTest::cleanup();
}
References orgQhull::RoadTest::cleanup().
deleteTests()
void orgQhull::RoadTest::deleteTests () static inherited
{
    foreach(RoadTest *testcase, s_testcases){
        delete testcase;
    }
    s_failed_tests.clear();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
recordFailedTest()
void orgQhull::RoadTest::recordFailedTest () inherited
{
    s_test_fail++;
    QString className= metaObject()->className();
    s_failed_tests << className + "::" + QTest::currentTestFunction();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_test_fail.
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
runTests()
int orgQhull::RoadTest::runTests (QStringList arguments) static inherited
{
    int result= 0; // assume success
    foreach(RoadTest *testcase, s_testcases){
        try{
            result += QTest::qExec(testcase, arguments);
        }catch(const std::exception &e){
            cout << "FAIL!  : Threw error ";
            cout << e.what() << endl;
    s_test_count++;
            testcase->recordFailedTest();
            // Qt 4.5.2 OK.  In Qt 4.3.3, qtestcase did not clear currentTestObject
        }
    }
    if(s_test_fail){
        cout << "Failed " << s_test_fail << " of " << s_test_count << " tests.\n";
        cout << s_failed_tests.join("\n").toLocal8Bit().constData() << std::endl;
    }else{
        cout << "Passed " << s_test_count << " tests.\n";
    }
    return result;
}//runTests
References orgQhull::RoadTest::recordFailedTest(), orgQhull::RoadTest::s_failed_tests, orgQhull::RoadTest::s_test_count, orgQhull::RoadTest::s_test_fail, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
t_const_iterator
void orgQhull::QhullPoint_test::t_const_iterator () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q(rcube,"QR0");  // rotated unit cube
        QhullPoint p= q.firstVertex().point();
        QhullPoint::ConstIterator i= p.begin();
        QhullPoint::const_iterator i2= p.begin();
        QVERIFY(i==i2);
        QVERIFY(i>=i2);
        QVERIFY(i<=i2);
        i= p.begin();
        QVERIFY(i==i2);
        i2= p.end();
        QVERIFY(i!=i2);
        double d3= *i;
        i2--;
        double d2= *i2;
        QCOMPARE(d3, p[0]);
        QCOMPARE(d2, p[2]);
        QhullPoint::ConstIterator i3(i2);
        QCOMPARE(*i2, *i3);
        (i3= i)++;
        QCOMPARE((*i3), p[1]);
        QVERIFY(i==i);
        QVERIFY(i!=i2);
        QVERIFY(i<i2);
        QVERIFY(i<=i2);
        QVERIFY(i2>i);
        QVERIFY(i2>=i);
        // See t_iterator for const_iterator COMP iterator
        i= p.begin();
        i2= p.constBegin();
        QCOMPARE(i, i2++);
        QCOMPARE(*i2, p[1]);
        QCOMPARE(++i, i2);
        QCOMPARE(i, i2--);
        QCOMPARE(i2, p.constBegin());
        QCOMPARE(--i, i2);
        QCOMPARE(i2+=3, p.constEnd());
        QCOMPARE(i2-=3, p.constBegin());
        QCOMPARE(i2+0, p.constBegin());
        QCOMPARE(i2+3, p.constEnd());
        i2 += 3;
        i= i2-0;
        QCOMPARE(i, i2);
        i= i2-3;
        QCOMPARE(i, p.constBegin());
        QCOMPARE(i2-i, 3);
        // QhullPoint is const-only
    }
}//t_const_iterator
References orgQhull::QhullPoint::begin(), orgQhull::QhullPoint::constBegin(), orgQhull::QhullPoint::constEnd(), orgQhull::QhullPoint::end(), orgQhull::Qhull::firstVertex(), and orgQhull::QhullVertex::point().
t_construct
void orgQhull::QhullPoint_test::t_construct () private slot
{
    QhullPoint p12;
    QVERIFY(!p12.isValid());
    QCOMPARE(p12.coordinates(), (coordT *)0);
    QCOMPARE(p12.dimension(), 0);
    QCOMPARE(p12.qh(), (QhullQh *)0);
    QCOMPARE(p12.id(), -3);
    QCOMPARE(p12.begin(), p12.end());
    QCOMPARE(p12.constBegin(), p12.constEnd());
    RboxPoints rcube("c");
    Qhull q(rcube, "Qt QR0");  // triangulation of rotated unit cube
    QhullPoint p(q);
    QVERIFY(!p.isValid());
    QCOMPARE(p.dimension(),3);
    QCOMPARE(p.coordinates(),static_cast<double *>(0));
    QhullPoint p7(q.qh());
    QCOMPARE(p, p7);
    // copy constructor and copy assignment
    QhullVertex v2(q.beginVertex());
    QhullPoint p2(v2.point());
    QVERIFY(p2.isValid());
    QCOMPARE(p2.dimension(),3);
    QVERIFY(p2!=p12);
    p= p2;
    QCOMPARE(p, p2);
    QhullPoint p3(q, p2.dimension(), p2.coordinates());
    QCOMPARE(p3, p2);
    QhullPoint p8(q, p2.coordinates()); // Qhull defines dimension
    QCOMPARE(p8, p2);
    QhullPoint p9(q.qh(), p2.dimension(), p2.coordinates());
    QCOMPARE(p9, p2);
    QhullPoint p10(q.qh(), p2.coordinates()); // Qhull defines dimension
    QCOMPARE(p10, p2);
    Coordinates c;
    c << 0.0 << 0.0 << 0.0;
    QhullPoint p6(q, c);
    QCOMPARE(p6, q.origin());
    QhullPoint p11(q.qh(), c);
    QCOMPARE(p11, q.origin());
    QhullPoint p5= p2; // copy constructor
    QVERIFY(p5==p2);
}//t_construct
References orgQhull::QhullPoint::begin(), orgQhull::Qhull::beginVertex(), orgQhull::QhullPoint::constBegin(), orgQhull::QhullPoint::constEnd(), orgQhull::QhullPoint::coordinates(), coordT, orgQhull::QhullPoint::dimension(), orgQhull::QhullPoint::end(), orgQhull::QhullPoint::id(), orgQhull::QhullPoint::isValid(), orgQhull::Qhull::origin(), orgQhull::QhullVertex::point(), orgQhull::QhullPoint::qh(), and orgQhull::Qhull::qh().
t_convert
void orgQhull::QhullPoint_test::t_convert () private slot
{
    RboxPoints rcube("c");
    Qhull q(rcube,"Qt QR0");  // triangulation of rotated unit cube
    QhullVertex v= q.firstVertex();
    QhullPoint p= v.point();
    std::vector<double> vs= p.toStdVector();
    QCOMPARE(vs.size(), 3u);
    for(int k=3; k--; ){
        QCOMPARE(vs[k], p[k]);
    }
    QList<double> qs= p.toQList();
    QCOMPARE(qs.size(), 3);
    for(int k=3; k--; ){
        QCOMPARE(qs[k], p[k]);
    }
}//t_convert
References orgQhull::Qhull::firstVertex(), orgQhull::QhullVertex::point(), and orgQhull::QhullPoint::toStdVector().
t_define
void orgQhull::QhullPoint_test::t_define () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q(rcube,"Qt QR0");  // triangulation of rotated unit cube
        QhullVertexList vs= q.vertexList();
        QhullPoint p= vs.first().point();
        QhullPoint p2= p;
        QVERIFY(p==p2);
        QhullPoint p3= vs.last().point();
        QVERIFY(p2!=p3);
        int idx= (p3.coordinates()-p2.coordinates())/p2.dimension();
        QVERIFY(idx>-8 && idx<8);
        p2.advancePoint(idx);
        QVERIFY(p2==p3);
        p2.advancePoint(-idx);
        QVERIFY(p2==p);
        p2.advancePoint(0);
        QVERIFY(p2==p);
        QhullPoint p4= p3;
        QVERIFY(p4==p3);
        p4.defineAs(p2);
        QVERIFY(p2==p4);
        QhullPoint p5= p3;
        p5.defineAs(p2.dimension(), p2.coordinates());
        QVERIFY(p2==p5);
        QhullPoint p6= p3;
        p6.setCoordinates(p2.coordinates());
        QCOMPARE(p2.coordinates(), p6.coordinates());
        QVERIFY(p2==p6);
        p6.setDimension(2);
        QCOMPARE(p6.dimension(), 2);
        QVERIFY(p2!=p6);
    }
}//t_define
References orgQhull::QhullPoint::advancePoint(), orgQhull::QhullPoint::coordinates(), orgQhull::QhullPoint::defineAs(), orgQhull::QhullPoint::dimension(), orgQhull::QhullLinkedList< T >::first(), orgQhull::QhullLinkedList< T >::last(), orgQhull::QhullPoint::setCoordinates(), orgQhull::QhullPoint::setDimension(), and orgQhull::Qhull::vertexList().
t_io
void orgQhull::QhullPoint_test::t_io () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q(rcube, "");
        QhullPoint p= q.beginVertex().point();
        ostringstream os;
        os << "Point:\n";
        os << p;
        os << "Point w/ print:\n";
        os << p.print(" message ");
        os << p.printWithIdentifier(" Point with id and a message ");
        cout << os.str();
        QString s= QString::fromStdString(os.str());
        QCOMPARE(s.count("p"), 2);
    }
}//t_io
References orgQhull::Qhull::beginVertex(), orgQhull::QhullVertex::point(), orgQhull::QhullPoint::print(), and orgQhull::QhullPoint::printWithIdentifier().
t_iterator
void orgQhull::QhullPoint_test::t_iterator () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q(rcube,"QR0");  // rotated unit cube
        QhullPoint p2(q);
        QCOMPARE(p2.begin(), p2.end());
        QhullPoint p= q.firstVertex().point();
        QhullPoint::Iterator i= p.begin();
        QhullPoint::iterator i2= p.begin();
        QVERIFY(i==i2);
        QVERIFY(i>=i2);
        QVERIFY(i<=i2);
        i= p.begin();
        QVERIFY(i==i2);
        i2= p.end();
        QVERIFY(i!=i2);
        double d3= *i;
        i2--;
        double d2= *i2;
        QCOMPARE(d3, p[0]);
        QCOMPARE(d2, p[2]);
        QhullPoint::Iterator i3(i2);
        QCOMPARE(*i2, *i3);
        (i3= i)++;
        QCOMPARE((*i3), p[1]);
        QVERIFY(i==i);
        QVERIFY(i!=i2);
        QVERIFY(i<i2);
        QVERIFY(i<=i2);
        QVERIFY(i2>i);
        QVERIFY(i2>=i);
        QhullPoint::ConstIterator i4= p.begin();
        QVERIFY(i==i4); // iterator COMP const_iterator
        QVERIFY(i<=i4);
        QVERIFY(i>=i4);
        QVERIFY(i4==i); // const_iterator COMP iterator
        QVERIFY(i4<=i);
        QVERIFY(i4>=i);
        QVERIFY(i>=i4);
        QVERIFY(i4<=i);
        QVERIFY(i2!=i4);
        QVERIFY(i2>i4);
        QVERIFY(i2>=i4);
        QVERIFY(i4!=i2);
        QVERIFY(i4<i2);
        QVERIFY(i4<=i2);
        ++i4;
        QVERIFY(i<i4);
        QVERIFY(i<=i4);
        QVERIFY(i4>i);
        QVERIFY(i4>=i);
        i= p.begin();
        i2= p.begin();
        QCOMPARE(i, i2++);
        QCOMPARE(*i2, p[1]);
        QCOMPARE(++i, i2);
        QCOMPARE(i, i2--);
        QCOMPARE(i2, p.begin());
        QCOMPARE(--i, i2);
        QCOMPARE(i2 += 3, p.end());
        QCOMPARE(i2 -= 3, p.begin());
        QCOMPARE(i2+0, p.begin());
        QCOMPARE(i2+3, p.end());
        i2 += 3;
        i= i2-0;
        QCOMPARE(i, i2);
        i= i2-3;
        QCOMPARE(i, p.begin());
        QCOMPARE(i2-i, 3);
        //p.begin end tested above
        // QhullPoint is const-only
    }
}//t_iterator
References orgQhull::QhullPoint::begin(), orgQhull::QhullPoint::end(), orgQhull::Qhull::firstVertex(), and orgQhull::QhullVertex::point().
t_method
void orgQhull::QhullPoint_test::t_method () private slot
{
    // advancePoint tested above
    RboxPoints rcube("c");
    Qhull q(rcube, "");
    QhullPoint p = q.firstVertex().point();
    double dist= p.distance(q.origin());
    QCOMPARE(dist, sqrt(double(2.0+1.0))/2); // half diagonal of unit cube
}//t_qhullpoint_iterator
References orgQhull::QhullPoint::distance(), orgQhull::Qhull::firstVertex(), orgQhull::Qhull::origin(), orgQhull::QhullVertex::point(), and sqrt().
t_operator
void orgQhull::QhullPoint_test::t_operator () private slot
{
    RboxPoints rcube("c");
    Qhull q(rcube,"Qt QR0");  // triangulation of rotated unit cube
    const QhullPoint p= q.firstVertex().point();
    //operator== and operator!= tested elsewhere
    const coordT *c= p.coordinates();
    for(int k=p.dimension(); k--; ){
        QCOMPARE(c[k], p[k]);
    }
    //p[0]= 10.0; // compiler error, const
    QhullPoint p2= q.firstVertex().point();
    p2[0]= 10.0;  // Overwrites point coordinate
    QCOMPARE(p2[0], 10.0);
}//t_operator
References orgQhull::QhullPoint::coordinates(), coordT, orgQhull::QhullPoint::dimension(), orgQhull::Qhull::firstVertex(), and orgQhull::QhullVertex::point().
t_qhullpoint_iterator
void orgQhull::QhullPoint_test::t_qhullpoint_iterator () private slot
{
    RboxPoints rcube("c");
    Qhull q(rcube,"QR0");  // rotated unit cube
    QhullPoint p2(q);
    QhullPointIterator i= p2;
    QCOMPARE(p2.dimension(), 3);
    QVERIFY(!i.hasNext());
    QVERIFY(!i.hasPrevious());
    i.toBack();
    QVERIFY(!i.hasNext());
    QVERIFY(!i.hasPrevious());
    QhullPoint p = q.firstVertex().point();
    QhullPointIterator i2(p);
    QCOMPARE(p.dimension(), 3);
    i= p;
    QVERIFY(i2.hasNext());
    QVERIFY(!i2.hasPrevious());
    QVERIFY(i.hasNext());
    QVERIFY(!i.hasPrevious());
    i2.toBack();
    i.toFront();
    QVERIFY(!i2.hasNext());
    QVERIFY(i2.hasPrevious());
    QVERIFY(i.hasNext());
    QVERIFY(!i.hasPrevious());
    // i at front, i2 at end/back, 3 coordinates
    QCOMPARE(i.peekNext(), p[0]);
    QCOMPARE(i2.peekPrevious(), p[2]);
    QCOMPARE(i2.previous(), p[2]);
    QCOMPARE(i2.previous(), p[1]);
    QCOMPARE(i2.previous(), p[0]);
    QVERIFY(!i2.hasPrevious());
    QCOMPARE(i.peekNext(), p[0]);
    // i.peekNext()= 1.0; // compiler error, i is const
    QCOMPARE(i.next(), p[0]);
    QCOMPARE(i.peekNext(), p[1]);
    QCOMPARE(i.next(), p[1]);
    QCOMPARE(i.next(), p[2]);
    QVERIFY(!i.hasNext());
    i.toFront();
    QCOMPARE(i.next(), p[0]);
}//t_qhullpoint_iterator
References orgQhull::QhullPoint::dimension(), orgQhull::Qhull::firstVertex(), and orgQhull::QhullVertex::point().
t_readonly
void orgQhull::QhullPoint_test::t_readonly () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q(rcube,"Qt QR0");  // triangulation of rotated unit cube
        QhullVertexList vs= q.vertexList();
        cout << "Point ids in 'rbox c'\n";
        QhullVertexListIterator i(vs);
        while(i.hasNext()){
            QhullPoint p= i.next().point();
            int id= p.id();
            cout << "p" << id << endl;
            QVERIFY(p.isValid());
            QCOMPARE(p.dimension(),3);
            QCOMPARE(id, p.id());
            QVERIFY(p.id()>=0 && p.id()<9);
            const coordT *c= p.coordinates();
            coordT *c2= p.coordinates();
            QCOMPARE(c, c2);
            QCOMPARE(p.dimension(), 3);
            QCOMPARE(q.qh(), p.qh());
        }
        QhullPoint p2= vs.first().point();
        QhullPoint p3= vs.last().point();
        QVERIFY(p2!=p3);
        QVERIFY(p3.coordinates()!=p2.coordinates());
    }
}//t_readonly
References orgQhull::QhullPoint::coordinates(), coordT, orgQhull::QhullPoint::dimension(), orgQhull::QhullLinkedList< T >::first(), orgQhull::QhullLinkedListIterator< T >::hasNext(), orgQhull::QhullPoint::id(), orgQhull::QhullPoint::isValid(), orgQhull::QhullLinkedList< T >::last(), orgQhull::QhullLinkedListIterator< T >::next(), orgQhull::QhullPoint::qh(), orgQhull::Qhull::qh(), and orgQhull::Qhull::vertexList().
Member Data Documentation
s_failed_tests
QStringList orgQhull::RoadTest::s_failed_tests static protected inherited
! Number of failed tests
Referenced by orgQhull::RoadTest::deleteTests(), orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_test_count
int orgQhull::RoadTest::s_test_count = 0 static protected inherited
! List of testcases to execute. Initialized via add_...()
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
s_test_fail
int orgQhull::RoadTest::s_test_fail = 0 static protected inherited
! Total number of tests executed
Referenced by orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_testcases
QList< RoadTest * > orgQhull::RoadTest::s_testcases static protected inherited
Referenced by orgQhull::RoadTest::RoadTest(), orgQhull::RoadTest::deleteTests(), and orgQhull::RoadTest::runTests().
The documentation for this class was generated from the following file:
src/qhull/src/qhulltest/QhullPoint_test.cpp