OrcaSlicer: Slic3r::GLWipeTowerVolume Class Reference
Slic3r::GLWipeTowerVolume Class Reference
#include <src/slic3r/GUI/3DScene.hpp>
Public Types
enum EHoverState : unsigned char { HS_None , HS_Hover , HS_Select , HS_Deselect }
Public Member Functions
GLWipeTowerVolume (const std::vector< std::array< float, 4 > > &colors)
virtual void render (bool with_outline=false) const
bool IsTransparent ()
BoundingBoxf3 bounding_box () const
void set_color (const std::array< float, 4 > &rgba)
void set_render_color (float r, float g, float b, float a)
void set_render_color (const std::array< float, 4 > &rgba)
void set_render_color ()
void set_color_from_model_volume (const ModelVolume &model_volume)
const Geometry::Transformation & get_instance_transformation () const
void set_instance_transformation (const Geometry::Transformation &transformation)
const Vec3d & get_instance_offset () const
double get_instance_offset (Axis axis) const
void set_instance_offset (const Vec3d &offset)
void set_instance_offset (Axis axis, double offset)
const Vec3d & get_instance_rotation () const
double get_instance_rotation (Axis axis) const
void set_instance_rotation (const Vec3d &rotation)
void set_instance_rotation (Axis axis, double rotation)
Vec3d get_instance_scaling_factor () const
double get_instance_scaling_factor (Axis axis) const
void set_instance_scaling_factor (const Vec3d &scaling_factor)
void set_instance_scaling_factor (Axis axis, double scaling_factor)
const Vec3d & get_instance_mirror () const
double get_instance_mirror (Axis axis) const
void set_instance_mirror (const Vec3d &mirror)
void set_instance_mirror (Axis axis, double mirror)
const Geometry::Transformation & get_volume_transformation () const
void set_volume_transformation (const Geometry::Transformation &transformation)
const Vec3d & get_volume_offset () const
double get_volume_offset (Axis axis) const
void set_volume_offset (const Vec3d &offset)
void set_volume_offset (Axis axis, double offset)
const Vec3d & get_volume_rotation () const
double get_volume_rotation (Axis axis) const
void set_volume_rotation (const Vec3d &rotation)
void set_volume_rotation (Axis axis, double rotation)
const Vec3d & get_volume_scaling_factor () const
double get_volume_scaling_factor (Axis axis) const
void set_volume_scaling_factor (const Vec3d &scaling_factor)
void set_volume_scaling_factor (Axis axis, double scaling_factor)
const Vec3d & get_volume_mirror () const
double get_volume_mirror (Axis axis) const
void set_volume_mirror (const Vec3d &mirror)
void set_volume_mirror (Axis axis, double mirror)
double get_sla_shift_z () const
void set_sla_shift_z (double z)
void set_convex_hull (std::shared_ptr< const TriangleMesh > convex_hull)
void set_convex_hull (const TriangleMesh &convex_hull)
void set_convex_hull (TriangleMesh &&convex_hull)
void set_offset_to_assembly (const Vec3d &offset)
Vec3d get_offset_to_assembly ()
int object_idx () const
int volume_idx () const
int instance_idx () const
Transform3d world_matrix () const
bool is_left_handed () const
const BoundingBoxf3 & transformed_bounding_box () const
BoundingBoxf3 transformed_convex_hull_bounding_box (const Transform3d &trafo) const
const BoundingBoxf3 & transformed_convex_hull_bounding_box () const
BoundingBoxf3 transformed_non_sinking_bounding_box (const Transform3d &trafo) const
const BoundingBoxf3 & transformed_non_sinking_bounding_box () const
const TriangleMesh * convex_hull () const
bool empty () const
void set_range (double low, double high)
void simple_render (GLShaderProgram *shader, ModelObjectPtrs &model_objects, std::vector< std::array< float, 4 > > &extruder_colors) const
void finalize_geometry (bool opengl_initialized)
void release_geometry ()
void set_bounding_boxes_as_dirty ()
bool is_sla_support () const
bool is_sla_pad () const
bool is_sinking () const
bool is_below_printbed () const
void render_sinking_contours ()
size_t cpu_memory_used () const
size_t gpu_memory_used () const
size_t total_memory_used () const
Static Public Member Functions
static void update_render_colors ()
static void load_render_colors ()
Public Attributes
std::vector< GLIndexedVertexArray > iva_per_colors
std::string name
std::array< float, 4 > color
std::array< float, 4 > render_color
CompositeID composite_id
std::pair< size_t, size_t > geometry_id
int extruder_id
size_t model_object_ID {0}
struct {
bool selected: 1
bool disabled: 1
bool printable: 1
bool visible: 1
bool is_active: 1
bool zoom_to_volumes: 1
bool shader_outside_printer_detection_enabled: 1
bool is_outside: 1
bool partly_inside: 1
bool is_modifier: 1
bool is_wipe_tower: 1
bool is_extrusion_path: 1
bool force_transparent: 1
bool force_native_color: 1
bool force_neutral_color: 1
bool force_sinking_contours: 1
};
EHoverState hover
GLIndexedVertexArray indexed_vertex_array
std::vector< GLIndexedVertexArray > mmuseg_ivas
ObjectBase::Timestamp mmuseg_ts
std::pair< size_t, size_t > tverts_range
std::pair< size_t, size_t > qverts_range
std::vector< coordf_t > print_zs
std::vector< size_t > offsets
Static Public Attributes
static std::array< float, 4 > DISABLED_COLOR = { 0.25f, 0.25f, 0.25f, 1.0f }
static std::array< float, 4 > SLA_SUPPORT_COLOR = { 0.75f, 0.75f, 0.75f, 1.0f }
static std::array< float, 4 > SLA_PAD_COLOR = { 0.0f, 0.2f, 0.0f, 1.0f }
static std::array< float, 4 > NEUTRAL_COLOR = { 0.8f, 0.8f, 0.8f, 1.0f }
static std::array< float, 4 > UNPRINTABLE_COLOR = { 0.0f, 0.0f, 0.0f, 0.5f }
static std::array< std::array< float, 4 >, 5 > MODEL_COLOR
static std::array< float, 4 > MODEL_MIDIFIER_COL = {1.0f, 1.0f, 0.0f, 0.6f}
static std::array< float, 4 > MODEL_NEGTIVE_COL = {0.3f, 0.3f, 0.3f, 0.4f}
static std::array< float, 4 > SUPPORT_ENFORCER_COL = {0.3f, 0.3f, 1.0f, 0.4f}
static std::array< float, 4 > SUPPORT_BLOCKER_COL = {1.0f, 0.3f, 0.3f, 0.4f}
static std::array< float, 4 > MODEL_HIDDEN_COL = {0.f, 0.f, 0.f, 0.3f}
static float explosion_ratio = 1.0
static float last_explosion_ratio = 1.0
Protected Attributes
Geometry::Transformation m_instance_transformation
Geometry::Transformation m_volume_transformation
Vec3d m_offset_to_assembly { 0.0, 0.0, 0.0 }
double m_sla_shift_z
std::optional< BoundingBoxf3 > m_transformed_bounding_box
std::shared_ptr< const TriangleMesh > m_convex_hull
std::optional< BoundingBoxf3 > m_transformed_convex_hull_bounding_box
std::optional< BoundingBoxf3 > m_transformed_non_sinking_bounding_box
SinkingContours m_sinking_contours
Private Attributes
std::vector< std::array< float, 4 > > m_colors
Detailed Description
Member Enumeration Documentation
EHoverState
enum Slic3r::GLVolume::EHoverState : unsigned char inherited
Enumerator
HS_None
HS_Hover
HS_Select
HS_Deselect
    {
        HS_None,
        HS_Hover,
        HS_Select,
        HS_Deselect
    };
Constructor & Destructor Documentation
GLWipeTowerVolume()
Slic3r::GLWipeTowerVolume::GLWipeTowerVolume (const std::vector< std::array< float, 4 > > & colors)
    : GLVolume()
{
    m_colors = colors;
}
References m_colors.
Member Function Documentation
bounding_box()
BoundingBoxf3 Slic3r::GLVolume::bounding_box () const inline inherited
{
        BoundingBoxf3 out;
        if (! this->indexed_vertex_array.bounding_box().isEmpty()) {
            out.min = this->indexed_vertex_array.bounding_box().min().cast<double>();
            out.max = this->indexed_vertex_array.bounding_box().max().cast<double>();
            out.defined = true;
        };
        return out;
    }
References Slic3r::GLIndexedVertexArray::bounding_box(), Eigen::AlignedBox< _Scalar, _AmbientDim >::isEmpty(), Eigen::AlignedBox< _Scalar, _AmbientDim >::max(), Eigen::AlignedBox< _Scalar, _AmbientDim >::min(), and out.
Referenced by Slic3r::GUI::GizmoObjectManipulation::change_size_value(), Slic3r::GUI::PartPlate::contains(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GLVolume::transformed_bounding_box(), Slic3r::GLVolume::transformed_convex_hull_bounding_box(), and Slic3r::GUI::Selection::translate().
convex_hull()
const TriangleMesh * Slic3r::GLVolume::convex_hull () const inline inherited
{ return m_convex_hull.get(); }
References Slic3r::GLVolume::m_convex_hull.
Referenced by Slic3r::GLVolume::set_convex_hull(), Slic3r::GLVolume::set_convex_hull(), and Slic3r::GLVolume::set_convex_hull().
cpu_memory_used()
size_t Slic3r::GLVolume::cpu_memory_used () const inline inherited
{
      //FIXME what to do wih m_convex_hull?
      return sizeof(*this) - sizeof(this->indexed_vertex_array) + this->indexed_vertex_array.cpu_memory_used() + this->print_zs.capacity() * sizeof(coordf_t) + this->offsets.capacity() * sizeof(size_t);
    }
References Slic3r::GLIndexedVertexArray::cpu_memory_used(), and Slic3r::GLVolume::indexed_vertex_array.
Referenced by Slic3r::GLVolume::total_memory_used().
empty()
bool Slic3r::GLVolume::empty () const inline inherited
{ return this->indexed_vertex_array.empty(); }
References Slic3r::GLIndexedVertexArray::empty().
finalize_geometry()
void Slic3r::GLVolume::finalize_geometry (bool opengl_initialized) inline inherited
{ this->indexed_vertex_array.finalize_geometry(opengl_initialized); }
References Slic3r::GLIndexedVertexArray::finalize_geometry().
Referenced by Slic3r::GUI::reserve_new_volume_finalize_old_volume().
get_instance_mirror() [1/2]
const Vec3d & Slic3r::GLVolume::get_instance_mirror () const inline inherited
{ return m_instance_transformation.get_mirror(); }
References Slic3r::Geometry::Transformation::get_mirror(), and Slic3r::GLVolume::m_instance_transformation.
Referenced by Slic3r::GUI::Selection::mirror(), and Slic3r::GUI::GLGizmoScale3D::on_render().
get_instance_mirror() [2/2]
double Slic3r::GLVolume::get_instance_mirror (Axis axis) const inline inherited
{ return m_instance_transformation.get_mirror(axis); }
References Slic3r::Geometry::Transformation::get_mirror(), and Slic3r::GLVolume::m_instance_transformation.
get_instance_offset() [1/2]
const Vec3d & Slic3r::GLVolume::get_instance_offset () const inline inherited
{ return m_instance_transformation.get_offset(); }
References Slic3r::Geometry::Transformation::get_offset(), and Slic3r::GLVolume::m_instance_transformation.
Referenced by Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::Selection::translate(), and Slic3r::GUI::Selection::translate().
get_instance_offset() [2/2]
double Slic3r::GLVolume::get_instance_offset (Axis axis) const inline inherited
{ return m_instance_transformation.get_offset(axis); }
References Slic3r::Geometry::Transformation::get_offset(), and Slic3r::GLVolume::m_instance_transformation.
get_instance_rotation() [1/2]
const Vec3d & Slic3r::GLVolume::get_instance_rotation () const inline inherited
{ return m_instance_transformation.get_rotation(); }
References Slic3r::Geometry::Transformation::get_rotation(), and Slic3r::GLVolume::m_instance_transformation.
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale(), and Slic3r::GUI::Selection::synchronize_unselected_instances().
get_instance_rotation() [2/2]
double Slic3r::GLVolume::get_instance_rotation (Axis axis) const inline inherited
{ return m_instance_transformation.get_rotation(axis); }
References Slic3r::Geometry::Transformation::get_rotation(), and Slic3r::GLVolume::m_instance_transformation.
get_instance_scaling_factor() [1/2]
Vec3d Slic3r::GLVolume::get_instance_scaling_factor () const inline inherited
{ return m_instance_transformation.get_scaling_factor(); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and Slic3r::GLVolume::m_instance_transformation.
Referenced by Slic3r::GUI::GLGizmoScale3D::get_tooltip(), and Slic3r::GUI::Selection::scale().
get_instance_scaling_factor() [2/2]
double Slic3r::GLVolume::get_instance_scaling_factor (Axis axis) const inline inherited
{ return m_instance_transformation.get_scaling_factor(axis); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and Slic3r::GLVolume::m_instance_transformation.
get_instance_transformation()
const Geometry::Transformation & Slic3r::GLVolume::get_instance_transformation () const inline inherited
{ return m_instance_transformation; }
References Slic3r::GLVolume::m_instance_transformation.
Referenced by Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::Selection::scale(), Slic3r::GUI::Selection::set_caches(), Slic3r::GUI::GLGizmoRotate::transform_to_local(), and Slic3r::GUI::GLGizmoCut::update_contours().
get_offset_to_assembly()
Vec3d Slic3r::GLVolume::get_offset_to_assembly () inline inherited
{ return m_offset_to_assembly; }
References Slic3r::GLVolume::m_offset_to_assembly.
get_sla_shift_z()
double Slic3r::GLVolume::get_sla_shift_z () const inline inherited
{ return m_sla_shift_z; }
References Slic3r::GLVolume::m_sla_shift_z.
Referenced by Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), and Slic3r::GUI::GLGizmoCut::perform_cut().
get_volume_mirror() [1/2]
const Vec3d & Slic3r::GLVolume::get_volume_mirror () const inline inherited
{ return m_volume_transformation.get_mirror(); }
References Slic3r::Geometry::Transformation::get_mirror(), and Slic3r::GLVolume::m_volume_transformation.
Referenced by Slic3r::GUI::Selection::mirror(), and Slic3r::GUI::GLGizmoScale3D::on_render().
get_volume_mirror() [2/2]
double Slic3r::GLVolume::get_volume_mirror (Axis axis) const inline inherited
{ return m_volume_transformation.get_mirror(axis); }
References Slic3r::Geometry::Transformation::get_mirror(), and Slic3r::GLVolume::m_volume_transformation.
get_volume_offset() [1/2]
const Vec3d & Slic3r::GLVolume::get_volume_offset () const inline inherited
{ return m_volume_transformation.get_offset(); }
References Slic3r::Geometry::Transformation::get_offset(), and Slic3r::GLVolume::m_volume_transformation.
Referenced by Slic3r::GUI::GCodeViewer::load_shells().
get_volume_offset() [2/2]
double Slic3r::GLVolume::get_volume_offset (Axis axis) const inline inherited
{ return m_volume_transformation.get_offset(axis); }
References Slic3r::Geometry::Transformation::get_offset(), and Slic3r::GLVolume::m_volume_transformation.
get_volume_rotation() [1/2]
const Vec3d & Slic3r::GLVolume::get_volume_rotation () const inline inherited
{ return m_volume_transformation.get_rotation(); }
References Slic3r::Geometry::Transformation::get_rotation(), and Slic3r::GLVolume::m_volume_transformation.
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
get_volume_rotation() [2/2]
double Slic3r::GLVolume::get_volume_rotation (Axis axis) const inline inherited
{ return m_volume_transformation.get_rotation(axis); }
References Slic3r::Geometry::Transformation::get_rotation(), and Slic3r::GLVolume::m_volume_transformation.
get_volume_scaling_factor() [1/2]
const Vec3d & Slic3r::GLVolume::get_volume_scaling_factor () const inline inherited
{ return m_volume_transformation.get_scaling_factor(); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and Slic3r::GLVolume::m_volume_transformation.
get_volume_scaling_factor() [2/2]
double Slic3r::GLVolume::get_volume_scaling_factor (Axis axis) const inline inherited
{ return m_volume_transformation.get_scaling_factor(axis); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and Slic3r::GLVolume::m_volume_transformation.
get_volume_transformation()
const Geometry::Transformation & Slic3r::GLVolume::get_volume_transformation () const inline inherited
{ return m_volume_transformation; }
References Slic3r::GLVolume::m_volume_transformation.
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render(), and Slic3r::GUI::Selection::set_caches().
gpu_memory_used()
size_t Slic3r::GLVolume::gpu_memory_used () const inline inherited
{ return this->indexed_vertex_array.gpu_memory_used(); }
References Slic3r::GLIndexedVertexArray::gpu_memory_used().
Referenced by Slic3r::GLVolume::total_memory_used().
instance_idx()
int Slic3r::GLVolume::instance_idx () const inline inherited
{ return this->composite_id.instance_id; }
References Slic3r::GLVolume::CompositeID::instance_id.
Referenced by Slic3r::GUI::GLCanvas3D::_update_selection_from_hover(), Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), Slic3r::GUI::Selection::do_remove_instance(), Slic3r::GUI::Selection::get_volume_idxs_from_instance(), Slic3r::GUI::Selection::get_volume_idxs_from_volume(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::scale(), Slic3r::GUI::Selection::synchronize_unselected_instances(), and Slic3r::GUI::Selection::translate().
is_below_printbed()
bool Slic3r::GLVolume::is_below_printbed () const inherited
{
    return transformed_convex_hull_bounding_box().max.z() < 0.0;
}
References Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::GLVolume::transformed_convex_hull_bounding_box().
Referenced by Slic3r::GLVolume::set_render_color().
is_left_handed()
bool Slic3r::GLVolume::is_left_handed () const inherited
{
    const Vec3d &m1 = m_instance_transformation.get_mirror();
    const Vec3d &m2 = m_volume_transformation.get_mirror();
    return m1.x() * m1.y() * m1.z() * m2.x() * m2.y() * m2.z() < 0.;
}
References Slic3r::Geometry::Transformation::get_mirror(), Slic3r::GLVolume::m_instance_transformation, and Slic3r::GLVolume::m_volume_transformation.
Referenced by Slic3r::GLVolume::render(), render(), and Slic3r::GLVolume::simple_render().
is_sinking()
bool Slic3r::GLVolume::is_sinking () const inherited
{
    if (is_modifier || GUI::wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA)
        return false;
    const BoundingBoxf3& box = transformed_convex_hull_bounding_box();
    return box.min.z() < SINKING_Z_THRESHOLD && box.max.z() >= SINKING_Z_THRESHOLD;
}
References Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::ptSLA, Slic3r::SINKING_Z_THRESHOLD, and Slic3r::GLVolume::transformed_convex_hull_bounding_box().
Referenced by Slic3r::GUI::Selection::set_caches().
is_sla_pad()
bool Slic3r::GLVolume::is_sla_pad () const inherited
{ return this->composite_id.volume_id == -int(slaposPad); }
References Slic3r::GLVolume::composite_id, int, Slic3r::slaposPad, and Slic3r::GLVolume::CompositeID::volume_id.
is_sla_support()
bool Slic3r::GLVolume::is_sla_support () const inherited
{ return this->composite_id.volume_id == -int(slaposSupportTree); }
References Slic3r::GLVolume::composite_id, int, Slic3r::slaposSupportTree, and Slic3r::GLVolume::CompositeID::volume_id.
IsTransparent()
bool Slic3r::GLWipeTowerVolume::IsTransparent ()
{
    for (size_t i = 0; i < m_colors.size(); i++) {
        if (m_colors[i][3] < 1.0f) {
            return true;
        }
    }
    return false;
}
References m_colors.
Referenced by Slic3r::volumes_to_render().
load_render_colors()
void Slic3r::GLVolume::load_render_colors () static inherited
{
    RenderColor::colors[RenderCol_Model_Disable]    = IMColor(GLVolume::DISABLED_COLOR);
    RenderColor::colors[RenderCol_Model_Neutral]    = IMColor(GLVolume::NEUTRAL_COLOR);
    RenderColor::colors[RenderCol_Modifier]         = IMColor(GLVolume::MODEL_COLOR[0]);
    RenderColor::colors[RenderCol_Negtive_Volume]   = IMColor(GLVolume::MODEL_COLOR[1]);
    RenderColor::colors[RenderCol_Support_Enforcer] = IMColor(GLVolume::MODEL_COLOR[2]);
    RenderColor::colors[RenderCol_Support_Blocker]  = IMColor(GLVolume::MODEL_COLOR[3]);
    RenderColor::colors[RenderCol_Model_Unprintable]= IMColor(GLVolume::UNPRINTABLE_COLOR);
}
References Slic3r::RenderColor::colors, Slic3r::GLVolume::DISABLED_COLOR, Slic3r::IMColor(), Slic3r::GLVolume::MODEL_COLOR, Slic3r::GLVolume::NEUTRAL_COLOR, RenderCol_Model_Disable, RenderCol_Model_Neutral, RenderCol_Model_Unprintable, RenderCol_Modifier, RenderCol_Negtive_Volume, RenderCol_Support_Blocker, RenderCol_Support_Enforcer, and Slic3r::GLVolume::UNPRINTABLE_COLOR.
Referenced by Slic3r::GUI::GLCanvas3D::init().
object_idx()
int Slic3r::GLVolume::object_idx () const inline inherited
{ return this->composite_id.object_id; }
References Slic3r::GLVolume::CompositeID::object_id.
Referenced by Slic3r::GUI::GLCanvas3D::_update_selection_from_hover(), Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::GizmoObjectManipulation::change_size_value(), Slic3r::GUI::Selection::do_remove_instance(), Slic3r::GUI::Selection::do_remove_object(), Slic3r::GUI::Selection::erase(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::Selection::get_volume_idxs_from_instance(), Slic3r::GUI::Selection::get_volume_idxs_from_volume(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::Selection::remove_volume(), Slic3r::GLVolume::render(), Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::Selection::scale(), Slic3r::GLVolume::simple_render(), Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::GUI::Selection::synchronize_unselected_volumes(), Slic3r::GLVolume::transformed_non_sinking_bounding_box(), Slic3r::GUI::Selection::translate(), Slic3r::GUI::Selection::translate(), Slic3r::GUI::Selection::translate(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::Selection::update_type().
release_geometry()
void Slic3r::GLVolume::release_geometry () inline inherited
{ this->indexed_vertex_array.release_geometry(); }
References Slic3r::GLIndexedVertexArray::release_geometry().
render()
void Slic3r::GLWipeTowerVolume::render (bool with_outline = false) const virtual
Reimplemented from Slic3r::GLVolume.
{
    if (!is_active)
        return;
    if (m_colors.size() == 0 || m_colors.size() != iva_per_colors.size())
        return;
    if (this->is_left_handed())
        glFrontFace(GL_CW);
    glsafe(::glCullFace(GL_BACK));
    glsafe(::glPushMatrix());
    glsafe(::glMultMatrixd(world_matrix().data()));
    GLShaderProgram* shader = GUI::wxGetApp().get_current_shader();
    for (int i = 0; i < m_colors.size(); i++) {
        if (shader) {
            std::array<float, 4> new_color = adjust_color_for_rendering(m_colors[i]);
            shader->set_uniform("uniform_color", new_color);
        }
        this->iva_per_colors[i].render();
    }
    glsafe(::glPopMatrix());
    if (this->is_left_handed())
        glFrontFace(GL_CCW);
}
References adjust_color_for_rendering(), glsafe, Slic3r::GLVolume::is_left_handed(), iva_per_colors, m_colors, Slic3r::GLShaderProgram::set_uniform(), and Slic3r::GLVolume::world_matrix().
render_sinking_contours()
void Slic3r::GLVolume::render_sinking_contours () inherited
{
    m_sinking_contours.render();
}
References Slic3r::GLVolume::m_sinking_contours, and Slic3r::GLVolume::SinkingContours::render().
set_bounding_boxes_as_dirty()
void Slic3r::GLVolume::set_bounding_boxes_as_dirty () inline inherited
{
        m_transformed_bounding_box.reset();
        m_transformed_convex_hull_bounding_box.reset();
        m_transformed_non_sinking_bounding_box.reset();
    }
References Slic3r::GLVolume::m_transformed_bounding_box, Slic3r::GLVolume::m_transformed_convex_hull_bounding_box, and Slic3r::GLVolume::m_transformed_non_sinking_bounding_box.
Referenced by Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::GLVolume::set_instance_transformation(), Slic3r::GLVolume::set_offset_to_assembly(), Slic3r::GLVolume::set_volume_mirror(), Slic3r::GLVolume::set_volume_mirror(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_rotation(), Slic3r::GLVolume::set_volume_rotation(), Slic3r::GLVolume::set_volume_scaling_factor(), Slic3r::GLVolume::set_volume_scaling_factor(), and Slic3r::GLVolume::set_volume_transformation().
set_color()
void Slic3r::GLVolume::set_color (const std::array< float, 4 > & rgba) inherited
{
    color = rgba;
}
References Slic3r::GLVolume::color.
Referenced by Slic3r::GLVolumeCollection::load_object_volume().
set_color_from_model_volume()
void Slic3r::GLVolume::set_color_from_model_volume (const ModelVolume & model_volume) inherited
set_convex_hull() [1/3]
void Slic3r::GLVolume::set_convex_hull (const TriangleMesh & convex_hull) inline inherited
{ m_convex_hull = std::make_shared<const TriangleMesh>(convex_hull); }
References Slic3r::GLVolume::convex_hull(), and Slic3r::GLVolume::m_convex_hull.
set_convex_hull() [2/3]
void Slic3r::GLVolume::set_convex_hull (std::shared_ptr< const TriangleMesh > convex_hull) inline inherited
{ m_convex_hull = std::move(convex_hull); }
References Slic3r::GLVolume::convex_hull(), and Slic3r::GLVolume::m_convex_hull.
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), and Slic3r::GLVolumeCollection::load_wipe_tower_preview().
set_convex_hull() [3/3]
void Slic3r::GLVolume::set_convex_hull (TriangleMesh && convex_hull) inline inherited
{ m_convex_hull = std::make_shared<const TriangleMesh>(std::move(convex_hull)); }
References Slic3r::GLVolume::convex_hull(), and Slic3r::GLVolume::m_convex_hull.
set_instance_mirror() [1/2]
void Slic3r::GLVolume::set_instance_mirror (Axis axis, double mirror) inline inherited
{ m_instance_transformation.set_mirror(axis, mirror); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_mirror().
set_instance_mirror() [2/2]
void Slic3r::GLVolume::set_instance_mirror (const Vec3d & mirror) inline inherited
{ m_instance_transformation.set_mirror(mirror); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_mirror().
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GUI::Selection::mirror(), and Slic3r::GUI::Selection::synchronize_unselected_instances().
set_instance_offset() [1/2]
void Slic3r::GLVolume::set_instance_offset (Axis axis, double offset) inline inherited
{ m_instance_transformation.set_offset(axis, offset); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, Slic3r::offset(), Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_offset().
set_instance_offset() [2/2]
void Slic3r::GLVolume::set_instance_offset (const Vec3d & offset) inline inherited
{ m_instance_transformation.set_offset(offset); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, Slic3r::offset(), Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_offset().
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GUI::Selection::move_to_center(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale(), Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::GUI::Selection::translate(), Slic3r::GUI::Selection::translate(), and Slic3r::GUI::Selection::translate().
set_instance_rotation() [1/2]
void Slic3r::GLVolume::set_instance_rotation (Axis axis, double rotation) inline inherited
{ m_instance_transformation.set_rotation(axis, rotation); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_rotation().
set_instance_rotation() [2/2]
void Slic3r::GLVolume::set_instance_rotation (const Vec3d & rotation) inline inherited
{ m_instance_transformation.set_rotation(rotation); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_rotation().
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GUI::Selection::flattening_rotate(), Slic3r::GUI::Selection::rotate(), and Slic3r::GUI::Selection::synchronize_unselected_instances().
set_instance_scaling_factor() [1/2]
void Slic3r::GLVolume::set_instance_scaling_factor (Axis axis, double scaling_factor) inline inherited
{ m_instance_transformation.set_scaling_factor(axis, scaling_factor); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_scaling_factor().
set_instance_scaling_factor() [2/2]
void Slic3r::GLVolume::set_instance_scaling_factor (const Vec3d & scaling_factor) inline inherited
{ m_instance_transformation.set_scaling_factor(scaling_factor); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_scaling_factor().
Referenced by Slic3r::GUI::Selection::scale(), and Slic3r::GUI::Selection::synchronize_unselected_instances().
set_instance_transformation()
void Slic3r::GLVolume::set_instance_transformation (const Geometry::Transformation & transformation) inline inherited
{ m_instance_transformation = transformation; set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_instance_transformation, and Slic3r::GLVolume::set_bounding_boxes_as_dirty().
Referenced by Slic3r::GLVolumeCollection::load_object_auxiliary(), and Slic3r::GLVolumeCollection::load_object_volume().
set_offset_to_assembly()
void Slic3r::GLVolume::set_offset_to_assembly (const Vec3d & offset) inline inherited
{ m_offset_to_assembly = offset; set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_offset_to_assembly, Slic3r::offset(), and Slic3r::GLVolume::set_bounding_boxes_as_dirty().
Referenced by Slic3r::GLVolumeCollection::load_object_volume().
set_range()
void Slic3r::GLVolume::set_range (double low, double high) inherited
{
    this->qverts_range.first = 0;
    this->qverts_range.second = this->indexed_vertex_array.quad_indices_size;
    this->tverts_range.first = 0;
    this->tverts_range.second = this->indexed_vertex_array.triangle_indices_size;
    if (! this->print_zs.empty()) {
        // The Z layer range is specified.
        // First test whether the Z span of this object is not out of (min_z, max_z) completely.
        if (this->print_zs.front() > max_z || this->print_zs.back() < min_z) {
            this->qverts_range.second = 0;
            this->tverts_range.second = 0;
        } else {
            // Then find the lowest layer to be displayed.
            size_t i = 0;
            for (; i < this->print_zs.size() && this->print_zs[i] < min_z; ++ i);
            if (i == this->print_zs.size()) {
                // This shall not happen.
                this->qverts_range.second = 0;
                this->tverts_range.second = 0;
            } else {
                // Remember start of the layer.
                this->qverts_range.first = this->offsets[i * 2];
                this->tverts_range.first = this->offsets[i * 2 + 1];
                // Some layers are above $min_z. Which?
                for (; i < this->print_zs.size() && this->print_zs[i] <= max_z; ++ i);
                if (i < this->print_zs.size()) {
                    this->qverts_range.second = this->offsets[i * 2];
                    this->tverts_range.second = this->offsets[i * 2 + 1];
                }
            }
        }
    }
}
References Slic3r::GLVolume::indexed_vertex_array, Slic3r::GLVolume::offsets, Slic3r::GLVolume::print_zs, Slic3r::GLIndexedVertexArray::quad_indices_size, Slic3r::GLVolume::qverts_range, Slic3r::GLIndexedVertexArray::triangle_indices_size, and Slic3r::GLVolume::tverts_range.
set_render_color() [1/3]
void Slic3r::GLVolume::set_render_color () inherited
{
    bool outside = is_outside || is_below_printbed();
    if (force_native_color || force_neutral_color) {
#ifdef ENABBLE_OUTSIDE_COLOR
        if (outside && shader_outside_printer_detection_enabled)
            set_render_color(OUTSIDE_COLOR);
        else {
#endif
            if (force_native_color)
                set_render_color(color);
            else
                set_render_color(NEUTRAL_COLOR);
#ifdef ENABLE_OUTSIDE_COLOR
        }
#endif
    }
    else {
        /* BBS
        if (hover == HS_Select)
            set_render_color(HOVER_SELECT_COLOR);
        else if (hover == HS_Deselect)
            set_render_color(HOVER_DESELECT_COLOR);
        else if (selected)
            set_render_color(outside ? SELECTED_OUTSIDE_COLOR : SELECTED_COLOR);
        else if (disabled)
        */
        if (disabled)
            set_render_color(DISABLED_COLOR);
#ifdef ENABLE_OUTSIDE_COLOR
        else if (is_outside && shader_outside_printer_detection_enabled)
            set_render_color(OUTSIDE_COLOR);
#endif
        else {
            //to make black not too hard too see
            std::array<float, 4> new_color = adjust_color_for_rendering(color);
            set_render_color(new_color);
        }
    }
    if (force_transparent) {
        if (color[3] < FullyTransparentMaterialThreshold) {
            render_color[3] = FullTransparentModdifiedToFixAlpha;
        } else {
            render_color[3] = color[3];
        }
    }
    //BBS set unprintable color
    if (!printable) {
        render_color[0] = UNPRINTABLE_COLOR[0];
        render_color[1] = UNPRINTABLE_COLOR[1];
        render_color[2] = UNPRINTABLE_COLOR[2];
        render_color[3] = UNPRINTABLE_COLOR[3];
    }
    //BBS set invisible color
    if (!visible) {
        render_color[0] = MODEL_HIDDEN_COL[0];
        render_color[1] = MODEL_HIDDEN_COL[1];
        render_color[2] = MODEL_HIDDEN_COL[2];
        render_color[3] = MODEL_HIDDEN_COL[3];
    }
}
References adjust_color_for_rendering(), Slic3r::GLVolume::color, Slic3r::GLVolume::DISABLED_COLOR, FullTransparentModdifiedToFixAlpha, FullyTransparentMaterialThreshold, Slic3r::GLVolume::is_below_printbed(), Slic3r::GLVolume::MODEL_HIDDEN_COL, Slic3r::GLVolume::NEUTRAL_COLOR, Slic3r::GLVolume::render_color, Slic3r::GLVolume::set_render_color(), and Slic3r::GLVolume::UNPRINTABLE_COLOR.
Referenced by Slic3r::GLVolume::GLVolume(), and Slic3r::GLVolume::set_render_color().
set_render_color() [2/3]
void Slic3r::GLVolume::set_render_color (const std::array< float, 4 > & rgba) inherited
{
    render_color = rgba;
}
References Slic3r::GLVolume::render_color.
set_render_color() [3/3]
void Slic3r::GLVolume::set_render_color (float r, float g, float b, float a) inherited
{
    render_color = { r, g, b, a };
}
References Slic3r::GLVolume::render_color.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::run_thread().
set_sla_shift_z()
void Slic3r::GLVolume::set_sla_shift_z (double z) inline inherited
{ m_sla_shift_z = z; }
References Slic3r::GLVolume::m_sla_shift_z.
set_volume_mirror() [1/2]
void Slic3r::GLVolume::set_volume_mirror (Axis axis, double mirror) inline inherited
{ m_volume_transformation.set_mirror(axis, mirror); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_mirror().
set_volume_mirror() [2/2]
void Slic3r::GLVolume::set_volume_mirror (const Vec3d & mirror) inline inherited
{ m_volume_transformation.set_mirror(mirror); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_mirror().
Referenced by Slic3r::GUI::Selection::mirror(), and Slic3r::GUI::Selection::synchronize_unselected_volumes().
set_volume_offset() [1/2]
void Slic3r::GLVolume::set_volume_offset (Axis axis, double offset) inline inherited
{ m_volume_transformation.set_offset(axis, offset); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, Slic3r::offset(), Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_offset().
set_volume_offset() [2/2]
void Slic3r::GLVolume::set_volume_offset (const Vec3d & offset) inline inherited
{ m_volume_transformation.set_offset(offset); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, Slic3r::offset(), Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_offset().
Referenced by Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::Selection::move_to_center(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::Selection::scale(), Slic3r::GUI::Selection::synchronize_unselected_volumes(), and Slic3r::GUI::Selection::translate().
set_volume_rotation() [1/2]
void Slic3r::GLVolume::set_volume_rotation (Axis axis, double rotation) inline inherited
{ m_volume_transformation.set_rotation(axis, rotation); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_rotation().
set_volume_rotation() [2/2]
void Slic3r::GLVolume::set_volume_rotation (const Vec3d & rotation) inline inherited
{ m_volume_transformation.set_rotation(rotation); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_rotation().
Referenced by Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::Selection::rotate(), and Slic3r::GUI::Selection::synchronize_unselected_volumes().
set_volume_scaling_factor() [1/2]
void Slic3r::GLVolume::set_volume_scaling_factor (Axis axis, double scaling_factor) inline inherited
{ m_volume_transformation.set_scaling_factor(axis, scaling_factor); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_scaling_factor().
set_volume_scaling_factor() [2/2]
void Slic3r::GLVolume::set_volume_scaling_factor (const Vec3d & scaling_factor) inline inherited
{ m_volume_transformation.set_scaling_factor(scaling_factor); set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::Geometry::Transformation::set_scaling_factor().
Referenced by Slic3r::GUI::Selection::scale(), and Slic3r::GUI::Selection::synchronize_unselected_volumes().
set_volume_transformation()
void Slic3r::GLVolume::set_volume_transformation (const Geometry::Transformation & transformation) inline inherited
{ m_volume_transformation = transformation; set_bounding_boxes_as_dirty(); }
References Slic3r::GLVolume::m_volume_transformation, and Slic3r::GLVolume::set_bounding_boxes_as_dirty().
Referenced by Slic3r::GLVolumeCollection::load_object_volume().
simple_render()
void Slic3r::GLVolume::simple_render (GLShaderProgram * shader, ModelObjectPtrs & model_objects, std::vector< std::array< float, 4 > > & extruder_colors) const inherited
{
    if (this->is_left_handed())
        glFrontFace(GL_CW);
    glsafe(::glCullFace(GL_BACK));
    glsafe(::glPushMatrix());
    bool color_volume = false;
    ModelObject* model_object = nullptr;
    ModelVolume* model_volume = nullptr;
    do {
        if ((!printable) || object_idx() >= model_objects.size())
            break;
        model_object = model_objects[object_idx()];
        if (volume_idx() >=  model_object->volumes.size())
            break;
        model_volume = model_object->volumes[volume_idx()];
        if (model_volume->mmu_segmentation_facets.empty())
            break;
        color_volume = true;
        if (model_volume->mmu_segmentation_facets.timestamp() != mmuseg_ts) {
            mmuseg_ivas.clear();
            std::vector<indexed_triangle_set> its_per_color;
            model_volume->mmu_segmentation_facets.get_facets(*model_volume, its_per_color);
            mmuseg_ivas.resize(its_per_color.size());
            for (int idx = 0; idx < its_per_color.size(); idx++) {
                mmuseg_ivas[idx].load_its_flat_shading(its_per_color[idx]);
                mmuseg_ivas[idx].finalize_geometry(true);
            }
            mmuseg_ts = model_volume->mmu_segmentation_facets.timestamp();
        }
    } while (0);
    if (color_volume) {
        glsafe(::glMultMatrixd(world_matrix().data()));
        for (int idx = 0; idx < mmuseg_ivas.size(); idx++) {
            GLIndexedVertexArray& iva = mmuseg_ivas[idx];
            if (iva.triangle_indices_size == 0 && iva.quad_indices_size == 0)
                continue;
            if (shader) {
                if (idx == 0) {
                    int extruder_id = model_volume->extruder_id();
                    //to make black not too hard too see
                    std::array<float, 4> new_color = adjust_color_for_rendering(extruder_colors[extruder_id - 1]);
                    shader->set_uniform("uniform_color", new_color);
                }
                else {
                    if (idx <= extruder_colors.size()) {
                        //shader->set_uniform("uniform_color", extruder_colors[idx - 1]);
                        //to make black not too hard too see
                        std::array<float, 4> new_color = adjust_color_for_rendering(extruder_colors[idx - 1]);
                        shader->set_uniform("uniform_color", new_color);
                    }
                    else {
                        //shader->set_uniform("uniform_color", extruder_colors[0]);
                        //to make black not too hard too see
                        std::array<float, 4> new_color = adjust_color_for_rendering(extruder_colors[0]);
                        shader->set_uniform("uniform_color", new_color);
                    }
                }
            }
            iva.render(this->tverts_range, this->qverts_range);
        }
    }
    else {
        glsafe(::glMultMatrixd(world_matrix().data()));
        this->indexed_vertex_array.render(this->tverts_range, this->qverts_range);
    }
    glsafe(::glPopMatrix());
    if (this->is_left_handed())
        glFrontFace(GL_CCW);
}
References adjust_color_for_rendering(), Slic3r::FacetsAnnotation::empty(), Slic3r::ModelVolume::extruder_id(), Slic3r::GLVolume::extruder_id, Slic3r::FacetsAnnotation::get_facets(), glsafe, Slic3r::GLVolume::indexed_vertex_array, Slic3r::GLVolume::is_left_handed(), Slic3r::ModelVolume::mmu_segmentation_facets, Slic3r::GLVolume::mmuseg_ivas, Slic3r::GLVolume::mmuseg_ts, Slic3r::GLVolume::object_idx(), Slic3r::GLIndexedVertexArray::quad_indices_size, Slic3r::GLVolume::qverts_range, Slic3r::GLIndexedVertexArray::render(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::ObjectWithTimestamp::timestamp(), Slic3r::GLIndexedVertexArray::triangle_indices_size, Slic3r::GLVolume::tverts_range, Slic3r::GLVolume::volume_idx(), Slic3r::ModelObject::volumes, and Slic3r::GLVolume::world_matrix().
total_memory_used()
size_t Slic3r::GLVolume::total_memory_used () const inline inherited
{ return this->cpu_memory_used() + this->gpu_memory_used(); }
References Slic3r::GLVolume::cpu_memory_used(), and Slic3r::GLVolume::gpu_memory_used().
transformed_bounding_box()
const BoundingBoxf3 & Slic3r::GLVolume::transformed_bounding_box () const inherited
{
    if (!m_transformed_bounding_box.has_value() || last_explosion_ratio != explosion_ratio) {
        const BoundingBoxf3& box = bounding_box();
        assert(box.defined || box.min.x() >= box.max.x() || box.min.y() >= box.max.y() || box.min.z() >= box.max.z());
        std::optional<BoundingBoxf3>* trans_box = const_cast<std::optional<BoundingBoxf3>*>(&m_transformed_bounding_box);
        *trans_box = box.transformed(world_matrix());
        last_explosion_ratio = explosion_ratio;
    }
    return *m_transformed_bounding_box;
}
References Slic3r::GLVolume::bounding_box(), Slic3r::BoundingBoxBase< PointClass >::defined, Slic3r::GLVolume::explosion_ratio, Slic3r::GLVolume::last_explosion_ratio, Slic3r::GLVolume::m_transformed_bounding_box, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::BoundingBoxf3::transformed(), and Slic3r::GLVolume::world_matrix().
transformed_convex_hull_bounding_box() [1/2]
const BoundingBoxf3 & Slic3r::GLVolume::transformed_convex_hull_bounding_box () const inherited
{
    if (!m_transformed_convex_hull_bounding_box.has_value()) {
        std::optional<BoundingBoxf3>* trans_box = const_cast<std::optional<BoundingBoxf3>*>(&m_transformed_convex_hull_bounding_box);
        *trans_box = transformed_convex_hull_bounding_box(world_matrix());
    }
    return *m_transformed_convex_hull_bounding_box;
}
References Slic3r::GLVolume::m_transformed_convex_hull_bounding_box, Slic3r::GLVolume::transformed_convex_hull_bounding_box(), and Slic3r::GLVolume::world_matrix().
Referenced by Slic3r::GLVolume::is_below_printbed(), Slic3r::GLVolume::is_sinking(), and Slic3r::GLVolume::transformed_convex_hull_bounding_box().
transformed_convex_hull_bounding_box() [2/2]
BoundingBoxf3 Slic3r::GLVolume::transformed_convex_hull_bounding_box (const Transform3d & trafo) const inherited
{
  return (m_convex_hull && ! m_convex_hull->empty()) ?
    m_convex_hull->transformed_bounding_box(trafo) :
        bounding_box().transformed(trafo);
}
References Slic3r::GLVolume::bounding_box(), Slic3r::GLVolume::m_convex_hull, and Slic3r::BoundingBoxf3::transformed().
Referenced by Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
transformed_non_sinking_bounding_box() [1/2]
const BoundingBoxf3 & Slic3r::GLVolume::transformed_non_sinking_bounding_box () const inherited
{
    if (!m_transformed_non_sinking_bounding_box.has_value()) {
        std::optional<BoundingBoxf3>* trans_box = const_cast<std::optional<BoundingBoxf3>*>(&m_transformed_non_sinking_bounding_box);
        const Transform3d& trafo = world_matrix();
        *trans_box = transformed_non_sinking_bounding_box(trafo);
    }
    return *m_transformed_non_sinking_bounding_box;
}
References Slic3r::GLVolume::m_transformed_non_sinking_bounding_box, Slic3r::GLVolume::transformed_non_sinking_bounding_box(), and Slic3r::GLVolume::world_matrix().
Referenced by Slic3r::GLVolume::transformed_non_sinking_bounding_box().
transformed_non_sinking_bounding_box() [2/2]
BoundingBoxf3 Slic3r::GLVolume::transformed_non_sinking_bounding_box (const Transform3d & trafo) const inherited
{
    return GUI::wxGetApp().plater()->model().objects[object_idx()]->volumes[volume_idx()]->mesh().transformed_bounding_box(trafo, 0.0);
}
References Slic3r::GLVolume::object_idx(), and Slic3r::GLVolume::volume_idx().
update_render_colors()
void Slic3r::GLVolume::update_render_colors () static inherited
{
    GLVolume::DISABLED_COLOR    = GLColor(RenderColor::colors[RenderCol_Model_Disable]);
    GLVolume::NEUTRAL_COLOR     = GLColor(RenderColor::colors[RenderCol_Model_Neutral]);
    GLVolume::MODEL_COLOR[0]    = GLColor(RenderColor::colors[RenderCol_Modifier]);
    GLVolume::MODEL_COLOR[1]    = GLColor(RenderColor::colors[RenderCol_Negtive_Volume]);
    GLVolume::MODEL_COLOR[2]    = GLColor(RenderColor::colors[RenderCol_Support_Enforcer]);
    GLVolume::MODEL_COLOR[3]    = GLColor(RenderColor::colors[RenderCol_Support_Blocker]);
    GLVolume::UNPRINTABLE_COLOR = GLColor(RenderColor::colors[RenderCol_Model_Unprintable]);
}
References Slic3r::RenderColor::colors, Slic3r::GLVolume::DISABLED_COLOR, Slic3r::GLColor(), Slic3r::GLVolume::MODEL_COLOR, Slic3r::GLVolume::NEUTRAL_COLOR, RenderCol_Model_Disable, RenderCol_Model_Neutral, RenderCol_Model_Unprintable, RenderCol_Modifier, RenderCol_Negtive_Volume, RenderCol_Support_Blocker, RenderCol_Support_Enforcer, and Slic3r::GLVolume::UNPRINTABLE_COLOR.
Referenced by Slic3r::GUI::GLCanvas3D::_render_style_editor().
volume_idx()
int Slic3r::GLVolume::volume_idx () const inline inherited
{ return this->composite_id.volume_id; }
References Slic3r::GLVolume::CompositeID::volume_id.
Referenced by Slic3r::GUI::GLCanvas3D::_update_selection_from_hover(), Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::Selection::erase(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::Plater::priv::get_selected_volume_idx(), Slic3r::GUI::Selection::get_volume_idxs_from_volume(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::Selection::remove_volume(), Slic3r::GLVolume::render(), Slic3r::GUI::Selection::render_synchronized_volumes(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GLVolume::simple_render(), Slic3r::GUI::Selection::synchronize_unselected_volumes(), and Slic3r::GLVolume::transformed_non_sinking_bounding_box().
world_matrix()
Transform3d Slic3r::GLVolume::world_matrix () const inherited
{
    Transform3d m = m_instance_transformation.get_matrix() * m_volume_transformation.get_matrix();
    Vec3d ofs2ass = m_offset_to_assembly * (GLVolume::explosion_ratio - 1.0);
    Vec3d volofs2obj = m_volume_transformation.get_offset() * (GLVolume::explosion_ratio - 1.0);
    m.translation()(2) += m_sla_shift_z;
    m.translate(ofs2ass + volofs2obj);
    return m;
}
References Slic3r::GLVolume::explosion_ratio, Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GLVolume::m_instance_transformation, Slic3r::GLVolume::m_offset_to_assembly, Slic3r::GLVolume::m_sla_shift_z, Slic3r::GLVolume::m_volume_transformation, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GLVolume::render(), render(), Slic3r::GLVolume::simple_render(), Slic3r::GLVolume::transformed_bounding_box(), Slic3r::GLVolume::transformed_convex_hull_bounding_box(), and Slic3r::GLVolume::transformed_non_sinking_bounding_box().
Member Data Documentation
[struct]
struct { ... } Slic3r::GLVolume
color
std::array<float, 4> Slic3r::GLVolume::color inherited
Referenced by Slic3r::GLVolume::GLVolume(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::GLVolume::set_color(), and Slic3r::GLVolume::set_render_color().
composite_id
CompositeID Slic3r::GLVolume::composite_id inherited
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GUI::get_model_volume(), Slic3r::GLVolume::is_sla_pad(), Slic3r::GLVolume::is_sla_support(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), and Slic3r::GUI::GLCanvas3D::reload_scene().
DISABLED_COLOR
std::array< float, 4 > Slic3r::GLVolume::DISABLED_COLOR = { 0.25f, 0.25f, 0.25f, 1.0f } static inherited
Referenced by Slic3r::GLVolume::load_render_colors(), Slic3r::GLVolume::set_render_color(), and Slic3r::GLVolume::update_render_colors().
explosion_ratio
float Slic3r::GLVolume::explosion_ratio = 1.0 static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLCanvas3D::on_mouse_wheel(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::render_cut(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::set_position(), Slic3r::GLVolume::transformed_bounding_box(), and Slic3r::GLVolume::world_matrix().
extruder_id
int Slic3r::GLVolume::extruder_id inherited
Referenced by Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolume::render(), and Slic3r::GLVolume::simple_render().
geometry_id
std::pair<size_t, size_t> Slic3r::GLVolume::geometry_id inherited
Referenced by Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GUI::GLCanvas3D::reload_scene(), and Slic3r::UndoRedo::StackImpl::take_snapshot().
hover
EHoverState Slic3r::GLVolume::hover inherited
Referenced by Slic3r::GUI::Selection::do_add_volume().
indexed_vertex_array
GLIndexedVertexArray Slic3r::GLVolume::indexed_vertex_array inherited
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::GLVolume::cpu_memory_used(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GLVolume::render(), Slic3r::GUI::reserve_new_volume_finalize_old_volume(), Slic3r::GLVolume::set_range(), and Slic3r::GLVolume::simple_render().
iva_per_colors
std::vector<GLIndexedVertexArray> Slic3r::GLWipeTowerVolume::iva_per_colors
Referenced by Slic3r::GLVolumeCollection::load_wipe_tower_preview(), and render().
last_explosion_ratio
float Slic3r::GLVolume::last_explosion_ratio = 1.0 static inherited
Referenced by Slic3r::GLVolume::transformed_bounding_box().
m_colors
std::vector<std::array<float, 4> > Slic3r::GLWipeTowerVolume::m_colors private
Referenced by GLWipeTowerVolume(), IsTransparent(), and render().
m_convex_hull
std::shared_ptr<const TriangleMesh> Slic3r::GLVolume::m_convex_hull protected inherited
Referenced by Slic3r::GLVolume::convex_hull(), Slic3r::GLVolume::set_convex_hull(), Slic3r::GLVolume::set_convex_hull(), Slic3r::GLVolume::set_convex_hull(), and Slic3r::GLVolume::transformed_convex_hull_bounding_box().
m_instance_transformation
Geometry::Transformation Slic3r::GLVolume::m_instance_transformation protected inherited
Referenced by Slic3r::GLVolume::get_instance_mirror(), Slic3r::GLVolume::get_instance_mirror(), Slic3r::GLVolume::get_instance_offset(), Slic3r::GLVolume::get_instance_offset(), Slic3r::GLVolume::get_instance_rotation(), Slic3r::GLVolume::get_instance_rotation(), Slic3r::GLVolume::get_instance_scaling_factor(), Slic3r::GLVolume::get_instance_scaling_factor(), Slic3r::GLVolume::get_instance_transformation(), Slic3r::GLVolume::is_left_handed(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::GLVolume::set_instance_transformation(), and Slic3r::GLVolume::world_matrix().
m_offset_to_assembly
Vec3d Slic3r::GLVolume::m_offset_to_assembly { 0.0, 0.0, 0.0 } protected inherited
Referenced by Slic3r::GLVolume::get_offset_to_assembly(), Slic3r::GLVolume::set_offset_to_assembly(), and Slic3r::GLVolume::world_matrix().
m_sinking_contours
SinkingContours Slic3r::GLVolume::m_sinking_contours protected inherited
Referenced by Slic3r::GLVolume::render_sinking_contours().
m_sla_shift_z
double Slic3r::GLVolume::m_sla_shift_z protected inherited
Referenced by Slic3r::GLVolume::get_sla_shift_z(), Slic3r::GLVolume::set_sla_shift_z(), and Slic3r::GLVolume::world_matrix().
m_transformed_bounding_box
std::optional<BoundingBoxf3> Slic3r::GLVolume::m_transformed_bounding_box protected inherited
Referenced by Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::GLVolume::transformed_bounding_box().
m_transformed_convex_hull_bounding_box
std::optional<BoundingBoxf3> Slic3r::GLVolume::m_transformed_convex_hull_bounding_box protected inherited
Referenced by Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::GLVolume::transformed_convex_hull_bounding_box().
m_transformed_non_sinking_bounding_box
std::optional<BoundingBoxf3> Slic3r::GLVolume::m_transformed_non_sinking_bounding_box protected inherited
Referenced by Slic3r::GLVolume::set_bounding_boxes_as_dirty(), and Slic3r::GLVolume::transformed_non_sinking_bounding_box().
m_volume_transformation
Geometry::Transformation Slic3r::GLVolume::m_volume_transformation protected inherited
Referenced by Slic3r::GLVolume::get_volume_mirror(), Slic3r::GLVolume::get_volume_mirror(), Slic3r::GLVolume::get_volume_offset(), Slic3r::GLVolume::get_volume_offset(), Slic3r::GLVolume::get_volume_rotation(), Slic3r::GLVolume::get_volume_rotation(), Slic3r::GLVolume::get_volume_scaling_factor(), Slic3r::GLVolume::get_volume_scaling_factor(), Slic3r::GLVolume::get_volume_transformation(), Slic3r::GLVolume::is_left_handed(), Slic3r::GLVolume::set_volume_mirror(), Slic3r::GLVolume::set_volume_mirror(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_rotation(), Slic3r::GLVolume::set_volume_rotation(), Slic3r::GLVolume::set_volume_scaling_factor(), Slic3r::GLVolume::set_volume_scaling_factor(), Slic3r::GLVolume::set_volume_transformation(), and Slic3r::GLVolume::world_matrix().
mmuseg_ivas
std::vector<GLIndexedVertexArray> Slic3r::GLVolume::mmuseg_ivas mutable inherited
Referenced by Slic3r::GLVolume::render(), and Slic3r::GLVolume::simple_render().
mmuseg_ts
ObjectBase::Timestamp Slic3r::GLVolume::mmuseg_ts mutable inherited
Referenced by Slic3r::GLVolume::GLVolume(), Slic3r::GLVolume::render(), and Slic3r::GLVolume::simple_render().
MODEL_COLOR
std::array< std::array< float, 4 >, 5 > Slic3r::GLVolume::MODEL_COLOR static inherited
Initial value:
= { {
    { 1.0f, 1.0f, 0.0f, 1.f },
    { 1.0f, 0.5f, 0.5f, 1.f },
    { 0.5f, 1.0f, 0.5f, 1.f },
    { 0.5f, 0.5f, 1.0f, 1.f },
    { 1.0f, 1.0f, 0.0f, 1.f }
} }
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolume::load_render_colors(), and Slic3r::GLVolume::update_render_colors().
MODEL_HIDDEN_COL
std::array< float, 4 > Slic3r::GLVolume::MODEL_HIDDEN_COL = {0.f, 0.f, 0.f, 0.3f} static inherited
Referenced by Slic3r::GLVolume::set_render_color(), and Slic3r::GUI::GLCanvas3D::set_selected_visible().
MODEL_MIDIFIER_COL
std::array< float, 4 > Slic3r::GLVolume::MODEL_MIDIFIER_COL = {1.0f, 1.0f, 0.0f, 0.6f} static inherited
Referenced by Slic3r::color_from_model_volume().
MODEL_NEGTIVE_COL
std::array< float, 4 > Slic3r::GLVolume::MODEL_NEGTIVE_COL = {0.3f, 0.3f, 0.3f, 0.4f} static inherited
Referenced by Slic3r::color_from_model_volume().
model_object_ID
size_t Slic3r::GLVolume::model_object_ID {0} inherited
Referenced by Slic3r::GLVolumeCollection::load_object_volume().
name
std::string Slic3r::GLVolume::name inherited
Referenced by Slic3r::GLVolumeCollection::load_object_volume(), and Slic3r::GLVolume::render().
NEUTRAL_COLOR
std::array< float, 4 > Slic3r::GLVolume::NEUTRAL_COLOR = { 0.8f, 0.8f, 0.8f, 1.0f } static inherited
Referenced by Slic3r::GLVolume::load_render_colors(), Slic3r::GUI::TriangleSelectorGUI::render(), Slic3r::GLVolume::set_render_color(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), and Slic3r::GLVolume::update_render_colors().
offsets
std::vector<size_t> Slic3r::GLVolume::offsets inherited
Referenced by Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), and Slic3r::GLVolume::set_range().
print_zs
std::vector<coordf_t> Slic3r::GLVolume::print_zs inherited
Referenced by Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), and Slic3r::GLVolume::set_range().
qverts_range
std::pair<size_t, size_t> Slic3r::GLVolume::qverts_range inherited
Referenced by Slic3r::GLVolume::render(), Slic3r::GLVolume::set_range(), and Slic3r::GLVolume::simple_render().
render_color
std::array<float, 4> Slic3r::GLVolume::render_color inherited
Referenced by Slic3r::GLVolume::render(), Slic3r::GLVolume::set_render_color(), Slic3r::GLVolume::set_render_color(), and Slic3r::GLVolume::set_render_color().
SLA_PAD_COLOR
std::array< float, 4 > Slic3r::GLVolume::SLA_PAD_COLOR = { 0.0f, 0.2f, 0.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), and Slic3r::GLVolumeCollection::load_object_auxiliary().
SLA_SUPPORT_COLOR
std::array< float, 4 > Slic3r::GLVolume::SLA_SUPPORT_COLOR = { 0.75f, 0.75f, 0.75f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), and Slic3r::GLVolumeCollection::load_object_auxiliary().
SUPPORT_BLOCKER_COL
std::array< float, 4 > Slic3r::GLVolume::SUPPORT_BLOCKER_COL = {1.0f, 0.3f, 0.3f, 0.4f} static inherited
Referenced by Slic3r::color_from_model_volume().
SUPPORT_ENFORCER_COL
std::array< float, 4 > Slic3r::GLVolume::SUPPORT_ENFORCER_COL = {0.3f, 0.3f, 1.0f, 0.4f} static inherited
Referenced by Slic3r::color_from_model_volume().
tverts_range
std::pair<size_t, size_t> Slic3r::GLVolume::tverts_range inherited
Referenced by Slic3r::GLVolume::render(), Slic3r::GLVolume::set_range(), and Slic3r::GLVolume::simple_render().
UNPRINTABLE_COLOR
std::array< float, 4 > Slic3r::GLVolume::UNPRINTABLE_COLOR = { 0.0f, 0.0f, 0.0f, 0.5f } static inherited
Referenced by Slic3r::GLVolume::load_render_colors(), Slic3r::GLVolume::set_render_color(), Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_object(), and Slic3r::GLVolume::update_render_colors().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DScene.hpp
src/slic3r/GUI/3DScene.cpp