OrcaSlicer: Slic3r::GUI::AssembleViewDataBase Class Reference
Slic3r::GUI::AssembleViewDataBase Class Reference abstract
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
AssembleViewDataBase (AssembleViewDataPool *cgdp)
virtual ~AssembleViewDataBase ()
void update ()
void release ()
bool is_valid () const
virtual AssembleViewDataID get_dependencies () const
Protected Member Functions
virtual void on_release ()=0
virtual void on_update ()=0
AssembleViewDataPool * get_pool () const
Private Attributes
bool m_is_valid = false
AssembleViewDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
AssembleViewDataBase()
Slic3r::GUI::AssembleViewDataBase::AssembleViewDataBase (AssembleViewDataPool * cgdp) inline explicit
        : m_common{ cgdp } {}
~AssembleViewDataBase()
virtual Slic3r::GUI::AssembleViewDataBase::~AssembleViewDataBase () inline virtual
{}
Member Function Documentation
get_dependencies()
virtual AssembleViewDataID Slic3r::GUI::AssembleViewDataBase::get_dependencies () const inline virtual
Reimplemented in Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper.
{ return AssembleViewDataID::None; }
References Slic3r::GUI::None.
get_pool()
AssembleViewDataPool * Slic3r::GUI::AssembleViewDataBase::get_pool () const inline protected
{ return m_common; }
References m_common.
Referenced by Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::on_update(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::on_update(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::render_cut(), and Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::set_position().
is_valid()
bool Slic3r::GUI::AssembleViewDataBase::is_valid () const inline
{ return m_is_valid; }
References m_is_valid.
Referenced by Slic3r::GUI::AssembleViewDataPool::model_objects_clipper(), and Slic3r::GUI::AssembleViewDataPool::model_objects_info().
on_release()
virtual void Slic3r::GUI::AssembleViewDataBase::on_release () protected pure virtual
Implemented in Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo, and Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper.
Referenced by release().
on_update()
virtual void Slic3r::GUI::AssembleViewDataBase::on_update () protected pure virtual
Implemented in Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo, and Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper.
Referenced by update().
release()
void Slic3r::GUI::AssembleViewDataBase::release () inline
{ on_release(); m_is_valid = false; }
References m_is_valid, and on_release().
update()
void Slic3r::GUI::AssembleViewDataBase::update () inline
{ on_update(); m_is_valid = true; }
References m_is_valid, and on_update().
Member Data Documentation
m_common
AssembleViewDataPool* Slic3r::GUI::AssembleViewDataBase::m_common = nullptr private
Referenced by get_pool().
m_is_valid
bool Slic3r::GUI::AssembleViewDataBase::m_is_valid = false private
Referenced by is_valid(), release(), and update().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp