OrcaSlicer: src/minilzo/minilzo.h File Reference
minilzo.h File Reference
#include <limits.h>
#include <stddef.h>
#include "lzodefs.h"
#include "lzoconf.h"
Macros
#define MINILZO_VERSION 0x20a0 /* 2.10 */
#define LZO1X_MEM_COMPRESS LZO1X_1_MEM_COMPRESS
#define LZO1X_1_MEM_COMPRESS ((lzo_uint32_t) (16384L * lzo_sizeof_dict_t))
#define LZO1X_MEM_DECOMPRESS (0)
Functions
lzo1x_1_compress (const lzo_bytep src, lzo_uint src_len, lzo_bytep dst, lzo_uintp dst_len, lzo_voidp wrkmem)
lzo1x_decompress (const lzo_bytep src, lzo_uint src_len, lzo_bytep dst, lzo_uintp dst_len, lzo_voidp wrkmem)
lzo1x_decompress_safe (const lzo_bytep src, lzo_uint src_len, lzo_bytep dst, lzo_uintp dst_len, lzo_voidp wrkmem)
Macro Definition Documentation
LZO1X_1_MEM_COMPRESS
#define LZO1X_1_MEM_COMPRESS ((lzo_uint32_t) (16384L * lzo_sizeof_dict_t))
LZO1X_MEM_COMPRESS
#define LZO1X_MEM_COMPRESS LZO1X_1_MEM_COMPRESS
LZO1X_MEM_DECOMPRESS
#define LZO1X_MEM_DECOMPRESS (0)
MINILZO_VERSION
#define MINILZO_VERSION 0x20a0 /* 2.10 */
Function Documentation
lzo1x_1_compress()
lzo1x_1_compress (const lzo_bytep src, lzo_uint src_len, lzo_bytep dst, lzo_uintp dst_len, lzo_voidp wrkmem)
Referenced by Slic3r::lzo_compress(), and main().
lzo1x_decompress()
lzo1x_decompress (const lzo_bytep src, lzo_uint src_len, lzo_bytep dst, lzo_uintp dst_len, lzo_voidp wrkmem)
Referenced by Slic3r::lzo_decompress(), and main().
lzo1x_decompress_safe()
lzo1x_decompress_safe (const lzo_bytep src, lzo_uint src_len, lzo_bytep dst, lzo_uintp dst_len, lzo_voidp wrkmem)