OrcaSlicer: cdt::box2d_t< T > Struct Template Reference
cdt::box2d_t< T > Struct Template Reference
2D bounding box
#include <src/mcut/include/mcut/internal/cdt/utils.h>
Public Member Functions
void expand_with_point (const vec2_< T > &p)
Envelop box around a point.
void expand_with_point (const T x, const T y)
Envelop box around a point with given coordinates.
Public Attributes
vec2_< T > min
min box corner
vec2_< T > max
max box corner
Detailed Description
template<typename T>
struct cdt::box2d_t< T >
2D bounding box
Member Function Documentation
expand_with_point() [1/2]
template<typename T > void cdt::box2d_t< T >::expand_with_point (const T x, const T y) inline
Envelop box around a point with given coordinates.
    {
        min.x() = std::min(x, min.x());
        max.x() = std::max(x, max.x());
        min.y() = std::min(y, min.y());
        max.y() = std::max(y, max.y());
    }
References cdt::box2d_t< T >::max, cdt::box2d_t< T >::min, vec2_< T >::x(), and vec2_< T >::y().
expand_with_point() [2/2]
template<typename T > void cdt::box2d_t< T >::expand_with_point (const vec2_< T > & p) inline
Envelop box around a point.
    {
        expand_with_point(p.x(), p.y());
    }
References cdt::box2d_t< T >::expand_with_point(), vec2_< T >::x(), and vec2_< T >::y().
Referenced by cdt::box2d_t< T >::expand_with_point(), and cdt::expand_with_points().
Member Data Documentation
max
template<typename T > vec2_<T> cdt::box2d_t< T >::max
max box corner
Referenced by cdt::triangulator_t< T, TNearPointLocator >::add_super_triangle(), and cdt::box2d_t< T >::expand_with_point().
min
template<typename T > vec2_<T> cdt::box2d_t< T >::min
min box corner
Referenced by cdt::triangulator_t< T, TNearPointLocator >::add_super_triangle(), and cdt::box2d_t< T >::expand_with_point().
The documentation for this struct was generated from the following file:
src/mcut/include/mcut/internal/cdt/utils.h