OrcaSlicer: Clipper2Lib::Rect< T > Struct Template Reference
Clipper2Lib::Rect< T > Struct Template Reference
#include <src/clipper2/Clipper2Lib/include/clipper2/clipper.core.h>
Public Member Functions
Rect ()
Rect (T l, T t, T r, T b)
T Width () const
T Height () const
void Width (T width)
void Height (T height)
Point< T > MidPoint () const
Path< T > AsPath () const
bool Contains (const Point< T > &pt) const
bool Contains (const Rect< T > &rec) const
void Scale (double scale)
bool IsEmpty () const
bool Intersects (const Rect< T > &rec) const
Public Attributes
T left
T top
T right
T bottom
Friends
std::ostream & operator<< (std::ostream &os, const Rect< T > &rect)
Detailed Description
template<typename T>
struct Clipper2Lib::Rect< T >
Constructor & Destructor Documentation
Rect() [1/2]
template<typename T > Clipper2Lib::Rect< T >::Rect () inline
         :
    left(0),
    top(0),
    right(0),
    bottom(0) {}
Rect() [2/2]
template<typename T > Clipper2Lib::Rect< T >::Rect (T l, T t, T r, T b) inline
                           :
    left(l),
    top(t),
    right(r),
    bottom(b) {}
Member Function Documentation
AsPath()
template<typename T > Path< T > Clipper2Lib::Rect< T >::AsPath () const inline
  {
    Path<T> result;
    result.reserve(4);
    result.push_back(Point<T>(left, top));
    result.push_back(Point<T>(right, top));
    result.push_back(Point<T>(right, bottom));
    result.push_back(Point<T>(left, bottom));
    return result;
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Referenced by Clipper2Lib::ClipperOffset::DoGroupOffset().
Contains() [1/2]
template<typename T > bool Clipper2Lib::Rect< T >::Contains (const Point< T > & pt) const inline
  {
    return pt.x > left && pt.x < right&& pt.y > top && pt.y < bottom;
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, Clipper2Lib::Rect< T >::top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::DeepCheckOwner(), Clipper2Lib::RectClip::Execute(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip64(), Clipper2Lib::RectClipD(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines64(), and Clipper2Lib::RectClipLinesD().
Contains() [2/2]
template<typename T > bool Clipper2Lib::Rect< T >::Contains (const Rect< T > & rec) const inline
  {
    return rec.left >= left && rec.right <= right &&
      rec.top >= top && rec.bottom <= bottom;
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Height() [1/2]
template<typename T > T Clipper2Lib::Rect< T >::Height () const inline
{ return bottom - top; }
References Clipper2Lib::Rect< T >::bottom, and Clipper2Lib::Rect< T >::top.
Referenced by Clipper2Lib::Ellipse().
Height() [2/2]
template<typename T > void Clipper2Lib::Rect< T >::Height (T height) inline
{ bottom = top + height; }
References Clipper2Lib::Rect< T >::bottom, and Clipper2Lib::Rect< T >::top.
Intersects()
template<typename T > bool Clipper2Lib::Rect< T >::Intersects (const Rect< T > & rec) const inline
  {
    return (std::max(left, rec.left) < std::min(right, rec.right)) &&
      (std::max(top, rec.top) < std::min(bottom, rec.bottom));
  };
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Referenced by Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip64(), Clipper2Lib::RectClipD(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines64(), and Clipper2Lib::RectClipLinesD().
IsEmpty()
template<typename T > bool Clipper2Lib::Rect< T >::IsEmpty () const inline
{ return bottom <= top || right <= left; };
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Referenced by Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::ClipperBase::DeepCheckOwner(), Clipper2Lib::RectClip::Execute(), Clipper2Lib::RectClipLines::Execute(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), and Clipper2Lib::RectClipLines().
MidPoint()
template<typename T > Point< T > Clipper2Lib::Rect< T >::MidPoint () const inline
  {
    return Point<T>((left + right) / 2, (top + bottom) / 2);
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Referenced by Clipper2Lib::Ellipse().
Scale()
template<typename T > void Clipper2Lib::Rect< T >::Scale (double scale) inline
{
    left *= scale;
    top *= scale;
    right *= scale;
    bottom *= scale;
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, scale(), and Clipper2Lib::Rect< T >::top.
Width() [1/2]
template<typename T > T Clipper2Lib::Rect< T >::Width () const inline
{ return right - left; }
References Clipper2Lib::Rect< T >::left, and Clipper2Lib::Rect< T >::right.
Referenced by Clipper2Lib::Ellipse().
Width() [2/2]
template<typename T > void Clipper2Lib::Rect< T >::Width (T width) inline
{ right = left + width; }
References Clipper2Lib::Rect< T >::left, and Clipper2Lib::Rect< T >::right.
Friends And Related Symbol Documentation
operator<<
template<typename T > std::ostream & operator<< (std::ostream & os, const Rect< T > & rect) friend
{
    os << "("
       << rect.left << "," << rect.top << "," << rect.right << "," << rect.bottom
       << ")";
    return os;
  }
Member Data Documentation
bottom
template<typename T > T Clipper2Lib::Rect< T >::bottom
Referenced by Clipper2Lib::Rect< T >::AsPath(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::CRectToRect(), Clipper2Lib::GetBounds(), Clipper2Lib::GetLocation(), Clipper2Lib::RectClip::GetNextLocation(), Clipper2Lib::Rect< T >::Height(), Clipper2Lib::Rect< T >::Height(), Clipper2Lib::Rect< T >::Intersects(), Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::Rect< T >::MidPoint(), Clipper2Lib::Rect< T >::Scale(), and Clipper2Lib::ScaleRect().
left
template<typename T > T Clipper2Lib::Rect< T >::left
Referenced by Clipper2Lib::Rect< T >::AsPath(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::CRectToRect(), Clipper2Lib::GetBounds(), Clipper2Lib::GetLocation(), Clipper2Lib::RectClip::GetNextLocation(), Clipper2Lib::Rect< T >::Intersects(), Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::Rect< T >::MidPoint(), Clipper2Lib::Rect< T >::Scale(), Clipper2Lib::ScaleRect(), Clipper2Lib::Rect< T >::Width(), and Clipper2Lib::Rect< T >::Width().
right
template<typename T > T Clipper2Lib::Rect< T >::right
Referenced by Clipper2Lib::Rect< T >::AsPath(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::CRectToRect(), Clipper2Lib::GetBounds(), Clipper2Lib::GetLocation(), Clipper2Lib::RectClip::GetNextLocation(), Clipper2Lib::Rect< T >::Intersects(), Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::Rect< T >::MidPoint(), Clipper2Lib::Rect< T >::Scale(), Clipper2Lib::ScaleRect(), Clipper2Lib::Rect< T >::Width(), and Clipper2Lib::Rect< T >::Width().
top
template<typename T > T Clipper2Lib::Rect< T >::top
Referenced by Clipper2Lib::Rect< T >::AsPath(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::CRectToRect(), Clipper2Lib::GetBounds(), Clipper2Lib::GetLocation(), Clipper2Lib::RectClip::GetNextLocation(), Clipper2Lib::Rect< T >::Height(), Clipper2Lib::Rect< T >::Height(), Clipper2Lib::Rect< T >::Intersects(), Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::Rect< T >::MidPoint(), Clipper2Lib::Rect< T >::Scale(), and Clipper2Lib::ScaleRect().
The documentation for this struct was generated from the following file:
src/clipper2/Clipper2Lib/include/clipper2/clipper.core.h