OrcaSlicer: Slic3r::GUI::GLModel Class Reference
Slic3r::GUI::GLModel Class Reference
#include <src/slic3r/GUI/GLModel.hpp>
Classes
struct InitializationData
struct RenderData
Public Types
enum class PrimitiveType : unsigned char { Triangles , Lines , LineStrip , LineLoop }
Public Member Functions
GLModel ()=default
virtual ~GLModel ()
void init_from (const InitializationData &data)
void init_from (const indexed_triangle_set &its, const BoundingBoxf3 &bbox)
void init_from (const indexed_triangle_set &its)
void init_from (const Polygons &polygons, float z)
bool init_from_file (const std::string &filename)
void set_color (int entity_id, const std::array< float, 4 > &color)
void reset ()
void render () const
void render_instanced (unsigned int instances_vbo, unsigned int instances_count) const
bool is_initialized () const
const BoundingBoxf3 & get_bounding_box () const
const std::string & get_filename () const
Private Member Functions
void send_to_gpu (RenderData &data, const std::vector< float > &vertices, const std::vector< unsigned int > &indices)
Private Attributes
std::vector< RenderData > m_render_data
BoundingBoxf3 m_bounding_box
std::string m_filename
Detailed Description
Class Documentation
Slic3r::GUI::GLModel::RenderData
struct Slic3r::GUI::GLModel::RenderData
Class Members
array< float, 4 > color { 1.0f, 1.0f, 1.0f, 1.0f }
unsigned int ibo_id { 0 }
size_t indices_count { 0 }
PrimitiveType type
unsigned int vbo_id { 0 }
Member Enumeration Documentation
PrimitiveType
enum class Slic3r::GUI::GLModel::PrimitiveType : unsigned char strong
Enumerator
Triangles
Lines
LineStrip
LineLoop
        {
            Triangles,
            Lines,
            LineStrip,
            LineLoop
        };
Constructor & Destructor Documentation
GLModel()
Slic3r::GUI::GLModel::GLModel () default
~GLModel()
virtual Slic3r::GUI::GLModel::~GLModel () inline virtual
{ reset(); }
References reset().
Member Function Documentation
get_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::GLModel::get_bounding_box () const inline
{ return m_bounding_box; }
References m_bounding_box.
Referenced by Slic3r::GUI::Bed3D::calc_extended_bounding_box(), and Slic3r::GUI::GCodeViewer::SequentialView::Marker::get_bounding_box().
get_filename()
const std::string & Slic3r::GUI::GLModel::get_filename () const inline
{ return m_filename; }
References m_filename.
Referenced by Slic3r::GUI::Bed3D::render_default(), and Slic3r::GUI::Bed3D::render_model().
init_from() [1/4]
void Slic3r::GUI::GLModel::init_from (const indexed_triangle_set & its)
{
    this->init_from(its, bounding_box(its));
}
References Slic3r::bounding_box(), and init_from().
init_from() [2/4]
void Slic3r::GUI::GLModel::init_from (const indexed_triangle_set & its, const BoundingBoxf3 & bbox)
{
    if (!m_render_data.empty()) // call reset() if you want to reuse this model
        return;
    RenderData data;
    data.type = PrimitiveType::Triangles;
    std::vector<float> vertices = std::vector<float>(18 * its.indices.size());
    std::vector<unsigned int> indices = std::vector<unsigned int>(3 * its.indices.size());
    unsigned int vertices_count = 0;
    for (uint32_t i = 0; i < its.indices.size(); ++i) {
        stl_triangle_vertex_indices face      = its.indices[i];
        stl_vertex                  vertex[3] = { its.vertices[face[0]], its.vertices[face[1]], its.vertices[face[2]] };
        stl_vertex                  n         = face_normal_normalized(vertex);
        for (size_t j = 0; j < 3; ++ j) {
            size_t offset = i * 18 + j * 6;
            ::memcpy(static_cast<void*>(&vertices[offset]), static_cast<const void*>(vertex[j].data()), 3 * sizeof(float));
            ::memcpy(static_cast<void*>(&vertices[3 + offset]), static_cast<const void*>(n.data()), 3 * sizeof(float));
        }
        for (size_t j = 0; j < 3; ++j)
            indices[i * 3 + j] = vertices_count + j;
        vertices_count += 3;
    }
    data.indices_count = static_cast<unsigned int>(indices.size());
    m_bounding_box = bbox;
    send_to_gpu(data, vertices, indices);
    m_render_data.emplace_back(data);
}
References Slic3r::face_normal_normalized(), indexed_triangle_set::indices, Slic3r::GUI::GLModel::RenderData::indices_count, m_bounding_box, m_render_data, memcpy, n, Slic3r::offset(), send_to_gpu(), Triangles, Slic3r::GUI::GLModel::RenderData::type, and indexed_triangle_set::vertices.
init_from() [3/4]
void Slic3r::GUI::GLModel::init_from (const InitializationData & data)
{
    if (!m_render_data.empty()) // call reset() if you want to reuse this model
        return;
    for (const InitializationData::Entity& entity : data.entities) {
        if (entity.positions.empty() || entity.indices.empty())
            continue;
        assert(entity.normals.empty() || entity.normals.size() == entity.positions.size());
        RenderData rdata;
        rdata.type = entity.type;
        rdata.color = entity.color;
        // vertices/normals data
        std::vector<float> vertices(6 * entity.positions.size());
        for (size_t i = 0; i < entity.positions.size(); ++i) {
            const size_t offset = i * 6;
            ::memcpy(static_cast<void*>(&vertices[offset]), static_cast<const void*>(entity.positions[i].data()), 3 * sizeof(float));
            if (!entity.normals.empty())
                ::memcpy(static_cast<void*>(&vertices[3 + offset]), static_cast<const void*>(entity.normals[i].data()), 3 * sizeof(float));
        }
        // indices data
        std::vector<unsigned int> indices = entity.indices;
        rdata.indices_count = static_cast<unsigned int>(indices.size());
        // update bounding box
        for (size_t i = 0; i < entity.positions.size(); ++i) {
            m_bounding_box.merge(entity.positions[i].cast<double>());
        }
        send_to_gpu(rdata, vertices, indices);
        m_render_data.emplace_back(rdata);
    }
}
References Slic3r::GUI::GLModel::RenderData::color, Slic3r::GUI::GLModel::InitializationData::entities, Slic3r::GUI::GLModel::RenderData::indices_count, m_bounding_box, m_render_data, memcpy, Slic3r::BoundingBox3Base< PointClass >::merge(), Slic3r::offset(), send_to_gpu(), and Slic3r::GUI::GLModel::RenderData::type.
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoHollow::GLGizmoHollow(), Slic3r::GUI::GLGizmoMove3D::GLGizmoMove3D(), Slic3r::GUI::Selection::init(), init_from(), init_from(), init_from_file(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
init_from() [4/4]
void Slic3r::GUI::GLModel::init_from (const Polygons & polygons, float z)
{
    auto append_polygon = [](const Polygon& polygon, float z, GUI::GLModel::InitializationData& data) {
        if (!polygon.empty()) {
            GUI::GLModel::InitializationData::Entity entity;
            entity.type = GUI::GLModel::PrimitiveType::LineLoop;
            // contour
            entity.positions.reserve(polygon.size() + 1);
            entity.indices.reserve(polygon.size() + 1);
            unsigned int id = 0;
            for (const Point& p : polygon) {
                Vec3f position = unscale(p.x(), p.y(), 0.0).cast<float>();
                position.z() = z;
                entity.positions.emplace_back(position);
                entity.indices.emplace_back(id++);
            }
            data.entities.emplace_back(entity);
        }
    };
    InitializationData init_data;
    for (const Polygon& polygon : polygons) {
        append_polygon(polygon, z, init_data);
    }
    init_from(init_data);
}
References Slic3r::MultiPoint::empty(), Slic3r::GUI::GLModel::InitializationData::Entity::indices, init_from(), LineLoop, Slic3r::GUI::GLModel::InitializationData::Entity::positions, Slic3r::MultiPoint::size(), Slic3r::GUI::GLModel::InitializationData::Entity::type, and Slic3r::unscale().
init_from_file()
bool Slic3r::GUI::GLModel::init_from_file (const std::string & filename)
{
    if (!boost::filesystem::exists(filename))
        return false;
    if (!boost::algorithm::iends_with(filename, ".stl"))
        return false;
    Model model;
    try
    {
        model = Model::read_from_file(filename);
    }
    catch (std::exception&)
    {
        return false;
    }
    TriangleMesh mesh = model.mesh();
    init_from(mesh.its, mesh.bounding_box());
    m_filename = filename;
    return true;
}
References Slic3r::TriangleMesh::bounding_box(), init_from(), Slic3r::TriangleMesh::its, m_filename, Slic3r::Model::mesh(), and Slic3r::Model::read_from_file().
Referenced by Slic3r::GUI::Bed3D::render_model().
is_initialized()
bool Slic3r::GUI::GLModel::is_initialized () const inline
{ return !m_render_data.empty(); }
References m_render_data.
Referenced by Slic3r::GUI::GCodeViewer::TBuffer::has_data(), Slic3r::GUI::GLGizmoSimplify::on_render(), and Slic3r::GUI::Bed3D::Axes::render().
render()
void Slic3r::GUI::GLModel::render () const
{
    GLShaderProgram* shader = wxGetApp().get_current_shader();
    for (const RenderData& data : m_render_data) {
        if (data.vbo_id == 0 || data.ibo_id == 0)
            continue;
        GLenum mode;
        switch (data.type)
        {
        default:
        case PrimitiveType::Triangles: { mode = GL_TRIANGLES; break; }
        case PrimitiveType::Lines:     { mode = GL_LINES; break; }
        case PrimitiveType::LineStrip: { mode = GL_LINE_STRIP; break; }
        case PrimitiveType::LineLoop:  { mode = GL_LINE_LOOP; break; }
        }
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, data.vbo_id));
        glsafe(::glVertexPointer(3, GL_FLOAT, 6 * sizeof(float), (const void*)0));
        glsafe(::glNormalPointer(GL_FLOAT, 6 * sizeof(float), (const void*)(3 * sizeof(float))));
        glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
        glsafe(::glEnableClientState(GL_NORMAL_ARRAY));
        if (shader != nullptr)
            shader->set_uniform("uniform_color", data.color);
        else
            glsafe(::glColor4fv(data.color.data()));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, data.ibo_id));
        glsafe(::glDrawElements(mode, static_cast<GLsizei>(data.indices_count), GL_UNSIGNED_INT, (const void*)0));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
        glsafe(::glDisableClientState(GL_NORMAL_ARRAY));
        glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
    }
}
References GL_LINE_LOOP, GL_TRIANGLES, glsafe, LineLoop, Lines, LineStrip, m_render_data, Slic3r::GLShaderProgram::set_uniform(), and Triangles.
Referenced by Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GLVolume::SinkingContours::render(), Slic3r::GUI::Bed3D::Axes::render(), Slic3r::GUI::GLGizmoAdvancedCut::render_connector_model(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::Bed3D::render_model(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::Selection::render_sidebar_position_hints(), Slic3r::GUI::Selection::render_sidebar_rotation_hints(), and Slic3r::GUI::Selection::render_sidebar_scale_hints().
render_instanced()
void Slic3r::GUI::GLModel::render_instanced (unsigned int instances_vbo, unsigned int instances_count) const
{
    if (instances_vbo == 0)
        return;
    GLShaderProgram* shader = wxGetApp().get_current_shader();
    assert(shader == nullptr || boost::algorithm::iends_with(shader->get_name(), "_instanced"));
    // vertex attributes
    GLint position_id = (shader != nullptr) ? shader->get_attrib_location("v_position") : -1;
    GLint normal_id = (shader != nullptr) ? shader->get_attrib_location("v_normal") : -1;
    assert(position_id != -1 && normal_id != -1);
    // instance attributes
    GLint offset_id = (shader != nullptr) ? shader->get_attrib_location("i_offset") : -1;
    GLint scales_id = (shader != nullptr) ? shader->get_attrib_location("i_scales") : -1;
    assert(offset_id != -1 && scales_id != -1);
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, instances_vbo));
    if (offset_id != -1) {
        glsafe(::glVertexAttribPointer(offset_id, 3, GL_FLOAT, GL_FALSE, 5 * sizeof(float), (GLvoid*)0));
        glsafe(::glEnableVertexAttribArray(offset_id));
        glsafe(::glVertexAttribDivisor(offset_id, 1));
    }
    if (scales_id != -1) {
        glsafe(::glVertexAttribPointer(scales_id, 2, GL_FLOAT, GL_FALSE, 5 * sizeof(float), (GLvoid*)(3 * sizeof(float))));
        glsafe(::glEnableVertexAttribArray(scales_id));
        glsafe(::glVertexAttribDivisor(scales_id, 1));
    }
    for (const RenderData& data : m_render_data) {
        if (data.vbo_id == 0 || data.ibo_id == 0)
            continue;
        GLenum mode;
        switch (data.type)
        {
        default:
        case PrimitiveType::Triangles: { mode = GL_TRIANGLES; break; }
        case PrimitiveType::Lines:     { mode = GL_LINES; break; }
        case PrimitiveType::LineStrip: { mode = GL_LINE_STRIP; break; }
        case PrimitiveType::LineLoop:  { mode = GL_LINE_LOOP; break; }
        }
        if (shader != nullptr)
            shader->set_uniform("uniform_color", data.color);
        else
            glsafe(::glColor4fv(data.color.data()));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, data.vbo_id));
        if (position_id != -1) {
            glsafe(::glVertexAttribPointer(position_id, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(float), (GLvoid*)0));
            glsafe(::glEnableVertexAttribArray(position_id));
        }
        if (normal_id != -1) {
            glsafe(::glVertexAttribPointer(normal_id, 3, GL_FLOAT, GL_FALSE, 6 * sizeof(float), (GLvoid*)(3 * sizeof(float))));
            glsafe(::glEnableVertexAttribArray(normal_id));
        }
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, data.ibo_id));
        glsafe(::glDrawElementsInstanced(mode, static_cast<GLsizei>(data.indices_count), GL_UNSIGNED_INT, (const void*)0, instances_count));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
        if (normal_id != -1)
            glsafe(::glDisableVertexAttribArray(normal_id));
        if (position_id != -1)
            glsafe(::glDisableVertexAttribArray(position_id));
    }
    if (scales_id != -1)
        glsafe(::glDisableVertexAttribArray(scales_id));
    if (offset_id != -1)
        glsafe(::glDisableVertexAttribArray(offset_id));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
}
References Slic3r::GLShaderProgram::get_attrib_location(), Slic3r::GLShaderProgram::get_name(), GL_FALSE, GL_LINE_LOOP, GL_TRIANGLES, glsafe, LineLoop, Lines, LineStrip, m_render_data, Slic3r::GLShaderProgram::set_uniform(), and Triangles.
reset()
void Slic3r::GUI::GLModel::reset ()
{
    for (RenderData& data : m_render_data) {
        // release gpu memory
        if (data.ibo_id > 0)
            glsafe(::glDeleteBuffers(1, &data.ibo_id));
        if (data.vbo_id > 0)
            glsafe(::glDeleteBuffers(1, &data.vbo_id));
    }
    m_render_data.clear();
    m_bounding_box = BoundingBoxf3();
    m_filename = std::string();
}
References glsafe, m_bounding_box, m_filename, and m_render_data.
Referenced by Slic3r::GUI::GLGizmoSimplify::~GLGizmoSimplify(), ~GLModel(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::Bed3D::set_shape(), Slic3r::GUI::Bed3D::Axes::set_stem_length(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
send_to_gpu()
void Slic3r::GUI::GLModel::send_to_gpu (RenderData & data, const std::vector< float > & vertices, const std::vector< unsigned int > & indices) private
{
    assert(data.vbo_id == 0);
    assert(data.ibo_id == 0);
    // vertex data -> send to gpu
    glsafe(::glGenBuffers(1, &data.vbo_id));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, data.vbo_id));
    glsafe(::glBufferData(GL_ARRAY_BUFFER, vertices.size() * sizeof(float), vertices.data(), GL_STATIC_DRAW));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
    // indices data -> send to gpu
    glsafe(::glGenBuffers(1, &data.ibo_id));
    glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, data.ibo_id));
    glsafe(::glBufferData(GL_ELEMENT_ARRAY_BUFFER, indices.size() * sizeof(unsigned int), indices.data(), GL_STATIC_DRAW));
    glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
}
References glsafe, Slic3r::GUI::GLModel::RenderData::ibo_id, and Slic3r::GUI::GLModel::RenderData::vbo_id.
Referenced by init_from(), and init_from().
set_color()
void Slic3r::GUI::GLModel::set_color (int entity_id, const std::array< float, 4 > & color)
{
    for (size_t i = 0; i < m_render_data.size(); ++i) {
        if (entity_id == -1 || static_cast<int>(i) == entity_id)
            m_render_data[i].color = color;
    }
}
References m_render_data.
Referenced by Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoAdvancedCut::render_connector_model(), Slic3r::GUI::Bed3D::render_internal(), Slic3r::GUI::Bed3D::render_model(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
Member Data Documentation
m_bounding_box
BoundingBoxf3 Slic3r::GUI::GLModel::m_bounding_box private
Referenced by get_bounding_box(), init_from(), init_from(), and reset().
m_filename
std::string Slic3r::GUI::GLModel::m_filename private
Referenced by get_filename(), init_from_file(), and reset().
m_render_data
std::vector<RenderData> Slic3r::GUI::GLModel::m_render_data private
Referenced by init_from(), init_from(), is_initialized(), render(), render_instanced(), reset(), and set_color().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLModel.hpp
src/slic3r/GUI/GLModel.cpp