OrcaSlicer: Slic3r::GUI::NotificationManager::ProgressBarNotification Class Reference
Slic3r::GUI::NotificationManager::ProgressBarNotification Class Reference
Public Types
enum class EState {
Unknown , Hidden , Shown , NotFading ,
FadingOut , ClosePending , Finished , Hovered ,
Paused
}
Public Member Functions
ProgressBarNotification (const NotificationData &n, NotificationIDProvider &id_provider, wxEvtHandler *evt_handler)
virtual void set_percentage (float percent)
virtual void render (GLCanvas3D &canvas, float initial_y, bool move_from_overlay, float overlay_width, float right_margin)
virtual void bbl_render_block_notification (GLCanvas3D &canvas, float initial_y, bool move_from_overlay, float overlay_width, float right_margin)
virtual void close ()
void update (const NotificationData &n)
void append (const std::string &append_str)
bool is_finished () const
void reinit ()
float get_top () const
float get_bottom () const
float get_current_top () const
const NotificationType get_type () const
const NotificationData & get_data () const
std::string get_text1 () const
const bool is_gray () const
void set_gray (bool g)
virtual bool compare_text (const std::string &text) const
void hide (bool h)
virtual bool update_state (bool paused, const int64_t delta)
int64_t next_render () const
EState get_state () const
bool is_hovered () const
void set_hovered ()
void reset_timer ()
void set_Multiline (bool Multi)
void on_change_color_mode (bool is_dark)
Protected Member Functions
virtual void init () override
virtual void render_text (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override
virtual void render_bar (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y)
virtual void render_cancel_button (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y)
void render_minimize_button (ImGuiWrapper &imgui, const float win_pos_x, const float win_pos_y) override
virtual void set_next_window_size (ImGuiWrapper &imgui)
virtual void render_close_button (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y)
virtual void render_hypertext (ImGuiWrapper &imgui, const float text_x, const float text_y, const std::string text, bool more=false)
virtual void bbl_render_block_notif_text (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y)
virtual void bbl_render_block_notif_buttons (ImGuiWrapper &imgui, ImVec2 win_size, ImVec2 win_pos)
virtual void bbl_render_block_notif_left_sign (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y)
virtual void bbl_render_left_sign (ImGuiWrapper &imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y)
virtual void render_left_sign (ImGuiWrapper &imgui)
virtual bool on_text_click ()
virtual void count_spaces ()
virtual void count_lines ()
virtual bool push_background_color ()
virtual int get_duration ()
void use_bbl_theme ()
void restore_default_theme ()
Protected Attributes
float m_percentage {0.0f}
bool m_has_cancel_button {false}
bool m_render_percentage {false}
bool m_is_dark = false
const NotificationData m_data
NotificationIDProvider & m_id_provider
int m_id { 0 }
ImGUITheme m_DefaultTheme
ImVec4 m_WindowBkgColor
ImVec4 m_TextColor
ImVec4 m_HyperTextColor
ImVec4 m_ErrorColor
ImVec4 m_WarnColor
ImVec4 m_NormalColor
ImVec4 m_CurrentColor
float m_WindowRadius
EState m_state { EState::Unknown }
int64_t m_fading_start { 0LL }
int64_t m_notification_start
int64_t m_next_render { std::numeric_limits<int64_t>::max() }
float m_current_fade_opacity { 1.0f }
std::string m_text1
std::string m_hypertext
std::string m_text2
size_t pos_start = string::npos
size_t pos_end = string::npos
std::string error_start = "<Error>"
std::string error_end = "</Error>"
float m_window_width_offset
float m_left_indentation
float m_window_height { 56.0f }
float m_window_width { 450.0f }
float m_top_y { 0.0f }
float m_bottom_y { 0.0f }
float m_line_height
std::vector< size_t > m_endlines
std::vector< size_t > m_endlines2
bool m_is_gray { false }
bool m_multiline { false }
bool m_minimize_b_visible { false }
size_t m_lines_count { 1 }
wxEvtHandler * m_evt_handler
Detailed Description
Member Enumeration Documentation
EState
enum class Slic3r::GUI::NotificationManager::PopNotification::EState strong inherited
Enumerator
Unknown
Hidden
Shown
NotFading
FadingOut
ClosePending
Finished
Hovered
Paused
    {
      Unknown,      // NOT initialized
      Hidden,
      Shown,        // Requesting Render at some time if duration != 0
      NotFading,      // Never jumps to state Fading out even if duration says so
      FadingOut,        // Requesting Render at some time
      ClosePending,     // Requesting Render
      Finished,         // Requesting Render
      Hovered,      // Followed by Shown
      Paused
    };
Constructor & Destructor Documentation
ProgressBarNotification()
Slic3r::GUI::NotificationManager::ProgressBarNotification::ProgressBarNotification (const NotificationData & n, NotificationIDProvider & id_provider, wxEvtHandler * evt_handler) inline
: PopNotification(n, id_provider, evt_handler) { }
Member Function Documentation
append()
void Slic3r::GUI::NotificationManager::PopNotification::append (const std::string & append_str) inherited
{
  m_text1            = m_text1 + "\n" + append_str;
  //m_hypertext      = n.hypertext;
  //m_text2          = n.text2;
  //const_cast<NotificationData&>(m_data).callback   = n.callback;
  init();
  m_multiline        = false;
}
References Slic3r::GUI::NotificationManager::init().
bbl_render_block_notif_buttons()
void Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notif_buttons (ImGuiWrapper & imgui, ImVec2 win_size, ImVec2 win_pos) protected virtual inherited
{
  // close button
    ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(.0f, .0f, .0f, .0f));
  ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(.0f, .0f, .0f, .0f));
  push_style_color(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 1.f), m_state == EState::FadingOut, m_current_fade_opacity);
  push_style_color(ImGuiCol_TextSelectedBg, ImVec4(0, .75f, .75f, 1.f), m_state == EState::FadingOut, m_current_fade_opacity);
  ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(.0f, .0f, .0f, .0f));
  std::wstring button_text;
  button_text = ImGui::CloseBlockNotifButton;
  ImVec2 button_pic_size = ImGui::CalcTextSize(into_u8(button_text).c_str());
  ImVec2 button_size(button_pic_size.x * 2.f, button_pic_size.y * 2.f);
  ImVec2 cursor_pos = { win_size.x - m_line_height * 2.0f, win_size.y / 2 - button_size.y / 2 };
  ImGui::SetCursorPos(cursor_pos);
  //if (ImGui::IsMouseHoveringRect(ImVec2(win_pos.x - win_size.x / 10.f, win_pos.y + win_size.y / 2 - button_pic_size.y),
  //  ImVec2(win_pos.x - win_size.x / 20.f, win_pos.y + win_size.y / 2 + button_pic_size.y),
  //  true))
  if(ImGui::IsMouseHoveringRect(win_pos + cursor_pos, win_pos + cursor_pos + button_size))
  {
    button_text = ImGui::CloseBlockNotifHoverButton;
  }
  if (imgui.button(button_text.c_str(), button_size.x, button_size.y))
  {
    close();
  }
  ImGui::PopStyleColor(5);
  //ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(.0f, .0f, .0f, .0f));
  //ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(.0f, .0f, .0f, .0f));
  //push_style_color(ImGuiCol_ButtonActive, ImGui::GetStyleColorVec4(ImGuiCol_WindowBg), m_state == EState::FadingOut, m_current_fade_opacity);
  //push_style_color(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 1.f), m_state == EState::FadingOut, m_current_fade_opacity);
  //push_style_color(ImGuiCol_TextSelectedBg, ImVec4(0, .75f, .75f, 1.f), m_state == EState::FadingOut, m_current_fade_opacity);
  //std::wstring button_text;
  //button_text = m_is_dark ? ImGui::MinimalizeDarkButton : ImGui::MinimalizeButton;
  //if (ImGui::IsMouseHoveringRect(ImVec2(win_pos_x - m_window_width / 10.f, win_pos_y + m_window_height - 2 * m_line_height + 1),
  //  ImVec2(win_pos_x, win_pos_y + m_window_height),
  //  true))
  //{
  //  button_text = m_is_dark ? ImGui::MinimalizeHoverDarkButton : ImGui::MinimalizeHoverButton;
  //}
  //ImVec2 button_pic_size = ImGui::CalcTextSize(into_u8(button_text).c_str());
  //ImVec2 button_size(button_pic_size.x * 1.25f, button_pic_size.y * 1.25f);
  //ImGui::SetCursorPosX(m_window_width - m_line_height * 1.8f);
  //ImGui::SetCursorPosY(m_window_height - button_size.y - 5);
  //if (imgui.button(button_text.c_str(), button_size.x, button_size.y))
  //{
  //  m_multiline = false;
  //}
  //ImGui::PopStyleColor(5);
  //m_minimize_b_visible = true;
}
References Slic3r::GUI::ImGuiWrapper::button(), ImGui::CalcTextSize(), ImGui::CloseBlockNotifButton, ImGui::CloseBlockNotifHoverButton, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiCol_TextSelectedBg, Slic3r::GUI::into_u8(), ImGui::IsMouseHoveringRect(), ImGui::PopStyleColor(), ImGui::PushStyleColor(), ImGui::SetCursorPos(), ImVec2::x, and ImVec2::y.
bbl_render_block_notif_left_sign()
void Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notif_left_sign (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) protected virtual inherited
{
  auto window = ImGui::GetCurrentWindow();
  //window->DrawList->AddImage(user_texture_id, bb.Min + padding + margin, bb.Max - padding - margin, uv0, uv1, ImGui::GetColorU32(tint_col));
  std::wstring text;
  text = ImGui::BlockNotifErrorIcon;
  ImGui::SetCursorPosX(m_line_height / 3);
  ImGui::SetCursorPosY(m_window_height / 2 - m_line_height);
  imgui.text(text.c_str());
}
References ImGui::BlockNotifErrorIcon, ImGui::GetCurrentWindow(), ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), and Slic3r::GUI::ImGuiWrapper::text().
bbl_render_block_notif_text()
void Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notif_text (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) protected virtual inherited
{
  float x_offset = m_left_indentation;
  int   last_end = 0;
  float starting_y = (m_lines_count == 2 ? win_size_y / 2 - m_line_height : (m_lines_count == 1 ? win_size_y / 2 - m_line_height / 2 : m_line_height / 2));
  float shift_y = m_line_height;
  std::string line;
  for (size_t i = 0; i < (m_multiline ? m_endlines.size() : std::min(m_endlines.size(), (size_t)2)); i++) {
    assert(m_endlines.size() > i && m_text1.size() >= m_endlines[i]);
    line.clear();
    ImGui::SetCursorPosX(x_offset);
    ImGui::SetCursorPosY(starting_y + i * shift_y);
    if (m_endlines.size() > i && m_text1.size() >= m_endlines[i]) {
      if (i == 1 && m_endlines.size() > 2 && !m_multiline) {
        // second line with "more" hypertext
        line = m_text1.substr(m_endlines[0] + (m_text1[m_endlines[0]] == '\n' || m_text1[m_endlines[0]] == ' ' ? 1 : 0), m_endlines[1] - m_endlines[0] - (m_text1[m_endlines[0]] == '\n' || m_text1[m_endlines[0]] == ' ' ? 1 : 0));
        while (ImGui::CalcTextSize(line.c_str()).x > m_window_width - m_window_width_offset - ImGui::CalcTextSize((".." + _u8L("More")).c_str()).x) {
          line = line.substr(0, line.length() - 1);
        }
        line += "..";
      }
      else {
        // regural line
        line = m_text1.substr(last_end, m_endlines[i] - last_end);
      }
      last_end = m_endlines[i];
      if (m_text1.size() > m_endlines[i])
        last_end += (m_text1[m_endlines[i]] == '\n' || m_text1[m_endlines[i]] == ' ' ? 1 : 0);
      if (pos_start != string::npos && pos_end != string::npos && m_endlines[i] - line.length() >= pos_start && m_endlines[i] <= pos_end) {
        push_style_color(ImGuiCol_Text, m_ErrorColor, m_state == EState::FadingOut, m_current_fade_opacity);
        imgui.text(line.c_str());
        ImGui::PopStyleColor();
      }
      else {
        imgui.text(line.c_str());
      }
    }
  }
  //hyperlink text
  if (!m_multiline && m_lines_count > 2) {
    render_hypertext(imgui, x_offset + ImGui::CalcTextSize((line + " ").c_str()).x, starting_y + shift_y, _u8L("More"), true);
  }
  else if (!m_hypertext.empty()) {
    const ImVec2 button_size = {52, 28};
    ImVec2 cursor_pos = { win_size_x - m_line_height * 6.0f, win_size_y / 2 - button_size.y / 2 };
    ImGui::SetCursorPos(cursor_pos);
    ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1);
    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 2);
    ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(1.f, 1.f, 1.f, 1.f));
    ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(1.f, 1.f, 1.f, 0.f));
        //if (imgui.button(_L("Jump"), button_size.x, button_size.y)) { if (on_text_click()) { close(); } }
    ImGui::PopStyleColor(2);
    ImGui::PopStyleVar(2);
    render_hypertext(imgui, x_offset + ImGui::CalcTextSize((line + (line.empty() ? "" : " ")).c_str()).x, starting_y + (m_endlines.size() - 1) * shift_y, m_hypertext);
  }
  // text2 (text after hypertext) is not rendered for regular notifications
  // its rendering is in HintNotification::render_text
}
References _u8L, ImGui::CalcTextSize(), ImGuiCol_Border, ImGuiCol_Button, ImGuiCol_Text, ImGuiStyleVar_FrameBorderSize, ImGuiStyleVar_FrameRounding, ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::SetCursorPos(), ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), Slic3r::GUI::ImGuiWrapper::text(), and ImVec2::y.
bbl_render_block_notification()
void Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notification (GLCanvas3D & canvas, float initial_y, bool move_from_overlay, float overlay_width, float right_margin) virtual inherited
{
  if (m_state == EState::Unknown)
    init();
  if (m_state == EState::Hidden) {
    m_top_y = initial_y - GAP_WIDTH;
    return;
  }
  if (m_state == EState::ClosePending || m_state == EState::Finished)
  {
    m_state = EState::Finished;
    return;
  }
  Size          cnv_size = canvas.get_canvas_size();
  ImGuiWrapper& imgui = *wxGetApp().imgui();
    float         right_gap  = right_margin + (move_from_overlay ? overlay_width + m_line_height * 5 : 0);
  bool          fading_pop = false;
  if (m_line_height != ImGui::CalcTextSize("A").y)
    init();
  set_next_window_size(imgui);
  // top y of window
    m_top_y = initial_y + m_window_height;
    ImVec2 win_pos(1.0f * (float) cnv_size.get_width() - right_gap, 1.0f * (float) cnv_size.get_height() - m_top_y);
    imgui.set_next_window_pos(win_pos.x, win_pos.y, ImGuiCond_Always, 1.0f, 0.0f);
    imgui.set_next_window_size(m_window_width, m_window_height, ImGuiCond_Always);
  // color change based on fading out
  if (m_state == EState::FadingOut) {
    push_style_color(ImGuiCol_WindowBg, ImGui::GetStyleColorVec4(ImGuiCol_WindowBg), true, m_current_fade_opacity);
    push_style_color(ImGuiCol_Text, ImGui::GetStyleColorVec4(ImGuiCol_Text), true, m_current_fade_opacity);
    push_style_color(ImGuiCol_ButtonHovered, ImGui::GetStyleColorVec4(ImGuiCol_ButtonHovered), true, m_current_fade_opacity);
    fading_pop = true;
  }
  bool bgrnd_color_pop = push_background_color();
  // name of window indentifies window - has to be unique string
  if (m_id == 0)
    m_id = m_id_provider.allocate_id();
  std::string name = "!!Ntfctn" + std::to_string(m_id);
  use_bbl_theme();
    if (m_data.level == NotificationLevel::SeriousWarningNotificationLevel)
  {
        push_style_color(ImGuiCol_Border, {245.f / 255.f, 155 / 255.f, 22 / 255.f, 1}, true, m_current_fade_opacity);
        push_style_color(ImGuiCol_WindowBg, {245.f / 255.f, 155 / 255.f, 22 / 255.f, 1}, true, m_current_fade_opacity);
  }
    if (m_data.level == NotificationLevel::ErrorNotificationLevel) {
        push_style_color(ImGuiCol_Border, {225.f / 255.f, 71 / 255.f, 71 / 255.f, 1}, true, m_current_fade_opacity);
        push_style_color(ImGuiCol_WindowBg, {225.f / 255.f, 71 / 255.f, 71 / 255.f, 1}, true, m_current_fade_opacity);
    }
  push_style_color(ImGuiCol_Text, { 1,1,1,1 }, true, m_current_fade_opacity);
  if (imgui.begin(name, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse)) {
    ImVec2 win_size = ImGui::GetWindowSize();
    ImVec2 win_pos = ImGui::GetWindowPos();
    if (ImGui::IsMouseHoveringRect(win_pos, win_pos + win_size)) {
      set_hovered();
    }
    //render left icon
    bbl_render_block_notif_left_sign(imgui, win_size.x, win_size.y, win_pos.x, win_pos.y);
    bbl_render_block_notif_text(imgui, win_size.x, win_size.y, win_pos.x, win_pos.y);
    bbl_render_block_notif_buttons(imgui, win_size, win_pos);
    //render_close_button(imgui, win_size.x, win_size.y, win_pos.x, win_pos.y);
    //m_minimize_b_visible = false;
    //if (m_multiline && m_lines_count > 3)
    //  render_minimize_button(imgui, win_pos.x, win_pos.y);
  }
  ImGui::BringWindowToDisplayFront(ImGui::GetCurrentWindow());
  imgui.end();
  ImGui::PopStyleColor(3);
  restore_default_theme();
  if (bgrnd_color_pop)
    ImGui::PopStyleColor();
  if (fading_pop)
    ImGui::PopStyleColor(3);
}
References Slic3r::GUI::NotificationManager::NotificationIDProvider::allocate_id(), Slic3r::GUI::ImGuiWrapper::begin(), ImGui::BringWindowToDisplayFront(), ImGui::CalcTextSize(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::NotificationManager::ErrorNotificationLevel, GAP_WIDTH, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), ImGui::GetCurrentWindow(), ImGui::GetStyleColorVec4(), ImGui::GetWindowPos(), ImGui::GetWindowSize(), ImGuiCol_Border, ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiCol_WindowBg, ImGuiCond_Always, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImGuiWindowFlags_NoTitleBar, Slic3r::GUI::NotificationManager::init(), ImGui::IsMouseHoveringRect(), Slic3r::GUI::NotificationManager::m_id_provider, ImGui::PopStyleColor(), Slic3r::GUI::NotificationManager::SeriousWarningNotificationLevel, Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::ImGuiWrapper::set_next_window_size(), ImVec2::x, and ImVec2::y.
bbl_render_left_sign()
void Slic3r::GUI::NotificationManager::PopNotification::bbl_render_left_sign (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) protected virtual inherited
{
    ImDrawList *draw_list = ImGui::GetWindowDrawList();
  ImVec2 round_rect_pos = ImVec2(win_pos_x - win_size_x + ImGui::GetStyle().WindowBorderSize, win_pos_y + ImGui::GetStyle().WindowBorderSize);
    ImVec2 round_rect_size = ImVec2(m_WindowRadius * 2, win_size_y - 2 * ImGui::GetStyle().WindowBorderSize);
  ImVec2 rect_pos = round_rect_pos + ImVec2(m_WindowRadius, 0);
    ImVec2 rect_size = ImVec2(round_rect_size.x / 2, round_rect_size.y);
  ImU32 clr = ImGui::GetColorU32(ImVec4(m_CurrentColor.x, m_CurrentColor.y, m_CurrentColor.z, m_current_fade_opacity));
    draw_list->AddRectFilled(round_rect_pos, round_rect_pos + round_rect_size, clr, m_WindowRadius);
    draw_list->AddRectFilled(rect_pos, rect_pos + rect_size, clr, 0);
}
References ImDrawList::AddRectFilled(), ImGui::GetColorU32(), ImGui::GetStyle(), ImGui::GetWindowDrawList(), ImVec2::x, and ImVec2::y.
close()
virtual void Slic3r::GUI::NotificationManager::PopNotification::close () inline virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::PlaterWarningNotification, and Slic3r::GUI::NotificationManager::UpdatedItemsInfoNotification.
{ m_state = EState::ClosePending; wxGetApp().plater()->get_current_canvas3D()->schedule_extra_frame(0);}
References Slic3r::GUI::NotificationManager::PopNotification::ClosePending, and Slic3r::GUI::NotificationManager::PopNotification::m_state.
Referenced by Slic3r::GUI::NotificationManager::UpdatedItemsInfoNotification::close().
compare_text()
bool Slic3r::GUI::NotificationManager::PopNotification::compare_text (const std::string & text) const virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification.
{
  std::wstring wt1 = boost::nowide::widen(m_text1);
  std::wstring wt2 = boost::nowide::widen(text);
  wt1.erase(std::remove_if(wt1.begin(), wt1.end(), ::iswspace), wt1.end());
  wt2.erase(std::remove_if(wt2.begin(), wt2.end(), ::iswspace), wt2.end());
  if (wt1.compare(wt2) == 0)
    return true;
  return false;
}
References boost::nowide::widen().
count_lines()
void Slic3r::GUI::NotificationManager::PopNotification::count_lines () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification.
{
  std::string text    = m_text1;
  size_t      last_end  = 0;
  m_lines_count     = 0;
  if (text.empty())
    return;
  // handle with marks
    if (pos_start == string::npos && pos_end == string::npos) {
        pos_start = text.find(error_start);
        if (pos_start != string::npos) {
            text.erase(pos_start, error_start.length());
            pos_end = text.find(error_end);
            if (pos_end != string::npos) {
                text.erase(pos_end, error_end.length());
            }
        }
        m_text1 = text;
    }
  m_endlines.clear();
  while (last_end < text.length())
  {
    size_t next_hard_end = text.find_first_of('\n', last_end);
    if (next_hard_end != std::string::npos && ImGui::CalcTextSize(text.substr(last_end, next_hard_end - last_end).c_str()).x < m_window_width - m_window_width_offset) {
      //next line is ended by '/n'
      m_endlines.push_back(next_hard_end);
      last_end = next_hard_end + 1;
    }
    else {
      // find next suitable endline
      if (ImGui::CalcTextSize(text.substr(last_end).c_str()).x >= m_window_width - m_window_width_offset) {
        // more than one line till end
        size_t next_space = text.find_first_of(' ', last_end);
        if (next_space > 0 && next_space < text.length()) {
                    size_t next_space_candidate = text.find_first_of(' ', next_space + 1);
          while (next_space_candidate > 0 && ImGui::CalcTextSize(text.substr(last_end, next_space_candidate - last_end).c_str()).x < m_window_width - m_window_width_offset) {
            next_space = next_space_candidate;
            next_space_candidate = text.find_first_of(' ', next_space + 1);
          }
        } else {
          next_space = text.length();
        }
        // when one word longer than line.
        if (ImGui::CalcTextSize(text.substr(last_end, next_space - last_end).c_str()).x > m_window_width - m_window_width_offset ||
          ImGui::CalcTextSize(text.substr(last_end, next_space - last_end).c_str()).x < (m_window_width - m_window_width_offset) / 4 * 3
          ) {
          //BBS
          wxString wx_text = from_u8(text.substr(last_end, text.length() - last_end).c_str());
                    float    width_of_char = ImGui::CalcTextSize("a").x;
                    int letter_count = (int) ((m_window_width - m_window_width_offset) / width_of_char) / 2;  // give a predict value of char count
          int output_count = 0;
          while (true) {
                        if (letter_count >= wx_text.size())
              break;
                        float used_space = ImGui::CalcTextSize(into_u8(wx_text.SubString(0, letter_count)).c_str()).x;
                        if (used_space > m_window_width - m_window_width_offset)
              break;
            letter_count++;
          }
          if (letter_count > 0) {
            output_count = into_u8(wx_text.SubString(0, letter_count - 1)).size();
                    }
                    m_endlines.push_back(last_end + output_count);
                    last_end += output_count;
        } else {
          m_endlines.push_back(next_space);
          last_end = next_space + 1;
        }
      }
      else {
        m_endlines.push_back(text.length());
        last_end = text.length();
      }
    }
    m_lines_count++;
  }
  // hypertext calculation
  if (!m_hypertext.empty()) {
    int prev_end = m_endlines.size() > 1 ? m_endlines[m_endlines.size() - 2] : 0; // m_endlines.size() - 2 because we are fitting hypertext instead of last endline
    if (ImGui::CalcTextSize((escape_string_cstyle(text.substr(prev_end, last_end - prev_end)) + m_hypertext).c_str()).x > m_window_width - m_window_width_offset) {
      m_endlines.push_back(last_end);
      m_lines_count++;
    }
  }
  // m_text_2 (text after hypertext) is not used for regular notifications right now.
  // its caluculation is in HintNotification::count_lines()
}
References ImGui::CalcTextSize(), Slic3r::escape_string_cstyle(), Slic3r::GUI::from_u8(), int, Slic3r::GUI::into_u8(), and ImVec2::x.
count_spaces()
void Slic3r::GUI::NotificationManager::PopNotification::count_spaces () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification, Slic3r::GUI::NotificationManager::PrintHostUploadNotification, Slic3r::GUI::NotificationManager::ExportFinishedNotification, and Slic3r::GUI::NotificationManager::UpdatedItemsInfoNotification.
{
  //determine line width
  m_line_height = ImGui::CalcTextSize("A").y;
  m_left_indentation = m_line_height;
  //if (m_data.level == NotificationLevel::ErrorNotificationLevel
  //  || m_data.level == NotificationLevel::WarningNotificationLevel
  //  || m_data.level == NotificationLevel::PrintInfoNotificationLevel
  //  || m_data.level == NotificationLevel::PrintInfoShortNotificationLevel) {
  //  std::string text;
  //  text = (m_data.level == NotificationLevel::ErrorNotificationLevel ? ImGui::ErrorMarker : ImGui::WarningMarker);
  //  float picture_width = ImGui::CalcTextSize(text.c_str()).x;
  //  m_left_indentation = picture_width + m_line_height / 2;
  //}
  m_window_width_offset = m_left_indentation + m_line_height * 3.f;
    if (m_data.level == NotificationLevel::ErrorNotificationLevel || m_data.level == NotificationLevel::SeriousWarningNotificationLevel) {
    m_left_indentation = 32 + m_line_height;
    m_window_width_offset = 90.f;
  }
  m_window_width = m_line_height * 25;
}
References ImGui::CalcTextSize(), Slic3r::GUI::NotificationManager::ErrorNotificationLevel, Slic3r::GUI::NotificationManager::SeriousWarningNotificationLevel, and ImVec2::y.
Referenced by Slic3r::GUI::NotificationManager::ExportFinishedNotification::count_spaces().
get_bottom()
float Slic3r::GUI::NotificationManager::PopNotification::get_bottom () const inline inherited
{ return m_bottom_y; }
References Slic3r::GUI::NotificationManager::PopNotification::m_bottom_y.
get_current_top()
float Slic3r::GUI::NotificationManager::PopNotification::get_current_top () const inline inherited
{ return m_top_y; }
References Slic3r::GUI::NotificationManager::PopNotification::m_top_y.
get_data()
const NotificationData & Slic3r::GUI::NotificationManager::PopNotification::get_data () const inline inherited
{ return m_data; }
References Slic3r::GUI::NotificationManager::PopNotification::m_data.
Referenced by Slic3r::GUI::NotificationManager::activate_existing().
get_duration()
virtual int Slic3r::GUI::NotificationManager::PopNotification::get_duration () inline protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::SlicingProgressNotification.
{ return m_data.duration; }
References Slic3r::GUI::NotificationManager::NotificationData::duration, and Slic3r::GUI::NotificationManager::PopNotification::m_data.
get_state()
EState Slic3r::GUI::NotificationManager::PopNotification::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::NotificationManager::PopNotification::m_state.
get_text1()
std::string Slic3r::GUI::NotificationManager::PopNotification::get_text1 () const inline inherited
{ return m_text1; }
References Slic3r::GUI::NotificationManager::PopNotification::m_text1.
get_top()
float Slic3r::GUI::NotificationManager::PopNotification::get_top () const inline inherited
{ return m_top_y; }
References Slic3r::GUI::NotificationManager::PopNotification::m_top_y.
get_type()
const NotificationType Slic3r::GUI::NotificationManager::PopNotification::get_type () const inline inherited
{ return m_data.type; }
References Slic3r::GUI::NotificationManager::PopNotification::m_data, and Slic3r::GUI::NotificationManager::NotificationData::type.
Referenced by Slic3r::GUI::NotificationManager::activate_existing().
hide()
void Slic3r::GUI::NotificationManager::PopNotification::hide (bool h) inline inherited
{ if (is_finished()) return; m_state = h ? EState::Hidden : EState::Unknown; }
References Slic3r::GUI::NotificationManager::PopNotification::Hidden, Slic3r::GUI::NotificationManager::PopNotification::is_finished(), Slic3r::GUI::NotificationManager::PopNotification::m_state, and Slic3r::GUI::NotificationManager::PopNotification::Unknown.
init()
void Slic3r::GUI::NotificationManager::ProgressBarNotification::init () override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::PopNotification.
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification, Slic3r::GUI::NotificationManager::SlicingProgressNotification, and Slic3r::GUI::NotificationManager::ProgressIndicatorNotification.
{
  PopNotification::init();
  //m_lines_count++;
  if (m_endlines.empty()) {
    m_endlines.push_back(0);
  }
  if(m_lines_count >= 2) {
    m_lines_count = 3;
    m_multiline = true;
    while (m_endlines.size() < 3)
      m_endlines.push_back(m_endlines.back());
  } else {
    m_lines_count = 2;
    m_endlines.push_back(m_endlines.back());
    m_multiline = false;
  }
  if(m_state == EState::Shown)
    m_state = EState::NotFading;
}
References Slic3r::GUI::NotificationManager::PopNotification::init().
Referenced by Slic3r::GUI::NotificationManager::PrintHostUploadNotification::init(), and Slic3r::GUI::NotificationManager::SlicingProgressNotification::init().
is_finished()
bool Slic3r::GUI::NotificationManager::PopNotification::is_finished () const inline inherited
{ return m_state == EState::ClosePending || m_state == EState::Finished; }
References Slic3r::GUI::NotificationManager::PopNotification::ClosePending, Slic3r::GUI::NotificationManager::PopNotification::Finished, and Slic3r::GUI::NotificationManager::PopNotification::m_state.
Referenced by Slic3r::GUI::NotificationManager::PlaterWarningNotification::close(), Slic3r::GUI::NotificationManager::PopNotification::hide(), and Slic3r::GUI::NotificationManager::PopNotification::next_render().
is_gray()
const bool Slic3r::GUI::NotificationManager::PopNotification::is_gray () const inline inherited
{ return m_is_gray; }
References Slic3r::GUI::NotificationManager::PopNotification::m_is_gray.
is_hovered()
bool Slic3r::GUI::NotificationManager::PopNotification::is_hovered () const inline inherited
{ return m_state == EState::Hovered; }
References Slic3r::GUI::NotificationManager::PopNotification::Hovered, and Slic3r::GUI::NotificationManager::PopNotification::m_state.
next_render()
int64_t Slic3r::GUI::NotificationManager::PopNotification::next_render () const inline inherited
{ return is_finished() ? 0 : m_next_render; }
References Slic3r::GUI::NotificationManager::PopNotification::is_finished(), and Slic3r::GUI::NotificationManager::PopNotification::m_next_render.
on_change_color_mode()
void Slic3r::GUI::NotificationManager::PopNotification::on_change_color_mode (bool is_dark) inherited
{
  m_is_dark = is_dark;
}
References Slic3r::GUI::NotificationManager::m_is_dark.
on_text_click()
bool Slic3r::GUI::NotificationManager::PopNotification::on_text_click () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification, and Slic3r::GUI::NotificationManager::ExportFinishedNotification.
{
  if(m_data.callback != nullptr)
    return m_data.callback(m_evt_handler);
  return false;
}
References Slic3r::GUI::NotificationManager::m_evt_handler.
push_background_color()
bool Slic3r::GUI::NotificationManager::PopNotification::push_background_color () protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification.
{
  if (m_is_gray) {
    ImVec4 backcolor(0.7f, 0.7f, 0.7f, 0.5f);
    push_style_color(ImGuiCol_WindowBg, backcolor, m_state == EState::FadingOut, m_current_fade_opacity);
    return true;
  }
  if (m_data.level == NotificationLevel::ErrorNotificationLevel) {
    ImVec4 backcolor = ImGui::GetStyleColorVec4(ImGuiCol_WindowBg);
    backcolor.x += 0.3f;
    push_style_color(ImGuiCol_WindowBg, backcolor, m_state == EState::FadingOut, m_current_fade_opacity);
    return true;
  }
  if (m_data.level == NotificationLevel::WarningNotificationLevel) {
    ImVec4 backcolor = ImGui::GetStyleColorVec4(ImGuiCol_WindowBg);
    backcolor.x += 0.3f;
    backcolor.y += 0.15f;
    push_style_color(ImGuiCol_WindowBg, backcolor, m_state == EState::FadingOut, m_current_fade_opacity);
    return true;
  }
  return false;
}
References Slic3r::GUI::NotificationManager::ErrorNotificationLevel, ImGui::GetStyleColorVec4(), ImGuiCol_WindowBg, Slic3r::GUI::NotificationManager::WarningNotificationLevel, ImVec4::x, and ImVec4::y.
reinit()
void Slic3r::GUI::NotificationManager::PopNotification::reinit () inline inherited
{ m_state = EState::Unknown; }
References Slic3r::GUI::NotificationManager::PopNotification::m_state, and Slic3r::GUI::NotificationManager::PopNotification::Unknown.
render()
void Slic3r::GUI::NotificationManager::PopNotification::render (GLCanvas3D & canvas, float initial_y, bool move_from_overlay, float overlay_width, float right_margin) virtual inherited
{
  if (m_state == EState::Unknown)
    init();
  if (m_state == EState::Hidden) {
    m_top_y = initial_y - GAP_WIDTH;
    return;
  }
  if (m_state == EState::ClosePending || m_state == EState::Finished)
  {
    m_state = EState::Finished;
    return;
  }
  Size          cnv_size = canvas.get_canvas_size();
  ImGuiWrapper& imgui = *wxGetApp().imgui();
  ImVec2        mouse_pos = ImGui::GetMousePos();
    float         right_gap  = right_margin + (move_from_overlay ? overlay_width + m_line_height * 5 : 0);
  bool          fading_pop = false;
  if (m_line_height != ImGui::CalcTextSize("A").y)
    init();
  set_next_window_size(imgui);
  // top y of window
  m_top_y = initial_y + m_window_height;
  ImVec2 win_pos(1.0f * (float)cnv_size.get_width() - right_gap, 1.0f * (float)cnv_size.get_height() - m_top_y);
  imgui.set_next_window_pos(win_pos.x, win_pos.y, ImGuiCond_Always, 1.0f, 0.0f);
  imgui.set_next_window_size(m_window_width, m_window_height, ImGuiCond_Always);
  // find if hovered FIXME:  do it only in update state?
  if (m_state == EState::Hovered) {
    m_state = EState::Unknown;
    init();
  }
  if (mouse_pos.x < win_pos.x && mouse_pos.x > win_pos.x - m_window_width && mouse_pos.y > win_pos.y && mouse_pos.y < win_pos.y + m_window_height) {
    // Uncomment if imgui window focus is needed on hover. I cant find any case.
    //ImGui::SetNextWindowFocus();
    set_hovered();
  }
  // color change based on fading out
  if (m_state == EState::FadingOut) {
    push_style_color(ImGuiCol_WindowBg, ImGui::GetStyleColorVec4(ImGuiCol_WindowBg), true, m_current_fade_opacity);
    push_style_color(ImGuiCol_Text, ImGui::GetStyleColorVec4(ImGuiCol_Text), true, m_current_fade_opacity);
    push_style_color(ImGuiCol_ButtonHovered, ImGui::GetStyleColorVec4(ImGuiCol_ButtonHovered), true, m_current_fade_opacity);
    fading_pop = true;
  }
  bool bgrnd_color_pop = push_background_color();
  // name of window indentifies window - has to be unique string
  if (m_id == 0)
    m_id = m_id_provider.allocate_id();
  std::string name = "!!Ntfctn" + std::to_string(m_id);
    use_bbl_theme();
  if (imgui.begin(name, ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoScrollbar | ImGuiWindowFlags_NoScrollWithMouse)) {
    ImVec2 win_size = ImGui::GetWindowSize();
    bbl_render_left_sign(imgui, win_size.x, win_size.y, win_pos.x, win_pos.y);
    render_left_sign(imgui);
    render_text(imgui, win_size.x, win_size.y, win_pos.x, win_pos.y);
    render_close_button(imgui, win_size.x, win_size.y, win_pos.x, win_pos.y);
        m_minimize_b_visible = false;
        if (m_multiline && m_lines_count > 3)
      render_minimize_button(imgui, win_pos.x, win_pos.y);
  }
  imgui.end();
  restore_default_theme();
  if (bgrnd_color_pop)
    ImGui::PopStyleColor();
  if (fading_pop)
    ImGui::PopStyleColor(3);
}
References Slic3r::GUI::NotificationManager::NotificationIDProvider::allocate_id(), Slic3r::GUI::ImGuiWrapper::begin(), ImGui::CalcTextSize(), Slic3r::GUI::ImGuiWrapper::end(), GAP_WIDTH, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), ImGui::GetMousePos(), ImGui::GetStyleColorVec4(), ImGui::GetWindowSize(), ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiCol_WindowBg, ImGuiCond_Always, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoScrollbar, ImGuiWindowFlags_NoScrollWithMouse, ImGuiWindowFlags_NoTitleBar, Slic3r::GUI::NotificationManager::init(), Slic3r::GUI::NotificationManager::m_id_provider, ImGui::PopStyleColor(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::ImGuiWrapper::set_next_window_size(), ImVec2::x, and ImVec2::y.
render_bar()
void Slic3r::GUI::NotificationManager::ProgressBarNotification::render_bar (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) protected virtual
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification, and Slic3r::GUI::NotificationManager::SlicingProgressNotification.
{
  //ImVec4 orange_color     = ImVec4(.99f, .313f, .0f, 1.0f);
  //ImVec4 gray_color     = ImVec4(.34f, .34f, .34f, 1.0f);
    ImVec4 orange_color         = m_NormalColor;
    ImVec4 gray_color           = ImVec4(.7f, .7f, .7f, 1.0f);
  ImVec2 lineEnd        = ImVec2(win_pos_x - m_window_width_offset, win_pos_y + win_size_y / 2 + (m_multiline ? m_line_height / 2 : 0));
  ImVec2 lineStart      = ImVec2(win_pos_x - win_size_x + m_left_indentation, win_pos_y + win_size_y / 2 + (m_multiline ? m_line_height / 2 : 0));
  ImVec2 midPoint       = ImVec2(lineStart.x + (lineEnd.x - lineStart.x) * m_percentage, lineStart.y);
  ImGui::GetWindowDrawList()->AddLine(lineStart, lineEnd, IM_COL32((int)(gray_color.x * 255), (int)(gray_color.y * 255), (int)(gray_color.z * 255), (m_current_fade_opacity * 255.f)), m_line_height * 0.2f);
  ImGui::GetWindowDrawList()->AddLine(lineStart, midPoint, IM_COL32((int)(orange_color.x * 255), (int)(orange_color.y * 255), (int)(orange_color.z * 255), (m_current_fade_opacity * 255.f)), m_line_height * 0.2f);
  if (m_render_percentage) {
    std::string text;
    std::stringstream stream;
    stream << std::fixed << std::setprecision(2) << (int)(m_percentage * 100) << "%";
    text = stream.str();
    ImGui::SetCursorPosX(m_left_indentation);
    ImGui::SetCursorPosY(win_size_y / 2 + win_size_y / 6 - (m_multiline ? 0 : m_line_height / 4));
    imgui.text(text.c_str());
  }
}
References ImDrawList::AddLine(), ImGui::GetWindowDrawList(), IM_COL32, int, ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), Slic3r::GUI::ImGuiWrapper::text(), ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by Slic3r::GUI::NotificationManager::PrintHostUploadNotification::render_bar(), and Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_bar().
render_cancel_button()
virtual void Slic3r::GUI::NotificationManager::ProgressBarNotification::render_cancel_button (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) inline protected virtual
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification, Slic3r::GUI::NotificationManager::SlicingProgressNotification, and Slic3r::GUI::NotificationManager::ProgressIndicatorNotification.
    {}
render_close_button()
void Slic3r::GUI::NotificationManager::PopNotification::render_close_button (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification, Slic3r::GUI::NotificationManager::SlicingProgressNotification, Slic3r::GUI::NotificationManager::ProgressIndicatorNotification, and Slic3r::GUI::NotificationManager::ExportFinishedNotification.
{
  ImVec2 win_size(win_size_x, win_size_y);
  ImVec2 win_pos(win_pos_x, win_pos_y);
  ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(.0f, .0f, .0f, .0f));
  ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(.0f, .0f, .0f, .0f));
  push_style_color(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 1.f), m_state == EState::FadingOut, m_current_fade_opacity);
  push_style_color(ImGuiCol_TextSelectedBg, ImVec4(0, .75f, .75f, 1.f), m_state == EState::FadingOut, m_current_fade_opacity);
  ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(.0f, .0f, .0f, .0f));
  std::wstring button_text;
  button_text = m_is_dark ? ImGui::CloseNotifDarkButton : ImGui::CloseNotifButton;
    //button_text = ImGui::PreferencesButton;
  //if (ImGui::IsMouseHoveringRect(ImVec2(win_pos.x - win_size.x / 10.f, win_pos.y),
  //                             ImVec2(win_pos.x, win_pos.y + win_size.y - ( m_minimize_b_visible ? 2 * m_line_height : 0)),
  //                             true))
    if (ImGui::IsMouseHoveringRect(ImVec2(win_pos.x - win_size.x / 10.f, win_pos.y), ImVec2(win_pos.x, win_pos.y + 2 * m_line_height+10),true))
  {
    button_text = m_is_dark ? ImGui::CloseNotifHoverDarkButton : ImGui::CloseNotifHoverButton;
  }
  ImVec2 button_pic_size = ImGui::CalcTextSize(into_u8(button_text).c_str());
  ImVec2 button_size(button_pic_size.x * 1.25f, button_pic_size.y * 1.25f);
  ImGui::SetCursorPosX(win_size.x - m_line_height * 2.75f);
  //ImGui::SetCursorPosY(win_size.y / 2 - button_size.y);
    if (m_minimize_b_visible)
    ImGui::SetCursorPosY(0);
    else
        ImGui::SetCursorPosY(win_size.y / 2 - button_size.y);
  if (imgui.button(button_text.c_str(), button_size.x, button_size.y))
  {
    close();
  }
  //invisible large button
  ImGui::SetCursorPosX(win_size.x - m_line_height * 2.35f);
  ImGui::SetCursorPosY(0);
  if (imgui.button(" ", m_line_height * 2.125, win_size.y - ( m_minimize_b_visible ? 2 * m_line_height : 0)))
  {
    close();
  }
  ImGui::PopStyleColor(5);
}
References Slic3r::GUI::ImGuiWrapper::button(), ImGui::CalcTextSize(), ImGui::CloseNotifButton, ImGui::CloseNotifDarkButton, ImGui::CloseNotifHoverButton, ImGui::CloseNotifHoverDarkButton, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiCol_TextSelectedBg, Slic3r::GUI::into_u8(), ImGui::IsMouseHoveringRect(), Slic3r::GUI::NotificationManager::m_is_dark, ImGui::PopStyleColor(), ImGui::PushStyleColor(), ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), ImVec2::x, and ImVec2::y.
Referenced by Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_close_button(), Slic3r::GUI::NotificationManager::ProgressIndicatorNotification::render_close_button(), and Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_close_button().
render_hypertext()
void Slic3r::GUI::NotificationManager::PopNotification::render_hypertext (ImGuiWrapper & imgui, const float text_x, const float text_y, const std::string text, bool more = false) protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::SlicingProgressNotification.
{
  //invisible button
  ImVec2 part_size = ImGui::CalcTextSize(text.c_str());
  ImGui::SetCursorPosX(text_x -4);
  ImGui::SetCursorPosY(text_y -5);
  ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(.4f, .4f, .4f, 0.0f));
  ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(.5f, .5f, .5f, 0.0f));
  ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(.7f, .7f, .7f, 0.0f));
  if (imgui.button("      ", part_size.x + 6, part_size.y + 10))
  {
    if (more)
    {
      m_multiline = true;
      set_next_window_size(imgui);
    }
    else if (on_text_click()) {
      close();
    }
  }
  ImGui::PopStyleColor(3);
  //hover color
    ImVec4 HyperColor = m_HyperTextColor;//ImVec4(150.f / 255.f, 100.f / 255.f, 0.f / 255.f, 1)
    if (m_data.level == NotificationLevel::SeriousWarningNotificationLevel)
    HyperColor = ImVec4(0.f, 0.f, 0.f, 0.4f);
  if (m_data.level == NotificationLevel::ErrorNotificationLevel)
    HyperColor = ImVec4(135.f / 255.f, 43 / 255.f, 43 / 255.f, 1);
  if (ImGui::IsItemHovered(ImGuiHoveredFlags_RectOnly))
  {
    HyperColor.y += 0.1f;
    if (m_data.level == NotificationLevel::SeriousWarningNotificationLevel || m_data.level == NotificationLevel::SeriousWarningNotificationLevel)
      HyperColor.x += 0.2f;
  }
  //text
    push_style_color(ImGuiCol_Text, HyperColor, m_state == EState::FadingOut, m_current_fade_opacity);
  ImGui::SetCursorPosX(text_x);
  ImGui::SetCursorPosY(text_y);
  imgui.text(text.c_str());
  ImGui::PopStyleColor();
  //underline
  ImVec2 lineEnd = ImGui::GetItemRectMax();
  lineEnd.y -= 2;
  ImVec2 lineStart = lineEnd;
  lineStart.x = ImGui::GetItemRectMin().x;
    ImGui::GetWindowDrawList()->AddLine(lineStart, lineEnd,
                                        IM_COL32((int) (HyperColor.x * 255), (int) (HyperColor.y * 255), (int) (HyperColor.z * 255),
                                                 (int) (HyperColor.w * 255.f * (m_state == EState::FadingOut ? m_current_fade_opacity : 1.f))));
}
References ImDrawList::AddLine(), Slic3r::GUI::ImGuiWrapper::button(), ImGui::CalcTextSize(), Slic3r::GUI::NotificationManager::ErrorNotificationLevel, ImGui::GetItemRectMax(), ImGui::GetItemRectMin(), ImGui::GetWindowDrawList(), IM_COL32, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiHoveredFlags_RectOnly, ImGui::IsItemHovered(), ImGui::PopStyleColor(), ImGui::PushStyleColor(), Slic3r::GUI::NotificationManager::SeriousWarningNotificationLevel, ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), Slic3r::GUI::ImGuiWrapper::text(), ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_hypertext().
render_left_sign()
void Slic3r::GUI::NotificationManager::PopNotification::render_left_sign (ImGuiWrapper & imgui) protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification.
{
  //if (m_data.level == NotificationLevel::ErrorNotificationLevel || m_data.level == NotificationLevel::WarningNotificationLevel) {
  //  std::string text;
  //  text = (m_data.level == NotificationLevel::ErrorNotificationLevel ? ImGui::ErrorMarker : ImGui::WarningMarker);
  //  ImGui::SetCursorPosX(m_line_height / 3);
  //  ImGui::SetCursorPosY(m_window_height / 2 - m_line_height);
  //  imgui.text(text.c_str());
  //} else if (m_data.level == NotificationLevel::PrintInfoNotificationLevel || m_data.level == NotificationLevel::PrintInfoShortNotificationLevel) {
  //  std::wstring text;
  //  text = ImGui::InfoMarker;
  //  ImGui::SetCursorPosX(m_line_height / 3);
  //  ImGui::SetCursorPosY(m_window_height / 2 - m_line_height);
  //  imgui.text(text.c_str());
  //}
}
render_minimize_button()
void Slic3r::GUI::NotificationManager::ProgressBarNotification::render_minimize_button (ImGuiWrapper & imgui, const float win_pos_x, const float win_pos_y) inline override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::PopNotification.
                                                             {}
render_text()
void Slic3r::GUI::NotificationManager::ProgressBarNotification::render_text (ImGuiWrapper & imgui, const float win_size_x, const float win_size_y, const float win_pos_x, const float win_pos_y) override protected virtual
Reimplemented from Slic3r::GUI::NotificationManager::PopNotification.
Reimplemented in Slic3r::GUI::NotificationManager::SlicingProgressNotification.
{
  // hypertext is not rendered at all. If it is needed, it needs to be added here.
  // m_endlines should have endline for each line and then for hypertext thus m_endlines[1] should always be in m_text1
  if (m_multiline) {
    assert(m_text1.size() >= m_endlines[0]  || m_text1.size() >= m_endlines[1]);
    if(m_endlines[0] > m_text1.size() || m_endlines[1] > m_text1.size())
      return;
    // two lines text (what doesnt fit, wont show), one line bar
    ImGui::SetCursorPosX(m_left_indentation);
    ImGui::SetCursorPosY(m_line_height / 4);
    imgui.text(m_text1.substr(0, m_endlines[0]).c_str());
    ImGui::SetCursorPosX(m_left_indentation);
    ImGui::SetCursorPosY(m_line_height + m_line_height / 4);
    std::string line = m_text1.substr(m_endlines[0] + (m_text1[m_endlines[0]] == '\n' || m_text1[m_endlines[0]] == ' ' ? 1 : 0), m_endlines[1] - m_endlines[0] - (m_text1[m_endlines[0]] == '\n' || m_text1[m_endlines[0]] == ' ' ? 1 : 0));
    imgui.text(line.c_str());
    if (m_has_cancel_button)
      render_cancel_button(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
    render_bar(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
  } else {
    assert(m_text1.size() >= m_endlines[0]);
    if (m_endlines[0] > m_text1.size())
      return;
    //one line text, one line bar
    ImGui::SetCursorPosX(m_left_indentation);
    ImGui::SetCursorPosY(/*win_size_y / 2 - win_size_y / 6 -*/ m_line_height / 4);
    imgui.text(m_text1.substr(0, m_endlines[0]).c_str());
    if (m_has_cancel_button)
      render_cancel_button(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
    render_bar(imgui, win_size_x, win_size_y, win_pos_x, win_pos_y);
  }
}
References ImGui::SetCursorPosX(), ImGui::SetCursorPosY(), and Slic3r::GUI::ImGuiWrapper::text().
Referenced by Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_text().
reset_timer()
void Slic3r::GUI::NotificationManager::PopNotification::reset_timer () inline inherited
{ m_notification_start = GLCanvas3D::timestamp_now(); m_state = EState::Shown; }
References Slic3r::GUI::NotificationManager::PopNotification::m_notification_start, Slic3r::GUI::NotificationManager::PopNotification::m_state, Slic3r::GUI::NotificationManager::PopNotification::Shown, and Slic3r::GUI::GLCanvas3D::timestamp_now().
restore_default_theme()
void Slic3r::GUI::NotificationManager::PopNotification::restore_default_theme () protected inherited
{
    ImGuiStyle &OldStyle = ImGui::GetStyle();
    OldStyle.WindowPadding             = m_DefaultTheme.mWindowPadding;
    OldStyle.WindowRounding            = m_DefaultTheme.mWindowRound;
  ImGui::PopStyleColor(3);
  ImGui::PopStyleVar();
  //OldStyle.Colors[ImGuiCol_WindowBg] = m_DefaultTheme.mWindowBkg;
 //   OldStyle.Colors[ImGuiCol_Text]     = m_DefaultTheme.mTextColor;
 //   OldStyle.Colors[ImGuiCol_Border]   = m_DefaultTheme.mBorderColor;
}
References ImGui::GetStyle(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGuiStyle::WindowPadding, and ImGuiStyle::WindowRounding.
set_gray()
void Slic3r::GUI::NotificationManager::PopNotification::set_gray (bool g) inline inherited
{ m_is_gray = g; }
References Slic3r::GUI::NotificationManager::PopNotification::m_is_gray.
set_hovered()
void Slic3r::GUI::NotificationManager::PopNotification::set_hovered () inline inherited
{ if (m_state != EState::Finished && m_state != EState::ClosePending && m_state != EState::Hidden && m_state != EState::Unknown) m_state = EState::Hovered; }
References Slic3r::GUI::NotificationManager::PopNotification::ClosePending, Slic3r::GUI::NotificationManager::PopNotification::Finished, Slic3r::GUI::NotificationManager::PopNotification::Hidden, Slic3r::GUI::NotificationManager::PopNotification::Hovered, Slic3r::GUI::NotificationManager::PopNotification::m_state, and Slic3r::GUI::NotificationManager::PopNotification::Unknown.
set_Multiline()
void Slic3r::GUI::NotificationManager::PopNotification::set_Multiline (bool Multi) inline inherited
{ m_multiline = Multi; }
References Slic3r::GUI::NotificationManager::PopNotification::m_multiline.
set_next_window_size()
void Slic3r::GUI::NotificationManager::PopNotification::set_next_window_size (ImGuiWrapper & imgui) protected virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::HintNotification.
{
  m_window_height = m_multiline ?
    std::max(m_lines_count, (size_t)2) * m_line_height :
    2 * m_line_height;
  m_window_height += 1 * m_line_height; // top and bottom
}
set_percentage()
virtual void Slic3r::GUI::NotificationManager::ProgressBarNotification::set_percentage (float percent) inline virtual
Reimplemented in Slic3r::GUI::NotificationManager::PrintHostUploadNotification, and Slic3r::GUI::NotificationManager::ProgressIndicatorNotification.
{ m_percentage = percent; }
References m_percentage.
Referenced by Slic3r::GUI::NotificationManager::ProgressIndicatorNotification::set_percentage().
update()
void Slic3r::GUI::NotificationManager::PopNotification::update (const NotificationData & n) inherited
{
  m_text1          = n.text1;
  m_hypertext      = n.hypertext;
    m_text2          = n.text2;
    const_cast<NotificationData&>(m_data).callback   = n.callback;
  init();
}
References Slic3r::GUI::NotificationManager::init(), and n.
update_state()
bool Slic3r::GUI::NotificationManager::PopNotification::update_state (bool paused, const int64_t delta) virtual inherited
Reimplemented in Slic3r::GUI::NotificationManager::SlicingProgressNotification, and Slic3r::GUI::NotificationManager::ProgressIndicatorNotification.
{
  m_next_render = std::numeric_limits<int64_t>::max();
  if (m_state == EState::Unknown) {
    init();
    return true;
  }
  if (m_state == EState::Hidden) {
    return false;
  }
  int64_t now = GLCanvas3D::timestamp_now();
  // reset fade opacity for non-closing notifications or hover during fading
  if (m_state != EState::FadingOut && m_state != EState::ClosePending && m_state != EState::Finished) {
    m_current_fade_opacity = 1.0f;
  }
  // reset timers - hovered state is set in render
  if (m_state == EState::Hovered) {
    m_state = EState::Unknown;
    init();
  // Timers when not fading
  } else if (m_state != EState::NotFading && m_state != EState::FadingOut && m_state != EState::ClosePending && m_state != EState::Finished && get_duration() != 0 && !paused) {
    int64_t up_time = now - m_notification_start;
    if (up_time >= get_duration() * 1000) {
      m_state         = EState::FadingOut;
      m_fading_start      = now;
    } else {
      m_next_render = get_duration() * 1000 - up_time;
    }
  }
  // Timers when fading
  if (m_state == EState::FadingOut && !paused) {
    int64_t curr_time   = now - m_fading_start;
    int64_t next_render   = FADING_OUT_TIMEOUT - delta;
    m_current_fade_opacity  = std::clamp(1.0f - 0.001f * static_cast<float>(curr_time) / FADING_OUT_DURATION, 0.0f, 1.0f);
    if (m_current_fade_opacity <= 0.0f) {
      m_state = EState::Finished;
      return true;
    } else if (next_render <= 20) {
      m_next_render = FADING_OUT_TIMEOUT;
      return true;
    } else {
      m_next_render = next_render;
      return false;
    }
  }
  if (m_state == EState::Finished) {
    return true;
  }
  if (m_state == EState::ClosePending) {
    m_state = EState::Finished;
    return true;
  }
  return false;
}
References FADING_OUT_DURATION, FADING_OUT_TIMEOUT, Slic3r::GUI::NotificationManager::init(), and Slic3r::GUI::GLCanvas3D::timestamp_now().
Referenced by Slic3r::GUI::NotificationManager::SlicingProgressNotification::update_state(), and Slic3r::GUI::NotificationManager::ProgressIndicatorNotification::update_state().
use_bbl_theme()
void Slic3r::GUI::NotificationManager::PopNotification::use_bbl_theme () protected inherited
{
    ImGuiStyle &OldStyle         = ImGui::GetStyle();
    m_DefaultTheme.mWindowPadding = OldStyle.WindowPadding;
    m_DefaultTheme.mWindowBkg     = OldStyle.Colors[ImGuiCol_WindowBg];
    m_DefaultTheme.mBorderColor   = OldStyle.Colors[ImGuiCol_Border];
    m_DefaultTheme.mTextColor     = OldStyle.Colors[ImGuiCol_Text];
    m_DefaultTheme.mWindowRound   = OldStyle.WindowRounding;
    OldStyle.WindowPadding             = ImVec2(0, 0);
    OldStyle.WindowRounding            = m_WindowRadius;
  if (m_data.level == NotificationLevel::ErrorNotificationLevel)
        m_CurrentColor = m_ErrorColor;
    else if (m_data.level == NotificationLevel::WarningNotificationLevel)
        m_CurrentColor = m_WarnColor;
    else {
        if (m_data.use_warn_color)
            m_CurrentColor = m_WarnColor;
        else
            m_CurrentColor = m_NormalColor;
    }
  //OldStyle.Colors[ImGuiCol_Border] = m_CurrentColor;
 //   OldStyle.Colors[ImGuiCol_WindowBg] = m_WindowBkgColor;
 //   OldStyle.Colors[ImGuiCol_Text]     = m_TextColor;
  m_WindowBkgColor = m_is_dark ? ImVec4(45 / 255.f, 45 / 255.f, 49 / 255.f, 1.f) : ImVec4(1, 1, 1, 1);
  m_TextColor = m_is_dark ? ImVec4(224 / 255.f, 224 / 255.f, 224 / 255.f, 1.f) : ImVec4(.2f, .2f, .2f, 1.0f);
  m_HyperTextColor = m_is_dark ? ImVec4(0, 0.588, 0.533, 1) : ImVec4(0, 0.588, 0.533, 1);
  m_is_dark ? push_style_color(ImGuiCol_Border, {62 / 255.f, 62 / 255.f, 69 / 255.f, 1.f}, true, m_current_fade_opacity) : push_style_color(ImGuiCol_Border, m_CurrentColor, true, m_current_fade_opacity);
    push_style_color(ImGuiCol_WindowBg, m_WindowBkgColor, true, m_current_fade_opacity);
    push_style_color(ImGuiCol_Text, m_TextColor, true, m_current_fade_opacity);
  ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, m_WindowRadius / 4);
}
References ImGuiStyle::Colors, Slic3r::GUI::NotificationManager::ErrorNotificationLevel, ImGui::GetStyle(), ImGuiCol_Border, ImGuiCol_Text, ImGuiCol_WindowBg, ImGuiStyleVar_WindowBorderSize, Slic3r::GUI::NotificationManager::m_is_dark, ImGui::PushStyleVar(), Slic3r::GUI::NotificationManager::WarningNotificationLevel, ImGuiStyle::WindowPadding, and ImGuiStyle::WindowRounding.
Member Data Documentation
error_end
std::string Slic3r::GUI::NotificationManager::PopNotification::error_end = "</Error>" protected inherited
error_start
std::string Slic3r::GUI::NotificationManager::PopNotification::error_start = "<Error>" protected inherited
m_bottom_y
float Slic3r::GUI::NotificationManager::PopNotification::m_bottom_y { 0.0f } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::get_bottom().
m_current_fade_opacity
float Slic3r::GUI::NotificationManager::PopNotification::m_current_fade_opacity { 1.0f } protected inherited
m_CurrentColor
ImVec4 Slic3r::GUI::NotificationManager::PopNotification::m_CurrentColor protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
m_data
const NotificationData Slic3r::GUI::NotificationManager::PopNotification::m_data protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::get_data(), Slic3r::GUI::NotificationManager::PopNotification::get_duration(), and Slic3r::GUI::NotificationManager::PopNotification::get_type().
m_DefaultTheme
ImGUITheme Slic3r::GUI::NotificationManager::PopNotification::m_DefaultTheme protected inherited
m_endlines
std::vector<size_t> Slic3r::GUI::NotificationManager::PopNotification::m_endlines protected inherited
m_endlines2
std::vector<size_t> Slic3r::GUI::NotificationManager::PopNotification::m_endlines2 protected inherited
m_ErrorColor
ImVec4 Slic3r::GUI::NotificationManager::PopNotification::m_ErrorColor protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
m_evt_handler
wxEvtHandler* Slic3r::GUI::NotificationManager::PopNotification::m_evt_handler protected inherited
m_fading_start
int64_t Slic3r::GUI::NotificationManager::PopNotification::m_fading_start { 0LL } protected inherited
m_has_cancel_button
bool Slic3r::GUI::NotificationManager::ProgressBarNotification::m_has_cancel_button {false} protected
Referenced by Slic3r::GUI::NotificationManager::PrintHostUploadNotification::PrintHostUploadNotification(), Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressNotification(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::cancel(), and Slic3r::GUI::NotificationManager::PrintHostUploadNotification::error().
m_hypertext
std::string Slic3r::GUI::NotificationManager::PopNotification::m_hypertext protected inherited
m_HyperTextColor
ImVec4 Slic3r::GUI::NotificationManager::PopNotification::m_HyperTextColor protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
m_id
int Slic3r::GUI::NotificationManager::PopNotification::m_id { 0 } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::~PopNotification().
m_id_provider
NotificationIDProvider& Slic3r::GUI::NotificationManager::PopNotification::m_id_provider protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::~PopNotification().
m_is_dark
bool Slic3r::GUI::NotificationManager::PopNotification::m_is_dark = false protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
m_is_gray
bool Slic3r::GUI::NotificationManager::PopNotification::m_is_gray { false } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::is_gray(), and Slic3r::GUI::NotificationManager::PopNotification::set_gray().
m_left_indentation
float Slic3r::GUI::NotificationManager::PopNotification::m_left_indentation protected inherited
Referenced by Slic3r::GUI::NotificationManager::HintNotification::count_spaces().
m_line_height
float Slic3r::GUI::NotificationManager::PopNotification::m_line_height protected inherited
Referenced by Slic3r::GUI::NotificationManager::HintNotification::count_spaces().
m_lines_count
size_t Slic3r::GUI::NotificationManager::PopNotification::m_lines_count { 1 } protected inherited
m_minimize_b_visible
bool Slic3r::GUI::NotificationManager::PopNotification::m_minimize_b_visible { false } protected inherited
Referenced by Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_minimize_button().
m_multiline
bool Slic3r::GUI::NotificationManager::PopNotification::m_multiline { false } protected inherited
Referenced by Slic3r::GUI::NotificationManager::ExportFinishedNotification::ExportFinishedNotification(), and Slic3r::GUI::NotificationManager::PopNotification::set_Multiline().
m_next_render
int64_t Slic3r::GUI::NotificationManager::PopNotification::m_next_render { std::numeric_limits<int64_t>::max() } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::next_render().
m_NormalColor
ImVec4 Slic3r::GUI::NotificationManager::PopNotification::m_NormalColor protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
m_notification_start
int64_t Slic3r::GUI::NotificationManager::PopNotification::m_notification_start protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::reset_timer().
m_percentage
float Slic3r::GUI::NotificationManager::ProgressBarNotification::m_percentage {0.0f} protected
Referenced by set_percentage().
m_render_percentage
bool Slic3r::GUI::NotificationManager::ProgressBarNotification::m_render_percentage {false} protected
Referenced by Slic3r::GUI::NotificationManager::ProgressIndicatorNotification::ProgressIndicatorNotification(), and Slic3r::GUI::NotificationManager::SlicingProgressNotification::SlicingProgressNotification().
m_state
EState Slic3r::GUI::NotificationManager::PopNotification::m_state { EState::Unknown } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::close(), Slic3r::GUI::NotificationManager::PlaterWarningNotification::close(), Slic3r::GUI::NotificationManager::PopNotification::get_state(), Slic3r::GUI::NotificationManager::PopNotification::hide(), Slic3r::GUI::NotificationManager::PopNotification::is_finished(), Slic3r::GUI::NotificationManager::PopNotification::is_hovered(), Slic3r::GUI::NotificationManager::PlaterWarningNotification::real_close(), Slic3r::GUI::NotificationManager::PopNotification::reinit(), Slic3r::GUI::NotificationManager::PopNotification::reset_timer(), Slic3r::GUI::NotificationManager::PopNotification::set_hovered(), and Slic3r::GUI::NotificationManager::PlaterWarningNotification::show().
m_text1
std::string Slic3r::GUI::NotificationManager::PopNotification::m_text1 protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::get_text1().
m_text2
std::string Slic3r::GUI::NotificationManager::PopNotification::m_text2 protected inherited
m_TextColor
ImVec4 Slic3r::GUI::NotificationManager::PopNotification::m_TextColor protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
m_top_y
float Slic3r::GUI::NotificationManager::PopNotification::m_top_y { 0.0f } protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::get_current_top(), and Slic3r::GUI::NotificationManager::PopNotification::get_top().
m_WarnColor
ImVec4 Slic3r::GUI::NotificationManager::PopNotification::m_WarnColor protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
m_window_height
float Slic3r::GUI::NotificationManager::PopNotification::m_window_height { 56.0f } protected inherited
m_window_width
float Slic3r::GUI::NotificationManager::PopNotification::m_window_width { 450.0f } protected inherited
Referenced by Slic3r::GUI::NotificationManager::HintNotification::count_spaces().
m_window_width_offset
float Slic3r::GUI::NotificationManager::PopNotification::m_window_width_offset protected inherited
Referenced by Slic3r::GUI::NotificationManager::HintNotification::count_spaces().
m_WindowBkgColor
ImVec4 Slic3r::GUI::NotificationManager::PopNotification::m_WindowBkgColor protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
m_WindowRadius
float Slic3r::GUI::NotificationManager::PopNotification::m_WindowRadius protected inherited
Referenced by Slic3r::GUI::NotificationManager::PopNotification::PopNotification().
pos_end
size_t Slic3r::GUI::NotificationManager::PopNotification::pos_end = string::npos protected inherited
pos_start
size_t Slic3r::GUI::NotificationManager::PopNotification::pos_start = string::npos protected inherited
The documentation for this class was generated from the following files:
src/slic3r/GUI/NotificationManager.hpp
src/slic3r/GUI/NotificationManager.cpp