OrcaSlicer: src/qhull/src/libqhullcpp/QhullFacetList.cpp File Reference
QhullFacetList.cpp File Reference
#include "libqhullcpp/QhullFacetList.h"
#include "libqhullcpp/QhullFacet.h"
#include "libqhullcpp/QhullPoint.h"
#include "libqhullcpp/QhullRidge.h"
#include "libqhullcpp/QhullVertex.h"
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global functions
ostream & operator<< (ostream &os, const QhullFacetList::PrintFacetList &pr)
ostream & operator<< (ostream &os, const QhullFacetList::PrintFacets &pr)
Print facet list to stream. From qh_printafacet [io_r.c].
ostream & operator<< (ostream &os, const QhullFacetList::PrintVertices &pr)
Print vertices of good faces in facet list to stream. From qh_printvertexlist [io_r.c] Same as vertices_toStdVector.
std::ostream & operator<< (ostream &os, const QhullFacetList &fs)
Function Documentation
operator<<() [1/4]
std::ostream & operator<< (ostream & os, const QhullFacetList & fs)
{
    os << fs.printFacets();
    return os;
}//QhullFacetList
operator<<() [2/4]
ostream & operator<< (ostream & os, const QhullFacetList::PrintFacetList & pr)
{
    os << pr.print_message;
    QhullFacetList fs= *pr.facet_list;
    os << "Vertices for " << fs.count() << " facets" << endl;
    os << fs.printVertices();
    os << fs.printFacets();
    return os;
}//operator<<
operator<<() [3/4]
ostream & operator<< (ostream & os, const QhullFacetList::PrintFacets & pr)
Print facet list to stream. From qh_printafacet [io_r.c].
{
    for(QhullFacetList::const_iterator i= pr.facet_list->begin(); i != pr.facet_list->end(); ++i){
        QhullFacet f= *i;
        if(pr.facet_list->isSelectAll() || f.isGood()){
            os << f.print("");
        }
    }
    return os;
}//printFacets
References orgQhull::QhullFacet::isGood(), and orgQhull::QhullFacet::print().
operator<<() [4/4]
ostream & operator<< (ostream & os, const QhullFacetList::PrintVertices & pr)
Print vertices of good faces in facet list to stream. From qh_printvertexlist [io_r.c] Same as vertices_toStdVector.
{
    QhullVertexSet vs(pr.facet_list->qh(), pr.facet_list->first().getFacetT(), NULL, pr.facet_list->isSelectAll());
    for(QhullVertexSet::iterator i=vs.begin(); i!=vs.end(); ++i){
        QhullVertex v= *i;
        os << v.print("");
    }
    return os;
}//printVertices
References orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::end(), NULL, and orgQhull::QhullVertex::print().