OrcaSlicer: orgQhull::Coordinates::iterator Class Reference
orgQhull::Coordinates::iterator Class Reference
#include <src/qhull/src/libqhullcpp/Coordinates.h>
Public Types
typedef std::random_access_iterator_tag iterator_category
typedef coordT value_type
typedef value_type * pointer
typedef value_type & reference
typedef ptrdiff_t difference_type
Public Member Functions
iterator ()
iterator (const iterator &other)
iterator (const std::vector< coordT >::iterator &vi)
iterator & operator= (const iterator &other)
std::vector< coordT >::iterator & base ()
coordT & operator* () const
coordT & operator[] (countT idx) const
bool operator== (const iterator &other) const
bool operator!= (const iterator &other) const
bool operator< (const iterator &other) const
bool operator<= (const iterator &other) const
bool operator> (const iterator &other) const
bool operator>= (const iterator &other) const
bool operator== (const Coordinates::const_iterator &other) const
bool operator!= (const Coordinates::const_iterator &other) const
bool operator< (const Coordinates::const_iterator &other) const
bool operator<= (const Coordinates::const_iterator &other) const
bool operator> (const Coordinates::const_iterator &other) const
bool operator>= (const Coordinates::const_iterator &other) const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
iterator & operator+= (countT idx)
iterator & operator-= (countT idx)
iterator operator+ (countT idx) const
iterator operator- (countT idx) const
difference_type operator- (iterator other) const
Private Attributes
std::vector< coordT >::iterator i
Friends
class const_iterator
Detailed Description
Member Typedef Documentation
difference_type
typedef ptrdiff_t orgQhull::Coordinates::iterator::difference_type
iterator_category
typedef std::random_access_iterator_tag orgQhull::Coordinates::iterator::iterator_category
pointer
typedef value_type* orgQhull::Coordinates::iterator::pointer
reference
typedef value_type& orgQhull::Coordinates::iterator::reference
value_type
typedef coordT orgQhull::Coordinates::iterator::value_type
Constructor & Destructor Documentation
iterator() [1/3]
orgQhull::Coordinates::iterator::iterator () inline
{}
Referenced by operator+(), operator++(), operator-(), and operator--().
iterator() [2/3]
orgQhull::Coordinates::iterator::iterator (const iterator & other) inline
{ i= other.i; }
References i.
iterator() [3/3]
orgQhull::Coordinates::iterator::iterator (const std::vector< coordT >::iterator & vi) inline explicit
{ i= vi; }
References i.
Member Function Documentation
base()
std::vector< coordT >::iterator & orgQhull::Coordinates::iterator::base () inline
{ return i; }
References i.
Referenced by orgQhull::Coordinates::erase(), orgQhull::Coordinates::erase(), and orgQhull::Coordinates::insert().
operator!=() [1/2]
bool orgQhull::Coordinates::iterator::operator!= (const Coordinates::const_iterator & other) const inline
{ return *this!=reinterpret_cast<const iterator &>(other); }
operator!=() [2/2]
bool orgQhull::Coordinates::iterator::operator!= (const iterator & other) const inline
{ return i!=other.i; }
References i.
operator*()
coordT & orgQhull::Coordinates::iterator::operator* () const inline
{ return *i; }
References i.
operator+()
iterator orgQhull::Coordinates::iterator::operator+ (countT idx) const inline
{ return iterator(i+idx); }
References iterator(), and i.
operator++() [1/2]
iterator & orgQhull::Coordinates::iterator::operator++ () inline
{ ++i; return *this; }
References i.
operator++() [2/2]
iterator orgQhull::Coordinates::iterator::operator++ (int) inline
{ return iterator(i++); }
References iterator(), and i.
operator+=()
iterator & orgQhull::Coordinates::iterator::operator+= (countT idx) inline
{ i += idx; return *this; }
References i.
operator-() [1/2]
iterator orgQhull::Coordinates::iterator::operator- (countT idx) const inline
{ return iterator(i-idx); }
References iterator(), and i.
operator-() [2/2]
difference_type orgQhull::Coordinates::iterator::operator- (iterator other) const inline
{ return i-other.i; }
References i.
operator--() [1/2]
iterator & orgQhull::Coordinates::iterator::operator-- () inline
{ --i; return *this; }
References i.
operator--() [2/2]
iterator orgQhull::Coordinates::iterator::operator-- (int) inline
{ return iterator(i--); }
References iterator(), and i.
operator-=()
iterator & orgQhull::Coordinates::iterator::operator-= (countT idx) inline
{ i -= idx; return *this; }
References i.
operator<() [1/2]
bool orgQhull::Coordinates::iterator::operator< (const Coordinates::const_iterator & other) const inline
{ return *this<reinterpret_cast<const iterator &>(other); }
operator<() [2/2]
bool orgQhull::Coordinates::iterator::operator< (const iterator & other) const inline
{ return i<other.i; }
References i.
operator<=() [1/2]
bool orgQhull::Coordinates::iterator::operator<= (const Coordinates::const_iterator & other) const inline
{ return *this<=reinterpret_cast<const iterator &>(other); }
operator<=() [2/2]
bool orgQhull::Coordinates::iterator::operator<= (const iterator & other) const inline
{ return i<=other.i; }
References i.
operator=()
iterator & orgQhull::Coordinates::iterator::operator= (const iterator & other) inline
{ i= other.i; return *this; }
References i.
operator==() [1/2]
bool orgQhull::Coordinates::iterator::operator== (const Coordinates::const_iterator & other) const inline
{ return *this==reinterpret_cast<const iterator &>(other); }
operator==() [2/2]
bool orgQhull::Coordinates::iterator::operator== (const iterator & other) const inline
{ return i==other.i; }
References i.
operator>() [1/2]
bool orgQhull::Coordinates::iterator::operator> (const Coordinates::const_iterator & other) const inline
{ return *this>reinterpret_cast<const iterator &>(other); }
operator>() [2/2]
bool orgQhull::Coordinates::iterator::operator> (const iterator & other) const inline
{ return i>other.i; }
References i.
operator>=() [1/2]
bool orgQhull::Coordinates::iterator::operator>= (const Coordinates::const_iterator & other) const inline
{ return *this>=reinterpret_cast<const iterator &>(other); }
operator>=() [2/2]
bool orgQhull::Coordinates::iterator::operator>= (const iterator & other) const inline
{ return i>=other.i; }
References i.
operator[]()
coordT & orgQhull::Coordinates::iterator::operator[] (countT idx) const inline
{ return i[idx]; }
References i.
Friends And Related Symbol Documentation
const_iterator
friend class const_iterator friend
Member Data Documentation
i
std::vector<coordT>::iterator orgQhull::Coordinates::iterator::i private
Referenced by iterator(), iterator(), base(), operator!=(), operator*(), operator+(), operator++(), operator++(), operator+=(), operator-(), operator-(), operator--(), operator--(), operator-=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), and operator[]().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/Coordinates.h