OrcaSlicer: src/slic3r/GUI/3DScene.cpp File Reference
3DScene.cpp File Reference
#include <GL/glew.h>
#include "3DScene.hpp"
#include "GLShader.hpp"
#include "GUI_App.hpp"
#include "GUI_Colors.hpp"
#include "Plater.hpp"
#include "BitmapCache.hpp"
#include "libslic3r/BuildVolume.hpp"
#include "libslic3r/ExtrusionEntity.hpp"
#include "libslic3r/ExtrusionEntityCollection.hpp"
#include "libslic3r/Geometry.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/SLAPrint.hpp"
#include "libslic3r/Slicing.hpp"
#include "libslic3r/Format/STL.hpp"
#include "libslic3r/Utils.hpp"
#include "libslic3r/AppConfig.hpp"
#include "libslic3r/PresetBundle.hpp"
#include "libslic3r/ClipperUtils.hpp"
#include "libslic3r/Tesselate.hpp"
#include "libslic3r/PrintConfig.hpp"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <assert.h>
#include <boost/log/trivial.hpp>
#include <boost/filesystem/operations.hpp>
#include <boost/algorithm/string/predicate.hpp>
#include <Eigen/Dense>
Namespaces
namespace Slic3r
Macros
#define LEFT 0
#define RIGHT 1
#define TOP 2
#define BOTTOM 3
#define LEFT 0
#define RIGHT 1
#define TOP 2
#define BOTTOM 3
Functions
void glAssertRecentCallImpl (const char *file_name, unsigned int line, const char *function_name)
std::vector< std::array< float, 4 > > get_extruders_colors ()
std::array< float, 4 > adjust_color_for_rendering (const std::array< float, 4 > &colors)
std::array< float, 4 > Slic3r::color_from_model_volume (const ModelVolume &model_volume)
GLVolumeWithIdAndZList Slic3r::volumes_to_render (const GLVolumePtrs &volumes, GLVolumeCollection::ERenderType type, const Transform3d &view_matrix, std::function< bool(const GLVolume &)> filter_func)
static void Slic3r::thick_lines_to_indexed_vertex_array (const Lines &lines, const std::vector< double > &widths, const std::vector< double > &heights, bool closed, double top_z, GLIndexedVertexArray &volume)
static void Slic3r::thick_lines_to_indexed_vertex_array (const Lines3 &lines, const std::vector< double > &widths, const std::vector< double > &heights, bool closed, GLIndexedVertexArray &volume)
static void Slic3r::point_to_indexed_vertex_array (const Vec3crd &point, double width, double height, GLIndexedVertexArray &volume)
static void Slic3r::thick_point_to_verts (const Vec3crd &point, double width, double height, GLVolume &volume)
Variables
float FullyTransparentMaterialThreshold = 0.1f
float FullTransparentModdifiedToFixAlpha = 0.3f
Macro Definition Documentation
BOTTOM [1/2]
#define BOTTOM 3
BOTTOM [2/2]
#define BOTTOM 3
LEFT [1/2]
#define LEFT 0
LEFT [2/2]
#define LEFT 0
RIGHT [1/2]
#define RIGHT 1
RIGHT [2/2]
#define RIGHT 1
TOP [1/2]
#define TOP 2
TOP [2/2]
#define TOP 2
Function Documentation
adjust_color_for_rendering()
std::array< float, 4 > adjust_color_for_rendering (const std::array< float, 4 > & colors)
{
   if (colors[3] < FullyTransparentMaterialThreshold) { // completely transparent
                std::array<float, 4> new_color;
                new_color[0] = 1;
                new_color[1] = 1;
                new_color[2] = 1;
                new_color[3] = FullTransparentModdifiedToFixAlpha;
                return new_color;
    }
    return colors;
}
References FullTransparentModdifiedToFixAlpha, and FullyTransparentMaterialThreshold.
Referenced by Slic3r::GUI::GCodeViewer::refresh_render_paths(), Slic3r::GLVolume::render(), Slic3r::GLWipeTowerVolume::render(), Slic3r::GUI::TriangleSelectorPatch::render(), Slic3r::GUI::GLCanvas3D::render_thumbnail_internal(), Slic3r::GLVolume::set_render_color(), and Slic3r::GLVolume::simple_render().
get_extruders_colors()
std::vector< std::array< float, 4 > > get_extruders_colors ()
{
    unsigned char                     rgba_color[4] = {};
    std::vector<std::string>          colors        = Slic3r::GUI::wxGetApp().plater()->get_extruder_colors_from_plater_config();
    std::vector<std::array<float, 4>> colors_out(colors.size());
    for (const std::string &color : colors) {
        Slic3r::GUI::BitmapCache::parse_color4(color, rgba_color);
        size_t color_idx      = &color - &colors.front();
        colors_out[color_idx] = {
            float(rgba_color[0]) / 255.f,
            float(rgba_color[1]) / 255.f,
            float(rgba_color[2]) / 255.f,
            float(rgba_color[3]) / 255.f,
        };
    }
    return colors_out;
}
References Slic3r::GUI::BitmapCache::parse_color4().
Referenced by Slic3r::GUI::GLGizmoMmuSegmentation::init_extruders_data(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), Slic3r::GLVolume::render(), Slic3r::GUI::GLCanvas3D::render_thumbnail(), Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data(), and Slic3r::GUI::GLGizmoMmuSegmentation::update_from_model_object().
glAssertRecentCallImpl()
void glAssertRecentCallImpl (const char * file_name, unsigned int line, const char * function_name)
{
#if defined(NDEBUG)
    // In release mode, only show OpenGL errors if sufficiently high loglevel.
    if (Slic3r::get_logging_level() < 5)
        return;
#endif // NDEBUG
    GLenum err = glGetError();
    if (err == GL_NO_ERROR)
        return;
    const char* sErr = 0;
    switch (err) {
    case GL_INVALID_ENUM:       sErr = "Invalid Enum";      break;
    case GL_INVALID_VALUE:      sErr = "Invalid Value";     break;
    // be aware that GL_INVALID_OPERATION is generated if glGetError is executed between the execution of glBegin and the corresponding execution of glEnd
    case GL_INVALID_OPERATION:  sErr = "Invalid Operation"; break;
    case GL_STACK_OVERFLOW:     sErr = "Stack Overflow";    break;
    case GL_STACK_UNDERFLOW:    sErr = "Stack Underflow";   break;
    case GL_OUT_OF_MEMORY:      sErr = "Out Of Memory";     break;
    default:                    sErr = "Unknown";           break;
    }
    BOOST_LOG_TRIVIAL(error) << "OpenGL error in " << file_name << ":" << line << ", function " << function_name << "() : " << (int)err << " - " << sErr;
    assert(false);
}
References error, Slic3r::get_logging_level(), and int.
Referenced by glAssertRecentCall().
Variable Documentation
FullTransparentModdifiedToFixAlpha
float FullTransparentModdifiedToFixAlpha = 0.3f
Referenced by adjust_color_for_rendering(), and Slic3r::GLVolume::set_render_color().
FullyTransparentMaterialThreshold
float FullyTransparentMaterialThreshold = 0.1f
Referenced by adjust_color_for_rendering(), and Slic3r::GLVolume::set_render_color().