OrcaSlicer: src/qhull/src/libqhull/poly.c File Reference
poly.c File Reference
#include "qhull_a.h"
Functions
void qh_appendfacet (facetT *facet)
void qh_appendvertex (vertexT *vertex)
void qh_attachnewfacets (void)
boolT qh_checkflipped (facetT *facet, realT *distp, boolT allerror)
void qh_delfacet (facetT *facet)
void qh_deletevisible (void)
setT * qh_facetintersect (facetT *facetA, facetT *facetB, int *skipA, int *skipB, int prepend)
int qh_gethash (int hashsize, setT *set, int size, int firstindex, void *skipelem)
facetT * qh_makenewfacet (setT *vertices, boolT toporient, facetT *horizon)
void qh_makenewplanes (void)
facetT * qh_makenew_nonsimplicial (facetT *visible, vertexT *apex, int *numnew)
facetT * qh_makenew_simplicial (facetT *visible, vertexT *apex, int *numnew)
void qh_matchneighbor (facetT *newfacet, int newskip, int hashsize, int *hashcount)
void qh_matchnewfacets (void)
boolT qh_matchvertices (int firstindex, setT *verticesA, int skipA, setT *verticesB, int *skipB, boolT *same)
facetT * qh_newfacet (void)
ridgeT * qh_newridge (void)
int qh_pointid (pointT *point)
void qh_removefacet (facetT *facet)
void qh_removevertex (vertexT *vertex)
void qh_updatevertices (void)
Function Documentation
qh_appendfacet()
void qh_appendfacet (facetT * facet)
{
  facetT *tail= qh facet_tail;
  if (tail == qh newfacet_list)
    qh newfacet_list= facet;
  if (tail == qh facet_next)
    qh facet_next= facet;
  facet->previous= tail->previous;
  facet->next= tail;
  if (tail->previous)
    tail->previous->next= facet;
  else
    qh facet_list= facet;
  tail->previous= facet;
  qh num_facets++;
  trace4((qh ferr, 4044, "qh_appendfacet: append f%d to facet_list\n", facet->id));
} /* appendfacet */
References facetT::id, facetT::next, facetT::previous, qh, tail(), and trace4.
Referenced by qh_checkconnect(), qh_checkconnect(), qh_createsimplex(), qh_createsimplex(), qh_findgooddist(), qh_findgooddist(), qh_findhorizon(), qh_findhorizon(), qh_makenewfacet(), qh_mergecycle_facets(), qh_mergecycle_facets(), qh_mergefacet(), qh_mergefacet(), qh_partitionpoint(), and qh_partitionpoint().
qh_appendvertex()
void qh_appendvertex (vertexT * vertex)
{
  vertexT *tail= qh vertex_tail;
  if (tail == qh newvertex_list)
    qh newvertex_list= vertex;
  vertex->newlist= True;
  vertex->previous= tail->previous;
  vertex->next= tail;
  if (tail->previous)
    tail->previous->next= vertex;
  else
    qh vertex_list= vertex;
  tail->previous= vertex;
  qh num_vertices++;
  trace4((qh ferr, 4045, "qh_appendvertex: append v%d to vertex_list\n", vertex->id));
} /* appendvertex */
References qh, tail(), trace4, and True.
Referenced by qh_createsimplex(), qh_createsimplex(), qh_makenewfacet(), qh_makenewfacets(), qh_makenewfacets(), qh_mergesimplex(), qh_mergesimplex(), qh_newvertices(), and qh_newvertices().
qh_attachnewfacets()
void qh_attachnewfacets (void)
{
  facetT *newfacet= NULL, *neighbor, **neighborp, *horizon, *visible;
  ridgeT *ridge, **ridgep;
  qh NEWfacets= True;
  trace3((qh ferr, 3012, "qh_attachnewfacets: delete interior ridges\n"));
  qh visit_id++;
  FORALLvisible_facets {
    visible->visitid= qh visit_id;
    if (visible->ridges) {
      FOREACHridge_(visible->ridges) {
        neighbor= otherfacet_(ridge, visible);
        if (neighbor->visitid == qh visit_id
            || (!neighbor->visible && neighbor->simplicial)) {
          if (!neighbor->visible)  /* delete ridge for simplicial horizon */
            qh_setdel(neighbor->ridges, ridge);
          qh_setfree(&(ridge->vertices)); /* delete on 2nd visit */
          qh_memfree(ridge, (int)sizeof(ridgeT));
        }
      }
      SETfirst_(visible->ridges)= NULL;
    }
    SETfirst_(visible->neighbors)= NULL;
  }
  trace1((qh ferr, 1017, "qh_attachnewfacets: attach horizon facets to new facets\n"));
  FORALLnew_facets {
    horizon= SETfirstt_(newfacet->neighbors, facetT);
    if (horizon->simplicial) {
      visible= NULL;
      FOREACHneighbor_(horizon) {   /* may have more than one horizon ridge */
        if (neighbor->visible) {
          if (visible) {
            if (qh_setequal_skip(newfacet->vertices, 0, horizon->vertices,
                                  SETindex_(horizon->neighbors, neighbor))) {
              visible= neighbor;
              break;
            }
          }else
            visible= neighbor;
        }
      }
      if (visible) {
        visible->f.replace= newfacet;
        qh_setreplace(horizon->neighbors, visible, newfacet);
      }else {
        qh_fprintf(qh ferr, 6102, "qhull internal error (qh_attachnewfacets): couldn't find visible facet for horizon f%d of newfacet f%d\n",
                 horizon->id, newfacet->id);
        qh_errexit2(qh_ERRqhull, horizon, newfacet);
      }
    }else { /* non-simplicial, with a ridge for newfacet */
      FOREACHneighbor_(horizon) {    /* may hold for many new facets */
        if (neighbor->visible) {
          neighbor->f.replace= newfacet;
          qh_setdelnth(horizon->neighbors,
                        SETindex_(horizon->neighbors, neighbor));
          neighborp--; /* repeat */
        }
      }
      qh_setappend(&horizon->neighbors, newfacet);
      ridge= SETfirstt_(newfacet->ridges, ridgeT);
      if (ridge->top == horizon)
        ridge->bottom= newfacet;
      else
        ridge->top= newfacet;
      }
  } /* newfacets */
  if (qh PRINTstatistics) {
    FORALLvisible_facets {
      if (!visible->f.replace)
        zinc_(Zinsidevisible);
    }
  }
} /* attachnewfacets */
References ridgeT::bottom, FORALLnew_facets, FORALLvisible_facets, FOREACHneighbor_, FOREACHridge_, facetT::id, facetT::neighbors, NULL, otherfacet_, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), qh_memfree(), qh_setappend(), qh_setdel(), qh_setdelnth(), qh_setequal_skip(), qh_setfree(), qh_setreplace(), facetT::ridges, SETfirst_, SETfirstt_, SETindex_, ridgeT::top, trace1, trace3, True, facetT::vertices, ridgeT::vertices, and zinc_.
Referenced by qh_addpoint(), and qh_addpoint().
qh_checkflipped()
boolT qh_checkflipped (facetT * facet, realT * distp, boolT allerror)
{
  realT dist;
  if (facet->flipped && !distp)
    return False;
  zzinc_(Zdistcheck);
  qh_distplane(qh interior_point, facet, &dist);
  if (distp)
    *distp= dist;
  if ((allerror && dist > -qh DISTround)|| (!allerror && dist >= 0.0)) {
    facet->flipped= True;
    zzinc_(Zflippedfacets);
    trace0((qh ferr, 19, "qh_checkflipped: facet f%d is flipped, distance= %6.12g during p%d\n",
              facet->id, dist, qh furthest_id));
    qh_precision("flipped facet");
    return False;
  }
  return True;
} /* checkflipped */
References False, facetT::flipped, facetT::id, qh, qh_distplane(), qh_precision(), realT, trace0, True, Zdistcheck, Zflippedfacets, and zzinc_.
Referenced by qh_checkflipped_all(), qh_checkflipped_all(), qh_initialhull(), qh_initialhull(), and qh_matchnewfacets().
qh_deletevisible()
void qh_deletevisible (void)
{
  facetT *visible, *nextfacet;
  vertexT *vertex, **vertexp;
  int numvisible= 0, numdel= qh_setsize(qh del_vertices);
  trace1((qh ferr, 1018, "qh_deletevisible: delete %d visible facets and %d vertices\n",
         qh num_visible, numdel));
  for (visible= qh visible_list; visible && visible->visible;
                visible= nextfacet) { /* deleting current */
    nextfacet= visible->next;
    numvisible++;
    qh_delfacet(visible);
  }
  if (numvisible != qh num_visible) {
    qh_fprintf(qh ferr, 6103, "qhull internal error (qh_deletevisible): qh num_visible %d is not number of visible facets %d\n",
             qh num_visible, numvisible);
    qh_errexit(qh_ERRqhull, NULL, NULL);
  }
  qh num_visible= 0;
  zadd_(Zvisfacettot, numvisible);
  zmax_(Zvisfacetmax, numvisible);
  zzadd_(Zdelvertextot, numdel);
  zmax_(Zdelvertexmax, numdel);
  FOREACHvertex_(qh del_vertices)
    qh_delvertex(vertex);
  qh_settruncate(qh del_vertices, 0);
} /* deletevisible */
References FOREACHvertex_, facetT::next, NULL, qh, qh_delfacet(), qh_delvertex(), qh_errexit(), qh_ERRqhull, qh_fprintf(), qh_setsize(), qh_settruncate(), trace1, facetT::visible, zadd_, Zdelvertextot, zmax_, and zzadd_.
Referenced by qh_addpoint(), qh_addpoint(), qh_qhull(), and qh_qhull().
qh_delfacet()
void qh_delfacet (facetT * facet)
{
  void **freelistp; /* used if !qh_NOmem by qh_memfree_() */
  trace4((qh ferr, 4046, "qh_delfacet: delete f%d\n", facet->id));
  if (facet == qh tracefacet)
    qh tracefacet= NULL;
  if (facet == qh GOODclosest)
    qh GOODclosest= NULL;
  qh_removefacet(facet);
  if (!facet->tricoplanar || facet->keepcentrum) {
    qh_memfree_(facet->normal, qh normal_size, freelistp);
    if (qh CENTERtype == qh_ASvoronoi) {   /* braces for macro calls */
      qh_memfree_(facet->center, qh center_size, freelistp);
    }else /* AScentrum */ {
      qh_memfree_(facet->center, qh normal_size, freelistp);
    }
  }
  qh_setfree(&(facet->neighbors));
  if (facet->ridges)
    qh_setfree(&(facet->ridges));
  qh_setfree(&(facet->vertices));
  if (facet->outsideset)
    qh_setfree(&(facet->outsideset));
  if (facet->coplanarset)
    qh_setfree(&(facet->coplanarset));
  qh_memfree_(facet, (int)sizeof(facetT), freelistp);
} /* delfacet */
References facetT::center, facetT::coplanarset, facetT::id, facetT::keepcentrum, facetT::neighbors, facetT::normal, NULL, facetT::outsideset, qh, qh_ASvoronoi, qh_memfree_, qh_removefacet(), qh_setfree(), facetT::ridges, trace4, facetT::tricoplanar, and facetT::vertices.
Referenced by qh_addpoint(), qh_addpoint(), qh_deletevisible(), qh_freebuild(), qh_freebuild(), qh_triangulate(), and qh_triangulate().
qh_facetintersect()
setT * qh_facetintersect (facetT * facetA, facetT * facetB, int * skipA, int * skipB, int prepend)
{
  setT *intersect;
  int dim= qh hull_dim, i, j;
  facetT **neighborsA, **neighborsB;
  neighborsA= SETaddr_(facetA->neighbors, facetT);
  neighborsB= SETaddr_(facetB->neighbors, facetT);
  i= j= 0;
  if (facetB == *neighborsA++)
    *skipA= 0;
  else if (facetB == *neighborsA++)
    *skipA= 1;
  else if (facetB == *neighborsA++)
    *skipA= 2;
  else {
    for (i=3; i < dim; i++) {
      if (facetB == *neighborsA++) {
        *skipA= i;
        break;
      }
    }
  }
  if (facetA == *neighborsB++)
    *skipB= 0;
  else if (facetA == *neighborsB++)
    *skipB= 1;
  else if (facetA == *neighborsB++)
    *skipB= 2;
  else {
    for (j=3; j < dim; j++) {
      if (facetA == *neighborsB++) {
        *skipB= j;
        break;
      }
    }
  }
  if (i >= dim || j >= dim) {
    qh_fprintf(qh ferr, 6104, "qhull internal error (qh_facetintersect): f%d or f%d not in others neighbors\n",
            facetA->id, facetB->id);
    qh_errexit2(qh_ERRqhull, facetA, facetB);
  }
  intersect= qh_setnew_delnthsorted(facetA->vertices, qh hull_dim, *skipA, prepend);
  trace4((qh ferr, 4047, "qh_facetintersect: f%d skip %d matches f%d skip %d\n",
          facetA->id, *skipA, facetB->id, *skipB));
  return(intersect);
} /* facetintersect */
References facetT::id, facetT::neighbors, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), qh_setnew_delnthsorted(), SETaddr_, trace4, and facetT::vertices.
Referenced by qh_makenew_simplicial().
qh_gethash()
int qh_gethash (int hashsize, setT * set, int size, int firstindex, void * skipelem)
{
  void **elemp= SETelemaddr_(set, firstindex, void);
  ptr_intT hash = 0, elem;
  unsigned result;
  int i;
#ifdef _MSC_VER                   /* Microsoft Visual C++ -- warn about 64-bit issues */
#pragma warning(push)            /* WARN64 -- ptr_intT holds a 64-bit pointer */
#pragma warning(disable : 4311)  /* 'type cast': pointer truncation from 'void*' to 'ptr_intT' */
#endif
  switch (size-firstindex) {
  case 1:
    hash= (ptr_intT)(*elemp) - (ptr_intT) skipelem;
    break;
  case 2:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] - (ptr_intT) skipelem;
    break;
  case 3:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] + (ptr_intT)elemp[2]
      - (ptr_intT) skipelem;
    break;
  case 4:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] + (ptr_intT)elemp[2]
      + (ptr_intT)elemp[3] - (ptr_intT) skipelem;
    break;
  case 5:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] + (ptr_intT)elemp[2]
      + (ptr_intT)elemp[3] + (ptr_intT)elemp[4] - (ptr_intT) skipelem;
    break;
  case 6:
    hash= (ptr_intT)(*elemp) + (ptr_intT)elemp[1] + (ptr_intT)elemp[2]
      + (ptr_intT)elemp[3] + (ptr_intT)elemp[4]+ (ptr_intT)elemp[5]
      - (ptr_intT) skipelem;
    break;
  default:
    hash= 0;
    i= 3;
    do {     /* this is about 10% in 10-d */
      if ((elem= (ptr_intT)*elemp++) != (ptr_intT)skipelem) {
        hash ^= (elem << i) + (elem >> (32-i));
        i += 3;
        if (i >= 32)
          i -= 32;
      }
    }while (*elemp);
    break;
  }
  if (hashsize<0) {
    qh_fprintf(qh ferr, 6202, "qhull internal error: negative hashsize %d passed to qh_gethash [poly.c]\n", hashsize);
    qh_errexit2(qh_ERRqhull, NULL, NULL);
  }
  result= (unsigned)hash;
  result %= (unsigned)hashsize;
  /* result= 0; for debugging */
  return result;
#ifdef _MSC_VER
#pragma warning(pop)
#endif
} /* gethash */
References hash(), NULL, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), SETelemaddr_, and size.
Referenced by qh_hashridge(), qh_hashridge(), qh_hashridge_find(), qh_hashridge_find(), qh_matchduplicates(), qh_matchduplicates(), and qh_matchneighbor().
qh_makenew_nonsimplicial()
facetT * qh_makenew_nonsimplicial (facetT * visible, vertexT * apex, int * numnew)
{
  void **freelistp; /* used if !qh_NOmem by qh_memfree_() */
  ridgeT *ridge, **ridgep;
  facetT *neighbor, *newfacet= NULL, *samecycle;
  setT *vertices;
  boolT toporient;
  int ridgeid;
  FOREACHridge_(visible->ridges) {
    ridgeid= ridge->id;
    neighbor= otherfacet_(ridge, visible);
    if (neighbor->visible) {
      if (!qh ONLYgood) {
        if (neighbor->visitid == qh visit_id) {
          qh_setfree(&(ridge->vertices));  /* delete on 2nd visit */
          qh_memfree_(ridge, (int)sizeof(ridgeT), freelistp);
        }
      }
    }else {  /* neighbor is an horizon facet */
      toporient= (ridge->top == visible);
      vertices= qh_setnew(qh hull_dim); /* makes sure this is quick */
      qh_setappend(&vertices, apex);
      qh_setappend_set(&vertices, ridge->vertices);
      newfacet= qh_makenewfacet(vertices, toporient, neighbor);
      (*numnew)++;
      if (neighbor->coplanar) {
        newfacet->mergehorizon= True;
        if (!neighbor->seen) {
          newfacet->f.samecycle= newfacet;
          neighbor->f.newcycle= newfacet;
        }else {
          samecycle= neighbor->f.newcycle;
          newfacet->f.samecycle= samecycle->f.samecycle;
          samecycle->f.samecycle= newfacet;
        }
      }
      if (qh ONLYgood) {
        if (!neighbor->simplicial)
          qh_setappend(&(newfacet->ridges), ridge);
      }else {  /* qh_attachnewfacets */
        if (neighbor->seen) {
          if (neighbor->simplicial) {
            qh_fprintf(qh ferr, 6105, "qhull internal error (qh_makenew_nonsimplicial): simplicial f%d sharing two ridges with f%d\n",
                   neighbor->id, visible->id);
            qh_errexit2(qh_ERRqhull, neighbor, visible);
          }
          qh_setappend(&(neighbor->neighbors), newfacet);
        }else
          qh_setreplace(neighbor->neighbors, visible, newfacet);
        if (neighbor->simplicial) {
          qh_setdel(neighbor->ridges, ridge);
          qh_setfree(&(ridge->vertices));
          qh_memfree(ridge, (int)sizeof(ridgeT));
        }else {
          qh_setappend(&(newfacet->ridges), ridge);
          if (toporient)
            ridge->top= newfacet;
          else
            ridge->bottom= newfacet;
        }
      trace4((qh ferr, 4048, "qh_makenew_nonsimplicial: created facet f%d from v%d and r%d of horizon f%d\n",
            newfacet->id, apex->id, ridgeid, neighbor->id));
      }
    }
    neighbor->seen= True;
  } /* for each ridge */
  if (!qh ONLYgood)
    SETfirst_(visible->ridges)= NULL;
  return newfacet;
} /* makenew_nonsimplicial */
References boolT, ridgeT::bottom, facetT::coplanar, facetT::f, FOREACHridge_, facetT::id, ridgeT::id, vertexT::id, facetT::mergehorizon, facetT::neighbors, NULL, otherfacet_, qh, qh_errexit2(), qh_ERRqhull, qh_fprintf(), qh_makenewfacet(), qh_memfree(), qh_memfree_, qh_setappend(), qh_setappend_set(), qh_setdel(), qh_setfree(), qh_setnew(), qh_setreplace(), facetT::ridges, facetT::seen, SETfirst_, facetT::simplicial, ridgeT::top, trace4, True, ridgeT::vertices, facetT::visible, and facetT::visitid.
Referenced by qh_makenewfacets(), qh_makenewfacets(), qh_triangulate_facet(), and qh_triangulate_facet().
qh_makenew_simplicial()
facetT * qh_makenew_simplicial (facetT * visible, vertexT * apex, int * numnew)
{
  facetT *neighbor, **neighborp, *newfacet= NULL;
  setT *vertices;
  boolT flip, toporient;
  int horizonskip= 0, visibleskip= 0;
  FOREACHneighbor_(visible) {
    if (!neighbor->seen && !neighbor->visible) {
      vertices= qh_facetintersect(neighbor,visible, &horizonskip, &visibleskip, 1);
      SETfirst_(vertices)= apex;
      flip= ((horizonskip & 0x1) ^ (visibleskip & 0x1));
      if (neighbor->toporient)
        toporient= horizonskip & 0x1;
      else
        toporient= (horizonskip & 0x1) ^ 0x1;
      newfacet= qh_makenewfacet(vertices, toporient, neighbor);
      (*numnew)++;
      if (neighbor->coplanar && (qh PREmerge || qh MERGEexact)) {
#ifndef qh_NOmerge
        newfacet->f.samecycle= newfacet;
        newfacet->mergehorizon= True;
#endif
      }
      if (!qh ONLYgood)
        SETelem_(neighbor->neighbors, horizonskip)= newfacet;
      trace4((qh ferr, 4049, "qh_makenew_simplicial: create facet f%d top %d from v%d and horizon f%d skip %d top %d and visible f%d skip %d, flip? %d\n",
            newfacet->id, toporient, apex->id, neighbor->id, horizonskip,
              neighbor->toporient, visible->id, visibleskip, flip));
    }
  }
  return newfacet;
} /* makenew_simplicial */
References boolT, facetT::coplanar, facetT::f, FOREACHneighbor_, facetT::id, vertexT::id, facetT::mergehorizon, facetT::neighbors, NULL, qh, qh_facetintersect(), qh_makenewfacet(), facetT::seen, SETelem_, SETfirst_, facetT::toporient, trace4, True, and facetT::visible.
Referenced by qh_makenewfacets(), and qh_makenewfacets().
qh_makenewfacet()
facetT * qh_makenewfacet (setT * vertices, boolT toporient, facetT * horizon)
{
  facetT *newfacet;
  vertexT *vertex, **vertexp;
  FOREACHvertex_(vertices) {
    if (!vertex->newlist) {
      qh_removevertex(vertex);
      qh_appendvertex(vertex);
    }
  }
  newfacet= qh_newfacet();
  newfacet->vertices= vertices;
  newfacet->toporient= (unsigned char)toporient;
  if (horizon)
    qh_setappend(&(newfacet->neighbors), horizon);
  qh_appendfacet(newfacet);
  return(newfacet);
} /* makenewfacet */
References FOREACHvertex_, facetT::neighbors, qh_appendfacet(), qh_appendvertex(), qh_newfacet(), qh_removevertex(), qh_setappend(), facetT::toporient, and facetT::vertices.
Referenced by qh_makenew_nonsimplicial(), and qh_makenew_simplicial().
qh_makenewplanes()
void qh_makenewplanes (void)
{
  facetT *newfacet;
  FORALLnew_facets {
    if (!newfacet->mergehorizon)
      qh_setfacetplane(newfacet);
  }
  if (qh JOGGLEmax < REALmax/2)
    minimize_(qh min_vertex, -wwval_(Wnewvertexmax));
} /* makenewplanes */
References FORALLnew_facets, facetT::mergehorizon, minimize_, qh, qh_setfacetplane(), REALmax, Wnewvertexmax, and wwval_.
Referenced by qh_addpoint(), and qh_addpoint().
qh_matchneighbor()
void qh_matchneighbor (facetT * newfacet, int newskip, int hashsize, int * hashcount)
{
  boolT newfound= False;   /* True, if new facet is already in hash chain */
  boolT same, ismatch;
  int hash, scan;
  facetT *facet, *matchfacet;
  int skip, matchskip;
  hash= qh_gethash(hashsize, newfacet->vertices, qh hull_dim, 1,
                     SETelem_(newfacet->vertices, newskip));
  trace4((qh ferr, 4050, "qh_matchneighbor: newfacet f%d skip %d hash %d hashcount %d\n",
          newfacet->id, newskip, hash, *hashcount));
  zinc_(Zhashlookup);
  for (scan= hash; (facet= SETelemt_(qh hash_table, scan, facetT));
       scan= (++scan >= hashsize ? 0 : scan)) {
    if (facet == newfacet) {
      newfound= True;
      continue;
    }
    zinc_(Zhashtests);
    if (qh_matchvertices(1, newfacet->vertices, newskip, facet->vertices, &skip, &same)) {
      if (SETelem_(newfacet->vertices, newskip) ==
          SETelem_(facet->vertices, skip)) {
        qh_precision("two facets with the same vertices");
        qh_fprintf(qh ferr, 6106, "qhull precision error: Vertex sets are the same for f%d and f%d.  Can not force output.\n",
          facet->id, newfacet->id);
        qh_errexit2(qh_ERRprec, facet, newfacet);
      }
      ismatch= (same == (boolT)((newfacet->toporient ^ facet->toporient)));
      matchfacet= SETelemt_(facet->neighbors, skip, facetT);
      if (ismatch && !matchfacet) {
        SETelem_(facet->neighbors, skip)= newfacet;
        SETelem_(newfacet->neighbors, newskip)= facet;
        (*hashcount)--;
        trace4((qh ferr, 4051, "qh_matchneighbor: f%d skip %d matched with new f%d skip %d\n",
           facet->id, skip, newfacet->id, newskip));
        return;
      }
      if (!qh PREmerge && !qh MERGEexact) {
        qh_precision("a ridge with more than two neighbors");
        qh_fprintf(qh ferr, 6107, "qhull precision error: facets f%d, f%d and f%d meet at a ridge with more than 2 neighbors.  Can not continue.\n",
                 facet->id, newfacet->id, getid_(matchfacet));
        qh_errexit2(qh_ERRprec, facet, newfacet);
      }
      SETelem_(newfacet->neighbors, newskip)= qh_DUPLICATEridge;
      newfacet->dupridge= True;
      if (!newfacet->normal)
        qh_setfacetplane(newfacet);
      qh_addhash(newfacet, qh hash_table, hashsize, hash);
      (*hashcount)++;
      if (!facet->normal)
        qh_setfacetplane(facet);
      if (matchfacet != qh_DUPLICATEridge) {
        SETelem_(facet->neighbors, skip)= qh_DUPLICATEridge;
        facet->dupridge= True;
        if (!facet->normal)
          qh_setfacetplane(facet);
        if (matchfacet) {
          matchskip= qh_setindex(matchfacet->neighbors, facet);
          if (matchskip<0) {
              qh_fprintf(qh ferr, 6260, "qhull internal error (qh_matchneighbor): matchfacet f%d is in f%d neighbors but not vice versa.  Can not continue.\n",
                  matchfacet->id, facet->id);
              qh_errexit2(qh_ERRqhull, matchfacet, facet);
          }
          SETelem_(matchfacet->neighbors, matchskip)= qh_DUPLICATEridge; /* matchskip>=0 by QH6260 */
          matchfacet->dupridge= True;
          if (!matchfacet->normal)
            qh_setfacetplane(matchfacet);
          qh_addhash(matchfacet, qh hash_table, hashsize, hash);
          *hashcount += 2;
        }
      }
      trace4((qh ferr, 4052, "qh_matchneighbor: new f%d skip %d duplicates ridge for f%d skip %d matching f%d ismatch %d at hash %d\n",
           newfacet->id, newskip, facet->id, skip,
           (matchfacet == qh_DUPLICATEridge ? -2 : getid_(matchfacet)),
           ismatch, hash));
      return; /* end of duplicate ridge */
    }
  }
  if (!newfound)
    SETelem_(qh hash_table, scan)= newfacet;  /* same as qh_addhash */
  (*hashcount)++;
  trace4((qh ferr, 4053, "qh_matchneighbor: no match for f%d skip %d at hash %d\n",
           newfacet->id, newskip, hash));
} /* matchneighbor */
References boolT, facetT::dupridge, False, getid_, hash(), facetT::id, facetT::neighbors, facetT::normal, qh, qh_addhash(), qh_DUPLICATEridge, qh_errexit2(), qh_ERRprec, qh_ERRqhull, qh_fprintf(), qh_gethash(), qh_matchvertices(), qh_precision(), qh_setfacetplane(), qh_setindex(), SETelem_, SETelemt_, facetT::toporient, trace4, True, facetT::vertices, and zinc_.
Referenced by qh_matchnewfacets().
qh_matchnewfacets()
void qh_matchnewfacets (void)
{
  int numnew=0, hashcount=0, newskip;
  facetT *newfacet, *neighbor;
  int dim= qh hull_dim, hashsize, neighbor_i, neighbor_n;
  setT *neighbors;
#ifndef qh_NOtrace
  int facet_i, facet_n, numfree= 0;
  facetT *facet;
#endif
  trace1((qh ferr, 1019, "qh_matchnewfacets: match neighbors for new facets.\n"));
  FORALLnew_facets {
    numnew++;
    {  /* inline qh_setzero(newfacet->neighbors, 1, qh hull_dim); */
      neighbors= newfacet->neighbors;
      neighbors->e[neighbors->maxsize].i= dim+1; /*may be overwritten*/
      memset((char *)SETelemaddr_(neighbors, 1, void), 0, dim * SETelemsize);
    }
  }
  qh_newhashtable(numnew*(qh hull_dim-1)); /* twice what is normally needed,
                                     but every ridge could be DUPLICATEridge */
  hashsize= qh_setsize(qh hash_table);
  FORALLnew_facets {
    for (newskip=1; newskip<qh hull_dim; newskip++) /* furthest/horizon already matched */
      /* hashsize>0 because hull_dim>1 and numnew>0 */
      qh_matchneighbor(newfacet, newskip, hashsize, &hashcount);
#if 0   /* use the following to trap hashcount errors */
    {
      int count= 0, k;
      facetT *facet, *neighbor;
      count= 0;
      FORALLfacet_(qh newfacet_list) {  /* newfacet already in use */
        for (k=1; k < qh hull_dim; k++) {
          neighbor= SETelemt_(facet->neighbors, k, facetT);
          if (!neighbor || neighbor == qh_DUPLICATEridge)
            count++;
        }
        if (facet == newfacet)
          break;
      }
      if (count != hashcount) {
        qh_fprintf(qh ferr, 8088, "qh_matchnewfacets: after adding facet %d, hashcount %d != count %d\n",
                 newfacet->id, hashcount, count);
        qh_errexit(qh_ERRqhull, newfacet, NULL);
      }
    }
#endif  /* end of trap code */
  }
  if (hashcount) {
    FORALLnew_facets {
      if (newfacet->dupridge) {
        FOREACHneighbor_i_(newfacet) {
          if (neighbor == qh_DUPLICATEridge) {
            qh_matchduplicates(newfacet, neighbor_i, hashsize, &hashcount);
                    /* this may report MERGEfacet */
          }
        }
      }
    }
  }
  if (hashcount) {
    qh_fprintf(qh ferr, 6108, "qhull internal error (qh_matchnewfacets): %d neighbors did not match up\n",
        hashcount);
    qh_printhashtable(qh ferr);
    qh_errexit(qh_ERRqhull, NULL, NULL);
  }
#ifndef qh_NOtrace
  if (qh IStracing >= 2) {
    FOREACHfacet_i_(qh hash_table) {
      if (!facet)
        numfree++;
    }
    qh_fprintf(qh ferr, 8089, "qh_matchnewfacets: %d new facets, %d unused hash entries .  hashsize %d\n",
             numnew, numfree, qh_setsize(qh hash_table));
  }
#endif /* !qh_NOtrace */
  qh_setfree(&qh hash_table);
  if (qh PREmerge || qh MERGEexact) {
    if (qh IStracing >= 4)
      qh_printfacetlist(qh newfacet_list, NULL, qh_ALL);
    FORALLnew_facets {
      if (newfacet->normal)
        qh_checkflipped(newfacet, NULL, qh_ALL);
    }
  }else if (qh FORCEoutput)
    qh_checkflipped_all(qh newfacet_list);  /* prints warnings for flipped */
} /* matchnewfacets */
References count, facetT::dupridge, setT::e, FORALLfacet_, FORALLnew_facets, FOREACHfacet_i_, FOREACHneighbor_i_, setelemT::i, facetT::id, setT::maxsize, memset, facetT::neighbors, facetT::normal, NULL, qh, qh_ALL, qh_checkflipped(), qh_checkflipped_all(), qh_DUPLICATEridge, qh_errexit(), qh_ERRqhull, qh_fprintf(), qh_matchduplicates(), qh_matchneighbor(), qh_newhashtable(), qh_printfacetlist(), qh_printhashtable(), qh_setfree(), qh_setsize(), SETelemaddr_, SETelemsize, SETelemt_, and trace1.
Referenced by qh_addpoint(), qh_addpoint(), qh_triangulate_facet(), and qh_triangulate_facet().
qh_matchvertices()
boolT qh_matchvertices (int firstindex, setT * verticesA, int skipA, setT * verticesB, int * skipB, boolT * same)
{
  vertexT **elemAp, **elemBp, **skipBp=NULL, **skipAp;
  elemAp= SETelemaddr_(verticesA, firstindex, vertexT);
  elemBp= SETelemaddr_(verticesB, firstindex, vertexT);
  skipAp= SETelemaddr_(verticesA, skipA, vertexT);
  do if (elemAp != skipAp) {
    while (*elemAp != *elemBp++) {
      if (skipBp)
        return False;
      skipBp= elemBp;  /* one extra like FOREACH */
    }
  }while (*(++elemAp));
  if (!skipBp)
    skipBp= ++elemBp;
  *skipB= SETindex_(verticesB, skipB); /* i.e., skipBp - verticesB */
  *same= !((skipA & 0x1) ^ (*skipB & 0x1)); /* result is 0 or 1 */
  trace4((qh ferr, 4054, "qh_matchvertices: matched by skip %d(v%d) and skip %d(v%d) same? %d\n",
          skipA, (*skipAp)->id, *skipB, (*(skipBp-1))->id, *same));
  return(True);
} /* matchvertices */
References False, NULL, qh, SETelemaddr_, SETindex_, trace4, and True.
Referenced by qh_matchduplicates(), qh_matchduplicates(), and qh_matchneighbor().
qh_newfacet()
facetT * qh_newfacet (void)
{
  facetT *facet;
  void **freelistp; /* used if !qh_NOmem by qh_memalloc_() */
  qh_memalloc_((int)sizeof(facetT), freelistp, facet, facetT);
  memset((char *)facet, (size_t)0, sizeof(facetT));
  if (qh facet_id == qh tracefacet_id)
    qh tracefacet= facet;
  facet->id= qh facet_id++;
  facet->neighbors= qh_setnew(qh hull_dim);
#if !qh_COMPUTEfurthest
  facet->furthestdist= 0.0;
#endif
#if qh_MAXoutside
  if (qh FORCEoutput && qh APPROXhull)
    facet->maxoutside= qh MINoutside;
  else
    facet->maxoutside= qh DISTround;
#endif
  facet->simplicial= True;
  facet->good= True;
  facet->newfacet= True;
  trace4((qh ferr, 4055, "qh_newfacet: created facet f%d\n", facet->id));
  return(facet);
} /* newfacet */
References facetT::furthestdist, facetT::good, facetT::id, memset, facetT::neighbors, facetT::newfacet, qh, qh_memalloc_, qh_setnew(), facetT::simplicial, trace4, and True.
Referenced by qh_createsimplex(), qh_createsimplex(), qh_makenewfacet(), and qh_makenewfacet().
qh_newridge()
ridgeT * qh_newridge (void)
{
  ridgeT *ridge;
  void **freelistp;   /* used if !qh_NOmem by qh_memalloc_() */
  qh_memalloc_((int)sizeof(ridgeT), freelistp, ridge, ridgeT);
  memset((char *)ridge, (size_t)0, sizeof(ridgeT));
  zinc_(Ztotridges);
  if (qh ridge_id == UINT_MAX) {
    qh_fprintf(qh ferr, 7074, "\
qhull warning: more than 2^32 ridges.  Qhull results are OK.  Since the ridge ID wraps around to 0, two ridges may have the same identifier.\n");
  }
  ridge->id= qh ridge_id++;
  trace4((qh ferr, 4056, "qh_newridge: created ridge r%d\n", ridge->id));
  return(ridge);
} /* newridge */
References ridgeT::id, memset, qh, qh_fprintf(), qh_memalloc_, trace4, and zinc_.
Referenced by qh_makeridges(), qh_makeridges(), qh_mergecycle_ridges(), and qh_mergecycle_ridges().
qh_pointid()
int qh_pointid (pointT * point)
{
  ptr_intT offset, id;
  if (!point)
    return qh_IDnone;
  else if (point == qh interior_point)
    return qh_IDinterior;
  else if (point >= qh first_point
  && point < qh first_point + qh num_points * qh hull_dim) {
    offset= (ptr_intT)(point - qh first_point);
    id= offset / qh hull_dim;
  }else if ((id= qh_setindex(qh other_points, point)) != -1)
    id += qh num_points;
  else
    return qh_IDunknown;
  return (int)id;
} /* pointid */
References qh, qh_IDinterior, qh_IDnone, qh_IDunknown, and qh_setindex().
Referenced by orgQhull::QhullPoint::id(), qh_addpoint(), qh_addpoint(), qh_buildhull(), qh_buildhull(), qh_buildtracing(), qh_buildtracing(), qh_check_maxout(), qh_check_maxout(), qh_check_point(), qh_check_point(), qh_checkconvex(), qh_checkconvex(), qh_checkpolygon(), qh_checkpolygon(), qh_checkvertex(), qh_checkvertex(), qh_compare_vertexpoint(), qh_detsimplex(), qh_detsimplex(), qh_detvnorm(), qh_detvnorm(), qh_detvridge3(), qh_detvridge3(), qh_distplane(), qh_distplane(), qh_eachvoronoi(), qh_eachvoronoi(), qh_eachvoronoi_all(), qh_eachvoronoi_all(), qh_facetarea_simplex(), qh_facetarea_simplex(), qh_findbest(), qh_findbest(), qh_findbestlower(), qh_findbestlower(), qh_findbestnew(), qh_findbestnew(), qh_findgood_all(), qh_findgood_all(), qh_findgooddist(), qh_findgooddist(), qh_findhorizon(), qh_findhorizon(), qh_furthestout(), qh_furthestout(), qh_initbuild(), qh_initbuild(), qh_makenewfacets(), qh_makenewfacets(), qh_maxsimplex(), qh_maxsimplex(), qh_nearvertex(), qh_nearvertex(), qh_newvertex(), qh_newvertex(), qh_partitionall(), qh_partitionall(), qh_partitioncoplanar(), qh_partitioncoplanar(), qh_partitionpoint(), qh_partitionpoint(), qh_point_add(), qh_point_add(), qh_printafacet(), qh_printafacet(), qh_printbegin(), qh_printbegin(), qh_printextremes(), qh_printextremes(), qh_printextremes_2d(), qh_printextremes_2d(), qh_printextremes_d(), qh_printextremes_d(), qh_printfacet3vertex(), qh_printfacet3vertex(), qh_printfacetheader(), qh_printfacetheader(), qh_printfacetNvertex_nonsimplicial(), qh_printfacetNvertex_nonsimplicial(), qh_printfacetNvertex_simplicial(), qh_printfacetNvertex_simplicial(), qh_printhelp_singular(), qh_printhelp_singular(), qh_printhyperplaneintersection(), qh_printhyperplaneintersection(), qh_printline3geom(), qh_printline3geom(), qh_printpoint(), qh_printpoint(), qh_printpoint3(), qh_printpoint3(), qh_printpoints(), qh_printpoints(), qh_printpoints_out(), qh_printpoints_out(), qh_printsummary(), qh_printsummary(), qh_printvdiagram2(), qh_printvdiagram2(), qh_printvertex(), qh_printvertex(), qh_printvertices(), qh_printvertices(), qh_printvnorm(), qh_printvnorm(), qh_printvridge(), qh_printvridge(), qh_rename_sharedvertex(), qh_rename_sharedvertex(), qh_setfacetplane(), qh_setfacetplane(), qh_updatevertices(), qh_voronoi_center(), and qh_voronoi_center().
qh_removefacet()
void qh_removefacet (facetT * facet)
{
  facetT *next= facet->next, *previous= facet->previous;
  if (facet == qh newfacet_list)
    qh newfacet_list= next;
  if (facet == qh facet_next)
    qh facet_next= next;
  if (facet == qh visible_list)
    qh visible_list= next;
  if (previous) {
    previous->next= next;
    next->previous= previous;
  }else {  /* 1st facet in qh facet_list */
    qh facet_list= next;
    qh facet_list->previous= NULL;
  }
  qh num_facets--;
  trace4((qh ferr, 4057, "qh_removefacet: remove f%d from facet_list\n", facet->id));
} /* removefacet */
References facetT::id, facetT::next, NULL, facetT::previous, qh, and trace4.
Referenced by qh_checkconnect(), qh_checkconnect(), qh_delfacet(), qh_findgooddist(), qh_findgooddist(), qh_findhorizon(), qh_findhorizon(), qh_furthestnext(), qh_furthestnext(), qh_mergecycle_facets(), qh_mergecycle_facets(), qh_mergefacet(), qh_mergefacet(), qh_nextfurthest(), qh_nextfurthest(), qh_partitionpoint(), qh_partitionpoint(), qh_willdelete(), and qh_willdelete().
qh_removevertex()
void qh_removevertex (vertexT * vertex)
{
  vertexT *next= vertex->next, *previous= vertex->previous;
  if (vertex == qh newvertex_list)
    qh newvertex_list= next;
  if (previous) {
    previous->next= next;
    next->previous= previous;
  }else {  /* 1st vertex in qh vertex_list */
    qh vertex_list= vertex->next;
    qh vertex_list->previous= NULL;
  }
  qh num_vertices--;
  trace4((qh ferr, 4058, "qh_removevertex: remove v%d from vertex_list\n", vertex->id));
} /* removevertex */
References vertexT::next, NULL, vertexT::previous, qh, and trace4.
Referenced by qh_delvertex(), qh_delvertex(), qh_makenewfacet(), qh_mergesimplex(), qh_mergesimplex(), qh_newvertices(), and qh_newvertices().
qh_updatevertices()
void qh_updatevertices (void)
{
  facetT *newfacet= NULL, *neighbor, **neighborp, *visible;
  vertexT *vertex, **vertexp;
  trace3((qh ferr, 3013, "qh_updatevertices: delete interior vertices and update vertex->neighbors\n"));
  if (qh VERTEXneighbors) {
    FORALLvertex_(qh newvertex_list) {
      FOREACHneighbor_(vertex) {
        if (neighbor->visible)
          SETref_(neighbor)= NULL;
      }
      qh_setcompact(vertex->neighbors);
    }
    FORALLnew_facets {
      FOREACHvertex_(newfacet->vertices)
        qh_setappend(&vertex->neighbors, newfacet);
    }
    FORALLvisible_facets {
      FOREACHvertex_(visible->vertices) {
        if (!vertex->newlist && !vertex->deleted) {
          FOREACHneighbor_(vertex) { /* this can happen under merging */
            if (!neighbor->visible)
              break;
          }
          if (neighbor)
            qh_setdel(vertex->neighbors, visible);
          else {
            vertex->deleted= True;
            qh_setappend(&qh del_vertices, vertex);
            trace2((qh ferr, 2041, "qh_updatevertices: delete vertex p%d(v%d) in f%d\n",
                  qh_pointid(vertex->point), vertex->id, visible->id));
          }
        }
      }
    }
  }else {  /* !VERTEXneighbors */
    FORALLvisible_facets {
      FOREACHvertex_(visible->vertices) {
        if (!vertex->newlist && !vertex->deleted) {
          vertex->deleted= True;
          qh_setappend(&qh del_vertices, vertex);
          trace2((qh ferr, 2042, "qh_updatevertices: delete vertex p%d(v%d) in f%d\n",
                  qh_pointid(vertex->point), vertex->id, visible->id));
        }
      }
    }
  }
} /* updatevertices */
References FORALLnew_facets, FORALLvertex_, FORALLvisible_facets, FOREACHneighbor_, FOREACHvertex_, NULL, qh, qh_pointid(), qh_setappend(), qh_setcompact(), qh_setdel(), SETref_, trace2, trace3, True, and facetT::vertices.
Referenced by qh_addpoint(), qh_addpoint(), qh_triangulate(), qh_triangulate(), qh_triangulate_facet(), and qh_triangulate_facet().