OrcaSlicer: src/slic3r/GUI/WipeTowerDialog.cpp File Reference
WipeTowerDialog.cpp File Reference
#include <algorithm>
#include <sstream>
#include "WipeTowerDialog.hpp"
#include "BitmapCache.hpp"
#include "GUI.hpp"
#include "I18N.hpp"
#include "GUI_App.hpp"
#include "MsgDialog.hpp"
#include "Widgets/Button.hpp"
#include "slic3r/Utils/ColorSpaceConvert.hpp"
#include <wx/sizer.h>
Macros
#define ICON_SIZE wxSize(FromDIP(16), FromDIP(16))
#define TABLE_BORDER FromDIP(28)
#define HEADER_VERT_PADDING FromDIP(12)
#define HEADER_BEG_PADDING FromDIP(30)
#define ICON_GAP FromDIP(44)
#define HEADER_END_PADDING FromDIP(24)
#define ROW_VERT_PADDING FromDIP(6)
#define ROW_BEG_PADDING FromDIP(20)
#define EDIT_BOXES_GAP FromDIP(30)
#define ROW_END_PADDING FromDIP(21)
#define BTN_SIZE wxSize(FromDIP(58), FromDIP(24))
#define BTN_GAP FromDIP(20)
#define TEXT_BEG_PADDING FromDIP(41)
#define MAX_FLUSH_VALUE 999
#define MIN_WIPING_DIALOG_WIDTH FromDIP(400)
#define style wxSP_ARROW_KEYS
Functions
int scale (const int val)
int ITEM_WIDTH ()
static void update_ui (wxWindow *window)
static float to_radians (float degree)
float DeltaHS_BBS (float h1, float s1, float v1, float h2, float s2, float v2)
static float get_luminance (float r, float g, float b)
static float calc_triangle_3rd_edge (float edge_a, float edge_b, float degree_ab)
Variables
static const wxColour g_text_color = wxColour(107, 107, 107, 255)
static const int m_max_flush_volume = 750.f
static const int g_min_flush_volume_from_support = 420.f
static const int g_flush_volume_to_support = 230
static const float g_min_flush_multiplier = 0.f
static const float g_max_flush_multiplier = 3.f
Macro Definition Documentation
BTN_GAP
#define BTN_GAP FromDIP(20)
BTN_SIZE
#define BTN_SIZE wxSize(FromDIP(58), FromDIP(24))
EDIT_BOXES_GAP
#define EDIT_BOXES_GAP FromDIP(30)
HEADER_BEG_PADDING
#define HEADER_BEG_PADDING FromDIP(30)
HEADER_END_PADDING
#define HEADER_END_PADDING FromDIP(24)
HEADER_VERT_PADDING
#define HEADER_VERT_PADDING FromDIP(12)
ICON_GAP
#define ICON_GAP FromDIP(44)
ICON_SIZE
#define ICON_SIZE wxSize(FromDIP(16), FromDIP(16))
MAX_FLUSH_VALUE
#define MAX_FLUSH_VALUE 999
MIN_WIPING_DIALOG_WIDTH
#define MIN_WIPING_DIALOG_WIDTH FromDIP(400)
ROW_BEG_PADDING
#define ROW_BEG_PADDING FromDIP(20)
ROW_END_PADDING
#define ROW_END_PADDING FromDIP(21)
ROW_VERT_PADDING
#define ROW_VERT_PADDING FromDIP(6)
style
#define style wxSP_ARROW_KEYS
TABLE_BORDER
#define TABLE_BORDER FromDIP(28)
TEXT_BEG_PADDING
#define TEXT_BEG_PADDING FromDIP(41)
Function Documentation
calc_triangle_3rd_edge()
static float calc_triangle_3rd_edge (float edge_a, float edge_b, float degree_ab) static
{
    return std::sqrt(edge_a * edge_a + edge_b * edge_b - 2 * edge_a * edge_b * std::cos(to_radians(degree_ab)));
}
References to_radians().
Referenced by WipingPanel::calc_flushing_volume().
DeltaHS_BBS()
float DeltaHS_BBS (float h1, float s1, float v1, float h2, float s2, float v2)
{
    float h1_rad = to_radians(h1);
    float h2_rad = to_radians(h2);
    float dx = std::cos(h1_rad) * s1 * v1 - cos(h2_rad) * s2 * v2;
    float dy = std::sin(h1_rad) * s1 * v1 - sin(h2_rad) * s2 * v2;
    float dxy = std::sqrt(dx * dx + dy * dy);
    return std::min(1.2f, dxy);
}
References cos(), sin(), and to_radians().
Referenced by WipingPanel::calc_flushing_volume().
get_luminance()
static float get_luminance (float r, float g, float b) static
{
    return r * 0.3 + g * 0.59 + b * 0.11;
}
Referenced by WipingPanel::calc_flushing_volume().
ITEM_WIDTH()
int ITEM_WIDTH ()
{ return scale(30); }
References scale().
Referenced by WipingDialog::WipingDialog(), and WipingPanel::WipingPanel().
scale()
int scale (const int val)
{ return val * Slic3r::GUI::wxGetApp().em_unit() / 10; }
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), Slic3r::GUI::GLCanvas3D::_render_overlays(), Slic3r::GUI::Camera::apply_projection(), Slic3r::Geometry::assemble_transform(), Slic3r::Geometry::assemble_transform(), ImGui::BBLRenderArrow(), Clipper2Lib::BooleanOpD(), Clipper2Lib::BooleanOpPtD(), ImGuiWindow::CalcFontSize(), ImFont::CalcTextSizeA(), ImFont::CalcWordWrapPositionA(), Slic3r::GUI::GizmoObjectManipulation::change_scale_value(), Eigen::SelfAdjointEigenSolver< _MatrixType >::compute(), Eigen::RealSchur< _MatrixType >::compute(), Eigen::BDCSVD< _MatrixType >::compute(), Eigen::JacobiSVD< _MatrixType, QRPreconditioner >::compute(), Clipper2Lib::ConvertCPathD(), Clipper2Lib::ConvertCPathsD(), Clipper2Lib::CreateCPathD(), Clipper2Lib::CreateCPathsD(), Clipper2Lib::CreateCPolyTreeD(), ImGui::DebugRenderViewportThumbnail(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GizmoObjectManipulation::do_scale(), Slic3r::SVG::draw(), Slic3r::SVG::draw(), Slic3r::dump_voronoi_to_svg(), Slic3r::format_memsize_MB(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::fromPositionOrientationScale(), Slic3r::gcode_paint_bitmap(), Slic3r::GUI::get_data_from_svg(), Slic3r::SVG::get_path_d(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::grid_to_mesh(), Slic3r::GUI::IMSlider::horizontal_slider(), ImFontAtlasBuildWithStbTruetype(), Clipper2Lib::InflatePaths(), Clipper2Lib::InflatePathsD(), Clipper2Lib::InitCPolyPathD(), InputTextCalcTextSizeW(), ITEM_WIDTH(), Slic3r::GUI::GLTexture::load_from_svg(), Slic3r::GUI::IMTexture::load_from_svg_file(), Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), log_i(), log_i(), Clipper2Lib::MinkowskiDiff(), Clipper2Lib::MinkowskiSum(), Slic3r::normal(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::on_mouse_wheel(), Clipper2Lib::Point< T >::operator*(), Slic3r::GUI::ObjectList::part_selection_changed(), igl::procrustes(), igl::procrustes(), igl::procrustes(), Slic3r::GUI::GLGizmoText::push_combo_style(), Slic3r::GUI::ImGuiWrapper::push_combo_style(), Slic3r::GUI::ImGuiWrapper::push_common_window_style(), Slic3r::GUI::ImGuiWrapper::push_menu_style(), Slic3r::GUI::ImGuiWrapper::push_toolbar_style(), qh_randomfactor(), qh_randomfactor(), qh_scalelast(), qh_scalelast(), qh_scalepoints(), qh_scalepoints(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClipD(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLinesD(), Slic3r::GLVolume::render(), Slic3r::GUI::IMSlider::render(), Slic3r::GUI::NotificationManager::HintNotification::render_documentation_button(), Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_eject_button(), Slic3r::GUI::NotificationManager::HintNotification::render_preferences_button(), Slic3r::GUI::NotificationManager::HintNotification::render_right_arrow_button(), ImGui::RenderArrow(), ImGui::RenderArrow(), ImFont::RenderChar(), ImGui::RenderMouseCursor(), ImFont::RenderText(), SwitchButton::Rescale(), Slic3r::GUI::round_to_bin(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 3, false >::run(), Eigen::internal::direct_selfadjoint_eigenvalues< SolverType, 2, false >::run(), Slic3r::EdgeGrid::save_png(), Clipper2Lib::Rect< T >::Scale(), Slic3r::GUI::BBLSplashScreen::scale_bitmap(), Slic3r::GUI::SplashScreen::scale_bitmap(), Slic3r::GUI::BBLSplashScreen::scale_font(), Slic3r::GUI::SplashScreen::scale_font(), NppDarkMode::scaled(), Clipper2Lib::ScalePath(), Clipper2Lib::ScalePaths(), Clipper2Lib::ScaleRect(), libnest2d::shapelike::serialize< libnest2d::Formats::SVG >(), Slic3r::GUI::GUI_App::set_auto_toolbar_icon_scale(), Slic3r::GUI::GLGizmoScale3D::set_scale(), Slic3r::GUI::GLToolbar::set_scale(), Slic3r::GUI::GCodeViewer::set_scale(), Slic3r::GUI::IMSlider::set_scale(), Slic3r::GUI::NotificationManager::set_scale(), Eigen::SimplicialCholeskyBase< Derived >::setShift(), ImGui::SetWindowFontScale(), ImGui::ShadeVertsLinearUV(), igl::shapeup_regular_face_projection(), Eigen::internal::stable_norm_kernel(), Eigen::MatrixBase< Derived >::stableNorm(), triangulate_face(), Clipper2Lib::TrimCollinear(), Slic3r::GUI::GizmoObjectManipulation::update_reset_buttons_visibility(), ImGui::UpdateMouseWheel(), Slic3r::GUI::IMSlider::vertical_slider(), Slic3r::Geometry::Transformation::volume_to_bed_transformation(), Slic3r::png::write_gray_to_file_scaled(), Slic3r::png::write_gray_to_file_scaled(), Slic3r::png::write_gray_to_file_scaled(), Slic3r::png::write_rgb_or_gray_to_file_scaled(), Slic3r::png::write_rgb_to_file_scaled(), Slic3r::png::write_rgb_to_file_scaled(), Slic3r::png::write_rgb_to_file_scaled(), and Slic3r::GUI::wxImage_to_wxBitmap_with_alpha().
to_radians()
static float to_radians (float degree) static
{
    return degree / 180.f * M_PI;
}
References M_PI.
Referenced by calc_triangle_3rd_edge(), and DeltaHS_BBS().
update_ui()
static void update_ui (wxWindow * window) static
{
    Slic3r::GUI::wxGetApp().UpdateDarkUI(window);
}
Referenced by WipingDialog::WipingDialog(), and WipingPanel::WipingPanel().
Variable Documentation
g_flush_volume_to_support
const int g_flush_volume_to_support = 230 static
Referenced by WipingPanel::calc_flushing_volumes().
g_max_flush_multiplier
const float g_max_flush_multiplier = 3.f static
Referenced by WipingPanel::WipingPanel().
g_min_flush_multiplier
const float g_min_flush_multiplier = 0.f static
Referenced by WipingPanel::WipingPanel().
g_min_flush_volume_from_support
const int g_min_flush_volume_from_support = 420.f static
Referenced by WipingPanel::calc_flushing_volumes().
g_text_color
const wxColour g_text_color = wxColour(107, 107, 107, 255) static
Referenced by WipingPanel::WipingPanel(), and WipingPanel::update_warning_texts().
m_max_flush_volume
const int m_max_flush_volume = 750.f static