OrcaSlicer: ProgressBar Class Reference
ProgressBar Class Reference
#include <src/slic3r/GUI/Widgets/ProgressBar.hpp>
Public Member Functions
ProgressBar ()
ProgressBar (wxWindow *parent, wxWindowID id=wxID_ANY, int max=100, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, bool shown=false)
void create (wxWindow *parent, wxWindowID id, const wxPoint &pos, wxSize &size)
~ProgressBar ()
void ShowNumber (bool shown)
void Disable (wxString text)
void SetValue (int step)
void Reset ()
void SetProgress (int step)
void SetRadius (double radius)
void SetProgressForedColour (wxColour colour)
void SetProgressBackgroundColour (wxColour colour)
void Rescale ()
void SetHeight (int height)
virtual void SetMinSize (const wxSize &size) override
Public Attributes
bool m_shownumber = {false}
int m_disable = {false}
int m_max = {100}
int m_step = {0}
int m_miniHeight = {0}
const int miniHeight = {14}
double m_radius = {7}
double m_proportion = {0}
wxColour m_progress_background_colour = {233, 233, 233}
wxColour m_progress_colour = {0, 150, 136}
wxColour m_progress_colour_disable = {255, 111, 0}
wxString m_disable_text
Protected Member Functions
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
Detailed Description
Constructor & Destructor Documentation
ProgressBar() [1/2]
ProgressBar::ProgressBar ()
ProgressBar() [2/2]
ProgressBar::ProgressBar (wxWindow * parent, wxWindowID id = wxID_ANY, int max = 100, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, bool shown = false)
{
    m_shownumber = shown;
    SetBackgroundColour(wxColour(255,255,255));
    if (size.y >= miniHeight) {
        m_miniHeight = size.y;
    } else {
        m_miniHeight = miniHeight;
    }
    m_max = max;
    m_radius = m_miniHeight / 2;
    wxSize temp_size(size.x, m_miniHeight);
    SetFont(Label::Head_12);
    create(parent, id, pos, temp_size);
}
References Label::Head_12, max(), and size.
~ProgressBar()
ProgressBar::~ProgressBar ()
{}
Member Function Documentation
create()
void ProgressBar::create (wxWindow * parent, wxWindowID id, const wxPoint & pos, wxSize & size)
{
    wxWindow::Create(parent, id, pos, size);
    // m_static_info = new wxStaticText(this, wxID_ANY,wxT(""),wxPoint(this->padding, 20), wxSize(GetSize().GetWidth() - this->padding * 3, -1), wxST_ELLIPSIZE_END);
    // m_static_info->Wrap(-1);
   /* wxBoxSizer *m_sizer_body  = new wxBoxSizer(wxHORIZONTAL);
     auto m_progress_bk = new StaticBox(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
     m_progress_bk->SetBackgroundColour(wxColour(238, 130, 238));
     StateColor btn_bg_green(std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed), std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
                             std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
     wxBoxSizer *m_sizer_progress= new wxBoxSizer(wxHORIZONTAL);
     auto m_progress = new wxPanel(m_progress_bk, wxID_ANY, wxDefaultPosition, wxSize(50, -1), wxTAB_TRAVERSAL);
     m_progress->SetBackgroundColour(wxColour(128, 0, 255));
     m_sizer_progress->Add(m_progress, 0, wxEXPAND, 0);
     m_progress_bk->SetSizer(m_sizer_progress);
     m_progress_bk->Layout();
     m_sizer_progress->Fit(m_progress_bk);
     m_sizer_body->Add(m_progress_bk, 1, wxEXPAND, 0);
     this->SetSizer(m_sizer_body);
     this->Layout();*/
}
References size.
Disable()
void ProgressBar::Disable (wxString text)
{
    if (m_disable) return;
    m_disable_text = text;
    m_disable = true;
    Refresh();
}
References m_disable, and m_disable_text.
doRender()
void ProgressBar::doRender (wxDC & dc) protected
{
    if (m_step >= m_max) m_step = m_max;
    wxSize size   = GetSize();
    dc.SetPen(wxPen(m_progress_background_colour, 1));
    dc.SetBrush(wxBrush(m_progress_background_colour));
    if (m_radius == 0) {
        dc.DrawRectangle(0, 0, size.x, size.y);
    } else {
        dc.DrawRoundedRectangle(0, 0, size.x, size.y, m_radius);
    }
    //draw progress
    if (m_disable) {
        m_proportion = float(size.x * float(this->m_step) / float(this->m_max));
        if (m_proportion < m_radius * 2 && m_proportion != 0) { m_proportion = m_radius * 2; }
        dc.SetPen(wxPen(m_progress_colour_disable, 1));
        dc.SetBrush(wxBrush(m_progress_colour_disable));
        if (m_radius == 0) {
            dc.DrawRectangle(0, 0, m_proportion, size.y);
        } else {
            dc.DrawRoundedRectangle(0, 0, m_proportion, size.y, m_radius);
        }
        dc.SetFont(::Label::Head_12);
        auto textSize = dc.GetMultiLineTextExtent(m_disable_text);
        dc.SetTextForeground(wxColour(144, 144, 144));
        auto pt = wxPoint();
        pt.x    = (size.x - textSize.x) / 2;
        pt.y    = (size.y - textSize.y) / 2;
        dc.DrawText(m_disable_text, pt);
    } else {
        m_proportion = float(size.x * float(this->m_step) / float(this->m_max));
        if (m_proportion < m_radius * 2  && m_proportion != 0) { m_proportion = m_radius * 2; }
        dc.SetPen(wxPen(m_progress_colour, 1));
        dc.SetBrush(wxBrush(m_progress_colour));
        if (m_radius == 0) {
            dc.DrawRectangle(0, 0, m_proportion, size.y);
        } else {
            dc.DrawRoundedRectangle(0, 0, m_proportion, size.y, m_radius);
        }
        dc.SetFont(GetFont());
        auto textSize = dc.GetMultiLineTextExtent(wxString("000%"));
        dc.SetTextForeground(wxColour(144, 144, 144));
        auto pt = wxPoint();
        pt.x    = (size.x - textSize.x) / 2;
        pt.y    = (size.y - textSize.y) / 2;
        auto text = wxString("");
        if (m_step < 10) {
            text = wxString::Format("%d", m_step);
        } else {
            text = wxString::Format("%d", m_step);
        }
        if (m_shownumber) {
            dc.DrawText(text + wxString("%"), pt);
        }
    }
}
References Label::Head_12, m_disable, m_disable_text, m_max, m_progress_background_colour, m_progress_colour, m_progress_colour_disable, m_proportion, m_radius, m_shownumber, m_step, and size.
Referenced by render().
DoSetSize()
void ProgressBar::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) protected virtual
{
    wxWindow::DoSetSize(x, y, width, height, sizeFlags);
}
paintEvent()
void ProgressBar::paintEvent (wxPaintEvent & evt) protected
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
render()
void ProgressBar::render (wxDC & dc) protected
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
Rescale()
void ProgressBar::Rescale ()
{
    ;
}
Referenced by Slic3r::GUI::StatusPanel::msw_rescale().
Reset()
void ProgressBar::Reset ()
{
    m_step = 0;
    SetValue(0);
}
References m_step, and SetValue().
SetHeight()
void ProgressBar::SetHeight (int height) inline
{
        m_minHeight = height;
        m_radius    = m_minHeight / 2;
        SetSize(GetSize().x,  height);
    }
References m_radius.
Referenced by Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), and Slic3r::GUI::StatusPanel::msw_rescale().
SetMinSize()
void ProgressBar::SetMinSize (const wxSize & size) override virtual
{
    if (size.y >= miniHeight) {
        m_miniHeight = size.y;
    } else {
        return;
    }
    m_radius = m_miniHeight / 2.4;
    wxWindow::SetMinSize({size.x, m_miniHeight});
    // SetSize(size);
    SetRadius(m_radius);
}
References m_miniHeight, m_radius, miniHeight, SetRadius(), and size.
Referenced by Slic3r::GUI::MachineInfoPanel::MachineInfoPanel().
SetProgress()
void ProgressBar::SetProgress (int step)
{
    m_disable = false;
    if (step < 0) return;
    //if (step == m_step) return;
    m_step = step;
    Refresh();
}
References m_disable, and m_step.
Referenced by SetValue().
SetProgressBackgroundColour()
void ProgressBar::SetProgressBackgroundColour (wxColour colour)
{
    m_progress_colour = colour;
     Refresh();
}
References m_progress_colour.
SetProgressForedColour()
void ProgressBar::SetProgressForedColour (wxColour colour)
{
    m_progress_background_colour = colour;
    Refresh();
}
References m_progress_background_colour.
SetRadius()
void ProgressBar::SetRadius (double radius)
{
    m_radius = radius;
    Refresh();
}
References m_radius.
Referenced by SetMinSize().
SetValue()
void ProgressBar::SetValue (int step)
{
    m_disable = false;
    SetProgress(step);
}
References m_disable, and SetProgress().
Referenced by Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Reset(), Slic3r::GUI::StatusPanel::reset_printing_values(), Slic3r::GUI::PublishDialog::SetPublishStep(), Slic3r::GUI::MachineInfoPanel::update(), Slic3r::GUI::StatusPanel::update_subtask(), and Slic3r::GUI::PublishDialog::UpdateStatus().
ShowNumber()
void ProgressBar::ShowNumber (bool shown)
{
    m_shownumber = shown;
    Refresh();
}
References m_shownumber.
Member Data Documentation
m_disable
int ProgressBar::m_disable = {false}
Referenced by Disable(), doRender(), SetProgress(), and SetValue().
m_disable_text
wxString ProgressBar::m_disable_text
Referenced by Disable(), and doRender().
m_max
int ProgressBar::m_max = {100}
Referenced by doRender().
m_miniHeight
int ProgressBar::m_miniHeight = {0}
Referenced by SetMinSize().
m_progress_background_colour
wxColour ProgressBar::m_progress_background_colour = {233, 233, 233}
Referenced by doRender(), and SetProgressForedColour().
m_progress_colour
wxColour ProgressBar::m_progress_colour = {0, 150, 136}
Referenced by doRender(), and SetProgressBackgroundColour().
m_progress_colour_disable
wxColour ProgressBar::m_progress_colour_disable = {255, 111, 0}
Referenced by doRender().
m_proportion
double ProgressBar::m_proportion = {0}
Referenced by doRender().
m_radius
double ProgressBar::m_radius = {7}
Referenced by doRender(), SetHeight(), SetMinSize(), and SetRadius().
m_shownumber
bool ProgressBar::m_shownumber = {false}
Referenced by doRender(), and ShowNumber().
m_step
int ProgressBar::m_step = {0}
Referenced by doRender(), Reset(), and SetProgress().
miniHeight
const int ProgressBar::miniHeight = {14}
Referenced by SetMinSize().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/ProgressBar.hpp
src/slic3r/GUI/Widgets/ProgressBar.cpp