OrcaSlicer: Slic3r::GUI::GLGizmoSimplify Class Reference
Slic3r::GUI::GLGizmoSimplify Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoSimplify.hpp>
Classes
struct Configuration
struct GuiCfg
class SimplifyCanceledException
struct State
Public Types
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoSimplify (GLCanvas3D &parent, const std::string &icon_filename, unsigned int sprite_id)
virtual ~GLGizmoSimplify ()
bool on_esc_key_down ()
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
int get_group_id () const
void set_group_id (int id)
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
void set_icon_filename (const std::string &filename)
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
virtual bool wants_enter_leave_snapshots () const
virtual std::string get_gizmo_entering_text () const
virtual std::string get_gizmo_leaving_text () const
virtual std::string get_action_snapshot_name ()
void set_common_data_pool (CommonGizmosDataPool *ptr)
virtual bool apply_clipping_plane ()
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
void set_highlight_color (const std::array< float, 4 > &color)
void enable_grabber (unsigned int id)
void disable_grabber (unsigned int id)
void start_dragging ()
void stop_dragging ()
bool is_dragging () const
void update (const UpdateData &data)
bool update_items_state ()
void render ()
void render_for_picking ()
void render_input_window (float x, float y, float bottom_limit)
virtual void on_change_color_mode (bool is_dark)
virtual std::string get_tooltip () const
int get_count ()
std::string get_gizmo_name ()
Static Public Member Functions
static void add_simplify_suggestion_notification (const std::vector< size_t > &object_ids, const std::vector< ModelObject * > &objects, NotificationManager &manager)
static void update_render_colors ()
static void load_render_colors ()
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static float INV_ZOOM = 1.0f
static std::array< float, 4 > DEFAULT_BASE_COLOR = { 0.625f, 0.625f, 0.625f, 1.0f }
static std::array< float, 4 > DEFAULT_DRAG_COLOR = { 1.0f, 1.0f, 1.0f, 1.0f }
static std::array< float, 4 > DEFAULT_HIGHLIGHT_COLOR = { 1.0f, 0.38f, 0.0f, 1.0f }
static std::array< std::array< float, 4 >, 3 > AXES_COLOR
static std::array< std::array< float, 4 >, 3 > AXES_HOVER_COLOR
static std::array< float, 4 > CONSTRAINED_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f }
static std::array< float, 4 > FLATTEN_COLOR = { 0.96f, 0.93f, 0.93f, 0.5f }
static std::array< float, 4 > FLATTEN_HOVER_COLOR = { 1.0f, 1.0f, 1.0f, 0.75f }
static std::array< float, 4 > GRABBER_NORMAL_COL = {1.0f, 1.0f, 1.0f, 1.0f}
static std::array< float, 4 > GRABBER_HOVER_COL = {0.863f, 0.125f, 0.063f, 1.0f}
static std::array< float, 4 > GRABBER_UNIFORM_COL = {0, 1.0, 1.0, 1.0f}
static std::array< float, 4 > GRABBER_UNIFORM_HOVER_COL = {0, 0.7, 0.7, 1.0f}
Protected Member Functions
virtual std::string on_get_name () const override
virtual void on_render_input_window (float x, float y, float bottom_limit) override
virtual bool on_is_activable () const override
virtual bool on_is_selectable () const override
virtual void on_set_state () override
virtual bool on_init () override
virtual void on_render () override
virtual void on_render_for_picking () override
CommonGizmosDataID on_get_requirements () const override
virtual void on_load (cereal::BinaryInputArchive &ar)
virtual void on_save (cereal::BinaryOutputArchive &ar) const
virtual void on_set_hover_id ()
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
virtual void on_start_dragging ()
virtual void on_stop_dragging ()
virtual void on_update (const UpdateData &data)
bool GizmoImguiBegin (const std::string &name, int flags)
void GizmoImguiEnd ()
void GizmoImguiSetNextWIndowPos (float &x, float y, int flag, float pivot_x=0.0f, float pivot_y=0.0f)
std::array< float, 4 > picking_color_component (unsigned int id) const
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers_for_picking (const BoundingBoxf3 &box) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
Protected Attributes
GLCanvas3D & m_parent
int m_group_id
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id
bool m_dragging
std::array< float, 4 > m_base_color
std::array< float, 4 > m_drag_color
std::array< float, 4 > m_highlight_color
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render
std::string m_tooltip
CommonGizmosDataPool * m_c
GLModel m_cone
GLModel m_cylinder
GLModel m_sphere
bool m_is_dark_mode = false
float last_input_window_width = 0
Private Member Functions
void apply_simplify ()
void close ()
void process ()
void stop_worker_thread_request ()
void worker_finished ()
void create_gui_cfg ()
void request_rerender (bool force=false)
void init_model (const indexed_triangle_set &its)
void set_center_position ()
Private Attributes
Configuration m_configuration
bool m_move_to_center
const ModelVolume * m_volume
bool m_show_wireframe
GLModel m_glmodel
size_t m_triangle_count
int64_t m_last_rerender_timestamp = std::numeric_limits<int64_t>::min()
std::thread m_worker
std::mutex m_state_mutex
State m_state
std::optional< GuiCfg > m_gui_cfg
const std::string tr_mesh_name
const std::string tr_triangles
const std::string tr_detail_level
const std::string tr_decimate_ratio
bool m_dirty
int count = 0
Detailed Description
Class Documentation
Slic3r::GUI::GLGizmoSimplify::GuiCfg
struct Slic3r::GUI::GLGizmoSimplify::GuiCfg
Class Members
int bottom_left_width = 100
int input_width = 100
size_t max_char_in_name = 30
duration< long int, milli > prcess_delay = std::chrono::milliseconds(250)
int top_left_width = 100
int window_offset_x = 100
int window_offset_y = 100
int window_padding = 0
Member Enumeration Documentation
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
Constructor & Destructor Documentation
GLGizmoSimplify()
Slic3r::GUI::GLGizmoSimplify::GLGizmoSimplify (GLCanvas3D & parent, const std::string & icon_filename, unsigned int sprite_id)
    : GLGizmoBase(parent, icon_filename, -1)
    , m_volume(nullptr)
    , m_show_wireframe(false)
    , m_move_to_center(false)
    // translation for GUI size
    , tr_mesh_name(_u8L("Mesh name"))
    , tr_triangles(_u8L("Triangles"))
    , tr_detail_level(_u8L("Detail level"))
    , tr_decimate_ratio(_u8L("Decimate ratio"))
{}
~GLGizmoSimplify()
Slic3r::GUI::GLGizmoSimplify::~GLGizmoSimplify () virtual
{
    stop_worker_thread_request();
    if (m_worker.joinable())
        m_worker.join();
    m_glmodel.reset();
}
References m_glmodel, m_worker, Slic3r::GUI::GLModel::reset(), and stop_worker_thread_request().
Member Function Documentation
add_simplify_suggestion_notification()
void Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification (const std::vector< size_t > & object_ids, const std::vector< ModelObject * > & objects, NotificationManager & manager) static
{
    std::vector<size_t> big_ids;
    big_ids.reserve(object_ids.size());
    auto is_big_object = [&objects](size_t object_id) {
        const uint32_t triangles_to_suggest_simplify = 1000000;
        if (object_id >= objects.size()) return false; // out of object index
        ModelVolumePtrs &volumes = objects[object_id]->volumes;
        if (volumes.size() != 1) return false; // not only one volume
        size_t triangle_count = volumes.front()->mesh().its.indices.size();
        if (triangle_count < triangles_to_suggest_simplify)
            return false; // small volume
        return true;
    };
    std::copy_if(object_ids.begin(), object_ids.end(),
                 std::back_inserter(big_ids), is_big_object);
    if (big_ids.empty()) return;
    for (size_t object_id : big_ids) {
        std::string t = GUI::format(_L(
            "Processing model '%1%' with more than 1M triangles "
            "could be slow. It is highly recommended to simplify the model."), objects[object_id]->name);
        std::string hypertext = _u8L("Simplify model");
        std::function<bool(wxEvtHandler *)> open_simplify =
            [object_id](wxEvtHandler *) {
                auto plater = wxGetApp().plater();
                if (object_id >= plater->model().objects.size()) return true;
                Selection &selection = plater->canvas3D()->get_selection();
                selection.clear();
                selection.add_object((unsigned int) object_id);
                auto &manager = plater->get_view3D_canvas3D()->get_gizmos_manager();
                bool  close_notification = true;
                if(!manager.open_gizmo(GLGizmosManager::Simplify))
                    return close_notification;
                GLGizmoSimplify* simplify = dynamic_cast<GLGizmoSimplify*>(manager.get_current());
                if (simplify == nullptr) return close_notification;
                simplify->set_center_position();
                return close_notification;
            };
        manager.push_simplify_suggestion_notification(
            t, objects[object_id]->id(), hypertext, open_simplify);
    }
}
References _L, _u8L, Slic3r::GUI::Selection::add_object(), Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::Selection::clear(), Slic3r::GUI::format(), Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Plater::get_view3D_canvas3D(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::plater(), Slic3r::GUI::NotificationManager::push_simplify_suggestion_notification(), and Slic3r::GUI::GLGizmosManager::Simplify.
Referenced by Slic3r::GUI::Plater::priv::load_files().
apply_clipping_plane()
virtual bool Slic3r::GUI::GLGizmoBase::apply_clipping_plane () inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut.
{ return true; }
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
apply_simplify()
void Slic3r::GUI::GLGizmoSimplify::apply_simplify () private
{
    const Selection& selection = m_parent.get_selection();
    int object_idx = selection.get_object_idx();
    auto plater = wxGetApp().plater();
    plater->take_snapshot(GUI::format("Simplify %1%", m_volume->name));
    plater->clear_before_change_mesh(object_idx);
    ModelVolume* mv = get_model_volume(selection, wxGetApp().model());
    assert(mv == m_volume);
    mv->set_mesh(std::move(*m_state.result));
    m_state.result.reset();
    mv->calculate_convex_hull();
    mv->invalidate_convex_hull_2d();
    mv->set_new_unique_id();
    mv->get_object()->invalidate_bounding_box();
    mv->get_object()->ensure_on_bed();
    // fix hollowing, sla support points, modifiers, ...
    plater->changed_mesh(object_idx);
    // Fix warning icon in object list
    wxGetApp().obj_list()->update_item_error_icon(object_idx, -1);
    close();
}
References Slic3r::ModelVolume::calculate_convex_hull(), Slic3r::GUI::Plater::changed_mesh(), Slic3r::GUI::Plater::clear_before_change_mesh(), close(), Slic3r::ModelObject::ensure_on_bed(), Slic3r::GUI::format(), Slic3r::GUI::get_model_volume(), Slic3r::ModelVolume::get_object(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::ModelObject::invalidate_bounding_box(), Slic3r::ModelVolume::invalidate_convex_hull_2d(), Slic3r::GUI::GLGizmoBase::m_parent, m_state, m_volume, Slic3r::ModelVolume::name, Slic3r::GUI::plater(), Slic3r::GUI::GLGizmoSimplify::State::result, Slic3r::ModelVolume::set_mesh(), Slic3r::ModelVolume::set_new_unique_id(), and Slic3r::GUI::Plater::take_snapshot().
Referenced by on_render_input_window().
close()
void Slic3r::GUI::GLGizmoSimplify::close () private
{
    // close gizmo == open it again
    GLGizmosManager &gizmos_mgr = m_parent.get_gizmos_manager();
    gizmos_mgr.open_gizmo(GLGizmosManager::EType::Simplify);
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmosManager::open_gizmo(), and Slic3r::GUI::GLGizmosManager::Simplify.
Referenced by apply_simplify(), and on_render_input_window().
create_gui_cfg()
void Slic3r::GUI::GLGizmoSimplify::create_gui_cfg () private
{
    if (m_gui_cfg.has_value()) return;
    int space_size = m_imgui->calc_text_size(":MM").x;
    GuiCfg cfg;
    cfg.top_left_width = std::max(m_imgui->calc_text_size(tr_mesh_name).x,
                                  m_imgui->calc_text_size(tr_triangles).x)
        + space_size;
    const float radio_size = ImGui::GetFrameHeight();
    cfg.bottom_left_width =
        std::max(m_imgui->calc_text_size(tr_detail_level).x,
                 m_imgui->calc_text_size(tr_decimate_ratio).x) +
        space_size + radio_size;
    cfg.input_width   = cfg.bottom_left_width * 1.5;
    cfg.window_offset_x = (cfg.bottom_left_width + cfg.input_width)/2;
    cfg.window_offset_y = ImGui::GetTextLineHeightWithSpacing() * 5;
    m_gui_cfg = cfg;
}
References Slic3r::GUI::GLGizmoSimplify::GuiCfg::bottom_left_width, Slic3r::GUI::ImGuiWrapper::calc_text_size(), ImGui::GetFrameHeight(), ImGui::GetTextLineHeightWithSpacing(), Slic3r::GUI::GLGizmoSimplify::GuiCfg::input_width, m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoSimplify::GuiCfg::top_left_width, tr_decimate_ratio, tr_detail_level, tr_mesh_name, tr_triangles, Slic3r::GUI::GLGizmoSimplify::GuiCfg::window_offset_x, Slic3r::GUI::GLGizmoSimplify::GuiCfg::window_offset_y, and ImVec2::x.
Referenced by on_render_input_window().
disable_grabber()
void Slic3r::GUI::GLGizmoBase::disable_grabber (unsigned int id) inherited
{
    if (id < m_grabbers.size())
        m_grabbers[id].enabled = false;
    on_disable_grabber(id);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_disable_grabber().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_disable_grabber().
enable_grabber()
void Slic3r::GUI::GLGizmoBase::enable_grabber (unsigned int id) inherited
{
    if (id < m_grabbers.size())
        m_grabbers[id].enabled = true;
    on_enable_grabber(id);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_enable_grabber().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_enable_grabber().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), and on_render_input_window().
get_action_snapshot_name()
virtual std::string Slic3r::GUI::GLGizmoBase::get_action_snapshot_name () inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{ return "Gizmo action"; }
Referenced by Slic3r::GUI::Plater::priv::take_snapshot().
get_count()
int Slic3r::GUI::GLGizmoBase::get_count () inline inherited
{ return ++count; }
References Slic3r::GUI::GLGizmoBase::count.
get_gizmo_entering_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_entering_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
get_gizmo_leaving_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_leaving_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
get_gizmo_name()
std::string Slic3r::GUI::GLGizmoBase::get_gizmo_name () inline inherited
{ return on_get_name(); }
References Slic3r::GUI::GLGizmoBase::on_get_name().
get_group_id()
int Slic3r::GUI::GLGizmoBase::get_group_id () const inline inherited
{ return m_group_id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), and Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers().
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmoText::gizmo_event().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    int key = get_shortcut_key();
    std::string out = on_get_name();
    if (include_shortcut && key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z)
        out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::on_get_name(), and out.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), and Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_state(), Slic3r::GUI::GLGizmoCut::on_set_state(), Slic3r::GUI::GLGizmoFaceDetector::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), and Slic3r::GUI::GLGizmoSeam::on_set_state().
get_tooltip()
virtual std::string Slic3r::GUI::GLGizmoBase::get_tooltip () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoScale3D.
{ return ""; }
GizmoImguiBegin()
bool Slic3r::GUI::GLGizmoBase::GizmoImguiBegin (const std::string & name, int flags) protected inherited
{
    return m_imgui->begin(name, flags);
}
References Slic3r::GUI::ImGuiWrapper::begin(), and Slic3r::GUI::GLGizmoBase::m_imgui.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
GizmoImguiEnd()
void Slic3r::GUI::GLGizmoBase::GizmoImguiEnd () protected inherited
{
    last_input_window_width = ImGui::GetWindowWidth();
    m_imgui->end();
}
References Slic3r::GUI::ImGuiWrapper::end(), ImGui::GetWindowWidth(), Slic3r::GUI::GLGizmoBase::last_input_window_width, and Slic3r::GUI::GLGizmoBase::m_imgui.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
GizmoImguiSetNextWIndowPos()
void Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos (float & x, float y, int flag, float pivot_x = 0.0f, float pivot_y = 0.0f) protected inherited
{
    if (abs(last_input_window_width) > 0.01f) {
        if (x + last_input_window_width > m_parent.get_canvas_size().get_width()) {
            if (last_input_window_width > m_parent.get_canvas_size().get_width()) {
                x = 0;
            } else {
                x = m_parent.get_canvas_size().get_width() - last_input_window_width;
            }
        }
    }
    m_imgui->set_next_window_pos(x, y, flag, pivot_x, pivot_y);
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLGizmoBase::last_input_window_width, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::GUI::ImGuiWrapper::set_next_window_pos().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
init_model()
void Slic3r::GUI::GLGizmoSimplify::init_model (const indexed_triangle_set & its) private
{
    if (its.indices.empty())
        return;
    m_glmodel.reset();
    m_glmodel.init_from(its);
    m_parent.toggle_model_objects_visibility(true); // selected volume may have changed
    m_parent.toggle_model_objects_visibility(false, m_c->selection_info()->model_object(),
        m_c->selection_info()->get_active_instance(), m_volume);
    if (const Selection&sel = m_parent.get_selection(); sel.get_volume_idxs().size() == 1)
        m_glmodel.set_color(-1, sel.get_volume(*sel.get_volume_idxs().begin())->color);
    m_triangle_count = its.indices.size();
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::GLCanvas3D::get_selection(), indexed_triangle_set::indices, Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLGizmoBase::m_c, m_glmodel, Slic3r::GUI::GLGizmoBase::m_parent, m_triangle_count, m_volume, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLModel::reset(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLModel::set_color(), and Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility().
Referenced by on_render_input_window(), and worker_finished().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
load_render_colors()
void Slic3r::GUI::GLGizmoBase::load_render_colors () static inherited
{
    RenderColor::colors[RenderCol_Grabber_X] = IMColor(GLGizmoBase::AXES_COLOR[0]);
    RenderColor::colors[RenderCol_Grabber_Y] = IMColor(GLGizmoBase::AXES_COLOR[1]);
    RenderColor::colors[RenderCol_Grabber_Z] = IMColor(GLGizmoBase::AXES_COLOR[2]);
    RenderColor::colors[RenderCol_Flatten_Plane] = IMColor(GLGizmoBase::FLATTEN_COLOR);
    RenderColor::colors[RenderCol_Flatten_Plane_Hover] = IMColor(GLGizmoBase::FLATTEN_HOVER_COLOR);
}
References Slic3r::GUI::GLGizmoBase::AXES_COLOR, Slic3r::RenderColor::colors, Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR, Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR, Slic3r::IMColor(), RenderCol_Flatten_Plane, RenderCol_Flatten_Plane_Hover, RenderCol_Grabber_X, RenderCol_Grabber_Y, and RenderCol_Grabber_Z.
Referenced by Slic3r::GUI::GLCanvas3D::init().
on_change_color_mode()
virtual void Slic3r::GUI::GLGizmoBase::on_change_color_mode (bool is_dark) inline virtual inherited
{  m_is_dark_mode = is_dark; }
References Slic3r::GUI::GLGizmoBase::m_is_dark_mode.
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_disable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, and Slic3r::GUI::GLGizmoRotate3D.
{}
Referenced by Slic3r::GUI::GLGizmoBase::disable_grabber().
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_enable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, and Slic3r::GUI::GLGizmoRotate3D.
{}
Referenced by Slic3r::GUI::GLGizmoBase::enable_grabber().
on_esc_key_down()
bool Slic3r::GUI::GLGizmoSimplify::on_esc_key_down ()
{
    return false;
    /*if (!m_is_worker_running)
        return false;
    stop_worker_thread_request();
    return true;*/
}
on_get_name()
std::string Slic3r::GUI::GLGizmoSimplify::on_get_name () const override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    return _u8L("Simplify");
}
References _u8L.
Referenced by on_render_input_window().
on_get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoSimplify::on_get_requirements () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return CommonGizmosDataID(
        int(CommonGizmosDataID::SelectionInfo));
}
References Slic3r::GUI::SelectionInfo.
on_init()
virtual bool Slic3r::GUI::GLGizmoSimplify::on_init () inline override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{ return true;};
on_is_activable()
bool Slic3r::GUI::GLGizmoSimplify::on_is_activable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return m_parent.get_selection().is_single_full_object() ||
        m_parent.get_selection().is_single_volume();
}
References Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_volume(), and Slic3r::GUI::GLGizmoBase::m_parent.
on_is_selectable()
virtual bool Slic3r::GUI::GLGizmoSimplify::on_is_selectable () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return false; }
on_load()
virtual void Slic3r::GUI::GLGizmoBase::on_load (cereal::BinaryInputArchive & ar) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeshBoolean, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::load().
on_render()
void Slic3r::GUI::GLGizmoSimplify::on_render () override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    if (! m_glmodel.is_initialized())
        return;
    const auto& selection   = m_parent.get_selection();
    const auto& volume_idxs = selection.get_volume_idxs();
    if (volume_idxs.empty() || volume_idxs.size() != 1) return;
    const GLVolume *selected_volume = selection.get_volume(*volume_idxs.begin());
    // Check that the GLVolume still belongs to the ModelObject we work on.
    if (m_volume != get_model_volume(selection, wxGetApp().model()))
        return;
    const Transform3d trafo_matrix = selected_volume->world_matrix();
    glsafe(::glPushMatrix());
    glsafe(::glMultMatrixd(trafo_matrix.data()));
    auto *gouraud_shader = wxGetApp().get_shader("gouraud_light");
    glsafe(::glPushAttrib(GL_DEPTH_TEST));
    glsafe(::glEnable(GL_DEPTH_TEST));
    gouraud_shader->start_using();
    m_glmodel.render();
    gouraud_shader->stop_using();
    if (m_show_wireframe) {
        auto* contour_shader = wxGetApp().get_shader("mm_contour");
        contour_shader->start_using();
        glsafe(::glLineWidth(1.0f));
        glsafe(::glPolygonMode(GL_FRONT_AND_BACK, GL_LINE));
        //ScopeGuard offset_fill_guard([]() { glsafe(::glDisable(GL_POLYGON_OFFSET_FILL)); });
        //glsafe(::glEnable(GL_POLYGON_OFFSET_FILL));
        //glsafe(::glPolygonOffset(5.0, 5.0));
        m_glmodel.render();
        glsafe(::glPolygonMode(GL_FRONT_AND_BACK, GL_FILL));
        contour_shader->stop_using();
    }
    glsafe(::glPopAttrib());
    glsafe(::glPopMatrix());
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume_idxs(), glsafe, Slic3r::GUI::GLModel::is_initialized(), m_glmodel, Slic3r::GUI::GLGizmoBase::m_parent, m_show_wireframe, m_volume, Slic3r::GUI::GLModel::render(), and Slic3r::GLVolume::world_matrix().
on_render_for_picking()
virtual void Slic3r::GUI::GLGizmoSimplify::on_render_for_picking () inline override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{};
on_render_input_window()
void Slic3r::GUI::GLGizmoSimplify::on_render_input_window (float x, float y, float bottom_limit) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    create_gui_cfg();
    const Selection &selection = m_parent.get_selection();
    const ModelVolume *act_volume = get_model_volume(selection, wxGetApp().plater()->model());
    if (act_volume == nullptr) {
        stop_worker_thread_request();
        close();
        if (! m_parent.get_selection().is_single_volume()) {
            MessageDialog msg((wxWindow*)wxGetApp().mainframe,
                _L("Simplification is currently only allowed when a single part is selected"),
                _L("Error"));
            msg.ShowModal();
        }
        return;
    }
    bool is_cancelling = false;
    bool is_worker_running = false;
    bool is_result_ready = false;
    int progress = 0;
    {
        std::lock_guard lk(m_state_mutex);
        is_cancelling = m_state.status == State::cancelling;
        is_worker_running = m_state.status == State::running;
        is_result_ready = bool(m_state.result);
        progress = m_state.progress;
    }
    // Whether to trigger calculation after rendering is done.
    bool start_process = false;
    // Check selection of new volume
    // Do not reselect object when processing
    if (act_volume != m_volume) {
        bool change_window_position = (m_volume == nullptr);
        // select different model
        // close suggestion notification
        auto notification_manager = wxGetApp().plater()->get_notification_manager();
        notification_manager->remove_simplify_suggestion_with_id(act_volume->get_object()->id());
        m_volume = act_volume;
        m_configuration.decimate_ratio = 50.; // default value
        m_configuration.fix_count_by_ratio(m_volume->mesh().its.indices.size());
        init_model(m_volume->mesh().its);
        // Start processing. If we switched from another object, process will
        // stop the background thread and it will restart itself later.
        start_process = true;
        // set window position
        if (m_move_to_center && change_window_position) {
            m_move_to_center = false;
            auto parent_size = m_parent.get_canvas_size();
            ImVec2 pos(parent_size.get_width() / 2 - m_gui_cfg->window_offset_x,
                       parent_size.get_height() / 2 - m_gui_cfg->window_offset_y);
            ImGui::SetNextWindowPos(pos, ImGuiCond_Always);
        }else if (change_window_position) {
            ImVec2 pos = ImGui::GetMousePos();
            pos.x -= m_gui_cfg->window_offset_x;
            pos.y -= m_gui_cfg->window_offset_y;
            // minimal top left value
            ImVec2 tl(m_gui_cfg->window_padding, m_gui_cfg->window_padding + m_parent.get_main_toolbar_height());
            if (pos.x < tl.x) pos.x = tl.x;
            if (pos.y < tl.y) pos.y = tl.y;
            // maximal bottom right value
            auto parent_size = m_parent.get_canvas_size();
            ImVec2 br(
                parent_size.get_width() - (2 * m_gui_cfg->window_offset_x + m_gui_cfg->window_padding),
                parent_size.get_height() - (2 * m_gui_cfg->window_offset_y + m_gui_cfg->window_padding));
            if (pos.x > br.x) pos.x = br.x;
            if (pos.y > br.y) pos.y = br.y;
            ImGui::SetNextWindowPos(pos, ImGuiCond_Always);
        }
    }
    float space_size = m_imgui->get_style_scaling() * 8;
    float mesh_size = m_imgui->calc_text_size(_L("Mesh name")).x + m_imgui->scaled(2.0f);
    float triangle_size = m_imgui->calc_text_size(_L("Triangles")).x + m_imgui->scaled(2.0f);
    float text_left_width = std::max(triangle_size,mesh_size);
    float detail_size = m_imgui->calc_text_size(_L("Detail level")).x + m_imgui->scaled(2.0f);
    float decimate_size = m_imgui->calc_text_size(_L("Decimate ratio")).x + m_imgui->scaled(2.0f);
    float circle_size = m_imgui->scaled(2.0f);
    float bottom_left_width = std::max(detail_size, decimate_size) + circle_size;
    float slider_width = m_imgui->scaled(5.0f);
    m_imgui->push_common_window_style(m_parent.get_scale());
    int flag = ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoResize |
               ImGuiWindowFlags_NoCollapse;
    m_imgui->begin(on_get_name(), flag);
    m_imgui->text(tr_mesh_name + ":");
    // BBS: somehow the calculated utf8 width is too narrow, have to add 35 here
    ImGui::SameLine(text_left_width + space_size);
    std::string name = m_volume->name;
    if (name.length() > m_gui_cfg->max_char_in_name)
        name = name.substr(0, m_gui_cfg->max_char_in_name - 3) + "...";
    m_imgui->text_colored(ImVec4(0.42f, 0.42f, 0.42f, 1.00f), name);
    m_imgui->text(tr_triangles + ":");
    ImGui::SameLine(text_left_width + space_size);
    size_t orig_triangle_count = m_volume->mesh().its.indices.size();
    m_imgui->text_colored(ImVec4(0.42f, 0.42f, 0.42f, 1.00f), std::to_string(orig_triangle_count));
    ImGui::Separator();
    if (m_imgui->bbl_radio_button("##use_error", !m_configuration.use_count)) {
        m_configuration.use_count = !m_configuration.use_count;
        start_process = true;
    }
    ImGui::SameLine();
    m_imgui->disabled_begin(m_configuration.use_count);
    ImGui::Text("%s", tr_detail_level.c_str());
    std::vector<std::string> reduce_captions = {
        static_cast<std::string>(_u8L("Extra high")),
        static_cast<std::string>(_u8L("High")),
        static_cast<std::string>(_u8L("Medium")),
        static_cast<std::string>(_u8L("Low")),
        static_cast<std::string>(_u8L("Extra low"))
    };
    ImGui::SameLine(bottom_left_width);
    ImGui::PushItemWidth(bottom_left_width - space_size);
    static int reduction = 2;
    ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(0.81f, 0.81f, 0.81f, 1.00f));
    ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, ImVec4(0.81f, 0.81f, 0.81f, 1.00f));
    ImGui::PushStyleColor(ImGuiCol_FrameBgActive, ImVec4(0.81f, 0.81f, 0.81f, 1.00f));
    ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(0.00f, 0.68f, 0.26f, 1.00f));
    ImGui::PushStyleColor(ImGuiCol_SliderGrab, ImVec4(0.00f, 0.68f, 0.26f, 1.00f));
    if (m_imgui->bbl_sliderin("##ReductionLevel", &reduction, 0, 4, reduce_captions[reduction].c_str())) {
        if (reduction < 0) reduction = 0;
        if (reduction > 4) reduction = 4;
        switch (reduction) {
        case 0: m_configuration.max_error = 1e-3f; break;
        case 1: m_configuration.max_error = 1e-2f; break;
        case 2: m_configuration.max_error = 0.1f; break;
        case 3: m_configuration.max_error = 0.5f; break;
        case 4: m_configuration.max_error = 1.f; break;
        }
        start_process = true;
    }
    ImGui::PopStyleColor(5);
    m_imgui->disabled_end(); // !use_count
    if (m_imgui->bbl_radio_button("##use_count", m_configuration.use_count)) {
        m_configuration.use_count = !m_configuration.use_count;
        start_process = true;
    }
    ImGui::SameLine();
    // show preview result triangle count (percent)
    if (!m_configuration.use_count) {
        m_configuration.wanted_count = static_cast<uint32_t>(m_triangle_count);
        m_configuration.decimate_ratio =
            (1.0f - (m_configuration.wanted_count / (float) orig_triangle_count)) * 100.f;
    }
    m_imgui->disabled_begin(!m_configuration.use_count);
    ImGui::Text("%s", tr_decimate_ratio.c_str());
    ImGui::SameLine(bottom_left_width);
    const char * format = (m_configuration.decimate_ratio > 10)? "%.0f %%":
        ((m_configuration.decimate_ratio > 1)? "%.1f %%":"%.2f %%");
    ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 0.0);
    ImGui::PushItemWidth(slider_width + space_size);
    if (m_imgui->bbl_slider_float_style("##decimate_ratio", &m_configuration.decimate_ratio, 0.f, 100.f, format)) {
        if (m_configuration.decimate_ratio < 0.f)
            m_configuration.decimate_ratio = 0.01f;
        if (m_configuration.decimate_ratio > 100.f)
            m_configuration.decimate_ratio = 100.f;
        m_configuration.fix_count_by_ratio(orig_triangle_count);
        start_process = true;
    }
    ImGui::SameLine();
    ImGui::PopStyleVar(1);
    ImGui::PushItemWidth(ImGui::CalcTextSize("100.00%").x + space_size);
    ImGui::BBLDragFloat("##decimate_ratio_input", &m_configuration.decimate_ratio, 0.05f, 0.0f, 0.0f, "%.2f%%");
    ImGui::NewLine();
    ImGui::SameLine(bottom_left_width + space_size);
    ImGui::Text(_u8L("%d triangles").c_str(), m_configuration.wanted_count);
    m_imgui->disabled_end(); // use_count
    m_imgui->bbl_checkbox(_L("Show wireframe").c_str(), m_show_wireframe);
     // draw progress bar
    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding,12);
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding,ImVec2(0,0));
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing,ImVec2(10,20));
    if (is_worker_running) { // apply or preview
        // draw progress bar
        std::string progress_text = GUI::format(_L("%1%"), std::to_string(progress)) + "%%";
        ImVec2 progress_size(bottom_left_width - space_size, 0.0f);
        ImGui::BBLProgressBar2(progress / 100., progress_size);
        ImGui::SameLine();
        ImGui::AlignTextToFramePadding();
        ImGui::TextColored(ImVec4(0.42f, 0.42f, 0.42f, 1.00f), progress_text.c_str());
        ImGui::SameLine(bottom_left_width + slider_width +  m_imgui->scaled(1.0f));
    } else {
        ImGui::Dummy(ImVec2(bottom_left_width - space_size, -1));
        ImGui::SameLine(bottom_left_width + slider_width +  m_imgui->scaled(1.0f));
    }
    ImGui::PopStyleVar(3);
    ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding,12);
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding,ImVec2(10,3));
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing,ImVec2(10,0));
    ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(0.15f, 0.18f, 0.19f, 1.00f));
    m_imgui->disabled_begin(is_worker_running || ! is_result_ready);
    m_imgui->push_confirm_button_style();
    if (m_imgui->bbl_button(_L("Apply"))) {
        apply_simplify();
    }
    else if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled) && is_worker_running) {
        ImGui::SetTooltip("%s", _u8L("Can't apply when proccess preview.").c_str());
    }
    m_imgui->pop_confirm_button_style();
    m_imgui->disabled_end(); // state !settings
    ImGui::SameLine();
    m_imgui->disabled_begin(is_cancelling);
    m_imgui->push_cancel_button_style();
    if (m_imgui->bbl_button(_L("Cancel"))) {
        close();
    }
    else if (ImGui::IsItemHovered(ImGuiHoveredFlags_AllowWhenDisabled) && is_cancelling)
        ImGui::SetTooltip("%s", _u8L("Operation already cancelling. Please wait few seconds.").c_str());
    m_imgui->pop_cancel_button_style();
    m_imgui->disabled_end(); // state cancelling
    ImGui::PopStyleVar(3);
    ImGui::PopStyleColor(1);
    m_imgui->end();
    m_imgui->pop_common_window_style();
    if (start_process)
        process();
}
References _L, _u8L, ImGui::AlignTextToFramePadding(), apply_simplify(), Slic3r::GUI::ImGuiWrapper::bbl_button(), Slic3r::GUI::ImGuiWrapper::bbl_checkbox(), Slic3r::GUI::ImGuiWrapper::bbl_radio_button(), Slic3r::GUI::ImGuiWrapper::bbl_slider_float_style(), Slic3r::GUI::ImGuiWrapper::bbl_sliderin(), ImGui::BBLDragFloat(), ImGui::BBLProgressBar2(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), ImGui::CalcTextSize(), Slic3r::GUI::GLGizmoSimplify::State::cancelling, close(), create_gui_cfg(), Slic3r::GUI::GLGizmoSimplify::Configuration::decimate_ratio, Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), ImGui::Dummy(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLGizmoSimplify::Configuration::fix_count_by_ratio(), Slic3r::GUI::format(), Slic3r::GUI::GLGizmoBase::format(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::GLCanvas3D::get_main_toolbar_height(), Slic3r::GUI::get_model_volume(), Slic3r::ModelVolume::get_object(), Slic3r::GUI::GLCanvas3D::get_scale(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::ImGuiWrapper::get_style_scaling(), ImGui::GetMousePos(), Slic3r::ObjectBase::id(), ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_SliderGrab, ImGuiCol_Text, ImGuiCond_Always, ImGuiHoveredFlags_AllowWhenDisabled, ImGuiStyleVar_FrameBorderSize, ImGuiStyleVar_FramePadding, ImGuiStyleVar_FrameRounding, ImGuiStyleVar_ItemSpacing, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoResize, indexed_triangle_set::indices, init_model(), Slic3r::GUI::Selection::is_single_volume(), ImGui::IsItemHovered(), Slic3r::TriangleMesh::its, m_configuration, m_gui_cfg, Slic3r::GUI::GLGizmoBase::m_imgui, m_move_to_center, Slic3r::GUI::GLGizmoBase::m_parent, m_show_wireframe, m_state, m_state_mutex, m_triangle_count, m_volume, Slic3r::GUI::GLGizmoSimplify::Configuration::max_error, Slic3r::ModelVolume::mesh(), Slic3r::ModelVolume::name, ImGui::NewLine(), on_get_name(), Slic3r::GUI::plater(), Slic3r::GUI::ImGuiWrapper::pop_cancel_button_style(), Slic3r::GUI::ImGuiWrapper::pop_common_window_style(), Slic3r::GUI::ImGuiWrapper::pop_confirm_button_style(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), process(), Slic3r::GUI::GLGizmoSimplify::State::progress, Slic3r::GUI::ImGuiWrapper::push_cancel_button_style(), Slic3r::GUI::ImGuiWrapper::push_common_window_style(), Slic3r::GUI::ImGuiWrapper::push_confirm_button_style(), ImGui::PushItemWidth(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), Slic3r::GUI::GLGizmoSimplify::State::result, Slic3r::GUI::GLGizmoSimplify::State::running, ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::scaled(), ImGui::Separator(), ImGui::SetNextWindowPos(), ImGui::SetTooltip(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::GUI::GLGizmoSimplify::State::status, stop_worker_thread_request(), ImGui::Text(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), ImGui::TextColored(), tr_decimate_ratio, tr_detail_level, tr_mesh_name, tr_triangles, Slic3r::GUI::GLGizmoSimplify::Configuration::use_count, Slic3r::GUI::GLGizmoSimplify::Configuration::wanted_count, ImVec2::x, and ImVec2::y.
on_save()
virtual void Slic3r::GUI::GLGizmoBase::on_save (cereal::BinaryOutputArchive & ar) const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeshBoolean, Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::save().
on_set_hover_id()
virtual void Slic3r::GUI::GLGizmoBase::on_set_hover_id () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::set_hover_id().
on_set_state()
void Slic3r::GUI::GLGizmoSimplify::on_set_state () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    // Closing gizmo. e.g. selecting another one
    if (GLGizmoBase::m_state == GLGizmoBase::Off) {
        m_parent.toggle_model_objects_visibility(true);
        stop_worker_thread_request();
        m_volume = nullptr; // invalidate selected model
        m_glmodel.reset();
    } else if (GLGizmoBase::m_state == GLGizmoBase::On) {
        // when open by hyperlink it needs to show up
        request_rerender();
    }
}
References m_glmodel, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::m_state, m_volume, Slic3r::GUI::GLGizmoBase::Off, Slic3r::GUI::GLGizmoBase::On, request_rerender(), Slic3r::GUI::GLModel::reset(), stop_worker_thread_request(), and Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility().
on_start_dragging()
virtual void Slic3r::GUI::GLGizmoBase::on_start_dragging () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::start_dragging().
on_stop_dragging()
virtual void Slic3r::GUI::GLGizmoBase::on_stop_dragging () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::stop_dragging().
on_update()
virtual void Slic3r::GUI::GLGizmoBase::on_update (const UpdateData & data) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, Slic3r::GUI::GLGizmoSlaSupports, and Slic3r::GUI::GLGizmoText.
{}
Referenced by Slic3r::GUI::GLGizmoBase::update().
picking_color_component()
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::picking_color_component (unsigned int id) const protected inherited
{
    static const float INV_255 = 1.0f / 255.0f;
    id = BASE_ID - id;
    if (m_group_id > -1)
        id -= m_group_id;
    // color components are encoded to match the calculation of volume_id made into GLCanvas3D::_picking_pass()
    return std::array<float, 4> {
    float((id >> 0) & 0xff) * INV_255, // red
    float((id >> 8) & 0xff) * INV_255, // green
    float((id >> 16) & 0xff) * INV_255, // blue
    float(picking_checksum_alpha_channel(id & 0xff, (id >> 8) & 0xff, (id >> 16) & 0xff))* INV_255 // checksum for validating against unwanted alpha blending and multi sampling
  };
}
References Slic3r::GUI::GLGizmoBase::BASE_ID, Slic3r::GUI::GLGizmoBase::m_group_id, and Slic3r::GUI::picking_checksum_alpha_channel().
Referenced by Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking(), Slic3r::GUI::GLGizmoHollow::render_points(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
process()
void Slic3r::GUI::GLGizmoSimplify::process () private
{
    if (m_volume == nullptr || m_volume->mesh().its.indices.empty())
        return;
    bool configs_match = false;
    bool result_valid  = false;
    bool is_worker_running = false;
    {
        std::lock_guard lk(m_state_mutex);
        configs_match = (m_volume == m_state.mv && m_state.config == m_configuration);
        result_valid = bool(m_state.result);
        is_worker_running = m_state.status == State::running;
    }
    if ((result_valid || is_worker_running) && configs_match) {
        // Either finished or waiting for result already. Nothing to do.
        return;
    }
    if (is_worker_running && ! configs_match) {
        // Worker is running with outdated config. Stop it. It will
        // restart itself when cancellation is done.
        stop_worker_thread_request();
        return;
    }
    if (m_worker.joinable()) {
        // This can happen when process() is called after previous worker terminated,
        // but before the worker_finished callback was called. In this case, just join the thread,
        // the callback will check this and do nothing.
        m_worker.join();
    }
    // Copy configuration that will be used.
    m_state.config = m_configuration;
    m_state.mv = m_volume;
    m_state.status = State::running;
    // Create a copy of current mesh to pass to the worker thread.
    // Using unique_ptr instead of pass-by-value to avoid an extra
    // copy (which would happen when passing to std::thread).
    auto its = std::make_unique<indexed_triangle_set>(m_volume->mesh().its);
    m_worker = std::thread([this](std::unique_ptr<indexed_triangle_set> its) {
        // Checks that the UI thread did not request cancellation, throws if so.
        std::function<void(void)> throw_on_cancel = [this]() {
            std::lock_guard lk(m_state_mutex);
            if (m_state.status == State::cancelling)
                throw SimplifyCanceledException();
        };
        // Called by worker thread, updates progress bar.
        // Using CallAfter so the rerequest function is run in UI thread.
        std::function<void(int)> statusfn = [this](int percent) {
            std::lock_guard lk(m_state_mutex);
            m_state.progress = percent;
            call_after_if_active([this]() { request_rerender(); });
        };
        // Initialize.
        uint32_t triangle_count = 0;
        float    max_error = std::numeric_limits<float>::max();
        {
            std::lock_guard lk(m_state_mutex);
            if (m_state.config.use_count)
                triangle_count = m_state.config.wanted_count;
            if (! m_state.config.use_count)
                max_error = m_state.config.max_error;
            m_state.progress = 0;
            m_state.result.reset();
            m_state.status = State::Status::running;
        }
        // Start the actual calculation.
        try {
            its_quadric_edge_collapse(*its, triangle_count, &max_error, throw_on_cancel, statusfn);
        } catch (SimplifyCanceledException &) {
            std::lock_guard lk(m_state_mutex);
            m_state.status = State::idle;
        }
        std::lock_guard lk(m_state_mutex);
        if (m_state.status == State::Status::running) {
            // We were not cancelled, the result is valid.
            m_state.status = State::Status::idle;
            m_state.result = std::move(its);
        }
        // Update UI. Use CallAfter so the function is run on UI thread.
        call_after_if_active([this]() { worker_finished(); });
    }, std::move(its));
}
References Slic3r::GUI::call_after_if_active(), Slic3r::GUI::GLGizmoSimplify::State::cancelling, Slic3r::GUI::GLGizmoSimplify::State::config, Slic3r::GUI::GLGizmoSimplify::State::idle, indexed_triangle_set::indices, Slic3r::TriangleMesh::its, Slic3r::its_quadric_edge_collapse(), m_configuration, m_state, m_state_mutex, m_volume, m_worker, Slic3r::GUI::GLGizmoSimplify::Configuration::max_error, Slic3r::ModelVolume::mesh(), Slic3r::GUI::GLGizmoSimplify::State::mv, Slic3r::GUI::GLGizmoSimplify::State::progress, request_rerender(), Slic3r::GUI::GLGizmoSimplify::State::result, Slic3r::GUI::GLGizmoSimplify::State::running, Slic3r::GUI::GLGizmoSimplify::State::status, stop_worker_thread_request(), Slic3r::GUI::GLGizmoSimplify::Configuration::use_count, void(), Slic3r::GUI::GLGizmoSimplify::Configuration::wanted_count, and worker_finished().
Referenced by on_render_input_window(), and worker_finished().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ m_tooltip.clear(); on_render(); }
References Slic3r::GUI::GLGizmoBase::m_tooltip, and Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render(), and Slic3r::GUI::GLGizmoBase::Grabber::render_for_picking().
render_for_picking()
void Slic3r::GUI::GLGizmoBase::render_for_picking () inline inherited
{ on_render_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_render_for_picking().
render_grabbers() [1/2]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
#if ENABLE_FIXED_GRABBER
    render_grabbers((float)(GLGizmoBase::Grabber::FixedGrabberSize));
#else
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
#endif
}
References Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/2]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    for (int i = 0; i < (int)m_grabbers.size(); ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(m_hover_id == i, size);
    }
    shader->stop_using();
}
References int, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), size, Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking (const BoundingBoxf3 & box) const protected inherited
{
#if ENABLE_FIXED_GRABBER
    float mean_size = (float)(GLGizmoBase::Grabber::FixedGrabberSize);
#else
    float mean_size = (float)((box.size().x() + box.size().y() + box.size().z()) / 3.0);
#endif
    for (unsigned int i = 0; i < (unsigned int)m_grabbers.size(); ++i) {
        if (m_grabbers[i].enabled) {
            std::array<float, 4> color = picking_color_component(i);
            m_grabbers[i].color = color;
            m_grabbers[i].render_for_picking(mean_size);
        }
    }
}
References Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, int, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::picking_color_component(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), and Slic3r::GUI::GLGizmoScale3D::on_render_for_picking().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // for some reason, the imgui dialogs are not shown on screen in the 1st frame where they are rendered, but show up only with the 2nd rendered frame
        // so, we forces another frame rendering the first time the imgui window is shown
        m_parent.set_as_dirty();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
request_rerender()
void Slic3r::GUI::GLGizmoSimplify::request_rerender (bool force = false) private
{
    int64_t now = m_parent.timestamp_now();
    if (force || now > m_last_rerender_timestamp + 250) { // 250 ms
        set_dirty();
        m_parent.schedule_extra_frame(0);
        m_last_rerender_timestamp = now;
    }
}
References m_last_rerender_timestamp, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLCanvas3D::schedule_extra_frame(), Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLCanvas3D::timestamp_now().
Referenced by on_set_state(), process(), and worker_finished().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
set_center_position()
void Slic3r::GUI::GLGizmoSimplify::set_center_position () private
{
    m_move_to_center = true;
}
References m_move_to_center.
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c, and ptr.
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::process_cut_line(), and request_rerender().
set_group_id()
void Slic3r::GUI::GLGizmoBase::set_group_id (int id) inline inherited
{ m_group_id = id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::GLGizmoAdvancedCut().
set_highlight_color()
void Slic3r::GUI::GLGizmoBase::set_highlight_color (const std::array< float, 4 > & color) inherited
{
    m_highlight_color = color;
}
References Slic3r::GUI::GLGizmoBase::m_highlight_color.
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    if (m_grabbers.empty() || (id < (int)m_grabbers.size()))
    {
        m_hover_id = id;
        on_set_hover_id();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_icon_filename()
void Slic3r::GUI::GLGizmoBase::set_icon_filename (const std::string & filename) inherited
{
    m_icon_filename = filename;
}
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
start_dragging()
void Slic3r::GUI::GLGizmoBase::start_dragging () inherited
{
    m_dragging = true;
    for (int i = 0; i < (int)m_grabbers.size(); ++i)
    {
        m_grabbers[i].dragging = (m_hover_id == i);
    }
    on_start_dragging();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("this %1%, m_hover_id=%2%\n")%this %m_hover_id;
}
References int, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_start_dragging().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), and Slic3r::GUI::GLGizmoText::gizmo_event().
stop_dragging()
void Slic3r::GUI::GLGizmoBase::stop_dragging () inherited
{
    m_dragging = false;
    for (int i = 0; i < (int)m_grabbers.size(); ++i)
    {
        m_grabbers[i].dragging = false;
    }
    on_stop_dragging();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("this %1%, m_hover_id=%2%\n")%this %m_hover_id;
}
References int, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_stop_dragging().
stop_worker_thread_request()
void Slic3r::GUI::GLGizmoSimplify::stop_worker_thread_request () private
{
    std::lock_guard lk(m_state_mutex);
    if (m_state.status == State::running)
        m_state.status = State::Status::cancelling;
}
References Slic3r::GUI::GLGizmoSimplify::State::cancelling, m_state, m_state_mutex, Slic3r::GUI::GLGizmoSimplify::State::running, and Slic3r::GUI::GLGizmoSimplify::State::status.
Referenced by ~GLGizmoSimplify(), on_render_input_window(), on_set_state(), and process().
update()
void Slic3r::GUI::GLGizmoBase::update (const UpdateData & data) inherited
{
    if (m_hover_id != -1)
        on_update(data);
}
References Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_update().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
};
References Slic3r::GUI::GLGizmoBase::m_dirty.
update_render_colors()
void Slic3r::GUI::GLGizmoBase::update_render_colors () static inherited
{
    GLGizmoBase::AXES_COLOR = { {
                                GLColor(RenderColor::colors[RenderCol_Grabber_X]),
                                GLColor(RenderColor::colors[RenderCol_Grabber_Y]),
                                GLColor(RenderColor::colors[RenderCol_Grabber_Z])
                                } };
    GLGizmoBase::FLATTEN_COLOR = GLColor(RenderColor::colors[RenderCol_Flatten_Plane]);
    GLGizmoBase::FLATTEN_HOVER_COLOR = GLColor(RenderColor::colors[RenderCol_Flatten_Plane_Hover]);
}
References Slic3r::GUI::GLGizmoBase::AXES_COLOR, Slic3r::RenderColor::colors, Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR, Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR, Slic3r::GLColor(), RenderCol_Flatten_Plane, RenderCol_Flatten_Plane_Hover, RenderCol_Grabber_X, RenderCol_Grabber_Y, and RenderCol_Grabber_Z.
Referenced by Slic3r::GUI::GLCanvas3D::_render_style_editor().
wants_enter_leave_snapshots()
virtual bool Slic3r::GUI::GLGizmoBase::wants_enter_leave_snapshots () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
worker_finished()
void Slic3r::GUI::GLGizmoSimplify::worker_finished () private
{
    {
        std::lock_guard lk(m_state_mutex);
        if (m_state.status == State::running) {
            // Someone started the worker again, before this callback
            // was called. Do nothing.
            return;
        }
    }
    if (m_worker.joinable())
        m_worker.join();
    if (GLGizmoBase::m_state == Off)
        return;
    if (m_state.result)
        init_model(*m_state.result);
    if (m_state.config != m_configuration || m_state.mv != m_volume) {
        // Settings were changed, restart the worker immediately.
        process();
    }
    request_rerender(true);
}
References Slic3r::GUI::GLGizmoSimplify::State::config, init_model(), m_configuration, Slic3r::GUI::GLGizmoBase::m_state, m_state, m_state_mutex, m_volume, m_worker, Slic3r::GUI::GLGizmoSimplify::State::mv, Slic3r::GUI::GLGizmoBase::Off, process(), request_rerender(), Slic3r::GUI::GLGizmoSimplify::State::result, Slic3r::GUI::GLGizmoSimplify::State::running, and Slic3r::GUI::GLGizmoSimplify::State::status.
Referenced by process().
Member Data Documentation
AXES_COLOR
std::array< std::array< float, 4 >, 3 > Slic3r::GUI::GLGizmoBase::AXES_COLOR static inherited
Initial value:
= { {
                                                                { 1.0, 0.0f, 0.0f, 1.0f },
                                                                { 0.0f, 1.0f, 0.0f, 1.0f },
                                                                { 0.0f, 0.0f, 1.0f, 1.0f }
                                                                }}
Referenced by Slic3r::GUI::get_color(), Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
AXES_HOVER_COLOR
std::array< std::array< float, 4 >, 3 > Slic3r::GUI::GLGizmoBase::AXES_HOVER_COLOR static inherited
Initial value:
= {{
                                                                { 0.7f, 0.0f, 0.0f, 1.0f },
                                                                { 0.0f, 0.7f, 0.0f, 1.0f },
                                                                { 0.0f, 0.0f, 0.7f, 1.0f }
                                                                }}
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), and Slic3r::GUI::GLGizmoRotate::render_grabber().
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::GLGizmoBase::picking_color_component().
CONSTRAINED_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::CONSTRAINED_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f } static inherited
count
int Slic3r::GUI::GLGizmoBase::count = 0 private inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_count().
DEFAULT_BASE_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_BASE_COLOR = { 0.625f, 0.625f, 0.625f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
DEFAULT_DRAG_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_DRAG_COLOR = { 1.0f, 1.0f, 1.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
DEFAULT_HIGHLIGHT_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_HIGHLIGHT_COLOR = { 1.0f, 0.38f, 0.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
FLATTEN_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR = { 0.96f, 0.93f, 0.93f, 0.5f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoFlatten::on_render(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
FLATTEN_HOVER_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR = { 1.0f, 1.0f, 1.0f, 0.75f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoFlatten::on_render(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
GRABBER_HOVER_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_HOVER_COL = {0.863f, 0.125f, 0.063f, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::Grabber().
GRABBER_NORMAL_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_NORMAL_COL = {1.0f, 1.0f, 1.0f, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::Grabber().
GRABBER_UNIFORM_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_UNIFORM_COL = {0, 1.0, 1.0, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
GRABBER_UNIFORM_HOVER_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_UNIFORM_HOVER_COL = {0, 0.7, 0.7, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
INV_ZOOM
float Slic3r::GUI::GLGizmoBase::INV_ZOOM = 1.0f static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_render_current_gizmo(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoBase::Grabber::render(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), and Slic3r::GUI::GLGizmoRotate::render_grabber_extension().
last_input_window_width
float Slic3r::GUI::GLGizmoBase::last_input_window_width = 0 protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), and Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos().
m_base_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_base_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c protected inherited
Referenced by Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::GLGizmoAdvancedCut::check_conflict_for_all_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::delete_selected_connectors(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoHollow::hollow_mesh(), Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoText::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoAdvancedCut::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::GUI::GLGizmoMeshBoolean::on_load(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), Slic3r::GUI::GLGizmoSeam::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), Slic3r::GUI::GLGizmoHollow::on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::GLGizmoFaceDetector::perform_recognition(), Slic3r::GUI::GLGizmoAdvancedCut::process_cut_line(), Slic3r::GUI::GLGizmoAdvancedCut::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLGizmoAdvancedCut::render_clipper_cut(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoAdvancedCut::reset_connectors(), Slic3r::GUI::GLGizmoSlaSupports::reslice_SLA_supports(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoAdvancedCut::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoAdvancedCut::update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoText::update_raycast_cache(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), and Slic3r::GUI::GLGizmoText::update_text_positions().
m_cone
GLModel Slic3r::GUI::GLGizmoBase::m_cone protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_configuration
Configuration Slic3r::GUI::GLGizmoSimplify::m_configuration private
Referenced by on_render_input_window(), process(), and worker_finished().
m_cylinder
GLModel Slic3r::GUI::GLGizmoBase::m_cylinder protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_drag_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_drag_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::on_render(), and Slic3r::GUI::GLGizmoRotate::render_grabber().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::stop_dragging().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_glmodel
GLModel Slic3r::GUI::GLGizmoSimplify::m_glmodel private
Referenced by ~GLGizmoSimplify(), init_model(), on_render(), and on_set_state().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::disable_grabber(), Slic3r::GUI::GLGizmoBase::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoText::on_init(), Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::stop_dragging().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_group_id(), Slic3r::GUI::GLGizmoBase::picking_color_component(), and Slic3r::GUI::GLGizmoBase::set_group_id().
m_gui_cfg
std::optional<GuiCfg> Slic3r::GUI::GLGizmoSimplify::m_gui_cfg private
Referenced by create_gui_cfg(), and on_render_input_window().
m_highlight_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_highlight_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::set_highlight_color().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id protected inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::calc_ratio(), Slic3r::GUI::GLGizmoScale3D::do_scale_along_axis(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoAdvancedCut::is_selection_changed(), Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoCut::on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_stop_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), Slic3r::GUI::GLGizmoCut::on_update(), Slic3r::GUI::GLGizmoHollow::on_update(), Slic3r::GUI::GLGizmoMove3D::on_update(), Slic3r::GUI::GLGizmoScale3D::on_update(), Slic3r::GUI::GLGizmoSlaSupports::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::update().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename(), and Slic3r::GUI::GLGizmoBase::set_icon_filename().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), create_gui_cfg(), Slic3r::GUI::GLGizmoBase::GizmoImguiBegin(), Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), Slic3r::GUI::GLGizmoText::on_init(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoMove3D::on_render_input_window(), Slic3r::GUI::GLGizmoScale3D::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_combo(), Slic3r::GUI::GLGizmoAdvancedCut::render_connect_type_radio_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_input_window_warning(), Slic3r::GUI::GLGizmoAdvancedCut::render_reset_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::update_font_texture().
m_is_dark_mode
bool Slic3r::GUI::GLGizmoBase::m_is_dark_mode = false protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::on_change_color_mode(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoText::push_button_style(), and Slic3r::GUI::GLGizmoText::push_combo_style().
m_last_rerender_timestamp
int64_t Slic3r::GUI::GLGizmoSimplify::m_last_rerender_timestamp = std::numeric_limits<int64_t>::min() private
Referenced by request_rerender().
m_move_to_center
bool Slic3r::GUI::GLGizmoSimplify::m_move_to_center private
Referenced by on_render_input_window(), and set_center_position().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::add_connector(), apply_simplify(), Slic3r::GUI::GLGizmoAdvancedCut::bounding_box(), Slic3r::GUI::GLGizmoCut::bounding_box(), Slic3r::GUI::GLGizmoPainterBase::bounding_box(), Slic3r::GUI::GLGizmoText::bounding_box(), close(), Slic3r::GUI::GLGizmoAdvancedCut::delete_selected_connectors(), Slic3r::GUI::GLGizmoText::delete_temp_preview_text_volume(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoAdvancedCut::get_plane_points_world_coord(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoText::get_text_mesh(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), init_model(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::GUI::GLGizmoAdvancedCut::on_is_activable(), Slic3r::GUI::GLGizmoCut::on_is_activable(), Slic3r::GUI::GLGizmoFaceDetector::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeshBoolean::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoText::on_is_activable(), Slic3r::GUI::GLGizmoAdvancedCut::on_load(), Slic3r::GUI::GLGizmoFdmSupports::on_opening(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoHollow::on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_render_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoText::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), request_rerender(), Slic3r::GUI::GLGizmoAdvancedCut::reset_cut_plane(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut::update_contours(), Slic3r::GUI::GLGizmoPainterBase::update_contours(), Slic3r::GUI::GLGizmoText::update_font_texture(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), and Slic3r::GUI::GLGizmoText::update_text_positions().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoAdvancedCut::on_init(), Slic3r::GUI::GLGizmoCut::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), Slic3r::GUI::GLGizmoHollow::on_init(), Slic3r::GUI::GLGizmoMeshBoolean::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), Slic3r::GUI::GLGizmoSlaSupports::on_init(), and Slic3r::GUI::GLGizmoText::on_init().
m_show_wireframe
bool Slic3r::GUI::GLGizmoSimplify::m_show_wireframe private
Referenced by on_render(), and on_render_input_window().
m_sphere
GLModel Slic3r::GUI::GLGizmoBase::m_sphere protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_state
State Slic3r::GUI::GLGizmoSimplify::m_state private
Referenced by apply_simplify(), on_render_input_window(), process(), stop_worker_thread_request(), and worker_finished().
m_state_mutex
std::mutex Slic3r::GUI::GLGizmoSimplify::m_state_mutex private
Referenced by on_render_input_window(), process(), stop_worker_thread_request(), and worker_finished().
m_tooltip
std::string Slic3r::GUI::GLGizmoBase::m_tooltip mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render().
m_triangle_count
size_t Slic3r::GUI::GLGizmoSimplify::m_triangle_count private
Referenced by init_model(), and on_render_input_window().
m_volume
const ModelVolume* Slic3r::GUI::GLGizmoSimplify::m_volume private
Referenced by apply_simplify(), init_model(), on_render(), on_render_input_window(), on_set_state(), process(), and worker_finished().
m_worker
std::thread Slic3r::GUI::GLGizmoSimplify::m_worker private
Referenced by ~GLGizmoSimplify(), process(), and worker_finished().
tr_decimate_ratio
const std::string Slic3r::GUI::GLGizmoSimplify::tr_decimate_ratio private
Referenced by create_gui_cfg(), and on_render_input_window().
tr_detail_level
const std::string Slic3r::GUI::GLGizmoSimplify::tr_detail_level private
Referenced by create_gui_cfg(), and on_render_input_window().
tr_mesh_name
const std::string Slic3r::GUI::GLGizmoSimplify::tr_mesh_name private
Referenced by create_gui_cfg(), and on_render_input_window().
tr_triangles
const std::string Slic3r::GUI::GLGizmoSimplify::tr_triangles private
Referenced by create_gui_cfg(), and on_render_input_window().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoSimplify.hpp
src/slic3r/GUI/Gizmos/GLGizmoSimplify.cpp