OrcaSlicer: Slic3r::ConfigBase Class Reference
Slic3r::ConfigBase Class Reference abstract
#include <src/libslic3r/Config.hpp>
Classes
struct SetDeserializeItem
Public Member Functions
ConfigBase ()=default
~ConfigBase () override=default
virtual const ConfigDef * def () const =0
virtual ConfigOption * optptr (const t_config_option_key &opt_key, bool create=false)=0
virtual t_config_option_keys keys () const =0
ConfigOption * option (const t_config_option_key &opt_key, bool create=false)
template<typename TYPE >
TYPE * option (const t_config_option_key &opt_key, bool create=false)
ConfigOption * option_throw (const t_config_option_key &opt_key, bool create=false)
template<typename TYPE >
TYPE * option_throw (const t_config_option_key &opt_key, bool create=false)
void apply (const ConfigBase &other, bool ignore_nonexistent=false)
void apply_only (const ConfigBase &other, const t_config_option_keys &keys, bool ignore_nonexistent=false)
bool equals (const ConfigBase &other, const std::set< std::string > *skipped_keys=nullptr) const
t_config_option_keys diff (const ConfigBase &other) const
t_config_option_keys equal (const ConfigBase &other) const
std::string opt_serialize (const t_config_option_key &opt_key) const
void set (const std::string &opt_key, bool value, bool create=false)
void set (const std::string &opt_key, int value, bool create=false)
void set (const std::string &opt_key, double value, bool create=false)
void set (const std::string &opt_key, const char *value, bool create=false)
void set (const std::string &opt_key, const std::string &value, bool create=false)
bool set_deserialize_nothrow (const t_config_option_key &opt_key_src, const std::string &value_src, ConfigSubstitutionContext &substitutions, bool append=false)
void set_deserialize (const t_config_option_key &opt_key, const std::string &str, ConfigSubstitutionContext &config_substitutions, bool append=false)
void set_deserialize_strict (const t_config_option_key &opt_key, const std::string &str, bool append=false)
void set_deserialize (std::initializer_list< SetDeserializeItem > items, ConfigSubstitutionContext &substitutions)
void set_deserialize_strict (std::initializer_list< SetDeserializeItem > items)
double get_abs_value (const t_config_option_key &opt_key) const
double get_abs_value (const t_config_option_key &opt_key, double ratio_over) const
void setenv_ () const
ConfigSubstitutions load (const std::string &file, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load_string_map (std::map< std::string, std::string > &key_values, ForwardCompatibilitySubstitutionRule compatibility_rule)
int load_from_json (const std::string &file, ConfigSubstitutionContext &substitutions, bool load_inherits_in_config, std::map< std::string, std::string > &key_values, std::string &reason)
ConfigSubstitutions load_from_json (const std::string &file, ForwardCompatibilitySubstitutionRule compatibility_rule, std::map< std::string, std::string > &key_values, std::string &reason)
ConfigSubstitutions load_from_ini (const std::string &file, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load_from_ini_string (const std::string &data, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load_from_ini_string_commented (std::string &&data, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load_from_gcode_file (const std::string &file, ForwardCompatibilitySubstitutionRule compatibility_rule)
ConfigSubstitutions load (const boost::property_tree::ptree &tree, ForwardCompatibilitySubstitutionRule compatibility_rule)
void save (const std::string &file) const
void save_to_json (const std::string &file, const std::string &name, const std::string &from, const std::string &version, const std::string is_custom="") const
void null_nullables ()
virtual const ConfigOption * optptr (const t_config_option_key &opt_key) const=0
const ConfigOption * option (const t_config_option_key &opt_key) const
template<typename TYPE >
const TYPE * option (const t_config_option_key &opt_key) const
const ConfigOption * option_throw (const t_config_option_key &opt_key) const
template<typename TYPE >
const TYPE * option_throw (const t_config_option_key &opt_key) const
bool has (const t_config_option_key &opt_key) const
Static Public Member Functions
static size_t load_from_gcode_string_legacy (ConfigBase &config, const char *str, ConfigSubstitutionContext &substitutions)
Protected Member Functions
virtual void handle_legacy (t_config_option_key &, std::string &) const
Private Member Functions
bool set_deserialize_raw (const t_config_option_key &opt_key_src, const std::string &value, ConfigSubstitutionContext &substitutions, bool append)
Detailed Description
Constructor & Destructor Documentation
ConfigBase()
Slic3r::ConfigBase::ConfigBase () default
~ConfigBase()
Slic3r::ConfigBase::~ConfigBase () override default
Member Function Documentation
apply()
void Slic3r::ConfigBase::apply (const ConfigBase & other, bool ignore_nonexistent = false) inline
{ this->apply_only(other, other.keys(), ignore_nonexistent); }
References apply_only(), and keys().
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::PresetCollection::PresetCollection(), Slic3r::BackgroundSlicingProcess::apply(), Slic3r::GCodeProcessor::apply_config_superslicer(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetBundle::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::PartPlate::load_gcode_from_file(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::GCodeProcessor::process_file(), Slic3r::CalibPressureAdvancePattern::refresh_setup(), Slic3r::GUI::ObjectTableSettings::resetAllValues(), Slic3r::CLI::run(), Slic3r::GUI::TabPrintModel::set_model_config(), Slic3r::GUI::PartPlateList::store_to_3mf_structure(), Slic3r::GUI::PresetComboBox::update_ams_color(), Slic3r::GUI::ObjectSettings::update_config_values(), Slic3r::GUI::TabPrintModel::update_model_config(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
apply_only()
void Slic3r::ConfigBase::apply_only (const ConfigBase & other, const t_config_option_keys & keys, bool ignore_nonexistent = false)
{
    // loop through options and apply them
    for (const t_config_option_key &opt_key : keys) {
        // Create a new option with default value for the key.
        // If the key is not in the parameter definition, or this ConfigBase is a static type and it does not support the parameter,
        // an exception is thrown if not ignore_nonexistent.
        ConfigOption *my_opt = this->option(opt_key, true);
        if (my_opt == nullptr) {
            // opt_key does not exist in this ConfigBase and it cannot be created, because it is not defined by this->def().
            // This is only possible if other is of DynamicConfig type.
            if (ignore_nonexistent)
                continue;
            throw UnknownOptionException(opt_key);
        }
    const ConfigOption *other_opt = other.option(opt_key);
    if (other_opt == nullptr) {
            // The key was not found in the source config, therefore it will not be initialized!
//      printf("Not found, therefore not initialized: %s\n", opt_key.c_str());
    } else
            my_opt->set(other_opt);
    }
}
References keys(), option(), and Slic3r::ConfigOption::set().
Referenced by Slic3r::PresetBundle::PresetBundle(), apply(), Slic3r::ModelConfig::apply(), Slic3r::ModelConfig::apply_only(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_user_preset(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::CLI::run(), Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::PhysicalPrinter::update_from_config(), Slic3r::PhysicalPrinter::update_from_preset(), and Slic3r::GUI::TabPrintModel::update_model_config().
def()
virtual const ConfigDef * Slic3r::ConfigBase::def () const pure virtual
Implemented in Slic3r::DynamicConfig, Slic3r::DynamicPrintConfig, Slic3r::StaticPrintConfig, and Slic3r::DynamicPrintAndCLIConfig.
Referenced by get_abs_value(), Slic3r::StaticConfig::keys(), load_from_json(), Slic3r::StaticConfig::set_defaults(), and set_deserialize_raw().
diff()
t_config_option_keys Slic3r::ConfigBase::diff (const ConfigBase & other) const
{
    t_config_option_keys diff;
    for (const t_config_option_key &opt_key : this->keys()) {
        const ConfigOption *this_opt  = this->option(opt_key);
        const ConfigOption *other_opt = other.option(opt_key);
        if (this_opt != nullptr && other_opt != nullptr && *this_opt != *other_opt)
            diff.emplace_back(opt_key);
    }
    return diff;
}
References diff(), keys(), and option().
Referenced by diff().
equal()
t_config_option_keys Slic3r::ConfigBase::equal (const ConfigBase & other) const
{
    t_config_option_keys equal;
    for (const t_config_option_key &opt_key : this->keys()) {
        const ConfigOption *this_opt  = this->option(opt_key);
        const ConfigOption *other_opt = other.option(opt_key);
        if (this_opt != nullptr && other_opt != nullptr && *this_opt == *other_opt)
            equal.emplace_back(opt_key);
    }
    return equal;
}
References equal(), keys(), and option().
Referenced by equal().
equals()
bool Slic3r::ConfigBase::equals (const ConfigBase & other, const std::set< std::string > * skipped_keys = nullptr) const
{
    for (const t_config_option_key &opt_key : this->keys()) {
        if (skipped_keys && (skipped_keys->count(opt_key) != 0))
            continue;
        const ConfigOption *this_opt  = this->option(opt_key);
        const ConfigOption *other_opt = other.option(opt_key);
        if (this_opt != nullptr && other_opt != nullptr && *this_opt != *other_opt)
            return false;
    }
    return true;
}
References keys(), and option().
get_abs_value() [1/2]
double Slic3r::ConfigBase::get_abs_value (const t_config_option_key & opt_key) const
{
    // Get stored option value.
    const ConfigOption *raw_opt = this->option(opt_key);
    if (raw_opt == nullptr) {
      std::stringstream ss;
      ss << "You can't define an option that need " << opt_key << " without defining it!";
      throw std::runtime_error(ss.str());
    }
    assert(raw_opt != nullptr);
    if (raw_opt->type() == coFloat)
        return static_cast<const ConfigOptionFloat*>(raw_opt)->value;
    if (raw_opt->type() == coInt)
      return static_cast<const ConfigOptionInt *>(raw_opt)->value;
    if (raw_opt->type() == coBool)
      return static_cast<const ConfigOptionBool *>(raw_opt)->value ? 1 : 0;
    const ConfigOptionPercent *cast_opt = nullptr;
    if (raw_opt->type() == coFloatOrPercent) {
        auto cofop = static_cast<const ConfigOptionFloatOrPercent*>(raw_opt);
            if (cofop->value == 0 && boost::ends_with(opt_key, "_line_width")) {
                return this->get_abs_value("line_width");
            }
            if (!cofop->percent)
                return cofop->value;
            cast_opt = cofop;
    }
    if (raw_opt->type() == coPercent) {
      cast_opt = static_cast<const ConfigOptionPercent *>(raw_opt);
    }
    // Get option definition.
    const ConfigDef *def = this->def();
    if (def == nullptr)
        throw NoDefinitionException(opt_key);
    const ConfigOptionDef *opt_def = def->get(opt_key);
    assert(opt_def != nullptr);
    if (opt_def->ratio_over == "")
        return cast_opt->get_abs_value(1);
    // Compute absolute value over the absolute value of the base option.
    //FIXME there are some ratio_over chains, which end with empty ratio_with.
    // For example, XXX_extrusion_width parameters are not handled by get_abs_value correctly.
    return opt_def->ratio_over.empty() ? 0. :
        static_cast<const ConfigOptionFloatOrPercent*>(raw_opt)->get_abs_value(this->get_abs_value(opt_def->ratio_over));
    throw ConfigurationError("ConfigBase::get_abs_value(): Not a valid option type for get_abs_value()");
}
References Slic3r::coBool, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coInt, Slic3r::coPercent, def(), Slic3r::ConfigDef::get(), get_abs_value(), Slic3r::ConfigOptionPercent::get_abs_value(), option(), Slic3r::ConfigOptionDef::ratio_over, Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), get_abs_value(), Slic3r::ModelConfig::get_abs_value(), get_abs_value(), Slic3r::CalibPressureAdvancePattern::line_width(), Slic3r::CalibPressureAdvancePattern::line_width_first_layer(), Slic3r::CLI::run(), and Slic3r::GUI::Plater::setPrintSpeedTable().
get_abs_value() [2/2]
double Slic3r::ConfigBase::get_abs_value (const t_config_option_key & opt_key, double ratio_over) const
{
    // Get stored option value.
    const ConfigOption *raw_opt = this->option(opt_key);
    assert(raw_opt != nullptr);
    if (raw_opt->type() != coFloatOrPercent)
        throw ConfigurationError("ConfigBase::get_abs_value(): opt_key is not of coFloatOrPercent");
    // Compute absolute value.
    return static_cast<const ConfigOptionFloatOrPercent*>(raw_opt)->get_abs_value(ratio_over);
}
References Slic3r::coFloatOrPercent, get_abs_value(), option(), and Slic3r::ConfigOption::type().
handle_legacy()
virtual void Slic3r::ConfigBase::handle_legacy (t_config_option_key & , std::string &) const inline protected virtual
Reimplemented in Slic3r::DynamicPrintConfig, Slic3r::StaticPrintConfig, and Slic3r::DynamicPrintAndCLIConfig.
{}
Referenced by load_from_json(), and set_deserialize_nothrow().
has()
bool Slic3r::ConfigOptionResolver::has (const t_config_option_key & opt_key) const inline inherited
{ return this->optptr(opt_key) != nullptr; }
References Slic3r::ConfigOptionResolver::optptr().
Referenced by Slic3r::GUI::change_opt_value(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::Bed3D::detect_type(), Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::dirty_options_without_option_list(), Slic3r::GUI::PartPlate::get_bed_type(), Slic3r::anonymous_namespace{SL1.cpp}::get_cfg_value(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::Preset::get_default_bed_type(), Slic3r::GUI::Plater::get_extruder_colors_from_plater_config(), Slic3r::get_instance_arrange_poly(), Slic3r::GUI::ConfigOptionsGroup::get_option(), Slic3r::GUI::PartPlate::get_print_seq(), Slic3r::GUI::PresetComboBox::get_tooltip(), Slic3r::handle_legacy_project_loaded(), Slic3r::handle_legacy_sla(), Slic3r::ModelConfig::has(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetCollection::is_dirty(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::DynamicPrintConfig::normalize_fdm(), Slic3r::DynamicPrintConfig::normalize_fdm_1(), Slic3r::DynamicConfig::read_cli(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::Preset::remove_invalid_keys(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::GUI::PartPlate::render_logo(), Slic3r::GUI::PartPlate::set_bed_type(), Slic3r::GUI::Plater::setExtruderParams(), Slic3r::GUI::Plater::setPrintSpeedTable(), and Slic3r::PresetBundle::update_compatible().
keys()
virtual t_config_option_keys Slic3r::ConfigBase::keys () const pure virtual
Implemented in Slic3r::StaticConfig, and Slic3r::DynamicConfig.
Referenced by apply(), Slic3r::ModelConfig::apply(), apply_only(), Slic3r::deep_diff(), diff(), equal(), equals(), null_nullables(), save(), save_to_json(), and setenv_().
load() [1/2]
ConfigSubstitutions Slic3r::ConfigBase::load (const boost::property_tree::ptree & tree, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
    ConfigSubstitutionContext substitutions_ctxt(compatibility_rule);
    for (const boost::property_tree::ptree::value_type &v : tree) {
        try {
            t_config_option_key opt_key = v.first;
            this->set_deserialize(opt_key, v.second.get_value<std::string>(), substitutions_ctxt);
        } catch (UnknownOptionException & /* e */) {
            // ignore
        }
    }
    return std::move(substitutions_ctxt.substitutions);
}
References set_deserialize(), and Slic3r::ConfigSubstitutionContext::substitutions.
load() [2/2]
ConfigSubstitutions Slic3r::ConfigBase::load (const std::string & file, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
    std::map<std::string, std::string> key_values;
    if (is_gcode_file(file))
        return this->load_from_gcode_file(file, compatibility_rule);
    else if (is_json_file(file)) {
        std::string reason;
        return this->load_from_json(file, compatibility_rule, key_values, reason);
    }
    else {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "unsupported format for config file" << file;
        return ConfigSubstitutions();
        //return this->load_from_ini(file, compatibility_rule);
    }
}
References error, Slic3r::is_gcode_file(), Slic3r::is_json_file(), load_from_gcode_file(), and load_from_json().
Referenced by Slic3r::import_sla_archive(), load_from_ini(), and load_from_ini_string().
load_from_gcode_file()
ConfigSubstitutions Slic3r::ConfigBase::load_from_gcode_file (const std::string & file, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
    // Read a 64k block from the end of the G-code.
  boost::nowide::ifstream ifs(file);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":  before parse_file %1%") % file.c_str();
    // Look for Slic3r or OrcaSlicer header.
    // Look for the header across the whole file as the G-code may have been extended at the start by a post-processing script or the user.
    //BBS
    bool has_delimiters = true;
    {
        //BBS
        std::string bambuslicer_gcode_header = "; OrcaSlicer";
        std::string orcaslicer_gcode_header = std::string("; generated by ");
        orcaslicer_gcode_header += SLIC3R_APP_NAME;
        std::string header;
        bool        header_found = false;
        while (std::getline(ifs, header)) {
            // BBS
            const char* line_c = skip_whitespaces(header.c_str());
            if (std::toupper(*line_c) == 'N')
                line_c = skip_word(line_c);
            line_c = skip_whitespaces(line_c);
            // BBS
            if (strncmp(bambuslicer_gcode_header.c_str(), line_c, strlen(bambuslicer_gcode_header.c_str())) == 0 ||
                strncmp(orcaslicer_gcode_header.c_str(), line_c, strlen(orcaslicer_gcode_header.c_str())) == 0) {
                header_found = true;
                break;
            }
        }
        if (!header_found) {
            std::string error_message = "Not a gcode file generated by ";
            error_message += SLIC3R_APP_FULL_NAME;
            error_message += ".";
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << error_message;
            throw Slic3r::RuntimeError(error_message.c_str());
        }
    }
    ConfigSubstitutionContext substitutions_ctxt(compatibility_rule);
    size_t                    key_value_pairs = 0;
    if (has_delimiters)
    {
        //BBS
        // PrusaSlicer starting with 2.4.0-alpha0 delimits the config section stored into G-code with
        // ; CONFIG_BLOCK_START
        // ...
        // ; CONFIG_BLOCK_END
        bool begin_found = false;
        bool end_found   = false;
        std::string line;
        while (std::getline(ifs, line))
            if (line.rfind("; CONFIG_BLOCK_START",0)==0) {
                begin_found = true;
                break;
            }
        if (!begin_found) {
            //BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << format("Configuration block closing tag \"; CONFIG_BLOCK_START\" not found when reading %1%", file);
            throw Slic3r::RuntimeError(format("Config tag \"; CONFIG_BLOCK_START\" not found"));
        }
        std::string key, value;
        while (std::getline(ifs, line)) {
            if (line.rfind("; CONFIG_BLOCK_END",0)==0) {
                end_found = true;
                break;
            }
            // line should be a valid key = value pair.
            auto pos = line.find('=');
            if (pos != std::string::npos && pos > 1 && line.front() == ';') {
                key   = line.substr(1, pos - 1);
                value = line.substr(pos + 1);
                boost::trim(key);
                boost::trim(value);
                try {
                    this->set_deserialize(key, value, substitutions_ctxt);
                    ++ key_value_pairs;
                } catch (UnknownOptionException & /* e */) {
                    // ignore
                }
            }
        }
        if (!end_found) {
            //BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << format("Configuration block opening tag \"; CONFIG_BLOCK_END\" not found when reading %1%", file);
            throw Slic3r::RuntimeError(format("Config tag \"; CONFIG_BLOCK_END\" not found"));
        }
    }
    else
    {
        auto                      header_end_pos = ifs.tellg();
        // Slicer older than 2.4.0-alpha0 do not emit any delimiter.
        // Try a heuristics reading the G-code from back.
        ifs.seekg(0, ifs.end);
        auto file_length = ifs.tellg();
      auto data_length = std::min<std::fstream::pos_type>(65535, file_length - header_end_pos);
      ifs.seekg(file_length - data_length, ifs.beg);
        std::vector<char> data(size_t(data_length) + 1, 0);
        ifs.read(data.data(), data_length);
        ifs.close();
        key_value_pairs = load_from_gcode_string_legacy(*this, data.data(), substitutions_ctxt);
    }
    if (key_value_pairs < 80) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << format("Suspiciously low number of configuration values extracted from %1%: %2%", file, key_value_pairs);
        throw Slic3r::RuntimeError(format("Suspiciously low number of configuration values extracted from %1%: %2%", file, key_value_pairs));
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":  finished to parse_file %1%") % file.c_str();
    return std::move(substitutions_ctxt.substitutions);
}
References error, Slic3r::format(), load_from_gcode_string_legacy(), set_deserialize(), Slic3r::skip_whitespaces(), Slic3r::skip_word(), SLIC3R_APP_FULL_NAME, and Slic3r::ConfigSubstitutionContext::substitutions.
Referenced by load(), Slic3r::PresetBundle::load_config_file(), and Slic3r::GCodeProcessor::process_file().
load_from_gcode_string_legacy()
size_t Slic3r::ConfigBase::load_from_gcode_string_legacy (ConfigBase & config, const char * str, ConfigSubstitutionContext & substitutions) static
{
    if (str == nullptr)
        return 0;
    // BBS. Remove line numbers.
    std::regex match_pattern("\nN[0-9]* *");
    std::string replace_pattern = "\n";
    char* result = (char*)calloc(strlen(str) + 1, 1);
    std::regex_replace(result, str, str + strlen(str), match_pattern, replace_pattern);
    // Walk line by line in reverse until a non-configuration key appears.
    const char *data_start = result;
    data_start = skip_whitespaces(data_start);
    if (std::toupper(*data_start) == 'N')
        data_start = skip_word(data_start);
    // boost::nowide::ifstream seems to cook the text data somehow, so less then the 64k of characters may be retrieved.
    const char *end = data_start + strlen(data_start);
    size_t num_key_value_pairs = 0;
    for (;;) {
        // Extract next line.
        for (--end; end > data_start && (*end == '\r' || *end == '\n'); --end);
        if (end == data_start)
            break;
        const char *start = end ++;
        for (; start > data_start && *start != '\r' && *start != '\n'; --start);
        if (start == data_start)
            break;
        // Extracted a line from start to end. Extract the key = value pair.
        if (end - (++ start) < 10 || start[0] != ';' || start[1] != ' ')
            break;
        const char *key = start + 2;
        if (!((*key >= 'a' && *key <= 'z') || (*key >= 'A' && *key <= 'Z')))
            // A key must start with a letter.
            break;
        const char *sep = key;
        for (; sep != end && *sep != '='; ++ sep) ;
        if (sep == end || sep[-1] != ' ' || sep[1] != ' ')
            break;
        const char *value = sep + 2;
        if (value > end)
            break;
        const char *key_end = sep - 1;
        if (key_end - key < 3)
            break;
        // The key may contain letters, digits and underscores.
        for (const char *c = key; c != key_end; ++ c)
            if (!((*c >= 'a' && *c <= 'z') || (*c >= 'A' && *c <= 'Z') || (*c >= '0' && *c <= '9') || *c == '_')) {
                key = nullptr;
                break;
            }
        if (key == nullptr)
            break;
        try {
            config.set_deserialize(std::string(key, key_end), std::string(value, end), substitutions);
            ++num_key_value_pairs;
        }
        catch (UnknownOptionException & /* e */) {
            // ignore
        }
        end = start;
    }
    // BBS
    free(result);
    return num_key_value_pairs;
}
References end, set_deserialize(), Slic3r::skip_whitespaces(), Slic3r::skip_word(), and start.
Referenced by load_from_gcode_file(), and Slic3r::load_from_superslicer_gcode_file().
load_from_ini()
ConfigSubstitutions Slic3r::ConfigBase::load_from_ini (const std::string & file, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
    try {
        boost::property_tree::ptree tree;
        boost::nowide::ifstream ifs(file);
        boost::property_tree::read_ini(ifs, tree);
        return this->load(tree, compatibility_rule);
    } catch (const ConfigurationError &e) {
        throw ConfigurationError(format("Failed loading configuration file \"%1%\": %2%", file, e.what()));
    }
}
References Slic3r::format(), and load().
Referenced by Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive().
load_from_ini_string()
ConfigSubstitutions Slic3r::ConfigBase::load_from_ini_string (const std::string & data, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
    boost::property_tree::ptree tree;
    std::istringstream iss(data);
    boost::property_tree::read_ini(iss, tree);
    return this->load(tree, compatibility_rule);
}
References load().
Referenced by load_from_ini_string_commented().
load_from_ini_string_commented()
ConfigSubstitutions Slic3r::ConfigBase::load_from_ini_string_commented (std::string && data, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
    // Convert the "data" string into INI format by removing the semi-colons at the start of a line.
    // Also the "; generated by PrusaSlicer ..." comment line will be removed.
    size_t j = 0;
    for (size_t i = 0; i < data.size();)
        if (i == 0 || data[i] == '\n') {
            // Start of a line.
            if (data[i] == '\n') {
                // Consume LF, don't keep empty lines.
                if (j > 0 && data[j - 1] != '\n')
                    data[j ++] = data[i];
                ++ i;
            }
            // Skip all leading spaces;
            for (; i < data.size() && (data[i] == ' ' || data[i] == '\t'); ++ i) ;
            // Skip the semicolon (comment indicator).
            if (i < data.size() && data[i] == ';')
                ++ i;
            // Skip all leading spaces after semicolon.
            for (; i < data.size() && (data[i] == ' ' || data[i] == '\t'); ++ i) ;
            if (strncmp(data.data() + i, "generated by ", 13) == 0) {
                // Skip the "; generated by ..." line.
                for (; i < data.size() && data[i] != '\n'; ++ i);
            }
        } else if (data[i] == '\r' && i + 1 < data.size() && data[i + 1] == '\n') {
            // Skip CR.
            ++ i;
        } else {
            // Consume the rest of the data.
            data[j ++] = data[i ++];
        }
    data.erase(data.begin() + j, data.end());
    return this->load_from_ini_string(data, compatibility_rule);
}
References load_from_ini_string().
load_from_json() [1/2]
int Slic3r::ConfigBase::load_from_json (const std::string & file, ConfigSubstitutionContext & substitutions, bool load_inherits_in_config, std::map< std::string, std::string > & key_values, std::string & reason)
{
    json j;
    std::list<std::string> different_settings_append;
    std::string new_support_style;
    bool is_project_settings = false;
    try {
        boost::nowide::ifstream ifs(file);
        ifs >> j;
        const ConfigDef* config_def = this->def();
        if (config_def == nullptr) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ": no config defs!";
            return -1;
        }
        //parse the json elements
        for (auto it = j.begin(); it != j.end(); it++) {
            if (boost::iequals(it.key(),BBL_JSON_KEY_VERSION)) {
                key_values.emplace(BBL_JSON_KEY_VERSION, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_IS_CUSTOM)) {
                key_values.emplace(BBL_JSON_KEY_IS_CUSTOM, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_NAME)) {
                key_values.emplace(BBL_JSON_KEY_NAME, it.value());
                if (it.value() == "project_settings")
                    is_project_settings = true;
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_URL)) {
                key_values.emplace(BBL_JSON_KEY_URL, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_TYPE)) {
                key_values.emplace(BBL_JSON_KEY_TYPE, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_SETTING_ID)) {
                key_values.emplace(BBL_JSON_KEY_SETTING_ID, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_FILAMENT_ID)) {
                key_values.emplace(BBL_JSON_KEY_FILAMENT_ID, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_FROM)) {
                key_values.emplace(BBL_JSON_KEY_FROM, it.value());
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_INSTANTIATION)) {
                key_values.emplace(BBL_JSON_KEY_INSTANTIATION, it.value());
            }
            else if (!load_inherits_to_config && boost::iequals(it.key(), BBL_JSON_KEY_INHERITS)) {
                key_values.emplace(BBL_JSON_KEY_INHERITS, it.value());
            }
            else {
                t_config_option_key opt_key = it.key();
                std::string value_str;
                if (it.value().is_string()) {
                    //bool test1 = (it.key() == std::string("end_gcode"));
                    this->set_deserialize(opt_key, it.value(), substitution_context);
                    //some logic for special values
                    if (opt_key == "support_type") {
                        //std::string new_value = dynamic_cast<ConfigOptionString*>(this->option(opt_key))->value;
                        if (it.value() == "hybrid(auto)") {
                            different_settings_append.push_back(opt_key);
                            different_settings_append.push_back("support_style");
                            new_support_style = "tree_hybrid";
                        }
                    }
                }
                else if (it.value().is_array()) {
                    t_config_option_key opt_key_src = opt_key;
                    this->handle_legacy(opt_key, value_str);
                    if (opt_key.empty()) {
                        //BBS: record these options
                        substitution_context.unrecogized_keys.push_back(opt_key_src);
                        continue;
                    }
                    bool valid = true, first = true, use_comma = true;
                    //bool test2 = (it.key() == std::string("filament_end_gcode"));
                    const ConfigOptionDef* optdef = config_def->get(opt_key);
                    if (optdef == nullptr) {
                        // If we didn't find an option, look for any other option having this as an alias.
                        for (const auto& opt : config_def->options) {
                            for (const t_config_option_key& opt_key2 : opt.second.aliases) {
                                if (opt_key2 == opt_key) {
                                    opt_key = opt.first;
                                    optdef = &opt.second;
                                    break;
                                }
                            }
                            if (optdef != nullptr)
                                break;
                        }
                    }
                    if (optdef && optdef->type == coStrings) {
                        use_comma = false;
                    }
                    for (auto iter = it.value().begin(); iter != it.value().end(); iter++) {
                        if (iter.value().is_string()) {
                            if (!first) {
                                if (use_comma)
                                    value_str += ",";
                                else
                                    value_str += ";";
                            }
                            else
                                first = false;
                            if (use_comma)
                                value_str += iter.value();
                            else {
                                value_str += "\"";
                                value_str += escape_string_cstyle(iter.value());
                                value_str += "\"";
                            }
                        }
                        else {
                            //should not happen
                            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" error, invalid json array for " << it.key();
                            valid = false;
                            break;
                        }
                    }
                    if (valid)
                        this->set_deserialize(opt_key, value_str, substitution_context);
                }
                else {
                    //should not happen
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" error, invalid json type for " << it.key();
                }
            }
        }
        if (!different_settings_append.empty()) {
            if (!new_support_style.empty()) {
                ConfigOptionEnum<SupportMaterialStyle>* opt = this->option<ConfigOptionEnum<SupportMaterialStyle>>("support_style", true);
                opt->value = smsTreeHybrid;
            }
            if (is_project_settings) {
                std::vector<std::string>& different_settings = this->option<ConfigOptionStrings>("different_settings_to_system", true)->values;
                size_t size = different_settings.size();
                if (size == 0) {
                    size = this->option<ConfigOptionStrings>("filament_settings_id")->values.size() + 2;
                    different_settings.resize(size);
                }
                std::vector<bool> is_first(size, false);
                std::vector<std::vector<std::string>> original_diffs(size);
                for (int index = 0; index < size; index++)
                {
                    if (different_settings[index].empty()) {
                        is_first[index] = true;
                    }
                    else {
                        Slic3r::unescape_strings_cstyle(different_settings[index], original_diffs[index]);
                    }
                }
                for (auto diff_key : different_settings_append)
                {
                    //get the index in the group
                    int index = 0;
                    bool need_insert = true;
                    if (diff_key == "support_type")
                        index = 0;
                    else if (diff_key == "support_style")
                        index = 0;
                    //check whether exist firstly
                    if (!original_diffs[index].empty()) {
                        for (int j = 0; j < original_diffs[index].size(); j++) {
                            if (original_diffs[index][j] == diff_key) {
                                need_insert = false;
                                break;
                            }
                        }
                    }
                    if (!need_insert)
                        continue;
                    //insert this key
                    if (!is_first[index])
                        different_settings[index] += ";";
                    else
                        is_first[index] = false;
                    different_settings[index] += diff_key;
                }
            }
        }
        return 0;
    }
    catch (const std::ifstream::failure &err)  {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" got a ifstream error, reason = " << err.what();
        reason = std::string("ifstreamError: ") + err.what();
        //throw ConfigurationError(format("Failed loading configuration file \"%1%\": %2%", file, e.what()));
    }
    catch(nlohmann::detail::parse_error &err) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" got a nlohmann::detail::parse_error, reason = " << err.what();
        reason = std::string("JsonParseError: ") + err.what();
        //throw ConfigurationError(format("Failed loading configuration file \"%1%\": %2%", file, err.what()));
    }
    catch(std::exception &err) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<file<<" got a generic exception, reason = " << err.what();
        reason = std::string("std::exception: ") + err.what();
    }
    return -1;
}
References BBL_JSON_KEY_FILAMENT_ID, BBL_JSON_KEY_FROM, BBL_JSON_KEY_INHERITS, BBL_JSON_KEY_INSTANTIATION, BBL_JSON_KEY_IS_CUSTOM, BBL_JSON_KEY_NAME, BBL_JSON_KEY_SETTING_ID, BBL_JSON_KEY_TYPE, BBL_JSON_KEY_URL, BBL_JSON_KEY_VERSION, Slic3r::coStrings, def(), Slic3r::empty(), error, Slic3r::escape_string_cstyle(), Slic3r::ConfigDef::get(), handle_legacy(), Slic3r::ConfigDef::options, set_deserialize(), size, Slic3r::smsTreeHybrid, Slic3r::ConfigOptionDef::type, Slic3r::unescape_strings_cstyle(), Slic3r::ConfigSubstitutionContext::unrecogized_keys, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::_BBS_3MF_Importer::_extract_project_config_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::PresetBundle::import_presets(), load(), load_from_json(), Slic3r::PresetCollection::load_presets(), Slic3r::PhysicalPrinterCollection::load_printers(), and Slic3r::PresetBundle::load_vendor_configs_from_json().
load_from_json() [2/2]
ConfigSubstitutions Slic3r::ConfigBase::load_from_json (const std::string & file, ForwardCompatibilitySubstitutionRule compatibility_rule, std::map< std::string, std::string > & key_values, std::string & reason)
{
    int ret = 0;
    ConfigSubstitutionContext substitutions_ctxt(compatibility_rule);
    ret = load_from_json(file, substitutions_ctxt, true, key_values, reason);
    return std::move(substitutions_ctxt.substitutions);
}
References load_from_json(), and Slic3r::ConfigSubstitutionContext::substitutions.
load_string_map()
ConfigSubstitutions Slic3r::ConfigBase::load_string_map (std::map< std::string, std::string > & key_values, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
    ConfigSubstitutionContext substitutions_ctxt(compatibility_rule);
    std::map<std::string, std::string>::iterator it;
    for (it = key_values.begin(); it != key_values.end(); it++) {
        try {
            t_config_option_key opt_key = it->first;
            this->set_deserialize(opt_key, it->second, substitutions_ctxt);
        }
        catch (UnknownOptionException& /* e */) {
            // ignore
        }
    }
    return std::move(substitutions_ctxt.substitutions);
}
References set_deserialize(), and Slic3r::ConfigSubstitutionContext::substitutions.
Referenced by Slic3r::PresetCollection::load_user_preset().
null_nullables()
void Slic3r::ConfigBase::null_nullables ()
{
    for (const std::string &opt_key : this->keys()) {
        ConfigOption *opt = this->optptr(opt_key, false);
        assert(opt != nullptr);
        if (opt->nullable())
          opt->deserialize("nil", ForwardCompatibilitySubstitutionRule::Disable);
    }
}
References Slic3r::ConfigOption::deserialize(), Slic3r::Disable, keys(), Slic3r::ConfigOption::nullable(), and optptr().
Referenced by Slic3r::PresetBundle::PresetBundle().
opt_serialize()
std::string Slic3r::ConfigBase::opt_serialize (const t_config_option_key & opt_key) const
{
    const ConfigOption* opt = this->option(opt_key);
    assert(opt != nullptr);
    return opt->serialize();
}
References option(), and Slic3r::ConfigOption::serialize().
Referenced by Slic3r::_3MF_Exporter::_add_print_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_print_config_file_to_archive(), Slic3r::GCode::_do_export(), Slic3r::GCode::append_full_config(), Slic3r::anonymous_namespace{SL1.cpp}::fill_slicerconf(), Slic3r::ModelConfig::opt_serialize(), and save().
option() [1/4]
template<typename TYPE > const TYPE * Slic3r::ConfigOptionResolver::option (const t_config_option_key & opt_key) const inline
    {
        const ConfigOption* opt = this->optptr(opt_key);
        return (opt == nullptr || opt->type() != TYPE::static_type()) ? nullptr : static_cast<const TYPE*>(opt);
    }
option() [2/4]
const ConfigOption * Slic3r::ConfigOptionResolver::option (const t_config_option_key & opt_key) const inline
{ return this->optptr(opt_key); }
option() [3/4]
ConfigOption * Slic3r::ConfigBase::option (const t_config_option_key & opt_key, bool create = false) inline
        { return this->optptr(opt_key, create); }
References optptr().
Referenced by Slic3r::DynamicConfig::DynamicConfig(), Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::PresetBundle::PresetBundle(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::Plater::_calib_pa_tower(), Slic3r::GCode::_do_export(), Slic3r::_BBS_3MF_Importer::_extract_project_embedded_presets_from_archive(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::add_correct_opts_to_diff(), Slic3r::GUI::add_correct_opts_to_options_list(), Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::GUI::ObjectTableSettings::add_missed_options(), Slic3r::GCode::append_full_config(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::Search::OptionsSearcher::append_options(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::ConfigManipulation::apply(), Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GCodeProcessor::apply_config(), Slic3r::PlaceholderParser::apply_config(), Slic3r::GUI::ConfigManipulation::apply_null_fff_config(), apply_only(), Slic3r::PlaceholderParser::apply_only(), Slic3r::GUI::GLCanvas3D::WipeTowerInfo::apply_wipe_tower(), Slic3r::GUI::ConfigOptionsGroup::back_to_config_value(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::TabPrinter::build_unregular_pages(), Slic3r::GUI::Plater::calib_max_vol_speed(), Slic3r::GUI::Plater::calib_retraction(), Slic3r::GUI::PlaterPresetComboBox::change_extruder_color(), Slic3r::Search::change_opt_key(), Slic3r::GUI::change_opt_value(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::Preset::compatible_printers_condition(), Slic3r::Preset::compatible_prints_condition(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::Tab::compatible_widget_reload(), Slic3r::GUI::Plater::config_change_notification(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::deep_diff(), Slic3r::GUI::Bed3D::detect_type(), diff(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::CalibPressureAdvancePattern::draw_line(), equal(), equals(), Slic3r::GUI::GLCanvas3D::estimate_wipe_tower_points(), Slic3r::GUI::PartPlate::estimate_wipe_tower_size(), Slic3r::GUI::Plater::export_3mf(), Slic3r::PresetBundle::export_selections(), Slic3r::GUI::GUI_App::extruders_cnt(), Slic3r::GUI::TabPrinter::extruders_count_changed(), Slic3r::GUI::GUI_App::extruders_edited_cnt(), Slic3r::CalibPressureAdvance::find_optimal_PA_speed(), Slic3r::GUI::Plater::force_filament_colors_update(), Slic3r::PresetBundle::full_fff_config(), Slic3r::full_print_config_diffs(), Slic3r::PresetBundle::full_sla_config(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), get_abs_value(), get_abs_value(), Slic3r::GUI::ExtrusionCalibration::get_bed_temp(), Slic3r::anonymous_namespace{SL1.cpp}::get_cfg_value(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::ModelObject::get_config_value(), Slic3r::GUI::ConfigOptionsGroup::get_config_value2(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::GUI::Plater::get_extruder_colors_from_plater_config(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::DynamicPrintConfig::get_filament_type(), Slic3r::GUI::get_full_label(), Slic3r::get_instance_arrange_poly(), Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::PrintHost::get_print_host(), get_printer_technology(), Slic3r::anonymous_namespace{SL1.cpp}::get_raster_params(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), Slic3r::anonymous_namespace{SL1.cpp}::get_slice_params(), Slic3r::GUI::get_string_from_enum(), Slic3r::GUI::get_string_value(), Slic3r::GUI::ObjectGridTable::get_volume_config_value(), Slic3r::handle_legacy_project_loaded(), Slic3r::CalibPressureAdvancePattern::height_first_layer(), Slic3r::CalibPressureAdvancePattern::height_layer(), Slic3r::PresetBundle::import_presets(), Slic3r::Preset::inherits(), Slic3r::GUI::ObjectTablePanel::init_filaments_and_colors(), Slic3r::is_compatible_with_parent_printer(), Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::is_compatible_with_printer(), Slic3r::DynamicPrintConfig::is_custom_defined(), Slic3r::GUI::is_support_filament(), Slic3r::StaticConfig::keys(), Slic3r::GUI::MainFrame::load_config(), Slic3r::GUI::Tab::load_config(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::PresetCollection::load_external_preset(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::min_object_distance(), Slic3r::Preset::normalize(), Slic3r::DynamicPrintConfig::normalize_fdm(), Slic3r::DynamicPrintConfig::normalize_fdm_1(), Slic3r::GUI::TabPrintLayer::notify_changed(), Slic3r::GUI::ExtruderOptionsGroup::on_change_OG(), Slic3r::GUI::Plater::on_config_change(), Slic3r::GUI::TabPrinter::on_preset_loaded(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::DynamicConfig::opt(), Slic3r::DynamicConfig::opt(), Slic3r::DynamicConfig::opt_enum(), Slic3r::DynamicConfig::opt_enum(), Slic3r::DynamicConfig::opt_float(), Slic3r::DynamicConfig::opt_float(), Slic3r::DynamicConfig::opt_int(), Slic3r::DynamicConfig::opt_int(), opt_serialize(), Slic3r::PlaceholderParser::option(), Slic3r::ModelConfig::option(), Slic3r::client::MyContext::optptr(), Slic3r::opts_equal(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::BackgroundSlicingProcess::prepare_upload(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::print_config_diffs(), Slic3r::Preset::printer_technology(), Slic3r::PhysicalPrinter::printer_technology(), Slic3r::Preset::printer_technology_ref(), Slic3r::DynamicConfig::read_cli(), Slic3r::CalibPressureAdvancePattern::refresh_setup(), Slic3r::GUI::ObjectGridTable::reload_object_data(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::reset_project_embedded_presets(), Slic3r::CLI::run(), Slic3r::Preset::save(), Slic3r::PresetCollection::save_current_preset(), save_to_json(), Slic3r::GUI::Selection::scale_to_fit_print_volume(), Slic3r::GUI::Tab::select_preset(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::StaticConfig::set_defaults(), set_deserialize_raw(), Slic3r::DynamicPrintConfig::set_num_extruders(), Slic3r::PresetBundle::set_num_filaments(), Slic3r::DynamicPrintConfig::set_num_filaments(), Slic3r::CLI::setup(), Slic3r::CalibPressureAdvancePattern::speed_first_layer(), Slic3r::CalibPressureAdvancePattern::speed_perimeter(), Slic3r::PresetBundle::sync_ams_list(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::ConfigManipulation::toggle_field(), Slic3r::GUI::ConfigManipulation::toggle_line(), Slic3r::GUI::TabFilament::toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::Plater::priv::undo_redo_to(), Slic3r::GUI::PhysicalPrinterDialog::update(), Slic3r::GUI::PresetComboBox::update_ams_color(), Slic3r::GLVolumeCollection::update_colors_by_extruder(), Slic3r::PresetBundle::update_compatible(), Slic3r::PresetCollection::update_compatible_internal(), Slic3r::GUI::ObjectTableSettings::update_config_values(), Slic3r::GUI::TabPrintLayer::update_custom_dirty(), Slic3r::GUI::TabPrinter::update_fff(), Slic3r::GUI::Plater::update_filament_colors_in_full_config(), Slic3r::GUI::TabFilament::update_filament_overrides_page(), Slic3r::PhysicalPrinter::update_from_config(), Slic3r::GUI::PhysicalPrinterDialog::update_host_type(), Slic3r::PresetBundle::update_multi_material_filament_presets(), Slic3r::PhysicalPrinter::update_preset_names_in_config(), Slic3r::GUI::Sidebar::update_presets(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::PresetBundle::update_selections(), Slic3r::GUI::ObjectTableSettings::update_settings_list(), Slic3r::DynamicPrintConfig::validate(), Slic3r::PresetBundle::validate_printers(), Slic3r::GUI::ObjectTableSettings::ValueChanged(), and Slic3r::CalibPressureAdvancePattern::wall_count().
option() [4/4]
template<typename TYPE > TYPE * Slic3r::ConfigBase::option (const t_config_option_key & opt_key, bool create = false) inline
    {
        ConfigOption *opt = this->optptr(opt_key, create);
        return (opt == nullptr || opt->type() != TYPE::static_type()) ? nullptr : static_cast<TYPE*>(opt);
    }
References optptr(), and Slic3r::ConfigOption::type().
option_throw() [1/4]
template<typename TYPE > const TYPE * Slic3r::ConfigOptionResolver::option_throw (const t_config_option_key & opt_key) const inline
    {
        const ConfigOption* opt = this->option_throw(opt_key);
        if (opt->type() != TYPE::static_type())
            throw BadOptionTypeException("Conversion to a wrong type");
        return static_cast<TYPE*>(opt);
    }
option_throw() [2/4]
const ConfigOption * Slic3r::ConfigOptionResolver::option_throw (const t_config_option_key & opt_key) const inline
    {
        const ConfigOption* opt = this->optptr(opt_key);
        if (opt == nullptr)
            throw UnknownOptionException(opt_key);
        return opt;
    }
option_throw() [3/4]
ConfigOption * Slic3r::ConfigBase::option_throw (const t_config_option_key & opt_key, bool create = false) inline
    {
        ConfigOption *opt = this->optptr(opt_key, create);
        if (opt == nullptr)
            throw UnknownOptionException(opt_key);
        return opt;
    }
References optptr().
Referenced by option_throw(), set(), and set().
option_throw() [4/4]
template<typename TYPE > TYPE * Slic3r::ConfigBase::option_throw (const t_config_option_key & opt_key, bool create = false) inline
    {
        ConfigOption *opt = this->option_throw(opt_key, create);
        if (opt->type() != TYPE::static_type())
            throw BadOptionTypeException("Conversion to a wrong type");
        return static_cast<TYPE*>(opt);
    }
References option_throw(), and Slic3r::ConfigOption::type().
optptr() [1/2]
virtual const ConfigOption * Slic3r::ConfigOptionResolver::optptr (const t_config_option_key & opt_key) const virtual
Implements Slic3r::ConfigOptionResolver.
Reimplemented in Slic3r::DynamicConfig.
optptr() [2/2]
virtual ConfigOption * Slic3r::ConfigBase::optptr (const t_config_option_key & opt_key, bool create = false) pure virtual
Implemented in Slic3r::DynamicConfig.
Referenced by null_nullables(), option(), and option_throw().
save()
void Slic3r::ConfigBase::save (const std::string & file) const
{
    boost::nowide::ofstream c;
    c.open(file, std::ios::out | std::ios::trunc);
    c << "# " << Slic3r::header_slic3r_generated() << std::endl;
    for (const std::string &opt_key : this->keys())
        c << opt_key << " = " << this->opt_serialize(opt_key) << std::endl;
    c.close();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", saved config to %1%\n")%file;
}
References Slic3r::header_slic3r_generated(), keys(), and opt_serialize().
save_to_json()
void Slic3r::ConfigBase::save_to_json (const std::string & file, const std::string & name, const std::string & from, const std::string & version, const std::string is_custom = "") const
{
    json j;
    //record the headers
    j[BBL_JSON_KEY_VERSION] = version;
    j[BBL_JSON_KEY_NAME] = name;
    j[BBL_JSON_KEY_FROM] = from;
    if (!is_custom.empty())
        j[BBL_JSON_KEY_IS_CUSTOM] = is_custom;
    //record all the key-values
    for (const std::string &opt_key : this->keys())
    {
        const ConfigOption* opt = this->option(opt_key);
        if ( opt->is_scalar() ) {
            if (opt->type() == coString && (opt_key != "bed_custom_texture" && opt_key != "bed_custom_model"))
                //keep \n, \r, \t
                j[opt_key] = (dynamic_cast<const ConfigOptionString *>(opt))->value;
            else
                j[opt_key] = opt->serialize();
        }
        else {
            const ConfigOptionVectorBase *vec = static_cast<const ConfigOptionVectorBase*>(opt);
            //if (!vec->empty())
            std::vector<std::string> string_values = vec->vserialize();
            /*for (int i = 0; i < string_values.size(); i++)
            {
                std::string string_value = escape_string_cstyle(string_values[i]);
                j[opt_key][i] = string_value;
            }*/
            json j_array(string_values);
            j[opt_key] = j_array;
        }
    }
    boost::nowide::ofstream c;
    c.open(file, std::ios::out | std::ios::trunc);
    c << std::setw(4) << j << std::endl;
    c.close();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format(", saved config to %1%\n")%file;
}
References BBL_JSON_KEY_FROM, BBL_JSON_KEY_IS_CUSTOM, BBL_JSON_KEY_NAME, BBL_JSON_KEY_VERSION, Slic3r::coString, Slic3r::ConfigOption::is_scalar(), keys(), option(), Slic3r::ConfigOption::serialize(), Slic3r::ConfigOption::type(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value(), and Slic3r::ConfigOptionVectorBase::vserialize().
Referenced by Slic3r::_BBS_3MF_Exporter::_add_project_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive(), Slic3r::CLI::run(), Slic3r::PhysicalPrinter::save(), Slic3r::Preset::save(), and Slic3r::PhysicalPrinter::save().
set() [1/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, bool value, bool create = false) inline
      { this->option_throw<ConfigOptionBool>(opt_key, create)->value = value; }
Referenced by Slic3r::import_sla_archive(), Slic3r::CLI::run(), and Slic3r::ModelConfig::set().
set() [2/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, const char * value, bool create = false) inline
      { this->option_throw<ConfigOptionString>(opt_key, create)->value = value; }
set() [3/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, const std::string & value, bool create = false) inline
      { this->option_throw<ConfigOptionString>(opt_key, create)->value = value; }
set() [4/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, double value, bool create = false)
{
    ConfigOption *opt = this->option_throw(opt_key, create);
    switch (opt->type()) {
      case coFloat:       static_cast<ConfigOptionFloat*>(opt)->value = value; break;
      case coFloatOrPercent:  static_cast<ConfigOptionFloatOrPercent*>(opt)->value = value; static_cast<ConfigOptionFloatOrPercent*>(opt)->percent = false; break;
        case coString:      static_cast<ConfigOptionString*>(opt)->value = float_to_string_decimal_point(value); break;
      default: throw BadOptionTypeException("Configbase::set() - conversion from float not possible");
    }
}
References Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coString, Slic3r::float_to_string_decimal_point(), option_throw(), and Slic3r::ConfigOption::type().
set() [5/5]
void Slic3r::ConfigBase::set (const std::string & opt_key, int value, bool create = false)
{
    ConfigOption *opt = this->option_throw(opt_key, create);
    switch (opt->type()) {
      case coInt:    static_cast<ConfigOptionInt*>(opt)->value = value; break;
      case coFloat:  static_cast<ConfigOptionFloat*>(opt)->value = value; break;
    case coFloatOrPercent:  static_cast<ConfigOptionFloatOrPercent*>(opt)->value = value; static_cast<ConfigOptionFloatOrPercent*>(opt)->percent = false; break;
    case coString: static_cast<ConfigOptionString*>(opt)->value = std::to_string(value); break;
      default: throw BadOptionTypeException("Configbase::set() - conversion from int not possible");
    }
}
References Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coInt, Slic3r::coString, option_throw(), and Slic3r::ConfigOption::type().
set_deserialize() [1/2]
void Slic3r::ConfigBase::set_deserialize (const t_config_option_key & opt_key, const std::string & str, ConfigSubstitutionContext & config_substitutions, bool append = false)
{
  if (! this->set_deserialize_nothrow(opt_key_src, value_src, substitutions_ctxt, append))
    throw BadOptionValueException(format("Invalid value provided for parameter %1%: %2%", opt_key_src,  value_src));
}
References Slic3r::append(), Slic3r::format(), and set_deserialize_nothrow().
Referenced by load(), load_from_gcode_file(), load_from_gcode_string_legacy(), load_from_json(), load_string_map(), Slic3r::ModelConfig::set_deserialize(), set_deserialize(), set_deserialize_strict(), and set_deserialize_strict().
set_deserialize() [2/2]
void Slic3r::ConfigBase::set_deserialize (std::initializer_list< SetDeserializeItem > items, ConfigSubstitutionContext & substitutions)
{
  for (const SetDeserializeItem &item : items)
    this->set_deserialize(item.opt_key, item.opt_value, substitutions_ctxt, item.append);
}
References set_deserialize().
set_deserialize_nothrow()
bool Slic3r::ConfigBase::set_deserialize_nothrow (const t_config_option_key & opt_key_src, const std::string & value_src, ConfigSubstitutionContext & substitutions, bool append = false)
{
    t_config_option_key opt_key = opt_key_src;
    std::string         value   = value_src;
    // Both opt_key and value may be modified by handle_legacy().
    // If the opt_key is no more valid in this version of Slic3r, opt_key is cleared by handle_legacy().
    this->handle_legacy(opt_key, value);
    if (opt_key.empty()) {
        // Ignore the option.
        //BBS: record these options, keep only one repeated opt_key
        auto iter = std::find(substitutions_ctxt.unrecogized_keys.begin(), substitutions_ctxt.unrecogized_keys.end(), opt_key_src);
        if (iter == substitutions_ctxt.unrecogized_keys.end())
            substitutions_ctxt.unrecogized_keys.push_back(opt_key_src);
        return true;
    }
    return this->set_deserialize_raw(opt_key, value, substitutions_ctxt, append);
}
References Slic3r::append(), handle_legacy(), set_deserialize_raw(), and Slic3r::ConfigSubstitutionContext::unrecogized_keys.
Referenced by Slic3r::DynamicConfig::read_cli(), and set_deserialize().
set_deserialize_raw()
bool Slic3r::ConfigBase::set_deserialize_raw (const t_config_option_key & opt_key_src, const std::string & value, ConfigSubstitutionContext & substitutions, bool append) private
{
    t_config_option_key    opt_key = opt_key_src;
    // Try to deserialize the option by its name.
    const ConfigDef       *def     = this->def();
    if (def == nullptr)
        throw NoDefinitionException(opt_key);
    const ConfigOptionDef *optdef  = def->get(opt_key);
    if (optdef == nullptr) {
        // If we didn't find an option, look for any other option having this as an alias.
        for (const auto &opt : def->options) {
            for (const t_config_option_key &opt_key2 : opt.second.aliases) {
                if (opt_key2 == opt_key) {
                    opt_key = opt.first;
                    optdef = &opt.second;
                    break;
                }
            }
            if (optdef != nullptr)
                break;
        }
        if (optdef == nullptr)
            throw UnknownOptionException(opt_key);
    }
    if (! optdef->shortcut.empty()) {
        // Aliasing for example "solid_layers" to "top_shell_layers" and "bottom_shell_layers".
        for (const t_config_option_key &shortcut : optdef->shortcut)
            // Recursive call.
            if (! this->set_deserialize_raw(shortcut, value, substitutions_ctxt, append))
                return false;
        return true;
    }
    ConfigOption *opt = this->option(opt_key, true);
    assert(opt != nullptr);
    bool success     = false;
    bool substituted = false;
    if (optdef->type == coBools && substitutions_ctxt.rule != ForwardCompatibilitySubstitutionRule::Disable) {
        //FIXME Special handling of vectors of bools, quick and not so dirty solution before PrusaSlicer 2.3.2 release.
      bool nullable = opt->nullable();
      ConfigHelpers::DeserializationSubstitution default_value = ConfigHelpers::DeserializationSubstitution::DefaultsToFalse;
      if (optdef->default_value) {
        // Default value for vectors of booleans used in a "per extruder" context, thus the default contains just a single value.
        assert(dynamic_cast<const ConfigOptionVector<unsigned char>*>(optdef->default_value.get()));
      auto &values = static_cast<const ConfigOptionVector<unsigned char>*>(optdef->default_value.get())->values;
      if (values.size() == 1 && values.front() == 1)
        default_value = ConfigHelpers::DeserializationSubstitution::DefaultsToTrue;
    }
      auto result = nullable ?
        static_cast<ConfigOptionBoolsNullable*>(opt)->deserialize_with_substitutions(value, append, default_value) :
        static_cast<ConfigOptionBools*>(opt)->deserialize_with_substitutions(value, append, default_value);
      success     = result != ConfigHelpers::DeserializationResult::Failed;
      substituted = result == ConfigHelpers::DeserializationResult::Substituted;
    } else {
    //bool test = (opt_key == "filament_end_gcode");
    success = opt->deserialize(value, append);
      if (! success && substitutions_ctxt.rule != ForwardCompatibilitySubstitutionRule::Disable &&
          // Only allow substitutions of an enum value by another enum value or a boolean value with an enum value.
          // That means, we expect enum values being added in the future and possibly booleans being converted to enums.
            (optdef->type == coEnum || optdef->type == coEnums || optdef->type == coBool) /*&& ConfigHelpers::looks_like_enum_value(value)*/) {
          // Deserialize failed, try to substitute with a default value.
          //assert(substitutions_ctxt.rule == ForwardCompatibilitySubstitutionRule::Enable || substitutions_ctxt.rule == ForwardCompatibilitySubstitutionRule::EnableSilent);
          if (optdef->type == coBool)
              static_cast<ConfigOptionBool*>(opt)->value = ConfigHelpers::enum_looks_like_true_value(value);
          else
            // Just use the default of the option.
              opt->set(optdef->default_value.get());
            success     = true;
            substituted = true;
      }
  }
    if (substituted && (substitutions_ctxt.rule == ForwardCompatibilitySubstitutionRule::Enable ||
                        substitutions_ctxt.rule == ForwardCompatibilitySubstitutionRule::EnableSystemSilent)) {
        // Log the substitution.
        ConfigSubstitution config_substitution;
        config_substitution.opt_def   = optdef;
        config_substitution.old_value = value;
        config_substitution.new_value = ConfigOptionUniquePtr(opt->clone());
        substitutions_ctxt.substitutions.emplace_back(std::move(config_substitution));
    }
    return success;
}
References Slic3r::append(), Slic3r::ConfigOption::clone(), Slic3r::coBool, Slic3r::coBools, Slic3r::coEnum, Slic3r::coEnums, def(), Slic3r::ConfigOptionDef::default_value, Slic3r::ConfigHelpers::DefaultsToFalse, Slic3r::ConfigHelpers::DefaultsToTrue, Slic3r::ConfigOption::deserialize(), Slic3r::Disable, Slic3r::Enable, Slic3r::EnableSystemSilent, Slic3r::ConfigHelpers::enum_looks_like_true_value(), Slic3r::ConfigHelpers::Failed, Slic3r::ConfigDef::get(), Slic3r::ConfigSubstitution::new_value, Slic3r::ConfigOption::nullable(), Slic3r::ConfigSubstitution::old_value, Slic3r::ConfigSubstitution::opt_def, option(), Slic3r::ConfigDef::options, Slic3r::ConfigSubstitutionContext::rule, Slic3r::ConfigOption::set(), set_deserialize_raw(), Slic3r::ConfigOptionDef::shortcut, Slic3r::ConfigHelpers::Substituted, Slic3r::ConfigSubstitutionContext::substitutions, and Slic3r::ConfigOptionDef::type.
Referenced by set_deserialize_nothrow(), and set_deserialize_raw().
set_deserialize_strict() [1/2]
void Slic3r::ConfigBase::set_deserialize_strict (const t_config_option_key & opt_key, const std::string & str, bool append = false) inline
        { ConfigSubstitutionContext ctxt{ ForwardCompatibilitySubstitutionRule::Disable }; this->set_deserialize(opt_key, str, ctxt, append); }
References Slic3r::append(), Slic3r::Disable, and set_deserialize().
set_deserialize_strict() [2/2]
void Slic3r::ConfigBase::set_deserialize_strict (std::initializer_list< SetDeserializeItem > items) inline
        { ConfigSubstitutionContext ctxt{ ForwardCompatibilitySubstitutionRule::Disable }; this->set_deserialize(items, ctxt); }
References Slic3r::Disable, and set_deserialize().
setenv_()
void Slic3r::ConfigBase::setenv_ () const
{
    t_config_option_keys opt_keys = this->keys();
    for (t_config_option_keys::const_iterator it = opt_keys.begin(); it != opt_keys.end(); ++it) {
        // prepend the SLIC3R_ prefix
        std::ostringstream ss;
        ss << "SLIC3R_";
        ss << *it;
        std::string envname = ss.str();
        // capitalize environment variable name
        for (size_t i = 0; i < envname.size(); ++i)
            envname[i] = (envname[i] <= 'z' && envname[i] >= 'a') ? envname[i]-('a'-'A') : envname[i];
        boost::nowide::setenv(envname.c_str(), this->opt_serialize(*it).c_str(), 1);
    }
}
References keys().
Referenced by Slic3r::run_post_process_scripts().
The documentation for this class was generated from the following files:
src/libslic3r/Config.hpp
src/libslic3r/Config.cpp