OrcaSlicer: orgQhull::QhullLinkedList< T > Class Template Reference
orgQhull::QhullLinkedList< T > Class Template Reference
#include <src/qhull/src/libqhullcpp/QhullLinkedList.h>
Classes
class const_iterator
class iterator
Public Types
Defined here
typedef const_iterator ConstIterator
typedef iterator Iterator
typedef ptrdiff_t difference_type
typedef countT size_type
typedef T value_type
typedef const value_type * const_pointer
typedef const value_type & const_reference
typedef value_type * pointer
typedef value_type & reference
Public Member Functions
Conversions
std::vector< T > toStdVector () const
GetSet
countT count () const
bool isEmpty () const
bool operator== (const QhullLinkedList< T > &o) const
bool operator!= (const QhullLinkedList< T > &o) const
size_t size () const
Element access
For back() and last(), return T instead of T& (T is computed)
const T back () const
T back ()
const T & first () const
T & first ()
const T & front () const
T & front ()
const T last () const
T last ()
Search
bool contains (const T &t) const
countT count (const T &t) const
Iterator
iterator begin ()
const_iterator begin () const
const_iterator constBegin () const
const_iterator constEnd () const
iterator end ()
const_iterator end () const
Private Attributes
Fields
T begin_node
T end_node
Constructors
Sentinel node at end of list
QhullLinkedList (T b, T e)
QhullLinkedList (const QhullLinkedList< T > &other)
Copy constructor copies begin_node and end_node, but not the list elements. Needed for return by value and parameter passing.
QhullLinkedList< T > & operator= (const QhullLinkedList< T > &other)
Copy assignment copies begin_node and end_node, but not the list elements.
~QhullLinkedList ()
QhullLinkedList ()
disabled since a sentinel must be allocated as the private type
Detailed Description
template<typename T>
class orgQhull::QhullLinkedList< T >
Member Typedef Documentation
const_pointer
template<typename T > typedef const value_type* orgQhull::QhullLinkedList< T >::const_pointer
const_reference
template<typename T > typedef const value_type& orgQhull::QhullLinkedList< T >::const_reference
ConstIterator
template<typename T > typedef const_iterator orgQhull::QhullLinkedList< T >::ConstIterator
difference_type
template<typename T > typedef ptrdiff_t orgQhull::QhullLinkedList< T >::difference_type
Iterator
template<typename T > typedef iterator orgQhull::QhullLinkedList< T >::Iterator
pointer
template<typename T > typedef value_type* orgQhull::QhullLinkedList< T >::pointer
reference
template<typename T > typedef value_type& orgQhull::QhullLinkedList< T >::reference
size_type
template<typename T > typedef countT orgQhull::QhullLinkedList< T >::size_type
value_type
template<typename T > typedef T orgQhull::QhullLinkedList< T >::value_type
Constructor & Destructor Documentation
QhullLinkedList() [1/3]
template<typename T > orgQhull::QhullLinkedList< T >::QhullLinkedList (T b, T e) inline
: begin_node(b), end_node(e) {}
QhullLinkedList() [2/3]
template<typename T > orgQhull::QhullLinkedList< T >::QhullLinkedList (const QhullLinkedList< T > & other) inline
Copy constructor copies begin_node and end_node, but not the list elements. Needed for return by value and parameter passing.
: begin_node(other.begin_node), end_node(other.end_node) {}
~QhullLinkedList()
template<typename T > orgQhull::QhullLinkedList< T >::~QhullLinkedList () inline
{}
QhullLinkedList() [3/3]
template<typename T > orgQhull::QhullLinkedList< T >::QhullLinkedList () inline private
disabled since a sentinel must be allocated as the private type
{}
Member Function Documentation
back() [1/2]
template<typename T > T orgQhull::QhullLinkedList< T >::back () inline
{ return last(); }
References orgQhull::QhullLinkedList< T >::last().
back() [2/2]
template<typename T > const T orgQhull::QhullLinkedList< T >::back () const inline
{ return last(); }
References orgQhull::QhullLinkedList< T >::last().
Referenced by orgQhull::QhullLinkedList_test::t_element().
begin() [1/2]
template<typename T > iterator orgQhull::QhullLinkedList< T >::begin () inline
{ return begin_node; }
References orgQhull::QhullLinkedList< T >::begin_node.
Referenced by operator<<(), orgQhull::QhullLinkedList_test::t_const_iterator(), orgQhull::QhullLinkedList_test::t_convert(), orgQhull::QhullLinkedList_test::t_iterator(), and orgQhull::QhullLinkedList_test::t_search().
begin() [2/2]
template<typename T > const_iterator orgQhull::QhullLinkedList< T >::begin () const inline
{ return begin_node; }
References orgQhull::QhullLinkedList< T >::begin_node.
constBegin()
template<typename T > const_iterator orgQhull::QhullLinkedList< T >::constBegin () const inline
{ return begin_node; }
References orgQhull::QhullLinkedList< T >::begin_node.
Referenced by orgQhull::QhullLinkedList_test::t_const_iterator().
constEnd()
template<typename T > const_iterator orgQhull::QhullLinkedList< T >::constEnd () const inline
{ return end_node; }
References orgQhull::QhullLinkedList< T >::end_node.
Referenced by orgQhull::QhullLinkedList_test::t_const_iterator().
contains()
template<typename T > bool orgQhull::QhullLinkedList< T >::contains (const T & t) const
{
    const_iterator i= begin_node;
    while(i != end_node){
        if(i==t){
            return true;
        }
        i++;
    }
    return false;
}//contains
Referenced by orgQhull::QhullFacetList::contains(), and orgQhull::QhullLinkedList_test::t_search().
count() [1/2]
template<typename T > countT orgQhull::QhullLinkedList< T >::count
{
    const_iterator i= begin_node;
    countT c= 0;
    while(i != end_node){
        c++;
        i++;
    }
    return c;
}//count
Referenced by orgQhull::QhullFacetList::count(), orgQhull::QhullFacetList::count(), orgQhull::QhullLinkedList< T >::size(), orgQhull::QhullLinkedList_test::t_construct(), orgQhull::QhullLinkedList_test::t_convert(), orgQhull::Qhull_test::t_foreach(), orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator(), and orgQhull::QhullLinkedList_test::t_search().
count() [2/2]
template<typename T > countT orgQhull::QhullLinkedList< T >::count (const T & t) const
{
    const_iterator i= begin_node;
    countT c= 0;
    while(i != end_node){
        if(i==t){
            c++;
        }
        i++;
    }
    return c;
}//count
end() [1/2]
template<typename T > iterator orgQhull::QhullLinkedList< T >::end () inline
{ return end_node; }
References orgQhull::QhullLinkedList< T >::end_node.
Referenced by orgQhull::QhullLinkedList< T >::last(), orgQhull::QhullLinkedList< T >::last(), operator<<(), orgQhull::QhullLinkedList_test::t_const_iterator(), and orgQhull::QhullLinkedList_test::t_iterator().
end() [2/2]
template<typename T > const_iterator orgQhull::QhullLinkedList< T >::end () const inline
{ return end_node; }
References orgQhull::QhullLinkedList< T >::end_node.
first() [1/2]
template<typename T > T & orgQhull::QhullLinkedList< T >::first () inline
{ QHULL_ASSERT(!isEmpty()); return begin_node; }
References orgQhull::QhullLinkedList< T >::begin_node, orgQhull::QhullLinkedList< T >::isEmpty(), and QHULL_ASSERT.
first() [2/2]
template<typename T > const T & orgQhull::QhullLinkedList< T >::first () const inline
{ QHULL_ASSERT(!isEmpty()); return begin_node; }
References orgQhull::QhullLinkedList< T >::begin_node, orgQhull::QhullLinkedList< T >::isEmpty(), and QHULL_ASSERT.
Referenced by orgQhull::QhullLinkedList< T >::front(), orgQhull::QhullLinkedList< T >::front(), orgQhull::QhullLinkedList_test::t_const_iterator(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullLinkedList_test::t_element(), orgQhull::QhullLinkedList_test::t_iterator(), orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator(), and orgQhull::QhullPoint_test::t_readonly().
front() [1/2]
template<typename T > T & orgQhull::QhullLinkedList< T >::front () inline
{ return first(); }
References orgQhull::QhullLinkedList< T >::first().
front() [2/2]
template<typename T > const T & orgQhull::QhullLinkedList< T >::front () const inline
{ return first(); }
References orgQhull::QhullLinkedList< T >::first().
Referenced by orgQhull::QhullLinkedList_test::t_element().
isEmpty()
template<typename T > bool orgQhull::QhullLinkedList< T >::isEmpty () const inline
{ return (begin_node==end_node); }
References orgQhull::QhullLinkedList< T >::begin_node, and orgQhull::QhullLinkedList< T >::end_node.
Referenced by orgQhull::QhullLinkedList< T >::first(), orgQhull::QhullLinkedList< T >::first(), orgQhull::QhullLinkedList< T >::last(), orgQhull::QhullLinkedList< T >::last(), orgQhull::QhullLinkedList_test::t_construct(), orgQhull::QhullFacetList_test::t_construct_q(), orgQhull::QhullFacetList_test::t_construct_qh(), orgQhull::QhullFacetList_test::t_convert(), and orgQhull::QhullLinkedList_test::t_convert().
last() [1/2]
template<typename T > T orgQhull::QhullLinkedList< T >::last () inline
{ QHULL_ASSERT(!isEmpty()); return *--end(); }
References orgQhull::QhullLinkedList< T >::end(), orgQhull::QhullLinkedList< T >::isEmpty(), and QHULL_ASSERT.
last() [2/2]
template<typename T > const T orgQhull::QhullLinkedList< T >::last () const inline
{ QHULL_ASSERT(!isEmpty()); return *--end(); }
References orgQhull::QhullLinkedList< T >::end(), orgQhull::QhullLinkedList< T >::isEmpty(), and QHULL_ASSERT.
Referenced by orgQhull::QhullLinkedList< T >::back(), orgQhull::QhullLinkedList< T >::back(), orgQhull::QhullLinkedList_test::t_const_iterator(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullLinkedList_test::t_element(), orgQhull::QhullLinkedList_test::t_iterator(), orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator(), orgQhull::QhullPoint_test::t_readonly(), and orgQhull::QhullLinkedList_test::t_search().
operator!=()
template<typename T > bool orgQhull::QhullLinkedList< T >::operator!= (const QhullLinkedList< T > & o) const inline
{ return !operator==(o); }
References orgQhull::QhullLinkedList< T >::operator==().
operator=()
template<typename T > QhullLinkedList< T > & orgQhull::QhullLinkedList< T >::operator= (const QhullLinkedList< T > & other) inline
Copy assignment copies begin_node and end_node, but not the list elements.
{ begin_node= other.begin_node; end_node= other.end_node; return *this; }
References orgQhull::QhullLinkedList< T >::begin_node, and orgQhull::QhullLinkedList< T >::end_node.
Referenced by orgQhull::QhullFacetList::operator=().
operator==()
template<typename T > bool orgQhull::QhullLinkedList< T >::operator== (const QhullLinkedList< T > & o) const
{
    if(begin_node==l.begin_node){
        return (end_node==l.end_node);
    }
    T i= begin_node;
    T il= l.begin_node;
    while(i != end_node){
        if(i != il){
            return false;
        }
        i= static_cast<T>(i.next());
        il= static_cast<T>(il.next());
    }
    if(il != l.end_node){
        return false;
    }
    return true;
}//operator==
References orgQhull::QhullLinkedList< T >::begin_node, and orgQhull::QhullLinkedList< T >::end_node.
Referenced by orgQhull::QhullLinkedList< T >::operator!=().
size()
template<typename T > size_t orgQhull::QhullLinkedList< T >::size () const inline
{ return count(); }
References orgQhull::QhullLinkedList< T >::count().
Referenced by orgQhull::QhullLinkedList_test::t_construct(), and orgQhull::QhullLinkedList_test::t_convert().
toStdVector()
template<typename T > std::vector< T > orgQhull::QhullLinkedList< T >::toStdVector
{
    std::vector<T> tmp;
    std::copy(constBegin(), constEnd(), std::back_inserter(tmp));
    return tmp;
}//toStdVector
Referenced by orgQhull::QhullLinkedList_test::t_convert().
Member Data Documentation
begin_node
template<typename T > T orgQhull::QhullLinkedList< T >::begin_node private
Referenced by orgQhull::QhullLinkedList< T >::begin(), orgQhull::QhullLinkedList< T >::begin(), orgQhull::QhullLinkedList< T >::constBegin(), orgQhull::QhullLinkedList< T >::first(), orgQhull::QhullLinkedList< T >::first(), orgQhull::QhullLinkedList< T >::isEmpty(), orgQhull::QhullLinkedList< T >::operator=(), and orgQhull::QhullLinkedList< T >::operator==().
end_node
template<typename T > T orgQhull::QhullLinkedList< T >::end_node private
Referenced by orgQhull::QhullLinkedList< T >::constEnd(), orgQhull::QhullLinkedList< T >::end(), orgQhull::QhullLinkedList< T >::end(), orgQhull::QhullLinkedList< T >::isEmpty(), orgQhull::QhullLinkedList< T >::operator=(), and orgQhull::QhullLinkedList< T >::operator==().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullLinkedList.h