OrcaSlicer: orgQhull::RboxPoints_test Class Reference
orgQhull::RboxPoints_test Class Reference
Test C++ interface to Rbox See eg/q_test for tests of rbox commands.
Public Slots
Test slots
! List of failed tests
void cleanup ()
Executed after each test.
Public Member Functions
Helper
void recordFailedTest ()
Static Public Member Functions
Class functions
static void deleteTests ()
static int runTests (QStringList arguments)
Static Protected Attributes
Class globals
static QList< RoadTest * > s_testcases
static int s_test_count = 0
! List of testcases to execute. Initialized via add_...()
static int s_test_fail = 0
! Total number of tests executed
static QStringList s_failed_tests
! Number of failed tests
Private Slots
Test slots
void t_construct ()
void t_error ()
void t_test ()
void t_getSet ()
void t_foreach ()
void t_change ()
void t_ostream ()
Detailed Description
Test C++ interface to Rbox See eg/q_test for tests of rbox commands.
Member Function Documentation
cleanup
void orgQhull::RoadTest::cleanup () slot inherited
Executed after each test.
{
    s_test_count++;
    if(QTest::currentTestFailed()){
        recordFailedTest();
    }
}//cleanup
References orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::s_test_count.
Referenced by orgQhull::Qhull_test::cleanup(), orgQhull::QhullFacet_test::cleanup(), orgQhull::QhullFacetList_test::cleanup(), orgQhull::QhullFacetSet_test::cleanup(), orgQhull::QhullHyperplane_test::cleanup(), orgQhull::QhullLinkedList_test::cleanup(), orgQhull::QhullPoint_test::cleanup(), orgQhull::QhullPoints_test::cleanup(), orgQhull::QhullPointSet_test::cleanup(), orgQhull::QhullRidge_test::cleanup(), orgQhull::QhullSet_test::cleanup(), orgQhull::QhullVertex_test::cleanup(), and orgQhull::QhullVertexSet_test::cleanup().
deleteTests()
void orgQhull::RoadTest::deleteTests () static inherited
{
    foreach(RoadTest *testcase, s_testcases){
        delete testcase;
    }
    s_failed_tests.clear();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
recordFailedTest()
void orgQhull::RoadTest::recordFailedTest () inherited
{
    s_test_fail++;
    QString className= metaObject()->className();
    s_failed_tests << className + "::" + QTest::currentTestFunction();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_test_fail.
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
runTests()
int orgQhull::RoadTest::runTests (QStringList arguments) static inherited
{
    int result= 0; // assume success
    foreach(RoadTest *testcase, s_testcases){
        try{
            result += QTest::qExec(testcase, arguments);
        }catch(const std::exception &e){
            cout << "FAIL!  : Threw error ";
            cout << e.what() << endl;
    s_test_count++;
            testcase->recordFailedTest();
            // Qt 4.5.2 OK.  In Qt 4.3.3, qtestcase did not clear currentTestObject
        }
    }
    if(s_test_fail){
        cout << "Failed " << s_test_fail << " of " << s_test_count << " tests.\n";
        cout << s_failed_tests.join("\n").toLocal8Bit().constData() << std::endl;
    }else{
        cout << "Passed " << s_test_count << " tests.\n";
    }
    return result;
}//runTests
References orgQhull::RoadTest::recordFailedTest(), orgQhull::RoadTest::s_failed_tests, orgQhull::RoadTest::s_test_count, orgQhull::RoadTest::s_test_fail, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
t_change
void orgQhull::RboxPoints_test::t_change () private slot
{
    RboxPoints rp("c D2");
    stringstream s;
    s << "4 count" << endl;
    s << "2 dimension" << endl;
    s << "1 2 3 4 5 6 7 8" << endl;
    rp.appendPoints(s);
    QCOMPARE(rp.count(), 8);
    orgQhull::Coordinates::Iterator ci= rp.beginCoordinates(7);
    QCOMPARE(*ci, 7.0);
    try{
        stringstream s2;
        s2 << "4 count" << endl;
        s2 << "2 dimension" << endl;
        s2 << "1 2 3 4 5 6 7 " << endl;
        rp.appendPoints(s2);
        QFAIL("incomplete appendPoints() did not fail.");
    }catch (const std::exception &e) {
        cout << "INFO   : Caught " << e.what();
    }
    RboxPoints rp2;
    rp2.append(rp);
    QCOMPARE(rp2.count(), 8);
    orgQhull::Coordinates::ConstIterator cci2= rp2.beginCoordinates(6);
    QCOMPARE(*(cci2+1), 6.0);
    rp2.appendPoints("D2 10 P0");
    QCOMPARE(rp2.count(), 19);
    orgQhull::Coordinates::ConstIterator cie= rp2.beginCoordinates(8);
    QCOMPARE(*cie, 0.0);
    RboxPoints rp3;
    coordT points[] = { 0, 1,1,0,1,1,0,0};
    rp3.setDimension(2);
    rp3.append(8,points);
    QCOMPARE(rp3.count(), 4);
    orgQhull::Coordinates::Iterator ci3= rp3.beginCoordinates(3);
    QCOMPARE(*ci3, 0.0);
}//t_change
References orgQhull::PointCoordinates::append(), orgQhull::RboxPoints::appendPoints(), orgQhull::PointCoordinates::beginCoordinates(), coordT, orgQhull::QhullPoints::count(), and orgQhull::PointCoordinates::setDimension().
t_construct
void orgQhull::RboxPoints_test::t_construct () private slot
{
    RboxPoints rp;
    QCOMPARE(rp.dimension(), 0);
    QCOMPARE(rp.count(), 0);
    QVERIFY(QString::fromStdString(rp.comment()) != QString(""));
    QVERIFY(rp.isEmpty());
    QVERIFY(!rp.hasRboxMessage());
    QCOMPARE(rp.rboxStatus(), qh_ERRnone);
    QCOMPARE(QString::fromStdString(rp.rboxMessage()), QString("rbox warning: no points generated\n"));
    RboxPoints rp2("c"); // 3-d cube
    QCOMPARE(rp2.dimension(), 3);
    QCOMPARE(rp2.count(), 8);
    QCOMPARE(QString::fromStdString(rp2.comment()), QString("rbox \"c\""));
    QVERIFY(!rp2.isEmpty());
    QVERIFY(!rp2.hasRboxMessage());
    QCOMPARE(rp2.rboxStatus(), qh_ERRnone);
    QCOMPARE(QString::fromStdString(rp2.rboxMessage()), QString("rbox: OK\n"));
}//t_construct
References orgQhull::PointCoordinates::comment(), orgQhull::QhullPoints::count(), orgQhull::QhullPoints::dimension(), orgQhull::RboxPoints::hasRboxMessage(), orgQhull::QhullPoints::isEmpty(), qh_ERRnone, orgQhull::RboxPoints::rboxMessage(), and orgQhull::RboxPoints::rboxStatus().
t_error
void orgQhull::RboxPoints_test::t_error () private slot
{
    RboxPoints rp;
    try{
        rp.appendPoints("D0 c");
        QFAIL("'D0 c' did not fail.");
    }catch (const std::exception &e) {
        const char *s= e.what();
        cout << "INFO   : Caught " << s;
        QCOMPARE(QString(s).left(6), QString("QH6189"));
        QVERIFY(rp.hasRboxMessage());
        QCOMPARE(QString::fromStdString(rp.rboxMessage()).left(8), QString("rbox err"));
        QCOMPARE(rp.rboxStatus(), 6189);
        rp.clearRboxMessage();
        QVERIFY(!rp.hasRboxMessage());
    }
    try{
        RboxPoints rp2;
        rp2.setDimension(-1);
        QFAIL("setDimension(-1) did not fail.");
    }catch (const RoadError &e) {
        const char *s= e.what();
        cout << "INFO   : Caught " << s;
        QCOMPARE(QString(s).left(7), QString("QH10062"));
        QCOMPARE(e.errorCode(), 10062);
        QCOMPARE(QString::fromStdString(e.what()), QString(s));
        RoadLogEvent logEvent= e.roadLogEvent();
        QCOMPARE(logEvent.int1(), -1);
    }
}//t_error
References orgQhull::RboxPoints::appendPoints(), orgQhull::RboxPoints::clearRboxMessage(), orgQhull::RboxPoints::hasRboxMessage(), orgQhull::RoadLogEvent::int1(), orgQhull::RboxPoints::rboxMessage(), orgQhull::RboxPoints::rboxStatus(), and orgQhull::PointCoordinates::setDimension().
t_foreach
void orgQhull::RboxPoints_test::t_foreach () private slot
{
    RboxPoints rp("c");
    Coordinates::ConstIterator cci= rp.beginCoordinates();
    orgQhull::Coordinates::Iterator ci= rp.beginCoordinates();
    QCOMPARE(*cci, -0.5);
    QCOMPARE(*ci, *cci);
    int i=1;
    while(++cci<rp.endCoordinates()){
        QVERIFY(++ci<rp.endCoordinates());
        QCOMPARE(*cci, *ci);
        i++;
    }
    QVERIFY(++ci==rp.endCoordinates());
    QCOMPARE(i, 8*3);
    orgQhull::Coordinates::Iterator ci4= rp.beginCoordinates(4);
    QCOMPARE(rp.endCoordinates()-ci4, 4*3);
    orgQhull::Coordinates::ConstIterator cci4= rp.beginCoordinates(4);
    orgQhull::Coordinates::ConstIterator cci5= rp.endCoordinates();
    QCOMPARE(cci5-cci4, 4*3);
}//t_foreach
References orgQhull::PointCoordinates::beginCoordinates(), and orgQhull::PointCoordinates::endCoordinates().
t_getSet
void orgQhull::RboxPoints_test::t_getSet () private slot
{
    // comment -- t_construct
    // count -- t_construct
    // dimension -- t_construct
    RboxPoints rp;
    QCOMPARE(rp.dimension(), 0);
    rp.setDimension(2);
    QCOMPARE(rp.dimension(), 2);
    try{
        rp.setDimension(102);
        QFAIL("setDimension(102) did not fail.");
    }catch (const std::exception &e) {
        cout << "INFO   : Caught " << e.what();
    }
    QCOMPARE(rp.newCount(), 0);
    rp.appendPoints("D2 P1 P2");
    QCOMPARE(rp.count(), 2);
    QCOMPARE(rp.newCount(), 2); // From previous appendPoints();
    PointCoordinates pc(rp.qh(), 2, "Test qh() and <<");
    pc << 1.0 << 0.0 << 2.0 << 0.0;
    QCOMPARE(pc.dimension(), 2);
    QCOMPARE(pc.count(), 2);
    QVERIFY(rp==pc);
    rp.setNewCount(10);  // Normally only used by appendPoints for rbox processing
    QCOMPARE(rp.newCount(), 10);
    rp.reservePoints();
    QVERIFY(rp==pc);
}//t_getSet
References orgQhull::RboxPoints::appendPoints(), orgQhull::QhullPoints::count(), orgQhull::QhullPoints::dimension(), orgQhull::RboxPoints::newCount(), orgQhull::QhullPoints::qh(), orgQhull::RboxPoints::reservePoints(), orgQhull::PointCoordinates::setDimension(), and orgQhull::RboxPoints::setNewCount().
t_ostream
void orgQhull::RboxPoints_test::t_ostream () private slot
{
    RboxPoints rp("c D2");
    ostringstream oss;
    oss << rp;
    string s= oss.str();
    QString qs= QString::fromStdString(s);
    QCOMPARE(qs.count("-0.5"), 4);
}//t_ostream
t_test
void orgQhull::RboxPoints_test::t_test () private slot
{
    // isEmpty -- t_construct
}//t_test
Member Data Documentation
s_failed_tests
QStringList orgQhull::RoadTest::s_failed_tests static protected inherited
! Number of failed tests
Referenced by orgQhull::RoadTest::deleteTests(), orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_test_count
int orgQhull::RoadTest::s_test_count = 0 static protected inherited
! List of testcases to execute. Initialized via add_...()
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
s_test_fail
int orgQhull::RoadTest::s_test_fail = 0 static protected inherited
! Total number of tests executed
Referenced by orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_testcases
QList< RoadTest * > orgQhull::RoadTest::s_testcases static protected inherited
Referenced by orgQhull::RoadTest::RoadTest(), orgQhull::RoadTest::deleteTests(), and orgQhull::RoadTest::runTests().
The documentation for this class was generated from the following file:
src/qhull/src/qhulltest/RboxPoints_test.cpp