OrcaSlicer: TabCtrl Class Reference
TabCtrl Class Reference
#include <src/slic3r/GUI/Widgets/TabCtrl.hpp>
Public Member Functions
TabCtrl (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
~TabCtrl ()
virtual bool SetFont (wxFont const &font) override
int AppendItem (const wxString &item, int image=-1, int selImage=-1, void *clientData=nullptr)
bool DeleteItem (int item)
void DeleteAllItems ()
unsigned int GetCount () const
int GetSelection () const
void SelectItem (int item)
void Unselect ()
virtual void Rescale ()
wxString GetItemText (unsigned int item) const
void SetItemText (unsigned int item, wxString const &value)
bool GetItemBold (unsigned int item) const
void SetItemBold (unsigned int item, bool bold)
void * GetItemData (unsigned int item) const
void SetItemData (unsigned int item, void *clientData)
void AssignImageList (wxImageList *imageList)
void SetItemTextColour (unsigned int item, const StateColor &col)
int GetFirstVisibleItem () const
int GetNextVisible (int item) const
bool IsVisible (unsigned int item) const
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void SetCornerRadius (double radius)
void SetBorderWidth (int width)
void SetBorderColor (StateColor const &color)
void SetBorderColorNormal (wxColor const &color)
void SetBackgroundColor (StateColor const &color)
void SetBackgroundColorNormal (wxColor const &color)
void SetBackgroundColor2 (StateColor const &color)
Static Public Member Functions
static wxColor GetParentBackgroundColor (wxWindow *parent)
Protected Member Functions
void eraseEvent (wxEraseEvent &evt)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
Protected Attributes
double radius
int border_width = 1
StateHandler state_handler
StateColor border_color
StateColor background_color
StateColor background_color2
Private Member Functions
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
void relayout ()
void buttonClicked (wxCommandEvent &event)
void keyDown (wxKeyEvent &event)
void doRender (wxDC &dc) override
bool sendTabCtrlEvent (bool changing=false)
Private Attributes
std::vector< Button * > btns
wxImageList * images = nullptr
wxBoxSizer * sizer = nullptr
int sel = -1
wxFont bold
Detailed Description
Constructor & Destructor Documentation
TabCtrl()
TabCtrl::TabCtrl (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
    : StaticBox(parent, id, pos, size, style)
{
#if 0
    radius = 5;
#else
    radius = 1;
#endif
    border_width = 1;
    SetBorderColor(0xcecece);
    sizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->AddSpacer(10);
    SetSizer(sizer);
    Bind(wxEVT_COMMAND_BUTTON_CLICKED, &TabCtrl::buttonClicked, this);
    //wxString reason;
    //IsTransparentBackgroundSupported(&reason);
}
References StaticBox::border_width, buttonClicked(), StaticBox::radius, StaticBox::SetBorderColor(), and sizer.
~TabCtrl()
TabCtrl::~TabCtrl ()
{
    delete images;
}
References images.
Member Function Documentation
AppendItem()
int TabCtrl::AppendItem (const wxString & item, int image = -1, int selImage = -1, void * clientData = nullptr)
{
    Button * btn = new Button();
    btn->Create(this, item, "", wxBORDER_NONE);
    btn->SetFont(GetFont());
    btn->SetTextColor(StateColor(
        std::make_pair(0x6B6B6C, (int) StateColor::NotChecked),
        std::make_pair(*wxLIGHT_GREY, (int) StateColor::Normal)));
    btn->SetBackgroundColor(StateColor());
    btn->SetCornerRadius(0);
    btn->SetPaddingSize({TAB_BUTTON_PADDING});
    btns.push_back(btn);
    if (btns.size() > 1)
        sizer->GetItem(sizer->GetItemCount() - 1)->SetMinSize({0, 0});
    sizer->Add(btn, 0, wxALIGN_CENTER_VERTICAL | wxALL, TAB_BUTTON_SPACE * 2);
    sizer->AddStretchSpacer(1);
    relayout();
    return btns.size() - 1;
}
References btns, Button::Create(), StateColor::Normal, StateColor::NotChecked, relayout(), StaticBox::SetBackgroundColor(), StaticBox::SetCornerRadius(), Button::SetFont(), Button::SetPaddingSize(), Button::SetTextColor(), sizer, TAB_BUTTON_PADDING, and TAB_BUTTON_SPACE.
Referenced by Slic3r::GUI::Tab::rebuild_page_tree().
AssignImageList()
void TabCtrl::AssignImageList (wxImageList * imageList)
{
    if (images == imageList) return;
    delete images;
    images = imageList;
}
References images.
Referenced by Slic3r::GUI::Tab::create_preset_tab().
buttonClicked()
void TabCtrl::buttonClicked (wxCommandEvent & event) private
{
    SetFocus();
    auto btn  = event.GetEventObject();
    auto iter = std::find(btns.begin(), btns.end(), btn);
    SelectItem(iter == btns.end() ? -1 : iter - btns.begin());
}
References btns, and SelectItem().
Referenced by TabCtrl().
Create()
bool StaticBox::Create (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0) inherited
{
    if (style & wxBORDER_NONE)
        border_width = 0;
    wxWindow::Create(parent, id, pos, size, style);
    state_handler.attach({&border_color, &background_color, &background_color2});
    state_handler.update_binds();
    SetBackgroundColour(GetParentBackgroundColor(parent));
    return true;
}
References StateHandler::attach(), StaticBox::background_color, StaticBox::background_color2, StaticBox::border_color, StaticBox::border_width, StaticBox::GetParentBackgroundColor(), size, StaticBox::state_handler, style, and StateHandler::update_binds().
Referenced by FanSwitchButton::FanSwitchButton(), ImageSwitchButton::ImageSwitchButton(), StaticBox::StaticBox(), Button::Create(), SpinInput::Create(), TextInput::Create(), and TempInput::Create().
DeleteAllItems()
void TabCtrl::DeleteAllItems ()
{
    sizer->Clear(true);
    sizer->AddSpacer(10);
    btns.clear();
    if (sel >= 0) {
        sel = -1;
        sendTabCtrlEvent();
    }
}
References btns, sel, sendTabCtrlEvent(), and sizer.
Referenced by Slic3r::GUI::Tab::rebuild_page_tree().
DeleteItem()
bool TabCtrl::DeleteItem (int item)
{
    return false;
}
doRender()
void TabCtrl::doRender (wxDC & dc) override private virtual
Reimplemented from StaticBox.
{
    wxSize size = GetSize();
    int states = state_handler.states();
    if (sel < 0) { return; }
    auto x1 = btns[sel]->GetPosition().x;
    auto x2 = x1 + btns[sel]->GetSize().x;
    const int BS2 = (1 + border_width) / 2;
#if 0
    const int BS = border_width / 2;
    x1 -= TAB_BUTTON_SPACE; x2 += TAB_BUTTON_SPACE;
    dc.SetPen(wxPen(border_color.colorForStates(states), border_width));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawLine(0, size.y - BS2, x1 - radius + BS2, size.y - BS2);
    dc.DrawArc(x1 - radius, size.y, x1, size.y - radius, x1 - radius, size.y - radius);
    dc.DrawLine(x1, size.y - radius, x1, radius);
    dc.DrawArc(x1 + radius, 0, x1, radius, x1 + radius, radius);
    dc.DrawLine(x1 + radius, BS, x2 - radius, BS);
    dc.DrawArc(x2, radius, x2 - radius, 0, x2 - radius, radius);
    dc.DrawLine(x2, radius, x2, size.y - radius);
    dc.DrawArc(x2, size.y - radius, x2 + radius, size.y, x2 + radius, size.y - radius);
    dc.DrawLine(x2 + radius - BS2, size.y - BS2, size.x, size.y - BS2);
#else
    dc.SetPen(wxPen(border_color.colorForStates(states), border_width));
    dc.DrawLine(0, size.y - BS2, size.x, size.y - BS2);
    wxColour c(0xf2, 0x75, 0x4e, 0xff);
    dc.SetPen(wxPen(c, 1));
    dc.SetBrush(c);
    dc.DrawRoundedRectangle(x1 - radius, size.y - BS2 - border_width * 3, x2 + radius * 2 - x1, border_width * 3, radius);
#endif
}
References StaticBox::border_color, StaticBox::border_width, btns, StateColor::colorForStates(), StaticBox::radius, sel, size, StaticBox::state_handler, StateHandler::states(), and TAB_BUTTON_SPACE.
DoSetSize()
void TabCtrl::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) private virtual
{
    wxWindow::DoSetSize(x, y, width, height, sizeFlags);
    if (sizeFlags & wxSIZE_USE_EXISTING) return;
    relayout();
}
References relayout().
eraseEvent()
void StaticBox::eraseEvent (wxEraseEvent & evt) protected inherited
{
    // for transparent background, but not work
#ifdef __WXMSW__
    wxDC *dc = evt.GetDC();
    wxSize size = GetSize();
    wxClientDC dc2(GetParent());
    dc->Blit({0, 0}, size, &dc2, GetPosition());
#endif
}
References size.
GetCount()
unsigned int TabCtrl::GetCount () const
{ return btns.size(); }
References btns.
GetFirstVisibleItem()
int TabCtrl::GetFirstVisibleItem () const
{
    return btns.size() == 0 ? -1 : 0;
}
References btns.
Referenced by Slic3r::GUI::Tab::rebuild_page_tree(), and Slic3r::GUI::Tab::restore_last_select_item().
GetItemBold()
bool TabCtrl::GetItemBold (unsigned int item) const
{
    if (item >= btns.size()) return false;
    return btns[item]->GetFont() == bold;
}
References bold, and btns.
GetItemData()
void * TabCtrl::GetItemData (unsigned int item) const
{
    if (item >= btns.size()) return nullptr;
    return btns[item]->GetClientData();
}
References btns.
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed().
GetItemText()
wxString TabCtrl::GetItemText (unsigned int item) const
{
    return item < btns.size() ? btns[item]->GetLabel() : wxString{};
}
References btns.
Referenced by Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::update_current_page_in_background().
GetNextVisible()
int TabCtrl::GetNextVisible (int item) const
{
    return ++item < btns.size() ? item : -1;
}
References btns.
GetParentBackgroundColor()
wxColor StaticBox::GetParentBackgroundColor (wxWindow * parent) static inherited
{
    if (auto box = dynamic_cast<StaticBox*>(parent)) {
        if (box->background_color.count() > 0) {
            if (box->background_color2.count() == 0)
                return box->background_color.defaultColor();
            auto s = box->background_color.defaultColor();
            auto e = box->background_color2.defaultColor();
            int r = (s.Red() + e.Red()) / 2;
            int g = (s.Green() + e.Green()) / 2;
            int b = (s.Blue() + e.Blue()) / 2;
            return wxColor(r, g, b);
        }
    }
    if (parent)
        return parent->GetBackgroundColour();
    return *wxWHITE;
}
Referenced by Label::Label(), ScalableButton::ScalableButton(), SwitchButton::SwitchButton(), StaticBox::Create(), and SwitchButton::Rescale().
GetSelection()
int TabCtrl::GetSelection () const
{ return sel; }
References sel.
Referenced by Slic3r::GUI::Tab::create_preset_tab(), keyDown(), Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::unselect_tree_item().
IsVisible()
bool TabCtrl::IsVisible (unsigned int item) const
{
    return true;
}
keyDown()
void TabCtrl::keyDown (wxKeyEvent & event) private
{
    switch (event.GetKeyCode()) {
    case WXK_UP:
    case WXK_DOWN:
    case WXK_LEFT:
    case WXK_RIGHT:
        if ((event.GetKeyCode() == WXK_UP || event.GetKeyCode() == WXK_LEFT) && GetSelection() > 0) {
            SelectItem(GetSelection() - 1);
        } else if ((event.GetKeyCode() == WXK_DOWN || event.GetKeyCode() == WXK_RIGHT) && GetSelection() + 1 < btns.size()) {
            SelectItem(GetSelection() + 1);
        }
        break;
    }
}
References btns, GetSelection(), and SelectItem().
paintEvent()
void StaticBox::paintEvent (wxPaintEvent & evt) protected inherited
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    render(dc);
}
References StaticBox::render().
relayout()
void TabCtrl::relayout () private
{
    int offset = 10;
    int item = sel + 1;
    int first = 0;
    for (int i = 0; i < item; ++i)
        offset += btns[i]->GetMinSize().x + TAB_BUTTON_SPACE * 2;
    if (item < btns.size())
        offset += btns[item]->GetMinSize().x + TAB_BUTTON_SPACE * 2;
    int  width = GetSize().x;
    auto sizer = GetSizer();
    for (int i = 0; i < btns.size(); ++i) {
        auto size = btns[i]->GetMinSize().x + TAB_BUTTON_SPACE * 2;
        if (i < sel && offset > width) {
            sizer->Show(i * 2 + 1, false);
            sizer->Show(i * 2 + 2, false);
            offset -= size;
            first = i + 1;
        } else if (i <= item) {
            sizer->Show(i * 2 + 1, true);
            sizer->Show(i * 2 + 2, true);
        } else if (offset <= width) {
            sizer->Show(i * 2 + 1, true);
            sizer->Show(i * 2 + 2, true);
            offset += size;
            item = i;
        } else {
            sizer->Show(i * 2 + 1, false);
            sizer->Show(i * 2 + 2, false);
        }
        sizer->GetItem(i * 2 + 2)->SetMinSize({0, 0});
    }
    if (item >= btns.size())
        -- item;
    // Keep spacing 2 ~ 10 TAB_BUTTON_SPACE
    int b = GetSize().x - offset - 10 - (item + 1 - first) * TAB_BUTTON_SPACE * 8;
    sizer->GetItem(item * 2 + 2)->SetMinSize({b > 0 ? b : 0, 0});
    sizer->Layout();
}
References btns, sel, size, sizer, and TAB_BUTTON_SPACE.
Referenced by AppendItem(), DoSetSize(), and SelectItem().
render()
void StaticBox::render (wxDC & dc) protected inherited
{
#ifdef __WXMSW__
    if (radius == 0) {
        doRender(dc);
        return;
    }
  wxSize size = GetSize();
    if (size.x <= 0 || size.y <= 0)
        return;
    wxMemoryDC memdc;
    wxBitmap bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    //memdc.Blit({0, 0}, size, &dc, {0, 0});
    memdc.SetBackground(wxBrush(GetBackgroundColour()));
    memdc.Clear();
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
  dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References StaticBox::doRender(), StaticBox::radius, and size.
Referenced by StaticBox::paintEvent(), Button::render(), ImageSwitchButton::render(), FanSwitchButton::render(), SpinInput::render(), TempInput::render(), and TextInput::render().
Rescale()
void TabCtrl::Rescale () virtual
{
    for (auto & b : btns)
        b->Rescale();
}
References btns.
SelectItem()
void TabCtrl::SelectItem (int item)
{
    if (item == sel || !sendTabCtrlEvent(true))
        return;
    if (sel >= 0) {
        wxCommandEvent e(wxEVT_CHECKBOX);
        auto b = btns[sel];
        e.SetEventObject(b);
        b->GetEventHandler()->ProcessEvent(e);
    }
    sel = item;
    if (sel >= 0) {
        wxCommandEvent e(wxEVT_CHECKBOX);
        auto b = btns[sel];
        e.SetEventObject(b);
        b->GetEventHandler()->ProcessEvent(e);
    }
    sendTabCtrlEvent();
    relayout();
    Refresh();
}
References btns, relayout(), sel, and sendTabCtrlEvent().
Referenced by buttonClicked(), keyDown(), Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::restore_last_select_item(), and Unselect().
sendTabCtrlEvent()
bool TabCtrl::sendTabCtrlEvent (bool changing = false) private
{
    wxCommandEvent event(changing ? wxEVT_TAB_SEL_CHANGING : wxEVT_TAB_SEL_CHANGED, GetId());
    event.SetEventObject(this);
    event.SetInt(sel);
    GetEventHandler()->ProcessEvent(event);
    return true;
}
References sel.
Referenced by DeleteAllItems(), and SelectItem().
SetBackgroundColor()
void StaticBox::SetBackgroundColor (StateColor const & color) inherited
{
    background_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::ParamsPanel::ParamsPanel(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::PublishDialog::create_publish_step_sizer(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::InputIpAddressDialog::on_check_ip_address_failed(), Slic3r::GUI::ColorPickerPopup::on_custom_clr_picker(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), ButtonsListCtrl::OnPaint(), TabButtonsListCtrl::OnPaint(), Slic3r::GUI::ColorPickerPopup::set_def_colour(), and Slic3r::GUI::MonitorPanel::show_status().
SetBackgroundColor2()
void StaticBox::SetBackgroundColor2 (StateColor const & color) inherited
{
    background_color2 = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color2, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::ParamsPanel::ParamsPanel().
SetBackgroundColorNormal()
void StaticBox::SetBackgroundColorNormal (wxColor const & color) inherited
{
    background_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::background_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderColor()
void StaticBox::SetBorderColor (StateColor const & color) inherited
{
    border_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::border_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), TabCtrl(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), and Slic3r::GUI::MonitorPanel::show_status().
SetBorderColorNormal()
void StaticBox::SetBorderColorNormal (wxColor const & color) inherited
{
    border_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::border_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderWidth()
void StaticBox::SetBorderWidth (int width) inherited
{
    border_width = width;
    Refresh();
}
References StaticBox::border_width.
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::StatusBasePanel::create_bed_control(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), and Slic3r::GUI::StatusBasePanel::create_misc_control().
SetCornerRadius()
void StaticBox::SetCornerRadius (double radius) inherited
{
    this->radius = radius;
    Refresh();
}
References StaticBox::radius.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::ProgressDialog::Create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), SpinInput::createButton(), Slic3r::GUI::StatusPanel::init_scaled_buttons(), Slic3r::GUI::AMSControl::init_scaled_buttons(), Slic3r::GUI::MonitorPanel::init_tabpanel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::MonitorPanel::msw_rescale(), Slic3r::GUI::ConnectPrinterDialog::on_dpi_changed(), Slic3r::GUI::RecenterDialog::on_dpi_changed(), and Slic3r::GUI::SelectMachineDialog::on_dpi_changed().
SetFont()
bool TabCtrl::SetFont (wxFont const & font) override virtual
{
    StaticBox::SetFont(font);
    bold = font.Bold();
    for (size_t i = 0; i < btns.size(); ++i)
        btns[i]->SetFont(i == sel ? bold : font);
    return true;
}
References bold, btns, sel, and SetFont().
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and SetFont().
SetItemBold()
void TabCtrl::SetItemBold (unsigned int item, bool bold)
{
    if (item >= btns.size()) return;
    btns[item]->SetFont(bold ? this->bold : GetFont());
    btns[item]->Rescale();
}
References bold, and btns.
Referenced by Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::unselect_tree_item().
SetItemData()
void TabCtrl::SetItemData (unsigned int item, void * clientData)
{
    if (item >= btns.size()) return;
    btns[item]->SetClientData(clientData);
}
References btns.
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed().
SetItemText()
void TabCtrl::SetItemText (unsigned int item, wxString const & value)
{
    if (item >= btns.size()) return;
    btns[item]->SetLabel(value);
}
References btns.
SetItemTextColour()
void TabCtrl::SetItemTextColour (unsigned int item, const StateColor & col)
{
    if (item >= btns.size()) return;
    btns[item]->SetTextColor(col);
}
References btns, and col().
Referenced by Slic3r::GUI::Tab::rebuild_page_tree().
Unselect()
void TabCtrl::Unselect ()
{
    SelectItem(-1);
}
References SelectItem().
Referenced by Slic3r::GUI::Tab::rebuild_page_tree(), and Slic3r::GUI::Tab::unselect_tree_item().
Member Data Documentation
background_color
StateColor StaticBox::background_color protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), StaticBox::SetBackgroundColor(), and StaticBox::SetBackgroundColorNormal().
background_color2
StateColor StaticBox::background_color2 protected inherited
Referenced by StaticBox::Create(), StaticBox::doRender(), and StaticBox::SetBackgroundColor2().
bold
wxFont TabCtrl::bold private
Referenced by GetItemBold(), SetFont(), and SetItemBold().
border_color
StateColor StaticBox::border_color protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), doRender(), StaticBox::SetBorderColor(), and StaticBox::SetBorderColorNormal().
border_width
int StaticBox::border_width = 1 protected inherited
Referenced by StepCtrl::StepCtrl(), StepIndicator::StepIndicator(), TabCtrl(), StaticBox::Create(), StaticBox::doRender(), doRender(), and StaticBox::SetBorderWidth().
btns
std::vector<Button*> TabCtrl::btns private
Referenced by AppendItem(), buttonClicked(), DeleteAllItems(), doRender(), GetCount(), GetFirstVisibleItem(), GetItemBold(), GetItemData(), GetItemText(), GetNextVisible(), keyDown(), relayout(), Rescale(), SelectItem(), SetFont(), SetItemBold(), SetItemData(), SetItemText(), and SetItemTextColour().
images
wxImageList* TabCtrl::images = nullptr private
Referenced by ~TabCtrl(), and AssignImageList().
radius
double StaticBox::radius protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StepCtrlBase::StepCtrlBase(), TabCtrl(), StaticBox::doRender(), doRender(), StaticBox::render(), and StaticBox::SetCornerRadius().
sel
int TabCtrl::sel = -1 private
Referenced by DeleteAllItems(), doRender(), GetSelection(), relayout(), SelectItem(), sendTabCtrlEvent(), and SetFont().
sizer
wxBoxSizer* TabCtrl::sizer = nullptr private
Referenced by TabCtrl(), AppendItem(), DeleteAllItems(), and relayout().
state_handler
StateHandler StaticBox::state_handler protected inherited
Referenced by Button::Create(), StaticBox::Create(), StaticBox::doRender(), StepCtrl::doRender(), StepIndicator::doRender(), doRender(), Button::GetValue(), Button::render(), ImageSwitchButton::render(), FanSwitchButton::render(), StaticBox::SetBackgroundColor(), StaticBox::SetBackgroundColor2(), StaticBox::SetBorderColor(), Button::SetTextColor(), ImageSwitchButton::SetTextColor(), FanSwitchButton::SetTextColor(), and Button::SetValue().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/TabCtrl.hpp
src/slic3r/GUI/Widgets/TabCtrl.cpp