OrcaSlicer: src/expat/xmltok.h File Reference
xmltok.h File Reference
Classes
struct position
struct ATTRIBUTE
struct encoding
struct INIT_ENCODING
Macros
#define XML_TOK_TRAILING_RSQB
#define XML_TOK_NONE -4 /* The string to be scanned is empty */
#define XML_TOK_TRAILING_CR
#define XML_TOK_PARTIAL_CHAR -2 /* only part of a multibyte sequence */
#define XML_TOK_PARTIAL -1 /* only part of a token */
#define XML_TOK_INVALID 0
#define XML_TOK_START_TAG_WITH_ATTS 1
#define XML_TOK_START_TAG_NO_ATTS 2
#define XML_TOK_EMPTY_ELEMENT_WITH_ATTS 3 /* empty element tag <e/> */
#define XML_TOK_EMPTY_ELEMENT_NO_ATTS 4
#define XML_TOK_END_TAG 5
#define XML_TOK_DATA_CHARS 6
#define XML_TOK_DATA_NEWLINE 7
#define XML_TOK_CDATA_SECT_OPEN 8
#define XML_TOK_ENTITY_REF 9
#define XML_TOK_CHAR_REF 10 /* numeric character reference */
#define XML_TOK_PI 11 /* processing instruction */
#define XML_TOK_XML_DECL 12 /* XML decl or text decl */
#define XML_TOK_COMMENT 13
#define XML_TOK_BOM 14 /* Byte order mark */
#define XML_TOK_PROLOG_S 15
#define XML_TOK_DECL_OPEN 16 /* <!foo */
#define XML_TOK_DECL_CLOSE 17 /* > */
#define XML_TOK_NAME 18
#define XML_TOK_NMTOKEN 19
#define XML_TOK_POUND_NAME 20 /* #name */
#define XML_TOK_OR 21 /* | */
#define XML_TOK_PERCENT 22
#define XML_TOK_OPEN_PAREN 23
#define XML_TOK_CLOSE_PAREN 24
#define XML_TOK_OPEN_BRACKET 25
#define XML_TOK_CLOSE_BRACKET 26
#define XML_TOK_LITERAL 27
#define XML_TOK_PARAM_ENTITY_REF 28
#define XML_TOK_INSTANCE_START 29
#define XML_TOK_NAME_QUESTION 30 /* name? */
#define XML_TOK_NAME_ASTERISK 31 /* name* */
#define XML_TOK_NAME_PLUS 32 /* name+ */
#define XML_TOK_COND_SECT_OPEN 33 /* <![ */
#define XML_TOK_COND_SECT_CLOSE 34 /* ]]> */
#define XML_TOK_CLOSE_PAREN_QUESTION 35 /*)? */
#define XML_TOK_CLOSE_PAREN_ASTERISK 36 /*)* */
#define XML_TOK_CLOSE_PAREN_PLUS 37 /*)+ */
#define XML_TOK_COMMA 38
#define XML_TOK_ATTRIBUTE_VALUE_S 39
#define XML_TOK_CDATA_SECT_CLOSE 40
#define XML_TOK_PREFIXED_NAME 41
#define XML_N_STATES 3
#define XML_PROLOG_STATE 0
#define XML_CONTENT_STATE 1
#define XML_CDATA_SECTION_STATE 2
#define XML_N_LITERAL_TYPES 2
#define XML_ATTRIBUTE_VALUE_LITERAL 0
#define XML_ENTITY_VALUE_LITERAL 1
#define XML_UTF8_ENCODE_MAX 4
#define XML_UTF16_ENCODE_MAX 2
#define XmlTok(enc, state, ptr, end, nextTokPtr) (((enc)->scanners[state])(enc, ptr, end, nextTokPtr))
#define XmlPrologTok(enc, ptr, end, nextTokPtr) XmlTok(enc, XML_PROLOG_STATE, ptr, end, nextTokPtr)
#define XmlContentTok(enc, ptr, end, nextTokPtr) XmlTok(enc, XML_CONTENT_STATE, ptr, end, nextTokPtr)
#define XmlCdataSectionTok(enc, ptr, end, nextTokPtr) XmlTok(enc, XML_CDATA_SECTION_STATE, ptr, end, nextTokPtr)
#define XmlLiteralTok(enc, literalType, ptr, end, nextTokPtr) (((enc)->literalScanners[literalType])(enc, ptr, end, nextTokPtr))
#define XmlAttributeValueTok(enc, ptr, end, nextTokPtr) XmlLiteralTok(enc, XML_ATTRIBUTE_VALUE_LITERAL, ptr, end, nextTokPtr)
#define XmlEntityValueTok(enc, ptr, end, nextTokPtr) XmlLiteralTok(enc, XML_ENTITY_VALUE_LITERAL, ptr, end, nextTokPtr)
#define XmlSameName(enc, ptr1, ptr2) (((enc)->sameName)(enc, ptr1, ptr2))
#define XmlNameMatchesAscii(enc, ptr1, end1, ptr2) (((enc)->nameMatchesAscii)(enc, ptr1, end1, ptr2))
#define XmlNameLength(enc, ptr) (((enc)->nameLength)(enc, ptr))
#define XmlSkipS(enc, ptr) (((enc)->skipS)(enc, ptr))
#define XmlGetAttributes(enc, ptr, attsMax, atts) (((enc)->getAtts)(enc, ptr, attsMax, atts))
#define XmlCharRefNumber(enc, ptr) (((enc)->charRefNumber)(enc, ptr))
#define XmlPredefinedEntityName(enc, ptr, end) (((enc)->predefinedEntityName)(enc, ptr, end))
#define XmlUpdatePosition(enc, ptr, end, pos) (((enc)->updatePosition)(enc, ptr, end, pos))
#define XmlIsPublicId(enc, ptr, end, badPtr) (((enc)->isPublicId)(enc, ptr, end, badPtr))
#define XmlUtf8Convert(enc, fromP, fromLim, toP, toLim) (((enc)->utf8Convert)(enc, fromP, fromLim, toP, toLim))
#define XmlUtf16Convert(enc, fromP, fromLim, toP, toLim) (((enc)->utf16Convert)(enc, fromP, fromLim, toP, toLim))
Typedefs
typedef struct position POSITION
typedef struct encoding ENCODING
typedef int(PTRCALL * SCANNER) (const ENCODING *, const char *, const char *, const char **)
typedef int(XMLCALL * CONVERTER) (void *userData, const char *p)
Enumerations
enum XML_Convert_Result { XML_CONVERT_COMPLETED = 0 , XML_CONVERT_INPUT_INCOMPLETE = 1 , XML_CONVERT_OUTPUT_EXHAUSTED = 2 }
Functions
int XmlParseXmlDecl (int isGeneralTextEntity, const ENCODING *enc, const char *ptr, const char *end, const char **badPtr, const char **versionPtr, const char **versionEndPtr, const char **encodingNamePtr, const ENCODING **namedEncodingPtr, int *standalonePtr)
int XmlInitEncoding (INIT_ENCODING *, const ENCODING **, const char *name)
const ENCODING * XmlGetUtf8InternalEncoding (void)
const ENCODING * XmlGetUtf16InternalEncoding (void)
int FASTCALL XmlUtf8Encode (int charNumber, char *buf)
int FASTCALL XmlUtf16Encode (int charNumber, unsigned short *buf)
int XmlSizeOfUnknownEncoding (void)
ENCODING * XmlInitUnknownEncoding (void *mem, int *table, CONVERTER convert, void *userData)
int XmlParseXmlDeclNS (int isGeneralTextEntity, const ENCODING *enc, const char *ptr, const char *end, const char **badPtr, const char **versionPtr, const char **versionEndPtr, const char **encodingNamePtr, const ENCODING **namedEncodingPtr, int *standalonePtr)
int XmlInitEncodingNS (INIT_ENCODING *, const ENCODING **, const char *name)
const ENCODING * XmlGetUtf8InternalEncodingNS (void)
const ENCODING * XmlGetUtf16InternalEncodingNS (void)
ENCODING * XmlInitUnknownEncodingNS (void *mem, int *table, CONVERTER convert, void *userData)
Class Documentation
position
struct position
Class Members
XML_Size columnNumber
XML_Size lineNumber
ATTRIBUTE
struct ATTRIBUTE
Class Members
const char * name
char normalized
const char * valueEnd
const char * valuePtr
INIT_ENCODING
struct INIT_ENCODING
Class Members
const ENCODING ** encPtr
ENCODING initEnc
Macro Definition Documentation
XML_ATTRIBUTE_VALUE_LITERAL
#define XML_ATTRIBUTE_VALUE_LITERAL 0
XML_CDATA_SECTION_STATE
#define XML_CDATA_SECTION_STATE 2
XML_CONTENT_STATE
#define XML_CONTENT_STATE 1
XML_ENTITY_VALUE_LITERAL
#define XML_ENTITY_VALUE_LITERAL 1
XML_N_LITERAL_TYPES
#define XML_N_LITERAL_TYPES 2
XML_N_STATES
#define XML_N_STATES 3
XML_PROLOG_STATE
#define XML_PROLOG_STATE 0
XML_TOK_ATTRIBUTE_VALUE_S
#define XML_TOK_ATTRIBUTE_VALUE_S 39
XML_TOK_BOM
#define XML_TOK_BOM 14 /* Byte order mark */
XML_TOK_CDATA_SECT_CLOSE
#define XML_TOK_CDATA_SECT_CLOSE 40
XML_TOK_CDATA_SECT_OPEN
#define XML_TOK_CDATA_SECT_OPEN 8
XML_TOK_CHAR_REF
#define XML_TOK_CHAR_REF 10 /* numeric character reference */
XML_TOK_CLOSE_BRACKET
#define XML_TOK_CLOSE_BRACKET 26
XML_TOK_CLOSE_PAREN
#define XML_TOK_CLOSE_PAREN 24
XML_TOK_CLOSE_PAREN_ASTERISK
#define XML_TOK_CLOSE_PAREN_ASTERISK 36 /*)* */
XML_TOK_CLOSE_PAREN_PLUS
#define XML_TOK_CLOSE_PAREN_PLUS 37 /*)+ */
XML_TOK_CLOSE_PAREN_QUESTION
#define XML_TOK_CLOSE_PAREN_QUESTION 35 /*)? */
XML_TOK_COMMA
#define XML_TOK_COMMA 38
XML_TOK_COMMENT
#define XML_TOK_COMMENT 13
XML_TOK_COND_SECT_CLOSE
#define XML_TOK_COND_SECT_CLOSE 34 /* ]]> */
XML_TOK_COND_SECT_OPEN
#define XML_TOK_COND_SECT_OPEN 33 /* <![ */
XML_TOK_DATA_CHARS
return XML_TOK_DATA_CHARS 6
Referenced by appendAttributeValue(), doCdataSection(), doContent(), and storeEntityValue().
XML_TOK_DATA_NEWLINE
#define XML_TOK_DATA_NEWLINE 7
XML_TOK_DECL_CLOSE
#define XML_TOK_DECL_CLOSE 17 /* > */
XML_TOK_DECL_OPEN
#define XML_TOK_DECL_OPEN 16 /* <!foo */
XML_TOK_EMPTY_ELEMENT_NO_ATTS
#define XML_TOK_EMPTY_ELEMENT_NO_ATTS 4
XML_TOK_EMPTY_ELEMENT_WITH_ATTS
#define XML_TOK_EMPTY_ELEMENT_WITH_ATTS 3 /* empty element tag <e/> */
XML_TOK_END_TAG
#define XML_TOK_END_TAG 5
XML_TOK_ENTITY_REF
#define XML_TOK_ENTITY_REF 9
XML_TOK_INSTANCE_START
#define XML_TOK_INSTANCE_START 29
XML_TOK_INVALID
#define XML_TOK_INVALID 0
XML_TOK_LITERAL
#define XML_TOK_LITERAL 27
XML_TOK_NAME
#define XML_TOK_NAME 18
XML_TOK_NAME_ASTERISK
#define XML_TOK_NAME_ASTERISK 31 /* name* */
XML_TOK_NAME_PLUS
#define XML_TOK_NAME_PLUS 32 /* name+ */
XML_TOK_NAME_QUESTION
#define XML_TOK_NAME_QUESTION 30 /* name? */
XML_TOK_NMTOKEN
#define XML_TOK_NMTOKEN 19
XML_TOK_NONE
#define XML_TOK_NONE -4 /* The string to be scanned is empty */
XML_TOK_OPEN_BRACKET
#define XML_TOK_OPEN_BRACKET 25
XML_TOK_OPEN_PAREN
#define XML_TOK_OPEN_PAREN 23
XML_TOK_OR
#define XML_TOK_OR 21 /* | */
XML_TOK_PARAM_ENTITY_REF
#define XML_TOK_PARAM_ENTITY_REF 28
XML_TOK_PARTIAL
#define XML_TOK_PARTIAL -1 /* only part of a token */
XML_TOK_PARTIAL_CHAR
#define XML_TOK_PARTIAL_CHAR -2 /* only part of a multibyte sequence */
XML_TOK_PERCENT
#define XML_TOK_PERCENT 22
XML_TOK_PI
#define XML_TOK_PI 11 /* processing instruction */
XML_TOK_POUND_NAME
#define XML_TOK_POUND_NAME 20 /* #name */
XML_TOK_PREFIXED_NAME
#define XML_TOK_PREFIXED_NAME 41
XML_TOK_PROLOG_S
#define XML_TOK_PROLOG_S 15
XML_TOK_START_TAG_NO_ATTS
#define XML_TOK_START_TAG_NO_ATTS 2
XML_TOK_START_TAG_WITH_ATTS
#define XML_TOK_START_TAG_WITH_ATTS 1
XML_TOK_TRAILING_CR
#define XML_TOK_TRAILING_CR
Value:
                                    -3   /* A CR at the end of the scan;
                                    might be part of CRLF sequence */
XML_TOK_TRAILING_RSQB
#define XML_TOK_TRAILING_RSQB
Value:
                                    -5 /* ] or ]] at the end of the scan; might be
                                    start of illegal ]]> sequence */
XML_TOK_XML_DECL
#define XML_TOK_XML_DECL 12 /* XML decl or text decl */
XML_UTF16_ENCODE_MAX
#define XML_UTF16_ENCODE_MAX 2
XML_UTF8_ENCODE_MAX
#define XML_UTF8_ENCODE_MAX 4
XmlAttributeValueTok
#define XmlAttributeValueTok (enc, ptr, end, nextTokPtr) XmlLiteralTok(enc, XML_ATTRIBUTE_VALUE_LITERAL, ptr, end, nextTokPtr)
XmlCdataSectionTok
#define XmlCdataSectionTok (enc, ptr, end, nextTokPtr) XmlTok(enc, XML_CDATA_SECTION_STATE, ptr, end, nextTokPtr)
XmlCharRefNumber
#define XmlCharRefNumber (enc, ptr) (((enc)->charRefNumber)(enc, ptr))
XmlContentTok
#define XmlContentTok (enc, ptr, end, nextTokPtr) XmlTok(enc, XML_CONTENT_STATE, ptr, end, nextTokPtr)
XmlEntityValueTok
#define XmlEntityValueTok (enc, ptr, end, nextTokPtr) XmlLiteralTok(enc, XML_ENTITY_VALUE_LITERAL, ptr, end, nextTokPtr)
XmlGetAttributes
#define XmlGetAttributes (enc, ptr, attsMax, atts) (((enc)->getAtts)(enc, ptr, attsMax, atts))
XmlIsPublicId
#define XmlIsPublicId (enc, ptr, end, badPtr) (((enc)->isPublicId)(enc, ptr, end, badPtr))
XmlLiteralTok
#define XmlLiteralTok (enc, literalType, ptr, end, nextTokPtr) (((enc)->literalScanners[literalType])(enc, ptr, end, nextTokPtr))
XmlNameLength
#define XmlNameLength (enc, ptr) (((enc)->nameLength)(enc, ptr))
XmlNameMatchesAscii
#define XmlNameMatchesAscii (enc, ptr1, end1, ptr2) (((enc)->nameMatchesAscii)(enc, ptr1, end1, ptr2))
XmlPredefinedEntityName
#define XmlPredefinedEntityName (enc, ptr, end) (((enc)->predefinedEntityName)(enc, ptr, end))
XmlPrologTok
#define XmlPrologTok (enc, ptr, end, nextTokPtr) XmlTok(enc, XML_PROLOG_STATE, ptr, end, nextTokPtr)
XmlSameName
#define XmlSameName (enc, ptr1, ptr2) (((enc)->sameName)(enc, ptr1, ptr2))
XmlSkipS
#define XmlSkipS (enc, ptr) (((enc)->skipS)(enc, ptr))
XmlTok
#define XmlTok (enc, state, ptr, end, nextTokPtr) (((enc)->scanners[state])(enc, ptr, end, nextTokPtr))
XmlUpdatePosition
#define XmlUpdatePosition (enc, ptr, end, pos) (((enc)->updatePosition)(enc, ptr, end, pos))
XmlUtf16Convert
#define XmlUtf16Convert (enc, fromP, fromLim, toP, toLim) (((enc)->utf16Convert)(enc, fromP, fromLim, toP, toLim))
XmlUtf8Convert
#define XmlUtf8Convert (enc, fromP, fromLim, toP, toLim) (((enc)->utf8Convert)(enc, fromP, fromLim, toP, toLim))
Typedef Documentation
CONVERTER
typedef int(XMLCALL * CONVERTER) (void *userData, const char *p)
ENCODING
typedef struct encoding ENCODING
POSITION
typedef struct position POSITION
SCANNER
typedef int(PTRCALL * SCANNER) (const ENCODING *, const char *, const char *, const char **)
Enumeration Type Documentation
XML_Convert_Result
enum XML_Convert_Result
Enumerator
XML_CONVERT_COMPLETED
XML_CONVERT_INPUT_INCOMPLETE
XML_CONVERT_OUTPUT_EXHAUSTED
{
  XML_CONVERT_COMPLETED = 0,
  XML_CONVERT_INPUT_INCOMPLETE = 1,
Function Documentation
XmlGetUtf16InternalEncoding()
const ENCODING * XmlGetUtf16InternalEncoding (void)
XmlGetUtf16InternalEncodingNS()
const ENCODING * XmlGetUtf16InternalEncodingNS (void)
XmlGetUtf8InternalEncoding()
const ENCODING * XmlGetUtf8InternalEncoding (void)
XmlGetUtf8InternalEncodingNS()
const ENCODING * XmlGetUtf8InternalEncodingNS (void)
XmlInitEncoding()
int XmlInitEncoding (INIT_ENCODING * , const ENCODING ** , const char * name)
Referenced by initializeEncoding(), and parserInit().
XmlInitEncodingNS()
int XmlInitEncodingNS (INIT_ENCODING * , const ENCODING ** , const char * name)
Referenced by initializeEncoding().
XmlInitUnknownEncoding()
ENCODING * XmlInitUnknownEncoding (void * mem, int * table, CONVERTER convert, void * userData)
{
  int i;
  struct unknown_encoding *e = (struct unknown_encoding *)mem;
  for (i = 0; i < (int)sizeof(struct normal_encoding); i++)
    ((char *)mem)[i] = ((char *)&latin1_encoding)[i];
  for (i = 0; i < 128; i++)
    if (latin1_encoding.type[i] != BT_OTHER
        && latin1_encoding.type[i] != BT_NONXML
        && table[i] != i)
      return 0;
  for (i = 0; i < 256; i++) {
    int c = table[i];
    if (c == -1) {
      e->normal.type[i] = BT_MALFORM;
      /* This shouldn't really get used. */
      e->utf16[i] = 0xFFFF;
      e->utf8[i][0] = 1;
      e->utf8[i][1] = 0;
    }
    else if (c < 0) {
      if (c < -4)
        return 0;
      e->normal.type[i] = (unsigned char)(BT_LEAD2 - (c + 2));
      e->utf8[i][0] = 0;
      e->utf16[i] = 0;
    }
    else if (c < 0x80) {
      if (latin1_encoding.type[c] != BT_OTHER
          && latin1_encoding.type[c] != BT_NONXML
          && c != i)
        return 0;
      e->normal.type[i] = latin1_encoding.type[c];
      e->utf8[i][0] = 1;
      e->utf8[i][1] = (char)c;
      e->utf16[i] = (unsigned short)(c == 0 ? 0xFFFF : c);
    }
    else if (checkCharRefNumber(c) < 0) {
      e->normal.type[i] = BT_NONXML;
      /* This shouldn't really get used. */
      e->utf16[i] = 0xFFFF;
      e->utf8[i][0] = 1;
      e->utf8[i][1] = 0;
    }
    else {
      if (c > 0xFFFF)
        return 0;
      if (UCS2_GET_NAMING(nmstrtPages, c >> 8, c & 0xff))
        e->normal.type[i] = BT_NMSTRT;
      else if (UCS2_GET_NAMING(namePages, c >> 8, c & 0xff))
        e->normal.type[i] = BT_NAME;
      else
        e->normal.type[i] = BT_OTHER;
      e->utf8[i][0] = (char)XmlUtf8Encode(c, e->utf8[i] + 1);
      e->utf16[i] = (unsigned short)c;
    }
  }
  e->userData = userData;
  e->convert = convert;
  if (convert) {
    e->normal.isName2 = unknown_isName;
    e->normal.isName3 = unknown_isName;
    e->normal.isName4 = unknown_isName;
    e->normal.isNmstrt2 = unknown_isNmstrt;
    e->normal.isNmstrt3 = unknown_isNmstrt;
    e->normal.isNmstrt4 = unknown_isNmstrt;
    e->normal.isInvalid2 = unknown_isInvalid;
    e->normal.isInvalid3 = unknown_isInvalid;
    e->normal.isInvalid4 = unknown_isInvalid;
  }
  e->normal.enc.utf8Convert = unknown_toUtf8;
  e->normal.enc.utf16Convert = unknown_toUtf16;
  return &(e->normal.enc);
}
References BT_LEAD2, BT_MALFORM, BT_NAME, BT_NMSTRT, BT_NONXML, BT_OTHER, checkCharRefNumber(), unknown_encoding::convert, convert(), normal_encoding::enc, int, latin1_encoding, namePages, nmstrtPages, unknown_encoding::normal, normal_encoding::type, UCS2_GET_NAMING, unknown_isInvalid(), unknown_isName(), unknown_isNmstrt(), unknown_toUtf16(), unknown_toUtf8(), userData, unknown_encoding::userData, unknown_encoding::utf16, unknown_encoding::utf8, and XmlUtf8Encode().
Referenced by handleUnknownEncoding(), and XmlInitUnknownEncodingNS().
XmlInitUnknownEncodingNS()
ENCODING * XmlInitUnknownEncodingNS (void * mem, int * table, CONVERTER convert, void * userData)
{
  ENCODING *enc = XmlInitUnknownEncoding(mem, table, convert, userData);
  if (enc)
    ((struct normal_encoding *)enc)->type[ASCII_COLON] = BT_COLON;
  return enc;
}
References ASCII_COLON, BT_COLON, convert(), enc, userData, and XmlInitUnknownEncoding().
Referenced by handleUnknownEncoding().
XmlParseXmlDecl()
int XmlParseXmlDecl (int isGeneralTextEntity, const ENCODING * enc, const char * ptr, const char * end, const char ** badPtr, const char ** versionPtr, const char ** versionEndPtr, const char ** encodingNamePtr, const ENCODING ** namedEncodingPtr, int * standalonePtr)
Referenced by processXmlDecl().
XmlParseXmlDeclNS()
int XmlParseXmlDeclNS (int isGeneralTextEntity, const ENCODING * enc, const char * ptr, const char * end, const char ** badPtr, const char ** versionPtr, const char ** versionEndPtr, const char ** encodingNamePtr, const ENCODING ** namedEncodingPtr, int * standalonePtr)
Referenced by processXmlDecl().
XmlSizeOfUnknownEncoding()
int XmlSizeOfUnknownEncoding (void)
{
  return sizeof(struct unknown_encoding);
}
Referenced by handleUnknownEncoding().
XmlUtf16Encode()
int FASTCALL XmlUtf16Encode (int charNumber, unsigned short * buf)
{
  if (charNum < 0)
    return 0;
  if (charNum < 0x10000) {
    buf[0] = (unsigned short)charNum;
    return 1;
  }
  if (charNum < 0x110000) {
    charNum -= 0x10000;
    buf[0] = (unsigned short)((charNum >> 10) + 0xD800);
    buf[1] = (unsigned short)((charNum & 0x3FF) + 0xDC00);
    return 2;
  }
  return 0;
}
XmlUtf8Encode()
int FASTCALL XmlUtf8Encode (int charNumber, char * buf)
{
  enum {
    /* minN is minimum legal resulting value for N byte sequence */
    min2 = 0x80,
    min3 = 0x800,
    min4 = 0x10000
  };
  if (c < 0)
    return 0;
  if (c < min2) {
    buf[0] = (char)(c | UTF8_cval1);
    return 1;
  }
  if (c < min3) {
    buf[0] = (char)((c >> 6) | UTF8_cval2);
    buf[1] = (char)((c & 0x3f) | 0x80);
    return 2;
  }
  if (c < min4) {
    buf[0] = (char)((c >> 12) | UTF8_cval3);
    buf[1] = (char)(((c >> 6) & 0x3f) | 0x80);
    buf[2] = (char)((c & 0x3f) | 0x80);
    return 3;
  }
  if (c < 0x110000) {
    buf[0] = (char)((c >> 18) | UTF8_cval4);
    buf[1] = (char)(((c >> 12) & 0x3f) | 0x80);
    buf[2] = (char)(((c >> 6) & 0x3f) | 0x80);
    buf[3] = (char)((c & 0x3f) | 0x80);
    return 4;
  }
  return 0;
}
References UTF8_cval1, UTF8_cval2, UTF8_cval3, and UTF8_cval4.
Referenced by unknown_toUtf8(), and XmlInitUnknownEncoding().