OrcaSlicer: Slic3r::GCodeWriter Class Reference
Slic3r::GCodeWriter Class Reference
#include <src/libslic3r/GCodeWriter.hpp>
Public Member Functions
GCodeWriter ()
Extruder * extruder ()
const Extruder * extruder () const
void apply_print_config (const PrintConfig &print_config)
void set_extruders (std::vector< unsigned int > extruder_ids)
const std::vector< Extruder > & extruders () const
std::vector< unsigned int > extruder_ids () const
std::string preamble ()
std::string postamble () const
std::string set_temperature (unsigned int temperature, bool wait=false, int tool=-1) const
std::string set_bed_temperature (int temperature, bool wait=false)
std::string set_acceleration (unsigned int acceleration)
std::string set_jerk_xy (double jerk)
std::string set_pressure_advance (double pa) const
std::string reset_e (bool force=false)
std::string update_progress (unsigned int num, unsigned int tot, bool allow_100=false) const
bool need_toolchange (unsigned int extruder_id) const
std::string set_extruder (unsigned int extruder_id)
std::string toolchange_prefix () const
std::string toolchange (unsigned int extruder_id)
std::string set_speed (double F, const std::string &comment=std::string(), const std::string &cooling_marker=std::string())
double get_current_speed () const
std::string travel_to_xy (const Vec2d &point, const std::string &comment=std::string())
std::string travel_to_xyz (const Vec3d &point, const std::string &comment=std::string())
std::string travel_to_z (double z, const std::string &comment=std::string())
bool will_move_z (double z) const
std::string extrude_to_xy (const Vec2d &point, double dE, const std::string &comment=std::string(), bool force_no_extrusion=false)
std::string extrude_arc_to_xy (const Vec2d &point, const Vec2d &center_offset, double dE, const bool is_ccw, const std::string &comment=std::string(), bool force_no_extrusion=false)
std::string extrude_to_xyz (const Vec3d &point, double dE, const std::string &comment=std::string(), bool force_no_extrusion=false)
std::string retract (bool before_wipe=false)
std::string retract_for_toolchange (bool before_wipe=false)
std::string unretract ()
std::string lift (LiftType lift_type=LiftType::NormalLift, bool spiral_vase=false)
std::string unlift ()
Vec3d get_position () const
void set_position (Vec3d &in)
void set_xy_offset (double x, double y)
Vec2f get_xy_offset ()
std::string set_fan (unsigned int speed) const
void set_object_start_str (std::string start_string)
bool is_object_start_str_empty ()
void set_object_end_str (std::string end_string)
bool is_object_end_str_empty ()
void add_object_start_labels (std::string &gcode)
void add_object_end_labels (std::string &gcode)
void add_object_change_labels (std::string &gcode)
void set_current_position_clear (bool clear)
bool is_current_position_clear () const
void set_is_bbl_machine (bool bval)
const bool is_bbl_printers () const
void set_is_first_layer (bool bval)
Static Public Member Functions
static std::string set_fan (const GCodeFlavor gcode_flavor, unsigned int speed)
static std::string set_additional_fan (unsigned int speed)
Public Attributes
GCodeConfig config
bool multiple_extruders
Static Public Attributes
static bool full_gcode_comment = true
static const double slope_threshold = 3 * PI / 180
Private Member Functions
std::string _travel_to_z (double z, const std::string &comment)
std::string _spiral_travel_to_z (double z, const Vec2d &ij_offset, const std::string &comment)
std::string _retract (double length, double restart_extra, const std::string &comment)
Private Attributes
std::vector< Extruder > m_extruders
bool m_single_extruder_multi_material
Extruder * m_extruder
unsigned int m_last_acceleration
unsigned int m_max_acceleration
double m_max_jerk
double m_last_jerk
double m_max_jerk_z
double m_max_jerk_e
unsigned int m_travel_acceleration
unsigned int m_travel_jerk
unsigned int m_last_additional_fan_speed
int m_last_bed_temperature
bool m_last_bed_temperature_reached
double m_lifted
double m_to_lift
LiftType m_to_lift_type
Vec3d m_pos = Vec3d::Zero()
bool m_is_current_pos_clear = false
double m_x_offset { 0 }
double m_y_offset { 0 }
std::string m_gcode_label_objects_start
std::string m_gcode_label_objects_end
bool m_is_bbl_printers = false
double m_current_speed
bool m_is_first_layer = true
Detailed Description
Constructor & Destructor Documentation
GCodeWriter()
Slic3r::GCodeWriter::GCodeWriter () inline
                  :
        multiple_extruders(false), m_extruder(nullptr),
        m_single_extruder_multi_material(false),
        m_last_acceleration(0), m_max_acceleration(0),
        m_last_jerk(0), m_max_jerk(0),
        /*m_last_bed_temperature(0), */m_last_bed_temperature_reached(true),
        m_lifted(0),
        m_to_lift(0),
        m_to_lift_type(LiftType::NormalLift),
        m_current_speed(3600), m_is_first_layer(true)
        {}
Member Function Documentation
_retract()
std::string Slic3r::GCodeWriter::_retract (double length, double restart_extra, const std::string & comment) private
{
    /*  If firmware retraction is enabled, we use a fake value of 1
    since we ignore the actual configured retract_length which
    might be 0, in which case the retraction logic gets skipped. */
    if (this->config.use_firmware_retraction)
        length = 1;
    std::string gcode;
    if (double dE = m_extruder->retract(length, restart_extra);  dE != 0) {
        if (this->config.use_firmware_retraction) {
            gcode = FLAVOR_IS(gcfMachinekit) ? "G22 ; retract\n" : "G10 ; retract\n";
        }
        else {
            // BBS
            GCodeG1Formatter w;
            w.emit_e(m_extruder->E());
            w.emit_f(m_extruder->retract_speed() * 60.);
            // BBS
            w.emit_comment(GCodeWriter::full_gcode_comment, comment);
            gcode = w.string();
        }
    }
    if (FLAVOR_IS(gcfMakerWare))
        gcode += "M103 ; extruder off\n";
    return gcode;
}
References config, Slic3r::Extruder::E(), Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_e(), Slic3r::GCodeFormatter::emit_f(), FLAVOR_IS, full_gcode_comment, Slic3r::gcfMachinekit, Slic3r::gcfMakerWare, Slic3r::length(), m_extruder, Slic3r::Extruder::retract(), Slic3r::Extruder::retract_speed(), and Slic3r::GCodeFormatter::string().
Referenced by retract(), and retract_for_toolchange().
_spiral_travel_to_z()
std::string Slic3r::GCodeWriter::_spiral_travel_to_z (double z, const Vec2d & ij_offset, const std::string & comment) private
{
    m_pos(2) = z;
    double speed = this->config.travel_speed_z.value;
    if (speed == 0.) {
        speed = m_is_first_layer ? this->config.get_abs_value("initial_layer_travel_speed")
                                 : this->config.travel_speed.value;
    }
    std::string output = "G17\n";
    GCodeG2G3Formatter w(true);
    w.emit_z(z);
    w.emit_ij(ij_offset);
    w.emit_string(" P1 ");
    w.emit_f(speed * 60.0);
    w.emit_comment(GCodeWriter::full_gcode_comment, comment);
    return output + w.string();
}
References config, Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_f(), Slic3r::GCodeFormatter::emit_ij(), Slic3r::GCodeFormatter::emit_string(), Slic3r::GCodeFormatter::emit_z(), full_gcode_comment, m_is_first_layer, m_pos, and Slic3r::GCodeFormatter::string().
Referenced by travel_to_xyz().
_travel_to_z()
std::string Slic3r::GCodeWriter::_travel_to_z (double z, const std::string & comment) private
{
    m_pos(2) = z;
    double speed = this->config.travel_speed_z.value;
    if (speed == 0.) {
        speed = m_is_first_layer ? this->config.get_abs_value("initial_layer_travel_speed")
                                 : this->config.travel_speed.value;
    }
    GCodeG1Formatter w;
    w.emit_z(z);
    w.emit_f(speed * 60.0);
    //BBS
    w.emit_comment(GCodeWriter::full_gcode_comment, comment);
    return w.string();
}
References config, Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_f(), Slic3r::GCodeFormatter::emit_z(), full_gcode_comment, m_is_first_layer, m_pos, and Slic3r::GCodeFormatter::string().
Referenced by lift(), travel_to_xyz(), travel_to_z(), and unlift().
add_object_change_labels()
void Slic3r::GCodeWriter::add_object_change_labels (std::string & gcode)
{
    add_object_end_labels(gcode);
    add_object_start_labels(gcode);
}
References add_object_end_labels(), and add_object_start_labels().
Referenced by Slic3r::GCode::_do_export().
add_object_end_labels()
void Slic3r::GCodeWriter::add_object_end_labels (std::string & gcode)
{
    if (!m_gcode_label_objects_end.empty()) {
        gcode += m_gcode_label_objects_end;
        m_gcode_label_objects_end = "";
        // Orca: reset E so that e value remain correct after skipping the object
        // ref to: https://github.com/SoftFever/OrcaSlicer/pull/205/commits/7f1fe0bd544077626080aa1a9a0576aa735da1a4#r1083470162
        if (!this->config.use_relative_e_distances)
            gcode += reset_e(true);
    }
}
References config, m_gcode_label_objects_end, and reset_e().
Referenced by add_object_change_labels(), and Slic3r::WipeTowerIntegration::append_tcr().
add_object_start_labels()
void Slic3r::GCodeWriter::add_object_start_labels (std::string & gcode)
{
    if (!m_gcode_label_objects_start.empty()) {
        gcode += m_gcode_label_objects_start;
        m_gcode_label_objects_start = "";
    }
}
References m_gcode_label_objects_start.
Referenced by add_object_change_labels().
apply_print_config()
void Slic3r::GCodeWriter::apply_print_config (const PrintConfig & print_config)
{
    this->config.apply(print_config, true);
    m_single_extruder_multi_material = print_config.single_extruder_multi_material.value;
    bool use_mach_limits = print_config.gcode_flavor.value == gcfMarlinLegacy ||
                     print_config.gcode_flavor.value == gcfMarlinFirmware ||
                     print_config.gcode_flavor.value == gcfKlipper ||
                     print_config.gcode_flavor.value == gcfRepRapFirmware;
    m_max_acceleration = std::lrint(use_mach_limits ? print_config.machine_max_acceleration_extruding.values.front() : 0);
    m_max_jerk = std::lrint(use_mach_limits ? std::min(print_config.machine_max_jerk_x.values.front(), print_config.machine_max_jerk_y.values.front()) : 0);
    m_max_jerk_z = print_config.machine_max_jerk_z.values.front();
    m_max_jerk_e = print_config.machine_max_jerk_e.values.front();
}
References config, Slic3r::gcfKlipper, Slic3r::gcfMarlinFirmware, Slic3r::gcfMarlinLegacy, Slic3r::gcfRepRapFirmware, m_max_acceleration, m_max_jerk, m_max_jerk_e, m_max_jerk_z, and m_single_extruder_multi_material.
Referenced by Slic3r::CalibPressureAdvancePattern::_refresh_writer().
extrude_arc_to_xy()
std::string Slic3r::GCodeWriter::extrude_arc_to_xy (const Vec2d & point, const Vec2d & center_offset, double dE, const bool is_ccw, const std::string & comment = std::string(), bool force_no_extrusion = false)
{
    m_pos(0) = point(0);
    m_pos(1) = point(1);
    if (!force_no_extrusion)
        m_extruder->extrude(dE);
    Vec2d point_on_plate = { point(0) - m_x_offset, point(1) - m_y_offset };
    GCodeG2G3Formatter w(is_ccw);
    w.emit_xy(point_on_plate);
    w.emit_ij(center_offset);
    if (!force_no_extrusion)
        w.emit_e(m_extruder->E());
    //BBS
    w.emit_comment(GCodeWriter::full_gcode_comment, comment);
    return w.string();
}
References Slic3r::Extruder::E(), Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_e(), Slic3r::GCodeFormatter::emit_ij(), Slic3r::GCodeFormatter::emit_xy(), Slic3r::Extruder::extrude(), full_gcode_comment, m_extruder, m_pos, m_x_offset, m_y_offset, and Slic3r::GCodeFormatter::string().
extrude_to_xy()
std::string Slic3r::GCodeWriter::extrude_to_xy (const Vec2d & point, double dE, const std::string & comment = std::string(), bool force_no_extrusion = false)
{
    m_pos(0) = point(0);
    m_pos(1) = point(1);
    if(std::abs(dE) <= std::numeric_limits<double>::epsilon())
        force_no_extrusion = true;
    if (!force_no_extrusion)
        m_extruder->extrude(dE);
    //BBS: take plate offset into consider
    Vec2d point_on_plate = { point(0) - m_x_offset, point(1) - m_y_offset };
    GCodeG1Formatter w;
    w.emit_xy(point_on_plate);
    if (!force_no_extrusion)
        w.emit_e(m_extruder->E());
    //BBS
    w.emit_comment(GCodeWriter::full_gcode_comment, comment);
    return w.string();
}
References Slic3r::Extruder::E(), Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_e(), Slic3r::GCodeFormatter::emit_xy(), Slic3r::Extruder::extrude(), full_gcode_comment, m_extruder, m_pos, m_x_offset, m_y_offset, and Slic3r::GCodeFormatter::string().
Referenced by Slic3r::CalibPressureAdvance::draw_digit(), Slic3r::CalibPressureAdvancePattern::draw_line(), and Slic3r::Wipe::wipe().
extrude_to_xyz()
std::string Slic3r::GCodeWriter::extrude_to_xyz (const Vec3d & point, double dE, const std::string & comment = std::string(), bool force_no_extrusion = false)
{
    m_pos = point;
    m_lifted = 0;
    if (!force_no_extrusion)
        m_extruder->extrude(dE);
    //BBS: take plate offset into consider
    Vec3d point_on_plate = { point(0) - m_x_offset, point(1) - m_y_offset, point(2) };
    GCodeG1Formatter w;
    w.emit_xyz(point_on_plate);
    if (!force_no_extrusion)
        w.emit_e(m_extruder->E());
    //BBS
    w.emit_comment(GCodeWriter::full_gcode_comment, comment);
    return w.string();
}
References Slic3r::Extruder::E(), Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_e(), Slic3r::GCodeFormatter::emit_xyz(), Slic3r::Extruder::extrude(), full_gcode_comment, m_extruder, m_lifted, m_pos, m_x_offset, m_y_offset, and Slic3r::GCodeFormatter::string().
extruder() [1/2]
Extruder * Slic3r::GCodeWriter::extruder () inline
{ return m_extruder; }
References m_extruder.
Referenced by Slic3r::GCode::_do_export(), Slic3r::OozePrevention::_get_temp(), Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::need_wipe(), Slic3r::OozePrevention::post_toolchange(), Slic3r::OozePrevention::pre_toolchange(), and Slic3r::Wipe::wipe().
extruder() [2/2]
const Extruder * Slic3r::GCodeWriter::extruder () const inline
{ return m_extruder; }
References m_extruder.
extruder_ids()
std::vector< unsigned int > Slic3r::GCodeWriter::extruder_ids () const inline
{
        std::vector<unsigned int> out;
        out.reserve(m_extruders.size());
        for (const Extruder &e : m_extruders)
            out.push_back(e.id());
        return out;
    }
References m_extruders, and out.
Referenced by set_extruders().
extruders()
const std::vector< Extruder > & Slic3r::GCodeWriter::extruders () const inline
{ return m_extruders; }
References m_extruders.
Referenced by Slic3r::CoolingBuffer::CoolingBuffer(), Slic3r::GCode::_do_export(), and Slic3r::GCode::do_export().
get_current_speed()
double Slic3r::GCodeWriter::get_current_speed () const inline
{ return m_current_speed;}
References m_current_speed.
Referenced by Slic3r::Wipe::wipe().
get_position()
Vec3d Slic3r::GCodeWriter::get_position () const inline
{ return m_pos; }
References m_pos.
Referenced by Slic3r::CoolingBuffer::CoolingBuffer(), Slic3r::GCode::_do_export(), Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::WipeTowerIntegration::finalize(), and Slic3r::OozePrevention::pre_toolchange().
get_xy_offset()
Vec2f Slic3r::GCodeWriter::get_xy_offset () inline
{ return Vec2f{m_x_offset, m_y_offset}; };
References m_x_offset, and m_y_offset.
Referenced by Slic3r::GCode::_do_export().
is_bbl_printers()
const bool Slic3r::GCodeWriter::is_bbl_printers () const inline
{return m_is_bbl_printers;}
References m_is_bbl_printers.
is_current_position_clear()
bool Slic3r::GCodeWriter::is_current_position_clear () const inline
{ return m_is_current_pos_clear; };
References m_is_current_pos_clear.
Referenced by travel_to_xyz().
is_object_end_str_empty()
bool Slic3r::GCodeWriter::is_object_end_str_empty () inline
{ return m_gcode_label_objects_end.empty(); }
References m_gcode_label_objects_end.
is_object_start_str_empty()
bool Slic3r::GCodeWriter::is_object_start_str_empty () inline
{ return m_gcode_label_objects_start.empty(); }
References m_gcode_label_objects_start.
lift()
std::string Slic3r::GCodeWriter::lift (LiftType lift_type = LiftType::NormalLift, bool spiral_vase = false)
{
    // check whether the above/below conditions are met
    double target_lift = 0;
    {
        double above = this->config.retract_lift_above.get_at(m_extruder->id());
        double below = this->config.retract_lift_below.get_at(m_extruder->id());
        if (m_pos(2) >= above && (below == 0 || m_pos(2) <= below))
            target_lift = this->config.z_hop.get_at(m_extruder->id());
    }
    // BBS
    if (m_lifted == 0 && m_to_lift == 0 && target_lift > 0) {
        if (spiral_vase) {
            m_lifted = target_lift;
            return this->_travel_to_z(m_pos(2) + target_lift, "lift Z");
        }
        else {
            m_to_lift = target_lift;
            m_to_lift_type = lift_type;
        }
    }
    return "";
}
References _travel_to_z(), config, Slic3r::Extruder::id(), m_extruder, m_lifted, m_pos, m_to_lift, and m_to_lift_type.
need_toolchange()
bool Slic3r::GCodeWriter::need_toolchange (unsigned int extruder_id) const inline
        { return m_extruder == nullptr || m_extruder->id() != extruder_id; }
References Slic3r::Extruder::id(), and m_extruder.
Referenced by Slic3r::GCode::_do_export(), Slic3r::WipeTowerIntegration::append_tcr(), set_extruder(), and Slic3r::WipeTowerIntegration::tool_change().
postamble()
std::string Slic3r::GCodeWriter::postamble () const
{
    std::ostringstream gcode;
    if (FLAVOR_IS(gcfMachinekit))
          gcode << "M2 ; end of program\n";
    return gcode.str();
}
References FLAVOR_IS, and Slic3r::gcfMachinekit.
Referenced by Slic3r::GCode::_do_export().
preamble()
std::string Slic3r::GCodeWriter::preamble ()
{
    std::ostringstream gcode;
    if (FLAVOR_IS_NOT(gcfMakerWare)) {
        gcode << "G90\n";
        gcode << "G21\n";
    }
    if (FLAVOR_IS(gcfRepRapSprinter) ||
        FLAVOR_IS(gcfRepRapFirmware) ||
        FLAVOR_IS(gcfMarlinLegacy) ||
        FLAVOR_IS(gcfMarlinFirmware) ||
        FLAVOR_IS(gcfTeacup) ||
        FLAVOR_IS(gcfRepetier) ||
        FLAVOR_IS(gcfSmoothie) ||
        FLAVOR_IS(gcfKlipper))
    {
        if (this->config.use_relative_e_distances) {
            gcode << "M83 ; use relative distances for extrusion\n";
        } else {
            gcode << "M82 ; use absolute distances for extrusion\n";
        }
        gcode << this->reset_e(true);
    }
    return gcode.str();
}
References config, FLAVOR_IS, FLAVOR_IS_NOT, Slic3r::gcfKlipper, Slic3r::gcfMakerWare, Slic3r::gcfMarlinFirmware, Slic3r::gcfMarlinLegacy, Slic3r::gcfRepetier, Slic3r::gcfRepRapFirmware, Slic3r::gcfRepRapSprinter, Slic3r::gcfSmoothie, Slic3r::gcfTeacup, and reset_e().
reset_e()
std::string Slic3r::GCodeWriter::reset_e (bool force = false)
{
    if (FLAVOR_IS(gcfMach3)
        || FLAVOR_IS(gcfMakerWare)
        || FLAVOR_IS(gcfSailfish))
        return "";
    if (m_extruder != nullptr) {
        if (m_extruder->E() == 0. && ! force)
            return "";
        m_extruder->reset_E();
    }
    if (! this->config.use_relative_e_distances) {
        std::ostringstream gcode;
        gcode << "G92 E0";
        //BBS
        if (GCodeWriter::full_gcode_comment) gcode << " ; reset extrusion distance";
        gcode << "\n";
        return gcode.str();
    } else {
        return "";
    }
}
References config, Slic3r::Extruder::E(), FLAVOR_IS, full_gcode_comment, Slic3r::gcfMach3, Slic3r::gcfMakerWare, Slic3r::gcfSailfish, m_extruder, and Slic3r::Extruder::reset_E().
Referenced by add_object_end_labels(), preamble(), toolchange(), and unretract().
retract()
std::string Slic3r::GCodeWriter::retract (bool before_wipe = false)
{
    double factor = before_wipe ? m_extruder->retract_before_wipe() : 1.;
    assert(factor >= 0. && factor <= 1. + EPSILON);
    return this->_retract(
        factor * m_extruder->retraction_length(),
        factor * m_extruder->retract_restart_extra(),
        "retract"
    );
}
References _retract(), EPSILON, m_extruder, Slic3r::Extruder::retract_before_wipe(), Slic3r::Extruder::retract_restart_extra(), and Slic3r::Extruder::retraction_length().
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), and Slic3r::CalibPressureAdvance::move_to().
retract_for_toolchange()
std::string Slic3r::GCodeWriter::retract_for_toolchange (bool before_wipe = false)
{
    double factor = before_wipe ? m_extruder->retract_before_wipe() : 1.;
    assert(factor >= 0. && factor <= 1. + EPSILON);
    return this->_retract(
        factor * m_extruder->retract_length_toolchange(),
        factor * m_extruder->retract_restart_extra_toolchange(),
        "retract for toolchange"
    );
}
References _retract(), EPSILON, m_extruder, Slic3r::Extruder::retract_before_wipe(), Slic3r::Extruder::retract_length_toolchange(), and Slic3r::Extruder::retract_restart_extra_toolchange().
set_acceleration()
std::string Slic3r::GCodeWriter::set_acceleration (unsigned int acceleration)
{
    // Clamp the acceleration to the allowed maximum.
    if (m_max_acceleration > 0 && acceleration > m_max_acceleration)
        acceleration = m_max_acceleration;
    if (acceleration == 0 || acceleration == m_last_acceleration)
        return std::string();
    m_last_acceleration = acceleration;
    std::ostringstream gcode;
    if (FLAVOR_IS(gcfRepetier)) {
        // M201: Set max printing acceleration
        gcode << "M201 X" << acceleration << " Y" << acceleration;
        //BBS
        if (GCodeWriter::full_gcode_comment) gcode << " ; adjust acceleration";
        gcode << "\n";
        // M202: Set max travel acceleration
        gcode << "M202 X" << acceleration << " Y" << acceleration;
    } else if (FLAVOR_IS(gcfRepRapFirmware)) {
        // M204: Set default acceleration
        gcode << "M204 P" << acceleration;
    } else if (FLAVOR_IS(gcfMarlinFirmware)) {
        // This is new MarlinFirmware with separated print/retraction/travel acceleration.
        // Use M204 P, we don't want to override travel acc by M204 S (which is deprecated anyway).
        gcode << "M204 P" << acceleration;
    } else if (FLAVOR_IS(gcfKlipper)) {
        gcode << "SET_VELOCITY_LIMIT ACCEL=" << acceleration;
        if (this->config.accel_to_decel_enable) {
            gcode << " ACCEL_TO_DECEL=" << acceleration * this->config.accel_to_decel_factor / 100;
            if (GCodeWriter::full_gcode_comment)
                gcode << " ; adjust ACCEL_TO_DECEL";
        }
    } else
        gcode << "M204 S" << acceleration;
    //BBS
    if (GCodeWriter::full_gcode_comment) gcode << " ; adjust acceleration";
    gcode << "\n";
    return gcode.str();
}
References config, FLAVOR_IS, full_gcode_comment, Slic3r::gcfKlipper, Slic3r::gcfMarlinFirmware, Slic3r::gcfRepetier, Slic3r::gcfRepRapFirmware, m_last_acceleration, and m_max_acceleration.
Referenced by Slic3r::GCode::_do_export().
set_additional_fan()
std::string Slic3r::GCodeWriter::set_additional_fan (unsigned int speed) static
{
    std::ostringstream gcode;
    gcode << "M106 " << "P2 " << "S" << (int)(255.0 * speed / 100.0);
    if (GCodeWriter::full_gcode_comment) {
        if (speed == 0)
            gcode << " ; disable additional fan ";
        else
            gcode << " ; enable additional fan ";
    }
    gcode << "\n";
    return gcode.str();
}
References full_gcode_comment, and int.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::CoolingBuffer::apply_layer_cooldown().
set_bed_temperature()
std::string Slic3r::GCodeWriter::set_bed_temperature (int temperature, bool wait = false)
{
    if (temperature == m_last_bed_temperature && (! wait || m_last_bed_temperature_reached))
        return std::string();
    m_last_bed_temperature = temperature;
    m_last_bed_temperature_reached = wait;
    std::string code, comment;
    std::ostringstream gcode;
    if (wait) {
        code = "M190";
        comment = "set bed temperature and wait for it to be reached";
    }
    else {
        code = "M140";
        comment = "set bed temperature";
    }
    gcode << code << " S" << temperature << " ; " << comment << "\n";
    return gcode.str();
}
References m_last_bed_temperature, and m_last_bed_temperature_reached.
set_current_position_clear()
void Slic3r::GCodeWriter::set_current_position_clear (bool clear) inline
{ m_is_current_pos_clear = clear; };
References m_is_current_pos_clear.
Referenced by Slic3r::GCode::_do_export(), Slic3r::WipeTowerIntegration::append_tcr(), travel_to_xy(), and travel_to_xyz().
set_extruder()
std::string Slic3r::GCodeWriter::set_extruder (unsigned int extruder_id) inline
        { return this->need_toolchange(extruder_id) ? this->toolchange(extruder_id) : ""; }
References need_toolchange(), and toolchange().
Referenced by Slic3r::CalibPressureAdvancePattern::_refresh_writer().
set_extruders()
void Slic3r::GCodeWriter::set_extruders (std::vector< unsigned int > extruder_ids)
{
    std::sort(extruder_ids.begin(), extruder_ids.end());
    m_extruders.clear();
    m_extruders.reserve(extruder_ids.size());
    for (unsigned int extruder_id : extruder_ids)
        m_extruders.emplace_back(Extruder(extruder_id, &this->config, config.single_extruder_multi_material.value));
    /*  we enable support for multiple extruder if any extruder greater than 0 is used
        (even if prints only uses that one) since we need to output Tx commands
        first extruder has index 0 */
    this->multiple_extruders = (*std::max_element(extruder_ids.begin(), extruder_ids.end())) > 0;
}
References config, extruder_ids(), m_extruders, and multiple_extruders.
Referenced by Slic3r::CalibPressureAdvancePattern::_refresh_writer().
set_fan() [1/2]
std::string Slic3r::GCodeWriter::set_fan (const GCodeFlavor gcode_flavor, unsigned int speed) static
{
    std::ostringstream gcode;
    if (speed == 0) {
        switch (gcode_flavor) {
        case gcfTeacup:
            gcode << "M106 S0"; break;
        case gcfMakerWare:
        case gcfSailfish:
            gcode << "M127";    break;
        default:
            gcode << "M106 S0";    break;
        }
        if (GCodeWriter::full_gcode_comment)
            gcode << " ; disable fan";
        gcode << "\n";
    } else {
        switch (gcode_flavor) {
        case gcfMakerWare:
        case gcfSailfish:
            gcode << "M126";    break;
        case gcfMach3:
        case gcfMachinekit:
            gcode << "M106 P" << static_cast<unsigned int>(255.5 * speed / 100.0); break;
        default:
            gcode << "M106 S" << static_cast<unsigned int>(255.5 * speed / 100.0); break;
        }
        if (GCodeWriter::full_gcode_comment)
            gcode << " ; enable fan";
        gcode << "\n";
    }
    return gcode.str();
}
References full_gcode_comment, Slic3r::gcfMach3, Slic3r::gcfMachinekit, Slic3r::gcfMakerWare, Slic3r::gcfSailfish, and Slic3r::gcfTeacup.
Referenced by Slic3r::GCode::_do_export(), Slic3r::FanMover::_set_fan(), Slic3r::CoolingBuffer::apply_layer_cooldown(), and set_fan().
set_fan() [2/2]
std::string Slic3r::GCodeWriter::set_fan (unsigned int speed) const
{
    //BBS
    return GCodeWriter::set_fan(this->config.gcode_flavor, speed);
}
References config, and set_fan().
set_is_bbl_machine()
void Slic3r::GCodeWriter::set_is_bbl_machine (bool bval) inline
{m_is_bbl_printers = bval;}
References m_is_bbl_printers.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::CalibPressureAdvancePattern::_refresh_writer().
set_is_first_layer()
void Slic3r::GCodeWriter::set_is_first_layer (bool bval) inline
{ m_is_first_layer = bval; }
References m_is_first_layer.
set_jerk_xy()
std::string Slic3r::GCodeWriter::set_jerk_xy (double jerk)
{
    // Clamp the jerk to the allowed maximum.
    if (m_max_jerk > 0 && jerk > m_max_jerk)
        jerk = m_max_jerk;
    if (jerk < 0.01 || is_approx(jerk, m_last_jerk))
        return std::string();
    m_last_jerk = jerk;
    std::ostringstream gcode;
    if(FLAVOR_IS(gcfKlipper))
        gcode << "SET_VELOCITY_LIMIT SQUARE_CORNER_VELOCITY=" << jerk;
    else
        gcode << "M205 X" << jerk << " Y" << jerk;
    if (m_is_bbl_printers)
        gcode << std::setprecision(2) << " Z" << m_max_jerk_z << " E" << m_max_jerk_e;
    if (GCodeWriter::full_gcode_comment) gcode << " ; adjust jerk";
    gcode << "\n";
    return gcode.str();
}
References FLAVOR_IS, full_gcode_comment, Slic3r::gcfKlipper, Slic3r::is_approx(), m_is_bbl_printers, m_last_jerk, m_max_jerk, m_max_jerk_e, and m_max_jerk_z.
Referenced by Slic3r::GCode::_do_export().
set_object_end_str()
void Slic3r::GCodeWriter::set_object_end_str (std::string end_string) inline
{ m_gcode_label_objects_end = end_string; }
References m_gcode_label_objects_end.
set_object_start_str()
void Slic3r::GCodeWriter::set_object_start_str (std::string start_string) inline
{ m_gcode_label_objects_start = start_string; }
References m_gcode_label_objects_start.
set_position()
void Slic3r::GCodeWriter::set_position (Vec3d & in) inline
{ m_pos = in; }
References in, and m_pos.
Referenced by Slic3r::WipeTowerIntegration::append_tcr().
set_pressure_advance()
std::string Slic3r::GCodeWriter::set_pressure_advance (double pa) const
{
    std::ostringstream gcode;
    if (pa < 0)
        return gcode.str();
    if(m_is_bbl_printers){
        //SoftFever: set L1000 to use linear model
        gcode << "M900 K" <<std::setprecision(4)<< pa << " L1000 M10 ; Override pressure advance value\n";
    }
    else{
        if (FLAVOR_IS(gcfKlipper))
            gcode << "SET_PRESSURE_ADVANCE ADVANCE=" << std::setprecision(4) << pa << "; Override pressure advance value\n";
        else if(FLAVOR_IS(gcfRepRapFirmware))
            gcode << ("M572 D0 S") << std::setprecision(4) << pa << "; Override pressure advance value\n";
        else
            gcode << "M900 K" <<std::setprecision(4)<< pa << "; Override pressure advance value\n";
    }
    return gcode.str();
}
References FLAVOR_IS, Slic3r::gcfKlipper, Slic3r::gcfRepRapFirmware, and m_is_bbl_printers.
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), and Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes().
set_speed()
std::string Slic3r::GCodeWriter::set_speed (double F, const std::string & comment = std::string(), const std::string & cooling_marker = std::string())
{
    assert(F > 0.);
    assert(F < 100000.);
    m_current_speed = F;
    GCodeG1Formatter w;
    w.emit_f(F);
    //BBS
    w.emit_comment(GCodeWriter::full_gcode_comment, comment);
    w.emit_string(cooling_marker);
    return w.string();
}
References Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_f(), Slic3r::GCodeFormatter::emit_string(), Slic3r::F, full_gcode_comment, m_current_speed, and Slic3r::GCodeFormatter::string().
Referenced by Slic3r::CalibPressureAdvancePattern::draw_line(), Slic3r::CalibPressureAdvance::draw_number(), and Slic3r::Wipe::wipe().
set_temperature()
std::string Slic3r::GCodeWriter::set_temperature (unsigned int temperature, bool wait = false, int tool = -1) const
{
    if (wait && (FLAVOR_IS(gcfMakerWare) || FLAVOR_IS(gcfSailfish)))
        return "";
    std::string code, comment;
    if (wait && FLAVOR_IS_NOT(gcfTeacup) && FLAVOR_IS_NOT(gcfRepRapFirmware)) {
        code = "M109";
        comment = "set nozzle temperature and wait for it to be reached";
    } else {
        if (FLAVOR_IS(gcfRepRapFirmware)) { // M104 is deprecated on RepRapFirmware
            code = "G10";
        } else {
            code = "M104";
        }
        comment = "set nozzle temperature";
    }
    std::ostringstream gcode;
    gcode << code << " ";
    if (FLAVOR_IS(gcfMach3) || FLAVOR_IS(gcfMachinekit)) {
        gcode << "P";
    } else {
        gcode << "S";
    }
    gcode << temperature;
    bool multiple_tools = this->multiple_extruders && ! m_single_extruder_multi_material;
    if (tool != -1 && (multiple_tools || FLAVOR_IS(gcfMakerWare) || FLAVOR_IS(gcfSailfish)) ) {
        if (FLAVOR_IS(gcfRepRapFirmware)) {
            gcode << " P" << tool;
        } else {
            gcode << " T" << tool;
        }
    }
    gcode << " ; " << comment << "\n";
    if ((FLAVOR_IS(gcfTeacup) || FLAVOR_IS(gcfRepRapFirmware)) && wait)
        gcode << "M116 ; wait for temperature to be reached\n";
    return gcode.str();
}
References FLAVOR_IS, FLAVOR_IS_NOT, Slic3r::gcfMach3, Slic3r::gcfMachinekit, Slic3r::gcfMakerWare, Slic3r::gcfRepRapFirmware, Slic3r::gcfSailfish, Slic3r::gcfTeacup, m_single_extruder_multi_material, and multiple_extruders.
Referenced by Slic3r::OozePrevention::post_toolchange(), and Slic3r::OozePrevention::pre_toolchange().
set_xy_offset()
void Slic3r::GCodeWriter::set_xy_offset (double x, double y) inline
{ m_x_offset = x; m_y_offset = y; }
References m_x_offset, and m_y_offset.
Referenced by Slic3r::CalibPressureAdvancePattern::_refresh_writer(), and Slic3r::GCode::set_gcode_offset().
toolchange()
std::string Slic3r::GCodeWriter::toolchange (unsigned int extruder_id)
{
    // set the new extruder
  auto it_extruder = Slic3r::lower_bound_by_predicate(m_extruders.begin(), m_extruders.end(), [extruder_id](const Extruder &e) { return e.id() < extruder_id; });
    assert(it_extruder != m_extruders.end() && it_extruder->id() == extruder_id);
    m_extruder = &*it_extruder;
    // return the toolchange command
    // if we are running a single-extruder setup, just set the extruder and return nothing
    std::ostringstream gcode;
    if (this->multiple_extruders) {
        gcode << this->toolchange_prefix() << extruder_id;
        //BBS
        if (GCodeWriter::full_gcode_comment)
            gcode << " ; change extruder";
        gcode << "\n";
        gcode << this->reset_e(true);
    }
    return gcode.str();
}
References full_gcode_comment, Slic3r::lower_bound_by_predicate(), m_extruder, m_extruders, multiple_extruders, reset_e(), and toolchange_prefix().
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), and set_extruder().
toolchange_prefix()
std::string Slic3r::GCodeWriter::toolchange_prefix () const
{
    return FLAVOR_IS(gcfMakerWare) ? "M135 T" :
           FLAVOR_IS(gcfSailfish)  ? "M108 T" : "T";
}
References FLAVOR_IS, Slic3r::gcfMakerWare, and Slic3r::gcfSailfish.
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), and toolchange().
travel_to_xy()
std::string Slic3r::GCodeWriter::travel_to_xy (const Vec2d & point, const std::string & comment = std::string())
{
    m_pos(0) = point(0);
    m_pos(1) = point(1);
    this->set_current_position_clear(true);
    //BBS: take plate offset into consider
    Vec2d point_on_plate = { point(0) - m_x_offset, point(1) - m_y_offset };
    GCodeG1Formatter w;
    w.emit_xy(point_on_plate);
    auto speed = m_is_first_layer
        ? this->config.get_abs_value("initial_layer_travel_speed") : this->config.travel_speed.value;
    w.emit_f(speed * 60.0);
    //BBS
    w.emit_comment(GCodeWriter::full_gcode_comment, comment);
    return w.string();
}
References config, Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_f(), Slic3r::GCodeFormatter::emit_xy(), full_gcode_comment, m_is_first_layer, m_pos, m_x_offset, m_y_offset, set_current_position_clear(), and Slic3r::GCodeFormatter::string().
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::CalibPressureAdvance::move_to(), Slic3r::OozePrevention::pre_toolchange(), and travel_to_xyz().
travel_to_xyz()
std::string Slic3r::GCodeWriter::travel_to_xyz (const Vec3d & point, const std::string & comment = std::string())
{
    // FIXME: This function was not being used when travel_speed_z was separated (bd6badf).
    // Calculation of feedrate was not updated accordingly. If you want to use
    // this function, fix it first.
    //std::terminate();
    /*  If target Z is lower than current Z but higher than nominal Z we
        don't perform the Z move but we only move in the XY plane and
        adjust the nominal Z by reducing the lift amount that will be
        used for unlift. */
        // BBS
    Vec3d dest_point = point;
    auto travel_speed =
        m_is_first_layer ? this->config.get_abs_value("initial_layer_travel_speed") : this->config.travel_speed.value;
    //BBS: a z_hop need to be handle when travel
    if (std::abs(m_to_lift) > EPSILON) {
        assert(std::abs(m_lifted) < EPSILON);
        //BBS: don't need to do real lift if the current position is absolutely same with target.
        //This ususally happens when the last extrusion line is short and the end of wipe position
        //is same with the traget point by chance.
        if ((!this->is_current_position_clear() || m_pos != dest_point) &&
            m_to_lift + m_pos(2) > point(2)) {
            m_lifted = m_to_lift + m_pos(2) - point(2);
            dest_point(2) = m_to_lift + m_pos(2);
        }
        m_to_lift = 0.;
        std::string slop_move;
        //BBS: minus plate offset
        Vec3d source = { m_pos(0) - m_x_offset, m_pos(1) - m_y_offset, m_pos(2) };
        Vec3d target = { dest_point(0) - m_x_offset, dest_point(1) - m_y_offset, dest_point(2) };
        Vec3d delta = target - source;
        Vec2d delta_no_z = { delta(0), delta(1) };
        //BBS: don'need slope travel because we don't know where is the source position the first time
        //BBS: Also don't need to do slope move or spiral lift if x-y distance is absolute zero
        if (delta(2) > 0 && delta_no_z.norm() != 0.0f)    {
            //BBS: SpiralLift
            if (m_to_lift_type == LiftType::SpiralLift && this->is_current_position_clear()) {
                //BBS: todo: check the arc move all in bed area, if not, then use lazy lift
                double radius = delta(2) / (2 * PI * atan(GCodeWriter::slope_threshold));
                Vec2d ij_offset = radius * delta_no_z.normalized();
                ij_offset = { -ij_offset(1), ij_offset(0) };
                slop_move = this->_spiral_travel_to_z(target(2), ij_offset, "spiral lift Z");
            }
            //BBS: LazyLift
            else if (m_to_lift_type == LiftType::LazyLift &&
                this->is_current_position_clear() &&
                atan2(delta(2), delta_no_z.norm()) < GCodeWriter::slope_threshold) {
                //BBS: check whether we can make a travel like
                //   _____
                //  /       to make the z list early to avoid to hit some warping place when travel is long.
                Vec2d temp = delta_no_z.normalized() * delta(2) / tan(GCodeWriter::slope_threshold);
                Vec3d slope_top_point = Vec3d(temp(0), temp(1), delta(2)) + source;
                GCodeG1Formatter w0;
                w0.emit_xyz(slope_top_point);
                w0.emit_f(travel_speed * 60.0);
                //BBS
                w0.emit_comment(GCodeWriter::full_gcode_comment, comment);
                slop_move = w0.string();
            }
            else if (m_to_lift_type == LiftType::NormalLift) {
                slop_move = _travel_to_z(target.z(), "normal lift Z");
            }
        }
        std::string xy_z_move;
        {
            GCodeG1Formatter w0;
            if (this->is_current_position_clear()) {
                w0.emit_xyz(target);
                w0.emit_f(travel_speed * 60.0);
                w0.emit_comment(GCodeWriter::full_gcode_comment, comment);
                xy_z_move = w0.string();
            }
            else {
                w0.emit_xy(Vec2d(target.x(), target.y()));
                w0.emit_f(travel_speed * 60.0);
                w0.emit_comment(GCodeWriter::full_gcode_comment, comment);
                xy_z_move = w0.string() + _travel_to_z(target.z(), comment);
            }
        }
        m_pos = dest_point;
        this->set_current_position_clear(true);
        return slop_move + xy_z_move;
    }
    else if (!this->will_move_z(point(2))) {
        double nominal_z = m_pos(2) - m_lifted;
        m_lifted -= (point(2) - nominal_z);
        // In case that z_hop == layer_height we could end up with almost zero in_m_lifted
        // and a retract could be skipped
        if (std::abs(m_lifted) < EPSILON)
            m_lifted = 0.;
        //BBS
        this->set_current_position_clear(true);
        return this->travel_to_xy(to_2d(point));
    }
    else {
        /*  In all the other cases, we perform an actual XYZ move and cancel
            the lift. */
        m_lifted = 0;
    }
    //BBS: take plate offset into consider
    Vec3d point_on_plate = { dest_point(0) - m_x_offset, dest_point(1) - m_y_offset, dest_point(2) };
    std::string out_string;
    GCodeG1Formatter w;
    if (!this->is_current_position_clear())
    {
        //force to move xy first then z after filament change
        w.emit_xy(Vec2d(point_on_plate.x(), point_on_plate.y()));
        w.emit_f(this->config.travel_speed.value * 60.0);
        w.emit_comment(GCodeWriter::full_gcode_comment, comment);
        out_string = w.string() + _travel_to_z(point_on_plate.z(), comment);
    } else {
        GCodeG1Formatter w;
        w.emit_xyz(point_on_plate);
        w.emit_f(this->config.travel_speed.value * 60.0);
        w.emit_comment(GCodeWriter::full_gcode_comment, comment);
        out_string = w.string();
    }
    m_pos = dest_point;
    this->set_current_position_clear(true);
    return out_string;
}
References _spiral_travel_to_z(), _travel_to_z(), atan(), config, Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_f(), Slic3r::GCodeFormatter::emit_xy(), Slic3r::GCodeFormatter::emit_xyz(), EPSILON, full_gcode_comment, is_current_position_clear(), Slic3r::LazyLift, m_is_first_layer, m_lifted, m_pos, m_to_lift, m_to_lift_type, m_x_offset, m_y_offset, Slic3r::NormalLift, PI, set_current_position_clear(), slope_threshold, Slic3r::SpiralLift, Slic3r::GCodeFormatter::string(), tan(), Slic3r::to_2d(), travel_to_xy(), and will_move_z().
travel_to_z()
std::string Slic3r::GCodeWriter::travel_to_z (double z, const std::string & comment = std::string())
{
    /*  If target Z is lower than current Z but higher than nominal Z
        we don't perform the move but we only adjust the nominal Z by
        reducing the lift amount that will be used for unlift. */
    if (!this->will_move_z(z)) {
        double nominal_z = m_pos(2) - m_lifted;
        m_lifted -= (z - nominal_z);
        if (std::abs(m_lifted) < EPSILON)
            m_lifted = 0.;
        return "";
    }
    /*  In all the other cases, we perform an actual Z move and cancel
        the lift. */
    m_lifted = 0;
    return this->_travel_to_z(z, comment);
}
References _travel_to_z(), EPSILON, m_lifted, m_pos, and will_move_z().
Referenced by Slic3r::GCode::_do_export(), Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
unlift()
std::string Slic3r::GCodeWriter::unlift ()
{
    std::string gcode;
    if (m_lifted > 0) {
        gcode += this->_travel_to_z(m_pos(2) - m_lifted, "restore layer Z");
        m_lifted = 0;
    }
    m_to_lift = 0.;
    return gcode;
}
References _travel_to_z(), m_lifted, m_pos, and m_to_lift.
Referenced by Slic3r::GCode::unretract().
unretract()
std::string Slic3r::GCodeWriter::unretract ()
{
    std::string gcode;
    if (FLAVOR_IS(gcfMakerWare))
        gcode = "M101 ; extruder on\n";
    if (double dE = m_extruder->unretract(); dE != 0) {
        if (this->config.use_firmware_retraction) {
            gcode += FLAVOR_IS(gcfMachinekit) ? "G23 ; unretract\n" : "G11 ; unretract\n";
            gcode += this->reset_e();
        }
        else {
            //BBS
            // use G1 instead of G0 because G0 will blend the restart with the previous travel move
            GCodeG1Formatter w;
            w.emit_e(m_extruder->E());
            w.emit_f(m_extruder->deretract_speed() * 60.);
            //BBS
            w.emit_comment(GCodeWriter::full_gcode_comment, " ; unretract");
            gcode += w.string();
        }
    }
    return gcode;
}
References config, Slic3r::Extruder::deretract_speed(), Slic3r::Extruder::E(), Slic3r::GCodeFormatter::emit_comment(), Slic3r::GCodeFormatter::emit_e(), Slic3r::GCodeFormatter::emit_f(), FLAVOR_IS, full_gcode_comment, Slic3r::gcfMachinekit, Slic3r::gcfMakerWare, m_extruder, reset_e(), Slic3r::GCodeFormatter::string(), and Slic3r::Extruder::unretract().
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::ProcessLayer::emit_custom_gcode_per_print_z(), Slic3r::CalibPressureAdvance::move_to(), and Slic3r::GCode::unretract().
update_progress()
std::string Slic3r::GCodeWriter::update_progress (unsigned int num, unsigned int tot, bool allow_100 = false) const
{
    if (FLAVOR_IS_NOT(gcfMakerWare) && FLAVOR_IS_NOT(gcfSailfish))
        return "";
    unsigned int percent = (unsigned int)floor(100.0 * num / tot + 0.5);
    if (!allow_100) percent = std::min(percent, (unsigned int)99);
    std::ostringstream gcode;
    gcode << "M73 P" << percent;
    //BBS
    if (GCodeWriter::full_gcode_comment) gcode << " ; update progress";
    gcode << "\n";
    return gcode.str();
}
References FLAVOR_IS_NOT, floor(), full_gcode_comment, Slic3r::gcfMakerWare, Slic3r::gcfSailfish, and int.
Referenced by Slic3r::GCode::_do_export().
will_move_z()
bool Slic3r::GCodeWriter::will_move_z (double z) const
{
    /* If target Z is lower than current Z but higher than nominal Z
        we don't perform an actual Z move. */
    if (m_lifted > 0) {
        double nominal_z = m_pos(2) - m_lifted;
        if (z >= nominal_z && z <= m_pos(2))
            return false;
    }
    // BBS.
    // Dont move z if it is the same as target z
    else if (std::abs(m_pos(2) - z) < EPSILON) {
        return false;
    }
    return true;
}
References EPSILON, m_lifted, and m_pos.
Referenced by travel_to_xyz(), and travel_to_z().
Member Data Documentation
config
GCodeConfig Slic3r::GCodeWriter::config
Referenced by Slic3r::FanMover::_process_gcode_line(), Slic3r::FanMover::_process_T(), _retract(), Slic3r::FanMover::_set_fan(), _spiral_travel_to_z(), _travel_to_z(), add_object_end_labels(), apply_print_config(), lift(), preamble(), reset_e(), set_acceleration(), set_extruders(), set_fan(), travel_to_xy(), travel_to_xyz(), and unretract().
full_gcode_comment
bool Slic3r::GCodeWriter::full_gcode_comment = true static
Referenced by _retract(), _spiral_travel_to_z(), _travel_to_z(), Slic3r::GCode::do_export(), extrude_arc_to_xy(), extrude_to_xy(), extrude_to_xyz(), reset_e(), set_acceleration(), set_additional_fan(), set_fan(), set_jerk_xy(), set_speed(), toolchange(), travel_to_xy(), travel_to_xyz(), unretract(), and update_progress().
m_current_speed
double Slic3r::GCodeWriter::m_current_speed private
Referenced by get_current_speed(), and set_speed().
m_extruder
Extruder* Slic3r::GCodeWriter::m_extruder private
Referenced by _retract(), extrude_arc_to_xy(), extrude_to_xy(), extrude_to_xyz(), extruder(), extruder(), lift(), need_toolchange(), reset_e(), retract(), retract_for_toolchange(), toolchange(), and unretract().
m_extruders
std::vector<Extruder> Slic3r::GCodeWriter::m_extruders private
Referenced by extruder_ids(), extruders(), set_extruders(), and toolchange().
m_gcode_label_objects_end
std::string Slic3r::GCodeWriter::m_gcode_label_objects_end private
Referenced by add_object_end_labels(), is_object_end_str_empty(), and set_object_end_str().
m_gcode_label_objects_start
std::string Slic3r::GCodeWriter::m_gcode_label_objects_start private
Referenced by add_object_start_labels(), is_object_start_str_empty(), and set_object_start_str().
m_is_bbl_printers
bool Slic3r::GCodeWriter::m_is_bbl_printers = false private
Referenced by is_bbl_printers(), set_is_bbl_machine(), set_jerk_xy(), and set_pressure_advance().
m_is_current_pos_clear
bool Slic3r::GCodeWriter::m_is_current_pos_clear = false private
Referenced by is_current_position_clear(), and set_current_position_clear().
m_is_first_layer
bool Slic3r::GCodeWriter::m_is_first_layer = true private
Referenced by _spiral_travel_to_z(), _travel_to_z(), set_is_first_layer(), travel_to_xy(), and travel_to_xyz().
m_last_acceleration
unsigned int Slic3r::GCodeWriter::m_last_acceleration private
Referenced by set_acceleration().
m_last_additional_fan_speed
unsigned int Slic3r::GCodeWriter::m_last_additional_fan_speed private
m_last_bed_temperature
int Slic3r::GCodeWriter::m_last_bed_temperature private
Referenced by set_bed_temperature().
m_last_bed_temperature_reached
bool Slic3r::GCodeWriter::m_last_bed_temperature_reached private
Referenced by set_bed_temperature().
m_last_jerk
double Slic3r::GCodeWriter::m_last_jerk private
Referenced by set_jerk_xy().
m_lifted
double Slic3r::GCodeWriter::m_lifted private
Referenced by extrude_to_xyz(), lift(), travel_to_xyz(), travel_to_z(), unlift(), and will_move_z().
m_max_acceleration
unsigned int Slic3r::GCodeWriter::m_max_acceleration private
Referenced by apply_print_config(), and set_acceleration().
m_max_jerk
double Slic3r::GCodeWriter::m_max_jerk private
Referenced by apply_print_config(), and set_jerk_xy().
m_max_jerk_e
double Slic3r::GCodeWriter::m_max_jerk_e private
Referenced by apply_print_config(), and set_jerk_xy().
m_max_jerk_z
double Slic3r::GCodeWriter::m_max_jerk_z private
Referenced by apply_print_config(), and set_jerk_xy().
m_pos
Vec3d Slic3r::GCodeWriter::m_pos = Vec3d::Zero() private
Referenced by _spiral_travel_to_z(), _travel_to_z(), extrude_arc_to_xy(), extrude_to_xy(), extrude_to_xyz(), get_position(), lift(), set_position(), travel_to_xy(), travel_to_xyz(), travel_to_z(), unlift(), and will_move_z().
m_single_extruder_multi_material
bool Slic3r::GCodeWriter::m_single_extruder_multi_material private
Referenced by apply_print_config(), and set_temperature().
m_to_lift
double Slic3r::GCodeWriter::m_to_lift private
Referenced by lift(), travel_to_xyz(), and unlift().
m_to_lift_type
LiftType Slic3r::GCodeWriter::m_to_lift_type private
Referenced by lift(), and travel_to_xyz().
m_travel_acceleration
unsigned int Slic3r::GCodeWriter::m_travel_acceleration private
m_travel_jerk
unsigned int Slic3r::GCodeWriter::m_travel_jerk private
m_x_offset
double Slic3r::GCodeWriter::m_x_offset { 0 } private
Referenced by extrude_arc_to_xy(), extrude_to_xy(), extrude_to_xyz(), get_xy_offset(), set_xy_offset(), travel_to_xy(), and travel_to_xyz().
m_y_offset
double Slic3r::GCodeWriter::m_y_offset { 0 } private
Referenced by extrude_arc_to_xy(), extrude_to_xy(), extrude_to_xyz(), get_xy_offset(), set_xy_offset(), travel_to_xy(), and travel_to_xyz().
multiple_extruders
bool Slic3r::GCodeWriter::multiple_extruders
Referenced by Slic3r::GCode::_do_export(), set_extruders(), set_temperature(), and toolchange().
slope_threshold
const double Slic3r::GCodeWriter::slope_threshold = 3 * PI / 180 static
Referenced by travel_to_xyz().
The documentation for this class was generated from the following files:
src/libslic3r/GCodeWriter.hpp
src/libslic3r/GCodeWriter.cpp