OrcaSlicer: Slic3r::PresetBundle Class Reference
Slic3r::PresetBundle Class Reference
#include <src/libslic3r/PresetBundle.hpp>
Classes
struct ObsoletePresets
struct PresetPreferences
Public Types
enum LoadConfigBundleAttribute { SaveImported , ResetUserProfile , LoadSystem , LoadVendorOnly }
using LoadConfigBundleAttributes = enum_bitmask< LoadConfigBundleAttribute >
Public Member Functions
PresetBundle ()
PresetBundle (const PresetBundle &rhs)
PresetBundle & operator= (const PresetBundle &rhs)
void reset (bool delete_files)
void setup_directories ()
void copy_files (const std::string &from)
PresetsConfigSubstitutions load_presets (AppConfig &config, ForwardCompatibilitySubstitutionRule rule, const PresetPreferences &preferred_selection=PresetPreferences())
void load_selections (AppConfig &config, const PresetPreferences &preferred_selection=PresetPreferences())
PresetsConfigSubstitutions load_user_presets (std::string user, ForwardCompatibilitySubstitutionRule rule)
PresetsConfigSubstitutions load_user_presets (AppConfig &config, std::map< std::string, std::map< std::string, std::string > > &my_presets, ForwardCompatibilitySubstitutionRule rule)
PresetsConfigSubstitutions import_presets (std::vector< std::string > &files, std::function< int(std::string const &)> override_confirm, ForwardCompatibilitySubstitutionRule rule)
void save_user_presets (AppConfig &config, std::vector< std::string > &need_to_delete_list)
void remove_users_preset (AppConfig &config, std::map< std::string, std::map< std::string, std::string > > *my_presets=nullptr)
void update_user_presets_directory (const std::string preset_folder)
void remove_user_presets_directory (const std::string preset_folder)
void update_system_preset_setting_ids (std::map< std::string, std::map< std::string, std::string > > &system_presets)
bool validate_printers (const std::string &name, DynamicPrintConfig &config)
Preset * get_preset_differed_for_save (Preset &preset)
int get_differed_values_to_update (Preset &preset, std::map< std::string, std::string > &key_values)
Semver get_vendor_profile_version (std::string vendor_name)
PresetsConfigSubstitutions load_project_embedded_presets (std::vector< Preset * > project_presets, ForwardCompatibilitySubstitutionRule substitution_rule)
std::vector< Preset * > get_current_project_embedded_presets ()
void reset_project_embedded_presets ()
std::string get_texture_for_printer_model (std::string model_name)
std::string get_stl_model_for_printer_model (std::string model_name)
std::string get_hotend_model_for_printer_model (std::string model_name)
void export_selections (AppConfig &config)
void set_num_filaments (unsigned int n, std::string new_col="")
unsigned int sync_ams_list (unsigned int &unknowns)
bool is_the_only_edited_filament (unsigned int filament_index)
void update_selections (AppConfig &config)
void set_calibrate_printer (std::string name)
PresetCollection & materials (PrinterTechnology pt)
const PresetCollection & materials (PrinterTechnology pt) const
bool has_defauls_only () const
DynamicPrintConfig full_config () const
DynamicPrintConfig full_config_secure () const
void load_config_from_wizard (const std::string &name, DynamicPrintConfig config, Semver file_version, bool is_custom_defined=false)
void load_config_model (const std::string &name, DynamicPrintConfig config, Semver file_version=Semver())
ConfigSubstitutions load_config_file (const std::string &path, ForwardCompatibilitySubstitutionRule compatibility_rule)
std::pair< PresetsConfigSubstitutions, size_t > load_vendor_configs_from_json (const std::string &path, const std::string &vendor_name, LoadConfigBundleAttributes flags, ForwardCompatibilitySubstitutionRule compatibility_rule)
std::vector< std::string > export_current_configs (const std::string &path, std::function< int(std::string const &)> override_confirm, bool include_modify, bool export_system_settings=false)
void set_default_suppressed (bool default_suppressed)
void set_filament_preset (size_t idx, const std::string &name)
void update_multi_material_filament_presets ()
void update_compatible (PresetSelectCompatibleType select_other_print_if_incompatible, PresetSelectCompatibleType select_other_filament_if_incompatible)
void update_compatible (PresetSelectCompatibleType select_other_if_incompatible)
void load_installed_printers (const AppConfig &config)
const std::string & get_preset_name_by_alias (const Preset::Type &preset_type, const std::string &alias) const
void save_changes_for_preset (const std::string &new_name, Preset::Type type, const std::vector< std::string > &unselected_options, bool save_to_project=false)
Public Attributes
PresetCollection prints
PresetCollection sla_prints
PresetCollection filaments
PresetCollection sla_materials
PrinterPresetCollection printers
PhysicalPrinterCollection physical_printers
std::vector< std::string > filament_presets
std::vector< DynamicPrintConfig > filament_ams_list
Preset const * calibrate_printer = nullptr
std::set< Preset const * > calibrate_filaments
DynamicPrintConfig project_config
VendorMap vendors
ObsoletePresets obsolete_presets
Static Public Attributes
static const char * BBL_BUNDLE = "Custom"
static const char * BBL_DEFAULT_PRINTER_MODEL = "MyKlipper 0.4 nozzle"
static const char * BBL_DEFAULT_PRINTER_VARIANT = "0.4"
static const char * BBL_DEFAULT_FILAMENT = "My Generic PLA"
Private Member Functions
std::pair< PresetsConfigSubstitutions, std::string > load_system_presets_from_json (ForwardCompatibilitySubstitutionRule compatibility_rule)
std::vector< std::string > merge_presets (PresetBundle &&other)
void update_system_maps ()
void load_installed_filaments (AppConfig &config)
void load_installed_sla_materials (AppConfig &config)
void load_config_file_config (const std::string &name_or_path, bool is_external, DynamicPrintConfig &&config, Semver file_version=Semver(), bool selected=false, bool is_custom_defined=false)
DynamicPrintConfig full_fff_config () const
DynamicPrintConfig full_sla_config () const
Detailed Description
Class Documentation
Slic3r::PresetBundle::ObsoletePresets
struct Slic3r::PresetBundle::ObsoletePresets
Class Members
vector< string > filaments
vector< string > printers
vector< string > prints
vector< string > sla_materials
vector< string > sla_prints
Slic3r::PresetBundle::PresetPreferences
struct Slic3r::PresetBundle::PresetPreferences
Class Members
string filament
string printer_model_id
string printer_variant
string sla_material
Member Typedef Documentation
LoadConfigBundleAttributes
using Slic3r::PresetBundle::LoadConfigBundleAttributes = enum_bitmask<LoadConfigBundleAttribute>
Member Enumeration Documentation
LoadConfigBundleAttribute
enum Slic3r::PresetBundle::LoadConfigBundleAttribute
Enumerator
SaveImported
ResetUserProfile
LoadSystem
LoadVendorOnly
{
        // Save the profiles, which have been loaded.
        SaveImported,
        // Delete all old config profiles before loading.
        ResetUserProfile,
        // Load a system config bundle.
        LoadSystem,
        LoadVendorOnly,
    };
Constructor & Destructor Documentation
PresetBundle() [1/2]
Slic3r::PresetBundle::PresetBundle ()
    : prints(Preset::TYPE_PRINT, Preset::print_options(), static_cast<const PrintRegionConfig &>(FullPrintConfig::defaults()))
    , filaments(Preset::TYPE_FILAMENT, Preset::filament_options(), static_cast<const PrintRegionConfig &>(FullPrintConfig::defaults()), "Default Filament")
    , sla_materials(Preset::TYPE_SLA_MATERIAL, Preset::sla_material_options(), static_cast<const SLAMaterialConfig &>(SLAFullPrintConfig::defaults()))
    , sla_prints(Preset::TYPE_SLA_PRINT, Preset::sla_print_options(), static_cast<const SLAPrintObjectConfig &>(SLAFullPrintConfig::defaults()))
    , printers(Preset::TYPE_PRINTER, Preset::printer_options(), static_cast<const PrintRegionConfig &>(FullPrintConfig::defaults()), "Default Printer")
    , physical_printers(PhysicalPrinter::printer_options())
{
    // The following keys are handled by the UI, they do not have a counterpart in any StaticPrintConfig derived classes,
    // therefore they need to be handled differently. As they have no counterpart in StaticPrintConfig, they are not being
    // initialized based on PrintConfigDef(), but to empty values (zeros, empty vectors, empty strings).
    //
    // "compatible_printers", "compatible_printers_condition", "inherits",
    // "print_settings_id", "filament_settings_id", "printer_settings_id", "printer_settings_id"
    // "printer_model", "printer_variant", "default_print_profile", "default_filament_profile"
    // Create the ID config keys, as they are not part of the Static print config classes.
    this->prints.default_preset().config.optptr("print_settings_id", true);
    this->prints.default_preset().compatible_printers_condition();
    this->prints.default_preset().inherits();
    this->filaments.default_preset().config.option<ConfigOptionStrings>("filament_settings_id", true)->values = {""};
    this->filaments.default_preset().compatible_printers_condition();
    this->filaments.default_preset().inherits();
    // Set all the nullable values to nils.
    this->filaments.default_preset().config.null_nullables();
    this->sla_materials.default_preset().config.optptr("sla_material_settings_id", true);
    this->sla_materials.default_preset().compatible_printers_condition();
    this->sla_materials.default_preset().inherits();
    this->sla_prints.default_preset().config.optptr("sla_print_settings_id", true);
    this->sla_prints.default_preset().config.opt_string("filename_format", true) = "[input_filename_base].sl1";
    this->sla_prints.default_preset().compatible_printers_condition();
    this->sla_prints.default_preset().inherits();
    //this->printers.add_default_preset(Preset::sla_printer_options(), static_cast<const SLAMaterialConfig &>(SLAFullPrintConfig::defaults()), "- default SLA -");
    //this->printers.preset(1).printer_technology_ref() = ptSLA;
    for (size_t i = 0; i < 1; ++i) {
        // The following ugly switch is to avoid printers.preset(0) to return the edited instance, as the 0th default is the current one.
        Preset &preset = this->printers.default_preset(i);
        for (const char *key : {"printer_settings_id", "printer_model", "printer_variant", "thumbnails"}) preset.config.optptr(key, true);
        //if (i == 0) {
            preset.config.optptr("default_print_profile", true);
            preset.config.option<ConfigOptionStrings>("default_filament_profile", true);
        //} else {
        //    preset.config.optptr("default_sla_print_profile", true);
        //    preset.config.optptr("default_sla_material_profile", true);
        //}
        // default_sla_material_profile
        preset.inherits();
    }
    // Re-activate the default presets, so their "edited" preset copies will be updated with the additional configuration values above.
    this->prints.select_preset(0);
    this->sla_prints.select_preset(0);
    this->filaments.select_preset(0);
    this->sla_materials.select_preset(0);
    this->printers.select_preset(0);
    this->project_config.apply_only(FullPrintConfig::defaults(), s_project_options);
}
References Slic3r::ConfigBase::apply_only(), Slic3r::Preset::compatible_printers_condition(), Slic3r::Preset::config, Slic3r::PresetCollection::default_preset(), filaments, Slic3r::Preset::inherits(), Slic3r::ConfigBase::null_nullables(), Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), Slic3r::DynamicConfig::optptr(), printers, prints, project_config, Slic3r::s_project_options, Slic3r::PresetCollection::select_preset(), sla_materials, and sla_prints.
PresetBundle() [2/2]
Slic3r::PresetBundle::PresetBundle (const PresetBundle & rhs)
{
    *this = rhs;
}
Member Function Documentation
copy_files()
void Slic3r::PresetBundle::copy_files (const std::string & from)
{
    boost::filesystem::path data_dir = boost::filesystem::path(Slic3r::data_dir());
    // list of searched paths based on current directory system in setup_directories()
    // do not copy cache and snapshots
    boost::filesystem::path from_data_dir = boost::filesystem::path(from);
    //BBS: change directoties by design
    std::initializer_list<boost::filesystem::path> from_dirs= {
        //from_data_dir / "vendor",
        // Store the print/filament/printer presets at the same location as the upstream Slic3r.
        from_data_dir / PRESET_PRINT_NAME,
        from_data_dir / PRESET_FILAMENT_NAME,
        from_data_dir / PRESET_PRINTER_NAME
    };
    // copy recursively all files
    //BBS: change directoties by design
    for (const boost::filesystem::path& from_dir : from_dirs) {
        copy_dir(from_dir, data_dir /"old"/from_dir.filename());
    }
}
References Slic3r::copy_dir(), Slic3r::data_dir(), PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, and PRESET_PRINTER_NAME.
Referenced by Slic3r::GUI::GUI_App::copy_older_config().
export_current_configs()
std::vector< std::string > Slic3r::PresetBundle::export_current_configs (const std::string & path, std::function< int(std::string const &)> override_confirm, bool include_modify, bool export_system_settings = false)
{
    const Preset &print_preset    = include_modify ? prints.get_edited_preset() : prints.get_selected_preset();
    const Preset &printer_preset  = include_modify ? printers.get_edited_preset() : printers.get_selected_preset();
    std::set<Preset const *> presets { &print_preset, &printer_preset };
    for (auto &f : filament_presets) {
        auto filament_preset = filaments.find_preset(f, include_modify);
        if (filament_preset) presets.insert(filament_preset);
    }
    int overwrite = 0;
    std::vector<std::string> result;
    for (auto preset : presets) {
        if ((preset->is_system  && !export_system_settings) || preset->is_default)
            continue;
        std::string file = path + "/" + preset->name + ".json";
        if (overwrite == 0) overwrite = 1;
        if (boost::filesystem::exists(file) && overwrite < 2) {
            overwrite = override_confirm(preset->name);
            if (overwrite == 0 || overwrite == 2)
                continue;
        }
        preset->config.save_to_json(file, preset->name, "", preset->version.to_string());
        result.push_back(file);
    }
    return result;
}
References Slic3r::f(), filament_presets, filaments, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::name, printers, and prints.
export_selections()
void Slic3r::PresetBundle::export_selections (AppConfig & config)
{
  assert(this->printers.get_edited_preset().printer_technology() != ptFFF || filament_presets.size() >= 1);
  //assert(this->printers.get_edited_preset().printer_technology() != ptFFF || filament_presets.size() > 1 || filaments.get_selected_preset_name() == filament_presets.front());
    config.clear_section("presets");
    auto printer_name = printers.get_selected_preset_name();
    config.set("presets", PRESET_PRINTER_NAME, printer_name);
    config.clear_printer_settings(printer_name);
    config.set_printer_setting(printer_name, PRESET_PRINTER_NAME, printer_name);
    config.set_printer_setting(printer_name, PRESET_PRINT_NAME, prints.get_selected_preset_name());
    config.set_printer_setting(printer_name, PRESET_FILAMENT_NAME,     filament_presets.front());
    config.set_printer_setting(printer_name, "curr_bed_type", config.get("curr_bed_type"));
    for (unsigned i = 1; i < filament_presets.size(); ++i) {
        char name[64];
        assert(!filament_presets[i].empty());
        sprintf(name, "filament_%02u", i);
        config.set_printer_setting(printer_name, name, filament_presets[i]);
    }
    CNumericLocalesSetter locales_setter;
    std::string           filament_colors = boost::algorithm::join(project_config.option<ConfigOptionStrings>("filament_colour")->values, ",");
    config.set_printer_setting(printer_name, "filament_colors", filament_colors);
    std::string flush_volumes_matrix = boost::algorithm::join(project_config.option<ConfigOptionFloats>("flush_volumes_matrix")->values |
                                                             boost::adaptors::transformed(static_cast<std::string (*)(double)>(std::to_string)),
                                                         "|");
    config.set_printer_setting(printer_name, "flush_volumes_matrix", flush_volumes_matrix);
    std::string flush_volumes_vector = boost::algorithm::join(project_config.option<ConfigOptionFloats>("flush_volumes_vector")->values |
                                                             boost::adaptors::transformed(static_cast<std::string (*)(double)>(std::to_string)),
                                                         "|");
    config.set_printer_setting(printer_name, "flush_volumes_vector", flush_volumes_vector);
    auto flush_multi_opt = project_config.option<ConfigOptionFloat>("flush_multiplier");
    config.set("flush_multiplier", std::to_string(flush_multi_opt ? flush_multi_opt->getFloat() : 1.0f));
    // BBS
    //config.set("presets", "sla_print",    sla_prints.get_selected_preset_name());
    //config.set("presets", "sla_material", sla_materials.get_selected_preset_name());
    //config.set("presets", "physical_printer", physical_printers.get_selected_full_printer_name());
    //BBS: add config related log
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": printer %1%, print %2%, filaments[0] %3% ")%printers.get_selected_preset_name() % prints.get_selected_preset_name() %filament_presets[0];
}
References Slic3r::AppConfig::clear_printer_settings(), Slic3r::AppConfig::clear_section(), Slic3r::empty(), filament_presets, Slic3r::flush_volumes_vector(), Slic3r::AppConfig::get(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::ConfigBase::option(), PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, Slic3r::Preset::printer_technology(), printers, prints, project_config, Slic3r::ptFFF, Slic3r::AppConfig::set(), Slic3r::AppConfig::set_printer_setting(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), Slic3r::GUI::GuideFrame::apply_config(), Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::GUI_App::check_and_save_current_preset_changes(), Slic3r::GUI::GuideFrame::run(), and Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers().
full_config()
DynamicPrintConfig Slic3r::PresetBundle::full_config () const
{
    return (this->printers.get_edited_preset().printer_technology() == ptFFF) ?
        this->full_fff_config() :
        this->full_sla_config();
}
References full_fff_config(), full_sla_config(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::Preset::printer_technology(), printers, and Slic3r::ptFFF.
Referenced by full_config_secure(), Slic3r::GUI::Plater::priv::on_select_bed_type(), and Slic3r::GUI::Plater::reslice().
full_config_secure()
DynamicPrintConfig Slic3r::PresetBundle::full_config_secure () const
{
    DynamicPrintConfig config = this->full_config();
    //FIXME legacy, the keys should not be there after conversion to a Physical Printer profile.
    config.erase("print_host");
    config.erase("print_host_webui");
    config.erase("printhost_apikey");
    config.erase("printhost_cafile");    return config;
}
References Slic3r::DynamicConfig::erase(), and full_config().
full_fff_config()
DynamicPrintConfig Slic3r::PresetBundle::full_fff_config () const private
{
    DynamicPrintConfig out;
    out.apply(FullPrintConfig::defaults());
    out.apply(this->prints.get_edited_preset().config);
    // Add the default filament preset to have the "filament_preset_id" defined.
  out.apply(this->filaments.default_preset().config);
  out.apply(this->printers.get_edited_preset().config);
    out.apply(this->project_config);
    // BBS
    size_t  num_filaments = this->filament_presets.size();
    auto* extruder_diameter = dynamic_cast<const ConfigOptionFloats*>(out.option("nozzle_diameter"));
    // Collect the "compatible_printers_condition" and "inherits" values over all presets (print, filaments, printers) into a single vector.
    std::vector<std::string> compatible_printers_condition;
    std::vector<std::string> compatible_prints_condition;
    std::vector<std::string> inherits;
    std::vector<std::string> filament_ids;
    std::vector<std::string> print_compatible_printers;
    //BBS: add logic for settings check between different system presets
    std::vector<std::string> different_settings;
    std::string different_print_settings, different_printer_settings;
    compatible_printers_condition.emplace_back(this->prints.get_edited_preset().compatible_printers_condition());
    const ConfigOptionStrings* compatible_printers =  (const_cast<PresetBundle*>(this))->prints.get_edited_preset().config.option<ConfigOptionStrings>("compatible_printers", false);
    if (compatible_printers)
        print_compatible_printers = compatible_printers->values;
    //BBS: add logic for settings check between different system presets
    std::string print_inherits = this->prints.get_edited_preset().inherits();
    inherits                     .emplace_back(print_inherits);
    const Preset* print_parent_preset =  this->prints.get_selected_preset_parent();
    if (print_parent_preset) {
        std::vector<std::string> dirty_options = this->prints.dirty_options_without_option_list(&(this->prints.get_edited_preset()), print_parent_preset, ignore_settings_list, false);
        if (!dirty_options.empty()) {
            different_print_settings = Slic3r::escape_strings_cstyle(dirty_options);
        }
    }
    different_settings.emplace_back(different_print_settings);
    if (num_filaments <= 1) {
        out.apply(this->filaments.get_edited_preset().config);
        compatible_printers_condition.emplace_back(this->filaments.get_edited_preset().compatible_printers_condition());
        compatible_prints_condition  .emplace_back(this->filaments.get_edited_preset().compatible_prints_condition());
        //BBS: add logic for settings check between different system presets
        //std::string filament_inherits = this->filaments.get_edited_preset().inherits();
        std::string current_preset_name = this->filament_presets[0];
        const Preset* preset = this->filaments.find_preset(current_preset_name, true);
        std::string filament_inherits = preset->inherits();
        inherits                     .emplace_back(filament_inherits);
        filament_ids.emplace_back(this->filaments.get_edited_preset().filament_id);
        std::string different_filament_settings;
        const Preset* filament_parent_preset =  this->filaments.get_selected_preset_parent();
        if (filament_parent_preset) {
            std::vector<std::string> dirty_options = this->filaments.dirty_options_without_option_list(&(this->filaments.get_edited_preset()), filament_parent_preset, ignore_settings_list, false);
            if (!dirty_options.empty()) {
                different_filament_settings = Slic3r::escape_strings_cstyle(dirty_options);
            }
        }
        different_settings.emplace_back(different_filament_settings);
    } else {
        // Retrieve filament presets and build a single config object for them.
        // First collect the filament configurations based on the user selection of this->filament_presets.
        // Here this->filaments.find_preset() and this->filaments.first_visible() return the edited copy of the preset if active.
        std::vector<const DynamicPrintConfig*> filament_configs;
        std::vector<const Preset*> filament_presets;
        for (const std::string& filament_preset_name : this->filament_presets) {
            const Preset* preset = this->filaments.find_preset(filament_preset_name, true);
            filament_presets.emplace_back(preset);
            filament_configs.emplace_back(&(preset->config));
        }
        while (filament_configs.size() < num_filaments) {
            const Preset* preset = &this->filaments.first_visible();
            filament_presets.emplace_back(preset);
            filament_configs.emplace_back(&(preset->config));
        }
        for (int index = 0; index < num_filaments; index++) {
            const DynamicPrintConfig *cfg = filament_configs[index];
            const Preset *preset = filament_presets[index];
            // The compatible_prints/printers_condition() returns a reference to configuration key, which may not yet exist.
            DynamicPrintConfig &cfg_rw = *const_cast<DynamicPrintConfig*>(cfg);
            compatible_printers_condition.emplace_back(Preset::compatible_printers_condition(cfg_rw));
            compatible_prints_condition  .emplace_back(Preset::compatible_prints_condition(cfg_rw));
            //BBS: add logic for settings check between different system presets
            std::string filament_inherits = Preset::inherits(cfg_rw);
            inherits                     .emplace_back(filament_inherits);
            filament_ids.emplace_back(preset->filament_id);
            std::string different_filament_settings;
            const Preset* filament_parent_preset = nullptr;
            if (preset->is_system || preset->is_default) {
                bool is_selected = this->filaments.get_selected_preset_name() == preset->name;
                if (is_selected) {
                    //use the real preset
                    filament_parent_preset = const_cast<PresetBundle*>(this)->filaments.find_preset(preset->name, false, true);
                }
                else {
                    filament_parent_preset = preset;
                }
            }
            else if (!filament_inherits.empty())
                filament_parent_preset =  const_cast<PresetBundle*>(this)->filaments.find_preset(filament_inherits, false, true);
            if (filament_parent_preset) {
                std::vector<std::string> dirty_options = cfg_rw.diff(filament_parent_preset->config);
                if (!dirty_options.empty()) {
                    auto iter = dirty_options.begin();
                    while (iter != dirty_options.end()) {
                        if (ignore_settings_list.find(*iter) != ignore_settings_list.end()) {
                            iter = dirty_options.erase(iter);
                        }
                        else {
                            ++iter;
                        }
                    }
                    different_filament_settings = Slic3r::escape_strings_cstyle(dirty_options);
                }
            }
            different_settings.emplace_back(different_filament_settings);
        }
        // loop through options and apply them to the resulting config.
        for (const t_config_option_key &key : this->filaments.default_preset().config.keys()) {
      if (key == "compatible_prints" || key == "compatible_printers")
        continue;
            // Get a destination option.
            ConfigOption *opt_dst = out.option(key, false);
            if (opt_dst->is_scalar()) {
                // Get an option, do not create if it does not exist.
                const ConfigOption *opt_src = filament_configs.front()->option(key);
                if (opt_src != nullptr)
                    opt_dst->set(opt_src);
            } else {
                // BBS
                ConfigOptionVectorBase* opt_vec_dst = static_cast<ConfigOptionVectorBase*>(opt_dst);
                {
                    std::vector<const ConfigOption*> filament_opts(num_filaments, nullptr);
                    // Setting a vector value from all filament_configs.
                    for (size_t i = 0; i < filament_opts.size(); ++i)
                        filament_opts[i] = filament_configs[i]->option(key);
                    opt_vec_dst->set(filament_opts);
                }
            }
        }
    }
    //BBS: add logic for settings check between different system presets
    std::string printer_inherits = this->printers.get_edited_preset().inherits();
    // Don't store the "compatible_printers_condition" for the printer profile, there is none.
    inherits                     .emplace_back(printer_inherits);
    const Preset* printer_parent_preset =  this->printers.get_selected_preset_parent();
    if (printer_parent_preset) {
        std::vector<std::string> dirty_options = this->printers.dirty_options_without_option_list(&(this->printers.get_edited_preset()), printer_parent_preset, ignore_settings_list, false);
        if (!dirty_options.empty()) {
            different_printer_settings = Slic3r::escape_strings_cstyle(dirty_options);
        }
    }
    different_settings.emplace_back(different_printer_settings);
    // These value types clash between the print and filament profiles. They should be renamed.
    out.erase("compatible_prints");
    out.erase("compatible_prints_condition");
    out.erase("compatible_printers");
    out.erase("compatible_printers_condition");
    out.erase("inherits");
    //BBS: add logic for settings check between different system presets
    out.erase("different_settings_to_system");
    static const char *keys[] = { "support_filament", "support_interface_filament" };
    for (size_t i = 0; i < sizeof(keys) / sizeof(keys[0]); ++ i) {
        std::string key = std::string(keys[i]);
        auto *opt = dynamic_cast<ConfigOptionInt*>(out.option(key, false));
        assert(opt != nullptr);
        opt->value = boost::algorithm::clamp<int>(opt->value, 0, int(num_filaments));
    }
    out.option<ConfigOptionString >("print_settings_id",    true)->value  = this->prints.get_selected_preset_name();
    out.option<ConfigOptionStrings>("filament_settings_id", true)->values = this->filament_presets;
    out.option<ConfigOptionString >("printer_settings_id",  true)->value  = this->printers.get_selected_preset_name();
    out.option<ConfigOptionStrings>("filament_ids", true)->values = filament_ids;
    // Serialize the collected "compatible_printers_condition" and "inherits" fields.
    // There will be 1 + num_exturders fields for "inherits" and 2 + num_extruders for "compatible_printers_condition" stored.
    // The vector will not be stored if all fields are empty strings.
    auto add_if_some_non_empty = [&out](std::vector<std::string> &&values, const std::string &key) {
        bool nonempty = false;
        for (const std::string &v : values)
            if (! v.empty()) {
                nonempty = true;
                break;
            }
        if (nonempty)
            out.set_key_value(key, new ConfigOptionStrings(std::move(values)));
    };
    add_if_some_non_empty(std::move(compatible_printers_condition), "compatible_machine_expression_group");
    add_if_some_non_empty(std::move(compatible_prints_condition),   "compatible_process_expression_group");
    add_if_some_non_empty(std::move(inherits),                      "inherits_group");
    //BBS: add logic for settings check between different system presets
    add_if_some_non_empty(std::move(different_settings),            "different_settings_to_system");
    add_if_some_non_empty(std::move(print_compatible_printers),     "print_compatible_printers");
  out.option<ConfigOptionEnumGeneric>("printer_technology", true)->value = ptFFF;
    return out;
}
References Slic3r::ConfigBase::apply(), Slic3r::Preset::compatible_printers_condition(), Slic3r::Preset::compatible_printers_condition(), Slic3r::Preset::compatible_prints_condition(), Slic3r::Preset::compatible_prints_condition(), Slic3r::Preset::config, Slic3r::PresetCollection::default_preset(), Slic3r::DynamicConfig::diff(), Slic3r::PresetCollection::dirty_options_without_option_list(), Slic3r::escape_strings_cstyle(), Slic3r::Preset::filament_id, filament_presets, filaments, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::ignore_settings_list, Slic3r::Preset::inherits(), Slic3r::Preset::inherits(), Slic3r::Preset::is_default, Slic3r::ConfigOption::is_scalar(), Slic3r::Preset::is_system, Slic3r::DynamicConfig::keys(), Slic3r::Preset::name, Slic3r::ConfigBase::option(), out, printers, prints, project_config, Slic3r::ptFFF, Slic3r::ConfigOption::set(), Slic3r::ConfigOptionVectorBase::set(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by full_config().
full_sla_config()
DynamicPrintConfig Slic3r::PresetBundle::full_sla_config () const private
{
    DynamicPrintConfig out;
    out.apply(SLAFullPrintConfig::defaults());
    out.apply(this->sla_prints.get_edited_preset().config);
    out.apply(this->sla_materials.get_edited_preset().config);
    out.apply(this->printers.get_edited_preset().config);
    // There are no project configuration values as of now, the project_config is reserved for FFF printers.
//    out.apply(this->project_config);
    // Collect the "compatible_printers_condition" and "inherits" values over all presets (sla_prints, sla_materials, printers) into a single vector.
    std::vector<std::string> compatible_printers_condition;
  std::vector<std::string> compatible_prints_condition;
    std::vector<std::string> inherits;
    compatible_printers_condition.emplace_back(this->sla_prints.get_edited_preset().compatible_printers_condition());
  inherits           .emplace_back(this->sla_prints.get_edited_preset().inherits());
    compatible_printers_condition.emplace_back(this->sla_materials.get_edited_preset().compatible_printers_condition());
  compatible_prints_condition  .emplace_back(this->sla_materials.get_edited_preset().compatible_prints_condition());
    inherits                     .emplace_back(this->sla_materials.get_edited_preset().inherits());
    inherits                     .emplace_back(this->printers.get_edited_preset().inherits());
    // These two value types clash between the print and filament profiles. They should be renamed.
    out.erase("compatible_printers");
    out.erase("compatible_printers_condition");
    out.erase("inherits");
    out.option<ConfigOptionString >("sla_print_settings_id",    true)->value  = this->sla_prints.get_selected_preset_name();
    out.option<ConfigOptionString >("sla_material_settings_id", true)->value  = this->sla_materials.get_selected_preset_name();
    out.option<ConfigOptionString >("printer_settings_id",      true)->value  = this->printers.get_selected_preset_name();
    // Serialize the collected "compatible_printers_condition" and "inherits" fields.
    // There will be 1 + num_exturders fields for "inherits" and 2 + num_extruders for "compatible_printers_condition" stored.
    // The vector will not be stored if all fields are empty strings.
    auto add_if_some_non_empty = [&out](std::vector<std::string> &&values, const std::string &key) {
        bool nonempty = false;
        for (const std::string &v : values)
            if (! v.empty()) {
                nonempty = true;
                break;
            }
        if (nonempty)
            out.set_key_value(key, new ConfigOptionStrings(std::move(values)));
    };
    add_if_some_non_empty(std::move(compatible_printers_condition), "compatible_machine_expression_group");
    add_if_some_non_empty(std::move(compatible_prints_condition),   "compatible_process_expression_group");
    add_if_some_non_empty(std::move(inherits),                      "inherits_group");
  out.option<ConfigOptionEnumGeneric>("printer_technology", true)->value = ptSLA;
  return out;
}
References Slic3r::ConfigBase::apply(), Slic3r::Preset::compatible_printers_condition(), Slic3r::Preset::compatible_prints_condition(), Slic3r::Preset::config, Slic3r::DynamicConfig::erase(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::Preset::inherits(), Slic3r::ConfigBase::option(), out, printers, Slic3r::ptSLA, sla_materials, and sla_prints.
Referenced by full_config().
get_current_project_embedded_presets()
std::vector< Preset * > Slic3r::PresetBundle::get_current_project_embedded_presets ()
{
    std::vector<Preset*> project_presets;
    project_presets = this->prints.get_project_embedded_presets();
    auto filament_presets = this->filaments.get_project_embedded_presets();
    if (!filament_presets.empty())
        std::copy(filament_presets.begin(), filament_presets.end(), std::back_inserter(project_presets));
    auto printer_presets = this->printers.get_project_embedded_presets();
    if (!printer_presets.empty())
        std::copy(printer_presets.begin(), printer_presets.end(), std::back_inserter(project_presets));
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" finished, returned project_presets count %1%")%project_presets.size();
    return project_presets;
}
References filament_presets, filaments, Slic3r::PresetCollection::get_project_embedded_presets(), printers, and prints.
Referenced by Slic3r::GUI::Plater::export_3mf().
get_differed_values_to_update()
int Slic3r::PresetBundle::get_differed_values_to_update (Preset & preset, std::map< std::string, std::string > & key_values)
{
    PresetCollection* preset_collection;
    switch(preset.type) {
        case Preset::TYPE_PRINT:
            preset_collection = &(this->prints);
            break;
        case Preset::TYPE_PRINTER:
            preset_collection = &(this->printers);
            break;
        case Preset::TYPE_FILAMENT:
            preset_collection = &(this->filaments);
            break;
        default:
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" invalid type %1%, return directly")%preset.type;
            return -1;
    }
    return preset_collection->get_differed_values_to_update(preset, key_values);
}
References filaments, Slic3r::PresetCollection::get_differed_values_to_update(), printers, prints, Slic3r::Preset::type, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, and Slic3r::Preset::TYPE_PRINTER.
Referenced by Slic3r::GUI::GUI_App::sync_preset().
get_hotend_model_for_printer_model()
std::string Slic3r::PresetBundle::get_hotend_model_for_printer_model (std::string model_name)
{
    std::string hotend_stl, vendor_name, out;
    for (auto vendor_profile: this->vendors)
    {
        for (auto vendor_model: vendor_profile.second.models)
        {
            if (vendor_model.name == model_name)
            {
                hotend_stl = vendor_model.hotend_model;
                vendor_name = vendor_profile.first;
                break;
            }
        }
    }
    if (!hotend_stl.empty())
    {
        out = Slic3r::data_dir() + "/vendor/" + vendor_name + "/" + hotend_stl;
        if (!boost::filesystem::exists(boost::filesystem::path(out)))
            out = Slic3r::resources_dir() + "/profiles/" + vendor_name + "/" + hotend_stl;
    }
    if (out.empty() ||!boost::filesystem::exists(boost::filesystem::path(out)))
        out = Slic3r::resources_dir() + "/profiles/hotend.stl";
    return out;
}
References Slic3r::data_dir(), out, Slic3r::resources_dir(), and vendors.
Referenced by Slic3r::GUI::GCodeViewer::init().
get_preset_differed_for_save()
Preset * Slic3r::PresetBundle::get_preset_differed_for_save (Preset & preset)
{
    PresetCollection* preset_collection;
    switch(preset.type) {
        case Preset::TYPE_PRINT:
            preset_collection = &(this->prints);
            break;
        case Preset::TYPE_PRINTER:
            preset_collection = &(this->printers);
            break;
        case Preset::TYPE_FILAMENT:
            preset_collection = &(this->filaments);
            break;
        default:
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" invalid type %1%, return directly")%preset.type;
            return nullptr;
    }
    return preset_collection->get_preset_differed_for_save(preset);
}
References filaments, Slic3r::PresetCollection::get_preset_differed_for_save(), printers, prints, Slic3r::Preset::type, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, and Slic3r::Preset::TYPE_PRINTER.
get_preset_name_by_alias()
const std::string & Slic3r::PresetBundle::get_preset_name_by_alias (const Preset::Type & preset_type, const std::string & alias) const
{
    // there are not aliases for Printers profiles
    if (preset_type == Preset::TYPE_PRINTER || preset_type == Preset::TYPE_INVALID)
        return alias;
    const PresetCollection& presets = preset_type == Preset::TYPE_PRINT     ? prints :
                                      preset_type == Preset::TYPE_SLA_PRINT ? sla_prints :
                                      preset_type == Preset::TYPE_FILAMENT  ? filaments :
                                      sla_materials;
    return presets.get_preset_name_by_alias(alias);
}
References filaments, Slic3r::PresetCollection::get_preset_name_by_alias(), prints, sla_materials, sla_prints, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, and Slic3r::Preset::TYPE_SLA_PRINT.
Referenced by load_selections().
get_stl_model_for_printer_model()
std::string Slic3r::PresetBundle::get_stl_model_for_printer_model (std::string model_name)
{
    std::string stl_name, vendor_name, out;
    for (auto vendor_profile: this->vendors)
    {
        for (auto vendor_model: vendor_profile.second.models)
        {
            if (vendor_model.name == model_name)
            {
                stl_name = vendor_model.bed_model;
                vendor_name = vendor_profile.first;
                break;
            }
        }
    }
    if (!stl_name.empty())
    {
        out = Slic3r::data_dir() + "/vendor/" + vendor_name + "/" + stl_name;
        if (!boost::filesystem::exists(boost::filesystem::path(out)))
            out = Slic3r::resources_dir() + "/profiles/" + vendor_name + "/" + stl_name;
    }
    return out;
}
References Slic3r::data_dir(), out, Slic3r::resources_dir(), and vendors.
get_texture_for_printer_model()
std::string Slic3r::PresetBundle::get_texture_for_printer_model (std::string model_name)
{
    std::string texture_name, vendor_name, out;
    for (auto vendor_profile: this->vendors)
    {
        for (auto vendor_model: vendor_profile.second.models)
        {
            if (vendor_model.name == model_name)
            {
                texture_name = vendor_model.bed_texture;
                vendor_name = vendor_profile.first;
                break;
            }
        }
    }
    if (!texture_name.empty())
    {
        out = Slic3r::data_dir() + "/vendor/" + vendor_name + "/" + texture_name;
        if (!boost::filesystem::exists(boost::filesystem::path(out)))
            out = Slic3r::resources_dir() + "/profiles/" + vendor_name + "/" + texture_name;
    }
    return out;
}
References Slic3r::data_dir(), out, Slic3r::resources_dir(), and vendors.
get_vendor_profile_version()
Semver Slic3r::PresetBundle::get_vendor_profile_version (std::string vendor_name)
{
    Semver result_ver;
    auto vendor_profile = vendors.find(vendor_name);
    if (vendor_profile != vendors.end()) {
        result_ver = vendor_profile->second.config_version;
    }
    return result_ver;
}
References vendors.
Referenced by Slic3r::GUI::GUI_App::start_sync_user_preset().
has_defauls_only()
bool Slic3r::PresetBundle::has_defauls_only () const inline
        { return prints.has_defaults_only() && filaments.has_defaults_only() && printers.has_defaults_only(); }
References filaments, Slic3r::PresetCollection::has_defaults_only(), printers, and prints.
import_presets()
PresetsConfigSubstitutions Slic3r::PresetBundle::import_presets (std::vector< std::string > & files, std::function< int(std::string const &)> override_confirm, ForwardCompatibilitySubstitutionRule rule)
{
    PresetsConfigSubstitutions substitutions;
    int overwrite = 0;
    std::vector<std::string>   result;
    for (auto &file : files) {
        if (Slic3r::is_json_file(file)) {
            try {
                DynamicPrintConfig config;
                // BBS: change to json format
                // ConfigSubstitutions config_substitutions = config.load_from_ini(preset.file, substitution_rule);
                std::map<std::string, std::string> key_values;
                std::string                        reason;
                ConfigSubstitutions                config_substitutions = config.load_from_json(file, rule, key_values, reason);
                std::string name = key_values[BBL_JSON_KEY_NAME];
                std::string version_str = key_values[BBL_JSON_KEY_VERSION];
                boost::optional<Semver> version = Semver::parse(version_str);
                if (!version) continue;
                Semver app_version = *(Semver::parse(SLIC3R_VERSION));
                if (version->maj() != app_version.maj()) {
                    BOOST_LOG_TRIVIAL(warning) << "Preset incompatibla, not loading: " << name;
                    continue;
                }
                PresetCollection * collection = nullptr;
                if (config.has("printer_settings_id"))
                    collection = &printers;
                else if (config.has("print_settings_id"))
                    collection = &prints;
                else if (config.has("filament_settings_id"))
                    collection = &filaments;
                if (collection == nullptr) {
                    BOOST_LOG_TRIVIAL(warning) << "Preset type is unknown, not loading: " << name;
                    continue;
                }
                if (overwrite == 0) overwrite = 1;
                if (auto p = collection->find_preset(name, false)) {
                    if (p->is_default || p->is_system) {
                        BOOST_LOG_TRIVIAL(warning) << "Preset already present and is system preset, not loading: " << name;
                        continue;
                    }
                    overwrite = override_confirm(name);
                }
                if (overwrite == 0 || overwrite == 2) {
                    BOOST_LOG_TRIVIAL(warning) << "Preset already present, not loading: " << name;
                    continue;
                }
                DynamicPrintConfig new_config;
                Preset *      inherit_preset  = nullptr;
                ConfigOption *inherits_config = config.option(BBL_JSON_KEY_INHERITS);
                std::string        inherits_value;
                if (inherits_config) {
                    ConfigOptionString *option_str     = dynamic_cast<ConfigOptionString *>(inherits_config);
                    inherits_value = option_str->value;
                    inherit_preset = collection->find_preset(inherits_value, false, true);
                }
                if (inherit_preset) {
                    new_config = inherit_preset->config;
                } else {
                    // Find a default preset for the config. The PrintPresetCollection provides different default preset based on the "printer_technology" field.
                    // new_config = default_preset.config;
                    // we should skip this preset here
                    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(", can not find inherit preset for user preset %1%, just skip") % name;
                    continue;
                }
                new_config.apply(std::move(config));
                Preset &preset     = collection->load_preset(collection->path_from_name(name), name, std::move(new_config), false);
                preset.is_external = true;
                preset.version     = *version;
                inherit_preset     = collection->find_preset(inherits_value, false, true); // pointer maybe wrong after insert, redo find
                if (inherit_preset)
                    preset.base_id     = inherit_preset->setting_id;
                Preset::normalize(preset.config);
                // Report configuration fields, which are misplaced into a wrong group.
                const Preset &default_preset = collection->default_preset_for(new_config);
                std::string incorrect_keys = Preset::remove_invalid_keys(preset.config, default_preset.config);
                if (!incorrect_keys.empty())
                    BOOST_LOG_TRIVIAL(error) << "Error in a preset file: The preset \"" << preset.file << "\" contains the following incorrect keys: " << incorrect_keys
                                                << ", which were removed";
                if (!config_substitutions.empty())
                    substitutions.push_back({name, collection->type(), PresetConfigSubstitutions::Source::UserFile, file, std::move(config_substitutions)});
                preset.save(inherit_preset ? &inherit_preset->config : nullptr);
                result.push_back(file);
            } catch (const std::ifstream::failure &err) {
                BOOST_LOG_TRIVIAL(error) << boost::format("The config cannot be loaded: %1%. Reason: %2%") % file % err.what();
            } catch (const std::runtime_error &err) {
                BOOST_LOG_TRIVIAL(error) << boost::format("Failed importing config file: %1%. Reason: %2%") % file % err.what();
            }
        }
    }
    files = result;
    return substitutions;
}
References Slic3r::ConfigBase::apply(), Slic3r::Preset::base_id, BBL_JSON_KEY_INHERITS, BBL_JSON_KEY_NAME, BBL_JSON_KEY_VERSION, Slic3r::Preset::config, Slic3r::PresetCollection::default_preset_for(), error, filaments, Slic3r::Preset::file, Slic3r::PresetCollection::find_preset(), Slic3r::ConfigOptionResolver::has(), Slic3r::Preset::is_external, Slic3r::is_json_file(), Slic3r::ConfigBase::load_from_json(), Slic3r::PresetCollection::load_preset(), Slic3r::Semver::maj(), Slic3r::Preset::normalize(), Slic3r::ConfigBase::option(), Slic3r::Semver::parse(), Slic3r::PresetCollection::path_from_name(), printers, prints, Slic3r::Preset::remove_invalid_keys(), Slic3r::Preset::save(), Slic3r::Preset::setting_id, Slic3r::PresetCollection::type(), Slic3r::PresetConfigSubstitutions::UserFile, Slic3r::ConfigOptionSingle< T >::value, and Slic3r::Preset::version.
is_the_only_edited_filament()
bool Slic3r::PresetBundle::is_the_only_edited_filament (unsigned int filament_index)
{
    int n = this->filament_presets.size();
    if (filament_index >= n)
        return false;
    std::string name = this->filament_presets[filament_index];
    Preset& edited_preset = this->filaments.get_edited_preset();
    if (edited_preset.name != name)
        return false;
    int index = 0;
    while (index < n)
    {
        if (index == filament_index) {
            index ++;
            continue;
        }
        std::string filament_preset = this->filament_presets[index];
        if (edited_preset.name == filament_preset)
            return false;
        else
            index ++;
    }
    return true;
}
References filament_presets, filaments, Slic3r::PresetCollection::get_edited_preset(), n, and Slic3r::Preset::name.
load_config_file()
ConfigSubstitutions Slic3r::PresetBundle::load_config_file (const std::string & path, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
  if (is_gcode_file(path)) {
    DynamicPrintConfig config;
        //BBS: add config related logs
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, gcodefile %1%, compatibility_rule %2%")%path %compatibility_rule;
    config.apply(FullPrintConfig::defaults());
        ConfigSubstitutions config_substitutions = config.load_from_gcode_file(path, compatibility_rule);
        Preset::normalize(config);
    load_config_file_config(path, true, std::move(config));
    return config_substitutions;
  }
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" can not load config file %1% not from gcode")%path ;
    throw Slic3r::RuntimeError(std::string("Unknown configuration file: ") + path);
    // 1) Try to load the config file into a boost property tree.
    /*boost::property_tree::ptree tree;
    try {
        boost::nowide::ifstream ifs(path);
        boost::property_tree::read_ini(ifs, tree);
    } catch (const std::ifstream::failure &err) {
        throw Slic3r::RuntimeError(std::string("The Config Bundle cannot be loaded: ") + path + "\n\tReason: " + err.what());
    } catch (const boost::property_tree::file_parser_error &err) {
        throw Slic3r::RuntimeError(format("Failed loading the Config Bundle \"%1%\": %2% at line %3%",
          err.filename(), err.message(), err.line()));
    } catch (const std::runtime_error &err) {
        throw Slic3r::RuntimeError(std::string("Failed loading the preset file: ") + path + "\n\tReason: " + err.what());
    }
    // 2) Continue based on the type of the configuration file.
    ConfigFileType config_file_type = guess_config_file_type(tree);
    ConfigSubstitutions config_substitutions;
    try {
        switch (config_file_type) {
        case CONFIG_FILE_TYPE_UNKNOWN:
            throw Slic3r::RuntimeError(std::string("Unknown configuration file type: ") + path);
        case CONFIG_FILE_TYPE_APP_CONFIG:
            throw Slic3r::RuntimeError(std::string("Invalid configuration file: ") + path + ". This is an application config file.");
      case CONFIG_FILE_TYPE_CONFIG:
      {
        // Initialize a config from full defaults.
        DynamicPrintConfig config;
        config.apply(FullPrintConfig::defaults());
            config_substitutions = config.load(tree, compatibility_rule);
        Preset::normalize(config);
        load_config_file_config(path, true, std::move(config));
            //BBS: add config related logs
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": normal config, finished, got %1% substitutions")%config_substitutions.size();
            return config_substitutions;
        }
        case CONFIG_FILE_TYPE_CONFIG_BUNDLE:
            //BBS: add config related logs
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": found config bundle");
            return load_config_file_config_bundle(path, tree, compatibility_rule);
        }
    } catch (const ConfigurationError &e) {
        throw Slic3r::RuntimeError(format("Invalid configuration file %1%: %2%", path, e.what()));
    }
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(" finished, should not be here");
    // This shall never happen. Suppres compiler warnings.
    assert(false);*/
    return ConfigSubstitutions{};
}
References Slic3r::ConfigBase::apply(), Slic3r::is_gcode_file(), load_config_file_config(), Slic3r::ConfigBase::load_from_gcode_file(), and Slic3r::Preset::normalize().
load_config_file_config()
void Slic3r::PresetBundle::load_config_file_config (const std::string & name_or_path, bool is_external, DynamicPrintConfig && config, Semver file_version = Semver(), bool selected = false, bool is_custom_defined = false) private
{
    PrinterTechnology printer_technology = Preset::printer_technology(config);
    auto clear_compatible_printers = [](DynamicPrintConfig& config){
        ConfigOption *opt_compatible = config.optptr("compatible_printers");
        if (opt_compatible != nullptr) {
            assert(opt_compatible->type() == coStrings);
            if (opt_compatible->type() == coStrings)
                static_cast<ConfigOptionStrings*>(opt_compatible)->values.clear();
        }
    };
    clear_compatible_printers(config);
#if 0
    size_t num_extruders = (printer_technology == ptFFF) ?
        std::min(config.option<ConfigOptionFloats>("nozzle_diameter"  )->values.size(),
                 config.option<ConfigOptionFloats>("filament_diameter")->values.size()) :
    // 1 SLA material
        1;
#else
    // BBS: use filament_colour insteadof filament_settings_id, filament_settings_id sometimes is not generated
    size_t num_filaments = config.option<ConfigOptionStrings>("filament_colour")->size();
#endif
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": , name_or_path %1%, is_external %2%, num_filaments %3%") % name_or_path % is_external % num_filaments;
    // Make a copy of the "compatible_machine_expression_group" and "inherits_group" vectors, which
    // accumulate values over all presets (print, filaments, printers).
    // These values will be distributed into their particular presets when loading.
    std::vector<std::string> compatible_printers_condition_values   = std::move(config.option<ConfigOptionStrings>("compatible_machine_expression_group", true)->values);
    std::vector<std::string> compatible_prints_condition_values     = std::move(config.option<ConfigOptionStrings>("compatible_process_expression_group",   true)->values);
    std::vector<std::string> inherits_values                        = std::move(config.option<ConfigOptionStrings>("inherits_group", true)->values);
    std::vector<std::string> filament_ids                           = std::move(config.option<ConfigOptionStrings>("filament_ids", true)->values);
    std::vector<std::string> print_compatible_printers              = std::move(config.option<ConfigOptionStrings>("print_compatible_printers", true)->values);
    //BBS: add different settings check logic
    bool has_different_settings_to_system                           = config.option("different_settings_to_system")?true:false;
    std::vector<std::string> different_values                       = std::move(config.option<ConfigOptionStrings>("different_settings_to_system", true)->values);
    std::string &compatible_printers_condition  = Preset::compatible_printers_condition(config);
    std::string &compatible_prints_condition    = Preset::compatible_prints_condition(config);
    std::string &inherits                       = Preset::inherits(config);
    compatible_printers_condition_values.resize(num_filaments + 2, std::string());
    compatible_prints_condition_values.resize(num_filaments, std::string());
    inherits_values.resize(num_filaments + 2, std::string());
    different_values.resize(num_filaments + 2, std::string());
    filament_ids.resize(num_filaments, std::string());
    // The "default_filament_profile" will be later extracted into the printer profile.
  switch (printer_technology) {
  case ptFFF:
    config.option<ConfigOptionString>("default_print_profile", true);
        config.option<ConfigOptionStrings>("default_filament_profile", true);
    break;
  case ptSLA:
    config.option<ConfigOptionString>("default_sla_print_profile", true);
    config.option<ConfigOptionString>("default_sla_material_profile", true);
    break;
    default: break;
  }
    // 1) Create a name from the file name.
    // Keep the suffix (.ini, .gcode, .amf, .3mf etc) to differentiate it from the normal profiles.
    std::string name = is_external ? boost::filesystem::path(name_or_path).filename().string() : name_or_path;
    // 2) If the loading succeeded, split and load the config into print / filament / printer settings.
    // First load the print and printer presets.
  auto load_preset =
    [&config, &inherits, &inherits_values,
         &compatible_printers_condition, &compatible_printers_condition_values,
         &compatible_prints_condition, &compatible_prints_condition_values,
         is_external, &name, &name_or_path, file_version, selected, is_custom_defined]
    (PresetCollection &presets, size_t idx, const std::string &key, const std::set<std::string> &different_keys, std::string filament_id) {
    // Split the "compatible_printers_condition" and "inherits" values one by one from a single vector to the print & printer profiles.
    inherits = inherits_values[idx];
    compatible_printers_condition = compatible_printers_condition_values[idx];
        if (idx > 0 && idx - 1 < compatible_prints_condition_values.size())
            compatible_prints_condition = compatible_prints_condition_values[idx - 1];
        //BBS: add config related logs
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": , name %1%, is_external %2%, inherits %3%")%name %is_external %inherits;
    if (is_external)
      presets.load_external_preset(name_or_path, name, config.opt_string(key, true), config, different_keys, PresetCollection::LoadAndSelect::Always, file_version, filament_id);
    else
      presets.load_preset(presets.path_from_name(name), name, config, selected, file_version, is_custom_defined).save(nullptr);
  };
    switch (Preset::printer_technology(config)) {
    case ptFFF:
    {
        //BBS: add different settings logic
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": load print preset from print_settings_id");
        std::vector<std::string> print_different_keys_vector;
        std::string print_different_settings = different_values[0];
        Slic3r::unescape_strings_cstyle(print_different_settings, print_different_keys_vector);
        std::set<std::string> print_different_keys_set(print_different_keys_vector.begin(), print_different_keys_vector.end());
        //if (!has_different_settings_to_system) {
        //    print_different_keys_set.clear();
        //}
        //else
            print_different_keys_set.insert(ignore_settings_list.begin(), ignore_settings_list.end());
        if (!print_compatible_printers.empty()) {
            ConfigOptionStrings* compatible_printers = config.option<ConfigOptionStrings>("compatible_printers", true);
            compatible_printers->values = print_compatible_printers;
        }
        load_preset(this->prints, 0, "print_settings_id", print_different_keys_set, std::string());
        //clear compatible printers
        clear_compatible_printers(config);
        std::vector<std::string> printer_different_keys_vector;
        std::string printer_different_settings = different_values[num_filaments + 1];
        Slic3r::unescape_strings_cstyle(printer_different_settings, printer_different_keys_vector);
        std::set<std::string> printer_different_keys_set(printer_different_keys_vector.begin(), printer_different_keys_vector.end());
        //if (!has_different_settings_to_system) {
        //    printer_different_keys_set.clear();
        //}
        //else
            printer_different_keys_set.insert(ignore_settings_list.begin(), ignore_settings_list.end());
        //BBS: add config related logs
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": load printer preset from printer_settings_id");
        load_preset(this->printers, num_filaments + 1, "printer_settings_id", printer_different_keys_set, std::string());
        // 3) Now load the filaments. If there are multiple filament presets, split them and load them.
        auto old_filament_profile_names = config.option<ConfigOptionStrings>("filament_settings_id", true);
        old_filament_profile_names->values.resize(num_filaments, std::string());
        if (num_filaments <= 1) {
            // Split the "compatible_printers_condition" and "inherits" from the cummulative vectors to separate filament presets.
            inherits                      = inherits_values[1];
            compatible_printers_condition = compatible_printers_condition_values[1];
      compatible_prints_condition   = compatible_prints_condition_values.front();
      Preset                *loaded = nullptr;
            //BBS: add different settings logic
            std::vector<std::string> filament_different_keys_vector;
            std::string filament_different_settings = different_values[1];
            Slic3r::unescape_strings_cstyle(filament_different_settings, filament_different_keys_vector);
            std::set<std::string> filament_different_keys_set(filament_different_keys_vector.begin(), filament_different_keys_vector.end());
            //if (!has_different_settings_to_system) {
            //    filament_different_keys_set.clear();
            //}
            //else
                filament_different_keys_set.insert(ignore_settings_list.begin(), ignore_settings_list.end());
            std::string filament_id = filament_ids[0];
            //BBS: add config related logs
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": load single filament preset from filament_settings_id");
            if (is_external)
                loaded = this->filaments.load_external_preset(name_or_path, name, old_filament_profile_names->values.front(), config, filament_different_keys_set, PresetCollection::LoadAndSelect::Always, file_version, filament_id).first;
            else {
                // called from Config Wizard.
        loaded= &this->filaments.load_preset(this->filaments.path_from_name(name), name, config, true, file_version, is_custom_defined);
        loaded->save(nullptr);
      }
            this->filament_presets.clear();
      this->filament_presets.emplace_back(loaded->name);
        } else {
            assert(is_external);
            // Split the filament presets, load each of them separately.
            std::vector<DynamicPrintConfig> configs(num_filaments, this->filaments.default_preset().config);
            // loop through options and scatter them into configs.
            for (const t_config_option_key &key : this->filaments.default_preset().config.keys()) {
                const ConfigOption *other_opt = config.option(key);
                if (other_opt == nullptr)
                    continue;
                if (other_opt->is_scalar()) {
                    for (size_t i = 0; i < configs.size(); ++ i)
                        configs[i].option(key, false)->set(other_opt);
                }
                else if (key != "compatible_printers" && key != "compatible_prints") {
                    for (size_t i = 0; i < configs.size(); ++i)
                        static_cast<ConfigOptionVectorBase*>(configs[i].option(key, false))->set_at(other_opt, 0, i);
                }
            }
            // Load the configs into this->filaments and make them active.
            this->filament_presets = std::vector<std::string>(configs.size());
            // To avoid incorrect selection of the first filament preset (means a value of Preset->m_idx_selected)
            // in a case when next added preset take a place of previosly selected preset,
            // we should add presets from last to first
            bool any_modified = false;
            //BBS: add config related logs
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": load multiple filament preset from filament_settings_id");
            for (int i = (int)configs.size()-1; i >= 0; i--) {
                DynamicPrintConfig &cfg = configs[i];
                // Split the "compatible_printers_condition" and "inherits" from the cummulative vectors to separate filament presets.
                cfg.opt_string("compatible_printers_condition", true) = compatible_printers_condition_values[i + 1];
                cfg.opt_string("compatible_prints_condition",   true) = compatible_prints_condition_values[i];
                cfg.opt_string("inherits", true)                      = inherits_values[i + 1];
                //BBS: add different settings logic
                std::vector<std::string> filament_different_keys_vector;
                std::string filament_different_settings = different_values[i+1];
                Slic3r::unescape_strings_cstyle(filament_different_settings, filament_different_keys_vector);
                std::set<std::string> filament_different_keys_set(filament_different_keys_vector.begin(), filament_different_keys_vector.end());
                //if (!has_different_settings_to_system) {
                //    filament_different_keys_set.clear();
                //}
                //else
                    filament_different_keys_set.insert(ignore_settings_list.begin(), ignore_settings_list.end());
                std::string filament_id = filament_ids[i];
                // Load all filament presets, but only select the first one in the preset dialog.
                auto [loaded, modified] = this->filaments.load_external_preset(name_or_path, name,
                    (i < int(old_filament_profile_names->values.size())) ? old_filament_profile_names->values[i] : "",
                    std::move(cfg),
                    filament_different_keys_set,
                    i == 0 ?
                        PresetCollection::LoadAndSelect::Always :
                    any_modified ?
                        PresetCollection::LoadAndSelect::Never :
                        PresetCollection::LoadAndSelect::OnlyIfModified,
                    file_version,
                    filament_id);
                any_modified |= modified;
                this->filament_presets[i] = loaded->name;
            }
        }
        // 4) Load the project config values (the per extruder wipe matrix etc).
        this->project_config.apply_only(config, s_project_options);
        break;
    }
    case ptSLA:
    {
        /*std::set<std::string> different_keys_set;
        load_preset(this->sla_prints, 0, "sla_print_settings_id", different_keys_set);
        load_preset(this->sla_materials, 1, "sla_material_settings_id", different_keys_set);
        load_preset(this->printers, 2, "printer_settings_id", different_keys_set);*/
        break;
    }
    default:
        break;
    }
  this->update_compatible(PresetSelectCompatibleType::Never);
    this->update_multi_material_filament_presets();
    //BBS
    //const std::string &physical_printer = config.option<ConfigOptionString>("physical_printer_settings_id", true)->value;
    const std::string physical_printer;
    if (this->printers.get_edited_preset().is_external || physical_printer.empty()) {
        this->physical_printers.unselect_printer();
    } else {
        // Activate the physical printer profile if possible.
        PhysicalPrinter *pp = this->physical_printers.find_printer(physical_printer, true);
        if (pp != nullptr && std::find(pp->preset_names.begin(), pp->preset_names.end(), this->printers.get_edited_preset().name) != pp->preset_names.end())
            this->physical_printers.select_printer(pp->name, this->printers.get_edited_preset().name);
        else
            this->physical_printers.unselect_printer();
    }
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": finished");
}
References Slic3r::PresetCollection::Always, Slic3r::ConfigBase::apply_only(), Slic3r::ConfigOptionVector< T >::clear(), Slic3r::Preset::compatible_printers_condition(), Slic3r::Preset::compatible_prints_condition(), Slic3r::Preset::config, Slic3r::coStrings, Slic3r::PresetCollection::default_preset(), filament_presets, filaments, Slic3r::PhysicalPrinterCollection::find_printer(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::ignore_settings_list, Slic3r::Preset::inherits(), Slic3r::Preset::is_external, Slic3r::ConfigOption::is_scalar(), Slic3r::DynamicConfig::keys(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::Preset::name, Slic3r::PhysicalPrinter::name, Slic3r::Never, Slic3r::PresetCollection::Never, Slic3r::PresetCollection::OnlyIfModified, Slic3r::DynamicConfig::opt_string(), Slic3r::PresetCollection::path_from_name(), physical_printers, Slic3r::PhysicalPrinter::preset_names, Slic3r::printer_technology(), Slic3r::Preset::printer_technology(), printers, prints, project_config, Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::s_project_options, Slic3r::Preset::save(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::ConfigOption::set(), Slic3r::ConfigOptionVector< T >::size(), size, Slic3r::ConfigOption::type(), Slic3r::unescape_strings_cstyle(), Slic3r::PhysicalPrinterCollection::unselect_printer(), update_compatible(), update_multi_material_filament_presets(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by load_config_file(), load_config_from_wizard(), and load_config_model().
load_config_from_wizard()
void Slic3r::PresetBundle::load_config_from_wizard (const std::string & name, DynamicPrintConfig config, Semver file_version, bool is_custom_defined = false) inline
        { this->load_config_file_config(name, false, std::move(config), file_version, true, is_custom_defined); }
References load_config_file_config().
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config().
load_config_model()
void Slic3r::PresetBundle::load_config_model (const std::string & name, DynamicPrintConfig config, Semver file_version = Semver()) inline
        { this->load_config_file_config(name, true, std::move(config), file_version); }
References load_config_file_config().
Referenced by Slic3r::GUI::Plater::priv::load_files().
load_installed_filaments()
void Slic3r::PresetBundle::load_installed_filaments (AppConfig & config) private
{
    //if (! config.has_section(AppConfig::SECTION_FILAMENTS)
    //    || config.get_section(AppConfig::SECTION_FILAMENTS).empty()) {
        // Compatibility with the PrusaSlicer 2.1.1 and older, where the filament profiles were not installable yet.
        // Find all filament profiles, which are compatible with installed printers, and act as if these filament profiles
        // were installed.
        std::unordered_set<const Preset*> compatible_filaments;
        for (const Preset &printer : printers)
            if (printer.is_visible && printer.printer_technology() == ptFFF && printer.vendor && (!printer.vendor->models.empty())) {
                bool add_default_materials = true;
                if (config.has_section(AppConfig::SECTION_FILAMENTS))
                {
                    const std::map<std::string, std::string>& installed_filament = config.get_section(AppConfig::SECTION_FILAMENTS);
                    for (auto filament_iter : installed_filament)
                    {
                        Preset* filament = filaments.find_preset(filament_iter.first, false, true);
                        if (filament && is_compatible_with_printer(PresetWithVendorProfile(*filament, filament->vendor), PresetWithVendorProfile(printer, printer.vendor)))
{
                            //already has compatible filament
                            add_default_materials = false;
                            break;
                        }
                    }
                }
                if (!add_default_materials)
                    continue;
                const VendorProfile::PrinterModel *printer_model = PresetUtils::system_printer_model(printer);
                if (!printer_model) {
                    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": can not find printer_model for printer %1%")%printer.name;
                    continue;
                }
                for (auto default_filament: printer_model->default_materials)
                {
                    Preset* filament = filaments.find_preset(default_filament, false, true);
                    if (filament && filament->is_system)
                        compatible_filaments.insert(filament);
                }
                //const PresetWithVendorProfile printer_with_vendor_profile = printers.get_preset_with_vendor_profile(printer);
                //for (const Preset &filament : filaments)
                //  if (filament.is_system && is_compatible_with_printer(filaments.get_preset_with_vendor_profile(filament), printer_with_vendor_profile))
                //      compatible_filaments.insert(&filament);
            }
        // and mark these filaments as installed, therefore this code will not be executed at the next start of the application.
        for (const auto &filament: compatible_filaments)
            config.set(AppConfig::SECTION_FILAMENTS, filament->name, "true");
    //}
    for (auto &preset : filaments)
        preset.set_visible_from_appconfig(config);
}
References filaments, Slic3r::PresetCollection::find_preset(), Slic3r::AppConfig::get_section(), Slic3r::AppConfig::has_section(), Slic3r::is_compatible_with_printer(), Slic3r::Preset::is_system, Slic3r::printer_model(), printers, Slic3r::ptFFF, Slic3r::AppConfig::SECTION_FILAMENTS, Slic3r::AppConfig::set(), Slic3r::PresetUtils::system_printer_model(), and Slic3r::Preset::vendor.
Referenced by load_selections().
load_installed_printers()
void Slic3r::PresetBundle::load_installed_printers (const AppConfig & config)
{
  this->update_system_maps();
    for (auto &preset : printers)
        preset.set_visible_from_appconfig(config);
}
References printers, and update_system_maps().
Referenced by load_selections().
load_installed_sla_materials()
void Slic3r::PresetBundle::load_installed_sla_materials (AppConfig & config) private
{
    if (! config.has_section(AppConfig::SECTION_MATERIALS)) {
        std::unordered_set<const Preset*> comp_sla_materials;
    // Compatibility with the PrusaSlicer 2.1.1 and older, where the SLA material profiles were not installable yet.
    // Find all SLA material profiles, which are compatible with installed printers, and act as if these SLA material profiles
    // were installed.
        for (const Preset &printer : printers)
            if (printer.is_visible && printer.printer_technology() == ptSLA) {
        const PresetWithVendorProfile printer_with_vendor_profile = printers.get_preset_with_vendor_profile(printer);
        for (const Preset &material : sla_materials)
          if (material.is_system && is_compatible_with_printer(sla_materials.get_preset_with_vendor_profile(material), printer_with_vendor_profile))
            comp_sla_materials.insert(&material);
      }
    // and mark these SLA materials as installed, therefore this code will not be executed at the next start of the application.
    for (const auto &material: comp_sla_materials)
            config.set(AppConfig::SECTION_MATERIALS, material->name, "true");
    }
    for (auto &preset : sla_materials)
        preset.set_visible_from_appconfig(config);
}
References Slic3r::PresetCollection::get_preset_with_vendor_profile(), Slic3r::AppConfig::has_section(), Slic3r::is_compatible_with_printer(), printers, Slic3r::ptSLA, Slic3r::AppConfig::SECTION_MATERIALS, Slic3r::AppConfig::set(), and sla_materials.
Referenced by load_selections().
load_presets()
PresetsConfigSubstitutions Slic3r::PresetBundle::load_presets (AppConfig & config, ForwardCompatibilitySubstitutionRule rule, const PresetPreferences & preferred_selection = PresetPreferences())
{
    // First load the vendor specific system presets.
    PresetsConfigSubstitutions substitutions;
    std::string errors_cummulative;
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" enter, substitution_rule %1%, preferred printer_model_id %2%")%substitution_rule%preferred_selection.printer_model_id;
    //BBS: change system config to json
    std::tie(substitutions, errors_cummulative) = this->load_system_presets_from_json(substitution_rule);
    // BBS load preset from user's folder, load system default if
    // BBS: change directories by design
    std::string dir_user_presets = config.get("preset_folder");
    if (dir_user_presets.empty()) {
        load_user_presets(DEFAULT_USER_FOLDER_NAME, substitution_rule);
    } else {
        load_user_presets(dir_user_presets, substitution_rule);
    }
    this->update_multi_material_filament_presets();
    this->update_compatible(PresetSelectCompatibleType::Never);
    this->load_selections(config, preferred_selection);
    set_calibrate_printer("");
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" finished, returned substitutions %1%")%substitutions.size();
    return substitutions;
}
References DEFAULT_USER_FOLDER_NAME, Slic3r::AppConfig::get(), load_selections(), load_system_presets_from_json(), load_user_presets(), Slic3r::Never, Slic3r::PresetBundle::PresetPreferences::printer_model_id, set_calibrate_printer(), update_compatible(), and update_multi_material_filament_presets().
Referenced by Slic3r::GUI::ConfigWizard::priv::apply_config(), and Slic3r::GUI::GuideFrame::apply_config().
load_project_embedded_presets()
PresetsConfigSubstitutions Slic3r::PresetBundle::load_project_embedded_presets (std::vector< Preset * > project_presets, ForwardCompatibilitySubstitutionRule substitution_rule)
{
    // First load the vendor specific system presets.
    PresetsConfigSubstitutions substitutions;
    std::string errors_cummulative;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, substitution_rule %1%, preset toltal count %2%")%substitution_rule% project_presets.size();
    try {
        this->prints.load_project_embedded_presets(project_presets, PRESET_PRINT_NAME, substitutions, substitution_rule);
    } catch (const std::runtime_error &err) {
        errors_cummulative += err.what();
    }
    try {
        this->filaments.load_project_embedded_presets(project_presets, PRESET_FILAMENT_NAME, substitutions, substitution_rule);
    } catch (const std::runtime_error &err) {
        errors_cummulative += err.what();
    }
    try {
        this->printers.load_project_embedded_presets(project_presets, PRESET_PRINTER_NAME, substitutions, substitution_rule);
    } catch (const std::runtime_error &err) {
        errors_cummulative += err.what();
    }
    //this->update_multi_material_filament_presets();
    //this->update_compatible(PresetSelectCompatibleType::Never);
    if (! errors_cummulative.empty())
        throw Slic3r::RuntimeError(errors_cummulative);
    //this->load_selections(config, "");
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" finished, returned substitutions %1%")%substitutions.size();
    return substitutions;
}
References filaments, Slic3r::PresetCollection::load_project_embedded_presets(), PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, printers, and prints.
Referenced by Slic3r::GUI::Plater::priv::load_files().
load_selections()
void Slic3r::PresetBundle::load_selections (AppConfig & config, const PresetPreferences & preferred_selection = PresetPreferences())
{
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": enter, preferred printer_model_id %1%")%preferred_selection.printer_model_id;
  // Update visibility of presets based on application vendor / model / variant configuration.
  this->load_installed_printers(config);
    // Update visibility of filament and sla material presets
    this->load_installed_filaments(config);
    this->load_installed_sla_materials(config);
    // Parse the initial print / filament / printer profile names.
    // std::string initial_sla_print_profile_name    = remove_ini_suffix(config.get("presets", PRESET_SLA_PRINT_NAME));
    // std::string initial_sla_material_profile_name = remove_ini_suffix(config.get("presets", PRESET_SLA_MATERIALS_NAME));
  std::string initial_printer_profile_name      = remove_ini_suffix(config.get("presets", PRESET_PRINTER_NAME));
    // Activate print / filament / printer profiles from either the config,
    // or from the preferred_model_id suggestion passed in by ConfigWizard.
    // If the printer profile enumerated by the config are not visible, select an alternate preset.
    // Do not select alternate profiles for the print / filament profiles as those presets
    // will be selected by the following call of this->update_compatible(PresetSelectCompatibleType::Always).
    const Preset *initial_printer = printers.find_preset(initial_printer_profile_name);
    // If executed due to a Config Wizard update, preferred_printer contains the first newly installed printer, otherwise nullptr.
    const Preset *preferred_printer = printers.find_system_preset_by_model_and_variant(preferred_selection.printer_model_id, preferred_selection.printer_variant);
    printers.select_preset_by_name(preferred_printer ? preferred_printer->name : initial_printer_profile_name, true);
    // Orca: load from orca_presets
    // const auto os_presets = config.get_machine_settings(initial_printer_profile_name);
    std::string initial_print_profile_name        = config.get_printer_setting(initial_printer_profile_name, PRESET_PRINT_NAME);
    std::string initial_filament_profile_name     = config.get_printer_setting(initial_printer_profile_name, PRESET_FILAMENT_NAME);
    //BBS: set default print/filament profiles to BBL's default setting
    if (preferred_printer)
    {
        const std::string& prefered_print_profile = preferred_printer->config.opt_string("default_print_profile");
        if ((!initial_print_profile_name.compare("Default Setting")) && (prefered_print_profile.size() > 0))
            initial_print_profile_name = prefered_print_profile;
        const std::vector<std::string>& prefered_filament_profiles = preferred_printer->config.option<ConfigOptionStrings>("default_filament_profile")->values;
        if ((!initial_filament_profile_name.compare("Default Filament")) && (prefered_filament_profiles.size() > 0))
            initial_filament_profile_name = prefered_filament_profiles[0];
    }
    // Selects the profile, leaves it to -1 if the initial profile name is empty or if it was not found.
    prints.select_preset_by_name_strict(initial_print_profile_name);
    filaments.select_preset_by_name_strict(initial_filament_profile_name);
  // sla_prints.select_preset_by_name_strict(initial_sla_print_profile_name);
    // sla_materials.select_preset_by_name_strict(initial_sla_material_profile_name);
    // Load the names of the other filament profiles selected for a multi-material printer.
    // Load it even if the current printer technology is SLA.
    // The possibly excessive filament names will be later removed with this->update_multi_material_filament_presets()
    // once the FFF technology gets selected.
    this->filament_presets = { filaments.get_selected_preset_name() };
    for (unsigned int i = 1; i < 1000; ++ i) {
        char name[64];
        sprintf(name, "filament_%02u", i);
        auto f_name = config.get_printer_setting(initial_printer_profile_name, name);
        if (f_name.empty())
            break;
        this->filament_presets.emplace_back(remove_ini_suffix(f_name));
    }
    std::vector<std::string> filament_colors;
    auto f_colors = config.get_printer_setting(initial_printer_profile_name, "filament_colors");
    if (!f_colors.empty()) {
        boost::algorithm::split(filament_colors, f_colors, boost::algorithm::is_any_of(","));
    }
    filament_colors.resize(filament_presets.size(), "#FF8040");
    project_config.option<ConfigOptionStrings>("filament_colour")->values = filament_colors;
    std::vector<std::string> matrix;
    if (config.has_printer_setting(initial_printer_profile_name, "flush_volumes_matrix")) {
        boost::algorithm::split(matrix, config.get_printer_setting(initial_printer_profile_name, "flush_volumes_matrix"), boost::algorithm::is_any_of("|"));
        auto flush_volumes_matrix = matrix | boost::adaptors::transformed(boost::lexical_cast<double, std::string>);
        project_config.option<ConfigOptionFloats>("flush_volumes_matrix")->values = std::vector<double>(flush_volumes_matrix.begin(), flush_volumes_matrix.end());
    }
    if (config.has_printer_setting(initial_printer_profile_name, "flush_volumes_vector")) {
        boost::algorithm::split(matrix, config.get_printer_setting(initial_printer_profile_name, "flush_volumes_vector"), boost::algorithm::is_any_of("|"));
        auto flush_volumes_vector = matrix | boost::adaptors::transformed(boost::lexical_cast<double, std::string>);
        project_config.option<ConfigOptionFloats>("flush_volumes_vector")->values = std::vector<double>(flush_volumes_vector.begin(), flush_volumes_vector.end());
    }
    if (config.has("app", "flush_multiplier")) {
        std::string str_flush_multiplier = config.get("app", "flush_multiplier");
        if (!str_flush_multiplier.empty())
            project_config.option<ConfigOptionFloat>("flush_multiplier")->set(new ConfigOptionFloat(std::stof(str_flush_multiplier)));
    }
    // Update visibility of presets based on their compatibility with the active printer.
    // Always try to select a compatible print and filament preset to the current printer preset,
    // as the application may have been closed with an active "external" preset, which does not
    // exist.
    this->update_compatible(PresetSelectCompatibleType::Always);
    this->update_multi_material_filament_presets();
    if (initial_printer != nullptr && (preferred_printer == nullptr || initial_printer == preferred_printer)) {
        // Don't run the following code, as we want to activate default filament / SLA material profiles when installing and selecting a new printer.
        // Only run this code if just a filament / SLA material was installed by Config Wizard for an active Printer.
        auto printer_technology = printers.get_selected_preset().printer_technology();
        if (printer_technology == ptFFF && ! preferred_selection.filament.empty()) {
            std::string preferred_preset_name = get_preset_name_by_alias(Preset::Type::TYPE_FILAMENT, preferred_selection.filament);
            if (auto it = filaments.find_preset_internal(preferred_preset_name);
                it != filaments.end() && (it->name == preferred_preset_name ) && it->is_visible && it->is_compatible) {
                filaments.select_preset_by_name_strict(preferred_preset_name);
                this->filament_presets.front() = filaments.get_selected_preset_name();
            }
        } else if (printer_technology == ptSLA && ! preferred_selection.sla_material.empty()) {
            std::string preferred_preset_name = get_preset_name_by_alias(Preset::Type::TYPE_SLA_MATERIAL, preferred_selection.sla_material);
            if (auto it = sla_materials.find_preset_internal(preferred_preset_name);
                it != sla_materials.end() && it->is_visible && it->is_compatible)
                sla_materials.select_preset_by_name_strict(preferred_preset_name);
        }
    }
    std::string first_visible_filament_name;
    for (auto & fp : filament_presets) {
        if (auto it = filaments.find_preset_internal(fp); it == filaments.end() || !it->is_visible || !it->is_compatible) {
            if (first_visible_filament_name.empty())
                first_visible_filament_name = filaments.first_compatible().name;
            fp = first_visible_filament_name;
        }
    }
    // Parse the initial physical printer name.
    std::string initial_physical_printer_name = remove_ini_suffix(config.get("presets", "physical_printer"));
    // Activate physical printer from the config
    if (!initial_physical_printer_name.empty())
        physical_printers.select_printer(initial_physical_printer_name);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": finished, preferred printer_model_id %1%")%preferred_selection.printer_model_id;
}
References Slic3r::Always, Slic3r::Preset::config, Slic3r::PresetCollection::end(), Slic3r::PresetBundle::PresetPreferences::filament, filament_presets, filaments, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::PrinterPresetCollection::find_system_preset_by_model_and_variant(), Slic3r::PresetCollection::first_compatible(), Slic3r::flush_volumes_vector(), Slic3r::AppConfig::get(), get_preset_name_by_alias(), Slic3r::AppConfig::get_printer_setting(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::AppConfig::has(), Slic3r::AppConfig::has_printer_setting(), load_installed_filaments(), load_installed_printers(), load_installed_sla_materials(), Slic3r::Preset::name, Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), physical_printers, PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, Slic3r::PresetBundle::PresetPreferences::printer_model_id, Slic3r::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::PresetPreferences::printer_variant, printers, prints, project_config, Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::remove_ini_suffix(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::select_preset_by_name_strict(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::ConfigOptionSingle< T >::set(), Slic3r::PresetBundle::PresetPreferences::sla_material, sla_materials, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_SLA_MATERIAL, update_compatible(), and update_multi_material_filament_presets().
Referenced by load_presets(), and Slic3r::GUI::GuideFrame::run().
load_system_presets_from_json()
std::pair< PresetsConfigSubstitutions, std::string > Slic3r::PresetBundle::load_system_presets_from_json (ForwardCompatibilitySubstitutionRule compatibility_rule) private
{
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, compatibility_rule %1%")%compatibility_rule;
    if (compatibility_rule == ForwardCompatibilitySubstitutionRule::EnableSystemSilent)
        // Loading system presets, don't log substitutions.
        compatibility_rule = ForwardCompatibilitySubstitutionRule::EnableSilent;
    else if (compatibility_rule == ForwardCompatibilitySubstitutionRule::EnableSilentDisableSystem)
        // Loading system presets, throw on unknown option value.
        compatibility_rule = ForwardCompatibilitySubstitutionRule::Disable;
    // Here the vendor specific read only Config Bundles are stored.
    //BBS: change directory by design
    boost::filesystem::path     dir = (boost::filesystem::path(data_dir()) / PRESET_SYSTEM_DIR).make_preferred();
    PresetsConfigSubstitutions  substitutions;
    std::string                 errors_cummulative;
    bool                        first = true;
    for (auto &dir_entry : boost::filesystem::directory_iterator(dir))
    {
        std::string vendor_file = dir_entry.path().string();
        if (Slic3r::is_json_file(vendor_file)) {
            std::string vendor_name = dir_entry.path().filename().string();
            // Remove the .json suffix.
            vendor_name.erase(vendor_name.size() - 5);
            try {
                // Load the config bundle, flatten it.
                if (first) {
                    // Reset this PresetBundle and load the first vendor config.
                    append(substitutions, this->load_vendor_configs_from_json(dir.string(), vendor_name, PresetBundle::LoadSystem, compatibility_rule).first);
                    first = false;
                } else {
                    // Load the other vendor configs, merge them with this PresetBundle.
                    // Report duplicate profiles.
                    PresetBundle other;
                    append(substitutions, other.load_vendor_configs_from_json(dir.string(), vendor_name, PresetBundle::LoadSystem, compatibility_rule).first);
                    std::vector<std::string> duplicates = this->merge_presets(std::move(other));
                    if (! duplicates.empty()) {
                        errors_cummulative += "Found duplicated settings in vendor " + vendor_name + "'s json file lists: ";
                        for (size_t i = 0; i < duplicates.size(); ++ i) {
                            if (i > 0)
                                errors_cummulative += ", ";
                            errors_cummulative += duplicates[i];
                        }
                    }
                }
            } catch (const std::runtime_error &err) {
                errors_cummulative += err.what();
                errors_cummulative += "\n";
            }
        }
    }
    if (first) {
    // No config bundle loaded, reset.
    this->reset(false);
  }
  this->update_system_maps();
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" finished, errors_cummulative %1%")%errors_cummulative;
    return std::make_pair(std::move(substitutions), errors_cummulative);
}
References Slic3r::append(), Slic3r::data_dir(), Slic3r::Disable, Slic3r::EnableSilent, Slic3r::EnableSilentDisableSystem, Slic3r::EnableSystemSilent, Slic3r::is_json_file(), load_vendor_configs_from_json(), LoadSystem, merge_presets(), PRESET_SYSTEM_DIR, reset(), and update_system_maps().
Referenced by load_presets().
load_user_presets() [1/2]
PresetsConfigSubstitutions Slic3r::PresetBundle::load_user_presets (AppConfig & config, std::map< std::string, std::map< std::string, std::string > > & my_presets, ForwardCompatibilitySubstitutionRule rule)
{
    // First load the vendor specific system presets.
    PresetsConfigSubstitutions substitutions;
    std::string errors_cummulative;
    bool process_added = false, filament_added = false, machine_added = false;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" enter, substitution_rule %1%, preset toltal count %2%")%substitution_rule%my_presets.size();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" print's selected_idx %1%, selected_name %2%") %prints.get_selected_idx() %prints.get_selected_preset_name();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" filament's selected_idx %1%, selected_name %2%") %filaments.get_selected_idx() %filaments.get_selected_preset_name();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" printers's selected_idx %1%, selected_name %2%") %printers.get_selected_idx() %printers.get_selected_preset_name();
    // Sync removing
    remove_users_preset(config, &my_presets);
    std::map<std::string, std::map<std::string, std::string>>::iterator it;
    for (it = my_presets.begin(); it != my_presets.end(); it++) {
        std::string name = it->first;
        std::map<std::string, std::string>& value_map = it->second;
        //get the type first
        std::map<std::string, std::string>::iterator type_iter = value_map.find(BBL_JSON_KEY_TYPE);
        if (type_iter == value_map.end()) {
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(" can not find type for setting %1%")%name;
            continue;
        }
        try {
            PresetCollection *preset_collection = nullptr;
            if (type_iter->second == PRESET_IOT_PRINT_TYPE) {
                preset_collection = &(this->prints);
                process_added |= preset_collection->load_user_preset(name, value_map, substitutions, substitution_rule);
            }
            else if (type_iter->second == PRESET_IOT_FILAMENT_TYPE) {
                preset_collection = &(this->filaments);
                filament_added |= preset_collection->load_user_preset(name, value_map, substitutions, substitution_rule);
            }
            else if (type_iter->second == PRESET_IOT_PRINTER_TYPE) {
                preset_collection = &(this->printers);
                machine_added |= preset_collection->load_user_preset(name, value_map, substitutions, substitution_rule);
            }
            else {
                BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format("invalid type %1% for setting %2%") %type_iter->second %name;
                continue;
            }
        }
        catch (const std::runtime_error& err) {
            errors_cummulative += err.what();
        }
    }
    /*if (process_added) {
        this->prints.update_after_user_presets_loaded();
    }
    if (filament_added) {
        this->filaments.update_after_user_presets_loaded();
    }
    if (machine_added) {
        this->printers.update_after_user_presets_loaded();
    }*/
    this->update_multi_material_filament_presets();
    this->update_compatible(PresetSelectCompatibleType::Never);
    //this->load_selections(config, PresetPreferences());
    set_calibrate_printer("");
    if (! errors_cummulative.empty())
        throw Slic3r::RuntimeError(errors_cummulative);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" finished, process_added %1%, filament_added %2%, machine_added %3%")%process_added %filament_added %machine_added;
    return substitutions;
}
References BBL_JSON_KEY_TYPE, filaments, Slic3r::PresetCollection::get_selected_idx(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::PresetCollection::load_user_preset(), Slic3r::Never, PRESET_IOT_FILAMENT_TYPE, PRESET_IOT_PRINT_TYPE, PRESET_IOT_PRINTER_TYPE, printers, prints, remove_users_preset(), set_calibrate_printer(), update_compatible(), and update_multi_material_filament_presets().
load_user_presets() [2/2]
PresetsConfigSubstitutions Slic3r::PresetBundle::load_user_presets (std::string user, ForwardCompatibilitySubstitutionRule rule)
{
    PresetsConfigSubstitutions substitutions;
    std::string errors_cummulative;
    fs::path user_folder(data_dir() + "/" + PRESET_USER_DIR);
    if (!fs::exists(user_folder)) fs::create_directory(user_folder);
    std::string dir_user_presets = data_dir() + "/" + PRESET_USER_DIR + "/" + user;
    fs::path    folder(user_folder / user);
    if (!fs::exists(folder)) fs::create_directory(folder);
    // BBS do not load sla_print
    // BBS: change directoties by design
    try {
        std::string print_selected_preset_name = prints.get_selected_preset().name;
        this->prints.load_presets(dir_user_presets, PRESET_PRINT_NAME, substitutions, substitution_rule);
        prints.select_preset_by_name(print_selected_preset_name, false);
    } catch (const std::runtime_error &err) {
        errors_cummulative += err.what();
    }
    try {
        std::string filament_selected_preset_name = filaments.get_selected_preset().name;
        this->filaments.load_presets(dir_user_presets, PRESET_FILAMENT_NAME, substitutions, substitution_rule);
        filaments.select_preset_by_name(filament_selected_preset_name, false);
    } catch (const std::runtime_error &err) {
        errors_cummulative += err.what();
    }
    try {
        std::string printer_selected_preset_name = printers.get_selected_preset().name;
        this->printers.load_presets(dir_user_presets, PRESET_PRINTER_NAME, substitutions, substitution_rule);
        printers.select_preset_by_name(printer_selected_preset_name, false);
    } catch (const std::runtime_error &err) {
        errors_cummulative += err.what();
    }
    if (!errors_cummulative.empty()) throw Slic3r::RuntimeError(errors_cummulative);
    this->update_multi_material_filament_presets();
    this->update_compatible(PresetSelectCompatibleType::Never);
    set_calibrate_printer("");
    return PresetsConfigSubstitutions();
}
References Slic3r::data_dir(), filaments, Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::Preset::name, Slic3r::Never, PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, PRESET_USER_DIR, printers, prints, Slic3r::PresetCollection::select_preset_by_name(), set_calibrate_printer(), update_compatible(), and update_multi_material_filament_presets().
Referenced by load_presets(), Slic3r::GUI::GUI_App::reload_settings(), Slic3r::GUI::GUI_App::start_sync_user_preset(), and Slic3r::GUI::GUI_App::stop_sync_user_preset().
load_vendor_configs_from_json()
std::pair< PresetsConfigSubstitutions, size_t > Slic3r::PresetBundle::load_vendor_configs_from_json (const std::string & path, const std::string & vendor_name, LoadConfigBundleAttributes flags, ForwardCompatibilitySubstitutionRule compatibility_rule)
{
    // Enable substitutions for user config bundle, throw an exception when loading a system profile.
    ConfigSubstitutionContext  substitution_context { compatibility_rule };
    PresetsConfigSubstitutions substitutions;
    std::string vendor_system_path = data_dir() + "/" + PRESET_SYSTEM_DIR;
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, path %1%, compatibility_rule %2%")%path.c_str()%compatibility_rule;
    if (flags.has(LoadConfigBundleAttribute::ResetUserProfile) || flags.has(LoadConfigBundleAttribute::LoadSystem))
        // Reset this bundle, delete user profile files if SaveImported.
        this->reset(flags.has(LoadConfigBundleAttribute::SaveImported));
    // 1) load the vroot json and construct the vendor profile
    VendorProfile vendor_profile(vendor_name);
    std::string root_file = path + "/" + vendor_name + ".json";
    std::vector<std::pair<std::string, std::string>> machine_model_subfiles;
    std::vector<std::pair<std::string, std::string>> process_subfiles;
    std::vector<std::pair<std::string, std::string>> filament_subfiles;
    std::vector<std::pair<std::string, std::string>> machine_subfiles;
    auto get_name_and_subpath = [](json::iterator& it, std::vector<std::pair<std::string, std::string>>& subfile_map) {
        if (it.value().is_array()) {
            for (auto iter1 = it.value().begin(); iter1 != it.value().end(); iter1++) {
                if (iter1.value().is_object()) {
                    std::string name, subpath;
                    for (auto iter2 = iter1.value().begin(); iter2 != iter1.value().end(); iter2++) {
                        if (iter2.value().is_string()) {
                            if (boost::iequals(iter2.key(), BBL_JSON_KEY_NAME)) {
                                name = iter2.value();
                            } else if (boost::iequals(iter2.key(), BBL_JSON_KEY_SUB_PATH)) {
                                subpath = iter2.value();
                            }
                        }
                        else {
                            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": invalid value type for " << iter2.key();
                        }
                    }
                    if (!name.empty() && !subpath.empty())
                        subfile_map.push_back(std::make_pair(name, subpath));
                }
                else
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": invalid type for " << iter1.key();
            }
        }
        else
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": invalid type for " << it.key();
    };
    try {
        boost::nowide::ifstream ifs(root_file);
        json j;
        ifs >> j;
        //parse the json elements
        for (auto it = j.begin(); it != j.end(); it++) {
            if (boost::iequals(it.key(), BBL_JSON_KEY_VERSION)) {
                //get version
                std::string version_str = it.value();
                auto config_version = Semver::parse(version_str);
                if (! config_version) {
                    throw ConfigurationError((boost::format("vendor %1%'s config version: %2% invalid\nSuggest cleaning the directory %3% firstly")
                        % vendor_name % version_str %vendor_system_path).str());
                } else {
                    vendor_profile.config_version = std::move(*config_version);
                }
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_URL)) {
                //get url
                vendor_profile.config_update_url = it.value();
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_DESCRIPTION)) {
                //get description
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< ": parse "<<root_file<<", got description:  " << it.value();
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_NAME)) {
                //get name
                vendor_profile.name = it.value();
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_MACHINE_MODEL_LIST)) {
                //get machine model list
                get_name_and_subpath(it, machine_model_subfiles);
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_PROCESS_LIST)) {
                //get process list
                get_name_and_subpath(it, process_subfiles);
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_FILAMENT_LIST)) {
                //get filament list
                get_name_and_subpath(it, filament_subfiles);
            }
            else if (boost::iequals(it.key(), BBL_JSON_KEY_MACHINE_LIST)) {
                //get machine list
                get_name_and_subpath(it, machine_subfiles);
            }
        }
    }
    catch(nlohmann::detail::parse_error &err) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<root_file<<" got a nlohmann::detail::parse_error, reason = " << err.what();
        throw ConfigurationError((boost::format("Failed loading configuration file %1%: %2%\nSuggest cleaning the directory %3% firstly")
                %root_file %err.what() %vendor_system_path).str());
        //goto __error_process;
    }
    //2) paste the machine model
    for (auto& machine_model : machine_model_subfiles)
    {
        std::string subfile = path + "/" + vendor_name + "/" + machine_model.second;
        VendorProfile::PrinterModel model;
        model.id = machine_model.first;
        try {
            boost::nowide::ifstream ifs(subfile);
            json j;
            ifs >> j;
            //parse the json elements
            for (auto it = j.begin(); it != j.end(); it++) {
                if (boost::iequals(it.key(), BBL_JSON_KEY_VERSION)) {
                    //get version
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_URL)) {
                    //get url
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_NAME)) {
                    //get name
                    model.name = it.value();
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_MODEL_ID)) {
                    //get model_id
                    model.model_id = it.value();
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_NOZZLE_DIAMETER)) {
                    //get nozzle diameter
                    std::string nozzle_diameters = it.value();
                    std::vector<std::string> variants;
                    if (Slic3r::unescape_strings_cstyle(nozzle_diameters, variants)) {
                        for (const std::string &variant_name : variants) {
                            if (model.variant(variant_name) == nullptr)
                                model.variants.emplace_back(VendorProfile::PrinterVariant(variant_name));
                        }
                    } else {
                        BOOST_LOG_TRIVIAL(error)<< __FUNCTION__ << boost::format(": invalid nozzle_diameters %1% for Vendor %1%") % nozzle_diameters % vendor_name;
                    }
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_PRINTER_TECH)) {
                    //get printer tech
                    if (boost::algorithm::starts_with(it.value(), "SL"))
                        model.technology = ptSLA;
                    else
                        model.technology = ptFFF;
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_FAMILY)) {
                    //get family
                    model.family = it.value();
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_BED_MODEL)) {
                    //get bed model
                    model.bed_model = it.value();
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_BED_TEXTURE)) {
                    //get bed texture
                    model.bed_texture = it.value();
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_HOTEND_MODEL)) {
                    model.hotend_model = it.value();
                }
                else if (boost::iequals(it.key(), BBL_JSON_KEY_DEFAULT_MATERIALS)) {
                    //get machine list
                    std::string default_materials_field = it.value();
                    if (Slic3r::unescape_strings_cstyle(default_materials_field, model.default_materials)) {
                      Slic3r::sort_remove_duplicates(model.default_materials);
                        if (! model.default_materials.empty() && model.default_materials.front().empty())
                            // An empty material was inserted into the list of default materials. Remove it.
                            model.default_materials.erase(model.default_materials.begin());
                    } else {
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(": invalid default_materials %1% for Vendor %1%") % default_materials_field % vendor_name;
                    }
                }
            }
        }
        catch(nlohmann::detail::parse_error &err) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<< subfile <<" got a nlohmann::detail::parse_error, reason = " << err.what();
            throw ConfigurationError((boost::format("Failed loading configuration file %1%: %2%\nSuggest cleaning the directory %3% firstly")
                %subfile %err.what() %vendor_system_path).str());
        }
        if (! model.id.empty() && ! model.variants.empty())
            vendor_profile.models.push_back(std::move(model));
    }
    //insert the vendor profile
    this->vendors.emplace(vendor_name, vendor_profile);
    const VendorProfile* current_vendor_profile = &this->vendors[vendor_name];
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", loaded vendor profile, name %1%, id %2%, version %3%")%vendor_profile.name%vendor_profile.id%vendor_profile.config_version.to_string();
    if (flags.has(LoadConfigBundleAttribute::LoadVendorOnly))
        return std::make_pair(PresetsConfigSubstitutions{}, 0);
    // 3) paste the process/filament/print configs
    PresetCollection         *presets = nullptr;
    size_t                   presets_loaded = 0;
    auto parse_subfile = [path, vendor_name, presets_loaded, current_vendor_profile](\
        ConfigSubstitutionContext& substitution_context,
        PresetsConfigSubstitutions& substitutions,
        LoadConfigBundleAttributes& flags,
        std::pair<std::string, std::string>& subfile_iter,
        std::map<std::string, DynamicPrintConfig>& config_maps,
        std::map<std::string, std::string>& filament_id_maps,
        PresetCollection* presets_collection,
        size_t& count) -> std::string {
        std::string subfile = path + "/" + vendor_name + "/" + subfile_iter.second;
        // Load the print, filament or printer preset.
        std::string               preset_name;
        DynamicPrintConfig        config;
        std::string         alias_name, inherits, instantiation, setting_id, filament_id;
        std::vector<std::string>  renamed_from;
        const DynamicPrintConfig* default_config = nullptr;
        std::string               reason;
        try {
            std::map<std::string, std::string> key_values;
            substitution_context.substitutions.clear();
            //parse the json elements
            DynamicPrintConfig config_src;
            config_src.load_from_json(subfile, substitution_context, false, key_values, reason);
            if (!reason.empty()) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": load config file "<<subfile<<" Failed!";
                return reason;
            }
            preset_name = key_values[BBL_JSON_KEY_NAME];
            instantiation = key_values[BBL_JSON_KEY_INSTANTIATION];
            auto setting_it = key_values.find(BBL_JSON_KEY_SETTING_ID);
            if (setting_it != key_values.end())
                setting_id = setting_it->second;
            auto filament_it = key_values.find(BBL_JSON_KEY_FILAMENT_ID);
            if (filament_it != key_values.end())
                filament_id = filament_it->second;
            //check whether it inherits other preset or not
            auto it1 = key_values.find(BBL_JSON_KEY_INHERITS);
            if (it1 != key_values.end()) {
                inherits = it1->second;
                auto it2 = config_maps.find(inherits);
                if (it2 != config_maps.end()) {
                    default_config = &(it2->second);
                    if (filament_id.empty() && (presets_collection->type() == Preset::TYPE_FILAMENT)) {
                        auto filament_id_map_iter = filament_id_maps.find(inherits);
                        if (filament_id_map_iter != filament_id_maps.end()) {
                            filament_id = filament_id_map_iter->second;
                        }
                    }
                }
                else {
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": can not find inherits "<<inherits<<" for " << preset_name;
                    //throw ConfigurationError(format("can not find inherits %1% for %2%", inherits, preset_name));
                    reason = "Can not find inherits: " + inherits;
                    return reason;
                }
            }
            else {
                if (presets_collection->type() == Preset::TYPE_PRINTER)
                    default_config = &presets_collection->default_preset_for(config_src).config;
                else
                    default_config = &presets_collection->default_preset().config;
            }
            config = *default_config;
            config.apply(config_src);
            if (instantiation == "false") {
                config_maps.emplace(preset_name, std::move(config));
                if ((presets_collection->type() == Preset::TYPE_FILAMENT) && (!filament_id.empty()))
                    filament_id_maps.emplace(preset_name, filament_id);
                return reason;
            }
            if (config.has("alias"))
                alias_name = (dynamic_cast<const ConfigOptionString *>(config.option("alias")))->value;
            if (config.has("renamed_from")) {
                const ConfigOptionVectorBase *vec = static_cast<const ConfigOptionVectorBase*>(config.option("renamed_from"));
                renamed_from = vec->vserialize();
            }
            Preset::normalize(config);
        }
        catch(nlohmann::detail::parse_error &err) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<< subfile <<" got a nlohmann::detail::parse_error, reason = " << err.what();
            reason = std::string("json parse error") + err.what();
            return reason;
        }
        // Report configuration fields, which are misplaced into a wrong group.
        std::string incorrect_keys = Preset::remove_invalid_keys(config, *default_config);
        if (! incorrect_keys.empty())
            BOOST_LOG_TRIVIAL(error)<< __FUNCTION__  << ": The config " <<
                subfile << " contains incorrect keys: " << incorrect_keys << ", which were removed";
        if (presets_collection->type() == Preset::TYPE_PRINTER) {
            // Filter out printer presets, which are not mentioned in the vendor profile.
            // These presets are considered not installed.
            auto printer_model   = config.opt_string("printer_model");
            if (printer_model.empty()) {
                BOOST_LOG_TRIVIAL(error) << "Error in a Vendor Config Bundle \"" << path << "\": The printer preset \"" <<
                    preset_name << "\" defines no printer model, it will be ignored.";
                reason = std::string("can not find printer_model");
                return reason;
            }
            auto printer_variant = config.opt_string("printer_variant");
            if (printer_variant.empty()) {
                BOOST_LOG_TRIVIAL(error) << "Error in a Vendor Config Bundle \"" << path << "\": The printer preset \"" <<
                    preset_name << "\" defines no printer variant, it will be ignored.";
                reason = std::string("can not find printer_variant");
                return reason;
            }
            auto it_model = std::find_if(current_vendor_profile->models.cbegin(), current_vendor_profile->models.cend(),
                [&](const VendorProfile::PrinterModel &m) { return m.id == printer_model; }
            );
            if (it_model == current_vendor_profile->models.end()) {
                BOOST_LOG_TRIVIAL(error) << "Error in a Vendor Config Bundle \"" << path << "\": The printer preset \"" <<
                    preset_name << "\" defines invalid printer model \"" << printer_model << "\", it will be ignored.";
                reason = std::string("can not find printer model in vendor profile");
                return reason;
            }
            auto it_variant = it_model->variant(printer_variant);
            if (it_variant == nullptr) {
                BOOST_LOG_TRIVIAL(error) << "Error in a Vendor Config Bundle \"" << path << "\": The printer preset \"" <<
                    preset_name << "\" defines invalid printer variant \"" << printer_variant << "\", it will be ignored.";
                reason = std::string("can not find printer_variant in vendor profile");
                return reason;
            }
        }
        const Preset *preset_existing = presets_collection->find_preset(preset_name, false);
        if (preset_existing != nullptr) {
            BOOST_LOG_TRIVIAL(error) << "Error in a Vendor Config Bundle \"" << path << "\": The printer preset \"" <<
                preset_name << "\" has already been loaded from another Confing Bundle.";
            reason = std::string("duplicated defines");
            return reason;
        }
        auto file_path = (boost::filesystem::path(data_dir())  /PRESET_SYSTEM_DIR/ vendor_name / subfile_iter.second).make_preferred();
        // Load the preset into the list of presets, save it to disk.
        Preset &loaded = presets_collection->load_preset(file_path.string(), preset_name, std::move(config), false);
        if (flags.has(LoadConfigBundleAttribute::LoadSystem)) {
            loaded.is_system = true;
            loaded.vendor = current_vendor_profile;
            loaded.version = current_vendor_profile->config_version;
            loaded.setting_id = setting_id;
            loaded.filament_id = filament_id;
            if (presets_collection->type() == Preset::TYPE_FILAMENT) {
                if (filament_id.empty()) {
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": can not find filament_id for " << preset_name;
                    //throw ConfigurationError(format("can not find inherits %1% for %2%", inherits, preset_name));
                    reason = "Can not find filament_id for " + preset_name;
                    return reason;
                }
                else {
                    filament_id_maps.emplace(preset_name, filament_id);
                }
            }
        }
        // Derive the profile logical name aka alias from the preset name if the alias was not stated explicitely.
        if (alias_name.empty()) {
            size_t end_pos = preset_name.find_first_of("@");
            if (end_pos != std::string::npos) {
                alias_name = preset_name.substr(0, end_pos);
                if (renamed_from.empty())
                    // Add the preset name with the '@' character removed into the "renamed_from" list.
                    renamed_from.emplace_back(alias_name + preset_name.substr(end_pos + 1));
                boost::trim_right(alias_name);
            }
        }
        if (alias_name.empty())
            loaded.alias = preset_name;
        else
            loaded.alias = std::move(alias_name);
        loaded.renamed_from = std::move(renamed_from);
        if (! substitution_context.empty())
            substitutions.push_back({
                preset_name, presets_collection->type(), PresetConfigSubstitutions::Source::ConfigBundle,
                std::string(), std::move(substitution_context.substitutions) });
        config_maps.emplace(preset_name, loaded.config);
        ++count;
        //BBS: add config related logs
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", got preset %1%, from %2%")%loaded.name %subfile;
        return reason;
    };
    std::map<std::string, DynamicPrintConfig> configs;
    std::map<std::string, std::string> filament_id_maps;
    //3.1) paste the process
    presets = &this->prints;
    configs.clear();
    filament_id_maps.clear();
    for (auto& subfile : process_subfiles)
    {
        std::string reason = parse_subfile(substitution_context, substitutions, flags, subfile, configs, filament_id_maps, presets, presets_loaded);
        if (!reason.empty()) {
            //parse error
            std::string subfile_path = path + "/" + vendor_name + "/" + subfile.second;
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(", got error when parse process setting from %1%") % subfile_path;
            throw ConfigurationError((boost::format("Failed loading configuration file %1%\nSuggest cleaning the directory %2% firstly") % subfile_path %vendor_system_path).str());
        }
    }
    //3.2) paste the filaments
    presets = &this->filaments;
    configs.clear();
    filament_id_maps.clear();
    for (auto& subfile : filament_subfiles)
    {
        std::string reason = parse_subfile(substitution_context, substitutions, flags, subfile, configs, filament_id_maps, presets, presets_loaded);
        if (!reason.empty()) {
            //parse error
            std::string subfile_path = path + "/" + vendor_name + "/" + subfile.second;
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(", got error when parse filament setting from %1%") % subfile_path;
            throw ConfigurationError((boost::format("Failed loading configuration file %1%\nSuggest cleaning the directory %2% firstly") % subfile_path %vendor_system_path).str());
        }
    }
    //3.3) paste the printers
    presets = &this->printers;
    configs.clear();
    filament_id_maps.clear();
    for (auto& subfile : machine_subfiles)
    {
        std::string reason = parse_subfile(substitution_context, substitutions, flags, subfile, configs, filament_id_maps, presets, presets_loaded);
        if (!reason.empty()) {
            //parse error
            std::string subfile_path = path + "/" + vendor_name + "/" + subfile.second;
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(", got error when parse printer setting from %1%") % subfile_path;
            throw ConfigurationError((boost::format("Failed loading configuration file %1%\nSuggest cleaning the directory %2% firstly") % subfile_path %vendor_system_path).str());
        }
    }
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", finished, presets_loaded %1%")%presets_loaded;
    return std::make_pair(std::move(substitutions), presets_loaded);
}
References Slic3r::Preset::alias, Slic3r::ConfigBase::apply(), BBL_JSON_KEY_BED_MODEL, BBL_JSON_KEY_BED_TEXTURE, BBL_JSON_KEY_DEFAULT_MATERIALS, BBL_JSON_KEY_DESCRIPTION, BBL_JSON_KEY_FAMILY, BBL_JSON_KEY_FILAMENT_ID, BBL_JSON_KEY_FILAMENT_LIST, BBL_JSON_KEY_HOTEND_MODEL, BBL_JSON_KEY_INHERITS, BBL_JSON_KEY_INSTANTIATION, BBL_JSON_KEY_MACHINE_LIST, BBL_JSON_KEY_MACHINE_MODEL_LIST, BBL_JSON_KEY_MODEL_ID, BBL_JSON_KEY_NAME, BBL_JSON_KEY_NOZZLE_DIAMETER, BBL_JSON_KEY_PRINTER_TECH, BBL_JSON_KEY_PROCESS_LIST, BBL_JSON_KEY_SETTING_ID, BBL_JSON_KEY_SUB_PATH, BBL_JSON_KEY_URL, BBL_JSON_KEY_VERSION, Slic3r::VendorProfile::PrinterModel::bed_model, Slic3r::VendorProfile::PrinterModel::bed_texture, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), Slic3r::Preset::config, Slic3r::VendorProfile::config_update_url, Slic3r::VendorProfile::config_version, Slic3r::PresetConfigSubstitutions::ConfigBundle, count, Slic3r::data_dir(), Slic3r::VendorProfile::PrinterModel::default_materials, Slic3r::ConfigSubstitutionContext::empty(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, Slic3r::VendorProfile::PrinterModel::family, Slic3r::Preset::filament_id, filaments, Slic3r::ConfigOptionResolver::has(), Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::VendorProfile::PrinterModel::hotend_model, Slic3r::VendorProfile::id, Slic3r::VendorProfile::PrinterModel::id, Slic3r::Preset::is_system, nlohmann::detail::iter_impl< BasicJsonType >::key(), Slic3r::ConfigBase::load_from_json(), LoadSystem, LoadVendorOnly, Slic3r::VendorProfile::PrinterModel::model_id, Slic3r::VendorProfile::models, Slic3r::VendorProfile::name, Slic3r::VendorProfile::PrinterModel::name, Slic3r::Preset::name, Slic3r::Preset::normalize(), Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), Slic3r::Semver::parse(), PRESET_SYSTEM_DIR, Slic3r::printer_model(), printers, prints, Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::Preset::remove_invalid_keys(), Slic3r::Preset::renamed_from, reset(), ResetUserProfile, SaveImported, Slic3r::Preset::setting_id, Slic3r::sort_remove_duplicates(), Slic3r::ConfigSubstitutionContext::substitutions, Slic3r::VendorProfile::PrinterModel::technology, Slic3r::Semver::to_string(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, Slic3r::unescape_strings_cstyle(), nlohmann::detail::iter_impl< BasicJsonType >::value(), Slic3r::VendorProfile::PrinterModel::variant(), Slic3r::VendorProfile::PrinterModel::variants, Slic3r::Preset::vendor, vendors, Slic3r::Preset::version, Slic3r::ConfigOptionVectorBase::vserialize(), and nlohmann::detail::exception::what().
Referenced by load_system_presets_from_json(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
materials() [1/2]
PresetCollection & Slic3r::PresetBundle::materials (PrinterTechnology pt) inline
{ return pt == ptFFF ? this->filaments : this->sla_materials; }
References filaments, Slic3r::ptFFF, and sla_materials.
materials() [2/2]
const PresetCollection & Slic3r::PresetBundle::materials (PrinterTechnology pt) const inline
{ return pt == ptFFF ? this->filaments : this->sla_materials; }
References filaments, Slic3r::ptFFF, and sla_materials.
merge_presets()
std::vector< std::string > Slic3r::PresetBundle::merge_presets (PresetBundle && other) private
{
    this->vendors.insert(other.vendors.begin(), other.vendors.end());
    std::vector<std::string> duplicate_prints        = this->prints       .merge_presets(std::move(other.prints),        this->vendors);
    std::vector<std::string> duplicate_sla_prints    = this->sla_prints   .merge_presets(std::move(other.sla_prints),    this->vendors);
    std::vector<std::string> duplicate_filaments     = this->filaments    .merge_presets(std::move(other.filaments),     this->vendors);
    std::vector<std::string> duplicate_sla_materials = this->sla_materials.merge_presets(std::move(other.sla_materials), this->vendors);
    std::vector<std::string> duplicate_printers      = this->printers     .merge_presets(std::move(other.printers),      this->vendors);
  append(this->obsolete_presets.prints,        std::move(other.obsolete_presets.prints));
  append(this->obsolete_presets.sla_prints,    std::move(other.obsolete_presets.sla_prints));
  append(this->obsolete_presets.filaments,     std::move(other.obsolete_presets.filaments));
    append(this->obsolete_presets.sla_materials, std::move(other.obsolete_presets.sla_materials));
  append(this->obsolete_presets.printers,      std::move(other.obsolete_presets.printers));
  append(duplicate_prints, std::move(duplicate_sla_prints));
  append(duplicate_prints, std::move(duplicate_filaments));
    append(duplicate_prints, std::move(duplicate_sla_materials));
    append(duplicate_prints, std::move(duplicate_printers));
    return duplicate_prints;
}
References Slic3r::append(), filaments, Slic3r::PresetBundle::ObsoletePresets::filaments, Slic3r::PresetCollection::merge_presets(), obsolete_presets, printers, Slic3r::PresetBundle::ObsoletePresets::printers, prints, Slic3r::PresetBundle::ObsoletePresets::prints, sla_materials, Slic3r::PresetBundle::ObsoletePresets::sla_materials, sla_prints, Slic3r::PresetBundle::ObsoletePresets::sla_prints, and vendors.
Referenced by load_system_presets_from_json().
operator=()
PresetBundle & Slic3r::PresetBundle::operator= (const PresetBundle & rhs)
{
    prints              = rhs.prints;
    sla_prints          = rhs.sla_prints;
    filaments           = rhs.filaments;
    sla_materials       = rhs.sla_materials;
    printers            = rhs.printers;
    physical_printers   = rhs.physical_printers;
    filament_presets    = rhs.filament_presets;
    project_config      = rhs.project_config;
    vendors             = rhs.vendors;
    obsolete_presets    = rhs.obsolete_presets;
    // Adjust Preset::vendor pointers to point to the copied vendors map.
    prints       .update_vendor_ptrs_after_copy(this->vendors);
    sla_prints   .update_vendor_ptrs_after_copy(this->vendors);
    filaments    .update_vendor_ptrs_after_copy(this->vendors);
    sla_materials.update_vendor_ptrs_after_copy(this->vendors);
    printers     .update_vendor_ptrs_after_copy(this->vendors);
    return *this;
}
References filament_presets, filaments, obsolete_presets, physical_printers, printers, prints, project_config, sla_materials, sla_prints, Slic3r::PresetCollection::update_vendor_ptrs_after_copy(), and vendors.
remove_user_presets_directory()
void Slic3r::PresetBundle::remove_user_presets_directory (const std::string preset_folder)
{
    const std::string dir_user_presets = data_dir() + "/" + PRESET_USER_DIR + "/" + preset_folder;
    if (preset_folder.empty()) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": preset_folder is empty, no need to remove directory : %1%") % dir_user_presets;
        return;
    }
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, delete directory : %1%") % dir_user_presets;
    fs::path folder(dir_user_presets);
    if (fs::exists(folder)) {
        fs::remove_all(folder);
    }
}
References Slic3r::data_dir(), and PRESET_USER_DIR.
remove_users_preset()
void Slic3r::PresetBundle::remove_users_preset (AppConfig & config, std::map< std::string, std::map< std::string, std::string > > * my_presets = nullptr)
{
    auto check_removed = [my_presets, this](Preset &preset) -> bool {
        if (my_presets == nullptr) return true;
        if (my_presets->find(preset.name) != my_presets->end()) return false;
        if (!preset.sync_info.empty()) return false; // syncing, not remove
        if (preset.setting_id.empty()) return false; // no id, not remove
        // Saved preset is removed by another session
        if (preset.is_dirty) {
            preset.setting_id.clear();
            return false;
        }
        preset.remove_files();
        return true;
    };
    std::string preset_folder_user_id = config.get("preset_folder");
    std::string printer_selected_preset_name = printers.get_selected_preset().name;
    bool need_reset_printer_preset = false;
    for (auto it = printers.begin(); it != printers.end();) {
        if (it->is_user() && it->user_id.compare(preset_folder_user_id) == 0 && check_removed(*it)) {
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":printers erase %1%, type %2% user_id %3%") % it->name % Preset::get_type_string(it->type) % it->user_id;
            if (it->name == printer_selected_preset_name)
                need_reset_printer_preset = true;
            it = printers.erase(it);
        }
        else {
            it++;
        }
    }
    if (need_reset_printer_preset) {
        std::string default_printer_model = BBL_DEFAULT_PRINTER_MODEL;
        std::string default_printer_name;
        for (auto it = printers.begin(); it != printers.end(); it++) {
            if (it->config.has("printer_model")) {
                if (it->config.opt_string("printer_model") == default_printer_model) {
                    default_printer_name = it->name;
                    break;
                }
            }
        }
        printers.select_preset_by_name(default_printer_name, true);
    } else {
        printers.select_preset_by_name(printer_selected_preset_name, false);
    }
    std::string selected_print_name = prints.get_selected_preset().name;
    bool need_reset_print_preset = false;
    // remove preset if user_id is not current user
    for (auto it = prints.begin(); it != prints.end();) {
        if (it->is_user() && !it->user_id.empty() && it->user_id.compare(preset_folder_user_id) == 0 && check_removed(*it)) {
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":prints erase %1%, type %2% user_id %3%")%it->name %Preset::get_type_string(it->type) %it->user_id;
            if (it->name == selected_print_name)
                need_reset_print_preset = true;
            it = prints.erase(it);
        }
        else {
            it++;
        }
    }
    if (need_reset_print_preset && printers.get_selected_preset().config.has("default_print_profile")) {
        std::string default_print_profile_name = printers.get_selected_preset().config.opt_string("default_print_profile");
        prints.select_preset_by_name(default_print_profile_name, true);
    } else {
        prints.select_preset_by_name(selected_print_name, false);
    }
    std::string selected_filament_name = filaments.get_selected_preset().name;
    bool need_reset_filament_preset = false;
    for (auto it = filaments.begin(); it != filaments.end();) {
        if (it->is_user() && !it->user_id.empty() && it->user_id.compare(preset_folder_user_id) == 0 && check_removed(*it)) {
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":filaments erase %1%, type %2% user_id %3%")%it->name %Preset::get_type_string(it->type) %it->user_id;
            if (it->name == selected_filament_name)
                need_reset_filament_preset = true;
            it = filaments.erase(it);
        }
        else {
            it++;
        }
    }
    if (need_reset_filament_preset && printers.get_selected_preset().config.has("default_filament_profile")) {
        const std::vector<std::string>& prefered_filament_profiles = printers.get_selected_preset().config.option<ConfigOptionStrings>("default_filament_profile")->values;
        if (prefered_filament_profiles.size() > 0)
            filaments.select_preset_by_name(prefered_filament_profiles[0], true);
    } else {
        filaments.select_preset_by_name(selected_filament_name, false);
    }
    update_compatible(PresetSelectCompatibleType::Always);
    /* set selected preset */
    for (size_t i = 0; i < filament_presets.size(); ++i)
    {
        auto preset = this->filaments.find_preset(filament_presets[i]);
        if (preset == nullptr)
            filament_presets[i] = filaments.get_selected_preset_name();
    }
}
References Slic3r::Always, BBL_DEFAULT_PRINTER_MODEL, Slic3r::PresetCollection::begin(), Slic3r::Preset::config, Slic3r::PresetCollection::end(), Slic3r::PresetCollection::erase(), filament_presets, filaments, Slic3r::PresetCollection::find_preset(), Slic3r::AppConfig::get(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::Preset::get_type_string(), Slic3r::ConfigOptionResolver::has(), Slic3r::Preset::name, Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), printers, prints, Slic3r::PresetCollection::select_preset_by_name(), and update_compatible().
Referenced by load_user_presets(), and Slic3r::GUI::GUI_App::remove_user_presets().
reset()
void Slic3r::PresetBundle::reset (bool delete_files)
{
    // Clear the existing presets, delete their respective files.
    this->vendors.clear();
    this->prints       .reset(delete_files);
    this->sla_prints   .reset(delete_files);
    this->filaments    .reset(delete_files);
    this->sla_materials.reset(delete_files);
    this->printers     .reset(delete_files);
    // BBS: filament_presets is load from project config, not handled here
    //this->filament_presets.clear();
    if (this->filament_presets.empty())
        this->filament_presets.emplace_back(this->filaments.get_selected_preset_name());
    this->obsolete_presets.prints.clear();
    this->obsolete_presets.sla_prints.clear();
    this->obsolete_presets.filaments.clear();
    this->obsolete_presets.sla_materials.clear();
    this->obsolete_presets.printers.clear();
}
References filament_presets, filaments, Slic3r::PresetBundle::ObsoletePresets::filaments, Slic3r::PresetCollection::get_selected_preset_name(), obsolete_presets, printers, Slic3r::PresetBundle::ObsoletePresets::printers, prints, Slic3r::PresetBundle::ObsoletePresets::prints, Slic3r::PresetCollection::reset(), sla_materials, Slic3r::PresetBundle::ObsoletePresets::sla_materials, sla_prints, Slic3r::PresetBundle::ObsoletePresets::sla_prints, and vendors.
Referenced by load_system_presets_from_json(), and load_vendor_configs_from_json().
reset_project_embedded_presets()
void Slic3r::PresetBundle::reset_project_embedded_presets ()
{
    std::string prefer_printer;
    Preset& current_printer = this->printers.get_selected_preset();
    ConfigOption* inherits = current_printer.config.option("inherits");
    if (inherits) {
        prefer_printer = dynamic_cast<ConfigOptionString *>(inherits)->value;
    }
    //first printer, then filament, then print
    bool printer_reselect = this->printers.reset_project_embedded_presets();
    bool filament_reselect = this->filaments.reset_project_embedded_presets();
    bool print_reselect = this->prints.reset_project_embedded_presets();
    if (printer_reselect) {
        if (!prefer_printer.empty())
           this->printers.select_preset_by_name(prefer_printer, true);
        else
           this->printers.select_preset(this->printers.first_visible_idx());
        //this->update_multi_material_filament_presets();
        this->update_compatible(PresetSelectCompatibleType::Never);
    }
    else if (filament_reselect || print_reselect) {
        //Preset& current_printer = this->printers.get_selected_preset();
        /*if (filament_reselect) {
            const std::vector<std::string> &prefered_filament_profiles = current_printer.config.option<ConfigOptionStrings>("default_filament_profile")->values;
            const std::string prefered_filament_profile = prefered_filament_profiles.empty() ? std::string() : prefered_filament_profiles.front();
            if (!prefered_filament_profile.empty())
               this->filaments.select_preset_by_name(prefered_filament_profile, true);
            else
               this->filaments.select_preset(this->filaments.first_visible_idx());
        }
        if (print_reselect) {
        }*/
        this->update_compatible(PresetSelectCompatibleType::Never);
    }
    //this->update_multi_material_filament_presets();
    //update filament_presets
    for (size_t i = 0; i < filament_presets.size(); ++ i)
    {
        Preset* selected_filament = this->filaments.find_preset(filament_presets[i], false);
        if (!selected_filament) {
            //it should be the project embedded presets
            Preset& current_printer = this->printers.get_selected_preset();
            const std::vector<std::string> &prefered_filament_profiles = current_printer.config.option<ConfigOptionStrings>("default_filament_profile")->values;
            const std::string prefered_filament_profile = prefered_filament_profiles.empty() ? std::string() : prefered_filament_profiles.front();
            if (!prefered_filament_profile.empty())
                filament_presets[i] = prefered_filament_profile;
            else
            filament_presets[i] = this->filaments.first_visible().name;
        }
    }
}
References Slic3r::Preset::config, Slic3r::ConfigOptionVector< T >::empty(), filament_presets, filaments, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::first_visible_idx(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::name, Slic3r::Never, Slic3r::ConfigBase::option(), printers, prints, Slic3r::PresetCollection::reset_project_embedded_presets(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::select_preset_by_name(), and update_compatible().
save_changes_for_preset()
void Slic3r::PresetBundle::save_changes_for_preset (const std::string & new_name, Preset::Type type, const std::vector< std::string > & unselected_options, bool save_to_project = false)
{
    PresetCollection& presets = type == Preset::TYPE_PRINT          ? prints :
                                type == Preset::TYPE_SLA_PRINT      ? sla_prints :
                                type == Preset::TYPE_FILAMENT       ? filaments :
                                type == Preset::TYPE_SLA_MATERIAL   ? sla_materials : printers;
    // if we want to save just some from selected options
    if (!unselected_options.empty()) {
        // revert unselected options to the old values
        presets.get_edited_preset().config.apply_only(presets.get_selected_preset().config, unselected_options);
    }
    // Save the preset into Slic3r::data_dir / presets / section_name / preset_name.ini
    //BBS: add project embedded preset logic
    //presets.save_current_preset(new_name);
    presets.save_current_preset(new_name, false, save_to_project);
    // Mark the print & filament enabled if they are compatible with the currently selected preset.
    // If saving the preset changes compatibility with other presets, keep the now incompatible dependent presets selected, however with a "red flag" icon showing that they are no more compatible.
    update_compatible(PresetSelectCompatibleType::Never);
    if (type == Preset::TYPE_FILAMENT) {
        // synchronize the first filament presets.
        set_filament_preset(0, filaments.get_selected_preset_name());
    }
}
References Slic3r::ConfigBase::apply_only(), Slic3r::Preset::config, filaments, Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::Never, printers, prints, Slic3r::PresetCollection::save_current_preset(), set_filament_preset(), sla_materials, sla_prints, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::Preset::TYPE_SLA_PRINT, and update_compatible().
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::GUI_App::check_and_save_current_preset_changes(), and Slic3r::GUI::Tab::may_discard_current_dirty_preset().
save_user_presets()
void Slic3r::PresetBundle::save_user_presets (AppConfig & config, std::vector< std::string > & need_to_delete_list)
{
    std::string user_sub_folder = DEFAULT_USER_FOLDER_NAME;
    if (!config.get("preset_folder").empty())
        user_sub_folder = config.get("preset_folder");
    //BBS: change directory by design
    const std::string dir_user_presets = data_dir() + "/" + PRESET_USER_DIR + "/"+ user_sub_folder;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, save to %1%")%dir_user_presets;
    fs::path user_folder(data_dir() + "/" + PRESET_USER_DIR);
    if (!fs::exists(user_folder))
        fs::create_directory(user_folder);
    fs::path folder(dir_user_presets);
    if (!fs::exists(folder))
        fs::create_directory(folder);
    this->prints.save_user_presets(dir_user_presets, PRESET_PRINT_NAME, need_to_delete_list);
    this->filaments.save_user_presets(dir_user_presets, PRESET_FILAMENT_NAME, need_to_delete_list);
    this->printers.save_user_presets(dir_user_presets, PRESET_PRINTER_NAME, need_to_delete_list);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" finished");
}
References Slic3r::data_dir(), DEFAULT_USER_FOLDER_NAME, filaments, Slic3r::AppConfig::get(), PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, PRESET_USER_DIR, printers, prints, and Slic3r::PresetCollection::save_user_presets().
Referenced by Slic3r::GUI::GUI_App::reload_settings().
set_calibrate_printer()
void Slic3r::PresetBundle::set_calibrate_printer (std::string name)
{
    if (name.empty()) {
        calibrate_filaments.clear();
        return;
    }
    if (!name.empty())
        calibrate_printer = printers.find_preset(name);
    const Preset &                printer_preset = calibrate_printer ? *calibrate_printer : printers.get_edited_preset();
    const PresetWithVendorProfile active_printer = printers.get_preset_with_vendor_profile(printer_preset);
    DynamicPrintConfig            config;
    config.set_key_value("printer_preset", new ConfigOptionString(active_printer.preset.name));
    const ConfigOption *opt = active_printer.preset.config.option("nozzle_diameter");
    if (opt) config.set_key_value("num_extruders", new ConfigOptionInt((int) static_cast<const ConfigOptionFloats *>(opt)->values.size()));
    calibrate_filaments.clear();
    for (size_t i = filaments.num_default_presets(); i < filaments.size(); ++i) {
        const Preset &                preset                          = filaments.m_presets[i];
        const PresetWithVendorProfile this_preset_with_vendor_profile = filaments.get_preset_with_vendor_profile(preset);
        bool                          is_compatible                   = is_compatible_with_printer(this_preset_with_vendor_profile, active_printer, &config);
        if (is_compatible) calibrate_filaments.insert(&preset);
    }
}
References calibrate_filaments, calibrate_printer, Slic3r::Preset::config, filaments, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_preset_with_vendor_profile(), Slic3r::is_compatible_with_printer(), Slic3r::PresetCollection::m_presets, Slic3r::Preset::name, Slic3r::PresetCollection::num_default_presets(), Slic3r::ConfigBase::option(), Slic3r::PresetWithVendorProfile::preset, printers, Slic3r::DynamicConfig::set_key_value(), Slic3r::PresetCollection::size(), and Slic3r::ConfigOptionVector< T >::size().
Referenced by load_presets(), load_user_presets(), and load_user_presets().
set_default_suppressed()
void Slic3r::PresetBundle::set_default_suppressed (bool default_suppressed)
{
    prints.set_default_suppressed(default_suppressed);
    filaments.set_default_suppressed(default_suppressed);
    sla_prints.set_default_suppressed(default_suppressed);
    sla_materials.set_default_suppressed(default_suppressed);
    printers.set_default_suppressed(default_suppressed);
}
References filaments, printers, prints, Slic3r::PresetCollection::set_default_suppressed(), sla_materials, and sla_prints.
set_filament_preset()
void Slic3r::PresetBundle::set_filament_preset (size_t idx, const std::string & name)
{
    if (idx >= filament_presets.size()) {
        BOOST_LOG_TRIVIAL(warning) << boost::format("Warning: set_filament_preset out of range %1% - %2%") % idx % filament_presets.size();
        return;
    }
    filament_presets[idx] = Preset::remove_suffix_modified(name);
}
References filament_presets, and Slic3r::Preset::remove_suffix_modified().
Referenced by save_changes_for_preset(), and Slic3r::GUI::Sidebar::update_presets().
set_num_filaments()
void Slic3r::PresetBundle::set_num_filaments (unsigned int n, std::string new_col = "")
{
    int old_filament_count = this->filament_presets.size();
    if (n > old_filament_count && old_filament_count != 0)
        filament_presets.resize(n, filament_presets.front());
    else {
        filament_presets.resize(n);
    }
    ConfigOptionStrings* filament_color = project_config.option<ConfigOptionStrings>("filament_colour");
    filament_color->resize(n);
    //BBS set new filament color to new_color
    if (old_filament_count < n) {
        if (!new_color.empty()) {
            for (int i = old_filament_count; i < n; i++) {
                filament_color->values[i] = new_color;
            }
        }
    }
    update_multi_material_filament_presets();
}
References filament_presets, n, Slic3r::ConfigBase::option(), project_config, Slic3r::ConfigOptionVector< T >::resize(), update_multi_material_filament_presets(), and Slic3r::ConfigOptionVector< T >::values.
setup_directories()
void Slic3r::PresetBundle::setup_directories ()
{
    boost::filesystem::path data_dir = boost::filesystem::path(Slic3r::data_dir());
    //BBS: change directoties by design
    std::initializer_list<boost::filesystem::path> paths = {
        data_dir,
        data_dir / "ota",
    data_dir / PRESET_SYSTEM_DIR,
        data_dir / PRESET_USER_DIR,
        // Store the print/filament/printer presets at the same location as the upstream Slic3r.
        //data_dir / PRESET_SYSTEM_DIR / PRESET_PRINT_NAME,
        //data_dir / PRESET_SYSTEM_DIR / PRESET_FILAMENT_NAME,
        //data_dir / PRESET_SYSTEM_DIR / PRESET_PRINTER_NAME
    };
    for (const boost::filesystem::path &path : paths) {
    boost::filesystem::path subdir = path;
        subdir.make_preferred();
        if (! boost::filesystem::is_directory(subdir) &&
            ! boost::filesystem::create_directory(subdir)) {
            if (boost::filesystem::is_directory(subdir)) {
                BOOST_LOG_TRIVIAL(warning) << boost::format("creating directory %1% failed, maybe created by other instance, go on!")%subdir.string();
            }
            else
                throw Slic3r::RuntimeError(std::string("Unable to create directory ") + subdir.string());
        }
    }
}
References Slic3r::data_dir(), PRESET_SYSTEM_DIR, and PRESET_USER_DIR.
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
sync_ams_list()
unsigned int Slic3r::PresetBundle::sync_ams_list (unsigned int & unknowns)
{
    std::vector<std::string> filament_presets;
    std::vector<std::string> filament_colors;
    for (auto &ams : filament_ams_list) {
        auto filament_id = ams.opt_string("filament_id", 0u);
        auto filament_color = ams.opt_string("filament_colour", 0u);
        auto filament_changed = !ams.has("filament_changed") || ams.opt_bool("filament_changed");
        if (filament_id.empty()) continue;
        if (!filament_changed && this->filament_presets.size() > filament_presets.size()) {
            filament_presets.push_back(this->filament_presets[filament_presets.size()]);
            filament_colors.push_back(filament_color);
            continue;
        }
        auto iter = std::find_if(filaments.begin(), filaments.end(), [&filament_id](auto &f) { return f.is_compatible && f.is_system && f.filament_id == filament_id; });
        if (iter == filaments.end()) {
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": filament_id %1% not found or system or compatible") % filament_id;
            auto filament_type = "Generic " + ams.opt_string("filament_type", 0u);
            iter = std::find_if(filaments.begin(), filaments.end(), [&filament_type](auto &f) { return f.is_compatible && f.is_system
                        && boost::algorithm::starts_with(f.name, filament_type);
                });
            if (iter == filaments.end())
                iter = std::find_if(filaments.begin(), filaments.end(), [&filament_type](auto &f) { return f.is_compatible && f.is_system; });
            if (iter == filaments.end())
                continue;
            ++unknowns;
            filament_id = iter->filament_id;
        }
        filament_presets.push_back(iter->name);
        filament_colors.push_back(filament_color);
    }
    if (filament_presets.empty())
        return 0;
    this->filament_presets = filament_presets;
    ConfigOptionStrings *filament_color = project_config.option<ConfigOptionStrings>("filament_colour");
    filament_color->resize(filament_presets.size());
    filament_color->values = filament_colors;
    update_multi_material_filament_presets();
    return filament_presets.size();
}
References Slic3r::PresetCollection::begin(), Slic3r::PresetCollection::end(), Slic3r::f(), filament_ams_list, filament_presets, filaments, Slic3r::ConfigBase::option(), project_config, Slic3r::ConfigOptionVector< T >::resize(), update_multi_material_filament_presets(), and Slic3r::ConfigOptionVector< T >::values.
update_compatible() [1/2]
void Slic3r::PresetBundle::update_compatible (PresetSelectCompatibleType select_other_if_incompatible) inline
{ this->update_compatible(select_other_if_incompatible, select_other_if_incompatible); }
References update_compatible().
Referenced by update_compatible().
update_compatible() [2/2]
void Slic3r::PresetBundle::update_compatible (PresetSelectCompatibleType select_other_print_if_incompatible, PresetSelectCompatibleType select_other_filament_if_incompatible)
{
    const Preset          &printer_preset             = this->printers.get_edited_preset();
  const PresetWithVendorProfile    printer_preset_with_vendor_profile = this->printers.get_preset_with_vendor_profile(printer_preset);
    class PreferedProfileMatch
    {
    public:
        PreferedProfileMatch(const std::string &prefered_alias, const std::string &prefered_name) :
            m_prefered_alias(prefered_alias), m_prefered_name(prefered_name) {}
        int operator()(const Preset &preset) const
        {
            return
                preset.is_default || preset.is_external ?
                    // Don't match any properties of the "-- default --" profile or the external profiles when switching printer profile.
                    0 :
                    ! m_prefered_alias.empty() && m_prefered_alias == preset.alias ?
                        // Matching an alias, always take this preset with priority.
                        std::numeric_limits<int>::max() :
                        // Otherwise take the prefered profile, or the first compatible.
                        preset.name == m_prefered_name;
        }
    private:
        const std::string  m_prefered_alias;
        const std::string &m_prefered_name;
    };
    // Matching by the layer height in addition.
    class PreferedPrintProfileMatch : public PreferedProfileMatch
    {
    public:
        PreferedPrintProfileMatch(const Preset *preset, const std::string &prefered_name) :
            PreferedProfileMatch(preset ? preset->alias : std::string(), prefered_name), m_prefered_layer_height(preset ? preset->config.opt_float("layer_height") : 0) {}
        int operator()(const Preset &preset) const
        {
            // Don't match any properties of the "-- default --" profile or the external profiles when switching printer profile.
            if (preset.is_default || preset.is_external)
                return 0;
            int match_quality = PreferedProfileMatch::operator()(preset);
            if (match_quality < std::numeric_limits<int>::max()) {
                match_quality += 1;
                if (m_prefered_layer_height > 0. && std::abs(preset.config.opt_float("layer_height") - m_prefered_layer_height) < 0.0005)
                    match_quality *= 10;
            }
            return match_quality;
        }
    private:
        const double m_prefered_layer_height;
    };
    // Matching by the layer height in addition.
    class PreferedFilamentProfileMatch : public PreferedProfileMatch
    {
    public:
        PreferedFilamentProfileMatch(const Preset *preset, const std::string &prefered_name) :
            PreferedProfileMatch(preset ? preset->alias : std::string(), prefered_name),
            m_prefered_filament_type(preset ? preset->config.opt_string("filament_type", 0) : std::string()) {}
        int operator()(const Preset &preset) const
        {
            // Don't match any properties of the "-- default --" profile or the external profiles when switching printer profile.
            if (preset.is_default || preset.is_external)
                return 0;
            int match_quality = PreferedProfileMatch::operator()(preset);
            if (match_quality < std::numeric_limits<int>::max()) {
                match_quality += 1;
                if (! m_prefered_filament_type.empty() && m_prefered_filament_type == preset.config.opt_string("filament_type", 0))
                    match_quality *= 10;
            }
            return match_quality;
        }
    private:
        const std::string m_prefered_filament_type;
    };
    // Matching by the layer height in addition.
    class PreferedFilamentsProfileMatch
    {
    public:
        PreferedFilamentsProfileMatch(const Preset *preset, const std::vector<std::string> &prefered_names) :
            m_prefered_alias(preset ? preset->alias : std::string()),
            m_prefered_filament_type(preset ? preset->config.opt_string("filament_type", 0) : std::string("PLA")), // BBS: default choose PLA
            m_prefered_names(prefered_names)
            {}
        int operator()(const Preset &preset) const
        {
            // Don't match any properties of the "-- default --" profile or the external profiles when switching printer profile.
            if (preset.is_default || preset.is_external)
                return 0;
            if (! m_prefered_alias.empty() && m_prefered_alias == preset.alias)
                // Matching an alias, always take this preset with priority.
                return std::numeric_limits<int>::max();
            int match_quality = (std::find(m_prefered_names.begin(), m_prefered_names.end(), preset.name) != m_prefered_names.end()) + 1;
            if (! m_prefered_filament_type.empty() && m_prefered_filament_type == preset.config.opt_string("filament_type", 0))
                match_quality *= 10;
            return match_quality;
        }
    private:
        const std::string               m_prefered_alias;
        const std::string               m_prefered_filament_type;
        const std::vector<std::string> &m_prefered_names;
    };
    BOOST_LOG_TRIVIAL(info) << boost::format("update_compatibility for all presets enter");
  switch (printer_preset.printer_technology()) {
    case ptFFF:
    {
    assert(printer_preset.config.has("default_print_profile"));
    assert(printer_preset.config.has("default_filament_profile"));
        const std::vector<std::string> &prefered_filament_profiles = printer_preset.config.option<ConfigOptionStrings>("default_filament_profile")->values;
        this->prints.update_compatible(printer_preset_with_vendor_profile, nullptr, select_other_print_if_incompatible,
            PreferedPrintProfileMatch(this->prints.get_selected_idx() == size_t(-1) ? nullptr : &this->prints.get_edited_preset(), printer_preset.config.opt_string("default_print_profile")));
        const PresetWithVendorProfile   print_preset_with_vendor_profile = this->prints.get_edited_preset_with_vendor_profile();
        // Remember whether the filament profiles were compatible before updating the filament compatibility.
        std::vector<char>         filament_preset_was_compatible(this->filament_presets.size(), false);
        for (size_t idx = 0; idx < this->filament_presets.size(); ++ idx) {
            Preset *preset = this->filaments.find_preset(this->filament_presets[idx], false);
            filament_preset_was_compatible[idx] = preset != nullptr && preset->is_compatible;
        }
        // First select a first compatible profile for the preset editor.
        this->filaments.update_compatible(printer_preset_with_vendor_profile, &print_preset_with_vendor_profile, select_other_filament_if_incompatible,
            PreferedFilamentsProfileMatch(this->filaments.get_selected_idx() == size_t(-1) ? nullptr : &this->filaments.get_edited_preset(), prefered_filament_profiles));
        if (select_other_filament_if_incompatible != PresetSelectCompatibleType::Never) {
            // Verify validity of the current filament presets.
            const std::string prefered_filament_profile = prefered_filament_profiles.empty() ? std::string() : prefered_filament_profiles.front();
            if (this->filament_presets.size() == 1) {
                // The compatible profile should have been already selected for the preset editor. Just use it.
              if (select_other_filament_if_incompatible == PresetSelectCompatibleType::Always || filament_preset_was_compatible.front())
                  this->filament_presets.front() = this->filaments.get_edited_preset().name;
            } else {
                for (size_t idx = 0; idx < this->filament_presets.size(); ++ idx) {
                    std::string &filament_name = this->filament_presets[idx];
                    Preset      *preset = this->filaments.find_preset(filament_name, false);
                    if (preset == nullptr || (! preset->is_compatible && (select_other_filament_if_incompatible == PresetSelectCompatibleType::Always || filament_preset_was_compatible[idx])))
                        // Pick a compatible profile. If there are prefered_filament_profiles, use them.
                        filament_name = this->filaments.first_compatible(
                            PreferedFilamentProfileMatch(preset,
                                (idx < prefered_filament_profiles.size()) ? prefered_filament_profiles[idx] : prefered_filament_profile)).name;
                }
            }
        }
    break;
    }
    case ptSLA:
    {
    assert(printer_preset.config.has("default_sla_print_profile"));
    assert(printer_preset.config.has("default_sla_material_profile"));
    this->sla_prints.update_compatible(printer_preset_with_vendor_profile, nullptr, select_other_print_if_incompatible,
            PreferedPrintProfileMatch(this->sla_prints.get_selected_idx() == size_t(-1) ? nullptr : &this->sla_prints.get_edited_preset(), printer_preset.config.opt_string("default_sla_print_profile")));
        const PresetWithVendorProfile sla_print_preset_with_vendor_profile = this->sla_prints.get_edited_preset_with_vendor_profile();
    this->sla_materials.update_compatible(printer_preset_with_vendor_profile, &sla_print_preset_with_vendor_profile, select_other_filament_if_incompatible,
            PreferedProfileMatch(this->sla_materials.get_selected_idx() == size_t(-1) ? std::string() : this->sla_materials.get_edited_preset().alias, printer_preset.config.opt_string("default_sla_material_profile")));
    break;
  }
    default: break;
    }
    BOOST_LOG_TRIVIAL(info) << boost::format("update_compatibility for all presets exit");
}
References Slic3r::Preset::alias, Slic3r::Always, Slic3r::Preset::config, filament_presets, filaments, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::first_compatible(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_edited_preset_with_vendor_profile(), Slic3r::PresetCollection::get_preset_with_vendor_profile(), Slic3r::PresetCollection::get_selected_idx(), Slic3r::ConfigOptionResolver::has(), Slic3r::Preset::is_compatible, Slic3r::Preset::is_default, Slic3r::Preset::is_external, Slic3r::Preset::name, Slic3r::Never, Slic3r::DynamicConfig::opt_float(), Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), Slic3r::Preset::printer_technology(), printers, prints, Slic3r::ptFFF, Slic3r::ptSLA, sla_materials, sla_prints, and Slic3r::PresetCollection::update_compatible().
Referenced by load_config_file_config(), load_presets(), load_selections(), load_user_presets(), load_user_presets(), remove_users_preset(), reset_project_embedded_presets(), save_changes_for_preset(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::DiffPresetDialog::update_compatibility(), and update_selections().
update_multi_material_filament_presets()
void Slic3r::PresetBundle::update_multi_material_filament_presets ()
{
    if (printers.get_edited_preset().printer_technology() != ptFFF)
        return;
    // BBS
#if 0
    // Verify and select the filament presets.
    auto   *nozzle_diameter = static_cast<const ConfigOptionFloats*>(printers.get_edited_preset().config.option("nozzle_diameter"));
    size_t  num_extruders   = nozzle_diameter->values.size();
    // Verify validity of the current filament presets.
    for (size_t i = 0; i < std::min(this->filament_presets.size(), num_extruders); ++ i)
        this->filament_presets[i] = this->filaments.find_preset(this->filament_presets[i], true)->name;
    // Append the rest of filament presets.
    this->filament_presets.resize(num_extruders, this->filament_presets.empty() ? this->filaments.first_visible().name : this->filament_presets.back());
#else
    size_t num_filaments = this->filament_presets.size();
#endif
    // Now verify if flush_volumes_matrix has proper size (it is used to deduce number of extruders in wipe tower generator):
    std::vector<double> old_matrix = this->project_config.option<ConfigOptionFloats>("flush_volumes_matrix")->values;
    size_t old_number_of_filaments = size_t(sqrt(old_matrix.size())+EPSILON);
    if (num_filaments != old_number_of_filaments) {
        // First verify if purging volumes presets for each extruder matches number of extruders
        std::vector<double>& filaments = this->project_config.option<ConfigOptionFloats>("flush_volumes_vector")->values;
        while (filaments.size() < 2* num_filaments) {
            filaments.push_back(filaments.size()>1 ? filaments[0] : 140.);  // copy the values from the first extruder
            filaments.push_back(filaments.size()>1 ? filaments[1] : 140.);
        }
        while (filaments.size() > 2* num_filaments) {
            filaments.pop_back();
            filaments.pop_back();
        }
        std::vector<double> new_matrix;
        for (unsigned int i=0;i< num_filaments;++i)
            for (unsigned int j=0;j< num_filaments;++j) {
                // append the value for this pair from the old matrix (if it's there):
                if (i < old_number_of_filaments && j < old_number_of_filaments)
                    new_matrix.push_back(old_matrix[i* old_number_of_filaments + j]);
                else
                    new_matrix.push_back( i == j ? 0. : filaments[2 * i] + filaments[2 * j + 1]); // so it matches new extruder volumes
            }
    this->project_config.option<ConfigOptionFloats>("flush_volumes_matrix")->values = new_matrix;
    }
}
References Slic3r::Preset::config, EPSILON, filament_presets, filaments, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::Preset::name, Slic3r::ConfigBase::option(), Slic3r::Preset::printer_technology(), printers, project_config, Slic3r::ptFFF, Slic3r::PresetCollection::size(), sqrt(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::TabPrinter::extruders_count_changed(), load_config_file_config(), load_presets(), load_selections(), load_user_presets(), load_user_presets(), set_num_filaments(), sync_ams_list(), Slic3r::GUI::TabPrinter::update_pages(), and update_selections().
update_selections()
void Slic3r::PresetBundle::update_selections (AppConfig & config)
{
    std::string initial_printer_profile_name    = printers.get_selected_preset_name();
    // Orca: load from orca_presets
    std::string initial_print_profile_name        = config.get_printer_setting(initial_printer_profile_name, PRESET_PRINT_NAME);
    std::string initial_filament_profile_name     = config.get_printer_setting(initial_printer_profile_name, PRESET_FILAMENT_NAME);
    // Selects the profiles, which were selected at the last application close.
    prints.select_preset_by_name_strict(initial_print_profile_name);
    filaments.select_preset_by_name_strict(initial_filament_profile_name);
    // Load the names of the other filament profiles selected for a multi-material printer.
    // Load it even if the current printer technology is SLA.
    // The possibly excessive filament names will be later removed with this->update_multi_material_filament_presets()
    // once the FFF technology gets selected.
    this->filament_presets = { filaments.get_selected_preset_name() };
    for (unsigned int i = 1; i < 1000; ++ i) {
        char name[64];
        sprintf(name, "filament_%02u", i);
        auto f_name = config.get_printer_setting(initial_printer_profile_name, name);
        if (f_name.empty())
            break;
        this->filament_presets.emplace_back(remove_ini_suffix(f_name));
    }
    std::vector<std::string> filament_colors;
    auto f_colors = config.get_printer_setting(initial_printer_profile_name, "filament_colors");
    if (!f_colors.empty()) {
        boost::algorithm::split(filament_colors, f_colors, boost::algorithm::is_any_of(","));
    }
    filament_colors.resize(filament_presets.size(), "#FF8040");
    project_config.option<ConfigOptionStrings>("filament_colour")->values = filament_colors;
    std::vector<std::string> matrix;
    if (config.has_printer_setting(initial_printer_profile_name, "flush_volumes_matrix")) {
        boost::algorithm::split(matrix, config.get_printer_setting(initial_printer_profile_name, "flush_volumes_matrix"), boost::algorithm::is_any_of("|"));
        auto flush_volumes_matrix = matrix | boost::adaptors::transformed(boost::lexical_cast<double, std::string>);
        project_config.option<ConfigOptionFloats>("flush_volumes_matrix")->values = std::vector<double>(flush_volumes_matrix.begin(), flush_volumes_matrix.end());
    }
    if (config.has_printer_setting(initial_printer_profile_name, "flush_volumes_vector")) {
        boost::algorithm::split(matrix, config.get_printer_setting(initial_printer_profile_name, "flush_volumes_vector"), boost::algorithm::is_any_of("|"));
        auto flush_volumes_vector = matrix | boost::adaptors::transformed(boost::lexical_cast<double, std::string>);
        project_config.option<ConfigOptionFloats>("flush_volumes_vector")->values = std::vector<double>(flush_volumes_vector.begin(), flush_volumes_vector.end());
    }
    if (config.has("app", "flush_multiplier")) {
        std::string str_flush_multiplier = config.get("app", "flush_multiplier");
        if (!str_flush_multiplier.empty())
            project_config.option<ConfigOptionFloat>("flush_multiplier")->set(new ConfigOptionFloat(std::stof(str_flush_multiplier)));
    }
    // Update visibility of presets based on their compatibility with the active printer.
    // Always try to select a compatible print and filament preset to the current printer preset,
    // as the application may have been closed with an active "external" preset, which does not
    // exist.
    this->update_compatible(PresetSelectCompatibleType::Always);
    this->update_multi_material_filament_presets();
    std::string first_visible_filament_name;
    for (auto & fp : filament_presets) {
        if (auto it = filaments.find_preset_internal(fp); it == filaments.end() || !it->is_visible || !it->is_compatible) {
            if (first_visible_filament_name.empty())
                first_visible_filament_name = filaments.first_compatible().name;
            fp = first_visible_filament_name;
        }
    }
}
References Slic3r::Always, Slic3r::PresetCollection::end(), filament_presets, filaments, Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::first_compatible(), Slic3r::flush_volumes_vector(), Slic3r::AppConfig::get(), Slic3r::AppConfig::get_printer_setting(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::AppConfig::has(), Slic3r::AppConfig::has_printer_setting(), Slic3r::Preset::name, Slic3r::ConfigBase::option(), PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, printers, prints, project_config, Slic3r::remove_ini_suffix(), Slic3r::PresetCollection::select_preset_by_name_strict(), Slic3r::ConfigOptionSingle< T >::set(), update_compatible(), and update_multi_material_filament_presets().
Referenced by Slic3r::GUI::Tab::select_preset().
update_system_maps()
void Slic3r::PresetBundle::update_system_maps () private
{
    this->prints     .update_map_system_profile_renamed();
    this->sla_prints   .update_map_system_profile_renamed();
    this->filaments    .update_map_system_profile_renamed();
    this->sla_materials.update_map_system_profile_renamed();
    this->printers     .update_map_system_profile_renamed();
    this->prints       .update_map_alias_to_profile_name();
    this->sla_prints   .update_map_alias_to_profile_name();
    this->filaments    .update_map_alias_to_profile_name();
    this->sla_materials.update_map_alias_to_profile_name();
}
References filaments, printers, prints, sla_materials, sla_prints, Slic3r::PresetCollection::update_map_alias_to_profile_name(), and Slic3r::PresetCollection::update_map_system_profile_renamed().
Referenced by load_installed_printers(), and load_system_presets_from_json().
update_system_preset_setting_ids()
void Slic3r::PresetBundle::update_system_preset_setting_ids (std::map< std::string, std::map< std::string, std::string > > & system_presets)
{
    for (auto iterator: system_presets)
    {
        std::string name = iterator.first;
        std::map<std::string, std::string>& value_map = iterator.second;
        //get the type first
        std::map<std::string, std::string>::iterator type_iter = value_map.find(BBL_JSON_KEY_TYPE);
        if (type_iter == value_map.end()) {
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(" can not find type for setting %1%")%name;
            continue;
        }
        PresetCollection *preset_collection = nullptr;
        if (type_iter->second == PRESET_IOT_PRINTER_TYPE) {
            preset_collection = &(this->printers);
        }
        else if (type_iter->second == PRESET_IOT_PRINTER_TYPE) {
            preset_collection = &(this->printers);
        }
        else if (type_iter->second == PRESET_IOT_PRINTER_TYPE) {
            preset_collection = &(this->printers);
        }
        else {
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format("invalid type %1% for setting %2%") %type_iter->second %name;
            continue;
        }
        std::string setting_id;
        if (value_map.count(BBL_JSON_KEY_SETTING_ID) > 0)
            setting_id = value_map[BBL_JSON_KEY_SETTING_ID];
        else {
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(" can not find setting_id for setting %1%")%name;
            continue;
        }
        Preset* preset = preset_collection->find_preset(name, false, true);
        if (preset) {
            if (!preset->setting_id.empty() && (preset->setting_id.compare(setting_id) != 0)) {
                BOOST_LOG_TRIVIAL(error) << boost::format("name %1%, local setting_id %2% is different with remote id %3%")
                    %preset->name %preset->setting_id %setting_id;
            }
            else if (preset->setting_id.empty())
                preset->setting_id = setting_id;
        }
        else {
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format("can not find setting %1% in system presets, type %2%") %name %type_iter->second;
            continue;
        }
    }
    return;
}
References BBL_JSON_KEY_SETTING_ID, BBL_JSON_KEY_TYPE, error, Slic3r::PresetCollection::find_preset(), Slic3r::Preset::name, PRESET_IOT_PRINTER_TYPE, printers, and Slic3r::Preset::setting_id.
update_user_presets_directory()
void Slic3r::PresetBundle::update_user_presets_directory (const std::string preset_folder)
{
    //BBS: change directory by design
    const std::string dir_user_presets = data_dir() + "/" + PRESET_USER_DIR + "/"+ preset_folder;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, update directory to %1%")%dir_user_presets;
    fs::path user_folder(data_dir() + "/" + PRESET_USER_DIR);
    if (!fs::exists(user_folder))
        fs::create_directory(user_folder);
    fs::path folder(dir_user_presets);
    if (!fs::exists(folder))
        fs::create_directory(folder);
    this->prints.update_user_presets_directory(dir_user_presets, PRESET_PRINT_NAME);
    this->filaments.update_user_presets_directory(dir_user_presets, PRESET_FILAMENT_NAME);
    this->printers.update_user_presets_directory(dir_user_presets, PRESET_PRINTER_NAME);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" finished");
}
References Slic3r::data_dir(), filaments, PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, PRESET_USER_DIR, printers, prints, and Slic3r::PresetCollection::update_user_presets_directory().
validate_printers()
bool Slic3r::PresetBundle::validate_printers (const std::string & name, DynamicPrintConfig & config)
{
    // BBS TODO:
#if 0
    std::vector<std::string> inherits_values;
    PrinterTechnology printer_technology = Preset::printer_technology(config);
    size_t num_extruders = (printer_technology == ptFFF) ?
        std::min(config.option<ConfigOptionFloats>("nozzle_diameter"  )->values.size(),
                 config.option<ConfigOptionFloats>("filament_diameter")->values.size()) : 1;
    inherits_values.resize(num_extruders + 2, std::string());
    inherits_values  = config.option<ConfigOptionStrings>("inherits_group", true)->values;
    std::string inherits;
    if (inherits_values.size() >= (num_extruders + 2))
        inherits = inherits_values[num_extruders + 1];
    return this->printers.validate_printers(name, config, inherits);
#else
    return true;
#endif
}
References Slic3r::ConfigBase::option(), Slic3r::printer_technology(), Slic3r::Preset::printer_technology(), printers, Slic3r::ptFFF, Slic3r::ConfigOptionVector< T >::size(), Slic3r::PresetCollection::validate_printers(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::Plater::priv::load_files().
Member Data Documentation
BBL_BUNDLE
const char * Slic3r::PresetBundle::BBL_BUNDLE = "Custom" static
Referenced by Slic3r::GUI::GuideFrame::apply_config(), Slic3r::GUI::BundleMap::bbl_bundle(), Slic3r::PresetUpdater::priv::check_installed_vendor_profiles(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::ConfigWizard::priv::create_3rdparty_pages(), Slic3r::GUI::BundleMap::load(), Slic3r::GUI::GuideFrame::LoadProfile(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::PagePrinters::set_run_reason(), and Slic3r::GUI::GUI_App::start_sync_user_preset().
BBL_DEFAULT_FILAMENT
const char * Slic3r::PresetBundle::BBL_DEFAULT_FILAMENT = "My Generic PLA" static
BBL_DEFAULT_PRINTER_MODEL
const char * Slic3r::PresetBundle::BBL_DEFAULT_PRINTER_MODEL = "MyKlipper 0.4 nozzle" static
Referenced by Slic3r::GUI::GCodeViewer::init(), remove_users_preset(), and Slic3r::GUI::GuideFrame::run().
BBL_DEFAULT_PRINTER_VARIANT
const char * Slic3r::PresetBundle::BBL_DEFAULT_PRINTER_VARIANT = "0.4" static
Referenced by Slic3r::GUI::GuideFrame::run().
calibrate_filaments
std::set<Preset const *> Slic3r::PresetBundle::calibrate_filaments
Referenced by set_calibrate_printer().
calibrate_printer
Preset const* Slic3r::PresetBundle::calibrate_printer = nullptr
Referenced by set_calibrate_printer().
filament_ams_list
std::vector<DynamicPrintConfig> Slic3r::PresetBundle::filament_ams_list
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), and sync_ams_list().
filament_presets
std::vector<std::string> Slic3r::PresetBundle::filament_presets
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), export_current_configs(), export_selections(), Slic3r::GUI::GUI_App::filaments_cnt(), full_fff_config(), get_current_project_embedded_presets(), is_the_only_edited_filament(), load_config_file_config(), Slic3r::GUI::Plater::priv::load_files(), load_selections(), Slic3r::GUI::Plater::merge(), operator=(), remove_users_preset(), reset(), reset_project_embedded_presets(), Slic3r::GUI::Plater::segment(), Slic3r::GUI::Tab::select_preset(), set_filament_preset(), set_num_filaments(), sync_ams_list(), Slic3r::GUI::PlaterPresetComboBox::update(), update_compatible(), update_multi_material_filament_presets(), Slic3r::GUI::Sidebar::update_presets_from_to(), and update_selections().
filaments
PresetCollection Slic3r::PresetBundle::filaments
Referenced by PresetBundle(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::TabFilament::build(), export_current_configs(), full_fff_config(), Slic3r::GUI::ExtrusionCalibration::get_bed_type_incompatible(), get_current_project_embedded_presets(), get_differed_values_to_update(), get_preset_differed_for_save(), get_preset_name_by_alias(), has_defauls_only(), import_presets(), is_the_only_edited_filament(), load_config_file_config(), load_installed_filaments(), load_project_embedded_presets(), load_selections(), load_user_presets(), load_user_presets(), load_vendor_configs_from_json(), materials(), materials(), merge_presets(), Slic3r::GUI::ExtrusionCalibration::on_click_cali(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::AMSMaterialsSetting::on_select_filament(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), operator=(), Slic3r::GUI::AMSMaterialsSetting::Popup(), remove_users_preset(), reset(), reset_project_embedded_presets(), save_changes_for_preset(), save_user_presets(), Slic3r::GUI::Tab::select_preset(), set_calibrate_printer(), set_default_suppressed(), Slic3r::GUI::GUI_App::start_sync_user_preset(), sync_ams_list(), Slic3r::GUI::GUI_App::sync_preset(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), update_compatible(), Slic3r::GUI::ExtrusionCalibration::update_filament_info(), update_multi_material_filament_presets(), Slic3r::GUI::Sidebar::update_presets(), update_selections(), update_system_maps(), and update_user_presets_directory().
obsolete_presets
ObsoletePresets Slic3r::PresetBundle::obsolete_presets
Referenced by merge_presets(), operator=(), and reset().
physical_printers
PhysicalPrinterCollection Slic3r::PresetBundle::physical_printers
Referenced by Slic3r::GUI::GUI_App::check_printer_presets(), Slic3r::GUI::Tab::delete_preset(), load_config_file_config(), load_selections(), operator=(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::Tab::update_btns_enabling().
printers
PrinterPresetCollection Slic3r::PresetBundle::printers
Referenced by Slic3r::GUI::MainFrame::MainFrame(), PresetBundle(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GUI_App::apply_keeped_preset_modifications(), Slic3r::GUI::TabPrinter::build(), Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::GUI_App::check_printer_presets(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::GUI_App::config_wizard_startup(), export_current_configs(), export_selections(), Slic3r::GUI::GUI_App::extruders_cnt(), Slic3r::GUI::TabPrinter::extruders_count_changed(), Slic3r::GUI::GUI_App::extruders_edited_cnt(), full_config(), full_fff_config(), full_sla_config(), get_current_project_embedded_presets(), get_differed_values_to_update(), get_preset_differed_for_save(), Slic3r::Preset::get_printer_type(), Slic3r::GUI::GUI_App::get_selected_presets(), Slic3r::GUI::GUI_App::has_current_preset_changes(), has_defauls_only(), Slic3r::Preset::has_lidar(), Slic3r::GUI::GUI_App::has_unsaved_preset_changes(), import_presets(), Slic3r::GUI::GCodeViewer::init(), Slic3r::GUI::SelectMachineDialog::is_same_printer_model(), load_config_file_config(), Slic3r::GUI::GUI_App::load_current_presets(), load_installed_filaments(), load_installed_printers(), load_installed_sla_materials(), Slic3r::GUI::MainFrame::load_printer_url(), load_project_embedded_presets(), load_selections(), load_user_presets(), load_user_presets(), load_vendor_configs_from_json(), Slic3r::GUI::Plater::merge(), merge_presets(), Slic3r::GUI::Plater::priv::on_select_bed_type(), operator=(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::BackgroundSlicingProcess::process_fff(), remove_users_preset(), reset(), reset_project_embedded_presets(), Slic3r::GUI::Plater::reslice(), Slic3r::GUI::GuideFrame::run(), save_changes_for_preset(), save_user_presets(), Slic3r::GUI::Plater::segment(), Slic3r::GUI::Tab::select_preset(), set_calibrate_printer(), set_default_suppressed(), Slic3r::GUI::GUI_App::start_sync_user_preset(), Slic3r::GUI::GUI_App::sync_preset(), Slic3r::GUI::TabFilament::toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::TabFilament::update(), Slic3r::GUI::TabSLAMaterial::update(), Slic3r::GUI::TabSLAPrint::update(), Slic3r::GUI::Sidebar::update_all_preset_comboboxes(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), Slic3r::GUI::DiffPresetDialog::update_compatibility(), update_compatible(), update_multi_material_filament_presets(), Slic3r::GUI::Sidebar::update_presets(), Slic3r::GUI::GUI_App::update_saved_preset_from_current_preset(), update_selections(), update_system_maps(), update_system_preset_setting_ids(), update_user_presets_directory(), and validate_printers().
prints
PresetCollection Slic3r::PresetBundle::prints
Referenced by PresetBundle(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::Tab::compatible_widget_create(), export_current_configs(), export_selections(), full_fff_config(), get_current_project_embedded_presets(), get_differed_values_to_update(), get_preset_differed_for_save(), get_preset_name_by_alias(), has_defauls_only(), import_presets(), load_config_file_config(), load_project_embedded_presets(), load_selections(), load_user_presets(), load_user_presets(), load_vendor_configs_from_json(), merge_presets(), operator=(), remove_users_preset(), reset(), reset_project_embedded_presets(), save_changes_for_preset(), save_user_presets(), Slic3r::GUI::Tab::select_preset(), set_default_suppressed(), Slic3r::GUI::GUI_App::start_sync_user_preset(), Slic3r::GUI::GUI_App::sync_preset(), update_compatible(), update_selections(), update_system_maps(), and update_user_presets_directory().
project_config
DynamicPrintConfig Slic3r::PresetBundle::project_config
Referenced by PresetBundle(), Slic3r::GUI::ConfigWizard::priv::apply_config(), export_selections(), Slic3r::GUI::TabPrinter::extruders_count_changed(), full_fff_config(), load_config_file_config(), Slic3r::GUI::Plater::priv::load_files(), load_selections(), operator=(), Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets(), set_num_filaments(), sync_ams_list(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::ProjectDirtyStateManager::update_from_presets(), update_multi_material_filament_presets(), and update_selections().
sla_materials
PresetCollection Slic3r::PresetBundle::sla_materials
Referenced by PresetBundle(), Slic3r::GUI::PresetComboBox::PresetComboBox(), full_sla_config(), get_preset_name_by_alias(), load_installed_sla_materials(), load_selections(), materials(), materials(), merge_presets(), operator=(), reset(), save_changes_for_preset(), Slic3r::GUI::Tab::select_preset(), set_default_suppressed(), update_compatible(), and update_system_maps().
sla_prints
PresetCollection Slic3r::PresetBundle::sla_prints
Referenced by PresetBundle(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::TabSLAPrint::build(), Slic3r::GUI::Tab::compatible_widget_create(), full_sla_config(), get_preset_name_by_alias(), merge_presets(), operator=(), reset(), save_changes_for_preset(), set_default_suppressed(), update_compatible(), and update_system_maps().
vendors
VendorMap Slic3r::PresetBundle::vendors
Referenced by Slic3r::Preset::get_current_printer_type(), get_hotend_model_for_printer_model(), Slic3r::Preset::get_printer_type(), get_stl_model_for_printer_model(), get_texture_for_printer_model(), get_vendor_profile_version(), Slic3r::Preset::has_lidar(), load_vendor_configs_from_json(), merge_presets(), operator=(), reset(), Slic3r::PresetUpdater::sync(), and Slic3r::GUI::Config::SnapshotDB::take_snapshot().
The documentation for this class was generated from the following files:
src/libslic3r/PresetBundle.hpp
src/libslic3r/PresetBundle.cpp