OrcaSlicer: Slic3r::ModelConfigObject Class Reference
Slic3r::ModelConfigObject Class Reference
#include <src/libslic3r/Model.hpp>
Public Types
using Timestamp = uint64_t
Public Member Functions
ObjectID id () const
void reset ()
void assign_config (const ModelConfig &rhs)
void assign_config (ModelConfig &&rhs)
void assign_config (const DynamicPrintConfig &rhs)
void assign_config (DynamicPrintConfig &&rhs)
void apply (const ModelConfig &other, bool ignore_nonexistent=false)
void apply (const ConfigBase &other, bool ignore_nonexistent=false)
void apply_only (const ModelConfig &other, const t_config_option_keys &keys, bool ignore_nonexistent=false)
void apply_only (const ConfigBase &other, const t_config_option_keys &keys, bool ignore_nonexistent=false)
bool set_key_value (const std::string &opt_key, ConfigOption *opt)
template<typename T >
void set (const std::string &opt_key, T value)
void set_deserialize (const t_config_option_key &opt_key, const std::string &str, ConfigSubstitutionContext &substitution_context, bool append=false)
bool erase (const t_config_option_key &opt_key)
const DynamicPrintConfig & get () const throw ()
bool empty () const throw ()
size_t size () const throw ()
auto cbegin () const
auto cend () const
t_config_option_keys keys () const
bool has (const t_config_option_key &opt_key) const
const ConfigOption * option (const t_config_option_key &opt_key) const
int opt_int (const t_config_option_key &opt_key) const
int extruder () const
double opt_float (const t_config_option_key &opt_key) const
double get_abs_value (const t_config_option_key &opt_key) const
std::string opt_serialize (const t_config_option_key &opt_key) const
bool timestamp_matches (const ModelConfig &rhs) const throw ()
void touch ()
Protected Member Functions
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
ModelConfigObject ()=default
ModelConfigObject (int)
ModelConfigObject (const ModelConfigObject &cfg)=default
ModelConfigObject (ModelConfigObject &&cfg)=default
Timestamp timestamp () const override throw ()
bool object_id_and_timestamp_match (const ModelConfigObject &rhs) const throw ()
ModelConfigObject & operator= (const ModelConfigObject &rhs)=default
ModelConfigObject & operator= (ModelConfigObject &&rhs)=default
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
ObjectID m_id
uint64_t m_timestamp { 1 }
DynamicPrintConfig m_data
Static Private Attributes
static size_t s_last_id = 0
static uint64_t s_last_timestamp = 1
Friends
class cereal::access
class UndoRedo::StackImpl
class ModelObject
class ModelVolume
class ModelMaterial
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
ModelConfigObject() [1/4]
Slic3r::ModelConfigObject::ModelConfigObject () explicit private default
ModelConfigObject() [2/4]
Slic3r::ModelConfigObject::ModelConfigObject (int) inline explicit private
: ObjectBase(-1) {}
ModelConfigObject() [3/4]
Slic3r::ModelConfigObject::ModelConfigObject (const ModelConfigObject & cfg) explicit private default
ModelConfigObject() [4/4]
Slic3r::ModelConfigObject::ModelConfigObject (ModelConfigObject && cfg) explicit private default
Member Function Documentation
apply() [1/2]
void Slic3r::ModelConfig::apply (const ConfigBase & other, bool ignore_nonexistent = false) inline inherited
{ m_data.apply_only(other, other.keys(), ignore_nonexistent); this->touch(); }
References Slic3r::ConfigBase::apply_only(), Slic3r::ConfigBase::keys(), Slic3r::ModelConfig::m_data, and Slic3r::ModelConfig::touch().
apply() [2/2]
void Slic3r::ModelConfig::apply (const ModelConfig & other, bool ignore_nonexistent = false) inline inherited
{ this->apply(other.get(), ignore_nonexistent); }
References Slic3r::ModelConfig::apply(), and Slic3r::ModelConfig::get().
Referenced by Slic3r::ModelConfig::apply(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), and Slic3r::ModelObject::split().
apply_only() [1/2]
void Slic3r::ModelConfig::apply_only (const ConfigBase & other, const t_config_option_keys & keys, bool ignore_nonexistent = false) inline inherited
{ m_data.apply_only(other, keys, ignore_nonexistent); this->touch(); }
References Slic3r::ConfigBase::apply_only(), Slic3r::ModelConfig::keys(), Slic3r::ModelConfig::m_data, and Slic3r::ModelConfig::touch().
apply_only() [2/2]
void Slic3r::ModelConfig::apply_only (const ModelConfig & other, const t_config_option_keys & keys, bool ignore_nonexistent = false) inline inherited
{ this->apply_only(other.get(), keys, ignore_nonexistent); }
References Slic3r::ModelConfig::apply_only(), Slic3r::ModelConfig::get(), and Slic3r::ModelConfig::keys().
Referenced by Slic3r::ModelConfig::apply_only(), Slic3r::GUI::ObjectTableSettings::update_config_values(), and Slic3r::GUI::ObjectSettings::update_config_values().
assign_config() [1/4]
void Slic3r::ModelConfig::assign_config (const DynamicPrintConfig & rhs) inline inherited
{ if (m_data != rhs) { m_data = rhs; this->touch(); } }
References Slic3r::ModelConfig::m_data, and Slic3r::ModelConfig::touch().
assign_config() [2/4]
void Slic3r::ModelConfig::assign_config (const ModelConfig & rhs) inline inherited
{
        if (m_timestamp != rhs.m_timestamp) {
            m_data      = rhs.m_data;
            m_timestamp = rhs.m_timestamp;
        }
    }
References Slic3r::ModelConfig::m_data, and Slic3r::ModelConfig::m_timestamp.
Referenced by Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::convert_units(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::ObjectList::merge(), Slic3r::ModelObject::merge_volumes(), Slic3r::model_volume_list_copy_configs(), Slic3r::ModelObject::segment(), and Slic3r::ModelObject::split().
assign_config() [3/4]
void Slic3r::ModelConfig::assign_config (DynamicPrintConfig && rhs) inline inherited
{ if (m_data != rhs) { m_data = std::move(rhs); this->touch(); } }
References Slic3r::ModelConfig::m_data, and Slic3r::ModelConfig::touch().
assign_config() [4/4]
void Slic3r::ModelConfig::assign_config (ModelConfig && rhs) inline inherited
{
        if (m_timestamp != rhs.m_timestamp) {
            m_data      = std::move(rhs.m_data);
            m_timestamp = rhs.m_timestamp;
            rhs.reset();
        }
    }
References Slic3r::ModelConfig::m_data, and Slic3r::ModelConfig::m_timestamp.
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
cbegin()
auto Slic3r::ModelConfig::cbegin () const inline inherited
{ return m_data.cbegin(); }
References Slic3r::DynamicConfig::cbegin(), and Slic3r::ModelConfig::m_data.
cend()
auto Slic3r::ModelConfig::cend () const inline inherited
{ return m_data.cend(); }
References Slic3r::DynamicConfig::cend(), and Slic3r::ModelConfig::m_data.
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
empty()
bool Slic3r::ModelConfig::empty () const throw () inline inherited
{ return m_data.empty(); }
References Slic3r::DynamicConfig::empty(), and Slic3r::ModelConfig::m_data.
erase()
bool Slic3r::ModelConfig::erase (const t_config_option_key & opt_key) inline inherited
{ bool out = m_data.erase(opt_key); if (out) this->touch(); return out; }
References Slic3r::DynamicConfig::erase(), Slic3r::ModelConfig::m_data, out, and Slic3r::ModelConfig::touch().
Referenced by Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::ObjectGridTable::reload_part_data(), Slic3r::GUI::ObjectTableSettings::resetAllValues(), Slic3r::GUI::ObjectList::update_filament_values_for_items(), Slic3r::GUI::ObjectGridTable::update_value_to_config(), and Slic3r::GUI::ObjectGridTable::update_volume_values_from_object().
extruder()
int Slic3r::ModelConfig::extruder () const inline inherited
{ return opt_int("extruder"); }
References Slic3r::ModelConfig::opt_int().
Referenced by Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::GUI::ObjectDataViewModel::AddObject(), Slic3r::GUI::MenuFactory::append_menu_item_change_extruder(), Slic3r::GUI::MenuFactory::append_menu_item_change_filament(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::del_subobject_from_object(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::Print::process(), and Slic3r::GUI::ObjectList::update_filament_values_for_items().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get()
const DynamicPrintConfig & Slic3r::ModelConfig::get () const throw () inline inherited
{ return m_data; }
References Slic3r::ModelConfig::m_data.
Referenced by Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::SLAPrint::apply(), Slic3r::ModelConfig::apply(), Slic3r::ModelConfig::apply_only(), Slic3r::GUI::ObjectList::copy_settings_to_clipboard(), Slic3r::GUI::ObjectList::del_subobject_from_object(), Slic3r::sla::find_least_supports_rotation(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::ObjectList::object_config_options_changed(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::Print::process(), Slic3r::GUI::ObjectTableSettings::resetAllValues(), Slic3r::GUI::ObjectSettings::update_config_values(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
get_abs_value()
double Slic3r::ModelConfig::get_abs_value (const t_config_option_key & opt_key) const inline inherited
{
      return m_data.get_abs_value(opt_key);
    }
References Slic3r::ConfigBase::get_abs_value(), and Slic3r::ModelConfig::m_data.
has()
bool Slic3r::ModelConfig::has (const t_config_option_key & opt_key) const inline inherited
{ return m_data.has(opt_key); }
References Slic3r::ConfigOptionResolver::has(), and Slic3r::ModelConfig::m_data.
Referenced by Slic3r::GUI::ObjectList::add_layer_item(), Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::GUI::ObjectTableSettings::add_missed_options(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::GUI::ObjectDataViewModel::AddObject(), Slic3r::GUI::MenuFactory::append_menu_item_change_extruder(), Slic3r::GUI::MenuFactory::append_menu_item_change_filament(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::ModelObject::get_config_value(), Slic3r::GUI::ObjectList::get_default_layer_config(), Slic3r::GUI::ObjectGridTable::get_volume_config_value(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::Print::process(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::ObjectTableSettings::update_extra_column_visible_status(), Slic3r::GUI::ObjectList::update_filament_values_for_items(), Slic3r::GUI::ObjectGridTable::update_value_to_config(), and Slic3r::GUI::ObjectTableSettings::ValueChanged().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
keys()
t_config_option_keys Slic3r::ModelConfig::keys () const inline inherited
{ return m_data.keys(); }
References Slic3r::DynamicConfig::keys(), and Slic3r::ModelConfig::m_data.
Referenced by Slic3r::_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::ModelConfig::apply_only(), Slic3r::ModelConfig::apply_only(), Slic3r::GUI::create_settings_popupmenu(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::merge(), and Slic3r::GUI::ObjectSettings::update_config_values().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
object_id_and_timestamp_match()
bool Slic3r::ModelConfigObject::object_id_and_timestamp_match (const ModelConfigObject & rhs) const throw () inline private
{ return this->id() == rhs.id() && this->timestamp() == rhs.timestamp(); }
References Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), and timestamp().
operator=() [1/2]
ModelConfigObject & Slic3r::ModelConfigObject::operator= (const ModelConfigObject & rhs) private default
operator=() [2/2]
ModelConfigObject & Slic3r::ModelConfigObject::operator= (ModelConfigObject && rhs) private default
opt_float()
double Slic3r::ModelConfig::opt_float (const t_config_option_key & opt_key) const inline inherited
{
      return m_data.opt_float(opt_key);
    }
References Slic3r::ModelConfig::m_data, and Slic3r::DynamicConfig::opt_float().
Referenced by Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::edit_layer_range(), and Slic3r::GUI::ObjectList::get_default_layer_config().
opt_int()
int Slic3r::ModelConfig::opt_int (const t_config_option_key & opt_key) const inline inherited
{ return m_data.opt_int(opt_key); }
References Slic3r::ModelConfig::m_data, and Slic3r::DynamicConfig::opt_int().
Referenced by Slic3r::GUI::ObjectList::add_layer_item(), Slic3r::GUI::ObjectList::edit_layer_range(), Slic3r::ModelConfig::extruder(), Slic3r::GUI::ObjectList::get_default_layer_config(), Slic3r::GUI::ObjectList::load_generic_subobject(), and Slic3r::GUI::ObjectList::load_modifier().
opt_serialize()
std::string Slic3r::ModelConfig::opt_serialize (const t_config_option_key & opt_key) const inline inherited
{ return m_data.opt_serialize(opt_key); }
References Slic3r::ModelConfig::m_data, and Slic3r::ConfigBase::opt_serialize().
Referenced by Slic3r::_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(), and Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive().
option()
const ConfigOption * Slic3r::ModelConfig::option (const t_config_option_key & opt_key) const inline inherited
{ return m_data.option(opt_key); }
References Slic3r::ModelConfig::m_data, and Slic3r::ConfigBase::option().
Referenced by Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::ModelObject::get_config_value(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::ObjectGridTable::get_volume_config_value(), Slic3r::GUI::ObjectList::merge(), Slic3r::CLI::run(), Slic3r::GUI::ObjectList::split(), Slic3r::GUI::ObjectGridTable::update_volume_values_from_object(), and Slic3r::GUI::ObjectTableSettings::ValueChanged().
reset()
void Slic3r::ModelConfig::reset () inline inherited
{ m_data.clear(); touch(); }
References Slic3r::DynamicConfig::clear(), Slic3r::ModelConfig::m_data, and Slic3r::ModelConfig::touch().
Referenced by Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::ModelObject::split(), and Slic3r::GUI::ObjectTableSettings::update_config_values().
serialize()
template<class Archive > void Slic3r::ModelConfigObject::serialize (Archive & ar) inline private
{
        ar(cereal::base_class<ModelConfig>(this));
    }
set()
template<typename T > void Slic3r::ModelConfig::set (const std::string & opt_key, T value) inline inherited
{ m_data.set(opt_key, value, true); this->touch(); }
References Slic3r::ModelConfig::m_data, Slic3r::ConfigBase::set(), and Slic3r::ModelConfig::touch().
Referenced by Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::ModelObject::segment(), and Slic3r::GUI::ObjectList::set_extruder_for_selected_items().
set_deserialize()
void Slic3r::ModelConfig::set_deserialize (const t_config_option_key & opt_key, const std::string & str, ConfigSubstitutionContext & substitution_context, bool append = false) inline inherited
        { m_data.set_deserialize(opt_key, str, substitution_context, append); this->touch(); }
References Slic3r::append(), Slic3r::ModelConfig::m_data, Slic3r::ConfigBase::set_deserialize(), and Slic3r::ModelConfig::touch().
Referenced by Slic3r::_3MF_Importer::_load_model_from_file().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_key_value()
bool Slic3r::ModelConfig::set_key_value (const std::string & opt_key, ConfigOption * opt) inline inherited
{ bool out = m_data.set_key_value(opt_key, opt); this->touch(); return out; }
References Slic3r::ModelConfig::m_data, out, Slic3r::DynamicConfig::set_key_value(), and Slic3r::ModelConfig::touch().
Referenced by Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::GUI::ObjectTableSettings::add_missed_options(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::edit_layer_range(), Slic3r::GUI::ObjectList::get_default_layer_config(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::ObjectList::update_filament_in_config(), Slic3r::GUI::ObjectGridTable::update_filament_to_config(), and Slic3r::GUI::ObjectGridTable::update_value_to_config().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
size()
size_t Slic3r::ModelConfig::size () const throw () inline inherited
{ return m_data.size(); }
References Slic3r::ModelConfig::m_data, and Slic3r::DynamicConfig::size().
timestamp()
Timestamp Slic3r::ModelConfigObject::timestamp () const throw () inline override private virtual
Reimplemented from Slic3r::ObjectBase.
{ return this->ModelConfig::timestamp(); }
References Slic3r::ModelConfig::timestamp().
Referenced by object_id_and_timestamp_match().
timestamp_matches()
bool Slic3r::ModelConfig::timestamp_matches (const ModelConfig & rhs) const throw () inline inherited
{ return m_timestamp == rhs.m_timestamp; }
References Slic3r::ModelConfig::m_timestamp.
Referenced by Slic3r::Print::apply(), and Slic3r::SLAPrint::apply().
touch()
void Slic3r::ModelConfig::touch () inline inherited
{ m_timestamp = ++ s_last_timestamp; }
References Slic3r::ModelConfig::m_timestamp, and Slic3r::ModelConfig::s_last_timestamp.
Referenced by Slic3r::ModelConfig::apply(), Slic3r::ModelConfig::apply_only(), Slic3r::ModelConfig::assign_config(), Slic3r::ModelConfig::assign_config(), Slic3r::GUI::ConfigOptionsGroup::change_opt_value(), Slic3r::ModelConfig::erase(), Slic3r::GUI::ConfigOptionsGroup::on_change_OG(), Slic3r::ModelConfig::reset(), Slic3r::ModelConfig::set(), Slic3r::ModelConfig::set_deserialize(), Slic3r::ModelConfig::set_key_value(), Slic3r::GUI::ObjectGridTable::update_filament_to_config(), and Slic3r::GUI::ObjectGridTable::update_value_to_config().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
ModelMaterial
friend class ModelMaterial friend
ModelObject
friend class ModelObject friend
ModelVolume
friend class ModelVolume friend
UndoRedo::StackImpl
friend class UndoRedo::StackImpl friend
Member Data Documentation
m_data
DynamicPrintConfig Slic3r::ModelConfig::m_data private inherited
Referenced by Slic3r::ModelConfig::apply(), Slic3r::ModelConfig::apply_only(), Slic3r::ModelConfig::assign_config(), Slic3r::ModelConfig::assign_config(), Slic3r::ModelConfig::assign_config(), Slic3r::ModelConfig::assign_config(), Slic3r::ModelConfig::cbegin(), Slic3r::ModelConfig::cend(), Slic3r::ModelConfig::empty(), Slic3r::ModelConfig::erase(), Slic3r::ModelConfig::get(), Slic3r::ModelConfig::get_abs_value(), Slic3r::ModelConfig::has(), Slic3r::ModelConfig::keys(), Slic3r::ModelConfig::opt_float(), Slic3r::ModelConfig::opt_int(), Slic3r::ModelConfig::opt_serialize(), Slic3r::ModelConfig::option(), Slic3r::ModelConfig::reset(), Slic3r::ModelConfig::serialize(), Slic3r::ModelConfig::set(), Slic3r::ModelConfig::set_deserialize(), Slic3r::ModelConfig::set_key_value(), and Slic3r::ModelConfig::size().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_timestamp
uint64_t Slic3r::ModelConfig::m_timestamp { 1 } private inherited
Referenced by Slic3r::ModelConfig::assign_config(), Slic3r::ModelConfig::assign_config(), Slic3r::ModelConfig::serialize(), Slic3r::ModelConfig::timestamp(), Slic3r::ModelConfig::timestamp_matches(), and Slic3r::ModelConfig::touch().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
s_last_timestamp
uint64_t Slic3r::ModelConfig::s_last_timestamp = 1 static private inherited
Referenced by Slic3r::ModelConfig::touch().
The documentation for this class was generated from the following file:
src/libslic3r/Model.hpp