OrcaSlicer: Slic3r::GUI::MainFrame::FileHistory Struct Reference
Slic3r::GUI::MainFrame::FileHistory Struct Reference
Public Member Functions
FileHistory (int max)
std::wstring GetThumbnailUrl (int index) const
virtual void AddFileToHistory (const wxString &file)
virtual void RemoveFileFromHistory (size_t i)
size_t FindFileInHistory (const wxString &file)
void LoadThumbnails ()
void SetMaxFiles (int max)
Private Attributes
std::deque< std::string > m_thumbnails
bool m_load_called = false
Detailed Description
Constructor & Destructor Documentation
FileHistory()
Slic3r::GUI::MainFrame::FileHistory::FileHistory (int max) inline
: wxFileHistory(max) {}
Member Function Documentation
AddFileToHistory()
void Slic3r::GUI::MainFrame::FileHistory::AddFileToHistory (const wxString & file) virtual
{
    wxFileHistory::AddFileToHistory(file);
    if (m_load_called)
        m_thumbnails.push_front(bbs_3mf_get_thumbnail(into_u8(file).c_str()));
    else
        m_thumbnails.push_front("");
}
References Slic3r::bbs_3mf_get_thumbnail(), and Slic3r::GUI::into_u8().
FindFileInHistory()
size_t Slic3r::GUI::MainFrame::FileHistory::FindFileInHistory (const wxString & file)
{
    return m_fileHistory.Index(file);
}
GetThumbnailUrl()
std::wstring Slic3r::GUI::MainFrame::FileHistory::GetThumbnailUrl (int index) const
{
    if (m_thumbnails[index].empty()) return L"";
    std::wstringstream wss;
    wss << L"data:image/png;base64,";
    wss << wxBase64Encode(m_thumbnails[index].data(), m_thumbnails[index].size());
    return wss.str();
}
References Slic3r::empty(), L, and size.
LoadThumbnails()
void Slic3r::GUI::MainFrame::FileHistory::LoadThumbnails ()
{
    tbb::parallel_for(tbb::blocked_range<size_t>(0, GetCount()), [this](tbb::blocked_range<size_t> range) {
        for (size_t i = range.begin(); i < range.end(); ++i) {
            auto thumbnail = bbs_3mf_get_thumbnail(into_u8(GetHistoryFile(i)).c_str());
            if (!thumbnail.empty()) {
                m_thumbnails[i] = thumbnail;
            }
        }
    });
    m_load_called = true;
}
References Slic3r::bbs_3mf_get_thumbnail(), Slic3r::GUI::into_u8(), and Slic3r::range().
RemoveFileFromHistory()
void Slic3r::GUI::MainFrame::FileHistory::RemoveFileFromHistory (size_t i) virtual
{
    wxFileHistory::RemoveFileFromHistory(i);
    m_thumbnails.erase(m_thumbnails.begin() + i);
}
SetMaxFiles()
void Slic3r::GUI::MainFrame::FileHistory::SetMaxFiles (int max) inline
{
    m_fileMaxFiles  = max;
    size_t numFiles = m_fileHistory.size();
    while (numFiles > m_fileMaxFiles)
        RemoveFileFromHistory(--numFiles);
}
References max().
Member Data Documentation
m_load_called
bool Slic3r::GUI::MainFrame::FileHistory::m_load_called = false private
m_thumbnails
std::deque<std::string> Slic3r::GUI::MainFrame::FileHistory::m_thumbnails private
The documentation for this struct was generated from the following files:
src/slic3r/GUI/MainFrame.hpp
src/slic3r/GUI/MainFrame.cpp