OrcaSlicer: Slic3r::GUI::BindJob Class Reference
Slic3r::GUI::BindJob Class Reference
#include <src/slic3r/GUI/Jobs/BindJob.hpp>
Public Types
enum JobPrepareState { PREPARE_STATE_DEFAULT = 0 , PREPARE_STATE_MENU = 1 }
Public Member Functions
BindJob (std::shared_ptr< ProgressIndicator > pri, Plater *plater, std::string dev_id, std::string dev_ip, std::string sec_link)
int status_range () const override
bool is_finished ()
void on_success (std::function< void()> success)
void update_status (int st, const wxString &msg)
void process () override
void finalize () override
void set_event_handle (wxWindow *hanle)
void post_fail_event ()
bool is_finalized () const
void start ()
bool join (int timeout_ms=0)
bool is_running () const
void cancel ()
Protected Member Functions
void on_exception (const std::exception_ptr &) override
void update_percent_finish ()
void show_networking_test (wxString msg)
bool was_canceled () const
virtual void prepare ()
Protected Attributes
Plater * m_plater
bool only_on_partplate {false}
Private Member Functions
void run (std::exception_ptr &)
Private Attributes
wxWindow * m_event_handle {nullptr}
std::function< void()> m_success_fun {nullptr}
std::string m_dev_id
std::string m_dev_ip
std::string m_sec_link
bool m_job_finished { false }
int m_print_job_completed_id = 0
int m_range = 100
int m_thread_evt_id = wxID_ANY
boost::thread m_thread
std::atomic< bool > m_running {false}
std::atomic< bool > m_canceled {false}
bool m_finalized = false
bool m_finalizing = false
std::shared_ptr< ProgressIndicator > m_progress
std::exception_ptr m_worker_error = nullptr
Detailed Description
Member Enumeration Documentation
JobPrepareState
enum Slic3r::GUI::Job::JobPrepareState inherited
Enumerator
PREPARE_STATE_DEFAULT
PREPARE_STATE_MENU
{
        PREPARE_STATE_DEFAULT = 0,
        PREPARE_STATE_MENU = 1,
    };
Constructor & Destructor Documentation
BindJob()
Slic3r::GUI::BindJob::BindJob (std::shared_ptr< ProgressIndicator > pri, Plater * plater, std::string dev_id, std::string dev_ip, std::string sec_link)
    : PlaterJob{std::move(pri), plater},
    m_dev_id(dev_id),
    m_dev_ip(dev_ip),
    m_sec_link(sec_link)
{
    ;
}
Member Function Documentation
cancel()
void Slic3r::GUI::Job::cancel () inline inherited
{ m_canceled.store(true); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::UpgradeNetworkJob::process().
finalize()
void Slic3r::GUI::BindJob::finalize () override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (was_canceled()) return;
    Job::finalize();
}
References Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::was_canceled().
is_finalized()
bool Slic3r::GUI::Job::is_finalized () const inline inherited
{ return m_finalized; }
References Slic3r::GUI::Job::m_finalized.
is_finished()
bool Slic3r::GUI::BindJob::is_finished () inline
{ return m_job_finished;  }
References m_job_finished.
is_running()
bool Slic3r::GUI::Job::is_running () const inline inherited
{ return m_running.load(); }
References Slic3r::GUI::Job::m_running.
join()
bool Slic3r::GUI::Job::join (int timeout_ms = 0) inherited
{
    if (!m_thread.joinable()) return true;
    if (timeout_ms <= 0)
        m_thread.join();
    else if (!m_thread.try_join_for(boost::chrono::milliseconds(timeout_ms)))
        return false;
    return true;
}
on_exception()
void Slic3r::GUI::BindJob::on_exception (const std::exception_ptr & eptr) override protected virtual
Reimplemented from Slic3r::GUI::Job.
{
    try {
        if (eptr)
            std::rethrow_exception(eptr);
    } catch (std::exception &e) {
        PlaterJob::on_exception(eptr);
    }
}
References Slic3r::GUI::PlaterJob::on_exception().
on_success()
void Slic3r::GUI::BindJob::on_success (std::function< void()> success)
{
    m_success_fun = success;
}
References m_success_fun.
post_fail_event()
void Slic3r::GUI::BindJob::post_fail_event ()
{
    wxCommandEvent event(EVT_BIND_MACHINE_FAIL);
    event.SetEventObject(m_event_handle);
    wxPostEvent(m_event_handle, event);
}
References m_event_handle.
Referenced by process().
prepare()
virtual void Slic3r::GUI::Job::prepare () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ArrangeJob, Slic3r::GUI::FillBedJob, Slic3r::GUI::OrientJob, Slic3r::GUI::PrintJob, Slic3r::GUI::RotoptimizeJob, Slic3r::GUI::SendJob, and Slic3r::GUI::SLAImportJob.
{}
process()
void Slic3r::GUI::BindJob::process () override virtual
Implements Slic3r::GUI::Job.
{
    /* display info */
    wxString msg = waiting_auth_str;
    int curr_percent = 0;
    NetworkAgent* m_agent = wxGetApp().getAgent();
    if (!m_agent) { return; }
    // get timezone
    wxDateTime::TimeZone tz(wxDateTime::Local);
    long offset = tz.GetOffset();
    std::string timezone = get_timezone_utc_hm(offset);
    int result = m_agent->bind(m_dev_ip, m_dev_id, m_sec_link, timezone,
        [this, &curr_percent, &msg](int stage, int code, std::string info) {
            if (stage == BBL::BindJobStage::LoginStageConnect) {
                curr_percent = 15;
                msg = _L("Logging in");
            } else if (stage == BBL::BindJobStage::LoginStageLogin) {
                curr_percent = 30;
                msg = _L("Logging in");
            } else if (stage == BBL::BindJobStage::LoginStageWaitForLogin) {
                curr_percent = 45;
                msg = _L("Logging in");
            } else if (stage == BBL::BindJobStage::LoginStageGetIdentify) {
                curr_percent = 60;
                msg = _L("Logging in");
            } else if (stage == BBL::BindJobStage::LoginStageWaitAuth) {
                curr_percent = 80;
                msg = _L("Logging in");
            } else if (stage == BBL::BindJobStage::LoginStageFinished) {
                curr_percent = 100;
                msg = _L("Logging in");
            } else {
                msg = _L("Logging in");
            }
            if (code != 0) {
                msg = _L("Login failed") + wxString::Format("(code=%d,info=%s). ", code, info);
                if (code == BAMBU_NETWORK_ERR_TIMEOUT) {
                    msg += _L("Please check the printer network connection.");
                }
            }
            update_status(curr_percent, msg);
        }
    );
    if (result < 0) {
        BOOST_LOG_TRIVIAL(trace) << "login: result = " << result;
        post_fail_event();
        return;
    }
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) {
        BOOST_LOG_TRIVIAL(trace) << "login: dev is null";
        post_fail_event();
        return;
    }
    dev->update_user_machine_list_info();
    wxCommandEvent event(EVT_BIND_MACHINE_SUCCESS);
    event.SetEventObject(m_event_handle);
    wxPostEvent(m_event_handle, event);
    return;
}
References _L, BAMBU_NETWORK_ERR_TIMEOUT, Slic3r::NetworkAgent::bind(), Slic3r::get_timezone_utc_hm(), BBL::LoginStageConnect, BBL::LoginStageFinished, BBL::LoginStageGetIdentify, BBL::LoginStageLogin, BBL::LoginStageWaitAuth, BBL::LoginStageWaitForLogin, m_dev_id, m_dev_ip, m_event_handle, m_sec_link, Slic3r::offset(), post_fail_event(), Slic3r::trace(), update_status(), Slic3r::DeviceManager::update_user_machine_list_info(), and Slic3r::GUI::waiting_auth_str.
run()
void Slic3r::GUI::Job::run (std::exception_ptr & eptr) private inherited
{
    m_running.store(true);
    try {
        process();
    } catch (...) {
        eptr = std::current_exception();
    }
    m_running.store(false);
    // ensure to call the last status to finalize the job
    update_status(status_range(), "");
}
References Slic3r::GUI::Job::m_running, Slic3r::GUI::Job::process(), Slic3r::GUI::Job::status_range(), and Slic3r::GUI::Job::update_status().
set_event_handle()
void Slic3r::GUI::BindJob::set_event_handle (wxWindow * hanle)
{
    m_event_handle = hanle;
}
References m_event_handle.
show_networking_test()
void Slic3r::GUI::Job::show_networking_test (wxString msg) protected inherited
{
    m_progress->show_networking_test(msg);
}
Referenced by Slic3r::GUI::PrintJob::process().
start()
void Slic3r::GUI::Job::start () inherited
{ // Start the job. No effect if the job is already running
    if (!m_running.load()) {
        prepare();
        // Save the current status indicatior range and push the new one
        m_range = m_progress->get_range();
        m_progress->set_range(status_range());
        // init cancellation flag and set the cancel callback
        m_canceled.store(false);
        m_progress->set_cancel_callback(
                    [this]() { m_canceled.store(true); });
        m_finalized  = false;
        m_finalizing = false;
        // Changing cursor to busy
        wxBeginBusyCursor();
        try { // Execute the job
            m_worker_error = nullptr;
            m_thread = create_thread([this] { this->run(m_worker_error); });
        } catch (std::exception &) {
            update_status(status_range(),
                          _(L("Error! Unable to create thread!")));
        }
        // The state changes will be undone when the process hits the
        // last status value, in the status update handler (see ctor)
    }
}
References _, Slic3r::create_thread(), and L.
Referenced by Slic3r::GUI::OrientJob::process().
status_range()
int Slic3r::GUI::BindJob::status_range () const inline override virtual
Reimplemented from Slic3r::GUI::Job.
    {
        return 100;
    }
update_percent_finish()
void Slic3r::GUI::Job::update_percent_finish () protected inherited
{
    m_progress->clear_percent();
}
Referenced by Slic3r::GUI::PrintJob::process().
update_status()
void Slic3r::GUI::BindJob::update_status (int st, const wxString & msg)
{
    GUI::Job::update_status(st, msg);
    //post_event(wxCommandEvent(EVT_BIND_UPDATE_MESSAGE), msg);
    wxCommandEvent event(EVT_BIND_UPDATE_MESSAGE);
    event.SetString(msg);
    event.SetEventObject(m_event_handle);
    wxPostEvent(m_event_handle, event);
}
References m_event_handle, and Slic3r::GUI::Job::update_status().
Referenced by process().
was_canceled()
bool Slic3r::GUI::Job::was_canceled () const inline protected inherited
{ return m_canceled.load(); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::ArrangeJob::finalize(), finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::PrintJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SendJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::UpgradeNetworkJob::finalize(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), and Slic3r::GUI::UpgradeNetworkJob::process().
Member Data Documentation
m_canceled
std::atomic<bool> Slic3r::GUI::Job::m_canceled {false} private inherited
Referenced by Slic3r::GUI::Job::cancel(), and Slic3r::GUI::Job::was_canceled().
m_dev_id
std::string Slic3r::GUI::BindJob::m_dev_id private
Referenced by process().
m_dev_ip
std::string Slic3r::GUI::BindJob::m_dev_ip private
Referenced by process().
m_event_handle
wxWindow* Slic3r::GUI::BindJob::m_event_handle {nullptr} private
Referenced by post_fail_event(), process(), set_event_handle(), and update_status().
m_finalized
bool Slic3r::GUI::Job::m_finalized = false private inherited
Referenced by Slic3r::GUI::Job::Job(), Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::is_finalized().
m_finalizing
bool Slic3r::GUI::Job::m_finalizing = false private inherited
Referenced by Slic3r::GUI::Job::Job().
m_job_finished
bool Slic3r::GUI::BindJob::m_job_finished { false } private
Referenced by is_finished().
m_plater
Plater* Slic3r::GUI::PlaterJob::m_plater protected inherited
Referenced by Slic3r::GUI::ArrangeJob::check_unprintable(), Slic3r::GUI::ArrangeJob::clear_input(), Slic3r::GUI::OrientJob::clear_input(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::ArrangeJob::on_exception(), Slic3r::GUI::PlaterJob::on_exception(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::OrientJob::prepare(), Slic3r::GUI::PrintJob::prepare(), Slic3r::GUI::RotoptimizeJob::prepare(), Slic3r::GUI::SendJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), and Slic3r::GUI::SLAImportJob::reset().
m_print_job_completed_id
int Slic3r::GUI::BindJob::m_print_job_completed_id = 0 private
m_progress
std::shared_ptr<ProgressIndicator> Slic3r::GUI::Job::m_progress private inherited
Referenced by Slic3r::GUI::Job::Job().
m_range
int Slic3r::GUI::Job::m_range = 100 private inherited
Referenced by Slic3r::GUI::Job::Job().
m_running
std::atomic<bool> Slic3r::GUI::Job::m_running {false} private inherited
Referenced by Slic3r::GUI::Job::is_running(), and Slic3r::GUI::Job::run().
m_sec_link
std::string Slic3r::GUI::BindJob::m_sec_link private
Referenced by process().
m_success_fun
std::function<void()> Slic3r::GUI::BindJob::m_success_fun {nullptr} private
Referenced by on_success().
m_thread
boost::thread Slic3r::GUI::Job::m_thread private inherited
m_thread_evt_id
int Slic3r::GUI::Job::m_thread_evt_id = wxID_ANY private inherited
Referenced by Slic3r::GUI::Job::Job().
m_worker_error
std::exception_ptr Slic3r::GUI::Job::m_worker_error = nullptr private inherited
Referenced by Slic3r::GUI::Job::Job().
only_on_partplate
bool Slic3r::GUI::PlaterJob::only_on_partplate {false} protected inherited
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::OrientJob::prepare(), and Slic3r::GUI::ArrangeJob::prepare_wipe_tower().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/BindJob.hpp
src/slic3r/GUI/Jobs/BindJob.cpp