OrcaSlicer: Slic3r::GUI::PrintJob Class Reference
Slic3r::GUI::PrintJob Class Reference
#include <src/slic3r/GUI/Jobs/PrintJob.hpp>
Public Types
enum JobPrepareState { PREPARE_STATE_DEFAULT = 0 , PREPARE_STATE_MENU = 1 }
Public Member Functions
PrintJob (std::shared_ptr< ProgressIndicator > pri, Plater *plater, std::string dev_id="")
void set_print_config (std::string bed_type, bool bed_leveling, bool flow_cali, bool vabration_cali, bool record_timelapse, bool layer_inspect)
int status_range () const override
bool is_finished ()
void set_print_job_finished_event (int event_id)
void on_success (std::function< void()> success)
wxString get_http_error_msg (unsigned int status, std::string body)
void process () override
void finalize () override
void set_project_name (std::string name)
void on_check_ip_address_fail (std::function< void()> func)
void on_check_ip_address_success (std::function< void()> func)
bool is_finalized () const
void start ()
bool join (int timeout_ms=0)
bool is_running () const
void cancel ()
Public Attributes
std::string m_project_name
std::string m_dev_ip
std::string m_ftp_folder
bool m_local_use_ssl { true }
std::string m_access_code
std::string task_bed_type
bool task_bed_leveling
bool task_flow_cali
bool task_vibration_cali
bool task_record_timelapse
bool task_layer_inspect
std::string task_ams_mapping
std::string task_ams_mapping_info
std::string connection_type
bool cloud_print_only { false }
bool has_sdcard { false }
bool task_use_ams { true }
Protected Member Functions
void prepare () override
void on_exception (const std::exception_ptr &) override
void update_status (int st, const wxString &msg="")
void update_percent_finish ()
void show_networking_test (wxString msg)
bool was_canceled () const
Protected Attributes
Plater * m_plater
bool only_on_partplate {false}
Private Member Functions
void run (std::exception_ptr &)
Private Attributes
std::function< void()> m_success_fun {nullptr}
PrintPrepareData job_data
std::string m_dev_id
bool m_job_finished { false }
int m_print_job_completed_id = 0
std::function< void()> m_enter_ip_address_fun_fail { nullptr }
std::function< void()> m_enter_ip_address_fun_success { nullptr }
int m_range = 100
int m_thread_evt_id = wxID_ANY
boost::thread m_thread
std::atomic< bool > m_running {false}
std::atomic< bool > m_canceled {false}
bool m_finalized = false
bool m_finalizing = false
std::shared_ptr< ProgressIndicator > m_progress
std::exception_ptr m_worker_error = nullptr
Detailed Description
Member Enumeration Documentation
JobPrepareState
enum Slic3r::GUI::Job::JobPrepareState inherited
Enumerator
PREPARE_STATE_DEFAULT
PREPARE_STATE_MENU
{
        PREPARE_STATE_DEFAULT = 0,
        PREPARE_STATE_MENU = 1,
    };
Constructor & Destructor Documentation
PrintJob()
Slic3r::GUI::PrintJob::PrintJob (std::shared_ptr< ProgressIndicator > pri, Plater * plater, std::string dev_id = "")
: PlaterJob{ std::move(pri), plater },
    m_dev_id(dev_id)
{
    m_print_job_completed_id = plater->get_print_finished_event();
}
References Slic3r::GUI::Plater::get_print_finished_event(), m_print_job_completed_id, and Slic3r::GUI::plater().
Member Function Documentation
cancel()
void Slic3r::GUI::Job::cancel () inline inherited
{ m_canceled.store(true); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::UpgradeNetworkJob::process().
finalize()
void Slic3r::GUI::PrintJob::finalize () override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (was_canceled()) return;
    Job::finalize();
}
References Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::was_canceled().
get_http_error_msg()
wxString Slic3r::GUI::PrintJob::get_http_error_msg (unsigned int status, std::string body)
{
    try {
        int code = 0;
        std::string error;
        std::string message;
        wxString result;
        if (status >= 400 && status < 500)
            try {
            json j = json::parse(body);
            if (j.contains("code")) {
                if (!j["code"].is_null())
                    code = j["code"].get<int>();
            }
            if (j.contains("error")) {
                if (!j["error"].is_null())
                    error = j["error"].get<std::string>();
            }
            if (j.contains("message")) {
                if (!j["message"].is_null())
                    message = j["message"].get<std::string>();
            }
            switch (status) {
                ;
            }
        }
        catch (...) {
            ;
        }
        else if (status == 503) {
            return _L("Service Unavailable");
        }
        else {
            wxString unkown_text = _L("Unkown Error.");
            unkown_text += wxString::Format("status=%u, body=%s", status, body);
            BOOST_LOG_TRIVIAL(error) << "http_error: status=" << status << ", code=" << code << ", error=" << error;
            return unkown_text;
        }
        BOOST_LOG_TRIVIAL(error) << "http_error: status=" << status << ", code=" << code << ", error=" << error;
        result = wxString::Format("code=%u, error=%s", code, from_u8(error));
        return result;
    } catch(...) {
        ;
    }
    return wxEmptyString;
}
References _L, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), error, Slic3r::GUI::from_u8(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse().
Referenced by process().
is_finalized()
bool Slic3r::GUI::Job::is_finalized () const inline inherited
{ return m_finalized; }
References Slic3r::GUI::Job::m_finalized.
is_finished()
bool Slic3r::GUI::PrintJob::is_finished () inline
{ return m_job_finished;  }
References m_job_finished.
is_running()
bool Slic3r::GUI::Job::is_running () const inline inherited
{ return m_running.load(); }
References Slic3r::GUI::Job::m_running.
join()
bool Slic3r::GUI::Job::join (int timeout_ms = 0) inherited
{
    if (!m_thread.joinable()) return true;
    if (timeout_ms <= 0)
        m_thread.join();
    else if (!m_thread.try_join_for(boost::chrono::milliseconds(timeout_ms)))
        return false;
    return true;
}
on_check_ip_address_fail()
void Slic3r::GUI::PrintJob::on_check_ip_address_fail (std::function< void()> func)
{
    m_enter_ip_address_fun_fail = func;
}
References m_enter_ip_address_fun_fail.
on_check_ip_address_success()
void Slic3r::GUI::PrintJob::on_check_ip_address_success (std::function< void()> func)
{
    m_enter_ip_address_fun_success = func;
}
References m_enter_ip_address_fun_success.
on_exception()
void Slic3r::GUI::PrintJob::on_exception (const std::exception_ptr & eptr) override protected virtual
Reimplemented from Slic3r::GUI::PlaterJob.
{
    try {
        if (eptr)
            std::rethrow_exception(eptr);
    } catch (std::exception &e) {
        PlaterJob::on_exception(eptr);
    }
}
References Slic3r::GUI::PlaterJob::on_exception().
on_success()
void Slic3r::GUI::PrintJob::on_success (std::function< void()> success)
{
    m_success_fun = success;
}
References m_success_fun.
prepare()
void Slic3r::GUI::PrintJob::prepare () override protected virtual
Reimplemented from Slic3r::GUI::Job.
{
    m_plater->get_print_job_data(&job_data);
    if (&job_data) {
        std::string temp_file = Slic3r::resources_dir() + "/check_access_code.txt";
        auto check_access_code_path = temp_file.c_str();
        BOOST_LOG_TRIVIAL(trace) << "sned_job: check_access_code_path = " << check_access_code_path;
        job_data._temp_path = fs::path(check_access_code_path);
    }
}
References Slic3r::GUI::PrintPrepareData::_temp_path, Slic3r::GUI::Plater::get_print_job_data(), job_data, Slic3r::GUI::PlaterJob::m_plater, Slic3r::resources_dir(), and Slic3r::trace().
process()
void Slic3r::GUI::PrintJob::process () override virtual
Implements Slic3r::GUI::Job.
{
    /* display info */
    wxString msg;
    wxString error_str;
    int curr_percent = 10;
    NetworkAgent* m_agent = wxGetApp().getAgent();
    AppConfig* config = wxGetApp().app_config;
    if (this->connection_type == "lan") {
        msg = _L("Sending print job over LAN");
    }
    else {
        msg = _L("Sending print job through cloud service");
    }
    int result = -1;
    unsigned int http_code;
    std::string http_body;
    int total_plate_num = m_plater->get_partplate_list().get_plate_count();
    PartPlate* plate = m_plater->get_partplate_list().get_plate(job_data.plate_idx);
    if (plate == nullptr) {
        plate = m_plater->get_partplate_list().get_curr_plate();
        if (plate == nullptr)
        return;
    }
    /* check gcode is valid */
    if (!plate->is_valid_gcode_file()) {
        update_status(curr_percent, check_gcode_failed_str);
        return;
    }
    if (was_canceled()) {
        update_status(curr_percent, printjob_cancel_str);
        return;
    }
    // task name
    std::string project_name = wxGetApp().plater()->get_project_name().ToUTF8().data();
    int curr_plate_idx = 0;
    if (job_data.plate_idx >= 0)
        curr_plate_idx = job_data.plate_idx + 1;
    else if (job_data.plate_idx == PLATE_CURRENT_IDX)
        curr_plate_idx = m_plater->get_partplate_list().get_curr_plate_index() + 1;
    else if (job_data.plate_idx == PLATE_ALL_IDX)
        curr_plate_idx = m_plater->get_partplate_list().get_curr_plate_index() + 1;
    else
        curr_plate_idx = m_plater->get_partplate_list().get_curr_plate_index() + 1;
    PartPlate* curr_plate = m_plater->get_partplate_list().get_curr_plate();
    if (curr_plate) {
        this->task_bed_type = bed_type_to_gcode_string(curr_plate->get_bed_type(true));
    }
    BBL::PrintParams params;
    // local print access
    params.dev_ip = m_dev_ip;
    params.use_ssl  = m_local_use_ssl;
    params.username = "bblp";
    params.password = m_access_code;
    // check access code and ip address
    if (this->connection_type == "lan") {
        params.dev_id = m_dev_id;
        params.project_name = "verify_job";
        params.filename = job_data._temp_path.string();
        params.connection_type = this->connection_type;
        result = m_agent->start_send_gcode_to_sdcard(params, nullptr, nullptr);
        if (result != 0) {
            BOOST_LOG_TRIVIAL(error) << "access code is invalid";
            m_enter_ip_address_fun_fail();
            m_job_finished = true;
            return;
        }
    }
    params.dev_id = m_dev_id;
    params.ftp_folder = m_ftp_folder;
    //params.project_name = project_name;
    params.project_name = m_project_name;
    params.preset_name = wxGetApp().preset_bundle->prints.get_selected_preset_name();
    params.filename = job_data._3mf_path.string();
    params.config_filename = job_data._3mf_config_path.string();
    params.plate_index = curr_plate_idx;
    params.task_bed_leveling    = this->task_bed_leveling;
    params.task_flow_cali       = this->task_flow_cali;
    params.task_vibration_cali  = this->task_vibration_cali;
    params.task_layer_inspect   = this->task_layer_inspect;
    params.task_record_timelapse= this->task_record_timelapse;
    params.ams_mapping          = this->task_ams_mapping;
    params.ams_mapping_info     = this->task_ams_mapping_info;
    params.connection_type      = this->connection_type;
    params.task_use_ams         = this->task_use_ams;
    params.task_bed_type        = this->task_bed_type;
    if (wxGetApp().model().model_info && wxGetApp().model().model_info.get()) {
        ModelInfo* model_info = wxGetApp().model().model_info.get();
        auto origin_profile_id = model_info->metadata_items.find(BBL_DESIGNER_PROFILE_ID_TAG);
        if (origin_profile_id != model_info->metadata_items.end()) {
            try {
                params.origin_profile_id    = stoi(origin_profile_id->second.c_str());
            }
            catch(...) {}
        }
        auto origin_model_id = model_info->metadata_items.find(BBL_DESIGNER_MODEL_ID_TAG);
        if (origin_model_id != model_info->metadata_items.end()) {
            try {
                params.origin_model_id = origin_model_id->second;
            }
            catch(...) {}
        }
    }
    wxString error_text;
    wxString msg_text;
    const int StagePercentPoint[(int)PrintingStageFinished + 1] = {
        20,     // PrintingStageCreate
        30,     // PrintingStageUpload
        70,     // PrintingStageWaiting
        75,     // PrintingStageRecord
        97,     // PrintingStageSending
        100     // PrintingStageFinished
    };
    bool is_try_lan_mode = false;
    bool is_try_lan_mode_failed = false;
    auto update_fn = [this, &is_try_lan_mode, &is_try_lan_mode_failed, &msg, &error_str, &curr_percent, &error_text, StagePercentPoint](int stage, int code, std::string info) {
                        if (stage == BBL::SendingPrintJobStage::PrintingStageCreate && !is_try_lan_mode_failed) {
                            if (this->connection_type == "lan") {
                                msg = _L("Sending print job over LAN");
                            } else {
                                msg = _L("Sending print job through cloud service");
                            }
                        }
                        else if (stage == BBL::SendingPrintJobStage::PrintingStageUpload && !is_try_lan_mode_failed) {
                            if (code >= 0 && code <= 100 && !info.empty()) {
                                if (this->connection_type == "lan") {
                                    msg = _L("Sending print job over LAN");
                                } else {
                                    msg = _L("Sending print job through cloud service");
                                }
                                msg += wxString::Format("(%s)", info);
                            }
                        }
                        else if (stage == BBL::SendingPrintJobStage::PrintingStageWaiting) {
                            if (this->connection_type == "lan") {
                                msg = _L("Sending print job over LAN");
                            } else {
                                msg = _L("Sending print job through cloud service");
                            }
                        }
                        else  if (stage == BBL::SendingPrintJobStage::PrintingStageRecord && !is_try_lan_mode) {
                            msg = _L("Sending print configuration");
                        }
                        else if (stage == BBL::SendingPrintJobStage::PrintingStageSending && !is_try_lan_mode) {
                            if (this->connection_type == "lan") {
                                msg = _L("Sending print job over LAN");
                            } else {
                                msg = _L("Sending print job through cloud service");
                            }
                        }
                        else if (stage == BBL::SendingPrintJobStage::PrintingStageFinished) {
                            msg = wxString::Format(_L("Successfully sent. Will automatically jump to the device page in %ss"), info);
                            this->update_percent_finish();
                        } else {
                            if (this->connection_type == "lan") {
                                msg = _L("Sending print job over LAN");
                            } else {
                                msg = _L("Sending print job through cloud service");
                            }
                        }
                        // update current percnet
                        if (stage >= 0 && stage <= (int) PrintingStageFinished) {
                            curr_percent = StagePercentPoint[stage];
                            if ((stage == BBL::SendingPrintJobStage::PrintingStageUpload
                                || stage == BBL::SendingPrintJobStage::PrintingStageRecord)
                                && (code > 0 && code <= 100)) {
                                curr_percent = (StagePercentPoint[stage + 1] - StagePercentPoint[stage]) * code / 100 + StagePercentPoint[stage];
                            }
                        }
                        if (code > 100 || code < 0) {
                            error_text = this->get_http_error_msg(code, info);
                            error_str = wxString::Format("[%s]", error_text);
                        } else {
                            error_str = wxEmptyString;
                        }
                        this->update_status(curr_percent, msg + error_str);
                    };
    auto cancel_fn = [this]() {
            return was_canceled();
        };
    if (params.connection_type != "lan") {
        if (params.dev_ip.empty())
            params.comments = "no_ip";
        else if (this->cloud_print_only)
            params.comments = "low_version";
        else if (!this->has_sdcard)
            params.comments = "no_sdcard";
        else if (params.password.empty())
            params.comments = "no_password";
        //use ftp only
        if (!wxGetApp().app_config->get("lan_mode_only").empty() && wxGetApp().app_config->get("lan_mode_only") == "1") {
            if (params.password.empty() || params.dev_ip.empty()) {
                error_text = wxString::Format("Access code:%s Ip address:%s", params.password, params.dev_ip);
                result = BAMBU_NETWORK_ERR_FTP_UPLOAD_FAILED;
            }
            else {
                BOOST_LOG_TRIVIAL(info) << "print_job: use ftp send print only";
                this->update_status(curr_percent, _L("Sending print job over LAN"));
                is_try_lan_mode = true;
                result = m_agent->start_local_print_with_record(params, update_fn, cancel_fn);
                if (result < 0) {
                    error_text = wxString::Format("Access code:%s Ip address:%s", params.password, params.dev_ip);
                    // try to send with cloud
                    BOOST_LOG_TRIVIAL(warning) << "print_job: use ftp send print failed";
                }
            }
        }
        else {
            if (!this->cloud_print_only
                && !params.password.empty()
                && !params.dev_ip.empty()
                && this->has_sdcard) {
                // try to send local with record
                BOOST_LOG_TRIVIAL(info) << "print_job: try to start local print with record";
                this->update_status(curr_percent, _L("Sending print job over LAN"));
                result = m_agent->start_local_print_with_record(params, update_fn, cancel_fn);
                if (result == 0) {
                    params.comments = "";
                }
                else if (result == BAMBU_NETWORK_ERR_FTP_LOGIN_DENIED) {
                    params.comments = "wrong_code";
                }
                else if (result == BAMBU_NETWORK_ERR_FTP_UPLOAD_FAILED) {
                    params.comments = "upload_failed";
                }
                else {
                    params.comments = (boost::format("failed(%1%)") % result).str();
                }
                if (result < 0) {
                    is_try_lan_mode_failed = true;
                    // try to send with cloud
                    BOOST_LOG_TRIVIAL(warning) << "print_job: try to send with cloud";
                    this->update_status(curr_percent, _L("Sending print job through cloud service"));
                    result = m_agent->start_print(params, update_fn, cancel_fn);
                }
            }
            else {
                BOOST_LOG_TRIVIAL(info) << "print_job: send with cloud";
                this->update_status(curr_percent, _L("Sending print job through cloud service"));
                result = m_agent->start_print(params, update_fn, cancel_fn);
            }
        }
    } else {
        if (this->has_sdcard) {
            this->update_status(curr_percent, _L("Sending print job over LAN"));
            result = m_agent->start_local_print(params, update_fn, cancel_fn);
        } else {
            this->update_status(curr_percent, _L("An SD card needs to be inserted before printing via LAN."));
            return;
        }
    }
    if (result < 0) {
        if (result == BAMBU_NETWORK_ERR_FTP_LOGIN_DENIED) {
            msg_text = _L("Failed to send the print job. Please try again.");
        } if (result == BAMBU_NETWORK_ERR_FILE_NOT_EXIST) {
            msg_text = file_is_not_exists_str;
        } else if (result == BAMBU_NETWORK_ERR_FILE_OVER_SIZE) {
            msg_text = file_over_size_str;
        } else if (result == BAMBU_NETWORK_ERR_CHECK_MD5_FAILED) {
            msg_text = failed_in_cloud_service_str;
        } else if (result == BAMBU_NETWORK_ERR_INVALID_PARAMS) {
            msg_text = _L("Failed to send the print job. Please try again.");
        } else if (result == BAMBU_NETWORK_ERR_CANCELED) {
            msg_text = print_canceled_str;
        } else if (result == BAMBU_NETWORK_ERR_TIMEOUT) {
            msg_text = timeout_to_upload_str;
        } else if (result == BAMBU_NETWORK_ERR_INVALID_RESULT) {
            msg_text = _L("Failed to send the print job. Please try again.");
        } else if (result == BAMBU_NETWORK_ERR_FTP_UPLOAD_FAILED) {
            msg_text = _L("Failed to send the print job. Please try again.");
        } else {
            update_status(curr_percent, failed_in_cloud_service_str);
        }
        if (!error_text.IsEmpty()) {
            curr_percent = 0;
            msg_text += wxString::Format("[%d][%s]", result, error_text);
        }
        if (result == BAMBU_NETWORK_ERR_INVALID_RESULT) {
            this->show_networking_test(msg_text);
        }
        else {
            update_status(curr_percent, msg_text);
        }
        BOOST_LOG_TRIVIAL(error) << "print_job: failed, result = " << result;
    } else {
        BOOST_LOG_TRIVIAL(error) << "print_job: send ok.";
        wxCommandEvent* evt = new wxCommandEvent(m_print_job_completed_id);
        evt->SetString(m_dev_id);
        wxQueueEvent(m_plater, evt);
        m_job_finished = true;
    }
}
References Slic3r::GUI::PrintPrepareData::_3mf_config_path, Slic3r::GUI::PrintPrepareData::_3mf_path, _L, Slic3r::GUI::PrintPrepareData::_temp_path, BBL::PrintParams::ams_mapping, BBL::PrintParams::ams_mapping_info, BAMBU_NETWORK_ERR_CANCELED, BAMBU_NETWORK_ERR_CHECK_MD5_FAILED, BAMBU_NETWORK_ERR_FILE_NOT_EXIST, BAMBU_NETWORK_ERR_FILE_OVER_SIZE, BAMBU_NETWORK_ERR_FTP_LOGIN_DENIED, BAMBU_NETWORK_ERR_FTP_UPLOAD_FAILED, BAMBU_NETWORK_ERR_INVALID_PARAMS, BAMBU_NETWORK_ERR_INVALID_RESULT, BAMBU_NETWORK_ERR_TIMEOUT, BBL_DESIGNER_MODEL_ID_TAG, BBL_DESIGNER_PROFILE_ID_TAG, Slic3r::bed_type_to_gcode_string(), Slic3r::GUI::check_gcode_failed_str, cloud_print_only, BBL::PrintParams::comments, BBL::PrintParams::config_filename, connection_type, BBL::PrintParams::connection_type, BBL::PrintParams::dev_id, BBL::PrintParams::dev_ip, error, Slic3r::GUI::failed_in_cloud_service_str, Slic3r::GUI::file_is_not_exists_str, Slic3r::GUI::file_over_size_str, BBL::PrintParams::filename, BBL::PrintParams::ftp_folder, Slic3r::GUI::PartPlate::get_bed_type(), Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::PartPlateList::get_curr_plate_index(), get_http_error_msg(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::PartPlateList::get_plate(), Slic3r::GUI::PartPlateList::get_plate_count(), has_sdcard, int, Slic3r::GUI::PartPlate::is_valid_gcode_file(), job_data, m_access_code, m_dev_id, m_dev_ip, m_enter_ip_address_fun_fail, m_ftp_folder, m_job_finished, m_local_use_ssl, Slic3r::GUI::PlaterJob::m_plater, m_print_job_completed_id, m_project_name, Slic3r::ModelInfo::metadata_items, BBL::PrintParams::origin_model_id, BBL::PrintParams::origin_profile_id, BBL::PrintParams::password, PLATE_ALL_IDX, PLATE_CURRENT_IDX, Slic3r::GUI::PrintPrepareData::plate_idx, BBL::PrintParams::plate_index, BBL::PrintParams::preset_name, Slic3r::GUI::print_canceled_str, BBL::PrintingStageCreate, BBL::PrintingStageFinished, BBL::PrintingStageRecord, BBL::PrintingStageSending, BBL::PrintingStageUpload, BBL::PrintingStageWaiting, Slic3r::GUI::printjob_cancel_str, BBL::PrintParams::project_name, Slic3r::GUI::Job::show_networking_test(), Slic3r::NetworkAgent::start_local_print(), Slic3r::NetworkAgent::start_local_print_with_record(), Slic3r::NetworkAgent::start_print(), Slic3r::NetworkAgent::start_send_gcode_to_sdcard(), task_ams_mapping, task_ams_mapping_info, task_bed_leveling, BBL::PrintParams::task_bed_leveling, task_bed_type, BBL::PrintParams::task_bed_type, task_flow_cali, BBL::PrintParams::task_flow_cali, task_layer_inspect, BBL::PrintParams::task_layer_inspect, task_record_timelapse, BBL::PrintParams::task_record_timelapse, task_use_ams, BBL::PrintParams::task_use_ams, task_vibration_cali, BBL::PrintParams::task_vibration_cali, Slic3r::GUI::timeout_to_upload_str, Slic3r::GUI::Job::update_percent_finish(), Slic3r::GUI::Job::update_status(), BBL::PrintParams::use_ssl, BBL::PrintParams::username, and Slic3r::GUI::Job::was_canceled().
run()
void Slic3r::GUI::Job::run (std::exception_ptr & eptr) private inherited
{
    m_running.store(true);
    try {
        process();
    } catch (...) {
        eptr = std::current_exception();
    }
    m_running.store(false);
    // ensure to call the last status to finalize the job
    update_status(status_range(), "");
}
References Slic3r::GUI::Job::m_running, Slic3r::GUI::Job::process(), Slic3r::GUI::Job::status_range(), and Slic3r::GUI::Job::update_status().
set_print_config()
void Slic3r::GUI::PrintJob::set_print_config (std::string bed_type, bool bed_leveling, bool flow_cali, bool vabration_cali, bool record_timelapse, bool layer_inspect) inline
    {
        task_bed_type       = bed_type;
        task_bed_leveling   = bed_leveling;
        task_flow_cali      = flow_cali;
        task_vibration_cali = vabration_cali;
        task_record_timelapse = record_timelapse;
        task_layer_inspect    = layer_inspect;
    }
References task_bed_leveling, task_bed_type, task_flow_cali, task_layer_inspect, task_record_timelapse, and task_vibration_cali.
set_print_job_finished_event()
void Slic3r::GUI::PrintJob::set_print_job_finished_event (int event_id) inline
{ m_print_job_completed_id = event_id; }
References m_print_job_completed_id.
set_project_name()
void Slic3r::GUI::PrintJob::set_project_name (std::string name)
{
    m_project_name = name;
}
References m_project_name.
show_networking_test()
void Slic3r::GUI::Job::show_networking_test (wxString msg) protected inherited
{
    m_progress->show_networking_test(msg);
}
Referenced by process().
start()
void Slic3r::GUI::Job::start () inherited
{ // Start the job. No effect if the job is already running
    if (!m_running.load()) {
        prepare();
        // Save the current status indicatior range and push the new one
        m_range = m_progress->get_range();
        m_progress->set_range(status_range());
        // init cancellation flag and set the cancel callback
        m_canceled.store(false);
        m_progress->set_cancel_callback(
                    [this]() { m_canceled.store(true); });
        m_finalized  = false;
        m_finalizing = false;
        // Changing cursor to busy
        wxBeginBusyCursor();
        try { // Execute the job
            m_worker_error = nullptr;
            m_thread = create_thread([this] { this->run(m_worker_error); });
        } catch (std::exception &) {
            update_status(status_range(),
                          _(L("Error! Unable to create thread!")));
        }
        // The state changes will be undone when the process hits the
        // last status value, in the status update handler (see ctor)
    }
}
References _, Slic3r::create_thread(), and L.
Referenced by Slic3r::GUI::OrientJob::process().
status_range()
int Slic3r::GUI::PrintJob::status_range () const inline override virtual
Reimplemented from Slic3r::GUI::Job.
    {
        return 100;
    }
update_percent_finish()
void Slic3r::GUI::Job::update_percent_finish () protected inherited
{
    m_progress->clear_percent();
}
Referenced by process().
update_status()
void Slic3r::GUI::Job::update_status (int st, const wxString & msg = "") protected inherited
{
    auto evt = new wxThreadEvent(wxEVT_THREAD, m_thread_evt_id);
    evt->SetInt(st);
    evt->SetString(msg);
    wxQueueEvent(this, evt);
}
Referenced by Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), Slic3r::GUI::Job::run(), Slic3r::GUI::BindJob::update_status(), and Slic3r::GUI::UpgradeNetworkJob::update_status().
was_canceled()
bool Slic3r::GUI::Job::was_canceled () const inline protected inherited
{ return m_canceled.load(); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::BindJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SendJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::UpgradeNetworkJob::finalize(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), and Slic3r::GUI::UpgradeNetworkJob::process().
Member Data Documentation
cloud_print_only
bool Slic3r::GUI::PrintJob::cloud_print_only { false }
Referenced by process().
connection_type
std::string Slic3r::GUI::PrintJob::connection_type
Referenced by process().
has_sdcard
bool Slic3r::GUI::PrintJob::has_sdcard { false }
Referenced by process().
job_data
PrintPrepareData Slic3r::GUI::PrintJob::job_data private
Referenced by prepare(), and process().
m_access_code
std::string Slic3r::GUI::PrintJob::m_access_code
Referenced by process().
m_canceled
std::atomic<bool> Slic3r::GUI::Job::m_canceled {false} private inherited
Referenced by Slic3r::GUI::Job::cancel(), and Slic3r::GUI::Job::was_canceled().
m_dev_id
std::string Slic3r::GUI::PrintJob::m_dev_id private
Referenced by process().
m_dev_ip
std::string Slic3r::GUI::PrintJob::m_dev_ip
Referenced by process().
m_enter_ip_address_fun_fail
std::function<void()> Slic3r::GUI::PrintJob::m_enter_ip_address_fun_fail { nullptr } private
Referenced by on_check_ip_address_fail(), and process().
m_enter_ip_address_fun_success
std::function<void()> Slic3r::GUI::PrintJob::m_enter_ip_address_fun_success { nullptr } private
Referenced by on_check_ip_address_success().
m_finalized
bool Slic3r::GUI::Job::m_finalized = false private inherited
Referenced by Slic3r::GUI::Job::Job(), Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::is_finalized().
m_finalizing
bool Slic3r::GUI::Job::m_finalizing = false private inherited
Referenced by Slic3r::GUI::Job::Job().
m_ftp_folder
std::string Slic3r::GUI::PrintJob::m_ftp_folder
Referenced by process().
m_job_finished
bool Slic3r::GUI::PrintJob::m_job_finished { false } private
Referenced by is_finished(), and process().
m_local_use_ssl
bool Slic3r::GUI::PrintJob::m_local_use_ssl { true }
Referenced by process().
m_plater
Plater* Slic3r::GUI::PlaterJob::m_plater protected inherited
Referenced by Slic3r::GUI::ArrangeJob::check_unprintable(), Slic3r::GUI::ArrangeJob::clear_input(), Slic3r::GUI::OrientJob::clear_input(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::ArrangeJob::on_exception(), Slic3r::GUI::PlaterJob::on_exception(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::OrientJob::prepare(), prepare(), Slic3r::GUI::RotoptimizeJob::prepare(), Slic3r::GUI::SendJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), and Slic3r::GUI::SLAImportJob::reset().
m_print_job_completed_id
int Slic3r::GUI::PrintJob::m_print_job_completed_id = 0 private
Referenced by PrintJob(), process(), and set_print_job_finished_event().
m_progress
std::shared_ptr<ProgressIndicator> Slic3r::GUI::Job::m_progress private inherited
Referenced by Slic3r::GUI::Job::Job().
m_project_name
std::string Slic3r::GUI::PrintJob::m_project_name
Referenced by process(), and set_project_name().
m_range
int Slic3r::GUI::Job::m_range = 100 private inherited
Referenced by Slic3r::GUI::Job::Job().
m_running
std::atomic<bool> Slic3r::GUI::Job::m_running {false} private inherited
Referenced by Slic3r::GUI::Job::is_running(), and Slic3r::GUI::Job::run().
m_success_fun
std::function<void()> Slic3r::GUI::PrintJob::m_success_fun {nullptr} private
Referenced by on_success().
m_thread
boost::thread Slic3r::GUI::Job::m_thread private inherited
m_thread_evt_id
int Slic3r::GUI::Job::m_thread_evt_id = wxID_ANY private inherited
Referenced by Slic3r::GUI::Job::Job().
m_worker_error
std::exception_ptr Slic3r::GUI::Job::m_worker_error = nullptr private inherited
Referenced by Slic3r::GUI::Job::Job().
only_on_partplate
bool Slic3r::GUI::PlaterJob::only_on_partplate {false} protected inherited
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::OrientJob::prepare(), and Slic3r::GUI::ArrangeJob::prepare_wipe_tower().
task_ams_mapping
std::string Slic3r::GUI::PrintJob::task_ams_mapping
Referenced by process().
task_ams_mapping_info
std::string Slic3r::GUI::PrintJob::task_ams_mapping_info
Referenced by process().
task_bed_leveling
bool Slic3r::GUI::PrintJob::task_bed_leveling
Referenced by process(), and set_print_config().
task_bed_type
std::string Slic3r::GUI::PrintJob::task_bed_type
Referenced by process(), and set_print_config().
task_flow_cali
bool Slic3r::GUI::PrintJob::task_flow_cali
Referenced by process(), and set_print_config().
task_layer_inspect
bool Slic3r::GUI::PrintJob::task_layer_inspect
Referenced by process(), and set_print_config().
task_record_timelapse
bool Slic3r::GUI::PrintJob::task_record_timelapse
Referenced by process(), and set_print_config().
task_use_ams
bool Slic3r::GUI::PrintJob::task_use_ams { true }
Referenced by process().
task_vibration_cali
bool Slic3r::GUI::PrintJob::task_vibration_cali
Referenced by process(), and set_print_config().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/PrintJob.hpp
src/slic3r/GUI/Jobs/PrintJob.cpp