OrcaSlicer: Slic3r::TreeSupportData Class Reference
Slic3r::TreeSupportData Class Reference
Lazily generates tree guidance volumes.
#include <src/libslic3r/TreeSupport.hpp>
Classes
struct RadiusLayerPair
Convenience typedef for the keys to the caches.
struct RadiusLayerPairEquality
struct RadiusLayerPairHash
Public Member Functions
TreeSupportData ()=default
TreeSupportData (const PrintObject &object, coordf_t max_move, coordf_t radius_sample_resolution, coordf_t collision_resolution)
Construct the TreeSupportData object.
TreeSupportData (TreeSupportData &&)=default
TreeSupportData & operator= (TreeSupportData &&)=default
TreeSupportData (const TreeSupportData &)=delete
TreeSupportData & operator= (const TreeSupportData &)=delete
const ExPolygons & get_collision (coordf_t radius, size_t layer_idx) const
Creates the areas that have to be avoided by the tree's branches.
const ExPolygons & get_avoidance (coordf_t radius, size_t layer_idx, int recursions=0) const
Creates the areas that have to be avoided by the tree's branches in order to reach the build plate.
Polygons get_contours (size_t layer_nr) const
Polygons get_contours_with_holes (size_t layer_nr) const
Public Attributes
std::vector< LayerHeightData > layer_heights
std::vector< TreeNode > tree_nodes
bool is_slim = false
coordf_t m_xy_distance
The required clearance between the model and the tree branches.
coordf_t m_max_move
The maximum distance that the centrepoint of a tree branch may move in consequtive layers.
coordf_t m_radius_sample_resolution
Sample resolution for radius values.
std::vector< ExPolygons > m_layer_outlines
Storage for layer outlines of the meshes.
std::vector< ExPolygons > m_layer_outlines_below
tbb::concurrent_unordered_map< RadiusLayerPair, ExPolygons, RadiusLayerPairHash, RadiusLayerPairEquality > m_collision_cache
Caches for the collision, avoidance and internal model polygons at given radius and layer indices.
tbb::concurrent_unordered_map< RadiusLayerPair, ExPolygons, RadiusLayerPairHash, RadiusLayerPairEquality > m_avoidance_cache
friend TreeSupport
Private Member Functions
coordf_t ceil_radius (coordf_t radius) const
Round radius upwards to a multiple of m_radius_sample_resolution.
const ExPolygons & calculate_collision (const RadiusLayerPair &key) const
Calculate the collision areas at the radius and layer indicated by key.
const ExPolygons & calculate_avoidance (const RadiusLayerPair &key) const
Calculate the avoidance areas at the radius and layer indicated by key.
Detailed Description
Lazily generates tree guidance volumes.
Warning
This class is not currently thread-safe and should not be accessed in OpenMP blocks
Class Documentation
Slic3r::TreeSupportData::RadiusLayerPair
struct Slic3r::TreeSupportData::RadiusLayerPair
Convenience typedef for the keys to the caches.
Class Members
size_t layer_nr
coordf_t radius
int recursions
Constructor & Destructor Documentation
TreeSupportData() [1/4]
Slic3r::TreeSupportData::TreeSupportData () default
TreeSupportData() [2/4]
Slic3r::TreeSupportData::TreeSupportData (const PrintObject & object, coordf_t max_move, coordf_t radius_sample_resolution, coordf_t collision_resolution)
Construct the TreeSupportData object.
Parameters
xy_distance The required clearance between the model and the tree branches.
max_move The maximum allowable movement between nodes on adjacent layers
radius_sample_resolution Sample size used to round requested node radii.
collision_resolution
    : m_xy_distance(xy_distance), m_max_move(max_move), m_radius_sample_resolution(radius_sample_resolution)
{
    for (std::size_t layer_nr  = 0; layer_nr < object.layers().size(); ++layer_nr)
    {
        const Layer* layer = object.get_layer(layer_nr);
        m_layer_outlines.push_back(ExPolygons());
        ExPolygons& outline = m_layer_outlines.back();
        for (const ExPolygon& poly : layer->lslices) {
            poly.simplify(scale_(m_radius_sample_resolution), &outline);
        }
        if (layer_nr == 0)
            m_layer_outlines_below.push_back(outline);
        else
            m_layer_outlines_below.push_back(union_ex(m_layer_outlines_below.end()[-1], outline));
    }
}
References Slic3r::Layer::lslices, m_layer_outlines, m_layer_outlines_below, m_radius_sample_resolution, scale_, size, and Slic3r::union_ex().
TreeSupportData() [3/4]
Slic3r::TreeSupportData::TreeSupportData (TreeSupportData &&) default
TreeSupportData() [4/4]
Slic3r::TreeSupportData::TreeSupportData (const TreeSupportData &) delete
Member Function Documentation
calculate_avoidance()
const ExPolygons & Slic3r::TreeSupportData::calculate_avoidance (const RadiusLayerPair & key) const private
Calculate the avoidance areas at the radius and layer indicated by key.
Parameters
key The radius and layer of the node of interest
{
    const auto& radius = key.radius;
    const auto& layer_nr = key.layer_nr;
    BOOST_LOG_TRIVIAL(debug) << "calculate_avoidance on radius=" << radius << ", layer=" << layer_nr<<", recursion="<<key.recursions;
    constexpr auto max_recursion_depth = 100;
    if (key.recursions <= max_recursion_depth*2) {
        if (layer_nr == 0) {
            m_avoidance_cache[key] = get_collision(radius, 0);
            return m_avoidance_cache[key];
        }
        // Avoidance for a given layer depends on all layers beneath it so could have very deep recursion depths if
        // called at high layer heights. We can limit the reqursion depth to N by checking if the layer N
        // below the current one exists and if not, forcing the calculation of that layer. This may cause another recursion
        // if the layer at 2N below the current one but we won't exceed our limit unless there are N*N uncalculated layers
        // below our current one.
        size_t         layer_nr_next       = layer_nr;
        int            layers_below;
        for (layers_below = 0; layers_below < max_recursion_depth && layer_nr_next > 0; layers_below++) { layer_nr_next = layer_heights[layer_nr_next].next_layer_nr; }
        // Check if we would exceed the recursion limit by trying to process this layer
        if (layers_below >= max_recursion_depth && m_avoidance_cache.find({radius, layer_nr_next}) == m_avoidance_cache.end()) {
            // Force the calculation of the layer `max_recursion_depth` below our current one, ignoring the result.
            get_avoidance(radius, layer_nr_next, key.recursions + 1);
        }
        layer_nr_next   = layer_heights[layer_nr].next_layer_nr;
        ExPolygons        avoidance_areas = std::move(offset_ex(get_avoidance(radius, layer_nr_next, key.recursions+1), scale_(-m_max_move)));
        const ExPolygons &collision       = get_collision(radius, layer_nr);
        avoidance_areas.insert(avoidance_areas.end(), collision.begin(), collision.end());
        avoidance_areas = std::move(union_ex(avoidance_areas));
        auto ret = m_avoidance_cache.insert({ key, std::move(avoidance_areas) });
        //assert(ret.second);
        return ret.first->second;
    } else {
        ExPolygons avoidance_areas = std::move(offset_ex(m_layer_outlines_below[layer_nr], scale_(m_xy_distance + radius)));
        auto ret = m_avoidance_cache.insert({ key, std::move(avoidance_areas) });
        assert(ret.second);
        return ret.first->second;
    }
}
References get_avoidance(), get_collision(), layer_heights, m_avoidance_cache, m_layer_outlines_below, m_max_move, m_xy_distance, Slic3r::offset_ex(), scale_, and Slic3r::union_ex().
Referenced by get_avoidance().
calculate_collision()
const ExPolygons & Slic3r::TreeSupportData::calculate_collision (const RadiusLayerPair & key) const private
Calculate the collision areas at the radius and layer indicated by key.
Parameters
key The radius and layer of the node of interest
{
    assert(key.layer_nr < m_layer_outlines.size());
    ExPolygons collision_areas = std::move(offset_ex(m_layer_outlines[key.layer_nr], scale_(key.radius)));
    const auto ret = m_collision_cache.insert({ key, std::move(collision_areas) });
    return ret.first->second;
}
References m_collision_cache, m_layer_outlines, Slic3r::offset_ex(), and scale_.
Referenced by get_collision().
ceil_radius()
coordf_t Slic3r::TreeSupportData::ceil_radius (coordf_t radius) const private
Round radius upwards to a multiple of m_radius_sample_resolution.
Parameters
radius The radius of the node of interest
{
#if 1
    size_t factor = (size_t)(radius / m_radius_sample_resolution);
    coordf_t remains = radius - m_radius_sample_resolution * factor;
    if (remains > EPSILON) {
        return radius + m_radius_sample_resolution - remains;
    }
    else {
        return radius;
    }
#else
    coordf_t resolution = m_radius_sample_resolution;
    return ceil(radius / resolution) * resolution;
#endif
}
References ceil(), EPSILON, and m_radius_sample_resolution.
Referenced by get_avoidance(), and get_collision().
get_avoidance()
const ExPolygons & Slic3r::TreeSupportData::get_avoidance (coordf_t radius, size_t layer_idx, int recursions = 0) const
Creates the areas that have to be avoided by the tree's branches in order to reach the build plate.
The result is a 2D area that would cause nodes of radius radius to collide with the model or be unable to reach the build platform.
The input collision areas are inset by the maximum move distance and propagated upwards.
Parameters
radius The radius of the node of interest
layer The layer of interest
Returns
Polygons object
{
    profiler.tic();
    radius = ceil_radius(radius);
    RadiusLayerPair key{radius, layer_nr, recursions };
    const auto it = m_avoidance_cache.find(key);
    const ExPolygons& avoidance = it != m_avoidance_cache.end() ? it->second : calculate_avoidance(key);
    profiler.stage_add(STAGE_GET_AVOIDANCE, true);
    return avoidance;
}
References calculate_avoidance(), ceil_radius(), m_avoidance_cache, Slic3r::profiler, Slic3r::TreeSupportProfiler::stage_add(), Slic3r::STAGE_GET_AVOIDANCE, and Slic3r::TreeSupportProfiler::tic().
Referenced by calculate_avoidance().
get_collision()
const ExPolygons & Slic3r::TreeSupportData::get_collision (coordf_t radius, size_t layer_idx) const
Creates the areas that have to be avoided by the tree's branches.
The result is a 2D area that would cause nodes of radius radius to collide with the model.
Parameters
radius The radius of the node of interest
layer The layer of interest
Returns
Polygons object
{
    profiler.tic();
    radius = ceil_radius(radius);
    RadiusLayerPair key{radius, layer_nr};
    const auto it = m_collision_cache.find(key);
    const ExPolygons& collision = it != m_collision_cache.end() ? it->second : calculate_collision(key);
    profiler.stage_add(STAGE_get_collision, true);
    return collision;
}
References calculate_collision(), ceil_radius(), m_collision_cache, Slic3r::profiler, Slic3r::TreeSupportProfiler::stage_add(), Slic3r::STAGE_get_collision, and Slic3r::TreeSupportProfiler::tic().
Referenced by calculate_avoidance().
get_contours()
Polygons Slic3r::TreeSupportData::get_contours (size_t layer_nr) const
{
    Polygons contours;
    for (const ExPolygon expoly : m_layer_outlines[layer_nr]) {
        contours.push_back(expoly.contour);
    }
    return contours;
}
References m_layer_outlines.
get_contours_with_holes()
Polygons Slic3r::TreeSupportData::get_contours_with_holes (size_t layer_nr) const
{
    Polygons contours;
    for (const ExPolygon expoly : m_layer_outlines[layer_nr]) {
        for(int i=0;i<expoly.num_contours();i++)
            contours.push_back(expoly.contour_or_hole(i));
    }
    return contours;
}
References m_layer_outlines.
operator=() [1/2]
TreeSupportData & Slic3r::TreeSupportData::operator= (const TreeSupportData &) delete
operator=() [2/2]
TreeSupportData & Slic3r::TreeSupportData::operator= (TreeSupportData &&) default
Member Data Documentation
is_slim
bool Slic3r::TreeSupportData::is_slim = false
layer_heights
std::vector<LayerHeightData> Slic3r::TreeSupportData::layer_heights
Referenced by calculate_avoidance().
m_avoidance_cache
tbb::concurrent_unordered_map<RadiusLayerPair, ExPolygons, RadiusLayerPairHash, RadiusLayerPairEquality> Slic3r::TreeSupportData::m_avoidance_cache mutable
Referenced by calculate_avoidance(), and get_avoidance().
m_collision_cache
tbb::concurrent_unordered_map<RadiusLayerPair, ExPolygons, RadiusLayerPairHash, RadiusLayerPairEquality> Slic3r::TreeSupportData::m_collision_cache mutable
Caches for the collision, avoidance and internal model polygons at given radius and layer indices.
These are mutable to allow modification from const function. This is generally considered OK as the functions are still logically const (ie there is no difference in behaviour for the user betweeen calculating the values each time vs caching the results).
coconut: previously stl::unordered_map is used which seems problematic with tbb::parallel_for. So we change to tbb::concurrent_unordered_map
Referenced by calculate_collision(), and get_collision().
m_layer_outlines
std::vector<ExPolygons> Slic3r::TreeSupportData::m_layer_outlines
Storage for layer outlines of the meshes.
Referenced by TreeSupportData(), calculate_collision(), get_contours(), and get_contours_with_holes().
m_layer_outlines_below
std::vector<ExPolygons> Slic3r::TreeSupportData::m_layer_outlines_below
Referenced by TreeSupportData(), and calculate_avoidance().
m_max_move
coordf_t Slic3r::TreeSupportData::m_max_move
The maximum distance that the centrepoint of a tree branch may move in consequtive layers.
Referenced by calculate_avoidance().
m_radius_sample_resolution
coordf_t Slic3r::TreeSupportData::m_radius_sample_resolution
Sample resolution for radius values.
The radius will be rounded (upwards) to multiples of this value before calculations are done when collision, avoidance and internal model Polygons are requested.
Referenced by TreeSupportData(), and ceil_radius().
m_xy_distance
coordf_t Slic3r::TreeSupportData::m_xy_distance
The required clearance between the model and the tree branches.
Referenced by calculate_avoidance().
tree_nodes
std::vector<TreeNode> Slic3r::TreeSupportData::tree_nodes
TreeSupport
friend Slic3r::TreeSupportData::TreeSupport
The documentation for this class was generated from the following files:
src/libslic3r/TreeSupport.hpp
src/libslic3r/TreeSupport.cpp