OrcaSlicer: Slic3r::GUI::ColorPickerPopup Class Reference
Slic3r::GUI::ColorPickerPopup Class Reference
#include <src/slic3r/GUI/AMSMaterialsSetting.hpp>
Public Member Functions
ColorPickerPopup (wxWindow *parent)
~ColorPickerPopup ()
void on_custom_clr_picker (wxMouseEvent &event)
void set_ams_colours (std::vector< wxColour > ams)
void set_def_colour (wxColour col)
void paintEvent (wxPaintEvent &evt)
void Popup ()
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Public Attributes
StaticBox * m_custom_cp
wxColourData * m_clrData
StaticBox * m_def_color_box
wxFlexGridSizer * m_ams_fg_sizer
wxColour m_def_col
std::vector< wxColour > m_def_colors
std::vector< wxColour > m_ams_colors
std::vector< ColorPicker * > m_color_pickers
std::vector< ColorPicker * > m_ams_color_pickers
Detailed Description
Constructor & Destructor Documentation
ColorPickerPopup()
Slic3r::GUI::ColorPickerPopup::ColorPickerPopup (wxWindow * parent)
    :PopupWindow(parent, wxBORDER_NONE)
{
    m_def_colors.clear();
    m_def_colors.push_back(wxColour(0xFFFFFF));
    m_def_colors.push_back(wxColour(0xfff144));
    m_def_colors.push_back(wxColour(0xDCF478));
    m_def_colors.push_back(wxColour(0x0ACC38));
    m_def_colors.push_back(wxColour(0x057748));
    m_def_colors.push_back(wxColour(0x0d6284));
    m_def_colors.push_back(wxColour(0x0EE2A0));
    m_def_colors.push_back(wxColour(0x76D9F4));
    m_def_colors.push_back(wxColour(0x46a8f9));
    m_def_colors.push_back(wxColour(0x2850E0));
    m_def_colors.push_back(wxColour(0x443089));
    m_def_colors.push_back(wxColour(0xA03CF7));
    m_def_colors.push_back(wxColour(0xF330F9));
    m_def_colors.push_back(wxColour(0xD4B1DD));
    m_def_colors.push_back(wxColour(0xf95d73));
    m_def_colors.push_back(wxColour(0xf72323));
    m_def_colors.push_back(wxColour(0x7c4b00));
    m_def_colors.push_back(wxColour(0xf98c36));
    m_def_colors.push_back(wxColour(0xfcecd6));
    m_def_colors.push_back(wxColour(0xD3C5A3));
    m_def_colors.push_back(wxColour(0xAF7933));
    m_def_colors.push_back(wxColour(0x898989));
    m_def_colors.push_back(wxColour(0xBCBCBC));
    m_def_colors.push_back(wxColour(0x161616));
    SetBackgroundColour(wxColour(*wxWHITE));
    wxBoxSizer* m_sizer_main = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* m_sizer_box = new wxBoxSizer(wxVERTICAL);
    m_def_color_box = new StaticBox(this);
    wxBoxSizer* m_sizer_ams = new wxBoxSizer(wxHORIZONTAL);
    auto m_title_ams = new wxStaticText(m_def_color_box, wxID_ANY, _L("AMS"), wxDefaultPosition, wxDefaultSize, 0);
    m_title_ams->SetFont(::Label::Body_14);
    m_title_ams->SetBackgroundColour(wxColour(238, 238, 238));
    m_sizer_ams->Add(m_title_ams, 0, wxALL, 5);
    auto ams_line = new wxPanel(m_def_color_box, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    ams_line->SetBackgroundColour(wxColour(0xCECECE));
    ams_line->SetMinSize(wxSize(-1, 1));
    ams_line->SetMaxSize(wxSize(-1, 1));
    m_sizer_ams->Add(ams_line, 1, wxALIGN_CENTER, 0);
    m_def_color_box->SetCornerRadius(FromDIP(10));
    m_def_color_box->SetBackgroundColor(StateColor(std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Normal)));
    m_def_color_box->SetBorderColor(StateColor(std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Normal)));
    //ams
    m_ams_fg_sizer = new wxFlexGridSizer(0, 8, 0, 0);
    m_ams_fg_sizer->SetFlexibleDirection(wxBOTH);
    m_ams_fg_sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
    //other
    wxFlexGridSizer* fg_sizer;
    fg_sizer = new wxFlexGridSizer(0, 8, 0, 0);
    fg_sizer->SetFlexibleDirection(wxBOTH);
    fg_sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
    for (wxColour col : m_def_colors) {
        auto cp = new ColorPicker(m_def_color_box, wxID_ANY, wxDefaultPosition, wxDefaultSize);
        cp->set_color(col);
        cp->set_selected(false);
        cp->SetBackgroundColour(StateColor::darkModeColorFor(wxColour(238,238,238)));
        m_color_pickers.push_back(cp);
        fg_sizer->Add(cp, 0, wxALL, FromDIP(3));
        cp->Bind(wxEVT_LEFT_DOWN, [this, cp](auto& e) {
            set_def_colour(cp->m_colour);
            wxCommandEvent evt(EVT_SELECTED_COLOR);
            unsigned long g_col = ((cp->m_colour.Red() & 0xff) << 16) + ((cp->m_colour.Green() & 0xff) << 8) + (cp->m_colour.Blue() & 0xff);
            evt.SetInt(g_col);
            wxPostEvent(GetParent(), evt);
        });
    }
    wxBoxSizer* m_sizer_other = new wxBoxSizer(wxHORIZONTAL);
    auto m_title_other = new wxStaticText(m_def_color_box, wxID_ANY, _L("Other Color"), wxDefaultPosition, wxDefaultSize, 0);
    m_title_other->SetFont(::Label::Body_14);
    m_title_other->SetBackgroundColour(wxColour(238, 238, 238));
    m_sizer_other->Add(m_title_other, 0, wxALL, 5);
    auto other_line = new wxPanel(m_def_color_box, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    other_line->SetMinSize(wxSize(-1, 1));
    other_line->SetMaxSize(wxSize(-1, 1));
    other_line->SetBackgroundColour(wxColour(0xCECECE));
    m_sizer_other->Add(other_line, 1, wxALIGN_CENTER, 0);
    //custom color
    wxBoxSizer* m_sizer_custom = new wxBoxSizer(wxHORIZONTAL);
    auto m_title_custom = new wxStaticText(m_def_color_box, wxID_ANY, _L("Custom Color"), wxDefaultPosition, wxDefaultSize, 0);
    m_title_custom->SetFont(::Label::Body_14);
    m_title_custom->SetBackgroundColour(wxColour(238, 238, 238));
    auto custom_line = new wxPanel(m_def_color_box, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    custom_line->SetBackgroundColour(wxColour(0xCECECE));
    custom_line->SetMinSize(wxSize(-1, 1));
    custom_line->SetMaxSize(wxSize(-1, 1));
    m_sizer_custom->Add(m_title_custom, 0, wxALL, 5);
    m_sizer_custom->Add(custom_line, 1, wxALIGN_CENTER, 0);
    m_custom_cp =  new StaticBox(m_def_color_box);
    m_custom_cp->SetSize(FromDIP(60), FromDIP(25));
    m_custom_cp->SetMinSize(wxSize(FromDIP(60), FromDIP(25)));
    m_custom_cp->SetMaxSize(wxSize(FromDIP(60), FromDIP(25)));
    m_custom_cp->SetBorderColor(StateColor(std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Normal)));
    m_custom_cp->Bind(wxEVT_LEFT_DOWN, &ColorPickerPopup::on_custom_clr_picker, this);
    m_custom_cp->Bind(wxEVT_ENTER_WINDOW, [this](auto& e) {
        SetCursor(wxCURSOR_HAND);
    });
    m_custom_cp->Bind(wxEVT_LEAVE_WINDOW, [this](auto& e) {
        SetCursor(wxCURSOR_ARROW);
    });
    m_clrData = new wxColourData();
    m_clrData->SetChooseFull(true);
    m_clrData->SetChooseAlpha(false);
    m_sizer_box->Add(0, 0, 0, wxTOP, FromDIP(10));
    m_sizer_box->Add(m_sizer_ams, 1, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(10));
    m_sizer_box->Add(m_ams_fg_sizer, 0, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(10));
    m_sizer_box->Add(m_sizer_other, 1, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(10));
    m_sizer_box->Add(fg_sizer, 0, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(10));
    m_sizer_box->Add(m_sizer_custom, 0, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(10));
    m_sizer_box->Add(m_custom_cp, 0, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(16));
    m_sizer_box->Add(0, 0, 0, wxTOP, FromDIP(10));
    m_def_color_box->SetSizer(m_sizer_box);
    m_def_color_box->Layout();
    m_def_color_box->Fit();
    m_sizer_main->Add(m_def_color_box, 0, wxALL | wxEXPAND, 10);
    SetSizer(m_sizer_main);
    Layout();
    Fit();
    Bind(wxEVT_PAINT, &ColorPickerPopup::paintEvent, this);
    wxGetApp().UpdateDarkUIWin(this);
}
References _L, Label::Body_14, col(), StateColor::darkModeColorFor(), m_ams_fg_sizer, m_clrData, m_color_pickers, m_custom_cp, m_def_color_box, m_def_colors, StateColor::Normal, on_custom_clr_picker(), paintEvent(), set_def_colour(), StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), and wxStaticText.
~ColorPickerPopup()
Slic3r::GUI::ColorPickerPopup::~ColorPickerPopup () inline
{};
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
on_custom_clr_picker()
void Slic3r::GUI::ColorPickerPopup::on_custom_clr_picker (wxMouseEvent & event)
{
    auto clr_dialog = new wxColourDialog(nullptr, m_clrData);
    wxColour picker_color;
    if (clr_dialog->ShowModal() == wxID_OK) {
        m_clrData = &(clr_dialog->GetColourData());
        picker_color = wxColour(
            m_clrData->GetColour().Red(),
            m_clrData->GetColour().Green(),
            m_clrData->GetColour().Blue(),
            254
        );
        m_custom_cp->SetBackgroundColor(picker_color);
        set_def_colour(picker_color);
        wxCommandEvent evt(EVT_SELECTED_COLOR);
        unsigned long g_col = ((picker_color.Red() & 0xff) << 16) + ((picker_color.Green() & 0xff) << 8) + (picker_color.Blue() & 0xff);
        evt.SetInt(g_col);
        wxPostEvent(GetParent(), evt);
    }
}
References m_clrData, m_custom_cp, set_def_colour(), and StaticBox::SetBackgroundColor().
Referenced by ColorPickerPopup().
OnDismiss()
void Slic3r::GUI::ColorPickerPopup::OnDismiss () virtual
{}
paintEvent()
void Slic3r::GUI::ColorPickerPopup::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRoundedRectangle(0, 0, GetSize().x, GetSize().y, 0);
}
Referenced by ColorPickerPopup().
Popup()
void Slic3r::GUI::ColorPickerPopup::Popup ()
{
    PopupWindow::Popup();
}
Referenced by Slic3r::GUI::AMSMaterialsSetting::on_clr_picker().
ProcessLeftDown()
bool Slic3r::GUI::ColorPickerPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
set_ams_colours()
void Slic3r::GUI::ColorPickerPopup::set_ams_colours (std::vector< wxColour > ams)
{
    if (m_ams_color_pickers.size() > 0) {
        for (ColorPicker* col_pick:m_ams_color_pickers) {
            std::vector<ColorPicker*>::iterator iter = find(m_color_pickers.begin(), m_color_pickers.end(), col_pick);
            if (iter != m_color_pickers.end()) {
                col_pick->Destroy();
                m_color_pickers.erase(iter);
            }
        }
        m_ams_color_pickers.clear();
    }
    m_ams_colors = ams;
    for (wxColour col : m_ams_colors) {
        auto cp = new ColorPicker(m_def_color_box, wxID_ANY, wxDefaultPosition, wxDefaultSize);
        cp->set_color(col);
        cp->set_selected(false);
        cp->SetBackgroundColour(StateColor::darkModeColorFor(wxColour(238,238,238)));
        m_color_pickers.push_back(cp);
        m_ams_color_pickers.push_back(cp);
        m_ams_fg_sizer->Add(cp, 0, wxALL, FromDIP(3));
        cp->Bind(wxEVT_LEFT_DOWN, [this, cp](auto& e) {
            set_def_colour(cp->m_colour);
            wxCommandEvent evt(EVT_SELECTED_COLOR);
            unsigned long g_col = ((cp->m_colour.Red() & 0xff) << 16) + ((cp->m_colour.Green() & 0xff) << 8) + (cp->m_colour.Blue() & 0xff);
            evt.SetInt(g_col);
            wxPostEvent(GetParent(), evt);
        });
    }
    m_ams_fg_sizer->Layout();
    Layout();
    Fit();
}
References col(), StateColor::darkModeColorFor(), m_ams_color_pickers, m_ams_colors, m_ams_fg_sizer, m_color_pickers, m_def_color_box, and set_def_colour().
Referenced by Slic3r::GUI::AMSMaterialsSetting::on_clr_picker().
set_def_colour()
void Slic3r::GUI::ColorPickerPopup::set_def_colour (wxColour col)
{
    m_def_col = col;
    for (ColorPicker* cp : m_color_pickers) {
        if (cp->m_selected) {
            cp->set_selected(false);
        }
    }
    for (ColorPicker* cp : m_color_pickers) {
        if (cp->m_colour == m_def_col) {
            cp->set_selected(true);
            break;
        }
    }
    m_custom_cp->SetBackgroundColor(m_def_col);
    Dismiss();
}
References col(), m_color_pickers, m_custom_cp, m_def_col, and StaticBox::SetBackgroundColor().
Referenced by ColorPickerPopup(), Slic3r::GUI::AMSMaterialsSetting::on_clr_picker(), on_custom_clr_picker(), and set_ams_colours().
Member Data Documentation
m_ams_color_pickers
std::vector<ColorPicker*> Slic3r::GUI::ColorPickerPopup::m_ams_color_pickers
Referenced by set_ams_colours().
m_ams_colors
std::vector<wxColour> Slic3r::GUI::ColorPickerPopup::m_ams_colors
Referenced by set_ams_colours().
m_ams_fg_sizer
wxFlexGridSizer* Slic3r::GUI::ColorPickerPopup::m_ams_fg_sizer
Referenced by ColorPickerPopup(), and set_ams_colours().
m_clrData
wxColourData* Slic3r::GUI::ColorPickerPopup::m_clrData
Referenced by ColorPickerPopup(), and on_custom_clr_picker().
m_color_pickers
std::vector<ColorPicker*> Slic3r::GUI::ColorPickerPopup::m_color_pickers
Referenced by ColorPickerPopup(), set_ams_colours(), and set_def_colour().
m_custom_cp
StaticBox* Slic3r::GUI::ColorPickerPopup::m_custom_cp
Referenced by ColorPickerPopup(), on_custom_clr_picker(), and set_def_colour().
m_def_col
wxColour Slic3r::GUI::ColorPickerPopup::m_def_col
Referenced by set_def_colour().
m_def_color_box
StaticBox* Slic3r::GUI::ColorPickerPopup::m_def_color_box
Referenced by ColorPickerPopup(), and set_ams_colours().
m_def_colors
std::vector<wxColour> Slic3r::GUI::ColorPickerPopup::m_def_colors
Referenced by ColorPickerPopup().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AMSMaterialsSetting.hpp
src/slic3r/GUI/AMSMaterialsSetting.cpp