OrcaSlicer: Slic3r::GUI::SelectMachineDialog Class Reference
Slic3r::GUI::SelectMachineDialog Class Reference
#include <src/slic3r/GUI/SelectMachine.hpp>
Public Member Functions
SelectMachineDialog (Plater *plater=nullptr)
~SelectMachineDialog ()
void check_focus (wxWindow *window)
void check_fcous_state (wxWindow *window)
void popup_filament_backup ()
wxWindow * create_ams_checkbox (wxString title, wxWindow *parent, wxString tooltip)
wxWindow * create_item_checkbox (wxString title, wxWindow *parent, wxString tooltip, std::string param)
void update_select_layout (MachineObject *obj)
void prepare_mode ()
void sending_mode ()
void finish_mode ()
void sync_ams_mapping_result (std::vector< FilamentInfo > &result)
bool do_ams_mapping (MachineObject *obj_)
bool get_ams_mapping_result (std::string &mapping_array_str, std::string &ams_mapping_info)
void prepare (int print_plate_idx)
bool has_tips (MachineObject *obj)
void show_status (PrintDialogStatus status, std::vector< wxString > params=std::vector< wxString >())
PrintDialogStatus get_status ()
bool is_same_printer_model ()
void sys_color_changed ()
bool Show (bool show)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Public Attributes
wxObjectDataPtr< MachineListModel > machine_model
std::shared_ptr< BBLStatusBarSend > m_status_bar
bool m_export_3mf_cancel {false}
bool m_is_canceled { false }
Protected Member Functions
void stripWhiteSpace (std::string &str)
wxString format_text (wxString &m_msg)
void update_ams_status_msg (wxString msg, bool is_warning=false)
void update_priner_status_msg (wxString msg, bool is_warning=false)
void update_print_status_msg (wxString msg, bool is_warning=false, bool is_printer=true)
bool is_timeout ()
void reset_timeout ()
void update_user_printer ()
void reset_ams_material ()
void update_show_status ()
void update_ams_check (MachineObject *obj)
bool is_show_timelapse ()
void on_rename_click (wxCommandEvent &event)
void on_rename_enter ()
void update_printer_combobox (wxCommandEvent &event)
void on_cancel (wxCloseEvent &event)
void show_errors (wxString &info)
void on_ok_btn (wxCommandEvent &event)
void on_ok ()
void clear_ip_address_config (wxCommandEvent &e)
void on_refresh (wxCommandEvent &event)
void on_set_finish_mapping (wxCommandEvent &evt)
void on_print_job_cancel (wxCommandEvent &evt)
void set_default ()
void on_timer (wxTimerEvent &event)
void on_selection_changed (wxCommandEvent &event)
void Enable_Refresh_Button (bool en)
void Enable_Send_Button (bool en)
void on_dpi_changed (const wxRect &suggested_rect) override
void update_user_machine_list ()
void update_lan_machine_list ()
wxImage * LoadImageFromBlob (const unsigned char *data, int size)
std::vector< std::string > sort_string (std::vector< std::string > strArray)
virtual void on_sys_color_changed ()
Protected Attributes
MaterialHash m_materialList
std::vector< FilamentInfo > m_filaments
std::vector< FilamentInfo > m_ams_mapping_result
bool m_ams_mapping_res { false }
bool ams_mapping_valid { false }
Plater * m_plater {nullptr}
wxPanel * m_line_top {nullptr}
wxPanel * m_panel_image {nullptr}
wxStaticText * m_stext_time {nullptr}
wxStaticText * m_stext_weight {nullptr}
wxPanel * m_line_materia {nullptr}
wxStaticText * m_stext_printer_title {nullptr}
wxBoxSizer * rename_sizer_v { nullptr }
wxBoxSizer * rename_sizer_h { nullptr }
wxStaticText * m_rename_text {nullptr}
TextInput * m_rename_input {nullptr}
Button * m_rename_button {nullptr}
wxPanel * m_rename_normal_panel {nullptr}
wxSimplebook * m_rename_switch_panel {nullptr}
wxStaticText * m_statictext_ams_msg {nullptr}
wxStaticText * m_statictext_printer_msg {nullptr}
wxStaticBitmap * m_staticbitmap {nullptr}
ThumbnailPanel * m_thumbnailPanel {nullptr}
::ComboBox * m_comboBox_printer {nullptr}
::ComboBox * m_comboBox_bed {nullptr}
wxStaticText * m_staticText_bed_title {nullptr}
wxPanel * m_line_schedule {nullptr}
wxPanel * m_panel_sending {nullptr}
wxStaticText * m_stext_sending {nullptr}
wxPanel * m_panel_prepare {nullptr}
Button * m_button_refresh {nullptr}
Button * m_button_ensure {nullptr}
wxPanel * m_panel_finish {nullptr}
wxSimplebook * m_simplebook {nullptr}
wxStaticText * m_statictext_finish {nullptr}
StateColor btn_bg_enable
int m_current_filament_id
bool m_is_in_sending_mode { false }
wxWrapSizer * m_sizer_select
wxBoxSizer * sizer_thumbnail
wxGridSizer * m_sizer_material
wxBoxSizer * m_sizer_main
wxBoxSizer * m_sizer_bottom
bool m_need_adaptation_screen {false}
wxScrolledWindow * m_scrollable_view
wxBoxSizer * m_sizer_scrollable_view
wxPanel * m_scrollable_region
wxBoxSizer * m_sizer_scrollable_region
wxWindow * select_bed {nullptr}
wxWindow * select_flow {nullptr}
wxWindow * select_timelapse { nullptr }
wxWindow * select_use_ams {nullptr}
CheckBox * ams_check {nullptr}
std::vector< MachineObject * > m_list
wxDataViewCtrl * m_dataViewListCtrl_machines {nullptr}
wxStaticText * m_staticText_left {nullptr}
wxHyperlinkCtrl * m_hyperlink_add_machine {nullptr}
wxGauge * m_gauge_job_progress {nullptr}
wxPanel * m_panel_status {nullptr}
wxButton * m_button_cancel {nullptr}
AmsMapingPopup m_mapping_popup {nullptr}
AmsMapingTipPopup m_mapping_tip_popup {nullptr}
AmsTutorialPopup m_mapping_tutorial_popup {nullptr}
wxString m_current_project_name
std::string m_print_info
int timeout_count = 0
bool m_is_rename_mode {false}
wxTimer * m_refresh_timer { nullptr }
std::shared_ptr< PrintJob > m_print_job
Private Member Functions
void init_model ()
void init_bind ()
void init_timer ()
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
int m_print_plate_idx
std::string m_printer_last_select
PrintDialogStatus m_print_status { PrintStatusInit }
std::vector< wxString > m_bedtype_list
std::map< std::string, ::CheckBox * > m_checkbox_list
wxColour m_colour_def_color {wxColour(255, 255, 255)}
wxColour m_colour_bold_color {wxColour(38, 46, 48)}
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
SelectMachineDialog()
Slic3r::GUI::SelectMachineDialog::SelectMachineDialog (Plater * plater = nullptr)
    : DPIDialog(static_cast<wxWindow *>(wxGetApp().mainframe), wxID_ANY, _L("Send print job to"), wxDefaultPosition, wxDefaultSize, wxCAPTION | wxCLOSE_BOX)
    , m_plater(plater), m_export_3mf_cancel(false)
    , m_mapping_popup(AmsMapingPopup(this))
    , m_mapping_tip_popup(AmsMapingTipPopup(this))
    , m_mapping_tutorial_popup(AmsTutorialPopup(this))
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    // bind
    Bind(wxEVT_CLOSE_WINDOW, &SelectMachineDialog::on_cancel, this);
    for (int i = 0; i < BED_TYPE_COUNT; i++) { m_bedtype_list.push_back(MACHINE_BED_TYPE_STRING[i]); }
    // font
    SetFont(wxGetApp().normal_font());
    // icon
    std::string icon_path = (boost::format("%1%/images/OrcaSlicerTitle.ico") % resources_dir()).str();
    SetIcon(wxIcon(encode_path(icon_path.c_str()), wxBITMAP_TYPE_ICO));
    Freeze();
    SetBackgroundColour(m_colour_def_color);
    m_sizer_main = new wxBoxSizer(wxVERTICAL);
    m_sizer_main->SetMinSize(wxSize(0, -1));
    m_line_top = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    m_line_top->SetBackgroundColour(wxColour(166, 169, 170));
    m_scrollable_view   = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    m_sizer_scrollable_view = new wxBoxSizer(wxVERTICAL);
    m_scrollable_region       = new wxPanel(m_scrollable_view, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_sizer_scrollable_region = new wxBoxSizer(wxVERTICAL);
    //rename normal
    m_rename_switch_panel = new wxSimplebook(m_scrollable_region);
    m_rename_switch_panel->SetSize(wxSize(FromDIP(420), FromDIP(25)));
    m_rename_switch_panel->SetMinSize(wxSize(FromDIP(420), FromDIP(25)));
    m_rename_switch_panel->SetMaxSize(wxSize(FromDIP(420), FromDIP(25)));
    m_rename_normal_panel = new wxPanel(m_rename_switch_panel, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_rename_normal_panel->SetBackgroundColour(*wxWHITE);
    rename_sizer_v = new wxBoxSizer(wxVERTICAL);
    rename_sizer_h = new wxBoxSizer(wxHORIZONTAL);
    m_rename_text = new wxStaticText(m_rename_normal_panel, wxID_ANY, wxT("MyLabel"), wxDefaultPosition, wxDefaultSize, 0);
    m_rename_text->SetFont(::Label::Body_13);
    m_rename_text->SetMaxSize(wxSize(FromDIP(390), -1));
    m_rename_button = new Button(m_rename_normal_panel, "", "ams_editable", wxBORDER_NONE, FromDIP(10));
    m_rename_button->SetBackgroundColor(*wxWHITE);
    m_rename_button->SetBackgroundColour(*wxWHITE);
    rename_sizer_h->Add(m_rename_text, 0, wxALIGN_CENTER, 0);
    rename_sizer_h->Add(m_rename_button, 0, wxALIGN_CENTER, 0);
    rename_sizer_v->Add(rename_sizer_h, 1, wxALIGN_CENTER, 0);
    m_rename_normal_panel->SetSizer(rename_sizer_v);
    m_rename_normal_panel->Layout();
    rename_sizer_v->Fit(m_rename_normal_panel);
    //rename edit
    auto m_rename_edit_panel = new wxPanel(m_rename_switch_panel, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_rename_edit_panel->SetBackgroundColour(*wxWHITE);
    auto rename_edit_sizer_v = new wxBoxSizer(wxVERTICAL);
    m_rename_input = new ::TextInput(m_rename_edit_panel, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    m_rename_input->GetTextCtrl()->SetFont(::Label::Body_13);
    m_rename_input->SetSize(wxSize(FromDIP(380), FromDIP(24)));
    m_rename_input->SetMinSize(wxSize(FromDIP(380), FromDIP(24)));
    m_rename_input->SetMaxSize(wxSize(FromDIP(380), FromDIP(24)));
    m_rename_input->Bind(wxEVT_TEXT_ENTER, [this](auto& e) {on_rename_enter();});
    m_rename_input->Bind(wxEVT_KILL_FOCUS, [this](auto& e) {
        if (!m_rename_input->HasFocus() && !m_rename_text->HasFocus())
            on_rename_enter();
        else
            e.Skip(); });
    rename_edit_sizer_v->Add(m_rename_input, 1, wxALIGN_CENTER, 0);
    m_rename_edit_panel->SetSizer(rename_edit_sizer_v);
    m_rename_edit_panel->Layout();
    rename_edit_sizer_v->Fit(m_rename_edit_panel);
    m_rename_button->Bind(wxEVT_BUTTON, &SelectMachineDialog::on_rename_click, this);
    m_rename_switch_panel->AddPage(m_rename_normal_panel, wxEmptyString, true);
    m_rename_switch_panel->AddPage(m_rename_edit_panel, wxEmptyString, false);
    Bind(wxEVT_CHAR_HOOK, [this](wxKeyEvent& e) {
        if (e.GetKeyCode() == WXK_ESCAPE) {
            if (m_rename_switch_panel->GetSelection() == 0) {
                e.Skip();
            }
            else {
                m_rename_switch_panel->SetSelection(0);
                m_rename_text->SetLabel(m_current_project_name);
                m_rename_normal_panel->Layout();
            }
        }
        else {
            e.Skip();
        }
    });
    m_panel_image = new wxPanel(m_scrollable_region, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_panel_image->SetBackgroundColour(m_colour_def_color);
    sizer_thumbnail = new wxBoxSizer(wxVERTICAL);
    m_thumbnailPanel = new ThumbnailPanel(m_panel_image);
    m_thumbnailPanel->SetSize(wxSize(FromDIP(256), FromDIP(256)));
    m_thumbnailPanel->SetMinSize(wxSize(FromDIP(256), FromDIP(256)));
    m_thumbnailPanel->SetMaxSize(wxSize(FromDIP(256), FromDIP(256)));
    sizer_thumbnail->Add(m_thumbnailPanel, 0, wxEXPAND, 0);
    m_panel_image->SetSizer(sizer_thumbnail);
    m_panel_image->Layout();
    wxBoxSizer *m_sizer_basic        = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_sizer_basic_weight = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_sizer_basic_time   = new wxBoxSizer(wxHORIZONTAL);
    auto timeimg = new wxStaticBitmap(m_scrollable_region, wxID_ANY, create_scaled_bitmap("print-time", this, 18), wxDefaultPosition, wxSize(FromDIP(18), FromDIP(18)), 0);
    m_sizer_basic_weight->Add(timeimg, 1, wxEXPAND | wxALL, FromDIP(5));
    m_stext_time = new wxStaticText(m_scrollable_region, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxALIGN_RIGHT);
    m_sizer_basic_weight->Add(m_stext_time, 0, wxALL, FromDIP(5));
    m_sizer_basic->Add(m_sizer_basic_weight, 0, wxALIGN_CENTER, 0);
    m_sizer_basic->Add(0, 0, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(30));
    auto weightimg = new wxStaticBitmap(m_scrollable_region, wxID_ANY, create_scaled_bitmap("print-weight", this, 18), wxDefaultPosition, wxSize(FromDIP(18), FromDIP(18)), 0);
    m_sizer_basic_time->Add(weightimg, 1, wxEXPAND | wxALL, FromDIP(5));
    m_stext_weight = new wxStaticText(m_scrollable_region, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    m_sizer_basic_time->Add(m_stext_weight, 0, wxALL, FromDIP(5));
    m_sizer_basic->Add(m_sizer_basic_time, 0, wxALIGN_CENTER, 0);
    wxBoxSizer* m_sizer_material_area = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* m_sizer_material_tips = new wxBoxSizer(wxHORIZONTAL);
    auto img_amsmapping_tip = new wxStaticBitmap(m_scrollable_region, wxID_ANY, create_scaled_bitmap("enable_ams", this, 16), wxDefaultPosition, wxSize(FromDIP(16), FromDIP(16)), 0);
    m_sizer_material_tips->Add(img_amsmapping_tip, 0, wxALIGN_CENTER | wxLEFT, FromDIP(5));
    img_amsmapping_tip->Bind(wxEVT_ENTER_WINDOW, [this, img_amsmapping_tip](auto& e) {
        wxPoint img_pos = img_amsmapping_tip->ClientToScreen(wxPoint(0, 0));
        wxPoint popup_pos(img_pos.x, img_pos.y + img_amsmapping_tip->GetRect().height);
        m_mapping_tutorial_popup.Position(popup_pos, wxSize(0, 0));
        m_mapping_tutorial_popup.Popup();
        if (m_mapping_tutorial_popup.ClientToScreen(wxPoint(0, 0)).y < img_pos.y) {
            m_mapping_tutorial_popup.Dismiss();
            popup_pos = wxPoint(img_pos.x, img_pos.y - m_mapping_tutorial_popup.GetRect().height);
            m_mapping_tutorial_popup.Position(popup_pos, wxSize(0, 0));
            m_mapping_tutorial_popup.Popup();
        }
        });
    img_amsmapping_tip->Bind(wxEVT_LEAVE_WINDOW, [this](wxMouseEvent& e) {
        m_mapping_tutorial_popup.Dismiss();
        });
    m_sizer_material = new wxGridSizer(0, 4, 0, FromDIP(5));
    m_sizer_material_area->Add(m_sizer_material_tips, 0, wxALIGN_CENTER|wxLEFT, FromDIP(8));
    m_sizer_material_area->Add(m_sizer_material, 0, wxLEFT, FromDIP(15));
#ifdef FILAMENT_BACKUP
    auto m_sizer_backup = new wxBoxSizer(wxHORIZONTAL);
    auto m_ams_backup_tip = new Label(this, _L("Ams filament backup"));
    m_ams_backup_tip->SetFont(::Label::Head_12);
    m_ams_backup_tip->SetForegroundColour(wxColour(0x00AE42));
    m_ams_backup_tip->SetBackgroundColour(*wxWHITE);
    auto img_ams_backup = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("automatic_material_renewal", this, 16), wxDefaultPosition, wxSize(FromDIP(16), FromDIP(16)), 0);
    img_ams_backup->SetBackgroundColour(*wxWHITE);
    m_sizer_backup->Add(0, 0, 1, wxEXPAND, 0);
    m_sizer_backup->Add(img_ams_backup, 0, wxALL, FromDIP(3));
    m_sizer_backup->Add(m_ams_backup_tip, 0, wxTOP, FromDIP(5));
    m_ams_backup_tip->Bind(wxEVT_ENTER_WINDOW, [this, img_amsmapping_tip](auto& e) {SetCursor(wxCURSOR_HAND); });
    img_ams_backup->Bind(wxEVT_ENTER_WINDOW, [this, img_amsmapping_tip](auto& e) {SetCursor(wxCURSOR_HAND); });
    m_ams_backup_tip->Bind(wxEVT_LEAVE_WINDOW, [this](auto& e) {SetCursor(wxCURSOR_ARROW); });
    img_ams_backup->Bind(wxEVT_LEAVE_WINDOW, [this](auto& e) {SetCursor(wxCURSOR_ARROW); });
    m_ams_backup_tip->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {popup_filament_backup(); on_rename_enter(); });
    img_ams_backup->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {popup_filament_backup(); });
#endif
    m_statictext_ams_msg = new wxStaticText(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    m_statictext_ams_msg->SetFont(::Label::Body_13);
    m_statictext_ams_msg->Hide();
    m_line_materia = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    m_line_materia->SetForegroundColour(wxColour(238, 238, 238));
    m_line_materia->SetBackgroundColour(wxColour(238, 238, 238));
    wxBoxSizer *m_sizer_printer = new wxBoxSizer(wxHORIZONTAL);
    m_stext_printer_title = new wxStaticText(this, wxID_ANY, _L("Printer"), wxDefaultPosition, wxSize(-1, -1), 0);
    m_stext_printer_title->SetFont(::Label::Head_14);
    m_stext_printer_title->Wrap(-1);
    m_stext_printer_title->SetForegroundColour(m_colour_bold_color);
    m_stext_printer_title->SetBackgroundColour(m_colour_def_color);
    m_sizer_printer->Add(m_stext_printer_title, 0, wxALL | wxLEFT, FromDIP(5));
    m_sizer_printer->Add(0, 0, 0, wxEXPAND | wxLEFT, FromDIP(12));
    m_comboBox_printer = new ::ComboBox(this, wxID_ANY, "", wxDefaultPosition, wxSize(FromDIP(250), -1), 0, nullptr, wxCB_READONLY);
    m_comboBox_printer->Bind(wxEVT_COMBOBOX, &SelectMachineDialog::on_selection_changed, this);
    m_sizer_printer->Add(m_comboBox_printer, 1, wxEXPAND | wxRIGHT, FromDIP(5));
    btn_bg_enable = StateColor(std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed), std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
                               std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    m_button_refresh = new Button(this, _L("Refresh"));
    m_button_refresh->SetBackgroundColor(btn_bg_enable);
    m_button_refresh->SetBorderColor(btn_bg_enable);
    m_button_refresh->SetTextColor(StateColor::darkModeColorFor("#FFFFFE"));
    m_button_refresh->SetSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_refresh->SetMinSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_refresh->SetCornerRadius(FromDIP(10));
    m_button_refresh->Bind(wxEVT_BUTTON, &SelectMachineDialog::on_refresh, this);
    m_sizer_printer->Add(m_button_refresh, 0, wxALL | wxLEFT, FromDIP(5));
    m_statictext_printer_msg = new wxStaticText(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    m_statictext_printer_msg->SetFont(::Label::Body_13);
    m_statictext_printer_msg->Hide();
    //m_sizer_select = new wxGridSizer(0, 2, 0, 0);
    m_sizer_select = new wxWrapSizer();
    select_bed     = create_item_checkbox(_L("Bed Leveling"), this, _L("Bed Leveling"), "bed_leveling");
    select_flow    = create_item_checkbox(_L("Flow Calibration"), this, _L("Flow Calibration"), "flow_cali");
    select_timelapse = create_item_checkbox(_L("Timelapse"), this, _L("Timelapse"), "timelapse");
    select_use_ams = create_ams_checkbox(_L("Enable AMS"), this, _L("Enable AMS"));
    m_sizer_select->Add(select_bed, 0, wxLEFT | wxRIGHT, WRAP_GAP);
    m_sizer_select->Add(select_flow, 0, wxLEFT | wxRIGHT, WRAP_GAP);
    m_sizer_select->Add(select_timelapse, 0, wxLEFT | wxRIGHT, WRAP_GAP);
    m_sizer_select->Add(select_use_ams, 0, wxLEFT | wxRIGHT, WRAP_GAP);
    select_bed->Show(true);
    select_flow->Show(true);
    select_timelapse->Show(true);
    select_use_ams->Show(true);
    m_sizer_select->Layout();
    // line schedule
    m_line_schedule = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1));
    m_line_schedule->SetBackgroundColour(wxColour(238, 238, 238));
    m_sizer_bottom = new wxBoxSizer(wxVERTICAL);
    m_simplebook   = new wxSimplebook(this, wxID_ANY, wxDefaultPosition, SELECT_MACHINE_DIALOG_SIMBOOK_SIZE, 0);
    // perpare mode
    m_panel_prepare = new wxPanel(m_simplebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_panel_prepare->SetBackgroundColour(m_colour_def_color);
    //m_panel_prepare->SetBackgroundColour(wxColour(135,206,250));
    wxBoxSizer *m_sizer_prepare = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_sizer_pcont   = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_prepare->Add(0, 0, 1, wxTOP, FromDIP(12));
    auto hyperlink_sizer = new wxBoxSizer( wxHORIZONTAL );
    auto m_hyperlink = new wxHyperlinkCtrl(m_panel_prepare, wxID_ANY, _L("Can't find my devices?"), wxT("https://wiki.bambulab.com/en/software/bambu-studio/failed-to-connect-printer"), wxDefaultPosition, wxDefaultSize, wxHL_DEFAULT_STYLE);
    //auto linkimg = new wxStaticBitmap(m_panel_prepare, wxID_ANY, create_scaled_bitmap("link_wiki_img", this, 18), wxDefaultPosition, wxSize(FromDIP(18), FromDIP(18)), 0);
    hyperlink_sizer->Add(m_hyperlink, 0, wxALIGN_CENTER | wxALL, 5);
    //hyperlink_sizer->Add(linkimg, 0, wxALIGN_CENTER | wxALL, FromDIP(5));
    m_sizer_prepare->Add(hyperlink_sizer, 0, wxALIGN_CENTER | wxALL, 5);
    m_button_ensure = new Button(m_panel_prepare, _L("Send"));
    m_button_ensure->SetBackgroundColor(btn_bg_enable);
    m_button_ensure->SetBorderColor(btn_bg_enable);
    m_button_ensure->SetTextColor(StateColor::darkModeColorFor("#FFFFFE"));
    m_button_ensure->SetSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_ensure->SetMinSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_ensure->SetCornerRadius(FromDIP(12));
    m_button_ensure->Bind(wxEVT_BUTTON, &SelectMachineDialog::on_ok_btn, this);
    m_sizer_pcont->Add(0, 0, 1, wxEXPAND, 0);
    m_sizer_pcont->Add(m_button_ensure, 0, wxEXPAND | wxBOTTOM, FromDIP(10));
    m_sizer_prepare->Add(m_sizer_pcont, 0, wxEXPAND, 0);
    m_panel_prepare->SetSizer(m_sizer_prepare);
    m_panel_prepare->Layout();
    m_simplebook->AddPage(m_panel_prepare, wxEmptyString, true);
    // sending mode
    m_status_bar    = std::make_shared<BBLStatusBarSend>(m_simplebook);
    m_panel_sending = m_status_bar->get_panel();
    m_simplebook->AddPage(m_panel_sending, wxEmptyString, false);
    // finish mode
    m_panel_finish = new wxPanel(m_simplebook, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_panel_finish->SetBackgroundColour(wxColour(135, 206, 250));
    wxBoxSizer *m_sizer_finish   = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_sizer_finish_v = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_sizer_finish_h = new wxBoxSizer(wxHORIZONTAL);
    auto imgsize      = FromDIP(25);
    auto completedimg = new wxStaticBitmap(m_panel_finish, wxID_ANY, create_scaled_bitmap("completed", m_panel_finish, 25), wxDefaultPosition, wxSize(imgsize, imgsize), 0);
    m_sizer_finish_h->Add(completedimg, 0, wxALIGN_CENTER | wxALL, FromDIP(5));
    m_statictext_finish = new wxStaticText(m_panel_finish, wxID_ANY, L("send completed"), wxDefaultPosition, wxDefaultSize, 0);
    m_statictext_finish->Wrap(-1);
    m_statictext_finish->SetForegroundColour(wxColour(0, 150, 136));
    m_sizer_finish_h->Add(m_statictext_finish, 0, wxALIGN_CENTER | wxALL, FromDIP(5));
    m_sizer_finish_v->Add(m_sizer_finish_h, 1, wxALIGN_CENTER, 0);
    m_sizer_finish->Add(m_sizer_finish_v, 1, wxALIGN_CENTER, 0);
    m_panel_finish->SetSizer(m_sizer_finish);
    m_panel_finish->Layout();
    m_sizer_finish->Fit(m_panel_finish);
    m_simplebook->AddPage(m_panel_finish, wxEmptyString, false);
    // bind
    Bind(EVT_UPDATE_USER_MACHINE_LIST, &SelectMachineDialog::update_printer_combobox, this);
    Bind(EVT_PRINT_JOB_CANCEL, &SelectMachineDialog::on_print_job_cancel, this);
    Bind(EVT_SET_FINISH_MAPPING, &SelectMachineDialog::on_set_finish_mapping, this);
    wxGetApp().Bind(EVT_CONNECT_LAN_MODE_PRINT, [this](wxCommandEvent& e) {
        if (e.GetInt() == 1) {
            DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
            if (!dev) return;
            if (dev->get_selected_machine()) {
                m_comboBox_printer->SetValue(dev->get_selected_machine()->dev_name + "(LAN)");
            }
        }
    });
    m_panel_prepare->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {
        check_fcous_state(this);
        e.Skip();
    });
    m_scrollable_region->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {
        check_fcous_state(this);
        e.Skip();
    });
    Bind(wxEVT_LEFT_DOWN, [this](auto& e) {
        check_fcous_state(this);
        e.Skip();
    });
    m_sizer_scrollable_region->Add(m_rename_switch_panel, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_scrollable_region->Add(0, 0, 0, wxTOP, FromDIP(8));
    m_sizer_scrollable_region->Add(m_panel_image, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_scrollable_region->Add(0, 0, 0, wxTOP, FromDIP(10));
    m_sizer_scrollable_region->Add(m_sizer_basic, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    //m_sizer_scrollable_region->Add(m_sizer_material, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_scrollable_region->Add(m_sizer_material_area, 0, wxLEFT, FromDIP(10));
    m_scrollable_region->SetSizer(m_sizer_scrollable_region);
    m_scrollable_region->Layout();
    m_scrollable_view->SetSizer(m_sizer_scrollable_view);
    m_scrollable_view->Layout();
    m_sizer_scrollable_view->Add(m_scrollable_region, 0, wxEXPAND, 0);
    m_sizer_main->Add(m_line_top, 0, wxEXPAND, 0);
    m_sizer_main->Add(0, 0, 0, wxTOP, FromDIP(22));
    m_sizer_main->Add(m_scrollable_view, 0, wxALIGN_CENTER_HORIZONTAL, 0);
#ifdef FILAMENT_BACKUP
    m_sizer_main->Add(m_sizer_backup, 0, wxALIGN_CENTER_HORIZONTAL, 0);
#endif
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(8));
    m_sizer_main->Add(m_statictext_ams_msg, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(8));
    m_sizer_main->Add(m_line_materia, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(30));
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(14));
    m_sizer_main->Add(m_sizer_printer, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(30));
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(5));
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(8));
    m_sizer_main->Add(m_statictext_printer_msg, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_main->Add(0, 1, 0, wxTOP, FromDIP(20));
    m_sizer_main->Add(m_sizer_select, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(40));
    m_sizer_main->Add(0, 1, 0, wxTOP, FromDIP(12));
    m_sizer_main->Add(m_line_schedule, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(30));
    m_sizer_main->Add(m_simplebook, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_sizer_main->Add(m_sizer_bottom, 0, wxALIGN_CENTER_HORIZONTAL);
    m_sizer_main->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(15));
    SetSizer(m_sizer_main);
    Layout();
    Fit();
    Thaw();
    init_bind();
    init_timer();
    // CenterOnParent();
    Centre(wxBOTH);
    wxGetApp().UpdateDlgDarkUI(this);
}
References Slic3r::BED_TYPE_COUNT, Label::Body_13, Slic3r::encode_path(), TextInput::GetTextCtrl(), m_bedtype_list, m_colour_def_color, m_line_top, m_rename_button, m_rename_input, m_rename_normal_panel, m_rename_switch_panel, m_rename_text, m_scrollable_region, m_scrollable_view, m_sizer_main, m_sizer_scrollable_region, m_sizer_scrollable_view, Slic3r::GUI::MACHINE_BED_TYPE_STRING, Slic3r::GUI::DPIAware< P >::normal_font(), on_cancel(), on_rename_click(), on_rename_enter(), rename_sizer_h, rename_sizer_v, Slic3r::resources_dir(), StaticBox::SetBackgroundColor(), TextInput::SetMinSize(), wxEVT_BUTTON, and wxStaticText.
~SelectMachineDialog()
Slic3r::GUI::SelectMachineDialog::~SelectMachineDialog ()
{
    delete m_refresh_timer;
}
References m_refresh_timer.
Member Function Documentation
check_fcous_state()
void Slic3r::GUI::SelectMachineDialog::check_fcous_state (wxWindow * window)
{
    check_focus(window);
    auto children = window->GetChildren();
    for (auto child : children) {
        check_fcous_state(child);
    }
}
References check_fcous_state(), and check_focus().
Referenced by check_fcous_state().
check_focus()
void Slic3r::GUI::SelectMachineDialog::check_focus (wxWindow * window)
{
    if (window == m_rename_input || window == m_rename_input->GetTextCtrl()) {
        on_rename_enter();
    }
}
References TextInput::GetTextCtrl(), m_rename_input, and on_rename_enter().
Referenced by check_fcous_state().
clear_ip_address_config()
void Slic3r::GUI::SelectMachineDialog::clear_ip_address_config (wxCommandEvent & e) protected
{
    prepare_mode();
}
References prepare_mode().
Referenced by init_bind().
create_ams_checkbox()
wxWindow * Slic3r::GUI::SelectMachineDialog::create_ams_checkbox (wxString title, wxWindow * parent, wxString tooltip)
{
    auto checkbox = new wxWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    checkbox->SetBackgroundColour(m_colour_def_color);
    wxBoxSizer *sizer_checkbox = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *sizer_check    = new wxBoxSizer(wxVERTICAL);
    ams_check = new ::CheckBox(checkbox);
    sizer_check->Add(ams_check, 0, wxBOTTOM | wxEXPAND | wxTOP, FromDIP(5));
    sizer_checkbox->Add(sizer_check, 0, wxEXPAND, FromDIP(5));
    sizer_checkbox->Add(0, 0, 0, wxEXPAND | wxLEFT, FromDIP(11));
    auto text = new wxStaticText(checkbox, wxID_ANY, title, wxDefaultPosition, wxDefaultSize, 0);
    text->SetFont(::Label::Body_13);
    text->SetForegroundColour(StateColor::darkModeColorFor(wxColour("#323A3C")));
    text->Wrap(-1);
    sizer_checkbox->Add(text, 0, wxALIGN_CENTER, 0);
    auto img_ams_tip = new wxStaticBitmap(checkbox, wxID_ANY, create_scaled_bitmap("enable_ams", this, 16), wxDefaultPosition, wxSize(FromDIP(16), FromDIP(16)), 0);
    sizer_checkbox->Add(img_ams_tip, 0, wxALIGN_CENTER | wxLEFT, FromDIP(5));
    img_ams_tip->Bind(wxEVT_ENTER_WINDOW, [this, img_ams_tip](auto& e) {
        wxPoint img_pos = img_ams_tip->ClientToScreen(wxPoint(0, 0));
        wxPoint popup_pos(img_pos.x, img_pos.y + img_ams_tip->GetRect().height);
        m_mapping_tip_popup.Position(popup_pos, wxSize(0, 0));
        m_mapping_tip_popup.Popup();
        if (m_mapping_tip_popup.ClientToScreen(wxPoint(0, 0)).y < img_pos.y) {
            m_mapping_tip_popup.Dismiss();
            popup_pos = wxPoint(img_pos.x, img_pos.y - m_mapping_tip_popup.GetRect().height);
            m_mapping_tip_popup.Position(popup_pos, wxSize(0, 0));
            m_mapping_tip_popup.Popup();
        }
    });
    img_ams_tip->Bind(wxEVT_LEAVE_WINDOW, [this](wxMouseEvent& e) {
        m_mapping_tip_popup.Dismiss();
        });
    checkbox->SetSizer(sizer_checkbox);
    checkbox->Layout();
    sizer_checkbox->Fit(checkbox);
    checkbox->SetToolTip(tooltip);
    text->SetToolTip(tooltip);
    ams_check->Bind(wxEVT_TOGGLEBUTTON, [this](wxCommandEvent &e) {
        wxGetApp().app_config->set("bbl_machine", "use_ams", ams_check->GetValue());
    });
    text->Bind(wxEVT_LEFT_DOWN, [this](wxMouseEvent& event) {
        ams_check->SetValue(ams_check->GetValue() ? false : true);
        });
    checkbox->Bind(wxEVT_LEFT_DOWN, [this](wxMouseEvent& event) {
        ams_check->SetValue(ams_check->GetValue() ? false : true);
        });
    return checkbox;
}
References ams_check, Label::Body_13, create_scaled_bitmap(), StateColor::darkModeColorFor(), m_colour_def_color, m_mapping_tip_popup, Slic3r::GUI::wxMouseEvent, and wxStaticText.
create_item_checkbox()
wxWindow * Slic3r::GUI::SelectMachineDialog::create_item_checkbox (wxString title, wxWindow * parent, wxString tooltip, std::string param)
{
    auto checkbox = new wxWindow(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    checkbox->SetBackgroundColour(m_colour_def_color);
    wxBoxSizer *sizer_checkbox = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *sizer_check    = new wxBoxSizer(wxVERTICAL);
    auto check = new ::CheckBox(checkbox);
    sizer_check->Add(check, 0, wxBOTTOM | wxEXPAND | wxTOP, FromDIP(5));
    sizer_checkbox->Add(sizer_check, 0, wxEXPAND, FromDIP(5));
    sizer_checkbox->Add(0, 0, 0, wxEXPAND | wxLEFT, FromDIP(11));
    auto text = new wxStaticText(checkbox, wxID_ANY, title, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
    text->SetFont(::Label::Body_13);
    text->SetForegroundColour(StateColor::darkModeColorFor(wxColour("#323A3C")));
    text->Wrap(-1);
    text->SetMinSize(wxSize(FromDIP(120), -1));
    text->SetMaxSize(wxSize(FromDIP(120), -1));
    sizer_checkbox->Add(text, 0, wxALIGN_CENTER, 0);
    checkbox->SetSizer(sizer_checkbox);
    checkbox->Layout();
    sizer_checkbox->Fit(checkbox);
    checkbox->SetToolTip(tooltip);
    text->SetToolTip(tooltip);
    checkbox->Bind(wxEVT_TOGGLEBUTTON, [this, param, check](wxCommandEvent &e) {
        wxGetApp().app_config->set("bbl_machine",param.c_str(), check->GetValue());
    });
    text->Bind(wxEVT_LEFT_DOWN, [this, check](wxMouseEvent &) { check->SetValue(check->GetValue() ? false : true); });
    check->Bind(wxEVT_LEFT_DOWN, [this, check, param](wxMouseEvent &e) {
        AppConfig* config = wxGetApp().app_config;
        if (config) {
            if (check->GetValue())
                config->set_str("print", param, "0");
            else
                config->set_str("print", param, "1");
        }
        e.Skip();
    });
    checkbox->Bind(wxEVT_LEFT_DOWN, [this, check, param](wxMouseEvent&) {
        check->SetValue(check->GetValue() ? false : true);
        AppConfig* config = wxGetApp().app_config;
        if (config) {
            if (check->GetValue())
                config->set_str("print", param, "1");
            else
                config->set_str("print", param, "0");
        }
        });
    text->Bind(wxEVT_LEFT_DOWN, [this, check, param](wxMouseEvent &) {
        check->SetValue(check->GetValue() ? false : true);
        AppConfig* config = wxGetApp().app_config;
        if (config) {
            if (check->GetValue())
                config->set_str("print", param, "1");
            else
                config->set_str("print", param, "0");
        }
    });
    m_checkbox_list[param] = check;
    return checkbox;
}
References Label::Body_13, StateColor::darkModeColorFor(), m_checkbox_list, m_colour_def_color, Slic3r::AppConfig::set_str(), Slic3r::GUI::wxMouseEvent, and wxStaticText.
do_ams_mapping()
bool Slic3r::GUI::SelectMachineDialog::do_ams_mapping (MachineObject * obj_)
{
    if (!obj_) return false;
    // try color and type mapping
    int result = obj_->ams_filament_mapping(m_filaments, m_ams_mapping_result);
    if (result == 0) {
        print_ams_mapping_result(m_ams_mapping_result);
        std::string ams_array;
        std::string mapping_info;
        get_ams_mapping_result(ams_array, mapping_info);
        if (ams_array.empty()) {
            reset_ams_material();
            BOOST_LOG_TRIVIAL(info) << "ams_mapping_array=[]";
        } else {
            sync_ams_mapping_result(m_ams_mapping_result);
            BOOST_LOG_TRIVIAL(info) << "ams_mapping_array=" << ams_array;
        }
        return obj_->is_valid_mapping_result(m_ams_mapping_result);
    } else {
        // do not support ams mapping try to use order mapping
        bool is_valid = obj_->is_valid_mapping_result(m_ams_mapping_result);
        if (result != 1 && !is_valid) {
            //reset invalid result
            for (int i = 0; i < m_ams_mapping_result.size(); i++) {
                m_ams_mapping_result[i].tray_id = -1;
                m_ams_mapping_result[i].distance = 99999;
            }
        }
        sync_ams_mapping_result(m_ams_mapping_result);
           return is_valid;
    }
    return true;
}
References Slic3r::MachineObject::ams_filament_mapping(), get_ams_mapping_result(), Slic3r::MachineObject::is_valid_mapping_result(), m_ams_mapping_result, m_filaments, Slic3r::GUI::print_ams_mapping_result(), reset_ams_material(), and sync_ams_mapping_result().
Referenced by update_show_status().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
Enable_Refresh_Button()
void Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button (bool en) protected
{
    if (!en) {
        if (m_button_refresh->IsEnabled()) {
            m_button_refresh->Disable();
            m_button_refresh->SetBackgroundColor(wxColour(0x90, 0x90, 0x90));
            m_button_refresh->SetBorderColor(wxColour(0x90, 0x90, 0x90));
        }
    } else {
        if (!m_button_refresh->IsEnabled()) {
            m_button_refresh->Enable();
            m_button_refresh->SetBackgroundColor(btn_bg_enable);
            m_button_refresh->SetBorderColor(btn_bg_enable);
        }
    }
}
References btn_bg_enable, Button::Enable(), m_button_refresh, StaticBox::SetBackgroundColor(), and StaticBox::SetBorderColor().
Referenced by show_status().
Enable_Send_Button()
void Slic3r::GUI::SelectMachineDialog::Enable_Send_Button (bool en) protected
{
    if (!en) {
        if (m_button_ensure->IsEnabled()) {
            m_button_ensure->Disable();
            m_button_ensure->SetBackgroundColor(wxColour(0x90, 0x90, 0x90));
            m_button_ensure->SetBorderColor(wxColour(0x90, 0x90, 0x90));
        }
    } else {
        if (!m_button_ensure->IsEnabled()) {
            m_button_ensure->Enable();
            m_button_ensure->SetBackgroundColor(btn_bg_enable);
            m_button_ensure->SetBorderColor(btn_bg_enable);
        }
    }
}
References btn_bg_enable, Button::Enable(), m_button_ensure, StaticBox::SetBackgroundColor(), and StaticBox::SetBorderColor().
Referenced by on_ok(), prepare_mode(), and show_status().
finish_mode()
void Slic3r::GUI::SelectMachineDialog::finish_mode ()
{
    m_is_in_sending_mode = false;
    m_simplebook->SetSelection(2);
    Layout();
    Fit();
}
References m_is_in_sending_mode, and m_simplebook.
Referenced by on_ok().
format_text()
wxString Slic3r::GUI::SelectMachineDialog::format_text (wxString & m_msg) protected
{
    if (wxGetApp().app_config->get("language") != "zh_CN") {return m_msg; }
    wxString out_txt      = m_msg;
    wxString count_txt    = "";
    int      new_line_pos = 0;
    for (int i = 0; i < m_msg.length(); i++) {
        auto text_size = m_statictext_ams_msg->GetTextExtent(count_txt);
        if (text_size.x < (FromDIP(400))) {
            count_txt += m_msg[i];
        } else {
            out_txt.insert(i - 1, '\n');
            count_txt = "";
        }
    }
    return out_txt;
}
References m_statictext_ams_msg.
Referenced by update_ams_status_msg(), and update_priner_status_msg().
get_ams_mapping_result()
bool Slic3r::GUI::SelectMachineDialog::get_ams_mapping_result (std::string & mapping_array_str, std::string & ams_mapping_info)
{
    if (m_ams_mapping_result.empty())
        return false;
    bool valid_mapping_result = true;
    int invalid_count = 0;
    for (int i = 0; i < m_ams_mapping_result.size(); i++) {
        if (m_ams_mapping_result[i].tray_id == -1) {
            valid_mapping_result = false;
            invalid_count++;
        }
    }
    if (invalid_count == m_ams_mapping_result.size()) {
        return false;
    } else {
        json          j = json::array();
        json mapping_info_json = json::array();
        for (int i = 0; i < wxGetApp().preset_bundle->filament_presets.size(); i++) {
            int tray_id = -1;
            json mapping_item;
            mapping_item["ams"] = tray_id;
            mapping_item["targetColor"] = "";
            mapping_item["filamentId"] = "";
            mapping_item["filamentType"] = "";
            for (int k = 0; k < m_ams_mapping_result.size(); k++) {
                if (m_ams_mapping_result[k].id == i) {
                    tray_id = m_ams_mapping_result[k].tray_id;
                    mapping_item["ams"]             = tray_id;
                    mapping_item["filamentType"]    = m_filaments[k].type;
                    auto it = wxGetApp().preset_bundle->filaments.find_preset(wxGetApp().preset_bundle->filament_presets[i]);
                    if (it != nullptr) {
                        mapping_item["filamentId"] = it->filament_id;
                    }
                    //convert #RRGGBB to RRGGBBAA
                    if (m_filaments[k].color.size() > 6) {
                        mapping_item["sourceColor"] = m_filaments[k].color.substr(1, 6) + "FF";
                    } else {
                        mapping_item["sourceColor"]     = m_filaments[k].color;
                    }
                    mapping_item["targetColor"]     = m_ams_mapping_result[k].color;
                }
            }
            j.push_back(tray_id);
            mapping_info_json.push_back(mapping_item);
        }
        mapping_array_str = j.dump();
        ams_mapping_info = mapping_info_json.dump();
        return valid_mapping_result;
    }
    return true;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::array, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_ams_mapping_result, m_filaments, and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::push_back().
Referenced by do_ams_mapping(), and on_ok().
get_status()
PrintDialogStatus Slic3r::GUI::SelectMachineDialog::get_status () inline
{ return m_print_status; }
References m_print_status.
Referenced by update_show_status().
has_tips()
bool Slic3r::GUI::SelectMachineDialog::has_tips (MachineObject * obj)
{
    if (!obj) return false;
    // must set to a status if return true
    if (select_timelapse->IsShown() &&
        m_checkbox_list["timelapse"]->GetValue()) {
        if (obj->get_sdcard_state() == MachineObject::SdcardState::NO_SDCARD) {
            show_status(PrintDialogStatus::PrintStatusTimelapseNoSdcard);
            return true;
        }
    }
    return false;
}
References Slic3r::MachineObject::get_sdcard_state(), m_checkbox_list, Slic3r::MachineObject::NO_SDCARD, Slic3r::GUI::PrintStatusTimelapseNoSdcard, select_timelapse, and show_status().
Referenced by update_show_status().
init_bind()
void Slic3r::GUI::SelectMachineDialog::init_bind () private
{
    Bind(wxEVT_TIMER, &SelectMachineDialog::on_timer, this);
    Bind(EVT_CLEAR_IPADDRESS, &SelectMachineDialog::clear_ip_address_config, this);
}
References clear_ip_address_config(), and on_timer().
init_model()
void Slic3r::GUI::SelectMachineDialog::init_model () private
{
    machine_model = new MachineListModel;
    m_dataViewListCtrl_machines->AssociateModel(machine_model.get());
    m_dataViewListCtrl_machines->AppendTextColumn("Printer Name", MachineListModel::Col_MachineName, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_SORTABLE);
    m_dataViewListCtrl_machines->AppendTextColumn("SN(dev_id)", MachineListModel::Col_MachineSN, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_RESIZABLE);
    m_dataViewListCtrl_machines->AppendTextColumn("Status", MachineListModel::Col_MachinePrintingStatus, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_RESIZABLE);
    m_dataViewListCtrl_machines->AppendTextColumn("TaskName", MachineListModel::Col_MachineTaskName, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_RESIZABLE);
    m_dataViewListCtrl_machines->AppendTextColumn("Connection", MachineListModel::Col_MachineConnection, wxDATAVIEW_CELL_INERT, wxCOL_WIDTH_AUTOSIZE, wxALIGN_NOT,
                                                  wxDATAVIEW_COL_RESIZABLE);
}
References Slic3r::GUI::MachineListModel::Col_MachineConnection, Slic3r::GUI::MachineListModel::Col_MachineName, Slic3r::GUI::MachineListModel::Col_MachinePrintingStatus, Slic3r::GUI::MachineListModel::Col_MachineSN, Slic3r::GUI::MachineListModel::Col_MachineTaskName, m_dataViewListCtrl_machines, and machine_model.
init_timer()
void Slic3r::GUI::SelectMachineDialog::init_timer () private
{
    m_refresh_timer = new wxTimer();
    m_refresh_timer->SetOwner(this);
}
References m_refresh_timer.
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
is_same_printer_model()
bool Slic3r::GUI::SelectMachineDialog::is_same_printer_model ()
{
    bool result = true;
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return result;
    MachineObject* obj_ = dev->get_selected_machine();
    assert(obj_->dev_id == m_printer_last_select);
    if (obj_ == nullptr) {
        return result;
    }
    PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    if (preset_bundle && preset_bundle->printers.get_edited_preset().get_printer_type(preset_bundle) != obj_->printer_type) {
        BOOST_LOG_TRIVIAL(info) << "printer_model: source = " << preset_bundle->printers.get_edited_preset().get_printer_type(preset_bundle);
        BOOST_LOG_TRIVIAL(info) << "printer_model: target = " << obj_->printer_type;
        return false;
    }
    return true;
}
References Slic3r::MachineObject::dev_id, Slic3r::PresetCollection::get_edited_preset(), Slic3r::Preset::get_printer_type(), Slic3r::DeviceManager::get_selected_machine(), m_printer_last_select, Slic3r::MachineObject::printer_type, and Slic3r::PresetBundle::printers.
Referenced by on_ok_btn().
is_show_timelapse()
bool Slic3r::GUI::SelectMachineDialog::is_show_timelapse () protected
{
    auto compare_version = [](const std::string &version1, const std::string &version2) -> bool {
        int i = 0, j = 0;
        int max_size = std::max(version1.size(), version2.size());
        while (i < max_size || j < max_size) {
            int v1 = 0, v2 = 0;
            while (i < version1.size() && version1[i] != '.') v1 = 10 * v1 + (version1[i++] - '0');
            while (j < version2.size() && version2[j] != '.') v2 = 10 * v2 + (version2[j++] - '0');
            if (v1 > v2) return true;
            if (v1 < v2) return false;
            ++i;
            ++j;
        }
        return false;
    };
    std::string standard_version = "01.04.00.00";
    PartPlate *plate      = m_plater->get_partplate_list().get_curr_plate();
    fs::path   gcode_path = plate->get_tmp_gcode_path();
    std::string   line;
    std::ifstream gcode_file;
    gcode_file.open(gcode_path.string());
    if (gcode_file.fail()) {
    } else {
        bool is_version = false;
        while (gcode_file >> line) {
            if (is_version) {
                if (compare_version(standard_version, line)) {
                    gcode_file.close();
                    return false;
                }
                break;
            }
            if (line == "BambuStudio" || line == "OrcaSlicer")
                is_version = true;
        }
    }
    gcode_file.close();
    return true;
}
References Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::PartPlate::get_tmp_gcode_path(), and m_plater.
Referenced by update_select_layout().
is_timeout()
bool Slic3r::GUI::SelectMachineDialog::is_timeout () protected
{
    if (timeout_count > 15 * 1000 / LIST_REFRESH_INTERVAL) {
        return true;
    }
    return false;
}
References LIST_REFRESH_INTERVAL, and timeout_count.
Referenced by update_show_status().
LoadImageFromBlob()
wxImage * Slic3r::GUI::SelectMachineDialog::LoadImageFromBlob (const unsigned char * data, int size) protected
{
    if (data != NULL) {
        wxMemoryInputStream mi(data, size);
        wxImage *           img = new wxImage(mi, wxBITMAP_TYPE_ANY);
        if (img != NULL && img->IsOk()) return img;
        // wxLogDebug( wxT("DB::LoadImageFromBlob error: data=%p size=%d"), data, size);
        // caller is responsible for deleting the pointer
        delete img;
    }
    return NULL;
}
References NULL, and size.
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_cancel()
void Slic3r::GUI::SelectMachineDialog::on_cancel (wxCloseEvent & event) protected
{
    if (m_mapping_popup.IsShown())
        m_mapping_popup.Dismiss();
    if (m_print_job) {
        if (m_print_job->is_running()) {
            m_print_job->cancel();
            m_print_job->join();
        }
    }
    this->EndModal(wxID_CANCEL);
}
References m_mapping_popup, and m_print_job.
Referenced by SelectMachineDialog().
on_dpi_changed()
void Slic3r::GUI::SelectMachineDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    m_button_refresh->SetMinSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_refresh->SetCornerRadius(FromDIP(12));
    m_button_ensure->SetMinSize(SELECT_MACHINE_DIALOG_BUTTON_SIZE);
    m_button_ensure->SetCornerRadius(FromDIP(12));
    m_status_bar->msw_rescale();
    Fit();
    Refresh();
}
References m_button_ensure, m_button_refresh, m_status_bar, SELECT_MACHINE_DIALOG_BUTTON_SIZE, StaticBox::SetCornerRadius(), and Button::SetMinSize().
on_ok()
void Slic3r::GUI::SelectMachineDialog::on_ok () protected
{
    BOOST_LOG_TRIVIAL(info) << "print_job: on_ok to send";
    m_is_canceled = false;
    Enable_Send_Button(false);
    if (m_is_in_sending_mode)
        return;
    int result = 0;
    if (m_printer_last_select.empty()) {
        return;
    }
    DeviceManager *dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    MachineObject *obj_ = dev->get_selected_machine();
    assert(obj_->dev_id == m_printer_last_select);
    if (obj_ == nullptr) {
        return;
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", print_job: for send task, current printer id =  " << m_printer_last_select << std::endl;
    show_status(PrintDialogStatus::PrintStatusSending);
    m_status_bar->reset();
    m_status_bar->set_prog_block();
    m_status_bar->set_cancel_callback_fina([this]() {
        BOOST_LOG_TRIVIAL(info) << "print_job: enter canceled";
        if (m_print_job) {
            if (m_print_job->is_running()) {
                BOOST_LOG_TRIVIAL(info) << "print_job: canceled";
                m_print_job->cancel();
            }
            m_print_job->join();
        }
        m_is_canceled = true;
        wxCommandEvent* event = new wxCommandEvent(EVT_PRINT_JOB_CANCEL);
        wxQueueEvent(this, event);
    });
    if (m_is_canceled) {
        BOOST_LOG_TRIVIAL(info) << "print_job: m_is_canceled";
        m_status_bar->set_status_text(task_canceled_text);
        return;
    }
    // enter sending mode
    sending_mode();
    // get ams_mapping_result
    std::string ams_mapping_array;
    std::string ams_mapping_info;
    if (ams_check->GetValue())
        get_ams_mapping_result(ams_mapping_array, ams_mapping_info);
    else {
        json mapping_info_json = json::array();
        json item;
        if (m_filaments.size() > 0) {
            item["sourceColor"]  = m_filaments[0].color.substr(1, 6) + "FF";
            item["filamentType"] = m_filaments[0].type;
            mapping_info_json.push_back(item);
            ams_mapping_info = mapping_info_json.dump();
        }
    }
    result = m_plater->send_gcode(m_print_plate_idx, [this](int export_stage, int current, int total, bool &cancel) {
        if (this->m_is_canceled) return;
        bool     cancelled = false;
        wxString msg       = _L("Preparing print job");
        m_status_bar->update_status(msg, cancelled, 10, true);
        m_export_3mf_cancel = cancel = cancelled;
    });
    if (m_is_canceled || m_export_3mf_cancel) {
        BOOST_LOG_TRIVIAL(info) << "print_job: m_export_3mf_cancel or m_is_canceled";
        m_status_bar->set_status_text(task_canceled_text);
        return;
    }
    if (result < 0) {
        wxString msg = _L("Abnormal print file data. Please slice again");
        m_status_bar->set_status_text(msg);
        return;
    }
    // export config 3mf if needed
    if (!obj_->is_lan_mode_printer()) {
        result = m_plater->export_config_3mf(m_print_plate_idx);
        if (result < 0) {
            BOOST_LOG_TRIVIAL(trace) << "export_config_3mf failed, result = " << result;
            return;
        }
    }
    if (m_is_canceled || m_export_3mf_cancel) {
        BOOST_LOG_TRIVIAL(info) << "print_job: m_export_3mf_cancel or m_is_canceled";
        m_status_bar->set_status_text(task_canceled_text);
        return;
    }
    m_print_job                = std::make_shared<PrintJob>(m_status_bar, m_plater, m_printer_last_select);
    m_print_job->m_dev_ip      = obj_->dev_ip;
    m_print_job->m_ftp_folder  = obj_->get_ftp_folder();
    m_print_job->m_access_code   = obj_->get_access_code();
    m_print_job->m_local_use_ssl = obj_->local_use_ssl;
    m_print_job->connection_type = obj_->connection_type();
    m_print_job->cloud_print_only= obj_->is_cloud_print_only;
    m_print_job->set_project_name(m_current_project_name.utf8_string());
    if (obj_->is_support_ams_mapping()) {
        m_print_job->task_ams_mapping = ams_mapping_array;
        m_print_job->task_ams_mapping_info = ams_mapping_info;
    } else {
        m_print_job->task_ams_mapping = "";
        m_print_job->task_ams_mapping_info = "";
    }
    m_print_job->has_sdcard = obj_->has_sdcard();
    bool timelapse_option = select_timelapse->IsShown() ? m_checkbox_list["timelapse"]->GetValue() : true;
    m_print_job->set_print_config(
        MachineBedTypeString[0],
        m_checkbox_list["bed_leveling"]->GetValue(),
        m_checkbox_list["flow_cali"]->GetValue(),
        false,
        timelapse_option,
        true);
    if (obj_->has_ams()) {
        m_print_job->task_use_ams = ams_check->GetValue();
    } else {
        m_print_job->task_use_ams = false;
    }
    BOOST_LOG_TRIVIAL(info) << "print_job: timelapse_option = " << timelapse_option;
    BOOST_LOG_TRIVIAL(info) << "print_job: use_ams = " << m_print_job->task_use_ams;
    m_print_job->on_success([this]() { finish_mode(); });
    m_print_job->on_check_ip_address_fail([this]() {
        wxCommandEvent* evt = new wxCommandEvent(EVT_CLEAR_IPADDRESS);
        wxQueueEvent(this, evt);
        wxGetApp().show_ip_address_enter_dialog();
     });
    // update ota version
    NetworkAgent* agent = wxGetApp().getAgent();
    if (agent)
        agent->track_update_property("dev_ota_version", obj_->get_ota_version());
    m_print_job->start();
    BOOST_LOG_TRIVIAL(info) << "print_job: start print job";
}
References _L, ams_check, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::array, Slic3r::MachineObject::connection_type(), Slic3r::MachineObject::dev_id, Slic3r::MachineObject::dev_ip, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), Enable_Send_Button(), Slic3r::GUI::Plater::export_config_3mf(), finish_mode(), Slic3r::MachineObject::get_access_code(), get_ams_mapping_result(), Slic3r::MachineObject::get_ftp_folder(), Slic3r::MachineObject::get_ota_version(), Slic3r::DeviceManager::get_selected_machine(), Slic3r::MachineObject::has_ams(), Slic3r::MachineObject::has_sdcard(), Slic3r::MachineObject::is_cloud_print_only, Slic3r::MachineObject::is_lan_mode_printer(), Slic3r::MachineObject::is_support_ams_mapping(), Slic3r::MachineObject::local_use_ssl, m_checkbox_list, m_current_project_name, m_export_3mf_cancel, m_filaments, m_is_canceled, m_is_in_sending_mode, m_plater, m_print_job, m_print_plate_idx, m_printer_last_select, m_status_bar, Slic3r::GUI::MachineBedTypeString, Slic3r::GUI::PrintStatusSending, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::push_back(), select_timelapse, Slic3r::GUI::Plater::send_gcode(), sending_mode(), show_status(), Slic3r::GUI::task_canceled_text, Slic3r::trace(), and Slic3r::NetworkAgent::track_update_property().
Referenced by on_ok_btn().
on_ok_btn()
void Slic3r::GUI::SelectMachineDialog::on_ok_btn (wxCommandEvent & event) protected
{
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    MachineObject* obj_ = dev->get_selected_machine();
    if (!obj_) return;
    std::vector<wxString> confirm_text;
    confirm_text.push_back(_L("Please check the following:") + "\n\n");
#if 1
    //Check Printer Model Id
    bool is_same_printer_type = is_same_printer_model();
    if (!is_same_printer_type)
        confirm_text.push_back(_L("The printer type selected when generating G-Code is not consistent with the currently selected printer. It is recommended that you use the same printer type for slicing.") + "\n");
#else
    bool is_same_printer_type = true;
#endif
    //Check slice warnings
    bool has_slice_warnings = false;
    PartPlate* plate = m_plater->get_partplate_list().get_curr_plate();
    for (auto warning : plate->get_slice_result()->warnings) {
        if (warning.msg == BED_TEMP_TOO_HIGH_THAN_FILAMENT) {
            if ((obj_->printer_type == "BL-P001" || obj_->printer_type == "BL-P002")) {
                confirm_text.push_back(Plater::get_slice_warning_string(warning) + "\n");
                has_slice_warnings = true;
            }
        }
        else {
            wxString error_info = Plater::get_slice_warning_string(warning);
            if (error_info.IsEmpty()) {
                error_info = wxString::Format("%s\n", warning.msg);
                confirm_text.push_back(error_info + "\n");
            } else
                confirm_text.push_back(error_info + "\n");
            has_slice_warnings = true;
        }
    }
    //check for unidentified material
    auto mapping_result = m_mapping_popup.parse_ams_mapping(obj_->amsList);
    auto has_unknown_filament = false;
    // check if ams mapping is has errors, tpu
    bool has_prohibited_filament = false;
    wxString prohibited_error = wxEmptyString;
    for (auto i = 0; i < m_ams_mapping_result.size(); i++) {
        auto tid = m_ams_mapping_result[i].tray_id;
        std::string filament_type = boost::to_upper_copy(m_ams_mapping_result[i].type);
        std::string filament_brand;
        for (auto fs : m_filaments) {
            if (fs.id == m_ams_mapping_result[i].id) {
                filament_brand = boost::to_upper_copy(m_filaments[i].brand);
            }
        }
        if (filament_type == "TPU") {
            has_prohibited_filament = true;
            prohibited_error = wxString::Format(_L("%s is not supported by AMS."), "TPU");
        }else if (filament_type == "PET-CF" && filament_brand == "BAMBULAB") {
            has_prohibited_filament = true;
            prohibited_error = wxString::Format(_L("%s is not supported by AMS."), "PET-CF");
        }else if (filament_type == "PA6-CF" && filament_brand == "BAMBULAB") {
            has_prohibited_filament = true;
            prohibited_error = wxString::Format(_L("%s is not supported by AMS."), "PA6-CF");
        }
        for (auto miter : mapping_result) {
            //matching
            if (miter.id == tid) {
                if (miter.type == TrayType::THIRD || miter.type == TrayType::EMPTY) {
                    has_unknown_filament = true;
                    break;
                }
            }
        }
    }
    if (has_prohibited_filament && obj_->has_ams() && ams_check->GetValue()) {
        wxString tpu_tips = prohibited_error;
        show_errors(tpu_tips);
        return;
    }
    if (has_unknown_filament) {
        has_slice_warnings = true;
        confirm_text.push_back(_L("There are some unknown filaments in the AMS mappings. Please check whether they are the required filaments. If they are okay, press \"Confirm\" to start printing.") + "\n");
    }
    if (!is_same_printer_type || has_slice_warnings) {
        wxString confirm_title = _L("Warning");
        ConfirmBeforeSendDialog confirm_dlg(this, wxID_ANY, confirm_title);
        confirm_dlg.Bind(EVT_SECONDARY_CHECK_CONFIRM, [this, &confirm_dlg](wxCommandEvent& e) {
            confirm_dlg.on_hide();
            this->on_ok();
        });
        confirm_text.push_back(_L("Please click the confirm button if you still want to proceed with printing.") + "\n");
        wxString info_msg = wxEmptyString;
        for (auto i = 0; i < confirm_text.size(); i++) {
            if (i == 0) {
                info_msg += confirm_text[i];
            }
            else if (i == confirm_text.size() - 1) {
                info_msg += confirm_text[i];
            }
            else {
                info_msg += wxString::Format("%d. %s\n",i, confirm_text[i]);
            }
        }
        confirm_dlg.update_text(info_msg);
        confirm_dlg.on_show();
    } else {
        this->on_ok();
    }
}
References _L, ams_check, Slic3r::MachineObject::amsList, BED_TEMP_TOO_HIGH_THAN_FILAMENT, Slic3r::GUI::EMPTY, Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::DeviceManager::get_selected_machine(), Slic3r::GUI::PartPlate::get_slice_result(), Slic3r::GUI::Plater::get_slice_warning_string(), Slic3r::MachineObject::has_ams(), is_same_printer_model(), m_ams_mapping_result, m_filaments, m_mapping_popup, m_plater, Slic3r::GUI::ConfirmBeforeSendDialog::on_hide(), on_ok(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::AmsMapingPopup::parse_ams_mapping(), Slic3r::MachineObject::printer_type, show_errors(), Slic3r::GUI::THIRD, Slic3r::GUI::ConfirmBeforeSendDialog::update_text(), and Slic3r::GCodeProcessorResult::warnings.
on_print_job_cancel()
void Slic3r::GUI::SelectMachineDialog::on_print_job_cancel (wxCommandEvent & evt) protected
{
    BOOST_LOG_TRIVIAL(info) << "print_job: canceled";
    show_status(PrintDialogStatus::PrintStatusSendingCanceled);
    // enter prepare mode
    prepare_mode();
}
References prepare_mode(), Slic3r::GUI::PrintStatusSendingCanceled, and show_status().
on_refresh()
void Slic3r::GUI::SelectMachineDialog::on_refresh (wxCommandEvent & event) protected
{
    BOOST_LOG_TRIVIAL(info) << "m_printer_last_select: on_refresh";
    show_status(PrintDialogStatus::PrintStatusRefreshingMachineList);
    update_user_machine_list();
}
References Slic3r::GUI::PrintStatusRefreshingMachineList, show_status(), and update_user_machine_list().
on_rename_click()
void Slic3r::GUI::SelectMachineDialog::on_rename_click (wxCommandEvent & event) protected
{
    m_is_rename_mode = true;
    m_rename_input->GetTextCtrl()->SetValue(m_current_project_name);
    m_rename_switch_panel->SetSelection(1);
    m_rename_input->GetTextCtrl()->SetFocus();
    m_rename_input->GetTextCtrl()->SetInsertionPointEnd();
}
References TextInput::GetTextCtrl(), m_current_project_name, m_is_rename_mode, m_rename_input, and m_rename_switch_panel.
Referenced by SelectMachineDialog().
on_rename_enter()
void Slic3r::GUI::SelectMachineDialog::on_rename_enter () protected
{
    if (m_is_rename_mode == false){
        return;
    }
    else {
        m_is_rename_mode = false;
    }
    auto     new_file_name = m_rename_input->GetTextCtrl()->GetValue();
    auto     m_valid_type = Valid;
    wxString info_line;
    const char* unusable_symbols = "<>[]:/\\|?*\"";
    const std::string unusable_suffix = PresetCollection::get_suffix_modified(); //"(modified)";
    for (size_t i = 0; i < std::strlen(unusable_symbols); i++) {
        if (new_file_name.find_first_of(unusable_symbols[i]) != std::string::npos) {
            info_line = _L("Name is invalid;") + "\n" + _L("illegal characters:") + " " + unusable_symbols;
            m_valid_type = NoValid;
            break;
        }
    }
    if (m_valid_type == Valid && new_file_name.find(unusable_suffix) != std::string::npos) {
        info_line = _L("Name is invalid;") + "\n" + _L("illegal suffix:") + "\n\t" + from_u8(PresetCollection::get_suffix_modified());
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.empty()) {
        info_line = _L("The name is not allowed to be empty.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.find_first_of(' ') == 0) {
        info_line = _L("The name is not allowed to start with space character.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && new_file_name.find_last_of(' ') == new_file_name.length() - 1) {
        info_line = _L("The name is not allowed to end with space character.");
        m_valid_type = NoValid;
    }
    if (m_valid_type != Valid) {
        MessageDialog msg_wingow(nullptr, info_line, "", wxICON_WARNING | wxOK);
        if (msg_wingow.ShowModal() == wxID_OK) {
             m_rename_switch_panel->SetSelection(0);
             m_rename_text->SetLabel(m_current_project_name);
             m_rename_normal_panel->Layout();
             return;
        }
    }
    m_current_project_name = new_file_name;
    m_rename_switch_panel->SetSelection(0);
    m_rename_text->SetLabel(m_current_project_name);
    m_rename_normal_panel->Layout();
}
References _L, Slic3r::GUI::from_u8(), Slic3r::PresetCollection::get_suffix_modified(), TextInput::GetTextCtrl(), m_current_project_name, m_is_rename_mode, m_rename_input, m_rename_normal_panel, m_rename_switch_panel, m_rename_text, NoValid, Slic3r::GUI::DPIAware< P >::ShowModal(), and Valid.
Referenced by SelectMachineDialog(), and check_focus().
on_selection_changed()
void Slic3r::GUI::SelectMachineDialog::on_selection_changed (wxCommandEvent & event) protected
{
    /* reset timeout and reading printer info */
    m_status_bar->reset();
    timeout_count      = 0;
    m_ams_mapping_res  = false;
    ams_mapping_valid  = false;
    m_ams_mapping_result.clear();
    auto selection = m_comboBox_printer->GetSelection();
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    MachineObject* obj = nullptr;
    for (int i = 0; i < m_list.size(); i++) {
        if (i == selection) {
            //check lan mode machine
            if (m_list[i]->is_lan_mode_printer() && !m_list[i]->has_access_right()) {
                ConnectPrinterDialog dlg(wxGetApp().mainframe, wxID_ANY, _L("Input access code"));
                dlg.set_machine_object(m_list[i]);
                auto res = dlg.ShowModal();
                m_printer_last_select = "";
                m_comboBox_printer->SetSelection(-1);
                m_comboBox_printer->Refresh();
                m_comboBox_printer->Update();
            }
            m_printer_last_select = m_list[i]->dev_id;
            obj = m_list[i];
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "for send task, current printer id =  " << m_printer_last_select << std::endl;
            break;
        }
    }
    if (obj && !obj->get_lan_mode_connection_state()) {
        obj->command_get_version();
        obj->command_request_push_all();
        dev->set_selected_machine(m_printer_last_select, true);
        // Has changed machine unrecoverably
        GUI::wxGetApp().sidebar().load_ams_list(obj->dev_id, obj->amsList);
        update_select_layout(obj);
    } else {
        BOOST_LOG_TRIVIAL(error) << "on_selection_changed dev_id not found";
        return;
    }
    reset_ams_material();
    update_show_status();
}
References _L, ams_mapping_valid, Slic3r::MachineObject::amsList, Slic3r::MachineObject::command_get_version(), Slic3r::MachineObject::command_request_push_all(), Slic3r::MachineObject::dev_id, error, Slic3r::MachineObject::get_lan_mode_connection_state(), ComboBox::GetSelection(), m_ams_mapping_res, m_ams_mapping_result, m_comboBox_printer, m_list, m_printer_last_select, m_status_bar, reset_ams_material(), Slic3r::GUI::ConnectPrinterDialog::set_machine_object(), Slic3r::DeviceManager::set_selected_machine(), ComboBox::SetSelection(), Slic3r::GUI::DPIAware< P >::ShowModal(), timeout_count, update_select_layout(), and update_show_status().
on_set_finish_mapping()
void Slic3r::GUI::SelectMachineDialog::on_set_finish_mapping (wxCommandEvent & evt) protected
{
    auto selection_data = evt.GetString();
    auto selection_data_arr = wxSplit(selection_data.ToStdString(), '|');
    BOOST_LOG_TRIVIAL(info) << "The ams mapping selection result: data is " << selection_data;
    if (selection_data_arr.size() == 5) {
         for (auto i = 0; i < m_ams_mapping_result.size(); i++) {
            if (m_ams_mapping_result[i].id == wxAtoi(selection_data_arr[4])) {
                m_ams_mapping_result[i].tray_id = evt.GetInt();
        auto ams_colour = wxColour(wxAtoi(selection_data_arr[0]), wxAtoi(selection_data_arr[1]), wxAtoi(selection_data_arr[2]));
        auto color = wxString::Format("%sFF", ams_colour.GetAsString(wxC2S_HTML_SYNTAX).substr(1, ams_colour.GetAsString(wxC2S_HTML_SYNTAX).size()-1));
         m_ams_mapping_result[i].color = color.ToStdString();
            }
            BOOST_LOG_TRIVIAL(trace) << "The ams mapping result: id is " << m_ams_mapping_result[i].id << "tray_id is " << m_ams_mapping_result[i].tray_id;
         }
        MaterialHash::iterator iter = m_materialList.begin();
        while (iter != m_materialList.end()) {
            Material*        item = iter->second;
            MaterialItem *m  = item->item;
            if (item->id == m_current_filament_id) {
                auto ams_colour = wxColour(wxAtoi(selection_data_arr[0]), wxAtoi(selection_data_arr[1]), wxAtoi(selection_data_arr[2]));
                m->set_ams_info(ams_colour, selection_data_arr[3]);
            }
            iter++;
        }
    }
}
References Slic3r::GUI::Material::id, Slic3r::GUI::Material::item, m_ams_mapping_result, m_current_filament_id, m_materialList, Slic3r::GUI::MaterialItem::set_ams_info(), and Slic3r::trace().
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
on_timer()
void Slic3r::GUI::SelectMachineDialog::on_timer (wxTimerEvent & event) protected
{
    wxGetApp().reset_to_active();
    update_show_status();
}
References update_show_status().
Referenced by init_bind().
popup_filament_backup()
void Slic3r::GUI::SelectMachineDialog::popup_filament_backup ()
{
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    if (dev->get_selected_machine() && dev->get_selected_machine()->filam_bak.size() > 0) {
        AmsReplaceMaterialDialog* m_replace_material_popup = new AmsReplaceMaterialDialog(this);
        m_replace_material_popup->update_machine_obj(dev->get_selected_machine());
        m_replace_material_popup->ShowModal();
    }
}
References Slic3r::MachineObject::filam_bak, Slic3r::DeviceManager::get_selected_machine(), Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::GUI::AmsReplaceMaterialDialog::update_machine_obj().
prepare()
void Slic3r::GUI::SelectMachineDialog::prepare (int print_plate_idx)
{
    m_print_plate_idx = print_plate_idx;
}
References m_print_plate_idx.
prepare_mode()
void Slic3r::GUI::SelectMachineDialog::prepare_mode ()
{
    // disable combobox
    m_comboBox_printer->Enable();
    m_is_in_sending_mode = false;
    if (m_print_job) {
        m_print_job->join();
    }
    if (wxIsBusy())
        wxEndBusyCursor();
    Enable_Send_Button(true);
    m_status_bar->reset();
    if (m_simplebook->GetSelection() != 0) {
        m_simplebook->SetSelection(0);
        Layout();
        Fit();
    }
}
References Enable_Send_Button(), m_comboBox_printer, m_is_in_sending_mode, m_print_job, m_simplebook, and m_status_bar.
Referenced by clear_ip_address_config(), on_print_job_cancel(), and show_status().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
reset_ams_material()
void Slic3r::GUI::SelectMachineDialog::reset_ams_material () protected
{
    MaterialHash::iterator iter = m_materialList.begin();
    while (iter != m_materialList.end()) {
        int           id = iter->first;
        Material* item = iter->second;
        MaterialItem* m = item->item;
        wxString ams_id = "-";
        wxColour ams_col = wxColour(0xEE, 0xEE, 0xEE);
        m->set_ams_info(ams_col, ams_id);
        iter++;
    }
}
References Slic3r::GUI::Material::item, m_materialList, and Slic3r::GUI::MaterialItem::set_ams_info().
Referenced by do_ams_mapping(), on_selection_changed(), and set_default().
reset_timeout()
void Slic3r::GUI::SelectMachineDialog::reset_timeout () protected
{
    timeout_count = 0;
}
References timeout_count.
Referenced by update_show_status().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
sending_mode()
void Slic3r::GUI::SelectMachineDialog::sending_mode ()
{
    // disable combobox
    m_comboBox_printer->Disable();
    m_is_in_sending_mode = true;
    if (m_simplebook->GetSelection() != 1){
        m_simplebook->SetSelection(1);
        Layout();
        Fit();
    }
}
References m_comboBox_printer, m_is_in_sending_mode, and m_simplebook.
Referenced by on_ok(), and show_status().
set_default()
void Slic3r::GUI::SelectMachineDialog::set_default () protected
{
    //project name
    m_rename_switch_panel->SetSelection(0);
    wxString filename = m_plater->get_export_gcode_filename("", false,
        m_print_plate_idx == PLATE_ALL_IDX ?true:false);
    if (m_print_plate_idx == PLATE_ALL_IDX && filename.empty()) {
        filename = _L("Untitled");
    }
    if (filename.empty()) {
        filename = m_plater->get_export_gcode_filename("", true);
    }
    fs::path filename_path(filename.c_str());
    m_current_project_name = wxString::FromUTF8(filename_path.filename().string());
    m_rename_text->SetLabelText(m_current_project_name);
    m_rename_normal_panel->Layout();
    //clear combobox
    m_list.clear();
    m_comboBox_printer->Clear();
    m_printer_last_select = "";
    m_print_info = "";
    m_comboBox_printer->SetValue(wxEmptyString);
    m_comboBox_printer->Enable();
    // rset status bar
    m_status_bar->reset();
    NetworkAgent* agent = wxGetApp().getAgent();
    if (agent) {
        if (agent->is_user_login()) {
            show_status(PrintDialogStatus::PrintStatusInit);
        } else {
            show_status(PrintDialogStatus::PrintStatusNoUserLogin);
        }
    }
    select_bed->Show();
    select_flow->Show();
    // load checkbox values from app config
    AppConfig* config = wxGetApp().app_config;
    if (config && config->get("print", "bed_leveling") == "0") {
        m_checkbox_list["bed_leveling"]->SetValue(false);
    } else {
        m_checkbox_list["bed_leveling"]->SetValue(true);
    }
    if (config && config->get("print", "flow_cali") == "0") {
        m_checkbox_list["flow_cali"]->SetValue(false);
    } else {
        m_checkbox_list["flow_cali"]->SetValue(true);
    }
    if (config && config->get("print", "timelapse") == "0") {
        m_checkbox_list["timelapse"]->SetValue(false);
    } else {
        m_checkbox_list["timelapse"]->SetValue(true);
    }
    ams_check->SetValue(true);
    // thumbmail
    //wxBitmap bitmap;
    ThumbnailData &data   = m_plater->get_partplate_list().get_curr_plate()->thumbnail_data;
    if (data.is_valid()) {
        wxImage image(data.width, data.height);
        image.InitAlpha();
        for (unsigned int r = 0; r < data.height; ++r) {
            unsigned int rr = (data.height - 1 - r) * data.width;
            for (unsigned int c = 0; c < data.width; ++c) {
                unsigned char *px = (unsigned char *) data.pixels.data() + 4 * (rr + c);
                image.SetRGB((int) c, (int) r, px[0], px[1], px[2]);
                image.SetAlpha((int) c, (int) r, px[3]);
            }
        }
        image  = image.Rescale(FromDIP(256), FromDIP(256));
        m_thumbnailPanel->set_thumbnail(image);
        //bitmap = wxBitmap(image);
    }
    //m_staticbitmap->SetBitmap(bitmap);
    //sizer_thumbnail->Layout();
    std::vector<std::string> materials;
    std::vector<std::string> brands;
    std::vector<std::string> display_materials;
    {
        auto preset_bundle = wxGetApp().preset_bundle;
        for (auto filament_name : preset_bundle->filament_presets) {
            for (auto iter = preset_bundle->filaments.lbegin(); iter != preset_bundle->filaments.end(); iter++) {
                if (filament_name.compare(iter->name) == 0) {
                    std::string display_filament_type;
                    std::string filament_type = iter->config.get_filament_type(display_filament_type);
                    display_materials.push_back(display_filament_type);
                    materials.push_back(filament_type);
                    if (iter->vendor && !iter->vendor->name.empty())
                        brands.push_back(iter->vendor->name);
                    else
                        brands.push_back("");
                }
            }
        }
    }
    // material info
    auto        extruders = wxGetApp().plater()->get_partplate_list().get_curr_plate()->get_used_extruders();
    BitmapCache bmcache;
    MaterialHash::iterator iter = m_materialList.begin();
    while (iter != m_materialList.end()) {
        int       id   = iter->first;
        Material *item = iter->second;
        item->item->Destroy();
        delete item;
        iter++;
    }
    m_sizer_material->Clear();
    m_materialList.clear();
    m_filaments.clear();
    for (auto i = 0; i < extruders.size(); i++) {
        auto          extruder = extruders[i] - 1;
        auto          colour   = wxGetApp().preset_bundle->project_config.opt_string("filament_colour", (unsigned int) extruder);
        unsigned char rgb[3];
        bmcache.parse_color(colour, rgb);
        auto          colour_rgb = wxColour((int) rgb[0], (int) rgb[1], (int) rgb[2]);
        if (extruder >= materials.size() || extruder < 0 || extruder >= display_materials.size())
            continue;
       /* if (m_materialList.size() == 0) {
            auto tips_panel = new wxPanel(m_scrollable_region, wxID_ANY);
            tips_panel->SetSize(wxSize(60,40));
            tips_panel->SetMinSize(wxSize(60,40));
            tips_panel->SetMaxSize(wxSize(60,40));
            tips_panel->SetBackgroundColour(*wxRED);
            m_sizer_material->Add(tips_panel, 0, wxALL, FromDIP(4));
        }*/
        MaterialItem *item = new MaterialItem(m_scrollable_region, colour_rgb, _L(display_materials[extruder]));
        m_sizer_material->Add(item, 0, wxALL, FromDIP(4));
        item->Bind(wxEVT_LEFT_UP, [this, item, materials, extruder](wxMouseEvent &e) {
        });
        item->Bind(wxEVT_LEFT_DOWN, [this, item, materials, extruder](wxMouseEvent &e) {
            MaterialHash::iterator iter = m_materialList.begin();
            while (iter != m_materialList.end()) {
                int           id   = iter->first;
                Material *    item = iter->second;
                MaterialItem *m    = item->item;
                m->on_normal();
                iter++;
            }
            m_current_filament_id = extruder;
            item->on_selected();
            auto    mouse_pos = ClientToScreen(e.GetPosition());
            wxPoint rect      = item->ClientToScreen(wxPoint(0, 0));
            // update ams data
            DeviceManager *dev_manager = Slic3r::GUI::wxGetApp().getDeviceManager();
            if (!dev_manager) return;
            MachineObject *obj_ = dev_manager->get_selected_machine();
            if (obj_ && obj_->is_support_ams_mapping()) {
                if (m_mapping_popup.IsShown()) return;
                wxPoint pos = item->ClientToScreen(wxPoint(0, 0));
                pos.y += item->GetRect().height;
                m_mapping_popup.Move(pos);
                if (obj_ &&
                    obj_->has_ams() &&
                    ams_check->GetValue() &&
                    obj_->dev_id == m_printer_last_select)
                {
                    m_mapping_popup.set_parent_item(item);
                    m_mapping_popup.set_current_filament_id(extruder);
                    m_mapping_popup.set_tag_texture(materials[extruder]);
                    m_mapping_popup.update_ams_data(obj_->amsList);
                    m_mapping_popup.Popup();
                }
            }
        });
        Material *material_item = new Material();
        material_item->id       = extruder;
        material_item->item     = item;
        m_materialList[i]       = material_item;
        // build for ams mapping
        if (extruder < materials.size() && extruder >= 0) {
            FilamentInfo info;
            info.id    = extruder;
            info.type  = materials[extruder];
            info.brand = brands[extruder];
            info.color = colour_rgb.GetAsString(wxC2S_HTML_SYNTAX).ToStdString();
            m_filaments.push_back(info);
        }
    }
    if (extruders.size() <= 4) {
        m_sizer_material->SetCols(extruders.size());
    } else {
        m_sizer_material->SetCols(4);
    }
    m_scrollable_region->Layout();
    m_scrollable_region->Fit();
    //m_scrollable_view->Layout();
    //m_scrollable_view->Fit();
    m_scrollable_view->SetSize(m_scrollable_region->GetSize());
    m_scrollable_view->SetMinSize(m_scrollable_region->GetSize());
    m_scrollable_view->SetMaxSize(m_scrollable_region->GetSize());
    Layout();
    Fit();
    wxSize screenSize = wxGetDisplaySize();
    auto dialogSize = this->GetSize();
    #ifdef __WINDOWS__
    if (screenSize.y < dialogSize.y) {
        m_need_adaptation_screen = true;
        m_scrollable_view->SetScrollRate(0, 5);
        m_scrollable_view->SetSize(wxSize(-1, FromDIP(220)));
        m_scrollable_view->SetMinSize(wxSize(-1, FromDIP(220)));
        m_scrollable_view->SetMaxSize(wxSize(-1, FromDIP(220)));
    } else {
        /* m_scrollable_view->SetSize(m_scrollable_region->GetSize());
         m_scrollable_view->SetMinSize(m_scrollable_region->GetSize());
         m_scrollable_view->SetMaxSize(m_scrollable_region->GetSize());*/
        m_scrollable_view->SetScrollRate(0, 0);
    }
    #endif // __WXOSX_MAC__
    reset_ams_material();
    // basic info
    auto       aprint_stats = m_plater->get_partplate_list().get_current_fff_print().print_statistics();
    wxString   time;
    PartPlate *plate = m_plater->get_partplate_list().get_curr_plate();
    if (plate) {
        if (plate->get_slice_result()) { time = wxString::Format("%s", short_time(get_time_dhms(plate->get_slice_result()->print_statistics.modes[0].time))); }
    }
    char weight[64];
    ::sprintf(weight, "  %.2f g", aprint_stats.total_weight);
    m_stext_time->SetLabel(time);
    m_stext_weight->SetLabel(weight);
}
References _L, ams_check, Slic3r::MachineObject::amsList, Slic3r::FilamentInfo::brand, Slic3r::FilamentInfo::color, Slic3r::MachineObject::dev_id, Slic3r::AppConfig::get(), Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::PartPlateList::get_current_fff_print(), Slic3r::GUI::Plater::get_export_gcode_filename(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::DeviceManager::get_selected_machine(), Slic3r::GUI::PartPlate::get_slice_result(), Slic3r::get_time_dhms(), Slic3r::MachineObject::has_ams(), Slic3r::ThumbnailData::height, Slic3r::FilamentInfo::id, Slic3r::GUI::Material::id, int, Slic3r::MachineObject::is_support_ams_mapping(), Slic3r::NetworkAgent::is_user_login(), Slic3r::ThumbnailData::is_valid(), Slic3r::GUI::Material::item, m_checkbox_list, m_comboBox_printer, m_current_filament_id, m_current_project_name, m_filaments, m_list, m_mapping_popup, m_materialList, m_need_adaptation_screen, m_plater, m_print_info, m_print_plate_idx, m_printer_last_select, m_rename_normal_panel, m_rename_switch_panel, m_rename_text, m_scrollable_region, m_scrollable_view, m_sizer_material, m_status_bar, m_stext_time, m_stext_weight, m_thumbnailPanel, Slic3r::PrintEstimatedStatistics::modes, Slic3r::GUI::MaterialItem::on_selected(), Slic3r::GUI::BitmapCache::parse_color(), Slic3r::ThumbnailData::pixels, PLATE_ALL_IDX, Slic3r::GCodeProcessorResult::print_statistics, Slic3r::Print::print_statistics(), Slic3r::GUI::PrintStatusInit, Slic3r::GUI::PrintStatusNoUserLogin, reset_ams_material(), select_bed, select_flow, Slic3r::GUI::AmsMapingPopup::set_current_filament_id(), Slic3r::GUI::AmsMapingPopup::set_parent_item(), Slic3r::GUI::AmsMapingPopup::set_tag_texture(), Slic3r::GUI::ThumbnailPanel::set_thumbnail(), ComboBox::SetValue(), Slic3r::short_time(), show_status(), Slic3r::GUI::PartPlate::thumbnail_data, Slic3r::FilamentInfo::type, Slic3r::GUI::AmsMapingPopup::update_ams_data(), Slic3r::ThumbnailData::width, and Slic3r::GUI::wxMouseEvent.
Referenced by Show().
Show()
bool Slic3r::GUI::SelectMachineDialog::Show (bool show)
{
    show_status(PrintDialogStatus::PrintStatusInit);
    // set default value when show this dialog
    if (show) {
        wxGetApp().UpdateDlgDarkUI(this);
        wxGetApp().reset_to_active();
        set_default();
        update_user_machine_list();
        //update_lan_machine_list();
    }
    if (show) {
        m_refresh_timer->Start(LIST_REFRESH_INTERVAL);
    } else {
        m_refresh_timer->Stop();
    }
    Layout();
    Fit();
    if (show) { CenterOnParent(); }
    return DPIDialog::Show(show);
}
References LIST_REFRESH_INTERVAL, m_refresh_timer, Slic3r::GUI::PrintStatusInit, set_default(), show_status(), and update_user_machine_list().
show_errors()
void Slic3r::GUI::SelectMachineDialog::show_errors (wxString & info) protected
{
    ConfirmBeforeSendDialog confirm_dlg(this, wxID_ANY, _L("Errors"));
    confirm_dlg.update_text(info);
    confirm_dlg.on_show();
}
References _L, Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), and Slic3r::GUI::ConfirmBeforeSendDialog::update_text().
Referenced by on_ok_btn().
show_status()
void Slic3r::GUI::SelectMachineDialog::show_status (PrintDialogStatus status, std::vector< wxString > params = std::vector<wxString>())
{
    if (m_print_status != status)
        BOOST_LOG_TRIVIAL(info) << "select_machine_dialog: show_status = " << status << "(" << get_print_status_info(status) << ")";
    m_print_status = status;
    // m_comboBox_printer
    if (status == PrintDialogStatus::PrintStatusRefreshingMachineList)
        m_comboBox_printer->Disable();
    else
        m_comboBox_printer->Enable();
    // m_panel_warn m_simplebook
    if (status == PrintDialogStatus::PrintStatusSending) {
        sending_mode();
    } else {
        prepare_mode();
    }
    // other
    if (status == PrintDialogStatus::PrintStatusInit) {
        update_print_status_msg(wxEmptyString, false, false);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusNoUserLogin) {
        wxString msg_text = _L("No login account, only printers in LAN mode are displayed");
        update_print_status_msg(msg_text, false, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    }else if (status == PrintDialogStatus::PrintStatusInvalidPrinter) {
        update_print_status_msg(wxEmptyString, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusConnectingServer) {
        wxString msg_text = _L("Connecting to server");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusReading) {
        wxString msg_text = _L("Synchronizing device information");
        update_print_status_msg(msg_text, false, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusReadingFinished) {
        update_print_status_msg(wxEmptyString, false, true);
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusReadingTimeout) {
        wxString msg_text = _L("Synchronizing device information time out");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusInUpgrading) {
        wxString msg_text = _L("Cannot send the print job when the printer is updating firmware");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusInSystemPrinting) {
        wxString msg_text = _L("The printer is executing instructions. Please restart printing after it ends");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusInPrinting) {
        wxString msg_text = _L("The printer is busy on other print job");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusDisableAms) {
        update_print_status_msg(wxEmptyString, false, false);
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusNeedUpgradingAms) {
        wxString msg_text;
        if (params.size() > 0)
            msg_text = wxString::Format(_L("Filament %s exceeds the number of AMS slots. Please update the printer firmware to support AMS slot assignment."), params[0]);
        else
            msg_text = _L("Filament exceeds the number of AMS slots. Please update the printer firmware to support AMS slot assignment.");
        update_print_status_msg(msg_text, true, false);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusAmsMappingSuccess){
        wxString msg_text = _L("Filaments to AMS slots mappings have been established. You can click a filament above to change its mapping AMS slot");
        update_print_status_msg(msg_text, false, false);
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusAmsMappingInvalid) {
        wxString msg_text = _L("Please click each filament above to specify its mapping AMS slot before sending the print job");
        update_print_status_msg(msg_text, true, false);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusAmsMappingU0Invalid) {
        wxString msg_text;
        if (params.size() > 1)
            msg_text = wxString::Format(_L("Filament %s does not match the filament in AMS slot %s. Please update the printer firmware to support AMS slot assignment."), params[0], params[1]);
        else
            msg_text = _L("Filament does not match the filament in AMS slot. Please update the printer firmware to support AMS slot assignment.");
        update_print_status_msg(msg_text, true, false);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusAmsMappingValid) {
        wxString msg_text = _L("Filaments to AMS slots mappings have been established. You can click a filament above to change its mapping AMS slot");
        update_print_status_msg(msg_text, false, false);
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusRefreshingMachineList) {
        update_print_status_msg(wxEmptyString, false, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(false);
    } else if (status == PrintDialogStatus::PrintStatusSending) {
        Enable_Send_Button(false);
        Enable_Refresh_Button(false);
    } else if (status == PrintDialogStatus::PrintStatusSendingCanceled) {
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusLanModeNoSdcard) {
        wxString msg_text = _L("An SD card needs to be inserted before printing via LAN.");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusAmsMappingByOrder) {
        wxString msg_text = _L("The printer firmware only supports sequential mapping of filament => AMS slot.");
        update_print_status_msg(msg_text, false, false);
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusNoSdcard) {
        wxString msg_text = _L("An SD card needs to be inserted before printing.");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusTimelapseNoSdcard) {
        wxString msg_text = _L("An SD card needs to be inserted to record timelapse.");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(true);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusNeedForceUpgrading) {
        wxString msg_text = _L("Cannot send the print job to a printer whose firmware is required to get updated.");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusNeedConsistencyUpgrading) {
        wxString msg_text = _L("Cannot send the print job to a printer whose firmware is required to get updated.");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusBlankPlate) {
        wxString msg_text = _L("Cannot send the print job for empty plate");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    } else if (status == PrintDialogStatus::PrintStatusNotSupportedPrintAll) {
        wxString msg_text = _L("This printer does not support printing all plates");
        update_print_status_msg(msg_text, true, true);
        Enable_Send_Button(false);
        Enable_Refresh_Button(true);
    }
}
References _L, Enable_Refresh_Button(), Enable_Send_Button(), Slic3r::GUI::get_print_status_info(), m_comboBox_printer, m_print_status, prepare_mode(), Slic3r::GUI::PrintStatusAmsMappingByOrder, Slic3r::GUI::PrintStatusAmsMappingInvalid, Slic3r::GUI::PrintStatusAmsMappingSuccess, Slic3r::GUI::PrintStatusAmsMappingU0Invalid, Slic3r::GUI::PrintStatusAmsMappingValid, Slic3r::GUI::PrintStatusBlankPlate, Slic3r::GUI::PrintStatusConnectingServer, Slic3r::GUI::PrintStatusDisableAms, Slic3r::GUI::PrintStatusInit, Slic3r::GUI::PrintStatusInPrinting, Slic3r::GUI::PrintStatusInSystemPrinting, Slic3r::GUI::PrintStatusInUpgrading, Slic3r::GUI::PrintStatusInvalidPrinter, Slic3r::GUI::PrintStatusLanModeNoSdcard, Slic3r::GUI::PrintStatusNeedConsistencyUpgrading, Slic3r::GUI::PrintStatusNeedForceUpgrading, Slic3r::GUI::PrintStatusNeedUpgradingAms, Slic3r::GUI::PrintStatusNoSdcard, Slic3r::GUI::PrintStatusNotSupportedPrintAll, Slic3r::GUI::PrintStatusNoUserLogin, Slic3r::GUI::PrintStatusReading, Slic3r::GUI::PrintStatusReadingFinished, Slic3r::GUI::PrintStatusReadingTimeout, Slic3r::GUI::PrintStatusRefreshingMachineList, Slic3r::GUI::PrintStatusSending, Slic3r::GUI::PrintStatusSendingCanceled, Slic3r::GUI::PrintStatusTimelapseNoSdcard, sending_mode(), and update_print_status_msg().
Referenced by has_tips(), on_ok(), on_print_job_cancel(), on_refresh(), set_default(), Show(), update_printer_combobox(), and update_show_status().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
sort_string()
std::vector< std::string > Slic3r::GUI::SelectMachineDialog::sort_string (std::vector< std::string > strArray) protected
{
    std::vector<std::string> outputArray;
    std::sort(strArray.begin(), strArray.end());
    std::vector<std::string>::iterator st;
    for (st = strArray.begin(); st != strArray.end(); st++) { outputArray.push_back(*st); }
    return outputArray;
}
Referenced by update_user_printer().
stripWhiteSpace()
void Slic3r::GUI::SelectMachineDialog::stripWhiteSpace (std::string & str) protected
{
    if (str == "") { return; }
    string::iterator cur_it;
    cur_it = str.begin();
    while (cur_it != str.end()) {
        if ((*cur_it) == '\n' || (*cur_it) == ' ') {
            cur_it = str.erase(cur_it);
        }
        else {
            cur_it++;
        }
    }
}
Referenced by update_ams_status_msg(), and update_priner_status_msg().
sync_ams_mapping_result()
void Slic3r::GUI::SelectMachineDialog::sync_ams_mapping_result (std::vector< FilamentInfo > & result)
{
    if (result.empty()) {
        BOOST_LOG_TRIVIAL(trace) << "ams_mapping result is empty";
        for (auto it = m_materialList.begin(); it != m_materialList.end(); it++) {
            wxString ams_id = "-";
            wxColour ams_col = wxColour(0xCE, 0xCE, 0xCE);
            it->second->item->set_ams_info(ams_col, ams_id);
        }
        return;
    }
    for (auto f = result.begin(); f != result.end(); f++) {
        BOOST_LOG_TRIVIAL(trace) << "ams_mapping f id = " << f->id << ", tray_id = " << f->tray_id << ", color = " << f->color << ", type = " << f->type;
        MaterialHash::iterator iter = m_materialList.begin();
        while (iter != m_materialList.end()) {
            int           id   = iter->second->id;
            Material *    item = iter->second;
            MaterialItem *m    = item->item;
            if (f->id == id) {
                wxString ams_id;
                wxColour ams_col;
                if (f->tray_id >= 0) {
                    ams_id = wxGetApp().transition_tridid(f->tray_id);
                    //ams_id = wxString::Format("%02d", f->tray_id + 1);
                } else {
                    ams_id = "-";
                }
                if (!f->color.empty()) {
                    ams_col = AmsTray::decode_color(f->color);
                } else {
                    // default color
                    ams_col = wxColour(0xCE, 0xCE, 0xCE);
                }
                m->set_ams_info(ams_col, ams_id);
                break;
            }
            iter++;
        }
    }
}
References Slic3r::AmsTray::decode_color(), Slic3r::f(), Slic3r::GUI::Material::item, m_materialList, Slic3r::GUI::MaterialItem::set_ams_info(), and Slic3r::trace().
Referenced by do_ams_mapping(), and update_show_status().
sys_color_changed()
void Slic3r::GUI::SelectMachineDialog::sys_color_changed ()
{
    if (wxGetApp(). dark_mode()) {
        m_rename_button->SetIcon("ams_editable_light");
    }
    else {
        m_rename_button->SetIcon("ams_editable");
    }
    m_rename_button->Refresh();
}
References m_rename_button, and Button::SetIcon().
update_ams_check()
void Slic3r::GUI::SelectMachineDialog::update_ams_check (MachineObject * obj) protected
{
    if (obj && obj->is_function_supported(FUNC_USE_AMS)
        && obj->ams_support_use_ams
        && obj->has_ams()) {
        select_use_ams->Show();
        auto use_ams_str = wxGetApp().app_config->get("bbl_machine", "use_ams");
        if(!use_ams_str.empty())
            ams_check->SetValue(use_ams_str == "1" || use_ams_str == "true");
    } else {
        select_use_ams->Hide();
    }
}
References ams_check, Slic3r::MachineObject::ams_support_use_ams, Slic3r::FUNC_USE_AMS, Slic3r::MachineObject::has_ams(), Slic3r::MachineObject::is_function_supported(), and select_use_ams.
Referenced by update_show_status().
update_ams_status_msg()
void Slic3r::GUI::SelectMachineDialog::update_ams_status_msg (wxString msg, bool is_warning = false) protected
{
    auto colour = is_warning ? wxColour(0xFF, 0x6F, 0x00):wxColour(0x6B, 0x6B, 0x6B);
    m_statictext_ams_msg->SetForegroundColour(colour);
    if (msg.empty()) {
        if (!m_statictext_ams_msg->GetLabel().empty()) {
            m_statictext_ams_msg->SetLabel(wxEmptyString);
            m_statictext_ams_msg->Hide();
            Layout();
            Fit();
        }
    } else {
        msg = format_text(msg);
        auto str_new = msg.ToStdString();
        stripWhiteSpace(str_new);
        auto str_old = m_statictext_ams_msg->GetLabel().ToStdString();
        stripWhiteSpace(str_old);
        if (str_new != str_old) {
            if (m_statictext_ams_msg->GetLabel() != msg) {
                m_statictext_ams_msg->SetLabel(msg);
                m_statictext_ams_msg->SetMinSize(wxSize(FromDIP(400), -1));
                m_statictext_ams_msg->SetMaxSize(wxSize(FromDIP(400), -1));
                m_statictext_ams_msg->Wrap(FromDIP(400));
                m_statictext_ams_msg->Show();
                Layout();
                Fit();
            }
        }
    }
}
References format_text(), m_statictext_ams_msg, and stripWhiteSpace().
Referenced by update_print_status_msg().
update_lan_machine_list()
void Slic3r::GUI::SelectMachineDialog::update_lan_machine_list () protected
{
    DeviceManager* dev = wxGetApp().getDeviceManager();
    if (!dev) return;
   auto  m_free_machine_list = dev->get_local_machine_list();
    BOOST_LOG_TRIVIAL(trace) << "SelectMachinePopup update_other_devices start";
    for (auto& elem : m_free_machine_list) {
        MachineObject* mobj = elem.second;
        /* do not show printer bind state is empty */
        if (!mobj->is_avaliable()) continue;
        if (!mobj->is_online()) continue;
        if (!mobj->is_lan_mode_printer()) continue;
        /*if (mobj->is_in_printing()) {op->set_printer_state(PrinterState::BUSY);}*/
        if (mobj->has_access_right()) {
                auto b = mobj->dev_name;
                // clear machine list
                //m_comboBox_printer->Clear();
                std::vector<std::string>              machine_list;
                wxArrayString                         machine_list_name;
                std::map<std::string, MachineObject*> option_list;
                // same machine only appear once
               /* machine_list = sort_string(machine_list);
                for (auto tt = machine_list.begin(); tt != machine_list.end(); tt++) {
                    for (auto it = option_list.begin(); it != option_list.end(); it++) {
                        if (it->second->dev_name == *tt) {
                            m_list.push_back(it->second);
                            wxString dev_name_text = from_u8(it->second->dev_name);
                            if (it->second->is_lan_mode_printer()) {
                                dev_name_text += "(LAN)";
                            }
                            machine_list_name.Add(dev_name_text);
                            break;
                        }
                    }
                }
                m_comboBox_printer->Set(machine_list_name);
                MachineObject* obj = dev->get_selected_machine();
                if (obj) {
                    m_printer_last_select = obj->dev_id;
                }
                else {
                    m_printer_last_select = "";
                }*/
                //op->set_printer_state(PrinterState::LOCK);
            }
    }
    BOOST_LOG_TRIVIAL(trace) << "SelectMachineDialog update_lan_devices end";
}
References Slic3r::MachineObject::dev_name, Slic3r::DeviceManager::get_local_machine_list(), Slic3r::MachineObject::has_access_right(), Slic3r::MachineObject::is_avaliable(), Slic3r::MachineObject::is_lan_mode_printer(), Slic3r::MachineObject::is_online(), and Slic3r::trace().
update_priner_status_msg()
void Slic3r::GUI::SelectMachineDialog::update_priner_status_msg (wxString msg, bool is_warning = false) protected
{
    auto colour = is_warning ? wxColour(0xFF, 0x6F, 0x00) : wxColour(0x6B, 0x6B, 0x6B);
    m_statictext_printer_msg->SetForegroundColour(colour);
    if (msg.empty()) {
        if (!m_statictext_printer_msg->GetLabel().empty()) {
            m_statictext_printer_msg->SetLabel(wxEmptyString);
            m_statictext_printer_msg->Hide();
            Layout();
            Fit();
        }
    } else {
        msg          = format_text(msg);
        auto str_new = msg.ToStdString();
        stripWhiteSpace(str_new);
        auto str_old = m_statictext_printer_msg->GetLabel().ToStdString();
        stripWhiteSpace(str_old);
        if (str_new != str_old) {
            if (m_statictext_printer_msg->GetLabel() != msg) {
                m_statictext_printer_msg->SetLabel(msg);
                m_statictext_printer_msg->SetMinSize(wxSize(FromDIP(400), -1));
                m_statictext_printer_msg->SetMaxSize(wxSize(FromDIP(400), -1));
                m_statictext_printer_msg->Wrap(FromDIP(400));
                m_statictext_printer_msg->Show();
                Layout();
                Fit();
            }
        }
    }
}
References format_text(), m_statictext_printer_msg, and stripWhiteSpace().
Referenced by update_print_status_msg().
update_print_status_msg()
void Slic3r::GUI::SelectMachineDialog::update_print_status_msg (wxString msg, bool is_warning = false, bool is_printer = true) protected
{
    if (is_printer_msg) {
        update_ams_status_msg(wxEmptyString, false);
        update_priner_status_msg(msg, is_warning);
    } else {
        update_ams_status_msg(msg, is_warning);
        update_priner_status_msg(wxEmptyString, false);
    }
}
References update_ams_status_msg(), and update_priner_status_msg().
Referenced by show_status().
update_printer_combobox()
void Slic3r::GUI::SelectMachineDialog::update_printer_combobox (wxCommandEvent & event) protected
{
    show_status(PrintDialogStatus::PrintStatusInit);
    update_user_printer();
}
References Slic3r::GUI::PrintStatusInit, show_status(), and update_user_printer().
update_select_layout()
void Slic3r::GUI::SelectMachineDialog::update_select_layout (MachineObject * obj)
{
    if (obj && obj->is_function_supported(PrinterFunction::FUNC_FLOW_CALIBRATION)) {
        select_flow->Show();
        auto flow_cali_str = wxGetApp().app_config->get("bbl_machine", "flow_cali");
        if(!flow_cali_str.empty())
            m_checkbox_list["flow_cali"]->SetValue(flow_cali_str == "1" || flow_cali_str == "true");
    } else {
        select_flow->Hide();
    }
    if (obj && obj->is_function_supported(PrinterFunction::FUNC_AUTO_LEVELING)) {
        select_bed->Show();
        auto bed_leveling_str = wxGetApp().app_config->get("bbl_machine", "bed_leveling");
        if(!bed_leveling_str.empty())
            m_checkbox_list["bed_leveling"]->SetValue(bed_leveling_str == "1" || bed_leveling_str == "true");
    } else {
        select_bed->Hide();
    }
    if (obj && obj->is_function_supported(PrinterFunction::FUNC_TIMELAPSE)
        && obj->is_support_print_with_timelapse()
        && is_show_timelapse()) {
        select_timelapse->Show();
        auto timelapse_str = wxGetApp().app_config->get("bbl_machine", "timelapse");
        if(!timelapse_str.empty())
            m_checkbox_list["timelapse"]->SetValue(timelapse_str == "1" || timelapse_str == "true");
    } else {
        select_timelapse->Hide();
    }
    m_sizer_select->Layout();
    Fit();
}
References Slic3r::FUNC_AUTO_LEVELING, Slic3r::FUNC_FLOW_CALIBRATION, Slic3r::FUNC_TIMELAPSE, Slic3r::MachineObject::is_function_supported(), is_show_timelapse(), Slic3r::MachineObject::is_support_print_with_timelapse(), m_checkbox_list, m_sizer_select, select_bed, select_flow, and select_timelapse.
Referenced by on_selection_changed(), and update_user_printer().
update_show_status()
void Slic3r::GUI::SelectMachineDialog::update_show_status () protected
{
    // refreshing return
    if (get_status() == PrintDialogStatus::PrintStatusRefreshingMachineList)
        return;
    if (get_status() == PrintDialogStatus::PrintStatusSending)
        return;
    if (get_status() == PrintDialogStatus::PrintStatusSendingCanceled)
        return;
    NetworkAgent* agent = Slic3r::GUI::wxGetApp().getAgent();
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!agent) {
        update_ams_check(nullptr);
        return;
    }
    if (!dev) return;
    dev->check_pushing();
    PartPlate* plate = m_plater->get_partplate_list().get_curr_plate();
    // blank plate has no valid gcode file
    if (plate&& !plate->is_valid_gcode_file()) {
        show_status(PrintDialogStatus::PrintStatusBlankPlate);
        return;
    }
    MachineObject* obj_ = dev->get_my_machine(m_printer_last_select);
    if (!obj_) {
        update_ams_check(nullptr);
        if (agent) {
            if (agent->is_user_login()) {
                show_status(PrintDialogStatus::PrintStatusInvalidPrinter);
            }
            else {
                show_status(PrintDialogStatus::PrintStatusNoUserLogin);
            }
        }
        return;
    }
    /* check cloud machine connections */
    if (!obj_->is_lan_mode_printer()) {
        if (!agent->is_server_connected()) {
            agent->refresh_connection();
            show_status(PrintDialogStatus::PrintStatusConnectingServer);
            reset_timeout();
            return;
        }
    }
    if (!obj_->is_info_ready()) {
        if (is_timeout()) {
            m_ams_mapping_result.clear();
            sync_ams_mapping_result(m_ams_mapping_result);
            show_status(PrintDialogStatus::PrintStatusReadingTimeout);
            return;
        }
        else {
            timeout_count++;
            show_status(PrintDialogStatus::PrintStatusReading);
            return;
        }
        return;
    }
    reset_timeout();
    update_ams_check(obj_);
    if (!obj_->is_function_supported(PrinterFunction::FUNC_PRINT_ALL) && m_print_plate_idx == PLATE_ALL_IDX) {
        show_status(PrintDialogStatus::PrintStatusNotSupportedPrintAll);
        return;
    }
    // do ams mapping if no ams result
    bool clean_ams_mapping = false;
    if (obj_->has_ams() && m_ams_mapping_result.empty()) {
        if (obj_->ams_support_use_ams) {
            if (ams_check->GetValue()) {
                do_ams_mapping(obj_);
            } else {
                clean_ams_mapping = true;
            }
        }
    }
    if (!obj_->has_ams() || !ams_check->GetValue()) {
        clean_ams_mapping = true;
    }
    if (clean_ams_mapping) {
        m_ams_mapping_result.clear();
        sync_ams_mapping_result(m_ams_mapping_result);
    }
    // reading done
    if (wxGetApp().app_config && wxGetApp().app_config->get("internal_debug").empty()) {
        if (obj_->upgrade_force_upgrade) {
            show_status(PrintDialogStatus::PrintStatusNeedForceUpgrading);
            return;
        }
        if (obj_->upgrade_consistency_request) {
            show_status(PrintStatusNeedConsistencyUpgrading);
            return;
        }
    }
    if (obj_->is_in_upgrading()) {
        show_status(PrintDialogStatus::PrintStatusInUpgrading);
        return;
    }
    else if (obj_->is_system_printing()) {
        show_status(PrintDialogStatus::PrintStatusInSystemPrinting);
        return;
    }
    else if (obj_->is_in_printing()) {
        show_status(PrintDialogStatus::PrintStatusInPrinting);
        return;
    }
    else if (!obj_->is_function_supported(PrinterFunction::FUNC_PRINT_WITHOUT_SD) && (obj_->get_sdcard_state() == MachineObject::SdcardState::NO_SDCARD)) {
        show_status(PrintDialogStatus::PrintStatusNoSdcard);
        return;
    }
    // check sdcard when if lan mode printer
    if (obj_->is_lan_mode_printer()) {
        if (obj_->get_sdcard_state() == MachineObject::SdcardState::NO_SDCARD) {
            show_status(PrintDialogStatus::PrintStatusLanModeNoSdcard);
            return;
        }
    }
    // no ams
    if (!obj_->has_ams() || !ams_check->GetValue()) {
        if (!has_tips(obj_))
            show_status(PrintDialogStatus::PrintStatusReadingFinished);
        return;
    }
    if (obj_->ams_support_use_ams) {
        if (!ams_check->GetValue()) {
            m_ams_mapping_result.clear();
            sync_ams_mapping_result(m_ams_mapping_result);
            show_status(PrintDialogStatus::PrintStatusDisableAms);
            return;
        }
    }
    // do ams mapping if no ams result
    if (m_ams_mapping_result.empty()) {
        do_ams_mapping(obj_);
    }
    if (!obj_->is_support_ams_mapping()) {
        int exceed_index = -1;
        if (obj_->is_mapping_exceed_filament(m_ams_mapping_result, exceed_index)) {
            std::vector<wxString> params;
            params.push_back(wxString::Format("%02d", exceed_index+1));
            show_status(PrintDialogStatus::PrintStatusNeedUpgradingAms, params);
        } else {
            if (obj_->is_valid_mapping_result(m_ams_mapping_result)) {
                show_status(PrintDialogStatus::PrintStatusAmsMappingByOrder);
            } else {
                int mismatch_index = -1;
                for (int i = 0; i < m_ams_mapping_result.size(); i++) {
                    if (m_ams_mapping_result[i].mapping_result == MappingResult::MAPPING_RESULT_TYPE_MISMATCH) {
                        mismatch_index = m_ams_mapping_result[i].id;
                        break;
                    }
                }
                std::vector<wxString> params;
                if (mismatch_index >= 0) {
                    params.push_back(wxString::Format("%02d", mismatch_index+1));
                    params.push_back(wxString::Format("%02d", mismatch_index+1));
                }
                show_status(PrintDialogStatus::PrintStatusAmsMappingU0Invalid, params);
            }
        }
        return;
    }
    if (m_ams_mapping_res) {
        show_status(PrintDialogStatus::PrintStatusAmsMappingSuccess);
        return;
    }
    else {
        if (obj_->is_valid_mapping_result(m_ams_mapping_result)) {
            if (!has_tips(obj_))
                show_status(PrintDialogStatus::PrintStatusAmsMappingValid);
            return;
        }
        else {
            show_status(PrintDialogStatus::PrintStatusAmsMappingInvalid);
            return;
        }
    }
}
References ams_check, Slic3r::MachineObject::ams_support_use_ams, Slic3r::DeviceManager::check_pushing(), do_ams_mapping(), Slic3r::FUNC_PRINT_ALL, Slic3r::FUNC_PRINT_WITHOUT_SD, Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::DeviceManager::get_my_machine(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::MachineObject::get_sdcard_state(), get_status(), Slic3r::MachineObject::has_ams(), has_tips(), Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_in_printing(), Slic3r::MachineObject::is_in_upgrading(), Slic3r::MachineObject::is_info_ready(), Slic3r::MachineObject::is_lan_mode_printer(), Slic3r::MachineObject::is_mapping_exceed_filament(), Slic3r::NetworkAgent::is_server_connected(), Slic3r::MachineObject::is_support_ams_mapping(), Slic3r::MachineObject::is_system_printing(), is_timeout(), Slic3r::NetworkAgent::is_user_login(), Slic3r::GUI::PartPlate::is_valid_gcode_file(), Slic3r::MachineObject::is_valid_mapping_result(), m_ams_mapping_res, m_ams_mapping_result, m_plater, m_print_plate_idx, m_printer_last_select, Slic3r::MAPPING_RESULT_TYPE_MISMATCH, Slic3r::MachineObject::NO_SDCARD, PLATE_ALL_IDX, Slic3r::GUI::PrintStatusAmsMappingByOrder, Slic3r::GUI::PrintStatusAmsMappingInvalid, Slic3r::GUI::PrintStatusAmsMappingSuccess, Slic3r::GUI::PrintStatusAmsMappingU0Invalid, Slic3r::GUI::PrintStatusAmsMappingValid, Slic3r::GUI::PrintStatusBlankPlate, Slic3r::GUI::PrintStatusConnectingServer, Slic3r::GUI::PrintStatusDisableAms, Slic3r::GUI::PrintStatusInPrinting, Slic3r::GUI::PrintStatusInSystemPrinting, Slic3r::GUI::PrintStatusInUpgrading, Slic3r::GUI::PrintStatusInvalidPrinter, Slic3r::GUI::PrintStatusLanModeNoSdcard, Slic3r::GUI::PrintStatusNeedConsistencyUpgrading, Slic3r::GUI::PrintStatusNeedForceUpgrading, Slic3r::GUI::PrintStatusNeedUpgradingAms, Slic3r::GUI::PrintStatusNoSdcard, Slic3r::GUI::PrintStatusNotSupportedPrintAll, Slic3r::GUI::PrintStatusNoUserLogin, Slic3r::GUI::PrintStatusReading, Slic3r::GUI::PrintStatusReadingFinished, Slic3r::GUI::PrintStatusReadingTimeout, Slic3r::GUI::PrintStatusRefreshingMachineList, Slic3r::GUI::PrintStatusSending, Slic3r::GUI::PrintStatusSendingCanceled, Slic3r::NetworkAgent::refresh_connection(), reset_timeout(), show_status(), sync_ams_mapping_result(), timeout_count, update_ams_check(), Slic3r::MachineObject::upgrade_consistency_request, and Slic3r::MachineObject::upgrade_force_upgrade.
Referenced by on_selection_changed(), and on_timer().
update_user_machine_list()
void Slic3r::GUI::SelectMachineDialog::update_user_machine_list () protected
{
    NetworkAgent* m_agent = wxGetApp().getAgent();
    if (m_agent && m_agent->is_user_login()) {
        boost::thread get_print_info_thread = Slic3r::create_thread([&] {
            NetworkAgent* agent = wxGetApp().getAgent();
            unsigned int http_code;
            std::string body;
            int result = agent->get_user_print_info(&http_code, &body);
            if (result == 0) {
                m_print_info = body;
            }
            else {
                m_print_info = "";
            }
            wxCommandEvent event(EVT_UPDATE_USER_MACHINE_LIST);
            event.SetEventObject(this);
            wxPostEvent(this, event);
        });
    } else {
        wxCommandEvent event(EVT_UPDATE_USER_MACHINE_LIST);
        event.SetEventObject(this);
        wxPostEvent(this, event);
    }
}
References Slic3r::create_thread(), Slic3r::NetworkAgent::get_user_print_info(), Slic3r::NetworkAgent::is_user_login(), and m_print_info.
Referenced by on_refresh(), and Show().
update_user_printer()
void Slic3r::GUI::SelectMachineDialog::update_user_printer () protected
{
    Slic3r::DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    // update user print info
    if (!m_print_info.empty()) {
        dev->parse_user_print_info(m_print_info);
        m_print_info = "";
    }
    // clear machine list
    m_list.clear();
    m_comboBox_printer->Clear();
    std::vector<std::string>              machine_list;
    wxArrayString                         machine_list_name;
    std::map<std::string, MachineObject*> option_list;
    //user machine list
    option_list = dev->get_my_machine_list();
    // same machine only appear once
    for (auto it = option_list.begin(); it != option_list.end(); it++) {
        if (it->second && (it->second->is_online() || it->second->is_connected())) {
            machine_list.push_back(it->second->dev_name);
        }
    }
    //lan machine list
    auto lan_option_list = dev->get_local_machine_list();
    for (auto elem : lan_option_list) {
        MachineObject* mobj = elem.second;
        /* do not show printer bind state is empty */
        if (!mobj->is_avaliable()) continue;
        if (!mobj->is_online()) continue;
        if (!mobj->is_lan_mode_printer()) continue;
        /*if (mobj->is_in_printing()) {op->set_printer_state(PrinterState::BUSY);}*/
        if (!mobj->has_access_right()) {
            option_list[mobj->dev_name] = mobj;
            machine_list.push_back(mobj->dev_name);
        }
    }
    machine_list = sort_string(machine_list);
    for (auto tt = machine_list.begin(); tt != machine_list.end(); tt++) {
        for (auto it = option_list.begin(); it != option_list.end(); it++) {
            if (it->second->dev_name == *tt) {
                m_list.push_back(it->second);
                wxString dev_name_text = from_u8(it->second->dev_name);
                if (it->second->is_lan_mode_printer()) {
                    dev_name_text += "(LAN)";
                }
                machine_list_name.Add(dev_name_text);
                break;
            }
        }
    }
    m_comboBox_printer->Set(machine_list_name);
    MachineObject* obj = dev->get_selected_machine();
    if (obj) {
        if (obj->is_lan_mode_printer() && !obj->has_access_right()) {
            m_printer_last_select = "";
        }
        else {
           m_printer_last_select = obj->dev_id;
        }
    } else {
        m_printer_last_select = "";
    }
    if (m_list.size() > 0) {
        // select a default machine
        if (m_printer_last_select.empty()) {
            int def_selection = -1;
            for (int i = 0; i < m_list.size(); i++) {
                if (m_list[i]->is_lan_mode_printer() && !m_list[i]->has_access_right()) {
                    continue;
                }
                else {
                    def_selection = i;
                }
            }
            if (def_selection >= 0) {
                m_printer_last_select = m_list[def_selection]->dev_id;
                m_comboBox_printer->SetSelection(def_selection);
                wxCommandEvent event(wxEVT_COMBOBOX);
                event.SetEventObject(m_comboBox_printer);
                wxPostEvent(m_comboBox_printer, event);
            }
        }
        for (auto i = 0; i < m_list.size(); i++) {
            if (m_list[i]->dev_id == m_printer_last_select) {
                if (obj && !obj->get_lan_mode_connection_state()) {
                    m_comboBox_printer->SetSelection(i);
                    wxCommandEvent event(wxEVT_COMBOBOX);
                    event.SetEventObject(m_comboBox_printer);
                    wxPostEvent(m_comboBox_printer, event);
                }
            }
        }
    }
    else {
        m_printer_last_select = "";
        update_select_layout(nullptr);
        m_comboBox_printer->SetTextLabel("");
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "for send task, current printer id =  " << m_printer_last_select << std::endl;
}
References Slic3r::MachineObject::dev_id, Slic3r::MachineObject::dev_name, Slic3r::GUI::from_u8(), Slic3r::MachineObject::get_lan_mode_connection_state(), Slic3r::DeviceManager::get_local_machine_list(), Slic3r::DeviceManager::get_my_machine_list(), Slic3r::DeviceManager::get_selected_machine(), Slic3r::MachineObject::has_access_right(), Slic3r::MachineObject::is_avaliable(), Slic3r::MachineObject::is_lan_mode_printer(), Slic3r::MachineObject::is_online(), m_comboBox_printer, m_list, m_print_info, m_printer_last_select, Slic3r::DeviceManager::parse_user_print_info(), ComboBox::SetSelection(), ComboBox::SetTextLabel(), sort_string(), and update_select_layout().
Referenced by update_printer_combobox().
Member Data Documentation
ams_check
CheckBox* Slic3r::GUI::SelectMachineDialog::ams_check {nullptr} protected
Referenced by create_ams_checkbox(), on_ok(), on_ok_btn(), set_default(), update_ams_check(), and update_show_status().
ams_mapping_valid
bool Slic3r::GUI::SelectMachineDialog::ams_mapping_valid { false } protected
Referenced by on_selection_changed().
btn_bg_enable
StateColor Slic3r::GUI::SelectMachineDialog::btn_bg_enable protected
Referenced by Enable_Refresh_Button(), and Enable_Send_Button().
m_ams_mapping_res
bool Slic3r::GUI::SelectMachineDialog::m_ams_mapping_res { false } protected
Referenced by on_selection_changed(), and update_show_status().
m_ams_mapping_result
std::vector<FilamentInfo> Slic3r::GUI::SelectMachineDialog::m_ams_mapping_result protected
Referenced by do_ams_mapping(), get_ams_mapping_result(), on_ok_btn(), on_selection_changed(), on_set_finish_mapping(), and update_show_status().
m_bedtype_list
std::vector<wxString> Slic3r::GUI::SelectMachineDialog::m_bedtype_list private
Referenced by SelectMachineDialog().
m_button_cancel
wxButton* Slic3r::GUI::SelectMachineDialog::m_button_cancel {nullptr} protected
m_button_ensure
Button* Slic3r::GUI::SelectMachineDialog::m_button_ensure {nullptr} protected
Referenced by Enable_Send_Button(), and on_dpi_changed().
m_button_refresh
Button* Slic3r::GUI::SelectMachineDialog::m_button_refresh {nullptr} protected
Referenced by Enable_Refresh_Button(), and on_dpi_changed().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_checkbox_list
std::map<std::string, ::CheckBox *> Slic3r::GUI::SelectMachineDialog::m_checkbox_list private
Referenced by create_item_checkbox(), has_tips(), on_ok(), set_default(), and update_select_layout().
m_colour_bold_color
wxColour Slic3r::GUI::SelectMachineDialog::m_colour_bold_color {wxColour(38, 46, 48)} private
m_colour_def_color
wxColour Slic3r::GUI::SelectMachineDialog::m_colour_def_color {wxColour(255, 255, 255)} private
Referenced by SelectMachineDialog(), create_ams_checkbox(), and create_item_checkbox().
m_comboBox_bed
::ComboBox* Slic3r::GUI::SelectMachineDialog::m_comboBox_bed {nullptr} protected
m_comboBox_printer
::ComboBox* Slic3r::GUI::SelectMachineDialog::m_comboBox_printer {nullptr} protected
Referenced by on_selection_changed(), prepare_mode(), sending_mode(), set_default(), show_status(), and update_user_printer().
m_current_filament_id
int Slic3r::GUI::SelectMachineDialog::m_current_filament_id protected
Referenced by on_set_finish_mapping(), and set_default().
m_current_project_name
wxString Slic3r::GUI::SelectMachineDialog::m_current_project_name protected
Referenced by on_ok(), on_rename_click(), on_rename_enter(), and set_default().
m_dataViewListCtrl_machines
wxDataViewCtrl* Slic3r::GUI::SelectMachineDialog::m_dataViewListCtrl_machines {nullptr} protected
Referenced by init_model().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_export_3mf_cancel
bool Slic3r::GUI::SelectMachineDialog::m_export_3mf_cancel {false}
Referenced by on_ok().
m_filaments
std::vector<FilamentInfo> Slic3r::GUI::SelectMachineDialog::m_filaments protected
Referenced by do_ams_mapping(), get_ams_mapping_result(), on_ok(), on_ok_btn(), and set_default().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_gauge_job_progress
wxGauge* Slic3r::GUI::SelectMachineDialog::m_gauge_job_progress {nullptr} protected
m_hyperlink_add_machine
wxHyperlinkCtrl* Slic3r::GUI::SelectMachineDialog::m_hyperlink_add_machine {nullptr} protected
m_is_canceled
bool Slic3r::GUI::SelectMachineDialog::m_is_canceled { false }
Referenced by on_ok().
m_is_in_sending_mode
bool Slic3r::GUI::SelectMachineDialog::m_is_in_sending_mode { false } protected
Referenced by finish_mode(), on_ok(), prepare_mode(), and sending_mode().
m_is_rename_mode
bool Slic3r::GUI::SelectMachineDialog::m_is_rename_mode {false} protected
Referenced by on_rename_click(), and on_rename_enter().
m_line_materia
wxPanel* Slic3r::GUI::SelectMachineDialog::m_line_materia {nullptr} protected
m_line_schedule
wxPanel* Slic3r::GUI::SelectMachineDialog::m_line_schedule {nullptr} protected
m_line_top
wxPanel* Slic3r::GUI::SelectMachineDialog::m_line_top {nullptr} protected
Referenced by SelectMachineDialog().
m_list
std::vector<MachineObject *> Slic3r::GUI::SelectMachineDialog::m_list protected
Referenced by on_selection_changed(), set_default(), and update_user_printer().
m_mapping_popup
AmsMapingPopup Slic3r::GUI::SelectMachineDialog::m_mapping_popup {nullptr} protected
Referenced by on_cancel(), on_ok_btn(), and set_default().
m_mapping_tip_popup
AmsMapingTipPopup Slic3r::GUI::SelectMachineDialog::m_mapping_tip_popup {nullptr} protected
Referenced by create_ams_checkbox().
m_mapping_tutorial_popup
AmsTutorialPopup Slic3r::GUI::SelectMachineDialog::m_mapping_tutorial_popup {nullptr} protected
m_materialList
MaterialHash Slic3r::GUI::SelectMachineDialog::m_materialList protected
Referenced by on_set_finish_mapping(), reset_ams_material(), set_default(), and sync_ams_mapping_result().
m_need_adaptation_screen
bool Slic3r::GUI::SelectMachineDialog::m_need_adaptation_screen {false} protected
Referenced by set_default().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_panel_finish
wxPanel* Slic3r::GUI::SelectMachineDialog::m_panel_finish {nullptr} protected
m_panel_image
wxPanel* Slic3r::GUI::SelectMachineDialog::m_panel_image {nullptr} protected
m_panel_prepare
wxPanel* Slic3r::GUI::SelectMachineDialog::m_panel_prepare {nullptr} protected
m_panel_sending
wxPanel* Slic3r::GUI::SelectMachineDialog::m_panel_sending {nullptr} protected
m_panel_status
wxPanel* Slic3r::GUI::SelectMachineDialog::m_panel_status {nullptr} protected
m_plater
Plater* Slic3r::GUI::SelectMachineDialog::m_plater {nullptr} protected
Referenced by is_show_timelapse(), on_ok(), on_ok_btn(), set_default(), and update_show_status().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_print_info
std::string Slic3r::GUI::SelectMachineDialog::m_print_info protected
Referenced by set_default(), update_user_machine_list(), and update_user_printer().
m_print_job
std::shared_ptr<PrintJob> Slic3r::GUI::SelectMachineDialog::m_print_job protected
Referenced by on_cancel(), on_ok(), and prepare_mode().
m_print_plate_idx
int Slic3r::GUI::SelectMachineDialog::m_print_plate_idx private
Referenced by on_ok(), prepare(), set_default(), and update_show_status().
m_print_status
PrintDialogStatus Slic3r::GUI::SelectMachineDialog::m_print_status { PrintStatusInit } private
Referenced by get_status(), and show_status().
m_printer_last_select
std::string Slic3r::GUI::SelectMachineDialog::m_printer_last_select private
Referenced by is_same_printer_model(), on_ok(), on_selection_changed(), set_default(), update_show_status(), and update_user_printer().
m_refresh_timer
wxTimer* Slic3r::GUI::SelectMachineDialog::m_refresh_timer { nullptr } protected
Referenced by ~SelectMachineDialog(), init_timer(), and Show().
m_rename_button
Button* Slic3r::GUI::SelectMachineDialog::m_rename_button {nullptr} protected
Referenced by SelectMachineDialog(), and sys_color_changed().
m_rename_input
TextInput* Slic3r::GUI::SelectMachineDialog::m_rename_input {nullptr} protected
Referenced by SelectMachineDialog(), check_focus(), on_rename_click(), and on_rename_enter().
m_rename_normal_panel
wxPanel* Slic3r::GUI::SelectMachineDialog::m_rename_normal_panel {nullptr} protected
Referenced by SelectMachineDialog(), on_rename_enter(), and set_default().
m_rename_switch_panel
wxSimplebook* Slic3r::GUI::SelectMachineDialog::m_rename_switch_panel {nullptr} protected
Referenced by SelectMachineDialog(), on_rename_click(), on_rename_enter(), and set_default().
m_rename_text
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_rename_text {nullptr} protected
Referenced by SelectMachineDialog(), on_rename_enter(), and set_default().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_scrollable_region
wxPanel* Slic3r::GUI::SelectMachineDialog::m_scrollable_region protected
Referenced by SelectMachineDialog(), and set_default().
m_scrollable_view
wxScrolledWindow* Slic3r::GUI::SelectMachineDialog::m_scrollable_view protected
Referenced by SelectMachineDialog(), and set_default().
m_simplebook
wxSimplebook* Slic3r::GUI::SelectMachineDialog::m_simplebook {nullptr} protected
Referenced by finish_mode(), prepare_mode(), and sending_mode().
m_sizer_bottom
wxBoxSizer* Slic3r::GUI::SelectMachineDialog::m_sizer_bottom protected
m_sizer_main
wxBoxSizer* Slic3r::GUI::SelectMachineDialog::m_sizer_main protected
Referenced by SelectMachineDialog().
m_sizer_material
wxGridSizer* Slic3r::GUI::SelectMachineDialog::m_sizer_material protected
Referenced by set_default().
m_sizer_scrollable_region
wxBoxSizer* Slic3r::GUI::SelectMachineDialog::m_sizer_scrollable_region protected
Referenced by SelectMachineDialog().
m_sizer_scrollable_view
wxBoxSizer* Slic3r::GUI::SelectMachineDialog::m_sizer_scrollable_view protected
Referenced by SelectMachineDialog().
m_sizer_select
wxWrapSizer* Slic3r::GUI::SelectMachineDialog::m_sizer_select protected
Referenced by update_select_layout().
m_staticbitmap
wxStaticBitmap* Slic3r::GUI::SelectMachineDialog::m_staticbitmap {nullptr} protected
m_statictext_ams_msg
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_statictext_ams_msg {nullptr} protected
Referenced by format_text(), and update_ams_status_msg().
m_staticText_bed_title
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_staticText_bed_title {nullptr} protected
m_statictext_finish
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_statictext_finish {nullptr} protected
m_staticText_left
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_staticText_left {nullptr} protected
m_statictext_printer_msg
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_statictext_printer_msg {nullptr} protected
Referenced by update_priner_status_msg().
m_status_bar
std::shared_ptr<BBLStatusBarSend> Slic3r::GUI::SelectMachineDialog::m_status_bar
Referenced by on_dpi_changed(), on_ok(), on_selection_changed(), prepare_mode(), and set_default().
m_stext_printer_title
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_stext_printer_title {nullptr} protected
m_stext_sending
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_stext_sending {nullptr} protected
m_stext_time
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_stext_time {nullptr} protected
Referenced by set_default().
m_stext_weight
wxStaticText* Slic3r::GUI::SelectMachineDialog::m_stext_weight {nullptr} protected
Referenced by set_default().
m_thumbnailPanel
ThumbnailPanel* Slic3r::GUI::SelectMachineDialog::m_thumbnailPanel {nullptr} protected
Referenced by set_default().
machine_model
wxObjectDataPtr<MachineListModel> Slic3r::GUI::SelectMachineDialog::machine_model
Referenced by init_model().
rename_sizer_h
wxBoxSizer* Slic3r::GUI::SelectMachineDialog::rename_sizer_h { nullptr } protected
Referenced by SelectMachineDialog().
rename_sizer_v
wxBoxSizer* Slic3r::GUI::SelectMachineDialog::rename_sizer_v { nullptr } protected
Referenced by SelectMachineDialog().
select_bed
wxWindow* Slic3r::GUI::SelectMachineDialog::select_bed {nullptr} protected
Referenced by set_default(), and update_select_layout().
select_flow
wxWindow* Slic3r::GUI::SelectMachineDialog::select_flow {nullptr} protected
Referenced by set_default(), and update_select_layout().
select_timelapse
wxWindow* Slic3r::GUI::SelectMachineDialog::select_timelapse { nullptr } protected
Referenced by has_tips(), on_ok(), and update_select_layout().
select_use_ams
wxWindow* Slic3r::GUI::SelectMachineDialog::select_use_ams {nullptr} protected
Referenced by update_ams_check().
sizer_thumbnail
wxBoxSizer* Slic3r::GUI::SelectMachineDialog::sizer_thumbnail protected
timeout_count
int Slic3r::GUI::SelectMachineDialog::timeout_count = 0 protected
Referenced by is_timeout(), on_selection_changed(), reset_timeout(), and update_show_status().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SelectMachine.hpp
src/slic3r/GUI/SelectMachine.cpp