OrcaSlicer: Slic3r::GUI::AuFolderPanel Class Reference
Slic3r::GUI::AuFolderPanel Class Reference
#include <src/slic3r/GUI/Auxiliary.hpp>
Public Member Functions
AuFolderPanel (wxWindow *parent, AuxiliaryFolderType type, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~AuFolderPanel ()
void clear ()
void update_cover ()
void update (std::vector< fs::path > paths)
void msw_rescale ()
void on_add (wxMouseEvent &event)
void on_delete (wxCommandEvent &event)
Public Attributes
AuxiliaryFolderType m_type
wxScrolledWindow * m_scrolledWindow {nullptr}
wxWrapSizer * m_gsizer_content {nullptr}
Button * m_button_del {nullptr}
AuFile * m_big_button_add { nullptr }
AuFilesHash m_aufiles_list
Detailed Description
Constructor & Destructor Documentation
AuFolderPanel()
Slic3r::GUI::AuFolderPanel::AuFolderPanel (wxWindow * parent, AuxiliaryFolderType type, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
    : wxPanel(parent, id, pos, size, style)
{
    m_type = type;
    SetBackgroundColour(AUFILE_GREY300);
    wxBoxSizer *sizer_main = new wxBoxSizer(wxVERTICAL);
    m_scrolledWindow = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxHSCROLL | wxVSCROLL);
    m_scrolledWindow->SetScrollRate(5, 5);
    wxBoxSizer *sizer_body = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *sizer_top  = new wxBoxSizer(wxHORIZONTAL);
    StateColor btn_bg_white(std::pair<wxColour, int>(AMS_CONTROL_DISABLE_COLOUR, StateColor::Disabled), std::pair<wxColour, int>(AMS_CONTROL_DISABLE_COLOUR, StateColor::Pressed),
                            std::pair<wxColour, int>(AMS_CONTROL_DEF_BLOCK_BK_COLOUR, StateColor::Hovered),
                            std::pair<wxColour, int>(AMS_CONTROL_WHITE_COLOUR, StateColor::Normal));
    StateColor btn_bd_white(std::pair<wxColour, int>(AMS_CONTROL_WHITE_COLOUR, StateColor::Disabled), std::pair<wxColour, int>(wxColour(38, 46, 48), StateColor::Enabled));
    //m_button_add = new AuFile(m_scrolledWindow, fs::path(), "", AddFileButton, -1);
    /*m_button_add->SetBackgroundColor(btn_bg_white);
    m_button_add->SetBorderColor(btn_bd_white);
    m_button_add->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_add->SetCornerRadius(FromDIP(12));
    m_button_add->SetFont(Label::Body_14);*/
    m_big_button_add = new AuFile(m_scrolledWindow, fs::path(), "", AddFileButton, -1);
    /*m_button_del = new Button(m_scrolledWindow, _L("Delete"), "auxiliary_delete_file", 12, 12);
    m_button_del->SetBackgroundColor(btn_bg_white);
    m_button_del->SetBorderColor(btn_bd_white);
    m_button_del->SetMinSize(wxSize(FromDIP(80), FromDIP(24)));
    m_button_del->SetCornerRadius(12);
    m_button_del->SetFont(Label::Body_14);*/
    // m_button_del->Bind(wxEVT_LEFT_UP, &AuxiliaryPanel::on_delete, this);
    sizer_top->Add(0, 0, 0, wxLEFT, FromDIP(10));
    m_gsizer_content = new wxWrapSizer(wxHORIZONTAL, wxWRAPSIZER_DEFAULT_FLAGS);
    //if (m_type == MODEL_PICTURE) {
    //    //sizer_top->Add(m_button_add, 0, wxALL, 0);
    //    //m_big_button_add->Hide();
    //}
    //else {
        m_gsizer_content->Add(m_big_button_add, 0, wxALL, FromDIP(8));
        //m_button_add->Hide();
    //}
    // sizer_top->Add(m_button_del, 0, wxALL, 0);
    sizer_body->Add(sizer_top, 0, wxEXPAND | wxTOP, FromDIP(35));
    sizer_body->AddSpacer(FromDIP(14));
    sizer_body->Add(m_gsizer_content, 0, 0, 0);
    m_scrolledWindow->SetSizer(sizer_body);
    m_scrolledWindow->Layout();
    sizer_main->Add(m_scrolledWindow, 1, wxEXPAND | wxLEFT, FromDIP(40));
    this->SetSizer(sizer_main);
    this->Layout();
    m_big_button_add->Bind(wxEVT_LEFT_DOWN, [this](auto& e)
        {
            auto evt = wxCommandEvent(EVT_AUXILIARY_IMPORT);
            evt.SetString(s_default_folders[m_type]);
            evt.SetEventObject(m_parent);
            wxPostEvent(m_parent, evt);
        });
    //m_button_add->Bind(wxEVT_LEFT_UP, &AuFolderPanel::on_add, this);
}
References AddFileButton, AMS_CONTROL_DEF_BLOCK_BK_COLOUR, AMS_CONTROL_DISABLE_COLOUR, AMS_CONTROL_WHITE_COLOUR, AUFILE_GREY300, StateColor::Disabled, StateColor::Enabled, StateColor::Hovered, m_big_button_add, m_gsizer_content, m_scrolledWindow, m_type, StateColor::Normal, StateColor::Pressed, and s_default_folders.
~AuFolderPanel()
Slic3r::GUI::AuFolderPanel::~AuFolderPanel ()
{
}
Member Function Documentation
clear()
void Slic3r::GUI::AuFolderPanel::clear ()
{
    for (auto i = 0; i < m_aufiles_list.GetCount(); i++) {
        AuFiles *aufile = m_aufiles_list[i];
        if (aufile->file) { aufile->file->Destroy(); }
    }
    m_aufiles_list.clear();
    Layout();
    Refresh();
}
References Slic3r::GUI::AuFiles::file, and m_aufiles_list.
Referenced by on_delete(), update(), and Slic3r::GUI::AuxiliaryPanel::update_all_panel().
msw_rescale()
void Slic3r::GUI::AuFolderPanel::msw_rescale ()
{
    //m_button_add->SetMinSize(wxSize(-1, FromDIP(24)));
    for (auto i = 0; i < m_aufiles_list.GetCount(); i++) {
        AuFiles *aufile = m_aufiles_list[i];
        aufile->file->msw_rescale();
    }
}
References Slic3r::GUI::AuFiles::file, m_aufiles_list, and Slic3r::GUI::AuFile::msw_rescale().
Referenced by Slic3r::GUI::AuxiliaryPanel::msw_rescale().
on_add()
void Slic3r::GUI::AuFolderPanel::on_add (wxMouseEvent & event)
{
    auto evt = wxCommandEvent(EVT_AUXILIARY_IMPORT);
    evt.SetString(s_default_folders[m_type]);
    evt.SetEventObject(m_parent);
    wxPostEvent(m_parent, evt);
}
References m_type, and s_default_folders.
on_delete()
void Slic3r::GUI::AuFolderPanel::on_delete (wxCommandEvent & event)
{ clear(); }
References clear().
update()
void Slic3r::GUI::AuFolderPanel::update (std::vector< fs::path > paths)
{
    clear();
    for (auto i = 0; i < paths.size(); i++) {
        std::string temp_name = fs::path(paths[i].c_str()).filename().string();
        auto name = encode_path(temp_name.c_str());
        auto        aufile = new AuFile(m_scrolledWindow, paths[i], name, m_type, wxID_ANY);
        m_gsizer_content->Add(aufile, 0, wxALL, FromDIP(8));
        auto af  = new AuFiles;
        af->path = paths[i].string();
        af->file = aufile;
        m_aufiles_list.push_back(af);
    }
    m_gsizer_content->Layout();
    Layout();
}
References clear(), Slic3r::encode_path(), m_aufiles_list, m_gsizer_content, m_scrolledWindow, m_type, and Slic3r::GUI::AuFiles::path.
Referenced by Slic3r::GUI::AuxiliaryPanel::update_all_panel().
update_cover()
void Slic3r::GUI::AuFolderPanel::update_cover ()
{
    if (wxGetApp().plater()->model().model_info != nullptr) {
        for (auto i = 0; i < m_aufiles_list.GetCount(); i++) {
            AuFiles *aufile = m_aufiles_list[i];
            if (wxString::FromUTF8(wxGetApp().plater()->model().model_info->cover_file) == aufile->file->m_file_name) {
                aufile->file->set_cover(true);
            } else {
                aufile->file->set_cover(false);
            }
        }
    }
}
References Slic3r::GUI::AuFiles::file, m_aufiles_list, Slic3r::GUI::AuFile::m_file_name, Slic3r::GUI::plater(), and Slic3r::GUI::AuFile::set_cover().
Referenced by Slic3r::GUI::AuxiliaryPanel::update_all_cover().
Member Data Documentation
m_aufiles_list
AuFilesHash Slic3r::GUI::AuFolderPanel::m_aufiles_list
Referenced by clear(), msw_rescale(), update(), and update_cover().
m_big_button_add
AuFile* Slic3r::GUI::AuFolderPanel::m_big_button_add { nullptr }
Referenced by AuFolderPanel().
m_button_del
Button* Slic3r::GUI::AuFolderPanel::m_button_del {nullptr}
m_gsizer_content
wxWrapSizer* Slic3r::GUI::AuFolderPanel::m_gsizer_content {nullptr}
Referenced by AuFolderPanel(), and update().
m_scrolledWindow
wxScrolledWindow* Slic3r::GUI::AuFolderPanel::m_scrolledWindow {nullptr}
Referenced by AuFolderPanel(), and update().
m_type
AuxiliaryFolderType Slic3r::GUI::AuFolderPanel::m_type
Referenced by AuFolderPanel(), on_add(), and update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Auxiliary.hpp
src/slic3r/GUI/Auxiliary.cpp