OrcaSlicer: src/qhull/src/libqhullcpp/PointCoordinates.h File Reference
PointCoordinates.h File Reference
#include "libqhull_r/qhull_ra.h"
#include "libqhullcpp/QhullPoints.h"
#include "libqhullcpp/Coordinates.h"
#include <ostream>
#include <string>
#include <vector>
Classes
class orgQhull::PointCoordinates
class orgQhull::PointCoordinatesIterator
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global
std::ostream & operator<< (std::ostream &os, const orgQhull::PointCoordinates &p)
Function Documentation
operator<<()
std::ostream & operator<< (std::ostream & os, const orgQhull::PointCoordinates & p)
{
    p.checkValid();
    countT count= p.count();
    int dimension= p.dimension();
    string comment= p.comment();
    if(comment.empty()){
        os << dimension << endl;
    }else{
        os << dimension << " " << comment << endl;
    }
    os << count << endl;
    Coordinates::ConstIterator c= p.beginCoordinates();
    for(countT i=0; i<count; i++){
        for(int j=0; j<dimension; j++){
            os << *c++ << " ";
        }
        os << endl;
    }
    return os;
}//operator<<
References orgQhull::PointCoordinates::beginCoordinates(), orgQhull::PointCoordinates::checkValid(), orgQhull::PointCoordinates::comment(), orgQhull::QhullPoints::count(), count, and orgQhull::QhullPoints::dimension().