OrcaSlicer: Slic3r::ExtrusionEntity Class Reference
Slic3r::ExtrusionEntity Class Reference abstract
#include <src/libslic3r/ExtrusionEntity.hpp>
Public Member Functions
virtual ExtrusionRole role () const =0
virtual bool is_collection () const
virtual bool is_loop () const
virtual bool can_reverse () const
virtual bool can_sort () const
virtual void set_reverse ()
virtual ExtrusionEntity * clone () const =0
virtual ExtrusionEntity * clone_move ()=0
virtual ~ExtrusionEntity ()
virtual void reverse ()=0
virtual const Point & first_point () const =0
virtual const Point & last_point () const =0
virtual void polygons_covered_by_width (Polygons &out, const float scaled_epsilon) const =0
virtual void polygons_covered_by_spacing (Polygons &out, const float scaled_epsilon) const =0
Polygons polygons_covered_by_width (const float scaled_epsilon=0.f) const
Polygons polygons_covered_by_spacing (const float scaled_epsilon=0.f) const
virtual double min_mm3_per_mm () const =0
virtual Polyline as_polyline () const =0
virtual void collect_polylines (Polylines &dst) const =0
virtual void collect_points (Points &dst) const =0
virtual Polylines as_polylines () const
virtual double length () const =0
virtual double total_volume () const =0
Static Public Member Functions
static std::string role_to_string (ExtrusionRole role)
static ExtrusionRole string_to_role (const std::string_view role)
Detailed Description
Constructor & Destructor Documentation
~ExtrusionEntity()
virtual Slic3r::ExtrusionEntity::~ExtrusionEntity () inline virtual
{}
Member Function Documentation
as_polyline()
virtual Polyline Slic3r::ExtrusionEntity::as_polyline () const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
as_polylines()
virtual Polylines Slic3r::ExtrusionEntity::as_polylines () const inline virtual
{ Polylines dst; this->collect_polylines(dst); return dst; }
References collect_polylines().
Referenced by Slic3r::SupportMaterialInternal::remove_bridges_from_contacts().
can_reverse()
virtual bool Slic3r::ExtrusionEntity::can_reverse () const inline virtual
Reimplemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
{ return true; }
Referenced by Slic3r::chain_extrusion_entities().
can_sort()
virtual bool Slic3r::ExtrusionEntity::can_sort () const inline virtual
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return true; }//BBS: only used in ExtrusionEntityCollection
clone()
virtual ExtrusionEntity * Slic3r::ExtrusionEntity::clone () const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
Referenced by Slic3r::ExtrusionEntityCollection::append(), and Slic3r::ExtrusionEntityCollection::replace().
clone_move()
virtual ExtrusionEntity * Slic3r::ExtrusionEntity::clone_move () pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
collect_points()
virtual void Slic3r::ExtrusionEntity::collect_points (Points & dst) const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
collect_polylines()
virtual void Slic3r::ExtrusionEntity::collect_polylines (Polylines & dst) const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
Referenced by as_polylines().
first_point()
virtual const Point & Slic3r::ExtrusionEntity::first_point () const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
is_collection()
virtual bool Slic3r::ExtrusionEntity::is_collection () const inline virtual
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return false; }
is_loop()
virtual bool Slic3r::ExtrusionEntity::is_loop () const inline virtual
Reimplemented in Slic3r::ExtrusionMultiPath, and Slic3r::ExtrusionLoop.
{ return false; }
Referenced by Slic3r::chain_extrusion_entities().
last_point()
virtual const Point & Slic3r::ExtrusionEntity::last_point () const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
length()
virtual double Slic3r::ExtrusionEntity::length () const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
min_mm3_per_mm()
virtual double Slic3r::ExtrusionEntity::min_mm3_per_mm () const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
polygons_covered_by_spacing() [1/2]
Polygons Slic3r::ExtrusionEntity::polygons_covered_by_spacing (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_spacing(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_spacing().
polygons_covered_by_spacing() [2/2]
virtual void Slic3r::ExtrusionEntity::polygons_covered_by_spacing (Polygons & out, const float scaled_epsilon) const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
Referenced by polygons_covered_by_spacing().
polygons_covered_by_width() [1/2]
Polygons Slic3r::ExtrusionEntity::polygons_covered_by_width (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_width(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_width().
polygons_covered_by_width() [2/2]
virtual void Slic3r::ExtrusionEntity::polygons_covered_by_width (Polygons & out, const float scaled_epsilon) const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
Referenced by polygons_covered_by_width().
reverse()
virtual void Slic3r::ExtrusionEntity::reverse () pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
role()
virtual ExtrusionRole Slic3r::ExtrusionEntity::role () const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
Referenced by Slic3r::filter_by_extrusion_role_in_place(), role_to_string(), and string_to_role().
role_to_string()
std::string Slic3r::ExtrusionEntity::role_to_string (ExtrusionRole role) static
{
    switch (role) {
        case erNone                         : return L("Undefined");
        case erPerimeter                    : return L("Inner wall");
        case erExternalPerimeter            : return L("Outer wall");
        case erOverhangPerimeter            : return L("Overhang wall");
        case erInternalInfill               : return L("Sparse infill");
        case erSolidInfill                  : return L("Internal solid infill");
        case erTopSolidInfill               : return L("Top surface");
        case erBottomSurface                : return L("Bottom surface");
        case erIroning                      : return L("Ironing");
        case erBridgeInfill                 : return L("Bridge");
        case erInternalBridgeInfill         : return L("Internal Bridge");
        case erGapFill                      : return L("Gap infill");
        case erSkirt                        : return ("Skirt");
        case erBrim                         : return ("Brim");
        case erSupportMaterial              : return L("Support");
        case erSupportMaterialInterface     : return L("Support interface");
        case erSupportTransition            : return L("Support transition");
        case erWipeTower                    : return L("Prime tower");
        case erCustom                       : return L("Custom");
        case erMixed                        : return L("Multiple");
        default                             : assert(false);
    }
    return "";
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and role().
Referenced by Slic3r::WipeTowerWriter::WipeTowerWriter(), Slic3r::GCode::_do_export(), and Slic3r::GUI::GCodeViewer::render_legend().
set_reverse()
virtual void Slic3r::ExtrusionEntity::set_reverse () inline virtual
Reimplemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, and Slic3r::ExtrusionEntityCollection.
{}
string_to_role()
ExtrusionRole Slic3r::ExtrusionEntity::string_to_role (const std::string_view role) static
{
    if (role == L("Inner wall"))
        return erPerimeter;
    else if (role == L("Outer wall"))
        return erExternalPerimeter;
    else if (role == L("Overhang wall"))
        return erOverhangPerimeter;
    else if (role == L("Sparse infill"))
        return erInternalInfill;
    else if (role == L("Internal solid infill"))
        return erSolidInfill;
    else if (role == L("Top surface"))
        return erTopSolidInfill;
    else if (role == L("Bottom surface"))
        return erBottomSurface;
    else if (role == L("Ironing"))
        return erIroning;
    else if (role == L("Bridge"))
        return erBridgeInfill;
    else if (role == L("Internal Bridge"))
        return erInternalBridgeInfill;
    else if (role == L("Gap infill"))
        return erGapFill;
    else if (role == ("Skirt"))
        return erSkirt;
    else if (role == ("Brim"))
        return erBrim;
    else if (role == L("Support"))
        return erSupportMaterial;
    else if (role == L("Support interface"))
        return erSupportMaterialInterface;
    else if (role == L("Support transition"))
        return erSupportTransition;
    else if (role == L("Prime tower"))
        return erWipeTower;
    else if (role == L("Custom"))
        return erCustom;
    else if (role == L("Multiple"))
        return erMixed;
    else
        return erNone;
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and role().
Referenced by Slic3r::FanMover::_process_gcode_line(), and Slic3r::GCodeProcessor::process_tags().
total_volume()
virtual double Slic3r::ExtrusionEntity::total_volume () const pure virtual
Implemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, Slic3r::ExtrusionLoop, and Slic3r::ExtrusionEntityCollection.
The documentation for this class was generated from the following files:
src/libslic3r/ExtrusionEntity.hpp
src/libslic3r/ExtrusionEntity.cpp