OrcaSlicer: Clipper2Lib::ClipperOffset Class Reference
Clipper2Lib::ClipperOffset Class Reference
#include <src/clipper2/Clipper2Lib/include/clipper2/clipper.offset.h>
Classes
class Group
Public Member Functions
ClipperOffset (double miter_limit=2.0, double arc_tolerance=0.0, bool preserve_collinear=false, bool reverse_solution=false)
~ClipperOffset ()
void AddPath (const Path64 &path, JoinType jt_, EndType et_)
void AddPaths (const Paths64 &paths, JoinType jt_, EndType et_)
void AddPath (const PathD &p, JoinType jt_, EndType et_)
void AddPaths (const PathsD &p, JoinType jt_, EndType et_)
void Clear ()
Paths64 Execute (double delta)
double MiterLimit () const
void MiterLimit (double miter_limit)
double ArcTolerance () const
void ArcTolerance (double arc_tolerance)
bool MergeGroups () const
void MergeGroups (bool merge_groups)
bool PreserveCollinear () const
void PreserveCollinear (bool preserve_collinear)
bool ReverseSolution () const
void ReverseSolution (bool reverse_solution)
Private Member Functions
void DoSquare (Group &group, const Path64 &path, size_t j, size_t k)
void DoMiter (Group &group, const Path64 &path, size_t j, size_t k, double cos_a)
void DoRound (Group &group, const Path64 &path, size_t j, size_t k, double angle)
void BuildNormals (const Path64 &path)
void OffsetPolygon (Group &group, Path64 &path)
void OffsetOpenJoined (Group &group, Path64 &path)
void OffsetOpenPath (Group &group, Path64 &path, EndType endType)
void OffsetPoint (Group &group, Path64 &path, size_t j, size_t &k)
void DoGroupOffset (Group &group, double delta)
Private Attributes
double group_delta_ = 0.0
double abs_group_delta_ = 0.0
double temp_lim_ = 0.0
double steps_per_rad_ = 0.0
PathD norms
Paths64 solution
std::vector< Group > groups_
JoinType join_type_ = JoinType::Square
double miter_limit_ = 0.0
double arc_tolerance_ = 0.0
bool merge_groups_ = true
bool preserve_collinear_ = false
bool reverse_solution_ = false
Detailed Description
Constructor & Destructor Documentation
ClipperOffset()
Clipper2Lib::ClipperOffset::ClipperOffset (double miter_limit = 2.0, double arc_tolerance = 0.0, bool preserve_collinear = false, bool reverse_solution = false) inline
                                   :
    miter_limit_(miter_limit), arc_tolerance_(arc_tolerance),
    preserve_collinear_(preserve_collinear),
    reverse_solution_(reverse_solution) { };
~ClipperOffset()
Clipper2Lib::ClipperOffset::~ClipperOffset () inline
{ Clear(); };
References Clear().
Member Function Documentation
AddPath() [1/2]
void Clipper2Lib::ClipperOffset::AddPath (const Path64 & path, JoinType jt_, EndType et_)
{
  Paths64 paths;
  paths.push_back(path);
  AddPaths(paths, jt_, et_);
}
References AddPaths().
AddPath() [2/2]
void Clipper2Lib::ClipperOffset::AddPath (const PathD & p, JoinType jt_, EndType et_)
{
  PathsD paths;
  paths.push_back(path);
  AddPaths(paths, jt_, et_);
}
References AddPaths().
AddPaths() [1/2]
void Clipper2Lib::ClipperOffset::AddPaths (const Paths64 & paths, JoinType jt_, EndType et_)
{
  if (paths.size() == 0) return;
  groups_.push_back(Group(paths, jt_, et_));
}
References groups_.
Referenced by AddPath(), AddPath(), Clipper2Lib::InflatePaths(), Clipper2Lib::InflatePaths(), Clipper2Lib::InflatePaths64(), and Clipper2Lib::InflatePathsD().
AddPaths() [2/2]
void Clipper2Lib::ClipperOffset::AddPaths (const PathsD & p, JoinType jt_, EndType et_)
{
  if (paths.size() == 0) return;
  groups_.push_back(Group(PathsDToPaths64(paths), jt_, et_));
}
References groups_, and Clipper2Lib::PathsDToPaths64().
ArcTolerance() [1/2]
double Clipper2Lib::ClipperOffset::ArcTolerance () const inline
{ return arc_tolerance_; }
References arc_tolerance_.
ArcTolerance() [2/2]
void Clipper2Lib::ClipperOffset::ArcTolerance (double arc_tolerance) inline
{ arc_tolerance_ = arc_tolerance; }
References arc_tolerance_.
BuildNormals()
void Clipper2Lib::ClipperOffset::BuildNormals (const Path64 & path) private
{
  norms.clear();
  norms.reserve(path.size());
  if (path.size() == 0) return;
  Path64::const_iterator path_iter, path_last_iter = --path.cend();
  for (path_iter = path.cbegin(); path_iter != path_last_iter; ++path_iter)
    norms.push_back(GetUnitNormal(*path_iter,*(path_iter +1)));
  norms.push_back(GetUnitNormal(*path_last_iter, *(path.cbegin())));
}
References Clipper2Lib::GetUnitNormal(), and norms.
Referenced by DoGroupOffset(), and OffsetOpenJoined().
Clear()
void Clipper2Lib::ClipperOffset::Clear () inline
{ groups_.clear(); norms.clear(); };
References groups_, and norms.
Referenced by ~ClipperOffset().
DoGroupOffset()
void Clipper2Lib::ClipperOffset::DoGroupOffset (Group & group, double delta) private
{
  if (group.end_type_ != EndType::Polygon) delta = std::abs(delta) * 0.5;
  bool isClosedPaths = IsClosedPath(group.end_type_);
  if (isClosedPaths)
  {
    //the lowermost polygon must be an outer polygon. So we can use that as the
    //designated orientation for outer polygons (needed for tidy-up clipping)
    Paths64::size_type lowestIdx = GetLowestPolygonIdx(group.paths_in_);
    // nb: don't use the default orientation here ...
    double area = Area(group.paths_in_[lowestIdx]);
    if (area == 0) return;
    group.is_reversed_ = (area < 0);
    if (group.is_reversed_) delta = -delta;
  }
  else
    group.is_reversed_ = false;
  group_delta_ = delta;
  abs_group_delta_ = std::abs(group_delta_);
  join_type_ = group.join_type_;
  double arcTol = (arc_tolerance_ > floating_point_tolerance ? arc_tolerance_
    : std::log10(2 + abs_group_delta_) * default_arc_tolerance); // empirically derived
//calculate a sensible number of steps (for 360 deg for the given offset
  if (group.join_type_ == JoinType::Round || group.end_type_ == EndType::Round)
  {
    steps_per_rad_ = PI / std::acos(1 - arcTol / abs_group_delta_) / (PI *2);
  }
  bool is_closed_path = IsClosedPath(group.end_type_);
  Paths64::const_iterator path_iter;
  for(path_iter = group.paths_in_.cbegin(); path_iter != group.paths_in_.cend(); ++path_iter)
  {
    Path64 path = StripDuplicates(*path_iter, is_closed_path);
    Path64::size_type cnt = path.size();
    if (cnt == 0) continue;
    if (cnt == 1) // single point - only valid with open paths
    {
      group.path_ = Path64();
      //single vertex so build a circle or square ...
      if (group.join_type_ == JoinType::Round)
      {
        double radius = abs_group_delta_;
        group.path_ = Ellipse(path[0], radius, radius);
      }
      else
      {
        int d = (int)std::ceil(abs_group_delta_);
        Rect64 r = Rect64(path[0].x - d, path[0].y - d, path[0].x + d, path[0].y + d);
        group.path_ = r.AsPath();
      }
      group.paths_out_.push_back(group.path_);
    }
    else
    {
      BuildNormals(path);
      if (group.end_type_ == EndType::Polygon) OffsetPolygon(group, path);
      else if (group.end_type_ == EndType::Joined) OffsetOpenJoined(group, path);
      else OffsetOpenPath(group, path, group.end_type_);
    }
  }
  if (!merge_groups_)
  {
    //clean up self-intersections ...
    Clipper64 c;
    c.PreserveCollinear = false;
    //the solution should retain the orientation of the input
    c.ReverseSolution = reverse_solution_ != group.is_reversed_;
    c.AddSubject(group.paths_out_);
    if (group.is_reversed_)
      c.Execute(ClipType::Union, FillRule::Negative, group.paths_out_);
    else
      c.Execute(ClipType::Union, FillRule::Positive, group.paths_out_);
  }
  solution.reserve(solution.size() + group.paths_out_.size());
  copy(group.paths_out_.begin(), group.paths_out_.end(), back_inserter(solution));
  group.paths_out_.clear();
}
References abs_group_delta_, arc_tolerance_, Clipper2Lib::Area(), Clipper2Lib::Rect< T >::AsPath(), BuildNormals(), Clipper2Lib::default_arc_tolerance, Clipper2Lib::Ellipse(), Clipper2Lib::ClipperOffset::Group::end_type_, Clipper2Lib::floating_point_tolerance, Clipper2Lib::GetLowestPolygonIdx(), group_delta_, int, Clipper2Lib::ClipperOffset::Group::is_reversed_, Clipper2Lib::IsClosedPath(), Clipper2Lib::ClipperOffset::Group::join_type_, join_type_, Clipper2Lib::Joined, merge_groups_, Clipper2Lib::Negative, OffsetOpenJoined(), OffsetOpenPath(), OffsetPolygon(), Clipper2Lib::ClipperOffset::Group::path_, Clipper2Lib::ClipperOffset::Group::paths_in_, Clipper2Lib::ClipperOffset::Group::paths_out_, Clipper2Lib::PI, Clipper2Lib::Polygon, Clipper2Lib::Positive, reverse_solution_, Clipper2Lib::Round, solution, steps_per_rad_, Clipper2Lib::StripDuplicates(), and Clipper2Lib::Union.
Referenced by Execute().
DoMiter()
void Clipper2Lib::ClipperOffset::DoMiter (Group & group, const Path64 & path, size_t j, size_t k, double cos_a) private
{
  double q = group_delta_ / (cos_a + 1);
  group.path_.push_back(Point64(
    path[j].x + (norms[k].x + norms[j].x) * q,
    path[j].y + (norms[k].y + norms[j].y) * q));
}
References group_delta_, norms, and Clipper2Lib::ClipperOffset::Group::path_.
Referenced by OffsetPoint().
DoRound()
void Clipper2Lib::ClipperOffset::DoRound (Group & group, const Path64 & path, size_t j, size_t k, double angle) private
{
  //even though angle may be negative this is a convex join
  Point64 pt = path[j];
  int steps = static_cast<int>(std::ceil(steps_per_rad_ * std::abs(angle)));
  double step_sin = std::sin(angle / steps);
  double step_cos = std::cos(angle / steps);
  PointD pt2 = PointD(norms[k].x * group_delta_, norms[k].y * group_delta_);
  if (j == k) pt2.Negate();
  group.path_.push_back(Point64(pt.x + pt2.x, pt.y + pt2.y));
  for (int i = 0; i < steps; i++)
  {
    pt2 = PointD(pt2.x * step_cos - step_sin * pt2.y,
      pt2.x * step_sin + pt2.y * step_cos);
    group.path_.push_back(Point64(pt.x + pt2.x, pt.y + pt2.y));
  }
  group.path_.push_back(GetPerpendic(path[j], norms[j], group_delta_));
}
References Clipper2Lib::GetPerpendic(), group_delta_, Clipper2Lib::Point< T >::Negate(), norms, Clipper2Lib::ClipperOffset::Group::path_, steps_per_rad_, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by OffsetOpenPath(), and OffsetPoint().
DoSquare()
void Clipper2Lib::ClipperOffset::DoSquare (Group & group, const Path64 & path, size_t j, size_t k) private
{
  PointD vec;
  if (j == k)
    vec = PointD(norms[0].y, -norms[0].x);
  else
    vec = GetAvgUnitVector(
      PointD(-norms[k].y, norms[k].x),
      PointD(norms[j].y, -norms[j].x));
  // now offset the original vertex delta units along unit vector
  PointD ptQ = PointD(path[j]);
  ptQ = TranslatePoint(ptQ, abs_group_delta_ * vec.x, abs_group_delta_ * vec.y);
  // get perpendicular vertices
  PointD pt1 = TranslatePoint(ptQ, group_delta_ * vec.y, group_delta_ * -vec.x);
  PointD pt2 = TranslatePoint(ptQ, group_delta_ * -vec.y, group_delta_ * vec.x);
  // get 2 vertices along one edge offset
  PointD pt3 = GetPerpendicD(path[k], norms[k], group_delta_);
  if (j == k)
  {
    PointD pt4 = PointD(pt3.x + vec.x * group_delta_, pt3.y + vec.y * group_delta_);
    PointD pt = IntersectPoint(pt1, pt2, pt3, pt4);
    //get the second intersect point through reflecion
    group.path_.push_back(Point64(ReflectPoint(pt, ptQ)));
    group.path_.push_back(Point64(pt));
  }
  else
  {
    PointD pt4 = GetPerpendicD(path[j], norms[k], group_delta_);
    PointD pt = IntersectPoint(pt1, pt2, pt3, pt4);
    group.path_.push_back(Point64(pt));
    //get the second intersect point through reflecion
    group.path_.push_back(Point64(ReflectPoint(pt, ptQ)));
  }
}
References abs_group_delta_, Clipper2Lib::GetAvgUnitVector(), Clipper2Lib::GetPerpendicD(), group_delta_, Clipper2Lib::IntersectPoint(), norms, Clipper2Lib::ClipperOffset::Group::path_, Clipper2Lib::ReflectPoint(), Clipper2Lib::TranslatePoint(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by OffsetOpenPath(), and OffsetPoint().
Execute()
Paths64 Clipper2Lib::ClipperOffset::Execute (double delta)
{
  solution.clear();
  if (std::abs(delta) < default_arc_tolerance)
  {
    for (const Group& group : groups_)
    {
      solution.reserve(solution.size() + group.paths_in_.size());
      copy(group.paths_in_.begin(), group.paths_in_.end(), back_inserter(solution));
    }
    return solution;
  }
  temp_lim_ = (miter_limit_ <= 1) ?
    2.0 :
    2.0 / (miter_limit_ * miter_limit_);
  std::vector<Group>::iterator groups_iter;
  for (groups_iter = groups_.begin();
    groups_iter != groups_.end(); ++groups_iter)
  {
    DoGroupOffset(*groups_iter, delta);
  }
  if (merge_groups_ && groups_.size() > 0)
  {
    //clean up self-intersections ...
    Clipper64 c;
    c.PreserveCollinear = false;
    //the solution should retain the orientation of the input
    c.ReverseSolution = reverse_solution_ != groups_[0].is_reversed_;
    c.AddSubject(solution);
    if (groups_[0].is_reversed_)
      c.Execute(ClipType::Union, FillRule::Negative, solution);
    else
      c.Execute(ClipType::Union, FillRule::Positive, solution);
  }
  return solution;
}
References Clipper2Lib::default_arc_tolerance, DoGroupOffset(), groups_, merge_groups_, miter_limit_, Clipper2Lib::Negative, Clipper2Lib::Positive, reverse_solution_, solution, temp_lim_, and Clipper2Lib::Union.
Referenced by Clipper2Lib::InflatePaths(), Clipper2Lib::InflatePaths(), Clipper2Lib::InflatePaths64(), and Clipper2Lib::InflatePathsD().
MergeGroups() [1/2]
bool Clipper2Lib::ClipperOffset::MergeGroups () const inline
{ return merge_groups_; }
References merge_groups_.
MergeGroups() [2/2]
void Clipper2Lib::ClipperOffset::MergeGroups (bool merge_groups) inline
{ merge_groups_ = merge_groups; }
References merge_groups_.
MiterLimit() [1/2]
double Clipper2Lib::ClipperOffset::MiterLimit () const inline
{ return miter_limit_; }
References miter_limit_.
MiterLimit() [2/2]
void Clipper2Lib::ClipperOffset::MiterLimit (double miter_limit) inline
{ miter_limit_ = miter_limit; }
References miter_limit_.
OffsetOpenJoined()
void Clipper2Lib::ClipperOffset::OffsetOpenJoined (Group & group, Path64 & path) private
{
  OffsetPolygon(group, path);
  std::reverse(path.begin(), path.end());
  BuildNormals(path);
  OffsetPolygon(group, path);
}
References BuildNormals(), and OffsetPolygon().
Referenced by DoGroupOffset().
OffsetOpenPath()
void Clipper2Lib::ClipperOffset::OffsetOpenPath (Group & group, Path64 & path, EndType endType) private
{
  group.path_.clear();
  // do the line start cap
  switch (end_type)
  {
  case EndType::Butt:
    group.path_.push_back(Point64(
      path[0].x - norms[0].x * group_delta_,
      path[0].y - norms[0].y * group_delta_));
    group.path_.push_back(GetPerpendic(path[0], norms[0], group_delta_));
    break;
  case EndType::Round:
    DoRound(group, path, 0,0, PI);
    break;
  default:
    DoSquare(group, path, 0, 0);
    break;
  }
  size_t highI = path.size() - 1;
  // offset the left side going forward
  for (Path64::size_type i = 1, k = 0; i < highI; ++i)
    OffsetPoint(group, path, i, k);
  // reverse normals
  for (size_t i = highI; i > 0; --i)
    norms[i] = PointD(-norms[i - 1].x, -norms[i - 1].y);
  norms[0] = norms[highI];
  // do the line end cap
  switch (end_type)
  {
  case EndType::Butt:
    group.path_.push_back(Point64(
      path[highI].x - norms[highI].x * group_delta_,
      path[highI].y - norms[highI].y * group_delta_));
    group.path_.push_back(GetPerpendic(path[highI], norms[highI], group_delta_));
    break;
  case EndType::Round:
    DoRound(group, path, highI, highI, PI);
    break;
  default:
    DoSquare(group, path, highI, highI);
    break;
  }
  for (size_t i = highI, k = 0; i > 0; --i)
    OffsetPoint(group, path, i, k);
  group.paths_out_.push_back(group.path_);
}
References Clipper2Lib::Butt, DoRound(), DoSquare(), Clipper2Lib::GetPerpendic(), group_delta_, norms, OffsetPoint(), Clipper2Lib::ClipperOffset::Group::path_, Clipper2Lib::ClipperOffset::Group::paths_out_, Clipper2Lib::PI, and Clipper2Lib::Round.
Referenced by DoGroupOffset().
OffsetPoint()
void Clipper2Lib::ClipperOffset::OffsetPoint (Group & group, Path64 & path, size_t j, size_t & k) private
{
  // Let A = change in angle where edges join
  // A == 0: ie no change in angle (flat join)
  // A == PI: edges 'spike'
  // sin(A) < 0: right turning
  // cos(A) < 0: change in angle is more than 90 degree
  if (path[j] == path[k]) { k = j; return; }
  double sin_a = CrossProduct(norms[j], norms[k]);
  double cos_a = DotProduct(norms[j], norms[k]);
  if (sin_a > 1.0) sin_a = 1.0;
  else if (sin_a < -1.0) sin_a = -1.0;
  bool almostNoAngle = AlmostZero(sin_a) && cos_a > 0;
  // when there's almost no angle of deviation or it's concave
  if (almostNoAngle || (sin_a * group_delta_ < 0))
  {
    Point64 p1 = Point64(
      path[j].x + norms[k].x * group_delta_,
      path[j].y + norms[k].y * group_delta_);
    Point64 p2 = Point64(
      path[j].x + norms[j].x * group_delta_,
      path[j].y + norms[j].y * group_delta_);
    group.path_.push_back(p1);
    if (p1 != p2)
    {
      // when concave add an extra vertex to ensure neat clipping
      if (!almostNoAngle) group.path_.push_back(path[j]);
      group.path_.push_back(p2);
    }
  }
  else // it's convex
  {
    if (join_type_ == JoinType::Round)
      DoRound(group, path, j, k, std::atan2(sin_a, cos_a));
    else if (join_type_ == JoinType::Miter)
    {
      // miter unless the angle is so acute the miter would exceeds ML
      if (cos_a > temp_lim_ - 1) DoMiter(group, path, j, k, cos_a);
      else DoSquare(group, path, j, k);
    }
    // don't bother squaring angles that deviate < ~20 degrees because
    // squaring will be indistinguishable from mitering and just be a lot slower
    else if (cos_a > 0.9)
      DoMiter(group, path, j, k, cos_a);
    else
      DoSquare(group, path, j, k);
  }
  k = j;
}
References Clipper2Lib::AlmostZero(), Clipper2Lib::CrossProduct(), DoMiter(), DoRound(), DoSquare(), Clipper2Lib::DotProduct(), group_delta_, join_type_, Clipper2Lib::Miter, norms, Clipper2Lib::ClipperOffset::Group::path_, Clipper2Lib::Round, and temp_lim_.
Referenced by OffsetOpenPath(), and OffsetPolygon().
OffsetPolygon()
void Clipper2Lib::ClipperOffset::OffsetPolygon (Group & group, Path64 & path) private
{
  group.path_.clear();
  for (Path64::size_type i = 0, j = path.size() -1; i < path.size(); j = i, ++i)
    OffsetPoint(group, path, i, j);
  group.paths_out_.push_back(group.path_);
}
References OffsetPoint(), Clipper2Lib::ClipperOffset::Group::path_, and Clipper2Lib::ClipperOffset::Group::paths_out_.
Referenced by DoGroupOffset(), and OffsetOpenJoined().
PreserveCollinear() [1/2]
bool Clipper2Lib::ClipperOffset::PreserveCollinear () const inline
{ return preserve_collinear_; }
References preserve_collinear_.
PreserveCollinear() [2/2]
void Clipper2Lib::ClipperOffset::PreserveCollinear (bool preserve_collinear) inline
{preserve_collinear_ = preserve_collinear;}
References preserve_collinear_.
ReverseSolution() [1/2]
bool Clipper2Lib::ClipperOffset::ReverseSolution () const inline
{ return reverse_solution_; }
References reverse_solution_.
ReverseSolution() [2/2]
void Clipper2Lib::ClipperOffset::ReverseSolution (bool reverse_solution) inline
{reverse_solution_ = reverse_solution;}
References reverse_solution_.
Member Data Documentation
abs_group_delta_
double Clipper2Lib::ClipperOffset::abs_group_delta_ = 0.0 private
Referenced by DoGroupOffset(), and DoSquare().
arc_tolerance_
double Clipper2Lib::ClipperOffset::arc_tolerance_ = 0.0 private
Referenced by ArcTolerance(), ArcTolerance(), and DoGroupOffset().
group_delta_
double Clipper2Lib::ClipperOffset::group_delta_ = 0.0 private
Referenced by DoGroupOffset(), DoMiter(), DoRound(), DoSquare(), OffsetOpenPath(), and OffsetPoint().
groups_
std::vector<Group> Clipper2Lib::ClipperOffset::groups_ private
Referenced by AddPaths(), AddPaths(), Clear(), and Execute().
join_type_
JoinType Clipper2Lib::ClipperOffset::join_type_ = JoinType::Square private
Referenced by DoGroupOffset(), and OffsetPoint().
merge_groups_
bool Clipper2Lib::ClipperOffset::merge_groups_ = true private
Referenced by DoGroupOffset(), Execute(), MergeGroups(), and MergeGroups().
miter_limit_
double Clipper2Lib::ClipperOffset::miter_limit_ = 0.0 private
Referenced by Execute(), MiterLimit(), and MiterLimit().
norms
PathD Clipper2Lib::ClipperOffset::norms private
Referenced by BuildNormals(), Clear(), DoMiter(), DoRound(), DoSquare(), OffsetOpenPath(), and OffsetPoint().
preserve_collinear_
bool Clipper2Lib::ClipperOffset::preserve_collinear_ = false private
Referenced by PreserveCollinear(), and PreserveCollinear().
reverse_solution_
bool Clipper2Lib::ClipperOffset::reverse_solution_ = false private
Referenced by DoGroupOffset(), Execute(), ReverseSolution(), and ReverseSolution().
solution
Paths64 Clipper2Lib::ClipperOffset::solution private
Referenced by DoGroupOffset(), and Execute().
steps_per_rad_
double Clipper2Lib::ClipperOffset::steps_per_rad_ = 0.0 private
Referenced by DoGroupOffset(), and DoRound().
temp_lim_
double Clipper2Lib::ClipperOffset::temp_lim_ = 0.0 private
Referenced by Execute(), and OffsetPoint().
The documentation for this class was generated from the following files:
src/clipper2/Clipper2Lib/include/clipper2/clipper.offset.h
src/clipper2/Clipper2Lib/src/clipper.offset.cpp