OrcaSlicer: Slic3r::GUI::Plater::priv Struct Reference
Slic3r::GUI::Plater::priv Struct Reference
Classes
class Jobs
Public Types
enum class UpdateParams { FORCE_FULL_SCREEN_REFRESH = 1 , FORCE_BACKGROUND_PROCESSING_UPDATE = 2 , POSTPONE_VALIDATION_ERROR_MESSAGE = 4 }
enum UpdateBackgroundProcessReturnState {
UPDATE_BACKGROUND_PROCESS_RESTART = 1 , UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE = 2 , UPDATE_BACKGROUND_PROCESS_INVALID = 4 , UPDATE_BACKGROUND_PROCESS_FORCE_RESTART = 8 ,
UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT = 16
}
Public Member Functions
priv (Plater *q, MainFrame *main_frame)
~priv ()
bool need_update () const
void set_need_update (bool need_update)
void set_plater_dirty (bool is_dirty)
bool is_project_dirty () const
bool is_presets_dirty () const
void update_project_dirty_from_presets ()
int save_project_if_dirty (const wxString &reason)
void reset_project_dirty_after_save ()
void reset_project_dirty_initial_presets ()
void update (unsigned int flags=0)
void select_view (const std::string &direction)
void select_view_3D (const std::string &name, bool no_slice=true)
void select_next_view_3D ()
bool is_preview_shown () const
bool is_preview_loaded () const
bool is_view3D_shown () const
bool is_assemble_view_show () const
bool are_view3D_labels_shown () const
void show_view3D_labels (bool show)
bool is_view3D_overhang_shown () const
void show_view3D_overhang (bool show)
bool is_sidebar_collapsed () const
void collapse_sidebar (bool collapse)
bool is_view3D_layers_editing_enabled () const
void set_current_canvas_as_dirty ()
GLCanvas3D * get_current_canvas3D (bool exclude_preview=false)
void unbind_canvas_event_handlers ()
void reset_canvas_volumes ()
bool init_collapse_toolbar ()
void hide_select_machine_dlg ()
void hide_send_to_printer_dlg ()
void update_preview_bottom_toolbar ()
void reset_gcode_toolpaths ()
void reset_all_gizmos ()
void apply_free_camera_correction (bool apply=true)
void update_ui_from_settings ()
std::shared_ptr< BBLStatusBar > statusbar ()
std::string get_config (const std::string &key) const
BoundingBoxf bed_shape_bb () const
BoundingBox scaled_bed_shape_bb () const
std::vector< size_t > load_files (const std::vector< fs::path > &input_files, LoadStrategy strategy, bool ask_multi=false)
std::vector< size_t > load_model_objects (const ModelObjectPtrs &model_objects, bool allow_negative_z=false, bool split_object=false)
fs::path get_export_file_path (GUI::FileType file_type)
wxString get_export_file (GUI::FileType file_type)
void load_auxiliary_files ()
const Selection & get_selection () const
Selection & get_selection ()
Selection & get_curr_selection ()
int get_selected_object_idx () const
int get_selected_volume_idx () const
void selection_changed ()
void object_list_changed ()
void select_curr_plate_all ()
void remove_curr_plate_all ()
void select_all ()
void deselect_all ()
void remove (size_t obj_idx)
bool delete_object_from_model (size_t obj_idx, bool refresh_immediately=true)
void delete_all_objects_from_model ()
void reset (bool apply_presets_change=false)
void center_selection ()
void mirror (Axis axis)
void split_object ()
void split_volume ()
void scale_selection_to_fit_print_volume ()
Slic3r::UndoRedo::Stack & undo_redo_stack ()
Slic3r::UndoRedo::Stack & undo_redo_stack_main ()
void enter_gizmos_stack ()
bool leave_gizmos_stack ()
void take_snapshot (const std::string &snapshot_name, UndoRedo::SnapshotType snapshot_type=UndoRedo::SnapshotType::Action)
int get_active_snapshot_index ()
void undo ()
void redo ()
void undo_redo_to (size_t time_to_load)
bool up_to_date (bool saved, bool backup)
void suppress_snapshots ()
void allow_snapshots ()
void single_snapshots_enter (SingleSnapshot *single)
void single_snapshots_leave (SingleSnapshot *single)
void process_validation_warning (StringObjectException const &warning) const
bool background_processing_enabled () const
void update_print_volume_state ()
void schedule_background_process ()
unsigned int update_background_process (bool force_validation=false, bool postpone_error_messages=false, bool switch_print=true)
bool restart_background_process (unsigned int state)
unsigned int update_restart_background_process (bool force_scene_update, bool force_preview_update)
void show_delayed_error_message ()
void export_gcode (fs::path output_path, bool output_path_on_removable_media)
void export_gcode (fs::path output_path, bool output_path_on_removable_media, PrintHostJob upload_job)
void reload_from_disk ()
bool replace_volume_with_stl (int object_idx, int volume_idx, const fs::path &new_path, const std::string &snapshot="")
void replace_with_stl ()
void reload_all_from_disk ()
void set_current_panel (wxPanel *panel, bool no_slice=true)
void on_combobox_select (wxCommandEvent &)
void on_select_bed_type (wxCommandEvent &)
void on_select_preset (wxCommandEvent &)
void on_slicing_update (SlicingStatusEvent &)
void on_slicing_completed (wxCommandEvent &)
void on_process_completed (SlicingProcessCompletedEvent &)
void on_export_began (wxCommandEvent &)
void on_export_finished (wxCommandEvent &)
void on_slicing_began ()
void clear_warnings ()
void add_warning (const Slic3r::PrintStateBase::Warning &warning, size_t oid)
void actualize_slicing_warnings (const PrintBase &print)
void actualize_object_warnings (const PrintBase &print)
bool warnings_dialog ()
void on_action_add (SimpleEvent &)
void on_action_add_plate (SimpleEvent &)
void on_action_del_plate (SimpleEvent &)
void on_action_split_objects (SimpleEvent &)
void on_action_split_volumes (SimpleEvent &)
void on_action_layersediting (SimpleEvent &)
void on_object_select (SimpleEvent &)
void on_right_click (RBtnEvent &)
void on_repair_model (wxCommandEvent &event)
void on_filament_color_changed (wxCommandEvent &event)
void show_install_plugin_hint (wxCommandEvent &event)
void install_network_plugin (wxCommandEvent &event)
void show_preview_only_hint (wxCommandEvent &event)
void on_plate_right_click (RBtnPlateEvent &)
void on_plate_selected (SimpleEvent &)
void on_action_request_model_id (wxCommandEvent &evt)
void on_action_download_project (wxCommandEvent &evt)
void on_slice_button_status (bool enable)
void on_action_open_project (SimpleEvent &)
void on_action_slice_plate (SimpleEvent &)
void on_action_slice_all (SimpleEvent &)
void on_action_publish (wxCommandEvent &evt)
void on_action_print_plate (SimpleEvent &)
void on_action_print_all (SimpleEvent &)
void on_action_export_gcode (SimpleEvent &)
void on_action_send_gcode (SimpleEvent &)
void on_action_export_sliced_file (SimpleEvent &)
void on_action_export_all_sliced_file (SimpleEvent &)
void on_action_select_sliced_plate (wxCommandEvent &evt)
void on_change_color_mode (SimpleEvent &evt)
void on_apple_change_color_mode (wxSysColourChangedEvent &evt)
void on_update_geometry (Vec3dsEvent< 2 > &)
void on_3dcanvas_mouse_dragging_started (SimpleEvent &)
void on_3dcanvas_mouse_dragging_finished (SimpleEvent &)
bool show_publish_dlg (bool show=true)
void update_publish_dialog_status (wxString &msg, int percent=-1)
void on_action_print_plate_from_sdcard (SimpleEvent &)
void set_bed_shape (const Pointfs &shape, const Pointfs &exclude_areas, const double printable_height, const std::string &custom_texture, const std::string &custom_model, bool force_as_custom=false)
bool can_delete () const
bool can_delete_all () const
bool can_edit_text () const
bool can_add_plate () const
bool can_delete_plate () const
bool can_increase_instances () const
bool can_decrease_instances () const
bool can_split_to_objects () const
bool can_split_to_volumes () const
bool can_arrange () const
bool can_layers_editing () const
bool can_fix_through_netfabb () const
bool can_simplify () const
bool can_set_instance_to_object () const
bool can_mirror () const
bool can_reload_from_disk () const
bool can_fillcolor () const
bool has_assemble_view () const
bool can_replace_with_stl () const
bool can_split (bool to_objects) const
void generate_thumbnail (ThumbnailData &data, unsigned int w, unsigned int h, const ThumbnailsParams &thumbnail_params, Camera::EType camera_type, bool use_top_view=false, bool for_picking=false)
ThumbnailsList generate_thumbnails (const ThumbnailsParams &params, Camera::EType camera_type)
void generate_calibration_thumbnail (ThumbnailData &data, unsigned int w, unsigned int h, const ThumbnailsParams &thumbnail_params)
PlateBBoxData generate_first_layer_bbox ()
void bring_instance_forward () const
wxString get_project_filename (const wxString &extension=wxEmptyString) const
wxString get_export_gcode_filename (const wxString &extension=wxEmptyString, bool only_filename=false, bool export_all=false) const
void set_project_filename (const wxString &filename)
wxString get_project_name ()
void set_project_name (const wxString &project_name)
void init_notification_manager ()
bool inside_snapshot_capture ()
void update_fff_scene_only_shells (bool only_shells=true)
bool PopupObjectTable (int object_id, int volume_id, const wxPoint &position)
void on_action_send_to_printer (bool isall=false)
Public Attributes
Plater * q
MainFrame * main_frame
MenuFactory menus
SelectMachineDialog * m_select_machine_dlg = nullptr
SendToPrinterDialog * m_send_to_sdcard_dlg = nullptr
PublishDialog * m_publish_dlg = nullptr
Slic3r::DynamicPrintConfig * config
Slic3r::Print fff_print
Slic3r::SLAPrint sla_print
Slic3r::Model model
PrinterTechnology printer_technology = ptFFF
Slic3r::GCodeProcessorResult gcode_result
wxSizer * panel_sizer { nullptr }
wxPanel * current_panel { nullptr }
std::vector< wxPanel * > panels
Sidebar * sidebar
Bed3D bed
Camera camera
PartPlateList partplate_list
bool m_ignore_event {false}
bool m_slice_all {false}
bool m_is_slicing {false}
bool m_is_publishing {false}
int m_is_RightClickInLeftUI {-1}
int m_cur_slice_plate
bool m_slice_all_only_has_gcode { false }
bool m_need_update {false}
Mouse3DController mouse3d_controller
View3D * view3D
GLToolbar collapse_toolbar
Preview * preview
AssembleView * assemble_view { nullptr }
bool first_enter_assemble { true }
std::unique_ptr< NotificationManager > notification_manager
ProjectDirtyStateManager dirty_state
BackgroundSlicingProcess background_process
bool suppressed_backround_processing_update { false }
Slic3r::GUI::Plater::priv::Jobs m_ui_jobs
int m_job_prepare_state
bool delayed_scene_refresh
std::string delayed_error_message
wxTimer background_process_timer
std::string label_btn_export
std::string label_btn_send
bool show_render_statistic_dialog { false }
bool show_wireframe { false }
bool wireframe_enabled { true }
bool m_is_dark = false
ExportingStatus exporting_status { NOT_EXPORTING }
std::string last_output_path
std::string last_output_dir_path
PrintPrepareData m_print_job_data
int process_completed_with_error { -1 }
BBLProject project
Static Public Attributes
static const std::regex pattern_bundle
static const std::regex pattern_3mf
static const std::regex pattern_zip_amf
static const std::regex pattern_any_amf
static const std::regex pattern_prusa
Private Member Functions
bool layers_height_allowed () const
void update_fff_scene ()
void update_sla_scene ()
void undo_redo_to (std::vector< UndoRedo::Snapshot >::const_iterator it_snapshot)
void update_after_undo_redo (const UndoRedo::Snapshot &snapshot, bool temp_snapshot_was_taken=false)
void on_action_export_to_sdcard (SimpleEvent &)
void on_action_export_to_sdcard_all (SimpleEvent &)
void update_plugin_when_launch (wxCommandEvent &event)
void record_start_print_preset (std::string action)
Private Attributes
boost::filesystem::path m_project_folder
wxString m_project_name
Slic3r::UndoRedo::Stack m_undo_redo_stack_main
Slic3r::UndoRedo::Stack m_undo_redo_stack_gizmos
Slic3r::UndoRedo::Stack * m_undo_redo_stack_active = &m_undo_redo_stack_main
int m_prevent_snapshots = 0
Plater::SingleSnapshot * m_single = nullptr
size_t m_saved_timestamp = 0
size_t m_backup_timestamp = 0
std::string m_last_fff_printer_profile_name
std::string m_last_sla_printer_profile_name
std::vector< std::pair< Slic3r::PrintStateBase::Warning, size_t > > current_warnings
bool show_warning_dialog { false }
Detailed Description
Member Enumeration Documentation
UpdateBackgroundProcessReturnState
enum Slic3r::GUI::Plater::priv::UpdateBackgroundProcessReturnState
Enumerator
UPDATE_BACKGROUND_PROCESS_RESTART
UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE
UPDATE_BACKGROUND_PROCESS_INVALID
UPDATE_BACKGROUND_PROCESS_FORCE_RESTART
UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT
{
        // update_background_process() reports, that the Print / SLAPrint was updated in a way,
        // that the background process was invalidated and it needs to be re-run.
        UPDATE_BACKGROUND_PROCESS_RESTART = 1,
        // update_background_process() reports, that the Print / SLAPrint was updated in a way,
        // that a scene needs to be refreshed (you should call _3DScene::reload_scene(canvas3Dwidget, false))
        UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE = 2,
        // update_background_process() reports, that the Print / SLAPrint is invalid, and the error message
        // was sent to the status line.
        UPDATE_BACKGROUND_PROCESS_INVALID = 4,
        // Restart even if the background processing is disabled.
        UPDATE_BACKGROUND_PROCESS_FORCE_RESTART = 8,
        // Restart for G-code (or SLA zip) export or upload.
        UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT = 16,
    };
UpdateParams
enum class Slic3r::GUI::Plater::priv::UpdateParams strong
Enumerator
FORCE_FULL_SCREEN_REFRESH
FORCE_BACKGROUND_PROCESSING_UPDATE
POSTPONE_VALIDATION_ERROR_MESSAGE
{
        FORCE_FULL_SCREEN_REFRESH          = 1,
        FORCE_BACKGROUND_PROCESSING_UPDATE = 2,
        POSTPONE_VALIDATION_ERROR_MESSAGE  = 4,
    };
Constructor & Destructor Documentation
priv()
Slic3r::GUI::Plater::priv::priv (Plater * q, MainFrame * main_frame)
    : q(q)
    , main_frame(main_frame)
    //BBS: add bed_exclude_area
    , config(Slic3r::DynamicPrintConfig::new_from_defaults_keys({
        "printable_area", "bed_exclude_area", "bed_custom_texture", "bed_custom_model", "print_sequence",
        "extruder_clearance_radius", "extruder_clearance_height_to_lid", "extruder_clearance_height_to_rod", "skirt_loops", "skirt_speed", "skirt_distance",
        "brim_width", "brim_object_gap", "brim_type", "nozzle_diameter", "single_extruder_multi_material",
        "enable_prime_tower", "wipe_tower_x", "wipe_tower_y", "prime_tower_width", "prime_tower_brim_width", "prime_volume",
        "extruder_colour", "filament_colour", "material_colour", "printable_height", "printer_model", "printer_technology",
        // These values are necessary to construct SlicingParameters by the Canvas3D variable layer height editor.
        "layer_height", "initial_layer_print_height", "min_layer_height", "max_layer_height",
        "brim_width", "wall_loops", "wall_filament", "sparse_infill_density", "sparse_infill_filament", "top_shell_layers",
        "enable_support", "support_filament", "support_interface_filament",
        "support_top_z_distance", "support_bottom_z_distance", "raft_layers"
        }))
    , sidebar(new Sidebar(q))
    , notification_manager(std::make_unique<NotificationManager>(q))
    , m_ui_jobs(this)
    , m_job_prepare_state(Job::JobPrepareState::PREPARE_STATE_DEFAULT)
    , delayed_scene_refresh(false)
    , collapse_toolbar(GLToolbar::Normal, "Collapse")
    //BBS :partplatelist construction
    , partplate_list(this->q, &model)
{
    this->q->SetFont(Slic3r::GUI::wxGetApp().normal_font());
    //BBS: use the first partplate's print for background process
    partplate_list.update_slice_context_to_current_plate(background_process);
    /*
    background_process.set_fff_print(&fff_print);
    background_process.set_sla_print(&sla_print);
    background_process.set_gcode_result(&gcode_result);
    background_process.set_thumbnail_cb([this](const ThumbnailsParams& params) { return this->generate_thumbnails(params, Camera::EType::Ortho); });
    background_process.set_slicing_completed_event(EVT_SLICING_COMPLETED);
    background_process.set_finished_event(EVT_PROCESS_COMPLETED);
    background_process.set_export_began_event(EVT_EXPORT_BEGAN);
    // Default printer technology for default config.
    background_process.select_technology(this->printer_technology);
    // Register progress callback from the Print class to the Plater.
    auto statuscb = [this](const Slic3r::PrintBase::SlicingStatus &status) {
        wxQueueEvent(this->q, new Slic3r::SlicingStatusEvent(EVT_SLICING_UPDATE, 0, status));
    };
    fff_print.set_status_callback(statuscb);
    sla_print.set_status_callback(statuscb); */
    // BBS: to be checked. Not follow patch.
    background_process.set_thumbnail_cb([this](const ThumbnailsParams& params) { return this->generate_thumbnails(params, Camera::EType::Ortho); });
    background_process.set_slicing_completed_event(EVT_SLICING_COMPLETED);
    background_process.set_finished_event(EVT_PROCESS_COMPLETED);
    background_process.set_export_began_event(EVT_EXPORT_BEGAN);
    background_process.set_export_finished_event(EVT_EXPORT_FINISHED);
    this->q->Bind(EVT_SLICING_UPDATE, &priv::on_slicing_update, this);
    this->q->Bind(EVT_PUBLISH, &priv::on_action_publish, this);
    this->q->Bind(EVT_REPAIR_MODEL, &priv::on_repair_model, this);
    this->q->Bind(EVT_FILAMENT_COLOR_CHANGED, &priv::on_filament_color_changed, this);
    this->q->Bind(EVT_INSTALL_PLUGIN_NETWORKING, &priv::install_network_plugin, this);
    this->q->Bind(EVT_INSTALL_PLUGIN_HINT, &priv::show_install_plugin_hint, this);
    this->q->Bind(EVT_UPDATE_PLUGINS_WHEN_LAUNCH, &priv::update_plugin_when_launch, this);
    this->q->Bind(EVT_PREVIEW_ONLY_MODE_HINT, &priv::show_preview_only_hint, this);
    this->q->Bind(EVT_GLCANVAS_COLOR_MODE_CHANGED, &priv::on_change_color_mode, this);
    this->q->Bind(wxEVT_SYS_COLOUR_CHANGED, &priv::on_apple_change_color_mode, this);
    view3D = new View3D(q, bed, &model, config, &background_process);
    //BBS: use partplater's gcode
    preview = new Preview(q, bed, &model, config, &background_process, partplate_list.get_current_slice_result(), [this]() { schedule_background_process(); });
    assemble_view = new AssembleView(q, bed, &model, config, &background_process);
#ifdef __APPLE__
    // BBS
    // set default view_toolbar icons size equal to GLGizmosManager::Default_Icons_Size
    //view_toolbar.set_icons_size(GLGizmosManager::Default_Icons_Size);
#endif // __APPLE__
    panels.push_back(view3D);
    panels.push_back(preview);
    panels.push_back(assemble_view);
    this->background_process_timer.SetOwner(this->q, 0);
    this->q->Bind(wxEVT_TIMER, [this](wxTimerEvent &evt)
    {
        if (!this->suppressed_backround_processing_update)
            this->update_restart_background_process(false, false);
    });
    update();
    auto* hsizer = new wxBoxSizer(wxHORIZONTAL);
    auto* vsizer = new wxBoxSizer(wxVERTICAL);
    // BBS: move sidebar to left side
    hsizer->Add(sidebar, 0, wxEXPAND | wxLEFT | wxRIGHT, 0);
    auto spliter_1 = new ::StaticLine(q, true);
    spliter_1->SetLineColour("#A6A9AA");
    hsizer->Add(spliter_1, 0, wxEXPAND);
    panel_sizer = new wxBoxSizer(wxHORIZONTAL);
    panel_sizer->Add(view3D, 1, wxEXPAND | wxALL, 0);
    panel_sizer->Add(preview, 1, wxEXPAND | wxALL, 0);
    panel_sizer->Add(assemble_view, 1, wxEXPAND | wxALL, 0);
    vsizer->Add(panel_sizer, 1, wxEXPAND | wxALL, 0);
    hsizer->Add(vsizer, 1, wxEXPAND | wxALL, 0);
    q->SetSizer(hsizer);
    menus.init(q);
    // Events:
    if (wxGetApp().is_editor()) {
        // Preset change event
        sidebar->Bind(wxEVT_COMBOBOX, &priv::on_combobox_select, this);
        sidebar->Bind(EVT_OBJ_LIST_OBJECT_SELECT, [this](wxEvent&) { priv::selection_changed(); });
        // BBS: should bind BACKGROUND_PROCESS event to plater
        q->Bind(EVT_SCHEDULE_BACKGROUND_PROCESS, [this](SimpleEvent&) { this->schedule_background_process(); });
        // jump to found option from SearchDialog
        q->Bind(wxCUSTOMEVT_JUMP_TO_OPTION, [this](wxCommandEvent& evt) { sidebar->jump_to_option(evt.GetInt()); });
    }
    wxGLCanvas* view3D_canvas = view3D->get_wxglcanvas();
    //BBS: GUI refactor
    wxGLCanvas* preview_canvas = preview->get_wxglcanvas();
    if (wxGetApp().is_editor()) {
        // 3DScene events:
        view3D_canvas->Bind(EVT_GLCANVAS_SCHEDULE_BACKGROUND_PROCESS, [this](SimpleEvent&) {
            delayed_error_message.clear();
            this->background_process_timer.Start(500, wxTIMER_ONE_SHOT);
            });
        view3D_canvas->Bind(EVT_GLCANVAS_OBJECT_SELECT, &priv::on_object_select, this);
        view3D_canvas->Bind(EVT_GLCANVAS_RIGHT_CLICK, &priv::on_right_click, this);
        //BBS: add part plate related logic
        view3D_canvas->Bind(EVT_GLCANVAS_PLATE_RIGHT_CLICK, &priv::on_plate_right_click, this);
        view3D_canvas->Bind(EVT_GLCANVAS_REMOVE_OBJECT, [q](SimpleEvent&) { q->remove_selected(); });
        view3D_canvas->Bind(EVT_GLCANVAS_ARRANGE, [this](SimpleEvent& evt) {
            //BBS arrage from EVT set default state.
            this->q->set_prepare_state(Job::PREPARE_STATE_DEFAULT);
            this->q->arrange(); });
        view3D_canvas->Bind(EVT_GLCANVAS_ARRANGE_PARTPLATE, [this](SimpleEvent& evt) {
            //BBS arrage from EVT set default state.
            this->q->set_prepare_state(Job::PREPARE_STATE_MENU);
            this->q->arrange(); });
        view3D_canvas->Bind(EVT_GLCANVAS_ORIENT, [this](SimpleEvent& evt) {
            //BBS oriant from EVT set default state.
            this->q->set_prepare_state(Job::PREPARE_STATE_DEFAULT);
            this->q->orient(); });
        view3D_canvas->Bind(EVT_GLCANVAS_ORIENT_PARTPLATE, [this](SimpleEvent& evt) {
            //BBS oriant from EVT set default state.
            this->q->set_prepare_state(Job::PREPARE_STATE_MENU);
            this->q->orient(); });
        //BBS
        view3D_canvas->Bind(EVT_GLCANVAS_SELECT_CURR_PLATE_ALL, [this](SimpleEvent&) {this->q->select_curr_plate_all(); });
        view3D_canvas->Bind(EVT_GLCANVAS_SELECT_ALL, [this](SimpleEvent&) { this->q->select_all(); });
        view3D_canvas->Bind(EVT_GLCANVAS_QUESTION_MARK, [](SimpleEvent&) { wxGetApp().keyboard_shortcuts(); });
        view3D_canvas->Bind(EVT_GLCANVAS_INCREASE_INSTANCES, [this](Event<int>& evt)
            { if (evt.data == 1) this->q->increase_instances(); else if (this->can_decrease_instances()) this->q->decrease_instances(); });
        view3D_canvas->Bind(EVT_GLCANVAS_INSTANCE_MOVED, [this](SimpleEvent&) { update(); });
        view3D_canvas->Bind(EVT_GLCANVAS_FORCE_UPDATE, [this](SimpleEvent&) { update(); });
        view3D_canvas->Bind(EVT_GLCANVAS_INSTANCE_ROTATED, [this](SimpleEvent&) { update(); });
        view3D_canvas->Bind(EVT_GLCANVAS_INSTANCE_SCALED, [this](SimpleEvent&) { update(); });
        // BBS
        //view3D_canvas->Bind(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS, [this](Event<bool>& evt) { this->sidebar->enable_buttons(evt.data); });
        view3D_canvas->Bind(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS, [this](Event<bool>& evt) { on_slice_button_status(evt.data); });
        view3D_canvas->Bind(EVT_GLCANVAS_UPDATE_GEOMETRY, &priv::on_update_geometry, this);
        view3D_canvas->Bind(EVT_GLCANVAS_MOUSE_DRAGGING_STARTED, &priv::on_3dcanvas_mouse_dragging_started, this);
        view3D_canvas->Bind(EVT_GLCANVAS_MOUSE_DRAGGING_FINISHED, &priv::on_3dcanvas_mouse_dragging_finished, this);
        view3D_canvas->Bind(EVT_GLCANVAS_TAB, [this](SimpleEvent&) { select_next_view_3D(); });
        view3D_canvas->Bind(EVT_GLCANVAS_RESETGIZMOS, [this](SimpleEvent&) { reset_all_gizmos(); });
        view3D_canvas->Bind(EVT_GLCANVAS_UNDO, [this](SimpleEvent&) { this->undo(); });
        view3D_canvas->Bind(EVT_GLCANVAS_REDO, [this](SimpleEvent&) { this->redo(); });
        view3D_canvas->Bind(EVT_GLCANVAS_COLLAPSE_SIDEBAR, [this](SimpleEvent&) { this->q->collapse_sidebar(!this->q->is_sidebar_collapsed());  });
        view3D_canvas->Bind(EVT_GLCANVAS_RESET_LAYER_HEIGHT_PROFILE, [this](SimpleEvent&) { this->view3D->get_canvas3d()->reset_layer_height_profile(); });
        view3D_canvas->Bind(EVT_GLCANVAS_ADAPTIVE_LAYER_HEIGHT_PROFILE, [this](Event<float>& evt) { this->view3D->get_canvas3d()->adaptive_layer_height_profile(evt.data); });
        view3D_canvas->Bind(EVT_GLCANVAS_SMOOTH_LAYER_HEIGHT_PROFILE, [this](HeightProfileSmoothEvent& evt) { this->view3D->get_canvas3d()->smooth_layer_height_profile(evt.data); });
        view3D_canvas->Bind(EVT_GLCANVAS_RELOAD_FROM_DISK, [this](SimpleEvent&) { this->reload_all_from_disk(); });
        // 3DScene/Toolbar:
        view3D_canvas->Bind(EVT_GLTOOLBAR_ADD, &priv::on_action_add, this);
        view3D_canvas->Bind(EVT_GLTOOLBAR_DELETE, [q](SimpleEvent&) { q->remove_selected(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_DELETE_ALL, [this](SimpleEvent&) { delete_all_objects_from_model(); });
//        view3D_canvas->Bind(EVT_GLTOOLBAR_DELETE_ALL, [q](SimpleEvent&) { q->reset_with_confirm(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_ADD_PLATE, &priv::on_action_add_plate, this);
        view3D_canvas->Bind(EVT_GLTOOLBAR_DEL_PLATE, &priv::on_action_del_plate, this);
        view3D_canvas->Bind(EVT_GLTOOLBAR_ORIENT, [this](SimpleEvent&) {
            //BBS arrage from EVT set default state.
            this->q->set_prepare_state(Job::PREPARE_STATE_DEFAULT);
            this->q->orient(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_ARRANGE, [this](SimpleEvent&) {
            //BBS arrage from EVT set default state.
            this->q->set_prepare_state(Job::PREPARE_STATE_DEFAULT);
            this->q->arrange();
            });
        view3D_canvas->Bind(EVT_GLTOOLBAR_CUT, [q](SimpleEvent&) { q->cut_selection_to_clipboard(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_COPY, [q](SimpleEvent&) { q->copy_selection_to_clipboard(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_PASTE, [q](SimpleEvent&) { q->paste_from_clipboard(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_LAYERSEDITING, &priv::on_action_layersediting, this);
        //BBS: add clone
        view3D_canvas->Bind(EVT_GLTOOLBAR_CLONE, [q](SimpleEvent&) { q->clone_selection(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_MORE, [q](SimpleEvent&) { q->increase_instances(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_FEWER, [q](SimpleEvent&) { q->decrease_instances(); });
        view3D_canvas->Bind(EVT_GLTOOLBAR_SPLIT_OBJECTS, &priv::on_action_split_objects, this);
        view3D_canvas->Bind(EVT_GLTOOLBAR_SPLIT_VOLUMES, &priv::on_action_split_volumes, this);
        //BBS: GUI refactor: GLToolbar
        view3D_canvas->Bind(EVT_GLTOOLBAR_OPEN_PROJECT, &priv::on_action_open_project, this);
        //view3D_canvas->Bind(EVT_GLTOOLBAR_SLICE_PLATE, &priv::on_action_slice_plate, this);
        //view3D_canvas->Bind(EVT_GLTOOLBAR_SLICE_ALL, &priv::on_action_slice_all, this);
        //view3D_canvas->Bind(EVT_GLTOOLBAR_PRINT_PLATE, &priv::on_action_print_plate, this);
        //view3D_canvas->Bind(EVT_GLTOOLBAR_PRINT_ALL, &priv::on_action_print_all, this);
        //view3D_canvas->Bind(EVT_GLTOOLBAR_EXPORT_GCODE, &priv::on_action_export_gcode, this);
        view3D_canvas->Bind(EVT_GLVIEWTOOLBAR_ASSEMBLE, [q](SimpleEvent&) { q->select_view_3D("Assemble"); });
        //preview also send these events
        //preview_canvas->Bind(EVT_GLTOOLBAR_SLICE_PLATE, &priv::on_action_slice_plate, this);
        //preview_canvas->Bind(EVT_GLTOOLBAR_PRINT_PLATE, &priv::on_action_print_plate, this);
        //preview_canvas->Bind(EVT_GLTOOLBAR_PRINT_ALL, &priv::on_action_print_all, this);
        //review_canvas->Bind(EVT_GLTOOLBAR_EXPORT_GCODE, &priv::on_action_export_gcode, this);
    }
    view3D_canvas->Bind(EVT_GLCANVAS_UPDATE_BED_SHAPE, [q](SimpleEvent&) { q->set_bed_shape(); });
    // Preview events:
    preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_QUESTION_MARK, [](SimpleEvent&) { wxGetApp().keyboard_shortcuts(); });
    preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_UPDATE_BED_SHAPE, [q](SimpleEvent&) { q->set_bed_shape(); });
    preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_UPDATE, [this](SimpleEvent &) {
            preview->get_canvas3d()->set_as_dirty();
        });
    if (wxGetApp().is_editor()) {
        preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_TAB, [this](SimpleEvent&) { select_next_view_3D(); });
        preview->get_wxglcanvas()->Bind(EVT_GLCANVAS_COLLAPSE_SIDEBAR, [this](SimpleEvent&) { this->q->collapse_sidebar(!this->q->is_sidebar_collapsed());  });
        preview->get_wxglcanvas()->Bind(EVT_CUSTOMEVT_TICKSCHANGED, [this](wxCommandEvent& event) {
            Type tick_event_type = (Type)event.GetInt();
            Model& model = wxGetApp().plater()->model();
            //BBS: replace model custom gcode with current plate custom gcode
            model.plates_custom_gcodes[model.curr_plate_index] = preview->get_canvas3d()->get_gcode_viewer().get_layers_slider()->GetTicksValues();
            // BBS set to invalid state only
            if (tick_event_type == Type::ToolChange || tick_event_type == Type::Custom || tick_event_type == Type::Template || tick_event_type == Type::PausePrint) {
                PartPlate *plate = this->q->get_partplate_list().get_curr_plate();
                if (plate) {
                    plate->update_slice_result_valid_state(false);
                }
            }
            set_plater_dirty(true);
            preview->on_tick_changed(tick_event_type);
            // update slice and print button
            wxGetApp().mainframe->update_slice_print_status(MainFrame::SlicePrintEventType::eEventSliceUpdate, true, false);
            update();
        });
    }
    if (wxGetApp().is_gcode_viewer())
        preview->Bind(EVT_GLCANVAS_RELOAD_FROM_DISK, [this](SimpleEvent&) { this->q->reload_gcode_from_disk(); });
    //BBS
    wxGLCanvas* assemble_canvas = assemble_view->get_wxglcanvas();
    if (wxGetApp().is_editor()) {
        assemble_canvas->Bind(EVT_GLTOOLBAR_FILLCOLOR, [q](IntEvent& evt) { q->fill_color(evt.get_data()); });
        assemble_canvas->Bind(EVT_GLCANVAS_OBJECT_SELECT, &priv::on_object_select, this);
        assemble_canvas->Bind(EVT_GLVIEWTOOLBAR_3D, [q](SimpleEvent&) { q->select_view_3D("3D"); });
        assemble_canvas->Bind(EVT_GLCANVAS_RIGHT_CLICK, &priv::on_right_click, this);
        assemble_canvas->Bind(EVT_GLCANVAS_UNDO, [this](SimpleEvent&) { this->undo(); });
        assemble_canvas->Bind(EVT_GLCANVAS_REDO, [this](SimpleEvent&) { this->redo(); });
    }
    if (wxGetApp().is_editor()) {
        q->Bind(EVT_SLICING_COMPLETED, &priv::on_slicing_completed, this);
        q->Bind(EVT_PROCESS_COMPLETED, &priv::on_process_completed, this);
        q->Bind(EVT_EXPORT_BEGAN, &priv::on_export_began, this);
        q->Bind(EVT_EXPORT_FINISHED, &priv::on_export_finished, this);
        q->Bind(EVT_GLVIEWTOOLBAR_3D, [q](SimpleEvent&) { q->select_view_3D("3D"); });
        //BBS: set on_slice to false
        q->Bind(EVT_GLVIEWTOOLBAR_PREVIEW, [q](SimpleEvent&) { q->select_view_3D("Preview", false); });
        q->Bind(EVT_GLTOOLBAR_SLICE_PLATE, &priv::on_action_slice_plate, this);
        q->Bind(EVT_GLTOOLBAR_SLICE_ALL, &priv::on_action_slice_all, this);
        q->Bind(EVT_GLTOOLBAR_PRINT_PLATE, &priv::on_action_print_plate, this);
        q->Bind(EVT_PRINT_FROM_SDCARD_VIEW, &priv::on_action_print_plate_from_sdcard, this);
        q->Bind(EVT_GLTOOLBAR_SELECT_SLICED_PLATE, &priv::on_action_select_sliced_plate, this);
        q->Bind(EVT_GLTOOLBAR_PRINT_ALL, &priv::on_action_print_all, this);
        q->Bind(EVT_GLTOOLBAR_EXPORT_GCODE, &priv::on_action_export_gcode, this);
        q->Bind(EVT_GLTOOLBAR_SEND_GCODE, &priv::on_action_send_gcode, this);
        q->Bind(EVT_GLTOOLBAR_EXPORT_SLICED_FILE, &priv::on_action_export_sliced_file, this);
        q->Bind(EVT_GLTOOLBAR_EXPORT_ALL_SLICED_FILE, &priv::on_action_export_all_sliced_file, this);
        q->Bind(EVT_GLTOOLBAR_SEND_TO_PRINTER, &priv::on_action_export_to_sdcard, this);
        q->Bind(EVT_GLTOOLBAR_SEND_TO_PRINTER_ALL, &priv::on_action_export_to_sdcard_all, this);
        q->Bind(EVT_GLCANVAS_PLATE_SELECT, &priv::on_plate_selected, this);
        q->Bind(EVT_DOWNLOAD_PROJECT, &priv::on_action_download_project, this);
        q->Bind(EVT_IMPORT_MODEL_ID, &priv::on_action_request_model_id, this);
        q->Bind(EVT_PRINT_FINISHED, [q](wxCommandEvent &evt) { q->print_job_finished(evt); });
        q->Bind(EVT_SEND_FINISHED, [q](wxCommandEvent &evt) { q->send_job_finished(evt); });
        q->Bind(EVT_PUBLISH_FINISHED, [q](wxCommandEvent &evt) { q->publish_job_finished(evt);});
        //q->Bind(EVT_GLVIEWTOOLBAR_ASSEMBLE, [q](SimpleEvent&) { q->select_view_3D("Assemble"); });
    }
    // Drop target:
    q->SetDropTarget(new PlaterDropTarget(q));   // if my understanding is right, wxWindow takes the owenership
    q->Layout();
    set_current_panel(wxGetApp().is_editor() ? static_cast<wxPanel*>(view3D) : static_cast<wxPanel*>(preview));
    // updates camera type from .ini file
    camera.enable_update_config_on_type_change(true);
    // BBS set config
    bool use_perspective_camera = get_config("use_perspective_camera").compare("true") == 0;
    if (use_perspective_camera) {
        camera.set_type(Camera::EType::Perspective);
    } else {
        camera.set_type(Camera::EType::Ortho);
    }
    // Load the 3DConnexion device database.
    mouse3d_controller.load_config(*wxGetApp().app_config);
    // Start the background thread to detect and connect to a HID device (Windows and Linux).
    // Connect to a 3DConnextion driver (OSX).
    mouse3d_controller.init();
#ifdef _WIN32
    // Register an USB HID (Human Interface Device) attach event. evt contains Win32 path to the USB device containing VID, PID and other info.
    // This event wakes up the Mouse3DController's background thread to enumerate HID devices, if the VID of the callback event
    // is one of the 3D Mouse vendors (3DConnexion or Logitech).
    this->q->Bind(EVT_HID_DEVICE_ATTACHED, [this](HIDDeviceAttachedEvent &evt) {
        mouse3d_controller.device_attached(evt.data);
        });
    this->q->Bind(EVT_HID_DEVICE_DETACHED, [this](HIDDeviceAttachedEvent& evt) {
        mouse3d_controller.device_detached(evt.data);
        });
#endif /* _WIN32 */
    //notification_manager = new NotificationManager(this->q);
    if (wxGetApp().is_editor()) {
        this->q->Bind(EVT_EJECT_DRIVE_NOTIFICAION_CLICKED, [this](EjectDriveNotificationClickedEvent&) { this->q->eject_drive(); });
        this->q->Bind(EVT_EXPORT_GCODE_NOTIFICAION_CLICKED, [this](ExportGcodeNotificationClickedEvent&) { this->q->export_gcode(true); });
        this->q->Bind(EVT_PRESET_UPDATE_AVAILABLE_CLICKED, [](PresetUpdateAvailableClickedEvent&) {  wxGetApp().get_preset_updater()->on_update_notification_confirm(); });
        /* BBS do not handle removeable driver event */
        this->q->Bind(EVT_REMOVABLE_DRIVE_EJECTED, [this](RemovableDriveEjectEvent &evt) {
            if (evt.data.second) {
                // BBS
                //this->show_action_buttons(this->ready_to_slice);
                notification_manager->close_notification_of_type(NotificationType::ExportFinished);
                notification_manager->push_notification(NotificationType::CustomNotification,
                                                        NotificationManager::NotificationLevel::RegularNotificationLevel,
                                                        format(_L("Successfully unmounted. The device %s(%s) can now be safely removed from the computer."), evt.data.first.name, evt.data.first.path)
                    );
            } else {
                notification_manager->push_notification(NotificationType::CustomNotification,
                                                        NotificationManager::NotificationLevel::ErrorNotificationLevel,
                                                        format(_L("Ejecting of device %s(%s) has failed."), evt.data.first.name, evt.data.first.path)
                    );
            }
        });
        this->q->Bind(EVT_REMOVABLE_DRIVES_CHANGED, [this](RemovableDrivesChangedEvent &) {
            // BBS
            //this->show_action_buttons(this->ready_to_slice);
            // Close notification ExportingFinished but only if last export was to removable
            notification_manager->device_ejected();
        });
        // Start the background thread and register this window as a target for update events.
        wxGetApp().removable_drive_manager()->init(this->q);
#ifdef _WIN32
        //Trigger enumeration of removable media on Win32 notification.
        this->q->Bind(EVT_VOLUME_ATTACHED, [this](VolumeAttachedEvent &evt) { wxGetApp().removable_drive_manager()->volumes_changed(); });
        this->q->Bind(EVT_VOLUME_DETACHED, [this](VolumeDetachedEvent &evt) { wxGetApp().removable_drive_manager()->volumes_changed(); });
#endif /* _WIN32 */
    }
    // Initialize the Undo / Redo stack with a first snapshot.
    //this->take_snapshot("New Project", UndoRedo::SnapshotType::ProjectSeparator);
    // Reset the "dirty project" flag.
    m_undo_redo_stack_main.mark_current_as_saved();
    dirty_state.update_from_undo_redo_stack(false);
    //this->take_snapshot("New Project");
    // BBS: save project confirm
    up_to_date(true, false);
    up_to_date(true, true);
    model.set_need_backup();
    // BBS: restore project
    if (wxGetApp().is_editor()) {
        auto last_backup = wxGetApp().app_config->get_last_backup_dir();
        this->q->Bind(EVT_RESTORE_PROJECT, [this, last = last_backup](wxCommandEvent& e) {
            std::string last_backup = last;
            std::string originfile;
            if (Slic3r::has_restore_data(last_backup, originfile)) {
                auto result = MessageDialog(this->q, _L("Previous unsaved project detected, do you want to restore it?"), wxString(SLIC3R_APP_FULL_NAME) + " - " + _L("Restore"), wxYES_NO | wxYES_DEFAULT | wxCENTRE).ShowModal();
                if (result == wxID_YES) {
                    this->q->load_project(from_path(last_backup), from_path(originfile));
                    Slic3r::backup_soon();
                    return;
                }
            }
            try {
                if (originfile != "<lock>") // see bbs_3mf.cpp for lock detail
                    boost::filesystem::remove_all(last);
            }
            catch (...) {}
            int skip_confirm = e.GetInt();
            this->q->new_project(skip_confirm, true);
            });
        //wxPostEvent(this->q, wxCommandEvent{EVT_RESTORE_PROJECT});
    }
    /*this->q->Bind(EVT_LOAD_MODEL_OTHER_INSTANCE, [this](LoadFromOtherInstanceEvent& evt) {
        BOOST_LOG_TRIVIAL(trace) << "Received load from other instance event.";
        wxArrayString input_files;
        for (size_t i = 0; i < evt.data.size(); ++i) {
            input_files.push_back(from_u8(evt.data[i].string()));
        }
        wxGetApp().mainframe->Raise();
        this->q->load_files(input_files);
    });
    this->q->Bind(EVT_INSTANCE_GO_TO_FRONT, [this](InstanceGoToFrontEvent &) {
        bring_instance_forward();
    });*/
    //wxGetApp().other_instance_message_handler()->init(this->q);
    // collapse sidebar according to saved value
    //if (wxGetApp().is_editor()) {
    //    bool is_collapsed = wxGetApp().app_config->get("collapsed_sidebar") == "1";
    //    sidebar->collapse(is_collapsed);
    //}
}
~priv()
Slic3r::GUI::Plater::priv::~priv ()
{
    if (config != nullptr)
        delete config;
    // Saves the database of visited (already shown) hints into hints.ini.
    notification_manager->deactivate_loaded_hints();
}
References Slic3r::GUI::Plater::config().
Member Function Documentation
actualize_object_warnings()
void Slic3r::GUI::Plater::priv::actualize_object_warnings (const PrintBase & print)
{
    std::vector<ObjectID> ids;
    for (const ModelObject* object : print.model().objects )
    {
        ids.push_back(object->id());
    }
    std::sort(ids.begin(), ids.end());
    notification_manager->remove_simplify_suggestion_of_released_objects(ids);
}
References Slic3r::PrintBase::model(), and Slic3r::Model::objects.
actualize_slicing_warnings()
void Slic3r::GUI::Plater::priv::actualize_slicing_warnings (const PrintBase & print)
{
    std::vector<ObjectID> ids = print.print_object_ids();
    if (ids.empty()) {
        clear_warnings();
        return;
    }
    ids.emplace_back(print.id());
    std::sort(ids.begin(), ids.end());
    notification_manager->remove_slicing_warnings_of_released_objects(ids);
    notification_manager->set_all_slicing_warnings_gray(true);
}
References Slic3r::ObjectBase::id(), and Slic3r::PrintBase::print_object_ids().
add_warning()
void Slic3r::GUI::Plater::priv::add_warning (const Slic3r::PrintStateBase::Warning & warning, size_t oid)
{
    for (auto& it : current_warnings) {
        if (warning.message_id == it.first.message_id) {
            if (warning.message_id != 0 || (warning.message_id == 0 && warning.message == it.first.message))
            {
                if (warning.message_id != 0)
                    it.first.message = warning.message;
                return;
            }
        }
    }
    current_warnings.emplace_back(std::pair<Slic3r::PrintStateBase::Warning, size_t>(warning, oid));
}
References Slic3r::PrintStateBase::Warning::message, and Slic3r::PrintStateBase::Warning::message_id.
allow_snapshots()
void Slic3r::GUI::Plater::priv::allow_snapshots () inline
{ m_prevent_snapshots--; }
References m_prevent_snapshots.
apply_free_camera_correction()
void Slic3r::GUI::Plater::priv::apply_free_camera_correction (bool apply = true)
{
    bool use_perspective_camera = get_config("use_perspective_camera").compare("true") == 0;
    if (use_perspective_camera)
        camera.set_type(Camera::EType::Perspective);
    else
        camera.set_type(Camera::EType::Ortho);
    if (apply
#ifdef SUPPORT_FREE_CAMERA
        && wxGetApp().app_config->get("use_free_camera") != "1"
#endif
        )
        camera.recover_from_free_camera();
}
References Slic3r::GUI::Camera::Ortho, and Slic3r::GUI::Camera::Perspective.
are_view3D_labels_shown()
bool Slic3r::GUI::Plater::priv::are_view3D_labels_shown () const inline
{ return (current_panel == view3D) && view3D->get_canvas3d()->are_labels_shown(); }
References Slic3r::GUI::GLCanvas3D::are_labels_shown(), current_panel, Slic3r::GUI::View3D::get_canvas3d(), and view3D.
background_processing_enabled()
bool Slic3r::GUI::Plater::priv::background_processing_enabled () const inline
{
#ifdef SUPPORT_BACKGROUND_PROCESSING
        return this->get_config("background_processing") == "1";
#else
        return false;
#endif
    }
References get_config().
bed_shape_bb()
BoundingBoxf Slic3r::GUI::Plater::priv::bed_shape_bb () const
{
    BoundingBox bb = scaled_bed_shape_bb();
    return BoundingBoxf(unscale(bb.min), unscale(bb.max));
}
References Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, and Slic3r::unscale().
bring_instance_forward()
void Slic3r::GUI::Plater::priv::bring_instance_forward () const
{
/*#ifdef __APPLE__
    wxGetApp().other_instance_message_handler()->bring_instance_forward();
    return;
#endif //__APPLE__*/
    if (main_frame == nullptr) {
        BOOST_LOG_TRIVIAL(debug) << "Couldnt bring instance forward - mainframe is null";
        return;
    }
    BOOST_LOG_TRIVIAL(debug) << "Orca Slicer window going forward";
    //this code maximize app window on Fedora
    {
        main_frame->Iconize(false);
        if (main_frame->IsMaximized())
            main_frame->Maximize(true);
        else
            main_frame->Maximize(false);
    }
    //this code maximize window on Ubuntu
    {
        main_frame->Restore();
        wxGetApp().GetTopWindow()->SetFocus();  // focus on my window
        wxGetApp().GetTopWindow()->Raise();  // bring window to front
        wxGetApp().GetTopWindow()->Show(true); // show the window
    }
}
can_add_plate()
bool Slic3r::GUI::Plater::priv::can_add_plate () const
{
    return q->get_partplate_list().get_plate_count() < PartPlateList::MAX_PLATES_COUNT;
}
References Slic3r::GUI::PartPlateList::MAX_PLATES_COUNT.
can_arrange()
bool Slic3r::GUI::Plater::priv::can_arrange () const
{
    return !model.objects.empty() && !m_ui_jobs.is_any_running();
}
References Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
can_decrease_instances()
bool Slic3r::GUI::Plater::priv::can_decrease_instances () const
{
    if (m_ui_jobs.is_any_running()
     || q->get_view3D_canvas3D()->get_gizmos_manager().is_in_editing_mode())
            return false;
    int obj_idx = get_selected_object_idx();
    return (0 <= obj_idx) && (obj_idx < (int)model.objects.size()) && (model.objects[obj_idx]->instances.size() > 1)
        && !sidebar->obj_list()->has_selected_cut_object();
}
References Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::ObjectList::has_selected_cut_object(), int, Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, and Slic3r::GUI::Plater::sidebar().
can_delete()
bool Slic3r::GUI::Plater::priv::can_delete () const
{
    return !get_selection().is_empty() && !get_selection().is_wipe_tower();
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::is_empty(), and Slic3r::GUI::Selection::is_wipe_tower().
can_delete_all()
bool Slic3r::GUI::Plater::priv::can_delete_all () const
{
    return !model.objects.empty();
}
References Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
can_delete_plate()
bool Slic3r::GUI::Plater::priv::can_delete_plate () const
{
    return q->get_partplate_list().get_plate_count() > 1;
}
can_edit_text()
bool Slic3r::GUI::Plater::priv::can_edit_text () const
{
    const Selection &selection = view3D->get_canvas3d()->get_selection();
    if (selection.is_single_full_instance())
        return true;
    if (selection.is_single_volume()) {
        const GLVolume *gl_volume      = selection.get_volume(*selection.get_volume_idxs().begin());
        int             out_object_idx = gl_volume->object_idx();
        ModelObject *   model_object   = selection.get_model()->objects[out_object_idx];
        int             out_volume_idx = gl_volume->volume_idx();
        ModelVolume *   model_volume   = model_object->volumes[out_volume_idx];
        if (model_volume)
            return !model_volume->get_text_info().m_text.empty();
    }
    return false;
}
References Slic3r::GUI::Selection::get_model(), Slic3r::ModelVolume::get_text_info(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_volume(), Slic3r::TextInfo::m_text, Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::GLVolume::volume_idx(), and Slic3r::ModelObject::volumes.
can_fillcolor()
bool Slic3r::GUI::Plater::priv::can_fillcolor () const
{
    //BBS TODO
    return true;
}
can_fix_through_netfabb()
bool Slic3r::GUI::Plater::priv::can_fix_through_netfabb () const
{
    std::vector<int> obj_idxs, vol_idxs;
    sidebar->obj_list()->get_selection_indexes(obj_idxs, vol_idxs);
#if FIX_THROUGH_NETFABB_ALWAYS
    // Fixing always.
    return ! obj_idxs.empty() || ! vol_idxs.empty();
#else // FIX_THROUGH_NETFABB_ALWAYS
    // Fixing only if the model is not manifold.
    if (vol_idxs.empty()) {
        for (auto obj_idx : obj_idxs)
            if (model.objects[obj_idx]->get_repaired_errors_count() > 0)
                return true;
        return false;
    }
    int obj_idx = obj_idxs.front();
    for (auto vol_idx : vol_idxs)
        if (model.objects[obj_idx]->get_repaired_errors_count(vol_idx) > 0)
            return true;
    return false;
#endif // FIX_THROUGH_NETFABB_ALWAYS
}
References Slic3r::GUI::ObjectList::get_selection_indexes(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, and Slic3r::GUI::Plater::sidebar().
can_increase_instances()
bool Slic3r::GUI::Plater::priv::can_increase_instances () const
{
    if (m_ui_jobs.is_any_running()
     || q->get_view3D_canvas3D()->get_gizmos_manager().is_in_editing_mode())
            return false;
    int obj_idx = get_selected_object_idx();
    return (0 <= obj_idx) && (obj_idx < (int)model.objects.size())
        && !sidebar->obj_list()->has_selected_cut_object();
}
References Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::ObjectList::has_selected_cut_object(), int, Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, and Slic3r::GUI::Plater::sidebar().
can_layers_editing()
bool Slic3r::GUI::Plater::priv::can_layers_editing () const
{
    return layers_height_allowed();
}
can_mirror()
bool Slic3r::GUI::Plater::priv::can_mirror () const
{
    return !sidebar->obj_list()->has_selected_cut_object()
        && get_selection().is_from_single_instance();
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Selection::is_from_single_instance(), Slic3r::GUI::Sidebar::obj_list(), and Slic3r::GUI::Plater::sidebar().
can_reload_from_disk()
bool Slic3r::GUI::Plater::priv::can_reload_from_disk () const
{
    if (sidebar->obj_list()->has_selected_cut_object())
        return false;
#if ENABLE_RELOAD_FROM_DISK_REWORK
    // collect selected reloadable ModelVolumes
    std::vector<std::pair<int, int>> selected_volumes = reloadable_volumes(model, get_selection());
    // nothing to reload, return
    if (selected_volumes.empty())
        return false;
#else
    // struct to hold selected ModelVolumes by their indices
    struct SelectedVolume
    {
        int object_idx;
        int volume_idx;
        // operators needed by std::algorithms
        bool operator < (const SelectedVolume& other) const { return (object_idx < other.object_idx) || ((object_idx == other.object_idx) && (volume_idx < other.volume_idx)); }
        bool operator == (const SelectedVolume& other) const { return (object_idx == other.object_idx) && (volume_idx == other.volume_idx); }
    };
    std::vector<SelectedVolume> selected_volumes;
    const Selection& selection = get_selection();
    // collects selected ModelVolumes
    const std::set<unsigned int>& selected_volumes_idxs = selection.get_volume_idxs();
    for (unsigned int idx : selected_volumes_idxs) {
        const GLVolume* v = selection.get_volume(idx);
        int v_idx = v->volume_idx();
        if (v_idx >= 0) {
            int o_idx = v->object_idx();
            if (0 <= o_idx && o_idx < (int)model.objects.size())
                selected_volumes.push_back({ o_idx, v_idx });
        }
    }
#endif // ENABLE_RELOAD_FROM_DISK_REWORK
#if ENABLE_RELOAD_FROM_DISK_REWORK
    std::sort(selected_volumes.begin(), selected_volumes.end(), [](const std::pair<int, int> &v1, const std::pair<int, int> &v2) {
        return (v1.first < v2.first) || (v1.first == v2.first && v1.second < v2.second);
        });
    selected_volumes.erase(std::unique(selected_volumes.begin(), selected_volumes.end(), [](const std::pair<int, int> &v1, const std::pair<int, int> &v2) {
        return (v1.first == v2.first) && (v1.second == v2.second);
        }), selected_volumes.end());
    // collects paths of files to load
    std::vector<fs::path> paths;
    for (auto [obj_idx, vol_idx] : selected_volumes) {
        paths.push_back(model.objects[obj_idx]->volumes[vol_idx]->source.input_file);
    }
#else
    std::sort(selected_volumes.begin(), selected_volumes.end());
    selected_volumes.erase(std::unique(selected_volumes.begin(), selected_volumes.end()), selected_volumes.end());
    // collects paths of files to load
    std::vector<fs::path> paths;
    for (const SelectedVolume& v : selected_volumes) {
        const ModelObject* object = model.objects[v.object_idx];
        const ModelVolume* volume = object->volumes[v.volume_idx];
        if (!volume->source.input_file.empty())
            paths.push_back(volume->source.input_file);
        else if (!object->input_file.empty() && !volume->name.empty() && !volume->source.is_from_builtin_objects)
            paths.push_back(volume->name);
    }
#endif // ENABLE_RELOAD_FROM_DISK_REWORK
    std::sort(paths.begin(), paths.end());
    paths.erase(std::unique(paths.begin(), paths.end()), paths.end());
    return !paths.empty();
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::GUI::operator<(), operator==(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GLVolume::volume_idx().
can_replace_with_stl()
bool Slic3r::GUI::Plater::priv::can_replace_with_stl () const
{
    return !sidebar->obj_list()->has_selected_cut_object()
        && get_selection().get_volume_idxs().size() == 1;
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::ObjectList::has_selected_cut_object(), Slic3r::GUI::Sidebar::obj_list(), and Slic3r::GUI::Plater::sidebar().
can_set_instance_to_object()
bool Slic3r::GUI::Plater::priv::can_set_instance_to_object () const
{
    const int obj_idx = get_selected_object_idx();
    return 0 <= obj_idx && obj_idx < (int)model.objects.size() && model.objects[obj_idx]->instances.size() > 1;
}
References Slic3r::GUI::Plater::get_selected_object_idx(), int, Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
can_simplify()
bool Slic3r::GUI::Plater::priv::can_simplify () const
{
    // is object for simplification selected
    if (get_selected_object_idx() < 0) return false;
    // is already opened?
    if (q->get_view3D_canvas3D()->get_gizmos_manager().get_current_type() ==
        GLGizmosManager::EType::Simplify)
        return false;
    return true;
}
References Slic3r::GUI::Plater::get_selected_object_idx(), and Slic3r::GUI::GLGizmosManager::Simplify.
can_split()
bool Slic3r::GUI::Plater::priv::can_split (bool to_objects) const
{
    return sidebar->obj_list()->is_splittable(to_objects);
}
References Slic3r::GUI::ObjectList::is_splittable(), Slic3r::GUI::Sidebar::obj_list(), and Slic3r::GUI::Plater::sidebar().
can_split_to_objects()
bool Slic3r::GUI::Plater::priv::can_split_to_objects () const
{
    return q->can_split(true);
}
can_split_to_volumes()
bool Slic3r::GUI::Plater::priv::can_split_to_volumes () const
{
    return (printer_technology != ptSLA) && q->can_split(false);
}
References Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptSLA.
center_selection()
void Slic3r::GUI::Plater::priv::center_selection ()
{
    view3D->center_selected();
}
clear_warnings()
void Slic3r::GUI::Plater::priv::clear_warnings ()
{
    notification_manager->close_slicing_errors_and_warnings();
    this->current_warnings.clear();
}
collapse_sidebar()
void Slic3r::GUI::Plater::priv::collapse_sidebar (bool collapse)
{
    if (q->m_only_gcode && !collapse)
        return;
    sidebar->collapse(collapse);
    notification_manager->set_sidebar_collapsed(collapse);
}
References Slic3r::GUI::Sidebar::collapse(), and Slic3r::GUI::Plater::sidebar().
delete_all_objects_from_model()
void Slic3r::GUI::Plater::priv::delete_all_objects_from_model ()
{
    Plater::TakeSnapshot snapshot(q, "Delete All Objects");
    if (view3D->is_layers_editing_enabled())
        view3D->enable_layers_editing(false);
    reset_gcode_toolpaths();
    gcode_result.reset();
    view3D->get_canvas3d()->reset_sequential_print_clearance();
    m_ui_jobs.cancel_all();
    // Stop and reset the Print content.
    background_process.reset();
    //BBS: update partplate
    partplate_list.clear();
    model.clear_objects();
    update();
    // Delete object from Sidebar list. Do it after update, so that the GLScene selection is updated with the modified model.
    sidebar->obj_list()->delete_all_objects_from_list();
    object_list_changed();
    //BBS
    model.calib_pa_pattern.reset();
    model.plates_custom_gcodes.clear();
}
References Slic3r::Model::calib_pa_pattern, Slic3r::Model::clear_objects(), Slic3r::GUI::ObjectList::delete_all_objects_from_list(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::object_list_changed(), Slic3r::Model::plates_custom_gcodes, Slic3r::GUI::Plater::reset_gcode_toolpaths(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Plater::update().
delete_object_from_model()
bool Slic3r::GUI::Plater::priv::delete_object_from_model (size_t obj_idx, bool refresh_immediately = true)
{
    // check if object isn't cut
    // show warning message that "cut consistancy" will not be supported any more
    ModelObject *obj = model.objects[obj_idx];
    if (obj->is_cut()) {
        InfoDialog dialog(q, _L("Delete object which is a part of cut object"),
                          _L("You try to delete an object which is a part of a cut object.\n"
                             "This action will break a cut correspondence.\n"
                             "After that model consistency can't be guaranteed."),
                          false, wxYES | wxCANCEL | wxCANCEL_DEFAULT | wxICON_WARNING);
        dialog.SetButtonLabel(wxID_YES, _L("Delete"));
        if (dialog.ShowModal() == wxID_CANCEL)
            return false;
    }
    std::string snapshot_label = "Delete Object";
    if (!obj->name.empty())
        snapshot_label += ": " + obj->name;
    Plater::TakeSnapshot snapshot(q, snapshot_label);
    m_ui_jobs.cancel_all();
    if (obj->is_cut())
        sidebar->obj_list()->invalidate_cut_info_for_object(obj_idx);
    model.delete_object(obj_idx);
    //BBS: notify partplate the instance removed
    partplate_list.notify_instance_removed(obj_idx, -1);
    //BBS
    if (refresh_immediately) {
        update();
        object_list_changed();
    }
    return true;
}
References _L, Slic3r::Model::delete_object(), Slic3r::GUI::ObjectList::invalidate_cut_info_for_object(), Slic3r::ModelObject::is_cut(), Slic3r::GUI::Plater::model(), Slic3r::ModelObject::name, Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::object_list_changed(), Slic3r::Model::objects, Slic3r::GUI::MsgDialog::SetButtonLabel(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Plater::update().
deselect_all()
void Slic3r::GUI::Plater::priv::deselect_all ()
{
    view3D->deselect_all();
}
enter_gizmos_stack()
void Slic3r::GUI::Plater::priv::enter_gizmos_stack ()
{
    assert(m_undo_redo_stack_active == &m_undo_redo_stack_main);
    if (m_undo_redo_stack_active == &m_undo_redo_stack_main) {
        m_undo_redo_stack_active = &m_undo_redo_stack_gizmos;
        assert(m_undo_redo_stack_active->empty());
        // Take the initial snapshot of the gizmos.
        // Not localized on purpose, the text will never be shown to the user.
        this->take_snapshot(std::string("Gizmos-Initial"));
    }
}
References Slic3r::GUI::Plater::take_snapshot().
export_gcode() [1/2]
void Slic3r::GUI::Plater::priv::export_gcode (fs::path output_path, bool output_path_on_removable_media)
{
    wxCHECK_RET(!(output_path.empty()), "export_gcode: output_path and upload_job empty");
    BOOST_LOG_TRIVIAL(info) << boost::format("export_gcode: output_path %1%")%output_path.string();
    if (model.objects.empty())
        return;
    if (background_process.is_export_scheduled()) {
        GUI::show_error(q, _L("Another export job is running."));
        return;
    }
    // bitmask of UpdateBackgroundProcessReturnState
    unsigned int state = update_background_process(true);
    if (state & priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE)
        view3D->reload_scene(false);
    if ((state & priv::UPDATE_BACKGROUND_PROCESS_INVALID) != 0)
        return;
    show_warning_dialog = true;
    if (! output_path.empty()) {
        background_process.schedule_export(output_path.string(), output_path_on_removable_media);
        notification_manager->push_delayed_notification(NotificationType::ExportOngoing, []() {return true; }, 1000, 0);
    } else {
        BOOST_LOG_TRIVIAL(info) << "output_path  is empty";
    }
    // If the SLA processing of just a single object's supports is running, restart slicing for the whole object.
    this->background_process.set_task(PrintBase::TaskParams());
    this->restart_background_process(priv::UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT);
}
References _L, Slic3r::GUI::ExportOngoing, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::show_error(), UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT, UPDATE_BACKGROUND_PROCESS_INVALID, and UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE.
export_gcode() [2/2]
void Slic3r::GUI::Plater::priv::export_gcode (fs::path output_path, bool output_path_on_removable_media, PrintHostJob upload_job)
{
    wxCHECK_RET(!(output_path.empty() && upload_job.empty()), "export_gcode: output_path and upload_job empty");
    if (model.objects.empty())
        return;
    if (background_process.is_export_scheduled()) {
        GUI::show_error(q, _L("Another export job is running."));
        return;
    }
    // bitmask of UpdateBackgroundProcessReturnState
    unsigned int state = update_background_process(true);
    if (state & priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE)
        view3D->reload_scene(false);
    if ((state & priv::UPDATE_BACKGROUND_PROCESS_INVALID) != 0)
        return;
    show_warning_dialog = true;
    if (! output_path.empty()) {
        background_process.schedule_export(output_path.string(), output_path_on_removable_media);
        notification_manager->push_delayed_notification(NotificationType::ExportOngoing, []() {return true; }, 1000, 0);
    } else {
        background_process.schedule_upload(std::move(upload_job));
    }
    // If the SLA processing of just a single object's supports is running, restart slicing for the whole object.
    this->background_process.set_task(PrintBase::TaskParams());
    this->restart_background_process(priv::UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT);
}
References _L, Slic3r::PrintHostJob::empty(), Slic3r::GUI::ExportOngoing, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::show_error(), UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT, UPDATE_BACKGROUND_PROCESS_INVALID, and UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE.
generate_calibration_thumbnail()
void Slic3r::GUI::Plater::priv::generate_calibration_thumbnail (ThumbnailData & data, unsigned int w, unsigned int h, const ThumbnailsParams & thumbnail_params)
{
    preview->get_canvas3d()->render_calibration_thumbnail(data, w, h, thumbnail_params);
}
generate_first_layer_bbox()
PlateBBoxData Slic3r::GUI::Plater::priv::generate_first_layer_bbox ()
{
    PlateBBoxData bboxdata;
    std::vector<BBoxData>& id_bboxes = bboxdata.bbox_objs;
    BoundingBoxf bbox_all;
    auto                   print = this->background_process.m_fff_print;
    auto curr_plate = this->partplate_list.get_curr_plate();
    auto curr_plate_seq = curr_plate->get_real_print_seq();
    bboxdata.is_seq_print = (curr_plate_seq == PrintSequence::ByObject);
    bboxdata.first_extruder = print->get_tool_ordering().first_extruder();
    bboxdata.bed_type       = bed_type_to_gcode_string(print->config().curr_bed_type.value);
    // get nozzle diameter
    auto opt_nozzle_diameters = print->config().option<ConfigOptionFloats>("nozzle_diameter");
    if (opt_nozzle_diameters != nullptr)
        bboxdata.nozzle_diameter = float(opt_nozzle_diameters->get_at(bboxdata.first_extruder));
    //PrintObjectPtrs objects;
    //if (this->printer_technology == ptFFF) {
    //    objects = this->background_process.m_fff_print->objects().vector();
    //}
    //else {
    //    objects = this->background_process.m_sla_print->objects();
    //}
    auto objects = print->objects();
    auto orig = this->partplate_list.get_curr_plate()->get_origin();
    Vec2d orig2d = { orig[0], orig[1] };
    BBoxData data;
    for (auto obj : objects)
    {
        auto bb_scaled = obj->get_first_layer_bbox(data.area, data.layer_height, data.name);
        auto bb = unscaled(bb_scaled);
        bb.min -= orig2d;
        bb.max -= orig2d;
        bbox_all.merge(bb);
        data.area *= (SCALING_FACTOR * SCALING_FACTOR); // unscale area
        data.id = obj->id().id;
        data.bbox = { bb.min.x(),bb.min.y(),bb.max.x(),bb.max.y() };
        id_bboxes.emplace_back(data);
    }
    // add wipe tower bounding box
    if (print->has_wipe_tower()) {
        auto   wt_corners = print->first_layer_wipe_tower_corners();
        // when loading gcode.3mf, wipe tower info may not be correct
        if (!wt_corners.empty()) {
            BoundingBox bb_scaled = {wt_corners[0], wt_corners[2]};
            auto        bb        = unscaled(bb_scaled);
            bb.min -= orig2d;
            bb.max -= orig2d;
            bbox_all.merge(bb);
            data.name = "wipe_tower";
            data.id   = partplate_list.get_curr_plate()->get_index() + 1000;
            data.bbox = {bb.min.x(), bb.min.y(), bb.max.x(), bb.max.y()};
            id_bboxes.emplace_back(data);
        }
    }
    bboxdata.bbox_all = { bbox_all.min.x(),bbox_all.min.y(),bbox_all.max.x(),bbox_all.max.y() };
    return bboxdata;
}
References Slic3r::BBoxData::area, Slic3r::BBoxData::bbox, Slic3r::PlateBBoxData::bbox_all, Slic3r::PlateBBoxData::bbox_objs, Slic3r::PlateBBoxData::bed_type, Slic3r::bed_type_to_gcode_string(), Slic3r::ByObject, Slic3r::PlateBBoxData::first_extruder, Slic3r::BBoxData::id, Slic3r::PlateBBoxData::is_seq_print, Slic3r::BBoxData::layer_height, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::BBoxData::name, Slic3r::PlateBBoxData::nozzle_diameter, SCALING_FACTOR, and Slic3r::unscaled().
generate_thumbnail()
void Slic3r::GUI::Plater::priv::generate_thumbnail (ThumbnailData & data, unsigned int w, unsigned int h, const ThumbnailsParams & thumbnail_params, Camera::EType camera_type, bool use_top_view = false, bool for_picking = false)
{
    view3D->get_canvas3d()->render_thumbnail(data, w, h, thumbnail_params, camera_type, use_top_view, for_picking);
}
generate_thumbnails()
ThumbnailsList Slic3r::GUI::Plater::priv::generate_thumbnails (const ThumbnailsParams & params, Camera::EType camera_type)
{
    ThumbnailsList thumbnails;
    for (const Vec2d& size : params.sizes) {
        thumbnails.push_back(ThumbnailData());
        Point isize(size); // round to ints
        generate_thumbnail(thumbnails.back(), isize.x(), isize.y(), params, camera_type);
        if (!thumbnails.back().is_valid())
            thumbnails.pop_back();
    }
    return thumbnails;
}
References size, Slic3r::ThumbnailsParams::sizes, and Slic3r::thumbnails().
get_active_snapshot_index()
int Slic3r::GUI::Plater::priv::get_active_snapshot_index ()
{
    const size_t active_snapshot_time = this->undo_redo_stack().active_snapshot_time();
    const std::vector<UndoRedo::Snapshot>& ss_stack = this->undo_redo_stack().snapshots();
    const auto it = std::lower_bound(ss_stack.begin(), ss_stack.end(), UndoRedo::Snapshot(active_snapshot_time));
    return it - ss_stack.begin();
}
get_config()
std::string Slic3r::GUI::Plater::priv::get_config (const std::string & key) const
{
    return wxGetApp().app_config->get(key);
}
Referenced by background_processing_enabled().
get_curr_selection()
Selection & Slic3r::GUI::Plater::priv::get_curr_selection ()
{
    return get_current_canvas3D()->get_selection();
}
References Slic3r::GUI::Plater::get_current_canvas3D(), and Slic3r::GUI::GLCanvas3D::get_selection().
get_current_canvas3D()
GLCanvas3D * Slic3r::GUI::Plater::priv::get_current_canvas3D (bool exclude_preview = false)
{
    if (current_panel == view3D)
        return view3D->get_canvas3d();
    else if (!exclude_preview && (current_panel == preview))
        return preview->get_canvas3d();
    else if (current_panel == assemble_view)
        return assemble_view->get_canvas3d();
    else //BBS default set to view3D
        return view3D->get_canvas3d();
    //return (current_panel == view3D) ? view3D->get_canvas3d() : ((current_panel == preview) ? preview->get_canvas3d() : nullptr);
}
get_export_file()
wxString Slic3r::GUI::Plater::priv::get_export_file (GUI::FileType file_type)
{
    wxString wildcard;
    switch (file_type) {
        case FT_STL:
        case FT_AMF:
        case FT_3MF:
        case FT_GCODE:
        case FT_OBJ:
            wildcard = file_wildcards(file_type);
        break;
        default:
            wildcard = file_wildcards(FT_MODEL);
        break;
    }
    fs::path output_file = get_export_file_path(file_type);
    wxString dlg_title;
    switch (file_type) {
        case FT_STL:
        {
            output_file.replace_extension("stl");
            dlg_title = _L("Export STL file:");
            break;
        }
        case FT_AMF:
        {
            // XXX: Problem on OS X with double extension?
            output_file.replace_extension("zip.amf");
            dlg_title = _devL("Export AMF file:");
            break;
        }
        case FT_3MF:
        {
            output_file.replace_extension("3mf");
            dlg_title = _L("Save file as:");
            break;
        }
        case FT_OBJ:
        {
            output_file.replace_extension("obj");
            dlg_title = _devL("Export OBJ file:");
            break;
        }
        default: break;
    }
    std::string out_dir = (boost::filesystem::path(output_file).parent_path()).string();
    wxFileDialog dlg(q, dlg_title,
        is_shapes_dir(out_dir) ? from_u8(wxGetApp().app_config->get_last_dir()) : from_path(output_file.parent_path()), from_path(output_file.filename()),
        wildcard, wxFD_SAVE | wxFD_OVERWRITE_PROMPT | wxPD_APP_MODAL);
    int result = dlg.ShowModal();
    if (result == wxID_CANCEL)
        return "<cancel>";
    if (result != wxID_OK)
        return wxEmptyString;
    wxString out_path = dlg.GetPath();
    fs::path path(into_path(out_path));
    wxGetApp().app_config->update_last_output_dir(path.parent_path().string());
    return out_path;
}
References _devL, _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::from_path(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_3MF, Slic3r::GUI::FT_AMF, Slic3r::GUI::FT_GCODE, Slic3r::GUI::FT_MODEL, Slic3r::GUI::FT_OBJ, Slic3r::GUI::FT_STL, Slic3r::GUI::into_path(), and Slic3r::is_shapes_dir().
get_export_file_path()
fs::path Slic3r::GUI::Plater::priv::get_export_file_path (GUI::FileType file_type)
{
    // Update printbility state of each of the ModelInstances.
    this->update_print_volume_state();
    const Selection& selection = get_selection();
    int obj_idx = selection.get_object_idx();
    fs::path output_file;
    if (file_type == FT_3MF)
        // for 3mf take the path from the project filename, if any
        output_file = into_path(get_project_filename(".3mf"));
    //bbs  name the project using the part name
    if (output_file.empty()) {
        if (get_project_name() != _L("Untitled")) {
            output_file = into_path(get_project_name() + ".3mf");
        }
    }
    if (output_file.empty())
    {
        // first try to get the file name from the current selection
        if ((0 <= obj_idx) && (obj_idx < (int)this->model.objects.size()))
            output_file = this->model.objects[obj_idx]->get_export_filename();
        if (output_file.empty())
            // Find the file name of the first printable object.
            output_file = this->model.propose_export_file_name_and_path();
        if (output_file.empty() && !model.objects.empty())
            // Find the file name of the first object.
            output_file = this->model.objects[0]->get_export_filename();
        if (output_file.empty())
            // Use _L("Untitled") name
            output_file = into_path(_L("Untitled"));
    }
    return output_file;
}
References _L, Slic3r::GUI::FT_3MF, Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::Plater::get_project_filename(), Slic3r::GUI::Plater::get_project_name(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::into_path(), Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
Referenced by save_project_if_dirty().
get_export_gcode_filename()
wxString Slic3r::GUI::Plater::priv::get_export_gcode_filename (const wxString & extension = wxEmptyString, bool only_filename = false, bool export_all = false) const
{
    std::string plate_index_str;
    auto plate_name = partplate_list.get_curr_plate()->get_plate_name();
    if (!plate_name.empty())
        plate_index_str = (boost::format("_%1%") % plate_name).str();
    else if (partplate_list.get_plate_count() > 1)
        plate_index_str = (boost::format("_plate_%1%") % std::to_string(partplate_list.get_curr_plate_index() + 1)).str();
    if (!m_project_folder.empty()) {
        if (!only_filename) {
            if (export_all) {
                auto full_filename = m_project_folder / std::string((m_project_name + extension).mb_str(wxConvUTF8));
                return from_path(full_filename);
            } else {
                auto full_filename = m_project_folder / std::string((m_project_name + from_u8(plate_index_str) + extension).mb_str(wxConvUTF8));
                return from_path(full_filename);
            }
        } else {
            if (export_all)
                return m_project_name + from_u8(plate_index_str) + extension;
            else
                return m_project_name + extension;
        }
    } else {
        if (only_filename) {
            if(m_project_name == _L("Untitled"))
                return wxString(fs::path(model.objects.front()->name).replace_extension().c_str()) + from_u8(plate_index_str) + extension;
            if (export_all)
                return m_project_name + extension;
            else
                return m_project_name + from_u8(plate_index_str) + extension;
        }
        else
            return "";
    }
}
References _L, Slic3r::GUI::from_path(), Slic3r::GUI::from_u8(), Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
get_project_filename()
wxString Slic3r::GUI::Plater::priv::get_project_filename (const wxString & extension = wxEmptyString) const
{
    if (m_project_name.empty())
        return "";
    else {
        auto full_filename = m_project_folder / std::string((m_project_name + extension).mb_str(wxConvUTF8));
        return m_project_folder.empty() ? "" : from_path(full_filename);
    }
}
References Slic3r::GUI::from_path().
Referenced by save_project_if_dirty().
get_project_name()
wxString Slic3r::GUI::Plater::priv::get_project_name ()
{
    return m_project_name;
}
get_selected_object_idx()
int Slic3r::GUI::Plater::priv::get_selected_object_idx () const
{
    int idx = get_selection().get_object_idx();
    return ((0 <= idx) && (idx < 1000)) ? idx : -1;
}
References Slic3r::GUI::Selection::get_object_idx(), and Slic3r::GUI::Plater::get_selection().
get_selected_volume_idx()
int Slic3r::GUI::Plater::priv::get_selected_volume_idx () const
{
    auto& selection = get_selection();
    int idx = selection.get_object_idx();
    if ((0 > idx) || (idx > 1000))
        return-1;
    const GLVolume* v = selection.get_volume(*selection.get_volume_idxs().begin());
    if (model.objects[idx]->volumes.size() > 1)
        return v->volume_idx();
    return -1;
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, and Slic3r::GLVolume::volume_idx().
get_selection() [1/2]
Selection & Slic3r::GUI::Plater::priv::get_selection ()
{
    return view3D->get_canvas3d()->get_selection();
}
get_selection() [2/2]
const Selection & Slic3r::GUI::Plater::priv::get_selection () const
{
    return view3D->get_canvas3d()->get_selection();
}
has_assemble_view()
bool Slic3r::GUI::Plater::priv::has_assemble_view () const
{
    for (auto object: model.objects)
    {
        for (auto instance : object->instances)
            if (instance->is_assemble_initialized())
                return true;
        int part_cnt = 0;
        for (auto volume : object->volumes) {
            if (volume->is_model_part())
                part_cnt++;
        }
        if (part_cnt > 1)
            return true;
    }
    return false;
}
References Slic3r::GUI::Plater::model(), and Slic3r::Model::objects.
hide_select_machine_dlg()
void Slic3r::GUI::Plater::priv::hide_select_machine_dlg () inline
{ m_select_machine_dlg->EndModal(wxID_OK); }
References m_select_machine_dlg.
hide_send_to_printer_dlg()
void Slic3r::GUI::Plater::priv::hide_send_to_printer_dlg () inline
{ m_send_to_sdcard_dlg->EndModal(wxID_OK); }
References m_send_to_sdcard_dlg.
init_collapse_toolbar()
bool Slic3r::GUI::Plater::priv::init_collapse_toolbar ()
{
    if (wxGetApp().is_gcode_viewer())
        return true;
    if (collapse_toolbar.get_items_count() > 0)
        // already initialized
        return true;
    BackgroundTexture::Metadata background_data;
    background_data.filename = m_is_dark ? "toolbar_background_dark.png" : "toolbar_background.png";
    background_data.left = 16;
    background_data.top = 16;
    background_data.right = 16;
    background_data.bottom = 16;
    if (!collapse_toolbar.init(background_data))
        return false;
    collapse_toolbar.set_layout_type(GLToolbar::Layout::Vertical);
    collapse_toolbar.set_horizontal_orientation(GLToolbar::Layout::HO_Right);
    collapse_toolbar.set_vertical_orientation(GLToolbar::Layout::VO_Top);
    collapse_toolbar.set_border(5.0f);
    collapse_toolbar.set_separator_size(5);
    collapse_toolbar.set_gap_size(2);
    collapse_toolbar.del_all_item();
    GLToolbarItem::Data item;
    item.name = "collapse_sidebar";
    // set collapse svg name
    item.icon_filename = "*.svg";
    item.sprite_id = 0;
    item.left.action_callback = []() {
        wxGetApp().plater()->collapse_sidebar(!wxGetApp().plater()->is_sidebar_collapsed());
    };
    if (!collapse_toolbar.add_item(item))
        return false;
    // Now "collapse" sidebar to current state. This is done so the tooltip
    // is updated before the toolbar is first used.
    wxGetApp().plater()->collapse_sidebar(wxGetApp().plater()->is_sidebar_collapsed());
    return true;
}
References Slic3r::GUI::GLToolbarItem::Data::Option::action_callback, Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::GUI::BackgroundTexture::Metadata::filename, Slic3r::GUI::GLToolbar::Layout::HO_Right, Slic3r::GUI::GLToolbarItem::Data::icon_filename, Slic3r::GUI::Plater::is_sidebar_collapsed(), Slic3r::GUI::GLToolbarItem::Data::left, Slic3r::GUI::BackgroundTexture::Metadata::left, Slic3r::GUI::GLToolbarItem::Data::name, Slic3r::GUI::plater(), Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::GLToolbarItem::Data::sprite_id, Slic3r::GUI::BackgroundTexture::Metadata::top, Slic3r::GUI::GLToolbar::Layout::Vertical, and Slic3r::GUI::GLToolbar::Layout::VO_Top.
init_notification_manager()
void Slic3r::GUI::Plater::priv::init_notification_manager ()
{
    if (!notification_manager)
        return;
    notification_manager->init();
    auto cancel_callback = [this]() {
        if (this->background_process.idle())
            return false;
        this->background_process.stop();
        return true;
    };
    notification_manager->init_slicing_progress_notification(cancel_callback);
    notification_manager->set_fff(printer_technology == ptFFF);
    notification_manager->init_progress_indicator();
}
References Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptFFF.
inside_snapshot_capture()
bool Slic3r::GUI::Plater::priv::inside_snapshot_capture () inline
{ return m_prevent_snapshots != 0; }
References m_prevent_snapshots.
install_network_plugin()
void Slic3r::GUI::Plater::priv::install_network_plugin (wxCommandEvent & event)
{
    wxGetApp().ShowDownNetPluginDlg();
    return;
}
is_assemble_view_show()
bool Slic3r::GUI::Plater::priv::is_assemble_view_show () const inline
{ return current_panel == assemble_view; }
References assemble_view, and current_panel.
is_presets_dirty()
bool Slic3r::GUI::Plater::priv::is_presets_dirty () const inline
{ return dirty_state.is_presets_dirty(); }
References dirty_state, and Slic3r::GUI::ProjectDirtyStateManager::is_presets_dirty().
is_preview_loaded()
bool Slic3r::GUI::Plater::priv::is_preview_loaded () const inline
{ return preview->is_loaded(); }
References Slic3r::GUI::Preview::is_loaded(), and preview.
is_preview_shown()
bool Slic3r::GUI::Plater::priv::is_preview_shown () const inline
{ return current_panel == preview; }
References current_panel, and preview.
is_project_dirty()
bool Slic3r::GUI::Plater::priv::is_project_dirty () const inline
{ return dirty_state.is_dirty(); }
References dirty_state, and Slic3r::GUI::ProjectDirtyStateManager::is_dirty().
is_sidebar_collapsed()
bool Slic3r::GUI::Plater::priv::is_sidebar_collapsed () const inline
{ return sidebar->is_collapsed(); }
References Slic3r::GUI::Sidebar::is_collapsed(), and sidebar.
is_view3D_layers_editing_enabled()
bool Slic3r::GUI::Plater::priv::is_view3D_layers_editing_enabled () const inline
{ return (current_panel == view3D) && view3D->get_canvas3d()->is_layers_editing_enabled(); }
References current_panel, Slic3r::GUI::View3D::get_canvas3d(), Slic3r::GUI::GLCanvas3D::is_layers_editing_enabled(), and view3D.
is_view3D_overhang_shown()
bool Slic3r::GUI::Plater::priv::is_view3D_overhang_shown () const inline
{ return (current_panel == view3D) && view3D->get_canvas3d()->is_overhang_shown(); }
References current_panel, Slic3r::GUI::View3D::get_canvas3d(), Slic3r::GUI::GLCanvas3D::is_overhang_shown(), and view3D.
is_view3D_shown()
bool Slic3r::GUI::Plater::priv::is_view3D_shown () const inline
{ return current_panel == view3D; }
References current_panel, and view3D.
layers_height_allowed()
bool Slic3r::GUI::Plater::priv::layers_height_allowed () const private
{
    if (printer_technology != ptFFF)
        return false;
    int obj_idx = get_selected_object_idx();
    return 0 <= obj_idx && obj_idx < (int)model.objects.size() && model.objects[obj_idx]->bounding_box().max.z() > SINKING_Z_THRESHOLD && view3D->is_layers_editing_allowed();
}
References Slic3r::GUI::Plater::get_selected_object_idx(), int, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::Plater::printer_technology(), Slic3r::ptFFF, and Slic3r::SINKING_Z_THRESHOLD.
leave_gizmos_stack()
bool Slic3r::GUI::Plater::priv::leave_gizmos_stack ()
{
    bool changed = false;
    assert(m_undo_redo_stack_active == &m_undo_redo_stack_gizmos);
    if (m_undo_redo_stack_active == &m_undo_redo_stack_gizmos) {
        assert(! m_undo_redo_stack_active->empty());
        changed = m_undo_redo_stack_gizmos.has_undo_snapshot();
        m_undo_redo_stack_active->clear();
        m_undo_redo_stack_active = &m_undo_redo_stack_main;
    }
    return changed;
}
load_auxiliary_files()
void Slic3r::GUI::Plater::priv::load_auxiliary_files ()
{
    std::string auxiliary_path = encode_path(q->model().get_auxiliary_file_temp_path().c_str());
    //wxGetApp().mainframe->m_project->Reload(auxiliary_path);
}
References Slic3r::encode_path().
load_files()
std::vector< size_t > Slic3r::GUI::Plater::priv::load_files (const std::vector< fs::path > & input_files, LoadStrategy strategy, bool ask_multi = false)
{
    std::vector<size_t> empty_result;
    bool dlg_cont = true;
    bool is_user_cancel = false;
    bool translate_old = false;
    int current_width, current_depth, current_height;
    if (input_files.empty()) { return std::vector<size_t>(); }
    // SoftFever: ugly fix so we can exist pa calib mode
    background_process.fff_print()->calib_mode() = CalibMode::Calib_None;
    // BBS
    int filaments_cnt = config->opt<ConfigOptionStrings>("filament_colour")->values.size();
    bool one_by_one = input_files.size() == 1 || printer_technology == ptSLA/* || filaments_cnt <= 1*/;
    if (! one_by_one) {
        for (const auto &path : input_files) {
            if (std::regex_match(path.string(), pattern_bundle)) {
                one_by_one = true;
                break;
            }
        }
    }
    bool load_model = strategy & LoadStrategy::LoadModel;
    bool load_config = strategy & LoadStrategy::LoadConfig;
    bool imperial_units = strategy & LoadStrategy::ImperialUnits;
    bool silence = strategy & LoadStrategy::Silence;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": load_model %1%, load_config %2%, input_files size %3%")%load_model %load_config %input_files.size();
    const auto loading = _L("Loading") + dots;
    ProgressDialog dlg(loading, "", 100, find_toplevel_parent(q), wxPD_AUTO_HIDE | wxPD_CAN_ABORT | wxPD_APP_MODAL);
    wxBusyCursor busy;
    auto *new_model = (!load_model || one_by_one) ? nullptr : new Slic3r::Model();
    std::vector<size_t> obj_idxs;
    int answer_convert_from_meters          = wxOK_DEFAULT;
    int answer_convert_from_imperial_units  = wxOK_DEFAULT;
    int tolal_model_count                   = 0;
    int progress_percent = 0;
    int total_files = input_files.size();
    const int stage_percent[IMPORT_STAGE_MAX+1] = {
            5,      // IMPORT_STAGE_RESTORE
            10,     // IMPORT_STAGE_OPEN
            30,     // IMPORT_STAGE_READ_FILES
            50,     // IMPORT_STAGE_EXTRACT
            60,     // IMPORT_STAGE_LOADING_OBJECTS
            70,     // IMPORT_STAGE_LOADING_PLATES
            80,     // IMPORT_STAGE_FINISH
            85,     // IMPORT_STAGE_ADD_INSTANCE
            90,      // IMPORT_STAGE_UPDATE_GCODE
            92,     // IMPORT_STAGE_CHECK_MODE_GCODE
            95,     // UPDATE_GCODE_RESULT
            98,     // IMPORT_LOAD_CONFIG
            99,     // IMPORT_LOAD_MODEL_OBJECTS
            100
     };
    const int step_percent[LOAD_STEP_STAGE_NUM+1] = {
            5,     // LOAD_STEP_STAGE_READ_FILE
            30,     // LOAD_STEP_STAGE_GET_SOLID
            60,     // LOAD_STEP_STAGE_GET_MESH
            100
     };
    const float INPUT_FILES_RATIO            = 0.7;
    const float INIT_MODEL_RATIO             = 0.75;
    const float CENTER_AROUND_ORIGIN_RATIO   = 0.8;
    const float LOAD_MODEL_RATIO             = 0.9;
    for (size_t i = 0; i < input_files.size(); ++i) {
        int file_percent = 0;
#ifdef _WIN32
        auto path = input_files[i];
        // On Windows, we swap slashes to back slashes, see GH #6803 as read_from_file() does not understand slashes on Windows thus it assignes full path to names of loaded objects.
        path.make_preferred();
#else  // _WIN32
       // Don't make a copy on Posix. Slash is a path separator, back slashes are not accepted as a substitute.
        const auto &path = input_files[i];
#endif // _WIN32
        const auto filename         = path.filename();
        int  progress_percent = static_cast<int>(100.0f * static_cast<float>(i) / static_cast<float>(input_files.size()));
        const auto real_filename    = (strategy & LoadStrategy::Restore) ? input_files[++i].filename() : filename;
        const auto dlg_info         = _L("Loading file") + ": " + from_path(real_filename);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": load file %1%") % filename;
        dlg_cont = dlg.Update(progress_percent, dlg_info);
        if (!dlg_cont) return empty_result;
        const bool type_3mf = std::regex_match(path.string(), pattern_3mf);
        // const bool type_zip_amf = !type_3mf && std::regex_match(path.string(), pattern_zip_amf);
        const bool type_any_amf = !type_3mf && std::regex_match(path.string(), pattern_any_amf);
        // const bool type_prusa   = std::regex_match(path.string(), pattern_prusa);
        Slic3r::Model model;
        // BBS: add auxiliary files related logic
        bool load_aux = strategy & LoadStrategy::LoadAuxiliary, load_old_project = false;
        if (load_model && load_config && type_3mf) {
            load_aux = true;
            strategy = strategy | LoadStrategy::LoadAuxiliary;
        }
        if (load_config) strategy = strategy | LoadStrategy::CheckVersion;
        bool is_project_file = false;
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": is_project_file %1%, type_3mf %2%") % is_project_file % type_3mf;
        try {
            if (type_3mf) {
                DynamicPrintConfig config;
                Semver             file_version;
                {
                    DynamicPrintConfig config_loaded;
                    // BBS: add part plate related logic
                    PlateDataPtrs             plate_data;
                    En3mfType                 en_3mf_file_type = En3mfType::From_BBS;
                    ConfigSubstitutionContext config_substitutions{ForwardCompatibilitySubstitutionRule::Enable};
                    std::vector<Preset *>     project_presets;
                    // BBS: backup & restore
                    q->skip_thumbnail_invalid = true;
                    model = Slic3r::Model::read_from_archive(path.string(), &config_loaded, &config_substitutions, en_3mf_file_type, strategy, &plate_data, &project_presets,
                                                             &file_version,
                                                             [this, &dlg, real_filename, &progress_percent, &file_percent, stage_percent, INPUT_FILES_RATIO, total_files, i,
                                                              &is_user_cancel](int import_stage, int current, int total, bool &cancel) {
                                                                 bool     cont = true;
                                                                 float percent_float = (100.0f * (float)i / (float)total_files) + INPUT_FILES_RATIO * ((float)stage_percent[import_stage] + (float)current * (float)(stage_percent[import_stage + 1] - stage_percent[import_stage]) /(float) total) / (float)total_files;
                                                                 BOOST_LOG_TRIVIAL(trace) << "load_3mf_file: percent(float)=" << percent_float << ", stage = " << import_stage << ", curr = " << current << ", total = " << total;
                                                                 progress_percent = (int)percent_float;
                                                                 wxString msg  = wxString::Format(_L("Loading file: %s"), from_path(real_filename));
                                                                 cont          = dlg.Update(progress_percent, msg);
                                                                 cancel        = !cont;
                                                                 if (cancel)
                                                                     is_user_cancel = cancel;
                                                             });
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__
                                            << boost::format(", plate_data.size %1%, project_preset.size %2%, is_bbs_3mf %3%, file_version %4% \n") % plate_data.size() %
                                                   project_presets.size() % (en_3mf_file_type == En3mfType::From_BBS) % file_version.to_string();
                    // 1. add extruder for prusa model if the number of existing extruders is not enough
                    // 2. add extruder for BBS or Other model if only import geometry
                    if (en_3mf_file_type == En3mfType::From_Prusa || (load_model && !load_config)) {
                        std::set<int> extruderIds;
                        for (ModelObject *o : model.objects) {
                            if (o->config.option("extruder")) extruderIds.insert(o->config.extruder());
                            for (auto volume : o->volumes) {
                                if (volume->config.option("extruder")) extruderIds.insert(volume->config.extruder());
                                for (int extruder : volume->get_extruders()) { extruderIds.insert(extruder); }
                            }
                        }
                        int size = extruderIds.size() == 0 ? 0 : *(extruderIds.rbegin());
                        int filament_size = sidebar->combos_filament().size();
                        while (filament_size < 16 && filament_size < size) {
                            int         filament_count = filament_size + 1;
                            wxColour    new_col        = Plater::get_next_color_for_filament();
                            std::string new_color      = new_col.GetAsString(wxC2S_HTML_SYNTAX).ToStdString();
                            wxGetApp().preset_bundle->set_num_filaments(filament_count, new_color);
                            wxGetApp().plater()->on_filaments_change(filament_count);
                            ++filament_size;
                        }
                        wxGetApp().get_tab(Preset::TYPE_PRINT)->update();
                    }
                    std::string import_project_action = wxGetApp().app_config->get("import_project_action");
                    LoadType load_type;
                    if (import_project_action.empty())
                        load_type = LoadType::Unknown;
                    else
                        load_type  = static_cast<LoadType>(std::stoi(import_project_action));
                    // BBS: version check
                    Semver app_version = *(Semver::parse(SLIC3R_VERSION));
                    if (en_3mf_file_type == En3mfType::From_Prusa) {
                        // do not reset the model config
                        load_config = false;
                        if(load_type != LoadType::LoadGeometry)
                            show_info(q, _L("The 3mf is not from Bambu Lab, load geometry data only."), _L("Load 3mf"));
                    }
                    else if (load_config && (file_version.maj() != app_version.maj())) {
                        // version mismatch, only load geometries
                        load_config = false;
                        if (!load_model) {
                            // only load config case, return directly
                            show_info(q, _L("The Config can not be loaded."), _L("Load 3mf"));
                            q->skip_thumbnail_invalid = false;
                            return empty_result;
                        }
                        load_old_project = true;
                        // select view to 3D
                        q->select_view_3D("3D");
                        // select plate 0 as default
                        q->select_plate(0);
                        if (load_type != LoadType::LoadGeometry) {
                            if (en_3mf_file_type == En3mfType::From_BBS)
                                show_info(q, _L("The 3mf is generated by old Orca Slicer, load geometry data only."), _L("Load 3mf"));
                            else
                                show_info(q, _L("The 3mf is not from Bambu Lab, load geometry data only."), _L("Load 3mf"));
                        }
                        for (ModelObject *model_object : model.objects) {
                            model_object->config.reset();
                            // Is there any modifier or advanced config data?
                            for (ModelVolume *model_volume : model_object->volumes) model_volume->config.reset();
                        }
                    } else if (load_config && (file_version > app_version)) {
                        if (config_substitutions.unrecogized_keys.size() > 0) {
                            wxString text  = wxString::Format(_L("The 3mf's version %s is newer than %s's version %s, Found following keys unrecognized:"),
                                                             file_version.to_string(), std::string(SLIC3R_APP_FULL_NAME), app_version.to_string());
                            text += "\n";
                            bool     first = true;
                            // std::string context = into_u8(text);
                            wxString context = text;
                            for (auto &key : config_substitutions.unrecogized_keys) {
                                context += "  -";
                                context += key;
                                context += ";\n";
                                first = false;
                            }
                            wxString append = _L("You'd better upgrade your software.\n");
                            context += "\n\n";
                            // context += into_u8(append);
                            context += append;
                            show_info(q, context, _L("Newer 3mf version"));
                        }
                        else {
                            //if the minor version is not matched
                            if (file_version.min() != app_version.min()) {
                                wxString text  = wxString::Format(_L("The 3mf's version %s is newer than %s's version %s, Suggest to upgrade your software."),
                                                 file_version.to_string(), std::string(SLIC3R_APP_FULL_NAME), app_version.to_string());
                                text += "\n";
                                show_info(q, text, _L("Newer 3mf version"));
                            }
                        }
                    } else if (!load_config) {
                        // reset config except color
                        for (ModelObject *model_object : model.objects) {
                            bool has_extruder = model_object->config.has("extruder");
                            int  extruder_id  = -1;
                            // save the extruder information before reset
                            if (has_extruder) { extruder_id = model_object->config.extruder(); }
                            model_object->config.reset();
                            // restore the extruder after reset
                            if (has_extruder) { model_object->config.set("extruder", extruder_id); }
                            // Is there any modifier or advanced config data?
                            for (ModelVolume *model_volume : model_object->volumes) {
                                has_extruder = model_volume->config.has("extruder");
                                if (has_extruder) { extruder_id = model_volume->config.extruder(); }
                                model_volume->config.reset();
                                if (has_extruder) { model_volume->config.set("extruder", extruder_id); }
                            }
                        }
                    }
                    // plate data
                    if (plate_data.size() > 0) {
                        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format(", import 3mf UPDATE_GCODE_RESULT \n");
                        wxString msg = wxString::Format(_L("Loading file: %s"), from_path(real_filename));
                        dlg_cont     = dlg.Update(progress_percent, msg);
                        if (!dlg_cont) {
                            q->skip_thumbnail_invalid = false;
                            return empty_result;
                        }
                        Semver old_version(1, 5, 9);
                        if ((en_3mf_file_type == En3mfType::From_BBS) && (file_version < old_version) && load_model && load_config && !config_loaded.empty()) {
                            translate_old = true;
                            partplate_list.get_plate_size(current_width, current_depth, current_height);
                        }
                        if (load_config) {
                            if (translate_old) {
                                //set the size back
                                partplate_list.reset_size(current_width + Bed3D::Axes::DefaultTipRadius, current_depth + Bed3D::Axes::DefaultTipRadius, current_height, false);
                            }
                            partplate_list.load_from_3mf_structure(plate_data);
                            partplate_list.update_slice_context_to_current_plate(background_process);
                            this->preview->update_gcode_result(partplate_list.get_current_slice_result());
                            release_PlateData_list(plate_data);
                            sidebar->obj_list()->reload_all_plates();
                        } else {
                            partplate_list.reload_all_objects();
                        }
                    }
                    // BBS:: project embedded presets
                    if ((project_presets.size() > 0) && load_config) {
                        // load project embedded presets
                        PresetsConfigSubstitutions preset_substitutions;
                        PresetBundle &             preset_bundle = *wxGetApp().preset_bundle;
                        preset_substitutions                     = preset_bundle.load_project_embedded_presets(project_presets, ForwardCompatibilitySubstitutionRule::Enable);
                        if (!preset_substitutions.empty()) show_substitutions_info(preset_substitutions);
                    }
                    if (project_presets.size() > 0) {
                        for (unsigned int i = 0; i < project_presets.size(); i++) { delete project_presets[i]; }
                        project_presets.clear();
                    }
                    if (load_config && !config_loaded.empty()) {
                        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format(", import 3mf IMPORT_LOAD_CONFIG \n");
                        wxString msg = wxString::Format(_L("Loading file: %s"), from_path(real_filename));
                        dlg_cont     = dlg.Update(progress_percent, msg);
                        if (!dlg_cont) {
                            q->skip_thumbnail_invalid = false;
                            return empty_result;
                        }
                        // Based on the printer technology field found in the loaded config, select the base for the config,
                        PrinterTechnology printer_technology = Preset::printer_technology(config_loaded);
                        config.apply(static_cast<const ConfigBase &>(FullPrintConfig::defaults()));
                        // and place the loaded config over the base.
                        config += std::move(config_loaded);
                        std::map<std::string, std::string> validity = config.validate();
                        if (!validity.empty()) {
                            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format("Param values in 3mf error: ");
                            for (std::map<std::string, std::string>::iterator it=validity.begin(); it!=validity.end(); ++it)
                                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format("%1%: %2%")%it->first %it->second;
                            //
                            NotificationManager *notify_manager = q->get_notification_manager();
                            std::string error_message = L("Invalid values found in the 3mf:");
                            error_message += "\n";
                            for (std::map<std::string, std::string>::iterator it=validity.begin(); it!=validity.end(); ++it)
                                error_message += "-" + it->first + ": " + it->second + "\n";
                            error_message += "\n";
                            error_message += L("Please correct them in the param tabs");
                            notify_manager->bbl_show_3mf_warn_notification(error_message);
                        }
                    }
                    if (!config_substitutions.empty()) show_substitutions_info(config_substitutions.substitutions, filename.string());
                    // BBS
                    if (load_model && !load_config) {
                        ;
                    }
                    else {
                        this->model.plates_custom_gcodes = model.plates_custom_gcodes;
                        this->model.design_info = model.design_info;
                        this->model.model_info = model.model_info;
                    }
                }
                if (load_config) {
                    if (!config.empty()) {
                        Preset::normalize(config);
                        PresetBundle *preset_bundle = wxGetApp().preset_bundle;
                        // BBS: first validate the printer
                        // TODO: remove it after released""
                        bool validated = preset_bundle->validate_printers(filename.string(), config);
                        if (!validated) {
                            load_config      = false;
                            load_old_project = true;
                            // select view to 3D
                            q->select_view_3D("3D");
                            // select plate 0 as default
                            q->select_plate(0);
                            show_info(q, _L("The 3mf is not compatible, load geometry data only!"), _L("Incompatible 3mf"));
                            for (ModelObject *model_object : model.objects) {
                                model_object->config.reset();
                                // Is there any modifier or advanced config data?
                                for (ModelVolume *model_volume : model_object->volumes) model_volume->config.reset();
                            }
                        } else {
                            preset_bundle->load_config_model(filename.string(), std::move(config), file_version);
                            // BBS: moved this logic to presetcollection
                            //{
                            //    // After loading of the presets from project, check if they are visible.
                            //    // Set them to visible if they are not.
                            //    auto update_selected_preset_visibility = [](PresetCollection& presets, std::vector<std::string>& names) {
                            //        if (!presets.get_selected_preset().is_visible) {
                            //            assert(presets.get_selected_preset().name == presets.get_edited_preset().name);
                            //            presets.get_selected_preset().is_visible = true;
                            //            presets.get_edited_preset().is_visible = true;
                            //            names.emplace_back(presets.get_selected_preset().name);
                            //        }
                            //    };
                            //    std::vector<std::string> names;
                            //    if (printer_technology == ptFFF) {
                            //        update_selected_preset_visibility(preset_bundle->prints, names);
                            //        for (const std::string& filament : preset_bundle->filament_presets) {
                            //            Preset* preset = preset_bundle->filaments.find_preset(filament);
                            //            if (preset && !preset->is_visible) {
                            //                preset->is_visible = true;
                            //                names.emplace_back(preset->name);
                            //                if (preset->name == preset_bundle->filaments.get_edited_preset().name)
                            //                    preset_bundle->filaments.get_selected_preset().is_visible = true;
                            //            }
                            //        }
                            //    }
                            //    else {
                            //        update_selected_preset_visibility(preset_bundle->sla_prints, names);
                            //        update_selected_preset_visibility(preset_bundle->sla_materials, names);
                            //    }
                            //    update_selected_preset_visibility(preset_bundle->printers, names);
                            //    preset_bundle->update_compatible(PresetSelectCompatibleType::Never);
                            //    // show notification about temporarily installed presets
                            //    if (!names.empty()) {
                            //        std::string notif_text = into_u8(_L_PLURAL("The preset below was temporarily installed on the active instance of PrusaSlicer",
                            //                                                   "The presets below were temporarily installed on the active instance of PrusaSlicer",
                            //                                                   names.size())) + ":";
                            //        for (std::string& name : names)
                            //            notif_text += "\n - " + name;
                            //        notification_manager->push_notification(NotificationType::CustomNotification,
                            //            NotificationManager::NotificationLevel::PrintInfoNotificationLevel, notif_text);
                            //    }
                            //}
                            // BBS
                            // if (printer_technology == ptFFF)
                            //    CustomGCode::update_custom_gcode_per_print_z_from_config(model.custom_gcode_per_print_z, &preset_bundle->project_config);
                            // For exporting from the amf/3mf we shouldn't check printer_presets for the containing information about "Print Host upload"
                            // BBS: add preset combo box re-active logic
                            // currently found only needs re-active here
                            wxGetApp().load_current_presets(false, false);
                            // Update filament colors for the MM-printer profile in the full config
                            // to avoid black (default) colors for Extruders in the ObjectList,
                            // when for extruder colors are used filament colors
                            q->on_filaments_change(preset_bundle->filament_presets.size());
                            ConfigOption *bed_type_opt = preset_bundle->project_config.option("curr_bed_type");
                            if (bed_type_opt != nullptr) q->on_bed_type_change((BedType) bed_type_opt->getInt());
                            is_project_file = true;
                        }
                    }
                    if (!silence) wxGetApp().app_config->update_config_dir(path.parent_path().string());
                }
            } else {
                // BBS: add plate data related logic
                PlateDataPtrs plate_data;
                // BBS: project embedded settings
                std::vector<Preset *> project_presets;
                bool                  is_xxx;
                Semver                file_version;
                model = Slic3r::Model::read_from_file(
                    path.string(), nullptr, nullptr, strategy, &plate_data, &project_presets, &is_xxx, &file_version, nullptr,
                    [this, &dlg, real_filename, &progress_percent, &file_percent, INPUT_FILES_RATIO, total_files, i](int current, int total, bool &cancel)
                    {
                            bool     cont = true;
                            float percent_float = (100.0f * (float)i / (float)total_files) + INPUT_FILES_RATIO * 100.0f * ((float)current / (float)total) / (float)total_files;
                            BOOST_LOG_TRIVIAL(trace) << "load_stl_file: percent(float)=" << percent_float << ", curr = " << current << ", total = " << total;
                            progress_percent = (int)percent_float;
                            wxString msg  = wxString::Format(_L("Loading file: %s"), from_path(real_filename));
                            cont          = dlg.Update(progress_percent, msg);
                            cancel        = !cont;
                     },
                    [this, &dlg, real_filename, &progress_percent, &file_percent, step_percent, INPUT_FILES_RATIO, total_files, i](int load_stage, int current, int total, bool &cancel)
                    {
                            bool     cont = true;
                            float percent_float = (100.0f * (float)i / (float)total_files) + INPUT_FILES_RATIO * ((float)step_percent[load_stage] + (float)current * (float)(step_percent[load_stage + 1] - step_percent[load_stage]) / (float)total) / (float)total_files;
                            BOOST_LOG_TRIVIAL(trace) << "load_step_file: percent(float)=" << percent_float << ", stage = " << load_stage << ", curr = " << current << ", total = " << total;
                            progress_percent = (int)percent_float;
                            wxString msg  = wxString::Format(_L("Loading file: %s"), from_path(real_filename));
                            cont          = dlg.Update(progress_percent, msg);
                            cancel        = !cont;
                    },
                    [](int isUtf8StepFile) {
                        if (!isUtf8StepFile)
                            Slic3r::GUI::show_info(nullptr, _L("Name of components inside step file is not UTF8 format!") + "\n\n" + _L("The name may show garbage characters!"),
                                                   _L("Attention!"));
                    });
                if (type_any_amf && is_xxx) imperial_units = true;
                for (auto obj : model.objects)
                    if (obj->name.empty()) obj->name = fs::path(obj->input_file).filename().string();
                if (plate_data.size() > 0) {
                    partplate_list.load_from_3mf_structure(plate_data);
                    partplate_list.update_slice_context_to_current_plate(background_process);
                    this->preview->update_gcode_result(partplate_list.get_current_slice_result());
                    release_PlateData_list(plate_data);
                    sidebar->obj_list()->reload_all_plates();
                }
                // BBS:: project embedded presets
                if (project_presets.size() > 0) {
                    // load project embedded presets
                    PresetsConfigSubstitutions preset_substitutions;
                    PresetBundle &             preset_bundle = *wxGetApp().preset_bundle;
                    preset_substitutions                     = preset_bundle.load_project_embedded_presets(project_presets, ForwardCompatibilitySubstitutionRule::Enable);
                    if (!preset_substitutions.empty()) show_substitutions_info(preset_substitutions);
                    for (unsigned int i = 0; i < project_presets.size(); i++) { delete project_presets[i]; }
                    project_presets.clear();
                }
            }
        } catch (const ConfigurationError &e) {
            std::string message = GUI::format(_L("Failed loading file \"%1%\". An invalid configuration was found."), filename.string()) + "\n\n" + e.what();
            GUI::show_error(q, message);
            continue;
        } catch (const std::exception &e) {
            if (!is_user_cancel)
                GUI::show_error(q, e.what());
            continue;
        }
        progress_percent = 100.0f * (float)i / (float)total_files + INIT_MODEL_RATIO * 100.0f / (float)total_files;
        dlg_cont = dlg.Update(progress_percent);
        if (!dlg_cont) {
            q->skip_thumbnail_invalid = false;
            return empty_result;
        }
        if (load_model) {
            // The model should now be initialized
            auto convert_from_imperial_units = [](Model &model, bool only_small_volumes) { model.convert_from_imperial_units(only_small_volumes); };
            // BBS: add load_old_project logic
            if ((!is_project_file) && (!load_old_project)) {
                // if (!is_project_file) {
                if (int deleted_objects = model.removed_objects_with_zero_volume(); deleted_objects > 0) {
                    MessageDialog(q, _L("Objects with zero volume removed"), _L("The volume of the object is zero"), wxICON_INFORMATION | wxOK).ShowModal();
                }
                if (imperial_units)
                    // Convert even if the object is big.
                    convert_from_imperial_units(model, false);
                else if (model.looks_like_saved_in_meters()) {
                    // BBS do not handle look like in meters
                    MessageDialog dlg(q,
                                      format_wxstr(_L("The object from file %s is too small, and maybe in meters or inches.\n Do you want to scale to millimeters?"),
                                                   from_path(filename)),
                                      _L("Object too small"), wxICON_QUESTION | wxYES_NO);
                    int           answer = dlg.ShowModal();
                    if (answer == wxID_YES) model.convert_from_meters(true);
                } else if (model.looks_like_imperial_units()) {
                    // BBS do not handle look like in meters
                    MessageDialog dlg(q,
                                      format_wxstr(_L("The object from file %s is too small, and maybe in meters or inches.\n Do you want to scale to millimeters?"),
                                                   from_path(filename)),
                                      _L("Object too small"), wxICON_QUESTION | wxYES_NO);
                    int           answer = dlg.ShowModal();
                    if (answer == wxID_YES) convert_from_imperial_units(model, true);
                }
                // else if (model.looks_like_imperial_units()) {
                // BBS do not handle look like in imperial
                // auto convert_model_if = [convert_from_imperial_units](Model& model, bool condition) {
                //    if (condition)
                //        //FIXME up-scale only the small parts?
                //        convert_from_imperial_units(model, true);
                //};
                // if (answer_convert_from_imperial_units == wxOK_DEFAULT) {
                //    RichMessageDialog dlg(q, format_wxstr(_L_PLURAL(
                //        "The dimensions of the object from file %s seem to be defined in inches.\n"
                //        "The internal unit of PrusaSlicer is a millimeter. Do you want to recalculate the dimensions of the object?",
                //        "The dimensions of some objects from file %s seem to be defined in inches.\n"
                //        "The internal unit of PrusaSlicer is a millimeter. Do you want to recalculate the dimensions of these objects?", model.objects.size()), from_path(filename))
                //        + "\n", _L("The object is too small"), wxICON_QUESTION | wxYES_NO);
                //    dlg.ShowCheckBox(_L("Apply to all the remaining small objects being loaded."));
                //    int answer = dlg.ShowModal();
                //    if (dlg.IsCheckBoxChecked())
                //        answer_convert_from_imperial_units = answer;
                //    else
                //        convert_model_if(model, answer == wxID_YES);
                //}
                // convert_model_if(model, answer_convert_from_imperial_units == wxID_YES);
            }
             if (!is_project_file && model.looks_like_multipart_object()) {
               MessageDialog msg_dlg(q, _L(
                    "This file contains several objects positioned at multiple heights.\n"
                    "Instead of considering them as multiple objects, should \n"
                    "the file be loaded as a single object having multiple parts?") + "\n",
                    _L("Multi-part object detected"), wxICON_WARNING | wxYES | wxNO);
                if (msg_dlg.ShowModal() == wxID_YES) {
                    model.convert_multipart_object(filaments_cnt);
                }
            }
        }
        // else if ((wxGetApp().get_mode() == comSimple) && (type_3mf || type_any_amf) && model_has_advanced_features(model)) {
        //    MessageDialog msg_dlg(q, _L("This file cannot be loaded in a simple mode. Do you want to switch to an advanced mode?")+"\n",
        //        _L("Detected advanced data"), wxICON_WARNING | wxYES | wxNO);
        //    if (msg_dlg.ShowModal() == wxID_YES) {
        //        Slic3r::GUI::wxGetApp().save_mode(comAdvanced);
        //        view3D->set_as_dirty();
        //    }
        //    else
        //        return obj_idxs;
        //}
        progress_percent = 100.0f * (float)i / (float)total_files + CENTER_AROUND_ORIGIN_RATIO * 100.0f / (float)total_files;
        dlg_cont = dlg.Update(progress_percent);
        if (!dlg_cont) {
            q->skip_thumbnail_invalid = false;
            return empty_result;
        }
        int model_idx = 0;
        for (ModelObject *model_object : model.objects) {
            if (!type_3mf && !type_any_amf) model_object->center_around_origin(false);
            // BBS
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format("import 3mf IMPORT_LOAD_MODEL_OBJECTS \n");
            wxString msg = wxString::Format("Loading file: %s", from_path(real_filename));
            model_idx++;
            dlg_cont = dlg.Update(progress_percent, msg);
            if (!dlg_cont) {
                q->skip_thumbnail_invalid = false;
                return empty_result;
            }
            model_object->ensure_on_bed(is_project_file);
        }
        tolal_model_count += model_idx;
        progress_percent = 100.0f * (float)i / (float)total_files + LOAD_MODEL_RATIO * 100.0f / (float)total_files;
        dlg_cont = dlg.Update(progress_percent);
        if (!dlg_cont) {
            q->skip_thumbnail_invalid = false;
            return empty_result;
        }
        if (one_by_one) {
            // BBS: add load_old_project logic
            if (type_3mf && !is_project_file && !load_old_project)
                // if (type_3mf && !is_project_file)
                model.center_instances_around_point(this->bed.build_volume().bed_center());
            // BBS: add auxiliary files logic
            // BBS: backup & restore
            if (load_aux) {
                q->model().load_from(model);
                load_auxiliary_files();
            }
            auto loaded_idxs = load_model_objects(model.objects, is_project_file);
            obj_idxs.insert(obj_idxs.end(), loaded_idxs.begin(), loaded_idxs.end());
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format("import 3mf IMPORT_LOAD_MODEL_OBJECTS \n");
            wxString msg = wxString::Format(_L("Loading file: %s"), from_path(real_filename));
            dlg_cont     = dlg.Update(progress_percent, msg);
            if (!dlg_cont) {
                q->skip_thumbnail_invalid = false;
                return empty_result;
            }
        } else {
            // This must be an .stl or .obj file, which may contain a maximum of one volume.
            for (const ModelObject *model_object : model.objects) {
                new_model->add_object(*model_object);
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format("import 3mf IMPORT_ADD_MODEL_OBJECTS \n");
                wxString msg = wxString::Format(_L("Loading file: %s"), from_path(real_filename));
                dlg_cont     = dlg.Update(progress_percent, msg);
                if (!dlg_cont) {
                    q->skip_thumbnail_invalid = false;
                    return empty_result;
                }
            }
        }
    }
    if (new_model != nullptr && new_model->objects.size() > 1) {
        //BBS do not popup this dialog
        if (ask_multi) {
            MessageDialog msg_dlg(q, _L("Load these files as a single object with multiple parts?\n"), _L("Object with multiple parts was detected"),
                                  wxICON_WARNING | wxYES | wxNO);
            if (msg_dlg.ShowModal() == wxID_YES) { new_model->convert_multipart_object(filaments_cnt); }
        }
        auto loaded_idxs = load_model_objects(new_model->objects);
        obj_idxs.insert(obj_idxs.end(), loaded_idxs.begin(), loaded_idxs.end());
    }
    if (new_model) delete new_model;
    //BBS: translate old 3mf to correct positions
    if (translate_old) {
        //translate the objects
        int plate_count = partplate_list.get_plate_count();
        for (int index = 1; index < plate_count; index ++) {
            PartPlate* cur_plate = (PartPlate *)partplate_list.get_plate(index);
            Vec3d cur_origin = cur_plate->get_origin();
            Vec3d new_origin = partplate_list.compute_origin_using_new_size(index, current_width, current_depth);
            cur_plate->translate_all_instance(new_origin - cur_origin);
        }
        partplate_list.reset_size(current_width, current_depth, current_height, true, true);
    }
    //BBS: add gcode loading logic in the end
    q->m_exported_file = false;
    q->skip_thumbnail_invalid = false;
    if (load_model && load_config) {
        if (model.objects.empty()) {
            partplate_list.load_gcode_files();
            PartPlate * first_plate = nullptr, *cur_plate = nullptr;
            int plate_cnt = partplate_list.get_plate_count();
            int index = 0, first_plate_index = 0;
            q->m_valid_plates_count = 0;
            for (index = 0; index < plate_cnt; index ++)
            {
                cur_plate = partplate_list.get_plate(index);
                if (!first_plate && cur_plate->is_slice_result_valid()) {
                    first_plate = cur_plate;
                    first_plate_index = index;
                }
                if (cur_plate->is_slice_result_valid())
                    q->m_valid_plates_count ++;
            }
            if (first_plate&&first_plate->is_slice_result_valid()) {
                q->m_exported_file = true;
                //select plate 0 as default
                q->select_plate(first_plate_index);
                //set to 3d tab
                q->select_view_3D("Preview");
                wxGetApp().mainframe->select_tab(MainFrame::tpPreview);
            }
            else {
                //set to 3d tab
                q->select_view_3D("3D");
                //select plate 0 as default
                q->select_plate(0);
            }
        }
        else {
            //set to 3d tab
            q->select_view_3D("3D");
            //select plate 0 as default
            q->select_plate(0);
        }
    }
    else {
        //always set to 3D after loading files
        q->select_view_3D("3D");
        wxGetApp().mainframe->select_tab(MainFrame::tp3DEditor);
    }
    if (load_model) {
        if (!silence) wxGetApp().app_config->update_skein_dir(input_files[input_files.size() - 1].parent_path().make_preferred().string());
        // XXX: Plater.pm had @loaded_files, but didn't seem to fill them with the filenames...
    }
    // automatic selection of added objects
    if (!obj_idxs.empty() && view3D != nullptr) {
        // update printable state for new volumes on canvas3D
        wxGetApp().plater()->canvas3D()->update_instance_printable_state_for_objects(obj_idxs);
        if (!load_config) {
            Selection& selection = view3D->get_canvas3d()->get_selection();
            selection.clear();
            for (size_t idx : obj_idxs) {
                selection.add_object((unsigned int)idx, false);
            }
        }
        // BBS: update object list selection
        this->sidebar->obj_list()->update_selections();
        if (view3D->get_canvas3d()->get_gizmos_manager().is_enabled())
            // this is required because the selected object changed and the flatten on face an sla support gizmos need to be updated accordingly
            view3D->get_canvas3d()->update_gizmos_on_off_state();
    }
    GLGizmoSimplify::add_simplify_suggestion_notification(
        obj_idxs, model.objects, *notification_manager);
    if (tolal_model_count <= 0 && !q->m_exported_file) {
        dlg.Hide();
        if (!is_user_cancel) {
            MessageDialog msg(wxGetApp().mainframe, _L("The file does not contain any geometry data."), _L("Warning"), wxYES | wxICON_WARNING);
            if (msg.ShowModal() == wxID_YES) {}
        }
    }
    return obj_idxs;
}
References _L, Slic3r::GUI::Selection::add_object(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), Slic3r::append(), Slic3r::ConfigBase::apply(), Slic3r::GUI::NotificationManager::bbl_show_3mf_warn_notification(), Slic3r::Calib_None, Slic3r::Model::center_instances_around_point(), Slic3r::CheckVersion, Slic3r::GUI::Selection::clear(), Slic3r::GUI::Sidebar::combos_filament(), Slic3r::GUI::Plater::config(), Slic3r::Model::convert_from_imperial_units(), Slic3r::Model::convert_from_meters(), Slic3r::Model::convert_multipart_object(), Slic3r::GUI::Bed3D::Axes::DefaultTipRadius, Slic3r::Model::design_info, Slic3r::GUI::dots(), Slic3r::DynamicConfig::empty(), Slic3r::Enable, Slic3r::PresetBundle::filament_presets, Slic3r::GUI::find_toplevel_parent(), Slic3r::GUI::format(), Slic3r::GUI::format_wxstr(), Slic3r::From_BBS, Slic3r::GUI::from_path(), Slic3r::From_Prusa, Slic3r::GUI::Plater::get_next_color_for_filament(), Slic3r::GUI::PartPlate::get_origin(), Slic3r::ConfigOption::getInt(), Slic3r::ImperialUnits, Slic3r::IMPORT_STAGE_MAX, Slic3r::GUI::PartPlate::is_slice_result_valid(), L, Slic3r::PresetBundle::load_config_model(), Slic3r::PresetBundle::load_project_embedded_presets(), Slic3r::LOAD_STEP_STAGE_NUM, Slic3r::LoadAuxiliary, Slic3r::LoadConfig, Slic3r::GUI::LoadGeometry, Slic3r::LoadModel, Slic3r::Model::looks_like_imperial_units(), Slic3r::Model::looks_like_multipart_object(), Slic3r::Model::looks_like_saved_in_meters(), Slic3r::GUI::Plater::m_exported_file, Slic3r::Semver::maj(), Slic3r::Semver::min(), Slic3r::GUI::Plater::model(), Slic3r::Model::model_info, Slic3r::Preset::normalize(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, Slic3r::DynamicConfig::opt(), Slic3r::ConfigBase::option(), Slic3r::Semver::parse(), Slic3r::Model::plates_custom_gcodes, Slic3r::Preset::printer_technology(), Slic3r::GUI::Plater::printer_technology(), Slic3r::PresetBundle::project_config, Slic3r::ptSLA, Slic3r::Model::read_from_archive(), Slic3r::Model::read_from_file(), Slic3r::release_PlateData_list(), Slic3r::GUI::ObjectList::reload_all_plates(), Slic3r::Model::removed_objects_with_zero_volume(), Slic3r::Restore, Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::GUI::Plater::sidebar(), Slic3r::Silence, Slic3r::ConfigOptionVector< T >::size(), size, SLIC3R_APP_FULL_NAME, Slic3r::Semver::to_string(), Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::GUI::MainFrame::tpPreview, Slic3r::GUI::PartPlate::translate_all_instance(), Slic3r::Preset::TYPE_PRINT, Slic3r::GUI::Unknown, Slic3r::GUI::ProgressDialog::Update(), Slic3r::GUI::ObjectList::update_selections(), Slic3r::DynamicPrintConfig::validate(), and Slic3r::PresetBundle::validate_printers().
load_model_objects()
std::vector< size_t > Slic3r::GUI::Plater::priv::load_model_objects (const ModelObjectPtrs & model_objects, bool allow_negative_z = false, bool split_object = false)
{
    const Vec3d bed_size = Slic3r::to_3d(this->bed.build_volume().bounding_volume2d().size(), 1.0) - 2.0 * Vec3d::Ones();
#ifndef AUTOPLACEMENT_ON_LOAD
    // bool need_arrange = false;
#endif /* AUTOPLACEMENT_ON_LOAD */
    bool scaled_down = false;
    std::vector<size_t> obj_idxs;
    unsigned int obj_count = model.objects.size();
#ifdef AUTOPLACEMENT_ON_LOAD
    ModelInstancePtrs new_instances;
#endif /* AUTOPLACEMENT_ON_LOAD */
    for (ModelObject *model_object : model_objects) {
        auto *object = model.add_object(*model_object);
        object->sort_volumes(true);
        std::string object_name = object->name.empty() ? fs::path(object->input_file).filename().string() : object->name;
        obj_idxs.push_back(obj_count++);
        if (model_object->instances.empty()) {
#ifdef AUTOPLACEMENT_ON_LOAD
            object->center_around_origin();
            new_instances.emplace_back(object->add_instance());
#else /* AUTOPLACEMENT_ON_LOAD */
            // if object has no defined position(s) we need to rearrange everything after loading
            // need_arrange = true;
             // add a default instance and center object around origin
            object->center_around_origin();  // also aligns object to Z = 0
            ModelInstance* instance = object->add_instance();
            //BBS calc transformation
            Geometry::Transformation t = instance->get_transformation();
            instance->set_offset(Slic3r::to_3d(this->bed.build_volume().bed_center(), -object->origin_translation(2)));
#endif /* AUTOPLACEMENT_ON_LOAD */
        }
        //BBS: when the object is too large, let the user choose whether to scale it down
        for (size_t i = 0; i < object->instances.size(); ++i) {
            ModelInstance* instance = object->instances[i];
            const Vec3d size = object->instance_bounding_box(i).size();
            const Vec3d ratio = size.cwiseQuotient(bed_size);
            const double max_ratio = std::max(ratio(0), ratio(1));
            if (max_ratio > 10000) {
                MessageDialog dlg(q, _L("Your object appears to be too large, Do you want to scale it down to fit the heat bed automatically?"), _L("Object too large"),
                                  wxICON_QUESTION | wxYES);
                int           answer = dlg.ShowModal();
                // the size of the object is too big -> this could lead to overflow when moving to clipper coordinates,
                // so scale down the mesh
                object->scale_mesh_after_creation(1. / max_ratio);
                object->origin_translation = Vec3d::Zero();
                object->center_around_origin();
                scaled_down = true;
                break;
            }
            else if (max_ratio > 10) {
                MessageDialog dlg(q, _L("Your object appears to be too large, Do you want to scale it down to fit the heat bed automatically?"), _L("Object too large"),
                                  wxICON_QUESTION | wxYES_NO);
                int           answer = dlg.ShowModal();
                if (answer == wxID_YES) {
                    instance->set_scaling_factor(instance->get_scaling_factor() / max_ratio);
                    scaled_down = true;
                }
            }
        }
        object->ensure_on_bed(allow_negative_z);
        if (!split_object) {
            //BBS initial assemble transformation
            for (ModelObject* model_object : model.objects) {
                //BBS initialize assemble transformation
                for (int i = 0; i < model_object->instances.size(); i++) {
                    if (!model_object->instances[i]->is_assemble_initialized()) {
                        model_object->instances[i]->set_assemble_transformation(model_object->instances[i]->get_transformation());
                    }
                }
            }
        }
    }
#ifdef AUTOPLACEMENT_ON_LOAD
#if 0
    // FIXME distance should be a config value /////////////////////////////////
    auto min_obj_distance = static_cast<coord_t>(6/SCALING_FACTOR);
    const auto *bed_shape_opt = config->opt<ConfigOptionPoints>("printable_area");
    assert(bed_shape_opt);
    auto& bedpoints = bed_shape_opt->values;
    Polyline bed; bed.points.reserve(bedpoints.size());
    for(auto& v : bedpoints) bed.append(Point::new_scale(v(0), v(1)));
    // BBS: get wipe tower of current plate
    int cur_plate_idx = partplate_list.get_curr_plate_index();
    std::pair<bool, GLCanvas3D::WipeTowerInfo> wti = view3D->get_canvas3d()->get_wipe_tower_info(cur_plate_idx);
    arr::find_new_position(model, new_instances, min_obj_distance, bed, wti);
    // it remains to move the wipe tower:
    view3D->get_canvas3d()->arrange_wipe_tower(wti);
#else
    // BBS: find an empty cell to put the copied object
    for (auto& instance : new_instances) {
        auto offset = instance->get_offset();
        auto start_point = this->bed.build_volume().bounding_volume2d().center();
        bool plate_empty = partplate_list.get_curr_plate()->empty();
        Vec3d displacement;
        if (plate_empty)
            displacement = {start_point(0), start_point(1), offset(2)};
        else {
            auto empty_cell = wxGetApp().plater()->canvas3D()->get_nearest_empty_cell({start_point(0), start_point(1)});
            displacement    = {empty_cell.x(), empty_cell.y(), offset(2)};
        }
        instance->set_offset(displacement);
    }
#endif
#endif /* AUTOPLACEMENT_ON_LOAD */
    //BBS: remove the auto scaled_down logic when load models
    //if (scaled_down) {
    //    GUI::show_info(q,
    //        _L("Your object appears to be too large, so it was automatically scaled down to fit your print bed."),
    //        _L("Object too large?"));
    //}
    notification_manager->close_notification_of_type(NotificationType::UpdatedItemsInfo);
    wxGetApp().obj_list()->add_objects_to_list(obj_idxs);
    update();
    // Update InfoItems in ObjectList after update() to use of a correct value of the GLCanvas3D::is_sinking(),
    // which is updated after a view3D->reload_scene(false, flags & (unsigned int)UpdateParams::FORCE_FULL_SCREEN_REFRESH) call
    for (const size_t idx : obj_idxs)
        wxGetApp().obj_list()->update_info_items(idx);
    object_list_changed();
    this->schedule_background_process();
    return obj_idxs;
}
References _L, Slic3r::Model::add_object(), Slic3r::Polyline::append(), Slic3r::GUI::Plater::config(), Slic3r::MultiPoint::empty(), Slic3r::ModelInstance::get_scaling_factor(), Slic3r::ModelInstance::get_transformation(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Plater::object_list_changed(), Slic3r::Model::objects, Slic3r::offset(), Slic3r::DynamicConfig::opt(), Slic3r::MultiPoint::points, SCALING_FACTOR, Slic3r::GUI::Plater::schedule_background_process(), Slic3r::ModelInstance::set_offset(), Slic3r::ModelInstance::set_scaling_factor(), Slic3r::GUI::DPIAware< P >::ShowModal(), size, Slic3r::ModelObject::sort_volumes(), Slic3r::GUI::Plater::split_object(), Slic3r::to_3d(), Slic3r::GUI::Plater::update(), and Slic3r::GUI::UpdatedItemsInfo.
mirror()
void Slic3r::GUI::Plater::priv::mirror (Axis axis)
{
    view3D->mirror_selection(axis);
}
need_update()
bool Slic3r::GUI::Plater::priv::need_update () const inline
{ return m_need_update; }
References m_need_update.
Referenced by set_need_update().
object_list_changed()
void Slic3r::GUI::Plater::priv::object_list_changed ()
{
    const bool export_in_progress = this->background_process.is_export_scheduled(); // || ! send_gcode_file.empty());
    // XXX: is this right?
    //const bool model_fits = view3D->get_canvas3d()->check_volumes_outside_state() == ModelInstancePVS_Inside;
    const bool model_fits = view3D->get_canvas3d()->check_volumes_outside_state() != ModelInstancePVS_Partly_Outside;
    PartPlate* part_plate = partplate_list.get_curr_plate();
    // BBS
    //sidebar->enable_buttons(!model.objects.empty() && !export_in_progress && model_fits && part_plate->has_printable_instances());
    bool can_slice = !model.objects.empty() && !export_in_progress && model_fits && part_plate->has_printable_instances();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": can_slice %1%, model_fits= %2%, export_in_progress %3%, has_printable_instances %4% ")%can_slice %model_fits %export_in_progress %part_plate->has_printable_instances();
    main_frame->update_slice_print_status(MainFrame::eEventObjectUpdate, can_slice);
    wxGetApp().params_panel()->notify_object_config_changed();
}
References Slic3r::GUI::MainFrame::eEventObjectUpdate, Slic3r::GUI::PartPlate::has_printable_instances(), Slic3r::GUI::Plater::model(), Slic3r::ModelInstancePVS_Partly_Outside, and Slic3r::Model::objects.
on_3dcanvas_mouse_dragging_finished()
void Slic3r::GUI::Plater::priv::on_3dcanvas_mouse_dragging_finished (SimpleEvent &)
{
    if (delayed_scene_refresh) {
        delayed_scene_refresh = false;
        update_sla_scene();
    }
    //partplate_list.reload_all_objects();
}
on_3dcanvas_mouse_dragging_started()
void Slic3r::GUI::Plater::priv::on_3dcanvas_mouse_dragging_started (SimpleEvent &)
{
    view3D->get_canvas3d()->reset_sequential_print_clearance();
}
on_action_add()
void Slic3r::GUI::Plater::priv::on_action_add (SimpleEvent &)
{
    if (q != nullptr) {
        //q->add_model();
        //BBS open file in toolbar add
        q->add_file();
    }
}
on_action_add_plate()
void Slic3r::GUI::Plater::priv::on_action_add_plate (SimpleEvent &)
{
    if (q != nullptr) {
        take_snapshot("add partplate");
        this->partplate_list.create_plate();
        int new_plate = this->partplate_list.get_plate_count() - 1;
        this->partplate_list.select_plate(new_plate);
        update();
        // BBS set default view
        //q->get_camera().select_view("topfront");
        q->get_camera().requires_zoom_to_plate = REQUIRES_ZOOM_TO_ALL_PLATE;
    }
}
References REQUIRES_ZOOM_TO_ALL_PLATE, Slic3r::GUI::Plater::take_snapshot(), and Slic3r::GUI::Plater::update().
on_action_del_plate()
void Slic3r::GUI::Plater::priv::on_action_del_plate (SimpleEvent &)
{
    if (q != nullptr) {
        q->delete_plate();
        //q->get_camera().select_view("topfront");
        //q->get_camera().requires_zoom_to_plate = REQUIRES_ZOOM_TO_ALL_PLATE;
    }
}
on_action_download_project()
void Slic3r::GUI::Plater::priv::on_action_download_project (wxCommandEvent & evt)
{
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received download project event\n" ;
    if (q != nullptr) {
        q->download_project(evt.GetString());
    }
}
on_action_export_all_sliced_file()
void Slic3r::GUI::Plater::priv::on_action_export_all_sliced_file (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received export all sliced file event\n";
        q->export_gcode_3mf(true);
    }
}
on_action_export_gcode()
void Slic3r::GUI::Plater::priv::on_action_export_gcode (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received export gcode event\n" ;
        q->export_gcode(false);
    }
}
on_action_export_sliced_file()
void Slic3r::GUI::Plater::priv::on_action_export_sliced_file (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received export sliced file event\n" ;
        q->export_gcode_3mf();
    }
}
on_action_export_to_sdcard()
void Slic3r::GUI::Plater::priv::on_action_export_to_sdcard (SimpleEvent &) private
{
  if (q != nullptr) {
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received export sliced file event\n";
    q->send_to_printer();
  }
}
on_action_export_to_sdcard_all()
void Slic3r::GUI::Plater::priv::on_action_export_to_sdcard_all (SimpleEvent &) private
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received export sliced file event\n";
        q->send_to_printer(true);
    }
}
on_action_layersediting()
void Slic3r::GUI::Plater::priv::on_action_layersediting (SimpleEvent &)
{
    view3D->enable_layers_editing(!view3D->is_layers_editing_enabled());
    notification_manager->set_move_from_overlay(view3D->is_layers_editing_enabled());
}
on_action_open_project()
void Slic3r::GUI::Plater::priv::on_action_open_project (SimpleEvent &)
{
    if (q != nullptr) {
        q->load_project();
    }
}
on_action_print_all()
void Slic3r::GUI::Plater::priv::on_action_print_all (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received print all event\n" ;
    }
    //BBS
    if (!m_select_machine_dlg) m_select_machine_dlg = new SelectMachineDialog(q);
    m_select_machine_dlg->prepare(PLATE_ALL_IDX);
    m_select_machine_dlg->ShowModal();
}
References PLATE_ALL_IDX.
on_action_print_plate()
void Slic3r::GUI::Plater::priv::on_action_print_plate (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received print plate event\n" ;
    }
    //do not check login for lan printing
    //if (!wxGetApp().check_login()) return;
    //BBS
    if (!m_select_machine_dlg) m_select_machine_dlg = new SelectMachineDialog(q);
    m_select_machine_dlg->prepare(partplate_list.get_curr_plate_index());
    m_select_machine_dlg->ShowModal();
}
on_action_print_plate_from_sdcard()
void Slic3r::GUI::Plater::priv::on_action_print_plate_from_sdcard (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received print plate event\n";
    }
    //BBS
    if (!m_select_machine_dlg) m_select_machine_dlg = new SelectMachineDialog(q);
    m_select_machine_dlg->prepare(0);
    m_select_machine_dlg->ShowModal();
}
on_action_publish()
void Slic3r::GUI::Plater::priv::on_action_publish (wxCommandEvent & evt)
{
    if (q != nullptr) {
        if (event.GetInt() == EVT_PUBLISHING_START) {
            // update by background slicing process
            if (process_completed_with_error >= 0) {
                wxString msg = _L("Please resolve the slicing errors and publish again.");
                this->m_publish_dlg->UpdateStatus(msg, false);
                return;
            }
            m_is_publishing = true;
            // if slicing is ready publish project, else slicing first
            if (partplate_list.is_all_slice_results_valid()) {
                q->publish_project();
            } else {
                BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received slice project in background event\n";
                SimpleEvent evt = SimpleEvent(EVT_GLTOOLBAR_SLICE_ALL);
                this->on_action_slice_all(evt);
            }
        } else {
            m_is_publishing = false;
            show_publish_dlg(false);
        }
    }
}
References _L, and EVT_PUBLISHING_START.
on_action_request_model_id()
void Slic3r::GUI::Plater::priv::on_action_request_model_id (wxCommandEvent & evt)
{
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received import model id event\n" ;
    if (q != nullptr) {
        q->import_model_id(evt.GetString().ToStdString());
    }
}
on_action_select_sliced_plate()
void Slic3r::GUI::Plater::priv::on_action_select_sliced_plate (wxCommandEvent & evt)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received select sliced plate event\n" ;
    }
    q->select_sliced_plate(evt.GetInt());
}
on_action_send_gcode()
void Slic3r::GUI::Plater::priv::on_action_send_gcode (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received export gcode event\n" ;
        q->send_gcode_legacy();
    }
}
on_action_send_to_printer()
void Slic3r::GUI::Plater::priv::on_action_send_to_printer (bool isall = false)
{
  if (!m_send_to_sdcard_dlg) m_send_to_sdcard_dlg = new SendToPrinterDialog(q);
    if (isall) {
        m_send_to_sdcard_dlg->prepare(PLATE_ALL_IDX);
    }
    else {
        m_send_to_sdcard_dlg->prepare(partplate_list.get_curr_plate_index());
    }
  m_send_to_sdcard_dlg->ShowModal();
}
References PLATE_ALL_IDX.
on_action_slice_all()
void Slic3r::GUI::Plater::priv::on_action_slice_all (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received slice project event\n" ;
        //BBS update extruder params and speed table before slicing
        Plater::setExtruderParams(Slic3r::Model::extruderParamsMap);
        Plater::setPrintSpeedTable(Slic3r::Model::printSpeedMap);
        m_slice_all = true;
        m_slice_all_only_has_gcode = true;
        m_cur_slice_plate = 0;
        //select plate
        q->select_plate(m_cur_slice_plate);
        q->reslice();
        if (!m_is_publishing)
            q->select_view_3D("Preview");
        //BBS: wish to select all plates stats item
        preview->get_canvas3d()->_update_select_plate_toolbar_stats_item(true);
    }
}
References Slic3r::Model::extruderParamsMap, Slic3r::Model::printSpeedMap, Slic3r::GUI::Plater::setExtruderParams(), and Slic3r::GUI::Plater::setPrintSpeedTable().
on_action_slice_plate()
void Slic3r::GUI::Plater::priv::on_action_slice_plate (SimpleEvent &)
{
    if (q != nullptr) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received slice plate event\n" ;
        //BBS update extruder params and speed table before slicing
        Plater::setExtruderParams(Slic3r::Model::extruderParamsMap);
        Plater::setPrintSpeedTable(Slic3r::Model::printSpeedMap);
        m_slice_all = false;
        q->reslice();
        q->select_view_3D("Preview");
    }
}
References Slic3r::Model::extruderParamsMap, Slic3r::Model::printSpeedMap, Slic3r::GUI::Plater::setExtruderParams(), and Slic3r::GUI::Plater::setPrintSpeedTable().
on_action_split_objects()
void Slic3r::GUI::Plater::priv::on_action_split_objects (SimpleEvent &)
{
    split_object();
}
References Slic3r::GUI::Plater::split_object().
on_action_split_volumes()
void Slic3r::GUI::Plater::priv::on_action_split_volumes (SimpleEvent &)
{
    split_volume();
}
References Slic3r::GUI::Plater::split_volume().
on_apple_change_color_mode()
void Slic3r::GUI::Plater::priv::on_apple_change_color_mode (wxSysColourChangedEvent & evt)
{
    m_is_dark = wxSystemSettings::GetAppearance().IsDark();
    if (view3D->get_canvas3d() && view3D->get_canvas3d()->is_initialized()) {
        view3D->get_canvas3d()->on_change_color_mode(m_is_dark);
        preview->get_canvas3d()->on_change_color_mode(m_is_dark);
        assemble_view->get_canvas3d()->on_change_color_mode(m_is_dark);
    }
}
on_change_color_mode()
void Slic3r::GUI::Plater::priv::on_change_color_mode (SimpleEvent & evt)
{
    m_is_dark = wxGetApp().app_config->get("dark_color_mode") == "1";
    view3D->get_canvas3d()->on_change_color_mode(m_is_dark);
    preview->get_canvas3d()->on_change_color_mode(m_is_dark);
    assemble_view->get_canvas3d()->on_change_color_mode(m_is_dark);
}
on_combobox_select()
void Slic3r::GUI::Plater::priv::on_combobox_select (wxCommandEvent & evt)
{
    PlaterPresetComboBox* preset_combo_box = dynamic_cast<PlaterPresetComboBox*>(evt.GetEventObject());
    if (preset_combo_box) {
        this->on_select_preset(evt);
    }
    else {
        this->on_select_bed_type(evt);
    }
}
on_export_began()
void Slic3r::GUI::Plater::priv::on_export_began (wxCommandEvent & evt)
{
    if (show_warning_dialog)
        warnings_dialog();
}
on_export_finished()
void Slic3r::GUI::Plater::priv::on_export_finished (wxCommandEvent & evt)
{
#if 0
    //BBS: also export 3mf to the same directory for debugging
    std::string gcode_path_str(evt.GetString().ToUTF8().data());
    fs::path gcode_path(gcode_path_str);
    if (q) {
        q->export_3mf(gcode_path.replace_extension(".3mf"), SaveStrategy::Silence); // BBS: silence
    }
#endif
}
References Slic3r::Silence.
on_filament_color_changed()
void Slic3r::GUI::Plater::priv::on_filament_color_changed (wxCommandEvent & event)
{
    //q->update_all_plate_thumbnails(true);
    //q->get_preview_canvas3D()->update_plate_thumbnails();
}
on_object_select()
void Slic3r::GUI::Plater::priv::on_object_select (SimpleEvent & evt)
{
    wxGetApp().obj_list()->update_selections();
    selection_changed();
}
on_plate_right_click()
void Slic3r::GUI::Plater::priv::on_plate_right_click (RBtnPlateEvent & evt)
{
    wxMenu* menu = menus.plate_menu();
#ifdef __linux__
    q->PopupMenu(menu);
#else
    //BBS: GUI refactor: move sidebar to the left
    int x, y;
    current_panel->GetPosition(&x, &y);
    q->PopupMenu(menu, (int)evt.data.first.x() + x, (int)evt.data.first.y());
    //q->PopupMenu(menu);
#endif
}
References Slic3r::GUI::Event< T >::data.
on_plate_selected()
void Slic3r::GUI::Plater::priv::on_plate_selected (SimpleEvent &)
{
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":received plate selected event\n" ;
    sidebar->obj_list()->on_plate_selected(partplate_list.get_curr_plate_index());
}
References Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::ObjectList::on_plate_selected(), and Slic3r::GUI::Plater::sidebar().
on_process_completed()
void Slic3r::GUI::Plater::priv::on_process_completed (SlicingProcessCompletedEvent & evt)
{
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": enter, m_ignore_event %1%, status %2%")%m_ignore_event %evt.status();
    //BBS:ignore cancel event for some special case
    if (m_ignore_event)
    {
        m_ignore_event = false;
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": ignore this event %1%") % evt.status();
        return;
    }
    //BBS: add project slice logic
    bool is_finished = !m_slice_all || (m_cur_slice_plate == (partplate_list.get_plate_count() - 1));
    //BBS: slice .gcode.3mf file related logic, assign is_finished again
    bool only_has_gcode_need_preview = false;
    auto plate_list = this->partplate_list.get_plate_list();
    bool has_print_instances = false;
    for (auto plate : plate_list)
        has_print_instances = has_print_instances || plate->has_printable_instances();
    if (this->model.objects.empty() && !has_print_instances)
        only_has_gcode_need_preview = true;
    if (only_has_gcode_need_preview && m_slice_all_only_has_gcode) {
        is_finished = (m_cur_slice_plate == (partplate_list.get_plate_count() - 1));
        if (is_finished)
            m_slice_all_only_has_gcode = false;
    }
    // Stop the background task, wait until the thread goes into the "Idle" state.
    // At this point of time the thread should be either finished or canceled,
    // so the following call just confirms, that the produced data were consumed.
    this->background_process.stop();
    notification_manager->set_slicing_progress_export_possible();
    // Reset the "export G-code path" name, so that the automatic background processing will be enabled again.
    this->background_process.reset_export();
    // This bool stops showing export finished notification even when process_completed_with_error is false
    bool has_error = false;
    if (evt.error()) {
        auto message = evt.format_error_message();
        if (evt.critical_error()) {
            if (q->m_tracking_popup_menu) {
                // We don't want to pop-up a message box when tracking a pop-up menu.
                // We postpone the error message instead.
                q->m_tracking_popup_menu_error_message = message.first;
            } else {
                show_error(q, message.first, message.second.size() != 0 && message.second[0] != 0);
                notification_manager->set_slicing_progress_hidden();
            }
        } else {
            std::vector<const ModelObject *> ptrs;
            for (auto oid : message.second)
            {
                const PrintObject *print_object = this->background_process.m_fff_print->get_object(ObjectID(oid));
                if (print_object) { ptrs.push_back(print_object->model_object()); }
            }
            notification_manager->push_slicing_error_notification(message.first, ptrs);
        }
        if (evt.invalidate_plater())
        {
            // BBS
#if 0
            const wxString invalid_str = _L("Invalid data");
            for (auto btn : { ActionButtonType::abReslice, ActionButtonType::abSendGCode, ActionButtonType::abExport })
                sidebar->set_btn_label(btn, invalid_str);
#endif
            process_completed_with_error = partplate_list.get_curr_plate_index();;
        }
        has_error = true;
        is_finished = true;
    }
    if (evt.cancelled()) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", cancel event, status: %1%") % evt.status();
        this->notification_manager->set_slicing_progress_canceled(_u8L("Slicing Canceled"));
        is_finished = true;
    }
    //BBS: set the current plater's slice result to valid
    if (!this->background_process.empty())
        this->background_process.get_current_plate()->update_slice_result_valid_state(evt.success());
    //BBS: update the action button according to the current plate's status
    bool ready_to_slice = !this->partplate_list.get_curr_plate()->is_slice_result_valid();
    // BBS
#if 0
    this->sidebar->show_sliced_info_sizer(evt.success());
#endif
    // This updates the "Slice now", "Export G-code", "Arrange" buttons status.
    // Namely, it refreshes the "Out of print bed" property of all the ModelObjects, and it enables
    // the "Slice now" and "Export G-code" buttons based on their "out of bed" status.
    //BBS: remove this update here, will be updated in update_fff_scene later
    //this->object_list_changed();
    // refresh preview
    if (view3D->is_dragging()) // updating scene now would interfere with the gizmo dragging
        delayed_scene_refresh = true;
    else {
        if (this->printer_technology == ptFFF) {
            if (is_finished)
                this->update_fff_scene();
        }
        else
            this->update_sla_scene();
    }
    //BBS: add slice&&print status update logic
    if (evt.cancelled()) {
        /*if (wxGetApp().get_mode() == comSimple)
            sidebar->set_btn_label(ActionButtonType::abReslice, "Slice now");
        show_action_buttons(true);*/
        ready_to_slice = true;
        //this->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, true, true);
        //BBS
        if (m_is_publishing) {
            m_publish_dlg->cancel();
        }
    } else {
        if((ready_to_slice) || (wxGetApp().get_mode() == comSimple)) {
            //this means the current plate is not the slicing plate
            //show_action_buttons(ready_to_slice);
            //this->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, ready_to_slice, true);
        }
        if (exporting_status != ExportingStatus::NOT_EXPORTING && !has_error) {
            notification_manager->stop_delayed_notifications_of_type(NotificationType::ExportOngoing);
            notification_manager->close_notification_of_type(NotificationType::ExportOngoing);
        }
        // If writing to removable drive was scheduled, show notification with eject button
        if (exporting_status == ExportingStatus::EXPORTING_TO_REMOVABLE && !has_error) {
            //show_action_buttons(ready_to_slice);
            this->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, ready_to_slice, true);
            notification_manager->push_exporting_finished_notification(last_output_path, last_output_dir_path,
                // Don't offer the "Eject" button on ChromeOS, the Linux side has no control over it.
                platform_flavor() != PlatformFlavor::LinuxOnChromium);
            wxGetApp().removable_drive_manager()->set_exporting_finished(true);
        }else
        if (exporting_status == ExportingStatus::EXPORTING_TO_LOCAL && !has_error)
            notification_manager->push_exporting_finished_notification(last_output_path, last_output_dir_path, false);
        // BBS, Generate calibration thumbnail for current plate
        if (!has_error && preview) {
            // generate calibration data
            /* BBS generate calibration data by printer
            preview->reload_print();
            ThumbnailData* calibration_data = &partplate_list.get_curr_plate()->cali_thumbnail_data;
            const ThumbnailsParams calibration_params = { {}, false, true, true, true, partplate_list.get_curr_plate_index() };
            generate_calibration_thumbnail(*calibration_data, PartPlate::cali_thumbnail_width, PartPlate::cali_thumbnail_height, calibration_params);
            preview->get_canvas3d()->reset_gcode_toolpaths();*/
            // generate bbox data
            PlateBBoxData* plate_bbox_data = &partplate_list.get_curr_plate()->cali_bboxes_data;
            *plate_bbox_data = generate_first_layer_bbox();
        }
    }
    exporting_status = ExportingStatus::NOT_EXPORTING;
    // BBS stop publishing if error occur
    //if (m_is_publishing) {
    //    GCodeProcessorResult *gcode_result = background_process.get_current_gcode_result();
    //    m_publish_dlg->UpdateStatus(_L("Error occurred during slicing"), -1, false);
    //    // if toolpath is outside
    //    if (!gcode_result || gcode_result->toolpath_outside) {
    //        m_is_publishing = false;
    //    }
    //}
    if (is_finished)
    {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":finished, reload print soon");
        m_is_slicing = false;
        this->preview->reload_print(false);
        /* BBS if in publishing progress */
        if (m_is_publishing) {
            if (m_publish_dlg && !m_publish_dlg->was_cancelled()) {
                if (m_publish_dlg->IsShown()) {
                    q->publish_project();
                } else {
                    m_is_publishing = false;
                }
            }
        }
        q->SetDropTarget(new PlaterDropTarget(q));
    }
    else
    {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":slicing all, plate %1% finished, start next slice...")%m_cur_slice_plate;
        m_cur_slice_plate++;
        q->Freeze();
        q->select_plate(m_cur_slice_plate);
        partplate_list.select_plate_view();
        int ret = q->start_next_slice();
        if (ret) {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":slicing all, plate %1% can not be sliced, will stop")%m_cur_slice_plate;
            m_is_slicing = false;
        }
        //not the last plate
        update_fff_scene_only_shells();
        q->Thaw();
        if (m_is_publishing) {
            if (m_publish_dlg && !m_publish_dlg->was_cancelled()) {
                wxString msg = wxString::Format(_L("Slicing Plate %d"), m_cur_slice_plate + 1);
                int percent  = 70 * m_cur_slice_plate / partplate_list.get_plate_count();
                m_publish_dlg->UpdateStatus(msg, percent, false);
            }
        }
    }
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", exit.");
}
References _L, _u8L, Slic3r::GUI::abExport, Slic3r::GUI::abReslice, Slic3r::GUI::abSendGCode, Slic3r::SlicingProcessCompletedEvent::cancelled(), Slic3r::comSimple, Slic3r::SlicingProcessCompletedEvent::critical_error(), Slic3r::GUI::MainFrame::eEventSliceUpdate, Slic3r::SlicingProcessCompletedEvent::error(), Slic3r::GUI::EXPORTING_TO_LOCAL, Slic3r::GUI::EXPORTING_TO_REMOVABLE, Slic3r::GUI::ExportOngoing, Slic3r::SlicingProcessCompletedEvent::format_error_message(), Slic3r::GUI::PartPlate::has_printable_instances(), Slic3r::SlicingProcessCompletedEvent::invalidate_plater(), Slic3r::LinuxOnChromium, Slic3r::PrintObjectBase::model_object(), Slic3r::GUI::NOT_EXPORTING, Slic3r::Model::objects, Slic3r::platform_flavor(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptFFF, Slic3r::GUI::Sidebar::set_btn_label(), Slic3r::GUI::show_error(), Slic3r::GUI::Plater::sidebar(), Slic3r::SlicingProcessCompletedEvent::status(), and Slic3r::SlicingProcessCompletedEvent::success().
on_repair_model()
void Slic3r::GUI::Plater::priv::on_repair_model (wxCommandEvent & event)
{
    wxGetApp().obj_list()->fix_through_netfabb();
}
on_right_click()
void Slic3r::GUI::Plater::priv::on_right_click (RBtnEvent & evt)
{
    int obj_idx = get_selected_object_idx();
    wxMenu* menu = nullptr;
    if (obj_idx == -1) { // no one or several object are selected
        if (evt.data.second) { // right button was clicked on empty space
            if (!get_selection().is_empty()) // several objects are selected in 3DScene
                return;
            menu = menus.default_menu();
        }
        else {
            if (current_panel == assemble_view) {
                menu = menus.assemble_multi_selection_menu();
            }
            else {
                menu = menus.multi_selection_menu();
            }
        }
    }
    else {
        // If in 3DScene is(are) selected volume(s), but right button was clicked on empty space
        if (evt.data.second)
            return;
        // Each context menu respects to the selected item in ObjectList,
        // so this selection should be updated before menu agyuicreation
        wxGetApp().obj_list()->update_selections();
        if (printer_technology == ptSLA)
            menu = menus.sla_object_menu();
        else {
            const Selection& selection = get_selection();
            // show "Object menu" for each one or several FullInstance instead of FullObject
            const bool is_some_full_instances = selection.is_single_full_instance() ||
                                                selection.is_single_full_object() ||
                                                selection.is_multiple_full_instance();
            const bool is_part = selection.is_single_volume() || selection.is_single_modifier();
            //BBS get assemble view menu
            if (current_panel == assemble_view) {
                menu = is_some_full_instances   ? menus.assemble_object_menu() :
                   is_part                  ? menus.assemble_part_menu()   : menus.assemble_multi_selection_menu();
            } else {
                menu = is_some_full_instances   ? menus.object_menu() :
                       is_part                  ? menus.part_menu()   : menus.multi_selection_menu();
            }
        }
    }
    if (q != nullptr && menu) {
#ifdef __linux__
        // For some reason on Linux the menu isn't displayed if position is specified
        // (even though the position is sane).
        q->PopupMenu(menu);
#else
        //BBS: GUI refactor: move sidebar to the left
        int x, y;
        current_panel->GetPosition(&x, &y);
        q->PopupMenu(menu, (int)evt.data.first.x() + x, (int)evt.data.first.y());
        //q->PopupMenu(menu);
#endif
    }
}
References Slic3r::GUI::Event< T >::data, Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::is_multiple_full_instance(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_modifier(), Slic3r::GUI::Selection::is_single_volume(), Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptSLA.
on_select_bed_type()
void Slic3r::GUI::Plater::priv::on_select_bed_type (wxCommandEvent & evt)
{
    ComboBox* combo = static_cast<ComboBox*>(evt.GetEventObject());
    int selection = combo->GetSelection();
    std::string bed_type_name = print_config_def.get("curr_bed_type")->enum_values[selection];
    PresetBundle& preset_bundle = *wxGetApp().preset_bundle;
    DynamicPrintConfig& proj_config = wxGetApp().preset_bundle->project_config;
    const t_config_enum_values* keys_map = print_config_def.get("curr_bed_type")->enum_keys_map;
    if (keys_map) {
        BedType new_bed_type = btCount;
        for (auto item : *keys_map) {
            if (item.first == bed_type_name) {
                new_bed_type = (BedType)item.second;
                break;
            }
        }
        if (new_bed_type != btCount) {
            BedType old_bed_type = proj_config.opt_enum<BedType>("curr_bed_type");
            if (old_bed_type != new_bed_type) {
                proj_config.set_key_value("curr_bed_type", new ConfigOptionEnum<BedType>(new_bed_type));
                wxGetApp().plater()->update_project_dirty_from_presets();
                // update plater with new config
                q->on_config_change(wxGetApp().preset_bundle->full_config());
                // update app_config
                AppConfig* app_config = wxGetApp().app_config;
                app_config->set("curr_bed_type", std::to_string(int(new_bed_type)));
                app_config->set_printer_setting(wxGetApp().preset_bundle->printers.get_selected_preset_name(),
                                                "curr_bed_type", std::to_string(int(new_bed_type)));
                //update slice status
                auto plate_list = partplate_list.get_plate_list();
                for (auto plate : plate_list) {
                    if (plate->get_bed_type() == btDefault) {
                        plate->update_slice_result_valid_state(false);
                    }
                }
                // update render
                view3D->get_canvas3d()->render();
                preview->msw_rescale();
            }
        }
    }
}
References Slic3r::btCount, Slic3r::btDefault, Slic3r::ConfigOptionDef::enum_keys_map, Slic3r::ConfigOptionDef::enum_values, Slic3r::PresetBundle::full_config(), Slic3r::ConfigDef::get(), Slic3r::GUI::PartPlate::get_bed_type(), Slic3r::PresetCollection::get_selected_preset_name(), ComboBox::GetSelection(), Slic3r::DynamicConfig::opt_enum(), Slic3r::print_config_def, Slic3r::PresetBundle::printers, Slic3r::AppConfig::set(), Slic3r::DynamicConfig::set_key_value(), Slic3r::AppConfig::set_printer_setting(), and Slic3r::GUI::PartPlate::update_slice_result_valid_state().
on_select_preset()
void Slic3r::GUI::Plater::priv::on_select_preset (wxCommandEvent & evt)
Because of The MSW and GTK version of wxBitmapComboBox derived from wxComboBox, but the OSX version derived from wxOwnerDrawnCombo. So, to get selected string we do combo->GetString(combo->GetSelection()) instead of combo->GetStringSelection().ToUTF8().data());
{
    PlaterPresetComboBox* combo = static_cast<PlaterPresetComboBox*>(evt.GetEventObject());
    Preset::Type preset_type    = combo->get_type();
    // Under OSX: in case of use of a same names written in different case (like "ENDER" and "Ender"),
    // m_presets_choice->GetSelection() will return first item, because search in PopupListCtrl is case-insensitive.
    // So, use GetSelection() from event parameter
    int selection = evt.GetSelection();
    auto idx = combo->get_filament_idx();
    std::string preset_name = wxGetApp().preset_bundle->get_preset_name_by_alias(preset_type,
        Preset::remove_suffix_modified(combo->GetString(selection).ToUTF8().data()));
    if (preset_type == Preset::TYPE_FILAMENT) {
        wxGetApp().preset_bundle->set_filament_preset(idx, preset_name);
        wxGetApp().plater()->update_project_dirty_from_presets();
        wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
        dynamic_filament_list.update();
    }
    bool select_preset = !combo->selection_is_changed_according_to_physical_printers();
    // TODO: ?
    if (preset_type == Preset::TYPE_FILAMENT && sidebar->is_multifilament()) {
        // Only update the plater UI for the 2nd and other filaments.
        combo->update();
    }
    else if (select_preset) {
        if (preset_type == Preset::TYPE_PRINTER) {
            PhysicalPrinterCollection& physical_printers = wxGetApp().preset_bundle->physical_printers;
            if(combo->is_selected_physical_printer())
                preset_name = physical_printers.get_selected_printer_preset_name();
            else
                physical_printers.unselect_printer();
        }
        //BBS
        //wxWindowUpdateLocker noUpdates1(sidebar->print_panel());
        wxWindowUpdateLocker noUpdates2(sidebar->filament_panel());
        wxGetApp().get_tab(preset_type)->select_preset(preset_name);
    }
    // update plater with new config
    q->on_config_change(wxGetApp().preset_bundle->full_config());
    if (preset_type == Preset::TYPE_PRINTER) {
    /* Settings list can be changed after printer preset changing, so
     * update all settings items for all item had it.
     * Furthermore, Layers editing is implemented only for FFF printers
     * and for SLA presets they should be deleted
     */
        wxGetApp().obj_list()->update_object_list_by_printer_technology();
    }
#ifdef __WXMSW__
    // From the Win 2004 preset combobox lose a focus after change the preset selection
    // and that is why the up/down arrow doesn't work properly
    // So, set the focus to the combobox explicitly
    combo->SetFocus();
#endif
    // BBS: log modify of filament selection
    Slic3r::put_other_changes();
    // update slice state and set bedtype default for 3rd-party printer
    auto plate_list = partplate_list.get_plate_list();
    for (auto plate : plate_list) {
         plate->update_slice_result_valid_state(false);
    }
}
References Slic3r::GUI::dynamic_filament_list, Slic3r::GUI::Sidebar::filament_panel(), Slic3r::GUI::PresetComboBox::get_filament_idx(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), Slic3r::GUI::PresetComboBox::get_type(), ComboBox::GetString(), Slic3r::GUI::Sidebar::is_multifilament(), Slic3r::GUI::PresetComboBox::is_selected_physical_printer(), Slic3r::put_other_changes(), Slic3r::Preset::remove_suffix_modified(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::Plater::sidebar(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, Slic3r::PhysicalPrinterCollection::unselect_printer(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::DynamicFilamentList::update(), and Slic3r::GUI::PartPlate::update_slice_result_valid_state().
on_slice_button_status()
void Slic3r::GUI::Plater::priv::on_slice_button_status (bool enable)
{
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ": enable = "<<enable<<"\n";
    if (!background_process.running())
        main_frame->update_slice_print_status(MainFrame::eEventObjectUpdate, enable);
}
References Slic3r::GUI::MainFrame::eEventObjectUpdate.
on_slicing_began()
void Slic3r::GUI::Plater::priv::on_slicing_began ()
{
    clear_warnings();
    notification_manager->close_notification_of_type(NotificationType::SignDetected);
    notification_manager->close_notification_of_type(NotificationType::ExportFinished);
    notification_manager->set_slicing_progress_began();
}
References Slic3r::GUI::ExportFinished, and Slic3r::GUI::SignDetected.
on_slicing_completed()
void Slic3r::GUI::Plater::priv::on_slicing_completed (wxCommandEvent & evt)
{
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": event_type %1%, string %2%") % evt.GetEventType() % evt.GetString();
    //BBS: add slice project logic
    if (m_slice_all && (m_cur_slice_plate < (partplate_list.get_plate_count() - 1))) {
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format("slicing all, finished plate %1%, will continue next.")%m_cur_slice_plate;
        return;
    }
    if (view3D->is_dragging()) // updating scene now would interfere with the gizmo dragging
        delayed_scene_refresh = true;
    else {
        if (this->printer_technology == ptFFF) {
            //BBS: only reload shells
            this->update_fff_scene_only_shells(false);
            //this->update_fff_scene();
        }
        else
            this->update_sla_scene();
    }
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format("exit.");
}
References Slic3r::GUI::Plater::printer_technology(), and Slic3r::ptFFF.
on_slicing_update()
void Slic3r::GUI::Plater::priv::on_slicing_update (SlicingStatusEvent & evt)
{
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": event_type %1%, percent %2%, text %3%") % evt.GetEventType() % evt.status.percent % evt.status.text;
    //BBS: add slice project logic
    std::string title_text = _u8L("Slicing");
    evt.status.text = title_text + evt.status.text;
    if (evt.status.percent >= 0) {
        if (m_ui_jobs.is_any_running()) {
            // Avoid a race condition
            return;
        }
        notification_manager->set_slicing_progress_percentage(evt.status.text, (float)evt.status.percent / 100.0f);
        // update slicing percent
        PartPlateList& plate_list = wxGetApp().plater()->get_partplate_list();
        //slicing parallel, only update if percent is greater than before
        if (evt.status.percent > plate_list.get_curr_plate()->get_slicing_percent())
            plate_list.get_curr_plate()->update_slicing_percent(evt.status.percent);
    }
    if (evt.status.flags & (PrintBase::SlicingStatus::RELOAD_SCENE | PrintBase::SlicingStatus::RELOAD_SLA_SUPPORT_POINTS)) {
        switch (this->printer_technology) {
        case ptFFF:
            //BBS: add slice project logic, only display shells at the beginning
            if (!m_slice_all || (m_cur_slice_plate == (partplate_list.get_plate_count() - 1)))
                //this->update_fff_scene();
                this->update_fff_scene_only_shells();
            break;
        case ptSLA:
            // If RELOAD_SLA_SUPPORT_POINTS, then the SLA gizmo is updated (reload_scene calls update_gizmos_data)
            if (view3D->is_dragging())
                delayed_scene_refresh = true;
            else
                this->update_sla_scene();
            break;
        default: break;
        }
    } else if (evt.status.flags & PrintBase::SlicingStatus::RELOAD_SLA_PREVIEW) {
        // Update the SLA preview. Only called if not RELOAD_SLA_SUPPORT_POINTS, as the block above will refresh the preview anyways.
        this->preview->reload_print();
    }
    if (evt.status.flags & (PrintBase::SlicingStatus::UPDATE_PRINT_STEP_WARNINGS | PrintBase::SlicingStatus::UPDATE_PRINT_OBJECT_STEP_WARNINGS)) {
        // Update notification center with warnings of object_id and its warning_step.
        ObjectID object_id = evt.status.warning_object_id;
        int warning_step = evt.status.warning_step;
        PrintStateBase::StateWithWarnings state;
        ModelObject const * model_object = nullptr;
        //BBS: add partplate related logic, use the print in background process
        if (evt.status.flags & PrintBase::SlicingStatus::UPDATE_PRINT_STEP_WARNINGS) {
            state = this->printer_technology == ptFFF ?
                this->background_process.m_fff_print->step_state_with_warnings(static_cast<PrintStep>(warning_step)) :
                this->background_process.m_sla_print->step_state_with_warnings(static_cast<SLAPrintStep>(warning_step));
        } else if (this->printer_technology == ptFFF) {
            const PrintObject *print_object = this->background_process.m_fff_print->get_object(object_id);
            if (print_object) {
                state = print_object->step_state_with_warnings(static_cast<PrintObjectStep>(warning_step));
                model_object = print_object->model_object();
            }
        } else {
            const SLAPrintObject *print_object = this->background_process.m_sla_print->get_object(object_id);
            if (print_object) {
                state = print_object->step_state_with_warnings(static_cast<SLAPrintObjectStep>(warning_step));
                model_object = print_object->model_object();
            }
        }
        // Now process state.warnings.
        for (auto const& warning : state.warnings) {
            if (warning.current) {
                notification_manager->push_slicing_warning_notification(warning.message, false, model_object, object_id, warning_step, warning.message_id);
                add_warning(warning, object_id.id);
            }
        }
    }
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format("exit.");
}
References _u8L, Slic3r::PrintBase::SlicingStatus::flags, Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::PartPlate::get_slicing_percent(), Slic3r::ObjectID::id, Slic3r::PrintObjectBase::model_object(), Slic3r::PrintBase::SlicingStatus::percent, Slic3r::GUI::Plater::printer_technology(), Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::PrintBase::SlicingStatus::RELOAD_SCENE, Slic3r::PrintBase::SlicingStatus::RELOAD_SLA_PREVIEW, Slic3r::PrintBase::SlicingStatus::RELOAD_SLA_SUPPORT_POINTS, Slic3r::SlicingStatusEvent::status, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::step_state_with_warnings(), Slic3r::PrintBase::SlicingStatus::text, Slic3r::PrintBase::SlicingStatus::UPDATE_PRINT_OBJECT_STEP_WARNINGS, Slic3r::PrintBase::SlicingStatus::UPDATE_PRINT_STEP_WARNINGS, Slic3r::GUI::PartPlate::update_slicing_percent(), Slic3r::PrintBase::SlicingStatus::warning_object_id, Slic3r::PrintBase::SlicingStatus::warning_step, and Slic3r::PrintStateBase::StateWithWarnings::warnings.
on_update_geometry()
void Slic3r::GUI::Plater::priv::on_update_geometry (Vec3dsEvent< 2 > &)
{
    // TODO
}
PopupObjectTable()
bool Slic3r::GUI::Plater::priv::PopupObjectTable (int object_id, int volume_id, const wxPoint & position)
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" enter, create ObjectTableDialog");
    int max_width{1920}, max_height{1080};
    max_width = q->GetMaxWidth();
    max_height = q->GetMaxHeight();
    ObjectTableDialog table_dialog(q, q, &model, wxSize(max_width, max_height));
    //m_popup_table = new ObjectTableDialog(q, q,  &model);
    wxRect rect = sidebar->GetRect();
    wxPoint pos = sidebar->ClientToScreen(wxPoint(rect.x, rect.y));
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": show ObjectTableDialog");
    table_dialog.Popup(object_id, volume_id, pos);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" finished, will destroy ObjectTableDialog");
    return true;
}
References Slic3r::GUI::Plater::model(), Slic3r::GUI::ObjectTableDialog::Popup(), and Slic3r::GUI::Plater::sidebar().
process_validation_warning()
void Slic3r::GUI::Plater::priv::process_validation_warning (StringObjectException const & warning) const
{
    if (warning.string.empty())
        notification_manager->close_notification_of_type(NotificationType::ValidateWarning);
    else {
        std::string text = warning.string;
        auto po = dynamic_cast<PrintObjectBase const *>(warning.object);
        auto mo = po ? po->model_object() : dynamic_cast<ModelObject const *>(warning.object);
        auto action_fn = (mo || !warning.opt_key.empty()) ? [id = mo ? mo->id() : 0, opt = warning.opt_key](wxEvtHandler *) {
        auto & objects = wxGetApp().model().objects;
        auto iter = id.id ? std::find_if(objects.begin(), objects.end(), [id](auto o) { return o->id() == id; }) : objects.end();
            if (iter != objects.end()) {
                wxGetApp().mainframe->select_tab(MainFrame::tp3DEditor);
          wxGetApp().obj_list()->select_items({{*iter, nullptr}});
            }
            if (!opt.empty()) {
                if (iter != objects.end())
            wxGetApp().params_panel()->switch_to_object();
                wxGetApp().sidebar().jump_to_option(opt, Preset::TYPE_PRINT, L"");
        }
        return false;
      } : std::function<bool(wxEvtHandler *)>();
        auto hypertext = (mo || !warning.opt_key.empty()) ? _u8L("Jump to") : "";
        if (mo) hypertext += std::string(" [") + mo->name + "]";
        if (!warning.opt_key.empty()) hypertext += std::string(" (") + warning.opt_key + ")";
        // BBS disable support enforcer
        //if (text == "_SUPPORTS_OFF") {
        //    text = _u8L("An object has custom support enforcers which will not be used "
        //                "because supports are disabled.")+"\n";
        //    hypertext = _u8L("Enable supports for enforcers only");
        //    action_fn = [](wxEvtHandler*) {
        //        Tab* print_tab = wxGetApp().get_tab(Preset::TYPE_PRINT);
        //        assert(print_tab);
        //        DynamicPrintConfig& config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
        //        config.set_key_value("enable_support", new ConfigOptionBool(true));
        //        config.set_key_value("auto_support_type", new ConfigOptionEnum<SupportType>(stNormalAuto));
        //        print_tab->on_value_change("enable_support", config.opt_bool("enable_support"));
        //        print_tab->on_value_change("support_material_auto", config.opt_bool("support_material_auto"));
        //        return true;
        //    };
        //}
        notification_manager->push_notification(
            NotificationType::ValidateWarning,
            NotificationManager::NotificationLevel::WarningNotificationLevel,
            _u8L("WARNING:") + "\n" + text, hypertext, action_fn
        );
    }
}
References _u8L, Slic3r::ObjectBase::id(), L, Slic3r::PrintObjectBase::model_object(), Slic3r::StringObjectException::object, Slic3r::StringObjectException::opt_key, Slic3r::StringObjectException::string, Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::Preset::TYPE_PRINT, Slic3r::GUI::ValidateWarning, and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
record_start_print_preset()
void Slic3r::GUI::Plater::priv::record_start_print_preset (std::string action) private
redo()
void Slic3r::GUI::Plater::priv::redo ()
{
    const std::vector<UndoRedo::Snapshot> &snapshots = this->undo_redo_stack().snapshots();
    auto it_current = std::lower_bound(snapshots.begin(), snapshots.end(), UndoRedo::Snapshot(this->undo_redo_stack().active_snapshot_time()));
    // BBS: undo-redo until modify record
    while (it_current != snapshots.end() && !snapshot_modifies_project(*it_current++));
    if (it_current != snapshots.end()) {
        while (it_current != snapshots.end() && !snapshot_modifies_project(*it_current++));
        this->undo_redo_to(--it_current);
    }
}
reload_all_from_disk()
void Slic3r::GUI::Plater::priv::reload_all_from_disk ()
{
    if (model.objects.empty())
        return;
    Plater::TakeSnapshot snapshot(q, "Reload all");
    Plater::SuppressSnapshots suppress(q);
    Selection& selection = get_selection();
    Selection::IndicesList curr_idxs = selection.get_volume_idxs();
    // reload from disk uses selection
    select_all();
    reload_from_disk();
    // restore previous selection
    selection.clear();
    for (unsigned int idx : curr_idxs) {
        selection.add(idx, false);
    }
}
References Slic3r::GUI::Selection::add(), Slic3r::GUI::Selection::clear(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::Plater::reload_from_disk(), and Slic3r::GUI::Plater::select_all().
reload_from_disk()
void Slic3r::GUI::Plater::priv::reload_from_disk ()
{
#if ENABLE_RELOAD_FROM_DISK_REWORK
    // collect selected reloadable ModelVolumes
    std::vector<std::pair<int, int>> selected_volumes = reloadable_volumes(model, get_selection());
    // nothing to reload, return
    if (selected_volumes.empty())
        return;
    std::sort(selected_volumes.begin(), selected_volumes.end(), [](const std::pair<int, int> &v1, const std::pair<int, int> &v2) {
        return (v1.first < v2.first) || (v1.first == v2.first && v1.second < v2.second);
        });
    selected_volumes.erase(std::unique(selected_volumes.begin(), selected_volumes.end(), [](const std::pair<int, int> &v1, const std::pair<int, int> &v2) {
        return (v1.first == v2.first) && (v1.second == v2.second);
        }), selected_volumes.end());
#else
    Plater::TakeSnapshot snapshot(q, "Reload from disk");
    const Selection& selection = get_selection();
    if (selection.is_wipe_tower())
        return;
    // struct to hold selected ModelVolumes by their indices
    struct SelectedVolume
    {
        int object_idx;
        int volume_idx;
        // operators needed by std::algorithms
        bool operator < (const SelectedVolume& other) const { return object_idx < other.object_idx || (object_idx == other.object_idx && volume_idx < other.volume_idx); }
        bool operator == (const SelectedVolume& other) const { return object_idx == other.object_idx && volume_idx == other.volume_idx; }
    };
    std::vector<SelectedVolume> selected_volumes;
    // collects selected ModelVolumes
    const std::set<unsigned int>& selected_volumes_idxs = selection.get_volume_idxs();
    for (unsigned int idx : selected_volumes_idxs) {
        const GLVolume* v = selection.get_volume(idx);
        int v_idx = v->volume_idx();
        if (v_idx >= 0) {
            int o_idx = v->object_idx();
            if (0 <= o_idx && o_idx < (int)model.objects.size())
                selected_volumes.push_back({ o_idx, v_idx });
        }
    }
    std::sort(selected_volumes.begin(), selected_volumes.end());
    selected_volumes.erase(std::unique(selected_volumes.begin(), selected_volumes.end()), selected_volumes.end());
#endif // ENABLE_RELOAD_FROM_DISK_REWORK
    // collects paths of files to load
    std::vector<fs::path> input_paths;
    std::vector<fs::path> missing_input_paths;
#if ENABLE_RELOAD_FROM_DISK_REWORK
    std::vector<std::pair<fs::path, fs::path>> replace_paths;
    for (auto [obj_idx, vol_idx] : selected_volumes) {
        const ModelObject *object = model.objects[obj_idx];
        const ModelVolume *volume = object->volumes[vol_idx];
        if (fs::exists(volume->source.input_file))
            input_paths.push_back(volume->source.input_file);
        else {
            // searches the source in the same folder containing the object
            bool found = false;
            if (!object->input_file.empty()) {
                fs::path object_path = fs::path(object->input_file).remove_filename();
                if (!object_path.empty()) {
                    object_path /= fs::path(volume->source.input_file).filename();
                    if (fs::exists(object_path)) {
                        input_paths.push_back(object_path);
                        found = true;
                    }
                }
            }
            if (!found)
                missing_input_paths.push_back(volume->source.input_file);
        }
    }
#else
    std::vector<fs::path> replace_paths;
    for (const SelectedVolume& v : selected_volumes) {
        const ModelObject* object = model.objects[v.object_idx];
        const ModelVolume* volume = object->volumes[v.volume_idx];
        if (!volume->source.input_file.empty()) {
            if (fs::exists(volume->source.input_file))
                input_paths.push_back(volume->source.input_file);
            else {
                // searches the source in the same folder containing the object
                bool found = false;
                if (!object->input_file.empty()) {
                    fs::path object_path = fs::path(object->input_file).remove_filename();
                    if (!object_path.empty()) {
                        object_path /= fs::path(volume->source.input_file).filename();
                        const std::string source_input_file = object_path.string();
                        if (fs::exists(source_input_file)) {
                            input_paths.push_back(source_input_file);
                            found = true;
                        }
                    }
                }
                if (!found)
                    missing_input_paths.push_back(volume->source.input_file);
            }
        }
        else if (!object->input_file.empty() && volume->is_model_part() && !volume->name.empty() && !volume->source.is_from_builtin_objects)
            missing_input_paths.push_back(volume->name);
    }
#endif // ENABLE_RELOAD_FROM_DISK_REWORK
    std::sort(missing_input_paths.begin(), missing_input_paths.end());
    missing_input_paths.erase(std::unique(missing_input_paths.begin(), missing_input_paths.end()), missing_input_paths.end());
    while (!missing_input_paths.empty()) {
        // ask user to select the missing file
        fs::path search = missing_input_paths.back();
        wxString title = _L("Please select a file");
#if defined(__APPLE__)
        title += " (" + from_u8(search.filename().string()) + ")";
#endif // __APPLE__
        title += ":";
        wxFileDialog dialog(q, title, "", from_u8(search.filename().string()), file_wildcards(FT_MODEL), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
        if (dialog.ShowModal() != wxID_OK)
            return;
        std::string sel_filename_path = dialog.GetPath().ToUTF8().data();
        std::string sel_filename = fs::path(sel_filename_path).filename().string();
        if (boost::algorithm::iequals(search.filename().string(), sel_filename)) {
            input_paths.push_back(sel_filename_path);
            missing_input_paths.pop_back();
            fs::path sel_path = fs::path(sel_filename_path).remove_filename().string();
            std::vector<fs::path>::iterator it = missing_input_paths.begin();
            while (it != missing_input_paths.end()) {
                // try to use the path of the selected file with all remaining missing files
                fs::path repathed_filename = sel_path;
                repathed_filename /= it->filename();
                if (fs::exists(repathed_filename)) {
                    input_paths.push_back(repathed_filename.string());
                    it = missing_input_paths.erase(it);
                }
                else
                    ++it;
            }
        }
        else {
            wxString      message = _devL("Do you want to replace it") + " ?";
            MessageDialog dlg(q, message, wxMessageBoxCaptionStr, wxYES_NO | wxYES_DEFAULT | wxICON_QUESTION);
            if (dlg.ShowModal() == wxID_YES)
#if ENABLE_RELOAD_FROM_DISK_REWORK
                replace_paths.emplace_back(search, sel_filename_path);
#else
                replace_paths.emplace_back(sel_filename_path);
#endif // ENABLE_RELOAD_FROM_DISK_REWORK
            missing_input_paths.pop_back();
        }
    }
    std::sort(input_paths.begin(), input_paths.end());
    input_paths.erase(std::unique(input_paths.begin(), input_paths.end()), input_paths.end());
    std::sort(replace_paths.begin(), replace_paths.end());
    replace_paths.erase(std::unique(replace_paths.begin(), replace_paths.end()), replace_paths.end());
#if ENABLE_RELOAD_FROM_DISK_REWORK
    Plater::TakeSnapshot snapshot(q, "Reload from disk");
#endif // ENABLE_RELOAD_FROM_DISK_REWORK
    std::vector<wxString> fail_list;
    // load one file at a time
    for (size_t i = 0; i < input_paths.size(); ++i) {
        const auto& path = input_paths[i].string();
        wxBusyCursor wait;
        wxBusyInfo info(_devL("Reload from:") + " " + from_u8(path), q->get_current_canvas3D()->get_wxglcanvas());
        Model new_model;
        try
        {
            //BBS: add plate data related logic
            PlateDataPtrs plate_data;
            //BBS: project embedded settings
            std::vector<Preset*> project_presets;
            // BBS: backup
            new_model = Model::read_from_file(path, nullptr, nullptr, LoadStrategy::AddDefaultInstances, &plate_data, &project_presets);
            for (ModelObject* model_object : new_model.objects)
            {
                model_object->center_around_origin();
                model_object->ensure_on_bed();
            }
            if (plate_data.size() > 0)
            {
                partplate_list.load_from_3mf_structure(plate_data);
                partplate_list.update_slice_context_to_current_plate(background_process);
                this->preview->update_gcode_result(partplate_list.get_current_slice_result());
                release_PlateData_list(plate_data);
                sidebar->obj_list()->reload_all_plates();
            }
        }
        catch (std::exception&)
        {
            // error while loading
            return;
        }
#if ENABLE_RELOAD_FROM_DISK_REWORK
        for (auto [obj_idx, vol_idx] : selected_volumes) {
            ModelObject *old_model_object = model.objects[obj_idx];
            ModelVolume *old_volume       = old_model_object->volumes[vol_idx];
            bool sinking = old_model_object->bounding_box().min.z() < SINKING_Z_THRESHOLD;
            bool has_source = !old_volume->source.input_file.empty() &&
                              boost::algorithm::iequals(fs::path(old_volume->source.input_file).filename().string(), fs::path(path).filename().string());
            bool has_name = !old_volume->name.empty() && boost::algorithm::iequals(old_volume->name, fs::path(path).filename().string());
            if (has_source || has_name) {
                int  new_volume_idx = -1;
                int  new_object_idx = -1;
                bool match_found    = false;
                // take idxs from the matching volume
                if (has_source && old_volume->source.object_idx < int(new_model.objects.size())) {
                    const ModelObject *obj = new_model.objects[old_volume->source.object_idx];
                    if (old_volume->source.volume_idx < int(obj->volumes.size())) {
                        if (obj->volumes[old_volume->source.volume_idx]->source.input_file == old_volume->source.input_file) {
                            new_volume_idx = old_volume->source.volume_idx;
                            new_object_idx = old_volume->source.object_idx;
                            match_found    = true;
                        }
                    }
                }
                if (!match_found && has_name) {
                    // take idxs from the 1st matching volume
                    for (size_t o = 0; o < new_model.objects.size(); ++o) {
                        ModelObject *obj   = new_model.objects[o];
                        bool         found = false;
                        for (size_t v = 0; v < obj->volumes.size(); ++v) {
                            if (obj->volumes[v]->name == old_volume->name) {
                                new_volume_idx = (int) v;
                                new_object_idx = (int) o;
                                found          = true;
                                break;
                            }
                        }
                        if (found) break;
                    }
                }
                if (new_object_idx < 0 || int(new_model.objects.size()) <= new_object_idx) {
                    fail_list.push_back(from_u8(has_source ? old_volume->source.input_file : old_volume->name));
                    continue;
                }
                ModelObject *new_model_object = new_model.objects[new_object_idx];
                if (new_volume_idx < 0 || int(new_model_object->volumes.size()) <= new_volume_idx) {
                    fail_list.push_back(from_u8(has_source ? old_volume->source.input_file : old_volume->name));
                    continue;
                }
                old_model_object->add_volume(*new_model_object->volumes[new_volume_idx]);
                ModelVolume *new_volume = old_model_object->volumes.back();
                new_volume->set_new_unique_id();
                new_volume->config.apply(old_volume->config);
                new_volume->set_type(old_volume->type());
                new_volume->set_material_id(old_volume->material_id());
                Transform3d transform = Transform3d::Identity();
                transform.translate(new_volume->source.mesh_offset - old_volume->source.mesh_offset);
                new_volume->set_transformation(old_volume->get_transformation().get_matrix() * old_volume->source.transform.get_matrix(true) *
                                               transform * new_volume->source.transform.get_matrix(true).inverse());
                new_volume->source.object_idx = old_volume->source.object_idx;
                new_volume->source.volume_idx = old_volume->source.volume_idx;
                assert(!old_volume->source.is_converted_from_inches || !old_volume->source.is_converted_from_meters);
                if (old_volume->source.is_converted_from_inches)
                    new_volume->convert_from_imperial_units();
                else if (old_volume->source.is_converted_from_meters)
                    new_volume->convert_from_meters();
                std::swap(old_model_object->volumes[vol_idx], old_model_object->volumes.back());
                old_model_object->delete_volume(old_model_object->volumes.size() - 1);
                if (!sinking) old_model_object->ensure_on_bed();
                old_model_object->sort_volumes(wxGetApp().app_config->get("order_volumes") == "1");
                sla::reproject_points_and_holes(old_model_object);
                // Fix warning icon in object list
                wxGetApp().obj_list()->update_item_error_icon(obj_idx, vol_idx);
            }
        }
#else
        // update the selected volumes whose source is the current file
        for (const SelectedVolume& sel_v : selected_volumes) {
            ModelObject* old_model_object = model.objects[sel_v.object_idx];
            ModelVolume* old_volume = old_model_object->volumes[sel_v.volume_idx];
            bool sinking = old_model_object->bounding_box().min.z() < SINKING_Z_THRESHOLD;
            bool has_source = !old_volume->source.input_file.empty() && boost::algorithm::iequals(fs::path(old_volume->source.input_file).filename().string(), fs::path(path).filename().string());
            bool has_name = !old_volume->name.empty() && boost::algorithm::iequals(old_volume->name, fs::path(path).filename().string());
            if (has_source || has_name) {
                int new_volume_idx = -1;
                int new_object_idx = -1;
//                if (has_source) {
//                    // take idxs from source
//                    new_volume_idx = old_volume->source.volume_idx;
//                    new_object_idx = old_volume->source.object_idx;
//                }
//                else {
                    // take idxs from the 1st matching volume
                    for (size_t o = 0; o < new_model.objects.size(); ++o) {
                        ModelObject* obj = new_model.objects[o];
                        bool found = false;
                        for (size_t v = 0; v < obj->volumes.size(); ++v) {
                            if (obj->volumes[v]->name == old_volume->name) {
                                new_volume_idx = (int)v;
                                new_object_idx = (int)o;
                                found = true;
                                break;
                            }
                        }
                        if (found)
                            break;
                    }
//                }
                if (new_object_idx < 0 || int(new_model.objects.size()) <= new_object_idx) {
                    fail_list.push_back(from_u8(has_source ? old_volume->source.input_file : old_volume->name));
                    continue;
                }
                ModelObject* new_model_object = new_model.objects[new_object_idx];
                if (new_volume_idx < 0 || int(new_model_object->volumes.size()) <= new_volume_idx) {
                    fail_list.push_back(from_u8(has_source ? old_volume->source.input_file : old_volume->name));
                    continue;
                }
                old_model_object->add_volume(*new_model_object->volumes[new_volume_idx]);
                ModelVolume* new_volume = old_model_object->volumes.back();
                new_volume->set_new_unique_id();
                new_volume->config.apply(old_volume->config);
                new_volume->set_type(old_volume->type());
                new_volume->set_material_id(old_volume->material_id());
                new_volume->set_transformation(old_volume->get_transformation());
                new_volume->translate(new_volume->get_transformation().get_matrix(true) * (new_volume->source.mesh_offset - old_volume->source.mesh_offset));
                new_volume->source.object_idx = old_volume->source.object_idx;
                new_volume->source.volume_idx = old_volume->source.volume_idx;
                assert(! old_volume->source.is_converted_from_inches || ! old_volume->source.is_converted_from_meters);
                if (old_volume->source.is_converted_from_inches)
                    new_volume->convert_from_imperial_units();
                else if (old_volume->source.is_converted_from_meters)
                    new_volume->convert_from_meters();
                std::swap(old_model_object->volumes[sel_v.volume_idx], old_model_object->volumes.back());
                old_model_object->delete_volume(old_model_object->volumes.size() - 1);
                if (!sinking)
                    old_model_object->ensure_on_bed();
                old_model_object->sort_volumes(true);
                sla::reproject_points_and_holes(old_model_object);
            }
        }
#endif // ENABLE_RELOAD_FROM_DISK_REWORK
    }
#if ENABLE_RELOAD_FROM_DISK_REWORK
    for (auto [src, dest] : replace_paths) {
        for (auto [obj_idx, vol_idx] : selected_volumes) {
            if (boost::algorithm::iequals(model.objects[obj_idx]->volumes[vol_idx]->source.input_file, src.string()))
                replace_volume_with_stl(obj_idx, vol_idx, dest, "");
        }
    }
#else
    for (size_t i = 0; i < replace_paths.size(); ++i) {
        const auto& path = replace_paths[i].string();
        for (const SelectedVolume& sel_v : selected_volumes) {
            ModelObject* old_model_object = model.objects[sel_v.object_idx];
            ModelVolume* old_volume = old_model_object->volumes[sel_v.volume_idx];
            bool has_source = !old_volume->source.input_file.empty() && boost::algorithm::iequals(fs::path(old_volume->source.input_file).filename().string(), fs::path(path).filename().string());
            if (!replace_volume_with_stl(sel_v.object_idx, sel_v.volume_idx, path, "")) {
                fail_list.push_back(from_u8(has_source ? old_volume->source.input_file : old_volume->name));
            }
        }
    }
#endif // ENABLE_RELOAD_FROM_DISK_REWORK
    if (!fail_list.empty()) {
        wxString message = _devL("Unable to reload:") + "\n";
        for (const wxString& s : fail_list) {
            message += s + "\n";
        }
        MessageDialog dlg(q, message, _devL("Error during reload"), wxOK | wxOK_DEFAULT | wxICON_WARNING);
        dlg.ShowModal();
    }
    // update 3D scene
    update();
    // new GLVolumes have been created at this point, so update their printable state
    for (size_t i = 0; i < model.objects.size(); ++i) {
        view3D->get_canvas3d()->update_instance_printable_state_for_object(i);
    }
}
References Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::GUI::Plater::model(), Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::GUI::operator<(), operator==(), and Slic3r::GLVolume::volume_idx().
remove()
void Slic3r::GUI::Plater::priv::remove (size_t obj_idx)
{
    if (view3D->is_layers_editing_enabled())
        view3D->enable_layers_editing(false);
    m_ui_jobs.cancel_all();
    model.delete_object(obj_idx);
    //BBS: notify partplate the instance removed
    partplate_list.notify_instance_removed(obj_idx, -1);
    update();
    // Delete object from Sidebar list. Do it after update, so that the GLScene selection is updated with the modified model.
    sidebar->obj_list()->delete_object_from_list(obj_idx);
    object_list_changed();
}
References Slic3r::Model::delete_object(), Slic3r::GUI::ObjectList::delete_object_from_list(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::object_list_changed(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Plater::update().
remove_curr_plate_all()
void Slic3r::GUI::Plater::priv::remove_curr_plate_all ()
{
    SingleSnapshot ss(q);
    view3D->remove_curr_plate_all();
    this->sidebar->obj_list()->update_selections();
}
References Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::ObjectList::update_selections().
replace_volume_with_stl()
bool Slic3r::GUI::Plater::priv::replace_volume_with_stl (int object_idx, int volume_idx, const fs::path & new_path, const std::string & snapshot = "")
{
    const std::string path = new_path.string();
    wxBusyCursor wait;
    wxBusyInfo info(_devL("Replace from:") + " " + from_u8(path), q->get_current_canvas3D()->get_wxglcanvas());
    Model new_model;
    try {
        new_model = Model::read_from_file(path, nullptr, nullptr, LoadStrategy::AddDefaultInstances);
        for (ModelObject* model_object : new_model.objects) {
            model_object->center_around_origin();
            model_object->ensure_on_bed();
        }
    }
    catch (std::exception&) {
        // error while loading
        return false;
    }
    if (new_model.objects.size() > 1 || new_model.objects.front()->volumes.size() > 1) {
        MessageDialog dlg(q, _devL("Unable to replace with more than one volume"), _devL("Error during replace"), wxOK | wxOK_DEFAULT | wxICON_WARNING);
        dlg.ShowModal();
        return false;
    }
    if (!snapshot.empty())
        q->take_snapshot(snapshot);
    ModelObject* old_model_object = model.objects[object_idx];
    ModelVolume* old_volume = old_model_object->volumes[volume_idx];
    bool sinking = old_model_object->bounding_box().min.z() < SINKING_Z_THRESHOLD;
    ModelObject* new_model_object = new_model.objects.front();
    old_model_object->add_volume(*new_model_object->volumes.front());
    ModelVolume* new_volume = old_model_object->volumes.back();
    new_volume->set_new_unique_id();
    new_volume->config.apply(old_volume->config);
    new_volume->set_type(old_volume->type());
    new_volume->set_material_id(old_volume->material_id());
    new_volume->set_transformation(old_volume->get_transformation());
    new_volume->translate(new_volume->get_transformation().get_matrix(true) * (new_volume->source.mesh_offset - old_volume->source.mesh_offset));
    assert(!old_volume->source.is_converted_from_inches || !old_volume->source.is_converted_from_meters);
    if (old_volume->source.is_converted_from_inches)
        new_volume->convert_from_imperial_units();
    else if (old_volume->source.is_converted_from_meters)
        new_volume->convert_from_meters();
    new_volume->supported_facets.assign(old_volume->supported_facets);
    new_volume->seam_facets.assign(old_volume->seam_facets);
    new_volume->mmu_segmentation_facets.assign(old_volume->mmu_segmentation_facets);
    std::swap(old_model_object->volumes[volume_idx], old_model_object->volumes.back());
    old_model_object->delete_volume(old_model_object->volumes.size() - 1);
    if (!sinking)
        old_model_object->ensure_on_bed();
    old_model_object->sort_volumes(true);
    // if object has just one volume, rename object too
    if (old_model_object->volumes.size() == 1)
        old_model_object->name = old_model_object->volumes.front()->name;
    // update new name in ObjectList
    sidebar->obj_list()->update_name_in_list(object_idx, volume_idx);
    sla::reproject_points_and_holes(old_model_object);
    return true;
}
References _devL, Slic3r::ModelObject::add_volume(), Slic3r::AddDefaultInstances, Slic3r::ModelConfig::apply(), Slic3r::FacetsAnnotation::assign(), Slic3r::ModelObject::bounding_box(), Slic3r::ModelVolume::config, Slic3r::ModelVolume::convert_from_imperial_units(), Slic3r::ModelVolume::convert_from_meters(), Slic3r::ModelObject::delete_volume(), Slic3r::ModelObject::ensure_on_bed(), Slic3r::GUI::from_u8(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::ModelVolume::get_transformation(), Slic3r::ModelVolume::Source::is_converted_from_inches, Slic3r::ModelVolume::Source::is_converted_from_meters, Slic3r::ModelVolume::material_id(), Slic3r::ModelVolume::Source::mesh_offset, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::ModelVolume::mmu_segmentation_facets, Slic3r::GUI::Plater::model(), Slic3r::ModelObject::name, Slic3r::GUI::Sidebar::obj_list(), Slic3r::Model::objects, Slic3r::Model::read_from_file(), Slic3r::sla::reproject_points_and_holes(), Slic3r::ModelVolume::seam_facets, Slic3r::ModelVolume::set_material_id(), Slic3r::ModelVolume::set_new_unique_id(), Slic3r::ModelVolume::set_transformation(), Slic3r::ModelVolume::set_type(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::GUI::Plater::sidebar(), Slic3r::SINKING_Z_THRESHOLD, Slic3r::ModelObject::sort_volumes(), Slic3r::ModelVolume::source, Slic3r::ModelVolume::supported_facets, Slic3r::ModelVolume::translate(), Slic3r::ModelVolume::type(), Slic3r::GUI::ObjectList::update_name_in_list(), and Slic3r::ModelObject::volumes.
replace_with_stl()
void Slic3r::GUI::Plater::priv::replace_with_stl ()
{
    if (! q->get_view3D_canvas3D()->get_gizmos_manager().check_gizmos_closed_except(GLGizmosManager::EType::Undefined))
        return;
    const Selection& selection = get_selection();
    if (selection.is_wipe_tower() || get_selection().get_volume_idxs().size() != 1)
        return;
    const GLVolume* v = selection.get_volume(*selection.get_volume_idxs().begin());
    int object_idx = v->object_idx();
    int volume_idx = v->volume_idx();
    // collects paths of files to load
    const ModelObject* object = model.objects[object_idx];
    const ModelVolume* volume = object->volumes[volume_idx];
    fs::path input_path;
    if (!volume->source.input_file.empty() && fs::exists(volume->source.input_file))
        input_path = volume->source.input_file;
    wxString title = _L("Select a new file");
    title += ":";
    wxFileDialog dialog(q, title, "", from_u8(input_path.filename().string()), file_wildcards(FT_MODEL), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() != wxID_OK)
        return;
    fs::path out_path = dialog.GetPath().ToUTF8().data();
    if (out_path.empty()) {
        MessageDialog dlg(q, _L("File for the replace wasn't selected"), _L("Error during replace"), wxOK | wxOK_DEFAULT | wxICON_WARNING);
        dlg.ShowModal();
        return;
    }
    if (!replace_volume_with_stl(object_idx, volume_idx, out_path, "Replace with STL"))
        return;
    // update 3D scene
    update();
    // new GLVolumes have been created at this point, so update their printable state
    for (size_t i = 0; i < model.objects.size(); ++i) {
        view3D->get_canvas3d()->update_instance_printable_state_for_object(i);
    }
}
References _L, Slic3r::GUI::file_wildcards(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_MODEL, Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::GUI::Plater::model(), Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::GUI::DPIAware< P >::ShowModal(), size, Slic3r::GUI::GLGizmosManager::Undefined, Slic3r::GUI::Plater::update(), and Slic3r::GLVolume::volume_idx().
reset()
void Slic3r::GUI::Plater::priv::reset (bool apply_presets_change = false)
{
    Plater::TakeSnapshot snapshot(q, "Reset Project", UndoRedo::SnapshotType::ProjectSeparator);
    clear_warnings();
    set_project_filename("");
    if (view3D->is_layers_editing_enabled())
        view3D->get_canvas3d()->force_main_toolbar_left_action(view3D->get_canvas3d()->get_main_toolbar_item_id("layersediting"));
    view3D->get_canvas3d()->reset_all_gizmos();
    reset_gcode_toolpaths();
    //BBS: update gcode to current partplate's
    //GCodeProcessorResult* current_result = this->background_process.get_current_plate()->get_slice_result();
    //current_result->reset();
    //gcode_result.reset();
    view3D->get_canvas3d()->reset_sequential_print_clearance();
    m_ui_jobs.cancel_all();
    //BBS: clear the partplate list's object before object cleared
    partplate_list.reinit();
    partplate_list.update_slice_context_to_current_plate(background_process);
    preview->update_gcode_result(partplate_list.get_current_slice_result());
    // Stop and reset the Print content.
    this->background_process.reset();
    model.clear_objects();
    assemble_view->get_canvas3d()->reset_explosion_ratio();
    update();
    //BBS
    if (wxGetApp().is_editor()) {
        // Delete object from Sidebar list. Do it after update, so that the GLScene selection is updated with the modified model.
        sidebar->obj_list()->delete_all_objects_from_list();
        object_list_changed();
    }
    project.reset();
    //BBS: reset all project embedded presets
    wxGetApp().preset_bundle->reset_project_embedded_presets();
    if (apply_presets_change)
        wxGetApp().apply_keeped_preset_modifications();
    else
        wxGetApp().load_current_presets(false, false);
    //BBS
    model.calib_pa_pattern.reset();
    model.plates_custom_gcodes.clear();
    // BBS
    m_saved_timestamp = m_backup_timestamp = size_t(-1);
}
References Slic3r::Model::calib_pa_pattern, Slic3r::Model::clear_objects(), Slic3r::GUI::ObjectList::delete_all_objects_from_list(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::object_list_changed(), Slic3r::Model::plates_custom_gcodes, Slic3r::UndoRedo::ProjectSeparator, Slic3r::GUI::Plater::reset_gcode_toolpaths(), Slic3r::GUI::Plater::set_project_filename(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Plater::update().
reset_all_gizmos()
void Slic3r::GUI::Plater::priv::reset_all_gizmos ()
{
    view3D->get_canvas3d()->reset_all_gizmos();
}
reset_canvas_volumes()
void Slic3r::GUI::Plater::priv::reset_canvas_volumes ()
{
    if (view3D != nullptr)
        view3D->get_canvas3d()->reset_volumes();
    if (preview != nullptr)
        preview->get_canvas3d()->reset_volumes();
}
reset_gcode_toolpaths()
void Slic3r::GUI::Plater::priv::reset_gcode_toolpaths ()
{
    preview->get_canvas3d()->reset_gcode_toolpaths();
}
reset_project_dirty_after_save()
void Slic3r::GUI::Plater::priv::reset_project_dirty_after_save () inline
{ m_undo_redo_stack_main.mark_current_as_saved(); dirty_state.reset_after_save(); }
References dirty_state, m_undo_redo_stack_main, Slic3r::UndoRedo::Stack::mark_current_as_saved(), and Slic3r::GUI::ProjectDirtyStateManager::reset_after_save().
reset_project_dirty_initial_presets()
void Slic3r::GUI::Plater::priv::reset_project_dirty_initial_presets () inline
{ dirty_state.reset_initial_presets(); }
References dirty_state, and Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets().
restart_background_process()
bool Slic3r::GUI::Plater::priv::restart_background_process (unsigned int state)
{
    if (m_ui_jobs.is_any_running()) {
        // Avoid a race condition
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(", Line %1%: ui jobs running, return false")%__LINE__;
        return false;
    }
    if ( ! this->background_process.empty() &&
         (state & priv::UPDATE_BACKGROUND_PROCESS_INVALID) == 0 &&
         ( ((state & UPDATE_BACKGROUND_PROCESS_FORCE_RESTART) != 0 && ! this->background_process.finished()) ||
           (state & UPDATE_BACKGROUND_PROCESS_FORCE_EXPORT) != 0 ||
           (state & UPDATE_BACKGROUND_PROCESS_RESTART) != 0 ) ) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: print is valid, try to start it now")%__LINE__;
        // The print is valid and it can be started.
        if (this->background_process.start()) {
            if (!show_warning_dialog)
                on_slicing_began();
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: start successfully")%__LINE__;
            return true;
        }
    }
    else if (this->background_process.empty()) {
        PartPlate* cur_plate = background_process.get_current_plate();
        if (cur_plate->is_slice_result_valid() && ((state & UPDATE_BACKGROUND_PROCESS_FORCE_RESTART) != 0)) {
            if (this->background_process.start()) {
                if (!show_warning_dialog)
                    on_slicing_began();
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: start successfully")%__LINE__;
                return true;
            }
        }
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: not started")%__LINE__;
    return false;
}
References Slic3r::GUI::PartPlate::is_slice_result_valid(), and UPDATE_BACKGROUND_PROCESS_INVALID.
save_project_if_dirty()
int Slic3r::GUI::Plater::priv::save_project_if_dirty (const wxString & reason) inline
{
        int res = wxID_NO;
        if (dirty_state.is_dirty()) {
            MainFrame* mainframe = wxGetApp().mainframe;
            if (mainframe->can_save_as()) {
                wxString suggested_project_name;
                wxString project_name = suggested_project_name = get_project_filename(".3mf");
                if (suggested_project_name.IsEmpty()) {
                    fs::path output_file = get_export_file_path(FT_3MF);
                    suggested_project_name = output_file.empty() ? _L("Untitled") : from_u8(output_file.stem().string());
                }
                res = MessageDialog(mainframe, reason + "\n" + format_wxstr(_L("Do you want to save changes to \"%1%\"?"), suggested_project_name),
                                    wxString(SLIC3R_APP_FULL_NAME), wxYES_NO | wxCANCEL).ShowModal();
                if (res == wxID_YES)
                    if (!mainframe->save_project_as(project_name))
                        res = wxID_CANCEL;
            }
        }
        return res;
    }
References _L, Slic3r::GUI::MainFrame::can_save_as(), dirty_state, Slic3r::GUI::format_wxstr(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_3MF, get_export_file_path(), get_project_filename(), Slic3r::GUI::ProjectDirtyStateManager::is_dirty(), Slic3r::GUI::MainFrame::save_project_as(), Slic3r::GUI::DPIAware< P >::ShowModal(), and SLIC3R_APP_FULL_NAME.
scale_selection_to_fit_print_volume()
void Slic3r::GUI::Plater::priv::scale_selection_to_fit_print_volume ()
{
#if ENABLE_ENHANCED_PRINT_VOLUME_FIT
    this->view3D->get_canvas3d()->get_selection().scale_to_fit_print_volume(this->bed.build_volume());
#else
    this->view3D->get_canvas3d()->get_selection().scale_to_fit_print_volume(*config);
#endif // ENABLE_ENHANCED_PRINT_VOLUME_FIT
}
References Slic3r::GUI::Plater::config().
scaled_bed_shape_bb()
BoundingBox Slic3r::GUI::Plater::priv::scaled_bed_shape_bb () const
{
    const auto *bed_shape_opt = config->opt<ConfigOptionPoints>("printable_area");
    const auto printable_area = Slic3r::Polygon::new_scale(bed_shape_opt->values);
    return printable_area.bounding_box();
}
References Slic3r::GUI::Plater::config(), Slic3r::Polygon::new_scale(), and Slic3r::DynamicConfig::opt().
schedule_background_process()
void Slic3r::GUI::Plater::priv::schedule_background_process ()
{
    delayed_error_message.clear();
    // Trigger the timer event after 0.5s
    this->background_process_timer.Start(500, wxTIMER_ONE_SHOT);
    // Notify the Canvas3D that something has changed, so it may invalidate some of the layer editing stuff.
    this->view3D->get_canvas3d()->set_config(this->config);
}
References Slic3r::GUI::Plater::config().
select_all()
void Slic3r::GUI::Plater::priv::select_all ()
{
    view3D->select_all();
    this->sidebar->obj_list()->update_selections();
}
References Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::ObjectList::update_selections().
select_curr_plate_all()
void Slic3r::GUI::Plater::priv::select_curr_plate_all ()
{
    view3D->select_curr_plate_all();
    this->sidebar->obj_list()->update_selections();
}
References Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::ObjectList::update_selections().
select_next_view_3D()
void Slic3r::GUI::Plater::priv::select_next_view_3D ()
{
    if (current_panel == view3D)
        wxGetApp().mainframe->select_tab(size_t(MainFrame::tpPreview));
    else if (current_panel == preview)
        wxGetApp().mainframe->select_tab(size_t(MainFrame::tp3DEditor));
//    else if (current_panel == assemble_view)
//        set_current_panel(view3D);
}
References Slic3r::GUI::MainFrame::tp3DEditor, and Slic3r::GUI::MainFrame::tpPreview.
select_view()
void Slic3r::GUI::Plater::priv::select_view (const std::string & direction)
{
    if (current_panel == view3D) {
        BOOST_LOG_TRIVIAL(info) << "select view3D";
        view3D->select_view(direction);
        wxGetApp().update_ui_from_settings();
    }
    else if (current_panel == preview) {
        BOOST_LOG_TRIVIAL(info) << "select preview";
        preview->select_view(direction);
        wxGetApp().update_ui_from_settings();
    }
    else if (current_panel == assemble_view) {
        BOOST_LOG_TRIVIAL(info) << "select assemble view";
        assemble_view->select_view(direction);
    }
}
select_view_3D()
void Slic3r::GUI::Plater::priv::select_view_3D (const std::string & name, bool no_slice = true)
{
    if (name == "3D") {
        BOOST_LOG_TRIVIAL(info) << "select view3D";
        if (q->only_gcode_mode() || q->using_exported_file()) {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("goto preview page when loading gcode/exported_3mf");
        }
        set_current_panel(view3D, no_slice);
    }
    else if (name == "Preview") {
        BOOST_LOG_TRIVIAL(info) << "select preview";
        //BBS update extruder params and speed table before slicing
        Plater::setExtruderParams(Slic3r::Model::extruderParamsMap);
        Plater::setPrintSpeedTable(Slic3r::Model::printSpeedMap);
        set_current_panel(preview, no_slice);
    }
    else if (name == "Assemble") {
        BOOST_LOG_TRIVIAL(info) << "select assemble view";
        set_current_panel(assemble_view, no_slice);
    }
    //BBS update selection
    wxGetApp().obj_list()->update_selections();
    selection_changed();
    apply_free_camera_correction(false);
}
References Slic3r::Model::extruderParamsMap, Slic3r::Model::printSpeedMap, Slic3r::GUI::Plater::setExtruderParams(), and Slic3r::GUI::Plater::setPrintSpeedTable().
selection_changed()
void Slic3r::GUI::Plater::priv::selection_changed ()
{
    // if the selection is not valid to allow for layer editing, we need to turn off the tool if it is running
    if (!layers_height_allowed() && view3D->is_layers_editing_enabled()) {
        SimpleEvent evt(EVT_GLTOOLBAR_LAYERSEDITING);
        on_action_layersediting(evt);
    }
    // forces a frame render to update the view (to avoid a missed update if, for example, the context menu appears)
    view3D->render();
}
set_bed_shape()
void Slic3r::GUI::Plater::priv::set_bed_shape (const Pointfs & shape, const Pointfs & exclude_areas, const double printable_height, const std::string & custom_texture, const std::string & custom_model, bool force_as_custom = false)
{
    //BBS: add shape position
    Vec2d shape_position = partplate_list.get_current_shape_position();
    bool new_shape = bed.set_shape(shape, printable_height, custom_model, force_as_custom, shape_position);
    float prev_height_lid, prev_height_rod;
    partplate_list.get_height_limits(prev_height_lid, prev_height_rod);
    auto prev_logo = partplate_list.get_logo_texture_filename();
    double height_to_lid = config->opt_float("extruder_clearance_height_to_lid");
    double height_to_rod = config->opt_float("extruder_clearance_height_to_rod");
    auto custom_bed_texture = config->opt_string("bed_custom_texture");
    Pointfs prev_exclude_areas = partplate_list.get_exclude_area();
    new_shape |= (height_to_lid != prev_height_lid) || (height_to_rod != prev_height_rod) || (prev_exclude_areas != exclude_areas) || (prev_logo != custom_bed_texture);
    if (new_shape) {
        if (view3D) view3D->bed_shape_changed();
        if (preview) preview->bed_shape_changed();
        //BBS: update part plate's size
        // BBS: to be checked
        Vec3d max = bed.extended_bounding_box().max;
        Vec3d min = bed.extended_bounding_box().min;
        double z = config->opt_float("printable_height");
        //Pointfs& exclude_areas = config->option<ConfigOptionPoints>("bed_exclude_area")->values;
        partplate_list.reset_size(max.x() - min.x() - Bed3D::Axes::DefaultTipRadius, max.y() - min.y() - Bed3D::Axes::DefaultTipRadius, z);
        partplate_list.set_shapes(shape, exclude_areas, custom_texture, height_to_lid, height_to_rod);
        Vec2d new_shape_position = partplate_list.get_current_shape_position();
        if (shape_position != new_shape_position)
            bed.set_shape(shape, printable_height, custom_model, force_as_custom, new_shape_position);
    }
}
References Slic3r::GUI::Plater::config(), Slic3r::GUI::Bed3D::Axes::DefaultTipRadius, max(), min(), Slic3r::DynamicConfig::opt_float(), Slic3r::DynamicConfig::opt_string(), and Slic3r::printable_height().
set_current_canvas_as_dirty()
void Slic3r::GUI::Plater::priv::set_current_canvas_as_dirty ()
{
    if (current_panel == view3D)
        view3D->set_as_dirty();
    else if (current_panel == preview)
        preview->set_as_dirty();
    else if (current_panel == assemble_view)
        assemble_view->set_as_dirty();
}
set_current_panel()
void Slic3r::GUI::Plater::priv::set_current_panel (wxPanel * panel, bool no_slice = true)
{
    if (std::find(panels.begin(), panels.end(), panel) == panels.end())
        return;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": current_panel %1%, new_panel %2%")%current_panel%panel;
#ifdef __WXMAC__
    bool force_render = (current_panel != nullptr);
#endif // __WXMAC__
    //BBS: add slice logic when switch to preview page
    auto do_reslice = [this, no_slice]() {
            // see: Plater::priv::object_list_changed()
            // FIXME: it may be better to have a single function making this check and let it be called wherever needed
            bool export_in_progress = this->background_process.is_export_scheduled();
            bool model_fits = this->view3D->get_canvas3d()->check_volumes_outside_state() != ModelInstancePVS_Partly_Outside;
            //BBS: add partplate logic
            PartPlate * current_plate = this->partplate_list.get_curr_plate();
            bool only_has_gcode_need_preview = false;
            bool current_has_print_instances = current_plate->has_printable_instances();
            if (current_plate->is_slice_result_valid() && this->model.objects.empty() && !current_has_print_instances)
                only_has_gcode_need_preview = true;
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": from set_current_panel, no_slice %1%, export_in_progress %2%, model_fits %3%, m_is_slicing %4%")%no_slice%export_in_progress%model_fits%m_is_slicing;
            if (!no_slice && !this->model.objects.empty() && !export_in_progress && model_fits && current_has_print_instances)
            {
                //if already running in background, not relice here
                //BBS: add more judge for slicing
                if (!this->background_process.running() && !this->m_is_slicing)
                {
                    this->m_slice_all = false;
                    this->q->reslice();
                }
                else {
                    //reset current plate to the slicing plate
                    int plate_index = this->background_process.get_current_plate()->get_index();
                    this->partplate_list.select_plate(plate_index);
                }
            }
            else if (only_has_gcode_need_preview)
            {
                this->m_slice_all = false;
                this->q->reslice();
            }
            //BBS: process empty plate, reset previous toolpath
            else
            {
                //if (!this->m_slice_all)
                if (!current_has_print_instances)
                    reset_gcode_toolpaths();
                //this->q->refresh_print();
                if (!preview->get_canvas3d()->is_initialized())
                {
                    preview->get_canvas3d()->render(true);
                }
            }
            //TODO: turn off this switch currently
            /*auto canvas_w = float(preview->get_canvas3d()->get_canvas_size().get_width());
            auto canvas_h = float(preview->get_canvas3d()->get_canvas_size().get_height());
            Point screen_center(canvas_w/2, canvas_h/2);
            auto center_point = preview->get_canvas3d()->_mouse_to_3d(screen_center);
            center_point(2) = 0.f;
            if (!current_plate->contains(center_point))
                this->partplate_list.select_plate_view();*/
            // keeps current gcode preview, if any
            if (this->m_slice_all) {
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": slicing all, just reload shells");
                this->update_fff_scene_only_shells();
            }
            else {
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": single slice, reload print");
                if (model_fits)
                    this->preview->reload_print(true);
                else
                    this->update_fff_scene_only_shells();
            }
            preview->set_as_dirty();
        };
    if (current_panel == panel)
    {
        //BBS: add slice logic when switch to preview page
        //BBS: add only gcode mode
        if (!q->only_gcode_mode() && (current_panel == preview) && (wxGetApp().is_editor())) {
            do_reslice();
        }
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": the same panel, exit");
        return;
    }
    //BBS: wish to reset all plates stats item selected state when back to View3D Tab
    preview->get_canvas3d()->reset_select_plate_toolbar_selection();
    wxPanel* old_panel = current_panel;
//#if BBL_HAS_FIRST_PAGE
    if (!old_panel) {
        //BBS: only switch to the first panel when visible
        panel->Show();
        //dynamic_cast<View3D *>(panel)->get_canvas3d()->render();
        if (!panel->IsShownOnScreen())
            return;
    }
//#endif
    current_panel = panel;
    //BBS: add the collapse logic
    if (current_panel == preview && q->only_gcode_mode()) {
        this->sidebar->collapse(true);
        preview->get_canvas3d()->enable_select_plate_toolbar(false);
    }
    else if (current_panel == preview && q->using_exported_file() && (q->m_valid_plates_count <= 1)) {
        preview->get_canvas3d()->enable_select_plate_toolbar(false);
    }
    else {
        preview->get_canvas3d()->enable_select_plate_toolbar(true);
    }
    // to reduce flickering when changing view, first set as visible the new current panel
    for (wxPanel* p : panels) {
        if (p == current_panel) {
#ifdef __WXMAC__
            // On Mac we need also to force a render to avoid flickering when changing view
            if (force_render) {
                if (p == view3D)
                    dynamic_cast<View3D*>(p)->get_canvas3d()->render();
                else if (p == preview)
                    dynamic_cast<Preview*>(p)->get_canvas3d()->render();
            }
#endif // __WXMAC__
            p->Show();
        }
    }
    // then set to invisible the other
    for (wxPanel* p : panels) {
        if (p != current_panel)
            p->Hide();
    }
    panel_sizer->Layout();
    if (wxGetApp().plater()) {
        Camera& cam = wxGetApp().plater()->get_camera();
        if (old_panel == preview || old_panel == view3D) {
            view3D->get_canvas3d()->get_camera().load_camera_view(cam);
        } else if (old_panel == assemble_view) {
            assemble_view->get_canvas3d()->get_camera().load_camera_view(cam);
        }
        if (current_panel == view3D || current_panel == preview) {
            cam.load_camera_view(view3D->get_canvas3d()->get_camera());
        }
        else if (current_panel == assemble_view) {
            cam.load_camera_view(assemble_view->get_canvas3d()->get_camera());
        }
    }
    if (current_panel == view3D) {
        if (old_panel == preview)
            preview->get_canvas3d()->unbind_event_handlers();
        else if (old_panel == assemble_view)
            assemble_view->get_canvas3d()->unbind_event_handlers();
        view3D->get_canvas3d()->bind_event_handlers();
        if (view3D->is_reload_delayed()) {
            // Delayed loading of the 3D scene.
            if (printer_technology == ptSLA) {
                // Update the SLAPrint from the current Model, so that the reload_scene()
                // pulls the correct data.
                update_restart_background_process(true, false);
            } else
                view3D->reload_scene(true);
        }
        // sets the canvas as dirty to force a render at the 1st idle event (wxWidgets IsShownOnScreen() is buggy and cannot be used reliably)
        view3D->set_as_dirty();
        // reset cached size to force a resize on next call to render() to keep imgui in synch with canvas size
        view3D->get_canvas3d()->reset_old_size();
        // BBS
        //view_toolbar.select_item("3D");
        if (notification_manager != nullptr)
            notification_manager->set_in_preview(false);
    }
    else if (current_panel == preview) {
        q->invalid_all_plate_thumbnails();
        if (old_panel == view3D)
            view3D->get_canvas3d()->unbind_event_handlers();
        else if (old_panel == assemble_view)
            assemble_view->get_canvas3d()->unbind_event_handlers();
        preview->get_canvas3d()->bind_event_handlers();
        GLGizmosManager& gizmos = view3D->get_canvas3d()->get_gizmos_manager();
        if (gizmos.is_running()) {
            gizmos.reset_all_states();
            gizmos.update_data();
        }
        if (wxGetApp().is_editor()) {
            // see: Plater::priv::object_list_changed()
            // FIXME: it may be better to have a single function making this check and let it be called wherever needed
            /*bool export_in_progress = this->background_process.is_export_scheduled();
            bool model_fits = view3D->get_canvas3d()->check_volumes_outside_state() != ModelInstancePVS_Partly_Outside;
            //BBS: add partplate logic
            PartPlate* current_plate = partplate_list.get_curr_plate();
            if (!no_slice && !model.objects.empty() && !export_in_progress && model_fits && current_plate->has_printable_instances()) {
                preview->get_canvas3d()->init_gcode_viewer();
                // BBS
                //if already running in background, not relice here
                if (!this->background_process.running())
                {
                    m_slice_all = false;
                    this->q->reslice();
                }
            }
            // keeps current gcode preview, if any
            preview->reload_print(true);
            preview->set_as_dirty();*/
            if (wxGetApp().is_editor() && !q->only_gcode_mode())
                do_reslice();
        }
        // reset cached size to force a resize on next call to render() to keep imgui in synch with canvas size
        preview->get_canvas3d()->reset_old_size();
        // BBS
        //view_toolbar.select_item("Preview");
        if (notification_manager != nullptr)
            notification_manager->set_in_preview(true);
    }
    else if (current_panel == assemble_view) {
        if (old_panel == view3D) {
            view3D->get_canvas3d()->unbind_event_handlers();
        }
        else if (old_panel == preview)
            preview->get_canvas3d()->unbind_event_handlers();
        assemble_view->get_canvas3d()->bind_event_handlers();
        assemble_view->reload_scene(true);
        // BBS set default view and zoom
        if (first_enter_assemble) {
            wxGetApp().plater()->get_camera().requires_zoom_to_volumes = true;
            first_enter_assemble = false;
        }
        assemble_view->set_as_dirty();
        // BBS
        //view_toolbar.select_item("Assemble");
    }
    current_panel->SetFocusFromKbd();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": successfully, exit");
}
References Slic3r::GUI::Sidebar::collapse(), Slic3r::GUI::PartPlate::has_printable_instances(), Slic3r::GUI::GLGizmosManager::is_running(), Slic3r::GUI::PartPlate::is_slice_result_valid(), Slic3r::GUI::Camera::load_camera_view(), Slic3r::ModelInstancePVS_Partly_Outside, Slic3r::Model::objects, Slic3r::GUI::Plater::p, Slic3r::GUI::Plater::printer_technology(), Slic3r::ptSLA, Slic3r::GUI::View3D::render(), Slic3r::GUI::GLGizmosManager::reset_all_states(), Slic3r::GUI::Plater::reset_gcode_toolpaths(), Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::GLGizmosManager::update_data().
set_need_update()
void Slic3r::GUI::Plater::priv::set_need_update (bool need_update) inline
{ m_need_update = need_update; }
References m_need_update, and need_update().
set_plater_dirty()
void Slic3r::GUI::Plater::priv::set_plater_dirty (bool is_dirty) inline
{ dirty_state.set_plater_dirty(is_dirty); }
References dirty_state, and Slic3r::GUI::ProjectDirtyStateManager::set_plater_dirty().
set_project_filename()
void Slic3r::GUI::Plater::priv::set_project_filename (const wxString & filename)
{
    boost::filesystem::path full_path = into_path(filename);
    boost::filesystem::path ext = full_path.extension();
    //if (boost::iequals(ext.string(), ".amf")) {
    //    // Remove the first extension.
    //    full_path.replace_extension("");
    //    // It may be ".zip.amf".
    //    if (boost::iequals(full_path.extension().string(), ".zip"))
    //        // Remove the 2nd extension.
    //        full_path.replace_extension("");
    //} else {
    //    // Remove just one extension.
    //    full_path.replace_extension("");
    //}
    full_path.replace_extension("");
    m_project_folder = full_path.parent_path();
    //BBS
    wxString project_name = from_u8(full_path.filename().string());
    set_project_name(project_name);
    // record filename for hint when open exported file/.gcode
    if (q->m_only_gcode)
        q->m_preview_only_filename = std::string((project_name + ".gcode").mb_str());
    if (q->m_exported_file)
        q->m_preview_only_filename = std::string((project_name + ".3mf").mb_str());
    wxGetApp().mainframe->update_title();
    if (!m_project_folder.empty() && !q->m_only_gcode)
        wxGetApp().mainframe->add_to_recent_projects(filename);
}
References Slic3r::GUI::from_u8(), and Slic3r::GUI::into_path().
set_project_name()
void Slic3r::GUI::Plater::priv::set_project_name (const wxString & project_name)
{
    m_project_name = project_name;
    //update topbar title
    wxGetApp().mainframe->SetTitle(m_project_name);
#ifdef __WINDOWS__
    wxGetApp().mainframe->topbar()->SetTitle(m_project_name);
#else
    if (!m_project_name.IsEmpty())
        wxGetApp().mainframe->update_title_colour_after_set_title();
#endif
}
show_delayed_error_message()
void Slic3r::GUI::Plater::priv::show_delayed_error_message () inline
{
        if (!this->delayed_error_message.empty()) {
            std::string msg = std::move(this->delayed_error_message);
            this->delayed_error_message.clear();
            GUI::show_error(this->q, msg);
        }
    }
References Slic3r::GUI::show_error().
show_install_plugin_hint()
void Slic3r::GUI::Plater::priv::show_install_plugin_hint (wxCommandEvent & event)
{
    notification_manager->bbl_show_plugin_install_notification(into_u8(_L("Network Plug-in is not detected. Network related features are unavailable.")));
}
References _L, and Slic3r::GUI::into_u8().
show_preview_only_hint()
void Slic3r::GUI::Plater::priv::show_preview_only_hint (wxCommandEvent & event)
{
    notification_manager->bbl_show_preview_only_notification(into_u8(_L("Preview only mode:\nThe loaded file contains gcode only, Can not enter the Prepare page")));
}
References _L, and Slic3r::GUI::into_u8().
show_publish_dlg()
bool Slic3r::GUI::Plater::priv::show_publish_dlg (bool show = true)
{
    if (q != nullptr) { BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << ":recevied publish event\n"; }
    if (!m_publish_dlg) m_publish_dlg = new PublishDialog(q);
    if (show) {
        m_publish_dlg->reset();
        m_publish_dlg->start_slicing();
        //m_publish_dlg->Show();
        m_publish_dlg->ShowModal();
    } else {
        m_publish_dlg->EndModal(wxID_OK);
        //cancel the slicing
        if (this->background_process.running())
            this->background_process.stop();
    }
    return true;
}
show_view3D_labels()
void Slic3r::GUI::Plater::priv::show_view3D_labels (bool show) inline
{ if (current_panel == view3D) view3D->get_canvas3d()->show_labels(show); }
References current_panel, Slic3r::GUI::View3D::get_canvas3d(), Slic3r::GUI::GLCanvas3D::show_labels(), and view3D.
show_view3D_overhang()
void Slic3r::GUI::Plater::priv::show_view3D_overhang (bool show) inline
    {
        if (current_panel == view3D) view3D->get_canvas3d()->show_overhang(show);
    }
References current_panel, Slic3r::GUI::View3D::get_canvas3d(), Slic3r::GUI::GLCanvas3D::show_overhang(), and view3D.
single_snapshots_enter()
void Slic3r::GUI::Plater::priv::single_snapshots_enter (SingleSnapshot * single) inline
    {
        if (m_single == nullptr) m_single = single;
    }
References m_single.
single_snapshots_leave()
void Slic3r::GUI::Plater::priv::single_snapshots_leave (SingleSnapshot * single) inline
    {
        if (m_single == single) m_single = nullptr;
    }
References m_single.
split_object()
void Slic3r::GUI::Plater::priv::split_object ()
{
    int obj_idx = get_selected_object_idx();
    if (obj_idx == -1)
        return;
    // we clone model object because split_object() adds the split volumes
    // into the same model object, thus causing duplicates when we call load_model_objects()
    Model new_model = model;
    ModelObject* current_model_object = new_model.objects[obj_idx];
    wxBusyCursor wait;
    ModelObjectPtrs new_objects;
    current_model_object->split(&new_objects);
    if (new_objects.size() == 1)
        // #ysFIXME use notification
        Slic3r::GUI::warning_catcher(q, _L("The selected object couldn't be split."));
    else
    {
        // BBS no solid parts removed
        // If we splited object which is contain some parts/modifiers then all non-solid parts (modifiers) were deleted
        //if (current_model_object->volumes.size() > 1 && current_model_object->volumes.size() != new_objects.size())
        //    notification_manager->push_notification(NotificationType::CustomNotification,
        //        NotificationManager::NotificationLevel::PrintInfoNotificationLevel,
        //        _u8L("All non-solid parts (modifiers) were deleted"));
        Plater::TakeSnapshot snapshot(q, "Split to Objects");
        remove(obj_idx);
        // load all model objects at once, otherwise the plate would be rearranged after each one
        // causing original positions not to be kept
        //BBS: set split_object to true to avoid re-compute assemble matrix
        std::vector<size_t> idxs = load_model_objects(new_objects, false, true);
        // select newly added objects
        for (size_t idx : idxs)
        {
            get_selection().add_object((unsigned int)idx, false);
        }
    }
}
References _L, Slic3r::GUI::Selection::add_object(), Slic3r::GUI::Plater::get_selected_object_idx(), Slic3r::GUI::Plater::get_selection(), Slic3r::GUI::Plater::model(), Slic3r::Model::objects, Slic3r::GUI::Plater::remove(), Slic3r::ModelObject::split(), and Slic3r::GUI::warning_catcher().
split_volume()
void Slic3r::GUI::Plater::priv::split_volume ()
{
    wxGetApp().obj_list()->split();
}
statusbar()
std::shared_ptr< BBLStatusBar > Slic3r::GUI::Plater::priv::statusbar ()
{
    return nullptr;
}
suppress_snapshots()
void Slic3r::GUI::Plater::priv::suppress_snapshots () inline
{ m_prevent_snapshots++; }
References m_prevent_snapshots.
take_snapshot()
void Slic3r::GUI::Plater::priv::take_snapshot (const std::string & snapshot_name, UndoRedo::SnapshotType snapshot_type = UndoRedo::SnapshotType::Action)
{
    if (m_prevent_snapshots > 0)
        return;
    assert(m_prevent_snapshots >= 0);
    // BBS: single snapshot
    if (m_single && !m_single->check(snapshot_modifies_project(snapshot_type) && (snapshot_name.empty() || snapshot_name.back() != '!')))
        return;
    UndoRedo::SnapshotData snapshot_data;
    snapshot_data.snapshot_type      = snapshot_type;
    snapshot_data.printer_technology = this->printer_technology;
    if (this->view3D->is_layers_editing_enabled())
        snapshot_data.flags |= UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE;
    if (this->sidebar->obj_list()->is_selected(itSettings)) {
        snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR;
        snapshot_data.layer_range_idx = this->sidebar->obj_list()->get_selected_layers_range_idx();
    }
    else if (this->sidebar->obj_list()->is_selected(itLayer)) {
        snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR;
        snapshot_data.layer_range_idx = this->sidebar->obj_list()->get_selected_layers_range_idx();
    }
    else if (this->sidebar->obj_list()->is_selected(itLayerRoot))
        snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR;
    // If SLA gizmo is active, ask it if it wants to trigger support generation
    // on loading this snapshot.
    if (view3D->get_canvas3d()->get_gizmos_manager().wants_reslice_supports_on_undo())
        snapshot_data.flags |= UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS;
    //FIXME updating the Wipe tower config values at the ModelWipeTower from the Print config.
    // This is a workaround until we refactor the Wipe Tower position / orientation to live solely inside the Model, not in the Print config.
    // BBS: add partplate logic
    if (this->printer_technology == ptFFF) {
        const DynamicPrintConfig& config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
        const DynamicPrintConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
        const ConfigOptionFloats* tower_x_opt = proj_cfg.option<ConfigOptionFloats>("wipe_tower_x");
        const ConfigOptionFloats* tower_y_opt = proj_cfg.option<ConfigOptionFloats>("wipe_tower_y");
        assert(tower_x_opt->values.size() == tower_y_opt->values.size());
        model.wipe_tower.positions.clear();
        model.wipe_tower.positions.resize(tower_x_opt->values.size());
        for (int plate_idx = 0; plate_idx < tower_x_opt->values.size(); plate_idx++) {
            ModelWipeTower& tower = model.wipe_tower;
            tower.positions[plate_idx] = Vec2d(tower_x_opt->get_at(plate_idx), tower_y_opt->get_at(plate_idx));
            tower.rotation = proj_cfg.opt_float("wipe_tower_rotation_angle");
        }
    }
    const GLGizmosManager& gizmos = get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView ? assemble_view->get_canvas3d()->get_gizmos_manager() : view3D->get_canvas3d()->get_gizmos_manager();
    if (snapshot_type == UndoRedo::SnapshotType::ProjectSeparator)
        this->undo_redo_stack().clear();
    this->undo_redo_stack().take_snapshot(snapshot_name, model, get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView ? assemble_view->get_canvas3d()->get_selection() : view3D->get_canvas3d()->get_selection(), gizmos, partplate_list, snapshot_data);
    if (snapshot_type == UndoRedo::SnapshotType::LeavingGizmoWithAction) {
        // Filter all but the last UndoRedo::SnapshotType::GizmoAction in a row between the last UndoRedo::SnapshotType::EnteringGizmo and UndoRedo::SnapshotType::LeavingGizmoWithAction.
        // The remaining snapshot will be renamed to a more generic name,
        // depending on what gizmo is being left.
        if (gizmos.get_current() != nullptr) {
            std::string new_name = gizmos.get_current()->get_action_snapshot_name();
            this->undo_redo_stack().reduce_noisy_snapshots(new_name);
        }
    } else if (snapshot_type == UndoRedo::SnapshotType::ProjectSeparator) {
        // Reset the "dirty project" flag.
        m_undo_redo_stack_main.mark_current_as_saved();
    }
    //BBS: add PartPlateList as the paremeter for take_snapshot
    this->undo_redo_stack().release_least_recently_used();
    dirty_state.update_from_undo_redo_stack(m_undo_redo_stack_main.project_modified());
    // Save the last active preset name of a particular printer technology.
    ((this->printer_technology == ptFFF) ? m_last_fff_printer_profile_name : m_last_sla_printer_profile_name) = wxGetApp().preset_bundle->printers.get_selected_preset_name();
    BOOST_LOG_TRIVIAL(info) << "Undo / Redo snapshot taken: " << snapshot_name << ", Undo / Redo stack memory: " << Slic3r::format_memsize_MB(this->undo_redo_stack().memsize()) << log_memory_info();
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::GUI::Plater::config(), Slic3r::UndoRedo::SnapshotData::flags, Slic3r::format_memsize_MB(), Slic3r::GUI::GLGizmoBase::get_action_snapshot_name(), Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::GLGizmosManager::get_current(), Slic3r::GUI::Plater::get_current_canvas3D(), Slic3r::GUI::ObjectList::get_selected_layers_range_idx(), Slic3r::GUI::ObjectList::is_selected(), Slic3r::GUI::itLayer, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itSettings, Slic3r::UndoRedo::SnapshotData::layer_range_idx, Slic3r::UndoRedo::LeavingGizmoWithAction, Slic3r::log_memory_info(), Slic3r::GUI::Plater::model(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::DynamicConfig::opt_float(), Slic3r::ConfigBase::option(), Slic3r::ModelWipeTower::positions, Slic3r::GUI::Plater::printer_technology(), Slic3r::UndoRedo::SnapshotData::printer_technology, Slic3r::UndoRedo::ProjectSeparator, Slic3r::ptFFF, Slic3r::UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS, Slic3r::ModelWipeTower::rotation, Slic3r::UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR, Slic3r::UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR, Slic3r::UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR, Slic3r::GUI::Plater::sidebar(), Slic3r::UndoRedo::SnapshotData::snapshot_type, Slic3r::ConfigOptionVector< T >::values, Slic3r::UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE, and Slic3r::Model::wipe_tower.
Referenced by Slic3r::GUI::Plater::priv::Jobs::arrange(), Slic3r::GUI::Plater::priv::Jobs::fill_bed(), Slic3r::GUI::Plater::priv::Jobs::import_sla_arch(), Slic3r::GUI::Plater::priv::Jobs::optimize_rotation(), and Slic3r::GUI::Plater::priv::Jobs::orient().
unbind_canvas_event_handlers()
void Slic3r::GUI::Plater::priv::unbind_canvas_event_handlers ()
{
    if (view3D != nullptr)
        view3D->get_canvas3d()->unbind_event_handlers();
    if (preview != nullptr)
        preview->get_canvas3d()->unbind_event_handlers();
    if (assemble_view != nullptr)
        assemble_view->get_canvas3d()->unbind_event_handlers();
}
undo()
void Slic3r::GUI::Plater::priv::undo ()
{
    const std::vector<UndoRedo::Snapshot> &snapshots = this->undo_redo_stack().snapshots();
    auto it_current = std::lower_bound(snapshots.begin(), snapshots.end(), UndoRedo::Snapshot(this->undo_redo_stack().active_snapshot_time()));
    // BBS: undo-redo until modify record
    while (--it_current != snapshots.begin() && !snapshot_modifies_project(*it_current));
    if (it_current == snapshots.begin()) return;
    if (get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView) {
        if (it_current->snapshot_data.snapshot_type != UndoRedo::SnapshotType::GizmoAction &&
            it_current->snapshot_data.snapshot_type != UndoRedo::SnapshotType::EnteringGizmo &&
            it_current->snapshot_data.snapshot_type != UndoRedo::SnapshotType::LeavingGizmoNoAction &&
            it_current->snapshot_data.snapshot_type != UndoRedo::SnapshotType::LeavingGizmoWithAction)
            return;
    }
    this->undo_redo_to(it_current);
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::UndoRedo::EnteringGizmo, Slic3r::GUI::Plater::get_current_canvas3D(), Slic3r::UndoRedo::GizmoAction, Slic3r::UndoRedo::LeavingGizmoNoAction, and Slic3r::UndoRedo::LeavingGizmoWithAction.
undo_redo_stack()
Slic3r::UndoRedo::Stack & Slic3r::GUI::Plater::priv::undo_redo_stack () inline
{ assert(m_undo_redo_stack_active != nullptr); return *m_undo_redo_stack_active; }
References m_undo_redo_stack_active.
undo_redo_stack_main()
Slic3r::UndoRedo::Stack & Slic3r::GUI::Plater::priv::undo_redo_stack_main () inline
{ return m_undo_redo_stack_main; }
References m_undo_redo_stack_main.
undo_redo_to() [1/2]
void Slic3r::GUI::Plater::priv::undo_redo_to (size_t time_to_load)
{
    const std::vector<UndoRedo::Snapshot> &snapshots = this->undo_redo_stack().snapshots();
    auto it_current = std::lower_bound(snapshots.begin(), snapshots.end(), UndoRedo::Snapshot(time_to_load));
    assert(it_current != snapshots.end());
    this->undo_redo_to(it_current);
}
undo_redo_to() [2/2]
void Slic3r::GUI::Plater::priv::undo_redo_to (std::vector< UndoRedo::Snapshot >::const_iterator it_snapshot) private
{
    // Make sure that no updating function calls take_snapshot until we are done.
    SuppressSnapshots snapshot_supressor(q);
    bool        temp_snapshot_was_taken   = this->undo_redo_stack().temp_snapshot_active();
    PrinterTechnology   new_printer_technology    = it_snapshot->snapshot_data.printer_technology;
    bool        printer_technology_changed  = this->printer_technology != new_printer_technology;
    if (printer_technology_changed) {
        //BBS do not support SLA
    }
    // Save the last active preset name of a particular printer technology.
    ((this->printer_technology == ptFFF) ? m_last_fff_printer_profile_name : m_last_sla_printer_profile_name) = wxGetApp().preset_bundle->printers.get_selected_preset_name();
    //FIXME updating the Wipe tower config values at the ModelWipeTower from the Print config.
    // This is a workaround until we refactor the Wipe Tower position / orientation to live solely inside the Model, not in the Print config.
    // BBS: add partplate logic
    if (this->printer_technology == ptFFF) {
        const DynamicPrintConfig& config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
        const DynamicPrintConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
        const ConfigOptionFloats* tower_x_opt = proj_cfg.option<ConfigOptionFloats>("wipe_tower_x");
        const ConfigOptionFloats* tower_y_opt = proj_cfg.option<ConfigOptionFloats>("wipe_tower_y");
        assert(tower_x_opt->values.size() == tower_y_opt->values.size());
        model.wipe_tower.positions.clear();
        model.wipe_tower.positions.resize(tower_x_opt->values.size());
        for (int plate_idx = 0; plate_idx < tower_x_opt->values.size(); plate_idx++) {
            ModelWipeTower& tower = model.wipe_tower;
            tower.positions[plate_idx] = Vec2d(tower_x_opt->get_at(plate_idx), tower_y_opt->get_at(plate_idx));
            tower.rotation = proj_cfg.opt_float("wipe_tower_rotation_angle");
        }
    }
    const int layer_range_idx = it_snapshot->snapshot_data.layer_range_idx;
    // Flags made of Snapshot::Flags enum values.
    unsigned int new_flags = it_snapshot->snapshot_data.flags;
    UndoRedo::SnapshotData top_snapshot_data;
    top_snapshot_data.printer_technology = this->printer_technology;
    if (this->view3D->is_layers_editing_enabled())
        top_snapshot_data.flags |= UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE;
    if (this->sidebar->obj_list()->is_selected(itSettings)) {
        top_snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR;
        top_snapshot_data.layer_range_idx = this->sidebar->obj_list()->get_selected_layers_range_idx();
    }
    else if (this->sidebar->obj_list()->is_selected(itLayer)) {
        top_snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR;
        top_snapshot_data.layer_range_idx = this->sidebar->obj_list()->get_selected_layers_range_idx();
    }
    else if (this->sidebar->obj_list()->is_selected(itLayerRoot))
        top_snapshot_data.flags |= UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR;
    bool       new_variable_layer_editing_active = (new_flags & UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE) != 0;
    bool         new_selected_settings_on_sidebar  = (new_flags & UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR) != 0;
    bool         new_selected_layer_on_sidebar     = (new_flags & UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR) != 0;
    bool         new_selected_layerroot_on_sidebar = (new_flags & UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR) != 0;
    if (this->view3D->get_canvas3d()->get_gizmos_manager().wants_reslice_supports_on_undo())
        top_snapshot_data.flags |= UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS;
    // Disable layer editing before the Undo / Redo jump.
    if (!new_variable_layer_editing_active && view3D->is_layers_editing_enabled())
        view3D->get_canvas3d()->force_main_toolbar_left_action(view3D->get_canvas3d()->get_main_toolbar_item_id("layersediting"));
    // Make a copy of the snapshot, undo/redo could invalidate the iterator
    const UndoRedo::Snapshot snapshot_copy = *it_snapshot;
    // Do the jump in time.
    if (it_snapshot->timestamp < this->undo_redo_stack().active_snapshot_time() ?
        this->undo_redo_stack().undo(model, get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView ? assemble_view->get_canvas3d()->get_selection() : this->view3D->get_canvas3d()->get_selection(), get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView ? assemble_view->get_canvas3d()->get_gizmos_manager() : this->view3D->get_canvas3d()->get_gizmos_manager(), this->partplate_list, top_snapshot_data, it_snapshot->timestamp) :
        this->undo_redo_stack().redo(model, get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView ? assemble_view->get_canvas3d()->get_gizmos_manager() : this->view3D->get_canvas3d()->get_gizmos_manager(), this->partplate_list, it_snapshot->timestamp)) {
        if (printer_technology_changed) {
            // Switch to the other printer technology. Switch to the last printer active for that particular technology.
            AppConfig *app_config = wxGetApp().app_config;
            app_config->set("presets", PRESET_PRINTER_NAME, (new_printer_technology == ptFFF) ? m_last_fff_printer_profile_name : m_last_sla_printer_profile_name);
            //FIXME Why are we reloading the whole preset bundle here? Please document. This is fishy and it is unnecessarily expensive.
            // Anyways, don't report any config value substitutions, they have been already reported to the user at application start up.
            wxGetApp().preset_bundle->load_presets(*app_config, ForwardCompatibilitySubstitutionRule::EnableSilent);
            // load_current_presets() calls Tab::load_current_preset() -> TabPrint::update() -> Object_list::update_and_show_object_settings_item(),
            // but the Object list still keeps pointer to the old Model. Avoid a crash by removing selection first.
            this->sidebar->obj_list()->unselect_objects();
            // Load the currently selected preset into the GUI, update the preset selection box.
            // This also switches the printer technology based on the printer technology of the active printer profile.
            wxGetApp().load_current_presets();
        }
        //FIXME updating the Print config from the Wipe tower config values at the ModelWipeTower.
        // This is a workaround until we refactor the Wipe Tower position / orientation to live solely inside the Model, not in the Print config.
        // BBS: add partplate logic
        if (this->printer_technology == ptFFF) {
            const DynamicPrintConfig& config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
            const DynamicPrintConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
            ConfigOptionFloats* tower_x_opt = const_cast<ConfigOptionFloats*>(proj_cfg.option<ConfigOptionFloats>("wipe_tower_x"));
            ConfigOptionFloats* tower_y_opt = const_cast<ConfigOptionFloats*>(proj_cfg.option<ConfigOptionFloats>("wipe_tower_y"));
            // BBS: don't support wipe tower rotation
            //double current_rotation = proj_cfg.opt_float("wipe_tower_rotation_angle");
            bool need_update = false;
            if (tower_x_opt->values.size() != model.wipe_tower.positions.size()) {
                tower_x_opt->clear();
                ConfigOptionFloat default_tower_x(40.f);
                tower_x_opt->resize(model.wipe_tower.positions.size(), &default_tower_x);
                need_update = true;
            }
            if (tower_y_opt->values.size() != model.wipe_tower.positions.size()) {
                tower_y_opt->clear();
                ConfigOptionFloat default_tower_y(200.f);
                tower_y_opt->resize(model.wipe_tower.positions.size(), &default_tower_y);
                need_update = true;
            }
            for (int plate_idx = 0; plate_idx < model.wipe_tower.positions.size(); plate_idx++) {
                if (Vec2d(tower_x_opt->get_at(plate_idx), tower_y_opt->get_at(plate_idx)) != model.wipe_tower.positions[plate_idx]) {
                    ConfigOptionFloat tower_x_new(model.wipe_tower.positions[plate_idx].x());
                    ConfigOptionFloat tower_y_new(model.wipe_tower.positions[plate_idx].y());
                    tower_x_opt->set_at(&tower_x_new, plate_idx, 0);
                    tower_y_opt->set_at(&tower_y_new, plate_idx, 0);
                    need_update = true;
                    break;
                }
            }
            if (need_update) {
                // update print to current plate (preview->m_process)
                this->partplate_list.update_slice_context_to_current_plate(this->background_process);
                this->preview->update_gcode_result(this->partplate_list.get_current_slice_result());
                this->update();
            }
        }
        // set selection mode for ObjectList on sidebar
        this->sidebar->obj_list()->set_selection_mode(new_selected_settings_on_sidebar  ? ObjectList::SELECTION_MODE::smSettings :
                                                      new_selected_layer_on_sidebar     ? ObjectList::SELECTION_MODE::smLayer :
                                                      new_selected_layerroot_on_sidebar ? ObjectList::SELECTION_MODE::smLayerRoot :
                                                                                          ObjectList::SELECTION_MODE::smUndef);
        if (new_selected_settings_on_sidebar || new_selected_layer_on_sidebar)
            this->sidebar->obj_list()->set_selected_layers_range_idx(layer_range_idx);
        this->update_after_undo_redo(snapshot_copy, temp_snapshot_was_taken);
        // Enable layer editing after the Undo / Redo jump.
        if (!view3D->is_layers_editing_enabled() && this->layers_height_allowed() && new_variable_layer_editing_active)
            view3D->get_canvas3d()->force_main_toolbar_left_action(view3D->get_canvas3d()->get_main_toolbar_item_id("layersediting"));
    }
    dirty_state.update_from_undo_redo_stack(m_undo_redo_stack_main.project_modified());
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::ConfigOptionVector< T >::clear(), Slic3r::GUI::Plater::config(), Slic3r::EnableSilent, Slic3r::UndoRedo::SnapshotData::flags, Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::Plater::get_current_canvas3D(), Slic3r::GUI::ObjectList::get_selected_layers_range_idx(), Slic3r::GUI::ObjectList::is_selected(), Slic3r::GUI::itLayer, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itSettings, Slic3r::UndoRedo::SnapshotData::layer_range_idx, Slic3r::GUI::Plater::model(), Slic3r::GUI::Plater::need_update(), Slic3r::GUI::Sidebar::obj_list(), Slic3r::DynamicConfig::opt_float(), Slic3r::ConfigBase::option(), Slic3r::ModelWipeTower::positions, PRESET_PRINTER_NAME, Slic3r::GUI::Plater::printer_technology(), Slic3r::UndoRedo::SnapshotData::printer_technology, Slic3r::ptFFF, Slic3r::UndoRedo::SnapshotData::RECALCULATE_SLA_SUPPORTS, Slic3r::ConfigOptionVector< T >::resize(), Slic3r::ModelWipeTower::rotation, Slic3r::UndoRedo::SnapshotData::SELECTED_LAYER_ON_SIDEBAR, Slic3r::UndoRedo::SnapshotData::SELECTED_LAYERROOT_ON_SIDEBAR, Slic3r::UndoRedo::SnapshotData::SELECTED_SETTINGS_ON_SIDEBAR, Slic3r::AppConfig::set(), Slic3r::ConfigOptionVector< T >::set_at(), Slic3r::GUI::ObjectList::set_selected_layers_range_idx(), Slic3r::GUI::ObjectList::set_selection_mode(), Slic3r::GUI::Plater::sidebar(), Slic3r::GUI::ObjectList::smLayer, Slic3r::GUI::ObjectList::smLayerRoot, Slic3r::GUI::ObjectList::smSettings, Slic3r::GUI::ObjectList::smUndef, Slic3r::GUI::ObjectList::unselect_objects(), Slic3r::GUI::Plater::update(), Slic3r::ConfigOptionVector< T >::values, Slic3r::UndoRedo::SnapshotData::VARIABLE_LAYER_EDITING_ACTIVE, and Slic3r::Model::wipe_tower.
up_to_date()
bool Slic3r::GUI::Plater::priv::up_to_date (bool saved, bool backup)
{
    size_t& last_time = backup ? m_backup_timestamp : m_saved_timestamp;
    if (saved) {
        last_time = undo_redo_stack_main().active_snapshot_time();
        if (!backup)
            undo_redo_stack_main().mark_current_as_saved();
        return true;
    }
    else {
        return !undo_redo_stack_main().has_real_change_from(last_time);
    }
}
References Slic3r::UndoRedo::Stack::active_snapshot_time(), Slic3r::UndoRedo::Stack::has_real_change_from(), Slic3r::UndoRedo::Stack::mark_current_as_saved(), and Slic3r::GUI::Plater::undo_redo_stack_main().
update()
void Slic3r::GUI::Plater::priv::update (unsigned int flags = 0)
{
    // the following line, when enabled, causes flickering on NVIDIA graphics cards
//    wxWindowUpdateLocker freeze_guard(q);
#ifdef SUPPORT_AUTOCENTER
    if (get_config("autocenter") == "true")
        model.center_instances_around_point(this->bed.build_volume().bed_center());
#endif
    unsigned int update_status = 0;
    const bool force_background_processing_restart = this->printer_technology == ptSLA || (flags & (unsigned int)UpdateParams::FORCE_BACKGROUND_PROCESSING_UPDATE);
    if (force_background_processing_restart)
        // Update the SLAPrint from the current Model, so that the reload_scene()
        // pulls the correct data.
        update_status = this->update_background_process(false, flags & (unsigned int)UpdateParams::POSTPONE_VALIDATION_ERROR_MESSAGE);
    //BBS TODO reload_scene
    this->view3D->reload_scene(false, flags & (unsigned int)UpdateParams::FORCE_FULL_SCREEN_REFRESH);
    this->preview->reload_print();
    //BBS assemble view
    this->assemble_view->reload_scene(false, flags);
    if (current_panel && q->is_preview_shown()) {
        q->force_update_all_plate_thumbnails();
        //update_fff_scene_only_shells(true);
    }
    if (force_background_processing_restart)
        this->restart_background_process(update_status);
    else
        this->schedule_background_process();
    // BBS
#if 0
    if (get_config("autocenter") == "true" && this->sidebar->obj_manipul()->IsShown())
        this->sidebar->obj_manipul()->UpdateAndShow(true);
#endif
}
References Slic3r::Model::center_instances_around_point(), int, Slic3r::GUI::Plater::model(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptSLA, Slic3r::GUI::Plater::schedule_background_process(), and Slic3r::GUI::Plater::sidebar().
update_after_undo_redo()
void Slic3r::GUI::Plater::priv::update_after_undo_redo (const UndoRedo::Snapshot & snapshot, bool temp_snapshot_was_taken = false) private
{
    get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView ? assemble_view->get_canvas3d()->get_selection().clear() : this->view3D->get_canvas3d()->get_selection().clear();
    // Update volumes from the deserializd model, always stop / update the background processing (for both the SLA and FFF technologies).
    this->update((unsigned int)UpdateParams::FORCE_BACKGROUND_PROCESSING_UPDATE | (unsigned int)UpdateParams::POSTPONE_VALIDATION_ERROR_MESSAGE);
    // Release old snapshots if the memory allocated is excessive. This may remove the top most snapshot if jumping to the very first snapshot.
    //if (temp_snapshot_was_taken)
    // Release the old snapshots always, as it may have happened, that some of the triangle meshes got deserialized from the snapshot, while some
    // triangle meshes may have gotten released from the scene or the background processing, therefore now being calculated into the Undo / Redo stack size.
        this->undo_redo_stack().release_least_recently_used();
    //YS_FIXME update obj_list from the deserialized model (maybe store ObjectIDs into the tree?) (no selections at this point of time)
        get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
            assemble_view->get_canvas3d()->get_selection().set_deserialized(GUI::Selection::EMode(this->undo_redo_stack().selection_deserialized().mode), this->undo_redo_stack().selection_deserialized().volumes_and_instances) :
            this->view3D->get_canvas3d()->get_selection().set_deserialized(GUI::Selection::EMode(this->undo_redo_stack().selection_deserialized().mode), this->undo_redo_stack().selection_deserialized().volumes_and_instances);
    get_current_canvas3D()->get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
        assemble_view->get_canvas3d()->get_gizmos_manager().update_after_undo_redo(snapshot) :
        this->view3D->get_canvas3d()->get_gizmos_manager().update_after_undo_redo(snapshot);
    wxGetApp().obj_list()->update_after_undo_redo();
    if (wxGetApp().get_mode() == comSimple && model_has_advanced_features(this->model)) {
        // If the user jumped to a snapshot that require user interface with advanced features, switch to the advanced mode without asking.
        // There is a little risk of surprising the user, as he already must have had the advanced or advanced mode active for such a snapshot to be taken.
        Slic3r::GUI::wxGetApp().save_mode(comAdvanced);
        view3D->set_as_dirty();
    }
    // this->update() above was called with POSTPONE_VALIDATION_ERROR_MESSAGE, so that if an error message was generated when updating the back end, it would not open immediately,
    // but it would be saved to be show later. Let's do it now. We do not want to display the message box earlier, because on Windows & OSX the message box takes over the message
    // queue pump, which in turn executes the rendering function before a full update after the Undo / Redo jump.
    this->show_delayed_error_message();
    //FIXME what about the state of the manipulators?
    //FIXME what about the focus? Cursor in the side panel?
    BOOST_LOG_TRIVIAL(info) << "Undo / Redo snapshot reloaded. Undo / Redo stack memory: " << Slic3r::format_memsize_MB(this->undo_redo_stack().memsize()) << log_memory_info();
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::comAdvanced, Slic3r::comSimple, Slic3r::format_memsize_MB(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::Plater::get_current_canvas3D(), Slic3r::log_memory_info(), Slic3r::model_has_advanced_features(), and Slic3r::GUI::Plater::update().
update_background_process()
unsigned int Slic3r::GUI::Plater::priv::update_background_process (bool force_validation = false, bool postpone_error_messages = false, bool switch_print = true)
{
    // bitmap of enum UpdateBackgroundProcessReturnState
    unsigned int return_state = 0;
    // If the update_background_process() was not called by the timer, kill the timer,
    // so the update_restart_background_process() will not be called again in vain.
    background_process_timer.Stop();
    // Update the "out of print bed" state of ModelInstances.
    update_print_volume_state();
    // Apply new config to the possibly running background task.
    bool               was_running = background_process.running();
    //BBS: add the switch print logic before Print::Apply
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": enter, force_validation=%1% postpone_error_messages=%2%, switch_print=%3%, was_running=%4%")%force_validation %postpone_error_messages %switch_print %was_running;
    if (switch_print)
    {
        // Update the "out of print bed" state of ModelInstances.
        this->update_print_volume_state();
        //BBS: update the current print to the current plate
        this->partplate_list.update_slice_context_to_current_plate(background_process);
        this->preview->update_gcode_result(partplate_list.get_current_slice_result());
    }
    Print::ApplyStatus invalidated = background_process.apply(this->model, wxGetApp().preset_bundle->full_config());
    if ((invalidated == Print::APPLY_STATUS_CHANGED) || (invalidated == Print::APPLY_STATUS_INVALIDATED))
        // BBS: add only gcode mode
        q->set_only_gcode(false);
    //BBS: add slicing related logs
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": background process apply result=%1%")%invalidated;
    if (background_process.empty())
        view3D->get_canvas3d()->reset_sequential_print_clearance();
    if (invalidated == Print::APPLY_STATUS_INVALIDATED) {
        //BBS: update current plater's slicer result to invalid
        this->background_process.get_current_plate()->update_slice_result_valid_state(false);
        //no need, should be done in background_process.apply
        //this->background_process.get_current_gcode_result()->reset();
        // Reset preview canvases. If the print has been invalidated, the preview canvases will be cleared.
        // Otherwise they will be just refreshed.
        if (preview != nullptr) {
            // If the preview is not visible, the following line just invalidates the preview,
            // but the G-code paths or SLA preview are calculated first once the preview is made visible.
            reset_gcode_toolpaths();
            preview->reload_print();
        }
        // In FDM mode, we need to reload the 3D scene because of the wipe tower preview box.
        // In SLA mode, we need to reload the 3D scene every time to show the support structures.
        if (printer_technology == ptSLA || (printer_technology == ptFFF && config->opt_bool("enable_prime_tower")))
            return_state |= UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE;
        notification_manager->set_slicing_progress_hidden();
    }
    if ((invalidated != Print::APPLY_STATUS_UNCHANGED || force_validation) && ! background_process.empty()) {
        // The delayed error message is no more valid.
        delayed_error_message.clear();
        // The state of the Print changed, and it is non-zero. Let's validate it and give the user feedback on errors.
        //BBS: add is_warning logic
        StringObjectException warning;
        //BBS: refine seq-print logic
        Polygons polygons;
        std::vector<std::pair<Polygon, float>> height_polygons;
        StringObjectException err = background_process.validate(&warning, &polygons, &height_polygons);
        // update string by type
        q->post_process_string_object_exception(err);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": validate err=%1%, warning=%2%")%err.string%warning.string;
        if (err.string.empty()) {
            this->partplate_list.get_curr_plate()->update_apply_result_invalid(false);
            notification_manager->set_all_slicing_errors_gray(true);
            notification_manager->close_notification_of_type(NotificationType::ValidateError);
            if (invalidated != Print::APPLY_STATUS_UNCHANGED && background_processing_enabled())
                return_state |= UPDATE_BACKGROUND_PROCESS_RESTART;
            // Pass a warning from validation and either show a notification,
            // or hide the old one.
            process_validation_warning(warning);
            if (printer_technology == ptFFF) {
                view3D->get_canvas3d()->reset_sequential_print_clearance();
                view3D->get_canvas3d()->set_as_dirty();
                view3D->get_canvas3d()->request_extra_frame();
            }
        }
        else {
            this->partplate_list.get_curr_plate()->update_apply_result_invalid(true);
            // The print is not valid.
            // Show error as notification.
            notification_manager->push_validate_error_notification(err);
            //also update the warnings
            process_validation_warning(warning);
            return_state |= UPDATE_BACKGROUND_PROCESS_INVALID;
            if (printer_technology == ptFFF) {
                const Print* print = background_process.fff_print();
                //Polygons polygons;
                //if (print->config().print_sequence == PrintSequence::ByObject)
                //    Print::sequential_print_clearance_valid(*print, &polygons);
                view3D->get_canvas3d()->set_sequential_print_clearance_visible(true);
                view3D->get_canvas3d()->set_sequential_print_clearance_render_fill(true);
                view3D->get_canvas3d()->set_sequential_print_clearance_polygons(polygons, height_polygons);
            }
        }
    }
    else if (! this->delayed_error_message.empty()) {
        // Reusing the old state.
        return_state |= UPDATE_BACKGROUND_PROCESS_INVALID;
    }
    //actualizate warnings
    if (invalidated != Print::APPLY_STATUS_UNCHANGED || background_process.empty()) {
        if (background_process.empty())
            process_validation_warning({});
        actualize_slicing_warnings(*this->background_process.current_print());
        actualize_object_warnings(*this->background_process.current_print());
        show_warning_dialog = false;
        process_completed_with_error = -1;
    }
    if (invalidated != Print::APPLY_STATUS_UNCHANGED && was_running && ! this->background_process.running() &&
        (return_state & UPDATE_BACKGROUND_PROCESS_RESTART) == 0) {
            // The background processing was killed and it will not be restarted.
            // Post the "canceled" callback message, so that it will be processed after any possible pending status bar update messages.
            SlicingProcessCompletedEvent evt(EVT_PROCESS_COMPLETED, 0,
                SlicingProcessCompletedEvent::Cancelled, nullptr);
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%, post an EVT_PROCESS_COMPLETED to main, status %2%")%__LINE__ %evt.status();
            wxQueueEvent(q, evt.Clone());
        }
    if ((return_state & UPDATE_BACKGROUND_PROCESS_INVALID) != 0)
    {
        // Validation of the background data failed.
        //BBS: add slice&&print status update logic
        this->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, false);
        process_completed_with_error = partplate_list.get_curr_plate_index();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: set to process_completed_with_error, return_state=%2%")%__LINE__%return_state;
    }
    else
    {
        // Background data is valid.
        if ((return_state & UPDATE_BACKGROUND_PROCESS_RESTART) != 0 ||
            (return_state & UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE) != 0 )
            notification_manager->set_slicing_progress_hidden();
        //BBS: add slice&&print status update logic
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: background data valid, return_state=%2%")%__LINE__%return_state;
        PartPlate* cur_plate = background_process.get_current_plate();
        if (background_process.finished() && cur_plate && cur_plate->is_slice_result_valid())
        {
            //ready_to_slice = false;
            this->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, false);
        }
        else if (!background_process.empty() &&
                 !background_process.running()) /* Do not update buttons if background process is running
                                                 * This condition is important for SLA mode especially,
                                                 * when this function is called several times during calculations
                                                 * */
        {
            if (cur_plate->can_slice()) {
                //ready_to_slice = true;
                this->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, true);
                process_completed_with_error = -1;
            }
            else {
                //ready_to_slice = false;
                this->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, false);
                process_completed_with_error = partplate_list.get_curr_plate_index();
            }
        }
#if 0
        //sidebar->set_btn_label(ActionButtonType::abExport, _(label_btn_export));
        //sidebar->set_btn_label(ActionButtonType::abSendGCode, _(label_btn_send));
        //const wxString slice_string = background_process.running() && wxGetApp().get_mode() == comSimple ?
        //                              _L("Slicing") + dots : _L("Slice now");
        //sidebar->set_btn_label(ActionButtonType::abReslice, slice_string);
        //if (background_process.finished())
        //    show_action_buttons(false);
        //else if (!background_process.empty() &&
        //         !background_process.running()) /* Do not update buttons if background process is running
        //                                         * This condition is important for SLA mode especially,
        //                                         * when this function is called several times during calculations
        //                                         * */
        //    show_action_buttons(true);
#endif
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: exit, return_state=%2%")%__LINE__%return_state;
    return return_state;
}
References Slic3r::PrintBase::APPLY_STATUS_CHANGED, Slic3r::PrintBase::APPLY_STATUS_INVALIDATED, Slic3r::PrintBase::APPLY_STATUS_UNCHANGED, Slic3r::GUI::PartPlate::can_slice(), Slic3r::SlicingProcessCompletedEvent::Cancelled, Slic3r::SlicingProcessCompletedEvent::Clone(), Slic3r::GUI::Plater::config(), Slic3r::GUI::MainFrame::eEventSliceUpdate, Slic3r::GUI::PartPlate::is_slice_result_valid(), Slic3r::DynamicConfig::opt_bool(), Slic3r::GUI::Plater::printer_technology(), Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::GUI::Plater::reset_gcode_toolpaths(), Slic3r::SlicingProcessCompletedEvent::status(), Slic3r::StringObjectException::string, and Slic3r::GUI::ValidateError.
update_fff_scene()
void Slic3r::GUI::Plater::priv::update_fff_scene () private
{
    if (this->preview != nullptr)
        this->preview->reload_print();
    // In case this was MM print, wipe tower bounding box on 3D tab might need redrawing with exact depth:
    view3D->reload_scene(true);
    //BBS: add assemble view related logic
    assemble_view->reload_scene(true);
}
update_fff_scene_only_shells()
void Slic3r::GUI::Plater::priv::update_fff_scene_only_shells (bool only_shells = true)
{
    if (this->preview != nullptr)
    {
        const Print* current_print = this->background_process.fff_print();
        if (current_print)
        {
            //this->preview->reset_shells();
            this->preview->load_shells(*current_print);
        }
    }
    if (!only_shells) {
        view3D->reload_scene(true);
        assemble_view->reload_scene(true);
    }
}
update_plugin_when_launch()
void Slic3r::GUI::Plater::priv::update_plugin_when_launch (wxCommandEvent & event) private
{
    std::string data_dir_str = data_dir();
    boost::filesystem::path data_dir_path(data_dir_str);
    auto cache_folder = data_dir_path / "ota";
    std::string changelog_file = cache_folder.string() + "/network_plugins.json";
    UpdatePluginDialog dlg(wxGetApp().mainframe);
    dlg.update_info(changelog_file);
    auto result = dlg.ShowModal();
    auto app_config = wxGetApp().app_config;
    if (!app_config) return;
    if (result == wxID_OK) {
        app_config->set("update_network_plugin", "true");
    }
    else if (result == wxID_NO) {
        app_config->set("update_network_plugin", "false");
    }
}
References Slic3r::data_dir(), Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::GUI::UpdatePluginDialog::update_info().
update_preview_bottom_toolbar()
void Slic3r::GUI::Plater::priv::update_preview_bottom_toolbar ()
{
    ;
}
update_print_volume_state()
void Slic3r::GUI::Plater::priv::update_print_volume_state ()
{
    //BBS: use the plate's bounding box instead of the bed's
    PartPlate* pp = partplate_list.get_curr_plate();
    BuildVolume build_volume(pp->get_shape(), this->bed.build_volume().printable_height());
    this->model.update_print_volume_state(build_volume);
}
References Slic3r::GUI::Plater::build_volume(), and Slic3r::GUI::PartPlate::get_shape().
update_project_dirty_from_presets()
void Slic3r::GUI::Plater::priv::update_project_dirty_from_presets () inline
    {
        // BBS: backup
        Slic3r::put_other_changes();
        dirty_state.update_from_presets();
    }
References dirty_state, Slic3r::put_other_changes(), and Slic3r::GUI::ProjectDirtyStateManager::update_from_presets().
update_publish_dialog_status()
void Slic3r::GUI::Plater::priv::update_publish_dialog_status (wxString & msg, int percent = -1)
{
    if (m_publish_dlg)
        m_publish_dlg->UpdateStatus(msg, percent);
}
update_restart_background_process()
unsigned int Slic3r::GUI::Plater::priv::update_restart_background_process (bool force_scene_update, bool force_preview_update)
{
    bool switch_print = true;
    //BBS: judge whether can switch print or not
    if ((partplate_list.get_plate_count() > 1) && !this->background_process.can_switch_print())
    {
        //can not switch print currently
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": plate count %1%, can not switch") % partplate_list.get_plate_count();
        switch_print = false;
    }
    // bitmask of UpdateBackgroundProcessReturnState
    unsigned int state = this->update_background_process(false, false, switch_print);
    if (force_update_scene || (state & UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE) != 0)
        view3D->reload_scene(false);
    if (force_update_preview)
        this->preview->reload_print();
    this->restart_background_process(state);
    return state;
}
update_sla_scene()
void Slic3r::GUI::Plater::priv::update_sla_scene () private
{
    // Update the SLAPrint from the current Model, so that the reload_scene()
    // pulls the correct data.
    delayed_scene_refresh = false;
    this->update_restart_background_process(true, true);
}
update_ui_from_settings()
void Slic3r::GUI::Plater::priv::update_ui_from_settings ()
{
    apply_free_camera_correction();
    view3D->get_canvas3d()->update_ui_from_settings();
    preview->get_canvas3d()->update_ui_from_settings();
    sidebar->update_ui_from_settings();
}
References Slic3r::GUI::Plater::sidebar(), and Slic3r::GUI::Sidebar::update_ui_from_settings().
warnings_dialog()
bool Slic3r::GUI::Plater::priv::warnings_dialog ()
{
    if (current_warnings.empty())
        return true;
    std::string text = _u8L("There are warnings after slicing models:") + "\n";
    for (auto const& it : current_warnings) {
        size_t next_n = it.first.message.find_first_of('\n', 0);
        text += "\n";
        if (next_n != std::string::npos)
            text += it.first.message.substr(0, next_n);
        else
            text += it.first.message;
    }
    //text += "\n\nDo you still wish to export?";
    MessageDialog msg_window(this->q, from_u8(text), _L("warnings"), wxOK);
    const auto    res = msg_window.ShowModal();
    return res == wxID_OK;
}
References _L, _u8L, Slic3r::GUI::from_u8(), and Slic3r::GUI::DPIAware< P >::ShowModal().
Member Data Documentation
assemble_view
AssembleView* Slic3r::GUI::Plater::priv::assemble_view { nullptr }
Referenced by is_assemble_view_show().
background_process
BackgroundSlicingProcess Slic3r::GUI::Plater::priv::background_process
Referenced by Slic3r::GUI::Plater::priv::Jobs::before_start().
background_process_timer
wxTimer Slic3r::GUI::Plater::priv::background_process_timer
bed
Bed3D Slic3r::GUI::Plater::priv::bed
camera
Camera Slic3r::GUI::Plater::priv::camera
collapse_toolbar
GLToolbar Slic3r::GUI::Plater::priv::collapse_toolbar
config
Slic3r::DynamicPrintConfig* Slic3r::GUI::Plater::priv::config
current_panel
wxPanel* Slic3r::GUI::Plater::priv::current_panel { nullptr }
Referenced by are_view3D_labels_shown(), is_assemble_view_show(), is_preview_shown(), is_view3D_layers_editing_enabled(), is_view3D_overhang_shown(), is_view3D_shown(), show_view3D_labels(), and show_view3D_overhang().
current_warnings
std::vector<std::pair<Slic3r::PrintStateBase::Warning, size_t> > Slic3r::GUI::Plater::priv::current_warnings private
delayed_error_message
std::string Slic3r::GUI::Plater::priv::delayed_error_message
delayed_scene_refresh
bool Slic3r::GUI::Plater::priv::delayed_scene_refresh
dirty_state
ProjectDirtyStateManager Slic3r::GUI::Plater::priv::dirty_state
Referenced by is_presets_dirty(), is_project_dirty(), reset_project_dirty_after_save(), reset_project_dirty_initial_presets(), save_project_if_dirty(), set_plater_dirty(), and update_project_dirty_from_presets().
exporting_status
ExportingStatus Slic3r::GUI::Plater::priv::exporting_status { NOT_EXPORTING }
fff_print
Slic3r::Print Slic3r::GUI::Plater::priv::fff_print
first_enter_assemble
bool Slic3r::GUI::Plater::priv::first_enter_assemble { true }
gcode_result
Slic3r::GCodeProcessorResult Slic3r::GUI::Plater::priv::gcode_result
label_btn_export
std::string Slic3r::GUI::Plater::priv::label_btn_export
label_btn_send
std::string Slic3r::GUI::Plater::priv::label_btn_send
last_output_dir_path
std::string Slic3r::GUI::Plater::priv::last_output_dir_path
last_output_path
std::string Slic3r::GUI::Plater::priv::last_output_path
m_backup_timestamp
size_t Slic3r::GUI::Plater::priv::m_backup_timestamp = 0 private
m_cur_slice_plate
int Slic3r::GUI::Plater::priv::m_cur_slice_plate
m_ignore_event
bool Slic3r::GUI::Plater::priv::m_ignore_event {false}
m_is_dark
bool Slic3r::GUI::Plater::priv::m_is_dark = false
m_is_publishing
bool Slic3r::GUI::Plater::priv::m_is_publishing {false}
m_is_RightClickInLeftUI
int Slic3r::GUI::Plater::priv::m_is_RightClickInLeftUI {-1}
m_is_slicing
bool Slic3r::GUI::Plater::priv::m_is_slicing {false}
m_job_prepare_state
int Slic3r::GUI::Plater::priv::m_job_prepare_state
m_last_fff_printer_profile_name
std::string Slic3r::GUI::Plater::priv::m_last_fff_printer_profile_name private
m_last_sla_printer_profile_name
std::string Slic3r::GUI::Plater::priv::m_last_sla_printer_profile_name private
m_need_update
bool Slic3r::GUI::Plater::priv::m_need_update {false}
Referenced by need_update(), and set_need_update().
m_prevent_snapshots
int Slic3r::GUI::Plater::priv::m_prevent_snapshots = 0 private
Referenced by allow_snapshots(), inside_snapshot_capture(), and suppress_snapshots().
m_print_job_data
PrintPrepareData Slic3r::GUI::Plater::priv::m_print_job_data
m_project_folder
boost::filesystem::path Slic3r::GUI::Plater::priv::m_project_folder private
m_project_name
wxString Slic3r::GUI::Plater::priv::m_project_name private
m_publish_dlg
PublishDialog* Slic3r::GUI::Plater::priv::m_publish_dlg = nullptr
m_saved_timestamp
size_t Slic3r::GUI::Plater::priv::m_saved_timestamp = 0 private
m_select_machine_dlg
SelectMachineDialog* Slic3r::GUI::Plater::priv::m_select_machine_dlg = nullptr
Referenced by hide_select_machine_dlg().
m_send_to_sdcard_dlg
SendToPrinterDialog* Slic3r::GUI::Plater::priv::m_send_to_sdcard_dlg = nullptr
Referenced by hide_send_to_printer_dlg().
m_single
Plater::SingleSnapshot* Slic3r::GUI::Plater::priv::m_single = nullptr private
Referenced by single_snapshots_enter(), and single_snapshots_leave().
m_slice_all
bool Slic3r::GUI::Plater::priv::m_slice_all {false}
m_slice_all_only_has_gcode
bool Slic3r::GUI::Plater::priv::m_slice_all_only_has_gcode { false }
m_ui_jobs
Slic3r::GUI::Plater::priv::Jobs Slic3r::GUI::Plater::priv::m_ui_jobs
m_undo_redo_stack_active
Slic3r::UndoRedo::Stack* Slic3r::GUI::Plater::priv::m_undo_redo_stack_active = &m_undo_redo_stack_main private
Referenced by undo_redo_stack().
m_undo_redo_stack_gizmos
Slic3r::UndoRedo::Stack Slic3r::GUI::Plater::priv::m_undo_redo_stack_gizmos private
m_undo_redo_stack_main
Slic3r::UndoRedo::Stack Slic3r::GUI::Plater::priv::m_undo_redo_stack_main private
Referenced by reset_project_dirty_after_save(), and undo_redo_stack_main().
main_frame
MainFrame* Slic3r::GUI::Plater::priv::main_frame
menus
MenuFactory Slic3r::GUI::Plater::priv::menus
model
Slic3r::Model Slic3r::GUI::Plater::priv::model
mouse3d_controller
Mouse3DController Slic3r::GUI::Plater::priv::mouse3d_controller
notification_manager
std::unique_ptr<NotificationManager> Slic3r::GUI::Plater::priv::notification_manager
panel_sizer
wxSizer* Slic3r::GUI::Plater::priv::panel_sizer { nullptr }
panels
std::vector<wxPanel*> Slic3r::GUI::Plater::priv::panels
partplate_list
PartPlateList Slic3r::GUI::Plater::priv::partplate_list
pattern_3mf
const std::regex Slic3r::GUI::Plater::priv::pattern_3mf static
pattern_any_amf
const std::regex Slic3r::GUI::Plater::priv::pattern_any_amf static
pattern_bundle
const std::regex Slic3r::GUI::Plater::priv::pattern_bundle static
pattern_prusa
const std::regex Slic3r::GUI::Plater::priv::pattern_prusa static
pattern_zip_amf
const std::regex Slic3r::GUI::Plater::priv::pattern_zip_amf static
preview
Preview* Slic3r::GUI::Plater::priv::preview
Referenced by is_preview_loaded(), and is_preview_shown().
printer_technology
PrinterTechnology Slic3r::GUI::Plater::priv::printer_technology = ptFFF
process_completed_with_error
int Slic3r::GUI::Plater::priv::process_completed_with_error { -1 }
project
BBLProject Slic3r::GUI::Plater::priv::project
q
Plater* Slic3r::GUI::Plater::priv::q
Referenced by Slic3r::GUI::Plater::priv::Jobs::Jobs().
show_render_statistic_dialog
bool Slic3r::GUI::Plater::priv::show_render_statistic_dialog { false }
show_warning_dialog
bool Slic3r::GUI::Plater::priv::show_warning_dialog { false } private
show_wireframe
bool Slic3r::GUI::Plater::priv::show_wireframe { false }
sidebar
Sidebar* Slic3r::GUI::Plater::priv::sidebar
Referenced by is_sidebar_collapsed().
sla_print
Slic3r::SLAPrint Slic3r::GUI::Plater::priv::sla_print
suppressed_backround_processing_update
bool Slic3r::GUI::Plater::priv::suppressed_backround_processing_update { false }
view3D
View3D* Slic3r::GUI::Plater::priv::view3D
Referenced by are_view3D_labels_shown(), is_view3D_layers_editing_enabled(), is_view3D_overhang_shown(), is_view3D_shown(), show_view3D_labels(), and show_view3D_overhang().
wireframe_enabled
bool Slic3r::GUI::Plater::priv::wireframe_enabled { true }
The documentation for this struct was generated from the following file:
src/slic3r/GUI/Plater.cpp