OrcaSlicer: Slic3r::GUI::CalibrationDialog Class Reference
Slic3r::GUI::CalibrationDialog Class Reference
#include <src/slic3r/GUI/Calibration.hpp>
Public Member Functions
CalibrationDialog (Plater *plater=nullptr)
~CalibrationDialog ()
void on_dpi_changed (const wxRect &suggested_rect) override
void update_cali (MachineObject *obj)
bool is_stage_list_info_changed (MachineObject *obj)
void on_start_calibration (wxMouseEvent &event)
void update_machine_obj (MachineObject *obj)
bool Show (bool show) override
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Public Attributes
StepIndicator * m_calibration_flow
Button * m_calibration_btn
MachineObject * m_obj
std::vector< int > last_stage_list_info
int m_state {0}
Protected Member Functions
virtual void on_sys_color_changed ()
Private Member Functions
wxWindow * create_check_option (wxString title, wxWindow *parent, wxString tooltip, std::string param)
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
std::map< std::string, ::CheckBox * > m_checkbox_list
wxWindow * select_xcam_cali { nullptr }
wxWindow * select_bed_leveling { nullptr }
wxWindow * select_vibration { nullptr }
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
CalibrationDialog()
Slic3r::GUI::CalibrationDialog::CalibrationDialog (Plater * plater = nullptr)
    : DPIDialog(static_cast<wxWindow *>(wxGetApp().mainframe), wxID_ANY, _L("Calibration"), wxDefaultPosition, wxDefaultSize, wxCAPTION | wxCLOSE_BOX)
{
    this->SetDoubleBuffered(true);
    std::string icon_path = (boost::format("%1%/images/OrcaSlicerTitle.ico") % resources_dir()).str();
    SetIcon(wxIcon(encode_path(icon_path.c_str()), wxBITMAP_TYPE_ICO));
    SetBackgroundColour(*wxWHITE);
    wxBoxSizer *m_sizer_main = new wxBoxSizer(wxVERTICAL);
    auto        m_line_top   = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    m_line_top->SetBackgroundColour(wxColour(166, 169, 170));
    m_sizer_main->Add(m_line_top, 0, wxEXPAND, 0);
    wxBoxSizer *sizer_body = new wxBoxSizer(wxHORIZONTAL);
    auto        body_panel = new wxPanel(this, wxID_ANY);
    body_panel->SetBackgroundColour(*wxWHITE);
    auto cali_left_panel = new StaticBox(body_panel, wxID_ANY, wxDefaultPosition, wxSize(FromDIP(303), -1));
    cali_left_panel->SetBackgroundColor(BG_COLOR);
    cali_left_panel->SetBorderColor(BG_COLOR);
    wxBoxSizer *cali_left_sizer = new wxBoxSizer(wxVERTICAL);
    cali_left_sizer->Add(0, 0, 0, wxTOP, FromDIP(25));
    // calibration step selection
    auto cali_step_select_title = new wxStaticText(cali_left_panel, wxID_ANY, _L("Calibration step selection"), wxDefaultPosition, wxDefaultSize, 0);
    cali_step_select_title->SetFont(::Label::Head_14);
    cali_step_select_title->Wrap(-1);
    cali_step_select_title->SetForegroundColour(FG_COLOR);
    cali_step_select_title->SetBackgroundColour(BG_COLOR);
    cali_left_sizer->Add(cali_step_select_title, 0, wxLEFT, FromDIP(15));
    select_xcam_cali    = create_check_option(_L("Micro lidar calibration"), cali_left_panel, _L("Micro lidar calibration"),            "xcam_cali");
    select_bed_leveling = create_check_option(_L("Bed leveling"),            cali_left_panel, _L("Bed leveling"),                       "bed_leveling");
    select_vibration    = create_check_option(_L("Resonance frequency identification"), cali_left_panel, _L("Resonance frequency identification"), "vibration");
    m_checkbox_list["xcam_cali"]->SetValue(true);
    m_checkbox_list["bed_leveling"]->SetValue(true);
    m_checkbox_list["vibration"]->SetValue(true);
    cali_left_sizer->Add(0, FromDIP(18), 0, wxEXPAND, 0);
    cali_left_sizer->Add(select_xcam_cali, 0, wxLEFT, FromDIP(15));
    cali_left_sizer->Add(select_bed_leveling, 0, wxLEFT, FromDIP(15));
    cali_left_sizer->Add(select_vibration, 0, wxLEFT, FromDIP(15));
    cali_left_sizer->Add(0, FromDIP(30), 0, wxEXPAND, 0);
    auto cali_left_text_top = new wxStaticText(cali_left_panel, wxID_ANY, _L("Calibration program"), wxDefaultPosition, wxDefaultSize, 0);
    cali_left_text_top->SetFont(::Label::Head_14);
    cali_left_text_top->Wrap(-1);
    cali_left_text_top->SetForegroundColour(FG_COLOR);
    cali_left_text_top->SetBackgroundColour(BG_COLOR);
    cali_left_sizer->Add(cali_left_text_top, 0, wxLEFT, FromDIP(15));
    cali_left_sizer->Add(0, 0, 0, wxTOP, FromDIP(5));
    auto cali_left_text_body =
        new Label(cali_left_panel, _L("The calibration program detects the status of your device automatically to minimize deviation.\nIt keeps the device performing optimally."));
    cali_left_text_body->Wrap(FromDIP(260));
    cali_left_text_body->SetForegroundColour(wxColour(0x6B, 0x6B, 0x6B));
    cali_left_text_body->SetBackgroundColour(BG_COLOR);
    cali_left_text_body->SetFont(::Label::Body_13);
    cali_left_sizer->Add(cali_left_text_body, 0, wxLEFT, FromDIP(15));
    cali_left_sizer->Add(0, 0, 0, wxTOP, FromDIP(20));
   /* auto cali_left_text_top_prepar = new wxStaticText(cali_left_panel, wxID_ANY, _L("Preparation before calibration"), wxDefaultPosition, wxDefaultSize, 0);
     cali_left_text_top_prepar->SetFont(::Label::Head_14);
     cali_left_text_top_prepar->SetForegroundColour(wxColour(0x32, 0x3A, 0x3D));
     cali_left_text_top_prepar->SetBackgroundColour(wxColour(0xF8, 0xF8, 0xF8));
     cali_left_text_top_prepar->Wrap(-1);
     cali_left_sizer->Add(cali_left_text_top_prepar, 0, wxLEFT, FromDIP(15));
     cali_left_sizer->Add(0, 0, 0, wxTOP, FromDIP(5));
     auto cali_left_text_body_prepar =
         new wxStaticText(cali_left_panel, wxID_ANY,
                          _L("Before calibration, please make sure a filament is loaded and its nozzle temperature and bed temperature is set in Feeding lab."),
     wxDefaultPosition, wxSize(FromDIP(260), -1), 0); cali_left_text_body_prepar->Wrap(FromDIP(260)); cali_left_text_body_prepar->SetFont(::Label::Body_13);
     cali_left_text_body_prepar->SetForegroundColour(wxColour(0x6B, 0x6B, 0x6B));
     cali_left_text_body_prepar->SetBackgroundColour(wxColour(0xF8, 0xF8, 0xF8));
     cali_left_sizer->Add(cali_left_text_body_prepar, 0, wxLEFT, FromDIP(15));*/
    cali_left_panel->SetSizer(cali_left_sizer);
    cali_left_panel->Layout();
    sizer_body->Add(cali_left_panel, 0, wxALIGN_CENTER, 0);
    sizer_body->Add(0, 0, 0, wxLEFT, FromDIP(8));
    wxBoxSizer *cali_right_sizer_h = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *cali_right_sizer_v = new wxBoxSizer(wxVERTICAL);
    auto cali_right_panel = new StaticBox(body_panel, wxID_ANY, wxDefaultPosition, wxSize(FromDIP(182), FromDIP(160)));
    cali_right_panel->SetBackgroundColor(BG_COLOR);
    cali_right_panel->SetBorderColor(BG_COLOR);
    auto cali_text_right_top = new wxStaticText(cali_right_panel, wxID_ANY, _L("Calibration Flow"), wxDefaultPosition, wxDefaultSize, 0);
    cali_text_right_top->Wrap(-1);
    cali_text_right_top->SetFont(::Label::Head_14);
    cali_text_right_top->SetForegroundColour(wxColour(0x00, 0xAE, 0x42));
    cali_text_right_top->SetBackgroundColour(BG_COLOR);
    auto staticline = new ::StaticLine(cali_right_panel);
    staticline->SetLineColour(wxColour(0x00, 0xAE, 0x42));
    auto calibration_panel = new wxPanel(cali_right_panel);
    calibration_panel->SetBackgroundColour(BG_COLOR);
    auto calibration_sizer = new wxBoxSizer(wxVERTICAL);
    calibration_panel->SetMinSize(wxSize(FromDIP(170), FromDIP(160)));
    calibration_panel->SetSize(wxSize(FromDIP(170), FromDIP(160)));
    m_calibration_flow = new StepIndicator(calibration_panel, wxID_ANY);
    StateColor bg_color(std::pair<wxColour, int>(BG_COLOR, StateColor::Normal));
    m_calibration_flow->SetBackgroundColor(bg_color);
    m_calibration_flow->SetFont(Label::Body_12);
    m_calibration_flow->SetMinSize(wxSize(FromDIP(170), FromDIP(160)));
    m_calibration_flow->SetSize(wxSize(FromDIP(170), FromDIP(160)));
    calibration_panel->SetSizer(calibration_sizer);
    calibration_panel->Layout();
    calibration_sizer->Add(m_calibration_flow, 0, wxEXPAND, 0);
    StateColor btn_bg_green(std::pair<wxColour, int>(AMS_CONTROL_DISABLE_COLOUR, StateColor::Disabled), std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed),
                            std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered), std::pair<wxColour, int>(AMS_CONTROL_BRAND_COLOUR, StateColor::Normal));
    StateColor btn_bd_green(std::pair<wxColour, int>(AMS_CONTROL_WHITE_COLOUR, StateColor::Disabled), std::pair<wxColour, int>(AMS_CONTROL_BRAND_COLOUR, StateColor::Enabled));
    m_calibration_btn = new Button(cali_right_panel, _L("Start Calibration"));
    m_calibration_btn->SetBackgroundColor(btn_bg_green);
    m_calibration_btn->SetBorderColor(btn_bd_green);
    m_calibration_btn->SetTextColor(wxColour("#FFFFFE"));
    m_calibration_btn->SetSize(wxSize(FromDIP(128), FromDIP(26)));
    m_calibration_btn->SetMinSize(wxSize(FromDIP(128), FromDIP(26)));
    cali_right_sizer_v->Add(cali_text_right_top, 0, wxALIGN_CENTER, 0);
    cali_right_sizer_v->Add(0, 0, 0, wxTOP, FromDIP(7));
    cali_right_sizer_v->Add(staticline, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(10));
    cali_right_sizer_v->Add(0, 0, 0, wxTOP, FromDIP(3));
    cali_right_sizer_v->Add(calibration_panel, 0, wxALIGN_CENTER_HORIZONTAL | wxLEFT | wxRIGHT, FromDIP(6));
    cali_right_sizer_v->Add(0, 0, 1, wxEXPAND, 5);
    cali_right_sizer_v->Add(m_calibration_btn, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    cali_right_sizer_h->Add(cali_right_sizer_v, 0, wxALIGN_CENTER, 0);
    cali_right_panel->SetSizer(cali_right_sizer_h);
    cali_right_panel->Layout();
    sizer_body->Add(cali_right_panel, 0, wxEXPAND, 0);
    body_panel->SetSizer(sizer_body);
    body_panel->Layout();
    m_sizer_main->Add(body_panel, 0, wxEXPAND | wxALL, FromDIP(25));
    SetSizer(m_sizer_main);
    Layout();
    Fit();
    m_calibration_btn->Bind(wxEVT_LEFT_DOWN, &CalibrationDialog::on_start_calibration, this);
}
References _L, AMS_CONTROL_BRAND_COLOUR, AMS_CONTROL_DISABLE_COLOUR, AMS_CONTROL_WHITE_COLOUR, BG_COLOR, Label::Body_12, Label::Body_13, create_check_option(), StateColor::Disabled, StateColor::Enabled, Slic3r::encode_path(), FG_COLOR, Label::Head_14, StateColor::Hovered, m_calibration_btn, m_calibration_flow, m_checkbox_list, StateColor::Normal, on_start_calibration(), StateColor::Pressed, Slic3r::resources_dir(), select_bed_leveling, select_vibration, select_xcam_cali, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), Button::SetMinSize(), Button::SetTextColor(), and wxStaticText.
~CalibrationDialog()
Slic3r::GUI::CalibrationDialog::~CalibrationDialog ()
{}
Member Function Documentation
create_check_option()
wxWindow * Slic3r::GUI::CalibrationDialog::create_check_option (wxString title, wxWindow * parent, wxString tooltip, std::string param) private
{
    auto checkbox = new wxWindow(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    checkbox->SetBackgroundColour(BG_COLOR);
    wxBoxSizer* sizer_checkbox = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer* sizer_check = new wxBoxSizer(wxVERTICAL);
    auto check = new ::CheckBox(checkbox);
    sizer_check->Add(check, 0, wxBOTTOM | wxEXPAND | wxTOP, FromDIP(5));
    sizer_checkbox->Add(sizer_check, 0, wxEXPAND, FromDIP(5));
    sizer_checkbox->Add(0, 0, 0, wxEXPAND | wxLEFT, FromDIP(11));
    auto text = new wxStaticText(checkbox, wxID_ANY, title, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
    text->SetFont(::Label::Body_13);
    text->SetForegroundColour(wxColour(107, 107, 107));
    text->Wrap(-1);
    sizer_checkbox->Add(text, 0, wxBOTTOM | wxEXPAND | wxTOP, FromDIP(5));
    checkbox->SetSizer(sizer_checkbox);
    checkbox->Layout();
    sizer_checkbox->Fit(checkbox);
    checkbox->SetToolTip(tooltip);
    text->SetToolTip(tooltip);
    text->Bind(wxEVT_LEFT_DOWN, [this, check](wxMouseEvent&) { check->SetValue(check->GetValue() ? false : true); });
    m_checkbox_list[param] = check;
    return checkbox;
}
References BG_COLOR, Label::Body_13, m_checkbox_list, Slic3r::GUI::wxMouseEvent, and wxStaticText.
Referenced by CalibrationDialog().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
is_stage_list_info_changed()
bool Slic3r::GUI::CalibrationDialog::is_stage_list_info_changed (MachineObject * obj)
{
    if (!obj) return true;
    if (last_stage_list_info.size() != obj->stage_list_info.size()) return true;
    for (int i = 0; i < last_stage_list_info.size(); i++) {
        if (last_stage_list_info[i] != obj->stage_list_info[i]) return true;
    }
    last_stage_list_info = obj->stage_list_info;
    return false;
}
References last_stage_list_info, and Slic3r::MachineObject::stage_list_info.
Referenced by update_cali().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_dpi_changed()
void Slic3r::GUI::CalibrationDialog::on_dpi_changed (const wxRect & suggested_rect) override virtual
Implements Slic3r::GUI::DPIAware< P >.
{}
on_start_calibration()
void Slic3r::GUI::CalibrationDialog::on_start_calibration (wxMouseEvent & event)
{
    if (m_obj) {
        if (m_obj->is_calibration_done()) {
            m_obj->calibration_done = false;
            EndModal(wxID_CANCEL);
            Close();
        } else {
            BOOST_LOG_TRIVIAL(info) << "on_start_calibration";
            m_obj->command_start_calibration(
                m_checkbox_list["vibration"]->GetValue(),
                m_checkbox_list["bed_leveling"]->GetValue(),
                m_checkbox_list["xcam_cali"]->GetValue()
                );
        }
    }
}
References Slic3r::MachineObject::calibration_done, Slic3r::MachineObject::command_start_calibration(), Slic3r::MachineObject::is_calibration_done(), m_checkbox_list, and m_obj.
Referenced by CalibrationDialog().
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
Show()
bool Slic3r::GUI::CalibrationDialog::Show (bool show) override
{
    if (show) {
        wxGetApp().UpdateDlgDarkUI(this);
        CentreOnParent();
    }
    return DPIDialog::Show(show);
}
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
update_cali()
void Slic3r::GUI::CalibrationDialog::update_cali (MachineObject * obj)
{
    if (!obj) return;
    if (obj->is_function_supported(PrinterFunction::FUNC_AI_MONITORING)) {
        select_xcam_cali->Show();
    } else {
        select_xcam_cali->Hide();
    }
    if (obj->is_calibration_running() || obj->is_calibration_done()) {
        if (obj->is_calibration_done()) {
            m_calibration_btn->Enable();
            m_calibration_btn->SetLabel(_L("Completed"));
        } else {
            // RUNNING && IDLE
            m_calibration_btn->Disable();
            m_calibration_btn->SetLabel(_L("Calibrating"));
        }
        auto size = wxSize(-1, obj->stage_list_info.size() * FromDIP(44));
        if (m_calibration_flow->GetSize().y != size.y) {
            m_calibration_flow->SetSize(size);
            m_calibration_flow->SetMinSize(size);
            m_calibration_flow->SetMaxSize(size);
            Layout();
        }
        if (is_stage_list_info_changed(obj)) {
            // change items if stage_list_info changed
            m_calibration_flow->DeleteAllItems();
            for (int i = 0; i < obj->stage_list_info.size(); i++) {
                m_calibration_flow->AppendItem(get_stage_string(obj->stage_list_info[i]));
            }
        }
        int index = obj->get_curr_stage_idx();
        m_calibration_flow->SelectItem(index);
    } else {
        // IDLE
        if (obj->is_in_printing()) {
            m_calibration_btn->Disable();
        }
        else {
            m_calibration_btn->Enable();
        }
        m_calibration_flow->DeleteAllItems();
        m_calibration_btn->SetLabel(_L("Start Calibration"));
    }
}
References _L, StepCtrlBase::AppendItem(), StepCtrlBase::DeleteAllItems(), Button::Enable(), Slic3r::FUNC_AI_MONITORING, Slic3r::MachineObject::get_curr_stage_idx(), get_stage_string(), Slic3r::MachineObject::is_calibration_done(), Slic3r::MachineObject::is_calibration_running(), Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_in_printing(), is_stage_list_info_changed(), m_calibration_btn, m_calibration_flow, select_xcam_cali, StepCtrlBase::SelectItem(), Button::SetLabel(), size, and Slic3r::MachineObject::stage_list_info.
Referenced by Slic3r::GUI::StatusPanel::update().
update_machine_obj()
void Slic3r::GUI::CalibrationDialog::update_machine_obj (MachineObject * obj)
{ m_obj = obj; }
References m_obj.
Referenced by Slic3r::GUI::StatusPanel::on_start_calibration(), and Slic3r::GUI::StatusPanel::update().
Member Data Documentation
last_stage_list_info
std::vector<int> Slic3r::GUI::CalibrationDialog::last_stage_list_info
Referenced by is_stage_list_info_changed().
m_calibration_btn
Button* Slic3r::GUI::CalibrationDialog::m_calibration_btn
Referenced by CalibrationDialog(), and update_cali().
m_calibration_flow
StepIndicator* Slic3r::GUI::CalibrationDialog::m_calibration_flow
Referenced by CalibrationDialog(), and update_cali().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_checkbox_list
std::map<std::string, ::CheckBox*> Slic3r::GUI::CalibrationDialog::m_checkbox_list private
Referenced by CalibrationDialog(), create_check_option(), and on_start_calibration().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_obj
MachineObject* Slic3r::GUI::CalibrationDialog::m_obj
Referenced by on_start_calibration(), and update_machine_obj().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_state
int Slic3r::GUI::CalibrationDialog::m_state {0}
select_bed_leveling
wxWindow* Slic3r::GUI::CalibrationDialog::select_bed_leveling { nullptr } private
Referenced by CalibrationDialog().
select_vibration
wxWindow* Slic3r::GUI::CalibrationDialog::select_vibration { nullptr } private
Referenced by CalibrationDialog().
select_xcam_cali
wxWindow* Slic3r::GUI::CalibrationDialog::select_xcam_cali { nullptr } private
Referenced by CalibrationDialog(), and update_cali().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Calibration.hpp
src/slic3r/GUI/Calibration.cpp