OrcaSlicer: src/qhull/src/libqhull_r/qset_r.c File Reference
qset_r.c File Reference
#include "libqhull_r.h"
#include "qset_r.h"
#include "mem_r.h"
#include <stdio.h>
#include <string.h>
Typedefs
typedef struct ridgeT ridgeT
typedef struct facetT facetT
Functions
void qh_errexit (qhT *qh, int exitcode, facetT *, ridgeT *)
void qh_fprintf (qhT *qh, FILE *fp, int msgcode, const char *fmt,...)
void qh_setaddnth (qhT *qh, setT **setp, int nth, void *newelem)
void qh_setaddsorted (qhT *qh, setT **setp, void *newelem)
void qh_setappend (qhT *qh, setT **setp, void *newelem)
void qh_setappend_set (qhT *qh, setT **setp, setT *setA)
void qh_setappend2ndlast (qhT *qh, setT **setp, void *newelem)
void qh_setcheck (qhT *qh, setT *set, const char *tname, unsigned id)
void qh_setcompact (qhT *qh, setT *set)
setT * qh_setcopy (qhT *qh, setT *set, int extra)
void * qh_setdel (setT *set, void *oldelem)
void * qh_setdellast (setT *set)
void * qh_setdelnth (qhT *qh, setT *set, int nth)
void * qh_setdelnthsorted (qhT *qh, setT *set, int nth)
void * qh_setdelsorted (setT *set, void *oldelem)
setT * qh_setduplicate (qhT *qh, setT *set, int elemsize)
void ** qh_setendpointer (setT *set)
int qh_setequal (setT *setA, setT *setB)
int qh_setequal_except (setT *setA, void *skipelemA, setT *setB, void *skipelemB)
int qh_setequal_skip (setT *setA, int skipA, setT *setB, int skipB)
void qh_setfree (qhT *qh, setT **setp)
void qh_setfree2 (qhT *qh, setT **setp, int elemsize)
void qh_setfreelong (qhT *qh, setT **setp)
int qh_setin (setT *set, void *setelem)
int qh_setindex (setT *set, void *atelem)
void qh_setlarger (qhT *qh, setT **oldsetp)
void * qh_setlast (setT *set)
setT * qh_setnew (qhT *qh, int setsize)
setT * qh_setnew_delnthsorted (qhT *qh, setT *set, int size, int nth, int prepend)
void qh_setprint (qhT *qh, FILE *fp, const char *string, setT *set)
void qh_setreplace (qhT *qh, setT *set, void *oldelem, void *newelem)
int qh_setsize (qhT *qh, setT *set)
setT * qh_settemp (qhT *qh, int setsize)
void qh_settempfree (qhT *qh, setT **set)
void qh_settempfree_all (qhT *qh)
setT * qh_settemppop (qhT *qh)
void qh_settemppush (qhT *qh, setT *set)
void qh_settruncate (qhT *qh, setT *set, int size)
int qh_setunique (qhT *qh, setT **set, void *elem)
void qh_setzero (qhT *qh, setT *set, int idx, int size)
Typedef Documentation
facetT
typedef struct facetT facetT
ridgeT
typedef struct ridgeT ridgeT
Function Documentation
qh_errexit()
void qh_errexit (qhT * qh, int exitcode, facetT * facet, ridgeT * ridge)
{
  if (qh->ERREXITcalled) {
    qh_fprintf(qh, qh->ferr, 8126, "\nqhull error while processing previous error.  Exit program\n");
    qh_exit(qh_ERRqhull);
  }
  qh->ERREXITcalled= True;
  if (!qh->QHULLfinished)
    qh->hulltime= qh_CPUclock - qh->hulltime;
  qh_errprint(qh, "ERRONEOUS", facet, NULL, ridge, NULL);
  qh_fprintf(qh, qh->ferr, 8127, "\nWhile executing: %s | %s\n", qh->rbox_command, qh->qhull_command);
  qh_fprintf(qh, qh->ferr, 8128, "Options selected for Qhull %s:\n%s\n", qh_version, qh->qhull_options);
  if (qh->furthest_id >= 0) {
    qh_fprintf(qh, qh->ferr, 8129, "Last point added to hull was p%d.", qh->furthest_id);
    if (zzval_(Ztotmerge))
      qh_fprintf(qh, qh->ferr, 8130, "  Last merge was #%d.", zzval_(Ztotmerge));
    if (qh->QHULLfinished)
      qh_fprintf(qh, qh->ferr, 8131, "\nQhull has finished constructing the hull.");
    else if (qh->POSTmerging)
      qh_fprintf(qh, qh->ferr, 8132, "\nQhull has started post-merging.");
    qh_fprintf(qh, qh->ferr, 8133, "\n");
  }
  if (qh->FORCEoutput && (qh->QHULLfinished || (!facet && !ridge)))
    qh_produce_output(qh);
  else if (exitcode != qh_ERRinput) {
    if (exitcode != qh_ERRsingular && zzval_(Zsetplane) > qh->hull_dim+1) {
      qh_fprintf(qh, qh->ferr, 8134, "\nAt error exit:\n");
      qh_printsummary(qh, qh->ferr);
      if (qh->PRINTstatistics) {
        qh_collectstatistics(qh);
        qh_printstatistics(qh, qh->ferr, "at error exit");
        qh_memstatistics(qh, qh->ferr);
      }
    }
    if (qh->PRINTprecision)
      qh_printstats(qh, qh->ferr, qh->qhstat.precision, NULL);
  }
  if (!exitcode)
    exitcode= qh_ERRqhull;
  else if (exitcode == qh_ERRsingular)
    qh_printhelp_singular(qh, qh->ferr);
  else if (exitcode == qh_ERRprec && !qh->PREmerge)
    qh_printhelp_degenerate(qh, qh->ferr);
  if (qh->NOerrexit) {
    qh_fprintf(qh, qh->ferr, 6187, "qhull error while ending program, or qh->NOerrexit not cleared after setjmp(). Exit program with error.\n");
    qh_exit(qh_ERRqhull);
  }
  qh->ERREXITcalled= False;
  qh->NOerrexit= True;
  qh->ALLOWrestart= False;  /* longjmp will undo qh_build_withrestart */
  longjmp(qh->errexit, exitcode);
} /* errexit */
References qh, qh_ERRqhull, qh_exit(), QHULL_UNUSED, True, void(), Ztotmerge, and zzval_.
Referenced by findDelaunay(), qh_fprintf(), qh_setaddnth(), qh_setcheck(), qh_setdelnth(), qh_setdelnthsorted(), qh_setnew_delnthsorted(), qh_setreplace(), qh_setsize(), qh_settempfree(), qh_settemppop(), qh_settemppush(), qh_settruncate(), and qh_setzero().
qh_fprintf()
void qh_fprintf (qhT * qh, FILE * fp, int msgcode, const char * fmt, ...)
{
    va_list args;
    if (!fp) {
        if(!qh){
            qh_fprintf_stderr(6241, "userprintf_r.c: fp and qh not defined for qh_fprintf '%s'", fmt);
            qh_exit(qhmem_ERRqhull);  /* can not use qh_errexit() */
        }
        /* could use qh->qhmem.ferr, but probably better to be cautious */
        qh_fprintf_stderr(6232, "Qhull internal error (userprintf_r.c): fp is 0.  Wrong qh_fprintf called.\n");
        qh_errexit(qh, 6232, NULL, NULL);
    }
    va_start(args, fmt);
    if (qh && qh->ANNOTATEoutput) {
      fprintf(fp, "[QH%.4d]", msgcode);
    }else if (msgcode >= MSG_ERROR && msgcode < MSG_STDERR ) {
      fprintf(fp, "QH%.4d ", msgcode);
    }
    vfprintf(fp, fmt, args);
    va_end(args);
    /* Place debugging traps here. Use with option 'Tn' */
} /* qh_fprintf */
References orgQhull::QhullQh::appendQhullMessage(), MSG_ERROR, MSG_MAXLEN, MSG_OUTPUT, MSG_WARNING, NULL, orgQhull::QhullQh::output_stream, qh, qh_errexit(), qh_exit(), qh_FILEstderr, qh_fprintf_stderr(), orgQhull::QhullQh::qhull_status, and orgQhull::QhullQh::use_output_stream.
Referenced by checkSetContents(), log_i(), main(), qh_setaddnth(), qh_setcheck(), qh_setdelnth(), qh_setdelnthsorted(), qh_setnew_delnthsorted(), qh_setprint(), qh_setreplace(), qh_setsize(), qh_settemp(), qh_settempfree(), qh_settemppop(), qh_settemppush(), qh_settruncate(), qh_setzero(), readOptions(), setupMemory(), testSetappendSet(), testSetappendSettruncate(), testSetcompactCopy(), testSetdelSetadd(), testSetdelsortedEtc(), testSetequalInEtc(), testSetlastEtc(), and testSettemp().
qh_setaddnth()
void qh_setaddnth (qhT * qh, setT ** setp, int nth, void * newelem)
{
  int oldsize, i;
  setelemT *sizep;          /* avoid strict aliasing */
  setelemT *oldp, *newp;
  if (!*setp || (sizep= SETsizeaddr_(*setp))->i==0) {
    qh_setlarger(qh, setp);
    sizep= SETsizeaddr_(*setp);
  }
  oldsize= sizep->i - 1;
  if (nth < 0 || nth > oldsize) {
    qh_fprintf(qh, qh->qhmem.ferr, 6171, "qhull internal error (qh_setaddnth): nth %d is out-of-bounds for set:\n", nth);
    qh_setprint(qh, qh->qhmem.ferr, "", *setp);
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  sizep->i++;
  oldp= (setelemT *)SETelemaddr_(*setp, oldsize, void);   /* NULL */
  newp= oldp+1;
  for (i=oldsize-nth+1; i--; )  /* move at least NULL  */
    (newp--)->p= (oldp--)->p;       /* may overwrite *sizep */
  newp->p= newelem;
} /* setaddnth */
References setelemT::i, NULL, setelemT::p, qh, qh_errexit(), qh_fprintf(), qh_setlarger(), qh_setprint(), qhmem_ERRqhull, SETelemaddr_, and SETsizeaddr_.
Referenced by qh_setaddsorted().
qh_setaddsorted()
void qh_setaddsorted (qhT * qh, setT ** setp, void * newelem)
{
  int newindex=0;
  void *elem, **elemp;
  FOREACHelem_(*setp) {          /* could use binary search instead */
    if (elem < newelem)
      newindex++;
    else if (elem == newelem)
      return;
    else
      break;
  }
  qh_setaddnth(qh, setp, newindex, newelem);
} /* setaddsorted */
References FOREACHelem_, qh, and qh_setaddnth().
qh_setappend()
void qh_setappend (qhT * qh, setT ** setp, void * newelem)
{
  setelemT *sizep;  /* Avoid strict aliasing.  Writing to *endp may overwrite *sizep */
  setelemT *endp;
  int count;
  if (!newelem)
    return;
  if (!*setp || (sizep= SETsizeaddr_(*setp))->i==0) {
    qh_setlarger(qh, setp);
    sizep= SETsizeaddr_(*setp);
  }
  count= (sizep->i)++ - 1;
  endp= (setelemT *)SETelemaddr_(*setp, count, void);
  (endp++)->p= newelem;
  endp->p= NULL;
} /* setappend */
References count, setelemT::i, NULL, setelemT::p, qh, qh_setlarger(), SETelemaddr_, and SETsizeaddr_.
Referenced by qh_setduplicate(), qh_settemp(), qh_settemppush(), and qh_setunique().
qh_setappend2ndlast()
void qh_setappend2ndlast (qhT * qh, setT ** setp, void * newelem)
{
    setelemT *sizep;  /* Avoid strict aliasing.  Writing to *endp may overwrite *sizep */
    setelemT *endp, *lastp;
    int count;
    if (!*setp || (sizep= SETsizeaddr_(*setp))->i==0) {
        qh_setlarger(qh, setp);
        sizep= SETsizeaddr_(*setp);
    }
    count= (sizep->i)++ - 1;
    endp= (setelemT *)SETelemaddr_(*setp, count, void); /* NULL */
    lastp= endp-1;
    *(endp++)= *lastp;
    endp->p= NULL;    /* may overwrite *sizep */
    lastp->p= newelem;
} /* setappend2ndlast */
References count, setelemT::i, NULL, setelemT::p, qh, qh_setlarger(), SETelemaddr_, and SETsizeaddr_.
qh_setappend_set()
void qh_setappend_set (qhT * qh, setT ** setp, setT * setA)
{
  int sizeA, size;
  setT *oldset;
  setelemT *sizep;
  if (!setA)
    return;
  SETreturnsize_(setA, sizeA);
  if (!*setp)
    *setp= qh_setnew(qh, sizeA);
  sizep= SETsizeaddr_(*setp);
  if (!(size= sizep->i))
    size= (*setp)->maxsize;
  else
    size--;
  if (size + sizeA > (*setp)->maxsize) {
    oldset= *setp;
    *setp= qh_setcopy(qh, oldset, sizeA);
    qh_setfree(qh, &oldset);
    sizep= SETsizeaddr_(*setp);
  }
  if (sizeA > 0) {
    sizep->i= size+sizeA+1;   /* memcpy may overwrite */
    memcpy((char *)&((*setp)->e[size].p), (char *)&(setA->e[0].p), (size_t)(sizeA+1) * SETelemsize);
  }
} /* setappend_set */
References setT::e, setelemT::i, memcpy, setelemT::p, qh, qh_setcopy(), qh_setfree(), qh_setnew(), SETelemsize, SETreturnsize_, SETsizeaddr_, and size.
qh_setcheck()
void qh_setcheck (qhT * qh, setT * set, const char * tname, unsigned id)
{
  int maxsize, size;
  int waserr= 0;
  if (!set)
    return;
  SETreturnsize_(set, size);
  maxsize= set->maxsize;
  if (size > maxsize || !maxsize) {
    qh_fprintf(qh, qh->qhmem.ferr, 6172, "qhull internal error (qh_setcheck): actual size %d of %s%d is greater than max size %d\n",
             size, tname, id, maxsize);
    waserr= 1;
  }else if (set->e[size].p) {
    qh_fprintf(qh, qh->qhmem.ferr, 6173, "qhull internal error (qh_setcheck): %s%d(size %d max %d) is not null terminated.\n",
             tname, id, size-1, maxsize);
    waserr= 1;
  }
  if (waserr) {
    qh_setprint(qh, qh->qhmem.ferr, "ERRONEOUS", set);
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
} /* setcheck */
References setT::e, setT::maxsize, NULL, setelemT::p, qh, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem_ERRqhull, SETreturnsize_, and size.
qh_setcompact()
void qh_setcompact (qhT * qh, setT * set)
{
  int size;
  void **destp, **elemp, **endp, **firstp;
  if (!set)
    return;
  SETreturnsize_(set, size);
  destp= elemp= firstp= SETaddr_(set, void);
  endp= destp + size;
  while (1) {
    if (!(*destp++ = *elemp++)) {
      destp--;
      if (elemp > endp)
        break;
    }
  }
  qh_settruncate(qh, set, (int)(destp-firstp));   /* WARN64 */
} /* setcompact */
References qh, qh_settruncate(), SETaddr_, SETreturnsize_, and size.
qh_setcopy()
setT * qh_setcopy (qhT * qh, setT * set, int extra)
{
  setT *newset;
  int size;
  if (extra < 0)
    extra= 0;
  SETreturnsize_(set, size);
  newset= qh_setnew(qh, size+extra);
  SETsizeaddr_(newset)->i= size+1;    /* memcpy may overwrite */
  memcpy((char *)&(newset->e[0].p), (char *)&(set->e[0].p), (size_t)(size+1) * SETelemsize);
  return(newset);
} /* setcopy */
References setT::e, memcpy, setelemT::p, qh, qh_setnew(), SETelemsize, SETreturnsize_, SETsizeaddr_, and size.
Referenced by qh_setappend_set().
qh_setdel()
void * qh_setdel (setT * set, void * oldelem)
{
  setelemT *sizep;
  setelemT *elemp;
  setelemT *lastp;
  if (!set)
    return NULL;
  elemp= (setelemT *)SETaddr_(set, void);
  while (elemp->p != oldelem && elemp->p)
    elemp++;
  if (elemp->p) {
    sizep= SETsizeaddr_(set);
    if (!(sizep->i)--)         /*  if was a full set */
      sizep->i= set->maxsize;  /*     *sizep= (maxsize-1)+ 1 */
    lastp= (setelemT *)SETelemaddr_(set, sizep->i-1, void);
    elemp->p= lastp->p;      /* may overwrite itself */
    lastp->p= NULL;
    return oldelem;
  }
  return NULL;
} /* setdel */
References setelemT::i, setT::maxsize, NULL, setelemT::p, SETaddr_, SETelemaddr_, and SETsizeaddr_.
qh_setdellast()
void * qh_setdellast (setT * set)
{
  int setsize;  /* actually, actual_size + 1 */
  int maxsize;
  setelemT *sizep;
  void *returnvalue;
  if (!set || !(set->e[0].p))
    return NULL;
  sizep= SETsizeaddr_(set);
  if ((setsize= sizep->i)) {
    returnvalue= set->e[setsize - 2].p;
    set->e[setsize - 2].p= NULL;
    sizep->i--;
  }else {
    maxsize= set->maxsize;
    returnvalue= set->e[maxsize - 1].p;
    set->e[maxsize - 1].p= NULL;
    sizep->i= maxsize;
  }
  return returnvalue;
} /* setdellast */
References setT::e, setelemT::i, setT::maxsize, NULL, setelemT::p, and SETsizeaddr_.
Referenced by qh_settemppop().
qh_setdelnth()
void * qh_setdelnth (qhT * qh, setT * set, int nth)
{
  void *elem;
  setelemT *sizep;
  setelemT *elemp, *lastp;
  sizep= SETsizeaddr_(set);
  if ((sizep->i--)==0)         /*  if was a full set */
    sizep->i= set->maxsize;  /*     *sizep= (maxsize-1)+ 1 */
  if (nth < 0 || nth >= sizep->i) {
    qh_fprintf(qh, qh->qhmem.ferr, 6174, "qhull internal error (qh_setdelnth): nth %d is out-of-bounds for set:\n", nth);
    qh_setprint(qh, qh->qhmem.ferr, "", set);
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  elemp= (setelemT *)SETelemaddr_(set, nth, void); /* nth valid by QH6174 */
  lastp= (setelemT *)SETelemaddr_(set, sizep->i-1, void);
  elem= elemp->p;
  elemp->p= lastp->p;      /* may overwrite itself */
  lastp->p= NULL;
  return elem;
} /* setdelnth */
References setelemT::i, setT::maxsize, NULL, setelemT::p, qh, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem_ERRqhull, SETelemaddr_, and SETsizeaddr_.
qh_setdelnthsorted()
void * qh_setdelnthsorted (qhT * qh, setT * set, int nth)
{
  void *elem;
  setelemT *sizep;
  setelemT *newp, *oldp;
  sizep= SETsizeaddr_(set);
  if (nth < 0 || (sizep->i && nth >= sizep->i-1) || nth >= set->maxsize) {
    qh_fprintf(qh, qh->qhmem.ferr, 6175, "qhull internal error (qh_setdelnthsorted): nth %d is out-of-bounds for set:\n", nth);
    qh_setprint(qh, qh->qhmem.ferr, "", set);
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  newp= (setelemT *)SETelemaddr_(set, nth, void);
  elem= newp->p;
  oldp= newp+1;
  while (((newp++)->p= (oldp++)->p))
    ; /* copy remaining elements and NULL */
  if ((sizep->i--)==0)         /*  if was a full set */
    sizep->i= set->maxsize;  /*     *sizep= (max size-1)+ 1 */
  return elem;
} /* setdelnthsorted */
References setelemT::i, setT::maxsize, NULL, setelemT::p, qh, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem_ERRqhull, SETelemaddr_, and SETsizeaddr_.
qh_setdelsorted()
void * qh_setdelsorted (setT * set, void * oldelem)
{
  setelemT *sizep;
  setelemT *newp, *oldp;
  if (!set)
    return NULL;
  newp= (setelemT *)SETaddr_(set, void);
  while(newp->p != oldelem && newp->p)
    newp++;
  if (newp->p) {
    oldp= newp+1;
    while (((newp++)->p= (oldp++)->p))
      ; /* copy remaining elements */
    sizep= SETsizeaddr_(set);
    if ((sizep->i--)==0)    /*  if was a full set */
      sizep->i= set->maxsize;  /*     *sizep= (max size-1)+ 1 */
    return oldelem;
  }
  return NULL;
} /* setdelsorted */
References setelemT::i, setT::maxsize, NULL, setelemT::p, SETaddr_, and SETsizeaddr_.
qh_setduplicate()
setT * qh_setduplicate (qhT * qh, setT * set, int elemsize)
{
  void          *elem, **elemp, *newElem;
  setT          *newSet;
  int           size;
  if (!(size= qh_setsize(qh, set)))
    return NULL;
  newSet= qh_setnew(qh, size);
  FOREACHelem_(set) {
    newElem= qh_memalloc(qh, elemsize);
    memcpy(newElem, elem, (size_t)elemsize);
    qh_setappend(qh, &newSet, newElem);
  }
  return newSet;
} /* setduplicate */
References FOREACHelem_, memcpy, NULL, qh, qh_memalloc(), qh_setappend(), qh_setnew(), qh_setsize(), and size.
qh_setendpointer()
void ** qh_setendpointer (setT * set)
{
  setelemT *sizep= SETsizeaddr_(set);
  int n= sizep->i;
  return (n ? &set->e[n-1].p : &sizep->p);
} /* qh_setendpointer */
References setT::e, setelemT::i, n, setelemT::p, and SETsizeaddr_.
qh_setequal()
int qh_setequal (setT * setA, setT * setB)
{
  void **elemAp, **elemBp;
  int sizeA= 0, sizeB= 0;
  if (setA) {
    SETreturnsize_(setA, sizeA);
  }
  if (setB) {
    SETreturnsize_(setB, sizeB);
  }
  if (sizeA != sizeB)
    return 0;
  if (!sizeA)
    return 1;
  elemAp= SETaddr_(setA, void);
  elemBp= SETaddr_(setB, void);
  if (!memcmp((char *)elemAp, (char *)elemBp, sizeA*SETelemsize))
    return 1;
  return 0;
} /* setequal */
References memcmp, SETaddr_, SETelemsize, and SETreturnsize_.
qh_setequal_except()
int qh_setequal_except (setT * setA, void * skipelemA, setT * setB, void * skipelemB)
{
  void **elemA, **elemB;
  int skip=0;
  elemA= SETaddr_(setA, void);
  elemB= SETaddr_(setB, void);
  while (1) {
    if (*elemA == skipelemA) {
      skip++;
      elemA++;
    }
    if (skipelemB) {
      if (*elemB == skipelemB) {
        skip++;
        elemB++;
      }
    }else if (*elemA != *elemB) {
      skip++;
      if (!(skipelemB= *elemB++))
        return 0;
    }
    if (!*elemA)
      break;
    if (*elemA++ != *elemB++)
      return 0;
  }
  if (skip != 2 || *elemB)
    return 0;
  return 1;
} /* setequal_except */
References SETaddr_.
qh_setequal_skip()
int qh_setequal_skip (setT * setA, int skipA, setT * setB, int skipB)
{
  void **elemA, **elemB, **skipAp, **skipBp;
  elemA= SETaddr_(setA, void);
  elemB= SETaddr_(setB, void);
  skipAp= SETelemaddr_(setA, skipA, void);
  skipBp= SETelemaddr_(setB, skipB, void);
  while (1) {
    if (elemA == skipAp)
      elemA++;
    if (elemB == skipBp)
      elemB++;
    if (!*elemA)
      break;
    if (*elemA++ != *elemB++)
      return 0;
  }
  if (*elemB)
    return 0;
  return 1;
} /* setequal_skip */
References SETaddr_, and SETelemaddr_.
qh_setfree()
void qh_setfree (qhT * qh, setT ** setp)
{
  int size;
  void **freelistp;  /* used if !qh_NOmem by qh_memfree_() */
  if (*setp) {
    size= sizeof(setT) + ((*setp)->maxsize)*SETelemsize;
    if (size <= qh->qhmem.LASTsize) {
      qh_memfree_(qh, *setp, size, freelistp);
    }else
      qh_memfree(qh, *setp, size);
    *setp= NULL;
  }
} /* setfree */
References qhmemT::LASTsize, NULL, qh, qh_memfree(), qh_memfree_, qhmem, SETelemsize, and size.
Referenced by qh_setappend_set(), qh_setfree2(), qh_setlarger(), qh_settempfree(), and qh_settempfree_all().
qh_setfree2()
void qh_setfree2 (qhT * qh, setT ** setp, int elemsize)
{
  void          *elem, **elemp;
  FOREACHelem_(*setp)
    qh_memfree(qh, elem, elemsize);
  qh_setfree(qh, setp);
} /* setfree2 */
References FOREACHelem_, qh, qh_memfree(), and qh_setfree().
qh_setfreelong()
void qh_setfreelong (qhT * qh, setT ** setp)
{
  int size;
  if (*setp) {
    size= sizeof(setT) + ((*setp)->maxsize)*SETelemsize;
    if (size > qh->qhmem.LASTsize) {
      qh_memfree(qh, *setp, size);
      *setp= NULL;
    }
  }
} /* setfreelong */
References NULL, qh, qh_memfree(), SETelemsize, and size.
qh_setin()
int qh_setin (setT * set, void * setelem)
{
  void *elem, **elemp;
  FOREACHelem_(set) {
    if (elem == setelem)
      return 1;
  }
  return 0;
} /* setin */
References FOREACHelem_.
Referenced by qh_setunique().
qh_setindex()
int qh_setindex (setT * set, void * atelem)
{
  void **elem;
  int size, i;
  if (!set)
    return -1;
  SETreturnsize_(set, size);
  if (size > set->maxsize)
    return -1;
  elem= SETaddr_(set, void);
  for (i=0; i < size; i++) {
    if (*elem++ == atelem)
      return i;
  }
  return -1;
} /* setindex */
References setT::maxsize, SETaddr_, SETreturnsize_, and size.
qh_setlarger()
void qh_setlarger (qhT * qh, setT ** oldsetp)
{
  int size= 1;
  setT *newset, *set, **setp, *oldset;
  setelemT *sizep;
  setelemT *newp, *oldp;
  if (*oldsetp) {
    oldset= *oldsetp;
    SETreturnsize_(oldset, size);
    qh->qhmem.cntlarger++;
    qh->qhmem.totlarger += size+1;
    newset= qh_setnew(qh, 2 * size);
    oldp= (setelemT *)SETaddr_(oldset, void);
    newp= (setelemT *)SETaddr_(newset, void);
    memcpy((char *)newp, (char *)oldp, (size_t)(size+1) * SETelemsize);
    sizep= SETsizeaddr_(newset);
    sizep->i= size+1;
    FOREACHset_((setT *)qh->qhmem.tempstack) {
      if (set == oldset)
        *(setp-1)= newset;
    }
    qh_setfree(qh, oldsetp);
  }else
    newset= qh_setnew(qh, 3);
  *oldsetp= newset;
} /* setlarger */
References FOREACHset_, setelemT::i, memcpy, qh, qh_setfree(), qh_setnew(), SETaddr_, SETelemsize, SETreturnsize_, SETsizeaddr_, and size.
Referenced by qh_setaddnth(), qh_setappend(), and qh_setappend2ndlast().
qh_setlast()
void * qh_setlast (setT * set)
{
  int size;
  if (set) {
    size= SETsizeaddr_(set)->i;
    if (!size)
      return SETelem_(set, set->maxsize - 1);
    else if (size > 1)
      return SETelem_(set, size - 2);
  }
  return NULL;
} /* setlast */
References setT::maxsize, NULL, SETelem_, SETsizeaddr_, and size.
qh_setnew()
setT * qh_setnew (qhT * qh, int setsize)
{
  setT *set;
  int sizereceived; /* used if !qh_NOmem */
  int size;
  void **freelistp; /* used if !qh_NOmem by qh_memalloc_() */
  if (!setsize)
    setsize++;
  size= sizeof(setT) + setsize * SETelemsize;
  if (size>0 && size <= qh->qhmem.LASTsize) {
    qh_memalloc_(qh, size, freelistp, set, setT);
#ifndef qh_NOmem
    sizereceived= qh->qhmem.sizetable[ qh->qhmem.indextable[size]];
    if (sizereceived > size)
      setsize += (sizereceived - size)/SETelemsize;
#endif
  }else
    set= (setT*)qh_memalloc(qh, size);
  set->maxsize= setsize;
  set->e[setsize].i= 1;
  set->e[0].p= NULL;
  return(set);
} /* setnew */
References setT::e, setelemT::i, qhmemT::LASTsize, setT::maxsize, NULL, setelemT::p, qh, qh_memalloc(), qh_memalloc_, qhmem, SETelemsize, and size.
Referenced by qh_setappend_set(), qh_setcopy(), qh_setduplicate(), qh_setlarger(), qh_setnew_delnthsorted(), and qh_settemp().
qh_setnew_delnthsorted()
setT * qh_setnew_delnthsorted (qhT * qh, setT * set, int size, int nth, int prepend)
{
  setT *newset;
  void **oldp, **newp;
  int tailsize= size - nth -1, newsize;
  if (tailsize < 0) {
    qh_fprintf(qh, qh->qhmem.ferr, 6176, "qhull internal error (qh_setnew_delnthsorted): nth %d is out-of-bounds for set:\n", nth);
    qh_setprint(qh, qh->qhmem.ferr, "", set);
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  newsize= size-1 + prepend;
  newset= qh_setnew(qh, newsize);
  newset->e[newset->maxsize].i= newsize+1;  /* may be overwritten */
  oldp= SETaddr_(set, void);
  newp= SETaddr_(newset, void) + prepend;
  switch (nth) {
  case 0:
    break;
  case 1:
    *(newp++)= *oldp++;
    break;
  case 2:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  case 3:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  case 4:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  default:
    memcpy((char *)newp, (char *)oldp, (size_t)nth * SETelemsize);
    newp += nth;
    oldp += nth;
    break;
  }
  oldp++;
  switch (tailsize) {
  case 0:
    break;
  case 1:
    *(newp++)= *oldp++;
    break;
  case 2:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  case 3:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  case 4:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  default:
    memcpy((char *)newp, (char *)oldp, (size_t)tailsize * SETelemsize);
    newp += tailsize;
  }
  *newp= NULL;
  return(newset);
} /* setnew_delnthsorted */
References setT::e, setelemT::i, setT::maxsize, memcpy, NULL, qh, qh_errexit(), qh_fprintf(), qh_setnew(), qh_setprint(), qhmem_ERRqhull, SETaddr_, SETelemsize, and size.
qh_setprint()
void qh_setprint (qhT * qh, FILE * fp, const char * string, setT * set)
{
  int size, k;
  if (!set)
    qh_fprintf(qh, fp, 9346, "%s set is null\n", string);
  else {
    SETreturnsize_(set, size);
    qh_fprintf(qh, fp, 9347, "%s set=%p maxsize=%d size=%d elems=",
             string, set, set->maxsize, size);
    if (size > set->maxsize)
      size= set->maxsize+1;
    for (k=0; k < size; k++)
      qh_fprintf(qh, fp, 9348, " %p", set->e[k].p);
    qh_fprintf(qh, fp, 9349, "\n");
  }
} /* setprint */
References setT::e, setT::maxsize, setelemT::p, qh, qh_fprintf(), SETreturnsize_, and size.
Referenced by qh_setaddnth(), qh_setcheck(), qh_setdelnth(), qh_setdelnthsorted(), qh_setnew_delnthsorted(), qh_setreplace(), qh_setsize(), qh_settruncate(), and qh_setzero().
qh_setreplace()
void qh_setreplace (qhT * qh, setT * set, void * oldelem, void * newelem)
{
  void **elemp;
  elemp= SETaddr_(set, void);
  while (*elemp != oldelem && *elemp)
    elemp++;
  if (*elemp)
    *elemp= newelem;
  else {
    qh_fprintf(qh, qh->qhmem.ferr, 6177, "qhull internal error (qh_setreplace): elem %p not found in set\n",
       oldelem);
    qh_setprint(qh, qh->qhmem.ferr, "", set);
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
} /* setreplace */
References NULL, qh, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem_ERRqhull, and SETaddr_.
qh_setsize()
int qh_setsize (qhT * qh, setT * set)
{
  int size;
  setelemT *sizep;
  if (!set)
    return(0);
  sizep= SETsizeaddr_(set);
  if ((size= sizep->i)) {
    size--;
    if (size > set->maxsize) {
      qh_fprintf(qh, qh->qhmem.ferr, 6178, "qhull internal error (qh_setsize): current set size %d is greater than maximum size %d\n",
               size, set->maxsize);
      qh_setprint(qh, qh->qhmem.ferr, "set: ", set);
      qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
    }
  }else
    size= set->maxsize;
  return size;
} /* setsize */
References setelemT::i, setT::maxsize, NULL, qh, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem_ERRqhull, SETsizeaddr_, and size.
Referenced by qh_setduplicate(), qh_settemp(), qh_settempfree(), qh_settemppop(), and qh_settemppush().
qh_settemp()
setT * qh_settemp (qhT * qh, int setsize)
{
  setT *newset;
  newset= qh_setnew(qh, setsize);
  qh_setappend(qh, &qh->qhmem.tempstack, newset);
  if (qh->qhmem.IStracing >= 5)
    qh_fprintf(qh, qh->qhmem.ferr, 8123, "qh_settemp: temp set %p of %d elements, depth %d\n",
       newset, newset->maxsize, qh_setsize(qh, qh->qhmem.tempstack));
  return newset;
} /* settemp */
References setT::maxsize, qh, qh_fprintf(), qh_setappend(), qh_setnew(), and qh_setsize().
qh_settempfree()
void qh_settempfree (qhT * qh, setT ** set)
{
  setT *stackedset;
  if (!*set)
    return;
  stackedset= qh_settemppop(qh);
  if (stackedset != *set) {
    qh_settemppush(qh, stackedset);
    qh_fprintf(qh, qh->qhmem.ferr, 6179, "qhull internal error (qh_settempfree): set %p(size %d) was not last temporary allocated(depth %d, set %p, size %d)\n",
             *set, qh_setsize(qh, *set), qh_setsize(qh, qh->qhmem.tempstack)+1,
             stackedset, qh_setsize(qh, stackedset));
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  qh_setfree(qh, set);
} /* settempfree */
References NULL, qh, qh_errexit(), qh_fprintf(), qh_setfree(), qh_setsize(), qh_settemppop(), qh_settemppush(), and qhmem_ERRqhull.
qh_settempfree_all()
void qh_settempfree_all (qhT * qh)
{
  setT *set, **setp;
  FOREACHset_(qh->qhmem.tempstack)
    qh_setfree(qh, &set);
  qh_setfree(qh, &qh->qhmem.tempstack);
} /* settempfree_all */
References FOREACHset_, qh, and qh_setfree().
qh_settemppop()
setT * qh_settemppop (qhT * qh)
{
  setT *stackedset;
  stackedset= (setT*)qh_setdellast(qh->qhmem.tempstack);
  if (!stackedset) {
    qh_fprintf(qh, qh->qhmem.ferr, 6180, "qhull internal error (qh_settemppop): pop from empty temporary stack\n");
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  if (qh->qhmem.IStracing >= 5)
    qh_fprintf(qh, qh->qhmem.ferr, 8124, "qh_settemppop: depth %d temp set %p of %d elements\n",
       qh_setsize(qh, qh->qhmem.tempstack)+1, stackedset, qh_setsize(qh, stackedset));
  return stackedset;
} /* settemppop */
References NULL, qh, qh_errexit(), qh_fprintf(), qh_setdellast(), qh_setsize(), and qhmem_ERRqhull.
qh_settemppush()
void qh_settemppush (qhT * qh, setT * set)
{
  if (!set) {
    qh_fprintf(qh, qh->qhmem.ferr, 6267, "qhull error (qh_settemppush): can not push a NULL temp\n");
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  qh_setappend(qh, &qh->qhmem.tempstack, set);
  if (qh->qhmem.IStracing >= 5)
    qh_fprintf(qh, qh->qhmem.ferr, 8125, "qh_settemppush: depth %d temp set %p of %d elements\n",
      qh_setsize(qh, qh->qhmem.tempstack), set, qh_setsize(qh, set));
} /* settemppush */
References NULL, qh, qh_errexit(), qh_fprintf(), qh_setappend(), qh_setsize(), and qhmem_ERRqhull.
Referenced by qh_settempfree().
qh_settruncate()
void qh_settruncate (qhT * qh, setT * set, int size)
{
  if (size < 0 || size > set->maxsize) {
    qh_fprintf(qh, qh->qhmem.ferr, 6181, "qhull internal error (qh_settruncate): size %d out of bounds for set:\n", size);
    qh_setprint(qh, qh->qhmem.ferr, "", set);
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  set->e[set->maxsize].i= size+1;   /* maybe overwritten */
  set->e[size].p= NULL;
} /* settruncate */
References setT::e, setelemT::i, setT::maxsize, NULL, setelemT::p, qh, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem_ERRqhull, and size.
Referenced by qh_setcompact().
qh_setunique()
int qh_setunique (qhT * qh, setT ** set, void * elem)
{
  if (!qh_setin(*set, elem)) {
    qh_setappend(qh, set, elem);
    return 1;
  }
  return 0;
} /* setunique */
References qh, qh_setappend(), and qh_setin().
qh_setzero()
void qh_setzero (qhT * qh, setT * set, int idx, int size)
{
  int count;
  if (idx < 0 || idx >= size || size > set->maxsize) {
    qh_fprintf(qh, qh->qhmem.ferr, 6182, "qhull internal error (qh_setzero): index %d or size %d out of bounds for set:\n", idx, size);
    qh_setprint(qh, qh->qhmem.ferr, "", set);
    qh_errexit(qh, qhmem_ERRqhull, NULL, NULL);
  }
  set->e[set->maxsize].i=  size+1;  /* may be overwritten */
  count= size - idx + 1;   /* +1 for NULL terminator */
  memset((char *)SETelemaddr_(set, idx, void), 0, (size_t)count * SETelemsize);
} /* setzero */
References count, setT::e, setelemT::i, setT::maxsize, memset, NULL, qh, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem_ERRqhull, SETelemaddr_, SETelemsize, and size.