OrcaSlicer: Slic3r::GUI::FanOperate Class Reference
Slic3r::GUI::FanOperate Class Reference
#include <src/slic3r/GUI/Widgets/FanControl.hpp>
Public Member Functions
FanOperate (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~FanOperate ()
void post_event (wxCommandEvent &&event)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
void msw_rescale ()
void create (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size)
void on_left_down (wxMouseEvent &event)
void set_fan_speeds (int g)
void add_fan_speeds ()
void decrease_fan_speeds ()
Private Attributes
int m_current_speeds
int m_min_speeds
int m_max_speeds
ScalableBitmap m_bitmap_add
ScalableBitmap m_bitmap_decrease
Detailed Description
Constructor & Destructor Documentation
FanOperate()
Slic3r::GUI::FanOperate::FanOperate (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{
    m_current_speeds = 0;
    m_min_speeds     = 1;
    m_max_speeds     = 10;
    create(parent, id, pos, size);
}
References create(), m_current_speeds, m_max_speeds, m_min_speeds, and size.
~FanOperate()
Slic3r::GUI::FanOperate::~FanOperate () inline
{};
Member Function Documentation
add_fan_speeds()
void Slic3r::GUI::FanOperate::add_fan_speeds ()
{
    if (m_current_speeds + 1 > m_max_speeds) return;
    set_fan_speeds(++m_current_speeds);
    post_event(wxCommandEvent(EVT_FAN_ADD));
    post_event(wxCommandEvent(EVT_FAN_SWITCH_ON));
}
References m_current_speeds, m_max_speeds, post_event(), and set_fan_speeds().
Referenced by on_left_down().
create()
void Slic3r::GUI::FanOperate::create (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size)
{
    wxWindow::Create(parent, id, pos, size, wxBORDER_NONE);
    SetBackgroundColour(*wxWHITE);
    m_bitmap_add        = ScalableBitmap(this, "fan_control_add", FromDIP(11));
    m_bitmap_decrease   = ScalableBitmap(this, "fan_control_decrease", FromDIP(11));
    SetMinSize(wxSize(FromDIP(SIZE_OF_FAN_OPERATE.x), FromDIP(SIZE_OF_FAN_OPERATE.y)));
    Bind(wxEVT_PAINT, &FanOperate::paintEvent, this);
    Bind(wxEVT_ENTER_WINDOW, [this](auto& e) { SetCursor(wxCURSOR_HAND);});
    Bind(wxEVT_LEAVE_WINDOW, [this](auto& e) { SetCursor(wxCURSOR_ARROW);});
    Bind(wxEVT_LEFT_DOWN, &FanOperate::on_left_down, this);
}
References m_bitmap_add, m_bitmap_decrease, on_left_down(), paintEvent(), size, and SIZE_OF_FAN_OPERATE.
Referenced by FanOperate().
decrease_fan_speeds()
void Slic3r::GUI::FanOperate::decrease_fan_speeds ()
{
    //turn off
    if (m_current_speeds - 1 < m_min_speeds) {
        m_current_speeds = 0;
        set_fan_speeds(m_current_speeds);
        post_event(wxCommandEvent(EVT_FAN_SWITCH_OFF));
    }
    else {
        set_fan_speeds(--m_current_speeds);
    }
     post_event(wxCommandEvent(EVT_FAN_DEC));
}
References m_current_speeds, m_min_speeds, post_event(), and set_fan_speeds().
Referenced by on_left_down().
doRender()
void Slic3r::GUI::FanOperate::doRender (wxDC & dc)
{
    wxSize size = GetSize();
    dc.SetPen(wxPen(DRAW_OPERATE_LINE_COLOUR));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRoundedRectangle(0,0,size.x,size.y,5);
    //splt
    auto left_fir = size.x / 3;
    dc.DrawLine(left_fir, FromDIP(4), left_fir, size.y - FromDIP(4));
    dc.DrawLine(left_fir * 2, FromDIP(4), left_fir * 2, size.y - FromDIP(4));
    dc.DrawBitmap(m_bitmap_decrease.bmp(), (left_fir - m_bitmap_decrease.GetBmpSize().x) / 2, (size.y - m_bitmap_decrease.GetBmpSize().y) / 2);
    dc.DrawBitmap(m_bitmap_add.bmp(), (left_fir * 2 + (left_fir - m_bitmap_decrease.GetBmpSize().x) / 2), (size.y - m_bitmap_add.GetBmpSize().y) / 2);
    //txt
    dc.SetFont(::Label::Body_12);
    dc.SetTextForeground(StateColor::darkModeColorFor(wxColour(0x898989)));
    wxString text = wxString::Format("%d%%", 10);
    wxSize text_size = dc.GetTextExtent(text);
    dc.DrawText(text, wxPoint(left_fir + (left_fir- text_size.x) / 2, (size.y- text_size.y) / 2));
}
References ScalableBitmap::bmp(), Label::Body_12, StateColor::darkModeColorFor(), DRAW_OPERATE_LINE_COLOUR, ScalableBitmap::GetBmpSize(), m_bitmap_add, m_bitmap_decrease, and size.
Referenced by render().
msw_rescale()
void Slic3r::GUI::FanOperate::msw_rescale ()
{
}
on_left_down()
void Slic3r::GUI::FanOperate::on_left_down (wxMouseEvent & event)
{
     auto mouse_pos = ClientToScreen(event.GetPosition());
     auto win_pos = ClientToScreen(wxPoint(0, 0));
     auto decrease_fir = GetSize().x / 3 + win_pos.x;
     auto add_fir = GetSize().x / 3 * 2 + win_pos.x;
     if (mouse_pos.x > win_pos.x && mouse_pos.x < decrease_fir && mouse_pos.y > win_pos.y && mouse_pos.y < (win_pos.y + GetSize().y)) {
         decrease_fan_speeds();
         return;
     }
     if (mouse_pos.x > add_fir && mouse_pos.x < (win_pos.x + GetSize().x) && mouse_pos.y > win_pos.y && mouse_pos.y < (win_pos.y + GetSize().y)) {
         add_fan_speeds();
         return;
     }
}
References add_fan_speeds(), and decrease_fan_speeds().
Referenced by create(), and Slic3r::GUI::FanControl::on_left_down().
paintEvent()
void Slic3r::GUI::FanOperate::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by create().
post_event()
void Slic3r::GUI::FanOperate::post_event (wxCommandEvent && event)
{
    event.SetInt(m_current_speeds);
    event.SetEventObject(this);
    wxPostEvent(this, event);
    event.Skip();
}
References m_current_speeds.
Referenced by add_fan_speeds(), and decrease_fan_speeds().
render()
void Slic3r::GUI::FanOperate::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
set_fan_speeds()
void Slic3r::GUI::FanOperate::set_fan_speeds (int g)
{
    m_current_speeds = g;
    Refresh();
}
References m_current_speeds.
Referenced by add_fan_speeds(), decrease_fan_speeds(), and Slic3r::GUI::FanControl::set_fan_speed().
Member Data Documentation
m_bitmap_add
ScalableBitmap Slic3r::GUI::FanOperate::m_bitmap_add private
Referenced by create(), and doRender().
m_bitmap_decrease
ScalableBitmap Slic3r::GUI::FanOperate::m_bitmap_decrease private
Referenced by create(), and doRender().
m_current_speeds
int Slic3r::GUI::FanOperate::m_current_speeds private
Referenced by FanOperate(), add_fan_speeds(), decrease_fan_speeds(), post_event(), and set_fan_speeds().
m_max_speeds
int Slic3r::GUI::FanOperate::m_max_speeds private
Referenced by FanOperate(), and add_fan_speeds().
m_min_speeds
int Slic3r::GUI::FanOperate::m_min_speeds private
Referenced by FanOperate(), and decrease_fan_speeds().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/FanControl.hpp
src/slic3r/GUI/Widgets/FanControl.cpp