OrcaSlicer: src/slic3r/GUI/Printer/gstbambusrc.c File Reference
gstbambusrc.c File Reference
#include <gst/gst.h>
#include "gstbambusrc.h"
#include <stdio.h>
#include <unistd.h>
#include "BambuTunnel.h"
Macros
#define BAMBU_DYNAMIC
#define BAMBULIB(x) (_lib->x)
#define GST_CAT_DEFAULT gst_bambusrc_debug
#define gst_bambusrc_parent_class parent_class
Enumerations
enum { PROP_0 , PROP_LOCATION }
Functions
BambuLib * bambulib_get ()
GST_DEBUG_CATEGORY_STATIC (gst_bambusrc_debug)
static void gst_bambusrc_uri_handler_init (gpointer g_iface, gpointer iface_data)
static void gst_bambusrc_finalize (GObject *gobject)
static void gst_bambusrc_dispose (GObject *gobject)
static void gst_bambusrc_set_property (GObject *object, guint prop_id, const GValue *value, GParamSpec *pspec)
static void gst_bambusrc_get_property (GObject *object, guint prop_id, GValue *value, GParamSpec *pspec)
static GstStateChangeReturn gst_bambusrc_change_state (GstElement *element, GstStateChange transition)
static GstFlowReturn gst_bambusrc_create (GstPushSrc *psrc, GstBuffer **outbuf)
static gboolean gst_bambusrc_start (GstBaseSrc *bsrc)
static gboolean gst_bambusrc_stop (GstBaseSrc *bsrc)
static gboolean gst_bambusrc_is_seekable (GstBaseSrc *bsrc)
static gboolean gst_bambusrc_query (GstBaseSrc *bsrc, GstQuery *query)
static gboolean gst_bambusrc_unlock (GstBaseSrc *bsrc)
static gboolean gst_bambusrc_unlock_stop (GstBaseSrc *bsrc)
static gboolean gst_bambusrc_set_location (GstBambuSrc *src, const gchar *uri, GError **error)
G_DEFINE_TYPE_WITH_CODE (GstBambuSrc, gst_bambusrc, GST_TYPE_PUSH_SRC, G_IMPLEMENT_INTERFACE(GST_TYPE_URI_HANDLER, gst_bambusrc_uri_handler_init))
static void gst_bambusrc_class_init (GstBambuSrcClass *klass)
static void gst_bambusrc_reset (GstBambuSrc *src)
static void gst_bambusrc_init (GstBambuSrc *src)
static void _log (void *ctx, int lvl, const char *msg)
static GstURIType gst_bambusrc_uri_get_type (GType type)
static const gchar *const * gst_bambusrc_uri_get_protocols (GType type)
static gchar * gst_bambusrc_uri_get_uri (GstURIHandler *handler)
static gboolean gst_bambusrc_uri_set_uri (GstURIHandler *handler, const gchar *uri, GError **error)
static gboolean gstbambusrc_init (GstPlugin *plugin)
void gstbambusrc_register ()
Variables
BambuLib * _lib = NULL
static GstStaticPadTemplate srctemplate
int gst_bambu_last_error = 0
Macro Definition Documentation
BAMBU_DYNAMIC
#define BAMBU_DYNAMIC
BAMBULIB
#define BAMBULIB (x) (_lib->x)
gst_bambusrc_parent_class
#define gst_bambusrc_parent_class parent_class
GST_CAT_DEFAULT
#define GST_CAT_DEFAULT gst_bambusrc_debug
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
PROP_0
PROP_LOCATION
{
  PROP_0,
  PROP_LOCATION,
};
Function Documentation
_log()
static void _log (void * ctx, int lvl, const char * msg) static
{
  GstBambuSrc *src = (GstBambuSrc *) ctx;
  GST_DEBUG_OBJECT(src, "bambu: %s", msg);
  BAMBULIB(Bambu_FreeLogMsg)(msg);
}
References Bambu_FreeLogMsg(), and BAMBULIB.
Referenced by gst_bambusrc_start().
bambulib_get()
BambuLib * bambulib_get ()
{
    return &StaticBambuLib::get();
}
References StaticBambuLib::get().
Referenced by gst_bambusrc_start().
G_DEFINE_TYPE_WITH_CODE()
G_DEFINE_TYPE_WITH_CODE (GstBambuSrc , gst_bambusrc , GST_TYPE_PUSH_SRC , G_IMPLEMENT_INTERFACE(GST_TYPE_URI_HANDLER, gst_bambusrc_uri_handler_init))
gst_bambusrc_change_state()
static GstStateChangeReturn gst_bambusrc_change_state (GstElement * element, GstStateChange transition) static
{
  GstStateChangeReturn ret;
  GstBambuSrc *src;
  src = GST_BAMBUSRC (element);
  (void) src;
  switch (transition) {
    case GST_STATE_CHANGE_READY_TO_NULL:
      //gst_bambusrc_session_close (src);
      break;
    default:
      break;
  }
  ret = GST_ELEMENT_CLASS (parent_class)->change_state (element, transition);
  return ret;
}
References void().
Referenced by gst_bambusrc_class_init().
gst_bambusrc_class_init()
static void gst_bambusrc_class_init (GstBambuSrcClass * klass) static
{
  GObjectClass *gobject_class;
  GstElementClass *gstelement_class;
  GstBaseSrcClass *gstbasesrc_class;
  GstPushSrcClass *gstpushsrc_class;
  gobject_class = (GObjectClass *) klass;
  gstelement_class = (GstElementClass *) klass;
  gstbasesrc_class = (GstBaseSrcClass *) klass;
  gstpushsrc_class = (GstPushSrcClass *) klass;
  gobject_class->set_property = gst_bambusrc_set_property;
  gobject_class->get_property = gst_bambusrc_get_property;
  gobject_class->finalize = gst_bambusrc_finalize;
  gobject_class->dispose = gst_bambusrc_dispose;
  g_object_class_install_property (gobject_class,
      PROP_LOCATION,
      g_param_spec_string ("location", "Location",
          "URI to pass to Bambu Lab blobs", "",
          (GParamFlags)(G_PARAM_READWRITE | G_PARAM_STATIC_STRINGS)));
  gst_element_class_add_static_pad_template (gstelement_class, &srctemplate);
  gst_element_class_set_static_metadata (gstelement_class, "Bambu Lab source",
      "Source/Network",
      "Receive data as a client over the network using the proprietary Bambu Lab blobs",
      "Joshua Wise <joshua@accelerated.tech>");
  gstelement_class->change_state =
      GST_DEBUG_FUNCPTR (gst_bambusrc_change_state);
  gstbasesrc_class->start = GST_DEBUG_FUNCPTR (gst_bambusrc_start);
  gstbasesrc_class->stop = GST_DEBUG_FUNCPTR (gst_bambusrc_stop);
  gstbasesrc_class->unlock = GST_DEBUG_FUNCPTR (gst_bambusrc_unlock);
  gstbasesrc_class->unlock_stop =
      GST_DEBUG_FUNCPTR (gst_bambusrc_unlock_stop);
  gstbasesrc_class->is_seekable =
      GST_DEBUG_FUNCPTR (gst_bambusrc_is_seekable);
  gstbasesrc_class->query = GST_DEBUG_FUNCPTR (gst_bambusrc_query);
  gstpushsrc_class->create = GST_DEBUG_FUNCPTR (gst_bambusrc_create);
  GST_DEBUG_CATEGORY_INIT (gst_bambusrc_debug, "bambusrc", 0,
      "Bambu Lab src");
}
References gst_bambusrc_change_state(), gst_bambusrc_create(), gst_bambusrc_dispose(), gst_bambusrc_finalize(), gst_bambusrc_get_property(), gst_bambusrc_is_seekable(), gst_bambusrc_query(), gst_bambusrc_set_property(), gst_bambusrc_start(), gst_bambusrc_stop(), gst_bambusrc_unlock(), gst_bambusrc_unlock_stop(), PROP_LOCATION, and srctemplate.
gst_bambusrc_create()
static GstFlowReturn gst_bambusrc_create (GstPushSrc * psrc, GstBuffer ** outbuf) static
{
  GstBambuSrc *src;
  src = GST_BAMBUSRC (psrc);
  (void) src;
  GST_DEBUG_OBJECT (src, "create()");
  int rv;
  Bambu_Sample sample;
  if (!src->tnl) {
    return GST_FLOW_ERROR;
  }
  while ((rv = BAMBULIB(Bambu_ReadSample)(src->tnl, &sample)) == Bambu_would_block) {
    GST_DEBUG_OBJECT(src, "create would block");
    usleep(33333); /* 30Hz */
  }
  if (rv == Bambu_stream_end) {
    return GST_FLOW_EOS;
  }
  if (rv != Bambu_success) {
      gst_bambu_last_error = rv;
      return GST_FLOW_ERROR;
  }
#if GLIB_CHECK_VERSION(2,68,0)
  gpointer sbuf = g_memdup2(sample.buffer, sample.size);
#else
  gpointer sbuf = g_memdup(sample.buffer, sample.size);
#endif
  *outbuf = gst_buffer_new_wrapped_full(0, sbuf, sample.size, 0, sample.size, sbuf, g_free);
  /* The NAL data already contains a timestamp (I think?), but we seem to
   * need to feed this in too -- otherwise the GStreamer pipeline gets upset
   * and starts triggering QoS events.
   */
  if (src->video_type == AVC1) {
    if (!src->sttime) {
      src->sttime = sample.decode_time * 100ULL;
    }
    GST_BUFFER_DTS(*outbuf) = sample.decode_time * 100ULL - src->sttime;
    GST_BUFFER_PTS(*outbuf) = GST_CLOCK_TIME_NONE;
    GST_BUFFER_DURATION(*outbuf) = GST_CLOCK_TIME_NONE;
  }
  else {
    if (!src->sttime) {
      //only available from 1.18
      //src->sttime = gst_element_get_current_clock_time((GstElement *)psrc);
      src->sttime = gst_clock_get_time(((GstElement *)psrc)->clock);
      //if (GST_CLOCK_TIME_NONE == src->sttime)
      //  src->sttime
      GST_DEBUG_OBJECT(src,
        "sttime init to %lu.",
        src->sttime);
    }
    //GST_BUFFER_DTS(*outbuf) = gst_element_get_current_clock_time((GstElement *)psrc) - src->sttime;
    GST_BUFFER_DTS(*outbuf) = gst_clock_get_time(((GstElement *)psrc)->clock) - src->sttime;
    GST_BUFFER_PTS(*outbuf) = GST_CLOCK_TIME_NONE;
    GST_BUFFER_DURATION(*outbuf) = GST_CLOCK_TIME_NONE;
  }
  GST_DEBUG_OBJECT(src,
    "sttime:%lu, DTS:%lu, PTS: %lu~",
    src->sttime, GST_BUFFER_DTS(*outbuf), GST_BUFFER_PTS(*outbuf));
  return GST_FLOW_OK;
}
References AVC1, Bambu_ReadSample(), Bambu_stream_end, Bambu_success, Bambu_would_block, BAMBULIB, __Bambu_Sample::buffer, __Bambu_Sample::decode_time, gst_bambu_last_error, __Bambu_Sample::size, and void().
Referenced by gst_bambusrc_class_init().
gst_bambusrc_dispose()
static void gst_bambusrc_dispose (GObject * gobject) static
{
  GstBambuSrc *src = GST_BAMBUSRC (gobject);
  GST_DEBUG_OBJECT (src, "dispose");
  G_OBJECT_CLASS (parent_class)->dispose (gobject);
}
Referenced by gst_bambusrc_class_init().
gst_bambusrc_finalize()
static void gst_bambusrc_finalize (GObject * gobject) static
{
  GstBambuSrc *src = GST_BAMBUSRC (gobject);
  GST_DEBUG_OBJECT (src, "finalize");
  g_free (src->location);
  if (src->tnl) {
    BAMBULIB(Bambu_Close)(src->tnl);
    BAMBULIB(Bambu_Destroy)(src->tnl);
  }
  G_OBJECT_CLASS (parent_class)->finalize (gobject);
}
References Bambu_Close(), Bambu_Destroy(), and BAMBULIB.
Referenced by gst_bambusrc_class_init().
gst_bambusrc_get_property()
static void gst_bambusrc_get_property (GObject * object, guint prop_id, GValue * value, GParamSpec * pspec) static
{
  GstBambuSrc *src = GST_BAMBUSRC (object);
  switch (prop_id) {
    case PROP_LOCATION:
      g_value_set_string (value, src->location);
      break;
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
  }
}
References PROP_LOCATION.
Referenced by gst_bambusrc_class_init().
gst_bambusrc_init()
static void gst_bambusrc_init (GstBambuSrc * src) static
{
  src->location = NULL;
  src->tnl = NULL;
  gst_base_src_set_automatic_eos (GST_BASE_SRC (src), FALSE);
  gst_base_src_set_live(GST_BASE_SRC(src), TRUE);
  gst_bambusrc_reset (src);
}
References FALSE, gst_bambusrc_reset(), NULL, and TRUE.
gst_bambusrc_is_seekable()
static gboolean gst_bambusrc_is_seekable (GstBaseSrc * bsrc) static
{
  GstBambuSrc *src = GST_BAMBUSRC (bsrc);
  (void) src;
  return FALSE;
}
References FALSE, and void().
Referenced by gst_bambusrc_class_init().
gst_bambusrc_query()
static gboolean gst_bambusrc_query (GstBaseSrc * bsrc, GstQuery * query) static
{
  GstBambuSrc *src = GST_BAMBUSRC (bsrc);
  gboolean ret;
  GstSchedulingFlags flags;
  gint minsize, maxsize, align;
  switch (GST_QUERY_TYPE (query)) {
    case GST_QUERY_URI:
      gst_query_set_uri (query, src->location);
      ret = TRUE;
      break;
    default:
      ret = FALSE;
      break;
  }
  if (!ret)
    ret = GST_BASE_SRC_CLASS (parent_class)->query (bsrc, query);
  switch (GST_QUERY_TYPE (query)) {
    case GST_QUERY_SCHEDULING:
      gst_query_parse_scheduling (query, &flags, &minsize, &maxsize, &align);
      flags = (GstSchedulingFlags)((int)flags | (int)GST_SCHEDULING_FLAG_SEQUENTIAL);
      gst_query_set_scheduling (query, flags, minsize, maxsize, align);
      break;
    default:
      break;
  }
  return ret;
}
References FALSE, int, and TRUE.
Referenced by gst_bambusrc_class_init().
gst_bambusrc_reset()
static void gst_bambusrc_reset (GstBambuSrc * src) static
{
  gst_caps_replace (&src->src_caps, NULL);
  if (src->tnl) {
    BAMBULIB(Bambu_Close)(src->tnl);
    BAMBULIB(Bambu_Destroy)(src->tnl);
    src->tnl = NULL;
  }
}
References Bambu_Close(), Bambu_Destroy(), BAMBULIB, and NULL.
Referenced by gst_bambusrc_init().
gst_bambusrc_set_location()
static gboolean gst_bambusrc_set_location (GstBambuSrc * src, const gchar * uri, GError ** error) static
{
  if (src->location) {
    g_free (src->location);
    src->location = NULL;
  }
  if (uri == NULL)
    return FALSE;
  src->location = g_strdup (uri);
  return TRUE;
}
References FALSE, NULL, and TRUE.
Referenced by gst_bambusrc_set_property(), and gst_bambusrc_uri_set_uri().
gst_bambusrc_set_property()
static void gst_bambusrc_set_property (GObject * object, guint prop_id, const GValue * value, GParamSpec * pspec) static
{
  GstBambuSrc *src = GST_BAMBUSRC (object);
  switch (prop_id) {
    case PROP_LOCATION:
    {
      const gchar *location;
      location = g_value_get_string (value);
      if (location == NULL) {
        GST_WARNING ("location property cannot be NULL");
        goto done;
      }
      if (!gst_bambusrc_set_location (src, location, NULL)) {
        GST_WARNING ("badly formatted location");
        goto done;
      }
      break;
    }
    default:
      G_OBJECT_WARN_INVALID_PROPERTY_ID (object, prop_id, pspec);
      break;
  }
done:
  return;
}
References gst_bambusrc_set_location(), NULL, and PROP_LOCATION.
Referenced by gst_bambusrc_class_init().
gst_bambusrc_start()
static gboolean gst_bambusrc_start (GstBaseSrc * bsrc) static
{
  GstBambuSrc *src = GST_BAMBUSRC (bsrc);
  GST_DEBUG_OBJECT (src, "start(\"%s\")", src->location);
  if (src->tnl) {
    BAMBULIB(Bambu_Close)(src->tnl);
    BAMBULIB(Bambu_Destroy)(src->tnl);
    src->tnl = NULL;
  }
#ifdef BAMBU_DYNAMIC
  if (!_lib) {
    _lib = bambulib_get();
    if (!_lib->Bambu_Open) {
      return FALSE;
    }
  }
#endif
  if (BAMBULIB(Bambu_Create)(&src->tnl, src->location) != Bambu_success) {
    return FALSE;
  }
  BAMBULIB(Bambu_SetLogger)(src->tnl, _log, (void *)src);
  if (BAMBULIB(Bambu_Open)(src->tnl) != Bambu_success) {
    BAMBULIB(Bambu_Destroy)(src->tnl);
    src->tnl = NULL;
    return FALSE;
  }
  int rv, n = 0;
  while ((rv = BAMBULIB(Bambu_StartStream)(src->tnl, 1 /* video */)) == Bambu_would_block) {
    usleep(100000);
  }
  if (rv != Bambu_success) {
    BAMBULIB(Bambu_Close)(src->tnl);
    BAMBULIB(Bambu_Destroy)(src->tnl);
    src->tnl = NULL;
    gst_bambu_last_error = rv;
    return FALSE;
  }
  src->video_type = AVC1;
  n = BAMBULIB(Bambu_GetStreamCount)(src->tnl);
  GST_INFO_OBJECT (src, "Bambu_GetStreamCount returned stream count=%d",n);
  for (int i = 0; i < n; ++i) {
    Bambu_StreamInfo info;
    BAMBULIB(Bambu_GetStreamInfo)(src->tnl, i, &info);
    GST_INFO_OBJECT (src, "stream %d type=%d, sub_type=%d", i, info.type, info.sub_type);
    if (info.type == VIDE) {
      src->video_type = info.sub_type;
      GST_INFO_OBJECT (src, " width %d height=%d, frame_rate=%d",
          info.format.video.width, info.format.video.height, info.format.video.frame_rate);
    }
  }
  src->sttime = 0;
  return TRUE;
}
References _lib, _log(), AVC1, Bambu_Close(), Bambu_Create(), Bambu_Destroy(), Bambu_GetStreamCount(), Bambu_GetStreamInfo(), Bambu_Open(), Bambu_SetLogger(), Bambu_StartStream(), Bambu_success, Bambu_would_block, BAMBULIB, bambulib_get(), FALSE, __Bambu_StreamInfo::format, gst_bambu_last_error, n, NULL, __Bambu_StreamInfo::sub_type, TRUE, __Bambu_StreamInfo::type, and VIDE.
Referenced by gst_bambusrc_class_init().
gst_bambusrc_stop()
static gboolean gst_bambusrc_stop (GstBaseSrc * bsrc) static
{
  GstBambuSrc *src;
  src = GST_BAMBUSRC (bsrc);
  GST_DEBUG_OBJECT (src, "stop()");
  if (src->tnl) {
    BAMBULIB(Bambu_Close)(src->tnl);
    BAMBULIB(Bambu_Destroy)(src->tnl);
    src->tnl = NULL;
  }
  return TRUE;
}
References Bambu_Close(), Bambu_Destroy(), BAMBULIB, NULL, and TRUE.
Referenced by gst_bambusrc_class_init().
gst_bambusrc_unlock()
static gboolean gst_bambusrc_unlock (GstBaseSrc * bsrc) static
{
  GstBambuSrc *src;
  src = GST_BAMBUSRC (bsrc);
  GST_DEBUG_OBJECT (src, "unlock()");
  return TRUE;
}
References TRUE.
Referenced by gst_bambusrc_class_init().
gst_bambusrc_unlock_stop()
static gboolean gst_bambusrc_unlock_stop (GstBaseSrc * bsrc) static
{
  GstBambuSrc *src;
  src = GST_BAMBUSRC (bsrc);
  GST_DEBUG_OBJECT (src, "unlock_stop()");
  return TRUE;
}
References TRUE.
Referenced by gst_bambusrc_class_init().
gst_bambusrc_uri_get_protocols()
static const gchar *const * gst_bambusrc_uri_get_protocols (GType type) static
{
  static const gchar *protocols[] = { "bambu", NULL };
  return protocols;
}
References NULL.
Referenced by gst_bambusrc_uri_handler_init().
gst_bambusrc_uri_get_type()
static GstURIType gst_bambusrc_uri_get_type (GType type) static
{
  return GST_URI_SRC;
}
Referenced by gst_bambusrc_uri_handler_init().
gst_bambusrc_uri_get_uri()
static gchar * gst_bambusrc_uri_get_uri (GstURIHandler * handler) static
{
  GstBambuSrc *src = GST_BAMBUSRC (handler);
  /* FIXME: make thread-safe */
  return g_strdup (src->location);
}
Referenced by gst_bambusrc_uri_handler_init().
gst_bambusrc_uri_handler_init()
static void gst_bambusrc_uri_handler_init (gpointer g_iface, gpointer iface_data) static
{
  GstURIHandlerInterface *iface = (GstURIHandlerInterface *) g_iface;
  iface->get_type = gst_bambusrc_uri_get_type;
  iface->get_protocols = gst_bambusrc_uri_get_protocols;
  iface->get_uri = gst_bambusrc_uri_get_uri;
  iface->set_uri = gst_bambusrc_uri_set_uri;
}
References gst_bambusrc_uri_get_protocols(), gst_bambusrc_uri_get_type(), gst_bambusrc_uri_get_uri(), and gst_bambusrc_uri_set_uri().
gst_bambusrc_uri_set_uri()
static gboolean gst_bambusrc_uri_set_uri (GstURIHandler * handler, const gchar * uri, GError ** error) static
{
  GstBambuSrc *src = GST_BAMBUSRC (handler);
  return gst_bambusrc_set_location (src, uri, error);
}
References error, and gst_bambusrc_set_location().
Referenced by gst_bambusrc_uri_handler_init().
GST_DEBUG_CATEGORY_STATIC()
GST_DEBUG_CATEGORY_STATIC (gst_bambusrc_debug)
gstbambusrc_init()
static gboolean gstbambusrc_init (GstPlugin * plugin) static
{
  return gst_element_register(plugin, "bambusrc", GST_RANK_PRIMARY, GST_TYPE_BAMBUSRC);
}
References GST_TYPE_BAMBUSRC.
Referenced by gstbambusrc_register().
gstbambusrc_register()
void gstbambusrc_register ()
{
  static int did_register = 0;
  if (did_register)
    return;
  did_register = 1;
  gst_plugin_register_static(GST_VERSION_MAJOR, GST_VERSION_MINOR, "bambusrc", "Bambu Lab source", gstbambusrc_init, "0.0.1", "GPL", "OrcaSlicer", "OrcaSlicer", "https://github.com/bambulab/OrcaSlicer");
}
References gstbambusrc_init().
Referenced by wxMediaCtrl2::wxMediaCtrl2().
Variable Documentation
_lib
BambuLib* _lib = NULL
Referenced by gst_bambusrc_start().
gst_bambu_last_error
int gst_bambu_last_error = 0
Referenced by wxMediaCtrl2::GetLastError(), gst_bambusrc_create(), and gst_bambusrc_start().
srctemplate
GstStaticPadTemplate srctemplate static
Initial value:
= GST_STATIC_PAD_TEMPLATE ("src",
    GST_PAD_SRC,
    GST_PAD_ALWAYS,
    GST_STATIC_CAPS_ANY)
Referenced by gst_bambusrc_class_init().