OrcaSlicer: Slic3r::ExtrusionLoop Class Reference
Slic3r::ExtrusionLoop Class Reference
#include <src/libslic3r/ExtrusionEntity.hpp>
Classes
struct ClosestPathPoint
Public Member Functions
ExtrusionLoop (ExtrusionLoopRole role=elrDefault)
ExtrusionLoop (const ExtrusionPaths &paths, ExtrusionLoopRole role=elrDefault)
ExtrusionLoop (ExtrusionPaths &&paths, ExtrusionLoopRole role=elrDefault)
ExtrusionLoop (const ExtrusionPath &path, ExtrusionLoopRole role=elrDefault)
ExtrusionLoop (const ExtrusionPath &&path, ExtrusionLoopRole role=elrDefault)
bool is_loop () const override
bool can_reverse () const override
ExtrusionEntity * clone () const override
ExtrusionEntity * clone_move () override
bool make_clockwise ()
bool make_counter_clockwise ()
bool is_clockwise ()
bool is_counter_clockwise ()
void reverse () override
const Point & first_point () const override
const Point & last_point () const override
Polygon polygon () const
double length () const override
bool split_at_vertex (const Point &point, const double scaled_epsilon=scaled< double >(0.001))
void split_at (const Point &point, bool prefer_non_overhang, const double scaled_epsilon=scaled< double >(0.001))
ClosestPathPoint get_closest_path_and_point (const Point &point, bool prefer_non_overhang) const
void clip_end (double distance, ExtrusionPaths *paths) const
bool has_overhang_point (const Point &point) const
ExtrusionRole role () const override
ExtrusionLoopRole loop_role () const
void set_loop_role (ExtrusionLoopRole role)
void polygons_covered_by_width (Polygons &out, const float scaled_epsilon) const override
void polygons_covered_by_spacing (Polygons &out, const float scaled_epsilon) const override
Polygons polygons_covered_by_width (const float scaled_epsilon=0.f) const
Polygons polygons_covered_by_spacing (const float scaled_epsilon=0.f) const
double min_mm3_per_mm () const override
Polyline as_polyline () const override
void collect_polylines (Polylines &dst) const override
void collect_points (Points &dst) const override
double total_volume () const override
bool validate () const
virtual bool is_collection () const
virtual bool can_sort () const
virtual void set_reverse ()
virtual Polylines as_polylines () const
Static Public Member Functions
static std::string role_to_string (ExtrusionRole role)
static ExtrusionRole string_to_role (const std::string_view role)
Public Attributes
ExtrusionPaths paths
Private Attributes
ExtrusionLoopRole m_loop_role
Detailed Description
Class Documentation
Slic3r::ExtrusionLoop::ClosestPathPoint
struct Slic3r::ExtrusionLoop::ClosestPathPoint
Class Members
Point foot_pt
size_t path_idx
size_t segment_idx
Constructor & Destructor Documentation
ExtrusionLoop() [1/5]
Slic3r::ExtrusionLoop::ExtrusionLoop (ExtrusionLoopRole role = elrDefault) inline
: m_loop_role(role) {}
ExtrusionLoop() [2/5]
Slic3r::ExtrusionLoop::ExtrusionLoop (const ExtrusionPaths & paths, ExtrusionLoopRole role = elrDefault) inline
: paths(paths), m_loop_role(role) {}
ExtrusionLoop() [3/5]
Slic3r::ExtrusionLoop::ExtrusionLoop (ExtrusionPaths && paths, ExtrusionLoopRole role = elrDefault) inline
: paths(std::move(paths)), m_loop_role(role) {}
ExtrusionLoop() [4/5]
Slic3r::ExtrusionLoop::ExtrusionLoop (const ExtrusionPath & path, ExtrusionLoopRole role = elrDefault) inline
                                                                                  : m_loop_role(role)
        { this->paths.push_back(path); }
ExtrusionLoop() [5/5]
Slic3r::ExtrusionLoop::ExtrusionLoop (const ExtrusionPath && path, ExtrusionLoopRole role = elrDefault) inline
                                                                                   : m_loop_role(role)
        { this->paths.emplace_back(std::move(path)); }
Member Function Documentation
as_polyline()
Polyline Slic3r::ExtrusionLoop::as_polyline () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->polygon().split_at_first_point(); }
References polygon(), and Slic3r::Polygon::split_at_first_point().
Referenced by Slic3r::_make_loops(), and collect_polylines().
as_polylines()
virtual Polylines Slic3r::ExtrusionEntity::as_polylines () const inline virtual inherited
{ Polylines dst; this->collect_polylines(dst); return dst; }
References Slic3r::ExtrusionEntity::collect_polylines().
Referenced by Slic3r::SupportMaterialInternal::remove_bridges_from_contacts().
can_reverse()
bool Slic3r::ExtrusionLoop::can_reverse () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ return false; }
can_sort()
virtual bool Slic3r::ExtrusionEntity::can_sort () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return true; }//BBS: only used in ExtrusionEntityCollection
clip_end()
void Slic3r::ExtrusionLoop::clip_end (double distance, ExtrusionPaths * paths) const
{
    *paths = this->paths;
    while (distance > 0 && !paths->empty()) {
        ExtrusionPath &last = paths->back();
        double len = last.length();
        if (len <= distance) {
            paths->pop_back();
            distance -= len;
        } else {
            last.polyline.clip_end(distance);
            break;
        }
    }
}
References Slic3r::Polyline::clip_end(), Slic3r::ExtrusionPath::length(), paths, and Slic3r::ExtrusionPath::polyline.
clone()
ExtrusionEntity * Slic3r::ExtrusionLoop::clone () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return new ExtrusionLoop (*this); }
clone_move()
ExtrusionEntity * Slic3r::ExtrusionLoop::clone_move () inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return new ExtrusionLoop(std::move(*this)); }
collect_points()
void Slic3r::ExtrusionLoop::collect_points (Points & dst) const inline override virtual
Implements Slic3r::ExtrusionEntity.
{
        size_t n = std::accumulate(paths.begin(), paths.end(), 0, [](const size_t n, const ExtrusionPath &p){ return n + p.polyline.size(); });
        dst.reserve(dst.size() + n);
        for (const ExtrusionPath &p : this->paths)
            append(dst, p.polyline.points);
    }
References Slic3r::append(), n, paths, Slic3r::MultiPoint::points, and Slic3r::ExtrusionPath::polyline.
collect_polylines()
void Slic3r::ExtrusionLoop::collect_polylines (Polylines & dst) const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ Polyline pl = this->as_polyline(); if (! pl.empty()) dst.emplace_back(std::move(pl)); }
References as_polyline(), and Slic3r::MultiPoint::empty().
first_point()
const Point & Slic3r::ExtrusionLoop::first_point () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->paths.front().polyline.points.front(); }
Referenced by last_point(), and validate().
get_closest_path_and_point()
ExtrusionLoop::ClosestPathPoint Slic3r::ExtrusionLoop::get_closest_path_and_point (const Point & point, bool prefer_non_overhang) const
{
    // Find the closest path and closest point belonging to that path. Avoid overhangs, if asked for.
    ClosestPathPoint out{0, 0};
    double           min2 = std::numeric_limits<double>::max();
    ClosestPathPoint best_non_overhang{0, 0};
    double           min2_non_overhang = std::numeric_limits<double>::max();
    for (const ExtrusionPath &path : this->paths) {
        std::pair<int, Point> foot_pt_ = foot_pt(path.polyline.points, point);
        double                d2       = (foot_pt_.second - point).cast<double>().squaredNorm();
        if (d2 < min2) {
            out.foot_pt     = foot_pt_.second;
            out.path_idx    = &path - &this->paths.front();
            out.segment_idx = foot_pt_.first;
            min2            = d2;
        }
        if (prefer_non_overhang && !is_bridge(path.role()) && d2 < min2_non_overhang) {
            best_non_overhang.foot_pt     = foot_pt_.second;
            best_non_overhang.path_idx    = &path - &this->paths.front();
            best_non_overhang.segment_idx = foot_pt_.first;
            min2_non_overhang             = d2;
        }
    }
    if (prefer_non_overhang && min2_non_overhang != std::numeric_limits<double>::max())
        // Only apply the non-overhang point if there is one.
        out = best_non_overhang;
    return out;
}
References Slic3r::foot_pt(), Slic3r::is_bridge(), out, and paths.
Referenced by split_at().
has_overhang_point()
bool Slic3r::ExtrusionLoop::has_overhang_point (const Point & point) const
{
    for (const ExtrusionPath &path : this->paths) {
        int pos = path.polyline.find_point(point);
        if (pos != -1) {
            // point belongs to this path
            // we consider it overhang only if it's not an endpoint
            return (is_bridge(path.role()) && pos > 0 && pos != (int)(path.polyline.points.size())-1);
        }
    }
    return false;
}
References int, Slic3r::is_bridge(), and paths.
is_clockwise()
bool Slic3r::ExtrusionLoop::is_clockwise () inline
{ return this->polygon().is_clockwise(); }
References Slic3r::Polygon::is_clockwise(), and polygon().
is_collection()
virtual bool Slic3r::ExtrusionEntity::is_collection () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionEntityCollection.
{ return false; }
is_counter_clockwise()
bool Slic3r::ExtrusionLoop::is_counter_clockwise () inline
{ return this->polygon().is_counter_clockwise(); }
References Slic3r::Polygon::is_counter_clockwise(), and polygon().
is_loop()
bool Slic3r::ExtrusionLoop::is_loop () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ return true; }
last_point()
const Point & Slic3r::ExtrusionLoop::last_point () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ assert(this->first_point() == this->paths.back().polyline.points.back()); return this->first_point(); }
References first_point().
length()
double Slic3r::ExtrusionLoop::length () const override virtual
Implements Slic3r::ExtrusionEntity.
{
    double len = 0;
    for (const ExtrusionPath &path : this->paths)
        len += path.polyline.length();
    return len;
}
References paths.
loop_role()
ExtrusionLoopRole Slic3r::ExtrusionLoop::loop_role () const inline
{ return m_loop_role; }
References m_loop_role.
make_clockwise()
bool Slic3r::ExtrusionLoop::make_clockwise ()
{
    bool was_ccw = this->polygon().is_counter_clockwise();
    if (was_ccw) this->reverse();
    return was_ccw;
}
References Slic3r::Polygon::is_counter_clockwise(), polygon(), and reverse().
Referenced by Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
make_counter_clockwise()
bool Slic3r::ExtrusionLoop::make_counter_clockwise ()
{
    bool was_cw = this->polygon().is_clockwise();
    if (was_cw) this->reverse();
    return was_cw;
}
References Slic3r::Polygon::is_clockwise(), polygon(), and reverse().
Referenced by Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
min_mm3_per_mm()
double Slic3r::ExtrusionLoop::min_mm3_per_mm () const override virtual
Implements Slic3r::ExtrusionEntity.
{
    double min_mm3_per_mm = std::numeric_limits<double>::max();
    for (const ExtrusionPath &path : this->paths)
        min_mm3_per_mm = std::min(min_mm3_per_mm, path.mm3_per_mm);
    return min_mm3_per_mm;
}
References min_mm3_per_mm(), and paths.
Referenced by min_mm3_per_mm().
polygon()
Polygon Slic3r::ExtrusionLoop::polygon () const
{
    Polygon polygon;
    for (const ExtrusionPath &path : this->paths) {
        // for each polyline, append all points except the last one (because it coincides with the first one of the next polyline)
        polygon.points.insert(polygon.points.end(), path.polyline.points.begin(), path.polyline.points.end()-1);
    }
    return polygon;
}
References paths, Slic3r::MultiPoint::points, and polygon().
Referenced by as_polyline(), is_clockwise(), is_counter_clockwise(), make_clockwise(), make_counter_clockwise(), and polygon().
polygons_covered_by_spacing() [1/2]
Polygons Slic3r::ExtrusionLoop::polygons_covered_by_spacing (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_spacing(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_spacing().
polygons_covered_by_spacing() [2/2]
void Slic3r::ExtrusionLoop::polygons_covered_by_spacing (Polygons & out, const float scaled_epsilon) const override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (const ExtrusionPath &path : this->paths)
        path.polygons_covered_by_spacing(out, scaled_epsilon);
}
References out, and paths.
Referenced by polygons_covered_by_spacing().
polygons_covered_by_width() [1/2]
Polygons Slic3r::ExtrusionLoop::polygons_covered_by_width (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_width(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_width().
polygons_covered_by_width() [2/2]
void Slic3r::ExtrusionLoop::polygons_covered_by_width (Polygons & out, const float scaled_epsilon) const override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (const ExtrusionPath &path : this->paths)
        path.polygons_covered_by_width(out, scaled_epsilon);
}
References out, and paths.
Referenced by polygons_covered_by_width().
reverse()
void Slic3r::ExtrusionLoop::reverse () override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (ExtrusionPath &path : this->paths)
        path.reverse();
    std::reverse(this->paths.begin(), this->paths.end());
}
References paths.
Referenced by make_clockwise(), and make_counter_clockwise().
role()
ExtrusionRole Slic3r::ExtrusionLoop::role () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->paths.empty() ? erNone : this->paths.front().role(); }
References Slic3r::erNone.
Referenced by set_loop_role().
role_to_string()
std::string Slic3r::ExtrusionEntity::role_to_string (ExtrusionRole role) static inherited
{
    switch (role) {
        case erNone                         : return L("Undefined");
        case erPerimeter                    : return L("Inner wall");
        case erExternalPerimeter            : return L("Outer wall");
        case erOverhangPerimeter            : return L("Overhang wall");
        case erInternalInfill               : return L("Sparse infill");
        case erSolidInfill                  : return L("Internal solid infill");
        case erTopSolidInfill               : return L("Top surface");
        case erBottomSurface                : return L("Bottom surface");
        case erIroning                      : return L("Ironing");
        case erBridgeInfill                 : return L("Bridge");
        case erInternalBridgeInfill         : return L("Internal Bridge");
        case erGapFill                      : return L("Gap infill");
        case erSkirt                        : return ("Skirt");
        case erBrim                         : return ("Brim");
        case erSupportMaterial              : return L("Support");
        case erSupportMaterialInterface     : return L("Support interface");
        case erSupportTransition            : return L("Support transition");
        case erWipeTower                    : return L("Prime tower");
        case erCustom                       : return L("Custom");
        case erMixed                        : return L("Multiple");
        default                             : assert(false);
    }
    return "";
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and Slic3r::ExtrusionEntity::role().
Referenced by Slic3r::WipeTowerWriter::WipeTowerWriter(), Slic3r::GCode::_do_export(), and Slic3r::GUI::GCodeViewer::render_legend().
set_loop_role()
void Slic3r::ExtrusionLoop::set_loop_role (ExtrusionLoopRole role) inline
{    m_loop_role = role; }
References m_loop_role, and role().
set_reverse()
virtual void Slic3r::ExtrusionEntity::set_reverse () inline virtual inherited
Reimplemented in Slic3r::ExtrusionPath, Slic3r::ExtrusionMultiPath, and Slic3r::ExtrusionEntityCollection.
{}
split_at()
void Slic3r::ExtrusionLoop::split_at (const Point & point, bool prefer_non_overhang, const double scaled_epsilon = scaled<double>(0.001))
{
    if (this->paths.empty())
        return;
    auto [path_idx, segment_idx, p] = get_closest_path_and_point(point, prefer_non_overhang);
    // Snap p to start or end of segment_idx if closer than scaled_epsilon.
    {
        const Point *p1 = this->paths[path_idx].polyline.points.data() + segment_idx;
        const Point *p2 = p1;
        ++p2;
        double       d2_1 = (point - *p1).cast<double>().squaredNorm();
        double       d2_2 = (point - *p2).cast<double>().squaredNorm();
        const double thr2 = scaled_epsilon * scaled_epsilon;
        if (d2_1 < d2_2) {
            if (d2_1 < thr2) p = *p1;
        } else {
            if (d2_2 < thr2) p = *p2;
        }
    }
    // now split path_idx in two parts
    const ExtrusionPath &path = this->paths[path_idx];
    ExtrusionPath p1(path.overhang_degree, path.curve_degree, path.role(), path.mm3_per_mm, path.width, path.height);
    ExtrusionPath p2(path.overhang_degree, path.curve_degree, path.role(), path.mm3_per_mm, path.width, path.height);
    path.polyline.split_at(p, &p1.polyline, &p2.polyline);
    if (this->paths.size() == 1) {
        if (!p1.polyline.is_valid()) {
            std::swap(this->paths.front().polyline.points, p2.polyline.points);
            std::swap(this->paths.front().polyline.fitting_result, p2.polyline.fitting_result);
        }
        else if (!p2.polyline.is_valid()) {
            std::swap(this->paths.front().polyline.points, p1.polyline.points);
            std::swap(this->paths.front().polyline.fitting_result, p1.polyline.fitting_result);
        }
        else {
            p2.polyline.append(std::move(p1.polyline));
            std::swap(this->paths.front().polyline.points, p2.polyline.points);
            std::swap(this->paths.front().polyline.fitting_result, p2.polyline.fitting_result);
        }
    } else {
        // install the two paths
        this->paths.erase(this->paths.begin() + path_idx);
        if (p2.polyline.is_valid()) this->paths.insert(this->paths.begin() + path_idx, p2);
        if (p1.polyline.is_valid()) this->paths.insert(this->paths.begin() + path_idx, p1);
    }
    // split at the new vertex
    this->split_at_vertex(p);
}
References Slic3r::Polyline::append(), Slic3r::ExtrusionPath::curve_degree, Slic3r::Polyline::fitting_result, get_closest_path_and_point(), Slic3r::ExtrusionPath::height, Slic3r::MultiPoint::is_valid(), Slic3r::ExtrusionPath::mm3_per_mm, Slic3r::ExtrusionPath::overhang_degree, paths, Slic3r::MultiPoint::points, Slic3r::ExtrusionPath::polyline, Slic3r::ExtrusionPath::role(), Slic3r::Polyline::split_at(), split_at_vertex(), and Slic3r::ExtrusionPath::width.
Referenced by Slic3r::_make_loops().
split_at_vertex()
bool Slic3r::ExtrusionLoop::split_at_vertex (const Point & point, const double scaled_epsilon = scaled<double>(0.001))
{
    for (ExtrusionPaths::iterator path = this->paths.begin(); path != this->paths.end(); ++path) {
        if (int idx = path->polyline.find_point(point, scaled_epsilon); idx != -1) {
            if (this->paths.size() == 1) {
                // just change the order of points
                Polyline p1, p2;
                path->polyline.split_at_index(idx, &p1, &p2);
                if (p1.is_valid() && p2.is_valid()) {
                    p2.append(std::move(p1));
                    std::swap(path->polyline.points, p2.points);
                    std::swap(path->polyline.fitting_result, p2.fitting_result);
                }
            } else {
                // new paths list starts with the second half of current path
                ExtrusionPaths new_paths;
                Polyline p1, p2;
                path->polyline.split_at_index(idx, &p1, &p2);
                new_paths.reserve(this->paths.size() + 1);
                {
                    ExtrusionPath p = *path;
                    std::swap(p.polyline.points, p2.points);
                    std::swap(p.polyline.fitting_result, p2.fitting_result);
                    if (p.polyline.is_valid()) new_paths.push_back(p);
                }
                // then we add all paths until the end of current path list
                new_paths.insert(new_paths.end(), path+1, this->paths.end());  // not including this path
                // then we add all paths since the beginning of current list up to the previous one
                new_paths.insert(new_paths.end(), this->paths.begin(), path);  // not including this path
                // finally we add the first half of current path
                {
                    ExtrusionPath p = *path;
                    std::swap(p.polyline.points, p1.points);
                    std::swap(p.polyline.fitting_result, p1.fitting_result);
                    if (p.polyline.is_valid()) new_paths.push_back(p);
                }
                // we can now override the old path list with the new one and stop looping
                std::swap(this->paths, new_paths);
            }
            return true;
        }
    }
    return false;
}
References Slic3r::Polyline::append(), Slic3r::Polyline::fitting_result, Slic3r::MultiPoint::is_valid(), paths, Slic3r::MultiPoint::points, Slic3r::ExtrusionPath::polyline, and Slic3r::Polyline::split_at_index().
Referenced by split_at().
string_to_role()
ExtrusionRole Slic3r::ExtrusionEntity::string_to_role (const std::string_view role) static inherited
{
    if (role == L("Inner wall"))
        return erPerimeter;
    else if (role == L("Outer wall"))
        return erExternalPerimeter;
    else if (role == L("Overhang wall"))
        return erOverhangPerimeter;
    else if (role == L("Sparse infill"))
        return erInternalInfill;
    else if (role == L("Internal solid infill"))
        return erSolidInfill;
    else if (role == L("Top surface"))
        return erTopSolidInfill;
    else if (role == L("Bottom surface"))
        return erBottomSurface;
    else if (role == L("Ironing"))
        return erIroning;
    else if (role == L("Bridge"))
        return erBridgeInfill;
    else if (role == L("Internal Bridge"))
        return erInternalBridgeInfill;
    else if (role == L("Gap infill"))
        return erGapFill;
    else if (role == ("Skirt"))
        return erSkirt;
    else if (role == ("Brim"))
        return erBrim;
    else if (role == L("Support"))
        return erSupportMaterial;
    else if (role == L("Support interface"))
        return erSupportMaterialInterface;
    else if (role == L("Support transition"))
        return erSupportTransition;
    else if (role == L("Prime tower"))
        return erWipeTower;
    else if (role == L("Custom"))
        return erCustom;
    else if (role == L("Multiple"))
        return erMixed;
    else
        return erNone;
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and Slic3r::ExtrusionEntity::role().
Referenced by Slic3r::FanMover::_process_gcode_line(), and Slic3r::GCodeProcessor::process_tags().
total_volume()
double Slic3r::ExtrusionLoop::total_volume () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ double volume =0.; for (const auto& path : paths) volume += path.total_volume(); return volume; }
References paths.
validate()
bool Slic3r::ExtrusionLoop::validate () const inline
{
    assert(this->first_point() == this->paths.back().polyline.points.back());
    for (size_t i = 1; i < paths.size(); ++ i)
      assert(this->paths[i - 1].polyline.points.back() == this->paths[i].polyline.points.front());
    return true;
  }
References first_point(), and paths.
Member Data Documentation
m_loop_role
ExtrusionLoopRole Slic3r::ExtrusionLoop::m_loop_role private
Referenced by loop_role(), and set_loop_role().
paths
ExtrusionPaths Slic3r::ExtrusionLoop::paths
Referenced by Slic3r::Print::_make_skirt(), clip_end(), collect_points(), Slic3r::extrusionentity_extents(), Slic3r::_3DScene::extrusionentity_to_verts(), get_closest_path_and_point(), has_overhang_point(), length(), min_mm3_per_mm(), polygon(), polygons_covered_by_spacing(), polygons_covered_by_width(), reverse(), split_at(), split_at_vertex(), total_volume(), Slic3r::traverse_extrusions(), and validate().
The documentation for this class was generated from the following files:
src/libslic3r/ExtrusionEntity.hpp
src/libslic3r/ExtrusionEntity.cpp