OrcaSlicer: Slic3r::GUI::KBShortcutsDialog Class Reference
Slic3r::GUI::KBShortcutsDialog Class Reference
#include <src/slic3r/GUI/KBShortcutsDialog.hpp>
Public Member Functions
KBShortcutsDialog ()
wxWindow * create_button (int id, wxString text)
void OnSelectTabel (wxCommandEvent &event)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Public Attributes
wxPanel * m_panel_selects
wxBoxSizer * m_sizer_right
wxSimplebook * m_simplebook
wxBoxSizer * m_sizer_body
SelectHash m_hash_selector
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
virtual void on_sys_color_changed ()
Private Types
typedef std::pair< std::string, std::string > Shortcut
typedef std::vector< Shortcut > Shortcuts
typedef std::pair< std::pair< wxString, wxString >, Shortcuts > ShortcutsItem
typedef std::vector< ShortcutsItem > ShortcutsVec
Private Member Functions
void fill_shortcuts ()
wxPanel * create_header (wxWindow *parent, const wxFont &bold_font)
wxPanel * create_page (wxWindow *parent, const ShortcutsItem &shortcuts, const wxFont &font, const wxFont &bold_font)
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
ShortcutsVec m_full_shortcuts
ScalableBitmap m_logo_bmp
wxStaticBitmap * m_header_bitmap
std::vector< wxPanel * > m_pages
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Member Typedef Documentation
Shortcut
typedef std::pair<std::string, std::string> Slic3r::GUI::KBShortcutsDialog::Shortcut private
Shortcuts
typedef std::vector<Shortcut> Slic3r::GUI::KBShortcutsDialog::Shortcuts private
ShortcutsItem
typedef std::pair<std::pair<wxString, wxString>, Shortcuts> Slic3r::GUI::KBShortcutsDialog::ShortcutsItem private
ShortcutsVec
typedef std::vector<ShortcutsItem> Slic3r::GUI::KBShortcutsDialog::ShortcutsVec private
Constructor & Destructor Documentation
KBShortcutsDialog()
Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog ()
    : DPIDialog(static_cast<wxWindow*>(wxGetApp().mainframe), wxID_ANY,_L("Keyboard Shortcuts"),
    wxDefaultPosition, wxDefaultSize, wxDEFAULT_DIALOG_STYLE)
{
    // fonts
    const wxFont& font = wxGetApp().normal_font();
    const wxFont& bold_font = wxGetApp().bold_font();
    SetFont(font);
    std::string icon_path = (boost::format("%1%/images/OrcaSlicerTitle.ico") % resources_dir()).str();
    SetIcon(wxIcon(encode_path(icon_path.c_str()), wxBITMAP_TYPE_ICO));
    this->SetSizeHints(wxDefaultSize, wxDefaultSize);
    this->SetBackgroundColour(wxColour(255, 255, 255));
    wxBoxSizer *m_sizer_top = new wxBoxSizer(wxVERTICAL);
    auto m_top_line = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    m_top_line->SetBackgroundColour(wxColour(166, 169, 170));
    m_sizer_top->Add(m_top_line, 0, wxEXPAND, 0);
    m_sizer_body = new wxBoxSizer(wxHORIZONTAL);
    m_panel_selects = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_panel_selects->SetBackgroundColour(wxColour(248, 248, 248));
    wxBoxSizer *m_sizer_left = new wxBoxSizer(wxVERTICAL);
    m_sizer_left->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(20));
    m_sizer_left->Add(create_button(0, _L("Global")), 0, wxEXPAND, 0);
    m_sizer_left->Add(create_button(1, _L("Prepare")), 0, wxEXPAND, 0);
    m_sizer_left->Add(create_button(2, _L("Toolbar")), 0, wxEXPAND, 0);
    m_sizer_left->Add(create_button(3, _L("Objects list")), 0, wxEXPAND, 0);
    m_sizer_left->Add(create_button(4, _L("Preview")), 0, wxEXPAND, 0);
    m_panel_selects->SetSizer(m_sizer_left);
    m_panel_selects->Layout();
    m_sizer_left->Fit(m_panel_selects);
    m_sizer_body->Add(m_panel_selects, 0, wxEXPAND, 0);
    m_sizer_right = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_right->Add(0, 0, 0, wxEXPAND | wxLEFT,  FromDIP(12));
    m_simplebook = new wxSimplebook(this, wxID_ANY, wxDefaultPosition, wxSize(FromDIP(870), FromDIP(500)), 0);
    m_sizer_right->Add(m_simplebook, 1, wxEXPAND, 0);
    m_sizer_body->Add(m_sizer_right, 1, wxEXPAND, 0);
    m_sizer_top->Add(m_sizer_body, 1, wxEXPAND, 0);
    fill_shortcuts();
    for (size_t i = 0; i < m_full_shortcuts.size(); ++i) {
        wxPanel *page = create_page(m_simplebook, m_full_shortcuts[i], font, bold_font);
        m_pages.push_back(page);
        m_simplebook->AddPage(page, m_full_shortcuts[i].first.first, i == 0);
    }
    Bind(EVT_PREFERENCES_SELECT_TAB, &KBShortcutsDialog::OnSelectTabel, this);
    SetSizer(m_sizer_top);
    Layout();
    Fit();
    CenterOnParent();
    // select first
    auto event = wxCommandEvent(EVT_PREFERENCES_SELECT_TAB);
    event.SetInt(0);
    event.SetEventObject(this);
    wxPostEvent(this, event);
    wxGetApp().UpdateDlgDarkUI(this);
}
References _L, create_button(), create_page(), Slic3r::encode_path(), fill_shortcuts(), m_full_shortcuts, m_pages, m_panel_selects, m_simplebook, m_sizer_body, m_sizer_right, Slic3r::GUI::DPIAware< P >::normal_font(), OnSelectTabel(), and Slic3r::resources_dir().
Member Function Documentation
create_button()
wxWindow * Slic3r::GUI::KBShortcutsDialog::create_button (int id, wxString text)
{
    auto tab_button = new wxWindow(m_panel_selects, wxID_ANY, wxDefaultPosition, wxSize( FromDIP(150),  FromDIP(28)), wxTAB_TRAVERSAL);
    wxBoxSizer *sizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add(0, 0, 0, wxEXPAND | wxLEFT, FromDIP(22));
    auto stext = new wxStaticText(tab_button, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, 0);
    stext->SetFont(::Label::Body_13);
    stext->SetForegroundColour(wxColour(38, 46, 48));
    stext->Wrap(-1);
    sizer->Add(stext, 1, wxALIGN_CENTER, 0);
    tab_button->Bind(wxEVT_LEFT_DOWN, [this, id](auto &e) {
        auto event = wxCommandEvent(EVT_PREFERENCES_SELECT_TAB);
        event.SetInt(id);
        event.SetEventObject(this);
        wxPostEvent(this, event);
    });
    stext->Bind(wxEVT_LEFT_DOWN, [this, id](wxMouseEvent &e) {
        auto event = wxCommandEvent(EVT_PREFERENCES_SELECT_TAB);
        event.SetInt(id);
        event.SetEventObject(this);
        wxPostEvent(this, event);
    });
    Select *sel                   = new Select;
    sel->m_index                  = id;
    sel->m_tab_button             = tab_button;
    sel->m_tab_text               = stext;
    m_hash_selector[sel->m_index] = sel;
    tab_button->SetSizer(sizer);
    tab_button->Layout();
    return tab_button;
}
References Label::Body_13, m_hash_selector, Slic3r::GUI::Select::m_index, m_panel_selects, Slic3r::GUI::Select::m_tab_button, Slic3r::GUI::Select::m_tab_text, Slic3r::GUI::wxMouseEvent, and wxStaticText.
Referenced by KBShortcutsDialog().
create_header()
wxPanel * Slic3r::GUI::KBShortcutsDialog::create_header (wxWindow * parent, const wxFont & bold_font) private
create_page()
wxPanel * Slic3r::GUI::KBShortcutsDialog::create_page (wxWindow * parent, const ShortcutsItem & shortcuts, const wxFont & font, const wxFont & bold_font) private
{
    wxPanel* main_page = new wxPanel(parent);
    wxBoxSizer* main_sizer = new wxBoxSizer(wxVERTICAL);
    if (!shortcuts.first.second.empty()) {
        main_sizer->AddSpacer(FromDIP(10));
        wxBoxSizer* info_sizer = new wxBoxSizer(wxHORIZONTAL);
        info_sizer->AddStretchSpacer();
        info_sizer->Add(new wxStaticText(main_page, wxID_ANY, shortcuts.first.second), 0);
        info_sizer->AddStretchSpacer();
        main_sizer->Add(info_sizer, 0, wxEXPAND);
        main_sizer->AddSpacer(FromDIP(10));
    }
    int items_count = (int) shortcuts.second.size();
    wxScrolledWindow *scrollable_panel = new wxScrolledWindow(main_page);
    wxGetApp().UpdateDarkUI(scrollable_panel);
    scrollable_panel->SetScrollbars(20, 20, 50, 50);
    scrollable_panel->SetInitialSize(wxSize(FromDIP(850), FromDIP(450)));
    wxBoxSizer *     scrollable_panel_sizer = new wxBoxSizer(wxVERTICAL);
    wxFlexGridSizer *grid_sizer             = new wxFlexGridSizer(items_count, 2, FromDIP(10), FromDIP(20));
    for (int i = 0; i < items_count; ++i) {
        const auto &[shortcut, description] = shortcuts.second[i];
        auto key                            = new wxStaticText(scrollable_panel, wxID_ANY, _(shortcut));
        key->SetForegroundColour(wxColour(50, 58, 61));
        key->SetFont(bold_font);
        grid_sizer->Add(key, 0, wxALIGN_CENTRE_VERTICAL);
        auto desc = new wxStaticText(scrollable_panel, wxID_ANY, _(description));
        desc->SetFont(font);
        desc->SetForegroundColour(wxColour(50, 58, 61));
        desc->Wrap(FromDIP(600));
        grid_sizer->Add(desc, 0, wxALIGN_CENTRE_VERTICAL);
    }
    scrollable_panel_sizer->Add(grid_sizer, 1, wxEXPAND | wxALL, FromDIP(20));
    scrollable_panel->SetSizer(scrollable_panel_sizer);
    main_sizer->Add(scrollable_panel, 1, wxEXPAND);
    main_page->SetSizer(main_sizer);
    return main_page;
}
References _, int, and wxStaticText.
Referenced by KBShortcutsDialog().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
fill_shortcuts()
void Slic3r::GUI::KBShortcutsDialog::fill_shortcuts () private
{
    const std::string& ctrl = GUI::shortkey_ctrl_prefix();
    const std::string& alt = GUI::shortkey_alt_prefix();
    if (wxGetApp().is_editor()) {
        Shortcuts global_shortcuts = {
            // File
            { ctrl + "N", L("New Project") },
            { ctrl + "O", L("Open Project") },
            { ctrl + "S", L("Save Project") },
            { ctrl + alt + "S", L("Save Project as") },
            // File>Import
            { ctrl + "I", L("Import geometry data from STL/STEP/3MF/OBJ/AMF files") },
            // File>Export
            { ctrl + "G", L("Export plate sliced file")},
            // Slice plate
            { ctrl + "R", L("Slice plate")},
            // Send to Print
#ifdef __APPLE__
            { L("+Shift+G"), L("Print plate")},
#else
            { L("Ctrl+Shift+G"), L("Print plate")},
#endif // __APPLE
            // Edit
            { ctrl + "X", L("Cut") },
            { ctrl + "C", L("Copy to clipboard") },
            { ctrl + "V", L("Paste from clipboard") },
            // Configuration
            { ctrl + "P", L("Preferences") },
            //3D control
            { ctrl + "M", L("Show/Hide 3Dconnexion devices settings dialog") },
            //DEL
            #ifdef __APPLE__
                {"fn+", L("Delete selected")},
            #else
                {L("Del"), L("Delete selected")},
            #endif
            // Help
            { "?", L("Show keyboard shortcuts list") }
        };
        m_full_shortcuts.push_back({{_L("Global shortcuts"), ""}, global_shortcuts});
        Shortcuts plater_shortcuts = {
            { L("Left mouse button"), L("Rotate View") },
            { L("Right mouse button"), L("Pan View") },
            { L("Mouse wheel"), L("Zoom View") },
            { "A", L("Arrange all objects") },
            { L("Shift+A"), L("Arrange objects on selected plates") },
            //{ "R", L("Auto orientates selected objects or all objects.If there are selected objects, it just orientates the selected ones.Otherwise, it will orientates all objects in the project.") },
            {L("Shift+R"), L("Auto orientates selected objects or all objects.If there are selected objects, it just orientates the selected ones.Otherwise, it will orientates all objects in the current disk.")},
            {L("Shift+Tab"), L("Collapse/Expand the sidebar")},
            #ifdef __APPLE__
                {L("+Any arrow"), L("Movement in camera space")},
                {L("+Left mouse button"), L("Select a part")},
                {L("+Left mouse button"), L("Select multiple objects")},
            #else
                {L("Ctrl+Any arrow"), L("Movement in camera space")},
                {L("Alt+Left mouse button"), L("Select a part")},
                {L("Ctrl+Left mouse button"), L("Select multiple objects")},
            #endif
            {L("Shift+Left mouse button"), L("Select objects by rectangle")},
            {L("Arrow Up"), L("Move selection 10 mm in positive Y direction")},
            {L("Arrow Down"), L("Move selection 10 mm in negative Y direction")},
            {L("Arrow Left"), L("Move selection 10 mm in negative X direction")},
            {L("Arrow Right"), L("Move selection 10 mm in positive X direction")},
            {L("Shift+Any arrow"), L("Movement step set to 1 mm")},
            {L("Esc"), L("Deselect all")},
            {"1-9", L("keyboard 1-9: set filament for object/part")},
            {ctrl + "0", L("Camera view - Default")},
            {ctrl + "1", L("Camera view - Top")},
            {ctrl + "2", L("Camera view - Bottom")},
            {ctrl + "3", L("Camera view - Front")},
            {ctrl + "4", L("Camera view - Behind")},
            {ctrl + "5", L("Camera Angle - Left side")},
            {ctrl + "6", L("Camera Angle - Right side")},
            {ctrl + "A", L("Select all objects")},
            {ctrl + "D", L("Delete all")},
            {ctrl + "Z", L("Undo")},
            {ctrl + "Y", L("Redo")},
            { "M", L("Gizmo move") },
            { "S", L("Gizmo scale") },
            { "R", L("Gizmo rotate") },
            { "C", L("Gizmo cut") },
            { "F", L("Gizmo Place face on bed") },
            { "L", L("Gizmo SLA support points") },
            { "P", L("Gizmo FDM paint-on seam") },
            { "Tab", L("Swtich between Prepare/Prewview") },
        };
        m_full_shortcuts.push_back({ { _L("Plater"), "" }, plater_shortcuts });
        Shortcuts gizmos_shortcuts = {
            {L("Esc"), L("Deselect all")},
            {L("Shift+"), L("Move: press to snap by 1mm")},
            #ifdef __APPLE__
                {L("+Mouse wheel"), L("Support/Color Painting: adjust pen radius")},
                {L("+Mouse wheel"), L("Support/Color Painting: adjust section position")},
            #else
            {L("Ctrl+Mouse wheel"), L("Support/Color Painting: adjust pen radius")},
                {L("Alt+Mouse wheel"), L("Support/Color Painting: adjust section position")},
            #endif
        };
        m_full_shortcuts.push_back({{_L("Gizmo"), ""}, gizmos_shortcuts});
        Shortcuts object_list_shortcuts = {
            {"1-9", L("Set extruder number for the objects and parts") },
            {L("Del"), L("Delete objects, parts, modifiers  ")},
            {L("Esc"), L("Deselect all")},
            {ctrl + "C", L("Copy to clipboard")},
            {ctrl + "V", L("Paste from clipboard")},
            {ctrl + "X", L("Cut")},
            {ctrl + "A", L("Select all objects")},
            {ctrl + "M", L("Clone selected")},
            {ctrl + "Z", L("Undo")},
            {ctrl + "Y", L("Redo")},
            {L("Space"), L("Select the object/part and press space to change the name")},
            {L("Mouse click"), L("Select the object/part and mouse click to change the name")},
        };
        m_full_shortcuts.push_back({ { _L("Objects List"), "" }, object_list_shortcuts });
    }
    Shortcuts preview_shortcuts = {
        { L("Arrow Up"),    L("Vertical slider - Move active thumb Up")},
        { L("Arrow Down"),  L("Vertical slider - Move active thumb Down")},
        { L("Arrow Left"),  L("Horizontal slider - Move active thumb Left")},
        { L("Arrow Right"), L("Horizontal slider - Move active thumb Right")},
        { "L", L("On/Off one layer mode of the vertical slider")},
        { "C", L("On/Off g-code window")},
        { "Tab", L("Swtich between Prepare/Prewview") },
        {L("Shift+Any arrow"), L("Move slider 5x faster")},
        {L("Shift+Mouse wheel"), L("Move slider 5x faster")},
        #ifdef __APPLE__
            {L("+Any arrow"), L("Move slider 5x faster")},
            {L("+Mouse wheel"), L("Move slider 5x faster")},
        #else
        {L("Ctrl+Any arrow"), L("Move slider 5x faster")},
        {L("Ctrl+Mouse wheel"), L("Move slider 5x faster")},
       #endif
    };
    m_full_shortcuts.push_back({ { _L("Preview"), "" }, preview_shortcuts });
}
References _L, Slic3r::GUI::ctrl, L, m_full_shortcuts, Slic3r::GUI::shortkey_alt_prefix(), and Slic3r::GUI::shortkey_ctrl_prefix().
Referenced by KBShortcutsDialog().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_dpi_changed()
void Slic3r::GUI::KBShortcutsDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    m_logo_bmp.msw_rescale();
    m_header_bitmap->SetBitmap(m_logo_bmp.bmp());
    msw_buttons_rescale(this, em_unit(), { wxID_OK });
    Layout();
    Fit();
    Refresh();
}
References ScalableBitmap::bmp(), Slic3r::GUI::DPIAware< P >::em_unit(), m_header_bitmap, m_logo_bmp, msw_buttons_rescale(), and ScalableBitmap::msw_rescale().
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
OnSelectTabel()
void Slic3r::GUI::KBShortcutsDialog::OnSelectTabel (wxCommandEvent & event)
{
    auto                   id = event.GetInt();
    SelectHash::iterator i  = m_hash_selector.begin();
    while (i != m_hash_selector.end()) {
        Select *sel = i->second;
        if (id == sel->m_index) {
            sel->m_tab_button->SetBackgroundColour(StateColor::darkModeColorFor(wxColour("#FFFFFF")));
            sel->m_tab_text->SetBackgroundColour(StateColor::darkModeColorFor(wxColour("#FFFFFF")));
            sel->m_tab_text->SetFont(::Label::Head_13);
            sel->m_tab_button->Refresh();
            sel->m_tab_text->Refresh();
            m_simplebook->SetSelection(id);
        } else {
            sel->m_tab_button->SetBackgroundColour(StateColor::darkModeColorFor(wxColour("#F8F8F8")));
            sel->m_tab_text->SetBackgroundColour(StateColor::darkModeColorFor(wxColour("#F8F8F8")));
            sel->m_tab_text->SetFont(::Label::Body_13);
            sel->m_tab_button->Refresh();
            sel->m_tab_text->Refresh();
        }
        i++;
    }
    wxGetApp().UpdateDlgDarkUI(this);
}
References Label::Body_13, StateColor::darkModeColorFor(), Label::Head_13, m_hash_selector, Slic3r::GUI::Select::m_index, m_simplebook, Slic3r::GUI::Select::m_tab_button, and Slic3r::GUI::Select::m_tab_text.
Referenced by KBShortcutsDialog().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
Member Data Documentation
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_full_shortcuts
ShortcutsVec Slic3r::GUI::KBShortcutsDialog::m_full_shortcuts private
Referenced by KBShortcutsDialog(), and fill_shortcuts().
m_hash_selector
SelectHash Slic3r::GUI::KBShortcutsDialog::m_hash_selector
Referenced by create_button(), and OnSelectTabel().
m_header_bitmap
wxStaticBitmap* Slic3r::GUI::KBShortcutsDialog::m_header_bitmap private
Referenced by on_dpi_changed().
m_logo_bmp
ScalableBitmap Slic3r::GUI::KBShortcutsDialog::m_logo_bmp private
Referenced by on_dpi_changed().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_pages
std::vector<wxPanel*> Slic3r::GUI::KBShortcutsDialog::m_pages private
Referenced by KBShortcutsDialog().
m_panel_selects
wxPanel* Slic3r::GUI::KBShortcutsDialog::m_panel_selects
Referenced by KBShortcutsDialog(), and create_button().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_simplebook
wxSimplebook* Slic3r::GUI::KBShortcutsDialog::m_simplebook
Referenced by KBShortcutsDialog(), and OnSelectTabel().
m_sizer_body
wxBoxSizer* Slic3r::GUI::KBShortcutsDialog::m_sizer_body
Referenced by KBShortcutsDialog().
m_sizer_right
wxBoxSizer* Slic3r::GUI::KBShortcutsDialog::m_sizer_right
Referenced by KBShortcutsDialog().
The documentation for this class was generated from the following files:
src/slic3r/GUI/KBShortcutsDialog.hpp
src/slic3r/GUI/KBShortcutsDialog.cpp