OrcaSlicer: Slic3r::Polyline Class Reference
Slic3r::Polyline Class Reference
#include <src/libslic3r/Polyline.hpp>
Public Member Functions
Polyline ()
Polyline (const Polyline &other)
Polyline (Polyline &&other)
Polyline (std::initializer_list< Point > list)
Polyline (const Point &p1, const Point &p2)
Polyline (const Points &points)
Polyline (Points &&points)
Polyline & operator= (const Polyline &other)
Polyline & operator= (Polyline &&other)
void append (const Point &point)
void append_before (const Point &point)
void append (const Points &src)
void append (const Points::const_iterator &begin, const Points::const_iterator &end)
void append (Points &&src)
void append (const Polyline &src)
void append (Polyline &&src)
const Point & last_point () const override
const Point & leftmost_point () const
Lines lines () const override
void clear ()
void reverse ()
void clip_end (double distance)
void clip_start (double distance)
void extend_end (double distance)
void extend_start (double distance)
Points equally_spaced_points (double distance) const
void simplify (double tolerance)
void split_at (Point &point, Polyline *p1, Polyline *p2) const
bool split_at_index (const size_t index, Polyline *p1, Polyline *p2) const
bool is_straight () const
bool is_closed () const
void simplify_by_fitting_arc (double tolerance)
Polylines equally_spaced_lines (double distance) const
void scale (double factor)
void scale (double factor_x, double factor_y)
void translate (double x, double y)
void translate (const Point &vector)
void rotate (double angle)
void rotate (double cos_angle, double sin_angle)
void rotate (double angle, const Point &center)
const Point & front () const
const Point & back () const
const Point & first_point () const
size_t size () const
bool empty () const
double length () const
bool is_valid () const
int find_point (const Point &point) const
int find_point (const Point &point, const double scaled_epsilon) const
bool has_boundary_point (const Point &point) const
int closest_point_index (const Point &point) const
const Point * closest_point (const Point &point) const
double distance_to (const Point &point) const
BoundingBox bounding_box () const
bool has_duplicate_points () const
bool remove_duplicate_points ()
bool intersection (const Line &line, Point *intersection) const
bool first_intersection (const Line &line, Point *intersection) const
bool intersections (const Line &line, Points *intersections) const
auto begin ()
auto begin () const
auto end ()
auto end () const
auto cbegin () const
auto cend () const
Static Public Member Functions
static Polyline new_scale (const std::vector< Vec2d > &points)
static Points _douglas_peucker (const Points &points, const double tolerance)
static Points visivalingam (const Points &pts, const double tolerance)
static Points concave_hull_2d (const Points &pts, const double tolerence)
Public Attributes
std::vector< PathFittingData > fitting_result
Points points
Private Member Functions
void append_fitting_result_after_append_points ()
void append_fitting_result_after_append_polyline (const Polyline &src)
void reset_to_linear_move ()
bool split_fitting_result_before_index (const size_t index, Point &new_endpoint, std::vector< PathFittingData > &data) const
bool split_fitting_result_after_index (const size_t index, Point &new_startpoint, std::vector< PathFittingData > &data) const
Detailed Description
Constructor & Destructor Documentation
Polyline() [1/7]
Slic3r::Polyline::Polyline () inline
{};
Polyline() [2/7]
Slic3r::Polyline::Polyline (const Polyline & other) inline
: MultiPoint(other.points), fitting_result(other.fitting_result) {}
Polyline() [3/7]
Slic3r::Polyline::Polyline (Polyline && other) inline
: MultiPoint(std::move(other.points)), fitting_result(std::move(other.fitting_result))  {}
Polyline() [4/7]
Slic3r::Polyline::Polyline (std::initializer_list< Point > list) inline
                                              : MultiPoint(list) {
        fitting_result.clear();
    }
References fitting_result.
Polyline() [5/7]
Slic3r::Polyline::Polyline (const Point & p1, const Point & p2) inline explicit
{
        points.reserve(2);
        points.emplace_back(p1);
        points.emplace_back(p2);
        fitting_result.clear();
    }
References fitting_result, and Slic3r::MultiPoint::points.
Polyline() [6/7]
Slic3r::Polyline::Polyline (const Points & points) inline explicit
                                            : MultiPoint(points) {
        fitting_result.clear();
    }
References fitting_result.
Polyline() [7/7]
Slic3r::Polyline::Polyline (Points && points) inline explicit
                                       : MultiPoint(std::move(points)) {
        fitting_result.clear();
    }
References fitting_result.
Member Function Documentation
_douglas_peucker()
std::vector< Point > Slic3r::MultiPoint::_douglas_peucker (const Points & points, const double tolerance) static inherited
{
    std::vector<Point> result_pts;
  double tolerance_sq = tolerance * tolerance;
    if (! pts.empty()) {
        const Point  *anchor      = &pts.front();
        size_t        anchor_idx  = 0;
        const Point  *floater     = &pts.back();
        size_t        floater_idx = pts.size() - 1;
        result_pts.reserve(pts.size());
        result_pts.emplace_back(*anchor);
        if (anchor_idx != floater_idx) {
            assert(pts.size() > 1);
            std::vector<size_t> dpStack;
            dpStack.reserve(pts.size());
            dpStack.emplace_back(floater_idx);
            for (;;) {
                double max_dist_sq  = 0.0;
                size_t furthest_idx = anchor_idx;
                // find point furthest from line seg created by (anchor, floater) and note it
                for (size_t i = anchor_idx + 1; i < floater_idx; ++ i) {
                    double dist_sq = Line::distance_to_squared(pts[i], *anchor, *floater);
                    if (dist_sq > max_dist_sq) {
                        max_dist_sq  = dist_sq;
                        furthest_idx = i;
                    }
                }
                // remove point if less than tolerance
                if (max_dist_sq <= tolerance_sq) {
                    result_pts.emplace_back(*floater);
                    anchor_idx = floater_idx;
                    anchor     = floater;
                    assert(dpStack.back() == floater_idx);
                    dpStack.pop_back();
                    if (dpStack.empty())
                        break;
                    floater_idx = dpStack.back();
                } else {
                    floater_idx = furthest_idx;
                    dpStack.emplace_back(floater_idx);
                }
                floater = &pts[floater_idx];
            }
        }
        assert(result_pts.front() == pts.front());
        assert(result_pts.back()  == pts.back());
#if 0
        {
            static int iRun = 0;
      BoundingBox bbox(pts);
      BoundingBox bbox2(result_pts);
      bbox.merge(bbox2);
            SVG svg(debug_out_path("douglas_peucker_%d.svg", iRun ++).c_str(), bbox);
            if (pts.front() == pts.back())
                svg.draw(Polygon(pts), "black");
            else
                svg.draw(Polyline(pts), "black");
            if (result_pts.front() == result_pts.back())
                svg.draw(Polygon(result_pts), "green", scale_(0.1));
            else
                svg.draw(Polyline(result_pts), "green", scale_(0.1));
        }
#endif
    }
    return result_pts;
}
References Slic3r::debug_out_path(), Slic3r::Line::distance_to_squared(), Slic3r::SVG::draw(), Slic3r::BoundingBoxBase< PointClass >::merge(), and scale_.
Referenced by Slic3r::Polygon::douglas_peucker(), Slic3r::polygons_simplify(), simplify(), Slic3r::Polygon::simplify(), Slic3r::ExPolygon::simplify_p(), and Slic3r::Geometry::simplify_polygons().
append() [1/6]
void Slic3r::Polyline::append (const Point & point) inline
{
        //BBS: don't need to append same point
        if (!this->empty() && this->last_point() == point)
            return;
        MultiPoint::append(point);
        append_fitting_result_after_append_points();
    }
References Slic3r::MultiPoint::append(), append_fitting_result_after_append_points(), Slic3r::MultiPoint::empty(), and last_point().
Referenced by Slic3r::_make_loops(), append(), append(), append(), append_before(), Slic3r::GUI::PartPlate::calc_gridlines(), Slic3r::FillAdaptive::connect_lines_using_hooks(), equally_spaced_lines(), extend_end(), Slic3r::LoopInterfaceProcessor::generate(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::modulate_extrusion_by_overlapping_layers(), Slic3r::GCode::needs_retraction(), Slic3r::ExtrusionLoop::split_at(), split_at(), split_at_index(), Slic3r::ExtrusionLoop::split_at_vertex(), Slic3r::thick_polyline_to_extrusion_paths(), Slic3r::thick_polyline_to_extrusion_paths_2(), Slic3r::to_polyline(), and Slic3r::Wipe::wipe().
append() [2/6]
void Slic3r::Polyline::append (const Points & src) inline
{
        //BBS: don't need to append same point
        if (!this->empty() && !src.empty() && this->last_point() == src[0])
            this->append(src.begin() + 1, src.end());
        else
            this->append(src.begin(), src.end());
    }
References append(), and Slic3r::MultiPoint::empty().
append() [3/6]
void Slic3r::Polyline::append (const Points::const_iterator & begin, const Points::const_iterator & end) inline
{
        //BBS: don't need to append same point
        if (!this->empty() && begin != end && this->last_point() == *begin)
            MultiPoint::append(begin + 1, end);
        else
            MultiPoint::append(begin, end);
        append_fitting_result_after_append_points();
    }
References Slic3r::MultiPoint::append(), append_fitting_result_after_append_points(), Slic3r::MultiPoint::begin(), Slic3r::MultiPoint::empty(), Slic3r::MultiPoint::end(), and last_point().
append() [4/6]
void Slic3r::Polyline::append (const Polyline & src)
{
    if (!src.is_valid()) return;
    if (this->points.empty()) {
        this->points = src.points;
        this->fitting_result = src.fitting_result;
    } else {
        //BBS: append the first point to create connection first, update the fitting date as well
        this->append(src.points[0]);
        //BBS: append a polyline which has fitting data to a polyline without fitting data.
        //Then create a fake fitting data first, so that we can keep the fitting data in last polyline
        if (this->fitting_result.empty() &&
            !src.fitting_result.empty()) {
            this->fitting_result.emplace_back(PathFittingData{ 0, this->points.size() - 1, EMovePathType::Linear_move, ArcSegment() });
        }
        //BBS: then append the remain points
        MultiPoint::append(src.points.begin() + 1, src.points.end());
        //BBS: finally append the fitting data
        append_fitting_result_after_append_polyline(src);
    }
}
References Slic3r::MultiPoint::append(), append(), append_fitting_result_after_append_polyline(), fitting_result, Slic3r::MultiPoint::is_valid(), Slic3r::Linear_move, and Slic3r::MultiPoint::points.
append() [5/6]
void Slic3r::Polyline::append (Points && src) inline
    {
        MultiPoint::append(std::move(src));
        append_fitting_result_after_append_points();
    }
References Slic3r::MultiPoint::append(), and append_fitting_result_after_append_points().
append() [6/6]
void Slic3r::Polyline::append (Polyline && src)
{
    if (!src.is_valid()) return;
    if (this->points.empty()) {
        this->points = std::move(src.points);
        this->fitting_result = std::move(src.fitting_result);
    } else {
        //BBS: append the first point to create connection first, update the fitting date as well
        this->append(src.points[0]);
        //BBS: append a polyline which has fitting data to a polyline without fitting data.
        //Then create a fake fitting data first, so that we can keep the fitting data in last polyline
        if (this->fitting_result.empty() &&
            !src.fitting_result.empty()) {
            this->fitting_result.emplace_back(PathFittingData{ 0, this->points.size() - 1, EMovePathType::Linear_move, ArcSegment() });
        }
        //BBS: then append the remain points
        MultiPoint::append(src.points.begin() + 1, src.points.end());
        //BBS: finally append the fitting data
        append_fitting_result_after_append_polyline(src);
        src.points.clear();
        src.fitting_result.clear();
    }
}
References Slic3r::MultiPoint::append(), append(), append_fitting_result_after_append_polyline(), fitting_result, Slic3r::Linear_move, and Slic3r::MultiPoint::points.
append_before()
void Slic3r::Polyline::append_before (const Point & point) inline
{
        //BBS: don't need to append same point
        if (!this->empty() && this->first_point() == point)
            return;
        if (this->size() == 1) {
            this->fitting_result.clear();
            MultiPoint::append(point);
            MultiPoint::reverse();
        } else {
            this->reverse();
            this->append(point);
            this->reverse();
        }
    }
References Slic3r::MultiPoint::append(), append(), Slic3r::MultiPoint::empty(), Slic3r::MultiPoint::first_point(), fitting_result, Slic3r::MultiPoint::reverse(), reverse(), and Slic3r::MultiPoint::size().
Referenced by split_at().
append_fitting_result_after_append_points()
void Slic3r::Polyline::append_fitting_result_after_append_points () private
{
    if (!fitting_result.empty()) {
        if (fitting_result.back().is_linear_move()) {
            fitting_result.back().end_point_index = this->points.size() - 1;
        } else {
            size_t new_start = fitting_result.back().end_point_index;
            size_t new_end = this->points.size() - 1;
            if (new_start != new_end)
                fitting_result.emplace_back(PathFittingData{ new_start, new_end, EMovePathType::Linear_move, ArcSegment() });
        }
    }
}
References fitting_result, Slic3r::Linear_move, and Slic3r::MultiPoint::points.
Referenced by append(), append(), and append().
append_fitting_result_after_append_polyline()
void Slic3r::Polyline::append_fitting_result_after_append_polyline (const Polyline & src) private
{
    if (!this->fitting_result.empty()) {
        //BBS: offset and save the fitting_result from src polyline
        if (!src.fitting_result.empty()) {
            size_t old_size = this->fitting_result.size();
            size_t index_offset = this->fitting_result.back().end_point_index;
            this->fitting_result.insert(this->fitting_result.end(), src.fitting_result.begin(), src.fitting_result.end());
            for (size_t i = old_size; i < this->fitting_result.size(); i++) {
                this->fitting_result[i].start_point_index += index_offset;
                this->fitting_result[i].end_point_index += index_offset;
            }
        } else {
            //BBS: the append polyline has no fitting data, then append as linear move directly
            size_t new_start = this->fitting_result.back().end_point_index;
            size_t new_end = this->size() - 1;
            if (new_start != new_end)
                this->fitting_result.emplace_back(PathFittingData{ new_start, new_end, EMovePathType::Linear_move, ArcSegment() });
        }
    }
}
References fitting_result, Slic3r::Linear_move, and Slic3r::MultiPoint::size().
Referenced by append(), and append().
back()
const Point & Slic3r::MultiPoint::back () const inline inherited
{ return this->points.back(); }
Referenced by Slic3r::_make_loops(), Slic3r::contour_distance(), Slic3r::make_brim_ears(), Slic3r::make_wave(), Slic3r::makeGrid(), Slic3r::polylines_from_paths(), Slic3r::Arachne::removeDegenerateVerts(), Slic3r::FillLightning::Node::removeJunctionOverlap(), Slic3r::resample_polygon(), and Slic3r::traverse_graph_generate_polylines().
begin() [1/2]
auto Slic3r::MultiPoint::begin () inline inherited
{ return points.begin(); }
References Slic3r::MultiPoint::points.
Referenced by Slic3r::MultiPoint::append(), append(), Slic3r::contour_distance(), Slic3r::contour_distance(), Slic3r::contour_distance2(), Slic3r::EdgeGrid::Grid::create_from_m_contours(), and split_at_index().
begin() [2/2]
auto Slic3r::MultiPoint::begin () const inline inherited
{ return points.begin(); }
References Slic3r::MultiPoint::points.
bounding_box()
BoundingBox Slic3r::MultiPoint::bounding_box () const inherited
{
    return BoundingBox(this->points);
}
References Slic3r::MultiPoint::points.
Referenced by Slic3r::Fill3DHoneycomb::_fill_surface_single(), Slic3r::FillConcentric::_fill_surface_single(), Slic3r::FillGyroid::_fill_surface_single(), Slic3r::FillHoneycomb::_fill_surface_single(), Slic3r::FillLine::_fill_surface_single(), Slic3r::FillConcentric::_fill_surface_single(), Slic3r::Fill::_infill_direction(), Slic3r::FillConcentricInternal::fill_surface_extrusion(), Slic3r::TreeSupport::generate_contact_points(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::GUI::get_shrink_bedpts(), Slic3r::sla::anonymous_namespace{Pad.cpp}::Intersector::intersects(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::PartPlate::set_shape(), and Slic3r::GUI::update_selected_items_inflation().
cbegin()
auto Slic3r::MultiPoint::cbegin () const inline inherited
{ return points.begin(); }
References Slic3r::MultiPoint::points.
cend()
auto Slic3r::MultiPoint::cend () const inline inherited
{ return points.end();   }
References Slic3r::MultiPoint::points.
clear()
void Slic3r::Polyline::clear () inline
{ MultiPoint::clear(); this->fitting_result.clear(); }
References Slic3r::MultiPoint::clear(), and fitting_result.
Referenced by Slic3r::ThickPolyline::clear(), Slic3r::FillAdaptive::connect_lines_using_hooks(), equally_spaced_lines(), Slic3r::evaluate_support_arches(), Slic3r::AvoidCrossingPerimeters::init_layer(), and split_at_index().
clip_end()
void Slic3r::Polyline::clip_end (double distance)
{
    bool last_point_inserted = false;
    size_t remove_after_index = MultiPoint::size();
    while (distance > 0) {
        Vec2d  last_point = this->last_point().cast<double>();
        this->points.pop_back();
        remove_after_index--;
        if (this->points.empty()) {
            this->fitting_result.clear();
            return;
        }
        Vec2d  v    = this->last_point().cast<double>() - last_point;
        double lsqr = v.squaredNorm();
        if (lsqr > distance * distance) {
            this->points.emplace_back((last_point + v * (distance / sqrt(lsqr))).cast<coord_t>());
            last_point_inserted = true;
            break;
        }
        distance -= sqrt(lsqr);
    }
    //BBS: don't need to clip fitting result if it's empty
    if (fitting_result.empty())
        return;
    while (!fitting_result.empty() && fitting_result.back().start_point_index >= remove_after_index)
        fitting_result.pop_back();
    if (!fitting_result.empty()) {
        //BBS: last remaining segment is arc move, then clip the arc at last point
        if (fitting_result.back().path_type == EMovePathType::Arc_move_ccw
            || fitting_result.back().path_type == EMovePathType::Arc_move_cw) {
            if (fitting_result.back().arc_data.clip_end(this->last_point()))
                //BBS: succeed to clip arc, then update the last point
                this->points.back() = fitting_result.back().arc_data.end_point;
            else
                //BBS: Failed to clip arc, then back to linear move
                fitting_result.back().path_type = EMovePathType::Linear_move;
        }
        fitting_result.back().end_point_index = this->points.size() - 1;
    }
}
References Slic3r::Arc_move_ccw, Slic3r::Arc_move_cw, fitting_result, last_point(), Slic3r::Linear_move, Slic3r::MultiPoint::points, Slic3r::MultiPoint::size(), and sqrt().
Referenced by Slic3r::ExtrusionPath::clip_end(), Slic3r::ExtrusionLoop::clip_end(), clip_start(), Slic3r::Fill::connect_base_support(), and Slic3r::Wipe::wipe().
clip_start()
void Slic3r::Polyline::clip_start (double distance)
{
    this->reverse();
    this->clip_end(distance);
    if (this->points.size() >= 2)
        this->reverse();
}
References clip_end(), Slic3r::MultiPoint::points, and reverse().
closest_point()
const Point * Slic3r::MultiPoint::closest_point (const Point & point) const inline inherited
{ return this->points.empty() ? nullptr : &this->points[this->closest_point_index(point)]; }
References Slic3r::MultiPoint::closest_point_index().
Referenced by Slic3r::MultiPoint::distance_to().
closest_point_index()
int Slic3r::MultiPoint::closest_point_index (const Point & point) const inline inherited
{
        int idx = -1;
        if (! this->points.empty()) {
            idx = 0;
            double dist_min = (point - this->points.front()).cast<double>().norm();
            for (int i = 1; i < int(this->points.size()); ++ i) {
                double d = (this->points[i] - point).cast<double>().norm();
                if (d < dist_min) {
                    dist_min = d;
                    idx = i;
                }
            }
        }
        return idx;
    }
References int.
Referenced by Slic3r::MultiPoint::closest_point().
concave_hull_2d()
Points Slic3r::MultiPoint::concave_hull_2d (const Points & pts, const double tolerence) static inherited
{
    Points hull;
    int n = (int)pts.size();
    if (n >= 3) {
        int k = 0;
        hull.resize(n);
        for (int i = 0; i < n; ++i) {
            while (k >= 2 && pts[i].ccw(hull[k - 2], hull[k - 1]) <= 0 && -pts[i].ccw(hull[k - 2], hull[k - 1]) / (pts[i] - hull[k - 1]).norm() < tolerence)
                --k;
            hull[k++] = pts[i];
        }
        hull.resize(k);
        if (hull.front() == hull.back())
            hull.pop_back();
    }
    return hull;
}
References int, and n.
distance_to()
double Slic3r::MultiPoint::distance_to (const Point & point) const inline inherited
{
        const Point* cl = closest_point(point);
        return (*cl - point).cast<double>().norm();
    }
References Slic3r::MultiPoint::closest_point().
empty()
bool Slic3r::MultiPoint::empty () const inline inherited
{ return points.empty(); }
References Slic3r::MultiPoint::points.
Referenced by append(), append(), append(), append_before(), Slic3r::ExtrusionPath::collect_polylines(), Slic3r::ExtrusionMultiPath::collect_polylines(), Slic3r::ExtrusionLoop::collect_polylines(), Slic3r::Fill::connect_base_support(), Slic3r::connect_brim_lines(), Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::contour_distance(), Slic3r::contour_distance(), Slic3r::contour_distance2(), Slic3r::EdgeGrid::Grid::create(), Slic3r::EdgeGrid::Grid::create(), Slic3r::ExtrusionPath::empty(), Slic3r::FillAdaptive::Intersection::fresh(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::Voronoi::offset(), Slic3r::Polygon::overlaps(), Slic3r::Arachne::simplify(), Slic3r::take_ccw_full(), Slic3r::take_ccw_limited(), Slic3r::take_cw_full(), Slic3r::take_cw_limited(), Slic3r::AvoidCrossingPerimeters::travel_to(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), and Slic3r::Wipe::wipe().
end() [1/2]
auto Slic3r::MultiPoint::end () inline inherited
{ return points.end();   }
References Slic3r::MultiPoint::points.
Referenced by Slic3r::MultiPoint::append(), append(), Slic3r::contour_distance(), Slic3r::contour_distance(), Slic3r::contour_distance2(), and Slic3r::EdgeGrid::Grid::create_from_m_contours().
end() [2/2]
auto Slic3r::MultiPoint::end () const inline inherited
{ return points.end();   }
References Slic3r::MultiPoint::points.
equally_spaced_lines()
Polylines Slic3r::Polyline::equally_spaced_lines (double distance) const
{
    Polylines lines;
    Polyline line;
    line.append(this->first_point());
    double len = 0;
    for (Points::const_iterator it = this->points.begin() + 1; it != this->points.end(); ++it) {
        Vec2d  p1 = line.points.back().cast<double>();
        Vec2d  v = it->cast<double>() - p1;
        double segment_length = v.norm();
        len += segment_length;
        if (len < distance)
            continue;
        if (len == distance) {
            line.append(*it);
            lines.emplace_back(line);
            line.clear();
            line.append(*it);
            len = 0;
            continue;
        }
        double take = distance;  // how much we take of this segment
        line.append((p1 + v * (take / v.norm())).cast<coord_t>());
        lines.emplace_back(line);
        line.clear();
        line.append(lines.back().last_point());
        --it;
        len = -take;
    }
    // add the last reminder
    if (line.size() == 1) {
        line.append(this->last_point());
        if(line.first_point()!=line.last_point())
            lines.emplace_back(line);
    }
    return lines;
}
References append(), clear(), Slic3r::MultiPoint::first_point(), last_point(), lines(), Slic3r::MultiPoint::points, Slic3r::segment_length(), Slic3r::MultiPoint::size(), and Slic3r::take().
equally_spaced_points()
Points Slic3r::Polyline::equally_spaced_points (double distance) const
{
    Points points;
    points.emplace_back(this->first_point());
    double len = 0;
    for (Points::const_iterator it = this->points.begin() + 1; it != this->points.end(); ++it) {
        Vec2d  p1 = (it-1)->cast<double>();
        Vec2d  v  = it->cast<double>() - p1;
        double segment_length = v.norm();
        len += segment_length;
        if (len < distance)
            continue;
        if (len == distance) {
            points.emplace_back(*it);
            len = 0;
            continue;
        }
        double take = segment_length - (len - distance);  // how much we take of this segment
        points.emplace_back((p1 + v * (take / v.norm())).cast<coord_t>());
        -- it;
        len = - take;
    }
    return points;
}
References Slic3r::MultiPoint::first_point(), Slic3r::MultiPoint::points, Slic3r::segment_length(), and Slic3r::take().
Referenced by Slic3r::Polygon::equally_spaced_points().
extend_end()
void Slic3r::Polyline::extend_end (double distance)
{
    //BBS: append a new last point by extending the last segment by the specified length
    Vec2d v = (this->points.back() - *(this->points.end() - 2)).cast<double>().normalized();
    Point new_last_point = this->points.back() + (v * distance).cast<coord_t>();
    this->append(new_last_point);
}
References append(), and Slic3r::MultiPoint::points.
Referenced by extend_start().
extend_start()
void Slic3r::Polyline::extend_start (double distance)
{
    this->reverse();
    this->extend_end(distance);
    this->reverse();
}
References extend_end(), and reverse().
find_point() [1/2]
int Slic3r::MultiPoint::find_point (const Point & point) const inherited
{
    for (const Point &pt : this->points)
        if (pt == point)
            return int(&pt - &this->points.front());
    return -1;  // not found
}
References int, and Slic3r::MultiPoint::points.
Referenced by Slic3r::MultiPoint::find_point(), and split_at().
find_point() [2/2]
int Slic3r::MultiPoint::find_point (const Point & point, const double scaled_epsilon) const inherited
{
    if (scaled_epsilon == 0) return this->find_point(point);
    auto dist2_min = std::numeric_limits<double>::max();
    auto eps2      = scaled_epsilon * scaled_epsilon;
    int  idx_min   = -1;
    for (const Point &pt : this->points) {
        double d2 = (pt - point).cast<double>().squaredNorm();
        if (d2 < dist2_min) {
            idx_min   = int(&pt - &this->points.front());
            dist2_min = d2;
        }
    }
    return dist2_min < eps2 ? idx_min : -1;
}
References Slic3r::MultiPoint::find_point(), int, and Slic3r::MultiPoint::points.
first_intersection()
bool Slic3r::MultiPoint::first_intersection (const Line & line, Point * intersection) const inherited
{
    bool   found = false;
    double dmin  = 0.;
    for (const Line &l : this->lines()) {
        Point ip;
        if (l.intersection(line, &ip)) {
            if (! found) {
                found = true;
                dmin = (line.a - ip).cast<double>().norm();
                *intersection = ip;
            } else {
                double d = (line.a - ip).cast<double>().norm();
                if (d < dmin) {
                    dmin = d;
                    *intersection = ip;
                }
            }
        }
    }
    return found;
}
References Slic3r::Line::a, dmin(), Slic3r::MultiPoint::intersection(), and Slic3r::MultiPoint::lines().
first_point()
const Point & Slic3r::MultiPoint::first_point () const inline inherited
{ return this->front(); }
References Slic3r::MultiPoint::front().
Referenced by append_before(), Slic3r::Geometry::MedialAxis::build(), Slic3r::connect_brim_lines(), equally_spaced_lines(), equally_spaced_points(), Slic3r::LoopInterfaceProcessor::generate(), Slic3r::improve_ordering_by_two_exchanges_with_segment_flipping(), is_straight(), Slic3r::ExPolygon::medial_axis(), Slic3r::need_wipe(), Slic3r::optimize_polylines_by_reversing(), Slic3r::Point::projection_onto(), split_at(), and split_at_index().
front()
const Point & Slic3r::MultiPoint::front () const inline inherited
{ return this->points.front(); }
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::MultiPoint::first_point(), Slic3r::mittered_offset_path_scaled(), libnest2d::shapelike::offset(), Slic3r::precompute_expolygon_distances(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::Arachne::WallToolPaths::stitchToolPaths(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
has_boundary_point()
bool Slic3r::MultiPoint::has_boundary_point (const Point & point) const inherited
{
    double dist = (point.projection_onto(*this) - point).cast<double>().norm();
    return dist < SCALED_EPSILON;
}
References Slic3r::Point::projection_onto(), and SCALED_EPSILON.
has_duplicate_points()
bool Slic3r::MultiPoint::has_duplicate_points () const inherited
{
    for (size_t i = 1; i < points.size(); ++i)
        if (points[i-1] == points[i])
            return true;
    return false;
}
References Slic3r::MultiPoint::points.
Referenced by Slic3r::polylines_from_paths(), and Slic3r::traverse_graph_generate_polylines().
intersection()
bool Slic3r::MultiPoint::intersection (const Line & line, Point * intersection) const inherited
{
    Lines lines = this->lines();
    for (Lines::const_iterator it = lines.begin(); it != lines.end(); ++it) {
        if (it->intersection(line, intersection)) return true;
    }
    return false;
}
References Slic3r::MultiPoint::intersection(), and Slic3r::MultiPoint::lines().
Referenced by Slic3r::MultiPoint::first_intersection(), Slic3r::MultiPoint::intersection(), and Slic3r::MultiPoint::intersections().
intersections()
bool Slic3r::MultiPoint::intersections (const Line & line, Points * intersections) const inherited
{
    size_t intersections_size = intersections->size();
    for (const Line &polygon_line : this->lines()) {
        Point intersection;
        if (polygon_line.intersection(line, &intersection))
            intersections->emplace_back(std::move(intersection));
    }
    return intersections->size() > intersections_size;
}
References Slic3r::MultiPoint::intersection(), Slic3r::MultiPoint::intersections(), and Slic3r::MultiPoint::lines().
Referenced by Slic3r::MultiPoint::intersections().
is_closed()
bool Slic3r::Polyline::is_closed () const inline
{ return this->points.front() == this->points.back(); }
References Slic3r::MultiPoint::points.
Referenced by Slic3r::connect_brim_lines(), and Slic3r::optimize_polylines_by_reversing().
is_straight()
bool Slic3r::Polyline::is_straight () const
{
    // Check that each segment's direction is equal to the line connecting
    // first point and last point. (Checking each line against the previous
    // one would cause the error to accumulate.)
    double dir = Line(this->first_point(), this->last_point()).direction();
    for (const auto &line: this->lines())
        if (! line.parallel_to(dir))
            return false;
    return true;
}
References Slic3r::Line::direction(), Slic3r::MultiPoint::first_point(), last_point(), and lines().
is_valid()
bool Slic3r::MultiPoint::is_valid () const inline inherited
{ return this->points.size() >= 2; }
Referenced by append(), Slic3r::ExtrusionLoop::split_at(), split_at(), Slic3r::ExtrusionLoop::split_at_vertex(), and Slic3r::thick_polyline_to_extrusion_paths().
last_point()
const Point & Slic3r::Polyline::last_point () const inline override virtual
Implements Slic3r::MultiPoint.
{ return this->points.back(); }
References Slic3r::MultiPoint::points.
Referenced by append(), append(), Slic3r::Geometry::MedialAxis::build(), clip_end(), Slic3r::connect_brim_lines(), equally_spaced_lines(), Slic3r::LoopInterfaceProcessor::generate(), is_straight(), Slic3r::ExPolygon::medial_axis(), Slic3r::need_wipe(), Slic3r::optimize_polylines_by_reversing(), split_at(), and split_at_index().
leftmost_point()
const Point & Slic3r::Polyline::leftmost_point () const
{
    const Point *p = &this->points.front();
    for (Points::const_iterator it = this->points.begin() + 1; it != this->points.end(); ++ it) {
        if (it->x() < p->x())
          p = &(*it);
    }
    return *p;
}
References Slic3r::MultiPoint::points.
length()
double Slic3r::MultiPoint::length () const inherited
{
    const Lines& lines = this->lines();
    double len = 0;
    for (auto it = lines.cbegin(); it != lines.cend(); ++it) {
        len += it->length();
    }
    return len;
}
References Slic3r::MultiPoint::lines().
Referenced by Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::ExtrusionPath::length(), Slic3r::ExPolygon::medial_axis(), Slic3r::GCode::needs_retraction(), Slic3r::AvoidCrossingPerimeters::travel_to(), and Slic3r::Wipe::wipe().
lines()
Lines Slic3r::Polyline::lines () const override virtual
Implements Slic3r::MultiPoint.
{
    Lines lines;
    if (this->points.size() >= 2) {
        lines.reserve(this->points.size() - 1);
        for (Points::const_iterator it = this->points.begin(); it != this->points.end()-1; ++it) {
            lines.push_back(Line(*it, *(it + 1)));
        }
    }
    return lines;
}
References lines(), and Slic3r::MultiPoint::points.
Referenced by Slic3r::GCode::_extrude(), Slic3r::LinesBucket::curLines(), equally_spaced_lines(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), is_straight(), lines(), split_at(), Slic3r::ThickPolyline::thicklines(), and Slic3r::Wipe::wipe().
new_scale()
static Polyline Slic3r::Polyline::new_scale (const std::vector< Vec2d > & points) inline static
{
    Polyline pl;
    pl.points.reserve(points.size());
    for (const Vec2d &pt : points)
      pl.points.emplace_back(Point::new_scale(pt(0), pt(1)));
        //BBS: new_scale doesn't support arc, so clean
        pl.fitting_result.clear();
    return pl;
    }
References fitting_result, and Slic3r::MultiPoint::points.
Referenced by Slic3r::GUI::Bed_2D::repaint().
operator=() [1/2]
Polyline & Slic3r::Polyline::operator= (const Polyline & other) inline
{
        points = other.points;
        fitting_result = other.fitting_result;
        return *this;
    }
References fitting_result, and Slic3r::MultiPoint::points.
operator=() [2/2]
Polyline & Slic3r::Polyline::operator= (Polyline && other) inline
{
        points = std::move(other.points);
        fitting_result = std::move(other.fitting_result);
        return *this;
    }
References fitting_result, and Slic3r::MultiPoint::points.
remove_duplicate_points()
bool Slic3r::MultiPoint::remove_duplicate_points () inherited
{
    size_t j = 0;
    for (size_t i = 1; i < points.size(); ++i) {
        if (points[j] == points[i]) {
            // Just increase index i.
        } else {
            ++ j;
            if (j < i)
                points[j] = points[i];
        }
    }
    if (++ j < points.size()) {
        points.erase(points.begin() + j, points.end());
        return true;
    }
    return false;
}
References Slic3r::MultiPoint::points.
Referenced by Slic3r::ExPolygonWithOffset::ExPolygonWithOffset(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::polylines_from_paths(), and Slic3r::traverse_graph_generate_polylines().
reset_to_linear_move()
void Slic3r::Polyline::reset_to_linear_move () private
{
    this->fitting_result.clear();
    fitting_result.emplace_back(PathFittingData{ 0, points.size() - 1, EMovePathType::Linear_move, ArcSegment() });
    this->fitting_result.shrink_to_fit();
}
References fitting_result, Slic3r::Linear_move, and Slic3r::MultiPoint::points.
reverse()
void Slic3r::Polyline::reverse ()
{
    //BBS: reverse points
    MultiPoint::reverse();
    //BBS: reverse the fitting_result
    if (!this->fitting_result.empty()) {
        for (size_t i = 0; i < this->fitting_result.size(); i++) {
            std::swap(fitting_result[i].start_point_index, fitting_result[i].end_point_index);
            fitting_result[i].start_point_index = MultiPoint::size() - 1 - fitting_result[i].start_point_index;
            fitting_result[i].end_point_index = MultiPoint::size() - 1 - fitting_result[i].end_point_index;
            if (fitting_result[i].is_arc_move())
                fitting_result[i].reverse_arc_path();
        }
        std::reverse(this->fitting_result.begin(), this->fitting_result.end());
    }
}
References fitting_result, Slic3r::MultiPoint::reverse(), and Slic3r::MultiPoint::size().
Referenced by append_before(), Slic3r::base_support_extend_infill_lines(), clip_start(), Slic3r::Fill::connect_base_support(), Slic3r::FillAdaptive::connect_lines_using_hooks(), extend_start(), Slic3r::LoopInterfaceProcessor::generate(), Slic3r::modulate_extrusion_by_overlapping_layers(), Slic3r::optimize_polylines_by_reversing(), Slic3r::ThickPolyline::reverse(), Slic3r::ExtrusionPath::reverse(), and Slic3r::take_limited().
rotate() [1/3]
void Slic3r::MultiPoint::rotate (double angle) inline inherited
{ this->rotate(cos(angle), sin(angle)); }
References Slic3r::angle(), cos(), Slic3r::MultiPoint::rotate(), and sin().
Referenced by Slic3r::ExPolygonWithOffset::ExPolygonWithOffset(), Slic3r::ExPolygonWithOffset::ExPolygonWithOffset(), Slic3r::FillHoneycomb::_fill_surface_single(), Slic3r::get_arrange_poly(), Slic3r::layered_print_cleareance_valid(), Slic3r::ExPolygon::rotate(), Slic3r::MultiPoint::rotate(), Slic3r::ExPolygon::rotate(), Slic3r::Print::sequential_print_clearance_valid(), and Slic3r::ModelInstance::transform_polygon().
rotate() [2/3]
void Slic3r::MultiPoint::rotate (double angle, const Point & center) inherited
{
    double s = sin(angle);
    double c = cos(angle);
    for (Point &pt : points) {
        Vec2crd v(pt - center);
        pt(0) = (coord_t)round(double(center(0)) + c * v[0] - s * v[1]);
        pt(1) = (coord_t)round(double(center(1)) + c * v[1] + s * v[0]);
    }
}
References Slic3r::angle(), cos(), Slic3r::MultiPoint::points, round(), and sin().
rotate() [3/3]
void Slic3r::MultiPoint::rotate (double cos_angle, double sin_angle) inherited
{
    for (Point &pt : this->points) {
        double cur_x = double(pt(0));
        double cur_y = double(pt(1));
        pt(0) = coord_t(round(cos_angle * cur_x - sin_angle * cur_y));
        pt(1) = coord_t(round(cos_angle * cur_y + sin_angle * cur_x));
    }
}
References Slic3r::MultiPoint::points, and round().
scale() [1/2]
void Slic3r::MultiPoint::scale (double factor) inherited
{
    for (Point &pt : points)
        pt *= factor;
}
References Slic3r::MultiPoint::points.
Referenced by Slic3r::ExPolygon::scale(), Slic3r::ExPolygon::scale(), and Slic3r::ModelInstance::transform_polygon().
scale() [2/2]
void Slic3r::MultiPoint::scale (double factor_x, double factor_y) inherited
{
    for (Point &pt : points)
    {
    pt(0) = coord_t(pt(0) * factor_x);
    pt(1) = coord_t(pt(1) * factor_y);
    }
}
References Slic3r::MultiPoint::points.
simplify()
void Slic3r::Polyline::simplify (double tolerance)
{
    this->points = MultiPoint::_douglas_peucker(this->points, tolerance);
    this->fitting_result.clear();
}
References Slic3r::MultiPoint::_douglas_peucker(), fitting_result, and Slic3r::MultiPoint::points.
Referenced by Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), and Slic3r::ExtrusionPath::simplify().
simplify_by_fitting_arc()
void Slic3r::Polyline::simplify_by_fitting_arc (double tolerance)
{
    //BBS: do arc fit first, then use DP simplify to handle the straight part to reduce point.
    ArcFitter::do_arc_fitting_and_simplify(this->points, this->fitting_result, tolerance);
}
References Slic3r::ArcFitter::do_arc_fitting_and_simplify(), fitting_result, and Slic3r::MultiPoint::points.
Referenced by Slic3r::ExtrusionPath::simplify_by_fitting_arc().
size()
size_t Slic3r::MultiPoint::size () const inline inherited
{ return points.size(); }
References Slic3r::MultiPoint::points.
Referenced by Slic3r::BuildVolume::BuildVolume(), Slic3r::GCode::_do_export(), Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::any_expolygon_contains(), append_before(), append_fitting_result_after_append_polyline(), Slic3r::avoid_perimeters_inner(), Slic3r::SeamPlacerImpl::calculate_polygon_angles_at_vertices(), clip_end(), Slic3r::Fill::connect_base_support(), Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::contour_distance(), Slic3r::contour_distance(), Slic3r::contour_distance2(), Slic3r::Geometry::convex_hull(), Slic3r::Geometry::convex_polygons_intersect(), Slic3r::create_boundary_infill_graph(), Slic3r::emit_loops_in_band(), equally_spaced_lines(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::find_first_different_vertex(), Slic3r::fuzzy_polygon(), Slic3r::get_shortest_direction(), Slic3r::FillLightning::Layer::getBestGroundingLocation(), Slic3r::Geometry::rotcalip::Idx::inc(), Slic3r::GUI::GLModel::init_from(), Slic3r::BoundaryInfillGraph::interpolate_contour_point(), Slic3r::mark_boundary_segments_overlapping_infill(), Slic3r::mittered_offset_path_scaled(), Slic3r::move_inside_expoly(), Slic3r::move_inside_expolys(), Slic3r::need_wipe(), Slic3r::Geometry::rotcalip::Idx::next(), Slic3r::Geometry::rotcalip::Idx::next_dir(), Slic3r::Voronoi::offset(), Slic3r::Arachne::PolygonsPointIndexSegmentLocator::operator()(), Slic3r::polygons_match(), Slic3r::precompute_polygon_distances(), Slic3r::Geometry::rotcalip::Idx::prev_dir(), Slic3r::arrangement::process_arrangeable(), Slic3r::SeamPlacerImpl::process_perimeter_polygon(), Slic3r::remove_duplicates(), Slic3r::Arachne::removeColinearEdges(), Slic3r::Arachne::removeDegenerateVerts(), Slic3r::FillLightning::Node::removeJunctionOverlap(), Slic3r::resample_polygon(), Slic3r::resample_polygon(), reverse(), Slic3r::Arachne::simplify(), Slic3r::ExtrusionPath::size(), Slic3r::slice_region_by_vertical_lines(), Slic3r::smooth_compensation_banded(), Slic3r::smooth_outward(), Slic3r::smooth_outward(), split_at_index(), Slic3r::Arachne::WallToolPaths::stitchToolPaths(), Slic3r::take(), Slic3r::take_ccw_full(), Slic3r::take_ccw_limited(), Slic3r::take_cw_full(), Slic3r::take_cw_limited(), Slic3r::take_limited(), Slic3r::to_polyline(), and Slic3r::triangulate_wall().
split_at()
void Slic3r::Polyline::split_at (Point & point, Polyline * p1, Polyline * p2) const
{
    if (this->points.empty()) return;
    //0 judge whether the point is on the polyline
    int index = this->find_point(point);
    if (index != -1) {
        //BBS: the spilit point is on the polyline, then easy
        split_at_index(index, p1, p2);
        point = p1->is_valid()? p1->last_point(): p2->first_point();
        return;
    }
    //1 find the line to split at
    size_t line_idx = 0;
    Point p = this->first_point();
    double min = (p - point).cast<double>().norm();
    Lines lines = this->lines();
    for (Lines::const_iterator line = lines.begin(); line != lines.end(); ++line) {
        Point p_tmp = point.projection_onto(*line);
        if ((p_tmp - point).cast<double>().norm() < min) {
          p = p_tmp;
          min = (p - point).cast<double>().norm();
          line_idx = line - lines.begin();
        }
    }
    //2 judge whether the cloest point is one vertex of polyline.
    //  and spilit the polyline at different index
    index = this->find_point(p);
    if (index != -1)
    {
        this->split_at_index(index, p1, p2);
        p1->append(point);
        p2->append_before(point);
    } else {
        Polyline temp;
        this->split_at_index(line_idx, p1, &temp);
        p1->append(point);
        this->split_at_index(line_idx + 1, &temp, p2);
        p2->append_before(point);
    }
}
References append(), append_before(), Slic3r::MultiPoint::find_point(), Slic3r::MultiPoint::first_point(), Slic3r::MultiPoint::is_valid(), last_point(), lines(), min(), Slic3r::MultiPoint::points, Slic3r::Point::projection_onto(), and split_at_index().
Referenced by Slic3r::CurveAnalyzer::calculate_curvatures(), and Slic3r::ExtrusionLoop::split_at().
split_at_index()
bool Slic3r::Polyline::split_at_index (const size_t index, Polyline * p1, Polyline * p2) const
{
    if (index > this->size() - 1)
        return false;
    if (index == 0) {
        p1->clear();
        p1->append(this->first_point());
        *p2 = *this;
    } else if (index == this->size() - 1) {
        p2->clear();
        p2->append(this->last_point());
        *p1 = *this;
    } else {
        //BBS: spilit first part
        p1->clear();
        p1->points.reserve(index + 1);
        p1->points.insert(p1->begin(), this->begin(), this->begin() + index + 1);
        Point new_endpoint;
        if (this->split_fitting_result_before_index(index, new_endpoint, p1->fitting_result))
            p1->points.back() = new_endpoint;
        p2->clear();
        p2->points.reserve(this->size() - index);
        p2->points.insert(p2->begin(), this->begin() + index, this->end());
        Point new_startpoint;
        if (this->split_fitting_result_after_index(index, new_startpoint, p2->fitting_result))
            p2->points.front() = new_startpoint;
    }
    return true;
}
References append(), Slic3r::MultiPoint::begin(), clear(), Slic3r::MultiPoint::first_point(), fitting_result, last_point(), Slic3r::MultiPoint::points, Slic3r::MultiPoint::size(), split_fitting_result_after_index(), and split_fitting_result_before_index().
Referenced by split_at(), and Slic3r::ExtrusionLoop::split_at_vertex().
split_fitting_result_after_index()
bool Slic3r::Polyline::split_fitting_result_after_index (const size_t index, Point & new_startpoint, std::vector< PathFittingData > & data) const private
{
    data.clear();
    new_startpoint = this->points[index];
    if (!this->fitting_result.empty()) {
        data.reserve(this->fitting_result.size());
        for (size_t i = 0; i < this->fitting_result.size(); i++) {
            if (this->fitting_result[i].end_point_index > index)
                data.push_back(this->fitting_result[i]);
        }
        if (!data.empty()) {
            for (size_t i = 0; i < data.size(); i++) {
                if (i != 0) {
                    data[i].start_point_index -= index;
                    data[i].end_point_index -= index;
                } else {
                    data[i].end_point_index -= index;
                    //BBS: need to clip the arc and generate new start point
                    if (data.front().is_arc_move() && data.front().start_point_index < index) {
                        if (!data.front().arc_data.clip_start(this->points[index]))
                            //BBS: failed to clip arc, then return to be linear move
                            data.front().path_type = EMovePathType::Linear_move;
                        else
                            //BBS: succeed to clip arc, then update and return the new start point
                            new_startpoint = data.front().arc_data.start_point;
                    }
                    data[i].start_point_index = 0;
                }
            }
        }
        data.shrink_to_fit();
        return true;
    }
    return false;
}
References fitting_result, Slic3r::Linear_move, and Slic3r::MultiPoint::points.
Referenced by split_at_index().
split_fitting_result_before_index()
bool Slic3r::Polyline::split_fitting_result_before_index (const size_t index, Point & new_endpoint, std::vector< PathFittingData > & data) const private
{
    data.clear();
    new_endpoint = this->points[index];
    if (!this->fitting_result.empty()) {
        //BBS: max size
        data.reserve(this->fitting_result.size());
        //BBS: save fitting result before index
        for (size_t i = 0; i < this->fitting_result.size(); i++)
        {
            if (this->fitting_result[i].start_point_index < index)
                data.push_back(this->fitting_result[i]);
            else
                break;
        }
        if (!data.empty()) {
            //BBS: need to clip the arc and generate new end point
            if (data.back().is_arc_move() && data.back().end_point_index > index) {
                if (!data.back().arc_data.clip_end(this->points[index]))
                    //BBS: failed to clip arc, then return to be linear move
                    data.back().path_type = EMovePathType::Linear_move;
                else
                    //BBS: succeed to clip arc, then update and return the new end point
                    new_endpoint = data.back().arc_data.end_point;
            }
            data.back().end_point_index = index;
        }
        data.shrink_to_fit();
        return true;
    }
    return false;
}
References fitting_result, Slic3r::Linear_move, and Slic3r::MultiPoint::points.
Referenced by split_at_index().
translate() [1/2]
void Slic3r::MultiPoint::translate (const Point & vector) inherited
{
    for (Point &pt : points)
        pt += v;
}
References Slic3r::MultiPoint::points.
translate() [2/2]
void Slic3r::MultiPoint::translate (double x, double y) inline inherited
{ this->translate(Point(coord_t(x), coord_t(y))); }
References Slic3r::MultiPoint::translate().
Referenced by Slic3r::ModelVolume::calculate_convex_hull_2d(), Slic3r::LinesBucket::curLines(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::get_arrange_poly(), Slic3r::ModelVolume::get_convex_hull_2d(), Slic3r::DoExport::init_ooze_prevention(), Slic3r::GCode::needs_retraction(), Slic3r::Print::sequential_print_clearance_valid(), Slic3r::ExPolygon::translate(), Slic3r::MultiPoint::translate(), and Slic3r::AvoidCrossingPerimeters::travel_to().
visivalingam()
Points Slic3r::MultiPoint::visivalingam (const Points & pts, const double tolerance) static inherited
{
    // Make sure there's enough points in "pts" to bother with simplification.
    assert(pts.size() >= 2);
     // Result object
    Points results;
     // Lambda to calculate effective area spanned by a point and its immediate
    // successor + predecessor.
    auto effective_area = [pts](const size_t& curr_pt_idx, const size_t& prev_pt_idx, const size_t& next_pt_idx)->coordf_t {
        const Point& curr = pts[curr_pt_idx];
        const Point& prev = pts[prev_pt_idx];
        const Point& next = pts[next_pt_idx];
        // Use point objects as vector-distances
    const Vec2d curr_to_next = (next - curr).cast<double>();
    const Vec2d prev_to_next = (prev - curr).cast<double>();
        // Take cross product of these two vector distances
    return 0.50 * abs(cross2(curr_to_next, prev_to_next));
    };
     // We store the effective areas for each node
    std::vector<coordf_t> areas;
    areas.reserve(pts.size());
     // Construct the initial set of nodes. We will make a heap out of the "heap" vector using
    // std::make_heap. node_list is used later.
    std::vector<vis_node*> node_list;
    node_list.resize(pts.size());
    std::vector<vis_node*> heap;
    heap.reserve(pts.size());
    for (size_t i = 1; i < pts.size() - 1; ++ i) {
        // Get effective area of current node.
        coordf_t area = effective_area(i, i - 1, i + 1);
        // If area is greater than some arbitrarily small value, use it.
        node_list[i] = new vis_node(i, i - 1, i + 1, area);
        heap.push_back(node_list[i]);
    }
     // Call std::make_heap, which uses the < operator by default to make "heap" into
    // a binheap, sorted by the < operator we defind in the vis_node struct
    std::make_heap(heap.begin(), heap.end());
     // Start comparing areas. Set min_area to an outrageous value initially.
    double min_area = -std::numeric_limits<double>::max();
    while (!heap.empty()) {
         // Get current node.
        vis_node* curr = heap.front();
         // Pop node we just retrieved off the heap. pop_heap moves front element in vector
        // to the back, so we can call pop_back()
        std::pop_heap(heap.begin(), heap.end());
        heap.pop_back();
         // Sanity assert check
        assert(curr == node_list[curr->pt_idx]);
         // If the current pt'ss area is less than that of the previous pt's area
        // use the last pt's area instead. This ensures we don't elimate the current
        // point without eliminating the previous
        min_area = std::max(min_area, curr->area);
         // Update prev
        vis_node* prev = node_list[curr->prev_idx];
        if(prev != nullptr){
            prev->next_idx = curr->next_idx;
            prev->area = effective_area(prev->pt_idx, prev->prev_idx, prev->next_idx);
            // For some reason, std::make_heap() is the fastest way to resort the heap. Probably needs testing.
            std::make_heap(heap.begin(), heap.end());
        }
         // Update next
        vis_node* next = node_list[curr->next_idx];
        if(next != nullptr){
            next->prev_idx = curr->prev_idx;
            next->area = effective_area(next->pt_idx, next->prev_idx, next->next_idx);
            std::make_heap(heap.begin(), heap.end());
        }
         areas[curr->pt_idx] = min_area;
        node_list[curr->pt_idx] = nullptr;
        delete curr;
    }
    // Clear node list and shrink_to_fit() (to free actual memory). Not necessary. Could be removed.
    node_list.clear();
    node_list.shrink_to_fit();
    // This lambda is how we test whether or not to keep a point.
    auto use_point = [areas, tolerance](const size_t& idx)->bool {
        assert(idx < areas.size());
        // Return true at front/back of path/areas
        if(idx == 0 || idx == areas.size() - 1){
            return true;
        }
        // Return true if area at idx is greater than minimum area to consider "valid"
        else{
            return areas[idx] > tolerance;
        }
    };
    // Use previously defined lambda to build results.
    for (size_t i = 0; i < pts.size(); ++i) {
        if (use_point(i)){
            results.push_back(pts[i]);
        }
    }
     // Check that results has at least two points
    assert(results.size() >= 2);
     // Return simplified vector of points
    return results;
}
References Slic3r::area(), Slic3r::vis_node::area, Slic3r::cross2(), Slic3r::vis_node::next_idx, Slic3r::vis_node::prev_idx, and Slic3r::vis_node::pt_idx.
Member Data Documentation
fitting_result
std::vector<PathFittingData> Slic3r::Polyline::fitting_result
Referenced by Polyline(), Polyline(), Polyline(), Polyline(), Slic3r::GCode::_extrude(), append(), append(), append_before(), append_fitting_result_after_append_points(), append_fitting_result_after_append_polyline(), clear(), clip_end(), Slic3r::from_json(), new_scale(), operator=(), operator=(), reset_to_linear_move(), reverse(), simplify(), simplify_by_fitting_arc(), Slic3r::ExtrusionLoop::split_at(), split_at_index(), Slic3r::ExtrusionLoop::split_at_vertex(), split_fitting_result_after_index(), split_fitting_result_before_index(), and Slic3r::to_json().
points
Points Slic3r::MultiPoint::points inherited
Referenced by Slic3r::BuildVolume::BuildVolume(), Polyline(), Slic3r::GCode::_do_export(), Slic3r::GCode::_extrude(), Slic3r::FillHoneycomb::_fill_surface_single(), Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::FillConcentric::_fill_surface_single(), Slic3r::_make_loops(), Slic3r::sla::ConcaveHull::add_connector_rectangles(), libnest2d::shapelike::addVertex(), Slic3r::any_expolygon_contains(), append(), append(), append_fitting_result_after_append_points(), Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::Polygon::area(), Slic3r::Polygon::area(), Slic3r::MutablePolygon::assign(), Slic3r::MultiPoint::begin(), Slic3r::MultiPoint::begin(), boost::polygon::polygon_traits< Slic3r::ExPolygon >::begin_points(), boost::polygon::polygon_traits< Slic3r::Polygon >::begin_points(), Slic3r::MultiPoint::bounding_box(), Slic3r::Geometry::MedialAxis::build(), Slic3r::CurveAnalyzer::calculate_curvatures(), Slic3r::SeamPlacerImpl::calculate_polygon_angles_at_vertices(), Slic3r::MultiPoint::cbegin(), Slic3r::MultiPoint::cend(), Slic3r::Polygon::centroid(), Slic3r::chain_lines(), Slic3r::ExPolygon::clear(), Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox(), Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox(), clip_end(), clip_start(), Slic3r::SupportMaterialInternal::collect_bridging_perimeter_areas(), Slic3r::ExtrusionPath::collect_points(), Slic3r::ExtrusionMultiPath::collect_points(), Slic3r::ExtrusionLoop::collect_points(), Slic3r::compSecondMoment(), Slic3r::Polygon::concave_points(), Slic3r::Fill::connect_base_support(), Slic3r::connect_brim_lines(), Slic3r::Fill::connect_infill(), Slic3r::FillAdaptive::connect_lines_using_hooks(), Slic3r::TreeSupport::contact_nodes_to_polygon(), Slic3r::contains(), Slic3r::contour_distance(), Slic3r::contours_simplified(), Slic3r::EdgeGrid::Grid::contours_simplified(), Slic3r::Geometry::convex_hull(), Slic3r::ModelObject::convex_hull_2d(), Slic3r::Geometry::convex_hulll(), Slic3r::Polygon::convex_points(), Slic3r::count_points(), Slic3r::count_points(), Slic3r::EdgeGrid::Grid::create(), Slic3r::EdgeGrid::Grid::create(), libnest2d::shapelike::create(), Slic3r::create_boundary_infill_graph(), Slic3r::Polygon::densify(), Slic3r::diff(), Slic3r::diff_ex(), Slic3r::diff_pl(), Slic3r::diff_pl(), Slic3r::distance_of_segmens(), Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint(), Slic3r::Polygon::douglas_peucker(), Slic3r::elephant_foot_compensation(), Slic3r::ExPolygon::empty(), Slic3r::MultiPoint::empty(), Slic3r::MultiPoint::end(), Slic3r::MultiPoint::end(), boost::polygon::polygon_traits< Slic3r::ExPolygon >::end_points(), boost::polygon::polygon_traits< Slic3r::Polygon >::end_points(), equally_spaced_lines(), equally_spaced_points(), Slic3r::evaluate_support_arch_cost(), Slic3r::evaluate_support_arches(), extend_end(), Slic3r::SupportGridPattern::extract_support(), Slic3r::ExtrusionSimulator::extrude_to_accumulator(), Slic3r::extrusion_entities_append_loops(), Slic3r::extrusion_polyline_extents(), Slic3r::fill_expolygons_with_sheath_generate_paths(), Slic3r::FillConcentricInternal::fill_surface_extrusion(), Slic3r::find_first_different_vertex(), Slic3r::MultiPoint::find_point(), Slic3r::MultiPoint::find_point(), Slic3r::Polygon::first_intersection(), Slic3r::ExtrusionPath::first_point(), Slic3r::anonymous_namespace{SL1.cpp}::foreach_vertex(), Slic3r::sla::foreach_vertex(), Slic3r::from_json(), Slic3r::from_json(), Slic3r::fuzzy_polygon(), Slic3r::LoopInterfaceProcessor::generate(), Slic3r::TreeSupport::generate_contact_points(), Slic3r::get_all_polygons(), Slic3r::get_arrange_poly(), Slic3r::get_bed_shape_with_excluded_area(), Slic3r::get_extents(), Slic3r::get_extents(), Slic3r::get_extents_rotated(), Slic3r::get_extents_rotated(), Slic3r::SVG::get_path_d(), Slic3r::get_polygon_vertex_inward_normal(), Slic3r::get_polygon_vertex_offset(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::FillLightning::Layer::getBestGroundingLocation(), Slic3r::MultiPoint::has_duplicate_points(), Slic3r::has_duplicate_points(), Slic3r::has_duplicate_points(), Slic3r::has_duplicate_points(), Slic3r::FillAdaptive::has_no_collinear_lines(), Slic3r::Wipe::has_path(), Slic3r::Polygon::intersection(), Slic3r::intersection(), Slic3r::intersection_pl(), Slic3r::intersection_pl(), Slic3r::intersection_pl(), Slic3r::Polygon::intersections(), Slic3r::Geometry::is_ccw(), Slic3r::ExtrusionPath::is_closed(), is_closed(), Slic3r::Arachne::ExtrusionLine::is_contour(), Slic3r::Polygon::is_counter_clockwise(), Slic3r::Polygon::is_valid(), Slic3r::SupportGridPattern::island_samples(), Slic3r::Polygon::last_point(), Slic3r::ExtrusionPath::last_point(), last_point(), Slic3r::layered_print_cleareance_valid(), leftmost_point(), Slic3r::Polygon::length(), lines(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::make_brim_ears(), Slic3r::make_expolygons_simple(), Slic3r::make_wave(), Slic3r::makeGrid(), Slic3r::mark_boundary_segments_overlapping_infill(), Slic3r::ExPolygon::medial_axis(), Slic3r::modulate_extrusion_by_overlapping_layers(), Slic3r::move_inside_expoly(), Slic3r::move_inside_expolys(), Slic3r::GCode::needs_retraction(), Slic3r::Polygon::new_scale(), new_scale(), Slic3r::Voronoi::offset(), Slic3r::offset(), Slic3r::offset(), Slic3r::offset_expolygon_inner(), Slic3r::operator!=(), Slic3r::operator!=(), Slic3r::ClipperUtils::ExPolygonProvider::iterator::operator*(), Slic3r::MultiPoint::operator=(), Slic3r::Polygon::operator=(), operator=(), Slic3r::MultiPoint::operator=(), Slic3r::Polygon::operator=(), operator=(), Slic3r::operator==(), Slic3r::operator==(), Slic3r::Polygon::operator[](), Slic3r::Polygon::operator[](), Slic3r::FillAdaptive::Intersection::other_hook(), Slic3r::ExPolygon::overlaps(), Slic3r::Polygon::parameter_by_length(), Slic3r::Polygon::point_projection(), Slic3r::ExtrusionLoop::polygon(), Slic3r::BoundingBox3Base< PointClass >::polygon(), Slic3r::MutablePolygon::polygon(), Slic3r::BoundingBox::polygon(), Slic3r::polygon_is_convex(), Slic3r::polygon_segment_append(), Slic3r::polygon_segment_append_reversed(), Slic3r::polygon_to_string(), Slic3r::polygons_match(), Slic3r::polylines_from_paths(), Slic3r::precompute_polygon_distances(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::Geometry::MedialAxis::process_edge_neighbors(), Slic3r::sla::raster_to_polygons(), Slic3r::PrintObject::remove_bridges_from_contacts(), Slic3r::remove_collinear(), Slic3r::MultiPoint::remove_duplicate_points(), Slic3r::remove_sticks(), Slic3r::Arachne::removeColinearEdges(), Slic3r::Arachne::removeDegenerateVerts(), Slic3r::FillLightning::Node::removeJunctionOverlap(), Slic3r::reorder_by_shortest_traverse(), Slic3r::resample_polygon(), libnest2d::shapelike::reserve(), reset_to_linear_move(), Slic3r::anonymous_namespace{SL1.cpp}::rings_to_expolygons(), Slic3r::MultiPoint::rotate(), Slic3r::MultiPoint::rotate(), Slic3r::MultiPoint::scale(), Slic3r::MultiPoint::scale(), Slic3r::segment_length(), Slic3r::Print::sequential_print_clearance_valid(), boost::polygon::polygon_mutable_traits< Slic3r::ExPolygon >::set_points(), boost::polygon::polygon_mutable_traits< Slic3r::Polygon >::set_points(), Slic3r::GUI::Plater::setPrintSpeedTable(), simplify(), Slic3r::Polygon::simplify(), Slic3r::Arachne::simplify(), simplify_by_fitting_arc(), Slic3r::ExPolygon::simplify_p(), Slic3r::Geometry::simplify_polygons(), Slic3r::MultiPoint::size(), boost::polygon::polygon_traits< Slic3r::ExPolygon >::size(), boost::polygon::polygon_traits< Slic3r::Polygon >::size(), Slic3r::slice_region_by_vertical_lines(), Slic3r::TreeSupport::spanning_tree_to_polygon(), Slic3r::ExtrusionLoop::split_at(), split_at(), split_at_index(), Slic3r::Polygon::split_at_index(), Slic3r::Polygon::split_at_vertex(), Slic3r::ExtrusionLoop::split_at_vertex(), split_fitting_result_after_index(), split_fitting_result_before_index(), Slic3r::take(), Slic3r::take_ccw_full(), Slic3r::take_ccw_limited(), Slic3r::take_cw_full(), Slic3r::take_cw_limited(), Slic3r::take_limited(), Slic3r::GluTessWrapper::tesselate3d(), Slic3r::thick_polyline_to_extrusion_paths(), Slic3r::ThickPolyline::thicklines(), Slic3r::to_json(), Slic3r::to_json(), Slic3r::to_lines(), Slic3r::to_lines(), Slic3r::to_lines(), Slic3r::to_lines(), Slic3r::to_lines(), Slic3r::to_linesf(), Slic3r::sla::AGGRaster< PixelRenderer, Renderer, Rasterizer, Scanline >::to_path(), Slic3r::to_points(), Slic3r::to_points(), Slic3r::to_points(), Slic3r::to_polygon(), Slic3r::to_polyline(), Slic3r::to_polyline(), Slic3r::to_polylines(), Slic3r::to_polylines(), Slic3r::to_polylines(), Slic3r::to_polylines(), Slic3r::to_polylines(), Slic3r::Arachne::ExtrusionLine::toPolygon(), libnest2d::shapelike::toString(), Slic3r::Polygon::transform(), Slic3r::MultiPoint::translate(), Slic3r::AvoidCrossingPerimeters::travel_to(), Slic3r::traverse_graph_generate_polylines(), Slic3r::traverse_loops(), Slic3r::traverse_pt(), Slic3r::Polygon::triangulate_convex(), Slic3r::triangulate_wall(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), Slic3r::GUI::GLGizmoText::update_text_positions(), Slic3r::variable_offset_inner(), Slic3r::variable_offset_inner_ex(), Slic3r::variable_offset_outer(), Slic3r::variable_offset_outer_ex(), Slic3r::wall_strip(), and Slic3r::Wipe::wipe().
The documentation for this class was generated from the following files:
src/libslic3r/Polyline.hpp
src/libslic3r/Polyline.cpp