OrcaSlicer: Clipper2Lib Namespace Reference
Clipper2Lib Namespace Reference
Namespaces
namespace detail
namespace details
Classes
struct Active
class Clipper2Exception
class Clipper64
class ClipperBase
class ClipperD
class ClipperOffset
struct CPolyPath64
struct CPolyPathD
struct CRect
struct IntersectNode
struct Joiner
struct LocalMinima
struct LocMinSorter
struct OutPt
struct OutRec
struct Point
class PolyPath
class PolyPath64
class PolyPathD
struct Rect
class RectClip
class RectClipLines
struct Scanline
struct Vertex
Typedefs
using Point64 = Point< int64_t >
using PointD = Point< double >
template<typename T >
using Path = std::vector< Point< T > >
template<typename T >
using Paths = std::vector< Path< T > >
using Path64 = Path< int64_t >
using PathD = Path< double >
using Paths64 = std::vector< Path64 >
using PathsD = std::vector< PathD >
using Rect64 = Rect< int64_t >
using RectD = Rect< double >
using PolyTree64 = PolyPath64
using PolyTreeD = PolyPathD
typedef std::vector< OutRec * > OutRecList
typedef int64_t * CPath64
typedef int64_t ** CPaths64
typedef double * CPathD
typedef double ** CPathsD
typedef struct Clipper2Lib::CPolyPath64 CPolyTree64
typedef struct Clipper2Lib::CPolyPathD CPolyTreeD
typedef CRect< int64_t > CRect64
typedef CRect< double > CRectD
Enumerations
enum class FillRule { EvenOdd , NonZero , Positive , Negative }
enum class PointInPolygonResult { IsOn , IsInside , IsOutside }
enum class ClipType {
None , Intersection , Union , Difference ,
Xor
}
enum class PathType { Subject , Clip }
enum class VertexFlags : uint32_t {
None = 0 , OpenStart = 1 , OpenEnd = 2 , LocalMax = 4 ,
LocalMin = 8
}
enum class JoinType { Square , Round , Miter }
enum class EndType {
Polygon , Joined , Butt , Square ,
Round
}
enum class Location {
Left , Top , Right , Bottom ,
Inside
}
Functions
template<typename T >
std::ostream & operator<< (std::ostream &outstream, const Path< T > &path)
template<typename T >
std::ostream & operator<< (std::ostream &outstream, const Paths< T > &paths)
template<typename T1 , typename T2 >
Path< T1 > ScalePath (const Path< T2 > &path, double scale)
template<typename T1 , typename T2 >
Paths< T1 > ScalePaths (const Paths< T2 > &paths, double scale)
template<typename T1 , typename T2 >
Path< T1 > TransformPath (const Path< T2 > &path)
template<typename T1 , typename T2 >
Paths< T1 > TransformPaths (const Paths< T2 > &paths)
PathD Path64ToPathD (const Path64 &path)
PathsD Paths64ToPathsD (const Paths64 &paths)
Path64 PathDToPath64 (const PathD &path)
Paths64 PathsDToPaths64 (const PathsD &paths)
template<typename T >
double Sqr (T val)
template<typename T >
bool NearEqual (const Point< T > &p1, const Point< T > &p2, double max_dist_sqrd)
template<typename T >
Path< T > StripNearEqual (const Path< T > &path, double max_dist_sqrd, bool is_closed_path)
template<typename T >
Paths< T > StripNearEqual (const Paths< T > &paths, double max_dist_sqrd, bool is_closed_path)
template<typename T >
Path< T > StripDuplicates (const Path< T > &path, bool is_closed_path)
template<typename T >
Paths< T > StripDuplicates (const Paths< T > &paths, bool is_closed_path)
template<typename T1 , typename T2 >
Rect< T1 > ScaleRect (const Rect< T2 > &rect, double scale)
void CheckPrecision (int &precision)
template<typename T >
double CrossProduct (const Point< T > &pt1, const Point< T > &pt2, const Point< T > &pt3)
template<typename T >
double CrossProduct (const Point< T > &vec1, const Point< T > &vec2)
template<typename T >
double DotProduct (const Point< T > &pt1, const Point< T > &pt2, const Point< T > &pt3)
template<typename T >
double DotProduct (const Point< T > &vec1, const Point< T > &vec2)
template<typename T >
double DistanceSqr (const Point< T > pt1, const Point< T > pt2)
template<typename T >
double DistanceFromLineSqrd (const Point< T > &pt, const Point< T > &ln1, const Point< T > &ln2)
template<typename T >
double Area (const Path< T > &path)
template<typename T >
double Area (const Paths< T > &paths)
template<typename T >
bool IsPositive (const Path< T > &poly)
bool SegmentsIntersect (const Point64 &seg1a, const Point64 &seg1b, const Point64 &seg2a, const Point64 &seg2b, bool inclusive=false)
template<typename T >
PointInPolygonResult PointInPolygon (const Point< T > &pt, const Path< T > &polygon)
constexpr enum VertexFlags operator& (enum VertexFlags a, enum VertexFlags b)
constexpr enum VertexFlags operator| (enum VertexFlags a, enum VertexFlags b)
template<typename T >
bool CRectIsEmpty (const CRect< T > &rect)
template<typename T >
Rect< T > CRectToRect (const CRect< T > &rect)
EXTERN_DLL_EXPORT const char * Version ()
EXTERN_DLL_EXPORT void DisposeExportedCPath64 (CPath64 p)
EXTERN_DLL_EXPORT void DisposeExportedCPaths64 (CPaths64 &pp)
EXTERN_DLL_EXPORT void DisposeExportedCPathD (CPathD p)
EXTERN_DLL_EXPORT void DisposeExportedCPathsD (CPathsD &pp)
EXTERN_DLL_EXPORT void DisposeExportedCPolyTree64 (CPolyTree64 *&cpt)
EXTERN_DLL_EXPORT void DisposeExportedCPolyTreeD (CPolyTreeD *&cpt)
EXTERN_DLL_EXPORT int BooleanOp64 (uint8_t cliptype, uint8_t fillrule, const CPaths64 subjects, const CPaths64 subjects_open, const CPaths64 clips, CPaths64 &solution, CPaths64 &solution_open, bool preserve_collinear=true, bool reverse_solution=false)
EXTERN_DLL_EXPORT int BooleanOpPt64 (uint8_t cliptype, uint8_t fillrule, const CPaths64 subjects, const CPaths64 subjects_open, const CPaths64 clips, CPolyTree64 *&solution, CPaths64 &solution_open, bool preserve_collinear=true, bool reverse_solution=false)
EXTERN_DLL_EXPORT int BooleanOpD (uint8_t cliptype, uint8_t fillrule, const CPathsD subjects, const CPathsD subjects_open, const CPathsD clips, CPathsD &solution, CPathsD &solution_open, int precision=2, bool preserve_collinear=true, bool reverse_solution=false)
EXTERN_DLL_EXPORT int BooleanOpPtD (uint8_t cliptype, uint8_t fillrule, const CPathsD subjects, const CPathsD subjects_open, const CPathsD clips, CPolyTreeD *&solution, CPathsD &solution_open, int precision=2, bool preserve_collinear=true, bool reverse_solution=false)
EXTERN_DLL_EXPORT CPaths64 InflatePaths64 (const CPaths64 paths, double delta, uint8_t jointype, uint8_t endtype, double miter_limit=2.0, double arc_tolerance=0.0, bool reverse_solution=false)
EXTERN_DLL_EXPORT CPathsD InflatePathsD (const CPathsD paths, double delta, uint8_t jointype, uint8_t endtype, int precision=2, double miter_limit=2.0, double arc_tolerance=0.0, bool reverse_solution=false)
EXTERN_DLL_EXPORT CPaths64 RectClip64 (const CRect64 &rect, const CPaths64 paths)
EXTERN_DLL_EXPORT CPathsD RectClipD (const CRectD &rect, const CPathsD paths, int precision=2)
EXTERN_DLL_EXPORT CPaths64 RectClipLines64 (const CRect64 &rect, const CPaths64 paths)
EXTERN_DLL_EXPORT CPathsD RectClipLinesD (const CRectD &rect, const CPathsD paths, int precision=2)
CPath64 CreateCPath64 (size_t cnt1, size_t cnt2)
CPath64 CreateCPath64 (const Path64 &p)
CPaths64 CreateCPaths64 (const Paths64 &pp)
Path64 ConvertCPath64 (const CPath64 &p)
Paths64 ConvertCPaths64 (const CPaths64 &pp)
CPathD CreateCPathD (size_t cnt1, size_t cnt2)
CPathD CreateCPathD (const PathD &p)
CPathsD CreateCPathsD (const PathsD &pp)
PathD ConvertCPathD (const CPathD &p)
PathsD ConvertCPathsD (const CPathsD &pp)
CPathD CreateCPathD (const Path64 &p, double scale)
CPathsD CreateCPathsD (const Paths64 &pp, double scale)
Path64 ConvertCPathD (const CPathD &p, double scale)
Paths64 ConvertCPathsD (const CPathsD &pp, double scale)
CPolyTree64 * CreateCPolyTree64 (const PolyTree64 &pt)
CPolyTreeD * CreateCPolyTreeD (const PolyTree64 &pt, double scale)
void InitCPolyPath64 (CPolyTree64 *cpt, bool is_hole, const PolyPath64 *pp)
void DisposeCPolyPath64 (CPolyPath64 *cpp)
void InitCPolyPathD (CPolyTreeD *cpt, bool is_hole, const PolyPath64 *pp, double scale)
void DisposeCPolyPathD (CPolyPathD *cpp)
Paths64 BooleanOp (ClipType cliptype, FillRule fillrule, const Paths64 &subjects, const Paths64 &clips)
void BooleanOp (ClipType cliptype, FillRule fillrule, const Paths64 &subjects, const Paths64 &clips, PolyTree64 &solution)
PathsD BooleanOp (ClipType cliptype, FillRule fillrule, const PathsD &subjects, const PathsD &clips, int decimal_prec=2)
void BooleanOp (ClipType cliptype, FillRule fillrule, const PathsD &subjects, const PathsD &clips, PolyTreeD &polytree, int decimal_prec=2)
Paths64 Intersect (const Paths64 &subjects, const Paths64 &clips, FillRule fillrule)
PathsD Intersect (const PathsD &subjects, const PathsD &clips, FillRule fillrule, int decimal_prec=2)
Paths64 Union (const Paths64 &subjects, const Paths64 &clips, FillRule fillrule)
PathsD Union (const PathsD &subjects, const PathsD &clips, FillRule fillrule, int decimal_prec=2)
Paths64 Union (const Paths64 &subjects, FillRule fillrule)
PathsD Union (const PathsD &subjects, FillRule fillrule, int decimal_prec=2)
Paths64 Difference (const Paths64 &subjects, const Paths64 &clips, FillRule fillrule)
PathsD Difference (const PathsD &subjects, const PathsD &clips, FillRule fillrule, int decimal_prec=2)
Paths64 Xor (const Paths64 &subjects, const Paths64 &clips, FillRule fillrule)
PathsD Xor (const PathsD &subjects, const PathsD &clips, FillRule fillrule, int decimal_prec=2)
Paths64 InflatePaths (const Paths64 &paths, double delta, JoinType jt, EndType et, double miter_limit=2.0)
PathsD InflatePaths (const PathsD &paths, double delta, JoinType jt, EndType et, double miter_limit=2.0, int precision=2)
Path64 TranslatePath (const Path64 &path, int64_t dx, int64_t dy)
PathD TranslatePath (const PathD &path, double dx, double dy)
Paths64 TranslatePaths (const Paths64 &paths, int64_t dx, int64_t dy)
PathsD TranslatePaths (const PathsD &paths, double dx, double dy)
Rect64 Bounds (const Path64 &path)
Rect64 Bounds (const Paths64 &paths)
RectD Bounds (const PathD &path)
RectD Bounds (const PathsD &paths)
Path64 RectClip (const Rect64 &rect, const Path64 &path)
Paths64 RectClip (const Rect64 &rect, const Paths64 &paths)
PathD RectClip (const RectD &rect, const PathD &path, int precision=2)
PathsD RectClip (const RectD &rect, const PathsD &paths, int precision=2)
Paths64 RectClipLines (const Rect64 &rect, const Path64 &path)
Paths64 RectClipLines (const Rect64 &rect, const Paths64 &paths)
PathsD RectClipLines (const RectD &rect, const PathD &path, int precision=2)
PathsD RectClipLines (const RectD &rect, const PathsD &paths, int precision=2)
Paths64 PolyTreeToPaths64 (const PolyTree64 &polytree)
PathsD PolyTreeToPathsD (const PolyTreeD &polytree)
bool CheckPolytreeFullyContainsChildren (const PolyTree64 &polytree)
Path64 MakePath (const std::string &s)
PathD MakePathD (const std::string &s)
Path64 TrimCollinear (const Path64 &p, bool is_open_path=false)
PathD TrimCollinear (const PathD &path, int precision, bool is_open_path=false)
template<typename T >
double Distance (const Point< T > pt1, const Point< T > pt2)
template<typename T >
double Length (const Path< T > &path, bool is_closed_path=false)
template<typename T >
bool NearCollinear (const Point< T > &pt1, const Point< T > &pt2, const Point< T > &pt3, double sin_sqrd_min_angle_rads)
template<typename T >
Path< T > Ellipse (const Rect< T > &rect, int steps=0)
template<typename T >
Path< T > Ellipse (const Point< T > &center, double radiusX, double radiusY=0, int steps=0)
template<typename T >
double PerpendicDistFromLineSqrd (const Point< T > &pt, const Point< T > &line1, const Point< T > &line2)
template<typename T >
void RDP (const Path< T > path, std::size_t begin, std::size_t end, double epsSqrd, std::vector< bool > &flags)
template<typename T >
Path< T > RamerDouglasPeucker (const Path< T > &path, double epsilon)
template<typename T >
Paths< T > RamerDouglasPeucker (const Paths< T > &paths, double epsilon)
Paths64 MinkowskiSum (const Path64 &pattern, const Path64 &path, bool isClosed)
PathsD MinkowskiSum (const PathD &pattern, const PathD &path, bool isClosed, int decimalPlaces=2)
Paths64 MinkowskiDiff (const Path64 &pattern, const Path64 &path, bool isClosed)
PathsD MinkowskiDiff (const PathD &pattern, const PathD &path, bool isClosed, int decimalPlaces=2)
bool IsOdd (int val)
bool IsHotEdge (const Active &e)
bool IsOpen (const Active &e)
bool IsOpenEnd (const Vertex &v)
bool IsOpenEnd (const Active &ae)
Active * GetPrevHotEdge (const Active &e)
bool IsFront (const Active &e)
bool IsInvalidPath (OutPt *op)
double GetDx (const Point64 &pt1, const Point64 &pt2)
int64_t TopX (const Active &ae, const int64_t currentY)
bool IsHorizontal (const Active &e)
bool IsHeadingRightHorz (const Active &e)
bool IsHeadingLeftHorz (const Active &e)
void SwapActives (Active *&e1, Active *&e2)
PathType GetPolyType (const Active &e)
bool IsSamePolyType (const Active &e1, const Active &e2)
Point64 GetEndE1ClosestToEndE2 (const Active &e1, const Active &e2)
Point64 GetIntersectPoint (const Active &e1, const Active &e2)
bool GetIntersectPoint (const Point64 &ln1a, const Point64 &ln1b, const Point64 &ln2a, const Point64 &ln2b, PointD &ip)
void SetDx (Active &e)
Vertex * NextVertex (const Active &e)
Vertex * PrevPrevVertex (const Active &ae)
Active * ExtractFromSEL (Active *ae)
void Insert1Before2InSEL (Active *ae1, Active *ae2)
bool IsMaxima (const Vertex &v)
bool IsMaxima (const Active &e)
Vertex * GetCurrYMaximaVertex (const Active &e)
Active * GetMaximaPair (const Active &e)
Active * GetHorzMaximaPair (const Active &horz, const Vertex *vert_max)
int PointCount (OutPt *op)
OutPt * InsertOp (const Point64 &pt, OutPt *insertAfter)
OutPt * DisposeOutPt (OutPt *op)
void DisposeOutPts (OutRec &outrec)
bool IntersectListSort (const IntersectNode &a, const IntersectNode &b)
void SetSides (OutRec &outrec, Active &start_edge, Active &end_edge)
void SwapOutrecs (Active &e1, Active &e2)
double Area (OutPt *op)
double AreaTriangle (const Point64 &pt1, const Point64 &pt2, const Point64 &pt3)
void ReverseOutPts (OutPt *op)
void SwapSides (OutRec &outrec)
OutRec * GetRealOutRec (OutRec *outrec)
void UncoupleOutRec (Active ae)
bool PtsReallyClose (const Point64 &pt1, const Point64 &pt2)
bool IsVerySmallTriangle (const OutPt &op)
bool IsValidClosedPath (const OutPt *op)
bool OutrecIsAscending (const Active *hotEdge)
void SwapFrontBackSides (OutRec &outrec)
bool EdgesAdjacentInAEL (const IntersectNode &inode)
bool TestJoinWithPrev1 (const Active &e)
bool TestJoinWithPrev2 (const Active &e, const Point64 &curr_pt)
bool TestJoinWithNext1 (const Active &e)
bool TestJoinWithNext2 (const Active &e, const Point64 &curr_pt)
bool IsValidAelOrder (const Active &resident, const Active &newcomer)
void InsertRightEdge (Active &e, Active &e2)
void UpdateOutrecOwner (OutRec *outrec)
Active * FindEdgeWithMatchingLocMin (Active *e)
bool HorzIsSpike (const Active &horzEdge)
void TrimHorz (Active &horzEdge, bool preserveCollinear)
Joiner * FindTrialJoinParent (Joiner *&joiner, const OutPt *op)
bool GetHorzExtendedHorzSeg (OutPt *&op, OutPt *&op2)
bool HorzEdgesOverlap (int64_t x1a, int64_t x1b, int64_t x2a, int64_t x2b)
bool ValueBetween (int64_t val, int64_t end1, int64_t end2)
bool ValueEqualOrBetween (int64_t val, int64_t end1, int64_t end2)
bool PointBetween (Point64 pt, Point64 corner1, Point64 corner2)
bool PointEqualOrBetween (Point64 pt, Point64 corner1, Point64 corner2)
Joiner * FindJoinParent (const Joiner *joiner, OutPt *op)
bool CheckDisposeAdjacent (OutPt *&op, const OutPt *guard, OutRec &outRec)
bool IsValidPath (OutPt *op)
bool CollinearSegsOverlap (const Point64 &seg1a, const Point64 &seg1b, const Point64 &seg2a, const Point64 &seg2b)
bool Path1InsidePath2 (const OutRec *or1, const OutRec *or2)
Rect64 GetBounds (const Path64 &path)
bool BuildPath64 (OutPt *op, bool reverse, bool isOpen, Path64 &path)
bool BuildPathD (OutPt *op, bool reverse, bool isOpen, PathD &path, double inv_scale)
Paths64::size_type GetLowestPolygonIdx (const Paths64 &paths)
PointD GetUnitNormal (const Point64 &pt1, const Point64 &pt2)
bool AlmostZero (double value, double epsilon=0.001)
double Hypot (double x, double y)
PointD NormalizeVector (const PointD &vec)
PointD GetAvgUnitVector (const PointD &vec1, const PointD &vec2)
bool IsClosedPath (EndType et)
Point64 GetPerpendic (const Point64 &pt, const PointD &norm, double delta)
PointD GetPerpendicD (const Point64 &pt, const PointD &norm, double delta)
PointD TranslatePoint (const PointD &pt, double dx, double dy)
PointD ReflectPoint (const PointD &pt, const PointD &pivot)
PointD IntersectPoint (const PointD &pt1a, const PointD &pt1b, const PointD &pt2a, const PointD &pt2b)
PointInPolygonResult Path1ContainsPath2 (Path64 path1, Path64 path2)
bool GetLocation (const Rect64 &rec, const Point64 &pt, Location &loc)
Point64 GetIntersectPoint64 (const Point64 &ln1a, const Point64 &ln1b, const Point64 &ln2a, const Point64 &ln2b)
bool GetIntersection (const Path64 &rectPath, const Point64 &p, const Point64 &p2, Location &loc, Point64 &ip)
Location GetAdjacentLocation (Location loc, bool isClockwise)
bool HeadingClockwise (Location prev, Location curr)
bool AreOpposites (Location prev, Location curr)
bool IsClockwise (Location prev, Location curr, Point64 prev_pt, Point64 curr_pt, Point64 rect_mp)
Variables
static const char * precision_error
static double const PI = 3.141592653589793238
static int64_t const MAX_COORD = LLONG_MAX / 2
static const Rect64 MaxInvalidRect64
static const RectD MaxInvalidRectD
static const double FloatingPointTolerance = 1.0e-12
static const Rect64 invalid_rect
const double default_arc_tolerance = 0.25
const double floating_point_tolerance = 1e-12
Class Documentation
Clipper2Lib::Active
struct Clipper2Lib::Active
Class Members
Point64 bot
int64_t curr_x = 0
double dx = 0.0
bool is_left_bound = false
Active * jump = nullptr
LocalMinima * local_min = nullptr
Active * next_in_ael = nullptr
Active * next_in_sel = nullptr
OutRec * outrec = nullptr
Active * prev_in_ael = nullptr
Active * prev_in_sel = nullptr
Point64 top
Vertex * vertex_top = nullptr
int wind_cnt = 0
int wind_cnt2 = 0
int wind_dx = 1
Clipper2Lib::CPolyPath64
struct Clipper2Lib::CPolyPath64
Class Members
uint32_t child_count
CPolyPath64 * childs
uint32_t is_hole
CPath64 polygon
Clipper2Lib::CPolyPathD
struct Clipper2Lib::CPolyPathD
Class Members
uint32_t child_count
CPolyPathD * childs
uint32_t is_hole
CPathD polygon
Clipper2Lib::CRect
struct Clipper2Lib::CRect
template<typename T>
struct Clipper2Lib::CRect< T >
Class Members
T bottom
T left
T right
T top
Clipper2Lib::Vertex
struct Clipper2Lib::Vertex
Class Members
VertexFlags flags = VertexFlags::None
Vertex * next = nullptr
Vertex * prev = nullptr
Point64 pt
Typedef Documentation
CPath64
typedef int64_t* Clipper2Lib::CPath64
CPathD
typedef double* Clipper2Lib::CPathD
CPaths64
typedef int64_t** Clipper2Lib::CPaths64
CPathsD
typedef double** Clipper2Lib::CPathsD
CPolyTree64
typedef struct Clipper2Lib::CPolyPath64 Clipper2Lib::CPolyTree64
CPolyTreeD
typedef struct Clipper2Lib::CPolyPathD Clipper2Lib::CPolyTreeD
CRect64
typedef CRect<int64_t> Clipper2Lib::CRect64
CRectD
typedef CRect<double> Clipper2Lib::CRectD
OutRecList
typedef std::vector<OutRec*> Clipper2Lib::OutRecList
Path
template<typename T > using Clipper2Lib::Path = typedef std::vector<Point<T> >
Path64
using Clipper2Lib::Path64 = typedef Path<int64_t>
PathD
using Clipper2Lib::PathD = typedef Path<double>
Paths
template<typename T > using Clipper2Lib::Paths = typedef std::vector<Path<T> >
Paths64
using Clipper2Lib::Paths64 = typedef std::vector< Path64>
PathsD
using Clipper2Lib::PathsD = typedef std::vector< PathD>
Point64
using Clipper2Lib::Point64 = typedef Point<int64_t>
PointD
using Clipper2Lib::PointD = typedef Point<double>
PolyTree64
using Clipper2Lib::PolyTree64 = typedef PolyPath64
PolyTreeD
using Clipper2Lib::PolyTreeD = typedef PolyPathD
Rect64
using Clipper2Lib::Rect64 = typedef Rect<int64_t>
RectD
using Clipper2Lib::RectD = typedef Rect<double>
Enumeration Type Documentation
ClipType
enum class Clipper2Lib::ClipType strong
Enumerator
None
Intersection
Union
Difference
Xor
{ None, Intersection, Union, Difference, Xor };
EndType
enum class Clipper2Lib::EndType strong
Enumerator
Polygon
Joined
Butt
Square
Round
{Polygon, Joined, Butt, Square, Round};
FillRule
enum class Clipper2Lib::FillRule strong
Enumerator
EvenOdd
NonZero
Positive
Negative
{ EvenOdd, NonZero, Positive, Negative };
JoinType
enum class Clipper2Lib::JoinType strong
Enumerator
Square
Round
Miter
{ Square, Round, Miter };
Location
enum class Clipper2Lib::Location strong
Enumerator
Left
Top
Right
Bottom
Inside
{ Left, Top, Right, Bottom, Inside };
PathType
enum class Clipper2Lib::PathType strong
Enumerator
Subject
Clip
{ Subject, Clip };
PointInPolygonResult
enum class Clipper2Lib::PointInPolygonResult strong
Enumerator
IsOn
IsInside
IsOutside
{ IsOn, IsInside, IsOutside };
VertexFlags
enum class Clipper2Lib::VertexFlags : uint32_t strong
Enumerator
None
OpenStart
OpenEnd
LocalMax
LocalMin
                         : uint32_t {
    None = 0, OpenStart = 1, OpenEnd = 2, LocalMax = 4, LocalMin = 8
  };
Function Documentation
AlmostZero()
bool Clipper2Lib::AlmostZero (double value, double epsilon = 0.001) inline
{
  return std::fabs(value) < epsilon;
}
Referenced by NormalizeVector(), and Clipper2Lib::ClipperOffset::OffsetPoint().
Area() [1/3]
template<typename T > double Clipper2Lib::Area (const Path< T > & path) inline
{
  size_t cnt = path.size();
  if (cnt < 3) return 0.0;
  double a = 0.0;
  typename Path<T>::const_iterator it1, it2 = path.cend() - 1, stop = it2;
  if (!(cnt & 1)) ++stop;
  for (it1 = path.cbegin(); it1 != stop;)
  {
    a += static_cast<double>(it2->y + it1->y) * (it2->x - it1->x);
    it2 = it1 + 1;
    a += static_cast<double>(it1->y + it2->y) * (it1->x - it2->x);
    it1 += 2;
  }
  if (cnt & 1)
    a += static_cast<double>(it2->y + it1->y) * (it2->x - it1->x);
  return a * 0.5;
}
Referenced by Clipper2Lib::ClipperBase::CompleteSplit(), Clipper2Lib::ClipperOffset::DoGroupOffset(), Clipper2Lib::ClipperBase::DoSplitOp(), and Path1InsidePath2().
Area() [2/3]
template<typename T > double Clipper2Lib::Area (const Paths< T > & paths) inline
{
  double a = 0.0;
  for (typename Paths<T>::const_iterator paths_iter = paths.cbegin();
    paths_iter != paths.cend(); ++paths_iter)
  {
    a += Area<T>(*paths_iter);
  }
  return a;
}
Area() [3/3]
double Clipper2Lib::Area (OutPt * op)
  {
    //https://en.wikipedia.org/wiki/Shoelace_formula
    double result = 0.0;
    OutPt* op2 = op;
    do
    {
      result += static_cast<double>(op2->prev->pt.y + op2->pt.y) *
        static_cast<double>(op2->prev->pt.x - op2->pt.x);
      op2 = op2->next;
    } while (op2 != op);
    return result * 0.5;
  }
References Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
AreaTriangle()
double Clipper2Lib::AreaTriangle (const Point64 & pt1, const Point64 & pt2, const Point64 & pt3) inline
  {
    return (static_cast<double>(pt3.y + pt1.y) * static_cast<double>(pt3.x - pt1.x) +
      static_cast<double>(pt1.y + pt2.y) * static_cast<double>(pt1.x - pt2.x) +
      static_cast<double>(pt2.y + pt3.y) * static_cast<double>(pt2.x - pt3.x));
  }
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::DoSplitOp().
AreOpposites()
bool Clipper2Lib::AreOpposites (Location prev, Location curr) inline
  {
    return abs(static_cast<int>(prev) - static_cast<int>(curr)) == 2;
  }
Referenced by IsClockwise().
BooleanOp() [1/4]
Paths64 Clipper2Lib::BooleanOp (ClipType cliptype, FillRule fillrule, const Paths64 & subjects, const Paths64 & clips) inline
  {
    Paths64 result;
    Clipper64 clipper;
    clipper.AddSubject(subjects);
    clipper.AddClip(clips);
    clipper.Execute(cliptype, fillrule, result);
    return result;
  }
References Clipper2Lib::Clipper64::AddClip(), Clipper2Lib::Clipper64::AddSubject(), and Clipper2Lib::Clipper64::Execute().
Referenced by Difference(), Difference(), Intersect(), Intersect(), Union(), Union(), Xor(), and Xor().
BooleanOp() [2/4]
void Clipper2Lib::BooleanOp (ClipType cliptype, FillRule fillrule, const Paths64 & subjects, const Paths64 & clips, PolyTree64 & solution) inline
  {
    Paths64 sol_open;
    Clipper64 clipper;
    clipper.AddSubject(subjects);
    clipper.AddClip(clips);
    clipper.Execute(cliptype, fillrule, solution, sol_open);
  }
References Clipper2Lib::Clipper64::AddClip(), Clipper2Lib::Clipper64::AddSubject(), and Clipper2Lib::Clipper64::Execute().
BooleanOp() [3/4]
PathsD Clipper2Lib::BooleanOp (ClipType cliptype, FillRule fillrule, const PathsD & subjects, const PathsD & clips, int decimal_prec = 2) inline
  {
    CheckPrecision(decimal_prec);
    PathsD result;
    ClipperD clipper(decimal_prec);
    clipper.AddSubject(subjects);
    clipper.AddClip(clips);
    clipper.Execute(cliptype, fillrule, result);
    return result;
  }
References Clipper2Lib::ClipperD::AddClip(), Clipper2Lib::ClipperD::AddSubject(), CheckPrecision(), and Clipper2Lib::ClipperD::Execute().
BooleanOp() [4/4]
void Clipper2Lib::BooleanOp (ClipType cliptype, FillRule fillrule, const PathsD & subjects, const PathsD & clips, PolyTreeD & polytree, int decimal_prec = 2) inline
  {
    CheckPrecision(decimal_prec);
    PathsD result;
    ClipperD clipper(decimal_prec);
    clipper.AddSubject(subjects);
    clipper.AddClip(clips);
    clipper.Execute(cliptype, fillrule, polytree);
  }
References Clipper2Lib::ClipperD::AddClip(), Clipper2Lib::ClipperD::AddSubject(), CheckPrecision(), and Clipper2Lib::ClipperD::Execute().
BooleanOp64()
EXTERN_DLL_EXPORT int Clipper2Lib::BooleanOp64 (uint8_t cliptype, uint8_t fillrule, const CPaths64 subjects, const CPaths64 subjects_open, const CPaths64 clips, CPaths64 & solution, CPaths64 & solution_open, bool preserve_collinear = true, bool reverse_solution = false)
{
  if (cliptype > static_cast<uint8_t>(ClipType::Xor)) return -4;
  if (fillrule > static_cast<uint8_t>(FillRule::Negative)) return -3;
  Paths64 sub, sub_open, clp, sol, sol_open;
  sub       = ConvertCPaths64(subjects);
  sub_open  = ConvertCPaths64(subjects_open);
  clp       = ConvertCPaths64(clips);
  Clipper64 clipper;
  clipper.PreserveCollinear = preserve_collinear;
  clipper.ReverseSolution = reverse_solution;
  if (sub.size() > 0) clipper.AddSubject(sub);
  if (sub_open.size() > 0) clipper.AddOpenSubject(sub_open);
  if (clp.size() > 0) clipper.AddClip(clp);
  if (!clipper.Execute(ClipType(cliptype), FillRule(fillrule), sol, sol_open))
    return -1; // clipping bug - should never happen :)
  solution = CreateCPaths64(sol);
  solution_open = CreateCPaths64(sol_open);
  return 0; //success !!
}
References Clipper2Lib::Clipper64::AddClip(), Clipper2Lib::Clipper64::AddOpenSubject(), Clipper2Lib::Clipper64::AddSubject(), ConvertCPaths64(), CreateCPaths64(), Clipper2Lib::Clipper64::Execute(), Negative, Clipper2Lib::ClipperBase::PreserveCollinear, Clipper2Lib::ClipperBase::ReverseSolution, and Xor.
BooleanOpD()
EXTERN_DLL_EXPORT int Clipper2Lib::BooleanOpD (uint8_t cliptype, uint8_t fillrule, const CPathsD subjects, const CPathsD subjects_open, const CPathsD clips, CPathsD & solution, CPathsD & solution_open, int precision = 2, bool preserve_collinear = true, bool reverse_solution = false)
{
  if (precision < -8 || precision > 8) return -5;
  if (cliptype > static_cast<uint8_t>(ClipType::Xor)) return -4;
  if (fillrule > static_cast<uint8_t>(FillRule::Negative)) return -3;
  const double scale = std::pow(10, precision);
  Paths64 sub, sub_open, clp, sol, sol_open;
  sub       = ConvertCPathsD(subjects, scale);
  sub_open  = ConvertCPathsD(subjects_open, scale);
  clp       = ConvertCPathsD(clips, scale);
  Clipper64 clipper;
  clipper.PreserveCollinear = preserve_collinear;
  clipper.ReverseSolution = reverse_solution;
  if (sub.size() > 0) clipper.AddSubject(sub);
  if (sub_open.size() > 0)
    clipper.AddOpenSubject(sub_open);
  if (clp.size() > 0) clipper.AddClip(clp);
  if (!clipper.Execute(ClipType(cliptype),
    FillRule(fillrule), sol, sol_open)) return -1;
  if (sol.size() > 0) solution = CreateCPathsD(sol, 1 / scale);
  if (sol_open.size() > 0)
    solution_open = CreateCPathsD(sol_open, 1 / scale);
  return 0;
}
References Clipper2Lib::Clipper64::AddClip(), Clipper2Lib::Clipper64::AddOpenSubject(), Clipper2Lib::Clipper64::AddSubject(), ConvertCPathsD(), CreateCPathsD(), Clipper2Lib::Clipper64::Execute(), Negative, Clipper2Lib::ClipperBase::PreserveCollinear, Clipper2Lib::ClipperBase::ReverseSolution, scale(), and Xor.
BooleanOpPt64()
EXTERN_DLL_EXPORT int Clipper2Lib::BooleanOpPt64 (uint8_t cliptype, uint8_t fillrule, const CPaths64 subjects, const CPaths64 subjects_open, const CPaths64 clips, CPolyTree64 *& solution, CPaths64 & solution_open, bool preserve_collinear = true, bool reverse_solution = false)
{
  if (cliptype > static_cast<uint8_t>(ClipType::Xor)) return -4;
  if (fillrule > static_cast<uint8_t>(FillRule::Negative)) return -3;
  Paths64 sub, sub_open, clp, sol_open;
  sub = ConvertCPaths64(subjects);
  sub_open = ConvertCPaths64(subjects_open);
  clp = ConvertCPaths64(clips);
  PolyTree64 pt;
  Clipper64 clipper;
  clipper.PreserveCollinear = preserve_collinear;
  clipper.ReverseSolution = reverse_solution;
  if (sub.size() > 0) clipper.AddSubject(sub);
  if (sub_open.size() > 0) clipper.AddOpenSubject(sub_open);
  if (clp.size() > 0) clipper.AddClip(clp);
  if (!clipper.Execute(ClipType(cliptype), FillRule(fillrule), pt, sol_open))
    return -1; // clipping bug - should never happen :)
  solution = CreateCPolyTree64(pt);
  solution_open = CreateCPaths64(sol_open);
  return 0; //success !!
}
References Clipper2Lib::Clipper64::AddClip(), Clipper2Lib::Clipper64::AddOpenSubject(), Clipper2Lib::Clipper64::AddSubject(), ConvertCPaths64(), CreateCPaths64(), CreateCPolyTree64(), Clipper2Lib::Clipper64::Execute(), Negative, Clipper2Lib::ClipperBase::PreserveCollinear, Clipper2Lib::ClipperBase::ReverseSolution, and Xor.
BooleanOpPtD()
EXTERN_DLL_EXPORT int Clipper2Lib::BooleanOpPtD (uint8_t cliptype, uint8_t fillrule, const CPathsD subjects, const CPathsD subjects_open, const CPathsD clips, CPolyTreeD *& solution, CPathsD & solution_open, int precision = 2, bool preserve_collinear = true, bool reverse_solution = false)
{
  if (precision < -8 || precision > 8) return -5;
  if (cliptype > static_cast<uint8_t>(ClipType::Xor)) return -4;
  if (fillrule > static_cast<uint8_t>(FillRule::Negative)) return -3;
  const double scale = std::pow(10, precision);
  Paths64 sub, sub_open, clp, sol_open;
  sub       = ConvertCPathsD(subjects, scale);
  sub_open  = ConvertCPathsD(subjects_open, scale);
  clp       = ConvertCPathsD(clips, scale);
  PolyTree64 sol;
  Clipper64 clipper;
  clipper.PreserveCollinear = preserve_collinear;
  clipper.ReverseSolution = reverse_solution;
  if (sub.size() > 0) clipper.AddSubject(sub);
  if (sub_open.size() > 0)
    clipper.AddOpenSubject(sub_open);
  if (clp.size() > 0) clipper.AddClip(clp);
  if (!clipper.Execute(ClipType(cliptype),
    FillRule(fillrule), sol, sol_open)) return -1;
  solution = CreateCPolyTreeD(sol, 1 / scale);
  if (sol_open.size() > 0)
    solution_open = CreateCPathsD(sol_open, 1 / scale);
  return 0;
}
References Clipper2Lib::Clipper64::AddClip(), Clipper2Lib::Clipper64::AddOpenSubject(), Clipper2Lib::Clipper64::AddSubject(), ConvertCPathsD(), CreateCPathsD(), CreateCPolyTreeD(), Clipper2Lib::Clipper64::Execute(), Negative, Clipper2Lib::ClipperBase::PreserveCollinear, Clipper2Lib::ClipperBase::ReverseSolution, scale(), and Xor.
Bounds() [1/4]
Rect64 Clipper2Lib::Bounds (const Path64 & path) inline
  {
    Rect64 rec = MaxInvalidRect64;
    for (const Point64& pt : path)
    {
      if (pt.x < rec.left) rec.left = pt.x;
      if (pt.x > rec.right) rec.right = pt.x;
      if (pt.y < rec.top) rec.top = pt.y;
      if (pt.y > rec.bottom) rec.bottom = pt.y;
    }
    if (rec.IsEmpty()) return Rect64();
    return rec;
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::Rect< T >::left, MaxInvalidRect64, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Referenced by Clipper2Lib::RectClip::Execute(), RectClip(), RectClip(), RectClip(), RectClip(), RectClip64(), RectClipD(), RectClipLines(), RectClipLines(), RectClipLines(), RectClipLines(), RectClipLines64(), and RectClipLinesD().
Bounds() [2/4]
RectD Clipper2Lib::Bounds (const PathD & path) inline
  {
    RectD rec = MaxInvalidRectD;
    for (const PointD& pt : path)
    {
      if (pt.x < rec.left) rec.left = pt.x;
      if (pt.x > rec.right) rec.right = pt.x;
      if (pt.y < rec.top) rec.top = pt.y;
      if (pt.y > rec.bottom) rec.bottom = pt.y;
    }
    if (rec.IsEmpty()) return RectD();
    return rec;
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::Rect< T >::left, MaxInvalidRectD, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Bounds() [3/4]
Rect64 Clipper2Lib::Bounds (const Paths64 & paths) inline
  {
    Rect64 rec = MaxInvalidRect64;
    for (const Path64& path : paths)
      for (const Point64& pt : path)
      {
        if (pt.x < rec.left) rec.left = pt.x;
        if (pt.x > rec.right) rec.right = pt.x;
        if (pt.y < rec.top) rec.top = pt.y;
        if (pt.y > rec.bottom) rec.bottom = pt.y;
      }
    if (rec.IsEmpty()) return Rect64();
    return rec;
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::Rect< T >::left, MaxInvalidRect64, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Bounds() [4/4]
RectD Clipper2Lib::Bounds (const PathsD & paths) inline
  {
    RectD rec = MaxInvalidRectD;
    for (const PathD& path : paths)
      for (const PointD& pt : path)
      {
        if (pt.x < rec.left) rec.left = pt.x;
        if (pt.x > rec.right) rec.right = pt.x;
        if (pt.y < rec.top) rec.top = pt.y;
        if (pt.y > rec.bottom) rec.bottom = pt.y;
      }
    if (rec.IsEmpty()) return RectD();
    return rec;
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::Rect< T >::left, MaxInvalidRectD, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
BuildPath64()
bool Clipper2Lib::BuildPath64 (OutPt * op, bool reverse, bool isOpen, Path64 & path)
  {
    if (op->next == op || (!isOpen && op->next == op->prev))
      return false;
    path.resize(0);
    Point64 lastPt;
    OutPt* op2;
    if (reverse)
    {
      lastPt = op->pt;
      op2 = op->prev;
    }
    else
    {
      op = op->next;
      lastPt = op->pt;
      op2 = op->next;
    }
    path.push_back(lastPt);
    while (op2 != op)
    {
      if (op2->pt != lastPt)
      {
        lastPt = op2->pt;
        path.push_back(lastPt);
      }
      if (reverse)
        op2 = op2->prev;
      else
        op2 = op2->next;
    }
    if (path.size() == 3 && IsVerySmallTriangle(*op2)) return false;
    else return true;
  }
References IsVerySmallTriangle(), Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::prev, and Clipper2Lib::OutPt::pt.
Referenced by Clipper2Lib::Clipper64::BuildPaths64(), Clipper2Lib::Clipper64::BuildTree64(), Clipper2Lib::ClipperD::BuildTreeD(), and Clipper2Lib::ClipperBase::DeepCheckOwner().
BuildPathD()
bool Clipper2Lib::BuildPathD (OutPt * op, bool reverse, bool isOpen, PathD & path, double inv_scale)
  {
    if (op->next == op || (!isOpen && op->next == op->prev)) return false;
    path.resize(0);
    Point64 lastPt;
    OutPt* op2;
    if (reverse)
    {
      lastPt = op->pt;
      op2 = op->prev;
    }
    else
    {
      op = op->next;
      lastPt = op->pt;
      op2 = op->next;
    }
    path.push_back(PointD(lastPt.x * inv_scale, lastPt.y * inv_scale));
    while (op2 != op)
    {
      if (op2->pt != lastPt)
      {
        lastPt = op2->pt;
        path.push_back(PointD(lastPt.x * inv_scale, lastPt.y * inv_scale));
      }
      if (reverse)
        op2 = op2->prev;
      else
        op2 = op2->next;
    }
    if (path.size() == 3 && IsVerySmallTriangle(*op2)) return false;
    return true;
  }
References IsVerySmallTriangle(), Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperD::BuildPathsD(), and Clipper2Lib::ClipperD::BuildTreeD().
CheckDisposeAdjacent()
bool Clipper2Lib::CheckDisposeAdjacent (OutPt *& op, const OutPt * guard, OutRec & outRec)
  {
    bool result = false;
    while (op->prev != op)
    {
      if (op->pt == op->prev->pt && op != guard &&
        op->prev->joiner && !op->joiner)
      {
        if (op == outRec.pts) outRec.pts = op->prev;
        op = DisposeOutPt(op);
        op = op->prev;
      }
      else
        break;
    }
    while (op->next != op)
    {
      if (op->pt == op->next->pt && op != guard &&
        op->next->joiner && !op->joiner)
      {
        if (op == outRec.pts) outRec.pts = op->prev;
        op = DisposeOutPt(op);
        op = op->prev;
      }
      else
        break;
    }
    return result;
  }
References DisposeOutPt(), Clipper2Lib::OutPt::joiner, Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin().
CheckPolytreeFullyContainsChildren()
bool Clipper2Lib::CheckPolytreeFullyContainsChildren (const PolyTree64 & polytree) inline
  {
    for (auto child : polytree)
      if (child->Count() > 0 &&
        !details::PolyPath64ContainsChildren(*(PolyPath64*)(child)))
          return false;
    return true;
  }
References Clipper2Lib::details::PolyPath64ContainsChildren().
CheckPrecision()
void Clipper2Lib::CheckPrecision (int & precision) inline
{
  if (precision >= -8 && precision <= 8) return;
#ifdef NO_EXCEPTIONS
  precision = precision > 8 ? 8 : -8;
#else
  throw Clipper2Exception(precision_error);
#endif
}
References precision_error.
Referenced by Clipper2Lib::ClipperD::ClipperD(), BooleanOp(), BooleanOp(), InflatePaths(), RectClip(), RectClip(), RectClipLines(), RectClipLines(), TrimCollinear(), and Union().
CollinearSegsOverlap()
bool Clipper2Lib::CollinearSegsOverlap (const Point64 & seg1a, const Point64 & seg1b, const Point64 & seg2a, const Point64 & seg2b)
  {
    //precondition: seg1 and seg2 are collinear
    if (seg1a.x == seg1b.x)
    {
      if (seg2a.x != seg1a.x || seg2a.x != seg2b.x) return false;
    }
    else if (seg1a.x < seg1b.x)
    {
      if (seg2a.x < seg2b.x)
      {
        if (seg2a.x >= seg1b.x || seg2b.x <= seg1a.x) return false;
      }
      else
      {
        if (seg2b.x >= seg1b.x || seg2a.x <= seg1a.x) return false;
      }
    }
    else
    {
      if (seg2a.x < seg2b.x)
      {
        if (seg2a.x >= seg1a.x || seg2b.x <= seg1b.x) return false;
      }
      else
      {
        if (seg2b.x >= seg1a.x || seg2a.x <= seg1b.x) return false;
      }
    }
    if (seg1a.y == seg1b.y)
    {
      if (seg2a.y != seg1a.y || seg2a.y != seg2b.y) return false;
    }
    else if (seg1a.y < seg1b.y)
    {
      if (seg2a.y < seg2b.y)
      {
        if (seg2a.y >= seg1b.y || seg2b.y <= seg1a.y) return false;
      }
      else
      {
        if (seg2b.y >= seg1b.y || seg2a.y <= seg1a.y) return false;
      }
    }
    else
    {
      if (seg2a.y < seg2b.y)
      {
        if (seg2a.y >= seg1a.y || seg2b.y <= seg1b.y) return false;
      }
      else
      {
        if (seg2b.y >= seg1a.y || seg2a.y <= seg1b.y) return false;
      }
    }
    return true;
  }
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin().
ConvertCPath64()
Path64 Clipper2Lib::ConvertCPath64 (const CPath64 & p) inline
{
  Path64 result;
  if (p && *p)
  {
    CPath64 v = p;
    const size_t cnt = static_cast<size_t>(p[0]);
    v += 2; // skip counters
    result.reserve(cnt);
    for (size_t i = 0; i < cnt; ++i)
    {
      // x,y here avoids right to left function evaluation
      // result.push_back(Point64(*v++, *v++));
      int64_t x = *v++;
      int64_t y = *v++;
      result.push_back(Point64(x, y));
    }
  }
  return result;
}
Referenced by ConvertCPaths64().
ConvertCPathD() [1/2]
PathD Clipper2Lib::ConvertCPathD (const CPathD & p) inline
{
  PathD result;
  if (p)
  {
    CPathD v = p;
    size_t cnt = static_cast<size_t>(v[0]);
    v += 2; // skip counters
    result.reserve(cnt);
    for (size_t i = 0; i < cnt; ++i)
    {
      // x,y here avoids right to left function evaluation
      // result.push_back(PointD(*v++, *v++));
      double x = *v++;
      double y = *v++;
      result.push_back(PointD(x, y));
    }
  }
  return result;
}
Referenced by ConvertCPathsD(), and ConvertCPathsD().
ConvertCPathD() [2/2]
Path64 Clipper2Lib::ConvertCPathD (const CPathD & p, double scale) inline
{
  Path64 result;
  if (p)
  {
    CPathD v = p;
    size_t cnt = static_cast<size_t>(*v);
    v += 2; // skip counters
    result.reserve(cnt);
    for (size_t i = 0; i < cnt; ++i)
    {
      // x,y here avoids right to left function evaluation
      // result.push_back(PointD(*v++, *v++));
      double x = *v++ * scale;
      double y = *v++ * scale;
      result.push_back(Point64(x, y));
    }
  }
  return result;
}
References scale().
ConvertCPaths64()
Paths64 Clipper2Lib::ConvertCPaths64 (const CPaths64 & pp) inline
{
  Paths64 result;
  if (pp)
  {
    CPaths64 v = pp;
    CPath64 cnts = pp[0];
    const size_t cnt = static_cast<size_t>(cnts[1]); // nb 2nd cnt
    ++v; // skip cnts
    result.reserve(cnt);
    for (size_t i = 0; i < cnt; ++i)
      result.push_back(ConvertCPath64(*v++));
  }
  return result;
}
References ConvertCPath64().
Referenced by BooleanOp64(), BooleanOpPt64(), InflatePaths64(), RectClip64(), and RectClipLines64().
ConvertCPathsD() [1/2]
PathsD Clipper2Lib::ConvertCPathsD (const CPathsD & pp) inline
{
  PathsD result;
  if (pp)
  {
    CPathsD v = pp;
    CPathD cnts = v[0];
    size_t cnt = static_cast<size_t>(cnts[1]);
    ++v; // skip cnts path
    result.reserve(cnt);
    for (size_t i = 0; i < cnt; ++i)
      result.push_back(ConvertCPathD(*v++));
  }
  return result;
}
References ConvertCPathD().
Referenced by BooleanOpD(), BooleanOpPtD(), InflatePathsD(), RectClipD(), and RectClipLinesD().
ConvertCPathsD() [2/2]
Paths64 Clipper2Lib::ConvertCPathsD (const CPathsD & pp, double scale) inline
{
  Paths64 result;
  if (pp)
  {
    CPathsD v = pp;
    CPathD cnts = v[0];
    size_t cnt = static_cast<size_t>(cnts[1]);
    result.reserve(cnt);
    ++v; // skip cnts path
    for (size_t i = 0; i < cnt; ++i)
      result.push_back(ConvertCPathD(*v++, scale));
  }
  return result;
}
References ConvertCPathD(), and scale().
CreateCPath64() [1/2]
CPath64 Clipper2Lib::CreateCPath64 (const Path64 & p) inline
{
  // allocates memory for CPath64, fills the counter
  // and returns the memory filled with path data
  size_t cnt = p.size();
  if (!cnt) return nullptr;
  CPath64 result = CreateCPath64(cnt, 0);
  CPath64 v = result;
  v += 2; // skip counters
  for (const Point64& pt : p)
  {
    *v++ = pt.x;
    *v++ = pt.y;
  }
  return result;
}
References CreateCPath64().
CreateCPath64() [2/2]
CPath64 Clipper2Lib::CreateCPath64 (size_t cnt1, size_t cnt2) inline
{
  // allocates memory for CPath64, fills in the counter, and
  // returns the structure ready to be filled with path data
  CPath64 result = new int64_t[2 + cnt1 *2];
  result[0] = cnt1;
  result[1] = cnt2;
  return result;
}
Referenced by CreateCPath64(), CreateCPaths64(), and InitCPolyPath64().
CreateCPathD() [1/3]
CPathD Clipper2Lib::CreateCPathD (const Path64 & p, double scale) inline
{
  // allocates memory for CPathD, fills in the counter, and
  // returns the structure filled with *scaled* path data
  size_t cnt = p.size();
  if (!cnt) return nullptr;
  CPathD result = CreateCPathD(cnt, 0);
  CPathD v = result;
  v += 2; // skip cnts
  for (const Point64& pt : p)
  {
    *v++ = pt.x * scale;
    *v++ = pt.y * scale;
  }
  return result;
}
References CreateCPathD(), and scale().
CreateCPathD() [2/3]
CPathD Clipper2Lib::CreateCPathD (const PathD & p) inline
{
  // allocates memory for CPath, fills the counter
  // and returns the memory fills with path data
  size_t cnt = p.size();
  if (!cnt) return nullptr;
  CPathD result = CreateCPathD(cnt, 0);
  CPathD v = result;
  v += 2; // skip counters
  for (const PointD& pt : p)
  {
    *v++ = pt.x;
    *v++ = pt.y;
  }
  return result;
}
References CreateCPathD().
CreateCPathD() [3/3]
CPathD Clipper2Lib::CreateCPathD (size_t cnt1, size_t cnt2) inline
{
  // allocates memory for CPathD, fills in the counter, and
  // returns the structure ready to be filled with path data
  CPathD result = new double[2 + cnt1 * 2];
  result[0] = static_cast<double>(cnt1);
  result[1] = static_cast<double>(cnt2);
  return result;
}
Referenced by CreateCPathD(), CreateCPathD(), CreateCPathsD(), CreateCPathsD(), and InitCPolyPathD().
CreateCPaths64()
CPaths64 Clipper2Lib::CreateCPaths64 (const Paths64 & pp) inline
{
  // allocates memory for multiple CPath64 and
  // and returns this memory filled with path data
  size_t cnt = pp.size(), cnt2 = cnt;
  // don't allocate space for empty paths
  for (size_t i = 0; i < cnt; ++i)
    if (!pp[i].size()) --cnt2;
  if (!cnt2) return nullptr;
  CPaths64 result = new int64_t* [cnt2 + 1];
  CPaths64 v = result;
  *v++ = CreateCPath64(0, cnt2); // assign a counter path
  for (const Path64& p : pp)
  {
    *v = CreateCPath64(p);
    if (*v) ++v;
  }
  return result;
}
References CreateCPath64(), and size.
Referenced by BooleanOp64(), BooleanOpPt64(), InflatePaths64(), RectClip64(), and RectClipLines64().
CreateCPathsD() [1/2]
CPathsD Clipper2Lib::CreateCPathsD (const Paths64 & pp, double scale) inline
{
  // allocates memory for *multiple* CPathD, and
  // returns the structure filled with scaled path data
  size_t cnt = pp.size(), cnt2 = cnt;
  // don't allocate space for empty paths
  for (size_t i = 0; i < cnt; ++i)
    if (!pp[i].size()) --cnt2;
  if (!cnt2) return nullptr;
  CPathsD result = new double* [cnt2 + 1];
  CPathsD v = result;
  *v++ = CreateCPathD(0, cnt2);
  for (const Path64& p : pp)
  {
    *v = CreateCPathD(p, scale);
    if (*v) ++v;
  }
  return result;
}
References CreateCPathD(), scale(), and size.
CreateCPathsD() [2/2]
CPathsD Clipper2Lib::CreateCPathsD (const PathsD & pp) inline
{
  size_t cnt = pp.size(), cnt2 = cnt;
  // don't allocate space for empty paths
  for (size_t i = 0; i < cnt; ++i)
    if (!pp[i].size()) --cnt2;
  if (!cnt2) return nullptr;
  CPathsD result = new double * [cnt2 + 1];
  CPathsD v = result;
  *v++ = CreateCPathD(0, cnt2); // assign counter path
  for (const PathD& p : pp)
  {
    *v = CreateCPathD(p);
    if (*v) { ++v; }
  }
  return result;
}
References CreateCPathD(), and size.
Referenced by BooleanOpD(), BooleanOpPtD(), InflatePathsD(), RectClipD(), and RectClipLinesD().
CreateCPolyTree64()
CPolyTree64 * Clipper2Lib::CreateCPolyTree64 (const PolyTree64 & pt) inline
{
  CPolyTree64* result = new CPolyTree64();
  result->polygon = nullptr;
  result->is_hole = false;
  size_t child_cnt = pt.Count();
  result->childs = nullptr;
  result->child_count = static_cast<uint32_t>(child_cnt);
  if (!child_cnt) return result;
  result->childs = new CPolyPath64[child_cnt];
  CPolyPath64* child = result->childs;
  for (const PolyPath64* pp : pt)
    InitCPolyPath64(child++, true, pp);
  return result;
}
References Clipper2Lib::CPolyPath64::child_count, Clipper2Lib::CPolyPath64::childs, Clipper2Lib::PolyPath64::Count(), InitCPolyPath64(), Clipper2Lib::CPolyPath64::is_hole, and Clipper2Lib::CPolyPath64::polygon.
Referenced by BooleanOpPt64().
CreateCPolyTreeD()
CPolyTreeD * Clipper2Lib::CreateCPolyTreeD (const PolyTree64 & pt, double scale) inline
{
  CPolyTreeD* result = new CPolyTreeD();
  result->polygon = nullptr;
  result->is_hole = false;
  size_t child_cnt = pt.Count();
  result->child_count = static_cast<uint32_t>(child_cnt);
  result->childs = nullptr;
  if (!child_cnt) return result;
  result->childs = new CPolyPathD[child_cnt];
  CPolyPathD* child = result->childs;
  for (const PolyPath64* pp : pt)
    InitCPolyPathD(child++, true, pp, scale);
  return result;
}
References Clipper2Lib::CPolyPathD::child_count, Clipper2Lib::CPolyPathD::childs, Clipper2Lib::PolyPath64::Count(), InitCPolyPathD(), Clipper2Lib::CPolyPathD::is_hole, Clipper2Lib::CPolyPathD::polygon, and scale().
Referenced by BooleanOpPtD().
CRectIsEmpty()
template<typename T > bool Clipper2Lib::CRectIsEmpty (const CRect< T > & rect) inline
{
  return (rect.right <= rect.left) || (rect.bottom <= rect.top);
}
References Clipper2Lib::CRect< T >::bottom, Clipper2Lib::CRect< T >::left, Clipper2Lib::CRect< T >::right, and Clipper2Lib::CRect< T >::top.
Referenced by RectClip64(), RectClipD(), RectClipLines64(), and RectClipLinesD().
CRectToRect()
template<typename T > Rect< T > Clipper2Lib::CRectToRect (const CRect< T > & rect) inline
{
  Rect<T> result;
  result.left = rect.left;
  result.top = rect.top;
  result.right = rect.right;
  result.bottom = rect.bottom;
  return result;
}
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::CRect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::CRect< T >::left, Clipper2Lib::Rect< T >::right, Clipper2Lib::CRect< T >::right, Clipper2Lib::Rect< T >::top, and Clipper2Lib::CRect< T >::top.
Referenced by RectClip64(), RectClipD(), RectClipLines64(), and RectClipLinesD().
CrossProduct() [1/2]
template<typename T > double Clipper2Lib::CrossProduct (const Point< T > & pt1, const Point< T > & pt2, const Point< T > & pt3) inline
{
  return (static_cast<double>(pt2.x - pt1.x) * static_cast<double>(pt3.y -
    pt2.y) - static_cast<double>(pt2.y - pt1.y) * static_cast<double>(pt3.x - pt2.x));
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::CleanCollinear(), Clipper2Lib::RectClip::Execute(), Clipper2Lib::ClipperBase::IntersectEdges(), IsClockwise(), IsValidAelOrder(), NearCollinear(), Clipper2Lib::ClipperOffset::OffsetPoint(), PointInPolygon(), Clipper2Lib::ClipperBase::ProcessJoin(), SegmentsIntersect(), TestJoinWithNext1(), TestJoinWithNext2(), TestJoinWithPrev1(), TestJoinWithPrev2(), and TrimCollinear().
CrossProduct() [2/2]
template<typename T > double Clipper2Lib::CrossProduct (const Point< T > & vec1, const Point< T > & vec2) inline
{
  return static_cast<double>(vec1.y * vec2.x) - static_cast<double>(vec2.y * vec1.x);
}
References Clipper2Lib::Point< T >::x, vec2_< T >::x(), Clipper2Lib::Point< T >::y, and vec2_< T >::y().
Difference() [1/2]
Paths64 Clipper2Lib::Difference (const Paths64 & subjects, const Paths64 & clips, FillRule fillrule) inline
  {
    return BooleanOp(ClipType::Difference, fillrule, subjects, clips);
  }
References BooleanOp(), and Difference.
Difference() [2/2]
PathsD Clipper2Lib::Difference (const PathsD & subjects, const PathsD & clips, FillRule fillrule, int decimal_prec = 2) inline
  {
    return BooleanOp(ClipType::Difference, fillrule, subjects, clips, decimal_prec);
  }
References BooleanOp(), and Difference.
DisposeCPolyPath64()
void Clipper2Lib::DisposeCPolyPath64 (CPolyPath64 * cpp) inline
{
  if (!cpp->child_count) return;
  CPolyPath64* child = cpp->childs;
  for (size_t i = 0; i < cpp->child_count; ++i)
    DisposeCPolyPath64(child);
  delete[] cpp->childs;
}
References Clipper2Lib::CPolyPath64::child_count, Clipper2Lib::CPolyPath64::childs, and DisposeCPolyPath64().
Referenced by DisposeCPolyPath64(), and DisposeExportedCPolyTree64().
DisposeCPolyPathD()
void Clipper2Lib::DisposeCPolyPathD (CPolyPathD * cpp) inline
{
  if (!cpp->child_count) return;
  CPolyPathD* child = cpp->childs;
  for (size_t i = 0; i < cpp->child_count; ++i)
    DisposeCPolyPathD(child++);
  delete[] cpp->childs;
}
References Clipper2Lib::CPolyPathD::child_count, Clipper2Lib::CPolyPathD::childs, and DisposeCPolyPathD().
Referenced by DisposeCPolyPathD(), and DisposeExportedCPolyTreeD().
DisposeExportedCPath64()
EXTERN_DLL_EXPORT void Clipper2Lib::DisposeExportedCPath64 (CPath64 p)
{
  if (p) delete[] p;
}
Referenced by DisposeExportedCPaths64().
DisposeExportedCPathD()
EXTERN_DLL_EXPORT void Clipper2Lib::DisposeExportedCPathD (CPathD p)
{
  if (p) delete[] p;
}
Referenced by DisposeExportedCPathsD().
DisposeExportedCPaths64()
EXTERN_DLL_EXPORT void Clipper2Lib::DisposeExportedCPaths64 (CPaths64 & pp)
{
  if (!pp) return;
  CPaths64 v = pp;
  CPath64 cnts = *v;
  const size_t cnt = static_cast<size_t>(cnts[1]);
  for (size_t i = 0; i <= cnt; ++i) //nb: cnt +1
    DisposeExportedCPath64(*v++);
  delete[] pp;
  pp = nullptr;
}
References DisposeExportedCPath64().
DisposeExportedCPathsD()
EXTERN_DLL_EXPORT void Clipper2Lib::DisposeExportedCPathsD (CPathsD & pp)
{
  if (!pp) return;
  CPathsD v = pp;
  CPathD cnts = *v;
  size_t cnt = static_cast<size_t>(cnts[1]);
  for (size_t i = 0; i <= cnt; ++i) //nb: cnt +1
    DisposeExportedCPathD(*v++);
  delete[] pp;
  pp = nullptr;
}
References DisposeExportedCPathD().
DisposeExportedCPolyTree64()
EXTERN_DLL_EXPORT void Clipper2Lib::DisposeExportedCPolyTree64 (CPolyTree64 *& cpt)
{
  if (!cpt) return;
  DisposeCPolyPath64(cpt);
  delete cpt;
  cpt = nullptr;
}
References DisposeCPolyPath64().
DisposeExportedCPolyTreeD()
EXTERN_DLL_EXPORT void Clipper2Lib::DisposeExportedCPolyTreeD (CPolyTreeD *& cpt)
{
  if (!cpt) return;
  DisposeCPolyPathD(cpt);
  delete cpt;
  cpt = nullptr;
}
References DisposeCPolyPathD().
DisposeOutPt()
OutPt * Clipper2Lib::DisposeOutPt (OutPt * op) inline
  {
    OutPt* result = op->next;
    op->prev->next = op->next;
    op->next->prev = op->prev;
    delete op;
    return result;
  }
References Clipper2Lib::OutPt::next, and Clipper2Lib::OutPt::prev.
Referenced by CheckDisposeAdjacent(), and Clipper2Lib::ClipperBase::CleanCollinear().
DisposeOutPts()
void Clipper2Lib::DisposeOutPts (OutRec & outrec) inline
  {
    if (!outrec.pts) return;
    OutPt* op2 = outrec.pts->next;
    while (op2 != outrec.pts)
    {
      OutPt* tmp = op2->next;
      delete op2;
      op2 = tmp;
    }
    delete outrec.pts;
    outrec.pts = nullptr;
  }
References Clipper2Lib::OutPt::next, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::DisposeAllOutRecs().
Distance()
template<typename T > double Clipper2Lib::Distance (const Point< T > pt1, const Point< T > pt2) inline
  {
    return std::sqrt(DistanceSqr(pt1, pt2));
  }
References DistanceSqr().
Referenced by Length().
DistanceFromLineSqrd()
template<typename T > double Clipper2Lib::DistanceFromLineSqrd (const Point< T > & pt, const Point< T > & ln1, const Point< T > & ln2) inline
{
  //perpendicular distance of point (x,y) = (Ax + By + C)/Sqrt(A + B)
  //see http://en.wikipedia.org/wiki/Perpendicular_distance
  double A = static_cast<double>(ln1.y - ln2.y);
  double B = static_cast<double>(ln2.x - ln1.x);
  double C = A * ln1.x + B * ln1.y;
  C = A * pt.x + B * pt.y - C;
  return (C * C) / (A * A + B * B);
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin().
DistanceSqr()
template<typename T > double Clipper2Lib::DistanceSqr (const Point< T > pt1, const Point< T > pt2) inline
{
  return Sqr(pt1.x - pt2.x) + Sqr(pt1.y - pt2.y);
}
References Sqr(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Distance(), GetEndE1ClosestToEndE2(), NearCollinear(), and Clipper2Lib::ClipperBase::ProcessJoin().
DotProduct() [1/2]
template<typename T > double Clipper2Lib::DotProduct (const Point< T > & pt1, const Point< T > & pt2, const Point< T > & pt3) inline
{
  return (static_cast<double>(pt2.x - pt1.x) * static_cast<double>(pt3.x - pt2.x) +
    static_cast<double>(pt2.y - pt1.y) * static_cast<double>(pt3.y - pt2.y));
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::CleanCollinear(), and Clipper2Lib::ClipperOffset::OffsetPoint().
DotProduct() [2/2]
template<typename T > double Clipper2Lib::DotProduct (const Point< T > & vec1, const Point< T > & vec2) inline
{
  return static_cast<double>(vec1.x * vec2.x) + static_cast<double>(vec1.y * vec2.y);
}
References Clipper2Lib::Point< T >::x, vec2_< T >::x(), Clipper2Lib::Point< T >::y, and vec2_< T >::y().
EdgesAdjacentInAEL()
bool Clipper2Lib::EdgesAdjacentInAEL (const IntersectNode & inode) inline
  {
    return (inode.edge1->next_in_ael == inode.edge2) || (inode.edge1->prev_in_ael == inode.edge2);
  }
References Clipper2Lib::IntersectNode::edge1, Clipper2Lib::IntersectNode::edge2, Clipper2Lib::Active::next_in_ael, and Clipper2Lib::Active::prev_in_ael.
Referenced by Clipper2Lib::ClipperBase::ProcessIntersectList().
Ellipse() [1/2]
template<typename T > Path< T > Clipper2Lib::Ellipse (const Point< T > & center, double radiusX, double radiusY = 0, int steps = 0) inline
  {
    if (radiusX <= 0) return Path<T>();
    if (radiusY <= 0) radiusY = radiusX;
    if (steps <= 2)
      steps = static_cast<int>(PI * sqrt((radiusX + radiusY) / 2));
    double si = std::sin(2 * PI / steps);
    double co = std::cos(2 * PI / steps);
    double dx = co, dy = si;
    Path<T> result;
    result.reserve(steps);
    result.push_back(Point<T>(center.x + radiusX, static_cast<double>(center.y)));
    for (int i = 1; i < steps; ++i)
    {
      result.push_back(Point<T>(center.x + radiusX * dx, center.y + radiusY * dy));
      double x = dx * co - dy * si;
      dy = dy * co + dx * si;
      dx = x;
    }
    return result;
  }
References PI, sqrt(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Ellipse() [2/2]
template<typename T > Path< T > Clipper2Lib::Ellipse (const Rect< T > & rect, int steps = 0) inline
  {
    return Ellipse(rect.MidPoint(),
      static_cast<double>(rect.Width()) *0.5,
      static_cast<double>(rect.Height()) * 0.5, steps);
  }
References Ellipse(), Clipper2Lib::Rect< T >::Height(), Clipper2Lib::Rect< T >::MidPoint(), and Clipper2Lib::Rect< T >::Width().
Referenced by Clipper2Lib::ClipperOffset::DoGroupOffset(), and Ellipse().
ExtractFromSEL()
Active * Clipper2Lib::ExtractFromSEL (Active * ae) inline
  {
    Active* res = ae->next_in_sel;
    if (res)
      res->prev_in_sel = ae->prev_in_sel;
    ae->prev_in_sel->next_in_sel = res;
    return res;
  }
References Clipper2Lib::Active::next_in_sel, and Clipper2Lib::Active::prev_in_sel.
Referenced by Clipper2Lib::ClipperBase::BuildIntersectList().
FindEdgeWithMatchingLocMin()
Active * Clipper2Lib::FindEdgeWithMatchingLocMin (Active * e)
  {
    Active* result = e->next_in_ael;
    while (result)
    {
      if (result->local_min == e->local_min) return result;
      else if (!IsHorizontal(*result) && e->bot != result->bot) result = nullptr;
      else result = result->next_in_ael;
    }
    result = e->prev_in_ael;
    while (result)
    {
      if (result->local_min == e->local_min) return result;
      else if (!IsHorizontal(*result) && e->bot != result->bot) return nullptr;
      else result = result->prev_in_ael;
    }
    return result;
  }
References Clipper2Lib::Active::bot, IsHorizontal(), Clipper2Lib::Active::local_min, Clipper2Lib::Active::next_in_ael, and Clipper2Lib::Active::prev_in_ael.
Referenced by Clipper2Lib::ClipperBase::IntersectEdges().
FindJoinParent()
Joiner * Clipper2Lib::FindJoinParent (const Joiner * joiner, OutPt * op)
  {
    Joiner* result = op->joiner;
    for (; ; )
    {
      if (op == result->op1)
      {
        if (result->next1 == joiner) return result;
        else result = result->next1;
      }
      else
      {
        if (result->next2 == joiner) return result;
        else result = result->next2;
      }
    }
  }
References Clipper2Lib::OutPt::joiner, Clipper2Lib::Joiner::next1, Clipper2Lib::Joiner::next2, and Clipper2Lib::Joiner::op1.
Referenced by Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins(), and Clipper2Lib::ClipperBase::DeleteJoin().
FindTrialJoinParent()
Joiner * Clipper2Lib::FindTrialJoinParent (Joiner *& joiner, const OutPt * op)
  {
    Joiner* parent = joiner;
    while (parent)
    {
      if (op == parent->op1)
      {
        if (parent->next1 && parent->next1->idx < 0)
        {
          joiner = parent->next1;
          return parent;
        }
        parent = parent->next1;
      }
      else
      {
        if (parent->next2 && parent->next2->idx < 0)
        {
          joiner = parent->next2;
          return parent;
        }
        parent = parent->next2;
      }
    }
    return nullptr;
  }
References Clipper2Lib::Joiner::idx, Clipper2Lib::Joiner::next1, Clipper2Lib::Joiner::next2, and Clipper2Lib::Joiner::op1.
Referenced by Clipper2Lib::ClipperBase::DeleteTrialHorzJoin().
GetAdjacentLocation()
Location Clipper2Lib::GetAdjacentLocation (Location loc, bool isClockwise) inline
  {
    int delta = (isClockwise) ? 1 : 3;
    return static_cast<Location>((static_cast<int>(loc) + delta) % 4);
  }
Referenced by Clipper2Lib::RectClip::AddCorner(), and Clipper2Lib::RectClip::Execute().
GetAvgUnitVector()
PointD Clipper2Lib::GetAvgUnitVector (const PointD & vec1, const PointD & vec2) inline
{
  return NormalizeVector(PointD(vec1.x + vec2.x, vec1.y + vec2.y));
}
References NormalizeVector(), Clipper2Lib::Point< T >::x, vec2_< T >::x(), Clipper2Lib::Point< T >::y, and vec2_< T >::y().
Referenced by Clipper2Lib::ClipperOffset::DoSquare().
GetBounds()
Rect64 Clipper2Lib::GetBounds (const Path64 & path) inline
  {
    if (path.empty()) return Rect64();
    Rect64 result = invalid_rect;
    for(const Point64& pt : path)
    {
      if (pt.x < result.left) result.left = pt.x;
      if (pt.x > result.right) result.right = pt.x;
      if (pt.y < result.top) result.top = pt.y;
      if (pt.y > result.bottom) result.bottom = pt.y;
    }
    return result;
  }
References Clipper2Lib::Rect< T >::bottom, invalid_rect, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, and Clipper2Lib::Rect< T >::top.
Referenced by Clipper2Lib::Clipper64::BuildTree64(), Clipper2Lib::ClipperD::BuildTreeD(), and Clipper2Lib::ClipperBase::DeepCheckOwner().
GetCurrYMaximaVertex()
Vertex * Clipper2Lib::GetCurrYMaximaVertex (const Active & e)
  {
    Vertex* result = e.vertex_top;
    if (e.wind_dx > 0)
      while (result->next->pt.y == result->pt.y) result = result->next;
    else
      while (result->prev->pt.y == result->pt.y) result = result->prev;
    if (!IsMaxima(*result)) result = nullptr; // not a maxima
    return result;
  }
References IsMaxima(), Clipper2Lib::Vertex::next, Clipper2Lib::Vertex::prev, Clipper2Lib::Vertex::pt, Clipper2Lib::Active::vertex_top, Clipper2Lib::Active::wind_dx, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal().
GetDx()
double Clipper2Lib::GetDx (const Point64 & pt1, const Point64 & pt2) inline
  {
    double dy = double(pt2.y - pt1.y);
    if (dy != 0)
      return double(pt2.x - pt1.x) / dy;
    else if (pt2.x > pt1.x)
      return -std::numeric_limits<double>::max();
    else
      return std::numeric_limits<double>::max();
  }
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by SetDx().
GetEndE1ClosestToEndE2()
Point64 Clipper2Lib::GetEndE1ClosestToEndE2 (const Active & e1, const Active & e2) inline
  {
    double d[] = {
      DistanceSqr(e1.bot, e2.bot),
      DistanceSqr(e1.top, e2.top),
      DistanceSqr(e1.top, e2.bot),
      DistanceSqr(e1.bot, e2.top)
    };
    if (d[0] == 0) return e1.bot;
    int idx = 0;
    for (int i = 1; i < 4; ++i)
    {
      if (d[i] < d[idx]) idx = i;
      if (d[i] == 0) break;
    }
    switch (idx)
    {
    case 1: case 2: return e1.top;
    default: return e1.bot;
    }
  }
References Clipper2Lib::Active::bot, DistanceSqr(), and Clipper2Lib::Active::top.
Referenced by GetIntersectPoint().
GetHorzExtendedHorzSeg()
bool Clipper2Lib::GetHorzExtendedHorzSeg (OutPt *& op, OutPt *& op2) inline
  {
    OutRec* outrec = GetRealOutRec(op->outrec);
    op2 = op;
    if (outrec->front_edge)
    {
      while (op->prev != outrec->pts &&
        op->prev->pt.y == op->pt.y) op = op->prev;
      while (op2 != outrec->pts &&
        op2->next->pt.y == op2->pt.y) op2 = op2->next;
      return op2 != op;
    }
    else
    {
      while (op->prev != op2 && op->prev->pt.y == op->pt.y)
        op = op->prev;
      while (op2->next != op && op2->next->pt.y == op2->pt.y)
        op2 = op2->next;
      return op2 != op && op2->next != op;
    }
  }
References Clipper2Lib::OutRec::front_edge, GetRealOutRec(), Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::outrec, Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, Clipper2Lib::OutRec::pts, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins().
GetHorzMaximaPair()
Active * Clipper2Lib::GetHorzMaximaPair (const Active & horz, const Vertex * vert_max)
  {
    //we can't be sure whether the MaximaPair is on the left or right, so ...
    Active* result = horz.prev_in_ael;
    while (result && result->curr_x >= vert_max->pt.x)
    {
      if (result->vertex_top == vert_max) return result;  // Found!
      result = result->prev_in_ael;
    }
    result = horz.next_in_ael;
    while (result && TopX(*result, horz.top.y) <= vert_max->pt.x)
    {
      if (result->vertex_top == vert_max) return result;  // Found!
      result = result->next_in_ael;
    }
    return nullptr;
  }
References Clipper2Lib::Active::curr_x, Clipper2Lib::Active::next_in_ael, Clipper2Lib::Active::prev_in_ael, Clipper2Lib::Vertex::pt, Clipper2Lib::Active::top, TopX(), Clipper2Lib::Active::vertex_top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal().
GetIntersection()
bool Clipper2Lib::GetIntersection (const Path64 & rectPath, const Point64 & p, const Point64 & p2, Location & loc, Point64 & ip) inline
  {
    // gets the intersection closest to 'p'
    // when Result = false, loc will remain unchanged
    switch (loc)
    {
    case Location::Left:
      if (SegmentsIntersect(p, p2, rectPath[0], rectPath[3], true))
        ip = GetIntersectPoint64(p, p2, rectPath[0], rectPath[3]);
      else if (p.y < rectPath[0].y &&
        SegmentsIntersect(p, p2, rectPath[0], rectPath[1], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[0], rectPath[1]);
        loc = Location::Top;
      }
      else if (SegmentsIntersect(p, p2, rectPath[2], rectPath[3], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[2], rectPath[3]);
        loc = Location::Bottom;
      }
      else return false;
      break;
    case Location::Top:
      if (SegmentsIntersect(p, p2, rectPath[0], rectPath[1], true))
        ip = GetIntersectPoint64(p, p2, rectPath[0], rectPath[1]);
      else if (p.x < rectPath[0].x &&
        SegmentsIntersect(p, p2, rectPath[0], rectPath[3], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[0], rectPath[3]);
        loc = Location::Left;
      }
      else if (p.x > rectPath[1].x &&
        SegmentsIntersect(p, p2, rectPath[1], rectPath[2], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[1], rectPath[2]);
        loc = Location::Right;
      }
      else return false;
        break;
    case Location::Right:
      if (SegmentsIntersect(p, p2, rectPath[1], rectPath[2], true))
        ip = GetIntersectPoint64(p, p2, rectPath[1], rectPath[2]);
      else if (p.y < rectPath[0].y &&
        SegmentsIntersect(p, p2, rectPath[0], rectPath[1], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[0], rectPath[1]);
        loc = Location::Top;
      }
      else if (SegmentsIntersect(p, p2, rectPath[2], rectPath[3], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[2], rectPath[3]);
        loc = Location::Bottom;
      }
      else return false;
      break;
    case Location::Bottom:
      if (SegmentsIntersect(p, p2, rectPath[2], rectPath[3], true))
        ip = GetIntersectPoint64(p, p2, rectPath[2], rectPath[3]);
      else if (p.x < rectPath[3].x &&
        SegmentsIntersect(p, p2, rectPath[0], rectPath[3], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[0], rectPath[3]);
        loc = Location::Left;
      }
      else if (p.x > rectPath[2].x &&
        SegmentsIntersect(p, p2, rectPath[1], rectPath[2], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[1], rectPath[2]);
        loc = Location::Right;
      }
      else return false;
      break;
    default: // loc == rInside
      if (SegmentsIntersect(p, p2, rectPath[0], rectPath[3], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[0], rectPath[3]);
        loc = Location::Left;
      }
      else if (SegmentsIntersect(p, p2, rectPath[0], rectPath[1], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[0], rectPath[1]);
        loc = Location::Top;
      }
      else if (SegmentsIntersect(p, p2, rectPath[1], rectPath[2], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[1], rectPath[2]);
        loc = Location::Right;
      }
      else if (SegmentsIntersect(p, p2, rectPath[2], rectPath[3], true))
      {
        ip = GetIntersectPoint64(p, p2, rectPath[2], rectPath[3]);
        loc = Location::Bottom;
      }
      else return false;
      break;
    }
    return true;
  }
References Bottom, GetIntersectPoint64(), Left, Right, SegmentsIntersect(), Top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::RectClip::Execute(), and Clipper2Lib::RectClipLines::Execute().
GetIntersectPoint() [1/2]
Point64 Clipper2Lib::GetIntersectPoint (const Active & e1, const Active & e2)
  {
    double b1, b2, q = (e1.dx - e2.dx);
    if (std::abs(q) < 1e-5)     // 1e-5 is a rough empirical limit
      return GetEndE1ClosestToEndE2(e1, e2); // ie almost parallel
    if (e1.dx == 0)
    {
      if (IsHorizontal(e2)) return Point64(e1.bot.x, e2.bot.y);
      b2 = e2.bot.y - (e2.bot.x / e2.dx);
      return Point64(e1.bot.x,
        static_cast<int64_t>(std::round(e1.bot.x / e2.dx + b2)));
    }
    else if (e2.dx == 0)
    {
      if (IsHorizontal(e1)) return Point64(e2.bot.x, e1.bot.y);
      b1 = e1.bot.y - (e1.bot.x / e1.dx);
      return Point64(e2.bot.x,
        static_cast<int64_t>(std::round(e2.bot.x / e1.dx + b1)));
    }
    else
    {
      b1 = e1.bot.x - e1.bot.y * e1.dx;
      b2 = e2.bot.x - e2.bot.y * e2.dx;
      q = (b2 - b1) / q;
      return (abs(e1.dx) < abs(e2.dx)) ?
        Point64(static_cast<int64_t>(e1.dx * q + b1),
          static_cast<int64_t>((q))) :
        Point64(static_cast<int64_t>(e2.dx * q + b2),
          static_cast<int64_t>((q)));
    }
  }
References Clipper2Lib::Active::bot, Clipper2Lib::Active::dx, GetEndE1ClosestToEndE2(), IsHorizontal(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::AddNewIntersectNode(), and Clipper2Lib::ClipperBase::DoSplitOp().
GetIntersectPoint() [2/2]
bool Clipper2Lib::GetIntersectPoint (const Point64 & ln1a, const Point64 & ln1b, const Point64 & ln2a, const Point64 & ln2b, PointD & ip)
  {
    ip = PointD(0, 0);
    double m1, b1, m2, b2;
    if (ln1b.x == ln1a.x)
    {
      if (ln2b.x == ln2a.x) return false;
      m2 = static_cast<double>(ln2b.y - ln2a.y) /
        static_cast<double>(ln2b.x - ln2a.x);
      b2 = ln2a.y - m2 * ln2a.x;
      ip.x = static_cast<double>(ln1a.x);
      ip.y = m2 * ln1a.x + b2;
    }
    else if (ln2b.x == ln2a.x)
    {
      m1 = static_cast<double>(ln1b.y - ln1a.y) /
        static_cast<double>(ln1b.x - ln1a.x);
      b1 = ln1a.y - m1 * ln1a.x;
      ip.x = static_cast<double>(ln2a.x);
      ip.y = m1 * ln2a.x + b1;
    }
    else
    {
      m1 = static_cast<double>(ln1b.y - ln1a.y) /
        static_cast<double>(ln1b.x - ln1a.x);
      b1 = ln1a.y - m1 * ln1a.x;
      m2 = static_cast<double>(ln2b.y - ln2a.y) /
        static_cast<double>(ln2b.x - ln2a.x);
      b2 = ln2a.y - m2 * ln2a.x;
      if (std::abs(m1 - m2) > FloatingPointTolerance)
      {
        ip.x = (b2 - b1) / (m1 - m2);
        ip.y = m1 * ip.x + b1;
      }
      else
      {
        ip.x = static_cast<double>(ln1a.x + ln1b.x) / 2;
        ip.y = static_cast<double>(ln1a.y + ln1b.y) / 2;
      }
    }
    return true;
  }
References FloatingPointTolerance, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
GetIntersectPoint64()
Point64 Clipper2Lib::GetIntersectPoint64 (const Point64 & ln1a, const Point64 & ln1b, const Point64 & ln2a, const Point64 & ln2b)
  {
    // see http://astronomy.swin.edu.au/~pbourke/geometry/lineline2d/
    if (ln1b.x == ln1a.x)
    {
      if (ln2b.x == ln2a.x) return Point64(); // parallel lines
      double m2 = static_cast<double>(ln2b.y - ln2a.y) / (ln2b.x - ln2a.x);
      double b2 = ln2a.y - m2 * ln2a.x;
      return Point64(ln1a.x, static_cast<int64_t>(std::round(m2 * ln1a.x + b2)));
    }
    else if (ln2b.x == ln2a.x)
    {
      double m1  = static_cast<double>(ln1b.y - ln1a.y) / (ln1b.x - ln1a.x);
      double b1 = ln1a.y - m1 * ln1a.x;
      return Point64(ln2a.x, static_cast<int64_t>(std::round(m1 * ln2a.x + b1)));
    }
    else
    {
      double m1 = static_cast<double>(ln1b.y - ln1a.y) / (ln1b.x - ln1a.x);
      double b1 = ln1a.y - m1 * ln1a.x;
      double m2 = static_cast<double>(ln2b.y - ln2a.y) / (ln2b.x - ln2a.x);
      double b2 = ln2a.y - m2 * ln2a.x;
      if (std::fabs(m1 - m2) > 1.0E-15)
      {
        double x = (b2 - b1) / (m1 - m2);
        return Point64(x, m1 * x + b1);
      }
      else
        return Point64((ln1a.x + ln1b.x) * 0.5, (ln1a.y + ln1b.y) * 0.5);
    }
  }
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by GetIntersection().
GetLocation()
bool Clipper2Lib::GetLocation (const Rect64 & rec, const Point64 & pt, Location & loc) inline
  {
    if (pt.x == rec.left && pt.y >= rec.top && pt.y <= rec.bottom)
    {
      loc = Location::Left;
      return false;
    }
    else if (pt.x == rec.right && pt.y >= rec.top && pt.y <= rec.bottom)
    {
      loc = Location::Right;
      return false;
    }
    else if (pt.y == rec.top && pt.x >= rec.left && pt.x <= rec.right)
    {
      loc = Location::Top;
      return false;
    }
    else if (pt.y == rec.bottom && pt.x >= rec.left && pt.x <= rec.right)
    {
      loc = Location::Bottom;
      return false;
    }
    else if (pt.x < rec.left) loc = Location::Left;
    else if (pt.x > rec.right) loc = Location::Right;
    else if (pt.y < rec.top) loc = Location::Top;
    else if (pt.y > rec.bottom) loc = Location::Bottom;
    else loc = Location::Inside;
    return true;
  }
References Clipper2Lib::Rect< T >::bottom, Bottom, Inside, Clipper2Lib::Rect< T >::left, Left, Clipper2Lib::Rect< T >::right, Right, Clipper2Lib::Rect< T >::top, Top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::RectClip::Execute(), and Clipper2Lib::RectClipLines::Execute().
GetLowestPolygonIdx()
Paths64::size_type Clipper2Lib::GetLowestPolygonIdx (const Paths64 & paths)
{
  Paths64::size_type result = 0;
  Point64 lp = Point64(static_cast<int64_t>(0),
    std::numeric_limits<int64_t>::min());
  for (Paths64::size_type i = 0 ; i < paths.size(); ++i)
    for (const Point64& p : paths[i])
    {
      if (p.y < lp.y || (p.y == lp.y && p.x >= lp.x)) continue;
      result = i;
      lp = p;
    }
  return result;
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperOffset::DoGroupOffset().
GetMaximaPair()
Active * Clipper2Lib::GetMaximaPair (const Active & e)
  {
    Active* e2;
    e2 = e.next_in_ael;
    while (e2)
    {
      if (e2->vertex_top == e.vertex_top) return e2;  // Found!
      e2 = e2->next_in_ael;
    }
    return nullptr;
  }
References Clipper2Lib::Active::next_in_ael, and Clipper2Lib::Active::vertex_top.
Referenced by Clipper2Lib::ClipperBase::DoMaxima().
GetPerpendic()
Point64 Clipper2Lib::GetPerpendic (const Point64 & pt, const PointD & norm, double delta) inline
{
  return Point64(pt.x + norm.x * delta, pt.y + norm.y * delta);
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperOffset::DoRound(), and Clipper2Lib::ClipperOffset::OffsetOpenPath().
GetPerpendicD()
PointD Clipper2Lib::GetPerpendicD (const Point64 & pt, const PointD & norm, double delta) inline
{
  return PointD(pt.x + norm.x * delta, pt.y + norm.y * delta);
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperOffset::DoSquare().
GetPolyType()
PathType Clipper2Lib::GetPolyType (const Active & e) inline
  {
    return e.local_min->polytype;
  }
References Clipper2Lib::Active::local_min, and Clipper2Lib::LocalMinima::polytype.
Referenced by Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::ClipperBase::IsContributingClosed(), Clipper2Lib::ClipperBase::SetWindCountForClosedPathEdge(), and Clipper2Lib::ClipperBase::SetWindCountForOpenPathEdge().
GetPrevHotEdge()
Active * Clipper2Lib::GetPrevHotEdge (const Active & e) inline
  {
    Active* prev = e.prev_in_ael;
    while (prev && (IsOpen(*prev) || !IsHotEdge(*prev)))
      prev = prev->prev_in_ael;
    return prev;
  }
References IsHotEdge(), IsOpen(), and Clipper2Lib::Active::prev_in_ael.
Referenced by Clipper2Lib::ClipperBase::AddLocalMinPoly().
GetRealOutRec()
OutRec * Clipper2Lib::GetRealOutRec (OutRec * outrec) inline
  {
    while (outrec && !outrec->pts) outrec = outrec->owner;
    return outrec;
  }
References Clipper2Lib::OutRec::owner, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::Clipper64::BuildTree64(), Clipper2Lib::ClipperD::BuildTreeD(), Clipper2Lib::ClipperBase::CleanCollinear(), Clipper2Lib::ClipperBase::DeepCheckOwner(), GetHorzExtendedHorzSeg(), Clipper2Lib::ClipperBase::ProcessJoin(), and Clipper2Lib::ClipperBase::SafeDisposeOutPts().
GetUnitNormal()
PointD Clipper2Lib::GetUnitNormal (const Point64 & pt1, const Point64 & pt2)
{
  double dx, dy, inverse_hypot;
  if (pt1 == pt2) return PointD(0.0, 0.0);
  dx = static_cast<double>(pt2.x - pt1.x);
  dy = static_cast<double>(pt2.y - pt1.y);
  inverse_hypot = 1.0 / hypot(dx, dy);
  dx *= inverse_hypot;
  dy *= inverse_hypot;
  return PointD(dy, -dx);
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperOffset::BuildNormals().
HeadingClockwise()
bool Clipper2Lib::HeadingClockwise (Location prev, Location curr) inline
  {
    return (static_cast<int>(prev) + 1) % 4 == static_cast<int>(curr);
  }
Referenced by Clipper2Lib::RectClip::AddCorner(), Clipper2Lib::RectClip::Execute(), and IsClockwise().
HorzEdgesOverlap()
bool Clipper2Lib::HorzEdgesOverlap (int64_t x1a, int64_t x1b, int64_t x2a, int64_t x2b) inline
  {
    const int64_t minOverlap = 2;
    if (x1a > x1b + minOverlap)
    {
      if (x2a > x2b + minOverlap)
        return !((x1a <= x2b) || (x2a <= x1b));
      else
        return !((x1a <= x2a) || (x2b <= x1b));
    }
    else if (x1b > x1a + minOverlap)
    {
      if (x2a > x2b + minOverlap)
        return !((x1b <= x2b) || (x2a <= x1a));
      else
        return !((x1b <= x2a) || (x2b <= x1a));
    }
    else
      return false;
  }
Referenced by Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins().
HorzIsSpike()
bool Clipper2Lib::HorzIsSpike (const Active & horzEdge) inline
  {
    Point64 nextPt = NextVertex(horzEdge)->pt;
    return (nextPt.y == horzEdge.bot.y) &&
      (horzEdge.bot.x < horzEdge.top.x) != (horzEdge.top.x < nextPt.x);
  }
References Clipper2Lib::Active::bot, NextVertex(), Clipper2Lib::Vertex::pt, Clipper2Lib::Active::top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal().
Hypot()
double Clipper2Lib::Hypot (double x, double y) inline
{
  //see https://stackoverflow.com/a/32436148/359538
  return std::sqrt(x * x + y * y);
}
Referenced by NormalizeVector().
InflatePaths() [1/2]
Paths64 Clipper2Lib::InflatePaths (const Paths64 & paths, double delta, JoinType jt, EndType et, double miter_limit = 2.0) inline
  {
    ClipperOffset clip_offset(miter_limit);
    clip_offset.AddPaths(paths, jt, et);
    return clip_offset.Execute(delta);
  }
References Clipper2Lib::ClipperOffset::AddPaths(), and Clipper2Lib::ClipperOffset::Execute().
InflatePaths() [2/2]
PathsD Clipper2Lib::InflatePaths (const PathsD & paths, double delta, JoinType jt, EndType et, double miter_limit = 2.0, int precision = 2) inline
  {
    CheckPrecision(precision);
    const double scale = std::pow(10, precision);
    ClipperOffset clip_offset(miter_limit);
    clip_offset.AddPaths(ScalePaths<int64_t,double>(paths, scale), jt, et);
    Paths64 tmp = clip_offset.Execute(delta * scale);
    return ScalePaths<double, int64_t>(tmp, 1 / scale);
  }
References Clipper2Lib::ClipperOffset::AddPaths(), CheckPrecision(), Clipper2Lib::ClipperOffset::Execute(), and scale().
InflatePaths64()
EXTERN_DLL_EXPORT CPaths64 Clipper2Lib::InflatePaths64 (const CPaths64 paths, double delta, uint8_t jointype, uint8_t endtype, double miter_limit = 2.0, double arc_tolerance = 0.0, bool reverse_solution = false)
{
  Paths64 pp;
  pp = ConvertCPaths64(paths);
  ClipperOffset clip_offset( miter_limit,
    arc_tolerance, reverse_solution);
  clip_offset.AddPaths(pp, JoinType(jointype), EndType(endtype));
  Paths64 result = clip_offset.Execute(delta);
  return CreateCPaths64(result);
}
References Clipper2Lib::ClipperOffset::AddPaths(), ConvertCPaths64(), CreateCPaths64(), and Clipper2Lib::ClipperOffset::Execute().
InflatePathsD()
EXTERN_DLL_EXPORT CPathsD Clipper2Lib::InflatePathsD (const CPathsD paths, double delta, uint8_t jointype, uint8_t endtype, int precision = 2, double miter_limit = 2.0, double arc_tolerance = 0.0, bool reverse_solution = false)
{
  if (precision < -8 || precision > 8 || !paths) return nullptr;
  const double scale = std::pow(10, precision);
  ClipperOffset clip_offset(miter_limit, arc_tolerance, reverse_solution);
  Paths64 pp = ConvertCPathsD(paths, scale);
  clip_offset.AddPaths(pp, JoinType(jointype), EndType(endtype));
  Paths64 result = clip_offset.Execute(delta * scale);
  return CreateCPathsD(result, 1/scale);
}
References Clipper2Lib::ClipperOffset::AddPaths(), ConvertCPathsD(), CreateCPathsD(), Clipper2Lib::ClipperOffset::Execute(), and scale().
InitCPolyPath64()
void Clipper2Lib::InitCPolyPath64 (CPolyTree64 * cpt, bool is_hole, const PolyPath64 * pp) inline
{
  cpt->polygon = CreateCPath64(pp->Polygon());
  cpt->is_hole = is_hole;
  size_t child_cnt = pp->Count();
  cpt->child_count = static_cast<uint32_t>(child_cnt);
  cpt->childs = nullptr;
  if (!child_cnt) return;
  cpt->childs = new CPolyPath64[child_cnt];
  CPolyPath64* child = cpt->childs;
  for (const PolyPath64* pp_child : *pp)
    InitCPolyPath64(child++, !is_hole, pp_child);
}
References Clipper2Lib::CPolyPath64::child_count, Clipper2Lib::CPolyPath64::childs, Clipper2Lib::PolyPath64::Count(), CreateCPath64(), InitCPolyPath64(), Clipper2Lib::CPolyPath64::is_hole, Clipper2Lib::PolyPath64::Polygon(), and Clipper2Lib::CPolyPath64::polygon.
Referenced by CreateCPolyTree64(), and InitCPolyPath64().
InitCPolyPathD()
void Clipper2Lib::InitCPolyPathD (CPolyTreeD * cpt, bool is_hole, const PolyPath64 * pp, double scale) inline
{
  cpt->polygon = CreateCPathD(pp->Polygon(), scale);
  cpt->is_hole = is_hole;
  size_t child_cnt = pp->Count();
  cpt->child_count = static_cast<uint32_t>(child_cnt);
  cpt->childs = nullptr;
  if (!child_cnt) return;
  cpt->childs = new CPolyPathD[child_cnt];
  CPolyPathD* child = cpt->childs;
  for (const PolyPath64* pp_child : *pp)
    InitCPolyPathD(child++, !is_hole, pp_child, scale);
}
References Clipper2Lib::CPolyPathD::child_count, Clipper2Lib::CPolyPathD::childs, Clipper2Lib::PolyPath64::Count(), CreateCPathD(), InitCPolyPathD(), Clipper2Lib::CPolyPathD::is_hole, Clipper2Lib::PolyPath64::Polygon(), Clipper2Lib::CPolyPathD::polygon, and scale().
Referenced by CreateCPolyTreeD(), and InitCPolyPathD().
Insert1Before2InSEL()
void Clipper2Lib::Insert1Before2InSEL (Active * ae1, Active * ae2) inline
  {
    ae1->prev_in_sel = ae2->prev_in_sel;
    if (ae1->prev_in_sel)
      ae1->prev_in_sel->next_in_sel = ae1;
    ae1->next_in_sel = ae2;
    ae2->prev_in_sel = ae1;
  }
References Clipper2Lib::Active::next_in_sel, and Clipper2Lib::Active::prev_in_sel.
Referenced by Clipper2Lib::ClipperBase::BuildIntersectList().
InsertOp()
OutPt * Clipper2Lib::InsertOp (const Point64 & pt, OutPt * insertAfter) inline
  {
    OutPt* result = new OutPt(pt, insertAfter->outrec);
    result->next = insertAfter->next;
    insertAfter->next->prev = result;
    insertAfter->next = result;
    result->prev = insertAfter;
    return result;
  }
References Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::outrec, and Clipper2Lib::OutPt::prev.
Referenced by Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins(), and Clipper2Lib::ClipperBase::ProcessJoin().
InsertRightEdge()
void Clipper2Lib::InsertRightEdge (Active & e, Active & e2)
  {
    e2.next_in_ael = e.next_in_ael;
    if (e.next_in_ael) e.next_in_ael->prev_in_ael = &e2;
    e2.prev_in_ael = &e;
    e.next_in_ael = &e2;
  }
References Clipper2Lib::Active::next_in_ael, and Clipper2Lib::Active::prev_in_ael.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
Intersect() [1/2]
Paths64 Clipper2Lib::Intersect (const Paths64 & subjects, const Paths64 & clips, FillRule fillrule) inline
  {
    return BooleanOp(ClipType::Intersection, fillrule, subjects, clips);
  }
References BooleanOp(), and Intersection.
Intersect() [2/2]
PathsD Clipper2Lib::Intersect (const PathsD & subjects, const PathsD & clips, FillRule fillrule, int decimal_prec = 2) inline
  {
    return BooleanOp(ClipType::Intersection, fillrule, subjects, clips, decimal_prec);
  }
References BooleanOp(), and Intersection.
IntersectListSort()
bool Clipper2Lib::IntersectListSort (const IntersectNode & a, const IntersectNode & b)
  {
    //note different inequality tests ...
    return (a.pt.y == b.pt.y) ? (a.pt.x < b.pt.x) : (a.pt.y > b.pt.y);
  }
Referenced by Clipper2Lib::ClipperBase::ProcessIntersectList().
IntersectPoint()
PointD Clipper2Lib::IntersectPoint (const PointD & pt1a, const PointD & pt1b, const PointD & pt2a, const PointD & pt2b)
{
  if (pt1a.x == pt1b.x) //vertical
  {
    if (pt2a.x == pt2b.x) return PointD(0, 0);
    double m2 = (pt2b.y - pt2a.y) / (pt2b.x - pt2a.x);
    double b2 = pt2a.y - m2 * pt2a.x;
    return PointD(pt1a.x, m2 * pt1a.x + b2);
  }
  else if (pt2a.x == pt2b.x) //vertical
  {
    double m1 = (pt1b.y - pt1a.y) / (pt1b.x - pt1a.x);
    double b1 = pt1a.y - m1 * pt1a.x;
    return PointD(pt2a.x, m1 * pt2a.x + b1);
  }
  else
  {
    double m1 = (pt1b.y - pt1a.y) / (pt1b.x - pt1a.x);
    double b1 = pt1a.y - m1 * pt1a.x;
    double m2 = (pt2b.y - pt2a.y) / (pt2b.x - pt2a.x);
    double b2 = pt2a.y - m2 * pt2a.x;
    if (m1 == m2) return PointD(0, 0);
    double x = (b2 - b1) / (m1 - m2);
    return PointD(x, m1 * x + b1);
  }
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperOffset::DoSquare().
IsClockwise()
bool Clipper2Lib::IsClockwise (Location prev, Location curr, Point64 prev_pt, Point64 curr_pt, Point64 rect_mp) inline
  {
    if (AreOpposites(prev, curr))
      return CrossProduct(prev_pt, rect_mp, curr_pt) < 0;
    else
      return HeadingClockwise(prev, curr);
  }
References AreOpposites(), CrossProduct(), and HeadingClockwise().
Referenced by Clipper2Lib::RectClip::Execute().
IsClosedPath()
bool Clipper2Lib::IsClosedPath (EndType et) inline
{
  return et == EndType::Polygon || et == EndType::Joined;
}
References Joined, and Polygon.
Referenced by Clipper2Lib::ClipperOffset::DoGroupOffset().
IsFront()
bool Clipper2Lib::IsFront (const Active & e) inline
  {
    return (&e == e.outrec->front_edge);
  }
References Clipper2Lib::OutRec::front_edge, and Clipper2Lib::Active::outrec.
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::AddOutPt(), Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::ClipperBase::IntersectEdges(), and Clipper2Lib::ClipperBase::JoinOutrecPaths().
IsHeadingLeftHorz()
bool Clipper2Lib::IsHeadingLeftHorz (const Active & e) inline
  {
    return e.dx == std::numeric_limits<double>::max();
  }
References Clipper2Lib::Active::dx.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
IsHeadingRightHorz()
bool Clipper2Lib::IsHeadingRightHorz (const Active & e) inline
  {
    return e.dx == -std::numeric_limits<double>::max();
  }
References Clipper2Lib::Active::dx.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
IsHorizontal()
bool Clipper2Lib::IsHorizontal (const Active & e) inline
  {
    return (e.top.y == e.bot.y);
  }
References Clipper2Lib::Active::bot, Clipper2Lib::Active::top, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::ClipperBase::DoTopOfScanbeam(), FindEdgeWithMatchingLocMin(), GetIntersectPoint(), Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), Clipper2Lib::ClipperBase::IntersectEdges(), and Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL().
IsHotEdge()
bool Clipper2Lib::IsHotEdge (const Active & e) inline
  {
    return (e.outrec);
  }
References Clipper2Lib::Active::outrec.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::ClipperBase::DoTopOfScanbeam(), GetPrevHotEdge(), Clipper2Lib::ClipperBase::IntersectEdges(), TestJoinWithNext1(), TestJoinWithNext2(), TestJoinWithPrev1(), and TestJoinWithPrev2().
IsInvalidPath()
bool Clipper2Lib::IsInvalidPath (OutPt * op) inline
  {
    return (!op || op->next == op);
  }
References Clipper2Lib::OutPt::next.
IsMaxima() [1/2]
bool Clipper2Lib::IsMaxima (const Active & e) inline
  {
    return IsMaxima(*e.vertex_top);
  }
References IsMaxima(), and Clipper2Lib::Active::vertex_top.
IsMaxima() [2/2]
bool Clipper2Lib::IsMaxima (const Vertex & v) inline
  {
    return ((v.flags & VertexFlags::LocalMax) != VertexFlags::None);
  }
References Clipper2Lib::Vertex::flags, LocalMax, and None.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoTopOfScanbeam(), GetCurrYMaximaVertex(), IsMaxima(), IsValidAelOrder(), and TrimHorz().
IsOdd()
bool Clipper2Lib::IsOdd (int val) inline
  {
    return (val & 1) ? true : false;
  }
Referenced by Clipper2Lib::ClipperBase::SetWindCountForOpenPathEdge().
IsOpen()
bool Clipper2Lib::IsOpen (const Active & e) inline
  {
    return (e.local_min->is_open);
  }
References Clipper2Lib::LocalMinima::is_open, and Clipper2Lib::Active::local_min.
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::AddLocalMinPoly(), Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), GetPrevHotEdge(), Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), Clipper2Lib::ClipperBase::IntersectEdges(), Clipper2Lib::ClipperBase::SetWindCountForClosedPathEdge(), Clipper2Lib::ClipperBase::SetWindCountForOpenPathEdge(), TestJoinWithNext1(), TestJoinWithNext2(), TestJoinWithPrev1(), and TestJoinWithPrev2().
IsOpenEnd() [1/2]
bool Clipper2Lib::IsOpenEnd (const Active & ae) inline
  {
    return IsOpenEnd(*ae.vertex_top);
  }
References IsOpenEnd(), and Clipper2Lib::Active::vertex_top.
IsOpenEnd() [2/2]
bool Clipper2Lib::IsOpenEnd (const Vertex & v) inline
  {
    return (v.flags & (VertexFlags::OpenStart | VertexFlags::OpenEnd)) !=
      VertexFlags::None;
  }
References Clipper2Lib::Vertex::flags, None, OpenEnd, and OpenStart.
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly(), Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoMaxima(), Clipper2Lib::ClipperBase::IntersectEdges(), IsOpenEnd(), and Clipper2Lib::ClipperBase::JoinOutrecPaths().
IsPositive()
template<typename T > bool Clipper2Lib::IsPositive (const Path< T > & poly) inline
{
  // A curve has positive orientation [and area] if a region 'R'
  // is on the left when traveling around the outside of 'R'.
  //https://mathworld.wolfram.com/CurveOrientation.html
  //nb: This statement is premised on using Cartesian coordinates
  return Area<T>(poly) >= 0;
}
Referenced by Clipper2Lib::detail::Minkowski().
IsSamePolyType()
bool Clipper2Lib::IsSamePolyType (const Active & e1, const Active & e2) inline
  {
    return e1.local_min->polytype == e2.local_min->polytype;
  }
References Clipper2Lib::Active::local_min, and Clipper2Lib::LocalMinima::polytype.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), and Clipper2Lib::ClipperBase::IntersectEdges().
IsValidAelOrder()
bool Clipper2Lib::IsValidAelOrder (const Active & resident, const Active & newcomer)
  {
    if (newcomer.curr_x != resident.curr_x)
      return newcomer.curr_x > resident.curr_x;
    //get the turning direction  a1.top, a2.bot, a2.top
    double d = CrossProduct(resident.top, newcomer.bot, newcomer.top);
    if (d != 0) return d < 0;
    //edges must be collinear to get here
    //for starting open paths, place them according to
    //the direction they're about to turn
    if (!IsMaxima(resident) && (resident.top.y > newcomer.top.y))
    {
      return CrossProduct(newcomer.bot,
        resident.top, NextVertex(resident)->pt) <= 0;
    }
    else if (!IsMaxima(newcomer) && (newcomer.top.y > resident.top.y))
    {
      return CrossProduct(newcomer.bot,
        newcomer.top, NextVertex(newcomer)->pt) >= 0;
    }
    int64_t y = newcomer.bot.y;
    bool newcomerIsLeft = newcomer.is_left_bound;
    if (resident.bot.y != y || resident.local_min->vertex->pt.y != y)
      return newcomer.is_left_bound;
    //resident must also have just been inserted
    else if (resident.is_left_bound != newcomerIsLeft)
      return newcomerIsLeft;
    else if (CrossProduct(PrevPrevVertex(resident)->pt,
      resident.bot, resident.top) == 0) return true;
    else
      //compare turning direction of the alternate bound
      return (CrossProduct(PrevPrevVertex(resident)->pt,
        newcomer.bot, PrevPrevVertex(newcomer)->pt) > 0) == newcomerIsLeft;
  }
References Clipper2Lib::Active::bot, CrossProduct(), Clipper2Lib::Active::curr_x, Clipper2Lib::Active::is_left_bound, IsMaxima(), Clipper2Lib::Active::local_min, NextVertex(), PrevPrevVertex(), Clipper2Lib::Vertex::pt, Clipper2Lib::Active::top, Clipper2Lib::LocalMinima::vertex, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::InsertLeftEdge(), and Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
IsValidClosedPath()
bool Clipper2Lib::IsValidClosedPath (const OutPt * op) inline
  {
    return op && (op->next != op) && (op->next != op->prev) &&
      !IsVerySmallTriangle(*op);
  }
References IsVerySmallTriangle(), Clipper2Lib::OutPt::next, and Clipper2Lib::OutPt::prev.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin(), and Clipper2Lib::ClipperBase::ValidateClosedPathEx().
IsValidPath()
bool Clipper2Lib::IsValidPath (OutPt * op) inline
  {
    return (op && op->next != op);
  }
References Clipper2Lib::OutPt::next.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin().
IsVerySmallTriangle()
bool Clipper2Lib::IsVerySmallTriangle (const OutPt & op) inline
  {
    return op.next->next == op.prev &&
      (PtsReallyClose(op.prev->pt, op.next->pt) ||
        PtsReallyClose(op.pt, op.next->pt) ||
        PtsReallyClose(op.pt, op.prev->pt));
  }
References Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::prev, Clipper2Lib::OutPt::pt, and PtsReallyClose().
Referenced by BuildPath64(), BuildPathD(), and IsValidClosedPath().
Length()
template<typename T > double Clipper2Lib::Length (const Path< T > & path, bool is_closed_path = false) inline
  {
    double result = 0.0;
    if (path.size() < 2) return result;
    auto it = path.cbegin(), stop = path.end() - 1;
    for (; it != stop; ++it)
      result += Distance(*it, *(it + 1));
    if (is_closed_path)
      result += Distance(*stop, *path.cbegin());
    return result;
  }
References Distance().
MakePath()
Path64 Clipper2Lib::MakePath (const std::string & s) inline
  {
    const std::string skip_chars = " ,(){}[]";
    Path64 result;
    std::string::const_iterator s_iter = s.cbegin();
    details::SkipUserDefinedChars(s_iter, s.cend(), skip_chars);
    while (s_iter != s.cend())
    {
      int64_t y = 0, x = 0;
      if (!details::GetInt(s_iter, s.cend(), x)) break;
      details::SkipSpacesWithOptionalComma(s_iter, s.cend());
      if (!details::GetInt(s_iter, s.cend(), y)) break;
      result.push_back(Point64(x, y));
      details::SkipUserDefinedChars(s_iter, s.cend(), skip_chars);
    }
    return result;
  }
References Clipper2Lib::details::GetInt(), Clipper2Lib::details::SkipSpacesWithOptionalComma(), and Clipper2Lib::details::SkipUserDefinedChars().
MakePathD()
PathD Clipper2Lib::MakePathD (const std::string & s) inline
  {
    const std::string skip_chars = " ,(){}[]";
    PathD result;
    std::string::const_iterator s_iter = s.cbegin();
    details::SkipUserDefinedChars(s_iter, s.cend(), skip_chars);
    while (s_iter != s.cend())
    {
      double y = 0, x = 0;
      if (!details::GetFloat(s_iter, s.cend(), x)) break;
      details::SkipSpacesWithOptionalComma(s_iter, s.cend());
      if (!details::GetFloat(s_iter, s.cend(), y)) break;
      result.push_back(PointD(x, y));
      details::SkipUserDefinedChars(s_iter, s.cend(), skip_chars);
    }
    return result;
  }
References Clipper2Lib::details::GetFloat(), Clipper2Lib::details::SkipSpacesWithOptionalComma(), and Clipper2Lib::details::SkipUserDefinedChars().
MinkowskiDiff() [1/2]
Paths64 Clipper2Lib::MinkowskiDiff (const Path64 & pattern, const Path64 & path, bool isClosed) inline
  {
    return detail::Union(detail::Minkowski(pattern, path, false, isClosed), FillRule::NonZero);
  }
References Clipper2Lib::detail::Minkowski(), NonZero, and Clipper2Lib::detail::Union().
MinkowskiDiff() [2/2]
PathsD Clipper2Lib::MinkowskiDiff (const PathD & pattern, const PathD & path, bool isClosed, int decimalPlaces = 2) inline
  {
    double scale = pow(10, decimalPlaces);
    Path64 pat64 = ScalePath<int64_t, double>(pattern, scale);
    Path64 path64 = ScalePath<int64_t, double>(path, scale);
    Paths64 tmp = detail::Union(detail::Minkowski(pat64, path64, false, isClosed), FillRule::NonZero);
    return ScalePaths<double, int64_t>(tmp, 1 / scale);
  }
References Clipper2Lib::detail::Minkowski(), NonZero, scale(), and Clipper2Lib::detail::Union().
MinkowskiSum() [1/2]
Paths64 Clipper2Lib::MinkowskiSum (const Path64 & pattern, const Path64 & path, bool isClosed) inline
  {
    return detail::Union(detail::Minkowski(pattern, path, true, isClosed), FillRule::NonZero);
  }
References Clipper2Lib::detail::Minkowski(), NonZero, and Clipper2Lib::detail::Union().
MinkowskiSum() [2/2]
PathsD Clipper2Lib::MinkowskiSum (const PathD & pattern, const PathD & path, bool isClosed, int decimalPlaces = 2) inline
  {
    double scale = pow(10, decimalPlaces);
    Path64 pat64 = ScalePath<int64_t, double>(pattern, scale);
    Path64 path64 = ScalePath<int64_t, double>(path, scale);
    Paths64 tmp = detail::Union(detail::Minkowski(pat64, path64, true, isClosed), FillRule::NonZero);
    return ScalePaths<double, int64_t>(tmp, 1 / scale);
  }
References Clipper2Lib::detail::Minkowski(), NonZero, scale(), and Clipper2Lib::detail::Union().
NearCollinear()
template<typename T > bool Clipper2Lib::NearCollinear (const Point< T > & pt1, const Point< T > & pt2, const Point< T > & pt3, double sin_sqrd_min_angle_rads) inline
  {
    double cp = std::abs(CrossProduct(pt1, pt2, pt3));
    return (cp * cp) / (DistanceSqr(pt1, pt2) * DistanceSqr(pt2, pt3)) < sin_sqrd_min_angle_rads;
  }
References CrossProduct(), and DistanceSqr().
NearEqual()
template<typename T > bool Clipper2Lib::NearEqual (const Point< T > & p1, const Point< T > & p2, double max_dist_sqrd) inline
{
  return Sqr(p1.x - p2.x) + Sqr(p1.y - p2.y) < max_dist_sqrd;
}
References Sqr(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by StripNearEqual().
NextVertex()
Vertex * Clipper2Lib::NextVertex (const Active & e) inline
  {
    if (e.wind_dx > 0)
      return e.vertex_top->next;
    else
      return e.vertex_top->prev;
  }
References Clipper2Lib::Vertex::next, Clipper2Lib::Vertex::prev, Clipper2Lib::Active::vertex_top, and Clipper2Lib::Active::wind_dx.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), HorzIsSpike(), IsValidAelOrder(), TrimHorz(), and Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL().
NormalizeVector()
PointD Clipper2Lib::NormalizeVector (const PointD & vec) inline
{
  double h = Hypot(vec.x, vec.y);
  if (AlmostZero(h)) return PointD(0,0);
  double inverseHypot = 1 / h;
  return PointD(vec.x * inverseHypot, vec.y * inverseHypot);
}
References AlmostZero(), Hypot(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by GetAvgUnitVector().
operator&()
constexpr enum VertexFlags Clipper2Lib::operator& (enum VertexFlags a, enum VertexFlags b) constexpr
  {
    return (enum VertexFlags)(uint32_t(a) & uint32_t(b));
  }
operator<<() [1/2]
template<typename T > std::ostream & Clipper2Lib::operator<< (std::ostream & outstream, const Path< T > & path)
{
  if (!path.empty())
  {
    auto pt = path.cbegin(), last = path.cend() - 1;
    while (pt != last)
      outstream << *pt++ << ", ";
    outstream << *last << std::endl;
  }
  return outstream;
}
operator<<() [2/2]
template<typename T > std::ostream & Clipper2Lib::operator<< (std::ostream & outstream, const Paths< T > & paths)
{
  for (auto p : paths)
    outstream << p;
  return outstream;
}
operator|()
constexpr enum VertexFlags Clipper2Lib::operator| (enum VertexFlags a, enum VertexFlags b) constexpr
  {
    return (enum VertexFlags)(uint32_t(a) | uint32_t(b));
  }
OutrecIsAscending()
bool Clipper2Lib::OutrecIsAscending (const Active * hotEdge) inline
  {
    return (hotEdge == hotEdge->outrec->front_edge);
  }
References Clipper2Lib::OutRec::front_edge, and Clipper2Lib::Active::outrec.
Referenced by Clipper2Lib::ClipperBase::AddLocalMinPoly().
Path1ContainsPath2()
PointInPolygonResult Clipper2Lib::Path1ContainsPath2 (Path64 path1, Path64 path2) inline
  {
    PointInPolygonResult result = PointInPolygonResult::IsOn;
    for(const Point64& pt : path2)
    {
      result = PointInPolygon(pt, path1);
      if (result != PointInPolygonResult::IsOn) break;
    }
    return result;
  }
References IsOn, and PointInPolygon().
Referenced by Clipper2Lib::RectClip::Execute().
Path1InsidePath2()
bool Clipper2Lib::Path1InsidePath2 (const OutRec * or1, const OutRec * or2) inline
  {
    PointInPolygonResult result = PointInPolygonResult::IsOn;
    OutPt* op = or1->pts;
    do
    {
      result = PointInPolygon(op->pt, or2->path);
      if (result != PointInPolygonResult::IsOn) break;
      op = op->next;
    } while (op != or1->pts);
    if (result == PointInPolygonResult::IsOn)
      return Area(op) < Area(or2->pts);
    else
      return result == PointInPolygonResult::IsInside;
  }
References Area(), IsInside, IsOn, Clipper2Lib::OutPt::next, Clipper2Lib::OutRec::path, PointInPolygon(), Clipper2Lib::OutPt::pt, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::DeepCheckOwner().
Path64ToPathD()
PathD Clipper2Lib::Path64ToPathD (const Path64 & path) inline
{
  return TransformPath<double, int64_t>(path);
}
PathDToPath64()
Path64 Clipper2Lib::PathDToPath64 (const PathD & path) inline
{
  return TransformPath<int64_t, double>(path);
}
Paths64ToPathsD()
PathsD Clipper2Lib::Paths64ToPathsD (const Paths64 & paths) inline
{
  return TransformPaths<double, int64_t>(paths);
}
PathsDToPaths64()
Paths64 Clipper2Lib::PathsDToPaths64 (const PathsD & paths) inline
{
  return TransformPaths<int64_t, double>(paths);
}
Referenced by Clipper2Lib::ClipperOffset::AddPaths().
PerpendicDistFromLineSqrd()
template<typename T > double Clipper2Lib::PerpendicDistFromLineSqrd (const Point< T > & pt, const Point< T > & line1, const Point< T > & line2) inline
  {
    double a = static_cast<double>(pt.x - line1.x);
    double b = static_cast<double>(pt.y - line1.y);
    double c = static_cast<double>(line2.x - line1.x);
    double d = static_cast<double>(line2.y - line1.y);
    if (c == 0 && d == 0) return 0;
    return Sqr(a * d - c * b) / (c * c + d * d);
  }
References Sqr(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by RDP().
PointBetween()
bool Clipper2Lib::PointBetween (Point64 pt, Point64 corner1, Point64 corner2) inline
  {
    //NB points may not be collinear
    return ValueBetween(pt.x, corner1.x, corner2.x) &&
      ValueBetween(pt.y, corner1.y, corner2.y);
  }
References ValueBetween(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin().
PointCount()
int Clipper2Lib::PointCount (OutPt * op) inline
  {
    OutPt* op2 = op;
    int cnt = 0;
    do
    {
      op2 = op2->next;
      ++cnt;
    } while (op2 != op);
    return cnt;
  }
References Clipper2Lib::OutPt::next.
PointEqualOrBetween()
bool Clipper2Lib::PointEqualOrBetween (Point64 pt, Point64 corner1, Point64 corner2) inline
  {
    //NB points may not be collinear
    return ValueEqualOrBetween(pt.x, corner1.x, corner2.x) &&
      ValueEqualOrBetween(pt.y, corner1.y, corner2.y);
  }
References ValueEqualOrBetween(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ProcessJoin().
PointInPolygon()
template<typename T > PointInPolygonResult Clipper2Lib::PointInPolygon (const Point< T > & pt, const Path< T > & polygon) inline
{
  if (polygon.size() < 3)
    return PointInPolygonResult::IsOutside;
  int val = 0;
  typename Path<T>::const_iterator start = polygon.cbegin(), cit = start;
  typename Path<T>::const_iterator cend = polygon.cend(), pit = cend - 1;
  while (pit->y == pt.y)
  {
    if (pit == start) return PointInPolygonResult::IsOutside;
    --pit;
  }
  bool is_above = pit->y < pt.y;
  while (cit != cend)
  {
    if (is_above)
    {
      while (cit != cend && cit->y < pt.y) ++cit;
      if (cit == cend) break;
    }
    else
    {
      while (cit != cend && cit->y > pt.y) ++cit;
      if (cit == cend) break;
    }
    if (cit == start) pit = cend - 1;
    else  pit = cit - 1;
    if (cit->y == pt.y)
    {
      if (cit->x == pt.x || (cit->y == pit->y &&
        ((pt.x < pit->x) != (pt.x < cit->x))))
        return PointInPolygonResult::IsOn;
      ++cit;
      continue;
    }
    if (pt.x < cit->x && pt.x < pit->x)
    {
      // we're only interested in edges crossing on the left
    }
    else if (pt.x > pit->x && pt.x > cit->x)
      val = 1 - val; // toggle val
    else
    {
      double d = CrossProduct(*pit, *cit, pt);
      if (d == 0) return PointInPolygonResult::IsOn;
      if ((d < 0) == is_above) val = 1 - val;
    }
    is_above = !is_above;
    ++cit;
  }
  return (val == 0) ?
    PointInPolygonResult::IsOutside :
    PointInPolygonResult::IsInside;
}
References CrossProduct(), IsInside, IsOn, IsOutside, start, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Path1ContainsPath2(), Path1InsidePath2(), and Clipper2Lib::details::PolyPath64ContainsChildren().
PolyTreeToPaths64()
Paths64 Clipper2Lib::PolyTreeToPaths64 (const PolyTree64 & polytree) inline
  {
    Paths64 result;
    for (auto child : polytree)
      details::PolyPathToPaths64(*(PolyPath64*)(child), result);
    return result;
  }
References Clipper2Lib::details::PolyPathToPaths64().
PolyTreeToPathsD()
PathsD Clipper2Lib::PolyTreeToPathsD (const PolyTreeD & polytree) inline
  {
    PathsD result;
    for (auto child : polytree)
      details::PolyPathToPathsD(*(PolyPathD*)(child), result);
    return result;
  }
References Clipper2Lib::details::PolyPathToPathsD().
PrevPrevVertex()
Vertex * Clipper2Lib::PrevPrevVertex (const Active & ae) inline
  {
    if (ae.wind_dx > 0)
      return ae.vertex_top->prev->prev;
    else
      return ae.vertex_top->next->next;
  }
References Clipper2Lib::Vertex::next, Clipper2Lib::Vertex::prev, Clipper2Lib::Active::vertex_top, and Clipper2Lib::Active::wind_dx.
Referenced by IsValidAelOrder().
PtsReallyClose()
bool Clipper2Lib::PtsReallyClose (const Point64 & pt1, const Point64 & pt2) inline
  {
    return (std::llabs(pt1.x - pt2.x) < 2) && (std::llabs(pt1.y - pt2.y) < 2);
  }
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by IsVerySmallTriangle().
RamerDouglasPeucker() [1/2]
template<typename T > Path< T > Clipper2Lib::RamerDouglasPeucker (const Path< T > & path, double epsilon) inline
  {
    const typename Path<T>::size_type len = path.size();
    if (len < 5) return Path<T>(path);
    std::vector<bool> flags(len);
    flags[0] = true;
    flags[len - 1] = true;
    RDP(path, 0, len - 1, Sqr(epsilon), flags);
    Path<T> result;
    result.reserve(len);
    for (typename Path<T>::size_type i = 0; i < len; ++i)
      if (flags[i])
        result.push_back(path[i]);
    return result;
  }
References RDP(), and Sqr().
RamerDouglasPeucker() [2/2]
template<typename T > Paths< T > Clipper2Lib::RamerDouglasPeucker (const Paths< T > & paths, double epsilon) inline
  {
    Paths<T> result;
    result.reserve(paths.size());
    for (const Path<T>& path : paths)
      result.push_back(RamerDouglasPeucker<T>(path, epsilon));
    return result;
  }
RDP()
template<typename T > void Clipper2Lib::RDP (const Path< T > path, std::size_t begin, std::size_t end, double epsSqrd, std::vector< bool > & flags) inline
  {
    typename Path<T>::size_type idx = 0;
    double max_d = 0;
    while (end > begin && path[begin] == path[end]) flags[end--] = false;
    for (typename Path<T>::size_type i = begin + 1; i < end; ++i)
    {
      // PerpendicDistFromLineSqrd - avoids expensive Sqrt()
      double d = PerpendicDistFromLineSqrd(path[i], path[begin], path[end]);
      if (d <= max_d) continue;
      max_d = d;
      idx = i;
    }
    if (max_d <= epsSqrd) return;
    flags[idx] = true;
    if (idx > begin + 1) RDP(path, begin, idx, epsSqrd, flags);
    if (idx < end - 1) RDP(path, idx, end, epsSqrd, flags);
  }
References end, PerpendicDistFromLineSqrd(), and RDP().
Referenced by RamerDouglasPeucker(), and RDP().
RectClip() [1/4]
Path64 Clipper2Lib::RectClip (const Rect64 & rect, const Path64 & path) inline
  {
    if (rect.IsEmpty() || path.empty()) return Path64();
    Rect64 pathRec = Bounds(path);
    if (!rect.Intersects(pathRec)) return Path64();
    if (rect.Contains(pathRec)) return path;
    class RectClip rc(rect);
    return rc.Execute(path);
  }
References Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::RectClip::Execute(), Clipper2Lib::Rect< T >::Intersects(), and Clipper2Lib::Rect< T >::IsEmpty().
RectClip() [2/4]
Paths64 Clipper2Lib::RectClip (const Rect64 & rect, const Paths64 & paths) inline
  {
    if (rect.IsEmpty() || paths.empty()) return Paths64();
    class RectClip rc(rect);
    Paths64 result;
    result.reserve(paths.size());
    for (const Path64& p : paths)
    {
      Rect64 pathRec = Bounds(p);
      if (!rect.Intersects(pathRec))
        continue;
      else if (rect.Contains(pathRec))
        result.push_back(p);
      else
      {
        Path64 p2 = rc.Execute(p);
        if (!p2.empty()) result.push_back(std::move(p2));
      }
    }
    return result;
  }
References Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::RectClip::Execute(), Clipper2Lib::Rect< T >::Intersects(), and Clipper2Lib::Rect< T >::IsEmpty().
RectClip() [3/4]
PathD Clipper2Lib::RectClip (const RectD & rect, const PathD & path, int precision = 2) inline
  {
    if (rect.IsEmpty() || path.empty() ||
      !rect.Contains(Bounds(path))) return PathD();
    CheckPrecision(precision);
    const double scale = std::pow(10, precision);
    Rect64 r = ScaleRect<int64_t, double>(rect, scale);
    class RectClip rc(r);
    Path64 p = ScalePath<int64_t, double>(path, scale);
    return ScalePath<double, int64_t>(rc.Execute(p), 1 / scale);
  }
References Bounds(), CheckPrecision(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::RectClip::Execute(), Clipper2Lib::Rect< T >::IsEmpty(), and scale().
RectClip() [4/4]
PathsD Clipper2Lib::RectClip (const RectD & rect, const PathsD & paths, int precision = 2) inline
  {
    if (rect.IsEmpty() || paths.empty()) return PathsD();
    CheckPrecision(precision);
    const double scale = std::pow(10, precision);
    Rect64 r = ScaleRect<int64_t, double>(rect, scale);
    class RectClip rc(r);
    PathsD result;
    result.reserve(paths.size());
    for (const PathD& path : paths)
    {
      RectD pathRec = Bounds(path);
      if (!rect.Intersects(pathRec))
        continue;
      else if (rect.Contains(pathRec))
        result.push_back(path);
      else
      {
        Path64 p = ScalePath<int64_t, double>(path, scale);
        p = rc.Execute(p);
        if (!p.empty())
          result.push_back(ScalePath<double, int64_t>(p, 1 / scale));
      }
    }
    return result;
  }
References Bounds(), CheckPrecision(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::RectClip::Execute(), Clipper2Lib::Rect< T >::Intersects(), Clipper2Lib::Rect< T >::IsEmpty(), and scale().
RectClip64()
EXTERN_DLL_EXPORT CPaths64 Clipper2Lib::RectClip64 (const CRect64 & rect, const CPaths64 paths)
{
  if (CRectIsEmpty(rect) || !paths) return nullptr;
  Rect64 r64 = CRectToRect(rect);
  class RectClip rc(r64);
  Paths64 pp = ConvertCPaths64(paths);
  Paths64 result;
  result.reserve(pp.size());
  for (const Path64& p : pp)
  {
    Rect64 pathRec = Bounds(p);
    if (!r64.Intersects(pathRec)) continue;
    if (r64.Contains(pathRec))
      result.push_back(p);
    else
    {
      Path64 p2 = rc.Execute(p);
      if (!p2.empty()) result.push_back(std::move(p2));
    }
  }
  return CreateCPaths64(result);
}
References Bounds(), Clipper2Lib::Rect< T >::Contains(), ConvertCPaths64(), CreateCPaths64(), CRectIsEmpty(), CRectToRect(), Clipper2Lib::RectClip::Execute(), and Clipper2Lib::Rect< T >::Intersects().
RectClipD()
EXTERN_DLL_EXPORT CPathsD Clipper2Lib::RectClipD (const CRectD & rect, const CPathsD paths, int precision = 2)
{
  if (CRectIsEmpty(rect) || !paths) return nullptr;
  if (precision < -8 || precision > 8) return nullptr;
  const double scale = std::pow(10, precision);
  Rect64 r = ScaleRect<int64_t, double>(CRectToRect(rect), scale);
  Paths64 pp = ConvertCPathsD(paths, scale);
  class RectClip rc(r);
  Paths64 result;
  result.reserve(pp.size());
  for (const Path64& p : pp)
  {
    Rect64 pathRec = Bounds(p);
    if (!r.Intersects(pathRec)) continue;
    if (r.Contains(pathRec))
      result.push_back(p);
    else
    {
      Path64 p2 = rc.Execute(p);
      if (!p2.empty()) result.push_back(std::move(p2));
    }
  }
  return CreateCPathsD(result, 1/scale);
}
References Bounds(), Clipper2Lib::Rect< T >::Contains(), ConvertCPathsD(), CreateCPathsD(), CRectIsEmpty(), CRectToRect(), Clipper2Lib::RectClip::Execute(), Clipper2Lib::Rect< T >::Intersects(), and scale().
RectClipLines() [1/4]
Paths64 Clipper2Lib::RectClipLines (const Rect64 & rect, const Path64 & path) inline
  {
    Paths64 result;
    if (rect.IsEmpty() || path.empty()) return result;
    Rect64 pathRec = Bounds(path);
    if (!rect.Intersects(pathRec)) return result;
    if (rect.Contains(pathRec))
    {
      result.push_back(path);
      return result;
    }
    class RectClipLines rcl(rect);
    return rcl.Execute(path);
  }
References Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::RectClipLines::Execute(), Clipper2Lib::Rect< T >::Intersects(), and Clipper2Lib::Rect< T >::IsEmpty().
RectClipLines() [2/4]
Paths64 Clipper2Lib::RectClipLines (const Rect64 & rect, const Paths64 & paths) inline
  {
    Paths64 result;
    if (rect.IsEmpty() || paths.empty()) return result;
    class RectClipLines rcl(rect);
    for (const Path64& p : paths)
    {
      Rect64 pathRec = Bounds(p);
      if (!rect.Intersects(pathRec))
        continue;
      else if (rect.Contains(pathRec))
        result.push_back(p);
      else
      {
        Paths64 pp = rcl.Execute(p);
        if (!pp.empty())
          result.insert(result.end(), pp.begin(), pp.end());
      }
    }
    return result;
  }
References Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::RectClipLines::Execute(), Clipper2Lib::Rect< T >::Intersects(), and Clipper2Lib::Rect< T >::IsEmpty().
RectClipLines() [3/4]
PathsD Clipper2Lib::RectClipLines (const RectD & rect, const PathD & path, int precision = 2) inline
  {
    if (rect.IsEmpty() || path.empty() ||
      !rect.Contains(Bounds(path))) return PathsD();
    CheckPrecision(precision);
    const double scale = std::pow(10, precision);
    Rect64 r = ScaleRect<int64_t, double>(rect, scale);
    class RectClipLines rcl(r);
    Path64 p = ScalePath<int64_t, double>(path, scale);
    return ScalePaths<double, int64_t>(rcl.Execute(p), 1 / scale);
  }
References Bounds(), CheckPrecision(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::RectClipLines::Execute(), Clipper2Lib::Rect< T >::IsEmpty(), and scale().
RectClipLines() [4/4]
PathsD Clipper2Lib::RectClipLines (const RectD & rect, const PathsD & paths, int precision = 2) inline
  {
    PathsD result;
    if (rect.IsEmpty() || paths.empty()) return result;
    CheckPrecision(precision);
    const double scale = std::pow(10, precision);
    Rect64 r = ScaleRect<int64_t, double>(rect, scale);
    class RectClipLines rcl(r);
    result.reserve(paths.size());
    for (const PathD& path : paths)
    {
      RectD pathRec = Bounds(path);
      if (!rect.Intersects(pathRec))
        continue;
      else if (rect.Contains(pathRec))
        result.push_back(path);
      else
      {
        Path64 p = ScalePath<int64_t, double>(path, scale);
        Paths64 pp = rcl.Execute(p);
        if (pp.empty()) continue;
        PathsD ppd = ScalePaths<double, int64_t>(pp, 1 / scale);
        result.insert(result.end(), ppd.begin(), ppd.end());
      }
    }
    return result;
  }
References Bounds(), CheckPrecision(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::RectClipLines::Execute(), Clipper2Lib::Rect< T >::Intersects(), Clipper2Lib::Rect< T >::IsEmpty(), and scale().
RectClipLines64()
EXTERN_DLL_EXPORT CPaths64 Clipper2Lib::RectClipLines64 (const CRect64 & rect, const CPaths64 paths)
{
  if (CRectIsEmpty(rect) || !paths) return nullptr;
  Rect64 r = CRectToRect(rect);
  class RectClipLines rcl (r);
  Paths64 pp = ConvertCPaths64(paths);
  Paths64 result;
  result.reserve(pp.size());
  for (const Path64& p : pp)
  {
    Rect64 pathRec = Bounds(p);
    if (!r.Intersects(pathRec)) continue;
    if (r.Contains(pathRec))
      result.push_back(p);
    else
    {
      Paths64 pp2 = rcl.Execute(p);
      if (!pp2.empty())
        result.insert(result.end(), pp2.begin(), pp2.end());
    }
  }
  return CreateCPaths64(result);
}
References Bounds(), Clipper2Lib::Rect< T >::Contains(), ConvertCPaths64(), CreateCPaths64(), CRectIsEmpty(), CRectToRect(), Clipper2Lib::RectClipLines::Execute(), and Clipper2Lib::Rect< T >::Intersects().
RectClipLinesD()
EXTERN_DLL_EXPORT CPathsD Clipper2Lib::RectClipLinesD (const CRectD & rect, const CPathsD paths, int precision = 2)
{
  Paths64 result;
  if (CRectIsEmpty(rect) || !paths) return nullptr;
  if (precision < -8 || precision > 8) return nullptr;
  const double scale = std::pow(10, precision);
  Rect64 r = ScaleRect<int64_t, double>(CRectToRect(rect), scale);
  class RectClipLines rcl(r);
  Paths64 pp = ConvertCPathsD(paths, scale);
  result.reserve(pp.size());
  for (const Path64& p : pp)
  {
    Rect64 pathRec = Bounds(p);
    if (!r.Intersects(pathRec)) continue;
    if (r.Contains(pathRec))
      result.push_back(p);
    else
    {
      Paths64 pp2 = rcl.Execute(p);
      if (pp2.empty()) continue;
      result.insert(result.end(), pp2.begin(), pp2.end());
    }
  }
  return CreateCPathsD(result, 1/scale);
}
References Bounds(), Clipper2Lib::Rect< T >::Contains(), ConvertCPathsD(), CreateCPathsD(), CRectIsEmpty(), CRectToRect(), Clipper2Lib::RectClipLines::Execute(), Clipper2Lib::Rect< T >::Intersects(), and scale().
ReflectPoint()
PointD Clipper2Lib::ReflectPoint (const PointD & pt, const PointD & pivot) inline
{
  return PointD(pivot.x + (pivot.x - pt.x), pivot.y + (pivot.y - pt.y));
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperOffset::DoSquare().
ReverseOutPts()
void Clipper2Lib::ReverseOutPts (OutPt * op)
  {
    if (!op) return;
    OutPt* op1 = op;
    OutPt* op2;
    do
    {
      op2 = op1->next;
      op1->next = op1->prev;
      op1->prev = op2;
      op1 = op2;
    } while (op1 != op);
  }
References Clipper2Lib::OutPt::next, and Clipper2Lib::OutPt::prev.
ScalePath()
template<typename T1 , typename T2 > Path< T1 > Clipper2Lib::ScalePath (const Path< T2 > & path, double scale) inline
{
  Path<T1> result;
  result.reserve(path.size());
#ifdef USINGZ
  for (const Point<T2>& pt : path)
    result.push_back(Point<T1>(pt.x * scale, pt.y * scale, pt.z));
#else
  for (const Point<T2>& pt : path)
    result.push_back(Point<T1>(pt.x * scale, pt.y * scale));
#endif
  return result;
}
References scale().
ScalePaths()
template<typename T1 , typename T2 > Paths< T1 > Clipper2Lib::ScalePaths (const Paths< T2 > & paths, double scale) inline
{
  Paths<T1> result;
  result.reserve(paths.size());
  for (const Path<T2>& path : paths)
    result.push_back(ScalePath<T1, T2>(path, scale));
  return result;
}
References scale().
ScaleRect()
template<typename T1 , typename T2 > Rect< T1 > Clipper2Lib::ScaleRect (const Rect< T2 > & rect, double scale) inline
{
  Rect<T1> result;
  if constexpr (std::numeric_limits<T1>::is_integer &&
    !std::numeric_limits<T2>::is_integer)
  {
    result.left = static_cast<T1>(std::round(rect.left * scale));
    result.top = static_cast<T1>(std::round(rect.top * scale));
    result.right = static_cast<T1>(std::round(rect.right * scale));
    result.bottom = static_cast<T1>(std::round(rect.bottom * scale));
  }
  else
  {
    result.left = rect.left * scale;
    result.top = rect.top * scale;
    result.right = rect.right * scale;
    result.bottom = rect.bottom * scale;
  }
  return result;
}
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Rect< T >::left, Clipper2Lib::Rect< T >::right, scale(), and Clipper2Lib::Rect< T >::top.
SegmentsIntersect()
bool Clipper2Lib::SegmentsIntersect (const Point64 & seg1a, const Point64 & seg1b, const Point64 & seg2a, const Point64 & seg2b, bool inclusive = false) inline
{
  if (inclusive)
  {
    double res1 = CrossProduct(seg1a, seg2a, seg2b);
    double res2 = CrossProduct(seg1b, seg2a, seg2b);
    if (res1 * res2 > 0) return false;
    double res3 = CrossProduct(seg2a, seg1a, seg1b);
    double res4 = CrossProduct(seg2b, seg1a, seg1b);
    if (res3 * res4 > 0) return false;
    return (res1 || res2 || res3 || res4); // ensures not collinear
  }
  else {
    double dx1 = static_cast<double>(seg1a.x - seg1b.x);
    double dy1 = static_cast<double>(seg1a.y - seg1b.y);
    double dx2 = static_cast<double>(seg2a.x - seg2b.x);
    double dy2 = static_cast<double>(seg2a.y - seg2b.y);
    return (((dy1 * (seg2a.x - seg1a.x) - dx1 * (seg2a.y - seg1a.y)) *
      (dy1 * (seg2b.x - seg1a.x) - dx1 * (seg2b.y - seg1a.y)) < 0) &&
      ((dy2 * (seg1a.x - seg2a.x) - dx2 * (seg1a.y - seg2a.y)) *
        (dy2 * (seg1b.x - seg2a.x) - dx2 * (seg1b.y - seg2a.y)) < 0));
  }
}
References CrossProduct(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::FixSelfIntersects(), and GetIntersection().
SetDx()
void Clipper2Lib::SetDx (Active & e) inline
  {
    e.dx = GetDx(e.bot, e.top);
  }
References Clipper2Lib::Active::bot, Clipper2Lib::Active::dx, GetDx(), and Clipper2Lib::Active::top.
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), TrimHorz(), and Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL().
SetSides()
void Clipper2Lib::SetSides (OutRec & outrec, Active & start_edge, Active & end_edge) inline
  {
    outrec.front_edge = &start_edge;
    outrec.back_edge = &end_edge;
  }
References Clipper2Lib::OutRec::back_edge, and Clipper2Lib::OutRec::front_edge.
Referenced by Clipper2Lib::ClipperBase::AddLocalMinPoly(), and Clipper2Lib::ClipperBase::IntersectEdges().
Sqr()
template<typename T > double Clipper2Lib::Sqr (T val) inline
{
  return static_cast<double>(val) * static_cast<double>(val);
}
Referenced by DistanceSqr(), NearEqual(), PerpendicDistFromLineSqrd(), and RamerDouglasPeucker().
StripDuplicates() [1/2]
template<typename T > Path< T > Clipper2Lib::StripDuplicates (const Path< T > & path, bool is_closed_path) inline
{
  if (path.size() == 0) return Path<T>();
  Path<T> result;
  result.reserve(path.size());
  typename Path<T>::const_iterator path_iter = path.cbegin();
  Point<T> first_pt = *path_iter++, last_pt = first_pt;
  result.push_back(first_pt);
  for (; path_iter != path.cend(); ++path_iter)
  {
    if (*path_iter != last_pt)
    {
      last_pt = *path_iter;
      result.push_back(last_pt);
    }
  }
  if (!is_closed_path) return result;
  while (result.size() > 1 && result.back() == first_pt) result.pop_back();
  return result;
}
Referenced by Clipper2Lib::ClipperOffset::DoGroupOffset(), and StripDuplicates().
StripDuplicates() [2/2]
template<typename T > Paths< T > Clipper2Lib::StripDuplicates (const Paths< T > & paths, bool is_closed_path) inline
{
  Paths<T> result;
  result.reserve(paths.size());
  for (typename Paths<T>::const_iterator paths_citer = paths.cbegin();
    paths_citer != paths.cend(); ++paths_citer)
  {
    result.push_back(StripDuplicates(*paths_citer, is_closed_path));
  }
  return result;
}
References StripDuplicates().
StripNearEqual() [1/2]
template<typename T > Path< T > Clipper2Lib::StripNearEqual (const Path< T > & path, double max_dist_sqrd, bool is_closed_path) inline
{
  if (path.size() == 0) return Path<T>();
  Path<T> result;
  result.reserve(path.size());
  typename Path<T>::const_iterator path_iter = path.cbegin();
  Point<T> first_pt = *path_iter++, last_pt = first_pt;
  result.push_back(first_pt);
  for (; path_iter != path.cend(); ++path_iter)
  {
    if (!NearEqual(*path_iter, last_pt, max_dist_sqrd))
    {
      last_pt = *path_iter;
      result.push_back(last_pt);
    }
  }
  if (!is_closed_path) return result;
  while (result.size() > 1 &&
    NearEqual(result.back(), first_pt, max_dist_sqrd)) result.pop_back();
  return result;
}
References NearEqual().
Referenced by StripNearEqual().
StripNearEqual() [2/2]
template<typename T > Paths< T > Clipper2Lib::StripNearEqual (const Paths< T > & paths, double max_dist_sqrd, bool is_closed_path) inline
{
  Paths<T> result;
  result.reserve(paths.size());
  for (typename Paths<T>::const_iterator paths_citer = paths.cbegin();
    paths_citer != paths.cend(); ++paths_citer)
  {
    result.push_back(StripNearEqual(*paths_citer, max_dist_sqrd, is_closed_path));
  }
  return result;
}
References StripNearEqual().
SwapActives()
void Clipper2Lib::SwapActives (Active *& e1, Active *& e2) inline
  {
    Active* e = e1;
    e1 = e2;
    e2 = e;
  }
Referenced by Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
SwapFrontBackSides()
void Clipper2Lib::SwapFrontBackSides (OutRec & outrec) inline
  {
    Active* tmp = outrec.front_edge;
    outrec.front_edge = outrec.back_edge;
    outrec.back_edge = tmp;
    outrec.pts = outrec.pts->next;
  }
References Clipper2Lib::OutRec::back_edge, Clipper2Lib::OutRec::front_edge, Clipper2Lib::OutPt::next, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly().
SwapOutrecs()
void Clipper2Lib::SwapOutrecs (Active & e1, Active & e2)
  {
    OutRec* or1 = e1.outrec;
    OutRec* or2 = e2.outrec;
    if (or1 == or2)
    {
      Active* e = or1->front_edge;
      or1->front_edge = or1->back_edge;
      or1->back_edge = e;
      return;
    }
    if (or1)
    {
      if (&e1 == or1->front_edge)
        or1->front_edge = &e2;
      else
        or1->back_edge = &e2;
    }
    if (or2)
    {
      if (&e2 == or2->front_edge)
        or2->front_edge = &e1;
      else
        or2->back_edge = &e1;
    }
    e1.outrec = or2;
    e2.outrec = or1;
  }
References Clipper2Lib::OutRec::back_edge, Clipper2Lib::OutRec::front_edge, and Clipper2Lib::Active::outrec.
Referenced by Clipper2Lib::ClipperBase::IntersectEdges().
SwapSides()
void Clipper2Lib::SwapSides (OutRec & outrec) inline
  {
    Active* e2 = outrec.front_edge;
    outrec.front_edge = outrec.back_edge;
    outrec.back_edge = e2;
    outrec.pts = outrec.pts->next;
  }
References Clipper2Lib::OutRec::back_edge, Clipper2Lib::OutRec::front_edge, Clipper2Lib::OutPt::next, and Clipper2Lib::OutRec::pts.
TestJoinWithNext1()
bool Clipper2Lib::TestJoinWithNext1 (const Active & e) inline
  {
    //this is marginally quicker than TestJoinWithNext2
    //but can only be used when e.NextInAEL.currX is accurate
    return IsHotEdge(e) && !IsOpen(e) &&
      e.next_in_ael && (e.next_in_ael->curr_x == e.curr_x) &&
      IsHotEdge(*e.next_in_ael) && !IsOpen(*e.next_in_ael) &&
      (CrossProduct(e.next_in_ael->top, e.bot, e.top) == 0);
  }
References Clipper2Lib::Active::bot, CrossProduct(), Clipper2Lib::Active::curr_x, IsHotEdge(), IsOpen(), Clipper2Lib::Active::next_in_ael, and Clipper2Lib::Active::top.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), and Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL().
TestJoinWithNext2()
bool Clipper2Lib::TestJoinWithNext2 (const Active & e, const Point64 & curr_pt) inline
  {
    return IsHotEdge(e) && !IsOpen(e) &&
      e.next_in_ael && !IsOpen(*e.next_in_ael) &&
      IsHotEdge(*e.next_in_ael) && (e.next_in_ael->top.y < e.bot.y) &&
      (std::llabs(TopX(*e.next_in_ael, curr_pt.y) - curr_pt.x) < 2) &&
      (CrossProduct(e.next_in_ael->top, curr_pt, e.top) == 0);
  }
References Clipper2Lib::Active::bot, CrossProduct(), IsHotEdge(), IsOpen(), Clipper2Lib::Active::next_in_ael, Clipper2Lib::Active::top, TopX(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ProcessIntersectList().
TestJoinWithPrev1()
bool Clipper2Lib::TestJoinWithPrev1 (const Active & e) inline
  {
    //this is marginally quicker than TestJoinWithPrev2
    //but can only be used when e.PrevInAEL.currX is accurate
    return IsHotEdge(e) && !IsOpen(e) &&
      e.prev_in_ael && e.prev_in_ael->curr_x == e.curr_x &&
      IsHotEdge(*e.prev_in_ael) && !IsOpen(*e.prev_in_ael) &&
      (CrossProduct(e.prev_in_ael->top, e.bot, e.top) == 0);
  }
References Clipper2Lib::Active::bot, CrossProduct(), Clipper2Lib::Active::curr_x, IsHotEdge(), IsOpen(), Clipper2Lib::Active::prev_in_ael, and Clipper2Lib::Active::top.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::InsertLocalMinimaIntoAEL(), and Clipper2Lib::ClipperBase::UpdateEdgeIntoAEL().
TestJoinWithPrev2()
bool Clipper2Lib::TestJoinWithPrev2 (const Active & e, const Point64 & curr_pt) inline
  {
    return IsHotEdge(e) && !IsOpen(e) &&
      e.prev_in_ael && !IsOpen(*e.prev_in_ael) &&
      IsHotEdge(*e.prev_in_ael) && (e.prev_in_ael->top.y < e.bot.y) &&
      (std::llabs(TopX(*e.prev_in_ael, curr_pt.y) - curr_pt.x) < 2) &&
      (CrossProduct(e.prev_in_ael->top, curr_pt, e.top) == 0);
  }
References Clipper2Lib::Active::bot, CrossProduct(), IsHotEdge(), IsOpen(), Clipper2Lib::Active::prev_in_ael, Clipper2Lib::Active::top, TopX(), Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::ProcessIntersectList().
TopX()
int64_t Clipper2Lib::TopX (const Active & ae, const int64_t currentY) inline
  {
    if ((currentY == ae.top.y) || (ae.top.x == ae.bot.x)) return ae.top.x;
    else if (currentY == ae.bot.y) return ae.bot.x;
    else return ae.bot.x + static_cast<int64_t>(std::nearbyint(ae.dx * (currentY - ae.bot.y)));
    // nb: std::nearbyint (or std::round) substantially *improves* performance here
    // as it greatly improves the likelihood of edge adjacency in ProcessIntersectList().
  }
References Clipper2Lib::Active::bot, Clipper2Lib::Active::dx, Clipper2Lib::Active::top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::AddNewIntersectNode(), Clipper2Lib::ClipperBase::AdjustCurrXAndCopyToSEL(), Clipper2Lib::ClipperBase::DoHorizontal(), Clipper2Lib::ClipperBase::DoTopOfScanbeam(), GetHorzMaximaPair(), TestJoinWithNext2(), and TestJoinWithPrev2().
TransformPath()
template<typename T1 , typename T2 > Path< T1 > Clipper2Lib::TransformPath (const Path< T2 > & path) inline
{
  Path<T1> result;
  result.reserve(path.size());
  std::transform(path.cbegin(), path.cend(), std::back_inserter(result),
    [](const Point<T2>& pt) {return Point<T1>(pt); });
  return result;
}
TransformPaths()
template<typename T1 , typename T2 > Paths< T1 > Clipper2Lib::TransformPaths (const Paths< T2 > & paths) inline
{
  Paths<T1> result;
  std::transform(paths.cbegin(), paths.cend(), std::back_inserter(result),
    [](const Path<T2>& path) {return TransformPath<T1, T2>(path); });
  return result;
}
TranslatePath() [1/2]
Path64 Clipper2Lib::TranslatePath (const Path64 & path, int64_t dx, int64_t dy) inline
  {
    Path64 result;
    result.reserve(path.size());
    for (const Point64& pt : path)
      result.push_back(Point64(pt.x + dx, pt.y + dy));
    return result;
  }
Referenced by TranslatePaths(), and TranslatePaths().
TranslatePath() [2/2]
PathD Clipper2Lib::TranslatePath (const PathD & path, double dx, double dy) inline
  {
    PathD result;
    result.reserve(path.size());
    for (const PointD& pt : path)
      result.push_back(PointD(pt.x + dx, pt.y + dy));
    return result;
  }
TranslatePaths() [1/2]
Paths64 Clipper2Lib::TranslatePaths (const Paths64 & paths, int64_t dx, int64_t dy) inline
  {
    Paths64 result;
    result.reserve(paths.size());
    for (const Path64& path : paths)
      result.push_back(TranslatePath(path, dx, dy));
    return result;
  }
References TranslatePath().
TranslatePaths() [2/2]
PathsD Clipper2Lib::TranslatePaths (const PathsD & paths, double dx, double dy) inline
  {
    PathsD result;
    result.reserve(paths.size());
    for (const PathD& path : paths)
      result.push_back(TranslatePath(path, dx, dy));
    return result;
  }
References TranslatePath().
TranslatePoint()
PointD Clipper2Lib::TranslatePoint (const PointD & pt, double dx, double dy) inline
{
  return PointD(pt.x + dx, pt.y + dy);
}
References Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperOffset::DoSquare().
TrimCollinear() [1/2]
Path64 Clipper2Lib::TrimCollinear (const Path64 & p, bool is_open_path = false) inline
  {
    size_t len = p.size();
    if (len < 3)
    {
      if (!is_open_path || len < 2 || p[0] == p[1]) return Path64();
      else return p;
    }
    Path64 dst;
    dst.reserve(len);
    Path64::const_iterator srcIt = p.cbegin(), prevIt, stop = p.cend() - 1;
    if (!is_open_path)
    {
      while (srcIt != stop && !CrossProduct(*stop, *srcIt, *(srcIt + 1)))
        ++srcIt;
      while (srcIt != stop && !CrossProduct(*(stop - 1), *stop, *srcIt))
        --stop;
      if (srcIt == stop) return Path64();
    }
    prevIt = srcIt++;
    dst.push_back(*prevIt);
    for (; srcIt != stop; ++srcIt)
    {
      if (CrossProduct(*prevIt, *srcIt, *(srcIt + 1)))
      {
        prevIt = srcIt;
        dst.push_back(*prevIt);
      }
    }
    if (is_open_path)
      dst.push_back(*srcIt);
    else if (CrossProduct(*prevIt, *stop, dst[0]))
      dst.push_back(*stop);
    else
    {
      while (dst.size() > 2 &&
        !CrossProduct(dst[dst.size() - 1], dst[dst.size() - 2], dst[0]))
          dst.pop_back();
      if (dst.size() < 3) return Path64();
    }
    return dst;
  }
References CrossProduct().
Referenced by TrimCollinear().
TrimCollinear() [2/2]
PathD Clipper2Lib::TrimCollinear (const PathD & path, int precision, bool is_open_path = false) inline
  {
    CheckPrecision(precision);
    const double scale = std::pow(10, precision);
    Path64 p = ScalePath<int64_t, double>(path, scale);
    p = TrimCollinear(p, is_open_path);
    return ScalePath<double, int64_t>(p, 1/scale);
  }
References CheckPrecision(), scale(), and TrimCollinear().
TrimHorz()
void Clipper2Lib::TrimHorz (Active & horzEdge, bool preserveCollinear) inline
  {
    bool wasTrimmed = false;
    Point64 pt = NextVertex(horzEdge)->pt;
    while (pt.y == horzEdge.top.y)
    {
      //always trim 180 deg. spikes (in closed paths)
      //but otherwise break if preserveCollinear = true
      if (preserveCollinear &&
        ((pt.x < horzEdge.top.x) != (horzEdge.bot.x < horzEdge.top.x)))
          break;
      horzEdge.vertex_top = NextVertex(horzEdge);
      horzEdge.top = pt;
      wasTrimmed = true;
      if (IsMaxima(horzEdge)) break;
      pt = NextVertex(horzEdge)->pt;
    }
    if (wasTrimmed) SetDx(horzEdge); // +/-infinity
  }
References Clipper2Lib::Active::bot, IsMaxima(), NextVertex(), Clipper2Lib::Vertex::pt, SetDx(), Clipper2Lib::Active::top, Clipper2Lib::Active::vertex_top, Clipper2Lib::Point< T >::x, and Clipper2Lib::Point< T >::y.
Referenced by Clipper2Lib::ClipperBase::DoHorizontal().
UncoupleOutRec()
void Clipper2Lib::UncoupleOutRec (Active ae) inline
  {
    OutRec* outrec = ae.outrec;
    if (!outrec) return;
    outrec->front_edge->outrec = nullptr;
    outrec->back_edge->outrec = nullptr;
    outrec->front_edge = nullptr;
    outrec->back_edge = nullptr;
  }
References Clipper2Lib::OutRec::back_edge, Clipper2Lib::OutRec::front_edge, and Clipper2Lib::Active::outrec.
Referenced by Clipper2Lib::ClipperBase::AddLocalMaxPoly().
Union() [1/4]
Paths64 Clipper2Lib::Union (const Paths64 & subjects, const Paths64 & clips, FillRule fillrule) inline
  {
    return BooleanOp(ClipType::Union, fillrule, subjects, clips);
  }
References BooleanOp(), and Union.
Union() [2/4]
Paths64 Clipper2Lib::Union (const Paths64 & subjects, FillRule fillrule) inline
  {
    Paths64 result;
    Clipper64 clipper;
    clipper.AddSubject(subjects);
    clipper.Execute(ClipType::Union, fillrule, result);
    return result;
  }
References Clipper2Lib::Clipper64::AddSubject(), Clipper2Lib::Clipper64::Execute(), and Union.
Union() [3/4]
PathsD Clipper2Lib::Union (const PathsD & subjects, const PathsD & clips, FillRule fillrule, int decimal_prec = 2) inline
  {
    return BooleanOp(ClipType::Union, fillrule, subjects, clips, decimal_prec);
  }
References BooleanOp(), and Union.
Union() [4/4]
PathsD Clipper2Lib::Union (const PathsD & subjects, FillRule fillrule, int decimal_prec = 2) inline
  {
    CheckPrecision(decimal_prec);
    PathsD result;
    ClipperD clipper(decimal_prec);
    clipper.AddSubject(subjects);
    clipper.Execute(ClipType::Union, fillrule, result);
    return result;
  }
References Clipper2Lib::ClipperD::AddSubject(), CheckPrecision(), Clipper2Lib::ClipperD::Execute(), and Union.
UpdateOutrecOwner()
void Clipper2Lib::UpdateOutrecOwner (OutRec * outrec) inline
  {
    OutPt* opCurr = outrec->pts;
    for (; ; )
    {
      opCurr->outrec = outrec;
      opCurr = opCurr->next;
      if (opCurr == outrec->pts) return;
    }
  }
References Clipper2Lib::OutPt::next, Clipper2Lib::OutPt::outrec, and Clipper2Lib::OutRec::pts.
Referenced by Clipper2Lib::ClipperBase::CompleteSplit().
ValueBetween()
bool Clipper2Lib::ValueBetween (int64_t val, int64_t end1, int64_t end2) inline
  {
    //NB accommodates axis aligned between where end1 == end2
    return ((val != end1) == (val != end2)) &&
      ((val > end1) == (val < end2));
  }
Referenced by Clipper2Lib::ClipperBase::ConvertHorzTrialsToJoins(), and PointBetween().
ValueEqualOrBetween()
bool Clipper2Lib::ValueEqualOrBetween (int64_t val, int64_t end1, int64_t end2) inline
  {
    return (val == end1) || (val == end2) || ((val > end1) == (val < end2));
  }
Referenced by PointEqualOrBetween().
Version()
EXTERN_DLL_EXPORT const char * Clipper2Lib::Version ()
{
  return CLIPPER2_VERSION;
}
References CLIPPER2_VERSION.
Xor() [1/2]
Paths64 Clipper2Lib::Xor (const Paths64 & subjects, const Paths64 & clips, FillRule fillrule) inline
  {
    return BooleanOp(ClipType::Xor, fillrule, subjects, clips);
  }
References BooleanOp(), and Xor.
Xor() [2/2]
PathsD Clipper2Lib::Xor (const PathsD & subjects, const PathsD & clips, FillRule fillrule, int decimal_prec = 2) inline
  {
    return BooleanOp(ClipType::Xor, fillrule, subjects, clips, decimal_prec);
  }
References BooleanOp(), and Xor.
Variable Documentation
default_arc_tolerance
const double Clipper2Lib::default_arc_tolerance = 0.25
Referenced by Clipper2Lib::ClipperOffset::DoGroupOffset(), and Clipper2Lib::ClipperOffset::Execute().
floating_point_tolerance
const double Clipper2Lib::floating_point_tolerance = 1e-12
Referenced by Clipper2Lib::ClipperOffset::DoGroupOffset().
FloatingPointTolerance
const double Clipper2Lib::FloatingPointTolerance = 1.0e-12 static
Referenced by GetIntersectPoint().
invalid_rect
const Rect64 Clipper2Lib::invalid_rect static
Initial value:
= Rect64(
    std::numeric_limits<int64_t>::max(),
    std::numeric_limits<int64_t>::max(),
    -std::numeric_limits<int64_t>::max(),
    -std::numeric_limits<int64_t>::max()
  )
Referenced by GetBounds().
MAX_COORD
int64_t const Clipper2Lib::MAX_COORD = LLONG_MAX / 2 static
MaxInvalidRect64
const Rect64 Clipper2Lib::MaxInvalidRect64 static
Initial value:
= Rect64(
    (std::numeric_limits<int64_t>::max)(),
    (std::numeric_limits<int64_t>::max)(),
    (std::numeric_limits<int64_t>::lowest)(),
    (std::numeric_limits<int64_t>::lowest)())
Referenced by Bounds(), and Bounds().
MaxInvalidRectD
const RectD Clipper2Lib::MaxInvalidRectD static
Initial value:
= RectD(
      (std::numeric_limits<double>::max)(),
      (std::numeric_limits<double>::max)(),
      (std::numeric_limits<double>::lowest)(),
      (std::numeric_limits<double>::lowest)())
Referenced by Bounds(), and Bounds().
PI
double const Clipper2Lib::PI = 3.141592653589793238 static
Referenced by Clipper2Lib::ClipperOffset::DoGroupOffset(), Ellipse(), and Clipper2Lib::ClipperOffset::OffsetOpenPath().
precision_error
const char* Clipper2Lib::precision_error static
Initial value:
=
    "Precision exceeds the permitted range"
Referenced by CheckPrecision().