OrcaSlicer: src/qhull/src/qhulltest/Qhull_test.cpp File Reference
Qhull_test.cpp File Reference
#include <iostream>
#include "qhulltest/RoadTest.h"
#include "libqhullcpp/Qhull.h"
#include "libqhullcpp/QhullError.h"
#include "libqhullcpp/RboxPoints.h"
#include "libqhullcpp/QhullFacetList.h"
#include "moc/Qhull_test.moc"
Classes
class orgQhull::Qhull_test
Test C++ interface to Qhull See eg/q_test for tests of Qhull commands.
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
void orgQhull::add_Qhull_test ()
void qh_exit (int exitcode)
void qh_fprintf_stderr (int msgcode, const char *fmt,...)
void qh_free (void *mem)
void * qh_malloc (size_t size)
Function Documentation
qh_exit()
void qh_exit (int exitcode)
{
    cout << "FAIL!  : Qhull called qh_exit().  Qhull's error handling not available.\n.. See the corresponding Qhull:qhull_message or setErrorStream().\n";
    exit(exitcode);
}
Referenced by qh_errexit(), qh_errexit(), qh_errexit(), qh_errexit(), qh_fprintf(), qh_init_qhull_command(), qh_init_qhull_command(), qh_initflags(), qh_initflags(), qh_initqhull_start(), qh_initstatistics(), qh_initstatistics(), qh_lib_check(), qh_memcheck(), qh_memcheck(), qh_meminit(), and qh_meminit().
qh_fprintf_stderr()
void qh_fprintf_stderr (int msgcode, const char * fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    if(msgcode)
        fprintf(stderr, "QH%.4d ", msgcode);
    vfprintf(stderr, fmt, args);
    va_end(args);
} /* fprintf_stderr */
Referenced by main(), main(), qh_fprintf(), qh_fprintf(), qh_fprintf_rbox(), qh_fprintf_rbox(), qh_initstatistics(), qh_lib_check(), qh_memcheck(), and qh_memcheck().
qh_free()
void qh_free (void * mem)
{
    free(mem);
}
Referenced by main(), qh_freebuffers(), qh_freebuffers(), qh_freeqhull(), qh_freestatistics(), qh_initstatistics(), qh_memfree(), qh_memfree(), qh_memfreeshort(), qh_memfreeshort(), qh_new_qhull(), qh_new_qhull(), qh_projectinput(), qh_projectinput(), qh_rboxpoints(), qh_rboxpoints(), qh_readpoints(), qh_readpoints(), qh_sethalfspace_all(), and qh_sethalfspace_all().
qh_malloc()
void * qh_malloc (size_t size)
{
    return malloc(size);
}
References size.
Referenced by orgQhull::Qhull::initializeFeasiblePoint(), main(), qh_copypoints(), qh_copypoints(), qh_initqhull_start(), qh_initstatistics(), qh_joggleinput(), qh_joggleinput(), qh_memalloc(), qh_memalloc(), qh_memsetup(), qh_memsetup(), qh_projectinput(), qh_projectinput(), qh_rboxpoints(), qh_rboxpoints(), qh_readfeasible(), qh_readfeasible(), qh_readpoints(), qh_readpoints(), qh_setfeasible(), qh_setfeasible(), qh_sethalfspace_all(), qh_sethalfspace_all(), setupMemory(), and setupMemory().