OrcaSlicer: Slic3r::GUI::GCodeViewer::Layers Class Reference
Slic3r::GUI::GCodeViewer::Layers Class Reference
Classes
struct Endpoints
Public Member Functions
void append (double z, Endpoints endpoints)
void reset ()
size_t size () const
bool empty () const
const std::vector< double > & get_zs () const
const std::vector< Endpoints > & get_endpoints () const
std::vector< Endpoints > & get_endpoints ()
double get_z_at (unsigned int id) const
Endpoints get_endpoints_at (unsigned int id) const
int get_l_at (double z) const
bool operator!= (const Layers &other) const
Private Attributes
std::vector< double > m_zs
std::vector< Endpoints > m_endpoints
Detailed Description
Member Function Documentation
append()
void Slic3r::GUI::GCodeViewer::Layers::append (double z, Endpoints endpoints) inline
{
            m_zs.emplace_back(z);
            m_endpoints.emplace_back(endpoints);
        }
References m_endpoints, and m_zs.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
empty()
bool Slic3r::GUI::GCodeViewer::Layers::empty () const inline
{ return m_zs.empty(); }
References m_zs.
Referenced by Slic3r::GUI::GCodeViewer::load(), and Slic3r::GUI::GCodeViewer::load_toolpaths().
get_endpoints() [1/2]
std::vector< Endpoints > & Slic3r::GUI::GCodeViewer::Layers::get_endpoints () inline
{ return m_endpoints; }
References m_endpoints.
get_endpoints() [2/2]
const std::vector< Endpoints > & Slic3r::GUI::GCodeViewer::Layers::get_endpoints () const inline
{ return m_endpoints; }
References m_endpoints.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
get_endpoints_at()
Endpoints Slic3r::GUI::GCodeViewer::Layers::get_endpoints_at (unsigned int id) const inline
{ return (id < m_endpoints.size()) ? m_endpoints[id] : Endpoints(); }
References m_endpoints.
Referenced by Slic3r::GUI::GCodeViewer::refresh_render_paths().
get_l_at()
int Slic3r::GUI::GCodeViewer::Layers::get_l_at (double z) const inline
        {
            auto iter = std::upper_bound(m_zs.begin(), m_zs.end(), z);
            return std::distance(m_zs.begin(), iter);
        }
References std::distance(), and m_zs.
Referenced by Slic3r::GUI::GCodeViewer::load().
get_z_at()
double Slic3r::GUI::GCodeViewer::Layers::get_z_at (unsigned int id) const inline
{ return (id < m_zs.size()) ? m_zs[id] : 0.0; }
References m_zs.
get_zs()
const std::vector< double > & Slic3r::GUI::GCodeViewer::Layers::get_zs () const inline
{ return m_zs; }
References m_zs.
Referenced by Slic3r::GUI::GCodeViewer::get_layers_zs(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and Slic3r::GUI::GCodeViewer::render_legend().
operator!=()
bool Slic3r::GUI::GCodeViewer::Layers::operator!= (const Layers & other) const inline
{
            if (m_zs != other.m_zs)
                return true;
            if (m_endpoints != other.m_endpoints)
                return true;
            return false;
        }
References m_endpoints, and m_zs.
reset()
void Slic3r::GUI::GCodeViewer::Layers::reset () inline
                     {
            m_zs = std::vector<double>();
            m_endpoints = std::vector<Endpoints>();
        }
References m_endpoints, and m_zs.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths(), and Slic3r::GUI::GCodeViewer::reset().
size()
size_t Slic3r::GUI::GCodeViewer::Layers::size () const inline
{ return m_zs.size(); }
References m_zs.
Member Data Documentation
m_endpoints
std::vector<Endpoints> Slic3r::GUI::GCodeViewer::Layers::m_endpoints private
Referenced by append(), get_endpoints(), get_endpoints(), get_endpoints_at(), operator!=(), and reset().
m_zs
std::vector<double> Slic3r::GUI::GCodeViewer::Layers::m_zs private
Referenced by append(), empty(), get_l_at(), get_z_at(), get_zs(), operator!=(), reset(), and size().
The documentation for this class was generated from the following file:
src/slic3r/GUI/GCodeViewer.hpp