OrcaSlicer: orgQhull::Qhull_test Class Reference
orgQhull::Qhull_test Class Reference
Test C++ interface to Qhull See eg/q_test for tests of Qhull commands.
Public Member Functions
Helper
void recordFailedTest ()
Static Public Member Functions
Class functions
static void deleteTests ()
static int runTests (QStringList arguments)
Static Protected Attributes
Class globals
static QList< RoadTest * > s_testcases
static int s_test_count = 0
! List of testcases to execute. Initialized via add_...()
static int s_test_fail = 0
! Total number of tests executed
static QStringList s_failed_tests
! Number of failed tests
Private Slots
Test slots
void cleanup ()
void t_construct ()
void t_attribute ()
void t_message ()
No QhullMessage for errors outside of qhull.
void t_getSet ()
void t_getQh ()
void t_getValue ()
void t_foreach ()
void t_modify ()
Detailed Description
Test C++ interface to Qhull See eg/q_test for tests of Qhull commands.
Member Function Documentation
cleanup
void orgQhull::Qhull_test::cleanup () private slot
{
    RoadTest::cleanup();
}
References orgQhull::RoadTest::cleanup().
deleteTests()
void orgQhull::RoadTest::deleteTests () static inherited
{
    foreach(RoadTest *testcase, s_testcases){
        delete testcase;
    }
    s_failed_tests.clear();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
recordFailedTest()
void orgQhull::RoadTest::recordFailedTest () inherited
{
    s_test_fail++;
    QString className= metaObject()->className();
    s_failed_tests << className + "::" + QTest::currentTestFunction();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_test_fail.
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
runTests()
int orgQhull::RoadTest::runTests (QStringList arguments) static inherited
{
    int result= 0; // assume success
    foreach(RoadTest *testcase, s_testcases){
        try{
            result += QTest::qExec(testcase, arguments);
        }catch(const std::exception &e){
            cout << "FAIL!  : Threw error ";
            cout << e.what() << endl;
    s_test_count++;
            testcase->recordFailedTest();
            // Qt 4.5.2 OK.  In Qt 4.3.3, qtestcase did not clear currentTestObject
        }
    }
    if(s_test_fail){
        cout << "Failed " << s_test_fail << " of " << s_test_count << " tests.\n";
        cout << s_failed_tests.join("\n").toLocal8Bit().constData() << std::endl;
    }else{
        cout << "Passed " << s_test_count << " tests.\n";
    }
    return result;
}//runTests
References orgQhull::RoadTest::recordFailedTest(), orgQhull::RoadTest::s_failed_tests, orgQhull::RoadTest::s_test_count, orgQhull::RoadTest::s_test_fail, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
t_attribute
void orgQhull::Qhull_test::t_attribute () private slot
{
    RboxPoints rcube("c");
    {
        double normals[] = {
            0,  -1, -0.5,
           -1,   0, -0.5,
            1,   0, -0.5,
            0,   1, -0.5
        };
        Qhull q;
        Coordinates feasible;
        feasible << 0.0 << 0.0;
        q.setFeasiblePoint(feasible);
        Coordinates c(std::vector<double>(2, 0.0));
        QVERIFY(q.feasiblePoint()==c);
        q.setOutputStream(&cout);
        q.runQhull("normals of square", 3, 4, normals, "H"); // halfspace intersect
        QVERIFY(q.feasiblePoint()==c); // from qh.feasible_point after runQhull()
        QCOMPARE(q.facetList().count(), 4); // Vertices of square
        cout << "Expecting summary of halfspace intersection\n";
        q.outputQhull();
        q.qh()->disableOutputStream();  // Same as q.disableOutputStream()
        cout << "Expecting no output from qh_fprintf() in Qhull.cpp\n";
        q.outputQhull();
    }
}//t_attribute
References orgQhull::QhullFacetList::count(), orgQhull::QhullQh::disableOutputStream(), orgQhull::Qhull::facetList(), orgQhull::Qhull::feasiblePoint(), orgQhull::Qhull::outputQhull(), orgQhull::Qhull::qh(), orgQhull::Qhull::runQhull(), orgQhull::Qhull::setFeasiblePoint(), and orgQhull::Qhull::setOutputStream().
t_construct
void orgQhull::Qhull_test::t_construct () private slot
{
    {
        Qhull q;
        QCOMPARE(q.dimension(),0);
        QVERIFY(q.qh()!=0);
        QCOMPARE(QString(q.qhullCommand()),QString(""));
        QCOMPARE(QString(q.rboxCommand()),QString(""));
        try{
            QCOMPARE(q.area(),0.0);
            QFAIL("area() did not fail.");
        }catch (const std::exception &e) {
            cout << "INFO   : Caught " << e.what();
        }
    }
    {
        RboxPoints rbox("10000");
        Qhull q(rbox, "QR0"); // Random points in a randomly rotated cube.
        QCOMPARE(q.dimension(),3);
        QVERIFY(q.volume() < 1.0);
        QVERIFY(q.volume() > 0.99);
    }
    {
        double points[] = {
            0, 0,
            1, 0,
            1, 1
        };
        Qhull q("triangle", 2, 3, points, "");
        QCOMPARE(q.dimension(),2);
        QCOMPARE(q.facetCount(),3);
        QCOMPARE(q.vertexCount(),3);
        QCOMPARE(q.dimension(),2);
        QCOMPARE(q.area(), 2.0+sqrt(2.0)); // length of boundary
        QCOMPARE(q.volume(), 0.5);        // the 2-d area
    }
}//t_construct
References orgQhull::Qhull::area(), orgQhull::Qhull::dimension(), orgQhull::Qhull::facetCount(), orgQhull::Qhull::qh(), orgQhull::Qhull::qhullCommand(), rbox, orgQhull::Qhull::rboxCommand(), sqrt(), orgQhull::Qhull::vertexCount(), and orgQhull::Qhull::volume().
t_foreach
void orgQhull::Qhull_test::t_foreach () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q;
        QCOMPARE(q.beginFacet(),q.endFacet());
        QCOMPARE(q.beginVertex(),q.endVertex());
        q.runQhull(rcube, "");
        QCOMPARE(q.facetList().count(), 6);
        // defineVertexNeighborFacets() tested in QhullVertex_test::t_io()
        QhullFacetList facets(q.beginFacet(), q.endFacet());
        QCOMPARE(facets.count(), 6);
        QCOMPARE(q.firstFacet(), q.beginFacet());
        QhullVertexList vertices(q.beginVertex(), q.endVertex());
        QCOMPARE(vertices.count(), 8);
        QCOMPARE(q.firstVertex(), q.beginVertex());
        QhullPoints ps= q.points();
        QCOMPARE(ps.count(), 8);
        QhullPointSet ps2= q.otherPoints();
        QCOMPARE(ps2.count(), 0);
        // ps2= q.otherPoints(); //disabled, would not copy the points
        QCOMPARE(q.facetCount(), 6);
        QCOMPARE(q.vertexCount(), 8);
        coordT *c= q.pointCoordinateBegin(); // of q.points()
        QVERIFY(*c==0.5 || *c==-0.5);
        coordT *c3= q.pointCoordinateEnd();
        QVERIFY(c3[-1]==0.5 || c3[-1]==-0.5);
        QCOMPARE(c3-c, 8*3);
        QCOMPARE(q.vertexList().count(), 8);
    }
}//t_foreach
References orgQhull::Qhull::beginFacet(), orgQhull::Qhull::beginVertex(), coordT, orgQhull::QhullFacetList::count(), orgQhull::QhullLinkedList< T >::count(), orgQhull::QhullPoints::count(), orgQhull::QhullSet< T >::count(), orgQhull::Qhull::endFacet(), orgQhull::Qhull::endVertex(), orgQhull::Qhull::facetCount(), orgQhull::Qhull::facetList(), orgQhull::Qhull::firstFacet(), orgQhull::Qhull::firstVertex(), orgQhull::Qhull::otherPoints(), orgQhull::Qhull::pointCoordinateBegin(), orgQhull::Qhull::pointCoordinateEnd(), orgQhull::Qhull::points(), orgQhull::Qhull::runQhull(), orgQhull::Qhull::vertexCount(), and orgQhull::Qhull::vertexList().
t_getQh
void orgQhull::Qhull_test::t_getQh () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q;
        q.runQhull(rcube, "s");
        QCOMPARE(QString(q.qhullCommand()), QString("qhull s"));
        QCOMPARE(QString(q.rboxCommand()), QString("rbox \"c\""));
        QCOMPARE(q.facetCount(), 6);
        QCOMPARE(q.vertexCount(), 8);
        // Sample fields from Qhull's qhT [libqhull.h]
        QCOMPARE(q.qh()->ALLpoints, 0u);
        QCOMPARE(q.qh()->GOODpoint, 0);
        QCOMPARE(q.qh()->IStracing, 0);
        QCOMPARE(q.qh()->MAXcoplanar+1.0, 1.0); // fuzzy compare
        QCOMPARE(q.qh()->MERGING, 1u);
        QCOMPARE(q.qh()->input_dim, 3);
        QCOMPARE(QString(q.qh()->qhull_options).left(8), QString("  run-id"));
        QCOMPARE(q.qh()->num_facets, 6);
        QCOMPARE(q.qh()->hasTriangulation, 0u);
        QCOMPARE(q.qh()->max_outside - q.qh()->min_vertex + 1.0, 1.0); // fuzzy compare
        QCOMPARE(*q.qh()->gm_matrix+1.0, 1.0); // fuzzy compare
    }
}//t_getQh
References qhT::ALLpoints, orgQhull::Qhull::facetCount(), qhT::gm_matrix, qhT::GOODpoint, qhT::hasTriangulation, qhT::input_dim, qhT::IStracing, qhT::max_outside, qhT::MAXcoplanar, qhT::MERGING, qhT::min_vertex, qhT::num_facets, orgQhull::Qhull::qh(), qhT::qhull_options, orgQhull::Qhull::qhullCommand(), orgQhull::Qhull::rboxCommand(), orgQhull::Qhull::runQhull(), and orgQhull::Qhull::vertexCount().
t_getSet
void orgQhull::Qhull_test::t_getSet () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q;
        QVERIFY(!q.initialized());
        q.runQhull(rcube, "s");
        QVERIFY(q.initialized());
        QCOMPARE(q.dimension(), 3);
        QhullPoint p= q.origin();
        QCOMPARE(p.dimension(), 3);
        QCOMPARE(p[0]+p[1]+p[2], 0.0);
        q.setErrorStream(&cout);
        q.outputQhull();
    }
    {
        Qhull q;
        q.runQhull(rcube, "");
        q.setOutputStream(&cout);
        q.outputQhull();
    }
}//t_getSet
References orgQhull::Qhull::dimension(), orgQhull::QhullPoint::dimension(), orgQhull::Qhull::initialized(), orgQhull::Qhull::origin(), orgQhull::Qhull::outputQhull(), orgQhull::Qhull::runQhull(), orgQhull::Qhull::setErrorStream(), and orgQhull::Qhull::setOutputStream().
t_getValue
void orgQhull::Qhull_test::t_getValue () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q;
        q.runQhull(rcube, "");
        QCOMPARE(q.area(), 6.0);
        QCOMPARE(q.volume(), 1.0);
    }
}//t_getValue
References orgQhull::Qhull::area(), orgQhull::Qhull::runQhull(), and orgQhull::Qhull::volume().
t_message
void orgQhull::Qhull_test::t_message () private slot
No QhullMessage for errors outside of qhull.
{
    RboxPoints rcube("c");
    {
        Qhull q;
        QCOMPARE(q.qhullMessage(), string(""));
        QCOMPARE(q.qhullStatus(), qh_ERRnone);
        QVERIFY(!q.hasQhullMessage());
        try{
            q.runQhull(rcube, "Fd");
            QFAIL("runQhull Fd did not fail.");
        }catch (const std::exception &e) {
            const char *s= e.what();
            cout << "INFO   : Caught " << s;
            QCOMPARE(QString::fromStdString(s).left(6), QString("QH6029"));
            // FIXUP QH11025 -- review decision to clearQhullMessage at QhullError()            // Cleared when copied to QhullError
            QVERIFY(!q.hasQhullMessage());
            // QCOMPARE(q.qhullMessage(), QString::fromStdString(s).remove(0, 7));
            // QCOMPARE(q.qhullStatus(), 6029);
            q.clearQhullMessage();
            QVERIFY(!q.hasQhullMessage());
        }
        q.appendQhullMessage("Append 1");
        QVERIFY(q.hasQhullMessage());
        QCOMPARE(QString::fromStdString(q.qhullMessage()), QString("Append 1"));
        q.appendQhullMessage("\nAppend 2\n");
        QCOMPARE(QString::fromStdString(q.qhullMessage()), QString("Append 1\nAppend 2\n"));
        q.clearQhullMessage();
        QVERIFY(!q.hasQhullMessage());
        QCOMPARE(QString::fromStdString(q.qhullMessage()), QString(""));
    }
    {
        cout << "INFO   : Error stream without output stream\n";
        Qhull q;
        q.setErrorStream(&cout);
        q.setOutputStream(0);
        try{
            q.runQhull(rcube, "Fd");
            QFAIL("runQhull Fd did not fail.");
        }catch (const QhullError &e) {
            cout << "INFO   : Caught " << e;
            QCOMPARE(e.errorCode(), 6029);
        }
        //FIXUP QH11025 Qhullmessage cleared when QhullError thrown.  Switched to e
        //QVERIFY(q.hasQhullMessage());
        //QCOMPARE(QString::fromStdString(q.qhullMessage()).left(6), QString("QH6029"));
        q.clearQhullMessage();
        QVERIFY(!q.hasQhullMessage());
    }
    {
        cout << "INFO   : Error output sent to output stream without error stream\n";
        Qhull q;
        q.setErrorStream(0);
        q.setOutputStream(&cout);
        try{
            q.runQhull(rcube, "Tz H0");
            QFAIL("runQhull TZ did not fail.");
        }catch (const std::exception &e) {
            const char *s= e.what();
            cout << "INFO   : Caught " << s;
            QCOMPARE(QString::fromLatin1(s).left(6), QString("QH6023"));
        }
        //FIXUP QH11025 Qhullmessage cleared when QhullError thrown.  Switched to e
        //QVERIFY(q.hasQhullMessage());
        //QCOMPARE(QString::fromStdString(q.qhullMessage()).left(17), QString("qhull: no message"));
        //QCOMPARE(q.qhullStatus(), 6023);
        q.clearQhullMessage();
        QVERIFY(!q.hasQhullMessage());
    }
    {
        cout << "INFO   : No error stream or output stream\n";
        Qhull q;
        q.setErrorStream(0);
        q.setOutputStream(0);
        try{
            q.runQhull(rcube, "Fd");
            QFAIL("outputQhull did not fail.");
        }catch (const std::exception &e) {
            const char *s= e.what();
            cout << "INFO   : Caught " << s;
            QCOMPARE(QString::fromLatin1(s).left(6), QString("QH6029"));
        }
        //FIXUP QH11025 Qhullmessage cleared when QhullError thrown.  Switched to e
        //QVERIFY(q.hasQhullMessage());
        //QCOMPARE(QString::fromStdString(q.qhullMessage()).left(9), QString("qhull err"));
        //QCOMPARE(q.qhullStatus(), 6029);
        q.clearQhullMessage();
        QVERIFY(!q.hasQhullMessage());
    }
}//t_message
References orgQhull::Qhull::appendQhullMessage(), orgQhull::Qhull::clearQhullMessage(), orgQhull::Qhull::hasQhullMessage(), qh_ERRnone, orgQhull::Qhull::qhullMessage(), orgQhull::Qhull::qhullStatus(), orgQhull::Qhull::runQhull(), orgQhull::Qhull::setErrorStream(), and orgQhull::Qhull::setOutputStream().
t_modify
void orgQhull::Qhull_test::t_modify () private slot
{
    //addPoint() tested in t_foreach
    RboxPoints diamond("d");
    Qhull q(diamond, "o");
    q.setOutputStream(&cout);
    cout << "Expecting vertexList and facetList of a 3-d diamond.\n";
    q.outputQhull();
    cout << "Expecting normals of a 3-d diamond.\n";
    q.outputQhull("n");
    // runQhull tested in t_attribute(), t_message(), etc.
}//t_modify
References orgQhull::Qhull::outputQhull(), and orgQhull::Qhull::setOutputStream().
Member Data Documentation
s_failed_tests
QStringList orgQhull::RoadTest::s_failed_tests static protected inherited
! Number of failed tests
Referenced by orgQhull::RoadTest::deleteTests(), orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_test_count
int orgQhull::RoadTest::s_test_count = 0 static protected inherited
! List of testcases to execute. Initialized via add_...()
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
s_test_fail
int orgQhull::RoadTest::s_test_fail = 0 static protected inherited
! Total number of tests executed
Referenced by orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_testcases
QList< RoadTest * > orgQhull::RoadTest::s_testcases static protected inherited
Referenced by orgQhull::RoadTest::RoadTest(), orgQhull::RoadTest::deleteTests(), and orgQhull::RoadTest::runTests().
The documentation for this class was generated from the following file:
src/qhull/src/qhulltest/Qhull_test.cpp