OrcaSlicer: Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper Class Reference
Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
ObjectClipper (CommonGizmosDataPool *cgdp)
CommonGizmosDataID get_dependencies () const override
void set_position (double pos, bool keep_normal)
double get_position () const
ClippingPlane * get_clipping_plane () const
void render_cut () const
void set_range_and_pos (const Vec3d &cpl_normal, double cpl_offset, double pos)
bool is_projection_inside_cut (const Vec3d &point_in) const
bool has_valid_contour () const
void update ()
void release ()
bool is_valid () const
Protected Member Functions
void on_update () override
void on_release () override
CommonGizmosDataPool * get_pool () const
Private Attributes
std::vector< const TriangleMesh * > m_old_meshes
std::vector< std::unique_ptr< MeshClipper > > m_clippers
std::unique_ptr< ClippingPlane > m_clp
double m_clp_ratio = 0.
double m_active_inst_bb_radius = 0.
bool m_is_valid = false
CommonGizmosDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
ObjectClipper()
Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::ObjectClipper (CommonGizmosDataPool * cgdp) inline explicit
        : CommonGizmosDataBase(cgdp) {}
Member Function Documentation
get_clipping_plane()
ClippingPlane * Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane () const inline
{ return m_clp.get(); }
References m_clp.
Referenced by Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoText::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::GLGizmoAdvancedCut::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoText::update_raycast_cache(), and Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache().
get_dependencies()
CommonGizmosDataID Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_dependencies () const inline override virtual
Reimplemented from Slic3r::GUI::CommonGizmosDataBase.
{ return CommonGizmosDataID::SelectionInfo; }
References Slic3r::GUI::SelectionInfo.
get_pool()
CommonGizmosDataPool * Slic3r::GUI::CommonGizmosDataBase::get_pool () const inline protected inherited
{ return m_common; }
References Slic3r::GUI::CommonGizmosDataBase::m_common.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_release(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), set_position(), and set_range_and_pos().
get_position()
double Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position () const inline
{ return m_clp_ratio; }
References m_clp_ratio.
Referenced by Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoText::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), and Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh().
has_valid_contour()
bool Slic3r::GUI::ObjectClipper::has_valid_contour () const
{
    return m_clp_ratio != 0. && std::any_of(m_clippers.begin(), m_clippers.end(), [](const auto &cl) {
        return cl->has_valid_contour();
    });
}
References m_clippers, and m_clp_ratio.
is_projection_inside_cut()
bool Slic3r::GUI::ObjectClipper::is_projection_inside_cut (const Vec3d & point_in) const
{
    return m_clp_ratio != 0. && std::any_of(m_clippers.begin(), m_clippers.end(), [point](const auto &cl) {
        return cl->is_projection_inside_cut(point);
    });
}
References m_clippers, and m_clp_ratio.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::is_outside_of_cut_contour(), and Slic3r::GUI::GLGizmoAdvancedCut::unproject_on_cut_plane().
is_valid()
bool Slic3r::GUI::CommonGizmosDataBase::is_valid () const inline inherited
{ return m_is_valid; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid.
Referenced by Slic3r::GUI::CommonGizmosDataPool::hollowed_mesh(), Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
on_release()
void Slic3r::GUI::ObjectClipper::on_release () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    m_clippers.clear();
    m_old_meshes.clear();
    m_clp.reset();
    m_clp_ratio = 0.;
}
References m_clippers, m_clp, m_clp_ratio, and m_old_meshes.
on_update()
void Slic3r::GUI::ObjectClipper::on_update () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    const ModelObject* mo = get_pool()->selection_info()->model_object();
    if (! mo)
        return;
    // which mesh should be cut?
    std::vector<const TriangleMesh*> meshes;
    bool has_hollowed = get_pool()->hollowed_mesh() && get_pool()->hollowed_mesh()->get_hollowed_mesh();
    if (has_hollowed)
        meshes.push_back(get_pool()->hollowed_mesh()->get_hollowed_mesh());
    if (meshes.empty())
        for (const ModelVolume* mv : mo->volumes)
            meshes.push_back(&mv->mesh());
    if (meshes != m_old_meshes) {
        m_clippers.clear();
        for (const TriangleMesh* mesh : meshes) {
            m_clippers.emplace_back(new MeshClipper);
            m_clippers.back()->set_mesh(*mesh);
        }
        m_old_meshes = meshes;
        if (has_hollowed)
            m_clippers.front()->set_negative_mesh(*get_pool()->hollowed_mesh()->get_hollowed_interior());
        m_active_inst_bb_radius =
            mo->instance_bounding_box(get_pool()->selection_info()->get_active_instance()).radius();
    }
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::get_hollowed_interior(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::get_hollowed_mesh(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), Slic3r::GUI::CommonGizmosDataPool::hollowed_mesh(), Slic3r::ModelObject::instance_bounding_box(), m_active_inst_bb_radius, m_clippers, m_old_meshes, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::volumes.
release()
void Slic3r::GUI::CommonGizmosDataBase::release () inline inherited
{ on_release(); m_is_valid = false; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_release().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_set_state().
render_cut()
void Slic3r::GUI::ObjectClipper::render_cut () const
{
    if (m_clp_ratio == 0.)
        return;
    const SelectionInfo* sel_info = get_pool()->selection_info();
    const ModelObject* mo = sel_info->model_object();
    Geometry::Transformation inst_trafo;
    bool is_assem_cnv = get_pool()->get_canvas()->get_canvas_type() == GLCanvas3D::CanvasAssembleView;
    inst_trafo = is_assem_cnv ?
        mo->instances[sel_info->get_active_instance()]->get_assemble_transformation() :
        mo->instances[sel_info->get_active_instance()]->get_transformation();
    auto offset_to_assembly = mo->instances[0]->get_offset_to_assembly();
    size_t clipper_id = 0;
    for (const ModelVolume* mv : mo->volumes) {
        Geometry::Transformation vol_trafo  = mv->get_transformation();
        Geometry::Transformation trafo = inst_trafo * vol_trafo;
        if (is_assem_cnv) {
            trafo.set_offset(trafo.get_offset() + offset_to_assembly * (GLVolume::explosion_ratio - 1.0) + vol_trafo.get_offset() * (GLVolume::explosion_ratio - 1.0));
        }
        else {
            trafo.set_offset(trafo.get_offset() + Vec3d(0., 0., sel_info->get_sla_shift()));
        }
        auto& clipper = m_clippers[clipper_id];
        clipper->set_plane(*m_clp);
        clipper->set_transformation(trafo);
        if (is_assem_cnv)
            clipper->set_limiting_plane(ClippingPlane(Vec3d::UnitZ(), std::numeric_limits<double>::max()));
        else
            clipper->set_limiting_plane(ClippingPlane(Vec3d::UnitZ(), -SINKING_Z_THRESHOLD));
        glsafe(::glPushMatrix());
        // BBS
        glsafe(::glColor3f(0.25f, 0.25f, 0.25f));
        clipper->render_cut();
        glsafe(::glPopMatrix());
        ++clipper_id;
    }
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::GLVolume::explosion_ratio, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), glsafe, Slic3r::ModelObject::instances, m_clippers, m_clp, m_clp_ratio, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::Geometry::Transformation::set_offset(), Slic3r::SINKING_Z_THRESHOLD, and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::render_clipper_cut(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), and Slic3r::GUI::GLGizmoSeam::render_painter_gizmo().
set_position()
void Slic3r::GUI::ObjectClipper::set_position (double pos, bool keep_normal)
{
    const ModelObject* mo = get_pool()->selection_info()->model_object();
    int active_inst = get_pool()->selection_info()->get_active_instance();
    double z_shift = get_pool()->selection_info()->get_sla_shift();
    //Vec3d camera_dir = wxGetApp().plater()->get_camera().get_dir_forward();
    //if (abs(camera_dir(0)) > EPSILON || abs(camera_dir(1)) > EPSILON)
    //    camera_dir(2) = 0;
    Vec3d normal = (keep_normal && m_clp) ? m_clp->get_normal() : /*-camera_dir;*/ -wxGetApp().plater()->get_camera().get_dir_forward();
    Vec3d center;
    if (get_pool()->get_canvas()->get_canvas_type() == GLCanvas3D::CanvasAssembleView) {
        const SelectionInfo* sel_info = get_pool()->selection_info();
        auto trafo = mo->instances[sel_info->get_active_instance()]->get_assemble_transformation();
        auto offset_to_assembly = mo->instances[0]->get_offset_to_assembly();
        center = trafo.get_offset() + offset_to_assembly * (GLVolume::explosion_ratio - 1.0);
    }
    else {
        center = mo->instances[active_inst]->get_offset() + Vec3d(0., 0., z_shift);
    }
    float dist = normal.dot(center);
    if (pos < 0.)
        pos = m_clp_ratio;
    m_clp_ratio = pos;
    m_clp.reset(new ClippingPlane(normal, (dist - (-m_active_inst_bb_radius) - m_clp_ratio * 2 * m_active_inst_bb_radius)));
    get_pool()->get_canvas()->set_as_dirty();
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::GLVolume::explosion_ratio, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::ModelObject::instances, m_active_inst_bb_radius, m_clp, m_clp_ratio, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::normal(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
Referenced by Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), and Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window().
set_range_and_pos()
void Slic3r::GUI::ObjectClipper::set_range_and_pos (const Vec3d & cpl_normal, double cpl_offset, double pos)
{
    m_clp.reset(new ClippingPlane(cpl_normal, cpl_offset));
    m_clp_ratio = pos;
    get_pool()->get_canvas()->set_as_dirty();
}
References Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), m_clp, m_clp_ratio, and Slic3r::GUI::GLCanvas3D::set_as_dirty().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::update_clipper().
update()
void Slic3r::GUI::CommonGizmosDataBase::update () inline inherited
{ on_update(); m_is_valid = true; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_update().
Member Data Documentation
m_active_inst_bb_radius
double Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::m_active_inst_bb_radius = 0. private
Referenced by on_update(), and set_position().
m_clippers
std::vector<std::unique_ptr<MeshClipper> > Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::m_clippers private
Referenced by has_valid_contour(), is_projection_inside_cut(), on_release(), on_update(), and render_cut().
m_clp
std::unique_ptr<ClippingPlane> Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::m_clp private
Referenced by get_clipping_plane(), on_release(), render_cut(), set_position(), and set_range_and_pos().
m_clp_ratio
double Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::m_clp_ratio = 0. private
Referenced by get_position(), has_valid_contour(), is_projection_inside_cut(), on_release(), render_cut(), set_position(), and set_range_and_pos().
m_common
CommonGizmosDataPool* Slic3r::GUI::CommonGizmosDataBase::m_common = nullptr private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::get_pool().
m_is_valid
bool Slic3r::GUI::CommonGizmosDataBase::m_is_valid = false private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::is_valid(), Slic3r::GUI::CommonGizmosDataBase::release(), and Slic3r::GUI::CommonGizmosDataBase::update().
m_old_meshes
std::vector<const TriangleMesh*> Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::m_old_meshes private
Referenced by on_release(), and on_update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp
src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp