OrcaSlicer: cdt Namespace Reference
cdt Namespace Reference
Namespace containing triangulation functionality.
Namespaces
namespace detail
Classes
struct action_on_intersecting_constraint_edges_t
struct box2d_t
2D bounding box
struct duplicates_info_t
struct edge_t
edge_t connecting two vertices: vertex with smaller index is always first
class locator_kdtree_t
KD-tree holding points.
struct point_to_line_location_t
Relative location of point to a line.
struct point_to_triangle_location_t
Location of point on a triangle.
struct super_geometry_type_t
Enum of what type of geometry used to embed triangulation into.
struct triangle_t
triangulator_t triangle (CCW winding)
class triangulator_t
struct vertex_insertion_order_t
Typedefs
typedef unsigned short layer_depth_t
typedef layer_depth_t boundary_overlap_count_t
Functions
std::vector< std::vector< std::uint32_t > > get_vertex_to_triangles_map (const std::vector< triangle_t > &triangles, const std::uint32_t verticesSize)
template<class ForwardIt , class SortUniqIndsFwdIt >
ForwardIt remove_at (ForwardIt first, ForwardIt last, SortUniqIndsFwdIt ii_first, SortUniqIndsFwdIt ii_last)
template<typename T , typename TVertexIter , typename TGetVertexCoordX , typename TGetVertexCoordY >
duplicates_info_t find_duplicates (TVertexIter first, TVertexIter last, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord)
template<typename TVertex , typename TAllocator >
void remove_duplicates (std::vector< TVertex, TAllocator > &vertices, const std::vector< std::size_t > &duplicates)
template<typename T >
duplicates_info_t remove_duplicates (std::vector< vec2_< T > > &vertices)
template<typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd , typename TMakeEdgeFromStartAndEnd >
void remap_edges (TEdgeIter first, const TEdgeIter last, const std::vector< std::size_t > &mapping, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd, TMakeEdgeFromStartAndEnd makeEdge)
void remap_edges (std::vector< edge_t > &edges, const std::vector< std::size_t > &mapping)
template<typename T , typename TVertex , typename TGetVertexCoordX , typename TGetVertexCoordY , typename TVertexAllocator , typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd , typename TMakeEdgeFromStartAndEnd >
duplicates_info_t remove_duplicates_and_remap_edges (std::vector< TVertex, TVertexAllocator > &vertices, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord, const TEdgeIter edgesFirst, const TEdgeIter edgesLast, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd, TMakeEdgeFromStartAndEnd makeEdge)
template<typename T >
duplicates_info_t remove_duplicates_and_remap_edges (std::vector< vec2_< T > > &vertices, std::vector< edge_t > &edges)
std::unordered_set< edge_t > extract_edges_from_triangles (const std::vector< triangle_t > &triangles)
std::unordered_map< edge_t, std::vector< edge_t > > edge_to_pieces_mapping (const std::unordered_map< edge_t, std::vector< edge_t > > &pieceToOriginals)
template<typename T >
std::unordered_map< edge_t, std::vector< std::uint32_t > > get_edge_to_split_vertices_map (const std::unordered_map< edge_t, std::vector< edge_t > > &edgeToPieces, const std::vector< vec2_< T > > &vertices)
template<typename T , typename TNearPointLocator >
bool check_topology (const cdt::triangulator_t< T, TNearPointLocator > &cdt)
edge_t remap_no_supertriangle (const edge_t &e)
Remap removing super-triangle: subtract 3 from vertices.
template<typename T >
const T & get_x_coord_vec2d (const vec2_< T > &v)
X- coordinate getter for vec2d_t.
template<typename T >
const T & get_y_coord_vec2d (const vec2_< T > &v)
Y-coordinate getter for vec2d_t.
template<typename T >
bool operator== (const vec2_< T > &lhs, const vec2_< T > &rhs)
If two 2D vectors are exactly equal.
static const std::uint32_t null_neighbour (std::numeric_limits< std::uint32_t >::max())
Constant representing no valid neighbor for a triangle.
static const std::uint32_t null_vertex (std::numeric_limits< std::uint32_t >::max())
Constant representing no valid vertex for a triangle.
template<typename T , typename TVertexIter , typename TGetVertexCoordX , typename TGetVertexCoordY >
box2d_t< T > expand_with_points (TVertexIter first, TVertexIter last, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord)
Bounding box of a collection of custom 2D points given coordinate getters.
template<typename T >
box2d_t< T > expand_with_points (const std::vector< vec2_< T > > &vertices)
Bounding box of a collection of 2D points.
std::uint32_t edge_get_v1 (const edge_t &e)
Get edge first vertex.
std::uint32_t edge_get_v2 (const edge_t &e)
Get edge second vertex.
edge_t edge_make (std::uint32_t iV1, std::uint32_t iV2)
Get edge second vertex.
std::uint32_t ccw (std::uint32_t i)
Advance vertex or neighbor index counter-clockwise.
std::uint32_t cw (std::uint32_t i)
Advance vertex or neighbor index clockwise.
bool check_on_edge (const point_to_triangle_location_t::Enum location)
Check if location is classified as on any of three edges.
std::uint32_t edge_neighbour (const point_to_triangle_location_t::Enum location)
Neighbor index from a on-edge location.
template<typename T >
point_to_line_location_t::Enum classify_orientation (const T orientation, const T orientationTolerance=T(0))
Classify value of orient2d predicate.
template<typename T >
point_to_line_location_t::Enum locate_point_wrt_line (const vec2_< T > &p, const vec2_< T > &v1, const vec2_< T > &v2, const T orientationTolerance=T(0))
Check if point lies to the left of, to the right of, or on a line.
template<typename T >
point_to_triangle_location_t::Enum locate_point_wrt_triangle (const vec2_< T > &p, const vec2_< T > &v1, const vec2_< T > &v2, const vec2_< T > &v3)
Check if point a lies inside of, outside of, or on an edge of a triangle.
std::uint32_t get_opposite_neighbour_from_vertex (const std::uint32_t vertIndex)
Opposed neighbor index from vertex index.
std::uint32_t opposite_vertex_from_neighbour (const std::uint32_t neighborIndex)
Opposed vertex index from neighbor index.
std::uint32_t opposite_triangle_index (const triangle_t &tri, const std::uint32_t iVert)
Index of triangle's neighbor opposed to a vertex.
std::uint32_t opposite_triangle_index (const triangle_t &tri, const std::uint32_t iVedge1, const std::uint32_t iVedge2)
Index of triangle's neighbor opposed to an edge.
std::uint32_t get_opposite_vertex_index (const triangle_t &tri, const std::uint32_t iTopo)
Index of triangle's vertex opposed to a triangle.
std::uint32_t get_neighbour_index (const triangle_t &tri, std::uint32_t iTnbr)
If triangle has a given neighbor return neighbor-index, throw otherwise.
std::uint32_t get_vertex_index (const triangle_t &tri, const std::uint32_t iV)
If triangle has a given vertex return vertex-index, throw otherwise.
std::uint32_t get_opposite_triangle_index (const triangle_t &tri, const std::uint32_t iVert)
Given triangle and a vertex find opposed triangle.
std::uint32_t get_opposed_vertex_index (const triangle_t &tri, std::uint32_t iTopo)
Given two triangles, return vertex of first triangle opposed to the second.
template<typename T >
bool check_is_in_circumcircle (const vec2_< T > &p, const vec2_< T > &v1, const vec2_< T > &v2, const vec2_< T > &v3)
Test if point lies in a circumscribed circle of a triangle.
bool check_vertices_share_edge (const std::vector< std::uint32_t > &aTris, const std::vector< std::uint32_t > &bTris)
Test if two vertices share at least one common triangle.
template<typename T >
T get_square_distance (const T ax, const T ay, const T bx, const T by)
template<typename T >
T distance (const T ax, const T ay, const T bx, const T by)
template<typename T >
T distance (const vec2_< T > &a, const vec2_< T > &b)
template<typename T >
T get_square_distance (const vec2_< T > &a, const vec2_< T > &b)
Detailed Description
Namespace containing triangulation functionality.
Function Documentation
ccw()
std::uint32_t cdt::ccw (std::uint32_t i) inline
Advance vertex or neighbor index counter-clockwise.
{
    return std::uint32_t((i + 1) % 3);
}
Referenced by cdt::triangulator_t< T, TNearPointLocator >::check_is_edgeflip_needed(), cdt::triangulator_t< T, TNearPointLocator >::do_edgeflip(), cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle(), cdt::triangulator_t< T, TNearPointLocator >::grow_to_boundary(), cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge(), cdt::triangulator_t< T, TNearPointLocator >::insert_vertex_and_flip_fixed_edges(), cdt::triangulator_t< T, TNearPointLocator >::peel_layer(), cdt::triangulator_t< T, TNearPointLocator >::TintersectedTriangle(), triangulate_face(), and cdt::triangulator_t< T, TNearPointLocator >::walk_triangles().
check_is_in_circumcircle()
template<typename T > bool cdt::check_is_in_circumcircle (const vec2_< T > & p, const vec2_< T > & v1, const vec2_< T > & v2, const vec2_< T > & v3)
Test if point lies in a circumscribed circle of a triangle.
{
    const double p_[2] = { static_cast<double>(p.x()), static_cast<double>(p.y()) };
    const double v1_[2] = { static_cast<double>(v1.x()), static_cast<double>(v1.y()) };
    const double v2_[2] = { static_cast<double>(v2.x()), static_cast<double>(v2.y()) };
    const double v3_[2] = { static_cast<double>(v3.x()), static_cast<double>(v3.y()) };
    return ::incircle(v1_, v2_, v3_, p_) > T(0);
}
References vec2_< T >::x(), and vec2_< T >::y().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::check_is_edgeflip_needed(), and cdt::triangulator_t< T, TNearPointLocator >::find_delaunay_point().
check_on_edge()
bool cdt::check_on_edge (const point_to_triangle_location_t::Enum location) inline
Check if location is classified as on any of three edges.
{
    return location > point_to_triangle_location_t::OUTSIDE;
}
References cdt::point_to_triangle_location_t::OUTSIDE.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::trianglesAt(), and cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at().
check_topology()
template<typename T , typename TNearPointLocator > bool cdt::check_topology (const cdt::triangulator_t< T, TNearPointLocator > & cdt) inline
Verify that triangulation topology is consistent.
Checks:
for each vertex adjacent triangles contain the vertex
each triangle's neighbor in turn has triangle as its neighbor
each of triangle's vertices has triangle as adjacent
Template Parameters
T type of vertex coordinates (e.g., float, double)
TNearPointLocator class providing locating near point for efficiently
{
    // Check if vertices' adjacent triangles contain vertex
    const std::vector<std::vector<std::uint32_t>> vertTris = cdt.is_finalized()
        ? get_vertex_to_triangles_map(
            cdt.triangles, static_cast<std::uint32_t>(cdt.vertices.size()))
        : cdt.vertTris;
    for (std::uint32_t iV(0); iV < std::uint32_t(cdt.vertices.size()); ++iV) {
        const std::vector<std::uint32_t>& vTris = vertTris[iV];
        typedef std::vector<std::uint32_t>::const_iterator TriIndCit;
        for (TriIndCit it = vTris.begin(); it != vTris.end(); ++it) {
            const std::array<std::uint32_t, 3>& vv = cdt.triangles[*it].vertices;
            if (std::find(vv.begin(), vv.end(), iV) == vv.end())
                return false;
        }
    }
    // Check if triangle neighbor links are fine
    for (std::uint32_t iT(0); iT < std::uint32_t(cdt.triangles.size()); ++iT) {
        const triangle_t& t = cdt.triangles[iT];
        typedef std::array<std::uint32_t, 3>::const_iterator NCit;
        for (NCit it = t.neighbors.begin(); it != t.neighbors.end(); ++it) {
            if (*it == null_neighbour)
                continue;
            const std::array<std::uint32_t, 3>& nn = cdt.triangles[*it].neighbors;
            if (std::find(nn.begin(), nn.end(), iT) == nn.end())
                return false;
        }
    }
    // Check if triangle's vertices have triangle as adjacent
    for (std::uint32_t iT(0); iT < std::uint32_t(cdt.triangles.size()); ++iT) {
        const triangle_t& t = cdt.triangles[iT];
        typedef std::array<std::uint32_t, 3>::const_iterator VCit;
        for (VCit it = t.vertices.begin(); it != t.vertices.end(); ++it) {
            const std::vector<std::uint32_t>& tt = vertTris[*it];
            if (std::find(tt.begin(), tt.end(), iT) == tt.end())
                return false;
        }
    }
    return true;
}
References get_vertex_to_triangles_map(), cdt::triangle_t::neighbors, null_neighbour(), and cdt::triangle_t::vertices.
Referenced by triangulate_face().
check_vertices_share_edge()
bool cdt::check_vertices_share_edge (const std::vector< std::uint32_t > & aTris, const std::vector< std::uint32_t > & bTris) inline
Test if two vertices share at least one common triangle.
{
    for (std::vector<std::uint32_t>::const_iterator it = aTris.begin(); it != aTris.end(); ++it)
        if (std::find(bTris.begin(), bTris.end(), *it) != bTris.end())
            return true;
    return false;
}
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), and cdt::triangulator_t< T, TNearPointLocator >::insert_edge().
classify_orientation()
template<typename T > point_to_line_location_t::Enum cdt::classify_orientation (const T orientation, const T orientationTolerance = T(0))
Classify value of orient2d predicate.
{
    if (orientation < -orientationTolerance)
        return point_to_line_location_t::RIGHT_SIDE;
    if (orientation > orientationTolerance)
        return point_to_line_location_t::LEFT_SIDE;
    return point_to_line_location_t::COLLINEAR;
}
References cdt::point_to_line_location_t::COLLINEAR, cdt::point_to_line_location_t::LEFT_SIDE, and cdt::point_to_line_location_t::RIGHT_SIDE.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle(), locate_point_wrt_line(), and cdt::triangulator_t< T, TNearPointLocator >::TintersectedTriangle().
cw()
std::uint32_t cdt::cw (std::uint32_t i) inline
Advance vertex or neighbor index clockwise.
{
    return std::uint32_t((i + 2) % 3);
}
Referenced by cdt::triangulator_t< T, TNearPointLocator >::check_is_edgeflip_needed(), cdt::triangulator_t< T, TNearPointLocator >::do_edgeflip(), cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle(), cdt::triangulator_t< T, TNearPointLocator >::grow_to_boundary(), cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge(), cdt::triangulator_t< T, TNearPointLocator >::insert_vertex_and_flip_fixed_edges(), cdt::triangulator_t< T, TNearPointLocator >::peel_layer(), cdt::triangulator_t< T, TNearPointLocator >::TintersectedTriangle(), and triangulate_face().
distance() [1/2]
template<typename T > T cdt::distance (const T ax, const T ay, const T bx, const T by)
{
    return std::sqrt(get_square_distance(ax, ay, bx, by));
}
References get_square_distance().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), distance(), and cdt::triangulator_t< T, TNearPointLocator >::insert_edge().
distance() [2/2]
template<typename T > T cdt::distance (const vec2_< T > & a, const vec2_< T > & b)
{
    return distance(a.x(), a.y(), b.x(), b.y());
}
References distance().
edge_get_v1()
std::uint32_t cdt::edge_get_v1 (const edge_t & e) inline
Get edge first vertex.
{
    return e.v1();
}
References cdt::edge_t::v1().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edges(), cdt::triangulator_t< T, TNearPointLocator >::insert_edges(), remap_edges(), and remove_duplicates_and_remap_edges().
edge_get_v2()
std::uint32_t cdt::edge_get_v2 (const edge_t & e) inline
Get edge second vertex.
{
    return e.v2();
}
References cdt::edge_t::v2().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edges(), cdt::triangulator_t< T, TNearPointLocator >::insert_edges(), remap_edges(), and remove_duplicates_and_remap_edges().
edge_make()
edge_t cdt::edge_make (std::uint32_t iV1, std::uint32_t iV2) inline
Get edge second vertex.
{
    return edge_t(iV1, iV2);
}
Referenced by remap_edges(), and remove_duplicates_and_remap_edges().
edge_neighbour()
std::uint32_t cdt::edge_neighbour (const point_to_triangle_location_t::Enum location) inline
Neighbor index from a on-edge location.
Note
Call only if located on the edge!
{
    assert(location >= point_to_triangle_location_t::ON_1ST_EDGE);
    return static_cast<std::uint32_t>(location - point_to_triangle_location_t::ON_1ST_EDGE);
}
References cdt::point_to_triangle_location_t::ON_1ST_EDGE.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::trianglesAt(), and cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at().
expand_with_points() [1/2]
template<typename T > box2d_t< T > cdt::expand_with_points (const std::vector< vec2_< T > > & vertices)
Bounding box of a collection of 2D points.
{
    return expand_with_points<T>(
        vertices.begin(), vertices.end(), get_x_coord_vec2d<T>, get_y_coord_vec2d<T>);
}
expand_with_points() [2/2]
template<typename T , typename TVertexIter , typename TGetVertexCoordX , typename TGetVertexCoordY > box2d_t< T > cdt::expand_with_points (TVertexIter first, TVertexIter last, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord)
Bounding box of a collection of custom 2D points given coordinate getters.
{
    const T max = std::numeric_limits<T>::max();
    box2d_t<T> box = { { max, max }, { -max, -max } };
    for (; first != last; ++first) {
        box.expand_with_point(get_x_coord(*first), get_y_coord(*first));
    }
    return box;
}
References cdt::box2d_t< T >::expand_with_point(), and max().
get_neighbour_index()
std::uint32_t cdt::get_neighbour_index (const triangle_t & tri, std::uint32_t iTnbr) inline
If triangle has a given neighbor return neighbor-index, throw otherwise.
{
    for (std::uint32_t ni = std::uint32_t(0); ni < std::uint32_t(3); ++ni)
        if (iTnbr == tri.neighbors[ni])
            return ni;
    throw std::runtime_error("Could not find neighbor triangle index");
}
References cdt::triangle_t::neighbors.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::change_neighbour().
get_opposed_vertex_index()
std::uint32_t cdt::get_opposed_vertex_index (const triangle_t & tri, std::uint32_t iTopo) inline
Given two triangles, return vertex of first triangle opposed to the second.
{
    return tri.vertices[get_opposite_vertex_index(tri, iTopo)];
}
References get_opposite_vertex_index(), and cdt::triangle_t::vertices.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), and cdt::triangulator_t< T, TNearPointLocator >::insert_edge().
get_opposite_neighbour_from_vertex()
std::uint32_t cdt::get_opposite_neighbour_from_vertex (const std::uint32_t vertIndex) inline
Opposed neighbor index from vertex index.
{
    MCUT_ASSERT(vertIndex < 3);
    if (vertIndex == std::uint32_t(0))
        return std::uint32_t(1);
    if (vertIndex == std::uint32_t(1))
        return std::uint32_t(2);
    if (vertIndex == std::uint32_t(2))
        return std::uint32_t(0);
    throw std::runtime_error("Invalid vertex index");
}
References MCUT_ASSERT.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::grow_to_boundary(), opposite_triangle_index(), opposite_triangle_index(), cdt::triangulator_t< T, TNearPointLocator >::peel_layer(), and triangulate_face().
get_opposite_triangle_index()
std::uint32_t cdt::get_opposite_triangle_index (const triangle_t & tri, const std::uint32_t iVert) inline
Given triangle and a vertex find opposed triangle.
{
    return tri.neighbors[opposite_triangle_index(tri, iVert)];
}
References cdt::triangle_t::neighbors, and opposite_triangle_index().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), cdt::triangulator_t< T, TNearPointLocator >::enforce_delaunay_property_using_edge_flips(), cdt::triangulator_t< T, TNearPointLocator >::insert_edge(), and cdt::triangulator_t< T, TNearPointLocator >::insert_vertex_and_flip_fixed_edges().
get_opposite_vertex_index()
std::uint32_t cdt::get_opposite_vertex_index (const triangle_t & tri, const std::uint32_t iTopo) inline
Index of triangle's vertex opposed to a triangle.
{
    for (std::uint32_t ni = std::uint32_t(0); ni < std::uint32_t(3); ++ni)
        if (iTopo == tri.neighbors[ni])
            return opposite_vertex_from_neighbour(ni);
    throw std::runtime_error("Could not find opposed vertex index");
}
References cdt::triangle_t::neighbors, and opposite_vertex_from_neighbour().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::check_is_edgeflip_needed(), cdt::triangulator_t< T, TNearPointLocator >::do_edgeflip(), get_opposed_vertex_index(), cdt::triangulator_t< T, TNearPointLocator >::insert_point_on_edge(), and cdt::triangulator_t< T, TNearPointLocator >::insert_vertex_and_flip_fixed_edges().
get_square_distance() [1/2]
template<typename T > T cdt::get_square_distance (const T ax, const T ay, const T bx, const T by)
{
    const T dx = bx - ax;
    const T dy = by - ay;
    return dx * dx + dy * dy;
}
Referenced by distance(), cdt::detail::get_intersection_point_coords(), get_square_distance(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
get_square_distance() [2/2]
template<typename T > T cdt::get_square_distance (const vec2_< T > & a, const vec2_< T > & b)
{
    return get_square_distance(a.x(), a.y(), b.x(), b.y());
}
References get_square_distance().
get_vertex_index()
std::uint32_t cdt::get_vertex_index (const triangle_t & tri, const std::uint32_t iV) inline
If triangle has a given vertex return vertex-index, throw otherwise.
{
    for (std::uint32_t i = std::uint32_t(0); i < std::uint32_t(3); ++i)
        if (iV == tri.vertices[i])
            return i;
    throw std::runtime_error("Could not find vertex index in triangle");
}
References cdt::triangle_t::vertices.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle(), and cdt::triangulator_t< T, TNearPointLocator >::TintersectedTriangle().
get_x_coord_vec2d()
template<typename T > const T & cdt::get_x_coord_vec2d (const vec2_< T > & v)
X- coordinate getter for vec2d_t.
{
    return v.x();
}
References vec2_< T >::x().
get_y_coord_vec2d()
template<typename T > const T & cdt::get_y_coord_vec2d (const vec2_< T > & v)
Y-coordinate getter for vec2d_t.
{
    return v.y();
}
References vec2_< T >::y().
locate_point_wrt_line()
template<typename T > point_to_line_location_t::Enum cdt::locate_point_wrt_line (const vec2_< T > & p, const vec2_< T > & v1, const vec2_< T > & v2, const T orientationTolerance = T(0))
Check if point lies to the left of, to the right of, or on a line.
{
    return classify_orientation(orient2d(p, v1, v2), orientationTolerance);
}
References classify_orientation(), and orient2d().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::check_is_edgeflip_needed(), cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), cdt::triangulator_t< T, TNearPointLocator >::insert_edge(), locate_point_wrt_triangle(), and cdt::triangulator_t< T, TNearPointLocator >::walk_triangles().
locate_point_wrt_triangle()
template<typename T > point_to_triangle_location_t::Enum cdt::locate_point_wrt_triangle (const vec2_< T > & p, const vec2_< T > & v1, const vec2_< T > & v2, const vec2_< T > & v3)
Check if point a lies inside of, outside of, or on an edge of a triangle.
{
    point_to_triangle_location_t::Enum result = point_to_triangle_location_t::INSIDE;
    point_to_line_location_t::Enum edgeCheck = locate_point_wrt_line(p, v1, v2);
    if (edgeCheck == point_to_line_location_t::RIGHT_SIDE)
        return point_to_triangle_location_t::OUTSIDE;
    if (edgeCheck == point_to_line_location_t::COLLINEAR)
        result = point_to_triangle_location_t::ON_1ST_EDGE;
    edgeCheck = locate_point_wrt_line(p, v2, v3);
    if (edgeCheck == point_to_line_location_t::RIGHT_SIDE)
        return point_to_triangle_location_t::OUTSIDE;
    if (edgeCheck == point_to_line_location_t::COLLINEAR)
        result = point_to_triangle_location_t::ON_2ND_EDGE;
    edgeCheck = locate_point_wrt_line(p, v3, v1);
    if (edgeCheck == point_to_line_location_t::RIGHT_SIDE)
        return point_to_triangle_location_t::OUTSIDE;
    if (edgeCheck == point_to_line_location_t::COLLINEAR)
        result = point_to_triangle_location_t::ON_3RD_EDGE;
    return result;
}
References cdt::point_to_line_location_t::COLLINEAR, cdt::point_to_triangle_location_t::INSIDE, locate_point_wrt_line(), cdt::point_to_triangle_location_t::ON_1ST_EDGE, cdt::point_to_triangle_location_t::ON_2ND_EDGE, cdt::point_to_triangle_location_t::ON_3RD_EDGE, cdt::point_to_triangle_location_t::OUTSIDE, and cdt::point_to_line_location_t::RIGHT_SIDE.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::trianglesAt(), and cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at().
null_neighbour()
static const std::uint32_t cdt::null_neighbour (std::numeric_limits< std::uint32_t > ::max()) static
Constant representing no valid neighbor for a triangle.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::add_super_triangle(), cdt::triangulator_t< T, TNearPointLocator >::add_triangle(), cdt::triangulator_t< T, TNearPointLocator >::change_neighbour(), check_topology(), cdt::triangulator_t< T, TNearPointLocator >::conform_to_edge(), cdt::triangulator_t< T, TNearPointLocator >::enforce_delaunay_property_using_edge_flips(), cdt::triangulator_t< T, TNearPointLocator >::erase_dummies(), cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle(), cdt::triangulator_t< T, TNearPointLocator >::grow_to_boundary(), cdt::triangulator_t< T, TNearPointLocator >::insert_edge(), cdt::triangulator_t< T, TNearPointLocator >::insert_vertex(), cdt::triangulator_t< T, TNearPointLocator >::insert_vertex_and_flip_fixed_edges(), cdt::triangulator_t< T, TNearPointLocator >::make_dummies(), cdt::triangulator_t< T, TNearPointLocator >::peel_layer(), cdt::triangulator_t< T, TNearPointLocator >::pseudo_polygon_outer_triangle(), cdt::triangulator_t< T, TNearPointLocator >::remove_triangles(), cdt::triangulator_t< T, TNearPointLocator >::TintersectedTriangle(), cdt::triangulator_t< T, TNearPointLocator >::trianglesAt(), triangulate_face(), cdt::triangulator_t< T, TNearPointLocator >::triangulate_pseudo_polygon(), cdt::triangulator_t< T, TNearPointLocator >::walk_triangles(), and cdt::triangulator_t< T, TNearPointLocator >::walking_search_triangle_at().
null_vertex()
static const std::uint32_t cdt::null_vertex (std::numeric_limits< std::uint32_t > ::max()) static
Constant representing no valid vertex for a triangle.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::add_triangle().
operator==()
template<typename T > bool cdt::operator== (const vec2_< T > & lhs, const vec2_< T > & rhs)
If two 2D vectors are exactly equal.
{
    return lhs.x() == rhs.x() && lhs.y() == rhs.y();
}
References vec2_< T >::x(), and vec2_< T >::y().
opposite_triangle_index() [1/2]
std::uint32_t cdt::opposite_triangle_index (const triangle_t & tri, const std::uint32_t iVedge1, const std::uint32_t iVedge2) inline
Index of triangle's neighbor opposed to an edge.
{
    for (std::uint32_t vi = std::uint32_t(0); vi < std::uint32_t(3); ++vi) {
        const std::uint32_t iVert = tri.vertices[vi];
        if (iVert != iVedge1 && iVert != iVedge2)
            return get_opposite_neighbour_from_vertex(vi);
    }
    throw std::runtime_error("Could not find opposed-to-edge triangle index");
}
References get_opposite_neighbour_from_vertex(), and cdt::triangle_t::vertices.
opposite_triangle_index() [2/2]
std::uint32_t cdt::opposite_triangle_index (const triangle_t & tri, const std::uint32_t iVert) inline
Index of triangle's neighbor opposed to a vertex.
{
    for (std::uint32_t vi = std::uint32_t(0); vi < std::uint32_t(3); ++vi)
        if (iVert == tri.vertices[vi])
            return get_opposite_neighbour_from_vertex(vi);
    throw std::runtime_error("Could not find opposed triangle index");
}
References get_opposite_neighbour_from_vertex(), and cdt::triangle_t::vertices.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::change_neighbour(), and get_opposite_triangle_index().
opposite_vertex_from_neighbour()
std::uint32_t cdt::opposite_vertex_from_neighbour (const std::uint32_t neighborIndex) inline
Opposed vertex index from neighbor index.
{
    if (neighborIndex == std::uint32_t(0))
        return std::uint32_t(2);
    if (neighborIndex == std::uint32_t(1))
        return std::uint32_t(0);
    if (neighborIndex == std::uint32_t(2))
        return std::uint32_t(1);
    throw std::runtime_error("Invalid neighbor index");
}
Referenced by get_opposite_vertex_index().
remap_no_supertriangle()
edge_t cdt::remap_no_supertriangle (const edge_t & e) inline
Remap removing super-triangle: subtract 3 from vertices.
{
    return edge_t(e.v1() - 3, e.v2() - 3);
}
References cdt::edge_t::v1(), and cdt::edge_t::v2().
Referenced by cdt::triangulator_t< T, TNearPointLocator >::finalise_triangulation().