OrcaSlicer: Slic3r::DnsRR_SRV Struct Reference
Slic3r::DnsRR_SRV Struct Reference
Public Types
enum { TAG = 0x21 , MIN_SIZE = 8 }
Static Public Member Functions
static optional< DnsRR_SRV > decode (const std::vector< char > &buffer, const DnsResource &rr, size_t dataoffset)
Public Attributes
uint16_t priority
uint16_t weight
uint16_t port
DnsName hostname
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
TAG
MIN_SIZE
  {
    TAG = 0x21,
    MIN_SIZE = 8,
  };
Member Function Documentation
decode()
static optional< DnsRR_SRV > Slic3r::DnsRR_SRV::decode (const std::vector< char > & buffer, const DnsResource & rr, size_t dataoffset) inline static
  {
    if (rr.data.size() < MIN_SIZE) {
      return boost::none;
    }
    DnsRR_SRV res;
    const uint16_t *data_16 = reinterpret_cast<const uint16_t*>(rr.data.data());
    res.priority = endian::big_to_native(data_16[0]);
    res.weight = endian::big_to_native(data_16[1]);
    res.port = endian::big_to_native(data_16[2]);
    size_t offset = dataoffset + 6;
    auto hostname = DnsName::decode(buffer, offset);
    if (hostname) {
      res.hostname = std::move(*hostname);
      return std::move(res);
    } else {
      return boost::none;
    }
  }
References buffer, Slic3r::DnsResource::data, Slic3r::DnsName::decode(), hostname, MIN_SIZE, Slic3r::offset(), port, priority, and weight.
Referenced by Slic3r::DnsMessage::parse_rr().
Member Data Documentation
hostname
DnsName Slic3r::DnsRR_SRV::hostname
Referenced by decode().
port
uint16_t Slic3r::DnsRR_SRV::port
Referenced by decode().
priority
uint16_t Slic3r::DnsRR_SRV::priority
Referenced by decode().
weight
uint16_t Slic3r::DnsRR_SRV::weight
Referenced by decode().
The documentation for this struct was generated from the following file:
src/slic3r/Utils/Bonjour.cpp