OrcaSlicer: Slic3r::GUI::ImGuiWrapper Class Reference
Slic3r::GUI::ImGuiWrapper Class Reference
#include <src/slic3r/GUI/ImGuiWrapper.hpp>
Classes
struct LastSliderStatus
Public Member Functions
ImGuiWrapper ()
~ImGuiWrapper ()
void read_glsl_version ()
void set_language (const std::string &language)
void set_display_size (float w, float h)
void set_scaling (float font_size, float scale_style, float scale_both)
bool update_mouse_data (wxMouseEvent &evt)
bool update_key_data (wxKeyEvent &evt)
float get_font_size () const
float get_style_scaling () const
void new_frame ()
void render ()
float scaled (float x) const
ImVec2 scaled (float x, float y) const
ImVec2 calc_text_size (const wxString &text, float wrap_width=-1.0f) const
ImVec2 calc_button_size (const wxString &text, const ImVec2 &button_size=ImVec2(0, 0)) const
ImVec2 get_item_spacing () const
float get_slider_float_height () const
const LastSliderStatus & get_last_slider_status () const
void set_next_window_pos (float x, float y, int flag, float pivot_x=0.0f, float pivot_y=0.0f)
void set_next_window_bg_alpha (float alpha)
void set_next_window_size (float x, float y, ImGuiCond cond)
bool bbl_combo_with_filter (const char *label, const std::string &preview_value, const std::vector< std::string > &all_items, std::vector< int > *filtered_items_idx, bool *is_filtered, float item_height=0.0f)
bool bbl_input_double (const wxString &label, const double &value, const std::string &format="%0.2f")
bool bbl_slider_float (const std::string &label, float *v, float v_min, float v_max, const char *format="%.3f", float power=1.0f, bool clamp=true, const wxString &tooltip={})
bool bbl_slider_float_style (const std::string &label, float *v, float v_min, float v_max, const char *format="%.3f", float power=1.0f, bool clamp=true, const wxString &tooltip={})
bool begin (const std::string &name, int flags=0)
bool begin (const wxString &name, int flags=0)
bool begin (const std::string &name, bool *close, int flags=0)
bool begin (const wxString &name, bool *close, int flags=0)
void end ()
bool button (const wxString &label)
bool bbl_button (const wxString &label)
bool button (const wxString &label, float width, float height)
bool radio_button (const wxString &label, bool active)
bool image_button ()
bool input_double (const std::string &label, const double &value, const std::string &format="%.3f")
bool input_double (const wxString &label, const double &value, const std::string &format="%.3f")
bool input_vec3 (const std::string &label, const Vec3d &value, float width, const std::string &format="%.3f")
bool checkbox (const wxString &label, bool &value)
bool bbl_checkbox (const wxString &label, bool &value)
bool bbl_radio_button (const char *label, bool active)
bool bbl_sliderin (const char *label, int *v, int v_min, int v_max, const char *format="%d", ImGuiSliderFlags flags=0)
void text (const char *label)
void text (const std::string &label)
void text (const wxString &label)
void text_colored (const ImVec4 &color, const char *label)
void text_colored (const ImVec4 &color, const std::string &label)
void text_colored (const ImVec4 &color, const wxString &label)
void text_wrapped (const char *label, float wrap_width)
void text_wrapped (const std::string &label, float wrap_width)
void text_wrapped (const wxString &label, float wrap_width)
void tooltip (const char *label, float wrap_width)
void tooltip (const wxString &label, float wrap_width)
bool slider_float (const char *label, float *v, float v_min, float v_max, const char *format="%.3f", float power=1.0f, bool clamp=true)
bool slider_float (const std::string &label, float *v, float v_min, float v_max, const char *format="%.3f", float power=1.0f, bool clamp=true)
bool slider_float (const wxString &label, float *v, float v_min, float v_max, const char *format="%.3f", float power=1.0f, bool clamp=true)
bool combo (const wxString &label, const std::vector< std::string > &options, int &selection)
bool undo_redo_list (const ImVec2 &size, const bool is_undo, bool(*items_getter)(const bool, int, const char **), int &hovered, int &selected, int &mouse_wheel)
void search_list (const ImVec2 &size, bool(*items_getter)(int, const char **label, const char **tooltip), char *search_str, Search::OptionViewParameters &view_params, int &selected, bool &edited, int &mouse_wheel, bool is_localized)
void bold_text (const std::string &str)
void title (const std::string &str)
const std::vector< std::string > get_fonts_names () const
bool push_bold_font ()
bool pop_bold_font ()
bool push_font_by_name (std::string font_name)
bool pop_font_by_name (std::string font_name)
void load_fonts_texture ()
void destroy_fonts_texture ()
void disabled_begin (bool disabled)
void disabled_end ()
bool want_mouse () const
bool want_keyboard () const
bool want_text_input () const
bool want_any_input () const
Static Public Member Functions
static void on_change_color_mode (bool is_dark)
static void push_toolbar_style (const float scale)
static void pop_toolbar_style ()
static void push_menu_style (const float scale)
static void pop_menu_style ()
static void push_common_window_style (const float scale)
static void pop_common_window_style ()
static void push_confirm_button_style ()
static void pop_confirm_button_style ()
static void push_cancel_button_style ()
static void pop_cancel_button_style ()
static void push_button_disable_style ()
static void pop_button_disable_style ()
static void push_combo_style (const float scale)
static void pop_combo_style ()
Static Public Attributes
static const ImVec4 COL_GREY_DARK = { 0.333f, 0.333f, 0.333f, 1.0f }
static const ImVec4 COL_GREY_LIGHT = { 0.4f, 0.4f, 0.4f, 1.0f }
static const ImVec4 COL_ORANGE_DARK = { 0.757f, 0.404f, 0.216f, 1.0f }
static const ImVec4 COL_ORANGE_LIGHT = { 1.0f, 0.49f, 0.216f, 1.0f }
static const ImVec4 COL_WINDOW_BACKGROUND = { 0.1f, 0.1f, 0.1f, 0.8f }
static const ImVec4 COL_BUTTON_BACKGROUND = COL_ORANGE_DARK
static const ImVec4 COL_BUTTON_HOVERED = COL_ORANGE_LIGHT
static const ImVec4 COL_BUTTON_ACTIVE = ImGuiWrapper::COL_BUTTON_HOVERED
static const ImVec4 COL_BLUE_LIGHT = ImVec4(0.122f, 0.557f, 0.918f, 1.0f)
static const ImVec4 COL_GREEN_LIGHT = ImVec4(0.86f, 0.99f, 0.91f, 1.0f)
static const ImVec4 COL_HOVER = { 0.933f, 0.933f, 0.933f, 1.0f }
static const ImVec4 COL_ACTIVE = { 0.675f, 0.675f, 0.675f, 1.0f }
static const ImVec4 COL_TITLE_BG = { 0.745f, 0.745f, 0.745f, 1.0f }
static const ImVec4 COL_WINDOW_BG = { 1.000f, 1.000f, 1.000f, 1.0f }
static const ImVec4 COL_WINDOW_BG_DARK = { 45 / 255.f, 45 / 255.f, 49 / 255.f, 1.f }
static const ImVec4 COL_SEPARATOR = { 0.93f, 0.93f, 0.93f, 1.0f }
static const ImVec4 COL_SEPARATOR_DARK = { 0.24f, 0.24f, 0.27f, 1.0f }
static int TOOLBAR_WINDOW_FLAGS
Private Member Functions
void init_font (bool compress)
void init_input ()
void init_style ()
void render_draw_data (ImDrawData *draw_data)
bool display_initialized () const
void destroy_font ()
std::vector< unsigned char > load_svg (const std::string &bitmap_name, unsigned target_width, unsigned target_height, unsigned *outwidth, unsigned *outheight)
Static Private Member Functions
static const char * clipboard_get (void *user_data)
static void clipboard_set (void *user_data, const char *text)
Private Attributes
const ImWchar * m_glyph_ranges { nullptr }
const ImWchar * m_glyph_basic_ranges { nullptr }
bool m_font_cjk { false }
float m_font_size { 18.0 }
unsigned m_font_texture { 0 }
unsigned m_font_another_texture { 0 }
float m_style_scaling { 1.0 }
unsigned m_mouse_buttons { 0 }
bool m_disabled { false }
bool m_new_frame_open { false }
std::string m_clipboard_text
LastSliderStatus m_last_slider_status
ImFont * default_font = nullptr
ImFont * bold_font = nullptr
std::map< std::string, ImFont * > im_fonts_map
std::vector< std::string > m_fonts_names
Detailed Description
Class Documentation
Slic3r::GUI::ImGuiWrapper::LastSliderStatus
struct Slic3r::GUI::ImGuiWrapper::LastSliderStatus
Class Members
bool clicked { false }
bool deactivated_after_edit { false }
bool edited { false }
bool hovered { false }
Constructor & Destructor Documentation
ImGuiWrapper()
Slic3r::GUI::ImGuiWrapper::ImGuiWrapper ()
{
    ImGui::CreateContext();
    init_input();
    init_style();
    ImGui::GetIO().IniFilename = nullptr;
}
References ImGui::CreateContext(), ImGui::GetIO(), ImGuiIO::IniFilename, init_input(), and init_style().
~ImGuiWrapper()
Slic3r::GUI::ImGuiWrapper::~ImGuiWrapper ()
{
    //destroy_fonts_texture();
    destroy_font();
    ImGui::DestroyContext();
}
References destroy_font(), and ImGui::DestroyContext().
Member Function Documentation
bbl_button()
bool Slic3r::GUI::ImGuiWrapper::bbl_button (const wxString & label)
{
    auto label_utf8 = into_u8(label);
    return ImGui::BBLButton(label_utf8.c_str());
}
References ImGui::BBLButton(), and Slic3r::GUI::into_u8().
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), and Slic3r::GUI::IMSlider::render_input_custom_gcode().
bbl_checkbox()
bool Slic3r::GUI::ImGuiWrapper::bbl_checkbox (const wxString & label, bool & value)
{
    bool result;
    bool b_value = value;
    if (b_value) {
        ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));
        ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));
        ImGui::PushStyleColor(ImGuiCol_FrameBgActive, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));
    }
    auto label_utf8 = into_u8(label);
    result          = ImGui::BBLCheckbox(label_utf8.c_str(), &value);
    if (b_value) { ImGui::PopStyleColor(3);}
    return result;
}
References ImGui::BBLCheckbox(), ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, Slic3r::GUI::into_u8(), ImGui::PopStyleColor(), and ImGui::PushStyleColor().
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
bbl_combo_with_filter()
bool Slic3r::GUI::ImGuiWrapper::bbl_combo_with_filter (const char * label, const std::string & preview_value, const std::vector< std::string > & all_items, std::vector< int > * filtered_items_idx, bool * is_filtered, float item_height = 0.0f)
{
    ImGuiContext& g = *GImGui;
    const ImGuiStyle& style = g.Style;
    ImGuiWindow* window = ImGui::GetCurrentWindow();
    if (window->SkipItems)
        return false;
    static char pattern_buffer[256] = { 0 };
    auto simple_match = [](const char* pattern, const char* str) {
        wxString sub_str = wxString(pattern).Lower();
        wxString main_str = wxString(str).Lower();
        return main_str.Find(sub_str);
    };
    bool is_filtering = false;
    bool is_new_open = false;
    float sz = ImGui::GetFrameHeight();
    ImVec2 arrow_size(sz, sz);
    ImVec2 CursorPos = window->DC.CursorPos;
    const ImRect arrow_bb(CursorPos, CursorPos + arrow_size);
    float ButtonTextAlignX = g.Style.ButtonTextAlign.x;
    g.Style.ButtonTextAlign.x = 0;
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, { sz, style.FramePadding.y});
    ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImGui::GetStyleColorVec4(ImGuiCol_ButtonHovered));
    if (button(preview_value + label, ImGui::CalcItemWidth(), 0))
    {
        ImGui::OpenPopup(label);
        is_new_open = true;
    }
    g.Style.ButtonTextAlign.x = ButtonTextAlignX;
    ImGui::PopStyleVar();
    ImGui::PopStyleColor();
    ImGui::BBLRenderArrow(window->DrawList, arrow_bb.Min + ImVec2(ImMax(0.0f, (arrow_size.x - g.FontSize) * 0.5f), ImMax(0.0f, (arrow_size.y - g.FontSize) * 0.5f)), ImGui::GetColorU32(ImGuiCol_Text), ImGuiDir_Down);
    if (is_new_open)
        memset(pattern_buffer, 0, IM_ARRAYSIZE(pattern_buffer));
    float item_rect_width = ImGui::GetItemRectSize().x;
    float item_rect_height = item_height ? item_height : ImGui::GetItemRectSize().y;
    ImGui::SetNextWindowPos({ CursorPos.x, ImGui::GetItemRectMax().y + 4 * m_style_scaling });
    ImGui::SetNextWindowSize({ item_rect_width, 0 });
    if (ImGui::BeginPopup(label))
    {
        ImGuiWindow* popup_window = ImGui::GetCurrentWindow();
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0, 0));
        ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(8.0f * m_style_scaling, item_rect_height - g.FontSize) * 0.5f);
        wchar_t ICON_SEARCH = *pattern_buffer != '\0' ? ImGui::TextSearchCloseIcon : ImGui::TextSearchIcon;
        const ImVec2 label_size = ImGui::CalcTextSize(into_u8(ICON_SEARCH).c_str(), nullptr, true);
        const ImVec2 search_icon_pos(ImGui::GetItemRectMax().x - label_size.x, popup_window->DC.CursorPos.y + style.FramePadding.y);
        ImGui::RenderText(search_icon_pos, into_u8(ICON_SEARCH).c_str());
        auto temp = popup_window->DC.CursorPos;
        popup_window->DC.CursorPos = search_icon_pos;
        ImGui::PushStyleColor(ImGuiCol_Button, {0, 0, 0, 0});
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImGui::GetStyleColorVec4(ImGuiCol_Button));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImGui::GetStyleColorVec4(ImGuiCol_Button));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImGui::GetStyleColorVec4(ImGuiCol_Button));
        ImGui::PushStyleColor(ImGuiCol_Border, { 0, 0, 0, 0 });
        if (button("##invisible_clear_button", label_size.x, label_size.y))
        {
            if (*pattern_buffer != '\0')
                memset(pattern_buffer, 0, IM_ARRAYSIZE(pattern_buffer));
        }
        ImGui::PopStyleColor(5);
        popup_window->DC.CursorPos = temp;
        ImGui::PushItemWidth(item_rect_width);
        if (is_new_open)
            ImGui::SetKeyboardFocusHere();
        ImGui::InputText("##bbl_combo_with_filter_inputText", pattern_buffer, sizeof(pattern_buffer));
        ImGui::PopItemWidth();
        ImGui::PopStyleVar();
        if (*pattern_buffer != '\0')
            is_filtering = true;
        if (is_filtering)
        {
            std::vector<std::pair<int, int> > filtered_items_with_priority;// std::pair<index, priority>
            for (int i = 0; i < all_items.size(); i++)
            {
                int priority = simple_match(pattern_buffer, all_items[i].c_str());
                if (priority != wxNOT_FOUND)
                    filtered_items_with_priority.push_back({ i, priority });
            }
            std::sort(filtered_items_with_priority.begin(), filtered_items_with_priority.end(), [](const std::pair<int, int>& a, const std::pair<int, int>& b) {return (b.second > a.second); });
            for (auto item : filtered_items_with_priority)
            {
                filtered_items_idx->push_back(item.first);
            }
        }
        *is_filtered = is_filtering;
        popup_window->DC.CursorPos.y -= 1 * m_style_scaling;
        ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(1.0f, 1.0f) * m_style_scaling);
        if (ImGui::BeginListBox("##bbl_combo_with_filter_listBox", { item_rect_width, item_rect_height * 7.75f})) {
            ImGui::PopStyleVar(2);
            return true;
        }
        else
        {
            ImGui::PopStyleVar(2);
            ImGui::EndPopup();
            return false;
        }
    }
    else
        return false;
}
References ImGui::BBLRenderArrow(), ImGui::BeginListBox(), ImGui::BeginPopup(), button(), ImGuiStyle::ButtonTextAlign, ImGui::CalcItemWidth(), ImGui::CalcTextSize(), ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGuiWindow::DrawList, ImGui::EndPopup(), ImGuiContext::FontSize, ImGui::GetColorU32(), ImGui::GetCurrentWindow(), ImGui::GetFrameHeight(), ImGui::GetItemRectMax(), ImGui::GetItemRectSize(), ImGui::GetStyleColorVec4(), GImGui, IM_ARRAYSIZE, ImGuiCol_Border, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiDir_Down, ImGuiStyleVar_FramePadding, ImGuiStyleVar_ItemSpacing, ImMax(), ImGui::InputText(), Slic3r::GUI::into_u8(), m_style_scaling, memset, ImRect::Min, ImGui::OpenPopup(), ImGui::PopItemWidth(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushItemWidth(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::RenderText(), ImGui::SetKeyboardFocusHere(), ImGui::SetNextWindowPos(), ImGui::SetNextWindowSize(), ImGuiWindow::SkipItems, ImGuiContext::Style, style, ImGui::TextSearchCloseIcon, ImGui::TextSearchIcon, ImVec2::x, and ImVec2::y.
Referenced by Slic3r::GUI::GLGizmoText::on_render_input_window().
bbl_input_double()
bool Slic3r::GUI::ImGuiWrapper::bbl_input_double (const wxString & label, const double & value, const std::string & format = "%0.2f")
{
    //return ImGui::InputDouble(label.c_str(), const_cast<double *>(&value), 0.0f, 0.0f, format.c_str(), ImGuiInputTextFlags_CharsDecimal);
    return ImGui::InputDouble(label.c_str(), const_cast<double *>(&value), 0.0f, 0.0f, format.c_str(), ImGuiInputTextFlags_CharsDecimal);
}
References Slic3r::GUI::format(), ImGuiInputTextFlags_CharsDecimal, and ImGui::InputDouble().
bbl_radio_button()
bool Slic3r::GUI::ImGuiWrapper::bbl_radio_button (const char * label, bool active)
{
    bool result;
    bool b_value = active;
    if (b_value) {
        ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));
        ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));
        ImGui::PushStyleColor(ImGuiCol_FrameBgActive, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));
    }
    result = ImGui::BBLRadioButton(label,active);
    if (b_value) { ImGui::PopStyleColor(3); }
    return result;
}
References ImGui::BBLRadioButton(), ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGui::PopStyleColor(), and ImGui::PushStyleColor().
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
bbl_slider_float()
bool Slic3r::GUI::ImGuiWrapper::bbl_slider_float (const std::string & label, float * v, float v_min, float v_max, const char * format = "%.3f", float power = 1.0f, bool clamp = true, const wxString & tooltip = {})
{
    const float max_tooltip_width = ImGui::GetFontSize() * 20.0f;
    // let the label string start with "##" to hide the automatic label from ImGui::SliderFloat()
    bool label_visible = !boost::algorithm::istarts_with(label, "##");
    std::string str_label = label_visible ? std::string("##") + std::string(label) : std::string(label);
    // removes 2nd evenience of "##", if present
    std::string::size_type pos = str_label.find("##", 2);
    if (pos != std::string::npos)
        str_label = str_label.substr(0, pos) + str_label.substr(pos + 2);
    bool ret = ImGui::BBLSliderFloat(str_label.c_str(), v, v_min, v_max, format, power);
    m_last_slider_status.hovered = ImGui::IsItemHovered();
    m_last_slider_status.clicked = ImGui::IsItemClicked();
    m_last_slider_status.deactivated_after_edit = ImGui::IsItemDeactivatedAfterEdit();
    if (!tooltip.empty() && ImGui::IsItemHovered())
        this->tooltip(into_u8(tooltip).c_str(), max_tooltip_width);
    if (clamp)
        *v = std::clamp(*v, v_min, v_max);
    const ImGuiStyle& style = ImGui::GetStyle();
    if (label_visible) {
        // if the label is visible, hide the part of it that should be hidden
        std::string out_label = std::string(label);
        std::string::size_type pos = out_label.find("##");
        if (pos != std::string::npos)
            out_label = out_label.substr(0, pos);
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, { 1, style.ItemSpacing.y });
        ImGui::SameLine();
        this->text(out_label.c_str());
        ImGui::PopStyleVar();
    }
    return ret;
}
References ImGui::BBLSliderFloat(), clamp(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::clicked, Slic3r::GUI::ImGuiWrapper::LastSliderStatus::deactivated_after_edit, Slic3r::GUI::format(), ImGui::GetFontSize(), ImGui::GetStyle(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::hovered, ImGuiStyleVar_ItemSpacing, Slic3r::GUI::into_u8(), ImGui::IsItemClicked(), ImGui::IsItemDeactivatedAfterEdit(), ImGui::IsItemHovered(), m_last_slider_status, ImGui::PopStyleVar(), ImGui::PushStyleVar(), ImGui::SameLine(), style, text(), and tooltip().
Referenced by bbl_slider_float_style().
bbl_slider_float_style()
bool Slic3r::GUI::ImGuiWrapper::bbl_slider_float_style (const std::string & label, float * v, float v_min, float v_max, const char * format = "%.3f", float power = 1.0f, bool clamp = true, const wxString & tooltip = {})
{
    ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 0.0f);
    ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 0.00f));
    ImGui::PushStyleColor(ImGuiCol_FrameBgActive, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 0.00f));
    ImGui::PushStyleColor(ImGuiCol_SliderGrab, ImVec4(0.81f, 0.81f, 0.81f, 1.0f));
    ImGui::PushStyleColor(ImGuiCol_SliderGrabActive, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));
    bool ret = bbl_slider_float(label, v, v_min,v_max, format, power, clamp,tooltip);
    ImGui::PopStyleColor(4);
    ImGui::PopStyleVar(1);
    return ret;
}
References bbl_slider_float(), clamp(), Slic3r::GUI::format(), ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiStyleVar_FrameBorderSize, ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), and tooltip().
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLGizmoAdvancedCut::render_slider_double_input(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
bbl_sliderin()
bool Slic3r::GUI::ImGuiWrapper::bbl_sliderin (const char * label, int * v, int v_min, int v_max, const char * format = "%d", ImGuiSliderFlags flags = 0)
{
    return ImGui::BBLSliderScalarIn(label, ImGuiDataType_S32, v, &v_min, &v_max, format, flags);
}
References ImGui::BBLSliderScalarIn(), Slic3r::GUI::format(), and ImGuiDataType_S32.
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
begin() [1/4]
bool Slic3r::GUI::ImGuiWrapper::begin (const std::string & name, bool * close, int flags = 0)
{
    return ImGui::Begin(name.c_str(), close, (ImGuiWindowFlags)flags);
}
References ImGui::Begin().
begin() [2/4]
bool Slic3r::GUI::ImGuiWrapper::begin (const std::string & name, int flags = 0)
{
    return ImGui::Begin(name.c_str(), nullptr, (ImGuiWindowFlags)flags);
}
References ImGui::Begin().
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_assemble_info(), Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::_render_orient_menu(), Slic3r::GUI::GLCanvas3D::_render_paint_toolbar(), Slic3r::GUI::GLCanvas3D::_render_return_toolbar(), Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notification(), begin(), begin(), Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoBase::GizmoImguiBegin(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::GLCanvas3D::Tooltip::render(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::render(), Slic3r::GUI::NotificationManager::PopNotification::render(), Slic3r::GUI::IMSlider::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::PartPlate::render_label(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
begin() [3/4]
bool Slic3r::GUI::ImGuiWrapper::begin (const wxString & name, bool * close, int flags = 0)
{
    return begin(into_u8(name), close, flags);
}
References begin(), and Slic3r::GUI::into_u8().
begin() [4/4]
bool Slic3r::GUI::ImGuiWrapper::begin (const wxString & name, int flags = 0)
{
    return begin(into_u8(name), flags);
}
References begin(), and Slic3r::GUI::into_u8().
bold_text()
void Slic3r::GUI::ImGuiWrapper::bold_text (const std::string & str)
{
    if (bold_font){
        ImGui::PushFont(bold_font);
        text(str);
        ImGui::PopFont();
    } else {
        text(str);
    }
}
References bold_font, ImGui::PopFont(), ImGui::PushFont(), and text().
Referenced by Slic3r::GUI::GCodeViewer::render_all_plates_stats(), and Slic3r::GUI::GCodeViewer::render_legend().
button() [1/2]
bool Slic3r::GUI::ImGuiWrapper::button (const wxString & label)
{
    auto label_utf8 = into_u8(label);
    return ImGui::Button(label_utf8.c_str());
}
References ImGui::Button(), and Slic3r::GUI::into_u8().
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_orient_menu(), bbl_combo_with_filter(), Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notif_buttons(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::render_cancel_button(), Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_cancel_button(), Slic3r::GUI::NotificationManager::ProgressIndicatorNotification::render_cancel_button(), Slic3r::GUI::NotificationManager::PopNotification::render_close_button(), Slic3r::GUI::NotificationManager::HintNotification::render_close_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::NotificationManager::HintNotification::render_documentation_button(), Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_eject_button(), Slic3r::GUI::NotificationManager::PopNotification::render_hypertext(), Slic3r::GUI::NotificationManager::PopNotification::render_minimize_button(), Slic3r::GUI::NotificationManager::HintNotification::render_preferences_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_reset_button(), Slic3r::GUI::NotificationManager::HintNotification::render_right_arrow_button(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
button() [2/2]
bool Slic3r::GUI::ImGuiWrapper::button (const wxString & label, float width, float height)
{
    auto label_utf8 = into_u8(label);
    return ImGui::Button(label_utf8.c_str(), ImVec2(width, height));
}
References ImGui::Button(), and Slic3r::GUI::into_u8().
calc_button_size()
ImVec2 Slic3r::GUI::ImGuiWrapper::calc_button_size (const wxString & text, const ImVec2 & button_size = ImVec2(0, 0)) const
{
    const ImVec2        text_size = this->calc_text_size(text);
    const ImGuiContext &g         = *GImGui;
    const ImGuiStyle   &style     = g.Style;
    return ImGui::CalcItemSize(button_size, text_size.x + style.FramePadding.x * 2.0f, text_size.y + style.FramePadding.y * 2.0f);
}
References calc_text_size(), ImGui::CalcItemSize(), GImGui, ImGuiContext::Style, style, ImVec2::x, and ImVec2::y.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
calc_text_size()
ImVec2 Slic3r::GUI::ImGuiWrapper::calc_text_size (const wxString & text, float wrap_width = -1.0f) const
{
    auto text_utf8 = into_u8(text);
    ImVec2 size = ImGui::CalcTextSize(text_utf8.c_str(), NULL, false, wrap_width);
/*#ifdef __linux__
    size.x *= m_style_scaling;
    size.y *= m_style_scaling;
#endif*/
    return size;
}
References ImGui::CalcTextSize(), Slic3r::GUI::into_u8(), NULL, size, and text().
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_assemble_info(), calc_button_size(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::PartPlate::render_label(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLCanvas3D::LayersEditing::show_tooltip_information(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::show_tooltip_information().
checkbox()
bool Slic3r::GUI::ImGuiWrapper::checkbox (const wxString & label, bool & value)
{
    auto label_utf8 = into_u8(label);
    return ImGui::Checkbox(label_utf8.c_str(), &value);
}
References ImGui::Checkbox(), and Slic3r::GUI::into_u8().
Referenced by Slic3r::GUI::GLCanvas3D::_render_orient_menu(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), and search_list().
clipboard_get()
const char * Slic3r::GUI::ImGuiWrapper::clipboard_get (void * user_data) static private
{
    ImGuiWrapper *self = reinterpret_cast<ImGuiWrapper*>(user_data);
    const char* res = "";
    if (wxTheClipboard->Open()) {
        if (wxTheClipboard->IsSupported(wxDF_TEXT)) {
            wxTextDataObject data;
            wxTheClipboard->GetData(data);
            if (data.GetTextLength() > 0) {
                self->m_clipboard_text = into_u8(data.GetText());
                res = self->m_clipboard_text.c_str();
            }
        }
        wxTheClipboard->Close();
    }
    return res;
}
References Slic3r::GUI::into_u8(), and m_clipboard_text.
Referenced by init_input().
clipboard_set()
void Slic3r::GUI::ImGuiWrapper::clipboard_set (void * user_data, const char * text) static private
{
    if (wxTheClipboard->Open()) {
        wxTheClipboard->SetData(new wxTextDataObject(wxString::FromUTF8(text)));   // object owned by the clipboard
        wxTheClipboard->Close();
    }
}
References text().
Referenced by init_input().
combo()
bool Slic3r::GUI::ImGuiWrapper::combo (const wxString & label, const std::vector< std::string > & options, int & selection)
{
    // this is to force the label to the left of the widget:
    text(label);
    ImGui::SameLine();
    int selection_out = selection;
    bool res = false;
    const char *selection_str = selection < int(options.size()) && selection >= 0 ? options[selection].c_str() : "";
    if (ImGui::BeginCombo("", selection_str)) {
        for (int i = 0; i < (int)options.size(); i++) {
            if (ImGui::Selectable(options[i].c_str(), i == selection)) {
                selection_out = i;
            }
        }
        ImGui::EndCombo();
        res = true;
    }
    selection = selection_out;
    return res;
}
References ImGui::BeginCombo(), ImGui::EndCombo(), int, ImGui::SameLine(), ImGui::Selectable(), and text().
destroy_font()
void Slic3r::GUI::ImGuiWrapper::destroy_font () private
{
    if (m_font_texture != 0) {
        ImGuiIO& io = ImGui::GetIO();
        io.Fonts->TexID = 0;
        glsafe(::glDeleteTextures(1, &m_font_texture));
        m_font_texture = 0;
    }
}
References ImGuiIO::Fonts, ImGui::GetIO(), glsafe, m_font_texture, and ImFontAtlas::TexID.
Referenced by ~ImGuiWrapper(), init_font(), set_language(), and set_scaling().
destroy_fonts_texture()
void Slic3r::GUI::ImGuiWrapper::destroy_fonts_texture ()
{
    //if (m_font_another_texture != 0) {
    //    if (m_new_frame_open) {
    //        render();
    //    }
    //    init_font(true);
    //    glsafe(::glDeleteTextures(1, &m_font_another_texture));
    //    m_font_another_texture = 0;
    //    if (!m_new_frame_open) {
    //        new_frame();
    //    }
    //}
}
disabled_begin()
void Slic3r::GUI::ImGuiWrapper::disabled_begin (bool disabled)
{
    wxCHECK_RET(!m_disabled, "ImGUI: Unbalanced disabled_begin() call");
    if (disabled) {
        ImGui::PushItemFlag(ImGuiItemFlags_Disabled, true);
        ImGui::PushStyleVar(ImGuiStyleVar_Alpha, ImGui::GetStyle().Alpha * 0.5f);
        m_disabled = true;
    }
}
References ImGui::GetStyle(), ImGuiItemFlags_Disabled, ImGuiStyleVar_Alpha, m_disabled, ImGui::PushItemFlag(), and ImGui::PushStyleVar().
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), and Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window().
disabled_end()
void Slic3r::GUI::ImGuiWrapper::disabled_end ()
{
    if (m_disabled) {
        ImGui::PopItemFlag();
        ImGui::PopStyleVar();
        m_disabled = false;
    }
}
References m_disabled, ImGui::PopItemFlag(), and ImGui::PopStyleVar().
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::RotoptimzeWindow(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), and Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window().
display_initialized()
bool Slic3r::GUI::ImGuiWrapper::display_initialized () const private
{
    const ImGuiIO& io = ImGui::GetIO();
    return io.DisplaySize.x >= 0.0f && io.DisplaySize.y >= 0.0f;
}
References ImGuiIO::DisplaySize, ImGui::GetIO(), ImVec2::x, and ImVec2::y.
Referenced by update_key_data(), and update_mouse_data().
end()
void Slic3r::GUI::ImGuiWrapper::end ()
{
    ImGui::End();
}
References ImGui::End().
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_assemble_info(), Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::_render_orient_menu(), Slic3r::GUI::GLCanvas3D::_render_paint_toolbar(), Slic3r::GUI::GLCanvas3D::_render_return_toolbar(), Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notification(), Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::GLCanvas3D::Tooltip::render(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::render(), Slic3r::GUI::NotificationManager::PopNotification::render(), Slic3r::GUI::IMSlider::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::PartPlate::render_label(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
get_font_size()
float Slic3r::GUI::ImGuiWrapper::get_font_size () const inline
{ return m_font_size; }
References m_font_size.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), Slic3r::GUI::GLGizmoText::on_init(), and Slic3r::GUI::GLGizmoText::on_render_input_window().
get_fonts_names()
const std::vector< std::string > Slic3r::GUI::ImGuiWrapper::get_fonts_names () const inline
{ return m_fonts_names; }
References m_fonts_names.
get_item_spacing()
ImVec2 Slic3r::GUI::ImGuiWrapper::get_item_spacing () const
{
    const ImGuiContext &g     = *GImGui;
    const ImGuiStyle   &style = g.Style;
    return style.ItemSpacing;
}
References GImGui, ImGuiContext::Style, and style.
Referenced by Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), and Slic3r::GUI::GCodeViewer::SequentialView::Marker::render().
get_last_slider_status()
const LastSliderStatus & Slic3r::GUI::ImGuiWrapper::get_last_slider_status () const inline
{ return m_last_slider_status; }
References m_last_slider_status.
Referenced by Slic3r::GUI::GLGizmoHollow::on_render_input_window(), and Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window().
get_slider_float_height()
float Slic3r::GUI::ImGuiWrapper::get_slider_float_height () const
{
    const ImGuiContext& g = *GImGui;
    const ImGuiStyle& style = g.Style;
    return g.FontSize + style.FramePadding.y * 2.0f + style.ItemSpacing.y;
}
References ImGuiContext::FontSize, GImGui, ImGuiContext::Style, and style.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window().
get_style_scaling()
float Slic3r::GUI::ImGuiWrapper::get_style_scaling () const inline
{ return m_style_scaling; }
References m_style_scaling.
Referenced by Slic3r::GUI::GLCanvas3D::_render_assemble_info(), Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), and Slic3r::GUI::Mouse3DController::render_settings_dialog().
image_button()
bool Slic3r::GUI::ImGuiWrapper::image_button ()
{
    return false;
}
init_font()
void Slic3r::GUI::ImGuiWrapper::init_font (bool compress) private
{
    destroy_font();
    ImGuiIO& io = ImGui::GetIO();
    io.Fonts->Clear();
    // Create ranges of characters from m_glyph_ranges, possibly adding some OS specific special characters.
    ImVector<ImWchar> ranges;
    ImVector<ImWchar> basic_ranges;
    ImFontAtlas::GlyphRangesBuilder builder;
    builder.AddRanges(m_glyph_ranges);
#ifdef __APPLE__
    if (m_font_cjk)
        // Apple keyboard shortcuts are only contained in the CJK fonts.
        builder.AddRanges(ranges_keyboard_shortcuts);
#endif
    builder.BuildRanges(&ranges); // Build the final result (ordered ranges with all the unique characters submitted)
    io.Fonts->Flags |= ImFontAtlasFlags_NoPowerOfTwoHeight;
    ImFontConfig cfg = ImFontConfig();
    cfg.OversampleH = cfg.OversampleV = 1;
    //FIXME replace with io.Fonts->AddFontFromMemoryTTF(buf_decompressed_data, (int)buf_decompressed_size, m_font_size, nullptr, ranges.Data);
    //https://github.com/ocornut/imgui/issues/220
    // Orca: temp fix for Korean font
    auto font_name_regular = "HarmonyOS_Sans_SC_Regular.ttf";
    auto font_name_bold = "HarmonyOS_Sans_SC_Bold.ttf";
    if(m_glyph_ranges == ImGui::GetIO().Fonts->GetGlyphRangesKorean()) {
        font_name_regular = "NotoSansKR-Regular.otf";
        font_name_bold = "NotoSansKR-Bold.otf";
    }
    default_font = io.Fonts->AddFontFromFileTTF((Slic3r::resources_dir() + "/fonts/" + font_name_regular).c_str(), m_font_size, &cfg, ranges.Data);
    if (default_font == nullptr) {
        default_font = io.Fonts->AddFontDefault();
        if (default_font == nullptr) {
            throw Slic3r::RuntimeError("ImGui: Could not load deafult font");
        }
    }
    bold_font        = io.Fonts->AddFontFromFileTTF((Slic3r::resources_dir() + "/fonts/" + font_name_bold).c_str(), m_font_size, &cfg, ranges.Data);
    if (bold_font == nullptr) {
        bold_font = io.Fonts->AddFontDefault();
        if (bold_font == nullptr) { throw Slic3r::RuntimeError("ImGui: Could not load deafult font"); }
    }
#ifdef __APPLE__
    ImFontConfig config;
    config.MergeMode = true;
    if (! m_font_cjk) {
        // Apple keyboard shortcuts are only contained in the CJK fonts.
        [[maybe_unused]]ImFont *font_cjk = io.Fonts->AddFontFromFileTTF((Slic3r::resources_dir() + "/fonts/HarmonyOS_Sans_SC_Regular.ttf").c_str(), m_font_size, &config, ranges_keyboard_shortcuts);
        assert(font_cjk != nullptr);
    }
#endif
    float font_scale = m_font_size/15;
    int icon_sz = lround(16 * font_scale); // default size of icon is 16 px
    int rect_id = io.Fonts->CustomRects.Size;  // id of the rectangle added next
    // add rectangles for the icons to the font atlas
    for (auto& icon : font_icons)
        io.Fonts->AddCustomRectFontGlyph(default_font, icon.first, icon_sz, icon_sz, 3.0 * font_scale + icon_sz);
    for (auto& icon : font_icons_large)
        io.Fonts->AddCustomRectFontGlyph(default_font, icon.first, icon_sz * 2, icon_sz * 2, 3.0 * font_scale + icon_sz * 2);
    for (auto& icon : font_icons_extra_large)
        io.Fonts->AddCustomRectFontGlyph(default_font, icon.first, icon_sz * 4, icon_sz * 4, 3.0 * font_scale + icon_sz * 4);
    // Build texture atlas
    unsigned char* pixels;
    int width, height;
    io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height);   // Load as RGBA 32-bits (75% of the memory is wasted, but default font is so small) because it is more likely to be compatible with user's existing shaders. If your ImTextureId represent a higher-level concept than just a GL texture id, consider calling GetTexDataAsAlpha8() instead to save on GPU memory.
    BOOST_LOG_TRIVIAL(trace) << "Build default font texture done. width: " << width << ", height: " << height;
    // Fill rectangles from the SVG-icons
    for (auto icon : font_icons) {
        if (const ImFontAtlas::CustomRect* rect = io.Fonts->GetCustomRectByIndex(rect_id)) {
            assert(rect->Width == icon_sz);
            assert(rect->Height == icon_sz);
            unsigned outwidth, outheight;
            std::vector<unsigned char> raw_data = load_svg(icon.second, icon_sz, icon_sz, &outwidth, &outheight);
            const ImU32* pIn = (ImU32*)raw_data.data();
            for (unsigned y = 0; y < outheight; y++) {
                ImU32* pOut = (ImU32*)pixels + (rect->Y + y) * width + (rect->X);
                for (unsigned x = 0; x < outwidth; x++)
                    *pOut++ = *pIn++;
            }
        }
        rect_id++;
    }
    icon_sz *= 2; // default size of large icon is 32 px
    for (auto icon : font_icons_large) {
        if (const ImFontAtlas::CustomRect* rect = io.Fonts->GetCustomRectByIndex(rect_id)) {
            assert(rect->Width == icon_sz);
            assert(rect->Height == icon_sz);
            unsigned outwidth, outheight;
            std::vector<unsigned char> raw_data = load_svg(icon.second, icon_sz, icon_sz, &outwidth, &outheight);
            const ImU32* pIn = (ImU32*)raw_data.data();
            for (unsigned y = 0; y < outheight; y++) {
                ImU32* pOut = (ImU32*)pixels + (rect->Y + y) * width + (rect->X);
                for (unsigned x = 0; x < outwidth; x++)
                    *pOut++ = *pIn++;
            }
        }
        rect_id++;
    }
    icon_sz *= 2; // default size of extra large icon is 64 px
    for (auto icon : font_icons_extra_large) {
        if (const ImFontAtlas::CustomRect* rect = io.Fonts->GetCustomRectByIndex(rect_id)) {
            assert(rect->Width == icon_sz);
            assert(rect->Height == icon_sz);
            unsigned outwidth, outheight;
            std::vector<unsigned char> raw_data = load_svg(icon.second, icon_sz, icon_sz, &outwidth, &outheight);
            const ImU32* pIn = (ImU32*)raw_data.data();
            for (unsigned y = 0; y < outheight; y++) {
                ImU32* pOut = (ImU32*)pixels + (rect->Y + y) * width + (rect->X);
                for (unsigned x = 0; x < outwidth; x++)
                    *pOut++ = *pIn++;
            }
        }
        rect_id++;
    }
    // Upload texture to graphics system
    GLint last_texture;
    glsafe(::glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture));
    glsafe(::glGenTextures(1, &m_font_texture));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_font_texture));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
    glsafe(::glPixelStorei(GL_UNPACK_ROW_LENGTH, 0));
    if (compress && GLEW_EXT_texture_compression_s3tc)
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels));
    else
        glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels));
    // Store our identifier
    io.Fonts->TexID = (ImTextureID)(intptr_t)m_font_texture;
    // Restore state
    glsafe(::glBindTexture(GL_TEXTURE_2D, last_texture));
}
References ImFontAtlas::AddCustomRectFontGlyph(), ImFontAtlas::AddFontDefault(), ImFontAtlas::AddFontFromFileTTF(), ImFontGlyphRangesBuilder::AddRanges(), bold_font, ImFontGlyphRangesBuilder::BuildRanges(), ImFontAtlas::Clear(), compress, ImFontAtlas::CustomRects, ImVector< T >::Data, default_font, destroy_font(), ImFontAtlas::Flags, Slic3r::GUI::font_icons, Slic3r::GUI::font_icons_extra_large, Slic3r::GUI::font_icons_large, ImGuiIO::Fonts, ImFontAtlas::GetCustomRectByIndex(), ImGui::GetIO(), ImFontAtlas::GetTexDataAsRGBA32(), glsafe, ImFontAtlasFlags_NoPowerOfTwoHeight, load_svg(), m_font_cjk, m_font_size, m_font_texture, m_glyph_ranges, ImFontConfig::MergeMode, ImFontConfig::OversampleH, ImFontConfig::OversampleV, Slic3r::resources_dir(), ImVector< T >::Size, ImFontAtlas::TexID, and Slic3r::trace().
Referenced by new_frame().
init_input()
void Slic3r::GUI::ImGuiWrapper::init_input () private
{
    ImGuiIO& io = ImGui::GetIO();
    // Keyboard mapping. ImGui will use those indices to peek into the io.KeysDown[] array.
    io.KeyMap[ImGuiKey_Tab] = WXK_TAB;
    io.KeyMap[ImGuiKey_LeftArrow] = WXK_LEFT;
    io.KeyMap[ImGuiKey_RightArrow] = WXK_RIGHT;
    io.KeyMap[ImGuiKey_UpArrow] = WXK_UP;
    io.KeyMap[ImGuiKey_DownArrow] = WXK_DOWN;
    io.KeyMap[ImGuiKey_PageUp] = WXK_PAGEUP;
    io.KeyMap[ImGuiKey_PageDown] = WXK_PAGEDOWN;
    io.KeyMap[ImGuiKey_Home] = WXK_HOME;
    io.KeyMap[ImGuiKey_End] = WXK_END;
    io.KeyMap[ImGuiKey_Insert] = WXK_INSERT;
    io.KeyMap[ImGuiKey_Delete] = WXK_DELETE;
    io.KeyMap[ImGuiKey_Backspace] = WXK_BACK;
    io.KeyMap[ImGuiKey_Space] = WXK_SPACE;
    io.KeyMap[ImGuiKey_Enter] = WXK_RETURN;
    io.KeyMap[ImGuiKey_KeyPadEnter] = WXK_NUMPAD_ENTER;
    io.KeyMap[ImGuiKey_Escape] = WXK_ESCAPE;
    io.KeyMap[ImGuiKey_A] = 'A';
    io.KeyMap[ImGuiKey_C] = 'C';
    io.KeyMap[ImGuiKey_V] = 'V';
    io.KeyMap[ImGuiKey_X] = 'X';
    io.KeyMap[ImGuiKey_Y] = 'Y';
    io.KeyMap[ImGuiKey_Z] = 'Z';
    // Don't let imgui special-case Mac, wxWidgets already do that
    io.ConfigMacOSXBehaviors = false;
    // Setup clipboard interaction callbacks
    io.SetClipboardTextFn = clipboard_set;
    io.GetClipboardTextFn = clipboard_get;
    io.ClipboardUserData = this;
}
References clipboard_get(), clipboard_set(), ImGuiIO::ClipboardUserData, ImGuiIO::ConfigMacOSXBehaviors, ImGuiIO::GetClipboardTextFn, ImGui::GetIO(), ImGuiKey_A, ImGuiKey_Backspace, ImGuiKey_C, ImGuiKey_Delete, ImGuiKey_DownArrow, ImGuiKey_End, ImGuiKey_Enter, ImGuiKey_Escape, ImGuiKey_Home, ImGuiKey_Insert, ImGuiKey_KeyPadEnter, ImGuiKey_LeftArrow, ImGuiKey_PageDown, ImGuiKey_PageUp, ImGuiKey_RightArrow, ImGuiKey_Space, ImGuiKey_Tab, ImGuiKey_UpArrow, ImGuiKey_V, ImGuiKey_X, ImGuiKey_Y, ImGuiKey_Z, ImGuiIO::KeyMap, and ImGuiIO::SetClipboardTextFn.
Referenced by ImGuiWrapper().
init_style()
void Slic3r::GUI::ImGuiWrapper::init_style () private
{
    ImGuiStyle &style = ImGui::GetStyle();
    auto set_color = [&](ImGuiCol_ entity, ImVec4 color) {
        style.Colors[entity] = color;
    };
    //BBS modify style
    // Window
    style.WindowRounding = 0.0f;
    set_color(ImGuiCol_WindowBg, COL_WINDOW_BACKGROUND);
    set_color(ImGuiCol_TitleBgActive, COL_WINDOW_BACKGROUND);
    // Generics
    set_color(ImGuiCol_FrameBg, COL_GREY_DARK);
    set_color(ImGuiCol_FrameBgHovered, COL_GREY_LIGHT);
    set_color(ImGuiCol_FrameBgActive, COL_GREY_LIGHT);
    // Text selection
    set_color(ImGuiCol_TextSelectedBg, COL_ORANGE_DARK);
    // Buttons
    set_color(ImGuiCol_Button, COL_BUTTON_BACKGROUND);
    set_color(ImGuiCol_ButtonHovered, COL_HOVER);
    set_color(ImGuiCol_ButtonActive, COL_ACTIVE);
    // Checkbox
    set_color(ImGuiCol_CheckMark, COL_BLUE_LIGHT);
    // ComboBox items
    set_color(ImGuiCol_Header, COL_ORANGE_DARK);
    set_color(ImGuiCol_HeaderHovered, COL_BLUE_LIGHT);
    set_color(ImGuiCol_HeaderActive, COL_BLUE_LIGHT);
    // Slider
    set_color(ImGuiCol_SliderGrab, COL_BLUE_LIGHT);
    set_color(ImGuiCol_SliderGrabActive, COL_BLUE_LIGHT);
    // Separator
    set_color(ImGuiCol_Separator, COL_BLUE_LIGHT);
    // Tabs
    set_color(ImGuiCol_Tab, COL_ORANGE_DARK);
    set_color(ImGuiCol_TabHovered, COL_BLUE_LIGHT);
    set_color(ImGuiCol_TabActive, COL_BLUE_LIGHT);
    set_color(ImGuiCol_TabUnfocused, COL_GREY_DARK);
    set_color(ImGuiCol_TabUnfocusedActive, COL_GREY_LIGHT);
    // Scrollbars
    set_color(ImGuiCol_ScrollbarGrab, COL_ORANGE_DARK);
    set_color(ImGuiCol_ScrollbarGrabHovered, COL_ORANGE_LIGHT);
    set_color(ImGuiCol_ScrollbarGrabActive, COL_ORANGE_LIGHT);
}
References COL_ACTIVE, COL_BLUE_LIGHT, COL_BUTTON_BACKGROUND, COL_GREY_DARK, COL_GREY_LIGHT, COL_HOVER, COL_ORANGE_DARK, COL_ORANGE_LIGHT, COL_WINDOW_BACKGROUND, ImGui::GetStyle(), ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiCol_ScrollbarGrab, ImGuiCol_ScrollbarGrabActive, ImGuiCol_ScrollbarGrabHovered, ImGuiCol_Separator, ImGuiCol_SliderGrab, ImGuiCol_SliderGrabActive, ImGuiCol_Tab, ImGuiCol_TabActive, ImGuiCol_TabHovered, ImGuiCol_TabUnfocused, ImGuiCol_TabUnfocusedActive, ImGuiCol_TextSelectedBg, ImGuiCol_TitleBgActive, ImGuiCol_WindowBg, and style.
Referenced by ImGuiWrapper().
input_double() [1/2]
bool Slic3r::GUI::ImGuiWrapper::input_double (const std::string & label, const double & value, const std::string & format = "%.3f")
{
    return ImGui::InputDouble(label.c_str(), const_cast<double*>(&value), 0.0f, 0.0f, format.c_str(), ImGuiInputTextFlags_CharsDecimal);
}
References Slic3r::GUI::format(), ImGuiInputTextFlags_CharsDecimal, and ImGui::InputDouble().
Referenced by input_double().
input_double() [2/2]
bool Slic3r::GUI::ImGuiWrapper::input_double (const wxString & label, const double & value, const std::string & format = "%.3f")
{
    auto label_utf8 = into_u8(label);
    return input_double(label_utf8, value, format);
}
References Slic3r::GUI::format(), input_double(), and Slic3r::GUI::into_u8().
input_vec3()
bool Slic3r::GUI::ImGuiWrapper::input_vec3 (const std::string & label, const Vec3d & value, float width, const std::string & format = "%.3f")
{
    bool value_changed = false;
    ImGui::BeginGroup();
    for (int i = 0; i < 3; ++i)
    {
        std::string item_label = (i == 0) ? "X" : ((i == 1) ? "Y" : "Z");
        ImGui::PushID(i);
        ImGui::PushItemWidth(width);
        value_changed |= ImGui::InputDouble(item_label.c_str(), const_cast<double*>(&value(i)), 0.0f, 0.0f, format.c_str());
        ImGui::PopID();
    }
    ImGui::EndGroup();
    return value_changed;
}
References ImGui::BeginGroup(), ImGui::EndGroup(), Slic3r::GUI::format(), ImGui::InputDouble(), ImGui::PopID(), ImGui::PushID(), and ImGui::PushItemWidth().
load_fonts_texture()
void Slic3r::GUI::ImGuiWrapper::load_fonts_texture ()
{
    //if (m_font_another_texture == 0) {
    //    ImGuiIO& io = ImGui::GetIO();
    //    io.Fonts->Flags |= ImFontAtlasFlags_NoPowerOfTwoHeight;
    //    ImFontConfig cfg = ImFontConfig();
    //    cfg.OversampleH = cfg.OversampleV = 1;
    //    std::map<std::string, std::string> sys_fonts_map = get_occt_fonts_maps(); // map<font name, font path>
    //    im_fonts_map.clear();                                                     // map<font name, ImFont*>
    //    BOOST_LOG_TRIVIAL(info) << "init_im_font start";
    //    for (auto sys_font : sys_fonts_map) {
    //        boost::filesystem::path font_path(sys_font.second);
    //        if (!boost::filesystem::exists(font_path)) {
    //            BOOST_LOG_TRIVIAL(trace) << "load font = " << sys_font.first << ", path = " << font_path << " is not exists";
    //            continue;
    //        }
    //        ImFont* im_font = io.Fonts->AddFontFromFileTTF(sys_font.second.c_str(), m_font_size, &cfg, ImGui::GetIO().Fonts->GetGlyphRangesBasic());
    //        if (im_font == nullptr) {
    //            BOOST_LOG_TRIVIAL(trace) << "load font = " << sys_font.first << " failed, path = " << font_path << " is not exists";
    //            continue;
    //        }
    //        im_fonts_map.insert({ sys_font.first, im_font });
    //    }
    //    BOOST_LOG_TRIVIAL(info) << "init_im_font end";
    //    unsigned char* pixels;
    //    int            width, height;
    //    io.Fonts->GetTexDataAsRGBA32(&pixels, &width, &height);
    //    BOOST_LOG_TRIVIAL(trace) << "Build system fonts texture done. width: " << width << ", height: " << height;
    //    if (m_fonts_names.size() == 0) {
    //        std::vector<std::string> to_delete_fonts;
    //        for (auto im_font : im_fonts_map) {
    //            if (im_font.second->Glyphs.Size < 4) { to_delete_fonts.push_back(im_font.first); }
    //        }
    //        for (auto to_delete_font : to_delete_fonts) {
    //            sys_fonts_map.erase(to_delete_font);
    //            im_fonts_map.erase(to_delete_font);
    //        }
    //        for (auto im_font : im_fonts_map) m_fonts_names.push_back(im_font.first);
    //    }
    //    GLint last_texture;
    //    glsafe(::glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture));
    //    glsafe(::glGenTextures(1, &(m_font_another_texture)));
    //    glsafe(::glBindTexture(GL_TEXTURE_2D, m_font_another_texture));
    //    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
    //    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
    //    glsafe(::glPixelStorei(GL_UNPACK_ROW_LENGTH, 0));
    //    glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_COMPRESSED_RGBA_S3TC_DXT5_EXT, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels));
    //    // Store our identifier
    //    io.Fonts->TexID = (ImTextureID)(intptr_t)m_font_another_texture;
    //    // Restore state
    //    glsafe(::glBindTexture(GL_TEXTURE_2D, last_texture));
    //}
}
load_svg()
std::vector< unsigned char > Slic3r::GUI::ImGuiWrapper::load_svg (const std::string & bitmap_name, unsigned target_width, unsigned target_height, unsigned * outwidth, unsigned * outheight) private
{
    std::vector<unsigned char> empty_vector;
    NSVGimage* image = BitmapCache::nsvgParseFromFileWithReplace(Slic3r::var(bitmap_name + ".svg").c_str(), "px", 96.0f, { { "\"#808080\"", "\"#FFFFFF\"" } });
    if (image == nullptr)
        return empty_vector;
    float svg_scale = target_height != 0 ?
        (float)target_height / image->height : target_width != 0 ?
        (float)target_width / image->width : 1;
    int   width = (int)(svg_scale * image->width + 0.5f);
    int   height = (int)(svg_scale * image->height + 0.5f);
    int   n_pixels = width * height;
    if (n_pixels <= 0) {
        ::nsvgDelete(image);
        return empty_vector;
    }
    NSVGrasterizer* rast = ::nsvgCreateRasterizer();
    if (rast == nullptr) {
        ::nsvgDelete(image);
        return empty_vector;
    }
    std::vector<unsigned char> data(n_pixels * 4, 0);
    ::nsvgRasterize(rast, image, 0, 0, svg_scale, data.data(), width, height, width * 4);
    ::nsvgDeleteRasterizer(rast);
    ::nsvgDelete(image);
    *outwidth = width;
    *outheight = height;
    return data;
}
References NSVGimage::height, int, nsvgCreateRasterizer(), nsvgDelete(), nsvgDeleteRasterizer(), Slic3r::GUI::BitmapCache::nsvgParseFromFileWithReplace(), nsvgRasterize(), Slic3r::var(), and NSVGimage::width.
Referenced by init_font().
new_frame()
void Slic3r::GUI::ImGuiWrapper::new_frame ()
{
    if (m_new_frame_open) {
        return;
    }
    if (m_font_texture == 0) {
        init_font(true);
    }
    ImGui::NewFrame();
    m_new_frame_open = true;
}
References init_font(), m_font_texture, m_new_frame_open, and ImGui::NewFrame().
Referenced by update_key_data(), and update_mouse_data().
on_change_color_mode()
void Slic3r::GUI::ImGuiWrapper::on_change_color_mode (bool is_dark) static
{
    m_is_dark_mode = is_dark;
}
References Slic3r::GUI::m_is_dark_mode.
pop_bold_font()
bool Slic3r::GUI::ImGuiWrapper::pop_bold_font ()
{
    if (bold_font) {
        ImGui::PopFont();
        return true;
    }
    else {
        return false;
    }
}
References bold_font, and ImGui::PopFont().
Referenced by Slic3r::GUI::GLCanvas3D::_render_paint_toolbar().
pop_button_disable_style()
void Slic3r::GUI::ImGuiWrapper::pop_button_disable_style () static
{
    ImGui::PopStyleColor(3);
}
References ImGui::PopStyleColor().
Referenced by Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), and Slic3r::GUI::IMSlider::render_input_custom_gcode().
pop_cancel_button_style()
void Slic3r::GUI::ImGuiWrapper::pop_cancel_button_style () static
{
    ImGui::PopStyleColor(6);
}
References ImGui::PopStyleColor().
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), and Slic3r::GUI::IMSlider::render_input_custom_gcode().
pop_combo_style()
void Slic3r::GUI::ImGuiWrapper::pop_combo_style () static
{
    ImGui::PopStyleVar(2);
    ImGui::PopStyleColor(7);
}
References ImGui::PopStyleColor(), and ImGui::PopStyleVar().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window().
pop_common_window_style()
void Slic3r::GUI::ImGuiWrapper::pop_common_window_style () static
{
    ImGui::PopStyleColor(14);
    ImGui::PopStyleVar(5);
}
References ImGui::PopStyleColor(), and ImGui::PopStyleVar().
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
pop_confirm_button_style()
void Slic3r::GUI::ImGuiWrapper::pop_confirm_button_style () static
{
    ImGui::PopStyleColor(6);
}
References ImGui::PopStyleColor().
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), and Slic3r::GUI::IMSlider::render_input_custom_gcode().
pop_font_by_name()
bool Slic3r::GUI::ImGuiWrapper::pop_font_by_name (std::string font_name)
{
    auto sys_font = im_fonts_map.find(font_name);
    if (sys_font != im_fonts_map.end()) {
        ImGui::PopFont();
        return true;
    }
    return false;
}
References im_fonts_map, and ImGui::PopFont().
pop_menu_style()
void Slic3r::GUI::ImGuiWrapper::pop_menu_style () static
{
    ImGui::PopStyleColor(4);
    ImGui::PopStyleVar(3);
    ImGuiWrapper::pop_toolbar_style();
}
References pop_toolbar_style(), ImGui::PopStyleColor(), and ImGui::PopStyleVar().
Referenced by Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), Slic3r::GUI::IMSlider::render_input_custom_gcode(), and Slic3r::GUI::IMSlider::render_menu().
pop_toolbar_style()
void Slic3r::GUI::ImGuiWrapper::pop_toolbar_style () static
{
    // size in push toolbar style
    ImGui::PopStyleColor(16);
    ImGui::PopStyleVar(6);
}
References ImGui::PopStyleColor(), and ImGui::PopStyleVar().
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_assemble_info(), Slic3r::GUI::GLCanvas3D::_render_orient_menu(), Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), pop_menu_style(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
push_bold_font()
bool Slic3r::GUI::ImGuiWrapper::push_bold_font ()
{
    if (bold_font) {
        ImGui::PushFont(bold_font);
        return true;
    }
    else {
        return false;
    }
}
References bold_font, and ImGui::PushFont().
Referenced by Slic3r::GUI::GLCanvas3D::_render_paint_toolbar().
push_button_disable_style()
void Slic3r::GUI::ImGuiWrapper::push_button_disable_style () static
{
    if (m_is_dark_mode) {
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(54 / 255.f, 54 / 255.f, 60 / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(54 / 255.f, 54 / 255.f, 60 / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 0.4f));
    }
    else {
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(206.f / 255.f, 206.f / 255.f, 206.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(206.f / 255.f, 206.f / 255.f, 206.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 1.f));
    }
}
References ImGuiCol_Border, ImGuiCol_Button, ImGuiCol_Text, Slic3r::GUI::m_is_dark_mode, and ImGui::PushStyleColor().
Referenced by Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), and Slic3r::GUI::IMSlider::render_input_custom_gcode().
push_cancel_button_style()
void Slic3r::GUI::ImGuiWrapper::push_cancel_button_style () static
{
    if (m_is_dark_mode) {
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.f, 0.f, 0.f, 0.f));
        ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(1.f, 1.f, 1.f, 0.64f));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(73 / 255.f, 73 / 255.f, 78 / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(129 / 255.f, 129 / 255.f, 131 / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1.f, 1.f, 1.f, 0.64f));
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 0.64f));
    }
    else {
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(1.f, 1.f, 1.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(38 / 255.f, 46 / 255.f, 48 / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(238.f / 255.f, 238.f / 255.f, 238.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(206.f / 255.f, 206.f / 255.f, 206.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(0.f, 0.f, 0.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(38.f / 255.0f, 46.f / 255.0f, 48.f / 255.0f, 1.00f));
    }
}
References ImGuiCol_Border, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_Text, Slic3r::GUI::m_is_dark_mode, and ImGui::PushStyleColor().
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), and Slic3r::GUI::IMSlider::render_input_custom_gcode().
push_combo_style()
void Slic3r::GUI::ImGuiWrapper::push_combo_style (const float scale) static
{
    if (m_is_dark_mode) {
        ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 1.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f * scale);
        ImGui::PushStyleColor(ImGuiCol_PopupBg, ImGuiWrapper::COL_WINDOW_BG_DARK);
        ImGui::PushStyleColor(ImGuiCol_BorderActive, ImVec4(0.00f, 0.68f, 0.26f, 1.00f));
        ImGui::PushStyleColor(ImGuiCol_HeaderHovered, ImVec4(0.00f, 0.68f, 0.26f, 0.0f));
        ImGui::PushStyleColor(ImGuiCol_HeaderActive, ImVec4(0.00f, 0.68f, 0.26f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_Header, ImVec4(0.00f, 0.68f, 0.26f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_ScrollbarBg, ImGuiWrapper::COL_WINDOW_BG_DARK);
        ImGui::PushStyleColor(ImGuiCol_Button, {1.00f, 1.00f, 1.00f, 0.0f});
    } else {
        ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 1.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f * scale);
        ImGui::PushStyleColor(ImGuiCol_PopupBg, ImGuiWrapper::COL_WINDOW_BG);
        ImGui::PushStyleColor(ImGuiCol_BorderActive, ImVec4(0.00f, 0.68f, 0.26f, 1.00f));
        ImGui::PushStyleColor(ImGuiCol_HeaderHovered, ImVec4(0.00f, 0.68f, 0.26f, 0.5f));
        ImGui::PushStyleColor(ImGuiCol_HeaderActive, ImVec4(0.00f, 0.68f, 0.26f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_Header, ImVec4(0.00f, 0.68f, 0.26f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_ScrollbarBg, ImGuiWrapper::COL_WINDOW_BG);
        ImGui::PushStyleColor(ImGuiCol_Button, {1.00f, 1.00f, 1.00f, 0.0f});
    }
}
References COL_WINDOW_BG, COL_WINDOW_BG_DARK, ImGuiCol_BorderActive, ImGuiCol_Button, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiCol_PopupBg, ImGuiCol_ScrollbarBg, ImGuiStyleVar_FrameBorderSize, ImGuiStyleVar_FrameRounding, Slic3r::GUI::m_is_dark_mode, ImGui::PushStyleColor(), ImGui::PushStyleVar(), and scale().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window().
push_common_window_style()
void Slic3r::GUI::ImGuiWrapper::push_common_window_style (const float scale) static
{
    if (m_is_dark_mode) {
        ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(20.0f, 10.0f) * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowTitleAlign, ImVec2(0.05f, 0.50f) * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 3.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.0f, 1.0f, 1.0f, 0.88f));                                   // 1
        ImGui::PushStyleColor(ImGuiCol_WindowBg, ImGuiWrapper::COL_WINDOW_BG_DARK);                              // 2
        ImGui::PushStyleColor(ImGuiCol_TitleBg, ImVec4(54 / 255.0f, 54 / 255.0f, 60 / 255.0f, 1.00f));           // 3
        ImGui::PushStyleColor(ImGuiCol_TitleBgActive, ImVec4(54 / 255.0f, 54 / 255.0f, 60 / 255.0f, 1.00f));     // 4
        ImGui::PushStyleColor(ImGuiCol_Separator, ImGuiWrapper::COL_SEPARATOR_DARK);                             // 5
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));                              // 6
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));                       // 7
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));                        // 8
        ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, ImVec4(84 / 255.0f, 84 / 255.0f, 90 / 255.0f, 1.00f));    // 9
        ImGui::PushStyleColor(ImGuiCol_FrameBgActive, ImVec4(62 / 255.0f, 62 / 255.0f, 69 / 255.0f, 1.00f));     // 10
        ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 0.00f));        // 11
        ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));                           // 12
        ImGui::PushStyleColor(ImGuiCol_TextSelectedBg, ImVec4(43 / 255.0f, 64 / 255.0f, 54 / 255.0f, 1.00f));    // 13
        ImGui::PushStyleColor(ImGuiCol_PlotHistogram, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));                       // 14
    }
    else {
        ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(20.0f, 10.0f) * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowTitleAlign, ImVec2(0.05f, 0.50f) * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 3.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(38 / 255.0f, 46 / 255.0f, 48 / 255.0f, 1.00f));              // 1
        ImGui::PushStyleColor(ImGuiCol_WindowBg, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));                            // 2
        ImGui::PushStyleColor(ImGuiCol_TitleBg, ImVec4(245 / 255.0f, 245 / 255.0f, 245 / 255.0f, 1.00f));        // 3
        ImGui::PushStyleColor(ImGuiCol_TitleBgActive, ImVec4(245 / 255.0f, 245 / 255.0f, 245 / 255.0f, 1.00f));  // 4
        ImGui::PushStyleColor(ImGuiCol_Separator, ImGuiWrapper::COL_SEPARATOR);                                  // 5
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));                              // 6
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));                       // 7
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));                        // 8
        ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 1.00f)); // 9
        ImGui::PushStyleColor(ImGuiCol_FrameBgActive, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 1.00f));  // 10
        ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 0.00f));        // 11
        ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));                           // 12
        ImGui::PushStyleColor(ImGuiCol_TextSelectedBg, ImGuiWrapper::COL_GREEN_LIGHT);                           // 13
        ImGui::PushStyleColor(ImGuiCol_PlotHistogram, ImVec4(0.00f, 0.59f, 0.53f, 1.00f));                       // 14
    }
}
References COL_GREEN_LIGHT, COL_SEPARATOR, COL_SEPARATOR_DARK, COL_WINDOW_BG_DARK, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_PlotHistogram, ImGuiCol_Separator, ImGuiCol_Text, ImGuiCol_TextSelectedBg, ImGuiCol_TitleBg, ImGuiCol_TitleBgActive, ImGuiCol_WindowBg, ImGuiStyleVar_FrameBorderSize, ImGuiStyleVar_WindowBorderSize, ImGuiStyleVar_WindowPadding, ImGuiStyleVar_WindowRounding, ImGuiStyleVar_WindowTitleAlign, Slic3r::GUI::m_is_dark_mode, ImGui::PushStyleColor(), ImGui::PushStyleVar(), and scale().
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
push_confirm_button_style()
void Slic3r::GUI::ImGuiWrapper::push_confirm_button_style () static
{
    if (m_is_dark_mode) {
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.f / 255.f, 150.f / 255.f, 136.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(0.f / 255.f, 150.f / 255.f, 136.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(61.f / 255.f, 203.f / 255.f, 115.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(27.f / 255.f, 136.f / 255.f, 68.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1.f, 1.f, 1.f, 0.88f));
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 0.88f));
    }
    else {
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(0.f / 255.f, 150.f / 255.f, 136.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(0.f / 255.f, 150.f / 255.f, 136.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(61.f / 255.f, 203.f / 255.f, 115.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(27.f / 255.f, 136.f / 255.f, 68.f / 255.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1.f, 1.f, 1.f, 1.f));
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.f, 1.f, 1.f, 1.f));
    }
}
References ImGuiCol_Border, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_Text, Slic3r::GUI::m_is_dark_mode, and ImGui::PushStyleColor().
Referenced by Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), and Slic3r::GUI::IMSlider::render_input_custom_gcode().
push_font_by_name()
bool Slic3r::GUI::ImGuiWrapper::push_font_by_name (std::string font_name)
{
    auto sys_font = im_fonts_map.find(font_name);
    if (sys_font != im_fonts_map.end()) {
        ImFont* font = sys_font->second;
        if (font && font->ContainerAtlas && font->Glyphs.Size > 4)
            ImGui::PushFont(font);
        else {
            ImGui::PushFont(default_font);
        }
        return true;
    }
    return false;
}
References ImFont::ContainerAtlas, default_font, ImFont::Glyphs, im_fonts_map, ImGui::PushFont(), and ImVector< T >::Size.
push_menu_style()
void Slic3r::GUI::ImGuiWrapper::push_menu_style (const float scale) static
{
    if (m_is_dark_mode) {
        ImGuiWrapper::push_toolbar_style(scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(10.0f, 10.0f) * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_PopupRounding, 4.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_PopupBorderSize, 0.0f);
        ImGui::PushStyleColor(ImGuiCol_PopupBg, ImGuiWrapper::COL_WINDOW_BG_DARK);
        ImGui::PushStyleColor(ImGuiCol_Header, ImVec4(0.00f, 0.59f, 0.53f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_HeaderHovered, ImVec4(0.00f, 0.59f, 0.53f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_HeaderActive, ImVec4(0.00f, 0.59f, 0.53f, 1.0f));
    }
    else {
        ImGuiWrapper::push_toolbar_style(scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(10.0f, 10.0f) * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_PopupRounding, 4.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_PopupBorderSize, 0.0f);
        ImGui::PushStyleColor(ImGuiCol_PopupBg, ImGuiWrapper::COL_WINDOW_BG);
        ImGui::PushStyleColor(ImGuiCol_Header, ImVec4(0.00f, 0.59f, 0.53f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_HeaderHovered, ImVec4(0.00f, 0.59f, 0.53f, 1.0f));
        ImGui::PushStyleColor(ImGuiCol_HeaderActive, ImVec4(0.00f, 0.59f, 0.53f, 1.0f));
    }
}
References COL_WINDOW_BG, COL_WINDOW_BG_DARK, ImGuiCol_Header, ImGuiCol_HeaderActive, ImGuiCol_HeaderHovered, ImGuiCol_PopupBg, ImGuiStyleVar_PopupBorderSize, ImGuiStyleVar_PopupRounding, ImGuiStyleVar_WindowPadding, Slic3r::GUI::m_is_dark_mode, push_toolbar_style(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), and scale().
Referenced by Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), Slic3r::GUI::IMSlider::render_input_custom_gcode(), and Slic3r::GUI::IMSlider::render_menu().
push_toolbar_style()
void Slic3r::GUI::ImGuiWrapper::push_toolbar_style (const float scale) static
{
    if (m_is_dark_mode) {
        ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(20.0f, 10.0f) * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 3.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
        ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 2.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(10.0f, 10.0f) * scale);
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.0f, 1.0f, 1.0f, 0.88f));                                        // 1
        ImGui::PushStyleColor(ImGuiCol_WindowBg, ImGuiWrapper::COL_WINDOW_BG_DARK);                                   // 2
        ImGui::PushStyleColor(ImGuiCol_TitleBg, ImGuiWrapper::COL_TITLE_BG);                                          // 3
        ImGui::PushStyleColor(ImGuiCol_TitleBgActive, ImGuiWrapper::COL_TITLE_BG);                                    // 4
        ImGui::PushStyleColor(ImGuiCol_Separator, ImGuiWrapper::COL_SEPARATOR_DARK);                                  // 5
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(62 / 255.0f, 62 / 255.0f, 69 / 255.0f, 1.00f));                 // 6
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImVec4(73 / 255.0f, 73 / 255.0f, 78 / 255.0f, 1.00f));          // 7
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(73 / 255.0f, 73 / 255.0f, 78 / 255.0f, 1.00f));           // 8
        ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, ImVec4(84 / 255.0f, 84 / 255.0f, 90 / 255.0f, 1.00f));         // 9
        ImGui::PushStyleColor(ImGuiCol_FrameBgActive, ImVec4(62 / 255.0f, 62 / 255.0f, 69 / 255.0f, 1.00f));          // 10
        ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 0.00f));             // 11
        ImGui::PushStyleColor(ImGuiCol_TextSelectedBg, ImVec4(43 / 255.0f, 64 / 255.0f, 54 / 255.0f, 1.00f));         // 12
        ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));                                // 13
        ImGui::PushStyleColor(ImGuiCol_ScrollbarGrab, ImVec4(0.42f, 0.42f, 0.42f, 1.00f));                            // 14
        ImGui::PushStyleColor(ImGuiCol_ScrollbarGrabHovered, ImVec4(0.93f, 0.93f, 0.93f, 1.00f));                     // 15
        ImGui::PushStyleColor(ImGuiCol_ScrollbarGrabActive, ImVec4(0.93f, 0.93f, 0.93f, 1.00f));                      // 16
    }
    else {
        ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 1.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(20.0f, 10.0f) * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 3.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 0.0f);
        ImGui::PushStyleVar(ImGuiStyleVar_FrameRounding, 2.0f * scale);
        ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(10.0f, 10.0f) * scale);
        ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(50 / 255.0f, 58 / 255.0f, 61 / 255.0f, 1.00f));       // 1
        ImGui::PushStyleColor(ImGuiCol_WindowBg, ImGuiWrapper::COL_WINDOW_BG);          // 2
        ImGui::PushStyleColor(ImGuiCol_TitleBg, ImGuiWrapper::COL_TITLE_BG);            // 3
        ImGui::PushStyleColor(ImGuiCol_TitleBgActive, ImGuiWrapper::COL_TITLE_BG);      // 4
        ImGui::PushStyleColor(ImGuiCol_Separator, ImGuiWrapper::COL_SEPARATOR);         // 5
        ImGui::PushStyleColor(ImGuiCol_Button, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));     // 6
        ImGui::PushStyleColor(ImGuiCol_ButtonHovered, ImGuiWrapper::COL_HOVER);         // 7
        ImGui::PushStyleColor(ImGuiCol_FrameBgHovered, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 1.00f)); // 8
        ImGui::PushStyleColor(ImGuiCol_ButtonActive, ImVec4(172 / 255.0f, 172 / 255.0f, 172 / 255.0f, 1.00f));                        // 9
        ImGui::PushStyleColor(ImGuiCol_FrameBgActive, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 1.00f));  // 10
        ImGui::PushStyleColor(ImGuiCol_FrameBg, ImVec4(238 / 255.0f, 238 / 255.0f, 238 / 255.0f, 0.00f));        // 11
        ImGui::PushStyleColor(ImGuiCol_TextSelectedBg, COL_GREEN_LIGHT);                                     // 12
        ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));//13
        ImGui::PushStyleColor(ImGuiCol_ScrollbarGrab, ImVec4(0.42f, 0.42f, 0.42f, 1.00f));
        ImGui::PushStyleColor(ImGuiCol_ScrollbarGrabHovered, ImVec4(0.93f, 0.93f, 0.93f, 1.00f));
        ImGui::PushStyleColor(ImGuiCol_ScrollbarGrabActive, ImVec4(0.93f, 0.93f, 0.93f, 1.00f));
    }
}
References COL_GREEN_LIGHT, COL_HOVER, COL_SEPARATOR, COL_SEPARATOR_DARK, COL_TITLE_BG, COL_WINDOW_BG, COL_WINDOW_BG_DARK, ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiCol_CheckMark, ImGuiCol_FrameBg, ImGuiCol_FrameBgActive, ImGuiCol_FrameBgHovered, ImGuiCol_ScrollbarGrab, ImGuiCol_ScrollbarGrabActive, ImGuiCol_ScrollbarGrabHovered, ImGuiCol_Separator, ImGuiCol_Text, ImGuiCol_TextSelectedBg, ImGuiCol_TitleBg, ImGuiCol_TitleBgActive, ImGuiCol_WindowBg, ImGuiStyleVar_FrameBorderSize, ImGuiStyleVar_FrameRounding, ImGuiStyleVar_ItemSpacing, ImGuiStyleVar_WindowBorderSize, ImGuiStyleVar_WindowPadding, ImGuiStyleVar_WindowRounding, Slic3r::GUI::m_is_dark_mode, ImGui::PushStyleColor(), ImGui::PushStyleVar(), and scale().
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_assemble_info(), Slic3r::GUI::GLCanvas3D::_render_orient_menu(), Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), push_menu_style(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
radio_button()
bool Slic3r::GUI::ImGuiWrapper::radio_button (const wxString & label, bool active)
{
    auto label_utf8 = into_u8(label);
    return ImGui::RadioButton(label_utf8.c_str(), active);
}
References Slic3r::GUI::into_u8(), and ImGui::RadioButton().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::render_connect_type_radio_button().
read_glsl_version()
void Slic3r::GUI::ImGuiWrapper::read_glsl_version ()
render()
void Slic3r::GUI::ImGuiWrapper::render ()
{
    ImGui::Render();
    render_draw_data(ImGui::GetDrawData());
    m_new_frame_open = false;
}
References ImGui::GetDrawData(), m_new_frame_open, ImGui::Render(), and render_draw_data().
render_draw_data()
void Slic3r::GUI::ImGuiWrapper::render_draw_data (ImDrawData * draw_data) private
{
    // Avoid rendering when minimized, scale coordinates for retina displays (screen coordinates != framebuffer coordinates)
    ImGuiIO& io = ImGui::GetIO();
    int fb_width = (int)(draw_data->DisplaySize.x * io.DisplayFramebufferScale.x);
    int fb_height = (int)(draw_data->DisplaySize.y * io.DisplayFramebufferScale.y);
    if (fb_width == 0 || fb_height == 0)
        return;
    draw_data->ScaleClipRects(io.DisplayFramebufferScale);
    // We are using the OpenGL fixed pipeline to make the example code simpler to read!
    // Setup render state: alpha-blending enabled, no face culling, no depth testing, scissor enabled, vertex/texcoord/color pointers, polygon fill.
    GLint last_texture; glsafe(::glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture));
    GLint last_polygon_mode[2]; glsafe(::glGetIntegerv(GL_POLYGON_MODE, last_polygon_mode));
    GLint last_viewport[4]; glsafe(::glGetIntegerv(GL_VIEWPORT, last_viewport));
    GLint last_scissor_box[4]; glsafe(::glGetIntegerv(GL_SCISSOR_BOX, last_scissor_box));
    glsafe(::glPushAttrib(GL_ENABLE_BIT | GL_COLOR_BUFFER_BIT | GL_TRANSFORM_BIT));
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    glsafe(::glDisable(GL_CULL_FACE));
    glsafe(::glDisable(GL_DEPTH_TEST));
    glsafe(::glDisable(GL_LIGHTING));
    glsafe(::glDisable(GL_COLOR_MATERIAL));
    glsafe(::glEnable(GL_SCISSOR_TEST));
    glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
    glsafe(::glEnableClientState(GL_TEXTURE_COORD_ARRAY));
    glsafe(::glEnableClientState(GL_COLOR_ARRAY));
    glsafe(::glEnable(GL_TEXTURE_2D));
    glsafe(::glPolygonMode(GL_FRONT_AND_BACK, GL_FILL));
    glsafe(::glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE));
    GLint texture_env_mode = GL_MODULATE;
    glsafe(::glGetTexEnviv(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, &texture_env_mode));
    glsafe(::glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, GL_MODULATE));
    //glUseProgram(0); // You may want this if using this code in an OpenGL 3+ context where shaders may be bound
    // Setup viewport, orthographic projection matrix
    // Our visible imgui space lies from draw_data->DisplayPps (top left) to draw_data->DisplayPos+data_data->DisplaySize (bottom right). DisplayMin is typically (0,0) for single viewport apps.
    glsafe(::glViewport(0, 0, (GLsizei)fb_width, (GLsizei)fb_height));
    glsafe(::glMatrixMode(GL_PROJECTION));
    glsafe(::glPushMatrix());
    glsafe(::glLoadIdentity());
    glsafe(::glOrtho(draw_data->DisplayPos.x, draw_data->DisplayPos.x + draw_data->DisplaySize.x, draw_data->DisplayPos.y + draw_data->DisplaySize.y, draw_data->DisplayPos.y, -1.0f, +1.0f));
    glsafe(::glMatrixMode(GL_MODELVIEW));
    glsafe(::glPushMatrix());
    glsafe(::glLoadIdentity());
    // Render command lists
    ImVec2 pos = draw_data->DisplayPos;
    for (int n = 0; n < draw_data->CmdListsCount; n++)
    {
        const ImDrawList* cmd_list = draw_data->CmdLists[n];
        const ImDrawVert* vtx_buffer = cmd_list->VtxBuffer.Data;
        const ImDrawIdx* idx_buffer = cmd_list->IdxBuffer.Data;
        glsafe(::glVertexPointer(2, GL_FLOAT, sizeof(ImDrawVert), (const GLvoid*)((const char*)vtx_buffer + IM_OFFSETOF(ImDrawVert, pos))));
        glsafe(::glTexCoordPointer(2, GL_FLOAT, sizeof(ImDrawVert), (const GLvoid*)((const char*)vtx_buffer + IM_OFFSETOF(ImDrawVert, uv))));
        glsafe(::glColorPointer(4, GL_UNSIGNED_BYTE, sizeof(ImDrawVert), (const GLvoid*)((const char*)vtx_buffer + IM_OFFSETOF(ImDrawVert, col))));
        for (int cmd_i = 0; cmd_i < cmd_list->CmdBuffer.Size; cmd_i++)
        {
            const ImDrawCmd* pcmd = &cmd_list->CmdBuffer[cmd_i];
            if (pcmd->UserCallback)
            {
                // User callback (registered via ImDrawList::AddCallback)
                pcmd->UserCallback(cmd_list, pcmd);
            }
            else
            {
                ImVec4 clip_rect = ImVec4(pcmd->ClipRect.x - pos.x, pcmd->ClipRect.y - pos.y, pcmd->ClipRect.z - pos.x, pcmd->ClipRect.w - pos.y);
                if (clip_rect.x < fb_width && clip_rect.y < fb_height && clip_rect.z >= 0.0f && clip_rect.w >= 0.0f)
                {
                    // Apply scissor/clipping rectangle
                    glsafe(::glScissor((int)clip_rect.x, (int)(fb_height - clip_rect.w), (int)(clip_rect.z - clip_rect.x), (int)(clip_rect.w - clip_rect.y)));
                    // Bind texture, Draw
                    glsafe(::glBindTexture(GL_TEXTURE_2D, (GLuint)(intptr_t)pcmd->TextureId));
                    glsafe(::glDrawElements(GL_TRIANGLES, (GLsizei)pcmd->ElemCount, sizeof(ImDrawIdx) == 2 ? GL_UNSIGNED_SHORT : GL_UNSIGNED_INT, idx_buffer));
                }
            }
            idx_buffer += pcmd->ElemCount;
        }
    }
    // Restore modified state
    glsafe(::glTexEnvi(GL_TEXTURE_ENV, GL_TEXTURE_ENV_MODE, texture_env_mode));
    glsafe(::glDisableClientState(GL_COLOR_ARRAY));
    glsafe(::glDisableClientState(GL_TEXTURE_COORD_ARRAY));
    glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
    glsafe(::glBindTexture(GL_TEXTURE_2D, (GLuint)last_texture));
    glsafe(::glMatrixMode(GL_MODELVIEW));
    glsafe(::glPopMatrix());
    glsafe(::glMatrixMode(GL_PROJECTION));
    glsafe(::glPopMatrix());
    glsafe(::glPopAttrib());
    glsafe(::glPolygonMode(GL_FRONT, (GLenum)last_polygon_mode[0]); glPolygonMode(GL_BACK, (GLenum)last_polygon_mode[1]));
    glsafe(::glViewport(last_viewport[0], last_viewport[1], (GLsizei)last_viewport[2], (GLsizei)last_viewport[3]));
    glsafe(::glScissor(last_scissor_box[0], last_scissor_box[1], (GLsizei)last_scissor_box[2], (GLsizei)last_scissor_box[3]));
}
References ImDrawCmd::ClipRect, ImDrawList::CmdBuffer, ImDrawData::CmdLists, ImDrawData::CmdListsCount, col(), ImVector< T >::Data, ImGuiIO::DisplayFramebufferScale, ImDrawData::DisplayPos, ImDrawData::DisplaySize, ImDrawCmd::ElemCount, ImGui::GetIO(), GL_TRIANGLES, glsafe, ImDrawList::IdxBuffer, IM_OFFSETOF, int, n, ImDrawData::ScaleClipRects(), ImVector< T >::Size, ImDrawCmd::TextureId, ImDrawCmd::UserCallback, ImDrawList::VtxBuffer, ImVec4::w, ImVec2::x, ImVec4::x, ImVec2::y, ImVec4::y, and ImVec4::z.
Referenced by render().
scaled() [1/2]
float Slic3r::GUI::ImGuiWrapper::scaled (float x) const inline
{ return x * m_font_size; }
References m_font_size.
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_return_toolbar(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GCodeViewer::render_all_plates_stats(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog(), Slic3r::GUI::GLCanvas3D::LayersEditing::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::update_font_texture().
scaled() [2/2]
ImVec2 Slic3r::GUI::ImGuiWrapper::scaled (float x, float y) const inline
{ return ImVec2(x * m_font_size, y * m_font_size); }
References m_font_size.
search_list()
void Slic3r::GUI::ImGuiWrapper::search_list (const ImVec2 & size, bool(*)(int, const char **label, const char **tooltip) items_getter, char * search_str, Search::OptionViewParameters & view_params, int & selected, bool & edited, int & mouse_wheel, bool is_localized)
{
    int& hovered_id = view_params.hovered_id;
    // ImGui::ListBoxHeader("", size);
    {
        // rewrote part of function to add a TextInput instead of label Text
        ImGuiContext& g = *GImGui;
        ImGuiWindow* window = ImGui::GetCurrentWindow();
        if (window->SkipItems)
            return ;
        const ImGuiStyle& style = g.Style;
        // Size default to hold ~7 items. Fractional number of items helps seeing that we can scroll down/up without looking at scrollbar.
        ImVec2 size = ImGui::CalcItemSize(size_, ImGui::CalcItemWidth(), ImGui::GetTextLineHeightWithSpacing() * 7.4f + style.ItemSpacing.y);
        ImRect frame_bb(window->DC.CursorPos, ImVec2(window->DC.CursorPos.x + size.x, window->DC.CursorPos.y + size.y));
        ImRect bb(frame_bb.Min, frame_bb.Max);
        window->DC.LastItemRect = bb; // Forward storage for ListBoxFooter.. dodgy.
        g.NextItemData.ClearFlags();
        if (!ImGui::IsRectVisible(bb.Min, bb.Max))
        {
            ImGui::ItemSize(bb.GetSize(), style.FramePadding.y);
            ImGui::ItemAdd(bb, 0, &frame_bb);
            return ;
        }
        ImGui::BeginGroup();
        const ImGuiID id = ImGui::GetID(search_str);
        ImVec2 search_size = ImVec2(size.x, ImGui::GetTextLineHeightWithSpacing() + style.ItemSpacing.y);
        if (!ImGui::IsAnyItemFocused() && !ImGui::IsAnyItemActive() && !ImGui::IsMouseClicked(0))
            ImGui::SetKeyboardFocusHere(0);
        // The press on Esc key invokes editing of InputText (removes last changes)
        // So we should save previous value...
        std::string str = search_str;
        ImGui::InputTextEx("", NULL, search_str, 40, search_size, ImGuiInputTextFlags_AutoSelectAll, NULL, NULL);
        edited = ImGui::IsItemEdited();
        if (edited)
            hovered_id = 0;
        process_key_down(ImGuiKey_Escape, [&selected, search_str, str]() {
            // use 9999 to mark selection as a Esc key
            selected = 9999;
            // ... and when Esc key was pressed, than revert search_str value
            strcpy(search_str, str.c_str());
        });
        ImGui::BeginChildFrame(id, frame_bb.GetSize());
    }
    int i = 0;
    const char* item_text;
    const char* tooltip;
    int mouse_hovered = -1;
    while (items_getter(i, &item_text, &tooltip))
    {
        selectable(item_text, i == hovered_id);
        if (ImGui::IsItemHovered()) {
            ImGui::SetTooltip("%s", /*item_text*/tooltip);
                hovered_id = -1;
            mouse_hovered = i;
        }
        if (ImGui::IsItemClicked())
            selected = i;
        i++;
    }
    // Process mouse wheel
    if (mouse_hovered > 0)
        process_mouse_wheel(mouse_wheel);
    // process Up/DownArrows and Enter
    process_key_down(ImGuiKey_UpArrow, [&hovered_id, mouse_hovered]() {
        if (mouse_hovered > 0)
            scroll_up();
        else {
            if (hovered_id > 0)
                --hovered_id;
            scroll_y(hovered_id);
        }
    });
    process_key_down(ImGuiKey_DownArrow, [&hovered_id, mouse_hovered, i]() {
        if (mouse_hovered > 0)
            scroll_down();
        else {
            if (hovered_id < 0)
                hovered_id = 0;
            else if (hovered_id < i - 1)
                ++hovered_id;
            scroll_y(hovered_id);
        }
    });
    process_key_down(ImGuiKey_Enter, [&selected, hovered_id]() {
        selected = hovered_id;
    });
    ImGui::ListBoxFooter();
    auto check_box = [&edited, this](const wxString& label, bool& check) {
        ImGui::SameLine();
        bool ch = check;
        checkbox(label, ch);
        if (ImGui::IsItemClicked()) {
            check = !check;
            edited = true;
        }
    };
    ImGui::AlignTextToFramePadding();
    // add checkboxes for show/hide Categories and Groups
    //text(_L("Use for search")+":");
    //check_box(_L("Category"),   view_params.category);
    //if (is_localized)
    //    check_box(_L("Search in English"), view_params.english);
}
References ImGui::AlignTextToFramePadding(), ImGui::BeginChildFrame(), ImGui::BeginGroup(), ImGui::CalcItemSize(), ImGui::CalcItemWidth(), checkbox(), ImGuiNextItemData::ClearFlags(), ImGuiWindowTempData::CursorPos, ImGuiWindow::DC, ImGui::GetCurrentWindow(), ImGui::GetID(), ImRect::GetSize(), ImGui::GetTextLineHeightWithSpacing(), GImGui, Slic3r::Search::OptionViewParameters::hovered_id, ImGuiInputTextFlags_AutoSelectAll, ImGuiKey_DownArrow, ImGuiKey_Enter, ImGuiKey_Escape, ImGuiKey_UpArrow, ImGui::InputTextEx(), ImGui::IsAnyItemActive(), ImGui::IsAnyItemFocused(), ImGui::IsItemClicked(), ImGui::IsItemEdited(), ImGui::IsItemHovered(), ImGui::IsMouseClicked(), ImGui::IsRectVisible(), ImGui::ItemAdd(), ImGui::ItemSize(), ImGuiWindowTempData::LastItemRect, ImGui::ListBoxFooter(), ImRect::Max, ImRect::Min, ImGuiContext::NextItemData, NULL, Slic3r::GUI::process_key_down(), Slic3r::GUI::process_mouse_wheel(), return, ImGui::SameLine(), Slic3r::GUI::scroll_down(), Slic3r::GUI::scroll_up(), scroll_y, Slic3r::GUI::selectable(), ImGui::SetKeyboardFocusHere(), ImGui::SetTooltip(), size, ImGuiWindow::SkipItems, ImGuiContext::Style, style, tooltip(), ImVec2::x, and ImVec2::y.
set_display_size()
void Slic3r::GUI::ImGuiWrapper::set_display_size (float w, float h)
{
    ImGuiIO& io = ImGui::GetIO();
    io.DisplaySize = ImVec2(w, h);
    io.DisplayFramebufferScale = ImVec2(1.0f, 1.0f);
}
References ImGuiIO::DisplayFramebufferScale, ImGuiIO::DisplaySize, and ImGui::GetIO().
set_language()
void Slic3r::GUI::ImGuiWrapper::set_language (const std::string & language)
{
    if (m_new_frame_open) {
        // ImGUI internally locks the font between NewFrame() and EndFrame()
        // NewFrame() might've been called here because of input from the 3D scene;
        // call EndFrame()
        ImGui::EndFrame();
        m_new_frame_open = false;
    }
    const ImWchar *ranges = nullptr;
    size_t idx = language.find('_');
    std::string lang = (idx == std::string::npos) ? language : language.substr(0, idx);
    static const ImWchar ranges_latin2[] =
    {
        0x0020, 0x00FF, // Basic Latin + Latin Supplement
        0x0100, 0x017F, // Latin Extended-A
        0,
    };
    static const ImWchar ranges_turkish[] = {
        0x0020, 0x01FF, // Basic Latin + Latin Supplement
        0x0100, 0x017F, // Latin Extended-A
        0x0180, 0x01FF, // Turkish
        0,
    };
    static const ImWchar ranges_vietnamese[] =
    {
        0x0020, 0x00FF, // Basic Latin
        0x0102, 0x0103,
        0x0110, 0x0111,
        0x0128, 0x0129,
        0x0168, 0x0169,
        0x01A0, 0x01A1,
        0x01AF, 0x01B0,
        0x1EA0, 0x1EF9,
        0,
    };
    m_font_cjk = false;
    if (lang == "cs" || lang == "pl") {
        ranges = ranges_latin2;
    } else if (lang == "ru" || lang == "uk") {
        ranges = ImGui::GetIO().Fonts->GetGlyphRangesCyrillic(); // Default + about 400 Cyrillic characters
    } else if (lang == "tr") {
        ranges = ranges_turkish;
    } else if (lang == "vi") {
        ranges = ranges_vietnamese;
    } else if (lang == "ja") {
        ranges = ImGui::GetIO().Fonts->GetGlyphRangesJapanese(); // Default + Hiragana, Katakana, Half-Width, Selection of 1946 Ideographs
        m_font_cjk = true;
    } else if (lang == "ko") {
        ranges = ImGui::GetIO().Fonts->GetGlyphRangesKorean(); // Default + Korean characters
        m_font_cjk = true;
    } else if (lang == "zh") {
        ranges = (language == "zh_TW") ?
            // Traditional Chinese
            // Default + Half-Width + Japanese Hiragana/Katakana + full set of about 21000 CJK Unified Ideographs
            ImGui::GetIO().Fonts->GetGlyphRangesChineseFull() :
            // Simplified Chinese
            // Default + Half-Width + Japanese Hiragana/Katakana + set of 2500 CJK Unified Ideographs for common simplified Chinese
            ImGui::GetIO().Fonts->GetGlyphRangesChineseSimplifiedCommon();
        m_font_cjk = true;
    } else if (lang == "th") {
        ranges = ImGui::GetIO().Fonts->GetGlyphRangesThai(); // Default + Thai characters
    }
    else if (lang == "en") {
        ranges = ImGui::GetIO().Fonts->GetGlyphRangesEnglish(); // Basic Latin
    }
    else{
        ranges = ImGui::GetIO().Fonts->GetGlyphRangesOthers();
    }
    if (ranges != m_glyph_ranges) {
        m_glyph_ranges = ranges;
        //destroy_fonts_texture();
        destroy_font();
    }
    m_glyph_basic_ranges = ImGui::GetIO().Fonts->GetGlyphRangesBasic();
}
References destroy_font(), ImGui::EndFrame(), ImGuiIO::Fonts, ImFontAtlas::GetGlyphRangesBasic(), ImFontAtlas::GetGlyphRangesChineseFull(), ImFontAtlas::GetGlyphRangesChineseSimplifiedCommon(), ImFontAtlas::GetGlyphRangesCyrillic(), ImFontAtlas::GetGlyphRangesEnglish(), ImFontAtlas::GetGlyphRangesJapanese(), ImFontAtlas::GetGlyphRangesKorean(), ImFontAtlas::GetGlyphRangesOthers(), ImFontAtlas::GetGlyphRangesThai(), ImGui::GetIO(), m_font_cjk, m_glyph_basic_ranges, m_glyph_ranges, and m_new_frame_open.
set_next_window_bg_alpha()
void Slic3r::GUI::ImGuiWrapper::set_next_window_bg_alpha (float alpha)
{
    ImGui::SetNextWindowBgAlpha(alpha);
}
References ImGui::SetNextWindowBgAlpha().
set_next_window_pos()
void Slic3r::GUI::ImGuiWrapper::set_next_window_pos (float x, float y, int flag, float pivot_x = 0.0f, float pivot_y = 0.0f)
{
    ImGui::SetNextWindowPos(ImVec2(x, y), (ImGuiCond)flag, ImVec2(pivot_x, pivot_y));
    ImGui::SetNextWindowSize(ImVec2(0.0, 0.0));
}
References ImGui::SetNextWindowPos(), and ImGui::SetNextWindowSize().
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_assemble_info(), Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::_render_orient_menu(), Slic3r::GUI::GLCanvas3D::_render_paint_toolbar(), Slic3r::GUI::GLCanvas3D::_render_return_toolbar(), Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notification(), Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::GLCanvas3D::Tooltip::render(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::render(), Slic3r::GUI::NotificationManager::PopNotification::render(), Slic3r::GUI::IMSlider::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::PartPlate::render_label(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
set_next_window_size()
void Slic3r::GUI::ImGuiWrapper::set_next_window_size (float x, float y, ImGuiCond cond)
{
    ImGui::SetNextWindowSize(ImVec2(x, y), cond);
}
References ImGui::SetNextWindowSize().
Referenced by Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::GLCanvas3D::_render_return_toolbar(), Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notification(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::render(), and Slic3r::GUI::NotificationManager::PopNotification::render().
set_scaling()
void Slic3r::GUI::ImGuiWrapper::set_scaling (float font_size, float scale_style, float scale_both)
{
    font_size *= scale_both;
    scale_style *= scale_both;
    if (m_font_size == font_size && m_style_scaling == scale_style) {
        return;
    }
    m_font_size = font_size;
    ImGui::GetStyle().ScaleAllSizes(scale_style / m_style_scaling);
    m_style_scaling = scale_style;
    //destroy_fonts_texture();
    destroy_font();
}
References destroy_font(), ImGui::GetStyle(), m_font_size, m_style_scaling, and ImGuiStyle::ScaleAllSizes().
slider_float() [1/3]
bool Slic3r::GUI::ImGuiWrapper::slider_float (const char * label, float * v, float v_min, float v_max, const char * format = "%.3f", float power = 1.0f, bool clamp = true)
{
    bool ret = ImGui::SliderFloat(label, v, v_min, v_max, format, power);
    if (clamp)
        *v = std::clamp(*v, v_min, v_max);
    return ret;
}
References clamp(), Slic3r::GUI::format(), and ImGui::SliderFloat().
Referenced by Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), slider_float(), and slider_float().
slider_float() [2/3]
bool Slic3r::GUI::ImGuiWrapper::slider_float (const std::string & label, float * v, float v_min, float v_max, const char * format = "%.3f", float power = 1.0f, bool clamp = true)
{
    return this->slider_float(label.c_str(), v, v_min, v_max, format, power, clamp);
}
References clamp(), Slic3r::GUI::format(), and slider_float().
slider_float() [3/3]
bool Slic3r::GUI::ImGuiWrapper::slider_float (const wxString & label, float * v, float v_min, float v_max, const char * format = "%.3f", float power = 1.0f, bool clamp = true)
{
    auto label_utf8 = into_u8(label);
    return this->slider_float(label_utf8.c_str(), v, v_min, v_max, format, power, clamp);
}
References clamp(), Slic3r::GUI::format(), Slic3r::GUI::into_u8(), and slider_float().
text() [1/3]
void Slic3r::GUI::ImGuiWrapper::text (const char * label)
{
    ImGui::Text("%s", label);
}
References ImGui::Text().
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notif_left_sign(), Slic3r::GUI::NotificationManager::PopNotification::bbl_render_block_notif_text(), bbl_slider_float(), bold_text(), calc_text_size(), clipboard_set(), combo(), Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::render(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), Slic3r::GUI::GCodeViewer::render_all_plates_stats(), Slic3r::GUI::NotificationManager::ProgressBarNotification::render_bar(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::render_bar(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::render_cancel_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_combo(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::NotificationManager::HintNotification::render_documentation_button(), Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_eject_button(), Slic3r::GUI::IMSlider::render_go_to_layer_dialog(), Slic3r::GUI::NotificationManager::PopNotification::render_hypertext(), Slic3r::GUI::IMSlider::render_input_custom_gcode(), Slic3r::GUI::GLGizmoAdvancedCut::render_input_window_warning(), Slic3r::GUI::PartPlate::render_label(), Slic3r::GUI::GCodeViewer::render_legend(), Slic3r::GUI::NotificationManager::HintNotification::render_preferences_button(), Slic3r::GUI::NotificationManager::HintNotification::render_right_arrow_button(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLGizmoAdvancedCut::render_slider_double_input(), Slic3r::GUI::NotificationManager::PopNotification::render_text(), Slic3r::GUI::NotificationManager::HintNotification::render_text(), Slic3r::GUI::NotificationManager::ProgressBarNotification::render_text(), Slic3r::GUI::NotificationManager::SlicingProgressNotification::render_text(), Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_text(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog(), text(), text(), text_wrapped(), and title().
text() [2/3]
void Slic3r::GUI::ImGuiWrapper::text (const std::string & label)
{
    this->text(label.c_str());
}
References text().
text() [3/3]
void Slic3r::GUI::ImGuiWrapper::text (const wxString & label)
{
    auto label_utf8 = into_u8(label);
    this->text(label_utf8.c_str());
}
References Slic3r::GUI::into_u8(), and text().
text_colored() [1/3]
void Slic3r::GUI::ImGuiWrapper::text_colored (const ImVec4 & color, const char * label)
{
    ImGui::TextColored(color, "%s", label);
}
References ImGui::TextColored().
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::Mouse3DController::render_settings_dialog(), Slic3r::GUI::GLCanvas3D::LayersEditing::show_tooltip_information(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), text_colored(), and text_colored().
text_colored() [2/3]
void Slic3r::GUI::ImGuiWrapper::text_colored (const ImVec4 & color, const std::string & label)
{
    this->text_colored(color, label.c_str());
}
References text_colored().
text_colored() [3/3]
void Slic3r::GUI::ImGuiWrapper::text_colored (const ImVec4 & color, const wxString & label)
{
    auto label_utf8 = into_u8(label);
    this->text_colored(color, label_utf8.c_str());
}
References Slic3r::GUI::into_u8(), and text_colored().
text_wrapped() [1/3]
void Slic3r::GUI::ImGuiWrapper::text_wrapped (const char * label, float wrap_width)
{
    ImGui::PushTextWrapPos(ImGui::GetCursorPos().x + wrap_width);
    this->text(label);
    ImGui::PopTextWrapPos();
}
References ImGui::GetCursorPos(), ImGui::PopTextWrapPos(), ImGui::PushTextWrapPos(), and text().
Referenced by text_wrapped(), and text_wrapped().
text_wrapped() [2/3]
void Slic3r::GUI::ImGuiWrapper::text_wrapped (const std::string & label, float wrap_width)
{
    this->text_wrapped(label.c_str(), wrap_width);
}
References text_wrapped().
text_wrapped() [3/3]
void Slic3r::GUI::ImGuiWrapper::text_wrapped (const wxString & label, float wrap_width)
{
    auto label_utf8 = into_u8(label);
    this->text_wrapped(label_utf8.c_str(), wrap_width);
}
References Slic3r::GUI::into_u8(), and text_wrapped().
title()
void Slic3r::GUI::ImGuiWrapper::title (const std::string & str)
{
    if (bold_font){
        ImGui::PushFont(bold_font);
        text(str);
        ImGui::PopFont();
    } else {
        text(str);
    }
    ImGui::Separator();
}
References bold_font, ImGui::PopFont(), ImGui::PushFont(), ImGui::Separator(), and text().
Referenced by Slic3r::GUI::GCodeViewer::render_all_plates_stats(), and Slic3r::GUI::GCodeViewer::render_legend().
tooltip() [1/2]
void Slic3r::GUI::ImGuiWrapper::tooltip (const char * label, float wrap_width)
{
    ImGui::BeginTooltip();
    ImGui::PushTextWrapPos(wrap_width);
    ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));
    ImGui::TextUnformatted(label);
    ImGui::PopStyleColor(1);
    ImGui::PopTextWrapPos();
    ImGui::EndTooltip();
}
References ImGui::BeginTooltip(), ImGui::EndTooltip(), ImGuiCol_Text, ImGui::PopStyleColor(), ImGui::PopTextWrapPos(), ImGui::PushStyleColor(), ImGui::PushTextWrapPos(), and ImGui::TextUnformatted().
Referenced by Slic3r::GUI::GLCanvas3D::_render_paint_toolbar(), bbl_slider_float(), bbl_slider_float_style(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_reset_button(), and search_list().
tooltip() [2/2]
void Slic3r::GUI::ImGuiWrapper::tooltip (const wxString & label, float wrap_width)
{
    ImGui::BeginTooltip();
    ImGui::PushTextWrapPos(wrap_width);
    ImGui::PushStyleColor(ImGuiCol_Text, ImVec4(1.00f, 1.00f, 1.00f, 1.00f));
    ImGui::TextUnformatted(label.ToUTF8().data());
    ImGui::PopStyleColor(1);
    ImGui::PopTextWrapPos();
    ImGui::EndTooltip();
}
References ImGui::BeginTooltip(), ImGui::EndTooltip(), ImGuiCol_Text, ImGui::PopStyleColor(), ImGui::PopTextWrapPos(), ImGui::PushStyleColor(), ImGui::PushTextWrapPos(), and ImGui::TextUnformatted().
undo_redo_list()
bool Slic3r::GUI::ImGuiWrapper::undo_redo_list (const ImVec2 & size, const bool is_undo, bool(*)(const bool, int, const char **) items_getter, int & hovered, int & selected, int & mouse_wheel)
{
    bool is_hovered = false;
    ImGui::ListBoxHeader("", size);
    int i=0;
    const char* item_text;
    while (items_getter(is_undo, i, &item_text)) {
        ImGui::Selectable(item_text, i < hovered);
        if (ImGui::IsItemHovered()) {
            ImGui::SetTooltip("%s", item_text);
            hovered = i;
            is_hovered = true;
        }
        if (ImGui::IsItemClicked())
            selected = i;
        i++;
    }
    if (is_hovered)
        process_mouse_wheel(mouse_wheel);
    ImGui::ListBoxFooter();
    return is_hovered;
}
References ImGui::IsItemClicked(), ImGui::IsItemHovered(), ImGui::ListBoxFooter(), ImGui::ListBoxHeader(), Slic3r::GUI::process_mouse_wheel(), ImGui::Selectable(), ImGui::SetTooltip(), and size.
update_key_data()
bool Slic3r::GUI::ImGuiWrapper::update_key_data (wxKeyEvent & evt)
{
    if (! display_initialized()) {
        return false;
    }
    ImGuiIO& io = ImGui::GetIO();
    if (evt.GetEventType() == wxEVT_CHAR) {
        // Char event
        const auto key = evt.GetUnicodeKey();
        if (key != 0) {
            io.AddInputCharacter(key);
        }
    } else {
        // Key up/down event
        int key = evt.GetKeyCode();
        wxCHECK_MSG(key >= 0 && key < IM_ARRAYSIZE(io.KeysDown), false, "Received invalid key code");
        io.KeysDown[key] = evt.GetEventType() == wxEVT_KEY_DOWN;
        io.KeyShift = evt.ShiftDown();
        io.KeyCtrl = evt.ControlDown();
        io.KeyAlt = evt.AltDown();
        io.KeySuper = evt.MetaDown();
    }
    bool ret = want_keyboard() || want_text_input();
    if (ret)
        new_frame();
    return ret;
}
References ImGuiIO::AddInputCharacter(), display_initialized(), ImGui::GetIO(), IM_ARRAYSIZE, ImGuiIO::KeyAlt, ImGuiIO::KeyCtrl, ImGuiIO::KeysDown, ImGuiIO::KeyShift, ImGuiIO::KeySuper, new_frame(), want_keyboard(), and want_text_input().
update_mouse_data()
bool Slic3r::GUI::ImGuiWrapper::update_mouse_data (wxMouseEvent & evt)
{
    if (! display_initialized()) {
        return false;
    }
    ImGuiIO& io = ImGui::GetIO();
    io.MousePos = ImVec2((float)evt.GetX(), (float)evt.GetY());
    io.MouseDown[0] = evt.LeftIsDown();
    io.MouseDown[1] = evt.RightIsDown();
    io.MouseDown[2] = evt.MiddleIsDown();
    float wheel_delta = static_cast<float>(evt.GetWheelDelta());
    if (wheel_delta != 0.0f) {
        io.MouseWheel = evt.GetWheelRotation() > 0 ? 1.f : -1.f;
    }
    unsigned buttons = (evt.LeftIsDown() ? 1 : 0) | (evt.RightIsDown() ? 2 : 0) | (evt.MiddleIsDown() ? 4 : 0);
    m_mouse_buttons = buttons;
    if (want_mouse())
        new_frame();
    return want_mouse();
}
References display_initialized(), ImGui::GetIO(), m_mouse_buttons, ImGuiIO::MouseDown, ImGuiIO::MousePos, ImGuiIO::MouseWheel, new_frame(), and want_mouse().
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
want_any_input()
bool Slic3r::GUI::ImGuiWrapper::want_any_input () const
{
    const auto io = ImGui::GetIO();
    return io.WantCaptureMouse || io.WantCaptureKeyboard || io.WantTextInput;
}
References ImGui::GetIO().
want_keyboard()
bool Slic3r::GUI::ImGuiWrapper::want_keyboard () const
{
    return ImGui::GetIO().WantCaptureKeyboard;
}
References ImGui::GetIO(), and ImGuiIO::WantCaptureKeyboard.
Referenced by update_key_data().
want_mouse()
bool Slic3r::GUI::ImGuiWrapper::want_mouse () const
{
    return ImGui::GetIO().WantCaptureMouse;
}
References ImGui::GetIO(), and ImGuiIO::WantCaptureMouse.
Referenced by update_mouse_data().
want_text_input()
bool Slic3r::GUI::ImGuiWrapper::want_text_input () const
{
    return ImGui::GetIO().WantTextInput;
}
References ImGui::GetIO(), and ImGuiIO::WantTextInput.
Referenced by update_key_data().
Member Data Documentation
bold_font
ImFont* Slic3r::GUI::ImGuiWrapper::bold_font = nullptr private
Referenced by bold_text(), init_font(), pop_bold_font(), push_bold_font(), and title().
COL_ACTIVE
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_ACTIVE = { 0.675f, 0.675f, 0.675f, 1.0f } static
Referenced by init_style(), Slic3r::GUI::GLCanvas3D::LayersEditing::show_tooltip_information(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::show_tooltip_information().
COL_BLUE_LIGHT
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_BLUE_LIGHT = ImVec4(0.122f, 0.557f, 0.918f, 1.0f) static
Referenced by init_style().
COL_BUTTON_ACTIVE
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_BUTTON_ACTIVE = ImGuiWrapper::COL_BUTTON_HOVERED static
COL_BUTTON_BACKGROUND
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_BUTTON_BACKGROUND = COL_ORANGE_DARK static
Referenced by init_style().
COL_BUTTON_HOVERED
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_BUTTON_HOVERED = COL_ORANGE_LIGHT static
COL_GREEN_LIGHT
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_GREEN_LIGHT = ImVec4(0.86f, 0.99f, 0.91f, 1.0f) static
Referenced by push_common_window_style(), and push_toolbar_style().
COL_GREY_DARK
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_GREY_DARK = { 0.333f, 0.333f, 0.333f, 1.0f } static
Referenced by init_style().
COL_GREY_LIGHT
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_GREY_LIGHT = { 0.4f, 0.4f, 0.4f, 1.0f } static
Referenced by init_style().
COL_HOVER
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_HOVER = { 0.933f, 0.933f, 0.933f, 1.0f } static
Referenced by init_style(), and push_toolbar_style().
COL_ORANGE_DARK
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_ORANGE_DARK = { 0.757f, 0.404f, 0.216f, 1.0f } static
Referenced by init_style(), and Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::render().
COL_ORANGE_LIGHT
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT = { 1.0f, 0.49f, 0.216f, 1.0f } static
Referenced by init_style(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow::render(), and Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window().
COL_SEPARATOR
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_SEPARATOR = { 0.93f, 0.93f, 0.93f, 1.0f } static
Referenced by push_common_window_style(), and push_toolbar_style().
COL_SEPARATOR_DARK
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_SEPARATOR_DARK = { 0.24f, 0.24f, 0.27f, 1.0f } static
Referenced by push_common_window_style(), and push_toolbar_style().
COL_TITLE_BG
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_TITLE_BG = { 0.745f, 0.745f, 0.745f, 1.0f } static
Referenced by push_toolbar_style().
COL_WINDOW_BACKGROUND
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_WINDOW_BACKGROUND = { 0.1f, 0.1f, 0.1f, 0.8f } static
Referenced by init_style(), Slic3r::GUI::NotificationManager::PrintHostUploadNotification::render_cancel_button(), Slic3r::GUI::NotificationManager::HintNotification::render_documentation_button(), Slic3r::GUI::NotificationManager::ExportFinishedNotification::render_eject_button(), Slic3r::GUI::NotificationManager::HintNotification::render_preferences_button(), Slic3r::GUI::NotificationManager::HintNotification::render_right_arrow_button(), and Slic3r::GUI::IMSlider::show_tooltip().
COL_WINDOW_BG
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_WINDOW_BG = { 1.000f, 1.000f, 1.000f, 1.0f } static
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoText::push_combo_style(), push_combo_style(), push_menu_style(), push_toolbar_style(), Slic3r::GUI::GLCanvas3D::LayersEditing::show_tooltip_information(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::show_tooltip_information().
COL_WINDOW_BG_DARK
const ImVec4 Slic3r::GUI::ImGuiWrapper::COL_WINDOW_BG_DARK = { 45 / 255.f, 45 / 255.f, 49 / 255.f, 1.f } static
Referenced by Slic3r::GUI::GLGizmoText::push_combo_style(), push_combo_style(), push_common_window_style(), push_menu_style(), and push_toolbar_style().
default_font
ImFont* Slic3r::GUI::ImGuiWrapper::default_font = nullptr private
Referenced by init_font(), and push_font_by_name().
im_fonts_map
std::map<std::string, ImFont*> Slic3r::GUI::ImGuiWrapper::im_fonts_map private
Referenced by pop_font_by_name(), and push_font_by_name().
m_clipboard_text
std::string Slic3r::GUI::ImGuiWrapper::m_clipboard_text private
Referenced by clipboard_get().
m_disabled
bool Slic3r::GUI::ImGuiWrapper::m_disabled { false } private
Referenced by disabled_begin(), and disabled_end().
m_font_another_texture
unsigned Slic3r::GUI::ImGuiWrapper::m_font_another_texture { 0 } private
m_font_cjk
bool Slic3r::GUI::ImGuiWrapper::m_font_cjk { false } private
Referenced by init_font(), and set_language().
m_font_size
float Slic3r::GUI::ImGuiWrapper::m_font_size { 18.0 } private
Referenced by get_font_size(), init_font(), scaled(), scaled(), and set_scaling().
m_font_texture
unsigned Slic3r::GUI::ImGuiWrapper::m_font_texture { 0 } private
Referenced by destroy_font(), init_font(), and new_frame().
m_fonts_names
std::vector<std::string> Slic3r::GUI::ImGuiWrapper::m_fonts_names private
Referenced by get_fonts_names().
m_glyph_basic_ranges
const ImWchar* Slic3r::GUI::ImGuiWrapper::m_glyph_basic_ranges { nullptr } private
Referenced by set_language().
m_glyph_ranges
const ImWchar* Slic3r::GUI::ImGuiWrapper::m_glyph_ranges { nullptr } private
Referenced by init_font(), and set_language().
m_last_slider_status
LastSliderStatus Slic3r::GUI::ImGuiWrapper::m_last_slider_status private
Referenced by bbl_slider_float(), and get_last_slider_status().
m_mouse_buttons
unsigned Slic3r::GUI::ImGuiWrapper::m_mouse_buttons { 0 } private
Referenced by update_mouse_data().
m_new_frame_open
bool Slic3r::GUI::ImGuiWrapper::m_new_frame_open { false } private
Referenced by new_frame(), render(), and set_language().
m_style_scaling
float Slic3r::GUI::ImGuiWrapper::m_style_scaling { 1.0 } private
Referenced by bbl_combo_with_filter(), get_style_scaling(), and set_scaling().
TOOLBAR_WINDOW_FLAGS
int Slic3r::GUI::ImGuiWrapper::TOOLBAR_WINDOW_FLAGS static
Initial value:
= ImGuiWindowFlags_AlwaysAutoResize
                                 | ImGuiWindowFlags_NoMove
                                 | ImGuiWindowFlags_NoResize
                                 | ImGuiWindowFlags_NoCollapse
                                 | ImGuiWindowFlags_NoTitleBar
Referenced by Slic3r::GUI::GizmoObjectManipulation::do_render_move_window(), Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window(), and Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ImGuiWrapper.hpp
src/slic3r/GUI/ImGuiWrapper.cpp