OrcaSlicer: Slic3r::GUI::MachineInfoPanel Class Reference
Slic3r::GUI::MachineInfoPanel Class Reference
#include <src/slic3r/GUI/UpgradePanel.hpp>
Public Types
enum PanelType { ptUndef , ptPushPanel , ptOtaPanel , ptAmsPanel }
Public Member Functions
MachineInfoPanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL, const wxString &name=wxEmptyString)
~MachineInfoPanel ()
void on_sys_color_changed ()
void Update_printer_img (MachineObject *obj)
void init_bitmaps ()
Button * get_btn ()
void msw_rescale ()
void update (MachineObject *obj)
void update_version_text (MachineObject *obj)
void update_ams_ext (MachineObject *obj)
void show_status (int status, std::string upgrade_status_str="")
void show_ams (bool show=false, bool force_update=false)
void show_ext (bool show=false, bool force_update=false)
void on_upgrade_firmware (wxCommandEvent &event)
void on_consisitency_upgrade_firmware (wxCommandEvent &event)
Public Attributes
MachineObject * m_obj {nullptr}
FirmwareInfo m_ota_info
FirmwareInfo m_ams_info
bool is_upgrading = false
enum Slic3r::GUI::MachineInfoPanel::PanelType panel_type
Protected Member Functions
wxPanel * create_caption_panel (wxWindow *parent)
void upgrade_firmware_internal ()
void on_show_release_note (wxMouseEvent &event)
void confirm_upgrade (MachineObject *obj=nullptr)
Protected Attributes
wxPanel * m_panel_caption
wxStaticBitmap * m_upgrade_status_img
wxStaticText * m_caption_text
wxStaticBitmap * m_printer_img
wxStaticText * m_staticText_model_id
wxStaticText * m_staticText_model_id_val
wxStaticText * m_staticText_sn
wxStaticText * m_staticText_sn_val
wxStaticBitmap * m_ota_new_version_img
wxStaticText * m_staticText_ver
wxStaticText * m_staticText_ver_val
wxStaticLine * m_staticline
wxStaticBitmap * m_ams_img
AmsPanel * m_ahb_panel
wxStaticLine * m_staticline2
wxStaticBitmap * m_ext_img
ExtensionPanel * m_ext_panel
wxFlexGridSizer * m_ams_info_sizer
bool m_last_ams_show = true
wxBoxSizer * m_ams_sizer
bool m_last_ext_show = true
wxBoxSizer * m_ext_sizer
wxBoxSizer * m_upgrading_sizer
wxStaticText * m_staticText_upgrading_info
ProgressBar * m_upgrade_progress
wxStaticText * m_staticText_upgrading_percent
wxStaticBitmap * m_upgrade_retry_img
wxStaticText * m_staticText_release_note
Button * m_button_upgrade_firmware
AmsPanelHash m_amspanel_list
wxBitmap m_img_ext
wxBitmap m_img_monitor_ams
wxBitmap m_img_printer
wxBitmap upgrade_gray_icon
wxBitmap upgrade_green_icon
wxBitmap upgrade_yellow_icon
int last_status = -1
std::string last_status_str = ""
SecondaryCheckDialog * confirm_dlg = nullptr
Detailed Description
Member Enumeration Documentation
PanelType
enum Slic3r::GUI::MachineInfoPanel::PanelType
Enumerator
ptUndef
ptPushPanel
ptOtaPanel
ptAmsPanel
                   {
        ptUndef,
        ptPushPanel,
        ptOtaPanel,
        ptAmsPanel,
    }panel_type;
Constructor & Destructor Documentation
MachineInfoPanel()
Slic3r::GUI::MachineInfoPanel::MachineInfoPanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL, const wxString & name = wxEmptyString)
    :wxPanel(parent, id, pos, size, style)
{
    this->SetBackgroundColour(wxColour(255, 255, 255));
    init_bitmaps();
    wxBoxSizer *m_top_sizer = new wxBoxSizer(wxVERTICAL);
    m_panel_caption = create_caption_panel(this);
    m_top_sizer->Add(m_panel_caption, 0, wxEXPAND | wxALL, 0);
    wxBoxSizer *m_main_sizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_main_left_sizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_ota_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_printer_img = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxSize(FromDIP(200), FromDIP(200)));
    m_printer_img->SetBitmap(m_img_printer);
    m_ota_sizer->Add(m_printer_img, 0, wxALIGN_CENTER_VERTICAL | wxALL, 0);
    wxBoxSizer *m_ota_content_sizer = new wxBoxSizer(wxVERTICAL);
    m_ota_content_sizer->Add(0, 0, 1, wxEXPAND, 0);
    wxFlexGridSizer *m_ota_info_sizer = new wxFlexGridSizer(0, 2, 0, 0);
    m_ota_info_sizer->AddGrowableCol(1);
    m_ota_info_sizer->SetFlexibleDirection(wxHORIZONTAL);
    m_ota_info_sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
    m_staticText_model_id = new wxStaticText(this, wxID_ANY, _L("Model:"), wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_model_id->Wrap(-1);
    m_staticText_model_id->SetFont(Label::Head_14);
    m_ota_info_sizer->Add(m_staticText_model_id, 0, wxALIGN_RIGHT | wxALL, FromDIP(5));
    m_staticText_model_id_val = new wxStaticText(this, wxID_ANY, "-", wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_model_id_val->Wrap(-1);
    m_ota_info_sizer->Add(m_staticText_model_id_val, 0, wxALL | wxEXPAND, FromDIP(5));
    m_staticText_sn = new wxStaticText(this, wxID_ANY, _L("Serial:"), wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_sn->Wrap(-1);
    m_staticText_sn->SetFont(Label::Head_14);
    m_ota_info_sizer->Add(m_staticText_sn, 0, wxALIGN_RIGHT | wxALL | wxEXPAND, FromDIP(5));
    m_staticText_sn_val = new wxStaticText(this, wxID_ANY, "-", wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_sn_val->Wrap(-1);
    m_ota_info_sizer->Add(m_staticText_sn_val, 0, wxALL | wxEXPAND, FromDIP(5));
    wxBoxSizer *m_ota_ver_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_ota_ver_sizer->Add(0, 0, 1, wxEXPAND, 0);
    m_ota_new_version_img = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxSize(FromDIP(5), FromDIP(5)));
    m_ota_new_version_img->SetBitmap(upgrade_green_icon);
    m_ota_ver_sizer->Add(m_ota_new_version_img, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    m_staticText_ver = new wxStaticText(this, wxID_ANY, _L("Version:"), wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_ver->Wrap(-1);
    m_staticText_ver->SetFont(Label::Head_14);
    m_ota_ver_sizer->Add(m_staticText_ver, 0, wxALL, FromDIP(5));
    m_ota_info_sizer->Add(m_ota_ver_sizer, 0, wxEXPAND, 0);
    m_staticText_ver_val = new wxStaticText(this, wxID_ANY, "-", wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_ver_val->Wrap(-1);
    m_ota_info_sizer->Add(m_staticText_ver_val, 0, wxALL | wxEXPAND, FromDIP(5));
    m_ota_content_sizer->Add(m_ota_info_sizer, 0, wxEXPAND, 0);
    m_ota_content_sizer->Add(0, 0, 1, wxEXPAND, 0);
    m_ota_sizer->Add(m_ota_content_sizer, 1, wxEXPAND, 0);
    m_main_left_sizer->Add(m_ota_sizer, 0, wxEXPAND, 0);
    m_staticline = new wxStaticLine(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_HORIZONTAL);
    m_staticline->SetBackgroundColour(wxColour(206,206,206));
    m_staticline->Show(false);
    m_main_left_sizer->Add(m_staticline, 0, wxEXPAND | wxLEFT, FromDIP(40));
    m_ams_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_ams_img   = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxSize(FromDIP(200), FromDIP(200)));
    m_ams_img->SetBitmap(m_img_monitor_ams);
    m_ams_sizer->Add(m_ams_img, 0, wxALIGN_TOP | wxALL, FromDIP(5));
    wxBoxSizer *m_ams_content_sizer = new wxBoxSizer(wxVERTICAL);
    m_ams_content_sizer->Add(0, 40, 0, wxEXPAND, FromDIP(5));
    m_ahb_panel = new AmsPanel(this, wxID_ANY);
    m_ahb_panel->m_staticText_ams->SetLabel("AMS HUB");
    m_ams_content_sizer->Add(m_ahb_panel, 0, wxEXPAND, 0);
    m_ams_info_sizer = new wxFlexGridSizer(0, 2, FromDIP(30), FromDIP(30));
    m_ams_info_sizer->SetFlexibleDirection(wxHORIZONTAL);
    m_ams_info_sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_ALL);
    for (auto i = 0; i < 4; i++) {
        auto amspanel = new AmsPanel(this, wxID_ANY);
        m_ams_info_sizer->Add(amspanel, 1, wxEXPAND, 5);
        amspanel->Hide();
        /*AmsPanelItem item = AmsPanelItem();
        item.id           = i;
        item.item         = amspanel;*/
        m_amspanel_list.Add(amspanel);
    }
    m_ams_content_sizer->Add(m_ams_info_sizer, 0, wxEXPAND, 0);
    m_ams_sizer->Add(m_ams_content_sizer, 1, wxEXPAND, 0);
    m_main_left_sizer->Add(m_ams_sizer, 0, wxEXPAND, 0);
    //Hide ams
    show_ams(false, true);
    m_staticline2 = new wxStaticLine(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_HORIZONTAL);
    m_staticline2->SetBackgroundColour(wxColour(206, 206, 206));
    //m_staticline2->Show(false);
    m_main_left_sizer->Add(m_staticline2, 0, wxEXPAND | wxLEFT, FromDIP(40));
    m_ext_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_ext_img = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxSize(FromDIP(200), FromDIP(200)));
    m_ext_img->SetBitmap(m_img_ext);
    m_ext_sizer->Add(m_ext_img, 0, wxALIGN_TOP | wxALL, FromDIP(5));
    wxBoxSizer* ext_content_sizer = new wxBoxSizer(wxVERTICAL);
    ext_content_sizer->Add(0, 40, 0, wxEXPAND, FromDIP(5));
    m_ext_panel = new ExtensionPanel(this, wxID_ANY);
    ext_content_sizer->Add(m_ext_panel, 0, wxEXPAND, 0);
    m_ext_sizer->Add(ext_content_sizer, 1, wxEXPAND, 0);
    m_main_left_sizer->Add(m_ext_sizer, 0, wxEXPAND, 0);
    m_main_sizer->Add(m_main_left_sizer, 1, wxEXPAND, 0);
    wxBoxSizer *m_main_right_sizer = new wxBoxSizer(wxVERTICAL);
    m_main_right_sizer->SetMinSize(wxSize(FromDIP(137), -1));
    m_main_right_sizer->Add(0, FromDIP(50), 0, wxEXPAND, FromDIP(5));
    m_button_upgrade_firmware = new Button(this, _L("Update firmware"));
    StateColor btn_bg(std::pair<wxColour, int>(wxColour(255, 255, 255), StateColor::Disabled), std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed),
                      std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered), std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Enabled),
                      std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    StateColor btn_bd(std::pair<wxColour, int>(wxColour(144, 144, 144), StateColor::Disabled), std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Enabled));
    StateColor btn_text(std::pair<wxColour, int>(wxColour(144, 144, 144), StateColor::Disabled), std::pair<wxColour, int>(wxColour(255, 255, 255), StateColor::Enabled));
    m_button_upgrade_firmware->SetBackgroundColor(btn_bg);
    m_button_upgrade_firmware->SetBorderColor(btn_bd);
    m_button_upgrade_firmware->SetTextColor(btn_text);
    m_button_upgrade_firmware->SetFont(Label::Body_10);
    m_button_upgrade_firmware->SetMinSize(wxSize(FromDIP(-1), FromDIP(24)));
    m_button_upgrade_firmware->SetCornerRadius(FromDIP(12));
    m_main_right_sizer->Add(m_button_upgrade_firmware, 0, wxALIGN_CENTER_HORIZONTAL | wxALL, FromDIP(5));
    m_staticText_upgrading_info = new wxStaticText(this, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_upgrading_info->Wrap(-1);
    m_main_right_sizer->Add(m_staticText_upgrading_info, 0, wxALIGN_CENTER_HORIZONTAL | wxALL, FromDIP(5));
    m_upgrading_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_upgrading_sizer->Add(0, 0, 1, wxEXPAND, 0);
    m_upgrade_progress = new ProgressBar(this, wxID_ANY, 100, wxDefaultPosition, wxDefaultSize);
    m_upgrade_progress->SetValue(0);
    m_upgrade_progress->SetSize(wxSize(FromDIP(54), FromDIP(14)));
    m_upgrade_progress->SetMinSize(wxSize(FromDIP(54), FromDIP(14)));
    m_upgrading_sizer->Add(m_upgrade_progress, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    m_staticText_upgrading_percent = new wxStaticText(this, wxID_ANY, "", wxDefaultPosition, wxDefaultSize);
    m_staticText_upgrading_percent->Wrap(-1);
    m_upgrading_sizer->Add(m_staticText_upgrading_percent, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    m_upgrade_retry_img = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize);
    m_upgrading_sizer->Add(m_upgrade_retry_img, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    m_upgrading_sizer->Add(0, 0, 1, wxEXPAND, 0);
    m_main_right_sizer->Add(m_upgrading_sizer, 0, wxEXPAND, 0);
    wxBoxSizer *sizer_release_note = new wxBoxSizer(wxVERTICAL);
    m_staticText_release_note = new wxStaticText(this, wxID_ANY, _L("Release Note"), wxDefaultPosition, wxDefaultSize);
    m_staticText_release_note->Wrap(-1);
    m_staticText_release_note->SetForegroundColour(wxColour(0x1F,0x8E,0xEA));
    auto line_release_note = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    line_release_note->SetBackgroundColour(wxColour(0x1F, 0x8E, 0xEA));
    sizer_release_note->Add(m_staticText_release_note, 0, wxALL, 0);
    sizer_release_note->Add(line_release_note, 1, wxEXPAND | wxALL, 0);
    m_main_right_sizer->Add(sizer_release_note, 0, wxALIGN_CENTER_HORIZONTAL | wxALL, 0);
    m_main_right_sizer->Add(0, 0, 1, wxEXPAND, 0);
    m_main_sizer->Add(m_main_right_sizer, 0, wxEXPAND, 0);
    m_top_sizer->Add(m_main_sizer, 1, wxEXPAND, 0);
    this->SetSizer(m_top_sizer);
    this->Layout();
    // Connect Events
    m_upgrade_retry_img->Bind(wxEVT_LEFT_UP, [this](auto &e) {
        upgrade_firmware_internal();
        });
    m_staticText_release_note->Bind(wxEVT_LEFT_DOWN, &MachineInfoPanel::on_show_release_note, this);
    m_button_upgrade_firmware->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MachineInfoPanel::on_upgrade_firmware), NULL, this);
    wxGetApp().UpdateDarkUIWin(this);
}
References _L, Label::Body_10, create_caption_panel(), StateColor::Disabled, StateColor::Enabled, Label::Head_14, StateColor::Hovered, init_bitmaps(), m_ahb_panel, m_ams_img, m_ams_info_sizer, m_ams_sizer, m_amspanel_list, m_button_upgrade_firmware, m_ext_img, m_ext_panel, m_ext_sizer, m_img_ext, m_img_monitor_ams, m_img_printer, m_ota_new_version_img, m_panel_caption, m_printer_img, m_staticline, m_staticline2, Slic3r::GUI::AmsPanel::m_staticText_ams, m_staticText_model_id, m_staticText_model_id_val, m_staticText_release_note, m_staticText_sn, m_staticText_sn_val, m_staticText_upgrading_info, m_staticText_upgrading_percent, m_staticText_ver, m_staticText_ver_val, m_upgrade_progress, m_upgrade_retry_img, m_upgrading_sizer, StateColor::Normal, NULL, on_show_release_note(), on_upgrade_firmware(), StateColor::Pressed, Slic3r::GUI::ProgressBar, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetFont(), Button::SetMinSize(), ProgressBar::SetMinSize(), Button::SetTextColor(), ProgressBar::SetValue(), show_ams(), upgrade_firmware_internal(), upgrade_green_icon, and wxStaticText.
~MachineInfoPanel()
Slic3r::GUI::MachineInfoPanel::~MachineInfoPanel ()
{
    // Disconnect Events
    m_button_upgrade_firmware->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(MachineInfoPanel::on_upgrade_firmware), NULL, this);
    if (confirm_dlg != nullptr)
        delete confirm_dlg;
}
References confirm_dlg, m_button_upgrade_firmware, NULL, and on_upgrade_firmware().
Member Function Documentation
confirm_upgrade()
void Slic3r::GUI::MachineInfoPanel::confirm_upgrade (MachineObject * obj = nullptr) protected
{
    if (obj) {
        obj->command_upgrade_confirm();
        obj->upgrade_display_state = MachineObject::UpgradingDisplayState::UpgradingInProgress;
        obj->upgrade_display_hold_count = HOLD_COUNT_MAX;
        // enter in progress status first
        this->show_status(MachineObject::UpgradingDisplayState::UpgradingInProgress);
    }
}
References Slic3r::MachineObject::command_upgrade_confirm(), HOLD_COUNT_MAX, show_status(), Slic3r::MachineObject::upgrade_display_hold_count, Slic3r::MachineObject::upgrade_display_state, and Slic3r::MachineObject::UpgradingInProgress.
Referenced by on_upgrade_firmware(), and upgrade_firmware_internal().
create_caption_panel()
wxPanel * Slic3r::GUI::MachineInfoPanel::create_caption_panel (wxWindow * parent) protected
{
    auto caption_panel = new wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    caption_panel->SetBackgroundColour(wxColour(248, 248, 248));
    caption_panel->SetMinSize(wxSize(FromDIP(925), FromDIP(36)));
    wxBoxSizer *m_caption_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_caption_sizer->Add(17, 0, 0, wxEXPAND, 0);
    m_upgrade_status_img = new wxStaticBitmap(caption_panel, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxSize(FromDIP(5), FromDIP(5)));
    m_upgrade_status_img->SetBitmap(upgrade_gray_icon);
    m_upgrade_status_img->Hide();
    m_caption_sizer->Add(m_upgrade_status_img, 0, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    m_caption_text = new wxStaticText(caption_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize);
    m_caption_text->SetForegroundColour("#262E30");
    m_caption_text->Wrap(-1);
    m_caption_sizer->Add(m_caption_text, 1, wxALIGN_CENTER_VERTICAL | wxALL, FromDIP(5));
    caption_panel->SetSizer(m_caption_sizer);
    caption_panel->Layout();
    m_caption_sizer->Fit(caption_panel);
    return caption_panel;
}
References m_caption_text, m_upgrade_status_img, upgrade_gray_icon, and wxStaticText.
Referenced by MachineInfoPanel().
get_btn()
Button * Slic3r::GUI::MachineInfoPanel::get_btn () inline
                      {
        return m_button_upgrade_firmware;
    }
References m_button_upgrade_firmware.
init_bitmaps()
void Slic3r::GUI::MachineInfoPanel::init_bitmaps ()
{
    m_img_printer        = create_scaled_bitmap("printer_thumbnail", nullptr, 160);
    m_img_monitor_ams    = create_scaled_bitmap("monitor_upgrade_ams", nullptr, 200);
    m_img_ext            = create_scaled_bitmap("monitor_upgrade_ext", nullptr, 200);
    upgrade_green_icon   = create_scaled_bitmap("monitor_upgrade_online", nullptr, 5);
    upgrade_gray_icon    = create_scaled_bitmap("monitor_upgrade_offline", nullptr, 5);
    upgrade_yellow_icon  = create_scaled_bitmap("monitor_upgrade_busy", nullptr, 5);
}
References create_scaled_bitmap(), m_img_ext, m_img_monitor_ams, m_img_printer, upgrade_gray_icon, upgrade_green_icon, and upgrade_yellow_icon.
Referenced by MachineInfoPanel(), and msw_rescale().
msw_rescale()
void Slic3r::GUI::MachineInfoPanel::msw_rescale ()
{
    init_bitmaps();
    m_button_upgrade_firmware->SetSize(wxSize(FromDIP(-1), FromDIP(24)));
    m_button_upgrade_firmware->SetMinSize(wxSize(FromDIP(-1), FromDIP(24)));
    m_button_upgrade_firmware->SetMaxSize(wxSize(FromDIP(-1), FromDIP(24)));
    m_printer_img->SetBitmap(m_img_printer);
    m_ams_img->SetBitmap(m_img_monitor_ams);
    m_ext_img->SetBitmap(m_img_ext);
    Layout();
    Fit();
}
References init_bitmaps(), m_ams_img, m_button_upgrade_firmware, m_ext_img, m_img_ext, m_img_monitor_ams, m_img_printer, m_printer_img, and Button::SetMinSize().
Referenced by Slic3r::GUI::UpgradePanel::msw_rescale().
on_consisitency_upgrade_firmware()
void Slic3r::GUI::MachineInfoPanel::on_consisitency_upgrade_firmware (wxCommandEvent & event)
{
    if (confirm_dlg == nullptr) {
        confirm_dlg = new SecondaryCheckDialog(this->GetParent(), wxID_ANY, _L("Update firmware"));
        confirm_dlg->Bind(EVT_SECONDARY_CHECK_CONFIRM, [this](wxCommandEvent& e) {
            if (m_obj) {
                m_obj->command_consistency_upgrade_confirm();
            }
        });
    }
    confirm_dlg->update_text(_L("Are you sure you want to update? This will take about 10 minutes. Do not turn off the power while the printer is updating."));
    confirm_dlg->on_show();
}
References _L, Slic3r::MachineObject::command_consistency_upgrade_confirm(), confirm_dlg, m_obj, Slic3r::GUI::SecondaryCheckDialog::on_show(), and Slic3r::GUI::SecondaryCheckDialog::update_text().
on_show_release_note()
void Slic3r::GUI::MachineInfoPanel::on_show_release_note (wxMouseEvent & event) protected
{
    DeviceManager *dev = wxGetApp().getDeviceManager();
    if (!dev) return;
    wxString next_version_release_note;
    wxString now_version_release_note;
    std::string version_number            = "";
    for (auto iter : m_obj->firmware_list) {
        if (iter.version == m_obj->ota_new_version_number) {
            version_number            = m_obj->ota_new_version_number;
            next_version_release_note = wxString::FromUTF8(iter.description);
        }
        if (iter.version == m_obj->get_ota_version()) {
            version_number           = m_obj->get_ota_version();
            now_version_release_note = wxString::FromUTF8(iter.description);
        }
    }
    ReleaseNoteDialog dlg;
    if (!m_obj->ota_new_version_number.empty()) {
        dlg.update_release_note(next_version_release_note, version_number);
        dlg.ShowModal();
        return;
    }
    if (!m_obj->get_ota_version().empty()) {
        dlg.update_release_note(now_version_release_note, version_number);
        dlg.ShowModal();
        return;
    }
}
References Slic3r::MachineObject::firmware_list, Slic3r::MachineObject::get_ota_version(), m_obj, Slic3r::MachineObject::ota_new_version_number, Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::GUI::ReleaseNoteDialog::update_release_note().
Referenced by MachineInfoPanel().
on_sys_color_changed()
void Slic3r::GUI::MachineInfoPanel::on_sys_color_changed ()
{
    if (m_obj) {
        Update_printer_img(m_obj);
    }
}
References m_obj, and Update_printer_img().
Referenced by Slic3r::GUI::UpgradePanel::on_sys_color_changed().
on_upgrade_firmware()
void Slic3r::GUI::MachineInfoPanel::on_upgrade_firmware (wxCommandEvent & event)
{
    if (confirm_dlg == nullptr) {
        confirm_dlg = new SecondaryCheckDialog(this->GetParent(), wxID_ANY, _L("Update firmware"));
        confirm_dlg->Bind(EVT_SECONDARY_CHECK_CONFIRM, [this](wxCommandEvent& e) {
                this->confirm_upgrade(m_obj);
        });
    }
    confirm_dlg->update_text(_L("Are you sure you want to update? This will take about 10 minutes. Do not turn off the power while the printer is updating."));
    confirm_dlg->on_show();
}
References _L, confirm_dlg, confirm_upgrade(), m_obj, Slic3r::GUI::SecondaryCheckDialog::on_show(), and Slic3r::GUI::SecondaryCheckDialog::update_text().
Referenced by MachineInfoPanel(), and ~MachineInfoPanel().
show_ams()
void Slic3r::GUI::MachineInfoPanel::show_ams (bool show = false, bool force_update = false)
{
    if (m_last_ams_show != show || force_update) {
        m_ams_img->Show(show);
        m_ams_sizer->Show(show);
        m_staticline->Show(show);
        BOOST_LOG_TRIVIAL(trace) << "upgrade: show_ams = " << show;
    }
    m_last_ams_show = show;
}
References m_ams_img, m_ams_sizer, m_last_ams_show, m_staticline, and Slic3r::trace().
Referenced by MachineInfoPanel(), and update_ams_ext().
show_ext()
void Slic3r::GUI::MachineInfoPanel::show_ext (bool show = false, bool force_update = false)
{
    if (m_last_ext_show != show || force_update) {
        m_ext_img->Show(show);
        m_ext_sizer->Show(show);
        m_staticline2->Show(show);
        BOOST_LOG_TRIVIAL(trace) << "upgrade: show_ext = " << show;
    }
    m_last_ext_show = show;
}
References m_ext_img, m_ext_sizer, m_last_ext_show, m_staticline2, and Slic3r::trace().
Referenced by update_ams_ext().
show_status()
void Slic3r::GUI::MachineInfoPanel::show_status (int status, std::string upgrade_status_str = "")
{
    if (last_status == status && last_status_str == upgrade_status_str) return;
    last_status     = status;
    last_status_str = upgrade_status_str;
    BOOST_LOG_TRIVIAL(trace) << "MachineInfoPanel: show_status = " << status << ", str = " << upgrade_status_str;
    Freeze();
    if (status == (int)MachineObject::UpgradingDisplayState::UpgradingUnavaliable) {
        m_button_upgrade_firmware->Show();
        m_button_upgrade_firmware->Disable();
        for (size_t i = 0; i < m_upgrading_sizer->GetItemCount(); i++) {
            m_upgrading_sizer->Show(false);
        }
        m_upgrade_retry_img->Hide();
        m_staticText_upgrading_info->Hide();
        m_staticText_upgrading_percent->Hide();
    } else if (status == (int) MachineObject::UpgradingDisplayState::UpgradingAvaliable) {
        m_button_upgrade_firmware->Show();
        m_button_upgrade_firmware->Enable();
        for (size_t i = 0; i < m_upgrading_sizer->GetItemCount(); i++) { m_upgrading_sizer->Show(false); }
        m_upgrade_retry_img->Hide();
        m_staticText_upgrading_info->Hide();
        m_staticText_upgrading_percent->Hide();
    } else if (status == (int) MachineObject::UpgradingDisplayState::UpgradingInProgress) {
        m_button_upgrade_firmware->Disable();
        for (size_t i = 0; i < m_upgrading_sizer->GetItemCount(); i++) { m_upgrading_sizer->Show(true); }
        m_upgrade_retry_img->Hide();
        m_staticText_upgrading_info->Show();
        m_staticText_upgrading_info->SetLabel(_L("Updating"));
        m_staticText_upgrading_info->SetForegroundColour(TEXT_NORMAL_CLR);
        m_staticText_upgrading_percent->SetForegroundColour(TEXT_NORMAL_CLR);
        m_staticText_upgrading_percent->Show();
    } else if (status == (int) MachineObject::UpgradingDisplayState::UpgradingFinished) {
        if (upgrade_status_str == "UPGRADE_FAIL") {
            m_staticText_upgrading_info->SetLabel(_L("Updating failed"));
            m_staticText_upgrading_info->SetForegroundColour(TEXT_FAILED_CLR);
            for (size_t i = 0; i < m_upgrading_sizer->GetItemCount(); i++) { m_upgrading_sizer->Show(true); }
            m_button_upgrade_firmware->Disable();
            m_staticText_upgrading_info->Show();
            m_staticText_upgrading_percent->Show();
            m_upgrade_retry_img->Show();
        } else {
            m_staticText_upgrading_info->SetLabel(_L("Updating successful"));
            m_staticText_upgrading_info->Show();
            for (size_t i = 0; i < m_upgrading_sizer->GetItemCount(); i++) { m_upgrading_sizer->Show(true); }
            m_button_upgrade_firmware->Disable();
            m_staticText_upgrading_info->SetForegroundColour(TEXT_NORMAL_CLR);
            m_staticText_upgrading_percent->SetForegroundColour(TEXT_NORMAL_CLR);
            m_staticText_upgrading_percent->Show();
            m_upgrade_retry_img->Hide();
        }
    } else {
        ;
    }
    Layout();
    Thaw();
}
References _L, Button::Enable(), last_status, last_status_str, m_button_upgrade_firmware, m_staticText_upgrading_info, m_staticText_upgrading_percent, m_upgrade_retry_img, m_upgrading_sizer, Slic3r::GUI::TEXT_FAILED_CLR, Slic3r::GUI::TEXT_NORMAL_CLR, Slic3r::trace(), Slic3r::MachineObject::UpgradingAvaliable, Slic3r::MachineObject::UpgradingFinished, Slic3r::MachineObject::UpgradingInProgress, and Slic3r::MachineObject::UpgradingUnavaliable.
Referenced by confirm_upgrade(), and update().
update()
void Slic3r::GUI::MachineInfoPanel::update (MachineObject * obj)
{
    if (m_obj != obj)
        Update_printer_img(obj);
    m_obj = obj;
    if (obj) {
        this->Freeze();
        //update online status img
        m_panel_caption->Freeze();
        if (!obj->is_connected()) {
            m_upgrade_status_img->SetBitmap(upgrade_gray_icon);
            wxString caption_text = wxString::Format("%s(%s)", from_u8(obj->dev_name), _L("Offline"));
            m_caption_text->SetLabelText(caption_text);
            show_status(MachineObject::UpgradingDisplayState::UpgradingUnavaliable);
        } else {
            show_status(obj->upgrade_display_state, obj->upgrade_status);
            if (obj->upgrade_display_state == (int) MachineObject::UpgradingDisplayState::UpgradingUnavaliable) {
                if (obj->can_abort()) {
                    wxString caption_text = wxString::Format("%s(%s)", from_u8(obj->dev_name), _L("Printing"));
                    m_caption_text->SetLabelText(caption_text);
                } else {
                    wxString caption_text = wxString::Format("%s", from_u8(obj->dev_name));
                    m_caption_text->SetLabelText(caption_text);
                }
                m_upgrade_status_img->SetBitmap(upgrade_yellow_icon);
            } else {
                wxString caption_text = wxString::Format("%s(%s)", from_u8(obj->dev_name), _L("Idle"));
                m_caption_text->SetLabelText(caption_text);
                m_upgrade_status_img->SetBitmap(upgrade_green_icon);
            }
        }
        m_panel_caption->Layout();
        m_panel_caption->Thaw();
        // update version
        update_version_text(obj);
        // update ams and extension
        update_ams_ext(obj);
        //update progress
        int upgrade_percent = obj->get_upgrade_percent();
        if (obj->upgrade_display_state == (int) MachineObject::UpgradingDisplayState::UpgradingInProgress) {
            m_upgrade_progress->SetValue(upgrade_percent);
            m_staticText_upgrading_percent->SetLabelText(wxString::Format("%d%%", upgrade_percent));
        } else if (obj->upgrade_display_state == (int) MachineObject::UpgradingDisplayState::UpgradingFinished) {
            wxString result_text = obj->get_upgrade_result_str(obj->upgrade_err_code);
            m_upgrade_progress->SetValue(upgrade_percent);
            m_staticText_upgrading_percent->SetLabelText(wxString::Format("%d%%", upgrade_percent));
        }
        wxString model_id_text = obj->get_printer_type_display_str();
        m_staticText_model_id_val->SetLabelText(model_id_text);
        wxString sn_text = obj->dev_id;
        m_staticText_sn_val->SetLabelText(sn_text.MakeUpper());
        this->Layout();
        this->Thaw();
    }
}
References _L, Slic3r::MachineObject::can_abort(), Slic3r::MachineObject::dev_id, Slic3r::MachineObject::dev_name, Slic3r::GUI::from_u8(), Slic3r::MachineObject::get_printer_type_display_str(), Slic3r::MachineObject::get_upgrade_percent(), Slic3r::MachineObject::get_upgrade_result_str(), Slic3r::MachineObject::is_connected(), m_caption_text, m_obj, m_panel_caption, m_staticText_model_id_val, m_staticText_sn_val, m_staticText_upgrading_percent, m_upgrade_progress, m_upgrade_status_img, ProgressBar::SetValue(), show_status(), update_ams_ext(), Update_printer_img(), update_version_text(), Slic3r::MachineObject::upgrade_display_state, Slic3r::MachineObject::upgrade_err_code, upgrade_gray_icon, upgrade_green_icon, Slic3r::MachineObject::upgrade_status, upgrade_yellow_icon, Slic3r::MachineObject::UpgradingFinished, Slic3r::MachineObject::UpgradingInProgress, and Slic3r::MachineObject::UpgradingUnavaliable.
Referenced by Slic3r::GUI::UpgradePanel::update().
update_ams_ext()
void Slic3r::GUI::MachineInfoPanel::update_ams_ext (MachineObject * obj)
{
    bool has_hub_model = false;
    //hub
    if (!obj->online_ahb || obj->module_vers.find("ahb") == obj->module_vers.end())
        m_ahb_panel->Hide();
    else {
        has_hub_model = true;
        show_ams(true);
        for (auto i = 0; i < m_amspanel_list.GetCount(); i++) {
            AmsPanel *amspanel = m_amspanel_list[i];
            amspanel->Hide();
        }
        m_ahb_panel->Show();
        wxString hub_sn = "-";
        if (!obj->module_vers.find("ahb")->second.sn.empty()) {
            wxString sn_text = obj->module_vers.find("ahb")->second.sn;
            hub_sn           = sn_text.MakeUpper();
        }
        wxString hub_ver = "-";
        if (!obj->module_vers.find("ahb")->second.sw_ver.empty()) {
            wxString sn_text = obj->module_vers.find("ahb")->second.sw_ver;
            hub_ver          = sn_text.MakeUpper();
        }
       /* auto ver_item = obj->new_ver_list.find("ahb");
        if (ver_item != obj->new_ver_list.end()) {
            m_ahb_panel->m_ams_new_version_img->Show();
            hub_ver = wxString::Format("%s->%s", hub_ver, ver_item->second.sw_new_ver);
        } else {
            m_ahb_panel->m_ams_new_version_img->Hide();
            hub_ver = wxString::Format("%s(%s)", hub_ver, _L("Latest version"));
        }*/
        if (obj->new_ver_list.empty() && !obj->m_new_ver_list_exist) {
            if (obj->upgrade_new_version && obj->ahb_new_version_number.compare(obj->module_vers.find("ahb")->second.sw_ver) != 0) {
                m_ahb_panel->m_ams_new_version_img->Show();
                if (obj->ahb_new_version_number.empty()) {
                    hub_ver = wxString::Format("%s", obj->module_vers.find("ahb")->second.sw_ver);
                } else {
                    hub_ver = wxString::Format("%s->%s", obj->module_vers.find("ahb")->second.sw_ver, obj->ahb_new_version_number);
                }
            } else {
                m_ahb_panel->m_ams_new_version_img->Hide();
                if (obj->ahb_new_version_number.empty()) {
                    wxString ver_text = wxString::Format("%s", obj->module_vers.find("ahb")->second.sw_ver);
                    hub_ver           = ver_text;
                } else {
                    wxString ver_text = wxString::Format("%s(%s)", obj->module_vers.find("ahb")->second.sw_ver, _L("Latest version"));
                    hub_ver           = ver_text;
                }
            }
        } else {
            auto ver_item = obj->new_ver_list.find("ahb");
            if (ver_item == obj->new_ver_list.end()) {
                m_ahb_panel->m_ams_new_version_img->Hide();
                wxString ver_text = wxString::Format("%s(%s)", obj->module_vers.find("ahb")->second.sw_ver, _L("Latest version"));
                hub_ver           = ver_text;
            } else {
                if (ver_item->second.sw_new_ver != ver_item->second.sw_ver) {
                    m_ahb_panel->m_ams_new_version_img->Show();
                    wxString ver_text = wxString::Format("%s->%s", ver_item->second.sw_ver, ver_item->second.sw_new_ver);
                    hub_ver           = ver_text;
                } else {
                    m_ahb_panel->m_ams_new_version_img->Hide();
                    wxString ver_text = wxString::Format("%s(%s)", ver_item->second.sw_ver, _L("Latest version"));
                    hub_ver           = ver_text;
                }
            }
        }
        m_ahb_panel->m_staticText_ams_sn_val->SetLabelText(hub_sn);
        m_ahb_panel->m_staticText_ams_ver_val->SetLabelText(hub_ver);
    }
    //ams
    if (obj->ams_exist_bits != 0) {
        show_ams(true);
        std::map<int, MachineObject::ModuleVersionInfo> ver_list = obj->get_ams_version();
        AmsPanelHash::iterator iter = m_amspanel_list.begin();
        for (auto i = 0; i < m_amspanel_list.GetCount(); i++) {
            AmsPanel *amspanel = m_amspanel_list[i];
             amspanel->Hide();
        }
        auto ams_index = 0;
        for (std::map<std::string, Ams *>::iterator iter = obj->amsList.begin(); iter != obj->amsList.end(); iter++) {
            wxString ams_name;
            wxString ams_sn;
            wxString ams_ver;
            AmsPanel *amspanel = m_amspanel_list[ams_index];
            amspanel->Show();
            auto it = ver_list.find(atoi(iter->first.c_str()));
            auto ams_id = std::stoi(iter->second->id);
            wxString ams_text = wxString::Format("AMS%s", std::to_string(ams_id + 1));
            ams_name = ams_text;
            if (it == ver_list.end()) {
                // hide this ams
                ams_sn   = "-";
                ams_ver  = "-";
            } else {
                // update ams img
                if (m_obj->upgrade_display_state == (int)MachineObject::UpgradingDisplayState::UpgradingInProgress) {
                    ams_ver = "-";
                    amspanel->m_ams_new_version_img->Hide();
                }
                else {
                    if (obj->new_ver_list.empty() && !obj->m_new_ver_list_exist) {
                        if (obj->upgrade_new_version
                            && obj->ams_new_version_number.compare(it->second.sw_ver) != 0) {
                            amspanel->m_ams_new_version_img->Show();
                            if (obj->ams_new_version_number.empty()) {
                                ams_ver = wxString::Format("%s", it->second.sw_ver);
                            } else {
                                ams_ver = wxString::Format("%s->%s", it->second.sw_ver, obj->ams_new_version_number);
                            }
                        } else {
                            amspanel->m_ams_new_version_img->Hide();
                            if (obj->ams_new_version_number.empty()) {
                                wxString ver_text = wxString::Format("%s", it->second.sw_ver);
                                ams_ver           = ver_text;
                            } else {
                                wxString ver_text = wxString::Format("%s(%s)", it->second.sw_ver, _L("Latest version"));
                                ams_ver           = ver_text;
                            }
                        }
                    } else {
                        std::string ams_idx = (boost::format("ams/%1%") % ams_id).str();
                        auto        ver_item = obj->new_ver_list.find(ams_idx);
                        if (ver_item == obj->new_ver_list.end()) {
                            amspanel->m_ams_new_version_img->Hide();
                            wxString ver_text = wxString::Format("%s(%s)", it->second.sw_ver, _L("Latest version"));
                            ams_ver           = ver_text;
                        } else {
                            if (ver_item->second.sw_new_ver != ver_item->second.sw_ver) {
                                amspanel->m_ams_new_version_img->Show();
                                wxString ver_text = wxString::Format("%s->%s", ver_item->second.sw_ver, ver_item->second.sw_new_ver);
                                ams_ver           = ver_text;
                            } else {
                                amspanel->m_ams_new_version_img->Hide();
                                wxString ver_text = wxString::Format("%s(%s)", ver_item->second.sw_ver, _L("Latest version"));
                                ams_ver           = ver_text;
                            }
                        }
                    }
                }
                // update ams sn
                if (it->second.sn.empty()) {
                    ams_sn = "-";
                } else {
                    wxString sn_text = it->second.sn;
                    ams_sn = sn_text.MakeUpper();
                }
            }
            amspanel->m_staticText_ams->SetLabelText(ams_name);
            amspanel->m_staticText_ams_sn_val->SetLabelText(ams_sn);
            amspanel->m_staticText_ams_ver_val->SetLabelText(ams_ver);
            ams_index++;
        }
    } else {
        if (!has_hub_model) { show_ams(false); }
    }
    //ext
    auto ext_module = obj->module_vers.find("ext");
    if (ext_module == obj->module_vers.end())
        show_ext(false);
    else {
        wxString sn_text = ext_module->second.sn;
        sn_text = sn_text.MakeUpper();
        wxString ext_ver = "";
        // has new version
        bool has_new_version = false;
        auto new_ext_ver = obj->new_ver_list.find("ext");
        if (new_ext_ver != obj->new_ver_list.end())
            has_new_version = true;
        if (has_new_version) {
            m_ext_panel->m_ext_new_version_img->Show();
            ext_ver = wxString::Format("%s->%s", new_ext_ver->second.sw_ver, new_ext_ver->second.sw_new_ver);
        } else {
            m_ext_panel->m_ext_new_version_img->Hide();
            ext_ver = wxString::Format("%s(%s)", ext_module->second.sw_ver, _L("Latest version"));
        }
        // set sn and version
        m_ext_panel->m_staticText_ext_sn_val->SetLabelText(sn_text);
        m_ext_panel->m_staticText_ext_ver_val->SetLabelText(ext_ver);
        show_ext(true);
    }
    this->Layout();
    this->Fit();
}
References _L, Slic3r::MachineObject::ahb_new_version_number, Slic3r::MachineObject::ams_exist_bits, Slic3r::MachineObject::ams_new_version_number, Slic3r::MachineObject::amsList, Slic3r::MachineObject::get_ams_version(), m_ahb_panel, Slic3r::GUI::AmsPanel::m_ams_new_version_img, m_amspanel_list, Slic3r::GUI::ExtensionPanel::m_ext_new_version_img, m_ext_panel, Slic3r::MachineObject::m_new_ver_list_exist, m_obj, Slic3r::GUI::AmsPanel::m_staticText_ams, Slic3r::GUI::AmsPanel::m_staticText_ams_sn_val, Slic3r::GUI::AmsPanel::m_staticText_ams_ver_val, Slic3r::GUI::ExtensionPanel::m_staticText_ext_sn_val, Slic3r::GUI::ExtensionPanel::m_staticText_ext_ver_val, Slic3r::MachineObject::module_vers, Slic3r::MachineObject::new_ver_list, Slic3r::MachineObject::online_ahb, show_ams(), show_ext(), Slic3r::MachineObject::upgrade_display_state, Slic3r::MachineObject::upgrade_new_version, and Slic3r::MachineObject::UpgradingInProgress.
Referenced by update().
Update_printer_img()
void Slic3r::GUI::MachineInfoPanel::Update_printer_img (MachineObject * obj)
{
    if (!obj) {return;}
    auto img = obj->get_printer_thumbnail_img_str();
    if (wxGetApp().dark_mode()) {img += "_dark";}
    m_img_printer = create_scaled_bitmap(img, nullptr, 160);
    m_printer_img->SetBitmap(m_img_printer);
    m_printer_img->Refresh();
}
References create_scaled_bitmap(), Slic3r::MachineObject::get_printer_thumbnail_img_str(), m_img_printer, and m_printer_img.
Referenced by on_sys_color_changed(), and update().
update_version_text()
void Slic3r::GUI::MachineInfoPanel::update_version_text (MachineObject * obj)
{
    if (obj->upgrade_display_state == (int)MachineObject::UpgradingDisplayState::UpgradingInProgress) {
        m_staticText_ver_val->SetLabelText("-");
        //m_staticText_ams_ver_val->SetLabelText("-");
        m_ota_new_version_img->Hide();
    } else {
        // update version text
        auto it = obj->module_vers.find("ota");
        // old protocol
        if (obj->new_ver_list.empty() && !obj->m_new_ver_list_exist) {
            if (obj->upgrade_new_version
                && !obj->ota_new_version_number.empty()) {
                if (it != obj->module_vers.end()) {
                    wxString ver_text = wxString::Format("%s->%s", it->second.sw_ver, obj->ota_new_version_number);
                    m_staticText_ver_val->SetLabelText(ver_text);
                }
                else {
                    m_staticText_ver_val->SetLabelText("-");
                }
                m_ota_new_version_img->Show();
            }
            else {
                if (it != obj->module_vers.end()) {
                    wxString ver_text = wxString::Format("%s(%s)", it->second.sw_ver, _L("Latest version"));
                    m_staticText_ver_val->SetLabelText(ver_text);
                }
                else {
                    m_staticText_ver_val->SetLabelText("-");
                }
                m_ota_new_version_img->Hide();
            }
        } else {
            auto ota_it = obj->new_ver_list.find("ota");
            if (ota_it == obj->new_ver_list.end()) {
                if (it != obj->module_vers.end()) {
                    wxString ver_text = wxString::Format("%s(%s)", it->second.sw_ver, _L("Latest version"));
                    m_staticText_ver_val->SetLabelText(ver_text);
                    m_ota_new_version_img->Hide();
                }
            } else {
                if (ota_it->second.sw_new_ver != ota_it->second.sw_ver) {
                    m_ota_new_version_img->Show();
                    wxString ver_text = wxString::Format("%s->%s", ota_it->second.sw_ver, ota_it->second.sw_new_ver);
                    m_staticText_ver_val->SetLabelText(ver_text);
                } else {
                    if (it != obj->module_vers.end()) {
                        m_ota_new_version_img->Hide();
                        wxString ver_text = wxString::Format("%s(%s)", it->second.sw_ver, _L("Latest version"));
                        m_staticText_ver_val->SetLabelText(ver_text);
                    }
                }
            }
        }
    }
}
References _L, Slic3r::MachineObject::m_new_ver_list_exist, m_ota_new_version_img, m_staticText_ver_val, Slic3r::MachineObject::module_vers, Slic3r::MachineObject::new_ver_list, Slic3r::MachineObject::ota_new_version_number, Slic3r::MachineObject::upgrade_display_state, Slic3r::MachineObject::upgrade_new_version, and Slic3r::MachineObject::UpgradingInProgress.
Referenced by update().
upgrade_firmware_internal()
void Slic3r::GUI::MachineInfoPanel::upgrade_firmware_internal () protected
{
    if (!m_obj)
        return;
    if (panel_type == ptOtaPanel) {
        m_obj->command_upgrade_firmware(m_ota_info);
    } else if (panel_type == ptAmsPanel) {
        m_obj->command_upgrade_firmware(m_ams_info);
    } else if (panel_type == ptPushPanel) {
        confirm_upgrade();
    }
}
References Slic3r::MachineObject::command_upgrade_firmware(), confirm_upgrade(), m_ams_info, m_obj, m_ota_info, panel_type, ptAmsPanel, ptOtaPanel, and ptPushPanel.
Referenced by MachineInfoPanel().
Member Data Documentation
confirm_dlg
SecondaryCheckDialog* Slic3r::GUI::MachineInfoPanel::confirm_dlg = nullptr protected
Referenced by ~MachineInfoPanel(), on_consisitency_upgrade_firmware(), and on_upgrade_firmware().
is_upgrading
bool Slic3r::GUI::MachineInfoPanel::is_upgrading = false
last_status
int Slic3r::GUI::MachineInfoPanel::last_status = -1 protected
Referenced by show_status().
last_status_str
std::string Slic3r::GUI::MachineInfoPanel::last_status_str = "" protected
Referenced by show_status().
m_ahb_panel
AmsPanel* Slic3r::GUI::MachineInfoPanel::m_ahb_panel protected
Referenced by MachineInfoPanel(), and update_ams_ext().
m_ams_img
wxStaticBitmap* Slic3r::GUI::MachineInfoPanel::m_ams_img protected
Referenced by MachineInfoPanel(), msw_rescale(), and show_ams().
m_ams_info
FirmwareInfo Slic3r::GUI::MachineInfoPanel::m_ams_info
Referenced by upgrade_firmware_internal().
m_ams_info_sizer
wxFlexGridSizer* Slic3r::GUI::MachineInfoPanel::m_ams_info_sizer protected
Referenced by MachineInfoPanel().
m_ams_sizer
wxBoxSizer* Slic3r::GUI::MachineInfoPanel::m_ams_sizer protected
Referenced by MachineInfoPanel(), and show_ams().
m_amspanel_list
AmsPanelHash Slic3r::GUI::MachineInfoPanel::m_amspanel_list protected
Referenced by MachineInfoPanel(), and update_ams_ext().
m_button_upgrade_firmware
Button* Slic3r::GUI::MachineInfoPanel::m_button_upgrade_firmware protected
Referenced by MachineInfoPanel(), ~MachineInfoPanel(), get_btn(), msw_rescale(), and show_status().
m_caption_text
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_caption_text protected
Referenced by create_caption_panel(), and update().
m_ext_img
wxStaticBitmap* Slic3r::GUI::MachineInfoPanel::m_ext_img protected
Referenced by MachineInfoPanel(), msw_rescale(), and show_ext().
m_ext_panel
ExtensionPanel* Slic3r::GUI::MachineInfoPanel::m_ext_panel protected
Referenced by MachineInfoPanel(), and update_ams_ext().
m_ext_sizer
wxBoxSizer* Slic3r::GUI::MachineInfoPanel::m_ext_sizer protected
Referenced by MachineInfoPanel(), and show_ext().
m_img_ext
wxBitmap Slic3r::GUI::MachineInfoPanel::m_img_ext protected
Referenced by MachineInfoPanel(), init_bitmaps(), and msw_rescale().
m_img_monitor_ams
wxBitmap Slic3r::GUI::MachineInfoPanel::m_img_monitor_ams protected
Referenced by MachineInfoPanel(), init_bitmaps(), and msw_rescale().
m_img_printer
wxBitmap Slic3r::GUI::MachineInfoPanel::m_img_printer protected
Referenced by MachineInfoPanel(), init_bitmaps(), msw_rescale(), and Update_printer_img().
m_last_ams_show
bool Slic3r::GUI::MachineInfoPanel::m_last_ams_show = true protected
Referenced by show_ams().
m_last_ext_show
bool Slic3r::GUI::MachineInfoPanel::m_last_ext_show = true protected
Referenced by show_ext().
m_obj
MachineObject* Slic3r::GUI::MachineInfoPanel::m_obj {nullptr}
Referenced by on_consisitency_upgrade_firmware(), on_show_release_note(), on_sys_color_changed(), on_upgrade_firmware(), update(), update_ams_ext(), and upgrade_firmware_internal().
m_ota_info
FirmwareInfo Slic3r::GUI::MachineInfoPanel::m_ota_info
Referenced by upgrade_firmware_internal().
m_ota_new_version_img
wxStaticBitmap* Slic3r::GUI::MachineInfoPanel::m_ota_new_version_img protected
Referenced by MachineInfoPanel(), and update_version_text().
m_panel_caption
wxPanel* Slic3r::GUI::MachineInfoPanel::m_panel_caption protected
Referenced by MachineInfoPanel(), and update().
m_printer_img
wxStaticBitmap* Slic3r::GUI::MachineInfoPanel::m_printer_img protected
Referenced by MachineInfoPanel(), msw_rescale(), and Update_printer_img().
m_staticline
wxStaticLine* Slic3r::GUI::MachineInfoPanel::m_staticline protected
Referenced by MachineInfoPanel(), and show_ams().
m_staticline2
wxStaticLine* Slic3r::GUI::MachineInfoPanel::m_staticline2 protected
Referenced by MachineInfoPanel(), and show_ext().
m_staticText_model_id
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_model_id protected
Referenced by MachineInfoPanel().
m_staticText_model_id_val
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_model_id_val protected
Referenced by MachineInfoPanel(), and update().
m_staticText_release_note
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_release_note protected
Referenced by MachineInfoPanel().
m_staticText_sn
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_sn protected
Referenced by MachineInfoPanel().
m_staticText_sn_val
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_sn_val protected
Referenced by MachineInfoPanel(), and update().
m_staticText_upgrading_info
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_upgrading_info protected
Referenced by MachineInfoPanel(), and show_status().
m_staticText_upgrading_percent
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_upgrading_percent protected
Referenced by MachineInfoPanel(), show_status(), and update().
m_staticText_ver
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_ver protected
Referenced by MachineInfoPanel().
m_staticText_ver_val
wxStaticText* Slic3r::GUI::MachineInfoPanel::m_staticText_ver_val protected
Referenced by MachineInfoPanel(), and update_version_text().
m_upgrade_progress
ProgressBar* Slic3r::GUI::MachineInfoPanel::m_upgrade_progress protected
Referenced by MachineInfoPanel(), and update().
m_upgrade_retry_img
wxStaticBitmap* Slic3r::GUI::MachineInfoPanel::m_upgrade_retry_img protected
Referenced by MachineInfoPanel(), and show_status().
m_upgrade_status_img
wxStaticBitmap* Slic3r::GUI::MachineInfoPanel::m_upgrade_status_img protected
Referenced by create_caption_panel(), and update().
m_upgrading_sizer
wxBoxSizer* Slic3r::GUI::MachineInfoPanel::m_upgrading_sizer protected
Referenced by MachineInfoPanel(), and show_status().
panel_type
enum Slic3r::GUI::MachineInfoPanel::PanelType Slic3r::GUI::MachineInfoPanel::panel_type
Referenced by upgrade_firmware_internal().
upgrade_gray_icon
wxBitmap Slic3r::GUI::MachineInfoPanel::upgrade_gray_icon protected
Referenced by create_caption_panel(), init_bitmaps(), and update().
upgrade_green_icon
wxBitmap Slic3r::GUI::MachineInfoPanel::upgrade_green_icon protected
Referenced by MachineInfoPanel(), init_bitmaps(), and update().
upgrade_yellow_icon
wxBitmap Slic3r::GUI::MachineInfoPanel::upgrade_yellow_icon protected
Referenced by init_bitmaps(), and update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UpgradePanel.hpp
src/slic3r/GUI/UpgradePanel.cpp