OrcaSlicer: nlohmann::detail::invalid_iterator Class Reference
nlohmann::detail::invalid_iterator Class Reference
exception indicating errors with iterators
#include <src/nlohmann/detail/exceptions.hpp>
Public Member Functions
const char * what () const noexcept override
returns the explanatory string
Static Public Member Functions
template<typename BasicJsonType >
static invalid_iterator create (int id_, const std::string &what_arg, const BasicJsonType &context)
Public Attributes
const int id
the id of the exception
Static Protected Member Functions
static std::string name (const std::string &ename, int id_)
template<typename BasicJsonType >
static std::string diagnostics (const BasicJsonType &leaf_element)
Private Member Functions
invalid_iterator (int id_, const char *what_arg)
Private Attributes
std::runtime_error m
an exception object as storage for error messages
Detailed Description
exception indicating errors with iterators
This exception is thrown if iterators passed to a library function do not match the expected semantics.
Exceptions have ids 2xx.
name / id example message description
json.exception.invalid_iterator.201 iterators are not compatible The iterators passed to constructor basic_json(InputIT first, InputIT last) are not compatible, meaning they do not belong to the same container. Therefore, the range (first, last) is invalid.
json.exception.invalid_iterator.202 iterator does not fit current value In an erase or insert function, the passed iterator pos does not belong to the JSON value for which the function was called. It hence does not define a valid position for the deletion/insertion.
json.exception.invalid_iterator.203 iterators do not fit current value Either iterator passed to function erase(IteratorType first, IteratorType last) does not belong to the JSON value from which values shall be erased. It hence does not define a valid range to delete values from.
json.exception.invalid_iterator.204 iterators out of range When an iterator range for a primitive type (number, boolean, or string) is passed to a constructor or an erase function, this range has to be exactly (begin(), end()), because this is the only way the single stored value is expressed. All other ranges are invalid.
json.exception.invalid_iterator.205 iterator out of range When an iterator for a primitive type (number, boolean, or string) is passed to an erase function, the iterator has to be the begin() iterator, because it is the only way to address the stored value. All other iterators are invalid.
json.exception.invalid_iterator.206 cannot construct with iterators from null The iterators passed to constructor basic_json(InputIT first, InputIT last) belong to a JSON null value and hence to not define a valid range.
json.exception.invalid_iterator.207 cannot use key() for non-object iterators The key() member function can only be used on iterators belonging to a JSON object, because other types do not have a concept of a key.
json.exception.invalid_iterator.208 cannot use operator[] for object iterators The operator[] to specify a concrete offset cannot be used on iterators belonging to a JSON object, because JSON objects are unordered.
json.exception.invalid_iterator.209 cannot use offsets with object iterators The offset operators (+, -, +=, -=) cannot be used on iterators belonging to a JSON object, because JSON objects are unordered.
json.exception.invalid_iterator.210 iterators do not fit The iterator range passed to the insert function are not compatible, meaning they do not belong to the same container. Therefore, the range (first, last) is invalid.
json.exception.invalid_iterator.211 passed iterators may not belong to container The iterator range passed to the insert function must not be a subrange of the container to insert to.
json.exception.invalid_iterator.212 cannot compare iterators of different containers When two iterators are compared, they must belong to the same container.
json.exception.invalid_iterator.213 cannot compare order of object iterators The order of object iterators cannot be compared, because JSON objects are unordered.
json.exception.invalid_iterator.214 cannot get value Cannot get value for iterator: Either the iterator belongs to a null value or it is an iterator to a primitive type (number, boolean, or string), but the iterator is different to begin().
@liveexample{The following code shows how an invalid_iterator exception can be caught.,invalid_iterator}
See also
- exception for the base class of the library exceptions
- parse_error for exceptions indicating a parse error
- type_error for exceptions indicating executing a member function with a wrong type
- out_of_range for exceptions indicating access out of the defined range
- other_error for exceptions indicating other library errors
Since
version 3.0.0
Constructor & Destructor Documentation
invalid_iterator()
nlohmann::detail::invalid_iterator::invalid_iterator (int id_, const char * what_arg) inline private
        : exception(id_, what_arg) {}
Member Function Documentation
create()
template<typename BasicJsonType > static invalid_iterator nlohmann::detail::invalid_iterator::create (int id_, const std::string & what_arg, const BasicJsonType & context) inline static
    {
        std::string w = exception::name("invalid_iterator", id_) + exception::diagnostics(context) + what_arg;
        return invalid_iterator(id_, w.c_str());
    }
References nlohmann::detail::exception::diagnostics(), and nlohmann::detail::exception::name().
Referenced by nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::basic_json(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::erase(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::erase(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert(), nlohmann::detail::iter_impl< BasicJsonType >::key(), nlohmann::detail::iter_impl< BasicJsonType >::operator*(), nlohmann::detail::iter_impl< BasicJsonType >::operator+=(), nlohmann::detail::iter_impl< BasicJsonType >::operator-(), nlohmann::detail::iter_impl< BasicJsonType >::operator->(), nlohmann::detail::iter_impl< BasicJsonType >::operator<(), nlohmann::detail::iter_impl< BasicJsonType >::operator==(), nlohmann::detail::iter_impl< BasicJsonType >::operator[](), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::update().
diagnostics()
template<typename BasicJsonType > static std::string nlohmann::detail::exception::diagnostics (const BasicJsonType & leaf_element) inline static protected inherited
    {
#if JSON_DIAGNOSTICS
        std::vector<std::string> tokens;
        for (const auto* current = &leaf_element; current->m_parent != nullptr; current = current->m_parent)
        {
            switch (current->m_parent->type())
            {
                case value_t::array:
                {
                    for (std::size_t i = 0; i < current->m_parent->m_value.array->size(); ++i)
                    {
                        if (&current->m_parent->m_value.array->operator[](i) == current)
{
                            tokens.emplace_back(std::to_string(i));
                            break;
                        }
                    }
                    break;
                }
                case value_t::object:
                {
                    for (const auto& element : *current->m_parent->m_value.object)
                    {
                        if (&element.second == current)
{
                            tokens.emplace_back(element.first.c_str());
                            break;
                        }
                    }
                    break;
                }
                case value_t::null: // LCOV_EXCL_LINE
                case value_t::string: // LCOV_EXCL_LINE
                case value_t::boolean: // LCOV_EXCL_LINE
                case value_t::number_integer: // LCOV_EXCL_LINE
                case value_t::number_unsigned: // LCOV_EXCL_LINE
                case value_t::number_float: // LCOV_EXCL_LINE
                case value_t::binary: // LCOV_EXCL_LINE
                case value_t::discarded: // LCOV_EXCL_LINE
                default:   // LCOV_EXCL_LINE
                    break; // LCOV_EXCL_LINE
            }
        }
        if (tokens.empty())
        {
            return "";
        }
        return "(" + std::accumulate(tokens.rbegin(), tokens.rend(), std::string{},
                                     [](const std::string & a, const std::string & b)
        {
            return a + "/" + detail::escape(b);
        }) + ") ";
#else
        static_cast<void>(leaf_element);
        return "";
#endif
    }
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::detail::parse_error::create(), create(), nlohmann::detail::type_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::other_error::create(), and nlohmann::detail::parse_error::create().
name()
static std::string nlohmann::detail::exception::name (const std::string & ename, int id_) inline static protected inherited
    {
        return "[json.exception." + ename + "." + std::to_string(id_) + "] ";
    }
Referenced by nlohmann::detail::parse_error::create(), create(), nlohmann::detail::type_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::other_error::create(), and nlohmann::detail::parse_error::create().
what()
const char * nlohmann::detail::exception::what () const inline override noexcept inherited
returns the explanatory string
    {
        return m.what();
    }
References nlohmann::detail::exception::m.
Referenced by Slic3r::PresetUpdater::priv::get_cached_plugins_version(), Slic3r::get_values_from_json(), Slic3r::get_version_from_json(), Slic3r::GUI::GuideFrame::GetFilamentInfo(), Slic3r::AppConfig::load(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::GUI::GuideFrame::LoadProfileFamily(), and Slic3r::GUI::UpdatePluginDialog::update_info().
Member Data Documentation
id
const int nlohmann::detail::exception::id inherited
the id of the exception
m
std::runtime_error nlohmann::detail::exception::m private inherited
an exception object as storage for error messages
Referenced by nlohmann::detail::exception::what().
The documentation for this class was generated from the following file:
src/nlohmann/detail/exceptions.hpp