OrcaSlicer: Slic3r::client::expr< Iterator > Struct Template Reference
Slic3r::client::expr< Iterator > Struct Template Reference
Classes
union Data
Public Types
enum Type {
TYPE_EMPTY = 0 , TYPE_BOOL , TYPE_INT , TYPE_DOUBLE ,
TYPE_STRING
}
enum Function2ParamsType { FUNCTION_MIN , FUNCTION_MAX }
Public Member Functions
expr ()
expr (bool b)
expr (bool b, const Iterator &it_begin, const Iterator &it_end)
expr (int i)
expr (int i, const Iterator &it_begin, const Iterator &it_end)
expr (double d)
expr (double d, const Iterator &it_begin, const Iterator &it_end)
expr (const char *s)
expr (const std::string &s)
expr (const std::string &s, const Iterator &it_begin, const Iterator &it_end)
expr (const expr &rhs)
expr (expr &&rhs)
expr (expr &&rhs, const Iterator &it_begin, const Iterator &it_end)
~expr ()
expr & operator= (const expr &rhs)
expr & operator= (expr &&rhs)
void reset ()
bool & b ()
bool b () const
void set_b (bool v)
int & i ()
int i () const
void set_i (int v)
int as_i () const
int as_i_rounded () const
double & d ()
double d () const
void set_d (double v)
double as_d () const
std::string & s ()
const std::string & s () const
void set_s (const std::string &s)
void set_s (std::string &&s)
std::string to_string () const
expr unary_minus (const Iterator start_pos) const
expr unary_integer (const Iterator start_pos) const
expr round (const Iterator start_pos) const
expr unary_not (const Iterator start_pos) const
expr & operator+= (const expr &rhs)
expr & operator-= (const expr &rhs)
expr & operator*= (const expr &rhs)
expr & operator/= (const expr &rhs)
expr & operator%= (const expr &rhs)
void throw_exception (const char *message) const
void throw_if_not_numeric (const char *message) const
Static Public Member Functions
static void to_string2 (expr &self, std::string &out)
static void evaluate_boolean (expr &self, bool &out)
static void evaluate_boolean_to_string (expr &self, std::string &out)
static void compare_op (expr &lhs, expr &rhs, char op, bool invert)
static void equal (expr &lhs, expr &rhs)
static void not_equal (expr &lhs, expr &rhs)
static void lower (expr &lhs, expr &rhs)
static void greater (expr &lhs, expr &rhs)
static void leq (expr &lhs, expr &rhs)
static void geq (expr &lhs, expr &rhs)
static void throw_if_not_numeric (const expr &param)
static void function_2params (expr &param1, expr &param2, Function2ParamsType fun)
static void min (expr &param1, expr &param2)
static void max (expr &param1, expr &param2)
static void random (expr &param1, expr &param2, std::mt19937 &rng)
template<bool leading_zeros>
static void digits (expr &param1, expr &param2, expr &param3)
static void regex_op (expr &lhs, boost::iterator_range< Iterator > &rhs, char op)
static void regex_matches (expr &lhs, boost::iterator_range< Iterator > &rhs)
static void regex_doesnt_match (expr &lhs, boost::iterator_range< Iterator > &rhs)
static void logical_op (expr &lhs, expr &rhs, char op)
static void logical_or (expr &lhs, expr &rhs)
static void logical_and (expr &lhs, expr &rhs)
static void ternary_op (expr &lhs, expr &rhs1, expr &rhs2)
static void set_if (bool &cond, bool &not_yet_consumed, std::string &str_in, std::string &str_out)
Public Attributes
union Slic3r::client::expr::Data data
Type type
boost::iterator_range< Iterator > it_range
Detailed Description
template<typename Iterator>
struct Slic3r::client::expr< Iterator >
Member Enumeration Documentation
Function2ParamsType
template<typename Iterator > enum Slic3r::client::expr::Function2ParamsType
Enumerator
FUNCTION_MIN
FUNCTION_MAX
{
            FUNCTION_MIN,
            FUNCTION_MAX,
        };
Type
template<typename Iterator > enum Slic3r::client::expr::Type
Enumerator
TYPE_EMPTY
TYPE_BOOL
TYPE_INT
TYPE_DOUBLE
TYPE_STRING
                  {
            TYPE_EMPTY = 0,
            TYPE_BOOL,
            TYPE_INT,
            TYPE_DOUBLE,
            TYPE_STRING,
        };
Constructor & Destructor Documentation
expr() [1/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr () inline
: type(TYPE_EMPTY) {}
Referenced by Slic3r::client::expr< Iterator >::round(), Slic3r::client::expr< Iterator >::unary_integer(), Slic3r::client::expr< Iterator >::unary_minus(), and Slic3r::client::expr< Iterator >::unary_not().
expr() [2/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (bool b) inline explicit
: type(TYPE_BOOL) { data.b = b; }
References Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::Data::b, and Slic3r::client::expr< Iterator >::data.
expr() [3/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (bool b, const Iterator & it_begin, const Iterator & it_end) inline explicit
: type(TYPE_BOOL), it_range(it_begin, it_end) { data.b = b; }
References Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::Data::b, and Slic3r::client::expr< Iterator >::data.
expr() [4/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (int i) inline explicit
: type(TYPE_INT) { data.i = i; }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::i(), and Slic3r::client::expr< Iterator >::Data::i.
expr() [5/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (int i, const Iterator & it_begin, const Iterator & it_end) inline explicit
: type(TYPE_INT), it_range(it_begin, it_end) { data.i = i; }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::i(), and Slic3r::client::expr< Iterator >::Data::i.
expr() [6/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (double d) inline explicit
: type(TYPE_DOUBLE) { data.d = d; }
References Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::Data::d, and Slic3r::client::expr< Iterator >::data.
expr() [7/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (double d, const Iterator & it_begin, const Iterator & it_end) inline explicit
: type(TYPE_DOUBLE), it_range(it_begin, it_end) { data.d = d; }
References Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::Data::d, and Slic3r::client::expr< Iterator >::data.
expr() [8/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (const char * s) inline explicit
: type(TYPE_STRING) { data.s = new std::string(s); }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::s(), and Slic3r::client::expr< Iterator >::Data::s.
expr() [9/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (const std::string & s) inline explicit
: type(TYPE_STRING) { data.s = new std::string(s); }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::s(), and Slic3r::client::expr< Iterator >::Data::s.
expr() [10/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (const std::string & s, const Iterator & it_begin, const Iterator & it_end) inline explicit
                                                                                            :
            type(TYPE_STRING), it_range(it_begin, it_end) { data.s = new std::string(s); }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::s(), and Slic3r::client::expr< Iterator >::Data::s.
expr() [11/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (const expr< Iterator > & rhs) inline
                                       : type(rhs.type), it_range(rhs.it_range)
            { if (rhs.type == TYPE_STRING) data.s = new std::string(*rhs.data.s); else data.set(rhs.data); }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::Data::s, Slic3r::client::expr< Iterator >::Data::set(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_STRING.
expr() [12/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (expr< Iterator > && rhs) inline explicit
                                  : type(rhs.type), it_range(rhs.it_range)
            { data.set(rhs.data); rhs.type = TYPE_EMPTY; }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::Data::set(), and Slic3r::client::expr< Iterator >::TYPE_EMPTY.
expr() [13/13]
template<typename Iterator > Slic3r::client::expr< Iterator >::expr (expr< Iterator > && rhs, const Iterator & it_begin, const Iterator & it_end) inline explicit
                                                                                    : type(rhs.type), it_range(it_begin, it_end)
            { data.set(rhs.data); rhs.type = TYPE_EMPTY; }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::Data::set(), and Slic3r::client::expr< Iterator >::TYPE_EMPTY.
~expr()
template<typename Iterator > Slic3r::client::expr< Iterator >::~expr () inline
{ this->reset(); }
References Slic3r::client::expr< Iterator >::reset().
Member Function Documentation
as_d()
template<typename Iterator > double Slic3r::client::expr< Iterator >::as_d () const inline
{ return (this->type == TYPE_DOUBLE) ? this->d() : double(this->i()); }
References Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_DOUBLE.
Referenced by Slic3r::client::expr< Iterator >::compare_op(), Slic3r::client::expr< Iterator >::digits(), Slic3r::client::expr< Iterator >::function_2params(), Slic3r::client::expr< Iterator >::operator%=(), Slic3r::client::expr< Iterator >::operator*=(), Slic3r::client::expr< Iterator >::operator+=(), Slic3r::client::expr< Iterator >::operator-=(), Slic3r::client::expr< Iterator >::operator/=(), and Slic3r::client::expr< Iterator >::random().
as_i()
template<typename Iterator > int Slic3r::client::expr< Iterator >::as_i () const inline
{ return (this->type == TYPE_INT) ? this->i() : int(this->d()); }
References Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::i(), int, Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_INT.
Referenced by Slic3r::client::expr< Iterator >::digits(), Slic3r::client::expr< Iterator >::function_2params(), and Slic3r::client::expr< Iterator >::random().
as_i_rounded()
template<typename Iterator > int Slic3r::client::expr< Iterator >::as_i_rounded () const inline
{ return (this->type == TYPE_INT) ? this->i() : int(std::round(this->d())); }
References Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::i(), int, Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_INT.
Referenced by Slic3r::client::expr< Iterator >::digits().
b() [1/2]
template<typename Iterator > bool & Slic3r::client::expr< Iterator >::b () inline
{ return data.b; }
References Slic3r::client::expr< Iterator >::Data::b, and Slic3r::client::expr< Iterator >::data.
Referenced by Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::compare_op(), Slic3r::client::expr< Iterator >::evaluate_boolean(), Slic3r::client::expr< Iterator >::evaluate_boolean_to_string(), Slic3r::client::expr< Iterator >::logical_op(), Slic3r::client::operator<<(), Slic3r::client::expr< Iterator >::ternary_op(), and Slic3r::client::expr< Iterator >::unary_not().
b() [2/2]
template<typename Iterator > bool Slic3r::client::expr< Iterator >::b () const inline
{ return data.b; }
References Slic3r::client::expr< Iterator >::Data::b, and Slic3r::client::expr< Iterator >::data.
compare_op()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::compare_op (expr< Iterator > & lhs, expr< Iterator > & rhs, char op, bool invert) inline static
        {
            bool value = false;
            if ((lhs.type == TYPE_INT || lhs.type == TYPE_DOUBLE) &&
                (rhs.type == TYPE_INT || rhs.type == TYPE_DOUBLE)) {
                // Both types are numeric.
                switch (op) {
                    case '=':
                        value = (lhs.type == TYPE_DOUBLE || rhs.type == TYPE_DOUBLE) ?
                            (std::abs(lhs.as_d() - rhs.as_d()) < 1e-8) : (lhs.i() == rhs.i());
                        break;
                    case '<':
                        value = (lhs.type == TYPE_DOUBLE || rhs.type == TYPE_DOUBLE) ?
                            (lhs.as_d() < rhs.as_d()) : (lhs.i() < rhs.i());
                        break;
                    case '>':
                    default:
                        value = (lhs.type == TYPE_DOUBLE || rhs.type == TYPE_DOUBLE) ?
                            (lhs.as_d() > rhs.as_d()) : (lhs.i() > rhs.i());
                        break;
                }
            } else if (lhs.type == TYPE_BOOL && rhs.type == TYPE_BOOL) {
                // Both type are bool.
                if (op != '=')
                    boost::throw_exception(qi::expectation_failure<Iterator>(
                        lhs.it_range.begin(), rhs.it_range.end(), spirit::info("*Cannot compare the types.")));
                value = lhs.b() == rhs.b();
            } else if (lhs.type == TYPE_STRING || rhs.type == TYPE_STRING) {
                // One type is string, the other could be converted to string.
                value = (op == '=') ? (lhs.to_string() == rhs.to_string()) :
                        (op == '<') ? (lhs.to_string() < rhs.to_string()) : (lhs.to_string() > rhs.to_string());
            } else {
                boost::throw_exception(qi::expectation_failure<Iterator>(
                    lhs.it_range.begin(), rhs.it_range.end(), spirit::info("*Cannot compare the types.")));
            }
            lhs.type = TYPE_BOOL;
            lhs.data.b = invert ? ! value : value;
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::Data::b, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::to_string(), Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_BOOL, Slic3r::client::expr< Iterator >::TYPE_DOUBLE, Slic3r::client::expr< Iterator >::TYPE_INT, and Slic3r::client::expr< Iterator >::TYPE_STRING.
Referenced by Slic3r::client::expr< Iterator >::equal(), Slic3r::client::expr< Iterator >::geq(), Slic3r::client::expr< Iterator >::greater(), Slic3r::client::expr< Iterator >::leq(), Slic3r::client::expr< Iterator >::lower(), and Slic3r::client::expr< Iterator >::not_equal().
d() [1/2]
template<typename Iterator > double & Slic3r::client::expr< Iterator >::d () inline
{ return data.d; }
References Slic3r::client::expr< Iterator >::Data::d, and Slic3r::client::expr< Iterator >::data.
Referenced by Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::as_i(), Slic3r::client::expr< Iterator >::as_i_rounded(), Slic3r::client::expr< Iterator >::function_2params(), Slic3r::client::expr< Iterator >::operator%=(), Slic3r::client::expr< Iterator >::operator*=(), Slic3r::client::expr< Iterator >::operator+=(), Slic3r::client::expr< Iterator >::operator-=(), Slic3r::client::expr< Iterator >::operator/=(), Slic3r::client::operator<<(), Slic3r::client::expr< Iterator >::round(), Slic3r::client::expr< Iterator >::unary_integer(), and Slic3r::client::expr< Iterator >::unary_minus().
d() [2/2]
template<typename Iterator > double Slic3r::client::expr< Iterator >::d () const inline
{ return data.d; }
References Slic3r::client::expr< Iterator >::Data::d, and Slic3r::client::expr< Iterator >::data.
digits()
template<typename Iterator > template<bool leading_zeros> static void Slic3r::client::expr< Iterator >::digits (expr< Iterator > & param1, expr< Iterator > & param2, expr< Iterator > & param3) inline static
        {
            throw_if_not_numeric(param1);
            if (param2.type != TYPE_INT)
                param2.throw_exception("digits: second parameter must be integer");
            bool has_decimals = param3.type != TYPE_EMPTY;
            if (has_decimals && param3.type != TYPE_INT)
                param3.throw_exception("digits: third parameter must be integer");
            char buf[256];
            int  ndigits = std::clamp(param2.as_i(), 0, 64);
            if (has_decimals) {
                // Format as double.
                int decimals = std::clamp(param3.as_i(), 0, 64);
                sprintf(buf, leading_zeros ? "%0*.*lf" : "%*.*lf", ndigits, decimals, param1.as_d());
            } else
                // Format as int.
                sprintf(buf, leading_zeros ? "%0*d" : "%*d", ndigits, param1.as_i_rounded());
            param1.set_s(buf);
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::as_i(), Slic3r::client::expr< Iterator >::as_i_rounded(), Slic3r::client::expr< Iterator >::set_s(), Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_EMPTY, and Slic3r::client::expr< Iterator >::TYPE_INT.
equal()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::equal (expr< Iterator > & lhs, expr< Iterator > & rhs) inline static
{ compare_op(lhs, rhs, '=', false); }
References Slic3r::client::expr< Iterator >::compare_op().
evaluate_boolean()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::evaluate_boolean (expr< Iterator > & self, bool & out) inline static
        {
            if (self.type != TYPE_BOOL)
                self.throw_exception("Not a boolean expression");
            out = self.b();
        }
References Slic3r::client::expr< Iterator >::b(), out, Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_BOOL.
evaluate_boolean_to_string()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::evaluate_boolean_to_string (expr< Iterator > & self, std::string & out) inline static
        {
            if (self.type != TYPE_BOOL)
                self.throw_exception("Not a boolean expression");
            out = self.b() ? "true" : "false";
        }
References Slic3r::client::expr< Iterator >::b(), out, Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_BOOL.
function_2params()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::function_2params (expr< Iterator > & param1, expr< Iterator > & param2, Function2ParamsType fun) inline static
        {
            throw_if_not_numeric(param1);
            throw_if_not_numeric(param2);
            if (param1.type == TYPE_DOUBLE || param2.type == TYPE_DOUBLE) {
                double d = 0.;
                switch (fun) {
                    case FUNCTION_MIN:  d = std::min(param1.as_d(), param2.as_d()); break;
                    case FUNCTION_MAX:  d = std::max(param1.as_d(), param2.as_d()); break;
                    default: param1.throw_exception("Internal error: invalid function");
                }
                param1.data.d = d;
                param1.type = TYPE_DOUBLE;
            } else {
                int i = 0;
                switch (fun) {
                    case FUNCTION_MIN:  i = std::min(param1.as_i(), param2.as_i()); break;
                    case FUNCTION_MAX:  i = std::max(param1.as_i(), param2.as_i()); break;
                    default: param1.throw_exception("Internal error: invalid function");
                }
                param1.data.i = i;
                param1.type = TYPE_INT;
            }
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::as_i(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::FUNCTION_MAX, Slic3r::client::expr< Iterator >::FUNCTION_MIN, Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::Data::i, Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_INT.
Referenced by Slic3r::client::expr< Iterator >::max(), and Slic3r::client::expr< Iterator >::min().
geq()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::geq (expr< Iterator > & lhs, expr< Iterator > & rhs) inline static
{ compare_op(lhs, rhs, '<', true); }
References Slic3r::client::expr< Iterator >::compare_op().
greater()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::greater (expr< Iterator > & lhs, expr< Iterator > & rhs) inline static
{ compare_op(lhs, rhs, '>', false); }
References Slic3r::client::expr< Iterator >::compare_op().
i() [1/2]
template<typename Iterator > int & Slic3r::client::expr< Iterator >::i () inline
{ return data.i; }
References Slic3r::client::expr< Iterator >::data, and Slic3r::client::expr< Iterator >::Data::i.
Referenced by Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::as_i(), Slic3r::client::expr< Iterator >::as_i_rounded(), Slic3r::client::expr< Iterator >::compare_op(), Slic3r::client::MyContext::evaluate_index(), Slic3r::client::expr< Iterator >::function_2params(), Slic3r::client::expr< Iterator >::operator%=(), Slic3r::client::expr< Iterator >::operator*=(), Slic3r::client::expr< Iterator >::operator+=(), Slic3r::client::expr< Iterator >::operator-=(), Slic3r::client::expr< Iterator >::operator/=(), Slic3r::client::operator<<(), Slic3r::client::expr< Iterator >::round(), Slic3r::client::expr< Iterator >::unary_integer(), and Slic3r::client::expr< Iterator >::unary_minus().
i() [2/2]
template<typename Iterator > int Slic3r::client::expr< Iterator >::i () const inline
{ return data.i; }
References Slic3r::client::expr< Iterator >::data, and Slic3r::client::expr< Iterator >::Data::i.
leq()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::leq (expr< Iterator > & lhs, expr< Iterator > & rhs) inline static
{ compare_op(lhs, rhs, '>', true); }
References Slic3r::client::expr< Iterator >::compare_op().
logical_and()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::logical_and (expr< Iterator > & lhs, expr< Iterator > & rhs) inline static
{ logical_op(lhs, rhs, '&'); }
References Slic3r::client::expr< Iterator >::logical_op().
logical_op()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::logical_op (expr< Iterator > & lhs, expr< Iterator > & rhs, char op) inline static
        {
            bool value = false;
            if (lhs.type == TYPE_BOOL && rhs.type == TYPE_BOOL) {
                value = (op == '|') ? (lhs.b() || rhs.b()) : (lhs.b() && rhs.b());
            } else {
                boost::throw_exception(qi::expectation_failure<Iterator>(
                    lhs.it_range.begin(), rhs.it_range.end(), spirit::info("*Cannot apply logical operation to non-boolean operators.")));
            }
            lhs.type   = TYPE_BOOL;
            lhs.data.b = value;
        }
References Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::Data::b, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_BOOL.
Referenced by Slic3r::client::expr< Iterator >::logical_and(), and Slic3r::client::expr< Iterator >::logical_or().
logical_or()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::logical_or (expr< Iterator > & lhs, expr< Iterator > & rhs) inline static
{ logical_op(lhs, rhs, '|'); }
References Slic3r::client::expr< Iterator >::logical_op().
lower()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::lower (expr< Iterator > & lhs, expr< Iterator > & rhs) inline static
{ compare_op(lhs, rhs, '<', false); }
References Slic3r::client::expr< Iterator >::compare_op().
max()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::max (expr< Iterator > & param1, expr< Iterator > & param2) inline static
{ function_2params(param1, param2, FUNCTION_MAX); }
References Slic3r::client::expr< Iterator >::function_2params(), and Slic3r::client::expr< Iterator >::FUNCTION_MAX.
min()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::min (expr< Iterator > & param1, expr< Iterator > & param2) inline static
{ function_2params(param1, param2, FUNCTION_MIN); }
References Slic3r::client::expr< Iterator >::function_2params(), and Slic3r::client::expr< Iterator >::FUNCTION_MIN.
not_equal()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::not_equal (expr< Iterator > & lhs, expr< Iterator > & rhs) inline static
{ compare_op(lhs, rhs, '=', true); }
References Slic3r::client::expr< Iterator >::compare_op().
operator%=()
template<typename Iterator > expr & Slic3r::client::expr< Iterator >::operator%= (const expr< Iterator > & rhs) inline
        {
            this->throw_if_not_numeric("Cannot divide a non-numeric type.");
            rhs.throw_if_not_numeric("Cannot divide with a non-numeric type.");
            if ((rhs.type == TYPE_INT) ? (rhs.i() == 0) : (rhs.d() == 0.))
                rhs.throw_exception("Division by zero");
            if (this->type == TYPE_DOUBLE || rhs.type == TYPE_DOUBLE) {
                double d = std::fmod(this->as_d(), rhs.as_d());
                this->data.d = d;
                this->type = TYPE_DOUBLE;
            } else
                this->data.i %= rhs.i();
            this->it_range = boost::iterator_range<Iterator>(this->it_range.begin(), rhs.it_range.end());
            return *this;
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::Data::i, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_INT.
operator*=()
template<typename Iterator > expr & Slic3r::client::expr< Iterator >::operator*= (const expr< Iterator > & rhs) inline
        {
            const char *err_msg = "Cannot multiply with non-numeric type.";
            this->throw_if_not_numeric(err_msg);
            rhs.throw_if_not_numeric(err_msg);
            if (this->type == TYPE_DOUBLE || rhs.type == TYPE_DOUBLE) {
                double d = this->as_d() * rhs.as_d();
                this->data.d = d;
                this->type = TYPE_DOUBLE;
            } else
                this->data.i *= rhs.i();
            this->it_range = boost::iterator_range<Iterator>(this->it_range.begin(), rhs.it_range.end());
            return *this;
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::Data::i, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_DOUBLE.
operator+=()
template<typename Iterator > expr & Slic3r::client::expr< Iterator >::operator+= (const expr< Iterator > & rhs) inline
        {
            if (this->type == TYPE_STRING) {
                // Convert the right hand side to string and append.
                *this->data.s += rhs.to_string();
            } else if (rhs.type == TYPE_STRING) {
                // Conver the left hand side to string, append rhs.
                this->data.s = new std::string(this->to_string() + rhs.s());
                this->type = TYPE_STRING;
            } else {
                const char *err_msg = "Cannot add non-numeric types.";
                this->throw_if_not_numeric(err_msg);
                rhs.throw_if_not_numeric(err_msg);
                if (this->type == TYPE_DOUBLE || rhs.type == TYPE_DOUBLE) {
                    double d = this->as_d() + rhs.as_d();
                    this->data.d = d;
                    this->type = TYPE_DOUBLE;
                } else
                    this->data.i += rhs.i();
            }
            this->it_range = boost::iterator_range<Iterator>(this->it_range.begin(), rhs.it_range.end());
            return *this;
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::Data::i, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::s(), Slic3r::client::expr< Iterator >::Data::s, Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::to_string(), Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_STRING.
operator-=()
template<typename Iterator > expr & Slic3r::client::expr< Iterator >::operator-= (const expr< Iterator > & rhs) inline
        {
            const char *err_msg = "Cannot subtract non-numeric types.";
            this->throw_if_not_numeric(err_msg);
            rhs.throw_if_not_numeric(err_msg);
            if (this->type == TYPE_DOUBLE || rhs.type == TYPE_DOUBLE) {
                double d = this->as_d() - rhs.as_d();
                this->data.d = d;
                this->type = TYPE_DOUBLE;
            } else
                this->data.i -= rhs.i();
            this->it_range = boost::iterator_range<Iterator>(this->it_range.begin(), rhs.it_range.end());
            return *this;
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::Data::i, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_DOUBLE.
operator/=()
template<typename Iterator > expr & Slic3r::client::expr< Iterator >::operator/= (const expr< Iterator > & rhs) inline
        {
            this->throw_if_not_numeric("Cannot divide a non-numeric type.");
            rhs.throw_if_not_numeric("Cannot divide with a non-numeric type.");
            if ((rhs.type == TYPE_INT) ? (rhs.i() == 0) : (rhs.d() == 0.))
                rhs.throw_exception("Division by zero");
            if (this->type == TYPE_DOUBLE || rhs.type == TYPE_DOUBLE) {
                double d = this->as_d() / rhs.as_d();
                this->data.d = d;
                this->type = TYPE_DOUBLE;
            } else
                this->data.i /= rhs.i();
            this->it_range = boost::iterator_range<Iterator>(this->it_range.begin(), rhs.it_range.end());
            return *this;
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::Data::i, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_INT.
operator=() [1/2]
template<typename Iterator > expr & Slic3r::client::expr< Iterator >::operator= (const expr< Iterator > & rhs) inline
        {
            //BBS: avoid memory leak when call operator= directly before call reset()
            if (this->type == TYPE_STRING && this->data.s) {
                delete this->data.s;
                this->data.s = nullptr;
            }
            this->type      = rhs.type;
            this->it_range  = rhs.it_range;
            if (rhs.type == TYPE_STRING)
                this->data.s = new std::string(*rhs.data.s);
            else
                this->data.set(rhs.data);
            return *this;
        }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::Data::s, Slic3r::client::expr< Iterator >::Data::set(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_STRING.
operator=() [2/2]
template<typename Iterator > expr & Slic3r::client::expr< Iterator >::operator= (expr< Iterator > && rhs) inline
        {
            type            = rhs.type;
            this->it_range  = rhs.it_range;
            data.set(rhs.data);
            rhs.type        = TYPE_EMPTY;
            return *this;
        }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::Data::set(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_EMPTY.
random()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::random (expr< Iterator > & param1, expr< Iterator > & param2, std::mt19937 & rng) inline static
        {
            throw_if_not_numeric(param1);
            throw_if_not_numeric(param2);
            if (param1.type == TYPE_DOUBLE || param2.type == TYPE_DOUBLE) {
                param1.data.d = std::uniform_real_distribution<>(param1.as_d(), param2.as_d())(rng);
                param1.type   = TYPE_DOUBLE;
            } else {
                param1.data.i = std::uniform_int_distribution<>(param1.as_i(), param2.as_i())(rng);
                param1.type   = TYPE_INT;
            }
        }
References Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::as_i(), Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::Data::i, Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_INT.
regex_doesnt_match()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::regex_doesnt_match (expr< Iterator > & lhs, boost::iterator_range< Iterator > & rhs) inline static
{ return regex_op(lhs, rhs, '!'); }
References Slic3r::client::expr< Iterator >::regex_op().
regex_matches()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::regex_matches (expr< Iterator > & lhs, boost::iterator_range< Iterator > & rhs) inline static
{ return regex_op(lhs, rhs, '='); }
References Slic3r::client::expr< Iterator >::regex_op().
regex_op()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::regex_op (expr< Iterator > & lhs, boost::iterator_range< Iterator > & rhs, char op) inline static
        {
            const std::string *subject  = nullptr;
            if (lhs.type == TYPE_STRING) {
                // One type is string, the other could be converted to string.
                subject = &lhs.s();
            } else {
                lhs.throw_exception("Left hand side of a regex match must be a string.");
            }
            try {
                std::string pattern(++ rhs.begin(), -- rhs.end());
                bool result = SLIC3R_REGEX_NAMESPACE::regex_match(*subject, SLIC3R_REGEX_NAMESPACE::regex(pattern));
                if (op == '!')
                    result = ! result;
                lhs.reset();
                lhs.type = TYPE_BOOL;
                lhs.data.b = result;
            } catch (SLIC3R_REGEX_NAMESPACE::regex_error &ex) {
                // Syntax error in the regular expression
                boost::throw_exception(qi::expectation_failure<Iterator>(
                    rhs.begin(), rhs.end(), spirit::info(std::string("*Regular expression compilation failed: ") + ex.what())));
            }
        }
References Slic3r::client::expr< Iterator >::Data::b, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::reset(), Slic3r::client::expr< Iterator >::s(), Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_BOOL, and Slic3r::client::expr< Iterator >::TYPE_STRING.
Referenced by Slic3r::client::expr< Iterator >::regex_doesnt_match(), and Slic3r::client::expr< Iterator >::regex_matches().
reset()
template<typename Iterator > void Slic3r::client::expr< Iterator >::reset () inline
        {
            //BBS
            if (this->type == TYPE_STRING && this->data.s) {
                delete this->data.s;
                this->data.s = nullptr;
            }
            this->type = TYPE_EMPTY;
        }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::Data::s, Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_EMPTY, and Slic3r::client::expr< Iterator >::TYPE_STRING.
Referenced by Slic3r::client::expr< Iterator >::~expr(), Slic3r::client::expr< Iterator >::regex_op(), Slic3r::client::expr< Iterator >::set_b(), Slic3r::client::expr< Iterator >::set_d(), Slic3r::client::expr< Iterator >::set_i(), Slic3r::client::expr< Iterator >::set_s(), and Slic3r::client::expr< Iterator >::set_s().
round()
template<typename Iterator > expr Slic3r::client::expr< Iterator >::round (const Iterator start_pos) const inline
        {
            switch (this->type) {
            case TYPE_INT:
                return expr<Iterator>(this->i(), start_pos, this->it_range.end());
            case TYPE_DOUBLE:
                return expr<Iterator>(static_cast<int>(std::round(this->d())), start_pos, this->it_range.end());
            default:
                this->throw_exception("Cannot round a non-numeric value.");
            }
            assert(false);
            // Suppress compiler warnings.
            return expr();
        }
References Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_INT.
s() [1/2]
template<typename Iterator > std::string & Slic3r::client::expr< Iterator >::s () inline
{ return *data.s; }
References Slic3r::client::expr< Iterator >::data, and Slic3r::client::expr< Iterator >::Data::s.
Referenced by Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::operator+=(), Slic3r::client::operator<<(), Slic3r::client::expr< Iterator >::regex_op(), Slic3r::client::expr< Iterator >::set_s(), and Slic3r::client::expr< Iterator >::set_s().
s() [2/2]
template<typename Iterator > const std::string & Slic3r::client::expr< Iterator >::s () const inline
{ return *data.s; }
References Slic3r::client::expr< Iterator >::data, and Slic3r::client::expr< Iterator >::Data::s.
set_b()
template<typename Iterator > void Slic3r::client::expr< Iterator >::set_b (bool v) inline
{ this->reset(); this->data.b = v; this->type = TYPE_BOOL; }
References Slic3r::client::expr< Iterator >::Data::b, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::reset(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_BOOL.
Referenced by Slic3r::client::MyContext::scalar_variable_reference(), and Slic3r::client::MyContext::vector_variable_reference().
set_d()
template<typename Iterator > void Slic3r::client::expr< Iterator >::set_d (double v) inline
{ this->reset(); this->data.d = v; this->type = TYPE_DOUBLE; }
References Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::reset(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_DOUBLE.
Referenced by Slic3r::client::MyContext::scalar_variable_reference(), and Slic3r::client::MyContext::vector_variable_reference().
set_i()
template<typename Iterator > void Slic3r::client::expr< Iterator >::set_i (int v) inline
{ this->reset(); this->data.i = v; this->type = TYPE_INT; }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::Data::i, Slic3r::client::expr< Iterator >::reset(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_INT.
Referenced by Slic3r::client::MyContext::scalar_variable_reference(), and Slic3r::client::MyContext::vector_variable_reference().
set_if()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::set_if (bool & cond, bool & not_yet_consumed, std::string & str_in, std::string & str_out) inline static
        {
            if (cond && not_yet_consumed) {
                str_out = str_in;
                not_yet_consumed = false;
            }
        }
set_s() [1/2]
template<typename Iterator > void Slic3r::client::expr< Iterator >::set_s (const std::string & s) inline
{ this->reset(); this->data.s = new std::string(s); this->type = TYPE_STRING; }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::reset(), Slic3r::client::expr< Iterator >::s(), Slic3r::client::expr< Iterator >::Data::s, Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_STRING.
Referenced by Slic3r::client::expr< Iterator >::digits(), Slic3r::client::MyContext::scalar_variable_reference(), and Slic3r::client::MyContext::vector_variable_reference().
set_s() [2/2]
template<typename Iterator > void Slic3r::client::expr< Iterator >::set_s (std::string && s) inline
{ this->reset(); this->data.s = new std::string(std::move(s)); this->type = TYPE_STRING; }
References Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::reset(), Slic3r::client::expr< Iterator >::s(), Slic3r::client::expr< Iterator >::Data::s, Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_STRING.
ternary_op()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::ternary_op (expr< Iterator > & lhs, expr< Iterator > & rhs1, expr< Iterator > & rhs2) inline static
        {
            if (lhs.type != TYPE_BOOL)
                lhs.throw_exception("Not a boolean expression");
            if (lhs.b())
                lhs = std::move(rhs1);
            else
                lhs = std::move(rhs2);
        }
References Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::type, and Slic3r::client::expr< Iterator >::TYPE_BOOL.
throw_exception()
template<typename Iterator > void Slic3r::client::expr< Iterator >::throw_exception (const char * message) const inline
        {
            boost::throw_exception(qi::expectation_failure<Iterator>(
                this->it_range.begin(), this->it_range.end(), spirit::info(std::string("*") + message)));
        }
Referenced by Slic3r::client::expr< Iterator >::digits(), Slic3r::client::expr< Iterator >::evaluate_boolean(), Slic3r::client::expr< Iterator >::evaluate_boolean_to_string(), Slic3r::client::MyContext::evaluate_index(), Slic3r::client::expr< Iterator >::function_2params(), Slic3r::client::expr< Iterator >::operator%=(), Slic3r::client::expr< Iterator >::operator/=(), Slic3r::client::expr< Iterator >::regex_op(), Slic3r::client::expr< Iterator >::round(), Slic3r::client::expr< Iterator >::ternary_op(), Slic3r::client::expr< Iterator >::throw_if_not_numeric(), Slic3r::client::expr< Iterator >::unary_integer(), Slic3r::client::expr< Iterator >::unary_minus(), and Slic3r::client::expr< Iterator >::unary_not().
throw_if_not_numeric() [1/2]
template<typename Iterator > void Slic3r::client::expr< Iterator >::throw_if_not_numeric (const char * message) const inline
        {
            if (this->type != TYPE_INT && this->type != TYPE_DOUBLE)
                this->throw_exception(message);
        }
References Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_INT.
throw_if_not_numeric() [2/2]
template<typename Iterator > static void Slic3r::client::expr< Iterator >::throw_if_not_numeric (const expr< Iterator > & param) inline static
        {
            const char *err_msg = "Not a numeric type.";
            param.throw_if_not_numeric(err_msg);
        }
References Slic3r::client::expr< Iterator >::throw_if_not_numeric().
Referenced by Slic3r::client::expr< Iterator >::digits(), Slic3r::client::expr< Iterator >::function_2params(), Slic3r::client::expr< Iterator >::operator%=(), Slic3r::client::expr< Iterator >::operator*=(), Slic3r::client::expr< Iterator >::operator+=(), Slic3r::client::expr< Iterator >::operator-=(), Slic3r::client::expr< Iterator >::operator/=(), Slic3r::client::expr< Iterator >::random(), and Slic3r::client::expr< Iterator >::throw_if_not_numeric().
to_string()
template<typename Iterator > std::string Slic3r::client::expr< Iterator >::to_string () const inline
        {
            std::string out;
            switch (type) {
      case TYPE_BOOL:   out = data.b ? "true" : "false"; break;
            case TYPE_INT:    out = std::to_string(data.i); break;
            case TYPE_DOUBLE:
#if 0
                // The default converter produces trailing zeros after the decimal point.
        out = std::to_string(data.d);
#else
                // ostringstream default converter produces no trailing zeros after the decimal point.
                // It seems to be doing what the old boost::to_string() did.
        {
          std::ostringstream ss;
          ss << data.d;
          out = ss.str();
        }
#endif
        break;
            case TYPE_STRING: out = *data.s; break;
            default:          break;
            }
            return out;
        }
References Slic3r::client::expr< Iterator >::Data::b, Slic3r::client::expr< Iterator >::Data::d, Slic3r::client::expr< Iterator >::data, Slic3r::client::expr< Iterator >::Data::i, out, Slic3r::client::expr< Iterator >::Data::s, Slic3r::client::expr< Iterator >::type, Slic3r::client::expr< Iterator >::TYPE_BOOL, Slic3r::client::expr< Iterator >::TYPE_DOUBLE, Slic3r::client::expr< Iterator >::TYPE_INT, and Slic3r::client::expr< Iterator >::TYPE_STRING.
Referenced by Slic3r::client::expr< Iterator >::compare_op(), Slic3r::client::expr< Iterator >::operator+=(), and Slic3r::client::expr< Iterator >::to_string2().
to_string2()
template<typename Iterator > static void Slic3r::client::expr< Iterator >::to_string2 (expr< Iterator > & self, std::string & out) inline static
        {
            out = self.to_string();
        }
References out, and Slic3r::client::expr< Iterator >::to_string().
unary_integer()
template<typename Iterator > expr Slic3r::client::expr< Iterator >::unary_integer (const Iterator start_pos) const inline
        {
            switch (this->type) {
            case TYPE_INT:
                return expr<Iterator>(this->i(), start_pos, this->it_range.end());
            case TYPE_DOUBLE:
                return expr<Iterator>(static_cast<int>(this->d()), start_pos, this->it_range.end());
            default:
                this->throw_exception("Cannot convert to integer.");
            }
            assert(false);
            // Suppress compiler warnings.
            return expr();
        }
References Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_INT.
unary_minus()
template<typename Iterator > expr Slic3r::client::expr< Iterator >::unary_minus (const Iterator start_pos) const inline
        {
            switch (this->type) {
            case TYPE_INT :
                return expr<Iterator>(- this->i(), start_pos, this->it_range.end());
            case TYPE_DOUBLE:
                return expr<Iterator>(- this->d(), start_pos, this->it_range.end());
            default:
                this->throw_exception("Cannot apply unary minus operator.");
            }
            assert(false);
            // Suppress compiler warnings.
            return expr();
        }
References Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::throw_exception(), Slic3r::client::expr< Iterator >::TYPE_DOUBLE, and Slic3r::client::expr< Iterator >::TYPE_INT.
unary_not()
template<typename Iterator > expr Slic3r::client::expr< Iterator >::unary_not (const Iterator start_pos) const inline
        {
            switch (this->type) {
            case TYPE_BOOL:
                return expr<Iterator>(! this->b(), start_pos, this->it_range.end());
            default:
                this->throw_exception("Cannot apply a not operator.");
            }
            assert(false);
            // Suppress compiler warnings.
            return expr();
        }
References Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::throw_exception(), and Slic3r::client::expr< Iterator >::TYPE_BOOL.
Member Data Documentation
data
template<typename Iterator > union Slic3r::client::expr::Data Slic3r::client::expr< Iterator >::data
Referenced by Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::compare_op(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::function_2params(), Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::logical_op(), Slic3r::client::expr< Iterator >::operator%=(), Slic3r::client::expr< Iterator >::operator*=(), Slic3r::client::expr< Iterator >::operator+=(), Slic3r::client::expr< Iterator >::operator-=(), Slic3r::client::expr< Iterator >::operator/=(), Slic3r::client::expr< Iterator >::operator=(), Slic3r::client::expr< Iterator >::operator=(), Slic3r::client::expr< Iterator >::random(), Slic3r::client::expr< Iterator >::regex_op(), Slic3r::client::expr< Iterator >::reset(), Slic3r::client::expr< Iterator >::s(), Slic3r::client::expr< Iterator >::s(), Slic3r::client::expr< Iterator >::set_b(), Slic3r::client::expr< Iterator >::set_d(), Slic3r::client::expr< Iterator >::set_i(), Slic3r::client::expr< Iterator >::set_s(), Slic3r::client::expr< Iterator >::set_s(), and Slic3r::client::expr< Iterator >::to_string().
it_range
template<typename Iterator > boost::iterator_range<Iterator> Slic3r::client::expr< Iterator >::it_range
Referenced by Slic3r::client::expr< Iterator >::compare_op(), Slic3r::client::expr< Iterator >::logical_op(), Slic3r::client::expr< Iterator >::operator%=(), Slic3r::client::expr< Iterator >::operator*=(), Slic3r::client::expr< Iterator >::operator+=(), Slic3r::client::expr< Iterator >::operator-=(), Slic3r::client::expr< Iterator >::operator/=(), Slic3r::client::operator<<(), Slic3r::client::expr< Iterator >::operator=(), Slic3r::client::expr< Iterator >::operator=(), Slic3r::client::MyContext::random(), Slic3r::client::MyContext::scalar_variable_reference(), and Slic3r::client::MyContext::vector_variable_reference().
type
template<typename Iterator > Type Slic3r::client::expr< Iterator >::type
Referenced by Slic3r::client::expr< Iterator >::expr(), Slic3r::client::expr< Iterator >::as_d(), Slic3r::client::expr< Iterator >::as_i(), Slic3r::client::expr< Iterator >::as_i_rounded(), Slic3r::client::expr< Iterator >::compare_op(), Slic3r::client::expr< Iterator >::digits(), Slic3r::client::expr< Iterator >::evaluate_boolean(), Slic3r::client::expr< Iterator >::evaluate_boolean_to_string(), Slic3r::client::MyContext::evaluate_index(), Slic3r::client::expr< Iterator >::function_2params(), Slic3r::client::expr< Iterator >::logical_op(), Slic3r::client::expr< Iterator >::operator%=(), Slic3r::client::expr< Iterator >::operator*=(), Slic3r::client::expr< Iterator >::operator+=(), Slic3r::client::expr< Iterator >::operator-=(), Slic3r::client::expr< Iterator >::operator/=(), Slic3r::client::operator<<(), Slic3r::client::expr< Iterator >::operator=(), Slic3r::client::expr< Iterator >::operator=(), Slic3r::client::expr< Iterator >::random(), Slic3r::client::expr< Iterator >::regex_op(), Slic3r::client::expr< Iterator >::reset(), Slic3r::client::expr< Iterator >::set_b(), Slic3r::client::expr< Iterator >::set_d(), Slic3r::client::expr< Iterator >::set_i(), Slic3r::client::expr< Iterator >::set_s(), Slic3r::client::expr< Iterator >::set_s(), Slic3r::client::expr< Iterator >::ternary_op(), and Slic3r::client::expr< Iterator >::to_string().
The documentation for this struct was generated from the following file:
src/libslic3r/PlaceholderParser.cpp