OrcaSlicer: AuxiliaryModelNode Class Reference
AuxiliaryModelNode Class Reference
#include <src/slic3r/GUI/AuxiliaryDataViewModel.hpp>
Public Member Functions
AuxiliaryModelNode ()
AuxiliaryModelNode (AuxiliaryModelNode *parent, const wxString &abs_path, bool is_container)
~AuxiliaryModelNode ()
bool IsContainer () const
AuxiliaryModelNode * GetParent ()
void SetParent (AuxiliaryModelNode *parent)
AuxiliaryModelNodePtrArray & GetChildren ()
AuxiliaryModelNode * GetNthChild (unsigned int n)
void Insert (AuxiliaryModelNode *child, unsigned int n)
void Append (AuxiliaryModelNode *child)
unsigned int GetChildCount () const
Public Attributes
wxString name
wxString path
Private Attributes
AuxiliaryModelNode * m_parent
AuxiliaryModelNodePtrArray m_children
bool m_container
bool m_root
Detailed Description
Constructor & Destructor Documentation
AuxiliaryModelNode() [1/2]
AuxiliaryModelNode::AuxiliaryModelNode () inline
    {
        m_parent = NULL;
        name = "";
        m_container = true;
        m_root = true;
    }
References m_container, m_parent, m_root, name, and NULL.
AuxiliaryModelNode() [2/2]
AuxiliaryModelNode::AuxiliaryModelNode (AuxiliaryModelNode * parent, const wxString & abs_path, bool is_container) inline
    {
        m_parent = parent;
        m_container = is_container;
        m_root = false;
        path = abs_path;
        boost::filesystem::path path_obj(path.ToStdWstring());
        name = path_obj.filename().generic_wstring();
        parent->Append(this);
    }
References Append(), m_container, m_parent, m_root, name, and path.
~AuxiliaryModelNode()
AuxiliaryModelNode::~AuxiliaryModelNode () inline
    {
        // free all our children nodes
        size_t count = m_children.GetCount();
        for (size_t i = 0; i < count; i++)
        {
            AuxiliaryModelNode* child = m_children[i];
            delete child;
        }
    }
References count, and m_children.
Member Function Documentation
Append()
void AuxiliaryModelNode::Append (AuxiliaryModelNode * child) inline
    {
        m_children.Add(child);
    }
References m_children.
Referenced by AuxiliaryModelNode(), and AuxiliaryModel::Reparent().
GetChildCount()
unsigned int AuxiliaryModelNode::GetChildCount () const inline
    {
        return m_children.GetCount();
    }
References m_children.
GetChildren()
AuxiliaryModelNodePtrArray & AuxiliaryModelNode::GetChildren () inline
    {
        return m_children;
    }
References m_children.
Referenced by AuxiliaryModel::CreateFolder(), AuxiliaryModel::Delete(), AuxiliaryModel::GetChildren(), AuxiliaryModel::ImportFile(), AuxiliaryModel::MoveItem(), AuxiliaryModel::Rename(), and AuxiliaryModel::Reparent().
GetNthChild()
AuxiliaryModelNode * AuxiliaryModelNode::GetNthChild (unsigned int n) inline
    {
        return m_children.Item(n);
    }
References m_children, and n.
GetParent()
AuxiliaryModelNode * AuxiliaryModelNode::GetParent () inline
    {
        return m_parent;
    }
References m_parent.
Referenced by AuxiliaryModel::Delete(), AuxiliaryList::do_import_file(), AuxiliaryModel::GetParent(), AuxiliaryModel::ImportFile(), AuxiliaryModel::IsOrphan(), AuxiliaryModel::MoveItem(), AuxiliaryModel::Rename(), and AuxiliaryModel::Reparent().
Insert()
void AuxiliaryModelNode::Insert (AuxiliaryModelNode * child, unsigned int n) inline
    {
        m_children.Insert(child, n);
    }
References m_children, and n.
IsContainer()
bool AuxiliaryModelNode::IsContainer () const inline
    {
        return m_container;
    }
References m_container.
Referenced by AuxiliaryList::AuxiliaryList(), AuxiliaryModel::Delete(), AuxiliaryList::do_import_file(), AuxiliaryModel::ImportFile(), AuxiliaryModel::IsContainer(), AuxiliaryModel::MoveItem(), AuxiliaryList::on_begin_drag(), AuxiliaryList::on_context_menu(), AuxiliaryList::on_import_file(), AuxiliaryList::on_left_dclick(), AuxiliaryModel::Reload(), AuxiliaryModel::Rename(), and AuxiliaryModel::Reparent().
SetParent()
void AuxiliaryModelNode::SetParent (AuxiliaryModelNode * parent) inline
    {
        m_parent = parent;
    }
References m_parent.
Referenced by AuxiliaryModel::Reparent().
Member Data Documentation
m_children
AuxiliaryModelNodePtrArray AuxiliaryModelNode::m_children private
Referenced by ~AuxiliaryModelNode(), Append(), GetChildCount(), GetChildren(), GetNthChild(), and Insert().
m_container
bool AuxiliaryModelNode::m_container private
Referenced by AuxiliaryModelNode(), AuxiliaryModelNode(), and IsContainer().
m_parent
AuxiliaryModelNode* AuxiliaryModelNode::m_parent private
Referenced by AuxiliaryModelNode(), AuxiliaryModelNode(), GetParent(), and SetParent().
m_root
bool AuxiliaryModelNode::m_root private
Referenced by AuxiliaryModelNode(), and AuxiliaryModelNode().
name
wxString AuxiliaryModelNode::name
Referenced by AuxiliaryModelNode(), AuxiliaryModelNode(), AuxiliaryModel::Delete(), AuxiliaryModel::GetValue(), AuxiliaryModel::ImportFile(), AuxiliaryModel::MoveItem(), AuxiliaryModel::Rename(), and AuxiliaryModel::SetValue().
path
wxString AuxiliaryModelNode::path
Referenced by AuxiliaryList::AuxiliaryList(), AuxiliaryModelNode(), AuxiliaryModel::Delete(), AuxiliaryModel::MoveItem(), AuxiliaryList::on_context_menu(), AuxiliaryList::on_left_dclick(), and AuxiliaryModel::Rename().
The documentation for this class was generated from the following file:
src/slic3r/GUI/AuxiliaryDataViewModel.hpp