OrcaSlicer: Slic3r::sla::SupportTree Class Reference
Slic3r::sla::SupportTree Class Reference abstract
The class containing mesh data for the generated supports.
#include <src/libslic3r/SLA/SupportTree.hpp>
Public Types
using UPtr = std::unique_ptr< SupportTree >
Public Member Functions
virtual ~SupportTree ()=default
virtual const indexed_triangle_set & retrieve_mesh (MeshType meshtype) const =0
virtual const indexed_triangle_set & add_pad (const ExPolygons &modelbase, const PadConfig &pcfg)=0
Adding the "pad" under the supports. modelbase will be used according to the embed_object flag in PoolConfig. If set, the plate will be interpreted as the model's intrinsic pad. Otherwise, the modelbase will be unified with the base plate calculated from the supports.
virtual void remove_pad ()=0
std::vector< ExPolygons > slice (const std::vector< float > &, float closing_radius) const
void retrieve_full_mesh (indexed_triangle_set &outmesh) const
const JobController & ctl () const
Static Public Member Functions
static UPtr create (const SupportableMesh &input, const JobController &ctl={})
Private Attributes
JobController m_ctl
Detailed Description
The class containing mesh data for the generated supports.
Member Typedef Documentation
UPtr
using Slic3r::sla::SupportTree::UPtr = std::unique_ptr<SupportTree>
Constructor & Destructor Documentation
~SupportTree()
virtual Slic3r::sla::SupportTree::~SupportTree () virtual default
Member Function Documentation
add_pad()
virtual const indexed_triangle_set & Slic3r::sla::SupportTree::add_pad (const ExPolygons & modelbase, const PadConfig & pcfg) pure virtual
Adding the "pad" under the supports. modelbase will be used according to the embed_object flag in PoolConfig. If set, the plate will be interpreted as the model's intrinsic pad. Otherwise, the modelbase will be unified with the base plate calculated from the supports.
Implemented in Slic3r::sla::SupportTreeBuilder.
create()
SupportTree::UPtr Slic3r::sla::SupportTree::create (const SupportableMesh & input, const JobController & ctl = {}) static
{
    auto builder = make_unique<SupportTreeBuilder>();
    builder->m_ctl = ctl;
    if (sm.cfg.enabled) {
        // Execute takes care about the ground_level
        SupportTreeBuildsteps::execute(*builder, sm);
        builder->merge_and_cleanup();   // clean metadata, leave only the meshes.
    } else {
        // If a pad gets added later, it will be in the right Z level
        builder->ground_level = sm.emesh.ground_level();
    }
    return std::move(builder);
}
References Slic3r::sla::SupportableMesh::cfg, ctl(), Slic3r::sla::SupportableMesh::emesh, Slic3r::sla::SupportTreeConfig::enabled, Slic3r::sla::SupportTreeBuildsteps::execute(), and Slic3r::sla::IndexedMesh::ground_level().
Referenced by Slic3r::SLAPrintObject::SupportData::create_support_tree().
ctl()
const JobController & Slic3r::sla::SupportTree::ctl () const inline
{ return m_ctl; }
References m_ctl.
Referenced by Slic3r::sla::SupportTreeBuilder::add_pad(), create(), Slic3r::sla::SupportTreeBuildsteps::execute(), Slic3r::sla::SupportTreeBuilder::merged_mesh(), and slice().
remove_pad()
virtual void Slic3r::sla::SupportTree::remove_pad () pure virtual
Implemented in Slic3r::sla::SupportTreeBuilder.
retrieve_full_mesh()
void Slic3r::sla::SupportTree::retrieve_full_mesh (indexed_triangle_set & outmesh) const
{
    its_merge(outmesh, retrieve_mesh(MeshType::Support));
    its_merge(outmesh, retrieve_mesh(MeshType::Pad));
}
References Slic3r::its_merge(), Slic3r::sla::Pad, retrieve_mesh(), and Slic3r::sla::Support.
retrieve_mesh()
virtual const indexed_triangle_set & Slic3r::sla::SupportTree::retrieve_mesh (MeshType meshtype) const pure virtual
Implemented in Slic3r::sla::SupportTreeBuilder.
Referenced by retrieve_full_mesh(), and slice().
slice()
std::vector< ExPolygons > Slic3r::sla::SupportTree::slice (const std::vector< float > & grid, float closing_radius) const
{
    const indexed_triangle_set &sup_mesh = retrieve_mesh(MeshType::Support);
    const indexed_triangle_set &pad_mesh = retrieve_mesh(MeshType::Pad);
    using Slices = std::vector<ExPolygons>;
    auto slices = reserve_vector<Slices>(2);
    if (!sup_mesh.empty()) {
        slices.emplace_back();
        slices.back() = slice_mesh_ex(sup_mesh, grid, cr, ctl().cancelfn);
    }
    if (!pad_mesh.empty()) {
        slices.emplace_back();
        auto bb = bounding_box(pad_mesh);
        auto maxzit = std::upper_bound(grid.begin(), grid.end(), bb.max.z());
        auto cap = grid.end() - maxzit;
        auto padgrid = reserve_vector<float>(size_t(cap > 0 ? cap : 0));
        std::copy(grid.begin(), maxzit, std::back_inserter(padgrid));
        slices.back() = slice_mesh_ex(pad_mesh, padgrid, cr, ctl().cancelfn);
    }
    size_t len = grid.size();
    for (const Slices &slv : slices) { len = std::min(len, slv.size()); }
    // Either the support or the pad or both has to be non empty
    if (slices.empty()) return {};
    Slices &mrg = slices.front();
    for (auto it = std::next(slices.begin()); it != slices.end(); ++it) {
        for (size_t i = 0; i < len; ++i) {
            Slices &slv = *it;
            std::copy(slv[i].begin(), slv[i].end(), std::back_inserter(mrg[i]));
            slv[i] = {}; // clear and delete
        }
    }
    return mrg;
}
References Slic3r::bounding_box(), ctl(), indexed_triangle_set::empty(), end, Slic3r::grid(), Slic3r::sla::Pad, retrieve_mesh(), Slic3r::slice_mesh_ex(), and Slic3r::sla::Support.
Member Data Documentation
m_ctl
JobController Slic3r::sla::SupportTree::m_ctl private
Referenced by ctl().
The documentation for this class was generated from the following files:
src/libslic3r/SLA/SupportTree.hpp
src/libslic3r/SLA/SupportTree.cpp