OrcaSlicer: Slic3r::GUI::Sidebar Class Reference
Slic3r::GUI::Sidebar Class Reference
#include <src/slic3r/GUI/Plater.hpp>
Classes
struct priv
Public Member Functions
Sidebar (Plater *parent)
Sidebar (Sidebar &&)=delete
Sidebar (const Sidebar &)=delete
Sidebar & operator= (Sidebar &&)=delete
Sidebar & operator= (const Sidebar &)=delete
~Sidebar ()
void init_filament_combo (PlaterPresetComboBox **combo, const int filament_idx)
void remove_unused_filament_combos (const size_t current_extruder_count)
void update_all_preset_comboboxes ()
void update_presets (Slic3r::Preset::Type preset_type)
void update_presets_from_to (Slic3r::Preset::Type preset_type, std::string from, std::string to)
void change_top_border_for_mode_sizer (bool increase_border)
void msw_rescale ()
void sys_color_changed ()
void search ()
void jump_to_option (size_t selected)
void jump_to_option (const std::string &opt_key, Preset::Type type, const std::wstring &category)
void on_filaments_change (size_t num_filaments)
void on_bed_type_change (BedType bed_type)
void load_ams_list (std::string const &device, std::map< std::string, Ams * > const &list)
void sync_ams_list ()
ObjectList * obj_list ()
ObjectSettings * obj_settings ()
ObjectLayers * obj_layers ()
wxPanel * scrolled_panel ()
wxPanel * print_panel ()
wxPanel * filament_panel ()
ConfigOptionsGroup * og_freq_chng_params (const bool is_fff)
wxButton * get_wiping_dialog_button ()
void enable_buttons (bool enable)
void set_btn_label (const ActionButtonType btn_type, const wxString &label) const
bool show_reslice (bool show) const
bool show_export (bool show) const
bool show_send (bool show) const
bool show_eject (bool show) const
bool show_export_removable (bool show) const
bool get_eject_shown () const
bool is_multifilament ()
void update_mode ()
bool is_collapsed ()
void collapse (bool collapse)
void update_searcher ()
void update_ui_from_settings ()
bool show_object_list (bool show) const
void finish_param_edit ()
void show_mode_sizer (bool show)
std::vector< PlaterPresetComboBox * > & combos_filament ()
Search::OptionsSearcher & get_searcher ()
std::string & get_search_line ()
Private Attributes
ConfigOptionMode m_mode
std::unique_ptr< priv > p
wxBoxSizer * m_scrolled_sizer = nullptr
ComboBox * m_bed_type_list = nullptr
ScalableButton * connection_btn = nullptr
ScalableButton * ams_btn = nullptr
Detailed Description
Constructor & Destructor Documentation
Sidebar() [1/3]
Slic3r::GUI::Sidebar::Sidebar (Plater * parent)
    : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxSize(42 * wxGetApp().em_unit(), -1)), p(new priv(parent))
{
    Choice::register_dynamic_list("support_filament", &dynamic_filament_list);
    Choice::register_dynamic_list("support_interface_filament", &dynamic_filament_list);
    p->scrolled = new wxPanel(this);
    //    p->scrolled->SetScrollbars(0, 100, 1, 2); // ys_DELETE_after_testing. pixelsPerUnitY = 100
    // but this cause the bad layout of the sidebar, when all infoboxes appear.
    // As a result we can see the empty block at the bottom of the sidebar
    // But if we set this value to 5, layout will be better
    //p->scrolled->SetScrollRate(0, 5);
    p->scrolled->SetBackgroundColour(*wxWHITE);
    SetFont(wxGetApp().normal_font());
#ifndef __APPLE__
#ifdef _WIN32
    wxGetApp().UpdateDarkUI(this);
    wxGetApp().UpdateDarkUI(p->scrolled);
#else
    SetBackgroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW));
#endif
#endif
    int em = wxGetApp().em_unit();
    //BBS refine layout and styles
    // Sizer in the scrolled area
    auto* scrolled_sizer = m_scrolled_sizer = new wxBoxSizer(wxVERTICAL);
    p->scrolled->SetSizer(scrolled_sizer);
    wxColour title_bg = wxColour(248, 248, 248);
    wxColour inactive_text = wxColour(86, 86, 86);
    wxColour active_text = wxColour(0, 0, 0);
    wxColour static_line_col = wxColour(166, 169, 170);
#ifdef __WINDOWS__
    p->scrolled->SetDoubleBuffered(true);
#endif //__WINDOWS__
    // add printer
    {
        /***************** 1. create printer title bar    **************/
        // 1.1 create title bar resources
        p->m_panel_printer_title = new StaticBox(p->scrolled, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL | wxBORDER_NONE);
        p->m_panel_printer_title->SetBackgroundColor(title_bg);
        p->m_panel_printer_title->SetBackgroundColor2(0xF1F1F1);
        p->m_printer_icon = new ScalableButton(p->m_panel_printer_title, wxID_ANY, "printer");
        p->m_text_printer_settings = new Label(p->m_panel_printer_title, _L("Printer"), LB_PROPAGATE_MOUSE_EVENT);
        p->m_printer_icon->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e) {
            //auto wizard_t = new ConfigWizard(wxGetApp().mainframe);
            //wizard_t->run(ConfigWizard::RR_USER, ConfigWizard::SP_CUSTOM);
            });
        p->m_printer_setting = new ScalableButton(p->m_panel_printer_title, wxID_ANY, "settings");
        p->m_printer_setting->Bind(wxEVT_BUTTON, [this](wxCommandEvent &e) {
            // p->editing_filament = -1;
            // wxGetApp().params_dialog()->Popup();
            // wxGetApp().get_tab(Preset::TYPE_FILAMENT)->restore_last_select_item();
            wxGetApp().run_wizard(ConfigWizard::RR_USER, ConfigWizard::SP_PRINTERS);
            });
        wxBoxSizer* h_sizer_title = new wxBoxSizer(wxHORIZONTAL);
        h_sizer_title->Add(p->m_printer_icon, 0, wxALIGN_CENTRE | wxLEFT | wxRIGHT, em);
        h_sizer_title->Add(p->m_text_printer_settings, 0, wxALIGN_CENTER);
        h_sizer_title->AddStretchSpacer();
        h_sizer_title->Add(p->m_printer_setting, 0, wxALIGN_CENTER);
        h_sizer_title->Add(15 * em / 10, 0, 0, 0, 0);
        h_sizer_title->SetMinSize(-1, 3 * em);
        p->m_panel_printer_title->SetSizer(h_sizer_title);
        p->m_panel_printer_title->Layout();
        // 1.2 Add spliters around title bar
        // add spliter 1
        //auto spliter_1 = new ::StaticLine(p->scrolled);
        //spliter_1->SetBackgroundColour("#A6A9AA");
        //scrolled_sizer->Add(spliter_1, 0, wxEXPAND);
        // add printer title
        scrolled_sizer->Add(p->m_panel_printer_title, 0, wxEXPAND | wxALL, 0);
        p->m_panel_printer_title->Bind(wxEVT_LEFT_UP, [this] (auto & e) {
            if (p->m_panel_printer_content->GetMaxHeight() == 0)
                p->m_panel_printer_content->SetMaxSize({-1, -1});
            else
                p->m_panel_printer_content->SetMaxSize({-1, 0});
            m_scrolled_sizer->Layout();
        });
        // add spliter 2
        auto spliter_2 = new ::StaticLine(p->scrolled);
        spliter_2->SetLineColour("#CECECE");
        scrolled_sizer->Add(spliter_2, 0, wxEXPAND);
        /*************************** 2. add printer content ************************/
        p->m_panel_printer_content = new wxPanel(p->scrolled, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
        p->m_panel_printer_content->SetBackgroundColour(wxColour(255, 255, 255));
        PlaterPresetComboBox* combo_printer = new PlaterPresetComboBox(p->m_panel_printer_content, Preset::TYPE_PRINTER);
        ScalableButton* edit_btn = new ScalableButton(p->m_panel_printer_content, wxID_ANY, "edit");
        edit_btn->SetToolTip(_L("Click to edit preset"));
        edit_btn->Bind(wxEVT_BUTTON, [this, combo_printer](wxCommandEvent)
            {
                p->editing_filament = -1;
                if (combo_printer->switch_to_tab())
                    p->editing_filament = 0;
            });
        combo_printer->edit_btn = edit_btn;
        p->combo_printer = combo_printer;
        connection_btn = new ScalableButton(p->m_panel_printer_content, wxID_ANY, "monitor_signal_strong");
        connection_btn->SetBackgroundColour(wxColour(255, 255, 255));
        connection_btn->SetToolTip(_L("Connection"));
        connection_btn->Bind(wxEVT_BUTTON, [this, combo_printer](wxCommandEvent)
            {
                PhysicalPrinterDialog dlg(this->GetParent());
                dlg.ShowModal();
            });
        wxBoxSizer* vsizer_printer = new wxBoxSizer(wxVERTICAL);
        wxBoxSizer* hsizer_printer = new wxBoxSizer(wxHORIZONTAL);
        vsizer_printer->AddSpacer(FromDIP(16));
        hsizer_printer->Add(combo_printer, 1, wxALIGN_CENTER_VERTICAL | wxLEFT, FromDIP(3));
        hsizer_printer->Add(edit_btn, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, FromDIP(3));
        hsizer_printer->Add(FromDIP(8), 0, 0, 0, 0);
        hsizer_printer->Add(connection_btn, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, FromDIP(3));
        hsizer_printer->Add(FromDIP(8), 0, 0, 0, 0);
        vsizer_printer->Add(hsizer_printer, 0, wxEXPAND, 0);
        // Bed type selection
        wxBoxSizer* bed_type_sizer = new wxBoxSizer(wxHORIZONTAL);
        wxStaticText* bed_type_title = new wxStaticText(p->m_panel_printer_content, wxID_ANY, _L("Bed type"));
        //bed_type_title->SetBackgroundColour();
        bed_type_title->Wrap(-1);
        bed_type_title->SetFont(Label::Body_14);
        m_bed_type_list = new ComboBox(p->m_panel_printer_content, wxID_ANY, wxString(""), wxDefaultPosition, {-1, FromDIP(30)}, 0, nullptr, wxCB_READONLY);
        const ConfigOptionDef* bed_type_def = print_config_def.get("curr_bed_type");
        if (bed_type_def && bed_type_def->enum_keys_map) {
            for (auto item : bed_type_def->enum_labels) {
                m_bed_type_list->AppendString(_L(item));
            }
        }
        bed_type_title->Bind(wxEVT_ENTER_WINDOW, [bed_type_title, this](wxMouseEvent &e) {
            e.Skip();
            auto font = bed_type_title->GetFont();
            font.SetUnderlined(true);
            bed_type_title->SetFont(font);
            SetCursor(wxCURSOR_HAND);
        });
        bed_type_title->Bind(wxEVT_LEAVE_WINDOW, [bed_type_title, this](wxMouseEvent &e) {
            e.Skip();
            auto font = bed_type_title->GetFont();
            font.SetUnderlined(false);
            bed_type_title->SetFont(font);
            SetCursor(wxCURSOR_ARROW);
        });
        bed_type_title->Bind(wxEVT_LEFT_UP, [bed_type_title, this](wxMouseEvent &e) {
            wxLaunchDefaultBrowser("https://wiki.bambulab.com/en/x1/manual/compatibility-and-parameter-settings-of-filaments");
        });
        AppConfig *app_config = wxGetApp().app_config;
        std::string str_bed_type = app_config->get("curr_bed_type");
        int bed_type_value = atoi(str_bed_type.c_str());
        // hotfix: btDefault is added as the first one in BedType, and app_config should not be btDefault
        if (bed_type_value == 0) {
            app_config->set("curr_bed_type", "1");
            bed_type_value = 1;
        }
        int bed_type_idx = bed_type_value - 1;
        m_bed_type_list->Select(bed_type_idx);
        bed_type_sizer->Add(bed_type_title, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, FromDIP(10));
        bed_type_sizer->Add(m_bed_type_list, 1, wxLEFT | wxRIGHT | wxEXPAND, FromDIP(10));
        vsizer_printer->Add(bed_type_sizer, 0, wxEXPAND | wxTOP, FromDIP(5));
        vsizer_printer->AddSpacer(FromDIP(16));
        auto& project_config = wxGetApp().preset_bundle->project_config;
        /*const t_config_enum_values* keys_map = print_config_def.get("curr_bed_type")->enum_keys_map;
        BedType bed_type = btCount;
        for (auto item : *keys_map) {
            if (item.first == str_bed_type)
                bed_type = (BedType)item.second;
        }*/
        BedType bed_type = (BedType)bed_type_value;
        project_config.set_key_value("curr_bed_type", new ConfigOptionEnum<BedType>(bed_type));
        p->m_panel_printer_content->SetSizer(vsizer_printer);
        p->m_panel_printer_content->Layout();
        scrolled_sizer->Add(p->m_panel_printer_content, 0, wxEXPAND, 0);
    }
    {
    // add filament title
    p->m_panel_filament_title = new StaticBox(p->scrolled, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL | wxBORDER_NONE);
    p->m_panel_filament_title->SetBackgroundColor(title_bg);
    p->m_panel_filament_title->SetBackgroundColor2(0xF1F1F1);
    p->m_panel_filament_title->Bind(wxEVT_LEFT_UP, [this](wxMouseEvent &e) {
        if (e.GetPosition().x > (p->m_flushing_volume_btn->IsShown()
                ? p->m_flushing_volume_btn->GetPosition().x : p->m_bpButton_add_filament->GetPosition().x))
            return;
        if (p->m_panel_filament_content->GetMaxHeight() == 0)
            p->m_panel_filament_content->SetMaxSize({-1, -1});
        else
            p->m_panel_filament_content->SetMaxSize({-1, 0});
        m_scrolled_sizer->Layout();
    });
    wxBoxSizer* bSizer39;
    bSizer39 = new wxBoxSizer( wxHORIZONTAL );
    p->m_filament_icon = new ScalableButton(p->m_panel_filament_title, wxID_ANY, "filament");
    p->m_staticText_filament_settings = new Label(p->m_panel_filament_title, _L("Filament"), LB_PROPAGATE_MOUSE_EVENT);
    bSizer39->Add(p->m_filament_icon, 0, wxALIGN_CENTER | wxLEFT | wxRIGHT, FromDIP(10));
    bSizer39->Add( p->m_staticText_filament_settings, 0, wxALIGN_CENTER );
    bSizer39->Add(FromDIP(10), 0, 0, 0, 0);
    bSizer39->SetMinSize(-1, FromDIP(30));
    p->m_panel_filament_title->SetSizer( bSizer39 );
    p->m_panel_filament_title->Layout();
    auto spliter_1 = new ::StaticLine(p->scrolled);
    spliter_1->SetLineColour("#A6A9AA");
    scrolled_sizer->Add(spliter_1, 0, wxEXPAND);
    scrolled_sizer->Add(p->m_panel_filament_title, 0, wxEXPAND | wxALL, 0);
    auto spliter_2 = new ::StaticLine(p->scrolled);
    spliter_2->SetLineColour("#CECECE");
    scrolled_sizer->Add(spliter_2, 0, wxEXPAND);
    bSizer39->AddStretchSpacer(1);
    // BBS
    // add wiping dialog
    //wiping_dialog_button->SetFont(wxGetApp().normal_font());
    p->m_flushing_volume_btn = new Button(p->m_panel_filament_title, _L("Flushing volumes"));
    p->m_flushing_volume_btn->SetFont(Label::Body_10);
    p->m_flushing_volume_btn->SetPaddingSize(wxSize(FromDIP(8),FromDIP(3)));
    p->m_flushing_volume_btn->SetCornerRadius(FromDIP(8));
    StateColor flush_bg_col(std::pair<wxColour, int>(wxColour(219, 253, 231), StateColor::Pressed),
                            std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Hovered),
                            std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Normal));
    StateColor flush_fg_col(std::pair<wxColour, int>(wxColour(107, 107, 106), StateColor::Pressed),
                            std::pair<wxColour, int>(wxColour(107, 107, 106), StateColor::Hovered),
                            std::pair<wxColour, int>(wxColour(107, 107, 106), StateColor::Normal));
    StateColor flush_bd_col(std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Pressed),
                            std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Hovered),
                            std::pair<wxColour, int>(wxColour(172, 172, 172), StateColor::Normal));
    p->m_flushing_volume_btn->SetBackgroundColor(flush_bg_col);
    p->m_flushing_volume_btn->SetBorderColor(flush_bd_col);
    p->m_flushing_volume_btn->SetTextColor(flush_fg_col);
    p->m_flushing_volume_btn->SetFocus();
    p->m_flushing_volume_btn->SetId(wxID_RESET);
    p->m_flushing_volume_btn->Rescale();
    p->m_flushing_volume_btn->Bind(wxEVT_BUTTON, ([parent](wxCommandEvent &e)
        {
            auto& project_config = wxGetApp().preset_bundle->project_config;
            auto& printer_config = wxGetApp().preset_bundle->printers.get_edited_preset().config;
            const std::vector<double>& init_matrix = (project_config.option<ConfigOptionFloats>("flush_volumes_matrix"))->values;
            const std::vector<double>& init_extruders = (project_config.option<ConfigOptionFloats>("flush_volumes_vector"))->values;
            ConfigOption* extra_flush_volume_opt = printer_config.option("nozzle_volume");
            int extra_flush_volume = extra_flush_volume_opt ? (int)extra_flush_volume_opt->getFloat() : 0;
            ConfigOptionFloat* flush_multi_opt = project_config.option<ConfigOptionFloat>("flush_multiplier");
            float flush_multiplier = flush_multi_opt ? flush_multi_opt->getFloat() : 1.f;
            const std::vector<std::string> extruder_colours = wxGetApp().plater()->get_extruder_colors_from_plater_config();
            WipingDialog dlg(parent, cast<float>(init_matrix), cast<float>(init_extruders), extruder_colours, extra_flush_volume, flush_multiplier);
            if (dlg.ShowModal() == wxID_OK) {
                std::vector<float> matrix = dlg.get_matrix();
                std::vector<float> extruders = dlg.get_extruders();
                (project_config.option<ConfigOptionFloats>("flush_volumes_matrix"))->values = std::vector<double>(matrix.begin(), matrix.end());
                (project_config.option<ConfigOptionFloats>("flush_volumes_vector"))->values = std::vector<double>(extruders.begin(), extruders.end());
                (project_config.option<ConfigOptionFloat>("flush_multiplier"))->set(new ConfigOptionFloat(dlg.get_flush_multiplier()));
                wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
                wxGetApp().plater()->update_project_dirty_from_presets();
                wxPostEvent(parent, SimpleEvent(EVT_SCHEDULE_BACKGROUND_PROCESS, parent));
            }
        }));
    bSizer39->Add(p->m_flushing_volume_btn, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, FromDIP(5));
    bSizer39->Hide(p->m_flushing_volume_btn);
    bSizer39->Add(FromDIP(10), 0, 0, 0, 0 );
    ScalableButton* add_btn = new ScalableButton(p->m_panel_filament_title, wxID_ANY, "add_filament");
    add_btn->SetToolTip(_L("Add one filament"));
    add_btn->Bind(wxEVT_BUTTON, [this, scrolled_sizer](wxCommandEvent& e){
        // Orca: limit filament choices to 64
        if (p->combos_filament.size() >= 64)
            return;
        int filament_count = p->combos_filament.size() + 1;
        wxColour new_col = Plater::get_next_color_for_filament();
        std::string new_color = new_col.GetAsString(wxC2S_HTML_SYNTAX).ToStdString();
        wxGetApp().preset_bundle->set_num_filaments(filament_count, new_color);
        wxGetApp().plater()->on_filaments_change(filament_count);
        wxGetApp().get_tab(Preset::TYPE_PRINT)->update();
        wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
    });
    p->m_bpButton_add_filament = add_btn;
    bSizer39->Add(add_btn, 0, wxALIGN_CENTER|wxALL, FromDIP(5));
    bSizer39->Add(FromDIP(10), 0, 0, 0, 0 );
    ScalableButton* del_btn = new ScalableButton(p->m_panel_filament_title, wxID_ANY, "delete_filament");
    del_btn->SetToolTip(_L("Remove last filament"));
    del_btn->Bind(wxEVT_BUTTON, [this, scrolled_sizer](wxCommandEvent &e) {
        if (p->combos_filament.size() <= 1)
            return;
        size_t filament_count = p->combos_filament.size() - 1;
        if (wxGetApp().preset_bundle->is_the_only_edited_filament(filament_count) || (filament_count == 1)) {
            wxGetApp().get_tab(Preset::TYPE_FILAMENT)->select_preset(wxGetApp().preset_bundle->filament_presets[0], false, "", true);
        }
        if (p->editing_filament >= filament_count) {
            p->editing_filament = -1;
        }
        wxGetApp().preset_bundle->set_num_filaments(filament_count);
        wxGetApp().plater()->on_filaments_change(filament_count);
        wxGetApp().get_tab(Preset::TYPE_PRINT)->update();
        wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
    });
    p->m_bpButton_del_filament = del_btn;
    bSizer39->Add(del_btn, 0, wxALIGN_CENTER_VERTICAL, FromDIP(5));
    bSizer39->Add(FromDIP(20), 0, 0, 0, 0);
    ams_btn = new ScalableButton(p->m_panel_filament_title, wxID_ANY, "ams_fila_sync", wxEmptyString, wxDefaultSize, wxDefaultPosition,
                                                 wxBU_EXACTFIT | wxNO_BORDER, false, 18);
    ams_btn->SetToolTip(_L("Synchronize filament list from AMS"));
    ams_btn->Bind(wxEVT_BUTTON, [this, scrolled_sizer](wxCommandEvent &e) {
        sync_ams_list();
    });
    p->m_bpButton_ams_filament = ams_btn;
    bSizer39->Add(ams_btn, 0, wxALIGN_CENTER|wxALL, FromDIP(5));
    bSizer39->Add(FromDIP(10), 0, 0, 0, 0 );
    ScalableButton* set_btn = new ScalableButton(p->m_panel_filament_title, wxID_ANY, "settings");
    set_btn->SetToolTip(_L("Set filaments to use"));
    set_btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent &e) {
        p->editing_filament = -1;
        // wxGetApp().params_dialog()->Popup();
        // wxGetApp().get_tab(Preset::TYPE_FILAMENT)->restore_last_select_item();
        wxGetApp().run_wizard(ConfigWizard::RR_USER, ConfigWizard::SP_FILAMENTS);
        });
    p->m_bpButton_set_filament = set_btn;
    bSizer39->Add(set_btn, 0, wxALIGN_CENTER);
    bSizer39->Add(FromDIP(15), 0, 0, 0, 0);
    // add filament content
    p->m_panel_filament_content = new wxPanel( p->scrolled, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL );
    p->m_panel_filament_content->SetBackgroundColour( wxColour( 255, 255, 255 ) );
    //wxBoxSizer* bSizer_filament_content;
    //bSizer_filament_content = new wxBoxSizer( wxHORIZONTAL );
    // BBS:  filament double columns
    p->sizer_filaments = new wxBoxSizer(wxHORIZONTAL);
    p->sizer_filaments->Add(new wxBoxSizer(wxVERTICAL), 1, wxEXPAND);
    p->sizer_filaments->Add(new wxBoxSizer(wxVERTICAL), 1, wxEXPAND);
    p->combos_filament.push_back(nullptr);
    /* first filament item */
    p->combos_filament[0] = new PlaterPresetComboBox(p->m_panel_filament_content, Preset::TYPE_FILAMENT);
    auto combo_and_btn_sizer = new wxBoxSizer(wxHORIZONTAL);
    // BBS:  filament double columns
    combo_and_btn_sizer->Add(FromDIP(8), 0, 0, 0, 0);
    if (p->combos_filament[0]->clr_picker) {
        p->combos_filament[0]->clr_picker->SetLabel("1");
        combo_and_btn_sizer->Add(p->combos_filament[0]->clr_picker, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, FromDIP(3));
    }
    combo_and_btn_sizer->Add(p->combos_filament[0], 1, wxALL | wxEXPAND, FromDIP(2))->SetMinSize({-1, FromDIP(30) });
    ScalableButton* edit_btn = new ScalableButton(p->m_panel_filament_content, wxID_ANY, "edit");
    edit_btn->SetBackgroundColour(wxColour(255, 255, 255));
    edit_btn->SetToolTip(_L("Click to edit preset"));
    PlaterPresetComboBox* combobox = p->combos_filament[0];
    edit_btn->Bind(wxEVT_BUTTON, [this, combobox](wxCommandEvent)
        {
            p->editing_filament = 0;
            combobox->switch_to_tab();
        });
    combobox->edit_btn = edit_btn;
    combo_and_btn_sizer->Add(edit_btn, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, FromDIP(3));
    combo_and_btn_sizer->Add(FromDIP(8), 0, 0, 0, 0);
    p->combos_filament[0]->set_filament_idx(0);
    p->sizer_filaments->GetItem((size_t)0)->GetSizer()->Add(combo_and_btn_sizer, 1, wxEXPAND);
    //bSizer_filament_content->Add(p->sizer_filaments, 1, wxALIGN_CENTER | wxALL);
    wxSizer *sizer_filaments2 = new wxBoxSizer(wxVERTICAL);
    sizer_filaments2->AddSpacer(FromDIP(16));
    sizer_filaments2->Add(p->sizer_filaments, 0, wxEXPAND, 0);
    sizer_filaments2->AddSpacer(FromDIP(16));
    p->m_panel_filament_content->SetSizer(sizer_filaments2);
    p->m_panel_filament_content->Layout();
    scrolled_sizer->Add(p->m_panel_filament_content, 0, wxEXPAND, 0);
    }
    {
    //add project title
    auto params_panel = ((MainFrame*)parent->GetParent())->m_param_panel;
    if (params_panel) {
        params_panel->get_top_panel()->Reparent(p->scrolled);
        auto spliter_1 = new ::StaticLine(p->scrolled);
        spliter_1->SetLineColour("#A6A9AA");
        scrolled_sizer->Add(spliter_1, 0, wxEXPAND);
        scrolled_sizer->Add(params_panel->get_top_panel(), 0, wxEXPAND);
        auto spliter_2 = new ::StaticLine(p->scrolled);
        spliter_2->SetLineColour("#CECECE");
        scrolled_sizer->Add(spliter_2, 0, wxEXPAND);
    }
    //add project content
    p->sizer_params = new wxBoxSizer(wxVERTICAL);
    p->m_object_list = new ObjectList(p->scrolled);
    p->sizer_params->Add(p->m_object_list, 1, wxEXPAND | wxTOP, 0);
    scrolled_sizer->Add(p->sizer_params, 2, wxEXPAND | wxLEFT, 0);
    p->m_object_list->Hide();
    // Frequently Object Settings
    p->object_settings = new ObjectSettings(p->scrolled);
#if !NEW_OBJECT_SETTING
    p->object_settings->Hide();
    p->sizer_params->Add(p->object_settings->get_sizer(), 0, wxEXPAND | wxTOP, 5 * em / 10);
#else
    if (params_panel) {
        params_panel->Reparent(p->scrolled);
        scrolled_sizer->Add(params_panel, 3, wxEXPAND);
    }
#endif
    }
    p->object_layers = new ObjectLayers(p->scrolled);
    p->object_layers->Hide();
    p->sizer_params->Add(p->object_layers->get_sizer(), 0, wxEXPAND | wxTOP, 0);
    auto *sizer = new wxBoxSizer(wxVERTICAL);
    sizer->Add(p->scrolled, 1, wxEXPAND);
    SetSizer(sizer);
}
References _L, ams_btn, Label::Body_10, Label::Body_14, connection_btn, Slic3r::GUI::dynamic_filament_list, Slic3r::GUI::PlaterPresetComboBox::edit_btn, Slic3r::flush_multiplier(), Slic3r::AppConfig::get(), Slic3r::ConfigDef::get(), WipingDialog::get_extruders(), WipingDialog::get_flush_multiplier(), WipingDialog::get_matrix(), Slic3r::GUI::Plater::get_next_color_for_filament(), Slic3r::ConfigOption::getFloat(), Slic3r::ConfigOptionFloat::getFloat(), StateColor::Hovered, int, LB_PROPAGATE_MOUSE_EVENT, m_bed_type_list, m_scrolled_sizer, StateColor::Normal, Slic3r::ConfigBase::option(), p, StateColor::Pressed, Slic3r::print_config_def, Slic3r::GUI::printer_config(), Slic3r::GUI::Choice::register_dynamic_list(), Slic3r::GUI::ConfigWizard::RR_USER, Slic3r::AppConfig::set(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::GUI::ConfigWizard::SP_FILAMENTS, Slic3r::GUI::ConfigWizard::SP_PRINTERS, Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), sync_ams_list(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, wxEVT_BUTTON, Slic3r::GUI::wxMouseEvent, and wxStaticText.
Sidebar() [2/3]
Slic3r::GUI::Sidebar::Sidebar (Sidebar &&) delete
Sidebar() [3/3]
Slic3r::GUI::Sidebar::Sidebar (const Sidebar &) delete
~Sidebar()
Slic3r::GUI::Sidebar::~Sidebar ()
{}
Member Function Documentation
change_top_border_for_mode_sizer()
void Slic3r::GUI::Sidebar::change_top_border_for_mode_sizer (bool increase_border)
{
    // BBS
#if 0
    if (p->mode_sizer) {
        p->mode_sizer->set_items_flag(increase_border ? wxTOP : 0);
        p->mode_sizer->set_items_border(increase_border ? int(0.5 * wxGetApp().em_unit()) : 0);
    }
#endif
}
References em_unit().
collapse()
void Slic3r::GUI::Sidebar::collapse (bool collapse)
{
    p->is_collapsed = collapse;
    this->Show(!collapse);
    p->plater->Layout();
    // save collapsing state to the AppConfig
    //if (wxGetApp().is_editor())
    //    wxGetApp().app_config->set_bool("collapsed_sidebar", collapse);
}
References collapse(), and p.
Referenced by collapse(), Slic3r::GUI::Plater::priv::collapse_sidebar(), and Slic3r::GUI::Plater::priv::set_current_panel().
combos_filament()
std::vector< PlaterPresetComboBox * > & Slic3r::GUI::Sidebar::combos_filament ()
{
    return p->combos_filament;
}
References p.
Referenced by Slic3r::GUI::Plater::priv::load_files().
enable_buttons()
void Slic3r::GUI::Sidebar::enable_buttons (bool enable)
{
#if 0
    p->btn_reslice->Enable(enable);
    p->btn_export_gcode->Enable(enable);
    p->btn_send_gcode->Enable(enable);
//    p->btn_eject_device->Enable(enable);
    p->btn_export_gcode_removable->Enable(enable);
#endif
}
filament_panel()
wxPanel * Slic3r::GUI::Sidebar::filament_panel ()
{
    return p->m_panel_filament_content;
}
Referenced by Slic3r::GUI::Plater::priv::on_select_preset().
finish_param_edit()
void Slic3r::GUI::Sidebar::finish_param_edit ()
{ p->editing_filament = -1; }
References p.
get_eject_shown()
bool Slic3r::GUI::Sidebar::get_eject_shown () const
get_search_line()
std::string & Slic3r::GUI::Sidebar::get_search_line ()
{
    return p->searcher.search_string();
}
References p.
get_searcher()
Search::OptionsSearcher & Slic3r::GUI::Sidebar::get_searcher ()
{
    return p->searcher;
}
References p.
get_wiping_dialog_button()
wxButton * Slic3r::GUI::Sidebar::get_wiping_dialog_button ()
{
#if 0
    return p->frequently_changed_parameters->get_wiping_dialog_button();
#endif
    return NULL;
}
References NULL, and wxButton.
init_filament_combo()
void Slic3r::GUI::Sidebar::init_filament_combo (PlaterPresetComboBox ** combo, const int filament_idx)
{
    *combo = new PlaterPresetComboBox(p->m_panel_filament_content, Slic3r::Preset::TYPE_FILAMENT);
    (*combo)->set_filament_idx(filament_idx);
    auto combo_and_btn_sizer = new wxBoxSizer(wxHORIZONTAL);
    // BBS:  filament double columns
    int em = wxGetApp().em_unit();
    combo_and_btn_sizer->Add(FromDIP(8), 0, 0, 0, 0 );
    (*combo)->clr_picker->SetLabel(wxString::Format("%d", filament_idx + 1));
    combo_and_btn_sizer->Add((*combo)->clr_picker, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, FromDIP(3));
    combo_and_btn_sizer->Add(*combo, 1, wxALL | wxEXPAND, FromDIP(2))->SetMinSize({-1, FromDIP(30)});
    /* BBS hide del_btn
    ScalableButton* del_btn = new ScalableButton(p->m_panel_filament_content, wxID_ANY, "delete_filament");
    del_btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e){
        int extruder_count = std::max(1, (int)p->combos_filament.size() - 1);
        update_objects_list_filament_column(std::max(1, extruder_count - 1));
        on_filaments_change(extruder_count);
        wxGetApp().preset_bundle->printers.get_edited_preset().set_num_extruders(extruder_count);
        wxGetApp().preset_bundle->update_multi_material_filament_presets();
    });
    combo_and_btn_sizer->Add(32 * em / 10, 0, 0, 0, 0);
    combo_and_btn_sizer->Add(del_btn, 0, wxALIGN_CENTER_VERTICAL, 5 * em / 10);
    */
    ScalableButton* edit_btn = new ScalableButton(p->m_panel_filament_content, wxID_ANY, "edit");
    edit_btn->SetToolTip(_L("Click to edit preset"));
    PlaterPresetComboBox* combobox = (*combo);
    edit_btn->Bind(wxEVT_BUTTON, [this, combobox, filament_idx](wxCommandEvent)
        {
            p->editing_filament = -1;
            if (combobox->switch_to_tab())
                p->editing_filament = filament_idx; // sync with TabPresetComboxBox's m_filament_idx
        });
    combobox->edit_btn = edit_btn;
    combo_and_btn_sizer->Add(edit_btn, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, FromDIP(3));
    combo_and_btn_sizer->Add(FromDIP(8), 0, 0, 0, 0);
    // BBS:  filament double columns
    auto side = filament_idx % 2;
    auto /***/sizer_filaments = this->p->sizer_filaments->GetItem(side)->GetSizer();
    if (side == 1 && filament_idx > 1) sizer_filaments->Remove(filament_idx / 2);
    sizer_filaments->Add(combo_and_btn_sizer, 1, wxEXPAND);
    if (side == 0) {
        sizer_filaments = this->p->sizer_filaments->GetItem(1)->GetSizer();
        sizer_filaments->AddStretchSpacer(1);
    }
}
References _L, Slic3r::GUI::PlaterPresetComboBox::edit_btn, Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), Slic3r::Preset::TYPE_FILAMENT, and wxEVT_BUTTON.
is_collapsed()
bool Slic3r::GUI::Sidebar::is_collapsed ()
{ return p->is_collapsed; }
References p.
Referenced by Slic3r::GUI::Plater::priv::is_sidebar_collapsed().
is_multifilament()
bool Slic3r::GUI::Sidebar::is_multifilament ()
{
    return p->combos_filament.size() > 1;
}
Referenced by Slic3r::GUI::Plater::priv::on_select_preset().
jump_to_option() [1/2]
void Slic3r::GUI::Sidebar::jump_to_option (const std::string & opt_key, Preset::Type type, const std::wstring & category)
{
    //const Search::Option& opt = p->searcher.get_option(opt_key, type);
    if (type == Preset::TYPE_PRINT) {
        auto tab = dynamic_cast<TabPrintModel*>(wxGetApp().params_panel()->get_current_tab());
        if (tab && tab->has_key(opt_key)) {
            tab->activate_option(opt_key, category);
            return;
        }
        wxGetApp().params_panel()->switch_to_global();
    }
    wxGetApp().get_tab(type)->activate_option(opt_key, category);
}
References Slic3r::GUI::Tab::activate_option(), and Slic3r::Preset::TYPE_PRINT.
jump_to_option() [2/2]
void Slic3r::GUI::Sidebar::jump_to_option (size_t selected)
{
    const Search::Option& opt = p->searcher.get_option(selected);
    jump_to_option(opt.opt_key(), opt.type, opt.category);
    // Switch to the Settings NotePad
//    wxGetApp().mainframe->select_tab();
}
References Slic3r::Search::Option::category, Slic3r::Search::Option::opt_key(), and Slic3r::Search::Option::type.
load_ams_list()
void Slic3r::GUI::Sidebar::load_ams_list (std::string const & device, std::map< std::string, Ams * > const & list)
{
    std::vector<DynamicPrintConfig> filament_ams_list;
    for (auto ams : list) {
        char n = ams.first.front() - '0' + 'A';
        for (auto tray : ams.second->trayList) {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__
                                    << boost::format(": ams %1% tray %2% id %3% color %4%") % ams.first % tray.first % tray.second->setting_id % tray.second->color;
            char t = tray.first.front() - '0' + '1';
            DynamicPrintConfig ams;
            ams.set_key_value("filament_id", new ConfigOptionStrings{tray.second->setting_id});
            ams.set_key_value("filament_type", new ConfigOptionStrings{tray.second->type});
            ams.set_key_value("tray_name", new ConfigOptionStrings{std::string(1, n) + std::string(1, t)});
            ams.set_key_value("filament_colour", new ConfigOptionStrings{"#" + tray.second->color.substr(0, 6)});
            filament_ams_list.emplace_back(std::move(ams));
        }
    }
    p->ams_list_device = device;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": %1% items") % filament_ams_list.size();
    wxGetApp().preset_bundle->filament_ams_list = filament_ams_list;
    for (auto c : p->combos_filament)
        c->update();
}
References n, Slic3r::DynamicConfig::set_key_value(), and Slic3r::ConfigOptionStrings::type().
msw_rescale()
void Slic3r::GUI::Sidebar::msw_rescale ()
{
    SetMinSize(wxSize(42 * wxGetApp().em_unit(), -1));
    p->m_panel_printer_title->GetSizer()->SetMinSize(-1, 3 * wxGetApp().em_unit());
    p->m_panel_filament_title->GetSizer()
        ->SetMinSize(-1, 3 * wxGetApp().em_unit());
    p->m_printer_icon->msw_rescale();
    p->m_printer_setting->msw_rescale();
    p->m_filament_icon->msw_rescale();
    p->m_bpButton_add_filament->msw_rescale();
    p->m_bpButton_del_filament->msw_rescale();
    p->m_bpButton_ams_filament->msw_rescale();
    p->m_bpButton_set_filament->msw_rescale();
    p->m_flushing_volume_btn->Rescale();
    //BBS
    m_bed_type_list->Rescale();
    m_bed_type_list->SetMinSize({-1, 3 * wxGetApp().em_unit()});
#if 0
    if (p->mode_sizer)
        p->mode_sizer->msw_rescale();
#endif
    //for (PlaterPresetComboBox* combo : std::vector<PlaterPresetComboBox*> { p->combo_print,
    //                                                            //p->combo_sla_print,
    //                                                            //p->combo_sla_material,
    //                                                            //p->combo_printer
    //                                                            } )
    //    combo->msw_rescale();
    p->combo_printer->msw_rescale();
    for (PlaterPresetComboBox* combo : p->combos_filament)
        combo->msw_rescale();
    // BBS
    //p->frequently_changed_parameters->msw_rescale();
    //obj_list()->msw_rescale();
    // BBS TODO: add msw_rescale for newly added windows
    // BBS
    //p->object_manipulation->msw_rescale();
    p->object_settings->msw_rescale();
    // BBS
#if 0
    p->object_info->msw_rescale();
    p->btn_send_gcode->msw_rescale();
//    p->btn_eject_device->msw_rescale();
    p->btn_export_gcode_removable->msw_rescale();
#ifdef _WIN32
    const int scaled_height = p->btn_export_gcode_removable->GetBitmapHeight();
#else
    const int scaled_height = p->btn_export_gcode_removable->GetBitmapHeight() + 4;
#endif
    p->btn_export_gcode->SetMinSize(wxSize(-1, scaled_height));
    p->btn_reslice     ->SetMinSize(wxSize(-1, scaled_height));
#endif
    p->scrolled->Layout();
    p->searcher.dlg_msw_rescale();
}
References em_unit().
obj_layers()
ObjectLayers * Slic3r::GUI::Sidebar::obj_layers ()
{
    return p->object_layers;
}
Referenced by Slic3r::GUI::GUI_App::obj_layers().
obj_list()
ObjectList * Slic3r::GUI::Sidebar::obj_list ()
{
    // BBS
    //return obj_list();
    return p->m_object_list;
}
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::Plater::priv::can_decrease_instances(), Slic3r::GUI::Plater::priv::can_fix_through_netfabb(), Slic3r::GUI::Plater::priv::can_increase_instances(), Slic3r::GUI::Plater::priv::can_mirror(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::Plater::priv::can_replace_with_stl(), Slic3r::GUI::Plater::priv::can_split(), Slic3r::GUI::Plater::decrease_instances(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::ObjectList::fix_through_netfabb(), Slic3r::GUI::Plater::increase_instances(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::GUI_App::obj_list(), Slic3r::GUI::Plater::on_filaments_change(), Slic3r::GUI::Plater::priv::on_plate_selected(), Slic3r::GUI::GUI_App::recreate_GUI(), Slic3r::GUI::Plater::priv::remove(), Slic3r::GUI::Plater::priv::remove_curr_plate_all(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::reset(), Slic3r::GUI::Plater::priv::select_all(), Slic3r::GUI::Plater::priv::select_curr_plate_all(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::Plater::priv::undo_redo_to(), and update_mode().
obj_settings()
ObjectSettings * Slic3r::GUI::Sidebar::obj_settings ()
{
    return p->object_settings;
}
Referenced by Slic3r::GUI::GUI_App::obj_settings(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::update_settings_item_and_selection().
og_freq_chng_params()
ConfigOptionsGroup * Slic3r::GUI::Sidebar::og_freq_chng_params (const bool is_fff)
{
    // BBS
#if 0
    return p->frequently_changed_parameters->get_og(is_fff);
#endif
    return NULL;
}
References NULL.
on_bed_type_change()
void Slic3r::GUI::Sidebar::on_bed_type_change (BedType bed_type)
{
    // btDefault option is not included in global bed type setting
    int sel_idx = (int)bed_type - 1;
    if (m_bed_type_list != nullptr)
        m_bed_type_list->SetSelection(sel_idx);
}
References int.
Referenced by Slic3r::GUI::Plater::on_bed_type_change().
on_filaments_change()
void Slic3r::GUI::Sidebar::on_filaments_change (size_t num_filaments)
{
    auto& choices = combos_filament();
    if (num_filaments == choices.size())
        return;
    if (choices.size() == 1 || num_filaments == 1)
        choices[0]->GetDropDown().Invalidate();
    wxWindowUpdateLocker noUpdates_scrolled_panel(this);
    size_t i = choices.size();
    while (i < num_filaments)
    {
        PlaterPresetComboBox* choice/*{ nullptr }*/;
        init_filament_combo(&choice, i);
        choices.push_back(choice);
        // initialize selection
        choice->update();
        ++i;
    }
    // remove unused choices if any
    remove_unused_filament_combos(num_filaments);
    auto sizer = p->m_panel_filament_title->GetSizer();
    if (p->m_flushing_volume_btn != nullptr && sizer != nullptr) {
        if (num_filaments > 1)
            sizer->Show(p->m_flushing_volume_btn);
        else
            sizer->Hide(p->m_flushing_volume_btn);
    }
    Layout();
    p->m_panel_filament_title->Refresh();
    update_ui_from_settings();
    dynamic_filament_list.update();
}
References Slic3r::GUI::dynamic_filament_list, Slic3r::GUI::PlaterPresetComboBox::update(), and Slic3r::GUI::DynamicFilamentList::update().
Referenced by Slic3r::GUI::Plater::on_filaments_change().
operator=() [1/2]
Sidebar & Slic3r::GUI::Sidebar::operator= (const Sidebar &) delete
References wxButton.
operator=() [2/2]
Sidebar & Slic3r::GUI::Sidebar::operator= (Sidebar &&) delete
print_panel()
wxPanel * Slic3r::GUI::Sidebar::print_panel ()
{
    return p->m_panel_print_content;
}
remove_unused_filament_combos()
void Slic3r::GUI::Sidebar::remove_unused_filament_combos (const size_t current_extruder_count)
{
    if (current_extruder_count >= p->combos_filament.size())
        return;
    while (p->combos_filament.size() > current_extruder_count) {
        const int last = p->combos_filament.size() - 1;
        auto sizer_filaments = this->p->sizer_filaments->GetItem(last % 2)->GetSizer();
        sizer_filaments->Remove(last / 2);
        (*p->combos_filament[last]).Destroy();
        p->combos_filament.pop_back();
    }
    // BBS:  filament double columns
    auto sizer_filaments0 = this->p->sizer_filaments->GetItem((size_t)0)->GetSizer();
    auto sizer_filaments1 = this->p->sizer_filaments->GetItem(1)->GetSizer();
    if (current_extruder_count < 2) {
        sizer_filaments1->Clear();
    } else {
        size_t c0 = sizer_filaments0->GetChildren().GetCount();
        size_t c1 = sizer_filaments1->GetChildren().GetCount();
        if (c0 < c1)
            sizer_filaments1->Remove(c1 - 1);
        else if (c0 > c1)
            sizer_filaments1->AddStretchSpacer(1);
    }
}
scrolled_panel()
wxPanel * Slic3r::GUI::Sidebar::scrolled_panel ()
{
    return p->scrolled;
}
search()
void Slic3r::GUI::Sidebar::search ()
{
    p->searcher.search();
}
set_btn_label()
void Slic3r::GUI::Sidebar::set_btn_label (const ActionButtonType btn_type, const wxString & label) const
{
    switch (btn_type)
    {
        case ActionButtonType::abReslice:   p->btn_reslice->SetLabelText(label);        break;
        case ActionButtonType::abExport:    p->btn_export_gcode->SetLabelText(label);   break;
        case ActionButtonType::abSendGCode: /*p->btn_send_gcode->SetLabelText(label);*/     break;
    }
}
References Slic3r::GUI::abExport, Slic3r::GUI::abReslice, Slic3r::GUI::abSendGCode, and Slic3r::GUI::Plater::p.
Referenced by Slic3r::GUI::Plater::priv::on_process_completed().
show_eject()
bool Slic3r::GUI::Sidebar::show_eject (bool show) const
show_export()
bool Slic3r::GUI::Sidebar::show_export (bool show) const
{ return p->btn_export_gcode->Show(show); }
show_export_removable()
bool Slic3r::GUI::Sidebar::show_export_removable (bool show) const
{ return p->btn_export_gcode_removable->Show(show); }
show_mode_sizer()
void Slic3r::GUI::Sidebar::show_mode_sizer (bool show)
{
    //p->mode_sizer->Show(show);
}
show_object_list()
bool Slic3r::GUI::Sidebar::show_object_list (bool show) const
{
    if (!p->m_object_list->Show(show))
        return false;
    if (!show)
        p->object_layers->Show(false);
    else
        p->m_object_list->part_selection_changed();
    p->scrolled->Layout();
    return true;
}
References p.
show_reslice()
bool Slic3r::GUI::Sidebar::show_reslice (bool show) const
{ return p->btn_reslice->Show(show); }
show_send()
bool Slic3r::GUI::Sidebar::show_send (bool show) const
{ return p->btn_send_gcode->Show(show); }
sync_ams_list()
void Slic3r::GUI::Sidebar::sync_ams_list ()
{
    auto & list = wxGetApp().preset_bundle->filament_ams_list;
    if (list.empty()) {
        MessageDialog dlg(this,
            _L("No AMS filaments. Please select a printer in 'Device' page to load AMS info."),
            _L("Sync filaments with AMS"), wxOK);
        dlg.ShowModal();
        return;
    }
    std::string ams_filament_ids = wxGetApp().app_config->get("ams_filament_ids", p->ams_list_device);
    std::vector<std::string> list2;
    if (!ams_filament_ids.empty())
        boost::algorithm::split(list2, ams_filament_ids, boost::algorithm::is_any_of(","));
    struct SyncAmsDialog : MessageDialog {
        SyncAmsDialog(wxWindow * parent, bool first): MessageDialog(parent,
            first
                ? _L("Sync filaments with AMS will drop all current selected filament presets and colors. Do you want to continue?")
                : _L("Already did a synchronization, do you want to sync only changes or resync all?"),
            _L("Sync filaments with AMS"), 0)
        {
            if (first) {
                add_button(wxID_YES, true, _L("Yes"));
            } else {
                add_button(wxID_OK, true, _L("Sync"));
                add_button(wxID_YES, false, _L("Resync"));
            }
            add_button(wxID_CANCEL, false, _L("Cancel"));
        }
    } dlg(this, ams_filament_ids.empty());
    auto res = dlg.ShowModal();
    if (res == wxID_CANCEL) return;
    list2.resize(list.size());
    for (int i = 0; i < list.size(); ++i) {
        auto filament_id = list[i].opt_string("filament_id", 0u);
        list[i].set_key_value("filament_changed", new ConfigOptionBool{res == wxID_YES || list2[i] != filament_id});
        list2[i] = filament_id;
    }
    unsigned int unknowns = 0;
    auto n = wxGetApp().preset_bundle->sync_ams_list(unknowns);
    if (n == 0) {
        MessageDialog dlg(this,
            _L("There are no compatible filaments, and sync is not performed."),
            _L("Sync filaments with AMS"), wxOK);
        dlg.ShowModal();
        return;
    }
    ams_filament_ids = boost::algorithm::join(list2, ",");
    wxGetApp().app_config ->set("ams_filament_ids", p->ams_list_device, ams_filament_ids);
    if (unknowns > 0) {
        MessageDialog dlg(this,
            _L("There are some unknown filaments mapped to generic preset. Please update Orca Slicer or restart Orca Slicer to check if there is an update to system presets."),
            _L("Sync filaments with AMS"), wxOK);
        dlg.ShowModal();
    }
    wxGetApp().plater()->on_filaments_change(n);
    for (auto &c : p->combos_filament)
        c->update();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->select_preset(wxGetApp().preset_bundle->filament_presets[0]);
    wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
    dynamic_filament_list.update();
    // Expand filament list
    p->m_panel_filament_content->SetMaxSize({-1, -1});
    Layout();
}
References _L, Slic3r::GUI::dynamic_filament_list, n, Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::Preset::TYPE_FILAMENT, and Slic3r::GUI::DynamicFilamentList::update().
Referenced by Sidebar().
sys_color_changed()
void Slic3r::GUI::Sidebar::sys_color_changed ()
{
    wxWindowUpdateLocker noUpdates(this);
#if 0
    for (wxWindow* win : std::vector<wxWindow*>{ this, p->sliced_info->GetStaticBox(), p->object_info->GetStaticBox(), p->btn_reslice, p->btn_export_gcode })
        wxGetApp().UpdateDarkUI(win);
    p->object_info->msw_rescale();
    for (wxWindow* win : std::vector<wxWindow*>{ p->scrolled, p->presets_panel })
        wxGetApp().UpdateAllStaticTextDarkUI(win);
#endif
    //for (wxWindow* btn : std::vector<wxWindow*>{ p->btn_reslice, p->btn_export_gcode })
    //    wxGetApp().UpdateDarkUI(btn, true);
    p->m_printer_icon->msw_rescale();
    p->m_printer_setting->msw_rescale();
    p->m_filament_icon->msw_rescale();
    p->m_bpButton_add_filament->msw_rescale();
    p->m_bpButton_del_filament->msw_rescale();
    p->m_bpButton_ams_filament->msw_rescale();
    p->m_bpButton_set_filament->msw_rescale();
    p->m_flushing_volume_btn->Rescale();
    // BBS
#if 0
    if (p->mode_sizer)
        p->mode_sizer->msw_rescale();
    p->frequently_changed_parameters->sys_color_changed();
#endif
    p->object_settings->sys_color_changed();
    //BBS: remove print related combos
#if 0
    for (PlaterPresetComboBox* combo : std::vector<PlaterPresetComboBox*>{  p->combo_print,
                                                                p->combo_sla_print,
                                                                p->combo_sla_material,
                                                                p->combo_printer })
        combo->sys_color_changed();
#endif
    for (PlaterPresetComboBox* combo : p->combos_filament)
        combo->sys_color_changed();
    // BBS
    obj_list()->sys_color_changed();
    obj_layers()->sys_color_changed();
    // BBS
    //p->object_manipulation->sys_color_changed();
    // btn...->msw_rescale() updates icon on button, so use it
    //p->btn_send_gcode->msw_rescale();
//    p->btn_eject_device->msw_rescale();
    //p->btn_export_gcode_removable->msw_rescale();
    p->scrolled->Layout();
    p->searcher.dlg_sys_color_changed();
}
References Slic3r::GUI::obj_list(), and Slic3r::GUI::ObjectList::sys_color_changed().
update_all_preset_comboboxes()
void Slic3r::GUI::Sidebar::update_all_preset_comboboxes ()
{
    PresetBundle &preset_bundle = *wxGetApp().preset_bundle;
    const auto print_tech = preset_bundle.printers.get_edited_preset().printer_technology();
    bool is_bbl_preset = preset_bundle.printers.get_edited_preset().has_lidar(&preset_bundle);
    auto p_mainframe = wxGetApp().mainframe;
    p_mainframe->show_device(is_bbl_preset);
    if (is_bbl_preset) {
        //only show connection button for not-BBL printer
        connection_btn->Hide();
        //only show sync-ams button for BBL printer
        ams_btn->Show();
        //update print button default value for bbl or third-party printer
        p_mainframe->set_print_button_to_default(MainFrame::PrintSelectType::ePrintPlate);
        m_bed_type_list->Enable();
        auto str_bed_type = wxGetApp().app_config->get_printer_setting(wxGetApp().preset_bundle->printers.get_selected_preset_name(), "curr_bed_type");
        if(!str_bed_type.empty()){
            int bed_type_value = atoi(str_bed_type.c_str());
            if(bed_type_value == 0)
                bed_type_value = 1;
            m_bed_type_list->SelectAndNotify(bed_type_value - 1);
        }
    } else {
        connection_btn->Show();
        ams_btn->Hide();
        p_mainframe->set_print_button_to_default(MainFrame::PrintSelectType::eSendGcode);
        auto cfg = preset_bundle.printers.get_edited_preset().config;
        wxString url = cfg.opt_string("print_host_webui").empty() ? cfg.opt_string("print_host") : cfg.opt_string("print_host_webui");
        if(!url.empty())
        {
            if(!url.Lower().starts_with("http"))
                url = wxString::Format("http://%s",url);
            p_mainframe->load_printer_url(url);
        }
        m_bed_type_list->SelectAndNotify(btPEI-1);
        m_bed_type_list->Disable();
    }
    // Update the print choosers to only contain the compatible presets, update the dirty flags.
    //BBS
    // Update the printer choosers, update the dirty flags.
    //p->combo_printer->update();
    // Update the filament choosers to only contain the compatible presets, update the color preview,
    // update the dirty flags.
    if (print_tech == ptFFF) {
        for (PlaterPresetComboBox* cb : p->combos_filament)
            cb->update();
    }
    if (p->combo_printer)
        p->combo_printer->update();
    p_mainframe->m_tabpanel->SetSelection(p_mainframe->m_tabpanel->GetSelection());
}
References Slic3r::btPEI, Slic3r::Preset::config, Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::Preset::has_lidar(), Slic3r::DynamicConfig::opt_string(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and Slic3r::ptFFF.
update_mode()
void Slic3r::GUI::Sidebar::update_mode ()
{
    m_mode = wxGetApp().get_mode();
    //BBS: remove print related combos
    update_searcher();
    wxWindowUpdateLocker noUpdates(this);
    // BBS
    //obj_list()->get_sizer()->Show(m_mode > comSimple);
    obj_list()->unselect_objects();
    obj_list()->update_selections();
//    obj_list()->update_object_menu();
    Layout();
}
References m_mode, obj_list(), Slic3r::GUI::ObjectList::unselect_objects(), update_searcher(), and Slic3r::GUI::ObjectList::update_selections().
Referenced by Slic3r::GUI::GUI_App::update_mode().
update_presets()
void Slic3r::GUI::Sidebar::update_presets (Slic3r::Preset::Type preset_type)
{
    PresetBundle &preset_bundle = *wxGetApp().preset_bundle;
    const auto print_tech = preset_bundle.printers.get_edited_preset().printer_technology();
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": enter, preset_type %1%")%preset_type;
    switch (preset_type) {
    case Preset::TYPE_FILAMENT:
    {
        // BBS
#if 0
        const size_t extruder_cnt = print_tech != ptFFF ? 1 :
                                dynamic_cast<ConfigOptionFloats*>(preset_bundle.printers.get_edited_preset().config.option("nozzle_diameter"))->values.size();
        const size_t filament_cnt = p->combos_filament.size() > extruder_cnt ? extruder_cnt : p->combos_filament.size();
#else
        const size_t filament_cnt = p->combos_filament.size();
#endif
        const std::string &name = preset_bundle.filaments.get_selected_preset_name();
        if (p->editing_filament >= 0) {
            preset_bundle.set_filament_preset(p->editing_filament, name);
        } else if (filament_cnt == 1) {
            // Single filament printer, synchronize the filament presets.
            preset_bundle.set_filament_preset(0, name);
        }
        for (size_t i = 0; i < filament_cnt; i++)
            p->combos_filament[i]->update();
        dynamic_filament_list.update();
        break;
    }
    case Preset::TYPE_PRINT:
        //wxGetApp().mainframe->m_param_panel;
        //p->combo_print->update();
        {
        Tab* print_tab = wxGetApp().get_tab(Preset::TYPE_PRINT);
        if (print_tab) {
            print_tab->get_combo_box()->update();
        }
        break;
        }
    case Preset::TYPE_SLA_PRINT:
        ;// p->combo_sla_print->update();
        break;
    case Preset::TYPE_SLA_MATERIAL:
        ;// p->combo_sla_material->update();
        break;
    case Preset::TYPE_PRINTER:
    {
        update_all_preset_comboboxes();
        p->show_preset_comboboxes();
        /* update bed shape */
        Tab* printer_tab = wxGetApp().get_tab(Preset::TYPE_PRINTER);
        if (printer_tab) {
            printer_tab->update();
        }
        break;
    }
    default: break;
    }
    // Synchronize config.ini with the current selections.
    wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": exit.");
}
References Slic3r::Preset::config, Slic3r::GUI::dynamic_filament_list, Slic3r::PresetBundle::filaments, Slic3r::GUI::Tab::get_combo_box(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::ConfigBase::option(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptFFF, Slic3r::PresetBundle::set_filament_preset(), Slic3r::ConfigOptionVector< T >::size(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::Preset::TYPE_SLA_PRINT, Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::Tab::update(), and Slic3r::GUI::DynamicFilamentList::update().
update_presets_from_to()
void Slic3r::GUI::Sidebar::update_presets_from_to (Slic3r::Preset::Type preset_type, std::string from, std::string to)
{
    PresetBundle &preset_bundle = *wxGetApp().preset_bundle;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": enter, preset_type %1%, from %2% to %3%")%preset_type %from %to;
    switch (preset_type) {
    case Preset::TYPE_FILAMENT:
    {
        const size_t filament_cnt = p->combos_filament.size();
        for (auto it = preset_bundle.filament_presets.begin(); it != preset_bundle.filament_presets.end(); it++)
        {
            if ((*it).compare(from) == 0) {
                (*it) = to;
            }
        }
        for (size_t i = 0; i < filament_cnt; i++)
            p->combos_filament[i]->update();
        break;
    }
    default: break;
    }
    // Synchronize config.ini with the current selections.
    wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": exit!");
}
References Slic3r::PresetBundle::filament_presets, and Slic3r::Preset::TYPE_FILAMENT.
update_searcher()
void Slic3r::GUI::Sidebar::update_searcher ()
{
    p->searcher.init(get_search_inputs(m_mode));
}
References Slic3r::GUI::get_search_inputs(), m_mode, and p.
Referenced by update_mode().
update_ui_from_settings()
void Slic3r::GUI::Sidebar::update_ui_from_settings ()
{
    // BBS
    //p->object_manipulation->update_ui_from_settings();
    // update Cut gizmo, if it's open
    p->plater->canvas3D()->update_gizmos_on_off_state();
    p->plater->set_current_canvas_as_dirty();
    p->plater->get_current_canvas3D()->request_extra_frame();
#if 0
    p->object_list->apply_volumes_order();
#endif
}
References p.
Referenced by Slic3r::GUI::Plater::priv::update_ui_from_settings().
Member Data Documentation
ams_btn
ScalableButton* Slic3r::GUI::Sidebar::ams_btn = nullptr private
Referenced by Sidebar().
connection_btn
ScalableButton* Slic3r::GUI::Sidebar::connection_btn = nullptr private
Referenced by Sidebar().
m_bed_type_list
ComboBox* Slic3r::GUI::Sidebar::m_bed_type_list = nullptr private
Referenced by Sidebar().
m_mode
ConfigOptionMode Slic3r::GUI::Sidebar::m_mode private
Referenced by update_mode(), and update_searcher().
m_scrolled_sizer
wxBoxSizer* Slic3r::GUI::Sidebar::m_scrolled_sizer = nullptr private
Referenced by Sidebar().
p
std::unique_ptr<priv> Slic3r::GUI::Sidebar::p private
Referenced by Sidebar(), collapse(), combos_filament(), finish_param_edit(), get_search_line(), get_searcher(), is_collapsed(), show_object_list(), update_searcher(), and update_ui_from_settings().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Plater.hpp
src/slic3r/GUI/Plater.cpp