OrcaSlicer: Slic3r::GUI::CommonGizmosDataObjects::InstancesHider Class Reference
Slic3r::GUI::CommonGizmosDataObjects::InstancesHider Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
InstancesHider (CommonGizmosDataPool *cgdp)
CommonGizmosDataID get_dependencies () const override
void show_supports (bool show)
bool are_supports_shown () const
void render_cut () const
void update ()
void release ()
bool is_valid () const
Protected Member Functions
void on_update () override
void on_release () override
CommonGizmosDataPool * get_pool () const
Private Attributes
bool m_show_supports = false
std::vector< const TriangleMesh * > m_old_meshes
std::vector< std::unique_ptr< MeshClipper > > m_clippers
bool m_is_valid = false
CommonGizmosDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
InstancesHider()
Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::InstancesHider (CommonGizmosDataPool * cgdp) inline explicit
        : CommonGizmosDataBase(cgdp) {}
Member Function Documentation
are_supports_shown()
bool Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::are_supports_shown () const inline
{ return m_show_supports; }
References m_show_supports.
Referenced by Slic3r::GUI::GLGizmoHollow::on_render_input_window().
get_dependencies()
CommonGizmosDataID Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::get_dependencies () const inline override virtual
Reimplemented from Slic3r::GUI::CommonGizmosDataBase.
{ return CommonGizmosDataID::SelectionInfo; }
References Slic3r::GUI::SelectionInfo.
get_pool()
CommonGizmosDataPool * Slic3r::GUI::CommonGizmosDataBase::get_pool () const inline protected inherited
{ return m_common; }
References Slic3r::GUI::CommonGizmosDataBase::m_common.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), on_release(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), on_update(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position(), and Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_range_and_pos().
is_valid()
bool Slic3r::GUI::CommonGizmosDataBase::is_valid () const inline inherited
{ return m_is_valid; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid.
Referenced by Slic3r::GUI::CommonGizmosDataPool::hollowed_mesh(), Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), render_cut(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
on_release()
void Slic3r::GUI::InstancesHider::on_release () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    get_pool()->get_canvas()->toggle_model_objects_visibility(true);
    get_pool()->get_canvas()->set_use_clipping_planes(false);
    m_old_meshes.clear();
    m_clippers.clear();
}
References Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), m_clippers, m_old_meshes, Slic3r::GUI::GLCanvas3D::set_use_clipping_planes(), and Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility().
on_update()
void Slic3r::GUI::InstancesHider::on_update () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    const ModelObject* mo = get_pool()->selection_info()->model_object();
    int active_inst = get_pool()->selection_info()->get_active_instance();
    GLCanvas3D* canvas = get_pool()->get_canvas();
    double z_min;
    if (canvas->get_canvas_type() == GLCanvas3D::CanvasAssembleView)
        z_min = std::numeric_limits<double>::max();
    else
        z_min = -SINKING_Z_THRESHOLD;
    if (mo && active_inst != -1) {
        canvas->toggle_model_objects_visibility(false);
        canvas->toggle_model_objects_visibility(true, mo, active_inst);
        canvas->toggle_sla_auxiliaries_visibility(m_show_supports, mo, active_inst);
        canvas->set_use_clipping_planes(true);
        // Some objects may be sinking, do not show whatever is below the bed.
        canvas->set_clipping_plane(0, ClippingPlane(Vec3d::UnitZ(), z_min));
        canvas->set_clipping_plane(1, ClippingPlane(-Vec3d::UnitZ(), std::numeric_limits<double>::max()));
        std::vector<const TriangleMesh*> meshes;
        for (const ModelVolume* mv : mo->volumes)
            meshes.push_back(&mv->mesh());
        if (meshes != m_old_meshes) {
            m_clippers.clear();
            for (const TriangleMesh* mesh : meshes) {
                m_clippers.emplace_back(new MeshClipper);
                m_clippers.back()->set_plane(ClippingPlane(-Vec3d::UnitZ(), z_min));
                m_clippers.back()->set_mesh(*mesh);
            }
            m_old_meshes = meshes;
        }
    }
    else
        canvas->toggle_model_objects_visibility(true);
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), m_clippers, m_old_meshes, m_show_supports, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLCanvas3D::set_clipping_plane(), Slic3r::GUI::GLCanvas3D::set_use_clipping_planes(), Slic3r::SINKING_Z_THRESHOLD, Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility(), Slic3r::GUI::GLCanvas3D::toggle_sla_auxiliaries_visibility(), and Slic3r::ModelObject::volumes.
Referenced by show_supports().
release()
void Slic3r::GUI::CommonGizmosDataBase::release () inline inherited
{ on_release(); m_is_valid = false; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_release().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_set_state().
render_cut()
void Slic3r::GUI::InstancesHider::render_cut () const
{
    const SelectionInfo* sel_info = get_pool()->selection_info();
    const ModelObject* mo = sel_info->model_object();
    Geometry::Transformation inst_trafo = mo->instances[sel_info->get_active_instance()]->get_transformation();
    size_t clipper_id = 0;
    for (const ModelVolume* mv : mo->volumes) {
        Geometry::Transformation vol_trafo  = mv->get_transformation();
        Geometry::Transformation trafo = inst_trafo * vol_trafo;
        trafo.set_offset(trafo.get_offset() + Vec3d(0., 0., sel_info->get_sla_shift()));
        auto& clipper = m_clippers[clipper_id];
        clipper->set_transformation(trafo);
        const ObjectClipper* obj_clipper = get_pool()->object_clipper();
        if (obj_clipper->is_valid() && obj_clipper->get_clipping_plane()
         && obj_clipper->get_position() != 0.) {
            ClippingPlane clp = *get_pool()->object_clipper()->get_clipping_plane();
            clp.set_normal(-clp.get_normal());
            clipper->set_limiting_plane(clp);
        } else
            clipper->set_limiting_plane(ClippingPlane::ClipsNothing());
        glsafe(::glPushMatrix());
        if (mv->is_model_part())
            glsafe(::glColor3f(0.8f, 0.3f, 0.0f));
        else {
            const std::array<float, 4>& c = color_from_model_volume(*mv);
            glsafe(::glColor4f(c[0], c[1], c[2], c[3]));
        }
        glsafe(::glPushAttrib(GL_DEPTH_TEST));
        glsafe(::glDisable(GL_DEPTH_TEST));
        clipper->render_cut();
        glsafe(::glPopAttrib());
        glsafe(::glPopMatrix());
        ++clipper_id;
    }
}
References Slic3r::GUI::ClippingPlane::ClipsNothing(), Slic3r::color_from_model_volume(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::ClippingPlane::get_normal(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), glsafe, Slic3r::ModelObject::instances, Slic3r::GUI::CommonGizmosDataBase::is_valid(), m_clippers, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::ClippingPlane::set_normal(), Slic3r::Geometry::Transformation::set_offset(), and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), and Slic3r::GUI::GLGizmoSeam::render_painter_gizmo().
show_supports()
void Slic3r::GUI::InstancesHider::show_supports (bool show)
{
    if (m_show_supports != show) {
        m_show_supports = show;
        on_update();
    }
}
References m_show_supports, and on_update().
Referenced by Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), and Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode().
update()
void Slic3r::GUI::CommonGizmosDataBase::update () inline inherited
{ on_update(); m_is_valid = true; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_update().
Member Data Documentation
m_clippers
std::vector<std::unique_ptr<MeshClipper> > Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::m_clippers private
Referenced by on_release(), on_update(), and render_cut().
m_common
CommonGizmosDataPool* Slic3r::GUI::CommonGizmosDataBase::m_common = nullptr private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::get_pool().
m_is_valid
bool Slic3r::GUI::CommonGizmosDataBase::m_is_valid = false private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::is_valid(), Slic3r::GUI::CommonGizmosDataBase::release(), and Slic3r::GUI::CommonGizmosDataBase::update().
m_old_meshes
std::vector<const TriangleMesh*> Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::m_old_meshes private
Referenced by on_release(), and on_update().
m_show_supports
bool Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::m_show_supports = false private
Referenced by are_supports_shown(), on_update(), and show_supports().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp
src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp