OrcaSlicer: bounding_box_t< vector_type > Struct Template Reference
bounding_box_t< vector_type > Struct Template Reference
#include <src/mcut/include/mcut/internal/math.h>
Public Member Functions
bounding_box_t (const vector_type &minimum, const vector_type &maximum)
bounding_box_t ()
const vector_type & minimum () const
const vector_type & maximum () const
void expand (const vector_type &point)
void expand (const bounding_box_t< vector_type > &bbox)
void enlarge (const typename vector_type::element_type &eps_)
float SurfaceArea () const
int MaximumExtent () const
Public Attributes
vector_type m_minimum
vector_type m_maximum
Detailed Description
template<typename vector_type>
struct bounding_box_t< vector_type >
Constructor & Destructor Documentation
bounding_box_t() [1/2]
template<typename vector_type > bounding_box_t< vector_type >::bounding_box_t (const vector_type & minimum, const vector_type & maximum) inline
    {
        m_minimum = minimum;
        m_maximum = maximum;
    }
References bounding_box_t< vector_type >::m_maximum, bounding_box_t< vector_type >::m_minimum, bounding_box_t< vector_type >::maximum(), and bounding_box_t< vector_type >::minimum().
bounding_box_t() [2/2]
template<typename vector_type > bounding_box_t< vector_type >::bounding_box_t () inline
    {
        m_minimum = vector_type(std::numeric_limits<double>::max());
        m_maximum = vector_type(-std::numeric_limits<double>::max());
    }
References bounding_box_t< vector_type >::m_maximum, and bounding_box_t< vector_type >::m_minimum.
Member Function Documentation
enlarge()
template<typename vector_type > void bounding_box_t< vector_type >::enlarge (const typename vector_type::element_type & eps_) inline
    {
        m_maximum = m_maximum + eps_;
        m_minimum = m_minimum - eps_;
    }
References bounding_box_t< vector_type >::m_maximum, and bounding_box_t< vector_type >::m_minimum.
expand() [1/2]
template<typename vector_type > void bounding_box_t< vector_type >::expand (const bounding_box_t< vector_type > & bbox) inline
    {
        m_maximum = compwise_max(m_maximum, bbox.maximum());
        m_minimum = compwise_min(m_minimum, bbox.minimum());
    }
References compwise_max(), compwise_min(), bounding_box_t< vector_type >::m_maximum, bounding_box_t< vector_type >::m_minimum, bounding_box_t< vector_type >::maximum(), and bounding_box_t< vector_type >::minimum().
expand() [2/2]
template<typename vector_type > void bounding_box_t< vector_type >::expand (const vector_type & point) inline
    {
        m_maximum = compwise_max(m_maximum, point);
        m_minimum = compwise_min(m_minimum, point);
    }
References compwise_max(), compwise_min(), bounding_box_t< vector_type >::m_maximum, and bounding_box_t< vector_type >::m_minimum.
Referenced by dispatch(), and make_bbox().
maximum()
template<typename vector_type > const vector_type & bounding_box_t< vector_type >::maximum () const inline
    {
        return m_maximum;
    }
References bounding_box_t< vector_type >::m_maximum.
Referenced by bounding_box_t< vector_type >::bounding_box_t(), and bounding_box_t< vector_type >::expand().
MaximumExtent()
template<typename vector_type > int bounding_box_t< vector_type >::MaximumExtent () const inline
    {
        vector_type diag = m_maximum - m_minimum;
        if (diag.x() > diag.y() && diag.x() > diag.z())
            return 0;
        else if (diag.y() > diag.z())
            return 1;
        else
            return 2;
    }
References bounding_box_t< vector_type >::m_maximum, and bounding_box_t< vector_type >::m_minimum.
minimum()
template<typename vector_type > const vector_type & bounding_box_t< vector_type >::minimum () const inline
    {
        return m_minimum;
    }
References bounding_box_t< vector_type >::m_minimum.
Referenced by bounding_box_t< vector_type >::bounding_box_t(), and bounding_box_t< vector_type >::expand().
SurfaceArea()
template<typename vector_type > float bounding_box_t< vector_type >::SurfaceArea () const inline
    {
        vector_type d = m_maximum - m_minimum;
        return typename vector_type::element_type(2.0) * (d.x() * d.y() + d.x() * d.z() + d.y() * d.z());
    }
References bounding_box_t< vector_type >::m_maximum, and bounding_box_t< vector_type >::m_minimum.
Member Data Documentation
m_maximum
template<typename vector_type > vector_type bounding_box_t< vector_type >::m_maximum
Referenced by bounding_box_t< vector_type >::bounding_box_t(), bounding_box_t< vector_type >::bounding_box_t(), bounding_box_t< vector_type >::enlarge(), bounding_box_t< vector_type >::expand(), bounding_box_t< vector_type >::expand(), bounding_box_t< vector_type >::maximum(), bounding_box_t< vector_type >::MaximumExtent(), point_in_bounding_box(), point_in_bounding_box(), and bounding_box_t< vector_type >::SurfaceArea().
m_minimum
template<typename vector_type > vector_type bounding_box_t< vector_type >::m_minimum
Referenced by bounding_box_t< vector_type >::bounding_box_t(), bounding_box_t< vector_type >::bounding_box_t(), bounding_box_t< vector_type >::enlarge(), bounding_box_t< vector_type >::expand(), bounding_box_t< vector_type >::expand(), bounding_box_t< vector_type >::MaximumExtent(), bounding_box_t< vector_type >::minimum(), point_in_bounding_box(), point_in_bounding_box(), and bounding_box_t< vector_type >::SurfaceArea().
The documentation for this struct was generated from the following file:
src/mcut/include/mcut/internal/math.h