OrcaSlicer: Slic3r::CalibPressureAdvance Class Reference
Slic3r::CalibPressureAdvance Class Reference
#include <src/libslic3r/calib.hpp>
Static Public Member Functions
static float find_optimal_PA_speed (const DynamicPrintConfig &config, double line_width, double layer_height, int filament_idx=0)
Protected Types
enum class DrawDigitMode { Left_To_Right , Bottom_To_Top }
Protected Member Functions
CalibPressureAdvance ()=default
~CalibPressureAdvance ()=default
void delta_scale_bed_ext (BoundingBoxf &bed_ext) const
std::string move_to (Vec2d pt, GCodeWriter &writer, std::string comment=std::string())
double e_per_mm (double line_width, double layer_height, float nozzle_diameter, float filament_diameter, float print_flow_ratio) const
double speed_adjust (int speed) const
std::string convert_number_to_string (double num) const
double number_spacing () const
std::string draw_digit (double startx, double starty, char c, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, GCodeWriter &writer)
std::string draw_number (double startx, double starty, double value, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, double speed, GCodeWriter &writer)
Protected Attributes
Vec3d m_last_pos
DrawDigitMode m_draw_digit_mode {DrawDigitMode::Left_To_Right}
const double m_digit_segment_len {2}
const double m_digit_gap_len {1}
const std::string::size_type m_max_number_len {5}
Detailed Description
Member Enumeration Documentation
DrawDigitMode
enum class Slic3r::CalibPressureAdvance::DrawDigitMode strong protected
Enumerator
Left_To_Right
Bottom_To_Top
{
        Left_To_Right,
        Bottom_To_Top
    };
Constructor & Destructor Documentation
CalibPressureAdvance()
Slic3r::CalibPressureAdvance::CalibPressureAdvance () protected default
~CalibPressureAdvance()
Slic3r::CalibPressureAdvance::~CalibPressureAdvance () protected default
Member Function Documentation
convert_number_to_string()
std::string Slic3r::CalibPressureAdvance::convert_number_to_string (double num) const protected
{
    auto sNumber = std::to_string(num);
    sNumber.erase(sNumber.find_last_not_of('0') + 1, std::string::npos);
    sNumber.erase(sNumber.find_last_not_of('.') + 1, std::string::npos);
    return sNumber;
}
Referenced by draw_number(), and Slic3r::CalibPressureAdvancePattern::max_numbering_height().
delta_scale_bed_ext()
void Slic3r::CalibPressureAdvance::delta_scale_bed_ext (BoundingBoxf & bed_ext) const inline protected
{ bed_ext.scale(1.0f / 1.41421f); }
References Slic3r::BoundingBoxBase< PointClass >::scale().
Referenced by Slic3r::CalibPressureAdvanceLine::generate_test().
draw_digit()
std::string Slic3r::CalibPressureAdvance::draw_digit (double startx, double starty, char c, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, GCodeWriter & writer) protected
{
    const double len = m_digit_segment_len;
    const double gap = line_width / 2.0;
    const auto dE = e_per_mm * len;
    const auto two_dE = dE * 2;
    Vec2d p0, p1, p2, p3, p4, p5;
    Vec2d p0_5, p4_5;
    Vec2d gap_p0_toward_p3, gap_p2_toward_p3;
    Vec2d dot_direction;
    if (mode == CalibPressureAdvance::DrawDigitMode::Bottom_To_Top) {
        //  1-------2-------5
        //  |       |       |
        //  |       |       |
        //  0-------3-------4
        p0 = Vec2d(startx, starty);
        p0_5 = Vec2d(startx, starty + len / 2);
        p1 = Vec2d(startx, starty + len);
        p2 = Vec2d(startx + len, starty + len);
        p3 = Vec2d(startx + len, starty);
        p4 = Vec2d(startx + len * 2, starty);
        p4_5 = Vec2d(startx + len * 2, starty + len / 2);
        p5 = Vec2d(startx + len * 2, starty + len);
        gap_p0_toward_p3 = p0 + Vec2d(gap, 0);
        gap_p2_toward_p3 = p2 + Vec2d(0, gap);
        dot_direction = Vec2d(-len / 2, 0);
    } else {
        //  0-------1
        //  |       |
        //  3-------2
        //  |       |
        //  4-------5
        p0 = Vec2d(startx, starty);
        p0_5 = Vec2d(startx + len / 2, starty);
        p1 = Vec2d(startx + len, starty);
        p2 = Vec2d(startx + len, starty - len);
        p3 = Vec2d(startx, starty - len);
        p4 = Vec2d(startx, starty - len * 2);
        p4_5 = Vec2d(startx + len / 2, starty - len * 2);
        p5 = Vec2d(startx + len, starty - len * 2);
        gap_p0_toward_p3 = p0 - Vec2d(0, gap);
        gap_p2_toward_p3 = p2 - Vec2d(gap, 0);
        dot_direction = Vec2d(0, len / 2);
    }
    std::stringstream gcode;
    switch (c) {
    case '0':
        gcode << move_to(p0, writer, "Glyph: 0");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(gap_p0_toward_p3, two_dE);
        break;
    case '1':
        gcode << move_to(p0_5, writer, "Glyph: 1");
        gcode << writer.extrude_to_xy(p4_5, two_dE);
        break;
    case '2':
        gcode << move_to(p0, writer, "Glyph: 2");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        break;
    case '3':
        gcode << move_to(p0, writer, "Glyph: 3");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << move_to(gap_p2_toward_p3, writer);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '4':
        gcode << move_to(p0, writer, "Glyph: 4");
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << move_to(p1, writer);
        gcode << writer.extrude_to_xy(p5, two_dE);
        break;
    case '5':
        gcode << move_to(p1, writer, "Glyph: 5");
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        break;
    case '6':
        gcode << move_to(p1, writer, "Glyph: 6");
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p4, two_dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '7':
        gcode << move_to(p0, writer, "Glyph: 7");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        break;
    case '8':
        gcode << move_to(p2, writer, "Glyph: 8");
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p1, two_dE);
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '9':
        gcode << move_to(p5, writer, "Glyph: 9");
        gcode << writer.extrude_to_xy(p1, two_dE);
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        break;
    case '.':
        gcode << move_to(p4_5, writer, "Glyph: .");
        gcode << writer.extrude_to_xy(p4_5 + dot_direction, dE);
        break;
    default:
        break;
    }
    return gcode.str();
}
References Bottom_To_Top, e_per_mm(), Slic3r::GCodeWriter::extrude_to_xy(), m_digit_segment_len, and move_to().
Referenced by draw_number().
draw_number()
std::string Slic3r::CalibPressureAdvance::draw_number (double startx, double starty, double value, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, double speed, GCodeWriter & writer) protected
{
    auto sNumber = convert_number_to_string(value);
    std::stringstream gcode;
    gcode << writer.set_speed(speed);
    for (std::string::size_type i = 0; i < sNumber.length(); ++i) {
        if (i > m_max_number_len) {
            break;
        }
        switch (mode) {
            case DrawDigitMode::Bottom_To_Top:
                gcode << draw_digit(
                    startx,
                    starty + i * number_spacing(),
                    sNumber[i],
                    mode,
                    line_width,
                    e_per_mm,
                    writer
                );
                break;
            default:
                gcode << draw_digit(
                    startx + i * number_spacing(),
                    starty,
                    sNumber[i],
                    mode,
                    line_width,
                    e_per_mm,
                    writer
                );
        }
    }
    return gcode.str();
}
References Bottom_To_Top, convert_number_to_string(), draw_digit(), e_per_mm(), m_max_number_len, number_spacing(), and Slic3r::GCodeWriter::set_speed().
Referenced by Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
e_per_mm()
double Slic3r::CalibPressureAdvance::e_per_mm (double line_width, double layer_height, float nozzle_diameter, float filament_diameter, float print_flow_ratio) const protected
{
    const Flow line_flow = Flow(line_width, layer_height, nozzle_diameter);
    const double filament_area = M_PI * std::pow(filament_diameter / 2, 2);
    return line_flow.mm3_per_mm() / filament_area * print_flow_ratio;
}
References Slic3r::layer_height(), M_PI, and Slic3r::Flow::mm3_per_mm().
Referenced by draw_digit(), Slic3r::CalibPressureAdvancePattern::draw_line(), draw_number(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
find_optimal_PA_speed()
float Slic3r::CalibPressureAdvance::find_optimal_PA_speed (const DynamicPrintConfig & config, double line_width, double layer_height, int filament_idx = 0) static
{
    const double general_suggested_min_speed = 100.0;
    double filament_max_volumetric_speed = config.option<ConfigOptionFloats>("filament_max_volumetric_speed")->get_at(0);
    Flow pattern_line = Flow(line_width, layer_height, config.option<ConfigOptionFloats>("nozzle_diameter")->get_at(0));
    auto pa_speed = std::min(std::max(general_suggested_min_speed,config.option<ConfigOptionFloat>("outer_wall_speed")->value), filament_max_volumetric_speed / pattern_line.mm3_per_mm());
    return std::floor(pa_speed);
}
References Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::layer_height(), Slic3r::Flow::mm3_per_mm(), Slic3r::ConfigBase::option(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::Plater::_calib_pa_tower(), and Slic3r::GCode::_do_export().
move_to()
std::string Slic3r::CalibPressureAdvance::move_to (Vec2d pt, GCodeWriter & writer, std::string comment = std::string()) protected
{
    std::stringstream gcode;
    gcode << writer.retract();
    gcode << writer.travel_to_xy(pt, comment);
    gcode << writer.unretract();
    m_last_pos = Vec3d(pt.x(), pt.y(), 0);
    return gcode.str();
}
References m_last_pos, Slic3r::GCodeWriter::retract(), Slic3r::GCodeWriter::travel_to_xy(), and Slic3r::GCodeWriter::unretract().
Referenced by Slic3r::CalibPressureAdvancePattern::draw_box(), draw_digit(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
number_spacing()
double Slic3r::CalibPressureAdvance::number_spacing () const inline protected
{ return m_digit_segment_len + m_digit_gap_len; };
References m_digit_gap_len, and m_digit_segment_len.
Referenced by draw_number().
speed_adjust()
double Slic3r::CalibPressureAdvance::speed_adjust (int speed) const inline protected
{ return speed * 60; };
Referenced by Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
Member Data Documentation
m_digit_gap_len
const double Slic3r::CalibPressureAdvance::m_digit_gap_len {1} protected
Referenced by Slic3r::CalibPressureAdvancePattern::max_numbering_height(), and number_spacing().
m_digit_segment_len
const double Slic3r::CalibPressureAdvance::m_digit_segment_len {2} protected
Referenced by draw_digit(), Slic3r::CalibPressureAdvancePattern::glyph_length_x(), Slic3r::CalibPressureAdvancePattern::max_numbering_height(), and number_spacing().
m_draw_digit_mode
DrawDigitMode Slic3r::CalibPressureAdvance::m_draw_digit_mode {DrawDigitMode::Left_To_Right} protected
Referenced by Slic3r::CalibPressureAdvancePattern::CalibPressureAdvancePattern(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
m_last_pos
Vec3d Slic3r::CalibPressureAdvance::m_last_pos protected
Referenced by Slic3r::CalibPressureAdvancePattern::draw_line(), and move_to().
m_max_number_len
const std::string::size_type Slic3r::CalibPressureAdvance::m_max_number_len {5} protected
Referenced by draw_number(), and Slic3r::CalibPressureAdvancePattern::max_numbering_height().
The documentation for this class was generated from the following files:
src/libslic3r/calib.hpp
src/libslic3r/calib.cpp