OrcaSlicer: src/mcut/include/mcut/internal/utils.h File Reference
utils.h File Reference
#include <fstream>
#include <iostream>
#include <sstream>
Classes
class logger_t
struct pair< T >
Macros
#define MCUT_MAKE_STRING__(s) #s
#define MCUT_MAKE_STRING_(s) MCUT_MAKE_STRING__(s)
#define MCUT_DEBUG_BUILD 1
#define MCUT_DEBUG_BREAKPOINT_() std::abort()
#define MCUT_ASSERT(a)
#define DEBUG_CODE_MASK(code) code
#define EXCEPTION_THROWN
#define PEDANTIC_SUBSCRIPT_ACCESS 1
#define SAFE_ACCESS(var, i) var.at(i)
#define log_msg(msg_str)
#define UNUSED(x) [&x] {}()
Typedefs
typedef char couldnt_parse_cxx_standard[-1]
Error: couldn't parse standard.
Functions
static int wrap_integer (int x, const int lo, const int hi)
template<typename T >
pair< T > make_pair (const T a, const T b)
Macro Definition Documentation
DEBUG_CODE_MASK
#define DEBUG_CODE_MASK (code) code
EXCEPTION_THROWN
#define EXCEPTION_THROWN
log_msg
#define log_msg (msg_str)
Value:
    {                                        \
        std::stringstream ss;                \
        ss << msg_str << std::endl;          \
        std::cerr << ss.str() << std::flush; \
        }
MCUT_ASSERT
#define MCUT_ASSERT (a)
Value:
    do {                                 \
        if (false == (a)) {              \
            std::fprintf(stderr,         \
                "Assertion failed: %s, " \
                "%d at \'%s\'\n",        \
                __FILE__,                \
                __LINE__,                \
                MCUT_MAKE_STRING_(a));   \
            MCUT_DEBUG_BREAKPOINT_();    \
        }                                \
    } while (0)
MCUT_DEBUG_BREAKPOINT_
#define MCUT_DEBUG_BREAKPOINT_ () std::abort()
MCUT_DEBUG_BUILD
#define MCUT_DEBUG_BUILD 1
MCUT_MAKE_STRING_
#define MCUT_MAKE_STRING_ (s) MCUT_MAKE_STRING__(s)
MCUT_MAKE_STRING__
#define MCUT_MAKE_STRING__ (s) #s
PEDANTIC_SUBSCRIPT_ACCESS
#define PEDANTIC_SUBSCRIPT_ACCESS 1
SAFE_ACCESS
#define SAFE_ACCESS (var, i) var.at(i)
UNUSED
#define UNUSED (x) [&x] {}()
Typedef Documentation
couldnt_parse_cxx_standard
typedef char couldnt_parse_cxx_standard[-1]
Error: couldn't parse standard.
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
Function Documentation
make_pair()
template<typename T > pair< T > make_pair (const T a, const T b)
{
    return pair<T>(a, b);
}
Referenced by dispatch(), and igl::embree::reorient_facets_raycast().
wrap_integer()
static int wrap_integer (int x, const int lo, const int hi) inline static
{
    const int range_size = hi - lo + 1;
    if (x < lo) {
        x += range_size * ((lo - x) / range_size + 1);
    }
    return lo + (x - lo) % range_size;
}
Referenced by triangulate_face().