OrcaSlicer: TabButton Class Reference
TabButton Class Reference
#include <src/slic3r/GUI/TabButton.hpp>
Public Member Functions
TabButton ()
TabButton (wxWindow *parent, wxString text, ScalableBitmap &icon, long style=0, int iconSize=0)
bool Create (wxWindow *parent, wxString text, ScalableBitmap &icon, long style=0, int iconSize=0)
void SetLabel (const wxString &label) override
void SetMinSize (const wxSize &size) override
void SetPaddingSize (const wxSize &size)
void SetTextColor (StateColor const &color)
void SetBorderColor (StateColor const &color)
void SetBGColor (StateColor const &color)
void SetBitmap (ScalableBitmap &bitmap)
bool Enable (bool enable=true)
void Rescale ()
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void SetCornerRadius (double radius)
void SetBorderWidth (int width)
void SetBorderColorNormal (wxColor const &color)
void SetBackgroundColor (StateColor const &color)
void SetBackgroundColorNormal (wxColor const &color)
void SetBackgroundColor2 (StateColor const &color)
Static Public Member Functions
static wxColor GetParentBackgroundColor (wxWindow *parent)
Protected Member Functions
void eraseEvent (wxEraseEvent &evt)
virtual void doRender (wxDC &dc)
Protected Attributes
double radius
int border_width = 1
StateHandler state_handler
StateColor background_color
StateColor background_color2
Private Member Functions
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void messureSize ()
void mouseDown (wxMouseEvent &event)
void mouseReleased (wxMouseEvent &event)
void sendButtonEvent ()
Private Attributes
wxSize textSize
wxSize minSize
wxSize paddingSize
ScalableBitmap icon
StateColor text_color
StateColor border_color
bool pressedDown = false
Detailed Description
Constructor & Destructor Documentation
TabButton() [1/2]
TabButton::TabButton ()
    : paddingSize(43, 16)
    , text_color(*wxBLACK)
{
    background_color = StateColor(
        std::make_pair(TAB_BUTTON_SEL, (int) StateColor::Checked),
        std::make_pair(wxColour("#FEFFFF"), (int) StateColor::Hovered),
        std::make_pair(wxColour("#FEFFFF"), (int) StateColor::Normal));
    border_color = StateColor(
        std::make_pair(wxColour("#FEFFFF"), (int) StateColor::Checked),
        std::make_pair(BORDER_HOVER_COL, (int) StateColor::Hovered),
        std::make_pair(wxColour("#FEFFFF"), (int)StateColor::Normal));
}
TabButton() [2/2]
TabButton::TabButton (wxWindow * parent, wxString text, ScalableBitmap & icon, long style = 0, int iconSize = 0)
    : TabButton()
{
    Create(parent, text, bmp, style, iconSize);
}
Member Function Documentation
Create() [1/2]
bool TabButton::Create (wxWindow * parent, wxString text, ScalableBitmap & icon, long style = 0, int iconSize = 0)
{
    StaticBox::Create(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, style);
    state_handler.attach({&text_color, &border_color});
    state_handler.update_binds();
    //BBS set default font
    SetFont(Label::Body_14);
    wxWindow::SetLabel(text);
    this->icon = bmp;
    messureSize();
    return true;
}
Create() [2/2]
bool StaticBox::Create (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0) inherited
{
    if (style & wxBORDER_NONE)
        border_width = 0;
    wxWindow::Create(parent, id, pos, size, style);
    state_handler.attach({&border_color, &background_color, &background_color2});
    state_handler.update_binds();
    SetBackgroundColour(GetParentBackgroundColor(parent));
    return true;
}
References StateHandler::attach(), StaticBox::background_color, StaticBox::background_color2, StaticBox::border_color, StaticBox::border_width, StaticBox::GetParentBackgroundColor(), size, StaticBox::state_handler, style, and StateHandler::update_binds().
Referenced by FanSwitchButton::FanSwitchButton(), ImageSwitchButton::ImageSwitchButton(), StaticBox::StaticBox(), Button::Create(), SpinInput::Create(), TextInput::Create(), and TempInput::Create().
doRender()
void StaticBox::doRender (wxDC & dc) protected virtual inherited
Reimplemented in StepCtrl, StepIndicator, and TabCtrl.
{
    wxSize size = GetSize();
    int states = state_handler.states();
    if (background_color2.count() == 0) {
        if ((border_width && border_color.count() > 0) || background_color.count() > 0) {
            wxRect rc(0, 0, size.x, size.y);
            if (border_width && border_color.count() > 0) {
                if (dc.GetContentScaleFactor() == 1.0) {
                    int d  = floor(border_width / 2.0);
                    int d2 = floor(border_width - 1);
                    rc.x += d;
                    rc.width -= d2;
                    rc.y += d;
                    rc.height -= d2;
                } else {
                    int d  = 1;
                    rc.x += d;
                    rc.width -= d;
                    rc.y += d;
                    rc.height -= d;
                }
                dc.SetPen(wxPen(border_color.colorForStates(states), border_width));
            } else {
                dc.SetPen(wxPen(background_color.colorForStates(states)));
            }
            if (background_color.count() > 0)
                dc.SetBrush(wxBrush(background_color.colorForStates(states)));
            else
                dc.SetBrush(wxBrush(GetBackgroundColour()));
            if (radius == 0) {
                dc.DrawRectangle(rc);
            }
            else {
                dc.DrawRoundedRectangle(rc, radius - border_width);
            }
        }
    }
    else {
        wxColor start = background_color.colorForStates(states);
        wxColor stop = background_color2.colorForStates(states);
        int r = start.Red(), g = start.Green(), b = start.Blue();
        int dr = (int) stop.Red() - r, dg = (int) stop.Green() - g, db = (int) stop.Blue() - b;
        int lr = 0, lg = 0, lb = 0;
        for (int y = 0; y < size.y; ++y) {
            dc.SetPen(wxPen(wxColor(r, g, b)));
            dc.DrawLine(0, y, size.x, y);
            lr += dr; while (lr >= size.y) { ++r, lr -= size.y; } while (lr <= -size.y) { --r, lr += size.y; }
            lg += dg; while (lg >= size.y) { ++g, lg -= size.y; } while (lg <= -size.y) { --g, lg += size.y; }
            lb += db; while (lb >= size.y) { ++b, lb -= size.y; } while (lb <= -size.y) { --b, lb += size.y; }
        }
    }
}
References StaticBox::background_color, StaticBox::background_color2, StaticBox::border_color, StaticBox::border_width, StateColor::colorForStates(), StateColor::count(), floor(), int, StaticBox::radius, size, start, StaticBox::state_handler, and StateHandler::states().
Referenced by StepCtrl::doRender(), StepIndicator::doRender(), and StaticBox::render().
Enable()
bool TabButton::Enable (bool enable = true)
{
    bool result = wxWindow::Enable(enable);
    if (result) {
        wxCommandEvent e(EVT_ENABLE_CHANGED);
        e.SetEventObject(this);
        GetEventHandler()->ProcessEvent(e);
    }
    return result;
}
eraseEvent()
void StaticBox::eraseEvent (wxEraseEvent & evt) protected inherited
{
    // for transparent background, but not work
#ifdef __WXMSW__
    wxDC *dc = evt.GetDC();
    wxSize size = GetSize();
    wxClientDC dc2(GetParent());
    dc->Blit({0, 0}, size, &dc2, GetPosition());
#endif
}
References size.
GetParentBackgroundColor()
wxColor StaticBox::GetParentBackgroundColor (wxWindow * parent) static inherited
{
    if (auto box = dynamic_cast<StaticBox*>(parent)) {
        if (box->background_color.count() > 0) {
            if (box->background_color2.count() == 0)
                return box->background_color.defaultColor();
            auto s = box->background_color.defaultColor();
            auto e = box->background_color2.defaultColor();
            int r = (s.Red() + e.Red()) / 2;
            int g = (s.Green() + e.Green()) / 2;
            int b = (s.Blue() + e.Blue()) / 2;
            return wxColor(r, g, b);
        }
    }
    if (parent)
        return parent->GetBackgroundColour();
    return *wxWHITE;
}
Referenced by Label::Label(), ScalableButton::ScalableButton(), SwitchButton::SwitchButton(), StaticBox::Create(), and SwitchButton::Rescale().
messureSize()
void TabButton::messureSize () private
{
    wxClientDC dc(this);
    textSize = dc.GetTextExtent(GetLabel());
    if (minSize.GetWidth() > 0) {
        wxWindow::SetMinSize(minSize);
        return;
    }
    wxSize szContent = textSize;
    if (this->icon.bmp().IsOk()) {
        if (szContent.y > 0) {
            // BBS norrow size between text and icon
            szContent.x += 5;
        }
        wxSize szIcon = this->icon.GetBmpSize();
        szContent.x += szIcon.x;
        if (szIcon.y > szContent.y) szContent.y = szIcon.y;
    }
    wxWindow::SetMinSize(szContent + paddingSize);
}
mouseDown()
void TabButton::mouseDown (wxMouseEvent & event) private
{
    event.Skip();
    pressedDown = true;
    SetFocus();
    CaptureMouse();
}
mouseReleased()
void TabButton::mouseReleased (wxMouseEvent & event) private
{
    event.Skip();
    if (pressedDown) {
        pressedDown = false;
        ReleaseMouse();
        if (wxRect({0, 0}, GetSize()).Contains(event.GetPosition()))
            sendButtonEvent();
    }
}
paintEvent()
void TabButton::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    render(dc);
}
render()
void TabButton::render (wxDC & dc) private
{
    StaticBox::render(dc);
    int    states = state_handler.states();
    wxSize size   = GetSize();
    dc.SetPen(wxPen(border_color.colorForStates(states)));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRectangle(0, 0, size.x, size.y);
    // calc content size
    wxSize szIcon;
    wxSize szContent = textSize;
    if (icon.bmp().IsOk()) {
        if (szContent.y > 0) {
            // BBS norrow size between text and icon
            szContent.x += 5;
        }
        szIcon = icon.GetBmpSize();
        szContent.x += szIcon.x;
        if (szIcon.y > szContent.y) szContent.y = szIcon.y;
    }
    // move to center
    wxRect rcContent = {{0, 0}, size};
    wxSize offset    = (size - szContent) / 2;
    rcContent.Deflate(offset.x, offset.y);
    // start draw
    wxPoint pt = rcContent.GetLeftTop();
    auto text = GetLabel();
    if (!text.IsEmpty()) {
        pt.x = paddingSize.x;
        pt.y = rcContent.y + (rcContent.height - textSize.y) / 2;
        dc.SetFont(GetFont());
        dc.SetTextForeground(text_color.colorForStates(states));
        dc.DrawText(text, pt);
    }
    if (icon.bmp().IsOk()) {
        pt.x = size.x - icon.GetBmpWidth() - paddingSize.y;
        pt.y = (size.y - icon.GetBmpHeight()) / 2;
        dc.DrawBitmap(icon.bmp(), pt);
    }
}
Rescale()
void TabButton::Rescale ()
{
    messureSize();
}
sendButtonEvent()
void TabButton::sendButtonEvent () private
{
    wxCommandEvent event(wxEVT_COMMAND_BUTTON_CLICKED, GetId());
    event.SetEventObject(this);
    GetEventHandler()->ProcessEvent(event);
}
SetBackgroundColor()
void StaticBox::SetBackgroundColor (StateColor const & color) inherited
{
    background_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::ParamsPanel::ParamsPanel(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::PublishDialog::create_publish_step_sizer(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::InputIpAddressDialog::on_check_ip_address_failed(), Slic3r::GUI::ColorPickerPopup::on_custom_clr_picker(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), ButtonsListCtrl::OnPaint(), TabButtonsListCtrl::OnPaint(), Slic3r::GUI::ColorPickerPopup::set_def_colour(), and Slic3r::GUI::MonitorPanel::show_status().
SetBackgroundColor2()
void StaticBox::SetBackgroundColor2 (StateColor const & color) inherited
{
    background_color2 = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color2, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::ParamsPanel::ParamsPanel().
SetBackgroundColorNormal()
void StaticBox::SetBackgroundColorNormal (wxColor const & color) inherited
{
    background_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::background_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBGColor()
void TabButton::SetBGColor (StateColor const & color)
{
    background_color = color;
    state_handler.update_binds();
    Refresh();
}
SetBitmap()
void TabButton::SetBitmap (ScalableBitmap & bitmap)
{
    this->icon = bitmap;
}
SetBorderColor()
void TabButton::SetBorderColor (StateColor const & color)
{
    border_color = color;
    state_handler.update_binds();
    Refresh();
}
SetBorderColorNormal()
void StaticBox::SetBorderColorNormal (wxColor const & color) inherited
{
    border_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::border_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderWidth()
void StaticBox::SetBorderWidth (int width) inherited
{
    border_width = width;
    Refresh();
}
References StaticBox::border_width.
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::StatusBasePanel::create_bed_control(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), and Slic3r::GUI::StatusBasePanel::create_misc_control().
SetCornerRadius()
void StaticBox::SetCornerRadius (double radius) inherited
{
    this->radius = radius;
    Refresh();
}
References StaticBox::radius.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::ProgressDialog::Create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), SpinInput::createButton(), Slic3r::GUI::StatusPanel::init_scaled_buttons(), Slic3r::GUI::AMSControl::init_scaled_buttons(), Slic3r::GUI::MonitorPanel::init_tabpanel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::MonitorPanel::msw_rescale(), Slic3r::GUI::ConnectPrinterDialog::on_dpi_changed(), Slic3r::GUI::RecenterDialog::on_dpi_changed(), and Slic3r::GUI::SelectMachineDialog::on_dpi_changed().
SetLabel()
void TabButton::SetLabel (const wxString & label) override
{
    wxWindow::SetLabel(label);
    messureSize();
    Refresh();
}
Referenced by TabButtonsListCtrl::SetPageText().
SetMinSize()
void TabButton::SetMinSize (const wxSize & size) override
{
    minSize = size;
    messureSize();
}
Referenced by TabButtonsListCtrl::InsertPage().
SetPaddingSize()
void TabButton::SetPaddingSize (const wxSize & size)
{
    paddingSize = size;
    messureSize();
}
SetTextColor()
void TabButton::SetTextColor (StateColor const & color)
{
    text_color = color;
    state_handler.update_binds();
    Refresh();
}
Referenced by TabButtonsListCtrl::InsertPage().
Member Data Documentation
background_color
StateColor StaticBox::background_color protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), StaticBox::SetBackgroundColor(), and StaticBox::SetBackgroundColorNormal().
background_color2
StateColor StaticBox::background_color2 protected inherited
Referenced by StaticBox::Create(), StaticBox::doRender(), and StaticBox::SetBackgroundColor2().
border_color
StateColor TabButton::border_color private
border_width
int StaticBox::border_width = 1 protected inherited
Referenced by StepCtrl::StepCtrl(), StepIndicator::StepIndicator(), TabCtrl::TabCtrl(), StaticBox::Create(), StaticBox::doRender(), TabCtrl::doRender(), and StaticBox::SetBorderWidth().
icon
ScalableBitmap TabButton::icon private
minSize
wxSize TabButton::minSize private
paddingSize
wxSize TabButton::paddingSize private
pressedDown
bool TabButton::pressedDown = false private
radius
double StaticBox::radius protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StepCtrlBase::StepCtrlBase(), TabCtrl::TabCtrl(), StaticBox::doRender(), TabCtrl::doRender(), StaticBox::render(), and StaticBox::SetCornerRadius().
state_handler
StateHandler StaticBox::state_handler protected inherited
Referenced by Button::Create(), StaticBox::Create(), StaticBox::doRender(), StepCtrl::doRender(), StepIndicator::doRender(), TabCtrl::doRender(), Button::GetValue(), Button::render(), ImageSwitchButton::render(), FanSwitchButton::render(), StaticBox::SetBackgroundColor(), StaticBox::SetBackgroundColor2(), StaticBox::SetBorderColor(), Button::SetTextColor(), ImageSwitchButton::SetTextColor(), FanSwitchButton::SetTextColor(), and Button::SetValue().
text_color
StateColor TabButton::text_color private
textSize
wxSize TabButton::textSize private
The documentation for this class was generated from the following files:
src/slic3r/GUI/TabButton.hpp
src/slic3r/GUI/TabButton.cpp