OrcaSlicer: Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo Class Reference
Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
ModelObjectsInfo (AssembleViewDataPool *cgdp)
ModelObjectPtrs model_objects () const
float get_sla_shift () const
void update ()
void release ()
bool is_valid () const
virtual AssembleViewDataID get_dependencies () const
Protected Member Functions
void on_update () override
void on_release () override
AssembleViewDataPool * get_pool () const
Private Attributes
ModelObjectPtrs m_model_objects
float m_z_shift = 0.f
bool m_is_valid = false
AssembleViewDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
ModelObjectsInfo()
Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::ModelObjectsInfo (AssembleViewDataPool * cgdp) inline explicit
        : AssembleViewDataBase(cgdp) {}
Member Function Documentation
get_dependencies()
virtual AssembleViewDataID Slic3r::GUI::AssembleViewDataBase::get_dependencies () const inline virtual inherited
Reimplemented in Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper.
{ return AssembleViewDataID::None; }
References Slic3r::GUI::None.
get_pool()
AssembleViewDataPool * Slic3r::GUI::AssembleViewDataBase::get_pool () const inline protected inherited
{ return m_common; }
References Slic3r::GUI::AssembleViewDataBase::m_common.
Referenced by on_update(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::on_update(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::render_cut(), and Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::set_position().
get_sla_shift()
float Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::get_sla_shift () const inline
{ return m_z_shift; }
References m_z_shift.
is_valid()
bool Slic3r::GUI::AssembleViewDataBase::is_valid () const inline inherited
{ return m_is_valid; }
References Slic3r::GUI::AssembleViewDataBase::m_is_valid.
Referenced by Slic3r::GUI::AssembleViewDataPool::model_objects_clipper(), and Slic3r::GUI::AssembleViewDataPool::model_objects_info().
model_objects()
ModelObjectPtrs Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::model_objects () const inline
{ return m_model_objects; }
References m_model_objects.
Referenced by Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::on_update(), and Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::render_cut().
on_release()
void Slic3r::GUI::ModelObjectsInfo::on_release () override protected virtual
Implements Slic3r::GUI::AssembleViewDataBase.
{
    m_model_objects.clear();
}
References m_model_objects.
on_update()
void Slic3r::GUI::ModelObjectsInfo::on_update () override protected virtual
Implements Slic3r::GUI::AssembleViewDataBase.
{
    if (!get_pool()->get_canvas()->get_model()->objects.empty()) {
        m_model_objects = get_pool()->get_canvas()->get_model()->objects;
    }
    else {
        m_model_objects.clear();
    }
}
References Slic3r::GUI::AssembleViewDataPool::get_canvas(), Slic3r::GUI::GLCanvas3D::get_model(), Slic3r::GUI::AssembleViewDataBase::get_pool(), m_model_objects, and Slic3r::Model::objects.
release()
void Slic3r::GUI::AssembleViewDataBase::release () inline inherited
{ on_release(); m_is_valid = false; }
References Slic3r::GUI::AssembleViewDataBase::m_is_valid, and Slic3r::GUI::AssembleViewDataBase::on_release().
update()
void Slic3r::GUI::AssembleViewDataBase::update () inline inherited
{ on_update(); m_is_valid = true; }
References Slic3r::GUI::AssembleViewDataBase::m_is_valid, and Slic3r::GUI::AssembleViewDataBase::on_update().
Member Data Documentation
m_common
AssembleViewDataPool* Slic3r::GUI::AssembleViewDataBase::m_common = nullptr private inherited
Referenced by Slic3r::GUI::AssembleViewDataBase::get_pool().
m_is_valid
bool Slic3r::GUI::AssembleViewDataBase::m_is_valid = false private inherited
Referenced by Slic3r::GUI::AssembleViewDataBase::is_valid(), Slic3r::GUI::AssembleViewDataBase::release(), and Slic3r::GUI::AssembleViewDataBase::update().
m_model_objects
ModelObjectPtrs Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::m_model_objects private
Referenced by model_objects(), on_release(), and on_update().
m_z_shift
float Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::m_z_shift = 0.f private
Referenced by get_sla_shift().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp
src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp