OrcaSlicer: Slic3r::GUI::GLToolbarItem Class Reference
Slic3r::GUI::GLToolbarItem Class Reference
#include <src/slic3r/GUI/GLToolbar.hpp>
Classes
struct Data
Public Types
enum EType : unsigned char {
Action , Separator , ActionWithText , ActionWithTextImage ,
SeparatorLine , Num_Types
}
enum EActionType : unsigned char { Undefined , Left , Right , Num_Action_Types }
enum EState : unsigned char {
Normal , Pressed , Disabled , Hover ,
HoverPressed , HoverDisabled , Num_States
}
enum EHighlightState : unsigned char { HighlightedShown , HighlightedHidden , Num_Rendered_Highlight_States , NotHighlighted }
typedef std::function< void()> ActionCallback
typedef std::function< bool()> VisibilityCallback
typedef std::function< bool()> EnablingCallback
typedef std::function< void(float, float, float, float)> RenderCallback
Public Member Functions
GLToolbarItem (EType type, const Data &data)
EState get_state () const
void set_state (EState state)
EHighlightState get_highlight () const
void set_highlight (EHighlightState state)
const std::string & get_name () const
const std::string & get_icon_filename () const
void set_icon_filename (const std::string &filename)
const std::string & get_tooltip () const
const std::string & get_additional_tooltip () const
void set_additional_tooltip (const std::string &text)
void set_tooltip (const std::string &text)
void do_left_action ()
void do_right_action ()
bool is_enabled () const
bool is_disabled () const
bool is_hovered () const
bool is_pressed () const
bool is_visible () const
bool is_separator () const
bool is_left_toggable () const
bool is_right_toggable () const
bool has_left_render_callback () const
bool has_right_render_callback () const
EActionType get_last_action_type () const
void reset_last_action_type ()
bool update_visibility ()
bool update_enabled_state ()
bool is_action () const
bool is_action_with_text () const
bool is_action_with_text_image () const
const std::string & get_button_text () const
void set_button_text (const std::string &text)
float get_extra_size_ratio () const
void set_extra_size_ratio (const float ratio)
void render_text (float left, float right, float bottom, float top) const
int generate_texture (wxFont &font)
int generate_image_texture ()
void render (unsigned int tex_id, float left, float right, float bottom, float top, unsigned int tex_width, unsigned int tex_height, unsigned int icon_size) const
void render_image (unsigned int tex_id, float left, float right, float bottom, float top, unsigned int tex_width, unsigned int tex_height, unsigned int icon_size) const
Public Attributes
float render_left_pos
Static Public Attributes
static const ActionCallback Default_Action_Callback = [](){}
static const VisibilityCallback Default_Visibility_Callback = []()->bool { return true; }
static const EnablingCallback Default_Enabling_Callback = []()->bool { return true; }
static const RenderCallback Default_Render_Callback = [](float, float, float, float){}
Private Member Functions
void set_visible (bool visible)
Private Attributes
EType m_type
EState m_state
Data m_data
EActionType m_last_action_type
EHighlightState m_highlight_state
Friends
class GLToolbar
Detailed Description
Member Typedef Documentation
ActionCallback
typedef std::function<void()> Slic3r::GUI::GLToolbarItem::ActionCallback
EnablingCallback
typedef std::function<bool()> Slic3r::GUI::GLToolbarItem::EnablingCallback
RenderCallback
typedef std::function<void(float, float, float, float)> Slic3r::GUI::GLToolbarItem::RenderCallback
VisibilityCallback
typedef std::function<bool()> Slic3r::GUI::GLToolbarItem::VisibilityCallback
Member Enumeration Documentation
EActionType
enum Slic3r::GUI::GLToolbarItem::EActionType : unsigned char
Enumerator
Undefined
Left
Right
Num_Action_Types
    {
        Undefined,
        Left,
        Right,
        Num_Action_Types
    };
EHighlightState
enum Slic3r::GUI::GLToolbarItem::EHighlightState : unsigned char
Enumerator
HighlightedShown
HighlightedHidden
Num_Rendered_Highlight_States
NotHighlighted
    {
        HighlightedShown,
        HighlightedHidden,
        Num_Rendered_Highlight_States,
        NotHighlighted
    };
EState
enum Slic3r::GUI::GLToolbarItem::EState : unsigned char
Enumerator
Normal
Pressed
Disabled
Hover
HoverPressed
HoverDisabled
Num_States
    {
        Normal,
        Pressed,
        Disabled,
        Hover,
        HoverPressed,
        HoverDisabled,
        Num_States
    };
EType
enum Slic3r::GUI::GLToolbarItem::EType : unsigned char
Enumerator
Action
Separator
ActionWithText
ActionWithTextImage
SeparatorLine
Num_Types
    {
        Action,
        Separator,
        //BBS: GUI refactor: GLToolbar
        ActionWithText,
        ActionWithTextImage,
        SeparatorLine,
        Num_Types
    };
Constructor & Destructor Documentation
GLToolbarItem()
Slic3r::GUI::GLToolbarItem::GLToolbarItem (GLToolbarItem::EType type, const Data & data)
    : m_type(type)
    , m_state(Normal)
    , m_data(data)
    , m_last_action_type(Undefined)
    , m_highlight_state(NotHighlighted)
{
    render_left_pos = 0.0f;
}
References render_left_pos.
Member Function Documentation
do_left_action()
void Slic3r::GUI::GLToolbarItem::do_left_action () inline
{ m_last_action_type = Left; m_data.left.action_callback(); }
References Slic3r::GUI::GLToolbarItem::Data::Option::action_callback, Left, Slic3r::GUI::GLToolbarItem::Data::left, m_data, and m_last_action_type.
Referenced by Slic3r::GUI::GLToolbar::do_action().
do_right_action()
void Slic3r::GUI::GLToolbarItem::do_right_action () inline
{ m_last_action_type = Right; m_data.right.action_callback(); }
References Slic3r::GUI::GLToolbarItem::Data::Option::action_callback, m_data, m_last_action_type, Right, and Slic3r::GUI::GLToolbarItem::Data::right.
Referenced by Slic3r::GUI::GLToolbar::do_action().
generate_image_texture()
int Slic3r::GUI::GLToolbarItem::generate_image_texture ()
{
    int ret = 0;
    bool result = false;
    if (m_type != ActionWithTextImage)
        return -1;
    /* load default texture when image is empty */
    if (m_data.image_data.empty()) {
        std::string default_image = resources_dir() + "/images/default_thumbnail.svg";
        result = m_data.image_texture.load_from_svg_file(default_image, true, false, false, m_data.image_width);
    }  else {
        result = m_data.image_texture.load_from_raw_data(m_data.image_data, m_data.image_width, m_data.image_height);
    }
    if (!result)
        ret = -1;
    return ret;
}
References Slic3r::resources_dir().
Referenced by Slic3r::GUI::GLToolbar::generate_image_textures().
generate_texture()
int Slic3r::GUI::GLToolbarItem::generate_texture (wxFont & font)
{
    int ret = 0;
    bool result;
    if (m_type != ActionWithText && m_type != ActionWithTextImage)
        return -1;
    result = m_data.text_texture.generate_from_text_string(m_data.button_text, font);
    if (!result)
        ret = -1;
    return ret;
}
Referenced by Slic3r::GUI::GLToolbar::generate_button_text_textures().
get_additional_tooltip()
const std::string & Slic3r::GUI::GLToolbarItem::get_additional_tooltip () const inline
{ return m_data.additional_tooltip; }
References Slic3r::GUI::GLToolbarItem::Data::additional_tooltip, and m_data.
get_button_text()
const std::string & Slic3r::GUI::GLToolbarItem::get_button_text () const inline
{ return m_data.button_text; }
References Slic3r::GUI::GLToolbarItem::Data::button_text, and m_data.
get_extra_size_ratio()
float Slic3r::GUI::GLToolbarItem::get_extra_size_ratio () const inline
{ return m_data.extra_size_ratio; }
References Slic3r::GUI::GLToolbarItem::Data::extra_size_ratio, and m_data.
Referenced by Slic3r::GUI::GLToolbar::contains_mouse_horizontal(), and Slic3r::GUI::GLToolbar::contains_mouse_vertical().
get_highlight()
EHighlightState Slic3r::GUI::GLToolbarItem::get_highlight () const inline
{ return m_highlight_state; }
References m_highlight_state.
get_icon_filename()
const std::string & Slic3r::GUI::GLToolbarItem::get_icon_filename () const inline
{ return m_data.icon_filename; }
References Slic3r::GUI::GLToolbarItem::Data::icon_filename, and m_data.
get_last_action_type()
EActionType Slic3r::GUI::GLToolbarItem::get_last_action_type () const inline
{ return m_last_action_type; }
References m_last_action_type.
get_name()
const std::string & Slic3r::GUI::GLToolbarItem::get_name () const inline
{ return m_data.name; }
References m_data, and Slic3r::GUI::GLToolbarItem::Data::name.
Referenced by Slic3r::GUI::GLToolbar::do_action(), and Slic3r::GUI::GLToolbar::render_arrow().
get_state()
EState Slic3r::GUI::GLToolbarItem::get_state () const inline
{ return m_state; }
References m_state.
Referenced by Slic3r::GUI::GLToolbar::do_action().
get_tooltip()
const std::string & Slic3r::GUI::GLToolbarItem::get_tooltip () const inline
{ return m_data.tooltip; }
References m_data, and Slic3r::GUI::GLToolbarItem::Data::tooltip.
has_left_render_callback()
bool Slic3r::GUI::GLToolbarItem::has_left_render_callback () const inline
{ return m_data.left.render_callback != nullptr; }
References Slic3r::GUI::GLToolbarItem::Data::left, m_data, and Slic3r::GUI::GLToolbarItem::Data::Option::render_callback.
has_right_render_callback()
bool Slic3r::GUI::GLToolbarItem::has_right_render_callback () const inline
{ return m_data.right.render_callback != nullptr; }
References m_data, Slic3r::GUI::GLToolbarItem::Data::Option::render_callback, and Slic3r::GUI::GLToolbarItem::Data::right.
is_action()
bool Slic3r::GUI::GLToolbarItem::is_action () const inline
{ return m_type == Action; }
References Action, and m_type.
is_action_with_text()
bool Slic3r::GUI::GLToolbarItem::is_action_with_text () const inline
{ return m_type == ActionWithText; }
References ActionWithText, and m_type.
Referenced by Slic3r::GUI::GLToolbar::contains_mouse_horizontal(), Slic3r::GUI::GLToolbar::contains_mouse_vertical(), and Slic3r::GUI::GLToolbar::generate_button_text_textures().
is_action_with_text_image()
bool Slic3r::GUI::GLToolbarItem::is_action_with_text_image () const inline
{ return m_type == ActionWithTextImage; }
References ActionWithTextImage, and m_type.
Referenced by Slic3r::GUI::GLToolbar::contains_mouse_vertical(), Slic3r::GUI::GLToolbar::generate_button_text_textures(), and Slic3r::GUI::GLToolbar::generate_image_textures().
is_disabled()
bool Slic3r::GUI::GLToolbarItem::is_disabled () const inline
{ return (m_state == Disabled) || (m_state == HoverDisabled); }
References Disabled, HoverDisabled, and m_state.
Referenced by Slic3r::GUI::GLToolbar::do_action().
is_enabled()
bool Slic3r::GUI::GLToolbarItem::is_enabled () const inline
{ return (m_state != Disabled) && (m_state != HoverDisabled); }
References Disabled, HoverDisabled, and m_state.
Referenced by update_enabled_state(), and Slic3r::GUI::GLToolbar::update_items_enabled_state().
is_hovered()
bool Slic3r::GUI::GLToolbarItem::is_hovered () const inline
{ return (m_state == Hover) || (m_state == HoverPressed) || (m_state == HoverDisabled); }
References Hover, HoverDisabled, HoverPressed, and m_state.
Referenced by Slic3r::GUI::GLToolbar::do_action().
is_left_toggable()
bool Slic3r::GUI::GLToolbarItem::is_left_toggable () const inline
{ return m_data.left.toggable; }
References Slic3r::GUI::GLToolbarItem::Data::left, m_data, and Slic3r::GUI::GLToolbarItem::Data::Option::toggable.
Referenced by Slic3r::GUI::GLToolbar::do_action().
is_pressed()
bool Slic3r::GUI::GLToolbarItem::is_pressed () const inline
{ return (m_state == Pressed) || (m_state == HoverPressed); }
References HoverPressed, m_state, and Pressed.
Referenced by Slic3r::GUI::GLToolbar::do_action().
is_right_toggable()
bool Slic3r::GUI::GLToolbarItem::is_right_toggable () const inline
{ return m_data.right.toggable; }
References m_data, Slic3r::GUI::GLToolbarItem::Data::right, and Slic3r::GUI::GLToolbarItem::Data::Option::toggable.
Referenced by Slic3r::GUI::GLToolbar::do_action().
is_separator()
bool Slic3r::GUI::GLToolbarItem::is_separator () const inline
{ return m_type == Separator; }
References m_type, and Separator.
Referenced by Slic3r::GUI::GLToolbar::contains_mouse_horizontal(), Slic3r::GUI::GLToolbar::contains_mouse_vertical(), Slic3r::GUI::GLToolbar::do_action(), and update_visibility().
is_visible()
bool Slic3r::GUI::GLToolbarItem::is_visible () const inline
{ return m_data.visible; }
References m_data, and Slic3r::GUI::GLToolbarItem::Data::visible.
Referenced by Slic3r::GUI::GLToolbar::contains_mouse_horizontal(), Slic3r::GUI::GLToolbar::contains_mouse_vertical(), and Slic3r::GUI::GLCanvas3D::highlight_toolbar_item().
render()
void Slic3r::GUI::GLToolbarItem::render (unsigned int tex_id, float left, float right, float bottom, float top, unsigned int tex_width, unsigned int tex_height, unsigned int icon_size) const
{
    auto uvs = [this](unsigned int tex_width, unsigned int tex_height, unsigned int icon_size) -> GLTexture::Quad_UVs
    {
        assert((tex_width != 0) && (tex_height != 0));
        GLTexture::Quad_UVs ret;
        // tiles in the texture are spaced by 1 pixel
        float icon_size_px = (float)(tex_width - 1) / ((float)Num_States + (float)Num_Rendered_Highlight_States);
        char render_state = (m_highlight_state ==  NotHighlighted ? m_state : Num_States + m_highlight_state);
        float inv_tex_width = 1.0f / (float)tex_width;
        float inv_tex_height = 1.0f / (float)tex_height;
        // tiles in the texture are spaced by 1 pixel
        float u_offset = 1.0f * inv_tex_width;
        float v_offset = 1.0f * inv_tex_height;
        float du = icon_size_px * inv_tex_width;
        float dv = icon_size_px * inv_tex_height;
        float left = u_offset + (float)render_state * du;
        float right = left + du - u_offset;
        float top = v_offset + (float)m_data.sprite_id * dv;
        float bottom = top + dv - v_offset;
        ret.left_top = { left, top };
        ret.left_bottom = { left, bottom };
        ret.right_bottom = { right, bottom };
        ret.right_top = { right, top };
        return ret;
    };
    GLTexture::render_sub_texture(tex_id, left, right, bottom, top, uvs(tex_width, tex_height, icon_size));
    if (is_pressed())
    {
        if ((m_last_action_type == Left) && m_data.left.can_render())
            m_data.left.render_callback(left, right, bottom, top);
        else if ((m_last_action_type == Right) && m_data.right.can_render())
            m_data.right.render_callback(left, right, bottom, top);
    }
}
References Slic3r::GUI::GLTexture::Quad_UVs::left_bottom, Slic3r::GUI::GLTexture::Quad_UVs::left_top, Slic3r::GUI::GLTexture::Quad_UVs::right_bottom, and Slic3r::GUI::GLTexture::Quad_UVs::right_top.
render_image()
void Slic3r::GUI::GLToolbarItem::render_image (unsigned int tex_id, float left, float right, float bottom, float top, unsigned int tex_width, unsigned int tex_height, unsigned int icon_size) const
{
    GLTexture::Quad_UVs image_uvs = { { 0.0f, 0.0f }, { 1.0f, 0.0f }, { 1.0f, 1.0f }, { 0.0f, 1.0f } };
    //GLTexture::Quad_UVs image_uvs = { { 0.0f, 1.0f }, { 1.0f, 1.0f }, { 1.0f, 0.0f }, { 0.0f, 0.0f } };
    GLTexture::render_sub_texture(tex_id, left, right, bottom, top, image_uvs);
    if (is_pressed()) {
        if ((m_last_action_type == Left) && m_data.left.can_render())
            m_data.left.render_callback(left, right, bottom, top);
        else if ((m_last_action_type == Right) && m_data.right.can_render())
            m_data.right.render_callback(left, right, bottom, top);
    }
}
render_text()
void Slic3r::GUI::GLToolbarItem::render_text (float left, float right, float bottom, float top) const
{
    float tex_width = (float)m_data.text_texture.get_width();
    float tex_height = (float)m_data.text_texture.get_height();
    //float inv_tex_width = (tex_width != 0.0f) ? 1.0f / tex_width : 0.0f;
    //float inv_tex_height = (tex_height != 0.0f) ? 1.0f / tex_height : 0.0f;
    float internal_left_uv = 0.0f;
    float internal_right_uv = (float)m_data.text_texture.m_original_width / tex_width;
    float internal_top_uv = 0.0f;
    float internal_bottom_uv = (float)m_data.text_texture.m_original_height / tex_height;
    GLTexture::render_sub_texture(m_data.text_texture.get_id(), left, right, bottom, top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
}
References Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::GLTexture::get_width(), m_data, Slic3r::GUI::GLTexture::m_original_height, Slic3r::GUI::GLTexture::m_original_width, Slic3r::GUI::GLTexture::render_sub_texture(), and Slic3r::GUI::GLToolbarItem::Data::text_texture.
reset_last_action_type()
void Slic3r::GUI::GLToolbarItem::reset_last_action_type () inline
{ m_last_action_type = Undefined; }
References m_last_action_type, and Undefined.
Referenced by Slic3r::GUI::GLToolbar::do_action().
set_additional_tooltip()
void Slic3r::GUI::GLToolbarItem::set_additional_tooltip (const std::string & text) inline
{ m_data.additional_tooltip = text; }
References Slic3r::GUI::GLToolbarItem::Data::additional_tooltip, and m_data.
set_button_text()
void Slic3r::GUI::GLToolbarItem::set_button_text (const std::string & text) inline
{ m_data.button_text = text; }
References Slic3r::GUI::GLToolbarItem::Data::button_text, and m_data.
set_extra_size_ratio()
void Slic3r::GUI::GLToolbarItem::set_extra_size_ratio (const float ratio) inline
{ m_data.extra_size_ratio = ratio; }
References Slic3r::GUI::GLToolbarItem::Data::extra_size_ratio, and m_data.
set_highlight()
void Slic3r::GUI::GLToolbarItem::set_highlight (EHighlightState state) inline
{ m_highlight_state = state; }
References m_highlight_state.
set_icon_filename()
void Slic3r::GUI::GLToolbarItem::set_icon_filename (const std::string & filename) inline
{ m_data.icon_filename = filename; }
References Slic3r::GUI::GLToolbarItem::Data::icon_filename, and m_data.
Referenced by Slic3r::GUI::GLCanvas3D::_switch_toolbars_icon_filename().
set_state()
void Slic3r::GUI::GLToolbarItem::set_state (EState state) inline
{ m_state = state; }
References m_state.
Referenced by Slic3r::GUI::GLToolbar::do_action(), and Slic3r::GUI::GLToolbar::update_items_enabled_state().
set_tooltip()
void Slic3r::GUI::GLToolbarItem::set_tooltip (const std::string & text) inline
{ m_data.tooltip = text; }
References m_data, and Slic3r::GUI::GLToolbarItem::Data::tooltip.
set_visible()
void Slic3r::GUI::GLToolbarItem::set_visible (bool visible) inline private
{ m_data.visible = visible; }
References m_data, and Slic3r::GUI::GLToolbarItem::Data::visible.
update_enabled_state()
bool Slic3r::GUI::GLToolbarItem::update_enabled_state ()
{
    bool enabled = m_data.enabling_callback();
    bool ret = (is_enabled() != enabled);
    if (ret)
        m_state = enabled ? GLToolbarItem::Normal : GLToolbarItem::Disabled;
    return ret;
}
References Disabled, Slic3r::GUI::GLToolbarItem::Data::enabling_callback, is_enabled(), m_data, m_state, and Normal.
Referenced by Slic3r::GUI::GLToolbar::update_items_enabled_state().
update_visibility()
bool Slic3r::GUI::GLToolbarItem::update_visibility ()
{
    bool visible = m_data.visibility_callback();
    bool ret = (m_data.visible != visible);
    if (ret)
        m_data.visible = visible;
    // Return false for separator as it would always return true.
    return is_separator() ? false : ret;
}
References is_separator(), m_data, Slic3r::GUI::GLToolbarItem::Data::visibility_callback, and Slic3r::GUI::GLToolbarItem::Data::visible.
Friends And Related Symbol Documentation
GLToolbar
friend class GLToolbar friend
Member Data Documentation
Default_Action_Callback
const GLToolbarItem::ActionCallback Slic3r::GUI::GLToolbarItem::Default_Action_Callback = [](){} static
Default_Enabling_Callback
const GLToolbarItem::EnablingCallback Slic3r::GUI::GLToolbarItem::Default_Enabling_Callback = []()->bool { return true; } static
Default_Render_Callback
const GLToolbarItem::RenderCallback Slic3r::GUI::GLToolbarItem::Default_Render_Callback = [](float, float, float, float){} static
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
Default_Visibility_Callback
const GLToolbarItem::VisibilityCallback Slic3r::GUI::GLToolbarItem::Default_Visibility_Callback = []()->bool { return true; } static
Referenced by Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
m_data
Data Slic3r::GUI::GLToolbarItem::m_data private
Referenced by do_left_action(), do_right_action(), get_additional_tooltip(), get_button_text(), get_extra_size_ratio(), get_icon_filename(), get_name(), get_tooltip(), has_left_render_callback(), has_right_render_callback(), is_left_toggable(), is_right_toggable(), is_visible(), render_text(), set_additional_tooltip(), set_button_text(), set_extra_size_ratio(), set_icon_filename(), set_tooltip(), set_visible(), update_enabled_state(), and update_visibility().
m_highlight_state
EHighlightState Slic3r::GUI::GLToolbarItem::m_highlight_state private
Referenced by get_highlight(), and set_highlight().
m_last_action_type
EActionType Slic3r::GUI::GLToolbarItem::m_last_action_type private
Referenced by do_left_action(), do_right_action(), get_last_action_type(), and reset_last_action_type().
m_state
EState Slic3r::GUI::GLToolbarItem::m_state private
Referenced by get_state(), is_disabled(), is_enabled(), is_hovered(), is_pressed(), set_state(), and update_enabled_state().
m_type
EType Slic3r::GUI::GLToolbarItem::m_type private
Referenced by is_action(), is_action_with_text(), is_action_with_text_image(), and is_separator().
render_left_pos
float Slic3r::GUI::GLToolbarItem::render_left_pos mutable
Referenced by GLToolbarItem(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLToolbar.hpp
src/slic3r/GUI/GLToolbar.cpp