OrcaSlicer: Slic3r::GUI::AmsMapingPopup Class Reference
Slic3r::GUI::AmsMapingPopup Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
AmsMapingPopup (wxWindow *parent)
~AmsMapingPopup ()
wxString format_text (wxString &m_msg)
void update_materials_list (std::vector< std::string > list)
void set_tag_texture (std::string texture)
void update_ams_data (std::map< std::string, Ams * > amsList)
void add_ams_mapping (std::vector< TrayData > tray_data, wxWindow *container, wxBoxSizer *sizer)
void set_current_filament_id (int id)
int get_current_filament_id ()
bool is_match_material (std::string material)
void on_left_down (wxMouseEvent &evt)
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
void paintEvent (wxPaintEvent &evt)
void set_parent_item (wxWindow *item)
std::vector< TrayData > parse_ams_mapping (std::map< std::string, Ams * > amsList)
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Public Attributes
wxStaticText * m_warning_text {nullptr}
std::vector< std::string > m_materials_list
std::vector< wxBoxSizer * > m_amsmapping_container_sizer_list
std::vector< wxWindow * > m_amsmapping_container_list
std::vector< MappingItem * > m_mapping_item_list
bool m_has_unmatch_filament {false}
int m_current_filament_id
std::string m_tag_material
wxBoxSizer * m_sizer_main {nullptr}
wxBoxSizer * m_sizer_list {nullptr}
wxWindow * m_parent_item {nullptr}
Detailed Description
Constructor & Destructor Documentation
AmsMapingPopup()
Slic3r::GUI::AmsMapingPopup::AmsMapingPopup (wxWindow * parent)
    : PopupWindow(parent, wxBORDER_NONE)
 {
     SetSize(wxSize(FromDIP(252), -1));
     SetMinSize(wxSize(FromDIP(252), -1));
     SetMaxSize(wxSize(FromDIP(252), -1));
     Bind(wxEVT_PAINT, &AmsMapingPopup::paintEvent, this);
     #if __APPLE__
     Bind(wxEVT_LEFT_DOWN, &AmsMapingPopup::on_left_down, this);
     #endif
     SetBackgroundColour(*wxWHITE);
     m_sizer_main         = new wxBoxSizer(wxVERTICAL);
     //m_sizer_main->Add(0, 0, 1, wxEXPAND, 0);
     auto title_panel = new wxPanel(this, wxID_ANY);
     title_panel->SetBackgroundColour(wxColour(0xF8, 0xF8, 0xF8));
     title_panel->SetSize(wxSize(-1, FromDIP(30)));
     title_panel->SetMinSize(wxSize(-1, FromDIP(30)));
     wxBoxSizer *title_sizer_h= new wxBoxSizer(wxHORIZONTAL);
     wxBoxSizer *title_sizer_v = new wxBoxSizer(wxVERTICAL);
     auto title_text = new wxStaticText(title_panel, wxID_ANY, _L("AMS Slots"));
     title_text->SetForegroundColour(wxColour(0x32, 0x3A, 0x3D));
     title_text->SetFont(::Label::Head_13);
     title_sizer_v->Add(title_text, 0, wxALIGN_CENTER, 5);
     title_sizer_h->Add(title_sizer_v, 1, wxALIGN_CENTER, 5);
     title_panel->SetSizer(title_sizer_h);
     title_panel->Layout();
     title_panel->Fit();
     m_sizer_list = new wxBoxSizer(wxVERTICAL);
     for (auto i = 0; i < AMS_TOTAL_COUNT; i++) {
         auto sizer_mapping_list = new wxBoxSizer(wxHORIZONTAL);
         /*auto ams_mapping_item_container = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("ams_mapping_container", this, 78), wxDefaultPosition,
             wxSize(FromDIP(230), FromDIP(78)), 0);*/
         auto ams_mapping_item_container = new MappingContainer(this);
         ams_mapping_item_container->SetSizer(sizer_mapping_list);
         ams_mapping_item_container->Layout();
         //ams_mapping_item_container->Hide();
         m_amsmapping_container_sizer_list.push_back(sizer_mapping_list);
         m_amsmapping_container_list.push_back(ams_mapping_item_container);
         m_sizer_list->Add(ams_mapping_item_container, 0, wxALIGN_CENTER_HORIZONTAL|wxTOP|wxBOTTOM, FromDIP(5));
     }
     m_warning_text = new wxStaticText(this, wxID_ANY, wxEmptyString);
     m_warning_text->SetForegroundColour(wxColour(0xFF, 0x6F, 0x00));
     m_warning_text->SetFont(::Label::Body_12);
     auto cant_not_match_tip = _L("Note: Only the AMS slots loaded with the same material type can be selected.");
     m_warning_text->SetLabel(format_text(cant_not_match_tip));
     m_warning_text->SetMinSize(wxSize(FromDIP(248), FromDIP(-1)));
     m_warning_text->Wrap(FromDIP(248));
     m_sizer_main->Add(title_panel, 0, wxEXPAND | wxALL, FromDIP(2));
     m_sizer_main->Add(0, 0, 0, wxTOP, FromDIP(5));
     m_sizer_main->Add(m_sizer_list, 0, wxEXPAND | wxALL, FromDIP(0));
     m_sizer_main->Add(0, 0, 0, wxTOP, FromDIP(5));
     m_sizer_main->Add(m_warning_text, 0, wxEXPAND | wxALL, FromDIP(6));
     SetSizer(m_sizer_main);
     Layout();
     Fit();
     Bind(wxEVT_SHOW, [this](wxShowEvent& e) {
         if (e.IsShown() && m_parent_item) {
             wxPoint pos = m_parent_item->ClientToScreen(wxPoint(0, 0));
             pos.y += m_parent_item->GetRect().height;
             this->Move(pos);
         }
     });
 }
References _L, AMS_TOTAL_COUNT, Label::Body_12, format_text(), Label::Head_13, m_amsmapping_container_list, m_amsmapping_container_sizer_list, m_parent_item, m_sizer_list, m_sizer_main, m_warning_text, on_left_down(), paintEvent(), and wxStaticText.
~AmsMapingPopup()
Slic3r::GUI::AmsMapingPopup::~AmsMapingPopup () inline
{};
Member Function Documentation
add_ams_mapping()
void Slic3r::GUI::AmsMapingPopup::add_ams_mapping (std::vector< TrayData > tray_data, wxWindow * container, wxBoxSizer * sizer)
{
    sizer->Add(0,0,0,wxLEFT,FromDIP(6));
    for (auto i = 0; i < tray_data.size(); i++) {
        // set number
       /* auto number = new wxStaticText(this, wxID_ANY, wxGetApp().transition_tridid(tray_data[i].id), wxDefaultPosition, wxDefaultSize, 0);
        number->SetFont(::Label::Body_13);
        number->SetForegroundColour(wxColour(0X6B, 0X6B, 0X6B));
        number->Wrap(-1);*/
        // set button
        MappingItem *m_mapping_item = new MappingItem(container);
        m_mapping_item->SetSize(wxSize(FromDIP(68 * 0.7), FromDIP(100 * 0.6)));
        m_mapping_item->SetMinSize(wxSize(FromDIP(68 * 0.7), FromDIP(100 * 0.6)));
        m_mapping_item->SetMaxSize(wxSize(FromDIP(68 * 0.7), FromDIP(100 * 0.6)));
        //m_mapping_item->SetCornerRadius(5);
        m_mapping_item->SetFont(::Label::Body_12);
        m_mapping_item_list.push_back(m_mapping_item);
        if (tray_data[i].type == NORMAL) {
            if (is_match_material(tray_data[i].filament_type)) {
                m_mapping_item->set_data(tray_data[i].colour, tray_data[i].name, tray_data[i]);
            } else {
                m_mapping_item->set_data(wxColour(0xEE,0xEE,0xEE), tray_data[i].name, tray_data[i], true);
                m_has_unmatch_filament = true;
            }
            m_mapping_item->Bind(wxEVT_LEFT_DOWN, [this, tray_data, i, m_mapping_item](wxMouseEvent &e) {
                if (!is_match_material(tray_data[i].filament_type)) return;
                m_mapping_item->send_event(m_current_filament_id);
                Dismiss();
            });
        }
        // temp
        if (tray_data[i].type == EMPTY) {
            m_mapping_item->set_data(wxColour(0xCE, 0xCE, 0xCE), "-", tray_data[i]);
            m_mapping_item->Bind(wxEVT_LEFT_DOWN, [this, tray_data, i, m_mapping_item](wxMouseEvent &e) {
                m_mapping_item->send_event(m_current_filament_id);
                Dismiss();
            });
        }
        // third party
        if (tray_data[i].type == THIRD) {
            m_mapping_item->set_data(wxColour(0xCE, 0xCE, 0xCE), "?", tray_data[i]);
            m_mapping_item->Bind(wxEVT_LEFT_DOWN, [this, tray_data, i, m_mapping_item](wxMouseEvent &e) {
                m_mapping_item->send_event(m_current_filament_id);
                Dismiss();
            });
        }
        //sizer_mapping_item->Add(number, 0, wxALIGN_CENTER_HORIZONTAL, 0);
        //sizer_mapping_item->Add(m_mapping_item, 0, wxALIGN_CENTER_HORIZONTAL, 0);
        m_mapping_item->set_tray_index(wxGetApp().transition_tridid(tray_data[i].id));
        sizer->Add(0,0,0,wxRIGHT,FromDIP(6));
        sizer->Add(m_mapping_item, 0, wxTOP, FromDIP(1));
    }
}
References Label::Body_12, Slic3r::GUI::EMPTY, is_match_material(), m_current_filament_id, m_has_unmatch_filament, m_mapping_item_list, Slic3r::GUI::NORMAL, Slic3r::GUI::MappingItem::send_event(), Slic3r::GUI::MappingItem::set_data(), Slic3r::GUI::MappingItem::set_tray_index(), Slic3r::GUI::THIRD, and Slic3r::GUI::wxMouseEvent.
Referenced by update_ams_data().
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
format_text()
wxString Slic3r::GUI::AmsMapingPopup::format_text (wxString & m_msg)
 {
     if (wxGetApp().app_config->get("language") != "zh_CN") { return m_msg; }
     wxString out_txt      = m_msg;
     wxString count_txt    = "";
     int      new_line_pos = 0;
     for (int i = 0; i < m_msg.length(); i++) {
         auto text_size = m_warning_text->GetTextExtent(count_txt);
         if (text_size.x < (FromDIP(280))) {
             count_txt += m_msg[i];
         } else {
             out_txt.insert(i - 1, '\n');
             count_txt = "";
         }
     }
     return out_txt;
 }
References m_warning_text.
Referenced by AmsMapingPopup().
get_current_filament_id()
int Slic3r::GUI::AmsMapingPopup::get_current_filament_id () inline
{return m_current_filament_id;};
References m_current_filament_id.
is_match_material()
bool Slic3r::GUI::AmsMapingPopup::is_match_material (std::string material)
{
    return m_tag_material == material ? true : false;
}
References m_tag_material.
Referenced by add_ams_mapping(), and on_left_down().
on_left_down()
void Slic3r::GUI::AmsMapingPopup::on_left_down (wxMouseEvent & evt)
{
    auto pos = ClientToScreen(evt.GetPosition());
    for (MappingItem *item : m_mapping_item_list) {
        auto p_rect = item->ClientToScreen(wxPoint(0, 0));
        auto left = item->GetSize();
        if (pos.x > p_rect.x && pos.y > p_rect.y && pos.x < (p_rect.x + item->GetSize().x) && pos.y < (p_rect.y + item->GetSize().y)) {
            if (item->m_tray_data.type == TrayType::NORMAL  && !is_match_material(item->m_tray_data.filament_type)) return;
            item->send_event(m_current_filament_id);
            Dismiss();
        }
    }
}
References is_match_material(), m_current_filament_id, m_mapping_item_list, and Slic3r::GUI::NORMAL.
Referenced by AmsMapingPopup().
OnDismiss()
void Slic3r::GUI::AmsMapingPopup::OnDismiss () virtual
{
}
paintEvent()
void Slic3r::GUI::AmsMapingPopup::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRoundedRectangle(0, 0, GetSize().x, GetSize().y, 0);
}
Referenced by AmsMapingPopup().
parse_ams_mapping()
std::vector< TrayData > Slic3r::GUI::AmsMapingPopup::parse_ams_mapping (std::map< std::string, Ams * > amsList)
{
    std::vector<TrayData> m_tray_data;
    std::map<std::string, Ams *>::iterator ams_iter;
    for (ams_iter = amsList.begin(); ams_iter != amsList.end(); ams_iter++) {
        BOOST_LOG_TRIVIAL(trace) << "ams_mapping ams id " << ams_iter->first.c_str();
        auto ams_indx = atoi(ams_iter->first.c_str());
        Ams* ams_group = ams_iter->second;
        std::vector<TrayData>                      tray_datas;
        std::map<std::string, AmsTray*>::iterator tray_iter;
        for (tray_iter = ams_group->trayList.begin(); tray_iter != ams_group->trayList.end(); tray_iter++) {
            AmsTray* tray_data = tray_iter->second;
            TrayData td;
            td.id = ams_indx * AMS_TOTAL_COUNT + atoi(tray_data->id.c_str());
            if (!tray_data->is_exists) {
                td.type = EMPTY;
            }
            else {
                if (!tray_data->is_tray_info_ready()) {
                    td.type = THIRD;
                }
                else {
                    td.type = NORMAL;
                    td.colour = AmsTray::decode_color(tray_data->color);
                    td.name = tray_data->get_display_filament_type();
                    td.filament_type = tray_data->get_filament_type();
                }
            }
            m_tray_data.push_back(td);
        }
    }
    return m_tray_data;
}
References AMS_TOTAL_COUNT, Slic3r::AmsTray::color, Slic3r::GUI::TrayData::colour, Slic3r::AmsTray::decode_color(), Slic3r::GUI::EMPTY, Slic3r::GUI::TrayData::filament_type, Slic3r::AmsTray::get_display_filament_type(), Slic3r::AmsTray::get_filament_type(), Slic3r::GUI::TrayData::id, Slic3r::AmsTray::id, Slic3r::AmsTray::is_exists, Slic3r::AmsTray::is_tray_info_ready(), Slic3r::GUI::TrayData::name, Slic3r::GUI::NORMAL, Slic3r::GUI::THIRD, Slic3r::trace(), Slic3r::Ams::trayList, and Slic3r::GUI::TrayData::type.
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok_btn().
ProcessLeftDown()
bool Slic3r::GUI::AmsMapingPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
set_current_filament_id()
void Slic3r::GUI::AmsMapingPopup::set_current_filament_id (int id) inline
{m_current_filament_id = id;};
References m_current_filament_id.
Referenced by Slic3r::GUI::SelectMachineDialog::set_default().
set_parent_item()
void Slic3r::GUI::AmsMapingPopup::set_parent_item (wxWindow * item) inline
{m_parent_item = item;};
References m_parent_item.
Referenced by Slic3r::GUI::SelectMachineDialog::set_default().
set_tag_texture()
void Slic3r::GUI::AmsMapingPopup::set_tag_texture (std::string texture)
{
    m_tag_material = texture;
}
References m_tag_material.
Referenced by Slic3r::GUI::SelectMachineDialog::set_default().
update_ams_data()
void Slic3r::GUI::AmsMapingPopup::update_ams_data (std::map< std::string, Ams * > amsList)
{
    m_has_unmatch_filament = false;
    //m_mapping_item_list.clear();
    for (auto& ams_container : m_amsmapping_container_list) {
        ams_container->Hide();
    }
    for (wxWindow *mitem : m_mapping_item_list) {
        mitem->Destroy();
        mitem = nullptr;
    }
     m_mapping_item_list.clear();
    if (m_amsmapping_container_sizer_list.size() > 0) {
        for (wxBoxSizer *siz : m_amsmapping_container_sizer_list) {
            siz->Clear(true);
        }
    }
    std::map<std::string, Ams *>::iterator ams_iter;
    BOOST_LOG_TRIVIAL(trace) << "ams_mapping total count " << amsList.size();
    int m_amsmapping_container_list_index = 0;
    for (ams_iter = amsList.begin(); ams_iter != amsList.end(); ams_iter++) {
        BOOST_LOG_TRIVIAL(trace) << "ams_mapping ams id " << ams_iter->first.c_str();
        auto ams_indx = atoi(ams_iter->first.c_str());
        Ams *ams_group = ams_iter->second;
        std::vector<TrayData>                      tray_datas;
        std::map<std::string, AmsTray *>::iterator tray_iter;
        for (tray_iter = ams_group->trayList.begin(); tray_iter != ams_group->trayList.end(); tray_iter++) {
            AmsTray *tray_data = tray_iter->second;
            TrayData td;
            td.id = ams_indx * AMS_TOTAL_COUNT + atoi(tray_data->id.c_str());
            if (!tray_data->is_exists) {
                td.type = EMPTY;
            } else {
                if (!tray_data->is_tray_info_ready()) {
                    td.type = THIRD;
                } else {
                    td.type   = NORMAL;
                    td.colour = AmsTray::decode_color(tray_data->color);
                    td.name   = tray_data->get_display_filament_type();
                    td.filament_type = tray_data->get_filament_type();
                }
            }
            tray_datas.push_back(td);
        }
        m_amsmapping_container_list[m_amsmapping_container_list_index]->Show();
        add_ams_mapping(tray_datas, m_amsmapping_container_list[m_amsmapping_container_list_index], m_amsmapping_container_sizer_list[m_amsmapping_container_list_index]);
        m_amsmapping_container_list_index++;
    }
    m_warning_text->Show(m_has_unmatch_filament);
    Layout();
    Fit();
}
References add_ams_mapping(), AMS_TOTAL_COUNT, Slic3r::AmsTray::color, Slic3r::GUI::TrayData::colour, Slic3r::AmsTray::decode_color(), Slic3r::GUI::EMPTY, Slic3r::GUI::TrayData::filament_type, Slic3r::AmsTray::get_display_filament_type(), Slic3r::AmsTray::get_filament_type(), Slic3r::GUI::TrayData::id, Slic3r::AmsTray::id, Slic3r::AmsTray::is_exists, Slic3r::AmsTray::is_tray_info_ready(), m_amsmapping_container_list, m_amsmapping_container_sizer_list, m_has_unmatch_filament, m_mapping_item_list, m_warning_text, Slic3r::GUI::TrayData::name, Slic3r::GUI::NORMAL, Slic3r::GUI::THIRD, Slic3r::trace(), Slic3r::Ams::trayList, and Slic3r::GUI::TrayData::type.
Referenced by Slic3r::GUI::SelectMachineDialog::set_default().
update_materials_list()
void Slic3r::GUI::AmsMapingPopup::update_materials_list (std::vector< std::string > list)
{
    m_materials_list = list;
}
References m_materials_list.
Member Data Documentation
m_amsmapping_container_list
std::vector<wxWindow*> Slic3r::GUI::AmsMapingPopup::m_amsmapping_container_list
Referenced by AmsMapingPopup(), and update_ams_data().
m_amsmapping_container_sizer_list
std::vector<wxBoxSizer*> Slic3r::GUI::AmsMapingPopup::m_amsmapping_container_sizer_list
Referenced by AmsMapingPopup(), and update_ams_data().
m_current_filament_id
int Slic3r::GUI::AmsMapingPopup::m_current_filament_id
Referenced by add_ams_mapping(), get_current_filament_id(), on_left_down(), and set_current_filament_id().
m_has_unmatch_filament
bool Slic3r::GUI::AmsMapingPopup::m_has_unmatch_filament {false}
Referenced by add_ams_mapping(), and update_ams_data().
m_mapping_item_list
std::vector<MappingItem*> Slic3r::GUI::AmsMapingPopup::m_mapping_item_list
Referenced by add_ams_mapping(), on_left_down(), and update_ams_data().
m_materials_list
std::vector<std::string> Slic3r::GUI::AmsMapingPopup::m_materials_list
Referenced by update_materials_list().
m_parent_item
wxWindow* Slic3r::GUI::AmsMapingPopup::m_parent_item {nullptr}
Referenced by AmsMapingPopup(), and set_parent_item().
m_sizer_list
wxBoxSizer* Slic3r::GUI::AmsMapingPopup::m_sizer_list {nullptr}
Referenced by AmsMapingPopup().
m_sizer_main
wxBoxSizer* Slic3r::GUI::AmsMapingPopup::m_sizer_main {nullptr}
Referenced by AmsMapingPopup().
m_tag_material
std::string Slic3r::GUI::AmsMapingPopup::m_tag_material
Referenced by is_match_material(), and set_tag_texture().
m_warning_text
wxStaticText* Slic3r::GUI::AmsMapingPopup::m_warning_text {nullptr}
Referenced by AmsMapingPopup(), format_text(), and update_ams_data().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp