OrcaSlicer: Slic3r::PrintBase Class Reference
Slic3r::PrintBase Class Reference abstract
Printing involves slicing and export of device dependent instructions.
#include <src/libslic3r/PrintBase.hpp>
Classes
struct SlicingStatus
struct TaskParams
Public Types
enum ApplyStatus { APPLY_STATUS_UNCHANGED , APPLY_STATUS_CHANGED , APPLY_STATUS_INVALIDATED }
enum CancelStatus { NOT_CANCELED = 0 , CANCELED_BY_USER = 1 , CANCELED_INTERNAL = 2 }
typedef std::function< void(const SlicingStatus &)> status_callback_type
typedef std::function< void()> cancel_callback_type
using Timestamp = uint64_t
Public Member Functions
PrintBase ()
virtual ~PrintBase ()
virtual PrinterTechnology technology () const noexcept=0
virtual void clear ()=0
virtual bool empty () const =0
virtual std::vector< ObjectID > print_object_ids () const =0
virtual StringObjectException validate (StringObjectException *warning=nullptr, Polygons *collison_polygons=nullptr, std::vector< std::pair< Polygon, float > > *height_polygons=nullptr) const
virtual ApplyStatus apply (const Model &model, DynamicPrintConfig config)=0
const Model & model () const
virtual void set_task (const TaskParams &params)
virtual void process (bool use_cache=false)=0
virtual int export_cached_data (const std::string &dir_path, bool with_space=false)
virtual int load_cached_data (const std::string &directory)
virtual void finalize ()
void set_status_default ()
void set_status_silent ()
void set_status_callback (status_callback_type cb)
void set_status (int percent, const std::string &message, unsigned int flags=SlicingStatus::DEFAULT, int warning_step=-1) const
void set_cancel_callback (cancel_callback_type cancel_callback)
CancelStatus cancel_status () const
bool canceled () const
void cancel ()
void cancel_internal ()
void restart ()
virtual bool finished () const =0
const PlaceholderParser & placeholder_parser () const
const DynamicPrintConfig & full_print_config () const
virtual std::string output_filename (const std::string &filename_base=std::string()) const =0
std::string output_filepath (const std::string &path, const std::string &filename_base=std::string()) const
int get_plate_index () const
void set_plate_index (int index)
bool get_no_check_flag () const
void set_no_check_flag (bool no_check)
std::string get_plate_name () const
void set_plate_name (const std::string &name)
ObjectID id () const
virtual Timestamp timestamp () const
Protected Member Functions
std::mutex & state_mutex () const
std::function< void()> cancel_callback ()
void call_cancel_callback ()
void status_update_warnings (int step, PrintStateBase::WarningLevel warning_level, const std::string &message, const PrintObjectBase *print_object=nullptr, PrintStateBase::SlicingNotificationType message_id=PrintStateBase::SlicingDefaultNotification)
void status_update_warnings (int step, PrintStateBase::WarningLevel, const std::string &message, PrintObjectBase &object, PrintStateBase::SlicingNotificationType message_id=PrintStateBase::SlicingDefaultNotification)
void throw_if_canceled () const
PrintTryCancel make_try_cancel () const
std::string output_filename (const std::string &format, const std::string &default_ext, const std::string &filename_base, const DynamicConfig *config_override=nullptr) const
void update_object_placeholders (DynamicConfig &config, const std::string &default_ext) const
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Protected Attributes
Model m_model
DynamicPrintConfig m_full_print_config
PlaceholderParser m_placeholder_parser
int m_plate_index { 0 }
bool m_no_check = false
std::string m_plate_name
status_callback_type m_status_callback
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
std::atomic< CancelStatus > m_cancel_status
cancel_callback_type m_cancel_callback = [](){}
std::mutex m_state_mutex
friend PrintTryCancel
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class PrintObjectBase
class BackgroundSlicingProcess
Detailed Description
Printing involves slicing and export of device dependent instructions.
Every technology has a potentially different set of requirements for slicing, support structures and output print instructions. The pipeline however remains roughly the same: slice -> convert to instructions -> send to printer
The PrintBase class will abstract this flow for different technologies.
Member Typedef Documentation
cancel_callback_type
typedef std::function<void()> Slic3r::PrintBase::cancel_callback_type
status_callback_type
typedef std::function<void(const SlicingStatus&)> Slic3r::PrintBase::status_callback_type
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Member Enumeration Documentation
ApplyStatus
enum Slic3r::PrintBase::ApplyStatus
Enumerator
APPLY_STATUS_UNCHANGED
APPLY_STATUS_CHANGED
APPLY_STATUS_INVALIDATED
                     {
        // No change after the Print::apply() call.
        APPLY_STATUS_UNCHANGED,
        // Some of the Print / PrintObject / PrintObjectInstance data was changed,
        // but no result was invalidated (only data influencing not yet calculated results were changed).
        APPLY_STATUS_CHANGED,
        // Some data was changed, which in turn invalidated already calculated steps.
        APPLY_STATUS_INVALIDATED,
    };
CancelStatus
enum Slic3r::PrintBase::CancelStatus
Enumerator
NOT_CANCELED
CANCELED_BY_USER
CANCELED_INTERNAL
                    {
    // No cancelation, background processing should run.
    NOT_CANCELED = 0,
    // Canceled by user from the user interface (user pressed the "Cancel" button or user closed the application).
    CANCELED_BY_USER = 1,
    // Canceled internally from Print::apply() through the Print/PrintObject::invalidate_step() or ::invalidate_all_steps().
    CANCELED_INTERNAL = 2
  };
Constructor & Destructor Documentation
PrintBase()
Slic3r::PrintBase::PrintBase () inline
: m_placeholder_parser(&m_full_print_config) { this->restart(); }
References restart().
~PrintBase()
virtual Slic3r::PrintBase::~PrintBase () inline virtual
{}
Member Function Documentation
apply()
virtual ApplyStatus Slic3r::PrintBase::apply (const Model & model, DynamicPrintConfig config) pure virtual
Implemented in Slic3r::Print, and Slic3r::SLAPrint.
Referenced by Slic3r::BackgroundSlicingProcess::apply(), and Slic3r::CLI::run().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
call_cancel_callback()
void Slic3r::PrintBase::call_cancel_callback () inline protected
{ m_cancel_callback(); }
References m_cancel_callback.
Referenced by Slic3r::SLAPrint::apply(), and Slic3r::SLAPrint::set_task().
cancel()
void Slic3r::PrintBase::cancel () inline
{ m_cancel_status = CANCELED_BY_USER; }
References CANCELED_BY_USER, and m_cancel_status.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::invalid_support_volumes(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), and Slic3r::BackgroundSlicingProcess::stop().
cancel_callback()
std::function< void()> Slic3r::PrintBase::cancel_callback () inline protected
{ return m_cancel_callback; }
References m_cancel_callback.
Referenced by Slic3r::PrintObjectBase::cancel_callback(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::invalidate_all_steps(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::invalidate_step(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::invalidate_steps(), and set_cancel_callback().
cancel_internal()
void Slic3r::PrintBase::cancel_internal () inline
{ m_cancel_status = CANCELED_INTERNAL; }
References CANCELED_INTERNAL, and m_cancel_status.
Referenced by Slic3r::BackgroundSlicingProcess::stop_internal().
cancel_status()
CancelStatus Slic3r::PrintBase::cancel_status () const inline
{ return m_cancel_status.load(std::memory_order_acquire); }
References m_cancel_status.
Referenced by Slic3r::BackgroundSlicingProcess::thread_proc().
canceled()
bool Slic3r::PrintBase::canceled () const inline
{ return m_cancel_status.load(std::memory_order_acquire) != NOT_CANCELED; }
References m_cancel_status, and NOT_CANCELED.
Referenced by Slic3r::SLAPrint::Steps::canceled(), Slic3r::BackgroundSlicingProcess::execute_ui_task(), Slic3r::SLAPrint::Steps::rasterize(), Slic3r::SLAPrint::Steps::support_tree(), Slic3r::BackgroundSlicingProcess::thread_proc(), and Slic3r::BackgroundSlicingProcess::throw_if_canceled().
clear()
virtual void Slic3r::PrintBase::clear () pure virtual
Implemented in Slic3r::Print, and Slic3r::SLAPrint.
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
empty()
virtual bool Slic3r::PrintBase::empty () const pure virtual
Implemented in Slic3r::Print, and Slic3r::SLAPrint.
Referenced by Slic3r::BackgroundSlicingProcess::empty(), Slic3r::CLI::run(), and Slic3r::BackgroundSlicingProcess::start().
export_cached_data()
virtual int Slic3r::PrintBase::export_cached_data (const std::string & dir_path, bool with_space = false) inline virtual
Reimplemented in Slic3r::Print.
{ return 0;}
Referenced by Slic3r::CLI::run().
finalize()
virtual void Slic3r::PrintBase::finalize () inline virtual
Reimplemented in Slic3r::SLAPrint.
{}
Referenced by Slic3r::BackgroundSlicingProcess::thread_proc().
finished()
virtual bool Slic3r::PrintBase::finished () const pure virtual
Implemented in Slic3r::Print, and Slic3r::SLAPrint.
Referenced by Slic3r::BackgroundSlicingProcess::finished(), and Slic3r::BackgroundSlicingProcess::process_fff().
full_print_config()
const DynamicPrintConfig & Slic3r::PrintBase::full_print_config () const inline
{ return m_full_print_config; }
References m_full_print_config.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GCode::append_full_config(), Slic3r::anonymous_namespace{SL1.cpp}::fill_iniconf(), Slic3r::anonymous_namespace{SL1.cpp}::fill_slicerconf(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::BackgroundSlicingProcess::finalize_gcode(), Slic3r::BackgroundSlicingProcess::prepare_upload(), and Slic3r::GUI::SLAImportJob::reset().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_no_check_flag()
bool Slic3r::PrintBase::get_no_check_flag () const inline
{ return m_no_check; }
References m_no_check.
get_plate_index()
int Slic3r::PrintBase::get_plate_index () const inline
{ return m_plate_index; }
References m_plate_index.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::GCode::append_full_config(), Slic3r::GUI::get_wipe_tower_arrangepoly(), Slic3r::get_wipe_tower_extrusions_extents(), Slic3r::layered_print_cleareance_valid(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::GCode::process_layer(), and Slic3r::Print::validate().
get_plate_name()
std::string Slic3r::PrintBase::get_plate_name () const inline
{ return m_plate_name; }
References m_plate_name.
Referenced by Slic3r::GCode::_do_export().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
load_cached_data()
virtual int Slic3r::PrintBase::load_cached_data (const std::string & directory) inline virtual
Reimplemented in Slic3r::Print.
{ return 0;}
Referenced by Slic3r::CLI::run().
make_try_cancel()
PrintTryCancel Slic3r::PrintBase::make_try_cancel () const inline protected
{ return PrintTryCancel(this); }
References PrintTryCancel.
model()
const Model & Slic3r::PrintBase::model () const inline
{ return m_model; }
References m_model.
Referenced by Slic3r::ToolOrdering::ToolOrdering(), Slic3r::GUI::Plater::priv::actualize_object_warnings(), Slic3r::SLAPrint::apply(), Slic3r::ToolOrdering::assign_custom_gcodes(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::Print::sequential_print_clearance_valid(), and Slic3r::sort_object_instances_by_model_order().
output_filename() [1/2]
virtual std::string Slic3r::PrintBase::output_filename (const std::string & filename_base = std::string()) const pure virtual
Implemented in Slic3r::Print, and Slic3r::SLAPrint.
Referenced by Slic3r::SLAPrint::output_filename(), and output_filepath().
output_filename() [2/2]
std::string Slic3r::PrintBase::output_filename (const std::string & format, const std::string & default_ext, const std::string & filename_base, const DynamicConfig * config_override = nullptr) const protected
{
    DynamicConfig cfg;
    if (config_override != nullptr)
      cfg = *config_override;
    cfg.set_key_value("version", new ConfigOptionString(std::string(SoftFever_VERSION)));
    PlaceholderParser::update_timestamp(cfg);
    this->update_object_placeholders(cfg, default_ext);
    if (! filename_base.empty()) {
    cfg.set_key_value("input_filename", new ConfigOptionString(filename_base + default_ext));
    cfg.set_key_value("input_filename_base", new ConfigOptionString(filename_base));
    }
    try {
    boost::filesystem::path filename = format.empty() ?
      cfg.opt_string("input_filename_base") + default_ext :
      this->placeholder_parser().process(format, 0, &cfg);
        if (filename.extension().empty())
            filename = boost::filesystem::change_extension(filename, default_ext);
        return filename.string();
    } catch (std::runtime_error &err) {
        throw Slic3r::PlaceholderParserError(L("Failed processing of the filename_format template.") + "\n" + err.what());
    }
}
References Slic3r::format(), L, Slic3r::DynamicConfig::opt_string(), placeholder_parser(), Slic3r::PlaceholderParser::process(), Slic3r::DynamicConfig::set_key_value(), update_object_placeholders(), and Slic3r::PlaceholderParser::update_timestamp().
output_filepath()
std::string Slic3r::PrintBase::output_filepath (const std::string & path, const std::string & filename_base = std::string()) const
{
    // if we were supplied no path, generate an automatic one based on our first object's input file
    if (path.empty())
        // get the first input file name
        return (boost::filesystem::path(m_model.propose_export_file_name_and_path()).parent_path() / this->output_filename(filename_base)).make_preferred().string();
    // if we were supplied a directory, use it and append our automatically generated filename
    boost::filesystem::path p(path);
    if (boost::filesystem::is_directory(p))
        return (p / this->output_filename(filename_base)).make_preferred().string();
    // if we were supplied a file which is not a directory, use it
    return path;
}
References m_model, output_filename(), and Slic3r::Model::propose_export_file_name_and_path().
Referenced by Slic3r::BackgroundSlicingProcess::output_filepath_for_project().
placeholder_parser()
const PlaceholderParser & Slic3r::PrintBase::placeholder_parser () const inline
{ return m_placeholder_parser; }
References m_placeholder_parser.
Referenced by Slic3r::GCode::_do_export(), and output_filename().
print_object_ids()
virtual std::vector< ObjectID > Slic3r::PrintBase::print_object_ids () const pure virtual
Implemented in Slic3r::Print, and Slic3r::SLAPrint.
Referenced by Slic3r::GUI::Plater::priv::actualize_slicing_warnings().
process()
virtual void Slic3r::PrintBase::process (bool use_cache = false) pure virtual
Implemented in Slic3r::Print, and Slic3r::SLAPrint.
Referenced by Slic3r::BackgroundSlicingProcess::process_fff(), Slic3r::BackgroundSlicingProcess::process_sla(), and Slic3r::CLI::run().
restart()
void Slic3r::PrintBase::restart () inline
{ m_cancel_status = NOT_CANCELED; }
References m_cancel_status, and NOT_CANCELED.
Referenced by PrintBase(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), and Slic3r::BackgroundSlicingProcess::thread_proc().
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_cancel_callback()
void Slic3r::PrintBase::set_cancel_callback (cancel_callback_type cancel_callback) inline
{ m_cancel_callback = cancel_callback; }
References cancel_callback(), and m_cancel_callback.
Referenced by Slic3r::BackgroundSlicingProcess::start(), Slic3r::BackgroundSlicingProcess::stop(), and Slic3r::BackgroundSlicingProcess::stop_internal().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_no_check_flag()
void Slic3r::PrintBase::set_no_check_flag (bool no_check) inline
{ m_no_check = no_check; }
References m_no_check.
Referenced by Slic3r::CLI::run().
set_plate_index()
void Slic3r::PrintBase::set_plate_index (int index) inline
{ m_plate_index = index; }
References m_plate_index.
Referenced by Slic3r::GUI::PartPlate::set_index().
set_plate_name()
void Slic3r::PrintBase::set_plate_name (const std::string & name) inline
{ m_plate_name = name; }
References m_plate_name.
Referenced by Slic3r::GUI::PartPlate::set_plate_name().
set_status()
void Slic3r::PrintBase::set_status (int percent, const std::string & message, unsigned int flags = SlicingStatus::DEFAULT, int warning_step = -1) const
{
  if (m_status_callback)
        m_status_callback(SlicingStatus(percent, message, flags, warning_step));
    else
        BOOST_LOG_TRIVIAL(debug) <<boost::format("Percent %1%: %2%\n")%percent %message.c_str();
}
References m_status_callback.
Referenced by Slic3r::BackgroundSlicingProcess::finalize_gcode(), Slic3r::PrintObject::make_perimeters(), Slic3r::SLAPrint::StatusReporter::operator()(), Slic3r::BackgroundSlicingProcess::prepare_upload(), Slic3r::BackgroundSlicingProcess::process_fff(), Slic3r::GCode::process_layers(), Slic3r::GCode::process_layers(), Slic3r::BackgroundSlicingProcess::process_sla(), and Slic3r::GUI::GLGizmoFdmSupports::run_thread().
set_status_callback()
void Slic3r::PrintBase::set_status_callback (status_callback_type cb) inline
{ m_status_callback = cb; }
References m_status_callback.
Referenced by Slic3r::CLI::run(), and Slic3r::GUI::PartPlate::update_slice_context().
set_status_default()
void Slic3r::PrintBase::set_status_default () inline
{ m_status_callback = nullptr; }
References m_status_callback.
set_status_silent()
void Slic3r::PrintBase::set_status_silent () inline
{ m_status_callback = [](const SlicingStatus&){}; }
References m_status_callback.
set_task()
virtual void Slic3r::PrintBase::set_task (const TaskParams & params) inline virtual
Reimplemented in Slic3r::SLAPrint.
{}
Referenced by Slic3r::BackgroundSlicingProcess::set_task().
state_mutex()
std::mutex & Slic3r::PrintBase::state_mutex () const inline protected
{ return m_state_mutex; }
References m_state_mutex.
Referenced by Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::active_step_add_warning(), Slic3r::SLAPrint::apply(), Slic3r::Print::clear(), Slic3r::SLAPrint::clear(), Slic3r::BackgroundSlicingProcess::is_step_done(), Slic3r::Print::is_step_done(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::is_step_done(), Slic3r::SLAPrint::is_step_done(), Slic3r::BackgroundSlicingProcess::reset_export(), Slic3r::BackgroundSlicingProcess::schedule_export(), Slic3r::BackgroundSlicingProcess::schedule_upload(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_done(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_started(), Slic3r::BackgroundSlicingProcess::set_step_done(), Slic3r::BackgroundSlicingProcess::set_step_started(), Slic3r::SLAPrint::set_task(), Slic3r::PrintObjectBase::state_mutex(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::step_state_with_timestamp(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::step_state_with_warnings(), and Slic3r::BackgroundSlicingProcess::stop_internal().
status_update_warnings() [1/2]
void Slic3r::PrintBase::status_update_warnings (int step, PrintStateBase::WarningLevel warning_level, const std::string & message, const PrintObjectBase * print_object = nullptr, PrintStateBase::SlicingNotificationType message_id = PrintStateBase::SlicingDefaultNotification) protected
{
    if (this->m_status_callback) {
        auto status = print_object ? SlicingStatus(*print_object, step, message, message_id) : SlicingStatus(*this, step, message, message_id);
        m_status_callback(status);
    }
    else if (! message.empty())
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Print warning: %1%\n")% message.c_str();
}
References m_status_callback.
Referenced by Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::active_step_add_warning(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_done(), and Slic3r::PrintObjectBase::status_update_warnings().
status_update_warnings() [2/2]
void Slic3r::PrintBase::status_update_warnings (int step, PrintStateBase::WarningLevel , const std::string & message, PrintObjectBase & object, PrintStateBase::SlicingNotificationType message_id = PrintStateBase::SlicingDefaultNotification) protected
{
    //BBS: add object it into slicing status
    if (this->m_status_callback) {
        m_status_callback(SlicingStatus(object, step, message, message_id));
    }
    else if (!message.empty())
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", PrintObject warning: %1%\n")% message.c_str();
}
References m_status_callback.
technology()
virtual PrinterTechnology Slic3r::PrintBase::technology () const pure virtual noexcept
Implemented in Slic3r::Print, and Slic3r::SLAPrint.
Referenced by Slic3r::BackgroundSlicingProcess::apply().
throw_if_canceled()
void Slic3r::PrintBase::throw_if_canceled () const inline protected
{ if (m_cancel_status.load(std::memory_order_acquire)) throw CanceledException(); }
References m_cancel_status.
Referenced by Slic3r::GCode::_do_export(), Slic3r::SLAPrint::Steps::generate_pad(), Slic3r::PrintObject::make_perimeters(), Slic3r::PrintTryCancel::operator()(), Slic3r::SLAPrint::process(), Slic3r::GCode::process_layers(), Slic3r::GCode::process_layers(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_done(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_started(), Slic3r::PrintObject::slice_support_volumes(), Slic3r::PrintObject::slice_volumes(), Slic3r::SLAPrint::Steps::support_points(), Slic3r::SLAPrint::Steps::support_tree(), and Slic3r::SLAPrint::Steps::throw_if_canceled().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
update_object_placeholders()
void Slic3r::PrintBase::update_object_placeholders (DynamicConfig & config, const std::string & default_ext) const protected
{
    // get the first input file name
    std::string input_file;
    std::vector<std::string> v_scale;
    int num_objects = 0;
    int num_instances = 0;
  for (const ModelObject *model_object : m_model.objects) {
    ModelInstance *printable = nullptr;
    for (ModelInstance *model_instance : model_object->instances)
      if (model_instance->is_printable()) {
        printable = model_instance;
        ++ num_instances;
      }
    if (printable) {
            ++ num_objects;
          // CHECK_ME -> Is the following correct ?
      v_scale.push_back("x:" + boost::lexical_cast<std::string>(printable->get_scaling_factor(X) * 100) +
        "% y:" + boost::lexical_cast<std::string>(printable->get_scaling_factor(Y) * 100) +
        "% z:" + boost::lexical_cast<std::string>(printable->get_scaling_factor(Z) * 100) + "%");
          if (input_file.empty())
              input_file = model_object->name.empty() ? model_object->input_file : model_object->name;
      }
    }
    config.set_key_value("num_objects", new ConfigOptionInt(num_objects));
    config.set_key_value("num_instances", new ConfigOptionInt(num_instances));
    config.set_key_value("scale", new ConfigOptionStrings(v_scale));
    if (! input_file.empty()) {
        // get basename with and without suffix
        const std::string input_filename = boost::filesystem::path(input_file).filename().string();
        const std::string input_filename_base = input_filename.substr(0, input_filename.find_last_of("."));
        config.set_key_value("input_filename", new ConfigOptionString(input_filename_base + default_ext));
        config.set_key_value("input_filename_base", new ConfigOptionString(input_filename_base));
    }
}
References Slic3r::ModelInstance::get_scaling_factor(), m_model, Slic3r::Model::objects, Slic3r::DynamicConfig::set_key_value(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by Slic3r::GCode::_do_export(), and output_filename().
validate()
virtual StringObjectException Slic3r::PrintBase::validate (StringObjectException * warning = nullptr, Polygons * collison_polygons = nullptr, std::vector< std::pair< Polygon, float > > * height_polygons = nullptr) const inline virtual
Reimplemented in Slic3r::Print, and Slic3r::SLAPrint.
{ return {}; }
Referenced by Slic3r::CLI::run(), and Slic3r::BackgroundSlicingProcess::validate().
Friends And Related Symbol Documentation
BackgroundSlicingProcess
friend class BackgroundSlicingProcess friend
PrintObjectBase
friend class PrintObjectBase friend
Member Data Documentation
m_cancel_callback
cancel_callback_type Slic3r::PrintBase::m_cancel_callback = [](){} private
Referenced by call_cancel_callback(), cancel_callback(), and set_cancel_callback().
m_cancel_status
std::atomic<CancelStatus> Slic3r::PrintBase::m_cancel_status private
Referenced by cancel(), cancel_internal(), cancel_status(), canceled(), restart(), and throw_if_canceled().
m_full_print_config
DynamicPrintConfig Slic3r::PrintBase::m_full_print_config protected
Referenced by Slic3r::SLAPrint::apply(), and full_print_config().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_model
Model Slic3r::PrintBase::m_model protected
Referenced by Slic3r::SLAPrint::apply(), Slic3r::Print::clear(), Slic3r::SLAPrint::clear(), Slic3r::Print::extruders(), model(), output_filepath(), and update_object_placeholders().
m_no_check
bool Slic3r::PrintBase::m_no_check = false protected
Referenced by get_no_check_flag(), and set_no_check_flag().
m_placeholder_parser
PlaceholderParser Slic3r::PrintBase::m_placeholder_parser protected
Referenced by Slic3r::SLAPrint::apply(), and placeholder_parser().
m_plate_index
int Slic3r::PrintBase::m_plate_index { 0 } protected
Referenced by get_plate_index(), and set_plate_index().
m_plate_name
std::string Slic3r::PrintBase::m_plate_name protected
Referenced by get_plate_name(), and set_plate_name().
m_state_mutex
std::mutex Slic3r::PrintBase::m_state_mutex mutable private
Referenced by state_mutex().
m_status_callback
status_callback_type Slic3r::PrintBase::m_status_callback protected
Referenced by set_status(), set_status_callback(), set_status_default(), set_status_silent(), status_update_warnings(), and status_update_warnings().
PrintTryCancel
friend Slic3r::PrintBase::PrintTryCancel private
Referenced by make_try_cancel().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
The documentation for this class was generated from the following files:
src/libslic3r/PrintBase.hpp
src/libslic3r/PrintBase.cpp