OrcaSlicer: Slic3r::ModelConfig Class Reference
Slic3r::ModelConfig Class Reference
#include <src/libslic3r/PrintConfig.hpp>
Public Member Functions
void reset ()
void assign_config (const ModelConfig &rhs)
void assign_config (ModelConfig &&rhs)
void assign_config (const DynamicPrintConfig &rhs)
void assign_config (DynamicPrintConfig &&rhs)
void apply (const ModelConfig &other, bool ignore_nonexistent=false)
void apply (const ConfigBase &other, bool ignore_nonexistent=false)
void apply_only (const ModelConfig &other, const t_config_option_keys &keys, bool ignore_nonexistent=false)
void apply_only (const ConfigBase &other, const t_config_option_keys &keys, bool ignore_nonexistent=false)
bool set_key_value (const std::string &opt_key, ConfigOption *opt)
template<typename T >
void set (const std::string &opt_key, T value)
void set_deserialize (const t_config_option_key &opt_key, const std::string &str, ConfigSubstitutionContext &substitution_context, bool append=false)
bool erase (const t_config_option_key &opt_key)
const DynamicPrintConfig & get () const throw ()
bool empty () const throw ()
size_t size () const throw ()
auto cbegin () const
auto cend () const
t_config_option_keys keys () const
bool has (const t_config_option_key &opt_key) const
const ConfigOption * option (const t_config_option_key &opt_key) const
int opt_int (const t_config_option_key &opt_key) const
int extruder () const
double opt_float (const t_config_option_key &opt_key) const
double get_abs_value (const t_config_option_key &opt_key) const
std::string opt_serialize (const t_config_option_key &opt_key) const
virtual uint64_t timestamp () const throw ()
bool timestamp_matches (const ModelConfig &rhs) const throw ()
void touch ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Private Attributes
uint64_t m_timestamp { 1 }
DynamicPrintConfig m_data
Static Private Attributes
static uint64_t s_last_timestamp = 1
Friends
class cereal::access
Detailed Description
Member Function Documentation
apply() [1/2]
void Slic3r::ModelConfig::apply (const ConfigBase & other, bool ignore_nonexistent = false) inline
{ m_data.apply_only(other, other.keys(), ignore_nonexistent); this->touch(); }
References Slic3r::ConfigBase::apply_only(), Slic3r::ConfigBase::keys(), m_data, and touch().
apply() [2/2]
void Slic3r::ModelConfig::apply (const ModelConfig & other, bool ignore_nonexistent = false) inline
{ this->apply(other.get(), ignore_nonexistent); }
References apply(), and get().
Referenced by apply(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), and Slic3r::ModelObject::split().
apply_only() [1/2]
void Slic3r::ModelConfig::apply_only (const ConfigBase & other, const t_config_option_keys & keys, bool ignore_nonexistent = false) inline
{ m_data.apply_only(other, keys, ignore_nonexistent); this->touch(); }
References Slic3r::ConfigBase::apply_only(), keys(), m_data, and touch().
apply_only() [2/2]
void Slic3r::ModelConfig::apply_only (const ModelConfig & other, const t_config_option_keys & keys, bool ignore_nonexistent = false) inline
{ this->apply_only(other.get(), keys, ignore_nonexistent); }
References apply_only(), get(), and keys().
Referenced by apply_only(), Slic3r::GUI::ObjectTableSettings::update_config_values(), and Slic3r::GUI::ObjectSettings::update_config_values().
assign_config() [1/4]
void Slic3r::ModelConfig::assign_config (const DynamicPrintConfig & rhs) inline
{ if (m_data != rhs) { m_data = rhs; this->touch(); } }
References m_data, and touch().
assign_config() [2/4]
void Slic3r::ModelConfig::assign_config (const ModelConfig & rhs) inline
{
        if (m_timestamp != rhs.m_timestamp) {
            m_data      = rhs.m_data;
            m_timestamp = rhs.m_timestamp;
        }
    }
References m_data, and m_timestamp.
Referenced by Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::convert_units(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::ObjectList::merge(), Slic3r::ModelObject::merge_volumes(), Slic3r::model_volume_list_copy_configs(), Slic3r::ModelObject::segment(), and Slic3r::ModelObject::split().
assign_config() [3/4]
void Slic3r::ModelConfig::assign_config (DynamicPrintConfig && rhs) inline
{ if (m_data != rhs) { m_data = std::move(rhs); this->touch(); } }
References m_data, and touch().
assign_config() [4/4]
void Slic3r::ModelConfig::assign_config (ModelConfig && rhs) inline
{
        if (m_timestamp != rhs.m_timestamp) {
            m_data      = std::move(rhs.m_data);
            m_timestamp = rhs.m_timestamp;
            rhs.reset();
        }
    }
References m_data, and m_timestamp.
cbegin()
auto Slic3r::ModelConfig::cbegin () const inline
{ return m_data.cbegin(); }
References Slic3r::DynamicConfig::cbegin(), and m_data.
cend()
auto Slic3r::ModelConfig::cend () const inline
{ return m_data.cend(); }
References Slic3r::DynamicConfig::cend(), and m_data.
empty()
bool Slic3r::ModelConfig::empty () const throw () inline
{ return m_data.empty(); }
References Slic3r::DynamicConfig::empty(), and m_data.
erase()
bool Slic3r::ModelConfig::erase (const t_config_option_key & opt_key) inline
{ bool out = m_data.erase(opt_key); if (out) this->touch(); return out; }
References Slic3r::DynamicConfig::erase(), m_data, out, and touch().
Referenced by Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::ObjectGridTable::reload_part_data(), Slic3r::GUI::ObjectTableSettings::resetAllValues(), Slic3r::GUI::ObjectList::update_filament_values_for_items(), Slic3r::GUI::ObjectGridTable::update_value_to_config(), and Slic3r::GUI::ObjectGridTable::update_volume_values_from_object().
extruder()
int Slic3r::ModelConfig::extruder () const inline
{ return opt_int("extruder"); }
References opt_int().
Referenced by Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::GUI::ObjectDataViewModel::AddObject(), Slic3r::GUI::MenuFactory::append_menu_item_change_extruder(), Slic3r::GUI::MenuFactory::append_menu_item_change_filament(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::del_subobject_from_object(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::Print::process(), and Slic3r::GUI::ObjectList::update_filament_values_for_items().
get()
const DynamicPrintConfig & Slic3r::ModelConfig::get () const throw () inline
{ return m_data; }
References m_data.
Referenced by Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::SLAPrint::apply(), apply(), apply_only(), Slic3r::GUI::ObjectList::copy_settings_to_clipboard(), Slic3r::GUI::ObjectList::del_subobject_from_object(), Slic3r::sla::find_least_supports_rotation(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::ObjectList::object_config_options_changed(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::Print::process(), Slic3r::GUI::ObjectTableSettings::resetAllValues(), Slic3r::GUI::ObjectSettings::update_config_values(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
get_abs_value()
double Slic3r::ModelConfig::get_abs_value (const t_config_option_key & opt_key) const inline
{
      return m_data.get_abs_value(opt_key);
    }
References Slic3r::ConfigBase::get_abs_value(), and m_data.
has()
bool Slic3r::ModelConfig::has (const t_config_option_key & opt_key) const inline
{ return m_data.has(opt_key); }
References Slic3r::ConfigOptionResolver::has(), and m_data.
Referenced by Slic3r::GUI::ObjectList::add_layer_item(), Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::GUI::ObjectTableSettings::add_missed_options(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::GUI::ObjectDataViewModel::AddObject(), Slic3r::GUI::MenuFactory::append_menu_item_change_extruder(), Slic3r::GUI::MenuFactory::append_menu_item_change_filament(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::ModelObject::get_config_value(), Slic3r::GUI::ObjectList::get_default_layer_config(), Slic3r::GUI::ObjectGridTable::get_volume_config_value(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::Print::process(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::ObjectTableSettings::update_extra_column_visible_status(), Slic3r::GUI::ObjectList::update_filament_values_for_items(), Slic3r::GUI::ObjectGridTable::update_value_to_config(), and Slic3r::GUI::ObjectTableSettings::ValueChanged().
keys()
t_config_option_keys Slic3r::ModelConfig::keys () const inline
{ return m_data.keys(); }
References Slic3r::DynamicConfig::keys(), and m_data.
Referenced by Slic3r::_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), apply_only(), apply_only(), Slic3r::GUI::create_settings_popupmenu(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::merge(), and Slic3r::GUI::ObjectSettings::update_config_values().
opt_float()
double Slic3r::ModelConfig::opt_float (const t_config_option_key & opt_key) const inline
{
      return m_data.opt_float(opt_key);
    }
References m_data, and Slic3r::DynamicConfig::opt_float().
Referenced by Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::edit_layer_range(), and Slic3r::GUI::ObjectList::get_default_layer_config().
opt_int()
int Slic3r::ModelConfig::opt_int (const t_config_option_key & opt_key) const inline
{ return m_data.opt_int(opt_key); }
References m_data, and Slic3r::DynamicConfig::opt_int().
Referenced by Slic3r::GUI::ObjectList::add_layer_item(), Slic3r::GUI::ObjectList::edit_layer_range(), extruder(), Slic3r::GUI::ObjectList::get_default_layer_config(), Slic3r::GUI::ObjectList::load_generic_subobject(), and Slic3r::GUI::ObjectList::load_modifier().
opt_serialize()
std::string Slic3r::ModelConfig::opt_serialize (const t_config_option_key & opt_key) const inline
{ return m_data.opt_serialize(opt_key); }
References m_data, and Slic3r::ConfigBase::opt_serialize().
Referenced by Slic3r::_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(), and Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive().
option()
const ConfigOption * Slic3r::ModelConfig::option (const t_config_option_key & opt_key) const inline
{ return m_data.option(opt_key); }
References m_data, and Slic3r::ConfigBase::option().
Referenced by Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::ModelVolume::extruder_id(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::ModelObject::get_config_value(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::ObjectGridTable::get_volume_config_value(), Slic3r::GUI::ObjectList::merge(), Slic3r::CLI::run(), Slic3r::GUI::ObjectList::split(), Slic3r::GUI::ObjectGridTable::update_volume_values_from_object(), and Slic3r::GUI::ObjectTableSettings::ValueChanged().
reset()
void Slic3r::ModelConfig::reset () inline
{ m_data.clear(); touch(); }
References Slic3r::DynamicConfig::clear(), m_data, and touch().
Referenced by Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::ModelObject::split(), and Slic3r::GUI::ObjectTableSettings::update_config_values().
serialize()
template<class Archive > void Slic3r::ModelConfig::serialize (Archive & ar) inline private
{ ar(m_timestamp); ar(m_data); }
References m_data, and m_timestamp.
set()
template<typename T > void Slic3r::ModelConfig::set (const std::string & opt_key, T value) inline
{ m_data.set(opt_key, value, true); this->touch(); }
References m_data, Slic3r::ConfigBase::set(), and touch().
Referenced by Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::ModelObject::segment(), and Slic3r::GUI::ObjectList::set_extruder_for_selected_items().
set_deserialize()
void Slic3r::ModelConfig::set_deserialize (const t_config_option_key & opt_key, const std::string & str, ConfigSubstitutionContext & substitution_context, bool append = false) inline
        { m_data.set_deserialize(opt_key, str, substitution_context, append); this->touch(); }
References Slic3r::append(), m_data, Slic3r::ConfigBase::set_deserialize(), and touch().
Referenced by Slic3r::_3MF_Importer::_load_model_from_file().
set_key_value()
bool Slic3r::ModelConfig::set_key_value (const std::string & opt_key, ConfigOption * opt) inline
{ bool out = m_data.set_key_value(opt_key, opt); this->touch(); return out; }
References m_data, out, Slic3r::DynamicConfig::set_key_value(), and touch().
Referenced by Slic3r::GUI::ObjectList::add_category_to_settings_from_frequent(), Slic3r::GUI::ObjectList::add_category_to_settings_from_selection(), Slic3r::GUI::ObjectSettings::add_missed_options(), Slic3r::GUI::ObjectTableSettings::add_missed_options(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::ObjectList::del_settings_from_config(), Slic3r::GUI::ObjectList::edit_layer_range(), Slic3r::GUI::ObjectList::get_default_layer_config(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::ObjectList::paste_settings_into_list(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::ObjectList::update_filament_in_config(), Slic3r::GUI::ObjectGridTable::update_filament_to_config(), and Slic3r::GUI::ObjectGridTable::update_value_to_config().
size()
size_t Slic3r::ModelConfig::size () const throw () inline
{ return m_data.size(); }
References m_data, and Slic3r::DynamicConfig::size().
timestamp()
virtual uint64_t Slic3r::ModelConfig::timestamp () const throw () inline virtual
Reimplemented in Slic3r::ModelConfigObject.
{ return m_timestamp; }
References m_timestamp.
Referenced by Slic3r::ModelConfigObject::timestamp().
timestamp_matches()
bool Slic3r::ModelConfig::timestamp_matches (const ModelConfig & rhs) const throw () inline
{ return m_timestamp == rhs.m_timestamp; }
References m_timestamp.
Referenced by Slic3r::Print::apply(), and Slic3r::SLAPrint::apply().
touch()
void Slic3r::ModelConfig::touch () inline
{ m_timestamp = ++ s_last_timestamp; }
References m_timestamp, and s_last_timestamp.
Referenced by apply(), apply_only(), assign_config(), assign_config(), Slic3r::GUI::ConfigOptionsGroup::change_opt_value(), erase(), Slic3r::GUI::ConfigOptionsGroup::on_change_OG(), reset(), set(), set_deserialize(), set_key_value(), Slic3r::GUI::ObjectGridTable::update_filament_to_config(), and Slic3r::GUI::ObjectGridTable::update_value_to_config().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Member Data Documentation
m_data
DynamicPrintConfig Slic3r::ModelConfig::m_data private
Referenced by apply(), apply_only(), assign_config(), assign_config(), assign_config(), assign_config(), cbegin(), cend(), empty(), erase(), get(), get_abs_value(), has(), keys(), opt_float(), opt_int(), opt_serialize(), option(), reset(), serialize(), set(), set_deserialize(), set_key_value(), and size().
m_timestamp
uint64_t Slic3r::ModelConfig::m_timestamp { 1 } private
Referenced by assign_config(), assign_config(), serialize(), timestamp(), timestamp_matches(), and touch().
s_last_timestamp
uint64_t Slic3r::ModelConfig::s_last_timestamp = 1 static private
Referenced by touch().
The documentation for this class was generated from the following files:
src/libslic3r/PrintConfig.hpp
src/libslic3r/PrintConfig.cpp