OrcaSlicer: orgQhull::QhullRidge_test Class Reference
orgQhull::QhullRidge_test Class Reference
Public Member Functions
Helper
void recordFailedTest ()
Static Public Member Functions
Class functions
static void deleteTests ()
static int runTests (QStringList arguments)
Static Protected Attributes
Class globals
static QList< RoadTest * > s_testcases
static int s_test_count = 0
! List of testcases to execute. Initialized via add_...()
static int s_test_fail = 0
! Total number of tests executed
static QStringList s_failed_tests
! Number of failed tests
Private Slots
Test slots
void cleanup ()
void t_construct ()
void t_getSet ()
void t_foreach ()
void t_io ()
Detailed Description
Member Function Documentation
cleanup
void orgQhull::QhullRidge_test::cleanup () private slot
{
    RoadTest::cleanup();
}
References orgQhull::RoadTest::cleanup().
deleteTests()
void orgQhull::RoadTest::deleteTests () static inherited
{
    foreach(RoadTest *testcase, s_testcases){
        delete testcase;
    }
    s_failed_tests.clear();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
recordFailedTest()
void orgQhull::RoadTest::recordFailedTest () inherited
{
    s_test_fail++;
    QString className= metaObject()->className();
    s_failed_tests << className + "::" + QTest::currentTestFunction();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_test_fail.
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
runTests()
int orgQhull::RoadTest::runTests (QStringList arguments) static inherited
{
    int result= 0; // assume success
    foreach(RoadTest *testcase, s_testcases){
        try{
            result += QTest::qExec(testcase, arguments);
        }catch(const std::exception &e){
            cout << "FAIL!  : Threw error ";
            cout << e.what() << endl;
    s_test_count++;
            testcase->recordFailedTest();
            // Qt 4.5.2 OK.  In Qt 4.3.3, qtestcase did not clear currentTestObject
        }
    }
    if(s_test_fail){
        cout << "Failed " << s_test_fail << " of " << s_test_count << " tests.\n";
        cout << s_failed_tests.join("\n").toLocal8Bit().constData() << std::endl;
    }else{
        cout << "Passed " << s_test_count << " tests.\n";
    }
    return result;
}//runTests
References orgQhull::RoadTest::recordFailedTest(), orgQhull::RoadTest::s_failed_tests, orgQhull::RoadTest::s_test_count, orgQhull::RoadTest::s_test_fail, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
t_construct
void orgQhull::QhullRidge_test::t_construct () private slot
{
    // Qhull.runQhull() constructs QhullFacets as facetT
    RboxPoints rcube("c");
    Qhull q(rcube,"QR0");  // triangulation of rotated unit cube
    QhullRidge r(q);
    QVERIFY(!r.isValid());
    QCOMPARE(r.dimension(),2);
    QhullFacet f(q.firstFacet());
    QhullRidgeSet rs(f.ridges());
    QVERIFY(!rs.isEmpty()); // Simplicial facets do not have ridges()
    QhullRidge r2(rs.first());
    QCOMPARE(r2.dimension(), 2); // One dimension lower than the facet
    r= r2;
    QVERIFY(r.isValid());
    QCOMPARE(r.dimension(), 2);
    QhullRidge r3(q, r2.getRidgeT());
    QCOMPARE(r,r3);
    QhullRidge r4(q, r2.getBaseT());
    QCOMPARE(r,r4);
    QhullRidge r5= r2; // copy constructor
    QVERIFY(r5==r2);
    QVERIFY(r5==r);
}//t_construct
References orgQhull::QhullRidge::dimension(), orgQhull::QhullSet< T >::first(), orgQhull::Qhull::firstFacet(), orgQhull::QhullRidge::getBaseT(), orgQhull::QhullRidge::getRidgeT(), orgQhull::QhullSet< T >::isEmpty(), orgQhull::QhullRidge::isValid(), and orgQhull::QhullFacet::ridges().
t_foreach
void orgQhull::QhullRidge_test::t_foreach () private slot
{
    RboxPoints rcube("c");  // cube
    {
        Qhull q(rcube, "QR0"); // rotated cube
        QhullFacet f(q.firstFacet());
        foreach (const QhullRidge &r, f.ridges()){  // Qt only
            QhullVertexSet vs= r.vertices();
            QCOMPARE(vs.count(), 2);
            foreach (const QhullVertex &v, vs){  // Qt only
                QVERIFY(f.vertices().contains(v));
            }
        }
        QhullRidgeSet rs= f.ridges();
        QhullRidge r= rs.first();
        QhullRidge r2= r;
        QList<QhullVertex> vs;
        int count= 0;
        while(!count || r2!=r){
            ++count;
            QhullVertex v(q);
            QVERIFY2(r2.hasNextRidge3d(f),"A cube should only have non-simplicial facets.");
            QhullRidge r3= r2.nextRidge3d(f, &v);
            QVERIFY(!vs.contains(v));
            vs << v;
            r2= r2.nextRidge3d(f);
            QCOMPARE(r3, r2);
        }
        QCOMPARE(vs.count(), rs.count());
        QCOMPARE(count, rs.count());
    }
}//t_foreach
References orgQhull::QhullSet< T >::contains(), orgQhull::QhullSet< T >::count(), count, orgQhull::QhullSet< T >::first(), orgQhull::Qhull::firstFacet(), orgQhull::QhullRidge::hasNextRidge3d(), orgQhull::QhullRidge::nextRidge3d(), orgQhull::QhullFacet::ridges(), orgQhull::QhullFacet::vertices(), and orgQhull::QhullRidge::vertices().
t_getSet
void orgQhull::QhullRidge_test::t_getSet () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q(rcube,"QR0");  // triangulation of rotated unit cube
        QCOMPARE(q.facetCount(), 6);
        QCOMPARE(q.vertexCount(), 8);
        QhullFacet f(q.firstFacet());
        QhullRidgeSet rs= f.ridges();
        QhullRidgeSetIterator i(rs);
        while(i.hasNext()){
            const QhullRidge r= i.next();
            cout << r.id() << endl;
            QVERIFY(r.bottomFacet()!=r.topFacet());
            QCOMPARE(r.dimension(), 2); // Ridge one-dimension less than facet
            QVERIFY(r.id()>=0 && r.id()<9*27);
            QVERIFY(r.isValid());
            QVERIFY(r==r);
            QVERIFY(r==i.peekPrevious());
            QCOMPARE(r.otherFacet(r.bottomFacet()),r.topFacet());
            QCOMPARE(r.otherFacet(r.topFacet()),r.bottomFacet());
        }
    }
}//t_getSet
References orgQhull::QhullRidge::bottomFacet(), orgQhull::QhullRidge::dimension(), orgQhull::Qhull::facetCount(), orgQhull::Qhull::firstFacet(), orgQhull::QhullSetIterator< T >::hasNext(), orgQhull::QhullRidge::id(), orgQhull::QhullRidge::isValid(), orgQhull::QhullSetIterator< T >::next(), orgQhull::QhullRidge::otherFacet(), orgQhull::QhullSetIterator< T >::peekPrevious(), orgQhull::QhullFacet::ridges(), orgQhull::QhullRidge::topFacet(), and orgQhull::Qhull::vertexCount().
t_io
void orgQhull::QhullRidge_test::t_io () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q(rcube, "");
        QhullFacet f(q.firstFacet());
        QhullRidgeSet rs= f.ridges();
        QhullRidge r= rs.first();
        ostringstream os;
        os << "Ridges\n" << rs << "Ridge\n" << r;
        os << r.print("\nRidge with message");
        cout << os.str();
        QString s= QString::fromStdString(os.str());
        QCOMPARE(s.count(" r"), 6);
    }
}//t_io
References orgQhull::QhullSet< T >::first(), orgQhull::Qhull::firstFacet(), orgQhull::QhullRidge::print(), and orgQhull::QhullFacet::ridges().
Member Data Documentation
s_failed_tests
QStringList orgQhull::RoadTest::s_failed_tests static protected inherited
! Number of failed tests
Referenced by orgQhull::RoadTest::deleteTests(), orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_test_count
int orgQhull::RoadTest::s_test_count = 0 static protected inherited
! List of testcases to execute. Initialized via add_...()
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
s_test_fail
int orgQhull::RoadTest::s_test_fail = 0 static protected inherited
! Total number of tests executed
Referenced by orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_testcases
QList< RoadTest * > orgQhull::RoadTest::s_testcases static protected inherited
Referenced by orgQhull::RoadTest::RoadTest(), orgQhull::RoadTest::deleteTests(), and orgQhull::RoadTest::runTests().
The documentation for this class was generated from the following file:
src/qhull/src/qhulltest/QhullRidge_test.cpp