OrcaSlicer: orgQhull::QhullSetIterator< T > Class Template Reference
orgQhull::QhullSetIterator< T > Class Template Reference
Faster then interator/const_iterator due to T::base_type.
#include <src/qhull/src/libqhullcpp/QhullSet.h>
Public Member Functions
Constructors
QhullSetIterator (const QhullSet< T > &s)
QhullSetIterator (const QhullSetIterator< T > &o)
QhullSetIterator< T > & operator= (const QhullSetIterator< T > &o)
ReadOnly
countT countRemaining ()
Search
bool findNext (const T &t)
bool findPrevious (const T &t)
Foreach
bool hasNext () const
bool hasPrevious () const
T next ()
T peekNext () const
T peekPrevious () const
T previous ()
void toBack ()
void toFront ()
Private Types
Subtypes
typedef QhullSet< T >::const_iterator const_iterator
Private Attributes
Fields
const T::base_type * i
const T::base_type * begin_i
const T::base_type * end_i
QhullQh * qh_qh
Detailed Description
template<typename T>
class orgQhull::QhullSetIterator< T >
Faster then interator/const_iterator due to T::base_type.
Member Typedef Documentation
const_iterator
template<typename T > typedef QhullSet<T>::const_iterator orgQhull::QhullSetIterator< T >::const_iterator private
Constructor & Destructor Documentation
QhullSetIterator() [1/2]
template<typename T > orgQhull::QhullSetIterator< T >::QhullSetIterator (const QhullSet< T > & s) inline
: i(s.data()), begin_i(i), end_i(s.endData()), qh_qh(s.qh()) {}
QhullSetIterator() [2/2]
template<typename T > orgQhull::QhullSetIterator< T >::QhullSetIterator (const QhullSetIterator< T > & o) inline
: i(o.i), begin_i(o.begin_i), end_i(o.end_i), qh_qh(o.qh_qh) {}
Member Function Documentation
countRemaining()
template<typename T > countT orgQhull::QhullSetIterator< T >::countRemaining () inline
{ return (countT)(end_i-i); } // WARN64
References orgQhull::QhullSetIterator< T >::end_i, and orgQhull::QhullSetIterator< T >::i.
Referenced by orgQhull::QhullPointSet_test::t_pointset_iterator().
findNext()
template<typename T > bool orgQhull::QhullSetIterator< T >::findNext (const T & t)
{
    typename T::base_type p= t.getBaseT();
    while(i!=end_i){
        if(*(++i)==p){
            return true;
        }
    }
    return false;
}//findNext
findPrevious()
template<typename T > bool orgQhull::QhullSetIterator< T >::findPrevious (const T & t)
{
    typename T::base_type p= t.getBaseT();
    while(i!=begin_i){
        if(*(--i)==p){
            return true;
        }
    }
    return false;
}//findPrevious
hasNext()
template<typename T > bool orgQhull::QhullSetIterator< T >::hasNext () const inline
{ return i != end_i; }
References orgQhull::QhullSetIterator< T >::end_i, and orgQhull::QhullSetIterator< T >::i.
Referenced by orgQhull::QhullRidge_test::t_getSet(), orgQhull::QhullPointSet_test::t_pointset_iterator(), orgQhull::QhullSet_test::t_qhullset_iterator(), orgQhull::QhullFacetSet::toStdVector(), and orgQhull::QhullVertexSet::toStdVector().
hasPrevious()
template<typename T > bool orgQhull::QhullSetIterator< T >::hasPrevious () const inline
{ return i != begin_i; }
References orgQhull::QhullSetIterator< T >::begin_i, and orgQhull::QhullSetIterator< T >::i.
Referenced by orgQhull::QhullPointSet_test::t_pointset_iterator(), and orgQhull::QhullSet_test::t_qhullset_iterator().
next()
template<typename T > T orgQhull::QhullSetIterator< T >::next () inline
{ return T(qh_qh, *i++); }
References orgQhull::QhullSetIterator< T >::i, and orgQhull::QhullSetIterator< T >::qh_qh.
Referenced by orgQhull::QhullRidge_test::t_getSet(), orgQhull::QhullPointSet_test::t_pointset_iterator(), orgQhull::QhullSet_test::t_qhullset_iterator(), orgQhull::QhullFacetSet::toStdVector(), and orgQhull::QhullVertexSet::toStdVector().
operator=()
template<typename T > QhullSetIterator< T > & orgQhull::QhullSetIterator< T >::operator= (const QhullSetIterator< T > & o) inline
{ i= o.i; begin_i= o.begin_i; end_i= o.end_i; qh_qh= o.qh_qh; return *this; }
References orgQhull::QhullSetIterator< T >::begin_i, orgQhull::QhullSetIterator< T >::end_i, orgQhull::QhullSetIterator< T >::i, and orgQhull::QhullSetIterator< T >::qh_qh.
peekNext()
template<typename T > T orgQhull::QhullSetIterator< T >::peekNext () const inline
{ return T(qh_qh, *i); }
References orgQhull::QhullSetIterator< T >::i, and orgQhull::QhullSetIterator< T >::qh_qh.
Referenced by orgQhull::QhullPointSet_test::t_pointset_iterator(), and orgQhull::QhullSet_test::t_qhullset_iterator().
peekPrevious()
template<typename T > T orgQhull::QhullSetIterator< T >::peekPrevious () const inline
{ const typename T::base_type *p = i; return T(qh_qh, *--p); }
References orgQhull::QhullSetIterator< T >::i, and orgQhull::QhullSetIterator< T >::qh_qh.
Referenced by orgQhull::QhullRidge_test::t_getSet(), orgQhull::QhullPointSet_test::t_pointset_iterator(), and orgQhull::QhullSet_test::t_qhullset_iterator().
previous()
template<typename T > T orgQhull::QhullSetIterator< T >::previous () inline
{ return T(qh_qh, *--i); }
References orgQhull::QhullSetIterator< T >::i, and orgQhull::QhullSetIterator< T >::qh_qh.
Referenced by orgQhull::QhullPointSet_test::t_pointset_iterator(), and orgQhull::QhullSet_test::t_qhullset_iterator().
toBack()
template<typename T > void orgQhull::QhullSetIterator< T >::toBack () inline
{ i = end_i; }
References orgQhull::QhullSetIterator< T >::end_i, and orgQhull::QhullSetIterator< T >::i.
Referenced by orgQhull::QhullPointSet_test::t_pointset_iterator(), and orgQhull::QhullSet_test::t_qhullset_iterator().
toFront()
template<typename T > void orgQhull::QhullSetIterator< T >::toFront () inline
{ i = begin_i; }
References orgQhull::QhullSetIterator< T >::begin_i, and orgQhull::QhullSetIterator< T >::i.
Referenced by orgQhull::QhullPointSet_test::t_pointset_iterator(), and orgQhull::QhullSet_test::t_qhullset_iterator().
Member Data Documentation
begin_i
template<typename T > const T::base_type* orgQhull::QhullSetIterator< T >::begin_i private
Referenced by orgQhull::QhullSetIterator< T >::hasPrevious(), orgQhull::QhullSetIterator< T >::operator=(), and orgQhull::QhullSetIterator< T >::toFront().
end_i
template<typename T > const T::base_type* orgQhull::QhullSetIterator< T >::end_i private
Referenced by orgQhull::QhullSetIterator< T >::countRemaining(), orgQhull::QhullSetIterator< T >::hasNext(), orgQhull::QhullSetIterator< T >::operator=(), and orgQhull::QhullSetIterator< T >::toBack().
i
template<typename T > const T::base_type* orgQhull::QhullSetIterator< T >::i private
Referenced by orgQhull::QhullSetIterator< T >::countRemaining(), orgQhull::QhullSetIterator< T >::hasNext(), orgQhull::QhullSetIterator< T >::hasPrevious(), orgQhull::QhullSetIterator< T >::next(), orgQhull::QhullSetIterator< T >::operator=(), orgQhull::QhullSetIterator< T >::peekNext(), orgQhull::QhullSetIterator< T >::peekPrevious(), orgQhull::QhullSetIterator< T >::previous(), orgQhull::QhullSetIterator< T >::toBack(), and orgQhull::QhullSetIterator< T >::toFront().
qh_qh
template<typename T > QhullQh* orgQhull::QhullSetIterator< T >::qh_qh private
Referenced by orgQhull::QhullSetIterator< T >::next(), orgQhull::QhullSetIterator< T >::operator=(), orgQhull::QhullSetIterator< T >::peekNext(), orgQhull::QhullSetIterator< T >::peekPrevious(), and orgQhull::QhullSetIterator< T >::previous().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullSet.h