OrcaSlicer: Slic3r::GUI::MarkdownTip Class Reference
Slic3r::GUI::MarkdownTip Class Reference
#include <src/slic3r/GUI/MarkdownTip.hpp>
Static Public Member Functions
static bool ShowTip (std::string const &tip, std::string const &tooltip, wxPoint pos)
static void ExitTip ()
static void Reload ()
static void Recreate (wxWindow *parent)
static wxWindow * AttachTo (wxWindow *parent)
static wxWindow * DetachFrom (wxWindow *parent)
Private Member Functions
MarkdownTip ()
~MarkdownTip ()
void LoadStyle ()
bool ShowTip (wxPoint pos, std::string const &tip, std::string const &tooltip)
std::string LoadTip (std::string const &tip, std::string const &tooltip)
void RunScript (std::string const &script)
wxWebView * CreateTipView (wxWindow *parent)
void OnLoaded (wxWebViewEvent &event)
void OnTitleChanged (wxWebViewEvent &event)
void OnError (wxWebViewEvent &event)
void OnTimer (wxTimerEvent &event)
Static Private Member Functions
static MarkdownTip * markdownTip (bool create=true)
Private Attributes
wxWebView * _tipView = nullptr
std::string _lastTip
std::string _pendingScript = " "
std::string _language
wxPoint _requestPos
double _lastHeight = 0
wxTimer * _timer = nullptr
bool _hide = false
bool _data_dir = false
Detailed Description
Constructor & Destructor Documentation
MarkdownTip()
Slic3r::GUI::MarkdownTip::MarkdownTip () private
    : wxPopupTransientWindow(wxGetApp().mainframe, wxBORDER_NONE)
{
    wxBoxSizer* topsizer = new wxBoxSizer(wxVERTICAL);
    _tipView = CreateTipView(this);
    topsizer->Add(_tipView, wxSizerFlags().Expand().Proportion(1));
    SetSizer(topsizer);
    SetSize({400, 300});
    LoadStyle();
    _timer = new wxTimer;
    _timer->Bind(wxEVT_TIMER, &MarkdownTip::OnTimer, this);
}
References _timer, _tipView, CreateTipView(), LoadStyle(), and OnTimer().
Referenced by markdownTip().
~MarkdownTip()
Slic3r::GUI::MarkdownTip::~MarkdownTip () private
{ delete _timer; }
References _timer.
Member Function Documentation
AttachTo()
wxWindow * Slic3r::GUI::MarkdownTip::AttachTo (wxWindow * parent) static
{
    MarkdownTip& tip = *markdownTip();
    tip._tipView = tip.CreateTipView(parent);
    tip._pendingScript = " ";
    return tip._tipView;
}
References _pendingScript, _tipView, CreateTipView(), and markdownTip().
CreateTipView()
wxWebView * Slic3r::GUI::MarkdownTip::CreateTipView (wxWindow * parent) private
{
    wxWebView *tipView = WebView::CreateWebView(parent, "");
    Bind(wxEVT_WEBVIEW_LOADED, &MarkdownTip::OnLoaded, this);
    Bind(wxEVT_WEBVIEW_TITLE_CHANGED, &MarkdownTip::OnTitleChanged, this);
    Bind(wxEVT_WEBVIEW_ERROR, &MarkdownTip::OnError, this);
    return tipView;
}
References WebView::CreateWebView(), OnError(), OnLoaded(), and OnTitleChanged().
Referenced by MarkdownTip(), and AttachTo().
DetachFrom()
wxWindow * Slic3r::GUI::MarkdownTip::DetachFrom (wxWindow * parent) static
{
    MarkdownTip& tip = *markdownTip();
    if (tip._tipView->GetParent() == parent) {
        tip.Destroy();
    }
    return NULL;
}
References _tipView, markdownTip(), and NULL.
ExitTip()
void Slic3r::GUI::MarkdownTip::ExitTip () static
{
    //if (auto tip = markdownTip(false))
    //    tip->Destroy();
}
Referenced by Slic3r::GUI::MainFrame::MainFrame().
LoadStyle()
void Slic3r::GUI::MarkdownTip::LoadStyle () private
{
    _language = GUI::into_u8(GUI::wxGetApp().current_language_code());
    fs::path ph(data_dir());
    ph /= "resources/tooltip/common/styled.html";
    _data_dir = true;
    if (!fs::exists(ph)) {
        ph = resources_dir();
        ph /= "tooltip/styled.html";
        _data_dir = false;
    }
    auto url = ph.string();
    std::replace(url.begin(), url.end(), '\\', '/');
    url = "file:///" + url;
    _tipView->LoadURL(from_u8(url));
    _lastTip.clear();
}
References _data_dir, _language, _lastTip, _tipView, Slic3r::data_dir(), Slic3r::GUI::from_u8(), Slic3r::GUI::into_u8(), and Slic3r::resources_dir().
Referenced by MarkdownTip().
LoadTip()
std::string Slic3r::GUI::MarkdownTip::LoadTip (std::string const & tip, std::string const & tooltip) private
{
    fs::path ph;
    wxString file;
    wxFile   f;
    if (_data_dir) {
        if (!_language.empty()) {
            ph = data_dir();
            ph /= "resources/tooltip/" + _language +  "/" + tip + ".md";
            file = from_u8(ph.string());
            if (wxFile::Exists(file) && f.Open(file)) {
                std::string content(f.Length(), 0);
                f.Read(&content[0], content.size());
                return content;
            }
        }
        ph = data_dir();
        ph /= "resources/tooltip/common/" + tip + ".md";
        file = from_u8(ph.string());
        if (wxFile::Exists(file) && f.Open(file)) {
            std::string content(f.Length(), 0);
            f.Read(&content[0], content.size());
            return content;
        }
    }
    /*
    file = var("tooltips.zip");
    if (wxFile::Exists(file) && f.Open(file)) {
        wxFileInputStream fs(f);
        wxZipInputStream zip(fs);
        file = tip + ".md";
        while (auto e = zip.GetNextEntry()) {
            if (e->GetName() == file) {
                if (zip.OpenEntry(*e)) {
                    std::string content(f.Length(), 0);
                    zip.Read(&content[0], content.size());
                    return content;
                }
                break;
            }
        }
    }
    */
    ph = resources_dir();
    ph /= "tooltip/" + _language + "/" + tip + ".md";
    file = from_u8(ph.string());
    if (wxFile::Exists(file) && f.Open(file)) {
        std::string content(f.Length(), 0);
        f.Read(&content[0], content.size());
        return content;
    }
    ph = resources_dir();
    ph /= "tooltip/" + tip + ".md";
    file = from_u8(ph.string());
    if (wxFile::Exists(file) && f.Open(file)) {
        std::string content(f.Length(), 0);
        f.Read(&content[0], content.size());
        return content;
    }
    if (!tooltip.empty()) return "#### " + _utf8(tip) + "\n" + tooltip;
    return (_tipView->GetParent() == this && tip.empty()) ? "" : LoadTip("", "");
}
References _data_dir, _language, _tipView, _utf8, Slic3r::data_dir(), Slic3r::f(), Slic3r::GUI::from_u8(), LoadTip(), and Slic3r::resources_dir().
Referenced by LoadTip(), and ShowTip().
markdownTip()
MarkdownTip * Slic3r::GUI::MarkdownTip::markdownTip (bool create = true) static private
{
    static MarkdownTip * markdownTip = nullptr;
    if (markdownTip == nullptr && create)
        markdownTip = new MarkdownTip;
    return markdownTip;
}
References MarkdownTip(), and markdownTip().
Referenced by AttachTo(), DetachFrom(), markdownTip(), Recreate(), Reload(), and ShowTip().
OnError()
void Slic3r::GUI::MarkdownTip::OnError (wxWebViewEvent & event) private
{
}
Referenced by CreateTipView().
OnLoaded()
void Slic3r::GUI::MarkdownTip::OnLoaded (wxWebViewEvent & event) private
{
}
Referenced by CreateTipView().
OnTimer()
void Slic3r::GUI::MarkdownTip::OnTimer (wxTimerEvent & event) private
{
    if (_hide) {
        wxPoint pos = ScreenToClient(wxGetMousePosition());
        if (GetClientRect().Contains(pos)) {
            BOOST_LOG_TRIVIAL(info) << "MarkdownTip::OnTimer: restart hide timer...";
            _timer->StartOnce();
            return;
        }
        BOOST_LOG_TRIVIAL(info) << "MarkdownTip::OnTimer: hide.";
        this->Hide();
    } else {
        BOOST_LOG_TRIVIAL(info) << "MarkdownTip::OnTimer: show.";
        this->Show();
    }
}
References _hide, and _timer.
Referenced by MarkdownTip().
OnTitleChanged()
void Slic3r::GUI::MarkdownTip::OnTitleChanged (wxWebViewEvent & event) private
{
    if (!_pendingScript.empty()) {
        RunScript(_pendingScript);
        _pendingScript.clear();
        return;
    }
#ifdef __linux__
    wxString str = "0";
#else
    wxString str = event.GetString();
#endif
    double height = 0;
    if (str.ToDouble(&height)) {
        if (height > _lastHeight - 10 && height < _lastHeight + 10)
            return;
        _lastHeight = height;
        height *= 1.25; height += 50;
        wxSize size = wxDisplay(this).GetClientArea().GetSize();
        if (height > size.y)
            height = size.y;
        wxPoint pos = _requestPos;
        if (pos.y + height > size.y)
            pos.y = size.y - height;
        this->SetSize({ 400, (int)height });
        this->SetPosition(pos);
    }
}
References _lastHeight, _pendingScript, _requestPos, int, RunScript(), and size.
Referenced by CreateTipView().
Recreate()
void Slic3r::GUI::MarkdownTip::Recreate (wxWindow * parent) static
{
    if (auto tip = markdownTip(false)) {
        tip->Reparent(parent);
        tip->LoadStyle(); // switch language
    }
}
References markdownTip().
Referenced by Slic3r::GUI::MainFrame::MainFrame().
Reload()
void Slic3r::GUI::MarkdownTip::Reload () static
{
    if (auto tip = markdownTip(false))
        tip->LoadStyle();
}
References markdownTip().
Referenced by Slic3r::PresetUpdater::priv::sync_tooltip().
RunScript()
void Slic3r::GUI::MarkdownTip::RunScript (std::string const & script) private
{
    WebView::RunScript(_tipView, script);
}
References _tipView, and WebView::RunScript().
Referenced by OnTitleChanged(), and ShowTip().
ShowTip() [1/2]
bool Slic3r::GUI::MarkdownTip::ShowTip (std::string const & tip, std::string const & tooltip, wxPoint pos) static
{
#ifdef NDEBUG
    return false;
#endif
    return markdownTip()->ShowTip(pos, tip, tooltip);
}
References markdownTip(), and ShowTip().
Referenced by Slic3r::GUI::OG_CustomCtrl::OnLeaveWin(), Slic3r::GUI::OG_CustomCtrl::OnMotion(), and ShowTip().
ShowTip() [2/2]
bool Slic3r::GUI::MarkdownTip::ShowTip (wxPoint pos, std::string const & tip, std::string const & tooltip) private
{
    if (tip.empty()) {
        if (_tipView->GetParent() != this)
            return false;
        if (pos.x) {
            _hide = true;
            BOOST_LOG_TRIVIAL(info) << "MarkdownTip::ShowTip: hide soon on empty tip.";
            this->Hide();
        }
        else if (!_hide) {
            _hide = true;
            BOOST_LOG_TRIVIAL(info) << "MarkdownTip::ShowTip: start hide timer (300)...";
            _timer->StartOnce(300);
        }
        return false;
    }
    bool tipChanged = _lastTip != tip;
    if (tipChanged) {
        auto content = LoadTip(tip, tooltip);
        if (content.empty()) {
            _hide = true;
            this->Hide();
            BOOST_LOG_TRIVIAL(info) << "MarkdownTip::ShowTip: hide soon on empty content.";
            return false;
        }
        auto script = "window.showMarkdown('" + url_encode(content) + "', true);";
        if (!_pendingScript.empty()) {
            _pendingScript = script;
        }
        else {
            RunScript(script);
        }
        _lastTip = tip;
        if (_tipView->GetParent() == this)
            this->Hide();
    }
    if (_tipView->GetParent() == this) {
        wxSize size = wxDisplay(this).GetClientArea().GetSize();
        _requestPos = pos;
        if (pos.y + this->GetSize().y > size.y)
            pos.y = size.y - this->GetSize().y;
        this->SetPosition(pos);
        if (tipChanged || _hide) {
            _hide = false;
            BOOST_LOG_TRIVIAL(info) << "MarkdownTip::ShowTip: start show timer (500)...";
            _timer->StartOnce(500);
        }
    }
    return true;
}
References _hide, _lastTip, _pendingScript, _requestPos, _timer, _tipView, LoadTip(), RunScript(), size, and Slic3r::GUI::url_encode().
Member Data Documentation
_data_dir
bool Slic3r::GUI::MarkdownTip::_data_dir = false private
Referenced by LoadStyle(), and LoadTip().
_hide
bool Slic3r::GUI::MarkdownTip::_hide = false private
Referenced by OnTimer(), and ShowTip().
_language
std::string Slic3r::GUI::MarkdownTip::_language private
Referenced by LoadStyle(), and LoadTip().
_lastHeight
double Slic3r::GUI::MarkdownTip::_lastHeight = 0 private
Referenced by OnTitleChanged().
_lastTip
std::string Slic3r::GUI::MarkdownTip::_lastTip private
Referenced by LoadStyle(), and ShowTip().
_pendingScript
std::string Slic3r::GUI::MarkdownTip::_pendingScript = " " private
Referenced by AttachTo(), OnTitleChanged(), and ShowTip().
_requestPos
wxPoint Slic3r::GUI::MarkdownTip::_requestPos private
Referenced by OnTitleChanged(), and ShowTip().
_timer
wxTimer* Slic3r::GUI::MarkdownTip::_timer = nullptr private
Referenced by MarkdownTip(), ~MarkdownTip(), OnTimer(), and ShowTip().
_tipView
wxWebView* Slic3r::GUI::MarkdownTip::_tipView = nullptr private
Referenced by MarkdownTip(), AttachTo(), DetachFrom(), LoadStyle(), LoadTip(), RunScript(), and ShowTip().
The documentation for this class was generated from the following files:
src/slic3r/GUI/MarkdownTip.hpp
src/slic3r/GUI/MarkdownTip.cpp