OrcaSlicer: Slic3r::GUI::PlaterDropTarget Class Reference
Slic3r::GUI::PlaterDropTarget Class Reference
Public Member Functions
PlaterDropTarget (Plater *plater)
virtual bool OnDropFiles (wxCoord x, wxCoord y, const wxArrayString &filenames)
void handleOnIdle (wxIdleEvent &event)
Private Attributes
Plater * m_plater
wxArrayString m_filenames
Detailed Description
Constructor & Destructor Documentation
PlaterDropTarget()
Slic3r::GUI::PlaterDropTarget::PlaterDropTarget (Plater * plater) inline
: m_plater(plater) { this->SetDefaultAction(wxDragCopy); }
Member Function Documentation
handleOnIdle()
void Slic3r::GUI::PlaterDropTarget::handleOnIdle (wxIdleEvent & event)
{
    wxGetApp().mainframe->Raise();
    wxGetApp().Unbind(wxEVT_IDLE, &PlaterDropTarget::handleOnIdle, this);
    if (m_plater != nullptr) {
        m_plater->load_files(m_filenames);
        wxGetApp().mainframe->update_title();
    }
    //m_filenames.clear();
}
References handleOnIdle(), Slic3r::GUI::Plater::load_files(), m_filenames, and m_plater.
Referenced by handleOnIdle(), and OnDropFiles().
OnDropFiles()
bool Slic3r::GUI::PlaterDropTarget::OnDropFiles (wxCoord x, wxCoord y, const wxArrayString & filenames) virtual
{
#ifdef WIN32
    // hides the system icon
    this->MSWUpdateDragImageOnLeave();
#endif // WIN32
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": drag %1% files into app")%filenames.size();
    m_filenames = filenames;
    wxGetApp().Bind(wxEVT_IDLE, &PlaterDropTarget::handleOnIdle, this);
    return true;
}
References handleOnIdle(), and m_filenames.
Member Data Documentation
m_filenames
wxArrayString Slic3r::GUI::PlaterDropTarget::m_filenames private
Referenced by handleOnIdle(), and OnDropFiles().
m_plater
Plater* Slic3r::GUI::PlaterDropTarget::m_plater private
Referenced by handleOnIdle().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Plater.cpp