OrcaSlicer: Slic3r::GUI::MediaPlayCtrl Class Reference
Slic3r::GUI::MediaPlayCtrl Class Reference
#include <src/slic3r/GUI/MediaPlayCtrl.h>
Public Member Functions
MediaPlayCtrl (wxWindow *parent, wxMediaCtrl2 *media_ctrl, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~MediaPlayCtrl ()
void SetMachineObject (MachineObject *obj)
bool IsStreaming () const
void ToggleStream ()
Protected Member Functions
void onStateChanged (wxMediaEvent &event)
void Play ()
void Stop (wxString const &msg={})
void TogglePlay ()
void SetStatus (wxString const &msg, bool hyperlink=true)
Private Member Functions
void on_show_hide (wxShowEvent &evt)
void media_proc ()
Static Private Member Functions
static bool start_stream_service (bool *need_install=nullptr)
static bool get_stream_url (std::string *url=nullptr)
Private Attributes
wxMediaCtrl2 * m_media_ctrl
wxMediaState m_last_state = MEDIASTATE_IDLE
std::string m_machine
std::string m_lan_ip
std::string m_lan_user
std::string m_lan_passwd
bool m_camera_exists = false
bool m_lan_mode = false
bool m_tutk_support = false
bool m_device_busy = false
wxString m_url
std::deque< wxString > m_tasks
boost::mutex m_mutex
boost::condition_variable m_cond
boost::thread m_thread
bool m_streaming = false
bool m_user_triggered = false
int m_failed_retry = 0
int m_failed_code = 0
int m_last_failed_code = 0
wxDateTime m_next_retry
::Button * m_button_play
::Label * m_label_status
Static Private Attributes
static constexpr wxMediaState MEDIASTATE_IDLE = (wxMediaState) 3
static constexpr wxMediaState MEDIASTATE_INITIALIZING = (wxMediaState) 4
static constexpr wxMediaState MEDIASTATE_LOADING = (wxMediaState) 5
static constexpr wxMediaState MEDIASTATE_BUFFERING = (wxMediaState) 6
Detailed Description
Constructor & Destructor Documentation
MediaPlayCtrl()
Slic3r::GUI::MediaPlayCtrl::MediaPlayCtrl (wxWindow * parent, wxMediaCtrl2 * media_ctrl, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
    : wxPanel(parent, wxID_ANY, pos, size)
    , m_media_ctrl(media_ctrl)
{
    SetBackgroundColour(*wxWHITE);
    m_media_ctrl->Bind(wxEVT_MEDIA_STATECHANGED, &MediaPlayCtrl::onStateChanged, this);
    m_button_play = new Button(this, "", "media_play", wxBORDER_NONE);
    m_button_play->SetCanFocus(false);
    m_label_status = new Label(this, "");
    m_label_status->SetForegroundColour(wxColour("#2C2C2E"));
    m_button_play->Bind(wxEVT_COMMAND_BUTTON_CLICKED, [this](auto &e) { TogglePlay(); });
    m_button_play->Bind(wxEVT_RIGHT_UP, [this](auto & e) { m_media_ctrl->Play(); });
    m_label_status->Bind(wxEVT_LEFT_UP, [this](auto &e) {
        auto url = wxString::Format(L"https://wiki.bambulab.com/%s/software/bambu-studio/faq/live-view", L"en");
        wxLaunchDefaultBrowser(url);
    });
    Bind(wxEVT_RIGHT_UP, [this](auto & e) { wxClipboard & c = *wxTheClipboard; if (c.Open()) { c.SetData(new wxTextDataObject(m_url)); c.Close(); } });
    wxBoxSizer * sizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add(m_button_play, 0, wxEXPAND | wxALL, 0);
    sizer->AddStretchSpacer(1);
    sizer->Add(m_label_status, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, FromDIP(25));
    SetSizer(sizer);
    m_thread = boost::thread([this] {
        media_proc();
    });
//#if BBL_RELEASE_TO_PUBLIC
//    m_next_retry = wxDateTime::Now();
//#endif
    parent->Bind(wxEVT_SHOW, &MediaPlayCtrl::on_show_hide, this);
    parent->GetParent()->GetParent()->Bind(wxEVT_SHOW, &MediaPlayCtrl::on_show_hide, this);
    m_lan_user = "bblp";
    m_lan_passwd = "bblp";
}
References L, m_button_play, m_label_status, m_lan_passwd, m_lan_user, m_media_ctrl, m_thread, media_proc(), on_show_hide(), onStateChanged(), wxMediaCtrl2::Play(), Button::SetCanFocus(), and TogglePlay().
~MediaPlayCtrl()
Slic3r::GUI::MediaPlayCtrl::~MediaPlayCtrl ()
{
    {
        boost::unique_lock lock(m_mutex);
        m_tasks.push_back("<exit>");
        m_cond.notify_all();
    }
    m_thread.join();
}
References m_cond, m_mutex, m_tasks, and m_thread.
Member Function Documentation
get_stream_url()
bool Slic3r::GUI::MediaPlayCtrl::get_stream_url (std::string * url = nullptr) static private
{
#ifdef __WIN32__
    HANDLE shm = ::OpenFileMapping(FILE_MAP_READ, FALSE, L"bambu_stream_url");
    if (shm == NULL) return false;
    if (url) {
        char *addr = (char *) MapViewOfFile(shm, FILE_MAP_READ, 0, 0, 0);
        if (addr) {
            *url = addr;
            UnmapViewOfFile(addr);
            url = nullptr;
        }
    }
    CloseHandle(shm);
#else
    std::string file_url = data_dir() + "/cameratools/url.txt";
    key_t key = ::ftok(file_url.c_str(), 1000);
    int shm = ::shmget(key, 1024, 0);
    if (shm == -1) return false;
    struct shmid_ds ds;
    ::shmctl(shm, IPC_STAT, &ds);
    if (ds.shm_nattch == 0) {
        return false;
    }
    if (url) {
        char *addr = (char *) ::shmat(shm, nullptr, 0);
        if (addr != (void*) -1) {
            *url = addr;
            ::shmdt(addr);
            url = nullptr;
        }
    }
#endif
    return url == nullptr;
}
References Slic3r::data_dir(), FALSE, L, and NULL.
Referenced by SetMachineObject().
IsStreaming()
bool Slic3r::GUI::MediaPlayCtrl::IsStreaming () const
{ return m_streaming; }
Referenced by Slic3r::GUI::StatusPanel::on_camera_enter(), Slic3r::GUI::StatusPanel::on_switch_vcamera(), Slic3r::GUI::StatusPanel::rescale_camera_icons(), and Slic3r::GUI::StatusPanel::update_camera_state().
media_proc()
void Slic3r::GUI::MediaPlayCtrl::media_proc () private
{
    boost::unique_lock lock(m_mutex);
    while (true) {
        while (m_tasks.empty()) {
            m_cond.wait(lock);
        }
        wxString url = m_tasks.front();
        lock.unlock();
        if (url.IsEmpty()) {
            break;
        }
        else if (url == "<stop>") {
            BOOST_LOG_TRIVIAL(info) <<  "MediaPlayCtrl: start stop";
            m_media_ctrl->Stop();
            BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl: end stop";
        }
        else if (url == "<exit>") {
            break;
        }
        else if (url == "<play>") {
            m_media_ctrl->Play();
        }
        else {
            BOOST_LOG_TRIVIAL(info) <<  "MediaPlayCtrl: start load";
            m_media_ctrl->Load(wxURI(url));
            BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl: end load";
        }
        lock.lock();
        m_tasks.pop_front();
        wxMediaEvent theEvent(wxEVT_MEDIA_STATECHANGED, m_media_ctrl->GetId());
        theEvent.SetId(0);
        m_media_ctrl->GetEventHandler()->AddPendingEvent(theEvent);
    }
}
Referenced by MediaPlayCtrl().
on_show_hide()
void Slic3r::GUI::MediaPlayCtrl::on_show_hide (wxShowEvent & evt) private
{
    evt.Skip();
    if (m_isBeingDeleted) return;
    m_failed_retry = 0;
    IsShownOnScreen() ? Play() : Stop();
}
Referenced by MediaPlayCtrl().
onStateChanged()
void Slic3r::GUI::MediaPlayCtrl::onStateChanged (wxMediaEvent & event) protected
{
    auto last_state = m_last_state;
    auto state      = m_media_ctrl->GetState();
    BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl::onStateChanged: " << state << ", last_state: " << last_state;
    if ((int) state < 0) return;
    {
        boost::unique_lock lock(m_mutex);
        if (!m_tasks.empty()) {
            BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl::onStateChanged: skip when task not finished";
            return;
        }
    }
    if ((last_state == MEDIASTATE_IDLE || last_state == MEDIASTATE_INITIALIZING) && state == wxMEDIASTATE_STOPPED) { return; }
    if ((last_state == wxMEDIASTATE_PAUSED || last_state == wxMEDIASTATE_PLAYING) && state == wxMEDIASTATE_STOPPED) {
        m_failed_code = m_media_ctrl->GetLastError();
        Stop();
        return;
    }
    if (last_state == MEDIASTATE_LOADING && (state == wxMEDIASTATE_STOPPED || state == wxMEDIASTATE_PAUSED)) {
        wxSize size = m_media_ctrl->GetVideoSize();
        BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl::onStateChanged: size: " << size.x << "x" << size.y;
        m_failed_code = m_media_ctrl->GetLastError();
        if (size.GetWidth() > 1000) {
            m_last_state = state;
            SetStatus(_L("Playing..."), false);
            // track event
            json j;
            j["stage"] =  std::to_string(m_last_state);
            j["dev_id"] = m_machine;
            j["dev_ip"] = m_lan_ip;
            j["result"] = "success";
            j["code"] = 0;
            NetworkAgent* agent = wxGetApp().getAgent();
            if (agent)
                agent->track_event("start_liveview", j.dump());
            m_failed_retry = 0;
            m_failed_code  = 0;
            boost::unique_lock lock(m_mutex);
            m_tasks.push_back("<play>");
            m_cond.notify_all();
        } else if (event.GetId()) {
            if (m_failed_code == 0)
                m_failed_code = 2;
            Stop(_L("Load failed [%d]!"));
        }
    } else {
        m_last_state = state;
    }
}
References _L, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), size, and Slic3r::NetworkAgent::track_event().
Referenced by MediaPlayCtrl().
Play()
void Slic3r::GUI::MediaPlayCtrl::Play () protected
{
    if (!m_next_retry.IsValid() || wxDateTime::Now() < m_next_retry)
        return;
    if (!IsShownOnScreen())
        return;
    if (m_last_state != MEDIASTATE_IDLE) {
        return;
    }
    m_failed_code = 0;
    if (m_machine.empty()) {
        Stop(_L("Initialize failed (No Device)!"));
        return;
    }
    if (!m_camera_exists) {
        Stop(_L("Initialize failed (No Camera Device)!"));
        return;
    }
    m_last_state = MEDIASTATE_INITIALIZING;
    m_button_play->SetIcon("media_stop");
    SetStatus(_L("Initializing..."));
    NetworkAgent *agent = wxGetApp().getAgent();
    std::string  agent_version = agent ? agent->get_version() : "";
    if (!m_lan_ip.empty() && (!m_lan_mode || !m_lan_passwd.empty()) && !m_device_busy) {
        m_url        = "bambu:///local/" + m_lan_ip + ".?port=6000&user=" + m_lan_user + "&passwd=" + m_lan_passwd + "&device=" + m_machine + "&version=" + agent_version;
        m_last_state = MEDIASTATE_LOADING;
        SetStatus(_L("Loading..."));
        if (wxGetApp().app_config->get("dump_video") == "true") {
            std::string file_h264 = data_dir() + "/video.h264";
            std::string file_info = data_dir() + "/video.info";
            BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl dump video to " << file_h264;
            // closed by BambuSource
            FILE *dump_h264_file = boost::nowide::fopen(file_h264.c_str(), "wb");
            FILE *dump_info_file = boost::nowide::fopen(file_info.c_str(), "wb");
            m_url                = m_url + "&dump_h264=" + boost::lexical_cast<std::string>(dump_h264_file);
            m_url                = m_url + "&dump_info=" + boost::lexical_cast<std::string>(dump_info_file);
        }
        boost::unique_lock lock(m_mutex);
        m_tasks.push_back(m_url);
        m_cond.notify_all();
        return;
    }
    if (m_lan_mode) {
        m_failed_code = 1;
        Stop(m_lan_passwd.empty()
            ? _L("Initialize failed (Not supported with LAN-only mode)!")
            : _L("Initialize failed (Not accessible in LAN-only mode)!"));
        return;
    }
    if (!m_tutk_support) { // not support tutk
        if (m_device_busy) {
            Stop(_L("Printer is busy downloading, Please wait for the downloading to finish."));
            m_failed_retry = 0;
            return;
        }
        m_failed_code = 1;
        Stop(m_lan_ip.empty()
            ? _L("Initialize failed (Missing LAN ip of printer)!")
            : _L("Initialize failed (Not supported by printer)!"));
        return;
    }
    if (agent) {
        agent->get_camera_url(m_machine, [this, m = m_machine, v = agent_version](std::string url) {
            if (boost::algorithm::starts_with(url, "bambu:///")) {
                url += "&device=" + m;
                url += "&version=" + v;
            }
            BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl camera_url: " << url << ", machine: " << m_machine;
            CallAfter([this, m, url] {
                if (m != m_machine) return;
                m_url = url;
                if (m_last_state == MEDIASTATE_INITIALIZING) {
                    if (url.empty() || !boost::algorithm::starts_with(url, "bambu:///")) {
                        m_failed_code = 3;
                        Stop(wxString::Format(_L("Initialize failed (%s)!"), url.empty() ? _L("Network unreachable") : from_u8(url)));
                    } else {
                        m_last_state = MEDIASTATE_LOADING;
                        SetStatus(_L("Loading..."));
                        if (wxGetApp().app_config->get("dump_video") == "true") {
                            BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl dump video to " << boost::filesystem::current_path();
                            m_url = m_url + "&dump=video.h264";
                        }
                        boost::unique_lock lock(m_mutex);
                        m_tasks.push_back(m_url);
                        m_cond.notify_all();
                    }
                } else {
                    BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl drop late ttcode for state: " << m_last_state;
                }
            });
        });
    }
}
References _L, Slic3r::data_dir(), Slic3r::NetworkAgent::get_camera_url(), Slic3r::NetworkAgent::get_version(), m_button_play, m_camera_exists, m_cond, m_device_busy, m_failed_code, m_failed_retry, m_lan_ip, m_lan_mode, m_lan_passwd, m_lan_user, m_last_state, m_machine, m_mutex, m_next_retry, m_tasks, m_tutk_support, m_url, MEDIASTATE_IDLE, MEDIASTATE_INITIALIZING, MEDIASTATE_LOADING, Button::SetIcon(), SetStatus(), and Stop().
Referenced by SetMachineObject().
SetMachineObject()
void Slic3r::GUI::MediaPlayCtrl::SetMachineObject (MachineObject * obj)
{
    std::string machine = obj ? obj->dev_id : "";
    if (obj && obj->is_function_supported(PrinterFunction::FUNC_CAMERA_VIDEO)) {
        m_camera_exists = obj->has_ipcam;
        m_lan_mode      = obj->is_lan_mode_printer();
        m_lan_ip       = obj->is_function_supported(PrinterFunction::FUNC_LOCAL_TUNNEL) ? obj->dev_ip : "";
        m_lan_passwd    = obj->is_function_supported(PrinterFunction::FUNC_LOCAL_TUNNEL) ? obj->get_access_code() : "";
        m_tutk_support = obj->is_function_supported(PrinterFunction::FUNC_REMOTE_TUNNEL);
        m_device_busy   = obj->is_in_prepare() || obj->is_in_upgrading();
    } else {
        m_camera_exists = false;
        m_lan_mode = false;
        m_lan_ip.clear();
        m_lan_passwd.clear();
        m_tutk_support = true;
        m_device_busy = false;
    }
    if (machine == m_machine) {
        if (m_last_state == MEDIASTATE_IDLE)
            Play();
        return;
    }
    m_machine = machine;
    BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl switch machine: " << m_machine;
    m_failed_retry = 0;
    std::string stream_url;
    if (get_stream_url(&stream_url)) {
        m_streaming = boost::algorithm::contains(stream_url, "device=" + m_machine);
    } else {
        m_streaming = false;
    }
    if (m_last_state != MEDIASTATE_IDLE)
        Stop();
    if (m_next_retry.IsValid()) // Try open 2 seconds later, to avoid state conflict
        m_next_retry = wxDateTime::Now() + wxTimeSpan::Seconds(2 * m_failed_retry);
    else
        SetStatus("", false);
}
References Slic3r::MachineObject::dev_id, Slic3r::MachineObject::dev_ip, Slic3r::FUNC_CAMERA_VIDEO, Slic3r::FUNC_LOCAL_TUNNEL, Slic3r::FUNC_REMOTE_TUNNEL, Slic3r::MachineObject::get_access_code(), get_stream_url(), Slic3r::MachineObject::has_ipcam, Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_in_prepare(), Slic3r::MachineObject::is_in_upgrading(), Slic3r::MachineObject::is_lan_mode_printer(), m_camera_exists, m_device_busy, m_failed_retry, m_lan_ip, m_lan_mode, m_lan_passwd, m_last_state, m_machine, m_next_retry, m_streaming, m_tutk_support, MEDIASTATE_IDLE, Play(), SetStatus(), and Stop().
Referenced by Slic3r::GUI::MonitorPanel::update_all().
SetStatus()
void Slic3r::GUI::MediaPlayCtrl::SetStatus (wxString const & msg, bool hyperlink = true) protected
{
    auto msg = wxString::Format(msg2, m_failed_code);
    BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl::SetStatus: " << msg.ToUTF8().data();
#ifdef __WXMSW__
    OutputDebugStringA("MediaPlayCtrl::SetStatus: ");
    OutputDebugStringA(msg.ToUTF8().data());
    OutputDebugStringA("\n");
#endif // __WXMSW__
    m_label_status->SetLabel(msg);
    long style = m_label_status->GetWindowStyle() & ~LB_HYPERLINK;
    if (hyperlink) {
        style |= LB_HYPERLINK;
    }
    m_label_status->SetWindowStyle(style);
    m_label_status->InvalidateBestSize();
    Layout();
}
References LB_HYPERLINK, and style.
Referenced by Play(), and SetMachineObject().
start_stream_service()
bool Slic3r::GUI::MediaPlayCtrl::start_stream_service (bool * need_install = nullptr) static private
{
#ifdef __WIN32__
    std::string file_source = data_dir() + "\\cameratools\\bambu_source.exe";
    std::string file_ffmpeg = data_dir() + "\\cameratools\\ffmpeg.exe";
    std::string file_ff_cfg = data_dir() + "\\cameratools\\ffmpeg.cfg";
#else
    std::string file_source = data_dir() + "/cameratools/bambu_source";
    std::string file_ffmpeg = data_dir() + "/cameratools/ffmpeg";
    std::string file_ff_cfg = data_dir() + "/cameratools/ffmpeg.cfg";
#endif
    if (!boost::filesystem::exists(file_source) || !boost::filesystem::exists(file_ffmpeg) || !boost::filesystem::exists(file_ff_cfg)) {
        if (need_install) *need_install = true;
        return false;
    }
    std::string file_url  = data_dir() + "/cameratools/url.txt";
    if (!boost::filesystem::exists(file_url)) {
        boost::nowide::ofstream file(file_url);
        file.close();
    }
    wxString file_url2 = L"bambu:///camera/" + from_u8(file_url);
    file_url2.Replace("\\", "/");
    file_url2 = wxURI(file_url2).BuildURI();
    try {
        std::string configs;
        boost::filesystem::load_string_file(file_ff_cfg, configs);
        std::vector<std::string> configss;
        boost::algorithm::split(configss, configs, boost::algorithm::is_any_of("\r\n"));
        configss.erase(std::remove(configss.begin(), configss.end(), std::string()), configss.end());
        boost::process::pipe intermediate;
        boost::filesystem::path start_dir(boost::filesystem::path(data_dir()) / "plugins");
#ifdef __WXMSW__
        start_dir = boost::filesystem::path(data_dir()) / "cameratools";
        std::string file_dll = data_dir() + "/cameratools/BambuSource.dll";
        std::string file_dll2 = data_dir() + "/plugins/BambuSource.dll";
        if (!boost::filesystem::exists(file_dll) || boost::filesystem::last_write_time(file_dll) != boost::filesystem::last_write_time(file_dll2))
            boost::filesystem::copy_file(file_dll2, file_dll, boost::filesystem::copy_option::overwrite_if_exists);
        boost::process::child process_source(file_source, file_url2.data().AsInternal(), boost::process::start_dir(start_dir), boost::process::windows::create_no_window,
                                             boost::process::std_out > intermediate, boost::process::limit_handles);
        boost::process::child process_ffmpeg(file_ffmpeg, configss, boost::process::windows::create_no_window,
                                             boost::process::std_in < intermediate, boost::process::limit_handles);
#else
        boost::filesystem::permissions(file_source, boost::filesystem::owner_exe | boost::filesystem::add_perms);
        boost::filesystem::permissions(file_ffmpeg, boost::filesystem::owner_exe | boost::filesystem::add_perms);
        boost::process::child process_source(file_source, file_url2.data().AsInternal(), boost::process::start_dir(start_dir),
                                             boost::process::std_out > intermediate, boost::process::limit_handles);
        boost::process::child process_ffmpeg(file_ffmpeg, configss, boost::process::std_in < intermediate, boost::process::limit_handles);
#endif
        process_source.detach();
        process_ffmpeg.detach();
    } catch (std::exception &e) {
        BOOST_LOG_TRIVIAL(info) << "MediaPlayCtrl failed to start camera stream: " << e.what();
        return false;
    }
    return true;
}
References Slic3r::data_dir(), Slic3r::GUI::from_u8(), and L.
Stop()
void Slic3r::GUI::MediaPlayCtrl::Stop (wxString const & msg = {}) protected
{
    bool init_failed = m_last_state != wxMEDIASTATE_PLAYING;
    if (m_last_state != MEDIASTATE_IDLE) {
        m_media_ctrl->InvalidateBestSize();
        m_button_play->SetIcon("media_play");
        boost::unique_lock lock(m_mutex);
        m_tasks.push_back("<stop>");
        m_cond.notify_all();
        m_last_state = MEDIASTATE_IDLE;
        if (!msg.IsEmpty())
            SetStatus(msg, false);
        else if (m_failed_code)
            SetStatus(_L("Stopped [%d]!"), true);
        else
            SetStatus(_L("Stopped."), false);
        if (m_failed_code >= 100) // not keep retry on local error
            m_next_retry = wxDateTime();
    } else if (!msg.IsEmpty()) {
        SetStatus(msg, false);
    } else {
        m_failed_code = 0;
    }
    if (init_failed && m_failed_code != 0 && m_last_failed_code != m_failed_code) {
        json j;
        j["stage"]          = std::to_string(m_last_state);
        j["dev_id"]         = m_machine;
        j["dev_ip"]         = m_lan_ip;
        j["result"]         = "failed";
        j["code"]           = m_failed_code;
        j["msg"]            = into_u8(msg);
        NetworkAgent *agent = wxGetApp().getAgent();
        if (agent)
            agent->track_event("start_liveview", j.dump());
    }
    m_last_failed_code = m_failed_code;
    ++m_failed_retry;
    if (m_failed_code != 0 && !m_tutk_support && (m_failed_retry > 1 || m_user_triggered)) {
        m_next_retry = wxDateTime(); // stop retry
        if (wxGetApp().show_modal_ip_address_enter_dialog(_L("LAN Connection Failed (Failed to start liveview)"))) {
            m_failed_retry = 0;
            m_user_triggered = true;
            m_last_failed_code = 0;
            m_next_retry   = wxDateTime::Now();
            return;
        }
    }
    m_user_triggered = false;
    if (m_next_retry.IsValid())
        m_next_retry = wxDateTime::Now() + wxTimeSpan::Seconds(5 * m_failed_retry);
}
References _L, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), Slic3r::GUI::into_u8(), and Slic3r::NetworkAgent::track_event().
Referenced by Play(), and SetMachineObject().
TogglePlay()
void Slic3r::GUI::MediaPlayCtrl::TogglePlay () protected
{
    if (m_last_state != MEDIASTATE_IDLE) {
        m_next_retry = wxDateTime();
        Stop();
    } else {
        m_failed_retry = 0;
        m_user_triggered = true;
        m_last_failed_code = 0;
        m_next_retry   = wxDateTime::Now();
        Play();
    }
}
Referenced by MediaPlayCtrl().
ToggleStream()
void Slic3r::GUI::MediaPlayCtrl::ToggleStream ()
{
    std::string file_url = data_dir() + "/cameratools/url.txt";
    if (m_streaming) {
        boost::nowide::ofstream file(file_url);
        file.close();
        m_streaming = false;
        return;
    } else if (!boost::filesystem::exists(file_url)) {
        boost::nowide::ofstream file(file_url);
        file.close();
    }
    std::string url;
    if (!get_stream_url(&url)) {
        // create stream pipeline
        bool need_install = false;
        if (!start_stream_service(&need_install)) {
            if (!need_install) return;
            auto res = MessageDialog(this->GetParent(), _L("Virtual Camera Tools is required for this task!\nDo you want to install them?"), _L("Info"),
                                    wxOK | wxCANCEL).ShowModal();
            if (res == wxID_OK) {
                // download tools
                struct DownloadProgressDialog2 : DownloadProgressDialog
                {
                    MediaPlayCtrl *ctrl;
                    DownloadProgressDialog2(MediaPlayCtrl *ctrl) : DownloadProgressDialog(_L("Downloading Virtual Camera Tools")), ctrl(ctrl) {}
                    struct UpgradeNetworkJob2 : UpgradeNetworkJob
                    {
                        UpgradeNetworkJob2(std::shared_ptr<ProgressIndicator> pri) : UpgradeNetworkJob(pri) {
                            name         = "cameratools";
                            package_name = "camera_tools.zip";
                        }
                    };
                    std::shared_ptr<UpgradeNetworkJob> make_job(std::shared_ptr<ProgressIndicator> pri) override
                    { return std::make_shared<UpgradeNetworkJob2>(pri); }
                    void                               on_finish() override
                    {
                        ctrl->CallAfter([ctrl = this->ctrl] { ctrl->ToggleStream(); });
                        EndModal(wxID_CLOSE);
                    }
                };
                DownloadProgressDialog2 dlg(this);
                dlg.ShowModal();
            }
            return;
        }
    }
    if (!url.empty() && wxGetApp().app_config->get("not_show_vcamera_stop_prev") != "1") {
        MessageDialog dlg(this->GetParent(), _L("Another virtual camera is running.\nOrca Slicer supports only a single virtual camera.\nDo you want to stop this virtual camera?"), _L("Warning"),
                                 wxYES | wxCANCEL | wxICON_INFORMATION);
        dlg.show_dsa_button();
        auto          res = dlg.ShowModal();
        if (dlg.get_checkbox_state())
            wxGetApp().app_config->set("not_show_vcamera_stop_prev", "1");
        if (res == wxID_CANCEL) return;
    }
    NetworkAgent *agent = wxGetApp().getAgent();
    if (!agent) return;
    agent->get_camera_url(m_machine, [this, m = m_machine, v = agent->get_version()](std::string url) {
        if (boost::algorithm::starts_with(url, "bambu:///")) {
            url += "&device=" + m;
            url += "&version=" + v;
        }
        BOOST_LOG_TRIVIAL(info) << "camera_url: " << url;
        CallAfter([this, m, url] {
            if (m != m_machine) return;
            if (url.empty() || !boost::algorithm::starts_with(url, "bambu:///")) {
                MessageDialog(this->GetParent(), wxString::Format(_L("Virtual camera initialize failed (%s)!"), url.empty() ? _L("Network unreachable") : from_u8(url)), _L("Information"),
                              wxICON_INFORMATION)
                    .ShowModal();
                return;
            }
            std::string             file_url = data_dir() + "/cameratools/url.txt";
            boost::nowide::ofstream file(file_url);
            auto                    url2 = encode_path(url.c_str());
            file.write(url2.c_str(), url2.size());
            file.close();
            m_streaming = true;
        });
    });
}
References _L, Slic3r::data_dir(), Slic3r::encode_path(), Slic3r::NetworkAgent::get_camera_url(), Slic3r::GUI::MsgDialog::get_checkbox_state(), Slic3r::NetworkAgent::get_version(), Slic3r::GUI::MsgDialog::show_dsa_button(), Slic3r::GUI::DPIAware< P >::ShowModal(), and ToggleStream().
Referenced by Slic3r::GUI::StatusPanel::on_switch_vcamera(), and ToggleStream().
Member Data Documentation
m_button_play
::Button* Slic3r::GUI::MediaPlayCtrl::m_button_play private
Referenced by MediaPlayCtrl(), and Play().
m_camera_exists
bool Slic3r::GUI::MediaPlayCtrl::m_camera_exists = false private
Referenced by Play(), and SetMachineObject().
m_cond
boost::condition_variable Slic3r::GUI::MediaPlayCtrl::m_cond private
Referenced by ~MediaPlayCtrl(), and Play().
m_device_busy
bool Slic3r::GUI::MediaPlayCtrl::m_device_busy = false private
Referenced by Play(), and SetMachineObject().
m_failed_code
int Slic3r::GUI::MediaPlayCtrl::m_failed_code = 0 private
Referenced by Play().
m_failed_retry
int Slic3r::GUI::MediaPlayCtrl::m_failed_retry = 0 private
Referenced by Play(), and SetMachineObject().
m_label_status
::Label* Slic3r::GUI::MediaPlayCtrl::m_label_status private
Referenced by MediaPlayCtrl().
m_lan_ip
std::string Slic3r::GUI::MediaPlayCtrl::m_lan_ip private
Referenced by Play(), and SetMachineObject().
m_lan_mode
bool Slic3r::GUI::MediaPlayCtrl::m_lan_mode = false private
Referenced by Play(), and SetMachineObject().
m_lan_passwd
std::string Slic3r::GUI::MediaPlayCtrl::m_lan_passwd private
Referenced by MediaPlayCtrl(), Play(), and SetMachineObject().
m_lan_user
std::string Slic3r::GUI::MediaPlayCtrl::m_lan_user private
Referenced by MediaPlayCtrl(), and Play().
m_last_failed_code
int Slic3r::GUI::MediaPlayCtrl::m_last_failed_code = 0 private
m_last_state
wxMediaState Slic3r::GUI::MediaPlayCtrl::m_last_state = MEDIASTATE_IDLE private
Referenced by Play(), and SetMachineObject().
m_machine
std::string Slic3r::GUI::MediaPlayCtrl::m_machine private
Referenced by Play(), and SetMachineObject().
m_media_ctrl
wxMediaCtrl2* Slic3r::GUI::MediaPlayCtrl::m_media_ctrl private
Referenced by MediaPlayCtrl().
m_mutex
boost::mutex Slic3r::GUI::MediaPlayCtrl::m_mutex private
Referenced by ~MediaPlayCtrl(), and Play().
m_next_retry
wxDateTime Slic3r::GUI::MediaPlayCtrl::m_next_retry private
Referenced by Play(), and SetMachineObject().
m_streaming
bool Slic3r::GUI::MediaPlayCtrl::m_streaming = false private
Referenced by SetMachineObject().
m_tasks
std::deque<wxString> Slic3r::GUI::MediaPlayCtrl::m_tasks private
Referenced by ~MediaPlayCtrl(), and Play().
m_thread
boost::thread Slic3r::GUI::MediaPlayCtrl::m_thread private
Referenced by MediaPlayCtrl(), and ~MediaPlayCtrl().
m_tutk_support
bool Slic3r::GUI::MediaPlayCtrl::m_tutk_support = false private
Referenced by Play(), and SetMachineObject().
m_url
wxString Slic3r::GUI::MediaPlayCtrl::m_url private
Referenced by Play().
m_user_triggered
bool Slic3r::GUI::MediaPlayCtrl::m_user_triggered = false private
MEDIASTATE_BUFFERING
constexpr wxMediaState Slic3r::GUI::MediaPlayCtrl::MEDIASTATE_BUFFERING = (wxMediaState) 6 static constexpr private
MEDIASTATE_IDLE
constexpr wxMediaState Slic3r::GUI::MediaPlayCtrl::MEDIASTATE_IDLE = (wxMediaState) 3 static constexpr private
Referenced by Play(), and SetMachineObject().
MEDIASTATE_INITIALIZING
constexpr wxMediaState Slic3r::GUI::MediaPlayCtrl::MEDIASTATE_INITIALIZING = (wxMediaState) 4 static constexpr private
Referenced by Play().
MEDIASTATE_LOADING
constexpr wxMediaState Slic3r::GUI::MediaPlayCtrl::MEDIASTATE_LOADING = (wxMediaState) 5 static constexpr private
Referenced by Play().
The documentation for this class was generated from the following files:
src/slic3r/GUI/MediaPlayCtrl.h
src/slic3r/GUI/MediaPlayCtrl.cpp