OrcaSlicer: AxisCtrlButton Class Reference
AxisCtrlButton Class Reference
#include <src/slic3r/GUI/Widgets/AxisCtrlButton.hpp>
Public Member Functions
AxisCtrlButton (wxWindow *parent, ScalableBitmap &icon, long style=0)
void SetMinSize (const wxSize &size) override
void SetTextColor (StateColor const &color)
void SetBorderColor (StateColor const &color)
void SetBackgroundColor (StateColor const &color)
void SetInnerBackgroundColor (StateColor const &color)
void SetBitmap (ScalableBitmap &bmp)
void Rescale ()
Private Types
enum CurrentPos {
OUTER_UP = 0 , OUTER_LEFT = 1 , OUTER_DOWN = 2 , OUTER_RIGHT = 3 ,
INNER_UP = 4 , INNER_LEFT = 5 , INNER_DOWN = 6 , INNER_RIGHT = 7 ,
INNER_HOME = 8 , UNDEFINED = 9
}
Private Member Functions
void updateParams ()
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void mouseDown (wxMouseEvent &event)
void mouseReleased (wxMouseEvent &event)
void mouseMoving (wxMouseEvent &event)
void sendButtonEvent ()
Private Attributes
wxSize minSize
double stretch
double r_outer
double r_inner
double r_home
double r_blank
double gap
wxPoint center
StateHandler state_handler
StateColor text_color
StateColor border_color
StateColor background_color
StateColor inner_background_color
ScalableBitmap m_icon
bool pressedDown = false
unsigned char last_pos
unsigned char current_pos
Detailed Description
Member Enumeration Documentation
CurrentPos
enum AxisCtrlButton::CurrentPos private
Enumerator
OUTER_UP
OUTER_LEFT
OUTER_DOWN
OUTER_RIGHT
INNER_UP
INNER_LEFT
INNER_DOWN
INNER_RIGHT
INNER_HOME
UNDEFINED
                    {
        OUTER_UP = 0,
        OUTER_LEFT = 1,
        OUTER_DOWN = 2,
        OUTER_RIGHT = 3,
        INNER_UP = 4,
        INNER_LEFT = 5,
        INNER_DOWN = 6,
        INNER_RIGHT = 7,
        INNER_HOME = 8,
        UNDEFINED = 9
    };
Constructor & Destructor Documentation
AxisCtrlButton()
AxisCtrlButton::AxisCtrlButton (wxWindow * parent, ScalableBitmap & icon, long style = 0)
    : wxWindow(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, stlye)
    , r_outer(OUTER_SIZE)
    , r_inner(INNER_SIZE)
    , r_home(HOME_SIZE)
    , r_blank(BLANK_SIZE)
    , gap(GAP_SIZE)
    , last_pos(UNDEFINED)
    , current_pos(UNDEFINED) // don't change init value
    , text_color(std::make_pair(0x6B6B6B, (int) StateColor::Disabled), std::make_pair(*wxBLACK, (int) StateColor::Normal))
  , state_handler(this)
{
    m_icon = icon;
  wxWindow::SetBackgroundColour(parent->GetBackgroundColour());
    border_color.append(bd, StateColor::Hovered);
    background_color.append(BUTTON_BG_COL, StateColor::Disabled);
    background_color.append(BUTTON_PRESS_COL, StateColor::Pressed);
    background_color.append(BUTTON_BG_COL, StateColor::Hovered);
    background_color.append(BUTTON_BG_COL, StateColor::Normal);
    background_color.append(BUTTON_BG_COL, StateColor::Enabled);
    inner_background_color.append(BUTTON_IN_BG_COL, StateColor::Disabled);
    inner_background_color.append(BUTTON_PRESS_COL, StateColor::Pressed);
    inner_background_color.append(BUTTON_IN_BG_COL, StateColor::Hovered);
    inner_background_color.append(BUTTON_IN_BG_COL, StateColor::Normal);
    inner_background_color.append(BUTTON_IN_BG_COL, StateColor::Enabled);
    state_handler.attach({ &border_color, &background_color });
    state_handler.update_binds();
}
References StateColor::append(), StateHandler::attach(), background_color, bd, border_color, BUTTON_BG_COL, BUTTON_IN_BG_COL, BUTTON_PRESS_COL, StateColor::Disabled, StateColor::Enabled, StateColor::Hovered, inner_background_color, m_icon, StateColor::Normal, StateColor::Pressed, state_handler, and StateHandler::update_binds().
Member Function Documentation
mouseDown()
void AxisCtrlButton::mouseDown (wxMouseEvent & event) private
{
    event.Skip();
    pressedDown = true;
    SetFocus();
    CaptureMouse();
}
References pressedDown.
mouseMoving()
void AxisCtrlButton::mouseMoving (wxMouseEvent & event) private
{
    if (pressedDown)
        return;
  wxPoint mouse_pos(event.GetX(), event.GetY());
  wxPoint transformed_mouse_pos = mouse_pos - center;
  double r_temp = transformed_mouse_pos.x * transformed_mouse_pos.x + transformed_mouse_pos.y * transformed_mouse_pos.y;
  if (r_temp > r_outer * r_outer) {
    current_pos = CurrentPos::UNDEFINED;
  }
  else if (r_temp > r_inner * r_inner) {
    if (transformed_mouse_pos.y < transformed_mouse_pos.x - gap && transformed_mouse_pos.y < -transformed_mouse_pos.x - gap)
    {
      current_pos = CurrentPos::OUTER_UP;
    }
    else if (transformed_mouse_pos.y > transformed_mouse_pos.x + gap && transformed_mouse_pos.y < -transformed_mouse_pos.x - gap)
    {
      current_pos = CurrentPos::OUTER_LEFT;
    }
    else if (transformed_mouse_pos.y > transformed_mouse_pos.x + gap && transformed_mouse_pos.y > -transformed_mouse_pos.x + gap)
    {
      current_pos = CurrentPos::OUTER_DOWN;
    }
    else if (transformed_mouse_pos.y < transformed_mouse_pos.x - gap && transformed_mouse_pos.y > -transformed_mouse_pos.x + gap)
    {
      current_pos = CurrentPos::OUTER_RIGHT;
    }
        else {
            current_pos = CurrentPos::UNDEFINED;
        }
  }
  else if (r_temp > r_blank * r_blank) {
    if (transformed_mouse_pos.y < transformed_mouse_pos.x - gap && transformed_mouse_pos.y < -transformed_mouse_pos.x - gap)
    {
      current_pos = CurrentPos::INNER_UP;
    }
    else if (transformed_mouse_pos.y > transformed_mouse_pos.x + gap && transformed_mouse_pos.y < -transformed_mouse_pos.x - gap)
    {
      current_pos = CurrentPos::INNER_LEFT;
    }
    else if (transformed_mouse_pos.y > transformed_mouse_pos.x + gap && transformed_mouse_pos.y > -transformed_mouse_pos.x + gap)
    {
      current_pos = CurrentPos::INNER_DOWN;
    }
    else if (transformed_mouse_pos.y < transformed_mouse_pos.x - gap && transformed_mouse_pos.y > -transformed_mouse_pos.x + gap)
    {
      current_pos = CurrentPos::INNER_RIGHT;
    }
        else {
            current_pos = CurrentPos::UNDEFINED;
        }
    } else if (r_temp <= r_home * r_home) {
        current_pos = INNER_HOME;
    }
  if (last_pos != current_pos) {
    last_pos = current_pos;
    Refresh();
  }
}
References center, current_pos, gap, INNER_DOWN, INNER_HOME, INNER_LEFT, INNER_RIGHT, INNER_UP, last_pos, OUTER_DOWN, OUTER_LEFT, OUTER_RIGHT, OUTER_UP, pressedDown, r_blank, r_home, r_inner, r_outer, and UNDEFINED.
mouseReleased()
void AxisCtrlButton::mouseReleased (wxMouseEvent & event) private
{
    event.Skip();
    if (pressedDown) {
        pressedDown = false;
        ReleaseMouse();
        if (wxRect({ 0, 0 }, GetSize()).Contains(event.GetPosition()))
            sendButtonEvent();
    }
}
References pressedDown, and sendButtonEvent().
paintEvent()
void AxisCtrlButton::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    wxGCDC gcdc(dc);
    render(gcdc);
}
References render().
render()
void AxisCtrlButton::render (wxDC & dc) private
{
    wxGraphicsContext* gc = dc.GetGraphicsContext();
    int states = state_handler.states();
  wxSize size = GetSize();
    gc->PushState();
    gc->Translate(center.x, center.y);
  //draw the outer ring
    wxGraphicsPath outer_path = gc->CreatePath();
    outer_path.AddCircle(0, 0, r_outer);
    outer_path.AddCircle(0, 0, r_inner);
    gc->SetPen(StateColor::darkModeColorFor(BUTTON_BG_COL));
    gc->SetBrush(StateColor::darkModeColorFor(BUTTON_BG_COL));
    gc->DrawPath(outer_path);
  //draw the inner ring
    wxGraphicsPath inner_path = gc->CreatePath();
    inner_path.AddCircle(0, 0, r_inner);
    inner_path.AddCircle(0, 0, r_blank);
    gc->SetPen(StateColor::darkModeColorFor(BUTTON_IN_BG_COL));
    gc->SetBrush(StateColor::darkModeColorFor(BUTTON_IN_BG_COL));
  gc->DrawPath(inner_path);
  //draw an arc in corresponding position
  if (current_pos != CurrentPos::UNDEFINED) {
    wxGraphicsPath path = gc->CreatePath();
    if (current_pos < 4) {
      path.AddArc(0, 0, r_outer, (5 - 2 * current_pos) * PI / 4, (7 - 2 * current_pos) * PI / 4, true);
      path.AddArc(0, 0, r_inner, (7 - 2 * current_pos) * PI / 4, (5 - 2 * current_pos) * PI / 4, false);
      path.CloseSubpath();
      gc->SetBrush(wxBrush(background_color.colorForStates(states)));
    }
    else if (current_pos < 8) {
      path.AddArc(0, 0, r_inner, (5 - 2 * current_pos) * PI / 4, (7 - 2 * current_pos) * PI / 4, true);
      path.AddArc(0, 0, r_blank, (7 - 2 * current_pos) * PI / 4, (5 - 2 * current_pos) * PI / 4, false);
      path.CloseSubpath();
      gc->SetBrush(wxBrush(inner_background_color.colorForStates(states)));
        }
    gc->SetPen(wxPen(border_color.colorForStates(states),2));
    gc->DrawPath(path);
  }
  //draw rectangle gap
  gc->SetPen(blank_bg.colorForStates(StateColor::Normal));
  gc->SetBrush(blank_bg.colorForStates(StateColor::Normal));
  gc->PushState();
  gc->Rotate(-PI / 4);
  gc->DrawRectangle(-sqrt2 * size.x / 2, -sqrt2 * gap / 2, sqrt2 * size.x, sqrt2 * gap);
  gc->Rotate(-PI / 2);
  gc->DrawRectangle(-sqrt2 * size.x / 2, -sqrt2 * gap / 2, sqrt2 * size.x, sqrt2 * gap);
  gc->PopState();
  // draw the home circle
    wxGraphicsPath home_path = gc->CreatePath();
    home_path.AddCircle(0, 0, r_home);
    home_path.CloseSubpath();
    gc->PushState();
    if (current_pos == 8) {
        gc->SetPen(wxPen(border_color.colorForStates(states), 2));
        gc->SetBrush(wxBrush(background_color.colorForStates(states)));
    } else {
        gc->SetPen(StateColor::darkModeColorFor(BUTTON_BG_COL));
        gc->SetBrush(StateColor::darkModeColorFor(BUTTON_BG_COL));
    }
    gc->DrawPath(home_path);
    if (m_icon.bmp().IsOk()) {
        gc->DrawBitmap(m_icon.bmp(), -1 * m_icon.GetBmpWidth() / 2, -1 * m_icon.GetBmpHeight() / 2, m_icon.GetBmpWidth(), m_icon.GetBmpHeight());
    }
    gc->PopState();
  //draw linear border of the arc
  if (current_pos != CurrentPos::UNDEFINED) {
        gc->PushState();
        gc->SetPen(wxPen(border_color.colorForStates(states), 2));
        if (current_pos == 8) {
            wxGraphicsPath line_path = gc->CreatePath();
            line_path.AddCircle(0, 0, r_home);
            gc->StrokePath(line_path);
        } else {
            wxGraphicsPath line_path1 = gc->CreatePath();
            wxGraphicsPath line_path2 = gc->CreatePath();
            if (current_pos < 4) {
                line_path1.MoveToPoint(r_inner, -sqrt2 * gap / 2);
                line_path1.AddLineToPoint(r_outer, -sqrt2 * gap / 2);
                line_path2.MoveToPoint(-r_inner, -sqrt2 * gap / 2);
                line_path2.AddLineToPoint(-r_outer, -sqrt2 * gap / 2);
            } else if (current_pos < 8) {
                line_path1.MoveToPoint(r_blank, -sqrt2 * gap / 2);
                line_path1.AddLineToPoint(r_inner, -sqrt2 * gap / 2);
                line_path2.MoveToPoint(-r_blank, -sqrt2 * gap / 2);
                line_path2.AddLineToPoint(-r_inner, -sqrt2 * gap / 2);
            }
            gc->Rotate(-(1 + 2 * current_pos) * PI / 4);
            gc->StrokePath(line_path1);
            gc->Rotate(PI / 2);
            gc->StrokePath(line_path2);
        }
        gc->PopState();
  }
  //draw text
    if (!IsEnabled())
        gc->SetFont(Label::Body_12, text_color.colorForStates(StateColor::Disabled));
    else
      gc->SetFont(Label::Head_12, text_color.colorForStates(states));
  wxDouble w, h;
  gc->GetTextExtent("Y", &w, &h);
  gc->DrawText(wxT("Y"), -w / 2, -r_outer + (r_outer - r_inner) / 2 - h / 2);
  gc->GetTextExtent("-X", &w, &h);
  gc->DrawText(wxT("-X"), -r_outer + (r_outer - r_inner) / 2 - w / 2, - h / 2);
  gc->GetTextExtent("-Y", &w, &h);
  gc->DrawText(wxT("-Y"), -w / 2, r_outer - (r_outer - r_inner) / 2 - h / 2);
  gc->GetTextExtent("X", &w, &h);
  gc->DrawText(wxT("X"), r_outer - (r_outer - r_inner) / 2 - w / 2, -h / 2);
  gc->SetFont(Label::Body_12, text_num_color);
  gc->PushState();
  gc->Rotate(PI / 4);
  gc->GetTextExtent("+10", &w, &h);
  gc->DrawText(wxT("+10"), sqrt2 * gap, -r_outer + (r_outer - r_inner) / 2 - h / 2);
  gc->GetTextExtent("+1", &w, &h);
  gc->DrawText(wxT("+1"), sqrt2 * gap, -r_inner + (r_inner - r_blank) / 2 - h / 2);
  gc->GetTextExtent("-1", &w, &h);
  gc->DrawText(wxT("-1"), sqrt2 * gap, r_inner - (r_inner - r_blank) / 2 - h / 2);
  gc->GetTextExtent("-10", &w, &h);
  gc->DrawText(wxT("-10"), sqrt2 * gap, r_outer - (r_outer - r_inner) / 2 - h / 2);
  gc->PopState();
  gc->PopState();
}
References background_color, blank_bg, ScalableBitmap::bmp(), Label::Body_12, border_color, BUTTON_BG_COL, BUTTON_IN_BG_COL, center, StateColor::colorForStates(), current_pos, StateColor::darkModeColorFor(), StateColor::Disabled, gap, ScalableBitmap::GetBmpHeight(), ScalableBitmap::GetBmpWidth(), Label::Head_12, inner_background_color, m_icon, StateColor::Normal, PI, r_blank, r_home, r_inner, r_outer, size, sqrt2, state_handler, StateHandler::states(), text_color, text_num_color, and UNDEFINED.
Referenced by paintEvent().
Rescale()
void AxisCtrlButton::Rescale ()
{
  Refresh();
}
Referenced by Slic3r::GUI::StatusPanel::msw_rescale().
sendButtonEvent()
void AxisCtrlButton::sendButtonEvent () private
{
    wxCommandEvent event(wxEVT_COMMAND_BUTTON_CLICKED, GetId());
    event.SetEventObject(this);
    event.SetInt(current_pos);
    GetEventHandler()->ProcessEvent(event);
}
References current_pos.
Referenced by mouseReleased().
SetBackgroundColor()
void AxisCtrlButton::SetBackgroundColor (StateColor const & color)
{
    background_color = color;
    state_handler.update_binds();
    Refresh();
}
References background_color, state_handler, and StateHandler::update_binds().
SetBitmap()
void AxisCtrlButton::SetBitmap (ScalableBitmap & bmp)
{
    m_icon = bmp;
}
References m_icon.
Referenced by Slic3r::GUI::StatusPanel::msw_rescale().
SetBorderColor()
void AxisCtrlButton::SetBorderColor (StateColor const & color)
{
    border_color = color;
    state_handler.update_binds();
    Refresh();
}
References border_color, state_handler, and StateHandler::update_binds().
SetInnerBackgroundColor()
void AxisCtrlButton::SetInnerBackgroundColor (StateColor const & color)
{
    inner_background_color = color;
    state_handler.update_binds();
    Refresh();
}
References inner_background_color, state_handler, and StateHandler::update_binds().
SetMinSize()
void AxisCtrlButton::SetMinSize (const wxSize & size) override
{
  wxSize cur_size = GetSize();
    if (size.GetWidth() > 0 && size.GetHeight() > 0) {
        stretch = std::min((double)size.GetWidth() / cur_size.x,(double)size.GetHeight() / cur_size.y);
    minSize = size;
        updateParams();
    }
    else if (size.GetWidth() > 0) {
    stretch = (double)size.GetWidth() / cur_size.x;
    minSize.x = size.x;
        updateParams();
    }
    else if (size.GetHeight() > 0) {
    stretch = (double)size.GetHeight() / cur_size.y;
    minSize.y = size.y;
        updateParams();
    }
    else {
    stretch = 1.0;
        minSize = wxSize(228, 228);
    }
    wxWindow::SetMinSize(minSize);
    center = wxPoint(minSize.x / 2, minSize.y / 2);
}
References center, minSize, size, stretch, and updateParams().
Referenced by Slic3r::GUI::StatusBasePanel::create_axis_control(), and Slic3r::GUI::StatusPanel::msw_rescale().
SetTextColor()
void AxisCtrlButton::SetTextColor (StateColor const & color)
{
    text_color = color;
    state_handler.update_binds();
    Refresh();
}
References state_handler, text_color, and StateHandler::update_binds().
Referenced by Slic3r::GUI::StatusBasePanel::create_axis_control().
updateParams()
void AxisCtrlButton::updateParams () private
{
    r_outer = OUTER_SIZE;
    r_inner = INNER_SIZE;
    r_home = HOME_SIZE;
    r_blank = BLANK_SIZE;
    gap = GAP_SIZE;
}
References BLANK_SIZE, gap, GAP_SIZE, HOME_SIZE, INNER_SIZE, OUTER_SIZE, r_blank, r_home, r_inner, and r_outer.
Referenced by SetMinSize().
Member Data Documentation
background_color
StateColor AxisCtrlButton::background_color private
Referenced by AxisCtrlButton(), render(), and SetBackgroundColor().
border_color
StateColor AxisCtrlButton::border_color private
Referenced by AxisCtrlButton(), render(), and SetBorderColor().
center
wxPoint AxisCtrlButton::center private
Referenced by mouseMoving(), render(), and SetMinSize().
current_pos
unsigned char AxisCtrlButton::current_pos private
Referenced by mouseMoving(), render(), and sendButtonEvent().
gap
double AxisCtrlButton::gap private
Referenced by mouseMoving(), render(), and updateParams().
inner_background_color
StateColor AxisCtrlButton::inner_background_color private
Referenced by AxisCtrlButton(), render(), and SetInnerBackgroundColor().
last_pos
unsigned char AxisCtrlButton::last_pos private
Referenced by mouseMoving().
m_icon
ScalableBitmap AxisCtrlButton::m_icon private
Referenced by AxisCtrlButton(), render(), and SetBitmap().
minSize
wxSize AxisCtrlButton::minSize private
Referenced by SetMinSize().
pressedDown
bool AxisCtrlButton::pressedDown = false private
Referenced by mouseDown(), mouseMoving(), and mouseReleased().
r_blank
double AxisCtrlButton::r_blank private
Referenced by mouseMoving(), render(), and updateParams().
r_home
double AxisCtrlButton::r_home private
Referenced by mouseMoving(), render(), and updateParams().
r_inner
double AxisCtrlButton::r_inner private
Referenced by mouseMoving(), render(), and updateParams().
r_outer
double AxisCtrlButton::r_outer private
Referenced by mouseMoving(), render(), and updateParams().
state_handler
StateHandler AxisCtrlButton::state_handler private
Referenced by AxisCtrlButton(), render(), SetBackgroundColor(), SetBorderColor(), SetInnerBackgroundColor(), and SetTextColor().
stretch
double AxisCtrlButton::stretch private
Referenced by SetMinSize().
text_color
StateColor AxisCtrlButton::text_color private
Referenced by render(), and SetTextColor().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AxisCtrlButton.hpp
src/slic3r/GUI/Widgets/AxisCtrlButton.cpp