OrcaSlicer: Slic3r::GUI::SavePresetDialog::Item Class Reference
Slic3r::GUI::SavePresetDialog::Item Class Reference
Public Types
enum ValidationType { Valid , NoValid , Warning }
Public Member Functions
Item (Preset::Type type, const std::string &suffix, wxBoxSizer *sizer, SavePresetDialog *parent)
void update_valid_bmp ()
void accept ()
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
bool is_valid () const
Preset::Type type () const
std::string preset_name () const
bool save_to_project () const
void update ()
Public Attributes
Preset::Type m_type
ValidationType m_valid_type
std::string m_preset_name
SavePresetDialog * m_parent {nullptr}
wxStaticBitmap * m_valid_bmp {nullptr}
wxComboBox * m_combo {nullptr}
TextInput * m_input_ctrl {nullptr}
wxStaticText * m_valid_label {nullptr}
PresetCollection * m_presets {nullptr}
RadioBox * m_radio_user {nullptr}
RadioBox * m_radio_project {nullptr}
bool m_save_to_project {false}
Detailed Description
Member Enumeration Documentation
ValidationType
enum Slic3r::GUI::SavePresetDialog::Item::ValidationType
Enumerator
Valid
NoValid
Warning
        {
            Valid,
            NoValid,
            Warning
        };
Constructor & Destructor Documentation
Item()
Slic3r::GUI::SavePresetDialog::Item::Item (Preset::Type type, const std::string & suffix, wxBoxSizer * sizer, SavePresetDialog * parent)
                                                                                                                : m_type(type), m_parent(parent)
{
    Tab *tab = wxGetApp().get_tab(m_type);
    assert(tab);
    m_presets = tab->get_presets();
    const Preset &sel_preset  = m_presets->get_selected_preset();
    std::string   preset_name = sel_preset.is_default ? "Untitled" : sel_preset.is_system ? (boost::format(("%1% - %2%")) % sel_preset.name % suffix).str() : sel_preset.name;
    // if name contains extension
    if (boost::iends_with(preset_name, ".ini")) {
        size_t len = preset_name.length() - 4;
        preset_name.resize(len);
    }
    std::vector<std::string> values;
    for (const Preset &preset : *m_presets) {
        // BBS: add project embedded preset logic and refine is_external
        if (preset.is_default || preset.is_system)
            // if (preset.is_default || preset.is_system || preset.is_external)
            continue;
        values.push_back(preset.name);
    }
    wxStaticText *label_top = new wxStaticText(m_parent, wxID_ANY, from_u8((boost::format(_utf8(L("Save %s as"))) % into_u8(tab->title())).str()));
    label_top->SetFont(::Label::Body_13);
    label_top->SetForegroundColour(wxColour(38,46,48));
    //    m_valid_bmp = new wxStaticBitmap(m_parent, wxID_ANY, create_scaled_bitmap("blank_16", m_parent));
    //
    //    m_combo = new wxComboBox(m_parent, wxID_ANY, from_u8(preset_name), wxDefaultPosition, wxSize(35 * wxGetApp().em_unit(), -1));
    //    for (const std::string& value : values)
    //        m_combo->Append(from_u8(value));
    //
    //    m_combo->Bind(wxEVT_TEXT, [this](wxCommandEvent&) { update(); });
    //#ifdef __WXOSX__
    //    // Under OSX wxEVT_TEXT wasn't invoked after change selection in combobox,
    //    // So process wxEVT_COMBOBOX too
    //    m_combo->Bind(wxEVT_COMBOBOX, [this](wxCommandEvent&) { update(); });
    //#endif //__WXOSX__
    //    wxBoxSizer *combo_sizer = new wxBoxSizer(wxHORIZONTAL);
    //    combo_sizer->Add(m_valid_bmp, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, BORDER_W);
    //    combo_sizer->Add(m_combo, 1, wxEXPAND, BORDER_W);
    wxBoxSizer *input_sizer_h = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *input_sizer_v  = new wxBoxSizer(wxVERTICAL);
    /*m_input_ctrl = new wxTextCtrl(this, wxID_ANY, from_u8(preset_name), wxDefaultPosition, wxDefaultSize,wxBORDER_NONE);*/
    m_input_ctrl = new ::TextInput(parent, from_u8(preset_name), wxEmptyString, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    StateColor input_bg(std::pair<wxColour, int>(wxColour("#F0F0F1"), StateColor::Disabled), std::pair<wxColour, int>(*wxWHITE, StateColor::Enabled));
    m_input_ctrl->SetBackgroundColor(input_bg);
    m_input_ctrl->Bind(wxEVT_TEXT, [this](wxCommandEvent &) { update(); });
    m_input_ctrl->SetMinSize(wxSize(SAVE_PRESET_DIALOG_INPUT_SIZE));
    m_input_ctrl->SetMaxSize(wxSize(SAVE_PRESET_DIALOG_INPUT_SIZE));
    input_sizer_v->Add(m_input_ctrl, 1, wxEXPAND, 0);
    input_sizer_h->Add(input_sizer_v, 1, wxALIGN_CENTER, 0);
    input_sizer_h->Layout();
    m_valid_label = new wxStaticText(m_parent, wxID_ANY, "");
    m_valid_label->SetForegroundColour(wxColor(255, 111, 0));
    sizer->Add(label_top, 0, wxEXPAND | wxLEFT | wxTOP | wxBOTTOM, BORDER_W);
    sizer->Add(input_sizer_h, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT, BORDER_W);
    sizer->Add(m_valid_label, 0, wxEXPAND | wxLEFT | wxRIGHT, BORDER_W);
    if (m_type == Preset::TYPE_PRINTER) m_parent->add_info_for_edit_ph_printer(sizer);
    // BBS: add project embedded presets logic
    wxBoxSizer *radio_sizer = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_sizer_left = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_left->Add(0, 0, 0, wxLEFT, 25);
    m_radio_user     = new RadioBox(parent);
    m_radio_user->SetBackgroundColour(SAVE_PRESET_DIALOG_DEF_COLOUR);
    m_sizer_left->Add(m_radio_user, 0, wxALIGN_CENTER, 0);
    m_sizer_left->Add(0, 0, 0, wxLEFT, 10);
    auto m_left_text = new wxStaticText(parent, wxID_ANY, _L("User Preset"), wxDefaultPosition, wxDefaultSize, 0);
    m_left_text->Wrap(-1);
    m_left_text->SetFont(::Label::Body_13);
    m_left_text->SetForegroundColour(wxColour(107,107,107));
    m_sizer_left->Add(m_left_text, 0, wxALIGN_CENTER, 0);
    radio_sizer->Add(m_sizer_left, 1, wxALIGN_CENTER, 5);
    wxBoxSizer *m_sizer_right = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_right->Add(0, 0, 0, wxLEFT, 15);
    m_radio_project   = new RadioBox(parent);
    m_radio_project->SetBackgroundColour(SAVE_PRESET_DIALOG_DEF_COLOUR);
    m_sizer_right->Add(m_radio_project, 0, wxALIGN_CENTER, 0);
    m_sizer_right->Add(0, 0, 0, wxLEFT, 10);
    auto m_right_text = new wxStaticText(parent, wxID_ANY, _L("Project Inside Preset"), wxDefaultPosition, wxDefaultSize, 0);
    m_right_text->SetForegroundColour(wxColour(107,107,107));
    m_right_text->SetFont(::Label::Body_13);
    m_right_text->Wrap(-1);
    m_sizer_right->Add(m_right_text, 0, wxALIGN_CENTER, 0);
    radio_sizer->Add(m_sizer_right, 1, wxEXPAND, 5);
    sizer->Add(radio_sizer, 0, wxEXPAND | wxTOP, BORDER_W);
    auto radio_clicked = [this](wxMouseEvent &e) {
        if (m_radio_user->GetId() == e.GetId()) {
            m_radio_user->SetValue(true);
            m_radio_project->SetValue(false);
            m_save_to_project = false;
        }
        if (m_radio_project->GetId() == e.GetId()) {
            m_radio_user->SetValue(false);
            m_radio_project->SetValue(true);
            m_save_to_project = true;
        }
    };
    m_radio_user->Bind(wxEVT_LEFT_DOWN, radio_clicked);
    m_radio_project->Bind(wxEVT_LEFT_DOWN, radio_clicked);
    bool is_project_embedded = m_presets->get_edited_preset().is_project_embedded;
    if (is_project_embedded)
        m_radio_project->SetValue(true);
    else
        m_radio_user->SetValue(true);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", create item: type" << Preset::get_type_string(m_type) << ", preset " << m_preset_name
                            << ", is_project_embedded = " << is_project_embedded;
    update();
}
References _L, _utf8, Slic3r::GUI::SavePresetDialog::add_info_for_edit_ph_printer(), Label::Body_13, BORDER_W, StateColor::Disabled, StateColor::Enabled, Slic3r::GUI::from_u8(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::Tab::get_presets(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::get_type_string(), Slic3r::GUI::into_u8(), Slic3r::Preset::is_default, Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_system, L, m_input_ctrl, m_parent, m_preset_name, m_presets, m_radio_project, m_radio_user, m_save_to_project, m_type, m_valid_label, Slic3r::Preset::name, preset_name(), SAVE_PRESET_DIALOG_DEF_COLOUR, SAVE_PRESET_DIALOG_INPUT_SIZE, TextInput::SetMinSize(), Slic3r::GUI::RadioBox::SetValue(), Slic3r::GUI::Tab::title(), Slic3r::Preset::TYPE_PRINTER, update(), Slic3r::GUI::wxMouseEvent, and wxStaticText.
Member Function Documentation
accept()
void Slic3r::GUI::SavePresetDialog::Item::accept ()
{
    if (m_valid_type == Warning) {
        // BBS add sync info
        auto    it               = m_presets->find_preset(m_preset_name, false);
        Preset &current_preset   = *it;
        current_preset.sync_info = "delete";
        if (!current_preset.setting_id.empty()) {
            BOOST_LOG_TRIVIAL(info) << "delete preset = " << current_preset.name << ", setting_id = " << current_preset.setting_id;
            wxGetApp().delete_preset_from_cloud(current_preset.setting_id);
        }
        m_presets->delete_preset(m_preset_name);
    }
}
References Slic3r::Preset::name, Slic3r::Preset::setting_id, Slic3r::Preset::sync_info, and Warning.
DoSetSize()
void Slic3r::GUI::SavePresetDialog::Item::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) virtual
{
    wxWindow::DoSetSize(x, y, width, height, sizeFlags);
}
is_valid()
bool Slic3r::GUI::SavePresetDialog::Item::is_valid () const inline
{ return m_valid_type != NoValid; }
References m_valid_type, and NoValid.
preset_name()
std::string Slic3r::GUI::SavePresetDialog::Item::preset_name () const inline
{ return m_preset_name; }
References m_preset_name.
Referenced by Item().
save_to_project()
bool Slic3r::GUI::SavePresetDialog::Item::save_to_project () const inline
{ return m_save_to_project; }
References m_save_to_project.
type()
Preset::Type Slic3r::GUI::SavePresetDialog::Item::type () const inline
{ return m_type; }
References m_type.
update()
void Slic3r::GUI::SavePresetDialog::Item::update ()
{
    m_preset_name = into_u8(m_input_ctrl->GetTextCtrl()->GetValue());
    m_valid_type = Valid;
    wxString info_line;
    const char *unusable_symbols = "<>[]:/\\|?*\"";
    const std::string unusable_suffix = PresetCollection::get_suffix_modified(); //"(modified)";
    for (size_t i = 0; i < std::strlen(unusable_symbols); i++) {
        if (m_preset_name.find_first_of(unusable_symbols[i]) != std::string::npos) {
            info_line    = _L("Name is invalid;") + "\n" + _L("illegal characters:") + " " + unusable_symbols;
            m_valid_type = NoValid;
            break;
        }
    }
    if (m_valid_type == Valid && m_preset_name.find(unusable_suffix) != std::string::npos) {
        info_line    = _L("Name is invalid;") + "\n" + _L("illegal suffix:") + "\n\t" + from_u8(PresetCollection::get_suffix_modified());
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid &&
        (m_preset_name == "Default Setting" || m_preset_name == "Default Filament" || m_preset_name == "Default Printer")) {
        info_line    = _L("Name is unavailable.");
        m_valid_type = NoValid;
    }
    const Preset *existing = m_presets->find_preset(m_preset_name, false);
    if (m_valid_type == Valid && existing && (existing->is_default || existing->is_system)) {
        info_line = _L("Overwrite a system profile is not allowed");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && existing && m_preset_name != m_presets->get_selected_preset_name()) {
        if (existing->is_compatible)
            info_line = from_u8((boost::format(_u8L("Preset \"%1%\" already exists.")) % m_preset_name).str());
        else
            info_line = from_u8((boost::format(_u8L("Preset \"%1%\" already exists and is incompatible with current printer.")) % m_preset_name).str());
        info_line += "\n" + _L("Please note that saving action will replace this preset");
        m_valid_type = Warning;
    }
    if (m_valid_type == Valid && m_preset_name.empty()) {
        info_line    = _L("The name is not allowed to be empty.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && m_preset_name.find_first_of(' ') == 0) {
        info_line    = _L("The name is not allowed to start with space character.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && m_preset_name.find_last_of(' ') == m_preset_name.length() - 1) {
        info_line    = _L("The name is not allowed to end with space character.");
        m_valid_type = NoValid;
    }
    if (m_valid_type == Valid && m_presets->get_preset_name_by_alias(m_preset_name) != m_preset_name) {
        info_line    = _L("The name cannot be the same as a preset alias name.");
        m_valid_type = NoValid;
    }
    // BBS: add project embedded presets logic
    if (existing) {
        if (existing->is_project_embedded) {
            m_radio_project->SetValue(true);
            m_save_to_project = true;
        } else {
            m_radio_user->SetValue(true);
            m_save_to_project = false;
        }
        m_radio_user->Disable();
        m_radio_project->Disable();
    } else {
        m_radio_user->Enable();
        m_radio_project->Enable();
        m_radio_user->SetValue(!m_save_to_project);
        m_radio_project->SetValue(m_save_to_project);
    }
    m_valid_label->SetLabel(info_line);
    m_valid_label->Show(!info_line.IsEmpty());
    // update_valid_bmp();
    if (m_type == Preset::TYPE_PRINTER) m_parent->update_info_for_edit_ph_printer(m_preset_name);
    m_parent->layout();
}
References _L, _u8L, Slic3r::GUI::from_u8(), Slic3r::PresetCollection::get_suffix_modified(), Slic3r::GUI::into_u8(), Slic3r::Preset::is_compatible, Slic3r::Preset::is_default, Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_system, NoValid, Slic3r::Preset::TYPE_PRINTER, Valid, and Warning.
Referenced by Item().
update_valid_bmp()
void Slic3r::GUI::SavePresetDialog::Item::update_valid_bmp ()
{
    std::string bmp_name = m_valid_type == Warning ? "obj_warning" : m_valid_type == NoValid ? "cross" : "blank_16";
    m_valid_bmp->SetBitmap(create_scaled_bitmap(bmp_name, m_parent));
}
References create_scaled_bitmap(), NoValid, and Warning.
Member Data Documentation
m_combo
wxComboBox* Slic3r::GUI::SavePresetDialog::Item::m_combo {nullptr}
m_input_ctrl
TextInput* Slic3r::GUI::SavePresetDialog::Item::m_input_ctrl {nullptr}
Referenced by Item(), and Slic3r::GUI::SavePresetDialog::input_name_from_other().
m_parent
SavePresetDialog* Slic3r::GUI::SavePresetDialog::Item::m_parent {nullptr}
Referenced by Item().
m_preset_name
std::string Slic3r::GUI::SavePresetDialog::Item::m_preset_name
Referenced by Item(), and preset_name().
m_presets
PresetCollection* Slic3r::GUI::SavePresetDialog::Item::m_presets {nullptr}
Referenced by Item().
m_radio_project
RadioBox* Slic3r::GUI::SavePresetDialog::Item::m_radio_project {nullptr}
Referenced by Item().
m_radio_user
RadioBox* Slic3r::GUI::SavePresetDialog::Item::m_radio_user {nullptr}
Referenced by Item().
m_save_to_project
bool Slic3r::GUI::SavePresetDialog::Item::m_save_to_project {false}
Referenced by Item(), and save_to_project().
m_type
Preset::Type Slic3r::GUI::SavePresetDialog::Item::m_type
Referenced by Item(), and type().
m_valid_bmp
wxStaticBitmap* Slic3r::GUI::SavePresetDialog::Item::m_valid_bmp {nullptr}
m_valid_label
wxStaticText* Slic3r::GUI::SavePresetDialog::Item::m_valid_label {nullptr}
Referenced by Item().
m_valid_type
ValidationType Slic3r::GUI::SavePresetDialog::Item::m_valid_type
Referenced by is_valid().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SavePresetDialog.hpp
src/slic3r/GUI/SavePresetDialog.cpp