OrcaSlicer: Slic3r::ModelInstance Class Reference
Slic3r::ModelInstance Class Reference final
#include <src/libslic3r/Model.hpp>
Public Types
using Timestamp = uint64_t
Public Member Functions
size_t get_labeled_id () const
ModelObject * get_object () const
const Geometry::Transformation & get_transformation () const
void set_transformation (const Geometry::Transformation &transformation)
const Geometry::Transformation & get_assemble_transformation () const
void set_assemble_transformation (const Geometry::Transformation &transformation)
void set_assemble_from_transform (Transform3d &transform)
void set_assemble_offset (const Vec3d &offset)
void rotate_assemble (double angle, const Vec3d &axis)
void set_offset_to_assembly (const Vec3d &offset)
Vec3d get_offset_to_assembly () const
const Vec3d & get_offset () const
double get_offset (Axis axis) const
void set_offset (const Vec3d &offset)
void set_offset (Axis axis, double offset)
const Vec3d & get_rotation () const
double get_rotation (Axis axis) const
void set_rotation (const Vec3d &rotation)
void set_rotation (Axis axis, double rotation)
void rotate (Matrix3d rotation_matrix)
const Vec3d & get_scaling_factor () const
double get_scaling_factor (Axis axis) const
void set_scaling_factor (const Vec3d &scaling_factor)
void set_scaling_factor (Axis axis, double scaling_factor)
const Vec3d & get_mirror () const
double get_mirror (Axis axis) const
bool is_left_handed () const
void set_mirror (const Vec3d &mirror)
void set_mirror (Axis axis, double mirror)
void transform_mesh (TriangleMesh *mesh, bool dont_translate=false) const
BoundingBoxf3 transform_mesh_bounding_box (const TriangleMesh &mesh, bool dont_translate=false) const
BoundingBoxf3 transform_bounding_box (const BoundingBoxf3 &bbox, bool dont_translate=false) const
Vec3d transform_vector (const Vec3d &v, bool dont_translate=false) const
void transform_polygon (Polygon *polygon) const
const Transform3d & get_matrix (bool dont_translate=false, bool dont_rotate=false, bool dont_scale=false, bool dont_mirror=false) const
bool is_printable () const
bool is_assemble_initialized ()
double get_auto_brim_width (double deltaT, double adhension) const
double get_auto_brim_width () const
Polygon convex_hull_2d ()
void invalidate_convex_hull_2d ()
void get_arrange_polygon (void *arrange_polygon, const Slic3r::DynamicPrintConfig &config=Slic3r::DynamicPrintConfig()) const
void apply_arrange_result (const Vec2d &offs, double rotation)
ObjectID id () const
virtual Timestamp timestamp () const
Public Attributes
ModelInstanceEPrintVolumeState print_volume_state
bool printable
bool use_loaded_id_for_label {false}
int arrange_order = 0
size_t loaded_id = 0
Protected Member Functions
ModelInstance (const ModelInstance &rhs)=default
void set_model_object (ModelObject *model_object)
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
ModelInstance (ModelObject *object)
ModelInstance (ModelObject *object, const ModelInstance &other)
ModelInstance (ModelInstance &&rhs)=delete
ModelInstance & operator= (const ModelInstance &rhs)=delete
ModelInstance & operator= (ModelInstance &&rhs)=delete
ModelInstance ()
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
Geometry::Transformation m_transformation
Geometry::Transformation m_assemble_transformation
Vec3d m_offset_to_assembly { 0.0, 0.0, 0.0 }
bool m_assemble_initialized
ModelObject * object
Polygon convex_hull
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class Print
class SLAPrint
class Model
class ModelObject
class cereal::access
class UndoRedo::StackImpl
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
ModelInstance() [1/5]
Slic3r::ModelInstance::ModelInstance (const ModelInstance & rhs) explicit protected default
ModelInstance() [2/5]
Slic3r::ModelInstance::ModelInstance (ModelObject * object) inline explicit private
: print_volume_state(ModelInstancePVS_Inside), printable(true), object(object), m_assemble_initialized(false) { assert(this->id().valid()); }
ModelInstance() [3/5]
Slic3r::ModelInstance::ModelInstance (ModelObject * object, const ModelInstance & other) inline explicit private
                                                                            :
        m_transformation(other.m_transformation)
        , m_assemble_transformation(other.m_assemble_transformation)
        , m_offset_to_assembly(other.m_offset_to_assembly)
        , print_volume_state(ModelInstancePVS_Inside)
        , printable(other.printable)
        , object(object)
        , m_assemble_initialized(false) { assert(this->id().valid() && this->id() != other.id()); }
References Slic3r::ObjectBase::id().
ModelInstance() [4/5]
Slic3r::ModelInstance::ModelInstance (ModelInstance && rhs) explicit private delete
ModelInstance() [5/5]
Slic3r::ModelInstance::ModelInstance () inline private
: ObjectBase(-1), object(nullptr) { assert(this->id().invalid()); }
Member Function Documentation
apply_arrange_result()
void Slic3r::ModelInstance::apply_arrange_result (const Vec2d & offs, double rotation) inline
    {
        // write the transformation data into the model instance
        set_rotation(Z, rotation);
        set_offset(X, unscale<double>(offs(X)));
        set_offset(Y, unscale<double>(offs(Y)));
        this->object->invalidate_bounding_box();
    }
References set_offset(), set_rotation(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
convex_hull_2d()
Polygon Slic3r::ModelInstance::convex_hull_2d ()
{
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": name %1%, is_valid %2%")% this->object->name.c_str()% convex_hull.is_valid();
    //if (!convex_hull.is_valid())
    { // this logic is not working right now, as moving instance doesn't update convex_hull
        const Transform3d& trafo_instance = get_matrix(false);
        convex_hull = get_object()->convex_hull_2d(trafo_instance);
    }
    //int size = convex_hull.size();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": convex_hull, point size %1%")% size;
    //for (int i = 0; i < size; i++)
    //    BOOST_LOG_TRIVIAL(info) << boost::format(": point %1%, position {%2%, %3%}")% i% convex_hull[i].x()% convex_hull[i].y();
    return convex_hull;
}
References convex_hull, Slic3r::ModelObject::convex_hull_2d(), get_matrix(), and get_object().
Referenced by Slic3r::GUI::PartPlate::check_outside(), and Slic3r::layered_print_cleareance_valid().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_arrange_polygon()
void Slic3r::ModelInstance::get_arrange_polygon (void * arrange_polygon, const Slic3r::DynamicPrintConfig & config = Slic3r::DynamicPrintConfig()) const
{
//    static const double SIMPLIFY_TOLERANCE_MM = 0.1;
    Vec3d rotation = get_rotation();
    rotation.z()   = 0.;
    Transform3d trafo_instance =
        Geometry::assemble_transform(get_offset().z() * Vec3d::UnitZ(), rotation, get_scaling_factor(), get_mirror());
    Polygon p = get_object()->convex_hull_2d(trafo_instance);
//    if (!p.points.empty()) {
//        Polygons pp{p};
//        pp = p.simplify(scaled<double>(SIMPLIFY_TOLERANCE_MM));
//        if (!pp.empty()) p = pp.front();
//    }
    arrangement::ArrangePolygon& ret = *(arrangement::ArrangePolygon*)ap;
    ret.poly.contour = std::move(p);
    ret.translation  = Vec2crd{scaled(get_offset(X)), scaled(get_offset(Y))};
    ret.rotation     = get_rotation(Z);
    //BBS: add materials related information
    ModelVolume *volume = NULL;
    for (size_t i = 0; i < object->volumes.size(); ++i) {
        if (object->volumes[i]->is_model_part()) {
            volume = object->volumes[i];
            if (!volume) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "invalid object, should not happen";
                return;
            }
            auto ve = object->volumes[i]->get_extruders();
            ret.extrude_ids.insert(ret.extrude_ids.end(), ve.begin(), ve.end());
        }
    }
    // get per-object support extruders
    auto op = object->get_config_value<ConfigOptionBool>(config_global, "enable_support");
    bool is_support_enabled = op && op->getBool();
    if (is_support_enabled) {
        auto op1 = object->get_config_value<ConfigOptionInt>(config_global, "support_filament");
        auto op2 = object->get_config_value<ConfigOptionInt>(config_global, "support_interface_filament");
        int extruder_id;
        // id==0 means follow previous material, so need not be recorded
        if (op1 && (extruder_id = op1->getInt()) > 0) ret.extrude_ids.push_back(extruder_id);
        if (op2 && (extruder_id = op2->getInt()) > 0) ret.extrude_ids.push_back(extruder_id);
    }
    if (ret.extrude_ids.empty()) //the default extruder
        ret.extrude_ids.push_back(1);
}
References Slic3r::Geometry::assemble_transform(), Slic3r::ExPolygon::contour, Slic3r::ModelObject::convex_hull_2d(), error, Slic3r::arrangement::ArrangePolygon::extrude_ids, get_mirror(), get_object(), get_offset(), get_rotation(), get_scaling_factor(), Slic3r::ConfigOptionBool::getBool(), Slic3r::ConfigOptionInt::getInt(), NULL, object, Slic3r::arrangement::ArrangePolygon::poly, Slic3r::arrangement::ArrangePolygon::rotation, Slic3r::scaled(), Slic3r::arrangement::ArrangePolygon::translation, Slic3r::ModelObject::volumes, Slic3r::X, Slic3r::Y, and Slic3r::Z.
get_assemble_transformation()
const Geometry::Transformation & Slic3r::ModelInstance::get_assemble_transformation () const inline
{ return m_assemble_transformation; }
References m_assemble_transformation.
Referenced by Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), and Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range().
get_auto_brim_width() [1/2]
double Slic3r::ModelInstance::get_auto_brim_width () const
{
    return 0.;
    double adhcoeff = getadhesionCoeff(object->volumes);
    double DeltaT = getTemperatureFromExtruder(object->volumes);
    // get auto brim width (Note even if the global brim_type=btOuterBrim, we can still go into this branch)
    return get_auto_brim_width(DeltaT, adhcoeff);
}
References get_auto_brim_width(), Slic3r::getadhesionCoeff(), Slic3r::getTemperatureFromExtruder(), object, and Slic3r::ModelObject::volumes.
Referenced by get_auto_brim_width().
get_auto_brim_width() [2/2]
double Slic3r::ModelInstance::get_auto_brim_width (double deltaT, double adhension) const
{
    BoundingBoxf3 raw_bbox = object->raw_mesh_bounding_box();
    double maxSpeed = Model::findMaxSpeed(object);
    auto bbox_size = transform_bounding_box(raw_bbox).size();
    double height_to_area = std::max(bbox_size(2) / (bbox_size(0) * bbox_size(0) * bbox_size(1)),
        bbox_size(2) / (bbox_size(1) * bbox_size(1) * bbox_size(0)));
    double thermalLength = sqrt(bbox_size(0)* bbox_size(0) + bbox_size(1)* bbox_size(1));
    double thermalLengthRef = Model::getThermalLength(object->volumes);
    double brim_width = adhension * std::min(std::min(std::max(height_to_area * 200 * maxSpeed/200, thermalLength * 8. / thermalLengthRef * std::min(bbox_size(2), 30.) / 30.), 20.), 1.5 * thermalLength);
    // small brims are omitted
    if (brim_width < 5 && brim_width < 1.5 * thermalLength)
        brim_width = 0;
    return brim_width;
}
References Slic3r::Model::findMaxSpeed(), Slic3r::Model::getThermalLength(), object, Slic3r::BoundingBox3Base< PointClass >::size(), sqrt(), transform_bounding_box(), and Slic3r::ModelObject::volumes.
Referenced by Slic3r::get_instance_arrange_poly().
get_labeled_id()
size_t Slic3r::ModelInstance::get_labeled_id () const inline
    {
        if (use_loaded_id_for_label && (loaded_id > 0))
            return loaded_id;
        else
            return id().id;
    }
References Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), loaded_id, and use_loaded_id_for_label.
get_matrix()
const Transform3d & Slic3r::ModelInstance::get_matrix (bool dont_translate = false, bool dont_rotate = false, bool dont_scale = false, bool dont_mirror = false) const inline
{ return m_transformation.get_matrix(dont_translate, dont_rotate, dont_scale, dont_mirror); }
References Slic3r::Geometry::Transformation::get_matrix(), and m_transformation.
Referenced by convex_hull_2d(), Slic3r::GUI::GLGizmoFaceDetector::display_exterior_face(), Slic3r::ModelObject::get_instance_max_z(), Slic3r::ModelObject::get_instance_min_z(), Slic3r::SlicingAdaptive::prepare(), rotate(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), transform_bounding_box(), transform_mesh(), transform_mesh_bounding_box(), and transform_vector().
get_mirror() [1/2]
const Vec3d & Slic3r::ModelInstance::get_mirror () const inline
{ return m_transformation.get_mirror(); }
References Slic3r::Geometry::Transformation::get_mirror(), and m_transformation.
Referenced by get_arrange_polygon(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate(), Slic3r::GUI::Plater::increase_instances(), Slic3r::layered_print_cleareance_valid(), Slic3r::Print::sequential_print_clearance_valid(), Slic3r::SLAPrint::sla_trafo(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
get_mirror() [2/2]
double Slic3r::ModelInstance::get_mirror (Axis axis) const inline
{ return m_transformation.get_mirror(axis); }
References Slic3r::Geometry::Transformation::get_mirror(), and m_transformation.
get_object()
ModelObject * Slic3r::ModelInstance::get_object () const inline
{ return this->object; }
References object.
Referenced by convex_hull_2d(), get_arrange_polygon(), Slic3r::get_instance_arrange_poly(), Slic3r::GUI::OrientJob::get_orient_mesh(), and Slic3r::orientation::orient().
get_offset() [1/2]
const Vec3d & Slic3r::ModelInstance::get_offset () const inline
{ return m_transformation.get_offset(); }
References Slic3r::Geometry::Transformation::get_offset(), and m_transformation.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::check_conflict_for_all_connectors(), Slic3r::duplicate(), get_arrange_polygon(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelObject::get_instance_max_z(), Slic3r::ModelObject::get_instance_min_z(), Slic3r::GUI::Plater::increase_instances(), Slic3r::invalidate_translations(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::SLAPrint::sla_trafo(), transform_mesh_bounding_box(), Slic3r::GUI::PartPlate::translate_all_instance(), Slic3r::ModelObject::translate_instance(), Slic3r::GUI::GLGizmoAdvancedCut::unproject_on_cut_plane(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
get_offset() [2/2]
double Slic3r::ModelInstance::get_offset (Axis axis) const inline
{ return m_transformation.get_offset(axis); }
References Slic3r::Geometry::Transformation::get_offset(), and m_transformation.
get_offset_to_assembly()
Vec3d Slic3r::ModelInstance::get_offset_to_assembly () const inline
{ return m_offset_to_assembly; }
References m_offset_to_assembly.
Referenced by Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), and Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range().
get_rotation() [1/2]
const Vec3d & Slic3r::ModelInstance::get_rotation () const inline
{ return m_transformation.get_rotation(); }
References Slic3r::Geometry::Transformation::get_rotation(), and m_transformation.
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), get_arrange_polygon(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::GUI::Plater::increase_instances(), Slic3r::layered_print_cleareance_valid(), Slic3r::Print::sequential_print_clearance_valid(), Slic3r::SLAPrint::sla_trafo(), transform_polygon(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
get_rotation() [2/2]
double Slic3r::ModelInstance::get_rotation (Axis axis) const inline
{ return m_transformation.get_rotation(axis); }
References Slic3r::Geometry::Transformation::get_rotation(), and m_transformation.
get_scaling_factor() [1/2]
const Vec3d & Slic3r::ModelInstance::get_scaling_factor () const inline
{ return m_transformation.get_scaling_factor(); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and m_transformation.
Referenced by get_arrange_polygon(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate(), Slic3r::GUI::Plater::increase_instances(), Slic3r::layered_print_cleareance_valid(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::Print::sequential_print_clearance_valid(), Slic3r::SLAPrint::sla_trafo(), transform_mesh_bounding_box(), transform_polygon(), Slic3r::PrintBase::update_object_placeholders(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
get_scaling_factor() [2/2]
double Slic3r::ModelInstance::get_scaling_factor (Axis axis) const inline
{ return m_transformation.get_scaling_factor(axis); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and m_transformation.
get_transformation()
const Geometry::Transformation & Slic3r::ModelInstance::get_transformation () const inline
{ return m_transformation; }
References m_transformation.
Referenced by Slic3r::GUI::PartPlate::add_instance(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::ModelObject::instance_bounding_box(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::PartPlate::set_pos_and_size(), and Slic3r::GUI::GLGizmoText::update_text_positions().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
invalidate_convex_hull_2d()
void Slic3r::ModelInstance::invalidate_convex_hull_2d ()
{
    convex_hull.clear();
}
References Slic3r::MultiPoint::clear(), and convex_hull.
is_assemble_initialized()
bool Slic3r::ModelInstance::is_assemble_initialized () inline
{ return m_assemble_initialized; }
References m_assemble_initialized.
is_left_handed()
bool Slic3r::ModelInstance::is_left_handed () const inline
{ return m_transformation.is_left_handed(); }
References Slic3r::Geometry::Transformation::is_left_handed(), and m_transformation.
Referenced by Slic3r::SlicingAdaptive::prepare(), and Slic3r::SLAPrint::sla_trafo().
is_printable()
bool Slic3r::ModelInstance::is_printable () const inline
{ return object->printable && printable && (print_volume_state == ModelInstancePVS_Inside); }
References Slic3r::ModelInstancePVS_Inside, print_volume_state, and printable.
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
operator=() [1/2]
ModelInstance & Slic3r::ModelInstance::operator= (const ModelInstance & rhs) private delete
operator=() [2/2]
ModelInstance & Slic3r::ModelInstance::operator= (ModelInstance && rhs) private delete
rotate()
void Slic3r::ModelInstance::rotate (Matrix3d rotation_matrix) inline
{
        // note: must remove scaling from transformation, otherwise auto-orientation with scaled objects will have problem
        auto R = get_matrix(true,false,true).matrix().block<3, 3>(0, 0);
        auto R_new = rotation_matrix * R;
        auto euler_angles = Geometry::extract_euler_angles(R_new);
        set_rotation(euler_angles);
    }
References Slic3r::Geometry::extract_euler_angles(), get_matrix(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), and set_rotation().
Referenced by Slic3r::GUI::OrientJob::get_orient_mesh(), and Slic3r::orientation::orient().
rotate_assemble()
void Slic3r::ModelInstance::rotate_assemble (double angle, const Vec3d & axis) inline
{
        m_assemble_transformation.set_rotation(m_assemble_transformation.get_rotation() + Geometry::extract_euler_angles(Eigen::Quaterniond(Eigen::AngleAxisd(angle, axis)).toRotationMatrix()));
    }
References Slic3r::angle(), Slic3r::Geometry::extract_euler_angles(), Slic3r::Geometry::Transformation::get_rotation(), m_assemble_transformation, Slic3r::Geometry::Transformation::set_rotation(), and Eigen::QuaternionBase< Derived >::toRotationMatrix().
serialize()
template<class Archive > void Slic3r::ModelInstance::serialize (Archive & ar) inline private
{
        ar(m_transformation, print_volume_state, printable, m_assemble_transformation, m_offset_to_assembly, m_assemble_initialized);
    }
References m_assemble_initialized, m_assemble_transformation, m_offset_to_assembly, m_transformation, print_volume_state, and printable.
set_assemble_from_transform()
void Slic3r::ModelInstance::set_assemble_from_transform (Transform3d & transform) inline
{
        m_assemble_initialized = true;
        m_assemble_transformation.set_from_transform(transform);
    }
References m_assemble_initialized, m_assemble_transformation, Slic3r::Geometry::Transformation::set_from_transform(), and Slic3r::transform().
set_assemble_offset()
void Slic3r::ModelInstance::set_assemble_offset (const Vec3d & offset) inline
{ m_assemble_transformation.set_offset(offset); }
References m_assemble_transformation, Slic3r::offset(), and Slic3r::Geometry::Transformation::set_offset().
set_assemble_transformation()
void Slic3r::ModelInstance::set_assemble_transformation (const Geometry::Transformation & transformation) inline
{
        m_assemble_initialized = true;
        m_assemble_transformation = transformation;
    }
References m_assemble_initialized, and m_assemble_transformation.
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_mirror() [1/2]
void Slic3r::ModelInstance::set_mirror (Axis axis, double mirror) inline
{ m_transformation.set_mirror(axis, mirror); }
References m_transformation, and Slic3r::Geometry::Transformation::set_mirror().
set_mirror() [2/2]
void Slic3r::ModelInstance::set_mirror (const Vec3d & mirror) inline
{ m_transformation.set_mirror(mirror); }
References m_transformation, and Slic3r::Geometry::Transformation::set_mirror().
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), and Slic3r::AMFParserContext::endDocument().
set_model_object()
void Slic3r::ModelInstance::set_model_object (ModelObject * model_object) inline protected
{ object = model_object; }
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_offset() [1/2]
void Slic3r::ModelInstance::set_offset (Axis axis, double offset) inline
{ m_transformation.set_offset(axis, offset); }
References m_transformation, Slic3r::offset(), and Slic3r::Geometry::Transformation::set_offset().
set_offset() [2/2]
void Slic3r::ModelInstance::set_offset (const Vec3d & offset) inline
{ m_transformation.set_offset(offset); }
References m_transformation, Slic3r::offset(), and Slic3r::Geometry::Transformation::set_offset().
Referenced by Slic3r::GUI::PartPlate::add_instance(), apply_arrange_result(), Slic3r::duplicate(), Slic3r::Model::duplicate_objects_grid(), Slic3r::AMFParserContext::endDocument(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::PartPlate::set_pos_and_size(), Slic3r::GUI::PartPlate::translate_all_instance(), and Slic3r::ModelObject::translate_instance().
set_offset_to_assembly()
void Slic3r::ModelInstance::set_offset_to_assembly (const Vec3d & offset) inline
{ m_offset_to_assembly = offset; }
References m_offset_to_assembly, and Slic3r::offset().
set_rotation() [1/2]
void Slic3r::ModelInstance::set_rotation (Axis axis, double rotation) inline
{ m_transformation.set_rotation(axis, rotation); }
References m_transformation, and Slic3r::Geometry::Transformation::set_rotation().
set_rotation() [2/2]
void Slic3r::ModelInstance::set_rotation (const Vec3d & rotation) inline
{ m_transformation.set_rotation(rotation); }
References m_transformation, and Slic3r::Geometry::Transformation::set_rotation().
Referenced by apply_arrange_result(), Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::AMFParserContext::endDocument(), and rotate().
set_scaling_factor() [1/2]
void Slic3r::ModelInstance::set_scaling_factor (Axis axis, double scaling_factor) inline
{ m_transformation.set_scaling_factor(axis, scaling_factor); }
References m_transformation, and Slic3r::Geometry::Transformation::set_scaling_factor().
set_scaling_factor() [2/2]
void Slic3r::ModelInstance::set_scaling_factor (const Vec3d & scaling_factor) inline
{ m_transformation.set_scaling_factor(scaling_factor); }
References m_transformation, and Slic3r::Geometry::Transformation::set_scaling_factor().
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::AMFParserContext::endDocument(), and Slic3r::GUI::Plater::priv::load_model_objects().
set_transformation()
void Slic3r::ModelInstance::set_transformation (const Geometry::Transformation & transformation) inline
{ m_transformation = transformation; }
References m_transformation.
Referenced by Slic3r::_3MF_Importer::_apply_transform(), and Slic3r::_BBS_3MF_Importer::_apply_transform().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
transform_bounding_box()
BoundingBoxf3 Slic3r::ModelInstance::transform_bounding_box (const BoundingBoxf3 & bbox, bool dont_translate = false) const
{
    return bbox.transformed(get_matrix(dont_translate));
}
References get_matrix(), and Slic3r::BoundingBoxf3::transformed().
Referenced by get_auto_brim_width().
transform_mesh()
void Slic3r::ModelInstance::transform_mesh (TriangleMesh * mesh, bool dont_translate = false) const
{
    mesh->transform(get_matrix(dont_translate));
}
References get_matrix(), and Slic3r::TriangleMesh::transform().
transform_mesh_bounding_box()
BoundingBoxf3 Slic3r::ModelInstance::transform_mesh_bounding_box (const TriangleMesh & mesh, bool dont_translate = false) const
{
    // Rotate around mesh origin.
    TriangleMesh copy(mesh);
    copy.transform(get_matrix(true, false, true, true));
    BoundingBoxf3 bbox = copy.bounding_box();
    if (!empty(bbox)) {
        // Scale the bounding box along the three axes.
        for (unsigned int i = 0; i < 3; ++i)
        {
            if (std::abs(get_scaling_factor((Axis)i)-1.0) > EPSILON)
            {
                bbox.min(i) *= get_scaling_factor((Axis)i);
                bbox.max(i) *= get_scaling_factor((Axis)i);
            }
        }
        // Translate the bounding box.
        if (! dont_translate) {
            bbox.min += get_offset();
            bbox.max += get_offset();
        }
    }
    return bbox;
}
References Slic3r::TriangleMesh::bounding_box(), Slic3r::empty(), EPSILON, get_matrix(), get_offset(), get_scaling_factor(), Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, and Slic3r::TriangleMesh::transform().
transform_polygon()
void Slic3r::ModelInstance::transform_polygon (Polygon * polygon) const
{
    // CHECK_ME -> Is the following correct or it should take in account all three rotations ?
    polygon->rotate(get_rotation(Z)); // rotate around polygon origin
    // CHECK_ME -> Is the following correct ?
    polygon->scale(get_scaling_factor(X), get_scaling_factor(Y)); // scale around polygon origin
}
References get_rotation(), get_scaling_factor(), Slic3r::MultiPoint::rotate(), Slic3r::MultiPoint::scale(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
transform_vector()
Vec3d Slic3r::ModelInstance::transform_vector (const Vec3d & v, bool dont_translate = false) const
{
    return get_matrix(dont_translate) * v;
}
References get_matrix().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Model
friend class Model friend
ModelObject
friend class ModelObject friend
Print
friend class Print friend
SLAPrint
friend class SLAPrint friend
UndoRedo::StackImpl
friend class UndoRedo::StackImpl friend
Member Data Documentation
arrange_order
int Slic3r::ModelInstance::arrange_order = 0
convex_hull
Polygon Slic3r::ModelInstance::convex_hull private
Referenced by convex_hull_2d(), and invalidate_convex_hull_2d().
loaded_id
size_t Slic3r::ModelInstance::loaded_id = 0
Referenced by Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), get_labeled_id(), Slic3r::Print::load_cached_data(), and Slic3r::GLVolumeCollection::load_object_volume().
m_assemble_initialized
bool Slic3r::ModelInstance::m_assemble_initialized private
Referenced by is_assemble_initialized(), serialize(), set_assemble_from_transform(), and set_assemble_transformation().
m_assemble_transformation
Geometry::Transformation Slic3r::ModelInstance::m_assemble_transformation private
Referenced by get_assemble_transformation(), rotate_assemble(), serialize(), set_assemble_from_transform(), set_assemble_offset(), and set_assemble_transformation().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_offset_to_assembly
Vec3d Slic3r::ModelInstance::m_offset_to_assembly { 0.0, 0.0, 0.0 } private
Referenced by get_offset_to_assembly(), serialize(), and set_offset_to_assembly().
m_transformation
Geometry::Transformation Slic3r::ModelInstance::m_transformation private
Referenced by get_matrix(), get_mirror(), get_mirror(), get_offset(), get_offset(), get_rotation(), get_rotation(), get_scaling_factor(), get_scaling_factor(), get_transformation(), is_left_handed(), serialize(), set_mirror(), set_mirror(), set_offset(), set_offset(), set_rotation(), set_rotation(), set_scaling_factor(), set_scaling_factor(), and set_transformation().
object
ModelObject* Slic3r::ModelInstance::object private
Referenced by get_arrange_polygon(), get_auto_brim_width(), get_auto_brim_width(), get_object(), and Slic3r::GUI::ObjectList::printable_state_changed().
print_volume_state
ModelInstanceEPrintVolumeState Slic3r::ModelInstance::print_volume_state
Referenced by is_printable(), and serialize().
printable
bool Slic3r::ModelInstance::printable
Referenced by Slic3r::_3MF_Importer::_create_object_instance(), Slic3r::_BBS_3MF_Importer::_create_object_instance(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::AMFParserContext::endDocument(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::GUI::PartPlate::has_printable_instances(), Slic3r::GUI::PartPlate::is_all_instances_unprintable(), is_printable(), Slic3r::GUI::PartPlate::printable_instance_size(), Slic3r::GUI::ObjectList::printable_state_changed(), Slic3r::CLI::run(), serialize(), and Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_object().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
use_loaded_id_for_label
bool Slic3r::ModelInstance::use_loaded_id_for_label {false}
Referenced by get_labeled_id().
The documentation for this class was generated from the following files:
src/libslic3r/Model.hpp
src/libslic3r/Model.cpp