OrcaSlicer: nlohmann::detail::out_of_range Class Reference
nlohmann::detail::out_of_range Class Reference
exception indicating access out of the defined range
#include <src/nlohmann/detail/exceptions.hpp>
Public Member Functions
const char * what () const noexcept override
returns the explanatory string
Static Public Member Functions
template<typename BasicJsonType >
static out_of_range create (int id_, const std::string &what_arg, const BasicJsonType &context)
Public Attributes
const int id
the id of the exception
Static Protected Member Functions
static std::string name (const std::string &ename, int id_)
template<typename BasicJsonType >
static std::string diagnostics (const BasicJsonType &leaf_element)
Private Member Functions
out_of_range (int id_, const char *what_arg)
Private Attributes
std::runtime_error m
an exception object as storage for error messages
Detailed Description
exception indicating access out of the defined range
This exception is thrown in case a library function is called on an input parameter that exceeds the expected range, for instance in case of array indices or nonexisting object keys.
Exceptions have ids 4xx.
name / id example message description
json.exception.out_of_range.401 array index 3 is out of range The provided array index i is larger than size-1.
json.exception.out_of_range.402 array index '-' (3) is out of range The special array index - in a JSON Pointer never describes a valid element of the array, but the index past the end. That is, it can only be used to add elements at this position, but not to read it.
json.exception.out_of_range.403 key 'foo' not found The provided key was not found in the JSON object.
json.exception.out_of_range.404 unresolved reference token 'foo' A reference token in a JSON Pointer could not be resolved.
json.exception.out_of_range.405 JSON pointer has no parent The JSON Patch operations 'remove' and 'add' can not be applied to the root element of the JSON value.
json.exception.out_of_range.406 number overflow parsing '10E1000' A parsed number could not be stored as without changing it to NaN or INF.
json.exception.out_of_range.407 number overflow serializing '9223372036854775808' UBJSON and BSON only support integer numbers up to 9223372036854775807. (until version 3.8.0)
json.exception.out_of_range.408 excessive array size: 8658170730974374167 The size (following #) of an UBJSON array or object exceeds the maximal capacity.
json.exception.out_of_range.409 BSON key cannot contain code point U+0000 (at byte 2) Key identifiers to be serialized to BSON cannot contain code point U+0000, since the key is stored as zero-terminated c-string
@liveexample{The following code shows how an out_of_range exception can be caught.,out_of_range}
See also
- exception for the base class of the library exceptions
- parse_error for exceptions indicating a parse error
- invalid_iterator for exceptions indicating errors with iterators
- type_error for exceptions indicating executing a member function with a wrong type
- other_error for exceptions indicating other library errors
Since
version 3.0.0
Constructor & Destructor Documentation
out_of_range()
nlohmann::detail::out_of_range::out_of_range (int id_, const char * what_arg) inline private
: exception(id_, what_arg) {}
Member Function Documentation
create()
template<typename BasicJsonType > static out_of_range nlohmann::detail::out_of_range::create (int id_, const std::string & what_arg, const BasicJsonType & context) inline static
    {
        std::string w = exception::name("out_of_range", id_) + exception::diagnostics(context) + what_arg;
        return out_of_range(id_, w.c_str());
    }
References nlohmann::detail::exception::diagnostics(), and nlohmann::detail::exception::name().
Referenced by nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), nlohmann::json_pointer< BasicJsonType >::back(), nlohmann::detail::binary_writer< BasicJsonType, CharType >::calc_bson_entry_header_size(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::erase(), nlohmann::json_pointer< BasicJsonType >::get_checked(), nlohmann::json_pointer< BasicJsonType >::get_checked(), nlohmann::json_pointer< BasicJsonType >::get_unchecked(), nlohmann::json_pointer< BasicJsonType >::get_unchecked(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::patch(), nlohmann::json_pointer< BasicJsonType >::pop_back(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal(), and nlohmann::detail::binary_writer< BasicJsonType, CharType >::write_bson_unsigned().
diagnostics()
template<typename BasicJsonType > static std::string nlohmann::detail::exception::diagnostics (const BasicJsonType & leaf_element) inline static protected inherited
    {
#if JSON_DIAGNOSTICS
        std::vector<std::string> tokens;
        for (const auto* current = &leaf_element; current->m_parent != nullptr; current = current->m_parent)
        {
            switch (current->m_parent->type())
            {
                case value_t::array:
                {
                    for (std::size_t i = 0; i < current->m_parent->m_value.array->size(); ++i)
                    {
                        if (&current->m_parent->m_value.array->operator[](i) == current)
{
                            tokens.emplace_back(std::to_string(i));
                            break;
                        }
                    }
                    break;
                }
                case value_t::object:
                {
                    for (const auto& element : *current->m_parent->m_value.object)
                    {
                        if (&element.second == current)
{
                            tokens.emplace_back(element.first.c_str());
                            break;
                        }
                    }
                    break;
                }
                case value_t::null: // LCOV_EXCL_LINE
                case value_t::string: // LCOV_EXCL_LINE
                case value_t::boolean: // LCOV_EXCL_LINE
                case value_t::number_integer: // LCOV_EXCL_LINE
                case value_t::number_unsigned: // LCOV_EXCL_LINE
                case value_t::number_float: // LCOV_EXCL_LINE
                case value_t::binary: // LCOV_EXCL_LINE
                case value_t::discarded: // LCOV_EXCL_LINE
                default:   // LCOV_EXCL_LINE
                    break; // LCOV_EXCL_LINE
            }
        }
        if (tokens.empty())
        {
            return "";
        }
        return "(" + std::accumulate(tokens.rbegin(), tokens.rend(), std::string{},
                                     [](const std::string & a, const std::string & b)
        {
            return a + "/" + detail::escape(b);
        }) + ") ";
#else
        static_cast<void>(leaf_element);
        return "";
#endif
    }
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::detail::parse_error::create(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::type_error::create(), create(), nlohmann::detail::other_error::create(), and nlohmann::detail::parse_error::create().
name()
static std::string nlohmann::detail::exception::name (const std::string & ename, int id_) inline static protected inherited
    {
        return "[json.exception." + ename + "." + std::to_string(id_) + "] ";
    }
Referenced by nlohmann::detail::parse_error::create(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::type_error::create(), create(), nlohmann::detail::other_error::create(), and nlohmann::detail::parse_error::create().
what()
const char * nlohmann::detail::exception::what () const inline override noexcept inherited
returns the explanatory string
    {
        return m.what();
    }
References nlohmann::detail::exception::m.
Referenced by Slic3r::PresetUpdater::priv::get_cached_plugins_version(), Slic3r::get_values_from_json(), Slic3r::get_version_from_json(), Slic3r::GUI::GuideFrame::GetFilamentInfo(), Slic3r::AppConfig::load(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::GUI::GuideFrame::LoadProfileFamily(), and Slic3r::GUI::UpdatePluginDialog::update_info().
Member Data Documentation
id
const int nlohmann::detail::exception::id inherited
the id of the exception
m
std::runtime_error nlohmann::detail::exception::m private inherited
an exception object as storage for error messages
Referenced by nlohmann::detail::exception::what().
The documentation for this class was generated from the following file:
src/nlohmann/detail/exceptions.hpp