OrcaSlicer: Slic3r::ConfigDef Class Reference
Slic3r::ConfigDef Class Reference
#include <src/libslic3r/Config.hpp>
Public Member Functions
bool has (const t_config_option_key &opt_key) const
const ConfigOptionDef * get (const t_config_option_key &opt_key) const
std::vector< std::string > keys () const
std::ostream & print_cli_help (std::ostream &out, bool show_defaults, std::function< bool(const ConfigOptionDef &)> filter=[](const ConfigOptionDef &){ return true;}) const
Public Attributes
t_optiondef_map options
std::map< size_t, const ConfigOptionDef * > by_serialization_key_ordinal
Protected Member Functions
ConfigOptionDef * add (const t_config_option_key &opt_key, ConfigOptionType type)
ConfigOptionDef * add_nullable (const t_config_option_key &opt_key, ConfigOptionType type)
Detailed Description
Member Function Documentation
add()
ConfigOptionDef * Slic3r::ConfigDef::add (const t_config_option_key & opt_key, ConfigOptionType type) protected
{
  static size_t serialization_key_ordinal_last = 0;
    ConfigOptionDef *opt = &this->options[opt_key];
    opt->opt_key = opt_key;
    opt->type = type;
    opt->serialization_key_ordinal = ++ serialization_key_ordinal_last;
    this->by_serialization_key_ordinal[opt->serialization_key_ordinal] = opt;
    return opt;
}
References by_serialization_key_ordinal, Slic3r::ConfigOptionDef::opt_key, options, Slic3r::ConfigOptionDef::serialization_key_ordinal, and Slic3r::ConfigOptionDef::type.
Referenced by Slic3r::CLIMiscConfigDef::CLIMiscConfigDef(), Slic3r::CLITransformConfigDef::CLITransformConfigDef(), add_nullable(), Slic3r::PrintConfigDef::init_common_params(), Slic3r::PrintConfigDef::init_fff_params(), and Slic3r::PrintConfigDef::init_sla_params().
add_nullable()
ConfigOptionDef * Slic3r::ConfigDef::add_nullable (const t_config_option_key & opt_key, ConfigOptionType type) protected
{
  ConfigOptionDef *def = this->add(opt_key, type);
  def->nullable = true;
  return def;
}
References add(), and Slic3r::ConfigOptionDef::nullable.
Referenced by Slic3r::PrintConfigDef::init_fff_params().
get()
const ConfigOptionDef * Slic3r::ConfigDef::get (const t_config_option_key & opt_key) const inline
{
        t_optiondef_map::iterator it = const_cast<ConfigDef*>(this)->options.find(opt_key);
        return (it == this->options.end()) ? nullptr : &it->second;
    }
References options.
Referenced by Slic3r::GUI::PageDiameters::PageDiameters(), Slic3r::GUI::PageTemperatures::PageTemperatures(), Slic3r::PhysicalPrinterCollection::PhysicalPrinterCollection(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::change_opt_value(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::StaticPrintConfig::StaticCache< T >::finalize(), Slic3r::ConfigBase::get_abs_value(), Slic3r::GUI::SettingsFactory::get_bundle(), Slic3r::GUI::ConfigOptionsGroup::get_config_value(), Slic3r::GUI::ConfigOptionsGroup::get_config_value2(), Slic3r::GUI::get_full_label(), Slic3r::GUI::get_full_settings_hierarchy(), Slic3r::GUI::ConfigOptionsGroup::get_option(), Slic3r::GUI::get_string_value(), Slic3r::ConfigBase::load_from_json(), Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::DynamicConfig::optptr(), cereal::save(), Slic3r::client::MyContext::scalar_variable_reference(), Slic3r::StaticConfig::set_defaults(), Slic3r::ConfigBase::set_deserialize_raw(), Slic3r::GUI::PageMaterials::sort_list_data(), Slic3r::GUI::TabPrint::toggle_options(), Slic3r::GLVolumeCollection::update_colors_by_extruder(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::validate(), and Slic3r::Print::validate().
has()
bool Slic3r::ConfigDef::has (const t_config_option_key & opt_key) const inline
{ return this->options.count(opt_key) > 0; }
Referenced by Slic3r::PrintConfigDef::handle_legacy(), and Slic3r::CLI::setup().
keys()
std::vector< std::string > Slic3r::ConfigDef::keys () const inline
{
        std::vector<std::string> out;
        out.reserve(options.size());
        for(auto const& kvp : options)
            out.push_back(kvp.first);
        return out;
    }
References options, and out.
print_cli_help()
std::ostream & Slic3r::ConfigDef::print_cli_help (std::ostream & out, bool show_defaults, std::function< bool(const ConfigOptionDef &)> filter = [](const ConfigOptionDef &){ return true; }) const
{
    // prepare a function for wrapping text
    auto wrap = [](std::string text, size_t line_length) -> std::string {
        std::istringstream words(text);
        std::ostringstream wrapped;
        std::string word;
        if (words >> word) {
            wrapped << word;
            size_t space_left = line_length - word.length();
            while (words >> word) {
                if (space_left < word.length() + 1) {
                    wrapped << '\n' << word;
                    space_left = line_length - word.length();
                } else {
                    wrapped << ' ' << word;
                    space_left -= word.length() + 1;
                }
            }
        }
        return wrapped.str();
    };
    // get the unique categories
    std::set<std::string> categories;
    for (const auto& opt : this->options) {
        const ConfigOptionDef& def = opt.second;
        if (filter(def))
            categories.insert(def.category);
    }
    for (auto category : categories) {
        if (category != "") {
            out << category << ":" << std::endl;
        } else if (categories.size() > 1) {
            out << "Misc options:" << std::endl;
        }
        for (const auto& opt : this->options) {
            const ConfigOptionDef& def = opt.second;
      if (def.category != category || def.cli == ConfigOptionDef::nocli || !filter(def))
                continue;
            // get all possible variations: --foo, --foobar, -f...
            std::vector<std::string> cli_args = def.cli_args(opt.first);
      if (cli_args.empty())
        continue;
            for (auto& arg : cli_args) {
                arg.insert(0, (arg.size() == 1) ? "-" : "--");
                //BBS: refine the print help format
                if (!def.cli_params.empty())
                    arg += " " + def.cli_params;
                /*if ( def.type == coInt || def.type == coInts) {
                    arg += " int_value";
                } else if (def.type == coFloat ||  def.type == coFloatOrPercent || def.type == coFloats) {
                    arg += " float_value";
                } else if (def.type == coPoint) {
                    arg += " X,Y";
                } else if (def.type == coPoint3) {
                    arg += " X,Y,Z";
                } else if (def.type == coString || def.type == coStrings) {
                    arg += " filename_lists";
                }*/
            }
            // left: command line options
            const std::string cli = boost::algorithm::join(cli_args, ", ");
            out << " " << std::left << std::setw(20) << cli;
            // right: option description
            std::string descr = def.tooltip;
            bool show_defaults_this = show_defaults || def.opt_key == "config_compatibility";
            if (show_defaults_this && def.default_value && def.type != coBool
                && (def.type != coString || !def.default_value->serialize().empty())) {
                descr += " (";
                if (!def.sidetext.empty()) {
                    descr += def.sidetext + ", ";
                } else if (!def.enum_values.empty()) {
                    descr += boost::algorithm::join(def.enum_values, ", ") + "; ";
                }
                descr += "default: " + def.default_value->serialize() + ")";
            }
            // wrap lines of description
            descr = wrap(descr, 80);
            std::vector<std::string> lines;
            boost::split(lines, descr, boost::is_any_of("\n"));
            // if command line options are too long, print description in new line
            for (size_t i = 0; i < lines.size(); ++i) {
                if (i == 0 && cli.size() > 19)
                    out << std::endl;
                if (i > 0 || cli.size() > 19)
                    out << std::string(21, ' ');
                out << lines[i] << std::endl;
            }
        }
    }
    return out;
}
References arg(), Slic3r::ConfigOptionDef::category, Slic3r::ConfigOptionDef::cli, Slic3r::ConfigOptionDef::cli_args(), Slic3r::ConfigOptionDef::cli_params, Slic3r::coBool, Slic3r::coString, Slic3r::ConfigOptionDef::default_value, Slic3r::ConfigOptionDef::enum_values, Slic3r::ConfigOptionDef::nocli, Slic3r::ConfigOptionDef::opt_key, options, out, Slic3r::ConfigOptionDef::sidetext, Slic3r::ConfigOptionDef::tooltip, and Slic3r::ConfigOptionDef::type.
Referenced by Slic3r::CLI::print_help().
Member Data Documentation
by_serialization_key_ordinal
std::map<size_t, const ConfigOptionDef*> Slic3r::ConfigDef::by_serialization_key_ordinal
Referenced by Slic3r::DynamicPrintAndCLIConfig::PrintAndCLIConfigDef::PrintAndCLIConfigDef(), add(), and cereal::load().
options
t_optiondef_map Slic3r::ConfigDef::options
Referenced by Slic3r::DynamicPrintAndCLIConfig::PrintAndCLIConfigDef::PrintAndCLIConfigDef(), Slic3r::PrintConfigDef::PrintConfigDef(), Slic3r::DynamicPrintAndCLIConfig::PrintAndCLIConfigDef::~PrintAndCLIConfigDef(), add(), Slic3r::Search::OptionsSearcher::append_options(), Slic3r::StaticPrintConfig::StaticCache< T >::finalize(), get(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::get_string_from_enum(), Slic3r::DynamicPrintAndCLIConfig::handle_legacy(), Slic3r::PrintConfigDef::init_fff_params(), keys(), Slic3r::StaticConfig::keys(), Slic3r::ConfigBase::load_from_json(), print_cli_help(), Slic3r::DynamicConfig::read_cli(), Slic3r::ConfigBase::set_deserialize_raw(), and Slic3r::CLI::setup().
The documentation for this class was generated from the following files:
src/libslic3r/Config.hpp
src/libslic3r/Config.cpp