OrcaSlicer: StateColor Class Reference
StateColor Class Reference
#include <src/slic3r/GUI/Widgets/StateColor.hpp>
Public Types
enum State {
Normal = 0 , Enabled = 1 , Checked = 2 , Focused = 4 ,
Hovered = 8 , Pressed = 16 , Disabled = 1 << 16 , NotChecked = 2 << 16 ,
NotFocused = 4 << 16 , NotHovered = 8 << 16 , NotPressed = 16 << 16
}
Public Member Functions
template<typename ... Colors>
StateColor (std::pair< Colors, int >... colors)
StateColor (wxColour const &color)
StateColor (wxString const &color)
StateColor (unsigned long color)
void append (wxColour const &color, int states)
void append (wxString const &color, int states)
void append (unsigned long color, int states)
void clear ()
int count () const
int states () const
wxColour defaultColor ()
wxColour colorForStates (int states)
wxColour colorForStatesNoDark (int states)
int colorIndexForStates (int states)
bool setColorForStates (wxColour const &color, int states)
void setTakeFocusedAsHovered (bool set)
Static Public Member Functions
static void SetDarkMode (bool dark)
static std::map< wxColour, wxColour > const & GetDarkMap ()
static wxColour darkModeColorFor (wxColour const &color)
static wxColour lightModeColorFor (wxColour const &color)
Private Member Functions
template<typename Color , typename ... Colors>
void fill (std::pair< Color, int > color, std::pair< Colors, int >... colors)
template<typename Color >
void fillOne (std::pair< Color, int > color)
void fill ()
Private Attributes
std::vector< int > statesList_
std::vector< wxColour > colors_
bool takeFocusedAsHovered_ = true
Detailed Description
Member Enumeration Documentation
State
enum StateColor::State
Enumerator
Normal
Enabled
Checked
Focused
Hovered
Pressed
Disabled
NotChecked
NotFocused
NotHovered
NotPressed
               {
        Normal = 0,
        Enabled = 1,
        Checked = 2,
        Focused = 4,
        Hovered = 8,
        Pressed = 16,
        Disabled = 1 << 16,
        NotChecked = 2 << 16,
        NotFocused = 4 << 16,
        NotHovered = 8 << 16,
        NotPressed = 16 << 16,
    };
Constructor & Destructor Documentation
StateColor() [1/4]
template<typename ... Colors> StateColor::StateColor (std::pair< Colors, int >... colors) inline
{
        fill(colors...);
    }
References fill().
StateColor() [2/4]
StateColor::StateColor (wxColour const & color)
{ append(color, 0); }
References append().
StateColor() [3/4]
StateColor::StateColor (wxString const & color)
{ append(color, 0); }
References append().
StateColor() [4/4]
StateColor::StateColor (unsigned long color)
{ append(color, 0); }
References append().
Member Function Documentation
append() [1/3]
void StateColor::append (unsigned long color, int states)
{
    if ((color & 0xff000000) == 0)
        color |= 0xff000000;
    wxColour cl; cl.SetRGBA(color & 0xff00ff00 | ((color & 0xff) << 16) | ((color >> 16) & 0xff));
    append(cl, states);
}
References append(), and states().
append() [2/3]
void StateColor::append (wxColour const & color, int states)
{
    statesList_.push_back(states);
    colors_.push_back(color);
}
References colors_, states(), and statesList_.
Referenced by AxisCtrlButton::AxisCtrlButton(), StateColor(), StateColor(), StateColor(), append(), append(), and fillOne().
append() [3/3]
void StateColor::append (wxString const & color, int states)
{
    wxColour c1(color);
    append(c1, states);
}
References append(), and states().
clear()
void StateColor::clear ()
{
    statesList_.clear();
    colors_.clear();
}
References colors_, and statesList_.
colorForStates()
wxColour StateColor::colorForStates (int states)
{
    bool focused = takeFocusedAsHovered_ && (states & Focused);
    for (int i = 0; i < statesList_.size(); ++i) {
        int s = statesList_[i];
        int on = s & 0xffff;
        int off = s >> 16;
        if ((on & states) == on && (off & ~states) == off) {
            return darkModeColorFor2(colors_[i]);
        }
        if (focused && (on & Hovered)) {
            on |= Focused;
            on &= ~Hovered;
            if ((on & states) == on && (off & ~states) == off) {
                return darkModeColorFor2(colors_[i]);
            }
        }
    }
    return wxColour(0, 0, 0, 0);
}
References colors_, darkModeColorFor2(), Focused, Hovered, states(), statesList_, and takeFocusedAsHovered_.
Referenced by SpinInput::Create(), TextInput::Create(), TempInput::Create(), defaultColor(), StaticBox::doRender(), StepCtrl::doRender(), StepIndicator::doRender(), TabCtrl::doRender(), SideButton::dorender(), TextInput::Enable(), SpinInput::Enable(), AxisCtrlButton::render(), Button::render(), DropDown::render(), ImageSwitchButton::render(), FanSwitchButton::render(), SpinInput::render(), TempInput::render(), TextInput::render(), and SwitchButton::Rescale().
colorForStatesNoDark()
wxColour StateColor::colorForStatesNoDark (int states)
{
    bool focused = takeFocusedAsHovered_ && (states & Focused);
    for (int i = 0; i < statesList_.size(); ++i) {
        int s = statesList_[i];
        int on = s & 0xffff;
        int off = s >> 16;
        if ((on & states) == on && (off & ~states) == off) {
            return colors_[i];
        }
        if (focused && (on & Hovered)) {
            on |= Focused;
            on &= ~Hovered;
            if ((on & states) == on && (off & ~states) == off) {
                return colors_[i];
            }
        }
    }
    return wxColour(0, 0, 0, 0);
}
References colors_, Focused, Hovered, states(), statesList_, and takeFocusedAsHovered_.
colorIndexForStates()
int StateColor::colorIndexForStates (int states)
{
    for (int i = 0; i < statesList_.size(); ++i) {
        int s   = statesList_[i];
        int on  = s & 0xffff;
        int off = s >> 16;
        if ((on & states) == on && (off & ~states) == off) { return i; }
    }
    return -1;
}
References states(), and statesList_.
count()
int StateColor::count () const inline
{ return statesList_.size(); }
References statesList_.
Referenced by StaticBox::doRender(), and SwitchButton::Rescale().
darkModeColorFor()
wxColour StateColor::darkModeColorFor (wxColour const & color) static
{ return darkModeColorFor2(color); }
References darkModeColorFor2().
Referenced by Slic3r::GUI::AuFile::AuFile(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineObjectPanel::MachineObjectPanel(), Slic3r::GUI::MappingContainer::MappingContainer(), Slic3r::GUI::MappingItem::MappingItem(), Slic3r::Search::SearchItem::SearchItem(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::add_msg_content(), Slic3r::GUI::UnsavedChangesDialog::build(), TempInput::Create(), Slic3r::GUI::SelectMachineDialog::create_ams_checkbox(), Slic3r::GUI::SelectMachineDialog::create_item_checkbox(), WebView::CreateWebView(), Slic3r::GUI::BBLSplashScreen::Decorate(), Slic3r::GUI::MachineObjectPanel::doRender(), Slic3r::GUI::AMSItem::doRender(), Slic3r::GUI::FanOperate::doRender(), Slic3r::GUI::SideTools::doRender(), SideButton::dorender(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::draw_text(), Slic3r::Search::SearchItem::DrawTextString(), Slic3r::GUI::ObjectTablePanel::load_data(), Slic3r::GUI::BBLSplashScreen::MakeBitmap(), Slic3r::GUI::InputIpAddressDialog::on_check_ip_address_failed(), Slic3r::Search::SearchItem::on_mouse_enter(), Slic3r::Search::SearchItem::on_mouse_leave(), Slic3r::Search::SearchItem::on_mouse_left_down(), Slic3r::GUI::StatusPanel::on_switch_speed(), Slic3r::GUI::InputIpAddressDialog::on_text(), Slic3r::GUI::OG_CustomCtrl::OnPaint(), TabButtonsListCtrl::OnPaint(), Slic3r::GUI::KBShortcutsDialog::OnSelectTabel(), Slic3r::GUI::AuFile::PaintBackground(), Slic3r::GUI::AMSMaterialsSetting::paintEvent(), Slic3r::GUI::AMSrefresh::paintEvent(), Slic3r::GUI::AuFile::PaintForeground(), Slic3r::GUI::ImageGrid::render(), AxisCtrlButton::render(), DropDown::render(), StaticLine::render(), TempInput::render(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::render(), Slic3r::GUI::ColorPickerPopup::set_ams_colours(), Slic3r::GUI::BBLSplashScreen::SetText(), Slic3r::GUI::MsgDialog::show_dsa_button(), Slic3r::Search::SearchDialog::update_list(), WipingPanel::update_warning_texts(), and Slic3r::GUI::GUI_App::UpdateDarkUI().
defaultColor()
wxColour StateColor::defaultColor ()
{
    return colorForStates(0);
}
References colorForStates().
Referenced by DropDown::render().
fill() [1/2]
void StateColor::fill () inline private
                {
    }
Referenced by StateColor(), and fill().
fill() [2/2]
template<typename Color , typename ... Colors> void StateColor::fill (std::pair< Color, int > color, std::pair< Colors, int >... colors) inline private
{
        fillOne(color);
        fill(colors...);
    }
References fill(), and fillOne().
fillOne()
template<typename Color > void StateColor::fillOne (std::pair< Color, int > color) inline private
{
        append(color.first, color.second);
    }
References append().
Referenced by fill().
GetDarkMap()
std::map< wxColour, wxColour > const & StateColor::GetDarkMap () static
{
    return gDarkColors;
}
References gDarkColors.
lightModeColorFor()
wxColour StateColor::lightModeColorFor (wxColour const & color) static
{
    static std::map<wxColour, wxColour> gLightColors = revert(gDarkColors);
    auto iter = gLightColors.find(color);
    wxASSERT(iter != gLightColors.end());
    if (iter != gLightColors.end()) return iter->second;
    return color;
}
References gDarkColors, and revert().
Referenced by Slic3r::GUI::GUI_App::UpdateDarkUI().
setColorForStates()
bool StateColor::setColorForStates (wxColour const & color, int states)
{
    for (int i = 0; i < statesList_.size(); ++i) {
        if (statesList_[i] == states) {
            colors_[i] = color;
            return true;
        }
    }
    return false;
}
References colors_, states(), and statesList_.
Referenced by StaticBox::SetBackgroundColorNormal(), StaticBox::SetBorderColorNormal(), and Button::SetTextColorNormal().
SetDarkMode()
void StateColor::SetDarkMode (bool dark) static
{ gDarkMode = dark; }
References gDarkMode.
Referenced by Slic3r::GUI::GUI_App::init_label_colours().
setTakeFocusedAsHovered()
void StateColor::setTakeFocusedAsHovered (bool set)
{ takeFocusedAsHovered_ = set; }
References takeFocusedAsHovered_.
states()
int StateColor::states () const
{
    int states = 0;
    for (auto s : statesList_) states |= s;
    states = (states & 0xffff) | (states >> 16);
    if (takeFocusedAsHovered_ && (states & Hovered))
        states |= Focused;
    return states;
}
References Focused, Hovered, states(), statesList_, and takeFocusedAsHovered_.
Referenced by append(), append(), append(), colorForStates(), colorForStatesNoDark(), colorIndexForStates(), setColorForStates(), and states().
Member Data Documentation
colors_
std::vector<wxColour> StateColor::colors_ private
Referenced by append(), clear(), colorForStates(), colorForStatesNoDark(), and setColorForStates().
statesList_
std::vector<int> StateColor::statesList_ private
Referenced by append(), clear(), colorForStates(), colorForStatesNoDark(), colorIndexForStates(), count(), setColorForStates(), and states().
takeFocusedAsHovered_
bool StateColor::takeFocusedAsHovered_ = true private
Referenced by colorForStates(), colorForStatesNoDark(), setTakeFocusedAsHovered(), and states().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/StateColor.hpp
src/slic3r/GUI/Widgets/StateColor.cpp