OrcaSlicer: src/mcut/include/mcut/internal/frontend.h File Reference
frontend.h File Reference
#include "mcut/mcut.h"
#include <future>
#include <map>
#include <memory>
#include <string>
#include "mcut/internal/tpool.h"
#include "mcut/internal/kernel.h"
Classes
struct connected_component_t
struct fragment_cc_t
struct patch_cc_t
struct seam_cc_t
struct input_cc_t
struct event_t
struct context_t
struct context_t::debug_log_msg_t
struct event_t.m_callback_info
Macros
#define CATCH_POSSIBLE_EXCEPTIONS(logstr)
Functions
void create_context_impl (McContext *pContext, McFlags flags, uint32_t num_helper_threads) noexcept(false)
void debug_message_callback_impl (McContext context, pfn_mcDebugOutput_CALLBACK cb, const McVoid *userParam) noexcept(false)
void get_debug_message_log_impl (McContext context, McUint32 count, McSize bufSize, McDebugSource *sources, McDebugType *types, McDebugSeverity *severities, McSize *lengths, McChar *messageLog, McUint32 &numFetched)
void debug_message_control_impl (McContext context, McDebugSource source, McDebugType type, McDebugSeverity severity, bool enabled) noexcept(false)
void get_info_impl (const McContext context, McFlags info, McSize bytes, McVoid *pMem, McSize *pNumBytes) noexcept(false)
void bind_state_impl (const McContext context, McFlags stateInfo, McSize bytes, const McVoid *pMem)
void create_user_event_impl (McEvent *event, McContext context)
void set_user_event_status_impl (McEvent event, McInt32 execution_status)
void get_event_info_impl (const McEvent event, McFlags info, McSize bytes, McVoid *pMem, McSize *pNumBytes) noexcept(false)
void set_event_callback_impl (McEvent eventHandle, pfn_McEvent_CALLBACK eventCallback, McVoid *data)
void wait_for_events_impl (uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McResult &runtimeStatusFromAllPrecedingEvents) noexcept(false)
void dispatch_impl (McContext context, McFlags flags, const McVoid *pSrcMeshVertices, const uint32_t *pSrcMeshFaceIndices, const uint32_t *pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid *pCutMeshVertices, const uint32_t *pCutMeshFaceIndices, const uint32_t *pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent) noexcept(false)
void dispatch_planar_section_impl (McContext context, McFlags flags, const McVoid *pSrcMeshVertices, const uint32_t *pSrcMeshFaceIndices, const uint32_t *pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McDouble *pNormalVector, const McDouble sectionOffset, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent) noexcept(false)
void get_connected_components_impl (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent *pConnComps, uint32_t *numConnComps, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent) noexcept(false)
void get_connected_component_data_impl (const McContext context, const McConnectedComponent connCompId, McFlags flags, McSize bytes, McVoid *pMem, McSize *pNumBytes, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent) noexcept(false)
void release_connected_components_impl (const McContext context, uint32_t numConnComps, const McConnectedComponent *pConnComps) noexcept(false)
void release_context_impl (McContext context) noexcept(false)
void release_events_impl (uint32_t numEvents, const McEvent *pEvents)
template<typename Derived >
void fn_delete_cc (connected_component_t *p)
Variables
thread_local std::string per_thread_api_log_str
threadsafe_list< std::shared_ptr< event_t > > g_events
std::atomic< std::uintptr_t > g_objects_counter
std::once_flag g_objects_counter_init_flag
threadsafe_list< std::shared_ptr< context_t > > g_contexts
Class Documentation
context_t::debug_log_msg_t
struct context_t::debug_log_msg_t
Class Members
McDebugSeverity severity
McDebugSource source
string str
McDebugType type
event_t.m_callback_info
struct event_t.m_callback_info
Class Members
McVoid * m_data_ptr
pfn_McEvent_CALLBACK m_fn_ptr
atomic< bool > m_invoked
Macro Definition Documentation
CATCH_POSSIBLE_EXCEPTIONS
#define CATCH_POSSIBLE_EXCEPTIONS (logstr)
Value:
    catch (std::invalid_argument & e0)                 \
    {                                                  \
        logstr = e0.what();                            \
        return_value = McResult::MC_INVALID_VALUE;     \
    }                                                  \
    catch (std::runtime_error & e1)                    \
    {                                                  \
        logstr = e1.what();                            \
        return_value = McResult::MC_INVALID_OPERATION; \
    }                                                  \
    catch (std::logic_error & e2)                      \
    {                                                  \
        logstr = e2.what();                            \
        return_value = McResult::MC_RESULT_MAX_ENUM;   \
    }                                                  \
    catch (std::exception & e3)                        \
    {                                                  \
        logstr = e3.what();                            \
        return_value = McResult::MC_RESULT_MAX_ENUM;   \
    }
Function Documentation
bind_state_impl()
void bind_state_impl (const McContext context, McFlags stateInfo, McSize bytes, const McVoid * pMem)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == context; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    switch (stateInfo) {
    case MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT: {
        McDouble value;
        memcpy(&value, pMem, bytes);
        context_ptr->dbg_cb(MC_DEBUG_SOURCE_API, MC_DEBUG_TYPE_OTHER, 0, MC_DEBUG_SEVERITY_NOTIFICATION, "general coords enforcement constant set to " + std::to_string(value));
        if (value <= 0) {
            throw std::invalid_argument("invalid general coords enforcement constant");
        }
        context_ptr->set_general_position_enforcement_constant(value);
    } break;
    case MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS: {
        McUint32 value;
        memcpy(&value, pMem, bytes);
        context_ptr->dbg_cb(MC_DEBUG_SOURCE_API, MC_DEBUG_TYPE_OTHER, 0, MC_DEBUG_SEVERITY_NOTIFICATION, "general position enforcement attempts set to " + std::to_string(value));
        if (value < 1) {
            throw std::invalid_argument("invalid general coords enforcement attempts -> " + std::to_string(value));
        }
        context_ptr->set_general_position_enforcement_attempts(value);
    } break;
    case MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER: {
        McConnectedComponentFaceWindingOrder value;
        memcpy(&value, pMem, bytes);
        context_ptr->dbg_cb(MC_DEBUG_SOURCE_API, MC_DEBUG_TYPE_OTHER, 0, MC_DEBUG_SEVERITY_NOTIFICATION, "winding-order set to " + std::to_string(value));
        if (value != McConnectedComponentFaceWindingOrder::MC_CONNECTED_COMPONENT_FACE_WINDING_ORDER_AS_GIVEN && //
            value != McConnectedComponentFaceWindingOrder::MC_CONNECTED_COMPONENT_FACE_WINDING_ORDER_REVERSED) {
            throw std::invalid_argument("invalid winding-order param value");
        }
        context_ptr->set_connected_component_winding_order(value);
    } break;
    default:
        throw std::invalid_argument("unknown info parameter");
        break;
    }
}
References g_contexts, MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT, MC_DEBUG_SEVERITY_NOTIFICATION, MC_DEBUG_SOURCE_API, MC_DEBUG_TYPE_OTHER, and memcpy.
Referenced by mcBindState().
create_context_impl()
void create_context_impl (McContext * pContext, McFlags flags, uint32_t num_helper_threads)
{
#if !defined(MCUT_WITH_COMPUTE_HELPER_THREADPOOL)
    UNUSED(helperThreadCount);
#endif
    MCUT_ASSERT(pOutContext != nullptr);
    std::call_once(g_objects_counter_init_flag, []() { g_objects_counter.store(0xDECAF); /*any non-ero value*/ });
    const McContext handle = reinterpret_cast<McContext>(g_objects_counter.fetch_add(1, std::memory_order_relaxed));
    g_contexts.push_front(std::shared_ptr<context_t>(
        new context_t(handle, flags
#if defined(MCUT_WITH_COMPUTE_HELPER_THREADPOOL)
            ,
            helperThreadCount
#endif
            )));
    *pOutContext = handle;
}
References g_contexts, g_objects_counter, g_objects_counter_init_flag, MCUT_ASSERT, and UNUSED.
Referenced by mcCreateContext(), and mcCreateContextWithHelpers().
create_user_event_impl()
void create_user_event_impl (McEvent * event, McContext context)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == context; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    //
    // create the event object associated with the enqueued task
    //
    std::shared_ptr<event_t> user_event_ptr = std::shared_ptr<event_t>(new event_t(
        reinterpret_cast<McEvent>(g_objects_counter.fetch_add(1, std::memory_order_relaxed)),
        McCommandType::MC_COMMAND_USER));
    MCUT_ASSERT(user_event_ptr != nullptr);
    g_events.push_front(user_event_ptr);
    // user_event_ptr->m_user_handle = reinterpret_cast<McEvent>(g_objects_counter.fetch_add(1, std::memory_order_relaxed));
    user_event_ptr->m_profiling_enabled = (context_ptr->get_flags() & MC_PROFILING_ENABLE) != 0;
    // user_event_ptr->m_command_type = McCommandType::MC_COMMAND_USER;
    user_event_ptr->m_context = context;
    user_event_ptr->m_responsible_thread_id = 0; // initialized but unused for user event
    user_event_ptr->log_submit_time();
    std::weak_ptr<event_t> user_event_weak_ptr(user_event_ptr);
    user_event_ptr->m_user_API_command_task_emulator = std::unique_ptr<std::packaged_task<void()>>(new std::packaged_task<void()>(
        // will be "called" when user updates the command status to MC_COMPLETE
        [user_event_weak_ptr]() {
            if (user_event_weak_ptr.expired()) {
                throw std::runtime_error("user event expired");
            }
            std::shared_ptr<event_t> event_ptr = user_event_weak_ptr.lock();
            if (event_ptr == nullptr) {
                throw std::runtime_error("user event null");
            }
            event_ptr->log_start_time();
        }));
    user_event_ptr->m_future = user_event_ptr->m_user_API_command_task_emulator->get_future(); // the future we can later wait on via mcWaitForEVents
    user_event_ptr->m_responsible_thread_id = MC_UNDEFINED_VALUE; // some user thread
    *eventHandle = user_event_ptr->m_user_handle;
}
References g_contexts, g_events, g_objects_counter, MC_PROFILING_ENABLE, MC_UNDEFINED_VALUE, MCUT_ASSERT, and void().
Referenced by mcCreateUserEvent().
debug_message_callback_impl()
void debug_message_callback_impl (McContext context, pfn_mcDebugOutput_CALLBACK cb, const McVoid * userParam)
{
    MCUT_ASSERT(contextHandle != nullptr);
    MCUT_ASSERT(cb != nullptr);
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
    // std::map<McContext, std::unique_ptr<context_t>>::iterator context_entry_iter = g_contexts.find(contextHandle);
    if (context_ptr == nullptr) {
        // "contextHandle" may not be NULL but that does not mean it maps to
        // a valid object in "g_contexts"
        throw std::invalid_argument("invalid context");
    }
    // const std::unique_ptr<context_t>& context_uptr = context_entry_iter->second;
    // set callback function ptr, and user pointer
    context_ptr->set_debug_callback_data(cb, userParam);
}
References g_contexts, and MCUT_ASSERT.
Referenced by mcDebugMessageCallback().
debug_message_control_impl()
void debug_message_control_impl (McContext context, McDebugSource source, McDebugType type, McDebugSeverity severity, bool enabled)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    //
    // Debug "source" flag
    //
    // for each possible "source" flag
    for (auto i : { MC_DEBUG_SOURCE_API, MC_DEBUG_SOURCE_KERNEL }) {
        if (sourceBitfieldParam & i) { // was it set/included by the user (to be enabled/disabled)?
            int n = trailing_zeroes(MC_DEBUG_SOURCE_ALL & i); // get coords of bit representing current "source" flag
            if (enabled) { // does the user want to enabled this information (from being logged in the debug callback function)
                context_ptr->dbgCallbackBitfieldSource = set_bit(context_ptr->dbgCallbackBitfieldSource, n);
            } else { // ... user wants to disable this information
                context_ptr->dbgCallbackBitfieldSource = clear_bit(context_ptr->dbgCallbackBitfieldSource, n);
            }
        }
    }
    //
    // Debug "type" flag
    //
    for (auto i : { MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR, MC_DEBUG_TYPE_ERROR, MC_DEBUG_TYPE_OTHER }) {
        if (typeBitfieldParam & i) {
            const int n = trailing_zeroes(MC_DEBUG_TYPE_ALL & i);
            if (enabled) {
                context_ptr->dbgCallbackBitfieldType = set_bit(context_ptr->dbgCallbackBitfieldType, n);
            } else {
                context_ptr->dbgCallbackBitfieldType = clear_bit(context_ptr->dbgCallbackBitfieldType, n);
            }
        }
    }
    //
    // Debug "severity" flag
    //
    for (auto i : { MC_DEBUG_SEVERITY_HIGH, MC_DEBUG_SEVERITY_LOW, MC_DEBUG_SEVERITY_MEDIUM, MC_DEBUG_SEVERITY_NOTIFICATION }) {
        if (severityBitfieldParam & i) {
            const int n = trailing_zeroes(MC_DEBUG_SEVERITY_ALL & i);
            if (enabled) {
                context_ptr->dbgCallbackBitfieldSeverity = set_bit(context_ptr->dbgCallbackBitfieldSeverity, n);
            } else {
                context_ptr->dbgCallbackBitfieldSeverity = clear_bit(context_ptr->dbgCallbackBitfieldSeverity, n);
            }
        }
    }
}
References clear_bit(), g_contexts, MC_DEBUG_SEVERITY_ALL, MC_DEBUG_SEVERITY_HIGH, MC_DEBUG_SEVERITY_LOW, MC_DEBUG_SEVERITY_MEDIUM, MC_DEBUG_SEVERITY_NOTIFICATION, MC_DEBUG_SOURCE_ALL, MC_DEBUG_SOURCE_API, MC_DEBUG_SOURCE_KERNEL, MC_DEBUG_TYPE_ALL, MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR, MC_DEBUG_TYPE_ERROR, MC_DEBUG_TYPE_OTHER, n, set_bit(), and trailing_zeroes().
Referenced by mcDebugMessageControl().
dispatch_impl()
void dispatch_impl (McContext context, McFlags flags, const McVoid * pSrcMeshVertices, const uint32_t * pSrcMeshFaceIndices, const uint32_t * pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid * pCutMeshVertices, const uint32_t * pCutMeshFaceIndices, const uint32_t * pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    std::weak_ptr<context_t> context_weak_ptr(context_ptr);
    // submit the dispatch call to be executed asynchronously and return the future
    // object that will be waited on as an event
    const McEvent event_handle = context_ptr->prepare_and_submit_API_task(
        MC_COMMAND_DISPATCH, numEventsInWaitlist, pEventWaitList,
        [=]() {
            if (!context_weak_ptr.expired()) {
                std::shared_ptr<context_t> context = context_weak_ptr.lock();
                if (context) {
                    preproc(
                        context,
                        dispatchFlags,
                        pSrcMeshVertices,
                        pSrcMeshFaceIndices,
                        pSrcMeshFaceSizes,
                        numSrcMeshVertices,
                        numSrcMeshFaces,
                        pCutMeshVertices,
                        pCutMeshFaceIndices,
                        pCutMeshFaceSizes,
                        numCutMeshVertices,
                        numCutMeshFaces);
                }
            }
        });
    MCUT_ASSERT(pEvent != nullptr);
    *pEvent = event_handle;
}
References g_contexts, and MC_COMMAND_DISPATCH.
Referenced by mcEnqueueDispatch().
dispatch_planar_section_impl()
void dispatch_planar_section_impl (McContext context, McFlags flags, const McVoid * pSrcMeshVertices, const uint32_t * pSrcMeshFaceIndices, const uint32_t * pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McDouble * pNormalVector, const McDouble sectionOffset, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == context; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    std::weak_ptr<context_t> context_weak_ptr(context_ptr);
    // submit the dispatch call to be executed asynchronously and return the future
    // object that will be waited on as an event
    const McEvent event_handle = context_ptr->prepare_and_submit_API_task(
        MC_COMMAND_DISPATCH, numEventsInWaitlist, pEventWaitList,
        [=]() {
            if (!context_weak_ptr.expired()) {
                std::shared_ptr<context_t> context = context_weak_ptr.lock();
                if (context) {
                    std::vector<McChar> supertriangle_vertices;
                    std::vector<McIndex> supertriangle_indices;
                    generate_supertriangle_from_mesh_vertices(
                        supertriangle_vertices,
                        supertriangle_indices,
                        flags,
                        pSrcMeshVertices,
                        numSrcMeshVertices,
                        pNormalVector,
                        sectionOffset,
                        context->get_general_position_enforcement_constant());
                    preproc(
                        context,
                        flags,
                        pSrcMeshVertices,
                        pSrcMeshFaceIndices,
                        pSrcMeshFaceSizes,
                        numSrcMeshVertices,
                        numSrcMeshFaces,
                        (McVoid*)supertriangle_vertices.data(),
                        (McIndex*)&supertriangle_indices[0],
                        nullptr,
                        3,
                        1);
                }
            }
        });
    MCUT_ASSERT(pEvent != nullptr);
    *pEvent = event_handle;
}
References g_contexts, and MC_COMMAND_DISPATCH.
Referenced by mcEnqueueDispatchPlanarSection().
fn_delete_cc()
template<typename Derived > void fn_delete_cc (connected_component_t * p)
{
    log_msg("[MCUT] Destroy connected component " << p->m_user_handle);
    delete dynamic_cast<Derived*>(p);
}
References log_msg, and connected_component_t::m_user_handle.
get_connected_component_data_impl()
void get_connected_component_data_impl (const McContext context, const McConnectedComponent connCompId, McFlags flags, McSize bytes, McVoid * pMem, McSize * pNumBytes, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    std::weak_ptr<context_t> context_weak_ptr(context_ptr);
    const McEvent event_handle = context_ptr->prepare_and_submit_API_task(
        MC_COMMAND_GET_CONNECTED_COMPONENT_DATA, numEventsInWaitlist, pEventWaitList,
        [=]() {
            if (!context_weak_ptr.expired()) {
                std::shared_ptr<context_t> context = context_weak_ptr.lock();
                if (context) {
                    // asynchronously get the data and write to user provided pointer
                    get_connected_component_data_impl_detail(
                        context,
                        connCompId,
                        flags,
                        bytes,
                        pMem,
                        pNumBytes);
                }
            }
        });
    *pEvent = event_handle;
}
References g_contexts, and MC_COMMAND_GET_CONNECTED_COMPONENT_DATA.
Referenced by mcEnqueueGetConnectedComponentData().
get_connected_components_impl()
void get_connected_components_impl (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent * pConnComps, uint32_t * numConnComps, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    std::weak_ptr<context_t> context_weak_ptr(context_ptr);
    const McEvent event_handle = context_ptr->prepare_and_submit_API_task(
        MC_COMMAND_GET_CONNECTED_COMPONENTS, numEventsInWaitlist, pEventWaitList,
        [=]() {
            if (!context_weak_ptr.expired()) {
                std::shared_ptr<context_t> context = context_weak_ptr.lock();
                if (context) {
                    if (numConnComps != nullptr) {
                        (*numConnComps) = 0; // reset
                    }
                    uint32_t valid_cc_counter = 0;
                    context->connected_components.for_each([&](const std::shared_ptr<connected_component_t> cc_ptr) {
                        const bool is_valid = (cc_ptr->type & connectedComponentType) != 0;
                        if (is_valid) {
                            if (pConnComps == nullptr) // query number
{
                                (*numConnComps)++;
                            } else // populate pConnComps
{
                                if (valid_cc_counter == numEntries) {
                                    return;
                                }
                                pConnComps[valid_cc_counter] = cc_ptr->m_user_handle;
                                valid_cc_counter += 1;
                            }
                        }
                    });
                }
            }
        });
    *pEvent = event_handle;
}
References g_contexts, and MC_COMMAND_GET_CONNECTED_COMPONENTS.
Referenced by mcEnqueueGetConnectedComponents().
get_debug_message_log_impl()
void get_debug_message_log_impl (McContext context, McUint32 count, McSize bufSize, McDebugSource * sources, McDebugType * types, McDebugSeverity * severities, McSize * lengths, McChar * messageLog, McUint32 & numFetched)
{
    MCUT_ASSERT(context != nullptr);
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == context; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    numFetched = 0;
    if (messageLog == nullptr) {
        context_ptr->dbg_cb(MC_DEBUG_SOURCE_API, MC_DEBUG_TYPE_OTHER, 0, MC_DEBUG_SEVERITY_NOTIFICATION, "output messageLog is NULL. Return.");
        return;
    }
    McSize messageLogOffset = 0;
    const uint32_t N = std::min((uint32_t)count, (uint32_t)context_ptr->m_debug_logs.size());
    // for internal message
    for (numFetched = 0; numFetched < N; ++numFetched) {
        const context_t::debug_log_msg_t& cur_dbg_msg = context_ptr->m_debug_logs[numFetched];
        const McSize msg_length = (McSize)cur_dbg_msg.str.size();
        const McSize newLengthOfActualMessageLog = (messageLogOffset + msg_length);
        if (newLengthOfActualMessageLog > bufSize) {
            break; // stop
        }
        if (sources != nullptr) {
            sources[numFetched] = cur_dbg_msg.source;
        }
        if (types != nullptr) {
            types[numFetched] = cur_dbg_msg.type;
        }
        if (severities != nullptr) {
            severities[numFetched] = cur_dbg_msg.severity;
        }
        if (lengths != nullptr) {
            lengths[numFetched] = msg_length;
        }
        // copy into output array
        memcpy(messageLog + messageLogOffset, cur_dbg_msg.str.data(), msg_length);
        messageLogOffset = newLengthOfActualMessageLog;
    }
}
References count, g_contexts, MC_DEBUG_SEVERITY_NOTIFICATION, MC_DEBUG_SOURCE_API, MC_DEBUG_TYPE_OTHER, MCUT_ASSERT, memcpy, context_t::debug_log_msg_t::severity, context_t::debug_log_msg_t::source, context_t::debug_log_msg_t::str, and context_t::debug_log_msg_t::type.
Referenced by mcGetDebugMessageLog().
get_event_info_impl()
void get_event_info_impl (const McEvent event, McFlags info, McSize bytes, McVoid * pMem, McSize * pNumBytes)
{
    std::shared_ptr<event_t> event_ptr = g_events.find_first_if([=](const std::shared_ptr<event_t> ptr) { return ptr->m_user_handle == event; });
    if (event_ptr == nullptr) {
        throw std::invalid_argument("invalid event");
    }
    switch (info) {
    case MC_EVENT_RUNTIME_EXECUTION_STATUS: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McResult);
        } else {
            if (bytes < sizeof(McResult)) {
                throw std::invalid_argument("invalid bytes");
            }
            McResult status = (McResult)event_ptr->m_runtime_exec_status.load();
            memcpy(pMem, reinterpret_cast<McVoid*>(&status), bytes);
        }
        break;
    }
    case MC_EVENT_TIMESTAMP_SUBMIT:
    case MC_EVENT_TIMESTAMP_START:
    case MC_EVENT_TIMESTAMP_END: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McSize);
        } else {
            if (bytes < sizeof(McSize)) {
                throw std::invalid_argument("invalid bytes");
            }
            McSize nanoseconds_since_epoch = 0;
            if (info == MC_EVENT_TIMESTAMP_SUBMIT) {
                nanoseconds_since_epoch = event_ptr->m_timestamp_submit.load();
            } else if (info == MC_EVENT_TIMESTAMP_START) {
                nanoseconds_since_epoch = event_ptr->m_timestamp_start.load();
            } else if (info == MC_EVENT_TIMESTAMP_END) {
                nanoseconds_since_epoch = event_ptr->m_timestamp_end.load();
            }
            MCUT_ASSERT(nanoseconds_since_epoch != 0);
            memcpy(pMem, reinterpret_cast<McVoid*>(&nanoseconds_since_epoch), bytes);
        }
        break;
    }
    case MC_EVENT_COMMAND_EXECUTION_STATUS: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McEventCommandExecStatus);
        } else {
            if (bytes < sizeof(McEventCommandExecStatus)) {
                throw std::invalid_argument("invalid bytes");
            }
            McEventCommandExecStatus status = (McEventCommandExecStatus)event_ptr->m_command_exec_status.load();
            memcpy(pMem, reinterpret_cast<McVoid*>(&status), bytes);
        }
    } break;
    case MC_EVENT_COMMAND_TYPE: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McCommandType);
        } else {
            if (bytes < sizeof(McCommandType)) {
                throw std::invalid_argument("invalid bytes");
            }
            McCommandType cmdType = (McCommandType)event_ptr->m_command_type;
            memcpy(pMem, reinterpret_cast<McVoid*>(&cmdType), bytes);
        }
    } break;
    case MC_EVENT_CONTEXT: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McContext);
        } else {
            if (bytes < sizeof(McContext)) {
                throw std::invalid_argument("invalid bytes");
            }
            McContext ctxt = (McContext)event_ptr->m_context;
            memcpy(pMem, reinterpret_cast<McVoid*>(&ctxt), bytes);
        }
    } break;
    default:
        throw std::invalid_argument("unknown info parameter");
        break;
    }
}
References g_events, MC_EVENT_COMMAND_EXECUTION_STATUS, MC_EVENT_COMMAND_TYPE, MC_EVENT_CONTEXT, MC_EVENT_RUNTIME_EXECUTION_STATUS, MC_EVENT_TIMESTAMP_END, MC_EVENT_TIMESTAMP_START, MC_EVENT_TIMESTAMP_SUBMIT, MCUT_ASSERT, memcpy, and ptr.
Referenced by mcGetEventInfo().
get_info_impl()
void get_info_impl (const McContext context, McFlags info, McSize bytes, McVoid * pMem, McSize * pNumBytes)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    switch (info) {
    case MC_CONTEXT_FLAGS: {
        McFlags flags = context_ptr->get_flags();
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McFlags);
        } else {
            if (bytes < sizeof(McFlags)) {
                throw std::invalid_argument("invalid bytes");
            }
            memcpy(pMem, reinterpret_cast<McVoid*>(&flags), bytes);
        }
        break;
    }
    case MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McSize);
        } else {
            std::lock_guard<std::mutex> lock(context_ptr->debugCallbackMutex);
            McSize sizeMax = 0;
            for (McUint32 i = 0; i < (McUint32)context_ptr->m_debug_logs.size(); ++i) {
                sizeMax = std::max((McSize)sizeMax, (McSize)context_ptr->m_debug_logs[i].str.size());
            }
            memcpy(pMem, reinterpret_cast<McVoid*>(&sizeMax), sizeof(McSize));
        }
    } break;
    case MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McDouble);
        } else {
            const McDouble gpec = context_ptr->get_general_position_enforcement_constant();
            memcpy(pMem, reinterpret_cast<const McDouble*>(&gpec), sizeof(McDouble));
        }
    } break;
    case MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McUint32);
        } else {
            const McUint32 attempts = context_ptr->get_general_position_enforcement_attempts();
            memcpy(pMem, reinterpret_cast<const McDouble*>(&attempts), sizeof(McUint32));
        }
    } break;
    case MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER: {
        if (pMem == nullptr) {
            *pNumBytes = sizeof(McConnectedComponentFaceWindingOrder);
        } else {
            const McConnectedComponentFaceWindingOrder wo = context_ptr->get_connected_component_winding_order();
            memcpy(pMem, reinterpret_cast<const McConnectedComponentFaceWindingOrder*>(&wo), sizeof(McConnectedComponentFaceWindingOrder));
        }
    } break;
    default:
        throw std::invalid_argument("unknown info parameter");
        break;
    }
}
References g_contexts, MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER, MC_CONTEXT_FLAGS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT, MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH, and memcpy.
Referenced by mcGetInfo().
release_connected_components_impl()
void release_connected_components_impl (const McContext context, uint32_t numConnComps, const McConnectedComponent * pConnComps)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context");
    }
    bool freeAll = numConnComps == 0 && pConnComps == NULL;
    if (freeAll) {
        context_ptr->connected_components.remove_if([](const std::shared_ptr<connected_component_t>) { return true; });
    } else {
        for (int i = 0; i < (int)numConnComps; ++i) {
            McConnectedComponent connCompId = pConnComps[i];
            // report error if cc is not valid
            std::shared_ptr<connected_component_t> cc_ptr = context_ptr->connected_components.find_first_if([=](const std::shared_ptr<connected_component_t> ccptr) { return ccptr->m_user_handle == connCompId; });
            if (cc_ptr == nullptr) {
                throw std::invalid_argument("invalid connected component handle");
            }
            context_ptr->connected_components.remove_if([=](const std::shared_ptr<connected_component_t> ccptr) { return ccptr->m_user_handle == connCompId; });
        }
    }
}
References g_contexts, int, and NULL.
Referenced by mcReleaseConnectedComponents().
release_context_impl()
void release_context_impl (McContext context)
{
    std::shared_ptr<context_t> context_ptr = g_contexts.find_first_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
    if (context_ptr == nullptr) {
        throw std::invalid_argument("invalid context handle");
    }
    g_contexts.remove_if([=](const std::shared_ptr<context_t> cptr) { return cptr->m_user_handle == contextHandle; });
}
References g_contexts.
Referenced by mcReleaseContext().
release_events_impl()
void release_events_impl (uint32_t numEvents, const McEvent * pEvents)
{
    for (uint32_t i = 0; i < numEvents; ++i) {
        McEvent eventHandle = pEvents[i];
        release_event_impl(eventHandle);
    }
}
References release_event_impl().
Referenced by mcDispatch(), mcGetConnectedComponentData(), mcGetConnectedComponents(), and mcReleaseEvents().
set_event_callback_impl()
void set_event_callback_impl (McEvent eventHandle, pfn_McEvent_CALLBACK eventCallback, McVoid * data)
{
    std::shared_ptr<event_t> event_ptr = g_events.find_first_if([=](const std::shared_ptr<event_t> eptr) { return eptr->m_user_handle == eventHandle; });
    if (event_ptr == nullptr) {
        // "contextHandle" may not be NULL but that does not mean it maps to
        // a valid object in "g_contexts"
        throw std::invalid_argument("unknown event object");
    }
    event_ptr->set_callback_data(eventHandle, eventCallback, data);
}
References g_events.
Referenced by mcSetEventCallback().
set_user_event_status_impl()
void set_user_event_status_impl (McEvent event, McInt32 execution_status)
execution_status specifies the new execution status to be set and can be CL_COMPLETE or a negative integer value to indicate an error. A negative integer value causes all enqueued commands that wait on this user event to be terminated.
{
    std::shared_ptr<event_t> event_ptr = g_events.find_first_if([=](const std::shared_ptr<event_t> ptr) { return ptr->m_user_handle == event; });
    if (event_ptr == nullptr) {
        throw std::invalid_argument("invalid event");
    }
    McResult userEventErrorCode = McResult::MC_NO_ERROR;
    std::unique_ptr<std::packaged_task<void()>>& associated_task_emulator = event_ptr->m_user_API_command_task_emulator;
    MCUT_ASSERT(associated_task_emulator != nullptr);
    // simply logs the start time and makes the std::packaged_task future object ready
    associated_task_emulator->operator()(); // call the internal "task" function to update event status
    switch (execution_status) {
    case McEventCommandExecStatus::MC_COMPLETE: {
        event_ptr->log_end_time();
    } break;
    default: {
        MCUT_ASSERT(execution_status < 0); // an error
        switch (execution_status) {
        case McResult::MC_INVALID_OPERATION:
        case McResult::MC_INVALID_VALUE:
        case McResult::MC_OUT_OF_MEMORY: {
            userEventErrorCode = (McResult)execution_status;
        } break;
        default: {
            throw std::invalid_argument("invalid command status");
        }
        }
    }
    }
    // invoke call back
    event_ptr->notify_task_complete(userEventErrorCode); // updated event state to indicate task completion (lock-based)
}
References g_events, MCUT_ASSERT, ptr, and void().
Referenced by mcSetUserEventStatus().
wait_for_events_impl()
void wait_for_events_impl (uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McResult & runtimeStatusFromAllPrecedingEvents)
{
    for (uint32_t i = 0; i < numEventsInWaitlist; ++i) {
        McEvent eventHandle = pEventWaitList[i];
        std::shared_ptr<event_t> event_ptr = g_events.find_first_if([=](const std::shared_ptr<event_t> eptr) { return eptr->m_user_handle == eventHandle; });
        if (event_ptr == nullptr) {
            // "contextHandle" may not be NULL but that does not mean it maps to
            // a valid object in "g_contexts"
            throw std::invalid_argument("null event object");
        } else {
            if (event_ptr->m_future.valid()) {
                event_ptr->m_future.wait(); // block until event task is finished
                runtimeStatusFromAllPrecedingEvents = (McResult)event_ptr->m_runtime_exec_status.load();
                if (runtimeStatusFromAllPrecedingEvents != McResult::MC_NO_ERROR) {
                    // indicate that a task waiting on any one of the event in pEventWaitList
                    // must not proceed because a runtime error occurred
                    break;
                }
            }
        }
    }
}
References g_events.
Referenced by mcDispatch(), mcGetConnectedComponentData(), mcGetConnectedComponents(), and mcWaitForEvents().
Variable Documentation
g_contexts
threadsafe_list<std::shared_ptr<context_t> > g_contexts
g_events
threadsafe_list<std::shared_ptr<event_t> > g_events extern
Referenced by create_user_event_impl(), get_event_info_impl(), context_t::prepare_and_submit_API_task(), release_event_impl(), set_event_callback_impl(), set_user_event_status_impl(), and wait_for_events_impl().
g_objects_counter
std::atomic<std::uintptr_t> g_objects_counter extern
Referenced by create_context_impl(), create_user_event_impl(), context_t::prepare_and_submit_API_task(), and preproc().
g_objects_counter_init_flag
std::once_flag g_objects_counter_init_flag extern
Referenced by create_context_impl().
per_thread_api_log_str
thread_local std::string per_thread_api_log_str extern
Referenced by mcBindState(), mcCreateContext(), mcCreateContextWithHelpers(), mcCreateUserEvent(), mcDebugMessageCallback(), mcDebugMessageControl(), mcEnqueueDispatch(), mcEnqueueDispatchPlanarSection(), mcEnqueueGetConnectedComponentData(), mcEnqueueGetConnectedComponents(), mcGetDebugMessageLog(), mcGetEventInfo(), mcGetInfo(), mcReleaseConnectedComponents(), mcReleaseContext(), mcReleaseEvents(), mcSetEventCallback(), mcSetUserEventStatus(), mcWaitForEvents(), and context_t::prepare_and_submit_API_task().