OrcaSlicer: orgQhull::MutableCoordinatesIterator Class Reference
orgQhull::MutableCoordinatesIterator Class Reference
#include <src/qhull/src/libqhullcpp/Coordinates.h>
Public Member Functions
MutableCoordinatesIterator (Coordinates &container)
MutableCoordinatesIterator & operator= (Coordinates &container)
~MutableCoordinatesIterator ()
bool findNext (const coordT &t)
bool findPrevious (const coordT &t)
bool hasNext () const
bool hasPrevious () const
void insert (const coordT &t)
coordT & next ()
coordT & peekNext () const
coordT & peekPrevious () const
coordT & previous ()
void remove ()
void setValue (const coordT &t) const
void toFront ()
void toBack ()
coordT & value ()
const coordT & value () const
Private Types
typedef Coordinates::iterator iterator
typedef Coordinates::const_iterator const_iterator
Private Member Functions
bool item_exists () const
Private Attributes
Coordinates * c
iterator i
iterator n
Detailed Description
Member Typedef Documentation
const_iterator
typedef Coordinates::const_iterator orgQhull::MutableCoordinatesIterator::const_iterator private
iterator
typedef Coordinates::iterator orgQhull::MutableCoordinatesIterator::iterator private
Constructor & Destructor Documentation
MutableCoordinatesIterator()
orgQhull::MutableCoordinatesIterator::MutableCoordinatesIterator (Coordinates & container) inline
: c(&container) { i= c->begin(); n= c->end(); }
References orgQhull::Coordinates::begin(), c, orgQhull::Coordinates::end(), i, and n.
~MutableCoordinatesIterator()
orgQhull::MutableCoordinatesIterator::~MutableCoordinatesIterator () inline
{}
Member Function Documentation
findNext()
bool orgQhull::MutableCoordinatesIterator::findNext (const coordT & t) inline
{ while(c->constEnd()!=const_iterator(n= i)){ if(*i++==t){ return true;}} return false; }
References c, orgQhull::Coordinates::constEnd(), i, and n.
Referenced by orgQhull::Coordinates::removeAll(), and orgQhull::Coordinates_test::t_mutable_coord_iterator().
findPrevious()
bool orgQhull::MutableCoordinatesIterator::findPrevious (const coordT & t) inline
{ while(c->constBegin()!=const_iterator(i)){ if(*(n= --i)== t){ return true;}} n= c->end(); return false;  }
References c, orgQhull::Coordinates::constBegin(), orgQhull::Coordinates::end(), i, and n.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
hasNext()
bool orgQhull::MutableCoordinatesIterator::hasNext () const inline
{ return (c->constEnd()!=const_iterator(i)); }
References c, orgQhull::Coordinates::constEnd(), and i.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
hasPrevious()
bool orgQhull::MutableCoordinatesIterator::hasPrevious () const inline
{ return (c->constBegin()!=const_iterator(i)); }
References c, orgQhull::Coordinates::constBegin(), and i.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
insert()
void orgQhull::MutableCoordinatesIterator::insert (const coordT & t) inline
{ n= i= c->insert(i, t); ++i; }
References c, i, orgQhull::Coordinates::insert(), and n.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
item_exists()
bool orgQhull::MutableCoordinatesIterator::item_exists () const inline private
{ return const_iterator(n) != c->constEnd(); }
References c, orgQhull::Coordinates::constEnd(), and n.
Referenced by value(), and value().
next()
coordT & orgQhull::MutableCoordinatesIterator::next () inline
{ n= i++; return *n; }
References i, and n.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
operator=()
MutableCoordinatesIterator & orgQhull::MutableCoordinatesIterator::operator= (Coordinates & container) inline
{ c= &container; i= c->begin(); n= c->end(); return *this; }
References orgQhull::Coordinates::begin(), c, orgQhull::Coordinates::end(), i, and n.
peekNext()
coordT & orgQhull::MutableCoordinatesIterator::peekNext () const inline
{ return *i; }
References i.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
peekPrevious()
coordT & orgQhull::MutableCoordinatesIterator::peekPrevious () const inline
{ iterator p= i; return *--p; }
References i.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
previous()
coordT & orgQhull::MutableCoordinatesIterator::previous () inline
{ n= --i; return *n; }
References i, and n.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
remove()
void orgQhull::MutableCoordinatesIterator::remove () inline
{ if(c->constEnd()!=const_iterator(n)){ i= c->erase(n); n= c->end();} }
References c, orgQhull::Coordinates::constEnd(), orgQhull::Coordinates::end(), orgQhull::Coordinates::erase(), i, and n.
Referenced by orgQhull::Coordinates::removeAll(), and orgQhull::Coordinates_test::t_mutable_coord_iterator().
setValue()
void orgQhull::MutableCoordinatesIterator::setValue (const coordT & t) const inline
{ if(c->constEnd()!=const_iterator(n)){ *n= t;} }
References c, orgQhull::Coordinates::constEnd(), and n.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
toBack()
void orgQhull::MutableCoordinatesIterator::toBack () inline
{ i= c->end(); n= i; }
References c, orgQhull::Coordinates::end(), i, and n.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
toFront()
void orgQhull::MutableCoordinatesIterator::toFront () inline
{ i= c->begin(); n= c->end(); }
References orgQhull::Coordinates::begin(), c, orgQhull::Coordinates::end(), i, and n.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
value() [1/2]
coordT & orgQhull::MutableCoordinatesIterator::value () inline
{ QHULL_ASSERT(item_exists()); return *n; }
References item_exists(), n, and QHULL_ASSERT.
Referenced by orgQhull::Coordinates_test::t_mutable_coord_iterator().
value() [2/2]
const coordT & orgQhull::MutableCoordinatesIterator::value () const inline
{ QHULL_ASSERT(item_exists()); return *n; }
References item_exists(), n, and QHULL_ASSERT.
Member Data Documentation
c
Coordinates* orgQhull::MutableCoordinatesIterator::c private
Referenced by MutableCoordinatesIterator(), findNext(), findPrevious(), hasNext(), hasPrevious(), insert(), item_exists(), operator=(), remove(), setValue(), toBack(), and toFront().
i
iterator orgQhull::MutableCoordinatesIterator::i private
Referenced by MutableCoordinatesIterator(), findNext(), findPrevious(), hasNext(), hasPrevious(), insert(), next(), operator=(), peekNext(), peekPrevious(), previous(), remove(), toBack(), and toFront().
n
iterator orgQhull::MutableCoordinatesIterator::n private
Referenced by MutableCoordinatesIterator(), findNext(), findPrevious(), insert(), item_exists(), next(), operator=(), previous(), remove(), setValue(), toBack(), toFront(), value(), and value().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/Coordinates.h