OrcaSlicer: Slic3r::GUI::FanControl Class Reference
Slic3r::GUI::FanControl Class Reference
#include <src/slic3r/GUI/Widgets/FanControl.hpp>
Public Member Functions
FanControl (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~FanControl ()
void update_obj_state (bool stat)
void command_control_fan ()
void set_machine_obj (MachineObject *obj)
void set_type (MachineObject::FanType type)
void set_name (wxString name)
void set_fan_speed (int g)
void set_fan_switch (bool s)
void post_event (wxCommandEvent &&event)
void on_swith_fan (wxMouseEvent &evt)
void on_swith_fan (bool on)
void on_left_down (wxMouseEvent &event)
Public Attributes
wxStaticBitmap * m_switch_button { nullptr }
Protected Attributes
MachineObject::FanType m_type
MachineObject * m_obj
wxStaticText * m_static_name { nullptr }
ScalableBitmap * m_bitmap_toggle_off { nullptr }
ScalableBitmap * m_bitmap_toggle_on { nullptr }
Fan * m_fan { nullptr }
FanOperate * m_fan_operate { nullptr }
bool m_switch_fan { false }
bool m_update_already {false}
int m_current_speed {0}
Detailed Description
Constructor & Destructor Documentation
FanControl()
Slic3r::GUI::FanControl::FanControl (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
    :wxWindow(parent, id, pos, size)
{
    auto m_bitmap_fan = new ScalableBitmap(this, "fan_icon", 18);
    m_bitmap_toggle_off = new ScalableBitmap(this, "toggle_off", 14);
    m_bitmap_toggle_on = new ScalableBitmap(this, "toggle_on", 14);
    SetBackgroundColour(*wxWHITE);
    wxBoxSizer* m_sizer_main = new wxBoxSizer(wxHORIZONTAL);
    m_fan = new Fan(this, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    m_sizer_main->Add(m_fan, 1, wxEXPAND | wxALL, 0);
    m_sizer_main->Add(0, 0, 0, wxLEFT, FromDIP(18));
    wxBoxSizer* sizer_control = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_control_top = new wxBoxSizer(wxHORIZONTAL);
    auto m_static_bitmap_fan = new wxStaticBitmap(this, wxID_ANY, m_bitmap_fan->bmp(), wxDefaultPosition, wxDefaultSize);
    m_static_name = new wxStaticText(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END|wxALIGN_CENTER_HORIZONTAL);
    m_static_name->SetForegroundColour(wxColour(DRAW_TEXT_COLOUR));
    m_static_name->SetBackgroundColour(*wxWHITE);
    m_static_name->SetMinSize(wxSize(FromDIP(50), -1));
    m_static_name->SetMaxSize(wxSize(FromDIP(50), -1));
    m_switch_button = new wxStaticBitmap(this, wxID_ANY, m_bitmap_toggle_off->bmp(), wxDefaultPosition, wxDefaultSize, 0);
    m_switch_button->Bind(wxEVT_ENTER_WINDOW, [this](auto& e) { SetCursor(wxCURSOR_HAND); });
    m_switch_button->Bind(wxEVT_LEAVE_WINDOW, [this](auto& e) { SetCursor(wxCURSOR_RIGHT_ARROW); });
    m_switch_button->Bind(wxEVT_LEFT_DOWN, &FanControl::on_swith_fan, this);
    sizer_control_top->Add(m_static_bitmap_fan, 0, wxALIGN_CENTER, 5);
    sizer_control_top->Add(m_static_name, 0, wxALIGN_CENTER, 0);
    sizer_control_top->Add( 0, 0, 1, wxEXPAND, 0 );
    sizer_control_top->Add(m_switch_button, 0, wxALIGN_CENTER, 0);
    sizer_control->Add(sizer_control_top, 0, wxALIGN_CENTER, 0);
    sizer_control->Add(0, 0, 0, wxTOP, FromDIP(15));
    m_fan_operate = new FanOperate(this, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    sizer_control->Add(m_fan_operate, 0, wxALIGN_CENTER, 0);
    m_sizer_main->Add(sizer_control, 0, wxALIGN_CENTER, 0);
    this->SetSizer(m_sizer_main);
    this->Layout();
    m_sizer_main->Fit(this);
    m_fan_operate->Bind(EVT_FAN_SWITCH_ON, [this](wxCommandEvent& e) {
        m_current_speed = e.GetInt();
        m_switch_button->SetBitmap(m_bitmap_toggle_on->bmp());
        m_switch_fan = true;
        m_fan->set_fan_speeds(m_current_speed);
    });
    m_fan_operate->Bind(EVT_FAN_SWITCH_OFF, [this](wxCommandEvent& e) {
        m_current_speed = e.GetInt();
        m_switch_button->SetBitmap(m_bitmap_toggle_off->bmp());
        m_switch_fan = false;
        m_fan->set_fan_speeds(m_current_speed);
    });
    m_fan_operate->Bind(EVT_FAN_ADD, [this](wxCommandEvent& e) {
        m_current_speed = e.GetInt();
        m_fan->set_fan_speeds(m_current_speed);
        command_control_fan();
    });
    m_fan_operate->Bind(EVT_FAN_DEC, [this](wxCommandEvent& e) {
        m_current_speed = e.GetInt();
        m_fan->set_fan_speeds(m_current_speed);
        command_control_fan();
    });
}
References ScalableBitmap::bmp(), command_control_fan(), DRAW_TEXT_COLOUR, m_bitmap_toggle_off, m_bitmap_toggle_on, m_current_speed, m_fan, m_fan_operate, m_static_name, m_switch_button, m_switch_fan, on_swith_fan(), Slic3r::GUI::Fan::set_fan_speeds(), and wxStaticText.
~FanControl()
Slic3r::GUI::FanControl::~FanControl () inline
{};
Member Function Documentation
command_control_fan()
void Slic3r::GUI::FanControl::command_control_fan ()
{
    if (m_current_speed < 0 || m_current_speed > 10) { return; }
    int speed = floor(m_current_speed * float(25.5));
    if (m_update_already && m_obj) {
        m_obj->command_control_fan_val(m_type, speed);
        post_event(wxCommandEvent(EVT_FAN_CHANGED));
    }
}
References Slic3r::MachineObject::command_control_fan_val(), floor(), m_current_speed, m_obj, m_type, m_update_already, and post_event().
Referenced by FanControl(), and on_swith_fan().
on_left_down()
void Slic3r::GUI::FanControl::on_left_down (wxMouseEvent & event)
{
    auto mouse_pos = ClientToScreen(evt.GetPosition());
    auto tag_pos = m_fan_operate->ScreenToClient(mouse_pos);
    evt.SetPosition(tag_pos);
    m_fan_operate->on_left_down(evt);
}
References m_fan_operate, and Slic3r::GUI::FanOperate::on_left_down().
Referenced by Slic3r::GUI::FanControlPopup::on_left_down().
on_swith_fan() [1/2]
void Slic3r::GUI::FanControl::on_swith_fan (bool on)
{
    m_switch_fan = on;
    if (m_switch_fan) {
        m_switch_button->SetBitmap(m_bitmap_toggle_on->bmp());
    }
    else {
        m_switch_button->SetBitmap(m_bitmap_toggle_off->bmp());
    }
}
References ScalableBitmap::bmp(), m_bitmap_toggle_off, m_bitmap_toggle_on, m_switch_button, and m_switch_fan.
on_swith_fan() [2/2]
void Slic3r::GUI::FanControl::on_swith_fan (wxMouseEvent & evt)
{
    int speed = 0;
    if (m_switch_fan) {
        m_switch_button->SetBitmap(m_bitmap_toggle_off->bmp());
        m_switch_fan = false;
    }
    else {
        speed = 255;
        m_switch_button->SetBitmap(m_bitmap_toggle_on->bmp());
        m_switch_fan = true;
    }
    set_fan_speed(speed);
    command_control_fan();
}
References ScalableBitmap::bmp(), command_control_fan(), m_bitmap_toggle_off, m_bitmap_toggle_on, m_switch_button, m_switch_fan, and set_fan_speed().
Referenced by FanControl(), Slic3r::GUI::FanControlPopup::on_left_down(), and set_fan_speed().
post_event()
void Slic3r::GUI::FanControl::post_event (wxCommandEvent && event)
{
    event.SetInt(m_type);
    event.SetString(wxString::Format("%d", m_current_speed));
    event.SetEventObject(GetParent());
    wxPostEvent(GetParent(), event);
    event.Skip();
}
References m_current_speed, and m_type.
Referenced by command_control_fan().
set_fan_speed()
void Slic3r::GUI::FanControl::set_fan_speed (int g)
{
    if (g < 0 || g > 255) return;
    int speed = round(float(g) / float(25.5));
    if (m_current_speed != speed) {
        m_current_speed = speed;
        m_fan->set_fan_speeds(speed);
        m_fan_operate->set_fan_speeds(m_current_speed);
        if (m_current_speed <= 0) {
            on_swith_fan(false);
        }
        else {
            on_swith_fan(true);
        }
    }
}
References m_current_speed, m_fan, m_fan_operate, on_swith_fan(), round(), Slic3r::GUI::Fan::set_fan_speeds(), and Slic3r::GUI::FanOperate::set_fan_speeds().
Referenced by on_swith_fan(), and Slic3r::GUI::FanControlPopup::update_fan_data().
set_fan_switch()
void Slic3r::GUI::FanControl::set_fan_switch (bool s)
{
}
set_machine_obj()
void Slic3r::GUI::FanControl::set_machine_obj (MachineObject * obj)
{
    m_update_already = true;
    m_obj = obj;
}
References m_obj, and m_update_already.
Referenced by Slic3r::GUI::FanControlPopup::update_fan_data().
set_name()
void Slic3r::GUI::FanControl::set_name (wxString name)
{
    m_static_name->SetLabelText(name);
}
References m_static_name.
Referenced by Slic3r::GUI::FanControlPopup::FanControlPopup().
set_type()
void Slic3r::GUI::FanControl::set_type (MachineObject::FanType type)
{
    m_type = type;
}
References m_type.
Referenced by Slic3r::GUI::FanControlPopup::FanControlPopup().
update_obj_state()
void Slic3r::GUI::FanControl::update_obj_state (bool stat) inline
{m_update_already = stat;};
References m_update_already.
Referenced by Slic3r::GUI::FanControlPopup::OnDismiss().
Member Data Documentation
m_bitmap_toggle_off
ScalableBitmap* Slic3r::GUI::FanControl::m_bitmap_toggle_off { nullptr } protected
Referenced by FanControl(), on_swith_fan(), and on_swith_fan().
m_bitmap_toggle_on
ScalableBitmap* Slic3r::GUI::FanControl::m_bitmap_toggle_on { nullptr } protected
Referenced by FanControl(), on_swith_fan(), and on_swith_fan().
m_current_speed
int Slic3r::GUI::FanControl::m_current_speed {0} protected
Referenced by FanControl(), command_control_fan(), post_event(), and set_fan_speed().
m_fan
Fan* Slic3r::GUI::FanControl::m_fan { nullptr } protected
Referenced by FanControl(), and set_fan_speed().
m_fan_operate
FanOperate* Slic3r::GUI::FanControl::m_fan_operate { nullptr } protected
Referenced by FanControl(), on_left_down(), and set_fan_speed().
m_obj
MachineObject* Slic3r::GUI::FanControl::m_obj protected
Referenced by command_control_fan(), and set_machine_obj().
m_static_name
wxStaticText* Slic3r::GUI::FanControl::m_static_name { nullptr } protected
Referenced by FanControl(), and set_name().
m_switch_button
wxStaticBitmap* Slic3r::GUI::FanControl::m_switch_button { nullptr }
Referenced by FanControl(), Slic3r::GUI::FanControlPopup::on_left_down(), on_swith_fan(), and on_swith_fan().
m_switch_fan
bool Slic3r::GUI::FanControl::m_switch_fan { false } protected
Referenced by FanControl(), on_swith_fan(), and on_swith_fan().
m_type
MachineObject::FanType Slic3r::GUI::FanControl::m_type protected
Referenced by command_control_fan(), post_event(), and set_type().
m_update_already
bool Slic3r::GUI::FanControl::m_update_already {false} protected
Referenced by command_control_fan(), set_machine_obj(), and update_obj_state().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/FanControl.hpp
src/slic3r/GUI/Widgets/FanControl.cpp