OrcaSlicer: src/nanosvg/nanosvgrast.h File Reference
nanosvgrast.h File Reference
Typedefs
typedef struct NSVGrasterizer NSVGrasterizer
Functions
NSVGrasterizer * nsvgCreateRasterizer ()
void nsvgRasterize (NSVGrasterizer *r, NSVGimage *image, float tx, float ty, float scale, unsigned char *dst, int w, int h, int stride)
void nsvgDeleteRasterizer (NSVGrasterizer *)
Typedef Documentation
NSVGrasterizer
typedef struct NSVGrasterizer NSVGrasterizer
Function Documentation
nsvgCreateRasterizer()
NSVGrasterizer * nsvgCreateRasterizer ()
Referenced by Slic3r::GUI::get_data_from_svg(), Slic3r::GUI::GLTexture::load_from_svg(), Slic3r::GUI::IMTexture::load_from_svg_file(), Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), Slic3r::GUI::BitmapCache::load_svg(), and Slic3r::GUI::ImGuiWrapper::load_svg().
nsvgDeleteRasterizer()
void nsvgDeleteRasterizer (NSVGrasterizer *)
Referenced by Slic3r::GUI::get_data_from_svg(), Slic3r::GUI::GLTexture::load_from_svg(), Slic3r::GUI::IMTexture::load_from_svg_file(), Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), Slic3r::GUI::BitmapCache::load_svg(), and Slic3r::GUI::ImGuiWrapper::load_svg().
nsvgRasterize()
void nsvgRasterize (NSVGrasterizer * r, NSVGimage * image, float tx, float ty, float scale, unsigned char * dst, int w, int h, int stride)
Referenced by Slic3r::GUI::get_data_from_svg(), Slic3r::GUI::GLTexture::load_from_svg(), Slic3r::GUI::IMTexture::load_from_svg_file(), Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), Slic3r::GUI::BitmapCache::load_svg(), and Slic3r::GUI::ImGuiWrapper::load_svg().