OrcaSlicer: Slic3r::LinesBucket Class Reference
Slic3r::LinesBucket Class Reference
#include <src/libslic3r/GCode/ConflictChecker.hpp>
Public Member Functions
LinesBucket (ExtrusionLayers &&paths, const void *id, Point offset)
LinesBucket (LinesBucket &&)=default
std::pair< int, int > curRange () const
bool valid () const
void raise ()
float curBottomZ () const
LineWithIDs curLines () const
Public Attributes
float _curBottomZ = 0.0
unsigned _curPileIdx = 0
ExtrusionLayers _piles
const void * _id
Point _offset
Friends
bool operator> (const LinesBucket &left, const LinesBucket &right)
bool operator< (const LinesBucket &left, const LinesBucket &right)
bool operator== (const LinesBucket &left, const LinesBucket &right)
Detailed Description
Constructor & Destructor Documentation
LinesBucket() [1/2]
Slic3r::LinesBucket::LinesBucket (ExtrusionLayers && paths, const void * id, Point offset) inline
: _piles(paths), _id(id), _offset(offset) {}
LinesBucket() [2/2]
Slic3r::LinesBucket::LinesBucket (LinesBucket &&) default
Member Function Documentation
curBottomZ()
float Slic3r::LinesBucket::curBottomZ () const inline
{ return _curBottomZ; }
References _curBottomZ.
curLines()
LineWithIDs Slic3r::LinesBucket::curLines () const inline
    {
        auto [b, e] = curRange();
        LineWithIDs lines;
        for (int i = b; i < e; ++i) {
            for (const ExtrusionPath &path : _piles[i].paths) {
                if (path.is_force_no_extrusion() == false) {
                    Polyline check_polyline = path.polyline;
                    check_polyline.translate(_offset);
                    Lines tmpLines = check_polyline.lines();
                    for (const Line &line : tmpLines) { lines.emplace_back(line, _id, path.role()); }
                }
            }
        }
        return lines;
    }
References _id, _offset, _piles, curRange(), Slic3r::Polyline::lines(), and Slic3r::MultiPoint::translate().
curRange()
std::pair< int, int > Slic3r::LinesBucket::curRange () const inline
    {
        auto begin = std::lower_bound(_piles.begin(), _piles.end(), _piles[_curPileIdx], [](const ExtrusionLayer &l, const ExtrusionLayer &r) { return l.bottom_z < r.bottom_z; });
        auto end = std::upper_bound(_piles.begin(), _piles.end(), _piles[_curPileIdx], [](const ExtrusionLayer &l, const ExtrusionLayer &r) { return l.bottom_z < r.bottom_z; });
        return std::make_pair<int, int>(std::distance(_piles.begin(), begin), std::distance(_piles.begin(), end));
    }
References _curPileIdx, _piles, std::distance(), and end.
Referenced by curLines(), and raise().
raise()
void Slic3r::LinesBucket::raise () inline
    {
        if (!valid()) { return; }
        auto [b, e] = curRange();
        _curPileIdx += (e - b);
        _curBottomZ = _curPileIdx == _piles.size() ? _piles.back().bottom_z : _piles[_curPileIdx].bottom_z;
    }
References _curBottomZ, _curPileIdx, _piles, curRange(), and valid().
valid()
bool Slic3r::LinesBucket::valid () const inline
{ return _curPileIdx < _piles.size(); }
References _curPileIdx, and _piles.
Referenced by raise().
Friends And Related Symbol Documentation
operator<
bool operator< (const LinesBucket & left, const LinesBucket & right) friend
{ return left._curBottomZ < right._curBottomZ; }
operator==
bool operator== (const LinesBucket & left, const LinesBucket & right) friend
{ return left._curBottomZ == right._curBottomZ; }
operator>
bool operator> (const LinesBucket & left, const LinesBucket & right) friend
{ return left._curBottomZ > right._curBottomZ; }
Member Data Documentation
_curBottomZ
float Slic3r::LinesBucket::_curBottomZ = 0.0
Referenced by curBottomZ(), and raise().
_curPileIdx
unsigned Slic3r::LinesBucket::_curPileIdx = 0
Referenced by curRange(), raise(), and valid().
_id
const void* Slic3r::LinesBucket::_id
Referenced by curLines().
_offset
Point Slic3r::LinesBucket::_offset
Referenced by curLines().
_piles
ExtrusionLayers Slic3r::LinesBucket::_piles
Referenced by curLines(), curRange(), raise(), and valid().
The documentation for this class was generated from the following file:
src/libslic3r/GCode/ConflictChecker.hpp