OrcaSlicer: Clipper2Lib::PolyPath Class Reference
Clipper2Lib::PolyPath Class Reference abstract
#include <src/clipper2/Clipper2Lib/include/clipper2/clipper.engine.h>
Public Member Functions
PolyPath (PolyPath *parent=nullptr)
virtual ~PolyPath ()
PolyPath (const PolyPath &)=delete
PolyPath & operator= (const PolyPath &)=delete
unsigned Level () const
virtual PolyPath * AddChild (const Path64 &path)=0
virtual void Clear ()
virtual size_t Count () const
const PolyPath * Parent () const
bool IsHole () const
Protected Attributes
PolyPath * parent_
Detailed Description
Constructor & Destructor Documentation
PolyPath() [1/2]
Clipper2Lib::PolyPath::PolyPath (PolyPath * parent = nullptr) inline
: parent_(parent){}
~PolyPath()
virtual Clipper2Lib::PolyPath::~PolyPath () inline virtual
{ Clear(); };
References Clear().
PolyPath() [2/2]
Clipper2Lib::PolyPath::PolyPath (const PolyPath &) delete
Member Function Documentation
AddChild()
virtual PolyPath * Clipper2Lib::PolyPath::AddChild (const Path64 & path) pure virtual
Implemented in Clipper2Lib::PolyPath64, and Clipper2Lib::PolyPathD.
Referenced by Clipper2Lib::Clipper64::BuildTree64(), and Clipper2Lib::ClipperD::BuildTreeD().
Clear()
virtual void Clipper2Lib::PolyPath::Clear () inline virtual
Reimplemented in Clipper2Lib::PolyPath64, and Clipper2Lib::PolyPathD.
{};
Referenced by ~PolyPath().
Count()
virtual size_t Clipper2Lib::PolyPath::Count () const inline virtual
Reimplemented in Clipper2Lib::PolyPath64, and Clipper2Lib::PolyPathD.
{ return 0; }
IsHole()
bool Clipper2Lib::PolyPath::IsHole () const inline
    {
      const PolyPath* pp = parent_;
      bool is_hole = pp;
      while (pp) {
        is_hole = !is_hole;
        pp = pp->parent_;
      }
      return is_hole;
    }
References parent_.
Level()
unsigned Clipper2Lib::PolyPath::Level () const inline
    {
      unsigned result = 0;
      const PolyPath* p = parent_;
      while (p) { ++result; p = p->parent_; }
      return result;
    }
References parent_.
operator=()
PolyPath & Clipper2Lib::PolyPath::operator= (const PolyPath &) delete
Parent()
const PolyPath * Clipper2Lib::PolyPath::Parent () const inline
{ return parent_; }
References parent_.
Member Data Documentation
parent_
PolyPath* Clipper2Lib::PolyPath::parent_ protected
Referenced by IsHole(), Level(), and Parent().
The documentation for this class was generated from the following file:
src/clipper2/Clipper2Lib/include/clipper2/clipper.engine.h