OrcaSlicer: SideButton Class Reference
SideButton Class Reference
#include <src/slic3r/GUI/Widgets/SideButton.hpp>
Public Types
enum EHorizontalOrientation : unsigned char { HO_Left , HO_Center , HO_Right , Num_Horizontal_Orientations }
Public Member Functions
SideButton (wxWindow *parent, wxString text, wxString icon="", long style=0, int iconSize=0)
void SetCornerRadius (double radius)
void SetCornerEnable (const std::vector< bool > &enable)
void SetTextLayout (EHorizontalOrientation orient, int margin=15)
void SetLayoutStyle (int style)
void SetLabel (const wxString &label)
bool SetForegroundColour (wxColour const &colour) override
bool SetBackgroundColour (wxColour const &color) override
bool SetBottomColour (wxColour const &color)
void SetMinSize (const wxSize &size) override
void SetBorderColor (StateColor const &color)
void SetForegroundColor (StateColor const &color)
void SetBackgroundColor (StateColor const &color)
bool Enable (bool enable=true)
void Rescale ()
void SetExtraSize (const wxSize &size)
void SetIconOffset (const int offset)
Private Member Functions
void paintEvent (wxPaintEvent &evt)
void dorender (wxDC &dc, wxDC &text_dc)
void messureSize ()
void mouseDown (wxMouseEvent &event)
void mouseReleased (wxMouseEvent &event)
void sendButtonEvent ()
Private Attributes
wxSize textSize
wxSize minSize
ScalableBitmap icon
double radius
wxSize extra_size
int icon_offset
std::vector< bool > radius_enable
StateHandler state_handler
StateColor text_color
StateColor border_color
StateColor background_color
wxColour bottom_color
bool pressedDown = false
int layout_style = 0
EHorizontalOrientation text_orientation
int text_margin
Detailed Description
Member Enumeration Documentation
EHorizontalOrientation
enum SideButton::EHorizontalOrientation : unsigned char
Enumerator
HO_Left
HO_Center
HO_Right
Num_Horizontal_Orientations
    {
        HO_Left,
        HO_Center,
        HO_Right,
        Num_Horizontal_Orientations
    };
Constructor & Destructor Documentation
SideButton()
SideButton::SideButton (wxWindow * parent, wxString text, wxString icon = "", long style = 0, int iconSize = 0)
    : wxWindow(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, stlye)
    , state_handler(this)
{
    radius = 12;
#ifdef __APPLE__
    extra_size = wxSize(38 + FromDIP(20), 10);
    text_margin = 15 + FromDIP(20);
#else
    extra_size = wxSize(38, 10);
    text_margin = 15;
#endif
    icon_offset = 0;
    text_orientation = HO_Left;
    border_color.append(0x6B6B6B, StateColor::Disabled);
    border_color.append(wxColour(0, 137, 123), StateColor::Pressed);
    border_color.append(wxColour(38, 166, 154), StateColor::Hovered);
    border_color.append(0x009688, StateColor::Normal);
    text_color.append(0xACACAC, StateColor::Disabled);
    text_color.append(0xFEFEFE, StateColor::Pressed);
    text_color.append(0xFEFEFE, StateColor::Hovered);
    text_color.append(0xFEFEFE, StateColor::Normal);
    background_color.append(0x6B6B6B, StateColor::Disabled);
    background_color.append(wxColour(0, 137, 123), StateColor::Pressed);
    background_color.append(wxColour(38, 166, 154), StateColor::Hovered);
    background_color.append(0x009688, StateColor::Normal);
    SetBottomColour(wxColour("#3B4446"));
    state_handler.attach({ &border_color, &text_color, &background_color });
    state_handler.update_binds();
    // icon only
    if (!icon.IsEmpty()) {
        this->icon = ScalableBitmap(this, icon.ToStdString(), iconSize > 0 ? iconSize : 14);
    }
    SetFont(Label::Body_14);
    wxWindow::SetLabel(text);
    messureSize();
}
References Label::Body_14, StateColor::Disabled, StateColor::Hovered, StateColor::Normal, StateColor::Pressed, and text_color().
Member Function Documentation
dorender()
void SideButton::dorender (wxDC & dc, wxDC & text_dc) private
{
    wxSize size = GetSize();
    // draw background
    dc.SetPen(wxNullPen);
    dc.SetBrush(StateColor::darkModeColorFor(bottom_color));
    dc.DrawRectangle(0, 0, size.x, size.y);
    int states = state_handler.states();
    dc.SetBrush(wxBrush(background_color.colorForStates(states)));
    dc.SetPen(wxPen(border_color.colorForStates(states)));
    int pen_width = dc.GetPen().GetWidth();
    // draw icon style
    if (icon.bmp().IsOk()) {
        if (radius > 1e-5) {
            dc.DrawRoundedRectangle(0, 0, size.x, size.y, radius);
            dc.DrawRectangle(radius, 0, size.x - radius, size.y);
            dc.SetPen(wxNullPen);
            dc.DrawRectangle(radius - pen_width, pen_width, radius, size.y - 2 * pen_width);
        }
        else {
            dc.DrawRectangle(0, 0, size.x, size.y);
        }
    }
    // draw text style
    else {
        if (radius > 1e-5) {
            if (layout_style == 1) {
                dc.DrawRoundedRectangle(0, 0, size.x, size.y, radius);
                dc.SetPen(wxNullPen);
            } else {
                dc.DrawRoundedRectangle(0, 0, size.x, size.y, radius);
                dc.DrawRectangle(0, 0, radius, size.y);
                dc.SetPen(wxNullPen);
                dc.DrawRectangle(pen_width, pen_width, size.x - radius, size.y - 2 * pen_width);
            }
        } else {
            dc.DrawRectangle(0, 0, size.x, size.y);
        }
    }
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    // calc content size
    wxSize szIcon;
    wxSize szContent = textSize;
    if (icon.bmp().IsOk()) {
        if (szContent.y > 0) {
            //BBS norrow size between text and icon
            szContent.x += 5;
        }
        szIcon = icon.GetBmpSize();
        szContent.x += szIcon.x;
        if (szIcon.y > szContent.y)
            szContent.y = szIcon.y;
    }
    // move to center
    wxRect rcContent = { {0, 0}, size };
    if (text_orientation == EHorizontalOrientation::HO_Center) {
        wxSize offset = (size - szContent) / 2;
        rcContent.Deflate(offset.x, offset.y);
    } else if (text_orientation == EHorizontalOrientation::HO_Left) {
        wxSize offset = (size - szContent) / 2;
        rcContent.Deflate(text_margin, offset.y);
    } else if (text_orientation == EHorizontalOrientation::HO_Right) {
        wxSize offset = (size - szContent) / 2;
        rcContent.Deflate(size.x - text_margin, offset.y);
    }
    // start draw
    wxPoint pt = rcContent.GetLeftTop();
    if (icon.bmp().IsOk()) {
        //BBS extra pixels for icon
        pt.x += icon_offset;
        pt.y += (rcContent.height - szIcon.y) / 2;
        dc.DrawBitmap(icon.bmp(), pt);
        //BBS norrow size between text and icon
        pt.x += szIcon.x + 5;
        pt.y = rcContent.y;
    }
    auto text = GetLabel();
    if (!text.IsEmpty()) {
        pt.y += (rcContent.height - textSize.y) / 2;
        text_dc.SetFont(GetFont());
        text_dc.SetTextForeground(text_color.colorForStates(states));
        text_dc.DrawText(text, pt);
    }
}
References background_color, ScalableBitmap::bmp(), border_color, bottom_color, StateColor::colorForStates(), StateColor::darkModeColorFor(), ScalableBitmap::GetBmpSize(), HO_Center, HO_Left, HO_Right, icon, icon_offset, layout_style, radius, size, state_handler, StateHandler::states(), text_color, text_margin, text_orientation, and textSize.
Referenced by paintEvent().
Enable()
bool SideButton::Enable (bool enable = true)
{
    bool result = wxWindow::Enable(enable);
    if (result) {
        wxCommandEvent e(EVT_ENABLE_CHANGED);
        e.SetEventObject(this);
        GetEventHandler()->ProcessEvent(e);
    }
    return result;
}
Referenced by Slic3r::GUI::MainFrame::MainFrame().
messureSize()
void SideButton::messureSize () private
{
    textSize = GetTextExtent(GetLabel());
    if (minSize.GetWidth() > 0) {
        wxWindow::SetMinSize(minSize);
        return;
    }
    wxSize szContent = textSize;
    if (this->icon.bmp().IsOk()) {
        if (szContent.y > 0) {
            szContent.x += 5;
        }
        wxSize szIcon = this->icon.GetBmpSize();
        szContent.x += szIcon.x;
        if (szIcon.y > szContent.y)
            szContent.y = szIcon.y;
        //BBS icon only
        wxWindow::SetMinSize(szContent + wxSize(szContent.GetX() + extra_size.GetX(), minSize.GetHeight()));
    }
    else {
        if (minSize.GetHeight() > 0) {
            //BBS with text size
            wxWindow::SetMinSize(wxSize(szContent.GetX() + extra_size.GetX(), minSize.GetHeight()));
        } else {
            //BBS with text size
            wxWindow::SetMinSize(szContent + extra_size);
        }
    }
}
References ScalableBitmap::bmp(), extra_size, ScalableBitmap::GetBmpSize(), icon, minSize, and textSize.
Referenced by Rescale(), SetExtraSize(), SetIconOffset(), SetLabel(), SetLayoutStyle(), SetMinSize(), and SetTextLayout().
mouseDown()
void SideButton::mouseDown (wxMouseEvent & event) private
{
    event.Skip();
    pressedDown = true;
    SetFocus();
    CaptureMouse();
}
References pressedDown.
mouseReleased()
void SideButton::mouseReleased (wxMouseEvent & event) private
{
    event.Skip();
    if (pressedDown) {
        pressedDown = false;
        ReleaseMouse();
        if (wxRect({0, 0}, GetSize()).Contains(event.GetPosition()))
            sendButtonEvent();
    }
}
References pressedDown, and sendButtonEvent().
paintEvent()
void SideButton::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
#ifdef __WXMSW__
    wxGCDC dc2(dc);
#else
    wxDC & dc2(dc);
#endif
    wxDC & dctext(dc);
    dorender(dc2, dctext);
}
References dorender().
Rescale()
void SideButton::Rescale ()
{
    if (this->icon.bmp().IsOk())
        this->icon.msw_rescale();
    messureSize();
}
References ScalableBitmap::bmp(), icon, messureSize(), and ScalableBitmap::msw_rescale().
sendButtonEvent()
void SideButton::sendButtonEvent () private
{
    wxCommandEvent event(wxEVT_COMMAND_BUTTON_CLICKED, GetId());
    event.SetEventObject(this);
    GetEventHandler()->ProcessEvent(event);
}
Referenced by mouseReleased().
SetBackgroundColor()
void SideButton::SetBackgroundColor (StateColor const & color)
{
    background_color = color;
    state_handler.update_binds();
    Refresh();
}
References background_color, state_handler, and StateHandler::update_binds().
SetBackgroundColour()
bool SideButton::SetBackgroundColour (wxColour const & color) override
{
    background_color = StateColor(color);
    state_handler.update_binds();
    return true;
}
References background_color, state_handler, and StateHandler::update_binds().
SetBorderColor()
void SideButton::SetBorderColor (StateColor const & color)
{
    border_color = color;
    state_handler.update_binds();
    Refresh();
}
References border_color, state_handler, and StateHandler::update_binds().
SetBottomColour()
bool SideButton::SetBottomColour (wxColour const & color)
{
    bottom_color = color;
    return true;
}
References bottom_color.
SetCornerEnable()
void SideButton::SetCornerEnable (const std::vector< bool > & enable)
{
    radius_enable.clear();
    for (auto en : enable) {
        radius_enable.push_back(en);
    }
}
References radius_enable.
SetCornerRadius()
void SideButton::SetCornerRadius (double radius)
{
    this->radius = radius;
    Refresh();
}
References radius.
Referenced by Slic3r::GUI::MainFrame::create_side_tools().
SetExtraSize()
void SideButton::SetExtraSize (const wxSize & size)
{
    extra_size = size;
    messureSize();
}
References extra_size, messureSize(), and size.
SetForegroundColor()
void SideButton::SetForegroundColor (StateColor const & color)
{
    text_color = color;
    state_handler.update_binds();
    Refresh();
}
References state_handler, text_color, and StateHandler::update_binds().
SetForegroundColour()
bool SideButton::SetForegroundColour (wxColour const & colour) override
{
    text_color = StateColor(color);
    state_handler.update_binds();
    return true;
}
References state_handler, text_color, and StateHandler::update_binds().
SetIconOffset()
void SideButton::SetIconOffset (const int offset)
{
    icon_offset = offset;
    messureSize();
}
References icon_offset, and messureSize().
SetLabel()
void SideButton::SetLabel (const wxString & label)
{
    wxWindow::SetLabel(label);
    messureSize();
    Refresh();
}
References messureSize().
SetLayoutStyle()
void SideButton::SetLayoutStyle (int style)
{
    layout_style = style;
    messureSize();
    Refresh();
}
References layout_style, messureSize(), and style.
SetMinSize()
void SideButton::SetMinSize (const wxSize & size) override
{
    minSize = size;
    messureSize();
}
References messureSize(), minSize, and size.
SetTextLayout()
void SideButton::SetTextLayout (EHorizontalOrientation orient, int margin = 15)
{
    text_orientation = orient;
    text_margin = margin;
    messureSize();
    Refresh();
}
References messureSize(), text_margin, and text_orientation.
Member Data Documentation
background_color
StateColor SideButton::background_color private
Referenced by dorender(), SetBackgroundColor(), and SetBackgroundColour().
border_color
StateColor SideButton::border_color private
Referenced by dorender(), and SetBorderColor().
bottom_color
wxColour SideButton::bottom_color private
Referenced by dorender(), and SetBottomColour().
extra_size
wxSize SideButton::extra_size private
Referenced by messureSize(), and SetExtraSize().
icon
ScalableBitmap SideButton::icon private
Referenced by dorender(), messureSize(), and Rescale().
icon_offset
int SideButton::icon_offset private
Referenced by dorender(), and SetIconOffset().
layout_style
int SideButton::layout_style = 0 private
Referenced by dorender(), and SetLayoutStyle().
minSize
wxSize SideButton::minSize private
Referenced by messureSize(), and SetMinSize().
pressedDown
bool SideButton::pressedDown = false private
Referenced by mouseDown(), and mouseReleased().
radius
double SideButton::radius private
Referenced by dorender(), and SetCornerRadius().
radius_enable
std::vector<bool> SideButton::radius_enable private
Referenced by SetCornerEnable().
state_handler
StateHandler SideButton::state_handler private
Referenced by dorender(), SetBackgroundColor(), SetBackgroundColour(), SetBorderColor(), SetForegroundColor(), and SetForegroundColour().
text_color
StateColor SideButton::text_color private
Referenced by dorender(), SetForegroundColor(), and SetForegroundColour().
text_margin
int SideButton::text_margin private
Referenced by dorender(), and SetTextLayout().
text_orientation
EHorizontalOrientation SideButton::text_orientation private
Referenced by dorender(), and SetTextLayout().
textSize
wxSize SideButton::textSize private
Referenced by dorender(), and messureSize().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/SideButton.hpp
src/slic3r/GUI/Widgets/SideButton.cpp