OrcaSlicer: Slic3r::OverhangCluster Struct Reference
Slic3r::OverhangCluster Struct Reference
Public Member Functions
OverhangCluster (ExPolygon *overhang, int layer_nr, coordf_t offset_scaled)
void insert (ExPolygon *overhang_new, int layer_nr)
int height ()
bool intersects (const ExPolygon &overhang_new, int layer_nr)
Public Attributes
std::map< int, std::vector< ExPolygon * > > layer_overhangs
ExPolygons merged_overhangs_dilated
int min_layer = 1e7
int max_layer = 0
coordf_t offset_scaled = 0
bool is_cantilever = false
bool is_sharp_tail = false
bool is_small_overhang = false
Detailed Description
Constructor & Destructor Documentation
OverhangCluster()
Slic3r::OverhangCluster::OverhangCluster (ExPolygon * overhang, int layer_nr, coordf_t offset_scaled) inline
{
        this->offset_scaled = offset_scaled;
        insert(overhang, layer_nr);
    }
Member Function Documentation
height()
int Slic3r::OverhangCluster::height () inline
                 {
        return max_layer - min_layer + 1;
    }
insert()
void Slic3r::OverhangCluster::insert (ExPolygon * overhang_new, int layer_nr) inline
{
        if (layer_overhangs.find(layer_nr) != layer_overhangs.end()) {
            layer_overhangs[layer_nr].push_back(overhang_new);
        }
        else {
            layer_overhangs.emplace(layer_nr, std::vector<ExPolygon*>{ overhang_new });
        }
        ExPolygons overhang_dilated = offset_scaled > EPSILON ? offset_ex(*overhang_new, offset_scaled) : ExPolygons{ *overhang_new };
        if (!overhang_dilated.empty())
            merged_overhangs_dilated = union_ex(merged_overhangs_dilated, overhang_dilated);
        min_layer = std::min(min_layer, layer_nr);
        max_layer = std::max(max_layer, layer_nr);
    }
References EPSILON, Slic3r::offset_ex(), and Slic3r::union_ex().
intersects()
bool Slic3r::OverhangCluster::intersects (const ExPolygon & overhang_new, int layer_nr) inline
{
        if (layer_nr < 1)
            return false;
        //auto it = layer_overhangs.find(layer_nr - 1);
        //if (it == layer_overhangs.end())
        //    return false;
        //ExPolygons overhangs_lower;
        //for (ExPolygon* poly : it->second) {
        //    overhangs_lower.push_back(*poly);
        //}
        if (layer_nr<min_layer - 1 || layer_nr>max_layer + 1)
            return false;
        const ExPolygons overhang_dilated = offset_ex(overhang_new, offset_scaled);
        return overlaps(overhang_dilated, merged_overhangs_dilated);
    }
References Slic3r::offset_ex(), and Slic3r::overlaps().
Member Data Documentation
is_cantilever
bool Slic3r::OverhangCluster::is_cantilever = false
is_sharp_tail
bool Slic3r::OverhangCluster::is_sharp_tail = false
is_small_overhang
bool Slic3r::OverhangCluster::is_small_overhang = false
layer_overhangs
std::map<int, std::vector<ExPolygon*> > Slic3r::OverhangCluster::layer_overhangs
max_layer
int Slic3r::OverhangCluster::max_layer = 0
merged_overhangs_dilated
ExPolygons Slic3r::OverhangCluster::merged_overhangs_dilated
min_layer
int Slic3r::OverhangCluster::min_layer = 1e7
offset_scaled
coordf_t Slic3r::OverhangCluster::offset_scaled = 0
The documentation for this struct was generated from the following file:
src/libslic3r/SupportMaterial.cpp