OrcaSlicer: StaticLine Class Reference
StaticLine Class Reference
#include <src/slic3r/GUI/Widgets/StaticLine.hpp>
Public Member Functions
StaticLine (wxWindow *parent, bool vertical=false, const wxString &label={}, const wxString &icon={})
void SetLabel (const wxString &label) override
void SetIcon (const wxString &icon)
void SetLineColour (wxColour color)
void Rescale ()
Private Member Functions
void paintEvent (wxPaintEvent &evt)
void messureSize ()
void render (wxDC &dc)
Private Attributes
wxColour lineColor
bool vertical
ScalableBitmap icon
Detailed Description
Constructor & Destructor Documentation
StaticLine()
StaticLine::StaticLine (wxWindow * parent, bool vertical = false, const wxString & label = {}, const wxString & icon = {})
    : wxWindow(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE)
    , vertical(vertical)
{
    wxWindow::SetBackgroundColour(parent->GetBackgroundColour());
    this->lineColor = wxColour("#EEEEEE");
    DisableFocusFromKeyboard();
    SetFont(Label::Body_14);
    wxWindow::SetLabel(label);
    SetIcon(icon);
}
References Label::Body_14.
Member Function Documentation
messureSize()
void StaticLine::messureSize () private
{
    wxClientDC dc(this);
    wxSize textSize = dc.GetTextExtent(GetLabel());
    wxSize szContent = textSize;
    if (this->icon.bmp().IsOk()) {
        if (szContent.y > 0) {
            // BBS norrow size between text and icon
            szContent.x += 5;
        }
        wxSize szIcon = this->icon.GetBmpSize();
        szContent.x += szIcon.x;
        if (szIcon.y > szContent.y) szContent.y = szIcon.y;
    }
    if (vertical)
        szContent.y += 10;
    else
        szContent.x += 10;
    SetMinSize(szContent);
}
References ScalableBitmap::bmp(), ScalableBitmap::GetBmpSize(), icon, and vertical.
Referenced by Rescale(), SetIcon(), and SetLabel().
paintEvent()
void StaticLine::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    render(dc);
}
References render().
render()
void StaticLine::render (wxDC & dc) private
{
    wxSize size = GetSize();
    wxSize textSize;
    auto   label = GetLabel();
    if (!label.IsEmpty()) textSize = dc.GetTextExtent(label);
    wxRect titleRect{{0, 0}, size};
    titleRect.height = wxMax(icon.GetBmpHeight(), textSize.GetHeight());
    int contentWidth = icon.GetBmpWidth() + ((icon.bmp().IsOk() && textSize.GetWidth() > 0) ? 5 : 0) +
                textSize.GetWidth();
    if (vertical) titleRect.Deflate((size.GetWidth() - contentWidth) / 2, 0);
    if (icon.bmp().IsOk()) {
        dc.DrawBitmap(icon.bmp(), {0, (size.y - icon.GetBmpHeight()) / 2});
        titleRect.x += icon.GetBmpWidth() + 5;
    }
    if (!label.IsEmpty()) {
        dc.SetTextForeground(StateColor::darkModeColorFor(GetForegroundColour()));
        dc.DrawText(label, titleRect.x, (size.GetHeight() - textSize.GetHeight()) / 2);
        titleRect.x += textSize.GetWidth() + 5;
    }
    dc.SetPen(wxPen(StateColor::darkModeColorFor(lineColor)));
    if (vertical) {
        size.x /= 2;
        if (titleRect.y > 0) titleRect.y += 5;
        dc.DrawLine(size.x, titleRect.y, size.x, size.y);
    } else {
        size.y /= 2;
        dc.DrawLine(titleRect.x, size.y, size.x, size.y);
    }
}
References ScalableBitmap::bmp(), StateColor::darkModeColorFor(), ScalableBitmap::GetBmpHeight(), ScalableBitmap::GetBmpWidth(), icon, lineColor, size, and vertical.
Referenced by paintEvent().
Rescale()
void StaticLine::Rescale ()
{
    if (this->icon.bmp().IsOk())
        this->icon.msw_rescale();
    messureSize();
}
References ScalableBitmap::bmp(), icon, messureSize(), and ScalableBitmap::msw_rescale().
SetIcon()
void StaticLine::SetIcon (const wxString & icon)
{
    this->icon = icon.IsEmpty() ? ScalableBitmap()
        : ScalableBitmap(this, icon.ToStdString(), 18);
    messureSize();
    Refresh();
}
References icon, and messureSize().
SetLabel()
void StaticLine::SetLabel (const wxString & label) override
{
    wxWindow::SetLabel(label);
    messureSize();
    Refresh();
}
References messureSize().
SetLineColour()
void StaticLine::SetLineColour (wxColour color)
{
    this->lineColor = color;
}
References lineColor.
Referenced by Slic3r::GUI::MonitorBasePanel::MonitorBasePanel(), Slic3r::GUI::PrintOptionsDialog::create_settings_group(), Slic3r::GUI::StatusBasePanel::create_temp_axis_group(), and Slic3r::GUI::StatusBasePanel::create_temp_control().
Member Data Documentation
icon
ScalableBitmap StaticLine::icon private
Referenced by messureSize(), render(), Rescale(), and SetIcon().
lineColor
wxColour StaticLine::lineColor private
Referenced by render(), and SetLineColour().
vertical
bool StaticLine::vertical private
Referenced by messureSize(), and render().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/StaticLine.hpp
src/slic3r/GUI/Widgets/StaticLine.cpp