OrcaSlicer: Slic3r::ExtrusionQualityEstimator Class Reference
Slic3r::ExtrusionQualityEstimator Class Reference
#include <src/libslic3r/GCode/ExtrusionProcessor.hpp>
Public Member Functions
void set_current_object (const PrintObject *object)
void prepare_for_new_layer (const PrintObject *obj, const Layer *layer)
std::vector< ProcessedPoint > estimate_extrusion_quality (const ExtrusionPath &path, const ConfigOptionPercents &overlaps, const ConfigOptionFloatsOrPercents &speeds, float ext_perimeter_speed, float original_speed)
Private Attributes
std::unordered_map< const PrintObject *, AABBTreeLines::LinesDistancer< Linef > > prev_layer_boundaries
std::unordered_map< const PrintObject *, AABBTreeLines::LinesDistancer< Linef > > next_layer_boundaries
const PrintObject * current_object
Detailed Description
Member Function Documentation
estimate_extrusion_quality()
std::vector< ProcessedPoint > Slic3r::ExtrusionQualityEstimator::estimate_extrusion_quality (const ExtrusionPath & path, const ConfigOptionPercents & overlaps, const ConfigOptionFloatsOrPercents & speeds, float ext_perimeter_speed, float original_speed) inline
    {
        size_t                               speed_sections_count = std::min(overlaps.values.size(), speeds.values.size());
        std::vector<std::pair<float, float>> speed_sections;
        for (size_t i = 0; i < speed_sections_count; i++) {
            float distance = path.width * (1.0 - (overlaps.get_at(i) / 100.0));
            float speed    = speeds.get_at(i).percent ? (ext_perimeter_speed * speeds.get_at(i).value / 100.0) : speeds.get_at(i).value;
            speed_sections.push_back({distance, speed});
        }
        std::sort(speed_sections.begin(), speed_sections.end(),
                  [](const std::pair<float, float> &a, const std::pair<float, float> &b) {
                    if (a.first == b.first) {
                        return a.second > b.second;
                    }
                    return a.first < b.first; });
        std::pair<float, float> last_section{INFINITY, 0};
        for (auto &section : speed_sections) {
            if (section.first == last_section.first) {
                section.second = last_section.second;
            } else {
                last_section = section;
            }
        }
        std::vector<ExtendedPoint> extended_points =
            estimate_points_properties<true, true, true, true>(path.polyline.points, prev_layer_boundaries[current_object], path.width);
        const auto width_inv = 1.0f / path.width;
        std::vector<ProcessedPoint> processed_points;
        processed_points.reserve(extended_points.size());
        for (size_t i = 0; i < extended_points.size(); i++) {
            const ExtendedPoint &curr = extended_points[i];
            const ExtendedPoint &next = extended_points[i + 1 < extended_points.size() ? i + 1 : i];
            auto calculate_speed = [&speed_sections, &original_speed](float distance) {
                float final_speed;
                if (distance <= speed_sections.front().first) {
                    final_speed = original_speed;
                } else if (distance >= speed_sections.back().first) {
                    final_speed = speed_sections.back().second;
                } else {
                    size_t section_idx = 0;
                    while (distance > speed_sections[section_idx + 1].first) {
                        section_idx++;
                    }
                    float t = (distance - speed_sections[section_idx].first) /
                              (speed_sections[section_idx + 1].first - speed_sections[section_idx].first);
                    t           = std::clamp(t, 0.0f, 1.0f);
                    final_speed = (1.0f - t) * speed_sections[section_idx].second + t * speed_sections[section_idx + 1].second;
                }
                return final_speed;
            };
            float extrusion_speed = std::min(calculate_speed(curr.distance), calculate_speed(next.distance));
            float overlap = std::min(1 - curr.distance * width_inv, 1 - next.distance * width_inv);
            processed_points.push_back({ scaled(curr.position), extrusion_speed, overlap });
        }
        return processed_points;
    }
References Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::overlaps(), Slic3r::FloatOrPercent::percent, Slic3r::FloatOrPercent::value, Slic3r::ConfigOptionVector< T >::values, and Slic3r::ExtrusionPath::width.
prepare_for_new_layer()
void Slic3r::ExtrusionQualityEstimator::prepare_for_new_layer (const PrintObject * obj, const Layer * layer) inline
    {
        if (layer == nullptr) return;
        const PrintObject *object = obj;
        prev_layer_boundaries[object] = next_layer_boundaries[object];
        next_layer_boundaries[object] = AABBTreeLines::LinesDistancer<Linef>{to_unscaled_linesf(layer->lslices)};
    }
References Slic3r::Layer::lslices, next_layer_boundaries, prev_layer_boundaries, and Slic3r::to_unscaled_linesf().
set_current_object()
void Slic3r::ExtrusionQualityEstimator::set_current_object (const PrintObject * object) inline
{ current_object = object; }
References current_object.
Member Data Documentation
current_object
const PrintObject* Slic3r::ExtrusionQualityEstimator::current_object private
Referenced by set_current_object().
next_layer_boundaries
std::unordered_map<const PrintObject *, AABBTreeLines::LinesDistancer<Linef> > Slic3r::ExtrusionQualityEstimator::next_layer_boundaries private
Referenced by prepare_for_new_layer().
prev_layer_boundaries
std::unordered_map<const PrintObject *, AABBTreeLines::LinesDistancer<Linef> > Slic3r::ExtrusionQualityEstimator::prev_layer_boundaries private
Referenced by prepare_for_new_layer().
The documentation for this class was generated from the following file:
src/libslic3r/GCode/ExtrusionProcessor.hpp