OrcaSlicer: src/qhull/src/libqhullcpp/QhullSet.h File Reference
QhullSet.h File Reference
#include "libqhull_r/qhull_ra.h"
#include "libqhullcpp/QhullError.h"
#include "libqhullcpp/QhullQh.h"
#include <cstddef>
#include <vector>
Classes
class orgQhull::QhullSetBase
Base class for QhullSet<T> QhullSet<T> defined below QhullSetIterator<T> defined below.
class orgQhull::QhullSet< T >
QhullSet<T> – A read-only wrapper to Qhull's collection class, setT. QhullSet is similar to STL's <vector> and Qt's QVector QhullSet is unrelated to STL and Qt's set and map types (e.g., QSet and QMap) T is a Qhull type that defines 'base_type' and getBaseT() (e.g., QhullFacet with base_type 'facetT *' A QhullSet does not own its contents – erase(), clear(), removeFirst(), removeLast(), pop_back(), pop_front(), fromStdList() not defined QhullSetIterator is faster than STL-style iterator/const_iterator Qhull's FOREACHelement_() [qset_r.h] maybe more efficient than QhullSet. It uses a NULL terminator instead of an end pointer. STL requires an end pointer. Derived from QhullLinkedList.h and Qt/core/tools/qlist.h w/o QT_STRICT_ITERATORS.
class orgQhull::QhullSet< T >::iterator
class orgQhull::QhullSet< T >::const_iterator
class orgQhull::QhullSetIterator< T >
Faster then interator/const_iterator due to T::base_type.
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
== Global namespace =========================================
template<typename T >
std::ostream & operator<< (std::ostream &os, const orgQhull::QhullSet< T > &qs)
Function Documentation
operator<<()
template<typename T > std::ostream & operator<< (std::ostream & os, const orgQhull::QhullSet< T > & qs)
{
    const typename T::base_type *i= qs.data();
    const typename T::base_type *e= qs.endData();
    while(i!=e){
        os << T(qs.qh(), *i++);
    }
    return os;
}//operator<<
References orgQhull::QhullSet< T >::data(), orgQhull::QhullSet< T >::endData(), and orgQhull::QhullSetBase::qh().