OrcaSlicer: SidePopup Class Reference
SidePopup Class Reference
#include <src/slic3r/GUI/Widgets/SideMenuPopup.hpp>
Public Member Functions
SidePopup (wxWindow *parent)
~SidePopup ()
void Create ()
virtual void Popup (wxWindow *focus=NULL) wxOVERRIDE
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
virtual bool Show (bool show=true) wxOVERRIDE
void append_button (SideButton *btn)
void paintEvent (wxPaintEvent &evt)
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Private Attributes
std::vector< SideButton * > btn_list
Detailed Description
Constructor & Destructor Documentation
SidePopup()
SidePopup::SidePopup (wxWindow * parent)
~SidePopup()
SidePopup::~SidePopup ()
{
    ;
}
Member Function Documentation
append_button()
void SidePopup::append_button (SideButton * btn)
{
    btn_list.push_back(btn);
}
References btn_list.
Referenced by Slic3r::GUI::MainFrame::create_side_tools().
Create() [1/2]
void SidePopup::Create ()
{
    wxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    int max_width = 0;
    int height = 0;
    for (auto btn : btn_list)
    {
        max_width = std::max(btn->GetMinSize().x, max_width);
    }
    for (auto btn : btn_list)
    {
        wxSize size = btn->GetMinSize();
        height += size.y;
        size.x = max_width;
        btn->SetMinSize(size);
        btn->SetSize(size);
        sizer->Add(btn, 0, 0, 0);
    }
    SetSize(wxSize(max_width, height));
    SetSizer(sizer, true);
    Layout();
    Refresh();
}
References btn_list, and size.
Referenced by Popup().
Create() [2/2]
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
OnDismiss()
void SidePopup::OnDismiss () virtual
{
    Slic3r::GUI::wxGetApp().set_side_menu_popup_status(false);
    PopupWindow::OnDismiss();
}
paintEvent()
void SidePopup::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    wxSize size = GetSize();
    dc.SetBrush(wxTransparentColour);
    dc.DrawRectangle(0, 0, size.x, size.y);
}
References size.
Popup()
void SidePopup::Popup (wxWindow * focus = NULL) virtual
{
    Create();
    auto drect = wxDisplay(GetParent()).GetGeometry();
    int screenwidth = drect.x + drect.width;
    //int screenwidth = wxSystemSettings::GetMetric(wxSYS_SCREEN_X,NULL);
    int max_width = 0;
    for (auto btn : btn_list)
    {
        max_width = std::max(btn->GetMinSize().x, max_width);
    }
    if (focus) {
        wxPoint pos = focus->ClientToScreen(wxPoint(0, -6));
#ifdef __APPLE__
         pos.x = pos.x - FromDIP(20);
#endif // __APPLE__
        if (pos.x + max_width > screenwidth)
            Position({pos.x - (pos.x + max_width - screenwidth),pos.y}, {0, focus->GetSize().y + 12});
        else
            Position(pos, {0, focus->GetSize().y + 12});
    }
    Slic3r::GUI::wxGetApp().set_side_menu_popup_status(true);
    PopupWindow::Popup();
}
References btn_list, and Create().
Referenced by Slic3r::GUI::MainFrame::create_side_tools().
ProcessLeftDown()
bool SidePopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
Show()
bool SidePopup::Show (bool show = true) virtual
{
    return PopupWindow::Show(show);
}
Member Data Documentation
btn_list
std::vector<SideButton*> SidePopup::btn_list private
Referenced by append_button(), Create(), and Popup().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/SideMenuPopup.hpp
src/slic3r/GUI/Widgets/SideMenuPopup.cpp