OrcaSlicer: orgQhull::PointCoordinatesIterator Class Reference
orgQhull::PointCoordinatesIterator Class Reference
#include <src/qhull/src/libqhullcpp/PointCoordinates.h>
Public Member Functions
PointCoordinatesIterator (const PointCoordinates &container)
PointCoordinatesIterator & operator= (const PointCoordinates &container)
void toFront ()
void toBack ()
bool hasNext () const
const QhullPoint next ()
const QhullPoint peekNext () const
bool hasPrevious () const
const QhullPoint previous ()
const QhullPoint peekPrevious () const
bool findNext (const QhullPoint &t)
bool findPrevious (const QhullPoint &t)
Private Types
typedef PointCoordinates::const_iterator const_iterator
Private Attributes
const PointCoordinates * c
const_iterator i
Detailed Description
Member Typedef Documentation
const_iterator
typedef PointCoordinates::const_iterator orgQhull::PointCoordinatesIterator::const_iterator private
Constructor & Destructor Documentation
PointCoordinatesIterator()
orgQhull::PointCoordinatesIterator::PointCoordinatesIterator (const PointCoordinates & container) inline
: c(&container), i(c->constBegin()) {}
Member Function Documentation
findNext()
bool orgQhull::PointCoordinatesIterator::findNext (const QhullPoint & t) inline
{ while(i != c->constEnd()){ if (*i++ == t) return true;} return false; }
References c, orgQhull::QhullPoints::constEnd(), and i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
findPrevious()
bool orgQhull::PointCoordinatesIterator::findPrevious (const QhullPoint & t) inline
{ while(i != c->constBegin()){ if (*(--i) == t) return true;} return false;  }
References c, orgQhull::QhullPoints::constBegin(), and i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
hasNext()
bool orgQhull::PointCoordinatesIterator::hasNext () const inline
{ return i != c->constEnd(); }
References c, orgQhull::QhullPoints::constEnd(), and i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
hasPrevious()
bool orgQhull::PointCoordinatesIterator::hasPrevious () const inline
{ return i != c->constBegin(); }
References c, orgQhull::QhullPoints::constBegin(), and i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
next()
const QhullPoint orgQhull::PointCoordinatesIterator::next () inline
{ return *i++; }
References i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
operator=()
PointCoordinatesIterator & orgQhull::PointCoordinatesIterator::operator= (const PointCoordinates & container) inline
{ c = &container; i = c->constBegin(); return *this; }
References c, orgQhull::QhullPoints::constBegin(), and i.
peekNext()
const QhullPoint orgQhull::PointCoordinatesIterator::peekNext () const inline
{ return *i; }
References i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
peekPrevious()
const QhullPoint orgQhull::PointCoordinatesIterator::peekPrevious () const inline
{ const_iterator p = i; return *--p; }
References i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
previous()
const QhullPoint orgQhull::PointCoordinatesIterator::previous () inline
{ return *--i; }
References i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
toBack()
void orgQhull::PointCoordinatesIterator::toBack () inline
{ i = c->constEnd(); }
References c, orgQhull::QhullPoints::constEnd(), and i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
toFront()
void orgQhull::PointCoordinatesIterator::toFront () inline
{ i = c->constBegin(); }
References c, orgQhull::QhullPoints::constBegin(), and i.
Referenced by orgQhull::PointCoordinates_test::t_coord_iterator().
Member Data Documentation
c
const PointCoordinates* orgQhull::PointCoordinatesIterator::c private
Referenced by findNext(), findPrevious(), hasNext(), hasPrevious(), operator=(), toBack(), and toFront().
i
const_iterator orgQhull::PointCoordinatesIterator::i private
Referenced by findNext(), findPrevious(), hasNext(), hasPrevious(), next(), operator=(), peekNext(), peekPrevious(), previous(), toBack(), and toFront().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/PointCoordinates.h