OrcaSlicer: Slic3r::GUI::AMSrefresh Class Reference
Slic3r::GUI::AMSrefresh Class Reference
#include <src/slic3r/GUI/Widgets/AMSControl.hpp>
Public Member Functions
AMSrefresh ()
AMSrefresh (wxWindow *parent, wxWindowID id, wxString number, Caninfo info, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
AMSrefresh (wxWindow *parent, wxWindowID id, int number, Caninfo info, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~AMSrefresh ()
void PlayLoading ()
void StopLoading ()
void create (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size)
void on_timer (wxTimerEvent &event)
void OnEnterWindow (wxMouseEvent &evt)
void OnLeaveWindow (wxMouseEvent &evt)
void OnClick (wxMouseEvent &evt)
void post_event (wxCommandEvent &&event)
void paintEvent (wxPaintEvent &evt)
void Update (std::string ams_id, Caninfo info)
void msw_rescale ()
Public Attributes
Caninfo m_info
Protected Member Functions
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
Protected Attributes
wxTimer * m_playing_timer = {nullptr}
int m_rotation_angle = 0
bool m_play_loading = {false}
bool m_selected = {false}
std::string m_ams_id
std::string m_can_id
ScalableBitmap m_bitmap_normal
ScalableBitmap m_bitmap_selected
ScalableBitmap m_bitmap_ams_rfid_0
ScalableBitmap m_bitmap_ams_rfid_1
ScalableBitmap m_bitmap_ams_rfid_2
ScalableBitmap m_bitmap_ams_rfid_3
ScalableBitmap m_bitmap_ams_rfid_4
ScalableBitmap m_bitmap_ams_rfid_5
ScalableBitmap m_bitmap_ams_rfid_6
ScalableBitmap m_bitmap_ams_rfid_7
std::vector< ScalableBitmap > m_rfid_bitmap_list
wxString m_refresh_id
wxBoxSizer * m_size_body
Detailed Description
Constructor & Destructor Documentation
AMSrefresh() [1/3]
Slic3r::GUI::AMSrefresh::AMSrefresh ()
{ SetFont(Label::Body_10);}
References Label::Body_10.
AMSrefresh() [2/3]
Slic3r::GUI::AMSrefresh::AMSrefresh (wxWindow * parent, wxWindowID id, wxString number, Caninfo info, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
                                                                                                                             : AMSrefresh()
{
    m_info = info;
    m_can_id = number.ToStdString();
    create(parent, id, pos, size);
}
References create(), m_can_id, m_info, and size.
AMSrefresh() [3/3]
Slic3r::GUI::AMSrefresh::AMSrefresh (wxWindow * parent, wxWindowID id, int number, Caninfo info, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
                                                                                                                        : AMSrefresh()
{
    m_info = info;
    m_can_id = wxString::Format("%d", number).ToStdString();
    create(parent, id, pos, size);
}
References create(), m_can_id, m_info, and size.
~AMSrefresh()
Slic3r::GUI::AMSrefresh::~AMSrefresh ()
 {
     if (m_playing_timer) {
         m_playing_timer->Stop();
         delete m_playing_timer;
         m_playing_timer = nullptr;
     }
 }
References m_playing_timer.
Member Function Documentation
create()
void Slic3r::GUI::AMSrefresh::create (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size)
{
    wxWindow::Create(parent, id, pos, size, wxBORDER_NONE);
    SetBackgroundColour(AMS_CONTROL_DEF_BLOCK_BK_COLOUR);
    Bind(wxEVT_TIMER, &AMSrefresh::on_timer, this);
    Bind(wxEVT_PAINT, &AMSrefresh::paintEvent, this);
    Bind(wxEVT_ENTER_WINDOW, &AMSrefresh::OnEnterWindow, this);
    Bind(wxEVT_LEAVE_WINDOW, &AMSrefresh::OnLeaveWindow, this);
    Bind(wxEVT_LEFT_DOWN, &AMSrefresh::OnClick, this);
    m_bitmap_normal   = ScalableBitmap(this, "ams_refresh_normal", 30);
    m_bitmap_selected = ScalableBitmap(this, "ams_refresh_selected", 30);
    m_bitmap_ams_rfid_0 = ScalableBitmap(this, "ams_rfid_0", 30);
    m_bitmap_ams_rfid_1 = ScalableBitmap(this, "ams_rfid_1", 30);
    m_bitmap_ams_rfid_2 = ScalableBitmap(this, "ams_rfid_2", 30);
    m_bitmap_ams_rfid_3 = ScalableBitmap(this, "ams_rfid_3", 30);
    m_bitmap_ams_rfid_4 = ScalableBitmap(this, "ams_rfid_4", 30);
    m_bitmap_ams_rfid_5 = ScalableBitmap(this, "ams_rfid_5", 30);
    m_bitmap_ams_rfid_6 = ScalableBitmap(this, "ams_rfid_6", 30);
    m_bitmap_ams_rfid_7 = ScalableBitmap(this, "ams_rfid_7", 30);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_0);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_1);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_2);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_3);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_4);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_5);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_6);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_7);
    m_playing_timer = new wxTimer();
    m_playing_timer->SetOwner(this);
    wxPostEvent(this, wxTimerEvent());
    SetSize(AMS_REFRESH_SIZE);
    SetMinSize(AMS_REFRESH_SIZE);
    SetMaxSize(AMS_REFRESH_SIZE);
}
References AMS_CONTROL_DEF_BLOCK_BK_COLOUR, AMS_REFRESH_SIZE, m_bitmap_ams_rfid_0, m_bitmap_ams_rfid_1, m_bitmap_ams_rfid_2, m_bitmap_ams_rfid_3, m_bitmap_ams_rfid_4, m_bitmap_ams_rfid_5, m_bitmap_ams_rfid_6, m_bitmap_ams_rfid_7, m_bitmap_normal, m_bitmap_selected, m_playing_timer, m_rfid_bitmap_list, on_timer(), OnClick(), OnEnterWindow(), OnLeaveWindow(), paintEvent(), and size.
Referenced by AMSrefresh(), and AMSrefresh().
DoSetSize()
void Slic3r::GUI::AMSrefresh::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) protected virtual
{
    wxWindow::DoSetSize(x, y, width, height, sizeFlags);
}
msw_rescale()
void Slic3r::GUI::AMSrefresh::msw_rescale ()
{
    m_bitmap_normal     = ScalableBitmap(this, "ams_refresh_normal", 30);
    m_bitmap_selected   = ScalableBitmap(this, "ams_refresh_selected", 30);
    m_bitmap_ams_rfid_0 = ScalableBitmap(this, "ams_rfid_0", 30);
    m_bitmap_ams_rfid_1 = ScalableBitmap(this, "ams_rfid_1", 30);
    m_bitmap_ams_rfid_2 = ScalableBitmap(this, "ams_rfid_2", 30);
    m_bitmap_ams_rfid_3 = ScalableBitmap(this, "ams_rfid_3", 30);
    m_bitmap_ams_rfid_4 = ScalableBitmap(this, "ams_rfid_4", 30);
    m_bitmap_ams_rfid_5 = ScalableBitmap(this, "ams_rfid_5", 30);
    m_bitmap_ams_rfid_6 = ScalableBitmap(this, "ams_rfid_6", 30);
    m_bitmap_ams_rfid_7 = ScalableBitmap(this, "ams_rfid_7", 30);
    m_rfid_bitmap_list.clear();
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_0);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_1);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_2);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_3);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_4);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_5);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_6);
    m_rfid_bitmap_list.push_back(m_bitmap_ams_rfid_7);
}
References m_bitmap_ams_rfid_0, m_bitmap_ams_rfid_1, m_bitmap_ams_rfid_2, m_bitmap_ams_rfid_3, m_bitmap_ams_rfid_4, m_bitmap_ams_rfid_5, m_bitmap_ams_rfid_6, m_bitmap_ams_rfid_7, m_bitmap_normal, m_bitmap_selected, and m_rfid_bitmap_list.
Referenced by Slic3r::GUI::AmsCans::msw_rescale().
on_timer()
void Slic3r::GUI::AMSrefresh::on_timer (wxTimerEvent & event)
{
    //if (m_rotation_angle >= m_rfid_bitmap_list.size()) {
    //    m_rotation_angle = 0;
    //} else {
    //    m_rotation_angle++;
    //}
    Refresh();
}
Referenced by create().
OnClick()
void Slic3r::GUI::AMSrefresh::OnClick (wxMouseEvent & evt)
{
    post_event(wxCommandEvent(EVT_AMS_REFRESH_RFID));
}
References post_event().
Referenced by create().
OnEnterWindow()
void Slic3r::GUI::AMSrefresh::OnEnterWindow (wxMouseEvent & evt)
{
    m_selected = true;
    Refresh();
}
References m_selected.
Referenced by create().
OnLeaveWindow()
void Slic3r::GUI::AMSrefresh::OnLeaveWindow (wxMouseEvent & evt)
{
    m_selected = false;
    Refresh();
}
References m_selected.
Referenced by create().
paintEvent()
void Slic3r::GUI::AMSrefresh::paintEvent (wxPaintEvent & evt)
{
    wxSize    size = GetSize();
    wxPaintDC dc(this);
    auto colour = StateColor::darkModeColorFor(AMS_CONTROL_GRAY700);
    if (!wxWindow::IsEnabled()) { colour = AMS_CONTROL_GRAY500; }
    auto pot = wxPoint((size.x - m_bitmap_selected.GetBmpSize().x) / 2, (size.y - m_bitmap_selected.GetBmpSize().y) / 2);
    if (!m_play_loading) {
        dc.DrawBitmap(m_selected ? m_bitmap_selected.bmp() : m_bitmap_normal.bmp(), pot);
    } else {
        /* m_bitmap_rotation    = ScalableBitmap(this, "ams_refresh_normal", 30);
         auto           image = m_bitmap_rotation.bmp().ConvertToImage();
         wxPoint        offset;
         auto           loading_img = image.Rotate(m_rotation_angle, wxPoint(image.GetWidth() / 2, image.GetHeight() / 2), true, &offset);
         ScalableBitmap loading_bitmap;
         loading_bitmap.bmp() = wxBitmap(loading_img);
         dc.DrawBitmap(loading_bitmap.bmp(), offset.x , offset.y);*/
        m_rotation_angle++;
        if (m_rotation_angle >= m_rfid_bitmap_list.size()) {
            m_rotation_angle = 0;
        }
        if (m_rfid_bitmap_list.size() <= 0)return;
        dc.DrawBitmap(m_rfid_bitmap_list[m_rotation_angle].bmp(), pot);
    }
    dc.SetPen(wxPen(colour));
    dc.SetBrush(wxBrush(colour));
    dc.SetFont(Label::Body_11);
    dc.SetTextForeground(colour);
    auto tsize = dc.GetTextExtent(m_refresh_id);
    pot        = wxPoint((size.x - tsize.x) / 2, (size.y - tsize.y) / 2);
    dc.DrawText(m_refresh_id, pot);
}
References AMS_CONTROL_GRAY500, AMS_CONTROL_GRAY700, ScalableBitmap::bmp(), Label::Body_11, StateColor::darkModeColorFor(), ScalableBitmap::GetBmpSize(), m_bitmap_normal, m_bitmap_selected, m_play_loading, m_refresh_id, m_rfid_bitmap_list, m_rotation_angle, m_selected, and size.
Referenced by create().
PlayLoading()
void Slic3r::GUI::AMSrefresh::PlayLoading ()
{
    if (m_play_loading)  return;
    m_play_loading = true;
    //m_rotation_angle = 0;
    m_playing_timer->Start(AMS_REFRESH_PLAY_LOADING_TIMER);
    Refresh();
}
References AMS_REFRESH_PLAY_LOADING_TIMER, m_play_loading, and m_playing_timer.
Referenced by Slic3r::GUI::AmsCans::PlayRridLoading().
post_event()
void Slic3r::GUI::AMSrefresh::post_event (wxCommandEvent && event)
{
    event.SetString(m_info.can_id);
    event.SetEventObject(m_parent);
    wxPostEvent(m_parent, event);
    event.Skip();
}
References Slic3r::GUI::Caninfo::can_id, and m_info.
Referenced by OnClick().
StopLoading()
void Slic3r::GUI::AMSrefresh::StopLoading ()
{
    if (!m_play_loading) return;
    m_playing_timer->Stop();
    m_play_loading = false;
    Refresh();
}
References m_play_loading, and m_playing_timer.
Referenced by Slic3r::GUI::AmsCans::StopRridLoading(), and Update().
Update()
void Slic3r::GUI::AMSrefresh::Update (std::string ams_id, Caninfo info)
{
    m_ams_id = ams_id;
    m_info   = info;
    if (!m_ams_id.empty() && !m_can_id.empty()) {
        auto aid = atoi(m_ams_id.c_str());
        auto tid = atoi(m_can_id.c_str());
        auto tray_id = aid * 4 + tid;
        m_refresh_id = wxGetApp().transition_tridid(tray_id);
    }
    StopLoading();
}
References m_ams_id, m_can_id, m_info, m_refresh_id, and StopLoading().
Referenced by Slic3r::GUI::AmsCans::Update().
Member Data Documentation
m_ams_id
std::string Slic3r::GUI::AMSrefresh::m_ams_id protected
Referenced by Update().
m_bitmap_ams_rfid_0
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_ams_rfid_0 protected
Referenced by create(), and msw_rescale().
m_bitmap_ams_rfid_1
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_ams_rfid_1 protected
Referenced by create(), and msw_rescale().
m_bitmap_ams_rfid_2
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_ams_rfid_2 protected
Referenced by create(), and msw_rescale().
m_bitmap_ams_rfid_3
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_ams_rfid_3 protected
Referenced by create(), and msw_rescale().
m_bitmap_ams_rfid_4
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_ams_rfid_4 protected
Referenced by create(), and msw_rescale().
m_bitmap_ams_rfid_5
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_ams_rfid_5 protected
Referenced by create(), and msw_rescale().
m_bitmap_ams_rfid_6
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_ams_rfid_6 protected
Referenced by create(), and msw_rescale().
m_bitmap_ams_rfid_7
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_ams_rfid_7 protected
Referenced by create(), and msw_rescale().
m_bitmap_normal
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_normal protected
Referenced by create(), msw_rescale(), and paintEvent().
m_bitmap_selected
ScalableBitmap Slic3r::GUI::AMSrefresh::m_bitmap_selected protected
Referenced by create(), msw_rescale(), and paintEvent().
m_can_id
std::string Slic3r::GUI::AMSrefresh::m_can_id protected
Referenced by AMSrefresh(), AMSrefresh(), and Update().
m_info
Caninfo Slic3r::GUI::AMSrefresh::m_info
Referenced by AMSrefresh(), AMSrefresh(), Slic3r::GUI::AmsCans::PlayRridLoading(), post_event(), Slic3r::GUI::AmsCans::StopRridLoading(), and Update().
m_play_loading
bool Slic3r::GUI::AMSrefresh::m_play_loading = {false} protected
Referenced by paintEvent(), PlayLoading(), and StopLoading().
m_playing_timer
wxTimer* Slic3r::GUI::AMSrefresh::m_playing_timer = {nullptr} protected
Referenced by ~AMSrefresh(), create(), PlayLoading(), and StopLoading().
m_refresh_id
wxString Slic3r::GUI::AMSrefresh::m_refresh_id protected
Referenced by paintEvent(), and Update().
m_rfid_bitmap_list
std::vector<ScalableBitmap> Slic3r::GUI::AMSrefresh::m_rfid_bitmap_list protected
Referenced by create(), msw_rescale(), and paintEvent().
m_rotation_angle
int Slic3r::GUI::AMSrefresh::m_rotation_angle = 0 protected
Referenced by paintEvent().
m_selected
bool Slic3r::GUI::AMSrefresh::m_selected = {false} protected
Referenced by OnEnterWindow(), OnLeaveWindow(), and paintEvent().
m_size_body
wxBoxSizer* Slic3r::GUI::AMSrefresh::m_size_body protected
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AMSControl.hpp
src/slic3r/GUI/Widgets/AMSControl.cpp