OrcaSlicer: vec3_< T > Class Template Reference
vec3_< T > Class Template Reference
#include <src/mcut/include/mcut/internal/math.h>
Public Types
typedef T element_type
Public Member Functions
vec3_ ()
vec3_ (const T &value)
vec3_ (const T &x, const T &y, const T &z)
~vec3_ ()
const T & operator[] (int index) const
T & operator[] (int index)
vec3_ operator- (const vec3_ &other) const
vec3_ operator+ (const vec3_ &other) const
const vec3_ operator/ (const T &number) const
const vec3_ operator* (const T &number) const
const T & z () const
bool operator== (const vec2_< T > &other) const
const vec2_ operator- (const vec2_ &other) const
const vec2_ operator+ (const vec2_ &other) const
const T & x () const
T & x ()
const T & y () const
T & y ()
Static Public Member Functions
static int cardinality ()
static vec2_ make (const T x, const T y)
Protected Attributes
T m_z
T m_x
T m_y
Detailed Description
template<typename T = double>
class vec3_< T >
Member Typedef Documentation
element_type
template<typename T = double> typedef T vec2_< T >::element_type inherited
Constructor & Destructor Documentation
vec3_() [1/3]
template<typename T = double> vec3_< T >::vec3_ () inline
        : vec2_<T>(0.0, 0.0)
        , m_z(0.0)
    {
    }
Referenced by vec3_< T >::operator*(), vec3_< T >::operator+(), vec3_< T >::operator-(), and vec3_< T >::operator/().
vec3_() [2/3]
template<typename T = double> vec3_< T >::vec3_ (const T & value) inline
        : vec2_<T>(value, value)
        , m_z(value)
    {
    }
vec3_() [3/3]
template<typename T = double> vec3_< T >::vec3_ (const T & x, const T & y, const T & z) inline
        : vec2_<T>(x, y)
        , m_z(z)
    {
    }
~vec3_()
template<typename T = double> vec3_< T >::~vec3_ () inline
    {
    }
Member Function Documentation
cardinality()
template<typename T = double> static int vec3_< T >::cardinality () inline static
    {
        return 3;
    }
Referenced by matrix_t< T >::operator*().
make()
template<typename T = double> static vec2_ vec2_< T >::make (const T x, const T y) inline static inherited
    {
        return vec2_<T>(x, y);
    }
References vec2_< T >::x(), and vec2_< T >::y().
Referenced by cdt::detail::get_intersection_point_coords(), and cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initialize().
operator*()
template<typename T = double> const vec3_ vec3_< T >::operator* (const T & number) const inline
    {
        return vec3_(this->m_x * number, this->m_y * number, this->m_z * number);
    }
References vec3_< T >::vec3_(), vec2_< T >::m_x, vec2_< T >::m_y, and vec3_< T >::m_z.
operator+() [1/2]
template<typename T = double> const vec2_ vec2_< T >::operator+ (const vec2_< T > & other) const inline inherited
    {
        return vec2_(m_x + other.m_x, m_y + other.m_y);
    }
References vec2_< T >::vec2_(), vec2_< T >::m_x, and vec2_< T >::m_y.
operator+() [2/2]
template<typename T = double> vec3_ vec3_< T >::operator+ (const vec3_< T > & other) const inline
    {
        return vec3_(this->m_x + other.m_x, this->m_y + other.m_y, this->m_z + other.m_z);
    }
References vec3_< T >::vec3_(), vec2_< T >::m_x, vec2_< T >::m_y, and vec3_< T >::m_z.
operator-() [1/2]
template<typename T = double> const vec2_ vec2_< T >::operator- (const vec2_< T > & other) const inline inherited
    {
        return vec2_(m_x - other.m_x, m_y - other.m_y);
    }
References vec2_< T >::vec2_(), vec2_< T >::m_x, and vec2_< T >::m_y.
operator-() [2/2]
template<typename T = double> vec3_ vec3_< T >::operator- (const vec3_< T > & other) const inline
    {
        return vec3_(this->m_x - other.m_x, this->m_y - other.m_y, this->m_z - other.m_z);
    }
References vec3_< T >::vec3_(), vec2_< T >::m_x, vec2_< T >::m_y, and vec3_< T >::m_z.
operator/()
template<typename T = double> const vec3_ vec3_< T >::operator/ (const T & number) const inline
    {
        return vec3_(this->m_x / number, this->m_y / number, this->m_z / number);
    }
References vec3_< T >::vec3_(), vec2_< T >::m_x, vec2_< T >::m_y, and vec3_< T >::m_z.
operator==()
template<typename T = double> bool vec2_< T >::operator== (const vec2_< T > & other) const inline inherited
    {
        return this->m_x == other.x() && this->m_y == other.y();
    }
References vec2_< T >::m_x, vec2_< T >::m_y, vec2_< T >::x(), and vec2_< T >::y().
operator[]() [1/2]
template<typename T = double> T & vec3_< T >::operator[] (int index) inline
    {
        MCUT_ASSERT(index >= 0 && index <= 2);
        if (index == 0) {
            return this->m_x;
        } else if (index == 1) {
            return this->m_y;
        } else {
            return this->m_z;
        }
    }
References vec2_< T >::m_x, vec2_< T >::m_y, vec3_< T >::m_z, and MCUT_ASSERT.
operator[]() [2/2]
template<typename T = double> const T & vec3_< T >::operator[] (int index) const inline
    {
        MCUT_ASSERT(index >= 0 && index <= 2);
        if (index == 0) {
            return this->m_x;
        } else if (index == 1) {
            return this->m_y;
        } else {
            return this->m_z;
        }
    }
References vec2_< T >::m_x, vec2_< T >::m_y, vec3_< T >::m_z, and MCUT_ASSERT.
x() [1/2]
template<typename T = double> T & vec2_< T >::x () inline inherited
    {
        return m_x;
    }
References vec2_< T >::m_x.
x() [2/2]
template<typename T = double> const T & vec2_< T >::x () const inline inherited
    {
        return m_x;
    }
References vec2_< T >::m_x.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::add_super_triangle(), hmesh_t::add_vertex(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo(), cdt::check_is_in_circumcircle(), compute_point_in_polygon_test(), Clipper2Lib::CrossProduct(), Clipper2Lib::DotProduct(), cdt::box2d_t< T >::expand_with_point(), cdt::box2d_t< T >::expand_with_point(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), cdt::get_x_coord_vec2d(), Clipper2Lib::GetAvgUnitVector(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), intersect_bounding_boxes(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::isInsideBox(), vec2_< T >::make(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest(), std::hash< vec2_< T > >::operator()(), operator<<(), cdt::operator==(), vec2_< T >::operator==(), orient2d(), orient3d(), point_in_bounding_box(), point_in_bounding_box(), resolve_floating_polygons(), triangulate_face(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::whichChild(), and write_off().
y() [1/2]
template<typename T = double> T & vec2_< T >::y () inline inherited
    {
        return m_y;
    }
References vec2_< T >::m_y.
y() [2/2]
template<typename T = double> const T & vec2_< T >::y () const inline inherited
    {
        return m_y;
    }
References vec2_< T >::m_y.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::add_super_triangle(), hmesh_t::add_vertex(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo(), cdt::check_is_in_circumcircle(), compute_point_in_polygon_test(), Clipper2Lib::CrossProduct(), Clipper2Lib::DotProduct(), cdt::box2d_t< T >::expand_with_point(), cdt::box2d_t< T >::expand_with_point(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), cdt::get_y_coord_vec2d(), Clipper2Lib::GetAvgUnitVector(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), intersect_bounding_boxes(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::isInsideBox(), vec2_< T >::make(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest(), std::hash< vec2_< T > >::operator()(), operator<<(), cdt::operator==(), vec2_< T >::operator==(), orient2d(), orient3d(), point_in_bounding_box(), point_in_bounding_box(), resolve_floating_polygons(), triangulate_face(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::whichChild(), and write_off().
z()
template<typename T = double> const T & vec3_< T >::z () const inline
    {
        return m_z;
    }
References vec3_< T >::m_z.
Referenced by hmesh_t::add_vertex(), intersect_bounding_boxes(), operator<<(), orient3d(), point_in_bounding_box(), and write_off().
Member Data Documentation
m_x
template<typename T = double> T vec2_< T >::m_x protected inherited
Referenced by vec2_< T >::operator*(), vec3_< T >::operator*(), vec2_< T >::operator+(), vec3_< T >::operator+(), vec2_< T >::operator-(), vec3_< T >::operator-(), vec2_< T >::operator/(), vec3_< T >::operator/(), vec2_< T >::operator==(), vec2_< T >::operator[](), vec3_< T >::operator[](), vec2_< T >::operator[](), vec3_< T >::operator[](), vec2_< T >::x(), and vec2_< T >::x().
m_y
template<typename T = double> T vec2_< T >::m_y protected inherited
Referenced by vec2_< T >::operator*(), vec3_< T >::operator*(), vec2_< T >::operator+(), vec3_< T >::operator+(), vec2_< T >::operator-(), vec3_< T >::operator-(), vec2_< T >::operator/(), vec3_< T >::operator/(), vec2_< T >::operator==(), vec2_< T >::operator[](), vec3_< T >::operator[](), vec2_< T >::operator[](), vec3_< T >::operator[](), vec2_< T >::y(), and vec2_< T >::y().
m_z
template<typename T = double> T vec3_< T >::m_z protected
Referenced by vec3_< T >::operator*(), vec3_< T >::operator+(), vec3_< T >::operator-(), vec3_< T >::operator/(), vec3_< T >::operator[](), vec3_< T >::operator[](), and vec3_< T >::z().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/math.h