OrcaSlicer: src/mcut/include/mcut/internal/math.h File Reference
math.h File Reference
#include <cmath>
#include <iostream>
#include <limits>
#include <memory>
#include <vector>
#include "mcut/internal/utils.h"
Classes
class vec2_< T >
class vec3_< T >
class matrix_t< T >
struct bounding_box_t< vector_type >
Typedefs
typedef vec2_ vec2
typedef vec3_ vec3
Enumerations
enum sign_t {
ON_NEGATIVE_SIDE = -1 , ON_ORIENTED_BOUNDARY = 0 , ON_POSITIVE_SIDE = 1 , NEGATIVE = ON_NEGATIVE_SIDE ,
ZERO = ON_ORIENTED_BOUNDARY , POSITIVE = ON_POSITIVE_SIDE
}
Functions
double square_root (const double &number)
double absolute_value (const double &number)
sign_t sign (const double &number)
std::ostream & operator<< (std::ostream &os, const vec3 &v)
template<typename U >
std::ostream & operator<< (std::ostream &os, const matrix_t< U > &m)
template<typename T >
const T & min (const T &a, const T &b)
template<typename T >
const T & max (const T &a, const T &b)
bool operator== (const vec3 &a, const vec3 &b)
template<typename T >
vec2_< T > compwise_min (const vec2_< T > &a, const vec2_< T > &b)
template<typename T >
vec2_< T > compwise_max (const vec2_< T > &a, const vec2_< T > &b)
template<typename T >
vec3_< T > compwise_min (const vec3_< T > &a, const vec3_< T > &b)
template<typename T >
vec3_< T > compwise_max (const vec3_< T > &a, const vec3_< T > &b)
vec3 cross_product (const vec3 &a, const vec3 &b)
template<typename vector_type >
double dot_product (const vector_type &a, const vector_type &b)
template<typename vector_type >
matrix_t< typename vector_type::element_type > outer_product (const vector_type &a, const vector_type &b)
template<typename vector_type >
double squared_length (const vector_type &v)
template<typename vector_type >
double length (const vector_type &v)
template<typename vector_type >
vector_type normalize (const vector_type &v)
double orient2d (const vec2 &pa, const vec2 &pb, const vec2 &pc)
double orient3d (const vec3 &pa, const vec3 &pb, const vec3 &pc, const vec3 &pd)
int compute_polygon_plane_coefficients (vec3 &normal, double &d_coeff, const vec3 *polygon_vertices, const int polygon_vertex_count)
char compute_line_plane_intersection (vec3 &p, const vec3 &q, const vec3 &r, const vec3 *polygon_vertices, const int polygon_vertex_count, const int polygon_normal_max_comp, const vec3 &polygon_plane_normal)
char compute_segment_plane_intersection (vec3 &p, const vec3 &normal, const double &d_coeff, const vec3 &q, const vec3 &r)
char compute_segment_plane_intersection_type (const vec3 &q, const vec3 &r, const std::vector< vec3 > &polygon_vertices, const vec3 &polygon_normal, const int polygon_normal_largest_component)
char compute_point_in_polygon_test (const vec2 &q, const std::vector< vec2 > &polygon_vertices)
char compute_point_in_polygon_test (const vec3 &p, const std::vector< vec3 > &polygon_vertices, const vec3 &polygon_normal, const int polygon_normal_largest_component)
void project_to_2d (std::vector< vec2 > &out, const std::vector< vec3 > &polygon_vertices, const vec3 &polygon_normal, const int polygon_normal_largest_component)
void project_to_2d (std::vector< vec2 > &out, const std::vector< vec3 > &polygon_vertices, const vec3 &polygon_normal)
bool coplaner (const vec3 &pa, const vec3 &pb, const vec3 &pc, const vec3 &pd)
bool collinear (const vec2 &a, const vec2 &b, const vec2 &c, double &predResult)
bool collinear (const vec2 &a, const vec2 &b, const vec2 &c)
char compute_segment_intersection (const vec2 &a, const vec2 &b, const vec2 &c, const vec2 &d, vec2 &p, double &s, double &t)
template<typename T >
bool intersect_bounding_boxes (const bounding_box_t< vec3_< T > > &a, const bounding_box_t< vec3_< T > > &b)
bool point_in_bounding_box (const vec2 &point, const bounding_box_t< vec2 > &bbox)
bool point_in_bounding_box (const vec3 &point, const bounding_box_t< vec3 > &bbox)
template<typename vector_type >
void make_bbox (bounding_box_t< vector_type > &bbox, const vector_type *vertices, const int num_vertices)
double orient2d (const double *pa, const double *pb, const double *pc)
double orient3d (const double *pa, const double *pb, const double *pc, const double *pd)
double orient3dfast (const double *pa, const double *pb, const double *pc, const double *pd)
double incircle (const double *pa, const double *pb, const double *pc, const double *pd)
double insphere (const double *pa, const double *pb, const double *pc, const double *pd, const double *pe)
Typedef Documentation
vec2
typedef vec2_ vec2
vec3
typedef vec3_ vec3
Enumeration Type Documentation
sign_t
enum sign_t
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
Enumerator
ON_NEGATIVE_SIDE
ON_ORIENTED_BOUNDARY
ON_POSITIVE_SIDE
NEGATIVE
ZERO
POSITIVE
            {
    ON_NEGATIVE_SIDE = -1, // left
    ON_ORIENTED_BOUNDARY = 0, // on boundary
    ON_POSITIVE_SIDE = 1, // right
    //
    NEGATIVE = ON_NEGATIVE_SIDE,
    ZERO = ON_ORIENTED_BOUNDARY,
    POSITIVE = ON_POSITIVE_SIDE,
};
Function Documentation
absolute_value()
double absolute_value (const double & number)
    {
#if !defined(MCUT_WITH_ARBITRARY_PRECISION_NUMBERS)
        return std::fabs(number);
#else
        double out(number);
        mpfr_abs(out.get_mpfr_handle(), number.get_mpfr_handle(), arbitrary_precision_number_t::get_default_rounding_mode());
        return out;
#endif // #if defined(MCUT_WITH_ARBITRARY_PRECISION_NUMBERS)
    }
References out.
Referenced by compute_polygon_plane_coefficients(), and coplaner().
collinear() [1/2]
bool collinear (const vec2 & a, const vec2 & b, const vec2 & c)
    {
        return orient2d(a, b, c) == double(0.);
    }
References orient2d().
collinear() [2/2]
bool collinear (const vec2 & a, const vec2 & b, const vec2 & c, double & predResult)
    {
        predResult = orient2d(a, b, c);
        return predResult == double(0.);
    }
References orient2d().
Referenced by determine_three_noncollinear_vertices(), Parallellnt(), and resolve_floating_polygons().
compute_line_plane_intersection()
char compute_line_plane_intersection (vec3 & p, const vec3 & q, const vec3 & r, const vec3 * polygon_vertices, const int polygon_vertex_count, const int polygon_normal_max_comp, const vec3 & polygon_plane_normal)
Referenced by dispatch().
compute_point_in_polygon_test() [1/2]
char compute_point_in_polygon_test (const vec2 & q, const std::vector< vec2 > & polygon_vertices)
    {
        const int polygon_vertex_count = (int)polygon_vertices.size();
#if 0 // Algorithm 1 in :
      // https://pdf.sciencedirectassets.com/271512/1-s2.0-S0925772100X00545/1-s2.0-S0925772101000128/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjEAEaCXVzLWVhc3QtMSJHMEUCIBr6Fu%2F%2FtscErn%2Fl4pn2UGNA45sAw9vggQscK7Tnl0ssAiEAzfnyy4B4%2BXkZp8xcEk7utDBrxgmGyH7pyqk0efKOUEoq%2BgMIKhAEGgwwNTkwMDM1NDY4NjUiDHQT4kOfk4%2B6kBB0xCrXAzd8SWlnELJbM5l93HSvv4nUgtO85%2FGyx5%2BOoHmYoUuVwJjCXChmLJmlz%2BxYUQE%2Fr8vQa2hPlUEPfiTVGgoHaK8NkSMP6LRs%2F3WjyZ9OxzHbqSwZixNceW34OAkq0E1QgYLdGVjpPKxNK1haXDfBTMN6bF2IOU9dKi9wTv3uTlep0kHDa1BNNl6M6yZk5QlF2bPF9XmNjjZCpFQLhr%2BPoHo%2Bx4xy39aH8hCkkTqGdy2KrKGN6lv0%2FduIaItyZfqalYS%2BwW6cll2F5G11g0tSu7yKu6mug94LUTzsRmzD0UhzeGl2WV6Ev2qhw26mwFEKgnTMqGst8XAHjFjjAQyMzXNHCQqNBRIevHIzVWuUY4QZMylSRsodo0dfwwCFhzl0%2BJA1ZXb0%2BoyB8c11meQBO8FpMSshngNcbiAYUtIOFcHNCTCUMk0JPOZ%2FxvANsopnivbrPARL71zU4PaTujg5jfC2zoO6ZDUL8E6Vn%2BNtfb%2BuQV7DwtIH51Bv%2F%2F1m6h5mjbpRiGYcH%2F5SDD%2Fk%2BpHfKRQzKu7jJc%2B0XO0bQvoLSrAte0Qk10PwOvDl5jMIMdmxTBDDiDGErRykYxMQhq5EwjyiWPXzM3ll9uK59Vy0bAEj5Qemj5by1jCDht6IBjqlAV4okAPQO5wWdWojCYeKvluKfXCvudrUxrLhsxb7%2BTZNMODTG%2Fn%2Fbw875Yr6fOQ42u40pOsnPB%2FTP3cWwjiB%2BEHzDqN8AhCVQyoedw7QrU3OBWlSl6lB%2BGLAVqrhcizgFUiM2nj3HaVP2m7S%2FXqpv%2FoWlEXt4gR8iI9XsIlh6L6SBE22FqbsU5ewCxXaqip19VXhAGnlvjTihXUg6yZGWhExHj%2BKcA%3D%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210814T103958Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTY3PPQSW2L%2F20210814%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=94403dce5c12ede9507e9612c000db5772607e59a2134d30d4e5b44212056dc7&hash=cada083b165f9786e6042e21d3d22147ec08b1e2c8fa2572ceeb2445cb5e730a&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S0925772101000128&tid=spdf-f9e7c4b7-808d-4a8e-a474-6430ff687798&sid=8dddff5b32fff2499908bf6501965aec3d0fgxrqb&type=client
            const double zero(0.0);
            int i = 0;
            int k = 0;
            double f = zero;
            double u1 = 0.0;
            double v1 = 0.0;
            double u2 = 0.0;
            double v2 = 0.0;
            const int n = polygon_vertex_count;
            for (i = 0; i < n; ++i)
            {
                v1 = polygon_vertices[i].y() - q.y();
                v2 = polygon_vertices[(i + 1) % n].y() - q.y();
                if ((v1 < zero && v2 < zero) || (v1 > zero && v2 > zero))
                {
                    continue;
                }
                u1 = polygon_vertices[i].x() - q.x();
                u2 = polygon_vertices[(i + 1) % n].x() - q.x();
                if (v2 > zero && v1 <= zero)
                {
                    f = u1 * v2 - u2 * v1;
                    if (f > zero)
                    {
                        k = k + 1;
                    }
                    else if (f == zero)
                    {
                        return 'e'; //-1; // boundary
                    }
                }
                else if (v1 > zero && v2 <= zero)
                {
                    f = u1 * v2 - u2 * v1;
                    if (f < zero)
                    {
                        k = k + 1;
                    }
                    else if (f == zero)
                    {
                        return 'e'; //-1; // boundary
                    }
                }
                else if (v2 == zero && v1 < zero)
                {
                    f = u1 * v2 - u2 * v1;
                    if (f == zero)
                    {
                        return 'e'; //-1; // // boundary
                    }
                }
                else if (v1 == zero && v2 < zero)
                {
                    f = u1 * v2 - u2 * v1;
                    if (f == zero)
                    {
                        return 'e'; //-1; // boundary
                    }
                }
                else if (v1 == zero && v2 == zero)
                {
                    if (u2 <= zero && u1 >= zero)
                    {
                        return 'e'; //-1; // boundary
                    }
                    else if (u1 <= zero && u2 >= zero)
                    {
                        return 'e'; //-1; // boundary
                    }
                }
            }
            if (k % 2 == 0)
            {
                return 'o'; //0; // outside
            }
            else
            {
                return 'i'; //1; // inside
            }
#else // http://www.science.smith.edu/~jorourke/books/compgeom.html
        std::vector<vec2> vertices(polygon_vertex_count, vec2());
        // Shift so that q is the origin. Note this destroys the polygon.
        // This is done for pedagogical clarity.
        for (int i = 0; i < polygon_vertex_count; i++) {
            for (int d = 0; d < 2; d++) {
                const double& a = polygon_vertices[i][d];
                const double& b = q[d];
                double& c = vertices[i][d];
                c = a - b;
            }
        }
        int Rcross = 0; /* number of right edge/ray crossings */
        int Lcross = 0; /* number ofleft edge/ray crossings */
        /* For each edge e = (ilj), see if crosses ray. */
        for (int i = 0; i < polygon_vertex_count; i++) {
            /* First check if q = (0, 0) is a vertex. */
            if (vertices[i].x() == double(0.) && vertices[i].y() == double(0.)) {
                return 'v';
            }
            int il = (i + polygon_vertex_count - 1) % polygon_vertex_count;
            // Check if e straddles x axis, with bias above/below.
            // Rstrad is TRUE iff one endpoint of e is strictly above the x axis and the other is not (i.e., the other is on
            // or below)
            bool Rstrad = (vertices[i].y() > double(0.)) != (vertices[il].y() > double(0.));
            bool Lstrad = (vertices[i].y() < double(0.)) != (vertices[il].y() < double(0.));
            if (Rstrad || Lstrad) {
                /* Compute intersection of e with x axis. */
                // The computation of x is needed whenever either of these straddle variables is TRUE, which
                // only excludes edges passing through q = (0, 0) (and incidentally protects against division by 0).
                double x = (vertices[i].x() * vertices[il].y() - vertices[il].x() * vertices[i].y()) / (vertices[il].y() - vertices[i].y());
                if (Rstrad && x > double(0.)) {
                    Rcross++;
                }
                if (Lstrad && x < double(0.)) {
                    Lcross++;
                }
            } /* end straddle computation*/
        } // end for
        /* q on an edge if L/Rcross counts are not the same parity.*/
        if ((Rcross % 2) != (Lcross % 2)) {
            return 'e';
        }
        /* q inside iff an odd number of crossings. */
        if ((Rcross % 2) == 1) {
            return 'i';
        } else {
            return 'o';
        }
#endif
    }
References int, n, vec2_< T >::x(), and vec2_< T >::y().
Referenced by compute_point_in_polygon_test(), dispatch(), and resolve_floating_polygons().
compute_point_in_polygon_test() [2/2]
char compute_point_in_polygon_test (const vec3 & p, const std::vector< vec3 > & polygon_vertices, const vec3 & polygon_normal, const int polygon_normal_largest_component)
    {
        const int polygon_vertex_count = (int)polygon_vertices.size();
        /* Project out coordinate m in both p and the triangular face */
        vec2 pp; /*projected p */
#if 0
    int k = 0;
    for (int j = 0; j < 3; j++)
    { // for each component
        if (j != polygon_plane_normal_largest_component)
        { /* skip largest coordinate */
            pp[k] = p[j];
            k++;
        }
    }
#endif
        const matrix_t<double> P = calculate_projection_matrix(polygon_normal, polygon_normal_largest_component);
        pp = P * p;
        std::vector<vec2> polygon_vertices2d(polygon_vertex_count, vec2());
        for (int i = 0; i < polygon_vertex_count; ++i) { // for each vertex
            const vec3& x = polygon_vertices[i];
            polygon_vertices2d[i] = P * x; // vertex in xz plane
        }
#if 0
    for (int i = 0; i < polygon_vertex_count; ++i)
    { // for each vertex
        vec2 &Tp = polygon_vertices2d[i];
        k = 0;
        for (int j = 0; j < 3; j++)
        { // for each component
            if (j != polygon_plane_normal_largest_component)
            { /* skip largest coordinate */
                Tp[k] = polygon_vertices[i][j];
                k++;
            }
        }
    }
#endif
        return compute_point_in_polygon_test(pp, polygon_vertices2d);
    }
References calculate_projection_matrix(), compute_point_in_polygon_test(), and int.
compute_polygon_plane_coefficients()
int compute_polygon_plane_coefficients (vec3 & normal, double & d_coeff, const vec3 * polygon_vertices, const int polygon_vertex_count)
    {
        // compute polygon normal (http://cs.haifa.ac.il/~gordon/plane.pdf)
        normal = vec3(0.0);
        for (int i = 0; i < polygon_vertex_count - 1; ++i) {
            normal = normal + cross_product(polygon_vertices[i] - polygon_vertices[0], polygon_vertices[(i + 1) % polygon_vertex_count] - polygon_vertices[0]);
        }
        // In our calculations we need the normal be be of unit length so that the d-coeff
        // represents the distance of the plane from the origin
        // normal = normalize(normal);
        d_coeff = dot_product(polygon_vertices[0], normal);
        double largest_component(0.0);
        double tmp(0.0);
        int largest_component_idx = 0;
        for (int i = 0; i < 3; ++i) {
            tmp = absolute_value(normal[i]);
            if (tmp > largest_component) {
                largest_component = tmp;
                largest_component_idx = i;
            }
        }
        return largest_component_idx;
    }
References absolute_value(), cross_product(), and dot_product().
Referenced by dispatch(), and triangulate_face().
compute_segment_intersection()
char compute_segment_intersection (const vec2 & a, const vec2 & b, const vec2 & c, const vec2 & d, vec2 & p, double & s, double & t)
    {
        // double s, t; /* The two parameters of the parametric eqns. */
        double num, denom; /* Numerator and denominator of equations. */
        char code = '?'; /* Return char characterizing intersection.*/
        denom = a[0] * (d[1] - c[1]) + //
            b[0] * (c[1] - d[1]) + //
            d[0] * (b[1] - a[1]) + //
            c[0] * (a[1] - b[1]);
        /* If denom is zero, then segments are parallel: handle separately. */
        if (denom == double(0.0)) {
            return Parallellnt(a, b, c, d, p);
        }
        num = a[0] * (d[1] - c[1]) + //
            c[0] * (a[1] - d[1]) + //
            d[0] * (c[1] - a[1]);
        if ((num == double(0.0)) || (num == denom)) {
            code = 'v';
        }
        s = num / denom;
        num = -(a[0] * (c[1] - b[1]) + //
            b[0] * (a[1] - c[1]) + //
            c[0] * (b[1] - a[1]));
        if ((num == double(0.0)) || (num == denom)) {
            code = 'v';
        }
        t = num / denom;
        if ((double(0.0) < s) && (s < double(1.0)) && (double(0.0) < t) && (t < double(1.0))) {
            code = '1';
        } else if ((double(0.0) > s) || (s > double(1.0)) || (double(0.0) > t) || (t > double(1.0))) {
            code = '0';
        }
        p[0] = a[0] + s * (b[0] - a[0]);
        p[1] = a[1] + s * (b[1] - a[1]);
        return code;
    }
References Parallellnt().
Referenced by resolve_floating_polygons(), and triangulate_face().
compute_segment_plane_intersection()
char compute_segment_plane_intersection (vec3 & p, const vec3 & normal, const double & d_coeff, const vec3 & q, const vec3 & r)
    {
        // vec3 planeNormal;
        // double planeDCoeff;
        // planeNormalLargestComponent = compute_polygon_plane_coefficients(planeNormal, planeDCoeff, polygonVertices,
        // polygonVertexCount);
        double num = d_coeff - dot_product(q, normal);
        const vec3 rq = (r - q);
        double denom = dot_product(rq, normal);
        if (denom == double(0.0) /* Segment is parallel to plane.*/) {
            if (num == double(0.0)) { // 'q' is on plane.
                return 'p'; // The segment lies wholly within the plane
            } else {
                return '0';
            }
        }
        double t = num / denom;
        for (int i = 0; i < 3; ++i) {
            p[i] = q[i] + t * (r[i] - q[i]);
        }
        if ((double(0.0) < t) && (t < double(1.0))) {
            return '1'; // The segment intersects the plane, and none of {p, q, r} hold
        } else if (num == double(0.0)) // t==0
        {
            return 'q'; // The (first) q endpoint is on the plane (but not 'p').
        } else if (num == denom) // t==1
        {
            return 'r'; // The (second) r endpoint is on the plane (but not 'p').
        } else {
            return '0'; // The segment lies strictly to one side or the other of the plane
        }
    }
References dot_product().
Referenced by dispatch().
compute_segment_plane_intersection_type()
char compute_segment_plane_intersection_type (const vec3 & q, const vec3 & r, const std::vector< vec3 > & polygon_vertices, const vec3 & polygon_normal, const int polygon_normal_largest_component)
    {
        // TODO: we could also return i,j and k so that "determine_three_noncollinear_vertices" is not called multiple times,
        // which we do to determine the type of intersection and the actual intersection point
        const int polygon_vertex_count = (int)polygon_vertices.size();
        // ... any three vertices that are not collinear
        int i = 0;
        int j = 1;
        int k = 2;
        if (polygon_vertex_count > 3) { // case where we'd have the possibility of noncollinearity
            bool b = determine_three_noncollinear_vertices(i, j, k, polygon_vertices, polygon_normal,
                polygon_normal_largest_component);
            if (!b) {
                return '0'; // all polygon points are collinear
            }
        }
        double qRes = orient3d(polygon_vertices[i], polygon_vertices[j], polygon_vertices[k], q);
        double rRes = orient3d(polygon_vertices[i], polygon_vertices[j], polygon_vertices[k], r);
        if (qRes == double(0.0) && rRes == double(0.0)) {
            return 'p';
        } else if (qRes == double(0.0)) {
            return 'q';
        } else if (rRes == double(0.0)) {
            return 'r';
        } else if ((rRes < double(0.0) && qRes < double(0.0)) || (rRes > double(0.0) && qRes > double(0.0))) {
            return '0';
        } else {
            return '1';
        }
    }
References determine_three_noncollinear_vertices(), int, and orient3d().
Referenced by dispatch().
compwise_max() [1/2]
template<typename T > vec2_< T > compwise_max (const vec2_< T > & a, const vec2_< T > & b)
{
    return vec2_<T>(max(a.x(), b.x()), max(a.y(), b.y()));
}
References max().
Referenced by client_input_arrays_to_hmesh(), bounding_box_t< vector_type >::expand(), and bounding_box_t< vector_type >::expand().
compwise_max() [2/2]
template<typename T > vec3_< T > compwise_max (const vec3_< T > & a, const vec3_< T > & b)
{
    return vec3_<T>(max(a.x(), b.x()), max(a.y(), b.y()), max(a.z(), b.z()));
}
References max().
compwise_min() [1/2]
template<typename T > vec2_< T > compwise_min (const vec2_< T > & a, const vec2_< T > & b)
{
    return vec2_<T>(min(a.x(), b.x()), min(a.y(), b.y()));
}
References min().
Referenced by client_input_arrays_to_hmesh(), bounding_box_t< vector_type >::expand(), and bounding_box_t< vector_type >::expand().
compwise_min() [2/2]
template<typename T > vec3_< T > compwise_min (const vec3_< T > & a, const vec3_< T > & b)
{
    return vec3_<T>(min(a.x(), b.x()), min(a.y(), b.y()), min(a.z(), b.z()));
}
References min().
coplaner()
bool coplaner (const vec3 & pa, const vec3 & pb, const vec3 & pc, const vec3 & pd)
    {
        const double val = orient3d(pa, pb, pc, pd);
        // typedef std::numeric_limits<double> dbl;
        // double d = 3.14159265358979;
        // std::cout.precision(dbl::max_digits10);
        // std::cout << "value=" << (double)val << std::endl;
        // NOTE: thresholds are chosen based on benchmark meshes that are used for testing.
        // It is extremely difficult to get this right because of intermediate conversions
        // between exact and fixed precision representations during cutting.
        // Thus, general advise is for user to ensure that the input polygons are really
        // co-planer. It might be possible for MCUT to help here (see eps used during poly
        // partitioning).
        return absolute_value(val) <= double(4e-7);
    }
References absolute_value(), orient3d(), and pd.
Referenced by is_coplanar().
cross_product()
vec3 cross_product (const vec3 & a, const vec3 & b)
    {
        return vec3(
            a.y() * b.z() - a.z() * b.y(),
            a.z() * b.x() - a.x() * b.z(),
            a.x() * b.y() - a.y() * b.x());
    }
Referenced by compute_polygon_plane_coefficients(), generate_supertriangle_from_mesh_vertices(), and project_to_2d().
dot_product()
template<typename vector_type > double dot_product (const vector_type & a, const vector_type & b)
{
    double out(0.0);
    for (int i = 0; i < vector_type::cardinality(); ++i) {
        out += (a[i] * b[i]);
    }
    return out;
}
References out.
Referenced by calculate_projection_matrix(), compute_line_plane_intersection(), compute_polygon_plane_coefficients(), compute_segment_line_plane_intersection_type(), compute_segment_plane_intersection(), dispatch(), generate_supertriangle_from_mesh_vertices(), linear_projection_sort(), project_to_2d(), and squared_length().
incircle()
double incircle (const double * pa, const double * pb, const double * pc, const double * pd)
Referenced by igl::delaunay_triangulation().
insphere()
double insphere (const double * pa, const double * pb, const double * pc, const double * pd, const double * pe)
intersect_bounding_boxes()
template<typename T > bool intersect_bounding_boxes (const bounding_box_t< vec3_< T > > & a, const bounding_box_t< vec3_< T > > & b) inline
{
    const vec3_<T>& amin = a.minimum();
    const vec3_<T>& amax = a.maximum();
    const vec3_<T>& bmin = b.minimum();
    const vec3_<T>& bmax = b.maximum();
    return (amin.x() <= bmax.x() && amax.x() >= bmin.x()) && //
        (amin.y() <= bmax.y() && amax.y() >= bmin.y()) && //
        (amin.z() <= bmax.z() && amax.z() >= bmin.z());
}
References vec2_< T >::x(), vec2_< T >::y(), and vec3_< T >::z().
Referenced by dispatch().
length()
template<typename vector_type > double length (const vector_type & v)
{
    return square_root(squared_length(v));
}
References square_root(), and squared_length().
Referenced by textconv_helper::CA2W_::CA2W_(), textconv_helper::CW2A_::CW2A_(), Slic3r::OpenPolyline::OpenPolyline(), Slic3r::chain_open_polylines_close_gaps(), client_input_arrays_to_hmesh(), Eigen::BDCSVD< _MatrixType >::deflation(), internal::detect_super_cols(), dispatch(), igl::opengl::ViewerCore::draw(), Eigen::internal::SparseLUImpl< Scalar, StorageIndex >::expand(), fast_float::fastfloat_strncasecmp(), internal::find_ordering(), internal::garbage_collection(), generate_supertriangle_from_mesh_vertices(), get_connected_component_data_impl_detail(), get_scheduling_parameters(), igl::opengl::gliReadTGA(), nlohmann::detail::dtoa_impl::grisu2_digit_gen(), hid_get_feature_report(), hid_read(), hid_read_timeout(), hid_send_feature_report(), hid_write(), internal::init_rows_cols(), nlohmann::detail::input_adapter(), orgQhull::Coordinates::mid(), orgQhull::QhullPoints::mid(), normalize(), parallel_find(), parallel_find_if(), parallel_find_in_map_by_key(), parallel_partial_sum(), igl::per_vertex_point_to_plane_quadrics(), qh_copyfilename(), qh_copyfilename(), return_data(), nlohmann::detail::lexer< BasicJsonType, InputAdapterType >::scan_literal(), set_report(), stb__lit(), stb__match(), stl_normalize_vector(), triangulate_face(), nlohmann::detail::output_vector_adapter< CharType, AllocatorType >::write_characters(), nlohmann::detail::output_stream_adapter< CharType >::write_characters(), and nlohmann::detail::output_string_adapter< CharType, StringType >::write_characters().
make_bbox()
template<typename vector_type > void make_bbox (bounding_box_t< vector_type > & bbox, const vector_type * vertices, const int num_vertices)
{
    MCUT_ASSERT(vertices != nullptr);
    MCUT_ASSERT(num_vertices >= 3);
    for (int i = 0; i < num_vertices; ++i) {
        const vector_type& vertex = vertices[i];
        bbox.expand(vertex);
    }
}
References bounding_box_t< vector_type >::expand(), and MCUT_ASSERT.
max()
template<typename T > const T & max (const T & a, const T & b)
{
    return ((a < b) ? b : a);
}
Referenced by ProgressBar::ProgressBar(), libnest2d::opt::bound(), Slic3r::GUI::SliderCtrl::BUILD(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo(), Slic3r::BoundingBoxBase< PointClass >::center(), Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::sla::ConcaveHull::centroid(), compwise_max(), compwise_max(), Slic3r::GUI::PreferencesDialog::create_general_page(), Slic3r::GUI::CameraUtils::create_hull2d(), boost::nowide::utf8_codecvt< CharType, 4 >::do_length(), boost::nowide::utf8_codecvt< CharType, 2 >::do_length(), cdt::expand_with_points(), Slic3r::FillMonotonicLineWGapFill::fill_surface_extrusion(), FloatDown(), CBaseException::GetLogicalAddress(), Slic3r::GUI::GetNumberFromUser(), cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initialize(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::isInsideBox(), igl::isolines(), Eigen::numext::maxi(), Slic3r::BoundingBox3Base< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::offset(), Slic3r::BoundingBox3Base< PointClass >::offset(), Slic3r::sla::pairhash(), Slic3r::BoundingBox3Base< PointClass >::polygon(), pqDelete(), pqDelete(), Eigen::internal::predux_max< Packet4f >(), Eigen::internal::predux_max< Packet4i >(), Slic3r::PerimeterGenerator::process_classic(), qh_printhelp_singular(), qh_printhelp_singular(), Slic3r::BoundingBoxBase< PointClass >::radius(), Slic3r::BoundingBox3Base< PointClass >::radius(), Slic3r::GUI::ImageGrid::render(), RenderMaximumFaceGroup(), ColorGenerator::rgb2hsv(), Slic3r::GUI::Plater::priv::set_bed_shape(), Slic3r::GUI::GeometryBuffer::set_from_triangles(), Slic3r::GUI::MainFrame::set_max_recent_count(), Slic3r::GUI::MainFrame::FileHistory::SetMaxFiles(), ImGui::ShadeVertsLinearUV(), Slic3r::BoundingBoxBase< PointClass >::size(), Slic3r::BoundingBox3Base< PointClass >::size(), Slic3r::GUI::GCodeViewer::Extrusions::Range::step_size(), igl::straighten_seams(), Slic3r::GUI::NotificationManager::update_notifications(), and Slic3r::volumes_to_render().
min()
template<typename T > const T & min (const T & a, const T & b)
{
    return ((b < a) ? b : a);
}
Referenced by Slic3r::Model::adjust_min_z(), libnest2d::opt::bound(), Slic3r::GUI::SliderCtrl::BUILD(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo(), Slic3r::BoundingBoxBase< PointClass >::center(), Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::sla::ConcaveHull::centroid(), compare_prerelease(), compwise_min(), compwise_min(), Slic3r::GUI::CameraUtils::create_hull2d(), Slic3r::FillMonotonicLineWGapFill::fill_surface_extrusion(), Slic3r::GUI::GCodeViewer::Extrusions::Range::get_color_at(), Slic3r::GUI::GCodeViewer::Extrusions::Range::get_value_at_step(), Slic3r::GUI::GetNumberFromUser(), CurvatureCalculator::getSphere(), cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initialize(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::isInsideBox(), igl::isolines(), Slic3r::BoundingBox3Base< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::merge(), Eigen::numext::mini(), Slic3r::BoundingBoxBase< PointClass >::offset(), Slic3r::BoundingBox3Base< PointClass >::offset(), Slic3r::sla::pad_blueprint(), Slic3r::sla::pairhash(), Slic3r::BoundingBox3Base< PointClass >::polygon(), pqExtractMin(), Eigen::internal::predux_min< Packet4f >(), Eigen::internal::predux_min< Packet4i >(), Slic3r::PerimeterGenerator::process_classic(), qh_printhelp_singular(), qh_printhelp_singular(), Slic3r::BoundingBoxBase< PointClass >::radius(), Slic3r::BoundingBox3Base< PointClass >::radius(), ColorGenerator::rgb2hsv(), Slic3r::GUI::Plater::priv::set_bed_shape(), Slic3r::GUI::GeometryBuffer::set_from_triangles(), ImGui::ShadeVertsLinearUV(), ImGui::ShowMetricsWindow(), Slic3r::BoundingBoxBase< PointClass >::size(), Slic3r::BoundingBox3Base< PointClass >::size(), Slic3r::Polyline::split_at(), Slic3r::GUI::GCodeViewer::Extrusions::Range::step_size(), and Slic3r::validate().
normalize()
template<typename vector_type > vector_type normalize (const vector_type & v)
{
    return v / length(v);
}
References length().
Referenced by calculate_projection_matrix(), igl::colormap(), dispatch(), generate_supertriangle_from_mesh_vertices(), igl::jet(), linear_projection_sort(), igl::parula(), project_to_2d(), and triangulate_face().
operator<<() [1/2]
template<typename U > std::ostream & operator<< (std::ostream & os, const matrix_t< U > & m)
{
    for (int i = 0; i < m.rows(); i++) {
        for (int j = 0; j < m.cols(); j++) {
            os << m(i, j) << ", ";
        }
        os << "\n";
    }
    return os;
}
References matrix_t< T >::cols(), and matrix_t< T >::rows().
operator<<() [2/2]
std::ostream & operator<< (std::ostream & os, const vec3 & v)
    {
        return os << static_cast<double>(v.x()) << ", " << static_cast<double>(v.y()) << ", " << static_cast<double>(v.z());
    }
References vec2_< T >::x(), vec2_< T >::y(), and vec3_< T >::z().
operator==()
bool operator== (const vec3 & a, const vec3 & b)
    {
        return (a.x() == b.x()) && (a.y() == b.y()) && (a.z() == b.z());
    }
Referenced by Slic3r::MMU_Graph::append_voronoi_vertices(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::chain_lines(), Slic3r::chain_open_polylines_close_gaps(), Slic3r::chain_open_polylines_exact(), Slic3r::FillAdaptive::has_no_collinear_lines(), Slic3r::Layer::make_ironing(), Slic3r::MMU_Graph::Arc::operator!=(), and Slic3r::GUI::Plater::priv::reload_from_disk().
orient2d() [1/2]
double orient2d (const double * pa, const double * pb, const double * pc)
orient2d() [2/2]
double orient2d (const vec2 & pa, const vec2 & pb, const vec2 & pc)
    {
        const double pa_[2] = { static_cast<double>(pa.x()), static_cast<double>(pa.y()) };
        const double pb_[2] = { static_cast<double>(pb.x()), static_cast<double>(pb.y()) };
        const double pc_[2] = { static_cast<double>(pc.x()), static_cast<double>(pc.y()) };
        return ::orient2d(pa_, pb_, pc_); // shewchuk predicate
    }
References vec2_< T >::x(), and vec2_< T >::y().
Referenced by collinear(), collinear(), cdt::triangulator_t< T, TNearPointLocator >::get_intersected_triangle(), cdt::detail::get_intersection_point_coords(), cdt::locate_point_wrt_line(), and triangulate_face().
orient3d() [1/2]
double orient3d (const double * pa, const double * pb, const double * pc, const double * pd)
orient3d() [2/2]
double orient3d (const vec3 & pa, const vec3 & pb, const vec3 & pc, const vec3 & pd)
    {
        const double pa_[3] = { static_cast<double>(pa.x()), static_cast<double>(pa.y()), static_cast<double>(pa.z()) };
        const double pb_[3] = { static_cast<double>(pb.x()), static_cast<double>(pb.y()), static_cast<double>(pb.z()) };
        const double pc_[3] = { static_cast<double>(pc.x()), static_cast<double>(pc.y()), static_cast<double>(pc.z()) };
        const double pd_[3] = { static_cast<double>(pd.x()), static_cast<double>(pd.y()), static_cast<double>(pd.z()) };
        return ::orient3d(pa_, pb_, pc_, pd_); // shewchuk predicate
    }
References pd, vec2_< T >::x(), vec2_< T >::y(), and vec3_< T >::z().
Referenced by compute_line_plane_intersection(), compute_segment_line_plane_intersection_type(), compute_segment_plane_intersection_type(), and coplaner().
orient3dfast()
double orient3dfast (const double * pa, const double * pb, const double * pc, const double * pd)
outer_product()
template<typename vector_type > matrix_t< typename vector_type::element_type > outer_product (const vector_type & a, const vector_type & b)
{
    matrix_t<typename vector_type::element_type> out(vector_type::cardinality(), vector_type::cardinality());
    const vector_type c0 = a * b[0]; // colmuns
    const vector_type c1 = a * b[1];
    if (vector_type::cardinality() == 3) {
        const vector_type c2 = a * b[2];
        out(0, 0) = c0[0];
        out(1, 0) = c0[1];
        out(2, 0) = c0[2];
        out(0, 1) = c1[0];
        out(1, 1) = c1[1];
        out(2, 1) = c1[2];
        out(0, 2) = c2[0];
        out(1, 2) = c2[1];
        out(2, 2) = c2[2];
    } else {
        out(0, 0) = c0[0];
        out(1, 0) = c0[1];
        out(0, 1) = c1[0];
        out(1, 1) = c1[1];
    }
    return out;
}
References out.
Referenced by calculate_projection_matrix().
point_in_bounding_box() [1/2]
bool point_in_bounding_box (const vec2 & point, const bounding_box_t< vec2 > & bbox) inline
    {
        if ((point.x() < bbox.m_minimum.x() || point.x() > bbox.m_maximum.x()) || //
            (point.y() < bbox.m_minimum.y() || point.y() > bbox.m_maximum.y())) {
            return false;
        } else {
            return true;
        }
    }
References bounding_box_t< vector_type >::m_maximum, bounding_box_t< vector_type >::m_minimum, vec2_< T >::x(), and vec2_< T >::y().
point_in_bounding_box() [2/2]
bool point_in_bounding_box (const vec3 & point, const bounding_box_t< vec3 > & bbox) inline
    {
        if ((point.x() < bbox.m_minimum.x() || point.x() > bbox.m_maximum.x()) || //
            (point.y() < bbox.m_minimum.y() || point.y() > bbox.m_maximum.y()) || //
            (point.z() < bbox.m_minimum.z() || point.z() > bbox.m_maximum.z())) { //
            return false;
        } else {
            return true;
        }
    }
References bounding_box_t< vector_type >::m_maximum, bounding_box_t< vector_type >::m_minimum, vec2_< T >::x(), vec2_< T >::y(), and vec3_< T >::z().
project_to_2d() [1/2]
void project_to_2d (std::vector< vec2 > & out, const std::vector< vec3 > & polygon_vertices, const vec3 & polygon_normal)
    {
        const uint32_t N = polygon_vertices.size();
        out.resize(N);
        const vec3 normal = normalize(polygon_normal);
        // first unit vector on plane (rotation by 90 degrees)
        vec3 u(-normal.y(), normal.x(), normal.z());
        vec3 v = normalize(cross_product(u, normal));
        for(uint32_t i =0; i < N; ++i)
        {
            const vec3 point = polygon_vertices[i];
            const vec2 projected(
                dot_product(point, u),
                dot_product(point, v)
            );
            out[i] = projected;
        }
    }
References cross_product(), dot_product(), normalize(), and out.
Referenced by determine_three_noncollinear_vertices().
project_to_2d() [2/2]
void project_to_2d (std::vector< vec2 > & out, const std::vector< vec3 > & polygon_vertices, const vec3 & polygon_normal, const int polygon_normal_largest_component)
    {
        const int polygon_vertex_count = (int)polygon_vertices.size();
        out.clear();
        out.resize(polygon_vertex_count);
#if 1
        // 3x3 matrix for projecting a point to 2D
        matrix_t<double> P = calculate_projection_matrix(polygon_normal, polygon_normal_largest_component);
        for (int i = 0; i < polygon_vertex_count; ++i) { // for each vertex
            const vec3& x = polygon_vertices[i];
            out[i] = P * x; // vertex in xz plane
        }
#else // This code is not reliable because it shadow-projects a polygons which can skew computations
        for (int i = 0; i < polygon_vertex_count; ++i) { // for each vertex
            vec2& Tp = out[i];
            int k = 0;
            for (int j = 0; j < 3; j++) { // for each component
                if (j != polygon_plane_normal_largest_component) { /* skip largest coordinate */
                    Tp[k] = polygon_vertices[i][j];
                    k++;
                }
            }
        }
#endif
    }
References calculate_projection_matrix(), int, and out.
Referenced by resolve_floating_polygons(), and triangulate_face().
sign()
sign_t sign (const double & number)
    {
#if !defined(MCUT_WITH_ARBITRARY_PRECISION_NUMBERS)
        int s = (double(0) < number) - (number < double(0));
        sign_t result = sign_t::ZERO;
        if (s > 0) {
            result = sign_t::POSITIVE;
        } else if (s < 0) {
            result = sign_t::NEGATIVE;
        }
        return result;
#else
        double out(number);
        int s = mpfr_sgn(number.get_mpfr_handle());
        sign_t result = sign_t::ZERO;
        if (s > 0) {
            result = sign_t::POSITIVE;
        } else if (s < 0) {
            result = sign_t::NEGATIVE;
        }
        return result;
#endif // #if defined(MCUT_WITH_ARBITRARY_PRECISION_NUMBERS)
    }
References NEGATIVE, out, POSITIVE, and ZERO.
square_root()
double square_root (const double & number)
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
    {
#if !defined(MCUT_WITH_ARBITRARY_PRECISION_NUMBERS)
        return std::sqrt(number);
#else
        arbitrary_precision_number_t out(number);
        mpfr_sqrt(out.get_mpfr_handle(), number.get_mpfr_handle(), arbitrary_precision_number_t::get_default_rounding_mode());
        return out;
#endif // #if !defined(MCUT_WITH_ARBITRARY_PRECISION_NUMBERS)
    }
References out.
Referenced by length().
squared_length()
template<typename vector_type > double squared_length (const vector_type & v)
{
    return dot_product(v, v);
}
References dot_product().
Referenced by calculate_projection_matrix(), dispatch(), length(), igl::copyleft::cgal::point_mesh_squared_distance(), igl::copyleft::cgal::point_segment_squared_distance(), point_triangle_squared_distance(), resolve_floating_polygons(), igl::copyleft::cgal::subdivide_segments(), and triangulate_face().