OrcaSlicer: src/mcut/source/hmesh.cpp File Reference
hmesh.cpp File Reference
#include "mcut/internal/hmesh.h"
#include <algorithm>
#include <cstdio>
Macros
#define ENABLE_EDGE_DESCRIPTOR_TRICK 1
Functions
void write_off (const char *fpath, const hmesh_t &mesh)
void read_off (hmesh_t &mesh, const char *fpath)
Macro Definition Documentation
ENABLE_EDGE_DESCRIPTOR_TRICK
#define ENABLE_EDGE_DESCRIPTOR_TRICK 1
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
Function Documentation
read_off()
void read_off (hmesh_t & mesh, const char * fpath)
{
    auto next_line = [&](std::ifstream& f, std::string& s) -> bool {
        while (getline(f, s)) {
            if (s.length() > 1 && s[0] != '#') {
                return true;
            }
        }
        return false;
    };
    std::ifstream infile(fpath);
    if (!infile.is_open()) {
        printf("error: could not open file: %s\n", fpath);
        std::exit(1);
    }
    //
    // file header
    //
    std::string header;
    if (!next_line(infile, header)) {
        printf("error: .off file header not found\n");
        std::exit(1);
    }
    if (header != "OFF") {
        printf("error: unrecognised .off file header\n");
        std::exit(1);
    }
    //
    // #vertices, #faces, #edges
    //
    std::string info;
    if (!next_line(infile, info)) {
        printf("error: .off element count not found\n");
        std::exit(1);
    }
    std::istringstream info_stream;
    info_stream.str(info);
    int nvertices;
    int nfaces;
    int nedges;
    info_stream >> nvertices >> nfaces >> nedges;
    //
    // vertices
    //
    std::map<int, vd_t> vmap;
    for (int i = 0; i < nvertices; ++i) {
        if (!next_line(infile, info)) {
            printf("error: .off vertex not found\n");
            std::exit(1);
        }
        std::istringstream vtx_line_stream(info);
        double x;
        double y;
        double z;
        vtx_line_stream >> x >> y >> z;
        vmap[i] = mesh.add_vertex(x, y, z);
    }
    //
    // edges
    //
    for (int i = 0; i < nedges; ++i) {
        // TODO
    }
    //
    // faces
    //
    for (auto i = 0; i < nfaces; ++i) {
        if (!next_line(infile, info)) {
            printf("error: .off file face not found\n");
            std::exit(1);
        }
        std::istringstream face_line_stream(info);
        int n; // number of vertices in face
        int index;
        face_line_stream >> n;
        if (n < 3) {
            printf("error: invalid polygon vertex count in file (%d)\n", n);
            std::exit(1);
        }
        typename std::vector<vd_t> face;
        face.resize(n);
        for (int j = 0; j < n; ++j) {
            info_stream >> index;
            face[j] = vmap[index];
        }
        mesh.add_face(face);
    }
    infile.close();
}
References hmesh_t::add_face(), hmesh_t::add_vertex(), and n.
write_off()
void write_off (const char * fpath, const hmesh_t & mesh)
{
    std::ofstream outfile(fpath);
    if (!outfile.is_open()) {
        printf("error: could not open file: %s\n", fpath);
        std::exit(1);
    }
    //
    // file header
    //
    outfile << "OFF\n";
    //
    // #vertices, #faces, #edges
    //
    outfile << mesh.number_of_vertices() << " " << mesh.number_of_faces() << " " << 0 /*mesh.number_of_edges()*/ << "\n";
    //
    // vertices
    //
    for (vertex_array_iterator_t iter = mesh.vertices_begin(); iter != mesh.vertices_end(); ++iter) {
        // const vertex_data_t& vdata = iter.second;
        const vec3& point = mesh.vertex(*iter);
        outfile << (double)point.x() << " " << (double)point.y() << " " << (double)point.z() << "\n";
    }
    //
    // edges
    //
#if 0
    for (typename hmesh_t::edge_iterator_t iter = mesh.edges_begin(); iter != mesh.edges_end(); ++iter) {
        const hmesh_t::edge_descriptor_t ed = iter.first;
        const hmesh_t::vertex_descriptor_t& v0 = vertex(ed, 0);
        const hmesh_t::vertex_descriptor_t& v1 = vertex(ed, 1);
        // TODO
    }
#endif
    //
    // faces
    //
    for (face_array_iterator_t iter = mesh.faces_begin(); iter != mesh.faces_end(); ++iter) {
        // const typename hmesh_t::face_descriptor_t& fd = iter.first;
        const std::vector<vertex_descriptor_t> vertices_around_face = mesh.get_vertices_around_face(*iter);
        MCUT_ASSERT(!vertices_around_face.empty());
        outfile << vertices_around_face.size() << " ";
        for (std::vector<vertex_descriptor_t>::const_iterator i = vertices_around_face.cbegin(); i != vertices_around_face.cend(); ++i) {
            outfile << (*i) << " ";
        }
        outfile << " \n";
    }
    outfile.close();
}
References hmesh_t::edges_begin(), hmesh_t::edges_end(), hmesh_t::faces_begin(), hmesh_t::faces_end(), hmesh_t::get_vertices_around_face(), MCUT_ASSERT, hmesh_t::number_of_faces(), hmesh_t::number_of_vertices(), hmesh_t::vertex(), hmesh_t::vertices_begin(), hmesh_t::vertices_end(), vec2_< T >::x(), vec2_< T >::y(), and vec3_< T >::z().
Referenced by ImGuiTextBuffer::append(), ImGuiTextBuffer::appendfv(), and dump_mesh().