OrcaSlicer: Slic3r::GUI::DesignerPanel Class Reference
Slic3r::GUI::DesignerPanel Class Reference
#include <src/slic3r/GUI/Auxiliary.hpp>
Public Member Functions
DesignerPanel (wxWindow *parent, AuxiliaryFolderType type, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~DesignerPanel ()
bool Show (bool show) override
void init_license_list ()
void on_input_enter_designer (wxCommandEvent &evt)
void on_input_enter_model (wxCommandEvent &evt)
void on_select_license (wxCommandEvent &evt)
void update_info ()
void msw_rescale ()
Public Attributes
::TextInput * m_input_designer {nullptr}
::TextInput * m_imput_model_name {nullptr}
Detailed Description
Constructor & Destructor Documentation
DesignerPanel()
Slic3r::GUI::DesignerPanel::DesignerPanel (wxWindow * parent, AuxiliaryFolderType type, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
     : wxPanel(parent, id, pos, size, style)
{
     SetBackgroundColour(AUFILE_GREY300);
     wxBoxSizer *m_sizer_body = new wxBoxSizer(wxVERTICAL);
     wxBoxSizer *m_sizer_designer = new wxBoxSizer(wxHORIZONTAL);
     auto m_text_designer = new wxStaticText(this, wxID_ANY, _L("Author"), wxDefaultPosition, wxSize(180, -1), 0);
     m_text_designer->Wrap(-1);
     m_text_designer->SetForegroundColour(*wxBLACK);
     m_sizer_designer->Add(m_text_designer, 0, wxALIGN_CENTER, 0);
     m_input_designer =  new ::TextInput(this, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, wxSize(FromDIP(450), FromDIP(30)), wxTE_PROCESS_ENTER);
     m_input_designer->GetTextCtrl()->SetFont(::Label::Body_14);
     m_input_designer->GetTextCtrl()->SetSize(wxSize(FromDIP(450), -1));
     m_sizer_designer->Add(m_input_designer, 0, wxALIGN_CENTER, 0);
     wxBoxSizer *m_sizer_model_name = new wxBoxSizer(wxHORIZONTAL);
     auto m_text_model_name = new wxStaticText(this, wxID_ANY, _L("Model Name"), wxDefaultPosition, wxSize(180, -1), 0);
     m_text_model_name->SetForegroundColour(*wxBLACK);
     m_text_model_name->Wrap(-1);
     m_sizer_model_name->Add(m_text_model_name, 0, wxALIGN_CENTER, 0);
     m_imput_model_name =  new ::TextInput(this, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition,wxSize(FromDIP(450),FromDIP(30)), wxTE_PROCESS_ENTER);
     m_imput_model_name->GetTextCtrl()->SetFont(::Label::Body_14);
     m_imput_model_name->GetTextCtrl()->SetSize(wxSize(FromDIP(450), -1));
     m_sizer_model_name->Add(m_imput_model_name, 0, wxALIGN_CENTER, 0);
     /*
     wxBoxSizer *m_sizer_license = new wxBoxSizer(wxHORIZONTAL);
     auto m_text_license = new wxStaticText(this, wxID_ANY, _L("License"), wxDefaultPosition, wxSize(120, -1), 0);
     m_text_license->Wrap(-1);
     m_sizer_license->Add(m_text_license, 0, wxALIGN_CENTER, 0);
     m_combo_license = new wxComboBox(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxSize(450, -1), 0, NULL, wxCB_READONLY);
     m_sizer_license->Add(m_combo_license, 0, wxALIGN_CENTER, 0);
     */
     m_sizer_body->Add( 0, 0, 0, wxTOP, FromDIP(50) );
     m_sizer_body->Add(m_sizer_designer, 0, wxLEFT, FromDIP(50));
     m_sizer_body->Add( 0, 0, 0, wxTOP, FromDIP(20));
     m_sizer_body->Add(m_sizer_model_name, 0, wxLEFT, FromDIP(50));
     //m_sizer_body->Add(0, 0, 0, wxTOP, FromDIP(20));
     //m_sizer_body->Add(m_sizer_license, 0, wxLEFT, FromDIP(50));
     //init_license_list();
     SetSizer(m_sizer_body);
     Layout();
     Fit();
     m_input_designer->Bind(wxEVT_TEXT, &DesignerPanel::on_input_enter_designer, this);
     m_imput_model_name->Bind(wxEVT_TEXT, &DesignerPanel::on_input_enter_model, this);
     //m_combo_license->Connect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(DesignerPanel::on_select_license), NULL, this);
}
References _L, AUFILE_GREY300, Label::Body_14, TextInput::GetTextCtrl(), m_imput_model_name, m_input_designer, on_input_enter_designer(), on_input_enter_model(), and wxStaticText.
~DesignerPanel()
Slic3r::GUI::DesignerPanel::~DesignerPanel ()
 {
     //m_combo_license->Disconnect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(DesignerPanel::on_select_license), NULL, this);
 }
Member Function Documentation
init_license_list()
void Slic3r::GUI::DesignerPanel::init_license_list ()
 {
     /*
     wxArrayString text_licese;
     for (int i = 0; i < license_list.size(); i++) {
         text_licese.Add(license_list[i]);
     }
     m_combo_license->Set(text_licese);
     */
 }
msw_rescale()
void Slic3r::GUI::DesignerPanel::msw_rescale ()
{
    m_input_designer->GetTextCtrl()->SetSize(wxSize(FromDIP(450), -1));
    m_imput_model_name->GetTextCtrl()->SetSize(wxSize(FromDIP(450), -1));
}
References TextInput::GetTextCtrl(), m_imput_model_name, and m_input_designer.
Referenced by Slic3r::GUI::AuxiliaryPanel::msw_rescale().
on_input_enter_designer()
void Slic3r::GUI::DesignerPanel::on_input_enter_designer (wxCommandEvent & evt)
{
    auto text  = evt.GetString();
    wxGetApp().plater()->model().SetDesigner(std::string(text.ToUTF8().data()), "");
}
Referenced by DesignerPanel().
on_input_enter_model()
void Slic3r::GUI::DesignerPanel::on_input_enter_model (wxCommandEvent & evt)
{
    auto text   = evt.GetString();
    if (wxGetApp().plater()->model().model_info) {
        wxGetApp().plater()->model().model_info->model_name = std::string(text.ToUTF8().data());
    }
}
References Slic3r::GUI::plater().
Referenced by DesignerPanel().
on_select_license()
void Slic3r::GUI::DesignerPanel::on_select_license (wxCommandEvent & evt)
 {
     int selected = evt.GetInt();
     if (selected >= 0 && selected < license_list.size()) {
         if (wxGetApp().plater()->model().model_info == nullptr) {
             wxGetApp().plater()->model().model_info = std::make_shared<ModelInfo>();
         }
         if (wxGetApp().plater()->model().model_info != nullptr) {
             wxGetApp().plater()->model().model_info->license = license_list[selected];
         }
     }
 }
References Slic3r::GUI::license_list, and Slic3r::GUI::plater().
Show()
bool Slic3r::GUI::DesignerPanel::Show (bool show) override
{
    if ( wxGetApp().plater()->model().design_info != nullptr) {
        wxString text = wxString::FromUTF8(wxGetApp().plater()->model().design_info->Designer);
        m_input_designer->GetTextCtrl()->SetValue(text);
    }
     if (wxGetApp().plater()->model().model_info != nullptr) {
         wxString text = wxString::FromUTF8(wxGetApp().plater()->model().model_info->model_name);
         m_imput_model_name->GetTextCtrl()->SetValue(text);
     }
    return wxPanel::Show(show);
}
References TextInput::GetTextCtrl(), m_imput_model_name, m_input_designer, and Slic3r::GUI::plater().
update_info()
void Slic3r::GUI::DesignerPanel::update_info ()
{
    if (wxGetApp().plater()->model().design_info != nullptr) {
        wxString text = wxString::FromUTF8(wxGetApp().plater()->model().design_info->Designer);
        m_input_designer->GetTextCtrl()->SetValue(text);
    } else {
        m_input_designer->GetTextCtrl()->SetValue(wxEmptyString);
    }
    if (wxGetApp().plater()->model().model_info != nullptr) {
        wxString text = wxString::FromUTF8(wxGetApp().plater()->model().model_info->model_name);
        m_imput_model_name->GetTextCtrl()->SetValue(text);
    } else {
         m_imput_model_name->GetTextCtrl()->SetValue(wxEmptyString);
    }
}
References TextInput::GetTextCtrl(), m_imput_model_name, m_input_designer, and Slic3r::GUI::plater().
Referenced by Slic3r::GUI::AuxiliaryPanel::Reload().
Member Data Documentation
m_imput_model_name
::TextInput* Slic3r::GUI::DesignerPanel::m_imput_model_name {nullptr}
Referenced by DesignerPanel(), msw_rescale(), Show(), and update_info().
m_input_designer
::TextInput* Slic3r::GUI::DesignerPanel::m_input_designer {nullptr}
Referenced by DesignerPanel(), msw_rescale(), Show(), and update_info().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Auxiliary.hpp
src/slic3r/GUI/Auxiliary.cpp