OrcaSlicer: orgQhull::QhullVertex Class Reference
orgQhull::QhullVertex Class Reference
#include <src/qhull/src/libqhullcpp/QhullVertex.h>
Classes
struct PrintVertex
Public Types
Defined here
typedef vertexT * base_type
Public Member Functions
Constructors
QhullVertex ()
QhullVertex (const Qhull &q)
QhullVertex (const Qhull &q, vertexT *v)
QhullVertex (QhullQh *qqh)
QhullVertex (QhullQh *qqh, vertexT *v)
QhullVertex (const QhullVertex &other)
QhullVertex & operator= (const QhullVertex &other)
~QhullVertex ()
GetSet
int dimension () const
vertexT * getBaseT () const
For QhullSet<QhullVertex>
vertexT * getVertexT () const
countT id () const
bool isValid () const
bool neighborFacetsDefined () const
True if defineVertexNeighborFacets() already called. Auotomatically set for facet merging, Voronoi diagrams.
QhullVertex next () const
bool operator== (const QhullVertex &other) const
bool operator!= (const QhullVertex &other) const
QhullPoint point () const
QhullVertex previous () const
QhullQh * qh () const
foreach
QhullFacetSet neighborFacets () const
Return neighboring facets for a vertex If neither merging nor Voronoi diagram, requires Qhull::defineVertexNeighborFacets() beforehand.
IO
PrintVertex print (const char *message) const
Private Attributes
Fields
vertexT * qh_vertex
Corresponding vertexT, never 0.
QhullQh * qh_qh
QhullQh/qhT for vertexT, may be 0.
Static Private Attributes
Class objects
static vertexT s_empty_vertex
Detailed Description
Member Typedef Documentation
base_type
typedef vertexT* orgQhull::QhullVertex::base_type
Constructor & Destructor Documentation
QhullVertex() [1/6]
orgQhull::QhullVertex::QhullVertex () inline
: qh_vertex(&s_empty_vertex), qh_qh(0) {}
Referenced by next(), and previous().
QhullVertex() [2/6]
orgQhull::QhullVertex::QhullVertex (const Qhull & q) explicit
: qh_vertex(&s_empty_vertex)
, qh_qh(q.qh())
{
}//Default
QhullVertex() [3/6]
orgQhull::QhullVertex::QhullVertex (const Qhull & q, vertexT * v)
: qh_vertex(v ? v : &s_empty_vertex)
, qh_qh(q.qh())
{
}//vertexT
QhullVertex() [4/6]
orgQhull::QhullVertex::QhullVertex (QhullQh * qqh) inline explicit
: qh_vertex(&s_empty_vertex), qh_qh(qqh) {}
QhullVertex() [5/6]
orgQhull::QhullVertex::QhullVertex (QhullQh * qqh, vertexT * v) inline
: qh_vertex(v ? v : &s_empty_vertex), qh_qh(qqh) {}
QhullVertex() [6/6]
orgQhull::QhullVertex::QhullVertex (const QhullVertex & other) inline
: qh_vertex(other.qh_vertex), qh_qh(other.qh_qh) {}
~QhullVertex()
orgQhull::QhullVertex::~QhullVertex () inline
{}
Member Function Documentation
dimension()
int orgQhull::QhullVertex::dimension () const inline
{ return (qh_qh ? qh_qh->hull_dim : 0); }
References qhT::hull_dim, and qh_qh.
Referenced by orgQhull::QhullVertex_test::t_constructConvert(), and orgQhull::QhullVertex_test::t_getSet().
getBaseT()
vertexT * orgQhull::QhullVertex::getBaseT () const inline
For QhullSet<QhullVertex>
References getVertexT().
Referenced by orgQhull::QhullVertex_test::t_constructConvert().
getVertexT()
vertexT * orgQhull::QhullVertex::getVertexT () const inline
{ return qh_vertex; }
References qh_vertex.
Referenced by getBaseT(), operator<<(), and orgQhull::QhullVertex_test::t_constructConvert().
id()
countT orgQhull::QhullVertex::id () const inline
{ return qh_vertex->id; }
References vertexT::id, and qh_vertex.
Referenced by operator<<(), operator<<(), operator<<(), orgQhull::QhullLinkedList_test::t_const_iterator(), orgQhull::QhullVertex_test::t_getSet(), and orgQhull::QhullLinkedList_test::t_iterator().
isValid()
bool orgQhull::QhullVertex::isValid () const inline
{ return (qh_qh && qh_vertex != &s_empty_vertex); }
References qh_qh, qh_vertex, and s_empty_vertex.
Referenced by orgQhull::QhullVertex_test::t_constructConvert(), and orgQhull::QhullVertex_test::t_getSet().
neighborFacets()
QhullFacetSet orgQhull::QhullVertex::neighborFacets () const
Return neighboring facets for a vertex If neither merging nor Voronoi diagram, requires Qhull::defineVertexNeighborFacets() beforehand.
{
    if(!neighborFacetsDefined()){
        throw QhullError(10034, "Qhull error: neighboring facets of vertex %d not defined.  Please call Qhull::defineVertexNeighborFacets() beforehand.", id());
    }
    return QhullFacetSet(qh_qh, qh_vertex->neighbors);
}//neighborFacets
References neighborFacetsDefined(), vertexT::neighbors, qh_qh, and qh_vertex.
Referenced by operator<<(), and orgQhull::QhullVertex_test::t_foreach().
neighborFacetsDefined()
bool orgQhull::QhullVertex::neighborFacetsDefined () const inline
True if defineVertexNeighborFacets() already called. Auotomatically set for facet merging, Voronoi diagrams.
{ return qh_vertex->neighbors != 0; }
References vertexT::neighbors, and qh_vertex.
Referenced by neighborFacets(), and operator<<().
next()
QhullVertex orgQhull::QhullVertex::next () const inline
{ return QhullVertex(qh_qh, qh_vertex->next); }
References QhullVertex(), vertexT::next, qh_qh, and qh_vertex.
Referenced by operator<<(), orgQhull::QhullLinkedList_test::t_const_iterator(), orgQhull::QhullLinkedList_test::t_element(), orgQhull::QhullVertex_test::t_getSet(), orgQhull::QhullLinkedList_test::t_iterator(), and orgQhull::QhullLinkedList_test::t_QhullLinkedList_iterator().
operator!=()
bool orgQhull::QhullVertex::operator!= (const QhullVertex & other) const inline
{ return !operator==(other); }
References operator==().
operator=()
QhullVertex & orgQhull::QhullVertex::operator= (const QhullVertex & other) inline
{ qh_vertex= other.qh_vertex; qh_qh= other.qh_qh; return *this; }
References qh_qh, and qh_vertex.
operator==()
bool orgQhull::QhullVertex::operator== (const QhullVertex & other) const inline
{ return qh_vertex==other.qh_vertex; }
References qh_vertex.
Referenced by operator!=().
point()
QhullPoint orgQhull::QhullVertex::point () const inline
{ return QhullPoint(qh_qh, qh_vertex->point); }
References vertexT::point, qh_qh, and qh_vertex.
Referenced by operator<<(), operator<<(), orgQhull::QhullPoint_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullPoint_test::t_convert(), orgQhull::QhullVertex_test::t_getSet(), orgQhull::QhullPoint_test::t_io(), orgQhull::QhullPoint_test::t_iterator(), orgQhull::QhullPoint_test::t_method(), orgQhull::QhullPoint_test::t_operator(), and orgQhull::QhullPoint_test::t_qhullpoint_iterator().
previous()
QhullVertex orgQhull::QhullVertex::previous () const inline
{ return QhullVertex(qh_qh, qh_vertex->previous); }
References QhullVertex(), vertexT::previous, qh_qh, and qh_vertex.
Referenced by orgQhull::QhullLinkedList_test::t_element(), and orgQhull::QhullVertex_test::t_getSet().
print()
PrintVertex orgQhull::QhullVertex::print (const char * message) const inline
{ return PrintVertex(message, *this); }
Referenced by operator<<(), operator<<(), and orgQhull::QhullVertex_test::t_io().
qh()
QhullQh * orgQhull::QhullVertex::qh () const inline
{ return qh_qh; }
References qh_qh.
Member Data Documentation
qh_qh
QhullQh* orgQhull::QhullVertex::qh_qh private
QhullQh/qhT for vertexT, may be 0.
Referenced by dimension(), isValid(), neighborFacets(), next(), operator=(), point(), previous(), and qh().
qh_vertex
vertexT* orgQhull::QhullVertex::qh_vertex private
Corresponding vertexT, never 0.
Referenced by getVertexT(), id(), isValid(), neighborFacets(), neighborFacetsDefined(), next(), operator=(), operator==(), point(), and previous().
s_empty_vertex
vertexT orgQhull::QhullVertex::s_empty_vertex static private
Initial value:
= {0,0,0,0,0,
                 0,0,0,0,0,
                 0}
Referenced by isValid().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullVertex.h
src/qhull/src/libqhullcpp/QhullVertex.cpp