OrcaSlicer: Clipper2Lib::RectClipLines Class Reference
Clipper2Lib::RectClipLines Class Reference
#include <src/clipper2/Clipper2Lib/include/clipper2/clipper.rectclip.h>
Public Member Functions
RectClipLines (const Rect64 &rect)
Paths64 Execute (const Path64 &path)
Protected Member Functions
void GetNextLocation (const Path64 &path, Location &loc, int &i, int highI)
void AddCorner (Location prev, Location curr)
void AddCorner (Location &loc, bool isClockwise)
Protected Attributes
const Rect64 rect_
const Point64 mp_
const Path64 rectPath_
Path64 result_
std::vector< Location > start_locs_
Detailed Description
Constructor & Destructor Documentation
RectClipLines()
Clipper2Lib::RectClipLines::RectClipLines (const Rect64 & rect) inline
: RectClip(rect) {};
Member Function Documentation
AddCorner() [1/2]
void Clipper2Lib::RectClip::AddCorner (Location & loc, bool isClockwise) protected inherited
  {
    if (isClockwise)
    {
      result_.push_back(rectPath_[static_cast<int>(loc)]);
      loc = GetAdjacentLocation(loc, true);
    }
    else
    {
      loc = GetAdjacentLocation(loc, false);
      result_.push_back(rectPath_[static_cast<int>(loc)]);
    }
  }
References Clipper2Lib::GetAdjacentLocation(), Clipper2Lib::RectClip::rectPath_, and Clipper2Lib::RectClip::result_.
AddCorner() [2/2]
void Clipper2Lib::RectClip::AddCorner (Location prev, Location curr) protected inherited
  {
    if (HeadingClockwise(prev, curr))
      result_.push_back(rectPath_[static_cast<int>(prev)]);
    else
      result_.push_back(rectPath_[static_cast<int>(curr)]);
  }
References Clipper2Lib::HeadingClockwise(), Clipper2Lib::RectClip::rectPath_, and Clipper2Lib::RectClip::result_.
Referenced by Clipper2Lib::RectClip::Execute().
Execute()
Paths64 Clipper2Lib::RectClipLines::Execute (const Path64 & path)
  {
    result_.clear();
    Paths64 result;
    if (rect_.IsEmpty() || path.size() == 0) return result;
    int i = 1, highI = static_cast<int>(path.size()) - 1;
    Location prev = Location::Inside, loc;
    Location crossing_loc = Location::Inside;
    if (!GetLocation(rect_, path[0], loc))
    {
      while (i <= highI && !GetLocation(rect_, path[i], prev)) ++i;
      if (i > highI) {
        result.push_back(path);
        return result;
      }
      if (prev == Location::Inside) loc = Location::Inside;
      i = 1;
    }
    if (loc == Location::Inside) result_.push_back(path[0]);
    while (i <= highI)
    {
      prev = loc;
      GetNextLocation(path, loc, i, highI);
      if (i > highI) break;
      Point64 ip, ip2;
      Point64 prev_pt = path[static_cast<size_t>(i - 1)];
      crossing_loc = loc;
      if (!GetIntersection(rectPath_, path[i], prev_pt, crossing_loc, ip))
      {
        // ie remaining outside
        ++i;
        continue;
      }
      // we must be crossing the rect boundary to get here
      if (loc == Location::Inside) // path must be entering rect
      {
        result_.push_back(ip);
      }
      else if (prev != Location::Inside)
      {
        // passing right through rect. 'ip' here will be the second
        // intersect pt but we'll also need the first intersect pt (ip2)
        crossing_loc = prev;
        GetIntersection(rectPath_, prev_pt, path[i], crossing_loc, ip2);
        result_.push_back(ip2);
        result_.push_back(ip);
        result.push_back(result_);
        result_.clear();
      }
      else // path must be exiting rect
      {
        result_.push_back(ip);
        result.push_back(result_);
        result_.clear();
      }
    } //while i <= highI
    if (result_.size() > 1)
      result.push_back(result_);
    return result;
  }
References Clipper2Lib::GetIntersection(), Clipper2Lib::GetLocation(), Clipper2Lib::RectClip::GetNextLocation(), Clipper2Lib::Inside, Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::RectClip::rect_, Clipper2Lib::RectClip::rectPath_, and Clipper2Lib::RectClip::result_.
Referenced by Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines(), Clipper2Lib::RectClipLines64(), and Clipper2Lib::RectClipLinesD().
GetNextLocation()
void Clipper2Lib::RectClip::GetNextLocation (const Path64 & path, Location & loc, int & i, int highI) protected inherited
  {
    switch (loc)
    {
    case Location::Left:
      while (i <= highI && path[i].x <= rect_.left) ++i;
      if (i > highI) break;
      else if (path[i].x >= rect_.right) loc = Location::Right;
      else if (path[i].y <= rect_.top) loc = Location::Top;
      else if (path[i].y >= rect_.bottom) loc = Location::Bottom;
      else loc = Location::Inside;
      break;
    case Location::Top:
      while (i <= highI && path[i].y <= rect_.top) ++i;
      if (i > highI) break;
      else if (path[i].y >= rect_.bottom) loc = Location::Bottom;
      else if (path[i].x <= rect_.left) loc = Location::Left;
      else if (path[i].x >= rect_.right) loc = Location::Right;
      else loc = Location::Inside;
      break;
    case Location::Right:
      while (i <= highI && path[i].x >= rect_.right) ++i;
      if (i > highI) break;
      else if (path[i].x <= rect_.left) loc = Location::Left;
      else if (path[i].y <= rect_.top) loc = Location::Top;
      else if (path[i].y >= rect_.bottom) loc = Location::Bottom;
      else loc = Location::Inside;
      break;
    case Location::Bottom:
      while (i <= highI && path[i].y >= rect_.bottom) ++i;
      if (i > highI) break;
      else if (path[i].y <= rect_.top) loc = Location::Top;
      else if (path[i].x <= rect_.left) loc = Location::Left;
      else if (path[i].x >= rect_.right) loc = Location::Right;
      else loc = Location::Inside;
      break;
    case Location::Inside:
      while (i <= highI)
      {
        if (path[i].x < rect_.left) loc = Location::Left;
        else if (path[i].x > rect_.right) loc = Location::Right;
        else if (path[i].y > rect_.bottom) loc = Location::Bottom;
        else if (path[i].y < rect_.top) loc = Location::Top;
        else { result_.push_back(path[i]); ++i; continue; }
        break; //inner loop
      }
      break;
    } //switch
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Bottom, Clipper2Lib::Inside, Clipper2Lib::Rect< T >::left, Clipper2Lib::Left, Clipper2Lib::RectClip::rect_, Clipper2Lib::RectClip::result_, Clipper2Lib::Rect< T >::right, Clipper2Lib::Right, Clipper2Lib::Rect< T >::top, and Clipper2Lib::Top.
Referenced by Clipper2Lib::RectClip::Execute(), and Execute().
Member Data Documentation
mp_
const Point64 Clipper2Lib::RectClip::mp_ protected inherited
Referenced by Clipper2Lib::RectClip::Execute().
rect_
const Rect64 Clipper2Lib::RectClip::rect_ protected inherited
Referenced by Clipper2Lib::RectClip::Execute(), Execute(), and Clipper2Lib::RectClip::GetNextLocation().
rectPath_
const Path64 Clipper2Lib::RectClip::rectPath_ protected inherited
Referenced by Clipper2Lib::RectClip::AddCorner(), Clipper2Lib::RectClip::AddCorner(), Clipper2Lib::RectClip::Execute(), and Execute().
result_
Path64 Clipper2Lib::RectClip::result_ protected inherited
Referenced by Clipper2Lib::RectClip::AddCorner(), Clipper2Lib::RectClip::AddCorner(), Clipper2Lib::RectClip::Execute(), Execute(), and Clipper2Lib::RectClip::GetNextLocation().
start_locs_
std::vector<Location> Clipper2Lib::RectClip::start_locs_ protected inherited
Referenced by Clipper2Lib::RectClip::Execute().
The documentation for this class was generated from the following files:
src/clipper2/Clipper2Lib/include/clipper2/clipper.rectclip.h
src/clipper2/Clipper2Lib/src/clipper.rectclip.cpp