OrcaSlicer: Slic3r::GUI::Bundle Struct Reference
Slic3r::GUI::Bundle Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
Bundle ()=default
Bundle (Bundle &&other)
bool load (fs::path source_path, bool is_in_resources, bool is_bbl_bundle=false)
const std::string & vendor_id () const
Public Attributes
std::unique_ptr< PresetBundle > preset_bundle
VendorProfile * vendor_profile { nullptr }
bool is_in_resources { false }
bool is_bbl_bundle { false }
Detailed Description
Constructor & Destructor Documentation
Bundle() [1/2]
Slic3r::GUI::Bundle::Bundle () default
Bundle() [2/2]
Slic3r::GUI::Bundle::Bundle (Bundle && other)
    : preset_bundle(std::move(other.preset_bundle))
    , vendor_profile(other.vendor_profile)
    , is_in_resources(other.is_in_resources)
    , is_bbl_bundle(other.is_bbl_bundle)
{
    other.vendor_profile = nullptr;
}
Member Function Documentation
load()
bool Slic3r::GUI::Bundle::load (fs::path source_path, bool is_in_resources, bool is_bbl_bundle = false)
{
    this->preset_bundle = std::make_unique<PresetBundle>();
    this->is_in_resources = ais_in_resources;
    this->is_bbl_bundle = ais_bbl_bundle;
    std::string path_string = source_path.string();
    std::string parent_path = source_path.parent_path().string();
    //BBS: add json logic for vendor bundles
    std::string vendor_name = source_path.filename().string();
    if (Slic3r::is_json_file(path_string)) {
        // Remove the .json suffix.
        vendor_name.erase(vendor_name.size() - 5);
    }
    else
        return false;
    // Throw when parsing invalid configuration. Only valid configuration is supposed to be provided over the air.
    //BBS: add json logic for vendor bundles
    auto [config_substitutions, presets_loaded] = preset_bundle->load_vendor_configs_from_json(
        parent_path, vendor_name, PresetBundle::LoadConfigBundleAttribute::LoadSystem, ForwardCompatibilitySubstitutionRule::Disable);
    UNUSED(config_substitutions);
    // No substitutions shall be reported when loading a system config bundle, no substitutions are allowed.
    assert(config_substitutions.empty());
    auto first_vendor = preset_bundle->vendors.begin();
    if (first_vendor == preset_bundle->vendors.end()) {
        BOOST_LOG_TRIVIAL(error) << boost::format("Vendor bundle: `%1%`: No vendor information defined, cannot install.") % path_string;
        return false;
    }
    if (presets_loaded == 0) {
        BOOST_LOG_TRIVIAL(error) << boost::format("Vendor bundle: `%1%`: No profile loaded.") % path_string;
        return false;
    }
    BOOST_LOG_TRIVIAL(trace) << boost::format("Vendor bundle: `%1%`: %2% profiles loaded.") % path_string % presets_loaded;
    this->vendor_profile = &first_vendor->second;
    return true;
}
References Slic3r::Disable, error, is_bbl_bundle, is_in_resources, Slic3r::is_json_file(), Slic3r::PresetBundle::LoadSystem, preset_bundle, Slic3r::trace(), UNUSED, and vendor_profile.
Referenced by Slic3r::GUI::BundleMap::load().
vendor_id()
const std::string & Slic3r::GUI::Bundle::vendor_id () const inline
{ return vendor_profile->id; }
References Slic3r::VendorProfile::id, and vendor_profile.
Member Data Documentation
is_bbl_bundle
bool Slic3r::GUI::Bundle::is_bbl_bundle { false }
Referenced by load().
is_in_resources
bool Slic3r::GUI::Bundle::is_in_resources { false }
Referenced by load().
preset_bundle
std::unique_ptr<PresetBundle> Slic3r::GUI::Bundle::preset_bundle
Referenced by load().
vendor_profile
VendorProfile* Slic3r::GUI::Bundle::vendor_profile { nullptr }
Referenced by load(), and vendor_id().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp