OrcaSlicer: Slic3r::GUI::ProjectDirtyStateManager Class Reference
Slic3r::GUI::ProjectDirtyStateManager Class Reference
#include <src/slic3r/GUI/ProjectDirtyStateManager.hpp>
Public Member Functions
void update_from_undo_redo_stack (bool dirty)
void update_from_presets ()
void reset_after_save ()
void reset_initial_presets ()
void set_plater_dirty (bool is_dirty)
bool is_dirty () const
bool is_presets_dirty () const
Private Attributes
bool m_plater_dirty { false }
bool m_presets_dirty { false }
bool m_project_config_dirty { false }
std::array< std::string, Preset::TYPE_COUNT > m_initial_presets
DynamicPrintConfig m_initial_project_config
std::vector< std::string > m_initial_filament_presets_names
std::vector< std::string > m_initial_filament_presets_colors
Detailed Description
Member Function Documentation
is_dirty()
bool Slic3r::GUI::ProjectDirtyStateManager::is_dirty () const inline
{ return m_plater_dirty || m_project_config_dirty || m_presets_dirty; }
References m_plater_dirty, m_presets_dirty, and m_project_config_dirty.
Referenced by Slic3r::GUI::Plater::priv::is_project_dirty(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), and set_plater_dirty().
is_presets_dirty()
bool Slic3r::GUI::ProjectDirtyStateManager::is_presets_dirty () const inline
{ return m_presets_dirty; }
References m_presets_dirty.
Referenced by Slic3r::GUI::Plater::priv::is_presets_dirty().
reset_after_save()
void Slic3r::GUI::ProjectDirtyStateManager::reset_after_save ()
{
    this->reset_initial_presets();
    m_plater_dirty  = false;
    m_presets_dirty = false;
    m_project_config_dirty = false;
    wxGetApp().mainframe->update_title();
}
References m_plater_dirty, m_presets_dirty, m_project_config_dirty, and reset_initial_presets().
Referenced by Slic3r::GUI::Plater::priv::reset_project_dirty_after_save().
reset_initial_presets()
void Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets ()
{
    m_initial_presets.fill(std::string{});
    GUI_App &app = wxGetApp();
    for (const auto &[type, name] : app.get_selected_presets()) {
        if (type == Preset::Type::TYPE_FILAMENT) {
            m_initial_filament_presets_names = wxGetApp().preset_bundle->filament_presets;
            if (ConfigOption *color_option = wxGetApp().preset_bundle->project_config.option("filament_colour")) {
                auto colors = static_cast<ConfigOptionStrings *>(color_option->clone());
                m_initial_filament_presets_colors = colors->values;
            }
        } else {
            m_initial_presets[type] = name;
        }
    }
    m_initial_project_config = app.preset_bundle->project_config;
}
References Slic3r::GUI::GUI_App::get_selected_presets(), m_initial_filament_presets_colors, m_initial_filament_presets_names, m_initial_presets, m_initial_project_config, Slic3r::GUI::GUI_App::preset_bundle, Slic3r::PresetBundle::project_config, and Slic3r::Preset::TYPE_FILAMENT.
Referenced by reset_after_save(), and Slic3r::GUI::Plater::priv::reset_project_dirty_initial_presets().
set_plater_dirty()
void Slic3r::GUI::ProjectDirtyStateManager::set_plater_dirty (bool is_dirty) inline
{ m_plater_dirty = is_dirty; }
References is_dirty(), and m_plater_dirty.
Referenced by Slic3r::GUI::Plater::priv::set_plater_dirty().
update_from_presets()
void Slic3r::GUI::ProjectDirtyStateManager::update_from_presets ()
{
    m_presets_dirty = false;
    // check switching of the presets only for exist/loaded project, but not for new
    GUI_App &app = wxGetApp();
    if (!app.plater()->get_project_filename().IsEmpty()) {
        for (const auto &[type, name] : app.get_selected_presets()) {
            if (type == Preset::Type::TYPE_FILAMENT) {
                m_presets_dirty |= m_initial_filament_presets_names != wxGetApp().preset_bundle->filament_presets;
                if (ConfigOption *color_option = wxGetApp().preset_bundle->project_config.option("filament_colour")) {
                    auto colors = static_cast<ConfigOptionStrings *>(color_option->clone());
                    m_presets_dirty |= m_initial_filament_presets_colors != colors->values;
                }
            } else {
                m_presets_dirty |= !m_initial_presets[type].empty() && m_initial_presets[type] != name;
            }
        }
    }
    m_presets_dirty |= app.has_unsaved_preset_changes();
    m_project_config_dirty = m_initial_project_config != app.preset_bundle->project_config;
    app.mainframe->update_title();
}
References Slic3r::GUI::Plater::get_project_filename(), Slic3r::GUI::GUI_App::get_selected_presets(), Slic3r::GUI::GUI_App::has_unsaved_preset_changes(), m_initial_filament_presets_colors, m_initial_filament_presets_names, m_initial_presets, m_initial_project_config, m_presets_dirty, m_project_config_dirty, Slic3r::GUI::GUI_App::mainframe, Slic3r::GUI::GUI_App::plater(), Slic3r::GUI::GUI_App::preset_bundle, Slic3r::PresetBundle::project_config, Slic3r::Preset::TYPE_FILAMENT, and Slic3r::GUI::MainFrame::update_title().
Referenced by Slic3r::GUI::Plater::priv::update_project_dirty_from_presets().
update_from_undo_redo_stack()
void Slic3r::GUI::ProjectDirtyStateManager::update_from_undo_redo_stack (bool dirty)
{
    if (!m_plater_dirty)
        m_plater_dirty = dirty;
    if (const Plater *plater = wxGetApp().plater(); plater && wxGetApp().initialized())
        wxGetApp().mainframe->update_title();
}
References m_plater_dirty, and Slic3r::GUI::plater().
Member Data Documentation
m_initial_filament_presets_colors
std::vector<std::string> Slic3r::GUI::ProjectDirtyStateManager::m_initial_filament_presets_colors private
Referenced by reset_initial_presets(), and update_from_presets().
m_initial_filament_presets_names
std::vector<std::string> Slic3r::GUI::ProjectDirtyStateManager::m_initial_filament_presets_names private
Referenced by reset_initial_presets(), and update_from_presets().
m_initial_presets
std::array<std::string, Preset::TYPE_COUNT> Slic3r::GUI::ProjectDirtyStateManager::m_initial_presets private
Referenced by reset_initial_presets(), and update_from_presets().
m_initial_project_config
DynamicPrintConfig Slic3r::GUI::ProjectDirtyStateManager::m_initial_project_config private
Referenced by reset_initial_presets(), and update_from_presets().
m_plater_dirty
bool Slic3r::GUI::ProjectDirtyStateManager::m_plater_dirty { false } private
Referenced by is_dirty(), reset_after_save(), set_plater_dirty(), and update_from_undo_redo_stack().
m_presets_dirty
bool Slic3r::GUI::ProjectDirtyStateManager::m_presets_dirty { false } private
Referenced by is_dirty(), is_presets_dirty(), reset_after_save(), and update_from_presets().
m_project_config_dirty
bool Slic3r::GUI::ProjectDirtyStateManager::m_project_config_dirty { false } private
Referenced by is_dirty(), reset_after_save(), and update_from_presets().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ProjectDirtyStateManager.hpp
src/slic3r/GUI/ProjectDirtyStateManager.cpp