OrcaSlicer: array_iterator_t< V > Class Template Reference
array_iterator_t< V > Class Template Reference
#include <src/mcut/include/mcut/internal/hmesh.h>
Public Member Functions
array_iterator_t ()
array_iterator_t (typename V::const_iterator it_, const hmesh_t *const mesh)
const hmesh_t * get_mesh_ptr () const
V::value_type::type operator* ()
array_iterator_t< V > & operator++ ()
array_iterator_t< V > & operator+= (std::ptrdiff_t n)
template<typename I = array_iterator_t<V>>
I cend ()
template<typename I = array_iterator_t<V>>
I cbegin (bool account_for_removed_elems)
Private Types
typedef V::const_iterator std_iterator_base_class
typedef V::value_type::type element_descriptor_type
Private Member Functions
V::value_type * operator-> ()=delete
array_iterator_t< V > operator++ (int)
template<typename I = array_iterator_t<V>>
I cend (id_< I >)
template<typename I = array_iterator_t<V>>
I cbegin (bool account_for_removed_elems, id_< I >)
vertex_array_iterator_t cbegin (bool account_for_removed_elems, id_< vertex_array_iterator_t >={})
vertex_array_iterator_t cend (id_< vertex_array_iterator_t >)
edge_array_iterator_t cbegin (bool account_for_removed_elems, id_< edge_array_iterator_t >={})
edge_array_iterator_t cend (id_< edge_array_iterator_t >)
halfedge_array_iterator_t cbegin (bool account_for_removed_elems, id_< halfedge_array_iterator_t >={})
halfedge_array_iterator_t cend (id_< halfedge_array_iterator_t >)
face_array_iterator_t cbegin (bool account_for_removed_elems, id_< face_array_iterator_t >={})
face_array_iterator_t cend (id_< face_array_iterator_t >)
Private Attributes
const hmesh_t * mesh_ptr
Detailed Description
template<typename V = face_array_t>
class array_iterator_t< V >
Member Typedef Documentation
element_descriptor_type
template<typename V = face_array_t> typedef V::value_type::type array_iterator_t< V >::element_descriptor_type private
std_iterator_base_class
template<typename V = face_array_t> typedef V::const_iterator array_iterator_t< V >::std_iterator_base_class private
Constructor & Destructor Documentation
array_iterator_t() [1/2]
template<typename V = face_array_t> array_iterator_t< V >::array_iterator_t () inline
        : V::const_iterator()
        , mesh_ptr(nullptr) {};
array_iterator_t() [2/2]
template<typename V = face_array_t> array_iterator_t< V >::array_iterator_t (typename V::const_iterator it_, const hmesh_t *const mesh) inline
        : V::const_iterator(it_)
        , mesh_ptr(mesh)
    {
    }
Member Function Documentation
cbegin() [1/6]
template<typename V = face_array_t> template<typename I = array_iterator_t<V>> I array_iterator_t< V >::cbegin (bool account_for_removed_elems) inline
    {
        return cbegin(account_for_removed_elems, id_<I>());
    }
References array_iterator_t< V >::cbegin().
Referenced by array_iterator_t< V >::cbegin().
cbegin() [2/6]
edge_array_iterator_t edge_array_iterator_t::cbegin (bool account_for_removed_elems, id_< edge_array_iterator_t< V > > = {}) private
{
    return mesh_ptr->edges_begin(account_for_removed_elems);
}
References hmesh_t::edges_begin(), and array_iterator_t< V >::mesh_ptr.
cbegin() [3/6]
face_array_iterator_t face_array_iterator_t::cbegin (bool account_for_removed_elems, id_< face_array_iterator_t< V > > = {}) private
{
    return mesh_ptr->faces_begin(account_for_removed_elems);
}
References hmesh_t::faces_begin(), and array_iterator_t< V >::mesh_ptr.
cbegin() [4/6]
halfedge_array_iterator_t halfedge_array_iterator_t::cbegin (bool account_for_removed_elems, id_< halfedge_array_iterator_t< V > > = {}) private
{
    return mesh_ptr->halfedges_begin(account_for_removed_elems);
}
References hmesh_t::halfedges_begin(), and array_iterator_t< V >::mesh_ptr.
cbegin() [5/6]
template<typename V = face_array_t> template<typename I = array_iterator_t<V>> I array_iterator_t< V >::cbegin (bool account_for_removed_elems, id_< I >) inline private
    {
        return I(account_for_removed_elems); // unused stub
    }
cbegin() [6/6]
vertex_array_iterator_t vertex_array_iterator_t::cbegin (bool account_for_removed_elems, id_< vertex_array_iterator_t< V > > = {}) private
{
    return mesh_ptr->vertices_begin(account_for_removed_elems);
}
References array_iterator_t< V >::mesh_ptr, and hmesh_t::vertices_begin().
cend() [1/6]
template<typename V = face_array_t> template<typename I = array_iterator_t<V>> I array_iterator_t< V >::cend () inline
    {
        return cend(id_<I>()); // https://stackoverflow.com/questions/3052579/explicit-specialization-in-non-namespace-scope
    }
References array_iterator_t< V >::cend().
Referenced by array_iterator_t< V >::cend().
cend() [2/6]
edge_array_iterator_t edge_array_iterator_t::cend (id_< edge_array_iterator_t< V > >) private
{
    return mesh_ptr->edges_end();
}
References hmesh_t::edges_end(), and array_iterator_t< V >::mesh_ptr.
cend() [3/6]
face_array_iterator_t face_array_iterator_t::cend (id_< face_array_iterator_t< V > >) private
{
    return mesh_ptr->faces_end();
}
References hmesh_t::faces_end(), and array_iterator_t< V >::mesh_ptr.
cend() [4/6]
halfedge_array_iterator_t halfedge_array_iterator_t::cend (id_< halfedge_array_iterator_t< V > >) private
{
    return mesh_ptr->halfedges_end();
}
References hmesh_t::halfedges_end(), and array_iterator_t< V >::mesh_ptr.
cend() [5/6]
template<typename V = face_array_t> template<typename I = array_iterator_t<V>> I array_iterator_t< V >::cend (id_< I >) inline private
    {
        return I(); // unused stub
    }
cend() [6/6]
vertex_array_iterator_t vertex_array_iterator_t::cend (id_< vertex_array_iterator_t< V > >) private
{
    return mesh_ptr->vertices_end();
}
References array_iterator_t< V >::mesh_ptr, and hmesh_t::vertices_end().
get_mesh_ptr()
template<typename V = face_array_t> const hmesh_t * array_iterator_t< V >::get_mesh_ptr () const inline
    {
        return mesh_ptr;
    }
References array_iterator_t< V >::mesh_ptr.
Referenced by std::distance().
operator*()
template<typename V = face_array_t> V::value_type::type array_iterator_t< V >::operator* () inline
    {
        size_t raw_index = (*this) - cbegin<>(false);
        element_descriptor_type d((std::uint32_t)raw_index);
        return d;
    }
operator++() [1/2]
template<typename V = face_array_t> array_iterator_t< V > & array_iterator_t< V >::operator++ () inline
    {
        bool cur_elem_is_removed = false;
        bool reached_end = false;
        do {
            V::const_iterator::operator++();
            reached_end = (*this) == cend<>();
            cur_elem_is_removed = false;
            if (!reached_end) {
                const std::size_t diff = ((*this) - cbegin<array_iterator_t<V>>(false));
                element_descriptor_type raw_descriptor((std::uint32_t)diff); // std::distance(cbegin<array_iterator_t<V>>(false), (*this)); // O(1) ??
                cur_elem_is_removed = mesh_ptr->is_removed(raw_descriptor);
                if (!cur_elem_is_removed) {
                    break;
                }
            }
            // keep iterating until the value pointed to after the (++i) operator is a valid element
            // i.e. one that is not marked removed!
        } while (cur_elem_is_removed && !reached_end);
        return (*this);
    }
References hmesh_t::is_removed(), and array_iterator_t< V >::mesh_ptr.
operator++() [2/2]
template<typename V = face_array_t> array_iterator_t< V > array_iterator_t< V >::operator++ (int) inline private
    {
        MCUT_ASSERT(false);
        return cend<>();
    }
References MCUT_ASSERT.
operator+=()
template<typename V = face_array_t> array_iterator_t< V > & array_iterator_t< V >::operator+= (std::ptrdiff_t n) inline
    {
        V::const_iterator::operator+=(n); // raw ptr shift (i.e. ignoring that there may be removed elements)
        bool cur_elem_is_removed = false;
        bool reached_end = (*this) == cend<>();
        cur_elem_is_removed = mesh_ptr->is_removed(*(*this));
        while (!reached_end && cur_elem_is_removed) {
            V::const_iterator::operator++(); //++(*this);
            size_t raw_descriptor = *(*this); // (*this) - cbegin<array_iterator_t<V>>(false); //std::distance(cbegin<array_iterator_t<V>>(false), (*this)); // O(1) ??
            cur_elem_is_removed = mesh_ptr->is_removed(element_descriptor_type((std::uint32_t)raw_descriptor));
            if (!cur_elem_is_removed) {
                break;
            }
            reached_end = (*this) == cend<>();
        }
        return *this;
    }
References hmesh_t::is_removed(), array_iterator_t< V >::mesh_ptr, and n.
operator->()
template<typename V = face_array_t> V::value_type * array_iterator_t< V >::operator-> () private delete
Member Data Documentation
mesh_ptr
template<typename V = face_array_t> const hmesh_t* array_iterator_t< V >::mesh_ptr private
Referenced by array_iterator_t< V >::cbegin(), array_iterator_t< V >::cbegin(), array_iterator_t< V >::cbegin(), array_iterator_t< V >::cbegin(), array_iterator_t< V >::cend(), array_iterator_t< V >::cend(), array_iterator_t< V >::cend(), array_iterator_t< V >::cend(), array_iterator_t< V >::get_mesh_ptr(), array_iterator_t< V >::operator++(), and array_iterator_t< V >::operator+=().
The documentation for this class was generated from the following files:
src/mcut/include/mcut/internal/hmesh.h
src/mcut/source/hmesh.cpp