OrcaSlicer: Slic3r::GUI::GLGizmosManager Class Reference
Slic3r::GUI::GLGizmosManager Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosManager.hpp>
Classes
struct Layout
struct MouseCapture
Public Types
enum EType : unsigned char {
Move , Rotate , Scale , Flatten ,
Cut , MeshBoolean , FdmSupports , Seam ,
Text , MmuSegmentation , Simplify , SlaSupports ,
Hollow , Undefined
}
enum MENU_ICON_NAME {
IC_TOOLBAR_RESET = 0 , IC_TOOLBAR_RESET_HOVER , IC_TOOLBAR_TOOLTIP , IC_TOOLBAR_TOOLTIP_HOVER ,
IC_TEXT_B , IC_TEXT_B_DARK , IC_TEXT_T , IC_TEXT_T_DARK ,
IC_NAME_COUNT
}
using Timestamp = uint64_t
Public Member Functions
GLGizmosManager (GLCanvas3D &parent)
void switch_gizmos_icon_filename ()
bool init ()
bool init_icon_textures ()
float get_layout_scale ()
bool init_arrow (const BackgroundTexture::Metadata &arrow_texture)
template<class Archive >
void load (Archive &ar)
template<class Archive >
void save (Archive &ar) const
bool is_enabled () const
void set_enabled (bool enable)
void set_icon_dirty ()
void set_overlay_icon_size (float size)
void set_overlay_scale (float scale)
void refresh_on_off_state ()
void reset_all_states ()
bool is_serializing () const
bool open_gizmo (EType type)
bool check_gizmos_closed_except (EType) const
void set_hover_id (int id)
void enable_grabber (EType type, unsigned int id, bool enable)
void update (const Linef3 &mouse_ray, const Point &mouse_pos)
void update_data ()
void update_assemble_view_data ()
EType get_current_type () const
GLGizmoBase * get_current () const
GLGizmoBase * get_gizmo (GLGizmosManager::EType type) const
EType get_gizmo_from_name (const std::string &gizmo_name) const
bool is_running () const
bool handle_shortcut (int key)
bool is_dragging () const
void start_dragging ()
void stop_dragging ()
Vec3d get_displacement () const
Vec3d get_scale () const
void set_scale (const Vec3d &scale)
Vec3d get_scale_offset () const
Vec3d get_rotation () const
void set_rotation (const Vec3d &rotation)
void finish_cut_rotation ()
void * get_icon_texture_id (MENU_ICON_NAME icon)
void * get_icon_texture_id (MENU_ICON_NAME icon) const
Vec3d get_flattening_normal () const
void set_flattening_data (const ModelObject *model_object)
void set_sla_support_data (ModelObject *model_object)
void set_painter_gizmo_data ()
bool gizmo_event (SLAGizmoEventType action, const Vec2d &mouse_position=Vec2d::Zero(), bool shift_down=false, bool alt_down=false, bool control_down=false)
ClippingPlane get_clipping_plane () const
ClippingPlane get_assemble_view_clipping_plane () const
bool wants_reslice_supports_on_undo () const
bool is_in_editing_mode (bool error_notification=false) const
bool is_hiding_instances () const
void on_change_color_mode (bool is_dark)
void render_current_gizmo () const
void render_current_gizmo_for_picking_pass () const
void render_painter_gizmo () const
void render_painter_assemble_view () const
void render_overlay ()
void render_arrow (const GLCanvas3D &parent, EType highlighted_type) const
std::string get_tooltip () const
bool on_mouse (wxMouseEvent &evt)
bool on_mouse_wheel (wxMouseEvent &evt)
bool on_char (wxKeyEvent &evt)
bool on_key (wxKeyEvent &evt)
void update_after_undo_redo (const UndoRedo::Snapshot &snapshot)
int get_selectable_icons_cnt () const
int get_shortcut_key (GLGizmosManager::EType) const
void set_highlight (EType gizmo, bool highlight_shown)
bool get_highlight_state () const
float get_scaled_total_height () const
float get_scaled_total_width () const
GizmoObjectManipulation & get_object_manipulation ()
bool get_uniform_scaling () const
ObjectID id () const
virtual Timestamp timestamp () const
Public Attributes
std::unique_ptr< AssembleViewDataPool > m_assemble_view_data
Static Public Attributes
static const float Default_Icons_Size
Protected Member Functions
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
std::vector< size_t > get_selectable_idxs () const
size_t get_gizmo_idx_from_mouse (const Vec2d &mouse_pos) const
bool activate_gizmo (EType type)
void render_background (float left, float top, float right, float bottom, float border) const
void do_render_overlay () const
bool generate_icons_texture () const
void update_on_off_state (const Vec2d &mouse_pos)
std::string update_hover_state (const Vec2d &mouse_pos)
bool grabber_contains_mouse () const
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
GLCanvas3D & m_parent
bool m_enabled
std::vector< std::unique_ptr< GLGizmoBase > > m_gizmos
GLTexture m_icons_texture
bool m_icons_texture_dirty
BackgroundTexture m_background_texture
BackgroundTexture m_arrow_texture
Layout m_layout
EType m_current
EType m_hover
std::pair< EType, bool > m_highlight
GizmoObjectManipulation m_object_manipulation
MouseCapture m_mouse_capture
std::string m_tooltip
bool m_serializing
std::unique_ptr< CommonGizmosDataPool > m_common_gizmos_data
std::map< int, void * > icon_list
bool m_is_dark = false
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Member Enumeration Documentation
EType
enum Slic3r::GUI::GLGizmosManager::EType : unsigned char
Enumerator
Move
Rotate
Scale
Flatten
Cut
MeshBoolean
FdmSupports
Seam
Text
MmuSegmentation
Simplify
SlaSupports
Hollow
Undefined
    {
        // Order must match index in m_gizmos!
        Move,
        Rotate,
        Scale,
        Flatten,
        Cut,
        MeshBoolean,
        FdmSupports,
        Seam,
        // BBS
        Text,
        MmuSegmentation,
        Simplify,
        SlaSupports,
        // BBS
        //FaceRecognition,
        Hollow,
        Undefined,
    };
MENU_ICON_NAME
enum Slic3r::GUI::GLGizmosManager::MENU_ICON_NAME
Enumerator
IC_TOOLBAR_RESET
IC_TOOLBAR_RESET_HOVER
IC_TOOLBAR_TOOLTIP
IC_TOOLBAR_TOOLTIP_HOVER
IC_TEXT_B
IC_TEXT_B_DARK
IC_TEXT_T
IC_TEXT_T_DARK
IC_NAME_COUNT
{
        IC_TOOLBAR_RESET            = 0,
        IC_TOOLBAR_RESET_HOVER,
        IC_TOOLBAR_TOOLTIP,
        IC_TOOLBAR_TOOLTIP_HOVER,
        IC_TEXT_B,
        IC_TEXT_B_DARK,
        IC_TEXT_T,
        IC_TEXT_T_DARK,
        IC_NAME_COUNT,
    };
Constructor & Destructor Documentation
GLGizmosManager()
Slic3r::GUI::GLGizmosManager::GLGizmosManager (GLCanvas3D & parent) explicit
Member Function Documentation
activate_gizmo()
bool Slic3r::GUI::GLGizmosManager::activate_gizmo (EType type) private
Referenced by load().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
check_gizmos_closed_except()
bool Slic3r::GUI::GLGizmosManager::check_gizmos_closed_except (EType) const
Referenced by Slic3r::GUI::ObjectList::simplify().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
do_render_overlay()
void Slic3r::GUI::GLGizmosManager::do_render_overlay () const private
enable_grabber()
void Slic3r::GUI::GLGizmosManager::enable_grabber (EType type, unsigned int id, bool enable)
finish_cut_rotation()
void Slic3r::GUI::GLGizmosManager::finish_cut_rotation ()
generate_icons_texture()
bool Slic3r::GUI::GLGizmosManager::generate_icons_texture () const private
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_assemble_view_clipping_plane()
ClippingPlane Slic3r::GUI::GLGizmosManager::get_assemble_view_clipping_plane () const
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
get_clipping_plane()
ClippingPlane Slic3r::GUI::GLGizmosManager::get_clipping_plane () const
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::GLCanvas3D::_render_objects().
get_current()
GLGizmoBase * Slic3r::GUI::GLGizmosManager::get_current () const
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::on_char(), Slic3r::GUI::GLCanvas3D::on_mouse(), and Slic3r::GUI::Plater::priv::take_snapshot().
get_current_type()
EType Slic3r::GUI::GLGizmosManager::get_current_type () const inline
{ return m_current; }
References m_current.
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_sequential_clearance(), Slic3r::GUI::call_after_if_active(), Slic3r::GUI::ObjectList::list_manipulation(), Slic3r::GUI::GLCanvas3D::on_char(), Slic3r::GUI::GLCanvas3D::on_key(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::ObjectList::OnEditingStarted(), Slic3r::GUI::ObjectList::part_selection_changed(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::ObjectList::simplify(), and Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility().
get_displacement()
Vec3d Slic3r::GUI::GLGizmosManager::get_displacement () const
get_flattening_normal()
Vec3d Slic3r::GUI::GLGizmosManager::get_flattening_normal () const
get_gizmo()
GLGizmoBase * Slic3r::GUI::GLGizmosManager::get_gizmo (GLGizmosManager::EType type) const
Referenced by Slic3r::GUI::ObjectList::part_selection_changed().
get_gizmo_from_name()
EType Slic3r::GUI::GLGizmosManager::get_gizmo_from_name (const std::string & gizmo_name) const
get_gizmo_idx_from_mouse()
size_t Slic3r::GUI::GLGizmosManager::get_gizmo_idx_from_mouse (const Vec2d & mouse_pos) const private
get_highlight_state()
bool Slic3r::GUI::GLGizmosManager::get_highlight_state () const inline
{ return m_highlight.second; }
References m_highlight.
get_icon_texture_id() [1/2]
void * Slic3r::GUI::GLGizmosManager::get_icon_texture_id (MENU_ICON_NAME icon) inline
{
        if (icon_list.find((int)icon) != icon_list.end())
            return icon_list[icon];
        else
            return nullptr;
    }
References icon_list.
Referenced by Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GizmoObjectManipulation::reset_button(), Slic3r::GUI::GLCanvas3D::LayersEditing::show_tooltip_information(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::show_tooltip_information().
get_icon_texture_id() [2/2]
void * Slic3r::GUI::GLGizmosManager::get_icon_texture_id (MENU_ICON_NAME icon) const inline
{
        if (icon_list.find((int)icon) != icon_list.end())
            return icon_list.at(icon);
        else
            return nullptr;
    }
References icon_list.
get_layout_scale()
float Slic3r::GUI::GLGizmosManager::get_layout_scale ()
Referenced by Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), and Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window().
get_object_manipulation()
GizmoObjectManipulation & Slic3r::GUI::GLGizmosManager::get_object_manipulation () inline
{ return m_object_manipulation; }
References m_object_manipulation.
get_rotation()
Vec3d Slic3r::GUI::GLGizmosManager::get_rotation () const
get_scale()
Vec3d Slic3r::GUI::GLGizmosManager::get_scale () const
get_scale_offset()
Vec3d Slic3r::GUI::GLGizmosManager::get_scale_offset () const
get_scaled_total_height()
float Slic3r::GUI::GLGizmosManager::get_scaled_total_height () const
Referenced by Slic3r::GUI::GLCanvas3D::_render_assemble_view_toolbar(), and Slic3r::GUI::GLCanvas3D::_render_main_toolbar().
get_scaled_total_width()
float Slic3r::GUI::GLGizmosManager::get_scaled_total_width () const
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), Slic3r::GUI::GLCanvas3D::_render_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_render_main_toolbar(), Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_left(), and Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_right().
get_selectable_icons_cnt()
int Slic3r::GUI::GLGizmosManager::get_selectable_icons_cnt () const inline
{ return get_selectable_idxs().size(); }
References get_selectable_idxs().
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale().
get_selectable_idxs()
std::vector< size_t > Slic3r::GUI::GLGizmosManager::get_selectable_idxs () const private
Referenced by get_selectable_icons_cnt().
get_shortcut_key()
int Slic3r::GUI::GLGizmosManager::get_shortcut_key (GLGizmosManager::EType) const
get_tooltip()
std::string Slic3r::GUI::GLGizmosManager::get_tooltip () const
Referenced by Slic3r::GUI::GLCanvas3D::render().
get_uniform_scaling()
bool Slic3r::GUI::GLGizmosManager::get_uniform_scaling () const inline
{ return m_object_manipulation.get_uniform_scaling();}
References Slic3r::GUI::GizmoObjectManipulation::get_uniform_scaling(), and m_object_manipulation.
Referenced by Slic3r::GUI::GLCanvas3D::_render_selection_sidebar_hints().
gizmo_event()
bool Slic3r::GUI::GLGizmosManager::gizmo_event (SLAGizmoEventType action, const Vec2d & mouse_position = Vec2d::Zero(), bool shift_down = false, bool alt_down = false, bool control_down = false)
grabber_contains_mouse()
bool Slic3r::GUI::GLGizmosManager::grabber_contains_mouse () const private
handle_shortcut()
bool Slic3r::GUI::GLGizmosManager::handle_shortcut (int key)
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
init()
bool Slic3r::GUI::GLGizmosManager::init ()
Referenced by Slic3r::GUI::GLCanvas3D::init().
init_arrow()
bool Slic3r::GUI::GLGizmosManager::init_arrow (const BackgroundTexture::Metadata & arrow_texture)
Referenced by Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
init_icon_textures()
bool Slic3r::GUI::GLGizmosManager::init_icon_textures ()
is_dragging()
bool Slic3r::GUI::GLGizmosManager::is_dragging () const
Referenced by Slic3r::GUI::GLCanvas3D::_render_sequential_clearance(), Slic3r::GUI::GLCanvas3D::is_dragging(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
is_enabled()
bool Slic3r::GUI::GLGizmosManager::is_enabled () const inline
{ return m_enabled; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::init(), and Slic3r::GUI::GLCanvas3D::on_key().
is_hiding_instances()
bool Slic3r::GUI::GLGizmosManager::is_hiding_instances () const
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
is_in_editing_mode()
bool Slic3r::GUI::GLGizmosManager::is_in_editing_mode (bool error_notification = false) const
Referenced by Slic3r::GUI::MainFrame::MainFrame().
is_running()
bool Slic3r::GUI::GLGizmosManager::is_running () const
Referenced by Slic3r::GUI::GLCanvas3D::_max_bounding_box(), Slic3r::GUI::GLCanvas3D::_render_selection(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::render(), and Slic3r::GUI::Plater::priv::set_current_panel().
is_serializing()
bool Slic3r::GUI::GLGizmosManager::is_serializing () const inline
{ return m_serializing; }
References m_serializing.
load()
template<class Archive > void Slic3r::GUI::GLGizmosManager::load (Archive & ar) inline
    {
        if (!m_enabled)
            return;
        m_serializing = true;
        // Following is needed to know which to be turn on, but not actually modify
        // m_current prematurely, so activate_gizmo is not confused.
        EType old_current = m_current;
        ar(m_current);
        EType new_current = m_current;
        m_current = old_current;
        // activate_gizmo call sets m_current and calls set_state for the gizmo
        // it does nothing in case the gizmo is already activated
        // it can safely be called for Undefined gizmo
        activate_gizmo(new_current);
        if (m_current != Undefined)
            m_gizmos[m_current]->load(ar);
    }
References activate_gizmo(), m_current, m_enabled, m_gizmos, m_serializing, and Undefined.
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
on_change_color_mode()
void Slic3r::GUI::GLGizmosManager::on_change_color_mode (bool is_dark)
Referenced by Slic3r::GUI::GLCanvas3D::on_change_color_mode().
on_char()
bool Slic3r::GUI::GLGizmosManager::on_char (wxKeyEvent & evt)
Referenced by Slic3r::GUI::GLCanvas3D::on_char().
on_key()
bool Slic3r::GUI::GLGizmosManager::on_key (wxKeyEvent & evt)
Referenced by Slic3r::GUI::GLCanvas3D::on_key().
on_mouse()
bool Slic3r::GUI::GLGizmosManager::on_mouse (wxMouseEvent & evt)
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
on_mouse_wheel()
bool Slic3r::GUI::GLGizmosManager::on_mouse_wheel (wxMouseEvent & evt)
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse_wheel().
open_gizmo()
bool Slic3r::GUI::GLGizmosManager::open_gizmo (EType type)
Referenced by Slic3r::GUI::GLGizmoSimplify::close(), Slic3r::GUI::Plater::edit_text(), Slic3r::GUI::ObjectList::list_manipulation(), Slic3r::GUI::ObjectList::OnEditingStarted(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::simplify().
refresh_on_off_state()
void Slic3r::GUI::GLGizmosManager::refresh_on_off_state ()
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::reload_scene(), and Slic3r::GUI::GLCanvas3D::update_gizmos_on_off_state().
render_arrow()
void Slic3r::GUI::GLGizmosManager::render_arrow (const GLCanvas3D & parent, EType highlighted_type) const
Referenced by Slic3r::GUI::GLCanvas3D::_render_gizmos_overlay().
render_background()
void Slic3r::GUI::GLGizmosManager::render_background (float left, float top, float right, float bottom, float border) const private
render_current_gizmo()
void Slic3r::GUI::GLGizmosManager::render_current_gizmo () const
Referenced by Slic3r::GUI::GLCanvas3D::_render_current_gizmo().
render_current_gizmo_for_picking_pass()
void Slic3r::GUI::GLGizmosManager::render_current_gizmo_for_picking_pass () const
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass().
render_overlay()
void Slic3r::GUI::GLGizmosManager::render_overlay ()
Referenced by Slic3r::GUI::GLCanvas3D::_render_gizmos_overlay().
render_painter_assemble_view()
void Slic3r::GUI::GLGizmosManager::render_painter_assemble_view () const
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
render_painter_gizmo()
void Slic3r::GUI::GLGizmosManager::render_painter_gizmo () const
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
reset_all_states()
void Slic3r::GUI::GLGizmosManager::reset_all_states ()
Referenced by Slic3r::GUI::GLCanvas3D::_render_return_toolbar(), Slic3r::GUI::ObjectList::del_info_item(), Slic3r::GUI::GLCanvas3D::deselect_all(), Slic3r::GUI::GLCanvas3D::handle_layers_data_focus_event(), Slic3r::GUI::ObjectList::list_manipulation(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::ObjectList::OnEditingStarted(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::reset_all_gizmos(), and Slic3r::GUI::Plater::priv::set_current_panel().
save()
template<class Archive > void Slic3r::GUI::GLGizmosManager::save (Archive & ar) const inline
    {
        if (!m_enabled)
            return;
        ar(m_current);
        if (m_current != Undefined && !m_gizmos.empty())
            m_gizmos[m_current]->save(ar);
    }
References m_current, m_enabled, m_gizmos, and Undefined.
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_enabled()
void Slic3r::GUI::GLGizmosManager::set_enabled (bool enable) inline
{ m_enabled = enable; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::enable_gizmos().
set_flattening_data()
void Slic3r::GUI::GLGizmosManager::set_flattening_data (const ModelObject * model_object)
set_highlight()
void Slic3r::GUI::GLGizmosManager::set_highlight (EType gizmo, bool highlight_shown) inline
{ m_highlight = std::pair<EType, bool>(gizmo, highlight_shown); }
References m_highlight.
set_hover_id()
void Slic3r::GUI::GLGizmosManager::set_hover_id (int id)
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::GLCanvas3D::_rectangular_selection_picking_pass().
set_icon_dirty()
void Slic3r::GUI::GLGizmosManager::set_icon_dirty () inline
{ m_icons_texture_dirty = true; }
References m_icons_texture_dirty.
Referenced by Slic3r::GUI::GLCanvas3D::on_change_color_mode().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_overlay_icon_size()
void Slic3r::GUI::GLGizmosManager::set_overlay_icon_size (float size)
Referenced by Slic3r::GUI::GLCanvas3D::_render_overlays().
set_overlay_scale()
void Slic3r::GUI::GLGizmosManager::set_overlay_scale (float scale)
Referenced by Slic3r::GUI::GLCanvas3D::_render_overlays().
set_painter_gizmo_data()
void Slic3r::GUI::GLGizmosManager::set_painter_gizmo_data ()
set_rotation()
void Slic3r::GUI::GLGizmosManager::set_rotation (const Vec3d & rotation)
set_scale()
void Slic3r::GUI::GLGizmosManager::set_scale (const Vec3d & scale)
set_sla_support_data()
void Slic3r::GUI::GLGizmosManager::set_sla_support_data (ModelObject * model_object)
start_dragging()
void Slic3r::GUI::GLGizmosManager::start_dragging ()
stop_dragging()
void Slic3r::GUI::GLGizmosManager::stop_dragging ()
switch_gizmos_icon_filename()
void Slic3r::GUI::GLGizmosManager::switch_gizmos_icon_filename ()
Referenced by Slic3r::GUI::GLCanvas3D::on_change_color_mode().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
update()
void Slic3r::GUI::GLGizmosManager::update (const Linef3 & mouse_ray, const Point & mouse_pos)
update_after_undo_redo()
void Slic3r::GUI::GLGizmosManager::update_after_undo_redo (const UndoRedo::Snapshot & snapshot)
update_assemble_view_data()
void Slic3r::GUI::GLGizmosManager::update_assemble_view_data ()
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene().
update_data()
void Slic3r::GUI::GLGizmosManager::update_data ()
Referenced by Slic3r::GUI::GLCanvas3D::deselect_all(), Slic3r::GUI::GLCanvas3D::on_key(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::Plater::priv::set_current_panel(), and Slic3r::GUI::GLCanvas3D::update_gizmos_on_off_state().
update_hover_state()
std::string Slic3r::GUI::GLGizmosManager::update_hover_state (const Vec2d & mouse_pos) private
update_on_off_state()
void Slic3r::GUI::GLGizmosManager::update_on_off_state (const Vec2d & mouse_pos) private
wants_reslice_supports_on_undo()
bool Slic3r::GUI::GLGizmosManager::wants_reslice_supports_on_undo () const
Member Data Documentation
Default_Icons_Size
const float Slic3r::GUI::GLGizmosManager::Default_Icons_Size static
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), Slic3r::GUI::GLCanvas3D::_render_main_toolbar(), and Slic3r::GUI::GLCanvas3D::_render_overlays().
icon_list
std::map<int, void*> Slic3r::GUI::GLGizmosManager::icon_list private
Referenced by get_icon_texture_id(), and get_icon_texture_id().
m_arrow_texture
BackgroundTexture Slic3r::GUI::GLGizmosManager::m_arrow_texture private
m_assemble_view_data
std::unique_ptr<AssembleViewDataPool> Slic3r::GUI::GLGizmosManager::m_assemble_view_data
Referenced by Slic3r::GUI::GLCanvas3D::_render_assemble_control(), Slic3r::GUI::GLCanvas3D::_render_objects(), and Slic3r::GUI::GLCanvas3D::on_mouse_wheel().
m_background_texture
BackgroundTexture Slic3r::GUI::GLGizmosManager::m_background_texture private
m_common_gizmos_data
std::unique_ptr<CommonGizmosDataPool> Slic3r::GUI::GLGizmosManager::m_common_gizmos_data private
m_current
EType Slic3r::GUI::GLGizmosManager::m_current private
Referenced by get_current_type(), load(), and save().
m_enabled
bool Slic3r::GUI::GLGizmosManager::m_enabled private
Referenced by is_enabled(), load(), save(), and set_enabled().
m_gizmos
std::vector<std::unique_ptr<GLGizmoBase> > Slic3r::GUI::GLGizmosManager::m_gizmos private
Referenced by load(), and save().
m_highlight
std::pair<EType, bool> Slic3r::GUI::GLGizmosManager::m_highlight private
Referenced by get_highlight_state(), and set_highlight().
m_hover
EType Slic3r::GUI::GLGizmosManager::m_hover private
m_icons_texture
GLTexture Slic3r::GUI::GLGizmosManager::m_icons_texture mutable private
m_icons_texture_dirty
bool Slic3r::GUI::GLGizmosManager::m_icons_texture_dirty mutable private
Referenced by set_icon_dirty().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_is_dark
bool Slic3r::GUI::GLGizmosManager::m_is_dark = false private
m_layout
Layout Slic3r::GUI::GLGizmosManager::m_layout private
m_mouse_capture
MouseCapture Slic3r::GUI::GLGizmosManager::m_mouse_capture private
m_object_manipulation
GizmoObjectManipulation Slic3r::GUI::GLGizmosManager::m_object_manipulation private
Referenced by get_object_manipulation(), and get_uniform_scaling().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmosManager::m_parent private
m_serializing
bool Slic3r::GUI::GLGizmosManager::m_serializing private
Referenced by is_serializing(), and load().
m_tooltip
std::string Slic3r::GUI::GLGizmosManager::m_tooltip private
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Gizmos/GLGizmosManager.hpp