OrcaSlicer: Slic3r::GUI::GLGizmoHollow Class Reference
Slic3r::GUI::GLGizmoHollow Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoHollow.hpp>
Public Types
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoHollow (GLCanvas3D &parent, const std::string &icon_filename, unsigned int sprite_id)
virtual ~GLGizmoHollow ()=default
void set_sla_support_data (ModelObject *model_object, const Selection &selection)
bool gizmo_event (SLAGizmoEventType action, const Vec2d &mouse_position, bool shift_down, bool alt_down, bool control_down)
void delete_selected_points ()
bool is_selection_rectangle_dragging () const
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
int get_group_id () const
void set_group_id (int id)
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
void set_icon_filename (const std::string &filename)
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
virtual bool wants_enter_leave_snapshots () const
virtual std::string get_gizmo_entering_text () const
virtual std::string get_gizmo_leaving_text () const
virtual std::string get_action_snapshot_name ()
void set_common_data_pool (CommonGizmosDataPool *ptr)
virtual bool apply_clipping_plane ()
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
void set_highlight_color (const std::array< float, 4 > &color)
void enable_grabber (unsigned int id)
void disable_grabber (unsigned int id)
void start_dragging ()
void stop_dragging ()
bool is_dragging () const
void update (const UpdateData &data)
bool update_items_state ()
void render ()
void render_for_picking ()
void render_input_window (float x, float y, float bottom_limit)
virtual void on_change_color_mode (bool is_dark)
virtual std::string get_tooltip () const
int get_count ()
std::string get_gizmo_name ()
Static Public Member Functions
static void update_render_colors ()
static void load_render_colors ()
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static float INV_ZOOM = 1.0f
static std::array< float, 4 > DEFAULT_BASE_COLOR = { 0.625f, 0.625f, 0.625f, 1.0f }
static std::array< float, 4 > DEFAULT_DRAG_COLOR = { 1.0f, 1.0f, 1.0f, 1.0f }
static std::array< float, 4 > DEFAULT_HIGHLIGHT_COLOR = { 1.0f, 0.38f, 0.0f, 1.0f }
static std::array< std::array< float, 4 >, 3 > AXES_COLOR
static std::array< std::array< float, 4 >, 3 > AXES_HOVER_COLOR
static std::array< float, 4 > CONSTRAINED_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f }
static std::array< float, 4 > FLATTEN_COLOR = { 0.96f, 0.93f, 0.93f, 0.5f }
static std::array< float, 4 > FLATTEN_HOVER_COLOR = { 1.0f, 1.0f, 1.0f, 0.75f }
static std::array< float, 4 > GRABBER_NORMAL_COL = {1.0f, 1.0f, 1.0f, 1.0f}
static std::array< float, 4 > GRABBER_HOVER_COL = {0.863f, 0.125f, 0.063f, 1.0f}
static std::array< float, 4 > GRABBER_UNIFORM_COL = {0, 1.0, 1.0, 1.0f}
static std::array< float, 4 > GRABBER_UNIFORM_HOVER_COL = {0, 0.7, 0.7, 1.0f}
Protected Member Functions
void on_set_state () override
void on_set_hover_id () override
void on_start_dragging () override
void on_stop_dragging () override
void on_render_input_window (float x, float y, float bottom_limit) override
virtual CommonGizmosDataID on_get_requirements () const override
std::string on_get_name () const override
bool on_is_activable () const override
bool on_is_selectable () const override
void on_load (cereal::BinaryInputArchive &ar) override
void on_save (cereal::BinaryOutputArchive &ar) const override
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
bool GizmoImguiBegin (const std::string &name, int flags)
void GizmoImguiEnd ()
void GizmoImguiSetNextWIndowPos (float &x, float y, int flag, float pivot_x=0.0f, float pivot_y=0.0f)
std::array< float, 4 > picking_color_component (unsigned int id) const
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers_for_picking (const BoundingBoxf3 &box) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
Protected Attributes
GLCanvas3D & m_parent
int m_group_id
EState m_state
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id
bool m_dragging
std::array< float, 4 > m_base_color
std::array< float, 4 > m_drag_color
std::array< float, 4 > m_highlight_color
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render
std::string m_tooltip
CommonGizmosDataPool * m_c
GLModel m_cone
GLModel m_cylinder
GLModel m_sphere
bool m_is_dark_mode = false
float last_input_window_width = 0
Private Types
enum { AllPoints = -2 , NoPoints }
Private Member Functions
bool unproject_on_mesh (const Vec2d &mouse_pos, std::pair< Vec3f, Vec3f > &pos_and_normal)
bool on_init () override
void on_update (const UpdateData &data) override
void on_render () override
void on_render_for_picking () override
void render_points (const Selection &selection, bool picking=false) const
void hollow_mesh (bool postpone_error_messages=false)
bool unsaved_changes () const
std::vector< std::pair< const ConfigOption *, const ConfigOptionDef * > > get_config_options (const std::vector< std::string > &keys) const
bool is_mesh_point_clipped (const Vec3d &point) const
void select_point (int i)
void unselect_point (int i)
void reload_cache ()
Private Attributes
ObjectID m_old_mo_id = -1
GLModel m_vbo_cylinder
float m_new_hole_radius = 2.f
float m_new_hole_height = 6.f
std::vector< bool > m_selected
bool m_enable_hollowing = true
float m_offset_stash = 3.0f
float m_quality_stash = 0.5f
float m_closing_d_stash = 2.f
Vec3f m_hole_before_drag = Vec3f::Zero()
sla::DrainHoles m_holes_in_drilled_mesh
sla::DrainHoles m_holes_stash
std::map< std::string, wxString > m_desc
GLSelectionRectangle m_selection_rectangle
bool m_wait_for_up_event = false
bool m_selection_empty = true
EState m_old_state = Off
bool m_dirty
int count = 0
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
AllPoints
NoPoints
         {
        AllPoints = -2,
        NoPoints,
    };
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
Constructor & Destructor Documentation
GLGizmoHollow()
Slic3r::GUI::GLGizmoHollow::GLGizmoHollow (GLCanvas3D & parent, const std::string & icon_filename, unsigned int sprite_id)
    : GLGizmoBase(parent, icon_filename, sprite_id)
{
    m_vbo_cylinder.init_from(its_make_cylinder(1., 1.));
}
References Slic3r::GUI::GLModel::init_from(), Slic3r::its_make_cylinder(), and m_vbo_cylinder.
~GLGizmoHollow()
virtual Slic3r::GUI::GLGizmoHollow::~GLGizmoHollow () virtual default
Member Function Documentation
apply_clipping_plane()
virtual bool Slic3r::GUI::GLGizmoBase::apply_clipping_plane () inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut.
{ return true; }
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
delete_selected_points()
void Slic3r::GUI::GLGizmoHollow::delete_selected_points ()
{
    Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Delete drainage hole");
    sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    for (unsigned int idx=0; idx<drain_holes.size(); ++idx) {
        if (m_selected[idx]) {
            m_selected.erase(m_selected.begin()+idx);
            drain_holes.erase(drain_holes.begin() + (idx--));
        }
    }
    select_point(NoPoints);
}
References Slic3r::GUI::GLGizmoBase::m_c, m_selected, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), NoPoints, Slic3r::GUI::plater(), select_point(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
Referenced by gizmo_event(), and on_render_input_window().
disable_grabber()
void Slic3r::GUI::GLGizmoBase::disable_grabber (unsigned int id) inherited
{
    if (id < m_grabbers.size())
        m_grabbers[id].enabled = false;
    on_disable_grabber(id);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_disable_grabber().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_disable_grabber().
enable_grabber()
void Slic3r::GUI::GLGizmoBase::enable_grabber (unsigned int id) inherited
{
    if (id < m_grabbers.size())
        m_grabbers[id].enabled = true;
    on_enable_grabber(id);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_enable_grabber().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_enable_grabber().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), and Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
get_action_snapshot_name()
virtual std::string Slic3r::GUI::GLGizmoBase::get_action_snapshot_name () inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{ return "Gizmo action"; }
Referenced by Slic3r::GUI::Plater::priv::take_snapshot().
get_config_options()
std::vector< std::pair< const ConfigOption *, const ConfigOptionDef * > > Slic3r::GUI::GLGizmoHollow::get_config_options (const std::vector< std::string > & keys) const private
{
    std::vector<std::pair<const ConfigOption*, const ConfigOptionDef*>> out;
    const ModelObject* mo = m_c->selection_info()->model_object();
    if (! mo)
        return out;
    const DynamicPrintConfig& object_cfg = mo->config.get();
    const DynamicPrintConfig& print_cfg = wxGetApp().preset_bundle->sla_prints.get_edited_preset().config;
    std::unique_ptr<DynamicPrintConfig> default_cfg = nullptr;
    for (const std::string& key : keys) {
        if (object_cfg.has(key))
            out.emplace_back(object_cfg.option(key), &object_cfg.def()->options.at(key)); // at() needed for const map
        else
            if (print_cfg.has(key))
                out.emplace_back(print_cfg.option(key), &print_cfg.def()->options.at(key));
            else { // we must get it from defaults
                if (default_cfg == nullptr)
                    default_cfg.reset(DynamicPrintConfig::new_from_defaults_keys(keys));
                out.emplace_back(default_cfg->option(key), &default_cfg->def()->options.at(key));
            }
    }
    return out;
}
References Slic3r::ModelObject::config, Slic3r::DynamicPrintConfig::def(), Slic3r::ModelConfig::get(), Slic3r::ConfigOptionResolver::has(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::DynamicPrintConfig::new_from_defaults_keys(), Slic3r::ConfigBase::option(), Slic3r::ConfigDef::options, out, and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by on_render_input_window().
get_count()
int Slic3r::GUI::GLGizmoBase::get_count () inline inherited
{ return ++count; }
References Slic3r::GUI::GLGizmoBase::count.
get_gizmo_entering_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_entering_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
get_gizmo_leaving_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_leaving_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
get_gizmo_name()
std::string Slic3r::GUI::GLGizmoBase::get_gizmo_name () inline inherited
{ return on_get_name(); }
References Slic3r::GUI::GLGizmoBase::on_get_name().
get_group_id()
int Slic3r::GUI::GLGizmoBase::get_group_id () const inline inherited
{ return m_group_id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), and Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers().
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmoText::gizmo_event().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    int key = get_shortcut_key();
    std::string out = on_get_name();
    if (include_shortcut && key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z)
        out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::on_get_name(), and out.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), and Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_state(), Slic3r::GUI::GLGizmoCut::on_set_state(), Slic3r::GUI::GLGizmoFaceDetector::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), and Slic3r::GUI::GLGizmoSeam::on_set_state().
get_tooltip()
virtual std::string Slic3r::GUI::GLGizmoBase::get_tooltip () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoScale3D.
{ return ""; }
gizmo_event()
bool Slic3r::GUI::GLGizmoHollow::gizmo_event (SLAGizmoEventType action, const Vec2d & mouse_position, bool shift_down, bool alt_down, bool control_down)
{
    ModelObject* mo = m_c->selection_info()->model_object();
    int active_inst = m_c->selection_info()->get_active_instance();
    // left down with shift - show the selection rectangle:
    if (action == SLAGizmoEventType::LeftDown && (shift_down || alt_down || control_down)) {
        if (m_hover_id == -1) {
            if (shift_down || alt_down) {
                m_selection_rectangle.start_dragging(mouse_position, shift_down ? GLSelectionRectangle::Select : GLSelectionRectangle::Deselect);
            }
        }
        else {
            if (m_selected[m_hover_id])
                unselect_point(m_hover_id);
            else {
                if (!alt_down)
                    select_point(m_hover_id);
            }
        }
        return true;
    }
    // left down without selection rectangle - place point on the mesh:
    if (action == SLAGizmoEventType::LeftDown && !m_selection_rectangle.is_dragging() && !shift_down) {
        // If any point is in hover state, this should initiate its move - return control back to GLCanvas:
        if (m_hover_id != -1)
            return false;
        // If there is some selection, don't add new point and deselect everything instead.
        if (m_selection_empty) {
            std::pair<Vec3f, Vec3f> pos_and_normal;
            if (unproject_on_mesh(mouse_position, pos_and_normal)) { // we got an intersection
                Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Add drainage hole");
                mo->sla_drain_holes.emplace_back(pos_and_normal.first,
                                                -pos_and_normal.second, m_new_hole_radius, m_new_hole_height);
                m_selected.push_back(false);
                assert(m_selected.size() == mo->sla_drain_holes.size());
                m_parent.set_as_dirty();
                m_wait_for_up_event = true;
            }
            else
                return false;
        }
        else
            select_point(NoPoints);
        return true;
    }
    // left up with selection rectangle - select points inside the rectangle:
    if ((action == SLAGizmoEventType::LeftUp || action == SLAGizmoEventType::ShiftUp || action == SLAGizmoEventType::AltUp) && m_selection_rectangle.is_dragging()) {
        // Is this a selection or deselection rectangle?
        GLSelectionRectangle::EState rectangle_status = m_selection_rectangle.get_state();
        // First collect positions of all the points in world coordinates.
        Geometry::Transformation trafo = mo->instances[active_inst]->get_transformation();
        trafo.set_offset(trafo.get_offset() + Vec3d(0., 0., m_c->selection_info()->get_sla_shift()));
        std::vector<Vec3d> points;
        for (unsigned int i=0; i<mo->sla_drain_holes.size(); ++i)
            points.push_back(trafo.get_matrix() * mo->sla_drain_holes[i].pos.cast<double>());
        // Now ask the rectangle which of the points are inside.
        std::vector<Vec3f> points_inside;
        std::vector<unsigned int> points_idxs = m_selection_rectangle.stop_dragging(m_parent, points);
        for (size_t idx : points_idxs)
            points_inside.push_back(points[idx].cast<float>());
        // Only select/deselect points that are actually visible
        for (size_t idx : m_c->raycaster()->raycaster()->get_unobscured_idxs(
                 trafo, wxGetApp().plater()->get_camera(), points_inside,
                 m_c->object_clipper()->get_clipping_plane()))
        {
            if (rectangle_status == GLSelectionRectangle::Deselect)
                unselect_point(points_idxs[idx]);
            else
                select_point(points_idxs[idx]);
        }
        return true;
    }
    // left up with no selection rectangle
    if (action == SLAGizmoEventType::LeftUp) {
        if (m_wait_for_up_event) {
            m_wait_for_up_event = false;
        }
        return true;
    }
    // dragging the selection rectangle:
    if (action == SLAGizmoEventType::Dragging) {
        if (m_wait_for_up_event)
            return true; // point has been placed and the button not released yet
                         // this prevents GLCanvas from starting scene rotation
        if (m_selection_rectangle.is_dragging())  {
            m_selection_rectangle.dragging(mouse_position);
            return true;
        }
        return false;
    }
    if (action == SLAGizmoEventType::Delete) {
        // delete key pressed
        delete_selected_points();
        return true;
    }
    if (action == SLAGizmoEventType::RightDown) {
        if (m_hover_id != -1) {
            select_point(NoPoints);
            select_point(m_hover_id);
            delete_selected_points();
            return true;
        }
        return false;
    }
    if (action == SLAGizmoEventType::SelectAll) {
        select_point(AllPoints);
        return true;
    }
    if (action == SLAGizmoEventType::MouseWheelUp && control_down) {
        double pos = m_c->object_clipper()->get_position();
        pos = std::min(1., pos + 0.01);
        m_c->object_clipper()->set_position(pos, true);
        return true;
    }
    if (action == SLAGizmoEventType::MouseWheelDown && control_down) {
        double pos = m_c->object_clipper()->get_position();
        pos = std::max(0., pos - 0.01);
        m_c->object_clipper()->set_position(pos, true);
        return true;
    }
    if (action == SLAGizmoEventType::ResetClippingPlane) {
        m_c->object_clipper()->set_position(-1., false);
        return true;
    }
    return false;
}
References AllPoints, Slic3r::GUI::AltUp, Slic3r::GUI::Delete, delete_selected_points(), Slic3r::GUI::GLSelectionRectangle::Deselect, Slic3r::GUI::Dragging, Slic3r::GUI::GLSelectionRectangle::dragging(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::GUI::GLSelectionRectangle::get_state(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::ModelObject::instances, Slic3r::GUI::GLSelectionRectangle::is_dragging(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_hover_id, m_new_hole_height, m_new_hole_radius, Slic3r::GUI::GLGizmoBase::m_parent, m_selected, m_selection_empty, m_selection_rectangle, m_wait_for_up_event, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::MouseWheelDown, Slic3r::GUI::MouseWheelUp, NoPoints, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::plater(), Slic3r::points_inside(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster(), Slic3r::GUI::ResetClippingPlane, Slic3r::GUI::RightDown, Slic3r::GUI::GLSelectionRectangle::Select, select_point(), Slic3r::GUI::SelectAll, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::Geometry::Transformation::set_offset(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position(), Slic3r::GUI::ShiftUp, Slic3r::ModelObject::sla_drain_holes, Slic3r::GUI::GLSelectionRectangle::start_dragging(), Slic3r::GUI::GLSelectionRectangle::stop_dragging(), unproject_on_mesh(), and unselect_point().
GizmoImguiBegin()
bool Slic3r::GUI::GLGizmoBase::GizmoImguiBegin (const std::string & name, int flags) protected inherited
{
    return m_imgui->begin(name, flags);
}
References Slic3r::GUI::ImGuiWrapper::begin(), and Slic3r::GUI::GLGizmoBase::m_imgui.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
GizmoImguiEnd()
void Slic3r::GUI::GLGizmoBase::GizmoImguiEnd () protected inherited
{
    last_input_window_width = ImGui::GetWindowWidth();
    m_imgui->end();
}
References Slic3r::GUI::ImGuiWrapper::end(), ImGui::GetWindowWidth(), Slic3r::GUI::GLGizmoBase::last_input_window_width, and Slic3r::GUI::GLGizmoBase::m_imgui.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
GizmoImguiSetNextWIndowPos()
void Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos (float & x, float y, int flag, float pivot_x = 0.0f, float pivot_y = 0.0f) protected inherited
{
    if (abs(last_input_window_width) > 0.01f) {
        if (x + last_input_window_width > m_parent.get_canvas_size().get_width()) {
            if (last_input_window_width > m_parent.get_canvas_size().get_width()) {
                x = 0;
            } else {
                x = m_parent.get_canvas_size().get_width() - last_input_window_width;
            }
        }
    }
    m_imgui->set_next_window_pos(x, y, flag, pivot_x, pivot_y);
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLGizmoBase::last_input_window_width, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::GUI::ImGuiWrapper::set_next_window_pos().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
hollow_mesh()
void Slic3r::GUI::GLGizmoHollow::hollow_mesh (bool postpone_error_messages = false) private
{
    wxGetApp().CallAfter([this, postpone_error_messages]() {
        wxGetApp().plater()->reslice_SLA_hollowing(
            *m_c->selection_info()->model_object(), postpone_error_messages);
    });
}
References Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by on_render_input_window().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
is_mesh_point_clipped()
bool Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped (const Vec3d & point) const private
{
    if (m_c->object_clipper()->get_position() == 0.)
        return false;
    auto sel_info = m_c->selection_info();
    int active_inst = m_c->selection_info()->get_active_instance();
    const ModelInstance* mi = sel_info->model_object()->instances[active_inst];
    const Transform3d& trafo = mi->get_transformation().get_matrix();
    Vec3d transformed_point =  trafo * point;
    transformed_point(2) += sel_info->get_sla_shift();
    return m_c->object_clipper()->get_clipping_plane()->is_point_clipped(transformed_point);
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::ModelInstance::get_transformation(), Slic3r::GUI::ClippingPlane::is_point_clipped(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by render_points().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
is_selection_rectangle_dragging()
bool Slic3r::GUI::GLGizmoHollow::is_selection_rectangle_dragging () const inline
{
        return m_selection_rectangle.is_dragging();
    }
References Slic3r::GUI::GLSelectionRectangle::is_dragging(), and m_selection_rectangle.
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
load_render_colors()
void Slic3r::GUI::GLGizmoBase::load_render_colors () static inherited
{
    RenderColor::colors[RenderCol_Grabber_X] = IMColor(GLGizmoBase::AXES_COLOR[0]);
    RenderColor::colors[RenderCol_Grabber_Y] = IMColor(GLGizmoBase::AXES_COLOR[1]);
    RenderColor::colors[RenderCol_Grabber_Z] = IMColor(GLGizmoBase::AXES_COLOR[2]);
    RenderColor::colors[RenderCol_Flatten_Plane] = IMColor(GLGizmoBase::FLATTEN_COLOR);
    RenderColor::colors[RenderCol_Flatten_Plane_Hover] = IMColor(GLGizmoBase::FLATTEN_HOVER_COLOR);
}
References Slic3r::GUI::GLGizmoBase::AXES_COLOR, Slic3r::RenderColor::colors, Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR, Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR, Slic3r::IMColor(), RenderCol_Flatten_Plane, RenderCol_Flatten_Plane_Hover, RenderCol_Grabber_X, RenderCol_Grabber_Y, and RenderCol_Grabber_Z.
Referenced by Slic3r::GUI::GLCanvas3D::init().
on_change_color_mode()
virtual void Slic3r::GUI::GLGizmoBase::on_change_color_mode (bool is_dark) inline virtual inherited
{  m_is_dark_mode = is_dark; }
References Slic3r::GUI::GLGizmoBase::m_is_dark_mode.
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_disable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, and Slic3r::GUI::GLGizmoRotate3D.
{}
Referenced by Slic3r::GUI::GLGizmoBase::disable_grabber().
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_enable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, and Slic3r::GUI::GLGizmoRotate3D.
{}
Referenced by Slic3r::GUI::GLGizmoBase::enable_grabber().
on_get_name()
std::string Slic3r::GUI::GLGizmoHollow::on_get_name () const override protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    return _u8L("Hollow and drill");
}
References _u8L.
on_get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoHollow::on_get_requirements () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return CommonGizmosDataID(
                int(CommonGizmosDataID::SelectionInfo)
              | int(CommonGizmosDataID::InstancesHider)
              | int(CommonGizmosDataID::Raycaster)
              | int(CommonGizmosDataID::HollowedMesh)
              | int(CommonGizmosDataID::ObjectClipper)
              | int(CommonGizmosDataID::SupportsClipper));
}
References Slic3r::GUI::HollowedMesh, Slic3r::GUI::InstancesHider, Slic3r::GUI::ObjectClipper, Slic3r::GUI::Raycaster, Slic3r::GUI::SelectionInfo, and Slic3r::GUI::SupportsClipper.
on_init()
bool Slic3r::GUI::GLGizmoHollow::on_init () override private virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    m_shortcut_key = WXK_CONTROL_H;
    m_desc["enable"]           = _(L("Hollow this object"));
    m_desc["preview"]          = _(L("Preview hollowed and drilled model"));
    m_desc["offset"]           = _(L("Offset")) + ": ";
    m_desc["quality"]          = _(L("Quality")) + ": ";
    m_desc["closing_distance"] = _(L("Closing distance")) + ": ";
    m_desc["hole_diameter"]    = _(L("Hole diameter")) + ": ";
    m_desc["hole_depth"]       = _(L("Hole depth")) + ": ";
    m_desc["remove_selected"]  = _(L("Remove selected holes"));
    m_desc["remove_all"]       = _(L("Remove all holes"));
    m_desc["clipping_of_view"] = _(L("Clipping of view"))+ ": ";
    m_desc["reset_direction"]  = _(L("Reset direction"));
    m_desc["show_supports"]    = _(L("Show supports"));
    return true;
}
References _, L, m_desc, and Slic3r::GUI::GLGizmoBase::m_shortcut_key.
on_is_activable()
bool Slic3r::GUI::GLGizmoHollow::on_is_activable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
    if (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() != ptSLA
        || !selection.is_from_single_instance())
        return false;
    // Check that none of the selected volumes is outside. Only SLA auxiliaries (supports) are allowed outside.
    const Selection::IndicesList& list = selection.get_volume_idxs();
    for (const auto& idx : list)
        if (selection.get_volume(idx)->is_outside && selection.get_volume(idx)->composite_id.volume_id >= 0)
            return false;
    return true;
}
References Slic3r::GLVolume::composite_id, Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_from_single_instance(), Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::ptSLA, and Slic3r::GLVolume::CompositeID::volume_id.
on_is_selectable()
bool Slic3r::GUI::GLGizmoHollow::on_is_selectable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA);
}
References Slic3r::ptSLA.
on_load()
void Slic3r::GUI::GLGizmoHollow::on_load (cereal::BinaryInputArchive & ar) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar(m_new_hole_radius,
       m_new_hole_height,
       m_selected,
       m_selection_empty
    );
}
References m_new_hole_height, m_new_hole_radius, m_selected, and m_selection_empty.
on_render()
void Slic3r::GUI::GLGizmoHollow::on_render () override private virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
    const CommonGizmosDataObjects::SelectionInfo* sel_info = m_c->selection_info();
    // If current m_c->m_model_object does not match selection, ask GLCanvas3D to turn us off
    if (m_state == On
     && (sel_info->model_object() != selection.get_model()->objects[selection.get_object_idx()]
      || sel_info->get_active_instance() != selection.get_instance_idx())) {
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_RESETGIZMOS));
        return;
    }
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glEnable(GL_DEPTH_TEST));
    if (selection.is_from_single_instance())
        render_points(selection, false);
    m_selection_rectangle.render(m_parent);
    m_c->object_clipper()->render_cut();
    m_c->supports_clipper()->render_cut();
    glsafe(::glDisable(GL_BLEND));
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_model(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), glsafe, Slic3r::GUI::Selection::is_from_single_instance(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_parent, m_selection_rectangle, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::Model::objects, Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::GLCanvas3D::post_event(), Slic3r::GUI::GLSelectionRectangle::render(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), render_points(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
on_render_for_picking()
void Slic3r::GUI::GLGizmoHollow::on_render_for_picking () override private virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
//#if ENABLE_RENDER_PICKING_PASS
//    m_z_shift = selection.get_volume(*selection.get_volume_idxs().begin())->get_sla_shift_z();
//#endif
    glsafe(::glEnable(GL_DEPTH_TEST));
    render_points(selection, true);
}
References Slic3r::GUI::GLCanvas3D::get_selection(), glsafe, Slic3r::GUI::GLGizmoBase::m_parent, and render_points().
on_render_input_window()
void Slic3r::GUI::GLGizmoHollow::on_render_input_window (float x, float y, float bottom_limit) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ModelObject* mo = m_c->selection_info()->model_object();
    if (! mo)
        return;
    bool first_run = true; // This is a hack to redraw the button when all points are removed,
                           // so it is not delayed until the background process finishes.
    ConfigOptionMode current_mode = wxGetApp().get_mode();
    std::vector<std::string> opts_keys = {"hollowing_min_thickness", "hollowing_quality", "hollowing_closing_distance"};
    auto opts = get_config_options(opts_keys);
    auto* offset_cfg = static_cast<const ConfigOptionFloat*>(opts[0].first);
    float offset = offset_cfg->value;
    double offset_min = opts[0].second->min;
    double offset_max = opts[0].second->max;
    auto* quality_cfg = static_cast<const ConfigOptionFloat*>(opts[1].first);
    float quality = quality_cfg->value;
    double quality_min = opts[1].second->min;
    double quality_max = opts[1].second->max;
    ConfigOptionMode quality_mode = opts[1].second->mode;
    auto* closing_d_cfg = static_cast<const ConfigOptionFloat*>(opts[2].first);
    float closing_d = closing_d_cfg->value;
    double closing_d_min = opts[2].second->min;
    double closing_d_max = opts[2].second->max;
    ConfigOptionMode closing_d_mode = opts[2].second->mode;
    m_desc["offset"] = _(opts[0].second->label) + ":";
    m_desc["quality"] = _(opts[1].second->label) + ":";
    m_desc["closing_distance"] = _(opts[2].second->label) + ":";
RENDER_AGAIN:
    const float approx_height = m_imgui->scaled(20.0f);
    y = std::min(y, bottom_limit - approx_height);
    m_imgui->set_next_window_pos(x, y, ImGuiCond_Always);
    m_imgui->begin(get_name(), ImGuiWindowFlags_NoMove | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoCollapse);
    // First calculate width of all the texts that are could possibly be shown. We will decide set the dialog width based on that:
    const float clipping_slider_left = std::max(m_imgui->calc_text_size(m_desc.at("clipping_of_view")).x,
                                                m_imgui->calc_text_size(m_desc.at("reset_direction")).x) + m_imgui->scaled(0.5f);
    const float settings_sliders_left =
        std::max(std::max({m_imgui->calc_text_size(m_desc.at("offset")).x,
                           m_imgui->calc_text_size(m_desc.at("quality")).x,
                           m_imgui->calc_text_size(m_desc.at("closing_distance")).x,
                           m_imgui->calc_text_size(m_desc.at("hole_diameter")).x,
                           m_imgui->calc_text_size(m_desc.at("hole_depth")).x}) + m_imgui->scaled(0.5f), clipping_slider_left);
    const float diameter_slider_left = settings_sliders_left; //m_imgui->calc_text_size(m_desc.at("hole_diameter")).x + m_imgui->scaled(1.f);
    const float minimal_slider_width = m_imgui->scaled(4.f);
    const float button_preview_width = m_imgui->calc_button_size(m_desc.at("preview")).x;
    float window_width = minimal_slider_width + std::max({settings_sliders_left, clipping_slider_left, diameter_slider_left});
    window_width = std::max(window_width, button_preview_width);
    if (m_imgui->button(m_desc["preview"]))
        hollow_mesh();
    bool config_changed = false;
    ImGui::Separator();
    {
        auto opts = get_config_options({"hollowing_enable"});
        m_enable_hollowing = static_cast<const ConfigOptionBool*>(opts[0].first)->value;
        if (m_imgui->checkbox(m_desc["enable"], m_enable_hollowing)) {
            mo->config.set("hollowing_enable", m_enable_hollowing);
            wxGetApp().obj_list()->update_and_show_object_settings_item();
            config_changed = true;
        }
    }
    m_imgui->disabled_begin(! m_enable_hollowing);
    float max_tooltip_width = ImGui::GetFontSize() * 20.0f;
    ImGui::AlignTextToFramePadding();
    m_imgui->text(m_desc.at("offset"));
    ImGui::SameLine(settings_sliders_left, m_imgui->get_item_spacing().x);
    ImGui::PushItemWidth(window_width - settings_sliders_left);
    m_imgui->slider_float("##offset", &offset, offset_min, offset_max, "%.1f mm");
    if (m_imgui->get_last_slider_status().hovered)
        m_imgui->tooltip((_utf8(opts[0].second->tooltip)).c_str(), max_tooltip_width);
    bool slider_clicked = m_imgui->get_last_slider_status().clicked; // someone clicked the slider
    bool slider_edited =m_imgui->get_last_slider_status().edited; // someone is dragging the slider
    bool slider_released =m_imgui->get_last_slider_status().deactivated_after_edit; // someone has just released the slider
    if (current_mode >= quality_mode) {
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("quality"));
        ImGui::SameLine(settings_sliders_left, m_imgui->get_item_spacing().x);
        m_imgui->slider_float("##quality", &quality, quality_min, quality_max, "%.1f");
        if (m_imgui->get_last_slider_status().hovered)
            m_imgui->tooltip((_utf8(opts[1].second->tooltip)).c_str(), max_tooltip_width);
        slider_clicked |= m_imgui->get_last_slider_status().clicked;
        slider_edited |= m_imgui->get_last_slider_status().edited;
        slider_released |= m_imgui->get_last_slider_status().deactivated_after_edit;
    }
    if (current_mode >= closing_d_mode) {
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("closing_distance"));
        ImGui::SameLine(settings_sliders_left, m_imgui->get_item_spacing().x);
        m_imgui->slider_float("##closing_distance", &closing_d, closing_d_min, closing_d_max, "%.1f mm");
        if (m_imgui->get_last_slider_status().hovered)
            m_imgui->tooltip((_utf8(opts[2].second->tooltip)).c_str(), max_tooltip_width);
        slider_clicked |= m_imgui->get_last_slider_status().clicked;
        slider_edited |= m_imgui->get_last_slider_status().edited;
        slider_released |= m_imgui->get_last_slider_status().deactivated_after_edit;
    }
    if (slider_clicked) {
        m_offset_stash = offset;
        m_quality_stash = quality;
        m_closing_d_stash = closing_d;
    }
    if (slider_edited || slider_released) {
        if (slider_released) {
            mo->config.set("hollowing_min_thickness", m_offset_stash);
            mo->config.set("hollowing_quality", m_quality_stash);
            mo->config.set("hollowing_closing_distance", m_closing_d_stash);
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Hollowing parameter change");
        }
        mo->config.set("hollowing_min_thickness", offset);
        mo->config.set("hollowing_quality", quality);
        mo->config.set("hollowing_closing_distance", closing_d);
        if (slider_released) {
            wxGetApp().obj_list()->update_and_show_object_settings_item();
            config_changed = true;
        }
    }
    m_imgui->disabled_end();
    bool force_refresh = false;
    bool remove_selected = false;
    bool remove_all = false;
    ImGui::Separator();
    float diameter_upper_cap = 60.;
    if (m_new_hole_radius * 2.f > diameter_upper_cap)
        m_new_hole_radius = diameter_upper_cap / 2.f;
    ImGui::AlignTextToFramePadding();
    m_imgui->text(m_desc.at("hole_diameter"));
    ImGui::SameLine(diameter_slider_left, m_imgui->get_item_spacing().x);
    ImGui::PushItemWidth(window_width - diameter_slider_left);
    float diam = 2.f * m_new_hole_radius;
    m_imgui->slider_float("##hole_diameter", &diam, 1.f, 25.f, "%.1f mm", 1.f, false);
    // Let's clamp the value (which could have been entered by keyboard) to a larger range
    // than the slider. This allows entering off-scale values and still protects against
    //complete non-sense.
    diam = std::clamp(diam, 0.1f, diameter_upper_cap);
    m_new_hole_radius = diam / 2.f;
    bool clicked = m_imgui->get_last_slider_status().clicked;
    bool edited = m_imgui->get_last_slider_status().edited;
    bool deactivated = m_imgui->get_last_slider_status().deactivated_after_edit;
    ImGui::AlignTextToFramePadding();
    m_imgui->text(m_desc["hole_depth"]);
    ImGui::SameLine(diameter_slider_left, m_imgui->get_item_spacing().x);
    m_imgui->slider_float("##hole_depth", &m_new_hole_height, 0.f, 10.f, "%.1f mm", 1.f, false);
    // Same as above:
    m_new_hole_height = std::clamp(m_new_hole_height, 0.f, 100.f);
    clicked |= m_imgui->get_last_slider_status().clicked;
    edited |= m_imgui->get_last_slider_status().edited;
    deactivated |= m_imgui->get_last_slider_status().deactivated_after_edit;;
    // Following is a nasty way to:
    //  - save the initial value of the slider before one starts messing with it
    //  - keep updating the head radius during sliding so it is continuosly refreshed in 3D scene
    //  - take correct undo/redo snapshot after the user is done with moving the slider
    if (! m_selection_empty) {
        if (clicked) {
            m_holes_stash = mo->sla_drain_holes;
        }
        if (edited) {
            for (size_t idx=0; idx<m_selected.size(); ++idx)
                if (m_selected[idx]) {
                    mo->sla_drain_holes[idx].radius = m_new_hole_radius;
                    mo->sla_drain_holes[idx].height = m_new_hole_height;
                }
        }
        if (deactivated) {
            // momentarily restore the old value to take snapshot
            sla::DrainHoles new_holes = mo->sla_drain_holes;
            mo->sla_drain_holes = m_holes_stash;
            float backup_rad = m_new_hole_radius;
            float backup_hei = m_new_hole_height;
            for (size_t i=0; i<m_holes_stash.size(); ++i) {
                if (m_selected[i]) {
                    m_new_hole_radius = m_holes_stash[i].radius;
                    m_new_hole_height = m_holes_stash[i].height;
                    break;
                }
            }
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Change drainage hole diameter");
            m_new_hole_radius = backup_rad;
            m_new_hole_height = backup_hei;
            mo->sla_drain_holes = new_holes;
        }
    }
    m_imgui->disabled_begin(m_selection_empty);
    remove_selected = m_imgui->button(m_desc.at("remove_selected"));
    m_imgui->disabled_end();
    m_imgui->disabled_begin(mo->sla_drain_holes.empty());
    remove_all = m_imgui->button(m_desc.at("remove_all"));
    m_imgui->disabled_end();
    // Following is rendered in both editing and non-editing mode:
   // m_imgui->text("");
    ImGui::Separator();
    if (m_c->object_clipper()->get_position() == 0.f) {
        ImGui::AlignTextToFramePadding();
        m_imgui->text(m_desc.at("clipping_of_view"));
    }
    else {
        if (m_imgui->button(m_desc.at("reset_direction"))) {
            wxGetApp().CallAfter([this](){
                    m_c->object_clipper()->set_position(-1., false);
                });
        }
    }
    ImGui::SameLine(settings_sliders_left, m_imgui->get_item_spacing().x);
    ImGui::PushItemWidth(window_width - settings_sliders_left);
    float clp_dist = m_c->object_clipper()->get_position();
    if (m_imgui->slider_float("##clp_dist", &clp_dist, 0.f, 1.f, "%.2f"))
        m_c->object_clipper()->set_position(clp_dist, true);
    // make sure supports are shown/hidden as appropriate
    bool show_sups = m_c->instances_hider()->are_supports_shown();
    if (m_imgui->checkbox(m_desc["show_supports"], show_sups)) {
        m_c->instances_hider()->show_supports(show_sups);
        force_refresh = true;
    }
    m_imgui->end();
    if (remove_selected || remove_all) {
        force_refresh = false;
        m_parent.set_as_dirty();
        if (remove_all) {
            select_point(AllPoints);
            delete_selected_points();
        }
        if (remove_selected)
            delete_selected_points();
        if (first_run) {
            first_run = false;
            goto RENDER_AGAIN;
        }
    }
    if (force_refresh)
        m_parent.set_as_dirty();
    if (config_changed)
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_FORCE_UPDATE));
}
References _, _utf8, ImGui::AlignTextToFramePadding(), AllPoints, Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::are_supports_shown(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::calc_button_size(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::checkbox(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::clicked, Slic3r::ModelObject::config, Slic3r::GUI::ImGuiWrapper::LastSliderStatus::deactivated_after_edit, delete_selected_points(), Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::edited, Slic3r::GUI::ImGuiWrapper::end(), get_config_options(), Slic3r::GUI::ImGuiWrapper::get_item_spacing(), Slic3r::GUI::ImGuiWrapper::get_last_slider_status(), Slic3r::GUI::GLGizmoBase::get_name(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), ImGui::GetFontSize(), hollow_mesh(), Slic3r::GUI::ImGuiWrapper::LastSliderStatus::hovered, ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::GLGizmoBase::m_c, m_closing_d_stash, m_desc, m_enable_hollowing, m_holes_stash, Slic3r::GUI::GLGizmoBase::m_imgui, m_new_hole_height, m_new_hole_radius, m_offset_stash, Slic3r::GUI::GLGizmoBase::m_parent, m_quality_stash, m_selected, m_selection_empty, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::offset(), Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::post_event(), ImGui::PushItemWidth(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::scaled(), select_point(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), ImGui::Separator(), Slic3r::ModelConfig::set(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::show_supports(), Slic3r::ModelObject::sla_drain_holes, Slic3r::GUI::ImGuiWrapper::slider_float(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::tooltip(), Slic3r::ConfigOptionSingle< T >::value, and ImVec2::x.
on_save()
void Slic3r::GUI::GLGizmoHollow::on_save (cereal::BinaryOutputArchive & ar) const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar(m_new_hole_radius,
       m_new_hole_height,
       m_selected,
       m_selection_empty
    );
}
References m_new_hole_height, m_new_hole_radius, m_selected, and m_selection_empty.
on_set_hover_id()
void Slic3r::GUI::GLGizmoHollow::on_set_hover_id () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (int(m_c->selection_info()->model_object()->sla_drain_holes.size()) <= m_hover_id)
        m_hover_id = -1;
}
References Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
on_set_state()
void Slic3r::GUI::GLGizmoHollow::on_set_state () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_state == m_old_state)
        return;
    if (m_state == Off && m_old_state != Off) // the gizmo was just turned Off
        m_parent.post_event(SimpleEvent(EVT_GLCANVAS_FORCE_UPDATE));
    m_old_state = m_state;
}
References m_old_state, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::Off, and Slic3r::GUI::GLCanvas3D::post_event().
on_start_dragging()
void Slic3r::GUI::GLGizmoHollow::on_start_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_hover_id != -1) {
        select_point(NoPoints);
        select_point(m_hover_id);
        m_hole_before_drag = m_c->selection_info()->model_object()->sla_drain_holes[m_hover_id].pos;
    }
    else
        m_hole_before_drag = Vec3f::Zero();
}
References Slic3r::GUI::GLGizmoBase::m_c, m_hole_before_drag, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), NoPoints, select_point(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
on_stop_dragging()
void Slic3r::GUI::GLGizmoHollow::on_stop_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    if (m_hover_id != -1) {
        Vec3f backup = drain_holes[m_hover_id].pos;
        if (m_hole_before_drag != Vec3f::Zero() // some point was touched
         && backup != m_hole_before_drag) // and it was moved, not just selected
        {
            drain_holes[m_hover_id].pos = m_hole_before_drag;
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Move drainage hole");
            drain_holes[m_hover_id].pos = backup;
        }
    }
    m_hole_before_drag = Vec3f::Zero();
}
References Slic3r::GUI::GLGizmoBase::m_c, m_hole_before_drag, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::plater(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
on_update()
void Slic3r::GUI::GLGizmoHollow::on_update (const UpdateData & data) override private virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    if (m_hover_id != -1) {
        std::pair<Vec3f, Vec3f> pos_and_normal;
        if (! unproject_on_mesh(data.mouse_pos.cast<double>(), pos_and_normal))
            return;
        drain_holes[m_hover_id].pos = pos_and_normal.first;
        drain_holes[m_hover_id].normal = -pos_and_normal.second;
    }
}
References Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLGizmoBase::UpdateData::mouse_pos, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_drain_holes, and unproject_on_mesh().
picking_color_component()
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::picking_color_component (unsigned int id) const protected inherited
{
    static const float INV_255 = 1.0f / 255.0f;
    id = BASE_ID - id;
    if (m_group_id > -1)
        id -= m_group_id;
    // color components are encoded to match the calculation of volume_id made into GLCanvas3D::_picking_pass()
    return std::array<float, 4> {
    float((id >> 0) & 0xff) * INV_255, // red
    float((id >> 8) & 0xff) * INV_255, // green
    float((id >> 16) & 0xff) * INV_255, // blue
    float(picking_checksum_alpha_channel(id & 0xff, (id >> 8) & 0xff, (id >> 16) & 0xff))* INV_255 // checksum for validating against unwanted alpha blending and multi sampling
  };
}
References Slic3r::GUI::GLGizmoBase::BASE_ID, Slic3r::GUI::GLGizmoBase::m_group_id, and Slic3r::GUI::picking_checksum_alpha_channel().
Referenced by Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking(), render_points(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
reload_cache()
void Slic3r::GUI::GLGizmoHollow::reload_cache () private
{
    m_selected.clear();
    m_selected.assign(m_c->selection_info()->model_object()->sla_drain_holes.size(), false);
}
References Slic3r::GUI::GLGizmoBase::m_c, m_selected, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
Referenced by set_sla_support_data().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ m_tooltip.clear(); on_render(); }
References Slic3r::GUI::GLGizmoBase::m_tooltip, and Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render(), and Slic3r::GUI::GLGizmoBase::Grabber::render_for_picking().
render_for_picking()
void Slic3r::GUI::GLGizmoBase::render_for_picking () inline inherited
{ on_render_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_render_for_picking().
render_grabbers() [1/2]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
#if ENABLE_FIXED_GRABBER
    render_grabbers((float)(GLGizmoBase::Grabber::FixedGrabberSize));
#else
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
#endif
}
References Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/2]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    for (int i = 0; i < (int)m_grabbers.size(); ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(m_hover_id == i, size);
    }
    shader->stop_using();
}
References int, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), size, Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking (const BoundingBoxf3 & box) const protected inherited
{
#if ENABLE_FIXED_GRABBER
    float mean_size = (float)(GLGizmoBase::Grabber::FixedGrabberSize);
#else
    float mean_size = (float)((box.size().x() + box.size().y() + box.size().z()) / 3.0);
#endif
    for (unsigned int i = 0; i < (unsigned int)m_grabbers.size(); ++i) {
        if (m_grabbers[i].enabled) {
            std::array<float, 4> color = picking_color_component(i);
            m_grabbers[i].color = color;
            m_grabbers[i].render_for_picking(mean_size);
        }
    }
}
References Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, int, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::picking_color_component(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), and Slic3r::GUI::GLGizmoScale3D::on_render_for_picking().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // for some reason, the imgui dialogs are not shown on screen in the 1st frame where they are rendered, but show up only with the 2nd rendered frame
        // so, we forces another frame rendering the first time the imgui window is shown
        m_parent.set_as_dirty();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
render_points()
void Slic3r::GUI::GLGizmoHollow::render_points (const Selection & selection, bool picking = false) const private
{
    GLShaderProgram* shader = picking ? nullptr : wxGetApp().get_shader("gouraud_light");
    if (shader)
        shader->start_using();
    ScopeGuard guard([shader]() { if (shader) shader->stop_using(); });
    const GLVolume* vol = selection.get_volume(*selection.get_volume_idxs().begin());
    const Transform3d& instance_scaling_matrix_inverse = vol->get_instance_transformation().get_matrix(true, true, false, true).inverse();
    const Transform3d& instance_matrix = vol->get_instance_transformation().get_matrix();
    glsafe(::glPushMatrix());
    glsafe(::glTranslated(0.0, 0.0, m_c->selection_info()->get_sla_shift()));
    glsafe(::glMultMatrixd(instance_matrix.data()));
    std::array<float, 4> render_color;
    const sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    size_t cache_size = drain_holes.size();
    for (size_t i = 0; i < cache_size; ++i) {
        const sla::DrainHole& drain_hole = drain_holes[i];
        const bool& point_selected = m_selected[i];
        if (is_mesh_point_clipped(drain_hole.pos.cast<double>()))
            continue;
        // First decide about the color of the point.
        if (picking) {
            std::array<float, 4> color = picking_color_component(i);
            render_color = color;
        }
        else {
            if (size_t(m_hover_id) == i) {
                render_color = {0.f, 1.f, 1.f, 1.f};
            }
            else if (m_c->hollowed_mesh() &&
                       i < m_c->hollowed_mesh()->get_drainholes().size() &&
                       m_c->hollowed_mesh()->get_drainholes()[i].failed) {
                render_color = {1.f, 0.f, 0.f, .5f};
            }
            else { // neigher hover nor picking
                render_color[0] = point_selected ? 1.0f : 1.f;
                render_color[1] = point_selected ? 0.3f : 1.f;
                render_color[2] = point_selected ? 0.3f : 1.f;
                render_color[3] = 0.5f;
            }
        }
        const_cast<GLModel*>(&m_vbo_cylinder)->set_color(-1, render_color);
        // Inverse matrix of the instance scaling is applied so that the mark does not scale with the object.
        glsafe(::glPushMatrix());
        glsafe(::glTranslatef(drain_hole.pos(0), drain_hole.pos(1), drain_hole.pos(2)));
        glsafe(::glMultMatrixd(instance_scaling_matrix_inverse.data()));
        if (vol->is_left_handed())
            glFrontFace(GL_CW);
        // Matrices set, we can render the point mark now.
        Eigen::Quaterniond q;
        q.setFromTwoVectors(Vec3d{0., 0., 1.}, instance_scaling_matrix_inverse * (-drain_hole.normal).cast<double>());
        Eigen::AngleAxisd aa(q);
        glsafe(::glRotated(aa.angle() * (180. / M_PI), aa.axis()(0), aa.axis()(1), aa.axis()(2)));
        glsafe(::glPushMatrix());
        glsafe(::glTranslated(0., 0., -drain_hole.height));
        glsafe(::glScaled(drain_hole.radius, drain_hole.radius, drain_hole.height + sla::HoleStickOutLength));
        m_vbo_cylinder.render();
        glsafe(::glPopMatrix());
        if (vol->is_left_handed())
            glFrontFace(GL_CCW);
        glsafe(::glPopMatrix());
    }
    glsafe(::glPopMatrix());
}
References Eigen::AngleAxis< _Scalar >::angle(), Eigen::AngleAxis< _Scalar >::axis(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::get_drainholes(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), glsafe, Slic3r::sla::DrainHole::height, Slic3r::sla::HoleStickOutLength, Slic3r::GUI::CommonGizmosDataPool::hollowed_mesh(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), is_mesh_point_clipped(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_hover_id, M_PI, m_selected, m_vbo_cylinder, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::sla::DrainHole::normal, Slic3r::GUI::GLGizmoBase::picking_color_component(), Slic3r::sla::DrainHole::pos, Slic3r::sla::DrainHole::radius, Slic3r::GUI::GLModel::render(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Eigen::QuaternionBase< Derived >::setFromTwoVectors(), size, Slic3r::ModelObject::sla_drain_holes, Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by on_render(), and on_render_for_picking().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
select_point()
void Slic3r::GUI::GLGizmoHollow::select_point (int i) private
{
    const sla::DrainHoles& drain_holes = m_c->selection_info()->model_object()->sla_drain_holes;
    if (i == AllPoints || i == NoPoints) {
        m_selected.assign(m_selected.size(), i == AllPoints);
        m_selection_empty = (i == NoPoints);
        if (i == AllPoints) {
            m_new_hole_radius = drain_holes[0].radius;
            m_new_hole_height = drain_holes[0].height;
        }
    }
    else {
        while (size_t(i) >= m_selected.size())
            m_selected.push_back(false);
        m_selected[i] = true;
        m_selection_empty = false;
        m_new_hole_radius = drain_holes[i].radius;
        m_new_hole_height = drain_holes[i].height;
    }
}
References AllPoints, Slic3r::GUI::GLGizmoBase::m_c, m_new_hole_height, m_new_hole_radius, m_selected, m_selection_empty, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), NoPoints, Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
Referenced by delete_selected_points(), gizmo_event(), on_render_input_window(), and on_start_dragging().
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c, and ptr.
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::process_cut_line(), and Slic3r::GUI::GLGizmoSimplify::request_rerender().
set_group_id()
void Slic3r::GUI::GLGizmoBase::set_group_id (int id) inline inherited
{ m_group_id = id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::GLGizmoAdvancedCut().
set_highlight_color()
void Slic3r::GUI::GLGizmoBase::set_highlight_color (const std::array< float, 4 > & color) inherited
{
    m_highlight_color = color;
}
References Slic3r::GUI::GLGizmoBase::m_highlight_color.
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    if (m_grabbers.empty() || (id < (int)m_grabbers.size()))
    {
        m_hover_id = id;
        on_set_hover_id();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_icon_filename()
void Slic3r::GUI::GLGizmoBase::set_icon_filename (const std::string & filename) inherited
{
    m_icon_filename = filename;
}
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
set_sla_support_data()
void Slic3r::GUI::GLGizmoHollow::set_sla_support_data (ModelObject * model_object, const Selection & selection)
{
    if (! m_c->selection_info())
        return;
    const ModelObject* mo = m_c->selection_info()->model_object();
    if (m_state == On && mo) {
        if (m_old_mo_id != mo->id()) {
            reload_cache();
            m_old_mo_id = mo->id();
        }
        if (m_c->hollowed_mesh() && m_c->hollowed_mesh()->get_hollowed_mesh())
            m_holes_in_drilled_mesh = mo->sla_drain_holes;
    }
}
References Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::get_hollowed_mesh(), Slic3r::GUI::CommonGizmosDataPool::hollowed_mesh(), Slic3r::ObjectBase::id(), Slic3r::GUI::GLGizmoBase::m_c, m_holes_in_drilled_mesh, m_old_mo_id, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLGizmoBase::On, reload_cache(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::ModelObject::sla_drain_holes.
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
start_dragging()
void Slic3r::GUI::GLGizmoBase::start_dragging () inherited
{
    m_dragging = true;
    for (int i = 0; i < (int)m_grabbers.size(); ++i)
    {
        m_grabbers[i].dragging = (m_hover_id == i);
    }
    on_start_dragging();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("this %1%, m_hover_id=%2%\n")%this %m_hover_id;
}
References int, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_start_dragging().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), and Slic3r::GUI::GLGizmoText::gizmo_event().
stop_dragging()
void Slic3r::GUI::GLGizmoBase::stop_dragging () inherited
{
    m_dragging = false;
    for (int i = 0; i < (int)m_grabbers.size(); ++i)
    {
        m_grabbers[i].dragging = false;
    }
    on_stop_dragging();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("this %1%, m_hover_id=%2%\n")%this %m_hover_id;
}
References int, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_stop_dragging().
unproject_on_mesh()
bool Slic3r::GUI::GLGizmoHollow::unproject_on_mesh (const Vec2d & mouse_pos, std::pair< Vec3f, Vec3f > & pos_and_normal) private
{
    if (! m_c->raycaster()->raycaster())
        return false;
    const Camera& camera = wxGetApp().plater()->get_camera();
    const Selection& selection = m_parent.get_selection();
    const GLVolume* volume = selection.get_volume(*selection.get_volume_idxs().begin());
    Geometry::Transformation trafo = volume->get_instance_transformation();
    trafo.set_offset(trafo.get_offset() + Vec3d(0., 0., m_c->selection_info()->get_sla_shift()));
    double clp_dist = m_c->object_clipper()->get_position();
    const ClippingPlane* clp = m_c->object_clipper()->get_clipping_plane();
    // The raycaster query
    Vec3f hit;
    Vec3f normal;
    if (m_c->raycaster()->raycaster()->unproject_on_mesh(
            mouse_pos,
            trafo.get_matrix(),
            camera,
            hit,
            normal,
            clp_dist != 0. ? clp : nullptr))
    {
        if (m_c->hollowed_mesh() && m_c->hollowed_mesh()->get_hollowed_mesh()) {
            // in this case the raycaster sees the hollowed and drilled mesh.
            // if the point lies on the surface created by the hole, we want
            // to ignore it.
            for (const sla::DrainHole& hole : m_holes_in_drilled_mesh) {
                sla::DrainHole outer(hole);
                outer.radius *= 1.001f;
                outer.height *= 1.001f;
                if (outer.is_inside(hit))
                    return false;
            }
        }
        // Return both the point and the facet normal.
        pos_and_normal = std::make_pair(hit, normal);
        return true;
    }
    else
        return false;
}
References Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::get_hollowed_mesh(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::sla::DrainHole::height, Slic3r::GUI::CommonGizmosDataPool::hollowed_mesh(), Slic3r::sla::DrainHole::is_inside(), Slic3r::GUI::GLGizmoBase::m_c, m_holes_in_drilled_mesh, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::normal(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::sla::DrainHole::radius, Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycaster(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::Geometry::Transformation::set_offset(), and Slic3r::GUI::MeshRaycaster::unproject_on_mesh().
Referenced by gizmo_event(), and on_update().
unsaved_changes()
bool Slic3r::GUI::GLGizmoHollow::unsaved_changes () const private
unselect_point()
void Slic3r::GUI::GLGizmoHollow::unselect_point (int i) private
{
    m_selected[i] = false;
    m_selection_empty = true;
    for (const bool sel : m_selected) {
        if (sel) {
            m_selection_empty = false;
            break;
        }
    }
}
References m_selected, and m_selection_empty.
Referenced by gizmo_event().
update()
void Slic3r::GUI::GLGizmoBase::update (const UpdateData & data) inherited
{
    if (m_hover_id != -1)
        on_update(data);
}
References Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_update().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
};
References Slic3r::GUI::GLGizmoBase::m_dirty.
update_render_colors()
void Slic3r::GUI::GLGizmoBase::update_render_colors () static inherited
{
    GLGizmoBase::AXES_COLOR = { {
                                GLColor(RenderColor::colors[RenderCol_Grabber_X]),
                                GLColor(RenderColor::colors[RenderCol_Grabber_Y]),
                                GLColor(RenderColor::colors[RenderCol_Grabber_Z])
                                } };
    GLGizmoBase::FLATTEN_COLOR = GLColor(RenderColor::colors[RenderCol_Flatten_Plane]);
    GLGizmoBase::FLATTEN_HOVER_COLOR = GLColor(RenderColor::colors[RenderCol_Flatten_Plane_Hover]);
}
References Slic3r::GUI::GLGizmoBase::AXES_COLOR, Slic3r::RenderColor::colors, Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR, Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR, Slic3r::GLColor(), RenderCol_Flatten_Plane, RenderCol_Flatten_Plane_Hover, RenderCol_Grabber_X, RenderCol_Grabber_Y, and RenderCol_Grabber_Z.
Referenced by Slic3r::GUI::GLCanvas3D::_render_style_editor().
wants_enter_leave_snapshots()
virtual bool Slic3r::GUI::GLGizmoBase::wants_enter_leave_snapshots () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Member Data Documentation
AXES_COLOR
std::array< std::array< float, 4 >, 3 > Slic3r::GUI::GLGizmoBase::AXES_COLOR static inherited
Initial value:
= { {
                                                                { 1.0, 0.0f, 0.0f, 1.0f },
                                                                { 0.0f, 1.0f, 0.0f, 1.0f },
                                                                { 0.0f, 0.0f, 1.0f, 1.0f }
                                                                }}
Referenced by Slic3r::GUI::get_color(), Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
AXES_HOVER_COLOR
std::array< std::array< float, 4 >, 3 > Slic3r::GUI::GLGizmoBase::AXES_HOVER_COLOR static inherited
Initial value:
= {{
                                                                { 0.7f, 0.0f, 0.0f, 1.0f },
                                                                { 0.0f, 0.7f, 0.0f, 1.0f },
                                                                { 0.0f, 0.0f, 0.7f, 1.0f }
                                                                }}
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), and Slic3r::GUI::GLGizmoRotate::render_grabber().
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::GLGizmoBase::picking_color_component().
CONSTRAINED_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::CONSTRAINED_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f } static inherited
count
int Slic3r::GUI::GLGizmoBase::count = 0 private inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_count().
DEFAULT_BASE_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_BASE_COLOR = { 0.625f, 0.625f, 0.625f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
DEFAULT_DRAG_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_DRAG_COLOR = { 1.0f, 1.0f, 1.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
DEFAULT_HIGHLIGHT_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_HIGHLIGHT_COLOR = { 1.0f, 0.38f, 0.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
FLATTEN_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR = { 0.96f, 0.93f, 0.93f, 0.5f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoFlatten::on_render(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
FLATTEN_HOVER_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR = { 1.0f, 1.0f, 1.0f, 0.75f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoFlatten::on_render(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
GRABBER_HOVER_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_HOVER_COL = {0.863f, 0.125f, 0.063f, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::Grabber().
GRABBER_NORMAL_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_NORMAL_COL = {1.0f, 1.0f, 1.0f, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::Grabber().
GRABBER_UNIFORM_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_UNIFORM_COL = {0, 1.0, 1.0, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
GRABBER_UNIFORM_HOVER_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_UNIFORM_HOVER_COL = {0, 0.7, 0.7, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
INV_ZOOM
float Slic3r::GUI::GLGizmoBase::INV_ZOOM = 1.0f static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_render_current_gizmo(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoBase::Grabber::render(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), and Slic3r::GUI::GLGizmoRotate::render_grabber_extension().
last_input_window_width
float Slic3r::GUI::GLGizmoBase::last_input_window_width = 0 protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), and Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos().
m_base_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_base_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c protected inherited
Referenced by Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::GLGizmoAdvancedCut::check_conflict_for_all_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::delete_selected_connectors(), delete_selected_points(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), hollow_mesh(), Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoText::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoAdvancedCut::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::GUI::GLGizmoMeshBoolean::on_load(), on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), on_set_hover_id(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), Slic3r::GUI::GLGizmoSeam::on_set_state(), on_start_dragging(), on_stop_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::GLGizmoFaceDetector::perform_recognition(), Slic3r::GUI::GLGizmoAdvancedCut::process_cut_line(), Slic3r::GUI::GLGizmoAdvancedCut::put_connectors_on_cut_plane(), reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLGizmoAdvancedCut::render_clipper_cut(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoAdvancedCut::reset_connectors(), Slic3r::GUI::GLGizmoSlaSupports::reslice_SLA_supports(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data(), set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoAdvancedCut::unproject_on_cut_plane(), unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoAdvancedCut::update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoText::update_raycast_cache(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), and Slic3r::GUI::GLGizmoText::update_text_positions().
m_closing_d_stash
float Slic3r::GUI::GLGizmoHollow::m_closing_d_stash = 2.f private
Referenced by on_render_input_window().
m_cone
GLModel Slic3r::GUI::GLGizmoBase::m_cone protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_cylinder
GLModel Slic3r::GUI::GLGizmoBase::m_cylinder protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_desc
std::map<std::string, wxString> Slic3r::GUI::GLGizmoHollow::m_desc private
Referenced by on_init(), and on_render_input_window().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_drag_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_drag_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::on_render(), and Slic3r::GUI::GLGizmoRotate::render_grabber().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::stop_dragging().
m_enable_hollowing
bool Slic3r::GUI::GLGizmoHollow::m_enable_hollowing = true private
Referenced by on_render_input_window().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::disable_grabber(), Slic3r::GUI::GLGizmoBase::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoText::on_init(), Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::stop_dragging().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_group_id(), Slic3r::GUI::GLGizmoBase::picking_color_component(), and Slic3r::GUI::GLGizmoBase::set_group_id().
m_highlight_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_highlight_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::set_highlight_color().
m_hole_before_drag
Vec3f Slic3r::GUI::GLGizmoHollow::m_hole_before_drag = Vec3f::Zero() private
Referenced by on_start_dragging(), and on_stop_dragging().
m_holes_in_drilled_mesh
sla::DrainHoles Slic3r::GUI::GLGizmoHollow::m_holes_in_drilled_mesh private
Referenced by set_sla_support_data(), and unproject_on_mesh().
m_holes_stash
sla::DrainHoles Slic3r::GUI::GLGizmoHollow::m_holes_stash private
Referenced by on_render_input_window().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id protected inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::calc_ratio(), Slic3r::GUI::GLGizmoScale3D::do_scale_along_axis(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoAdvancedCut::is_selection_changed(), Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_hover_id(), on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoCut::on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_stop_dragging(), on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), Slic3r::GUI::GLGizmoCut::on_update(), on_update(), Slic3r::GUI::GLGizmoMove3D::on_update(), Slic3r::GUI::GLGizmoScale3D::on_update(), Slic3r::GUI::GLGizmoSlaSupports::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::GLGizmoBase::render_grabbers(), render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::update().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename(), and Slic3r::GUI::GLGizmoBase::set_icon_filename().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), Slic3r::GUI::GLGizmoBase::GizmoImguiBegin(), Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), Slic3r::GUI::GLGizmoText::on_init(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoMove3D::on_render_input_window(), Slic3r::GUI::GLGizmoScale3D::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_combo(), Slic3r::GUI::GLGizmoAdvancedCut::render_connect_type_radio_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_input_window_warning(), Slic3r::GUI::GLGizmoAdvancedCut::render_reset_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::update_font_texture().
m_is_dark_mode
bool Slic3r::GUI::GLGizmoBase::m_is_dark_mode = false protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::on_change_color_mode(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoText::push_button_style(), and Slic3r::GUI::GLGizmoText::push_combo_style().
m_new_hole_height
float Slic3r::GUI::GLGizmoHollow::m_new_hole_height = 6.f private
Referenced by gizmo_event(), on_load(), on_render_input_window(), on_save(), and select_point().
m_new_hole_radius
float Slic3r::GUI::GLGizmoHollow::m_new_hole_radius = 2.f private
Referenced by gizmo_event(), on_load(), on_render_input_window(), on_save(), and select_point().
m_offset_stash
float Slic3r::GUI::GLGizmoHollow::m_offset_stash = 3.0f private
Referenced by on_render_input_window().
m_old_mo_id
ObjectID Slic3r::GUI::GLGizmoHollow::m_old_mo_id = -1 private
Referenced by set_sla_support_data().
m_old_state
EState Slic3r::GUI::GLGizmoHollow::m_old_state = Off private
Referenced by on_set_state().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::add_connector(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::GLGizmoAdvancedCut::bounding_box(), Slic3r::GUI::GLGizmoCut::bounding_box(), Slic3r::GUI::GLGizmoPainterBase::bounding_box(), Slic3r::GUI::GLGizmoText::bounding_box(), Slic3r::GUI::GLGizmoSimplify::close(), Slic3r::GUI::GLGizmoAdvancedCut::delete_selected_connectors(), Slic3r::GUI::GLGizmoText::delete_temp_preview_text_volume(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoAdvancedCut::get_plane_points_world_coord(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoText::get_text_mesh(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::GUI::GLGizmoAdvancedCut::on_is_activable(), Slic3r::GUI::GLGizmoCut::on_is_activable(), Slic3r::GUI::GLGizmoFaceDetector::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), on_is_activable(), Slic3r::GUI::GLGizmoMeshBoolean::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoText::on_is_activable(), Slic3r::GUI::GLGizmoAdvancedCut::on_load(), Slic3r::GUI::GLGizmoFdmSupports::on_opening(), Slic3r::GUI::GLGizmoFlatten::on_render(), on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_render_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoText::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), Slic3r::GUI::GLGizmoAdvancedCut::reset_cut_plane(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut::update_contours(), Slic3r::GUI::GLGizmoPainterBase::update_contours(), Slic3r::GUI::GLGizmoText::update_font_texture(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), and Slic3r::GUI::GLGizmoText::update_text_positions().
m_quality_stash
float Slic3r::GUI::GLGizmoHollow::m_quality_stash = 0.5f private
Referenced by on_render_input_window().
m_selected
std::vector<bool> Slic3r::GUI::GLGizmoHollow::m_selected mutable private
Referenced by delete_selected_points(), gizmo_event(), on_load(), on_render_input_window(), on_save(), reload_cache(), render_points(), select_point(), and unselect_point().
m_selection_empty
bool Slic3r::GUI::GLGizmoHollow::m_selection_empty = true private
Referenced by gizmo_event(), on_load(), on_render_input_window(), on_save(), select_point(), and unselect_point().
m_selection_rectangle
GLSelectionRectangle Slic3r::GUI::GLGizmoHollow::m_selection_rectangle private
Referenced by gizmo_event(), is_selection_rectangle_dragging(), and on_render().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoAdvancedCut::on_init(), Slic3r::GUI::GLGizmoCut::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), on_init(), Slic3r::GUI::GLGizmoMeshBoolean::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), Slic3r::GUI::GLGizmoSlaSupports::on_init(), and Slic3r::GUI::GLGizmoText::on_init().
m_sphere
GLModel Slic3r::GUI::GLGizmoBase::m_sphere protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_state
EState Slic3r::GUI::GLGizmoBase::m_state protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoBase::load(), on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), on_set_state(), Slic3r::GUI::GLGizmoMeshBoolean::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoText::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data(), set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::GUI::GLGizmoBase::set_state(), and Slic3r::GUI::GLGizmoSimplify::worker_finished().
m_tooltip
std::string Slic3r::GUI::GLGizmoBase::m_tooltip mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render().
m_vbo_cylinder
GLModel Slic3r::GUI::GLGizmoHollow::m_vbo_cylinder private
Referenced by GLGizmoHollow(), and render_points().
m_wait_for_up_event
bool Slic3r::GUI::GLGizmoHollow::m_wait_for_up_event = false private
Referenced by gizmo_event().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoHollow.hpp
src/slic3r/GUI/Gizmos/GLGizmoHollow.cpp