OrcaSlicer: orgQhull::QhullPointsIterator Class Reference
orgQhull::QhullPointsIterator Class Reference
#include <src/qhull/src/libqhullcpp/QhullPoints.h>
Private Types
typedef QhullPoints::const_iterator const_iterator
Fields
const QhullPoints * ps
const_iterator i
QhullPointsIterator (const QhullPoints &other)
QhullPointsIterator & operator= (const QhullPoints &other)
bool findNext (const QhullPoint &t)
bool findPrevious (const QhullPoint &t)
bool hasNext () const
bool hasPrevious () const
QhullPoint next ()
QhullPoint peekNext () const
QhullPoint peekPrevious () const
QhullPoint previous ()
void toBack ()
void toFront ()
Detailed Description
Member Typedef Documentation
const_iterator
typedef QhullPoints::const_iterator orgQhull::QhullPointsIterator::const_iterator private
Constructor & Destructor Documentation
QhullPointsIterator()
orgQhull::QhullPointsIterator::QhullPointsIterator (const QhullPoints & other) inline
: ps(&other), i(ps->constBegin()) {}
Member Function Documentation
findNext()
bool orgQhull::QhullPointsIterator::findNext (const QhullPoint & t)
{
    while(i!=ps->constEnd()){
        if(*i++ == p){
            return true;
        }
    }
    return false;
}//findNext
References orgQhull::QhullPoints::constEnd(), i, and ps.
findPrevious()
bool orgQhull::QhullPointsIterator::findPrevious (const QhullPoint & t)
{
    while(i!=ps->constBegin()){
        if(*--i == p){
            return true;
        }
    }
    return false;
}//findPrevious
References orgQhull::QhullPoints::constBegin(), i, and ps.
hasNext()
bool orgQhull::QhullPointsIterator::hasNext () const inline
{ return i != ps->constEnd(); }
References orgQhull::QhullPoints::constEnd(), i, and ps.
Referenced by operator<<(), orgQhull::QhullPoints_test::t_points_iterator(), and orgQhull::QhullPoints::toStdVector().
hasPrevious()
bool orgQhull::QhullPointsIterator::hasPrevious () const inline
{ return i != ps->constBegin(); }
References orgQhull::QhullPoints::constBegin(), i, and ps.
Referenced by orgQhull::QhullPoints_test::t_points_iterator().
next()
QhullPoint orgQhull::QhullPointsIterator::next () inline
{ return *i++; }
References i.
Referenced by operator<<(), orgQhull::QhullPoints_test::t_points_iterator(), and orgQhull::QhullPoints::toStdVector().
operator=()
QhullPointsIterator & orgQhull::QhullPointsIterator::operator= (const QhullPoints & other) inline
{ ps = &other; i = ps->constBegin(); return *this; }
References orgQhull::QhullPoints::constBegin(), i, and ps.
peekNext()
QhullPoint orgQhull::QhullPointsIterator::peekNext () const inline
{ return *i; }
References i.
Referenced by orgQhull::QhullPoints_test::t_points_iterator().
peekPrevious()
QhullPoint orgQhull::QhullPointsIterator::peekPrevious () const inline
{ const_iterator p = i; return *--p; }
References i.
Referenced by orgQhull::QhullPoints_test::t_points_iterator().
previous()
QhullPoint orgQhull::QhullPointsIterator::previous () inline
{ return *--i; }
References i.
Referenced by orgQhull::QhullPoints_test::t_points_iterator().
toBack()
void orgQhull::QhullPointsIterator::toBack () inline
{ i = ps->constEnd(); }
References orgQhull::QhullPoints::constEnd(), i, and ps.
Referenced by orgQhull::QhullPoints_test::t_points_iterator().
toFront()
void orgQhull::QhullPointsIterator::toFront () inline
{ i = ps->constBegin(); }
References orgQhull::QhullPoints::constBegin(), i, and ps.
Referenced by orgQhull::QhullPoints_test::t_points_iterator().
Member Data Documentation
i
const_iterator orgQhull::QhullPointsIterator::i private
Referenced by findNext(), findPrevious(), hasNext(), hasPrevious(), next(), operator=(), peekNext(), peekPrevious(), previous(), toBack(), and toFront().
ps
const QhullPoints* orgQhull::QhullPointsIterator::ps private
Referenced by findNext(), findPrevious(), hasNext(), hasPrevious(), operator=(), toBack(), and toFront().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullPoints.h
src/qhull/src/libqhullcpp/QhullPoints.cpp