OrcaSlicer: Slic3r::GUI::WipeTower Class Reference
Slic3r::GUI::WipeTower Class Reference
Public Member Functions
WipeTower (const GLCanvas3D::WipeTowerInfo &wti)
WipeTower (GLCanvas3D::WipeTowerInfo &&wti)
void apply_arrange_result (const Vec2d &tr, double rotation, int item_id)
ArrangePolygon get_arrange_polygon () const
operator bool () const
const Vec2d & pos () const
double rotation () const
const Vec2d bb_size () const
void apply_wipe_tower () const
Protected Attributes
Vec2d m_pos = {std::nan(""), std::nan("")}
double m_rotation = 0.
BoundingBoxf m_bb
int m_plate_idx = -1
Detailed Description
Constructor & Destructor Documentation
WipeTower() [1/2]
Slic3r::GUI::WipeTower::WipeTower (const GLCanvas3D::WipeTowerInfo & wti) inline explicit
        : GLCanvas3D::WipeTowerInfo(wti)
    {}
WipeTower() [2/2]
Slic3r::GUI::WipeTower::WipeTower (GLCanvas3D::WipeTowerInfo && wti) inline explicit
        : GLCanvas3D::WipeTowerInfo(std::move(wti))
    {}
Member Function Documentation
apply_arrange_result()
void Slic3r::GUI::WipeTower::apply_arrange_result (const Vec2d & tr, double rotation, int item_id) inline
    {
        m_pos = unscaled(tr); m_rotation = rotation;
        apply_wipe_tower();
    }
References Slic3r::GUI::GLCanvas3D::WipeTowerInfo::apply_wipe_tower(), Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_pos, Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_rotation, Slic3r::GUI::GLCanvas3D::WipeTowerInfo::rotation(), and Slic3r::unscaled().
apply_wipe_tower()
void Slic3r::GUI::GLCanvas3D::WipeTowerInfo::apply_wipe_tower () const inherited
{
    // BBS: add partplate logic
    DynamicConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
    Vec3d plate_origin = wxGetApp().plater()->get_partplate_list().get_plate(m_plate_idx)->get_origin();
    ConfigOptionFloat wipe_tower_x(m_pos(X) - plate_origin(0));
    ConfigOptionFloat wipe_tower_y(m_pos(Y) - plate_origin(1));
    ConfigOptionFloats* wipe_tower_x_opt = proj_cfg.option<ConfigOptionFloats>("wipe_tower_x", true);
    ConfigOptionFloats* wipe_tower_y_opt = proj_cfg.option<ConfigOptionFloats>("wipe_tower_y", true);
    wipe_tower_x_opt->set_at(&wipe_tower_x, m_plate_idx, 0);
    wipe_tower_y_opt->set_at(&wipe_tower_y, m_plate_idx, 0);
    //q->update();
}
References Slic3r::ConfigBase::option(), Slic3r::ConfigOptionVector< T >::set_at(), Slic3r::wipe_tower_y(), Slic3r::X, and Slic3r::Y.
Referenced by apply_arrange_result().
bb_size()
const Vec2d Slic3r::GUI::GLCanvas3D::WipeTowerInfo::bb_size () const inline inherited
{ return m_bb.size(); }
References Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_bb, and Slic3r::BoundingBoxBase< PointClass >::size().
get_arrange_polygon()
ArrangePolygon Slic3r::GUI::WipeTower::get_arrange_polygon () const inline
    {
        Polygon ap({
            {scaled(m_bb.min)},
            {scaled(m_bb.max.x()), scaled(m_bb.min.y())},
            {scaled(m_bb.max)},
            {scaled(m_bb.min.x()), scaled(m_bb.max.y())}
            });
        ArrangePolygon ret;
        ret.poly.contour = std::move(ap);
        ret.translation  = scaled(m_pos);
        ret.rotation     = m_rotation;
        //BBS
        ret.name = "WipeTower";
        ret.is_virt_object = true;
        ret.is_wipe_tower = true;
        ++ret.priority;
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << " arrange: wipe tower info:" << m_bb << ", m_pos: " << m_pos.transpose();
        return ret;
    }
References Slic3r::ExPolygon::contour, Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_bb, Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_pos, Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_rotation, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::arrangement::ArrangePolygon::poly, and Slic3r::scaled().
Referenced by Slic3r::GUI::get_wipetower_arrange_poly().
operator bool()
Slic3r::GUI::GLCanvas3D::WipeTowerInfo::operator bool () const inline inherited
{
            return !std::isnan(m_pos.x()) && !std::isnan(m_pos.y());
        }
References Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_pos.
pos()
const Vec2d & Slic3r::GUI::GLCanvas3D::WipeTowerInfo::pos () const inline inherited
{ return m_pos; }
References Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_pos.
rotation()
double Slic3r::GUI::GLCanvas3D::WipeTowerInfo::rotation () const inline inherited
{ return m_rotation; }
References Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_rotation.
Referenced by apply_arrange_result().
Member Data Documentation
m_bb
BoundingBoxf Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_bb protected inherited
Referenced by Slic3r::GUI::GLCanvas3D::WipeTowerInfo::bb_size(), get_arrange_polygon(), and Slic3r::GUI::GLCanvas3D::get_wipe_tower_info().
m_plate_idx
int Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_plate_idx = -1 protected inherited
Referenced by Slic3r::GUI::GLCanvas3D::get_wipe_tower_info().
m_pos
Vec2d Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_pos = {std::nan(""), std::nan("")} protected inherited
Referenced by apply_arrange_result(), get_arrange_polygon(), Slic3r::GUI::GLCanvas3D::get_wipe_tower_info(), Slic3r::GUI::GLCanvas3D::WipeTowerInfo::operator bool(), and Slic3r::GUI::GLCanvas3D::WipeTowerInfo::pos().
m_rotation
double Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_rotation = 0. protected inherited
Referenced by apply_arrange_result(), get_arrange_polygon(), and Slic3r::GUI::GLCanvas3D::WipeTowerInfo::rotation().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Jobs/ArrangeJob.cpp