OrcaSlicer: Slic3r::GUI::OptionsGroup Class Reference
Slic3r::GUI::OptionsGroup Class Reference
#include <src/slic3r/GUI/OptionsGroup.hpp>
Public Member Functions
wxWindow * parent () const
Returns a copy of the pointer of the parent wxWindow. Accessor function is because users are not allowed to change the parent but defining it as const means a lot of const_casts to deal with wx functions.
wxWindow * ctrl_parent () const
void append_line (const Line &line)
void activate_line (Line &line)
Line * get_line (const std::string &opt_key)
bool activate (std::function< void()> throw_if_canceled=[](){}, int horiz_alignment=wxALIGN_LEFT)
void clear (bool destroy_custom_ctrl=false)
Line create_single_option_line (const Option &option, const std::string &path=std::string()) const
void append_single_option_line (const Option &option, const std::string &path=std::string())
void append_separator ()
Field * get_field (const t_config_option_key &id) const
bool set_value (const t_config_option_key &id, const boost::any &value, bool change_event=false)
boost::any get_value (const t_config_option_key &id)
void show_field (const t_config_option_key &opt_key, bool show=true)
void hide_field (const t_config_option_key &opt_key)
void set_name (const wxString &new_name)
void enable ()
void disable ()
void set_grid_vgap (int gap)
void clear_fields_except_of (const std::vector< std::string > left_fields)
void hide_labels ()
OptionsGroup (wxWindow *_parent, const wxString &title, const wxString &icon, bool is_tab_opt=false, column_t extra_clmn=nullptr)
~OptionsGroup ()
wxGridSizer * get_grid_sizer ()
const std::vector< Line > & get_lines ()
bool is_legend_line ()
void set_max_win_width (int max_win_width)
bool is_activated ()
Static Public Member Functions
static wxString get_url (const std::string &path_end)
static bool launch_browser (const std::string &path_end)
Public Attributes
const bool staticbox {true}
bool split_multi_line {false}
bool option_label_at_right {false}
wxWindow * stb
const wxString icon
const wxString title
size_t label_width = 20
wxSizer * sizer {nullptr}
OG_CustomCtrl * custom_ctrl { nullptr }
int ctrl_horiz_alignment { wxALIGN_LEFT}
column_t extra_column {nullptr}
t_change m_on_change { nullptr }
t_kill_focus m_fill_empty_value { nullptr }
std::function< DynamicPrintConfig()> m_get_initial_config { nullptr }
std::function< DynamicPrintConfig()> m_get_sys_config { nullptr }
std::function< bool()> have_sys_config { nullptr }
std::function< void(wxWindow *win)> rescale_extra_column_item { nullptr }
std::function< void(wxWindow *win)> rescale_near_label_widget { nullptr }
wxFont sidetext_font {wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) }
wxFont label_font {wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) }
int sidetext_width { -1 }
int sublabel_width { -1 }
Protected Member Functions
const t_field & build_field (const t_config_option_key &id, const ConfigOptionDef &opt)
Generate a wxSizer or wxWindow from a configuration option Precondition: opt resolves to a known ConfigOption Postcondition: fields contains a wx gui object.
const t_field & build_field (const t_config_option_key &id)
const t_field & build_field (const Option &opt)
virtual void on_kill_focus (const std::string &opt_key)
virtual void on_change_OG (const t_config_option_key &opt_id, const boost::any &value)
virtual void back_to_initial_value (const std::string &opt_key)
virtual void back_to_sys_value (const std::string &opt_key)
Protected Attributes
std::map< t_config_option_key, Option > m_options
wxWindow * m_parent {nullptr}
std::vector< ConfigOptionMode > m_options_mode
std::vector< wxWindow * > m_extra_column_item_ptrs
std::vector< Line > m_lines
t_optionfield_map m_fields
Field list, contains unique_ptrs of the derived type. using types that need to know what it is beyond the public interface need to cast based on the related ConfigOptionDef.
bool m_disabled {false}
wxGridSizer * m_grid_sizer {nullptr}
bool m_use_custom_ctrl { false }
bool m_use_custom_ctrl_as_parent { false }
Detailed Description
Constructor & Destructor Documentation
OptionsGroup()
Slic3r::GUI::OptionsGroup::OptionsGroup (wxWindow * _parent, const wxString & title, const wxString & icon, bool is_tab_opt = false, column_t extra_clmn = nullptr)
                                                   :
                m_parent(_parent), title(title), icon(icon),
                m_use_custom_ctrl(is_tab_opt),
        // BBS: new layout
        staticbox(!is_tab_opt), extra_column(extra_clmn)
{
}
~OptionsGroup()
Slic3r::GUI::OptionsGroup::~OptionsGroup () inline
{ clear(true); }
References clear().
Member Function Documentation
activate()
bool Slic3r::GUI::OptionsGroup::activate (std::function< void()> throw_if_canceled = [](){}, int horiz_alignment = wxALIGN_LEFT)
{
  if (sizer)//(!sizer->IsEmpty())
    return false;
  try {
    if (staticbox) {
      wxStaticBox * stb = new wxStaticBox(m_parent, wxID_ANY, _(title));
      if (!wxOSX) stb->SetBackgroundStyle(wxBG_STYLE_PAINT);
            stb->SetBackgroundColour(m_parent->GetBackgroundColour());
      stb->SetFont(wxOSX ? wxGetApp().normal_font() : wxGetApp().bold_font());
      wxGetApp().UpdateDarkUI(stb);
      // BBS: new layout
      sizer = new wxStaticBoxSizer(stb, wxVERTICAL);
      this->stb = stb;
    }
    else {
      // BBS: new layout
      ::StaticLine* stl = new ::StaticLine(m_parent, false, _(title), icon);
            stl->SetFont(Label::Head_14);
            stl->SetForegroundColour("#262E30");
            sizer = new wxBoxSizer(wxVERTICAL);
            if (title.IsEmpty()) {
                stl->Hide();
            } else {
          sizer->Add(stl, 0, wxEXPAND);
          sizer->AddSpacer(8);
            }
      this->stb = stl;
    }
    auto num_columns = 1U;
    size_t grow_col = 1;
    if (label_width == 0)
      grow_col = 0;
    else
      num_columns++;
    if (extra_column) {
      num_columns++;
      grow_col++;
    }
    m_grid_sizer = new wxFlexGridSizer(0, num_columns, 1, 0);
    static_cast<wxFlexGridSizer*>(m_grid_sizer)->SetFlexibleDirection(wxBOTH);
    static_cast<wxFlexGridSizer*>(m_grid_sizer)->AddGrowableCol(grow_col);
    sizer->Add(m_grid_sizer, 0, wxEXPAND | wxALL, wxOSX || !staticbox ? 0 : 5);
    // activate lines
    for (Line& line: m_lines) {
      throw_if_canceled();
      activate_line(line);
    }
        ctrl_horiz_alignment = horiz_alignment;
        if (custom_ctrl)
            custom_ctrl->init_max_win_width();
  } catch (UIBuildCanceled&) {
    auto p = sizer;
    this->clear();
    p->Clear(true);
    delete p;
    throw;
  }
  return true;
}
References _, activate_line(), clear(), ctrl_horiz_alignment, custom_ctrl, extra_column, Label::Head_14, icon, Slic3r::GUI::OG_CustomCtrl::init_max_win_width(), label_width, m_grid_sizer, m_lines, m_parent, sizer, staticbox, stb, title, and wxOSX.
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
activate_line()
void Slic3r::GUI::OptionsGroup::activate_line (Line & line)
To correct translation by context have to use wxGETTEXT_IN_CONTEXT macro from wxWidget 3.1.1
.target<wxWindow>()
requires verification
istead of (opt != option_set.back())
requires verification
{
    if (line.is_separator())
        return;
    m_use_custom_ctrl_as_parent = false;
  if (line.full_width && (
    line.widget != nullptr ||
    !line.get_extra_widgets().empty())
    ) {
    // BBS: new layout
    const auto h_sizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add(h_sizer, 1, wxEXPAND | wxALL, wxOSX ? 0 : 15);
        if (line.widget != nullptr) {
      // description lines
      h_sizer->Add(line.widget(this->ctrl_parent()), 0, wxEXPAND | wxLEFT, titleWidth * wxGetApp().em_unit());
            return;
        }
    if (!line.get_extra_widgets().empty()) {
            bool is_first_item = true;
      for (auto extra_widget : line.get_extra_widgets()) {
        h_sizer->Add(extra_widget(this->ctrl_parent()), is_first_item ? 1 : 0, wxLEFT, titleWidth * wxGetApp().em_unit());
        is_first_item = false;
      }
      return;
    }
    }
  auto option_set = line.get_options();
  bool is_legend_line = option_set.front().opt.gui_type == ConfigOptionDef::GUIType::legend;
    if (!custom_ctrl && m_use_custom_ctrl) {
        custom_ctrl = new OG_CustomCtrl(is_legend_line || !staticbox ? this->parent() : static_cast<wxWindow*>(this->stb), this);
    // BBS: new layout
    custom_ctrl->SetLabel("");
    if (is_legend_line)
      sizer->Add(custom_ctrl, 0, wxEXPAND | wxLEFT, wxOSX ? 0 : 10);
    else
            sizer->Add(custom_ctrl, 0, wxEXPAND | wxALL, wxOSX || !staticbox ? 0 : 5);
    }
  // Set sidetext width for a better alignment of options in line
  // "m_show_modified_btns==true" means that options groups are in tabs
  if (option_set.size() > 1 && m_use_custom_ctrl) {
        // sublabel_width = Field::def_width();
        sidetext_width = Field::def_width_thinner();
  }
  // if we have a single option with no label, no sidetext just add it directly to sizer
    if (option_set.size() == 1 && label_width == 0 && option_set.front().opt.full_width &&
    option_set.front().opt.sidetext.size() == 0 && option_set.front().side_widget == nullptr &&
    line.get_extra_widgets().size() == 0) {
    const auto& option = option_set.front();
    const auto& field = build_field(option);
    // BBS: new layout
    const auto h_sizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add(h_sizer, 1, wxEXPAND | wxALL, wxOSX ? 0 : 5);
    if (is_window_field(field))
      h_sizer->Add(field->getWindow(), 1, wxEXPAND | wxLEFT, option.opt.multiline ? 0 : titleWidth * wxGetApp().em_unit());
    if (is_sizer_field(field))
      h_sizer->Add(field->getSizer(), 1, wxEXPAND | wxLEFT, titleWidth * wxGetApp().em_unit());
    return;
  }
    auto grid_sizer = m_grid_sizer;
    if (custom_ctrl)
        m_use_custom_ctrl_as_parent = true;
    // if we have an extra column, build it
    if (extra_column) {
    m_extra_column_item_ptrs.push_back(extra_column(this->ctrl_parent(), line));
    grid_sizer->Add(m_extra_column_item_ptrs.back(), 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, 3);
  }
  // Build a label if we have it
  wxStaticText* label=nullptr;
    if (label_width != 0) {
        if (custom_ctrl) {
            if (line.near_label_widget)
                line.near_label_widget_win = line.near_label_widget(this->ctrl_parent());
        }
        else {
            if (!line.near_label_widget || !line.label.IsEmpty()) {
                // Only create the label if it is going to be displayed.
                long label_style = staticbox ? 0 : wxALIGN_RIGHT;
#ifdef __WXGTK__
                // workaround for correct text align of the StaticBox on Linux
                // flags wxALIGN_RIGHT and wxALIGN_CENTRE don't work when Ellipsize flags are _not_ given.
                // Text is properly aligned only when Ellipsize is checked.
                label_style |= staticbox ? 0 : wxST_ELLIPSIZE_END;
#endif /* __WXGTK__ */
                label = new wxStaticText(this->ctrl_parent(), wxID_ANY, line.label + (line.label.IsEmpty() ? "" : ": "),
                    wxDefaultPosition, wxSize(label_width * wxGetApp().em_unit(), -1), label_style);
                label->SetBackgroundStyle(wxBG_STYLE_PAINT);
                label->SetFont(wxGetApp().normal_font());
                label->Wrap(label_width * wxGetApp().em_unit()); // avoid a Linux/GTK bug
            }
            if (!line.near_label_widget)
                grid_sizer->Add(label, 0, (staticbox ? 0 : wxALIGN_RIGHT | wxRIGHT) | wxALIGN_CENTER_VERTICAL, line.label.IsEmpty() ? 0 : 5);
            else if (!line.label.IsEmpty()) {
                // If we're here, we have some widget near the label
                // so we need a horizontal sizer to arrange these things
                auto sizer = new wxBoxSizer(wxHORIZONTAL);
                grid_sizer->Add(sizer, 0, wxEXPAND | (staticbox ? wxALL : wxBOTTOM | wxTOP | wxLEFT), staticbox ? 0 : 1);
                sizer->Add(label, 0, (staticbox ? 0 : wxALIGN_RIGHT | wxRIGHT) | wxALIGN_CENTER_VERTICAL, 5);
            }
            if (label != nullptr && line.label_tooltip != "")
                label->SetToolTip(line.label_tooltip);
        }
    }
  // If there's a widget, build it and add the result to the sizer.
  if (line.widget != nullptr) {
    auto wgt = line.widget(this->ctrl_parent());
        if (custom_ctrl)
            line.widget_sizer = wgt;
        else
            grid_sizer->Add(wgt, 0, wxEXPAND | wxBOTTOM | wxTOP, (wxOSX || line.label.IsEmpty()) ? 0 : 5);
    return;
  }
  // If we're here, we have more than one option or a single option with sidetext
    // so we need a horizontal sizer to arrange these things
    auto sizer = custom_ctrl ? nullptr : new wxBoxSizer(wxHORIZONTAL);
    if (!custom_ctrl)
        grid_sizer->Add(sizer, 0, wxEXPAND | (staticbox ? wxALL : wxBOTTOM | wxTOP | wxLEFT), staticbox ? 0 : 1);
    // If we have a single option with no sidetext just add it directly to the grid sizer
    if (option_set.size() == 1 && option_set.front().opt.sidetext.size() == 0 &&
    option_set.front().side_widget == nullptr && line.get_extra_widgets().size() == 0) {
    const auto& option = option_set.front();
    const auto& field = build_field(option);
        if (!custom_ctrl) {
            if (is_window_field(field))
                sizer->Add(field->getWindow(), option.opt.full_width ? 1 : 0,
                    wxBOTTOM | wxTOP | (option.opt.full_width ? int(wxEXPAND) : int(wxALIGN_CENTER_VERTICAL)), (wxOSX || !staticbox) ? 0 : 2);
            if (is_sizer_field(field))
                sizer->Add(field->getSizer(), 1, (option.opt.full_width ? int(wxEXPAND) : int(wxALIGN_CENTER_VERTICAL)), 0);
        }
        return;
  }
    bool is_multioption_line = option_set.size() > 1;
    for (auto opt : option_set) {
    ConfigOptionDef option = opt.opt;
        wxSizer* sizer_tmp = sizer;
    // add label if any
    if ((is_multioption_line || line.label.IsEmpty()) && !option.label.empty() && !custom_ctrl) {
      wxString str_label = (option.label == L_CONTEXT("Top", "Layers") || option.label == L_CONTEXT("Bottom", "Layers")) ?
        _CTX(option.label, "Layers") :
        _(option.label);
      label = new wxStaticText(this->ctrl_parent(), wxID_ANY, str_label + ": ", wxDefaultPosition, //wxDefaultSize);
        wxSize(sublabel_width != -1 ? sublabel_width * wxGetApp().em_unit() : -1, -1), wxALIGN_RIGHT);
      label->SetBackgroundStyle(wxBG_STYLE_PAINT);
            label->SetFont(wxGetApp().normal_font());
      sizer_tmp->Add(label, 0, wxALIGN_CENTER_VERTICAL, 0);
    }
    // add field
    const Option& opt_ref = opt;
    auto& field = build_field(opt_ref);
        if (!custom_ctrl) {
            if (option_set.size() == 1 && option_set.front().opt.full_width)
            {
                const auto v_sizer = new wxBoxSizer(wxVERTICAL);
                sizer_tmp->Add(v_sizer, 1, wxEXPAND);
                is_sizer_field(field) ?
                    v_sizer->Add(field->getSizer(), 0, wxEXPAND) :
                    v_sizer->Add(field->getWindow(), 0, wxEXPAND);
                break;
            }
            is_sizer_field(field) ?
                sizer_tmp->Add(field->getSizer(), 0, wxALIGN_CENTER_VERTICAL, 0) :
                sizer_tmp->Add(field->getWindow(), 0, wxALIGN_CENTER_VERTICAL, 0);
            // add sidetext if any
            if (!field->combine_side_text() && (!option.sidetext.empty() || sidetext_width > 0)) {
                auto sidetext = new wxStaticText(this->ctrl_parent(), wxID_ANY, _(option.sidetext), wxDefaultPosition,
                    wxSize(sidetext_width != -1 ? sidetext_width * wxGetApp().em_unit() : -1, -1), wxALIGN_LEFT);
                sidetext->SetBackgroundStyle(wxBG_STYLE_PAINT);
                sidetext->SetFont(wxGetApp().normal_font());
                sizer_tmp->Add(sidetext, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, 4);
            }
            // add side widget if any
            if (opt.side_widget != nullptr) {
                sizer_tmp->Add(opt.side_widget(this->ctrl_parent()), 0, wxLEFT | wxALIGN_CENTER_VERTICAL, 1);
            }
            if (opt.opt_id != option_set.back().opt_id)
                sizer_tmp->AddSpacer(6);
        }
  }
  // add extra sizers if any
  for (auto extra_widget : line.get_extra_widgets())
    {
        if (line.get_extra_widgets().size() == 1 && !staticbox)
        {
            // extra widget for non-staticbox option group (like for the frequently used parameters on the sidebar) should be wxALIGN_RIGHT
            const auto v_sizer = new wxBoxSizer(wxVERTICAL);
            sizer->Add(v_sizer, option_set.size() == 1 ? 0 : 1, wxEXPAND);
            v_sizer->Add(extra_widget(this->ctrl_parent()), 0, wxALIGN_RIGHT);
            return;
        }
        line.extra_widget_sizer = extra_widget(this->ctrl_parent());
        if (!custom_ctrl)
            sizer->Add(line.extra_widget_sizer, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, 4);
  }
}
References _, _CTX, build_field(), ctrl_parent(), custom_ctrl, Slic3r::GUI::Field::def_width_thinner(), em_unit(), extra_column, Slic3r::GUI::Line::extra_widget_sizer, Slic3r::GUI::Line::full_width, Slic3r::GUI::Line::get_extra_widgets(), Slic3r::GUI::Line::get_options(), int, is_legend_line(), Slic3r::GUI::Line::is_separator(), Slic3r::GUI::is_sizer_field(), Slic3r::GUI::is_window_field(), L_CONTEXT, Slic3r::ConfigOptionDef::label, Slic3r::GUI::Line::label, Slic3r::GUI::Line::label_tooltip, label_width, Slic3r::ConfigOptionDef::legend, m_extra_column_item_ptrs, m_grid_sizer, m_use_custom_ctrl, m_use_custom_ctrl_as_parent, Slic3r::GUI::Line::near_label_widget, Slic3r::GUI::Line::near_label_widget_win, parent(), Slic3r::ConfigOptionDef::sidetext, sidetext_width, sizer, staticbox, stb, sublabel_width, Slic3r::GUI::titleWidth, Slic3r::GUI::Line::widget, Slic3r::GUI::Line::widget_sizer, wxOSX, and wxStaticText.
Referenced by activate().
append_line()
void Slic3r::GUI::OptionsGroup::append_line (const Line & line)
{
  m_lines.emplace_back(line);
  if (line.full_width && (
    line.widget != nullptr ||
    !line.get_extra_widgets().empty())
    )
    return;
  auto option_set = line.get_options();
  for (auto opt : option_set)
    m_options.emplace(opt.opt_id, opt);
  // add mode value for current line to m_options_mode
    if (!option_set.empty())
        m_options_mode.push_back(option_set[0].opt.mode);
}
References Slic3r::GUI::Line::full_width, Slic3r::GUI::Line::get_extra_widgets(), Slic3r::GUI::Line::get_options(), m_lines, m_options, m_options_mode, and Slic3r::GUI::Line::widget.
Referenced by append_single_option_line(), Slic3r::GUI::Tab::build_preset_description_line(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), and Slic3r::GUI::Tab::create_line_with_widget().
append_separator()
void Slic3r::GUI::OptionsGroup::append_separator ()
{
    m_lines.emplace_back(Line());
}
References m_lines.
append_single_option_line()
void Slic3r::GUI::OptionsGroup::append_single_option_line (const Option & option, const std::string & path = std::string()) inline
{ append_line(create_single_option_line(option, path)); }
References append_line(), and create_single_option_line().
Referenced by Slic3r::GUI::ConfigOptionsGroup::append_single_option_line().
back_to_initial_value()
virtual void Slic3r::GUI::OptionsGroup::back_to_initial_value (const std::string & opt_key) inline protected virtual
Reimplemented in Slic3r::GUI::ConfigOptionsGroup.
{}
Referenced by build_field().
back_to_sys_value()
virtual void Slic3r::GUI::OptionsGroup::back_to_sys_value (const std::string & opt_key) inline protected virtual
Reimplemented in Slic3r::GUI::ConfigOptionsGroup.
{}
Referenced by build_field().
build_field() [1/3]
const t_field & Slic3r::GUI::OptionsGroup::build_field (const Option & opt) protected
{
    return build_field(opt.opt_id, opt.opt);
}
References build_field(), Slic3r::GUI::Option::opt, and Slic3r::GUI::Option::opt_id.
build_field() [2/3]
const t_field & Slic3r::GUI::OptionsGroup::build_field (const t_config_option_key & id) protected
{
  const ConfigOptionDef& opt = m_options.at(id).opt;
    return build_field(id, opt);
}
References build_field(), and m_options.
build_field() [3/3]
const t_field & Slic3r::GUI::OptionsGroup::build_field (const t_config_option_key & id, const ConfigOptionDef & opt) protected
Generate a wxSizer or wxWindow from a configuration option Precondition: opt resolves to a known ConfigOption Postcondition: fields contains a wx gui object.
This function will be called from Field. Call OptionGroup._on_change(...)
This function will be called from Field.
{
    // Check the gui_type field first, fall through
    // is the normal type.
    switch (opt.gui_type) {
    case ConfigOptionDef::GUIType::select_open:
        m_fields.emplace(id, Choice::Create<Choice>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::color:
        m_fields.emplace(id, ColourPicker::Create<ColourPicker>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::f_enum_open:
    case ConfigOptionDef::GUIType::i_enum_open:
        m_fields.emplace(id, Choice::Create<Choice>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::slider:
        m_fields.emplace(id, SliderCtrl::Create<SliderCtrl>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::legend: // StaticText
        m_fields.emplace(id, StaticText::Create<StaticText>(this->ctrl_parent(), opt, id));
        break;
    case ConfigOptionDef::GUIType::one_string:
        m_fields.emplace(id, TextCtrl::Create<TextCtrl>(this->ctrl_parent(), opt, id));
        break;
    default:
        switch (opt.type) {
            case coFloatOrPercent:
            case coFloat:
            case coFloats:
      case coPercent:
      case coPercents:
      case coString:
      case coStrings:
                m_fields.emplace(id, TextCtrl::Create<TextCtrl>(this->ctrl_parent(), opt, id));
                break;
      case coBool:
      case coBools:
                m_fields.emplace(id, CheckBox::Create<CheckBox>(this->ctrl_parent(), opt, id));
        break;
      case coInt:
      case coInts:
                m_fields.emplace(id, SpinCtrl::Create<SpinCtrl>(this->ctrl_parent(), opt, id));
        break;
            case coEnum:
            case coEnums:
                m_fields.emplace(id, Choice::Create<Choice>(this->ctrl_parent(), opt, id));
        break;
            case coPoints:
                m_fields.emplace(id, PointCtrl::Create<PointCtrl>(this->ctrl_parent(), opt, id));
        break;
            case coNone:   break;
            default:
        throw Slic3r::LogicError("This control doesn't exist till now"); break;
        }
    }
    // Grab a reference to fields for convenience
    const t_field& field = m_fields[id];
  field->m_on_change = [this](const std::string& opt_id, const boost::any& value) {
      if (!m_disabled)
        this->on_change_OG(opt_id, value);
  };
    field->m_on_kill_focus = [this](const std::string& opt_id) {
      if (!m_disabled)
        this->on_kill_focus(opt_id);
  };
    field->m_parent = parent();
  field->m_back_to_initial_value = [this](std::string opt_id) {
    if (!m_disabled)
      this->back_to_initial_value(opt_id);
  };
  field->m_back_to_sys_value = [this](std::string opt_id) {
    if (!this->m_disabled)
      this->back_to_sys_value(opt_id);
  };
  // assign function objects for callbacks, etc.
    return field;
}
References back_to_initial_value(), back_to_sys_value(), Slic3r::coBool, Slic3r::coBools, Slic3r::coEnum, Slic3r::coEnums, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coFloats, Slic3r::coInt, Slic3r::coInts, Slic3r::ConfigOptionDef::color, Slic3r::coNone, Slic3r::coPercent, Slic3r::coPercents, Slic3r::coPoints, Slic3r::coString, Slic3r::coStrings, ctrl_parent(), Slic3r::ConfigOptionDef::f_enum_open, Slic3r::ConfigOptionDef::gui_type, Slic3r::ConfigOptionDef::i_enum_open, Slic3r::ConfigOptionDef::legend, m_disabled, m_fields, on_change_OG(), on_kill_focus(), Slic3r::ConfigOptionDef::one_string, parent(), Slic3r::ConfigOptionDef::select_open, Slic3r::ConfigOptionDef::slider, and Slic3r::ConfigOptionDef::type.
Referenced by activate_line(), build_field(), and build_field().
clear()
void Slic3r::GUI::OptionsGroup::clear (bool destroy_custom_ctrl = false)
{
  if (!sizer)
    return;
  m_grid_sizer = nullptr;
  sizer = nullptr;
    stb = nullptr; // BBS: fix pointer
  for (Line& line : m_lines) {
        if (line.near_label_widget_win)
            line.near_label_widget_win = nullptr;
        if (line.widget_sizer) {
            line.widget_sizer->Clear(true);
            line.widget_sizer = nullptr;
        }
        if (line.extra_widget_sizer) {
            line.extra_widget_sizer->Clear(true);
            line.extra_widget_sizer = nullptr;
        }
  }
    if (custom_ctrl) {
        for (auto const &item : m_fields) {
            wxWindow* win = item.second.get()->getWindow();
            if (win)
                win = nullptr;
        }
    //BBS: custom_ctrl already destroyed from sizer->clear(), no need to destroy here anymore
    if (destroy_custom_ctrl)
            //custom_ctrl->Destroy();
      custom_ctrl = nullptr;
        else
            custom_ctrl = nullptr;
    }
  m_extra_column_item_ptrs.clear();
  m_fields.clear();
}
References custom_ctrl, m_extra_column_item_ptrs, m_fields, m_grid_sizer, m_lines, sizer, and stb.
Referenced by ~OptionsGroup(), and activate().
clear_fields_except_of()
void Slic3r::GUI::OptionsGroup::clear_fields_except_of (const std::vector< std::string > left_fields)
{
    auto it = m_fields.begin();
    while (it != m_fields.end()) {
        if (std::find(left_fields.begin(), left_fields.end(), it->first) == left_fields.end())
            it = m_fields.erase(it);
        else
            it++;
    }
}
References m_fields.
create_single_option_line()
Line Slic3r::GUI::OptionsGroup::create_single_option_line (const Option & option, const std::string & path = std::string()) const
{
    wxString tooltip = _(option.opt.tooltip);
    edit_tooltip(tooltip);
  Line retval{ _(option.opt.label), tooltip };
  retval.label_path = path;
    retval.append_option(option);
    return retval;
}
References _, edit_tooltip(), Slic3r::ConfigOptionDef::label, Slic3r::GUI::Option::opt, and Slic3r::ConfigOptionDef::tooltip.
Referenced by append_single_option_line(), Slic3r::GUI::ConfigOptionsGroup::create_single_option_line(), and Slic3r::GUI::ConfigOptionsGroup::create_single_option_line().
ctrl_parent()
wxWindow * Slic3r::GUI::OptionsGroup::ctrl_parent () const
{
  // BBS: new layout
  return this->custom_ctrl && m_use_custom_ctrl_as_parent ? static_cast<wxWindow*>(this->custom_ctrl) : (staticbox ? static_cast<wxWindow*>(this->stb) : this->parent());
}
References custom_ctrl, m_use_custom_ctrl_as_parent, parent(), staticbox, and stb.
Referenced by activate_line(), and build_field().
disable()
void Slic3r::GUI::OptionsGroup::disable () inline
{ for (auto& field : m_fields) field.second->disable(); }
References m_fields.
enable()
void Slic3r::GUI::OptionsGroup::enable () inline
{ for (auto& field : m_fields) field.second->enable(); }
References m_fields.
get_field()
Field * Slic3r::GUI::OptionsGroup::get_field (const t_config_option_key & id) const inline
{
              if (m_fields.find(id) == m_fields.end()) return nullptr;
              return m_fields.at(id).get();
    }
References m_fields.
Referenced by Slic3r::GUI::ConfigOptionsGroup::back_to_config_value(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::ConfigOptionsGroup::get_fieldc(), Slic3r::GUI::OG_CustomCtrl::get_pos(), Slic3r::GUI::OG_CustomCtrl::OnLeftDown(), Slic3r::GUI::OG_CustomCtrl::OnMotion(), Slic3r::GUI::ConfigOptionsGroup::reload_config(), show_field(), Slic3r::GUI::PhysicalPrinterDialog::update_host_type(), and Slic3r::GUI::PhysicalPrinterDialog::update_printers().
get_grid_sizer()
wxGridSizer * Slic3r::GUI::OptionsGroup::get_grid_sizer () inline
{ return m_grid_sizer; }
References m_grid_sizer.
Referenced by Slic3r::GUI::ObjectTableSettings::update_extra_column_visible_status().
get_line()
Line * Slic3r::GUI::OptionsGroup::get_line (const std::string & opt_key)
{
    for (auto& l : m_lines)
    {
        if(l.is_separator())
            continue;
        if (l.get_first_option_key() == opt_key)
            return &l;
    }
    return nullptr;
}
References m_lines.
Referenced by Slic3r::GUI::ObjectTableSettings::update_extra_column_visible_status().
get_lines()
const std::vector< Line > & Slic3r::GUI::OptionsGroup::get_lines () inline
{ return m_lines; }
References m_lines.
Referenced by Slic3r::GUI::OG_CustomCtrl::init_ctrl_lines().
get_url()
wxString Slic3r::GUI::OptionsGroup::get_url (const std::string & path_end) static
{
    //BBS
    wxString str = from_u8(path_end);
    auto     pos = str.find(L'#');
    if (pos != size_t(-1)) {
        pos++;
        wxString anchor = str.Mid(pos).Lower();
        anchor.Replace(L" ", "-");
        str = str.Left(pos) + anchor;
    }
    // Softfever: point to sf wiki for seam parameters
    if (path_end == "Seam") {
        return wxString::Format(L"https://github.com/SoftFever/OrcaSlicer/wiki/%s", from_u8(path_end));
    }
    else {
        //BBS
        return wxString::Format(L"https://wiki.bambulab.com/%s/software/bambu-studio/%s", L"en", str);
    }
}
References Slic3r::GUI::from_u8(), and L.
Referenced by launch_browser(), Slic3r::GUI::OG_CustomCtrl::OnMotion(), and Slic3r::GUI::ogStaticText::SetPathEnd().
get_value()
boost::any Slic3r::GUI::OptionsGroup::get_value (const t_config_option_key & id) inline
{
              boost::any out;
                if (m_fields.find(id) == m_fields.end()) ;
              else
                out = m_fields.at(id)->get_value();
              return out;
    }
References m_fields, and out.
Referenced by Slic3r::GUI::ConfigOptionsGroup::back_to_config_value().
hide_field()
void Slic3r::GUI::OptionsGroup::hide_field (const t_config_option_key & opt_key) inline
{  show_field(opt_key, false);  }
References show_field().
Referenced by Slic3r::GUI::PhysicalPrinterDialog::update().
hide_labels()
void Slic3r::GUI::OptionsGroup::hide_labels () inline
{ label_width = 0; }
References label_width.
is_activated()
bool Slic3r::GUI::OptionsGroup::is_activated () inline
{ return sizer != nullptr; }
References sizer.
is_legend_line()
bool Slic3r::GUI::OptionsGroup::is_legend_line ()
{
  if (m_lines.size() == 1) {
    const std::vector<Option>& option_set = m_lines.front().get_options();
    return !option_set.empty() && option_set.front().opt.gui_type == ConfigOptionDef::GUIType::legend;
  }
  return false;
}
References Slic3r::ConfigOptionDef::legend, and m_lines.
Referenced by activate_line().
launch_browser()
bool Slic3r::GUI::OptionsGroup::launch_browser (const std::string & path_end) static
{
    return wxLaunchDefaultBrowser(OptionsGroup::get_url(path_end));
}
References get_url().
Referenced by Slic3r::GUI::OG_CustomCtrl::CtrlLine::launch_browser().
on_change_OG()
void Slic3r::GUI::OptionsGroup::on_change_OG (const t_config_option_key & opt_id, const boost::any & value) protected virtual
Reimplemented in Slic3r::GUI::ConfigOptionsGroup, and Slic3r::GUI::ExtruderOptionsGroup.
{
  if (m_on_change != nullptr)
    m_on_change(opt_id, value);
}
References m_on_change.
Referenced by build_field(), Slic3r::GUI::ConfigOptionsGroup::on_change_OG(), and Slic3r::GUI::ExtruderOptionsGroup::on_change_OG().
on_kill_focus()
virtual void Slic3r::GUI::OptionsGroup::on_kill_focus (const std::string & opt_key) inline protected virtual
Reimplemented in Slic3r::GUI::ConfigOptionsGroup.
{};
Referenced by build_field().
parent()
wxWindow * Slic3r::GUI::OptionsGroup::parent () const inline
Returns a copy of the pointer of the parent wxWindow. Accessor function is because users are not allowed to change the parent but defining it as const means a lot of const_casts to deal with wx functions.
{ return m_parent; }
References m_parent.
Referenced by activate_line(), build_field(), and ctrl_parent().
set_grid_vgap()
void Slic3r::GUI::OptionsGroup::set_grid_vgap (int gap) inline
{ m_grid_sizer->SetVGap(gap); }
References m_grid_sizer.
set_max_win_width()
void Slic3r::GUI::OptionsGroup::set_max_win_width (int max_win_width)
{
    if (custom_ctrl)
        custom_ctrl->set_max_win_width(max_win_width);
}
References custom_ctrl, and Slic3r::GUI::OG_CustomCtrl::set_max_win_width().
set_name()
void Slic3r::GUI::OptionsGroup::set_name (const wxString & new_name)
{
  stb->SetLabel(new_name);
}
References stb.
set_value()
bool Slic3r::GUI::OptionsGroup::set_value (const t_config_option_key & id, const boost::any & value, bool change_event = false) inline
{
              if (m_fields.find(id) == m_fields.end()) return false;
              m_fields.at(id)->set_value(value, change_event);
              return true;
    }
References m_fields.
Referenced by Slic3r::GUI::ConfigOptionsGroup::back_to_config_value(), Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::ConfigOptionsGroup::reload_config(), and Slic3r::GUI::PhysicalPrinterDialog::update().
show_field()
void Slic3r::GUI::OptionsGroup::show_field (const t_config_option_key & opt_key, bool show = true)
{
    Field* field = get_field(opt_key);
    if (!field) return;
    wxWindow* win = field->getWindow();
    if (!win) return;
    wxSizerItem* win_item = m_grid_sizer->GetItem(win, true);
    if (!win_item) return;
    const size_t cols = (size_t)m_grid_sizer->GetCols();
    const size_t rows = (size_t)m_grid_sizer->GetEffectiveRowsCount();
    auto show_row = [this, show, cols, win_item](wxSizerItem* item, size_t row_shift) {
        // check if item contanes required win
        if (!item->IsWindow() || item != win_item)
            return false;
        // show/hide hole line contanes this window
        for (size_t i = 0; i < cols; ++i)
            m_grid_sizer->Show(row_shift + i, show);
        return true;
    };
    size_t row_shift = 0;
    for (size_t j = 0; j < rows; ++j) {
        for (size_t i = 0; i < cols; ++i) {
            wxSizerItem* item = m_grid_sizer->GetItem(row_shift + i);
            if (!item)
                continue;
            if (item->IsSizer()) {
                for (wxSizerItem* child_item : item->GetSizer()->GetChildren())
                    if (show_row(child_item, row_shift))
                        return;
            }
            else if (show_row(item, row_shift))
                return;
        }
        row_shift += cols;
    }
}
References get_field(), Slic3r::GUI::Field::getWindow(), and m_grid_sizer.
Referenced by hide_field(), and Slic3r::GUI::PhysicalPrinterDialog::update().
Member Data Documentation
ctrl_horiz_alignment
int Slic3r::GUI::OptionsGroup::ctrl_horiz_alignment { wxALIGN_LEFT}
Referenced by activate(), and Slic3r::GUI::OG_CustomCtrl::init_max_win_width().
custom_ctrl
OG_CustomCtrl* Slic3r::GUI::OptionsGroup::custom_ctrl { nullptr }
Referenced by activate(), activate_line(), clear(), ctrl_parent(), Slic3r::GUI::ConfigOptionsGroup::get_custom_ctrl_with_blinking_ptr(), Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), Slic3r::GUI::OG_CustomCtrl::OnPaint(), Slic3r::GUI::ConfigOptionsGroup::refresh(), set_max_win_width(), Slic3r::GUI::ConfigOptionsGroup::sys_color_changed(), and Slic3r::GUI::ConfigOptionsGroup::update_visibility().
extra_column
column_t Slic3r::GUI::OptionsGroup::extra_column {nullptr}
Referenced by activate(), and activate_line().
have_sys_config
std::function<bool()> Slic3r::GUI::OptionsGroup::have_sys_config { nullptr }
Referenced by Slic3r::GUI::ConfigOptionsGroup::back_to_sys_value().
icon
const wxString Slic3r::GUI::OptionsGroup::icon
Referenced by activate().
label_font
wxFont Slic3r::GUI::OptionsGroup::label_font {wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) }
label_width
size_t Slic3r::GUI::OptionsGroup::label_width = 20
Referenced by activate(), activate_line(), Slic3r::GUI::OG_CustomCtrl::get_pos(), hide_labels(), and Slic3r::GUI::OG_CustomCtrl::init_ctrl_lines().
m_disabled
bool Slic3r::GUI::OptionsGroup::m_disabled {false} protected
Referenced by build_field().
m_extra_column_item_ptrs
std::vector<wxWindow*> Slic3r::GUI::OptionsGroup::m_extra_column_item_ptrs protected
Referenced by activate_line(), clear(), Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), and Slic3r::GUI::ConfigOptionsGroup::sys_color_changed().
m_fields
t_optionfield_map Slic3r::GUI::OptionsGroup::m_fields protected
Field list, contains unique_ptrs of the derived type. using types that need to know what it is beyond the public interface need to cast based on the related ConfigOptionDef.
Referenced by build_field(), clear(), clear_fields_except_of(), disable(), enable(), get_field(), get_value(), Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), set_value(), and Slic3r::GUI::ConfigOptionsGroup::sys_color_changed().
m_fill_empty_value
t_kill_focus Slic3r::GUI::OptionsGroup::m_fill_empty_value { nullptr }
Referenced by Slic3r::GUI::ConfigOptionsGroup::on_kill_focus().
m_get_initial_config
std::function<DynamicPrintConfig()> Slic3r::GUI::OptionsGroup::m_get_initial_config { nullptr }
Referenced by Slic3r::GUI::ConfigOptionsGroup::back_to_initial_value().
m_get_sys_config
std::function<DynamicPrintConfig()> Slic3r::GUI::OptionsGroup::m_get_sys_config { nullptr }
Referenced by Slic3r::GUI::ConfigOptionsGroup::back_to_sys_value().
m_grid_sizer
wxGridSizer* Slic3r::GUI::OptionsGroup::m_grid_sizer {nullptr} protected
Referenced by activate(), activate_line(), clear(), get_grid_sizer(), set_grid_vgap(), Slic3r::GUI::ConfigOptionsGroup::Show(), show_field(), and Slic3r::GUI::ConfigOptionsGroup::update_visibility().
m_lines
std::vector<Line> Slic3r::GUI::OptionsGroup::m_lines protected
Referenced by activate(), append_line(), append_separator(), clear(), Slic3r::GUI::ConfigOptionsGroup::get_custom_ctrl_with_blinking_ptr(), get_line(), get_lines(), is_legend_line(), Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), and Slic3r::GUI::ConfigOptionsGroup::sys_color_changed().
m_on_change
t_change Slic3r::GUI::OptionsGroup::m_on_change { nullptr }
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings(), and on_change_OG().
m_options
std::map<t_config_option_key, Option> Slic3r::GUI::OptionsGroup::m_options protected
Referenced by append_line(), build_field(), and Slic3r::GUI::ConfigOptionsGroup::reload_config().
m_options_mode
std::vector<ConfigOptionMode> Slic3r::GUI::OptionsGroup::m_options_mode protected
Referenced by append_line(), Slic3r::GUI::ConfigOptionsGroup::is_visible(), and Slic3r::GUI::ConfigOptionsGroup::update_visibility().
m_parent
wxWindow* Slic3r::GUI::OptionsGroup::m_parent {nullptr} protected
Referenced by activate(), and parent().
m_use_custom_ctrl
bool Slic3r::GUI::OptionsGroup::m_use_custom_ctrl { false } protected
Referenced by activate_line(), and Slic3r::GUI::ConfigOptionsGroup::get_option().
m_use_custom_ctrl_as_parent
bool Slic3r::GUI::OptionsGroup::m_use_custom_ctrl_as_parent { false } protected
Referenced by activate_line(), and ctrl_parent().
option_label_at_right
bool Slic3r::GUI::OptionsGroup::option_label_at_right {false}
Referenced by Slic3r::GUI::OG_CustomCtrl::get_pos().
rescale_extra_column_item
std::function<void(wxWindow* win)> Slic3r::GUI::OptionsGroup::rescale_extra_column_item { nullptr }
Referenced by Slic3r::GUI::ConfigOptionsGroup::msw_rescale().
rescale_near_label_widget
std::function<void(wxWindow* win)> Slic3r::GUI::OptionsGroup::rescale_near_label_widget { nullptr }
sidetext_font
wxFont Slic3r::GUI::OptionsGroup::sidetext_font {wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT) }
sidetext_width
int Slic3r::GUI::OptionsGroup::sidetext_width { -1 }
Referenced by activate_line(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
sizer
wxSizer* Slic3r::GUI::OptionsGroup::sizer {nullptr}
Referenced by Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), activate(), activate_line(), clear(), is_activated(), Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), Slic3r::GUI::ConfigOptionsGroup::Show(), Slic3r::GUI::ConfigOptionsGroup::sys_color_changed(), and Slic3r::GUI::ConfigOptionsGroup::update_visibility().
split_multi_line
bool Slic3r::GUI::OptionsGroup::split_multi_line {false}
Referenced by Slic3r::GUI::OG_CustomCtrl::correct_window_position(), Slic3r::GUI::OG_CustomCtrl::get_pos(), and Slic3r::GUI::OG_CustomCtrl::init_ctrl_lines().
staticbox
const bool Slic3r::GUI::OptionsGroup::staticbox {true}
Referenced by activate(), activate_line(), ctrl_parent(), Slic3r::GUI::OG_CustomCtrl::init_ctrl_lines(), and Slic3r::GUI::ConfigOptionsGroup::sys_color_changed().
stb
wxWindow* Slic3r::GUI::OptionsGroup::stb
Referenced by activate(), activate_line(), clear(), ctrl_parent(), Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), set_name(), and Slic3r::GUI::ConfigOptionsGroup::sys_color_changed().
sublabel_width
int Slic3r::GUI::OptionsGroup::sublabel_width { -1 }
Referenced by activate_line(), and Slic3r::GUI::OG_CustomCtrl::get_pos().
title
const wxString Slic3r::GUI::OptionsGroup::title
Referenced by activate(), Slic3r::GUI::ConfigOptionsGroup::append_single_option_line(), Slic3r::GUI::ConfigOptionsGroup::create_single_option_line(), and Slic3r::GUI::ConfigOptionsGroup::get_option().
The documentation for this class was generated from the following files:
src/slic3r/GUI/OptionsGroup.hpp
src/slic3r/GUI/OptionsGroup.cpp