OrcaSlicer: Slic3r::GUI::NetworkTestDialog Class Reference
Slic3r::GUI::NetworkTestDialog Class Reference
#include <src/slic3r/GUI/NetworkTestDialog.hpp>
Public Member Functions
NetworkTestDialog (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(605, 375), long style=wxDEFAULT_DIALOG_STYLE)
~NetworkTestDialog ()
void on_dpi_changed (const wxRect &suggested_rect)
void set_default ()
wxString get_studio_version ()
wxString get_os_info ()
wxString get_dns_info ()
void start_all_job ()
void start_all_job_sequence ()
void start_test_bing_thread ()
void start_test_bambulab_thread ()
void start_test_iot_thread ()
void start_test_oss_thread ()
void start_test_oss_upgrade_thread ()
void start_test_oss_download_thread ()
void start_test_oss_upload_thread ()
void start_test_ping_thread ()
void start_test_bing ()
void start_test_bambulab ()
void start_test_iot ()
void start_test_oss ()
void start_test_oss_upgrade ()
void start_test_oss_download ()
void start_test_oss_upload ()
void on_close (wxCloseEvent &event)
void update_status (int job_id, wxString info)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Protected Member Functions
wxBoxSizer * create_top_sizer (wxWindow *parent)
wxBoxSizer * create_info_sizer (wxWindow *parent)
wxBoxSizer * create_content_sizer (wxWindow *parent)
wxBoxSizer * create_result_sizer (wxWindow *parent)
void init_bind ()
virtual void on_sys_color_changed ()
Protected Attributes
wxButton * btn_start
wxButton * btn_start_sequence
wxButton * btn_download_log
wxStaticText * text_basic_info
wxStaticText * text_version_title
wxStaticText * text_version_val
wxStaticText * txt_sys_info_title
wxStaticText * txt_sys_info_value
wxStaticText * txt_dns_info_title
wxStaticText * txt_dns_info_value
wxButton * btn_link
wxStaticText * text_link_title
wxStaticText * text_link_val
wxButton * btn_bing
wxStaticText * text_bing_title
wxStaticText * text_bing_val
wxButton * btn_iot
wxStaticText * text_iot_title
wxStaticText * text_iot_value
wxButton * btn_oss
wxStaticText * text_oss_title
wxStaticText * text_oss_value
wxButton * btn_oss_upgrade
wxStaticText * text_oss_upgrade_title
wxStaticText * text_oss_upgrade_value
wxButton * btn_oss_download
wxStaticText * text_oss_download_title
wxStaticText * text_oss_download_value
wxButton * btn_oss_upload
wxStaticText * text_oss_upload_title
wxStaticText * text_oss_upload_value
wxStaticText * text_ping_title
wxStaticText * text_ping_value
wxStaticText * text_result
wxTextCtrl * txt_log
boost::thread * test_job [TEST_JOB_MAX]
boost::thread * m_sequence_job { nullptr }
bool m_in_testing [TEST_JOB_MAX]
bool m_download_cancel = false
bool m_closing = false
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
NetworkTestDialog()
Slic3r::GUI::NetworkTestDialog::NetworkTestDialog (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(605, 375), long style = wxDEFAULT_DIALOG_STYLE)
    : DPIDialog(parent,wxID_ANY,from_u8((boost::format(_utf8(L("Network Test")))).str()),wxDefaultPosition,
            wxSize(1000, 700),
            /*wxCAPTION*/wxDEFAULT_DIALOG_STYLE|wxMAXIMIZE_BOX|wxMINIMIZE_BOX|wxRESIZE_BORDER)
{
  this->SetSizeHints(wxDefaultSize, wxDefaultSize);
  wxBoxSizer* main_sizer;
  main_sizer = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* top_sizer = create_top_sizer(this);
  main_sizer->Add(top_sizer, 0, wxEXPAND, 5);
  wxBoxSizer* info_sizer = create_info_sizer(this);
  main_sizer->Add(info_sizer, 0, wxEXPAND, 5);
  wxBoxSizer* content_sizer = create_content_sizer(this);
  main_sizer->Add(content_sizer, 0, wxEXPAND, 5);
  wxBoxSizer* result_sizer = create_result_sizer(this);
  main_sizer->Add(result_sizer, 1, wxEXPAND, 5);
  set_default();
  init_bind();
  this->SetSizer(main_sizer);
  this->Layout();
  this->Centre(wxBOTH);
}
References create_content_sizer(), create_info_sizer(), create_result_sizer(), create_top_sizer(), Slic3r::GUI::from_u8(), init_bind(), and set_default().
~NetworkTestDialog()
Slic3r::GUI::NetworkTestDialog::~NetworkTestDialog ()
{
    ;
}
Member Function Documentation
create_content_sizer()
wxBoxSizer * Slic3r::GUI::NetworkTestDialog::create_content_sizer (wxWindow * parent) protected
{
  auto sizer = new wxBoxSizer(wxVERTICAL);
  wxFlexGridSizer* grid_sizer;
  grid_sizer = new wxFlexGridSizer(0, 3, 0, 0);
  grid_sizer->SetFlexibleDirection(wxBOTH);
  grid_sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
  btn_link = new wxButton(this, wxID_ANY, _L("Test BambuLab"), wxDefaultPosition, wxDefaultSize, 0);
  grid_sizer->Add(btn_link, 0, wxEXPAND | wxALL, 5);
  text_link_title = new wxStaticText(this, wxID_ANY, _L("Test BambuLab:"), wxDefaultPosition, wxDefaultSize, 0);
  text_link_title->Wrap(-1);
  grid_sizer->Add(text_link_title, 0, wxALIGN_RIGHT | wxALL, 5);
  text_link_val = new wxStaticText(this, wxID_ANY, _L("N/A"), wxDefaultPosition, wxDefaultSize, 0);
  text_link_val->Wrap(-1);
  grid_sizer->Add(text_link_val, 0, wxALL, 5);
  btn_bing = new wxButton(this, wxID_ANY, _L("Test Bing.com"), wxDefaultPosition, wxDefaultSize, 0);
  grid_sizer->Add(btn_bing, 0, wxEXPAND | wxALL, 5);
  text_bing_title = new wxStaticText(this, wxID_ANY, _L("Test bing.com:"), wxDefaultPosition, wxDefaultSize, 0);
  text_bing_title->Wrap(-1);
  grid_sizer->Add(text_bing_title, 0, wxALIGN_RIGHT | wxALL, 5);
  text_bing_val = new wxStaticText(this, wxID_ANY, _L("N/A"), wxDefaultPosition, wxDefaultSize, 0);
  text_bing_val->Wrap(-1);
  grid_sizer->Add(text_bing_val, 0, wxALL, 5);
  btn_iot = new wxButton(this, wxID_ANY, _L("Test HTTP"), wxDefaultPosition, wxDefaultSize, 0);
  grid_sizer->Add(btn_iot, 0, wxEXPAND | wxALL, 5);
  text_iot_title = new wxStaticText(this, wxID_ANY, _L("Test HTTP Service:"), wxDefaultPosition, wxDefaultSize, 0);
  text_iot_title->Wrap(-1);
  grid_sizer->Add(text_iot_title, 0, wxALIGN_RIGHT | wxALL, 5);
  text_iot_value = new wxStaticText(this, wxID_ANY, _L("N/A"), wxDefaultPosition, wxDefaultSize, 0);
  text_iot_value->Wrap(-1);
  grid_sizer->Add(text_iot_value, 0, wxALL, 5);
  btn_oss = new wxButton(this, wxID_ANY, _L("Test storage"), wxDefaultPosition, wxDefaultSize, 0);
  grid_sizer->Add(btn_oss, 0, wxEXPAND | wxALL, 5);
  text_oss_title = new wxStaticText(this, wxID_ANY, _L("Test Storage Upload:"), wxDefaultPosition, wxDefaultSize, 0);
  text_oss_title->Wrap(-1);
  grid_sizer->Add(text_oss_title, 0, wxALIGN_RIGHT | wxALL, 5);
  text_oss_value = new wxStaticText(this, wxID_ANY, _L("N/A"), wxDefaultPosition, wxDefaultSize, 0);
  text_oss_value->Wrap(-1);
  grid_sizer->Add(text_oss_value, 0, wxALL, 5);
  btn_oss_upgrade = new wxButton(this, wxID_ANY, _L("Test storage upgrade"), wxDefaultPosition, wxDefaultSize, 0);
  grid_sizer->Add(btn_oss_upgrade, 0, wxEXPAND | wxALL, 5);
  text_oss_upgrade_title = new wxStaticText(this, wxID_ANY, _L("Test Storage Upgrade:"), wxDefaultPosition, wxDefaultSize, 0);
  text_oss_upgrade_title->Wrap(-1);
  grid_sizer->Add(text_oss_upgrade_title, 0, wxALIGN_RIGHT | wxALL, 5);
  text_oss_upgrade_value = new wxStaticText(this, wxID_ANY, _L("N/A"), wxDefaultPosition, wxDefaultSize, 0);
  text_oss_upgrade_value->Wrap(-1);
  grid_sizer->Add(text_oss_upgrade_value, 0, wxALL, 5);
  btn_oss_download = new wxButton(this, wxID_ANY, _L("Test storage download"), wxDefaultPosition, wxDefaultSize, 0);
  grid_sizer->Add(btn_oss_download, 0, wxEXPAND | wxALL, 5);
  text_oss_download_title = new wxStaticText(this, wxID_ANY, _L("Test Storage Download:"), wxDefaultPosition, wxDefaultSize, 0);
  text_oss_download_title->Wrap(-1);
  grid_sizer->Add(text_oss_download_title, 0, wxALIGN_RIGHT | wxALL, 5);
  text_oss_download_value = new wxStaticText(this, wxID_ANY, _L("N/A"), wxDefaultPosition, wxDefaultSize, 0);
  text_oss_download_value->Wrap(-1);
  grid_sizer->Add(text_oss_download_value, 0, wxALL, 5);
  btn_oss_upload = new wxButton(this, wxID_ANY, _L("Test Storage Upload"), wxDefaultPosition, wxDefaultSize, 0);
  grid_sizer->Add(btn_oss_upload, 0, wxEXPAND | wxALL, 5);
  text_oss_upload_title = new wxStaticText(this, wxID_ANY, _L("Test Storage Upload:"), wxDefaultPosition, wxDefaultSize, 0);
  text_oss_upload_title->Wrap(-1);
  grid_sizer->Add(text_oss_upload_title, 0, wxALIGN_RIGHT | wxALL, 5);
  text_oss_upload_value = new wxStaticText(this, wxID_ANY, _L("N/A"), wxDefaultPosition, wxDefaultSize, 0);
  text_oss_upload_value->Wrap(-1);
  grid_sizer->Add(text_oss_upload_value, 0, wxALL, 5);
  btn_oss_upload->Hide();
  text_oss_upload_title->Hide();
  text_oss_upload_value->Hide();
  sizer->Add(grid_sizer, 1, wxEXPAND, 5);
  btn_link->Bind(wxEVT_BUTTON, [this](wxCommandEvent& evt) {
    start_test_bambulab_thread();
  });
  btn_bing->Bind(wxEVT_BUTTON, [this](wxCommandEvent& evt) {
    start_test_bing_thread();
  });
  btn_iot->Bind(wxEVT_BUTTON, [this](wxCommandEvent& evt) {
    start_test_iot_thread();
  });
  btn_oss->Bind(wxEVT_BUTTON, [this](wxCommandEvent& evt) {
    start_test_oss_thread();
  });
  btn_oss_upgrade->Bind(wxEVT_BUTTON, [this](wxCommandEvent& evt) {
    start_test_oss_upgrade_thread();
  });
  btn_oss_download->Bind(wxEVT_BUTTON, [this](wxCommandEvent& evt) {
    start_test_oss_download_thread();
  });
  return sizer;
}
References _L, btn_bing, btn_iot, btn_link, btn_oss, btn_oss_download, btn_oss_upgrade, btn_oss_upload, start_test_bambulab_thread(), start_test_bing_thread(), start_test_iot_thread(), start_test_oss_download_thread(), start_test_oss_thread(), start_test_oss_upgrade_thread(), text_bing_title, text_bing_val, text_iot_title, text_iot_value, text_link_title, text_link_val, text_oss_download_title, text_oss_download_value, text_oss_title, text_oss_upgrade_title, text_oss_upgrade_value, text_oss_upload_title, text_oss_upload_value, text_oss_value, wxButton, wxEVT_BUTTON, and wxStaticText.
Referenced by NetworkTestDialog().
create_info_sizer()
wxBoxSizer * Slic3r::GUI::NetworkTestDialog::create_info_sizer (wxWindow * parent) protected
{
  auto sizer = new wxBoxSizer(wxVERTICAL);
  text_basic_info = new wxStaticText(this, wxID_ANY, _L("Basic Info"), wxDefaultPosition, wxDefaultSize, 0);
  text_basic_info->Wrap(-1);
  sizer->Add(text_basic_info, 0, wxALL, 5);
  wxBoxSizer* version_sizer = new wxBoxSizer(wxHORIZONTAL);
  text_version_title = new wxStaticText(this, wxID_ANY, _L("Studio Version:"), wxDefaultPosition, wxDefaultSize, 0);
  text_version_title->Wrap(-1);
  version_sizer->Add(text_version_title, 0, wxALL, 5);
  wxString text_version = get_studio_version();
  text_version_val = new wxStaticText(this, wxID_ANY, text_version, wxDefaultPosition, wxDefaultSize, 0);
  text_version_val->Wrap(-1);
  version_sizer->Add(text_version_val, 0, wxALL, 5);
  sizer->Add(version_sizer, 1, wxEXPAND, 5);
  wxBoxSizer* sys_sizer = new wxBoxSizer(wxHORIZONTAL);
  txt_sys_info_title = new wxStaticText(this, wxID_ANY, _L("System Version:"), wxDefaultPosition, wxDefaultSize, 0);
  txt_sys_info_title->Wrap(-1);
  sys_sizer->Add(txt_sys_info_title, 0, wxALL, 5);
  txt_sys_info_value = new wxStaticText(this, wxID_ANY, get_os_info(), wxDefaultPosition, wxDefaultSize, 0);
  txt_sys_info_value->Wrap(-1);
  sys_sizer->Add(txt_sys_info_value, 0, wxALL, 5);
  sizer->Add(sys_sizer, 1, wxEXPAND, 5);
  wxBoxSizer* line_sizer = new wxBoxSizer(wxHORIZONTAL);
  txt_dns_info_title = new wxStaticText(this, wxID_ANY, _L("DNS Server:"), wxDefaultPosition, wxDefaultSize, 0);
  txt_dns_info_title->Wrap(-1);
  txt_dns_info_title->Hide();
  line_sizer->Add(txt_dns_info_title, 0, wxALL, 5);
  txt_dns_info_value = new wxStaticText(this, wxID_ANY, get_dns_info(), wxDefaultPosition, wxDefaultSize, 0);
  txt_dns_info_value->Hide();
  line_sizer->Add(txt_dns_info_value, 0, wxALL, 5);
  sizer->Add(line_sizer, 1, wxEXPAND, 5);
  return sizer;
}
References _L, get_dns_info(), get_os_info(), get_studio_version(), text_basic_info, text_version_title, text_version_val, txt_dns_info_title, txt_dns_info_value, txt_sys_info_title, txt_sys_info_value, and wxStaticText.
Referenced by NetworkTestDialog().
create_result_sizer()
wxBoxSizer * Slic3r::GUI::NetworkTestDialog::create_result_sizer (wxWindow * parent) protected
{
  auto sizer = new wxBoxSizer(wxVERTICAL);
  text_result = new wxStaticText(this, wxID_ANY, _L("Log Info"), wxDefaultPosition, wxDefaultSize, 0);
  text_result->Wrap(-1);
  sizer->Add(text_result, 0, wxALL, 5);
  txt_log = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_MULTILINE);
  sizer->Add(txt_log, 1, wxALL | wxEXPAND, 5);
  return sizer;
}
References _L, text_result, txt_log, and wxStaticText.
Referenced by NetworkTestDialog().
create_top_sizer()
wxBoxSizer * Slic3r::GUI::NetworkTestDialog::create_top_sizer (wxWindow * parent) protected
{
  auto sizer = new wxBoxSizer(wxVERTICAL);
  auto line_sizer = new wxBoxSizer(wxHORIZONTAL);
  btn_start = new wxButton(this, wxID_ANY, _L("Start Test Multi-Thread"), wxDefaultPosition, wxDefaultSize, 0);
  line_sizer->Add(btn_start, 0, wxALL, 5);
  btn_start_sequence = new wxButton(this, wxID_ANY, _L("Start Test Single-Thread"), wxDefaultPosition, wxDefaultSize, 0);
  line_sizer->Add(btn_start_sequence, 0, wxALL, 5);
  btn_download_log = new wxButton(this, wxID_ANY, _L("Export Log"), wxDefaultPosition, wxDefaultSize, 0);
  line_sizer->Add(btn_download_log, 0, wxALL, 5);
  btn_download_log->Hide();
  btn_start->Bind(wxEVT_BUTTON, [this](wxCommandEvent &evt) {
      start_all_job();
    });
  btn_start_sequence->Bind(wxEVT_BUTTON, [this](wxCommandEvent &evt) {
      start_all_job_sequence();
    });
  sizer->Add(line_sizer, 0, wxEXPAND, 5);
  return sizer;
}
References _L, btn_download_log, btn_start, btn_start_sequence, start_all_job(), start_all_job_sequence(), wxButton, and wxEVT_BUTTON.
Referenced by NetworkTestDialog().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
get_dns_info()
wxString Slic3r::GUI::NetworkTestDialog::get_dns_info ()
{
  return NA_STR;
}
References Slic3r::GUI::NA_STR.
Referenced by create_info_sizer(), and set_default().
get_os_info()
wxString Slic3r::GUI::NetworkTestDialog::get_os_info ()
{
  int major = 0, minor = 0, micro = 0;
  wxGetOsVersion(&major, &minor, &micro);
  std::string os_version = (boost::format("%1%.%2%.%3%") % major % minor % micro).str();
  wxString text_sys_version = wxGetOsDescription() + wxString::Format("%d.%d.%d", major, minor, micro);
  return text_sys_version;
}
Referenced by create_info_sizer(), and set_default().
get_studio_version()
wxString Slic3r::GUI::NetworkTestDialog::get_studio_version ()
{
  return wxString(SLIC3R_VERSION);
}
Referenced by create_info_sizer(), and set_default().
init_bind()
void Slic3r::GUI::NetworkTestDialog::init_bind () protected
{
  Bind(EVT_UPDATE_RESULT, [this](wxCommandEvent& evt) {
    if (evt.GetInt() == TEST_BAMBULAB_JOB) {
      text_link_val->SetLabelText(evt.GetString());
    } else if (evt.GetInt() == TEST_BING_JOB) {
      text_bing_val->SetLabelText(evt.GetString());
    } else if (evt.GetInt() == TEST_IOT_JOB) {
      text_iot_value->SetLabelText(evt.GetString());
    } else if (evt.GetInt() == TEST_OSS_JOB) {
      text_oss_value->SetLabelText(evt.GetString());
    } else if (evt.GetInt() == TEST_OSS_UPGRADE_JOB) {
      text_oss_upgrade_value->SetLabelText(evt.GetString());
    } else if (evt.GetInt() == TEST_OSS_DOWNLOAD_JOB) {
      text_oss_download_value->SetLabelText(evt.GetString());
    } else if (evt.GetInt() == TEST_OSS_UPLOAD_JOB) {
      text_oss_upload_value->SetLabelText(evt.GetString());
    }
    std::time_t t = std::time(0);
    std::tm* now_time = std::localtime(&t);
    std::stringstream buf;
    buf << std::put_time(now_time, "%a %b %d %H:%M:%S");
    wxString info = wxString::Format("%s:", buf.str()) + evt.GetString() + "\n";
    try {
      txt_log->AppendText(info);
    }
    catch (std::exception& e) {
      BOOST_LOG_TRIVIAL(error) << "Unkown Exception in print_log, exception=" << e.what();
      return;
    }
    catch (...) {
      BOOST_LOG_TRIVIAL(error) << "Unkown Exception in print_log";
      return;
    }
    return;
  });
  Bind(wxEVT_CLOSE_WINDOW, &NetworkTestDialog::on_close, this);
}
References error, on_close(), Slic3r::GUI::TEST_BAMBULAB_JOB, Slic3r::GUI::TEST_BING_JOB, Slic3r::GUI::TEST_IOT_JOB, Slic3r::GUI::TEST_OSS_DOWNLOAD_JOB, Slic3r::GUI::TEST_OSS_JOB, Slic3r::GUI::TEST_OSS_UPGRADE_JOB, Slic3r::GUI::TEST_OSS_UPLOAD_JOB, and txt_log.
Referenced by NetworkTestDialog().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_close()
void Slic3r::GUI::NetworkTestDialog::on_close (wxCloseEvent & event)
{
  m_download_cancel = true;
  m_closing = true;
  for (int i = 0; i < TEST_JOB_MAX; i++) {
    if (test_job[i]) {
      test_job[i]->join();
      test_job[i] = nullptr;
    }
  }
  event.Skip();
}
References m_closing, m_download_cancel, test_job, and Slic3r::GUI::TEST_JOB_MAX.
Referenced by init_bind().
on_dpi_changed()
void Slic3r::GUI::NetworkTestDialog::on_dpi_changed (const wxRect & suggested_rect) virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    ;
}
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
set_default()
void Slic3r::GUI::NetworkTestDialog::set_default ()
{
  for (int i = 0; i < TEST_JOB_MAX; i++) {
    test_job[i] = nullptr;
    m_in_testing[i] = false;
  }
  m_sequence_job = nullptr;
  text_version_val->SetLabelText(get_studio_version());
  txt_sys_info_value->SetLabelText(get_os_info());
  txt_dns_info_value->SetLabelText(get_dns_info());
  text_link_val->SetLabelText(NA_STR);
  text_bing_val->SetLabelText(NA_STR);
  text_iot_value->SetLabelText(NA_STR);
  text_oss_value->SetLabelText(NA_STR);
  text_oss_upgrade_value->SetLabelText(NA_STR);
  text_oss_download_value->SetLabelText(NA_STR);
  text_oss_upload_value->SetLabelText(NA_STR);
  //text_ping_value->SetLabelText(NA_STR);
  m_download_cancel = false;
  m_closing = false;
}
References get_dns_info(), get_os_info(), get_studio_version(), m_closing, m_download_cancel, m_in_testing, m_sequence_job, Slic3r::GUI::NA_STR, test_job, Slic3r::GUI::TEST_JOB_MAX, text_bing_val, text_iot_value, text_link_val, text_oss_download_value, text_oss_upgrade_value, text_oss_upload_value, text_oss_value, text_version_val, txt_dns_info_value, and txt_sys_info_value.
Referenced by NetworkTestDialog().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
start_all_job()
void Slic3r::GUI::NetworkTestDialog::start_all_job ()
{
  start_test_bing_thread();
  start_test_bambulab_thread();
  start_test_iot_thread();
  start_test_oss_thread();
  start_test_oss_upgrade_thread();
  start_test_oss_download_thread();
  start_test_ping_thread();
}
References start_test_bambulab_thread(), start_test_bing_thread(), start_test_iot_thread(), start_test_oss_download_thread(), start_test_oss_thread(), start_test_oss_upgrade_thread(), and start_test_ping_thread().
Referenced by create_top_sizer().
start_all_job_sequence()
void Slic3r::GUI::NetworkTestDialog::start_all_job_sequence ()
{
  m_sequence_job = new boost::thread([this] {
    update_status(-1, "start_test_sequence");
    start_test_bing();
    if (m_closing) return;
    start_test_bambulab();
    if (m_closing) return;
    start_test_oss();
    if (m_closing) return;
    start_test_oss_upgrade();
    if (m_closing) return;
    start_test_oss_download();
    update_status(-1, "end_test_sequence");
  });
}
References m_closing, m_sequence_job, start_test_bambulab(), start_test_bing(), start_test_oss(), start_test_oss_download(), start_test_oss_upgrade(), and update_status().
Referenced by create_top_sizer().
start_test_bambulab()
void Slic3r::GUI::NetworkTestDialog::start_test_bambulab ()
{
  m_in_testing[TEST_BAMBULAB_JOB] = true;
  update_status(TEST_BAMBULAB_JOB, "test bambulab start...");
  std::string platform = "windows";
#ifdef __WINDOWS__
  platform = "windows";
#endif
#ifdef __APPLE__
  platform = "macos";
#endif
#ifdef __LINUX__
  platform = "linux";
#endif
  std::string query_params = (boost::format("?name=slicer&version=%1%&guide_version=%2%")
    % VersionInfo::convert_full_version(SLIC3R_VERSION)
    % VersionInfo::convert_full_version("0.0.0.1")
    ).str();
  AppConfig* app_config = wxGetApp().app_config;
  std::string url = wxGetApp().get_http_url(app_config->get_country_code()) + query_params;
  Slic3r::Http http = Slic3r::Http::get(url);
  int result = -1;
  http.header("accept", "application/json")
    .timeout_max(10)
    .on_complete([this, &result](std::string body, unsigned status) {
      try {
        if (status == 200) {
          result = 0;
        }
      }
      catch (...) {
        ;
      }
    })
    .on_ip_resolve([this](std::string ip) {
      wxString ip_report = wxString::Format("test bambulab ip resolved = %s", ip);
      update_status(TEST_BAMBULAB_JOB, ip_report);
    })
    .on_error([this](std::string body, std::string error, unsigned int status) {
      wxString info = wxString::Format("status=%u, body=%s, error=%s", status, body, error);
      this->update_status(TEST_BAMBULAB_JOB, "test bambulab failed");
      this->update_status(-1, info);
    }).perform_sync();
  if (result == 0) {
    update_status(TEST_BAMBULAB_JOB, "test bambulab ok");
  }
  m_in_testing[TEST_BAMBULAB_JOB] = false;
}
References Slic3r::GUI::VersionInfo::convert_full_version(), error, Slic3r::Http::get(), Slic3r::AppConfig::get_country_code(), Slic3r::Http::header(), m_in_testing, Slic3r::Http::on_complete(), Slic3r::platform(), Slic3r::GUI::TEST_BAMBULAB_JOB, Slic3r::Http::timeout_max(), and update_status().
Referenced by start_all_job_sequence(), and start_test_bambulab_thread().
start_test_bambulab_thread()
void Slic3r::GUI::NetworkTestDialog::start_test_bambulab_thread ()
{
  if (m_in_testing[TEST_BAMBULAB_JOB]) return;
  test_job[TEST_BAMBULAB_JOB] = new boost::thread([this] {
    start_test_bambulab();
  });
}
References m_in_testing, start_test_bambulab(), Slic3r::GUI::TEST_BAMBULAB_JOB, and test_job.
Referenced by create_content_sizer(), and start_all_job().
start_test_bing()
void Slic3r::GUI::NetworkTestDialog::start_test_bing ()
{
  m_in_testing[TEST_BING_JOB] = true;
  update_status(TEST_BING_JOB, "test bing start...");
  std::string url = "http://www.bing.com/";
  Slic3r::Http http = Slic3r::Http::get(url);
  int result = -1;
  http.timeout_max(10)
    .on_complete([this, &result](std::string body, unsigned status) {
      try {
        if (status == 200) {
          result = 0;
        }
      }
      catch (...) {
        ;
      }
    })
    .on_ip_resolve([this](std::string ip) {
      wxString ip_report = wxString::Format("test bing ip resolved = %s", ip);
      update_status(TEST_BING_JOB, ip_report);
    })
    .on_error([this](std::string body, std::string error, unsigned int status) {
    wxString info = wxString::Format("status=%u, body=%s, error=%s", status, body, error);
    this->update_status(TEST_BING_JOB, "test bing failed");
    this->update_status(-1, info);
  }).perform_sync();
  if (result == 0) {
    update_status(TEST_BING_JOB, "test bing ok");
  }
  m_in_testing[TEST_BING_JOB] = false;
}
References error, Slic3r::Http::get(), m_in_testing, Slic3r::Http::on_complete(), Slic3r::GUI::TEST_BING_JOB, Slic3r::Http::timeout_max(), and update_status().
Referenced by start_all_job_sequence(), and start_test_bing_thread().
start_test_bing_thread()
void Slic3r::GUI::NetworkTestDialog::start_test_bing_thread ()
{
  test_job[TEST_BING_JOB] = new boost::thread([this] {
    start_test_bing();
  });
}
References start_test_bing(), Slic3r::GUI::TEST_BING_JOB, and test_job.
Referenced by create_content_sizer(), and start_all_job().
start_test_iot()
void Slic3r::GUI::NetworkTestDialog::start_test_iot ()
{
  m_in_testing[TEST_IOT_JOB] = true;
  update_status(TEST_IOT_JOB, "test http start...");
  NetworkAgent* agent = wxGetApp().getAgent();
  if (agent) {
    unsigned int http_code;
    std::string http_body;
    if (!agent->is_user_login()) {
      update_status(TEST_IOT_JOB, "please login first");
    } else {
      int result = agent->get_user_print_info(&http_code, &http_body);
      if (result == 0) {
        update_status(TEST_IOT_JOB, "test http ok");
      } else {
        update_status(TEST_IOT_JOB, "test http failed");
        wxString info = wxString::Format("test http failed, status = %u, error = %s", http_code, http_body);
        update_status(-1, info);
      }
    }
  } else {
    update_status(TEST_IOT_JOB, "please install network module first");
  }
  m_in_testing[TEST_IOT_JOB] = false;
}
References Slic3r::NetworkAgent::get_user_print_info(), Slic3r::NetworkAgent::is_user_login(), m_in_testing, Slic3r::GUI::TEST_IOT_JOB, and update_status().
Referenced by start_test_iot_thread().
start_test_iot_thread()
void Slic3r::GUI::NetworkTestDialog::start_test_iot_thread ()
{
  if (m_in_testing[TEST_IOT_JOB]) return;
  test_job[TEST_IOT_JOB] = new boost::thread([this] {
    start_test_iot();
  });
}
References m_in_testing, start_test_iot(), Slic3r::GUI::TEST_IOT_JOB, and test_job.
Referenced by create_content_sizer(), and start_all_job().
start_test_oss()
void Slic3r::GUI::NetworkTestDialog::start_test_oss ()
{
  m_in_testing[TEST_OSS_JOB] = true;
  update_status(TEST_OSS_JOB, "test storage start...");
  std::string url = "http://upload-file.bambulab.com";
  AppConfig* config = wxGetApp().app_config;
  if (config) {
    if (config->get_country_code() == "CN")
      url = "http://upload-file.bambulab.cn";
  }
  Slic3r::Http http = Slic3r::Http::get(url);
  int result = -1;
  http.timeout_max(15)
    .on_complete([this, &result](std::string body, unsigned status) {
    try {
      if (status == 200) {
        result = 0;
      }
    }
    catch (...) {
      ;
    }
      })
    .on_ip_resolve([this](std::string ip) {
      wxString ip_report = wxString::Format("test oss ip resolved = %s", ip);
      update_status(TEST_OSS_JOB, ip_report);
    })
    .on_error([this, &result](std::string body, std::string error, unsigned int status) {
      if (status == 403) {
        result = 0;
      } else {
        wxString info = wxString::Format("status=%u, body=%s, error=%s", status, body, error);
        this->update_status(TEST_OSS_JOB, "test storage failed");
        this->update_status(-1, info);
      }
    }).perform_sync();
    if (result == 0) {
      update_status(TEST_OSS_JOB, "test storage ok");
    }
  m_in_testing[TEST_OSS_JOB] = false;
}
References error, Slic3r::Http::get(), Slic3r::AppConfig::get_country_code(), m_in_testing, Slic3r::Http::on_complete(), Slic3r::GUI::TEST_OSS_JOB, Slic3r::Http::timeout_max(), and update_status().
Referenced by start_all_job_sequence(), and start_test_oss_thread().
start_test_oss_download()
void Slic3r::GUI::NetworkTestDialog::start_test_oss_download ()
{
  int result = 0;
  // get country_code
  AppConfig* app_config = wxGetApp().app_config;
  if (!app_config) {
    update_status(TEST_OSS_DOWNLOAD_JOB, "app config is nullptr");
    return;
  }
  m_in_testing[TEST_OSS_DOWNLOAD_JOB] = true;
  update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download start...");
  m_download_cancel = false;
  // get temp path
  fs::path target_file_path = (fs::temp_directory_path() / "test_storage_download.zip");
  fs::path tmp_path = target_file_path;
  tmp_path += (boost::format(".%1%%2%") % get_current_pid() % ".tmp").str();
  // get_url
  std::string url = wxGetApp().get_plugin_url("plugins", app_config->get_country_code());
  std::string download_url;
  Slic3r::Http http_url = Slic3r::Http::get(url);
  update_status(-1, "[test_oss_download]: url=" + url);
  http_url.on_complete(
    [&download_url](std::string body, unsigned status) {
      try {
        json j = json::parse(body);
        std::string message = j["message"].get<std::string>();
        if (message == "success") {
          json resource = j.at("resources");
          if (resource.is_array()) {
            for (auto iter = resource.begin(); iter != resource.end(); iter++) {
              Semver version;
              std::string url;
              std::string type;
              std::string vendor;
              std::string description;
              for (auto sub_iter = iter.value().begin(); sub_iter != iter.value().end(); sub_iter++) {
                if (boost::iequals(sub_iter.key(), "type")) {
                  type = sub_iter.value();
                  BOOST_LOG_TRIVIAL(info) << "[test_storage_download]: get version of settings's type, " << sub_iter.value();
                }
                else if (boost::iequals(sub_iter.key(), "version")) {
                  version = *(Semver::parse(sub_iter.value()));
                }
                else if (boost::iequals(sub_iter.key(), "description")) {
                  description = sub_iter.value();
                }
                else if (boost::iequals(sub_iter.key(), "url")) {
                  url = sub_iter.value();
                }
              }
              BOOST_LOG_TRIVIAL(info) << "[test_storage_download]: get type " << type << ", version " << version.to_string() << ", url " << url;
              download_url = url;
            }
          }
        }
        else {
          BOOST_LOG_TRIVIAL(info) << "[test_storage_download]: get version of plugin failed, body=" << body;
        }
      }
      catch (...) {
        BOOST_LOG_TRIVIAL(error) << "[test_storage_download]: catch unknown exception";
        ;
      }
    }).on_error(
      [&result, this](std::string body, std::string error, unsigned int status) {
        BOOST_LOG_TRIVIAL(error) << "[test_storage_download] on_error: " << error << ", body = " << body;
        wxString info = wxString::Format("status=%u, body=%s, error=%s", status, body, error);
        this->update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download failed");
        this->update_status(-1, info);
        result = -1;
    }).perform_sync();
  if (result < 0) {
    this->update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download failed");
    m_in_testing[TEST_OSS_DOWNLOAD_JOB] = false;
    return;
  }
  if (download_url.empty()) {
    BOOST_LOG_TRIVIAL(info) << "[test_oss_download]: no availaible plugin found for this app version: " << SLIC3R_VERSION;
    this->update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download failed");
    m_in_testing[TEST_OSS_DOWNLOAD_JOB] = false;
    return;
  }
  if (m_download_cancel) {
    this->update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download canceled");
    m_in_testing[TEST_OSS_DOWNLOAD_JOB] = false;
    return;
  }
  bool cancel = false;
  BOOST_LOG_TRIVIAL(info) << "[test_storage_download] get_url = " << download_url;
  // download
  Slic3r::Http http = Slic3r::Http::get(download_url);
  int reported_percent = 0;
  http.on_progress(
    [this, &result, &reported_percent](Slic3r::Http::Progress progress, bool& cancel) {
      int percent = 0;
      if (progress.dltotal != 0) {
        percent = progress.dlnow * 100 / progress.dltotal;
      }
      if (percent - reported_percent >= 10) {
        reported_percent = percent;
        std::string download_progress_info = (boost::format("downloading %1%%%") % percent).str();
        this->update_status(TEST_OSS_DOWNLOAD_JOB, download_progress_info);
      }
      BOOST_LOG_TRIVIAL(info) << "[test_storage_download] progress: " << reported_percent;
      cancel = m_download_cancel;
      if (cancel)
        result = -1;
    })
    .on_complete([this, tmp_path, target_file_path](std::string body, unsigned status) {
      BOOST_LOG_TRIVIAL(info) << "[test_storage_download] completed";
      bool cancel = false;
      fs::fstream file(tmp_path, std::ios::out | std::ios::binary | std::ios::trunc);
      file.write(body.c_str(), body.size());
      file.close();
      fs::rename(tmp_path, target_file_path);
      this->update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download ok");
    })
    .on_error([this, &result](std::string body, std::string error, unsigned int status) {
      BOOST_LOG_TRIVIAL(error) << "[test_oss_download] downloading... on_error: " << error << ", body = " << body;
      wxString info = wxString::Format("status=%u, body=%s, error=%s", status, body, error);
      this->update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download failed");
      this->update_status(-1, info);
      result = -1;
    });
  http.perform_sync();
  if (result < 0) {
    this->update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download failed");
  } else {
    this->update_status(TEST_OSS_DOWNLOAD_JOB, "test storage download ok");
  }
  m_in_testing[TEST_OSS_DOWNLOAD_JOB] = false;
  return;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), Slic3r::Http::Progress::dltotal, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::Http::get(), Slic3r::AppConfig::get_country_code(), Slic3r::get_current_pid(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::is_array(), m_download_cancel, m_in_testing, Slic3r::Http::on_complete(), Slic3r::Http::on_progress(), Slic3r::Semver::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::Http::perform_sync(), Slic3r::GUI::TEST_OSS_DOWNLOAD_JOB, Slic3r::Semver::to_string(), and update_status().
Referenced by start_all_job_sequence(), and start_test_oss_download_thread().
start_test_oss_download_thread()
void Slic3r::GUI::NetworkTestDialog::start_test_oss_download_thread ()
{
  test_job[TEST_OSS_DOWNLOAD_JOB] = new boost::thread([this] {
    start_test_oss_download();
  });
}
References start_test_oss_download(), test_job, and Slic3r::GUI::TEST_OSS_DOWNLOAD_JOB.
Referenced by create_content_sizer(), and start_all_job().
start_test_oss_thread()
void Slic3r::GUI::NetworkTestDialog::start_test_oss_thread ()
{
  test_job[TEST_OSS_JOB] = new boost::thread([this] {
    start_test_oss();
  });
}
References start_test_oss(), test_job, and Slic3r::GUI::TEST_OSS_JOB.
Referenced by create_content_sizer(), and start_all_job().
start_test_oss_upgrade()
void Slic3r::GUI::NetworkTestDialog::start_test_oss_upgrade ()
{
  m_in_testing[TEST_OSS_UPGRADE_JOB] = true;
  update_status(TEST_OSS_UPGRADE_JOB, "test storage upgrade start...");
  std::string url = "http://upgrade-file.bambulab.com";
  AppConfig* config = wxGetApp().app_config;
  if (config) {
    if (config->get_country_code() == "CN")
      url = "http://upgrade-file.bambulab.cn";
  }
  Slic3r::Http http = Slic3r::Http::get(url);
  int result = -1;
  http.timeout_max(15)
    .on_complete([this, &result](std::string body, unsigned status) {
    try {
      if (status == 200) {
        result = 0;
      }
    }
    catch (...) {
      ;
    }
      })
    .on_ip_resolve([this](std::string ip) {
        wxString ip_report = wxString::Format("test storage upgrade ip resolved = %s", ip);
        update_status(TEST_OSS_UPGRADE_JOB, ip_report);
      })
    .on_error([this, &result](std::string body, std::string error, unsigned int status) {
      if (status == 403) {
        result = 0;
      }
      else {
        wxString info = wxString::Format("status=%u, body=%s, error=%s", status, body, error);
        this->update_status(TEST_OSS_UPGRADE_JOB, "test storage upgrade failed");
        this->update_status(-1, info);
      }
    }).perform_sync();
  if (result == 0) {
    update_status(TEST_OSS_UPGRADE_JOB, "test storage upgrade ok");
  }
  m_in_testing[TEST_OSS_UPGRADE_JOB] = false;
}
References error, Slic3r::Http::get(), Slic3r::AppConfig::get_country_code(), m_in_testing, Slic3r::Http::on_complete(), Slic3r::GUI::TEST_OSS_UPGRADE_JOB, Slic3r::Http::timeout_max(), and update_status().
Referenced by start_all_job_sequence(), and start_test_oss_upgrade_thread().
start_test_oss_upgrade_thread()
void Slic3r::GUI::NetworkTestDialog::start_test_oss_upgrade_thread ()
{
  test_job[TEST_OSS_UPGRADE_JOB] = new boost::thread([this] {
    start_test_oss_upgrade();
  });
}
References start_test_oss_upgrade(), test_job, and Slic3r::GUI::TEST_OSS_UPGRADE_JOB.
Referenced by create_content_sizer(), and start_all_job().
start_test_oss_upload()
void Slic3r::GUI::NetworkTestDialog::start_test_oss_upload ()
{
  ;
}
Referenced by start_test_oss_upload_thread().
start_test_oss_upload_thread()
void Slic3r::GUI::NetworkTestDialog::start_test_oss_upload_thread ()
{
  test_job[TEST_OSS_UPLOAD_JOB] = new boost::thread([this] {
    start_test_oss_upload();
  });
}
References start_test_oss_upload(), test_job, and Slic3r::GUI::TEST_OSS_UPLOAD_JOB.
start_test_ping_thread()
void Slic3r::GUI::NetworkTestDialog::start_test_ping_thread ()
{
  test_job[TEST_PING_JOB] = new boost::thread([this] {
    m_in_testing[TEST_PING_JOB] = true;
    m_in_testing[TEST_PING_JOB] = false;
  });
}
References m_in_testing, test_job, and Slic3r::GUI::TEST_PING_JOB.
Referenced by start_all_job().
update_status()
void Slic3r::GUI::NetworkTestDialog::update_status (int job_id, wxString info)
{
  auto evt = new wxCommandEvent(EVT_UPDATE_RESULT, this->GetId());
  evt->SetString(info);
  evt->SetInt(job_id);
  wxQueueEvent(this, evt);
}
Referenced by start_all_job_sequence(), start_test_bambulab(), start_test_bing(), start_test_iot(), start_test_oss(), start_test_oss_download(), and start_test_oss_upgrade().
Member Data Documentation
btn_bing
wxButton* Slic3r::GUI::NetworkTestDialog::btn_bing protected
Referenced by create_content_sizer().
btn_download_log
wxButton* Slic3r::GUI::NetworkTestDialog::btn_download_log protected
Referenced by create_top_sizer().
btn_iot
wxButton* Slic3r::GUI::NetworkTestDialog::btn_iot protected
Referenced by create_content_sizer().
btn_link
wxButton* Slic3r::GUI::NetworkTestDialog::btn_link protected
Referenced by create_content_sizer().
btn_oss
wxButton* Slic3r::GUI::NetworkTestDialog::btn_oss protected
Referenced by create_content_sizer().
btn_oss_download
wxButton* Slic3r::GUI::NetworkTestDialog::btn_oss_download protected
Referenced by create_content_sizer().
btn_oss_upgrade
wxButton* Slic3r::GUI::NetworkTestDialog::btn_oss_upgrade protected
Referenced by create_content_sizer().
btn_oss_upload
wxButton* Slic3r::GUI::NetworkTestDialog::btn_oss_upload protected
Referenced by create_content_sizer().
btn_start
wxButton* Slic3r::GUI::NetworkTestDialog::btn_start protected
Referenced by create_top_sizer().
btn_start_sequence
wxButton* Slic3r::GUI::NetworkTestDialog::btn_start_sequence protected
Referenced by create_top_sizer().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_closing
bool Slic3r::GUI::NetworkTestDialog::m_closing = false protected
Referenced by on_close(), set_default(), and start_all_job_sequence().
m_download_cancel
bool Slic3r::GUI::NetworkTestDialog::m_download_cancel = false protected
Referenced by on_close(), set_default(), and start_test_oss_download().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_in_testing
bool Slic3r::GUI::NetworkTestDialog::m_in_testing[TEST_JOB_MAX] protected
Referenced by set_default(), start_test_bambulab(), start_test_bambulab_thread(), start_test_bing(), start_test_iot(), start_test_iot_thread(), start_test_oss(), start_test_oss_download(), start_test_oss_upgrade(), and start_test_ping_thread().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_sequence_job
boost::thread* Slic3r::GUI::NetworkTestDialog::m_sequence_job { nullptr } protected
Referenced by set_default(), and start_all_job_sequence().
test_job
boost::thread* Slic3r::GUI::NetworkTestDialog::test_job[TEST_JOB_MAX] protected
Referenced by on_close(), set_default(), start_test_bambulab_thread(), start_test_bing_thread(), start_test_iot_thread(), start_test_oss_download_thread(), start_test_oss_thread(), start_test_oss_upgrade_thread(), start_test_oss_upload_thread(), and start_test_ping_thread().
text_basic_info
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_basic_info protected
Referenced by create_info_sizer().
text_bing_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_bing_title protected
Referenced by create_content_sizer().
text_bing_val
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_bing_val protected
Referenced by create_content_sizer(), and set_default().
text_iot_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_iot_title protected
Referenced by create_content_sizer().
text_iot_value
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_iot_value protected
Referenced by create_content_sizer(), and set_default().
text_link_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_link_title protected
Referenced by create_content_sizer().
text_link_val
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_link_val protected
Referenced by create_content_sizer(), and set_default().
text_oss_download_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_oss_download_title protected
Referenced by create_content_sizer().
text_oss_download_value
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_oss_download_value protected
Referenced by create_content_sizer(), and set_default().
text_oss_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_oss_title protected
Referenced by create_content_sizer().
text_oss_upgrade_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_oss_upgrade_title protected
Referenced by create_content_sizer().
text_oss_upgrade_value
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_oss_upgrade_value protected
Referenced by create_content_sizer(), and set_default().
text_oss_upload_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_oss_upload_title protected
Referenced by create_content_sizer().
text_oss_upload_value
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_oss_upload_value protected
Referenced by create_content_sizer(), and set_default().
text_oss_value
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_oss_value protected
Referenced by create_content_sizer(), and set_default().
text_ping_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_ping_title protected
text_ping_value
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_ping_value protected
text_result
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_result protected
Referenced by create_result_sizer().
text_version_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_version_title protected
Referenced by create_info_sizer().
text_version_val
wxStaticText* Slic3r::GUI::NetworkTestDialog::text_version_val protected
Referenced by create_info_sizer(), and set_default().
txt_dns_info_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::txt_dns_info_title protected
Referenced by create_info_sizer().
txt_dns_info_value
wxStaticText* Slic3r::GUI::NetworkTestDialog::txt_dns_info_value protected
Referenced by create_info_sizer(), and set_default().
txt_log
wxTextCtrl* Slic3r::GUI::NetworkTestDialog::txt_log protected
Referenced by create_result_sizer(), and init_bind().
txt_sys_info_title
wxStaticText* Slic3r::GUI::NetworkTestDialog::txt_sys_info_title protected
Referenced by create_info_sizer().
txt_sys_info_value
wxStaticText* Slic3r::GUI::NetworkTestDialog::txt_sys_info_value protected
Referenced by create_info_sizer(), and set_default().
The documentation for this class was generated from the following files:
src/slic3r/GUI/NetworkTestDialog.hpp
src/slic3r/GUI/NetworkTestDialog.cpp