OrcaSlicer: Slic3r::ExtrusionEntityCollection Class Reference
Slic3r::ExtrusionEntityCollection Class Reference
#include <src/libslic3r/ExtrusionEntityCollection.hpp>
Public Member Functions
ExtrusionEntity * clone () const override
ExtrusionEntity * clone_move () override
ExtrusionEntityCollection ()
ExtrusionEntityCollection (const ExtrusionEntityCollection &other)
ExtrusionEntityCollection (ExtrusionEntityCollection &&other)
ExtrusionEntityCollection (const ExtrusionPaths &paths)
ExtrusionEntityCollection & operator= (const ExtrusionEntityCollection &other)
ExtrusionEntityCollection & operator= (ExtrusionEntityCollection &&other)
~ExtrusionEntityCollection ()
operator ExtrusionPaths () const
bool is_collection () const override
ExtrusionRole role () const override
bool can_sort () const override
bool can_reverse () const override
void set_reverse () override
bool empty () const
void clear ()
void swap (ExtrusionEntityCollection &c)
void append (const ExtrusionEntity &entity)
void append (ExtrusionEntity &&entity)
void append (const ExtrusionEntitiesPtr &entities)
void append (ExtrusionEntitiesPtr &&src)
void append (const ExtrusionPaths &paths)
void append (ExtrusionPaths &&paths)
void replace (size_t i, const ExtrusionEntity &entity)
void remove (size_t i)
ExtrusionEntityCollection chained_path_from (const Point &start_near, ExtrusionRole role=erMixed) const
void reverse () override
const Point & first_point () const override
const Point & last_point () const override
void polygons_covered_by_width (Polygons &out, const float scaled_epsilon) const override
void polygons_covered_by_spacing (Polygons &out, const float scaled_epsilon) const override
Polygons polygons_covered_by_width (const float scaled_epsilon=0.f) const
Polygons polygons_covered_by_spacing (const float scaled_epsilon=0.f) const
size_t items_count () const
ExtrusionEntityCollection flatten (bool preserve_ordering=false) const
Returns a flattened copy of this ExtrusionEntityCollection. That is, all of the items in its entities vector are not collections. You should be iterating over flatten().entities if you are interested in the underlying ExtrusionEntities (and don't care about hierarchy).
double min_mm3_per_mm () const override
double total_volume () const override
Polyline as_polyline () const override
void collect_polylines (Polylines &dst) const override
void collect_points (Points &dst) const override
double length () const override
virtual bool is_loop () const
virtual Polylines as_polylines () const
Static Public Member Functions
static ExtrusionEntityCollection chained_path_from (const ExtrusionEntitiesPtr &extrusion_entities, const Point &start_near, ExtrusionRole role=erMixed)
static std::string role_to_string (ExtrusionRole role)
static ExtrusionRole string_to_role (const std::string_view role)
Public Attributes
ExtrusionEntitiesPtr entities
bool no_sort
Private Attributes
bool is_reverse {true}
Detailed Description
Constructor & Destructor Documentation
ExtrusionEntityCollection() [1/4]
Slic3r::ExtrusionEntityCollection::ExtrusionEntityCollection () inline
: no_sort(false) {}
Referenced by clone(), and clone_move().
ExtrusionEntityCollection() [2/4]
Slic3r::ExtrusionEntityCollection::ExtrusionEntityCollection (const ExtrusionEntityCollection & other) inline
: no_sort(other.no_sort), is_reverse(other.is_reverse) { this->append(other.entities); }
References append(), and entities.
ExtrusionEntityCollection() [3/4]
Slic3r::ExtrusionEntityCollection::ExtrusionEntityCollection (ExtrusionEntityCollection && other) inline
: entities(std::move(other.entities)), no_sort(other.no_sort), is_reverse(other.is_reverse) {}
ExtrusionEntityCollection() [4/4]
Slic3r::ExtrusionEntityCollection::ExtrusionEntityCollection (const ExtrusionPaths & paths) explicit
    : no_sort(false)
{
    this->append(paths);
}
References append().
~ExtrusionEntityCollection()
Slic3r::ExtrusionEntityCollection::~ExtrusionEntityCollection () inline
{ clear(); }
References clear().
Member Function Documentation
append() [1/6]
void Slic3r::ExtrusionEntityCollection::append (const ExtrusionEntitiesPtr & entities) inline
{
        this->entities.reserve(this->entities.size() + entities.size());
        for (const ExtrusionEntity *ptr : entities)
            this->entities.emplace_back(ptr->clone());
    }
References entities, and ptr.
append() [2/6]
void Slic3r::ExtrusionEntityCollection::append (const ExtrusionEntity & entity) inline
{ this->entities.emplace_back(entity.clone()); }
References Slic3r::ExtrusionEntity::clone().
Referenced by ExtrusionEntityCollection(), ExtrusionEntityCollection(), Slic3r::FillConcentricInternal::fill_surface_extrusion(), Slic3r::FillMonotonicLineWGapFill::fill_surface_extrusion(), Slic3r::PerimeterGenerator::process_arachne(), Slic3r::PerimeterGenerator::process_classic(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().
append() [3/6]
void Slic3r::ExtrusionEntityCollection::append (const ExtrusionPaths & paths) inline
{
        this->entities.reserve(this->entities.size() + paths.size());
        for (const ExtrusionPath &path : paths)
            this->entities.emplace_back(path.clone());
    }
append() [4/6]
void Slic3r::ExtrusionEntityCollection::append (ExtrusionEntitiesPtr && src) inline
{
        if (entities.empty())
            entities = std::move(src);
        else {
            std::move(std::begin(src), std::end(src), std::back_inserter(entities));
            src.clear();
        }
    }
References entities.
append() [5/6]
void Slic3r::ExtrusionEntityCollection::append (ExtrusionEntity && entity) inline
{ this->entities.emplace_back(entity.clone_move()); }
append() [6/6]
void Slic3r::ExtrusionEntityCollection::append (ExtrusionPaths && paths) inline
{
        this->entities.reserve(this->entities.size() + paths.size());
        for (ExtrusionPath &path : paths)
            this->entities.emplace_back(new ExtrusionPath(std::move(path)));
    }
as_polyline()
Polyline Slic3r::ExtrusionEntityCollection::as_polyline () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{
        throw Slic3r::RuntimeError("Calling as_polyline() on a ExtrusionEntityCollection");
        return Polyline();
    };
as_polylines()
virtual Polylines Slic3r::ExtrusionEntity::as_polylines () const inline virtual inherited
{ Polylines dst; this->collect_polylines(dst); return dst; }
References Slic3r::ExtrusionEntity::collect_polylines().
Referenced by Slic3r::SupportMaterialInternal::remove_bridges_from_contacts().
can_reverse()
bool Slic3r::ExtrusionEntityCollection::can_reverse () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
    {
        if (this->no_sort)
            return false;
        else
            return is_reverse;
    }
References is_reverse.
Referenced by Slic3r::GCode::ObjectByExtruder::Island::Region::append().
can_sort()
bool Slic3r::ExtrusionEntityCollection::can_sort () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ return !this->no_sort; }
References no_sort.
chained_path_from() [1/2]
ExtrusionEntityCollection Slic3r::ExtrusionEntityCollection::chained_path_from (const ExtrusionEntitiesPtr & extrusion_entities, const Point & start_near, ExtrusionRole role = erMixed) static
{
  // Return a filtered copy of the collection.
    ExtrusionEntityCollection out;
    out.entities = filter_by_extrusion_role(extrusion_entities, role);
  // Clone the extrusion entities.
  for (auto &ptr : out.entities)
    ptr = ptr->clone();
  chain_and_reorder_extrusion_entities(out.entities, &start_near);
    return out;
}
References Slic3r::chain_and_reorder_extrusion_entities(), Slic3r::filter_by_extrusion_role(), out, ptr, and role().
Referenced by chained_path_from().
chained_path_from() [2/2]
ExtrusionEntityCollection Slic3r::ExtrusionEntityCollection::chained_path_from (const Point & start_near, ExtrusionRole role = erMixed) const inline
      { return this->no_sort ? *this : chained_path_from(this->entities, start_near, role); }
References chained_path_from(), and role().
clear()
void Slic3r::ExtrusionEntityCollection::clear ()
{
  for (size_t i = 0; i < this->entities.size(); ++i)
    delete this->entities[i];
    this->entities.clear();
}
References entities.
Referenced by ~ExtrusionEntityCollection(), Slic3r::Layer::make_perimeters(), and Slic3r::LayerRegion::make_perimeters().
clone()
ExtrusionEntity * Slic3r::ExtrusionEntityCollection::clone () const override virtual
Implements Slic3r::ExtrusionEntity.
{
    ExtrusionEntityCollection* coll = new ExtrusionEntityCollection(*this);
    for (size_t i = 0; i < coll->entities.size(); ++i)
        coll->entities[i] = this->entities[i]->clone();
    return coll;
}
References ExtrusionEntityCollection(), and entities.
Referenced by operator=().
clone_move()
ExtrusionEntity * Slic3r::ExtrusionEntityCollection::clone_move () inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return new ExtrusionEntityCollection(std::move(*this)); }
References ExtrusionEntityCollection().
collect_points()
void Slic3r::ExtrusionEntityCollection::collect_points (Points & dst) const inline override virtual
Implements Slic3r::ExtrusionEntity.
{
        for (ExtrusionEntity* extrusion_entity : this->entities)
            extrusion_entity->collect_points(dst);
    }
References entities.
collect_polylines()
void Slic3r::ExtrusionEntityCollection::collect_polylines (Polylines & dst) const inline override virtual
Implements Slic3r::ExtrusionEntity.
{
        for (ExtrusionEntity* extrusion_entity : this->entities)
            extrusion_entity->collect_polylines(dst);
    }
References entities.
empty()
bool Slic3r::ExtrusionEntityCollection::empty () const inline
{ return this->entities.empty(); }
Referenced by Slic3r::FillMonotonicLineWGapFill::fill_surface_extrusion(), Slic3r::SupportLayer::has_extrusions(), Slic3r::PerimeterGenerator::process_arachne(), Slic3r::PerimeterGenerator::process_classic(), and Slic3r::GCode::process_layer().
first_point()
const Point & Slic3r::ExtrusionEntityCollection::first_point () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->entities.front()->first_point(); }
flatten()
ExtrusionEntityCollection Slic3r::ExtrusionEntityCollection::flatten (bool preserve_ordering = false) const
Returns a flattened copy of this ExtrusionEntityCollection. That is, all of the items in its entities vector are not collections. You should be iterating over flatten().entities if you are interested in the underlying ExtrusionEntities (and don't care about hierarchy).
Parameters
preserve_ordering Flag to method that will flatten if and only if the underlying collection is sortable when True (default: False).
{
  struct Flatten {
    Flatten(bool preserve_ordering) : preserve_ordering(preserve_ordering) {}
    ExtrusionEntityCollection out;
    bool              preserve_ordering;
    void recursive_do(const ExtrusionEntityCollection &collection) {
        if (collection.no_sort && preserve_ordering) {
          // Don't flatten whatever happens below this level.
          out.append(collection);
        } else {
        for (const ExtrusionEntity *entity : collection.entities)
          if (entity->is_collection())
            this->recursive_do(*static_cast<const ExtrusionEntityCollection*>(entity));
          else
            out.append(*entity);
      }
    }
  } flatten(preserve_ordering);
  flatten.recursive_do(*this);
    return flatten.out;
}
References entities, flatten(), no_sort, and out.
Referenced by flatten().
is_collection()
bool Slic3r::ExtrusionEntityCollection::is_collection () const inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ return true; }
is_loop()
virtual bool Slic3r::ExtrusionEntity::is_loop () const inline virtual inherited
Reimplemented in Slic3r::ExtrusionMultiPath, and Slic3r::ExtrusionLoop.
{ return false; }
Referenced by Slic3r::chain_extrusion_entities().
items_count()
size_t Slic3r::ExtrusionEntityCollection::items_count () const
{
    size_t count = 0;
    for (const ExtrusionEntity *entity : this->entities)
        if (entity->is_collection())
            count += static_cast<const ExtrusionEntityCollection*>(entity)->items_count();
        else
            ++ count;
    return count;
}
References count, entities, and items_count().
Referenced by items_count().
last_point()
const Point & Slic3r::ExtrusionEntityCollection::last_point () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ return this->entities.back()->last_point(); }
length()
double Slic3r::ExtrusionEntityCollection::length () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{
        throw Slic3r::RuntimeError("Calling length() on a ExtrusionEntityCollection");
        return 0.;
    }
min_mm3_per_mm()
double Slic3r::ExtrusionEntityCollection::min_mm3_per_mm () const override virtual
Implements Slic3r::ExtrusionEntity.
{
    double min_mm3_per_mm = std::numeric_limits<double>::max();
    for (const ExtrusionEntity *entity : this->entities)
      min_mm3_per_mm = std::min(min_mm3_per_mm, entity->min_mm3_per_mm());
    return min_mm3_per_mm;
}
References entities, and min_mm3_per_mm().
Referenced by min_mm3_per_mm().
operator ExtrusionPaths()
Slic3r::ExtrusionEntityCollection::operator ExtrusionPaths () const explicit
{
    ExtrusionPaths paths;
    for (const ExtrusionEntity *ptr : this->entities) {
        if (const ExtrusionPath *path = dynamic_cast<const ExtrusionPath*>(ptr))
            paths.push_back(*path);
    }
    return paths;
}
References ptr.
operator=() [1/2]
ExtrusionEntityCollection & Slic3r::ExtrusionEntityCollection::operator= (const ExtrusionEntityCollection & other)
{
    this->entities      = other.entities;
    for (size_t i = 0; i < this->entities.size(); ++i)
        this->entities[i] = this->entities[i]->clone();
    this->no_sort       = other.no_sort;
    return *this;
}
References clone(), entities, and no_sort.
operator=() [2/2]
ExtrusionEntityCollection & Slic3r::ExtrusionEntityCollection::operator= (ExtrusionEntityCollection && other) inline
    {
        this->entities = std::move(other.entities);
        this->no_sort  = other.no_sort;
        is_reverse     = other.is_reverse;
        return *this;
    }
References is_reverse.
polygons_covered_by_spacing() [1/2]
Polygons Slic3r::ExtrusionEntityCollection::polygons_covered_by_spacing (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_spacing(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_spacing().
polygons_covered_by_spacing() [2/2]
void Slic3r::ExtrusionEntityCollection::polygons_covered_by_spacing (Polygons & out, const float scaled_epsilon) const override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (const ExtrusionEntity *entity : this->entities)
        entity->polygons_covered_by_spacing(out, scaled_epsilon);
}
References entities, and out.
Referenced by Slic3r::FillMonotonicLineWGapFill::fill_surface_extrusion(), and polygons_covered_by_spacing().
polygons_covered_by_width() [1/2]
Polygons Slic3r::ExtrusionEntityCollection::polygons_covered_by_width (const float scaled_epsilon = 0.f) const inline
        { Polygons out; this->polygons_covered_by_width(out, scaled_epsilon); return out; }
References out, and polygons_covered_by_width().
polygons_covered_by_width() [2/2]
void Slic3r::ExtrusionEntityCollection::polygons_covered_by_width (Polygons & out, const float scaled_epsilon) const override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (const ExtrusionEntity *entity : this->entities)
        entity->polygons_covered_by_width(out, scaled_epsilon);
}
References entities, and out.
Referenced by polygons_covered_by_width(), and Slic3r::PerimeterGenerator::process_classic().
remove()
void Slic3r::ExtrusionEntityCollection::remove (size_t i)
{
    delete this->entities[i];
    this->entities.erase(this->entities.begin() + i);
}
References entities.
replace()
void Slic3r::ExtrusionEntityCollection::replace (size_t i, const ExtrusionEntity & entity)
{
    delete this->entities[i];
    this->entities[i] = entity.clone();
}
References Slic3r::ExtrusionEntity::clone(), and entities.
reverse()
void Slic3r::ExtrusionEntityCollection::reverse () override virtual
Implements Slic3r::ExtrusionEntity.
{
    for (ExtrusionEntity *ptr : this->entities)
        // Don't reverse it if it's a loop, as it doesn't change anything in terms of elements ordering
        // and caller might rely on winding order
        if (! ptr->is_loop())
          ptr->reverse();
    std::reverse(this->entities.begin(), this->entities.end());
}
References entities, and ptr.
Referenced by Slic3r::PerimeterGenerator::process_classic().
role()
ExtrusionRole Slic3r::ExtrusionEntityCollection::role () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{
        ExtrusionRole out = erNone;
        for (const ExtrusionEntity *ee : entities) {
            ExtrusionRole er = ee->role();
            out = (out == erNone || out == er) ? er : erMixed;
        }
        return out;
    }
References entities, Slic3r::erMixed, Slic3r::erNone, and out.
Referenced by chained_path_from(), chained_path_from(), Slic3r::LayerTools::extruder(), Slic3r::WipingExtrusions::is_overriddable(), and Slic3r::GCode::process_layer().
role_to_string()
std::string Slic3r::ExtrusionEntity::role_to_string (ExtrusionRole role) static inherited
{
    switch (role) {
        case erNone                         : return L("Undefined");
        case erPerimeter                    : return L("Inner wall");
        case erExternalPerimeter            : return L("Outer wall");
        case erOverhangPerimeter            : return L("Overhang wall");
        case erInternalInfill               : return L("Sparse infill");
        case erSolidInfill                  : return L("Internal solid infill");
        case erTopSolidInfill               : return L("Top surface");
        case erBottomSurface                : return L("Bottom surface");
        case erIroning                      : return L("Ironing");
        case erBridgeInfill                 : return L("Bridge");
        case erInternalBridgeInfill         : return L("Internal Bridge");
        case erGapFill                      : return L("Gap infill");
        case erSkirt                        : return ("Skirt");
        case erBrim                         : return ("Brim");
        case erSupportMaterial              : return L("Support");
        case erSupportMaterialInterface     : return L("Support interface");
        case erSupportTransition            : return L("Support transition");
        case erWipeTower                    : return L("Prime tower");
        case erCustom                       : return L("Custom");
        case erMixed                        : return L("Multiple");
        default                             : assert(false);
    }
    return "";
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and Slic3r::ExtrusionEntity::role().
Referenced by Slic3r::WipeTowerWriter::WipeTowerWriter(), Slic3r::GCode::_do_export(), and Slic3r::GUI::GCodeViewer::render_legend().
set_reverse()
void Slic3r::ExtrusionEntityCollection::set_reverse () inline override virtual
Reimplemented from Slic3r::ExtrusionEntity.
{ is_reverse = false; }
References is_reverse.
string_to_role()
ExtrusionRole Slic3r::ExtrusionEntity::string_to_role (const std::string_view role) static inherited
{
    if (role == L("Inner wall"))
        return erPerimeter;
    else if (role == L("Outer wall"))
        return erExternalPerimeter;
    else if (role == L("Overhang wall"))
        return erOverhangPerimeter;
    else if (role == L("Sparse infill"))
        return erInternalInfill;
    else if (role == L("Internal solid infill"))
        return erSolidInfill;
    else if (role == L("Top surface"))
        return erTopSolidInfill;
    else if (role == L("Bottom surface"))
        return erBottomSurface;
    else if (role == L("Ironing"))
        return erIroning;
    else if (role == L("Bridge"))
        return erBridgeInfill;
    else if (role == L("Internal Bridge"))
        return erInternalBridgeInfill;
    else if (role == L("Gap infill"))
        return erGapFill;
    else if (role == ("Skirt"))
        return erSkirt;
    else if (role == ("Brim"))
        return erBrim;
    else if (role == L("Support"))
        return erSupportMaterial;
    else if (role == L("Support interface"))
        return erSupportMaterialInterface;
    else if (role == L("Support transition"))
        return erSupportTransition;
    else if (role == L("Prime tower"))
        return erWipeTower;
    else if (role == L("Custom"))
        return erCustom;
    else if (role == L("Multiple"))
        return erMixed;
    else
        return erNone;
}
References Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erBrim, Slic3r::erCustom, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erMixed, Slic3r::erNone, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, L, and Slic3r::ExtrusionEntity::role().
Referenced by Slic3r::FanMover::_process_gcode_line(), and Slic3r::GCodeProcessor::process_tags().
swap()
void Slic3r::ExtrusionEntityCollection::swap (ExtrusionEntityCollection & c)
{
    std::swap(this->entities, c.entities);
    std::swap(this->no_sort, c.no_sort);
}
References entities, and no_sort.
total_volume()
double Slic3r::ExtrusionEntityCollection::total_volume () const inline override virtual
Implements Slic3r::ExtrusionEntity.
{ double volume=0.; for (const auto& ent : entities) volume+=ent->total_volume(); return volume; }
References entities.
Member Data Documentation
entities
ExtrusionEntitiesPtr Slic3r::ExtrusionEntityCollection::entities
Referenced by ExtrusionEntityCollection(), Slic3r::ExtrusionPath::_inflate_collection(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), append(), Slic3r::GCode::ObjectByExtruder::Island::Region::append(), append(), clear(), clone(), Slic3r::SupportMaterialInternal::collect_bridging_perimeter_areas(), Slic3r::ToolOrdering::collect_extruders(), collect_points(), collect_polylines(), Slic3r::convert_extrusion_from_json(), Slic3r::convert_extrusion_to_json(), Slic3r::GCode::extrude_support(), Slic3r::LayerTools::extruder(), Slic3r::extrusionentity_extents(), Slic3r::_3DScene::extrusionentity_to_verts(), Slic3r::Fill::fill_surface_extrusion(), Slic3r::FillConcentricInternal::fill_surface_extrusion(), Slic3r::FillMonotonicLineWGapFill::fill_surface_extrusion(), flatten(), Slic3r::TreeSupport::generate_toolpaths(), Slic3r::PrintObjectSupportMaterial::generate_toolpaths(), Slic3r::get_print_object_extrusions_extents(), Slic3r::getExtrusionPathsFromEntity(), Slic3r::SupportMaterialInternal::has_bridging_fills(), Slic3r::SupportMaterialInternal::has_bridging_perimeters(), Slic3r::LayerRegion::has_extrusions(), Slic3r::DoExport::init_ooze_prevention(), items_count(), Slic3r::Layer::make_fills(), Slic3r::make_inner_brim(), Slic3r::make_inner_island_brim(), Slic3r::Layer::make_ironing(), Slic3r::Skirt::make_skirt_loops_per_extruder_1st_layer(), Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers(), min_mm3_per_mm(), operator=(), polygons_covered_by_spacing(), polygons_covered_by_width(), Slic3r::PerimeterGenerator::process_classic(), Slic3r::GCode::process_layer(), remove(), replace(), reverse(), role(), Slic3r::LayerRegion::simplify_entity_collection(), Slic3r::Layer::simplify_support_entity_collection(), Slic3r::Skirt::skirt_loops_per_extruder_all_printing(), swap(), Slic3r::to_json(), total_volume(), and Slic3r::traverse_loops().
is_reverse
bool Slic3r::ExtrusionEntityCollection::is_reverse {true} private
Referenced by can_reverse(), operator=(), and set_reverse().
no_sort
bool Slic3r::ExtrusionEntityCollection::no_sort
Referenced by can_sort(), Slic3r::convert_extrusion_from_json(), Slic3r::convert_extrusion_to_json(), Slic3r::convert_layer_region_from_json(), Slic3r::extract_support_layer(), Slic3r::Fill::fill_surface_extrusion(), Slic3r::FillConcentricInternal::fill_surface_extrusion(), Slic3r::FillMonotonicLineWGapFill::fill_surface_extrusion(), flatten(), Slic3r::Layer::make_ironing(), operator=(), swap(), and Slic3r::to_json().
The documentation for this class was generated from the following files:
src/libslic3r/ExtrusionEntityCollection.hpp
src/libslic3r/ExtrusionEntityCollection.cpp