OrcaSlicer: Slic3r::GUI::RadioBox Class Reference
Slic3r::GUI::RadioBox Class Reference
#include <src/slic3r/GUI/Widgets/RadioBox.hpp>
Public Member Functions
RadioBox (wxWindow *parent)
void SetValue (bool value) override
bool GetValue ()
void Rescale ()
bool Disable ()
bool Enable ()
Private Member Functions
void update ()
Private Attributes
ScalableBitmap m_on
ScalableBitmap m_off
Detailed Description
Constructor & Destructor Documentation
RadioBox()
Slic3r::GUI::RadioBox::RadioBox (wxWindow * parent)
    : wxBitmapToggleButton(parent, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE), m_on(this, "radio_on", 18), m_off(this, "radio_off", 18)
{
    // SetBackgroundStyle(wxBG_STYLE_TRANSPARENT);
    if (parent) SetBackgroundColour(parent->GetBackgroundColour());
    // Bind(wxEVT_TOGGLEBUTTON, [this](auto& e) { update(); e.Skip(); });
    SetSize(m_on.GetBmpSize());
    SetMinSize(m_on.GetBmpSize());
    update();
}
References ScalableBitmap::GetBmpSize(), m_on, and update().
Member Function Documentation
Disable()
bool Slic3r::GUI::RadioBox::Disable () inline
                   {
        return wxBitmapToggleButton::Disable();
    }
Enable()
bool Slic3r::GUI::RadioBox::Enable () inline
                  {
        return wxBitmapToggleButton::Enable();
    }
GetValue()
bool Slic3r::GUI::RadioBox::GetValue ()
{
    return wxBitmapToggleButton::GetValue();
}
Referenced by Slic3r::GUI::ProjectDropDialog::get_select_radio(), Slic3r::GUI::PreferencesDialog::get_select_radio(), and update().
Rescale()
void Slic3r::GUI::RadioBox::Rescale ()
{
    m_on.msw_rescale();
    m_off.msw_rescale();
    SetSize(m_on.GetBmpSize());
    update();
}
References ScalableBitmap::GetBmpSize(), m_off, m_on, ScalableBitmap::msw_rescale(), and update().
SetValue()
void Slic3r::GUI::RadioBox::SetValue (bool value) override
{
    wxBitmapToggleButton::SetValue(value);
    update();
}
References update().
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::PreferencesDialog::on_select_radio(), Slic3r::GUI::ProjectDropDialog::on_select_radio(), Slic3r::GUI::PreferencesDialog::OnSelectRadio(), and Slic3r::GUI::ProjectDropDialog::select_radio().
update()
void Slic3r::GUI::RadioBox::update () private
{ SetBitmap((GetValue() ? m_on : m_off).bmp()); }
References GetValue(), m_off, and m_on.
Referenced by RadioBox(), Rescale(), and SetValue().
Member Data Documentation
m_off
ScalableBitmap Slic3r::GUI::RadioBox::m_off private
Referenced by Rescale(), and update().
m_on
ScalableBitmap Slic3r::GUI::RadioBox::m_on private
Referenced by RadioBox(), Rescale(), and update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/RadioBox.hpp
src/slic3r/GUI/Widgets/RadioBox.cpp