OrcaSlicer: Slic3r::GUI::TabPresetComboBox Class Reference
Slic3r::GUI::TabPresetComboBox Class Reference
#include <src/slic3r/GUI/PresetComboBoxes.hpp>
Public Types
enum LabelItemType {
LABEL_ITEM_PHYSICAL_PRINTER = 0xffffff01 , LABEL_ITEM_DISABLED , LABEL_ITEM_MARKER , LABEL_ITEM_PHYSICAL_PRINTERS ,
LABEL_ITEM_WIZARD_PRINTERS , LABEL_ITEM_WIZARD_FILAMENTS , LABEL_ITEM_WIZARD_MATERIALS , LABEL_ITEM_MAX
}
Public Member Functions
TabPresetComboBox (wxWindow *parent, Preset::Type preset_type)
~TabPresetComboBox ()
void set_show_incompatible_presets (bool show_incompatible_presets)
wxString get_preset_name (const Preset &preset) override
void update () override
void update_dirty ()
void msw_rescale () override
void OnSelect (wxCommandEvent &evt) override
void set_enable_all (bool enable=true)
PresetCollection * presets () const
Preset::Type type () const
void set_label_marker (int item, LabelItemType label_item_type=LABEL_ITEM_MARKER)
bool set_printer_technology (PrinterTechnology pt)
void set_selection_changed_function (std::function< void(int)> sel_changed)
bool is_selected_physical_printer ()
bool selection_is_changed_according_to_physical_printers ()
void update (std::string select_preset)
void update_from_bundle ()
void add_ams_filaments (std::string selected, bool alias_name=false)
int selected_ams_filament () const
void set_filament_idx (const int extr_idx)
int get_filament_idx () const
wxString get_tooltip (const Preset &preset)
Preset::Type get_type ()
void show_all (bool show_all)
virtual void sys_color_changed ()
DropDown & GetDropDown ()
virtual bool SetFont (wxFont const &font) override
int Append (const wxString &item, const wxBitmap &bitmap=wxNullBitmap)
int Append (const wxString &item, const wxBitmap &bitmap, void *clientData)
unsigned int GetCount () const override
int GetSelection () const override
void SetSelection (int n) override
void SelectAndNotify (int n)
virtual void Rescale () override
wxString GetValue () const
void SetValue (const wxString &value)
void SetLabel (const wxString &label) override
wxString GetLabel () const override
void SetTextLabel (const wxString &label)
wxString GetTextLabel () const
wxString GetString (unsigned int n) const override
void SetString (unsigned int n, wxString const &value) override
wxBitmap GetItemBitmap (unsigned int n)
void SetItemBitmap (unsigned int n, wxBitmap const &bitmap)
Static Public Member Functions
static wxColor different_color (wxColor const &color)
Protected Types
typedef std::size_t Marker
Protected Member Functions
void invalidate_selection ()
void validate_selection (bool predicate=false)
void update_selection ()
int update_ams_color ()
wxBitmap * get_bmp (std::string bitmap_key, bool wide_icons, const std::string &main_icon_name, bool is_compatible=true, bool is_system=false, bool is_single_bar=false, const std::string &filament_rgb="", const std::string &extruder_rgb="", const std::string &material_rgb="")
wxBitmap * get_bmp (std::string bitmap_key, const std::string &main_icon_name, const std::string &next_icon_name, bool is_enabled=true, bool is_compatible=true, bool is_system=false)
wxBitmap * get_bmp (Preset const &preset)
virtual int DoInsertItems (const wxArrayStringsAdapter &items, unsigned int pos, void **clientData, wxClientDataType type) override
virtual void DoClear () override
void DoDeleteOneItem (unsigned int pos) override
void * DoGetItemClientData (unsigned int n) const override
void DoSetItemClientData (unsigned int n, void *data) override
void OnEdit () override
void sendComboBoxEvent ()
Static Protected Member Functions
static BitmapCache & bitmap_cache ()
static const char * separator_head ()
static const char * separator_tail ()
static wxString separator (const std::string &label)
Protected Attributes
std::function< void(int)> on_selection_changed { nullptr }
Preset::Type m_type
std::string m_main_bitmap_name
PresetBundle * m_preset_bundle {nullptr}
PresetCollection * m_collection {nullptr}
ScalableBitmap m_bitmapCompatible
ScalableBitmap m_bitmapIncompatible
int m_last_selected
int m_em_unit
bool m_suppress_change { true }
int m_filament_idx = -1
int m_first_ams_filament = 0
int m_last_ams_filament = 0
int icon_height
int norm_icon_width
int thin_icon_width
int wide_icon_width
int space_icon_width
int thin_space_icon_width
int wide_space_icon_width
PrinterTechnology printer_technology {ptAny}
Private Member Functions
void fill_width_height ()
void mouseDown (wxMouseEvent &event)
void mouseWheelMoved (wxMouseEvent &event)
void keyDown (wxKeyEvent &event)
Private Attributes
bool show_incompatible {false}
bool m_enable_all {false}
bool m_show_all { false }
std::vector< wxString > texts
std::vector< wxBitmap > icons
std::vector< void * > datas
std::vector< wxClientDataType > types
DropDown drop
bool drop_down = false
bool text_off = false
Detailed Description
Member Typedef Documentation
Marker
typedef std::size_t Slic3r::GUI::PresetComboBox::Marker protected inherited
Member Enumeration Documentation
LabelItemType
enum Slic3r::GUI::PresetComboBox::LabelItemType inherited
Enumerator
LABEL_ITEM_PHYSICAL_PRINTER
LABEL_ITEM_DISABLED
LABEL_ITEM_MARKER
LABEL_ITEM_PHYSICAL_PRINTERS
LABEL_ITEM_WIZARD_PRINTERS
LABEL_ITEM_WIZARD_FILAMENTS
LABEL_ITEM_WIZARD_MATERIALS
LABEL_ITEM_MAX
                     {
    LABEL_ITEM_PHYSICAL_PRINTER = 0xffffff01,
    LABEL_ITEM_DISABLED,
    LABEL_ITEM_MARKER,
    LABEL_ITEM_PHYSICAL_PRINTERS,
    LABEL_ITEM_WIZARD_PRINTERS,
        LABEL_ITEM_WIZARD_FILAMENTS,
        LABEL_ITEM_WIZARD_MATERIALS,
        LABEL_ITEM_MAX,
  };
Constructor & Destructor Documentation
TabPresetComboBox()
Slic3r::GUI::TabPresetComboBox::TabPresetComboBox (wxWindow * parent, Preset::Type preset_type)
                                                                             :
    // BBS: new layout
    PresetComboBox(parent, preset_type, wxSize(20 * wxGetApp().em_unit(), 30 * wxGetApp().em_unit() / 10))
{
}
~TabPresetComboBox()
Slic3r::GUI::TabPresetComboBox::~TabPresetComboBox () inline
{}
Member Function Documentation
add_ams_filaments()
void Slic3r::GUI::PresetComboBox::add_ams_filaments (std::string selected, bool alias_name = false) inherited
{
    if (!m_preset_bundle->filament_ams_list.empty()) {
        set_label_marker(Append(separator(L("AMS filaments")), wxNullBitmap));
        m_first_ams_filament = GetCount();
        auto &filaments      = m_collection->get_presets();
        for (auto &f : m_preset_bundle->filament_ams_list) {
            std::string filament_id = f.opt_string("filament_id", 0u);
            if (filament_id.empty()) continue;
            auto iter = std::find_if(filaments.begin(), filaments.end(),
                [&filament_id](auto &f) { return f.is_compatible && f.is_system && f.filament_id == filament_id; });
            if (iter == filaments.end()) {
                auto filament_type = "Generic " + f.opt_string("filament_type", 0u);
                iter               = std::find_if(filaments.begin(), filaments.end(),
                                    [&filament_type](auto &f) { return f.is_compatible && f.is_system && boost::algorithm::starts_with(f.name, filament_type); });
            }
            if (iter == filaments.end()) {
                BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": filament_id %1% not found or system or compatible") % filament_id;
                continue;
            }
            const_cast<Preset&>(*iter).is_visible = true;
            auto color = f.opt_string("filament_colour", 0u);
            auto name = f.opt_string("tray_name", 0u);
            wxColour clr(color);
            wxImage img(24, 16);
            if (clr.Red() > 224 && clr.Blue() > 224 && clr.Green() > 224) {
                img.SetRGB(wxRect({0, 0}, img.GetSize()), 128, 128, 128);
                img.SetRGB(wxRect({1, 1}, img.GetSize() - wxSize{2, 2}), clr.Red(), clr.Green(), clr.Blue());
            } else {
                img.SetRGB(wxRect({0, 0}, img.GetSize()), clr.Red(), clr.Green(), clr.Blue());
            }
            wxBitmap bmp(img);
            wxMemoryDC dc(bmp);
            dc.SetFont(Label::Body_10);
            dc.SetTextForeground(different_color(clr));
            auto size = dc.GetTextExtent(name);
            dc.DrawText(name, bmp.GetWidth() / 2 - size.x / 2, bmp.GetHeight() / 2 - size.y / 2);
            int item_id = Append(get_preset_name(*iter), bmp.ConvertToImage(), &m_first_ams_filament + (&f - &m_preset_bundle->filament_ams_list.front()));
            //validate_selection(id->value == selected); // can not select
        }
        m_last_ams_filament = GetCount();
    }
}
References ComboBox::Append(), Label::Body_10, Slic3r::GUI::PresetComboBox::different_color(), Slic3r::f(), Slic3r::PresetBundle::filament_ams_list, Slic3r::GUI::PresetComboBox::get_preset_name(), Slic3r::PresetCollection::get_presets(), ComboBox::GetCount(), Slic3r::Preset::is_visible, L, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_first_ams_filament, Slic3r::GUI::PresetComboBox::m_last_ams_filament, Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::separator(), Slic3r::GUI::PresetComboBox::set_label_marker(), and size.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), and update().
Append() [1/2]
int ComboBox::Append (const wxString & item, const wxBitmap & bitmap, void * clientData) inherited
{
    texts.push_back(item);
    icons.push_back(bitmap);
    datas.push_back(clientData);
    types.push_back(wxClientData_None);
    drop.Invalidate();
    return texts.size() - 1;
}
References ComboBox::datas, ComboBox::drop, ComboBox::icons, DropDown::Invalidate(), ComboBox::texts, and ComboBox::types.
Append() [2/2]
int ComboBox::Append (const wxString & item, const wxBitmap & bitmap = wxNullBitmap) inherited
{
    return Append(item, bitmap, nullptr);
}
References ComboBox::Append().
Referenced by Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PresetComboBox::add_ams_filaments(), ComboBox::Append(), Slic3r::GUI::Choice::BUILD(), Slic3r::GUI::GridCellFilamentsEditor::Create(), Slic3r::GUI::GridCellChoiceEditor::Create(), Slic3r::GUI::PrintOptionsDialog::create_settings_group(), BitmapChoiceRenderer::CreateEditorCtrl(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
bitmap_cache()
BitmapCache & Slic3r::GUI::PresetComboBox::bitmap_cache () static protected inherited
{
    static BitmapCache bmps;
    return bmps;
}
Referenced by Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::get_bmp().
different_color()
wxColor Slic3r::GUI::PresetComboBox::different_color (wxColor const & color) static inherited
{
    if (clr.GetLuminance() < 0.51) return *wxWHITE;
    return *wxBLACK;
}
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), and Slic3r::GUI::PlaterPresetComboBox::update().
DoClear()
void ComboBox::DoClear () override protected virtual inherited
{
    texts.clear();
    icons.clear();
    datas.clear();
    types.clear();
    drop.Invalidate(true);
}
References ComboBox::datas, ComboBox::drop, ComboBox::icons, DropDown::Invalidate(), ComboBox::texts, and ComboBox::types.
DoDeleteOneItem()
void ComboBox::DoDeleteOneItem (unsigned int pos) override protected inherited
{
    if (pos >= texts.size()) return;
    texts.erase(texts.begin() + pos);
    icons.erase(icons.begin() + pos);
    datas.erase(datas.begin() + pos);
    types.erase(types.begin() + pos);
    drop.Invalidate(true);
}
References ComboBox::datas, ComboBox::drop, ComboBox::icons, DropDown::Invalidate(), ComboBox::texts, and ComboBox::types.
DoGetItemClientData()
void * ComboBox::DoGetItemClientData (unsigned int n) const override protected inherited
{ return n < texts.size() ? datas[n] : NULL; }
References ComboBox::datas, n, NULL, and ComboBox::texts.
DoInsertItems()
int ComboBox::DoInsertItems (const wxArrayStringsAdapter & items, unsigned int pos, void ** clientData, wxClientDataType type) override protected virtual inherited
{
    if (pos > texts.size()) return -1;
    for (int i = 0; i < items.GetCount(); ++i) {
        texts.insert(texts.begin() + pos, items[i]);
        icons.insert(icons.begin() + pos, wxNullBitmap);
        datas.insert(datas.begin() + pos, clientData ? clientData[i] : NULL);
        types.insert(types.begin() + pos, type);
        ++pos;
    }
    drop.Invalidate(true);
    return pos - 1;
}
References ComboBox::datas, ComboBox::drop, ComboBox::icons, DropDown::Invalidate(), NULL, ComboBox::texts, and ComboBox::types.
DoSetItemClientData()
void ComboBox::DoSetItemClientData (unsigned int n, void * data) override protected inherited
{
    if (n < texts.size())
        datas[n] = data;
}
References ComboBox::datas, n, and ComboBox::texts.
fill_width_height()
void Slic3r::GUI::PresetComboBox::fill_width_height () private inherited
{
    // To avoid asserts, each added bitmap to wxBitmapCombobox should be the same size, so
    // set a bitmap's height to m_bitmapCompatible->GetHeight() and norm_icon_width to m_bitmapCompatible->GetWidth()
    icon_height     = m_bitmapCompatible.GetBmpHeight();
    norm_icon_width = m_bitmapCompatible.GetBmpWidth();
    /* It's supposed that standard size of an icon is 16px*16px for 100% scaled display.
    * So set sizes for solid_colored icons used for filament preset
    * and scale them in respect to em_unit value
    */
    const float scale_f = (float)m_em_unit * 0.1f;
    thin_icon_width = lroundf(8 * scale_f);          // analogue to 8px;
    wide_icon_width = norm_icon_width + thin_icon_width;
    space_icon_width      = lroundf(2 * scale_f);
    thin_space_icon_width = lroundf(4 * scale_f);
    wide_space_icon_width = lroundf(6 * scale_f);
}
References ScalableBitmap::GetBmpHeight(), ScalableBitmap::GetBmpWidth(), Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::PresetComboBox::m_bitmapCompatible, Slic3r::GUI::PresetComboBox::m_em_unit, Slic3r::GUI::PresetComboBox::norm_icon_width, Slic3r::GUI::PresetComboBox::space_icon_width, Slic3r::GUI::PresetComboBox::thin_icon_width, Slic3r::GUI::PresetComboBox::thin_space_icon_width, Slic3r::GUI::PresetComboBox::wide_icon_width, and Slic3r::GUI::PresetComboBox::wide_space_icon_width.
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), and Slic3r::GUI::PresetComboBox::msw_rescale().
get_bmp() [1/3]
wxBitmap * Slic3r::GUI::PresetComboBox::get_bmp (Preset const & preset) protected inherited
{
    static wxBitmap sbmp;
    if (m_type == Preset::TYPE_FILAMENT) {
        Preset const & preset2 = &m_collection->get_selected_preset() == &preset ? m_collection->get_edited_preset() : preset;
        wxString color = preset2.config.opt_string("default_filament_colour", 0);
        wxColour clr(color);
        if (clr.IsOk()) {
            std::string bitmap_key = "default_filament_colour_" + color.ToStdString();
            wxBitmap *bmp        = bitmap_cache().find(bitmap_key);
            if (bmp == nullptr) {
                wxImage img(16, 16);
                if (clr.Red() > 224 && clr.Blue() > 224 && clr.Green() > 224) {
                    img.SetRGB(wxRect({0, 0}, img.GetSize()), 128, 128, 128);
                    img.SetRGB(wxRect({1, 1}, img.GetSize() - wxSize{2, 2}), clr.Red(), clr.Green(), clr.Blue());
                } else {
                    img.SetRGB(wxRect({0, 0}, img.GetSize()), clr.Red(), clr.Green(), clr.Blue());
                }
                bmp = new wxBitmap(img);
                bmp = bitmap_cache().insert(bitmap_key, *bmp);
            }
            return bmp;
        }
    }
    return &sbmp;
}
References Slic3r::GUI::PresetComboBox::bitmap_cache(), Slic3r::Preset::config, Slic3r::GUI::BitmapCache::find(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::GUI::BitmapCache::insert(), Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_type, Slic3r::DynamicConfig::opt_string(), and Slic3r::Preset::TYPE_FILAMENT.
get_bmp() [2/3]
wxBitmap * Slic3r::GUI::PresetComboBox::get_bmp (std::string bitmap_key, bool wide_icons, const std::string & main_icon_name, bool is_compatible = true, bool is_system = false, bool is_single_bar = false, const std::string & filament_rgb = "", const std::string & extruder_rgb = "", const std::string & material_rgb = "") protected inherited
{
    // BBS: no icon
#if 1
    static wxBitmap bmp;
    return &bmp;
#else
    // If the filament preset is not compatible and there is a "red flag" icon loaded, show it left
    // to the filament color image.
    if (wide_icons)
        bitmap_key += is_compatible ? ",cmpt" : ",ncmpt";
    bitmap_key += is_system ? ",syst" : ",nsyst";
    bitmap_key += ",h" + std::to_string(icon_height);
    bool dark_mode = wxGetApp().dark_mode();
    if (dark_mode)
        bitmap_key += ",dark";
    bitmap_key += material_rgb;
    wxBitmap* bmp = bitmap_cache().find(bitmap_key);
    if (bmp == nullptr) {
        // Create the bitmap with color bars.
        std::vector<wxBitmap> bmps;
        if (wide_icons)
            // Paint a red flag for incompatible presets.
            bmps.emplace_back(is_compatible ? bitmap_cache().mkclear(norm_icon_width, icon_height) : m_bitmapIncompatible.bmp());
        if (m_type == Preset::TYPE_FILAMENT && !filament_rgb.empty())
        {
            // BBS
#if 0
            unsigned char rgb[3];
            // Paint the color bars.
            bitmap_cache().parse_color(filament_rgb, rgb);
            bmps.emplace_back(bitmap_cache().mksolid(is_single_bar ? wide_icon_width : norm_icon_width, icon_height, rgb, false, 1, dark_mode));
            if (!is_single_bar) {
                bitmap_cache().parse_color(extruder_rgb, rgb);
                bmps.emplace_back(bitmap_cache().mksolid(thin_icon_width, icon_height, rgb, false, 1, dark_mode));
            }
#endif
            // Paint a lock at the system presets.
            bmps.emplace_back(bitmap_cache().mkclear(space_icon_width, icon_height));
        }
        else
        {
            // BBS
#if 0
            // Paint the color bars.
            bmps.emplace_back(bitmap_cache().mkclear(thin_space_icon_width, icon_height));
            if (m_type == Preset::TYPE_SLA_MATERIAL)
                bmps.emplace_back(create_scaled_bitmap(main_icon_name, this, 16, false, material_rgb));
            else
                bmps.emplace_back(create_scaled_bitmap(main_icon_name));
#endif
            // Paint a lock at the system presets.
            bmps.emplace_back(bitmap_cache().mkclear(wide_space_icon_width, icon_height));
        }
        bmps.emplace_back(is_system ? create_scaled_bitmap("unlock_normal") : bitmap_cache().mkclear(norm_icon_width, icon_height));
        bmp = bitmap_cache().insert(bitmap_key, bmps);
    }
    return bmp;
#endif
}
References Slic3r::GUI::PresetComboBox::bitmap_cache(), ScalableBitmap::bmp(), create_scaled_bitmap(), Slic3r::GUI::BitmapCache::find(), Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::BitmapCache::insert(), Slic3r::GUI::PresetComboBox::m_bitmapIncompatible, Slic3r::GUI::PresetComboBox::m_type, Slic3r::GUI::BitmapCache::mkclear(), Slic3r::GUI::PresetComboBox::norm_icon_width, Slic3r::GUI::BitmapCache::parse_color(), Slic3r::GUI::PresetComboBox::space_icon_width, Slic3r::GUI::PresetComboBox::thin_icon_width, Slic3r::GUI::PresetComboBox::thin_space_icon_width, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::GUI::PresetComboBox::wide_icon_width, and Slic3r::GUI::PresetComboBox::wide_space_icon_width.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), Slic3r::GUI::PresetComboBox::update(), and update_dirty().
get_bmp() [3/3]
wxBitmap * Slic3r::GUI::PresetComboBox::get_bmp (std::string bitmap_key, const std::string & main_icon_name, const std::string & next_icon_name, bool is_enabled = true, bool is_compatible = true, bool is_system = false) protected inherited
{
    // BBS: no icon
#if 1
    static wxBitmap bmp;
    return &bmp;
#else
    bitmap_key += !is_enabled ? "_disabled" : "";
    bitmap_key += is_compatible ? ",cmpt" : ",ncmpt";
    bitmap_key += is_system ? ",syst" : ",nsyst";
    bitmap_key += ",h" + std::to_string(icon_height);
    if (wxGetApp().dark_mode())
        bitmap_key += ",dark";
    wxBitmap* bmp = bitmap_cache().find(bitmap_key);
    if (bmp == nullptr) {
        // Create the bitmap with color bars.
        std::vector<wxBitmap> bmps;
        bmps.emplace_back(m_type == Preset::TYPE_PRINTER ? create_scaled_bitmap(main_icon_name, this, 16, !is_enabled) :
                          is_compatible ? m_bitmapCompatible.bmp() : m_bitmapIncompatible.bmp());
        // Paint a lock at the system presets.
        bmps.emplace_back(is_system ? create_scaled_bitmap(next_icon_name, this, 16, !is_enabled) : bitmap_cache().mkclear(norm_icon_width, icon_height));
        bmp = bitmap_cache().insert(bitmap_key, bmps);
    }
    return bmp;
#endif
}
References Slic3r::GUI::PresetComboBox::bitmap_cache(), ScalableBitmap::bmp(), create_scaled_bitmap(), Slic3r::GUI::BitmapCache::find(), Slic3r::GUI::PresetComboBox::icon_height, Slic3r::GUI::BitmapCache::insert(), Slic3r::GUI::PresetComboBox::m_bitmapCompatible, Slic3r::GUI::PresetComboBox::m_bitmapIncompatible, Slic3r::GUI::PresetComboBox::m_type, Slic3r::GUI::BitmapCache::mkclear(), Slic3r::GUI::PresetComboBox::norm_icon_width, and Slic3r::Preset::TYPE_PRINTER.
get_filament_idx()
int Slic3r::GUI::PresetComboBox::get_filament_idx () const inline inherited
{ return m_filament_idx; }
References Slic3r::GUI::PresetComboBox::m_filament_idx.
Referenced by Slic3r::GUI::Plater::priv::on_select_preset().
get_preset_name()
wxString Slic3r::GUI::TabPresetComboBox::get_preset_name (const Preset & preset) override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    return from_u8(preset.label(true));
}
References Slic3r::GUI::from_u8(), and Slic3r::Preset::label().
Referenced by update().
get_tooltip()
wxString Slic3r::GUI::PresetComboBox::get_tooltip (const Preset & preset) inherited
{
    wxString tooltip = from_u8(preset.name);
    // BBS: FIXME
#if 0
    if (m_type == Preset::TYPE_FILAMENT) {
        int temperature[4] = { 0,0,0,0 };
        if (preset.config.has("nozzle_temperature_initial_layer")) //get the nozzle_temperature_initial_layer
            temperature[0] = preset.config.opt_int("nozzle_temperature_initial_layer", 0);
        if (preset.config.has("nozzle_temperature")) //get the nozzle temperature
            temperature[1] = preset.config.opt_int("nozzle_temperature", 0);
        if (preset.config.has("bed_temperature_initial_layer")) //get the bed_temperature_initial_layer
            temperature[2] = preset.config.opt_int("bed_temperature_initial_layer", 0);
        if (preset.config.has("bed_temperature")) //get the bed_temperature
            temperature[3] = preset.config.opt_int("bed_temperature", 0);
        tooltip += wxString::Format("\nNozzle First Layer:%d, Other Layer:%d\n Bed First Layer:%d, Other Layers:%d",
            temperature[0], temperature[1], temperature[2], temperature[3]);
    }
#endif
    return tooltip;
}
References Slic3r::Preset::config, Slic3r::GUI::from_u8(), Slic3r::ConfigOptionResolver::has(), Slic3r::GUI::PresetComboBox::m_type, Slic3r::Preset::name, Slic3r::DynamicConfig::opt_int(), and Slic3r::Preset::TYPE_FILAMENT.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update().
get_type()
Preset::Type Slic3r::GUI::PresetComboBox::get_type () inline inherited
{ return m_type; }
References Slic3r::GUI::PresetComboBox::m_type.
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::Plater::priv::on_select_preset(), and Slic3r::GUI::DiffPresetDialog::update_compatibility().
GetCount()
unsigned int ComboBox::GetCount () const override inherited
{ return texts.size(); }
References ComboBox::texts.
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), Slic3r::GUI::Choice::get_value(), ComboBox::mouseWheelMoved(), Slic3r::GUI::Choice::set_value(), update_dirty(), and Slic3r::GUI::PresetComboBox::validate_selection().
GetDropDown()
DropDown & ComboBox::GetDropDown () inline inherited
{ return drop; }
References ComboBox::drop.
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::Choice::BUILD(), and BitmapChoiceRenderer::CreateEditorCtrl().
GetItemBitmap()
wxBitmap ComboBox::GetItemBitmap (unsigned int n) inherited
{ return icons[n]; }
References ComboBox::icons, and n.
GetLabel()
wxString ComboBox::GetLabel () const override inherited
{
    if (GetTextCtrl()->IsShown() || text_off)
        return GetTextCtrl()->GetValue();
    else
        return TextInput::GetLabel();
}
References ComboBox::text_off.
Referenced by ComboBox::GetValue(), and Slic3r::GUI::PresetComboBox::update_ams_color().
GetSelection()
int ComboBox::GetSelection () const override inherited
{ return drop.GetSelection(); }
References ComboBox::drop, and DropDown::GetSelection().
Referenced by Slic3r::GUI::PrintOptionsDialog::PrintOptionsDialog(), Slic3r::GUI::ExtrusionCalibration::get_bed_temp(), Slic3r::GUI::PlateSettingsDialog::get_bed_type_choice(), Slic3r::GUI::PlateSettingsDialog::get_print_seq_choice(), Slic3r::GUI::get_selection(), Slic3r::GUI::Choice::get_value(), Slic3r::GUI::PresetComboBox::is_selected_physical_printer(), ComboBox::keyDown(), ComboBox::mouseWheelMoved(), Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PrintOptionsDialog::set_ai_monitor_sensitivity(), Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), Slic3r::GUI::PresetComboBox::update(), and update_dirty().
GetString()
wxString ComboBox::GetString (unsigned int n) const override inherited
{
    return n < texts.size() ? texts[n] : wxString{};
}
References n, and ComboBox::texts.
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::get_selection(), Slic3r::GUI::Plater::priv::on_select_preset(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), Slic3r::GUI::PresetComboBox::update(), update_dirty(), and Slic3r::GUI::PresetComboBox::update_selection().
GetTextLabel()
wxString ComboBox::GetTextLabel () const inherited
{
    return TextInput::GetLabel();
}
GetValue()
wxString ComboBox::GetValue () const inherited
{
    return drop.GetSelection() >= 0 ? drop.GetValue() : GetLabel();
}
References ComboBox::drop, ComboBox::GetLabel(), DropDown::GetSelection(), and DropDown::GetValue().
Referenced by Slic3r::GUI::Choice::BUILD(), Slic3r::GUI::GridCellFilamentsEditor::EndEdit(), Slic3r::GUI::GridCellChoiceEditor::EndEdit(), Slic3r::GUI::ExtrusionCalibration::get_bed_type_incompatible(), Slic3r::GUI::Choice::get_value(), Slic3r::GUI::Choice::msw_rescale(), Slic3r::GUI::ExtrusionCalibration::on_click_cali(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::AMSMaterialsSetting::on_select_filament(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), and Slic3r::GUI::ExtrusionCalibration::update_filament_info().
invalidate_selection()
void Slic3r::GUI::PresetComboBox::invalidate_selection () protected inherited
{
    m_last_selected = INT_MAX; // this value means that no one item is selected
}
References Slic3r::GUI::PresetComboBox::m_last_selected.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
is_selected_physical_printer()
bool Slic3r::GUI::PresetComboBox::is_selected_physical_printer () inherited
{
    auto selected_item = this->GetSelection();
    auto marker = reinterpret_cast<Marker>(this->GetClientData(selected_item));
    return marker == LABEL_ITEM_PHYSICAL_PRINTER;
}
References ComboBox::GetSelection(), and Slic3r::GUI::PresetComboBox::LABEL_ITEM_PHYSICAL_PRINTER.
Referenced by Slic3r::GUI::Tab::delete_preset(), Slic3r::GUI::Plater::priv::on_select_preset(), and Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers().
keyDown()
void ComboBox::keyDown (wxKeyEvent & event) private inherited
{
    switch (event.GetKeyCode()) {
        case WXK_RETURN:
        case WXK_SPACE:
            if (drop_down) {
                drop.DismissAndNotify();
            } else if (drop.HasDismissLongTime()) {
                drop.autoPosition();
                drop_down = true;
                drop.Popup();
                wxCommandEvent e(wxEVT_COMBOBOX_DROPDOWN);
                GetEventHandler()->ProcessEvent(e);
            }
            break;
        case WXK_UP:
        case WXK_DOWN:
        case WXK_LEFT:
        case WXK_RIGHT:
            if ((event.GetKeyCode() == WXK_UP || event.GetKeyCode() == WXK_LEFT) && GetSelection() > 0) {
                SetSelection(GetSelection() - 1);
            } else if ((event.GetKeyCode() == WXK_DOWN || event.GetKeyCode() == WXK_RIGHT) && GetSelection() + 1 < texts.size()) {
                SetSelection(GetSelection() + 1);
            } else {
                break;
            }
            sendComboBoxEvent();
            break;
        case WXK_TAB:
            HandleAsNavigationKey(event);
            break;
        default:
            event.Skip();
            break;
    }
}
References DropDown::autoPosition(), ComboBox::drop, ComboBox::drop_down, ComboBox::GetSelection(), DropDown::HasDismissLongTime(), ComboBox::sendComboBoxEvent(), ComboBox::SetSelection(), and ComboBox::texts.
Referenced by ComboBox::ComboBox().
mouseDown()
void ComboBox::mouseDown (wxMouseEvent & event) private inherited
{
    SetFocus();
    if (drop_down) {
        drop.Hide();
    } else if (drop.HasDismissLongTime()) {
        drop.autoPosition();
        drop_down = true;
        drop.Popup(&drop);
        wxCommandEvent e(wxEVT_COMBOBOX_DROPDOWN);
        GetEventHandler()->ProcessEvent(e);
    }
}
References DropDown::autoPosition(), ComboBox::drop, ComboBox::drop_down, and DropDown::HasDismissLongTime().
mouseWheelMoved()
void ComboBox::mouseWheelMoved (wxMouseEvent & event) private inherited
{
    event.Skip();
    if (drop_down) return;
    auto delta = event.GetWheelRotation() < 0 ? 1 : -1;
    unsigned int n = GetSelection() + delta;
    if (n < GetCount()) {
        SetSelection((int) n);
        sendComboBoxEvent();
    }
}
References ComboBox::drop_down, ComboBox::GetCount(), ComboBox::GetSelection(), n, ComboBox::sendComboBoxEvent(), and ComboBox::SetSelection().
msw_rescale()
void Slic3r::GUI::TabPresetComboBox::msw_rescale () override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    PresetComboBox::msw_rescale();
    // BBS: new layout
    wxSize sz = wxSize(20 * m_em_unit, 30 * m_em_unit / 10);
    SetMinSize(sz);
    SetSize(sz);
}
References Slic3r::GUI::PresetComboBox::m_em_unit, and Slic3r::GUI::PresetComboBox::msw_rescale().
OnEdit()
void ComboBox::OnEdit () override protected inherited
{
    auto value = GetTextCtrl()->GetValue();
    SetValue(value);
}
References ComboBox::SetValue().
OnSelect()
void Slic3r::GUI::TabPresetComboBox::OnSelect (wxCommandEvent & evt) override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    // Under OSX: in case of use of a same names written in different case (like "ENDER" and "Ender")
    // m_presets_choice->GetSelection() will return first item, because search in PopupListCtrl is case-insensitive.
    // So, use GetSelection() from event parameter
    auto selected_item = evt.GetSelection();
    auto marker = reinterpret_cast<Marker>(this->GetClientData(selected_item));
    if (marker >= LABEL_ITEM_DISABLED && marker < LABEL_ITEM_MAX) {
        this->SetSelection(m_last_selected);
        // BBS: Add/Remove filaments
        ConfigWizard::StartPage sp = ConfigWizard::SP_WELCOME;
        switch (marker) {
        case LABEL_ITEM_WIZARD_PRINTERS: sp = ConfigWizard::SP_PRINTERS; break;
        case LABEL_ITEM_WIZARD_FILAMENTS: sp = ConfigWizard::SP_FILAMENTS; break;
        case LABEL_ITEM_WIZARD_MATERIALS: sp = ConfigWizard::SP_MATERIALS; break;
        default: break;
        }
        if (sp != ConfigWizard::SP_WELCOME) {
            wxTheApp->CallAfter([this, sp]() {
                run_wizard(sp);
            });
        }
    }
    else if (on_selection_changed && (m_last_selected != selected_item || m_collection->current_is_dirty())) {
        m_last_selected = selected_item;
        // BBS: ams
        update_ams_color();
        on_selection_changed(selected_item);
    }
    evt.StopPropagation();
#ifdef __WXMSW__
    // From the Win 2004 preset combobox lose a focus after change the preset selection
    // and that is why the up/down arrow doesn't work properly
    // So, set the focus to the combobox explicitly
    this->SetFocus();
#endif
}
References Slic3r::PresetCollection::current_is_dirty(), Slic3r::GUI::PresetComboBox::LABEL_ITEM_DISABLED, Slic3r::GUI::PresetComboBox::LABEL_ITEM_MAX, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_FILAMENTS, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_MATERIALS, Slic3r::GUI::PresetComboBox::LABEL_ITEM_WIZARD_PRINTERS, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_last_selected, Slic3r::GUI::PresetComboBox::on_selection_changed, Slic3r::GUI::run_wizard(), ComboBox::SetSelection(), Slic3r::GUI::ConfigWizard::SP_FILAMENTS, Slic3r::GUI::ConfigWizard::SP_MATERIALS, Slic3r::GUI::ConfigWizard::SP_PRINTERS, Slic3r::GUI::ConfigWizard::SP_WELCOME, and Slic3r::GUI::PresetComboBox::update_ams_color().
presets()
PresetCollection * Slic3r::GUI::TabPresetComboBox::presets () const inline
{ return m_collection; }
References Slic3r::GUI::PresetComboBox::m_collection.
Referenced by update().
Rescale()
void ComboBox::Rescale () override virtual inherited
{
    TextInput::Rescale();
    drop.Rescale();
}
References ComboBox::drop, DropDown::Rescale(), and TextInput::Rescale().
Referenced by Slic3r::GUI::PresetComboBox::msw_rescale().
SelectAndNotify()
void ComboBox::SelectAndNotify (int n) inherited
{
    SetSelection(n);
    sendComboBoxEvent();
}
References n, ComboBox::sendComboBoxEvent(), and ComboBox::SetSelection().
selected_ams_filament()
int Slic3r::GUI::PresetComboBox::selected_ams_filament () const inherited
{
    if (m_first_ams_filament && m_last_selected >= m_first_ams_filament && m_last_selected < m_last_ams_filament) {
        return reinterpret_cast<int *>(GetClientData(m_last_selected)) - &m_first_ams_filament;
    }
    return -1;
}
References Slic3r::GUI::PresetComboBox::m_first_ams_filament, Slic3r::GUI::PresetComboBox::m_last_ams_filament, and Slic3r::GUI::PresetComboBox::m_last_selected.
Referenced by Slic3r::GUI::PresetComboBox::update_ams_color().
selection_is_changed_according_to_physical_printers()
bool Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers () inherited
{
    if (m_type != Preset::TYPE_PRINTER || !is_selected_physical_printer())
        return false;
    PhysicalPrinterCollection& physical_printers = m_preset_bundle->physical_printers;
    std::string selected_string = this->GetString(this->GetSelection()).ToUTF8().data();
    std::string old_printer_full_name, old_printer_preset;
    if (physical_printers.has_selection()) {
        old_printer_full_name = physical_printers.get_selected_full_printer_name();
        old_printer_preset = physical_printers.get_selected_printer_preset_name();
    }
    else
        old_printer_preset = m_collection->get_edited_preset().name;
    // Select related printer preset on the Printer Settings Tab
    physical_printers.select_printer(selected_string);
    std::string preset_name = physical_printers.get_selected_printer_preset_name();
    // if new preset wasn't selected, there is no need to call update preset selection
    if (old_printer_preset == preset_name) {
        // we need just to update according Plater<->Tab PresetComboBox
        if (dynamic_cast<PlaterPresetComboBox*>(this)!=nullptr) {
            wxGetApp().get_tab(m_type)->update_preset_choice();
            // Synchronize config.ini with the current selections.
            m_preset_bundle->export_selections(*wxGetApp().app_config);
        }
        else if (dynamic_cast<TabPresetComboBox*>(this)!=nullptr)
            wxGetApp().sidebar().update_presets(m_type);
        this->update();
        return true;
    }
    Tab* tab = wxGetApp().get_tab(Preset::TYPE_PRINTER);
    if (tab)
        tab->select_preset(preset_name, false, old_printer_full_name);
    return true;
}
References Slic3r::PresetBundle::export_selections(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PhysicalPrinterCollection::get_selected_full_printer_name(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), ComboBox::GetSelection(), ComboBox::GetString(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::PresetComboBox::is_selected_physical_printer(), Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::Preset::name, Slic3r::PresetBundle::physical_printers, Slic3r::GUI::Tab::select_preset(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::Preset::TYPE_PRINTER, and Slic3r::GUI::PresetComboBox::update().
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Plater::priv::on_select_preset().
sendComboBoxEvent()
void ComboBox::sendComboBoxEvent () protected inherited
{
    wxCommandEvent event(wxEVT_COMBOBOX, GetId());
    event.SetEventObject(this);
    event.SetInt(drop.GetSelection());
    event.SetString(drop.GetValue());
    GetEventHandler()->ProcessEvent(event);
}
References ComboBox::drop, DropDown::GetSelection(), and DropDown::GetValue().
Referenced by ComboBox::keyDown(), ComboBox::mouseWheelMoved(), and ComboBox::SelectAndNotify().
separator()
wxString Slic3r::GUI::PresetComboBox::separator (const std::string & label) static protected inherited
{
    return wxString::FromUTF8(separator_head()) + _(label) + wxString::FromUTF8(separator_tail());
}
References _, Slic3r::GUI::PresetComboBox::separator_head(), and Slic3r::GUI::PresetComboBox::separator_tail().
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
separator_head()
static const char * Slic3r::GUI::PresetComboBox::separator_head () inline static protected inherited
{ return "------ "; }
Referenced by Slic3r::GUI::PresetComboBox::separator().
separator_tail()
static const char * Slic3r::GUI::PresetComboBox::separator_tail () inline static protected inherited
{ return " ------"; }
Referenced by Slic3r::GUI::PresetComboBox::separator().
set_enable_all()
void Slic3r::GUI::TabPresetComboBox::set_enable_all (bool enable = true) inline
{ m_enable_all = enable; }
References m_enable_all.
set_filament_idx()
void Slic3r::GUI::PresetComboBox::set_filament_idx (const int extr_idx) inline inherited
{ m_filament_idx = extr_idx; }
References Slic3r::GUI::PresetComboBox::m_filament_idx.
set_label_marker()
void Slic3r::GUI::PresetComboBox::set_label_marker (int item, LabelItemType label_item_type = LABEL_ITEM_MARKER) inherited
{
    this->SetClientData(item, (void*)label_item_type);
}
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
set_printer_technology()
bool Slic3r::GUI::PresetComboBox::set_printer_technology (PrinterTechnology pt) inherited
{
    if (printer_technology != pt) {
        printer_technology = pt;
        return true;
    }
    return false;
}
References Slic3r::GUI::PresetComboBox::printer_technology.
set_selection_changed_function()
void Slic3r::GUI::PresetComboBox::set_selection_changed_function (std::function< void(int)> sel_changed) inline inherited
{ on_selection_changed = sel_changed; }
References Slic3r::GUI::PresetComboBox::on_selection_changed.
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), and Slic3r::GUI::Tab::create_preset_tab().
set_show_incompatible_presets()
void Slic3r::GUI::TabPresetComboBox::set_show_incompatible_presets (bool show_incompatible_presets) inline
{
        show_incompatible = show_incompatible_presets;
    }
References show_incompatible.
Referenced by Slic3r::GUI::Tab::toggle_show_hide_incompatible().
SetFont()
bool ComboBox::SetFont (wxFont const & font) override virtual inherited
{
    if (GetTextCtrl() && GetTextCtrl()->IsShown())
        return GetTextCtrl()->SetFont(font);
    else
        return TextInput::SetFont(font);
}
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), and Slic3r::GUI::GridCellChoiceEditor::Create().
SetItemBitmap()
void ComboBox::SetItemBitmap (unsigned int n, wxBitmap const & bitmap) inherited
{
    if (n >= texts.size()) return;
    icons[n] = bitmap;
    drop.Invalidate();
}
References ComboBox::drop, ComboBox::icons, DropDown::Invalidate(), n, and ComboBox::texts.
Referenced by update_dirty().
SetLabel()
void ComboBox::SetLabel (const wxString & label) override inherited
{
    if (GetTextCtrl()->IsShown() || text_off)
        GetTextCtrl()->SetValue(value);
    else
        TextInput::SetLabel(value);
}
References TextInput::SetLabel(), and ComboBox::text_off.
Referenced by ComboBox::SetSelection(), ComboBox::SetString(), and ComboBox::SetValue().
SetSelection()
void ComboBox::SetSelection (int n) override inherited
{
    drop.SetSelection(n);
    SetLabel(drop.GetValue());
    if (drop.selection >= 0)
        SetIcon(icons[drop.selection]);
}
References ComboBox::drop, DropDown::GetValue(), ComboBox::icons, n, DropDown::selection, ComboBox::SetLabel(), and DropDown::SetSelection().
Referenced by Slic3r::GUI::GridCellFilamentsEditor::BeginEdit(), Slic3r::GUI::GridCellChoiceEditor::BeginEdit(), Slic3r::GUI::ExtrusionCalibration::create(), BitmapChoiceRenderer::CreateEditorCtrl(), ComboBox::keyDown(), ComboBox::mouseWheelMoved(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PresetComboBox::OnSelect(), Slic3r::GUI::PlaterPresetComboBox::OnSelect(), OnSelect(), Slic3r::GUI::AMSMaterialsSetting::Popup(), ComboBox::SelectAndNotify(), Slic3r::GUI::Choice::set_selection(), Slic3r::GUI::Choice::set_value(), Slic3r::GUI::Choice::set_value(), Slic3r::GUI::PlateSettingsDialog::sync_bed_type(), Slic3r::GUI::PlateSettingsDialog::sync_print_seq(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), update_dirty(), Slic3r::GUI::PrintOptionsDialog::update_options(), Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
SetString()
void ComboBox::SetString (unsigned int n, wxString const & value) override inherited
{
    if (n >= texts.size()) return;
    texts[n]  = value;
    drop.Invalidate();
    if (n == drop.GetSelection()) SetLabel(value);
}
References ComboBox::drop, DropDown::GetSelection(), DropDown::Invalidate(), n, ComboBox::SetLabel(), and ComboBox::texts.
Referenced by update_dirty().
SetTextLabel()
void ComboBox::SetTextLabel (const wxString & label) inherited
{
    TextInput::SetLabel(label);
}
References TextInput::SetLabel().
Referenced by Slic3r::GUI::Choice::BUILD(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
SetValue()
void ComboBox::SetValue (const wxString & value) inherited
{
    drop.SetValue(value);
    SetLabel(value);
    if (drop.selection >= 0)
        SetIcon(icons[drop.selection]);
}
References ComboBox::drop, ComboBox::icons, DropDown::selection, ComboBox::SetLabel(), and DropDown::SetValue().
Referenced by ComboBox::OnEdit(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::Choice::set_selection(), Slic3r::GUI::Choice::set_value(), Slic3r::GUI::Choice::set_value(), and Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments().
show_all()
void Slic3r::GUI::PresetComboBox::show_all (bool show_all) inherited
{
    m_show_all = show_all;
    update();
}
References Slic3r::GUI::PresetComboBox::m_show_all, Slic3r::GUI::PresetComboBox::show_all(), and Slic3r::GUI::PresetComboBox::update().
Referenced by Slic3r::GUI::PresetComboBox::show_all().
sys_color_changed()
void Slic3r::GUI::PresetComboBox::sys_color_changed () virtual inherited
{
    wxGetApp().UpdateDarkUI(this);
    msw_rescale();
}
References Slic3r::GUI::PresetComboBox::msw_rescale().
type()
Preset::Type Slic3r::GUI::TabPresetComboBox::type () const inline
{ return m_type; }
References Slic3r::GUI::PresetComboBox::m_type.
update() [1/2]
void Slic3r::GUI::TabPresetComboBox::update () override virtual
Reimplemented from Slic3r::GUI::PresetComboBox.
{
    Freeze();
    Clear();
    invalidate_selection();
    const std::deque<Preset>& presets = m_collection->get_presets();
    std::map<wxString, std::pair<wxBitmap*, bool>> nonsys_presets;
    //BBS: add project embedded presets logic
    std::map<wxString, std::pair<wxBitmap*, bool>>  project_embedded_presets;
    //BBS:  move system to the end
    std::map<wxString, std::pair<wxBitmap*, bool>>  system_presets;
    wxString selected = "";
    //BBS:  move system to the end
    /*if (!presets.front().is_visible)
        set_label_marker(Append(separator(L("System presets")), wxNullBitmap));*/
    size_t idx_selected = m_collection->get_selected_idx();
    if (m_type == Preset::TYPE_PRINTER && m_preset_bundle->physical_printers.has_selection()) {
        std::string sel_preset_name = m_preset_bundle->physical_printers.get_selected_printer_preset_name();
        Preset* preset = m_collection->find_preset(sel_preset_name);
        if (!preset)
            m_preset_bundle->physical_printers.unselect_printer();
    }
    for (size_t i = presets.front().is_visible ? 0 : m_collection->num_default_presets(); i < presets.size(); ++i)
    {
        const Preset& preset = presets[i];
        if (!preset.is_visible || (!show_incompatible && !preset.is_compatible && i != idx_selected))
            continue;
        // marker used for disable incompatible printer models for the selected physical printer
        bool is_enabled = true;
        wxBitmap* bmp = get_bmp(preset);
        assert(bmp);
        if (preset.is_default || preset.is_system) {
            //BBS: move system to the end
            system_presets.emplace(get_preset_name(preset), std::pair<wxBitmap *, bool>(bmp, is_enabled));
            if (i == idx_selected)
                selected = get_preset_name(preset);
            //int item_id = Append(get_preset_name(preset), *bmp);
            //if (!is_enabled)
            //    set_label_marker(item_id, LABEL_ITEM_DISABLED);
            //validate_selection(i == idx_selected);
        }
        //BBS: add project embedded preset logic
        else if (preset.is_project_embedded)
        {
            //std::pair<wxBitmap*, bool> pair(bmp, is_enabled);
            project_embedded_presets.emplace(get_preset_name(preset), std::pair<wxBitmap *, bool>(bmp, is_enabled));
            if (i == idx_selected)
                selected = get_preset_name(preset);
        }
        else
        {
            std::pair<wxBitmap*, bool> pair(bmp, is_enabled);
            nonsys_presets.emplace(get_preset_name(preset), std::pair<wxBitmap*, bool>(bmp, is_enabled));
            if (i == idx_selected)
                selected = get_preset_name(preset);
        }
        //BBS: move system to the end
        //if (i + 1 == m_collection->num_default_presets())
        //    set_label_marker(Append(separator(L("System presets")), wxNullBitmap));
    }
    if (m_type == Preset::TYPE_FILAMENT && m_preset_bundle->printers.get_edited_preset().has_lidar(m_preset_bundle))
        add_ams_filaments(into_u8(selected));
    //BBS: add project embedded preset logic
    if (!project_embedded_presets.empty())
    {
        set_label_marker(Append(separator(L("Project-inside presets")), wxNullBitmap));
        for (std::map<wxString, std::pair<wxBitmap*, bool>>::iterator it = project_embedded_presets.begin(); it != project_embedded_presets.end(); ++it) {
            int item_id = Append(it->first, *it->second.first);
            bool is_enabled = it->second.second;
            if (!is_enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->first == selected);
        }
    }
    if (!nonsys_presets.empty())
    {
        set_label_marker(Append(separator(L("User presets")), wxNullBitmap));
        for (std::map<wxString, std::pair<wxBitmap*, bool>>::iterator it = nonsys_presets.begin(); it != nonsys_presets.end(); ++it) {
            int item_id = Append(it->first, *it->second.first);
            bool is_enabled = it->second.second;
            if (!is_enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->first == selected);
        }
    }
    //BBS: move system to the end
    if (!system_presets.empty())
    {
        set_label_marker(Append(separator(L("System presets")), wxNullBitmap));
        for (std::map<wxString, std::pair<wxBitmap*, bool>>::iterator it = system_presets.begin(); it != system_presets.end(); ++it) {
            int item_id = Append(it->first, *it->second.first);
            bool is_enabled = it->second.second;
            if (!is_enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->first == selected);
        }
    }
    if (m_type == Preset::TYPE_PRINTER)
    {
        //BBS: remove unused pysical printer logic
        /*// add Physical printers, if any exists
        if (!m_preset_bundle->physical_printers.empty()) {
            set_label_marker(Append(separator(L("Physical printers")), wxNullBitmap));
            const PhysicalPrinterCollection& ph_printers = m_preset_bundle->physical_printers;
            for (PhysicalPrinterCollection::ConstIterator it = ph_printers.begin(); it != ph_printers.end(); ++it) {
                for (const std::string& preset_name : it->get_preset_names()) {
                    Preset* preset = m_collection->find_preset(preset_name);
                    if (!preset || !preset->is_visible)
                        continue;
                    std::string main_icon_name = preset->printer_technology() == ptSLA ? "sla_printer" : m_main_bitmap_name;
                    wxBitmap* bmp = get_bmp(main_icon_name, main_icon_name, "", true, true, false);
                    assert(bmp);
                    set_label_marker(Append(from_u8(it->get_full_name(preset_name) + suffix(preset)), *bmp), LABEL_ITEM_PHYSICAL_PRINTER);
                    validate_selection(ph_printers.is_selected(it, preset_name));
                }
            }
        }*/
        // add "Add/Remove printers" item
        //std::string icon_name = "edit_uni";
        //wxBitmap* bmp = get_bmp("edit_preset_list, tab,", icon_name, "");
        //assert(bmp);
        //set_label_marker(Append(separator(L("Add/Remove printers")), *bmp), LABEL_ITEM_WIZARD_PRINTERS);
    }
    // BBS Add/Remove filaments select
    //wxBitmap* bmp = get_bmp("edit_preset_list", false, "edit_uni");
    //assert(bmp);
    //if (m_type == Preset::TYPE_FILAMENT)
    //    set_label_marker(Append(separator(L("Add/Remove filaments")), *bmp), LABEL_ITEM_WIZARD_FILAMENTS);
    //else if (m_type == Preset::TYPE_SLA_MATERIAL)
    //    set_label_marker(Append(separator(L("Add/Remove materials")), *bmp), LABEL_ITEM_WIZARD_MATERIALS);
    update_selection();
    Thaw();
}
References Slic3r::GUI::PresetComboBox::add_ams_filaments(), ComboBox::Append(), Slic3r::PresetCollection::find_preset(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::PresetCollection::get_edited_preset(), get_preset_name(), Slic3r::PresetCollection::get_presets(), Slic3r::PresetCollection::get_selected_idx(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), Slic3r::Preset::has_lidar(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::GUI::into_u8(), Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::Preset::is_compatible, Slic3r::Preset::is_default, Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_system, Slic3r::Preset::is_visible, L, Slic3r::GUI::PresetComboBox::LABEL_ITEM_DISABLED, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_preset_bundle, Slic3r::GUI::PresetComboBox::m_type, Slic3r::PresetCollection::num_default_presets(), Slic3r::PresetBundle::physical_printers, presets(), Slic3r::PresetBundle::printers, Slic3r::GUI::PresetComboBox::separator(), Slic3r::GUI::PresetComboBox::set_label_marker(), show_incompatible, Slic3r::PresetCollection::size(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, Slic3r::PhysicalPrinterCollection::unselect_printer(), Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::PresetComboBox::validate_selection().
Referenced by Slic3r::GUI::Tab::update_preset_choice(), and Slic3r::GUI::Sidebar::update_presets().
update() [2/2]
void Slic3r::GUI::PresetComboBox::update (std::string select_preset) inherited
{
    Freeze();
    Clear();
    invalidate_selection();
    const std::deque<Preset>& presets = m_collection->get_presets();
    std::map<wxString, std::pair<wxBitmap*, bool>>  nonsys_presets;
    std::map<wxString, wxBitmap*>                   incomp_presets;
    wxString selected = "";
    if (!presets.front().is_visible)
        set_label_marker(Append(separator(L("System presets")), wxNullBitmap));
    for (size_t i = presets.front().is_visible ? 0 : m_collection->num_default_presets(); i < presets.size(); ++i)
    {
        const Preset& preset = presets[i];
        if (!m_show_all && (!preset.is_visible || !preset.is_compatible))
            continue;
        // marker used for disable incompatible printer models for the selected physical printer
        bool is_enabled = m_type == Preset::TYPE_PRINTER && printer_technology != ptAny ? preset.printer_technology() == printer_technology : true;
        if (select_preset_name.empty() && is_enabled)
            select_preset_name = preset.name;
        wxBitmap* bmp = get_bmp(preset);
        assert(bmp);
        if (!is_enabled)
            incomp_presets.emplace(get_preset_name(preset), bmp);
        else if (preset.is_default || preset.is_system)
        {
            Append(get_preset_name(preset), *bmp);
            validate_selection(preset.name == select_preset_name);
        }
        else
        {
            nonsys_presets.emplace(get_preset_name(preset), std::pair<wxBitmap*, bool>(bmp, is_enabled));
            if (preset.name == select_preset_name || (select_preset_name.empty() && is_enabled))
                selected = get_preset_name(preset);
        }
        if (i + 1 == m_collection->num_default_presets())
            set_label_marker(Append(separator(L("System presets")), wxNullBitmap));
    }
    if (!nonsys_presets.empty())
    {
        set_label_marker(Append(separator(L("User presets")), wxNullBitmap));
        for (std::map<wxString, std::pair<wxBitmap*, bool>>::iterator it = nonsys_presets.begin(); it != nonsys_presets.end(); ++it) {
            int item_id = Append(it->first, *it->second.first);
            bool is_enabled = it->second.second;
            if (!is_enabled)
                set_label_marker(item_id, LABEL_ITEM_DISABLED);
            validate_selection(it->first == selected);
        }
    }
    if (!incomp_presets.empty())
    {
        set_label_marker(Append(separator(L("Incompatible presets")), wxNullBitmap));
        for (std::map<wxString, wxBitmap*>::iterator it = incomp_presets.begin(); it != incomp_presets.end(); ++it) {
            set_label_marker(Append(it->first, *it->second), LABEL_ITEM_DISABLED);
        }
    }
    update_selection();
    Thaw();
}
References ComboBox::Append(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_preset_name(), Slic3r::PresetCollection::get_presets(), Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::Preset::is_compatible, Slic3r::Preset::is_default, Slic3r::Preset::is_system, Slic3r::Preset::is_visible, L, Slic3r::GUI::PresetComboBox::LABEL_ITEM_DISABLED, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_show_all, Slic3r::GUI::PresetComboBox::m_type, Slic3r::Preset::name, Slic3r::PresetCollection::num_default_presets(), Slic3r::Preset::printer_technology(), Slic3r::GUI::PresetComboBox::printer_technology, Slic3r::ptAny, Slic3r::GUI::PresetComboBox::separator(), Slic3r::GUI::PresetComboBox::set_label_marker(), Slic3r::Preset::TYPE_PRINTER, Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::PresetComboBox::validate_selection().
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), and Slic3r::GUI::DiffPresetDialog::update_compatibility().
update_ams_color()
int Slic3r::GUI::PresetComboBox::update_ams_color () protected inherited
{
    if (m_filament_idx < 0) return -1;
    int idx = selected_ams_filament();
    std::string color;
    if (idx < 0) {
        auto *preset = m_collection->find_preset(Preset::remove_suffix_modified(GetLabel().ToUTF8().data()));
        if (preset) color = preset->config.opt_string("default_filament_colour", 0u);
        if (color.empty()) return -1;
    } else {
        auto &ams_list = wxGetApp().preset_bundle->filament_ams_list;
        if (idx >= ams_list.size()) {
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": ams %1% out of range %2%") % idx % ams_list.size();
            return -1;
        }
        color = ams_list[idx].opt_string("filament_colour", 0u);
    }
    DynamicPrintConfig *cfg        = &wxGetApp().preset_bundle->project_config;
    auto colors = static_cast<ConfigOptionStrings*>(cfg->option("filament_colour")->clone());
    colors->values[m_filament_idx] = color;
    DynamicPrintConfig new_cfg;
    new_cfg.set_key_value("filament_colour", colors);
    cfg->apply(new_cfg);
    wxGetApp().plater()->on_config_change(new_cfg);
    //trigger the filament color changed
    wxCommandEvent *evt = new wxCommandEvent(EVT_FILAMENT_COLOR_CHANGED);
    wxQueueEvent(wxGetApp().plater(), evt);
    return idx;
}
References Slic3r::ConfigBase::apply(), Slic3r::ConfigOption::clone(), Slic3r::Preset::config, Slic3r::PresetCollection::find_preset(), ComboBox::GetLabel(), Slic3r::GUI::PresetComboBox::m_collection, Slic3r::GUI::PresetComboBox::m_filament_idx, Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), Slic3r::GUI::plater(), Slic3r::Preset::remove_suffix_modified(), Slic3r::GUI::PresetComboBox::selected_ams_filament(), Slic3r::DynamicConfig::set_key_value(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::PlaterPresetComboBox::OnSelect(), and OnSelect().
update_dirty()
void Slic3r::GUI::TabPresetComboBox::update_dirty ()
{
    // 1) Update the dirty flag of the current preset.
    m_collection->update_dirty();
    // 2) Update the labels.
    wxWindowUpdateLocker noUpdates(this);
    for (unsigned int ui_id = 0; ui_id < GetCount(); ++ui_id) {
        auto marker = reinterpret_cast<Marker>(this->GetClientData(ui_id));
        if (marker >= LABEL_ITEM_MARKER)
            continue;
        std::string   old_label = GetString(ui_id).utf8_str().data();
        std::string   preset_name = Preset::remove_suffix_modified(old_label);
        std::string   ph_printer_name;
        if (marker == LABEL_ITEM_PHYSICAL_PRINTER) {
            ph_printer_name = PhysicalPrinter::get_short_name(preset_name);
            preset_name = PhysicalPrinter::get_preset_name(preset_name);
        }
        Preset* preset = m_collection->find_preset(preset_name, false);
        if (preset) {
            std::string new_label = preset->label(true);
            if (marker == LABEL_ITEM_PHYSICAL_PRINTER)
                new_label = ph_printer_name + PhysicalPrinter::separator() + new_label;
            if (old_label != new_label) {
                SetString(ui_id, from_u8(new_label));
                SetItemBitmap(ui_id, *get_bmp(*preset));
                if (ui_id == GetSelection()) SetToolTip(wxString::FromUTF8(new_label.c_str())); // BBS
            }
        }
    }
#ifdef __APPLE__
    // wxWidgets on OSX do not upload the text of the combo box line automatically.
    // Force it to update by re-selecting.
    SetSelection(GetSelection());
#endif /* __APPLE __ */
}
References Slic3r::PresetCollection::find_preset(), Slic3r::GUI::from_u8(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::PhysicalPrinter::get_preset_name(), Slic3r::PhysicalPrinter::get_short_name(), ComboBox::GetCount(), ComboBox::GetSelection(), ComboBox::GetString(), Slic3r::Preset::label(), Slic3r::GUI::PresetComboBox::LABEL_ITEM_MARKER, Slic3r::GUI::PresetComboBox::LABEL_ITEM_PHYSICAL_PRINTER, Slic3r::GUI::PresetComboBox::m_collection, Slic3r::Preset::remove_suffix_modified(), Slic3r::PhysicalPrinter::separator(), ComboBox::SetItemBitmap(), ComboBox::SetSelection(), ComboBox::SetString(), and Slic3r::PresetCollection::update_dirty().
update_from_bundle()
void Slic3r::GUI::PresetComboBox::update_from_bundle () inherited
{
    this->update(m_collection->get_selected_preset().name);
}
References Slic3r::PresetCollection::get_selected_preset(), Slic3r::GUI::PresetComboBox::m_collection, Slic3r::Preset::name, and Slic3r::GUI::PresetComboBox::update().
update_selection()
void Slic3r::GUI::PresetComboBox::update_selection () protected inherited
{
    /* If selected_preset_item is still equal to INT_MAX, it means that
     * there is no presets added to the list.
     * So, select last combobox item ("Add/Remove preset")
     */
    validate_selection();
    SetSelection(m_last_selected);
#ifdef __WXMSW__
    // From the Windows 2004 the tooltip for preset combobox doesn't work after next call of SetTooltip()
    // (There was an issue, when tooltip doesn't appears after changing of the preset selection)
    // But this workaround seems to work: We should to kill tooltip and than set new tooltip value
    SetToolTip(NULL);
#endif
    SetToolTip(GetString(m_last_selected));
// A workaround for a set of issues related to text fitting into gtk widgets:
#if defined(__WXGTK20__) || defined(__WXGTK3__)
    GList* cells = gtk_cell_layout_get_cells(GTK_CELL_LAYOUT(m_widget));
    // 'cells' contains the GtkCellRendererPixBuf for the icon,
    // 'cells->next' contains GtkCellRendererText for the text we need to ellipsize
    if (!cells || !cells->next) return;
    auto cell = static_cast<GtkCellRendererText *>(cells->next->data);
    if (!cell) return;
    g_object_set(G_OBJECT(cell), "ellipsize", PANGO_ELLIPSIZE_END, (char*)NULL);
    // Only the list of cells must be freed, the renderer isn't ours to free
    g_list_free(cells);
#endif
}
References ComboBox::GetString(), Slic3r::GUI::PresetComboBox::m_last_selected, NULL, ComboBox::SetSelection(), and Slic3r::GUI::PresetComboBox::validate_selection().
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
validate_selection()
void Slic3r::GUI::PresetComboBox::validate_selection (bool predicate = false) protected inherited
{
    if (predicate ||
        // just in case: mark m_last_selected as a first added element
        m_last_selected == INT_MAX)
        m_last_selected = GetCount() - 1;
}
References ComboBox::GetCount(), and Slic3r::GUI::PresetComboBox::m_last_selected.
Referenced by Slic3r::GUI::PlaterPresetComboBox::update(), update(), Slic3r::GUI::PresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update_selection().
Member Data Documentation
datas
std::vector<void *> ComboBox::datas private inherited
Referenced by ComboBox::Append(), ComboBox::DoClear(), ComboBox::DoDeleteOneItem(), ComboBox::DoGetItemClientData(), ComboBox::DoInsertItems(), and ComboBox::DoSetItemClientData().
drop
DropDown ComboBox::drop private inherited
Referenced by ComboBox::Append(), ComboBox::DoClear(), ComboBox::DoDeleteOneItem(), ComboBox::DoInsertItems(), ComboBox::GetDropDown(), ComboBox::GetSelection(), ComboBox::GetValue(), ComboBox::keyDown(), ComboBox::mouseDown(), ComboBox::Rescale(), ComboBox::sendComboBoxEvent(), ComboBox::SetItemBitmap(), ComboBox::SetSelection(), ComboBox::SetString(), and ComboBox::SetValue().
drop_down
bool ComboBox::drop_down = false private inherited
Referenced by ComboBox::keyDown(), ComboBox::mouseDown(), and ComboBox::mouseWheelMoved().
icon_height
int Slic3r::GUI::PresetComboBox::icon_height protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::get_bmp().
icons
std::vector<wxBitmap> ComboBox::icons private inherited
Referenced by ComboBox::Append(), ComboBox::DoClear(), ComboBox::DoDeleteOneItem(), ComboBox::DoInsertItems(), ComboBox::GetItemBitmap(), ComboBox::SetItemBitmap(), ComboBox::SetSelection(), and ComboBox::SetValue().
m_bitmapCompatible
ScalableBitmap Slic3r::GUI::PresetComboBox::m_bitmapCompatible protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::msw_rescale().
m_bitmapIncompatible
ScalableBitmap Slic3r::GUI::PresetComboBox::m_bitmapIncompatible protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::msw_rescale().
m_collection
PresetCollection* Slic3r::GUI::PresetComboBox::m_collection {nullptr} protected inherited
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::add_ams_filaments(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::OnSelect(), Slic3r::GUI::PlaterPresetComboBox::OnSelect(), OnSelect(), presets(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), Slic3r::GUI::PresetComboBox::update(), Slic3r::GUI::PresetComboBox::update_ams_color(), update_dirty(), and Slic3r::GUI::PresetComboBox::update_from_bundle().
m_em_unit
int Slic3r::GUI::PresetComboBox::m_em_unit protected inherited
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::msw_rescale(), Slic3r::GUI::PlaterPresetComboBox::msw_rescale(), msw_rescale(), and Slic3r::GUI::PlaterPresetComboBox::update().
m_enable_all
bool Slic3r::GUI::TabPresetComboBox::m_enable_all {false} private
Referenced by set_enable_all().
m_filament_idx
int Slic3r::GUI::PresetComboBox::m_filament_idx = -1 protected inherited
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::PlaterPresetComboBox::change_extruder_color(), Slic3r::GUI::PresetComboBox::get_filament_idx(), Slic3r::GUI::PresetComboBox::set_filament_idx(), Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), Slic3r::GUI::PlaterPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update_ams_color().
m_first_ams_filament
int Slic3r::GUI::PresetComboBox::m_first_ams_filament = 0 protected inherited
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), and Slic3r::GUI::PresetComboBox::selected_ams_filament().
m_last_ams_filament
int Slic3r::GUI::PresetComboBox::m_last_ams_filament = 0 protected inherited
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), and Slic3r::GUI::PresetComboBox::selected_ams_filament().
m_last_selected
int Slic3r::GUI::PresetComboBox::m_last_selected protected inherited
Referenced by Slic3r::GUI::PresetComboBox::invalidate_selection(), Slic3r::GUI::PresetComboBox::OnSelect(), Slic3r::GUI::PlaterPresetComboBox::OnSelect(), OnSelect(), Slic3r::GUI::PresetComboBox::selected_ams_filament(), Slic3r::GUI::PresetComboBox::update_selection(), and Slic3r::GUI::PresetComboBox::validate_selection().
m_main_bitmap_name
std::string Slic3r::GUI::PresetComboBox::m_main_bitmap_name protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox().
m_preset_bundle
PresetBundle* Slic3r::GUI::PresetComboBox::m_preset_bundle {nullptr} protected inherited
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::add_ams_filaments(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::update(), and update().
m_show_all
bool Slic3r::GUI::PresetComboBox::m_show_all { false } private inherited
Referenced by Slic3r::GUI::PresetComboBox::show_all(), and Slic3r::GUI::PresetComboBox::update().
m_suppress_change
bool Slic3r::GUI::PresetComboBox::m_suppress_change { true } protected inherited
Referenced by Slic3r::GUI::PresetComboBox::PresetComboBox().
m_type
Preset::Type Slic3r::GUI::PresetComboBox::m_type protected inherited
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::PresetComboBox::PresetComboBox(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_tooltip(), Slic3r::GUI::PresetComboBox::get_type(), Slic3r::GUI::PlaterPresetComboBox::OnSelect(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PlaterPresetComboBox::show_edit_menu(), Slic3r::GUI::PlaterPresetComboBox::switch_to_tab(), type(), Slic3r::GUI::PlaterPresetComboBox::update(), update(), and Slic3r::GUI::PresetComboBox::update().
norm_icon_width
int Slic3r::GUI::PresetComboBox::norm_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::PresetComboBox::get_bmp(), and Slic3r::GUI::PresetComboBox::get_bmp().
on_selection_changed
std::function<void(int)> Slic3r::GUI::PresetComboBox::on_selection_changed { nullptr } protected inherited
Referenced by Slic3r::GUI::PresetComboBox::OnSelect(), OnSelect(), and Slic3r::GUI::PresetComboBox::set_selection_changed_function().
printer_technology
PrinterTechnology Slic3r::GUI::PresetComboBox::printer_technology {ptAny} protected inherited
Referenced by Slic3r::GUI::PresetComboBox::set_printer_technology(), and Slic3r::GUI::PresetComboBox::update().
show_incompatible
bool Slic3r::GUI::TabPresetComboBox::show_incompatible {false} private
Referenced by set_show_incompatible_presets(), and update().
space_icon_width
int Slic3r::GUI::PresetComboBox::space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
text_off
bool ComboBox::text_off = false private inherited
Referenced by ComboBox::GetLabel(), and ComboBox::SetLabel().
texts
std::vector<wxString> ComboBox::texts private inherited
Referenced by ComboBox::Append(), ComboBox::DoClear(), ComboBox::DoDeleteOneItem(), ComboBox::DoGetItemClientData(), ComboBox::DoInsertItems(), ComboBox::DoSetItemClientData(), ComboBox::GetCount(), ComboBox::GetString(), ComboBox::keyDown(), ComboBox::SetItemBitmap(), and ComboBox::SetString().
thin_icon_width
int Slic3r::GUI::PresetComboBox::thin_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
thin_space_icon_width
int Slic3r::GUI::PresetComboBox::thin_space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
types
std::vector<wxClientDataType> ComboBox::types private inherited
Referenced by ComboBox::Append(), ComboBox::DoClear(), ComboBox::DoDeleteOneItem(), and ComboBox::DoInsertItems().
wide_icon_width
int Slic3r::GUI::PresetComboBox::wide_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
wide_space_icon_width
int Slic3r::GUI::PresetComboBox::wide_space_icon_width protected inherited
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), and Slic3r::GUI::PresetComboBox::get_bmp().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PresetComboBoxes.hpp
src/slic3r/GUI/PresetComboBoxes.cpp