OrcaSlicer: Slic3r::GUI::GUI_App Class Reference
Slic3r::GUI::GUI_App Class Reference
#include <src/slic3r/GUI/GUI_App.hpp>
Public Types
enum class EAppMode : unsigned char { Editor , GCodeViewer }
Public Member Functions
void check_filaments_in_blacklist (std::string tag_supplier, std::string tag_material, bool &in_blacklist, std::string &action, std::string &info)
std::string get_local_models_path ()
bool OnInit () override
bool initialized () const
GUI_App ()
~GUI_App () override
void show_message_box (std::string msg)
EAppMode get_app_mode () const
Slic3r::DeviceManager * getDeviceManager ()
HMSQuery * get_hms_query ()
NetworkAgent * getAgent ()
bool is_editor () const
bool is_gcode_viewer () const
bool is_recreating_gui () const
std::string logo_name () const
bool show_gcode_window () const
void set_show_gcode_window (bool val)
void post_init ()
void shutdown ()
wxGLContext * init_glcontext (wxGLCanvas &canvas)
bool init_opengl ()
void init_download_path ()
const wxColour get_label_default_clr_system ()
const wxColour get_label_default_clr_modified ()
void init_label_colours ()
void update_label_colours_from_appconfig ()
void update_label_colours ()
void UpdateDarkUI (wxWindow *window, bool highlited=false, bool just_font=false)
void UpdateDarkUIWin (wxWindow *win)
void Update_dark_mode_flag ()
void UpdateDlgDarkUI (wxDialog *dlg)
void UpdateFrameDarkUI (wxFrame *dlg)
void UpdateDVCDarkUI (wxDataViewCtrl *dvc, bool highlited=false)
void UpdateAllStaticTextDarkUI (wxWindow *parent)
void init_fonts ()
void update_fonts (const MainFrame *main_frame=nullptr)
void set_label_clr_modified (const wxColour &clr)
void set_label_clr_sys (const wxColour &clr)
bool get_side_menu_popup_status ()
void set_side_menu_popup_status (bool status)
const wxColour & get_label_clr_modified ()
const wxColour & get_label_clr_sys ()
const wxColour & get_label_clr_default ()
const wxColour & get_window_default_clr ()
const wxColour & get_label_highlight_clr ()
const wxColour & get_highlight_default_clr ()
const wxColour & get_color_hovered_btn_label ()
const wxColour & get_color_selected_btn_bg ()
void force_colors_update ()
void force_menu_update ()
const wxFont & small_font ()
const wxFont & bold_font ()
const wxFont & normal_font ()
const wxFont & code_font ()
const wxFont & link_font ()
int em_unit () const
bool tabs_as_menu () const
wxSize get_min_size () const
float toolbar_icon_scale (const bool is_limited=false) const
void set_auto_toolbar_icon_scale (float scale) const
void check_printer_presets ()
void recreate_GUI (const wxString &message)
void system_info ()
void keyboard_shortcuts ()
void load_project (wxWindow *parent, wxString &input_file) const
void import_model (wxWindow *parent, wxArrayString &input_files) const
void load_gcode (wxWindow *parent, wxString &input_file) const
wxString transition_tridid (int trid_id)
void ShowUserGuide ()
void ShowDownNetPluginDlg ()
void ShowUserLogin (bool show=true)
void ShowOnlyFilament ()
void request_login (bool show_user_info=false)
bool check_login ()
void get_login_info ()
bool is_user_login ()
void request_user_login (int online_login=0)
void request_user_handle (int online_login=0)
void request_user_logout ()
int request_user_unbind (std::string dev_id)
std::string handle_web_request (std::string cmd)
void handle_script_message (std::string msg)
void request_model_download (std::string url)
void download_project (std::string project_id)
void request_project_download (std::string project_id)
void request_open_project (std::string project_id)
void request_remove_project (std::string project_id)
void handle_http_error (unsigned int status, std::string body)
void on_http_error (wxCommandEvent &evt)
void on_set_selected_machine (wxCommandEvent &evt)
void on_user_login (wxCommandEvent &evt)
void on_user_login_handle (wxCommandEvent &evt)
void enable_user_preset_folder (bool enable)
bool is_studio_active ()
void reset_to_active ()
void check_update (bool show_tips, int by_user)
void check_new_version (bool show_tips=false, int by_user=0)
void check_new_version_sf (bool show_tips=false, int by_user=0)
void request_new_version (int by_user)
void enter_force_upgrade ()
void set_skip_version (bool skip=true)
void no_new_version ()
void show_dialog (wxString msg)
void reload_settings ()
void remove_user_presets ()
void sync_preset (Preset *preset)
void start_sync_user_preset (bool load_immediately=false, bool with_progress_dlg=false)
void stop_sync_user_preset ()
void start_http_server ()
void stop_http_server ()
void on_show_check_privacy_dlg (int online_login=0)
void show_check_privacy_dlg (wxCommandEvent &evt)
void on_check_privacy_update (wxCommandEvent &evt)
bool check_privacy_update ()
void check_privacy_version (int online_login=0)
void check_track_enable ()
void persist_window_geometry (wxTopLevelWindow *window, bool default_maximized=false)
void update_ui_from_settings ()
bool switch_language ()
bool load_language (wxString language, bool initial)
Tab * get_tab (Preset::Type type)
Tab * get_model_tab (bool part=false)
Tab * get_layer_tab ()
ConfigOptionMode get_mode ()
void save_mode (const int mode)
void update_mode ()
void show_ip_address_enter_dialog (wxString title=wxEmptyString)
void show_ip_address_enter_dialog_handler (wxCommandEvent &evt)
bool show_modal_ip_address_enter_dialog (wxString title=wxEmptyString)
bool has_unsaved_preset_changes () const
bool has_current_preset_changes () const
void update_saved_preset_from_current_preset ()
std::vector< std::pair< unsigned int, std::string > > get_selected_presets () const
bool check_and_save_current_preset_changes (const wxString &caption, const wxString &header, bool remember_choice=true, bool use_dont_save_insted_of_discard=false)
void apply_keeped_preset_modifications ()
bool check_and_keep_current_preset_changes (const wxString &caption, const wxString &header, int action_buttons, bool *postponed_apply_of_keeped_changes=nullptr)
bool can_load_project ()
bool check_print_host_queue ()
bool checked_tab (Tab *tab)
void load_current_presets (bool active_preset_combox=false, bool check_printer_presets=true)
std::vector< std::string > & get_delete_cache_presets ()
std::vector< std::string > get_delete_cache_presets_lock ()
void delete_preset_from_cloud (std::string setting_id)
void preset_deleted_from_cloud (std::string setting_id)
wxString current_language_code () const
wxString current_language_code_safe () const
bool is_localized () const
void open_preferences (size_t open_on_tab=0, const std::string &highlight_option=std::string())
virtual bool OnExceptionInMainLoop () override
bool open_browser_with_warning_dialog (const wxString &url, int flags=0)
Sidebar & sidebar ()
ObjectSettings * obj_settings ()
ObjectList * obj_list ()
ObjectLayers * obj_layers ()
Plater * plater ()
const Plater * plater () const
ParamsPanel * params_panel ()
ParamsDialog * params_dialog ()
Model & model ()
NotificationManager * notification_manager ()
void set_download_model_url (std::string url)
void set_download_model_name (std::string name)
std::string get_download_model_url ()
std::string get_download_model_name ()
void load_url (wxString url)
void open_mall_page_dialog ()
void open_publish_page_dialog ()
void remove_mall_system_dialog ()
void run_script (wxString js)
bool is_adding_script_handler ()
void set_adding_script_handler (bool status)
char from_hex (char ch)
std::string url_encode (std::string value)
std::string url_decode (std::string value)
PresetUpdater * get_preset_updater ()
Notebook * tab_panel () const
int extruders_cnt () const
int extruders_edited_cnt () const
int filaments_cnt () const
RemovableDriveManager * removable_drive_manager ()
ImGuiWrapper * imgui ()
PrintHostJobQueue & printhost_job_queue ()
void open_web_page_localized (const std::string &http_address)
bool may_switch_to_SLA_preset (const wxString &caption)
bool run_wizard (ConfigWizard::RunReason reason, ConfigWizard::StartPage start_page=ConfigWizard::SP_WELCOME)
void show_desktop_integration_dialog ()
OpenGLManager & get_opengl_manager ()
GLShaderProgram * get_shader (const std::string &shader_name)
GLShaderProgram * get_current_shader ()
bool is_gl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
bool is_glsl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
int GetSingleChoiceIndex (const wxString &message, const wxString &caption, const wxArrayString &choices, int initialSelection)
std::string get_plugin_url (std::string name, std::string country_code)
int download_plugin (std::string name, std::string package_name, InstallProgressFn pro_fn=nullptr, WasCancelledFn cancel_fn=nullptr)
int install_plugin (std::string name, std::string package_name, InstallProgressFn pro_fn=nullptr, WasCancelledFn cancel_fn=nullptr)
std::string get_http_url (std::string country_code)
std::string get_model_http_url (std::string country_code)
bool is_compatibility_version ()
bool check_networking_version ()
void cancel_networking_install ()
void restart_networking ()
Static Public Member Functions
static std::string get_gl_info (bool for_github)
static unsigned get_colour_approx_luma (const wxColour &colour)
static bool dark_mode ()
static std::string format_display_version ()
static bool catch_error (std::function< void()> cb, const std::string &err)
Public Attributes
bool m_studio_active = true
std::chrono::system_clock::time_point last_active_point
std::string m_mall_model_download_url
std::string m_mall_model_download_name
ModelMallDialog * m_mall_publish_dialog { nullptr }
GUI_InitParams * init_params { nullptr }
AppConfig * app_config { nullptr }
PresetBundle * preset_bundle { nullptr }
PresetUpdater * preset_updater { nullptr }
MainFrame * mainframe { nullptr }
Plater * plater_ { nullptr }
std::vector< Tab * > tabs_list
std::vector< Tab * > model_tabs_list
Private Member Functions
int updating_bambu_networking ()
bool on_init_inner ()
void copy_network_if_available ()
bool on_init_network (bool try_backup=false)
void init_networking_callbacks ()
void init_app_config ()
void remove_old_networking_plugins ()
std::map< std::string, std::string > get_extra_header ()
void init_http_extra_header ()
void update_http_extra_header ()
bool check_older_app_config (Semver current_version, bool backup)
void copy_older_config ()
void window_pos_save (wxTopLevelWindow *window, const std::string &name)
bool window_pos_restore (wxTopLevelWindow *window, const std::string &name, bool default_maximized=false)
void window_pos_sanitize (wxTopLevelWindow *window)
void window_pos_center (wxTopLevelWindow *window)
bool select_language ()
bool config_wizard_startup ()
void check_updates (const bool verbose)
Private Attributes
bool m_initialized { false }
bool m_post_initialized { false }
bool m_app_conf_exists { false }
EAppMode m_app_mode { EAppMode::Editor }
bool m_is_recreating_gui { false }
std::string m_download_file_url
wxColour m_color_label_modified
wxColour m_color_label_sys
wxColour m_color_label_default
wxColour m_color_window_default
wxColour m_color_highlight_label_default
wxColour m_color_hovered_btn_label
wxColour m_color_default_btn_label
wxColour m_color_highlight_default
wxColour m_color_selected_btn_bg
bool m_force_colors_update { false }
wxFont m_small_font
wxFont m_bold_font
wxFont m_normal_font
wxFont m_code_font
wxFont m_link_font
int m_em_unit
std::unique_ptr< wxLocale > m_wxLocale
const wxLanguageInfo * m_language_info_system = nullptr
const wxLanguageInfo * m_language_info_best = nullptr
OpenGLManager m_opengl_mgr
std::unique_ptr< RemovableDriveManager > m_removable_drive_manager
std::unique_ptr< ImGuiWrapper > m_imgui
std::unique_ptr< PrintHostJobQueue > m_printhost_job_queue
bool m_is_closing {false}
Slic3r::DeviceManager * m_device_manager { nullptr }
NetworkAgent * m_agent { nullptr }
std::vector< std::string > need_delete_presets
bool m_networking_compatible { false }
bool m_networking_need_update { false }
bool m_networking_cancel_update { false }
std::shared_ptr< UpgradeNetworkJob > m_upgrade_network_job
ZUserLogin * login_dlg { nullptr }
VersionInfo version_info
VersionInfo privacy_version_info
HMSQuery * hms_query { nullptr }
boost::thread m_sync_update_thread
bool enable_sync = false
bool m_is_dark_mode { false }
bool m_adding_script_handler { false }
bool m_side_popup_status {false}
HttpServer m_http_server
bool m_show_gcode_window {true}
bool m_init_app_config_from_older { false }
bool m_datadir_redefined { false }
std::string m_older_data_dir_path
boost::optional< Semver > m_last_config_version
Static Private Attributes
static std::string version_display = ""
Detailed Description
Member Enumeration Documentation
EAppMode
enum class Slic3r::GUI::GUI_App::EAppMode : unsigned char strong
Enumerator
Editor
GCodeViewer
    {
        Editor,
        GCodeViewer
    };
Constructor & Destructor Documentation
GUI_App()
Slic3r::GUI::GUI_App::GUI_App () explicit
    : wxApp()
    //, m_app_mode(mode)
    , m_app_mode(EAppMode::Editor)
    , m_em_unit(10)
    , m_imgui(new ImGuiWrapper())
    , hms_query(new HMSQuery())
  , m_removable_drive_manager(std::make_unique<RemovableDriveManager>())
  //, m_other_instance_message_handler(std::make_unique<OtherInstanceMessageHandler>())
{
  //app config initializes early becasuse it is used in instance checking in OrcaSlicer.cpp
    this->init_app_config();
    this->init_download_path();
    reset_to_active();
}
~GUI_App()
Slic3r::GUI::GUI_App::~GUI_App () override
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": enter");
    if (app_config != nullptr) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": destroy app_config");
        delete app_config;
    }
    if (preset_bundle != nullptr) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": destroy preset_bundle");
        delete preset_bundle;
    }
    if (preset_updater != nullptr) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": destroy preset updater");
        delete preset_updater;
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": exit");
}
References app_config, preset_bundle, and preset_updater.
Member Function Documentation
apply_keeped_preset_modifications()
void Slic3r::GUI::GUI_App::apply_keeped_preset_modifications ()
{
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (Tab* tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology))
            tab->apply_config_from_cache();
    }
    load_current_presets(false);
}
References Slic3r::PresetCollection::get_edited_preset(), load_current_presets(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
Referenced by check_and_keep_current_preset_changes(), Slic3r::GUI::GuideFrame::run(), and Slic3r::GUI::ConfigWizard::run().
bold_font()
const wxFont & Slic3r::GUI::GUI_App::bold_font () inline
{ return m_bold_font; }
References m_bold_font.
can_load_project()
bool Slic3r::GUI::GUI_App::can_load_project ()
{
    return true;
}
cancel_networking_install()
void Slic3r::GUI::GUI_App::cancel_networking_install ()
{
    m_networking_cancel_update = true;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": plugin install cancelled!");
}
References m_networking_cancel_update.
catch_error()
bool Slic3r::GUI::GUI_App::catch_error (std::function< void()> cb, const std::string & err) static
{
    if (!err.empty()) {
        if (cb)
            cb();
        //         if (message_dialog)
        //             message_dialog->(err, "Error", wxOK | wxICON_ERROR);
        show_error(/*this*/nullptr, err);
        return true;
    }
    return false;
}
References Slic3r::GUI::show_error().
check_and_keep_current_preset_changes()
bool Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes (const wxString & caption, const wxString & header, int action_buttons, bool * postponed_apply_of_keeped_changes = nullptr)
{
    if (has_current_preset_changes()) {
        bool is_called_from_configwizard = postponed_apply_of_keeped_changes != nullptr;
        UnsavedChangesDialog dlg(caption, header, "", action_buttons);
        if (dlg.ShowModal() == wxID_CANCEL)
            return false;
        auto reset_modifications = [this, is_called_from_configwizard]() {
            //if (is_called_from_configwizard)
            //    return; // no need to discared changes. It will be done fromConfigWizard closing
            PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
            for (const Tab* const tab : tabs_list) {
                if (tab->supports_printer_technology(printer_technology) && tab->current_preset_is_dirty())
                    tab->m_presets->discard_current_changes();
            }
            load_current_presets(false);
        };
        if (dlg.discard())
            reset_modifications();
        else  // save selected changes
        {
            //BBS: add project embedded preset relate logic
            const auto& preset_names_and_types = dlg.get_names_and_types();
            if (dlg.save_preset()) {
                for (const UnsavedChangesDialog::PresetData& nt : preset_names_and_types)
                    preset_bundle->save_changes_for_preset(nt.name, nt.type, dlg.get_unselected_options(nt.type), nt.save_to_project);
                // if we saved changes to the new presets, we should to
                // synchronize config.ini with the current selections.
                preset_bundle->export_selections(*app_config);
                //wxString text = _L_PLURAL("Modifications to the preset have been saved",
                //    "Modifications to the presets have been saved", preset_names_and_types.size());
                //if (!is_called_from_configwizard)
                //    text += "\n\n" + _L("All modifications will be discarded for new project.");
                //MessageDialog(nullptr, text).ShowModal();
                reset_modifications();
            }
            else if (dlg.transfer_changes() && (dlg.has_unselected_options() || is_called_from_configwizard)) {
                // execute this part of code only if not all modifications are keeping to the new project
                // OR this function is called when ConfigWizard is closed and "Keep modifications" is selected
                for (const UnsavedChangesDialog::PresetData& nt : preset_names_and_types) {
                    Preset::Type type = nt.type;
                    Tab* tab = get_tab(type);
                    std::vector<std::string> selected_options = dlg.get_selected_options(type);
                    if (type == Preset::TYPE_PRINTER) {
                        auto it = std::find(selected_options.begin(), selected_options.end(), "extruders_count");
                        if (it != selected_options.end()) {
                            // erase "extruders_count" option from the list
                            selected_options.erase(it);
                            // cache the extruders count
                            static_cast<TabPrinter*>(tab)->cache_extruder_cnt();
                        }
                    }
                    std::vector<std::string> selected_options2;
                    std::transform(selected_options.begin(), selected_options.end(), std::back_inserter(selected_options2), [](auto & o) {
                        auto i = o.find('#');
                        return i != std::string::npos ? o.substr(0, i) : o;
                    });
                    tab->cache_config_diff(selected_options2);
                    if (!is_called_from_configwizard)
                        tab->m_presets->discard_current_changes();
                }
                if (is_called_from_configwizard)
                    *postponed_apply_of_keeped_changes = true;
                else
                    apply_keeped_preset_modifications();
            }
        }
    }
    return true;
}
References app_config, apply_keeped_preset_modifications(), Slic3r::GUI::Tab::cache_config_diff(), Slic3r::GUI::UnsavedChangesDialog::discard(), Slic3r::PresetCollection::discard_current_changes(), Slic3r::PresetBundle::export_selections(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::UnsavedChangesDialog::get_names_and_types(), Slic3r::GUI::UnsavedChangesDialog::get_selected_options(), get_tab(), Slic3r::GUI::UnsavedChangesDialog::get_unselected_options(), has_current_preset_changes(), Slic3r::GUI::UnsavedChangesDialog::has_unselected_options(), load_current_presets(), Slic3r::GUI::Tab::m_presets, preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::GUI::UnsavedChangesDialog::save_preset(), Slic3r::GUI::UnsavedChangesDialog::ShowModal(), tabs_list, Slic3r::GUI::UnsavedChangesDialog::transfer_changes(), and Slic3r::Preset::TYPE_PRINTER.
check_and_save_current_preset_changes()
bool Slic3r::GUI::GUI_App::check_and_save_current_preset_changes (const wxString & caption, const wxString & header, bool remember_choice = true, bool use_dont_save_insted_of_discard = false)
{
    if (has_current_preset_changes()) {
        int act_buttons = UnsavedChangesDialog::ActionButtons::SAVE;
        if (dont_save_insted_of_discard)
            act_buttons |= UnsavedChangesDialog::ActionButtons::DONT_SAVE;
        if (remember_choice)
            act_buttons |= UnsavedChangesDialog::ActionButtons::REMEMBER_CHOISE;
        UnsavedChangesDialog dlg(caption, header, "", act_buttons);
        if (dlg.ShowModal() == wxID_CANCEL)
            return false;
        if (dlg.save_preset())  // save selected changes
        {
            //BBS: add project embedded preset relate logic
            for (const UnsavedChangesDialog::PresetData& nt : dlg.get_names_and_types())
                preset_bundle->save_changes_for_preset(nt.name, nt.type, dlg.get_unselected_options(nt.type), nt.save_to_project);
            //for (const std::pair<std::string, Preset::Type>& nt : dlg.get_names_and_types())
            //    preset_bundle->save_changes_for_preset(nt.first, nt.second, dlg.get_unselected_options(nt.second));
            load_current_presets(false);
            // if we saved changes to the new presets, we should to
            // synchronize config.ini with the current selections.
            preset_bundle->export_selections(*app_config);
            //MessageDialog(nullptr, _L_PLURAL("Modifications to the preset have been saved",
            //                                 "Modifications to the presets have been saved", dlg.get_names_and_types().size())).ShowModal();
        }
    }
    return true;
}
References app_config, Slic3r::GUI::UnsavedChangesDialog::DONT_SAVE, Slic3r::PresetBundle::export_selections(), Slic3r::GUI::UnsavedChangesDialog::get_names_and_types(), Slic3r::GUI::UnsavedChangesDialog::get_unselected_options(), has_current_preset_changes(), load_current_presets(), preset_bundle, Slic3r::GUI::UnsavedChangesDialog::REMEMBER_CHOISE, Slic3r::GUI::UnsavedChangesDialog::SAVE, Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::GUI::UnsavedChangesDialog::save_preset(), and Slic3r::GUI::UnsavedChangesDialog::ShowModal().
check_filaments_in_blacklist()
void Slic3r::GUI::GUI_App::check_filaments_in_blacklist (std::string tag_supplier, std::string tag_material, bool & in_blacklist, std::string & action, std::string & info)
check_login()
bool Slic3r::GUI::GUI_App::check_login ()
{
    bool result = false;
    if (m_agent) {
        result = m_agent->is_user_login();
    }
    if (!result) {
        ShowUserLogin();
    }
    return result;
}
References Slic3r::NetworkAgent::is_user_login(), m_agent, and ShowUserLogin().
Referenced by request_project_download().
check_networking_version()
bool Slic3r::GUI::GUI_App::check_networking_version ()
{
    std::string network_ver = Slic3r::NetworkAgent::get_version();
    if (!network_ver.empty()) {
        BOOST_LOG_TRIVIAL(info) << "get_network_agent_version=" << network_ver;
    }
    std::string studio_ver = SLIC3R_VERSION;
    if (network_ver.length() >= 8) {
        if (network_ver.substr(0,8) == studio_ver.substr(0,8)) {
            m_networking_compatible = true;
            return true;
        }
    }
    m_networking_compatible = false;
    return false;
}
References Slic3r::NetworkAgent::get_version(), and m_networking_compatible.
Referenced by on_init_network().
check_new_version()
void Slic3r::GUI::GUI_App::check_new_version (bool show_tips = false, int by_user = 0)
{
    std::string platform = "windows";
#ifdef __WINDOWS__
    platform = "windows";
#endif
#ifdef __APPLE__
    platform = "macos";
#endif
#ifdef __LINUX__
    platform = "linux";
#endif
    std::string query_params = (boost::format("?name=slicer&version=%1%&guide_version=%2%")
        % VersionInfo::convert_full_version(SLIC3R_VERSION)
        % VersionInfo::convert_full_version("0.0.0.1")
        ).str();
    std::string url = get_http_url(app_config->get_country_code()) + query_params;
    Slic3r::Http http = Slic3r::Http::get(url);
    http.header("accept", "application/json")
        .timeout_connect(TIMEOUT_CONNECT)
        .timeout_max(TIMEOUT_RESPONSE)
        .on_complete([this, show_tips, by_user](std::string body, unsigned) {
        try {
            json j = json::parse(body);
            if (j.contains("message")) {
                if (j["message"].get<std::string>() == "success") {
                    if (j.contains("software")) {
                        if (j["software"].empty() && show_tips) {
                            this->no_new_version();
                        }
                        else {
                            if (j["software"].contains("url")
                                && j["software"].contains("version")
                                && j["software"].contains("description")) {
                                version_info.url = j["software"]["url"].get<std::string>();
                                version_info.version_str = j["software"]["version"].get<std::string>();
                                version_info.description = j["software"]["description"].get<std::string>();
                            }
                            if (j["software"].contains("force_update")) {
                                version_info.force_upgrade = j["software"]["force_update"].get<bool>();
                            }
                            CallAfter([this, show_tips, by_user](){
                                this->check_update(show_tips, by_user);
                            });
                        }
                    }
                }
            }
        }
        catch (...) {
            ;
        }
            })
        .on_error([this](std::string body, std::string error, unsigned int status) {
            handle_http_error(status, body);
            BOOST_LOG_TRIVIAL(error) << "check new version error" << body;
    }).perform();
}
References app_config, check_update(), Slic3r::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), Slic3r::GUI::VersionInfo::convert_full_version(), Slic3r::GUI::VersionInfo::description, Slic3r::empty(), error, Slic3r::GUI::VersionInfo::force_upgrade, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::Http::get(), Slic3r::AppConfig::get_country_code(), get_http_url(), handle_http_error(), Slic3r::Http::header(), no_new_version(), Slic3r::Http::on_complete(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::platform(), TIMEOUT_CONNECT, Slic3r::Http::timeout_connect(), Slic3r::Http::timeout_max(), TIMEOUT_RESPONSE, Slic3r::GUI::VersionInfo::url, version_info, and Slic3r::GUI::VersionInfo::version_str.
check_new_version_sf()
void Slic3r::GUI::GUI_App::check_new_version_sf (bool show_tips = false, int by_user = 0)
{
    AppConfig* app_config = wxGetApp().app_config;
    auto version_check_url = app_config->version_check_url();
    Http::get(version_check_url).on_error([&](std::string body, std::string error, unsigned http_status) {
        (void)body;
        BOOST_LOG_TRIVIAL(error) << format("Error getting: `%1%`: HTTP %2%, %3%",
            version_check_url,
            http_status,
            error);
        })
        .timeout_connect(1)
        .on_complete([&](std::string body, unsigned /* http_status */) {
            boost::trim(body);
            // SoftFever: parse github release, ported from SS
            boost::property_tree::ptree root;
            std::stringstream json_stream(body);
            boost::property_tree::read_json(json_stream, root);
            bool i_am_pre = false;
            //at least two number, use '.' as separator. can be followed by -Az23 for prereleased and +Az42 for metadata
            std::regex matcher("[0-9]+\\.[0-9]+(\\.[0-9]+)*(-[A-Za-z0-9]+)?(\\+[A-Za-z0-9]+)?");
            Semver current_version = get_version(SoftFever_VERSION, matcher);
            Semver best_pre(1, 0, 0);
            Semver best_release(1, 0, 0);
            std::string best_pre_url;
            std::string best_release_url;
            std::string best_release_content;
            std::string best_pre_content;
            const std::regex reg_num("([0-9]+)");
            for (auto json_version : root) {
                std::string tag = json_version.second.get<std::string>("tag_name");
                if (tag[0] == 'v')
                    tag.erase(0, 1);
                for (std::regex_iterator it = std::sregex_iterator(tag.begin(), tag.end(), reg_num); it != std::sregex_iterator(); ++it) {
                }
                Semver tag_version = get_version(tag, matcher);
                if (current_version == tag_version)
                    i_am_pre = json_version.second.get<bool>("prerelease");
                if (json_version.second.get<bool>("prerelease")) {
                    if (best_pre < tag_version) {
                        best_pre = tag_version;
                        best_pre_url = json_version.second.get<std::string>("html_url");
                        best_pre_content = json_version.second.get<std::string>("body");
                        best_pre.set_prerelease("Preview");
                    }
                }
                else {
                    if (best_release < tag_version) {
                        best_release = tag_version;
                        best_release_url = json_version.second.get<std::string>("html_url");
                        best_release_content = json_version.second.get<std::string>("body");
                    }
                }
            }
            //if release is more recent than beta, use release anyway
            if (best_pre < best_release) {
                best_pre = best_release;
                best_pre_url = best_release_url;
                best_pre_content = best_release_content;
            }
            //if we're the most recent, don't do anything
            if ((i_am_pre ? best_pre : best_release) <= current_version)
                return;
            //BOOST_LOG_TRIVIAL(info) << format("Got %1% online version: `%2%`. Sending to GUI thread...", SLIC3R_APP_NAME, i_am_pre ? best_pre.to_string(): best_release.to_string());
            version_info.url = i_am_pre ? best_pre_url : best_release_url;
            version_info.version_str = i_am_pre ? best_pre.to_string() : best_release.to_string_sf();
            version_info.description = i_am_pre ? best_pre_content : best_release_content;
            version_info.force_upgrade = false;
            wxCommandEvent* evt = new wxCommandEvent(EVT_SLIC3R_VERSION_ONLINE);
            evt->SetString((i_am_pre ? best_pre : best_release).to_string());
            GUI::wxGetApp().QueueEvent(evt);
            })
            .perform_sync();;
}
References app_config, Slic3r::GUI::VersionInfo::description, error, Slic3r::GUI::VersionInfo::force_upgrade, Slic3r::GUI::format(), Slic3r::Http::get(), Slic3r::GUI::get_version(), Slic3r::Http::on_complete(), Slic3r::Http::on_error(), Slic3r::Semver::set_prerelease(), Slic3r::Semver::to_string(), Slic3r::to_string(), Slic3r::Semver::to_string_sf(), Slic3r::GUI::VersionInfo::url, Slic3r::AppConfig::version_check_url(), version_info, Slic3r::GUI::VersionInfo::version_str, and void().
Referenced by post_init().
check_older_app_config()
bool Slic3r::GUI::GUI_App::check_older_app_config (Semver current_version, bool backup) private
{
    //BBS: current no need these logic
    return false;
}
check_print_host_queue()
bool Slic3r::GUI::GUI_App::check_print_host_queue ()
{
    wxString dirty;
    std::vector<std::pair<std::string, std::string>> jobs;
    // Get ongoing jobs from dialog
    mainframe->m_printhost_queue_dlg->get_active_jobs(jobs);
    if (jobs.empty())
        return true;
    // Show dialog
    wxString job_string = wxString();
    for (const auto& job : jobs) {
        job_string += format_wxstr("   %1% : %2% \n", job.first, job.second);
    }
    wxString message;
    message += _(L("The uploads are still ongoing")) + ":\n\n" + job_string +"\n" + _(L("Stop them and continue anyway?"));
    //wxMessageDialog dialog(mainframe,
    MessageDialog dialog(mainframe,
        message,
        wxString(SLIC3R_APP_NAME) + " - " + _(L("Ongoing uploads")),
        wxICON_QUESTION | wxYES_NO | wxNO_DEFAULT);
    if (dialog.ShowModal() == wxID_YES)
        return true;
    // TODO: If already shown, bring forward
    mainframe->m_printhost_queue_dlg->Show();
    return false;
}
References _, Slic3r::GUI::format_wxstr(), Slic3r::GUI::PrintHostQueueDialog::get_active_jobs(), L, Slic3r::GUI::MainFrame::m_printhost_queue_dlg, mainframe, Slic3r::GUI::PrintHostQueueDialog::Show(), and Slic3r::GUI::DPIAware< P >::ShowModal().
check_printer_presets()
void Slic3r::GUI::GUI_App::check_printer_presets ()
{
//BBS
#if 0
    std::vector<std::string> preset_names = PhysicalPrinter::presets_with_print_host_information(preset_bundle->printers);
    if (preset_names.empty())
        return;
    // BBS: remove "print host upload" message dialog
    preset_bundle->physical_printers.load_printers_from_presets(preset_bundle->printers);
#endif
}
References Slic3r::PhysicalPrinterCollection::load_printers_from_presets(), Slic3r::PresetBundle::physical_printers, preset_bundle, Slic3r::PhysicalPrinter::presets_with_print_host_information(), and Slic3r::PresetBundle::printers.
Referenced by load_current_presets().
check_privacy_update()
bool Slic3r::GUI::GUI_App::check_privacy_update ()
{
    if (privacy_version_info.version_str.empty() || privacy_version_info.description.empty()
        || privacy_version_info.url.empty()) {
        return false;
    }
    std::string local_privacy_ver = app_config->get("privacy_version");
    auto curr_version = Semver::parse(local_privacy_ver);
    auto remote_version = Semver::parse(privacy_version_info.version_str);
    if (curr_version && remote_version) {
        if (*remote_version > *curr_version || app_config->get("privacy_update_checked") != "true") {
            return true;
        }
    }
    return false;
}
References app_config, Slic3r::GUI::VersionInfo::description, Slic3r::AppConfig::get(), Slic3r::Semver::parse(), privacy_version_info, Slic3r::GUI::VersionInfo::url, and Slic3r::GUI::VersionInfo::version_str.
Referenced by on_check_privacy_update().
check_privacy_version()
void Slic3r::GUI::GUI_App::check_privacy_version (int online_login = 0)
{
    update_http_extra_header();
    std::string query_params = "?policy/privacy=00.00.00.00";
    std::string url = get_http_url(app_config->get_country_code()) + query_params;
    Slic3r::Http http = Slic3r::Http::get(url);
    http.header("accept", "application/json")
        .timeout_connect(TIMEOUT_CONNECT)
        .timeout_max(TIMEOUT_RESPONSE)
        .on_complete([this, online_login](std::string body, unsigned) {
            try {
                json j = json::parse(body);
                if (j.contains("message")) {
                    if (j["message"].get<std::string>() == "success") {
                        if (j.contains("resources")) {
                            for (auto it = j["resources"].begin(); it != j["resources"].end(); it++) {
                                if (it->contains("type")) {
                                    if ((*it)["type"] == std::string("policy/privacy")
                                        && it->contains("version")
                                        && it->contains("description")
                                        && it->contains("url")
                                        && it->contains("force_update")) {
                                        privacy_version_info.version_str = (*it)["version"].get<std::string>();
                                        privacy_version_info.description = (*it)["description"].get<std::string>();
                                        privacy_version_info.url = (*it)["url"].get<std::string>();
                                        privacy_version_info.force_upgrade = (*it)["force_update"].get<bool>();
                                        break;
                                    }
                                }
                            }
                            CallAfter([this, online_login]() {
                                auto evt = new wxCommandEvent(EVT_CHECK_PRIVACY_VER);
                                evt->SetInt(online_login);
                                wxQueueEvent(this, evt);
                            });
                        }
                    }
                }
            }
            catch (...) {
                request_user_handle(online_login);
            }
        })
        .on_error([this, online_login](std::string body, std::string error, unsigned int status) {
            request_user_handle(online_login);
            BOOST_LOG_TRIVIAL(error) << "check privacy version error" << body;
    }).perform();
}
References app_config, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), Slic3r::GUI::VersionInfo::description, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, Slic3r::GUI::VersionInfo::force_upgrade, Slic3r::Http::get(), Slic3r::AppConfig::get_country_code(), get_http_url(), Slic3r::Http::header(), Slic3r::Http::on_complete(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), privacy_version_info, request_user_handle(), TIMEOUT_CONNECT, Slic3r::Http::timeout_connect(), Slic3r::Http::timeout_max(), TIMEOUT_RESPONSE, update_http_extra_header(), Slic3r::GUI::VersionInfo::url, and Slic3r::GUI::VersionInfo::version_str.
Referenced by on_user_login(), and post_init().
check_track_enable()
void Slic3r::GUI::GUI_App::check_track_enable ()
{
    // Orca: alaways disable track event
    return;
    if (app_config && app_config->get("firstguide", "privacyuse") == "true") {
        //enable track event
        json header_json;
        header_json["ver"] = SLIC3R_VERSION;
        wxString os_desc = wxGetOsDescription();
        int major = 0, minor = 0, micro = 0;
        header_json["os"] = std::string(os_desc.ToUTF8());
        header_json["name"] = std::string(SLIC3R_APP_NAME);
        if (m_agent) {
            m_agent->track_header(header_json.dump());
            m_agent->track_enable(true);
        }
    }
}
References app_config, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), Slic3r::AppConfig::get(), m_agent, Slic3r::NetworkAgent::track_enable(), and Slic3r::NetworkAgent::track_header().
Referenced by on_user_login().
check_update()
void Slic3r::GUI::GUI_App::check_update (bool show_tips, int by_user)
{
    if (version_info.version_str.empty()) return;
    if (version_info.url.empty()) return;
    auto curr_version = Semver::parse(SLIC3R_VERSION);
    auto remote_version = Semver::parse(version_info.version_str);
    if (curr_version && remote_version && (*remote_version > *curr_version)) {
        if (version_info.force_upgrade) {
            wxGetApp().app_config->set_bool("force_upgrade", version_info.force_upgrade);
            wxGetApp().app_config->set("upgrade", "force_upgrade", true);
            wxGetApp().app_config->set("upgrade", "description", version_info.description);
            wxGetApp().app_config->set("upgrade", "version", version_info.version_str);
            wxGetApp().app_config->set("upgrade", "url", version_info.url);
            GUI::wxGetApp().enter_force_upgrade();
        }
        else {
            GUI::wxGetApp().request_new_version(by_user);
        }
    } else {
        wxGetApp().app_config->set("upgrade", "force_upgrade", false);
        if (show_tips)
            this->no_new_version();
    }
}
References Slic3r::GUI::VersionInfo::description, Slic3r::GUI::VersionInfo::force_upgrade, no_new_version(), Slic3r::Semver::parse(), Slic3r::GUI::VersionInfo::url, version_info, and Slic3r::GUI::VersionInfo::version_str.
Referenced by check_new_version().
check_updates()
void Slic3r::GUI::GUI_App::check_updates (const bool verbose) private
{
  PresetUpdater::UpdateResult updater_result;
  try {
    updater_result = preset_updater->config_update(app_config->orig_version(), verbose ? PresetUpdater::UpdateParams::SHOW_TEXT_BOX : PresetUpdater::UpdateParams::SHOW_NOTIFICATION);
    if (updater_result == PresetUpdater::R_INCOMPAT_EXIT) {
      mainframe->Close();
    }
    else if (updater_result == PresetUpdater::R_INCOMPAT_CONFIGURED) {
            m_app_conf_exists = true;
    }
    else if (verbose && updater_result == PresetUpdater::R_NOOP) {
      MsgNoUpdates dlg;
      dlg.ShowModal();
    }
  }
  catch (const std::exception & ex) {
    show_error(nullptr, ex.what());
  }
}
References app_config, Slic3r::PresetUpdater::config_update(), m_app_conf_exists, mainframe, Slic3r::AppConfig::orig_version(), preset_updater, Slic3r::PresetUpdater::R_INCOMPAT_CONFIGURED, Slic3r::PresetUpdater::R_INCOMPAT_EXIT, Slic3r::PresetUpdater::R_NOOP, Slic3r::GUI::show_error(), Slic3r::PresetUpdater::SHOW_NOTIFICATION, Slic3r::PresetUpdater::SHOW_TEXT_BOX, and Slic3r::GUI::DPIAware< P >::ShowModal().
Referenced by post_init().
checked_tab()
bool Slic3r::GUI::GUI_App::checked_tab (Tab * tab)
{
    bool ret = true;
    if (find(tabs_list.begin(), tabs_list.end(), tab) == tabs_list.end() &&
        find(model_tabs_list.begin(), model_tabs_list.end(), tab) == model_tabs_list.end())
        ret = false;
    return ret;
}
References model_tabs_list, and tabs_list.
code_font()
const wxFont & Slic3r::GUI::GUI_App::code_font () inline
{ return m_code_font; }
References m_code_font.
config_wizard_startup()
bool Slic3r::GUI::GUI_App::config_wizard_startup () private
{
    if (!m_app_conf_exists || preset_bundle->printers.only_default_printers()) {
        BOOST_LOG_TRIVIAL(info) << "run wizard...";
        run_wizard(ConfigWizard::RR_DATA_EMPTY);
        BOOST_LOG_TRIVIAL(info) << "finished run wizard";
        return true;
    } /*else if (get_app_config()->legacy_datadir()) {
        // Looks like user has legacy pre-vendorbundle data directory,
        // explain what this is and run the wizard
        MsgDataLegacy dlg;
        dlg.ShowModal();
        run_wizard(ConfigWizard::RR_DATA_LEGACY);
        return true;
    }*/
    return false;
}
References m_app_conf_exists, Slic3r::PrinterPresetCollection::only_default_printers(), preset_bundle, Slic3r::PresetBundle::printers, Slic3r::GUI::ConfigWizard::RR_DATA_EMPTY, and run_wizard().
Referenced by post_init().
copy_network_if_available()
void Slic3r::GUI::GUI_App::copy_network_if_available () private
{
    if (app_config->get("update_network_plugin") != "true")
        return;
    std::string network_library, player_library, network_library_dst, player_library_dst;
    std::string data_dir_str = data_dir();
    boost::filesystem::path data_dir_path(data_dir_str);
    auto plugin_folder = data_dir_path / "plugins";
    auto cache_folder = data_dir_path / "ota";
    std::string changelog_file = cache_folder.string() + "/network_plugins.json";
#if defined(_MSC_VER) || defined(_WIN32)
    network_library = cache_folder.string() + "/bambu_networking.dll";
    player_library = cache_folder.string() + "/BambuSource.dll";
    network_library_dst = plugin_folder.string() + "/bambu_networking.dll";
    player_library_dst = plugin_folder.string() + "/BambuSource.dll";
#elif defined(__WXMAC__)
    network_library = cache_folder.string() + "/libbambu_networking.dylib";
    player_library = cache_folder.string() + "/libBambuSource.dylib";
    network_library_dst = plugin_folder.string() + "/libbambu_networking.dylib";
    player_library_dst = plugin_folder.string() + "/libBambuSource.dylib";
#else
    network_library = cache_folder.string() + "/libbambu_networking.so";
    player_library = cache_folder.string() + "/libBambuSource.so";
    network_library_dst = plugin_folder.string() + "/libbambu_networking.so";
    player_library_dst = plugin_folder.string() + "/libBambuSource.so";
#endif
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< ": checking network_library " << network_library << ", player_library " << player_library;
    if (!boost::filesystem::exists(plugin_folder)) {
        BOOST_LOG_TRIVIAL(info)<< __FUNCTION__ << ": create directory "<<plugin_folder.string();
        boost::filesystem::create_directory(plugin_folder);
    }
    std::string error_message;
    if (boost::filesystem::exists(network_library)) {
        CopyFileResult cfr = copy_file(network_library, network_library_dst, error_message, false);
        if (cfr != CopyFileResult::SUCCESS) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": Copying failed(" << cfr << "): " << error_message;
            return;
        }
        static constexpr const auto perms = fs::owner_read | fs::owner_write | fs::group_read | fs::others_read;
        fs::permissions(network_library_dst, perms);
        fs::remove(network_library);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< ": Copying network library from" << network_library << " to " << network_library_dst<<" successfully.";
    }
    if (boost::filesystem::exists(player_library)) {
        CopyFileResult cfr = copy_file(player_library, player_library_dst, error_message, false);
        if (cfr != CopyFileResult::SUCCESS) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": Copying failed(" << cfr << "): " << error_message;
            return;
        }
        static constexpr const auto perms = fs::owner_read | fs::owner_write | fs::group_read | fs::others_read;
        fs::permissions(player_library_dst, perms);
        fs::remove(player_library);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< ": Copying player library from" << player_library << " to " << player_library_dst<<" successfully.";
    }
    if (boost::filesystem::exists(changelog_file))
        fs::remove(changelog_file);
    app_config->set("update_network_plugin", "false");
}
References app_config, Slic3r::copy_file(), Slic3r::data_dir(), error, Slic3r::AppConfig::get(), Slic3r::AppConfig::set(), and Slic3r::SUCCESS.
copy_older_config()
void Slic3r::GUI::GUI_App::copy_older_config () private
{
    preset_bundle->copy_files(m_older_data_dir_path);
}
References Slic3r::PresetBundle::copy_files(), m_older_data_dir_path, and preset_bundle.
Referenced by on_init_inner().
current_language_code()
wxString Slic3r::GUI::GUI_App::current_language_code () const inline
{ return m_wxLocale->GetCanonicalName(); }
References m_wxLocale.
Referenced by current_language_code_safe(), open_mall_page_dialog(), open_publish_page_dialog(), and post_init().
current_language_code_safe()
wxString Slic3r::GUI::GUI_App::current_language_code_safe () const
{
  // Translate the language code to a code, for which Prusa Research maintains translations.
  const std::map<wxString, wxString> mapping {
    { "cs",   "cs_CZ", },
    { "sk",   "cs_CZ", },
    { "de",   "de_DE", },
    { "nl",   "nl_NL", },
    { "sv",   "sv_SE", },
    { "es",   "es_ES", },
    { "fr",   "fr_FR", },
    { "it",   "it_IT", },
    { "ja",   "ja_JP", },
    { "ko",   "ko_KR", },
    { "pl",   "pl_PL", },
    { "uk",   "uk_UA", },
    { "zh",   "zh_CN", },
    { "ru",   "ru_RU", },
  };
  wxString language_code = this->current_language_code().BeforeFirst('_');
  auto it = mapping.find(language_code);
  if (it != mapping.end())
    language_code = it->second;
  else
    language_code = "en_US";
  return language_code;
}
References current_language_code().
Referenced by open_web_page_localized().
dark_mode()
bool Slic3r::GUI::GUI_App::dark_mode () static
{
#ifdef SUPPORT_DARK_MODE
#if __APPLE__
    // The check for dark mode returns false positive on 10.12 and 10.13,
    // which allowed setting dark menu bar and dock area, which is
    // is detected as dark mode. We must run on at least 10.14 where the
    // proper dark mode was first introduced.
    return wxPlatformInfo::Get().CheckOSVersion(10, 14) && mac_dark_mode();
#else
    return wxGetApp().app_config->get("dark_color_mode") == "1" ? true : check_dark_mode();
    //const unsigned luma = get_colour_approx_luma(wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW));
    //return luma < 128;
#endif
#else
    //BBS disable DarkUI mode
    return false;
#endif
}
References Slic3r::GUI::check_dark_mode(), and Slic3r::GUI::mac_dark_mode().
Referenced by force_colors_update(), get_label_default_clr_modified(), get_label_default_clr_system(), init_label_colours(), on_init_inner(), Update_dark_mode_flag(), and UpdateDVCDarkUI().
delete_preset_from_cloud()
void Slic3r::GUI::GUI_App::delete_preset_from_cloud (std::string setting_id)
{
    std::scoped_lock l(mutex_delete_cache_presets);
    need_delete_presets.push_back(setting_id);
}
References Slic3r::GUI::mutex_delete_cache_presets, and need_delete_presets.
download_plugin()
int Slic3r::GUI::GUI_App::download_plugin (std::string name, std::string package_name, InstallProgressFn pro_fn = nullptr, WasCancelledFn cancel_fn = nullptr)
{
    int result = 0;
    json j;
    std::string err_msg;
    // get country_code
    AppConfig* app_config = wxGetApp().app_config;
    if (!app_config) {
        j["result"] = "failed";
        j["error_msg"] = "app_config is nullptr";
        if (m_agent) {
            m_agent->track_event("networkplugin_download", j.dump());
        }
        return -1;
    }
    BOOST_LOG_TRIVIAL(info) << "[download_plugin]: enter";
    m_networking_cancel_update = false;
    // get temp path
    fs::path target_file_path = (fs::temp_directory_path() / package_name);
    fs::path tmp_path = target_file_path;
    tmp_path += format(".%1%%2%", get_current_pid(), ".tmp");
    // get_url
    std::string  url = get_plugin_url(name, app_config->get_country_code());
    std::string download_url;
    Slic3r::Http http_url = Slic3r::Http::get(url);
    BOOST_LOG_TRIVIAL(info) << "[download_plugin]: check the plugin from " << url;
    http_url.timeout_connect(TIMEOUT_CONNECT)
        .timeout_max(TIMEOUT_RESPONSE)
        .on_complete(
        [&download_url](std::string body, unsigned status) {
            try {
                json j = json::parse(body);
                std::string message = j["message"].get<std::string>();
                if (message == "success") {
                    json resource = j.at("resources");
                    if (resource.is_array()) {
                        for (auto iter = resource.begin(); iter != resource.end(); iter++) {
                            Semver version;
                            std::string url;
                            std::string type;
                            std::string vendor;
                            std::string description;
                            for (auto sub_iter = iter.value().begin(); sub_iter != iter.value().end(); sub_iter++) {
                                if (boost::iequals(sub_iter.key(), "type")) {
                                    type = sub_iter.value();
                                    BOOST_LOG_TRIVIAL(info) << "[download_plugin]: get version of settings's type, " << sub_iter.value();
                                }
                                else if (boost::iequals(sub_iter.key(), "version")) {
                                    version = *(Semver::parse(sub_iter.value()));
                                }
                                else if (boost::iequals(sub_iter.key(), "description")) {
                                    description = sub_iter.value();
                                }
                                else if (boost::iequals(sub_iter.key(), "url")) {
                                    url = sub_iter.value();
                                }
                            }
                            BOOST_LOG_TRIVIAL(info) << "[download_plugin 1]: get type " << type << ", version " << version.to_string() << ", url " << url;
                            download_url = url;
                        }
                    }
                }
                else {
                    BOOST_LOG_TRIVIAL(info) << "[download_plugin 1]: get version of plugin failed, body=" << body;
                }
            }
            catch (...) {
                BOOST_LOG_TRIVIAL(error) << "[download_plugin 1]: catch unknown exception";
                ;
            }
        }).on_error(
            [&result, &err_msg](std::string body, std::string error, unsigned int status) {
                BOOST_LOG_TRIVIAL(error) << "[download_plugin 1] on_error: " << error<<", body = " << body;
                err_msg += "[download_plugin 1] on_error: " + error + ", body = " + body;
                result = -1;
        }).perform_sync();
    bool cancel = false;
    if (result < 0) {
        j["result"] = "failed";
        j["error_msg"] = err_msg;
        if (m_agent) {
            m_agent->track_event("networkplugin_download", j.dump());
        }
        if (pro_fn) pro_fn(InstallStatusDownloadFailed, 0, cancel);
        return result;
    }
    if (download_url.empty()) {
        BOOST_LOG_TRIVIAL(info) << "[download_plugin 1]: no available plugin found for this app version: " << SLIC3R_VERSION;
        if (pro_fn) pro_fn(InstallStatusDownloadFailed, 0, cancel);
        j["result"] = "failed";
        j["error_msg"] = "[download_plugin 1]: no available plugin found for this app version: " + std::string(SLIC3R_VERSION);
        if (m_agent) {
            m_agent->track_event("networkplugin_download", j.dump());
        }
        return -1;
    }
    else if (pro_fn) {
        pro_fn(InstallStatusNormal, 5, cancel);
    }
    if (m_networking_cancel_update || cancel) {
        BOOST_LOG_TRIVIAL(info) << boost::format("[download_plugin 1]: %1%, cancelled by user") % __LINE__;
        j["result"] = "failed";
        j["error_msg"] = (boost::format("[download_plugin 1]: %1%, cancelled by user") % __LINE__).str();
        if (m_agent) {
            m_agent->track_event("networkplugin_download", j.dump());
        }
        return -1;
    }
    BOOST_LOG_TRIVIAL(info) << "[download_plugin] get_url = " << download_url;
    // download
    Slic3r::Http http = Slic3r::Http::get(download_url);
    int reported_percent = 0;
    http.on_progress(
        [this, &pro_fn, cancel_fn, &result, &reported_percent, &err_msg](Slic3r::Http::Progress progress, bool& cancel) {
            int percent = 0;
            if (progress.dltotal != 0)
                percent = progress.dlnow * 50 / progress.dltotal;
            bool was_cancel = false;
            if (pro_fn && ((percent - reported_percent) >= 10)) {
                pro_fn(InstallStatusNormal, percent, was_cancel);
                reported_percent = percent;
                BOOST_LOG_TRIVIAL(info) << "[download_plugin 2] progress: " << reported_percent;
            }
            cancel = m_networking_cancel_update || was_cancel;
            if (cancel_fn)
                if (cancel_fn())
                    cancel = true;
            if (cancel) {
                err_msg += "[download_plugin] cancel";
                result = -1;
            }
        })
        .on_complete([&pro_fn, tmp_path, target_file_path](std::string body, unsigned status) {
            BOOST_LOG_TRIVIAL(info) << "[download_plugin 2] completed";
            bool cancel = false;
            int percent = 0;
            fs::fstream file(tmp_path, std::ios::out | std::ios::binary | std::ios::trunc);
            file.write(body.c_str(), body.size());
            file.close();
            fs::rename(tmp_path, target_file_path);
            if (pro_fn) pro_fn(InstallStatusDownloadCompleted, 80, cancel);
            })
        .on_error([&pro_fn, &result, &err_msg](std::string body, std::string error, unsigned int status) {
            bool cancel = false;
            if (pro_fn) pro_fn(InstallStatusDownloadFailed, 0, cancel);
            BOOST_LOG_TRIVIAL(error) << "[download_plugin 2] on_error: " << error<<", body = " << body;
            err_msg += "[download_plugin 2] on_error: " + error + ", body = " + body;
            result = -1;
        });
    http.perform_sync();
    j["result"] = result < 0 ? "failed" : "success";
    j["error_msg"] = err_msg;
    if (m_agent) {
        m_agent->track_event("networkplugin_download", j.dump());
    }
    return result;
}
References app_config, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), Slic3r::Http::Progress::dlnow, Slic3r::Http::Progress::dltotal, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, Slic3r::GUI::format(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::Http::get(), Slic3r::AppConfig::get_country_code(), Slic3r::get_current_pid(), get_plugin_url(), Slic3r::GUI::InstallStatusDownloadCompleted, Slic3r::GUI::InstallStatusDownloadFailed, Slic3r::GUI::InstallStatusNormal, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::is_array(), m_agent, m_networking_cancel_update, Slic3r::Http::on_complete(), Slic3r::Http::on_progress(), Slic3r::Semver::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::Http::perform_sync(), TIMEOUT_CONNECT, Slic3r::Http::timeout_connect(), Slic3r::Http::timeout_max(), TIMEOUT_RESPONSE, Slic3r::Semver::to_string(), and Slic3r::NetworkAgent::track_event().
download_project()
void Slic3r::GUI::GUI_App::download_project (std::string project_id)
{
    if (plater_) {
        plater_->request_download_project(project_id);
    }
}
References plater_, and Slic3r::GUI::Plater::request_download_project().
Referenced by request_project_download().
em_unit()
int Slic3r::GUI::GUI_App::em_unit () const inline
{ return m_em_unit; }
References m_em_unit.
enable_user_preset_folder()
void Slic3r::GUI::GUI_App::enable_user_preset_folder (bool enable)
{
    if (enable) {
        std::string user_id = m_agent->get_user_id();
        app_config->set("preset_folder", user_id);
        GUI::wxGetApp().preset_bundle->update_user_presets_directory(user_id);
    } else {
        BOOST_LOG_TRIVIAL(info) << "preset_folder: set to empty";
        app_config->set("preset_folder", "");
        GUI::wxGetApp().preset_bundle->update_user_presets_directory(DEFAULT_USER_FOLDER_NAME);
    }
}
References app_config, DEFAULT_USER_FOLDER_NAME, Slic3r::NetworkAgent::get_user_id(), m_agent, and Slic3r::AppConfig::set().
Referenced by on_user_login_handle(), start_sync_user_preset(), and stop_sync_user_preset().
enter_force_upgrade()
void Slic3r::GUI::GUI_App::enter_force_upgrade ()
{
    wxCommandEvent *evt = new wxCommandEvent(EVT_ENTER_FORCE_UPGRADE);
    GUI::wxGetApp().QueueEvent(evt);
}
extruders_cnt()
int Slic3r::GUI::GUI_App::extruders_cnt () const
{
    const Preset& preset = preset_bundle->printers.get_selected_preset();
    return preset.printer_technology() == ptSLA ? 1 :
           preset.config.option<ConfigOptionFloats>("nozzle_diameter")->values.size();
}
References Slic3r::Preset::config, Slic3r::PresetCollection::get_selected_preset(), Slic3r::ConfigBase::option(), preset_bundle, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptSLA, and Slic3r::ConfigOptionVector< T >::size().
extruders_edited_cnt()
int Slic3r::GUI::GUI_App::extruders_edited_cnt () const
{
    const Preset& preset = preset_bundle->printers.get_edited_preset();
    return preset.printer_technology() == ptSLA ? 1 :
           preset.config.option<ConfigOptionFloats>("nozzle_diameter")->values.size();
}
References Slic3r::Preset::config, Slic3r::PresetCollection::get_edited_preset(), Slic3r::ConfigBase::option(), preset_bundle, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptSLA, and Slic3r::ConfigOptionVector< T >::size().
filaments_cnt()
int Slic3r::GUI::GUI_App::filaments_cnt () const
{
    return preset_bundle->filament_presets.size();
}
References Slic3r::PresetBundle::filament_presets, and preset_bundle.
force_colors_update()
void Slic3r::GUI::GUI_App::force_colors_update ()
{
#ifdef _MSW_DARK_MODE
#ifdef __WINDOWS__
    NppDarkMode::SetDarkMode(dark_mode());
    if (WXHWND wxHWND = wxToolTip::GetToolTipCtrl())
        NppDarkMode::SetDarkExplorerTheme((HWND)wxHWND);
    NppDarkMode::SetDarkTitleBar(mainframe->GetHWND());
    //NppDarkMode::SetDarkExplorerTheme((HWND)mainframe->m_settings_dialog.GetHWND());
    //NppDarkMode::SetDarkTitleBar(mainframe->m_settings_dialog.GetHWND());
#endif // __WINDOWS__
#endif //_MSW_DARK_MODE
    m_force_colors_update = true;
}
References dark_mode(), m_force_colors_update, mainframe, NppDarkMode::SetDarkExplorerTheme(), NppDarkMode::SetDarkMode(), and NppDarkMode::SetDarkTitleBar().
force_menu_update()
void Slic3r::GUI::GUI_App::force_menu_update ()
format_display_version()
std::string Slic3r::GUI::GUI_App::format_display_version () static
{
    if (!version_display.empty())
        return version_display;
    version_display = SoftFever_VERSION;
    return version_display;
}
References version_display.
Referenced by Slic3r::GUI::BBLSplashScreen::ConstantText::init(), and Slic3r::GUI::AboutDialog::onCopyToClipboard().
from_hex()
char Slic3r::GUI::GUI_App::from_hex (char ch)
{
    return isdigit(ch) ? ch - '0' : tolower(ch) - 'a' + 10;
}
get_app_mode()
EAppMode Slic3r::GUI::GUI_App::get_app_mode () const inline
{ return m_app_mode; }
References m_app_mode.
get_color_hovered_btn_label()
const wxColour & Slic3r::GUI::GUI_App::get_color_hovered_btn_label () inline
{ return m_color_hovered_btn_label; }
References m_color_hovered_btn_label.
get_color_selected_btn_bg()
const wxColour & Slic3r::GUI::GUI_App::get_color_selected_btn_bg () inline
{ return m_color_selected_btn_bg; }
References m_color_selected_btn_bg.
get_colour_approx_luma()
unsigned Slic3r::GUI::GUI_App::get_colour_approx_luma (const wxColour & colour) static
{
    double r = colour.Red();
    double g = colour.Green();
    double b = colour.Blue();
    return std::round(std::sqrt(
        r * r * .241 +
        g * g * .691 +
        b * b * .068
        ));
}
get_current_shader()
GLShaderProgram * Slic3r::GUI::GUI_App::get_current_shader () inline
{ return m_opengl_mgr.get_current_shader(); }
References Slic3r::GUI::OpenGLManager::get_current_shader(), and m_opengl_mgr.
get_delete_cache_presets()
std::vector< std::string > & Slic3r::GUI::GUI_App::get_delete_cache_presets ()
{
    return need_delete_presets;
}
References need_delete_presets.
Referenced by reload_settings().
get_delete_cache_presets_lock()
std::vector< std::string > Slic3r::GUI::GUI_App::get_delete_cache_presets_lock ()
{
    std::scoped_lock l(mutex_delete_cache_presets);
    return need_delete_presets;
}
References Slic3r::GUI::mutex_delete_cache_presets, and need_delete_presets.
Referenced by start_sync_user_preset().
get_download_model_name()
std::string Slic3r::GUI::GUI_App::get_download_model_name () inline
{return m_mall_model_download_name;}
References m_mall_model_download_name.
get_download_model_url()
std::string Slic3r::GUI::GUI_App::get_download_model_url () inline
{return m_mall_model_download_url;}
References m_mall_model_download_url.
get_extra_header()
std::map< std::string, std::string > Slic3r::GUI::GUI_App::get_extra_header () private
{
    std::map<std::string, std::string> extra_headers;
    extra_headers.insert(std::make_pair("X-BBL-Client-Type", "slicer"));
    extra_headers.insert(std::make_pair("X-BBL-Client-Name", SLIC3R_APP_NAME));
    extra_headers.insert(std::make_pair("X-BBL-Client-Version", VersionInfo::convert_full_version(SLIC3R_VERSION)));
#if defined(__WINDOWS__)
    extra_headers.insert(std::make_pair("X-BBL-OS-Type", "windows"));
#elif defined(__APPLE__)
    extra_headers.insert(std::make_pair("X-BBL-OS-Type", "macos"));
#elif defined(__LINUX__)
    extra_headers.insert(std::make_pair("X-BBL-OS-Type", "linux"));
#endif
    int major = 0, minor = 0, micro = 0;
    wxGetOsVersion(&major, &minor, &micro);
    std::string os_version = (boost::format("%1%.%2%.%3%") % major % minor % micro).str();
    extra_headers.insert(std::make_pair("X-BBL-OS-Version", os_version));
    if (app_config)
        extra_headers.insert(std::make_pair("X-BBL-Device-ID", app_config->get("slicer_uuid")));
    extra_headers.insert(std::make_pair("X-BBL-Language", convert_studio_language_to_api(app_config->get("language"))));
    return extra_headers;
}
References app_config, Slic3r::GUI::VersionInfo::convert_full_version(), Slic3r::GUI::convert_studio_language_to_api(), Slic3r::extra_headers, and Slic3r::AppConfig::get().
Referenced by init_http_extra_header(), on_init_inner(), and update_http_extra_header().
get_gl_info()
std::string Slic3r::GUI::GUI_App::get_gl_info (bool for_github) static
{
    return OpenGLManager::get_gl_info().to_string(for_github);
}
References Slic3r::GUI::OpenGLManager::get_gl_info(), and Slic3r::GUI::OpenGLManager::GLInfo::to_string().
get_highlight_default_clr()
const wxColour & Slic3r::GUI::GUI_App::get_highlight_default_clr () inline
{ return m_color_highlight_default; }
References m_color_highlight_default.
get_hms_query()
HMSQuery * Slic3r::GUI::GUI_App::get_hms_query () inline
{ return hms_query; }
References hms_query.
get_http_url()
std::string Slic3r::GUI::GUI_App::get_http_url (std::string country_code)
{
    std::string url;
    if (country_code == "US") {
        url = "https://api.bambulab.com/";
    }
    else if (country_code == "CN") {
        url = "https://api.bambulab.cn/";
    }
    else if (country_code == "ENV_CN_DEV") {
        url = "https://api-dev.bambu-lab.com/";
    }
    else if (country_code == "ENV_CN_QA") {
        url = "https://api-qa.bambu-lab.com/";
    }
    else if (country_code == "ENV_CN_PRE") {
        url = "https://api-pre.bambu-lab.com/";
    }
    else {
        url = "https://api.bambulab.com/";
    }
    url += "v1/iot-service/api/slicer/resource";
    return url;
}
Referenced by check_new_version(), check_privacy_version(), get_plugin_url(), and post_init().
get_label_clr_default()
const wxColour & Slic3r::GUI::GUI_App::get_label_clr_default () inline
{ return m_color_label_default; }
References m_color_label_default.
get_label_clr_modified()
const wxColour & Slic3r::GUI::GUI_App::get_label_clr_modified () inline
{ return m_color_label_modified; }
References m_color_label_modified.
get_label_clr_sys()
const wxColour & Slic3r::GUI::GUI_App::get_label_clr_sys () inline
{ return m_color_label_sys; }
References m_color_label_sys.
get_label_default_clr_modified()
const wxColour Slic3r::GUI::GUI_App::get_label_default_clr_modified ()
{
    return dark_mode() ? wxColour(253, 111, 40) : wxColour(252, 77, 1);
}
References dark_mode().
get_label_default_clr_system()
const wxColour Slic3r::GUI::GUI_App::get_label_default_clr_system ()
{
    return dark_mode() ? wxColour(115, 220, 103) : wxColour(26, 132, 57);
}
References dark_mode().
get_label_highlight_clr()
const wxColour & Slic3r::GUI::GUI_App::get_label_highlight_clr () inline
{ return m_color_highlight_label_default; }
References m_color_highlight_label_default.
get_layer_tab()
Tab * Slic3r::GUI::GUI_App::get_layer_tab ()
{
    return model_tabs_list[2];
}
References model_tabs_list.
get_local_models_path()
std::string Slic3r::GUI::GUI_App::get_local_models_path ()
{
    std::string local_path = "";
    if (data_dir().empty()) {
        return local_path;
    }
    auto models_folder = (boost::filesystem::path(data_dir()) / "models");
    local_path = models_folder.string();
    if (!fs::exists(models_folder)) {
        if (!fs::create_directory(models_folder)) {
            local_path = "";
        }
        BOOST_LOG_TRIVIAL(info) << "create models folder:" << models_folder.string();
    }
    return local_path;
}
References Slic3r::data_dir(), and Slic3r::empty().
get_login_info()
void Slic3r::GUI::GUI_App::get_login_info ()
{
    if (m_agent) {
        if (m_agent->is_user_login()) {
            std::string login_cmd = m_agent->build_login_cmd();
            wxString strJS = wxString::Format("window.postMessage(%s)", login_cmd);
            GUI::wxGetApp().run_script(strJS);
        }
        else {
            m_agent->user_logout();
            std::string logout_cmd = m_agent->build_logout_cmd();
            wxString strJS = wxString::Format("window.postMessage(%s)", logout_cmd);
            GUI::wxGetApp().run_script(strJS);
        }
    }
}
References Slic3r::NetworkAgent::build_login_cmd(), Slic3r::NetworkAgent::build_logout_cmd(), Slic3r::NetworkAgent::is_user_login(), m_agent, and Slic3r::NetworkAgent::user_logout().
Referenced by handle_web_request(), and request_login().
get_min_size()
wxSize Slic3r::GUI::GUI_App::get_min_size () const
{
    return wxSize(76*m_em_unit, 49 * m_em_unit);
}
References m_em_unit.
get_mode()
ConfigOptionMode Slic3r::GUI::GUI_App::get_mode ()
{
    if (!app_config->has("user_mode"))
        return comSimple;
    //BBS
    const auto mode = app_config->get("user_mode");
    return mode == "advanced" ? comAdvanced :
           mode == "simple" ? comSimple :
           mode == "develop" ? comDevelop : comSimple;
}
References app_config, Slic3r::comAdvanced, Slic3r::comDevelop, Slic3r::comSimple, Slic3r::AppConfig::get(), and Slic3r::AppConfig::has().
get_model_http_url()
std::string Slic3r::GUI::GUI_App::get_model_http_url (std::string country_code)
{
    std::string url;
    if (country_code == "US") {
        url = "https://makerhub.bambu-lab.com/";
    }
    else if (country_code == "CN") {
        url = "https://makerhub.bambu-lab.com/zh/";
    }
    else if (country_code == "ENV_CN_DEV") {
        url = "https://makerhub-dev.bambu-lab.com/";
    }
    else if (country_code == "ENV_CN_QA") {
        url = "https://makerhub-qa.bambu-lab.com/";
    }
    else if (country_code == "ENV_CN_PRE") {
        url = "https://makerhub-pre.bambu-lab.com/";
    }
    else {
        url = "https://makerhub.bambu-lab.com/";
    }
    return url;
}
Referenced by open_mall_page_dialog(), and open_publish_page_dialog().
get_model_tab()
Tab * Slic3r::GUI::GUI_App::get_model_tab (bool part = false)
{
    return model_tabs_list[part ? 1 : 0];
}
References model_tabs_list.
get_opengl_manager()
OpenGLManager & Slic3r::GUI::GUI_App::get_opengl_manager () inline
{ return m_opengl_mgr; }
References m_opengl_mgr.
get_plugin_url()
std::string Slic3r::GUI::GUI_App::get_plugin_url (std::string name, std::string country_code)
{
    std::string url = get_http_url(country_code);
    std::string curr_version = SLIC3R_VERSION;
    std::string using_version = curr_version.substr(0, 9) + "00";
    if (name == "cameratools")
        using_version = curr_version.substr(0, 6) + "00.00";
    url += (boost::format("?slicer/%1%/cloud=%2%") % name % using_version).str();
    //url += (boost::format("?slicer/plugins/cloud=%1%") % "01.01.00.00").str();
    return url;
}
References get_http_url().
Referenced by download_plugin().
get_preset_updater()
PresetUpdater * Slic3r::GUI::GUI_App::get_preset_updater () inline
{ return preset_updater; }
References preset_updater.
get_selected_presets()
std::vector< std::pair< unsigned int, std::string > > Slic3r::GUI::GUI_App::get_selected_presets () const
{
    std::vector<std::pair<unsigned int, std::string>> ret;
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (Tab* tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology)) {
            const PresetCollection* presets = tab->get_presets();
            ret.push_back({ static_cast<unsigned int>(presets->type()), presets->get_selected_preset_name() });
        }
    }
    return ret;
}
References Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_presets(), Slic3r::PresetCollection::get_selected_preset_name(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, tabs_list, and Slic3r::PresetCollection::type().
Referenced by Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets(), and Slic3r::GUI::ProjectDirtyStateManager::update_from_presets().
get_shader()
GLShaderProgram * Slic3r::GUI::GUI_App::get_shader (const std::string & shader_name) inline
{ return m_opengl_mgr.get_shader(shader_name); }
References Slic3r::GUI::OpenGLManager::get_shader(), and m_opengl_mgr.
get_side_menu_popup_status()
bool Slic3r::GUI::GUI_App::get_side_menu_popup_status ()
{
    return m_side_popup_status;
}
References m_side_popup_status.
get_tab()
Tab * Slic3r::GUI::GUI_App::get_tab (Preset::Type type)
{
    for (Tab* tab: tabs_list)
        if (tab->type() == type)
            return tab->completed() ? tab : nullptr; // To avoid actions with no-completed Tab
    return nullptr;
}
References Slic3r::GUI::Tab::completed(), and tabs_list.
Referenced by check_and_keep_current_preset_changes().
get_window_default_clr()
const wxColour & Slic3r::GUI::GUI_App::get_window_default_clr () inline
{ return m_color_window_default; }
References m_color_window_default.
getAgent()
NetworkAgent * Slic3r::GUI::GUI_App::getAgent () inline
{ return m_agent; }
References m_agent.
Referenced by open_mall_page_dialog(), and open_publish_page_dialog().
getDeviceManager()
Slic3r::DeviceManager * Slic3r::GUI::GUI_App::getDeviceManager () inline
{ return m_device_manager; }
References m_device_manager.
GetSingleChoiceIndex()
int Slic3r::GUI::GUI_App::GetSingleChoiceIndex (const wxString & message, const wxString & caption, const wxArrayString & choices, int initialSelection)
{
#ifdef _WIN32
    wxSingleChoiceDialog dialog(nullptr, message, caption, choices);
    dialog.SetBackgroundColour(*wxWHITE);
    wxGetApp().UpdateDlgDarkUI(&dialog);
    dialog.SetSelection(initialSelection);
    return dialog.ShowModal() == wxID_OK ? dialog.GetSelection() : -1;
#else
    return wxGetSingleChoiceIndex(message, caption, choices, initialSelection);
#endif
}
Referenced by select_language().
handle_http_error()
void Slic3r::GUI::GUI_App::handle_http_error (unsigned int status, std::string body)
{
    // tips body size must less than 1024
    auto evt = new wxCommandEvent(EVT_HTTP_ERROR);
    evt->SetInt(status);
    evt->SetString(wxString(body));
    wxQueueEvent(this, evt);
}
Referenced by check_new_version(), post_init(), and restart_networking().
handle_script_message()
void Slic3r::GUI::GUI_App::handle_script_message (std::string msg)
{
    try {
        json j = json::parse(msg);
        if (j.contains("command")) {
            wxString cmd = j["command"];
            if (cmd == "user_login") {
                if (m_agent) {
                    m_agent->change_user(j.dump());
                    if (m_agent->is_user_login()) {
                        request_user_login(1);
                    }
                }
            }
        }
    }
    catch (...) {
        ;
    }
}
References Slic3r::NetworkAgent::change_user(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), Slic3r::NetworkAgent::is_user_login(), m_agent, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), and request_user_login().
handle_web_request()
std::string Slic3r::GUI::GUI_App::handle_web_request (std::string cmd)
{
    try {
        //BBS use nlohmann json format
        std::stringstream ss(cmd), oss;
        pt::ptree root, response;
        pt::read_json(ss, root);
        if (root.empty())
            return "";
        boost::optional<std::string> sequence_id = root.get_optional<std::string>("sequence_id");
        boost::optional<std::string> command = root.get_optional<std::string>("command");
        if (command.has_value()) {
            std::string command_str = command.value();
            if (command_str.compare("request_project_download") == 0) {
                if (root.get_child_optional("data") != boost::none) {
                    pt::ptree data_node = root.get_child("data");
                    boost::optional<std::string> project_id = data_node.get_optional<std::string>("project_id");
                    if (project_id.has_value()) {
                        this->request_project_download(project_id.value());
                    }
                }
            }
            else if (command_str.compare("open_project") == 0) {
                if (root.get_child_optional("data") != boost::none) {
                    pt::ptree data_node = root.get_child("data");
                    boost::optional<std::string> project_id = data_node.get_optional<std::string>("project_id");
                    if (project_id.has_value()) {
                        this->request_open_project(project_id.value());
                    }
                }
            }
            else if (command_str.compare("get_login_info") == 0) {
                CallAfter([this] {
                        get_login_info();
                    });
            }
            else if (command_str.compare("homepage_login_or_register") == 0) {
                CallAfter([this] {
                    this->request_login(true);
                });
            }
            else if (command_str.compare("homepage_logout") == 0) {
                CallAfter([this] {
                    wxGetApp().request_user_logout();
                });
            }
            else if (command_str.compare("homepage_modeldepot") == 0) {
                CallAfter([this] {
                    wxGetApp().open_mall_page_dialog();
                });
            }
            else if (command_str.compare("homepage_newproject") == 0) {
                this->request_open_project("<new>");
            }
            else if (command_str.compare("homepage_openproject") == 0) {
                this->request_open_project({});
            }
            else if (command_str.compare("get_recent_projects") == 0) {
                if (mainframe) {
                    if (mainframe->m_webview) {
                        mainframe->m_webview->SendRecentList(from_u8(sequence_id.value()));
                    }
                }
            }
            else if (command_str.compare("homepage_open_recentfile") == 0) {
                if (root.get_child_optional("data") != boost::none) {
                    pt::ptree data_node = root.get_child("data");
                    boost::optional<std::string> path = data_node.get_optional<std::string>("path");
                    if (path.has_value()) {
                        this->request_open_project(path.value());
                    }
                }
            }
            else if (command_str.compare("homepage_delete_recentfile") == 0) {
                if (root.get_child_optional("data") != boost::none) {
                    pt::ptree                    data_node = root.get_child("data");
                    boost::optional<std::string> path      = data_node.get_optional<std::string>("path");
                    if (path.has_value()) {
                        this->request_remove_project(path.value());
                    }
                }
            }
            else if (command_str.compare("homepage_delete_all_recentfile") == 0) {
                this->request_remove_project("");
            }
            else if (command_str.compare("homepage_explore_recentfile") == 0) {
                if (root.get_child_optional("data") != boost::none) {
                    pt::ptree                    data_node = root.get_child("data");
                    boost::optional<std::string> path      = data_node.get_optional<std::string>("path");
                    if (path.has_value())
                    {
                        boost::filesystem::path NowFile(path.value());
                        std::string FilePath = NowFile.make_preferred().string();
                        desktop_open_any_folder(FilePath);
                    }
                }
            }
            else if (command_str.compare("homepage_open_hotspot") == 0) {
                if (root.get_child_optional("data") != boost::none) {
                    pt::ptree data_node = root.get_child("data");
                    boost::optional<std::string> url = data_node.get_optional<std::string>("url");
                    if (url.has_value()) {
                        this->request_open_project(url.value());
                    }
                }
            }
            else if (command_str.compare("begin_network_plugin_download") == 0) {
                CallAfter([this] { wxGetApp().ShowDownNetPluginDlg(); });
            }
            else if (command_str.compare("get_web_shortcut") == 0) {
                if (root.get_child_optional("key_event") != boost::none) {
                    pt::ptree key_event_node = root.get_child("key_event");
                    auto keyCode = key_event_node.get<int>("key");
                    auto ctrlKey = key_event_node.get<bool>("ctrl");
                    auto shiftKey = key_event_node.get<bool>("shift");
                    auto cmdKey = key_event_node.get<bool>("cmd");
                    wxKeyEvent e(wxEVT_CHAR_HOOK);
#ifdef __APPLE__
                    e.SetControlDown(cmdKey);
                    e.SetRawControlDown(ctrlKey);
#else
                    e.SetControlDown(ctrlKey);
#endif
                    e.SetShiftDown(shiftKey);
                    keyCode     = keyCode == 188 ? ',' : keyCode;
                    e.m_keyCode = keyCode;
                    e.SetEventObject(mainframe);
                    wxPostEvent(mainframe, e);
                }
            }
            else if (command_str.compare("userguide_wiki_open") == 0) {
                if (root.get_child_optional("data") != boost::none) {
                    pt::ptree                    data_node = root.get_child("data");
                    boost::optional<std::string> path      = data_node.get_optional<std::string>("url");
                    if (path.has_value()) {
                        wxLaunchDefaultBrowser(path.value());
                    }
                }
            }
            else if (command_str.compare("homepage_open_ccabin") == 0) {
                if (root.get_child_optional("data") != boost::none) {
                    pt::ptree                    data_node = root.get_child("data");
                    boost::optional<std::string> path      = data_node.get_optional<std::string>("file");
                    if (path.has_value()) {
                        std::string Fullpath = resources_dir() + "/web/homepage/model/" + path.value();
                        this->request_open_project(Fullpath);
                    }
                }
            }
        }
    }
    catch (...) {
        BOOST_LOG_TRIVIAL(trace) << "parse json cmd failed " << cmd;
        return "";
    }
    return "";
}
References Slic3r::GUI::desktop_open_any_folder(), Slic3r::GUI::from_u8(), get_login_info(), Slic3r::GUI::MainFrame::m_webview, mainframe, request_login(), request_open_project(), request_project_download(), request_remove_project(), Slic3r::resources_dir(), Slic3r::GUI::WebViewPanel::SendRecentList(), and Slic3r::trace().
has_current_preset_changes()
bool Slic3r::GUI::GUI_App::has_current_preset_changes () const
{
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (const Tab* const tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology) && tab->current_preset_is_dirty())
            return true;
    }
    return false;
}
References Slic3r::PresetCollection::get_edited_preset(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
Referenced by check_and_keep_current_preset_changes(), and check_and_save_current_preset_changes().
has_unsaved_preset_changes()
bool Slic3r::GUI::GUI_App::has_unsaved_preset_changes () const
{
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (const Tab* const tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology) && tab->saved_preset_is_dirty())
            return true;
    }
    return false;
}
References Slic3r::PresetCollection::get_edited_preset(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
Referenced by Slic3r::GUI::ProjectDirtyStateManager::update_from_presets().
imgui()
ImGuiWrapper * Slic3r::GUI::GUI_App::imgui () inline
{ return m_imgui.get(); }
References m_imgui.
import_model()
void Slic3r::GUI::GUI_App::import_model (wxWindow * parent, wxArrayString & input_files) const
{
    input_files.Clear();
    wxFileDialog dialog(parent ? parent : GetTopWindow(),
        _L("Choose one or more files (3mf/step/stl/svg/obj/amf):"),
        from_u8(app_config->get_last_dir()), "",
        file_wildcards(FT_MODEL), wxFD_OPEN | wxFD_MULTIPLE | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() == wxID_OK)
        dialog.GetPaths(input_files);
}
References _L, app_config, Slic3r::GUI::file_wildcards(), Slic3r::GUI::from_u8(), Slic3r::GUI::FT_MODEL, and Slic3r::AppConfig::get_last_dir().
init_app_config()
void Slic3r::GUI::GUI_App::init_app_config () private
{
  // Profiles for the alpha are stored into the PrusaSlicer-alpha directory to not mix with the current release.
    SetAppName(SLIC3R_APP_KEY);
//  SetAppName(SLIC3R_APP_KEY "-alpha");
//  SetAppName(SLIC3R_APP_KEY "-beta");
//  SetAppDisplayName(SLIC3R_APP_NAME);
  // Set the Slic3r data directory at the Slic3r XS module.
  // Unix: ~/ .Slic3r
  // Windows : "C:\Users\username\AppData\Roaming\Slic3r" or "C:\Documents and Settings\username\Application Data\Slic3r"
  // Mac : "~/Library/Application Support/Slic3r"
    if (data_dir().empty()) {
        boost::filesystem::path data_dir_path;
        #ifndef __linux__
            std::string data_dir = wxStandardPaths::Get().GetUserDataDir().ToUTF8().data();
            //BBS create folder if not exists
            data_dir_path = boost::filesystem::path(data_dir);
            set_data_dir(data_dir);
        #else
            // Since version 2.3, config dir on Linux is in ${XDG_CONFIG_HOME}.
            // https://github.com/prusa3d/PrusaSlicer/issues/2911
            wxString dir;
            if (! wxGetEnv(wxS("XDG_CONFIG_HOME"), &dir) || dir.empty() )
                dir = wxFileName::GetHomeDir() + wxS("/.config");
            set_data_dir((dir + "/" + GetAppName()).ToUTF8().data());
            data_dir_path = boost::filesystem::path(data_dir());
        #endif
        if (!boost::filesystem::exists(data_dir_path)){
            auto older_data_dir = data_dir_path.parent_path() / "BambuStudio-SoftFever";
            if(boost::filesystem::exists(older_data_dir)){
                copy_directory_recursively(older_data_dir,data_dir_path);
                boost::system::error_code ec;
                boost::filesystem::rename(data_dir_path / "BambuStudio.conf", data_dir_path / "OrcaSlicer.conf", ec);
                boost::filesystem::rename(data_dir_path / "BambuStudio.conf.bak", data_dir_path / "OrcaSlicer.conf.bak", ec);
            }
            else
                boost::filesystem::create_directory(data_dir_path);
        }
    } else {
        m_datadir_redefined = true;
    }
    // start log here
    std::time_t       t        = std::time(0);
    std::tm *         now_time = std::localtime(&t);
    std::stringstream buf;
    buf << std::put_time(now_time, "debug_%a_%b_%d_%H_%M_%S_");
    buf << get_current_pid() << ".log";
    std::string log_filename = buf.str();
#if !BBL_RELEASE_TO_PUBLIC
    set_log_path_and_level(log_filename, 5);
#else
    set_log_path_and_level(log_filename, 3);
#endif
    //BBS: remove GCodeViewer as seperate APP logic
  if (!app_config)
        app_config = new AppConfig();
        //app_config = new AppConfig(is_editor() ? AppConfig::EAppMode::Editor : AppConfig::EAppMode::GCodeViewer);
  // load settings
  m_app_conf_exists = app_config->exists();
  if (m_app_conf_exists) {
        std::string error = app_config->load();
        if (!error.empty()) {
            // Error while parsing config file. We'll customize the error message and rethrow to be displayed.
            throw Slic3r::RuntimeError(
                _u8L("OrcaSlicer configuration file may be corrupted and is not abled to be parsed."
                     "Please delete the file and try again.") +
                "\n\n" + app_config->config_path() + "\n\n" + error);
        }
        // Save orig_version here, so its empty if no app_config existed before this run.
        m_last_config_version = app_config->orig_version();//parse_semver_from_ini(app_config->config_path());
    }
    else {
#ifdef _WIN32
        // update associate files from registry information
        if (is_associate_files(L"3mf")) {
            app_config->set("associate_3mf", "true");
        }
        if (is_associate_files(L"stl")) {
            app_config->set("associate_stl", "true");
        }
        if (is_associate_files(L"step") && is_associate_files(L"stp")) {
            app_config->set("associate_step", "true");
        }
#endif // _WIN32
    }
}
References _u8L, app_config, Slic3r::AppConfig::config_path(), Slic3r::copy_directory_recursively(), Slic3r::data_dir(), Slic3r::empty(), error, Slic3r::AppConfig::exists(), Slic3r::get_current_pid(), L, Slic3r::AppConfig::load(), m_app_conf_exists, m_datadir_redefined, m_last_config_version, Slic3r::AppConfig::orig_version(), Slic3r::AppConfig::set(), Slic3r::set_data_dir(), and Slic3r::set_log_path_and_level().
init_download_path()
void Slic3r::GUI::GUI_App::init_download_path ()
{
    std::string down_path = app_config->get("download_path");
    if (down_path.empty()) {
        std::string user_down_path = wxStandardPaths::Get().GetUserDir(wxStandardPaths::Dir_Downloads).ToUTF8().data();
        app_config->set("download_path", user_down_path);
    }
    else {
        fs::path dp(down_path);
        if (!fs::exists(dp)) {
            std::string user_down_path = wxStandardPaths::Get().GetUserDir(wxStandardPaths::Dir_Downloads).ToUTF8().data();
            app_config->set("download_path", user_down_path);
        }
    }
}
References app_config, Slic3r::AppConfig::get(), and Slic3r::AppConfig::set().
init_fonts()
void Slic3r::GUI::GUI_App::init_fonts ()
{
    // BBS: modify font
    m_small_font = Label::Body_10;
    m_bold_font = Label::Body_10.Bold();
    m_normal_font = Label::Body_10;
#ifdef __WXMAC__
    m_small_font.SetPointSize(11);
    m_bold_font.SetPointSize(13);
#endif /*__WXMAC__*/
    // wxSYS_OEM_FIXED_FONT and wxSYS_ANSI_FIXED_FONT use the same as
    // DEFAULT in wxGtk. Use the TELETYPE family as a work-around
    m_code_font = wxFont(wxFontInfo().Family(wxFONTFAMILY_TELETYPE));
    m_code_font.SetPointSize(m_small_font.GetPointSize());
}
References Label::Body_10, m_bold_font, m_code_font, m_normal_font, and m_small_font.
Referenced by on_init_inner().
init_glcontext()
wxGLContext * Slic3r::GUI::GUI_App::init_glcontext (wxGLCanvas & canvas)
{
    return m_opengl_mgr.init_glcontext(canvas);
}
References Slic3r::GUI::OpenGLManager::init_glcontext(), and m_opengl_mgr.
init_http_extra_header()
void Slic3r::GUI::GUI_App::init_http_extra_header () private
{
    std::map<std::string, std::string> extra_headers = get_extra_header();
    if (m_agent)
        m_agent->set_extra_http_header(extra_headers);
}
References Slic3r::extra_headers, get_extra_header(), m_agent, and Slic3r::NetworkAgent::set_extra_http_header().
Referenced by on_init_network().
init_label_colours()
void Slic3r::GUI::GUI_App::init_label_colours ()
{
    bool is_dark_mode = dark_mode();
    m_color_label_modified = is_dark_mode ? wxColour("#F1754E") : wxColour("#F1754E");
    m_color_label_sys      = is_dark_mode ? wxColour("#B2B3B5") : wxColour("#363636");
#ifdef _WIN32
    m_color_label_default           = is_dark_mode ? wxColour(250, 250, 250) : m_color_label_sys; // wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT);
    m_color_highlight_label_default = is_dark_mode ? wxColour(230, 230, 230): wxSystemSettings::GetColour(/*wxSYS_COLOUR_HIGHLIGHTTEXT*/wxSYS_COLOUR_WINDOWTEXT);
    m_color_highlight_default       = is_dark_mode ? wxColour(78, 78, 78)   : wxSystemSettings::GetColour(wxSYS_COLOUR_3DLIGHT);
    m_color_hovered_btn_label       = is_dark_mode ? wxColour(255, 255, 254) : wxColour(0,0,0);
    m_color_default_btn_label       = is_dark_mode ? wxColour(255, 255, 254): wxColour(0,0,0);
    m_color_selected_btn_bg         = is_dark_mode ? wxColour(84, 84, 91)   : wxColour(206, 206, 206);
#else
    m_color_label_default = wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT);
#endif
    m_color_window_default          = is_dark_mode ? wxColour(43, 43, 43)   : wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW);
    StateColor::SetDarkMode(is_dark_mode);
}
References dark_mode(), m_color_default_btn_label, m_color_highlight_default, m_color_highlight_label_default, m_color_hovered_btn_label, m_color_label_default, m_color_label_modified, m_color_label_sys, m_color_selected_btn_bg, m_color_window_default, and StateColor::SetDarkMode().
Referenced by on_init_inner().
init_networking_callbacks()
void Slic3r::GUI::GUI_App::init_networking_callbacks () private
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": enter, m_agent=%1%")%m_agent;
    if (m_agent) {
        //set callbacks
        //m_agent->set_on_user_login_fn([this](int online_login, bool login) {
        //    GUI::wxGetApp().request_user_handle(online_login);
        //    });
        m_agent->set_on_server_connected_fn([this]() {
            if (m_is_closing) {
                return;
            }
            GUI::wxGetApp().CallAfter([this] {
                if (m_is_closing)
                    return;
                BOOST_LOG_TRIVIAL(trace) << "static: server connected";
                m_agent->set_user_selected_machine(m_agent->get_user_selected_machine());
                });
            });
        m_agent->set_on_printer_connected_fn([this](std::string dev_id) {
            if (m_is_closing) {
                return;
            }
            GUI::wxGetApp().CallAfter([this, dev_id] {
                if (m_is_closing)
                    return;
                /* request_pushing */
                MachineObject* obj = m_device_manager->get_my_machine(dev_id);
                if (obj) {
                    obj->command_request_push_all();
                    obj->command_get_version();
                }
                });
            });
        m_agent->set_get_country_code_fn([this]() {
            if (app_config)
                return app_config->get_country_code();
            return std::string();
            }
        );
        m_agent->set_on_local_connect_fn(
            [this](int state, std::string dev_id, std::string msg) {
                if (m_is_closing) {
                    return;
                }
                CallAfter([this, state, dev_id, msg] {
                    if (m_is_closing) {
                        return;
                    }
                    /* request_pushing */
                    MachineObject* obj = m_device_manager->get_my_machine(dev_id);
                    wxCommandEvent event(EVT_CONNECT_LAN_MODE_PRINT);
                    if (obj) {
                        if (obj->is_lan_mode_printer()) {
                            if (state == ConnectStatus::ConnectStatusOk) {
                                obj->command_request_push_all();
                                obj->command_get_version();
                                event.SetInt(1);
                                event.SetString(obj->dev_id);
                            } else if (state == ConnectStatus::ConnectStatusFailed) {
                                obj->set_access_code("");
                                obj->set_user_access_code("");
                                m_device_manager->set_selected_machine("", true);
                                wxString text;
                                if (msg == "5") {
                                    text = wxString::Format(_L("Incorrect password"));
                                    wxGetApp().show_dialog(text);
                                } else {
                                    text = wxString::Format(_L("Connect %s failed! [SN:%s, code=%s]"), from_u8(obj->dev_name), obj->dev_id, msg);
                                    wxGetApp().show_dialog(text);
                                }
                                event.SetInt(0);
                            } else if (state == ConnectStatus::ConnectStatusLost) {
                                m_device_manager->set_selected_machine("", true);
                                event.SetInt(0);
                                BOOST_LOG_TRIVIAL(info) << "set_on_local_connect_fn: state = lost";
                            } else {
                                event.SetInt(0);
                                BOOST_LOG_TRIVIAL(info) << "set_on_local_connect_fn: state = " << state;
                            }
                            obj->set_lan_mode_connection_state(false);
                        }
                    }
                    event.SetEventObject(this);
                    wxPostEvent(this, event);
                });
            }
        );
        auto message_arrive_fn = [this](std::string dev_id, std::string msg) {
            if (m_is_closing) {
                return;
            }
            CallAfter([this, dev_id, msg] {
                if (m_is_closing)
                    return;
                MachineObject* obj = this->m_device_manager->get_user_machine(dev_id);
                if (obj) {
                    obj->is_ams_need_update = false;
                    obj->parse_json(msg);
                    auto sel = this->m_device_manager->get_selected_machine();
                    if ((sel == obj || sel == nullptr) && obj->is_ams_need_update) {
                        GUI::wxGetApp().sidebar().load_ams_list(obj->dev_id, obj->amsList);
                    }
                }
            });
        };
        m_agent->set_on_message_fn(message_arrive_fn);
        auto lan_message_arrive_fn = [this](std::string dev_id, std::string msg) {
            if (m_is_closing) {
                return;
            }
            CallAfter([this, dev_id, msg] {
                if (m_is_closing)
                    return;
                MachineObject* obj = m_device_manager->get_my_machine(dev_id);
                if (!obj || !obj->is_lan_mode_printer()) {
                    obj = m_device_manager->get_local_machine(dev_id);
                }
                if (obj) {
                    obj->parse_json(msg);
                    if (this->m_device_manager->get_selected_machine() == obj && obj->is_ams_need_update) {
                        GUI::wxGetApp().sidebar().load_ams_list(obj->dev_id, obj->amsList);
                    }
                }
                });
        };
        m_agent->set_on_local_message_fn(lan_message_arrive_fn);
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": exit, m_agent=%1%")%m_agent;
}
References _L, app_config, Slic3r::MachineObject::command_get_version(), Slic3r::MachineObject::command_request_push_all(), Slic3r::MachineObject::dev_id, Slic3r::MachineObject::dev_name, Slic3r::GUI::from_u8(), Slic3r::AppConfig::get_country_code(), Slic3r::DeviceManager::get_my_machine(), Slic3r::DeviceManager::get_selected_machine(), Slic3r::DeviceManager::get_user_machine(), Slic3r::NetworkAgent::get_user_selected_machine(), Slic3r::MachineObject::is_ams_need_update, Slic3r::MachineObject::is_lan_mode_printer(), m_agent, m_device_manager, m_is_closing, Slic3r::MachineObject::parse_json(), Slic3r::MachineObject::set_access_code(), Slic3r::NetworkAgent::set_get_country_code_fn(), Slic3r::MachineObject::set_lan_mode_connection_state(), Slic3r::NetworkAgent::set_on_local_connect_fn(), Slic3r::NetworkAgent::set_on_local_message_fn(), Slic3r::NetworkAgent::set_on_message_fn(), Slic3r::NetworkAgent::set_on_printer_connected_fn(), Slic3r::NetworkAgent::set_on_server_connected_fn(), Slic3r::DeviceManager::set_selected_machine(), Slic3r::MachineObject::set_user_access_code(), Slic3r::NetworkAgent::set_user_selected_machine(), and Slic3r::trace().
Referenced by on_init_network(), and restart_networking().
init_opengl()
bool Slic3r::GUI::GUI_App::init_opengl ()
{
#ifdef __linux__
    bool status = m_opengl_mgr.init_gl();
    m_opengl_initialized = true;
    return status;
#else
    return m_opengl_mgr.init_gl();
#endif
}
References Slic3r::GUI::OpenGLManager::init_gl(), and m_opengl_mgr.
initialized()
bool Slic3r::GUI::GUI_App::initialized () const inline
{ return m_initialized; }
References m_initialized.
Referenced by post_init().
install_plugin()
int Slic3r::GUI::GUI_App::install_plugin (std::string name, std::string package_name, InstallProgressFn pro_fn = nullptr, WasCancelledFn cancel_fn = nullptr)
{
    bool cancel = false;
    std::string target_file_path = (fs::temp_directory_path() / package_name).string();
    BOOST_LOG_TRIVIAL(info) << "[install_plugin] enter";
    // get plugin folder
    std::string data_dir_str = data_dir();
    boost::filesystem::path data_dir_path(data_dir_str);
    auto plugin_folder = data_dir_path / name;
    //auto plugin_folder = boost::filesystem::path(wxStandardPaths::Get().GetUserDataDir().ToUTF8().data()) / "plugins";
    auto backup_folder = plugin_folder/"backup";
    if (!boost::filesystem::exists(plugin_folder)) {
        BOOST_LOG_TRIVIAL(info) << "[install_plugin] will create directory "<<plugin_folder.string();
        boost::filesystem::create_directory(plugin_folder);
    }
    if (!boost::filesystem::exists(backup_folder)) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", will create directory %1%")%backup_folder.string();
        boost::filesystem::create_directory(backup_folder);
    }
    if (m_networking_cancel_update) {
        BOOST_LOG_TRIVIAL(info) << boost::format("[install_plugin]: %1%, cancelled by user")%__LINE__;
        return -1;
    }
    if (pro_fn) {
        pro_fn(InstallStatusNormal, 50, cancel);
    }
    // unzip
    mz_zip_archive archive;
    mz_zip_zero_struct(&archive);
    if (!open_zip_reader(&archive, target_file_path)) {
        BOOST_LOG_TRIVIAL(error) << boost::format("[install_plugin]: %1%, open zip file failed")%__LINE__;
        if (pro_fn) pro_fn(InstallStatusDownloadFailed, 0, cancel);
        return InstallStatusUnzipFailed;
    }
    mz_uint num_entries = mz_zip_reader_get_num_files(&archive);
    mz_zip_archive_file_stat stat;
    BOOST_LOG_TRIVIAL(error) << boost::format("[install_plugin]: %1%, got %2% files")%__LINE__ %num_entries;
    for (mz_uint i = 0; i < num_entries; i++) {
        if (m_networking_cancel_update || cancel) {
            BOOST_LOG_TRIVIAL(info) << boost::format("[install_plugin]: %1%, cancelled by user")%__LINE__;
            return -1;
        }
        if (mz_zip_reader_file_stat(&archive, i, &stat)) {
            if (stat.m_uncomp_size > 0) {
                std::string dest_file;
                if (stat.m_is_utf8) {
                    dest_file = stat.m_filename;
                }
                else {
                    std::string extra(1024, 0);
                    size_t n = mz_zip_reader_get_extra(&archive, stat.m_file_index, extra.data(), extra.size());
                    dest_file = decode(extra.substr(0, n), stat.m_filename);
                }
                auto dest_file_path = boost::filesystem::path(dest_file);
                dest_file = dest_file_path.filename().string();
                auto dest_path = boost::filesystem::path(plugin_folder.string() + "/" + dest_file);
                std::string dest_zip_file = encode_path(dest_path.string().c_str());
                try {
                    if (fs::exists(dest_path))
                        fs::remove(dest_path);
                    mz_bool res = mz_zip_reader_extract_to_file(&archive, stat.m_file_index, dest_zip_file.c_str(), 0);
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", extract  %1% from plugin zip %2%\n") % dest_file % stat.m_filename;
                    if (res == 0) {
                        mz_zip_error zip_error = mz_zip_get_last_error(&archive);
                        BOOST_LOG_TRIVIAL(error) << "[install_plugin]Archive read error:" << mz_zip_get_error_string(zip_error) << std::endl;
                        close_zip_reader(&archive);
                        if (pro_fn) {
                            pro_fn(InstallStatusUnzipFailed, 0, cancel);
                        }
                        return InstallStatusUnzipFailed;
                    }
                    else {
                        if (pro_fn) {
                            pro_fn(InstallStatusNormal, 50 + i/num_entries, cancel);
                        }
                        try {
                            auto backup_path = boost::filesystem::path(backup_folder.string() + "/" + dest_file);
                            if (fs::exists(backup_path))
                                fs::remove(backup_path);
                            std::string error_message;
                            CopyFileResult cfr = copy_file(dest_path.string(), backup_path.string(), error_message, false);
                            if (cfr != CopyFileResult::SUCCESS) {
                                BOOST_LOG_TRIVIAL(error) << "Copying to backup failed(" << cfr << "): " << error_message;
                            }
                        }
                        catch (const std::exception& e)
{
                            BOOST_LOG_TRIVIAL(error) << "Copying to backup failed: " << e.what();
                            //continue
                        }
                    }
                }
                catch (const std::exception& e)
                {
                    // ensure the zip archive is closed and rethrow the exception
                    close_zip_reader(&archive);
                    BOOST_LOG_TRIVIAL(error) << "[install_plugin]Archive read exception:"<<e.what();
                    if (pro_fn) {
                        pro_fn(InstallStatusUnzipFailed, 0, cancel);
                    }
                    return InstallStatusUnzipFailed;
                }
            }
        }
        else {
            BOOST_LOG_TRIVIAL(error) << boost::format("[install_plugin]: %1%, mz_zip_reader_file_stat for file %2% failed")%__LINE__%i;
        }
    }
    close_zip_reader(&archive);
    if (pro_fn)
        pro_fn(InstallStatusInstallCompleted, 100, cancel);
    if (name == "plugins")
        app_config->set_str("app", "installed_networking", "1");
    BOOST_LOG_TRIVIAL(info) << "[install_plugin] success";
    return 0;
}
References app_config, Slic3r::close_zip_reader(), Slic3r::copy_file(), Slic3r::data_dir(), Slic3r::GUI::decode(), Slic3r::encode_path(), error, Slic3r::GUI::InstallStatusDownloadFailed, Slic3r::GUI::InstallStatusInstallCompleted, Slic3r::GUI::InstallStatusNormal, Slic3r::GUI::InstallStatusUnzipFailed, mz_zip_archive_file_stat::m_file_index, mz_zip_archive_file_stat::m_filename, mz_zip_archive_file_stat::m_is_utf8, m_networking_cancel_update, mz_zip_archive_file_stat::m_uncomp_size, mz_zip_get_error_string(), mz_zip_get_last_error(), mz_zip_reader_extract_to_file(), mz_zip_reader_file_stat(), mz_zip_reader_get_extra(), mz_zip_reader_get_num_files(), mz_zip_zero_struct(), n, Slic3r::open_zip_reader(), Slic3r::AppConfig::set_str(), and Slic3r::SUCCESS.
is_adding_script_handler()
bool Slic3r::GUI::GUI_App::is_adding_script_handler () inline
{ return m_adding_script_handler; }
References m_adding_script_handler.
is_compatibility_version()
bool Slic3r::GUI::GUI_App::is_compatibility_version ()
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": m_networking_compatible=%1%")%m_networking_compatible;
    return m_networking_compatible;
}
References m_networking_compatible.
is_editor()
bool Slic3r::GUI::GUI_App::is_editor () const inline
{ return m_app_mode == EAppMode::Editor; }
References Editor, and m_app_mode.
Referenced by logo_name(), on_init_inner(), open_preferences(), post_init(), and recreate_GUI().
is_gcode_viewer()
bool Slic3r::GUI::GUI_App::is_gcode_viewer () const inline
{ return m_app_mode == EAppMode::GCodeViewer; }
References GCodeViewer, and m_app_mode.
Referenced by post_init().
is_gl_version_greater_or_equal_to()
bool Slic3r::GUI::GUI_App::is_gl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const inline
{ return m_opengl_mgr.get_gl_info().is_version_greater_or_equal_to(major, minor); }
References Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::is_version_greater_or_equal_to(), and m_opengl_mgr.
is_glsl_version_greater_or_equal_to()
bool Slic3r::GUI::GUI_App::is_glsl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const inline
{ return m_opengl_mgr.get_gl_info().is_glsl_version_greater_or_equal_to(major, minor); }
References Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::OpenGLManager::GLInfo::is_glsl_version_greater_or_equal_to(), and m_opengl_mgr.
is_localized()
bool Slic3r::GUI::GUI_App::is_localized () const inline
{ return m_wxLocale->GetLocale() != "English"; }
References m_wxLocale.
is_recreating_gui()
bool Slic3r::GUI::GUI_App::is_recreating_gui () const inline
{ return m_is_recreating_gui; }
References m_is_recreating_gui.
is_studio_active()
bool Slic3r::GUI::GUI_App::is_studio_active ()
{
    auto curr_time = std::chrono::system_clock::now();
    auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(curr_time - last_active_point);
    if (diff.count() < STUDIO_INACTIVE_TIMEOUT) {
        return true;
    }
    return false;
}
References Slic3r::diff(), last_active_point, and STUDIO_INACTIVE_TIMEOUT.
is_user_login()
bool Slic3r::GUI::GUI_App::is_user_login ()
{
    if (m_agent) {
        return m_agent->is_user_login();
    }
    return false;
}
References Slic3r::NetworkAgent::is_user_login(), and m_agent.
Referenced by open_mall_page_dialog(), and post_init().
keyboard_shortcuts()
void Slic3r::GUI::GUI_App::keyboard_shortcuts ()
{
    KBShortcutsDialog dlg;
    dlg.ShowModal();
}
References Slic3r::GUI::DPIAware< P >::ShowModal().
link_font()
const wxFont & Slic3r::GUI::GUI_App::link_font () inline
{ return m_link_font; }
References m_link_font.
load_current_presets()
void Slic3r::GUI::GUI_App::load_current_presets (bool active_preset_combox = false, bool check_printer_presets = true)
{
    // check printer_presets for the containing information about "Print Host upload"
    // and create physical printer from it, if any exists
    if (check_printer_presets_)
        check_printer_presets();
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
  this->plater()->set_printer_technology(printer_technology);
    for (Tab *tab : tabs_list)
    if (tab->supports_printer_technology(printer_technology)) {
      if (tab->type() == Preset::TYPE_PRINTER) {
        static_cast<TabPrinter*>(tab)->update_pages();
        // Mark the plater to update print bed by tab->load_current_preset() from Plater::on_config_change().
        this->plater()->force_print_bed_update();
      }
      tab->load_current_preset();
      //BBS: add preset combox re-active logic
      if (active_preset_combox)
        tab->reactive_preset_combo_box();
    }
    // BBS: model config
    for (Tab *tab : model_tabs_list)
    if (tab->supports_printer_technology(printer_technology)) {
            tab->rebuild_page_tree();
        }
}
References check_printer_presets(), Slic3r::GUI::Plater::force_print_bed_update(), Slic3r::PresetCollection::get_edited_preset(), model_tabs_list, plater(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::GUI::Plater::set_printer_technology(), tabs_list, and Slic3r::Preset::TYPE_PRINTER.
Referenced by apply_keeped_preset_modifications(), check_and_keep_current_preset_changes(), check_and_save_current_preset_changes(), recreate_GUI(), run_wizard(), ShowOnlyFilament(), and ShowUserGuide().
load_gcode()
void Slic3r::GUI::GUI_App::load_gcode (wxWindow * parent, wxString & input_file) const
{
    input_file.Clear();
    wxFileDialog dialog(parent ? parent : GetTopWindow(),
        _L("Choose one file (gcode/3mf):"),
        app_config->get_last_dir(), "",
        file_wildcards(FT_GCODE), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() == wxID_OK)
        input_file = dialog.GetPath();
}
References _L, app_config, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_GCODE, and Slic3r::AppConfig::get_last_dir().
load_language()
bool Slic3r::GUI::GUI_App::load_language (wxString language, bool initial)
{
    if (initial) {
      // There is a static list of lookup path prefixes in wxWidgets. Add ours.
      wxFileTranslationsLoader::AddCatalogLookupPathPrefix(from_u8(localization_dir()));
      // Get the active language from PrusaSlicer.ini, or empty string if the key does not exist.
        language = app_config->get("language");
        if (! language.empty())
          BOOST_LOG_TRIVIAL(trace) << boost::format("language provided by OrcaSlicer.conf: %1%") % language;
        else {
            // Get the system language.
            const wxLanguage lang_system = wxLanguage(wxLocale::GetSystemLanguage());
            if (lang_system != wxLANGUAGE_UNKNOWN) {
                m_language_info_system = wxLocale::GetLanguageInfo(lang_system);
                BOOST_LOG_TRIVIAL(trace) << boost::format("System language detected (user locales and such): %1%") % m_language_info_system->CanonicalName.ToUTF8().data();
                // BBS set language to app config
                app_config->set("language", m_language_info_system->CanonicalName.ToUTF8().data());
            } else {
                {
                    std::map<wxString, wxString> language_descptions = {
                        {"zh_CN", wxString::FromUTF8("\xE4\xB8\xAD\xE6\x96\x87\x28\xE7\xAE\x80\xE4\xBD\x93\x29")},
                        {"zh_TW", wxString::FromUTF8("\xE4\xB8\xAD\xE6\x96\x87\x28\xE7\xB9\x81\xE9\xAB\x94\x29")},
                        {"de", wxString::FromUTF8("Deutsch")},
                        {"cs", wxString::FromUTF8("Czech")},
                        {"nl", wxString::FromUTF8("Nederlands")},
                        {"sv", wxString::FromUTF8("\x53\x76\x65\x6e\x73\x6b\x61")}, //Svenska
                        {"en", wxString::FromUTF8("English")},
                        {"es", wxString::FromUTF8("\x45\x73\x70\x61\xC3\xB1\x6F\x6C")},
                        {"fr", wxString::FromUTF8("\x46\x72\x61\x6E\xC3\xA7\x61\x69\x73")},
                        {"it", wxString::FromUTF8("\x49\x74\x61\x6C\x69\x61\x6E\x6F")},
                        {"ru", wxString::FromUTF8("\xD1\x80\xD1\x83\xD1\x81\xD1\x81\xD0\xBA\xD0\xB8\xD0\xB9")},
                        {"hu", wxString::FromUTF8("Magyar")},
                        {"ja", wxString::FromUTF8("\xE6\x97\xA5\xE6\x9C\xAC\xE8\xAA\x9E")},
                        {"ko", wxString::FromUTF8("\xED\x95\x9C\xEA\xB5\xAD\xEC\x96\xB4")}
                    };
                    for (auto l : language_descptions) {
                        const wxLanguageInfo *langinfo = wxLocale::FindLanguageInfo(l.first);
                        if (langinfo) const_cast<wxLanguageInfo *>(langinfo)->Description = l.second;
                    }
                }
                {
                    // Allocating a temporary locale will switch the default wxTranslations to its internal wxTranslations instance.
                    wxLocale temp_locale;
                    // Set the current translation's language to default, otherwise GetBestTranslation() may not work (see the wxWidgets source code).
                    wxTranslations::Get()->SetLanguage(wxLANGUAGE_DEFAULT);
                    // Let the wxFileTranslationsLoader enumerate all translation dictionaries for PrusaSlicer
                    // and try to match them with the system specific "preferred languages".
                    // There seems to be a support for that on Windows and OSX, while on Linuxes the code just returns wxLocale::GetSystemLanguage().
                    // The last parameter gets added to the list of detected dictionaries. This is a workaround
                    // for not having the English dictionary. Let's hope wxWidgets of various versions process this call the same way.
                    wxString best_language = wxTranslations::Get()->GetBestTranslation(SLIC3R_APP_KEY, wxLANGUAGE_ENGLISH);
                    if (!best_language.IsEmpty()) {
                        m_language_info_best = wxLocale::FindLanguageInfo(best_language);
                        BOOST_LOG_TRIVIAL(trace) << boost::format("Best translation language detected (may be different from user locales): %1%") %
                                                        m_language_info_best->CanonicalName.ToUTF8().data();
                        app_config->set("language", m_language_info_best->CanonicalName.ToUTF8().data());
                    }
#ifdef __linux__
                    wxString lc_all;
                    if (wxGetEnv("LC_ALL", &lc_all) && !lc_all.IsEmpty()) {
                        // Best language returned by wxWidgets on Linux apparently does not respect LC_ALL.
                        // Disregard the "best" suggestion in case LC_ALL is provided.
                        m_language_info_best = nullptr;
                    }
#endif
                }
            }
        }
    }
  const wxLanguageInfo *language_info = language.empty() ? nullptr : wxLocale::FindLanguageInfo(language);
  if (! language.empty() && (language_info == nullptr || language_info->CanonicalName.empty())) {
    // Fix for wxWidgets issue, where the FindLanguageInfo() returns locales with undefined ANSII code (wxLANGUAGE_KONKANI or wxLANGUAGE_MANIPURI).
    language_info = nullptr;
      BOOST_LOG_TRIVIAL(error) << boost::format("Language code \"%1%\" is not supported") % language.ToUTF8().data();
  }
  if (language_info != nullptr && language_info->LayoutDirection == wxLayout_RightToLeft) {
      BOOST_LOG_TRIVIAL(trace) << boost::format("The following language code requires right to left layout, which is not supported by OrcaSlicer: %1%") % language_info->CanonicalName.ToUTF8().data();
    language_info = nullptr;
  }
    if (language_info == nullptr) {
        // PrusaSlicer does not support the Right to Left languages yet.
        if (m_language_info_system != nullptr && m_language_info_system->LayoutDirection != wxLayout_RightToLeft)
            language_info = m_language_info_system;
        if (m_language_info_best != nullptr && m_language_info_best->LayoutDirection != wxLayout_RightToLeft)
          language_info = m_language_info_best;
      if (language_info == nullptr)
      language_info = wxLocale::GetLanguageInfo(wxLANGUAGE_ENGLISH_US);
    }
  BOOST_LOG_TRIVIAL(trace) << boost::format("Switching wxLocales to %1%") % language_info->CanonicalName.ToUTF8().data();
    // Select language for locales. This language may be different from the language of the dictionary.
    //if (language_info == m_language_info_best || language_info == m_language_info_system) {
    //    // The current language matches user's default profile exactly. That's great.
    //} else if (m_language_info_best != nullptr && language_info->CanonicalName.BeforeFirst('_') == m_language_info_best->CanonicalName.BeforeFirst('_')) {
    //    // Use whatever the operating system recommends, if it the language code of the dictionary matches the recommended language.
    //    // This allows a Swiss guy to use a German dictionary without forcing him to German locales.
    //    language_info = m_language_info_best;
    //} else if (m_language_info_system != nullptr && language_info->CanonicalName.BeforeFirst('_') == m_language_info_system->CanonicalName.BeforeFirst('_'))
    //    language_info = m_language_info_system;
    // Alternate language code.
    wxLanguage language_dict = wxLanguage(language_info->Language);
    if (language_info->CanonicalName.BeforeFirst('_') == "sk") {
      // Slovaks understand Czech well. Give them the Czech translation.
      language_dict = wxLANGUAGE_CZECH;
    BOOST_LOG_TRIVIAL(trace) << "Using Czech dictionaries for Slovak language";
    }
#ifdef __linux__
    // If we can't find this locale , try to use different one for the language
    // instead of just reporting that it is impossible to switch.
    if (! wxLocale::IsAvailable(language_info->Language)) {
        std::string original_lang = into_u8(language_info->CanonicalName);
        if (nullptr == m_language_info_system) {
            m_language_info_system = wxLocale::GetLanguageInfo(wxLANGUAGE_DEFAULT);
        }
        language_info = linux_get_existing_locale_language(language_info, m_language_info_system);
        BOOST_LOG_TRIVIAL(trace) << boost::format("Can't switch language to %1% (missing locales). Using %2% instead.")
                                    % original_lang % language_info->CanonicalName.ToUTF8().data();
    }
#endif
    if (! wxLocale::IsAvailable(language_info->Language)&&initial) {
        language_info = wxLocale::GetLanguageInfo(wxLANGUAGE_ENGLISH_UK);
        app_config->set("language", language_info->CanonicalName.ToUTF8().data());
    }
    else if (initial) {
        // bbs supported languages
        //TODO: use a global one with Preference
        wxLanguage supported_languages[]{
            wxLANGUAGE_ENGLISH,
            wxLANGUAGE_CHINESE_SIMPLIFIED,
            wxLANGUAGE_GERMAN,
            wxLANGUAGE_FRENCH,
            wxLANGUAGE_SPANISH,
            wxLANGUAGE_SWEDISH,
            wxLANGUAGE_DUTCH,
            wxLANGUAGE_HUNGARIAN,
            wxLANGUAGE_JAPANESE,
            wxLANGUAGE_ITALIAN,
            wxLANGUAGE_KOREAN,
            wxLANGUAGE_RUSSIAN,
            wxLANGUAGE_UKRAINIAN
        };
        std::string cur_language = app_config->get("language");
        if (cur_language != "") {
            //cleanup the language wrongly set before
            const wxLanguageInfo *langinfo = nullptr;
            bool embedded_language = false;
            int language_num = sizeof(supported_languages) / sizeof(supported_languages[0]);
            for (auto index = 0; index < language_num; index++) {
                langinfo = wxLocale::GetLanguageInfo(supported_languages[index]);
                std::string temp_lan = langinfo->CanonicalName.ToUTF8().data();
                if (cur_language == temp_lan) {
                    embedded_language = true;
                    break;
                }
            }
            if (!embedded_language)
                app_config->erase("app", "language");
        }
    }
    if (! wxLocale::IsAvailable(language_info->Language)) {
      // Loading the language dictionary failed.
      wxString message = "Switching Orca Slicer to language " + language_info->CanonicalName + " failed.";
#if !defined(_WIN32) && !defined(__APPLE__)
        // likely some linux system
        message += "\nYou may need to reconfigure the missing locales, likely by running the \"locale-gen\" and \"dpkg-reconfigure locales\" commands.\n";
#endif
        if (initial)
          message + "\n\nApplication will close.";
        wxMessageBox(message, "Orca Slicer - Switching language failed", wxOK | wxICON_ERROR);
        if (initial)
      std::exit(EXIT_FAILURE);
    else
      return false;
    }
    // Release the old locales, create new locales.
    //FIXME wxWidgets cause havoc if the current locale is deleted. We just forget it causing memory leaks for now.
    m_wxLocale.release();
    m_wxLocale = Slic3r::make_unique<wxLocale>();
    m_wxLocale->Init(language_info->Language);
    // Override language at the active wxTranslations class (which is stored in the active m_wxLocale)
    // to load possibly different dictionary, for example, load Czech dictionary for Slovak language.
    wxTranslations::Get()->SetLanguage(language_dict);
    m_wxLocale->AddCatalog(SLIC3R_APP_KEY);
    m_imgui->set_language(into_u8(language_info->CanonicalName));
    //FIXME This is a temporary workaround, the correct solution is to switch to "C" locale during file import / export only.
    //wxSetlocale(LC_NUMERIC, "C");
    Preset::update_suffix_modified((_L("*") + " ").ToUTF8().data());
  return true;
}
References _L, app_config, Slic3r::AppConfig::erase(), error, Slic3r::GUI::from_u8(), Slic3r::AppConfig::get(), Slic3r::GUI::into_u8(), Slic3r::localization_dir(), m_imgui, m_language_info_best, m_language_info_system, m_wxLocale, Slic3r::AppConfig::set(), Slic3r::trace(), and Slic3r::Preset::update_suffix_modified().
Referenced by on_init_inner(), and select_language().
load_project()
void Slic3r::GUI::GUI_App::load_project (wxWindow * parent, wxString & input_file) const
{
    input_file.Clear();
    wxFileDialog dialog(parent ? parent : GetTopWindow(),
        _L("Choose one file (3mf):"),
        app_config->get_last_dir(), "",
        file_wildcards(FT_PROJECT), wxFD_OPEN | wxFD_FILE_MUST_EXIST);
    if (dialog.ShowModal() == wxID_OK)
        input_file = dialog.GetPath();
}
References _L, app_config, Slic3r::GUI::file_wildcards(), Slic3r::GUI::FT_PROJECT, and Slic3r::AppConfig::get_last_dir().
load_url()
void Slic3r::GUI::GUI_App::load_url (wxString url)
{
    if (mainframe)
        return mainframe->load_url(url);
}
References Slic3r::GUI::MainFrame::load_url(), and mainframe.
logo_name()
std::string Slic3r::GUI::GUI_App::logo_name () const inline
{ return is_editor() ? "OrcaSlicer" : "OrcaSlicer-gcodeviewer"; }
References is_editor().
may_switch_to_SLA_preset()
bool Slic3r::GUI::GUI_App::may_switch_to_SLA_preset (const wxString & caption)
{
    if (model_has_multi_part_objects(model())) {
        // BBS: remove SLA related message
        return false;
    }
    return true;
}
References model(), and Slic3r::model_has_multi_part_objects().
model()
Model & Slic3r::GUI::GUI_App::model ()
{
    return plater_->model();
}
References Slic3r::GUI::Plater::model(), and plater_.
Referenced by may_switch_to_SLA_preset().
no_new_version()
void Slic3r::GUI::GUI_App::no_new_version ()
{
    wxCommandEvent* evt = new wxCommandEvent(EVT_SHOW_NO_NEW_VERSION);
    GUI::wxGetApp().QueueEvent(evt);
}
Referenced by check_new_version(), and check_update().
normal_font()
const wxFont & Slic3r::GUI::GUI_App::normal_font () inline
{ return m_normal_font; }
References m_normal_font.
notification_manager()
NotificationManager * Slic3r::GUI::GUI_App::notification_manager ()
{
    if (plater_)
        return plater_->get_notification_manager();
    return nullptr;
}
References Slic3r::GUI::Plater::get_notification_manager(), and plater_.
obj_layers()
ObjectLayers * Slic3r::GUI::GUI_App::obj_layers ()
{
    return sidebar().obj_layers();
}
References Slic3r::GUI::Sidebar::obj_layers(), and sidebar().
obj_list()
ObjectList * Slic3r::GUI::GUI_App::obj_list ()
{
    return sidebar().obj_list();
}
References Slic3r::GUI::Sidebar::obj_list(), and sidebar().
Referenced by recreate_GUI().
obj_settings()
ObjectSettings * Slic3r::GUI::GUI_App::obj_settings ()
{
    return sidebar().obj_settings();
}
References Slic3r::GUI::Sidebar::obj_settings(), and sidebar().
on_check_privacy_update()
void Slic3r::GUI::GUI_App::on_check_privacy_update (wxCommandEvent & evt)
{
    int online_login = evt.GetInt();
    bool result = check_privacy_update();
    if (result)
        on_show_check_privacy_dlg(online_login);
    else
        request_user_handle(online_login);
}
References check_privacy_update(), on_show_check_privacy_dlg(), and request_user_handle().
on_http_error()
void Slic3r::GUI::GUI_App::on_http_error (wxCommandEvent & evt)
{
    int status = evt.GetInt();
    int code = 0;
    std::string error;
    wxString result;
    if (status >= 400 && status < 500) {
        try {
        json j = json::parse(evt.GetString());
        if (j.contains("code")) {
            if (!j["code"].is_null())
                code = j["code"].get<int>();
        }
        if (j.contains("error"))
            if (!j["error"].is_null())
                error = j["error"].get<std::string>();
        }
        catch (...) {}
    }
    // Version limit
    if (code == HttpErrorVersionLimited) {
        MessageDialog msg_dlg(nullptr, _L("The version of Orca Slicer is too low and needs to be updated to the latest version before it can be used normally"), "", wxAPPLY | wxOK);
        if (msg_dlg.ShowModal() == wxOK) {
            return;
        }
    }
    // request login
    if (status == 401) {
        if (m_agent) {
            if (m_agent->is_user_login()) {
                this->request_user_logout();
                MessageDialog msg_dlg(nullptr, _L("Login information expired. Please login again."), "", wxAPPLY | wxOK);
                if (msg_dlg.ShowModal() == wxOK) {
                    return;
                }
            }
        }
        return;
    }
}
References _L, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), error, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::HttpErrorVersionLimited, Slic3r::NetworkAgent::is_user_login(), m_agent, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), request_user_logout(), and Slic3r::GUI::DPIAware< P >::ShowModal().
on_init_inner()
bool Slic3r::GUI::GUI_App::on_init_inner () private
{
    // Set initialization of image handlers before any UI actions - See GH issue #7469
    wxInitAllImageHandlers();
#ifdef NDEBUG
    wxImage::SetDefaultLoadFlags(0); // ignore waring in release build
#endif
#if defined(_WIN32) && ! defined(_WIN64)
    // BBS: remove 32bit build prompt
    // Win32 32bit build.
#endif // _WIN64
    // Forcing back menu icons under gtk2 and gtk3. Solution is based on:
    // https://docs.gtk.org/gtk3/class.Settings.html
    // see also https://docs.wxwidgets.org/3.0/classwx_menu_item.html#a2b5d6bcb820b992b1e4709facbf6d4fb
    // TODO: Find workaround for GTK4
#if defined(__WXGTK20__) || defined(__WXGTK3__)
    g_object_set (gtk_settings_get_default (), "gtk-menu-images", TRUE, NULL);
#endif
#ifdef WIN32
    //BBS set crash log folder
    CBaseException::set_log_folder(data_dir());
#endif
    wxGetApp().Bind(wxEVT_QUERY_END_SESSION, [this](auto & e) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< "received wxEVT_QUERY_END_SESSION";
        if (mainframe) {
            wxCloseEvent e2(wxEVT_CLOSE_WINDOW);
            e2.SetCanVeto(true);
            mainframe->GetEventHandler()->ProcessEvent(e2);
            if (e2.GetVeto()) {
                e.Veto();
                return;
            }
        }
        for (auto d : dialogStack)
            d->EndModal(wxID_ABORT);
    });
    std::map<std::string, std::string> extra_headers = get_extra_header();
    Slic3r::Http::set_extra_headers(extra_headers);
    // Verify resources path
    const wxString resources_dir = from_u8(Slic3r::resources_dir());
    wxCHECK_MSG(wxDirExists(resources_dir), false,
        wxString::Format("Resources path does not exist or is not a directory: %s", resources_dir));
#ifdef __linux__
    if (! check_old_linux_datadir(GetAppName())) {
        std::cerr << "Quitting, user chose to move their data to new location." << std::endl;
        return false;
    }
#endif
    // Enable this to get the default Win32 COMCTRL32 behavior of static boxes.
//    wxSystemOptions::SetOption("msw.staticbox.optimized-paint", 0);
    // Enable this to disable Windows Vista themes for all wxNotebooks. The themes seem to lead to terrible
    // performance when working on high resolution multi-display setups.
//    wxSystemOptions::SetOption("msw.notebook.themed-background", 0);
//     Slic3r::debugf "wxWidgets version %s, Wx version %s\n", wxVERSION_STRING, wxVERSION;
    if (is_editor()) {
        std::string msg = Slic3r::Http::tls_global_init();
        std::string ssl_cert_store = app_config->get("tls_accepted_cert_store_location");
        bool ssl_accept = app_config->get("tls_cert_store_accepted") == "yes" && ssl_cert_store == Slic3r::Http::tls_system_cert_store();
        if (!msg.empty() && !ssl_accept) {
            RichMessageDialog
                dlg(nullptr,
                    wxString::Format(_L("%s\nDo you want to continue?"), msg),
                    "OrcaSlicer", wxICON_QUESTION | wxYES_NO);
            dlg.ShowCheckBox(_L("Remember my choice"));
            if (dlg.ShowModal() != wxID_YES) return false;
            app_config->set("tls_cert_store_accepted",
                dlg.IsCheckBoxChecked() ? "yes" : "no");
            app_config->set("tls_accepted_cert_store_location",
                dlg.IsCheckBoxChecked() ? Slic3r::Http::tls_system_cert_store() : "");
        }
    }
    // !!! Initialization of UI settings as a language, application color mode, fonts... have to be done before first UI action.
    // Like here, before the show InfoDialog in check_older_app_config()
    // If load_language() fails, the application closes.
    load_language(wxString(), true);
#ifdef _MSW_DARK_MODE
#ifdef __APPLE__
    wxSystemAppearance app = wxSystemSettings::GetAppearance();
    GUI::wxGetApp().app_config->set("dark_color_mode", app.IsDark() ? "1" : "0");
    GUI::wxGetApp().app_config->save();
#endif // __APPLE__
    bool init_dark_color_mode = dark_mode();
    bool init_sys_menu_enabled = app_config->get("sys_menu_enabled") == "1";
#ifdef __WINDOWS__
     NppDarkMode::InitDarkMode(init_dark_color_mode, init_sys_menu_enabled);
#endif // __WINDOWS__
#endif
    // initialize label colors and fonts
    init_label_colours();
    init_fonts();
    wxGetApp().Update_dark_mode_flag();
#ifdef _MSW_DARK_MODE
    // app_config can be updated in check_older_app_config(), so check if dark_color_mode and sys_menu_enabled was changed
    if (bool new_dark_color_mode = dark_mode();
        init_dark_color_mode != new_dark_color_mode) {
#ifdef __WINDOWS__
        NppDarkMode::SetDarkMode(new_dark_color_mode);
#endif // __WINDOWS__
        init_label_colours();
        //update_label_colours_from_appconfig();
    }
    if (bool new_sys_menu_enabled = app_config->get("sys_menu_enabled") == "1";
        init_sys_menu_enabled != new_sys_menu_enabled)
#ifdef __WINDOWS__
        NppDarkMode::SetSystemMenuForApp(new_sys_menu_enabled);
#endif
#endif
    if (m_last_config_version) {
        int last_major = m_last_config_version->maj();
        int last_minor = m_last_config_version->min();
        int last_patch = m_last_config_version->patch()/100;
        std::string studio_ver = SLIC3R_VERSION;
        int cur_major = atoi(studio_ver.substr(0,2).c_str());
        int cur_minor = atoi(studio_ver.substr(3,2).c_str());
        int cur_patch = atoi(studio_ver.substr(6,2).c_str());
        BOOST_LOG_TRIVIAL(info) << boost::format("last app version {%1%.%2%.%3%}, current version {%4%.%5%.%6%}")
            %last_major%last_minor%last_patch%cur_major%cur_minor%cur_patch;
        if ((last_major != cur_major)
            ||(last_minor != cur_minor)
            ||(last_patch != cur_patch)) {
            remove_old_networking_plugins();
        }
    }
    if(app_config->get("version") != SLIC3R_VERSION) {
        app_config->set("version", SLIC3R_VERSION);
    }
    BBLSplashScreen * scrn = nullptr;
    const bool show_splash_screen = true;
    if (show_splash_screen) {
        // make a bitmap with dark grey banner on the left side
        //BBS make BBL splash screen bitmap
        wxBitmap bmp = BBLSplashScreen::MakeBitmap();
        // Detect position (display) to show the splash screen
        // Now this position is equal to the mainframe position
        wxPoint splashscreen_pos = wxDefaultPosition;
        if (app_config->has("window_mainframe")) {
            auto metrics = WindowMetrics::deserialize(app_config->get("window_mainframe"));
            if (metrics)
                splashscreen_pos = metrics->get_rect().GetPosition();
        }
        BOOST_LOG_TRIVIAL(info) << "begin to show the splash screen...";
        //BBS use BBL splashScreen
        scrn = new BBLSplashScreen(bmp, wxSPLASH_CENTRE_ON_SCREEN | wxSPLASH_TIMEOUT, 10000, splashscreen_pos);
#ifndef __linux__
        wxYield();
#endif
        scrn->SetText(_L("Loading configuration")+ dots);
    }
    BOOST_LOG_TRIVIAL(info) << "loading systen presets...";
    preset_bundle = new PresetBundle();
    // just checking for existence of Slic3r::data_dir is not enough : it may be an empty directory
    // supplied as argument to --datadir; in that case we should still run the wizard
    preset_bundle->setup_directories();
    if (m_init_app_config_from_older)
        copy_older_config();
    if (is_editor()) {
#ifdef __WXMSW__
        if (app_config->get("associate_3mf") == "true")
            associate_files(L"3mf");
        if (app_config->get("associate_stl") == "true")
            associate_files(L"stl");
        if (app_config->get("associate_step") == "true") {
            associate_files(L"step");
            associate_files(L"stp");
        }
        if (app_config->get("associate_gcode") == "true")
            associate_files(L"gcode");
#endif // __WXMSW__
        preset_updater = new PresetUpdater();
        Bind(EVT_SLIC3R_VERSION_ONLINE, [this](const wxCommandEvent& evt) {
            if (this->plater_ != nullptr) {
                // this->plater_->get_notification_manager()->push_notification(NotificationType::NewAppAvailable);
                //BBS show msg box to download new version
               /* wxString tips = wxString::Format(_L("Click to download new version in default browser: %s"), version_info.version_str);
                DownloadDialog dialog(this->mainframe,
                    tips,
                    _L("New version of Orca Slicer"),
                    false,
                    wxCENTER | wxICON_INFORMATION);
                dialog.SetExtendedMessage(extmsg);*/
                std::string skip_version_str = this->app_config->get("app", "skip_version");
                bool skip_this_version = false;
                if (!skip_version_str.empty()) {
                    BOOST_LOG_TRIVIAL(info) << "new version = " << version_info.version_str << ", skip version = " << skip_version_str;
                    if (version_info.version_str <= skip_version_str) {
                        skip_this_version = true;
                    } else {
                        app_config->set("skip_version", "");
                        skip_this_version = false;
                    }
                }
                if (!skip_this_version
                    || evt.GetInt() != 0) {
                    UpdateVersionDialog dialog(this->mainframe);
                    wxString            extmsg = wxString::FromUTF8(version_info.description);
                    dialog.update_version_info(extmsg, version_info.version_str);
                    //dialog.update_version_info(version_info.description);
                    if (evt.GetInt() != 0) {
                        dialog.m_remind_choice->Hide();
                    }
                    switch (dialog.ShowModal())
                    {
                    case wxID_YES:
                        wxLaunchDefaultBrowser(version_info.url);
                        break;
                    case wxID_NO:
                        break;
                    default:
                        ;
                    }
                }
            }
            });
        Bind(EVT_ENTER_FORCE_UPGRADE, [this](const wxCommandEvent& evt) {
                wxString      version_str = wxString::FromUTF8(this->app_config->get("upgrade", "version"));
                wxString      description_text = wxString::FromUTF8(this->app_config->get("upgrade", "description"));
                std::string   download_url = this->app_config->get("upgrade", "url");
                wxString tips = wxString::Format(_L("Click to download new version in default browser: %s"), version_str);
                DownloadDialog dialog(this->mainframe,
                    tips,
                    _L("The Orca Slicer needs an upgrade"),
                    false,
                    wxCENTER | wxICON_INFORMATION);
                dialog.SetExtendedMessage(description_text);
                int result = dialog.ShowModal();
                switch (result)
                {
                 case wxID_YES:
                     wxLaunchDefaultBrowser(download_url);
                     break;
                 case wxID_NO:
                     wxGetApp().mainframe->Close(true);
                     break;
                 default:
                     wxGetApp().mainframe->Close(true);
                }
            });
        Bind(EVT_SHOW_NO_NEW_VERSION, [this](const wxCommandEvent& evt) {
            wxString msg = _L("This is the newest version.");
            InfoDialog dlg(nullptr, _L("Info"), msg);
            dlg.ShowModal();
        });
        Bind(EVT_SHOW_DIALOG, [this](const wxCommandEvent& evt) {
            wxString msg = evt.GetString();
            InfoDialog dlg(this->mainframe, _L("Info"), msg);
            dlg.ShowModal();
            /*wxString text = evt.GetString();
            Slic3r::GUI::MessageDialog msg_dlg(this->mainframe, text, "", wxAPPLY | wxOK);
            msg_dlg.ShowModal();*/
        });
    }
    else {
#ifdef __WXMSW__
        if (app_config->get("associate_gcode") == "true")
            associate_files(L"gcode");
#endif // __WXMSW__
    }
    // Suppress the '- default -' presets.
    preset_bundle->set_default_suppressed(true);
    Bind(EVT_SET_SELECTED_MACHINE, &GUI_App::on_set_selected_machine, this);
    Bind(EVT_USER_LOGIN, &GUI_App::on_user_login, this);
    Bind(EVT_USER_LOGIN_HANDLE, &GUI_App::on_user_login_handle, this);
    Bind(EVT_CHECK_PRIVACY_VER, &GUI_App::on_check_privacy_update, this);
    Bind(EVT_CHECK_PRIVACY_SHOW, &GUI_App::show_check_privacy_dlg, this);
    Bind(EVT_SHOW_IP_DIALOG, &GUI_App::show_ip_address_enter_dialog_handler, this);
    Bind(EVT_SHOW_IP_DIALOG, &GUI_App::show_ip_address_enter_dialog_handler, this);
    copy_network_if_available();
    on_init_network();
    if (m_agent && m_agent->is_user_login()) {
        enable_user_preset_folder(true);
    } else {
        enable_user_preset_folder(false);
    }
    // BBS if load user preset failed
    //if (loaded_preset_result != 0) {
        try {
            // Enable all substitutions (in both user and system profiles), but log the substitutions in user profiles only.
            // If there are substitutions in system profiles, then a "reconfigure" event shall be triggered, which will force
            // installation of a compatible system preset, thus nullifying the system preset substitutions.
            init_params->preset_substitutions = preset_bundle->load_presets(*app_config, ForwardCompatibilitySubstitutionRule::EnableSystemSilent);
        }
        catch (const std::exception& ex) {
            show_error(nullptr, ex.what());
        }
    //}
    if (app_config->get("sync_user_preset") == "true") {
        //BBS loading user preset
        // Always async, not such startup step
        //BOOST_LOG_TRIVIAL(info) << "Loading user presets...";
        //scrn->SetText(_L("Loading user presets..."));
        if (m_agent) {
            start_sync_user_preset();
        }
    }
#ifdef WIN32
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
    register_win32_dpi_event();
#endif // !wxVERSION_EQUAL_OR_GREATER_THAN
    register_win32_device_notification_event();
#endif // WIN32
    // Let the libslic3r know the callback, which will translate messages on demand.
    Slic3r::I18N::set_translate_callback(libslic3r_translate_callback);
    BOOST_LOG_TRIVIAL(info) << "create the main window";
    mainframe = new MainFrame();
    // hide settings tabs after first Layout
    if (is_editor()) {
        mainframe->select_tab(size_t(0));
    }
    sidebar().obj_list()->init();
    //sidebar().aux_list()->init_auxiliary();
    //mainframe->m_auxiliary->init_auxiliary();
//     update_mode(); // !!! do that later
    SetTopWindow(mainframe);
    plater_->init_notification_manager();
    m_printhost_job_queue.reset(new PrintHostJobQueue(mainframe->printhost_queue_dlg()));
    if (is_gcode_viewer()) {
        mainframe->update_layout();
        if (plater_ != nullptr)
            // ensure the selected technology is ptFFF
            plater_->set_printer_technology(ptFFF);
    }
    else
        load_current_presets();
    if (plater_ != nullptr) {
        plater_->reset_project_dirty_initial_presets();
        plater_->update_project_dirty_from_presets();
    }
    // BBS:
#ifdef __WINDOWS__
    mainframe->topbar()->SaveNormalRect();
#endif
    mainframe->Show(true);
    BOOST_LOG_TRIVIAL(info) << "main frame firstly shown";
//#if BBL_HAS_FIRST_PAGE
    //BBS: set tp3DEditor firstly
    /*plater_->canvas3D()->enable_render(false);
    mainframe->select_tab(size_t(MainFrame::tp3DEditor));
    scrn->SetText(_L("Loading Opengl resourses..."));
    plater_->select_view_3D("3D");
    //BBS init the opengl resource here
    Size canvas_size = plater_->canvas3D()->get_canvas_size();
    wxGetApp().imgui()->set_display_size(static_cast<float>(canvas_size.get_width()), static_cast<float>(canvas_size.get_height()));
    wxGetApp().init_opengl();
    plater_->canvas3D()->init();
    wxGetApp().imgui()->new_frame();
    plater_->canvas3D()->enable_render(true);
    plater_->canvas3D()->render();
    if (is_editor())
        mainframe->select_tab(size_t(0));*/
//#else
    //plater_->trigger_restore_project(1);
//#endif
    obj_list()->set_min_height();
    update_mode(); // update view mode after fix of the object_list size
//#ifdef __APPLE__
//    other_instance_message_handler()->bring_instance_forward();
//#endif //__APPLE__
    Bind(EVT_HTTP_ERROR, &GUI_App::on_http_error, this);
    Bind(wxEVT_IDLE, [this](wxIdleEvent& event)
    {
        bool curr_studio_active = this->is_studio_active();
        if (m_studio_active != curr_studio_active) {
            if (curr_studio_active) {
                BOOST_LOG_TRIVIAL(info) << "studio is active, start to subscribe";
                if (m_agent) {
                    json j = json::object();
                    m_agent->start_subscribe("app");
                    m_agent->track_event("mqtt_active", j.dump());
                }
            } else {
                BOOST_LOG_TRIVIAL(info) << "studio is inactive, stop to subscribe";
                if (m_agent) {
                    json j = json::object();
                    m_agent->stop_subscribe("app");
                    m_agent->track_event("mqtt_inactive", j.dump());
                }
            }
            m_studio_active = curr_studio_active;
        }
        if (! plater_)
            return;
        // BBS
        //this->obj_manipul()->update_if_dirty();
        //use m_post_initialized instead
        //static bool update_gui_after_init = true;
        // An ugly solution to GH #5537 in which GUI_App::init_opengl (normally called from events wxEVT_PAINT
        // and wxEVT_SET_FOCUS before GUI_App::post_init is called) wasn't called before GUI_App::post_init and OpenGL wasn't initialized.
//#ifdef __linux__
//        if (!m_post_initialized && m_opengl_initialized) {
//#else
        if (!m_post_initialized && !m_adding_script_handler) {
//#endif
            m_post_initialized = true;
#ifdef WIN32
            this->mainframe->register_win32_callbacks();
#endif
            this->post_init();
            if (!m_download_file_url.empty()) {
                request_model_download(m_download_file_url);
                m_download_file_url = "";
            }
        }
        if (m_post_initialized && app_config->dirty())
            app_config->save();
    });
    m_initialized = true;
    flush_logs();
    BOOST_LOG_TRIVIAL(info) << "finished the gui app init";
    //BBS: delete splash screen
    delete scrn;
    return true;
}
References _L, app_config, copy_older_config(), dark_mode(), Slic3r::data_dir(), Slic3r::GUI::WindowMetrics::deserialize(), Slic3r::GUI::dialogStack, Slic3r::GUI::dots(), Slic3r::extra_headers, Slic3r::GUI::from_u8(), Slic3r::AppConfig::get(), get_extra_header(), Slic3r::AppConfig::has(), init_fonts(), init_label_colours(), NppDarkMode::InitDarkMode(), is_editor(), Slic3r::GUI::RichMessageDialog::IsCheckBoxChecked(), L, load_language(), m_init_app_config_from_older, m_last_config_version, mainframe, Slic3r::GUI::BBLSplashScreen::MakeBitmap(), NULL, plater_, preset_bundle, preset_updater, remove_old_networking_plugins(), Slic3r::resources_dir(), Slic3r::AppConfig::set(), Slic3r::Http::set_extra_headers(), CBaseException::set_log_folder(), NppDarkMode::SetDarkMode(), NppDarkMode::SetSystemMenuForApp(), Slic3r::GUI::BBLSplashScreen::SetText(), Slic3r::PresetBundle::setup_directories(), Slic3r::GUI::RichMessageDialog::ShowCheckBox(), Slic3r::GUI::RichMessageDialog::ShowModal(), Slic3r::Http::tls_global_init(), Slic3r::Http::tls_system_cert_store(), and TRUE.
Referenced by OnInit().
on_init_network()
bool Slic3r::GUI::GUI_App::on_init_network (bool try_backup = false) private
{
    int load_agent_dll = Slic3r::NetworkAgent::initialize_network_module();
    bool create_network_agent = false;
__retry:
    if (!load_agent_dll) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": on_init_network, load dll ok";
        if (check_networking_version()) {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": on_init_network, compatibility version";
            auto bambu_source = Slic3r::NetworkAgent::get_bambu_source_entry();
            if (!bambu_source) {
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": can not get bambu source module!";
                m_networking_compatible = false;
                if (app_config->get("installed_networking") == "1") {
                    m_networking_need_update = true;
                }
            }
            else
                create_network_agent = true;
        } else {
            if (try_backup) {
                int result = Slic3r::NetworkAgent::unload_network_module();
                BOOST_LOG_TRIVIAL(info) << "on_init_network, version mismatch, unload_network_module, result = " << result;
                load_agent_dll = Slic3r::NetworkAgent::initialize_network_module(true);
                try_backup = false;
                goto __retry;
            }
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": on_init_network, version dismatch, need upload network module";
            if (app_config->get("installed_networking") == "1") {
                m_networking_need_update = true;
            }
        }
    } else {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": on_init_network, load dll failed";
        if (app_config->get("installed_networking") == "1") {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": on_init_network, need upload network module";
            m_networking_need_update = true;
        }
    }
    if (create_network_agent) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", create network agent...");
        m_agent = new Slic3r::NetworkAgent();
        if (!m_device_manager)
            m_device_manager = new Slic3r::DeviceManager(m_agent);
        else
            m_device_manager->set_agent(m_agent);
        //std::string data_dir = wxStandardPaths::Get().GetUserDataDir().ToUTF8().data();
        std::string data_directory = data_dir();
        //BBS set config dir
        if (m_agent) {
            m_agent->set_config_dir(data_directory);
        }
        //BBS start http log
        if (m_agent) {
            m_agent->init_log();
        }
        //BBS set cert dir
        if (m_agent)
            m_agent->set_cert_file(resources_dir() + "/cert", "slicer_base64.cer");
        init_http_extra_header();
        if (m_agent) {
            init_networking_callbacks();
            std::string country_code = app_config->get_country_code();
            m_agent->set_country_code(country_code);
            m_agent->start();
        }
    }
    else {
        int result = Slic3r::NetworkAgent::unload_network_module();
        BOOST_LOG_TRIVIAL(info) << "on_init_network, unload_network_module, result = " << result;
        if (!m_device_manager)
            m_device_manager = new Slic3r::DeviceManager();
    }
    return true;
}
References app_config, check_networking_version(), Slic3r::data_dir(), Slic3r::AppConfig::get(), Slic3r::NetworkAgent::get_bambu_source_entry(), Slic3r::AppConfig::get_country_code(), init_http_extra_header(), Slic3r::NetworkAgent::init_log(), init_networking_callbacks(), Slic3r::NetworkAgent::initialize_network_module(), m_agent, m_device_manager, m_networking_compatible, m_networking_need_update, Slic3r::resources_dir(), Slic3r::DeviceManager::set_agent(), Slic3r::NetworkAgent::set_cert_file(), Slic3r::NetworkAgent::set_config_dir(), Slic3r::NetworkAgent::set_country_code(), Slic3r::NetworkAgent::start(), and Slic3r::NetworkAgent::unload_network_module().
Referenced by restart_networking().
on_set_selected_machine()
void Slic3r::GUI::GUI_App::on_set_selected_machine (wxCommandEvent & evt)
{
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev || m_agent) return;
    dev->set_selected_machine(m_agent->get_user_selected_machine());
}
References Slic3r::NetworkAgent::get_user_selected_machine(), m_agent, and Slic3r::DeviceManager::set_selected_machine().
on_show_check_privacy_dlg()
void Slic3r::GUI::GUI_App::on_show_check_privacy_dlg (int online_login = 0)
{
    auto evt = new wxCommandEvent(EVT_CHECK_PRIVACY_SHOW);
    evt->SetInt(online_login);
    wxQueueEvent(this, evt);
}
Referenced by on_check_privacy_update().
on_user_login()
void Slic3r::GUI::GUI_App::on_user_login (wxCommandEvent & evt)
{
    if (!m_agent) { return; }
    int online_login = evt.GetInt();
    // check privacy before handle
    check_privacy_version(online_login);
    check_track_enable();
}
References check_privacy_version(), check_track_enable(), and m_agent.
on_user_login_handle()
void Slic3r::GUI::GUI_App::on_user_login_handle (wxCommandEvent & evt)
{
    if (!m_agent) { return; }
    int online_login = evt.GetInt();
    m_agent->connect_server();
    // get machine list
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    boost::thread update_thread = boost::thread([this, dev] {
        dev->update_user_machine_list_info();
        auto evt = new wxCommandEvent(EVT_SET_SELECTED_MACHINE);
        wxQueueEvent(this, evt);
    });
    if (online_login)
        GUI::wxGetApp().mainframe->show_sync_dialog();
    else if (app_config->get("sync_user_preset") == "true") {
        enable_user_preset_folder(true);
    } else {
        enable_user_preset_folder(false);
    }
    //show publish button
    if (m_agent->is_user_login() && mainframe) {
        int identifier;
        int result = m_agent->get_user_info(&identifier);
        auto publish_identifier = identifier & 1;
#ifdef __WINDOWS__
        if (result == 0 && publish_identifier >= 0) {
            mainframe->m_topbar->show_publish_button(publish_identifier == 0 ? false : true);
        }
#else
        mainframe->show_publish_button(publish_identifier == 0 ? false : true);
#endif
    }
}
References app_config, Slic3r::NetworkAgent::connect_server(), enable_user_preset_folder(), Slic3r::AppConfig::get(), Slic3r::NetworkAgent::get_user_info(), Slic3r::NetworkAgent::is_user_login(), m_agent, Slic3r::GUI::MainFrame::m_topbar, mainframe, BBLTopbar::show_publish_button(), Slic3r::GUI::MainFrame::show_publish_button(), and Slic3r::DeviceManager::update_user_machine_list_info().
OnExceptionInMainLoop()
bool Slic3r::GUI::GUI_App::OnExceptionInMainLoop () override virtual
{
    generic_exception_handle();
    return false;
}
References Slic3r::GUI::generic_exception_handle().
OnInit()
bool Slic3r::GUI::GUI_App::OnInit () override
{
    try {
        return on_init_inner();
    } catch (const std::exception&) {
        generic_exception_handle();
        return false;
    }
}
References Slic3r::GUI::generic_exception_handle(), and on_init_inner().
open_browser_with_warning_dialog()
bool Slic3r::GUI::GUI_App::open_browser_with_warning_dialog (const wxString & url, int flags = 0)
{
    return wxLaunchDefaultBrowser(url, flags);
}
Referenced by open_web_page_localized().
open_mall_page_dialog()
void Slic3r::GUI::GUI_App::open_mall_page_dialog ()
{
    std::string host_url;
    std::string model_url;
    std::string link_url;
    int result = -1;
    //model api url
    host_url = get_model_http_url(app_config->get_country_code());
    //model url
    wxString language_code = this->current_language_code().BeforeFirst('_');
    model_url = language_code.ToStdString();
    if (getAgent() && mainframe) {
        //login already
        if (getAgent()->is_user_login()) {
            std::string ticket;
            result = getAgent()->request_bind_ticket(&ticket);
            if(result == 0){
                link_url = host_url + "api/sign-in/ticket?to=" + host_url + url_encode(model_url) + "&ticket=" + ticket;
            }
        }
    }
    if (result < 0) {
       link_url = host_url + model_url;
    }
    wxLaunchDefaultBrowser(link_url);
}
References app_config, current_language_code(), Slic3r::AppConfig::get_country_code(), get_model_http_url(), getAgent(), is_user_login(), mainframe, Slic3r::NetworkAgent::request_bind_ticket(), and url_encode().
open_preferences()
void Slic3r::GUI::GUI_App::open_preferences (size_t open_on_tab = 0, const std::string & highlight_option = std::string())
{
    bool app_layout_changed = false;
    {
        // the dialog needs to be destroyed before the call to recreate_GUI()
        // or sometimes the application crashes into wxDialogBase() destructor
        // so we put it into an inner scope
        PreferencesDialog dlg(mainframe, open_on_tab, highlight_option);
        dlg.ShowModal();
        // BBS
        //app_layout_changed = dlg.settings_layout_changed();
#if ENABLE_GCODE_LINES_ID_IN_H_SLIDER
        if (dlg.seq_top_layer_only_changed() || dlg.seq_seq_top_gcode_indices_changed())
#else
        if (dlg.seq_top_layer_only_changed())
#endif // ENABLE_GCODE_LINES_ID_IN_H_SLIDER
            this->plater_->refresh_print();
#ifdef _WIN32
        if (is_editor()) {
            if (app_config->get("associate_3mf") == "true")
                associate_files(L"3mf");
            if (app_config->get("associate_stl") == "true")
                associate_files(L"stl");
            if (app_config->get("associate_step") == "true") {
                associate_files(L"step");
                associate_files(L"stp");
            }
        }
        else {
            if (app_config->get("associate_gcode") == "true")
                associate_files(L"gcode");
        }
#endif // _WIN32
    }
    // BBS
    /*
    if (app_layout_changed) {
        // hide full main_sizer for mainFrame
        mainframe->GetSizer()->Show(false);
        mainframe->update_layout();
        mainframe->select_tab(size_t(0));
    }*/
}
References app_config, Slic3r::AppConfig::get(), is_editor(), L, mainframe, plater_, Slic3r::GUI::Plater::refresh_print(), Slic3r::GUI::PreferencesDialog::seq_top_layer_only_changed(), and Slic3r::GUI::DPIAware< P >::ShowModal().
open_publish_page_dialog()
void Slic3r::GUI::GUI_App::open_publish_page_dialog ()
{
    std::string host_url;
    std::string model_url;
    std::string link_url;
    int result = -1;
    //model api url
    host_url = get_model_http_url(app_config->get_country_code());
    //publish url
    wxString language_code = this->current_language_code().BeforeFirst('_');
    model_url += (language_code.ToStdString() + "/my/models/publish");
    if (getAgent() && mainframe) {
        //login already
        if (getAgent()->is_user_login()) {
            std::string ticket;
            result = getAgent()->request_bind_ticket(&ticket);
            if (result == 0) {
                link_url = host_url + "api/sign-in/ticket?to=" + host_url + url_encode(model_url) + "&ticket=" + ticket;
            }
        }
    }
    if (result < 0) {
        link_url = host_url + model_url;
    }
    wxLaunchDefaultBrowser(link_url);
}
References app_config, current_language_code(), Slic3r::AppConfig::get_country_code(), get_model_http_url(), getAgent(), Slic3r::NetworkAgent::is_user_login(), mainframe, Slic3r::NetworkAgent::request_bind_ticket(), and url_encode().
open_web_page_localized()
void Slic3r::GUI::GUI_App::open_web_page_localized (const std::string & http_address)
{
    open_browser_with_warning_dialog(http_address + "&lng=" + this->current_language_code_safe());
}
References current_language_code_safe(), and open_browser_with_warning_dialog().
params_dialog()
ParamsDialog * Slic3r::GUI::GUI_App::params_dialog ()
{
    if (mainframe)
        return mainframe->m_param_dialog;
    return nullptr;
}
References Slic3r::GUI::MainFrame::m_param_dialog, and mainframe.
params_panel()
ParamsPanel * Slic3r::GUI::GUI_App::params_panel ()
{
    if (mainframe)
        return mainframe->m_param_panel;
    return nullptr;
}
References Slic3r::GUI::MainFrame::m_param_panel, and mainframe.
persist_window_geometry()
void Slic3r::GUI::GUI_App::persist_window_geometry (wxTopLevelWindow * window, bool default_maximized = false)
{
    const std::string name = into_u8(window->GetName());
    window->Bind(wxEVT_CLOSE_WINDOW, [=](wxCloseEvent &event) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< ": received wxEVT_CLOSE_WINDOW, trigger save for window_mainframe";
        window_pos_save(window, "mainframe");
        event.Skip();
    });
    if (window_pos_restore(window, "mainframe", default_maximized)) {
        on_window_geometry(window, [=]() {
            window_pos_sanitize(window);
        });
    } else {
        on_window_geometry(window, [=]() {
            window_pos_center(window);
        });
    }
}
References Slic3r::GUI::into_u8(), Slic3r::GUI::on_window_geometry(), window_pos_center(), window_pos_restore(), window_pos_sanitize(), and window_pos_save().
plater() [1/2]
Plater * Slic3r::GUI::GUI_App::plater ()
{
    return plater_;
}
References plater_.
Referenced by load_current_presets(), post_init(), request_open_project(), Slic3r::GUI::ProjectDirtyStateManager::update_from_presets(), and update_mode().
plater() [2/2]
const Plater * Slic3r::GUI::GUI_App::plater () const
{
    return plater_;
}
References plater_.
post_init()
void Slic3r::GUI::GUI_App::post_init ()
{
    assert(initialized());
    if (! this->initialized())
        throw Slic3r::RuntimeError("Calling post_init() while not yet initialized");
    bool switch_to_3d = false;
    if (!this->init_params->input_files.empty()) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", init with input files, size %1%, input_gcode %2%")
            %this->init_params->input_files.size() %this->init_params->input_gcode;
        if (this->init_params->input_files.size() == 1 &&
            boost::starts_with(this->init_params->input_files.front(), "orcaslicer://open")) {
            auto input_str_arr = split_str(this->init_params->input_files.front(), "orcaslicer://open/?file=");
            std::string download_origin_url;
            for (auto input_str:input_str_arr) {
                if (!input_str.empty()) download_origin_url = input_str;
            }
            std::string download_file_url = url_decode(download_origin_url);
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << download_file_url;
            if (!download_file_url.empty() && ( boost::starts_with(download_file_url, "http://") ||  boost::starts_with(download_file_url, "https://")) ) {
                request_model_download(download_origin_url);
            }
        }
        else {
            switch_to_3d = true;
            if (this->init_params->input_gcode) {
                mainframe->select_tab(size_t(MainFrame::tp3DEditor));
                plater_->select_view_3D("3D");
                this->plater()->load_gcode(from_u8(this->init_params->input_files.front()));
            }
            else {
                mainframe->select_tab(size_t(MainFrame::tp3DEditor));
                plater_->select_view_3D("3D");
                Plater::TakeSnapshot      snapshot(this->plater(), "Load Project", UndoRedo::SnapshotType::ProjectSeparator);
                const std::vector<size_t> res = this->plater()->load_files(this->init_params->input_files);
                if (!res.empty()) {
                    if (this->init_params->input_files.size() == 1) {
                        // Update application titlebar when opening a project file
                        const std::string& filename = this->init_params->input_files.front();
                        this->plater()->up_to_date(true, false);
                        this->plater()->up_to_date(true, true);
                        //BBS: remove amf logic as project
                        if (boost::algorithm::iends_with(filename, ".3mf"))
                            this->plater()->set_project_filename(from_u8(filename));
                    }
                }
            }
        }
    }
//#if BBL_HAS_FIRST_PAGE
    bool slow_bootup = false;
    if (app_config->get("slow_bootup") == "true") {
        slow_bootup = true;
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", slow bootup, won't render gl here.";
    }
    if (!switch_to_3d) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", begin load_gl_resources";
        mainframe->Freeze();
        plater_->canvas3D()->enable_render(false);
        mainframe->select_tab(size_t(MainFrame::tp3DEditor));
        plater_->select_view_3D("3D");
        //BBS init the opengl resource here
//#ifdef __linux__
        if (plater_->canvas3D()->get_wxglcanvas()->IsShownOnScreen()&&plater_->canvas3D()->make_current_for_postinit()) {
//#endif
            Size canvas_size = plater_->canvas3D()->get_canvas_size();
            wxGetApp().imgui()->set_display_size(static_cast<float>(canvas_size.get_width()), static_cast<float>(canvas_size.get_height()));
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", start to init opengl";
            wxGetApp().init_opengl();
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", finished init opengl";
            plater_->canvas3D()->init();
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", finished init canvas3D";
            wxGetApp().imgui()->new_frame();
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", finished init imgui frame";
            plater_->canvas3D()->enable_render(true);
            if (!slow_bootup) {
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", start to render a first frame for test";
                plater_->canvas3D()->render(false);
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", finished rendering a first frame for test";
            }
//#ifdef __linux__
        }
        else {
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << "Found glcontext not ready, postpone the init";
        }
//#endif
        if (is_editor())
            mainframe->select_tab(size_t(0));
        mainframe->Thaw();
        plater_->trigger_restore_project(1);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ", end load_gl_resources";
    }
//#endif
    //BBS: remove GCodeViewer as seperate APP logic
    /*if (this->init_params->start_as_gcodeviewer) {
        if (! this->init_params->input_files.empty())
            this->plater()->load_gcode(wxString::FromUTF8(this->init_params->input_files[0].c_str()));
    }
    else
    {
        if (! this->init_params->preset_substitutions.empty())
            show_substitutions_info(this->init_params->preset_substitutions);
#if 0
        // Load the cummulative config over the currently active profiles.
        //FIXME if multiple configs are loaded, only the last one will have an effect.
        // We need to decide what to do about loading of separate presets (just print preset, just filament preset etc).
        // As of now only the full configs are supported here.
        if (!m_print_config.empty())
            this->gui->mainframe->load_config(m_print_config);
#endif
        if (! this->init_params->load_configs.empty())
            // Load the last config to give it a name at the UI. The name of the preset may be later
            // changed by loading an AMF or 3MF.
            //FIXME this is not strictly correct, as one may pass a print/filament/printer profile here instead of a full config.
            this->mainframe->load_config_file(this->init_params->load_configs.back());
        // If loading a 3MF file, the config is loaded from the last one.
        if (!this->init_params->input_files.empty()) {
            const std::vector<size_t> res = this->plater()->load_files(this->init_params->input_files);
            if (!res.empty() && this->init_params->input_files.size() == 1) {
                // Update application titlebar when opening a project file
                const std::string& filename = this->init_params->input_files.front();
                //BBS: remove amf logic as project
                if (boost::algorithm::iends_with(filename, ".3mf"))
                    this->plater()->set_project_filename(filename);
            }
        }
        if (! this->init_params->extra_config.empty())
            this->mainframe->load_config(this->init_params->extra_config);
    }*/
    // BBS: to be checked
#if 1
    // show "Did you know" notification
    if (app_config->get("show_hints") == "true" && !is_gcode_viewer()) {
        plater_->get_notification_manager()->push_hint_notification(false);
    }
#endif
    m_show_gcode_window = app_config->get("show_gcode_window") == "true";
    if (m_networking_need_update) {
        //updating networking
        int ret = updating_bambu_networking();
        if (!ret) {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<":networking plugin updated successfully";
            //restart_networking();
        }
        else {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<<":networking plugin updated failed";
        }
    }
    // The extra CallAfter() is needed because of Mac, where this is the only way
    // to popup a modal dialog on start without screwing combo boxes.
    // This is ugly but I honestly found no better way to do it.
    // Neither wxShowEvent nor wxWindowCreateEvent work reliably.
    if (this->preset_updater) { // G-Code Viewer does not initialize preset_updater.
        BOOST_LOG_TRIVIAL(info) << "before check_updates";
        this->check_updates(false);
        BOOST_LOG_TRIVIAL(info) << "after check_updates";
        CallAfter([this] {
            bool cw_showed = this->config_wizard_startup();
            std::string http_url = get_http_url(app_config->get_country_code());
            std::string language = GUI::into_u8(current_language_code());
            std::string network_ver = Slic3r::NetworkAgent::get_version();
            bool        sys_preset  = app_config->get("sync_system_preset") == "true";
            this->preset_updater->sync(http_url, language, network_ver, sys_preset ? preset_bundle : nullptr);
            //BBS: check new version
            this->check_new_version_sf();
      //BBS: check privacy version
            if (is_user_login())
                this->check_privacy_version(0);
        });
    }
    if(!m_networking_need_update && m_agent) {
        m_agent->set_on_ssdp_msg_fn(
            [this](std::string json_str) {
                if (m_is_closing) {
                    return;
                }
                GUI::wxGetApp().CallAfter([this, json_str] {
                    if (m_device_manager) {
                        m_device_manager->on_machine_alive(json_str);
                    }
                    });
            }
        );
        m_agent->set_on_http_error_fn([this](unsigned int status, std::string body) {
            this->handle_http_error(status, body);
        });
        m_agent->start_discovery(true, false);
    }
    //update the plugin tips
    CallAfter([this] {
            mainframe->refresh_plugin_tips();
        });
    // update hms info
    CallAfter([this] {
            if (hms_query)
                hms_query->check_hms_info();
        });
    std::string functional_config_file = Slic3r::resources_dir() + "/config.json";
    DeviceManager::load_functional_config(encode_path(functional_config_file.c_str()));
    std::string filaments_blacklist_config_file = Slic3r::resources_dir() + "/printers/filaments_blacklist.json";
    DeviceManager::load_filaments_blacklist_config(encode_path(filaments_blacklist_config_file.c_str()));
    // remove old log files over LOG_FILES_MAX_NUM
    std::string log_addr = data_dir();
    if (!log_addr.empty()) {
        auto log_folder = boost::filesystem::path(log_addr) / "log";
        if (boost::filesystem::exists(log_folder)) {
           std::vector<std::pair<time_t, std::string>> files_vec;
           for (auto& it : boost::filesystem::directory_iterator(log_folder)) {
               auto temp_path = it.path();
               try {
                   std::time_t lw_t = boost::filesystem::last_write_time(temp_path) ;
                   files_vec.push_back({ lw_t, temp_path.filename().string() });
               } catch (const std::exception &ex) {
               }
           }
           std::sort(files_vec.begin(), files_vec.end(), [](
               std::pair<time_t, std::string> &a, std::pair<time_t, std::string> &b) {
               return a.first > b.first;
           });
           while (files_vec.size() > LOG_FILES_MAX_NUM) {
               auto full_path = log_folder / boost::filesystem::path(files_vec[files_vec.size() - 1].second);
               BOOST_LOG_TRIVIAL(info) << "delete log file over " << LOG_FILES_MAX_NUM << ", filename: "<< files_vec[files_vec.size() - 1].second;
               try {
                   boost::filesystem::remove(full_path);
               }
               catch (const std::exception& ex) {
                   BOOST_LOG_TRIVIAL(error) << "failed to delete log file: "<< files_vec[files_vec.size() - 1].second << ". Error: " << ex.what();
               }
               files_vec.pop_back();
           }
        }
    }
    BOOST_LOG_TRIVIAL(info) << "finished post_init";
//BBS: remove the single instance currently
/*#ifdef _WIN32
    // Sets window property to mainframe so other instances can indentify it.
    OtherInstanceMessageHandler::init_windows_properties(mainframe, m_instance_hash_int);
#endif //WIN32*/
}
References app_config, Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::HMSQuery::check_hms_info(), check_new_version_sf(), check_privacy_version(), check_updates(), config_wizard_startup(), current_language_code(), Slic3r::data_dir(), Slic3r::GUI::GLCanvas3D::enable_render(), Slic3r::encode_path(), error, Slic3r::GUI::from_u8(), Slic3r::AppConfig::get(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::AppConfig::get_country_code(), Slic3r::GUI::Size::get_height(), get_http_url(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::NetworkAgent::get_version(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLCanvas3D::get_wxglcanvas(), handle_http_error(), hms_query, Slic3r::GUI::GLCanvas3D::init(), init_params, initialized(), Slic3r::GUI::GUI_InitParams::input_files, Slic3r::GUI::GUI_InitParams::input_gcode, Slic3r::GUI::into_u8(), is_editor(), is_gcode_viewer(), is_user_login(), Slic3r::DeviceManager::load_filaments_blacklist_config(), Slic3r::GUI::Plater::load_files(), Slic3r::DeviceManager::load_functional_config(), Slic3r::GUI::Plater::load_gcode(), LOG_FILES_MAX_NUM, m_agent, m_device_manager, m_is_closing, m_networking_need_update, m_show_gcode_window, mainframe, Slic3r::GUI::GLCanvas3D::make_current_for_postinit(), Slic3r::DeviceManager::on_machine_alive(), plater(), plater_, preset_bundle, preset_updater, Slic3r::UndoRedo::ProjectSeparator, Slic3r::GUI::NotificationManager::push_hint_notification(), Slic3r::GUI::MainFrame::refresh_plugin_tips(), Slic3r::GUI::GLCanvas3D::render(), request_model_download(), Slic3r::resources_dir(), Slic3r::GUI::MainFrame::select_tab(), Slic3r::GUI::Plater::select_view_3D(), Slic3r::NetworkAgent::set_on_http_error_fn(), Slic3r::NetworkAgent::set_on_ssdp_msg_fn(), Slic3r::GUI::Plater::set_project_filename(), Slic3r::GUI::split_str(), Slic3r::NetworkAgent::start_discovery(), Slic3r::PresetUpdater::sync(), Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::GUI::Plater::trigger_restore_project(), Slic3r::GUI::Plater::up_to_date(), updating_bambu_networking(), and url_decode().
preset_deleted_from_cloud()
void Slic3r::GUI::GUI_App::preset_deleted_from_cloud (std::string setting_id)
{
    std::scoped_lock l(mutex_delete_cache_presets);
    need_delete_presets.erase(std::remove(need_delete_presets.begin(), need_delete_presets.end(), setting_id), need_delete_presets.end());
}
References Slic3r::GUI::mutex_delete_cache_presets, and need_delete_presets.
Referenced by start_sync_user_preset().
printhost_job_queue()
PrintHostJobQueue & Slic3r::GUI::GUI_App::printhost_job_queue () inline
{ return *m_printhost_job_queue.get(); }
References m_printhost_job_queue.
recreate_GUI()
void Slic3r::GUI::GUI_App::recreate_GUI (const wxString & message)
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "recreate_GUI enter";
    m_is_recreating_gui = true;
    mainframe->shutdown();
    ProgressDialog dlg(msg_name, msg_name, 100, nullptr, wxPD_AUTO_HIDE);
    dlg.Pulse();
    dlg.Update(10, _L("Rebuild") + dots);
    MainFrame *old_main_frame = mainframe;
    mainframe = new MainFrame();
    if (is_editor())
        // hide settings tabs after first Layout
        mainframe->select_tab(size_t(MainFrame::tp3DEditor));
    // Propagate model objects to object list.
    sidebar().obj_list()->init();
    //sidebar().aux_list()->init_auxiliary();
    //mainframe->m_auxiliary->init_auxiliary();
    SetTopWindow(mainframe);
    dlg.Update(30, _L("Rebuild") + dots);
    old_main_frame->Destroy();
    dlg.Update(80, _L("Loading current presets") + dots);
    m_printhost_job_queue.reset(new PrintHostJobQueue(mainframe->printhost_queue_dlg()));
    load_current_presets();
    mainframe->Show(true);
    //mainframe->refresh_plugin_tips();
    dlg.Update(90, _L("Loading a mode view") + dots);
    obj_list()->set_min_height();
    update_mode();
    //check hms info for different language
    if (hms_query)
        hms_query->check_hms_info();
    //BBS: trigger restore project logic here, and skip confirm
    plater_->trigger_restore_project(1);
    // #ys_FIXME_delete_after_testing  Do we still need this  ?
//     CallAfter([]() {
//         // Run the config wizard, don't offer the "reset user profile" checkbox.
//         config_wizard_startup(true);
//     });
     //show publish button
    if (m_agent && m_agent->is_user_login() && mainframe) {
        int identifier;
        int result = m_agent->get_user_info(&identifier);
        auto publish_identifier = identifier & 1;
#ifdef __WINDOWS__
        if (result == 0 && publish_identifier >= 0) {
            mainframe->m_topbar->show_publish_button(publish_identifier == 0 ? false : true);
        }
#else
        mainframe->show_publish_button(publish_identifier == 0 ? false : true);
#endif
    }
    m_is_recreating_gui = false;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "recreate_GUI exit";
}
References _L, Slic3r::GUI::HMSQuery::check_hms_info(), Slic3r::GUI::dots(), Slic3r::NetworkAgent::get_user_info(), hms_query, Slic3r::GUI::ObjectList::init(), is_editor(), Slic3r::NetworkAgent::is_user_login(), load_current_presets(), m_agent, m_is_recreating_gui, m_printhost_job_queue, Slic3r::GUI::MainFrame::m_topbar, mainframe, obj_list(), Slic3r::GUI::Sidebar::obj_list(), plater_, Slic3r::GUI::MainFrame::printhost_queue_dlg(), Slic3r::GUI::ProgressDialog::Pulse(), Slic3r::GUI::MainFrame::select_tab(), Slic3r::GUI::ObjectList::set_min_height(), BBLTopbar::show_publish_button(), Slic3r::GUI::MainFrame::show_publish_button(), Slic3r::GUI::MainFrame::shutdown(), sidebar(), Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::GUI::Plater::trigger_restore_project(), Slic3r::GUI::ProgressDialog::Update(), and update_mode().
Referenced by switch_language().
reload_settings()
void Slic3r::GUI::GUI_App::reload_settings ()
{
    if (preset_bundle && m_agent) {
        std::map<std::string, std::map<std::string, std::string>> user_presets;
        m_agent->get_user_presets(&user_presets);
        preset_bundle->load_user_presets(*app_config, user_presets, ForwardCompatibilitySubstitutionRule::Enable);
        preset_bundle->save_user_presets(*app_config, get_delete_cache_presets());
        mainframe->update_side_preset_ui();
    }
}
References app_config, Slic3r::Enable, get_delete_cache_presets(), Slic3r::NetworkAgent::get_user_presets(), Slic3r::PresetBundle::load_user_presets(), m_agent, mainframe, preset_bundle, Slic3r::PresetBundle::save_user_presets(), and Slic3r::GUI::MainFrame::update_side_preset_ui().
Referenced by start_sync_user_preset().
removable_drive_manager()
RemovableDriveManager * Slic3r::GUI::GUI_App::removable_drive_manager () inline
{ return m_removable_drive_manager.get(); }
References m_removable_drive_manager.
Referenced by shutdown().
remove_mall_system_dialog()
void Slic3r::GUI::GUI_App::remove_mall_system_dialog ()
{
    if (m_mall_publish_dialog != nullptr) {
        m_mall_publish_dialog->Destroy();
        delete m_mall_publish_dialog;
    }
}
References m_mall_publish_dialog.
remove_old_networking_plugins()
void Slic3r::GUI::GUI_App::remove_old_networking_plugins () private
{
    std::string data_dir_str = data_dir();
    boost::filesystem::path data_dir_path(data_dir_str);
    auto plugin_folder = data_dir_path / "plugins";
    //auto plugin_folder = boost::filesystem::path(wxStandardPaths::Get().GetUserDataDir().ToUTF8().data()) / "plugins";
    if (boost::filesystem::exists(plugin_folder)) {
        BOOST_LOG_TRIVIAL(info) << "[remove_old_networking_plugins] remove the directory "<<plugin_folder.string();
        try {
            fs::remove_all(plugin_folder);
        } catch (...) {
            BOOST_LOG_TRIVIAL(error) << "Failed  removing the plugins directory " << plugin_folder.string();
        }
    }
}
References Slic3r::data_dir(), and error.
Referenced by on_init_inner().
remove_user_presets()
void Slic3r::GUI::GUI_App::remove_user_presets ()
{
    if (preset_bundle && m_agent) {
        preset_bundle->remove_users_preset(*app_config);
        // Not remove user preset cache
        //std::string user_id = m_agent->get_user_id();
        //preset_bundle->remove_user_presets_directory(user_id);
        //update ui
        mainframe->update_side_preset_ui();
    }
}
References app_config, m_agent, mainframe, preset_bundle, Slic3r::PresetBundle::remove_users_preset(), and Slic3r::GUI::MainFrame::update_side_preset_ui().
Referenced by start_sync_user_preset(), and stop_sync_user_preset().
request_login()
void Slic3r::GUI::GUI_App::request_login (bool show_user_info = false)
{
    ShowUserLogin();
    if (show_user_info) {
        get_login_info();
    }
}
References get_login_info(), and ShowUserLogin().
Referenced by handle_web_request().
request_model_download()
void Slic3r::GUI::GUI_App::request_model_download (std::string url)
{
    if (plater_) {
        plater_->request_model_download(url);
    }
}
References plater_, and Slic3r::GUI::Plater::request_model_download().
Referenced by post_init().
request_new_version()
void Slic3r::GUI::GUI_App::request_new_version (int by_user)
{
    wxCommandEvent* evt = new wxCommandEvent(EVT_SLIC3R_VERSION_ONLINE);
    evt->SetString(GUI::from_u8(version_info.version_str));
    evt->SetInt(by_user);
    GUI::wxGetApp().QueueEvent(evt);
}
References Slic3r::GUI::from_u8(), version_info, and Slic3r::GUI::VersionInfo::version_str.
request_open_project()
void Slic3r::GUI::GUI_App::request_open_project (std::string project_id)
{
    if (plater()->is_background_process_slicing()) {
        Slic3r::GUI::show_info(nullptr, _L("new or open project file is not allowed during the slicing process!"), _L("Open Project"));
        return;
    }
    if (project_id == "<new>")
        plater()->new_project();
    else if (project_id.empty())
        plater()->load_project();
    else if (std::find_if_not(project_id.begin(), project_id.end(),
        [](char c) { return std::isdigit(c); }) == project_id.end())
        ;
    else if (boost::algorithm::starts_with(project_id, "http"))
        ;
    else
        CallAfter([this, project_id] { mainframe->open_recent_project(-1, wxString::FromUTF8(project_id)); });
}
References _L, Slic3r::GUI::Plater::load_project(), mainframe, Slic3r::GUI::Plater::new_project(), Slic3r::GUI::MainFrame::open_recent_project(), plater(), and Slic3r::GUI::show_info().
Referenced by handle_web_request().
request_project_download()
void Slic3r::GUI::GUI_App::request_project_download (std::string project_id)
{
    if (!check_login()) return;
    download_project(project_id);
}
References check_login(), and download_project().
Referenced by handle_web_request().
request_remove_project()
void Slic3r::GUI::GUI_App::request_remove_project (std::string project_id)
{
    mainframe->remove_recent_project(-1, wxString::FromUTF8(project_id));
}
References mainframe, and Slic3r::GUI::MainFrame::remove_recent_project().
Referenced by handle_web_request().
request_user_handle()
void Slic3r::GUI::GUI_App::request_user_handle (int online_login = 0)
{
    auto evt = new wxCommandEvent(EVT_USER_LOGIN_HANDLE);
    evt->SetInt(online_login);
    wxQueueEvent(this, evt);
}
Referenced by check_privacy_version(), on_check_privacy_update(), and show_check_privacy_dlg().
request_user_login()
void Slic3r::GUI::GUI_App::request_user_login (int online_login = 0)
{
    auto evt = new wxCommandEvent(EVT_USER_LOGIN);
    evt->SetInt(online_login);
    wxQueueEvent(this, evt);
}
Referenced by handle_script_message().
request_user_logout()
void Slic3r::GUI::GUI_App::request_user_logout ()
{
    if (m_agent) {
        bool     transfer_preset_changes = false;
        wxString header = _L("Some presets are modified.") + "\n" +
            _L("You can keep the modifield presets to the new project, discard or save changes as new presets.");
        using ab        = UnsavedChangesDialog::ActionButtons;
        wxGetApp().check_and_keep_current_preset_changes(_L("User logged out"), header, ab::KEEP | ab::SAVE, &transfer_preset_changes);
        m_agent->user_logout();
        m_agent->set_user_selected_machine("");
        /* delete old user settings */
        m_device_manager->clean_user_info();
        GUI::wxGetApp().sidebar().load_ams_list({}, {});
        GUI::wxGetApp().stop_sync_user_preset();
#ifdef __WINDOWS__
        wxGetApp().mainframe->topbar()->show_publish_button(false);
#else
        wxGetApp().mainframe->show_publish_button(false);
#endif
    }
}
References _L, Slic3r::DeviceManager::clean_user_info(), m_agent, m_device_manager, Slic3r::NetworkAgent::set_user_selected_machine(), and Slic3r::NetworkAgent::user_logout().
Referenced by on_http_error().
request_user_unbind()
int Slic3r::GUI::GUI_App::request_user_unbind (std::string dev_id)
{
    int result = -1;
    if (m_agent) {
        result = m_agent->unbind(dev_id);
        BOOST_LOG_TRIVIAL(info) << "request_user_unbind, dev_id = " << dev_id << ", result = " << result;
        return result;
    }
    return result;
}
References m_agent, and Slic3r::NetworkAgent::unbind().
reset_to_active()
void Slic3r::GUI::GUI_App::reset_to_active ()
{
    last_active_point = std::chrono::system_clock::now();
}
References last_active_point.
restart_networking()
void Slic3r::GUI::GUI_App::restart_networking ()
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(" enter, mainframe %1%")%mainframe;
    on_init_network(true);
    if(m_agent) {
        init_networking_callbacks();
        m_agent->set_on_ssdp_msg_fn(
            [this](std::string json_str) {
                if (m_is_closing) {
                    return;
                }
                GUI::wxGetApp().CallAfter([this, json_str] {
                    if (m_device_manager) {
                        m_device_manager->on_machine_alive(json_str);
                    }
                    });
            }
        );
        m_agent->set_on_http_error_fn([this](unsigned int status, std::string body) {
            this->handle_http_error(status, body);
        });
        m_agent->start_discovery(true, false);
        if (mainframe)
            mainframe->refresh_plugin_tips();
        if (plater_)
            plater_->get_notification_manager()->bbl_close_plugin_install_notification();
        if (app_config->get("sync_user_preset") == "true") { start_sync_user_preset(); }
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(" exit, m_agent=%1%")%m_agent;
}
References app_config, Slic3r::GUI::NotificationManager::bbl_close_plugin_install_notification(), Slic3r::AppConfig::get(), Slic3r::GUI::Plater::get_notification_manager(), handle_http_error(), init_networking_callbacks(), m_agent, m_device_manager, m_is_closing, mainframe, on_init_network(), Slic3r::DeviceManager::on_machine_alive(), plater_, Slic3r::GUI::MainFrame::refresh_plugin_tips(), Slic3r::NetworkAgent::set_on_http_error_fn(), Slic3r::NetworkAgent::set_on_ssdp_msg_fn(), Slic3r::NetworkAgent::start_discovery(), and start_sync_user_preset().
run_script()
void Slic3r::GUI::GUI_App::run_script (wxString js)
{
    if (mainframe)
        return mainframe->RunScript(js);
}
References mainframe, and Slic3r::GUI::MainFrame::RunScript().
run_wizard()
bool Slic3r::GUI::GUI_App::run_wizard (ConfigWizard::RunReason reason, ConfigWizard::StartPage start_page = ConfigWizard::SP_WELCOME)
{
    wxCHECK_MSG(mainframe != nullptr, false, "Internal error: Main frame not created / null");
    //if (reason == ConfigWizard::RR_USER) {
    //    //TODO: turn off it currently, maybe need to turn on in the future
    //    if (preset_updater->config_update(app_config->orig_version(), PresetUpdater::UpdateParams::FORCED_BEFORE_WIZARD) == PresetUpdater::R_ALL_CANCELED)
    //        return false;
    //}
    //auto wizard_t = new ConfigWizard(mainframe);
    //const bool res = wizard_t->run(reason, start_page);
    std::string strFinish = wxGetApp().app_config->get("firstguide", "finish");
    long        pStyle    = wxCAPTION | wxCLOSE_BOX | wxSYSTEM_MENU;
    if (strFinish == "false" || strFinish.empty())
        pStyle = wxCAPTION | wxTAB_TRAVERSAL;
    GuideFrame wizard(this, pStyle);
    auto page = start_page == ConfigWizard::SP_WELCOME ? GuideFrame::BBL_WELCOME :
                start_page == ConfigWizard::SP_FILAMENTS ? GuideFrame::BBL_FILAMENT_ONLY :
                start_page == ConfigWizard::SP_PRINTERS ? GuideFrame::BBL_MODELS_ONLY :
                GuideFrame::BBL_MODELS;
    wizard.SetStartPage(page);
    bool       res = wizard.run();
    if (res) {
        load_current_presets();
        // BBS: remove SLA related message
    }
    return res;
}
References Slic3r::GUI::GuideFrame::BBL_FILAMENT_ONLY, Slic3r::GUI::GuideFrame::BBL_MODELS, Slic3r::GUI::GuideFrame::BBL_MODELS_ONLY, Slic3r::GUI::GuideFrame::BBL_WELCOME, load_current_presets(), mainframe, Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::GuideFrame::SetStartPage(), Slic3r::GUI::ConfigWizard::SP_FILAMENTS, Slic3r::GUI::ConfigWizard::SP_PRINTERS, and Slic3r::GUI::ConfigWizard::SP_WELCOME.
Referenced by config_wizard_startup().
save_mode()
void Slic3r::GUI::GUI_App::save_mode (const int mode)
{
    //BBS
    const std::string mode_str = mode == comAdvanced ? "advanced" :
                                 mode == comSimple ? "simple" :
                                 mode == comDevelop ? "develop" : "simple";
    app_config->set("user_mode", mode_str);
    update_mode();
}
References app_config, Slic3r::comAdvanced, Slic3r::comDevelop, Slic3r::comSimple, Slic3r::AppConfig::set(), and update_mode().
select_language()
bool Slic3r::GUI::GUI_App::select_language () private
{
  wxArrayString translations = wxTranslations::Get()->GetAvailableTranslations(SLIC3R_APP_KEY);
    std::vector<const wxLanguageInfo*> language_infos;
    language_infos.emplace_back(wxLocale::GetLanguageInfo(wxLANGUAGE_ENGLISH));
    for (size_t i = 0; i < translations.GetCount(); ++ i) {
      const wxLanguageInfo *langinfo = wxLocale::FindLanguageInfo(translations[i]);
        if (langinfo != nullptr)
            language_infos.emplace_back(langinfo);
    }
    sort_remove_duplicates(language_infos);
  std::sort(language_infos.begin(), language_infos.end(), [](const wxLanguageInfo* l, const wxLanguageInfo* r) { return l->Description < r->Description; });
    wxArrayString names;
    names.Alloc(language_infos.size());
    // Some valid language should be selected since the application start up.
    const wxLanguage current_language = wxLanguage(m_wxLocale->GetLanguage());
    int          init_selection       = -1;
    int        init_selection_alt     = -1;
    int        init_selection_default = -1;
    for (size_t i = 0; i < language_infos.size(); ++ i) {
        if (wxLanguage(language_infos[i]->Language) == current_language)
          // The dictionary matches the active language and country.
            init_selection = i;
        else if ((language_infos[i]->CanonicalName.BeforeFirst('_') == m_wxLocale->GetCanonicalName().BeforeFirst('_')) ||
             // if the active language is Slovak, mark the Czech language as active.
               (language_infos[i]->CanonicalName.BeforeFirst('_') == "cs" && m_wxLocale->GetCanonicalName().BeforeFirst('_') == "sk"))
          // The dictionary matches the active language, it does not necessarily match the country.
          init_selection_alt = i;
        if (language_infos[i]->CanonicalName.BeforeFirst('_') == "en")
          // This will be the default selection if the active language does not match any dictionary.
          init_selection_default = i;
        names.Add(language_infos[i]->Description);
    }
    if (init_selection == -1)
      // This is the dictionary matching the active language.
      init_selection = init_selection_alt;
    if (init_selection != -1)
      // This is the language to highlight in the choice dialog initially.
      init_selection_default = init_selection;
    const long index = GetSingleChoiceIndex(_L("Select the language"), _L("Language"), names, init_selection_default);
  // Try to load a new language.
    if (index != -1 && (init_selection == -1 || init_selection != index)) {
      const wxLanguageInfo *new_language_info = language_infos[index];
      if (this->load_language(new_language_info->CanonicalName, false)) {
      // Save language at application config.
            // Which language to save as the selected dictionary language?
            // 1) Hopefully the language set to wxTranslations by this->load_language(), but that API is weird and we don't want to rely on its
            //    stability in the future:
            //    wxTranslations::Get()->GetBestTranslation(SLIC3R_APP_KEY, wxLANGUAGE_ENGLISH);
            // 2) Current locale language may not match the dictionary name, see GH issue #3901
            //    m_wxLocale->GetCanonicalName()
            // 3) new_language_info->CanonicalName is a safe bet. It points to a valid dictionary name.
      app_config->set("language", new_language_info->CanonicalName.ToUTF8().data());
        return true;
      }
    }
    return false;
}
References _L, app_config, GetSingleChoiceIndex(), load_language(), m_wxLocale, Slic3r::AppConfig::set(), and Slic3r::sort_remove_duplicates().
Referenced by switch_language().
set_adding_script_handler()
void Slic3r::GUI::GUI_App::set_adding_script_handler (bool status) inline
{ m_adding_script_handler = status; }
References m_adding_script_handler.
set_auto_toolbar_icon_scale()
void Slic3r::GUI::GUI_App::set_auto_toolbar_icon_scale (float scale) const
{
#ifdef __APPLE__
    const float icon_sc = 1.0f; // for Retina display will be used its own scale
#else
    const float icon_sc = m_em_unit * 0.1f;
#endif // __APPLE__
    long int_val = std::min(int(std::lround(scale / icon_sc * 100)), 100);
    std::string val = std::to_string(int_val);
    app_config->set("toolkit_size", val);
}
References app_config, m_em_unit, scale(), and Slic3r::AppConfig::set().
set_download_model_name()
void Slic3r::GUI::GUI_App::set_download_model_name (std::string name) inline
{m_mall_model_download_name = name;}
References m_mall_model_download_name.
set_download_model_url()
void Slic3r::GUI::GUI_App::set_download_model_url (std::string url) inline
{m_mall_model_download_url = url;}
References m_mall_model_download_url.
set_label_clr_modified()
void Slic3r::GUI::GUI_App::set_label_clr_modified (const wxColour & clr)
{
    return;
    //BBS
    /*
    if (m_color_label_modified == clr)
        return;
    m_color_label_modified = clr;
    auto clr_str = wxString::Format(wxT("#%02X%02X%02X"), clr.Red(), clr.Green(), clr.Blue());
    std::string str = clr_str.ToStdString();
    app_config->save();
    */
}
set_label_clr_sys()
void Slic3r::GUI::GUI_App::set_label_clr_sys (const wxColour & clr)
{
    return;
    //BBS
    /*
    if (m_color_label_sys == clr)
        return;
    m_color_label_sys = clr;
    auto clr_str = wxString::Format(wxT("#%02X%02X%02X"), clr.Red(), clr.Green(), clr.Blue());
    std::string str = clr_str.ToStdString();
    app_config->save();
    */
}
set_show_gcode_window()
void Slic3r::GUI::GUI_App::set_show_gcode_window (bool val) inline
{ m_show_gcode_window = val; }
References m_show_gcode_window.
set_side_menu_popup_status()
void Slic3r::GUI::GUI_App::set_side_menu_popup_status (bool status)
{
    m_side_popup_status = status;
}
References m_side_popup_status.
set_skip_version()
void Slic3r::GUI::GUI_App::set_skip_version (bool skip = true)
{
    BOOST_LOG_TRIVIAL(info) << "set_skip_version, skip = " << skip << ", version = " <<version_info.version_str;
    if (skip) {
        app_config->set("skip_version", version_info.version_str);
    }else {
        app_config->set("skip_version", "");
    }
}
References app_config, Slic3r::AppConfig::set(), version_info, and Slic3r::GUI::VersionInfo::version_str.
show_check_privacy_dlg()
void Slic3r::GUI::GUI_App::show_check_privacy_dlg (wxCommandEvent & evt)
{
    int online_login = evt.GetInt();
    PrivacyUpdateDialog privacy_dlg(this->mainframe, wxID_ANY, _L("Privacy Policy Update"));
    privacy_dlg.Bind(EVT_PRIVACY_UPDATE_CONFIRM, [this, online_login](wxCommandEvent &e) {
        app_config->set("privacy_version", privacy_version_info.version_str);
        app_config->set_bool("privacy_update_checked", true);
        request_user_handle(online_login);
        });
    privacy_dlg.Bind(EVT_PRIVACY_UPDATE_CANCEL, [this](wxCommandEvent &e) {
            app_config->set_bool("privacy_update_checked", false);
            if (m_agent) {
                m_agent->user_logout();
            }
        });
    privacy_dlg.set_text(privacy_version_info.description);
    privacy_dlg.on_show();
}
References _L, app_config, Slic3r::GUI::VersionInfo::description, m_agent, mainframe, Slic3r::GUI::PrivacyUpdateDialog::on_show(), privacy_version_info, request_user_handle(), Slic3r::AppConfig::set(), Slic3r::AppConfig::set_bool(), Slic3r::GUI::PrivacyUpdateDialog::set_text(), Slic3r::NetworkAgent::user_logout(), and Slic3r::GUI::VersionInfo::version_str.
show_desktop_integration_dialog()
void Slic3r::GUI::GUI_App::show_desktop_integration_dialog ()
{
#ifdef __linux__
    //wxCHECK_MSG(mainframe != nullptr, false, "Internal error: Main frame not created / null");
    DesktopIntegrationDialog dialog(mainframe);
    dialog.ShowModal();
#endif //__linux__
}
References mainframe.
show_dialog()
void Slic3r::GUI::GUI_App::show_dialog (wxString msg)
{
    wxCommandEvent* evt = new wxCommandEvent(EVT_SHOW_DIALOG);
    evt->SetString(msg);
    GUI::wxGetApp().QueueEvent(evt);
}
show_gcode_window()
bool Slic3r::GUI::GUI_App::show_gcode_window () const inline
{ return m_show_gcode_window; }
References m_show_gcode_window.
show_ip_address_enter_dialog()
void Slic3r::GUI::GUI_App::show_ip_address_enter_dialog (wxString title = wxEmptyString)
{
    auto evt = new wxCommandEvent(EVT_SHOW_IP_DIALOG);
    evt->SetString(title);
    wxQueueEvent(this, evt);
}
show_ip_address_enter_dialog_handler()
void Slic3r::GUI::GUI_App::show_ip_address_enter_dialog_handler (wxCommandEvent & evt)
{
    wxString title = evt.GetString();
    show_modal_ip_address_enter_dialog(title);
}
References show_modal_ip_address_enter_dialog().
show_message_box()
void Slic3r::GUI::GUI_App::show_message_box (std::string msg) inline
{ wxMessageBox(msg); }
show_modal_ip_address_enter_dialog()
bool Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog (wxString title = wxEmptyString)
{
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return false;
    if (!dev->get_selected_machine()) return false;
    auto obj = dev->get_selected_machine();
    InputIpAddressDialog dlg(nullptr);
    dlg.set_machine_obj(obj);
    if (!title.empty()) dlg.update_title(title);
    dlg.Bind(EVT_ENTER_IP_ADDRESS, [this, obj](wxCommandEvent& e) {
        auto selection_data_arr = wxSplit(e.GetString().ToStdString(), '|');
        if (selection_data_arr.size() == 2) {
            auto ip_address = selection_data_arr[0];
            auto access_code = selection_data_arr[1];
            BOOST_LOG_TRIVIAL(info) << "User enter IP address is " << ip_address;
            if (!ip_address.empty()) {
                wxGetApp().app_config->set_str("ip_address", obj->dev_id, ip_address.ToStdString());
                wxGetApp().app_config->save();
                obj->dev_ip = ip_address.ToStdString();
                obj->set_user_access_code(access_code.ToStdString());
            }
        }
    });
    if (dlg.ShowModal() == wxID_YES) {
        return true;
    }
    return false;
}
References Slic3r::DeviceManager::get_selected_machine(), Slic3r::GUI::InputIpAddressDialog::set_machine_obj(), Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::GUI::InputIpAddressDialog::update_title().
Referenced by show_ip_address_enter_dialog_handler().
ShowDownNetPluginDlg()
void Slic3r::GUI::GUI_App::ShowDownNetPluginDlg ()
{
    try {
        auto iter = std::find_if(dialogStack.begin(), dialogStack.end(), [](auto dialog) {
            return dynamic_cast<DownloadProgressDialog *>(dialog) != nullptr;
        });
        if (iter != dialogStack.end())
            return;
        DownloadProgressDialog dlg(_L("Downloading Bambu Network Plug-in"));
        dlg.ShowModal();
    } catch (std::exception &e) {
        ;
    }
}
References _L, Slic3r::GUI::dialogStack, and Slic3r::GUI::DPIAware< P >::ShowModal().
ShowOnlyFilament()
void Slic3r::GUI::GUI_App::ShowOnlyFilament ()
{
    // BBS:Show NewUser Guide
    try {
        bool       res = false;
        GuideFrame GuideDlg(this);
        GuideDlg.SetStartPage(GuideFrame::GuidePage::BBL_FILAMENT_ONLY);
        res = GuideDlg.run();
        if (res) {
            load_current_presets();
            // BBS: remove SLA related message
        }
    } catch (std::exception &e) {
        // wxMessageBox(e.what(), "", MB_OK);
    }
}
References Slic3r::GUI::GuideFrame::BBL_FILAMENT_ONLY, load_current_presets(), Slic3r::GUI::GuideFrame::run(), and Slic3r::GUI::GuideFrame::SetStartPage().
ShowUserGuide()
void Slic3r::GUI::GUI_App::ShowUserGuide ()
{
    // BBS:Show NewUser Guide
    try {
        bool res = false;
        GuideFrame GuideDlg(this);
        //if (GuideDlg.IsFirstUse())
        res = GuideDlg.run();
        if (res) {
            load_current_presets();
            // BBS: remove SLA related message
        }
    } catch (std::exception &e) {
        // wxMessageBox(e.what(), "", MB_OK);
    }
}
References load_current_presets(), and Slic3r::GUI::GuideFrame::run().
ShowUserLogin()
void Slic3r::GUI::GUI_App::ShowUserLogin (bool show = true)
{
    // BBS: User Login Dialog
    if (show) {
        try {
            if (!login_dlg)
                login_dlg = new ZUserLogin();
            else {
                delete login_dlg;
                login_dlg = new ZUserLogin();
            }
            login_dlg->ShowModal();
        } catch (std::exception &e) {
            ;
        }
    } else {
        if (login_dlg)
            login_dlg->EndModal(wxID_OK);
    }
}
References login_dlg.
Referenced by check_login(), and request_login().
shutdown()
void Slic3r::GUI::GUI_App::shutdown ()
{
    BOOST_LOG_TRIVIAL(info) << "GUI_App::shutdown enter";
  if (m_removable_drive_manager) {
    removable_drive_manager()->shutdown();
  }
    // destroy login dialog
    if (login_dlg != nullptr) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": destroy login dialog");
        delete login_dlg;
        login_dlg = nullptr;
    }
    if (m_is_recreating_gui) return;
    m_is_closing = true;
    stop_sync_user_preset();
    if (m_device_manager) {
        delete m_device_manager;
        m_device_manager = nullptr;
    }
    if (m_agent) {
        //BBS avoid a crash on mac platform
#ifdef __WINDOWS__
        m_agent->start_discovery(false, false);
#endif
        delete m_agent;
        m_agent = nullptr;
    }
    BOOST_LOG_TRIVIAL(info) << "GUI_App::shutdown exit";
}
References login_dlg, m_agent, m_device_manager, m_is_closing, m_is_recreating_gui, m_removable_drive_manager, removable_drive_manager(), Slic3r::GUI::RemovableDriveManager::shutdown(), Slic3r::NetworkAgent::start_discovery(), and stop_sync_user_preset().
sidebar()
Sidebar & Slic3r::GUI::GUI_App::sidebar ()
{
    return plater_->sidebar();
}
References plater_, and Slic3r::GUI::Plater::sidebar().
Referenced by obj_layers(), obj_list(), obj_settings(), recreate_GUI(), and update_mode().
small_font()
const wxFont & Slic3r::GUI::GUI_App::small_font () inline
{ return m_small_font; }
References m_small_font.
start_http_server()
void Slic3r::GUI::GUI_App::start_http_server ()
{
    if (!m_http_server.is_started())
        m_http_server.start();
}
References Slic3r::GUI::HttpServer::is_started(), m_http_server, and Slic3r::GUI::HttpServer::start().
start_sync_user_preset()
void Slic3r::GUI::GUI_App::start_sync_user_preset (bool load_immediately = false, bool with_progress_dlg = false)
{
    if (!m_agent || !m_agent->is_user_login()) return;
    if (load_immediately)
        remove_user_presets();
    enable_user_preset_folder(true);
    // has already start sync
    if (enable_sync)
        return;
    if (load_immediately) {
        preset_bundle->load_user_presets(m_agent->get_user_id(), ForwardCompatibilitySubstitutionRule::Enable);
        mainframe->update_side_preset_ui();
    }
    ProgressFn progressFn;
    WasCancelledFn cancelFn;
    std::function<void()> finishFn;
    if (with_progress_dlg) {
        auto dlg = new ProgressDialog(_L("Loading"), "", 100, this->mainframe, wxPD_AUTO_HIDE | wxPD_APP_MODAL | wxPD_CAN_ABORT);
        dlg->Update(0, _L("Loading user preset"));
        progressFn = [this, dlg](int percent) {
            CallAfter([=]{
                dlg->Update(percent, _L("Loading user preset"));
            });
        };
        cancelFn = [dlg]() {
            return dlg->WasCanceled();
        };
        finishFn = [this, dlg] {
            CallAfter([=]{
                dlg->Destroy();
                reload_settings();
            });
        };
    }
    else {
        finishFn = [this] {
            CallAfter([=] {
                reload_settings();
            });
        };
    }
    BOOST_LOG_TRIVIAL(info) << "start_sync_service...";
    //BBS
    enable_sync = true;
    m_sync_update_thread = Slic3r::create_thread(
        [this, progressFn, cancelFn, finishFn] {
            // get setting list, update setting list
            std::string version = preset_bundle->get_vendor_profile_version(PresetBundle::BBL_BUNDLE).to_string();
            m_agent->get_setting_list(version, progressFn, cancelFn);
            finishFn();
            int count = 0, sync_count = 0;
            std::vector<Preset> presets_to_sync;
            while (enable_sync) {
                count++;
                if (count % 20 == 0) {
                    if (m_agent) {
                        if (!m_agent->is_user_login()) {
                            continue;
                        }
                        //sync preset
                        if (!preset_bundle) continue;
                        sync_count = preset_bundle->prints.get_user_presets(presets_to_sync);
                        if (sync_count > 0) {
                            for (Preset& preset : presets_to_sync) {
                                sync_preset(&preset);
                            }
                        }
                        sync_count = preset_bundle->filaments.get_user_presets(presets_to_sync);
                        if (sync_count > 0) {
                            for (Preset& preset : presets_to_sync) {
                                sync_preset(&preset);
                            }
                        }
                        sync_count = preset_bundle->printers.get_user_presets(presets_to_sync);
                        if (sync_count > 0) {
                            for (Preset& preset : presets_to_sync) {
                                sync_preset(&preset);
                            }
                        }
                        unsigned int http_code = 200;
                        /* get list witch need to be deleted*/
                        std::vector<string> delete_cache_presets = get_delete_cache_presets_lock();
                        for (auto it = delete_cache_presets.begin(); it != delete_cache_presets.end();) {
                            if ((*it).empty()) continue;
                            std::string del_setting_id = *it;
                            int result = m_agent->delete_setting(del_setting_id);
                            if (result == 0) {
                                preset_deleted_from_cloud(del_setting_id);
                                it = delete_cache_presets.erase(it);
                                BOOST_LOG_TRIVIAL(trace) << "sync_preset: sync operation: delete success! setting id = " << del_setting_id;
                            }
                            else {
                                BOOST_LOG_TRIVIAL(info) << "delete setting = " <<del_setting_id << " failed";
                                it++;
                            }
                        }
                    }
                } else {
                    boost::this_thread::sleep_for(boost::chrono::milliseconds(100));
                }
            }
        });
}
References _L, Slic3r::PresetBundle::BBL_BUNDLE, count, Slic3r::create_thread(), Slic3r::NetworkAgent::delete_setting(), Slic3r::Enable, enable_sync, enable_user_preset_folder(), Slic3r::PresetBundle::filaments, get_delete_cache_presets_lock(), Slic3r::NetworkAgent::get_setting_list(), Slic3r::NetworkAgent::get_user_id(), Slic3r::PresetCollection::get_user_presets(), Slic3r::PresetBundle::get_vendor_profile_version(), Slic3r::NetworkAgent::is_user_login(), Slic3r::PresetBundle::load_user_presets(), m_agent, m_sync_update_thread, mainframe, preset_bundle, preset_deleted_from_cloud(), Slic3r::PresetBundle::printers, Slic3r::PresetBundle::prints, reload_settings(), remove_user_presets(), sync_preset(), Slic3r::to_string(), Slic3r::trace(), Slic3r::GUI::MainFrame::update_side_preset_ui(), and void().
Referenced by restart_networking().
stop_http_server()
void Slic3r::GUI::GUI_App::stop_http_server ()
{
    m_http_server.stop();
}
References m_http_server, and Slic3r::GUI::HttpServer::stop().
stop_sync_user_preset()
void Slic3r::GUI::GUI_App::stop_sync_user_preset ()
{
    if (!wxGetApp().m_is_closing)
        remove_user_presets();
    enable_user_preset_folder(false);
    preset_bundle->load_user_presets(DEFAULT_USER_FOLDER_NAME, ForwardCompatibilitySubstitutionRule::Enable);
    mainframe->update_side_preset_ui();
    if (!enable_sync)
        return;
    enable_sync = false;
    if (m_sync_update_thread.joinable())
        m_sync_update_thread.join();
}
References DEFAULT_USER_FOLDER_NAME, Slic3r::Enable, enable_sync, enable_user_preset_folder(), Slic3r::PresetBundle::load_user_presets(), m_is_closing, m_sync_update_thread, mainframe, preset_bundle, remove_user_presets(), and Slic3r::GUI::MainFrame::update_side_preset_ui().
Referenced by shutdown().
switch_language()
bool Slic3r::GUI::GUI_App::switch_language ()
{
    if (select_language()) {
        recreate_GUI(_L("Switching application language") + dots);
        return true;
    } else {
        return false;
    }
}
References _L, Slic3r::GUI::dots(), recreate_GUI(), and select_language().
sync_preset()
void Slic3r::GUI::GUI_App::sync_preset (Preset * preset)
{
    int result = -1;
    unsigned int http_code = 200;
    std::string updated_info;
    // only sync user's preset
    if (!preset->is_user()) return;
    if (preset->is_custom_defined()) return;
    if (preset->setting_id.empty() && preset->sync_info.empty() && !preset->base_id.empty()) {
        std::map<std::string, std::string> values_map;
        int ret = preset_bundle->get_differed_values_to_update(*preset, values_map);
        if (!ret) {
            std::string new_setting_id = m_agent->request_setting_id(preset->name, &values_map, &http_code);
            if (!new_setting_id.empty()) {
                preset->setting_id = new_setting_id;
                result = 0;
            }
            else {
                BOOST_LOG_TRIVIAL(trace) << "[sync_preset]init: request_setting_id failed, http code "<<http_code;
                // do not post new preset this time if http code >= 400
                if (http_code >= 400) {
                    result = 0;
                    updated_info = "hold";
                }
                else
                    result = -1;
            }
        }
        else {
            BOOST_LOG_TRIVIAL(trace) << "[sync_preset]init: can not generate differed key-values";
            result = 0;
            updated_info = "hold";
        }
    }
    else if ((preset->sync_info.compare("create") == 0) && !preset->base_id.empty()) {
        std::map<std::string, std::string> values_map;
        int ret = preset_bundle->get_differed_values_to_update(*preset, values_map);
        if (!ret) {
            std::string new_setting_id = m_agent->request_setting_id(preset->name, &values_map, &http_code);
            if (!new_setting_id.empty()) {
                preset->setting_id = new_setting_id;
                result = 0;
            }
            else {
                BOOST_LOG_TRIVIAL(trace) << "[sync_preset]create: request_setting_id failed, http code "<<http_code;
                // do not post new preset this time if http code >= 400
                if (http_code >= 400) {
                    result = 0;
                    updated_info = "hold";
                }
                else
                    result = -1;
            }
        }
        else {
            BOOST_LOG_TRIVIAL(trace) << "[sync_preset]create: can not generate differed preset";
        }
    }
    else if ((preset->sync_info.compare("update") == 0) && !preset->base_id.empty()) {
        if (!preset->setting_id.empty()) {
            std::map<std::string, std::string> values_map;
            int ret = preset_bundle->get_differed_values_to_update(*preset, values_map);
            if (!ret) {
                if (values_map[BBL_JSON_KEY_BASE_ID] ==  preset->setting_id) {
                    //clear the setting_id in this case
                    preset->setting_id.clear();
                    result = 0;
                }
                else {
                    result = m_agent->put_setting(preset->setting_id, preset->name, &values_map, &http_code);
                    if (http_code >= 400) {
                        result = 0;
                        updated_info = "hold";
                        BOOST_LOG_TRIVIAL(error) << "[sync_preset] put setting_id = " << preset->setting_id << " failed, http_code = " << http_code;
                    }
                }
            }
            else {
                BOOST_LOG_TRIVIAL(trace) << "[sync_preset]update: can not generate differed key-values, we need to skip this preset "<< preset->name;
                result = 0;
            }
        }
        else {
            //clear the sync_info
            result = 0;
        }
    }
    //update sync_info preset info in file
    if (result == 0) {
        //PresetBundle* preset_bundle = wxGetApp().preset_bundle;
        if (!this->preset_bundle) return;
        BOOST_LOG_TRIVIAL(trace) << "sync_preset: sync operation: " << preset->sync_info << " success! preset = " << preset->name;
        if (preset->type == Preset::Type::TYPE_FILAMENT) {
            preset_bundle->filaments.set_sync_info_and_save(preset->name, preset->setting_id, updated_info);
        } else if (preset->type == Preset::Type::TYPE_PRINT) {
            preset_bundle->prints.set_sync_info_and_save(preset->name, preset->setting_id, updated_info);
        } else if (preset->type == Preset::Type::TYPE_PRINTER) {
            preset_bundle->printers.set_sync_info_and_save(preset->name, preset->setting_id, updated_info);
        }
    }
}
References Slic3r::Preset::base_id, BBL_JSON_KEY_BASE_ID, error, Slic3r::PresetBundle::filaments, Slic3r::PresetBundle::get_differed_values_to_update(), Slic3r::Preset::is_custom_defined(), Slic3r::Preset::is_user(), m_agent, Slic3r::Preset::name, preset_bundle, Slic3r::PresetBundle::printers, Slic3r::PresetBundle::prints, Slic3r::NetworkAgent::put_setting(), Slic3r::NetworkAgent::request_setting_id(), Slic3r::PresetCollection::set_sync_info_and_save(), Slic3r::Preset::setting_id, Slic3r::Preset::sync_info, Slic3r::trace(), Slic3r::Preset::type, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, and Slic3r::Preset::TYPE_PRINTER.
Referenced by start_sync_user_preset().
system_info()
void Slic3r::GUI::GUI_App::system_info ()
{
    //SysInfoDialog dlg;
    //dlg.ShowModal();
}
tab_panel()
Notebook * Slic3r::GUI::GUI_App::tab_panel () const
{
    if (mainframe)
        return mainframe->m_tabpanel;
    return nullptr;
}
References Slic3r::GUI::MainFrame::m_tabpanel, and mainframe.
tabs_as_menu()
bool Slic3r::GUI::GUI_App::tabs_as_menu () const
{
    return false;
}
Referenced by update_mode().
toolbar_icon_scale()
float Slic3r::GUI::GUI_App::toolbar_icon_scale (const bool is_limited = false) const
{
#ifdef __APPLE__
    const float icon_sc = 1.0f; // for Retina display will be used its own scale
#else
    const float icon_sc = m_em_unit * 0.1f;
#endif // __APPLE__
    //return icon_sc;
    const std::string& auto_val = app_config->get("toolkit_size");
    if (auto_val.empty())
        return icon_sc;
    int int_val =  100;
    // correct value in respect to toolkit_size
    int_val = std::min(atoi(auto_val.c_str()), int_val);
    if (is_limited && int_val < 50)
        int_val = 50;
    return 0.01f * int_val * icon_sc;
}
References app_config, Slic3r::AppConfig::get(), and m_em_unit.
transition_tridid()
wxString Slic3r::GUI::GUI_App::transition_tridid (int trid_id)
{
    wxString maping_dict[8] = { "A", "B", "C", "D", "E", "F", "G" };
    int id_index = ceil(trid_id / 4);
    int id_suffix = (trid_id + 1) % 4 == 0 ? 4 : (trid_id + 1) % 4;
    return wxString::Format("%s%d", maping_dict[id_index], id_suffix);
}
References ceil().
Update_dark_mode_flag()
void Slic3r::GUI::GUI_App::Update_dark_mode_flag ()
{
    m_is_dark_mode = dark_mode();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": switch the current dark mode status to %1% ")%m_is_dark_mode;
}
References dark_mode(), and m_is_dark_mode.
update_fonts()
void Slic3r::GUI::GUI_App::update_fonts (const MainFrame * main_frame = nullptr)
{
    /* Only normal and bold fonts are used for an application rescale,
     * because of under MSW small and normal fonts are the same.
     * To avoid same rescaling twice, just fill this values
     * from rescaled MainFrame
     */
  if (main_frame == nullptr)
    main_frame = this->mainframe;
    m_normal_font   = Label::Body_14; // BBS: larger font size
    m_small_font    = m_normal_font;
    m_bold_font     = m_normal_font.Bold();
    m_link_font     = m_bold_font.Underlined();
    m_em_unit       = main_frame->em_unit();
    m_code_font.SetPointSize(m_small_font.GetPointSize());
}
References Label::Body_14, Slic3r::GUI::DPIAware< P >::em_unit(), m_bold_font, m_code_font, m_em_unit, m_link_font, m_normal_font, m_small_font, and mainframe.
update_http_extra_header()
void Slic3r::GUI::GUI_App::update_http_extra_header () private
{
    std::map<std::string, std::string> extra_headers = get_extra_header();
    Slic3r::Http::set_extra_headers(extra_headers);
    if (m_agent)
        m_agent->set_extra_http_header(extra_headers);
}
References Slic3r::extra_headers, get_extra_header(), m_agent, Slic3r::Http::set_extra_headers(), and Slic3r::NetworkAgent::set_extra_http_header().
Referenced by check_privacy_version().
update_label_colours()
void Slic3r::GUI::GUI_App::update_label_colours ()
{
    for (Tab* tab : tabs_list)
        tab->update_label_colours();
}
References tabs_list.
Referenced by update_ui_from_settings().
update_label_colours_from_appconfig()
void Slic3r::GUI::GUI_App::update_label_colours_from_appconfig ()
{
    if (app_config->has("label_clr_sys")) {
        auto str = app_config->get("label_clr_sys");
        if (str != "")
            m_color_label_sys = wxColour(str);
    }
    if (app_config->has("label_clr_modified")) {
        auto str = app_config->get("label_clr_modified");
        if (str != "")
            m_color_label_modified = wxColour(str);
    }
}
References app_config, Slic3r::AppConfig::get(), Slic3r::AppConfig::has(), m_color_label_modified, and m_color_label_sys.
update_mode()
void Slic3r::GUI::GUI_App::update_mode ()
{
    sidebar().update_mode();
    //BBS: GUI refactor
    if (mainframe->m_param_panel)
        mainframe->m_param_panel->update_mode();
    if (mainframe->m_param_dialog)
        mainframe->m_param_dialog->panel()->update_mode();
    mainframe->m_webview->update_mode();
#ifdef _MSW_DARK_MODE
    if (!wxGetApp().tabs_as_menu())
        dynamic_cast<Notebook*>(mainframe->m_tabpanel)->UpdateMode();
#endif
    for (auto tab : tabs_list)
        tab->update_mode();
    for (auto tab : model_tabs_list)
        tab->update_mode();
    //BBS plater()->update_menus();
    plater()->canvas3D()->update_gizmos_on_off_state();
}
References Slic3r::GUI::Plater::canvas3D(), Slic3r::GUI::MainFrame::m_param_dialog, Slic3r::GUI::MainFrame::m_param_panel, Slic3r::GUI::MainFrame::m_tabpanel, Slic3r::GUI::MainFrame::m_webview, mainframe, model_tabs_list, Slic3r::GUI::ParamsDialog::panel(), plater(), sidebar(), tabs_as_menu(), tabs_list, Slic3r::GUI::GLCanvas3D::update_gizmos_on_off_state(), Slic3r::GUI::ParamsPanel::update_mode(), Slic3r::GUI::Sidebar::update_mode(), and Slic3r::GUI::WebViewPanel::update_mode().
Referenced by recreate_GUI(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), and save_mode().
update_saved_preset_from_current_preset()
void Slic3r::GUI::GUI_App::update_saved_preset_from_current_preset ()
{
    PrinterTechnology printer_technology = preset_bundle->printers.get_edited_preset().printer_technology();
    for (Tab* tab : tabs_list) {
        if (tab->supports_printer_technology(printer_technology))
            tab->update_saved_preset_from_current_preset();
    }
}
References Slic3r::PresetCollection::get_edited_preset(), preset_bundle, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, and tabs_list.
update_ui_from_settings()
void Slic3r::GUI::GUI_App::update_ui_from_settings ()
{
    update_label_colours();
    // Upadte UI colors before Update UI from settings
    if (m_force_colors_update) {
        m_force_colors_update = false;
        //UpdateDlgDarkUI(&mainframe->m_settings_dialog);
        //mainframe->m_settings_dialog.Refresh();
        //mainframe->m_settings_dialog.Update();
        if (mainframe) {
#ifdef __WINDOWS__
            mainframe->force_color_changed();
            update_scrolls(mainframe);
            update_scrolls(&mainframe->m_settings_dialog);
#endif //_MSW_DARK_MODE
            update_dark_children_ui(mainframe);
        }
    }
    if (mainframe) {mainframe->update_ui_from_settings();}
}
References m_force_colors_update, Slic3r::GUI::MainFrame::m_settings_dialog, mainframe, Slic3r::GUI::update_dark_children_ui(), update_label_colours(), and Slic3r::GUI::MainFrame::update_ui_from_settings().
UpdateAllStaticTextDarkUI()
void Slic3r::GUI::GUI_App::UpdateAllStaticTextDarkUI (wxWindow * parent)
{
#ifdef __WINDOWS__
    wxGetApp().UpdateDarkUI(parent);
    auto children = parent->GetChildren();
    for (auto child : children) {
        if (dynamic_cast<wxStaticText*>(child))
            child->SetForegroundColour(m_color_label_default);
    }
#endif
}
References m_color_label_default, and wxStaticText.
UpdateDarkUI()
void Slic3r::GUI::GUI_App::UpdateDarkUI (wxWindow * window, bool highlited = false, bool just_font = false)
{
    if (wxButton *btn = dynamic_cast<wxButton*>(window)) {
        if (btn->GetWindowStyleFlag() & wxBU_AUTODRAW)
            return;
        else {
#ifdef _WIN32
            if (btn->GetId() == wxID_OK || btn->GetId() == wxID_CANCEL) {
                bool is_focused_button = false;
                bool is_default_button = false;
                if (!(btn->GetWindowStyle() & wxNO_BORDER)) {
                    btn->SetWindowStyle(btn->GetWindowStyle() | wxNO_BORDER);
                    highlited = true;
                }
                auto mark_button = [this, btn, highlited](const bool mark) {
                    btn->SetBackgroundColour(mark ? m_color_selected_btn_bg : highlited ? m_color_highlight_default : m_color_window_default);
                    btn->SetForegroundColour(mark ? m_color_hovered_btn_label :m_color_default_btn_label);
                    btn->Refresh();
                    btn->Update();
                };
                // hovering
                btn->Bind(wxEVT_ENTER_WINDOW, [mark_button](wxMouseEvent& event) { mark_button(true); event.Skip(); });
                btn->Bind(wxEVT_LEAVE_WINDOW, [mark_button, btn](wxMouseEvent& event) { mark_button(is_focused(btn->GetHWND())); event.Skip(); });
                // focusing
                btn->Bind(wxEVT_SET_FOCUS, [mark_button](wxFocusEvent& event) { mark_button(true); event.Skip(); });
                btn->Bind(wxEVT_KILL_FOCUS, [mark_button](wxFocusEvent& event) { mark_button(false); event.Skip(); });
                is_focused_button = is_focused(btn->GetHWND());
                is_default_button = is_default(btn);
                mark_button(is_focused_button);
            }
#endif
        }
    }
    if (Button* btn = dynamic_cast<Button*>(window)) {
        if (btn->GetWindowStyleFlag() & wxBU_AUTODRAW)
            return;
    }
    /*if (m_is_dark_mode != dark_mode() )
        m_is_dark_mode = dark_mode();*/
    if (m_is_dark_mode) {
        auto original_col = window->GetBackgroundColour();
        auto bg_col = StateColor::darkModeColorFor(original_col);
        if (bg_col != original_col) {
            window->SetBackgroundColour(bg_col);
        }
        original_col = window->GetForegroundColour();
        auto fg_col = StateColor::darkModeColorFor(original_col);
        if (fg_col != original_col) {
            window->SetForegroundColour(fg_col);
        }
    }
    else {
        auto original_col = window->GetBackgroundColour();
        auto bg_col = StateColor::lightModeColorFor(original_col);
        if (bg_col != original_col) {
            window->SetBackgroundColour(bg_col);
        }
        original_col = window->GetForegroundColour();
        auto fg_col = StateColor::lightModeColorFor(original_col);
        if (fg_col != original_col) {
            window->SetForegroundColour(fg_col);
        }
    }
}
References StateColor::darkModeColorFor(), StateColor::lightModeColorFor(), m_color_default_btn_label, m_color_highlight_default, m_color_hovered_btn_label, m_color_selected_btn_bg, m_color_window_default, m_is_dark_mode, wxButton, and Slic3r::GUI::wxMouseEvent.
Referenced by UpdateDVCDarkUI().
UpdateDarkUIWin()
void Slic3r::GUI::GUI_App::UpdateDarkUIWin (wxWindow * win)
{
    update_dark_children_ui(win);
}
References Slic3r::GUI::update_dark_children_ui().
UpdateDlgDarkUI()
void Slic3r::GUI::GUI_App::UpdateDlgDarkUI (wxDialog * dlg)
{
#ifdef __WINDOWS__
    NppDarkMode::SetDarkExplorerTheme(dlg->GetHWND());
    NppDarkMode::SetDarkTitleBar(dlg->GetHWND());
#endif
    update_dark_children_ui(dlg);
}
References NppDarkMode::SetDarkExplorerTheme(), NppDarkMode::SetDarkTitleBar(), and Slic3r::GUI::update_dark_children_ui().
UpdateDVCDarkUI()
void Slic3r::GUI::GUI_App::UpdateDVCDarkUI (wxDataViewCtrl * dvc, bool highlited = false)
{
#ifdef __WINDOWS__
    UpdateDarkUI(dvc, highlited ? dark_mode() : false);
#ifdef _MSW_DARK_MODE
    //dvc->RefreshHeaderDarkMode(&m_normal_font);
    HWND hwnd = (HWND)dvc->GenericGetHeader()->GetHandle();
    hwnd = GetWindow(hwnd, GW_CHILD);
    if (hwnd != NULL)
        NppDarkMode::SetDarkListViewHeader(hwnd);
    wxItemAttr attr;
    attr.SetTextColour(NppDarkMode::GetTextColor());
    attr.SetFont(m_normal_font);
    dvc->SetHeaderAttr(attr);
#endif //_MSW_DARK_MODE
    if (dvc->HasFlag(wxDV_ROW_LINES))
        dvc->SetAlternateRowColour(m_color_highlight_default);
    if (dvc->GetBorder() != wxBORDER_SIMPLE)
        dvc->SetWindowStyle(dvc->GetWindowStyle() | wxBORDER_SIMPLE);
#endif
}
References dark_mode(), NppDarkMode::GetTextColor(), m_color_highlight_default, m_normal_font, NULL, NppDarkMode::SetDarkListViewHeader(), and UpdateDarkUI().
UpdateFrameDarkUI()
void Slic3r::GUI::GUI_App::UpdateFrameDarkUI (wxFrame * dlg)
{
#ifdef __WINDOWS__
    NppDarkMode::SetDarkExplorerTheme(dlg->GetHWND());
    NppDarkMode::SetDarkTitleBar(dlg->GetHWND());
#endif
    update_dark_children_ui(dlg);
}
References NppDarkMode::SetDarkExplorerTheme(), NppDarkMode::SetDarkTitleBar(), and Slic3r::GUI::update_dark_children_ui().
updating_bambu_networking()
int Slic3r::GUI::GUI_App::updating_bambu_networking () private
{
    DownloadProgressDialog dlg(_L("Downloading Bambu Network Plug-in"));
    dlg.ShowModal();
    return 0;
}
References _L, and Slic3r::GUI::DPIAware< P >::ShowModal().
Referenced by post_init().
url_decode()
std::string Slic3r::GUI::GUI_App::url_decode (std::string value)
{
    return Http::url_decode(value);
}
References Slic3r::Http::url_decode().
Referenced by post_init().
url_encode()
std::string Slic3r::GUI::GUI_App::url_encode (std::string value)
{
    return Http::url_encode(value);
}
References Slic3r::Http::url_encode().
Referenced by open_mall_page_dialog(), and open_publish_page_dialog().
window_pos_center()
void Slic3r::GUI::GUI_App::window_pos_center (wxTopLevelWindow * window) private
{
    /*unsigned*/int display_idx = wxDisplay::GetFromWindow(window);
    wxRect display;
    if (display_idx == wxNOT_FOUND) {
        display = wxDisplay(0u).GetClientArea();
        window->Move(display.GetTopLeft());
    } else {
        display = wxDisplay(display_idx).GetClientArea();
    }
    auto metrics = WindowMetrics::from_window(window);
    metrics.center_for_display(display);
    if (window->GetScreenRect() != metrics.get_rect()) {
        window->SetSize(metrics.get_rect());
    }
}
References Slic3r::GUI::WindowMetrics::from_window().
Referenced by persist_window_geometry().
window_pos_restore()
bool Slic3r::GUI::GUI_App::window_pos_restore (wxTopLevelWindow * window, const std::string & name, bool default_maximized = false) private
{
    if (name.empty()) { return false; }
    const auto config_key = (boost::format("window_%1%") % name).str();
    if (! app_config->has(config_key)) {
        //window->Maximize(default_maximized);
        return false;
    }
    auto metrics = WindowMetrics::deserialize(app_config->get(config_key));
    if (! metrics) {
        window->Maximize(default_maximized);
        return true;
    }
    const wxRect& rect = metrics->get_rect();
    window->SetPosition(rect.GetPosition());
    window->SetSize(rect.GetSize());
    window->Maximize(metrics->get_maximized());
    return true;
}
References app_config, Slic3r::GUI::WindowMetrics::deserialize(), Slic3r::AppConfig::get(), and Slic3r::AppConfig::has().
Referenced by persist_window_geometry().
window_pos_sanitize()
void Slic3r::GUI::GUI_App::window_pos_sanitize (wxTopLevelWindow * window) private
{
    /*unsigned*/int display_idx = wxDisplay::GetFromWindow(window);
    wxRect display;
    if (display_idx == wxNOT_FOUND) {
        display = wxDisplay(0u).GetClientArea();
        window->Move(display.GetTopLeft());
    } else {
        display = wxDisplay(display_idx).GetClientArea();
    }
    auto metrics = WindowMetrics::from_window(window);
    metrics.sanitize_for_display(display);
    if (window->GetScreenRect() != metrics.get_rect()) {
        window->SetSize(metrics.get_rect());
    }
}
References Slic3r::GUI::WindowMetrics::from_window().
Referenced by persist_window_geometry().
window_pos_save()
void Slic3r::GUI::GUI_App::window_pos_save (wxTopLevelWindow * window, const std::string & name) private
{
    if (name.empty()) { return; }
    const auto config_key = (boost::format("window_%1%") % name).str();
    WindowMetrics metrics = WindowMetrics::from_window(window);
    app_config->set(config_key, metrics.serialize());
    app_config->save();
}
References app_config, Slic3r::GUI::WindowMetrics::from_window(), Slic3r::AppConfig::save(), Slic3r::GUI::WindowMetrics::serialize(), and Slic3r::AppConfig::set().
Referenced by persist_window_geometry().
Member Data Documentation
app_config
AppConfig* Slic3r::GUI::GUI_App::app_config { nullptr }
Referenced by ~GUI_App(), check_and_keep_current_preset_changes(), check_and_save_current_preset_changes(), check_new_version(), check_new_version_sf(), check_privacy_update(), check_privacy_version(), check_track_enable(), check_updates(), copy_network_if_available(), download_plugin(), enable_user_preset_folder(), get_extra_header(), get_mode(), import_model(), init_app_config(), init_download_path(), init_networking_callbacks(), install_plugin(), load_gcode(), load_language(), load_project(), on_init_inner(), on_init_network(), on_user_login_handle(), open_mall_page_dialog(), open_preferences(), open_publish_page_dialog(), post_init(), reload_settings(), remove_user_presets(), restart_networking(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), save_mode(), Slic3r::GUI::GuideFrame::SaveProfile(), select_language(), set_auto_toolbar_icon_scale(), set_skip_version(), show_check_privacy_dlg(), toolbar_icon_scale(), update_label_colours_from_appconfig(), window_pos_restore(), and window_pos_save().
enable_sync
bool Slic3r::GUI::GUI_App::enable_sync = false private
Referenced by start_sync_user_preset(), and stop_sync_user_preset().
hms_query
HMSQuery* Slic3r::GUI::GUI_App::hms_query { nullptr } private
Referenced by get_hms_query(), post_init(), and recreate_GUI().
init_params
GUI_InitParams* Slic3r::GUI::GUI_App::init_params { nullptr }
Referenced by Slic3r::GUI::GUI_Run(), and post_init().
last_active_point
std::chrono::system_clock::time_point Slic3r::GUI::GUI_App::last_active_point
Referenced by is_studio_active(), and reset_to_active().
login_dlg
ZUserLogin* Slic3r::GUI::GUI_App::login_dlg { nullptr } private
Referenced by ShowUserLogin(), and shutdown().
m_adding_script_handler
bool Slic3r::GUI::GUI_App::m_adding_script_handler { false } private
Referenced by is_adding_script_handler(), and set_adding_script_handler().
m_agent
NetworkAgent* Slic3r::GUI::GUI_App::m_agent { nullptr } private
Referenced by check_login(), check_track_enable(), download_plugin(), enable_user_preset_folder(), get_login_info(), getAgent(), handle_script_message(), init_http_extra_header(), init_networking_callbacks(), is_user_login(), on_http_error(), on_init_network(), on_set_selected_machine(), on_user_login(), on_user_login_handle(), post_init(), recreate_GUI(), reload_settings(), remove_user_presets(), request_user_logout(), request_user_unbind(), restart_networking(), show_check_privacy_dlg(), shutdown(), start_sync_user_preset(), sync_preset(), and update_http_extra_header().
m_app_conf_exists
bool Slic3r::GUI::GUI_App::m_app_conf_exists { false } private
Referenced by check_updates(), config_wizard_startup(), and init_app_config().
m_app_mode
EAppMode Slic3r::GUI::GUI_App::m_app_mode { EAppMode::Editor } private
Referenced by get_app_mode(), is_editor(), and is_gcode_viewer().
m_bold_font
wxFont Slic3r::GUI::GUI_App::m_bold_font private
Referenced by bold_font(), init_fonts(), and update_fonts().
m_code_font
wxFont Slic3r::GUI::GUI_App::m_code_font private
Referenced by code_font(), init_fonts(), and update_fonts().
m_color_default_btn_label
wxColour Slic3r::GUI::GUI_App::m_color_default_btn_label private
Referenced by init_label_colours(), and UpdateDarkUI().
m_color_highlight_default
wxColour Slic3r::GUI::GUI_App::m_color_highlight_default private
Referenced by get_highlight_default_clr(), init_label_colours(), UpdateDarkUI(), and UpdateDVCDarkUI().
m_color_highlight_label_default
wxColour Slic3r::GUI::GUI_App::m_color_highlight_label_default private
Referenced by get_label_highlight_clr(), and init_label_colours().
m_color_hovered_btn_label
wxColour Slic3r::GUI::GUI_App::m_color_hovered_btn_label private
Referenced by get_color_hovered_btn_label(), init_label_colours(), and UpdateDarkUI().
m_color_label_default
wxColour Slic3r::GUI::GUI_App::m_color_label_default private
Referenced by get_label_clr_default(), init_label_colours(), and UpdateAllStaticTextDarkUI().
m_color_label_modified
wxColour Slic3r::GUI::GUI_App::m_color_label_modified private
Referenced by get_label_clr_modified(), init_label_colours(), and update_label_colours_from_appconfig().
m_color_label_sys
wxColour Slic3r::GUI::GUI_App::m_color_label_sys private
Referenced by get_label_clr_sys(), init_label_colours(), and update_label_colours_from_appconfig().
m_color_selected_btn_bg
wxColour Slic3r::GUI::GUI_App::m_color_selected_btn_bg private
Referenced by get_color_selected_btn_bg(), init_label_colours(), and UpdateDarkUI().
m_color_window_default
wxColour Slic3r::GUI::GUI_App::m_color_window_default private
Referenced by get_window_default_clr(), init_label_colours(), and UpdateDarkUI().
m_datadir_redefined
bool Slic3r::GUI::GUI_App::m_datadir_redefined { false } private
Referenced by init_app_config().
m_device_manager
Slic3r::DeviceManager* Slic3r::GUI::GUI_App::m_device_manager { nullptr } private
Referenced by getDeviceManager(), init_networking_callbacks(), on_init_network(), post_init(), request_user_logout(), restart_networking(), and shutdown().
m_download_file_url
std::string Slic3r::GUI::GUI_App::m_download_file_url private
m_em_unit
int Slic3r::GUI::GUI_App::m_em_unit private
Referenced by em_unit(), get_min_size(), set_auto_toolbar_icon_scale(), toolbar_icon_scale(), and update_fonts().
m_force_colors_update
bool Slic3r::GUI::GUI_App::m_force_colors_update { false } private
Referenced by force_colors_update(), and update_ui_from_settings().
m_http_server
HttpServer Slic3r::GUI::GUI_App::m_http_server private
Referenced by start_http_server(), and stop_http_server().
m_imgui
std::unique_ptr<ImGuiWrapper> Slic3r::GUI::GUI_App::m_imgui private
Referenced by imgui(), and load_language().
m_init_app_config_from_older
bool Slic3r::GUI::GUI_App::m_init_app_config_from_older { false } private
Referenced by on_init_inner().
m_initialized
bool Slic3r::GUI::GUI_App::m_initialized { false } private
Referenced by initialized().
m_is_closing
bool Slic3r::GUI::GUI_App::m_is_closing {false} private
Referenced by init_networking_callbacks(), post_init(), restart_networking(), shutdown(), and stop_sync_user_preset().
m_is_dark_mode
bool Slic3r::GUI::GUI_App::m_is_dark_mode { false } private
Referenced by Update_dark_mode_flag(), and UpdateDarkUI().
m_is_recreating_gui
bool Slic3r::GUI::GUI_App::m_is_recreating_gui { false } private
Referenced by is_recreating_gui(), recreate_GUI(), and shutdown().
m_language_info_best
const wxLanguageInfo* Slic3r::GUI::GUI_App::m_language_info_best = nullptr private
Referenced by load_language().
m_language_info_system
const wxLanguageInfo* Slic3r::GUI::GUI_App::m_language_info_system = nullptr private
Referenced by load_language().
m_last_config_version
boost::optional<Semver> Slic3r::GUI::GUI_App::m_last_config_version private
Referenced by init_app_config(), and on_init_inner().
m_link_font
wxFont Slic3r::GUI::GUI_App::m_link_font private
Referenced by link_font(), and update_fonts().
m_mall_model_download_name
std::string Slic3r::GUI::GUI_App::m_mall_model_download_name
Referenced by get_download_model_name(), and set_download_model_name().
m_mall_model_download_url
std::string Slic3r::GUI::GUI_App::m_mall_model_download_url
Referenced by get_download_model_url(), and set_download_model_url().
m_mall_publish_dialog
ModelMallDialog* Slic3r::GUI::GUI_App::m_mall_publish_dialog { nullptr }
Referenced by remove_mall_system_dialog().
m_networking_cancel_update
bool Slic3r::GUI::GUI_App::m_networking_cancel_update { false } private
Referenced by cancel_networking_install(), download_plugin(), and install_plugin().
m_networking_compatible
bool Slic3r::GUI::GUI_App::m_networking_compatible { false } private
Referenced by check_networking_version(), is_compatibility_version(), and on_init_network().
m_networking_need_update
bool Slic3r::GUI::GUI_App::m_networking_need_update { false } private
Referenced by on_init_network(), and post_init().
m_normal_font
wxFont Slic3r::GUI::GUI_App::m_normal_font private
Referenced by init_fonts(), normal_font(), update_fonts(), and UpdateDVCDarkUI().
m_older_data_dir_path
std::string Slic3r::GUI::GUI_App::m_older_data_dir_path private
Referenced by copy_older_config().
m_opengl_mgr
OpenGLManager Slic3r::GUI::GUI_App::m_opengl_mgr private
Referenced by get_current_shader(), get_opengl_manager(), get_shader(), init_glcontext(), init_opengl(), is_gl_version_greater_or_equal_to(), and is_glsl_version_greater_or_equal_to().
m_post_initialized
bool Slic3r::GUI::GUI_App::m_post_initialized { false } private
m_printhost_job_queue
std::unique_ptr<PrintHostJobQueue> Slic3r::GUI::GUI_App::m_printhost_job_queue private
Referenced by printhost_job_queue(), and recreate_GUI().
m_removable_drive_manager
std::unique_ptr<RemovableDriveManager> Slic3r::GUI::GUI_App::m_removable_drive_manager private
Referenced by removable_drive_manager(), and shutdown().
m_show_gcode_window
bool Slic3r::GUI::GUI_App::m_show_gcode_window {true} private
Referenced by post_init(), set_show_gcode_window(), and show_gcode_window().
m_side_popup_status
bool Slic3r::GUI::GUI_App::m_side_popup_status {false} private
Referenced by get_side_menu_popup_status(), and set_side_menu_popup_status().
m_small_font
wxFont Slic3r::GUI::GUI_App::m_small_font private
Referenced by init_fonts(), small_font(), and update_fonts().
m_studio_active
bool Slic3r::GUI::GUI_App::m_studio_active = true
m_sync_update_thread
boost::thread Slic3r::GUI::GUI_App::m_sync_update_thread private
Referenced by start_sync_user_preset(), and stop_sync_user_preset().
m_upgrade_network_job
std::shared_ptr<UpgradeNetworkJob> Slic3r::GUI::GUI_App::m_upgrade_network_job private
m_wxLocale
std::unique_ptr<wxLocale> Slic3r::GUI::GUI_App::m_wxLocale private
Referenced by current_language_code(), is_localized(), load_language(), and select_language().
mainframe
MainFrame* Slic3r::GUI::GUI_App::mainframe { nullptr }
Referenced by check_print_host_queue(), check_updates(), force_colors_update(), handle_web_request(), load_url(), on_init_inner(), on_user_login_handle(), Slic3r::GUI::GuideFrame::OnScriptMessage(), open_mall_page_dialog(), open_preferences(), open_publish_page_dialog(), params_dialog(), params_panel(), post_init(), recreate_GUI(), reload_settings(), remove_user_presets(), request_open_project(), request_remove_project(), restart_networking(), run_script(), run_wizard(), show_check_privacy_dlg(), show_desktop_integration_dialog(), start_sync_user_preset(), stop_sync_user_preset(), tab_panel(), update_fonts(), Slic3r::GUI::ProjectDirtyStateManager::update_from_presets(), update_mode(), and update_ui_from_settings().
model_tabs_list
std::vector<Tab *> Slic3r::GUI::GUI_App::model_tabs_list
Referenced by checked_tab(), get_layer_tab(), get_model_tab(), load_current_presets(), and update_mode().
need_delete_presets
std::vector<std::string> Slic3r::GUI::GUI_App::need_delete_presets private
Referenced by delete_preset_from_cloud(), get_delete_cache_presets(), get_delete_cache_presets_lock(), and preset_deleted_from_cloud().
plater_
Plater* Slic3r::GUI::GUI_App::plater_ { nullptr }
Referenced by download_project(), model(), notification_manager(), on_init_inner(), open_preferences(), plater(), plater(), post_init(), recreate_GUI(), request_model_download(), restart_networking(), and sidebar().
preset_bundle
PresetBundle* Slic3r::GUI::GUI_App::preset_bundle { nullptr }
Referenced by ~GUI_App(), apply_keeped_preset_modifications(), check_and_keep_current_preset_changes(), check_and_save_current_preset_changes(), check_printer_presets(), config_wizard_startup(), copy_older_config(), extruders_cnt(), extruders_edited_cnt(), filaments_cnt(), get_selected_presets(), has_current_preset_changes(), has_unsaved_preset_changes(), load_current_presets(), on_init_inner(), post_init(), reload_settings(), remove_user_presets(), Slic3r::GUI::ProjectDirtyStateManager::reset_initial_presets(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), start_sync_user_preset(), stop_sync_user_preset(), sync_preset(), Slic3r::GUI::ProjectDirtyStateManager::update_from_presets(), and update_saved_preset_from_current_preset().
preset_updater
PresetUpdater* Slic3r::GUI::GUI_App::preset_updater { nullptr }
Referenced by ~GUI_App(), check_updates(), get_preset_updater(), on_init_inner(), post_init(), Slic3r::GUI::GuideFrame::run(), and Slic3r::GUI::ConfigWizard::run().
privacy_version_info
VersionInfo Slic3r::GUI::GUI_App::privacy_version_info private
Referenced by check_privacy_update(), check_privacy_version(), and show_check_privacy_dlg().
tabs_list
std::vector<Tab *> Slic3r::GUI::GUI_App::tabs_list
Referenced by apply_keeped_preset_modifications(), check_and_keep_current_preset_changes(), checked_tab(), get_selected_presets(), get_tab(), has_current_preset_changes(), has_unsaved_preset_changes(), load_current_presets(), update_label_colours(), update_mode(), and update_saved_preset_from_current_preset().
version_display
std::string Slic3r::GUI::GUI_App::version_display = "" static private
Referenced by format_display_version().
version_info
VersionInfo Slic3r::GUI::GUI_App::version_info private
Referenced by check_new_version(), check_new_version_sf(), check_update(), request_new_version(), and set_skip_version().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_App.hpp
src/slic3r/GUI/GUI_App.cpp