OrcaSlicer: Slic3r::GUI::ObjectDataViewModelNode Class Reference
Slic3r::GUI::ObjectDataViewModelNode Class Reference
#include <src/slic3r/GUI/ObjectDataViewModel.hpp>
Public Member Functions
ObjectDataViewModelNode (const wxString &name, const wxString &extruder, const int plate_idx, ModelObject *model_object)
ObjectDataViewModelNode (ObjectDataViewModelNode *parent, const wxString &sub_obj_name, Slic3r::ModelVolumeType type, const wxBitmap &bmp, const wxString &extruder, const int idx=-1, const std::string &warning_icon_name=std::string())
ObjectDataViewModelNode (ObjectDataViewModelNode *parent, const t_layer_height_range &layer_range, const int idx=-1, const wxString extruder="")
ObjectDataViewModelNode (PartPlate *part_plate, wxString name)
ObjectDataViewModelNode (ObjectDataViewModelNode *parent, const ItemType type, const int plate_idx=-1)
ObjectDataViewModelNode (ObjectDataViewModelNode *parent, const InfoItemType type)
~ObjectDataViewModelNode ()
void init_container ()
bool IsContainer () const
ObjectDataViewModelNode * GetParent ()
MyObjectTreeModelNodePtrArray & GetChildren ()
ObjectDataViewModelNode * GetNthChild (unsigned int n)
int GetChildIndex (ObjectDataViewModelNode *child) const
void Insert (ObjectDataViewModelNode *child, unsigned int n)
void Append (ObjectDataViewModelNode *child)
void RemoveAllChildren ()
size_t GetChildCount () const
bool SetValue (const wxVariant &variant, unsigned int col)
void SetVolumeType (ModelVolumeType type)
void SetBitmap (const wxBitmap &icon)
void SetExtruder (const wxString &extruder)
void SetWarningBitmap (const wxBitmap &icon, const std::string &warning_icon_name)
void SetLock (bool has_lock)
const wxBitmap & GetBitmap () const
const wxString & GetName () const
ItemType GetType () const
InfoItemType GetInfoItemType () const
void SetIdx (const int &idx)
int GetIdx () const
void SetPlateIdx (const int &idx)
int GetPlateIdx () const
ModelVolumeType GetVolumeType ()
t_layer_height_range GetLayerRange () const
wxString GetExtruder ()
PrintIndicator IsPrintable () const
bool HasColorPainting () const
bool HasSupportPainting () const
bool HasSinking () const
bool IsActionEnabled () const
void UpdateExtruderAndColorIcon (wxString extruder="")
void AssignAllVal (ObjectDataViewModelNode &from_node)
bool SwapChildrens (int frst_id, int scnd_id)
void set_icons ()
void set_extruder_icon ()
void set_printable_icon (PrintIndicator printable)
void set_action_icon (bool enable)
void set_color_icon (bool enable)
void set_support_icon (bool enable)
void set_sinking_icon (bool enable)
void set_warning_icon (const std::string &warning_icon)
void update_settings_digest_bitmaps ()
bool update_settings_digest (const std::vector< std::string > &categories)
int volume_type () const
void msw_rescale ()
bool valid ()
bool invalid () const
bool has_warning_icon () const
std::string warning_icon_name () const
bool has_lock () const
Public Attributes
PartPlate * m_part_plate
ModelObject * m_model_object
Private Attributes
ObjectDataViewModelNode * m_parent
MyObjectTreeModelNodePtrArray m_children
wxBitmap m_empty_bmp
size_t m_volumes_cnt = 0
std::vector< std::string > m_opt_categories
t_layer_height_range m_layer_range = { 0.0f, 0.0f }
wxString m_name
wxBitmap & m_bmp = m_empty_bmp
ItemType m_type
int m_idx = -1
int m_plate_idx = -1
bool m_container = false
wxString m_extruder = wxEmptyString
wxBitmap m_extruder_bmp
wxBitmap m_action_icon
wxBitmap m_support_icon
wxBitmap m_color_icon
wxBitmap m_sinking_icon
PrintIndicator m_printable {piUndef}
wxBitmap m_printable_icon
std::string m_warning_icon_name { "" }
bool m_has_lock {false}
std::string m_action_icon_name = ""
ModelVolumeType m_volume_type
InfoItemType m_info_item_type {InfoItemType::Undef}
bool m_action_enable = false
bool m_support_enable = false
bool m_color_enable = false
bool m_sink_enable = false
Friends
class ObjectDataViewModel
Detailed Description
Constructor & Destructor Documentation
ObjectDataViewModelNode() [1/6]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (const wxString & name, const wxString & extruder, const int plate_idx, ModelObject * model_object) inline
                                                      :
        m_parent(NULL),
        m_name(name),
        m_type(itObject),
        m_extruder(extruder),
        m_plate_idx(plate_idx),
        m_model_object(model_object)
    {
        set_icons();
        init_container();
  }
References init_container(), and set_icons().
ObjectDataViewModelNode() [2/6]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (ObjectDataViewModelNode * parent, const wxString & sub_obj_name, Slic3r::ModelVolumeType type, const wxBitmap & bmp, const wxString & extruder, const int idx = -1, const std::string & warning_icon_name = std::string())
                                                                                               :
    m_parent(parent),
    m_name(sub_obj_name),
    m_type(itVolume),
    m_volume_type(type),
    m_idx(idx),
    m_extruder(type == Slic3r::ModelVolumeType::MODEL_PART || type == Slic3r::ModelVolumeType::PARAMETER_MODIFIER ? extruder : ""),
    m_warning_icon_name(warning_icon_name)
{
    m_bmp = bmp;
    set_icons();
    init_container();
}
References init_container(), m_bmp, and set_icons().
ObjectDataViewModelNode() [3/6]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (ObjectDataViewModelNode * parent, const t_layer_height_range & layer_range, const int idx = -1, const wxString extruder = "")
                                                                          :
    m_parent(parent),
    m_type(itLayer),
    m_idx(idx),
    m_layer_range(layer_range),
    m_extruder(extruder)
{
    const int children_cnt = parent->GetChildCount();
    if (idx < 0)
        m_idx = children_cnt;
    else
    {
        // update indexes for another Laeyr Nodes
        for (int i = m_idx; i < children_cnt; i++)
            parent->GetNthChild(i)->SetIdx(i + 1);
    }
    const std::string label_range = (boost::format(" %.2f-%.2f ") % layer_range.first % layer_range.second).str();
    m_name = _(L("Range")) + label_range + "(" + _(L("mm")) + ")";
    m_bmp = create_scaled_bitmap(LayerIcon);    // FIXME: pass window ptr
    set_icons();
    init_container();
}
References _, create_scaled_bitmap(), GetChildCount(), GetNthChild(), init_container(), L, Slic3r::GUI::LayerIcon, m_bmp, m_idx, m_name, set_icons(), and SetIdx().
ObjectDataViewModelNode() [4/6]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (PartPlate * part_plate, wxString name)
                                                                                     :
    m_parent(nullptr),
    m_name(name),
    m_type(itPlate),
    m_part_plate(part_plate),
    m_extruder(wxEmptyString),
    m_container(true)
{
    m_plate_idx = part_plate ? part_plate->get_index() : -1;
    set_action_icon(false);
    // BBS
    set_color_icon(false);
    set_support_icon(false);
    init_container();
}
References Slic3r::GUI::PartPlate::get_index(), init_container(), m_plate_idx, set_action_icon(), set_color_icon(), and set_support_icon().
ObjectDataViewModelNode() [5/6]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (ObjectDataViewModelNode * parent, const ItemType type, const int plate_idx = -1)
                                                                                                                          :
    m_parent(parent),
    m_type(type),
    m_extruder(wxEmptyString),
    m_plate_idx(plate_idx)
{
    if (type == itSettings) {
        m_name = "Settings to modified";
    }
    else if (type == itInstanceRoot) {
        m_name = _(_devL("Instances"));
        m_extruder = parent->m_extruder;
    }
    else if (type == itInstance)
    {
        m_idx = parent->GetChildCount();
        m_name = wxString::Format(_(_devL("Instance %d")), m_idx + 1);
        m_extruder = parent->GetParent()->m_extruder;
        set_icons();
    }
    else if (type == itLayerRoot)
    {
        //BBS do not support layer range edit
        m_bmp = create_scaled_bitmap(LayerRootIcon);    // FIXME: pass window ptr
        m_name = _(L("Layers"));
    }
    else if (type == itInfo)
        assert(false);
    if (type & (itInstanceRoot | itLayerRoot))
        init_container();
}
References _, _devL, create_scaled_bitmap(), GetChildCount(), GetParent(), init_container(), Slic3r::GUI::itInfo, Slic3r::GUI::itInstance, Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itSettings, L, Slic3r::GUI::LayerRootIcon, m_bmp, m_extruder, m_idx, m_name, and set_icons().
ObjectDataViewModelNode() [6/6]
Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode (ObjectDataViewModelNode * parent, const InfoItemType type)
                                                                                                              :
    m_parent(parent),
    m_type(itInfo),
    m_info_item_type(info_type),
    m_extruder(wxEmptyString),
    m_name(_(INFO_ITEMS.at(info_type).name))
{
}
~ObjectDataViewModelNode()
Slic3r::GUI::ObjectDataViewModelNode::~ObjectDataViewModelNode () inline
    {
        // free all our children nodes
        size_t count = m_children.GetCount();
        for (size_t i = 0; i < count; i++)
        {
            ObjectDataViewModelNode *child = m_children[i];
            delete child;
        }
#ifndef NDEBUG
        // Indicate that the object was deleted.
        m_idx = -2;
#endif /* NDEBUG */
    }
References count, m_children, and m_idx.
Member Function Documentation
Append()
void Slic3r::GUI::ObjectDataViewModelNode::Append (ObjectDataViewModelNode * child) inline
    {
        if (!m_container)
            m_container = true;
        m_children.Add(child);
    }
References m_children, and m_container.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddInstanceChild(), Slic3r::GUI::ObjectDataViewModel::AddLayersChild(), Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::append_root_node(), and Slic3r::GUI::ObjectDataViewModel::ReparentObject().
AssignAllVal()
void Slic3r::GUI::ObjectDataViewModelNode::AssignAllVal (ObjectDataViewModelNode & from_node) inline
    {
        // ! Don't overwrite other values because of equality of this values for all children --
        m_name = from_node.m_name;
        m_bmp = from_node.m_bmp;
        m_idx = from_node.m_idx;
        m_extruder = from_node.m_extruder;
        m_type = from_node.m_type;
    }
References m_bmp, m_extruder, m_idx, m_name, and m_type.
GetBitmap()
const wxBitmap & Slic3r::GUI::ObjectDataViewModelNode::GetBitmap () const inline
{ return m_bmp; }
References m_bmp.
Referenced by Slic3r::GUI::ObjectDataViewModel::DeleteWarningIcon().
GetChildCount()
size_t Slic3r::GUI::ObjectDataViewModelNode::GetChildCount () const inline
    {
        return m_children.GetCount();
    }
References m_children.
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::AddAllChildren(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteChildren(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren(), Slic3r::GUI::get_root_idx(), Slic3r::GUI::ObjectDataViewModel::GetAllChildren(), GetChildIndex(), Slic3r::GUI::ObjectDataViewModel::GetChildren(), Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume(), Slic3r::GUI::ObjectDataViewModel::GetRowByItem(), RemoveAllChildren(), and SwapChildrens().
GetChildIndex()
int Slic3r::GUI::ObjectDataViewModelNode::GetChildIndex (ObjectDataViewModelNode * child) const inline
    {
        size_t child_count = GetChildCount();
        for (int index = 0; index < child_count; index++)
        {
            if (m_children.Item(index) == child)
                return index;
        }
        return -1;
    }
References GetChildCount(), and m_children.
Referenced by Slic3r::GUI::ObjectDataViewModel::ReorganizeObjects().
GetChildren()
MyObjectTreeModelNodePtrArray & Slic3r::GUI::ObjectDataViewModelNode::GetChildren () inline
    {
        return m_children;
    }
References m_children.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddAllChildren(), Slic3r::GUI::ObjectDataViewModel::AddInfoChild(), Slic3r::GUI::ObjectDataViewModel::AddObject(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteChildren(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren(), Slic3r::GUI::ObjectDataViewModel::GetAllChildren(), Slic3r::GUI::ObjectDataViewModel::GetChildren(), Slic3r::GUI::ObjectDataViewModel::GetVolumeItem(), Slic3r::GUI::ObjectDataViewModel::ReorganizeChildren(), Slic3r::GUI::ObjectDataViewModel::ReorganizeObjects(), Slic3r::GUI::ObjectDataViewModel::ReparentObject(), Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable(), Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable(), and Slic3r::GUI::ObjectDataViewModel::UpdateVolumesExtruderBitmap().
GetExtruder()
wxString Slic3r::GUI::ObjectDataViewModelNode::GetExtruder () inline
{ return m_extruder; }
References m_extruder.
Referenced by Slic3r::GUI::ObjectDataViewModel::SetVolumeType(), UpdateExtruderAndColorIcon(), and Slic3r::GUI::ObjectDataViewModel::UpdateVolumesExtruderBitmap().
GetIdx()
int Slic3r::GUI::ObjectDataViewModelNode::GetIdx () const inline
{ return m_idx; }
References m_idx.
Referenced by Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::GetIdByItemAndType(), and Slic3r::GUI::ObjectDataViewModel::GetItemInfo().
GetInfoItemType()
InfoItemType Slic3r::GUI::ObjectDataViewModelNode::GetInfoItemType () const inline
{ return m_info_item_type; }
References m_info_item_type.
GetLayerRange()
t_layer_height_range Slic3r::GUI::ObjectDataViewModelNode::GetLayerRange () const inline
{ return m_layer_range; }
References m_layer_range.
Referenced by Slic3r::GUI::ObjectDataViewModel::GetLayerRangeByItem().
GetName()
const wxString & Slic3r::GUI::ObjectDataViewModelNode::GetName () const inline
{ return m_name; }
References m_name.
GetNthChild()
ObjectDataViewModelNode * Slic3r::GUI::ObjectDataViewModelNode::GetNthChild (unsigned int n) inline
    {
        return m_children.Item(n);
    }
References m_children, and n.
Referenced by ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::AddLayersChild(), Slic3r::GUI::append_root_node(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::get_root_idx(), Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume(), Slic3r::GUI::ObjectDataViewModel::GetRowByItem(), Slic3r::GUI::ObjectDataViewModel::ReorganizeChildren(), SwapChildrens(), Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable(), and Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable().
GetParent()
ObjectDataViewModelNode * Slic3r::GUI::ObjectDataViewModelNode::GetParent () inline
    {
        assert(m_parent == nullptr || m_parent->valid());
        return m_parent;
    }
References m_parent, and valid().
Referenced by ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::AddWarningIcon(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::GetItemInfo(), Slic3r::GUI::ObjectDataViewModel::GetObject(), Slic3r::GUI::ObjectDataViewModel::GetParent(), and Slic3r::GUI::ObjectDataViewModel::GetTopParent().
GetPlateIdx()
int Slic3r::GUI::ObjectDataViewModelNode::GetPlateIdx () const inline
{ return m_plate_idx; }
References m_plate_idx.
Referenced by Slic3r::GUI::ObjectList::ObjectList(), and Slic3r::GUI::ObjectList::update_plate_values_for_items().
GetType()
ItemType Slic3r::GUI::ObjectDataViewModelNode::GetType () const inline
{ return m_type; }
References m_type.
Referenced by Slic3r::GUI::ObjectList::ObjectList(), Slic3r::GUI::ObjectDataViewModel::AddLayersChild(), Slic3r::GUI::ObjectDataViewModel::AddWarningIcon(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::ObjectDataViewModel::DeleteWarningIcon(), Slic3r::GUI::get_root_idx(), Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume(), Slic3r::GUI::ObjectDataViewModel::GetItemInfo(), Slic3r::GUI::ObjectDataViewModel::SetExtruder(), Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode(), and Slic3r::GUI::ObjectDataViewModel::UpdateCutObjectIcon().
GetVolumeType()
ModelVolumeType Slic3r::GUI::ObjectDataViewModelNode::GetVolumeType () inline
{ return m_volume_type; }
References m_volume_type.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddWarningIcon(), Slic3r::GUI::ObjectDataViewModel::GetVolumeType(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
has_lock()
bool Slic3r::GUI::ObjectDataViewModelNode::has_lock () const inline
{ return m_has_lock; }
References m_has_lock.
Referenced by SetLock(), Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode(), and Slic3r::GUI::ObjectDataViewModel::UpdateCutObjectIcon().
has_warning_icon()
bool Slic3r::GUI::ObjectDataViewModelNode::has_warning_icon () const inline
{ return !m_warning_icon_name.empty(); }
References m_warning_icon_name.
Referenced by Slic3r::GUI::ObjectDataViewModel::HasWarningIcon(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
HasColorPainting()
bool Slic3r::GUI::ObjectDataViewModelNode::HasColorPainting () const inline
{ return m_color_enable; }
References m_color_enable.
Referenced by Slic3r::GUI::ObjectList::list_manipulation(), Slic3r::GUI::ObjectList::OnEditingStarted(), and Slic3r::GUI::ObjectList::set_tooltip_for_item().
HasSinking()
bool Slic3r::GUI::ObjectDataViewModelNode::HasSinking () const inline
{ return m_sink_enable; }
References m_sink_enable.
Referenced by Slic3r::GUI::ObjectList::set_tooltip_for_item().
HasSupportPainting()
bool Slic3r::GUI::ObjectDataViewModelNode::HasSupportPainting () const inline
{ return m_support_enable; }
References m_support_enable.
Referenced by Slic3r::GUI::ObjectList::list_manipulation(), Slic3r::GUI::ObjectList::OnEditingStarted(), and Slic3r::GUI::ObjectList::set_tooltip_for_item().
init_container()
void Slic3r::GUI::ObjectDataViewModelNode::init_container ()
{
#ifdef __WXGTK__
    // it's necessary on GTK because of control have to know if this item will be container
    // in another case you couldn't to add subitem for this item
    // it will be produce "segmentation fault"
    m_container = true;
#endif  //__WXGTK__
}
References m_container.
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), ObjectDataViewModelNode(), ObjectDataViewModelNode(), and ObjectDataViewModelNode().
Insert()
void Slic3r::GUI::ObjectDataViewModelNode::Insert (ObjectDataViewModelNode * child, unsigned int n) inline
    {
        if (!m_container)
            m_container = true;
        m_children.Insert(child, n);
    }
References m_children, m_container, and n.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddInfoChild(), Slic3r::GUI::ObjectDataViewModel::AddLayersChild(), Slic3r::GUI::ObjectDataViewModel::AddSettingsChild(), Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::append_root_node(), Slic3r::GUI::ObjectDataViewModel::ReorganizeChildren(), and Slic3r::GUI::ObjectDataViewModel::ReorganizeObjects().
invalid()
bool Slic3r::GUI::ObjectDataViewModelNode::invalid () const inline
{ return m_idx < -1; }
References m_idx.
Referenced by Slic3r::GUI::ObjectDataViewModel::InvalidItem().
IsActionEnabled()
bool Slic3r::GUI::ObjectDataViewModelNode::IsActionEnabled () const inline
{ return m_action_enable; }
References m_action_enable.
Referenced by Slic3r::GUI::ObjectList::set_tooltip_for_item().
IsContainer()
bool Slic3r::GUI::ObjectDataViewModelNode::IsContainer () const inline
  {
    return m_container;
  }
References m_container.
Referenced by Slic3r::GUI::ObjectDataViewModel::IsContainer().
IsPrintable()
PrintIndicator Slic3r::GUI::ObjectDataViewModelNode::IsPrintable () const inline
{ return m_printable; }
References m_printable.
Referenced by Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::IsPrintable(), Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable(), and Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable().
msw_rescale()
void Slic3r::GUI::ObjectDataViewModelNode::msw_rescale ()
{
    if (!m_action_icon_name.empty())
        m_action_icon = create_scaled_bitmap(m_action_icon_name);
    if (m_printable != piUndef)
        m_printable_icon = create_scaled_bitmap(m_printable == piPrintable ? "obj_printable" : "obj_unprintable");
    if (!m_opt_categories.empty())
        update_settings_digest_bitmaps();
    set_extruder_icon();
}
References create_scaled_bitmap(), m_action_icon, m_action_icon_name, m_opt_categories, m_printable, m_printable_icon, Slic3r::GUI::piPrintable, Slic3r::GUI::piUndef, set_extruder_icon(), and update_settings_digest_bitmaps().
Referenced by Slic3r::GUI::ObjectDataViewModel::Rescale().
RemoveAllChildren()
void Slic3r::GUI::ObjectDataViewModelNode::RemoveAllChildren () inline
    {
        if (GetChildCount() == 0)
            return;
        for (int id = int(GetChildCount()) - 1; id >= 0; --id)
        {
            if (m_children.Item(id)->GetChildCount() > 0)
                m_children[id]->RemoveAllChildren();
            auto node = m_children[id];
            m_children.RemoveAt(id);
            delete node;
        }
    }
References GetChildCount(), and m_children.
set_action_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_action_icon (bool enable)
{
    m_action_enable = enable;
    auto undo = enable ? "lock_normal" : "dot";
    m_action_icon_name = m_type & itPlate ? "dot" :
                         m_type & itObject ? undo :
                         m_type & (itVolume | itLayer) ? undo : /*m_type & itInstance*/ "set_separate_obj";
    m_action_icon = create_scaled_bitmap(m_action_icon_name);    // FIXME: pass window ptr
}
References create_scaled_bitmap(), Slic3r::GUI::itLayer, Slic3r::GUI::itObject, Slic3r::GUI::itPlate, Slic3r::GUI::itVolume, m_action_enable, m_action_icon, m_action_icon_name, and m_type.
Referenced by ObjectDataViewModelNode(), Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), and set_icons().
set_color_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_color_icon (bool enable)
{
    m_color_enable = enable;
    if ((m_type & itObject) && enable)
        m_color_icon = create_scaled_bitmap("mmu_segmentation");
    else
        m_color_icon = create_scaled_bitmap("dot");
}
References create_scaled_bitmap(), Slic3r::GUI::itObject, m_color_enable, m_color_icon, and m_type.
Referenced by ObjectDataViewModelNode(), set_icons(), and Slic3r::GUI::ObjectDataViewModel::SetColorPaintState().
set_extruder_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_extruder_icon ()
{
    if (m_type & (itInstance | itInstanceRoot | itLayerRoot) ||
        ((m_type & itVolume) && m_volume_type != Slic3r::ModelVolumeType::MODEL_PART && m_volume_type != Slic3r::ModelVolumeType::PARAMETER_MODIFIER))
        return; // don't set colored bitmap for Instance
    UpdateExtruderAndColorIcon();
}
References Slic3r::GUI::itInstance, Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itLayerRoot, Slic3r::GUI::itVolume, m_type, m_volume_type, Slic3r::MODEL_PART, Slic3r::PARAMETER_MODIFIER, and UpdateExtruderAndColorIcon().
Referenced by msw_rescale(), and set_icons().
set_icons()
void Slic3r::GUI::ObjectDataViewModelNode::set_icons ()
{
    set_action_icon(false);
    // BBS
    set_color_icon(false);
    set_support_icon(false);
    // set extruder bitmap
    set_extruder_icon();
}
References set_action_icon(), set_color_icon(), set_extruder_icon(), and set_support_icon().
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), ObjectDataViewModelNode(), and ObjectDataViewModelNode().
set_printable_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon (PrintIndicator printable)
{
    m_printable = printable;
    m_printable_icon = m_printable == piUndef ? m_empty_bmp :
                       create_scaled_bitmap(m_printable == piPrintable ? "check_on" : "check_off_focused");
}
References create_scaled_bitmap(), m_empty_bmp, m_printable, m_printable_icon, Slic3r::GUI::piPrintable, and Slic3r::GUI::piUndef.
Referenced by Slic3r::GUI::ObjectDataViewModel::AddInstanceChild(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::SetObjectPrintableState(), Slic3r::GUI::ObjectDataViewModel::SetPrintableState(), Slic3r::GUI::ObjectDataViewModel::UpdateInstancesPrintable(), and Slic3r::GUI::ObjectDataViewModel::UpdateObjectPrintable().
set_sinking_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_sinking_icon (bool enable)
{
    m_sink_enable = enable;
    if ((m_type & itObject) && enable)
        m_sinking_icon = create_scaled_bitmap("objlist_sinking");
    else
        m_sinking_icon = create_scaled_bitmap("dot");
}
References create_scaled_bitmap(), Slic3r::GUI::itObject, m_sink_enable, m_sinking_icon, and m_type.
Referenced by Slic3r::GUI::ObjectDataViewModel::SetSinkState().
set_support_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_support_icon (bool enable)
{
    m_support_enable = enable;
    if ((m_type & itObject) && enable)
        m_support_icon = create_scaled_bitmap("toolbar_support");
    else
        m_support_icon = create_scaled_bitmap("dot");
}
References create_scaled_bitmap(), Slic3r::GUI::itObject, m_support_enable, m_support_icon, and m_type.
Referenced by ObjectDataViewModelNode(), set_icons(), and Slic3r::GUI::ObjectDataViewModel::SetSupportPaintState().
set_warning_icon()
void Slic3r::GUI::ObjectDataViewModelNode::set_warning_icon (const std::string & warning_icon)
{
    m_warning_icon_name = warning_icon_name;
    if (warning_icon_name.empty())
        m_bmp = m_empty_bmp;
}
References m_bmp, m_empty_bmp, m_warning_icon_name, and warning_icon_name().
SetBitmap()
void Slic3r::GUI::ObjectDataViewModelNode::SetBitmap (const wxBitmap & icon) inline
{ m_bmp = icon; }
References m_bmp.
Referenced by Slic3r::GUI::ObjectDataViewModel::SetVolumeType(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
SetExtruder()
void Slic3r::GUI::ObjectDataViewModelNode::SetExtruder (const wxString & extruder) inline
{ m_extruder = extruder; }
References m_extruder.
Referenced by Slic3r::GUI::ObjectDataViewModel::SetVolumeType().
SetIdx()
void Slic3r::GUI::ObjectDataViewModelNode::SetIdx (const int & idx)
{
    m_idx = idx;
    // update name if this node is instance
    if (m_type == itInstance) {
        if (m_plate_idx > 0) {
            m_name = wxString::Format(_(_devL("[P%d]Instance %d")), m_plate_idx, m_idx + 1);
        }
        else {
            m_name = wxString::Format(_(_devL("Instance %d")), m_idx + 1);
        }
    }
}
References _, _devL, Slic3r::GUI::itInstance, m_idx, m_name, m_plate_idx, and m_type.
Referenced by ObjectDataViewModelNode().
SetLock()
void Slic3r::GUI::ObjectDataViewModelNode::SetLock (bool has_lock) inline
{ m_has_lock = has_lock; }
References has_lock(), and m_has_lock.
Referenced by Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode(), and Slic3r::GUI::ObjectDataViewModel::UpdateCutObjectIcon().
SetPlateIdx()
void Slic3r::GUI::ObjectDataViewModelNode::SetPlateIdx (const int & idx)
{
    m_plate_idx = idx;
}
References m_plate_idx.
SetValue()
bool Slic3r::GUI::ObjectDataViewModelNode::SetValue (const wxVariant & variant, unsigned int col)
{
    switch (col)
    {
    case colPrint:
        m_printable_icon << variant;
        return true;
    case colName: {
        DataViewBitmapText data;
        data << variant;
        m_bmp = data.GetBitmap();
        m_name = data.GetText();
        return true; }
    case colFilament: {
        DataViewBitmapText data;
        data << variant;
        m_extruder_bmp = data.GetBitmap();
        m_extruder = data.GetText() == "0" ? _(L("default")) : data.GetText();
        return true; }
    // BBS
    case colSupportPaint:
        m_support_icon << variant;
        break;
    case colSinking:
        m_sinking_icon << variant;
        break;
    case colColorPaint:
        m_color_icon << variant;
        break;
    case colEditing:
        m_action_icon << variant;
        return true;
    default:
        printf("MyObjectTreeModel::SetValue: wrong column");
    }
    return false;
}
References _, col(), Slic3r::GUI::colColorPaint, Slic3r::GUI::colEditing, Slic3r::GUI::colFilament, Slic3r::GUI::colName, Slic3r::GUI::colPrint, Slic3r::GUI::colSinking, Slic3r::GUI::colSupportPaint, DataViewBitmapText::GetBitmap(), DataViewBitmapText::GetText(), L, m_action_icon, m_bmp, m_color_icon, m_extruder, m_extruder_bmp, m_name, m_printable_icon, m_sinking_icon, and m_support_icon.
Referenced by Slic3r::GUI::ObjectDataViewModel::SetValue().
SetVolumeType()
void Slic3r::GUI::ObjectDataViewModelNode::SetVolumeType (ModelVolumeType type) inline
{ m_volume_type = type; }
References m_volume_type.
Referenced by Slic3r::GUI::ObjectDataViewModel::SetVolumeType().
SetWarningBitmap()
void Slic3r::GUI::ObjectDataViewModelNode::SetWarningBitmap (const wxBitmap & icon, const std::string & warning_icon_name) inline
{ m_bmp = icon; m_warning_icon_name = warning_icon_name; }
References m_bmp, m_warning_icon_name, and warning_icon_name().
Referenced by Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::ObjectDataViewModel::AddWarningIcon(), and Slic3r::GUI::ObjectDataViewModel::DeleteWarningIcon().
SwapChildrens()
bool Slic3r::GUI::ObjectDataViewModelNode::SwapChildrens (int frst_id, int scnd_id) inline
{
        if (GetChildCount() < 2 ||
            frst_id < 0 || (size_t)frst_id >= GetChildCount() ||
            scnd_id < 0 || (size_t)scnd_id >= GetChildCount())
            return false;
        ObjectDataViewModelNode new_scnd = *GetNthChild(frst_id);
        ObjectDataViewModelNode new_frst = *GetNthChild(scnd_id);
        new_scnd.m_idx = m_children.Item(scnd_id)->m_idx;
        new_frst.m_idx = m_children.Item(frst_id)->m_idx;
        m_children.Item(frst_id)->AssignAllVal(new_frst);
        m_children.Item(scnd_id)->AssignAllVal(new_scnd);
        return true;
    }
References GetChildCount(), GetNthChild(), m_children, and m_idx.
update_settings_digest()
bool Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest (const std::vector< std::string > & categories)
{
    if (m_type != itSettings || m_opt_categories == categories)
        return false;
    m_opt_categories = categories;
    m_name = wxEmptyString;
    for (auto& cat : m_opt_categories)
        m_name += _(cat) + "; ";
    if (!m_name.IsEmpty())
        m_name.erase(m_name.Length()-2, 2); // Delete last "; "
    update_settings_digest_bitmaps();
    return true;
}
References _, Slic3r::GUI::itSettings, m_name, m_opt_categories, m_type, and update_settings_digest_bitmaps().
Referenced by Slic3r::GUI::ObjectDataViewModel::UpdateSettingsDigest().
update_settings_digest_bitmaps()
void Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest_bitmaps ()
{
    m_bmp = m_empty_bmp;
    std::string scaled_bitmap_name = m_name.ToUTF8().data();
    scaled_bitmap_name += "-em" + std::to_string(wxGetApp().em_unit()) + (wxGetApp().dark_mode() ? "-dm" : "");
    wxBitmap *bmp = m_bitmap_cache->find(scaled_bitmap_name);
    if (bmp == nullptr) {
        std::vector<wxBitmap> bmps;
        for (auto& category : m_opt_categories)
            bmps.emplace_back(SettingsFactory::get_category_bitmap(category, false));
        bmp = m_bitmap_cache->insert(scaled_bitmap_name, bmps);
    }
    m_bmp = *bmp;
}
References em_unit(), Slic3r::GUI::BitmapCache::find(), Slic3r::GUI::SettingsFactory::get_category_bitmap(), Slic3r::GUI::BitmapCache::insert(), Slic3r::GUI::m_bitmap_cache, m_bmp, m_empty_bmp, m_name, and m_opt_categories.
Referenced by msw_rescale(), and update_settings_digest().
UpdateExtruderAndColorIcon()
void Slic3r::GUI::ObjectDataViewModelNode::UpdateExtruderAndColorIcon (wxString extruder = "")
{
    if (m_type == itVolume && m_volume_type != ModelVolumeType::MODEL_PART && m_volume_type != ModelVolumeType::PARAMETER_MODIFIER)
        return;
    if (extruder.empty())
        extruder = m_extruder;
    else
        m_extruder = extruder; // update extruder
    // update color icon
    size_t extruder_idx = atoi(extruder.c_str());
    if (extruder_idx == 0) {
        if (m_type & itObject);
        else if (m_type & itVolume && m_volume_type == ModelVolumeType::MODEL_PART) {
            extruder_idx = atoi(m_parent->GetExtruder().c_str());
        }
        // BBS
        else if (m_type & itVolume && m_volume_type == ModelVolumeType::PARAMETER_MODIFIER) {
            m_extruder_bmp = *get_default_extruder_color_icon();
            return;
        }
        else {
            m_extruder_bmp = wxNullBitmap;
            return;
        }
    }
    if (extruder_idx > 0) --extruder_idx;
    // Create the bitmap with color bars.
    std::vector<wxBitmap*> bmps = get_extruder_color_icons(false);// use wide icons
    if (bmps.empty()) {
        m_extruder_bmp = wxNullBitmap;
        return;
    }
    m_extruder_bmp = *bmps[extruder_idx >= bmps.size() ? 0 : extruder_idx];
}
References get_default_extruder_color_icon(), get_extruder_color_icons(), GetExtruder(), Slic3r::GUI::itObject, Slic3r::GUI::itVolume, m_extruder, m_extruder_bmp, m_parent, m_type, m_volume_type, Slic3r::MODEL_PART, and Slic3r::PARAMETER_MODIFIER.
Referenced by set_extruder_icon(), Slic3r::GUI::ObjectDataViewModel::SetExtruder(), Slic3r::GUI::ObjectDataViewModel::SetVolumeType(), Slic3r::GUI::ObjectDataViewModel::UpdateExtruderBitmap(), and Slic3r::GUI::ObjectDataViewModel::UpdateVolumesExtruderBitmap().
valid()
bool Slic3r::GUI::ObjectDataViewModelNode::valid ()
{
  // Verify that the object was not deleted yet.
  assert(m_idx >= -1);
  return m_idx >= -1;
}
References m_idx.
Referenced by GetParent(), and Slic3r::GUI::ObjectDataViewModel::GetParent().
volume_type()
int Slic3r::GUI::ObjectDataViewModelNode::volume_type () const inline
{ return int(m_volume_type); }
References int, and m_volume_type.
Referenced by Slic3r::GUI::ObjectDataViewModel::DeleteWarningIcon().
warning_icon_name()
std::string Slic3r::GUI::ObjectDataViewModelNode::warning_icon_name () const inline
{ return m_warning_icon_name; }
References m_warning_icon_name.
Referenced by set_warning_icon(), SetWarningBitmap(), and Slic3r::GUI::ObjectDataViewModel::UpdateBitmapForNode().
Friends And Related Symbol Documentation
ObjectDataViewModel
friend class ObjectDataViewModel friend
Member Data Documentation
m_action_enable
bool Slic3r::GUI::ObjectDataViewModelNode::m_action_enable = false private
Referenced by IsActionEnabled(), and set_action_icon().
m_action_icon
wxBitmap Slic3r::GUI::ObjectDataViewModelNode::m_action_icon private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), msw_rescale(), set_action_icon(), and SetValue().
m_action_icon_name
std::string Slic3r::GUI::ObjectDataViewModelNode::m_action_icon_name = "" private
Referenced by msw_rescale(), and set_action_icon().
m_bmp
wxBitmap& Slic3r::GUI::ObjectDataViewModelNode::m_bmp = m_empty_bmp private
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), ObjectDataViewModelNode(), AssignAllVal(), GetBitmap(), Slic3r::GUI::ObjectDataViewModel::GetBitmap(), Slic3r::GUI::ObjectDataViewModel::GetValue(), Slic3r::GUI::ObjectDataViewModel::Rescale(), set_warning_icon(), SetBitmap(), SetValue(), SetWarningBitmap(), and update_settings_digest_bitmaps().
m_children
MyObjectTreeModelNodePtrArray Slic3r::GUI::ObjectDataViewModelNode::m_children private
Referenced by ~ObjectDataViewModelNode(), Append(), GetChildCount(), GetChildIndex(), GetChildren(), GetNthChild(), Insert(), RemoveAllChildren(), and SwapChildrens().
m_color_enable
bool Slic3r::GUI::ObjectDataViewModelNode::m_color_enable = false private
Referenced by HasColorPainting(), Slic3r::GUI::ObjectDataViewModel::IsColorPainted(), and set_color_icon().
m_color_icon
wxBitmap Slic3r::GUI::ObjectDataViewModelNode::m_color_icon private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), set_color_icon(), and SetValue().
m_container
bool Slic3r::GUI::ObjectDataViewModelNode::m_container = false private
Referenced by Append(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::DeleteChildren(), Slic3r::GUI::ObjectDataViewModel::DeleteLastInstance(), Slic3r::GUI::ObjectDataViewModel::DeleteSettings(), Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren(), init_container(), Insert(), and IsContainer().
m_empty_bmp
wxBitmap Slic3r::GUI::ObjectDataViewModelNode::m_empty_bmp private
Referenced by set_printable_icon(), set_warning_icon(), and update_settings_digest_bitmaps().
m_extruder
wxString Slic3r::GUI::ObjectDataViewModelNode::m_extruder = wxEmptyString private
Referenced by ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), AssignAllVal(), GetExtruder(), Slic3r::GUI::ObjectDataViewModel::GetExtruder(), Slic3r::GUI::ObjectDataViewModel::GetExtruderNumber(), Slic3r::GUI::ObjectDataViewModel::GetValue(), Slic3r::GUI::ObjectDataViewModel::IsEnabled(), SetExtruder(), SetValue(), and UpdateExtruderAndColorIcon().
m_extruder_bmp
wxBitmap Slic3r::GUI::ObjectDataViewModelNode::m_extruder_bmp private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), SetValue(), and UpdateExtruderAndColorIcon().
m_has_lock
bool Slic3r::GUI::ObjectDataViewModelNode::m_has_lock {false} private
Referenced by has_lock(), and SetLock().
m_idx
int Slic3r::GUI::ObjectDataViewModelNode::m_idx = -1 private
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), ~ObjectDataViewModelNode(), AssignAllVal(), GetIdx(), invalid(), SetIdx(), SwapChildrens(), and valid().
m_info_item_type
InfoItemType Slic3r::GUI::ObjectDataViewModelNode::m_info_item_type {InfoItemType::Undef} private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType(), GetInfoItemType(), Slic3r::GUI::ObjectDataViewModel::GetInfoItemType(), and Slic3r::GUI::ObjectDataViewModel::Rescale().
m_layer_range
t_layer_height_range Slic3r::GUI::ObjectDataViewModelNode::m_layer_range = { 0.0f, 0.0f } private
Referenced by GetLayerRange().
m_model_object
ModelObject* Slic3r::GUI::ObjectDataViewModelNode::m_model_object
Referenced by Slic3r::GUI::ObjectList::set_extruder_for_selected_items().
m_name
wxString Slic3r::GUI::ObjectDataViewModelNode::m_name private
Referenced by ObjectDataViewModelNode(), ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), AssignAllVal(), GetName(), Slic3r::GUI::ObjectDataViewModel::GetName(), Slic3r::GUI::ObjectDataViewModel::GetValue(), SetIdx(), SetValue(), update_settings_digest(), and update_settings_digest_bitmaps().
m_opt_categories
std::vector< std::string > Slic3r::GUI::ObjectDataViewModelNode::m_opt_categories private
Referenced by msw_rescale(), update_settings_digest(), and update_settings_digest_bitmaps().
m_parent
ObjectDataViewModelNode* Slic3r::GUI::ObjectDataViewModelNode::m_parent private
Referenced by Slic3r::GUI::ObjectDataViewModel::AddObject(), GetParent(), Slic3r::GUI::ObjectDataViewModel::ReorganizeObjects(), Slic3r::GUI::ObjectDataViewModel::ReparentObject(), and UpdateExtruderAndColorIcon().
m_part_plate
PartPlate* Slic3r::GUI::ObjectDataViewModelNode::m_part_plate
Referenced by Slic3r::GUI::ObjectDataViewModel::AddObject().
m_plate_idx
int Slic3r::GUI::ObjectDataViewModelNode::m_plate_idx = -1 private
Referenced by ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::Delete(), GetPlateIdx(), Slic3r::GUI::ObjectDataViewModel::ReparentObject(), SetIdx(), and SetPlateIdx().
m_printable
PrintIndicator Slic3r::GUI::ObjectDataViewModelNode::m_printable {piUndef} private
Referenced by IsPrintable(), msw_rescale(), and set_printable_icon().
m_printable_icon
wxBitmap Slic3r::GUI::ObjectDataViewModelNode::m_printable_icon private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), msw_rescale(), set_printable_icon(), and SetValue().
m_sink_enable
bool Slic3r::GUI::ObjectDataViewModelNode::m_sink_enable = false private
Referenced by HasSinking(), Slic3r::GUI::ObjectDataViewModel::IsSinked(), and set_sinking_icon().
m_sinking_icon
wxBitmap Slic3r::GUI::ObjectDataViewModelNode::m_sinking_icon private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), set_sinking_icon(), and SetValue().
m_support_enable
bool Slic3r::GUI::ObjectDataViewModelNode::m_support_enable = false private
Referenced by HasSupportPainting(), Slic3r::GUI::ObjectDataViewModel::IsSupportPainted(), and set_support_icon().
m_support_icon
wxBitmap Slic3r::GUI::ObjectDataViewModelNode::m_support_icon private
Referenced by Slic3r::GUI::ObjectDataViewModel::GetValue(), set_support_icon(), and SetValue().
m_type
ItemType Slic3r::GUI::ObjectDataViewModelNode::m_type private
Referenced by AssignAllVal(), Slic3r::GUI::ObjectDataViewModel::Delete(), Slic3r::GUI::ObjectDataViewModel::GetIdByItemAndType(), Slic3r::GUI::ObjectDataViewModel::GetInfoItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemByType(), Slic3r::GUI::ObjectDataViewModel::GetItemInfo(), Slic3r::GUI::ObjectDataViewModel::GetItemType(), Slic3r::GUI::ObjectDataViewModel::GetLayerRangeByItem(), Slic3r::GUI::ObjectDataViewModel::GetObject(), Slic3r::GUI::ObjectDataViewModel::GetParent(), Slic3r::GUI::ObjectDataViewModel::GetRowByItem(), Slic3r::GUI::ObjectDataViewModel::GetTopParent(), GetType(), Slic3r::GUI::ObjectDataViewModel::IsSettingsItem(), Slic3r::GUI::ObjectDataViewModel::ReparentObject(), Slic3r::GUI::ObjectDataViewModel::Rescale(), set_action_icon(), set_color_icon(), set_extruder_icon(), set_sinking_icon(), set_support_icon(), SetIdx(), update_settings_digest(), and UpdateExtruderAndColorIcon().
m_volume_type
ModelVolumeType Slic3r::GUI::ObjectDataViewModelNode::m_volume_type private
Referenced by GetVolumeType(), Slic3r::GUI::ObjectDataViewModel::Rescale(), set_extruder_icon(), SetVolumeType(), UpdateExtruderAndColorIcon(), and volume_type().
m_volumes_cnt
size_t Slic3r::GUI::ObjectDataViewModelNode::m_volumes_cnt = 0 private
Referenced by Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), Slic3r::GUI::ObjectDataViewModel::DeleteChildren(), Slic3r::GUI::ObjectDataViewModel::DeleteVolumeChildren(), and Slic3r::GUI::ObjectDataViewModel::GetItemIndexForFirstVolume().
m_warning_icon_name
std::string Slic3r::GUI::ObjectDataViewModelNode::m_warning_icon_name { "" } private
Referenced by Slic3r::GUI::ObjectDataViewModel::AddVolumeChild(), has_warning_icon(), Slic3r::GUI::ObjectDataViewModel::Rescale(), set_warning_icon(), SetWarningBitmap(), and warning_icon_name().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ObjectDataViewModel.hpp
src/slic3r/GUI/ObjectDataViewModel.cpp