OrcaSlicer: Slic3r::ModelObject Class Reference
Slic3r::ModelObject Class Reference final
#include <src/libslic3r/Model.hpp>
Public Types
using Timestamp = uint64_t
Public Member Functions
Model * get_model ()
const Model * get_model () const
int get_backup_id () const
template<typename T >
const T * get_config_value (const DynamicPrintConfig &global_config, const std::string &config_option)
ModelVolume * add_volume (const TriangleMesh &mesh)
ModelVolume * add_volume (TriangleMesh &&mesh, ModelVolumeType type=ModelVolumeType::MODEL_PART)
ModelVolume * add_volume (const ModelVolume &volume, ModelVolumeType type=ModelVolumeType::INVALID)
ModelVolume * add_volume (const ModelVolume &volume, TriangleMesh &&mesh)
ModelVolume * add_volume_with_shared_mesh (const ModelVolume &other, ModelVolumeType type=ModelVolumeType::MODEL_PART)
void delete_volume (size_t idx)
void clear_volumes ()
void sort_volumes (bool full_sort)
bool is_multiparts () const
bool is_fdm_support_painted () const
bool is_seam_painted () const
bool is_mm_painted () const
ModelInstance * add_instance ()
ModelInstance * add_instance (const ModelInstance &instance)
ModelInstance * add_instance (const Vec3d &offset, const Vec3d &scaling_factor, const Vec3d &rotation, const Vec3d &mirror)
void delete_instance (size_t idx)
void delete_last_instance ()
void clear_instances ()
const BoundingBoxf3 & bounding_box () const
void invalidate_bounding_box ()
TriangleMesh mesh () const
TriangleMesh raw_mesh () const
indexed_triangle_set raw_indexed_triangle_set () const
const BoundingBoxf3 & raw_bounding_box () const
BoundingBoxf3 instance_bounding_box (size_t instance_idx, bool dont_translate=false) const
BoundingBoxf3 instance_bounding_box (const ModelInstance &instance, bool dont_translate=false) const
const BoundingBoxf3 & raw_mesh_bounding_box () const
BoundingBoxf3 full_raw_mesh_bounding_box () const
BoundingBoxf3 instance_convex_hull_bounding_box (size_t instance_idx, bool dont_translate=false) const
Polygon convex_hull_2d (const Transform3d &trafo_instance) const
void center_around_origin (bool include_modifiers=true)
void ensure_on_bed (bool allow_negative_z=false)
void translate_instances (const Vec3d &vector)
void translate_instance (size_t instance_idx, const Vec3d &vector)
void translate (const Vec3d &vector)
void translate (double x, double y, double z)
void scale (const Vec3d &versor)
void scale (const double s)
void scale (double x, double y, double z)
void scale_to_fit (const Vec3d &size)
Scale the current ModelObject to fit by altering the scaling factor of ModelInstances. It operates on the total size by duplicating the object according to all the instances.
void rotate (double angle, Axis axis)
void rotate (double angle, const Vec3d &axis)
void mirror (Axis axis)
void scale_mesh_after_creation (const float scale)
void convert_units (ModelObjectPtrs &new_objects, ConversionType conv_type, std::vector< int > volume_idxs)
size_t materials_count () const
size_t facets_count () const
size_t parts_count () const
bool is_cut () const
bool has_connectors () const
void apply_cut_connectors (const std::string &name)
void invalidate_cut ()
void delete_connectors ()
void synchronize_model_after_cut ()
void apply_cut_attributes (ModelObjectCutAttributes attributes)
void clone_for_cut (ModelObject **obj)
Transform3d calculate_cut_plane_inverse_matrix (const std::array< Vec3d, 4 > &plane_points)
void process_connector_cut (ModelVolume *volume, const Transform3d &instance_matrix, const Transform3d &cut_matrix, ModelObjectCutAttributes attributes, ModelObject *upper, ModelObject *lower, std::vector< ModelObject * > &dowels, Vec3d &local_dowels_displace)
void process_modifier_cut (ModelVolume *volume, const Transform3d &instance_matrix, const Transform3d &inverse_cut_matrix, ModelObjectCutAttributes attributes, ModelObject *upper, ModelObject *lower)
void process_volume_cut (ModelVolume *volume, const Transform3d &instance_matrix, const Transform3d &cut_matrix, ModelObjectCutAttributes attributes, TriangleMesh &upper_mesh, TriangleMesh &lower_mesh)
void process_solid_part_cut (ModelVolume *volume, const Transform3d &instance_matrix, const Transform3d &cut_matrix, const std::array< Vec3d, 4 > &plane_points, ModelObjectCutAttributes attributes, ModelObject *upper, ModelObject *lower, Vec3d &local_displace)
ModelObjectPtrs cut (size_t instance, std::array< Vec3d, 4 > plane_points, ModelObjectCutAttributes attributes)
ModelObjectPtrs segment (size_t instance, unsigned int max_extruders, double smoothing_alpha=0.5, int segment_number=5)
void split (ModelObjectPtrs *new_objects)
void merge ()
bool make_boolean (ModelObject *cut_object, const std::string &boolean_opts)
ModelObjectPtrs merge_volumes (std::vector< int > &vol_indeces)
void bake_xy_rotation_into_meshes (size_t instance_idx)
double get_min_z () const
double get_max_z () const
double get_instance_min_z (size_t instance_idx) const
double get_instance_max_z (size_t instance_idx) const
void print_info () const
std::string get_export_filename () const
TriangleMeshStats get_object_stl_stats () const
int get_repaired_errors_count (const int vol_idx=-1) const
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Member Functions
static indexed_triangle_set get_connector_mesh (CutConnectorAttributes connector_attributes)
Public Attributes
std::string name
std::string module_name
std::string input_file
ModelInstancePtrs instances
ModelVolumePtrs volumes
ModelConfigObject config
t_layer_config_ranges layer_config_ranges
LayerHeightProfile layer_height_profile
bool printable
sla::SupportPoints sla_support_points
sla::PointsStatus sla_points_status = sla::PointsStatus::NoPoints
sla::DrainHoles sla_drain_holes
Vec3d origin_translation
std::vector< ObjectID > volume_ids
CutConnectors cut_connectors
CutObjectBase cut_id
Protected Member Functions
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
Private Member Functions
ModelObject (Model *model)
ModelObject (int)
~ModelObject ()
void assign_new_unique_ids_recursive () override
ModelObject (const ModelObject &rhs)
ModelObject (ModelObject &&rhs)
ModelObject & operator= (const ModelObject &rhs)
ModelObject & operator= (ModelObject &&rhs)
void set_new_unique_id ()
void set_model (Model *model)
ModelObject ()
template<class Archive >
void save (Archive &ar) const
template<class Archive >
void load (Archive &ar)
unsigned int update_instances_print_volume_state (const BuildVolume &build_volume)
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
Model * m_model = nullptr
BoundingBoxf3 m_bounding_box
bool m_bounding_box_valid
BoundingBoxf3 m_raw_bounding_box
bool m_raw_bounding_box_valid
BoundingBoxf3 m_raw_mesh_bounding_box
bool m_raw_mesh_bounding_box_valid
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class Model
class Print
class SLAPrint
class cereal::access
class UndoRedo::StackImpl
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
ModelObject() [1/5]
Slic3r::ModelObject::ModelObject (Model * model) inline explicit private
                                       : m_model(model), printable(true), origin_translation(Vec3d::Zero()),
        m_bounding_box_valid(false), m_raw_bounding_box_valid(false), m_raw_mesh_bounding_box_valid(false)
    {
        assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->layer_height_profile.id().valid());
    }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectID::valid().
ModelObject() [2/5]
Slic3r::ModelObject::ModelObject (int) inline explicit private
                              : ObjectBase(-1), config(-1), layer_height_profile(-1), m_model(nullptr), printable(true), origin_translation(Vec3d::Zero()), m_bounding_box_valid(false), m_raw_bounding_box_valid(false), m_raw_mesh_bounding_box_valid(false)
    {
        assert(this->id().invalid());
        assert(this->config.id().invalid());
        assert(this->layer_height_profile.id().invalid());
    }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectID::invalid().
~ModelObject()
Slic3r::ModelObject::~ModelObject () private
{
    this->clear_volumes();
    this->clear_instances();
}
References clear_instances(), and clear_volumes().
ModelObject() [3/5]
Slic3r::ModelObject::ModelObject (const ModelObject & rhs) inline private
                                        : ObjectBase(-1), config(-1), layer_height_profile(-1), m_model(rhs.m_model) {
      assert(this->id().invalid());
        assert(this->config.id().invalid());
        assert(this->layer_height_profile.id().invalid());
        assert(rhs.id() != rhs.config.id());
        assert(rhs.id() != rhs.layer_height_profile.id());
      this->assign_copy(rhs);
      assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->layer_height_profile.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->layer_height_profile.id());
      assert(this->id() == rhs.id());
        assert(this->config.id() == rhs.config.id());
        assert(this->layer_height_profile.id() == rhs.layer_height_profile.id());
    }
References config, Slic3r::ObjectBase::id(), Slic3r::ObjectID::invalid(), layer_height_profile, and Slic3r::ObjectID::valid().
ModelObject() [4/5]
Slic3r::ModelObject::ModelObject (ModelObject && rhs) inline explicit private
                                            : ObjectBase(-1), config(-1), layer_height_profile(-1) {
      assert(this->id().invalid());
        assert(this->config.id().invalid());
        assert(this->layer_height_profile.id().invalid());
        assert(rhs.id() != rhs.config.id());
        assert(rhs.id() != rhs.layer_height_profile.id());
      this->assign_copy(std::move(rhs));
      assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->layer_height_profile.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->layer_height_profile.id());
      assert(this->id() == rhs.id());
        assert(this->config.id() == rhs.config.id());
        assert(this->layer_height_profile.id() == rhs.layer_height_profile.id());
    }
References Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), Slic3r::ObjectID::invalid(), and Slic3r::ObjectID::valid().
ModelObject() [5/5]
Slic3r::ModelObject::ModelObject () inline private
                :
        ObjectBase(-1), config(-1), layer_height_profile(-1),
        m_model(nullptr), m_bounding_box_valid(false), m_raw_bounding_box_valid(false), m_raw_mesh_bounding_box_valid(false) {
    assert(this->id().invalid());
        assert(this->config.id().invalid());
        assert(this->layer_height_profile.id().invalid());
  }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectID::invalid().
Member Function Documentation
add_instance() [1/3]
ModelInstance * Slic3r::ModelObject::add_instance ()
{
    ModelInstance* i = new ModelInstance(this);
    this->instances.push_back(i);
    this->invalidate_bounding_box();
    // BBS: backup: do not save
    if (this->instances.size() == 1)
        Slic3r::save_object_mesh(*this);
    return i;
}
References instances, invalidate_bounding_box(), and Slic3r::save_object_mesh().
Referenced by Slic3r::_3MF_Importer::_load_model_from_file(), add_instance(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::AMFParserContext::endDocument(), Slic3r::GUI::Plater::increase_instances(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::merge(), and split().
add_instance() [2/3]
ModelInstance * Slic3r::ModelObject::add_instance (const ModelInstance & instance)
{
    ModelInstance* i = new ModelInstance(this, other);
    this->instances.push_back(i);
    this->invalidate_bounding_box();
    return i;
}
References instances, and invalidate_bounding_box().
add_instance() [3/3]
ModelInstance * Slic3r::ModelObject::add_instance (const Vec3d & offset, const Vec3d & scaling_factor, const Vec3d & rotation, const Vec3d & mirror)
{
    auto *instance = add_instance();
    instance->set_offset(offset);
    instance->set_scaling_factor(scaling_factor);
    instance->set_rotation(rotation);
    instance->set_mirror(mirror);
    return instance;
}
References add_instance(), mirror(), and Slic3r::offset().
add_volume() [1/4]
ModelVolume * Slic3r::ModelObject::add_volume (const ModelVolume & volume, ModelVolumeType type = ModelVolumeType::INVALID)
{
    ModelVolume* v = new ModelVolume(this, other);
    if (type != ModelVolumeType::INVALID && v->type() != type)
        v->set_type(type);
    v->cut_info = other.cut_info;
    this->volumes.push_back(v);
  // The volume should already be centered at this point of time when copying shared pointers of the triangle mesh and convex hull.
//  v->center_geometry_after_creation();
//    this->invalidate_bounding_box();
    // BBS: backup
    Slic3r::save_object_mesh(*this);
    return v;
}
References Slic3r::ModelVolume::cut_info, Slic3r::INVALID, Slic3r::save_object_mesh(), Slic3r::ModelVolume::set_type(), Slic3r::ModelVolume::type(), and volumes.
add_volume() [2/4]
ModelVolume * Slic3r::ModelObject::add_volume (const ModelVolume & volume, TriangleMesh && mesh)
{
    ModelVolume* v = new ModelVolume(this, other, std::move(mesh));
    this->volumes.push_back(v);
    v->center_geometry_after_creation();
    this->invalidate_bounding_box();
    // BBS: backup
    Slic3r::save_object_mesh(*this);
    return v;
}
References Slic3r::ModelVolume::center_geometry_after_creation(), invalidate_bounding_box(), mesh(), Slic3r::save_object_mesh(), and volumes.
add_volume() [3/4]
ModelVolume * Slic3r::ModelObject::add_volume (const TriangleMesh & mesh)
{
    ModelVolume* v = new ModelVolume(this, mesh);
    this->volumes.push_back(v);
    v->center_geometry_after_creation();
    this->invalidate_bounding_box();
    // BBS: backup
    Slic3r::save_object_mesh(*this);
    return v;
}
References Slic3r::ModelVolume::center_geometry_after_creation(), invalidate_bounding_box(), mesh(), Slic3r::save_object_mesh(), and volumes.
Referenced by Slic3r::Model::add_object(), Slic3r::Model::add_object(), apply_cut_connectors(), convert_units(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::load_mesh_part(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::load_svg(), make_boolean(), merge(), Slic3r::GUI::ObjectList::merge(), merge_volumes(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), process_connector_cut(), process_modifier_cut(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), segment(), split(), and Slic3r::AMFParserContext::startElement().
add_volume() [4/4]
ModelVolume * Slic3r::ModelObject::add_volume (TriangleMesh && mesh, ModelVolumeType type = ModelVolumeType::MODEL_PART)
{
    ModelVolume* v = new ModelVolume(this, std::move(mesh), type);
    this->volumes.push_back(v);
    v->center_geometry_after_creation();
    this->invalidate_bounding_box();
    // BBS: backup
    Slic3r::save_object_mesh(*this);
    return v;
}
References Slic3r::ModelVolume::center_geometry_after_creation(), invalidate_bounding_box(), mesh(), Slic3r::save_object_mesh(), and volumes.
add_volume_with_shared_mesh()
ModelVolume * Slic3r::ModelObject::add_volume_with_shared_mesh (const ModelVolume & other, ModelVolumeType type = ModelVolumeType::MODEL_PART)
{
    ModelVolume* v = new ModelVolume(this, other.m_mesh);
    if (type != ModelVolumeType::INVALID && v->type() != type)
        v->set_type(type);
    this->volumes.push_back(v);
  // The volume should already be centered at this point of time when copying shared pointers of the triangle mesh and convex hull.
//  v->center_geometry_after_creation();
//    this->invalidate_bounding_box();
    // BBS: backup
    Slic3r::save_object_mesh(*this);
    return v;
}
References Slic3r::INVALID, Slic3r::ModelVolume::m_mesh, Slic3r::save_object_mesh(), Slic3r::ModelVolume::set_type(), Slic3r::ModelVolume::type(), and volumes.
apply_cut_attributes()
void Slic3r::ModelObject::apply_cut_attributes (ModelObjectCutAttributes attributes)
{
    // we don't save cut information, if result will not contains all parts of initial object
    if (!attributes.has(ModelObjectCutAttribute::KeepUpper) ||
        !attributes.has(ModelObjectCutAttribute::KeepLower) ||
        attributes.has(ModelObjectCutAttribute::InvalidateCutInfo))
        return;
    if (cut_id.id().invalid())
        cut_id.init();
    {
        int cut_obj_cnt = -1;
        if (attributes.has(ModelObjectCutAttribute::KeepUpper))
            cut_obj_cnt++;
        if (attributes.has(ModelObjectCutAttribute::KeepLower))
            cut_obj_cnt++;
        if (attributes.has(ModelObjectCutAttribute::CreateDowels))
            cut_obj_cnt++;
        if (cut_obj_cnt > 0)
            cut_id.increase_check_sum(size_t(cut_obj_cnt));
    }
}
References Slic3r::CreateDowels, cut_id, Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::ObjectBase::id(), Slic3r::CutObjectBase::increase_check_sum(), Slic3r::CutObjectBase::init(), Slic3r::ObjectID::invalid(), Slic3r::InvalidateCutInfo, Slic3r::KeepLower, and Slic3r::KeepUpper.
Referenced by cut().
apply_cut_connectors()
void Slic3r::ModelObject::apply_cut_connectors (const std::string & name)
{
    if (cut_connectors.empty())
        return;
    using namespace Geometry;
    size_t connector_id = cut_id.connectors_cnt();
    for (const CutConnector &connector : cut_connectors) {
        TriangleMesh mesh = TriangleMesh(get_connector_mesh(connector.attribs));
        // Mesh will be centered when loading.
        ModelVolume *new_volume = add_volume(std::move(mesh), ModelVolumeType::NEGATIVE_VOLUME);
        Transform3d translate_transform = Transform3d::Identity();
        translate_transform.translate(connector.pos);
        Transform3d scale_transform = Transform3d::Identity();
        scale_transform.scale(Vec3f(connector.radius, connector.radius, connector.height).cast<double>());
        // Transform the new modifier to be aligned inside the instance
        new_volume->set_transformation(translate_transform * connector.rotation_m * scale_transform);
        new_volume->cut_info = {connector.attribs.type, connector.radius, connector.height, connector.radius_tolerance, connector.height_tolerance};
        new_volume->name     = name + "-" + std::to_string(++connector_id);
    }
    cut_id.increase_connectors_cnt(cut_connectors.size());
    // delete all connectors
    cut_connectors.clear();
}
References add_volume(), Slic3r::CutObjectBase::connectors_cnt(), cut_connectors, cut_id, Slic3r::ModelVolume::cut_info, get_connector_mesh(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::CutObjectBase::increase_connectors_cnt(), mesh(), name, Slic3r::ModelVolume::name, Slic3r::NEGATIVE_VOLUME, Slic3r::ModelVolume::CutInfo::radius, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale(), Slic3r::ModelVolume::set_transformation(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::apply_connectors_in_model().
assign_new_unique_ids_recursive()
void Slic3r::ModelObject::assign_new_unique_ids_recursive () override private virtual
Reimplemented from Slic3r::ObjectBase.
{
    this->set_new_unique_id();
    for (ModelVolume *model_volume : this->volumes)
        model_volume->assign_new_unique_ids_recursive();
    for (ModelInstance *model_instance : this->instances)
        model_instance->assign_new_unique_ids_recursive();
    this->layer_height_profile.set_new_unique_id();
}
References instances, layer_height_profile, set_new_unique_id(), Slic3r::ObjectBase::set_new_unique_id(), and volumes.
bake_xy_rotation_into_meshes()
void Slic3r::ModelObject::bake_xy_rotation_into_meshes (size_t instance_idx)
{
    assert(instance_idx < this->instances.size());
  const Geometry::Transformation reference_trafo = this->instances[instance_idx]->get_transformation();
    if (Geometry::is_rotation_ninety_degrees(reference_trafo.get_rotation()))
        // nothing to do, scaling in the world coordinate space is possible in the representation of Geometry::Transformation.
        return;
    bool   left_handed        = reference_trafo.is_left_handed();
    bool   has_mirrorring     = ! reference_trafo.get_mirror().isApprox(Vec3d(1., 1., 1.));
    bool   uniform_scaling    = std::abs(reference_trafo.get_scaling_factor().x() - reference_trafo.get_scaling_factor().y()) < EPSILON &&
                                std::abs(reference_trafo.get_scaling_factor().x() - reference_trafo.get_scaling_factor().z()) < EPSILON;
    double new_scaling_factor = uniform_scaling ? reference_trafo.get_scaling_factor().x() : 1.;
    // Adjust the instances.
    for (size_t i = 0; i < this->instances.size(); ++ i) {
        ModelInstance &model_instance = *this->instances[i];
        model_instance.set_rotation(Vec3d(0., 0., Geometry::rotation_diff_z(reference_trafo.get_rotation(), model_instance.get_rotation())));
        model_instance.set_scaling_factor(Vec3d(new_scaling_factor, new_scaling_factor, new_scaling_factor));
        model_instance.set_mirror(Vec3d(1., 1., 1.));
    }
    // Adjust the meshes.
    // Transformation to be applied to the meshes.
    Eigen::Matrix3d mesh_trafo_3x3           = reference_trafo.get_matrix(true, false, uniform_scaling, ! has_mirrorring).matrix().block<3, 3>(0, 0);
  Transform3d     volume_offset_correction = this->instances[instance_idx]->get_transformation().get_matrix().inverse() * reference_trafo.get_matrix();
    for (ModelVolume *model_volume : this->volumes) {
        const Geometry::Transformation volume_trafo = model_volume->get_transformation();
        bool   volume_left_handed        = volume_trafo.is_left_handed();
        bool   volume_has_mirrorring     = ! volume_trafo.get_mirror().isApprox(Vec3d(1., 1., 1.));
        bool   volume_uniform_scaling    = std::abs(volume_trafo.get_scaling_factor().x() - volume_trafo.get_scaling_factor().y()) < EPSILON &&
                                           std::abs(volume_trafo.get_scaling_factor().x() - volume_trafo.get_scaling_factor().z()) < EPSILON;
        double volume_new_scaling_factor = volume_uniform_scaling ? volume_trafo.get_scaling_factor().x() : 1.;
        // Transform the mesh.
    Matrix3d volume_trafo_3x3 = volume_trafo.get_matrix(true, false, volume_uniform_scaling, !volume_has_mirrorring).matrix().block<3, 3>(0, 0);
        // Following method creates a new shared_ptr<TriangleMesh>
    model_volume->transform_this_mesh(mesh_trafo_3x3 * volume_trafo_3x3, left_handed != volume_left_handed);
        // Reset the rotation, scaling and mirroring.
        model_volume->set_rotation(Vec3d(0., 0., 0.));
        model_volume->set_scaling_factor(Vec3d(volume_new_scaling_factor, volume_new_scaling_factor, volume_new_scaling_factor));
        model_volume->set_mirror(Vec3d(1., 1., 1.));
        // Move the reference point of the volume to compensate for the change of the instance trafo.
        model_volume->set_offset(volume_offset_correction * volume_trafo.get_offset());
        // reset the source to disable reload from disk
        model_volume->source = ModelVolume::Source();
    }
    this->invalidate_bounding_box();
}
References EPSILON, Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_mirror(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::Geometry::Transformation::get_rotation(), Slic3r::ModelInstance::get_rotation(), Slic3r::Geometry::Transformation::get_scaling_factor(), instances, invalidate_bounding_box(), Slic3r::Geometry::Transformation::is_left_handed(), Slic3r::Geometry::is_rotation_ninety_degrees(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::Geometry::rotation_diff_z(), Slic3r::ModelInstance::set_mirror(), Slic3r::ModelInstance::set_rotation(), Slic3r::ModelInstance::set_scaling_factor(), and volumes.
bounding_box()
const BoundingBoxf3 & Slic3r::ModelObject::bounding_box () const
{
    if (! m_bounding_box_valid) {
        m_bounding_box_valid = true;
        BoundingBoxf3 raw_bbox = this->raw_mesh_bounding_box();
        m_bounding_box.reset();
        for (const ModelInstance *i : this->instances)
            m_bounding_box.merge(i->transform_bounding_box(raw_bbox));
    }
    return m_bounding_box;
}
References instances, m_bounding_box, m_bounding_box_valid, Slic3r::BoundingBox3Base< PointClass >::merge(), raw_mesh_bounding_box(), and Slic3r::BoundingBoxBase< PointClass >::reset().
Referenced by Slic3r::GUI::Plater::priv::replace_volume_with_stl(), scale_to_fit(), and Slic3r::GUI::GLCanvas3D::LayersEditing::select_object().
calculate_cut_plane_inverse_matrix()
Transform3d Slic3r::ModelObject::calculate_cut_plane_inverse_matrix (const std::array< Vec3d, 4 > & plane_points)
{
    Vec3d mid_point = {0.0, 0.0, 0.0};
    for (auto pt : plane_points)
        mid_point += pt;
    mid_point /= (double) plane_points.size();
    Vec3d movement = -mid_point;
    Vec3d v01 = plane_points[1] - plane_points[0];
    Vec3d v12 = plane_points[2] - plane_points[1];
    Vec3d plane_normal = v01.cross(v12);
    plane_normal.normalize();
    Vec3d    axis = {0.0, 0.0, 0.0};
    double   phi  = 0.0;
    Matrix3d matrix;
    matrix.setIdentity();
    Geometry::rotation_from_two_vectors(plane_normal, {0.0, 0.0, 1.0}, axis, phi, &matrix);
    Vec3d angles = Geometry::extract_euler_angles(matrix);
    movement = matrix * movement;
    Transform3d transfo;
    transfo.setIdentity();
    transfo.translate(movement);
    transfo.rotate(Eigen::AngleAxisd(angles(2), Vec3d::UnitZ()) * Eigen::AngleAxisd(angles(1), Vec3d::UnitY()) * Eigen::AngleAxisd(angles(0), Vec3d::UnitX()));
    return transfo;
}
References Slic3r::Geometry::extract_euler_angles(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate(), Slic3r::Geometry::rotation_from_two_vectors(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::setIdentity(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate().
Referenced by cut().
center_around_origin()
void Slic3r::ModelObject::center_around_origin (bool include_modifiers = true)
{
    // calculate the displacements needed to
    // center this object around the origin
    const BoundingBoxf3 bb = include_modifiers ? full_raw_mesh_bounding_box() : raw_mesh_bounding_box();
    // Shift is the vector from the center of the bounding box to the origin
    const Vec3d shift = -bb.center();
    this->translate(shift);
    this->origin_translation += shift;
}
References Slic3r::BoundingBox3Base< PointClass >::center(), full_raw_mesh_bounding_box(), origin_translation, raw_mesh_bounding_box(), and translate().
Referenced by Slic3r::GUI::ObjectList::merge(), rotate(), and rotate().
clear_instances()
void Slic3r::ModelObject::clear_instances ()
{
    for (ModelInstance *i : this->instances)
        delete i;
    this->instances.clear();
    this->invalidate_bounding_box();
}
References instances, and invalidate_bounding_box().
Referenced by ~ModelObject(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), and Slic3r::AMFParserContext::endDocument().
clear_volumes()
void Slic3r::ModelObject::clear_volumes ()
{
    for (ModelVolume *v : this->volumes)
        delete v;
    this->volumes.clear();
    this->invalidate_bounding_box();
    // BBS: backup: do not save
    // Slic3r::save_object_mesh(*this);
}
References invalidate_bounding_box(), and volumes.
Referenced by ~ModelObject(), convert_units(), make_boolean(), merge(), merge_volumes(), and segment().
clone_for_cut()
void Slic3r::ModelObject::clone_for_cut (ModelObject ** obj)
{
    (*obj) = ModelObject::new_clone(*this);
    (*obj)->set_model(nullptr);
    (*obj)->sla_support_points.clear();
    (*obj)->sla_drain_holes.clear();
    (*obj)->sla_points_status = sla::PointsStatus::NoPoints;
    (*obj)->clear_volumes();
    (*obj)->input_file.clear();
}
References Slic3r::sla::NoPoints.
Referenced by cut(), and process_connector_cut().
convert_units()
void Slic3r::ModelObject::convert_units (ModelObjectPtrs & new_objects, ConversionType conv_type, std::vector< int > volume_idxs)
{
    BOOST_LOG_TRIVIAL(trace) << "ModelObject::convert_units - start";
    ModelObject* new_object = new_clone(*this);
    float koef = conv_type == ConversionType::CONV_FROM_INCH   ? 25.4f  : conv_type == ConversionType::CONV_TO_INCH  ? 0.0393700787f  :
                 conv_type == ConversionType::CONV_FROM_METER  ? 1000.f : conv_type == ConversionType::CONV_TO_METER ? 0.001f         : 1.f;
    new_object->set_model(nullptr);
    new_object->sla_support_points.clear();
    new_object->sla_drain_holes.clear();
    new_object->sla_points_status = sla::PointsStatus::NoPoints;
    new_object->clear_volumes();
    new_object->input_file.clear();
    int vol_idx = 0;
    for (ModelVolume* volume : volumes) {
        if (!volume->mesh().empty()) {
            TriangleMesh mesh(volume->mesh());
            ModelVolume* vol = new_object->add_volume(mesh);
            vol->name = volume->name;
            vol->set_type(volume->type());
            // Don't copy the config's ID.
            vol->config.assign_config(volume->config);
            assert(vol->config.id().valid());
            assert(vol->config.id() != volume->config.id());
            vol->set_material(volume->material_id(), *volume->material());
            vol->source.input_file = volume->source.input_file;
            vol->source.object_idx = (int)new_objects.size();
            vol->source.volume_idx = vol_idx;
            vol->source.is_converted_from_inches = volume->source.is_converted_from_inches;
            vol->source.is_converted_from_meters = volume->source.is_converted_from_meters;
            vol->source.is_from_builtin_objects = volume->source.is_from_builtin_objects;
            vol->supported_facets.assign(volume->supported_facets);
            vol->seam_facets.assign(volume->seam_facets);
            vol->mmu_segmentation_facets.assign(volume->mmu_segmentation_facets);
            // Perform conversion only if the target "imperial" state is different from the current one.
            // This check supports conversion of "mixed" set of volumes, each with different "imperial" state.
            if (//vol->source.is_converted_from_inches != from_imperial &&
                (volume_idxs.empty() ||
                 std::find(volume_idxs.begin(), volume_idxs.end(), vol_idx) != volume_idxs.end())) {
                vol->scale_geometry_after_creation(koef);
                vol->set_offset(Vec3d(koef, koef, koef).cwiseProduct(volume->get_offset()));
                if (conv_type == ConversionType::CONV_FROM_INCH || conv_type == ConversionType::CONV_TO_INCH)
                    vol->source.is_converted_from_inches = conv_type == ConversionType::CONV_FROM_INCH;
                if (conv_type == ConversionType::CONV_FROM_METER || conv_type == ConversionType::CONV_TO_METER)
                    vol->source.is_converted_from_meters = conv_type == ConversionType::CONV_FROM_METER;
                assert(! vol->source.is_converted_from_inches || ! vol->source.is_converted_from_meters);
            }
            else
                vol->set_offset(volume->get_offset());
        }
        vol_idx ++;
    }
    new_object->invalidate_bounding_box();
    new_objects.push_back(new_object);
    BOOST_LOG_TRIVIAL(trace) << "ModelObject::convert_units - end";
}
References add_volume(), Slic3r::FacetsAnnotation::assign(), Slic3r::ModelConfig::assign_config(), clear_volumes(), Slic3r::ModelVolume::config, Slic3r::CONV_FROM_INCH, Slic3r::CONV_FROM_METER, Slic3r::CONV_TO_INCH, Slic3r::CONV_TO_METER, Slic3r::ObjectBase::id(), input_file, Slic3r::ModelVolume::Source::input_file, int, invalidate_bounding_box(), Slic3r::ModelVolume::Source::is_converted_from_inches, Slic3r::ModelVolume::Source::is_converted_from_meters, Slic3r::ModelVolume::Source::is_from_builtin_objects, mesh(), Slic3r::ModelVolume::mmu_segmentation_facets, Slic3r::ModelVolume::name, Slic3r::sla::NoPoints, Slic3r::ModelVolume::Source::object_idx, Slic3r::ModelVolume::scale_geometry_after_creation(), Slic3r::ModelVolume::seam_facets, Slic3r::ModelVolume::set_material(), set_model(), Slic3r::ModelVolume::set_offset(), Slic3r::ModelVolume::set_type(), sla_drain_holes, sla_points_status, sla_support_points, Slic3r::ModelVolume::source, Slic3r::ModelVolume::supported_facets, Slic3r::trace(), Slic3r::ObjectID::valid(), Slic3r::ModelVolume::Source::volume_idx, and volumes.
convex_hull_2d()
Polygon Slic3r::ModelObject::convex_hull_2d (const Transform3d & trafo_instance) const
{
#if 0
    Points pts;
    for (const ModelVolume* v : volumes) {
        if (v->is_model_part())
            //BBS: use convex hull vertex instead of all
            append(pts, its_convex_hull_2d_above(v->get_convex_hull().its, (trafo_instance * v->get_matrix()).cast<float>(), 0.0f).points);
            //append(pts, its_convex_hull_2d_above(v->mesh().its, (trafo_instance * v->get_matrix()).cast<float>(), 0.0f).points);
    }
    return Geometry::convex_hull(std::move(pts));
#else
    Points pts;
    for (const ModelVolume *v : this->volumes)
        if (v->is_model_part()) {
            const Polygon& volume_hull = v->get_convex_hull_2d(trafo_instance);
            pts.insert(pts.end(), volume_hull.points.begin(), volume_hull.points.end());
        }
    //std::sort(pts.begin(), pts.end(), [](const Point& a, const Point& b) { return a(0) < b(0) || (a(0) == b(0) && a(1) < b(1)); });
    //pts.erase(std::unique(pts.begin(), pts.end(), [](const Point& a, const Point& b) { return a(0) == b(0) && a(1) == b(1); }), pts.end());
    /*std::vector<Points> points;
    //points.push_back(pts);
    Polygon hull = Geometry::convex_hull(std::move(pts));
    static int irun = 0;
    BoundingBox bbox_svg;
    bbox_svg.merge(get_extents(pts));
    bbox_svg.merge(get_extents(hull));
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": bbox_svg.min{%1%,%2%} max{%3%,%4%}, points count %5%")% bbox_svg.min.x()% bbox_svg.min.y()% bbox_svg.max.x()% bbox_svg.max.y()%points[0].size();
    {
        std::stringstream stri;
        stri << "convex_2d_hull_" << irun << ".svg";
        SVG svg(stri.str(), bbox_svg);
        std::vector<Polygon> hulls;
        hulls.push_back(hull);
        svg.draw(to_polylines(points), "blue");
        svg.draw(to_polylines(hulls), "red");
        svg.Close();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": stri %1%, Polygon.size %2%, point[0] {%3%, %4%}, point[1] {%5%, %6%}")% stri.str()% hull.size()% hull[0].x()% hull[0].y()% hull[1].x()% hull[1].y();
    }
    ++ irun;
    return hull;*/
    return Geometry::convex_hull(std::move(pts));
#endif
}
References Slic3r::append(), Slic3r::Geometry::convex_hull(), Slic3r::its_convex_hull_2d_above(), Slic3r::MultiPoint::points, and volumes.
Referenced by Slic3r::ModelInstance::convex_hull_2d(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::ModelInstance::get_arrange_polygon(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
cut()
ModelObjectPtrs Slic3r::ModelObject::cut (size_t instance, std::array< Vec3d, 4 > plane_points, ModelObjectCutAttributes attributes)
{
    if (! attributes.has(ModelObjectCutAttribute::KeepUpper) && ! attributes.has(ModelObjectCutAttribute::KeepLower))
        return {};
    BOOST_LOG_TRIVIAL(trace) << "ModelObject::cut - start";
    // apply cut attributes for object
    apply_cut_attributes(attributes);
    ModelObject* upper{ nullptr };
    if (attributes.has(ModelObjectCutAttribute::KeepUpper))
        clone_for_cut(&upper);
    ModelObject* lower{ nullptr };
    if (attributes.has(ModelObjectCutAttribute::KeepLower) && !attributes.has(ModelObjectCutAttribute::CutToParts))
        clone_for_cut(&lower);
    // Because transformations are going to be applied to meshes directly,
    // we reset transformation of all instances and volumes,
    // except for translation and Z-rotation on instances, which are preserved
    // in the transformation matrix and not applied to the mesh transform.
    // const auto instance_matrix = instances[instance]->get_matrix(true);
    const auto instance_matrix = Geometry::assemble_transform(
        Vec3d::Zero(),  // don't apply offset
        instances[instance]->get_rotation().cwiseProduct(Vec3d(1.0, 1.0, 1.0)),   // BBS: do apply Z-rotation
        instances[instance]->get_scaling_factor(),
        instances[instance]->get_mirror()
    );
    // BBS
    //z -= instances[instance]->get_offset().z();
    for (Vec3d& point : plane_points) {
        point -= instances[instance]->get_offset();
    }
    Transform3d inverse_cut_matrix = calculate_cut_plane_inverse_matrix(plane_points);
    Transform3d cut_matrix = inverse_cut_matrix.inverse();
    std::vector<ModelObject *> dowels;
    // Displacement (in instance coordinates) to be applied to place the upper parts
    Vec3d local_displace = Vec3d::Zero();
    Vec3d local_dowels_displace = Vec3d::Zero();
    for (ModelVolume *volume : volumes) {
        const auto volume_matrix = volume->get_matrix();
        volume->supported_facets.reset();
        volume->seam_facets.reset();
        volume->mmu_segmentation_facets.reset();
        if (! volume->is_model_part()) {
            if (volume->cut_info.is_processed) {
                // Modifiers are not cut, but we still need to add the instance transformation
                // to the modifier volume transformation to preserve their shape properly.
                //Transform3d inverse_cut_matrix = calculate_cut_plane_inverse_matrix(plane_points);
                process_modifier_cut(volume, instance_matrix, inverse_cut_matrix, attributes, upper, lower);
            }
            else {
                process_connector_cut(volume, instance_matrix, cut_matrix, attributes, upper, lower, dowels, local_dowels_displace);
            }
        }
        else if (! volume->mesh().empty()) {
            process_solid_part_cut(volume, instance_matrix, cut_matrix, plane_points, attributes, upper, lower, local_displace);
        }
    }
    ModelObjectPtrs res;
    if (attributes.has(ModelObjectCutAttribute::CutToParts) && !upper->volumes.empty()) {
        reset_instance_transformation(upper, instance, cut_matrix);
        res.push_back(upper);
    }
    else {
        if (attributes.has(ModelObjectCutAttribute::KeepUpper) && upper->volumes.size() > 0) {
            reset_instance_transformation(upper, instance, cut_matrix, attributes.has(ModelObjectCutAttribute::PlaceOnCutUpper),
                                          attributes.has(ModelObjectCutAttribute::FlipUpper), local_displace);
            res.push_back(upper);
        }
        if (attributes.has(ModelObjectCutAttribute::KeepLower) && lower->volumes.size() > 0) {
            reset_instance_transformation(lower, instance, cut_matrix, attributes.has(ModelObjectCutAttribute::PlaceOnCutLower),
                                          attributes.has(ModelObjectCutAttribute::PlaceOnCutLower) ? true : attributes.has(ModelObjectCutAttribute::FlipLower));
            res.push_back(lower);
        }
        if (attributes.has(ModelObjectCutAttribute::CreateDowels) && !dowels.empty()) {
            for (auto dowel : dowels) {
                reset_instance_transformation(dowel, instance, Transform3d::Identity(), false, false, local_dowels_displace);
                local_dowels_displace += dowel->full_raw_mesh_bounding_box().size().cwiseProduct(Vec3d(-1.5, -1.5, 0.0));
                dowel->name += "-Dowel-" + dowel->volumes[0]->name;
                res.push_back(dowel);
            }
        }
    }
    BOOST_LOG_TRIVIAL(trace) << "ModelObject::cut - end";
    synchronize_model_after_cut();
    return res;
}
References apply_cut_attributes(), Slic3r::Geometry::assemble_transform(), calculate_cut_plane_inverse_matrix(), clone_for_cut(), Slic3r::CreateDowels, Slic3r::CutToParts, Slic3r::FlipLower, Slic3r::FlipUpper, Slic3r::enum_bitmask< option_type, typename >::has(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), instances, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::KeepLower, Slic3r::KeepUpper, Slic3r::PlaceOnCutLower, Slic3r::PlaceOnCutUpper, process_connector_cut(), process_modifier_cut(), process_solid_part_cut(), Slic3r::reset_instance_transformation(), synchronize_model_after_cut(), Slic3r::trace(), and volumes.
delete_connectors()
void Slic3r::ModelObject::delete_connectors ()
{
    for (int id = int(this->volumes.size()) - 1; id >= 0; id--) {
        if (volumes[id]->is_cut_connector())
            this->delete_volume(size_t(id));
    }
}
References delete_volume(), and volumes.
delete_instance()
void Slic3r::ModelObject::delete_instance (size_t idx)
{
    ModelInstancePtrs::iterator i = this->instances.begin() + idx;
    delete *i;
    this->instances.erase(i);
    this->invalidate_bounding_box();
}
References instances, and invalidate_bounding_box().
Referenced by delete_last_instance(), Slic3r::GUI::ObjectList::instances_to_separated_object(), and Slic3r::GUI::ObjectList::instances_to_separated_objects().
delete_last_instance()
void Slic3r::ModelObject::delete_last_instance ()
{
    this->delete_instance(this->instances.size() - 1);
}
References delete_instance(), and instances.
Referenced by Slic3r::_3MF_Importer::_load_model_from_file(), and Slic3r::GUI::Plater::decrease_instances().
delete_volume()
void Slic3r::ModelObject::delete_volume (size_t idx)
{
    ModelVolumePtrs::iterator i = this->volumes.begin() + idx;
    delete *i;
    this->volumes.erase(i);
    if (this->volumes.size() == 1)
    {
        // only one volume left
        // we need to collapse the volume transform into the instances transforms because now when selecting this volume
        // it will be seen as a single full instance ans so its volume transform may be ignored
        ModelVolume* v = this->volumes.front();
        Transform3d v_t = v->get_transformation().get_matrix();
        for (ModelInstance* inst : this->instances)
        {
            inst->set_transformation(Geometry::Transformation(inst->get_transformation().get_matrix() * v_t));
        }
        Geometry::Transformation t;
        v->set_transformation(t);
        v->set_new_unique_id();
    }
    this->invalidate_bounding_box();
    // BBS: backup
    Slic3r::save_object_mesh(*this);
}
References Slic3r::Geometry::Transformation::get_matrix(), Slic3r::ModelVolume::get_transformation(), instances, invalidate_bounding_box(), Slic3r::save_object_mesh(), Slic3r::ModelVolume::set_new_unique_id(), Slic3r::ModelVolume::set_transformation(), and volumes.
Referenced by delete_connectors(), Slic3r::GUI::GLGizmoText::delete_temp_preview_text_volume(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoText::gizmo_event(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
ensure_on_bed()
void Slic3r::ModelObject::ensure_on_bed (bool allow_negative_z = false)
{
    double z_offset = 0.0;
    if (allow_negative_z) {
        if (parts_count() == 1) {
            const double min_z = get_min_z();
            const double max_z = get_max_z();
            if (min_z >= SINKING_Z_THRESHOLD || max_z < 0.0)
                z_offset = -min_z;
        }
        else {
            const double max_z = get_max_z();
            if (max_z < SINKING_MIN_Z_THRESHOLD)
                z_offset = SINKING_MIN_Z_THRESHOLD - max_z;
        }
    }
    else
        z_offset = -get_min_z();
    if (z_offset != 0.0)
        translate_instances(z_offset * Vec3d::UnitZ());
}
References get_max_z(), get_min_z(), parts_count(), Slic3r::SINKING_MIN_Z_THRESHOLD, Slic3r::SINKING_Z_THRESHOLD, and translate_instances().
Referenced by Slic3r::GUI::ObjectList::apply_object_instance_transfrom_to_all_volumes(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::ObjectList::fix_through_netfabb(), Slic3r::GUI::OrientJob::get_orient_mesh(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::merge(), Slic3r::orientation::orient(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
facets_count()
size_t Slic3r::ModelObject::facets_count () const
{
    size_t num = 0;
    for (const ModelVolume *v : this->volumes)
        if (v->is_model_part())
            num += v->mesh().facets_count();
    return num;
}
References volumes.
Referenced by Slic3r::GUI::Plater::show_object_info().
full_raw_mesh_bounding_box()
BoundingBoxf3 Slic3r::ModelObject::full_raw_mesh_bounding_box () const
{
  BoundingBoxf3 bb;
  for (const ModelVolume *v : this->volumes)
    bb.merge(v->mesh().transformed_bounding_box(v->get_matrix()));
  return bb;
}
References Slic3r::BoundingBox3Base< PointClass >::merge(), and volumes.
Referenced by center_around_origin(), process_connector_cut(), and process_solid_part_cut().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_backup_id()
int Slic3r::ModelObject::get_backup_id () const
{ return m_model ? get_model()->get_object_backup_id(*this) : -1; }
References get_model(), Slic3r::Model::get_object_backup_id(), and m_model.
get_config_value()
template<typename T > const T * Slic3r::ModelObject::get_config_value (const DynamicPrintConfig & global_config, const std::string & config_option) inline
{
        if (config.has(config_option))
            return static_cast<const T*>(config.option(config_option));
        else
            return global_config.option<T>(config_option);
    }
References config, Slic3r::ModelConfig::has(), Slic3r::ModelConfig::option(), and Slic3r::ConfigBase::option().
get_connector_mesh()
indexed_triangle_set Slic3r::ModelObject::get_connector_mesh (CutConnectorAttributes connector_attributes) static
{
    indexed_triangle_set connector_mesh;
    int   sectorCount {1};
    switch (CutConnectorShape(connector_attributes.shape)) {
    case CutConnectorShape::Triangle:
        sectorCount = 3;
        break;
    case CutConnectorShape::Square:
        sectorCount = 4;
        break;
    case CutConnectorShape::Circle:
        sectorCount = 360;
        break;
    case CutConnectorShape::Hexagon:
        sectorCount = 6;
        break;
    default:
        break;
    }
    if (connector_attributes.style == CutConnectorStyle::Prizm)
        connector_mesh = its_make_cylinder(1.0, 1.0, (2 * PI / sectorCount));
    else if (connector_attributes.type == CutConnectorType::Plug)
        connector_mesh = its_make_cone(1.0, 1.0, (2 * PI / sectorCount));
    else
        connector_mesh = its_make_frustum_dowel(1.0, 1.0, sectorCount);
    return connector_mesh;
}
References Slic3r::Circle, Slic3r::Hexagon, Slic3r::its_make_cone(), Slic3r::its_make_cylinder(), Slic3r::its_make_frustum_dowel(), PI, Slic3r::Plug, Slic3r::Prizm, Slic3r::CutConnectorAttributes::shape, Slic3r::Square, Slic3r::CutConnectorAttributes::style, Slic3r::Triangle, and Slic3r::CutConnectorAttributes::type.
Referenced by apply_cut_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::init_connector_shapes(), and Slic3r::GUI::GLGizmoAdvancedCut::update_connector_shape().
get_export_filename()
std::string Slic3r::ModelObject::get_export_filename () const
{
    std::string ret = input_file;
    if (!name.empty())
    {
        if (ret.empty())
            // input_file was empty, just use name
            ret = name;
        else
        {
            // Replace file name in input_file with name, but keep the path and file extension.
            ret = (boost::filesystem::path(name).parent_path().empty()) ?
                (boost::filesystem::path(ret).parent_path() / name).make_preferred().string() : name;
        }
    }
    return ret;
}
References input_file, and name.
get_instance_max_z()
double Slic3r::ModelObject::get_instance_max_z (size_t instance_idx) const
{
    double max_z = -DBL_MAX;
    const ModelInstance* inst = instances[instance_idx];
    const Transform3d& mi = inst->get_matrix(true);
    for (const ModelVolume* v : volumes) {
        if (!v->is_model_part())
            continue;
        const Transform3d mv = mi * v->get_matrix();
        const TriangleMesh& hull = v->get_convex_hull();
        for (const stl_triangle_vertex_indices& facet : hull.its.indices)
            for (int i = 0; i < 3; ++i)
                max_z = std::max(max_z, (mv * hull.its.vertices[facet[i]].cast<double>()).z());
    }
    return max_z + inst->get_offset(Z);
}
References Slic3r::ModelInstance::get_matrix(), Slic3r::ModelInstance::get_offset(), indexed_triangle_set::indices, instances, Slic3r::TriangleMesh::its, indexed_triangle_set::vertices, volumes, and Slic3r::Z.
Referenced by get_max_z().
get_instance_min_z()
double Slic3r::ModelObject::get_instance_min_z (size_t instance_idx) const
{
    double min_z = DBL_MAX;
    const ModelInstance* inst = instances[instance_idx];
    const Transform3d& mi = inst->get_matrix(true);
    for (const ModelVolume* v : volumes) {
        if (!v->is_model_part())
            continue;
        const Transform3d mv = mi * v->get_matrix();
        const TriangleMesh& hull = v->get_convex_hull();
        //BBS: in some case the convex hull is empty due to the qhull algo
        //use the original mesh instead
        //TODO: when the vertex's x/y/z are all the same, the run_qhull can not get correct result
        //we need to find another algo then
        if (hull.its.indices.size() == 0) {
            const TriangleMesh& mesh = v->mesh();
            for (const stl_triangle_vertex_indices& facet : mesh.its.indices)
                for (int i = 0; i < 3; ++i)
                    min_z = std::min(min_z, (mv * mesh.its.vertices[facet[i]].cast<double>()).z());
        }
        else {
            for (const stl_triangle_vertex_indices& facet : hull.its.indices)
                for (int i = 0; i < 3; ++i)
                    min_z = std::min(min_z, (mv * hull.its.vertices[facet[i]].cast<double>()).z());
        }
    }
    //BBS: add some logic to avoid wrong compute for min_z
    if (min_z == DBL_MAX)
        min_z = 0;
    return min_z + inst->get_offset(Z);
}
References Slic3r::ModelInstance::get_matrix(), Slic3r::ModelInstance::get_offset(), indexed_triangle_set::indices, instances, Slic3r::TriangleMesh::its, mesh(), indexed_triangle_set::vertices, volumes, and Slic3r::Z.
Referenced by Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), and get_min_z().
get_max_z()
double Slic3r::ModelObject::get_max_z () const
{
    if (instances.empty())
        return 0.0;
    else {
        double max_z = -DBL_MAX;
        for (size_t i = 0; i < instances.size(); ++i) {
            max_z = std::max(max_z, get_instance_max_z(i));
        }
        return max_z;
    }
}
References get_instance_max_z(), and instances.
Referenced by ensure_on_bed().
get_min_z()
double Slic3r::ModelObject::get_min_z () const
{
    if (instances.empty())
        return 0.0;
    else {
        double min_z = DBL_MAX;
        for (size_t i = 0; i < instances.size(); ++i) {
            min_z = std::min(min_z, get_instance_min_z(i));
        }
        return min_z;
    }
}
References get_instance_min_z(), and instances.
Referenced by ensure_on_bed().
get_model() [1/2]
Model * Slic3r::ModelObject::get_model () inline
{ return m_model; }
References m_model.
Referenced by Slic3r::Model::add_object(), get_backup_id(), Slic3r::GUI::ObjectList::instances_to_separated_object(), and Slic3r::GUI::ObjectList::instances_to_separated_objects().
get_model() [2/2]
const Model * Slic3r::ModelObject::get_model () const inline
{ return m_model; }
References m_model.
get_object_stl_stats()
TriangleMeshStats Slic3r::ModelObject::get_object_stl_stats () const
{
    TriangleMeshStats full_stats;
    full_stats.volume = 0.f;
    // fill full_stats from all objet's meshes
    for (ModelVolume* volume : this->volumes)
    {
        const TriangleMeshStats& stats = volume->mesh().stats();
        // initialize full_stats (for repaired errors)
        full_stats.open_edges           += stats.open_edges;
        full_stats.repaired_errors.merge(stats.repaired_errors);
        // another used satistics value
        if (volume->is_model_part()) {
            Transform3d trans = instances.empty() ? volume->get_matrix() : (volume->get_matrix() * instances[0]->get_matrix());
            full_stats.volume           += stats.volume * std::fabs(trans.matrix().block(0, 0, 3, 3).determinant());
            full_stats.number_of_parts  += stats.number_of_parts;
        }
    }
    return full_stats;
}
References instances, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::RepairedMeshErrors::merge(), Slic3r::TriangleMeshStats::number_of_parts, Slic3r::TriangleMeshStats::open_edges, Slic3r::TriangleMeshStats::repaired_errors, Slic3r::TriangleMeshStats::volume, and volumes.
Referenced by Slic3r::GUI::ObjectList::delete_from_model_and_list(), get_repaired_errors_count(), and Slic3r::GUI::Plater::show_object_info().
get_repaired_errors_count()
int Slic3r::ModelObject::get_repaired_errors_count (const int vol_idx = -1) const
{
    if (vol_idx >= 0)
        return this->volumes[vol_idx]->get_repaired_errors_count();
    const RepairedMeshErrors& stats = get_object_stl_stats().repaired_errors;
    return  stats.degenerate_facets + stats.edges_fixed     + stats.facets_removed +
            stats.facets_reversed + stats.backwards_edges;
}
References Slic3r::RepairedMeshErrors::backwards_edges, Slic3r::RepairedMeshErrors::degenerate_facets, Slic3r::RepairedMeshErrors::edges_fixed, Slic3r::RepairedMeshErrors::facets_removed, Slic3r::RepairedMeshErrors::facets_reversed, get_object_stl_stats(), Slic3r::TriangleMeshStats::repaired_errors, and volumes.
Referenced by Slic3r::GUI::ObjectList::fix_through_netfabb().
has_connectors()
bool Slic3r::ModelObject::has_connectors () const
{
    assert(is_cut());
    for (const ModelVolume *v : this->volumes)
        if (v->cut_info.is_connector) return true;
    return false;
}
References is_cut(), and volumes.
Referenced by Slic3r::GUI::ObjectList::update_info_items().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), ModelObject(), ModelObject(), ModelObject(), ModelObject(), ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), is_cut(), Slic3r::CutObjectBase::is_equal(), load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), operator=(), operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
instance_bounding_box() [1/2]
BoundingBoxf3 Slic3r::ModelObject::instance_bounding_box (const ModelInstance & instance, bool dont_translate = false) const
{
    BoundingBoxf3 bbox;
    const auto& inst_mat = instance.get_transformation().get_matrix(dont_translate);
    for (auto vol : this->volumes) {
        if (vol->is_model_part())
            bbox.merge(vol->mesh().transformed_bounding_box(inst_mat * vol->get_matrix()));
    }
    return bbox;
}
References Slic3r::Geometry::Transformation::get_matrix(), Slic3r::ModelInstance::get_transformation(), Slic3r::BoundingBox3Base< PointClass >::merge(), and volumes.
instance_bounding_box() [2/2]
BoundingBoxf3 Slic3r::ModelObject::instance_bounding_box (size_t instance_idx, bool dont_translate = false) const
{
    return instance_bounding_box(*this->instances[instance_idx], dont_translate);
}
References instance_bounding_box(), and instances.
Referenced by Slic3r::CalibPressureAdvancePattern::_refresh_starting_point(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), instance_bounding_box(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::on_update(), and Slic3r::GUI::Selection::paste_volumes_from_clipboard().
instance_convex_hull_bounding_box()
BoundingBoxf3 Slic3r::ModelObject::instance_convex_hull_bounding_box (size_t instance_idx, bool dont_translate = false) const
{
    BoundingBoxf3 bb;
    const Transform3d& inst_matrix = this->instances[instance_idx]->get_transformation().get_matrix(dont_translate);
    for (ModelVolume *v : this->volumes)
    {
        if (v->is_model_part())
            bb.merge(v->get_convex_hull().transformed_bounding_box(inst_matrix * v->get_matrix()));
    }
    return bb;
}
References instances, Slic3r::BoundingBox3Base< PointClass >::merge(), and volumes.
Referenced by Slic3r::GUI::Selection::paste_objects_from_clipboard(), and Slic3r::GUI::Plater::show_object_info().
invalidate_bounding_box()
void Slic3r::ModelObject::invalidate_bounding_box () inline
{ m_bounding_box_valid = false; m_raw_bounding_box_valid = false; m_raw_mesh_bounding_box_valid = false; }
References m_bounding_box_valid, m_raw_bounding_box_valid, and m_raw_mesh_bounding_box_valid.
Referenced by add_instance(), add_instance(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), add_volume(), add_volume(), add_volume(), Slic3r::Print::apply(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), bake_xy_rotation_into_meshes(), clear_instances(), clear_volumes(), convert_units(), delete_instance(), delete_volume(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::GUI::ObjectList::load_mesh_object(), merge_volumes(), mirror(), rotate(), rotate(), scale(), scale_mesh_after_creation(), segment(), and translate_instance().
invalidate_cut()
void Slic3r::ModelObject::invalidate_cut ()
{
    this->cut_id.invalidate();
    for (ModelVolume *volume : this->volumes)
        volume->invalidate_cut_info();
}
References cut_id, Slic3r::CutObjectBase::invalidate(), and volumes.
is_cut()
bool Slic3r::ModelObject::is_cut () const inline
{ return cut_id.id().valid(); }
References cut_id, Slic3r::ObjectBase::id(), and Slic3r::ObjectID::valid().
Referenced by Slic3r::GUI::ObjectList::add_volumes_to_object_in_list(), Slic3r::GUI::ObjectList::del_subobject_from_object(), Slic3r::GUI::ObjectList::delete_all_connectors_for_object(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ObjectList::fix_cut_selection(), has_connectors(), Slic3r::GUI::ObjectList::invalidate_cut_info_for_object(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::update_info_items().
is_fdm_support_painted()
bool Slic3r::ModelObject::is_fdm_support_painted () const
{
    return std::any_of(this->volumes.cbegin(), this->volumes.cend(), [](const ModelVolume *mv) { return mv->is_fdm_support_painted(); });
}
References volumes.
is_mm_painted()
bool Slic3r::ModelObject::is_mm_painted () const
{
    return std::any_of(this->volumes.cbegin(), this->volumes.cend(), [](const ModelVolume *mv) { return mv->is_mm_painted(); });
}
References volumes.
Referenced by Slic3r::Print::apply(), and Slic3r::PrintObject::is_mm_painted().
is_multiparts()
bool Slic3r::ModelObject::is_multiparts () const inline
{ return volumes.size() > 1; }
References volumes.
is_seam_painted()
bool Slic3r::ModelObject::is_seam_painted () const
{
    return std::any_of(this->volumes.cbegin(), this->volumes.cend(), [](const ModelVolume *mv) { return mv->is_seam_painted(); });
}
References volumes.
load()
template<class Archive > void Slic3r::ModelObject::load (Archive & ar) inline private
{
        ar(cereal::base_class<ObjectBase>(this));
        Internal::StaticSerializationWrapper<ModelConfigObject> config_wrapper(config);
        Internal::StaticSerializationWrapper<LayerHeightProfile> layer_heigth_profile_wrapper(layer_height_profile);
        // BBS: add backup, check modify
        SaveObjectGaurd gaurd(*this);
        ar(name, module_name, input_file, instances, volumes, config_wrapper, layer_config_ranges, layer_heigth_profile_wrapper,
            sla_support_points, sla_points_status, sla_drain_holes, printable, origin_translation,
            m_bounding_box, m_bounding_box_valid, m_raw_bounding_box, m_raw_bounding_box_valid, m_raw_mesh_bounding_box, m_raw_mesh_bounding_box_valid,
            cut_connectors, cut_id);
        std::vector<ObjectID> volume_ids2;
        std::transform(volumes.begin(), volumes.end(), std::back_inserter(volume_ids2), std::mem_fn(&ObjectBase::id));
        if (volume_ids != volume_ids2)
            Slic3r::save_object_mesh(*this);
        volume_ids.clear();
    }
References config, cut_connectors, cut_id, Slic3r::ObjectBase::id(), input_file, instances, layer_config_ranges, layer_height_profile, m_bounding_box, m_bounding_box_valid, m_raw_bounding_box, m_raw_bounding_box_valid, m_raw_mesh_bounding_box, m_raw_mesh_bounding_box_valid, module_name, name, origin_translation, printable, Slic3r::save_object_mesh(), sla_drain_holes, sla_points_status, sla_support_points, volume_ids, and volumes.
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
make_boolean()
bool Slic3r::ModelObject::make_boolean (ModelObject * cut_object, const std::string & boolean_opts)
{
    // merge meshes into single volume instead of multi-parts object
    if (this->volumes.size() != 1) {
        // we can't merge meshes if there's not just one volume
        return false;
    }
    std::vector<TriangleMesh> new_meshes;
    const TriangleMesh &cut_mesh = cut_object->mesh();
    MeshBoolean::mcut::make_boolean(this->mesh(), cut_mesh, new_meshes, boolean_opts);
    this->clear_volumes();
    int i = 1;
    for (TriangleMesh &mesh : new_meshes) {
        ModelVolume *vol = this->add_volume(mesh);
        vol->name        = this->name + "_" + std::to_string(i++);
    }
    return true;
}
References add_volume(), clear_volumes(), Slic3r::cut_mesh(), Slic3r::MeshBoolean::mcut::make_boolean(), mesh(), name, Slic3r::ModelVolume::name, and volumes.
materials_count()
size_t Slic3r::ModelObject::materials_count () const
{
    std::set<t_model_material_id> material_ids;
    for (const ModelVolume *v : this->volumes)
        material_ids.insert(v->material_id());
    return material_ids.size();
}
References volumes.
merge()
void Slic3r::ModelObject::merge ()
{
    if (this->volumes.size() == 1) {
        // We can't merge meshes if there's just one volume
        return;
    }
    TriangleMesh mesh;
    for (ModelVolume* volume : volumes)
        if (!volume->mesh().empty())
            mesh.merge(volume->mesh());
    this->clear_volumes();
    ModelVolume* vol = this->add_volume(mesh);
    if (!vol)
        return;
}
References add_volume(), clear_volumes(), Slic3r::TriangleMesh::merge(), mesh(), and volumes.
Referenced by Slic3r::GUI::ObjectList::merge().
merge_volumes()
ModelObjectPtrs Slic3r::ModelObject::merge_volumes (std::vector< int > & vol_indeces)
{
    ModelObjectPtrs res;
    if (this->volumes.size() == 1) {
        // We can't merge meshes if there's just one volume
        return res;
    }
    ModelObject* upper = ModelObject::new_clone(*this);
    upper->set_model(nullptr);
    upper->sla_support_points.clear();
    upper->sla_drain_holes.clear();
    upper->sla_points_status = sla::PointsStatus::NoPoints;
    upper->clear_volumes();
    upper->input_file.clear();
#if 1
    TriangleMesh mesh;
    for (int i : vol_indeces) {
        auto volume = volumes[i];
        if (!volume->mesh().empty()) {
            const auto volume_matrix = volume->get_matrix();
            TriangleMesh mesh_(volume->mesh());
            mesh_.transform(volume_matrix, true);
            volume->reset_mesh();
            mesh.merge(mesh_);
        }
    }
#else
    std::vector<TriangleMesh> meshes;
    for (int i : vol_indeces) {
        auto volume = volumes[i];
        if (!volume->mesh().empty())
            meshes.emplace_back(volume->mesh());
    }
    TriangleMesh mesh = MeshBoolean::cgal::merge(meshes);
#endif
    ModelVolume* vol = upper->add_volume(mesh);
    for (int i = 0; i < volumes.size();i++) {
        if (std::find(vol_indeces.begin(), vol_indeces.end(), i) != vol_indeces.end()) {
            vol->name = volumes[i]->name + "_merged";
            vol->config.assign_config(volumes[i]->config);
        }
        else
            upper->add_volume(*volumes[i]);
    }
    upper->invalidate_bounding_box();
    res.push_back(upper);
    return res;
}
References add_volume(), Slic3r::ModelConfig::assign_config(), clear_volumes(), config, Slic3r::ModelVolume::config, input_file, invalidate_bounding_box(), Slic3r::TriangleMesh::merge(), Slic3r::MeshBoolean::cgal::merge(), mesh(), Slic3r::ModelVolume::name, Slic3r::sla::NoPoints, set_model(), sla_drain_holes, sla_points_status, sla_support_points, Slic3r::TriangleMesh::transform(), and volumes.
Referenced by Slic3r::GUI::ObjectList::merge_volumes().
mesh()
TriangleMesh Slic3r::ModelObject::mesh () const
{
    TriangleMesh mesh;
    TriangleMesh raw_mesh = this->raw_mesh();
    for (const ModelInstance *i : this->instances) {
        TriangleMesh m = raw_mesh;
        i->transform_mesh(&m);
        mesh.merge(m);
    }
    return mesh;
}
References instances, Slic3r::TriangleMesh::merge(), mesh(), and raw_mesh().
Referenced by add_volume(), add_volume(), add_volume(), apply_cut_connectors(), convert_units(), get_instance_min_z(), make_boolean(), merge(), merge_volumes(), mesh(), Slic3r::orientation::orient(), Slic3r::orientation::orient(), print_info(), process_volume_cut(), raw_mesh(), segment(), split(), Slic3r::store_obj(), and Slic3r::store_stl().
mirror()
void Slic3r::ModelObject::mirror (Axis axis)
{
    for (ModelVolume *v : this->volumes) {
        v->mirror(axis);
    }
    this->invalidate_bounding_box();
}
References invalidate_bounding_box(), and volumes.
Referenced by add_instance().
operator=() [1/2]
ModelObject & Slic3r::ModelObject::operator= (const ModelObject & rhs) inline private
{
      this->assign_copy(rhs);
      m_model = rhs.m_model;
      assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->layer_height_profile.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->layer_height_profile.id());
      assert(this->id() == rhs.id());
        assert(this->config.id() == rhs.config.id());
        assert(this->layer_height_profile.id() == rhs.layer_height_profile.id());
      return *this;
    }
References config, Slic3r::ObjectBase::id(), layer_height_profile, m_model, and Slic3r::ObjectID::valid().
operator=() [2/2]
ModelObject & Slic3r::ModelObject::operator= (ModelObject && rhs) inline private
{
      this->assign_copy(std::move(rhs));
      m_model = rhs.m_model;
      assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->layer_height_profile.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->layer_height_profile.id());
      assert(this->id() == rhs.id());
        assert(this->config.id() == rhs.config.id());
        assert(this->layer_height_profile.id() == rhs.layer_height_profile.id());
      return *this;
    }
References Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), m_model, and Slic3r::ObjectID::valid().
parts_count()
size_t Slic3r::ModelObject::parts_count () const
{
    size_t num = 0;
    for (const ModelVolume* v : this->volumes)
        if (v->is_model_part())
            ++num;
    return num;
}
References volumes.
Referenced by ensure_on_bed().
print_info()
void Slic3r::ModelObject::print_info () const
{
    using namespace std;
    cout << fixed;
    boost::nowide::cout << "[" << boost::filesystem::path(this->input_file).filename().string() << "]" << endl;
    TriangleMesh mesh = this->raw_mesh();
    BoundingBoxf3 bb = mesh.bounding_box();
    Vec3d size = bb.size();
    cout << "size_x = " << size(0) << endl;
    cout << "size_y = " << size(1) << endl;
    cout << "size_z = " << size(2) << endl;
    cout << "min_x = " << bb.min(0) << endl;
    cout << "min_y = " << bb.min(1) << endl;
    cout << "min_z = " << bb.min(2) << endl;
    cout << "max_x = " << bb.max(0) << endl;
    cout << "max_y = " << bb.max(1) << endl;
    cout << "max_z = " << bb.max(2) << endl;
    cout << "number_of_facets = " << mesh.facets_count() << endl;
    cout << "manifold = "   << (mesh.stats().manifold() ? "yes" : "no") << endl;
    if (! mesh.stats().manifold())
        cout << "open_edges = " << mesh.stats().open_edges << endl;
    if (mesh.stats().repaired()) {
        const RepairedMeshErrors& stats = mesh.stats().repaired_errors;
        if (stats.degenerate_facets > 0)
            cout << "degenerate_facets = "  << stats.degenerate_facets << endl;
        if (stats.edges_fixed > 0)
            cout << "edges_fixed = "        << stats.edges_fixed       << endl;
        if (stats.facets_removed > 0)
            cout << "facets_removed = "     << stats.facets_removed    << endl;
        if (stats.facets_reversed > 0)
            cout << "facets_reversed = "    << stats.facets_reversed   << endl;
        if (stats.backwards_edges > 0)
            cout << "backwards_edges = "    << stats.backwards_edges   << endl;
    }
    cout << "number_of_parts =  " << mesh.stats().number_of_parts << endl;
    cout << "volume = "           << mesh.volume()                << endl;
}
References Slic3r::RepairedMeshErrors::backwards_edges, Slic3r::TriangleMesh::bounding_box(), Slic3r::RepairedMeshErrors::degenerate_facets, Slic3r::RepairedMeshErrors::edges_fixed, Slic3r::TriangleMesh::facets_count(), Slic3r::RepairedMeshErrors::facets_removed, Slic3r::RepairedMeshErrors::facets_reversed, input_file, Slic3r::TriangleMeshStats::manifold(), Slic3r::BoundingBoxBase< PointClass >::max, mesh(), Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::TriangleMeshStats::number_of_parts, Slic3r::TriangleMeshStats::open_edges, raw_mesh(), Slic3r::TriangleMeshStats::repaired(), Slic3r::TriangleMeshStats::repaired_errors, Slic3r::BoundingBox3Base< PointClass >::size(), size, Slic3r::TriangleMesh::stats(), and Slic3r::TriangleMesh::volume().
process_connector_cut()
void Slic3r::ModelObject::process_connector_cut (ModelVolume * volume, const Transform3d & instance_matrix, const Transform3d & cut_matrix, ModelObjectCutAttributes attributes, ModelObject * upper, ModelObject * lower, std::vector< ModelObject * > & dowels, Vec3d & local_dowels_displace)
{
    assert(volume->cut_info.is_connector);
    volume->cut_info.set_processed();
    const auto volume_matrix = volume->get_matrix();
    // ! Don't apply instance transformation for the conntectors.
    // This transformation is already there
    if (volume->cut_info.connector_type != CutConnectorType::Dowel) {
        if (attributes.has(ModelObjectCutAttribute::KeepUpper)) {
            ModelVolume *vol = upper->add_volume(*volume);
            vol->set_transformation(volume_matrix);
            vol->apply_tolerance();
        }
        if (attributes.has(ModelObjectCutAttribute::KeepLower)) {
            ModelVolume *vol = lower->add_volume(*volume);
            vol->set_transformation(volume_matrix);
            // for lower part change type of connector from NEGATIVE_VOLUME to MODEL_PART if this connector is a plug
            vol->set_type(ModelVolumeType::MODEL_PART);
        }
    }
    else {
        if (attributes.has(ModelObjectCutAttribute::CreateDowels)) {
            ModelObject *dowel{nullptr};
            // Clone the object to duplicate instances, materials etc.
            clone_for_cut(&dowel);
            // add one more solid part same as connector if this connector is a dowel
            ModelVolume *vol = dowel->add_volume(*volume);
            vol->set_type(ModelVolumeType::MODEL_PART);
            // But discard rotation and Z-offset for this volume
            vol->set_rotation(Vec3d::Zero());
            vol->set_offset(Z, 0.0);
            // Compute the displacement (in instance coordinates) to be applied to place the dowels
            local_dowels_displace = lower->full_raw_mesh_bounding_box().size().cwiseProduct(Vec3d(1.0, 1.0, 0.0));
            dowels.push_back(dowel);
        }
        // Cut the dowel
        volume->apply_tolerance();
        // Perform cut
        TriangleMesh upper_mesh, lower_mesh;
        process_volume_cut(volume, Transform3d::Identity(), cut_matrix, attributes, upper_mesh, lower_mesh);
        // add small Z offset to better preview
        upper_mesh.translate((-0.05 * Vec3d::UnitZ()).cast<float>());
        lower_mesh.translate((0.05 * Vec3d::UnitZ()).cast<float>());
        // Add cut parts to the related objects
        add_cut_volume(upper_mesh, upper, volume, cut_matrix, "_A", volume->type());
        add_cut_volume(lower_mesh, lower, volume, cut_matrix, "_B", volume->type());
    }
}
References Slic3r::add_cut_volume(), add_volume(), Slic3r::ModelVolume::apply_tolerance(), clone_for_cut(), Slic3r::CreateDowels, Slic3r::Dowel, full_raw_mesh_bounding_box(), Slic3r::enum_bitmask< option_type, typename >::has(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::KeepLower, Slic3r::KeepUpper, Slic3r::MODEL_PART, process_volume_cut(), Slic3r::ModelVolume::set_offset(), Slic3r::ModelVolume::set_rotation(), Slic3r::ModelVolume::set_transformation(), Slic3r::ModelVolume::set_type(), Slic3r::BoundingBox3Base< PointClass >::size(), Slic3r::TriangleMesh::translate(), and Slic3r::Z.
Referenced by cut().
process_modifier_cut()
void Slic3r::ModelObject::process_modifier_cut (ModelVolume * volume, const Transform3d & instance_matrix, const Transform3d & inverse_cut_matrix, ModelObjectCutAttributes attributes, ModelObject * upper, ModelObject * lower)
{
    const auto volume_matrix = instance_matrix * volume->get_matrix();
    // Modifiers are not cut, but we still need to add the instance transformation
    // to the modifier volume transformation to preserve their shape properly.
    volume->set_transformation(Geometry::Transformation(volume_matrix));
    if (attributes.has(ModelObjectCutAttribute::CutToParts)) {
        upper->add_volume(*volume);
        return;
    }
    // Some logic for the negative volumes/connectors. Add only needed modifiers
    auto bb = volume->mesh().transformed_bounding_box(inverse_cut_matrix * volume_matrix);
    bool is_crossed_by_cut = bb.min[Z] <= 0 && bb.max[Z] >= 0;
    if (attributes.has(ModelObjectCutAttribute::KeepUpper) && (bb.min[Z] >= 0 || is_crossed_by_cut))
        upper->add_volume(*volume);
    if (attributes.has(ModelObjectCutAttribute::KeepLower) && (bb.max[Z] <= 0 || is_crossed_by_cut))
        lower->add_volume(*volume);
}
References add_volume(), Slic3r::CutToParts, Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::KeepLower, Slic3r::KeepUpper, and Slic3r::Z.
Referenced by cut().
process_solid_part_cut()
void Slic3r::ModelObject::process_solid_part_cut (ModelVolume * volume, const Transform3d & instance_matrix, const Transform3d & cut_matrix, const std::array< Vec3d, 4 > & plane_points, ModelObjectCutAttributes attributes, ModelObject * upper, ModelObject * lower, Vec3d & local_displace)
{
    // Perform cut
    TriangleMesh upper_mesh, lower_mesh;
    process_volume_cut(volume, instance_matrix, cut_matrix, attributes, upper_mesh, lower_mesh);
    // Add required cut parts to the objects
    if (attributes.has(ModelObjectCutAttribute::CutToParts)) {
        add_cut_volume(upper_mesh, upper, volume, cut_matrix, "_A");
        add_cut_volume(lower_mesh, upper, volume, cut_matrix, "_B");
        return;
    }
    if (attributes.has(ModelObjectCutAttribute::KeepUpper))
        add_cut_volume(upper_mesh, upper, volume, cut_matrix);
    if (attributes.has(ModelObjectCutAttribute::KeepLower) && !lower_mesh.empty()) {
        add_cut_volume(lower_mesh, lower, volume, cut_matrix);
        // Compute the displacement (in instance coordinates) to be applied to place the upper parts
        // The upper part displacement is set to half of the lower part bounding box
        // this is done in hope at least a part of the upper part will always be visible and draggable
        local_displace = lower->full_raw_mesh_bounding_box().size().cwiseProduct(Vec3d(-0.5, -0.5, 0.0));
    }
}
References Slic3r::add_cut_volume(), Slic3r::CutToParts, Slic3r::TriangleMesh::empty(), full_raw_mesh_bounding_box(), Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::KeepLower, Slic3r::KeepUpper, process_volume_cut(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by cut().
process_volume_cut()
void Slic3r::ModelObject::process_volume_cut (ModelVolume * volume, const Transform3d & instance_matrix, const Transform3d & cut_matrix, ModelObjectCutAttributes attributes, TriangleMesh & upper_mesh, TriangleMesh & lower_mesh)
{
    const auto volume_matrix = volume->get_matrix();
    using namespace Geometry;
    const Geometry::Transformation cut_transformation = Geometry::Transformation(cut_matrix);
    const Transform3d invert_cut_matrix = cut_transformation.get_matrix(true, false, true, true).inverse()
                                          * translation_transform(-1 * cut_transformation.get_offset());
    // Transform the mesh by the combined transformation matrix.
    // Flip the triangles in case the composite transformation is left handed.
    TriangleMesh mesh(volume->mesh());
    mesh.transform(invert_cut_matrix * instance_matrix * volume_matrix, true);
    indexed_triangle_set upper_its, lower_its;
    cut_mesh(mesh.its, 0.0f, &upper_its, &lower_its);
    if (attributes.has(ModelObjectCutAttribute::KeepUpper))
        upper_mesh = TriangleMesh(upper_its);
    if (attributes.has(ModelObjectCutAttribute::KeepLower))
        lower_mesh = TriangleMesh(lower_its);
}
References Slic3r::cut_mesh(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::enum_bitmask< option_type, typename >::has(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::TriangleMesh::its, Slic3r::KeepLower, Slic3r::KeepUpper, mesh(), and Slic3r::TriangleMesh::transform().
Referenced by process_connector_cut(), and process_solid_part_cut().
raw_bounding_box()
const BoundingBoxf3 & Slic3r::ModelObject::raw_bounding_box () const
{
    if (! m_raw_bounding_box_valid) {
        m_raw_bounding_box_valid = true;
        m_raw_bounding_box.reset();
        if (this->instances.empty())
            throw Slic3r::InvalidArgument("Can't call raw_bounding_box() with no instances");
        const Transform3d& inst_matrix = this->instances.front()->get_transformation().get_matrix(true);
        for (const ModelVolume *v : this->volumes)
            if (v->is_model_part())
                m_raw_bounding_box.merge(v->mesh().transformed_bounding_box(inst_matrix * v->get_matrix()));
    }
  return m_raw_bounding_box;
}
References instances, m_raw_bounding_box, m_raw_bounding_box_valid, Slic3r::BoundingBox3Base< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::reset(), and volumes.
Referenced by Slic3r::PrintObject::PrintObject().
raw_indexed_triangle_set()
indexed_triangle_set Slic3r::ModelObject::raw_indexed_triangle_set () const
{
    size_t num_vertices = 0;
    size_t num_faces    = 0;
    for (const ModelVolume *v : this->volumes)
        if (v->is_model_part()) {
            num_vertices += v->mesh().its.vertices.size();
            num_faces    += v->mesh().its.indices.size();
        }
    indexed_triangle_set out;
    out.vertices.reserve(num_vertices);
    out.indices.reserve(num_faces);
    for (const ModelVolume *v : this->volumes)
        if (v->is_model_part()) {
            size_t i = out.vertices.size();
            size_t j = out.indices.size();
            append(out.vertices, v->mesh().its.vertices);
            append(out.indices,  v->mesh().its.indices);
            auto m = v->get_matrix();
            for (; i < out.vertices.size(); ++ i)
                out.vertices[i] = (m * out.vertices[i].cast<double>()).cast<float>().eval();
            if (v->is_left_handed()) {
                for (; j < out.indices.size(); ++ j)
                    std::swap(out.indices[j][0], out.indices[j][1]);
            }
        }
    return out;
}
References Slic3r::append(), out, indexed_triangle_set::vertices, and volumes.
raw_mesh()
TriangleMesh Slic3r::ModelObject::raw_mesh () const
{
    TriangleMesh mesh;
    for (const ModelVolume *v : this->volumes)
        if (v->is_model_part())
        {
            TriangleMesh vol_mesh(v->mesh());
            vol_mesh.transform(v->get_matrix());
            mesh.merge(vol_mesh);
        }
    return mesh;
}
References Slic3r::TriangleMesh::merge(), mesh(), Slic3r::TriangleMesh::transform(), and volumes.
Referenced by Slic3r::SLAPrintObject::SLAPrintObject(), Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate(), mesh(), print_info(), and Slic3r::GUI::GLGizmoCut::update_contours().
raw_mesh_bounding_box()
const BoundingBoxf3 & Slic3r::ModelObject::raw_mesh_bounding_box () const
{
    if (! m_raw_mesh_bounding_box_valid) {
        m_raw_mesh_bounding_box_valid = true;
        m_raw_mesh_bounding_box.reset();
        for (const ModelVolume *v : this->volumes)
            if (v->is_model_part())
                m_raw_mesh_bounding_box.merge(v->mesh().transformed_bounding_box(v->get_matrix()));
    }
    return m_raw_mesh_bounding_box;
}
References m_raw_mesh_bounding_box, m_raw_mesh_bounding_box_valid, Slic3r::BoundingBox3Base< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::reset(), and volumes.
Referenced by bounding_box(), and center_around_origin().
rotate() [1/2]
void Slic3r::ModelObject::rotate (double angle, Axis axis)
{
    for (ModelVolume *v : this->volumes) {
        v->rotate(angle, axis);
    }
    center_around_origin();
    this->invalidate_bounding_box();
}
References Slic3r::angle(), center_around_origin(), invalidate_bounding_box(), and volumes.
Referenced by Slic3r::orientation::orient().
rotate() [2/2]
void Slic3r::ModelObject::rotate (double angle, const Vec3d & axis)
{
    for (ModelVolume *v : this->volumes) {
        v->rotate(angle, axis);
    }
    //BBS update assemble transformation when modify volume rotation
    for (int i = 0; i < instances.size(); i++) {
        instances[i]->rotate_assemble(-angle, axis);
    }
    center_around_origin();
    this->invalidate_bounding_box();
}
References Slic3r::angle(), center_around_origin(), instances, invalidate_bounding_box(), and volumes.
save()
template<class Archive > void Slic3r::ModelObject::save (Archive & ar) const inline private
{
        ar(cereal::base_class<ObjectBase>(this));
        Internal::StaticSerializationWrapper<ModelConfigObject const> config_wrapper(config);
        Internal::StaticSerializationWrapper<LayerHeightProfile const> layer_heigth_profile_wrapper(layer_height_profile);
        ar(name, module_name, input_file, instances, volumes, config_wrapper, layer_config_ranges, layer_heigth_profile_wrapper,
            sla_support_points, sla_points_status, sla_drain_holes, printable, origin_translation,
            m_bounding_box, m_bounding_box_valid, m_raw_bounding_box, m_raw_bounding_box_valid, m_raw_mesh_bounding_box, m_raw_mesh_bounding_box_valid,
            cut_connectors, cut_id);
    }
References config, cut_connectors, cut_id, input_file, instances, layer_config_ranges, layer_height_profile, m_bounding_box, m_bounding_box_valid, m_raw_bounding_box, m_raw_bounding_box_valid, m_raw_mesh_bounding_box, m_raw_mesh_bounding_box_valid, module_name, name, origin_translation, printable, sla_drain_holes, sla_points_status, sla_support_points, and volumes.
scale() [1/3]
void Slic3r::ModelObject::scale (const double s) inline
{ this->scale(Vec3d(s, s, s)); }
References scale().
Referenced by scale().
scale() [2/3]
void Slic3r::ModelObject::scale (const Vec3d & versor)
{
    for (ModelVolume *v : this->volumes) {
        v->scale(versor);
    }
    this->invalidate_bounding_box();
}
References invalidate_bounding_box(), and volumes.
Referenced by scale_mesh_after_creation(), and scale_to_fit().
scale() [3/3]
void Slic3r::ModelObject::scale (double x, double y, double z) inline
{ this->scale(Vec3d(x, y, z)); }
References scale().
Referenced by scale().
scale_mesh_after_creation()
void Slic3r::ModelObject::scale_mesh_after_creation (const float scale)
{
    for (ModelVolume *v : this->volumes) {
        v->scale_geometry_after_creation(scale);
        v->set_offset(Vec3d(scale, scale, scale).cwiseProduct(v->get_offset()));
    }
    this->invalidate_bounding_box();
}
References invalidate_bounding_box(), scale(), and volumes.
scale_to_fit()
void Slic3r::ModelObject::scale_to_fit (const Vec3d & size)
Scale the current ModelObject to fit by altering the scaling factor of ModelInstances. It operates on the total size by duplicating the object according to all the instances.
Parameters
size Sizef3 the size vector
{
    Vec3d orig_size = this->bounding_box().size();
    double factor = std::min(
        size.x() / orig_size.x(),
        std::min(
            size.y() / orig_size.y(),
            size.z() / orig_size.z()
        )
    );
    this->scale(factor);
}
References bounding_box(), scale(), Slic3r::BoundingBox3Base< PointClass >::size(), and size.
segment()
ModelObjectPtrs Slic3r::ModelObject::segment (size_t instance, unsigned int max_extruders, double smoothing_alpha = 0.5, int segment_number = 5)
{
    BOOST_LOG_TRIVIAL(trace) << "ModelObject::segment - start";
    // Clone the object to duplicate instances, materials etc.
    ModelObject* upper = ModelObject::new_clone(*this);
    upper->set_model(nullptr);
    upper->sla_support_points.clear();
    upper->sla_drain_holes.clear();
    upper->sla_points_status = sla::PointsStatus::NoPoints;
    upper->clear_volumes();
    upper->input_file.clear();
    // Because transformations are going to be applied to meshes directly,
    // we reset transformation of all instances and volumes,
    // except for translation and Z-rotation on instances, which are preserved
    // in the transformation matrix and not applied to the mesh transform.
    // const auto instance_matrix = instances[instance]->get_matrix(true);
    const auto instance_matrix = Geometry::assemble_transform(
        Vec3d::Zero(),  // don't apply offset
        instances[instance]->get_rotation(),   // BBS: keep Z-rotation
        instances[instance]->get_scaling_factor(),
        instances[instance]->get_mirror()
    );
    for (ModelVolume* volume : volumes) {
        const auto volume_matrix = volume->get_matrix();
        volume->supported_facets.reset();
        volume->seam_facets.reset();
        if (!volume->is_model_part()) {
            // Modifiers are not cut, but we still need to add the instance transformation
            // to the modifier volume transformation to preserve their shape properly.
            volume->set_transformation(Geometry::Transformation(instance_matrix * volume_matrix));
            upper->add_volume(*volume);
        }
        else if (!volume->mesh().empty()) {
            // Transform the mesh by the combined transformation matrix.
            // Flip the triangles in case the composite transformation is left handed.
            TriangleMesh mesh(volume->mesh());
            mesh.transform(instance_matrix * volume_matrix, true);
            volume->reset_mesh();
            auto mesh_segments = MeshBoolean::cgal::segment(mesh, smoothing_alpha, segment_number);
            // Reset volume transformation except for offset
            const Vec3d offset = volume->get_offset();
            volume->set_transformation(Geometry::Transformation());
            volume->set_offset(offset);
            unsigned int extruder_counter = 0;
            for (int idx=0;idx<mesh_segments.size();idx++)
            {
                auto& mesh_segment = mesh_segments[idx];
                if (mesh_segment.facets_count() > 0) {
                    ModelVolume* vol = upper->add_volume(mesh_segment);
                    vol->name = volume->name.substr(0, volume->name.find_last_of('.')) + "_" + std::to_string(idx);
                    // Don't copy the config's ID.
                    vol->config.assign_config(volume->config);
#if 0
                    assert(vol->config.id().valid());
                    assert(vol->config.id() != volume->config.id());
                    vol->set_material(volume->material_id(), *volume->material());
#else
                    vol->config.set("extruder", auto_extruder_id(max_extruders, extruder_counter));
#endif
                }
            }
        }
    }
    ModelObjectPtrs res;
    if (upper->volumes.size() > 0) {
        upper->invalidate_bounding_box();
        // Reset instance transformation except offset and Z-rotation
        for (size_t i = 0; i < instances.size(); i++) {
            auto& instance = upper->instances[i];
            const Vec3d offset = instance->get_offset();
            // BBS
            //const double rot_z = instance->get_rotation()(2);
            instance->set_transformation(Geometry::Transformation());
            instance->set_offset(offset);
            // BBS
            //instance->set_rotation(Vec3d(0.0, 0.0, rot_z));
        }
        res.push_back(upper);
    }
    BOOST_LOG_TRIVIAL(trace) << "ModelObject::segment - end";
    return res;
}
References add_volume(), Slic3r::Geometry::assemble_transform(), Slic3r::ModelConfig::assign_config(), Slic3r::auto_extruder_id(), clear_volumes(), Slic3r::ModelVolume::config, Slic3r::ObjectBase::id(), input_file, instances, invalidate_bounding_box(), mesh(), Slic3r::ModelVolume::name, Slic3r::sla::NoPoints, Slic3r::offset(), Slic3r::MeshBoolean::cgal::segment(), Slic3r::ModelConfig::set(), Slic3r::ModelVolume::set_material(), set_model(), sla_drain_holes, sla_points_status, sla_support_points, Slic3r::trace(), Slic3r::TriangleMesh::transform(), Slic3r::ObjectID::valid(), and volumes.
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_model()
void Slic3r::ModelObject::set_model (Model * model) inline private
{ m_model = model; }
References m_model.
Referenced by Slic3r::Model::add_object(), convert_units(), merge_volumes(), and segment().
set_new_unique_id()
void Slic3r::ModelObject::set_new_unique_id () inline private
{
        ObjectBase::set_new_unique_id();
        this->config.set_new_unique_id();
        this->layer_height_profile.set_new_unique_id();
    }
References Slic3r::ObjectBase::set_new_unique_id().
Referenced by assign_new_unique_ids_recursive().
sort_volumes()
void Slic3r::ModelObject::sort_volumes (bool full_sort)
{
    // sort volumes inside the object to order "Model Part, Negative Volume, Modifier, Support Blocker and Support Enforcer. "
    if (full_sort)
        std::stable_sort(volumes.begin(), volumes.end(), [](ModelVolume* vl, ModelVolume* vr) {
            return vl->type() < vr->type();
        });
    // sort have to controll "place" of the support blockers/enforcers. But one of the model parts have to be on the first place.
    else
        std::stable_sort(volumes.begin(), volumes.end(), [](ModelVolume* vl, ModelVolume* vr) {
            ModelVolumeType vl_type = vl->type() > ModelVolumeType::PARAMETER_MODIFIER ? vl->type() : ModelVolumeType::PARAMETER_MODIFIER;
            ModelVolumeType vr_type = vr->type() > ModelVolumeType::PARAMETER_MODIFIER ? vr->type() : ModelVolumeType::PARAMETER_MODIFIER;
            return vl_type < vr_type;
        });
}
References volumes.
Referenced by Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::ObjectList::reorder_volumes_and_get_selection(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
split()
void Slic3r::ModelObject::split (ModelObjectPtrs * new_objects)
{
    std::vector<TriangleMesh> all_meshes;
    std::vector<Transform3d> all_transfos;
    std::vector<std::pair<int, int>> volume_mesh_counts;
    all_meshes.reserve(this->volumes.size() * 5);
    bool is_multi_volume_object = (this->volumes.size() > 1);
    for (int volume_idx = 0; volume_idx < this->volumes.size(); volume_idx++) {
        ModelVolume* volume = this->volumes[volume_idx];
        if (volume->type() != ModelVolumeType::MODEL_PART)
            continue;
        if (!is_multi_volume_object) {
            //BBS: not multi volume object, then split mesh.
            std::vector<TriangleMesh> volume_meshes = volume->mesh().split();
            int mesh_count = 0;
            for (TriangleMesh& mesh : volume_meshes) {
                if (mesh.facets_count() < 3)
                    continue;
                all_meshes.emplace_back(std::move(mesh));
                all_transfos.emplace_back(volume->get_matrix());
                mesh_count++;
            }
            volume_mesh_counts.push_back({ volume_idx, mesh_count });
        } else {
            //BBS: multi volume object, then only split to volume
            if (volume->mesh().facets_count() >= 3) {
                all_meshes.emplace_back(std::move(volume->mesh()));
                all_transfos.emplace_back(volume->get_matrix());
                volume_mesh_counts.push_back({ volume_idx, 1 });
            }
        }
    }
    FaceDetector face_detector(all_meshes, all_transfos, 1.0);
    face_detector.detect_exterior_face();
    int volume_mesh_begin = 0;
    for (int i = 0; i < volume_mesh_counts.size(); i++) {
        std::pair<int, int> mesh_info = volume_mesh_counts[i];
        ModelVolume* volume = this->volumes[mesh_info.first];
        std::vector<TriangleMesh> meshes;
        for (int mesh_idx = volume_mesh_begin; mesh_idx < volume_mesh_begin + mesh_info.second; mesh_idx++) {
            meshes.emplace_back(std::move(all_meshes[mesh_idx]));
        }
        volume_mesh_begin += mesh_info.second;
        size_t counter = 1;
        for (TriangleMesh& mesh : meshes) {
            // FIXME: crashes if not satisfied
            if (mesh.facets_count() < 3)
                continue;
            // XXX: this seems to be the only real usage of m_model, maybe refactor this so that it's not needed?
            ModelObject* new_object = m_model->add_object();
            //BBS: refine the config logic
            //use object as basic, and add volume's config
            if (meshes.size() == 1) {
                new_object->name = volume->name;
                // Don't copy the config's ID.
                //new_object->config.assign_config(this->config.size() > 0 ? this->config : volume->config);
            }
            else {
                new_object->name = this->name + (meshes.size() > 1 ? "_" + std::to_string(counter++) : "");
                // Don't copy the config's ID.
                //new_object->config.assign_config(this->config);
            }
            new_object->config.assign_config(this->config);
            new_object->config.apply(volume->config, true);
            assert(new_object->config.id().valid());
            assert(new_object->config.id() != this->config.id());
            new_object->instances.reserve(this->instances.size());
            for (const ModelInstance* model_instance : this->instances)
                new_object->add_instance(*model_instance);
            ModelVolume* new_vol = new_object->add_volume(*volume, std::move(mesh));
            if (is_multi_volume_object) {
                // BBS: volume geometry not changed, so we can keep the color paint facets
                if (new_vol->mmu_segmentation_facets.timestamp() == volume->mmu_segmentation_facets.timestamp())
                    new_vol->mmu_segmentation_facets.reset(); // BBS: let next assign take effect
                new_vol->mmu_segmentation_facets.assign(volume->mmu_segmentation_facets);
            }
            // BBS: clear volume's config, as we already set them into object
            new_vol->config.reset();
            for (ModelInstance* model_instance : new_object->instances)
            {
                Vec3d shift = model_instance->get_transformation().get_matrix(true) * new_vol->get_offset();
                model_instance->set_offset(model_instance->get_offset() + shift);
                //BBS: add assemble_view related logic
                Geometry::Transformation instance_transformation_copy = model_instance->get_transformation();
                instance_transformation_copy.set_offset(-new_vol->get_offset());
                const Transform3d &assemble_matrix = model_instance->get_assemble_transformation().get_matrix();
                const Transform3d &instance_inverse_matrix = instance_transformation_copy.get_matrix().inverse();
                Transform3d new_instance_inverse_matrix = instance_inverse_matrix * model_instance->get_transformation().get_matrix(true).inverse();
                Transform3d new_assemble_transform      = assemble_matrix * new_instance_inverse_matrix;
                model_instance->set_assemble_from_transform(new_assemble_transform);
            }
            new_vol->set_offset(Vec3d::Zero());
            // reset the source to disable reload from disk
            new_vol->source = ModelVolume::Source();
            new_objects->emplace_back(new_object);
        }
    }
}
References add_instance(), Slic3r::Model::add_object(), add_volume(), Slic3r::ModelConfig::apply(), Slic3r::FacetsAnnotation::assign(), Slic3r::ModelConfig::assign_config(), config, Slic3r::ModelVolume::config, Slic3r::FaceDetector::detect_exterior_face(), Slic3r::TriangleMesh::facets_count(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::ModelVolume::get_offset(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), instances, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), m_model, mesh(), Slic3r::ModelVolume::mmu_segmentation_facets, Slic3r::MODEL_PART, name, Slic3r::FacetsAnnotation::reset(), Slic3r::ModelConfig::reset(), Slic3r::Geometry::Transformation::set_offset(), Slic3r::ModelVolume::set_offset(), Slic3r::ModelVolume::source, Slic3r::ObjectWithTimestamp::timestamp(), Slic3r::ObjectID::valid(), and volumes.
Referenced by Slic3r::GUI::Plater::priv::split_object().
synchronize_model_after_cut()
void Slic3r::ModelObject::synchronize_model_after_cut ()
{
    for (ModelObject *obj : m_model->objects) {
        if (obj == this || obj->cut_id.is_equal(this->cut_id)) continue;
        if (obj->is_cut() && obj->cut_id.has_same_id(this->cut_id))
            obj->cut_id.copy(this->cut_id);
    }
}
References cut_id, m_model, and Slic3r::Model::objects.
Referenced by cut().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
translate() [1/2]
void Slic3r::ModelObject::translate (const Vec3d & vector) inline
{ this->translate(vector(0), vector(1), vector(2)); }
References translate().
Referenced by Slic3r::GUI::ObjectList::apply_object_instance_transfrom_to_all_volumes(), center_around_origin(), Slic3r::GUI::ObjectList::load_mesh_object(), and translate().
translate() [2/2]
void Slic3r::ModelObject::translate (double x, double y, double z)
{
    for (ModelVolume *v : this->volumes) {
        v->translate(x, y, z);
    }
    if (m_bounding_box_valid)
        m_bounding_box.translate(x, y, z);
}
References m_bounding_box, m_bounding_box_valid, Slic3r::BoundingBox3Base< PointClass >::translate(), and volumes.
translate_instance()
void Slic3r::ModelObject::translate_instance (size_t instance_idx, const Vec3d & vector)
{
    assert(instance_idx < instances.size());
    ModelInstance* i = instances[instance_idx];
    i->set_offset(i->get_offset() + vector);
    invalidate_bounding_box();
}
References Slic3r::ModelInstance::get_offset(), instances, invalidate_bounding_box(), and Slic3r::ModelInstance::set_offset().
Referenced by Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), and translate_instances().
translate_instances()
void Slic3r::ModelObject::translate_instances (const Vec3d & vector)
{
    for (size_t i = 0; i < instances.size(); ++i) {
        translate_instance(i, vector);
    }
}
References instances, and translate_instance().
Referenced by Slic3r::GUI::ObjectList::apply_object_instance_transfrom_to_all_volumes(), ensure_on_bed(), and Slic3r::GUI::ObjectList::merge().
update_instances_print_volume_state()
unsigned int Slic3r::ModelObject::update_instances_print_volume_state (const BuildVolume & build_volume) private
{
    unsigned int num_printable = 0;
    enum {
        INSIDE = 1,
        OUTSIDE = 2
    };
    //BBS: add logs for build_volume
    //const BoundingBoxf3& print_volume = build_volume.bounding_volume();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", print_volume {%1%, %2%, %3%} to {%4%, %5%, %6%}")\
    //    %print_volume.min.x() %print_volume.min.y() %print_volume.min.z()%print_volume.max.x() %print_volume.max.y() %print_volume.max.z();
    for (ModelInstance* model_instance : this->instances) {
        unsigned int inside_outside = 0;
        for (const ModelVolume *vol : this->volumes) {
            if (vol->is_model_part()) {
                //BBS: add bounding box empty check logic, for some volume is empty before split(it will be removed after split to object)
                BoundingBoxf3 bb = vol->get_convex_hull().bounding_box();
                Vec3d size = bb.size();
                if ((size.x() == 0.f) || (size.y() == 0.f) || (size.z() == 0.f)) {
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", object %1%'s vol %2% is empty, skip it, box: {%3%, %4%, %5%} to {%6%, %7%, %8%}")%this->name %vol->name\
                        %bb.min.x() %bb.min.y() %bb.min.z()%bb.max.x() %bb.max.y() %bb.max.z();
                    continue;
                }
                const Transform3d matrix = model_instance->get_matrix() * vol->get_matrix();
                BuildVolume::ObjectState state = build_volume.object_state(vol->mesh().its, matrix.cast<float>(), true /* may be below print bed */);
                if (state == BuildVolume::ObjectState::Inside)
                    // Volume is completely inside.
                    inside_outside |= INSIDE;
                else if (state == BuildVolume::ObjectState::Outside)
                    // Volume is completely outside.
                    inside_outside |= OUTSIDE;
                else if (state == BuildVolume::ObjectState::Below) {
                    // Volume below the print bed, thus it is completely outside, however this does not prevent the object to be printable
                    // if some of its volumes are still inside the build volume.
                } else
                    // Volume colliding with the build volume.
                    inside_outside |= INSIDE | OUTSIDE;
            }
        }
        model_instance->print_volume_state =
            inside_outside == (INSIDE | OUTSIDE) ? ModelInstancePVS_Partly_Outside :
            inside_outside == INSIDE ? ModelInstancePVS_Inside : ModelInstancePVS_Fully_Outside;
        if (inside_outside == INSIDE) {
            //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", object %1%'s instance inside print volum")%this->name;
            ++num_printable;
        }
    }
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", found %1% printable instances")%num_printable;
    return num_printable;
}
References Slic3r::BuildVolume::Below, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), Slic3r::BuildVolume::Inside, INSIDE, instances, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::ModelInstancePVS_Fully_Outside, Slic3r::ModelInstancePVS_Inside, Slic3r::ModelInstancePVS_Partly_Outside, name, Slic3r::BuildVolume::object_state(), Slic3r::BuildVolume::Outside, OUTSIDE, Slic3r::BoundingBox3Base< PointClass >::size(), size, and volumes.
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Model
friend class Model friend
Print
friend class Print friend
SLAPrint
friend class SLAPrint friend
UndoRedo::StackImpl
friend class UndoRedo::StackImpl friend
Member Data Documentation
config
ModelConfigObject Slic3r::ModelObject::config
Referenced by ModelObject(), Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::GUI::ObjectDataViewModel::AddObject(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::check_model_ids_equal(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::ObjectList::del_subobject_from_object(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), Slic3r::sla::find_least_supports_rotation(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), get_config_value(), Slic3r::GUI::ObjectList::get_default_layer_config(), Slic3r::GUI::PartPlate::get_extruders(), load(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::merge(), merge_volumes(), Slic3r::GUI::ObjectList::object_config_options_changed(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), operator=(), Slic3r::Print::process(), Slic3r::CLI::run(), save(), split(), Slic3r::GUI::ObjectList::update_filament_values_for_items(), and Slic3r::SLAPrint::validate().
cut_connectors
CutConnectors Slic3r::ModelObject::cut_connectors
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::apply_connectors_in_model(), apply_cut_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::check_conflict_for_all_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::delete_selected_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), load(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::perform_cut(), Slic3r::GUI::GLGizmoAdvancedCut::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::reset_connectors(), and save().
cut_id
CutObjectBase Slic3r::ModelObject::cut_id
Referenced by apply_cut_attributes(), apply_cut_connectors(), Slic3r::GUI::ObjectList::delete_all_connectors_for_object(), Slic3r::GUI::ObjectList::fix_cut_selection(), invalidate_cut(), Slic3r::GUI::ObjectList::invalidate_cut_info_for_object(), is_cut(), load(), Slic3r::GUI::ObjectList::part_selection_changed(), save(), and synchronize_model_after_cut().
input_file
std::string Slic3r::ModelObject::input_file
Referenced by Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), convert_units(), Slic3r::GUI::Selection::copy_to_clipboard(), get_export_filename(), load(), Slic3r::load_svg(), merge_volumes(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), print_info(), save(), and segment().
instances
ModelInstancePtrs Slic3r::ModelObject::instances
Referenced by Slic3r::PrintObject::PrintObject(), Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::_3MF_Importer::_handle_end_model(), Slic3r::_BBS_3MF_Importer::_handle_end_model(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::CalibPressureAdvancePattern::_refresh_starting_point(), add_instance(), add_instance(), Slic3r::GUI::MenuFactory::append_menu_item_printable(), Slic3r::GUI::MenuFactory::append_menu_item_set_printable(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::GUI::ObjectList::apply_object_instance_transfrom_to_all_volumes(), assign_new_unique_ids_recursive(), bake_xy_rotation_into_meshes(), bounding_box(), Slic3r::GUI::GLGizmoAdvancedCut::check_conflict_for_all_connectors(), Slic3r::check_model_ids_equal(), clear_instances(), Slic3r::GUI::Plater::combine_mesh_fff(), Slic3r::configBrimWidthByVolumes(), Slic3r::GUI::Selection::copy_to_clipboard(), cut(), Slic3r::GUI::Plater::decrease_instances(), Slic3r::GUI::ObjectList::del_subobject_from_object(), delete_instance(), delete_last_instance(), delete_volume(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), get_instance_max_z(), get_instance_min_z(), get_max_z(), Slic3r::sla::RotfinderBoilerplate< MAX_ITER >::get_mesh_to_rotate(), get_min_z(), get_object_stl_stats(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoText::get_text_mesh(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::Plater::increase_instances(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), instance_bounding_box(), instance_convex_hull_bounding_box(), Slic3r::GUI::ObjectList::instances_to_separated_object(), Slic3r::GUI::ObjectList::instances_to_separated_objects(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), load(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::load_mesh_part(), Slic3r::GUI::GLCanvas3D::load_object(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), mesh(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::Selection::paste_objects_from_clipboard(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::print_objects_from_model_object(), Slic3r::GUI::ObjectList::printable_state_changed(), Slic3r::Print::process(), Slic3r::GUI::GLGizmoAdvancedCut::process_cut_line(), Slic3r::GUI::GLGizmoAdvancedCut::put_connectors_on_cut_plane(), raw_bounding_box(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), rotate(), Slic3r::CLI::run(), save(), segment(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::Plater::set_number_of_copies(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position(), Slic3r::GUI::Plater::show_object_info(), Slic3r::sla_instances(), Slic3r::SLAPrint::sla_trafo(), split(), Slic3r::GUI::ObjectList::toggle_printable_state(), Slic3r::SLAPrintObject::transformed_drainhole_points(), translate_instance(), translate_instances(), Slic3r::GUI::GLGizmoAdvancedCut::unproject_on_cut_plane(), Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_object(), update_instances_print_volume_state(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::ObjectList::update_printable_state(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), Slic3r::GUI::GLGizmoText::update_text_positions(), and Slic3r::GUI::Selection::update_type().
layer_config_ranges
t_layer_config_ranges Slic3r::ModelObject::layer_config_ranges
Referenced by Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::GUI::ObjectList::add_layer_item(), Slic3r::GUI::ObjectList::add_layer_range_after_current(), Slic3r::GUI::ObjectList::add_layer_root_item(), Slic3r::Print::apply(), Slic3r::GUI::ObjectList::can_add_new_range_after_current(), Slic3r::GUI::ObjectList::copy_layers_to_clipboard(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::ObjectList::del_layer_from_object(), Slic3r::GUI::ObjectList::del_layer_range(), Slic3r::GUI::ObjectList::del_layers_from_object(), Slic3r::GUI::ObjectList::edit_layer_range(), Slic3r::GUI::ObjectList::edit_layer_range(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::ObjectList::layers_editing(), load(), Slic3r::GUI::ObjectList::merge(), Slic3r::Print::object_extruders(), Slic3r::GUI::ObjectList::paste_layers_into_list(), and save().
layer_height_profile
LayerHeightProfile Slic3r::ModelObject::layer_height_profile
Referenced by ModelObject(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::Print::apply(), assign_new_unique_ids_recursive(), Slic3r::GUI::Selection::copy_to_clipboard(), load(), operator=(), and save().
m_bounding_box
BoundingBoxf3 Slic3r::ModelObject::m_bounding_box mutable private
Referenced by bounding_box(), load(), save(), and translate().
m_bounding_box_valid
bool Slic3r::ModelObject::m_bounding_box_valid mutable private
Referenced by bounding_box(), invalidate_bounding_box(), load(), save(), and translate().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_model
Model* Slic3r::ModelObject::m_model = nullptr private
Referenced by get_backup_id(), get_model(), get_model(), operator=(), operator=(), set_model(), split(), and synchronize_model_after_cut().
m_raw_bounding_box
BoundingBoxf3 Slic3r::ModelObject::m_raw_bounding_box mutable private
Referenced by load(), raw_bounding_box(), and save().
m_raw_bounding_box_valid
bool Slic3r::ModelObject::m_raw_bounding_box_valid mutable private
Referenced by invalidate_bounding_box(), load(), raw_bounding_box(), and save().
m_raw_mesh_bounding_box
BoundingBoxf3 Slic3r::ModelObject::m_raw_mesh_bounding_box mutable private
Referenced by load(), raw_mesh_bounding_box(), and save().
m_raw_mesh_bounding_box_valid
bool Slic3r::ModelObject::m_raw_mesh_bounding_box_valid mutable private
Referenced by invalidate_bounding_box(), load(), raw_mesh_bounding_box(), and save().
module_name
std::string Slic3r::ModelObject::module_name
Referenced by Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), load(), and save().
name
std::string Slic3r::ModelObject::name
Referenced by Slic3r::_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::_3MF_Importer::_handle_start_object(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::GUI::ObjectList::add_volumes_to_object_in_list(), Slic3r::GUI::ObjectDataViewModel::AddObject(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), apply_cut_connectors(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::AMFParserContext::endElement(), Slic3r::Print::export_cached_data(), get_export_filename(), Slic3r::PrintObject::get_first_layer_bbox(), load(), Slic3r::Print::load_cached_data(), Slic3r::GUI::ObjectList::load_mesh_object(), make_boolean(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), save(), Slic3r::GUI::Plater::show_object_info(), split(), update_instances_print_volume_state(), and Slic3r::GUI::ObjectDataViewModel::UpdateItemNames().
origin_translation
Vec3d Slic3r::ModelObject::origin_translation
Referenced by Slic3r::Print::apply(), center_around_origin(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::Plater::export_stl(), load(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::merge(), and save().
printable
bool Slic3r::ModelObject::printable
Referenced by load(), Slic3r::GUI::OrientJob::prepare_selection(), and save().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
sla_drain_holes
sla::DrainHoles Slic3r::ModelObject::sla_drain_holes
Referenced by Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::SLAPrint::apply(), convert_units(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), load(), merge_volumes(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::GLGizmoHollow::on_update(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), save(), segment(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::SLAPrintObject::transformed_drainhole_points(), and Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh().
sla_points_status
sla::PointsStatus Slic3r::ModelObject::sla_points_status = sla::PointsStatus::NoPoints
Referenced by Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::SLAPrint::apply(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), convert_units(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), load(), merge_volumes(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLCanvas3D::reload_scene(), save(), segment(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrint::Steps::support_points(), and Slic3r::SLAPrint::validate().
sla_support_points
sla::SupportPoints Slic3r::ModelObject::sla_support_points
Referenced by Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::SLAPrint::apply(), convert_units(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), load(), merge_volumes(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), save(), segment(), Slic3r::SLAPrint::Steps::support_points(), Slic3r::SLAPrintObject::transformed_support_points(), and Slic3r::SLAPrint::validate().
volume_ids
std::vector<ObjectID> Slic3r::ModelObject::volume_ids
Referenced by load().
volumes
ModelVolumePtrs Slic3r::ModelObject::volumes
Referenced by Slic3r::Model::add_object(), Slic3r::Model::add_object(), add_volume(), add_volume(), add_volume(), add_volume(), add_volume_with_shared_mesh(), Slic3r::GUI::ObjectList::add_volumes_to_object_in_list(), Slic3r::Print::apply(), Slic3r::GUI::ObjectList::apply_object_instance_transfrom_to_all_volumes(), assign_new_unique_ids_recursive(), Slic3r::Print::auto_assign_extruders(), bake_xy_rotation_into_meshes(), Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::check_model_ids_equal(), Slic3r::GUI::Plater::clear_before_change_mesh(), clear_volumes(), Slic3r::GUI::Plater::combine_mesh_fff(), Slic3r::SeamPlacerImpl::compute_global_occlusion(), convert_units(), convex_hull_2d(), Slic3r::GUI::Selection::copy_to_clipboard(), cut(), Slic3r::GUI::ObjectList::del_subobject_from_object(), delete_connectors(), Slic3r::GUI::ObjectList::delete_from_model_and_list(), delete_volume(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), facets_count(), Slic3r::GUI::ObjectList::fix_through_netfabb(), full_raw_mesh_bounding_box(), Slic3r::SeamPlacerImpl::gather_enforcers_blockers(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::ModelInstance::get_arrange_polygon(), Slic3r::ModelInstance::get_auto_brim_width(), Slic3r::ModelInstance::get_auto_brim_width(), Slic3r::GUI::get_extruder_id_for_volumes(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::PartPlate::get_extruders_without_support(), get_instance_max_z(), get_instance_min_z(), Slic3r::GUI::get_model_volume(), get_object_stl_stats(), get_repaired_errors_count(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), has_connectors(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), instance_bounding_box(), instance_convex_hull_bounding_box(), invalidate_cut(), is_fdm_support_painted(), is_mm_painted(), is_multiparts(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), is_seam_painted(), load(), Slic3r::GUI::ObjectList::load_mesh_part(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GLVolumeCollection::load_object(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::load_svg(), make_boolean(), materials_count(), merge(), Slic3r::GUI::ObjectList::merge(), merge_volumes(), mirror(), Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::model_property_changed(), Slic3r::csg::model_to_csgmesh(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::multi_material_segmentation_by_painting(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::GUI::ObjectList::object_config_options_changed(), Slic3r::Print::object_extruders(), Slic3r::GUI::Plater::on_filaments_change(), Slic3r::GUI::GLGizmoMeshBoolean::on_load(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), parts_count(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::Print::process(), raw_bounding_box(), raw_indexed_triangle_set(), raw_mesh(), raw_mesh_bounding_box(), Slic3r::GUI::ObjectGridTable::reload_cell_data(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GLVolume::render(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::ObjectList::reorder_volumes_and_get_selection(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), rotate(), rotate(), Slic3r::CLI::run(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), save(), scale(), scale_mesh_after_creation(), segment(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::ObjectList::select_items(), Slic3r::GUI::ObjectList::set_extruder_for_selected_items(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::Plater::show_object_info(), Slic3r::GLVolume::simple_render(), sort_volumes(), split(), Slic3r::ModelVolume::split(), translate(), Slic3r::GUI::ObjectList::update_filament_values_for_items(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::ObjectList::update_info_items(), update_instances_print_volume_state(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::ObjectList::update_selections_on_canvas(), Slic3r::GUI::GLGizmoText::update_text_positions(), Slic3r::GUI::Selection::update_type(), and Slic3r::GUI::ObjectDataViewModel::UpdateItemNames().
The documentation for this class was generated from the following files:
src/libslic3r/Model.hpp
src/libslic3r/Model.cpp