OrcaSlicer: Slic3r::GUI::SettingsFactory Struct Reference
Slic3r::GUI::SettingsFactory Struct Reference
#include <src/slic3r/GUI/GUI_Factories.hpp>
Public Types
typedef std::map< std::string, std::vector< std::string > > Bundle
Static Public Member Functions
static wxBitmap get_category_bitmap (const std::string &category_name, bool menu_bmp=true)
static Bundle get_bundle (const DynamicPrintConfig *config, bool is_object_settings, bool is_layer_settings=false)
static std::vector< std::string > get_options (bool is_part)
static std::vector< SimpleSettingData > get_visible_options (const std::string &category, const bool is_part)
static std::map< std::string, std::vector< SimpleSettingData > > get_all_visible_options (const bool is_part)
Static Public Attributes
static std::map< std::string, std::string > CATEGORY_ICON
static std::map< std::string, std::vector< SimpleSettingData > > OBJECT_CATEGORY_SETTINGS
static std::map< std::string, std::vector< SimpleSettingData > > PART_CATEGORY_SETTINGS
Detailed Description
Member Typedef Documentation
Bundle
typedef std::map<std::string, std::vector<std::string> > Slic3r::GUI::SettingsFactory::Bundle
Member Function Documentation
get_all_visible_options()
std::map< std::string, std::vector< SimpleSettingData > > Slic3r::GUI::SettingsFactory::get_all_visible_options (const bool is_part) static
{
    std::map<std::string, std::vector<SimpleSettingData>> option_maps;
    std::map<std::string, std::vector<SimpleSettingData>>::iterator it1, it2;
    option_maps = PART_CATEGORY_SETTINGS;
    if (!is_part) {
        for (it1 = OBJECT_CATEGORY_SETTINGS.begin(); it1 != OBJECT_CATEGORY_SETTINGS.end(); it1++)
        {
            std::string category = it1->first;
            it2 = PART_CATEGORY_SETTINGS.find(category);
            if (it2 != PART_CATEGORY_SETTINGS.end())
            {
                std::vector<SimpleSettingData>& options = option_maps[category];
                options.insert(options.end(), it1->second.begin(), it1->second.end());
                auto sort_func = [](SimpleSettingData& setting1, SimpleSettingData& setting2) {
                    return (setting1.priority < setting2.priority);
                };
                std::sort(options.begin(), options.end(), sort_func);
            }
            else {
                option_maps.insert(*it1);
            }
        }
    }
    return option_maps;
}
References OBJECT_CATEGORY_SETTINGS, PART_CATEGORY_SETTINGS, and Slic3r::GUI::SimpleSettingData::priority.
Referenced by Slic3r::GUI::ObjectTableSettings::resetAllValues(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
get_bundle()
SettingsFactory::Bundle Slic3r::GUI::SettingsFactory::get_bundle (const DynamicPrintConfig * config, bool is_object_settings, bool is_layer_settings = false) static
{
    auto opt_keys = config->keys();
    if (opt_keys.empty())
        return Bundle();
    // update options list according to print technology
    auto full_current_opts = get_options(!is_object_settings);
    if (is_layer_settings)
        full_current_opts.push_back("layer_height");
    for (int i = opt_keys.size() - 1; i >= 0; --i)
        if (find(full_current_opts.begin(), full_current_opts.end(), opt_keys[i]) == full_current_opts.end())
            opt_keys.erase(opt_keys.begin() + i);
    if (opt_keys.empty())
        return Bundle();
    const int filaments_cnt = wxGetApp().filaments_cnt();
    Bundle bundle;
    for (auto& opt_key : opt_keys)
    {
        auto category = config->def()->get(opt_key)->category;
        if (is_improper_category(category, filaments_cnt, is_object_settings))
            continue;
        std::vector< std::string > new_category;
        auto& cat_opt = bundle.find(category) == bundle.end() ? new_category : bundle.at(category);
        cat_opt.push_back(opt_key);
        if (cat_opt.size() == 1)
            bundle[category] = cat_opt;
    }
    return bundle;
}
References Slic3r::ConfigOptionDef::category, Slic3r::DynamicPrintConfig::def(), Slic3r::ConfigDef::get(), get_options(), Slic3r::GUI::is_improper_category(), and Slic3r::DynamicConfig::keys().
Referenced by Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::ParamsPanel::notify_object_config_changed(), Slic3r::GUI::ObjectList::object_config_options_changed(), and Slic3r::GUI::ObjectSettings::update_settings_list().
get_category_bitmap()
wxBitmap Slic3r::GUI::SettingsFactory::get_category_bitmap (const std::string & category_name, bool menu_bmp = true) static
{
    if (CATEGORY_ICON.find(category_name) == CATEGORY_ICON.end())
        return wxNullBitmap;
    return create_scaled_bitmap(CATEGORY_ICON.at(category_name));
}
References CATEGORY_ICON, and create_scaled_bitmap().
Referenced by Slic3r::GUI::create_freq_settings_popupmenu(), Slic3r::GUI::create_settings_popupmenu(), and Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest_bitmaps().
get_options()
std::vector< std::string > Slic3r::GUI::SettingsFactory::get_options (bool is_part) static
{
    if (printer_technology() == ptSLA) {
        SLAPrintObjectConfig full_sla_config;
        auto options = full_sla_config.keys();
        options.erase(find(options.begin(), options.end(), "layer_height"));
        return options;
    }
    PrintRegionConfig reg_config;
    auto options = reg_config.keys();
    if (!is_part) {
        PrintObjectConfig obj_config;
        std::vector<std::string> obj_options = obj_config.keys();
        options.insert(options.end(), obj_options.begin(), obj_options.end());
    }
    return options;
}
References Slic3r::GUI::printer_technology(), Slic3r::PrintObjectConfig, Slic3r::PrintRegionConfig, and Slic3r::ptSLA.
Referenced by get_bundle(), Slic3r::GUI::get_full_settings_hierarchy(), and Slic3r::GUI::ObjectList::paste_settings_into_list().
get_visible_options()
std::vector< SimpleSettingData > Slic3r::GUI::SettingsFactory::get_visible_options (const std::string & category, const bool is_part) static
{
    /*t_config_option_keys options = {
        //Quality
        "wall_infill_order", "ironing_type", "inner_wall_line_width", "outer_wall_line_width", "top_surface_line_width",
        //Shell
        "wall_loops", "top_shell_layers", "bottom_shell_layers", "top_shell_thickness", "bottom_shell_thickness",
        //Infill
        "sparse_infill_density", "sparse_infill_pattern", "top_surface_pattern", "bottom_surface_pattern", "infill_combination", "infill_direction", "infill_wall_overlap",
        //speed
        "inner_wall_speed", "outer_wall_speed", "sparse_infill_speed", "internal_solid_infill_speed", "top_surface_speed", "gap_infill_speed"
        };
    t_config_option_keys object_options = {
        //Quality
        "layer_height", "initial_layer_print_height", "adaptive_layer_height", "seam_position", "xy_hole_compensation", "xy_contour_compensation", "elefant_foot_compensation", "support_line_width",
        //Support
        "enable_support", "support_type", "support_threshold_angle", "support_on_build_plate_only", "support_critical_regions_only", "enforce_support_layers",
        //tree support
        "tree_support_wall_count",
        //support
        "support_top_z_distance", "support_base_pattern", "support_base_pattern_spacing", "support_interface_top_layers", "support_interface_bottom_layers", "support_interface_spacing", "support_bottom_interface_spacing", "support_object_xy_distance",
        //adhesion
        "brim_type", "brim_width", "brim_object_gap", "raft_layers"
        };*/
    std::vector<SimpleSettingData> options;
    std::map<std::string, std::vector<SimpleSettingData>>::iterator it;
    it = PART_CATEGORY_SETTINGS.find(category);
    if (it != PART_CATEGORY_SETTINGS.end())
    {
        options = PART_CATEGORY_SETTINGS[category];
    }
    if (!is_part) {
        it = OBJECT_CATEGORY_SETTINGS.find(category);
        if (it != OBJECT_CATEGORY_SETTINGS.end())
            options.insert(options.end(), OBJECT_CATEGORY_SETTINGS[category].begin(), OBJECT_CATEGORY_SETTINGS[category].end());
    }
    auto sort_func = [](SimpleSettingData& setting1, SimpleSettingData& setting2) {
        return (setting1.priority < setting2.priority);
    };
    std::sort(options.begin(), options.end(), sort_func);
    return options;
}
References OBJECT_CATEGORY_SETTINGS, PART_CATEGORY_SETTINGS, and Slic3r::GUI::SimpleSettingData::priority.
Referenced by Slic3r::GUI::ObjectTableSettings::resetAllValues(), Slic3r::GUI::ObjectTableSettings::update_config_values(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
Member Data Documentation
CATEGORY_ICON
std::map< std::string, std::string > Slic3r::GUI::SettingsFactory::CATEGORY_ICON static
Initial value:
=
{
    { L("Quality")              , "blank2"      },
    { L("Shell")                , "blank_14"    },
    { L("Infill")               , "blank_14"    },
    { L("Ironing")              , "blank_14"    },
    { L("Fuzzy Skin")           , "menu_fuzzy_skin"  },
    { L("Support")              , "support"     },
    { L("Speed")                , "blank_14"    },
    { L("Extruders")            , "blank_14"    },
    { L("Extrusion Width")      , "blank_14"    },
    { L("Wipe options")         , "blank_14"    },
    { L("Bed adhension")        , "blank_14"    },
    { L("Advanced")             , "blank_14"    },
}
Referenced by get_category_bitmap().
OBJECT_CATEGORY_SETTINGS
std::map< std::string, std::vector< SimpleSettingData > > Slic3r::GUI::SettingsFactory::OBJECT_CATEGORY_SETTINGS static
Initial value:
=
{
    { L("Quality"), {{"layer_height", "",1},
                    {"seam_position", "",2},
                    {"slice_closing_radius", "",3}, {"resolution", "",4},
                    {"xy_hole_compensation", "",5}, {"xy_contour_compensation", "",6}, {"elefant_foot_compensation", "",7},
                    {"make_overhang_printable_angle","", 8},{"make_overhang_printable_hole_size","",9}
                    }},
    { L("Support"), {{"brim_type", "",1},{"brim_width", "",2},{"brim_object_gap", "",3},
                    {"enable_support", "",4},{"support_type", "",5},{"support_threshold_angle", "",6},{"support_on_build_plate_only", "",7},
                    {"support_filament", "",8},{"support_interface_filament", "",9},{"support_expansion", "",24},{"support_style", "",25},
                     {"tree_support_branch_angle", "",10}, {"tree_support_wall_count", "",11},
                            {"support_top_z_distance", "",13},{"support_bottom_z_distance", "",12},{"support_base_pattern", "",14},{"support_base_pattern_spacing", "",15},
                            {"support_interface_top_layers", "",16},{"support_interface_bottom_layers", "",17},{"support_interface_spacing", "",18},{"support_bottom_interface_spacing", "",19},
                            {"support_object_xy_distance", "",20}, {"bridge_no_support", "",21},{"max_bridge_length", "",22},{"support_critical_regions_only", "",23}
                            }},
    { L("Speed"), {{"support_speed", "",12}, {"support_interface_speed", "",13}
                    }}
}
Referenced by get_all_visible_options(), and get_visible_options().
PART_CATEGORY_SETTINGS
std::map< std::string, std::vector< SimpleSettingData > > Slic3r::GUI::SettingsFactory::PART_CATEGORY_SETTINGS static
Initial value:
=
{
    { L("Quality"), {{"ironing_type", "",8},{"ironing_flow", "",9},{"ironing_spacing", "",10},{"bridge_flow", "",11},{"make_overhang_printable", "",11},{"bridge_density", "", 1}
                    }},
    { L("Strength"), {{"wall_loops", "",1},{"top_shell_layers", L("Top Solid Layers"),1},{"top_shell_thickness", L("Top Minimum Shell Thickness"),1},
                    {"bottom_shell_layers", L("Bottom Solid Layers"),1}, {"bottom_shell_thickness", L("Bottom Minimum Shell Thickness"),1},
                    {"sparse_infill_density", "",1},{"sparse_infill_pattern", "",1},{"infill_anchor", "",1},{"infill_anchor_max", "",1},{"top_surface_pattern", "",1},{"bottom_surface_pattern", "",1}, {"internal_solid_infill_pattern", "",1},
                    {"infill_combination", "",1}, {"infill_wall_overlap", "",1}, {"infill_direction", "",1}, {"bridge_angle", "",1}, {"minimum_sparse_infill_area", "",1}
                    }},
    { L("Speed"), {{"outer_wall_speed", "",1},{"inner_wall_speed", "",2},{"sparse_infill_speed", "",3},{"top_surface_speed", "",4}, {"internal_solid_infill_speed", "",5},
                    {"enable_overhang_speed", "",6}, {"overhang_speed_classic", "",6}, {"overhang_1_4_speed", "",7}, {"overhang_2_4_speed", "",8}, {"overhang_3_4_speed", "",9}, {"overhang_4_4_speed", "",10},
                    {"bridge_speed", "",11}, {"gap_infill_speed", "",12}, {"internal_bridge_speed", "", 13}
                    }}
}
Referenced by get_all_visible_options(), and get_visible_options().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GUI_Factories.hpp
src/slic3r/GUI/GUI_Factories.cpp