OrcaSlicer: Slic3r::GUI::ParamsPanel::Highlighter Struct Reference
Slic3r::GUI::ParamsPanel::Highlighter Struct Reference
#include <src/slic3r/GUI/ParamsPanel.hpp>
Public Member Functions
void set_timer_owner (wxEvtHandler *owner, int timerid=wxID_ANY)
void init (std::pair< wxWindow *, bool * >, wxWindow *parent=nullptr)
void blink ()
void invalidate ()
Private Attributes
wxWindow * m_bitmap {nullptr}
bool * m_show_blink_ptr {nullptr}
int m_blink_counter {0}
wxTimer m_timer
wxWindow * m_parent { nullptr }
Detailed Description
Member Function Documentation
blink()
void Slic3r::GUI::ParamsPanel::Highlighter::blink ()
{
    if (m_bitmap && m_show_blink_ptr) {
        *m_show_blink_ptr = !*m_show_blink_ptr;
        m_bitmap->Show(*m_show_blink_ptr);
        if (m_parent) {
            m_parent->Layout();
            m_parent->Refresh();
        }
    } else
        return;
    if ((++m_blink_counter) == 11) invalidate();
}
Referenced by Slic3r::GUI::ParamsPanel::ParamsPanel(), and Slic3r::GUI::ParamsPanel::switch_to_object().
init()
void Slic3r::GUI::ParamsPanel::Highlighter::init (std::pair< wxWindow *, bool * > params, wxWindow * parent = nullptr)
    {
    if (m_timer.IsRunning()) invalidate();
    if (!params.first || !params.second) return;
    m_timer.Start(300, false);
    m_bitmap         = params.first;
    m_show_blink_ptr = params.second;
    m_parent         = parent;
    *m_show_blink_ptr = true;
    }
Referenced by Slic3r::GUI::ParamsPanel::switch_to_object().
invalidate()
void Slic3r::GUI::ParamsPanel::Highlighter::invalidate ()
{
    m_timer.Stop();
    if (m_bitmap && m_show_blink_ptr) {
        *m_show_blink_ptr = false;
        m_bitmap->Show(*m_show_blink_ptr);
        if (m_parent) {
            m_parent->Layout();
            m_parent->Refresh();
        }
        m_show_blink_ptr = nullptr;
        m_bitmap         = nullptr;
        m_parent         = nullptr;
    }
    m_blink_counter = 0;
}
set_timer_owner()
void Slic3r::GUI::ParamsPanel::Highlighter::set_timer_owner (wxEvtHandler * owner, int timerid = wxID_ANY)
{
    m_timer.SetOwner(owner, timerid);
}
References m_timer.
Referenced by Slic3r::GUI::ParamsPanel::ParamsPanel().
Member Data Documentation
m_bitmap
wxWindow* Slic3r::GUI::ParamsPanel::Highlighter::m_bitmap {nullptr} private
m_blink_counter
int Slic3r::GUI::ParamsPanel::Highlighter::m_blink_counter {0} private
m_parent
wxWindow* Slic3r::GUI::ParamsPanel::Highlighter::m_parent { nullptr } private
m_show_blink_ptr
bool* Slic3r::GUI::ParamsPanel::Highlighter::m_show_blink_ptr {nullptr} private
m_timer
wxTimer Slic3r::GUI::ParamsPanel::Highlighter::m_timer private
Referenced by set_timer_owner().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ParamsPanel.hpp
src/slic3r/GUI/ParamsPanel.cpp