OrcaSlicer: Slic3r::GUI::ConnectPrinterDialog Class Reference
Slic3r::GUI::ConnectPrinterDialog Class Reference
#include <src/slic3r/GUI/ConnectPrinter.hpp>
Public Member Functions
ConnectPrinterDialog (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxCLOSE_BOX|wxCAPTION)
~ConnectPrinterDialog ()
void end_modal (wxStandardID id)
void init_bitmap ()
void set_machine_object (MachineObject *obj)
void on_input_enter (wxCommandEvent &evt)
void on_button_confirm (wxCommandEvent &event)
void on_dpi_changed (const wxRect &suggested_rect) override
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Protected Member Functions
virtual void on_sys_color_changed ()
Protected Attributes
wxStaticText * m_staticText_connection_code
TextInput * m_textCtrl_code
Button * m_button_confirm
wxStaticText * m_staticText_hints
wxStaticBitmap * m_bitmap_diagram
wxBitmap m_diagram_bmp
wxImage m_diagram_img
MachineObject * m_obj
wxString m_input_access_code
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
ConnectPrinterDialog()
Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxCLOSE_BOX | wxCAPTION)
    : DPIDialog(parent, id, _L("ConnectPrinter(LAN)"), pos, size, style)
{
    init_bitmap();
    SetBackgroundColour(*wxWHITE);
    this->SetSizeHints(wxDefaultSize, wxDefaultSize);
    wxBoxSizer *main_sizer;
    main_sizer = new wxBoxSizer(wxHORIZONTAL);
    main_sizer->Add(FromDIP(40), 0);
    wxBoxSizer *sizer_top;
    sizer_top = new wxBoxSizer(wxVERTICAL);
    sizer_top->Add(0, FromDIP(40));
    m_staticText_connection_code = new wxStaticText(this, wxID_ANY, _L("Please input the printer access code:"), wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_connection_code->SetFont(Label::Body_15);
    m_staticText_connection_code->SetForegroundColour(wxColour(50, 58, 61));
    m_staticText_connection_code->Wrap(-1);
    sizer_top->Add(m_staticText_connection_code, 0, wxALL, 0);
    sizer_top->Add(0, FromDIP(10));
    wxBoxSizer *sizer_connect;
    sizer_connect = new wxBoxSizer(wxHORIZONTAL);
    m_textCtrl_code = new TextInput(this, wxEmptyString);
    m_textCtrl_code->GetTextCtrl()->SetMaxLength(10);
    m_textCtrl_code->SetFont(Label::Body_14);
    m_textCtrl_code->SetCornerRadius(FromDIP(5));
    m_textCtrl_code->SetSize(wxSize(FromDIP(330), FromDIP(40)));
    m_textCtrl_code->SetMinSize(wxSize(FromDIP(330), FromDIP(40)));
    m_textCtrl_code->GetTextCtrl()->SetSize(wxSize(-1, FromDIP(22)));
    m_textCtrl_code->GetTextCtrl()->SetMinSize(wxSize(-1, FromDIP(22)));
    m_textCtrl_code->SetBackgroundColour(*wxWHITE);
    m_textCtrl_code->GetTextCtrl()->SetForegroundColour(wxColour(107, 107, 107));
    sizer_connect->Add(m_textCtrl_code, 0, wxALL | wxALIGN_CENTER_VERTICAL, 0);
    sizer_connect->Add(FromDIP(20), 0);
    m_button_confirm = new Button(this, _L("Confirm"));
    m_button_confirm->SetFont(Label::Body_12);
    m_button_confirm->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_confirm->SetCornerRadius(FromDIP(12));
    m_button_confirm->SetTextColor(wxColour("#FFFFFE"));
    StateColor btn_bg(
        std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed),
        std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal)
    );
    StateColor btn_bd(std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    StateColor btn_text(std::pair<wxColour, int>(wxColour(255, 255, 255), StateColor::Normal));
    m_button_confirm->SetBackgroundColor(btn_bg);
    m_button_confirm->SetBorderColor(btn_bd);
    m_button_confirm->SetTextColor(btn_text);
    sizer_connect->Add(m_button_confirm, 0, wxALL | wxALIGN_CENTER_VERTICAL, 0);
    sizer_connect->Add(FromDIP(60), 0);
    sizer_top->Add(sizer_connect);
    sizer_top->Add(0, FromDIP(35));
    m_staticText_hints = new wxStaticText(this, wxID_ANY, _L("You can find it in \"Settings > Network > Connection code\"\non the printer, as shown in the figure:"), wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_hints->SetFont(Label::Body_15);
    m_staticText_hints->SetForegroundColour(wxColour(50, 58, 61));
    m_staticText_hints->Wrap(-1);
    sizer_top->Add(m_staticText_hints, 0, wxALL, 0);
    sizer_top->Add(0, FromDIP(25));
    wxBoxSizer *sizer_diagram;
    sizer_diagram = new wxBoxSizer(wxHORIZONTAL);
    m_bitmap_diagram = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxSize(FromDIP(340), FromDIP(190)), 0);
    m_bitmap_diagram->SetBitmap(m_diagram_img);
    sizer_diagram->Add(m_bitmap_diagram);
    sizer_top->Add(sizer_diagram);
    sizer_top->Add(0, FromDIP(40), 0, wxEXPAND, 0);
    main_sizer->Add(sizer_top);
    this->SetSizer(main_sizer);
    this->Layout();
    this->Fit();
    CentreOnParent();
    m_textCtrl_code->Bind(wxEVT_TEXT, &ConnectPrinterDialog::on_input_enter, this);
    m_button_confirm->Bind(wxEVT_BUTTON, &ConnectPrinterDialog::on_button_confirm, this);
    wxGetApp().UpdateDlgDarkUI(this);
}
References _L, Label::Body_12, Label::Body_14, Label::Body_15, TextInput::GetTextCtrl(), StateColor::Hovered, init_bitmap(), m_bitmap_diagram, m_button_confirm, m_diagram_img, m_staticText_connection_code, m_staticText_hints, m_textCtrl_code, StateColor::Normal, on_button_confirm(), on_input_enter(), StateColor::Pressed, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), TextInput::SetCornerRadius(), Button::SetFont(), Button::SetMinSize(), TextInput::SetMinSize(), Button::SetTextColor(), wxEVT_BUTTON, and wxStaticText.
~ConnectPrinterDialog()
Slic3r::GUI::ConnectPrinterDialog::~ConnectPrinterDialog ()
{}
Member Function Documentation
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
end_modal()
void Slic3r::GUI::ConnectPrinterDialog::end_modal (wxStandardID id)
{
    EndModal(id);
}
init_bitmap()
void Slic3r::GUI::ConnectPrinterDialog::init_bitmap ()
{
    AppConfig *config = get_app_config();
    std::string language = config->get("language");
    if (language == "zh_CN") {
        m_diagram_bmp = create_scaled_bitmap("input_access_code_cn", nullptr, 190);
    }
    else{
        m_diagram_bmp = create_scaled_bitmap("input_access_code_en", nullptr, 190);
    }
    m_diagram_img = m_diagram_bmp.ConvertToImage();
    m_diagram_img.Rescale(FromDIP(340), FromDIP(190));
}
References create_scaled_bitmap(), Slic3r::AppConfig::get(), Slic3r::GUI::get_app_config(), m_diagram_bmp, and m_diagram_img.
Referenced by ConnectPrinterDialog(), and on_dpi_changed().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_button_confirm()
void Slic3r::GUI::ConnectPrinterDialog::on_button_confirm (wxCommandEvent & event)
{
    wxString code = m_textCtrl_code->GetTextCtrl()->GetValue();
    for (char c : code) {
        if (!('0' <= c && c <= '9' || 'a' <= c && c <= 'z' || 'A' <= c && c <= 'Z')) {
            show_error(this, _L("Invalid input."));
            return;
        }
    }
    if (m_obj) {
        m_obj->set_user_access_code(code.ToStdString());
        wxGetApp().getDeviceManager()->set_selected_machine(m_obj->dev_id);
    }
    EndModal(wxID_OK);
}
References _L, Slic3r::MachineObject::dev_id, TextInput::GetTextCtrl(), m_obj, m_textCtrl_code, Slic3r::MachineObject::set_user_access_code(), and Slic3r::GUI::show_error().
Referenced by ConnectPrinterDialog().
on_dpi_changed()
void Slic3r::GUI::ConnectPrinterDialog::on_dpi_changed (const wxRect & suggested_rect) override virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    init_bitmap();
    m_bitmap_diagram->SetBitmap(m_diagram_img);
    m_textCtrl_code->GetTextCtrl()->SetSize(wxSize(-1, FromDIP(22)));
    m_textCtrl_code->GetTextCtrl()->SetMinSize(wxSize(-1, FromDIP(22)));
    m_button_confirm->SetCornerRadius(FromDIP(12));
    m_button_confirm->Rescale();
    Layout();
    this->Refresh();
}
References TextInput::GetTextCtrl(), init_bitmap(), m_bitmap_diagram, m_button_confirm, m_diagram_img, m_textCtrl_code, Button::Rescale(), and StaticBox::SetCornerRadius().
on_input_enter()
void Slic3r::GUI::ConnectPrinterDialog::on_input_enter (wxCommandEvent & evt)
{
    m_input_access_code = evt.GetString();
}
References m_input_access_code.
Referenced by ConnectPrinterDialog().
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
set_machine_object()
void Slic3r::GUI::ConnectPrinterDialog::set_machine_object (MachineObject * obj)
{
    m_obj = obj;
}
References m_obj.
Referenced by Slic3r::GUI::SelectMachineDialog::on_selection_changed().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
Member Data Documentation
m_bitmap_diagram
wxStaticBitmap* Slic3r::GUI::ConnectPrinterDialog::m_bitmap_diagram protected
Referenced by ConnectPrinterDialog(), and on_dpi_changed().
m_button_confirm
Button* Slic3r::GUI::ConnectPrinterDialog::m_button_confirm protected
Referenced by ConnectPrinterDialog(), and on_dpi_changed().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_diagram_bmp
wxBitmap Slic3r::GUI::ConnectPrinterDialog::m_diagram_bmp protected
Referenced by init_bitmap().
m_diagram_img
wxImage Slic3r::GUI::ConnectPrinterDialog::m_diagram_img protected
Referenced by ConnectPrinterDialog(), init_bitmap(), and on_dpi_changed().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_input_access_code
wxString Slic3r::GUI::ConnectPrinterDialog::m_input_access_code protected
Referenced by on_input_enter().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_obj
MachineObject* Slic3r::GUI::ConnectPrinterDialog::m_obj protected
Referenced by on_button_confirm(), and set_machine_object().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_staticText_connection_code
wxStaticText* Slic3r::GUI::ConnectPrinterDialog::m_staticText_connection_code protected
Referenced by ConnectPrinterDialog().
m_staticText_hints
wxStaticText* Slic3r::GUI::ConnectPrinterDialog::m_staticText_hints protected
Referenced by ConnectPrinterDialog().
m_textCtrl_code
TextInput* Slic3r::GUI::ConnectPrinterDialog::m_textCtrl_code protected
Referenced by ConnectPrinterDialog(), on_button_confirm(), and on_dpi_changed().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ConnectPrinter.hpp
src/slic3r/GUI/ConnectPrinter.cpp