OrcaSlicer: WebView Class Reference
WebView Class Reference
#include <src/slic3r/GUI/Widgets/WebView.hpp>
Static Public Member Functions
static wxWebView * CreateWebView (wxWindow *parent, wxString const &url)
static void LoadUrl (wxWebView *webView, wxString const &url)
static bool RunScript (wxWebView *webView, wxString const &msg)
static void RecreateAll ()
Detailed Description
Member Function Documentation
CreateWebView()
wxWebView * WebView::CreateWebView (wxWindow * parent, wxString const & url) static
{
#if wxUSE_WEBVIEW_EDGE
    // Check if a fixed version of edge is present in
    // $executable_path/edge_fixed and use it
    wxFileName edgeFixedDir(wxStandardPaths::Get().GetExecutablePath());
    edgeFixedDir.SetFullName("");
    edgeFixedDir.AppendDir("edge_fixed");
    if (edgeFixedDir.DirExists()) {
        wxWebViewEdge::MSWSetBrowserExecutableDir(edgeFixedDir.GetFullPath());
        wxLogMessage("Using fixed edge version");
    }
#endif
    auto url2  = url;
#ifdef __WIN32__
    url2.Replace("\\", "/");
#endif
    if (!url2.empty()) { url2 = wxURI(url2).BuildURI(); }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": " << url2.ToUTF8();
#ifdef __WIN32__
    wxWebView* webView = new WebViewEdge;
#elif defined(__WXOSX__)
    wxWebView *webView = new WebViewWebKit;
#else
    auto webView = wxWebView::New();
#endif
    if (webView) {
        webView->SetBackgroundColour(StateColor::darkModeColorFor(*wxWHITE));
#ifdef __WIN32__
        webView->SetUserAgent(wxString::Format("BBL-Slicer/v%s (%s) Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36 Edg/107.0.1418.52", SLIC3R_VERSION,
            Slic3r::GUI::wxGetApp().dark_mode() ? "dark" : "light"));
        webView->Create(parent, wxID_ANY, url2, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE);
        // We register the wxfs:// protocol for testing purposes
        webView->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewArchiveHandler("bbl")));
        // And the memory: file system
        webView->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
#else
        // With WKWebView handlers need to be registered before creation
        webView->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewArchiveHandler("wxfs")));
        // And the memory: file system
        webView->RegisterHandler(wxSharedPtr<wxWebViewHandler>(new wxWebViewFSHandler("memory")));
        webView->Create(parent, wxID_ANY, url2, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE);
        webView->SetUserAgent(wxString::Format("BBL-Slicer/v%s (%s) Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)", SLIC3R_VERSION,
                                               Slic3r::GUI::wxGetApp().dark_mode() ? "dark" : "light"));
#endif
#ifdef __WXMAC__
        WKWebView * wkWebView = (WKWebView *) webView->GetNativeBackend();
        Slic3r::GUI::WKWebView_setTransparentBackground(wkWebView);
#endif
        auto addScriptMessageHandler = [] (wxWebView *webView) {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": begin to add script message handler for wx.";
            Slic3r::GUI::wxGetApp().set_adding_script_handler(true);
            if (!webView->AddScriptMessageHandler("wx"))
                wxLogError("Could not add script message handler");
            Slic3r::GUI::wxGetApp().set_adding_script_handler(false);
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": finished add script message handler for wx.";
        };
#ifndef __WIN32__
        webView->CallAfter([webView, addScriptMessageHandler] {
#endif
            if (Slic3r::GUI::wxGetApp().is_adding_script_handler()) {
                g_delay_webviews.push_back(webView);
            } else {
                addScriptMessageHandler(webView);
                while (!g_delay_webviews.empty()) {
                    auto views = std::move(g_delay_webviews);
                    for (auto wv : views)
                        addScriptMessageHandler(wv);
                }
            }
#ifndef __WIN32__
        });
#endif
        webView->EnableContextMenu(true);
    } else {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": failed. Use fake web view.";
        webView = new FakeWebView;
    }
    webView->SetRefData(new WebViewRef(webView));
    g_webviews.push_back(webView);
    return webView;
}
References StateColor::darkModeColorFor(), g_delay_webviews, g_webviews, and Slic3r::GUI::WKWebView_setTransparentBackground().
Referenced by Slic3r::GUI::DownPluginFrame::DownPluginFrame(), Slic3r::GUI::GuideFrame::GuideFrame(), Slic3r::GUI::ModelMallDialog::ModelMallDialog(), Slic3r::GUI::PrinterWebView::PrinterWebView(), Slic3r::GUI::ProjectPanel::ProjectPanel(), Slic3r::GUI::WebViewPanel::WebViewPanel(), Slic3r::GUI::ZUserLogin::ZUserLogin(), Slic3r::GUI::MarkdownTip::CreateTipView(), Slic3r::GUI::PrivacyUpdateDialog::CreateTipView(), and Slic3r::GUI::UpdateVersionDialog::CreateTipView().
LoadUrl()
void WebView::LoadUrl (wxWebView * webView, wxString const & url) static
{
    auto url2  = url;
#ifdef __WIN32__
    url2.Replace("\\", "/");
#endif
    if (!url2.empty()) { url2 = wxURI(url2).BuildURI(); }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << url2.ToUTF8();
    webView->LoadURL(url2);
}
Referenced by Slic3r::GUI::ModelMallDialog::go_to_url(), and Slic3r::GUI::GuideFrame::load_url().
RecreateAll()
void WebView::RecreateAll () static
{
    for (auto webView : g_webviews) {
        webView->SetUserAgent(wxString::Format("BBL-Slicer/v%s (%s) Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko)", SLIC3R_VERSION,
                                               Slic3r::GUI::wxGetApp().dark_mode() ? "dark" : "light"));
        webView->Reload();
    }
}
References g_webviews.
Referenced by Slic3r::GUI::MainFrame::on_sys_color_changed().
RunScript()
bool WebView::RunScript (wxWebView * webView, wxString const & msg) static
{
    if (Slic3r::GUI::wxGetApp().get_mode() == Slic3r::comDevelop)
        wxLogMessage("Running JavaScript:\n%s\n", javascript);
    try {
#ifdef __WIN32__
        ICoreWebView2 *   webView2 = (ICoreWebView2 *) webView->GetNativeBackend();
        if (webView2 == nullptr)
            return false;
        int               count   = 0;
        wxJSScriptWrapper wrapJS(javascript, &count);
        return webView2->ExecuteScript(wrapJS.GetWrappedCode(), NULL) == 0;
#elif defined __WXMAC__
        WKWebView * wkWebView = (WKWebView *) webView->GetNativeBackend();
        int               count   = 0;
        wxJSScriptWrapper wrapJS(javascript, &count);
        Slic3r::GUI::WKWebView_evaluateJavaScript(wkWebView, wrapJS.GetWrappedCode(), nullptr);
        return true;
#else
        WebKitWebView *wkWebView = (WebKitWebView *) webView->GetNativeBackend();
        webkit_web_view_run_javascript(
            wkWebView, javascript.utf8_str(), NULL,
            [](GObject *wkWebView, GAsyncResult *res, void *) {
                GError * error = NULL;
                auto result = webkit_web_view_run_javascript_finish((WebKitWebView*)wkWebView, res, &error);
                if (!result)
                    g_error_free (error);
                else
                    webkit_javascript_result_unref (result);
        }, NULL);
        return true;
#endif
    } catch (std::exception &e) {
        return false;
    }
}
References Slic3r::comDevelop, count, NULL, and Slic3r::GUI::WKWebView_evaluateJavaScript().
Referenced by Slic3r::GUI::DownPluginFrame::RunScript(), Slic3r::GUI::GuideFrame::RunScript(), Slic3r::GUI::ZUserLogin::RunScript(), Slic3r::GUI::WebViewPanel::RunScript(), Slic3r::GUI::MarkdownTip::RunScript(), Slic3r::GUI::ProjectPanel::RunScript(), Slic3r::GUI::PrivacyUpdateDialog::RunScript(), and Slic3r::GUI::UpdateVersionDialog::RunScript().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/WebView.hpp
src/slic3r/GUI/Widgets/WebView.cpp