OrcaSlicer: kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement > Class Template Reference
kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement > Class Template Reference
Simple tree structure with alternating half splitting nodes.
#include <src/mcut/include/mcut/internal/cdt/kdtree.h>
Classes
struct NearestTask
struct Node
Stores kd-tree node data.
Public Types
typedef TCoordType coord_type
typedef vec2_< coord_type > point_type
typedef std::pair< point_type, std::uint32_t > value_type
typedef std::vector< std::uint32_t > point_data_vec
typedef point_data_vec::const_iterator pd_cit
typedef std::array< std::uint32_t, 2 > children_type
Public Member Functions
kdtree_t_ ()
Default constructor.
kdtree_t_ (const point_type &min, const point_type &max)
Constructor with bounding box known in advance.
void insert (const std::uint32_t &iPoint, const std::vector< point_type > &points)
Insert a point into kd-tree.
value_type nearest (const point_type &point, const std::vector< point_type > &points) const
Query kd-tree for a nearest neighbor point.
Private Member Functions
std::uint32_t addNewNode ()
Add a new node and return it's index in nodes buffer.
std::size_t whichChild (const point_type &point, const coord_type &split, const NodeSplitDirection::Enum dir) const
Test which child point belongs to after the split.
void extendTree (const point_type &point)
Extend a tree by creating new root with old root and a new node as children.
void initializeRootBox (const std::vector< point_type > &points)
Calculate root's box enclosing all root points.
Static Private Member Functions
static void calcSplitInfo (const point_type &min, const point_type &max, const NodeSplitDirection::Enum dir, coord_type &midOut, NodeSplitDirection::Enum &newDirOut, point_type &newMinOut, point_type &newMaxOut)
Calculate split location, direction, and children boxes.
static bool isInsideBox (const point_type &p, const point_type &min, const point_type &max)
Test if point is inside a box.
Private Attributes
std::uint32_t m_root
std::vector< Node > m_nodes
NodeSplitDirection::Enum m_rootDir
point_type m_min
point_type m_max
bool m_isRootBoxInitialized
std::vector< NearestTask > m_tasksStack
Detailed Description
template<typename TCoordType, size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement>
class kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >
Simple tree structure with alternating half splitting nodes.
Simple tree structure
Tree to incrementally add points to the structure.
Get the nearest point to a given input.
Does not check for duplicates, expect unique points.
Template Parameters
TCoordType type used for storing point coordinate.
NumVerticesInLeaf The number of points per leaf.
InitialStackDepth initial size of stack depth for nearest query. Should be at least 1.
StackDepthIncrement increment of stack depth for nearest query when stack depth is reached.
Member Typedef Documentation
children_type
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> typedef std::array<std::uint32_t, 2> kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::children_type
coord_type
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> typedef TCoordType kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::coord_type
pd_cit
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> typedef point_data_vec::const_iterator kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::pd_cit
point_data_vec
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> typedef std::vector<std::uint32_t> kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::point_data_vec
point_type
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> typedef vec2_<coord_type> kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::point_type
value_type
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> typedef std::pair<point_type, std::uint32_t> kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::value_type
Constructor & Destructor Documentation
kdtree_t_() [1/2]
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::kdtree_t_ () inline
Default constructor.
        : m_rootDir(NodeSplitDirection::X)
        , m_min(point_type::make(
              -std::numeric_limits<coord_type>::max(),
              -std::numeric_limits<coord_type>::max()))
        , m_max(point_type::make(
              std::numeric_limits<coord_type>::max(),
              std::numeric_limits<coord_type>::max()))
        , m_isRootBoxInitialized(false)
        , m_tasksStack(InitialStackDepth, NearestTask())
    {
        m_root = addNewNode();
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::addNewNode(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_root.
kdtree_t_() [2/2]
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::kdtree_t_ (const point_type & min, const point_type & max) inline
Constructor with bounding box known in advance.
        : m_rootDir(NodeSplitDirection::X)
        , m_min(min)
        , m_max(max)
        , m_isRootBoxInitialized(true)
        , m_tasksStack(InitialStackDepth, NearestTask())
    {
        m_root = addNewNode();
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::addNewNode(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_root.
Member Function Documentation
addNewNode()
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> std::uint32_t kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::addNewNode () inline private
Add a new node and return it's index in nodes buffer.
    {
        const std::uint32_t newNodeIndex = static_cast<std::uint32_t>(m_nodes.size());
        m_nodes.push_back(Node());
        return newNodeIndex;
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_nodes.
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::kdtree_t_(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::kdtree_t_(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert().
calcSplitInfo()
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> static void kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo (const point_type & min, const point_type & max, const NodeSplitDirection::Enum dir, coord_type & midOut, NodeSplitDirection::Enum & newDirOut, point_type & newMinOut, point_type & newMaxOut) inline static private
Calculate split location, direction, and children boxes.
    {
        newMaxOut = max;
        newMinOut = min;
        switch (dir) {
        case NodeSplitDirection::X:
            midOut = (min.x() + max.x()) / coord_type(2);
            newDirOut = NodeSplitDirection::Y;
            newMinOut.x() = midOut;
            newMaxOut.x() = midOut;
            return;
        case NodeSplitDirection::Y:
            midOut = (min.y() + max.y()) / coord_type(2);
            newDirOut = NodeSplitDirection::X;
            newMinOut.y() = midOut;
            newMaxOut.y() = midOut;
            return;
        }
    }
References max(), min(), kdt::NodeSplitDirection::X, vec2_< T >::x(), kdt::NodeSplitDirection::Y, and vec2_< T >::y().
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
extendTree()
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> void kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree (const point_type & point) inline private
Extend a tree by creating new root with old root and a new node as children.
    {
        const std::uint32_t newRoot = addNewNode();
        const std::uint32_t newLeaf = addNewNode();
        switch (m_rootDir) {
        case NodeSplitDirection::X:
            m_rootDir = NodeSplitDirection::Y;
            point.y() < m_min.y() ? m_nodes[newRoot].setChildren(newLeaf, m_root)
                                  : m_nodes[newRoot].setChildren(m_root, newLeaf);
            if (point.y() < m_min.y())
                m_min.y() -= m_max.y() - m_min.y();
            else if (point.y() > m_max.y())
                m_max.y() += m_max.y() - m_min.y();
            break;
        case NodeSplitDirection::Y:
            m_rootDir = NodeSplitDirection::X;
            point.x() < m_min.x() ? m_nodes[newRoot].setChildren(newLeaf, m_root)
                                  : m_nodes[newRoot].setChildren(m_root, newLeaf);
            if (point.x() < m_min.x())
                m_min.x() -= m_max.x() - m_min.x();
            else if (point.x() > m_max.x())
                m_max.x() += m_max.x() - m_min.x();
            break;
        }
        m_root = newRoot;
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::addNewNode(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_max, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_min, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_nodes, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_root, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_rootDir, kdt::NodeSplitDirection::X, vec2_< T >::x(), kdt::NodeSplitDirection::Y, and vec2_< T >::y().
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert().
initializeRootBox()
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> void kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox (const std::vector< point_type > & points) inline private
Calculate root's box enclosing all root points.
    {
        const point_data_vec& data = m_nodes[m_root].data;
        m_min = points[data.front()];
        m_max = m_min;
        for (pd_cit it = data.begin(); it != data.end(); ++it) {
            const point_type& p = points[*it];
            m_min = point_type::make(
                std::min(m_min.x(), p.x()), std::min(m_min.y(), p.y()));
            m_max = point_type::make(
                std::max(m_max.x(), p.x()), std::max(m_max.y(), p.y()));
        }
        // Make sure bounding box does not have a zero size by adding padding:
        // zero-size bounding box cannot be extended properly
        const TCoordType padding(1);
        if (m_min.x() == m_max.x()) {
            m_min.x() -= padding;
            m_max.x() += padding;
        }
        if (m_min.y() == m_max.y()) {
            m_min.y() -= padding;
            m_max.y() += padding;
        }
        m_isRootBoxInitialized = true;
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_isRootBoxInitialized, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_max, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_min, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_nodes, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_root, vec2_< coord_type >::make(), vec2_< T >::x(), and vec2_< T >::y().
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert().
insert()
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> void kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert (const std::uint32_t & iPoint, const std::vector< point_type > & points) inline
Insert a point into kd-tree.
Note
external point-buffer is used to reduce kd-tree's memory footprint
Parameters
iPoint index of point in external point-buffer
points external point-buffer
    {
        // if point is outside root, extend tree by adding new roots
        const point_type& pos = points[iPoint];
        while (!isInsideBox(pos, m_min, m_max)) {
            extendTree(pos);
        }
        // now insert the point into the tree
        std::uint32_t node = m_root;
        point_type min = m_min;
        point_type max = m_max;
        NodeSplitDirection::Enum dir = m_rootDir;
        // below: initialized only to suppress warnings
        NodeSplitDirection::Enum newDir(NodeSplitDirection::X);
        coord_type mid(0);
        point_type newMin, newMax;
        while (true) {
            if (m_nodes[node].isLeaf()) {
                // add point if capacity is not reached
                point_data_vec& pd = m_nodes[node].data;
                if (pd.size() < NumVerticesInLeaf) {
                    pd.push_back(iPoint);
                    return;
                }
                // initialize bbox first time the root capacity is reached
                if (!m_isRootBoxInitialized) {
                    initializeRootBox(points);
                    min = m_min;
                    max = m_max;
                }
                // split a full leaf node
                calcSplitInfo(min, max, dir, mid, newDir, newMin, newMax);
                const std::uint32_t c1 = addNewNode(), c2 = addNewNode();
                Node& n = m_nodes[node];
                n.setChildren(c1, c2);
                point_data_vec& c1data = m_nodes[c1].data;
                point_data_vec& c2data = m_nodes[c2].data;
                // move node's points to children
                for (pd_cit it = n.data.begin(); it != n.data.end(); ++it) {
                    whichChild(points[*it], mid, dir) == 0
                        ? c1data.push_back(*it)
                        : c2data.push_back(*it);
                }
                n.data = point_data_vec();
            } else {
                calcSplitInfo(min, max, dir, mid, newDir, newMin, newMax);
            }
            // add the point to a child
            const std::size_t iChild = whichChild(points[iPoint], mid, dir);
            iChild == 0 ? max = newMax : min = newMin;
            node = m_nodes[node].children[iChild];
            dir = newDir;
        }
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::addNewNode(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::isInsideBox(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_isRootBoxInitialized, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_max, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_min, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_nodes, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_root, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_rootDir, max(), min(), n, pd, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::whichChild(), and kdt::NodeSplitDirection::X.
Referenced by cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::add_point(), and cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initialize().
isInsideBox()
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> static bool kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::isInsideBox (const point_type & p, const point_type & min, const point_type & max) inline static private
Test if point is inside a box.
    {
        return p.x() >= min.x() && p.x() <= max.x() && p.y() >= min.y() && p.y() <= max.y();
    }
References max(), min(), vec2_< T >::x(), and vec2_< T >::y().
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert().
nearest()
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> value_type kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest (const point_type & point, const std::vector< point_type > & points) const inline
Query kd-tree for a nearest neighbor point.
Note
external point-buffer is used to reduce kd-tree's memory footprint
Parameters
point query point position
points external point-buffer
    {
        value_type out;
        int iTask = -1;
        coord_type minDistSq = std::numeric_limits<coord_type>::max();
        m_tasksStack[++iTask] = NearestTask(m_root, m_min, m_max, m_rootDir, minDistSq);
        while (iTask != -1) {
            const NearestTask t = m_tasksStack[iTask--];
            if (t.distSq > minDistSq)
                continue;
            const Node& n = m_nodes[t.node];
            if (n.isLeaf()) {
                for (pd_cit it = n.data.begin(); it != n.data.end(); ++it) {
                    const point_type& p = points[*it];
                    const coord_type distSq = cdt::get_square_distance(point, p);
                    if (distSq < minDistSq) {
                        minDistSq = distSq;
                        out.first = p;
                        out.second = *it;
                    }
                }
            } else {
                coord_type mid(0);
                NodeSplitDirection::Enum newDir;
                point_type newMin, newMax;
                calcSplitInfo(t.min, t.max, t.dir, mid, newDir, newMin, newMax);
                const coord_type distToMid = t.dir == NodeSplitDirection::X
                    ? (point.x() - mid)
                    : (point.y() - mid);
                const coord_type toMidSq = distToMid * distToMid;
                const std::size_t iChild = whichChild(point, mid, t.dir);
                if (iTask + 2 >= static_cast<int>(m_tasksStack.size())) {
                    m_tasksStack.resize(
                        m_tasksStack.size() + StackDepthIncrement);
                }
                // node containing point should end up on top of the stack
                if (iChild == 0) {
                    m_tasksStack[++iTask] = NearestTask(
                        n.children[1], newMin, t.max, newDir, toMidSq);
                    m_tasksStack[++iTask] = NearestTask(
                        n.children[0], t.min, newMax, newDir, toMidSq);
                } else {
                    m_tasksStack[++iTask] = NearestTask(
                        n.children[0], t.min, newMax, newDir, toMidSq);
                    m_tasksStack[++iTask] = NearestTask(
                        n.children[1], newMin, t.max, newDir, toMidSq);
                }
            }
        }
        return out;
    }
References kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::NearestTask::dir, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::NearestTask::distSq, cdt::get_square_distance(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_max, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_min, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_nodes, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_root, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_rootDir, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_tasksStack, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::NearestTask::max, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::NearestTask::min, n, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::NearestTask::node, out, kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::whichChild(), kdt::NodeSplitDirection::X, vec2_< T >::x(), and vec2_< T >::y().
Referenced by cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearPoint().
whichChild()
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> std::size_t kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::whichChild (const point_type & point, const coord_type & split, const NodeSplitDirection::Enum dir) const inline private
Test which child point belongs to after the split.
Returns
0 if first child, 1 if second child
    {
        return static_cast<size_t>(
            dir == NodeSplitDirection::X ? point.x() > split : point.y() > split);
    }
References kdt::NodeSplitDirection::X, vec2_< T >::x(), and vec2_< T >::y().
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
Member Data Documentation
m_isRootBoxInitialized
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> bool kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_isRootBoxInitialized private
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert().
m_max
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> point_type kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_max private
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
m_min
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> point_type kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_min private
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
m_nodes
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> std::vector<Node> kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_nodes private
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::addNewNode(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
m_root
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> std::uint32_t kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_root private
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::kdtree_t_(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::kdtree_t_(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
m_rootDir
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> NodeSplitDirection::Enum kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_rootDir private
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::insert(), and kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
m_tasksStack
template<typename TCoordType , size_t NumVerticesInLeaf, size_t InitialStackDepth, size_t StackDepthIncrement> std::vector<NearestTask> kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::m_tasksStack mutable private
Referenced by kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/cdt/kdtree.h