OrcaSlicer: std Namespace Reference
std Namespace Reference
STL namespace.
Classes
class allocator
STL class.
class array
STL class.
class atomic
STL class.
class atomic_ref
STL class.
class auto_ptr
STL class.
class bad_alloc
STL class.
class bad_cast
STL class.
class bad_exception
STL class.
class bad_typeid
STL class.
class basic_fstream
STL class.
class basic_ifstream
STL class.
class basic_ios
STL class.
class basic_iostream
STL class.
class basic_istream
STL class.
class basic_istringstream
STL class.
class basic_ofstream
STL class.
class basic_ostream
STL class.
class basic_ostringstream
STL class.
class basic_string
STL class.
class basic_string_view
STL class.
class basic_stringstream
STL class.
class bitset
STL class.
class complex
STL class.
class deque
STL class.
class deque< T, EIGEN_ALIGNED_ALLOCATOR< T > >
class domain_error
STL class.
class error_category
STL class.
class error_code
STL class.
class error_condition
STL class.
class exception
STL class.
class forward_list
STL class.
class fstream
STL class.
struct hash< cdt::edge_t >
edge_t hasher
struct hash< edge_descriptor_t >
struct hash< face_descriptor_t >
struct hash< halfedge_descriptor_t >
struct hash< nlohmann::json >
hash value for JSON objects
struct hash< Slic3r::Arachne::PolygonsPointIndex >
struct hash< Slic3r::FloatOrPercent >
struct hash< Slic3r::Vec2d >
struct hash< Slic3r::Vec3d >
struct hash< vec2_< T > >
struct hash< vertex_descriptor_t >
class ifstream
STL class.
class invalid_argument
STL class.
class ios
STL class.
class ios_base
STL class.
class istream
STL class.
class istringstream
STL class.
class jthread
STL class.
class length_error
STL class.
struct less<::nlohmann::detail::value_t >
specialization for std::less<value_t>
class list
STL class.
class list< T, EIGEN_ALIGNED_ALLOCATOR< T > >
class lock_guard
STL class.
class logic_error
STL class.
class map
STL class.
class multimap
STL class.
class multiset
STL class.
class mutex
STL class.
struct numeric_limits< const Eigen::half >
struct numeric_limits< const volatile Eigen::half >
struct numeric_limits< Eigen::half >
struct numeric_limits< volatile Eigen::half >
class ofstream
STL class.
class ostream
STL class.
class ostringstream
STL class.
class out_of_range
STL class.
class overflow_error
STL class.
class priority_queue
STL class.
class queue
STL class.
class range_error
STL class.
class recursive_mutex
STL class.
class recursive_timed_mutex
STL class.
class runtime_error
STL class.
class set
STL class.
class shared_lock
STL class.
class shared_mutex
STL class.
class shared_ptr
STL class.
class shared_timed_mutex
STL class.
class smart_ptr
STL class.
class span
STL class.
class stack
STL class.
class string
STL class.
class string_view
STL class.
class stringstream
STL class.
class system_error
STL class.
class thread
STL class.
class timed_mutex
STL class.
class tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >
class tuple_size<::nlohmann::detail::iteration_proxy_value< IteratorType > >
class u16string
STL class.
class u16string_view
STL class.
class u32string
STL class.
class u32string_view
STL class.
class u8string
STL class.
class u8string_view
STL class.
class underflow_error
STL class.
class unique_lock
STL class.
class unique_ptr
STL class.
class unordered_map
STL class.
class unordered_multimap
STL class.
class unordered_multiset
STL class.
class unordered_set
STL class.
class valarray
STL class.
class vector
STL class.
class vector< T, EIGEN_ALIGNED_ALLOCATOR< T > >
class weak_ptr
STL class.
class wfstream
STL class.
class wifstream
STL class.
class wios
STL class.
class wistream
STL class.
class wistringstream
STL class.
class wofstream
STL class.
class wostream
STL class.
class wostringstream
STL class.
class wstring
STL class.
class wstring_view
STL class.
class wstringstream
STL class.
Functions
template<class _Elem , class _Traits , class _Arg >
basic_ostream< _Elem, _Traits > & operator<< (basic_ostream< _Elem, _Traits > &ostr, const hex_wrap< _Arg > &wrap)
template<>
edge_array_iterator_t::difference_type distance (edge_array_iterator_t first, edge_array_iterator_t last)
template<>
edge_array_iterator_t::difference_type distance (edge_array_iterator_t first, edge_array_iterator_t last)
template<>
void swap< nlohmann::json > (nlohmann::json &j1, nlohmann::json &j2) noexcept(//NOLINT(readability-inconsistent-declaration-parameter-name) is_nothrow_move_constructible< nlohmann::json >::value &&//NOLINT(misc-redundant-expression) is_nothrow_move_assignable< nlohmann::json >::value)
exchanges the values of two JSON objects
Detailed Description
STL namespace.
Class Documentation
std::tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >
class std::tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >
template<std::size_t N, typename IteratorType>
class std::tuple_element< N, ::nlohmann::detail::iteration_proxy_value< IteratorType > >
Class Members
typedef decltype(get< N >(declval< ::iteration_proxy_value< IteratorType > >())) type
Function Documentation
distance() [1/2]
template<> edge_array_iterator_t::difference_type std::distance (edge_array_iterator_t first, edge_array_iterator_t last) inline
{
    MCUT_ASSERT(first.get_mesh_ptr() == last.get_mesh_ptr());
    edge_array_iterator_t it = first;
    edge_array_iterator_t::difference_type dist = last - first;
    uint32_t r = it.get_mesh_ptr()->count_removed_elements_in_range(first, last);
    if (r > 0) {
        dist = dist - r;
    }
    MCUT_ASSERT(dist >= 0);
    return dist;
}
References hmesh_t::count_removed_elements_in_range(), array_iterator_t< V >::get_mesh_ptr(), and MCUT_ASSERT.
Referenced by Slic3r::MachineObject::ams_filament_mapping(), Slic3r::calc_threshold(), Slic3r::GUI::Selection::center(), Slic3r::Geometry::circle_center_taubin_newton(), client_input_arrays_to_hmesh(), Slic3r::LinesBucket::curRange(), dispatch(), extract_connected_components(), PrinterFileSystem::FileRemoved(), cdt::find_duplicates(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::find_min_score(), PrinterFileSystem::FindFile(), get_connected_component_data_impl_detail(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::GUI::PartPlate::get_extruders_without_support(), Slic3r::GUI::GCodeViewer::Layers::get_l_at(), PrinterFileSystem::GetIndexAtTime(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert_iterator(), cdt::triangulator_t< T, TNearPointLocator >::insert_vertices(), Slic3r::its_remove_degenerate_faces(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::lower_bound_by_predicate(), parallel_find(), parallel_find_if(), parallel_find_in_map_by_key(), parallel_for(), parallel_for(), parallel_partial_sum(), Slic3r::GCodeProcessor::TimeProcessor::post_process(), Slic3r::GUI::GLGizmoAdvancedCut::put_connectors_on_cut_plane(), Slic3r::GUI::GLCanvas3D::render_thumbnail_internal(), resolve_floating_polygons(), Slic3r::GUI::Camera::set_distance(), DropDown::SetValue(), Slic3r::Range< It >::size(), and Slic3r::GUI::GLGizmoText::update_text_positions().
distance() [2/2]
template<> edge_array_iterator_t::difference_type std::distance (edge_array_iterator_t first, edge_array_iterator_t last) inline
{
    MCUT_ASSERT(first.get_mesh_ptr() == last.get_mesh_ptr());
    edge_array_iterator_t it = first;
    edge_array_iterator_t::difference_type dist = last - first;
    uint32_t r = it.get_mesh_ptr()->count_removed_elements_in_range(first, last);
    if (r > 0) {
        dist = dist - r;
    }
    MCUT_ASSERT(dist >= 0);
    return dist;
}
References hmesh_t::count_removed_elements_in_range(), array_iterator_t< V >::get_mesh_ptr(), and MCUT_ASSERT.
Referenced by Slic3r::MachineObject::ams_filament_mapping(), Slic3r::calc_threshold(), Slic3r::GUI::Selection::center(), Slic3r::Geometry::circle_center_taubin_newton(), client_input_arrays_to_hmesh(), Slic3r::LinesBucket::curRange(), dispatch(), extract_connected_components(), PrinterFileSystem::FileRemoved(), cdt::find_duplicates(), Slic3r::sla::anonymous_namespace{Rotfinder.cpp}::find_min_score(), PrinterFileSystem::FindFile(), get_connected_component_data_impl_detail(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::GUI::PartPlate::get_extruders_without_support(), Slic3r::GUI::GCodeViewer::Layers::get_l_at(), PrinterFileSystem::GetIndexAtTime(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert_iterator(), cdt::triangulator_t< T, TNearPointLocator >::insert_vertices(), Slic3r::its_remove_degenerate_faces(), Slic3r::GUI::GCodeViewer::load_toolpaths(), Slic3r::lower_bound_by_predicate(), parallel_find(), parallel_find_if(), parallel_find_in_map_by_key(), parallel_for(), parallel_for(), parallel_partial_sum(), Slic3r::GCodeProcessor::TimeProcessor::post_process(), Slic3r::GUI::GLGizmoAdvancedCut::put_connectors_on_cut_plane(), Slic3r::GUI::GLCanvas3D::render_thumbnail_internal(), resolve_floating_polygons(), Slic3r::GUI::Camera::set_distance(), DropDown::SetValue(), Slic3r::Range< It >::size(), and Slic3r::GUI::GLGizmoText::update_text_positions().
operator<<()
template<class _Elem , class _Traits , class _Arg > basic_ostream< _Elem, _Traits > & std::operator<< (basic_ostream< _Elem, _Traits > & ostr, const hex_wrap< _Arg > & wrap)
                                    { // insert by calling function with output stream and argument
        auto of = ostr.fill('0');
        ostr << setw(sizeof(_Arg) * 2) << std::hex << wrap.t;
        ostr << std::dec << setw(0);
        ostr.fill(of);
        return ostr;
    }
swap< nlohmann::json >()
template<> void std::swap< nlohmann::json > (nlohmann::json & j1, nlohmann::json & j2) inline noexcept
exchanges the values of two JSON objects
Since
version 1.0.0
{
    j1.swap(j2);
}