OrcaSlicer: src/slic3r/GUI/Printer/BambuTunnel.h File Reference
BambuTunnel.h File Reference
#include <stdbool.h>
Classes
struct __Bambu_StreamInfo
struct __Bambu_Sample
union __Bambu_StreamInfo.format
struct __Bambu_StreamInfo.format.video
struct __Bambu_StreamInfo.format.audio
Macros
#define BAMBU_EXPORT
#define BAMBU_FUNC(x) x
Typedefs
typedef char tchar
typedef void * Bambu_Tunnel
typedef void(* Logger) (void *context, int level, tchar const *msg)
typedef enum __Bambu_StreamType Bambu_StreamType
typedef enum __Bambu_VideoSubType Bambu_VideoSubType
typedef enum __Bambu_AudioSubType Bambu_AudioSubType
typedef enum __Bambu_FormatType Bambu_FormatType
typedef struct __Bambu_StreamInfo Bambu_StreamInfo
typedef enum __Bambu_SampleFlag Bambu_SampleFlag
typedef struct __Bambu_Sample Bambu_Sample
typedef enum __Bambu_Error Bambu_Error
Enumerations
enum __Bambu_StreamType { VIDE , AUDI }
enum __Bambu_VideoSubType { AVC1 , MJPG }
enum __Bambu_AudioSubType { MP4A }
enum __Bambu_FormatType {
video_avc_packet , video_avc_byte_stream , video_jpeg , audio_raw ,
audio_adts
}
enum __Bambu_SampleFlag { f_sync = 1 }
enum __Bambu_Error { Bambu_success , Bambu_stream_end , Bambu_would_block , Bambu_buffer_limit }
Functions
BAMBU_EXPORT int BAMBU_FUNC() Bambu_Create (Bambu_Tunnel *tunnel, char const *path)
BAMBU_EXPORT void BAMBU_FUNC() Bambu_SetLogger (Bambu_Tunnel tunnel, Logger logger, void *context)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_Open (Bambu_Tunnel tunnel)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_StartStream (Bambu_Tunnel tunnel, bool video)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_GetStreamCount (Bambu_Tunnel tunnel)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_GetStreamInfo (Bambu_Tunnel tunnel, int index, Bambu_StreamInfo *info)
BAMBU_EXPORT unsigned long BAMBU_FUNC() Bambu_GetDuration (Bambu_Tunnel tunnel)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_Seek (Bambu_Tunnel tunnel, unsigned long time)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_ReadSample (Bambu_Tunnel tunnel, Bambu_Sample *sample)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_SendMessage (Bambu_Tunnel tunnel, int ctrl, char const *data, int len)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_RecvMessage (Bambu_Tunnel tunnel, int *ctrl, char *data, int *len)
BAMBU_EXPORT void BAMBU_FUNC() Bambu_Close (Bambu_Tunnel tunnel)
BAMBU_EXPORT void BAMBU_FUNC() Bambu_Destroy (Bambu_Tunnel tunnel)
BAMBU_EXPORT int BAMBU_FUNC() Bambu_Init ()
BAMBU_EXPORT void BAMBU_FUNC() Bambu_Deinit ()
BAMBU_EXPORT char const *BAMBU_FUNC() Bambu_GetLastErrorMsg ()
BAMBU_EXPORT void BAMBU_FUNC() Bambu_FreeLogMsg (tchar const *msg)
Class Documentation
__Bambu_StreamInfo
struct __Bambu_StreamInfo
Class Members
union __Bambu_StreamInfo.format format
unsigned char const * format_buffer
int format_size
int format_type
int max_frame_size
int sub_type
Bambu_StreamType type
__Bambu_Sample
struct __Bambu_Sample
Class Members
unsigned char const * buffer
unsigned long long decode_time
int flags
int itrack
int size
__Bambu_StreamInfo.format
union __Bambu_StreamInfo.format
Class Members
struct __Bambu_StreamInfo.format.audio audio
struct __Bambu_StreamInfo.format.video video
__Bambu_StreamInfo.format.video
struct __Bambu_StreamInfo.format.video
Class Members
int frame_rate
int height
int width
__Bambu_StreamInfo.format.audio
struct __Bambu_StreamInfo.format.audio
Class Members
int channel_count
int sample_rate
int sample_size
Macro Definition Documentation
BAMBU_EXPORT
#define BAMBU_EXPORT
BAMBU_FUNC
#define BAMBU_FUNC (x) x
Typedef Documentation
Bambu_AudioSubType
typedef enum __Bambu_AudioSubType Bambu_AudioSubType
Bambu_Error
typedef enum __Bambu_Error Bambu_Error
Bambu_FormatType
typedef enum __Bambu_FormatType Bambu_FormatType
Bambu_Sample
typedef struct __Bambu_Sample Bambu_Sample
Bambu_SampleFlag
typedef enum __Bambu_SampleFlag Bambu_SampleFlag
Bambu_StreamInfo
typedef struct __Bambu_StreamInfo Bambu_StreamInfo
Bambu_StreamType
typedef enum __Bambu_StreamType Bambu_StreamType
Bambu_Tunnel
typedef void* Bambu_Tunnel
Bambu_VideoSubType
typedef enum __Bambu_VideoSubType Bambu_VideoSubType
Logger
typedef void(* Logger) (void *context, int level, tchar const *msg)
tchar
typedef char tchar
Enumeration Type Documentation
__Bambu_AudioSubType
enum __Bambu_AudioSubType
Enumerator
MP4A
{
    MP4A
} Bambu_AudioSubType;
__Bambu_Error
enum __Bambu_Error
Enumerator
Bambu_success
Bambu_stream_end
Bambu_would_block
Bambu_buffer_limit
{
    Bambu_success,
    Bambu_stream_end,
    Bambu_would_block,
    Bambu_buffer_limit
} Bambu_Error;
__Bambu_FormatType
enum __Bambu_FormatType
Enumerator
video_avc_packet
video_avc_byte_stream
video_jpeg
audio_raw
audio_adts
{
    video_avc_packet,
    video_avc_byte_stream,
    video_jpeg,
    audio_raw,
    audio_adts
} Bambu_FormatType;
__Bambu_SampleFlag
enum __Bambu_SampleFlag
Enumerator
f_sync
{
    f_sync = 1
} Bambu_SampleFlag;
__Bambu_StreamType
enum __Bambu_StreamType
Enumerator
VIDE
AUDI
{
    VIDE,
    AUDI
} Bambu_StreamType;
__Bambu_VideoSubType
enum __Bambu_VideoSubType
Enumerator
AVC1
MJPG
{
    AVC1,
    MJPG,
} Bambu_VideoSubType;
Function Documentation
Bambu_Close()
BAMBU_EXPORT void BAMBU_FUNC() Bambu_Close (Bambu_Tunnel tunnel)
Referenced by StaticBambuLib::get(), gst_bambusrc_finalize(), gst_bambusrc_reset(), gst_bambusrc_start(), gst_bambusrc_stop(), and PrinterFileSystem::Reconnect().
Bambu_Create()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_Create (Bambu_Tunnel * tunnel, char const * path)
Referenced by StaticBambuLib::get(), gst_bambusrc_start(), and PrinterFileSystem::Reconnect().
Bambu_Deinit()
BAMBU_EXPORT void BAMBU_FUNC() Bambu_Deinit ()
Bambu_Destroy()
BAMBU_EXPORT void BAMBU_FUNC() Bambu_Destroy (Bambu_Tunnel tunnel)
Referenced by StaticBambuLib::get(), gst_bambusrc_finalize(), gst_bambusrc_reset(), gst_bambusrc_start(), gst_bambusrc_stop(), and PrinterFileSystem::Reconnect().
Bambu_FreeLogMsg()
BAMBU_EXPORT void BAMBU_FUNC() Bambu_FreeLogMsg (tchar const * msg)
Referenced by _log(), PrinterFileSystem::DumpLog(), and StaticBambuLib::get().
Bambu_GetDuration()
BAMBU_EXPORT unsigned long BAMBU_FUNC() Bambu_GetDuration (Bambu_Tunnel tunnel)
Bambu_GetLastErrorMsg()
BAMBU_EXPORT char const *BAMBU_FUNC() Bambu_GetLastErrorMsg ()
Bambu_GetStreamCount()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_GetStreamCount (Bambu_Tunnel tunnel)
Referenced by StaticBambuLib::get(), and gst_bambusrc_start().
Bambu_GetStreamInfo()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_GetStreamInfo (Bambu_Tunnel tunnel, int index, Bambu_StreamInfo * info)
Referenced by StaticBambuLib::get(), and gst_bambusrc_start().
Bambu_Init()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_Init ()
Bambu_Open()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_Open (Bambu_Tunnel tunnel)
Referenced by StaticBambuLib::get(), gst_bambusrc_start(), and PrinterFileSystem::Reconnect().
Bambu_ReadSample()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_ReadSample (Bambu_Tunnel tunnel, Bambu_Sample * sample)
Referenced by StaticBambuLib::get(), gst_bambusrc_create(), PrinterFileSystem::RecvData(), and PrinterFileSystem::RecvMessageThread().
Bambu_RecvMessage()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_RecvMessage (Bambu_Tunnel tunnel, int * ctrl, char * data, int * len)
Bambu_Seek()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_Seek (Bambu_Tunnel tunnel, unsigned long time)
Bambu_SendMessage()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_SendMessage (Bambu_Tunnel tunnel, int ctrl, char const * data, int len)
Referenced by StaticBambuLib::get(), and PrinterFileSystem::RecvMessageThread().
Bambu_SetLogger()
BAMBU_EXPORT void BAMBU_FUNC() Bambu_SetLogger (Bambu_Tunnel tunnel, Logger logger, void * context)
Referenced by StaticBambuLib::get(), gst_bambusrc_start(), and PrinterFileSystem::Reconnect().
Bambu_StartStream()
BAMBU_EXPORT int BAMBU_FUNC() Bambu_StartStream (Bambu_Tunnel tunnel, bool video)
Referenced by StaticBambuLib::get(), gst_bambusrc_start(), and PrinterFileSystem::Reconnect().