OrcaSlicer: Slic3r::Geometry::Transformation Class Reference
Slic3r::Geometry::Transformation Class Reference
#include <src/libslic3r/Geometry.hpp>
Classes
struct Flags
Public Member Functions
Transformation ()
Transformation (const Transform3d &transform)
bool is_dirty ()
const Vec3d & get_offset () const
double get_offset (Axis axis) const
void set_offset (const Vec3d &offset)
void set_offset (Axis axis, double offset)
const Vec3d & get_rotation () const
double get_rotation (Axis axis) const
void set_rotation (const Vec3d &rotation)
void set_rotation (Axis axis, double rotation)
const Vec3d & get_scaling_factor () const
double get_scaling_factor (Axis axis) const
void set_scaling_factor (const Vec3d &scaling_factor)
void set_scaling_factor (Axis axis, double scaling_factor)
bool is_scaling_uniform () const
const Vec3d & get_mirror () const
double get_mirror (Axis axis) const
bool is_left_handed () const
void set_mirror (const Vec3d &mirror)
void set_mirror (Axis axis, double mirror)
void set_from_transform (const Transform3d &transform)
void reset ()
const Transform3d & get_matrix (bool dont_translate=false, bool dont_rotate=false, bool dont_scale=false, bool dont_mirror=false) const
Transformation operator* (const Transformation &other) const
Static Public Member Functions
static Transformation volume_to_bed_transformation (const Transformation &instance_transformation, const BoundingBoxf3 &bbox)
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Transformation (int)
Static Private Member Functions
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< Transformation > &construct)
Private Attributes
Vec3d m_offset
Vec3d m_rotation
Vec3d m_scaling_factor
Vec3d m_mirror
Transform3d m_matrix
Flags m_flags
bool m_dirty
Friends
class cereal::access
bool operator== (Transformation const &l, Transformation const &r)
Detailed Description
Constructor & Destructor Documentation
Transformation() [1/3]
Slic3r::Geometry::Transformation::Transformation ()
{
    reset();
}
References reset().
Referenced by operator*().
Transformation() [2/3]
Slic3r::Geometry::Transformation::Transformation (const Transform3d & transform) explicit
{
    set_from_transform(transform);
}
References set_from_transform(), and Slic3r::transform().
Transformation() [3/3]
Slic3r::Geometry::Transformation::Transformation (int) inline explicit private
: m_dirty(true) {}
Member Function Documentation
get_matrix()
const Transform3d & Slic3r::Geometry::Transformation::get_matrix (bool dont_translate = false, bool dont_rotate = false, bool dont_scale = false, bool dont_mirror = false) const
{
    if (m_dirty || m_flags.needs_update(dont_translate, dont_rotate, dont_scale, dont_mirror))
    {
        m_matrix = Geometry::assemble_transform(
            dont_translate ? Vec3d::Zero() : m_offset,
            dont_rotate ? Vec3d::Zero() : m_rotation,
            dont_scale ? Vec3d::Ones() : m_scaling_factor,
            dont_mirror ? Vec3d::Ones() : m_mirror
            );
        m_flags.set(dont_translate, dont_rotate, dont_scale, dont_mirror);
        m_dirty = false;
    }
    return m_matrix;
}
References Slic3r::Geometry::assemble_transform(), m_dirty, m_flags, m_matrix, m_mirror, m_offset, m_rotation, m_scaling_factor, Slic3r::Geometry::Transformation::Flags::needs_update(), and Slic3r::Geometry::Transformation::Flags::set().
Referenced by Slic3r::GUI::ObjectList::apply_object_instance_transfrom_to_all_volumes(), Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::ModelObject::delete_volume(), Slic3r::ModelVolume::get_convex_hull_2d(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelVolume::get_matrix(), Slic3r::ModelInstance::get_matrix(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::ModelObject::instance_bounding_box(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::ModelVolume::load(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_update(), operator*(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::ModelObject::process_volume_cut(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::reset_instance_transformation(), Slic3r::GUI::Selection::scale(), set_from_transform(), Slic3r::GUI::MeshClipper::set_transformation(), Slic3r::ModelObject::split(), Slic3r::GUI::GLGizmoRotate::transform_to_local(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut::update_contours(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), Slic3r::GUI::GLGizmoText::update_text_positions(), volume_to_bed_transformation(), and Slic3r::GLVolume::world_matrix().
get_mirror() [1/2]
const Vec3d & Slic3r::Geometry::Transformation::get_mirror () const inline
{ return m_mirror; }
References m_mirror.
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::ModelVolume::calculate_convex_hull_2d(), Slic3r::ModelVolume::get_convex_hull_2d(), Slic3r::GLVolume::get_instance_mirror(), Slic3r::GLVolume::get_instance_mirror(), Slic3r::ModelVolume::get_mirror(), Slic3r::ModelInstance::get_mirror(), Slic3r::ModelVolume::get_mirror(), Slic3r::ModelInstance::get_mirror(), Slic3r::GLVolume::get_volume_mirror(), Slic3r::GLVolume::get_volume_mirror(), Slic3r::GLVolume::is_left_handed(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), and volume_to_bed_transformation().
get_mirror() [2/2]
double Slic3r::Geometry::Transformation::get_mirror (Axis axis) const inline
{ return m_mirror(axis); }
References m_mirror.
get_offset() [1/2]
const Vec3d & Slic3r::Geometry::Transformation::get_offset () const inline
{ return m_offset; }
References m_offset.
Referenced by Slic3r::GUI::PartPlate::add_instance(), Slic3r::GUI::ObjectList::apply_object_instance_transfrom_to_all_volumes(), Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::ModelVolume::calculate_convex_hull_2d(), Slic3r::Model::convert_multipart_object(), Slic3r::GLVolume::get_instance_offset(), Slic3r::GLVolume::get_instance_offset(), Slic3r::ModelVolume::get_offset(), Slic3r::ModelInstance::get_offset(), Slic3r::ModelVolume::get_offset(), Slic3r::ModelInstance::get_offset(), Slic3r::GUI::GLGizmoText::get_text_mesh(), Slic3r::GLVolume::get_volume_offset(), Slic3r::GLVolume::get_volume_offset(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::ModelObject::process_volume_cut(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::render_cut(), Slic3r::GUI::PartPlate::set_pos_and_size(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoText::update_text_positions(), and Slic3r::GLVolume::world_matrix().
get_offset() [2/2]
double Slic3r::Geometry::Transformation::get_offset (Axis axis) const inline
{ return m_offset(axis); }
References m_offset.
get_rotation() [1/2]
const Vec3d & Slic3r::Geometry::Transformation::get_rotation () const inline
{ return m_rotation; }
References m_rotation.
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::ModelVolume::calculate_convex_hull_2d(), Slic3r::ModelVolume::get_convex_hull_2d(), Slic3r::GLVolume::get_instance_rotation(), Slic3r::GLVolume::get_instance_rotation(), Slic3r::ModelVolume::get_rotation(), Slic3r::ModelInstance::get_rotation(), Slic3r::ModelVolume::get_rotation(), Slic3r::ModelInstance::get_rotation(), Slic3r::GLVolume::get_volume_rotation(), Slic3r::GLVolume::get_volume_rotation(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::ModelInstance::rotate_assemble(), and volume_to_bed_transformation().
get_rotation() [2/2]
double Slic3r::Geometry::Transformation::get_rotation (Axis axis) const inline
{ return m_rotation(axis); }
References m_rotation.
get_scaling_factor() [1/2]
const Vec3d & Slic3r::Geometry::Transformation::get_scaling_factor () const inline
{ return m_scaling_factor; }
References m_scaling_factor.
Referenced by Slic3r::TriangleSelector::Cursor::Cursor(), Slic3r::_3MF_Importer::_apply_transform(), Slic3r::_BBS_3MF_Importer::_apply_transform(), Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::ModelVolume::calculate_convex_hull_2d(), Slic3r::ModelVolume::get_convex_hull_2d(), Slic3r::GLVolume::get_instance_scaling_factor(), Slic3r::GLVolume::get_instance_scaling_factor(), Slic3r::ModelVolume::get_scaling_factor(), Slic3r::ModelInstance::get_scaling_factor(), Slic3r::ModelVolume::get_scaling_factor(), Slic3r::ModelInstance::get_scaling_factor(), Slic3r::GUI::MeshRaycaster::get_unobscured_idxs(), Slic3r::GLVolume::get_volume_scaling_factor(), Slic3r::GLVolume::get_volume_scaling_factor(), Slic3r::GUI::MeshClipper::recalculate_triangles(), Slic3r::GUI::GLGizmoFlatten::update_planes(), and volume_to_bed_transformation().
get_scaling_factor() [2/2]
double Slic3r::Geometry::Transformation::get_scaling_factor (Axis axis) const inline
{ return m_scaling_factor(axis); }
References m_scaling_factor.
is_dirty()
bool Slic3r::Geometry::Transformation::is_dirty () inline
{ return m_dirty; }
References m_dirty.
is_left_handed()
bool Slic3r::Geometry::Transformation::is_left_handed () const inline
{ return m_mirror.x() * m_mirror.y() * m_mirror.z() < 0.; }
References m_mirror.
Referenced by Slic3r::ModelObject::bake_xy_rotation_into_meshes(), Slic3r::ModelVolume::is_left_handed(), Slic3r::ModelInstance::is_left_handed(), and Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere().
is_scaling_uniform()
bool Slic3r::Geometry::Transformation::is_scaling_uniform () const inline
{ return std::abs(m_scaling_factor.x() - m_scaling_factor.y()) < 1e-8 && std::abs(m_scaling_factor.x() - m_scaling_factor.z()) < 1e-8; }
References m_scaling_factor.
Referenced by volume_to_bed_transformation().
load_and_construct()
template<class Archive > static void Slic3r::Geometry::Transformation::load_and_construct (Archive & ar, cereal::construct< Transformation > & construct) inline static private
  {
    // Calling a private constructor with special "int" parameter to indicate that no construction is necessary.
    construct(1);
    ar(construct.ptr()->m_offset, construct.ptr()->m_rotation, construct.ptr()->m_scaling_factor, construct.ptr()->m_mirror);
  }
operator*()
Transformation Slic3r::Geometry::Transformation::operator* (const Transformation & other) const
{
    return Transformation(get_matrix() * other.get_matrix());
}
References Transformation(), and get_matrix().
reset()
void Slic3r::Geometry::Transformation::reset ()
{
    m_offset = Vec3d::Zero();
    m_rotation = Vec3d::Zero();
    m_scaling_factor = Vec3d::Ones();
    m_mirror = Vec3d::Ones();
    m_matrix = Transform3d::Identity();
    m_dirty = false;
}
References Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), m_dirty, m_matrix, m_mirror, m_offset, m_rotation, and m_scaling_factor.
Referenced by Transformation().
serialize()
template<class Archive > void Slic3r::Geometry::Transformation::serialize (Archive & ar) inline private
{ ar(m_offset, m_rotation, m_scaling_factor, m_mirror); }
References m_mirror, m_offset, m_rotation, and m_scaling_factor.
set_from_transform()
void Slic3r::Geometry::Transformation::set_from_transform (const Transform3d & transform)
{
    // offset
    set_offset(transform.matrix().block(0, 3, 3, 1));
    Eigen::Matrix<double, 3, 3, Eigen::DontAlign> m3x3 = transform.matrix().block(0, 0, 3, 3);
    // mirror
    // it is impossible to reconstruct the original mirroring factors from a matrix,
    // we can only detect if the matrix contains a left handed reference system
    // in which case we reorient it back to right handed by mirroring the x axis
    Vec3d mirror = Vec3d::Ones();
    if (m3x3.col(0).dot(m3x3.col(1).cross(m3x3.col(2))) < 0.0)
    {
        mirror(0) = -1.0;
        // remove mirror
        m3x3.col(0) *= -1.0;
    }
    set_mirror(mirror);
    // scale
    set_scaling_factor(Vec3d(m3x3.col(0).norm(), m3x3.col(1).norm(), m3x3.col(2).norm()));
    // remove scale
    m3x3.col(0).normalize();
    m3x3.col(1).normalize();
    m3x3.col(2).normalize();
    // rotation
    set_rotation(extract_euler_angles(m3x3));
    // forces matrix recalculation matrix
    m_matrix = get_matrix();
//    // debug check
//    if (!m_matrix.isApprox(transform))
//        std::cout << "something went wrong in extracting data from matrix" << std::endl;
}
References Slic3r::Geometry::extract_euler_angles(), get_matrix(), m_matrix, set_mirror(), set_offset(), set_rotation(), set_scaling_factor(), and Slic3r::transform().
Referenced by Transformation(), Slic3r::ModelInstance::set_assemble_from_transform(), and Slic3r::ModelVolume::set_transformation().
set_mirror() [1/2]
void Slic3r::Geometry::Transformation::set_mirror (Axis axis, double mirror)
{
    double abs_mirror = std::abs(mirror);
    if (abs_mirror == 0.0)
        mirror = 1.0;
    else if (abs_mirror != 1.0)
        mirror /= abs_mirror;
    if (m_mirror(axis) != mirror)
    {
        m_mirror(axis) = mirror;
        m_dirty = true;
    }
}
References m_dirty, and m_mirror.
set_mirror() [2/2]
void Slic3r::Geometry::Transformation::set_mirror (const Vec3d & mirror)
{
    set_mirror(X, mirror(0));
    set_mirror(Y, mirror(1));
    set_mirror(Z, mirror(2));
}
References set_mirror(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), set_from_transform(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::ModelVolume::set_mirror(), Slic3r::ModelInstance::set_mirror(), set_mirror(), Slic3r::ModelVolume::set_mirror(), Slic3r::ModelInstance::set_mirror(), Slic3r::GLVolume::set_volume_mirror(), and Slic3r::GLVolume::set_volume_mirror().
set_offset() [1/2]
void Slic3r::Geometry::Transformation::set_offset (Axis axis, double offset)
{
    if (m_offset(axis) != offset)
    {
        m_offset(axis) = offset;
        m_dirty = true;
    }
}
References m_dirty, m_offset, and Slic3r::offset().
set_offset() [2/2]
void Slic3r::Geometry::Transformation::set_offset (const Vec3d & offset)
{
    set_offset(X, offset(0));
    set_offset(Y, offset(1));
    set_offset(Z, offset(2));
}
References Slic3r::offset(), set_offset(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by Slic3r::GUI::ObjectList::apply_object_instance_transfrom_to_all_volumes(), Slic3r::Model::convert_multipart_object(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::render_cut(), Slic3r::reset_instance_transformation(), Slic3r::ModelInstance::set_assemble_offset(), set_from_transform(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_offset(), Slic3r::ModelVolume::set_offset(), Slic3r::ModelInstance::set_offset(), set_offset(), Slic3r::ModelVolume::set_offset(), Slic3r::ModelInstance::set_offset(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_offset(), Slic3r::ModelObject::split(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
set_rotation() [1/2]
void Slic3r::Geometry::Transformation::set_rotation (Axis axis, double rotation)
{
    rotation = angle_to_0_2PI(rotation);
    if (is_approx(std::abs(rotation), 2.0 * (double)PI))
        rotation = 0.0;
    if (m_rotation(axis) != rotation)
    {
        m_rotation(axis) = rotation;
        m_dirty = true;
    }
}
References Slic3r::Geometry::angle_to_0_2PI(), Slic3r::is_approx(), m_dirty, m_rotation, and PI.
set_rotation() [2/2]
void Slic3r::Geometry::Transformation::set_rotation (const Vec3d & rotation)
{
    set_rotation(X, rotation(0));
    set_rotation(Y, rotation(1));
    set_rotation(Z, rotation(2));
}
References set_rotation(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::ModelInstance::rotate_assemble(), set_from_transform(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::ModelVolume::set_rotation(), Slic3r::ModelInstance::set_rotation(), set_rotation(), Slic3r::ModelVolume::set_rotation(), Slic3r::ModelInstance::set_rotation(), Slic3r::GLVolume::set_volume_rotation(), Slic3r::GLVolume::set_volume_rotation(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
set_scaling_factor() [1/2]
void Slic3r::Geometry::Transformation::set_scaling_factor (Axis axis, double scaling_factor)
{
    if (m_scaling_factor(axis) != std::abs(scaling_factor))
    {
        m_scaling_factor(axis) = std::abs(scaling_factor);
        m_dirty = true;
    }
}
References m_dirty, and m_scaling_factor.
set_scaling_factor() [2/2]
void Slic3r::Geometry::Transformation::set_scaling_factor (const Vec3d & scaling_factor)
{
    set_scaling_factor(X, scaling_factor(0));
    set_scaling_factor(Y, scaling_factor(1));
    set_scaling_factor(Z, scaling_factor(2));
}
References set_scaling_factor(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), set_from_transform(), Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::ModelVolume::set_scaling_factor(), Slic3r::ModelInstance::set_scaling_factor(), set_scaling_factor(), Slic3r::ModelVolume::set_scaling_factor(), Slic3r::ModelInstance::set_scaling_factor(), Slic3r::GLVolume::set_volume_scaling_factor(), Slic3r::GLVolume::set_volume_scaling_factor(), and Slic3r::GUI::GLGizmoFlatten::update_planes().
volume_to_bed_transformation()
Transformation Slic3r::Geometry::Transformation::volume_to_bed_transformation (const Transformation & instance_transformation, const BoundingBoxf3 & bbox) static
{
    Transformation out;
    if (instance_transformation.is_scaling_uniform()) {
        // No need to run the non-linear least squares fitting for uniform scaling.
        // Just set the inverse.
        out.set_from_transform(instance_transformation.get_matrix(true).inverse());
    }
    else if (is_rotation_ninety_degrees(instance_transformation.get_rotation()))
    {
        // Anisotropic scaling, rotation by multiples of ninety degrees.
        Eigen::Matrix3d instance_rotation_trafo =
            (Eigen::AngleAxisd(instance_transformation.get_rotation().z(), Vec3d::UnitZ()) *
            Eigen::AngleAxisd(instance_transformation.get_rotation().y(), Vec3d::UnitY()) *
            Eigen::AngleAxisd(instance_transformation.get_rotation().x(), Vec3d::UnitX())).toRotationMatrix();
        Eigen::Matrix3d volume_rotation_trafo =
            (Eigen::AngleAxisd(-instance_transformation.get_rotation().x(), Vec3d::UnitX()) *
            Eigen::AngleAxisd(-instance_transformation.get_rotation().y(), Vec3d::UnitY()) *
            Eigen::AngleAxisd(-instance_transformation.get_rotation().z(), Vec3d::UnitZ())).toRotationMatrix();
        // 8 corners of the bounding box.
        auto pts = Eigen::MatrixXd(8, 3);
        pts(0, 0) = bbox.min.x(); pts(0, 1) = bbox.min.y(); pts(0, 2) = bbox.min.z();
        pts(1, 0) = bbox.min.x(); pts(1, 1) = bbox.min.y(); pts(1, 2) = bbox.max.z();
        pts(2, 0) = bbox.min.x(); pts(2, 1) = bbox.max.y(); pts(2, 2) = bbox.min.z();
        pts(3, 0) = bbox.min.x(); pts(3, 1) = bbox.max.y(); pts(3, 2) = bbox.max.z();
        pts(4, 0) = bbox.max.x(); pts(4, 1) = bbox.min.y(); pts(4, 2) = bbox.min.z();
        pts(5, 0) = bbox.max.x(); pts(5, 1) = bbox.min.y(); pts(5, 2) = bbox.max.z();
        pts(6, 0) = bbox.max.x(); pts(6, 1) = bbox.max.y(); pts(6, 2) = bbox.min.z();
        pts(7, 0) = bbox.max.x(); pts(7, 1) = bbox.max.y(); pts(7, 2) = bbox.max.z();
        // Corners of the bounding box transformed into the modifier mesh coordinate space, with inverse rotation applied to the modifier.
        auto qs = pts *
            (instance_rotation_trafo *
            Eigen::Scaling(instance_transformation.get_scaling_factor().cwiseProduct(instance_transformation.get_mirror())) *
            volume_rotation_trafo).inverse().transpose();
        // Fill in scaling based on least squares fitting of the bounding box corners.
        Vec3d scale;
        for (int i = 0; i < 3; ++i)
            scale(i) = pts.col(i).dot(qs.col(i)) / pts.col(i).dot(pts.col(i));
        out.set_rotation(Geometry::extract_euler_angles(volume_rotation_trafo));
        out.set_scaling_factor(Vec3d(std::abs(scale(0)), std::abs(scale(1)), std::abs(scale(2))));
        out.set_mirror(Vec3d(scale(0) > 0 ? 1. : -1, scale(1) > 0 ? 1. : -1, scale(2) > 0 ? 1. : -1));
    }
    else
    {
        // General anisotropic scaling, general rotation.
        // Keep the modifier mesh in the instance coordinate system, so the modifier mesh will not be aligned with the world.
        // Scale it to get the required size.
        out.set_scaling_factor(instance_transformation.get_scaling_factor().cwiseInverse());
    }
    return out;
}
References Slic3r::Geometry::extract_euler_angles(), get_matrix(), get_mirror(), get_rotation(), get_scaling_factor(), inverse(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::Geometry::is_rotation_ninety_degrees(), is_scaling_uniform(), Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, out, scale(), and Eigen::Scaling().
Referenced by Slic3r::GUI::ObjectList::load_generic_subobject(), and Slic3r::GUI::ObjectList::load_modifier().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
operator==
bool operator== (Transformation const & l, Transformation const & r) friend
{
        return l.m_offset == r.m_offset && l.m_rotation == r.m_rotation && l.m_scaling_factor == r.m_scaling_factor && l.m_mirror == r.m_mirror;
    }
Member Data Documentation
m_dirty
bool Slic3r::Geometry::Transformation::m_dirty mutable private
Referenced by get_matrix(), is_dirty(), reset(), set_mirror(), set_offset(), set_rotation(), and set_scaling_factor().
m_flags
Flags Slic3r::Geometry::Transformation::m_flags mutable private
Referenced by get_matrix().
m_matrix
Transform3d Slic3r::Geometry::Transformation::m_matrix mutable private
Referenced by get_matrix(), reset(), and set_from_transform().
m_mirror
Vec3d Slic3r::Geometry::Transformation::m_mirror private
Referenced by get_matrix(), get_mirror(), get_mirror(), is_left_handed(), reset(), serialize(), and set_mirror().
m_offset
Vec3d Slic3r::Geometry::Transformation::m_offset private
Referenced by get_matrix(), get_offset(), get_offset(), reset(), serialize(), and set_offset().
m_rotation
Vec3d Slic3r::Geometry::Transformation::m_rotation private
Referenced by get_matrix(), get_rotation(), get_rotation(), reset(), serialize(), and set_rotation().
m_scaling_factor
Vec3d Slic3r::Geometry::Transformation::m_scaling_factor private
Referenced by get_matrix(), get_scaling_factor(), get_scaling_factor(), is_scaling_uniform(), reset(), serialize(), and set_scaling_factor().
The documentation for this class was generated from the following files:
src/libslic3r/Geometry.hpp
src/libslic3r/Geometry.cpp