OrcaSlicer: Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > > Class Template Reference
Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > > Class Template Reference
#include <src/libslic3r/Optimize/NLoptOptimizer.hpp>
Public Member Functions
template<class Func , size_t N>
Result< N > optimize (Func &&func, const Input< N > &initvals, const Bounds< N > &bounds)
NLoptOpt (StopCriteria stopcr={})
void set_criteria (const StopCriteria &cr)
const StopCriteria & get_criteria () const noexcept
void set_dir (OptDir dir) noexcept
void seed (long s)
Protected Types
template<class Fn >
using TOptData = std::tuple< std::remove_reference_t< Fn > *, NLoptOpt *, nlopt_opt >
Protected Member Functions
template<size_t N>
void set_up (NLopt &nl, const Bounds< N > &bounds)
template<class Fn , size_t N>
Result< N > optimize (NLopt &nl, Fn &&fn, const Input< N > &initvals)
Static Protected Member Functions
template<class Fn , size_t N>
static double optfunc (unsigned n, const double *params, double *gradient, void *data)
Protected Attributes
StopCriteria m_stopcr
OptDir m_dir
Detailed Description
template<nlopt_algorithm alg>
class Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >
Member Typedef Documentation
TOptData
template<nlopt_algorithm alg> template<class Fn > using Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::TOptData = std::tuple<std::remove_reference_t<Fn>*, NLoptOpt*, nlopt_opt> protected
Constructor & Destructor Documentation
NLoptOpt()
template<nlopt_algorithm alg> Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::NLoptOpt (StopCriteria stopcr = {}) inline explicit
{}) : m_stopcr(stopcr) {}
Member Function Documentation
get_criteria()
template<nlopt_algorithm alg> const StopCriteria & Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::get_criteria () const inline noexcept
{ return m_stopcr; }
optfunc()
template<nlopt_algorithm alg> template<class Fn , size_t N> static double Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::optfunc (unsigned n, const double * params, double * gradient, void * data) inline static protected
    {
        assert(n >= N);
        auto tdata = static_cast<TOptData<Fn>*>(data);
        if (std::get<1>(*tdata)->m_stopcr.stop_condition())
            nlopt_force_stop(std::get<2>(*tdata));
        auto fnptr  = std::get<0>(*tdata);
        auto funval = to_arr<N>(params);
        double scoreval = 0.;
        using RetT = decltype((*fnptr)(funval));
        if constexpr (std::is_convertible_v<RetT, ScoreGradient<N>>) {
            ScoreGradient<N> score = (*fnptr)(funval);
            for (size_t i = 0; i < n; ++i) gradient[i] = (*score.gradient)[i];
            scoreval = score.score;
        } else {
            scoreval = (*fnptr)(funval);
        }
        return scoreval;
    }
References Slic3r::opt::ScoreGradient< N >::gradient, n, and Slic3r::opt::ScoreGradient< N >::score.
optimize() [1/2]
template<nlopt_algorithm alg> template<class Func , size_t N> Result< N > Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::optimize (Func && func, const Input< N > & initvals, const Bounds< N > & bounds) inline
    {
        NLopt nl{alg, N};
        set_up(nl, bounds);
        return optimize(nl, std::forward<Func>(func), initvals);
    }
References Slic3r::opt::bounds().
optimize() [2/2]
template<nlopt_algorithm alg> template<class Fn , size_t N> Result< N > Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::optimize (NLopt & nl, Fn && fn, const Input< N > & initvals) inline protected
    {
        Result<N> r;
        TOptData<Fn> data = std::make_tuple(&fn, this, nl.ptr);
        switch(m_dir) {
        case OptDir::MIN:
            nlopt_set_min_objective(nl.ptr, optfunc<Fn, N>, &data); break;
        case OptDir::MAX:
            nlopt_set_max_objective(nl.ptr, optfunc<Fn, N>, &data); break;
        }
        r.optimum = initvals;
        r.resultcode = nlopt_optimize(nl.ptr, r.optimum.data(), &r.score);
        return r;
    }
References Slic3r::opt::detail::MAX, Slic3r::opt::detail::MIN, Slic3r::opt::Result< N >::optimum, Slic3r::opt::detail::NLopt::ptr, Slic3r::opt::Result< N >::resultcode, and Slic3r::opt::Result< N >::score.
seed()
template<nlopt_algorithm alg> void Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::seed (long s) inline
{ nlopt_srand(s); }
set_criteria()
template<nlopt_algorithm alg> void Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::set_criteria (const StopCriteria & cr) inline
{ m_stopcr = cr; }
set_dir()
template<nlopt_algorithm alg> void Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::set_dir (OptDir dir) inline noexcept
{ m_dir = dir; }
set_up()
template<nlopt_algorithm alg> template<size_t N> void Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::set_up (NLopt & nl, const Bounds< N > & bounds) inline protected
    {
        std::array<double, N> lb, ub;
        for (size_t i = 0; i < N; ++i) {
            lb[i] = bounds[i].min();
            ub[i] = bounds[i].max();
        }
        nlopt_set_lower_bounds(nl.ptr, lb.data());
        nlopt_set_upper_bounds(nl.ptr, ub.data());
        double abs_diff = m_stopcr.abs_score_diff();
        double rel_diff = m_stopcr.rel_score_diff();
        double stopval = m_stopcr.stop_score();
        if(!std::isnan(abs_diff)) nlopt_set_ftol_abs(nl.ptr, abs_diff);
        if(!std::isnan(rel_diff)) nlopt_set_ftol_rel(nl.ptr, rel_diff);
        if(!std::isnan(stopval))  nlopt_set_stopval(nl.ptr, stopval);
        if(m_stopcr.max_iterations() > 0)
            nlopt_set_maxeval(nl.ptr, m_stopcr.max_iterations());
    }
References Slic3r::opt::StopCriteria::abs_score_diff(), Slic3r::opt::bounds(), Slic3r::opt::StopCriteria::max_iterations(), Slic3r::opt::detail::NLopt::ptr, Slic3r::opt::StopCriteria::rel_score_diff(), and Slic3r::opt::StopCriteria::stop_score().
Member Data Documentation
m_dir
template<nlopt_algorithm alg> OptDir Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::m_dir protected
m_stopcr
template<nlopt_algorithm alg> StopCriteria Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::m_stopcr protected
The documentation for this class was generated from the following file:
src/libslic3r/Optimize/NLoptOptimizer.hpp