OrcaSlicer: Slic3r::GUI::GridCellFilamentsEditor Class Reference
Slic3r::GUI::GridCellFilamentsEditor Class Reference
#include <src/slic3r/GUI/GUI_ObjectTable.hpp>
Public Member Functions
GridCellFilamentsEditor (size_t count=0, const wxString choices[]=NULL, bool allowOthers=false, std::vector< wxBitmap * > *bitmaps=NULL)
GridCellFilamentsEditor (const wxArrayString &choices, bool allowOthers=false, std::vector< wxBitmap * > *bitmaps=NULL)
virtual void Create (wxWindow *parent, wxWindowID id, wxEvtHandler *evtHandler) wxOVERRIDE
virtual void SetSize (const wxRect &rect) wxOVERRIDE
virtual wxGridCellEditor * Clone () const wxOVERRIDE
virtual void BeginEdit (int row, int col, wxGrid *grid) wxOVERRIDE
virtual bool EndEdit (int row, int col, const wxGrid *grid, const wxString &oldval, wxString *newval) wxOVERRIDE
virtual wxGridActivationResult TryActivate (int row, int col, wxGrid *grid, const wxGridActivationSource &actSource) wxOVERRIDE
virtual void DoActivate (int row, int col, wxGrid *grid) wxOVERRIDE
Protected Member Functions
::ComboBox * Combo () const
void OnComboCloseUp (wxCommandEvent &evt)
wxDECLARE_NO_COPY_CLASS (GridCellFilamentsEditor)
Protected Attributes
std::vector< wxBitmap * > * m_icons
Private Attributes
int m_cached_value {-1}
Detailed Description
Constructor & Destructor Documentation
GridCellFilamentsEditor() [1/2]
Slic3r::GUI::GridCellFilamentsEditor::GridCellFilamentsEditor (size_t count = 0, const wxString choices[] = NULL, bool allowOthers = false, std::vector< wxBitmap * > * bitmaps = NULL)
    : wxGridCellChoiceEditor(count, choices, allowOthers), m_icons(bitmaps)
{
}
GridCellFilamentsEditor() [2/2]
Slic3r::GUI::GridCellFilamentsEditor::GridCellFilamentsEditor (const wxArrayString & choices, bool allowOthers = false, std::vector< wxBitmap * > * bitmaps = NULL)
    : wxGridCellChoiceEditor(choices, allowOthers), m_icons(bitmaps)
{
}
Member Function Documentation
BeginEdit()
void Slic3r::GUI::GridCellFilamentsEditor::BeginEdit (int row, int col, wxGrid * grid) virtual
{
    wxGridCellEditorEvtHandler* evtHandler = NULL;
    if (m_control)
    {
        // This event handler is needed to properly dismiss the editor when the popup is closed
        m_control->Bind(wxEVT_COMBOBOX_CLOSEUP, &GridCellFilamentsEditor::OnComboCloseUp, this);
        evtHandler = static_cast<wxGridCellEditorEvtHandler*>(m_control->GetEventHandler());
    }
    // Don't immediately end if we get a kill focus event within BeginEdit
    if (evtHandler)
        evtHandler->SetInSetFocus(true);
    //m_value = grid->GetTable()->GetValue(row, col);
    ObjectGridTable *table = dynamic_cast<ObjectGridTable *>(grid->GetTable());
    ObjectGridTable::ObjectGridCol* grid_col = table->get_grid_col(col);
    ObjectGridTable::ObjectGridRow* grid_row = table->get_grid_row(row - 1);
    ConfigOption& option = (*grid_row)[(ObjectGridTable::GridColType)col];
    ConfigOptionInt& option_value = dynamic_cast<ConfigOptionInt&>(option);
    if ((option_value.value - 1) < grid_col->choice_count) {
       //return grid_col->choices[(option_value.value > 0)?option_value.value - 1: 0];
        int index = (option_value.value > 0) ? option_value.value - 1 : 0;
        m_value = grid_col->choices[index];
       //return grid_col->choices[index];
    }
    //m_value = grid->GetTable()->GetValue(row, col);
    //Reset(); // this updates combo box to correspond to m_value
    int pos = Combo()->FindString(m_value);
    if (pos == wxNOT_FOUND) pos = 0;
    Combo()->SetSelection(pos);
    Combo()->SetFocus();
#ifdef __WXOSX_COCOA__
    // This is a work around for the combobox being simply dismissed when a
    // choice is made in it under OS X. The bug is almost certainly due to a
    // problem in focus events generation logic but it's not obvious to fix and
    // for now this at least allows to use wxGrid.
    //Combo()->Popup();
#endif
    if (evtHandler)
    {
        // When dropping down the menu, a kill focus event
        // happens after this point, so we can't reset the flag yet.
#if !defined(__WXGTK20__)
        //evtHandler->SetInSetFocus(false);
#endif
    }
}
References Slic3r::GUI::ObjectGridTable::ObjectGridCol::choice_count, Slic3r::GUI::ObjectGridTable::ObjectGridCol::choices, col(), Combo(), Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), Slic3r::grid(), NULL, OnComboCloseUp(), row(), ComboBox::SetSelection(), and Slic3r::ConfigOptionSingle< T >::value.
Clone()
wxGridCellEditor * Slic3r::GUI::GridCellFilamentsEditor::Clone () const virtual
{
    GridCellFilamentsEditor *editor = new GridCellFilamentsEditor;
    editor->m_allowOthers = m_allowOthers;
    editor->m_choices = m_choices;
    editor->m_icons = m_icons;
    return editor;
}
References m_icons.
Combo()
::ComboBox * Slic3r::GUI::GridCellFilamentsEditor::Combo () const inline protected
{ return (::ComboBox *)m_control; }
Referenced by BeginEdit(), and EndEdit().
Create()
void Slic3r::GUI::GridCellFilamentsEditor::Create (wxWindow * parent, wxWindowID id, wxEvtHandler * evtHandler) virtual
{
    int style = wxTE_PROCESS_ENTER |
                wxTE_PROCESS_TAB |
                wxBORDER_NONE;
    if ( !m_allowOthers )
        style |= wxCB_READONLY;
    ::ComboBox *bitmap_combo = new ComboBox(parent, id, wxEmptyString,
                               wxDefaultPosition, wxSize(((*m_icons)[0])->GetWidth() + 10, -1), 0, nullptr, CB_NO_DROP_ICON | CB_NO_TEXT | wxCB_READONLY);
    if (m_icons) {
        int array_count = m_choices.GetCount();
        int icon_count = m_icons->size();
        for (int i = 0; i < array_count; i++)
        {
            wxBitmap* bitmap = (i < icon_count) ? (*m_icons)[i] : (*m_icons)[0];
            bitmap_combo->Append(m_choices[i], *bitmap);
        }
    }
    m_control = bitmap_combo;
    wxGridCellEditor::Create(parent, id, evtHandler);
    /* bitmap_combo->GetDropDown().Bind(wxEVT_COMBOBOX, [this](wxCommandEvent& e) {
         const wxString value = Combo()->GetValue();
         if (value == m_value)
             return false;
         m_value = value;
         return true;
         e.Skip();
     });*/
}
References ComboBox::Append(), CB_NO_DROP_ICON, CB_NO_TEXT, m_icons, and style.
DoActivate()
void Slic3r::GUI::GridCellFilamentsEditor::DoActivate (int row, int col, wxGrid * grid) virtual
{
    if (m_cached_value != -1) {
        ObjectGridTable *table = dynamic_cast<ObjectGridTable *>(grid->GetTable());
        ObjectGridTable::ObjectGridCol* grid_col = table->get_grid_col(col);
        ObjectGridTable::ObjectGridRow* grid_row = table->get_grid_row(row - 1);
        if (m_cached_value <= grid_col->choice_count) {
            wxString choice = grid_col->choices[m_cached_value-1];
            table->SetValue(row, col, choice);
            //Combo()->SetValue(choice);
        }
        m_cached_value = -1;
    }
}
References Slic3r::GUI::ObjectGridTable::ObjectGridCol::choices, col(), Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), Slic3r::grid(), m_cached_value, row(), and Slic3r::GUI::ObjectGridTable::SetValue().
EndEdit()
bool Slic3r::GUI::GridCellFilamentsEditor::EndEdit (int row, int col, const wxGrid * grid, const wxString & oldval, wxString * newval) virtual
{
    const wxString value = Combo()->GetValue();
    if ( value == m_value )
        return false;
    m_value = value;
    if ( newval )
        *newval = value;
    return true;
}
References Combo(), and ComboBox::GetValue().
OnComboCloseUp()
void Slic3r::GUI::GridCellFilamentsEditor::OnComboCloseUp (wxCommandEvent & evt) protected
{
    wxGridCellChoiceEditor::OnComboCloseUp(evt);
}
Referenced by BeginEdit().
SetSize()
void Slic3r::GUI::GridCellFilamentsEditor::SetSize (const wxRect & rect) virtual
{
    wxGridCellChoiceEditor::SetSize(rect);
    /*wxASSERT_MSG(m_control,
                 wxT("The wxGridCellChoiceEditor must be created first!"));
    // Use normal wxChoice size, except for extending it to fill the cell
    // width: we can't be smaller because this could make the control unusable
    // and we don't want to be taller because this looks unusual and weird.
    wxSize size = m_control->GetBestSize();
    if ( size.x < rect.width )
        size.x = rect.width;
    DoPositionEditor(size, rect);*/
}
TryActivate()
wxGridActivationResult Slic3r::GUI::GridCellFilamentsEditor::TryActivate (int row, int col, wxGrid * grid, const wxGridActivationSource & actSource) virtual
{
    ObjectGridTable *table = dynamic_cast<ObjectGridTable *>(grid->GetTable());
    ObjectGridTable::ObjectGridCol* grid_col = table->get_grid_col(col);
    ObjectGridTable::ObjectGridRow* grid_row = table->get_grid_row(row - 1);
    if ( actSource.GetOrigin() == wxGridActivationSource::Key ) {
        const wxKeyEvent& key_event = actSource.GetKeyEvent();
        int keyCode = key_event.GetKeyCode();
        wxString choice;
        int digital_value = keyCode - '0';
        if ((digital_value >= 1) && (digital_value <= 9))
            m_cached_value = digital_value;
        else
            m_cached_value = -1;
        if (m_cached_value != -1) {
            if (m_cached_value <= grid_col->choice_count) {
                choice = grid_col->choices[m_cached_value-1];
                return wxGridActivationResult::DoChange(choice);
            }
            else {
                return wxGridActivationResult::DoNothing();
            }
        }
        else
            return wxGridActivationResult::DoNothing();
    }
    else {
        m_cached_value = -1;
        return wxGridActivationResult::DoEdit();
    }
}
References Slic3r::GUI::ObjectGridTable::ObjectGridCol::choices, col(), Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), Slic3r::grid(), m_cached_value, and row().
wxDECLARE_NO_COPY_CLASS()
Slic3r::GUI::GridCellFilamentsEditor::wxDECLARE_NO_COPY_CLASS (GridCellFilamentsEditor) protected
Member Data Documentation
m_cached_value
int Slic3r::GUI::GridCellFilamentsEditor::m_cached_value {-1} private
Referenced by DoActivate(), and TryActivate().
m_icons
std::vector<wxBitmap*>* Slic3r::GUI::GridCellFilamentsEditor::m_icons protected
Referenced by Clone(), and Create().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTable.hpp
src/slic3r/GUI/GUI_ObjectTable.cpp