OrcaSlicer: Slic3r::GUI::Selection Class Reference
Slic3r::GUI::Selection Class Reference
#include <src/slic3r/GUI/Selection.hpp>
Classes
struct Cache
class Clipboard
struct VolumeCache
Public Types
enum EMode : unsigned char { Volume , Instance }
enum EType : unsigned char {
Invalid , Empty , WipeTower , SingleModifier ,
MultipleModifier , SingleVolume , MultipleVolume , SingleFullObject ,
MultipleFullObject , SingleFullInstance , MultipleFullInstance , Mixed
}
enum SyncRotationType { SYNC_ROTATION_NONE = 0 , SYNC_ROTATION_GENERAL = 1 }
typedef std::set< unsigned int > IndicesList
typedef std::map< unsigned int, VolumeCache > VolumesCache
typedef std::set< int > InstanceIdxsList
typedef std::map< int, InstanceIdxsList > ObjectIdxsToInstanceIdxsMap
Public Member Functions
Selection ()
void set_volumes (GLVolumePtrs *volumes)
bool init ()
bool is_enabled () const
void set_enabled (bool enable)
Model * get_model () const
void set_model (Model *model)
EMode get_mode () const
void set_mode (EMode mode)
void add (unsigned int volume_idx, bool as_single_selection=true, bool check_for_already_contained=false)
void remove (unsigned int volume_idx)
void add_object (unsigned int object_idx, bool as_single_selection=true)
void remove_object (unsigned int object_idx)
void add_instance (unsigned int object_idx, unsigned int instance_idx, bool as_single_selection=true)
void remove_instance (unsigned int object_idx, unsigned int instance_idx)
void add_volume (unsigned int object_idx, unsigned int volume_idx, int instance_idx, bool as_single_selection=true)
void remove_volume (unsigned int object_idx, unsigned int volume_idx)
void add_volumes (EMode mode, const std::vector< unsigned int > &volume_idxs, bool as_single_selection=true)
void remove_volumes (EMode mode, const std::vector< unsigned int > &volume_idxs)
void add_curr_plate ()
void remove_curr_plate ()
void clone (int numbers=1)
void center ()
void set_printable (bool printable)
void add_all ()
void remove_all ()
void set_deserialized (EMode mode, const std::vector< std::pair< size_t, size_t > > &volumes_and_instances)
void instances_changed (const std::vector< size_t > &instance_ids_selected)
void volumes_changed (const std::vector< size_t > &map_volume_old_to_new)
void clear ()
bool is_empty () const
bool is_wipe_tower () const
bool is_any_modifier () const
bool is_single_modifier () const
bool is_multiple_modifier () const
bool is_single_full_instance () const
bool is_multiple_full_instance () const
bool is_single_full_object () const
bool is_multiple_full_object () const
bool is_single_volume () const
bool is_multiple_volume () const
bool is_any_volume () const
bool is_mixed () const
bool is_from_single_instance () const
bool is_from_single_object () const
bool is_sla_compliant () const
bool is_instance_mode () const
bool contains_volume (unsigned int volume_idx) const
bool contains_all_volumes (const std::vector< unsigned int > &volume_idxs) const
bool contains_any_volume (const std::vector< unsigned int > &volume_idxs) const
bool matches (const std::vector< unsigned int > &volume_idxs) const
bool requires_uniform_scale () const
int get_object_idx () const
int get_instance_idx () const
const InstanceIdxsList & get_instance_idxs () const
const IndicesList & get_volume_idxs () const
const GLVolume * get_volume (unsigned int volume_idx) const
const ObjectIdxsToInstanceIdxsMap & get_content () const
unsigned int volumes_count () const
const BoundingBoxf3 & get_bounding_box () const
const BoundingBoxf3 & get_unscaled_instance_bounding_box () const
const BoundingBoxf3 & get_scaled_instance_bounding_box () const
void start_dragging ()
void stop_dragging ()
bool is_dragging () const
void translate (const Vec3d &displacement, bool local=false)
void move_to_center (const Vec3d &displacement, bool local=false)
void rotate (const Vec3d &rotation, TransformationType transformation_type)
void flattening_rotate (const Vec3d &normal)
void scale (const Vec3d &scale, TransformationType transformation_type)
void scale_to_fit_print_volume (const DynamicPrintConfig &config)
void mirror (Axis axis)
void translate (unsigned int object_idx, const Vec3d &displacement)
void translate (unsigned int object_idx, unsigned int instance_idx, const Vec3d &displacement)
void notify_instance_update (int object_idx, int instance_idx)
void set_volume_selection_mode (EMode mode)
void lock_volume_selection_mode ()
void unlock_volume_selection_mode ()
void erase ()
void render (float scale_factor=1.0) const
void render_sidebar_hints (const std::string &sidebar_field, bool uniform_scale) const
bool requires_local_axes () const
void render_bounding_box (const BoundingBoxf3 &box, float *color, float scale)
void cut_to_clipboard ()
void copy_to_clipboard ()
void paste_from_clipboard ()
std::set< std::pair< int, int > > get_selected_object_instances ()
const Clipboard & get_clipboard () const
void fill_color (int extruder_id)
std::vector< unsigned int > get_volume_idxs_from_object (unsigned int object_idx) const
std::vector< unsigned int > get_volume_idxs_from_instance (unsigned int object_idx, unsigned int instance_idx) const
std::vector< unsigned int > get_volume_idxs_from_volume (unsigned int object_idx, unsigned int instance_idx, unsigned int volume_idx) const
std::vector< unsigned int > get_missing_volume_idxs_from (const std::vector< unsigned int > &volume_idxs) const
std::vector< unsigned int > get_unselected_volume_idxs_from (const std::vector< unsigned int > &volume_idxs) const
void synchronize_unselected_instances (SyncRotationType sync_rotation_type)
void synchronize_unselected_volumes ()
Private Member Functions
void update_valid ()
void update_type ()
void set_caches ()
void do_add_volume (unsigned int volume_idx)
void do_add_volumes (const std::vector< unsigned int > &volume_idxs)
void do_remove_volume (unsigned int volume_idx)
void do_remove_instance (unsigned int object_idx, unsigned int instance_idx)
void do_remove_object (unsigned int object_idx)
void set_bounding_boxes_dirty ()
void render_selected_volumes () const
void render_synchronized_volumes () const
void render_bounding_box (const BoundingBoxf3 &box, float *color) const
void render_sidebar_position_hints (const std::string &sidebar_field) const
void render_sidebar_rotation_hints (const std::string &sidebar_field) const
void render_sidebar_scale_hints (const std::string &sidebar_field, bool gizmo_uniform_scale) const
void render_sidebar_layers_hints (const std::string &sidebar_field) const
void ensure_on_bed ()
void ensure_not_below_bed ()
bool is_from_fully_selected_instance (unsigned int volume_idx) const
void paste_volumes_from_clipboard ()
void paste_objects_from_clipboard ()
Private Attributes
GLVolumePtrs * m_volumes
Model * m_model
bool m_enabled
bool m_valid
EMode m_mode
EType m_type
IndicesList m_list
Cache m_cache
Clipboard m_clipboard
std::optional< BoundingBoxf3 > m_bounding_box
std::optional< BoundingBoxf3 > m_unscaled_instance_bounding_box
std::optional< BoundingBoxf3 > m_scaled_instance_bounding_box
GLModel m_arrow
GLModel m_curved_arrow
float m_scale_factor
bool m_dragging
EMode m_volume_selection_mode { Instance }
bool m_volume_selection_locked { false }
Detailed Description
Class Documentation
Slic3r::GUI::Selection::Cache
struct Slic3r::GUI::Selection::Cache
Class Members
ObjectIdxsToInstanceIdxsMap content
Vec3d dragging_center
vector< unsigned int > sinking_volumes
VolumesCache volumes_data
Member Typedef Documentation
IndicesList
typedef std::set<unsigned int> Slic3r::GUI::Selection::IndicesList
InstanceIdxsList
typedef std::set<int> Slic3r::GUI::Selection::InstanceIdxsList
ObjectIdxsToInstanceIdxsMap
typedef std::map<int, InstanceIdxsList> Slic3r::GUI::Selection::ObjectIdxsToInstanceIdxsMap
VolumesCache
typedef std::map<unsigned int, VolumeCache> Slic3r::GUI::Selection::VolumesCache
Member Enumeration Documentation
EMode
enum Slic3r::GUI::Selection::EMode : unsigned char
Enumerator
Volume
Instance
    {
        Volume,
        Instance
    };
EType
enum Slic3r::GUI::Selection::EType : unsigned char
Enumerator
Invalid
Empty
WipeTower
SingleModifier
MultipleModifier
SingleVolume
MultipleVolume
SingleFullObject
MultipleFullObject
SingleFullInstance
MultipleFullInstance
Mixed
    {
        Invalid,
        Empty,
        WipeTower,
        SingleModifier,
        MultipleModifier,
        SingleVolume,
        MultipleVolume,
        SingleFullObject,
        MultipleFullObject,
        SingleFullInstance,
        MultipleFullInstance,
        Mixed
    };
SyncRotationType
enum Slic3r::GUI::Selection::SyncRotationType
Enumerator
SYNC_ROTATION_NONE
SYNC_ROTATION_GENERAL
{
        // Do not synchronize rotation. Either not rotating at all, or rotating by world Z axis.
        SYNC_ROTATION_NONE = 0,
        // Synchronize after rotation by an axis not parallel with Z.
        SYNC_ROTATION_GENERAL = 1,
    };
Constructor & Destructor Documentation
Selection()
Slic3r::GUI::Selection::Selection ()
    : m_volumes(nullptr)
    , m_model(nullptr)
    , m_enabled(false)
    , m_mode(Instance)
    , m_type(Empty)
    , m_valid(false)
    , m_scale_factor(1.0f)
    , m_dragging(false)
{
    this->set_bounding_boxes_dirty();
}
References set_bounding_boxes_dirty().
Member Function Documentation
add()
void Slic3r::GUI::Selection::add (unsigned int volume_idx, bool as_single_selection = true, bool check_for_already_contained = false)
{
    if (!m_valid || (unsigned int)m_volumes->size() <= volume_idx)
        return;
    const GLVolume* volume = (*m_volumes)[volume_idx];
    //BBS: multiple wipe tower case should be considered
    // wipe tower is already selected
    //if (is_wipe_tower() && volume->is_wipe_tower)
    //    return;
    if (!m_list.empty() && !is_wipe_tower() && volume->is_wipe_tower && !as_single_selection)
        return;
    bool keep_instance_mode = (m_mode == Instance) && !as_single_selection;
    bool already_contained = check_for_already_contained && contains_volume(volume_idx);
    // resets the current list if needed
    bool needs_reset = as_single_selection && !already_contained;
    needs_reset |= volume->is_wipe_tower;
    needs_reset |= is_wipe_tower() && !volume->is_wipe_tower;
    needs_reset |= as_single_selection && !is_any_modifier() && volume->is_modifier;
    needs_reset |= is_any_modifier() && !volume->is_modifier;
    if (!needs_reset && (is_any_modifier() || is_any_volume())) {
        int obj_index = volume->object_idx();
        int inst_index = volume->instance_idx();
        int first = *(m_list.begin());
        if (first < m_volumes->size()) {
            const GLVolume* volume = (*m_volumes)[first];
            if ((volume->object_idx() != obj_index) || (volume->instance_idx() != inst_index))
                needs_reset = true;
        }
    }
    if (!already_contained || needs_reset) {
        wxGetApp().plater()->take_snapshot(std::string("Selection-Add!"), UndoRedo::SnapshotType::Selection);
        if (needs_reset)
            clear();
        // BBS
        if (!keep_instance_mode)
            m_mode = volume->is_modifier ? Volume : m_volume_selection_mode;
    }
    else
      // keep current mode
      return;
    switch (m_mode)
    {
    case Volume:
    {
        if (volume->volume_idx() >= 0 && (is_empty() || volume->instance_idx() == get_instance_idx()))
            do_add_volume(volume_idx);
        break;
    }
    case Instance:
    {
        Plater::SuppressSnapshots suppress(wxGetApp().plater());
        add_instance(volume->object_idx(), volume->instance_idx(), as_single_selection);
        break;
    }
    }
    update_type();
    this->set_bounding_boxes_dirty();
}
References add_instance(), clear(), contains_volume(), do_add_volume(), get_instance_idx(), Instance, is_any_modifier(), is_any_volume(), is_empty(), is_wipe_tower(), m_list, m_mode, m_valid, m_volume_selection_mode, m_volumes, Slic3r::GUI::plater(), Slic3r::UndoRedo::Selection, set_bounding_boxes_dirty(), size, update_type(), and Volume.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), and Slic3r::GUI::Plater::priv::reload_all_from_disk().
add_all()
void Slic3r::GUI::Selection::add_all ()
{
    if (!m_valid)
        return;
    unsigned int count = 0;
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i) {
        if (!(*m_volumes)[i]->is_wipe_tower)
            ++count;
    }
    if ((unsigned int)m_list.size() == count)
        return;
    wxGetApp().plater()->take_snapshot(std::string("Selection-Add All!"), UndoRedo::SnapshotType::Selection);
    m_mode = Instance;
    clear();
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i) {
        if (!(*m_volumes)[i]->is_wipe_tower)
            do_add_volume(i);
    }
    update_type();
    this->set_bounding_boxes_dirty();
}
References clear(), count, do_add_volume(), Instance, int, m_list, m_mode, m_valid, m_volumes, Slic3r::UndoRedo::Selection, set_bounding_boxes_dirty(), and update_type().
Referenced by Slic3r::GUI::GLCanvas3D::select_all().
add_curr_plate()
void Slic3r::GUI::Selection::add_curr_plate ()
{
    if (!m_valid)
        return;
    wxGetApp().plater()->take_snapshot(std::string("Selection-Add Curr Plate All!"));
    m_mode = Instance;
    clear();
    PartPlate* plate = wxGetApp().plater()->get_partplate_list().get_curr_plate();
    for (int obj_idx = 0; obj_idx < m_model->objects.size(); obj_idx++) {
        if (plate && plate->contain_instance_totally(obj_idx, 0)) {
            std::vector<unsigned int> volume_idxs = get_volume_idxs_from_object(obj_idx);
            do_add_volumes(volume_idxs);
        }
    }
    update_type();
    this->set_bounding_boxes_dirty();
}
References clear(), Slic3r::GUI::PartPlate::contain_instance_totally(), do_add_volumes(), get_volume_idxs_from_object(), Instance, m_mode, m_model, m_valid, Slic3r::Model::objects, set_bounding_boxes_dirty(), and update_type().
Referenced by Slic3r::GUI::GLCanvas3D::select_curr_plate_all().
add_instance()
void Slic3r::GUI::Selection::add_instance (unsigned int object_idx, unsigned int instance_idx, bool as_single_selection = true)
{
    if (!m_valid)
        return;
    const std::vector<unsigned int> volume_idxs = get_volume_idxs_from_instance(object_idx, instance_idx);
    if ((!as_single_selection && contains_all_volumes(volume_idxs)) ||
        (as_single_selection && matches(volume_idxs)))
        return;
    wxGetApp().plater()->take_snapshot(std::string("Selection-Add Instance"), UndoRedo::SnapshotType::Selection);
    // resets the current list if needed
    if (as_single_selection)
        clear();
    m_mode = Instance;
    do_add_volumes(volume_idxs);
    update_type();
    this->set_bounding_boxes_dirty();
}
References clear(), contains_all_volumes(), do_add_volumes(), get_volume_idxs_from_instance(), Instance, m_mode, m_valid, matches(), Slic3r::UndoRedo::Selection, set_bounding_boxes_dirty(), and update_type().
Referenced by add().
add_object()
void Slic3r::GUI::Selection::add_object (unsigned int object_idx, bool as_single_selection = true)
{
    if (!m_valid)
        return;
    std::vector<unsigned int> volume_idxs = get_volume_idxs_from_object(object_idx);
    if ((!as_single_selection && contains_all_volumes(volume_idxs)) ||
        (as_single_selection && matches(volume_idxs)))
        return;
    wxGetApp().plater()->take_snapshot(std::string("Selection-Add Object"), UndoRedo::SnapshotType::Selection);
    // resets the current list if needed
    if (as_single_selection)
        clear();
    m_mode = Instance;
    do_add_volumes(volume_idxs);
    update_type();
    this->set_bounding_boxes_dirty();
}
References clear(), contains_all_volumes(), do_add_volumes(), get_volume_idxs_from_object(), Instance, m_mode, m_valid, matches(), Slic3r::UndoRedo::Selection, set_bounding_boxes_dirty(), and update_type().
Referenced by Slic3r::GUI::Plater::_calib_pa_select_added_objects(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), Slic3r::GUI::Plater::convert_unit(), Slic3r::GUI::Plater::cut(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::merge(), Slic3r::GUI::Plater::segment(), and Slic3r::GUI::Plater::priv::split_object().
add_volume()
void Slic3r::GUI::Selection::add_volume (unsigned int object_idx, unsigned int volume_idx, int instance_idx, bool as_single_selection = true)
{
    if (!m_valid)
        return;
    std::vector<unsigned int> volume_idxs = get_volume_idxs_from_volume(object_idx, instance_idx, volume_idx);
    if ((!as_single_selection && contains_all_volumes(volume_idxs)) ||
        (as_single_selection && matches(volume_idxs)))
        return;
    // resets the current list if needed
    if (as_single_selection)
        clear();
    m_mode = Volume;
    do_add_volumes(volume_idxs);
    update_type();
    this->set_bounding_boxes_dirty();
}
References clear(), contains_all_volumes(), do_add_volumes(), get_volume_idxs_from_volume(), m_mode, m_valid, matches(), set_bounding_boxes_dirty(), update_type(), and Volume.
Referenced by Slic3r::GUI::Plater::convert_unit().
add_volumes()
void Slic3r::GUI::Selection::add_volumes (EMode mode, const std::vector< unsigned int > & volume_idxs, bool as_single_selection = true)
{
    if (!m_valid)
        return;
    if ((!as_single_selection && contains_all_volumes(volume_idxs)) ||
        (as_single_selection && matches(volume_idxs)))
        return;
    // resets the current list if needed
    if (as_single_selection)
        clear();
    m_mode = mode;
    for (unsigned int i : volume_idxs) {
        if (i < (unsigned int)m_volumes->size())
            do_add_volume(i);
    }
    update_type();
    this->set_bounding_boxes_dirty();
}
References clear(), contains_all_volumes(), do_add_volume(), m_mode, m_valid, m_volumes, matches(), set_bounding_boxes_dirty(), and update_type().
Referenced by Slic3r::GUI::ObjectList::update_selections_on_canvas().
center()
void Slic3r::GUI::Selection::center ()
{
    PartPlate* plate = wxGetApp().plater()->get_partplate_list().get_selected_plate();
    // calc distance
    Vec3d src_pos = this->get_bounding_box().center();
    Vec3d tar_pos = plate->get_center_origin();
    Vec3d distance = Vec3d(tar_pos.x() - src_pos.x(), tar_pos.y() - src_pos.y(), 0);
    this->move_to_center(distance);
    wxGetApp().plater()->get_view3D_canvas3D()->do_move(L("Move Object"));
    return;
}
References Slic3r::BoundingBox3Base< PointClass >::center(), std::distance(), get_bounding_box(), Slic3r::GUI::PartPlate::get_center_origin(), L, and move_to_center().
Referenced by Slic3r::GUI::GLCanvas3D::do_center(), and scale_to_fit_print_volume().
clear()
void Slic3r::GUI::Selection::clear ()
{
    if (!m_valid)
        return;
    if (m_list.empty())
        return;
#if ENABLE_MODIFIERS_ALWAYS_TRANSPARENT
    // ensure that the volumes get the proper color before next call to render (expecially needed for transparent volumes)
    for (unsigned int i : m_list) {
        GLVolume& volume = *(*m_volumes)[i];
        volume.selected = false;
        bool transparent = volume.color[3] < 1.0f;
        if (transparent)
            volume.force_transparent = true;
        volume.set_render_color();
        if (transparent)
            volume.force_transparent = false;
    }
#else
    for (unsigned int i : m_list) {
        (*m_volumes)[i]->selected = false;
        // ensure the volume gets the proper color before next call to render (expecially needed for transparent volumes)
        (*m_volumes)[i]->set_render_color();
    }
#endif // ENABLE_MODIFIERS_ALWAYS_TRANSPARENT
    m_list.clear();
    update_type();
    set_bounding_boxes_dirty();
    // BBS
#if 0
    // this happens while the application is closing
    if (wxGetApp().obj_manipul() == nullptr)
        return;
    // resets the cache in the sidebar
    wxGetApp().obj_manipul()->reset_cache();
#endif
    // #et_FIXME fake KillFocus from sidebar
    wxGetApp().plater()->canvas3D()->handle_sidebar_focus_event("", false);
}
References m_list, m_valid, set_bounding_boxes_dirty(), and update_type().
Referenced by Slic3r::GUI::Plater::_calib_pa_select_added_objects(), add(), add_all(), add_curr_plate(), add_instance(), add_object(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), add_volume(), add_volumes(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::priv::reload_all_from_disk(), remove_all(), remove_curr_plate(), Slic3r::GUI::GLCanvas3D::reset_volumes(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
clone()
void Slic3r::GUI::Selection::clone (int numbers = 1)
{
    if (numbers > 0)
        wxGetApp().plater()->take_snapshot(std::string("Selection-clone!"));
    for (int i = 0; i < numbers; i++) {
        copy_to_clipboard();
        paste_from_clipboard();
    }
}
References copy_to_clipboard(), and paste_from_clipboard().
Referenced by Slic3r::GUI::Plater::clone_selection().
contains_all_volumes()
bool Slic3r::GUI::Selection::contains_all_volumes (const std::vector< unsigned int > & volume_idxs) const
{
    for (unsigned int i : volume_idxs) {
        if (m_list.find(i) == m_list.end())
            return false;
    }
    return true;
}
References m_list.
Referenced by add_instance(), add_object(), add_volume(), add_volumes(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
contains_any_volume()
bool Slic3r::GUI::Selection::contains_any_volume (const std::vector< unsigned int > & volume_idxs) const
{
    for (unsigned int i : volume_idxs) {
        if (m_list.find(i) != m_list.end())
            return true;
    }
    return false;
}
References m_list.
contains_volume()
bool Slic3r::GUI::Selection::contains_volume (unsigned int volume_idx) const inline
{ return m_list.find(volume_idx) != m_list.end(); }
References m_list.
Referenced by add(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::reload_scene(), and remove().
copy_to_clipboard()
void Slic3r::GUI::Selection::copy_to_clipboard ()
{
    if (!m_valid)
        return;
    m_clipboard.reset();
    for (const ObjectIdxsToInstanceIdxsMap::value_type& object : m_cache.content)
    {
        ModelObject* src_object = m_model->objects[object.first];
        ModelObject* dst_object = m_clipboard.add_object();
        dst_object->name                 = src_object->name;
        dst_object->input_file           = src_object->input_file;
    dst_object->config.assign_config(src_object->config);
        dst_object->sla_support_points   = src_object->sla_support_points;
        dst_object->sla_points_status    = src_object->sla_points_status;
        dst_object->sla_drain_holes      = src_object->sla_drain_holes;
        dst_object->layer_config_ranges  = src_object->layer_config_ranges;     // #ys_FIXME_experiment
        dst_object->layer_height_profile.assign(src_object->layer_height_profile);
        dst_object->origin_translation   = src_object->origin_translation;
        for (int i : object.second)
        {
            dst_object->add_instance(*src_object->instances[i]);
        }
        for (unsigned int i : m_list)
        {
            // Copy the ModelVolumes only for the selected GLVolumes of the 1st selected instance.
            const GLVolume* volume = (*m_volumes)[i];
            if ((volume->object_idx() == object.first) && (volume->instance_idx() == *object.second.begin()))
            {
                int volume_idx = volume->volume_idx();
                if ((0 <= volume_idx) && (volume_idx < (int)src_object->volumes.size()))
                {
                    ModelVolume* src_volume = src_object->volumes[volume_idx];
                    ModelVolume* dst_volume = dst_object->add_volume(*src_volume);
                    dst_volume->set_new_unique_id();
                } else {
                    assert(false);
                }
            }
        }
    }
    m_clipboard.set_mode(m_mode);
}
References Slic3r::ModelObject::add_instance(), Slic3r::GUI::Selection::Clipboard::add_object(), Slic3r::ModelObject::add_volume(), Slic3r::LayerHeightProfile::assign(), Slic3r::ModelConfig::assign_config(), Slic3r::ModelObject::config, Slic3r::GUI::Selection::Cache::content, Slic3r::ModelObject::input_file, Slic3r::ModelObject::instances, int, Slic3r::ModelObject::layer_config_ranges, Slic3r::ModelObject::layer_height_profile, m_cache, m_clipboard, m_list, m_mode, m_model, m_valid, Slic3r::ModelObject::name, Slic3r::Model::objects, Slic3r::ModelObject::origin_translation, Slic3r::GUI::Selection::Clipboard::reset(), Slic3r::GUI::Selection::Clipboard::set_mode(), Slic3r::ModelVolume::set_new_unique_id(), Slic3r::ModelObject::sla_drain_holes, Slic3r::ModelObject::sla_points_status, Slic3r::ModelObject::sla_support_points, and Slic3r::ModelObject::volumes.
Referenced by clone(), and cut_to_clipboard().
cut_to_clipboard()
void Slic3r::GUI::Selection::cut_to_clipboard ()
{
    copy_to_clipboard();
    erase();
}
References copy_to_clipboard(), and erase().
do_add_volume()
void Slic3r::GUI::Selection::do_add_volume (unsigned int volume_idx) private
{
    m_list.insert(volume_idx);
    GLVolume* v = (*m_volumes)[volume_idx];
    v->selected = true;
    if (v->hover == GLVolume::HS_Select || v->hover == GLVolume::HS_Deselect)
        v->hover = GLVolume::HS_Hover;
}
References Slic3r::GLVolume::hover, Slic3r::GLVolume::HS_Deselect, Slic3r::GLVolume::HS_Hover, Slic3r::GLVolume::HS_Select, and m_list.
Referenced by add(), add_all(), add_volumes(), do_add_volumes(), instances_changed(), and set_deserialized().
do_add_volumes()
void Slic3r::GUI::Selection::do_add_volumes (const std::vector< unsigned int > & volume_idxs) private
{
    for (unsigned int i : volume_idxs)
    {
        if (i < (unsigned int)m_volumes->size())
            do_add_volume(i);
    }
}
References do_add_volume(), and m_volumes.
Referenced by add_curr_plate(), add_instance(), add_object(), add_volume(), and remove_curr_plate().
do_remove_instance()
void Slic3r::GUI::Selection::do_remove_instance (unsigned int object_idx, unsigned int instance_idx) private
{
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i) {
        GLVolume* v = (*m_volumes)[i];
        if (v->object_idx() == (int)object_idx && v->instance_idx() == (int)instance_idx)
            do_remove_volume(i);
    }
}
References do_remove_volume(), Slic3r::GLVolume::instance_idx(), int, m_volumes, and Slic3r::GLVolume::object_idx().
Referenced by remove(), and remove_instance().
do_remove_object()
void Slic3r::GUI::Selection::do_remove_object (unsigned int object_idx) private
{
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i) {
        GLVolume* v = (*m_volumes)[i];
        if (v->object_idx() == (int)object_idx)
            do_remove_volume(i);
    }
}
References do_remove_volume(), int, m_volumes, and Slic3r::GLVolume::object_idx().
Referenced by remove_object().
do_remove_volume()
void Slic3r::GUI::Selection::do_remove_volume (unsigned int volume_idx) private
{
    IndicesList::iterator v_it = m_list.find(volume_idx);
    if (v_it == m_list.end())
        return;
    m_list.erase(v_it);
    (*m_volumes)[volume_idx]->selected = false;
}
References m_list.
Referenced by do_remove_instance(), do_remove_object(), remove(), remove_volume(), and remove_volumes().
ensure_not_below_bed()
void Slic3r::GUI::Selection::ensure_not_below_bed () private
{
    typedef std::map<std::pair<int, int>, double> InstancesToZMap;
    InstancesToZMap instances_max_z;
    for (size_t i = 0; i < m_volumes->size(); ++i) {
        GLVolume* volume = (*m_volumes)[i];
        if (!volume->is_wipe_tower && !volume->is_modifier) {
            const double max_z = volume->transformed_convex_hull_bounding_box().max.z();
            const std::pair<int, int> instance = std::make_pair(volume->object_idx(), volume->instance_idx());
            InstancesToZMap::iterator it = instances_max_z.find(instance);
            if (it == instances_max_z.end())
                it = instances_max_z.insert({ instance, -DBL_MAX }).first;
            it->second = std::max(it->second, max_z);
        }
    }
    if (is_any_volume()) {
        for (unsigned int i : m_list) {
            GLVolume& volume = *(*m_volumes)[i];
            const std::pair<int, int> instance = std::make_pair(volume.object_idx(), volume.instance_idx());
            InstancesToZMap::const_iterator it = instances_max_z.find(instance);
            const double z_shift = SINKING_MIN_Z_THRESHOLD - it->second;
            if (it != instances_max_z.end() && z_shift > 0.0)
                volume.set_volume_offset(Z, volume.get_volume_offset(Z) + z_shift);
        }
    }
    else {
        for (GLVolume* volume : *m_volumes) {
            const std::pair<int, int> instance = std::make_pair(volume->object_idx(), volume->instance_idx());
            InstancesToZMap::const_iterator it = instances_max_z.find(instance);
            if (it != instances_max_z.end() && it->second < SINKING_MIN_Z_THRESHOLD)
                volume->set_instance_offset(Z, volume->get_instance_offset(Z) + SINKING_MIN_Z_THRESHOLD - it->second);
        }
    }
}
References is_any_volume(), m_list, m_volumes, Slic3r::SINKING_MIN_Z_THRESHOLD, and Slic3r::Z.
Referenced by erase(), and translate().
ensure_on_bed()
void Slic3r::GUI::Selection::ensure_on_bed () private
{
    typedef std::map<std::pair<int, int>, double> InstancesToZMap;
    InstancesToZMap instances_min_z;
    for (size_t i = 0; i < m_volumes->size(); ++i) {
        GLVolume* volume = (*m_volumes)[i];
        if (!volume->is_wipe_tower && !volume->is_modifier &&
            std::find(m_cache.sinking_volumes.begin(), m_cache.sinking_volumes.end(), i) == m_cache.sinking_volumes.end()) {
            const double min_z = volume->transformed_convex_hull_bounding_box().min.z();
            std::pair<int, int> instance = std::make_pair(volume->object_idx(), volume->instance_idx());
            InstancesToZMap::iterator it = instances_min_z.find(instance);
            if (it == instances_min_z.end())
                it = instances_min_z.insert(InstancesToZMap::value_type(instance, DBL_MAX)).first;
            it->second = std::min(it->second, min_z);
        }
    }
    for (GLVolume* volume : *m_volumes) {
        std::pair<int, int> instance = std::make_pair(volume->object_idx(), volume->instance_idx());
        InstancesToZMap::iterator it = instances_min_z.find(instance);
        if (it != instances_min_z.end())
            volume->set_instance_offset(Z, volume->get_instance_offset(Z) - it->second);
    }
}
References m_cache, m_volumes, Slic3r::GUI::Selection::Cache::sinking_volumes, and Slic3r::Z.
Referenced by scale().
erase()
void Slic3r::GUI::Selection::erase ()
{
    if (!m_valid)
        return;
    if (is_single_full_object())
        wxGetApp().obj_list()->delete_from_model_and_list(ItemType::itObject, get_object_idx(), 0);
    else if (is_multiple_full_object()) {
        std::vector<ItemForDelete> items;
        items.reserve(m_cache.content.size());
        for (ObjectIdxsToInstanceIdxsMap::iterator it = m_cache.content.begin(); it != m_cache.content.end(); ++it) {
            items.emplace_back(ItemType::itObject, it->first, 0);
        }
        wxGetApp().obj_list()->delete_from_model_and_list(items);
    }
    else if (is_multiple_full_instance()) {
        std::set<std::pair<int, int>> instances_idxs;
        for (ObjectIdxsToInstanceIdxsMap::iterator obj_it = m_cache.content.begin(); obj_it != m_cache.content.end(); ++obj_it) {
            for (InstanceIdxsList::reverse_iterator inst_it = obj_it->second.rbegin(); inst_it != obj_it->second.rend(); ++inst_it) {
                instances_idxs.insert(std::make_pair(obj_it->first, *inst_it));
            }
        }
        std::vector<ItemForDelete> items;
        items.reserve(instances_idxs.size());
        for (const std::pair<int, int>& i : instances_idxs) {
            items.emplace_back(ItemType::itInstance, i.first, i.second);
        }
        wxGetApp().obj_list()->delete_from_model_and_list(items);
    }
    else if (is_single_full_instance())
        wxGetApp().obj_list()->delete_from_model_and_list(ItemType::itInstance, get_object_idx(), get_instance_idx());
    else if (is_mixed()) {
        std::set<ItemForDelete> items_set;
        std::map<int, int> volumes_in_obj;
        for (auto i : m_list) {
            const auto gl_vol = (*m_volumes)[i];
            const auto glv_obj_idx = gl_vol->object_idx();
            const auto model_object = m_model->objects[glv_obj_idx];
            if (model_object->instances.size() == 1) {
                if (model_object->volumes.size() == 1)
                    items_set.insert(ItemForDelete(ItemType::itObject, glv_obj_idx, -1));
                else {
                    items_set.insert(ItemForDelete(ItemType::itVolume, glv_obj_idx, gl_vol->volume_idx()));
                    int idx = (volumes_in_obj.find(glv_obj_idx) == volumes_in_obj.end()) ? 0 : volumes_in_obj.at(glv_obj_idx);
                    volumes_in_obj[glv_obj_idx] = ++idx;
                }
                continue;
            }
            const auto glv_ins_idx = gl_vol->instance_idx();
            for (auto obj_ins : m_cache.content) {
                if (obj_ins.first == glv_obj_idx) {
                    if (obj_ins.second.find(glv_ins_idx) != obj_ins.second.end()) {
                        if (obj_ins.second.size() == model_object->instances.size())
                            items_set.insert(ItemForDelete(ItemType::itObject, glv_obj_idx, -1));
                        else
                            items_set.insert(ItemForDelete(ItemType::itInstance, glv_obj_idx, glv_ins_idx));
                        break;
                    }
                }
            }
        }
        std::vector<ItemForDelete> items;
        items.reserve(items_set.size());
        for (const ItemForDelete& i : items_set) {
            if (i.type == ItemType::itVolume) {
                const int vol_in_obj_cnt = volumes_in_obj.find(i.obj_idx) == volumes_in_obj.end() ? 0 : volumes_in_obj.at(i.obj_idx);
                if (vol_in_obj_cnt == (int)m_model->objects[i.obj_idx]->volumes.size()) {
                    if (i.sub_obj_idx == vol_in_obj_cnt - 1)
                        items.emplace_back(ItemType::itObject, i.obj_idx, 0);
                    continue;
                }
            }
            items.emplace_back(i.type, i.obj_idx, i.sub_obj_idx);
        }
        wxGetApp().obj_list()->delete_from_model_and_list(items);
    }
    else {
        std::set<std::pair<int, int>> volumes_idxs;
        for (unsigned int i : m_list) {
            const GLVolume* v = (*m_volumes)[i];
            // Only remove volumes associated with ModelVolumes from the object list.
            // Temporary meshes (SLA supports or pads) are not managed by the object list.
            if (v->volume_idx() >= 0)
                volumes_idxs.insert(std::make_pair(v->object_idx(), v->volume_idx()));
        }
        std::vector<ItemForDelete> items;
        items.reserve(volumes_idxs.size());
        for (const std::pair<int, int>& v : volumes_idxs) {
            items.emplace_back(ItemType::itVolume, v.first, v.second);
        }
        wxGetApp().obj_list()->delete_from_model_and_list(items);
        ensure_not_below_bed();
    }
}
References Slic3r::GUI::Selection::Cache::content, ensure_not_below_bed(), get_instance_idx(), get_object_idx(), is_mixed(), is_multiple_full_instance(), is_multiple_full_object(), is_single_full_instance(), is_single_full_object(), Slic3r::GUI::itInstance, Slic3r::GUI::itObject, Slic3r::GUI::itVolume, m_cache, m_list, m_model, m_valid, Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, and Slic3r::GLVolume::volume_idx().
Referenced by cut_to_clipboard(), Slic3r::GUI::GLCanvas3D::delete_selected(), and remove_curr_plate().
fill_color()
void Slic3r::GUI::Selection::fill_color (int extruder_id)
{
    wxGetApp().obj_list()->set_extruder_for_selected_items(extruder_id);
}
flattening_rotate()
void Slic3r::GUI::Selection::flattening_rotate (const Vec3d & normal)
{
    // We get the normal in untransformed coordinates. We must transform it using the instance matrix, find out
    // how to rotate the instance so it faces downwards and do the rotation. All that for all selected instances.
    // The function assumes that is_from_single_object() holds.
    assert(Slic3r::is_approx(normal.norm(), 1.));
    if (!m_valid)
        return;
    // BBS: show the normal for debug
    std::stringstream ss;
    ss << std::fixed << std::setprecision(4) << ": " << (-normal).transpose();
    wxGetApp().plater()->show_status_message("place on face -normal: "+ss.str());
    BOOST_LOG_TRIVIAL(debug) <<"flattening_rotate at "<<__FILE__<<":"<<__LINE__ << std::fixed << std::setprecision(4) << ": " << normal.transpose();
    flush_logs();
    for (unsigned int i : m_list) {
        GLVolume& v = *(*m_volumes)[i];
        // Normal transformed from the object coordinate space to the world coordinate space.
        const auto &voldata = m_cache.volumes_data[i];
        Vec3d tnormal = (Geometry::assemble_transform(
            Vec3d::Zero(), voldata.get_instance_rotation(),
            voldata.get_instance_scaling_factor().cwiseInverse(), voldata.get_instance_mirror()) * normal).normalized();
        // Additional rotation to align tnormal with the down vector in the world coordinate space.
        auto  extra_rotation = Eigen::Quaterniond().setFromTwoVectors(tnormal, - Vec3d::UnitZ());
        v.set_instance_rotation(Geometry::extract_euler_angles(extra_rotation.toRotationMatrix() * m_cache.volumes_data[i].get_instance_rotation_matrix()));
        BOOST_LOG_TRIVIAL(debug) << "flattening_rotate " << (*m_volumes)[i]->name << std::fixed << std::setprecision(4) << ": tnormal=" << tnormal.transpose() << "; extra_rotation=" << Geometry::extract_euler_angles(extra_rotation.toRotationMatrix()).transpose();
        flush_logs();
    }
#if !DISABLE_INSTANCES_SYNCH
    // Apply the same transformation also to other instances,
    // but respect their possibly diffrent z-rotation.
    if (m_mode == Instance)
        synchronize_unselected_instances(SYNC_ROTATION_GENERAL);
#endif // !DISABLE_INSTANCES_SYNCH
    this->set_bounding_boxes_dirty();
}
References Slic3r::Geometry::assemble_transform(), Slic3r::Geometry::extract_euler_angles(), Slic3r::flush_logs(), Instance, Slic3r::is_approx(), m_cache, m_list, m_mode, m_valid, Slic3r::normal(), set_bounding_boxes_dirty(), Slic3r::GLVolume::set_instance_rotation(), SYNC_ROTATION_GENERAL, synchronize_unselected_instances(), and Slic3r::GUI::Selection::Cache::volumes_data.
Referenced by Slic3r::GUI::GLCanvas3D::do_flatten().
get_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::Selection::get_bounding_box () const
{
    if (!m_bounding_box.has_value()) {
        std::optional<BoundingBoxf3>* bbox = const_cast<std::optional<BoundingBoxf3>*>(&m_bounding_box);
        *bbox = BoundingBoxf3();
        if (m_valid) {
            for (unsigned int i : m_list) {
                (*bbox)->merge((*m_volumes)[i]->transformed_convex_hull_bounding_box());
            }
        }
    }
    return *m_bounding_box;
}
References m_bounding_box, m_list, m_valid, and m_volumes.
Referenced by Slic3r::GUI::GLCanvas3D::_max_bounding_box(), Slic3r::GUI::GLCanvas3D::_render_assemble_info(), Slic3r::GUI::MenuFactory::append_menu_item_center(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), center(), Slic3r::GUI::GLGizmoAdvancedCut::get_plane_points_world_coord(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_render_for_picking(), Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), render_selected_volumes(), render_sidebar_layers_hints(), Slic3r::GUI::GLGizmoAdvancedCut::reset_cut_plane(), scale_to_fit_print_volume(), set_caches(), Slic3r::GUI::GizmoObjectManipulation::update_settings_value(), and Slic3r::GUI::GLCanvas3D::zoom_to_selection().
get_clipboard()
const Clipboard & Slic3r::GUI::Selection::get_clipboard () const inline
{ return m_clipboard; }
References m_clipboard.
Referenced by Slic3r::GUI::Plater::can_paste_from_clipboard().
get_content()
const ObjectIdxsToInstanceIdxsMap & Slic3r::GUI::Selection::get_content () const inline
{ return m_cache.content; }
References Slic3r::GUI::Selection::Cache::content, and m_cache.
Referenced by Slic3r::GUI::RotoptimizeJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::Plater::show_object_info(), and Slic3r::GUI::ObjectList::update_selections().
get_instance_idx()
int Slic3r::GUI::Selection::get_instance_idx () const
{
    if (m_cache.content.size() == 1) {
        const InstanceIdxsList& idxs = m_cache.content.begin()->second;
        if (idxs.size() == 1)
            return *idxs.begin();
    }
    return -1;
}
References Slic3r::GUI::Selection::Cache::content, and m_cache.
Referenced by Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), add(), erase(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), is_from_single_instance(), is_single_full_instance(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_update(), paste_volumes_from_clipboard(), Slic3r::GUI::GLGizmoAdvancedCut::perform_cut(), Slic3r::GUI::GLGizmoCut::perform_cut(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::Plater::show_object_info(), Slic3r::GUI::ObjectList::split_instances(), Slic3r::GUI::GLGizmoCut::update_contours(), Slic3r::GUI::GLGizmoPainterBase::update_contours(), Slic3r::GUI::ObjectList::update_selections(), Slic3r::GUI::ObjectList::update_selections_on_canvas(), and Slic3r::GUI::GLGizmoText::update_text_positions().
get_instance_idxs()
const Selection::InstanceIdxsList & Slic3r::GUI::Selection::get_instance_idxs () const
{
    assert(m_cache.content.size() == 1);
    return m_cache.content.begin()->second;
}
References Slic3r::GUI::Selection::Cache::content, and m_cache.
Referenced by Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::split_instances(), and Slic3r::GUI::ObjectList::update_selections().
get_missing_volume_idxs_from()
std::vector< unsigned int > Slic3r::GUI::Selection::get_missing_volume_idxs_from (const std::vector< unsigned int > & volume_idxs) const
{
    std::vector<unsigned int> idxs;
    for (unsigned int i : m_list)
    {
        std::vector<unsigned int>::const_iterator it = std::find(volume_idxs.begin(), volume_idxs.end(), i);
        if (it == volume_idxs.end())
            idxs.push_back(i);
    }
    return idxs;
}
References m_list.
Referenced by Slic3r::GUI::ObjectList::update_selections_on_canvas().
get_mode()
EMode Slic3r::GUI::Selection::get_mode () const inline
{ return m_mode; }
References m_mode.
Referenced by Slic3r::GUI::Plater::can_paste_from_clipboard(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::Plater::show_object_info(), Slic3r::UndoRedo::StackImpl::take_snapshot(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
get_model()
Model * Slic3r::GUI::Selection::get_model () const inline
{ return m_model; }
References m_model.
Referenced by Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::GLGizmoText::delete_temp_preview_text_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoText::get_text_mesh(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::GLGizmoText::on_update(), and Slic3r::GUI::GLGizmoText::update_text_positions().
get_object_idx()
int Slic3r::GUI::Selection::get_object_idx () const
{
    return (m_cache.content.size() == 1) ? m_cache.content.begin()->first : -1;
}
References Slic3r::GUI::Selection::Cache::content, and m_cache.
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), Slic3r::GUI::MenuFactory::append_menu_item_settings(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::GLCanvas3D::do_rotate(), erase(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::Plater::priv::get_export_file_path(), Slic3r::GUI::Plater::priv::get_selected_object_idx(), is_from_single_object(), is_single_full_instance(), Slic3r::GUI::ObjectList::layers_editing(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::load_shape_object(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::on_mouse_wheel(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::ObjectList::part_selection_changed(), paste_volumes_from_clipboard(), Slic3r::GUI::GLGizmoAdvancedCut::perform_cut(), Slic3r::GUI::GLGizmoCut::perform_cut(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), Slic3r::GUI::Plater::show_object_info(), Slic3r::GUI::ObjectList::split_instances(), Slic3r::GUI::GLGizmoCut::update_contours(), Slic3r::GUI::GLGizmoPainterBase::update_contours(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
get_scaled_instance_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::Selection::get_scaled_instance_bounding_box () const
{
    if (!m_scaled_instance_bounding_box.has_value()) {
        std::optional<BoundingBoxf3>* bbox = const_cast<std::optional<BoundingBoxf3>*>(&m_scaled_instance_bounding_box);
        *bbox = BoundingBoxf3();
        if (m_valid) {
            for (unsigned int i : m_list) {
                const GLVolume& volume = *(*m_volumes)[i];
                if (volume.is_modifier)
                    continue;
                Transform3d trafo = volume.get_instance_transformation().get_matrix(false, false, false, false) * volume.get_volume_transformation().get_matrix();
                trafo.translation().z() += volume.get_sla_shift_z();
                (*bbox)->merge(volume.transformed_convex_hull_bounding_box(trafo));
            }
        }
    }
    return *m_scaled_instance_bounding_box;
}
References m_list, m_scaled_instance_bounding_box, m_valid, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::GUI::GizmoObjectManipulation::update_settings_value().
get_selected_object_instances()
std::set< std::pair< int, int > > Slic3r::GUI::Selection::get_selected_object_instances ()
{
    std::set<std::pair<int, int>> instances_idxs;
    // BBS only support multi full object now
    if (!is_multiple_full_object())
        return instances_idxs;
    for (ObjectIdxsToInstanceIdxsMap::iterator obj_it = m_cache.content.begin(); obj_it != m_cache.content.end(); ++obj_it)
    {
        for (InstanceIdxsList::reverse_iterator inst_it = obj_it->second.rbegin(); inst_it != obj_it->second.rend(); ++inst_it)
        {
            instances_idxs.insert(std::make_pair(obj_it->first, *inst_it));
        }
    }
    return instances_idxs;
}
References Slic3r::GUI::Selection::Cache::content, is_multiple_full_object(), and m_cache.
get_unscaled_instance_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::Selection::get_unscaled_instance_bounding_box () const
{
    if (!m_unscaled_instance_bounding_box.has_value()) {
        std::optional<BoundingBoxf3>* bbox = const_cast<std::optional<BoundingBoxf3>*>(&m_unscaled_instance_bounding_box);
        *bbox = BoundingBoxf3();
        if (m_valid) {
            for (unsigned int i : m_list) {
                const GLVolume& volume = *(*m_volumes)[i];
                if (volume.is_modifier)
                    continue;
                Transform3d trafo = volume.get_instance_transformation().get_matrix(false, false, true, false) * volume.get_volume_transformation().get_matrix();
                trafo.translation().z() += volume.get_sla_shift_z();
                (*bbox)->merge(volume.transformed_convex_hull_bounding_box(trafo));
            }
        }
    }
    return *m_unscaled_instance_bounding_box;
}
References m_list, m_unscaled_instance_bounding_box, m_valid, and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translation().
Referenced by Slic3r::GUI::GizmoObjectManipulation::change_size_value(), and Slic3r::GUI::GizmoObjectManipulation::update_settings_value().
get_unselected_volume_idxs_from()
std::vector< unsigned int > Slic3r::GUI::Selection::get_unselected_volume_idxs_from (const std::vector< unsigned int > & volume_idxs) const
{
    std::vector<unsigned int> idxs;
    for (unsigned int i : volume_idxs)
    {
        if (m_list.find(i) == m_list.end())
            idxs.push_back(i);
    }
    return idxs;
}
References m_list.
Referenced by Slic3r::GUI::ObjectList::update_selections_on_canvas().
get_volume()
const GLVolume * Slic3r::GUI::Selection::get_volume (unsigned int volume_idx) const
{
    return (m_valid && (volume_idx < (unsigned int)m_volumes->size())) ? (*m_volumes)[volume_idx] : nullptr;
}
References m_valid, and m_volumes.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_set_visible(), Slic3r::GUI::GLGizmoAdvancedCut::bounding_box(), Slic3r::GUI::GLGizmoCut::bounding_box(), Slic3r::GUI::GLGizmoPainterBase::bounding_box(), Slic3r::GUI::GLGizmoText::bounding_box(), Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::GizmoObjectManipulation::change_size_value(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::perform_cut(), Slic3r::GUI::GLGizmoCut::perform_cut(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GizmoObjectManipulation::reset_position_value(), Slic3r::GUI::GizmoObjectManipulation::reset_rotation_value(), Slic3r::GUI::GLCanvas3D::set_selected_visible(), Slic3r::GUI::GizmoObjectManipulation::set_uniform_scaling(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoRotate::transform_to_local(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut::update_contours(), Slic3r::GUI::GLGizmoPainterBase::update_contours(), Slic3r::GUI::GizmoObjectManipulation::update_reset_buttons_visibility(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::GizmoObjectManipulation::update_settings_value().
get_volume_idxs()
const IndicesList & Slic3r::GUI::Selection::get_volume_idxs () const inline
{ return m_list; }
References m_list.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_set_visible(), Slic3r::GUI::GLGizmoAdvancedCut::bounding_box(), Slic3r::GUI::GLGizmoCut::bounding_box(), Slic3r::GUI::GLGizmoPainterBase::bounding_box(), Slic3r::GUI::GLGizmoText::bounding_box(), Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::Plater::priv::can_replace_with_stl(), Slic3r::GUI::GizmoObjectManipulation::change_size_value(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeshBoolean::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::perform_cut(), Slic3r::GUI::GLGizmoCut::perform_cut(), Slic3r::GUI::Plater::priv::reload_all_from_disk(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GizmoObjectManipulation::reset_position_value(), Slic3r::GUI::GizmoObjectManipulation::reset_rotation_value(), Slic3r::GUI::GLCanvas3D::set_selected_visible(), Slic3r::GUI::GizmoObjectManipulation::set_uniform_scaling(), Slic3r::GUI::Plater::show_object_info(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoRotate::transform_to_local(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut::update_contours(), Slic3r::GUI::GLGizmoPainterBase::update_contours(), Slic3r::GUI::GizmoObjectManipulation::update_reset_buttons_visibility(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::GizmoObjectManipulation::update_settings_value().
get_volume_idxs_from_instance()
std::vector< unsigned int > Slic3r::GUI::Selection::get_volume_idxs_from_instance (unsigned int object_idx, unsigned int instance_idx) const
{
    std::vector<unsigned int> idxs;
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i)
    {
        const GLVolume* v = (*m_volumes)[i];
        if ((v->object_idx() == (int)object_idx) && (v->instance_idx() == (int)instance_idx))
            idxs.push_back(i);
    }
    return idxs;
}
References Slic3r::GLVolume::instance_idx(), int, m_volumes, and Slic3r::GLVolume::object_idx().
Referenced by add_instance(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
get_volume_idxs_from_object()
std::vector< unsigned int > Slic3r::GUI::Selection::get_volume_idxs_from_object (unsigned int object_idx) const
{
    std::vector<unsigned int> idxs;
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i)
    {
        if ((*m_volumes)[i]->object_idx() == (int)object_idx)
            idxs.push_back(i);
    }
    return idxs;
}
References int, and m_volumes.
Referenced by add_curr_plate(), add_object(), remove_curr_plate(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
get_volume_idxs_from_volume()
std::vector< unsigned int > Slic3r::GUI::Selection::get_volume_idxs_from_volume (unsigned int object_idx, unsigned int instance_idx, unsigned int volume_idx) const
{
    std::vector<unsigned int> idxs;
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i)
    {
        const GLVolume* v = (*m_volumes)[i];
        if ((v->object_idx() == (int)object_idx) && (v->volume_idx() == (int)volume_idx))
        {
            if (((int)instance_idx != -1) && (v->instance_idx() == (int)instance_idx))
                idxs.push_back(i);
        }
    }
    return idxs;
}
References Slic3r::GLVolume::instance_idx(), int, m_volumes, Slic3r::GLVolume::object_idx(), and Slic3r::GLVolume::volume_idx().
Referenced by add_volume(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
init()
bool Slic3r::GUI::Selection::init ()
{
    m_arrow.init_from(straight_arrow(10.0f, 5.0f, 5.0f, 10.0f, 1.0f));
    m_curved_arrow.init_from(circular_arrow(16, 10.0f, 5.0f, 10.0f, 5.0f, 1.0f));
#if ENABLE_RENDER_SELECTION_CENTER
    m_vbo_sphere.init_from(make_sphere(0.75, 2*PI/24));
#endif // ENABLE_RENDER_SELECTION_CENTER
    return true;
}
References Slic3r::GUI::circular_arrow(), Slic3r::GUI::GLModel::init_from(), m_arrow, m_curved_arrow, Slic3r::make_sphere(), Slic3r::GUI::PI, and Slic3r::GUI::straight_arrow().
Referenced by Slic3r::GUI::GLCanvas3D::init().
instances_changed()
void Slic3r::GUI::Selection::instances_changed (const std::vector< size_t > & instance_ids_selected)
{
    assert(m_valid);
    assert(m_mode == Instance);
    m_list.clear();
    for (unsigned int volume_idx = 0; volume_idx < (unsigned int)m_volumes->size(); ++ volume_idx) {
        const GLVolume *volume = (*m_volumes)[volume_idx];
        auto it = std::lower_bound(instance_ids_selected.begin(), instance_ids_selected.end(), volume->geometry_id.second);
    if (it != instance_ids_selected.end() && *it == volume->geometry_id.second)
            this->do_add_volume(volume_idx);
    }
    update_type();
    this->set_bounding_boxes_dirty();
}
References do_add_volume(), Instance, int, m_list, m_mode, m_valid, m_volumes, set_bounding_boxes_dirty(), and update_type().
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene().
is_any_modifier()
bool Slic3r::GUI::Selection::is_any_modifier () const inline
{ return is_single_modifier() || is_multiple_modifier(); }
References is_multiple_modifier(), and is_single_modifier().
Referenced by Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), add(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::update_selections().
is_any_volume()
bool Slic3r::GUI::Selection::is_any_volume () const inline
{ return is_single_volume() || is_multiple_volume(); }
References is_multiple_volume(), and is_single_volume().
Referenced by add(), ensure_not_below_bed(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::update_selections().
is_dragging()
bool Slic3r::GUI::Selection::is_dragging () const inline
{ return m_dragging; }
References m_dragging.
is_empty()
bool Slic3r::GUI::Selection::is_empty () const inline
{ return m_type == Empty; }
References Empty, and m_type.
Referenced by Slic3r::GUI::GLCanvas3D::_render_assemble_info(), Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), add(), Slic3r::GUI::Plater::priv::can_delete(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLCanvas3D::on_key(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::reload_scene(), remove_all(), render(), scale_to_fit_print_volume(), and Slic3r::GUI::GLCanvas3D::zoom_to_selection().
is_enabled()
bool Slic3r::GUI::Selection::is_enabled () const inline
{ return m_enabled; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::init().
is_from_fully_selected_instance()
bool Slic3r::GUI::Selection::is_from_fully_selected_instance (unsigned int volume_idx) const private
{
    struct SameInstance
    {
        int obj_idx;
        int inst_idx;
        GLVolumePtrs& volumes;
        SameInstance(int obj_idx, int inst_idx, GLVolumePtrs& volumes) : obj_idx(obj_idx), inst_idx(inst_idx), volumes(volumes) {}
        bool operator () (unsigned int i) { return (volumes[i]->volume_idx() >= 0) && (volumes[i]->object_idx() == obj_idx) && (volumes[i]->instance_idx() == inst_idx); }
    };
    if ((unsigned int)m_volumes->size() <= volume_idx)
        return false;
    GLVolume* volume = (*m_volumes)[volume_idx];
    int object_idx = volume->object_idx();
    if ((int)m_model->objects.size() <= object_idx)
        return false;
    unsigned int count = (unsigned int)std::count_if(m_list.begin(), m_list.end(), SameInstance(object_idx, volume->instance_idx(), *m_volumes));
    return count == (unsigned int)m_model->objects[object_idx]->volumes.size();
}
References count, int, m_list, m_model, m_volumes, and Slic3r::Model::objects.
Referenced by move_to_center(), and translate().
is_from_single_instance()
bool Slic3r::GUI::Selection::is_from_single_instance () const inline
{ return get_instance_idx() != -1; }
References get_instance_idx().
Referenced by Slic3r::GUI::Plater::priv::can_mirror(), Slic3r::GUI::Plater::can_paste_from_clipboard(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), paste_from_clipboard(), requires_local_axes(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), and Slic3r::GUI::ObjectList::update_selections().
is_from_single_object()
bool Slic3r::GUI::Selection::is_from_single_object () const
{
    const int idx = get_object_idx();
    return 0 <= idx && idx < 1000;
}
References get_object_idx().
is_instance_mode()
bool Slic3r::GUI::Selection::is_instance_mode () const inline
{ return m_mode == Instance; }
References Instance, and m_mode.
is_mixed()
bool Slic3r::GUI::Selection::is_mixed () const inline
{ return m_type == Mixed; }
References m_type, and Mixed.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_settings(), erase(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::update_selections().
is_multiple_full_instance()
bool Slic3r::GUI::Selection::is_multiple_full_instance () const inline
{ return m_type == MultipleFullInstance; }
References m_type, and MultipleFullInstance.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_export_stl(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_process(), Slic3r::GUI::MenuFactory::append_menu_item_settings(), Slic3r::GUI::ObjectList::can_split_instances(), erase(), Slic3r::GUI::Plater::priv::on_right_click(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::update_selections().
is_multiple_full_object()
bool Slic3r::GUI::Selection::is_multiple_full_object () const inline
{ return m_type == MultipleFullObject; }
References m_type, and MultipleFullObject.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_export_stl(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_process(), erase(), Slic3r::GUI::Plater::export_stl(), get_selected_object_instances(), Slic3r::GUI::ObjectList::part_selection_changed(), and Slic3r::GUI::ObjectList::update_selections().
is_multiple_modifier()
bool Slic3r::GUI::Selection::is_multiple_modifier () const inline
{ return m_type == MultipleModifier; }
References m_type, and MultipleModifier.
Referenced by is_any_modifier().
is_multiple_volume()
bool Slic3r::GUI::Selection::is_multiple_volume () const inline
{ return m_type == MultipleVolume; }
References m_type, and MultipleVolume.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_per_object_process(), Slic3r::GUI::MenuFactory::append_menu_item_settings(), and is_any_volume().
is_single_full_instance()
bool Slic3r::GUI::Selection::is_single_full_instance () const
{
    if (m_type == SingleFullInstance)
        return true;
    if (m_type == SingleFullObject)
        return get_instance_idx() != -1;
    if (m_list.empty() || m_volumes->empty())
        return false;
    int object_idx = m_valid ? get_object_idx() : -1;
    if (object_idx < 0 || (int)m_model->objects.size() <= object_idx)
        return false;
    int instance_idx = (*m_volumes)[*m_list.begin()]->instance_idx();
    std::set<int> volumes_idxs;
    for (unsigned int i : m_list) {
        const GLVolume* v = (*m_volumes)[i];
        if (object_idx != v->object_idx() || instance_idx != v->instance_idx())
            return false;
        int volume_idx = v->volume_idx();
        if (volume_idx >= 0)
            volumes_idxs.insert(volume_idx);
    }
    return m_model->objects[object_idx]->volumes.size() == volumes_idxs.size();
}
References get_instance_idx(), get_object_idx(), Slic3r::GLVolume::instance_idx(), m_list, m_model, m_type, m_valid, m_volumes, Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, SingleFullInstance, SingleFullObject, and Slic3r::GLVolume::volume_idx().
Referenced by Slic3r::GUI::GLCanvas3D::_update_volumes_hover_state(), Slic3r::GUI::MenuFactory::append_menu_item_export_stl(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_process(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_settings(), Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::ObjectList::can_split_instances(), Slic3r::GUI::GizmoObjectManipulation::change_rotation_value(), Slic3r::GUI::GizmoObjectManipulation::change_size_value(), Slic3r::GUI::GizmoObjectManipulation::do_scale(), erase(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::ObjectList::is_instance_or_object_selected(), mirror(), Slic3r::GUI::GLGizmoAdvancedCut::on_is_activable(), Slic3r::GUI::GLGizmoCut::on_is_activable(), Slic3r::GUI::GLGizmoFaceDetector::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoMeshBoolean::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoText::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::Plater::priv::on_right_click(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::ObjectList::part_selection_changed(), requires_uniform_scale(), Slic3r::GUI::GizmoObjectManipulation::reset_position_value(), Slic3r::GUI::GizmoObjectManipulation::reset_rotation_value(), rotate(), scale(), Slic3r::GUI::GizmoObjectManipulation::set_uniform_scaling(), Slic3r::GUI::Plater::show_object_info(), Slic3r::GUI::GizmoObjectManipulation::update_reset_buttons_visibility(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::GizmoObjectManipulation::update_settings_value().
is_single_full_object()
bool Slic3r::GUI::Selection::is_single_full_object () const inline
{ return m_type == SingleFullObject; }
References m_type, and SingleFullObject.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_export_stl(), Slic3r::GUI::MenuFactory::append_menu_item_instance_to_object(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_process(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_settings(), Slic3r::GUI::MenuFactory::append_menu_item_settings(), erase(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::ObjectList::is_instance_or_object_selected(), Slic3r::GUI::ObjectList::layers_editing(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::Plater::priv::on_right_click(), Slic3r::GUI::ObjectList::part_selection_changed(), Slic3r::GUI::Plater::show_object_info(), Slic3r::GUI::ObjectList::split_instances(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::GizmoObjectManipulation::update_settings_value().
is_single_modifier()
bool Slic3r::GUI::Selection::is_single_modifier () const inline
{ return m_type == SingleModifier; }
References m_type, and SingleModifier.
Referenced by Slic3r::GUI::GizmoObjectManipulation::change_size_value(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), is_any_modifier(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::Plater::priv::on_right_click(), Slic3r::GUI::GLGizmoText::on_set_state(), requires_uniform_scale(), Slic3r::GUI::GizmoObjectManipulation::reset_position_value(), Slic3r::GUI::GizmoObjectManipulation::reset_rotation_value(), rotate(), scale(), Slic3r::GUI::GLGizmoRotate::transform_to_local(), Slic3r::GUI::GizmoObjectManipulation::update_reset_buttons_visibility(), and Slic3r::GUI::GizmoObjectManipulation::update_settings_value().
is_single_volume()
bool Slic3r::GUI::Selection::is_single_volume () const inline
{ return m_type == SingleVolume; }
References m_type, and SingleVolume.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_per_object_process(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_settings(), Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::GizmoObjectManipulation::change_size_value(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), is_any_volume(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::Plater::priv::on_right_click(), Slic3r::GUI::GLGizmoText::on_set_state(), requires_uniform_scale(), Slic3r::GUI::GizmoObjectManipulation::reset_position_value(), Slic3r::GUI::GizmoObjectManipulation::reset_rotation_value(), rotate(), scale(), Slic3r::GUI::Plater::show_object_info(), Slic3r::GUI::GLGizmoRotate::transform_to_local(), Slic3r::GUI::GizmoObjectManipulation::update_reset_buttons_visibility(), Slic3r::GUI::ObjectList::update_selections(), and Slic3r::GUI::GizmoObjectManipulation::update_settings_value().
is_sla_compliant()
bool Slic3r::GUI::Selection::is_sla_compliant () const
{
    if (m_mode == Volume)
        return false;
    for (unsigned int i : m_list) {
        if ((*m_volumes)[i]->is_modifier)
            return false;
    }
    return true;
}
References m_list, m_mode, m_volumes, and Volume.
Referenced by Slic3r::GUI::Plater::can_copy_to_clipboard().
is_wipe_tower()
bool Slic3r::GUI::Selection::is_wipe_tower () const inline
{ return m_type == WipeTower; }
References m_type, and WipeTower.
Referenced by add(), Slic3r::GUI::Plater::priv::can_delete(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoAdvancedCut::on_is_activable(), Slic3r::GUI::GLGizmoCut::on_is_activable(), Slic3r::GUI::GLGizmoFaceDetector::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::Plater::priv::replace_with_stl(), rotate(), and update_type().
lock_volume_selection_mode()
void Slic3r::GUI::Selection::lock_volume_selection_mode () inline
{ m_volume_selection_locked = true; }
References m_volume_selection_locked.
Referenced by Slic3r::GUI::AssembleView::init().
matches()
bool Slic3r::GUI::Selection::matches (const std::vector< unsigned int > & volume_idxs) const
{
    unsigned int count = 0;
    for (unsigned int i : volume_idxs) {
        if (m_list.find(i) != m_list.end())
            ++count;
        else
            return false;
    }
    return count == (unsigned int)m_list.size();
}
References count, int, and m_list.
Referenced by add_instance(), add_object(), add_volume(), and add_volumes().
mirror()
void Slic3r::GUI::Selection::mirror (Axis axis)
{
    if (!m_valid)
        return;
    for (unsigned int i : m_list) {
        GLVolume& v = *(*m_volumes)[i];
        if (is_single_full_instance())
            v.set_instance_mirror(axis, -v.get_instance_mirror(axis));
        else if (m_mode == Volume)
            v.set_volume_mirror(axis, -v.get_volume_mirror(axis));
    }
#if !DISABLE_INSTANCES_SYNCH
    if (m_mode == Instance)
        synchronize_unselected_instances(SYNC_ROTATION_NONE);
    else if (m_mode == Volume)
        synchronize_unselected_volumes();
#endif // !DISABLE_INSTANCES_SYNCH
    set_bounding_boxes_dirty();
}
References Slic3r::GLVolume::get_instance_mirror(), Slic3r::GLVolume::get_volume_mirror(), Instance, is_single_full_instance(), m_list, m_mode, m_valid, set_bounding_boxes_dirty(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_volume_mirror(), SYNC_ROTATION_NONE, synchronize_unselected_instances(), synchronize_unselected_volumes(), and Volume.
Referenced by Slic3r::GUI::GLCanvas3D::mirror_selection(), synchronize_unselected_instances(), and synchronize_unselected_volumes().
move_to_center()
void Slic3r::GUI::Selection::move_to_center (const Vec3d & displacement, bool local = false)
{
    if (!m_valid)
        return;
    EMode translation_type = m_mode;
    //BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, displacement {%2%, %3%, %4%}") % __LINE__ % displacement(X) % displacement(Y) % displacement(Z);
    set_caches();
    for (unsigned int i : m_list) {
        GLVolume& v = *(*m_volumes)[i];
        if (m_mode == Volume) {
            if (local)
                v.set_volume_offset(m_cache.volumes_data[i].get_volume_position() + displacement);
            else {
                const Vec3d local_displacement = (m_cache.volumes_data[i].get_instance_rotation_matrix() * m_cache.volumes_data[i].get_instance_scale_matrix() * m_cache.volumes_data[i].get_instance_mirror_matrix()).inverse() * displacement;
                v.set_volume_offset(m_cache.volumes_data[i].get_volume_position() + local_displacement);
            }
        }
        else if (m_mode == Instance) {
            if (is_from_fully_selected_instance(i)) {
                v.set_instance_offset(m_cache.volumes_data[i].get_instance_position() + displacement);
            }
            else {
                const Vec3d local_displacement = (m_cache.volumes_data[i].get_instance_rotation_matrix() * m_cache.volumes_data[i].get_instance_scale_matrix() * m_cache.volumes_data[i].get_instance_mirror_matrix()).inverse() * displacement;
                v.set_volume_offset(m_cache.volumes_data[i].get_volume_position() + local_displacement);
                translation_type = Volume;
            }
        }
    }
    this->set_bounding_boxes_dirty();
}
References Instance, inverse(), is_from_fully_selected_instance(), m_cache, m_list, m_mode, m_valid, set_bounding_boxes_dirty(), set_caches(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_volume_offset(), Volume, and Slic3r::GUI::Selection::Cache::volumes_data.
Referenced by center().
notify_instance_update()
void Slic3r::GUI::Selection::notify_instance_update (int object_idx, int instance_idx)
{
    //BBS: notify instance updates to part plater list
    PartPlateList& plate_list = wxGetApp().plater()->get_partplate_list();
    if (object_idx == -1)
    {
        std::set<std::pair<int, int>> notify_set;
        for (unsigned int i : m_list)
        {
            int obj_index = (*m_volumes)[i]->object_idx();
            //-1 means all the instance in this object
            if (instance_idx == -1)
            {
                ModelObject* object = m_model->objects[obj_index];
                for (int instance_index = 0; instance_index < object->instances.size(); instance_index++)
                {
                    std::pair<int, int> notify_index(obj_index, instance_index);
                    if (notify_set.find(notify_index) == notify_set.end()) {
                        plate_list.notify_instance_update(obj_index, instance_index);
                        notify_set.insert(notify_index);
                    }
                }
            }
            else {
                std::pair<int, int> notify_index(obj_index, instance_idx);
                if (notify_set.find(notify_index) == notify_set.end()) {
                    plate_list.notify_instance_update(obj_index, instance_idx);
                    notify_set.insert(notify_index);
                }
            }
        }
    }
    else
    {
        if (instance_idx == -1)
        {
            ModelObject* object = m_model->objects[object_idx];
            for (int index = 0; index < object->instances.size(); index++)
            {
                plate_list.notify_instance_update(object_idx, index);
            }
        }
        else
            plate_list.notify_instance_update(object_idx, instance_idx);
    }
}
References m_list, m_model, Slic3r::GUI::PartPlateList::notify_instance_update(), and Slic3r::Model::objects.
Referenced by Slic3r::GUI::Plater::_calib_pa_select_added_objects(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), and Slic3r::GUI::GLCanvas3D::do_scale().
paste_from_clipboard()
void Slic3r::GUI::Selection::paste_from_clipboard ()
{
    if (!m_valid || m_clipboard.is_empty())
        return;
    switch (m_clipboard.get_mode())
    {
    case Volume:
    {
        if (is_from_single_instance())
            paste_volumes_from_clipboard();
        break;
    }
    case Instance:
    {
        if (m_mode == Instance)
            paste_objects_from_clipboard();
        break;
    }
    }
}
References Slic3r::GUI::Selection::Clipboard::get_mode(), Instance, Slic3r::GUI::Selection::Clipboard::is_empty(), is_from_single_instance(), m_clipboard, m_mode, m_valid, paste_objects_from_clipboard(), paste_volumes_from_clipboard(), and Volume.
Referenced by clone().
paste_objects_from_clipboard()
void Slic3r::GUI::Selection::paste_objects_from_clipboard () private
{
#ifdef _DEBUG
    check_model_ids_validity(*m_model);
#endif /* _DEBUG */
    std::vector<size_t> object_idxs;
    const ModelObjectPtrs& src_objects = m_clipboard.get_objects();
    PartPlate *            plate       = wxGetApp().plater()->get_partplate_list().get_curr_plate();
    //BBS: if multiple objects are selected, move them as a whole after copy
    Vec2d shift_all = {0, 0};
    Vec2f empty_cell_all = {0, 0};
    if (src_objects.size() > 1) {
        BoundingBoxf3 bbox_all;
        for (const ModelObject *src_object : src_objects) {
            BoundingBoxf3 bbox = src_object->instance_convex_hull_bounding_box(0);
            bbox_all.merge(bbox);
        }
        auto bsize = bbox_all.size();
        if (bsize.x() < bsize.y())
            shift_all = {bbox_all.size().x(), 0};
        else
            shift_all = {0, bbox_all.size().y()};
    }
    for (size_t i=0;i<src_objects.size();i++)
    {
        const ModelObject *src_object = src_objects[i];
        ModelObject* dst_object = m_model->add_object(*src_object);
        // BBS: find an empty cell to put the copied object
        BoundingBoxf3 bbox = src_object->instance_convex_hull_bounding_box(0);
        Vec3d displacement;
        bool  in_current  = plate->intersects(bbox);
        auto  start_point = in_current ? bbox.center() : plate->get_build_volume().center();
        if (shift_all(0) != 0 || shift_all(1) != 0) {
            // BBS: if multiple objects are selected, move them as a whole after copy
            if (i == 0) empty_cell_all = wxGetApp().plater()->canvas3D()->get_nearest_empty_cell({start_point(0), start_point(1)}, {bbox.size()(0)+1,bbox.size()(1)+1});
            auto instance_shift = src_object->instances.front()->get_offset() - src_objects[0]->instances.front()->get_offset();
            displacement = {shift_all.x() + empty_cell_all.x()+instance_shift.x(), shift_all.y() + empty_cell_all.y()+instance_shift.y(), start_point(2)};
        } else {
            // BBS: if only one object is copied, find an empty cell to put it
            auto start_offset = in_current ? src_object->instances.front()->get_offset() : plate->get_build_volume().center();
            auto point_offset = start_offset - start_point;
            auto empty_cell   = wxGetApp().plater()->canvas3D()->get_nearest_empty_cell({start_point(0), start_point(1)}, {bbox.size()(0)+1, bbox.size()(1)+1});
            displacement      = {empty_cell.x() + point_offset.x(), empty_cell.y() + point_offset.y(), start_offset(2)};
        }
        for (ModelInstance* inst : dst_object->instances) {
            inst->set_offset(displacement);
            //BBS init asssmble transformation
            Geometry::Transformation t = inst->get_transformation();
            inst->set_assemble_transformation(t);
        }
        object_idxs.push_back(m_model->objects.size() - 1);
#ifdef _DEBUG
      check_model_ids_validity(*m_model);
#endif /* _DEBUG */
    }
    wxGetApp().obj_list()->paste_objects_into_list(object_idxs);
#ifdef _DEBUG
    check_model_ids_validity(*m_model);
#endif /* _DEBUG */
}
References Slic3r::Model::add_object(), Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::check_model_ids_validity(), Slic3r::GUI::PartPlate::get_build_volume(), Slic3r::GUI::Selection::Clipboard::get_objects(), Slic3r::ModelObject::instance_convex_hull_bounding_box(), Slic3r::ModelObject::instances, Slic3r::GUI::PartPlate::intersects(), m_clipboard, m_model, Slic3r::BoundingBox3Base< PointClass >::merge(), Slic3r::Model::objects, and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by paste_from_clipboard().
paste_volumes_from_clipboard()
void Slic3r::GUI::Selection::paste_volumes_from_clipboard () private
{
#ifdef _DEBUG
    check_model_ids_validity(*m_model);
#endif /* _DEBUG */
    int dst_obj_idx = get_object_idx();
    if ((dst_obj_idx < 0) || ((int)m_model->objects.size() <= dst_obj_idx))
        return;
    ModelObject* dst_object = m_model->objects[dst_obj_idx];
    int dst_inst_idx = get_instance_idx();
    if ((dst_inst_idx < 0) || ((int)dst_object->instances.size() <= dst_inst_idx))
        return;
    ModelObject* src_object = m_clipboard.get_object(0);
    if (src_object != nullptr)
    {
        ModelInstance* dst_instance = dst_object->instances[dst_inst_idx];
        BoundingBoxf3 dst_instance_bb = dst_object->instance_bounding_box(dst_inst_idx);
        Transform3d src_matrix = src_object->instances[0]->get_transformation().get_matrix(true);
        Transform3d dst_matrix = dst_instance->get_transformation().get_matrix(true);
        bool from_same_object = (src_object->input_file == dst_object->input_file) && src_matrix.isApprox(dst_matrix);
        // used to keep relative position of multivolume selections when pasting from another object
        BoundingBoxf3 total_bb;
        ModelVolumePtrs volumes;
        for (ModelVolume* src_volume : src_object->volumes)
        {
            ModelVolume* dst_volume = dst_object->add_volume(*src_volume);
            dst_volume->set_new_unique_id();
            if (from_same_object)
            {
//                // if the volume comes from the same object, apply the offset in world system
//                double offset = wxGetApp().plater()->canvas3D()->get_size_proportional_to_max_bed_size(0.05);
//                dst_volume->translate(dst_matrix.inverse() * Vec3d(offset, offset, 0.0));
            }
            else
            {
                // if the volume comes from another object, apply the offset as done when adding modifiers
                // see ObjectList::load_generic_subobject()
                total_bb.merge(dst_volume->mesh().bounding_box().transformed(src_volume->get_matrix()));
            }
            volumes.push_back(dst_volume);
#ifdef _DEBUG
        check_model_ids_validity(*m_model);
#endif /* _DEBUG */
        }
        // keeps relative position of multivolume selections
        if (!from_same_object)
        {
            for (ModelVolume* v : volumes)
            {
                v->set_offset((v->get_offset() - total_bb.center()) + dst_matrix.inverse() * (Vec3d(dst_instance_bb.max(0), dst_instance_bb.min(1), dst_instance_bb.min(2)) + 0.5 * total_bb.size() - dst_instance->get_transformation().get_offset()));
            }
        }
        wxGetApp().obj_list()->paste_volumes_into_list(dst_obj_idx, volumes);
    }
#ifdef _DEBUG
    check_model_ids_validity(*m_model);
#endif /* _DEBUG */
}
References Slic3r::ModelObject::add_volume(), Slic3r::TriangleMesh::bounding_box(), Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::check_model_ids_validity(), get_instance_idx(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::GUI::Selection::Clipboard::get_object(), get_object_idx(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::ModelInstance::get_transformation(), Slic3r::ModelObject::input_file, Slic3r::ModelObject::instance_bounding_box(), Slic3r::ModelObject::instances, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::isApprox(), m_clipboard, m_model, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBox3Base< PointClass >::merge(), Slic3r::ModelVolume::mesh(), Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::Model::objects, Slic3r::ModelVolume::set_new_unique_id(), Slic3r::BoundingBox3Base< PointClass >::size(), Slic3r::BoundingBoxf3::transformed(), and Slic3r::ModelObject::volumes.
Referenced by paste_from_clipboard().
remove()
void Slic3r::GUI::Selection::remove (unsigned int volume_idx)
{
    if (!m_valid || (unsigned int)m_volumes->size() <= volume_idx)
        return;
    if (!contains_volume(volume_idx))
        return;
    wxGetApp().plater()->take_snapshot(std::string("Selection-Remove!"), UndoRedo::SnapshotType::Selection);
    GLVolume* volume = (*m_volumes)[volume_idx];
    switch (m_mode)
    {
    case Volume:
    {
        do_remove_volume(volume_idx);
        break;
    }
    case Instance:
    {
        do_remove_instance(volume->object_idx(), volume->instance_idx());
        break;
    }
    }
    update_type();
    this->set_bounding_boxes_dirty();
}
References contains_volume(), do_remove_instance(), do_remove_volume(), Instance, m_mode, m_valid, m_volumes, Slic3r::UndoRedo::Selection, set_bounding_boxes_dirty(), update_type(), and Volume.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
remove_all()
void Slic3r::GUI::Selection::remove_all ()
{
    if (!m_valid)
        return;
    if (is_empty())
        return;
// Not taking the snapshot with non-empty Redo stack will likely be more confusing than losing the Redo stack.
// Let's wait for user feedback.
//    if (!wxGetApp().plater()->can_redo())
        wxGetApp().plater()->take_snapshot(std::string("Selection-Remove All!"), UndoRedo::SnapshotType::Selection);
    m_mode = Instance;
    clear();
}
References clear(), Instance, is_empty(), m_mode, m_valid, and Slic3r::UndoRedo::Selection.
Referenced by Slic3r::GUI::GLCanvas3D::deselect_all(), and Slic3r::GUI::ObjectList::update_selections_on_canvas().
remove_curr_plate()
void Slic3r::GUI::Selection::remove_curr_plate ()
{
    if (!m_valid)
        return;
    PartPlate* plate = wxGetApp().plater()->get_partplate_list().get_curr_plate();
    if (plate->empty())
        return;
    wxGetApp().plater()->take_snapshot(std::string("Selection-Delete Curr Plate All"));
    m_mode = Instance;
    clear();
    for (int obj_idx = 0; obj_idx < m_model->objects.size(); obj_idx++) {
        if (plate && plate->contain_instance(obj_idx, 0)) {
            std::vector<unsigned int> volume_idxs = get_volume_idxs_from_object(obj_idx);
            do_add_volumes(volume_idxs);
        }
    }
    update_type();
    this->set_bounding_boxes_dirty();
    erase();
}
References clear(), Slic3r::GUI::PartPlate::contain_instance(), do_add_volumes(), Slic3r::GUI::PartPlate::empty(), erase(), get_volume_idxs_from_object(), Instance, m_mode, m_model, m_valid, Slic3r::Model::objects, set_bounding_boxes_dirty(), and update_type().
Referenced by Slic3r::GUI::GLCanvas3D::remove_curr_plate_all().
remove_instance()
void Slic3r::GUI::Selection::remove_instance (unsigned int object_idx, unsigned int instance_idx)
{
    if (!m_valid)
        return;
    wxGetApp().plater()->take_snapshot(std::string("Selection-Remove Instance"), UndoRedo::SnapshotType::Selection);
    do_remove_instance(object_idx, instance_idx);
    update_type();
    this->set_bounding_boxes_dirty();
}
References do_remove_instance(), m_valid, Slic3r::UndoRedo::Selection, set_bounding_boxes_dirty(), and update_type().
remove_object()
void Slic3r::GUI::Selection::remove_object (unsigned int object_idx)
{
    if (!m_valid)
        return;
    wxGetApp().plater()->take_snapshot(std::string("Selection-Remove Object"), UndoRedo::SnapshotType::Selection);
    do_remove_object(object_idx);
    update_type();
    this->set_bounding_boxes_dirty();
}
References do_remove_object(), m_valid, Slic3r::UndoRedo::Selection, set_bounding_boxes_dirty(), and update_type().
remove_volume()
void Slic3r::GUI::Selection::remove_volume (unsigned int object_idx, unsigned int volume_idx)
{
    if (!m_valid)
        return;
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i) {
        GLVolume* v = (*m_volumes)[i];
        if (v->object_idx() == (int)object_idx && v->volume_idx() == (int)volume_idx)
            do_remove_volume(i);
    }
    update_type();
    this->set_bounding_boxes_dirty();
}
References do_remove_volume(), int, m_valid, m_volumes, Slic3r::GLVolume::object_idx(), set_bounding_boxes_dirty(), update_type(), and Slic3r::GLVolume::volume_idx().
remove_volumes()
void Slic3r::GUI::Selection::remove_volumes (EMode mode, const std::vector< unsigned int > & volume_idxs)
{
    if (!m_valid)
        return;
    m_mode = mode;
    for (unsigned int i : volume_idxs) {
        if (i < (unsigned int)m_volumes->size())
            do_remove_volume(i);
    }
    update_type();
    this->set_bounding_boxes_dirty();
}
References do_remove_volume(), m_mode, m_valid, m_volumes, set_bounding_boxes_dirty(), and update_type().
Referenced by Slic3r::GUI::ObjectList::update_selections_on_canvas().
render()
void Slic3r::GUI::Selection::render (float scale_factor = 1.0) const
{
    if (!m_valid || is_empty())
        return;
    *const_cast<float*>(&m_scale_factor) = scale_factor;
    // render cumulative bounding box of selected volumes
    render_selected_volumes();
    render_synchronized_volumes();
}
References is_empty(), m_scale_factor, m_valid, render_selected_volumes(), and render_synchronized_volumes().
Referenced by Slic3r::GUI::GLCanvas3D::_render_selection().
render_bounding_box() [1/2]
void Slic3r::GUI::Selection::render_bounding_box (const BoundingBoxf3 & box, float * color) const private
{
    if (color == nullptr)
        return;
    Vec3f b_min = box.min.cast<float>();
    Vec3f b_max = box.max.cast<float>();
    Vec3f size = 0.2f * box.size().cast<float>();
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glColor3fv(color));
    glsafe(::glLineWidth(2.0f * m_scale_factor));
    ::glBegin(GL_LINES);
    ::glVertex3f(b_min(0), b_min(1), b_min(2)); ::glVertex3f(b_min(0) + size(0), b_min(1), b_min(2));
    ::glVertex3f(b_min(0), b_min(1), b_min(2)); ::glVertex3f(b_min(0), b_min(1) + size(1), b_min(2));
    ::glVertex3f(b_min(0), b_min(1), b_min(2)); ::glVertex3f(b_min(0), b_min(1), b_min(2) + size(2));
    ::glVertex3f(b_max(0), b_min(1), b_min(2)); ::glVertex3f(b_max(0) - size(0), b_min(1), b_min(2));
    ::glVertex3f(b_max(0), b_min(1), b_min(2)); ::glVertex3f(b_max(0), b_min(1) + size(1), b_min(2));
    ::glVertex3f(b_max(0), b_min(1), b_min(2)); ::glVertex3f(b_max(0), b_min(1), b_min(2) + size(2));
    ::glVertex3f(b_max(0), b_max(1), b_min(2)); ::glVertex3f(b_max(0) - size(0), b_max(1), b_min(2));
    ::glVertex3f(b_max(0), b_max(1), b_min(2)); ::glVertex3f(b_max(0), b_max(1) - size(1), b_min(2));
    ::glVertex3f(b_max(0), b_max(1), b_min(2)); ::glVertex3f(b_max(0), b_max(1), b_min(2) + size(2));
    ::glVertex3f(b_min(0), b_max(1), b_min(2)); ::glVertex3f(b_min(0) + size(0), b_max(1), b_min(2));
    ::glVertex3f(b_min(0), b_max(1), b_min(2)); ::glVertex3f(b_min(0), b_max(1) - size(1), b_min(2));
    ::glVertex3f(b_min(0), b_max(1), b_min(2)); ::glVertex3f(b_min(0), b_max(1), b_min(2) + size(2));
    ::glVertex3f(b_min(0), b_min(1), b_max(2)); ::glVertex3f(b_min(0) + size(0), b_min(1), b_max(2));
    ::glVertex3f(b_min(0), b_min(1), b_max(2)); ::glVertex3f(b_min(0), b_min(1) + size(1), b_max(2));
    ::glVertex3f(b_min(0), b_min(1), b_max(2)); ::glVertex3f(b_min(0), b_min(1), b_max(2) - size(2));
    ::glVertex3f(b_max(0), b_min(1), b_max(2)); ::glVertex3f(b_max(0) - size(0), b_min(1), b_max(2));
    ::glVertex3f(b_max(0), b_min(1), b_max(2)); ::glVertex3f(b_max(0), b_min(1) + size(1), b_max(2));
    ::glVertex3f(b_max(0), b_min(1), b_max(2)); ::glVertex3f(b_max(0), b_min(1), b_max(2) - size(2));
    ::glVertex3f(b_max(0), b_max(1), b_max(2)); ::glVertex3f(b_max(0) - size(0), b_max(1), b_max(2));
    ::glVertex3f(b_max(0), b_max(1), b_max(2)); ::glVertex3f(b_max(0), b_max(1) - size(1), b_max(2));
    ::glVertex3f(b_max(0), b_max(1), b_max(2)); ::glVertex3f(b_max(0), b_max(1), b_max(2) - size(2));
    ::glVertex3f(b_min(0), b_max(1), b_max(2)); ::glVertex3f(b_min(0) + size(0), b_max(1), b_max(2));
    ::glVertex3f(b_min(0), b_max(1), b_max(2)); ::glVertex3f(b_min(0), b_max(1) - size(1), b_max(2));
    ::glVertex3f(b_min(0), b_max(1), b_max(2)); ::glVertex3f(b_min(0), b_max(1), b_max(2) - size(2));
    glsafe(::glEnd());
}
References glsafe, m_scale_factor, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::BoundingBox3Base< PointClass >::size(), and size.
render_bounding_box() [2/2]
void Slic3r::GUI::Selection::render_bounding_box (const BoundingBoxf3 & box, float * color, float scale) inline
{
        m_scale_factor = scale;
        render_bounding_box(box, color);
    }
References m_scale_factor, render_bounding_box(), and scale().
Referenced by Slic3r::GUI::GLGizmoMeshBoolean::on_render(), render_bounding_box(), render_selected_volumes(), and render_synchronized_volumes().
render_selected_volumes()
void Slic3r::GUI::Selection::render_selected_volumes () const private
{
    float color[3] = { 1.0f, 1.0f, 1.0f };
    render_bounding_box(get_bounding_box(), color);
}
References get_bounding_box(), and render_bounding_box().
Referenced by render().
render_sidebar_hints()
void Slic3r::GUI::Selection::render_sidebar_hints (const std::string & sidebar_field, bool uniform_scale) const
{
    if (sidebar_field.empty())
        return;
    GLShaderProgram* shader = nullptr;
    if (!boost::starts_with(sidebar_field, "layer")) {
        shader = wxGetApp().get_shader("gouraud_light");
        if (shader == nullptr)
            return;
        shader->start_using();
        glsafe(::glClear(GL_DEPTH_BUFFER_BIT));
    }
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glPushMatrix());
    if (!boost::starts_with(sidebar_field, "layer")) {
        const Vec3d& center = get_bounding_box().center();
        // BBS
        if (is_single_full_instance()/* && !wxGetApp().obj_manipul()->get_world_coordinates()*/) {
            glsafe(::glTranslated(center(0), center(1), center(2)));
            if (!boost::starts_with(sidebar_field, "position")) {
                Transform3d orient_matrix = Transform3d::Identity();
                if (boost::starts_with(sidebar_field, "scale"))
                    orient_matrix = (*m_volumes)[*m_list.begin()]->get_instance_transformation().get_matrix(true, false, true, true);
                else if (boost::starts_with(sidebar_field, "rotation")) {
                    if (boost::ends_with(sidebar_field, "x"))
                        orient_matrix = (*m_volumes)[*m_list.begin()]->get_instance_transformation().get_matrix(true, false, true, true);
                    else if (boost::ends_with(sidebar_field, "y")) {
                        const Vec3d& rotation = (*m_volumes)[*m_list.begin()]->get_instance_transformation().get_rotation();
                        if (rotation(0) == 0.0)
                            orient_matrix = (*m_volumes)[*m_list.begin()]->get_instance_transformation().get_matrix(true, false, true, true);
                        else
                            orient_matrix.rotate(Eigen::AngleAxisd(rotation(2), Vec3d::UnitZ()));
                    }
                }
                glsafe(::glMultMatrixd(orient_matrix.data()));
            }
        } else if (is_single_volume() || is_single_modifier()) {
            glsafe(::glTranslated(center(0), center(1), center(2)));
            Transform3d orient_matrix = (*m_volumes)[*m_list.begin()]->get_instance_transformation().get_matrix(true, false, true, true);
            if (!boost::starts_with(sidebar_field, "position"))
                orient_matrix = orient_matrix * (*m_volumes)[*m_list.begin()]->get_volume_transformation().get_matrix(true, false, true, true);
            glsafe(::glMultMatrixd(orient_matrix.data()));
        } else {
            glsafe(::glTranslated(center(0), center(1), center(2)));
            if (requires_local_axes()) {
                const Transform3d orient_matrix = (*m_volumes)[*m_list.begin()]->get_instance_transformation().get_matrix(true, false, true, true);
                glsafe(::glMultMatrixd(orient_matrix.data()));
            }
        }
    }
    if (boost::starts_with(sidebar_field, "position"))
        render_sidebar_position_hints(sidebar_field);
    else if (boost::starts_with(sidebar_field, "rotation"))
        render_sidebar_rotation_hints(sidebar_field);
    else if (boost::starts_with(sidebar_field, "scale") || boost::starts_with(sidebar_field, "size"))
        //BBS: GUI refactor: add uniform_scale from gizmo
        render_sidebar_scale_hints(sidebar_field, uniform_scale);
    else if (boost::starts_with(sidebar_field, "layer"))
        render_sidebar_layers_hints(sidebar_field);
    glsafe(::glPopMatrix());
    if (!boost::starts_with(sidebar_field, "layer"))
        shader->stop_using();
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), glsafe, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by Slic3r::GUI::GLCanvas3D::_render_selection_sidebar_hints().
render_sidebar_layers_hints()
void Slic3r::GUI::Selection::render_sidebar_layers_hints (const std::string & sidebar_field) const private
{
    static const double Margin = 10.0;
    std::string field = sidebar_field;
    // extract max_z
    std::string::size_type pos = field.rfind("_");
    if (pos == std::string::npos)
        return;
    double max_z = string_to_double_decimal_point(field.substr(pos + 1));
    // extract min_z
    field = field.substr(0, pos);
    pos = field.rfind("_");
    if (pos == std::string::npos)
        return;
    const double min_z = string_to_double_decimal_point(field.substr(pos + 1));
    // extract type
    field = field.substr(0, pos);
    pos = field.rfind("_");
    if (pos == std::string::npos)
        return;
    const int type = std::stoi(field.substr(pos + 1));
    const BoundingBoxf3& box = get_bounding_box();
    const float min_x = box.min(0) - Margin;
    const float max_x = box.max(0) + Margin;
    const float min_y = box.min(1) - Margin;
    const float max_y = box.max(1) + Margin;
    // view dependend order of rendering to keep correct transparency
    bool camera_on_top = wxGetApp().plater()->get_camera().is_looking_downward();
    const float z1 = camera_on_top ? min_z : max_z;
    const float z2 = camera_on_top ? max_z : min_z;
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glDisable(GL_CULL_FACE));
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    ::glBegin(GL_QUADS);
    if ((camera_on_top && type == 1) || (!camera_on_top && type == 2))
        ::glColor4f(0.0f, 174.0f / 255.0f, 66.0f / 255.0f, 1.0f);
    else
        ::glColor4f(0.8f, 0.8f, 0.8f, 0.5f);
    ::glVertex3f(min_x, min_y, z1);
    ::glVertex3f(max_x, min_y, z1);
    ::glVertex3f(max_x, max_y, z1);
    ::glVertex3f(min_x, max_y, z1);
    glsafe(::glEnd());
    ::glBegin(GL_QUADS);
    if ((camera_on_top && type == 2) || (!camera_on_top && type == 1))
        ::glColor4f(0.0f, 174.0f / 255.0f, 66.0f / 255.0f, 1.0f);
    else
        ::glColor4f(0.8f, 0.8f, 0.8f, 0.5f);
    ::glVertex3f(min_x, min_y, z2);
    ::glVertex3f(max_x, min_y, z2);
    ::glVertex3f(max_x, max_y, z2);
    ::glVertex3f(min_x, max_y, z2);
    glsafe(::glEnd());
    glsafe(::glEnable(GL_CULL_FACE));
    glsafe(::glDisable(GL_BLEND));
}
References get_bounding_box(), glsafe, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, and Slic3r::string_to_double_decimal_point().
render_sidebar_position_hints()
void Slic3r::GUI::Selection::render_sidebar_position_hints (const std::string & sidebar_field) const private
{
    if (boost::ends_with(sidebar_field, "x")) {
        glsafe(::glRotated(-90.0, 0.0, 0.0, 1.0));
        const_cast<GLModel*>(&m_arrow)->set_color(-1, get_color(X));
        m_arrow.render();
    }
    else if (boost::ends_with(sidebar_field, "y")) {
        const_cast<GLModel*>(&m_arrow)->set_color(-1, get_color(Y));
        m_arrow.render();
    }
    else if (boost::ends_with(sidebar_field, "z")) {
        glsafe(::glRotated(90.0, 1.0, 0.0, 0.0));
        const_cast<GLModel*>(&m_arrow)->set_color(-1, get_color(Z));
        m_arrow.render();
    }
}
References Slic3r::GUI::get_color(), glsafe, m_arrow, Slic3r::GUI::GLModel::render(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
render_sidebar_rotation_hints()
void Slic3r::GUI::Selection::render_sidebar_rotation_hints (const std::string & sidebar_field) const private
{
    auto render_sidebar_rotation_hint = [this]() {
        m_curved_arrow.render();
        glsafe(::glRotated(180.0, 0.0, 0.0, 1.0));
        m_curved_arrow.render();
    };
    if (boost::ends_with(sidebar_field, "x")) {
        glsafe(::glRotated(90.0, 0.0, 1.0, 0.0));
        const_cast<GLModel*>(&m_curved_arrow)->set_color(-1, get_color(X));
        render_sidebar_rotation_hint();
    }
    else if (boost::ends_with(sidebar_field, "y")) {
        glsafe(::glRotated(-90.0, 1.0, 0.0, 0.0));
        const_cast<GLModel*>(&m_curved_arrow)->set_color(-1, get_color(Y));
        render_sidebar_rotation_hint();
    }
    else if (boost::ends_with(sidebar_field, "z")) {
        const_cast<GLModel*>(&m_curved_arrow)->set_color(-1, get_color(Z));
        render_sidebar_rotation_hint();
    }
}
References Slic3r::GUI::get_color(), glsafe, m_curved_arrow, Slic3r::GUI::GLModel::render(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
render_sidebar_scale_hints()
void Slic3r::GUI::Selection::render_sidebar_scale_hints (const std::string & sidebar_field, bool gizmo_uniform_scale) const private
{
    // BBS
    //bool uniform_scale = requires_uniform_scale() || wxGetApp().obj_manipul()->get_uniform_scaling();
    bool uniform_scale = requires_uniform_scale() || gizmo_uniform_scale;
    auto render_sidebar_scale_hint = [this, uniform_scale](Axis axis) {
        const_cast<GLModel*>(&m_arrow)->set_color(-1, uniform_scale ? UNIFORM_SCALE_COLOR : get_color(axis));
        GLShaderProgram* shader = wxGetApp().get_current_shader();
        if (shader != nullptr)
            shader->set_uniform("emission_factor", 0.0f);
        glsafe(::glTranslated(0.0, 5.0, 0.0));
        m_arrow.render();
        glsafe(::glTranslated(0.0, -10.0, 0.0));
        glsafe(::glRotated(180.0, 0.0, 0.0, 1.0));
        m_arrow.render();
    };
    if (boost::ends_with(sidebar_field, "x") || uniform_scale) {
        glsafe(::glPushMatrix());
        glsafe(::glRotated(-90.0, 0.0, 0.0, 1.0));
        render_sidebar_scale_hint(X);
        glsafe(::glPopMatrix());
    }
    if (boost::ends_with(sidebar_field, "y") || uniform_scale) {
        glsafe(::glPushMatrix());
        render_sidebar_scale_hint(Y);
        glsafe(::glPopMatrix());
    }
    if (boost::ends_with(sidebar_field, "z") || uniform_scale) {
        glsafe(::glPushMatrix());
        glsafe(::glRotated(90.0, 1.0, 0.0, 0.0));
        render_sidebar_scale_hint(Z);
        glsafe(::glPopMatrix());
    }
}
References Slic3r::GUI::get_color(), glsafe, m_arrow, Slic3r::GUI::GLModel::render(), requires_uniform_scale(), Slic3r::GLShaderProgram::set_uniform(), UNIFORM_SCALE_COLOR, Slic3r::X, Slic3r::Y, and Slic3r::Z.
render_synchronized_volumes()
void Slic3r::GUI::Selection::render_synchronized_volumes () const private
{
    if (m_mode == Instance)
        return;
    float color[3] = { 1.0f, 1.0f, 0.0f };
    for (unsigned int i : m_list) {
        const GLVolume* volume = (*m_volumes)[i];
        int object_idx = volume->object_idx();
        int volume_idx = volume->volume_idx();
        for (unsigned int j = 0; j < (unsigned int)m_volumes->size(); ++j) {
            if (i == j)
                continue;
            const GLVolume* v = (*m_volumes)[j];
            if (v->object_idx() != object_idx || v->volume_idx() != volume_idx)
                continue;
            render_bounding_box(v->transformed_convex_hull_bounding_box(), color);
        }
    }
}
References Instance, int, m_list, m_mode, m_volumes, Slic3r::GLVolume::object_idx(), render_bounding_box(), Slic3r::GLVolume::transformed_convex_hull_bounding_box(), and Slic3r::GLVolume::volume_idx().
Referenced by render().
requires_local_axes()
bool Slic3r::GUI::Selection::requires_local_axes () const
{
    return (m_mode == Volume) && is_from_single_instance();
}
References is_from_single_instance(), m_mode, and Volume.
Referenced by Slic3r::GUI::GizmoObjectManipulation::change_position_value(), Slic3r::GUI::GizmoObjectManipulation::change_rotation_value(), Slic3r::GUI::GLGizmoRotate::mouse_position_in_local_plane(), and Slic3r::GUI::GLGizmoRotate::transform_to_local().
requires_uniform_scale()
bool Slic3r::GUI::Selection::requires_uniform_scale () const
{
    if (is_single_full_instance() || is_single_modifier() || is_single_volume())
        return false;
    return true;
}
References is_single_full_instance(), is_single_modifier(), and is_single_volume().
Referenced by render_sidebar_scale_hints().
rotate()
void Slic3r::GUI::Selection::rotate (const Vec3d & rotation, TransformationType transformation_type)
{
    if (!m_valid)
        return;
    // Only relative rotation values are allowed in the world coordinate system.
    assert(!transformation_type.world() || transformation_type.relative());
    if (!is_wipe_tower()) {
        int rot_axis_max = 0;
        if (rotation.isApprox(Vec3d::Zero())) {
            for (unsigned int i : m_list) {
                GLVolume &v = *(*m_volumes)[i];
                if (m_mode == Instance) {
                    v.set_instance_rotation(m_cache.volumes_data[i].get_instance_rotation());
                    v.set_instance_offset(m_cache.volumes_data[i].get_instance_position());
                }
                else if (m_mode == Volume) {
                    v.set_volume_rotation(m_cache.volumes_data[i].get_volume_rotation());
                    v.set_volume_offset(m_cache.volumes_data[i].get_volume_position());
                }
            }
        }
        else { // this is not the wipe tower
            //FIXME this does not work for absolute rotations (transformation_type.absolute() is true)
            rotation.cwiseAbs().maxCoeff(&rot_axis_max);
//            if (single instance or single volume)
                // Rotate around center , if only a single object or volume
//                transformation_type.set_independent();
            // For generic rotation, we want to rotate the first volume in selection, and then to synchronize the other volumes with it.
            std::vector<int> object_instance_first(m_model->objects.size(), -1);
            auto rotate_instance = [this, &rotation, &object_instance_first, rot_axis_max, transformation_type](GLVolume &volume, int i) {
                const int first_volume_idx = object_instance_first[volume.object_idx()];
                if (rot_axis_max != 2 && first_volume_idx != -1) {
                    // Generic rotation, but no rotation around the Z axis.
                    // Always do a local rotation (do not consider the selection to be a rigid body).
                    assert(is_approx(rotation.z(), 0.0));
                    const GLVolume &first_volume = *(*m_volumes)[first_volume_idx];
                    const Vec3d    &rotation = first_volume.get_instance_rotation();
                    const double z_diff = Geometry::rotation_diff_z(m_cache.volumes_data[first_volume_idx].get_instance_rotation(), m_cache.volumes_data[i].get_instance_rotation());
                    volume.set_instance_rotation(Vec3d(rotation(0), rotation(1), rotation(2) + z_diff));
                }
                else {
                    // extracts rotations from the composed transformation
                    Vec3d new_rotation = transformation_type.world() ?
                        Geometry::extract_euler_angles(Geometry::assemble_transform(Vec3d::Zero(), rotation) * m_cache.volumes_data[i].get_instance_rotation_matrix()) :
                        transformation_type.absolute() ? rotation : rotation + m_cache.volumes_data[i].get_instance_rotation();
                    if (rot_axis_max == 2 && transformation_type.joint()) {
                        // Only allow rotation of multiple instances as a single rigid body when rotating around the Z axis.
                        const double z_diff = Geometry::rotation_diff_z(m_cache.volumes_data[i].get_instance_rotation(), new_rotation);
                        volume.set_instance_offset(m_cache.dragging_center + Eigen::AngleAxisd(z_diff, Vec3d::UnitZ()) * (m_cache.volumes_data[i].get_instance_position() - m_cache.dragging_center));
                    }
                    volume.set_instance_rotation(new_rotation);
                    object_instance_first[volume.object_idx()] = i;
                }
            };
            for (unsigned int i : m_list) {
                GLVolume &v = *(*m_volumes)[i];
                if (is_single_full_instance())
                    rotate_instance(v, i);
                else if (is_single_volume() || is_single_modifier()) {
                    if (transformation_type.independent())
                        v.set_volume_rotation(m_cache.volumes_data[i].get_volume_rotation() + rotation);
                    else {
                        const Transform3d m = Geometry::assemble_transform(Vec3d::Zero(), rotation);
                        const Vec3d new_rotation = Geometry::extract_euler_angles(m * m_cache.volumes_data[i].get_volume_rotation_matrix());
                        v.set_volume_rotation(new_rotation);
                    }
                }
                else
                {
                    if (m_mode == Instance)
                        rotate_instance(v, i);
                    else if (m_mode == Volume) {
                        // extracts rotations from the composed transformation
                        Transform3d m = Geometry::assemble_transform(Vec3d::Zero(), rotation);
                        Vec3d new_rotation = Geometry::extract_euler_angles(m * m_cache.volumes_data[i].get_volume_rotation_matrix());
                        if (transformation_type.joint()) {
                            const Vec3d local_pivot = m_cache.volumes_data[i].get_instance_full_matrix().inverse() * m_cache.dragging_center;
                            const Vec3d offset = m * (m_cache.volumes_data[i].get_volume_position() - local_pivot);
                            v.set_volume_offset(local_pivot + offset);
                        }
                        v.set_volume_rotation(new_rotation);
                    }
                }
            }
        }
    #if !DISABLE_INSTANCES_SYNCH
        if (m_mode == Instance)
            synchronize_unselected_instances((rot_axis_max == 2) ? SYNC_ROTATION_NONE : SYNC_ROTATION_GENERAL);
        else if (m_mode == Volume)
            synchronize_unselected_volumes();
    #endif // !DISABLE_INSTANCES_SYNCH
    }
    else { // it's the wipe tower that's selected and being rotated
        GLVolume& volume = *((*m_volumes)[*m_list.begin()]); // the wipe tower is always alone in the selection
        // make sure the wipe tower rotates around its center, not origin
        // we can assume that only Z rotation changes
        const Vec3d center_local = volume.transformed_bounding_box().center() - volume.get_volume_offset();
        const Vec3d center_local_new = Eigen::AngleAxisd(rotation(2)-volume.get_volume_rotation()(2), Vec3d(0.0, 0.0, 1.0)) * center_local;
        volume.set_volume_rotation(rotation);
        volume.set_volume_offset(volume.get_volume_offset() + center_local - center_local_new);
    }
    set_bounding_boxes_dirty();
    wxGetApp().plater()->canvas3D()->requires_check_outside_state();
}
References Slic3r::GUI::TransformationType::absolute(), Slic3r::Geometry::assemble_transform(), Slic3r::GUI::Selection::Cache::dragging_center, Slic3r::Geometry::extract_euler_angles(), Slic3r::GLVolume::get_instance_rotation(), Slic3r::GUI::TransformationType::independent(), Instance, Slic3r::is_approx(), is_single_full_instance(), is_single_modifier(), is_single_volume(), is_wipe_tower(), Slic3r::GUI::TransformationType::joint(), m_cache, m_list, m_mode, m_model, m_valid, Slic3r::Model::objects, Slic3r::offset(), Slic3r::GUI::TransformationType::relative(), Slic3r::Geometry::rotation_diff_z(), set_bounding_boxes_dirty(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_rotation(), SYNC_ROTATION_GENERAL, SYNC_ROTATION_NONE, synchronize_unselected_instances(), synchronize_unselected_volumes(), Volume, Slic3r::GUI::Selection::Cache::volumes_data, and Slic3r::GUI::TransformationType::world().
Referenced by Slic3r::GUI::GizmoObjectManipulation::change_rotation_value(), and Slic3r::GUI::GLCanvas3D::on_key().
scale()
void Slic3r::GUI::Selection::scale (const Vec3d & scale, TransformationType transformation_type)
{
    if (!m_valid)
        return;
    for (unsigned int i : m_list) {
        GLVolume &v = *(*m_volumes)[i];
        if (is_single_full_instance()) {
            if (transformation_type.relative()) {
                Transform3d m = Geometry::assemble_transform(Vec3d::Zero(), Vec3d::Zero(), scale);
                Eigen::Matrix<double, 3, 3, Eigen::DontAlign> new_matrix = (m * m_cache.volumes_data[i].get_instance_scale_matrix()).matrix().block(0, 0, 3, 3);
                // extracts scaling factors from the composed transformation
                Vec3d new_scale(new_matrix.col(0).norm(), new_matrix.col(1).norm(), new_matrix.col(2).norm());
                if (transformation_type.joint())
                    v.set_instance_offset(m_cache.dragging_center + m * (m_cache.volumes_data[i].get_instance_position() - m_cache.dragging_center));
                v.set_instance_scaling_factor(new_scale);
            }
            else {
                if (transformation_type.world() && (std::abs(scale.x() - scale.y()) > EPSILON || std::abs(scale.x() - scale.z()) > EPSILON)) {
                    // Non-uniform scaling. Transform the scaling factors into the local coordinate system.
                    // This is only possible, if the instance rotation is mulitples of ninety degrees.
                    assert(Geometry::is_rotation_ninety_degrees(v.get_instance_rotation()));
                    v.set_instance_scaling_factor((v.get_instance_transformation().get_matrix(true, false, true, true).matrix().block<3, 3>(0, 0).transpose() * scale).cwiseAbs());
                }
                else
                    v.set_instance_scaling_factor(scale);
            }
            // update the instance assemble transform
            ModelObject* object = m_model->objects[v.object_idx()];
            Geometry::Transformation assemble_transform = object->instances[v.instance_idx()]->get_assemble_transformation();
            assemble_transform.set_scaling_factor(v.get_instance_scaling_factor());
            object->instances[v.instance_idx()]->set_assemble_transformation(assemble_transform);
        }
        else if (is_single_volume() || is_single_modifier())
            v.set_volume_scaling_factor(scale);
        else {
            Transform3d m = Geometry::assemble_transform(Vec3d::Zero(), Vec3d::Zero(), scale);
            if (m_mode == Instance) {
                Eigen::Matrix<double, 3, 3, Eigen::DontAlign> new_matrix = (m * m_cache.volumes_data[i].get_instance_scale_matrix()).matrix().block(0, 0, 3, 3);
                // extracts scaling factors from the composed transformation
                Vec3d new_scale(new_matrix.col(0).norm(), new_matrix.col(1).norm(), new_matrix.col(2).norm());
                if (transformation_type.joint())
                    v.set_instance_offset(m_cache.dragging_center + m * (m_cache.volumes_data[i].get_instance_position() - m_cache.dragging_center));
                v.set_instance_scaling_factor(new_scale);
            }
            else if (m_mode == Volume) {
                Eigen::Matrix<double, 3, 3, Eigen::DontAlign> new_matrix = (m * m_cache.volumes_data[i].get_volume_scale_matrix()).matrix().block(0, 0, 3, 3);
                // extracts scaling factors from the composed transformation
                Vec3d new_scale(new_matrix.col(0).norm(), new_matrix.col(1).norm(), new_matrix.col(2).norm());
                if (transformation_type.joint()) {
                    Vec3d offset = m * (m_cache.volumes_data[i].get_volume_position() + m_cache.volumes_data[i].get_instance_position() - m_cache.dragging_center);
                    v.set_volume_offset(m_cache.dragging_center - m_cache.volumes_data[i].get_instance_position() + offset);
                }
                v.set_volume_scaling_factor(new_scale);
            }
        }
    }
#if !DISABLE_INSTANCES_SYNCH
    if (m_mode == Instance)
        synchronize_unselected_instances(SYNC_ROTATION_NONE);
    else if (m_mode == Volume)
        synchronize_unselected_volumes();
#endif // !DISABLE_INSTANCES_SYNCH
    ensure_on_bed();
    set_bounding_boxes_dirty();
    wxGetApp().plater()->canvas3D()->requires_check_outside_state();
}
References Slic3r::Geometry::assemble_transform(), Slic3r::GUI::Selection::Cache::dragging_center, ensure_on_bed(), EPSILON, Slic3r::GLVolume::get_instance_rotation(), Slic3r::GLVolume::get_instance_scaling_factor(), Slic3r::GLVolume::get_instance_transformation(), Slic3r::Geometry::Transformation::get_matrix(), Instance, Slic3r::GLVolume::instance_idx(), Slic3r::Geometry::is_rotation_ninety_degrees(), is_single_full_instance(), is_single_modifier(), is_single_volume(), Slic3r::GUI::TransformationType::joint(), m_cache, m_list, m_mode, m_model, m_valid, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, Slic3r::offset(), Slic3r::GUI::TransformationType::relative(), scale(), set_bounding_boxes_dirty(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_scaling_factor(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_scaling_factor(), SYNC_ROTATION_NONE, synchronize_unselected_instances(), synchronize_unselected_volumes(), Volume, Slic3r::GUI::Selection::Cache::volumes_data, and Slic3r::GUI::TransformationType::world().
Referenced by Slic3r::GUI::GizmoObjectManipulation::do_scale(), render_bounding_box(), scale(), and scale_to_fit_print_volume().
scale_to_fit_print_volume()
void Slic3r::GUI::Selection::scale_to_fit_print_volume (const DynamicPrintConfig & config)
{
    if (is_empty() || m_mode == Volume)
        return;
    // adds 1/100th of a mm on all sides to avoid false out of print volume detections due to floating-point roundings
    Vec3d box_size = get_bounding_box().size() + 0.01 * Vec3d::Ones();
    const ConfigOptionPoints* opt = dynamic_cast<const ConfigOptionPoints*>(config.option("printable_area"));
    if (opt != nullptr) {
        BoundingBox bed_box_2D = get_extents(Polygon::new_scale(opt->values));
        BoundingBoxf3 print_volume({ unscale<double>(bed_box_2D.min(0)), unscale<double>(bed_box_2D.min(1)), 0.0 }, { unscale<double>(bed_box_2D.max(0)), unscale<double>(bed_box_2D.max(1)), config.opt_float("printable_height") });
        Vec3d print_volume_size = print_volume.size();
        double sx = (box_size(0) != 0.0) ? print_volume_size(0) / box_size(0) : 0.0;
        double sy = (box_size(1) != 0.0) ? print_volume_size(1) / box_size(1) : 0.0;
        double sz = (box_size(2) != 0.0) ? print_volume_size(2) / box_size(2) : 0.0;
        if (sx != 0.0 && sy != 0.0 && sz != 0.0)
        {
            double s = std::min(sx, std::min(sy, sz));
            if (s != 1.0) {
                wxGetApp().plater()->take_snapshot("Scale To Fit");
                TransformationType type;
                type.set_world();
                type.set_relative();
                type.set_joint();
                // apply scale
                start_dragging();
                scale(s * Vec3d::Ones(), type);
                wxGetApp().plater()->canvas3D()->do_scale(""); // avoid storing another snapshot
                // center selection on print bed
                start_dragging();
                translate(print_volume.center() - get_bounding_box().center());
                wxGetApp().plater()->canvas3D()->do_move(""); // avoid storing another snapshot
                // BBS
                //wxGetApp().obj_manipul()->set_dirty();
            }
        }
    }
}
References center(), Slic3r::BoundingBox3Base< PointClass >::center(), get_bounding_box(), Slic3r::get_extents(), is_empty(), m_mode, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::Polygon::new_scale(), Slic3r::DynamicConfig::opt_float(), Slic3r::ConfigBase::option(), scale(), Slic3r::GUI::TransformationType::set_joint(), Slic3r::GUI::TransformationType::set_relative(), Slic3r::GUI::TransformationType::set_world(), Slic3r::BoundingBox3Base< PointClass >::size(), start_dragging(), translate(), Slic3r::ConfigOptionVector< T >::values, and Volume.
set_bounding_boxes_dirty()
void Slic3r::GUI::Selection::set_bounding_boxes_dirty () inline private
{ m_bounding_box.reset(); m_unscaled_instance_bounding_box.reset(); m_scaled_instance_bounding_box.reset(); }
References m_bounding_box, m_scaled_instance_bounding_box, and m_unscaled_instance_bounding_box.
Referenced by Selection(), add(), add_all(), add_curr_plate(), add_instance(), add_object(), add_volume(), add_volumes(), clear(), flattening_rotate(), instances_changed(), mirror(), move_to_center(), remove(), remove_curr_plate(), remove_instance(), remove_object(), remove_volume(), remove_volumes(), rotate(), scale(), set_deserialized(), translate(), translate(), translate(), and volumes_changed().
set_caches()
void Slic3r::GUI::Selection::set_caches () private
{
    m_cache.volumes_data.clear();
    m_cache.sinking_volumes.clear();
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++i) {
        const GLVolume& v = *(*m_volumes)[i];
        m_cache.volumes_data.emplace(i, VolumeCache(v.get_volume_transformation(), v.get_instance_transformation()));
        if (v.is_sinking())
            m_cache.sinking_volumes.push_back(i);
    }
    m_cache.dragging_center = get_bounding_box().center();
}
References Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::GUI::Selection::Cache::dragging_center, get_bounding_box(), Slic3r::GLVolume::get_instance_transformation(), Slic3r::GLVolume::get_volume_transformation(), int, Slic3r::GLVolume::is_sinking(), m_cache, m_volumes, Slic3r::GUI::Selection::Cache::sinking_volumes, and Slic3r::GUI::Selection::Cache::volumes_data.
Referenced by move_to_center(), and start_dragging().
set_deserialized()
void Slic3r::GUI::Selection::set_deserialized (EMode mode, const std::vector< std::pair< size_t, size_t > > & volumes_and_instances)
{
    if (! m_valid)
        return;
    m_mode = mode;
    for (unsigned int i : m_list)
        (*m_volumes)[i]->selected = false;
    m_list.clear();
    for (unsigned int i = 0; i < (unsigned int)m_volumes->size(); ++ i)
    if (std::binary_search(volumes_and_instances.begin(), volumes_and_instances.end(), (*m_volumes)[i]->geometry_id))
      do_add_volume(i);
    update_type();
    set_bounding_boxes_dirty();
}
References do_add_volume(), int, m_list, m_mode, m_valid, m_volumes, set_bounding_boxes_dirty(), and update_type().
set_enabled()
void Slic3r::GUI::Selection::set_enabled (bool enable) inline
{ m_enabled = enable; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::enable_selection().
set_mode()
void Slic3r::GUI::Selection::set_mode (EMode mode) inline
{ m_mode = mode; }
References m_mode.
Referenced by Slic3r::GUI::GLCanvas3D::enable_picking().
set_model()
void Slic3r::GUI::Selection::set_model (Model * model)
{
    m_model = model;
    update_valid();
}
References m_model, and update_valid().
Referenced by Slic3r::GUI::GLCanvas3D::set_model().
set_printable()
void Slic3r::GUI::Selection::set_printable (bool printable)
{
    if (!m_valid)
        return;
    std::set<std::pair<int, int>> instances_idxs;
    for (ObjectIdxsToInstanceIdxsMap::iterator obj_it = m_cache.content.begin(); obj_it != m_cache.content.end(); ++obj_it)
    {
        for (InstanceIdxsList::reverse_iterator inst_it = obj_it->second.rbegin(); inst_it != obj_it->second.rend(); ++inst_it)
        {
            instances_idxs.insert(std::make_pair(obj_it->first, *inst_it));
        }
    }
    std::string snapshot_text = (boost::format("%1%") % (printable ? "Set Selection Printable" : "Set Selection Unprintable")).str();
    wxGetApp().plater()->take_snapshot(snapshot_text);
    // set printable value for all instances in object
    for (const std::pair<int, int>& i : instances_idxs)
    {
        ModelObject* object = m_model->objects[i.first];
        for (auto inst : object->instances)
            inst->printable = printable;
        wxGetApp().obj_list()->update_printable_state(i.first, i.second);
        //update printable state on canvas
        wxGetApp().plater()->canvas3D()->update_instance_printable_state_for_object((size_t)i.first);
    }
    // update scene
    wxGetApp().plater()->update();
}
References Slic3r::GUI::Selection::Cache::content, m_cache, m_model, m_valid, and Slic3r::Model::objects.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_set_printable().
set_volume_selection_mode()
void Slic3r::GUI::Selection::set_volume_selection_mode (EMode mode) inline
{ if (!m_volume_selection_locked) m_volume_selection_mode = mode; }
References m_volume_selection_locked, and m_volume_selection_mode.
Referenced by Slic3r::GUI::AssembleView::init(), and Slic3r::GUI::GLCanvas3D::on_mouse().
set_volumes()
void Slic3r::GUI::Selection::set_volumes (GLVolumePtrs * volumes)
{
    m_volumes = volumes;
    update_valid();
}
References m_volumes, and update_valid().
Referenced by Slic3r::GUI::GLCanvas3D::GLCanvas3D().
start_dragging()
void Slic3r::GUI::Selection::start_dragging ()
{
    if (!m_valid)
        return;
    m_dragging = true;
    set_caches();
}
References m_dragging, m_valid, and set_caches().
Referenced by Slic3r::GUI::GizmoObjectManipulation::change_position_value(), Slic3r::GUI::GizmoObjectManipulation::change_rotation_value(), Slic3r::GUI::GizmoObjectManipulation::do_scale(), Slic3r::GUI::GLCanvas3D::on_key(), Slic3r::GUI::GLCanvas3D::on_mouse(), and scale_to_fit_print_volume().
stop_dragging()
void Slic3r::GUI::Selection::stop_dragging () inline
{ m_dragging = false; }
References m_dragging.
Referenced by Slic3r::GUI::GLCanvas3D::on_key(), and Slic3r::GUI::GLCanvas3D::on_mouse().
synchronize_unselected_instances()
void Slic3r::GUI::Selection::synchronize_unselected_instances (SyncRotationType sync_rotation_type)
{
    std::set<unsigned int> done;  // prevent processing volumes twice
    done.insert(m_list.begin(), m_list.end());
    for (unsigned int i : m_list) {
        if (done.size() == m_volumes->size())
            break;
        const GLVolume* volume = (*m_volumes)[i];
        const int object_idx = volume->object_idx();
        if (object_idx >= 1000)
            continue;
        const int instance_idx = volume->instance_idx();
        const Vec3d& rotation = volume->get_instance_rotation();
        const Vec3d& scaling_factor = volume->get_instance_scaling_factor();
        const Vec3d& mirror = volume->get_instance_mirror();
        // Process unselected instances.
        for (unsigned int j = 0; j < (unsigned int)m_volumes->size(); ++j) {
            if (done.size() == m_volumes->size())
                break;
            if (done.find(j) != done.end())
                continue;
            GLVolume* v = (*m_volumes)[j];
            if (v->object_idx() != object_idx || v->instance_idx() == instance_idx)
                continue;
            assert(is_rotation_xy_synchronized(m_cache.volumes_data[i].get_instance_rotation(), m_cache.volumes_data[j].get_instance_rotation()));
            switch (sync_rotation_type) {
            case SYNC_ROTATION_NONE: {
                // z only rotation -> synch instance z
                // The X,Y rotations should be synchronized from start to end of the rotation.
                assert(is_rotation_xy_synchronized(rotation, v->get_instance_rotation()));
                if (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() != ptSLA)
                    v->set_instance_offset(Z, volume->get_instance_offset().z());
                break;
            }
            case SYNC_ROTATION_GENERAL:
                // generic rotation -> update instance z with the delta of the rotation.
                const double z_diff = Geometry::rotation_diff_z(m_cache.volumes_data[i].get_instance_rotation(), m_cache.volumes_data[j].get_instance_rotation());
                v->set_instance_rotation({ rotation.x(), rotation.y(), rotation.z() + z_diff });
                break;
            }
            v->set_instance_scaling_factor(scaling_factor);
            v->set_instance_mirror(mirror);
            done.insert(j);
        }
    }
#ifndef NDEBUG
    verify_instances_rotation_synchronized(*m_model, *m_volumes);
#endif /* NDEBUG */
}
References Slic3r::GLVolume::get_instance_rotation(), Slic3r::GLVolume::instance_idx(), int, Slic3r::GUI::is_rotation_xy_synchronized(), m_cache, m_list, m_model, m_volumes, mirror(), Slic3r::GLVolume::object_idx(), Slic3r::ptSLA, Slic3r::Geometry::rotation_diff_z(), Slic3r::GLVolume::set_instance_mirror(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_instance_rotation(), Slic3r::GLVolume::set_instance_scaling_factor(), SYNC_ROTATION_GENERAL, SYNC_ROTATION_NONE, Slic3r::GUI::verify_instances_rotation_synchronized(), Slic3r::GUI::Selection::Cache::volumes_data, and Slic3r::Z.
Referenced by flattening_rotate(), mirror(), Slic3r::GUI::GizmoObjectManipulation::reset_rotation_value(), rotate(), scale(), and translate().
synchronize_unselected_volumes()
void Slic3r::GUI::Selection::synchronize_unselected_volumes ()
{
    for (unsigned int i : m_list) {
        const GLVolume* volume = (*m_volumes)[i];
        const int object_idx = volume->object_idx();
        if (object_idx >= 1000)
            continue;
        const int volume_idx = volume->volume_idx();
        const Vec3d& offset = volume->get_volume_offset();
        const Vec3d& rotation = volume->get_volume_rotation();
        const Vec3d& scaling_factor = volume->get_volume_scaling_factor();
        const Vec3d& mirror = volume->get_volume_mirror();
        // Process unselected volumes.
        for (unsigned int j = 0; j < (unsigned int)m_volumes->size(); ++j) {
            if (j == i)
                continue;
            GLVolume* v = (*m_volumes)[j];
            if (v->object_idx() != object_idx || v->volume_idx() != volume_idx)
                continue;
            v->set_volume_offset(offset);
            v->set_volume_rotation(rotation);
            v->set_volume_scaling_factor(scaling_factor);
            v->set_volume_mirror(mirror);
        }
    }
}
References int, m_list, m_volumes, mirror(), Slic3r::GLVolume::object_idx(), Slic3r::offset(), Slic3r::GLVolume::set_volume_mirror(), Slic3r::GLVolume::set_volume_offset(), Slic3r::GLVolume::set_volume_rotation(), Slic3r::GLVolume::set_volume_scaling_factor(), and Slic3r::GLVolume::volume_idx().
Referenced by mirror(), Slic3r::GUI::GizmoObjectManipulation::reset_rotation_value(), rotate(), scale(), and translate().
translate() [1/3]
void Slic3r::GUI::Selection::translate (const Vec3d & displacement, bool local = false)
{
    if (!m_valid)
        return;
    EMode translation_type = m_mode;
    //BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, displacement {%2%, %3%, %4%}") % __LINE__ % displacement(X) % displacement(Y) % displacement(Z);
    for (unsigned int i : m_list) {
        GLVolume& v = *(*m_volumes)[i];
        if (v.is_wipe_tower) {
            int plate_idx = v.object_idx() - 1000;
            BoundingBoxf3 plate_bbox = wxGetApp().plater()->get_partplate_list().get_plate(plate_idx)->get_bounding_box();
            Vec3d tower_size = v.bounding_box().size();
            Vec3d tower_origin = m_cache.volumes_data[i].get_volume_position();
            Vec3d actual_displacement = displacement;
            const double margin = 15.f;
            if (!local)
                actual_displacement = (m_cache.volumes_data[i].get_instance_rotation_matrix() * m_cache.volumes_data[i].get_instance_scale_matrix() * m_cache.volumes_data[i].get_instance_mirror_matrix()).inverse() * displacement;
            if (tower_origin(0) + actual_displacement(0) - margin < plate_bbox.min(0)) {
                actual_displacement(0) = plate_bbox.min(0) - tower_origin(0) + margin;
            }
            else if (tower_origin(0) + actual_displacement(0) + tower_size(0) + margin > plate_bbox.max(0)) {
                actual_displacement(0) = plate_bbox.max(0) - tower_origin(0) - tower_size(0) - margin;
            }
            if (tower_origin(1) + actual_displacement(1) - margin < plate_bbox.min(1)) {
                actual_displacement(1) = plate_bbox.min(1) - tower_origin(1) + margin;
            }
            else if (tower_origin(1) + actual_displacement(1) + tower_size(1) + margin > plate_bbox.max(1)) {
                actual_displacement(1) = plate_bbox.max(1) - tower_origin(1) - tower_size(1) - margin;
            }
            v.set_volume_offset(m_cache.volumes_data[i].get_volume_position() + actual_displacement);
        }
        else if (m_mode == Volume || v.is_wipe_tower) {
            if (local)
                v.set_volume_offset(m_cache.volumes_data[i].get_volume_position() + displacement);
            else {
                const Vec3d local_displacement = (m_cache.volumes_data[i].get_instance_rotation_matrix() * m_cache.volumes_data[i].get_instance_scale_matrix() * m_cache.volumes_data[i].get_instance_mirror_matrix()).inverse() * displacement;
                v.set_volume_offset(m_cache.volumes_data[i].get_volume_position() + local_displacement);
            }
        }
        else if (m_mode == Instance) {
            if (is_from_fully_selected_instance(i))
                v.set_instance_offset(m_cache.volumes_data[i].get_instance_position() + displacement);
            else {
                const Vec3d local_displacement = (m_cache.volumes_data[i].get_instance_rotation_matrix() * m_cache.volumes_data[i].get_instance_scale_matrix() * m_cache.volumes_data[i].get_instance_mirror_matrix()).inverse() * displacement;
                v.set_volume_offset(m_cache.volumes_data[i].get_volume_position() + local_displacement);
                translation_type = Volume;
            }
        }
    }
#if !DISABLE_INSTANCES_SYNCH
    if (translation_type == Instance)
        synchronize_unselected_instances(SYNC_ROTATION_NONE);
    else if (translation_type == Volume)
        synchronize_unselected_volumes();
#endif // !DISABLE_INSTANCES_SYNCH
    ensure_not_below_bed();
    set_bounding_boxes_dirty();
    wxGetApp().plater()->canvas3D()->requires_check_outside_state();
}
References Slic3r::GLVolume::bounding_box(), ensure_not_below_bed(), Instance, inverse(), is_from_fully_selected_instance(), m_cache, m_list, m_mode, m_valid, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::GLVolume::object_idx(), set_bounding_boxes_dirty(), Slic3r::GLVolume::set_instance_offset(), Slic3r::GLVolume::set_volume_offset(), Slic3r::BoundingBox3Base< PointClass >::size(), SYNC_ROTATION_NONE, synchronize_unselected_instances(), synchronize_unselected_volumes(), Volume, and Slic3r::GUI::Selection::Cache::volumes_data.
Referenced by Slic3r::GUI::GizmoObjectManipulation::change_position_value(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::GUI::GLCanvas3D::on_key(), Slic3r::GUI::GLCanvas3D::on_mouse(), and scale_to_fit_print_volume().
translate() [2/3]
void Slic3r::GUI::Selection::translate (unsigned int object_idx, const Vec3d & displacement)
{
    if (!m_valid)
        return;
    //BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": obj %1%") % object_idx;
    //BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, displacement {%2%, %3%, %4%}") % __LINE__ % displacement(X) % displacement(Y) % displacement(Z);
    for (unsigned int i : m_list) {
        GLVolume& v = *(*m_volumes)[i];
        if (v.object_idx() == (int)object_idx)
            v.set_instance_offset(v.get_instance_offset() + displacement);
    }
    std::set<unsigned int> done;  // prevent processing volumes twice
    done.insert(m_list.begin(), m_list.end());
    for (unsigned int i : m_list) {
        if (done.size() == m_volumes->size())
            break;
        int object_idx = (*m_volumes)[i]->object_idx();
        if (object_idx >= 1000)
            continue;
        // Process unselected volumes of the object.
        for (unsigned int j = 0; j < (unsigned int)m_volumes->size(); ++j) {
            if (done.size() == m_volumes->size())
                break;
            if (done.find(j) != done.end())
                continue;
            GLVolume& v = *(*m_volumes)[j];
            if (v.object_idx() != object_idx)
                continue;
            v.set_instance_offset(v.get_instance_offset() + displacement);
            done.insert(j);
        }
    }
    this->set_bounding_boxes_dirty();
}
References Slic3r::GLVolume::get_instance_offset(), int, m_list, m_valid, m_volumes, Slic3r::GLVolume::object_idx(), set_bounding_boxes_dirty(), and Slic3r::GLVolume::set_instance_offset().
translate() [3/3]
void Slic3r::GUI::Selection::translate (unsigned int object_idx, unsigned int instance_idx, const Vec3d & displacement)
{
    if (!m_valid)
        return;
    //BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": obj %1%, instance %2%") % object_idx % instance_idx;
    //BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, displacement {%2%, %3%, %4%}") % __LINE__ % displacement(X) % displacement(Y) % displacement(Z);
    for (unsigned int i : m_list) {
        GLVolume& v = *(*m_volumes)[i];
        if (v.object_idx() == (int)object_idx && v.instance_idx() == (int)instance_idx)
            v.set_instance_offset(v.get_instance_offset() + displacement);
    }
    std::set<unsigned int> done;  // prevent processing volumes twice
    done.insert(m_list.begin(), m_list.end());
    for (unsigned int i : m_list) {
        if (done.size() == m_volumes->size())
            break;
        int object_idx = (*m_volumes)[i]->object_idx();
        if (object_idx >= 1000)
            continue;
        // Process unselected volumes of the object.
        for (unsigned int j = 0; j < (unsigned int)m_volumes->size(); ++j) {
            if (done.size() == m_volumes->size())
                break;
            if (done.find(j) != done.end())
                continue;
            GLVolume& v = *(*m_volumes)[j];
            if (v.object_idx() != object_idx || v.instance_idx() != (int)instance_idx)
                continue;
            v.set_instance_offset(v.get_instance_offset() + displacement);
            done.insert(j);
        }
    }
    this->set_bounding_boxes_dirty();
}
References Slic3r::GLVolume::get_instance_offset(), Slic3r::GLVolume::instance_idx(), int, m_list, m_valid, m_volumes, Slic3r::GLVolume::object_idx(), set_bounding_boxes_dirty(), and Slic3r::GLVolume::set_instance_offset().
unlock_volume_selection_mode()
void Slic3r::GUI::Selection::unlock_volume_selection_mode () inline
{ m_volume_selection_locked = false; }
References m_volume_selection_locked.
update_type()
void Slic3r::GUI::Selection::update_type () private
{
    m_cache.content.clear();
    m_type = Mixed;
    for (unsigned int i : m_list)
    {
        const GLVolume* volume = (*m_volumes)[i];
        int obj_idx = volume->object_idx();
        int inst_idx = volume->instance_idx();
        ObjectIdxsToInstanceIdxsMap::iterator obj_it = m_cache.content.find(obj_idx);
        if (obj_it == m_cache.content.end())
            obj_it = m_cache.content.insert(ObjectIdxsToInstanceIdxsMap::value_type(obj_idx, InstanceIdxsList())).first;
        obj_it->second.insert(inst_idx);
    }
    bool requires_disable = false;
    if (!m_valid)
        m_type = Invalid;
    else
    {
        if (m_list.empty())
            m_type = Empty;
        else if (m_list.size() == 1)
        {
            const GLVolume* first = (*m_volumes)[*m_list.begin()];
            if (first->is_wipe_tower)
                m_type = WipeTower;
            else if (first->is_modifier)
            {
                m_type = SingleModifier;
                requires_disable = true;
            }
            else
            {
                const ModelObject* model_object = m_model->objects[first->object_idx()];
                unsigned int volumes_count = (unsigned int)model_object->volumes.size();
                unsigned int instances_count = (unsigned int)model_object->instances.size();
                if (volumes_count * instances_count == 1)
                {
                    m_type = SingleFullObject;
                    // ensures the correct mode is selected
                    m_mode = Instance;
                }
                else if (volumes_count == 1) // instances_count > 1
                {
                    m_type = SingleFullInstance;
                    // ensures the correct mode is selected
                    m_mode = Instance;
                }
                else
                {
                    m_type = SingleVolume;
                    requires_disable = true;
                }
            }
        }
        else
        {
            unsigned int sla_volumes_count = 0;
            // Note: sla_volumes_count is a count of the selected sla_volumes per object instead of per instance, like a model_volumes_count is
            for (unsigned int i : m_list) {
                if ((*m_volumes)[i]->volume_idx() < 0)
                    ++sla_volumes_count;
            }
            if (m_cache.content.size() == 1) // single object
            {
                const ModelObject* model_object = m_model->objects[m_cache.content.begin()->first];
                unsigned int model_volumes_count = (unsigned int)model_object->volumes.size();
                unsigned int instances_count = (unsigned int)model_object->instances.size();
                unsigned int selected_instances_count = (unsigned int)m_cache.content.begin()->second.size();
                if (model_volumes_count * instances_count + sla_volumes_count == (unsigned int)m_list.size())
                {
                    m_type = SingleFullObject;
                    // ensures the correct mode is selected
                    m_mode = Instance;
                }
                else if (selected_instances_count == 1)
                {
                    if (model_volumes_count + sla_volumes_count == (unsigned int)m_list.size())
                    {
                        m_type = SingleFullInstance;
                        // ensures the correct mode is selected
                        m_mode = Instance;
                    }
                    else
                    {
                        unsigned int modifiers_count = 0;
                        for (unsigned int i : m_list)
{
                            if ((*m_volumes)[i]->is_modifier)
                                ++modifiers_count;
                        }
                        if (modifiers_count == 0)
                            m_type = MultipleVolume;
                        else if (modifiers_count == (unsigned int)m_list.size())
                            m_type = MultipleModifier;
                        requires_disable = true;
                    }
                }
                else if ((selected_instances_count > 1) && (selected_instances_count * model_volumes_count + sla_volumes_count == (unsigned int)m_list.size()))
                {
                    m_type = MultipleFullInstance;
                    // ensures the correct mode is selected
                    m_mode = Instance;
                }
            }
            else
            {
                unsigned int sels_cntr = 0;
                for (ObjectIdxsToInstanceIdxsMap::iterator it = m_cache.content.begin(); it != m_cache.content.end(); ++it)
                {
                    bool               is_wipe_tower   = it->first >= 1000;
                    int                actual_obj_id   = is_wipe_tower ? it->first - 1000 : it->first;
                    const ModelObject *model_object    = m_model->objects[actual_obj_id];
                    unsigned int volumes_count = (unsigned int)model_object->volumes.size();
                    unsigned int instances_count = (unsigned int)model_object->instances.size();
                    sels_cntr += volumes_count * instances_count;
                }
                if (sels_cntr + sla_volumes_count == (unsigned int)m_list.size())
                {
                    m_type = MultipleFullObject;
                    // ensures the correct mode is selected
                    m_mode = Instance;
                }
            }
        }
    }
    //BBS: remove the disable logic here
    /*int object_idx = get_object_idx();
    int instance_idx = get_instance_idx();
    for (GLVolume* v : *m_volumes)
    {
        v->disabled = requires_disable ? (v->object_idx() != object_idx) || (v->instance_idx() != instance_idx) : false;
    }*/
#if ENABLE_SELECTION_DEBUG_OUTPUT
    std::cout << "Selection: ";
    std::cout << "mode: ";
    switch (m_mode)
    {
    case Volume:
    {
        std::cout << "Volume";
        break;
    }
    case Instance:
    {
        std::cout << "Instance";
        break;
    }
    }
    std::cout << " - type: ";
    switch (m_type)
    {
    case Invalid:
    {
        std::cout << "Invalid" << std::endl;
        break;
    }
    case Empty:
    {
        std::cout << "Empty" << std::endl;
        break;
    }
    case WipeTower:
    {
        std::cout << "WipeTower" << std::endl;
        break;
    }
    case SingleModifier:
    {
        std::cout << "SingleModifier" << std::endl;
        break;
    }
    case MultipleModifier:
    {
        std::cout << "MultipleModifier" << std::endl;
        break;
    }
    case SingleVolume:
    {
        std::cout << "SingleVolume" << std::endl;
        break;
    }
    case MultipleVolume:
    {
        std::cout << "MultipleVolume" << std::endl;
        break;
    }
    case SingleFullObject:
    {
        std::cout << "SingleFullObject" << std::endl;
        break;
    }
    case MultipleFullObject:
    {
        std::cout << "MultipleFullObject" << std::endl;
        break;
    }
    case SingleFullInstance:
    {
        std::cout << "SingleFullInstance" << std::endl;
        break;
    }
    case MultipleFullInstance:
    {
        std::cout << "MultipleFullInstance" << std::endl;
        break;
    }
    case Mixed:
    {
        std::cout << "Mixed" << std::endl;
        break;
    }
    }
#endif // ENABLE_SELECTION_DEBUG_OUTPUT
}
References Slic3r::GUI::Selection::Cache::content, Empty, Instance, Slic3r::ModelObject::instances, int, Invalid, is_wipe_tower(), m_cache, m_list, m_mode, m_model, m_type, m_valid, m_volumes, Mixed, MultipleFullInstance, MultipleFullObject, MultipleModifier, MultipleVolume, Slic3r::GLVolume::object_idx(), Slic3r::Model::objects, SingleFullInstance, SingleFullObject, SingleModifier, SingleVolume, Volume, Slic3r::ModelObject::volumes, volumes_count(), and WipeTower.
Referenced by add(), add_all(), add_curr_plate(), add_instance(), add_object(), add_volume(), add_volumes(), clear(), instances_changed(), remove(), remove_curr_plate(), remove_instance(), remove_object(), remove_volume(), remove_volumes(), set_deserialized(), and volumes_changed().
update_valid()
void Slic3r::GUI::Selection::update_valid () private
{
    m_valid = (m_volumes != nullptr) && (m_model != nullptr);
}
References m_model, m_valid, and m_volumes.
Referenced by set_model(), and set_volumes().
volumes_changed()
void Slic3r::GUI::Selection::volumes_changed (const std::vector< size_t > & map_volume_old_to_new)
{
    assert(m_valid);
    assert(m_mode == Volume);
    IndicesList list_new;
    for (unsigned int idx : m_list)
        if (map_volume_old_to_new[idx] != size_t(-1)) {
            unsigned int new_idx = (unsigned int)map_volume_old_to_new[idx];
            (*m_volumes)[new_idx]->selected = true;
            list_new.insert(new_idx);
        }
    m_list = std::move(list_new);
    update_type();
    this->set_bounding_boxes_dirty();
}
References int, m_list, m_mode, m_valid, set_bounding_boxes_dirty(), update_type(), and Volume.
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene().
volumes_count()
unsigned int Slic3r::GUI::Selection::volumes_count () const inline
{ return (unsigned int)m_list.size(); }
References m_list.
Referenced by update_type().
Member Data Documentation
m_arrow
GLModel Slic3r::GUI::Selection::m_arrow private
Referenced by init(), render_sidebar_position_hints(), and render_sidebar_scale_hints().
m_bounding_box
std::optional<BoundingBoxf3> Slic3r::GUI::Selection::m_bounding_box private
Referenced by get_bounding_box(), and set_bounding_boxes_dirty().
m_cache
Cache Slic3r::GUI::Selection::m_cache private
Referenced by copy_to_clipboard(), ensure_on_bed(), erase(), flattening_rotate(), get_content(), get_instance_idx(), get_instance_idxs(), get_object_idx(), get_selected_object_instances(), move_to_center(), rotate(), scale(), set_caches(), set_printable(), synchronize_unselected_instances(), translate(), and update_type().
m_clipboard
Clipboard Slic3r::GUI::Selection::m_clipboard private
Referenced by copy_to_clipboard(), get_clipboard(), paste_from_clipboard(), paste_objects_from_clipboard(), and paste_volumes_from_clipboard().
m_curved_arrow
GLModel Slic3r::GUI::Selection::m_curved_arrow private
Referenced by init(), and render_sidebar_rotation_hints().
m_dragging
bool Slic3r::GUI::Selection::m_dragging private
Referenced by is_dragging(), start_dragging(), and stop_dragging().
m_enabled
bool Slic3r::GUI::Selection::m_enabled private
Referenced by is_enabled(), and set_enabled().
m_list
IndicesList Slic3r::GUI::Selection::m_list private
Referenced by add(), add_all(), clear(), contains_all_volumes(), contains_any_volume(), contains_volume(), copy_to_clipboard(), do_add_volume(), do_remove_volume(), ensure_not_below_bed(), erase(), flattening_rotate(), get_bounding_box(), get_missing_volume_idxs_from(), get_scaled_instance_bounding_box(), get_unscaled_instance_bounding_box(), get_unselected_volume_idxs_from(), get_volume_idxs(), instances_changed(), is_from_fully_selected_instance(), is_single_full_instance(), is_sla_compliant(), matches(), mirror(), move_to_center(), notify_instance_update(), render_synchronized_volumes(), rotate(), scale(), set_deserialized(), synchronize_unselected_instances(), synchronize_unselected_volumes(), translate(), translate(), translate(), update_type(), volumes_changed(), and volumes_count().
m_mode
EMode Slic3r::GUI::Selection::m_mode private
Referenced by add(), add_all(), add_curr_plate(), add_instance(), add_object(), add_volume(), add_volumes(), copy_to_clipboard(), flattening_rotate(), get_mode(), instances_changed(), is_instance_mode(), Slic3r::GUI::Selection::Clipboard::is_sla_compliant(), is_sla_compliant(), mirror(), move_to_center(), paste_from_clipboard(), remove(), remove_all(), remove_curr_plate(), remove_volumes(), render_synchronized_volumes(), requires_local_axes(), rotate(), scale(), scale_to_fit_print_volume(), set_deserialized(), set_mode(), translate(), update_type(), and volumes_changed().
m_model
Model* Slic3r::GUI::Selection::m_model private
Referenced by Slic3r::GUI::Selection::Clipboard::Clipboard(), add_curr_plate(), Slic3r::GUI::Selection::Clipboard::add_object(), copy_to_clipboard(), erase(), get_model(), Slic3r::GUI::Selection::Clipboard::get_object(), Slic3r::GUI::Selection::Clipboard::get_objects(), Slic3r::GUI::Selection::Clipboard::is_empty(), is_from_fully_selected_instance(), is_single_full_instance(), Slic3r::GUI::Selection::Clipboard::is_sla_compliant(), notify_instance_update(), paste_objects_from_clipboard(), paste_volumes_from_clipboard(), remove_curr_plate(), Slic3r::GUI::Selection::Clipboard::reset(), rotate(), scale(), set_model(), set_printable(), synchronize_unselected_instances(), update_type(), and update_valid().
m_scale_factor
float Slic3r::GUI::Selection::m_scale_factor private
Referenced by render(), render_bounding_box(), and render_bounding_box().
m_scaled_instance_bounding_box
std::optional<BoundingBoxf3> Slic3r::GUI::Selection::m_scaled_instance_bounding_box private
Referenced by get_scaled_instance_bounding_box(), and set_bounding_boxes_dirty().
m_type
EType Slic3r::GUI::Selection::m_type private
Referenced by is_empty(), is_mixed(), is_multiple_full_instance(), is_multiple_full_object(), is_multiple_modifier(), is_multiple_volume(), is_single_full_instance(), is_single_full_object(), is_single_modifier(), is_single_volume(), is_wipe_tower(), and update_type().
m_unscaled_instance_bounding_box
std::optional<BoundingBoxf3> Slic3r::GUI::Selection::m_unscaled_instance_bounding_box private
Referenced by get_unscaled_instance_bounding_box(), and set_bounding_boxes_dirty().
m_valid
bool Slic3r::GUI::Selection::m_valid private
Referenced by add(), add_all(), add_curr_plate(), add_instance(), add_object(), add_volume(), add_volumes(), clear(), copy_to_clipboard(), erase(), flattening_rotate(), get_bounding_box(), get_scaled_instance_bounding_box(), get_unscaled_instance_bounding_box(), get_volume(), instances_changed(), is_single_full_instance(), mirror(), move_to_center(), paste_from_clipboard(), remove(), remove_all(), remove_curr_plate(), remove_instance(), remove_object(), remove_volume(), remove_volumes(), render(), rotate(), scale(), set_deserialized(), set_printable(), start_dragging(), translate(), translate(), translate(), update_type(), update_valid(), and volumes_changed().
m_volume_selection_locked
bool Slic3r::GUI::Selection::m_volume_selection_locked { false } private
Referenced by lock_volume_selection_mode(), set_volume_selection_mode(), and unlock_volume_selection_mode().
m_volume_selection_mode
EMode Slic3r::GUI::Selection::m_volume_selection_mode { Instance } private
Referenced by add(), and set_volume_selection_mode().
m_volumes
GLVolumePtrs* Slic3r::GUI::Selection::m_volumes private
Referenced by add(), add_all(), add_volumes(), do_add_volumes(), do_remove_instance(), do_remove_object(), ensure_not_below_bed(), ensure_on_bed(), get_bounding_box(), get_volume(), get_volume_idxs_from_instance(), get_volume_idxs_from_object(), get_volume_idxs_from_volume(), instances_changed(), is_from_fully_selected_instance(), is_single_full_instance(), is_sla_compliant(), remove(), remove_volume(), remove_volumes(), render_synchronized_volumes(), set_caches(), set_deserialized(), set_volumes(), synchronize_unselected_instances(), synchronize_unselected_volumes(), translate(), translate(), update_type(), and update_valid().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Selection.hpp
src/slic3r/GUI/Selection.cpp