OrcaSlicer: Slic3r::GUI::PlaterJob Class Reference
Slic3r::GUI::PlaterJob Class Reference abstract
#include <src/slic3r/GUI/Jobs/PlaterJob.hpp>
Public Types
enum JobPrepareState { PREPARE_STATE_DEFAULT = 0 , PREPARE_STATE_MENU = 1 }
Public Member Functions
PlaterJob (std::shared_ptr< ProgressIndicator > pri, Plater *plater)
bool is_finalized () const
void start ()
bool join (int timeout_ms=0)
bool is_running () const
void cancel ()
Protected Member Functions
void on_exception (const std::exception_ptr &) override
virtual int status_range () const
void update_status (int st, const wxString &msg="")
void update_percent_finish ()
void show_networking_test (wxString msg)
bool was_canceled () const
virtual void prepare ()
virtual void process ()=0
virtual void finalize ()
Protected Attributes
Plater * m_plater
bool only_on_partplate {false}
Private Member Functions
void run (std::exception_ptr &)
Private Attributes
int m_range = 100
int m_thread_evt_id = wxID_ANY
boost::thread m_thread
std::atomic< bool > m_running {false}
std::atomic< bool > m_canceled {false}
bool m_finalized = false
bool m_finalizing = false
std::shared_ptr< ProgressIndicator > m_progress
std::exception_ptr m_worker_error = nullptr
Detailed Description
Member Enumeration Documentation
JobPrepareState
enum Slic3r::GUI::Job::JobPrepareState inherited
Enumerator
PREPARE_STATE_DEFAULT
PREPARE_STATE_MENU
{
        PREPARE_STATE_DEFAULT = 0,
        PREPARE_STATE_MENU = 1,
    };
Constructor & Destructor Documentation
PlaterJob()
Slic3r::GUI::PlaterJob::PlaterJob (std::shared_ptr< ProgressIndicator > pri, Plater * plater) inline
                                                                   :
        Job{std::move(pri)}, m_plater{plater} {}
Member Function Documentation
cancel()
void Slic3r::GUI::Job::cancel () inline inherited
{ m_canceled.store(true); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::UpgradeNetworkJob::process().
finalize()
virtual void Slic3r::GUI::Job::finalize () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ArrangeJob, Slic3r::GUI::BindJob, Slic3r::GUI::FillBedJob, Slic3r::GUI::OrientJob, Slic3r::GUI::PrintJob, Slic3r::GUI::RotoptimizeJob, Slic3r::GUI::SendJob, Slic3r::GUI::SLAImportJob, and Slic3r::GUI::UpgradeNetworkJob.
{ m_finalized = true; }
References Slic3r::GUI::Job::m_finalized.
Referenced by Slic3r::GUI::Job::Job(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::BindJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::PrintJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SendJob::finalize(), and Slic3r::GUI::UpgradeNetworkJob::finalize().
is_finalized()
bool Slic3r::GUI::Job::is_finalized () const inline inherited
{ return m_finalized; }
References Slic3r::GUI::Job::m_finalized.
is_running()
bool Slic3r::GUI::Job::is_running () const inline inherited
{ return m_running.load(); }
References Slic3r::GUI::Job::m_running.
join()
bool Slic3r::GUI::Job::join (int timeout_ms = 0) inherited
{
    if (!m_thread.joinable()) return true;
    if (timeout_ms <= 0)
        m_thread.join();
    else if (!m_thread.try_join_for(boost::chrono::milliseconds(timeout_ms)))
        return false;
    return true;
}
on_exception()
void Slic3r::GUI::PlaterJob::on_exception (const std::exception_ptr & eptr) override protected virtual
Reimplemented from Slic3r::GUI::Job.
Reimplemented in Slic3r::GUI::PrintJob, and Slic3r::GUI::SendJob.
{
    try {
        if (eptr)
            std::rethrow_exception(eptr);
    }  catch (std::exception &e) {
       show_error(m_plater, _(L("Exception")) + ": "+ e.what());
    }
}
References _, L, m_plater, and Slic3r::GUI::show_error().
Referenced by Slic3r::GUI::ArrangeJob::on_exception(), Slic3r::GUI::BindJob::on_exception(), Slic3r::GUI::OrientJob::on_exception(), Slic3r::GUI::PrintJob::on_exception(), and Slic3r::GUI::SendJob::on_exception().
prepare()
virtual void Slic3r::GUI::Job::prepare () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ArrangeJob, Slic3r::GUI::FillBedJob, Slic3r::GUI::OrientJob, Slic3r::GUI::PrintJob, Slic3r::GUI::RotoptimizeJob, Slic3r::GUI::SendJob, and Slic3r::GUI::SLAImportJob.
{}
process()
virtual void Slic3r::GUI::Job::process () protected pure virtual inherited
Implemented in Slic3r::GUI::ArrangeJob, Slic3r::GUI::BindJob, Slic3r::GUI::FillBedJob, Slic3r::GUI::OrientJob, Slic3r::GUI::PrintJob, Slic3r::GUI::RotoptimizeJob, Slic3r::GUI::SendJob, Slic3r::GUI::SLAImportJob, and Slic3r::GUI::UpgradeNetworkJob.
Referenced by Slic3r::GUI::Job::run().
run()
void Slic3r::GUI::Job::run (std::exception_ptr & eptr) private inherited
{
    m_running.store(true);
    try {
        process();
    } catch (...) {
        eptr = std::current_exception();
    }
    m_running.store(false);
    // ensure to call the last status to finalize the job
    update_status(status_range(), "");
}
References Slic3r::GUI::Job::m_running, Slic3r::GUI::Job::process(), Slic3r::GUI::Job::status_range(), and Slic3r::GUI::Job::update_status().
show_networking_test()
void Slic3r::GUI::Job::show_networking_test (wxString msg) protected inherited
{
    m_progress->show_networking_test(msg);
}
Referenced by Slic3r::GUI::PrintJob::process().
start()
void Slic3r::GUI::Job::start () inherited
{ // Start the job. No effect if the job is already running
    if (!m_running.load()) {
        prepare();
        // Save the current status indicatior range and push the new one
        m_range = m_progress->get_range();
        m_progress->set_range(status_range());
        // init cancellation flag and set the cancel callback
        m_canceled.store(false);
        m_progress->set_cancel_callback(
                    [this]() { m_canceled.store(true); });
        m_finalized  = false;
        m_finalizing = false;
        // Changing cursor to busy
        wxBeginBusyCursor();
        try { // Execute the job
            m_worker_error = nullptr;
            m_thread = create_thread([this] { this->run(m_worker_error); });
        } catch (std::exception &) {
            update_status(status_range(),
                          _(L("Error! Unable to create thread!")));
        }
        // The state changes will be undone when the process hits the
        // last status value, in the status update handler (see ctor)
    }
}
References _, Slic3r::create_thread(), and L.
Referenced by Slic3r::GUI::OrientJob::process().
status_range()
virtual int Slic3r::GUI::Job::status_range () const inline protected virtual inherited
Reimplemented in Slic3r::GUI::ArrangeJob, Slic3r::GUI::BindJob, Slic3r::GUI::FillBedJob, Slic3r::GUI::PrintJob, Slic3r::GUI::SendJob, and Slic3r::GUI::UpgradeNetworkJob.
{ return 100; }
Referenced by Slic3r::GUI::Job::Job(), and Slic3r::GUI::Job::run().
update_percent_finish()
void Slic3r::GUI::Job::update_percent_finish () protected inherited
{
    m_progress->clear_percent();
}
Referenced by Slic3r::GUI::PrintJob::process().
update_status()
void Slic3r::GUI::Job::update_status (int st, const wxString & msg = "") protected inherited
{
    auto evt = new wxThreadEvent(wxEVT_THREAD, m_thread_evt_id);
    evt->SetInt(st);
    evt->SetString(msg);
    wxQueueEvent(this, evt);
}
Referenced by Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), Slic3r::GUI::Job::run(), Slic3r::GUI::BindJob::update_status(), and Slic3r::GUI::UpgradeNetworkJob::update_status().
was_canceled()
bool Slic3r::GUI::Job::was_canceled () const inline protected inherited
{ return m_canceled.load(); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::BindJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::PrintJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SendJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::UpgradeNetworkJob::finalize(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), and Slic3r::GUI::UpgradeNetworkJob::process().
Member Data Documentation
m_canceled
std::atomic<bool> Slic3r::GUI::Job::m_canceled {false} private inherited
Referenced by Slic3r::GUI::Job::cancel(), and Slic3r::GUI::Job::was_canceled().
m_finalized
bool Slic3r::GUI::Job::m_finalized = false private inherited
Referenced by Slic3r::GUI::Job::Job(), Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::is_finalized().
m_finalizing
bool Slic3r::GUI::Job::m_finalizing = false private inherited
Referenced by Slic3r::GUI::Job::Job().
m_plater
Plater* Slic3r::GUI::PlaterJob::m_plater protected
Referenced by Slic3r::GUI::ArrangeJob::check_unprintable(), Slic3r::GUI::ArrangeJob::clear_input(), Slic3r::GUI::OrientJob::clear_input(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::ArrangeJob::on_exception(), on_exception(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::OrientJob::prepare(), Slic3r::GUI::PrintJob::prepare(), Slic3r::GUI::RotoptimizeJob::prepare(), Slic3r::GUI::SendJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), and Slic3r::GUI::SLAImportJob::reset().
m_progress
std::shared_ptr<ProgressIndicator> Slic3r::GUI::Job::m_progress private inherited
Referenced by Slic3r::GUI::Job::Job().
m_range
int Slic3r::GUI::Job::m_range = 100 private inherited
Referenced by Slic3r::GUI::Job::Job().
m_running
std::atomic<bool> Slic3r::GUI::Job::m_running {false} private inherited
Referenced by Slic3r::GUI::Job::is_running(), and Slic3r::GUI::Job::run().
m_thread
boost::thread Slic3r::GUI::Job::m_thread private inherited
m_thread_evt_id
int Slic3r::GUI::Job::m_thread_evt_id = wxID_ANY private inherited
Referenced by Slic3r::GUI::Job::Job().
m_worker_error
std::exception_ptr Slic3r::GUI::Job::m_worker_error = nullptr private inherited
Referenced by Slic3r::GUI::Job::Job().
only_on_partplate
bool Slic3r::GUI::PlaterJob::only_on_partplate {false} protected
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::OrientJob::prepare(), and Slic3r::GUI::ArrangeJob::prepare_wipe_tower().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/PlaterJob.hpp
src/slic3r/GUI/Jobs/PlaterJob.cpp