OrcaSlicer: orgQhull::QhullLinkedList< T >::const_iterator Class Reference
orgQhull::QhullLinkedList< T >::const_iterator Class Reference
#include <src/qhull/src/libqhullcpp/QhullLinkedList.h>
Public Types
typedef std::bidirectional_iterator_tag iterator_category
typedef T value_type
typedef const value_type * pointer
typedef const value_type & reference
typedef ptrdiff_t difference_type
Public Member Functions
const_iterator ()
const_iterator (const T &t)
Automatic conversion to const_iterator.
const_iterator (const iterator &o)
const_iterator (const const_iterator &o)
const_iterator & operator= (const const_iterator &o)
const T & operator* () const
const T * operator-> () const
bool operator== (const const_iterator &o) const
bool operator!= (const const_iterator &o) const
const_iterator & operator++ ()
const_iterator operator++ (int)
const_iterator & operator-- ()
const_iterator operator-- (int)
const_iterator operator- (int j) const
const_iterator & operator+= (int j)
const_iterator & operator-= (int j)
Iterator
const_iterator operator+ (int j) const
Private Attributes
T i
Detailed Description
template<typename T>
class orgQhull::QhullLinkedList< T >::const_iterator
Member Typedef Documentation
difference_type
template<typename T > typedef ptrdiff_t orgQhull::QhullLinkedList< T >::const_iterator::difference_type
iterator_category
template<typename T > typedef std::bidirectional_iterator_tag orgQhull::QhullLinkedList< T >::const_iterator::iterator_category
pointer
template<typename T > typedef const value_type* orgQhull::QhullLinkedList< T >::const_iterator::pointer
reference
template<typename T > typedef const value_type& orgQhull::QhullLinkedList< T >::const_iterator::reference
value_type
template<typename T > typedef T orgQhull::QhullLinkedList< T >::const_iterator::value_type
Constructor & Destructor Documentation
const_iterator() [1/4]
template<typename T > orgQhull::QhullLinkedList< T >::const_iterator::const_iterator () inline
: i() {}
const_iterator() [2/4]
template<typename T > orgQhull::QhullLinkedList< T >::const_iterator::const_iterator (const T & t) inline
Automatic conversion to const_iterator.
const_iterator() [3/4]
template<typename T > orgQhull::QhullLinkedList< T >::const_iterator::const_iterator (const iterator & o) inline
: i(o.i) {}
const_iterator() [4/4]
template<typename T > orgQhull::QhullLinkedList< T >::const_iterator::const_iterator (const const_iterator & o) inline
: i(o.i) {}
Member Function Documentation
operator!=()
template<typename T > bool orgQhull::QhullLinkedList< T >::const_iterator::operator!= (const const_iterator & o) const inline
{ return !operator==(o); }
References orgQhull::QhullLinkedList< T >::const_iterator::operator==().
operator*()
template<typename T > const T & orgQhull::QhullLinkedList< T >::const_iterator::operator* () const inline
{ return i; }
References orgQhull::QhullLinkedList< T >::const_iterator::i.
operator+()
template<typename T > QhullLinkedList< T >::const_iterator orgQhull::QhullLinkedList< T >::const_iterator::operator+ (int j) const
{
    T n= i;
    if(j>0){
        while(j--){
            n= n.next();
        }
    }else{
        while(j++){
            n= n.previous();
        }
    }
    return const_iterator(n);
}//operator+
References n.
Referenced by orgQhull::QhullLinkedList< T >::const_iterator::operator-().
operator++() [1/2]
template<typename T > const_iterator & orgQhull::QhullLinkedList< T >::const_iterator::operator++ () inline
{ i= i.next(); return *this; }
References orgQhull::QhullLinkedList< T >::const_iterator::i.
operator++() [2/2]
template<typename T > const_iterator orgQhull::QhullLinkedList< T >::const_iterator::operator++ (int) inline
{ const_iterator o= i; i= i.next(); return o; }
References orgQhull::QhullLinkedList< T >::const_iterator::i.
operator+=()
template<typename T > const_iterator & orgQhull::QhullLinkedList< T >::const_iterator::operator+= (int j) inline
{ return (*this= *this + j); }
operator-()
template<typename T > const_iterator orgQhull::QhullLinkedList< T >::const_iterator::operator- (int j) const inline
{ return operator+(-j); }
References orgQhull::QhullLinkedList< T >::const_iterator::operator+().
operator--() [1/2]
template<typename T > const_iterator & orgQhull::QhullLinkedList< T >::const_iterator::operator-- () inline
{ i= i.previous(); return *this; }
References orgQhull::QhullLinkedList< T >::const_iterator::i.
operator--() [2/2]
template<typename T > const_iterator orgQhull::QhullLinkedList< T >::const_iterator::operator-- (int) inline
{ const_iterator o= i; i= i.previous(); return o; }
References orgQhull::QhullLinkedList< T >::const_iterator::i.
operator-=()
template<typename T > const_iterator & orgQhull::QhullLinkedList< T >::const_iterator::operator-= (int j) inline
{ return (*this= *this - j); }
operator->()
template<typename T > const T * orgQhull::QhullLinkedList< T >::const_iterator::operator-> () const inline
{ return i; }
References orgQhull::QhullLinkedList< T >::const_iterator::i.
operator=()
template<typename T > const_iterator & orgQhull::QhullLinkedList< T >::const_iterator::operator= (const const_iterator & o) inline
{ i= o.i; return *this; }
References orgQhull::QhullLinkedList< T >::const_iterator::i.
operator==()
template<typename T > bool orgQhull::QhullLinkedList< T >::const_iterator::operator== (const const_iterator & o) const inline
{ return i == o.i; }
References orgQhull::QhullLinkedList< T >::const_iterator::i.
Referenced by orgQhull::QhullLinkedList< T >::const_iterator::operator!=().
Member Data Documentation
i
template<typename T > T orgQhull::QhullLinkedList< T >::const_iterator::i private
Referenced by orgQhull::QhullLinkedList< T >::const_iterator::operator*(), orgQhull::QhullLinkedList< T >::const_iterator::operator++(), orgQhull::QhullLinkedList< T >::const_iterator::operator++(), orgQhull::QhullLinkedList< T >::const_iterator::operator--(), orgQhull::QhullLinkedList< T >::const_iterator::operator--(), orgQhull::QhullLinkedList< T >::const_iterator::operator->(), orgQhull::QhullLinkedList< T >::const_iterator::operator=(), and orgQhull::QhullLinkedList< T >::const_iterator::operator==().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullLinkedList.h