OrcaSlicer: orgQhull::QhullSet< T >::iterator Class Reference
orgQhull::QhullSet< T >::iterator Class Reference
#include <src/qhull/src/libqhullcpp/QhullSet.h>
Public Types
typedef ptrdiff_t difference_type
typedef std::bidirectional_iterator_tag iterator_category
typedef T value_type
Public Member Functions
iterator (QhullQh *qqh, typename T::base_type *p)
iterator (const iterator &o)
iterator & operator= (const iterator &o)
T operator* () const
T operator[] (countT idx) const
No error checking.
bool operator== (const iterator &o) const
bool operator!= (const iterator &o) const
bool operator== (const const_iterator &o) const
bool operator!= (const const_iterator &o) const
countT operator- (const iterator &o) const
Assumes same point set.
bool operator> (const iterator &o) const
bool operator<= (const iterator &o) const
bool operator< (const iterator &o) const
bool operator>= (const iterator &o) const
bool operator> (const const_iterator &o) const
bool operator<= (const const_iterator &o) const
bool operator< (const const_iterator &o) const
bool operator>= (const const_iterator &o) const
iterator & operator++ ()
No error checking.
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
iterator operator+ (countT j) const
iterator operator- (countT j) const
iterator & operator+= (countT j)
iterator & operator-= (countT j)
Private Attributes
T::base_type * i
QhullQh * qh_qh
Friends
class const_iterator
Detailed Description
template<typename T>
class orgQhull::QhullSet< T >::iterator
Member Typedef Documentation
difference_type
template<typename T > typedef ptrdiff_t orgQhull::QhullSet< T >::iterator::difference_type
iterator_category
template<typename T > typedef std::bidirectional_iterator_tag orgQhull::QhullSet< T >::iterator::iterator_category
value_type
template<typename T > typedef T orgQhull::QhullSet< T >::iterator::value_type
Constructor & Destructor Documentation
iterator() [1/2]
template<typename T > orgQhull::QhullSet< T >::iterator::iterator (QhullQh * qqh, typename T::base_type * p) inline
: i(p), qh_qh(qqh) {}
iterator() [2/2]
template<typename T > orgQhull::QhullSet< T >::iterator::iterator (const iterator & o) inline
: i(o.i), qh_qh(o.qh_qh) {}
Member Function Documentation
operator!=() [1/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator!= (const const_iterator & o) const inline
{ return !operator==(o); }
References orgQhull::QhullSet< T >::iterator::operator==().
operator!=() [2/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator!= (const iterator & o) const inline
{ return !operator==(o); }
References orgQhull::QhullSet< T >::iterator::operator==().
operator*()
template<typename T > T orgQhull::QhullSet< T >::iterator::operator* () const inline
{ return T(qh_qh, *i); }
References orgQhull::QhullSet< T >::iterator::i, and orgQhull::QhullSet< T >::iterator::qh_qh.
operator+()
template<typename T > iterator orgQhull::QhullSet< T >::iterator::operator+ (countT j) const inline
{ return iterator(qh_qh, i+j); }
References orgQhull::QhullSet< T >::iterator::i, and orgQhull::QhullSet< T >::iterator::qh_qh.
Referenced by orgQhull::QhullSet< T >::iterator::operator-().
operator++() [1/2]
template<typename T > iterator & orgQhull::QhullSet< T >::iterator::operator++ () inline
No error checking.
{ ++i; return *this; }
References orgQhull::QhullSet< T >::iterator::i.
operator++() [2/2]
template<typename T > iterator orgQhull::QhullSet< T >::iterator::operator++ (int) inline
{ iterator o= *this; ++i; return o; }
References orgQhull::QhullSet< T >::iterator::i.
operator+=()
template<typename T > iterator & orgQhull::QhullSet< T >::iterator::operator+= (countT j) inline
{ i += j; return *this; }
References orgQhull::QhullSet< T >::iterator::i.
operator-() [1/2]
template<typename T > countT orgQhull::QhullSet< T >::iterator::operator- (const iterator & o) const inline
Assumes same point set.
{ return (countT)(i-o.i); } //WARN64
References orgQhull::QhullSet< T >::iterator::i.
operator-() [2/2]
template<typename T > iterator orgQhull::QhullSet< T >::iterator::operator- (countT j) const inline
{ return operator+(-j); }
References orgQhull::QhullSet< T >::iterator::operator+().
operator--() [1/2]
template<typename T > iterator & orgQhull::QhullSet< T >::iterator::operator-- () inline
{ --i; return *this; }
References orgQhull::QhullSet< T >::iterator::i.
operator--() [2/2]
template<typename T > iterator orgQhull::QhullSet< T >::iterator::operator-- (int) inline
{ iterator o= *this; --i; return o; }
References orgQhull::QhullSet< T >::iterator::i.
operator-=()
template<typename T > iterator & orgQhull::QhullSet< T >::iterator::operator-= (countT j) inline
{ i -= j; return *this; }
References orgQhull::QhullSet< T >::iterator::i.
operator<() [1/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator< (const const_iterator & o) const inline
{ return (i < reinterpret_cast<const iterator &>(o).i); }
References orgQhull::QhullSet< T >::iterator::i.
operator<() [2/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator< (const iterator & o) const inline
{ return i<o.i; }
References orgQhull::QhullSet< T >::iterator::i.
Referenced by orgQhull::QhullSet< T >::iterator::operator>=(), and orgQhull::QhullSet< T >::iterator::operator>=().
operator<=() [1/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator<= (const const_iterator & o) const inline
{ return !operator>(o); }
References orgQhull::QhullSet< T >::iterator::operator>().
operator<=() [2/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator<= (const iterator & o) const inline
{ return !operator>(o); }
References orgQhull::QhullSet< T >::iterator::operator>().
operator=()
template<typename T > iterator & orgQhull::QhullSet< T >::iterator::operator= (const iterator & o) inline
{ i= o.i; qh_qh= o.qh_qh; return *this; }
References orgQhull::QhullSet< T >::iterator::i, and orgQhull::QhullSet< T >::iterator::qh_qh.
operator==() [1/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator== (const const_iterator & o) const inline
{ return (i==reinterpret_cast<const iterator &>(o).i); }
References orgQhull::QhullSet< T >::iterator::i.
operator==() [2/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator== (const iterator & o) const inline
{ return i == o.i; }
References orgQhull::QhullSet< T >::iterator::i.
Referenced by orgQhull::QhullSet< T >::iterator::operator!=(), and orgQhull::QhullSet< T >::iterator::operator!=().
operator>() [1/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator> (const const_iterator & o) const inline
{ return (i > reinterpret_cast<const iterator &>(o).i); }
References orgQhull::QhullSet< T >::iterator::i.
operator>() [2/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator> (const iterator & o) const inline
{ return i>o.i; }
References orgQhull::QhullSet< T >::iterator::i.
Referenced by orgQhull::QhullSet< T >::iterator::operator<=(), and orgQhull::QhullSet< T >::iterator::operator<=().
operator>=() [1/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator>= (const const_iterator & o) const inline
{ return !operator<(o); }
References orgQhull::QhullSet< T >::iterator::operator<().
operator>=() [2/2]
template<typename T > bool orgQhull::QhullSet< T >::iterator::operator>= (const iterator & o) const inline
{ return !operator<(o); }
References orgQhull::QhullSet< T >::iterator::operator<().
operator[]()
template<typename T > T orgQhull::QhullSet< T >::iterator::operator[] (countT idx) const inline
No error checking.
References orgQhull::QhullSet< T >::iterator::i, and orgQhull::QhullSet< T >::iterator::qh_qh.
Friends And Related Symbol Documentation
const_iterator
template<typename T > friend class const_iterator friend
Member Data Documentation
i
template<typename T > T::base_type* orgQhull::QhullSet< T >::iterator::i private
Referenced by orgQhull::QhullSet< T >::iterator::operator*(), orgQhull::QhullSet< T >::iterator::operator+(), orgQhull::QhullSet< T >::iterator::operator++(), orgQhull::QhullSet< T >::iterator::operator++(), orgQhull::QhullSet< T >::iterator::operator+=(), orgQhull::QhullSet< T >::iterator::operator-(), orgQhull::QhullSet< T >::iterator::operator--(), orgQhull::QhullSet< T >::iterator::operator--(), orgQhull::QhullSet< T >::iterator::operator-=(), orgQhull::QhullSet< T >::iterator::operator<(), orgQhull::QhullSet< T >::iterator::operator<(), orgQhull::QhullSet< T >::iterator::operator=(), orgQhull::QhullSet< T >::iterator::operator==(), orgQhull::QhullSet< T >::iterator::operator==(), orgQhull::QhullSet< T >::iterator::operator>(), orgQhull::QhullSet< T >::iterator::operator>(), and orgQhull::QhullSet< T >::iterator::operator[]().
qh_qh
template<typename T > QhullQh* orgQhull::QhullSet< T >::iterator::qh_qh private
Referenced by orgQhull::QhullSet< T >::iterator::operator*(), orgQhull::QhullSet< T >::iterator::operator+(), orgQhull::QhullSet< T >::iterator::operator=(), and orgQhull::QhullSet< T >::iterator::operator[]().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullSet.h