OrcaSlicer: Slic3r::GUI::WebViewPanel Class Reference
Slic3r::GUI::WebViewPanel Class Reference
#include <src/slic3r/GUI/WebViewDialog.hpp>
Public Member Functions
WebViewPanel (wxWindow *parent)
virtual ~WebViewPanel ()
void load_url (wxString &url)
void UpdateState ()
void OnIdle (wxIdleEvent &evt)
void OnUrl (wxCommandEvent &evt)
void OnBack (wxCommandEvent &evt)
void OnForward (wxCommandEvent &evt)
void OnStop (wxCommandEvent &evt)
void OnReload (wxCommandEvent &evt)
void OnNavigationRequest (wxWebViewEvent &evt)
void OnNavigationComplete (wxWebViewEvent &evt)
void OnDocumentLoaded (wxWebViewEvent &evt)
void OnTitleChanged (wxWebViewEvent &evt)
void OnNewWindow (wxWebViewEvent &evt)
void OnScriptMessage (wxWebViewEvent &evt)
void OnScriptResponseMessage (wxCommandEvent &evt)
void OnViewSourceRequest (wxCommandEvent &evt)
void OnViewTextRequest (wxCommandEvent &evt)
void OnToolsClicked (wxCommandEvent &evt)
void OnError (wxWebViewEvent &evt)
void OnCut (wxCommandEvent &evt)
void OnCopy (wxCommandEvent &evt)
void OnPaste (wxCommandEvent &evt)
void OnUndo (wxCommandEvent &evt)
void OnRedo (wxCommandEvent &evt)
void OnMode (wxCommandEvent &evt)
void RunScript (const wxString &javascript)
void OnRunScriptString (wxCommandEvent &evt)
void OnRunScriptInteger (wxCommandEvent &evt)
void OnRunScriptDouble (wxCommandEvent &evt)
void OnRunScriptBool (wxCommandEvent &evt)
void OnRunScriptObject (wxCommandEvent &evt)
void OnRunScriptArray (wxCommandEvent &evt)
void OnRunScriptDOM (wxCommandEvent &evt)
void OnRunScriptUndefined (wxCommandEvent &evt)
void OnRunScriptNull (wxCommandEvent &evt)
void OnRunScriptDate (wxCommandEvent &evt)
void OnRunScriptMessage (wxCommandEvent &evt)
void OnRunScriptCustom (wxCommandEvent &evt)
void OnAddUserScript (wxCommandEvent &evt)
void OnSetCustomUserAgent (wxCommandEvent &evt)
void OnClearSelection (wxCommandEvent &evt)
void OnDeleteSelection (wxCommandEvent &evt)
void OnSelectAll (wxCommandEvent &evt)
void OnLoadScheme (wxCommandEvent &evt)
void OnUseMemoryFS (wxCommandEvent &evt)
void OnEnableContextMenu (wxCommandEvent &evt)
void OnEnableDevTools (wxCommandEvent &evt)
void OnClose (wxCloseEvent &evt)
void OnFreshLoginStatus (wxTimerEvent &event)
void SendRecentList (wxString const &sequence_id)
void SendLoginInfo ()
void ShowNetpluginTip ()
void update_mode ()
Public Attributes
wxTimer * m_LoginUpdateTimer {nullptr}
Private Attributes
wxWebView * m_browser
wxBoxSizer * bSizer_toolbar
wxButton * m_button_back
wxButton * m_button_forward
wxButton * m_button_stop
wxButton * m_button_reload
wxTextCtrl * m_url
wxButton * m_button_tools
wxMenu * m_tools_menu
wxMenuItem * m_tools_handle_navigation
wxMenuItem * m_tools_handle_new_window
wxMenuItem * m_edit_cut
wxMenuItem * m_edit_copy
wxMenuItem * m_edit_paste
wxMenuItem * m_edit_undo
wxMenuItem * m_edit_redo
wxMenuItem * m_edit_mode
wxMenuItem * m_scroll_line_up
wxMenuItem * m_scroll_line_down
wxMenuItem * m_scroll_page_up
wxMenuItem * m_scroll_page_down
wxMenuItem * m_script_string
wxMenuItem * m_script_integer
wxMenuItem * m_script_double
wxMenuItem * m_script_bool
wxMenuItem * m_script_object
wxMenuItem * m_script_array
wxMenuItem * m_script_dom
wxMenuItem * m_script_undefined
wxMenuItem * m_script_null
wxMenuItem * m_script_date
wxMenuItem * m_script_message
wxMenuItem * m_script_custom
wxMenuItem * m_selection_clear
wxMenuItem * m_selection_delete
wxMenuItem * m_context_menu
wxMenuItem * m_dev_tools
wxInfoBar * m_info
wxStaticText * m_info_text
long m_zoomFactor
wxString m_javascript
wxString m_response_js
Detailed Description
Constructor & Destructor Documentation
WebViewPanel()
Slic3r::GUI::WebViewPanel::WebViewPanel (wxWindow * parent)
        : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize)
 {
    wxString url = wxString::Format("file://%s/web/homepage/index.html", from_u8(resources_dir()));
    std::string strlang = wxGetApp().app_config->get("language");
    if (strlang != "")
        url = wxString::Format("file://%s/web/homepage/index.html?lang=%s", from_u8(resources_dir()), strlang);
    wxBoxSizer* topsizer = new wxBoxSizer(wxVERTICAL);
#if !BBL_RELEASE_TO_PUBLIC
    // Create the button
    bSizer_toolbar = new wxBoxSizer(wxHORIZONTAL);
    m_button_back = new wxButton(this, wxID_ANY, wxT("Back"), wxDefaultPosition, wxDefaultSize, 0);
    m_button_back->Enable(false);
    bSizer_toolbar->Add(m_button_back, 0, wxALL, 5);
    m_button_forward = new wxButton(this, wxID_ANY, wxT("Forward"), wxDefaultPosition, wxDefaultSize, 0);
    m_button_forward->Enable(false);
    bSizer_toolbar->Add(m_button_forward, 0, wxALL, 5);
    m_button_stop = new wxButton(this, wxID_ANY, wxT("Stop"), wxDefaultPosition, wxDefaultSize, 0);
    bSizer_toolbar->Add(m_button_stop, 0, wxALL, 5);
    m_button_reload = new wxButton(this, wxID_ANY, wxT("Reload"), wxDefaultPosition, wxDefaultSize, 0);
    bSizer_toolbar->Add(m_button_reload, 0, wxALL, 5);
    m_url = new wxTextCtrl(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_PROCESS_ENTER);
    bSizer_toolbar->Add(m_url, 1, wxALL | wxEXPAND, 5);
    m_button_tools = new wxButton(this, wxID_ANY, wxT("Tools"), wxDefaultPosition, wxDefaultSize, 0);
    bSizer_toolbar->Add(m_button_tools, 0, wxALL, 5);
    topsizer->Add(bSizer_toolbar, 0, wxEXPAND, 0);
    bSizer_toolbar->Show(false);
    // Create panel for find toolbar.
    wxPanel* panel = new wxPanel(this);
    topsizer->Add(panel, wxSizerFlags().Expand());
    // Create sizer for panel.
    wxBoxSizer* panel_sizer = new wxBoxSizer(wxVERTICAL);
    panel->SetSizer(panel_sizer);
#endif //BBL_RELEASE_TO_PUBLIC
    // Create the info panel
    m_info = new wxInfoBar(this);
    topsizer->Add(m_info, wxSizerFlags().Expand());
    // Create the webview
    m_browser = WebView::CreateWebView(this, url);
    if (m_browser == nullptr) {
        wxLogError("Could not init m_browser");
        return;
    }
    m_browser->Hide();
    SetSizer(topsizer);
    topsizer->Add(m_browser, wxSizerFlags().Expand().Proportion(1));
    // Log backend information
    if (wxGetApp().get_mode() == comDevelop) {
        wxLogMessage(wxWebView::GetBackendVersionInfo().ToString());
        wxLogMessage("Backend: %s Version: %s", m_browser->GetClassInfo()->GetClassName(),
            wxWebView::GetBackendVersionInfo().ToString());
        wxLogMessage("User Agent: %s", m_browser->GetUserAgent());
    }
    // Create the Tools menu
    m_tools_menu = new wxMenu();
    wxMenuItem* viewSource = m_tools_menu->Append(wxID_ANY, _L("View Source"));
    wxMenuItem* viewText = m_tools_menu->Append(wxID_ANY, _L("View Text"));
    m_tools_menu->AppendSeparator();
    m_tools_handle_navigation = m_tools_menu->AppendCheckItem(wxID_ANY, _L("Handle Navigation"));
    m_tools_handle_new_window = m_tools_menu->AppendCheckItem(wxID_ANY, _L("Handle New Windows"));
    m_tools_menu->AppendSeparator();
    //Create an editing menu
    wxMenu* editmenu = new wxMenu();
    m_edit_cut = editmenu->Append(wxID_ANY, _L("Cut"));
    m_edit_copy = editmenu->Append(wxID_ANY, _L("Copy"));
    m_edit_paste = editmenu->Append(wxID_ANY, _L("Paste"));
    editmenu->AppendSeparator();
    m_edit_undo = editmenu->Append(wxID_ANY, _L("Undo"));
    m_edit_redo = editmenu->Append(wxID_ANY, _L("Redo"));
    editmenu->AppendSeparator();
    m_edit_mode = editmenu->AppendCheckItem(wxID_ANY, _L("Edit Mode"));
    m_tools_menu->AppendSubMenu(editmenu, "Edit");
    wxMenu* script_menu = new wxMenu;
    m_script_string = script_menu->Append(wxID_ANY, "Return String");
    m_script_integer = script_menu->Append(wxID_ANY, "Return integer");
    m_script_double = script_menu->Append(wxID_ANY, "Return double");
    m_script_bool = script_menu->Append(wxID_ANY, "Return bool");
    m_script_object = script_menu->Append(wxID_ANY, "Return JSON object");
    m_script_array = script_menu->Append(wxID_ANY, "Return array");
    m_script_dom = script_menu->Append(wxID_ANY, "Modify DOM");
    m_script_undefined = script_menu->Append(wxID_ANY, "Return undefined");
    m_script_null = script_menu->Append(wxID_ANY, "Return null");
    m_script_date = script_menu->Append(wxID_ANY, "Return Date");
    m_script_message = script_menu->Append(wxID_ANY, "Send script message");
    m_script_custom = script_menu->Append(wxID_ANY, "Custom script");
    m_tools_menu->AppendSubMenu(script_menu, _L("Run Script"));
    wxMenuItem* addUserScript = m_tools_menu->Append(wxID_ANY, _L("Add user script"));
    wxMenuItem* setCustomUserAgent = m_tools_menu->Append(wxID_ANY, _L("Set custom user agent"));
    //Selection menu
    wxMenu* selection = new wxMenu();
    m_selection_clear = selection->Append(wxID_ANY, _L("Clear Selection"));
    m_selection_delete = selection->Append(wxID_ANY, _L("Delete Selection"));
    wxMenuItem* selectall = selection->Append(wxID_ANY, _L("Select All"));
    editmenu->AppendSubMenu(selection, "Selection");
    wxMenuItem* loadscheme = m_tools_menu->Append(wxID_ANY, _L("Custom Scheme Example"));
    wxMenuItem* usememoryfs = m_tools_menu->Append(wxID_ANY, _L("Memory File System Example"));
    m_context_menu = m_tools_menu->AppendCheckItem(wxID_ANY, _L("Enable Context Menu"));
    m_dev_tools = m_tools_menu->AppendCheckItem(wxID_ANY, _L("Enable Dev Tools"));
    //By default we want to handle navigation and new windows
    m_tools_handle_navigation->Check();
    m_tools_handle_new_window->Check();
    //Zoom
    m_zoomFactor = 100;
    // Connect the button events
#if !BBL_RELEASE_TO_PUBLIC
    Bind(wxEVT_BUTTON, &WebViewPanel::OnBack, this, m_button_back->GetId());
    Bind(wxEVT_BUTTON, &WebViewPanel::OnForward, this, m_button_forward->GetId());
    Bind(wxEVT_BUTTON, &WebViewPanel::OnStop, this, m_button_stop->GetId());
    Bind(wxEVT_BUTTON, &WebViewPanel::OnReload, this, m_button_reload->GetId());
    Bind(wxEVT_BUTTON, &WebViewPanel::OnToolsClicked, this, m_button_tools->GetId());
    Bind(wxEVT_TEXT_ENTER, &WebViewPanel::OnUrl, this, m_url->GetId());
#endif //BBL_RELEASE_TO_PUBLIC
    // Connect the webview events
    Bind(wxEVT_WEBVIEW_NAVIGATING, &WebViewPanel::OnNavigationRequest, this);
    Bind(wxEVT_WEBVIEW_NAVIGATED, &WebViewPanel::OnNavigationComplete, this);
    Bind(wxEVT_WEBVIEW_LOADED, &WebViewPanel::OnDocumentLoaded, this);
    Bind(wxEVT_WEBVIEW_TITLE_CHANGED, &WebViewPanel::OnTitleChanged, this);
    Bind(wxEVT_WEBVIEW_ERROR, &WebViewPanel::OnError, this);
    Bind(wxEVT_WEBVIEW_NEWWINDOW, &WebViewPanel::OnNewWindow, this);
    Bind(wxEVT_WEBVIEW_SCRIPT_MESSAGE_RECEIVED, &WebViewPanel::OnScriptMessage, this);
    Bind(EVT_RESPONSE_MESSAGE, &WebViewPanel::OnScriptResponseMessage, this);
    // Connect the menu events
    Bind(wxEVT_MENU, &WebViewPanel::OnViewSourceRequest, this, viewSource->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnViewTextRequest, this, viewText->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnCut, this, m_edit_cut->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnCopy, this, m_edit_copy->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnPaste, this, m_edit_paste->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnUndo, this, m_edit_undo->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRedo, this, m_edit_redo->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnMode, this, m_edit_mode->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptString, this, m_script_string->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptInteger, this, m_script_integer->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptDouble, this, m_script_double->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptBool, this, m_script_bool->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptObject, this, m_script_object->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptArray, this, m_script_array->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptDOM, this, m_script_dom->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptUndefined, this, m_script_undefined->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptNull, this, m_script_null->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptDate, this, m_script_date->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptMessage, this, m_script_message->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnRunScriptCustom, this, m_script_custom->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnAddUserScript, this, addUserScript->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnSetCustomUserAgent, this, setCustomUserAgent->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnClearSelection, this, m_selection_clear->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnDeleteSelection, this, m_selection_delete->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnSelectAll, this, selectall->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnLoadScheme, this, loadscheme->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnUseMemoryFS, this, usememoryfs->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnEnableContextMenu, this, m_context_menu->GetId());
    Bind(wxEVT_MENU, &WebViewPanel::OnEnableDevTools, this, m_dev_tools->GetId());
    //Connect the idle events
    Bind(wxEVT_IDLE, &WebViewPanel::OnIdle, this);
    Bind(wxEVT_CLOSE_WINDOW, &WebViewPanel::OnClose, this);
    m_LoginUpdateTimer = nullptr;
 }
References _L, Slic3r::comDevelop, WebView::CreateWebView(), Slic3r::GUI::from_u8(), OnAddUserScript(), OnBack(), OnClearSelection(), OnClose(), OnCopy(), OnCut(), OnDeleteSelection(), OnDocumentLoaded(), OnEnableContextMenu(), OnEnableDevTools(), OnError(), OnForward(), OnIdle(), OnLoadScheme(), OnMode(), OnNavigationComplete(), OnNavigationRequest(), OnNewWindow(), OnPaste(), OnRedo(), OnReload(), OnRunScriptArray(), OnRunScriptBool(), OnRunScriptCustom(), OnRunScriptDate(), OnRunScriptDOM(), OnRunScriptDouble(), OnRunScriptInteger(), OnRunScriptMessage(), OnRunScriptNull(), OnRunScriptObject(), OnRunScriptString(), OnRunScriptUndefined(), OnScriptMessage(), OnScriptResponseMessage(), OnSelectAll(), OnSetCustomUserAgent(), OnStop(), OnTitleChanged(), OnToolsClicked(), OnUndo(), OnUrl(), OnUseMemoryFS(), OnViewSourceRequest(), OnViewTextRequest(), Slic3r::resources_dir(), wxButton, and wxEVT_BUTTON.
~WebViewPanel()
Slic3r::GUI::WebViewPanel::~WebViewPanel () virtual
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << " Start";
    SetEvtHandlerEnabled(false);
    delete m_tools_menu;
    if (m_LoginUpdateTimer != nullptr) {
        m_LoginUpdateTimer->Stop();
        delete m_LoginUpdateTimer;
        m_LoginUpdateTimer = NULL;
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << " End";
}
References m_LoginUpdateTimer, m_tools_menu, and NULL.
Member Function Documentation
load_url()
void Slic3r::GUI::WebViewPanel::load_url (wxString & url)
{
    this->Show();
    this->Raise();
    m_url->SetLabelText(url);
    if (wxGetApp().get_mode() == comDevelop)
        wxLogMessage(m_url->GetValue());
    m_browser->LoadURL(url);
    m_browser->SetFocus();
    UpdateState();
}
References Slic3r::comDevelop, m_browser, m_url, and UpdateState().
OnAddUserScript()
void Slic3r::GUI::WebViewPanel::OnAddUserScript (wxCommandEvent & evt)
{
    wxString userScript = "window.wx_test_var = 'wxWidgets webview sample';";
    wxTextEntryDialog dialog
    (
        this,
        "Enter the JavaScript code to run as the initialization script that runs before any script in the HTML document.",
        wxGetTextFromUserPromptStr,
        userScript,
        wxOK | wxCANCEL | wxCENTRE | wxTE_MULTILINE
    );
    if (dialog.ShowModal() != wxID_OK)
        return;
    if (!m_browser->AddUserScript(dialog.GetValue()))
        wxLogError("Could not add user script");
}
References m_browser.
Referenced by WebViewPanel().
OnBack()
void Slic3r::GUI::WebViewPanel::OnBack (wxCommandEvent & evt)
Callback invoked when user pressed the "back" button
{
    m_browser->GoBack();
    UpdateState();
}
References m_browser, and UpdateState().
Referenced by WebViewPanel().
OnClearSelection()
void Slic3r::GUI::WebViewPanel::OnClearSelection (wxCommandEvent & evt)
{
    m_browser->ClearSelection();
}
References m_browser.
Referenced by WebViewPanel().
OnClose()
void Slic3r::GUI::WebViewPanel::OnClose (wxCloseEvent & evt)
{
    this->Hide();
}
Referenced by WebViewPanel().
OnCopy()
void Slic3r::GUI::WebViewPanel::OnCopy (wxCommandEvent & evt)
{
    m_browser->Copy();
}
References m_browser.
Referenced by WebViewPanel().
OnCut()
void Slic3r::GUI::WebViewPanel::OnCut (wxCommandEvent & evt)
{
    m_browser->Cut();
}
References m_browser.
Referenced by WebViewPanel().
OnDeleteSelection()
void Slic3r::GUI::WebViewPanel::OnDeleteSelection (wxCommandEvent & evt)
{
    m_browser->DeleteSelection();
}
References m_browser.
Referenced by WebViewPanel().
OnDocumentLoaded()
void Slic3r::GUI::WebViewPanel::OnDocumentLoaded (wxWebViewEvent & evt)
Callback invoked when a page is finished loading
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": " << evt.GetTarget().ToUTF8().data();
    // Only notify if the document is the main frame, not a subframe
    if (evt.GetURL() == m_browser->GetCurrentURL())
    {
        if (wxGetApp().get_mode() == comDevelop)
            wxLogMessage("%s", "Document loaded; url='" + evt.GetURL() + "'");
    }
    UpdateState();
    ShowNetpluginTip();
}
References Slic3r::comDevelop, m_browser, ShowNetpluginTip(), and UpdateState().
Referenced by WebViewPanel().
OnEnableContextMenu()
void Slic3r::GUI::WebViewPanel::OnEnableContextMenu (wxCommandEvent & evt)
{
    m_browser->EnableContextMenu(evt.IsChecked());
}
References m_browser.
Referenced by WebViewPanel().
OnEnableDevTools()
void Slic3r::GUI::WebViewPanel::OnEnableDevTools (wxCommandEvent & evt)
{
    m_browser->EnableAccessToDevTools(evt.IsChecked());
}
References m_browser.
Referenced by WebViewPanel().
OnError()
void Slic3r::GUI::WebViewPanel::OnError (wxWebViewEvent & evt)
Callback invoked when a loading error occurs
{
#define WX_ERROR_CASE(type) \
    case type: \
    category = #type; \
    break;
    wxString category;
    switch (evt.GetInt())
    {
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_CONNECTION);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_CERTIFICATE);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_AUTH);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_SECURITY);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_NOT_FOUND);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_REQUEST);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_USER_CANCELLED);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_OTHER);
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": [" << category << "] " << evt.GetString().ToUTF8().data();
    if (wxGetApp().get_mode() == comDevelop)
        wxLogMessage("%s", "Error; url='" + evt.GetURL() + "', error='" + category + " (" + evt.GetString() + ")'");
    //Show the info bar with an error
    m_info->ShowMessage(_L("An error occurred loading ") + evt.GetURL() + "\n" +
        "'" + category + "'", wxICON_ERROR);
    UpdateState();
}
References _L, Slic3r::comDevelop, m_info, UpdateState(), and WX_ERROR_CASE.
Referenced by WebViewPanel().
OnForward()
void Slic3r::GUI::WebViewPanel::OnForward (wxCommandEvent & evt)
Callback invoked when user pressed the "forward" button
{
    m_browser->GoForward();
    UpdateState();
}
References m_browser, and UpdateState().
Referenced by WebViewPanel().
OnFreshLoginStatus()
void Slic3r::GUI::WebViewPanel::OnFreshLoginStatus (wxTimerEvent & event)
{
    auto mainframe = Slic3r::GUI::wxGetApp().mainframe;
    if (mainframe && mainframe->m_webview == this)
        Slic3r::GUI::wxGetApp().get_login_info();
}
OnIdle()
void Slic3r::GUI::WebViewPanel::OnIdle (wxIdleEvent & evt)
{
#if !BBL_RELEASE_TO_PUBLIC
    if (m_browser->IsBusy())
    {
        wxSetCursor(wxCURSOR_ARROWWAIT);
        m_button_stop->Enable(true);
    }
    else
    {
        wxSetCursor(wxNullCursor);
        m_button_stop->Enable(false);
    }
#endif //BBL_RELEASE_TO_PUBLIC
}
References m_browser, and m_button_stop.
Referenced by WebViewPanel().
OnLoadScheme()
void Slic3r::GUI::WebViewPanel::OnLoadScheme (wxCommandEvent & evt)
{
    wxPathList pathlist;
    pathlist.Add(".");
    pathlist.Add("..");
    pathlist.Add("../help");
    pathlist.Add("../../../samples/help");
    wxFileName helpfile(pathlist.FindValidPath("doc.zip"));
    helpfile.MakeAbsolute();
    wxString path = helpfile.GetFullPath();
    //Under MSW we need to flip the slashes
    path.Replace("\\", "/");
    path = "wxfs:///" + path + ";protocol=zip/doc.htm";
    m_browser->LoadURL(path);
}
References m_browser.
Referenced by WebViewPanel().
OnMode()
void Slic3r::GUI::WebViewPanel::OnMode (wxCommandEvent & evt)
{
    m_browser->SetEditable(m_edit_mode->IsChecked());
}
References m_browser, and m_edit_mode.
Referenced by WebViewPanel().
OnNavigationComplete()
void Slic3r::GUI::WebViewPanel::OnNavigationComplete (wxWebViewEvent & evt)
Callback invoked when a navigation request was accepted
{
    m_browser->Show();
    Layout();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": " << evt.GetTarget().ToUTF8().data();
    if (wxGetApp().get_mode() == comDevelop)
        wxLogMessage("%s", "Navigation complete; url='" + evt.GetURL() + "'");
    UpdateState();
}
References Slic3r::comDevelop, m_browser, and UpdateState().
Referenced by WebViewPanel().
OnNavigationRequest()
void Slic3r::GUI::WebViewPanel::OnNavigationRequest (wxWebViewEvent & evt)
Callback invoked when there is a request to load a new page (for instance when the user clicks a link)
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": " << evt.GetTarget().ToUTF8().data();
    const wxString &url = evt.GetURL();
    if (url.StartsWith("File://") || url.StartsWith("file://")) {
        if (!url.Contains("/web/homepage/index.html")) {
            evt.Veto();
            return;
        }
    }
    if (m_info->IsShown())
    {
        m_info->Dismiss();
    }
    if (wxGetApp().get_mode() == comDevelop)
        wxLogMessage("%s", "Navigation request to '" + evt.GetURL() + "' (target='" +
            evt.GetTarget() + "')");
    //If we don't want to handle navigation then veto the event and navigation
    //will not take place, we also need to stop the loading animation
    if (!m_tools_handle_navigation->IsChecked())
    {
        evt.Veto();
        m_button_stop->Enable(false);
    }
    else
    {
        UpdateState();
    }
}
References Slic3r::comDevelop, m_button_stop, m_info, m_tools_handle_navigation, and UpdateState().
Referenced by WebViewPanel().
OnNewWindow()
void Slic3r::GUI::WebViewPanel::OnNewWindow (wxWebViewEvent & evt)
On new window, we veto to stop extra windows appearing
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": " << evt.GetURL().ToUTF8().data();
    wxString flag = " (other)";
    if (evt.GetNavigationAction() == wxWEBVIEW_NAV_ACTION_USER)
    {
        flag = " (user)";
    }
    if (wxGetApp().get_mode() == comDevelop)
        wxLogMessage("%s", "New window; url='" + evt.GetURL() + "'" + flag);
    //If we handle new window events then just load them in this window as we
    //are a single window browser
    if (m_tools_handle_new_window->IsChecked())
        m_browser->LoadURL(evt.GetURL());
    UpdateState();
}
References Slic3r::comDevelop, m_browser, m_tools_handle_new_window, and UpdateState().
Referenced by WebViewPanel().
OnPaste()
void Slic3r::GUI::WebViewPanel::OnPaste (wxCommandEvent & evt)
{
    m_browser->Paste();
}
References m_browser.
Referenced by WebViewPanel().
OnRedo()
void Slic3r::GUI::WebViewPanel::OnRedo (wxCommandEvent & evt)
{
    m_browser->Redo();
}
References m_browser.
Referenced by WebViewPanel().
OnReload()
void Slic3r::GUI::WebViewPanel::OnReload (wxCommandEvent & evt)
Callback invoked when user pressed the "reload" button
{
    m_browser->Reload();
    UpdateState();
}
References m_browser, and UpdateState().
Referenced by WebViewPanel().
OnRunScriptArray()
void Slic3r::GUI::WebViewPanel::OnRunScriptArray (wxCommandEvent & evt)
{
    RunScript("function f(){ return [\"foo\", \"bar\"]; }f();");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptBool()
void Slic3r::GUI::WebViewPanel::OnRunScriptBool (wxCommandEvent & evt)
{
    RunScript("function f(a){return a;}f(false);");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptCustom()
void Slic3r::GUI::WebViewPanel::OnRunScriptCustom (wxCommandEvent & evt)
{
    wxTextEntryDialog dialog
    (
        this,
        "Please enter JavaScript code to execute",
        wxGetTextFromUserPromptStr,
        m_javascript,
        wxOK | wxCANCEL | wxCENTRE | wxTE_MULTILINE
    );
    if (dialog.ShowModal() != wxID_OK)
        return;
    RunScript(dialog.GetValue());
}
References m_javascript, and RunScript().
Referenced by WebViewPanel().
OnRunScriptDate()
void Slic3r::GUI::WebViewPanel::OnRunScriptDate (wxCommandEvent & evt)
{
    RunScript("function f(){var d = new Date('10/08/2017 21:30:40'); \
    var tzoffset = d.getTimezoneOffset() * 60000; \
    return new Date(d.getTime() - tzoffset);}f();");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptDOM()
void Slic3r::GUI::WebViewPanel::OnRunScriptDOM (wxCommandEvent & evt)
{
    RunScript("document.write(\"Hello World!\");");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptDouble()
void Slic3r::GUI::WebViewPanel::OnRunScriptDouble (wxCommandEvent & evt)
{
    RunScript("function f(a){return a;}f(2.34);");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptInteger()
void Slic3r::GUI::WebViewPanel::OnRunScriptInteger (wxCommandEvent & evt)
{
    RunScript("function f(a){return a;}f(123);");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptMessage()
void Slic3r::GUI::WebViewPanel::OnRunScriptMessage (wxCommandEvent & evt)
{
    RunScript("window.wx.postMessage('This is a web message');");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptNull()
void Slic3r::GUI::WebViewPanel::OnRunScriptNull (wxCommandEvent & evt)
{
    RunScript("function f(){return null;}f();");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptObject()
void Slic3r::GUI::WebViewPanel::OnRunScriptObject (wxCommandEvent & evt)
{
    RunScript("function f(){var person = new Object();person.name = 'Foo'; \
    person.lastName = 'Bar';return person;}f();");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptString()
void Slic3r::GUI::WebViewPanel::OnRunScriptString (wxCommandEvent & evt)
{
    RunScript("setCount(345);");
}
References RunScript().
Referenced by WebViewPanel().
OnRunScriptUndefined()
void Slic3r::GUI::WebViewPanel::OnRunScriptUndefined (wxCommandEvent & evt)
{
    RunScript("function f(){var person = new Object();}f();");
}
References RunScript().
Referenced by WebViewPanel().
OnScriptMessage()
void Slic3r::GUI::WebViewPanel::OnScriptMessage (wxWebViewEvent & evt)
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": " << evt.GetString().ToUTF8().data();
    // update login status
    if (m_LoginUpdateTimer == nullptr) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << " Create Timer";
        m_LoginUpdateTimer = new wxTimer(this, LOGIN_INFO_UPDATE_TIMER_ID);
        m_LoginUpdateTimer->Start(2000);
    }
    if (wxGetApp().get_mode() == comDevelop)
        wxLogMessage("Script message received; value = %s, handler = %s", evt.GetString(), evt.GetMessageHandler());
    std::string response = wxGetApp().handle_web_request(evt.GetString().ToUTF8().data());
    if (response.empty()) return;
    /* remove \n in response string */
    response.erase(std::remove(response.begin(), response.end(), '\n'), response.end());
    if (!response.empty()) {
        m_response_js = wxString::Format("window.postMessage('%s')", response);
        wxCommandEvent* event = new wxCommandEvent(EVT_RESPONSE_MESSAGE, this->GetId());
        wxQueueEvent(this, event);
    }
    else {
        m_response_js.clear();
    }
}
References Slic3r::comDevelop, LOGIN_INFO_UPDATE_TIMER_ID, m_LoginUpdateTimer, and m_response_js.
Referenced by WebViewPanel().
OnScriptResponseMessage()
void Slic3r::GUI::WebViewPanel::OnScriptResponseMessage (wxCommandEvent & evt)
{
    if (!m_response_js.empty()) {
        RunScript(m_response_js);
    }
}
References m_response_js, and RunScript().
Referenced by WebViewPanel().
OnSelectAll()
void Slic3r::GUI::WebViewPanel::OnSelectAll (wxCommandEvent & evt)
{
    m_browser->SelectAll();
}
References m_browser.
Referenced by WebViewPanel().
OnSetCustomUserAgent()
void Slic3r::GUI::WebViewPanel::OnSetCustomUserAgent (wxCommandEvent & evt)
{
    wxString customUserAgent = "Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_3 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Mobile/15E148 Safari/604.1";
    wxTextEntryDialog dialog
    (
        this,
        "Enter the custom user agent string you would like to use.",
        wxGetTextFromUserPromptStr,
        customUserAgent,
        wxOK | wxCANCEL | wxCENTRE
    );
    if (dialog.ShowModal() != wxID_OK)
        return;
    if (!m_browser->SetUserAgent(customUserAgent))
        wxLogError("Could not set custom user agent");
}
References m_browser.
Referenced by WebViewPanel().
OnStop()
void Slic3r::GUI::WebViewPanel::OnStop (wxCommandEvent & evt)
Callback invoked when user pressed the "stop" button
{
    m_browser->Stop();
    UpdateState();
}
References m_browser, and UpdateState().
Referenced by WebViewPanel().
OnTitleChanged()
void Slic3r::GUI::WebViewPanel::OnTitleChanged (wxWebViewEvent & evt)
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ": " << evt.GetString().ToUTF8().data();
    // wxGetApp().CallAfter([this] { SendRecentList(); });
}
Referenced by WebViewPanel().
OnToolsClicked()
void Slic3r::GUI::WebViewPanel::OnToolsClicked (wxCommandEvent & evt)
Invoked when user selects the "Menu" item
{
    if (m_browser->GetCurrentURL() == "")
        return;
    m_edit_cut->Enable(m_browser->CanCut());
    m_edit_copy->Enable(m_browser->CanCopy());
    m_edit_paste->Enable(m_browser->CanPaste());
    m_edit_undo->Enable(m_browser->CanUndo());
    m_edit_redo->Enable(m_browser->CanRedo());
    m_selection_clear->Enable(m_browser->HasSelection());
    m_selection_delete->Enable(m_browser->HasSelection());
    m_context_menu->Check(m_browser->IsContextMenuEnabled());
    m_dev_tools->Check(m_browser->IsAccessToDevToolsEnabled());
    wxPoint position = ScreenToClient(wxGetMousePosition());
    PopupMenu(m_tools_menu, position.x, position.y);
}
References m_browser, m_context_menu, m_dev_tools, m_edit_copy, m_edit_cut, m_edit_paste, m_edit_redo, m_edit_undo, m_selection_clear, m_selection_delete, and m_tools_menu.
Referenced by WebViewPanel().
OnUndo()
void Slic3r::GUI::WebViewPanel::OnUndo (wxCommandEvent & evt)
{
    m_browser->Undo();
}
References m_browser.
Referenced by WebViewPanel().
OnUrl()
void Slic3r::GUI::WebViewPanel::OnUrl (wxCommandEvent & evt)
Callback invoked when user entered an URL and pressed enter
{
    if (wxGetApp().get_mode() == comDevelop)
        wxLogMessage(m_url->GetValue());
    m_browser->LoadURL(m_url->GetValue());
    m_browser->SetFocus();
    UpdateState();
}
References Slic3r::comDevelop, m_browser, m_url, and UpdateState().
Referenced by WebViewPanel().
OnUseMemoryFS()
void Slic3r::GUI::WebViewPanel::OnUseMemoryFS (wxCommandEvent & evt)
{
    m_browser->LoadURL("memory:page1.htm");
}
References m_browser.
Referenced by WebViewPanel().
OnViewSourceRequest()
void Slic3r::GUI::WebViewPanel::OnViewSourceRequest (wxCommandEvent & evt)
Invoked when user selects the "View Source" menu item
{
    SourceViewDialog dlg(this, m_browser->GetPageSource());
    dlg.ShowModal();
}
References m_browser.
Referenced by WebViewPanel().
OnViewTextRequest()
void Slic3r::GUI::WebViewPanel::OnViewTextRequest (wxCommandEvent & evt)
Invoked when user selects the "View Text" menu item
{
    wxDialog textViewDialog(this, wxID_ANY, "Page Text",
        wxDefaultPosition, wxSize(700, 500),
        wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER);
    wxTextCtrl* text = new wxTextCtrl(this, wxID_ANY, m_browser->GetPageText(),
        wxDefaultPosition, wxDefaultSize,
        wxTE_MULTILINE |
        wxTE_RICH |
        wxTE_READONLY);
    wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    sizer->Add(text, 1, wxEXPAND);
    SetSizer(sizer);
    textViewDialog.ShowModal();
}
References m_browser.
Referenced by WebViewPanel().
RunScript()
void Slic3r::GUI::WebViewPanel::RunScript (const wxString & javascript)
{
    // Remember the script we run in any case, so the next time the user opens
    // the "Run Script" dialog box, it is shown there for convenient updating.
    m_javascript = javascript;
    if (!m_browser) return;
    WebView::RunScript(m_browser, javascript);
}
References m_browser, m_javascript, and WebView::RunScript().
Referenced by OnRunScriptArray(), OnRunScriptBool(), OnRunScriptCustom(), OnRunScriptDate(), OnRunScriptDOM(), OnRunScriptDouble(), OnRunScriptInteger(), OnRunScriptMessage(), OnRunScriptNull(), OnRunScriptObject(), OnRunScriptString(), OnRunScriptUndefined(), OnScriptResponseMessage(), SendLoginInfo(), SendRecentList(), and ShowNetpluginTip().
SendLoginInfo()
void Slic3r::GUI::WebViewPanel::SendLoginInfo ()
{
    if (wxGetApp().getAgent()) {
        std::string login_info = wxGetApp().getAgent()->build_login_info();
        wxString strJS = wxString::Format("window.postMessage(%s)", login_info);
        RunScript(strJS);
    }
}
References RunScript().
SendRecentList()
void Slic3r::GUI::WebViewPanel::SendRecentList (wxString const & sequence_id)
{
    boost::property_tree::wptree req;
    boost::property_tree::wptree data;
    wxGetApp().mainframe->get_recent_projects(data);
    req.put(L"sequence_id", sequence_id);
    req.put(L"command", L"get_recent_projects");
    req.put_child(L"response", data);
    std::wostringstream oss;
    pt::write_json(oss, req, false);
    RunScript(wxString::Format("window.postMessage(%s)", oss.str()));
}
References L, and RunScript().
Referenced by Slic3r::GUI::GUI_App::handle_web_request().
ShowNetpluginTip()
void Slic3r::GUI::WebViewPanel::ShowNetpluginTip ()
{
    // Install Network Plugin
    //std::string NP_Installed = wxGetApp().app_config->get("installed_networking");
    bool        bValid       = wxGetApp().is_compatibility_version();
    int nShow = 0;
    if (!bValid) nShow = 1;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": bValid=%1%, nShow=%2%")%bValid %nShow;
    json m_Res           = json::object();
    m_Res["command"]     = "network_plugin_installtip";
    m_Res["sequence_id"] = "10001";
    m_Res["show"]        = nShow;
    wxString strJS = wxString::Format("window.postMessage(%s)", m_Res.dump(-1, ' ', false, json::error_handler_t::ignore));
    RunScript(strJS);
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::object(), and RunScript().
Referenced by OnDocumentLoaded().
update_mode()
void Slic3r::GUI::WebViewPanel::update_mode ()
{
    int app_mode = Slic3r::GUI::wxGetApp().get_mode();
    GetSizer()->Show(size_t(0), app_mode == comDevelop);
    GetSizer()->Layout();
}
References Slic3r::comDevelop.
Referenced by Slic3r::GUI::GUI_App::update_mode().
UpdateState()
void Slic3r::GUI::WebViewPanel::UpdateState ()
Method that retrieves the current state from the web control and updates the GUI the reflect this current state.
{
#if !BBL_RELEASE_TO_PUBLIC
    if (m_browser->CanGoBack()) {
        m_button_back->Enable(true);
    }
    else {
        m_button_back->Enable(false);
    }
    if (m_browser->CanGoForward()) {
        m_button_forward->Enable(true);
    }
    else {
        m_button_forward->Enable(false);
    }
    if (m_browser->IsBusy())
    {
        m_button_stop->Enable(true);
    }
    else
    {
        m_button_stop->Enable(false);
    }
    //SetTitle(m_browser->GetCurrentTitle());
    m_url->SetValue(m_browser->GetCurrentURL());
#endif //BBL_RELEASE_TO_PUBLIC
}
References m_browser, m_button_back, m_button_forward, m_button_stop, and m_url.
Referenced by load_url(), OnBack(), OnDocumentLoaded(), OnError(), OnForward(), OnNavigationComplete(), OnNavigationRequest(), OnNewWindow(), OnReload(), OnStop(), and OnUrl().
Member Data Documentation
bSizer_toolbar
wxBoxSizer* Slic3r::GUI::WebViewPanel::bSizer_toolbar private
m_browser
wxWebView* Slic3r::GUI::WebViewPanel::m_browser private
Referenced by load_url(), OnAddUserScript(), OnBack(), OnClearSelection(), OnCopy(), OnCut(), OnDeleteSelection(), OnDocumentLoaded(), OnEnableContextMenu(), OnEnableDevTools(), OnForward(), OnIdle(), OnLoadScheme(), OnMode(), OnNavigationComplete(), OnNewWindow(), OnPaste(), OnRedo(), OnReload(), OnSelectAll(), OnSetCustomUserAgent(), OnStop(), OnToolsClicked(), OnUndo(), OnUrl(), OnUseMemoryFS(), OnViewSourceRequest(), OnViewTextRequest(), RunScript(), and UpdateState().
m_button_back
wxButton* Slic3r::GUI::WebViewPanel::m_button_back private
Referenced by UpdateState().
m_button_forward
wxButton* Slic3r::GUI::WebViewPanel::m_button_forward private
Referenced by UpdateState().
m_button_reload
wxButton* Slic3r::GUI::WebViewPanel::m_button_reload private
m_button_stop
wxButton* Slic3r::GUI::WebViewPanel::m_button_stop private
Referenced by OnIdle(), OnNavigationRequest(), and UpdateState().
m_button_tools
wxButton* Slic3r::GUI::WebViewPanel::m_button_tools private
m_context_menu
wxMenuItem* Slic3r::GUI::WebViewPanel::m_context_menu private
Referenced by OnToolsClicked().
m_dev_tools
wxMenuItem* Slic3r::GUI::WebViewPanel::m_dev_tools private
Referenced by OnToolsClicked().
m_edit_copy
wxMenuItem* Slic3r::GUI::WebViewPanel::m_edit_copy private
Referenced by OnToolsClicked().
m_edit_cut
wxMenuItem* Slic3r::GUI::WebViewPanel::m_edit_cut private
Referenced by OnToolsClicked().
m_edit_mode
wxMenuItem* Slic3r::GUI::WebViewPanel::m_edit_mode private
Referenced by OnMode().
m_edit_paste
wxMenuItem* Slic3r::GUI::WebViewPanel::m_edit_paste private
Referenced by OnToolsClicked().
m_edit_redo
wxMenuItem* Slic3r::GUI::WebViewPanel::m_edit_redo private
Referenced by OnToolsClicked().
m_edit_undo
wxMenuItem* Slic3r::GUI::WebViewPanel::m_edit_undo private
Referenced by OnToolsClicked().
m_info
wxInfoBar* Slic3r::GUI::WebViewPanel::m_info private
Referenced by OnError(), and OnNavigationRequest().
m_info_text
wxStaticText* Slic3r::GUI::WebViewPanel::m_info_text private
m_javascript
wxString Slic3r::GUI::WebViewPanel::m_javascript private
Referenced by OnRunScriptCustom(), and RunScript().
m_LoginUpdateTimer
wxTimer* Slic3r::GUI::WebViewPanel::m_LoginUpdateTimer {nullptr}
Referenced by ~WebViewPanel(), and OnScriptMessage().
m_response_js
wxString Slic3r::GUI::WebViewPanel::m_response_js private
Referenced by OnScriptMessage(), and OnScriptResponseMessage().
m_script_array
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_array private
m_script_bool
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_bool private
m_script_custom
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_custom private
m_script_date
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_date private
m_script_dom
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_dom private
m_script_double
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_double private
m_script_integer
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_integer private
m_script_message
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_message private
m_script_null
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_null private
m_script_object
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_object private
m_script_string
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_string private
m_script_undefined
wxMenuItem* Slic3r::GUI::WebViewPanel::m_script_undefined private
m_scroll_line_down
wxMenuItem* Slic3r::GUI::WebViewPanel::m_scroll_line_down private
m_scroll_line_up
wxMenuItem* Slic3r::GUI::WebViewPanel::m_scroll_line_up private
m_scroll_page_down
wxMenuItem* Slic3r::GUI::WebViewPanel::m_scroll_page_down private
m_scroll_page_up
wxMenuItem* Slic3r::GUI::WebViewPanel::m_scroll_page_up private
m_selection_clear
wxMenuItem* Slic3r::GUI::WebViewPanel::m_selection_clear private
Referenced by OnToolsClicked().
m_selection_delete
wxMenuItem* Slic3r::GUI::WebViewPanel::m_selection_delete private
Referenced by OnToolsClicked().
m_tools_handle_navigation
wxMenuItem* Slic3r::GUI::WebViewPanel::m_tools_handle_navigation private
Referenced by OnNavigationRequest().
m_tools_handle_new_window
wxMenuItem* Slic3r::GUI::WebViewPanel::m_tools_handle_new_window private
Referenced by OnNewWindow().
m_tools_menu
wxMenu* Slic3r::GUI::WebViewPanel::m_tools_menu private
Referenced by ~WebViewPanel(), and OnToolsClicked().
m_url
wxTextCtrl* Slic3r::GUI::WebViewPanel::m_url private
Referenced by load_url(), OnUrl(), and UpdateState().
m_zoomFactor
long Slic3r::GUI::WebViewPanel::m_zoomFactor private
The documentation for this class was generated from the following files:
src/slic3r/GUI/WebViewDialog.hpp
src/slic3r/GUI/WebViewDialog.cpp