OrcaSlicer: Slic3r::GUI::ExtrusionCalibration Class Reference
Slic3r::GUI::ExtrusionCalibration Class Reference
#include <src/slic3r/GUI/ExtrusionCalibration.hpp>
Public Member Functions
ExtrusionCalibration (wxWindow *parent, wxWindowID id)
~ExtrusionCalibration ()
void create ()
void input_value_finish ()
void update ()
bool Show (bool show) override
void Popup ()
void post_select_event ()
void update_machine_obj (MachineObject *obj_)
void set_step (int step_index)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Static Public Member Functions
static bool check_k_n_validation (wxString k_text, wxString n_text)
static bool check_k_validation (wxString k_text)
Public Attributes
MachineObject * obj { nullptr }
int ams_id { 0 }
int tray_id { 0 }
std::string ams_filament_id
std::string m_filament_type
std::vector< Preset * > user_filaments
Protected Member Functions
void init_bitmaps ()
void on_dpi_changed (const wxRect &suggested_rect) override
void paint (wxPaintEvent &)
void open_bitmap (wxMouseEvent &event)
void on_select_filament (wxCommandEvent &evt)
void on_select_bed_type (wxCommandEvent &evt)
void on_select_nozzle_dia (wxCommandEvent &evt)
void on_click_cali (wxCommandEvent &evt)
void on_click_cancel (wxCommandEvent &evt)
void on_click_save (wxCommandEvent &evt)
void on_click_last (wxCommandEvent &evt)
void on_click_next (wxCommandEvent &evt)
void update_filament_info ()
void update_combobox_filaments ()
wxString get_bed_type_incompatible (bool incompatible)
void show_info (bool show, bool is_error, wxString text)
int get_bed_temp (DynamicPrintConfig *config)
virtual void on_sys_color_changed ()
Protected Attributes
StateColor m_btn_bg_green
StateColor m_btn_bg_gray
wxPanel * m_step_1_panel
wxPanel * m_step_2_panel
Label * m_filament_preset_title
ComboBox * m_comboBox_filament
ComboBox * m_comboBox_bed_type
ComboBox * m_comboBox_nozzle_dia
TextInput * m_nozzle_temp
TextInput * m_bed_temp
TextInput * m_max_flow_ratio
Button * m_cali_cancel
Button * m_button_cali
Button * m_button_next_step
Label * m_save_cali_result_title
wxStaticText * m_fill_cali_params_tips
wxStaticText * m_info_text
wxStaticText * m_error_text
wxBitmap m_calibration_tips_open_btn_bmp
wxBitmap m_calibration_tips_bmp_zh
wxBitmap m_calibration_tips_bmp_en
wxStaticBitmap * m_calibration_tips_static_bmp
wxStaticText * m_k_param
TextInput * m_k_val
wxStaticText * m_n_param
TextInput * m_n_val
Button * m_button_last_step
Button * m_button_save_result
bool m_is_zh { false }
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
ExtrusionCalibration()
Slic3r::GUI::ExtrusionCalibration::ExtrusionCalibration (wxWindow * parent, wxWindowID id)
    : DPIDialog(parent, id, _L("Dynamic flow calibration"), wxDefaultPosition, wxDefaultSize, (wxSYSTEM_MENU |
        wxMINIMIZE_BOX | wxMAXIMIZE_BOX | wxCLOSE_BOX | wxCAPTION |wxCLIP_CHILDREN))
{
    create();
    wxGetApp().UpdateDlgDarkUI(this);
}
References create().
~ExtrusionCalibration()
Slic3r::GUI::ExtrusionCalibration::~ExtrusionCalibration ()
{
    m_comboBox_filament->Disconnect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(ExtrusionCalibration::on_select_filament), NULL, this);
    m_comboBox_bed_type->Disconnect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(ExtrusionCalibration::on_select_bed_type), NULL, this);
    m_comboBox_nozzle_dia->Disconnect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(ExtrusionCalibration::on_select_nozzle_dia), NULL, this);
}
References m_comboBox_bed_type, m_comboBox_filament, m_comboBox_nozzle_dia, NULL, on_select_bed_type(), on_select_filament(), and on_select_nozzle_dia().
Member Function Documentation
check_k_n_validation()
bool Slic3r::GUI::ExtrusionCalibration::check_k_n_validation (wxString k_text, wxString n_text) static
{
    if (k_text.IsEmpty() || n_text.IsEmpty())
        return false;
    double k = 0.0;
    try {
        k_text.ToDouble(&k);
    }
    catch (...) {
        ;
    }
    double n = 0.0;
    try {
        n_text.ToDouble(&n);
    }
    catch (...) {
        ;
    }
    if (k < 0 || k > 0.5)
        return false;
    if (n < 0.6 || n > 2.0)
        return false;
    return true;
}
References n.
check_k_validation()
bool Slic3r::GUI::ExtrusionCalibration::check_k_validation (wxString k_text) static
{
    if (k_text.IsEmpty())
        return false;
    double k = 0.0;
    try {
        k_text.ToDouble(&k);
    }
    catch (...) {
        ;
    }
    if (k < 0 || k > 0.5)
        return false;
    return true;
}
Referenced by on_click_save(), and Slic3r::GUI::AMSMaterialsSetting::on_select_ok().
create()
void Slic3r::GUI::ExtrusionCalibration::create ()
{
    init_bitmaps();
    SetBackgroundColour(*wxWHITE);
    wxBoxSizer* sizer_main = new wxBoxSizer(wxVERTICAL);
    m_step_1_panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_step_1_panel->SetBackgroundColour(*wxWHITE);
    wxBoxSizer* step_1_sizer = new wxBoxSizer(wxVERTICAL);
    m_step_1_panel->SetSizer(step_1_sizer);
    step_1_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    // filament title
    wxString intro_text = _L("The nozzle temp and max volumetric speed will affect the calibration results. Please fill in the same values as the actual printing. They can be auto-filled by selecting a filament preset.");
    m_filament_preset_title = new Label(m_step_1_panel, intro_text);
    m_filament_preset_title->SetFont(Label::Body_12);
    m_filament_preset_title->SetForegroundColour(EXTRUSION_CALIBRATION_GREY800);
    m_filament_preset_title->Wrap(this->GetSize().x);
    step_1_sizer->Add(m_filament_preset_title, 0, wxEXPAND);
    step_1_sizer->AddSpacer(FromDIP(12));
    auto select_sizer = new wxBoxSizer(wxVERTICAL);
    auto nozzle_dia_sel_text = new wxStaticText(m_step_1_panel, wxID_ANY, _L("Nozzle Diameter"), wxDefaultPosition, wxDefaultSize, 0);
    select_sizer->Add(nozzle_dia_sel_text, 0, wxALIGN_LEFT);
    select_sizer->AddSpacer(FromDIP(4));
#ifdef __APPLE__
    m_comboBox_nozzle_dia = new wxComboBox(m_step_1_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, EXTRUSION_CALIBRATION_BED_COMBOX, 0, nullptr, wxCB_READONLY);
#else
    m_comboBox_nozzle_dia = new ComboBox(m_step_1_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, EXTRUSION_CALIBRATION_BED_COMBOX, 0, nullptr, wxCB_READONLY);
#endif
    m_comboBox_nozzle_dia->AppendString(wxString::Format("%1.1f", 0.2));
    m_comboBox_nozzle_dia->AppendString(wxString::Format("%1.1f", 0.4));
    m_comboBox_nozzle_dia->AppendString(wxString::Format("%1.1f", 0.6));
    m_comboBox_nozzle_dia->AppendString(wxString::Format("%1.1f", 0.8));
    select_sizer->Add(m_comboBox_nozzle_dia, 0, wxEXPAND);
    select_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    auto filament_sel_text = new wxStaticText(m_step_1_panel, wxID_ANY, _L("Filament"), wxDefaultPosition, wxDefaultSize, 0);
    select_sizer->Add(filament_sel_text, 0, wxALIGN_LEFT);
    select_sizer->AddSpacer(FromDIP(4));
#ifdef __APPLE__
    m_comboBox_filament = new wxComboBox(m_step_1_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, EXTRUSION_CALIBRATION_BED_COMBOX, 0, nullptr, wxCB_READONLY);
#else
    m_comboBox_filament = new ComboBox(m_step_1_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, EXTRUSION_CALIBRATION_BED_COMBOX, 0, nullptr, wxCB_READONLY);
#endif
    select_sizer->Add(m_comboBox_filament, 0, wxEXPAND);
    select_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    auto bed_type_sel_text = new wxStaticText(m_step_1_panel, wxID_ANY, _L("Bed Type"), wxDefaultPosition, wxDefaultSize, 0);
    select_sizer->Add(bed_type_sel_text, 0, wxALIGN_LEFT);
    select_sizer->AddSpacer(FromDIP(4));
#ifdef __APPLE__
    m_comboBox_bed_type = new wxComboBox(m_step_1_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, EXTRUSION_CALIBRATION_BED_COMBOX, 0, nullptr, wxCB_READONLY);
#else
    m_comboBox_bed_type = new ComboBox(m_step_1_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, EXTRUSION_CALIBRATION_BED_COMBOX, 0, nullptr, wxCB_READONLY);
#endif
    select_sizer->Add(m_comboBox_bed_type, 0, wxEXPAND);
    // get bed type
    const ConfigOptionDef* bed_type_def = print_config_def.get("curr_bed_type");
    if (bed_type_def && bed_type_def->enum_keys_map) {
        for (auto item : *bed_type_def->enum_keys_map) {
            if (item.first == "Default Plate")
                continue;
            m_comboBox_bed_type->AppendString(_L(item.first));
        }
    }
    step_1_sizer->Add(select_sizer, 0, wxEXPAND);
    // static line
    step_1_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    wxPanel* static_line = new wxPanel(m_step_1_panel, wxID_ANY, wxDefaultPosition, { -1, FromDIP(1) });
    static_line->SetBackgroundColour(EXTRUSION_CALIBRATION_GREY300);
    step_1_sizer->Add(static_line, 0, wxEXPAND);
    step_1_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    // filament info
    auto info_sizer = new wxFlexGridSizer(0, 3, 0, FromDIP(16));
    info_sizer->SetFlexibleDirection(wxBOTH);
    info_sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
    auto nozzle_temp_sizer = new wxBoxSizer(wxVERTICAL);
    auto nozzle_temp_text = new wxStaticText(m_step_1_panel, wxID_ANY, _L("Nozzle temperature"));
    auto max_input_width = std::max(std::max(std::max(wxWindow::GetTextExtent(_L("Nozzle temperature")).x,
        wxWindow::GetTextExtent(_L("Bed Temperature")).x),
        wxWindow::GetTextExtent(_L("Max volumetric speed")).x),
        EXTRUSION_CALIBRATION_INPUT_SIZE.x);
    m_nozzle_temp = new TextInput(m_step_1_panel, wxEmptyString, _L("\u2103"), "", wxDefaultPosition, { max_input_width, EXTRUSION_CALIBRATION_INPUT_SIZE.y }, wxTE_READONLY);
    nozzle_temp_sizer->Add(nozzle_temp_text, 0, wxALIGN_LEFT);
    nozzle_temp_sizer->AddSpacer(FromDIP(4));
    nozzle_temp_sizer->Add(m_nozzle_temp, 0, wxEXPAND);
    auto bed_temp_sizer = new wxBoxSizer(wxVERTICAL);
    auto bed_temp_text = new wxStaticText(m_step_1_panel, wxID_ANY, _L("Bed temperature"));
    m_bed_temp = new TextInput(m_step_1_panel, wxEmptyString, _L("\u2103"), "", wxDefaultPosition, { max_input_width, EXTRUSION_CALIBRATION_INPUT_SIZE.y }, wxTE_READONLY);
    bed_temp_sizer->Add(bed_temp_text, 0, wxALIGN_LEFT);
    bed_temp_sizer->AddSpacer(FromDIP(4));
    bed_temp_sizer->Add(m_bed_temp, 0, wxEXPAND);
    auto max_flow_sizer = new wxBoxSizer(wxVERTICAL);
    auto max_flow_text = new wxStaticText(m_step_1_panel, wxID_ANY, _L("Max volumetric speed"));
    m_max_flow_ratio = new TextInput(m_step_1_panel, wxEmptyString, _L("mm\u00B3"), "", wxDefaultPosition, { max_input_width, EXTRUSION_CALIBRATION_INPUT_SIZE.y }, wxTE_READONLY);
    max_flow_sizer->Add(max_flow_text, 0, wxALIGN_LEFT);
    max_flow_sizer->AddSpacer(FromDIP(4));
    max_flow_sizer->Add(m_max_flow_ratio, 0, wxEXPAND);
    info_sizer->Add(nozzle_temp_sizer);
    info_sizer->Add(bed_temp_sizer);
    info_sizer->Add(max_flow_sizer);
    step_1_sizer->Add(info_sizer, 0, wxEXPAND);
    // static line
    step_1_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    wxPanel* static_line2 = new wxPanel(m_step_1_panel, wxID_ANY, wxDefaultPosition, { -1, FromDIP(1) });
    static_line2->SetBackgroundColour(EXTRUSION_CALIBRATION_GREY300);
    step_1_sizer->Add(static_line2, 0, wxEXPAND);
    step_1_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    auto cali_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_info_text = new wxStaticText(m_step_1_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
    m_info_text->SetFont(Label::Body_12);
    m_info_text->Hide();
    m_error_text = new wxStaticText(m_step_1_panel, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
    m_error_text->SetFont(Label::Body_12);
    m_error_text->SetForegroundColour(wxColour(208, 27, 27));
    m_error_text->Hide();
    m_button_cali = new Button(m_step_1_panel, _L("Start calibration"));
    m_btn_bg_green = StateColor(std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Disabled), std::pair<wxColour, int>(wxColour(27, 136, 68), StateColor::Pressed), std::pair<wxColour, int>(wxColour(61, 203, 115), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    m_button_cali->SetBackgroundColor(m_btn_bg_green);
    m_button_cali->SetFont(Label::Body_13);
    m_button_cali->SetBorderColor({ std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Disabled), std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Enabled) });
    m_button_cali->SetTextColor({ std::pair<wxColour, int>(wxColour(172, 172, 172), StateColor::Disabled), std::pair<wxColour, int>(EXTRUSION_CALIBRATION_GREY200, StateColor::Enabled) });
    m_button_cali->SetCornerRadius(FromDIP(12));
    m_button_cali->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_cali->Bind(wxEVT_BUTTON, &ExtrusionCalibration::on_click_cali, this);
    m_cali_cancel = new Button(m_step_1_panel, _L("Cancel"));
    m_btn_bg_green = StateColor(std::pair<wxColour, int>(wxColour(27, 136, 68), StateColor::Pressed), std::pair<wxColour, int>(wxColour(61, 203, 115), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    m_cali_cancel->SetBackgroundColor(m_btn_bg_green);
    m_cali_cancel->SetBorderColor(wxColour(0, 150, 136));
    m_cali_cancel->SetTextColor(EXTRUSION_CALIBRATION_GREY200);
    m_cali_cancel->SetMinSize(EXTRUSION_CALIBRATION_BUTTON_SIZE);
    m_cali_cancel->SetCornerRadius(FromDIP(12));
    m_cali_cancel->Hide();
    m_cali_cancel->Bind(wxEVT_BUTTON, &ExtrusionCalibration::on_click_cancel, this);
    m_button_next_step = new Button(m_step_1_panel, _L("Next"));
    m_btn_bg_gray = StateColor(std::pair<wxColour, int>(wxColour(206, 206, 206), StateColor::Pressed), std::pair<wxColour, int>(*wxWHITE, StateColor::Focused),
        std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Hovered),
        std::pair<wxColour, int>(*wxWHITE, StateColor::Normal));
    m_button_next_step->SetBackgroundColor(m_btn_bg_gray);
    m_button_next_step->SetFont(Label::Body_13);
    m_button_next_step->SetBorderColor(EXTRUSION_CALIBRATION_GREY900);
    m_button_next_step->SetTextColor(EXTRUSION_CALIBRATION_GREY900);
    m_button_next_step->SetMinSize(EXTRUSION_CALIBRATION_BUTTON_SIZE);
    m_button_next_step->SetCornerRadius(FromDIP(12));
    m_button_next_step->Bind(wxEVT_BUTTON, &ExtrusionCalibration::on_click_next, this);
    m_button_next_step->Hide();
    cali_sizer->Add(m_info_text, 10, wxALIGN_LEFT | wxRIGHT | wxALIGN_CENTRE_VERTICAL, FromDIP(10));
    cali_sizer->Add(m_error_text, 10, wxALIGN_LEFT | wxRIGHT | wxALIGN_CENTRE_VERTICAL, FromDIP(10));
    cali_sizer->AddStretchSpacer();
    cali_sizer->Add(m_button_cali, 0, wxRIGHT | wxALIGN_CENTRE_VERTICAL, FromDIP(10));
    cali_sizer->Add(m_cali_cancel, 0, wxRIGHT | wxALIGN_CENTRE_VERTICAL, FromDIP(10));
    cali_sizer->Add(m_button_next_step, 0, wxRIGHT | wxALIGN_CENTRE_VERTICAL, FromDIP(10));
    step_1_sizer->Add(cali_sizer, 0, wxEXPAND);
    step_1_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    m_step_2_panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_step_2_panel->SetBackgroundColour(*wxWHITE);
    wxBoxSizer* step_2_sizer = new wxBoxSizer(wxVERTICAL);
    m_step_2_panel->SetSizer(step_2_sizer);
    step_2_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    // save result title and tips
    wxBoxSizer* save_result_sizer = new wxBoxSizer(wxHORIZONTAL);
    wxString fill_intro_text = _L("Calibration completed. Please find the most uniform extrusion line on your hot bed like the picture below, and fill the value on its left side into the factor K input box.");
    m_save_cali_result_title = new Label(m_step_2_panel, fill_intro_text);
    m_save_cali_result_title->SetFont(::Label::Body_12);
    m_save_cali_result_title->SetForegroundColour(EXTRUSION_CALIBRATION_GREY800);
    m_save_cali_result_title->Wrap(this->GetSize().x);
    save_result_sizer->Add(m_save_cali_result_title, 0, wxEXPAND);
    step_2_sizer->Add(save_result_sizer, 0, wxEXPAND);
    step_2_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    auto content_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_calibration_tips_static_bmp = new wxStaticBitmap(m_step_2_panel, wxID_ANY, wxNullBitmap, wxDefaultPosition, EXTRUSION_CALIBRATION_BMP_SIZE, 0);
    m_calibration_tips_static_bmp->SetMinSize(EXTRUSION_CALIBRATION_BMP_SIZE);
    content_sizer->Add(m_calibration_tips_static_bmp, 1, wxEXPAND | wxSHAPED);
    content_sizer->Add(EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0, 0);
    // k/n input value
    auto kn_sizer = new wxBoxSizer(wxVERTICAL);
    auto k_val_text = new wxStaticText(m_step_2_panel, wxID_ANY, _L("Factor K"), wxDefaultPosition, wxDefaultSize, 0);
    m_k_val = new TextInput(m_step_2_panel, wxEmptyString, "", "", wxDefaultPosition, wxDefaultSize);
    auto n_val_text = new wxStaticText(m_step_2_panel, wxID_ANY, _L("Factor N"), wxDefaultPosition, wxDefaultSize, 0);
    m_n_val = new TextInput(m_step_2_panel, wxEmptyString, "", "", wxDefaultPosition, wxDefaultSize);
    // hide n
    n_val_text->Hide();
    m_n_val->Hide();
    kn_sizer->Add(k_val_text, 0, wxALIGN_CENTER_VERTICAL);
    kn_sizer->Add(m_k_val, 0, wxEXPAND);
    kn_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    kn_sizer->Add(n_val_text, 0, wxALIGN_CENTER_VERTICAL);
    kn_sizer->Add(m_n_val, 0, wxEXPAND);
    // save button
    m_button_save_result = new Button(m_step_2_panel, _L("Save"));
    m_btn_bg_green = StateColor(std::pair<wxColour, int>(wxColour(27, 136, 68), StateColor::Pressed), std::pair<wxColour, int>(wxColour(61, 203, 115), StateColor::Hovered),
        std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    m_button_save_result->SetBackgroundColor(m_btn_bg_green);
    m_button_save_result->SetFont(Label::Body_13);
    m_button_save_result->SetBorderColor(wxColour(0, 150, 136));
    m_button_save_result->SetTextColor(EXTRUSION_CALIBRATION_GREY200);
    m_button_save_result->SetMinSize(EXTRUSION_CALIBRATION_BUTTON_SIZE);
    m_button_save_result->SetCornerRadius(FromDIP(12));
    m_button_save_result->Bind(wxEVT_BUTTON, &ExtrusionCalibration::on_click_save, this);
    m_button_last_step = new Button(m_step_2_panel, _L("Last Step")); // Back for english
    m_button_last_step->SetBackgroundColor(m_btn_bg_gray);
    m_button_last_step->SetFont(Label::Body_13);
    m_button_last_step->SetBorderColor(EXTRUSION_CALIBRATION_GREY900);
    m_button_last_step->SetTextColor(EXTRUSION_CALIBRATION_GREY900);
    m_button_last_step->SetMinSize(EXTRUSION_CALIBRATION_BUTTON_SIZE);
    m_button_last_step->SetCornerRadius(FromDIP(12));
    m_button_last_step->Bind(wxEVT_BUTTON, &ExtrusionCalibration::on_click_last, this);
    kn_sizer->AddStretchSpacer();
    kn_sizer->Add(m_button_last_step, 0);
    kn_sizer->AddSpacer(FromDIP(10));
    kn_sizer->Add(m_button_save_result, 0);
    content_sizer->Add(kn_sizer, 0, wxEXPAND);
    step_2_sizer->Add(content_sizer, 0, wxEXPAND);
    step_2_sizer->Add(0, EXTRUSION_CALIBRATION_WIDGET_GAP, 0, 0);
    sizer_main->Add(m_step_1_panel, 1, wxEXPAND);
    sizer_main->Add(m_step_2_panel, 1, wxEXPAND);
    wxBoxSizer* top_sizer = new wxBoxSizer(wxHORIZONTAL);
    top_sizer->Add(FromDIP(24), 0);
    top_sizer->Add(sizer_main, 1, wxEXPAND);
    top_sizer->Add(FromDIP(24), 0);
    SetSizer(top_sizer);
    // set default nozzle
    m_comboBox_nozzle_dia->SetSelection(1);
    // set a default bed type
    m_comboBox_bed_type->SetSelection(0);
    // set to step 1
    set_step(1);
    Layout();
    Fit();
    m_k_val->GetTextCtrl()->Bind(wxEVT_TEXT_ENTER, [this](wxCommandEvent& e) {
        input_value_finish();
        e.Skip();
        });
    m_n_val->GetTextCtrl()->Bind(wxEVT_TEXT_ENTER, [this](wxCommandEvent& e) {
        input_value_finish();
        e.Skip();
        });
    m_calibration_tips_static_bmp->Bind(wxEVT_PAINT, &ExtrusionCalibration::paint, this);
    m_calibration_tips_static_bmp->Bind(wxEVT_LEFT_UP, &ExtrusionCalibration::open_bitmap, this);
    m_comboBox_filament->Connect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(ExtrusionCalibration::on_select_filament), NULL, this);
    m_comboBox_bed_type->Connect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(ExtrusionCalibration::on_select_bed_type), NULL, this);
    m_comboBox_nozzle_dia->Connect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(ExtrusionCalibration::on_select_nozzle_dia), NULL, this);
}
References _L, Label::Body_12, Label::Body_13, StateColor::Disabled, StateColor::Enabled, Slic3r::ConfigOptionDef::enum_keys_map, EXTRUSION_CALIBRATION_BED_COMBOX, EXTRUSION_CALIBRATION_BMP_SIZE, EXTRUSION_CALIBRATION_BUTTON_SIZE, EXTRUSION_CALIBRATION_GREY200, EXTRUSION_CALIBRATION_GREY300, EXTRUSION_CALIBRATION_GREY800, EXTRUSION_CALIBRATION_GREY900, EXTRUSION_CALIBRATION_INPUT_SIZE, EXTRUSION_CALIBRATION_WIDGET_GAP, StateColor::Focused, Slic3r::ConfigDef::get(), TextInput::GetTextCtrl(), StateColor::Hovered, init_bitmaps(), input_value_finish(), m_bed_temp, m_btn_bg_gray, m_btn_bg_green, m_button_cali, m_button_last_step, m_button_next_step, m_button_save_result, m_cali_cancel, m_calibration_tips_static_bmp, m_comboBox_bed_type, m_comboBox_filament, m_comboBox_nozzle_dia, m_error_text, m_filament_preset_title, m_info_text, m_k_val, m_max_flow_ratio, m_n_val, m_nozzle_temp, m_save_cali_result_title, m_step_1_panel, m_step_2_panel, StateColor::Normal, NULL, on_click_cali(), on_click_cancel(), on_click_last(), on_click_next(), on_click_save(), on_select_bed_type(), on_select_filament(), on_select_nozzle_dia(), open_bitmap(), paint(), StateColor::Pressed, Slic3r::print_config_def, set_step(), StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetFont(), Button::SetMinSize(), ComboBox::SetSelection(), Button::SetTextColor(), Label::Wrap(), wxEVT_BUTTON, and wxStaticText.
Referenced by ExtrusionCalibration().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
get_bed_temp()
int Slic3r::GUI::ExtrusionCalibration::get_bed_temp (DynamicPrintConfig * config) protected
{
    BedType curr_bed_type = BedType(m_comboBox_bed_type->GetSelection() + btDefault + 1);
    const ConfigOptionInts* opt_bed_temp_ints = config->option<ConfigOptionInts>(get_bed_temp_key(curr_bed_type));
    if (opt_bed_temp_ints) {
        return opt_bed_temp_ints->get_at(0);
    }
    return -1;
}
References Slic3r::btDefault, Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::get_bed_temp_key(), ComboBox::GetSelection(), m_comboBox_bed_type, and Slic3r::ConfigBase::option().
Referenced by on_click_cali(), on_click_save(), and update_filament_info().
get_bed_type_incompatible()
wxString Slic3r::GUI::ExtrusionCalibration::get_bed_type_incompatible (bool incompatible) protected
{
    if (incompatible) {
        m_button_cali->Enable();
        return wxEmptyString;
    }
    else {
        m_button_cali->Disable();
        std::string filament_alias = "";
        PresetBundle* preset_bundle = wxGetApp().preset_bundle;
        if (preset_bundle) {
            for (auto filament_it = preset_bundle->filaments.begin(); filament_it != preset_bundle->filaments.end(); filament_it++) {
                wxString filament_name = wxString::FromUTF8(filament_it->name);
                if (filament_name.compare(m_comboBox_filament->GetValue()) == 0) {
                    filament_alias = filament_it->alias;
                }
            }
        }
        wxString tips = wxString::Format(_L("%s does not support %s"), m_comboBox_bed_type->GetValue(), filament_alias);
        return tips;
    }
}
References _L, Slic3r::PresetCollection::begin(), Button::Enable(), Slic3r::PresetCollection::end(), Slic3r::PresetBundle::filaments, ComboBox::GetValue(), m_button_cali, m_comboBox_bed_type, and m_comboBox_filament.
Referenced by update().
init_bitmaps()
void Slic3r::GUI::ExtrusionCalibration::init_bitmaps () protected
{
    auto lan = wxGetApp().app_config->get_language_code();
    if (lan == "zh-cn") {
        m_is_zh = true;
        m_calibration_tips_bmp_zh = create_scaled_bitmap("extrusion_calibration_tips_zh", nullptr, 256);
    }
    else{
        m_is_zh = false;
        m_calibration_tips_bmp_en = create_scaled_bitmap("extrusion_calibration_tips_en", nullptr, 256);
    }
    m_calibration_tips_open_btn_bmp = create_scaled_bitmap("extrusion_calibrati_open_button", nullptr, 16);
}
References create_scaled_bitmap(), m_calibration_tips_bmp_en, m_calibration_tips_bmp_zh, m_calibration_tips_open_btn_bmp, and m_is_zh.
Referenced by create().
input_value_finish()
void Slic3r::GUI::ExtrusionCalibration::input_value_finish ()
{
    ;
}
Referenced by create().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_click_cali()
void Slic3r::GUI::ExtrusionCalibration::on_click_cali (wxCommandEvent & evt) protected
{
    if (obj) {
        int nozzle_temp = -1;
        int bed_temp = -1;
        float max_volumetric_speed = -1;
        PresetBundle* preset_bundle = wxGetApp().preset_bundle;
        if (preset_bundle) {
            for (auto it = preset_bundle->filaments.begin(); it != preset_bundle->filaments.end(); it++) {
                wxString filament_name = wxString::FromUTF8(it->name);
                if (filament_name.compare(m_comboBox_filament->GetValue()) == 0) {
                    try {
                        bed_temp = get_bed_temp(&it->config);
                        const ConfigOptionInts* nozzle_temp_opt = it->config.option<ConfigOptionInts>("nozzle_temperature");
                        const ConfigOptionFloats* speed_opt = it->config.option<ConfigOptionFloats>("filament_max_volumetric_speed");
                        if (nozzle_temp_opt && speed_opt) {
                            nozzle_temp = nozzle_temp_opt->get_at(0);
                            max_volumetric_speed = speed_opt->get_at(0);
                            if (bed_temp >= 0 && nozzle_temp >= 0 && max_volumetric_speed >= 0) {
                                int curr_tray_id = ams_id * 4 + tray_id;
                                if (tray_id == VIRTUAL_TRAY_ID)
                                    curr_tray_id = tray_id;
                                obj->command_start_extrusion_cali(curr_tray_id, nozzle_temp, bed_temp, max_volumetric_speed, it->setting_id);
                                return;
                            }
                        } else {
                            BOOST_LOG_TRIVIAL(error) << "cali parameters is invalid";
                        }
                    } catch(...) {
                        ;
                    }
                }
            }
        } else {
            BOOST_LOG_TRIVIAL(error) << "extrusion_cali: preset_bundle is nullptr";
        }
    } else {
        BOOST_LOG_TRIVIAL(error) << "cali obj parameters is invalid";
    }
}
References ams_id, Slic3r::PresetCollection::begin(), Slic3r::MachineObject::command_start_extrusion_cali(), Slic3r::PresetCollection::end(), error, Slic3r::PresetBundle::filaments, Slic3r::ConfigOptionVector< T >::get_at(), get_bed_temp(), ComboBox::GetValue(), m_comboBox_filament, obj, tray_id, and VIRTUAL_TRAY_ID.
Referenced by create().
on_click_cancel()
void Slic3r::GUI::ExtrusionCalibration::on_click_cancel (wxCommandEvent & evt) protected
{
    if (obj) {
        BOOST_LOG_TRIVIAL(info) << "extrusion_cali: stop";
        obj->command_stop_extrusion_cali();
    }
}
References Slic3r::MachineObject::command_stop_extrusion_cali(), and obj.
Referenced by create().
on_click_last()
void Slic3r::GUI::ExtrusionCalibration::on_click_last (wxCommandEvent & evt) protected
{
    set_step(1);
}
References set_step().
Referenced by create().
on_click_next()
void Slic3r::GUI::ExtrusionCalibration::on_click_next (wxCommandEvent & evt) protected
{
    set_step(2);
}
References set_step().
Referenced by create().
on_click_save()
void Slic3r::GUI::ExtrusionCalibration::on_click_save (wxCommandEvent & evt) protected
{
    wxString k_text = m_k_val->GetTextCtrl()->GetValue();
    wxString n_text = m_n_val->GetTextCtrl()->GetValue();
    if (!ExtrusionCalibration::check_k_validation(k_text)) {
        wxString k_tips = _L("Please input a valid value (K in 0~0.5)");
        wxString kn_tips = _L("Please input a valid value (K in 0~0.5, N in 0.6~2.0)");
        MessageDialog msg_dlg(nullptr, k_tips, wxEmptyString, wxICON_WARNING | wxOK);
        msg_dlg.ShowModal();
        return;
    }
    double k = 0.0;
    try {
        k_text.ToDouble(&k);
    }
    catch (...) {
        ;
    }
    double n = 0.0;
    try {
        n_text.ToDouble(&n);
    }
    catch (...) {
        ;
    }
    // set values
    int nozzle_temp = -1;
    int bed_temp = -1;
    float max_volumetric_speed = -1;
    std::string setting_id;
    std::string name;
    PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    if (preset_bundle) {
        for (auto it = preset_bundle->filaments.begin(); it != preset_bundle->filaments.end(); it++) {
            wxString filament_name = wxString::FromUTF8(it->name);
            if (filament_name.compare(m_comboBox_filament->GetValue()) == 0) {
                if (obj) {
                    bed_temp    = get_bed_temp(&it->config);
                    const ConfigOptionInts* nozzle_temp_opt = it->config.option<ConfigOptionInts>("nozzle_temperature");
                    const ConfigOptionFloats* speed_opt = it->config.option<ConfigOptionFloats>("filament_max_volumetric_speed");
                    if (nozzle_temp_opt && speed_opt) {
                        nozzle_temp = nozzle_temp_opt->get_at(0);
                        max_volumetric_speed = speed_opt->get_at(0);
                    }
                    setting_id = it->setting_id;
                    name = it->name;
                }
            }
        }
    }
    // send command
    int curr_tray_id = ams_id * 4 + tray_id;
    if (tray_id == VIRTUAL_TRAY_ID)
        curr_tray_id = tray_id;
    obj->command_extrusion_cali_set(curr_tray_id, setting_id, name, k, n, bed_temp, nozzle_temp, max_volumetric_speed);
    Close();
}
References _L, ams_id, Slic3r::PresetCollection::begin(), check_k_validation(), Slic3r::MachineObject::command_extrusion_cali_set(), Slic3r::PresetCollection::end(), Slic3r::PresetBundle::filaments, Slic3r::ConfigOptionVector< T >::get_at(), get_bed_temp(), TextInput::GetTextCtrl(), ComboBox::GetValue(), m_comboBox_filament, m_k_val, m_n_val, n, obj, Slic3r::GUI::DPIAware< P >::ShowModal(), tray_id, and VIRTUAL_TRAY_ID.
Referenced by create().
on_dpi_changed()
void Slic3r::GUI::ExtrusionCalibration::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{ this->Refresh(); }
on_select_bed_type()
void Slic3r::GUI::ExtrusionCalibration::on_select_bed_type (wxCommandEvent & evt) protected
{
    update_filament_info();
}
References update_filament_info().
Referenced by ~ExtrusionCalibration(), and create().
on_select_filament()
void Slic3r::GUI::ExtrusionCalibration::on_select_filament (wxCommandEvent & evt) protected
{
    m_filament_type = "";
    update_filament_info();
    // set a default value for input values
    if (m_k_val->GetTextCtrl()->GetValue().IsEmpty()) {
        m_k_val->GetTextCtrl()->SetValue("0");
    }
    if (m_n_val->GetTextCtrl()->GetValue().IsEmpty()) {
        m_n_val->GetTextCtrl()->SetValue("0");
    }
}
References TextInput::GetTextCtrl(), m_filament_type, m_k_val, m_n_val, and update_filament_info().
Referenced by ~ExtrusionCalibration(), and create().
on_select_nozzle_dia()
void Slic3r::GUI::ExtrusionCalibration::on_select_nozzle_dia (wxCommandEvent & evt) protected
{
    update_combobox_filaments();
}
References update_combobox_filaments().
Referenced by ~ExtrusionCalibration(), and create().
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
open_bitmap()
void Slic3r::GUI::ExtrusionCalibration::open_bitmap (wxMouseEvent & event) protected
{
    auto pos = event.GetPosition();
    auto size = m_calibration_tips_static_bmp->GetSize();
    if (pos.x > size.x - EXTRUSION_CALIBRATION_BMP_TIP_BAR.y && pos.y > 0 &&
        pos.x < size.x && pos.y < EXTRUSION_CALIBRATION_BMP_TIP_BAR.y) {
        auto* popup = new wxDialog(this, wxID_ANY, "", wxDefaultPosition, wxDefaultSize);
        auto bmp_sizer = new wxBoxSizer(wxVERTICAL);
        wxStaticBitmap* zoomed_bitmap =  new wxStaticBitmap(popup, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, 0);
        zoomed_bitmap->SetBitmap(create_scaled_bitmap(m_is_zh ? "extrusion_calibration_tips_zh" : "extrusion_calibration_tips_en", nullptr, 720));
        bmp_sizer->Add(zoomed_bitmap, 1, wxEXPAND);
        popup->SetSizer(bmp_sizer);
        popup->Layout();
        popup->Fit();
        popup->CenterOnParent();
        wxGetApp().UpdateDlgDarkUI(popup);
        popup->ShowModal();
    }
    return;
}
References create_scaled_bitmap(), EXTRUSION_CALIBRATION_BMP_TIP_BAR, m_calibration_tips_static_bmp, m_is_zh, and size.
Referenced by create().
paint()
void Slic3r::GUI::ExtrusionCalibration::paint (wxPaintEvent &) protected
{
    auto      size = m_calibration_tips_static_bmp->GetSize();
    wxPaintDC dc(m_calibration_tips_static_bmp);
    wxGCDC gcdc(dc);
    dc.DrawBitmap(m_is_zh ? m_calibration_tips_bmp_zh : m_calibration_tips_bmp_en, wxPoint(0, 0));
    gcdc.SetPen(wxColour(0, 0, 0, 61));
    gcdc.SetBrush(wxColour(0, 0, 0, 61));
    gcdc.DrawRectangle(wxPoint(0, 0), EXTRUSION_CALIBRATION_BMP_TIP_BAR);
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    int pos_offset = (EXTRUSION_CALIBRATION_BMP_TIP_BAR.y - EXTRUSION_CALIBRATION_BMP_BTN_SIZE.y) / 2;
    wxPoint open_btn_pos = wxPoint(size.x - pos_offset - EXTRUSION_CALIBRATION_BMP_BTN_SIZE.x, pos_offset);
    dc.DrawBitmap(m_calibration_tips_open_btn_bmp, open_btn_pos);
    gcdc.SetFont(Label::Head_14);
    gcdc.SetTextForeground(wxColour(255, 255, 255, 224));
    wxSize text_size = wxWindow::GetTextExtent(_L("Example"));
    gcdc.DrawText(_L("Example"), { (EXTRUSION_CALIBRATION_BMP_TIP_BAR.x - text_size.x) / 2, (EXTRUSION_CALIBRATION_BMP_TIP_BAR.y - text_size.y) / 2});
    return;
}
References _L, EXTRUSION_CALIBRATION_BMP_BTN_SIZE, EXTRUSION_CALIBRATION_BMP_TIP_BAR, Label::Head_14, m_calibration_tips_bmp_en, m_calibration_tips_bmp_zh, m_calibration_tips_open_btn_bmp, m_calibration_tips_static_bmp, m_is_zh, and size.
Referenced by create().
Popup()
void Slic3r::GUI::ExtrusionCalibration::Popup ()
{
    this->SetSize(EXTRUSION_CALIBRATION_DIALOG_SIZE);
    update_combobox_filaments();
    set_step(1);
    update();
    Layout();
    Fit();
    wxGetApp().UpdateDlgDarkUI(this);
    ShowModal();
}
References EXTRUSION_CALIBRATION_DIALOG_SIZE, set_step(), Slic3r::GUI::DPIAware< P >::ShowModal(), update(), and update_combobox_filaments().
Referenced by Slic3r::GUI::StatusPanel::on_filament_extrusion_cali().
post_select_event()
void Slic3r::GUI::ExtrusionCalibration::post_select_event ()
{
    wxCommandEvent event(wxEVT_COMBOBOX);
    event.SetEventObject(m_comboBox_filament);
    wxPostEvent(m_comboBox_filament, event);
}
References m_comboBox_filament.
Referenced by update_combobox_filaments().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
set_step()
void Slic3r::GUI::ExtrusionCalibration::set_step (int step_index)
{
    if (step_index == 2) {
        wxString title_text = wxString::Format("%s - %s 2/2", _L("Dynamic flow Calibration"), _L("Step"));
        SetTitle(title_text);
        m_step_1_panel->Hide();
        m_step_2_panel->Show();
    } else {
        wxString title_text = wxString::Format("%s - %s 1/2", _L("Dynamic flow Calibration"), _L("Step"));
        SetTitle(title_text);
        m_step_1_panel->Show();
        m_step_2_panel->Hide();
    }
    this->SetMinSize(EXTRUSION_CALIBRATION_DIALOG_SIZE);
    Layout();
    Fit();
}
References _L, EXTRUSION_CALIBRATION_DIALOG_SIZE, m_step_1_panel, and m_step_2_panel.
Referenced by create(), on_click_last(), on_click_next(), and Popup().
Show()
bool Slic3r::GUI::ExtrusionCalibration::Show (bool show) override
{
    if (show) {
        m_k_val->GetTextCtrl()->SetSize(wxSize(-1, FromDIP(20)));
        m_n_val->GetTextCtrl()->SetSize(wxSize(-1, FromDIP(20)));
    }
    return DPIDialog::Show(show);
}
References TextInput::GetTextCtrl(), m_k_val, and m_n_val.
show_info()
void Slic3r::GUI::ExtrusionCalibration::show_info (bool show, bool is_error, wxString text) protected
{
    if (show && is_error) {
        m_error_text->Show();
        if (m_error_text->GetLabelText().compare(text) != 0)
            m_error_text->SetLabelText(text);
        m_info_text->Hide();
    }
    else if (show && !is_error) {
        m_info_text->Show();
        if (m_info_text->GetLabelText().compare(text) != 0)
            m_info_text->SetLabelText(text);
        m_error_text->Hide();
    }
    else {
        if (is_error) {
            m_info_text->Hide();
            m_error_text->Show();
            if (m_error_text->GetLabelText().compare(text) != 0)
                m_error_text->SetLabelText(text);
        } else {
            m_info_text->Show();
            if (m_info_text->GetLabelText().compare(text) != 0)
                m_info_text->SetLabelText(text);
            m_error_text->Hide();
        }
    }
}
References m_error_text, and m_info_text.
Referenced by update().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
update()
void Slic3r::GUI::ExtrusionCalibration::update ()
{
    if (obj) {
        if (obj->is_in_extrusion_cali()) {
            show_info(true, false, wxString::Format(_L("Calibrating... %d%%"), obj->mc_print_percent));
            m_cali_cancel->Show();
            m_cali_cancel->Enable();
            m_button_cali->Hide();
            m_button_next_step->Hide();
        } else if (obj->is_extrusion_cali_finished()) {
            if (m_bed_temp->GetTextCtrl()->GetValue().compare("0") == 0) {
                wxString tips = get_bed_type_incompatible(false);
                show_info(true, true, tips);
            }
            else {
                get_bed_type_incompatible(true);
                show_info(true, false, _L("Calibration completed"));
            }
            m_cali_cancel->Hide();
            m_button_cali->Show();
            m_button_next_step->Show();
        } else {
            if (m_bed_temp->GetTextCtrl()->GetValue().compare("0") == 0) {
                wxString tips = get_bed_type_incompatible(false);
                show_info(true, true, tips);
            } else {
                get_bed_type_incompatible(true);
                show_info(true, false, wxEmptyString);
            }
            m_cali_cancel->Hide();
            m_button_cali->Show();
            m_button_next_step->Hide();
        }
        Layout();
    }
}
References _L, Button::Enable(), get_bed_type_incompatible(), TextInput::GetTextCtrl(), Slic3r::MachineObject::is_extrusion_cali_finished(), Slic3r::MachineObject::is_in_extrusion_cali(), m_bed_temp, m_button_cali, m_button_next_step, m_cali_cancel, Slic3r::MachineObject::mc_print_percent, obj, and show_info().
Referenced by Popup(), and Slic3r::GUI::StatusPanel::update().
update_combobox_filaments()
void Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments () protected
{
    m_comboBox_filament->SetValue(wxEmptyString);
    user_filaments.clear();
    int selection_idx = -1;
    int filament_index = -1;
    int curr_selection = -1;
    wxArrayString filament_items;
    PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    if (preset_bundle && obj) {
        BOOST_LOG_TRIVIAL(trace) << "system_preset_bundle filament number=" << preset_bundle->filaments.size();
        std::string printer_type = obj->printer_type;
        std::set<std::string> printer_preset_list;
        for (auto printer_it = preset_bundle->printers.begin(); printer_it != preset_bundle->printers.end(); printer_it++) {
            // only use system printer preset
            if (!printer_it->is_system) continue;
            std::string model_id = printer_it->get_current_printer_type(preset_bundle);
            ConfigOption* printer_nozzle_opt = printer_it->config.option("nozzle_diameter");
            ConfigOptionFloats* printer_nozzle_vals = nullptr;
            if (printer_nozzle_opt)
                printer_nozzle_vals = dynamic_cast<ConfigOptionFloats*>(printer_nozzle_opt);
            double nozzle_value = 0.4;
            wxString nozzle_value_str = m_comboBox_nozzle_dia->GetValue();
            try {
                nozzle_value_str.ToDouble(&nozzle_value);
            } catch(...) {
                ;
            }
            if (!model_id.empty() && model_id.compare(obj->printer_type) == 0
                && printer_nozzle_vals
                && abs(printer_nozzle_vals->get_at(0) - nozzle_value) < 1e-3) {
                    printer_preset_list.insert(printer_it->name);
                    BOOST_LOG_TRIVIAL(trace) << "extrusion_cali: printer_model = " << model_id;
            } else {
                BOOST_LOG_TRIVIAL(error) << "extrusion_cali: printer_model = " << model_id;
            }
        }
        for (auto filament_it = preset_bundle->filaments.begin(); filament_it != preset_bundle->filaments.end(); filament_it++) {
            ConfigOption* printer_opt = filament_it->config.option("compatible_printers");
            ConfigOptionStrings* printer_strs = dynamic_cast<ConfigOptionStrings*>(printer_opt);
            for (auto printer_str : printer_strs->values) {
                if (printer_preset_list.find(printer_str) != printer_preset_list.end()) {
                    user_filaments.push_back(&(*filament_it));
                    // set default filament id
                    filament_index++;
                    if (filament_it->is_system
                        && !ams_filament_id.empty()
                        && filament_it->filament_id == ams_filament_id
                        ) {
                        curr_selection = filament_index;
                    }
                    wxString filament_name = wxString::FromUTF8(filament_it->name);
                    filament_items.Add(filament_name);
                    break;
                }
            }
        }
        m_comboBox_filament->Set(filament_items);
        m_comboBox_filament->SetSelection(curr_selection);
        post_select_event();
    }
    if (m_comboBox_filament->GetValue().IsEmpty())
        m_button_cali->Disable();
    else
        m_button_cali->Enable();
}
References ams_filament_id, Slic3r::PresetCollection::begin(), Button::Enable(), Slic3r::PresetCollection::end(), error, Slic3r::PresetBundle::filaments, Slic3r::ConfigOptionVector< T >::get_at(), ComboBox::GetValue(), m_button_cali, m_comboBox_filament, m_comboBox_nozzle_dia, obj, post_select_event(), Slic3r::MachineObject::printer_type, Slic3r::PresetBundle::printers, ComboBox::SetSelection(), ComboBox::SetValue(), Slic3r::PresetCollection::size(), Slic3r::trace(), user_filaments, and Slic3r::ConfigOptionVector< T >::values.
Referenced by on_select_nozzle_dia(), and Popup().
update_filament_info()
void Slic3r::GUI::ExtrusionCalibration::update_filament_info () protected
{
    if (m_comboBox_filament->GetValue().IsEmpty()) {
        m_nozzle_temp->GetTextCtrl()->SetValue(wxEmptyString);
        m_bed_temp->GetTextCtrl()->SetValue(wxEmptyString);
        m_max_flow_ratio->GetTextCtrl()->SetValue(wxEmptyString);
        return;
    }
    PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    int bed_temp_int = -1;
    if (preset_bundle) {
        for (auto filament_it = preset_bundle->filaments.begin(); filament_it != preset_bundle->filaments.end(); filament_it++) {
            wxString filament_name = wxString::FromUTF8(filament_it->name);
            if (filament_name.compare(m_comboBox_filament->GetValue()) == 0) {
                m_filament_type = filament_it->name;
                // update nozzle temperature
                ConfigOption* opt_nozzle_temp = filament_it->config.option("nozzle_temperature");
                if (opt_nozzle_temp) {
                    ConfigOptionInts* opt_min_ints = dynamic_cast<ConfigOptionInts*>(opt_nozzle_temp);
                    if (opt_min_ints) {
                        wxString text_nozzle_temp = wxString::Format("%d", opt_min_ints->get_at(0));
                        m_nozzle_temp->GetTextCtrl()->SetValue(text_nozzle_temp);
                    }
                }
                // update bed temperature
                bed_temp_int = get_bed_temp(&filament_it->config);
                wxString bed_temp_text = wxString::Format("%d", bed_temp_int);
                m_bed_temp->GetTextCtrl()->SetValue(bed_temp_text);
                // update max flow speed
                ConfigOption* opt_flow_speed = filament_it->config.option("filament_max_volumetric_speed");
                if (opt_flow_speed) {
                    ConfigOptionFloats* opt_flow_floats = dynamic_cast<ConfigOptionFloats*>(opt_flow_speed);
                    if (opt_flow_floats) {
                        wxString flow_val_text = wxString::Format("%0.2f", opt_flow_floats->get_at(0));
                        m_max_flow_ratio->GetTextCtrl()->SetValue(flow_val_text);
                    }
                }
            }
        }
    }
}
References Slic3r::PresetCollection::begin(), Slic3r::PresetCollection::end(), Slic3r::PresetBundle::filaments, Slic3r::ConfigOptionVector< T >::get_at(), get_bed_temp(), TextInput::GetTextCtrl(), ComboBox::GetValue(), m_bed_temp, m_comboBox_filament, m_filament_type, m_max_flow_ratio, and m_nozzle_temp.
Referenced by on_select_bed_type(), and on_select_filament().
update_machine_obj()
void Slic3r::GUI::ExtrusionCalibration::update_machine_obj (MachineObject * obj_) inline
{ obj = obj_; };
References obj.
Referenced by Slic3r::GUI::StatusPanel::update().
Member Data Documentation
ams_filament_id
std::string Slic3r::GUI::ExtrusionCalibration::ams_filament_id
Referenced by Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), and update_combobox_filaments().
ams_id
int Slic3r::GUI::ExtrusionCalibration::ams_id { 0 }
Referenced by on_click_cali(), on_click_save(), and Slic3r::GUI::StatusPanel::on_filament_extrusion_cali().
m_bed_temp
TextInput* Slic3r::GUI::ExtrusionCalibration::m_bed_temp protected
Referenced by create(), update(), and update_filament_info().
m_btn_bg_gray
StateColor Slic3r::GUI::ExtrusionCalibration::m_btn_bg_gray protected
Referenced by create().
m_btn_bg_green
StateColor Slic3r::GUI::ExtrusionCalibration::m_btn_bg_green protected
Referenced by create().
m_button_cali
Button* Slic3r::GUI::ExtrusionCalibration::m_button_cali protected
Referenced by create(), get_bed_type_incompatible(), update(), and update_combobox_filaments().
m_button_last_step
Button* Slic3r::GUI::ExtrusionCalibration::m_button_last_step protected
Referenced by create().
m_button_next_step
Button* Slic3r::GUI::ExtrusionCalibration::m_button_next_step protected
Referenced by create(), and update().
m_button_save_result
Button* Slic3r::GUI::ExtrusionCalibration::m_button_save_result protected
Referenced by create().
m_cali_cancel
Button* Slic3r::GUI::ExtrusionCalibration::m_cali_cancel protected
Referenced by create(), and update().
m_calibration_tips_bmp_en
wxBitmap Slic3r::GUI::ExtrusionCalibration::m_calibration_tips_bmp_en protected
Referenced by init_bitmaps(), and paint().
m_calibration_tips_bmp_zh
wxBitmap Slic3r::GUI::ExtrusionCalibration::m_calibration_tips_bmp_zh protected
Referenced by init_bitmaps(), and paint().
m_calibration_tips_open_btn_bmp
wxBitmap Slic3r::GUI::ExtrusionCalibration::m_calibration_tips_open_btn_bmp protected
Referenced by init_bitmaps(), and paint().
m_calibration_tips_static_bmp
wxStaticBitmap* Slic3r::GUI::ExtrusionCalibration::m_calibration_tips_static_bmp protected
Referenced by create(), open_bitmap(), and paint().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_comboBox_bed_type
ComboBox* Slic3r::GUI::ExtrusionCalibration::m_comboBox_bed_type protected
Referenced by ~ExtrusionCalibration(), create(), get_bed_temp(), and get_bed_type_incompatible().
m_comboBox_filament
ComboBox* Slic3r::GUI::ExtrusionCalibration::m_comboBox_filament protected
Referenced by ~ExtrusionCalibration(), create(), get_bed_type_incompatible(), on_click_cali(), on_click_save(), post_select_event(), update_combobox_filaments(), and update_filament_info().
m_comboBox_nozzle_dia
ComboBox* Slic3r::GUI::ExtrusionCalibration::m_comboBox_nozzle_dia protected
Referenced by ~ExtrusionCalibration(), create(), and update_combobox_filaments().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_error_text
wxStaticText* Slic3r::GUI::ExtrusionCalibration::m_error_text protected
Referenced by create(), and show_info().
m_filament_preset_title
Label* Slic3r::GUI::ExtrusionCalibration::m_filament_preset_title protected
Referenced by create().
m_filament_type
std::string Slic3r::GUI::ExtrusionCalibration::m_filament_type
Referenced by on_select_filament(), and update_filament_info().
m_fill_cali_params_tips
wxStaticText* Slic3r::GUI::ExtrusionCalibration::m_fill_cali_params_tips protected
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_info_text
wxStaticText* Slic3r::GUI::ExtrusionCalibration::m_info_text protected
Referenced by create(), and show_info().
m_is_zh
bool Slic3r::GUI::ExtrusionCalibration::m_is_zh { false } protected
Referenced by init_bitmaps(), open_bitmap(), and paint().
m_k_param
wxStaticText* Slic3r::GUI::ExtrusionCalibration::m_k_param protected
m_k_val
TextInput* Slic3r::GUI::ExtrusionCalibration::m_k_val protected
Referenced by create(), on_click_save(), on_select_filament(), and Show().
m_max_flow_ratio
TextInput* Slic3r::GUI::ExtrusionCalibration::m_max_flow_ratio protected
Referenced by create(), and update_filament_info().
m_n_param
wxStaticText* Slic3r::GUI::ExtrusionCalibration::m_n_param protected
m_n_val
TextInput* Slic3r::GUI::ExtrusionCalibration::m_n_val protected
Referenced by create(), on_click_save(), on_select_filament(), and Show().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_nozzle_temp
TextInput* Slic3r::GUI::ExtrusionCalibration::m_nozzle_temp protected
Referenced by create(), and update_filament_info().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_save_cali_result_title
Label* Slic3r::GUI::ExtrusionCalibration::m_save_cali_result_title protected
Referenced by create().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_step_1_panel
wxPanel* Slic3r::GUI::ExtrusionCalibration::m_step_1_panel protected
Referenced by create(), and set_step().
m_step_2_panel
wxPanel* Slic3r::GUI::ExtrusionCalibration::m_step_2_panel protected
Referenced by create(), and set_step().
obj
MachineObject* Slic3r::GUI::ExtrusionCalibration::obj { nullptr }
Referenced by on_click_cali(), on_click_cancel(), on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), update(), update_combobox_filaments(), and update_machine_obj().
tray_id
int Slic3r::GUI::ExtrusionCalibration::tray_id { 0 }
Referenced by on_click_cali(), on_click_save(), and Slic3r::GUI::StatusPanel::on_filament_extrusion_cali().
user_filaments
std::vector<Preset*> Slic3r::GUI::ExtrusionCalibration::user_filaments
Referenced by update_combobox_filaments().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ExtrusionCalibration.hpp
src/slic3r/GUI/ExtrusionCalibration.cpp