OrcaSlicer: Slic3r::client Namespace Reference
Slic3r::client Namespace Reference
Classes
struct expr
struct macro_processor
struct MyContext
struct OptWithPos
struct strict_real_policies_without_nan_inf
struct utf8_char_skipper_parser
Functions
template<typename ITERATOR >
std::ostream & operator<< (std::ostream &os, OptWithPos< ITERATOR > const &opt)
template<typename ITERATOR >
std::ostream & operator<< (std::ostream &os, const expr< ITERATOR > &expression)
template<typename Iterator >
std::ostream & operator<< (std::ostream &os, const boost::iterator_range< Iterator > &it_range)
Function Documentation
operator<<() [1/3]
template<typename Iterator > std::ostream & Slic3r::client::operator<< (std::ostream & os, const boost::iterator_range< Iterator > & it_range)
    {
        os << std::string(it_range.begin(), it_range.end());
        return os;
    }
operator<<() [2/3]
template<typename ITERATOR > std::ostream & Slic3r::client::operator<< (std::ostream & os, const expr< ITERATOR > & expression)
    {
        typedef expr<ITERATOR> Expr;
        os << std::string(expression.it_range.begin(), expression.it_range.end()) << " - ";
        switch (expression.type) {
        case Expr::TYPE_EMPTY:    os << "empty"; break;
        case Expr::TYPE_BOOL:     os << "bool ("   << expression.b() << ")"; break;
        case Expr::TYPE_INT:      os << "int ("    << expression.i() << ")"; break;
        case Expr::TYPE_DOUBLE:   os << "double (" << expression.d() << ")"; break;
        case Expr::TYPE_STRING:   os << "string (" << expression.s() << ")"; break;
        default: os << "unknown";
        };
        return os;
    }
References Slic3r::client::expr< Iterator >::b(), Slic3r::client::expr< Iterator >::d(), Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::it_range, Slic3r::client::expr< Iterator >::s(), and Slic3r::client::expr< Iterator >::type.
operator<<() [3/3]
template<typename ITERATOR > std::ostream & Slic3r::client::operator<< (std::ostream & os, OptWithPos< ITERATOR > const & opt)
    {
        os << std::string(opt.it_range.begin(), opt.it_range.end());
        return os;
    }
References Slic3r::client::OptWithPos< Iterator >::it_range.