OrcaSlicer: Slic3r::GUI::PartPlate Class Reference
Slic3r::GUI::PartPlate Class Reference
#include <src/slic3r/GUI/PartPlate.hpp>
Public Types
enum HeightLimitMode { HEIGHT_LIMIT_NONE , HEIGHT_LIMIT_BOTTOM , HEIGHT_LIMIT_TOP , HEIGHT_LIMIT_BOTH }
using Timestamp = uint64_t
Public Member Functions
PartPlate ()
PartPlate (PartPlateList *partplate_list, Vec3d origin, int width, int depth, int height, Plater *platerObj, Model *modelObj, bool printable=true, PrinterTechnology tech=ptFFF)
~PartPlate ()
bool operator< (PartPlate &) const
void clear (bool clear_sliced_result=true)
BedType get_bed_type (bool load_from_project=false) const
void set_bed_type (BedType bed_type)
void reset_bed_type ()
DynamicPrintConfig * config ()
void set_print_seq (PrintSequence print_seq=PrintSequence::ByDefault)
PrintSequence get_print_seq () const
PrintSequence get_real_print_seq () const
void set_index (int index)
int get_index ()
std::string get_plate_name () const
void generate_plate_name_texture ()
void set_plate_name (const std::string &name)
void get_print (PrintBase **print, GCodeResult **result, int *index)
void set_print (PrintBase *print, GCodeResult *result=nullptr, int index=-1)
std::string get_gcode_filename ()
bool is_valid_gcode_file ()
Vec3d get_center_origin ()
void set_pos_and_size (Vec3d &origin, int width, int depth, int height, bool with_instance_move)
ModelObjectPtrs get_objects ()
ModelInstance * get_instance (int obj_id, int instance_id)
Vec3d get_origin ()
Vec3d estimate_wipe_tower_size (const double w, const double wipe_volume) const
std::vector< int > get_extruders (bool conside_custom_gcode=false) const
std::vector< int > get_extruders_under_cli (bool conside_custom_gcode, DynamicPrintConfig &full_config) const
std::vector< int > get_extruders_without_support (bool conside_custom_gcode=false) const
std::vector< int > get_used_extruders ()
bool contain_instance (int obj_id, int instance_id)
bool contain_instance_totally (ModelObject *object, int instance_id) const
bool contain_instance_totally (int obj_id, int instance_id) const
bool is_left_top_of (int obj_id, int instance_id)
bool check_outside (int obj_id, int instance_id, BoundingBoxf3 *bounding_box=nullptr)
bool intersect_instance (int obj_id, int instance_id, BoundingBoxf3 *bounding_box=nullptr)
int add_instance (int obj_id, int instance_id, bool move_position, BoundingBoxf3 *bounding_box=nullptr)
int remove_instance (int obj_id, int instance_id)
void translate_all_instance (Vec3d position)
void duplicate_all_instance (unsigned int dup_count, bool need_skip, std::map< int, bool > &skip_objects)
void update_instance_exclude_status (int obj_id, int instance_id, BoundingBoxf3 *bounding_box=nullptr)
void update_object_index (int obj_idx_removed, int obj_idx_max)
bool empty ()
int printable_instance_size ()
bool has_printable_instances ()
bool is_all_instances_unprintable ()
void move_instances_to (PartPlate &left_plate, PartPlate &right_plate, BoundingBoxf3 *bounding_box=nullptr)
const Pointfs & get_shape () const
bool set_shape (const Pointfs &shape, const Pointfs &exclude_areas, Vec2d position, float height_to_lid, float height_to_rod)
bool contains (const Vec3d &point) const
bool contains (const GLVolume &v) const
bool contains (const BoundingBoxf3 &bb) const
bool intersects (const BoundingBoxf3 &bb) const
void render (bool bottom, bool only_body=false, bool force_background_color=false, HeightLimitMode mode=HEIGHT_LIMIT_NONE, int hover_id=-1, bool render_cali=false)
void render_for_picking () const
void set_selected ()
void set_unselected ()
void set_hover_id (int id)
const BoundingBoxf3 & get_bounding_box (bool extended=false)
const BoundingBox get_bounding_box_crd ()
BoundingBoxf3 get_build_volume ()
const std::vector< BoundingBoxf3 > & get_exclude_areas ()
void update_states ()
bool is_locked () const
void lock (bool state)
bool is_printable () const
bool can_slice () const
void update_slice_ready_status (bool ready_slice)
bool is_apply_result_invalid () const
void update_apply_result_invalid (bool invalid)
bool is_slice_result_valid () const
bool is_slice_result_ready_for_print () const
void update_slice_result_valid_state (bool valid=false)
void update_slicing_percent (float percent)
float get_slicing_percent ()
void update_slice_context (BackgroundSlicingProcess &process)
Print * fff_print ()
GCodeProcessorResult * get_slice_result ()
std::string get_tmp_gcode_path ()
std::string get_temp_config_3mf_path ()
void set_tmp_gcode_path (std::string new_path)
int load_gcode_from_file (const std::string &filename)
int load_thumbnail_data (std::string filename, ThumbnailData &thumb_data)
int load_pattern_thumbnail_data (std::string filename)
int load_pattern_box_data (std::string filename)
void print () const
template<class Archive >
void load (Archive &ar)
template<class Archive >
void save (Archive &ar) const
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Member Functions
static void update_render_colors ()
static void load_render_colors ()
Public Attributes
ThumbnailData thumbnail_data
ThumbnailData top_thumbnail_data
ThumbnailData pick_thumbnail_data
PlateBBoxData cali_bboxes_data
Static Public Attributes
static const unsigned int PLATE_BASE_ID = 255 * 255 * 253
static const unsigned int GRABBER_COUNT = 6
static std::array< float, 4 > SELECT_COLOR = { 0.2666f, 0.2784f, 0.2784f, 1.0f }
static std::array< float, 4 > UNSELECT_COLOR = { 0.82f, 0.82f, 0.82f, 1.0f }
static std::array< float, 4 > UNSELECT_DARK_COLOR = { 0.384f, 0.384f, 0.412f, 1.0f }
static std::array< float, 4 > DEFAULT_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f }
static std::array< float, 4 > LINE_BOTTOM_COLOR = { 0.8f, 0.8f, 0.8f, 0.4f }
static std::array< float, 4 > LINE_TOP_COLOR = { 0.89f, 0.89f, 0.89f, 1.0f }
static std::array< float, 4 > LINE_TOP_DARK_COLOR = { 0.431f, 0.431f, 0.463f, 1.0f }
static std::array< float, 4 > LINE_TOP_SEL_COLOR = { 0.5294f, 0.5451, 0.5333f, 1.0f}
static std::array< float, 4 > LINE_TOP_SEL_DARK_COLOR = { 0.298f, 0.298f, 0.3333f, 1.0f}
static std::array< float, 4 > HEIGHT_LIMIT_BOTTOM_COLOR = { 0.4f, 0.4f, 1.0f, 1.0f }
static std::array< float, 4 > HEIGHT_LIMIT_TOP_COLOR = { 0.6f, 0.6f, 1.0f, 1.0f }
static const int plate_thumbnail_width = 512
static const int plate_thumbnail_height = 512
Protected Member Functions
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
void init ()
bool valid_instance (int obj_id, int instance_id)
void generate_print_polygon (ExPolygon &print_polygon)
void generate_exclude_polygon (ExPolygon &exclude_polygon)
void generate_logo_polygon (ExPolygon &logo_polygon)
void calc_bounding_boxes () const
void calc_triangles (const ExPolygon &poly)
void calc_exclude_triangles (const ExPolygon &poly)
void calc_gridlines (const ExPolygon &poly, const BoundingBox &pp_bbox)
void calc_height_limit ()
void calc_vertex_for_number (int index, bool one_number, GeometryBuffer &buffer)
void calc_vertex_for_icons (int index, GeometryBuffer &buffer)
void calc_vertex_for_icons_background (int icon_count, GeometryBuffer &buffer)
void render_background (bool force_default_color=false) const
void render_logo (bool bottom, bool render_cali=true) const
void render_logo_texture (GLTexture &logo_texture, const GeometryBuffer &logo_buffer, bool bottom, unsigned int vbo_id) const
void render_exclude_area (bool force_default_color) const
void render_grid (bool bottom) const
void render_height_limit (PartPlate::HeightLimitMode mode=HEIGHT_LIMIT_BOTH) const
void render_label (GLCanvas3D &canvas) const
void render_grabber (const float *render_color, bool use_lighting) const
void render_face (float x_size, float y_size) const
void render_arrows (const float *render_color, bool use_lighting) const
void render_left_arrow (const float *render_color, bool use_lighting) const
void render_right_arrow (const float *render_color, bool use_lighting) const
void render_icon_texture (int position_id, int tex_coords_id, const GeometryBuffer &buffer, GLTexture &texture, unsigned int &vbo_id) const
void render_icons (bool bottom, bool only_name=false, int hover_id=-1)
void render_only_numbers (bool bottom) const
void render_plate_name_texture (int position_id, int tex_coords_id)
void render_rectangle_for_picking (const GeometryBuffer &buffer, const float *render_color) const
void on_render_for_picking () const
std::array< float, 4 > picking_color_component (int idx) const
void release_opengl_resource ()
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
PartPlateList * m_partplate_list {nullptr }
Plater * m_plater
Model * m_model
PrinterTechnology printer_technology
std::set< std::pair< int, int > > obj_to_instance_set
std::set< std::pair< int, int > > instance_outside_set
int m_plate_index
Vec3d m_origin
int m_width
int m_depth
int m_height
float m_height_to_lid
float m_height_to_rod
bool m_printable
bool m_locked
bool m_ready_for_slice
bool m_slice_result_valid
bool m_apply_invalid {false}
float m_slice_percent
Print * m_print
GCodeProcessorResult * m_gcode_result
std::vector< FilamentInfo > slice_filaments_info
int m_print_index
std::string m_tmp_gcode_path
std::string m_temp_config_3mf_path
std::string m_gcode_path_from_3mf
Pointfs m_shape
Pointfs m_exclude_area
BoundingBoxf3 m_bounding_box
BoundingBoxf3 m_extended_bounding_box
std::vector< BoundingBoxf3 > m_exclude_bounding_box
BoundingBoxf3 m_grabber_box
Transform3d m_grabber_trans_matrix
Slic3r::Geometry::Transformation position
std::vector< Vec3f > positions
unsigned int m_vbo_id { 0 }
GeometryBuffer m_triangles
GeometryBuffer m_exclude_triangles
GeometryBuffer m_logo_triangles
GeometryBuffer m_gridlines
GeometryBuffer m_gridlines_bolder
GeometryBuffer m_height_limit_common
GeometryBuffer m_height_limit_bottom
GeometryBuffer m_height_limit_top
GeometryBuffer m_del_icon
unsigned int m_del_vbo_id { 0 }
GeometryBuffer m_arrange_icon
unsigned int m_arrange_vbo_id { 0 }
GeometryBuffer m_orient_icon
unsigned int m_orient_vbo_id { 0 }
GeometryBuffer m_lock_icon
unsigned int m_lock_vbo_id { 0 }
GeometryBuffer m_plate_settings_icon
unsigned int m_plate_settings_vbo_id { 0 }
GeometryBuffer m_plate_idx_icon
unsigned int m_plate_idx_vbo_id { 0 }
GLTexture m_texture
float m_grabber_color [4]
float m_scale_factor { 1.0f }
GLUquadricObject * m_quadric
int m_hover_id
bool m_selected
DynamicPrintConfig m_config
std::string m_name
GeometryBuffer m_plate_name_icon
unsigned int m_plate_name_vbo_id { 0 }
GLTexture m_name_texture
wxCoord m_name_texture_width
wxCoord m_name_texture_height
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class PartPlateList
class cereal::access
class UndoRedo::StackImpl
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Member Enumeration Documentation
HeightLimitMode
enum Slic3r::GUI::PartPlate::HeightLimitMode
Enumerator
HEIGHT_LIMIT_NONE
HEIGHT_LIMIT_BOTTOM
HEIGHT_LIMIT_TOP
HEIGHT_LIMIT_BOTH
{
        HEIGHT_LIMIT_NONE,
        HEIGHT_LIMIT_BOTTOM,
        HEIGHT_LIMIT_TOP,
        HEIGHT_LIMIT_BOTH
    };
Constructor & Destructor Documentation
PartPlate() [1/2]
Slic3r::GUI::PartPlate::PartPlate ()
  : ObjectBase(-1), m_plater(nullptr), m_model(nullptr), m_quadric(nullptr)
{
  assert(this->id().invalid());
  init();
}
References init().
PartPlate() [2/2]
Slic3r::GUI::PartPlate::PartPlate (PartPlateList * partplate_list, Vec3d origin, int width, int depth, int height, Plater * platerObj, Model * modelObj, bool printable = true, PrinterTechnology tech = ptFFF)
  :m_partplate_list(partplate_list), m_plater(platerObj), m_model(modelObj), printer_technology(tech), m_origin(origin), m_width(width), m_depth(depth), m_height(height),  m_printable(printable)
{
  init();
}
References init().
~PartPlate()
Slic3r::GUI::PartPlate::~PartPlate ()
{
  clear();
  //if (m_quadric != nullptr)
  //  ::gluDeleteQuadric(m_quadric);
  release_opengl_resource();
  //boost::nowide::remove(m_tmp_gcode_path.c_str());
}
References clear(), and release_opengl_resource().
Member Function Documentation
add_instance()
int Slic3r::GUI::PartPlate::add_instance (int obj_id, int instance_id, bool move_position, BoundingBoxf3 * bounding_box = nullptr)
{
  if (!valid_instance(obj_id, instance_id))
  {
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(": plate_id %1%, invalid obj_id %2%, instance_id %3%, move_position %4%") % m_plate_index % obj_id % instance_id % move_position;
    return -1;
  }
  ModelObject* object = m_model->objects[obj_id];
  ModelInstance* instance = object->instances[instance_id];
  std::pair<int, int> pair(obj_id, instance_id);
  obj_to_instance_set.insert(pair);
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": plate_id %1%, add instance obj_id %2%, instance_id %3%, move_position %4%") % m_plate_index % obj_id % instance_id % move_position;
  if (move_position)
  {
    //move this instance into the new position
    Vec3d center = get_center_origin();
    center.z() = instance->get_transformation().get_offset(Z);
    instance->set_offset(center);
    object->invalidate_bounding_box();
  }
  //need to judge whether this instance has an outer part
  bool outside = check_outside(obj_id, instance_id, bounding_box);
  if (outside)
    instance_outside_set.insert(pair);
  if (m_ready_for_slice && outside)
  {
    m_ready_for_slice = false;
  }
  else if ((obj_to_instance_set.size() == 1) && (!m_ready_for_slice) && !outside)
  {
    m_ready_for_slice = true;
  }
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1% , m_ready_for_slice changes to %2%") % m_plate_index %m_ready_for_slice;
  return 0;
}
References Slic3r::bounding_box(), check_outside(), error, get_center_origin(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::ModelInstance::get_transformation(), instance_outside_set, m_model, m_plate_index, m_ready_for_slice, obj_to_instance_set, Slic3r::Model::objects, Slic3r::ModelInstance::set_offset(), valid_instance(), and Slic3r::Z.
Referenced by Slic3r::GUI::PartPlateList::add_to_plate(), Slic3r::GUI::PartPlateList::construct_objects_list_for_new_plate(), move_instances_to(), Slic3r::GUI::PartPlateList::notify_instance_update(), and Slic3r::GUI::PartPlateList::reload_all_objects().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
calc_bounding_boxes()
void Slic3r::GUI::PartPlate::calc_bounding_boxes () const private
{
  BoundingBoxf3* bounding_box = const_cast<BoundingBoxf3*>(&m_bounding_box);
  *bounding_box = BoundingBoxf3();
  for (const Vec2d& p : m_shape) {
    bounding_box->merge({ p(0), p(1), 0.0 });
  }
  BoundingBoxf3* extended_bounding_box = const_cast<BoundingBoxf3*>(&m_extended_bounding_box);
  *extended_bounding_box = m_bounding_box;
  double half_x = bounding_box->size().x() * GRABBER_X_FACTOR;
  double half_y = bounding_box->size().y() * 1.0f * GRABBER_Y_FACTOR;
  double half_z = GRABBER_Z_VALUE;
  Vec3d center(bounding_box->center().x(), bounding_box->min(1) -half_y, GROUND_Z);
  m_grabber_box.min = Vec3d(center.x() - half_x, center.y() - half_y, center.z() - half_z);
  m_grabber_box.max = Vec3d(center.x() + half_x, center.y() + half_y, center.z() + half_z);
  m_grabber_box.defined = true;
  extended_bounding_box->merge(m_grabber_box);
    //calc exclude area bounding box
    m_exclude_bounding_box.clear();
    BoundingBoxf3 exclude_bb;
    for (int index = 0; index < m_exclude_area.size(); index ++) {
    const Vec2d& p = m_exclude_area[index];
    if (index % 4 == 0)
      exclude_bb = BoundingBoxf3();
    exclude_bb.merge({ p(0), p(1), 0.0 });
    if (index % 4 == 3)
    {
      exclude_bb.max(2) = m_depth;
      exclude_bb.min(2) = GROUND_Z;
      m_exclude_bounding_box.emplace_back(exclude_bb);
    }
  }
}
References Slic3r::bounding_box(), Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::BoundingBoxBase< PointClass >::defined, GRABBER_X_FACTOR, GRABBER_Y_FACTOR, GRABBER_Z_VALUE, GROUND_Z, m_bounding_box, m_depth, m_exclude_area, m_exclude_bounding_box, m_extended_bounding_box, m_grabber_box, m_shape, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBox3Base< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::min, and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by set_shape().
calc_exclude_triangles()
void Slic3r::GUI::PartPlate::calc_exclude_triangles (const ExPolygon & poly) private
{
  if (!m_exclude_triangles.set_from_triangles(triangulate_expolygon_2f(poly, NORMALS_UP), GROUND_Z))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":Unable to create exclude triangles\n";
}
References error, GROUND_Z, m_exclude_triangles, Slic3r::NORMALS_UP, Slic3r::GUI::GeometryBuffer::set_from_triangles(), and Slic3r::triangulate_expolygon_2f().
Referenced by set_shape().
calc_gridlines()
void Slic3r::GUI::PartPlate::calc_gridlines (const ExPolygon & poly, const BoundingBox & pp_bbox) private
{
  Polylines axes_lines, axes_lines_bolder;
  int count = 0;
  for (coord_t x = pp_bbox.min(0); x <= pp_bbox.max(0); x += scale_(10.0)) {
    Polyline line;
    line.append(Point(x, pp_bbox.min(1)));
    line.append(Point(x, pp_bbox.max(1)));
    if ( (count % 5) == 0 )
      axes_lines_bolder.push_back(line);
    else
      axes_lines.push_back(line);
    count ++;
  }
  count = 0;
  for (coord_t y = pp_bbox.min(1); y <= pp_bbox.max(1); y += scale_(10.0)) {
    Polyline line;
    line.append(Point(pp_bbox.min(0), y));
    line.append(Point(pp_bbox.max(0), y));
    axes_lines.push_back(line);
    if ( (count % 5) == 0 )
      axes_lines_bolder.push_back(line);
    else
      axes_lines.push_back(line);
    count ++;
  }
  // clip with a slightly grown expolygon because our lines lay on the contours and may get erroneously clipped
  Lines gridlines = to_lines(intersection_pl(axes_lines, offset(poly, (float)SCALED_EPSILON)));
  Lines gridlines_bolder = to_lines(intersection_pl(axes_lines_bolder, offset(poly, (float)SCALED_EPSILON)));
  // append bed contours
  Lines contour_lines = to_lines(poly);
  std::copy(contour_lines.begin(), contour_lines.end(), std::back_inserter(gridlines));
  if (!m_gridlines.set_from_lines(gridlines, GROUND_Z_GRIDLINE))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to create bed grid lines\n";
  if (!m_gridlines_bolder.set_from_lines(gridlines_bolder, GROUND_Z_GRIDLINE))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to create bed grid lines\n";
}
References Slic3r::Polyline::append(), count, error, GROUND_Z_GRIDLINE, Slic3r::intersection_pl(), m_gridlines, m_gridlines_bolder, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::offset(), scale_, SCALED_EPSILON, Slic3r::GUI::GeometryBuffer::set_from_lines(), and Slic3r::to_lines().
Referenced by set_shape().
calc_height_limit()
void Slic3r::GUI::PartPlate::calc_height_limit () private
{
  Lines3 bottom_h_lines, top_lines, top_h_lines, common_lines;
  int shape_count = m_shape.size();
  float first_z = 0.02f;
  for (int i = 0; i < shape_count; i++) {
    auto &cur_p = m_shape[i];
    Vec3crd p1(scale_(cur_p.x()), scale_(cur_p.y()), scale_(first_z));
    Vec3crd p2(scale_(cur_p.x()), scale_(cur_p.y()), scale_(m_height_to_rod));
    Vec3crd p3(scale_(cur_p.x()), scale_(cur_p.y()), scale_(m_height_to_lid));
    common_lines.emplace_back(p1, p2);
    top_lines.emplace_back(p2, p3);
    Vec2d next_p;
    if (i < (shape_count - 1)) {
      next_p = m_shape[i+1];
    }
    else {
      next_p = m_shape[0];
    }
    Vec3crd p4(scale_(cur_p.x()), scale_(cur_p.y()), scale_(m_height_to_rod));
    Vec3crd p5(scale_(next_p.x()), scale_(next_p.y()), scale_(m_height_to_rod));
    bottom_h_lines.emplace_back(p4, p5);
    Vec3crd p6(scale_(cur_p.x()), scale_(cur_p.y()), scale_(m_height_to_lid));
    Vec3crd p7(scale_(next_p.x()), scale_(next_p.y()), scale_(m_height_to_lid));
    top_h_lines.emplace_back(p6, p7);
  }
  //std::copy(bottom_lines.begin(), bottom_lines.end(), std::back_inserter(bottom_h_lines));
  std::copy(top_lines.begin(), top_lines.end(), std::back_inserter(top_h_lines));
  if (!m_height_limit_common.set_from_3d_Lines(common_lines))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to create height limit bottom lines\n";
  if (!m_height_limit_bottom.set_from_3d_Lines(bottom_h_lines))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to create height limit bottom lines\n";
  if (!m_height_limit_top.set_from_3d_Lines(top_h_lines))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to create height limit top lines\n";
}
References error, m_height_limit_bottom, m_height_limit_common, m_height_limit_top, m_height_to_lid, m_height_to_rod, m_shape, scale_, and Slic3r::GUI::GeometryBuffer::set_from_3d_Lines().
Referenced by set_shape().
calc_triangles()
void Slic3r::GUI::PartPlate::calc_triangles (const ExPolygon & poly) private
{
  if (!m_triangles.set_from_triangles(triangulate_expolygon_2f(poly, NORMALS_UP), GROUND_Z))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":Unable to create plate triangles\n";
}
References error, GROUND_Z, m_triangles, Slic3r::NORMALS_UP, Slic3r::GUI::GeometryBuffer::set_from_triangles(), and Slic3r::triangulate_expolygon_2f().
Referenced by set_shape().
calc_vertex_for_icons()
void Slic3r::GUI::PartPlate::calc_vertex_for_icons (int index, GeometryBuffer & buffer) private
{
  ExPolygon poly;
  auto bed_ext = get_extents(m_shape);
    Vec2d p = bed_ext[2];
    if (m_plater->get_build_volume_type() == BuildVolume_Type::Circle)
        p[1] -= std::max(
            0.0, (bed_ext.size()(1) - 5 * PARTPLATE_ICON_SIZE - 4 * PARTPLATE_ICON_GAP_Y - PARTPLATE_ICON_GAP_TOP) / 2);
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT), scale_(p(1) - index * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP_Y) - PARTPLATE_ICON_GAP_TOP - PARTPLATE_ICON_SIZE) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + PARTPLATE_ICON_SIZE), scale_(p(1) - index * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP_Y)- PARTPLATE_ICON_GAP_TOP - PARTPLATE_ICON_SIZE) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + PARTPLATE_ICON_SIZE), scale_(p(1) - index * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP_Y)- PARTPLATE_ICON_GAP_TOP)});
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT), scale_(p(1) - index * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP_Y)- PARTPLATE_ICON_GAP_TOP) });
  auto triangles = triangulate_expolygon_2f(poly, NORMALS_UP);
  if (!buffer.set_from_triangles(triangles, GROUND_Z))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to generate geometry buffers for icons\n";
}
References Slic3r::MultiPoint::append(), buffer, Slic3r::Circle, Slic3r::ExPolygon::contour, error, Slic3r::GUI::Plater::get_build_volume_type(), Slic3r::get_extents(), GROUND_Z, m_plater, m_shape, Slic3r::NORMALS_UP, PARTPLATE_ICON_GAP_LEFT, PARTPLATE_ICON_GAP_TOP, PARTPLATE_ICON_GAP_Y, PARTPLATE_ICON_SIZE, scale_, and Slic3r::triangulate_expolygon_2f().
Referenced by set_shape().
calc_vertex_for_icons_background()
void Slic3r::GUI::PartPlate::calc_vertex_for_icons_background (int icon_count, GeometryBuffer & buffer) private
{
  ExPolygon poly;
  auto bed_ext = get_extents(m_shape);
    Vec2d p = bed_ext[2];
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT), scale_(p(1) - icon_count * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP_Y) - PARTPLATE_ICON_GAP_TOP) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + PARTPLATE_ICON_SIZE), scale_(p(1) - icon_count * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP_Y)- PARTPLATE_ICON_GAP_TOP) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + PARTPLATE_ICON_SIZE), scale_(p(1) - PARTPLATE_ICON_GAP_TOP)});
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT), scale_(p(1) - PARTPLATE_ICON_GAP_TOP) });
  auto triangles = triangulate_expolygon_2f(poly, NORMALS_UP);
  if (!buffer.set_from_triangles(triangles, GROUND_Z))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to generate geometry buffers for icons\n";
}
References Slic3r::MultiPoint::append(), buffer, Slic3r::ExPolygon::contour, error, Slic3r::get_extents(), GROUND_Z, m_shape, Slic3r::NORMALS_UP, PARTPLATE_ICON_GAP_LEFT, PARTPLATE_ICON_GAP_TOP, PARTPLATE_ICON_GAP_Y, PARTPLATE_ICON_SIZE, scale_, and Slic3r::triangulate_expolygon_2f().
calc_vertex_for_number()
void Slic3r::GUI::PartPlate::calc_vertex_for_number (int index, bool one_number, GeometryBuffer & buffer) private
{
  ExPolygon poly;
#if 0 //in the up area
  Vec2d& p = m_shape[2];
  float offset_x = one_number?PARTPLATE_TEXT_OFFSET_X1: PARTPLATE_TEXT_OFFSET_X2;
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP + offset_x), scale_(p(1) - index * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP) - PARTPLATE_ICON_GAP - PARTPLATE_ICON_SIZE + PARTPLATE_TEXT_OFFSET_Y) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP + PARTPLATE_ICON_SIZE - offset_x), scale_(p(1) - index * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP)- PARTPLATE_ICON_GAP - PARTPLATE_ICON_SIZE + PARTPLATE_TEXT_OFFSET_Y) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP + PARTPLATE_ICON_SIZE - offset_x), scale_(p(1) - index * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP)- PARTPLATE_ICON_GAP - PARTPLATE_TEXT_OFFSET_Y)});
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP + offset_x), scale_(p(1) - index * (PARTPLATE_ICON_SIZE + PARTPLATE_ICON_GAP)- PARTPLATE_ICON_GAP - PARTPLATE_TEXT_OFFSET_Y) });
#else //in the bottom
  auto bed_ext = get_extents(m_shape);
    Vec2d p = bed_ext[1];
  float offset_x = one_number?PARTPLATE_TEXT_OFFSET_X1: PARTPLATE_TEXT_OFFSET_X2;
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + offset_x), scale_(p(1) + PARTPLATE_TEXT_OFFSET_Y) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + PARTPLATE_ICON_SIZE - offset_x), scale_(p(1) + PARTPLATE_TEXT_OFFSET_Y) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + PARTPLATE_ICON_SIZE - offset_x), scale_(p(1) + PARTPLATE_ICON_SIZE - PARTPLATE_TEXT_OFFSET_Y)});
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + offset_x), scale_(p(1) + PARTPLATE_ICON_SIZE - PARTPLATE_TEXT_OFFSET_Y) });
#endif
  auto triangles = triangulate_expolygon_2f(poly, NORMALS_UP);
  if (!buffer.set_from_triangles(triangles, GROUND_Z))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to generate geometry buffers for icons\n";
}
References Slic3r::MultiPoint::append(), buffer, Slic3r::ExPolygon::contour, error, Slic3r::get_extents(), GROUND_Z, m_shape, Slic3r::NORMALS_UP, PARTPLATE_ICON_GAP_LEFT, PARTPLATE_ICON_SIZE, PARTPLATE_TEXT_OFFSET_X1, PARTPLATE_TEXT_OFFSET_X2, PARTPLATE_TEXT_OFFSET_Y, scale_, and Slic3r::triangulate_expolygon_2f().
Referenced by set_shape().
can_slice()
bool Slic3r::GUI::PartPlate::can_slice () const inline
    {
        return m_ready_for_slice && !m_apply_invalid;
    }
References m_apply_invalid, and m_ready_for_slice.
Referenced by Slic3r::GUI::MainFrame::get_enable_slice_status(), and Slic3r::GUI::Plater::priv::update_background_process().
check_outside()
bool Slic3r::GUI::PartPlate::check_outside (int obj_id, int instance_id, BoundingBoxf3 * bounding_box = nullptr)
{
  bool outside = true;
  ModelObject* object = m_model->objects[obj_id];
  ModelInstance* instance = object->instances[instance_id];
  BoundingBoxf3 instance_box = bounding_box? *bounding_box: object->instance_convex_hull_bounding_box(instance_id);
    Vec3d up_point = m_bounding_box.max + Vec3d(Slic3r::BuildVolume::SceneEpsilon, Slic3r::BuildVolume::SceneEpsilon,
                                                m_origin.z() + m_height + Slic3r::BuildVolume::SceneEpsilon);
    Vec3d low_point = m_bounding_box.min + Vec3d(-Slic3r::BuildVolume::SceneEpsilon, -Slic3r::BuildVolume::SceneEpsilon,
                                                 m_origin.z() - Slic3r::BuildVolume::SceneEpsilon);
    Polygon hull = instance->convex_hull_2d();
    if (instance_box.max.z() > low_point.z()) low_point.z() +=  instance_box.min.z(); // not considering outsize if sinking
  BoundingBoxf3 plate_box(low_point, up_point);
  if (plate_box.contains(instance_box))
  {
    if (m_exclude_bounding_box.size() > 0)
    {
      Polygon hull = instance->convex_hull_2d();
      int index;
      for (index = 0; index < m_exclude_bounding_box.size(); index ++)
      {
        Polygon p = m_exclude_bounding_box[index].polygon(true);  // instance convex hull is scaled, so we need to scale here
        if (intersection({ p }, { hull }).empty() == false)
        //if (m_exclude_bounding_box[index].intersects(instance_box))
        {
          break;
        }
      }
      if (index >= m_exclude_bounding_box.size())
        outside = false;
    }
    else
      outside = false;
  }
  return outside;
}
References Slic3r::bounding_box(), Slic3r::BoundingBox3Base< PointClass >::contains(), Slic3r::ModelInstance::convex_hull_2d(), empty(), Slic3r::intersection(), m_bounding_box, m_exclude_bounding_box, m_height, m_model, m_origin, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::Model::objects, and Slic3r::BuildVolume::SceneEpsilon.
Referenced by add_instance(), and update_instance_exclude_status().
clear()
void Slic3r::GUI::PartPlate::clear (bool clear_sliced_result = true)
{
  obj_to_instance_set.clear();
  instance_outside_set.clear();
  if (clear_sliced_result) {
    m_ready_for_slice = true;
    update_slice_result_valid_state(false);
  }
  m_name_texture.reset();
  return;
}
References instance_outside_set, m_name_texture, m_ready_for_slice, obj_to_instance_set, Slic3r::GUI::GLTexture::reset(), and update_slice_result_valid_state().
Referenced by ~PartPlate(), Slic3r::GUI::PartPlateList::clear(), Slic3r::GUI::PartPlateList::construct_objects_list_for_new_plate(), and set_pos_and_size().
config()
DynamicPrintConfig * Slic3r::GUI::PartPlate::config () inline
{ return &m_config; }
References m_config.
Referenced by Slic3r::BackgroundSlicingProcess::apply(), Slic3r::CLI::run(), and Slic3r::GUI::Plater::select_plate_by_hover_id().
contain_instance()
bool Slic3r::GUI::PartPlate::contain_instance (int obj_id, int instance_id)
{
  bool result = false;
  std::set<std::pair<int, int>>::iterator it;
  it = obj_to_instance_set.find(std::pair(obj_id, instance_id));
  if (it != obj_to_instance_set.end()) {
    result = true;
  }
  return result;
}
References obj_to_instance_set.
Referenced by Slic3r::GUI::PartPlateList::construct_objects_list_for_new_plate(), Slic3r::GUI::PartPlateList::find_instance(), get_instance(), Slic3r::GUI::PartPlateList::notify_instance_removed(), Slic3r::GUI::PartPlateList::notify_instance_update(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::Selection::remove_curr_plate(), and Slic3r::GUI::GLCanvas3D::Labels::render().
contain_instance_totally() [1/2]
bool Slic3r::GUI::PartPlate::contain_instance_totally (int obj_id, int instance_id) const
{
  bool result = false;
  std::set<std::pair<int, int>>::iterator it;
  it = obj_to_instance_set.find(std::pair(obj_id, instance_id));
  if (it != obj_to_instance_set.end()) {
    it = instance_outside_set.find(std::pair(obj_id, instance_id));
    if (it == instance_outside_set.end())
      result = true;
  }
  return result;
}
References instance_outside_set, and obj_to_instance_set.
contain_instance_totally() [2/2]
bool Slic3r::GUI::PartPlate::contain_instance_totally (ModelObject * object, int instance_id) const
{
  bool result = false;
  int obj_id = -1;
  for (int index = 0; index < m_model->objects.size(); index ++)
  {
    if (m_model->objects[index] == object)
    {
      obj_id = index;
      break;
    }
  }
  if ((obj_id >= 0 ) && (obj_id < m_model->objects.size()))
    result = contain_instance_totally(obj_id, instance_id);
  return result;
}
References contain_instance_totally(), m_model, and Slic3r::Model::objects.
Referenced by Slic3r::GUI::Selection::add_curr_plate(), Slic3r::GUI::ObjectDataViewModel::AddPlate(), contain_instance_totally(), estimate_wipe_tower_size(), Slic3r::GUI::PartPlateList::find_instance_belongs(), get_extruders(), and get_extruders_without_support().
contains() [1/3]
bool Slic3r::GUI::PartPlate::contains (const BoundingBoxf3 & bb) const
{
  // Allow the objects to protrude below the print bed
  BoundingBoxf3 print_volume(Vec3d(m_bounding_box.min(0), m_bounding_box.min(1), 0.0), Vec3d(m_bounding_box.max(0), m_bounding_box.max(1), 1e3));
  print_volume.min(2) = -1e10;
  print_volume.min(0) -= Slic3r::BuildVolume::BedEpsilon;
  print_volume.min(1) -= Slic3r::BuildVolume::BedEpsilon;
  print_volume.max(0) += Slic3r::BuildVolume::BedEpsilon;
  print_volume.max(1) += Slic3r::BuildVolume::BedEpsilon;
  return print_volume.contains(bb);
}
References Slic3r::BuildVolume::BedEpsilon, Slic3r::BoundingBox3Base< PointClass >::contains(), m_bounding_box, Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::BoundingBoxBase< PointClass >::min.
contains() [2/3]
bool Slic3r::GUI::PartPlate::contains (const GLVolume & v) const
{
  return m_bounding_box.contains(v.bounding_box());
}
References Slic3r::GLVolume::bounding_box(), Slic3r::BoundingBox3Base< PointClass >::contains(), and m_bounding_box.
contains() [3/3]
bool Slic3r::GUI::PartPlate::contains (const Vec3d & point) const
{
  return m_bounding_box.contains(point);
}
References Slic3r::BoundingBox3Base< PointClass >::contains(), and m_bounding_box.
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
duplicate_all_instance()
void Slic3r::GUI::PartPlate::duplicate_all_instance (unsigned int dup_count, bool need_skip, std::map< int, bool > & skip_objects)
{
    std::set<std::pair<int, int>> old_obj_list = obj_to_instance_set;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": plate_id %1%, dup_count %2%") % m_plate_index % dup_count;
    for (std::set<std::pair<int, int>>::iterator it = old_obj_list.begin(); it != old_obj_list.end(); ++it)
    {
        int obj_id = it->first;
        int instance_id = it->second;
        if ((obj_id >= 0) && (obj_id < m_model->objects.size()))
        {
            ModelObject* object = m_model->objects[obj_id];
            ModelInstance* instance = object->instances[instance_id];
            if (need_skip)
            {
                if (skip_objects.find(instance->loaded_id) != skip_objects.end())
                {
                    instance->printable = false;
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": skipped object, loaded_id %1%, name %2%, set to unprintable, no need to duplicate") % instance->loaded_id % object->name;
                    continue;
                }
            }
            for (size_t index = 0; index < dup_count; index ++)
            {
                ModelObject* newObj = m_model->add_object(*object);
                newObj->name = object->name +"_"+ std::to_string(index+1);
                int new_obj_id = m_model->objects.size() - 1;
                for ( size_t new_instance_id = 0; new_instance_id < object->instances.size(); new_instance_id++ )
                {
                    obj_to_instance_set.emplace(std::pair(new_obj_id, new_instance_id));
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": duplicate object into plate: index_pair [%1%,%2%], obj_id %3%") % new_obj_id % new_instance_id % newObj->id().id;
                }
            }
        }
    }
    return;
}
References Slic3r::Model::add_object(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), Slic3r::ModelInstance::loaded_id, m_model, m_plate_index, Slic3r::ModelObject::name, obj_to_instance_set, Slic3r::Model::objects, and Slic3r::ModelInstance::printable.
empty()
bool Slic3r::GUI::PartPlate::empty () inline
{ return obj_to_instance_set.empty(); }
References obj_to_instance_set.
Referenced by check_outside(), is_valid_gcode_file(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), and Slic3r::GUI::Selection::remove_curr_plate().
estimate_wipe_tower_size()
Vec3d Slic3r::GUI::PartPlate::estimate_wipe_tower_size (const double w, const double wipe_volume) const
{
  Vec3d wipe_tower_size;
  std::vector<int> plate_extruders = get_extruders(true);
  double layer_height = 0.08f; // hard code layer height
  double max_height = 0.f;
  wipe_tower_size.setZero();
  wipe_tower_size(0) = w;
  ConfigOption* layer_height_opt = wxGetApp().preset_bundle->prints.get_edited_preset().config.option("layer_height");
  if (layer_height_opt)
    layer_height = layer_height_opt->getFloat();
  // empty plate
  if (plate_extruders.empty())
    return wipe_tower_size;
  for (int obj_idx = 0; obj_idx < m_model->objects.size(); obj_idx++) {
    if (!contain_instance_totally(obj_idx, 0))
      continue;
    BoundingBoxf3 bbox = m_model->objects[obj_idx]->bounding_box();
    max_height = std::max(bbox.size().z(), max_height);
  }
  wipe_tower_size(2) = max_height;
  const DynamicPrintConfig &dconfig = wxGetApp().preset_bundle->prints.get_edited_preset().config;
    auto timelapse_type    = dconfig.option<ConfigOptionEnum<TimelapseType>>("timelapse_type");
    bool timelapse_enabled = timelapse_type ? (timelapse_type->value == TimelapseType::tlSmooth) : false;
  double depth = wipe_volume * (plate_extruders.size() - 1) / (layer_height * w);
    if (timelapse_enabled || depth > EPSILON) {
    float min_wipe_tower_depth = 0.f;
    auto iter = WipeTower::min_depth_per_height.begin();
    while (iter != WipeTower::min_depth_per_height.end()) {
      auto curr_height_to_depth = *iter;
      // This is the case that wipe tower height is lower than the first min_depth_to_height member.
      if (curr_height_to_depth.first >= max_height) {
        min_wipe_tower_depth = curr_height_to_depth.second;
        break;
      }
      iter++;
      // If curr_height_to_depth is the last member, use its min_depth.
      if (iter == WipeTower::min_depth_per_height.end()) {
        min_wipe_tower_depth = curr_height_to_depth.second;
        break;
      }
      // If wipe tower height is between the current and next member, set the min_depth as linear interpolation between them
      auto next_height_to_depth = *iter;
      if (next_height_to_depth.first > max_height) {
        float height_base = curr_height_to_depth.first;
        float height_diff = next_height_to_depth.first - curr_height_to_depth.first;
        float min_depth_base = curr_height_to_depth.second;
        float depth_diff = next_height_to_depth.second - curr_height_to_depth.second;
        min_wipe_tower_depth = min_depth_base + (max_height - curr_height_to_depth.first) / height_diff * depth_diff;
        break;
      }
    }
    depth = std::max((double)min_wipe_tower_depth, depth);
  }
  wipe_tower_size(1) = depth;
  return wipe_tower_size;
}
References contain_instance_totally(), end, EPSILON, get_extruders(), Slic3r::ConfigOption::getFloat(), Slic3r::GUI::layer_height, m_model, Slic3r::WipeTower::min_depth_per_height, Slic3r::Model::objects, Slic3r::ConfigBase::option(), Eigen::PlainObjectBase< Derived >::setZero(), Slic3r::BoundingBox3Base< PointClass >::size(), and Slic3r::tlSmooth.
Referenced by Slic3r::GUI::GLCanvas3D::estimate_wipe_tower_points(), and Slic3r::GUI::GLCanvas3D::reload_scene().
fff_print()
Print * Slic3r::GUI::PartPlate::fff_print () inline
{ return m_print; }
References m_print.
generate_exclude_polygon()
void Slic3r::GUI::PartPlate::generate_exclude_polygon (ExPolygon & exclude_polygon) private
{
  auto compute_exclude_points = [&exclude_polygon](Vec2d& center, double radius, double start_angle, double stop_angle, int count)
  {
    double angle, angle_steps;
    angle_steps = (stop_angle - start_angle) / (count - 1);
    for(int j = 0; j < count; j++ )
    {
      double angle = start_angle + j * angle_steps;
      double x = center(0) + ::cos(angle) * radius;
      double y = center(1) + ::sin(angle) * radius;
      exclude_polygon.contour.append({ scale_(x), scale_(y) });
    }
  };
  int points_count = 8;
  if (m_exclude_area.size() == 4)
  {
      //rectangle case
      for (int i = 0; i < 4; i++)
      {
        const Vec2d& p = m_exclude_area[i];
        Vec2d center;
        double start_angle, stop_angle, angle_steps, radius_x, radius_y, radius;
        switch (i) {
          case 0:
            radius = 5.f;
            center(0) = p(0) + radius;
            center(1) = p(1) + radius;
            start_angle = PI;
            stop_angle = 1.5 * PI;
            compute_exclude_points(center, radius, start_angle, stop_angle, points_count);
            break;
          case 1:
            exclude_polygon.contour.append({ scale_(p(0)), scale_(p(1)) });
            break;
          case 2:
            radius = 3.f;
            center(0) = p(0) - radius;
            center(1) = p(1) - radius;
            start_angle = 0;
            stop_angle = 0.5 * PI;
            compute_exclude_points(center, radius, start_angle, stop_angle, points_count);
            break;
          case 3:
            exclude_polygon.contour.append({ scale_(p(0)), scale_(p(1)) });
            break;
        }
      }
  }
  else {
    for (const Vec2d& p : m_exclude_area) {
      exclude_polygon.contour.append({ scale_(p(0)), scale_(p(1)) });
    }
  }
}
References Slic3r::angle(), Slic3r::MultiPoint::append(), Slic3r::ExPolygon::contour, cos(), count, m_exclude_area, Slic3r::GUI::PI, scale_, and sin().
Referenced by set_shape().
generate_logo_polygon()
void Slic3r::GUI::PartPlate::generate_logo_polygon (ExPolygon & logo_polygon) private
{
  if (m_shape.size() == 4)
  {
    //rectangle case
    for (int i = 0; i < 4; i++)
    {
      const Vec2d& p = m_shape[i];
      if ((i  == 0) || (i  == 1)) {
        logo_polygon.contour.append({ scale_(p(0)), scale_(p(1) - 12.f) });
      }
      else {
        logo_polygon.contour.append({ scale_(p(0)), scale_(p(1)) });
      }
    }
  }
  else {
    for (const Vec2d& p : m_shape) {
      logo_polygon.contour.append({ scale_(p(0)), scale_(p(1)) });
    }
  }
}
References Slic3r::MultiPoint::append(), Slic3r::ExPolygon::contour, m_shape, and scale_.
Referenced by set_shape().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
generate_plate_name_texture()
void Slic3r::GUI::PartPlate::generate_plate_name_texture ()
{
  // generate m_name_texture texture from m_name with generate_from_text_string
  m_name_texture.reset();
  auto text = m_name.empty()? _L("Untitled") : from_u8(m_name);
  wxCoord w, h;
  auto* font = &Label::Head_32;
  wxColour foreground(0xf2, 0x75, 0x4e, 0xff);
    if (!m_name_texture.generate_from_text_string(text.ToUTF8().data(), *font, *wxBLACK, foreground))
    BOOST_LOG_TRIVIAL(error) << "PartPlate::generate_plate_name_texture(): generate_from_text_string() failed";
    auto bed_ext = get_extents(m_shape);
    auto factor = bed_ext.size()(1) / 200.0;
  ExPolygon poly;
  float offset_x = 1;
    w = int(factor * (m_name_texture.get_width() * 16) / m_name_texture.get_height());
    h = int(factor * 16);
    Vec2d p = bed_ext[3] + Vec2d(0, 1 + h * m_name_texture.m_original_height / m_name_texture.get_height());
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + offset_x), scale_(p(1) - h + PARTPLATE_TEXT_OFFSET_Y) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + w - offset_x), scale_(p(1) - h + PARTPLATE_TEXT_OFFSET_Y) });
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + w - offset_x), scale_(p(1) - PARTPLATE_TEXT_OFFSET_Y)});
  poly.contour.append({ scale_(p(0) + PARTPLATE_ICON_GAP_LEFT + offset_x), scale_(p(1) - PARTPLATE_TEXT_OFFSET_Y) });
  auto triangles = triangulate_expolygon_2f(poly, NORMALS_UP);
  if (!m_plate_name_icon.set_from_triangles(triangles, GROUND_Z))
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "Unable to generate geometry buffers for icons\n";
  if (m_plate_name_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_plate_name_vbo_id));
    m_plate_name_vbo_id = 0;
  }
}
References _L, Slic3r::MultiPoint::append(), Slic3r::ExPolygon::contour, error, Slic3r::GUI::from_u8(), Slic3r::GUI::GLTexture::generate_from_text_string(), Slic3r::get_extents(), Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_width(), glsafe, GROUND_Z, Label::Head_32, int, m_name, m_name_texture, Slic3r::GUI::GLTexture::m_original_height, m_plate_name_icon, m_plate_name_vbo_id, m_shape, Slic3r::NORMALS_UP, PARTPLATE_ICON_GAP_LEFT, PARTPLATE_TEXT_OFFSET_Y, Slic3r::GUI::GLTexture::reset(), scale_, Slic3r::GUI::GeometryBuffer::set_from_triangles(), and Slic3r::triangulate_expolygon_2f().
Referenced by render_plate_name_texture(), set_plate_name(), and set_shape().
generate_print_polygon()
void Slic3r::GUI::PartPlate::generate_print_polygon (ExPolygon & print_polygon) private
{
  auto compute_points = [&print_polygon](Vec2d& center, double radius, double start_angle, double stop_angle, int count)
  {
    double angle, angle_steps;
    angle_steps = (stop_angle - start_angle) / (count - 1);
    for(int j = 0; j < count; j++ )
    {
      double angle = start_angle + j * angle_steps;
      double x = center(0) + ::cos(angle) * radius;
      double y = center(1) + ::sin(angle) * radius;
      print_polygon.contour.append({ scale_(x), scale_(y) });
    }
  };
  int points_count = 8;
  if (m_shape.size() == 4)
  {
      //rectangle case
      for (int i = 0; i < 4; i++)
      {
        const Vec2d& p = m_shape[i];
        Vec2d center;
        double start_angle, stop_angle, angle_steps, radius_x, radius_y, radius;
        switch (i) {
          case 0:
            radius = 5.f;
            center(0) = p(0) + radius;
            center(1) = p(1) + radius;
            start_angle = PI;
            stop_angle = 1.5 * PI;
            compute_points(center, radius, start_angle, stop_angle, points_count);
            break;
          case 1:
            print_polygon.contour.append({ scale_(p(0)), scale_(p(1)) });
            break;
          case 2:
            radius_x = (int)(p(0)) % 10;
                        radius_y = (int)(p(1)) % 10;
            radius = (radius_x > radius_y)?radius_y: radius_x;
            if (radius < 5.0)
              radius = 5.f;
            center(0) = p(0) - radius;
            center(1) = p(1) - radius;
            start_angle = 0;
            stop_angle = 0.5 * PI;
            compute_points(center, radius, start_angle, stop_angle, points_count);
            break;
          case 3:
                        radius_x = (int)(p(0)) % 10;
            radius_y = (int)(p(1)) % 10;
            radius = (radius_x > radius_y)?radius_y: radius_x;
            if (radius < 5.0)
              radius = 5.f;
            center(0) = p(0) + radius;
            center(1) = p(1) - radius;
            start_angle = 0.5 * PI;
            stop_angle = PI;
            compute_points(center, radius, start_angle, stop_angle, points_count);
            break;
        }
      }
  }
  else {
    for (const Vec2d& p : m_shape) {
      print_polygon.contour.append({ scale_(p(0)), scale_(p(1)) });
    }
  }
}
References Slic3r::angle(), Slic3r::MultiPoint::append(), Slic3r::ExPolygon::contour, cos(), count, int, m_shape, Slic3r::GUI::PI, scale_, and sin().
Referenced by set_shape().
get_bed_type()
BedType Slic3r::GUI::PartPlate::get_bed_type (bool load_from_project = false) const
{
  std::string bed_type_key = "curr_bed_type";
  if (m_config.has(bed_type_key)) {
    BedType bed_type = m_config.opt_enum<BedType>(bed_type_key);
    return bed_type;
  }
  if (!load_from_project || !m_plater || !wxGetApp().preset_bundle)
    return btDefault;
  DynamicConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
  if (proj_cfg.has(bed_type_key))
    return proj_cfg.opt_enum<BedType>(bed_type_key);
  return btDefault;
}
References Slic3r::btDefault, Slic3r::ConfigOptionResolver::has(), m_config, m_plater, and Slic3r::DynamicConfig::opt_enum().
Referenced by Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::GUI::PrintJob::process(), render_icons(), render_logo(), Slic3r::CLI::run(), Slic3r::GUI::Plater::select_plate_by_hover_id(), and set_bed_type().
get_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::PartPlate::get_bounding_box (bool extended = false) inline
{ return extended ? m_extended_bounding_box : m_bounding_box; }
References m_bounding_box, and m_extended_bounding_box.
Referenced by Slic3r::GUI::GLCanvas3D::_get_current_partplate_print_volume(), Slic3r::GUI::GCodeViewer::_render_calibration_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::on_gesture(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLCanvas3D::plate_scene_bounding_box(), Slic3r::CLI::run(), and Slic3r::GUI::GLCanvas3D::zoom_to_plate().
get_bounding_box_crd()
const BoundingBox Slic3r::GUI::PartPlate::get_bounding_box_crd ()
{
  const auto plate_shape = Slic3r::Polygon::new_scale(m_shape);
  return plate_shape.bounding_box();
}
References m_shape, and Slic3r::Polygon::new_scale().
Referenced by Slic3r::GUI::FillBedJob::prepare(), and Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
get_build_volume()
BoundingBoxf3 Slic3r::GUI::PartPlate::get_build_volume () inline
    {
        Vec3d up_point = m_bounding_box.max + Vec3d(0, 0, m_origin.z() + m_height);
        Vec3d low_point = m_bounding_box.min + Vec3d(0, 0, m_origin.z());
        BoundingBoxf3 plate_box(low_point, up_point);
        return plate_box;
    }
References m_bounding_box, m_height, m_origin, Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::BoundingBoxBase< PointClass >::min.
Referenced by Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::GUI::Selection::paste_objects_from_clipboard(), and Slic3r::GUI::GLCanvas3D::render_thumbnail_internal().
get_center_origin()
Vec3d Slic3r::GUI::PartPlate::get_center_origin ()
{
  Vec3d origin;
  origin(0) = (m_bounding_box.min(0) + m_bounding_box.max(0)) / 2;//m_origin.x() + m_width / 2;
  origin(1) = (m_bounding_box.min(1) + m_bounding_box.max(1)) / 2; //m_origin.y() + m_depth / 2;
  origin(2) = m_origin.z();
  return origin;
}
References m_bounding_box, m_origin, Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::BoundingBoxBase< PointClass >::min.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), add_instance(), Slic3r::GUI::MenuFactory::append_menu_item_center(), and Slic3r::GUI::Selection::center().
get_exclude_areas()
const std::vector< BoundingBoxf3 > & Slic3r::GUI::PartPlate::get_exclude_areas () inline
{ return m_exclude_bounding_box; }
References m_exclude_bounding_box.
Referenced by Slic3r::GLVolumeCollection::check_outside_state(), and Slic3r::GUI::GLCanvas3D::load_gcode_preview().
get_extruders()
std::vector< int > Slic3r::GUI::PartPlate::get_extruders (bool conside_custom_gcode = false) const
{
  std::vector<int> plate_extruders;
  // if gcode.3mf file
  if (m_model->objects.empty()) {
    for (int i = 0; i < slice_filaments_info.size(); i++) {
      plate_extruders.push_back(slice_filaments_info[i].id + 1);
    }
    return plate_extruders;
  }
  // if 3mf file
  const DynamicPrintConfig& glb_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
  int glb_support_intf_extr = glb_config.opt_int("support_interface_filament");
  int glb_support_extr = glb_config.opt_int("support_filament");
  bool glb_support = glb_config.opt_bool("enable_support");
    glb_support |= glb_config.opt_int("raft_layers") > 0;
  for (int obj_idx = 0; obj_idx < m_model->objects.size(); obj_idx++) {
    if (!contain_instance_totally(obj_idx, 0))
      continue;
    ModelObject* mo = m_model->objects[obj_idx];
    for (ModelVolume* mv : mo->volumes) {
      std::vector<int> volume_extruders = mv->get_extruders();
      plate_extruders.insert(plate_extruders.end(), volume_extruders.begin(), volume_extruders.end());
    }
    // layer range
        for (auto layer_range : mo->layer_config_ranges) {
            if (layer_range.second.has("extruder")) {
                if (auto id = layer_range.second.option("extruder")->getInt(); id > 0)
          plate_extruders.push_back(id);
      }
    }
    bool obj_support = false;
    const ConfigOption* obj_support_opt = mo->config.option("enable_support");
        const ConfigOption *obj_raft_opt    = mo->config.option("raft_layers");
    if (obj_support_opt != nullptr || obj_raft_opt != nullptr) {
            if (obj_support_opt != nullptr)
        obj_support = obj_support_opt->getBool();
            if (obj_raft_opt != nullptr)
        obj_support |= obj_raft_opt->getInt() > 0;
        }
    else
      obj_support = glb_support;
    if (!obj_support)
      continue;
    int obj_support_intf_extr = 0;
    const ConfigOption* support_intf_extr_opt = mo->config.option("support_interface_filament");
    if (support_intf_extr_opt != nullptr)
      obj_support_intf_extr = support_intf_extr_opt->getInt();
    if (obj_support_intf_extr != 0)
      plate_extruders.push_back(obj_support_intf_extr);
    else if (glb_support_intf_extr != 0)
      plate_extruders.push_back(glb_support_intf_extr);
    int obj_support_extr = 0;
    const ConfigOption* support_extr_opt = mo->config.option("support_filament");
    if (support_extr_opt != nullptr)
      obj_support_extr = support_extr_opt->getInt();
    if (obj_support_extr != 0)
      plate_extruders.push_back(obj_support_extr);
    else if (glb_support_extr != 0)
      plate_extruders.push_back(glb_support_extr);
  }
  if (conside_custom_gcode) {
    //BBS
        int nums_extruders = 0;
        if (const ConfigOptionStrings *color_option = dynamic_cast<const ConfigOptionStrings *>(wxGetApp().preset_bundle->project_config.option("filament_colour"))) {
            nums_extruders = color_option->values.size();
      if (m_model->plates_custom_gcodes.find(m_plate_index) != m_model->plates_custom_gcodes.end()) {
        for (auto item : m_model->plates_custom_gcodes.at(m_plate_index).gcodes) {
          if (item.type == CustomGCode::Type::ToolChange && item.extruder <= nums_extruders)
            plate_extruders.push_back(item.extruder);
        }
      }
    }
  }
  std::sort(plate_extruders.begin(), plate_extruders.end());
  auto it_end = std::unique(plate_extruders.begin(), plate_extruders.end());
  plate_extruders.resize(std::distance(plate_extruders.begin(), it_end));
  return plate_extruders;
}
References Slic3r::ModelObject::config, contain_instance_totally(), std::distance(), Slic3r::ConfigOption::getBool(), Slic3r::ConfigOption::getInt(), Slic3r::ModelObject::layer_config_ranges, m_model, m_plate_index, Slic3r::Model::objects, Slic3r::DynamicConfig::opt_bool(), Slic3r::DynamicConfig::opt_int(), Slic3r::ModelConfig::option(), Slic3r::Model::plates_custom_gcodes, slice_filaments_info, Slic3r::CustomGCode::ToolChange, and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::GLCanvas3D::estimate_wipe_tower_points(), estimate_wipe_tower_size(), and Slic3r::GLVolumeCollection::load_wipe_tower_preview().
get_extruders_under_cli()
std::vector< int > Slic3r::GUI::PartPlate::get_extruders_under_cli (bool conside_custom_gcode, DynamicPrintConfig & full_config) const
{
    std::vector<int> plate_extruders;
    // if 3mf file
    int glb_support_intf_extr = full_config.opt_int("support_interface_filament");
    int glb_support_extr = full_config.opt_int("support_filament");
    bool glb_support = full_config.opt_bool("enable_support");
    glb_support |= full_config.opt_int("raft_layers") > 0;
    for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it)
    {
        int obj_id = it->first;
        int instance_id = it->second;
        if ((obj_id >= 0) && (obj_id < m_model->objects.size()))
        {
            ModelObject* object = m_model->objects[obj_id];
            ModelInstance* instance = object->instances[instance_id];
            if (!instance->printable)
                continue;
            for (ModelVolume* mv : object->volumes) {
                std::vector<int> volume_extruders = mv->get_extruders();
                plate_extruders.insert(plate_extruders.end(), volume_extruders.begin(), volume_extruders.end());
            }
            // layer range
            for (auto layer_range : object->layer_config_ranges) {
                if (layer_range.second.has("extruder")) {
                    if (auto id = layer_range.second.option("extruder")->getInt(); id > 0)
                        plate_extruders.push_back(id);
                }
            }
            bool obj_support = false;
            const ConfigOption* obj_support_opt = object->config.option("enable_support");
            const ConfigOption *obj_raft_opt    = object->config.option("raft_layers");
            if (obj_support_opt != nullptr || obj_raft_opt != nullptr) {
                if (obj_support_opt != nullptr)
                    obj_support = obj_support_opt->getBool();
                if (obj_raft_opt != nullptr)
                    obj_support |= obj_raft_opt->getInt() > 0;
            }
            else
                obj_support = glb_support;
            if (!obj_support)
                continue;
            int obj_support_intf_extr = 0;
            const ConfigOption* support_intf_extr_opt = object->config.option("support_interface_filament");
            if (support_intf_extr_opt != nullptr)
                obj_support_intf_extr = support_intf_extr_opt->getInt();
            if (obj_support_intf_extr != 0)
                plate_extruders.push_back(obj_support_intf_extr);
            else if (glb_support_intf_extr != 0)
                plate_extruders.push_back(glb_support_intf_extr);
            int obj_support_extr = 0;
            const ConfigOption* support_extr_opt = object->config.option("support_filament");
            if (support_extr_opt != nullptr)
                obj_support_extr = support_extr_opt->getInt();
            if (obj_support_extr != 0)
                plate_extruders.push_back(obj_support_extr);
            else if (glb_support_extr != 0)
                plate_extruders.push_back(glb_support_extr);
        }
    }
    if (conside_custom_gcode) {
        //BBS
        int nums_extruders = 0;
        if (const ConfigOptionStrings *color_option = dynamic_cast<const ConfigOptionStrings *>(full_config.option("filament_colour"))) {
            nums_extruders = color_option->values.size();
            if (m_model->plates_custom_gcodes.find(m_plate_index) != m_model->plates_custom_gcodes.end()) {
                for (auto item : m_model->plates_custom_gcodes.at(m_plate_index).gcodes) {
                    if (item.type == CustomGCode::Type::ToolChange && item.extruder <= nums_extruders)
                        plate_extruders.push_back(item.extruder);
                }
            }
        }
    }
    std::sort(plate_extruders.begin(), plate_extruders.end());
    auto it_end = std::unique(plate_extruders.begin(), plate_extruders.end());
    plate_extruders.resize(std::distance(plate_extruders.begin(), it_end));
    return plate_extruders;
}
References std::distance(), Slic3r::ConfigOption::getBool(), Slic3r::ConfigOption::getInt(), m_model, m_plate_index, obj_to_instance_set, Slic3r::Model::objects, Slic3r::DynamicConfig::opt_bool(), Slic3r::DynamicConfig::opt_int(), Slic3r::ConfigBase::option(), Slic3r::Model::plates_custom_gcodes, Slic3r::ModelInstance::printable, and Slic3r::CustomGCode::ToolChange.
get_extruders_without_support()
std::vector< int > Slic3r::GUI::PartPlate::get_extruders_without_support (bool conside_custom_gcode = false) const
{
  std::vector<int> plate_extruders;
  // if gcode.3mf file
  if (m_model->objects.empty()) {
    for (int i = 0; i < slice_filaments_info.size(); i++) {
      plate_extruders.push_back(slice_filaments_info[i].id + 1);
    }
    return plate_extruders;
  }
  // if 3mf file
  const DynamicPrintConfig& glb_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
  for (int obj_idx = 0; obj_idx < m_model->objects.size(); obj_idx++) {
    if (!contain_instance_totally(obj_idx, 0))
      continue;
    ModelObject* mo = m_model->objects[obj_idx];
    for (ModelVolume* mv : mo->volumes) {
      std::vector<int> volume_extruders = mv->get_extruders();
      plate_extruders.insert(plate_extruders.end(), volume_extruders.begin(), volume_extruders.end());
    }
  }
  if (conside_custom_gcode) {
    //BBS
    int nums_extruders = 0;
    if (const ConfigOptionStrings* color_option = dynamic_cast<const ConfigOptionStrings*>(wxGetApp().preset_bundle->project_config.option("filament_colour"))) {
      nums_extruders = color_option->values.size();
      if (m_model->plates_custom_gcodes.find(m_plate_index) != m_model->plates_custom_gcodes.end()) {
        for (auto item : m_model->plates_custom_gcodes.at(m_plate_index).gcodes) {
          if (item.type == CustomGCode::Type::ToolChange && item.extruder <= nums_extruders)
            plate_extruders.push_back(item.extruder);
        }
      }
    }
  }
  std::sort(plate_extruders.begin(), plate_extruders.end());
  auto it_end = std::unique(plate_extruders.begin(), plate_extruders.end());
  plate_extruders.resize(std::distance(plate_extruders.begin(), it_end));
  return plate_extruders;
}
References contain_instance_totally(), std::distance(), m_model, m_plate_index, Slic3r::Model::objects, Slic3r::Model::plates_custom_gcodes, slice_filaments_info, Slic3r::CustomGCode::ToolChange, and Slic3r::ModelObject::volumes.
get_gcode_filename()
std::string Slic3r::GUI::PartPlate::get_gcode_filename ()
{
  if (is_slice_result_valid() && get_slice_result()) {
    return m_gcode_result->filename;
  }
  return "";
}
References Slic3r::GCodeProcessorResult::filename, get_slice_result(), is_slice_result_valid(), and m_gcode_result.
Referenced by is_valid_gcode_file().
get_index()
int Slic3r::GUI::PartPlate::get_index () inline
{ return m_plate_index; }
References m_plate_index.
Referenced by Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModel::AddObject(), Slic3r::GUI::ObjectDataViewModel::AddPlate(), Slic3r::BackgroundSlicingProcess::can_switch_print(), Slic3r::GUI::PartPlateList::delete_plate(), operator<(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::CLI::run(), and Slic3r::GUI::ObjectList::update_selections().
get_instance()
ModelInstance * Slic3r::GUI::PartPlate::get_instance (int obj_id, int instance_id)
{
  if (!contain_instance(obj_id, instance_id))
    return nullptr;
  else
    return m_model->objects[obj_id]->instances[instance_id];
}
References contain_instance(), m_model, and Slic3r::Model::objects.
get_objects()
ModelObjectPtrs Slic3r::GUI::PartPlate::get_objects () inline
{ return m_model->objects; }
References m_model, and Slic3r::Model::objects.
Referenced by Slic3r::GUI::MenuFactory::create_plate_menu().
get_origin()
Vec3d Slic3r::GUI::PartPlate::get_origin () inline
{ return m_origin; }
References m_origin.
Referenced by Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::estimate_wipe_tower_points(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GCodeViewer::SequentialView::Marker::render(), and Slic3r::CLI::run().
get_plate_name()
std::string Slic3r::GUI::PartPlate::get_plate_name () const inline
{ return m_name; }
References m_name.
Referenced by Slic3r::GUI::Plater::select_plate_by_hover_id().
get_print()
void Slic3r::GUI::PartPlate::get_print (PrintBase ** print, GCodeResult ** result, int * index)
{
  if (print && (printer_technology == PrinterTechnology::ptFFF))
    *print = m_print;
  if (result)
    *result = m_gcode_result;
  if (index)
    *index = m_print_index;
  return;
}
References m_gcode_result, m_print, m_print_index, print(), printer_technology, and Slic3r::ptFFF.
Referenced by Slic3r::GUI::PartPlateList::delete_plate(), Slic3r::GUI::PartPlateList::get_current_fff_print(), Slic3r::CLI::run(), Slic3r::GUI::Plater::select_plate(), and Slic3r::GUI::Plater::select_plate_by_hover_id().
get_print_seq()
PrintSequence Slic3r::GUI::PartPlate::get_print_seq () const
{
    std::string print_seq_key = "print_sequence";
    if (m_config.has(print_seq_key)) {
        PrintSequence print_seq = m_config.opt_enum<PrintSequence>(print_seq_key);
        return print_seq;
    }
    return PrintSequence::ByDefault;
}
References Slic3r::ByDefault, Slic3r::ConfigOptionResolver::has(), m_config, and Slic3r::DynamicConfig::opt_enum().
Referenced by get_real_print_seq(), Slic3r::GUI::ObjectList::OnBeginDrag(), Slic3r::GUI::GLCanvas3D::reload_scene(), render_icons(), Slic3r::CLI::run(), Slic3r::GUI::Plater::select_plate_by_hover_id(), and set_print_seq().
get_real_print_seq()
PrintSequence Slic3r::GUI::PartPlate::get_real_print_seq () const
{
    PrintSequence curr_plate_seq = get_print_seq();
    if (curr_plate_seq == PrintSequence::ByDefault) {
        auto curr_preset_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
        if (curr_preset_config.has("print_sequence")) curr_plate_seq = curr_preset_config.option<ConfigOptionEnum<PrintSequence>>("print_sequence")->value;
    }
    return curr_plate_seq;
}
References Slic3r::ByDefault, and get_print_seq().
Referenced by Slic3r::GUI::init_arrange_params(), and Slic3r::GUI::ArrangeJob::prepare_partplate().
get_shape()
const Pointfs & Slic3r::GUI::PartPlate::get_shape () const inline
{ return m_shape; }
References m_shape.
Referenced by Slic3r::GLVolumeCollection::check_outside_state(), Slic3r::CLI::run(), and Slic3r::GUI::Plater::priv::update_print_volume_state().
get_slice_result()
GCodeProcessorResult * Slic3r::GUI::PartPlate::get_slice_result () inline
{ return m_gcode_result; }
References m_gcode_result.
Referenced by Slic3r::GUI::PartPlateList::get_current_slice_result(), get_gcode_filename(), get_used_extruders(), Slic3r::GUI::SelectMachineDialog::on_ok_btn(), Slic3r::CLI::run(), Slic3r::GUI::SelectMachineDialog::set_default(), and Slic3r::GUI::SendToPrinterDialog::set_default().
get_slicing_percent()
float Slic3r::GUI::PartPlate::get_slicing_percent () inline
{ return m_slice_percent; }
References m_slice_percent.
Referenced by Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), and Slic3r::GUI::Plater::priv::on_slicing_update().
get_temp_config_3mf_path()
std::string Slic3r::GUI::PartPlate::get_temp_config_3mf_path ()
{
  if (m_temp_config_3mf_path.empty()) {
    boost::filesystem::path temp_path(m_model->get_backup_path("Metadata"));
    temp_path /= (boost::format(".%1%.%2%_config.3mf") % get_current_pid() %
      GLOBAL_PLATE_INDEX++).str();
    m_temp_config_3mf_path = temp_path.string();
  }
  return m_temp_config_3mf_path;
}
References Slic3r::Model::get_backup_path(), Slic3r::get_current_pid(), GLOBAL_PLATE_INDEX, m_model, and m_temp_config_3mf_path.
Referenced by Slic3r::GUI::Plater::export_config_3mf().
get_tmp_gcode_path()
std::string Slic3r::GUI::PartPlate::get_tmp_gcode_path ()
{
    if (m_tmp_gcode_path.empty()) {
        boost::filesystem::path temp_path(m_model->get_backup_path("Metadata"));
        temp_path /= (boost::format(".%1%.%2%.gcode") % get_current_pid() %
                      GLOBAL_PLATE_INDEX++).str();
        m_tmp_gcode_path = temp_path.string();
    }
    return m_tmp_gcode_path;
}
References Slic3r::Model::get_backup_path(), Slic3r::get_current_pid(), GLOBAL_PLATE_INDEX, m_model, and m_tmp_gcode_path.
Referenced by Slic3r::GUI::SelectMachineDialog::is_show_timelapse(), Slic3r::BackgroundSlicingProcess::process_fff(), Slic3r::CLI::run(), and Slic3r::GUI::Plater::send_gcode().
get_used_extruders()
std::vector< int > Slic3r::GUI::PartPlate::get_used_extruders ()
{
  std::vector<int> used_extruders;
  // if gcode.3mf file
  if (m_model->objects.empty()) {
    for (int i = 0; i < slice_filaments_info.size(); i++) {
      used_extruders.push_back(slice_filaments_info[i].id + 1);
    }
    return used_extruders;
  }
  GCodeProcessorResult* result = get_slice_result();
  if (!result)
    return used_extruders;
  PrintEstimatedStatistics& ps = result->print_statistics;
  for (auto it = ps.volumes_per_extruder.begin(); it != ps.volumes_per_extruder.end(); it++) {
    used_extruders.push_back(it->first + 1);
  }
  return used_extruders;
}
References get_slice_result(), m_model, Slic3r::Model::objects, Slic3r::GCodeProcessorResult::print_statistics, slice_filaments_info, and Slic3r::PrintEstimatedStatistics::volumes_per_extruder.
has_printable_instances()
bool Slic3r::GUI::PartPlate::has_printable_instances ()
{
  bool result = false;
  for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it)
  {
    int obj_id = it->first;
    int instance_id = it->second;
    if (obj_id >= m_model->objects.size())
      continue;
    ModelObject* object = m_model->objects[obj_id];
    ModelInstance* instance = object->instances[instance_id];
    if ((instance->printable)&&(instance_outside_set.find(std::pair(obj_id, instance_id)) == instance_outside_set.end()))
    {
      result = true;
      break;
    }
  }
  return result;
}
References instance_outside_set, m_model, obj_to_instance_set, Slic3r::Model::objects, and Slic3r::ModelInstance::printable.
Referenced by Slic3r::GUI::GCodeViewer::load(), Slic3r::GUI::Plater::priv::object_list_changed(), Slic3r::GUI::Plater::priv::on_process_completed(), Slic3r::GUI::Plater::reslice(), Slic3r::GUI::Plater::select_plate(), Slic3r::GUI::Plater::select_plate_by_hover_id(), and Slic3r::GUI::Plater::priv::set_current_panel().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
init()
void Slic3r::GUI::PartPlate::init () private
{
  m_locked = false;
  m_ready_for_slice = true;
  m_slice_result_valid = false;
  m_slice_percent = 0.0f;
  m_hover_id = -1;
  m_selected = false;
  //m_quadric = ::gluNewQuadric();
  //if (m_quadric != nullptr)
  //  ::gluQuadricDrawStyle(m_quadric, GLU_FILL);
  m_print_index = -1;
  m_print = nullptr;
  m_plate_name_vbo_id = 0;
}
References m_hover_id, m_locked, m_plate_name_vbo_id, m_print, m_print_index, m_ready_for_slice, m_selected, m_slice_percent, and m_slice_result_valid.
Referenced by PartPlate(), and PartPlate().
intersect_instance()
bool Slic3r::GUI::PartPlate::intersect_instance (int obj_id, int instance_id, BoundingBoxf3 * bounding_box = nullptr)
{
  bool result = false;
  if (!valid_instance(obj_id, instance_id))
  {
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(": plate_id %1%, invalid obj_id %2%, instance_id %3%") % m_plate_index % obj_id % instance_id;
    return false;
  }
  if (m_printable)
  {
    ModelObject* object = m_model->objects[obj_id];
    ModelInstance* instance = object->instances[instance_id];
    BoundingBoxf3 instance_box = bounding_box? *bounding_box: object->instance_convex_hull_bounding_box(instance_id);
        Vec3d up_point =
            m_bounding_box.max + Vec3d(Slic3r::BuildVolume::SceneEpsilon, Slic3r::BuildVolume::SceneEpsilon,
                                       m_origin.z() + m_height + Slic3r::BuildVolume::SceneEpsilon);
        Vec3d low_point =
            m_bounding_box.min + Vec3d(-Slic3r::BuildVolume::SceneEpsilon, -Slic3r::BuildVolume::SceneEpsilon,
                                       m_origin.z() - Slic3r::BuildVolume::SceneEpsilon);
    BoundingBoxf3 plate_box(low_point, up_point);
    result = plate_box.intersects(instance_box);
  }
  else
  {
    result = is_left_top_of(obj_id, instance_id);
  }
  return result;
}
References Slic3r::bounding_box(), error, Slic3r::BoundingBox3Base< PointClass >::intersects(), is_left_top_of(), m_bounding_box, m_height, m_model, m_origin, m_plate_index, m_printable, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::Model::objects, Slic3r::BuildVolume::SceneEpsilon, and valid_instance().
Referenced by Slic3r::GUI::PartPlateList::construct_objects_list_for_new_plate(), move_instances_to(), Slic3r::GUI::PartPlateList::notify_instance_update(), Slic3r::GUI::ArrangeJob::prepare_partplate(), and Slic3r::GUI::PartPlateList::reload_all_objects().
intersects()
bool Slic3r::GUI::PartPlate::intersects (const BoundingBoxf3 & bb) const
{
  // Allow the objects to protrude below the print bed
  BoundingBoxf3 print_volume(Vec3d(m_bounding_box.min(0), m_bounding_box.min(1), 0.0), Vec3d(m_bounding_box.max(0), m_bounding_box.max(1), 1e3));
  print_volume.min(2) = -1e10;
  print_volume.min(0) -= Slic3r::BuildVolume::BedEpsilon;
  print_volume.min(1) -= Slic3r::BuildVolume::BedEpsilon;
  print_volume.max(0) += Slic3r::BuildVolume::BedEpsilon;
  print_volume.max(1) += Slic3r::BuildVolume::BedEpsilon;
  return print_volume.intersects(bb);
}
References Slic3r::BuildVolume::BedEpsilon, Slic3r::BoundingBox3Base< PointClass >::intersects(), m_bounding_box, Slic3r::BoundingBoxBase< PointClass >::max, and Slic3r::BoundingBoxBase< PointClass >::min.
Referenced by Slic3r::GUI::PartPlateList::find_instance(), and Slic3r::GUI::Selection::paste_objects_from_clipboard().
is_all_instances_unprintable()
bool Slic3r::GUI::PartPlate::is_all_instances_unprintable ()
{
    bool result = true;
    for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it) {
        int obj_id      = it->first;
        int instance_id = it->second;
        if (obj_id >= m_model->objects.size()) continue;
        ModelObject *  object   = m_model->objects[obj_id];
        ModelInstance *instance = object->instances[instance_id];
        if ((instance->printable)) {
            result = false;
            break;
        }
    }
    return result;
}
References m_model, obj_to_instance_set, Slic3r::Model::objects, and Slic3r::ModelInstance::printable.
is_apply_result_invalid()
bool Slic3r::GUI::PartPlate::is_apply_result_invalid () const inline
    {
        return m_apply_invalid;
    }
References m_apply_invalid.
is_left_top_of()
bool Slic3r::GUI::PartPlate::is_left_top_of (int obj_id, int instance_id)
{
  bool result = false;
  if (!valid_instance(obj_id, instance_id))
  {
    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(": plate_id %1%, invalid obj_id %2%, instance_id %3%") % m_plate_index % obj_id % instance_id;
    return false;
  }
  ModelObject* object = m_model->objects[obj_id];
  ModelInstance* instance = object->instances[instance_id];
  std::pair<int, int> pair(obj_id, instance_id);
  BoundingBoxf3 instance_box = object->instance_convex_hull_bounding_box(instance_id);
  result = (m_origin.x() <= instance_box.min.x()) && (m_origin.y() >= instance_box.min.y());
  return result;
}
References error, m_model, m_origin, m_plate_index, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::Model::objects, and valid_instance().
Referenced by intersect_instance().
is_locked()
bool Slic3r::GUI::PartPlate::is_locked () const inline
{ return m_locked; }
References m_locked.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_locked(), Slic3r::GUI::PartPlateList::clear(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), and render_icons().
is_printable()
bool Slic3r::GUI::PartPlate::is_printable () const inline
{ return m_printable; }
References m_printable.
is_slice_result_ready_for_print()
bool Slic3r::GUI::PartPlate::is_slice_result_ready_for_print () const inline
    {
        bool result = m_slice_result_valid;
        if (result)
            result = m_gcode_result ? (!m_gcode_result->toolpath_outside) : false;// && !m_gcode_result->conflict_result.has_value()  gcode conflict can also print
        return result;
    }
References m_gcode_result, m_slice_result_valid, and Slic3r::GCodeProcessorResult::toolpath_outside.
Referenced by Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::MainFrame::can_export_gcode(), and Slic3r::GUI::MainFrame::get_enable_print_status().
is_slice_result_valid()
bool Slic3r::GUI::PartPlate::is_slice_result_valid () const inline
    {
        return m_slice_result_valid;
    }
References m_slice_result_valid.
Referenced by Slic3r::GUI::GLCanvas3D::_render_imgui_select_plate_toolbar(), Slic3r::GUI::Plater::apply_background_progress(), Slic3r::GUI::MainFrame::get_enable_print_status(), Slic3r::GUI::MainFrame::get_enable_slice_status(), get_gcode_filename(), Slic3r::GUI::GCodeViewer::load(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::priv::restart_background_process(), Slic3r::CLI::run(), Slic3r::GUI::Plater::select_plate(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::priv::set_current_panel(), Slic3r::BackgroundSlicingProcess::start(), and Slic3r::GUI::Plater::priv::update_background_process().
is_valid_gcode_file()
bool Slic3r::GUI::PartPlate::is_valid_gcode_file ()
{
  if (get_gcode_filename().empty())
    return false;
  boost::filesystem::path gcode_file(m_gcode_result->filename);
  if (!boost::filesystem::exists(gcode_file)) {
    BOOST_LOG_TRIVIAL(info) << "invalid gcode file, file is missing, file = " << m_gcode_result->filename;
    return false;
  }
  return true;
}
References empty(), Slic3r::GCodeProcessorResult::filename, get_gcode_filename(), and m_gcode_result.
Referenced by Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
load()
template<class Archive > void Slic3r::GUI::PartPlate::load (Archive & ar) inline
{
        std::vector<std::pair<int, int>>  objects_and_instances;
        std::vector<std::pair<int, int>>  instances_outside;
        ar(m_plate_index, m_name, m_print_index, m_origin, m_width, m_depth, m_height, m_locked, m_selected, m_ready_for_slice, m_slice_result_valid, m_apply_invalid, m_printable, m_tmp_gcode_path, objects_and_instances, instances_outside, m_config);
        for (std::vector<std::pair<int, int>>::iterator it = objects_and_instances.begin(); it != objects_and_instances.end(); ++it)
            obj_to_instance_set.insert(std::pair(it->first, it->second));
        for (std::vector<std::pair<int, int>>::iterator it = instances_outside.begin(); it != instances_outside.end(); ++it)
            instance_outside_set.insert(std::pair(it->first, it->second));
    }
References instance_outside_set, m_apply_invalid, m_config, m_depth, m_height, m_locked, m_name, m_origin, m_plate_index, m_print_index, m_printable, m_ready_for_slice, m_selected, m_slice_result_valid, m_tmp_gcode_path, m_width, and obj_to_instance_set.
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
load_gcode_from_file()
int Slic3r::GUI::PartPlate::load_gcode_from_file (const std::string & filename)
{
  int ret = 0;
  // process gcode
  DynamicPrintConfig full_config = wxGetApp().preset_bundle->full_config();
  full_config.apply(m_config, true);
  m_print->apply(*m_model, full_config);
  //BBS: need to apply two times, for after the first apply, the m_print got its object,
  //which will affect the config when new_full_config.normalize_fdm(used_filaments);
  m_print->apply(*m_model, full_config);
  // BBS: use backup path to save temp gcode
    // auto path = get_tmp_gcode_path();
    // if (boost::filesystem::exists(boost::filesystem::path(path))) {
    //  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": file %1% exists, delete it firstly") % filename.c_str();
    //  boost::nowide::remove(path.c_str());
    //}
    // std::error_code error = rename_file(filename, path);
    // if (error) {
    //  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("Failed to rename the output G-code file from %1% to %2%, error code %3%") % filename.c_str() % path.c_str() %
    //error.message();  return -1;
    //}
  if (boost::filesystem::exists(filename)) {
    assert(m_tmp_gcode_path.empty());
    m_tmp_gcode_path = filename;
    m_gcode_result->filename = filename;
    m_print->set_gcode_file_ready();
    update_slice_result_valid_state(true);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": found valid gcode file %1%") % filename.c_str();
  }
  else {
    BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": can not find gcode file %1%") % filename.c_str();
    ret = -1;
  }
  m_ready_for_slice = true;
  return ret;
}
References Slic3r::ConfigBase::apply(), Slic3r::Print::apply(), Slic3r::GCodeProcessorResult::filename, m_config, m_gcode_result, m_model, m_print, m_ready_for_slice, m_tmp_gcode_path, Slic3r::Print::set_gcode_file_ready(), and update_slice_result_valid_state().
load_pattern_box_data()
int Slic3r::GUI::PartPlate::load_pattern_box_data (std::string filename)
{
    try {
        nlohmann::json j;
        boost::nowide::ifstream ifs(filename);
        ifs >> j;
        PlateBBoxData bbox_data;
        bbox_data.from_json(j);
        cali_bboxes_data = bbox_data;
        return 0;
    }
    catch(std::exception &ex) {
        BOOST_LOG_TRIVIAL(trace) << boost::format("catch an exception %1%")%ex.what();
        return -1;
    }
}
References cali_bboxes_data, Slic3r::PlateBBoxData::from_json(), and Slic3r::trace().
load_pattern_thumbnail_data()
int Slic3r::GUI::PartPlate::load_pattern_thumbnail_data (std::string filename)
{
  /*bool result = true;
  wxImage img;
  result = load_image(filename, img);
  if (result) {
    cali_thumbnail_data.set(img.GetWidth(), img.GetHeight());
    for (int i = 0; i < img.GetWidth() * img.GetHeight(); i++) {
      memcpy(&cali_thumbnail_data.pixels[4 * i], (unsigned char*)(img.GetData() + 3 * i), 3);
      if (img.HasAlpha()) {
        cali_thumbnail_data.pixels[4 * i + 3] = *(unsigned char*)(img.GetAlpha() + i);
      }
    }
  }
  else {
    return -1;
  }*/
  return 0;
}
load_render_colors()
void Slic3r::GUI::PartPlate::load_render_colors () static
{
  RenderColor::colors[RenderCol_Plate_Selected] = IMColor(SELECT_COLOR);
  RenderColor::colors[RenderCol_Plate_Unselected] = IMColor(UNSELECT_COLOR);
  RenderColor::colors[RenderCol_Plate_Default] = IMColor(DEFAULT_COLOR);
  RenderColor::colors[RenderCol_Plate_Line_Top] = IMColor(LINE_TOP_COLOR);
  RenderColor::colors[RenderCol_Plate_Line_Bottom] = IMColor(LINE_BOTTOM_COLOR);
}
References Slic3r::RenderColor::colors, DEFAULT_COLOR, Slic3r::IMColor(), LINE_BOTTOM_COLOR, LINE_TOP_COLOR, RenderCol_Plate_Default, RenderCol_Plate_Line_Bottom, RenderCol_Plate_Line_Top, RenderCol_Plate_Selected, RenderCol_Plate_Unselected, SELECT_COLOR, and UNSELECT_COLOR.
Referenced by Slic3r::GUI::GLCanvas3D::init().
load_thumbnail_data()
int Slic3r::GUI::PartPlate::load_thumbnail_data (std::string filename, ThumbnailData & thumb_data)
{
  bool result = true;
  wxImage img;
  if (boost::algorithm::iends_with(filename, ".png")) {
    result = img.LoadFile(wxString::FromUTF8(filename.c_str()), wxBITMAP_TYPE_PNG);
    img = img.Mirror(false);
  }
  if (result) {
    thumb_data.set(img.GetWidth(), img.GetHeight());
    for (int i = 0; i < img.GetWidth() * img.GetHeight(); i++) {
      memcpy(&thumb_data.pixels[4 * i], (unsigned char*)(img.GetData() + 3 * i), 3);
      if (img.HasAlpha()) {
        thumb_data.pixels[4 * i + 3] = *(unsigned char*)(img.GetAlpha() + i);
      }
    }
  } else {
    return -1;
  }
  return 0;
}
References memcpy, Slic3r::ThumbnailData::pixels, and Slic3r::ThumbnailData::set().
lock()
void Slic3r::GUI::PartPlate::lock (bool state) inline
{ m_locked = state; }
References m_locked.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_locked(), and Slic3r::GUI::PartPlateList::lock_plate().
move_instances_to()
void Slic3r::GUI::PartPlate::move_instances_to (PartPlate & left_plate, PartPlate & right_plate, BoundingBoxf3 * bounding_box = nullptr)
{
  for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it)
  {
    int obj_id = it->first;
    int instance_id = it->second;
    if (left_plate.intersect_instance(obj_id, instance_id, bounding_box))
      left_plate.add_instance(obj_id, instance_id, false, bounding_box);
    else
      right_plate.add_instance(obj_id, instance_id, false, bounding_box);
  }
  return;
}
References add_instance(), Slic3r::bounding_box(), intersect_instance(), and obj_to_instance_set.
Referenced by Slic3r::GUI::PartPlateList::delete_plate().
on_render_for_picking()
void Slic3r::GUI::PartPlate::on_render_for_picking () const private
{
  //glsafe(::glDisable(GL_DEPTH_TEST));
  int hover_id = 0;
  std::array<float, 4> color = picking_color_component(hover_id);
  m_grabber_color[0] = color[0];
  m_grabber_color[1] = color[1];
  m_grabber_color[2] = color[2];
  m_grabber_color[3] = color[3];
  //render_grabber(m_grabber_color, false);
  render_rectangle_for_picking(m_triangles, m_grabber_color);
  hover_id = 1;
  color = picking_color_component(hover_id);
  m_grabber_color[0] = color[0];
  m_grabber_color[1] = color[1];
  m_grabber_color[2] = color[2];
  m_grabber_color[3] = color[3];
  //render_left_arrow(m_grabber_color, false);
  render_rectangle_for_picking(m_del_icon, m_grabber_color);
  hover_id = 2;
  color = picking_color_component(hover_id);
  m_grabber_color[0] = color[0];
  m_grabber_color[1] = color[1];
  m_grabber_color[2] = color[2];
  m_grabber_color[3] = color[3];
  render_rectangle_for_picking(m_orient_icon, m_grabber_color);
    hover_id = 3;
  color = picking_color_component(hover_id);
  m_grabber_color[0] = color[0];
  m_grabber_color[1] = color[1];
  m_grabber_color[2] = color[2];
  m_grabber_color[3] = color[3];
  render_rectangle_for_picking(m_arrange_icon, m_grabber_color);
  hover_id = 4;
  color = picking_color_component(hover_id);
  m_grabber_color[0] = color[0];
  m_grabber_color[1] = color[1];
  m_grabber_color[2] = color[2];
  m_grabber_color[3] = color[3];
  //render_right_arrow(m_grabber_color, false);
  render_rectangle_for_picking(m_lock_icon, m_grabber_color);
  hover_id = 5;
  color = picking_color_component(hover_id);
  m_grabber_color[0] = color[0];
  m_grabber_color[1] = color[1];
  m_grabber_color[2] = color[2];
  m_grabber_color[3] = color[3];
    if (m_partplate_list->render_plate_settings)
        render_rectangle_for_picking(m_plate_settings_icon, m_grabber_color);
}
References m_arrange_icon, m_del_icon, m_grabber_color, m_lock_icon, m_orient_icon, m_partplate_list, m_plate_settings_icon, m_triangles, picking_color_component(), Slic3r::GUI::PartPlateList::render_plate_settings, and render_rectangle_for_picking().
Referenced by render_for_picking().
operator<()
bool Slic3r::GUI::PartPlate::operator< (PartPlate & plate) const
{
  int index = plate.get_index();
  return (this->m_plate_index < index);
}
References get_index(), and m_plate_index.
picking_color_component()
std::array< float, 4 > Slic3r::GUI::PartPlate::picking_color_component (int idx) const private
{
  static const float INV_255 = 1.0f / 255.0f;
  unsigned int id = PLATE_BASE_ID - this->m_plate_index * GRABBER_COUNT - idx;
  return std::array<float, 4> {
    float((id >> 0) & 0xff)* INV_255, // red
      float((id >> 8) & 0xff)* INV_255, // greeen
      float((id >> 16) & 0xff)* INV_255, // blue
      float(picking_checksum_alpha_channel(id & 0xff, (id >> 8) & 0xff, (id >> 16) & 0xff))* INV_255
  };
}
References GRABBER_COUNT, m_plate_index, Slic3r::GUI::picking_checksum_alpha_channel(), and PLATE_BASE_ID.
Referenced by on_render_for_picking().
print()
void Slic3r::GUI::PartPlate::print () const
{
  unsigned int count=0;
  BOOST_LOG_TRIVIAL(trace) << __FUNCTION__ << boost::format(": plate index %1%, pointer %2%, print_index %3% print pointer %4%") % m_plate_index % this % m_print_index % m_print;
  BOOST_LOG_TRIVIAL(trace) << boost::format("\t origin {%1%,%2%,%3%}, width %4%,  depth %5%, height %6%") % m_origin.x() % m_origin.y() % m_origin.z() % m_width % m_depth % m_height;
  BOOST_LOG_TRIVIAL(trace) << boost::format("\t m_printable %1%, m_locked %2%, m_ready_for_slice %3%, m_slice_result_valid %4%,  m_tmp_gcode_path %5%, set size %6%")\
    % m_printable % m_locked % m_ready_for_slice % m_slice_result_valid % m_tmp_gcode_path % obj_to_instance_set.size();
  /*for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it) {
    int obj_id = it->first;
    int instance_id = it->second;
    BOOST_LOG_TRIVIAL(trace) << boost::format("\t the %1%th instance, obj_id %2%, instance id %3%") % count++ % obj_id % instance_id;
  }*/
  BOOST_LOG_TRIVIAL(trace) << boost::format("excluded instance set size %1%")%instance_outside_set.size();
  /*for (std::set<std::pair<int, int>>::iterator it = instance_outside_set.begin(); it != instance_outside_set.end(); ++it) {
    int obj_id = it->first;
    int instance_id = it->second;
    BOOST_LOG_TRIVIAL(trace) << boost::format("\t obj_id %1%, instance id %2%") % obj_id % instance_id;
  }*/
  return;
}
References count, instance_outside_set, m_depth, m_height, m_locked, m_origin, m_plate_index, m_print, m_print_index, m_printable, m_ready_for_slice, m_slice_result_valid, m_tmp_gcode_path, m_width, obj_to_instance_set, and Slic3r::trace().
Referenced by get_print(), Slic3r::GUI::PartPlateList::print(), and set_print().
printable_instance_size()
int Slic3r::GUI::PartPlate::printable_instance_size ()
{
    int size = 0;
    for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it) {
        int obj_id      = it->first;
        int instance_id = it->second;
        if (obj_id >= m_model->objects.size())
      continue;
        ModelObject *  object   = m_model->objects[obj_id];
        ModelInstance *instance = object->instances[instance_id];
        if ((instance->printable) && (instance_outside_set.find(std::pair(obj_id, instance_id)) == instance_outside_set.end())) {
            size++;
        }
    }
    return size;
}
References instance_outside_set, m_model, obj_to_instance_set, Slic3r::Model::objects, Slic3r::ModelInstance::printable, and size.
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene().
release_opengl_resource()
void Slic3r::GUI::PartPlate::release_opengl_resource () private
{
  if (m_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_vbo_id));
    m_vbo_id = 0;
  }
  if (m_del_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_del_vbo_id));
    m_del_vbo_id = 0;
  }
    if (m_orient_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_orient_vbo_id));
    m_orient_vbo_id = 0;
  }
  if (m_arrange_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_arrange_vbo_id));
    m_arrange_vbo_id = 0;
  }
  if (m_lock_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_lock_vbo_id));
    m_lock_vbo_id = 0;
  }
  if (m_plate_settings_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_plate_settings_vbo_id));
    m_plate_settings_vbo_id = 0;
  }
  if (m_plate_idx_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_plate_idx_vbo_id));
    m_plate_idx_vbo_id = 0;
  }
  if (m_plate_name_vbo_id > 0) {
    glsafe(::glDeleteBuffers(1, &m_plate_name_vbo_id));
    m_plate_name_vbo_id = 0;
  }
}
References glsafe, m_arrange_vbo_id, m_del_vbo_id, m_lock_vbo_id, m_orient_vbo_id, m_plate_idx_vbo_id, m_plate_name_vbo_id, m_plate_settings_vbo_id, and m_vbo_id.
Referenced by ~PartPlate(), and set_shape().
remove_instance()
int Slic3r::GUI::PartPlate::remove_instance (int obj_id, int instance_id)
{
  bool result;
  std::set<std::pair<int, int>>::iterator it;
  it = obj_to_instance_set.find(std::pair(obj_id, instance_id));
  if (it != obj_to_instance_set.end()) {
    obj_to_instance_set.erase(it);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":plate_id %1%, found obj_id %2%, instance_id %3%") % m_plate_index % obj_id % instance_id;
    result = 0;
  }
  else {
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": plate_id %1%, can not find obj_id %2%, instance_id %3%") % m_plate_index % obj_id % instance_id;
    result = -1;
    return result;
  }
  it = instance_outside_set.find(std::pair(obj_id, instance_id));
  if (it != instance_outside_set.end()) {
    instance_outside_set.erase(it);
  }
  if (!m_ready_for_slice)
    update_states();
  return result;
}
References instance_outside_set, m_plate_index, m_ready_for_slice, obj_to_instance_set, and update_states().
Referenced by Slic3r::GUI::PartPlateList::add_to_plate(), Slic3r::GUI::PartPlateList::notify_instance_removed(), and Slic3r::GUI::PartPlateList::notify_instance_update().
render()
void Slic3r::GUI::PartPlate::render (bool bottom, bool only_body = false, bool force_background_color = false, HeightLimitMode mode = HEIGHT_LIMIT_NONE, int hover_id = -1, bool render_cali = false)
{
  glsafe(::glEnable(GL_DEPTH_TEST));
  glsafe(::glEnable(GL_BLEND));
  glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
  glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
  if (!bottom) {
    // draw background
    render_background(force_background_color);
    render_exclude_area(force_background_color);
  }
  render_grid(bottom);
  if (!bottom && m_selected && !force_background_color) {
    if (m_partplate_list)
           render_logo(bottom, m_partplate_list->render_cali_logo && render_cali);
    else
       render_logo(bottom);
  }
  render_height_limit(mode);
  render_icons(bottom, only_body, hover_id);
  if (!force_background_color){
    render_only_numbers(bottom);
  }
  glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
  glsafe(::glDisable(GL_BLEND));
  //if (with_label) {
  //  render_label(canvas);
  //}
  glsafe(::glDisable(GL_DEPTH_TEST));
}
References glsafe, m_partplate_list, m_selected, render_background(), Slic3r::GUI::PartPlateList::render_cali_logo, render_exclude_area(), render_grid(), render_height_limit(), render_icons(), render_logo(), and render_only_numbers().
render_arrows()
void Slic3r::GUI::PartPlate::render_arrows (const float * render_color, bool use_lighting) const private
{
#if 0
  if (m_quadric == nullptr)
    return;
  double radius = m_grabber_box.size().y() * 0.5f;
  double height = radius * 2.0f;
  double position = m_grabber_box.size().x() * 0.8f;
  if (use_lighting)
    glsafe(::glEnable(GL_LIGHTING));
  glsafe(::glColor4fv(render_color));
  glsafe(::glPushMatrix());
  glsafe(::glTranslated(m_grabber_box.center().x(), m_grabber_box.center().y(), m_grabber_box.center().z()));
  glsafe(::glRotated(90.0, 0.0, 1.0, 0.0));
  glsafe(::glTranslated(0.0, 0.0, position));
  ::gluQuadricOrientation(m_quadric, GLU_OUTSIDE);
  ::gluCylinder(m_quadric, 0.9 * radius, 0.0, height, 36, 1);
  ::gluQuadricOrientation(m_quadric, GLU_INSIDE);
  ::gluDisk(m_quadric, 0.0, 0.9 * radius, 36, 1);
  glsafe(::glPopMatrix());
  glsafe(::glPushMatrix());
  glsafe(::glTranslated(m_grabber_box.center().x(), m_grabber_box.center().y(), m_grabber_box.center().z()));
  glsafe(::glRotated(-90.0, 0.0, 1.0, 0.0));
  glsafe(::glTranslated(0.0, 0.0, position));
  ::gluQuadricOrientation(m_quadric, GLU_OUTSIDE);
  ::gluCylinder(m_quadric, 0.9 * radius, 0.0, height, 36, 1);
  ::gluQuadricOrientation(m_quadric, GLU_INSIDE);
  ::gluDisk(m_quadric, 0.0, 0.9 * radius, 36, 1);
  glsafe(::glPopMatrix());
  if (use_lighting)
    glsafe(::glDisable(GL_LIGHTING));
#endif
}
References Slic3r::BoundingBox3Base< PointClass >::center(), glsafe, m_grabber_box, m_quadric, and Slic3r::BoundingBox3Base< PointClass >::size().
render_background()
void Slic3r::GUI::PartPlate::render_background (bool force_default_color = false) const private
{
  unsigned int triangles_vcount = m_triangles.get_vertices_count();
  //return directly for current plate
  if (m_selected && !force_default_color) return;
  // draw background
  glsafe(::glDepthMask(GL_FALSE));
  if (!force_default_color) {
    if (m_selected) {
      glsafe(::glColor4fv(PartPlate::SELECT_COLOR.data()));
    }
    else {
      glsafe(m_partplate_list->m_is_dark ? ::glColor4fv(PartPlate::UNSELECT_DARK_COLOR.data()) : ::glColor4fv(PartPlate::UNSELECT_COLOR.data()));
    }
  }
  else {
    glsafe(::glColor4fv(PartPlate::DEFAULT_COLOR.data()));
  }
  glsafe(::glNormal3d(0.0f, 0.0f, 1.0f));
  glsafe(::glVertexPointer(3, GL_FLOAT, m_triangles.get_vertex_data_size(), (GLvoid*)m_triangles.get_vertices_data()));
  glsafe(::glDrawArrays(GL_TRIANGLES, 0, (GLsizei)triangles_vcount));
  glsafe(::glDepthMask(GL_TRUE));
}
References DEFAULT_COLOR, Slic3r::GUI::GeometryBuffer::get_vertex_data_size(), Slic3r::GUI::GeometryBuffer::get_vertices_count(), Slic3r::GUI::GeometryBuffer::get_vertices_data(), GL_FALSE, GL_TRIANGLES, GL_TRUE, glsafe, Slic3r::GUI::PartPlateList::m_is_dark, m_partplate_list, m_selected, m_triangles, SELECT_COLOR, UNSELECT_COLOR, and UNSELECT_DARK_COLOR.
Referenced by render().
render_exclude_area()
void Slic3r::GUI::PartPlate::render_exclude_area (bool force_default_color) const private
{
  if (force_default_color) //for thumbnail case
    return;
  unsigned int triangles_vcount = m_exclude_triangles.get_vertices_count();
  std::array<float, 4> select_color{ 0.765f, 0.7686f, 0.7686f, 1.0f };
  std::array<float, 4> unselect_color{ 0.9f, 0.9f, 0.9f, 1.0f };
  std::array<float, 4> default_color{ 0.9f, 0.9f, 0.9f, 1.0f };
  // draw exclude area
  glsafe(::glDepthMask(GL_FALSE));
  if (m_selected) {
    glsafe(::glColor4fv(select_color.data()));
  }
  else {
    glsafe(::glColor4fv(unselect_color.data()));
  }
  glsafe(::glNormal3d(0.0f, 0.0f, 1.0f));
  glsafe(::glVertexPointer(3, GL_FLOAT, m_exclude_triangles.get_vertex_data_size(), (GLvoid*)m_exclude_triangles.get_vertices_data()));
  glsafe(::glDrawArrays(GL_TRIANGLES, 0, (GLsizei)triangles_vcount));
  glsafe(::glDepthMask(GL_TRUE));
}
References Slic3r::GUI::GeometryBuffer::get_vertex_data_size(), Slic3r::GUI::GeometryBuffer::get_vertices_count(), Slic3r::GUI::GeometryBuffer::get_vertices_data(), GL_FALSE, GL_TRIANGLES, GL_TRUE, glsafe, m_exclude_triangles, and m_selected.
Referenced by render().
render_face()
void Slic3r::GUI::PartPlate::render_face (float x_size, float y_size) const private
{
  ::glBegin(GL_TRIANGLES);
  ::glNormal3f(0.0f, 0.0f, 1.0f);
  ::glVertex3f(-(GLfloat)x_size, -(GLfloat)y_size, 0.0f);
  ::glVertex3f((GLfloat)x_size, -(GLfloat)y_size, 0.0f);
  ::glVertex3f((GLfloat)x_size, (GLfloat)y_size, 0.0f);
  ::glVertex3f((GLfloat)x_size, (GLfloat)y_size, 0.0f);
  ::glVertex3f(-(GLfloat)x_size, (GLfloat)y_size, 0.0f);
  ::glVertex3f(-(GLfloat)x_size, -(GLfloat)y_size, 0.0f);
  glsafe(::glEnd());
}
References GL_TRIANGLES, and glsafe.
Referenced by render_grabber().
render_for_picking()
void Slic3r::GUI::PartPlate::render_for_picking () const inline
{ on_render_for_picking(); }
References on_render_for_picking().
render_grabber()
void Slic3r::GUI::PartPlate::render_grabber (const float * render_color, bool use_lighting) const private
{
  BoundingBoxf3* bounding_box = const_cast<BoundingBoxf3*>(&m_bounding_box);
  const Vec3d& center = m_grabber_box.center();
  if (use_lighting)
    glsafe(::glEnable(GL_LIGHTING));
  glsafe(::glColor4fv(render_color));
  glsafe(::glPushMatrix());
  glsafe(::glTranslated(center(0), center(1), center(2)));
  Vec3d angles(Vec3d::Zero());
  glsafe(::glRotated(Geometry::rad2deg(angles(2)), 0.0, 0.0, 1.0));
  glsafe(::glRotated(Geometry::rad2deg(angles(1)), 0.0, 1.0, 0.0));
  glsafe(::glRotated(Geometry::rad2deg(angles(0)), 1.0, 0.0, 0.0));
  float half_x = bounding_box->size().x() * GRABBER_X_FACTOR;
  float half_y = bounding_box->size().y() * GRABBER_Y_FACTOR;
  float half_z = GRABBER_Z_VALUE;
  // face min x
  glsafe(::glPushMatrix());
  glsafe(::glTranslatef(-(GLfloat)half_x, 0, 0.0f));
  glsafe(::glRotatef(-90.0f, 0.0f, 1.0f, 0.0f));
  render_face(half_z, half_y);
  glsafe(::glPopMatrix());
  // face max x
  glsafe(::glPushMatrix());
  glsafe(::glTranslatef((GLfloat)half_x, 0, 0.0f));
  glsafe(::glRotatef(90.0f, 0.0f, 1.0f, 0.0f));
  render_face(half_z, half_y);
  glsafe(::glPopMatrix());
  // face min y
  glsafe(::glPushMatrix());
  glsafe(::glTranslatef(0.0f, -(GLfloat)half_y, 0.0f));
  glsafe(::glRotatef(90.0f, 1.0f, 0.0f, 0.0f));
  render_face(half_x, half_z);
  glsafe(::glPopMatrix());
  // face max y
  glsafe(::glPushMatrix());
  glsafe(::glTranslatef(0.0f, (GLfloat)half_y, 0.0f));
  glsafe(::glRotatef(-90.0f, 1.0f, 0.0f, 0.0f));
  render_face(half_x, half_z);
  glsafe(::glPopMatrix());
  // face min z
  glsafe(::glPushMatrix());
  glsafe(::glTranslatef(0.0f, 0.0f, -(GLfloat)half_z));
  glsafe(::glRotatef(180.0f, 1.0f, 0.0f, 0.0f));
  render_face(half_x, half_y);
  glsafe(::glPopMatrix());
  // face max z
  glsafe(::glPushMatrix());
  glsafe(::glTranslatef(0.0f, 0.0f, (GLfloat)half_z));
  render_face(half_x, half_y);
  glsafe(::glPopMatrix());
  glsafe(::glPopMatrix());
  if (use_lighting)
    glsafe(::glDisable(GL_LIGHTING));
}
References Slic3r::bounding_box(), Slic3r::BoundingBox3Base< PointClass >::center(), glsafe, GRABBER_X_FACTOR, GRABBER_Y_FACTOR, GRABBER_Z_VALUE, m_bounding_box, m_grabber_box, Slic3r::Geometry::rad2deg(), render_face(), and Slic3r::BoundingBox3Base< PointClass >::size().
render_grid()
void Slic3r::GUI::PartPlate::render_grid (bool bottom) const private
{
  //glsafe(::glEnable(GL_MULTISAMPLE));
  // draw grid
  glsafe(::glLineWidth(1.0f * m_scale_factor));
  if (bottom)
    glsafe(::glColor4fv(LINE_BOTTOM_COLOR.data()));
  else {
    if (m_selected)
      glsafe(m_partplate_list->m_is_dark ? ::glColor4fv(LINE_TOP_SEL_DARK_COLOR.data()) : ::glColor4fv(LINE_TOP_SEL_COLOR.data()));
    else
      glsafe(m_partplate_list->m_is_dark ? ::glColor4fv(LINE_TOP_DARK_COLOR.data()) : ::glColor4fv(LINE_TOP_COLOR.data()));
  }
  glsafe(::glVertexPointer(3, GL_FLOAT, m_gridlines.get_vertex_data_size(), (GLvoid*)m_gridlines.get_vertices_data()));
  glsafe(::glDrawArrays(GL_LINES, 0, (GLsizei)m_gridlines.get_vertices_count()));
  glsafe(::glLineWidth(2.0f * m_scale_factor));
  glsafe(::glVertexPointer(3, GL_FLOAT, m_gridlines_bolder.get_vertex_data_size(), (GLvoid*)m_gridlines_bolder.get_vertices_data()));
  glsafe(::glDrawArrays(GL_LINES, 0, (GLsizei)m_gridlines_bolder.get_vertices_count()));
}
References Slic3r::GUI::GeometryBuffer::get_vertex_data_size(), Slic3r::GUI::GeometryBuffer::get_vertices_count(), Slic3r::GUI::GeometryBuffer::get_vertices_data(), glsafe, LINE_BOTTOM_COLOR, LINE_TOP_COLOR, LINE_TOP_DARK_COLOR, LINE_TOP_SEL_COLOR, LINE_TOP_SEL_DARK_COLOR, m_gridlines, m_gridlines_bolder, Slic3r::GUI::PartPlateList::m_is_dark, m_partplate_list, m_scale_factor, and m_selected.
Referenced by render().
render_height_limit()
void Slic3r::GUI::PartPlate::render_height_limit (PartPlate::HeightLimitMode mode = HEIGHT_LIMIT_BOTH) const private
{
  if (m_print && m_print->config().print_sequence == PrintSequence::ByObject && mode != HEIGHT_LIMIT_NONE)
  {
    // draw lower limit
    glsafe(::glLineWidth(3.0f * m_scale_factor));
    glsafe(::glColor4fv(HEIGHT_LIMIT_BOTTOM_COLOR.data()));
    glsafe(::glVertexPointer(3, GL_FLOAT, m_height_limit_common.get_vertex_data_size(), (GLvoid*)m_height_limit_common.get_vertices_data()));
    glsafe(::glDrawArrays(GL_LINES, 0, (GLsizei)m_height_limit_common.get_vertices_count()));
    if ((mode == HEIGHT_LIMIT_BOTTOM) || (mode == HEIGHT_LIMIT_BOTH)) {
      glsafe(::glLineWidth(3.0f * m_scale_factor));
      glsafe(::glColor4fv(HEIGHT_LIMIT_BOTTOM_COLOR.data()));
      glsafe(::glVertexPointer(3, GL_FLOAT, m_height_limit_bottom.get_vertex_data_size(), (GLvoid*)m_height_limit_bottom.get_vertices_data()));
      glsafe(::glDrawArrays(GL_LINES, 0, (GLsizei)m_height_limit_bottom.get_vertices_count()));
    }
    // draw upper limit
    if ((mode == HEIGHT_LIMIT_TOP) || (mode == HEIGHT_LIMIT_BOTH)){
      glsafe(::glLineWidth(3.0f * m_scale_factor));
      glsafe(::glColor4fv(HEIGHT_LIMIT_TOP_COLOR.data()));
      glsafe(::glVertexPointer(3, GL_FLOAT, m_height_limit_top.get_vertex_data_size(), (GLvoid*)m_height_limit_top.get_vertices_data()));
      glsafe(::glDrawArrays(GL_LINES, 0, (GLsizei)m_height_limit_top.get_vertices_count()));
    }
  }
}
References Slic3r::ByObject, Slic3r::Print::config(), Slic3r::GUI::GeometryBuffer::get_vertex_data_size(), Slic3r::GUI::GeometryBuffer::get_vertices_count(), Slic3r::GUI::GeometryBuffer::get_vertices_data(), glsafe, HEIGHT_LIMIT_BOTH, HEIGHT_LIMIT_BOTTOM, HEIGHT_LIMIT_BOTTOM_COLOR, HEIGHT_LIMIT_NONE, HEIGHT_LIMIT_TOP, HEIGHT_LIMIT_TOP_COLOR, m_height_limit_bottom, m_height_limit_common, m_height_limit_top, m_print, and m_scale_factor.
Referenced by render().
render_icon_texture()
void Slic3r::GUI::PartPlate::render_icon_texture (int position_id, int tex_coords_id, const GeometryBuffer & buffer, GLTexture & texture, unsigned int & vbo_id) const private
{
  if (vbo_id == 0) {
    glsafe(::glGenBuffers(1, &vbo_id));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, vbo_id));
    glsafe(::glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)buffer.get_vertices_data_size(), (const GLvoid*)buffer.get_vertices_data(), GL_STATIC_DRAW));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
  }
  unsigned int stride = buffer.get_vertex_data_size();
  GLuint tex_id = (GLuint)texture.get_id();
  glsafe(::glBindTexture(GL_TEXTURE_2D, tex_id));
  glsafe(::glBindBuffer(GL_ARRAY_BUFFER, vbo_id));
  if (position_id != -1)
    glsafe(::glVertexAttribPointer(position_id, 3, GL_FLOAT, GL_FALSE, stride, (GLvoid*)(intptr_t)buffer.get_position_offset()));
  if (tex_coords_id != -1)
    glsafe(::glVertexAttribPointer(tex_coords_id, 2, GL_FLOAT, GL_FALSE, stride, (GLvoid*)(intptr_t)buffer.get_tex_coords_offset()));
  glsafe(::glDrawArrays(GL_TRIANGLES, 0, (GLsizei)buffer.get_vertices_count()));
  glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
  glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
}
References buffer, Slic3r::GUI::GLTexture::get_id(), GL_FALSE, GL_TRIANGLES, and glsafe.
Referenced by render_icons(), and render_only_numbers().
render_icons()
void Slic3r::GUI::PartPlate::render_icons (bool bottom, bool only_name = false, int hover_id = -1) private
{
  GLShaderProgram* shader = wxGetApp().get_shader("printbed");
  if (shader != nullptr) {
    shader->start_using();
    shader->set_uniform("transparent_background", bottom);
    //shader->set_uniform("svg_source", boost::algorithm::iends_with(m_partplate_list->m_del_texture.get_source(), ".svg"));
    shader->set_uniform("svg_source", 0);
        //if (bottom)
        //    glsafe(::glFrontFace(GL_CW));
        glsafe(::glDepthMask(GL_FALSE));
        GLint position_id = shader->get_attrib_location("v_position");
        GLint tex_coords_id = shader->get_attrib_location("v_tex_coords");
        if (position_id != -1) {
            glsafe(::glEnableVertexAttribArray(position_id));
        }
        if (tex_coords_id != -1) {
            glsafe(::glEnableVertexAttribArray(tex_coords_id));
        }
        if (!only_name) {
            if (hover_id == 1)
                render_icon_texture(position_id, tex_coords_id, m_del_icon, m_partplate_list->m_del_hovered_texture,
                                    m_del_vbo_id);
            else
                render_icon_texture(position_id, tex_coords_id, m_del_icon, m_partplate_list->m_del_texture,
                                    m_del_vbo_id);
            if (hover_id == 2)
                render_icon_texture(position_id, tex_coords_id, m_orient_icon,
                                    m_partplate_list->m_orient_hovered_texture, m_orient_vbo_id);
            else
                render_icon_texture(position_id, tex_coords_id, m_orient_icon, m_partplate_list->m_orient_texture,
                                    m_orient_vbo_id);
            if (hover_id == 3)
                render_icon_texture(position_id, tex_coords_id, m_arrange_icon,
                                    m_partplate_list->m_arrange_hovered_texture, m_arrange_vbo_id);
            else
                render_icon_texture(position_id, tex_coords_id, m_arrange_icon, m_partplate_list->m_arrange_texture,
                                    m_arrange_vbo_id);
            if (hover_id == 4) {
                if (this->is_locked())
                    render_icon_texture(position_id, tex_coords_id, m_lock_icon,
                                        m_partplate_list->m_locked_hovered_texture, m_lock_vbo_id);
                else
                    render_icon_texture(position_id, tex_coords_id, m_lock_icon,
                                        m_partplate_list->m_lockopen_hovered_texture, m_lock_vbo_id);
            } else {
                if (this->is_locked())
                    render_icon_texture(position_id, tex_coords_id, m_lock_icon, m_partplate_list->m_locked_texture,
                                        m_lock_vbo_id);
                else
                    render_icon_texture(position_id, tex_coords_id, m_lock_icon, m_partplate_list->m_lockopen_texture,
                                        m_lock_vbo_id);
            }
            if (m_partplate_list->render_plate_settings) {
                if (hover_id == 5) {
                    if (get_bed_type() == BedType::btDefault && get_print_seq() == PrintSequence::ByDefault)
                      render_icon_texture(position_id, tex_coords_id, m_plate_settings_icon,
                                          m_partplate_list->m_plate_settings_hovered_texture, m_plate_settings_vbo_id);
                    else
                      render_icon_texture(position_id, tex_coords_id, m_plate_settings_icon,
                                          m_partplate_list->m_plate_settings_changed_hovered_texture,
                                          m_plate_settings_vbo_id);
                } else {
                    if (get_bed_type() == BedType::btDefault && get_print_seq() == PrintSequence::ByDefault)
                      render_icon_texture(position_id, tex_coords_id, m_plate_settings_icon,
                                          m_partplate_list->m_plate_settings_texture, m_plate_settings_vbo_id);
                    else
                      render_icon_texture(position_id, tex_coords_id, m_plate_settings_icon,
                                          m_partplate_list->m_plate_settings_changed_texture, m_plate_settings_vbo_id);
                }
            }
            if (m_plate_index >= 0 && m_plate_index < MAX_PLATE_COUNT) {
                render_icon_texture(position_id, tex_coords_id, m_plate_idx_icon,
                                    m_partplate_list->m_idx_textures[m_plate_index], m_plate_idx_vbo_id);
            }
        }
    render_plate_name_texture(position_id, tex_coords_id);
        if (tex_coords_id != -1)
            glsafe(::glDisableVertexAttribArray(tex_coords_id));
        if (position_id != -1)
            glsafe(::glDisableVertexAttribArray(position_id));
        //if (bottom)
        //    glsafe(::glFrontFace(GL_CCW));
        glsafe(::glDepthMask(GL_TRUE));
        shader->stop_using();
    }
}
References Slic3r::btDefault, Slic3r::ByDefault, Slic3r::GLShaderProgram::get_attrib_location(), get_bed_type(), get_print_seq(), GL_FALSE, GL_TRUE, glsafe, is_locked(), Slic3r::GUI::PartPlateList::m_arrange_hovered_texture, m_arrange_icon, Slic3r::GUI::PartPlateList::m_arrange_texture, m_arrange_vbo_id, Slic3r::GUI::PartPlateList::m_del_hovered_texture, m_del_icon, Slic3r::GUI::PartPlateList::m_del_texture, m_del_vbo_id, Slic3r::GUI::PartPlateList::m_idx_textures, m_lock_icon, m_lock_vbo_id, Slic3r::GUI::PartPlateList::m_locked_hovered_texture, Slic3r::GUI::PartPlateList::m_locked_texture, Slic3r::GUI::PartPlateList::m_lockopen_hovered_texture, Slic3r::GUI::PartPlateList::m_lockopen_texture, Slic3r::GUI::PartPlateList::m_orient_hovered_texture, m_orient_icon, Slic3r::GUI::PartPlateList::m_orient_texture, m_orient_vbo_id, m_partplate_list, m_plate_idx_icon, m_plate_idx_vbo_id, m_plate_index, Slic3r::GUI::PartPlateList::m_plate_settings_changed_hovered_texture, Slic3r::GUI::PartPlateList::m_plate_settings_changed_texture, Slic3r::GUI::PartPlateList::m_plate_settings_hovered_texture, m_plate_settings_icon, Slic3r::GUI::PartPlateList::m_plate_settings_texture, m_plate_settings_vbo_id, MAX_PLATE_COUNT, render_icon_texture(), render_plate_name_texture(), Slic3r::GUI::PartPlateList::render_plate_settings, Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by render().
render_label()
void Slic3r::GUI::PartPlate::render_label (GLCanvas3D & canvas) const private
{
  std::string label = (boost::format("Plate %1%") % (m_plate_index + 1)).str();
  const Camera& camera = wxGetApp().plater()->get_camera();
  Transform3d world_to_eye = camera.get_view_matrix();
  Transform3d world_to_screen = camera.get_projection_matrix() * world_to_eye;
  const std::array<int, 4>& viewport = camera.get_viewport();
  BoundingBoxf3* bounding_box = const_cast<BoundingBoxf3*>(&m_bounding_box);
  Vec3d screen_box_center = world_to_screen * bounding_box->min;
  float x = 0.0f;
  float y = 0.0f;
  if (camera.get_type() == Camera::EType::Perspective) {
    x = (0.5f + 0.001f * 0.5f * (float)screen_box_center(0)) * viewport[2];
    y = (0.5f - 0.001f * 0.5f * (float)screen_box_center(1)) * viewport[3];
  }
  else {
    x = (0.5f + 0.5f * (float)screen_box_center(0)) * viewport[2];
    y = (0.5f - 0.5f * (float)screen_box_center(1)) * viewport[3];
  }
  ImGuiWrapper& imgui = *wxGetApp().imgui();
  ImGui::PushStyleVar(ImGuiStyleVar_WindowBorderSize, 1.5f);
  ImGui::PushStyleVar(ImGuiStyleVar_WindowRounding, 0.0f);
  ImGui::PushStyleColor(ImGuiCol_Border, ImVec4(0.75f, 0.75f, 0.75f, 1.0f));
  imgui.set_next_window_pos(x, y, ImGuiCond_Always, 0.5f, 0.5f);
  imgui.begin(label, ImGuiWindowFlags_NoMouseInputs | ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove);
  ImGui::BringWindowToDisplayFront(ImGui::GetCurrentWindow());
  float win_w = ImGui::GetWindowWidth();
  float label_len = imgui.calc_text_size(label).x;
  ImGui::SetCursorPosX(0.5f * (win_w - label_len));
  ImGui::AlignTextToFramePadding();
  imgui.text(label);
  // force re-render while the windows gets to its final size (it takes several frames)
  if (ImGui::GetWindowContentRegionWidth() + 2.0f * ImGui::GetStyle().WindowPadding.x != ImGui::CalcWindowNextAutoFitSize(ImGui::GetCurrentWindow()).x)
    canvas.request_extra_frame();
  imgui.end();
  ImGui::PopStyleColor();
  ImGui::PopStyleVar(2);
}
References ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::bounding_box(), ImGui::BringWindowToDisplayFront(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), ImGui::CalcWindowNextAutoFitSize(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::Camera::get_projection_matrix(), Slic3r::GUI::Camera::get_type(), Slic3r::GUI::Camera::get_view_matrix(), Slic3r::GUI::Camera::get_viewport(), ImGui::GetCurrentWindow(), ImGui::GetStyle(), ImGui::GetWindowContentRegionWidth(), ImGui::GetWindowWidth(), ImGuiCol_Border, ImGuiCond_Always, ImGuiStyleVar_WindowBorderSize, ImGuiStyleVar_WindowRounding, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoDecoration, ImGuiWindowFlags_NoMouseInputs, ImGuiWindowFlags_NoMove, m_bounding_box, m_plate_index, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::GUI::Camera::Perspective, ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), Slic3r::GUI::GLCanvas3D::request_extra_frame(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), ImGui::SetCursorPosX(), Slic3r::GUI::ImGuiWrapper::text(), and ImVec2::x.
render_left_arrow()
void Slic3r::GUI::PartPlate::render_left_arrow (const float * render_color, bool use_lighting) const private
{
#if 0
  if (m_quadric == nullptr)
    return;
  double radius = m_grabber_box.size().y() * 0.5f;
  double height = radius * 2.0f;
  double position = m_grabber_box.size().x() * 0.8f;
  if (use_lighting)
    glsafe(::glEnable(GL_LIGHTING));
  glsafe(::glColor4fv(render_color));
  glsafe(::glPushMatrix());
  glsafe(::glTranslated(m_grabber_box.center().x(), m_grabber_box.center().y(), m_grabber_box.center().z()));
  glsafe(::glRotated(-90.0, 0.0, 1.0, 0.0));
  glsafe(::glTranslated(0.0, 0.0, position));
  ::gluQuadricOrientation(m_quadric, GLU_OUTSIDE);
  ::gluCylinder(m_quadric, 0.9 * radius, 0.0, height, 36, 1);
  ::gluQuadricOrientation(m_quadric, GLU_INSIDE);
  ::gluDisk(m_quadric, 0.0, 0.9 * radius, 36, 1);
  glsafe(::glPopMatrix());
  if (use_lighting)
    glsafe(::glDisable(GL_LIGHTING));
#endif
}
References Slic3r::BoundingBox3Base< PointClass >::center(), glsafe, m_grabber_box, m_quadric, and Slic3r::BoundingBox3Base< PointClass >::size().
render_logo()
void Slic3r::GUI::PartPlate::render_logo (bool bottom, bool render_cali = true) const private
{
  if (!m_partplate_list->render_bedtype_logo) {
    // render third-party printer texture logo
    if (m_partplate_list->m_logo_texture_filename.empty()) {
      m_partplate_list->m_logo_texture.reset();
      return;
    }
    //GLTexture* temp_texture = const_cast<GLTexture*>(&m_temp_texture);
    if (m_partplate_list->m_logo_texture.get_id() == 0 || m_partplate_list->m_logo_texture.get_source() != m_partplate_list->m_logo_texture_filename) {
      m_partplate_list->m_logo_texture.reset();
      if (boost::algorithm::iends_with(m_partplate_list->m_logo_texture_filename, ".svg")) {
        /*// use higher resolution images if graphic card and opengl version allow
        GLint max_tex_size = OpenGLManager::get_gl_info().get_max_tex_size();
        if (temp_texture->get_id() == 0 || temp_texture->get_source() != m_texture_filename) {
          // generate a temporary lower resolution texture to show while no main texture levels have been compressed
          if (!temp_texture->load_from_svg_file(m_texture_filename, false, false, false, max_tex_size / 8)) {
            render_default(bottom, false);
            return;
          }
          canvas.request_extra_frame();
        }*/
        // starts generating the main texture, compression will run asynchronously
        GLint max_tex_size = OpenGLManager::get_gl_info().get_max_tex_size();
        GLint logo_tex_size = (max_tex_size < 2048) ? max_tex_size : 2048;
        if (!m_partplate_list->m_logo_texture.load_from_svg_file(m_partplate_list->m_logo_texture_filename, true, true, true, logo_tex_size)) {
          BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": load logo texture from %1% failed!") % m_partplate_list->m_logo_texture_filename;
          return;
        }
      }
      else if (boost::algorithm::iends_with(m_partplate_list->m_logo_texture_filename, ".png")) {
        // generate a temporary lower resolution texture to show while no main texture levels have been compressed
        /* if (temp_texture->get_id() == 0 || temp_texture->get_source() != m_logo_texture_filename) {
          if (!temp_texture->load_from_file(m_logo_texture_filename, false, GLTexture::None, false)) {
            render_default(bottom, false);
            return;
          }
          canvas.request_extra_frame();
        }*/
        // starts generating the main texture, compression will run asynchronously
        if (!m_partplate_list->m_logo_texture.load_from_file(m_partplate_list->m_logo_texture_filename, true, GLTexture::MultiThreaded, true)) {
          BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": load logo texture from %1% failed!") % m_partplate_list->m_logo_texture_filename;
          return;
        }
      }
      else {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": can not load logo texture from %1%, unsupported format") % m_partplate_list->m_logo_texture_filename;
        return;
      }
    }
    else if (m_partplate_list->m_logo_texture.unsent_compressed_data_available()) {
      // sends to gpu the already available compressed levels of the main texture
      m_partplate_list->m_logo_texture.send_compressed_data_to_gpu();
      // the temporary texture is not needed anymore, reset it
      //if (temp_texture->get_id() != 0)
      //    temp_texture->reset();
      //canvas.request_extra_frame();
    }
    if (m_vbo_id == 0) {
      unsigned int* vbo_id_ptr = const_cast<unsigned int*>(&m_vbo_id);
      glsafe(::glGenBuffers(1, vbo_id_ptr));
      glsafe(::glBindBuffer(GL_ARRAY_BUFFER, *vbo_id_ptr));
      glsafe(::glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)m_logo_triangles.get_vertices_data_size(), (const GLvoid*)m_logo_triangles.get_vertices_data(), GL_STATIC_DRAW));
      glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
    }
    if (m_vbo_id != 0 && m_logo_triangles.get_vertices_count() > 0)
      render_logo_texture(m_partplate_list->m_logo_texture, m_logo_triangles, bottom, m_vbo_id);
    return;
  }
  m_partplate_list->load_bedtype_textures();
  m_partplate_list->load_cali_textures();
  // btDefault should be skipped
  auto curr_bed_type = get_bed_type();
  if (curr_bed_type == btDefault) {
        DynamicConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
        if (proj_cfg.has(std::string("curr_bed_type")))
            curr_bed_type = proj_cfg.opt_enum<BedType>(std::string("curr_bed_type"));
  }
  int bed_type_idx = (int)curr_bed_type;
  // render bed textures
  for (auto &part : m_partplate_list->bed_texture_info[bed_type_idx].parts) {
    if (part.texture) {
      if (part.buffer && part.buffer->get_vertices_count() > 0
        //&& part.vbo_id != 0
        ) {
        if (part.offset.x() != m_origin.x() || part.offset.y() != m_origin.y()) {
          part.offset = Vec2d(m_origin.x(), m_origin.y());
          part.update_buffer();
        }
        render_logo_texture(*(part.texture),
                  *(part.buffer),
                  bottom,
                  part.vbo_id);
      }
    }
  }
  // render cali texture
  if (render_cali) {
    for (auto& part : m_partplate_list->cali_texture_info.parts) {
      if (part.texture) {
        if (part.buffer && part.buffer->get_vertices_count() > 0) {
          if (part.offset.x() != m_origin.x() || part.offset.y() != m_origin.y()) {
            part.offset = Vec2d(m_origin.x(), m_origin.y());
            part.update_buffer();
          }
          render_logo_texture(*(part.texture),
            *(part.buffer),
            bottom,
            part.vbo_id);
        }
      }
    }
  }
}
References Slic3r::GUI::PartPlateList::bed_texture_info, Slic3r::btDefault, Slic3r::GUI::PartPlateList::cali_texture_info, get_bed_type(), Slic3r::GUI::OpenGLManager::get_gl_info(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::OpenGLManager::GLInfo::get_max_tex_size(), Slic3r::GUI::GLTexture::get_source(), Slic3r::GUI::GeometryBuffer::get_vertices_count(), Slic3r::GUI::GeometryBuffer::get_vertices_data(), Slic3r::GUI::GeometryBuffer::get_vertices_data_size(), glsafe, Slic3r::ConfigOptionResolver::has(), int, Slic3r::GUI::PartPlateList::load_bedtype_textures(), Slic3r::GUI::PartPlateList::load_cali_textures(), Slic3r::GUI::GLTexture::load_from_file(), Slic3r::GUI::GLTexture::load_from_svg_file(), Slic3r::GUI::PartPlateList::m_logo_texture, Slic3r::GUI::PartPlateList::m_logo_texture_filename, m_logo_triangles, m_origin, m_partplate_list, m_vbo_id, Slic3r::GUI::GLTexture::MultiThreaded, Slic3r::DynamicConfig::opt_enum(), Slic3r::GUI::PartPlateList::BedTextureInfo::parts, Slic3r::GUI::PartPlateList::render_bedtype_logo, render_logo_texture(), Slic3r::GUI::GLTexture::reset(), Slic3r::GUI::GLTexture::send_compressed_data_to_gpu(), and Slic3r::GUI::GLTexture::unsent_compressed_data_available().
Referenced by render().
render_logo_texture()
void Slic3r::GUI::PartPlate::render_logo_texture (GLTexture & logo_texture, const GeometryBuffer & logo_buffer, bool bottom, unsigned int vbo_id) const private
{
  //check valid
  if (logo_texture.unsent_compressed_data_available()) {
    // sends to gpu the already available compressed levels of the main texture
    logo_texture.send_compressed_data_to_gpu();
  }
  if (logo_buffer.get_vertices_count() > 0) {
    GLShaderProgram* shader = wxGetApp().get_shader("printbed");
    if (shader != nullptr) {
      shader->start_using();
      shader->set_uniform("transparent_background", 0);
      shader->set_uniform("svg_source", 0);
      //glsafe(::glEnable(GL_DEPTH_TEST));
      glsafe(::glDepthMask(GL_FALSE));
      if (bottom)
        glsafe(::glFrontFace(GL_CW));
      unsigned int stride = logo_buffer.get_vertex_data_size();
      GLint position_id = shader->get_attrib_location("v_position");
      GLint tex_coords_id = shader->get_attrib_location("v_tex_coords");
      if (position_id != -1) {
        glsafe(::glEnableVertexAttribArray(position_id));
      }
      if (tex_coords_id != -1) {
        glsafe(::glEnableVertexAttribArray(tex_coords_id));
      }
      // show the temporary texture while no compressed data is available
      GLuint tex_id = (GLuint)logo_texture.get_id();
      glsafe(::glBindTexture(GL_TEXTURE_2D, tex_id));
      glsafe(::glBindBuffer(GL_ARRAY_BUFFER, vbo_id));
      if (position_id != -1)
        glsafe(::glVertexAttribPointer(position_id, 3, GL_FLOAT, GL_FALSE, stride, (GLvoid*)(intptr_t)logo_buffer.get_position_offset()));
      if (tex_coords_id != -1)
        glsafe(::glVertexAttribPointer(tex_coords_id, 2, GL_FLOAT, GL_FALSE, stride, (GLvoid*)(intptr_t)logo_buffer.get_tex_coords_offset()));
      glsafe(::glDrawArrays(GL_TRIANGLES, 0, (GLsizei)logo_buffer.get_vertices_count()));
      if (tex_coords_id != -1)
        glsafe(::glDisableVertexAttribArray(tex_coords_id));
      if (position_id != -1)
        glsafe(::glDisableVertexAttribArray(position_id));
      glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
      glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
      if (bottom)
        glsafe(::glFrontFace(GL_CCW));
      glsafe(::glDepthMask(GL_TRUE));
      shader->stop_using();
    }
  }
}
References Slic3r::GLShaderProgram::get_attrib_location(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::GeometryBuffer::get_position_offset(), Slic3r::GUI::GeometryBuffer::get_tex_coords_offset(), Slic3r::GUI::GeometryBuffer::get_vertex_data_size(), Slic3r::GUI::GeometryBuffer::get_vertices_count(), GL_FALSE, GL_TRIANGLES, GL_TRUE, glsafe, Slic3r::GUI::GLTexture::send_compressed_data_to_gpu(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::GUI::GLTexture::unsent_compressed_data_available().
Referenced by render_logo().
render_only_numbers()
void Slic3r::GUI::PartPlate::render_only_numbers (bool bottom) const private
{
  GLShaderProgram* shader = wxGetApp().get_shader("printbed");
  if (shader != nullptr) {
    shader->start_using();
    shader->set_uniform("transparent_background", bottom);
    //shader->set_uniform("svg_source", boost::algorithm::iends_with(m_partplate_list->m_del_texture.get_source(), ".svg"));
    shader->set_uniform("svg_source", 0);
        //if (bottom)
        //    glsafe(::glFrontFace(GL_CW));
        glsafe(::glDepthMask(GL_FALSE));
        GLint position_id = shader->get_attrib_location("v_position");
        GLint tex_coords_id = shader->get_attrib_location("v_tex_coords");
        if (position_id != -1) {
            glsafe(::glEnableVertexAttribArray(position_id));
        }
        if (tex_coords_id != -1) {
            glsafe(::glEnableVertexAttribArray(tex_coords_id));
        }
        if (m_plate_index >=0 && m_plate_index < MAX_PLATE_COUNT) {
            render_icon_texture(position_id, tex_coords_id, m_plate_idx_icon, m_partplate_list->m_idx_textures[m_plate_index], m_plate_idx_vbo_id);
        }
        if (tex_coords_id != -1)
            glsafe(::glDisableVertexAttribArray(tex_coords_id));
        if (position_id != -1)
            glsafe(::glDisableVertexAttribArray(position_id));
        //if (bottom)
        //    glsafe(::glFrontFace(GL_CCW));
        glsafe(::glDepthMask(GL_TRUE));
        shader->stop_using();
    }
}
References Slic3r::GLShaderProgram::get_attrib_location(), GL_FALSE, GL_TRUE, glsafe, Slic3r::GUI::PartPlateList::m_idx_textures, m_partplate_list, m_plate_idx_icon, m_plate_idx_vbo_id, m_plate_index, MAX_PLATE_COUNT, render_icon_texture(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by render().
render_plate_name_texture()
void Slic3r::GUI::PartPlate::render_plate_name_texture (int position_id, int tex_coords_id) private
{
  if (m_name_texture.get_id() == 0)
    generate_plate_name_texture();
  if (m_plate_name_vbo_id == 0 && m_plate_name_icon.get_vertices_data_size() > 0) {
    glsafe(::glGenBuffers(1, &m_plate_name_vbo_id));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, m_plate_name_vbo_id));
    glsafe(::glBufferData(GL_ARRAY_BUFFER, (GLsizeiptr)m_plate_name_icon.get_vertices_data_size(), (const GLvoid*)m_plate_name_icon.get_vertices_data(), GL_STATIC_DRAW));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
  }
  unsigned int stride = m_plate_name_icon.get_vertex_data_size();
  GLuint tex_id = (GLuint)m_name_texture.get_id();
  glsafe(::glBindTexture(GL_TEXTURE_2D, tex_id));
  glsafe(::glBindBuffer(GL_ARRAY_BUFFER, m_plate_name_vbo_id));
  if (position_id != -1)
    glsafe(::glVertexAttribPointer(position_id, 3, GL_FLOAT, GL_FALSE, stride, (GLvoid*)(intptr_t)m_plate_name_icon.get_position_offset()));
  if (tex_coords_id != -1)
    glsafe(::glVertexAttribPointer(tex_coords_id, 2, GL_FLOAT, GL_FALSE, stride, (GLvoid*)(intptr_t)m_plate_name_icon.get_tex_coords_offset()));
  glsafe(::glDrawArrays(GL_TRIANGLES, 0, (GLsizei)m_plate_name_icon.get_vertices_count()));
  glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
  glsafe(::glBindTexture(GL_TEXTURE_2D, 0));
}
References generate_plate_name_texture(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::GeometryBuffer::get_position_offset(), Slic3r::GUI::GeometryBuffer::get_tex_coords_offset(), Slic3r::GUI::GeometryBuffer::get_vertex_data_size(), Slic3r::GUI::GeometryBuffer::get_vertices_count(), Slic3r::GUI::GeometryBuffer::get_vertices_data(), Slic3r::GUI::GeometryBuffer::get_vertices_data_size(), GL_FALSE, GL_TRIANGLES, glsafe, m_name_texture, m_plate_name_icon, and m_plate_name_vbo_id.
Referenced by render_icons().
render_rectangle_for_picking()
void Slic3r::GUI::PartPlate::render_rectangle_for_picking (const GeometryBuffer & buffer, const float * render_color) const private
{
  unsigned int triangles_vcount = buffer.get_vertices_count();
  //glsafe(::glDepthMask(GL_FALSE));
  glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
  glsafe(::glColor4fv(render_color));
  glsafe(::glNormal3d(0.0f, 0.0f, 1.0f));
  glsafe(::glVertexPointer(3, GL_FLOAT, buffer.get_vertex_data_size(), (GLvoid*)buffer.get_vertices_data()));
  glsafe(::glDrawArrays(GL_TRIANGLES, 0, (GLsizei)triangles_vcount));
  glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
  //glsafe(::glDepthMask(GL_TRUE));
}
References buffer, GL_TRIANGLES, and glsafe.
Referenced by on_render_for_picking().
render_right_arrow()
void Slic3r::GUI::PartPlate::render_right_arrow (const float * render_color, bool use_lighting) const private
{
#if 0
  if (m_quadric == nullptr)
    return;
  double radius = m_grabber_box.size().y() * 0.5f;
  double height = radius * 2.0f;
  double position = m_grabber_box.size().x() * 0.8f;
  if (use_lighting)
    glsafe(::glEnable(GL_LIGHTING));
  glsafe(::glColor4fv(render_color));
  glsafe(::glPushMatrix());
  glsafe(::glTranslated(m_grabber_box.center().x(), m_grabber_box.center().y(), m_grabber_box.center().z()));
  glsafe(::glRotated(90.0, 0.0, 1.0, 0.0));
  glsafe(::glTranslated(0.0, 0.0, position));
  ::gluQuadricOrientation(m_quadric, GLU_OUTSIDE);
  ::gluCylinder(m_quadric, 0.9 * radius, 0.0, height, 36, 1);
  ::gluQuadricOrientation(m_quadric, GLU_INSIDE);
  ::gluDisk(m_quadric, 0.0, 0.9 * radius, 36, 1);
  glsafe(::glPopMatrix());
  if (use_lighting)
    glsafe(::glDisable(GL_LIGHTING));
#endif
}
References Slic3r::BoundingBox3Base< PointClass >::center(), glsafe, m_grabber_box, m_quadric, and Slic3r::BoundingBox3Base< PointClass >::size().
reset_bed_type()
void Slic3r::GUI::PartPlate::reset_bed_type ()
{
    m_config.erase("curr_bed_type");
}
References Slic3r::DynamicConfig::erase(), and m_config.
save()
template<class Archive > void Slic3r::GUI::PartPlate::save (Archive & ar) const inline
{
        std::vector<std::pair<int, int>>  objects_and_instances;
        std::vector<std::pair<int, int>>  instances_outside;
        for (std::set<std::pair<int, int>>::iterator it = instance_outside_set.begin(); it != instance_outside_set.end(); ++it)
            instances_outside.emplace_back(it->first, it->second);
        for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it)
            objects_and_instances.emplace_back(it->first, it->second);
        ar(m_plate_index, m_name, m_print_index, m_origin, m_width, m_depth, m_height, m_locked, m_selected, m_ready_for_slice, m_slice_result_valid, m_apply_invalid, m_printable, m_tmp_gcode_path, objects_and_instances, instances_outside, m_config);
    }
References instance_outside_set, m_apply_invalid, m_config, m_depth, m_height, m_locked, m_name, m_origin, m_plate_index, m_print_index, m_printable, m_ready_for_slice, m_selected, m_slice_result_valid, m_tmp_gcode_path, m_width, and obj_to_instance_set.
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_bed_type()
void Slic3r::GUI::PartPlate::set_bed_type (BedType bed_type)
{
    std::string bed_type_key = "curr_bed_type";
    // should be called in GUI context
    assert(m_plater != nullptr);
    // update slice state
    BedType old_real_bed_type = get_bed_type();
    if (old_real_bed_type == btDefault) {
        DynamicConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
        if (proj_cfg.has(bed_type_key))
            old_real_bed_type = proj_cfg.opt_enum<BedType>(bed_type_key);
    }
    BedType new_real_bed_type = bed_type;
    if (bed_type == BedType::btDefault) {
        DynamicConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
        if (proj_cfg.has(bed_type_key))
            new_real_bed_type = proj_cfg.opt_enum<BedType>(bed_type_key);
    }
    if (old_real_bed_type != new_real_bed_type) {
        update_slice_result_valid_state(false);
    }
    if (bed_type == BedType::btDefault)
        m_config.erase(bed_type_key);
    else
        m_config.set_key_value("curr_bed_type", new ConfigOptionEnum<BedType>(bed_type));
}
References Slic3r::btDefault, Slic3r::DynamicConfig::erase(), get_bed_type(), Slic3r::ConfigOptionResolver::has(), m_config, m_plater, Slic3r::DynamicConfig::opt_enum(), Slic3r::DynamicConfig::set_key_value(), and update_slice_result_valid_state().
Referenced by Slic3r::GUI::Plater::select_plate_by_hover_id().
set_hover_id()
void Slic3r::GUI::PartPlate::set_hover_id (int id) inline
{ m_hover_id = id; }
References Slic3r::ObjectBase::id(), and m_hover_id.
set_index()
void Slic3r::GUI::PartPlate::set_index (int index)
{
  BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": plate_id update from %1% to %2%") % m_plate_index % index;
  m_plate_index = index;
  if (m_print != nullptr)
    m_print->set_plate_index(index);
}
References m_plate_index, m_print, and Slic3r::PrintBase::set_plate_index().
Referenced by Slic3r::GUI::PartPlateList::create_plate(), Slic3r::GUI::PartPlateList::delete_plate(), Slic3r::GUI::PartPlateList::init(), and Slic3r::GUI::PartPlateList::move_plate_to_index().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_plate_name()
void Slic3r::GUI::PartPlate::set_plate_name (const std::string & name)
{
  // compare if name equal to m_name, case sensitive
    if (boost::equals(m_name, name))
        return;
  m_name = name;
    if (m_print != nullptr)
        m_print->set_plate_name(name);
  generate_plate_name_texture();
}
References generate_plate_name_texture(), m_name, m_print, and Slic3r::PrintBase::set_plate_name().
Referenced by Slic3r::GUI::Plater::select_plate_by_hover_id().
set_pos_and_size()
void Slic3r::GUI::PartPlate::set_pos_and_size (Vec3d & origin, int width, int depth, int height, bool with_instance_move)
{
  bool size_changed = false; //size changed means the machine changed
  bool pos_changed = false;
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate_id %1%, before, origin {%2%,%3%,%4%}, plate_width %5%, plate_depth %6%, plate_height %7%")\
    % m_plate_index % m_origin.x() % m_origin.y() % m_origin.z() % m_width % m_depth % m_height;
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": with_instance_move %1%, after, origin {%2%,%3%,%4%}, plate_width %5%, plate_depth %6%, plate_height %7%")\
    % with_instance_move % origin.x() % origin.y() % origin.z() % width % depth % height;
  size_changed = ((width != m_width) || (depth != m_depth) || (height != m_height));
  pos_changed = (m_origin != origin);
  if ((!size_changed) && (!pos_changed))
  {
    //size and position the same with before, just return
    return;
  }
  if (with_instance_move)
  {
    for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it) {
      int obj_id = it->first;
      int instance_id = it->second;
      ModelObject* object = m_model->objects[obj_id];
      ModelInstance* instance = object->instances[instance_id];
      //move this instance into the new plate's same position
      Vec3d offset = instance->get_transformation().get_offset();
      int off_x, off_y;
      if (size_changed)
      {
        //change position due to the bed size changes
        //off_x = (width - m_width) * m_plate_index + (width - m_width) / 2;
        //off_y = (depth - m_depth) * m_plate_index + (depth - m_depth) / 2;
        off_x = origin.x() - m_origin.x() + (width - m_width) / 2;
        off_y = origin.y() - m_origin.y() + (depth - m_depth) / 2;
      }
      else
      {
        //change position due to the plate moves
        off_x = origin.x() - m_origin.x();
        off_y = origin.y() - m_origin.y();
      }
      offset.x() = offset.x() + off_x;
      offset.y() = offset.y() + off_y;
      BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": object %1%, instance %2%, moved {%3%,%4%} to {%5%, %6%}")\
        % obj_id % instance_id % off_x % off_y % offset.x() % offset.y();
      instance->set_offset(offset);
      object->invalidate_bounding_box();
    }
  }
  else
  {
    clear();
  }
    if (m_print)
        m_print->set_plate_origin(origin);
  m_origin = origin;
  m_width = width;
  m_depth = depth;
  m_height = height;
  return;
}
References clear(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::ModelInstance::get_transformation(), m_depth, m_height, m_model, m_origin, m_plate_index, m_print, m_width, obj_to_instance_set, Slic3r::Model::objects, Slic3r::offset(), Slic3r::ModelInstance::set_offset(), and Slic3r::Print::set_plate_origin().
Referenced by Slic3r::GUI::PartPlateList::create_plate(), Slic3r::GUI::PartPlateList::delete_plate(), Slic3r::GUI::PartPlateList::move_plate_to_index(), Slic3r::GUI::PartPlateList::reinit(), and Slic3r::GUI::PartPlateList::update_all_plates_pos_and_size().
set_print()
void Slic3r::GUI::PartPlate::set_print (PrintBase * print, GCodeResult * result = nullptr, int index = -1)
{
  if (printer_technology == PrinterTechnology::ptFFF)
    m_print = static_cast<Print*>(print);
  //todo, for other printers
  m_gcode_result = result;
  if (index >= 0)
    m_print_index = index;
  m_print->set_plate_origin(m_origin);
  return;
}
References m_gcode_result, m_origin, m_print, m_print_index, print(), printer_technology, Slic3r::ptFFF, and Slic3r::Print::set_plate_origin().
Referenced by Slic3r::GUI::PartPlateList::create_plate(), and Slic3r::GUI::PartPlateList::init().
set_print_seq()
void Slic3r::GUI::PartPlate::set_print_seq (PrintSequence print_seq = PrintSequence::ByDefault)
{
    std::string print_seq_key = "print_sequence";
    // should be called in GUI context
    assert(m_plater != nullptr);
    // update slice state
    PrintSequence old_real_print_seq = get_print_seq();
    if (old_real_print_seq == PrintSequence::ByDefault) {
        auto curr_preset_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
        if (curr_preset_config.has(print_seq_key))
            old_real_print_seq = curr_preset_config.option<ConfigOptionEnum<PrintSequence>>(print_seq_key)->value;
    }
    PrintSequence new_real_print_seq = print_seq;
    if (print_seq == PrintSequence::ByDefault) {
        auto curr_preset_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
        if (curr_preset_config.has(print_seq_key))
            new_real_print_seq = curr_preset_config.option<ConfigOptionEnum<PrintSequence>>(print_seq_key)->value;
    }
    if (old_real_print_seq != new_real_print_seq) {
        update_slice_result_valid_state(false);
    }
    //print_seq_same_global = same_global;
    if (print_seq == PrintSequence::ByDefault)
        m_config.erase(print_seq_key);
    else
        m_config.set_key_value(print_seq_key, new ConfigOptionEnum<PrintSequence>(print_seq));
}
References Slic3r::ByDefault, Slic3r::DynamicConfig::erase(), get_print_seq(), m_config, m_plater, Slic3r::DynamicConfig::set_key_value(), and update_slice_result_valid_state().
Referenced by Slic3r::GUI::Plater::select_plate_by_hover_id().
set_selected()
void Slic3r::GUI::PartPlate::set_selected ()
{
  m_selected = true;
}
References m_selected.
set_shape()
bool Slic3r::GUI::PartPlate::set_shape (const Pointfs & shape, const Pointfs & exclude_areas, Vec2d position, float height_to_lid, float height_to_rod)
{
  Pointfs new_shape, new_exclude_areas;
  for (const Vec2d& p : shape) {
    new_shape.push_back(Vec2d(p.x() + position.x(), p.y() + position.y()));
  }
  for (const Vec2d& p : exclude_areas) {
    new_exclude_areas.push_back(Vec2d(p.x() + position.x(), p.y() + position.y()));
  }
  if ((m_shape == new_shape)&&(m_exclude_area == new_exclude_areas)
    &&(m_height_to_lid == height_to_lid)&&(m_height_to_rod == height_to_rod)) {
    BOOST_LOG_TRIVIAL(info) << "PartPlate same shape, skip directly";
    return false;
  }
  m_height_to_lid =  height_to_lid;
  m_height_to_rod =  height_to_rod;
  if ((m_shape != new_shape) || (m_exclude_area != new_exclude_areas))
  {
    /*m_shape.clear();
    for (const Vec2d& p : shape) {
      m_shape.push_back(Vec2d(p.x() + position.x(), p.y() + position.y()));
    }
    m_exclude_area.clear();
    for (const Vec2d& p : exclude_areas) {
      m_exclude_area.push_back(Vec2d(p.x() + position.x(), p.y() + position.y()));
    }*/
    m_shape = std::move(new_shape);
    m_exclude_area = std::move(new_exclude_areas);
    calc_bounding_boxes();
    ExPolygon logo_poly;
    generate_logo_polygon(logo_poly);
    if (!m_logo_triangles.set_from_triangles(triangulate_expolygon_2f(logo_poly, NORMALS_UP), GROUND_Z+0.02f))
      BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":Unable to create logo triangles\n";
    else {
      ;
    }
    ExPolygon poly;
    /*for (const Vec2d& p : m_shape) {
      poly.contour.append({ scale_(p(0)), scale_(p(1)) });
    }*/
    generate_print_polygon(poly);
    calc_triangles(poly);
    ExPolygon exclude_poly;
    /*for (const Vec2d& p : m_exclude_area) {
      exclude_poly.contour.append({ scale_(p(0)), scale_(p(1)) });
    }*/
    generate_exclude_polygon(exclude_poly);
    calc_exclude_triangles(exclude_poly);
    const BoundingBox& pp_bbox = poly.contour.bounding_box();
    calc_gridlines(poly, pp_bbox);
    //calc_vertex_for_icons_background(5, m_del_and_background_icon);
    //calc_vertex_for_icons(4, m_del_icon);
    calc_vertex_for_icons(0, m_del_icon);
    calc_vertex_for_icons(1, m_orient_icon);
    calc_vertex_for_icons(2, m_arrange_icon);
    calc_vertex_for_icons(3, m_lock_icon);
    calc_vertex_for_icons(4, m_plate_settings_icon);
    //calc_vertex_for_number(0, (m_plate_index < 9), m_plate_idx_icon);
    calc_vertex_for_number(0, false, m_plate_idx_icon);
    // calc vertex for plate name
    generate_plate_name_texture();
  }
  calc_height_limit();
  release_opengl_resource();
  return true;
}
References Slic3r::MultiPoint::bounding_box(), calc_bounding_boxes(), calc_exclude_triangles(), calc_gridlines(), calc_height_limit(), calc_triangles(), calc_vertex_for_icons(), calc_vertex_for_number(), Slic3r::ExPolygon::contour, error, generate_exclude_polygon(), generate_logo_polygon(), generate_plate_name_texture(), generate_print_polygon(), GROUND_Z, m_arrange_icon, m_del_icon, m_exclude_area, m_height_to_lid, m_height_to_rod, m_lock_icon, m_logo_triangles, m_orient_icon, m_plate_idx_icon, m_plate_settings_icon, m_shape, Slic3r::NORMALS_UP, release_opengl_resource(), Slic3r::GUI::GeometryBuffer::set_from_triangles(), and Slic3r::triangulate_expolygon_2f().
Referenced by Slic3r::GUI::PartPlateList::create_plate(), Slic3r::GUI::PartPlateList::delete_plate(), and Slic3r::GUI::PartPlateList::set_shapes().
set_tmp_gcode_path()
void Slic3r::GUI::PartPlate::set_tmp_gcode_path (std::string new_path) inline
    {
        m_tmp_gcode_path = new_path;
    }
References m_tmp_gcode_path.
Referenced by Slic3r::CLI::run().
set_unselected()
void Slic3r::GUI::PartPlate::set_unselected ()
{
  m_selected = false;
}
References m_selected.
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
translate_all_instance()
void Slic3r::GUI::PartPlate::translate_all_instance (Vec3d position)
{
    for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it)
    {
        int obj_id = it->first;
        int instance_id = it->second;
        if ((obj_id >= 0) && (obj_id < m_model->objects.size()))
        {
            ModelObject* object = m_model->objects[obj_id];
            if ((instance_id >= 0) && (instance_id < object->instances.size()))
            {
                ModelInstance* instance = object->instances[instance_id];
                const Vec3d& offset =  instance->get_offset();
                instance->set_offset(offset + position);
            }
        }
    }
    return;
}
References Slic3r::ModelInstance::get_offset(), m_model, obj_to_instance_set, Slic3r::Model::objects, Slic3r::offset(), and Slic3r::ModelInstance::set_offset().
Referenced by Slic3r::GUI::Plater::priv::load_files(), and Slic3r::CLI::run().
update_apply_result_invalid()
void Slic3r::GUI::PartPlate::update_apply_result_invalid (bool invalid) inline
    {
        m_apply_invalid = invalid;
    }
References m_apply_invalid.
update_instance_exclude_status()
void Slic3r::GUI::PartPlate::update_instance_exclude_status (int obj_id, int instance_id, BoundingBoxf3 * bounding_box = nullptr)
{
  bool outside;
  std::set<std::pair<int, int>>::iterator it;
  outside = check_outside(obj_id, instance_id, bounding_box);
  it = instance_outside_set.find(std::pair(obj_id, instance_id));
  if (it == instance_outside_set.end()) {
    if (outside)
      instance_outside_set.insert(std::pair(obj_id, instance_id));
  }
  else {
    if (!outside)
      instance_outside_set.erase(it);
  }
}
References Slic3r::bounding_box(), check_outside(), and instance_outside_set.
Referenced by Slic3r::GUI::PartPlateList::notify_instance_update().
update_object_index()
void Slic3r::GUI::PartPlate::update_object_index (int obj_idx_removed, int obj_idx_max)
{
  std::set<std::pair<int, int>> temp_set;
  std::set<std::pair<int, int>>::iterator it;
  //update the obj_to_instance_set
  for (it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it)
  {
    if (it->first >= obj_idx_removed)
      temp_set.insert(std::pair(it->first-1, it->second));
    else
      temp_set.insert(std::pair(it->first, it->second));
  }
  obj_to_instance_set.clear();
  obj_to_instance_set = temp_set;
  //update the instance_outside_set
  temp_set.clear();
  for (it = instance_outside_set.begin(); it != instance_outside_set.end(); ++it)
  {
    if (it->first >= obj_idx_removed)
      temp_set.insert(std::pair(it->first - 1, it->second));
    else
      temp_set.insert(std::pair(it->first, it->second));
  }
  instance_outside_set.clear();
  instance_outside_set = temp_set;
}
References instance_outside_set, and obj_to_instance_set.
Referenced by Slic3r::GUI::PartPlateList::notify_instance_removed().
update_render_colors()
void Slic3r::GUI::PartPlate::update_render_colors () static
{
  PartPlate::SELECT_COLOR     = GLColor(RenderColor::colors[RenderCol_Plate_Selected]);
  PartPlate::UNSELECT_COLOR   = GLColor(RenderColor::colors[RenderCol_Plate_Unselected]);
  PartPlate::DEFAULT_COLOR    = GLColor(RenderColor::colors[RenderCol_Plate_Default]);
  PartPlate::LINE_TOP_COLOR   = GLColor(RenderColor::colors[RenderCol_Plate_Line_Top]);
  PartPlate::LINE_BOTTOM_COLOR  = GLColor(RenderColor::colors[RenderCol_Plate_Line_Bottom]);
}
References Slic3r::RenderColor::colors, DEFAULT_COLOR, Slic3r::GLColor(), LINE_BOTTOM_COLOR, LINE_TOP_COLOR, RenderCol_Plate_Default, RenderCol_Plate_Line_Bottom, RenderCol_Plate_Line_Top, RenderCol_Plate_Selected, RenderCol_Plate_Unselected, SELECT_COLOR, and UNSELECT_COLOR.
Referenced by Slic3r::GUI::GLCanvas3D::_render_style_editor().
update_slice_context()
void Slic3r::GUI::PartPlate::update_slice_context (BackgroundSlicingProcess & process)
{
  auto statuscb = [this](const Slic3r::PrintBase::SlicingStatus& status) {
    Slic3r::SlicingStatusEvent *event = new Slic3r::SlicingStatusEvent(EVT_SLICING_UPDATE, 0, status);
    //BBS: GUI refactor: add plate info befor message
    if (status.message_type == Slic3r::PrintStateBase::SlicingDefaultNotification) {
      auto temp = Slic3r::format(_u8L(" plate %1%:"), std::to_string(m_plate_index + 1));
      event->status.text = temp + event->status.text;
    }
    wxQueueEvent(m_plater, event);
  };
  process.set_fff_print(m_print);
  process.set_gcode_result(m_gcode_result);
  process.select_technology(this->printer_technology);
  process.set_current_plate(this);
  m_print->set_status_callback(statuscb);
  process.switch_print_preprocess();
  return;
}
References _u8L, Slic3r::format(), m_gcode_result, m_plate_index, m_plater, m_print, printer_technology, Slic3r::BackgroundSlicingProcess::select_technology(), Slic3r::BackgroundSlicingProcess::set_current_plate(), Slic3r::BackgroundSlicingProcess::set_fff_print(), Slic3r::BackgroundSlicingProcess::set_gcode_result(), Slic3r::PrintBase::set_status_callback(), Slic3r::PrintStateBase::SlicingDefaultNotification, and Slic3r::BackgroundSlicingProcess::switch_print_preprocess().
Referenced by Slic3r::GUI::PartPlateList::update_slice_context_to_current_plate().
update_slice_ready_status()
void Slic3r::GUI::PartPlate::update_slice_ready_status (bool ready_slice) inline
    {
        m_ready_for_slice = ready_slice;
    }
References m_ready_for_slice.
Referenced by Slic3r::GUI::Plater::validate_current_plate().
update_slice_result_valid_state()
void Slic3r::GUI::PartPlate::update_slice_result_valid_state (bool valid = false)
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1% , update slice result from %2% to %3%") % m_plate_index %m_slice_result_valid %valid;
    m_slice_result_valid = valid;
    if (valid)
        m_slice_percent = 100.0f;
    else {
        m_slice_percent = -1.0f;
    }
}
References m_plate_index, m_slice_percent, and m_slice_result_valid.
Referenced by Slic3r::GUI::Plater::apply_background_progress(), clear(), load_gcode_from_file(), Slic3r::GUI::PartPlateList::notify_instance_removed(), Slic3r::GUI::PartPlateList::notify_instance_update(), Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::GUI::Plater::priv::on_select_preset(), Slic3r::GUI::Plater::reslice(), Slic3r::CLI::run(), Slic3r::GUI::Plater::select_plate(), Slic3r::GUI::Plater::select_plate_by_hover_id(), set_bed_type(), and set_print_seq().
update_slicing_percent()
void Slic3r::GUI::PartPlate::update_slicing_percent (float percent) inline
    {
        m_slice_percent = percent;
    }
References m_slice_percent.
Referenced by Slic3r::GUI::Plater::priv::on_slicing_update().
update_states()
void Slic3r::GUI::PartPlate::update_states ()
{
  //currently let judge outside partplate when plate is empty
  /*if (obj_to_instance_set.size() == 0)
  {
    m_ready_for_slice = false;
    return;
  }*/
  m_ready_for_slice = true;
  for (std::set<std::pair<int, int>>::iterator it = obj_to_instance_set.begin(); it != obj_to_instance_set.end(); ++it) {
    int obj_id = it->first;
    int instance_id = it->second;
    //if (check_outside(obj_id, instance_id))
    if (instance_outside_set.find(std::pair(obj_id, instance_id)) != instance_outside_set.end())
    {
      m_ready_for_slice = false;
      //currently only check whether ready to slice
      break;
    }
  }
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": plate %1% , m_ready_for_slice changes to %2%") % m_plate_index %m_ready_for_slice;
  return;
}
References instance_outside_set, m_plate_index, m_ready_for_slice, and obj_to_instance_set.
Referenced by Slic3r::GUI::PartPlateList::notify_instance_update(), and remove_instance().
valid_instance()
bool Slic3r::GUI::PartPlate::valid_instance (int obj_id, int instance_id) private
{
  if ((obj_id >= 0) && (obj_id < m_model->objects.size()))
  {
    ModelObject* object = m_model->objects[obj_id];
    if ((instance_id >= 0) && (instance_id < object->instances.size()))
      return true;
  }
  return false;
}
References m_model, and Slic3r::Model::objects.
Referenced by add_instance(), intersect_instance(), and is_left_top_of().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
PartPlateList
friend class PartPlateList friend
UndoRedo::StackImpl
friend class UndoRedo::StackImpl friend
Member Data Documentation
cali_bboxes_data
PlateBBoxData Slic3r::GUI::PartPlate::cali_bboxes_data
Referenced by load_pattern_box_data().
DEFAULT_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::DEFAULT_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f } static
Referenced by load_render_colors(), render_background(), and update_render_colors().
GRABBER_COUNT
const unsigned int Slic3r::GUI::PartPlate::GRABBER_COUNT = 6 static
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), picking_color_component(), Slic3r::GUI::PartPlateList::render(), Slic3r::GUI::Plater::select_plate_by_hover_id(), and Slic3r::GUI::PartPlateList::set_hover_id().
HEIGHT_LIMIT_BOTTOM_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::HEIGHT_LIMIT_BOTTOM_COLOR = { 0.4f, 0.4f, 1.0f, 1.0f } static
Referenced by render_height_limit().
HEIGHT_LIMIT_TOP_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::HEIGHT_LIMIT_TOP_COLOR = { 0.6f, 0.6f, 1.0f, 1.0f } static
Referenced by render_height_limit().
instance_outside_set
std::set<std::pair<int, int> > Slic3r::GUI::PartPlate::instance_outside_set private
Referenced by add_instance(), clear(), contain_instance_totally(), has_printable_instances(), load(), print(), printable_instance_size(), remove_instance(), save(), update_instance_exclude_status(), update_object_index(), and update_states().
LINE_BOTTOM_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::LINE_BOTTOM_COLOR = { 0.8f, 0.8f, 0.8f, 0.4f } static
Referenced by load_render_colors(), render_grid(), and update_render_colors().
LINE_TOP_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::LINE_TOP_COLOR = { 0.89f, 0.89f, 0.89f, 1.0f } static
Referenced by load_render_colors(), render_grid(), and update_render_colors().
LINE_TOP_DARK_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::LINE_TOP_DARK_COLOR = { 0.431f, 0.431f, 0.463f, 1.0f } static
Referenced by render_grid().
LINE_TOP_SEL_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::LINE_TOP_SEL_COLOR = { 0.5294f, 0.5451, 0.5333f, 1.0f} static
Referenced by render_grid().
LINE_TOP_SEL_DARK_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::LINE_TOP_SEL_DARK_COLOR = { 0.298f, 0.298f, 0.3333f, 1.0f} static
Referenced by render_grid().
m_apply_invalid
bool Slic3r::GUI::PartPlate::m_apply_invalid {false} private
Referenced by can_slice(), is_apply_result_invalid(), load(), save(), and update_apply_result_invalid().
m_arrange_icon
GeometryBuffer Slic3r::GUI::PartPlate::m_arrange_icon private
Referenced by on_render_for_picking(), render_icons(), and set_shape().
m_arrange_vbo_id
unsigned int Slic3r::GUI::PartPlate::m_arrange_vbo_id { 0 } mutable private
Referenced by release_opengl_resource(), and render_icons().
m_bounding_box
BoundingBoxf3 Slic3r::GUI::PartPlate::m_bounding_box private
Referenced by calc_bounding_boxes(), check_outside(), contains(), contains(), contains(), get_bounding_box(), get_build_volume(), get_center_origin(), intersect_instance(), intersects(), render_grabber(), and render_label().
m_config
DynamicPrintConfig Slic3r::GUI::PartPlate::m_config private
Referenced by config(), get_bed_type(), get_print_seq(), load(), load_gcode_from_file(), reset_bed_type(), save(), set_bed_type(), and set_print_seq().
m_del_icon
GeometryBuffer Slic3r::GUI::PartPlate::m_del_icon private
Referenced by on_render_for_picking(), render_icons(), and set_shape().
m_del_vbo_id
unsigned int Slic3r::GUI::PartPlate::m_del_vbo_id { 0 } mutable private
Referenced by release_opengl_resource(), and render_icons().
m_depth
int Slic3r::GUI::PartPlate::m_depth private
Referenced by calc_bounding_boxes(), load(), print(), save(), and set_pos_and_size().
m_exclude_area
Pointfs Slic3r::GUI::PartPlate::m_exclude_area private
Referenced by calc_bounding_boxes(), generate_exclude_polygon(), and set_shape().
m_exclude_bounding_box
std::vector<BoundingBoxf3> Slic3r::GUI::PartPlate::m_exclude_bounding_box mutable private
Referenced by calc_bounding_boxes(), check_outside(), get_exclude_areas(), and Slic3r::GUI::PartPlateList::preprocess_exclude_areas().
m_exclude_triangles
GeometryBuffer Slic3r::GUI::PartPlate::m_exclude_triangles private
Referenced by calc_exclude_triangles(), and render_exclude_area().
m_extended_bounding_box
BoundingBoxf3 Slic3r::GUI::PartPlate::m_extended_bounding_box private
Referenced by calc_bounding_boxes(), and get_bounding_box().
m_gcode_path_from_3mf
std::string Slic3r::GUI::PartPlate::m_gcode_path_from_3mf private
m_gcode_result
GCodeProcessorResult* Slic3r::GUI::PartPlate::m_gcode_result private
Referenced by get_gcode_filename(), get_print(), get_slice_result(), is_slice_result_ready_for_print(), is_valid_gcode_file(), load_gcode_from_file(), set_print(), and update_slice_context().
m_grabber_box
BoundingBoxf3 Slic3r::GUI::PartPlate::m_grabber_box mutable private
Referenced by calc_bounding_boxes(), render_arrows(), render_grabber(), render_left_arrow(), and render_right_arrow().
m_grabber_color
float Slic3r::GUI::PartPlate::m_grabber_color[4] mutable private
Referenced by on_render_for_picking().
m_grabber_trans_matrix
Transform3d Slic3r::GUI::PartPlate::m_grabber_trans_matrix private
m_gridlines
GeometryBuffer Slic3r::GUI::PartPlate::m_gridlines private
Referenced by calc_gridlines(), and render_grid().
m_gridlines_bolder
GeometryBuffer Slic3r::GUI::PartPlate::m_gridlines_bolder private
Referenced by calc_gridlines(), and render_grid().
m_height
int Slic3r::GUI::PartPlate::m_height private
Referenced by check_outside(), get_build_volume(), intersect_instance(), load(), print(), save(), and set_pos_and_size().
m_height_limit_bottom
GeometryBuffer Slic3r::GUI::PartPlate::m_height_limit_bottom private
Referenced by calc_height_limit(), and render_height_limit().
m_height_limit_common
GeometryBuffer Slic3r::GUI::PartPlate::m_height_limit_common private
Referenced by calc_height_limit(), and render_height_limit().
m_height_limit_top
GeometryBuffer Slic3r::GUI::PartPlate::m_height_limit_top private
Referenced by calc_height_limit(), and render_height_limit().
m_height_to_lid
float Slic3r::GUI::PartPlate::m_height_to_lid private
Referenced by calc_height_limit(), and set_shape().
m_height_to_rod
float Slic3r::GUI::PartPlate::m_height_to_rod private
Referenced by calc_height_limit(), and set_shape().
m_hover_id
int Slic3r::GUI::PartPlate::m_hover_id private
Referenced by init(), and set_hover_id().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_lock_icon
GeometryBuffer Slic3r::GUI::PartPlate::m_lock_icon private
Referenced by on_render_for_picking(), render_icons(), and set_shape().
m_lock_vbo_id
unsigned int Slic3r::GUI::PartPlate::m_lock_vbo_id { 0 } mutable private
Referenced by release_opengl_resource(), and render_icons().
m_locked
bool Slic3r::GUI::PartPlate::m_locked private
Referenced by init(), is_locked(), load(), lock(), print(), and save().
m_logo_triangles
GeometryBuffer Slic3r::GUI::PartPlate::m_logo_triangles private
Referenced by render_logo(), and set_shape().
m_model
Model* Slic3r::GUI::PartPlate::m_model private
Referenced by add_instance(), check_outside(), contain_instance_totally(), duplicate_all_instance(), estimate_wipe_tower_size(), get_extruders(), get_extruders_under_cli(), get_extruders_without_support(), get_instance(), get_objects(), get_temp_config_3mf_path(), get_tmp_gcode_path(), get_used_extruders(), has_printable_instances(), intersect_instance(), is_all_instances_unprintable(), is_left_top_of(), load_gcode_from_file(), printable_instance_size(), set_pos_and_size(), translate_all_instance(), and valid_instance().
m_name
std::string Slic3r::GUI::PartPlate::m_name private
Referenced by generate_plate_name_texture(), get_plate_name(), load(), save(), and set_plate_name().
m_name_texture
GLTexture Slic3r::GUI::PartPlate::m_name_texture private
Referenced by clear(), generate_plate_name_texture(), and render_plate_name_texture().
m_name_texture_height
wxCoord Slic3r::GUI::PartPlate::m_name_texture_height private
m_name_texture_width
wxCoord Slic3r::GUI::PartPlate::m_name_texture_width private
m_orient_icon
GeometryBuffer Slic3r::GUI::PartPlate::m_orient_icon private
Referenced by on_render_for_picking(), render_icons(), and set_shape().
m_orient_vbo_id
unsigned int Slic3r::GUI::PartPlate::m_orient_vbo_id { 0 } mutable private
Referenced by release_opengl_resource(), and render_icons().
m_origin
Vec3d Slic3r::GUI::PartPlate::m_origin private
Referenced by check_outside(), get_build_volume(), get_center_origin(), get_origin(), intersect_instance(), is_left_top_of(), load(), print(), render_logo(), save(), set_pos_and_size(), and set_print().
m_partplate_list
PartPlateList* Slic3r::GUI::PartPlate::m_partplate_list {nullptr } private
Referenced by on_render_for_picking(), render(), render_background(), render_grid(), render_icons(), render_logo(), and render_only_numbers().
m_plate_idx_icon
GeometryBuffer Slic3r::GUI::PartPlate::m_plate_idx_icon private
Referenced by render_icons(), render_only_numbers(), and set_shape().
m_plate_idx_vbo_id
unsigned int Slic3r::GUI::PartPlate::m_plate_idx_vbo_id { 0 } mutable private
Referenced by release_opengl_resource(), render_icons(), and render_only_numbers().
m_plate_index
int Slic3r::GUI::PartPlate::m_plate_index private
Referenced by add_instance(), duplicate_all_instance(), get_extruders(), get_extruders_under_cli(), get_extruders_without_support(), get_index(), intersect_instance(), is_left_top_of(), load(), operator<(), picking_color_component(), print(), remove_instance(), render_icons(), render_label(), render_only_numbers(), save(), set_index(), set_pos_and_size(), update_slice_context(), update_slice_result_valid_state(), and update_states().
m_plate_name_icon
GeometryBuffer Slic3r::GUI::PartPlate::m_plate_name_icon private
Referenced by generate_plate_name_texture(), and render_plate_name_texture().
m_plate_name_vbo_id
unsigned int Slic3r::GUI::PartPlate::m_plate_name_vbo_id { 0 } mutable private
Referenced by generate_plate_name_texture(), init(), release_opengl_resource(), and render_plate_name_texture().
m_plate_settings_icon
GeometryBuffer Slic3r::GUI::PartPlate::m_plate_settings_icon private
Referenced by on_render_for_picking(), render_icons(), and set_shape().
m_plate_settings_vbo_id
unsigned int Slic3r::GUI::PartPlate::m_plate_settings_vbo_id { 0 } mutable private
Referenced by release_opengl_resource(), and render_icons().
m_plater
Plater* Slic3r::GUI::PartPlate::m_plater private
Referenced by calc_vertex_for_icons(), get_bed_type(), set_bed_type(), set_print_seq(), and update_slice_context().
m_print
Print* Slic3r::GUI::PartPlate::m_print private
Referenced by fff_print(), get_print(), init(), load_gcode_from_file(), print(), render_height_limit(), set_index(), set_plate_name(), set_pos_and_size(), set_print(), and update_slice_context().
m_print_index
int Slic3r::GUI::PartPlate::m_print_index private
Referenced by Slic3r::GUI::PartPlateList::find_plate_by_print_index(), get_print(), init(), load(), print(), save(), and set_print().
m_printable
bool Slic3r::GUI::PartPlate::m_printable private
Referenced by intersect_instance(), is_printable(), load(), print(), and save().
m_quadric
GLUquadricObject* Slic3r::GUI::PartPlate::m_quadric private
Referenced by render_arrows(), render_left_arrow(), and render_right_arrow().
m_ready_for_slice
bool Slic3r::GUI::PartPlate::m_ready_for_slice private
Referenced by add_instance(), can_slice(), clear(), init(), load(), load_gcode_from_file(), print(), remove_instance(), save(), update_slice_ready_status(), and update_states().
m_scale_factor
float Slic3r::GUI::PartPlate::m_scale_factor { 1.0f } private
Referenced by render_grid(), and render_height_limit().
m_selected
bool Slic3r::GUI::PartPlate::m_selected private
Referenced by init(), load(), render(), render_background(), render_exclude_area(), render_grid(), save(), set_selected(), and set_unselected().
m_shape
Pointfs Slic3r::GUI::PartPlate::m_shape private
Referenced by calc_bounding_boxes(), calc_height_limit(), calc_vertex_for_icons(), calc_vertex_for_icons_background(), calc_vertex_for_number(), generate_logo_polygon(), generate_plate_name_texture(), generate_print_polygon(), get_bounding_box_crd(), get_shape(), and set_shape().
m_slice_percent
float Slic3r::GUI::PartPlate::m_slice_percent private
Referenced by get_slicing_percent(), init(), update_slice_result_valid_state(), and update_slicing_percent().
m_slice_result_valid
bool Slic3r::GUI::PartPlate::m_slice_result_valid private
Referenced by init(), is_slice_result_ready_for_print(), is_slice_result_valid(), load(), print(), save(), and update_slice_result_valid_state().
m_temp_config_3mf_path
std::string Slic3r::GUI::PartPlate::m_temp_config_3mf_path private
Referenced by get_temp_config_3mf_path().
m_texture
GLTexture Slic3r::GUI::PartPlate::m_texture private
m_tmp_gcode_path
std::string Slic3r::GUI::PartPlate::m_tmp_gcode_path private
Referenced by get_tmp_gcode_path(), load(), load_gcode_from_file(), print(), save(), and set_tmp_gcode_path().
m_triangles
GeometryBuffer Slic3r::GUI::PartPlate::m_triangles private
Referenced by calc_triangles(), on_render_for_picking(), and render_background().
m_vbo_id
unsigned int Slic3r::GUI::PartPlate::m_vbo_id { 0 } private
Referenced by release_opengl_resource(), and render_logo().
m_width
int Slic3r::GUI::PartPlate::m_width private
Referenced by load(), print(), save(), and set_pos_and_size().
obj_to_instance_set
std::set<std::pair<int, int> > Slic3r::GUI::PartPlate::obj_to_instance_set private
Referenced by add_instance(), clear(), contain_instance(), contain_instance_totally(), duplicate_all_instance(), empty(), get_extruders_under_cli(), has_printable_instances(), is_all_instances_unprintable(), load(), move_instances_to(), print(), printable_instance_size(), remove_instance(), save(), set_pos_and_size(), translate_all_instance(), update_object_index(), and update_states().
pick_thumbnail_data
ThumbnailData Slic3r::GUI::PartPlate::pick_thumbnail_data
Referenced by Slic3r::GUI::PartPlateList::notify_instance_removed(), Slic3r::GUI::PartPlateList::notify_instance_update(), and Slic3r::CLI::run().
PLATE_BASE_ID
const unsigned int Slic3r::GUI::PartPlate::PLATE_BASE_ID = 255 * 255 * 253 static
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and picking_color_component().
plate_thumbnail_height
const int Slic3r::GUI::PartPlate::plate_thumbnail_height = 512 static
Referenced by Slic3r::GUI::Plater::update_all_plate_thumbnails().
plate_thumbnail_width
const int Slic3r::GUI::PartPlate::plate_thumbnail_width = 512 static
Referenced by Slic3r::GUI::Plater::update_all_plate_thumbnails().
position
Slic3r::Geometry::Transformation Slic3r::GUI::PartPlate::position private
positions
std::vector<Vec3f> Slic3r::GUI::PartPlate::positions private
printer_technology
PrinterTechnology Slic3r::GUI::PartPlate::printer_technology private
Referenced by get_print(), set_print(), and update_slice_context().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
SELECT_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::SELECT_COLOR = { 0.2666f, 0.2784f, 0.2784f, 1.0f } static
Referenced by load_render_colors(), render_background(), and update_render_colors().
slice_filaments_info
std::vector<FilamentInfo> Slic3r::GUI::PartPlate::slice_filaments_info private
Referenced by get_extruders(), get_extruders_without_support(), and get_used_extruders().
thumbnail_data
ThumbnailData Slic3r::GUI::PartPlate::thumbnail_data
Referenced by Slic3r::GUI::GLCanvas3D::_update_imgui_select_plate_toolbar(), Slic3r::GUI::Plater::invalid_all_plate_thumbnails(), Slic3r::GUI::PartPlateList::notify_instance_removed(), Slic3r::GUI::PartPlateList::notify_instance_update(), Slic3r::GUI::SelectMachineDialog::set_default(), and Slic3r::GUI::Plater::update_all_plate_thumbnails().
top_thumbnail_data
ThumbnailData Slic3r::GUI::PartPlate::top_thumbnail_data
Referenced by Slic3r::GUI::PartPlateList::notify_instance_removed(), Slic3r::GUI::PartPlateList::notify_instance_update(), and Slic3r::CLI::run().
UNSELECT_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::UNSELECT_COLOR = { 0.82f, 0.82f, 0.82f, 1.0f } static
Referenced by load_render_colors(), render_background(), and update_render_colors().
UNSELECT_DARK_COLOR
std::array< float, 4 > Slic3r::GUI::PartPlate::UNSELECT_DARK_COLOR = { 0.384f, 0.384f, 0.412f, 1.0f } static
Referenced by render_background().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PartPlate.hpp
src/slic3r/GUI/PartPlate.cpp