OrcaSlicer: nlohmann::detail::exception Class Reference
nlohmann::detail::exception Class Reference
general exception of the basic_json class
#include <src/nlohmann/detail/exceptions.hpp>
Public Member Functions
const char * what () const noexcept override
returns the explanatory string
Public Attributes
const int id
the id of the exception
Protected Member Functions
exception (int id_, const char *what_arg)
Static Protected Member Functions
static std::string name (const std::string &ename, int id_)
template<typename BasicJsonType >
static std::string diagnostics (const BasicJsonType &leaf_element)
Private Attributes
std::runtime_error m
an exception object as storage for error messages
Detailed Description
general exception of the basic_json class
This class is an extension of std::exception objects with a member id for exception ids. It is used as the base class for all exceptions thrown by the basic_json class. This class can hence be used as "wildcard" to catch exceptions.
Subclasses:
parse_error for exceptions indicating a parse error
invalid_iterator for exceptions indicating errors with iterators
type_error for exceptions indicating executing a member function with a wrong type
out_of_range for exceptions indicating access out of the defined range
other_error for exceptions indicating other library errors
@liveexample{The following code shows how arbitrary library exceptions can be caught.,exception}
Since
version 3.0.0
Constructor & Destructor Documentation
exception()
nlohmann::detail::exception::exception (int id_, const char * what_arg) inline protected
: id(id_), m(what_arg) {}
Member Function Documentation
diagnostics()
template<typename BasicJsonType > static std::string nlohmann::detail::exception::diagnostics (const BasicJsonType & leaf_element) inline static protected
    {
#if JSON_DIAGNOSTICS
        std::vector<std::string> tokens;
        for (const auto* current = &leaf_element; current->m_parent != nullptr; current = current->m_parent)
        {
            switch (current->m_parent->type())
            {
                case value_t::array:
                {
                    for (std::size_t i = 0; i < current->m_parent->m_value.array->size(); ++i)
                    {
                        if (&current->m_parent->m_value.array->operator[](i) == current)
{
                            tokens.emplace_back(std::to_string(i));
                            break;
                        }
                    }
                    break;
                }
                case value_t::object:
                {
                    for (const auto& element : *current->m_parent->m_value.object)
                    {
                        if (&element.second == current)
{
                            tokens.emplace_back(element.first.c_str());
                            break;
                        }
                    }
                    break;
                }
                case value_t::null: // LCOV_EXCL_LINE
                case value_t::string: // LCOV_EXCL_LINE
                case value_t::boolean: // LCOV_EXCL_LINE
                case value_t::number_integer: // LCOV_EXCL_LINE
                case value_t::number_unsigned: // LCOV_EXCL_LINE
                case value_t::number_float: // LCOV_EXCL_LINE
                case value_t::binary: // LCOV_EXCL_LINE
                case value_t::discarded: // LCOV_EXCL_LINE
                default:   // LCOV_EXCL_LINE
                    break; // LCOV_EXCL_LINE
            }
        }
        if (tokens.empty())
        {
            return "";
        }
        return "(" + std::accumulate(tokens.rbegin(), tokens.rend(), std::string{},
                                     [](const std::string & a, const std::string & b)
        {
            return a + "/" + detail::escape(b);
        }) + ") ";
#else
        static_cast<void>(leaf_element);
        return "";
#endif
    }
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by nlohmann::detail::parse_error::create(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::type_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::other_error::create(), and nlohmann::detail::parse_error::create().
name()
static std::string nlohmann::detail::exception::name (const std::string & ename, int id_) inline static protected
    {
        return "[json.exception." + ename + "." + std::to_string(id_) + "] ";
    }
Referenced by nlohmann::detail::parse_error::create(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::type_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::other_error::create(), and nlohmann::detail::parse_error::create().
what()
const char * nlohmann::detail::exception::what () const inline override noexcept
returns the explanatory string
    {
        return m.what();
    }
References m.
Referenced by Slic3r::PresetUpdater::priv::get_cached_plugins_version(), Slic3r::get_values_from_json(), Slic3r::get_version_from_json(), Slic3r::GUI::GuideFrame::GetFilamentInfo(), Slic3r::AppConfig::load(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::GUI::GuideFrame::LoadProfileFamily(), and Slic3r::GUI::UpdatePluginDialog::update_info().
Member Data Documentation
id
const int nlohmann::detail::exception::id
the id of the exception
m
std::runtime_error nlohmann::detail::exception::m private
an exception object as storage for error messages
Referenced by what().
The documentation for this class was generated from the following file:
src/nlohmann/detail/exceptions.hpp