OrcaSlicer: ImGuiTextFilter::ImGuiTextRange Struct Reference
ImGuiTextFilter::ImGuiTextRange Struct Reference
#include <src/imgui/imgui.h>
Public Member Functions
ImGuiTextRange ()
ImGuiTextRange (const char *_b, const char *_e)
bool empty () const
IMGUI_API void split (char separator, ImVector< ImGuiTextRange > *out) const
Public Attributes
const char * b
const char * e
Detailed Description
Constructor & Destructor Documentation
ImGuiTextRange() [1/2]
ImGuiTextFilter::ImGuiTextRange::ImGuiTextRange () inline
{ b = e = NULL; }
References NULL.
Referenced by split().
ImGuiTextRange() [2/2]
ImGuiTextFilter::ImGuiTextRange::ImGuiTextRange (const char * _b, const char * _e) inline
{ b = _b; e = _e; }
Member Function Documentation
empty()
bool ImGuiTextFilter::ImGuiTextRange::empty () const inline
{ return b == e; }
Referenced by ImGuiTextFilter::Build(), and ImGuiTextFilter::PassFilter().
split()
void ImGuiTextFilter::ImGuiTextRange::split (char separator, ImVector< ImGuiTextRange > * out) const
{
    out->resize(0);
    const char* wb = b;
    const char* we = wb;
    while (we < e)
    {
        if (*we == separator)
        {
            out->push_back(ImGuiTextRange(wb, we));
            wb = we + 1;
        }
        we++;
    }
    if (wb != we)
        out->push_back(ImGuiTextRange(wb, we));
}
References ImGuiTextRange(), b, e, and out.
Referenced by ImGuiTextFilter::Build().
Member Data Documentation
b
const char* ImGuiTextFilter::ImGuiTextRange::b
Referenced by ImGuiTextFilter::Build(), ImGuiTextFilter::PassFilter(), and split().
e
const char* ImGuiTextFilter::ImGuiTextRange::e
Referenced by ImGuiTextFilter::Build(), ImGuiTextFilter::PassFilter(), and split().
The documentation for this struct was generated from the following files:
src/imgui/imgui.h
src/imgui/imgui.cpp