OrcaSlicer: Slic3r::GUI::HMSQuery Class Reference
Slic3r::GUI::HMSQuery Class Reference
#include <src/slic3r/GUI/HMS.hpp>
Public Member Functions
HMSQuery ()
int check_hms_info ()
wxString query_hms_msg (std::string long_error_code)
wxString query_print_error_msg (int print_error)
Static Public Member Functions
static std::string hms_language_code ()
Protected Member Functions
int download_hms_info ()
int load_from_local (std::string &version_info)
int save_to_local ()
std::string get_hms_file ()
wxString _query_hms_msg (std::string long_error_code, std::string lang_code="en")
wxString _query_error_msg (std::string long_error_code, std::string lang_code="en")
Protected Attributes
json m_hms_json
Detailed Description
Constructor & Destructor Documentation
HMSQuery()
Slic3r::GUI::HMSQuery::HMSQuery () inline
{}
Member Function Documentation
_query_error_msg()
wxString Slic3r::GUI::HMSQuery::_query_error_msg (std::string long_error_code, std::string lang_code = "en") protected
{
    if (m_hms_json.contains("device_error")) {
        if (m_hms_json["device_error"].contains(lang_code)) {
            for (auto item = m_hms_json["device_error"][lang_code].begin(); item != m_hms_json["device_error"][lang_code].end(); item++) {
                if (item->contains("ecode") && boost::to_upper_copy((*item)["ecode"].get<std::string>()) == error_code) {
                    if (item->contains("intro")) {
                        return wxString::FromUTF8((*item)["intro"].get<std::string>());
                    }
                }
            }
            BOOST_LOG_TRIVIAL(info) << "hms: query_error_msg, not found error_code = " << error_code;
        } else {
            BOOST_LOG_TRIVIAL(error) << "hms: query_error_msg, do not contains lang_code = " << lang_code;
            // return first language
            if (!m_hms_json["device_error"].empty()) {
                for (auto lang : m_hms_json["device_error"]) {
                    for (auto item = lang.begin(); item != lang.end(); item++) {
                        if (item->contains("ecode") && boost::to_upper_copy((*item)["ecode"].get<std::string>()) == error_code) {
                            if (item->contains("intro")) {
                                return wxString::FromUTF8((*item)["intro"].get<std::string>());
                            }
                        }
                    }
                }
            }
        }
    }
    else {
        BOOST_LOG_TRIVIAL(info) << "device_error is not exists";
        return wxEmptyString;
    }
    return wxEmptyString;
}
References Slic3r::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), Slic3r::empty(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, and m_hms_json.
Referenced by query_print_error_msg().
_query_hms_msg()
wxString Slic3r::GUI::HMSQuery::_query_hms_msg (std::string long_error_code, std::string lang_code = "en") protected
{
    if (long_error_code.empty())
        return wxEmptyString;
    if (m_hms_json.contains("device_hms")) {
        if (m_hms_json["device_hms"].contains(lang_code)) {
            for (auto item = m_hms_json["device_hms"][lang_code].begin(); item != m_hms_json["device_hms"][lang_code].end(); item++) {
                if (item->contains("ecode")) {
                    std::string temp_string =  (*item)["ecode"].get<std::string>();
                    if (boost::to_upper_copy(temp_string) == long_error_code) {
                        if (item->contains("intro")) {
                            return wxString::FromUTF8((*item)["intro"].get<std::string>());
                        }
                    }
                }
            }
            BOOST_LOG_TRIVIAL(info) << "hms: query_hms_msg, not found error_code = " << long_error_code;
        } else {
            BOOST_LOG_TRIVIAL(error) << "hms: query_hms_msg, do not contains lang_code = " << lang_code;
            // return first language
            if (!m_hms_json["device_hms"].empty()) {
                for (auto lang : m_hms_json["device_hms"]) {
                    for (auto item = lang.begin(); item != lang.end(); item++) {
                        if (item->contains("ecode")) {
                            std::string temp_string = (*item)["ecode"].get<std::string>();
                            if (boost::to_upper_copy(temp_string) == long_error_code) {
                                if (item->contains("intro")) {
                                    return wxString::FromUTF8((*item)["intro"].get<std::string>());
                                }
                            }
                        }
                    }
                }
            }
        }
    } else {
        BOOST_LOG_TRIVIAL(info) << "device_hms is not exists";
        return wxEmptyString;
    }
    return wxEmptyString;
}
References Slic3r::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), Slic3r::empty(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), error, and m_hms_json.
Referenced by query_hms_msg().
check_hms_info()
int Slic3r::GUI::HMSQuery::check_hms_info ()
{
    boost::thread check_thread = boost::thread([this] {
        bool download_new_hms_info = true;
        // load local hms json file
        std::string version = "";
        if (load_from_local(version) == 0) {
            BOOST_LOG_TRIVIAL(info) << "HMS: check_hms_info current version = " << version;
            std::string new_version;
            get_hms_info_version(new_version);
            BOOST_LOG_TRIVIAL(info) << "HMS: check_hms_info latest version = " << new_version;
            if (!version.empty() && version == new_version) {
                download_new_hms_info = false;
            }
        }
        BOOST_LOG_TRIVIAL(info) << "HMS: check_hms_info need download new hms info = " << download_new_hms_info;
        // download if version is update
        if (download_new_hms_info) {
            download_hms_info();
        }
        return;
    });
    return 0;
}
References download_hms_info(), Slic3r::GUI::get_hms_info_version(), and load_from_local().
Referenced by Slic3r::GUI::GUI_App::post_init(), and Slic3r::GUI::GUI_App::recreate_GUI().
download_hms_info()
int Slic3r::GUI::HMSQuery::download_hms_info () protected
{
    AppConfig* config = wxGetApp().app_config;
    if (!config) return -1;
    std::string hms_host = wxGetApp().app_config->get_hms_host();
    std::string lang_code = HMSQuery::hms_language_code();
    std::string url = (boost::format("https://%1%/query.php?lang=%2%") % hms_host % lang_code).str();
    BOOST_LOG_TRIVIAL(info) << "hms: download url = " << url;
    Slic3r::Http http = Slic3r::Http::get(url);
    http.on_complete([this](std::string body, unsigned status) {
        try {
            json j = json::parse(body);
            if (j.contains("result")) {
                if (j["result"] == 0 && j.contains("data")) {
                    this->m_hms_json = j["data"];
                    if (j.contains("ver"))
                        m_hms_json["version"] = std::to_string(j["ver"].get<long long>());
                } else {
                    this->m_hms_json.clear();
                    BOOST_LOG_TRIVIAL(info) << "HMSQuery: update hms info error = " << j["result"].get<int>();
                }
            }
        } catch (...) {
            ;
        }
        })
        .timeout_max(20)
        .on_error([](std::string body, std::string error, unsigned status) {
            BOOST_LOG_TRIVIAL(error) << "HMSQuery: update hms info error = " << error << ", body = " << body << ", status = " << status;
        }).perform_sync();
    save_to_local();
    return 0;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::clear(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), error, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::Http::get(), Slic3r::AppConfig::get_hms_host(), hms_language_code(), m_hms_json, Slic3r::Http::on_complete(), Slic3r::Http::on_error(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), and save_to_local().
Referenced by check_hms_info().
get_hms_file()
std::string Slic3r::GUI::HMSQuery::get_hms_file () protected
{
    std::string lang_code = HMSQuery::hms_language_code();
    return (boost::format("hms_%1%.json") % lang_code).str();
}
References hms_language_code().
Referenced by load_from_local(), and save_to_local().
hms_language_code()
std::string Slic3r::GUI::HMSQuery::hms_language_code () static
{
    AppConfig* config = wxGetApp().app_config;
    if (!config)
        // set language code to en by default
        return "en";
    std::string lang_code = wxGetApp().app_config->get_language_code();
    if (lang_code.empty()) {
        // set language code to en by default
        return "en";
    }
    return lang_code;
}
References Slic3r::AppConfig::get_language_code().
Referenced by download_hms_info(), get_hms_file(), Slic3r::GUI::get_hms_wiki_url(), query_hms_msg(), and query_print_error_msg().
load_from_local()
int Slic3r::GUI::HMSQuery::load_from_local (std::string & version_info) protected
{
    if (data_dir().empty()) {
        version_info = "";
        BOOST_LOG_TRIVIAL(error) << "HMS: load_from_local, data_dir() is empty";
        return -1;
    }
    std::string filename = get_hms_file();
    auto hms_folder = (boost::filesystem::path(data_dir()) / "hms");
    if (!fs::exists(hms_folder))
        fs::create_directory(hms_folder);
    std::string dir_str = (hms_folder / filename).make_preferred().string();
    std::ifstream json_file(encode_path(dir_str.c_str()));
    try {
        if (json_file.is_open()) {
            json_file >> m_hms_json;
            if (m_hms_json.contains("version")) {
                version_info = m_hms_json["version"].get<std::string>();
                return 0;
            } else {
                BOOST_LOG_TRIVIAL(warning) << "HMS: load_from_local, no version info";
                return 0;
            }
        }
    } catch(...) {
        version_info = "";
        BOOST_LOG_TRIVIAL(error) << "HMS: load_from_local failed";
        return -1;
    }
    version_info = "";
    return 0;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), Slic3r::data_dir(), Slic3r::empty(), Slic3r::encode_path(), error, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), get_hms_file(), and m_hms_json.
Referenced by check_hms_info().
query_hms_msg()
wxString Slic3r::GUI::HMSQuery::query_hms_msg (std::string long_error_code)
{
    AppConfig* config = wxGetApp().app_config;
    if (!config) return wxEmptyString;
    std::string lang_code = HMSQuery::hms_language_code();
    return _query_hms_msg(long_error_code, lang_code);
}
References _query_hms_msg(), and hms_language_code().
query_print_error_msg()
wxString Slic3r::GUI::HMSQuery::query_print_error_msg (int print_error)
{
    char buf[32];
    ::sprintf(buf, "%08X", print_error);
    std::string lang_code = HMSQuery::hms_language_code();
    return _query_error_msg(std::string(buf), lang_code);
}
References _query_error_msg(), and hms_language_code().
save_to_local()
int Slic3r::GUI::HMSQuery::save_to_local () protected
{
    if (data_dir().empty()) {
        BOOST_LOG_TRIVIAL(error) << "HMS: save_to_local, data_dir() is empty";
        return -1;
    }
    std::string filename = get_hms_file();
    auto hms_folder = (boost::filesystem::path(data_dir()) / "hms");
    if (!fs::exists(hms_folder))
        fs::create_directory(hms_folder);
    std::string dir_str = (hms_folder / filename).make_preferred().string();
    std::ofstream json_file(encode_path(dir_str.c_str()));
    if (json_file.is_open()) {
        json_file << std::setw(4) << m_hms_json << std::endl;
        json_file.close();
        return 0;
    }
    BOOST_LOG_TRIVIAL(error) << "HMS: save_to_local failed";
    return -1;
}
References Slic3r::data_dir(), Slic3r::empty(), Slic3r::encode_path(), error, get_hms_file(), and m_hms_json.
Referenced by download_hms_info().
Member Data Documentation
m_hms_json
json Slic3r::GUI::HMSQuery::m_hms_json protected
Referenced by _query_error_msg(), _query_hms_msg(), download_hms_info(), load_from_local(), and save_to_local().
The documentation for this class was generated from the following files:
src/slic3r/GUI/HMS.hpp
src/slic3r/GUI/HMS.cpp