OrcaSlicer: Slic3r::_BBS_3MF_Importer::ObjectImporter Struct Reference
Slic3r::_BBS_3MF_Importer::ObjectImporter Struct Reference
Public Member Functions
ObjectImporter (_BBS_3MF_Importer *importer, std::string file_path, std::string obj_path)
~ObjectImporter ()
void _destroy_object_xml_parser ()
void _stop_object_xml_parser (const std::string &msg=std::string())
bool object_parse_error () const
const char * object_parse_error_message () const
bool _extract_object_from_archive (mz_zip_archive &archive, const mz_zip_archive_file_stat &stat)
bool extract_object_model ()
bool _handle_object_start_model (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_model ()
bool _handle_object_start_resources (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_resources ()
bool _handle_object_start_object (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_object ()
bool _handle_object_start_color_group (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_color_group ()
bool _handle_object_start_color (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_color ()
bool _handle_object_start_mesh (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_mesh ()
bool _handle_object_start_vertices (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_vertices ()
bool _handle_object_start_vertex (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_vertex ()
bool _handle_object_start_triangles (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_triangles ()
bool _handle_object_start_triangle (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_triangle ()
bool _handle_object_start_components (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_components ()
bool _handle_object_start_component (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_component ()
bool _handle_object_start_metadata (const char **attributes, unsigned int num_attributes)
bool _handle_object_end_metadata ()
void _handle_object_start_model_xml_element (const char *name, const char **attributes)
void _handle_object_end_model_xml_element (const char *name)
void _handle_object_xml_characters (const XML_Char *s, int len)
Static Public Member Functions
static void XMLCALL _handle_object_start_model_xml_element (void *userData, const char *name, const char **attributes)
static void XMLCALL _handle_object_end_model_xml_element (void *userData, const char *name)
static void XMLCALL _handle_object_xml_characters (void *userData, const XML_Char *s, int len)
Public Attributes
IdToCurrentObjectMap object_list
CurrentObject * current_object {nullptr}
std::string object_path
std::string zip_path
_BBS_3MF_Importer * top_importer {nullptr}
XML_Parser object_xml_parser
bool obj_parse_error { false }
std::string obj_parse_error_message
std::string obj_curr_metadata_name
std::string obj_curr_characters
float object_unit_factor
int object_current_color_group {-1}
std::map< int, std::string > object_group_id_to_color
bool is_bbl_3mf { false }
Detailed Description
Constructor & Destructor Documentation
ObjectImporter()
Slic3r::_BBS_3MF_Importer::ObjectImporter::ObjectImporter (_BBS_3MF_Importer * importer, std::string file_path, std::string obj_path) inline
            {
                top_importer = importer;
                object_path = obj_path;
                zip_path = file_path;
            }
References object_path, top_importer, and zip_path.
~ObjectImporter()
Slic3r::_BBS_3MF_Importer::ObjectImporter::~ObjectImporter () inline
            {
                _destroy_object_xml_parser();
            }
References _destroy_object_xml_parser().
Member Function Documentation
_destroy_object_xml_parser()
void Slic3r::_BBS_3MF_Importer::ObjectImporter::_destroy_object_xml_parser () inline
            {
                if (object_xml_parser != nullptr) {
                    XML_ParserFree(object_xml_parser);
                    object_xml_parser = nullptr;
                }
            }
References object_xml_parser, and XML_ParserFree().
Referenced by ~ObjectImporter().
_extract_object_from_archive()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_extract_object_from_archive (mz_zip_archive & archive, const mz_zip_archive_file_stat & stat)
    {
        if (stat.m_uncomp_size == 0) {
            top_importer->add_error("Found invalid size for "+object_path);
            return false;
        }
        object_xml_parser = XML_ParserCreate(nullptr);
        if (object_xml_parser == nullptr) {
            top_importer->add_error("Unable to create parser for "+object_path);
            return false;
        }
        XML_SetUserData(object_xml_parser, (void*)this);
        XML_SetElementHandler(object_xml_parser, _BBS_3MF_Importer::ObjectImporter::_handle_object_start_model_xml_element, _BBS_3MF_Importer::ObjectImporter::_handle_object_end_model_xml_element);
        XML_SetCharacterDataHandler(object_xml_parser, _BBS_3MF_Importer::ObjectImporter::_handle_object_xml_characters);
        struct CallbackData
        {
            XML_Parser& parser;
            _BBS_3MF_Importer::ObjectImporter& importer;
            const mz_zip_archive_file_stat& stat;
            CallbackData(XML_Parser& parser, _BBS_3MF_Importer::ObjectImporter& importer, const mz_zip_archive_file_stat& stat) : parser(parser), importer(importer), stat(stat) {}
        };
        CallbackData data(object_xml_parser, *this, stat);
        mz_bool res = 0;
        try
        {
            mz_file_write_func callback = [](void* pOpaque, mz_uint64 file_ofs, const void* pBuf, size_t n)->size_t {
                CallbackData* data = (CallbackData*)pOpaque;
                if (!XML_Parse(data->parser, (const char*)pBuf, (int)n, (file_ofs + n == data->stat.m_uncomp_size) ? 1 : 0) || data->importer.object_parse_error()) {
                    char error_buf[1024];
                    ::sprintf(error_buf, "Error (%s) while parsing '%s' at line %d", data->importer.object_parse_error_message(), data->stat.m_filename, (int)XML_GetCurrentLineNumber(data->parser));
                    throw Slic3r::FileIOError(error_buf);
                }
                return n;
            };
            void* opaque = &data;
            res = mz_zip_reader_extract_to_callback(&archive, stat.m_file_index, callback, opaque, 0);
        }
        catch (const version_error& e)
        {
            // rethrow the exception
            std::string error_message = std::string(e.what()) + " for " + object_path;
            throw Slic3r::FileIOError(error_message);
        }
        catch (std::exception& e)
        {
            std::string error_message = std::string(e.what()) + " for " + object_path;
            top_importer->add_error(error_message);
            return false;
        }
        if (res == 0) {
            top_importer->add_error("Error while extracting model data from zip archive for "+object_path);
            return false;
        }
        return true;
    }
References int, mz_zip_archive_file_stat::m_file_index, mz_zip_archive_file_stat::m_uncomp_size, mz_zip_reader_extract_to_callback(), n, XML_GetCurrentLineNumber(), XML_Parse(), XML_ParserCreate(), XML_SetCharacterDataHandler(), XML_SetElementHandler(), and XML_SetUserData().
_handle_object_end_color()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_color ()
    {
        // do nothing
        return true;
    }
_handle_object_end_color_group()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_color_group ()
    {
        // do nothing
        return true;
    }
_handle_object_end_component()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_component ()
    {
        // do nothing
        return true;
    }
_handle_object_end_components()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_components ()
    {
        // do nothing
        return true;
    }
_handle_object_end_mesh()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_mesh ()
    {
        // do nothing
        return true;
    }
_handle_object_end_metadata()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_metadata ()
    {
        if ((obj_curr_metadata_name == BBS_3MF_VERSION)||(obj_curr_metadata_name == BBS_3MF_VERSION1)) {
            is_bbl_3mf = true;
        }
        return true;
    }
References BBS_3MF_VERSION, and BBS_3MF_VERSION1.
_handle_object_end_model()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_model ()
    {
        // do nothing
        return true;
    }
_handle_object_end_model_xml_element() [1/2]
void Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_model_xml_element (const char * name)
    {
        if (object_xml_parser == nullptr)
            return;
        bool res = true;
        if (::strcmp(MODEL_TAG, name) == 0)
            res = _handle_object_end_model();
        else if (::strcmp(RESOURCES_TAG, name) == 0)
            res = _handle_object_end_resources();
        else if (::strcmp(OBJECT_TAG, name) == 0)
            res = _handle_object_end_object();
        else if (::strcmp(COLOR_GROUP_TAG, name) == 0)
            res = _handle_object_end_color_group();
        else if (::strcmp(COLOR_TAG, name) == 0)
            res = _handle_object_end_color();
        else if (::strcmp(MESH_TAG, name) == 0)
            res = _handle_object_end_mesh();
        else if (::strcmp(VERTICES_TAG, name) == 0)
            res = _handle_object_end_vertices();
        else if (::strcmp(VERTEX_TAG, name) == 0)
            res = _handle_object_end_vertex();
        else if (::strcmp(TRIANGLES_TAG, name) == 0)
            res = _handle_object_end_triangles();
        else if (::strcmp(TRIANGLE_TAG, name) == 0)
            res = _handle_object_end_triangle();
        else if (::strcmp(COMPONENTS_TAG, name) == 0)
            res = _handle_object_end_components();
        else if (::strcmp(COMPONENT_TAG, name) == 0)
            res = _handle_object_end_component();
        else if (::strcmp(METADATA_TAG, name) == 0)
            res = _handle_object_end_metadata();
        if (!res)
            _stop_object_xml_parser();
    }
References COLOR_GROUP_TAG, COLOR_TAG, COMPONENT_TAG, COMPONENTS_TAG, MESH_TAG, METADATA_TAG, MODEL_TAG, OBJECT_TAG, RESOURCES_TAG, TRIANGLE_TAG, TRIANGLES_TAG, VERTEX_TAG, and VERTICES_TAG.
Referenced by _handle_object_end_model_xml_element().
_handle_object_end_model_xml_element() [2/2]
void XMLCALL Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_model_xml_element (void * userData, const char * name) static
    {
        ObjectImporter* importer = (ObjectImporter*)userData;
        if (importer != nullptr)
            importer->_handle_object_end_model_xml_element(name);
    }
References _handle_object_end_model_xml_element(), and userData.
_handle_object_end_object()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_object ()
    {
        if (!current_object || (current_object->id == -1)) {
            top_importer->add_error("Found invalid object for "+ object_path);
            return false;
        }
        else {
            if (is_bbl_3mf && boost::ends_with(current_object->uuid, OBJECT_UUID_SUFFIX) && top_importer->m_load_restore) {
                std::istringstream iss(current_object->uuid);
                int backup_id;
                bool need_replace = false;
                if (iss >> std::hex >> backup_id) {
                    need_replace = (current_object->id != backup_id);
                    current_object->id = backup_id;
                }
                //if (need_replace)
                {
                    for (int index = 0; index < current_object->components.size(); index++)
                    {
                        int temp_id = (index + 1) << 16 | backup_id;
                        Component& component = current_object->components[index];
                        std::string new_path = component.object_id.first;
                        Id new_id = std::make_pair(new_path, temp_id);
                        IdToCurrentObjectMap::iterator object_it = object_list.find(component.object_id);
                        if (object_it != object_list.end()) {
                            CurrentObject new_object;
                            new_object.geometry = std::move(object_it->second.geometry);
                            new_object.id = temp_id;
                            new_object.model_object_idx = object_it->second.model_object_idx;
                            new_object.name = object_it->second.name;
                            new_object.uuid = object_it->second.uuid;
                            object_list.erase(object_it);
                            object_list.insert({ new_id, std::move(new_object) });
                        }
                        else {
                            top_importer->add_error("can not find object for component, id=" + std::to_string(component.object_id.second));
                            delete current_object;
                            current_object = nullptr;
                            return false;
                        }
                        component.object_id.second = temp_id;
                    }
                }
            }
            Id id = std::make_pair(object_path, current_object->id);
            if (object_list.find(id) == object_list.end()) {
                object_list.insert({ id, std::move(*current_object) });
                delete current_object;
                current_object = nullptr;
            }
            else {
                top_importer->add_error("Found object with duplicate id for "+object_path);
                delete current_object;
                current_object = nullptr;
                return false;
            }
        }
        return true;
    }
References Slic3r::_BBS_3MF_Importer::CurrentObject::geometry, Slic3r::_BBS_3MF_Importer::CurrentObject::id, Slic3r::_BBS_3MF_Importer::CurrentObject::model_object_idx, Slic3r::_BBS_3MF_Importer::CurrentObject::name, Slic3r::_BBS_3MF_Importer::Component::object_id, OBJECT_UUID_SUFFIX, and Slic3r::_BBS_3MF_Importer::CurrentObject::uuid.
_handle_object_end_resources()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_resources ()
    {
        // do nothing
        return true;
    }
_handle_object_end_triangle()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_triangle ()
    {
        // do nothing
        return true;
    }
_handle_object_end_triangles()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_triangles ()
    {
        // do nothing
        return true;
    }
_handle_object_end_vertex()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_vertex ()
    {
        // do nothing
        return true;
    }
_handle_object_end_vertices()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_end_vertices ()
    {
        // do nothing
        return true;
    }
_handle_object_start_color()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_color (const char ** attributes, unsigned int num_attributes)
    {
        std::string color = bbs_get_attribute_value_string(attributes, num_attributes, COLOR_ATTR);
        object_group_id_to_color[object_current_color_group] = color;
        return true;
    }
References bbs_get_attribute_value_string(), and COLOR_ATTR.
_handle_object_start_color_group()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_color_group (const char ** attributes, unsigned int num_attributes)
    {
        object_current_color_group = bbs_get_attribute_value_int(attributes, num_attributes, ID_ATTR);
        return true;
    }
References bbs_get_attribute_value_int(), and ID_ATTR.
_handle_object_start_component()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_component (const char ** attributes, unsigned int num_attributes)
    {
        int object_id = bbs_get_attribute_value_int(attributes, num_attributes, OBJECTID_ATTR);
        Transform3d transform = bbs_get_transform_from_3mf_specs_string(bbs_get_attribute_value_string(attributes, num_attributes, TRANSFORM_ATTR));
        /*Id id = std::make_pair(m_sub_model_path, object_id);
        IdToModelObjectMap::iterator object_item = m_objects.find(id);
        if (object_item == m_objects.end()) {
            IdToAliasesMap::iterator alias_item = m_objects_aliases.find(id);
            if (alias_item == m_objects_aliases.end()) {
                add_error("Found component with invalid object id");
                return false;
            }
        }*/
        if (current_object) {
            Id id = std::make_pair(object_path, object_id);
            current_object->components.emplace_back(id, transform);
        }
        return true;
    }
References bbs_get_attribute_value_int(), bbs_get_attribute_value_string(), bbs_get_transform_from_3mf_specs_string(), OBJECTID_ATTR, Slic3r::transform(), and TRANSFORM_ATTR.
_handle_object_start_components()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_components (const char ** attributes, unsigned int num_attributes)
    {
        // reset current components
        if (current_object)
            current_object->components.clear();
        return true;
    }
_handle_object_start_mesh()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_mesh (const char ** attributes, unsigned int num_attributes)
    {
        // reset current geometry
        if (current_object)
            current_object->geometry.reset();
        return true;
    }
_handle_object_start_metadata()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_metadata (const char ** attributes, unsigned int num_attributes)
    {
        obj_curr_metadata_name.clear();
        std::string name = bbs_get_attribute_value_string(attributes, num_attributes, NAME_ATTR);
        if (!name.empty()) {
            obj_curr_metadata_name = name;
        }
        return true;
    }
References bbs_get_attribute_value_string(), and NAME_ATTR.
_handle_object_start_model()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_model (const char ** attributes, unsigned int num_attributes)
    {
        object_unit_factor = bbs_get_unit_factor(bbs_get_attribute_value_string(attributes, num_attributes, UNIT_ATTR));
        return true;
    }
References bbs_get_attribute_value_string(), bbs_get_unit_factor(), and UNIT_ATTR.
_handle_object_start_model_xml_element() [1/2]
void Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_model_xml_element (const char * name, const char ** attributes)
    {
        if (object_xml_parser == nullptr)
            return;
        bool res = true;
        unsigned int num_attributes = (unsigned int)XML_GetSpecifiedAttributeCount(object_xml_parser);
        if (::strcmp(MODEL_TAG, name) == 0)
            res = _handle_object_start_model(attributes, num_attributes);
        else if (::strcmp(RESOURCES_TAG, name) == 0)
            res = _handle_object_start_resources(attributes, num_attributes);
        else if (::strcmp(OBJECT_TAG, name) == 0)
            res = _handle_object_start_object(attributes, num_attributes);
        else if (::strcmp(COLOR_GROUP_TAG, name) == 0)
            res = _handle_object_start_color_group(attributes, num_attributes);
        else if (::strcmp(COLOR_TAG, name) == 0)
            res = _handle_object_start_color(attributes, num_attributes);
        else if (::strcmp(MESH_TAG, name) == 0)
            res = _handle_object_start_mesh(attributes, num_attributes);
        else if (::strcmp(VERTICES_TAG, name) == 0)
            res = _handle_object_start_vertices(attributes, num_attributes);
        else if (::strcmp(VERTEX_TAG, name) == 0)
            res = _handle_object_start_vertex(attributes, num_attributes);
        else if (::strcmp(TRIANGLES_TAG, name) == 0)
            res = _handle_object_start_triangles(attributes, num_attributes);
        else if (::strcmp(TRIANGLE_TAG, name) == 0)
            res = _handle_object_start_triangle(attributes, num_attributes);
        else if (::strcmp(COMPONENTS_TAG, name) == 0)
            res = _handle_object_start_components(attributes, num_attributes);
        else if (::strcmp(COMPONENT_TAG, name) == 0)
            res = _handle_object_start_component(attributes, num_attributes);
        else if (::strcmp(METADATA_TAG, name) == 0)
            res = _handle_object_start_metadata(attributes, num_attributes);
        if (!res)
            _stop_object_xml_parser();
    }
References COLOR_GROUP_TAG, COLOR_TAG, COMPONENT_TAG, COMPONENTS_TAG, int, MESH_TAG, METADATA_TAG, MODEL_TAG, OBJECT_TAG, RESOURCES_TAG, TRIANGLE_TAG, TRIANGLES_TAG, VERTEX_TAG, VERTICES_TAG, and XML_GetSpecifiedAttributeCount().
Referenced by _handle_object_start_model_xml_element().
_handle_object_start_model_xml_element() [2/2]
void XMLCALL Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_model_xml_element (void * userData, const char * name, const char ** attributes) static
    {
        ObjectImporter* importer = (ObjectImporter*)userData;
        if (importer != nullptr)
            importer->_handle_object_start_model_xml_element(name, attributes);
    }
References _handle_object_start_model_xml_element(), and userData.
_handle_object_start_object()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_object (const char ** attributes, unsigned int num_attributes)
    {
        // reset current object data
        if (current_object) {
            delete current_object;
            current_object = nullptr;
        }
        std::string object_type = bbs_get_attribute_value_string(attributes, num_attributes, TYPE_ATTR);
        if (bbs_is_valid_object_type(object_type)) {
            if (!current_object) {
                current_object = new CurrentObject();
            }
            current_object->id = bbs_get_attribute_value_int(attributes, num_attributes, ID_ATTR);
            current_object->name = bbs_get_attribute_value_string(attributes, num_attributes, NAME_ATTR);
            current_object->uuid = bbs_get_attribute_value_string(attributes, num_attributes, PUUID_ATTR);
            current_object->pid = bbs_get_attribute_value_int(attributes, num_attributes, PID_ATTR);
        }
        return true;
    }
References bbs_get_attribute_value_int(), bbs_get_attribute_value_string(), bbs_is_valid_object_type(), ID_ATTR, NAME_ATTR, PID_ATTR, PUUID_ATTR, and TYPE_ATTR.
_handle_object_start_resources()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_resources (const char ** attributes, unsigned int num_attributes)
    {
        // do nothing
        return true;
    }
_handle_object_start_triangle()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_triangle (const char ** attributes, unsigned int num_attributes)
    {
        // we are ignoring the following attributes:
        // p1
        // p2
        // p3
        // pid
        // see specifications
        // appends the triangle's vertices indices
        // missing values are set equal to ZERO
        if (current_object) {
            current_object->geometry.triangles.emplace_back(
                bbs_get_attribute_value_int(attributes, num_attributes, V1_ATTR),
                bbs_get_attribute_value_int(attributes, num_attributes, V2_ATTR),
                bbs_get_attribute_value_int(attributes, num_attributes, V3_ATTR));
            current_object->geometry.custom_supports.push_back(bbs_get_attribute_value_string(attributes, num_attributes, CUSTOM_SUPPORTS_ATTR));
            current_object->geometry.custom_seam.push_back(bbs_get_attribute_value_string(attributes, num_attributes, CUSTOM_SEAM_ATTR));
            current_object->geometry.mmu_segmentation.push_back(bbs_get_attribute_value_string(attributes, num_attributes, MMU_SEGMENTATION_ATTR));
            // BBS
            current_object->geometry.face_properties.push_back(bbs_get_attribute_value_string(attributes, num_attributes, FACE_PROPERTY_ATTR));
        }
        return true;
    }
References bbs_get_attribute_value_int(), bbs_get_attribute_value_string(), CUSTOM_SEAM_ATTR, CUSTOM_SUPPORTS_ATTR, FACE_PROPERTY_ATTR, MMU_SEGMENTATION_ATTR, V1_ATTR, V2_ATTR, and V3_ATTR.
_handle_object_start_triangles()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_triangles (const char ** attributes, unsigned int num_attributes)
    {
        // reset current triangles
        if (current_object)
            current_object->geometry.triangles.clear();
        return true;
    }
_handle_object_start_vertex()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_vertex (const char ** attributes, unsigned int num_attributes)
    {
        // appends the vertex coordinates
        // missing values are set equal to ZERO
        if (current_object)
            current_object->geometry.vertices.emplace_back(
                object_unit_factor * bbs_get_attribute_value_float(attributes, num_attributes, X_ATTR),
                object_unit_factor * bbs_get_attribute_value_float(attributes, num_attributes, Y_ATTR),
                object_unit_factor * bbs_get_attribute_value_float(attributes, num_attributes, Z_ATTR));
        return true;
    }
References bbs_get_attribute_value_float(), X_ATTR, Y_ATTR, and Z_ATTR.
_handle_object_start_vertices()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_vertices (const char ** attributes, unsigned int num_attributes)
    {
        // reset current vertices
        if (current_object)
            current_object->geometry.vertices.clear();
        return true;
    }
_handle_object_xml_characters() [1/2]
void Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_xml_characters (const XML_Char * s, int len)
    {
        obj_curr_characters.append(s, len);
    }
Referenced by _handle_object_xml_characters().
_handle_object_xml_characters() [2/2]
void XMLCALL Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_xml_characters (void * userData, const XML_Char * s, int len) static
    {
        ObjectImporter* importer = (ObjectImporter*)userData;
        if (importer != nullptr)
            importer->_handle_object_xml_characters(s, len);
    }
References _handle_object_xml_characters(), and userData.
_stop_object_xml_parser()
void Slic3r::_BBS_3MF_Importer::ObjectImporter::_stop_object_xml_parser (const std::string & msg = std::string()) inline
            {
                assert(! obj_parse_error);
                assert(obj_parse_error_message.empty());
                assert(object_xml_parser != nullptr);
                obj_parse_error = true;
                obj_parse_error_message = msg;
                XML_StopParser(object_xml_parser, false);
            }
References obj_parse_error, obj_parse_error_message, object_xml_parser, and XML_StopParser().
extract_object_model()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::extract_object_model () inline
            {
                mz_zip_archive archive;
                mz_zip_archive_file_stat stat;
                mz_zip_zero_struct(&archive);
                if (!open_zip_reader(&archive, zip_path)) {
                    top_importer->add_error("Unable to open the zipfile "+ zip_path);
                    return false;
                }
                if (!top_importer->_extract_from_archive(archive, object_path, [this] (mz_zip_archive& archive, const mz_zip_archive_file_stat& stat) {
                    return _extract_object_from_archive(archive, stat);
                }, top_importer->m_load_restore)) {
                    std::string error_msg = std::string("Archive does not contain a valid model for ") + object_path;
                    top_importer->add_error(error_msg);
                    close_zip_reader(&archive);
                    return false;
                }
                close_zip_reader(&archive);
                if (obj_parse_error) {
                    //already add_error inside
                    //top_importer->add_error(object_parse_error_message());
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ":" << __LINE__ << boost::format(", Found error while extrace object %1%\n")%object_path;
                    return false;
                }
                return true;
            }
References Slic3r::_BBS_3MF_Importer::_extract_from_archive(), Slic3r::_BBS_3MF_Base::add_error(), Slic3r::close_zip_reader(), error, Slic3r::_BBS_3MF_Importer::m_load_restore, mz_zip_zero_struct(), obj_parse_error, object_path, Slic3r::open_zip_reader(), top_importer, and zip_path.
object_parse_error()
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::object_parse_error () const inline
{ return obj_parse_error; }
References obj_parse_error.
object_parse_error_message()
const char * Slic3r::_BBS_3MF_Importer::ObjectImporter::object_parse_error_message () const inline
{
                return obj_parse_error ?
                    // The error was signalled by the user code, not the expat parser.
                    (obj_parse_error_message.empty() ? "Invalid 3MF format" : obj_parse_error_message.c_str()) :
                    // The error was signalled by the expat parser.
                    XML_ErrorString(XML_GetErrorCode(object_xml_parser));
            }
References obj_parse_error, obj_parse_error_message, object_xml_parser, XML_ErrorString(), and XML_GetErrorCode().
Member Data Documentation
current_object
CurrentObject* Slic3r::_BBS_3MF_Importer::ObjectImporter::current_object {nullptr}
is_bbl_3mf
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::is_bbl_3mf { false }
obj_curr_characters
std::string Slic3r::_BBS_3MF_Importer::ObjectImporter::obj_curr_characters
obj_curr_metadata_name
std::string Slic3r::_BBS_3MF_Importer::ObjectImporter::obj_curr_metadata_name
obj_parse_error
bool Slic3r::_BBS_3MF_Importer::ObjectImporter::obj_parse_error { false }
Referenced by _stop_object_xml_parser(), extract_object_model(), object_parse_error(), and object_parse_error_message().
obj_parse_error_message
std::string Slic3r::_BBS_3MF_Importer::ObjectImporter::obj_parse_error_message
Referenced by _stop_object_xml_parser(), and object_parse_error_message().
object_current_color_group
int Slic3r::_BBS_3MF_Importer::ObjectImporter::object_current_color_group {-1}
object_group_id_to_color
std::map<int, std::string> Slic3r::_BBS_3MF_Importer::ObjectImporter::object_group_id_to_color
object_list
IdToCurrentObjectMap Slic3r::_BBS_3MF_Importer::ObjectImporter::object_list
object_path
std::string Slic3r::_BBS_3MF_Importer::ObjectImporter::object_path
Referenced by ObjectImporter(), and extract_object_model().
object_unit_factor
float Slic3r::_BBS_3MF_Importer::ObjectImporter::object_unit_factor
object_xml_parser
XML_Parser Slic3r::_BBS_3MF_Importer::ObjectImporter::object_xml_parser
Referenced by _destroy_object_xml_parser(), _stop_object_xml_parser(), and object_parse_error_message().
top_importer
_BBS_3MF_Importer* Slic3r::_BBS_3MF_Importer::ObjectImporter::top_importer {nullptr}
Referenced by ObjectImporter(), and extract_object_model().
zip_path
std::string Slic3r::_BBS_3MF_Importer::ObjectImporter::zip_path
Referenced by ObjectImporter(), and extract_object_model().
The documentation for this struct was generated from the following file:
src/libslic3r/Format/bbs_3mf.cpp