OrcaSlicer: orgQhull::RoadTest Class Reference
orgQhull::RoadTest Class Reference
#include <src/qhull/src/qhulltest/RoadTest.h>
Public Slots
Test slots
! List of failed tests
void cleanup ()
Executed after each test.
Public Member Functions
Constructors, etc.
RoadTest ()
virtual ~RoadTest ()
Helper
void recordFailedTest ()
Static Public Member Functions
Class functions
static void deleteTests ()
static int runTests (QStringList arguments)
Static Protected Attributes
Class globals
static QList< RoadTest * > s_testcases
static int s_test_count = 0
! List of testcases to execute. Initialized via add_...()
static int s_test_fail = 0
! Total number of tests executed
static QStringList s_failed_tests
! Number of failed tests
Detailed Description
Constructor & Destructor Documentation
RoadTest()
orgQhull::RoadTest::RoadTest () inline
{ s_testcases.append(this); }
References s_testcases.
~RoadTest()
virtual orgQhull::RoadTest::~RoadTest () inline virtual
{} // Derived from QObject
Member Function Documentation
cleanup
void orgQhull::RoadTest::cleanup () slot
Executed after each test.
{
    s_test_count++;
    if(QTest::currentTestFailed()){
        recordFailedTest();
    }
}//cleanup
References recordFailedTest(), and s_test_count.
Referenced by orgQhull::Qhull_test::cleanup(), orgQhull::QhullFacet_test::cleanup(), orgQhull::QhullFacetList_test::cleanup(), orgQhull::QhullFacetSet_test::cleanup(), orgQhull::QhullHyperplane_test::cleanup(), orgQhull::QhullLinkedList_test::cleanup(), orgQhull::QhullPoint_test::cleanup(), orgQhull::QhullPoints_test::cleanup(), orgQhull::QhullPointSet_test::cleanup(), orgQhull::QhullRidge_test::cleanup(), orgQhull::QhullSet_test::cleanup(), orgQhull::QhullVertex_test::cleanup(), and orgQhull::QhullVertexSet_test::cleanup().
deleteTests()
void orgQhull::RoadTest::deleteTests () static
{
    foreach(RoadTest *testcase, s_testcases){
        delete testcase;
    }
    s_failed_tests.clear();
}
References s_failed_tests, and s_testcases.
Referenced by orgQhull::main().
recordFailedTest()
void orgQhull::RoadTest::recordFailedTest ()
{
    s_test_fail++;
    QString className= metaObject()->className();
    s_failed_tests << className + "::" + QTest::currentTestFunction();
}
References s_failed_tests, and s_test_fail.
Referenced by cleanup(), and runTests().
runTests()
int orgQhull::RoadTest::runTests (QStringList arguments) static
{
    int result= 0; // assume success
    foreach(RoadTest *testcase, s_testcases){
        try{
            result += QTest::qExec(testcase, arguments);
        }catch(const std::exception &e){
            cout << "FAIL!  : Threw error ";
            cout << e.what() << endl;
    s_test_count++;
            testcase->recordFailedTest();
            // Qt 4.5.2 OK.  In Qt 4.3.3, qtestcase did not clear currentTestObject
        }
    }
    if(s_test_fail){
        cout << "Failed " << s_test_fail << " of " << s_test_count << " tests.\n";
        cout << s_failed_tests.join("\n").toLocal8Bit().constData() << std::endl;
    }else{
        cout << "Passed " << s_test_count << " tests.\n";
    }
    return result;
}//runTests
References recordFailedTest(), s_failed_tests, s_test_count, s_test_fail, and s_testcases.
Referenced by orgQhull::main().
Member Data Documentation
s_failed_tests
QStringList orgQhull::RoadTest::s_failed_tests static protected
! Number of failed tests
Referenced by deleteTests(), recordFailedTest(), and runTests().
s_test_count
int orgQhull::RoadTest::s_test_count = 0 static protected
! List of testcases to execute. Initialized via add_...()
Referenced by cleanup(), and runTests().
s_test_fail
int orgQhull::RoadTest::s_test_fail = 0 static protected
! Total number of tests executed
Referenced by recordFailedTest(), and runTests().
s_testcases
QList< RoadTest * > orgQhull::RoadTest::s_testcases static protected
Referenced by RoadTest(), deleteTests(), and runTests().
The documentation for this class was generated from the following files:
src/qhull/src/qhulltest/RoadTest.h
src/qhull/src/qhulltest/RoadTest.cpp