OrcaSlicer: Slic3r::GUI::http_headers Class Reference
Slic3r::GUI::http_headers Class Reference
#include <src/slic3r/GUI/HttpServer.hpp>
Public Member Functions
std::string get_response ()
int content_length ()
void on_read_header (std::string line)
void on_read_request_line (std::string line)
Private Attributes
std::string method
std::string url
std::string version
std::map< std::string, std::string > headers
Detailed Description
Member Function Documentation
content_length()
int Slic3r::GUI::http_headers::content_length () inline
    {
        auto request = headers.find("content-length");
        if (request != headers.end())
        {
            std::stringstream ssLength(request->second);
            int content_length;
            ssLength >> content_length;
            return content_length;
        }
        return 0;
    }
References content_length(), and headers.
Referenced by content_length().
get_response()
std::string Slic3r::GUI::http_headers::get_response ()
{
    BOOST_LOG_TRIVIAL(info) << "thirdparty_login: get_response";
    std::stringstream ssOut;
    std::string url_str = Http::url_decode(url);
    if (boost::contains(url_str, "access_token")) {
        std::string sHTML = "<html><body><p>redirect to url </p></body></html>";
        std::string redirect_url = parse_params(url_str, "redirect_url");
        std::string access_token = parse_params(url_str, "access_token");
        std::string refresh_token = parse_params(url_str, "refresh_token");
        std::string expires_in_str = parse_params(url_str, "expires_in");
        std::string refresh_expires_in_str = parse_params(url_str, "refresh_expires_in");
        NetworkAgent* agent = wxGetApp().getAgent();
        unsigned int http_code;
        std::string http_body;
        int result = agent->get_my_profile(access_token, &http_code, &http_body);
        if (result == 0) {
            std::string user_id;
            std::string user_name;
            std::string user_account;
            std::string user_avatar;
            try {
                json user_j = json::parse(http_body);
                if (user_j.contains("uidStr"))
                    user_id = user_j["uidStr"].get<std::string>();
                if (user_j.contains("name"))
                    user_name = user_j["name"].get<std::string>();
                if (user_j.contains("avatar"))
                    user_avatar = user_j["avatar"].get<std::string>();
                if (user_j.contains("account"))
                    user_account = user_j["account"].get<std::string>();
            } catch (...) {
                ;
            }
            json j;
            j["data"]["refresh_token"] = refresh_token;
            j["data"]["token"] = access_token;
            j["data"]["expires_in"] = expires_in_str;
            j["data"]["refresh_expires_in"] = refresh_expires_in_str;
            j["data"]["user"]["uid"] = user_id;
            j["data"]["user"]["name"] = user_name;
            j["data"]["user"]["account"] = user_account;
            j["data"]["user"]["avatar"] = user_avatar;
            agent->change_user(j.dump());
            if (agent->is_user_login()) {
                wxGetApp().request_user_login(1);
            }
            GUI::wxGetApp().CallAfter([this] {
                wxGetApp().ShowUserLogin(false);
            });
            std::string location_str = (boost::format("Location: %1%?result=success") % redirect_url).str();
            ssOut << "HTTP/1.1 302 Found" << std::endl;
            ssOut << location_str << std::endl;
            ssOut << "content-type: text/html" << std::endl;
            ssOut << "content-length: " << sHTML.length() << std::endl;
            ssOut << std::endl;
            ssOut << sHTML;
        } else {
            std::string error_str = "get_user_profile_error_" + std::to_string(result);
            std::string location_str = (boost::format("Location: %1%?result=fail&error=%2%") % redirect_url % error_str).str();
            ssOut << "HTTP/1.1 302 Found" << std::endl;
            ssOut << location_str << std::endl;
            ssOut << "content-type: text/html" << std::endl;
            ssOut << "content-length: " << sHTML.length() << std::endl;
            ssOut << std::endl;
            ssOut << sHTML;
        }
    } else {
        std::string sHTML = "<html><body><h1>404 Not Found</h1><p>There's nothing here.</p></body></html>";
        ssOut << "HTTP/1.1 404 Not Found" << std::endl;
        ssOut << "content-type: text/html" << std::endl;
        ssOut << "content-length: " << sHTML.length() << std::endl;
        ssOut << std::endl;
        ssOut << sHTML;
    }
    return ssOut.str();
}
References Slic3r::NetworkAgent::change_user(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::NetworkAgent::get_my_profile(), Slic3r::NetworkAgent::is_user_login(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::GUI::parse_params(), url, and Slic3r::Http::url_decode().
on_read_header()
void Slic3r::GUI::http_headers::on_read_header (std::string line) inline
    {
        //std::cout << "header: " << line << std::endl;
        std::stringstream ssHeader(line);
        std::string headerName;
        std::getline(ssHeader, headerName, ':');
        std::string value;
        std::getline(ssHeader, value);
        headers[headerName] = value;
    }
References headers.
on_read_request_line()
void Slic3r::GUI::http_headers::on_read_request_line (std::string line) inline
    {
        std::stringstream ssRequestLine(line);
        ssRequestLine >> method;
        ssRequestLine >> url;
        ssRequestLine >> version;
        std::cout << "request for resource: " << url << std::endl;
    }
References method, url, and version.
Member Data Documentation
headers
std::map<std::string, std::string> Slic3r::GUI::http_headers::headers private
Referenced by content_length(), and on_read_header().
method
std::string Slic3r::GUI::http_headers::method private
Referenced by on_read_request_line().
url
std::string Slic3r::GUI::http_headers::url private
Referenced by get_response(), and on_read_request_line().
version
std::string Slic3r::GUI::http_headers::version private
Referenced by on_read_request_line().
The documentation for this class was generated from the following files:
src/slic3r/GUI/HttpServer.hpp
src/slic3r/GUI/HttpServer.cpp