OrcaSlicer: Slic3r::GUI::AmsRMItem Class Reference
Slic3r::GUI::AmsRMItem Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
AmsRMItem (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~AmsRMItem ()
void set_color (wxColour col)
void set_type (RMTYPE type)
void set_index (std::string index)
void set_focus (bool focus)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
Private Attributes
RMTYPE m_type
wxColour m_color
std::string m_index
bool m_focus = false
bool m_selected = false
Detailed Description
Constructor & Destructor Documentation
AmsRMItem()
Slic3r::GUI::AmsRMItem::AmsRMItem (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{
    wxWindow::Create(parent, id, pos, size);
    SetSize(wxSize(FromDIP(42), FromDIP(32)));
    SetMinSize(wxSize(FromDIP(42), FromDIP(32)));
    SetMaxSize(wxSize(FromDIP(42), FromDIP(32)));
    SetBackgroundColour(*wxWHITE);
    Bind(wxEVT_PAINT, &AmsRMItem::paintEvent, this);
}
References paintEvent(), and size.
~AmsRMItem()
Slic3r::GUI::AmsRMItem::~AmsRMItem () inline
{};
Member Function Documentation
doRender()
void Slic3r::GUI::AmsRMItem::doRender (wxDC & dc)
{
    wxSize size = GetSize();
    if (m_type == RMTYPE_NORMAL) {
        dc.SetPen(wxPen(m_color, 2));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
    }
    else {
        dc.SetPen(wxPen(m_color, 2, wxSHORT_DASH));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
    }
    //top bottom line
    dc.DrawLine(FromDIP(0), FromDIP(4), size.x - FromDIP(5), FromDIP(4));
    dc.DrawLine(FromDIP(0), size.y - FromDIP(4), size.x - FromDIP(5), size.y - FromDIP(4));
    //left right line
    dc.DrawLine(FromDIP(1), FromDIP(4), FromDIP(1), FromDIP(11));
    dc.DrawLine(FromDIP(1), FromDIP(22), FromDIP(1), size.y - FromDIP(4));
    dc.DrawLine(size.x - FromDIP(5), FromDIP(4), size.x - FromDIP(5), FromDIP(11));
    dc.DrawLine(size.x - FromDIP(5), FromDIP(22), size.x - FromDIP(5), size.y - FromDIP(4));
    //delta
    dc.DrawLine(FromDIP(0), FromDIP(11), FromDIP(5), size.y / 2);
    dc.DrawLine(FromDIP(0), FromDIP(22), FromDIP(5), size.y / 2);
    dc.DrawLine(size.x - FromDIP(5), FromDIP(11), size.x - FromDIP(1), size.y / 2);
    dc.DrawLine(size.x - FromDIP(5), FromDIP(22), size.x - FromDIP(1), size.y / 2);
    if (m_focus) {
        dc.SetPen(wxPen(wxColour(0x00AE42), 2));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawLine(FromDIP(0), FromDIP(1), size.x - FromDIP(5), FromDIP(1));
        dc.DrawLine(FromDIP(0), size.y - FromDIP(1), size.x - FromDIP(5), size.y - FromDIP(1));
    }
    if (m_selected) {
    }
    auto tsize = dc.GetMultiLineTextExtent(m_index);
    auto tpot = wxPoint((size.x - tsize.x) / 2 - FromDIP(2), (size.y - tsize.y) / 2 + FromDIP(2));
    dc.SetTextForeground(wxColour(0x6B6B6B));
    dc.SetFont(::Label::Head_12);
    dc.DrawText(m_index, tpot);
}
References Label::Head_12, m_color, m_focus, m_index, m_selected, m_type, Slic3r::GUI::RMTYPE_NORMAL, and size.
Referenced by render().
paintEvent()
void Slic3r::GUI::AmsRMItem::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by AmsRMItem().
render()
void Slic3r::GUI::AmsRMItem::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
set_color()
void Slic3r::GUI::AmsRMItem::set_color (wxColour col) inline
{m_color = col;};
References col().
Referenced by Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line().
set_focus()
void Slic3r::GUI::AmsRMItem::set_focus (bool focus) inline
{m_focus = focus;};
Referenced by Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line().
set_index()
void Slic3r::GUI::AmsRMItem::set_index (std::string index) inline
{m_index = index;};
Referenced by Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line().
set_type()
void Slic3r::GUI::AmsRMItem::set_type (RMTYPE type) inline
{m_type = type;};
Referenced by Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line().
Member Data Documentation
m_color
wxColour Slic3r::GUI::AmsRMItem::m_color private
Referenced by doRender().
m_focus
bool Slic3r::GUI::AmsRMItem::m_focus = false private
Referenced by doRender().
m_index
std::string Slic3r::GUI::AmsRMItem::m_index private
Referenced by doRender().
m_selected
bool Slic3r::GUI::AmsRMItem::m_selected = false private
Referenced by doRender().
m_type
RMTYPE Slic3r::GUI::AmsRMItem::m_type private
Referenced by doRender().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp