OrcaSlicer: Slic3r::GUI::AMSVirtualRoad Class Reference
Slic3r::GUI::AMSVirtualRoad Class Reference
#include <src/slic3r/GUI/Widgets/AMSControl.hpp>
Public Member Functions
AMSVirtualRoad (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~AMSVirtualRoad ()
void OnVamsLoading (bool load, wxColour col=AMS_CONTROL_GRAY500)
void SetHasVams (bool hvams)
void create (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
void msw_rescale ()
Private Attributes
bool m_has_vams { true }
bool m_vams_loading { false }
wxColour m_current_color
Detailed Description
Constructor & Destructor Documentation
AMSVirtualRoad()
Slic3r::GUI::AMSVirtualRoad::AMSVirtualRoad (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{ create(parent, id, pos, size); }
References create(), and size.
~AMSVirtualRoad()
Slic3r::GUI::AMSVirtualRoad::~AMSVirtualRoad ()
{}
Member Function Documentation
create()
void Slic3r::GUI::AMSVirtualRoad::create (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size)
{
    wxWindow::Create(parent, id, pos, wxDefaultSize, wxBORDER_NONE);
    SetBackgroundColour(AMS_CONTROL_WHITE_COLOUR);
    Layout();
    Bind(wxEVT_PAINT, &AMSVirtualRoad::paintEvent, this);
}
References AMS_CONTROL_WHITE_COLOUR, and paintEvent().
Referenced by AMSVirtualRoad().
doRender()
void Slic3r::GUI::AMSVirtualRoad::doRender (wxDC & dc)
{
    if (!m_has_vams) return;
    wxSize size = GetSize();
    if (m_vams_loading) {
        dc.SetPen(wxPen(m_current_color, 6, wxSOLID));
    }
    else {
        dc.SetPen(wxPen(AMS_CONTROL_GRAY500, 2, wxSOLID));
    }
    dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
    dc.DrawRoundedRectangle(size.x / 2, -size.y / 1.1 + FromDIP(1), size.x, size.y, 4);
    if (m_current_color == *wxWHITE && !wxGetApp().dark_mode()) {
        dc.SetPen(wxPen(AMS_CONTROL_DEF_BLOCK_BK_COLOUR, 1, wxSOLID));
        dc.DrawRoundedRectangle(size.x / 2 - FromDIP(3), -size.y / 1.1 + FromDIP(4), size.x, size.y, 5);
        dc.DrawRoundedRectangle(size.x / 2 + FromDIP(3), -size.y / 1.1 - FromDIP(2), size.x, size.y, 3);
    }
}
References AMS_CONTROL_DEF_BLOCK_BK_COLOUR, AMS_CONTROL_GRAY500, m_current_color, m_has_vams, m_vams_loading, and size.
Referenced by render().
msw_rescale()
void Slic3r::GUI::AMSVirtualRoad::msw_rescale ()
{
    Layout();
    Update();
    Refresh();
}
Referenced by Slic3r::GUI::AMSControl::msw_rescale().
OnVamsLoading()
void Slic3r::GUI::AMSVirtualRoad::OnVamsLoading (bool load, wxColour col = AMS_CONTROL_GRAY500)
{
    m_vams_loading = load;
    if (load)m_current_color = col;
    Refresh();
}
References col(), m_current_color, and m_vams_loading.
Referenced by Slic3r::GUI::AMSControl::SetAmsStep(), and Slic3r::GUI::AMSControl::SetExtruder().
paintEvent()
void Slic3r::GUI::AMSVirtualRoad::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by create().
render()
void Slic3r::GUI::AMSVirtualRoad::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
SetHasVams()
void Slic3r::GUI::AMSVirtualRoad::SetHasVams (bool hvams) inline
{ m_has_vams = hvams; };
References m_has_vams.
Member Data Documentation
m_current_color
wxColour Slic3r::GUI::AMSVirtualRoad::m_current_color private
Referenced by doRender(), and OnVamsLoading().
m_has_vams
bool Slic3r::GUI::AMSVirtualRoad::m_has_vams { true } private
Referenced by doRender(), and SetHasVams().
m_vams_loading
bool Slic3r::GUI::AMSVirtualRoad::m_vams_loading { false } private
Referenced by doRender(), and OnVamsLoading().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AMSControl.hpp
src/slic3r/GUI/Widgets/AMSControl.cpp