OrcaSlicer: Slic3r::FlushVolCalculator Class Reference
Slic3r::FlushVolCalculator Class Reference
#include <src/libslic3r/FlushVolCalc.hpp>
Public Member Functions
FlushVolCalculator (int min, int max, float multiplier=1.0f)
~FlushVolCalculator ()
int calc_flush_vol (unsigned char src_a, unsigned char src_r, unsigned char src_g, unsigned char src_b, unsigned char dst_a, unsigned char dst_r, unsigned char dst_g, unsigned char dst_b)
Private Attributes
int m_min_flush_vol
int m_max_flush_vol
float m_multiplier
Detailed Description
Constructor & Destructor Documentation
FlushVolCalculator()
Slic3r::FlushVolCalculator::FlushVolCalculator (int min, int max, float multiplier = 1.0f)
    :m_min_flush_vol(min), m_max_flush_vol(max), m_multiplier(multiplier)
{
}
~FlushVolCalculator()
Slic3r::FlushVolCalculator::~FlushVolCalculator () inline
    {
    }
Member Function Documentation
calc_flush_vol()
int Slic3r::FlushVolCalculator::calc_flush_vol (unsigned char src_a, unsigned char src_r, unsigned char src_g, unsigned char src_b, unsigned char dst_a, unsigned char dst_r, unsigned char dst_g, unsigned char dst_b)
{
    // BBS: Transparent materials are treated as white materials
    if (src_a == 0) {
        src_r = src_g = src_b = 255;
    }
    if (dst_a == 0) {
        dst_r = dst_g = dst_b = 255;
    }
    float src_r_f, src_g_f, src_b_f, dst_r_f, dst_g_f, dst_b_f;
    float from_hsv_h, from_hsv_s, from_hsv_v;
    float to_hsv_h, to_hsv_s, to_hsv_v;
    src_r_f = (float)src_r / 255.f;
    src_g_f = (float)src_g / 255.f;
    src_b_f = (float)src_b / 255.f;
    dst_r_f = (float)dst_r / 255.f;
    dst_g_f = (float)dst_g / 255.f;
    dst_b_f = (float)dst_b / 255.f;
    // Calculate color distance in HSV color space
    RGB2HSV(src_r_f, src_g_f,src_b_f, &from_hsv_h, &from_hsv_s, &from_hsv_v);
    RGB2HSV(dst_r_f, dst_g_f, dst_b_f, &to_hsv_h, &to_hsv_s, &to_hsv_v);
    float hs_dist = DeltaHS_BBS(from_hsv_h, from_hsv_s, from_hsv_v, to_hsv_h, to_hsv_s, to_hsv_v);
    // 1. Color difference is more obvious if the dest color has high luminance
    // 2. Color difference is more obvious if the source color has low luminance
    float from_lumi = get_luminance(src_r_f, src_g_f, src_b_f);
    float to_lumi = get_luminance(dst_r_f, dst_g_f, dst_b_f);
    float lumi_flush = 0.f;
    if (to_lumi >= from_lumi) {
        lumi_flush = std::pow(to_lumi - from_lumi, 0.7f) * 560.f;
    }
    else {
        lumi_flush = (from_lumi - to_lumi) * 80.f;
        float inter_hsv_v = 0.67 * to_hsv_v + 0.33 * from_hsv_v;
        hs_dist = std::min(inter_hsv_v, hs_dist);
    }
    float hs_flush = 230.f * hs_dist;
    float flush_volume = calc_triangle_3rd_edge(hs_flush, lumi_flush, 120.f);
    flush_volume = std::max(flush_volume, 60.f);
    //float flush_multiplier = std::atof(m_flush_multiplier_ebox->GetValue().c_str());
    flush_volume += m_min_flush_vol;
    return std::min((int)flush_volume, m_max_flush_vol);
}
References Slic3r::calc_triangle_3rd_edge(), Slic3r::DeltaHS_BBS(), Slic3r::get_luminance(), m_max_flush_vol, m_min_flush_vol, and RGB2HSV().
Member Data Documentation
m_max_flush_vol
int Slic3r::FlushVolCalculator::m_max_flush_vol private
Referenced by calc_flush_vol().
m_min_flush_vol
int Slic3r::FlushVolCalculator::m_min_flush_vol private
Referenced by calc_flush_vol().
m_multiplier
float Slic3r::FlushVolCalculator::m_multiplier private
The documentation for this class was generated from the following files:
src/libslic3r/FlushVolCalc.hpp
src/libslic3r/FlushVolCalc.cpp