OrcaSlicer: WipingPanel Class Reference
WipingPanel Class Reference
#include <src/slic3r/GUI/WipeTowerDialog.hpp>
Public Member Functions
WipingPanel (wxWindow *parent, const std::vector< float > &matrix, const std::vector< float > &extruders, const std::vector< std::string > &extruder_colours, Button *calc_button, int extra_flush_volume, float flush_multiplier)
std::vector< float > read_matrix_values ()
std::vector< float > read_extruders_values ()
void toggle_advanced (bool user_action=false)
void create_panels (wxWindow *parent, const int num)
void calc_flushing_volumes ()
float get_flush_multiplier ()
Private Member Functions
void fill_in_matrix ()
bool advanced_matches_simple ()
int calc_flushing_volume (const wxColour &from, const wxColour &to)
void update_warning_texts ()
Private Attributes
std::vector< wxSpinCtrl * > m_old
std::vector< wxSpinCtrl * > m_new
std::vector< std::vector< wxTextCtrl * > > edit_boxes
std::vector< wxColour > m_colours
unsigned int m_number_of_extruders = 0
bool m_advanced = false
wxPanel * m_page_simple = nullptr
wxPanel * m_page_advanced = nullptr
wxPanel * header_line_panel = nullptr
wxBoxSizer * m_sizer = nullptr
wxBoxSizer * m_sizer_simple = nullptr
wxBoxSizer * m_sizer_advanced = nullptr
wxGridSizer * m_gridsizer_advanced = nullptr
wxButton * m_widget_button = nullptr
const int m_min_flush_volume
const int m_max_flush_volume
wxTextCtrl * m_flush_multiplier_ebox = nullptr
wxStaticText * m_min_flush_label = nullptr
std::vector< float > m_matrix
Detailed Description
Constructor & Destructor Documentation
WipingPanel()
WipingPanel::WipingPanel (wxWindow * parent, const std::vector< float > & matrix, const std::vector< float > & extruders, const std::vector< std::string > & extruder_colours, Button * calc_button, int extra_flush_volume, float flush_multiplier)
: wxPanel(parent,wxID_ANY, wxDefaultPosition, wxDefaultSize/*,wxBORDER_RAISED*/)
,m_matrix(matrix), m_min_flush_volume(extra_flush_volume), m_max_flush_volume(800)
{
    m_number_of_extruders = (int)(sqrt(matrix.size())+0.001);
    for (const std::string& color : extruder_colours) {
        //unsigned char rgb[3];
        //Slic3r::GUI::BitmapCache::parse_color(color, rgb);
        m_colours.push_back(wxColor(color));
    }
    // Create two switched panels with their own sizers
    m_sizer_simple          = new wxBoxSizer(wxVERTICAL);
    m_sizer_advanced        = new wxBoxSizer(wxVERTICAL);
    m_page_simple     = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_page_advanced     = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_page_simple->SetSizer(m_sizer_simple);
    m_page_advanced->SetSizer(m_sizer_advanced);
    update_ui(m_page_simple);
    update_ui(m_page_advanced);
    auto gridsizer_simple   = new wxGridSizer(3, 5, 10);
    m_gridsizer_advanced = new wxGridSizer(m_number_of_extruders + 1, 5, 1);
    // First create controls for advanced mode and assign them to m_page_advanced:
    for (unsigned int i = 0; i < m_number_of_extruders; ++i) {
        edit_boxes.push_back(std::vector<wxTextCtrl*>(0));
        for (unsigned int j = 0; j < m_number_of_extruders; ++j) {
#ifdef _WIN32
            wxTextCtrl* text = new wxTextCtrl(m_page_advanced, wxID_ANY, wxEmptyString, wxDefaultPosition, wxSize(ITEM_WIDTH(), -1), wxTE_CENTER | wxBORDER_NONE | wxTE_PROCESS_ENTER);
            update_ui(text);
            edit_boxes.back().push_back(text);
#else
            edit_boxes.back().push_back(new wxTextCtrl(m_page_advanced, wxID_ANY, wxEmptyString, wxDefaultPosition, wxSize(ITEM_WIDTH(), -1)));
#endif
            if (i == j) {
                edit_boxes[i][j]->SetValue(wxString("-"));
                edit_boxes[i][j]->SetEditable(false);
                edit_boxes[i][j]->Bind(wxEVT_KILL_FOCUS, [this](wxFocusEvent&) {});
                edit_boxes[i][j]->Bind(wxEVT_SET_FOCUS, [this](wxFocusEvent&) {});
            }
            else {
                edit_boxes[i][j]->SetValue(wxString("") << int(m_matrix[m_number_of_extruders * j + i] * flush_multiplier));
                edit_boxes[i][j]->Bind(wxEVT_TEXT, [this, i, j](wxCommandEvent& e) {
                    wxString str = edit_boxes[i][j]->GetValue();
                    int value = wxAtoi(str);
                    if (value > MAX_FLUSH_VALUE) {
                        str = wxString::Format(("%d"), MAX_FLUSH_VALUE);
                        edit_boxes[i][j]->SetValue(str);
                    }
                    });
                auto on_apply_text_modify = [this, i, j](wxEvent &e) {
                    wxString str   = edit_boxes[i][j]->GetValue();
                    int      value = wxAtoi(str);
                    m_matrix[m_number_of_extruders * j + i] = value / get_flush_multiplier();
                    this->update_warning_texts();
                    e.Skip();
                };
                edit_boxes[i][j]->Bind(wxEVT_TEXT_ENTER, on_apply_text_modify);
                edit_boxes[i][j]->Bind(wxEVT_KILL_FOCUS, on_apply_text_modify);
            }
        }
    }
    // BBS
    header_line_panel = new wxPanel(m_page_advanced, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    header_line_panel->SetBackgroundColour(wxColour(238, 238, 238));
    auto header_line_sizer = new wxBoxSizer(wxHORIZONTAL);
    header_line_panel->SetSizer(header_line_sizer);
    header_line_sizer->AddSpacer(HEADER_BEG_PADDING);
    for (unsigned int i = 0; i < m_number_of_extruders; ++i) {
        wxButton* icon = new wxButton(header_line_panel, wxID_ANY, wxString("") << i + 1, wxDefaultPosition, ICON_SIZE, wxBORDER_NONE | wxBU_AUTODRAW);
        icon->SetBackgroundColour(m_colours[i]);
        //auto icon_style = icon->GetWindowStyle() & ~(wxBORDER_NONE | wxBORDER_SIMPLE);
        //icon->SetWindowStyle(m_colours[i].Red() > 224 && m_colours[i].Blue() > 224 && m_colours[i].Green() > 224 ? (icon_style | wxBORDER_SIMPLE) : (icon_style | wxBORDER_NONE));
        auto label_clr = m_colours[i].GetLuminance() < 0.51  ? *wxWHITE : *wxBLACK;
        icon->SetForegroundColour(label_clr);
        icon->SetCanFocus(false);
        header_line_sizer->AddSpacer(ICON_GAP);
        header_line_sizer->Add(icon, 0, wxALIGN_CENTER_VERTICAL | wxTOP | wxBOTTOM, HEADER_VERT_PADDING);
    }
    header_line_sizer->AddSpacer(HEADER_END_PADDING);
    m_sizer_advanced->Add(header_line_panel, 0, wxEXPAND | wxTOP | wxRIGHT | wxLEFT, TABLE_BORDER);
    create_panels(m_page_advanced, m_number_of_extruders);
    m_sizer_advanced->AddSpacer(BTN_SIZE.y);
    // BBS: for tunning flush volumes
    {
        wxBoxSizer* param_sizer = new wxBoxSizer(wxHORIZONTAL);
        wxStaticText* flush_multiplier_title = new wxStaticText(m_page_advanced, wxID_ANY, _L("Multiplier"));
        param_sizer->Add(flush_multiplier_title);
        param_sizer->AddSpacer(FromDIP(5));
        m_flush_multiplier_ebox = new wxTextCtrl(m_page_advanced, wxID_ANY, wxEmptyString, wxDefaultPosition, wxSize(FromDIP(50), -1), wxTE_PROCESS_ENTER);
        char flush_multi_str[32] = { 0 };
        snprintf(flush_multi_str, sizeof(flush_multi_str), "%.2f", flush_multiplier);
        m_flush_multiplier_ebox->SetValue(flush_multi_str);
        param_sizer->Add(m_flush_multiplier_ebox);
        param_sizer->AddStretchSpacer(1);
        m_sizer_advanced->Add(param_sizer, 0, wxEXPAND | wxLEFT, TEXT_BEG_PADDING);
        auto multi_desc_label = new wxStaticText(m_page_advanced, wxID_ANY, _(L("Flushing volume (mm³) for each filament pair.")), wxDefaultPosition, wxDefaultSize, 0);
        multi_desc_label->SetForegroundColour(g_text_color);
        m_sizer_advanced->Add(multi_desc_label, 0, wxEXPAND | wxLEFT, TEXT_BEG_PADDING);
        wxString min_flush_str = wxString::Format(_L("Suggestion: Flushing Volume in range [%d, %d]"), m_min_flush_volume, m_max_flush_volume);
        m_min_flush_label = new wxStaticText(m_page_advanced, wxID_ANY, min_flush_str, wxDefaultPosition, wxDefaultSize, 0);
        m_min_flush_label->SetForegroundColour(g_text_color);
        m_sizer_advanced->Add(m_min_flush_label, 0, wxEXPAND | wxLEFT, TEXT_BEG_PADDING);
        auto on_apply_text_modify = [this](wxEvent& e) {
            wxString str = m_flush_multiplier_ebox->GetValue();
            float      multiplier = wxAtof(str);
            if (multiplier < g_min_flush_multiplier || multiplier > g_max_flush_multiplier) {
                str = wxString::Format(("%.2f"), multiplier < g_min_flush_multiplier ? g_min_flush_multiplier : g_max_flush_multiplier);
                m_flush_multiplier_ebox->SetValue(str);
                MessageDialog dlg(nullptr,
                    wxString::Format(_L("The multiplier should be in range [%.2f, %.2f]."), g_min_flush_multiplier, g_max_flush_multiplier),
                    _L("Warning"), wxICON_WARNING | wxOK);
                dlg.ShowModal();
            }
            for (unsigned int i = 0; i < m_number_of_extruders; ++i) {
                for (unsigned int j = 0; j < m_number_of_extruders; ++j) {
                    edit_boxes[i][j]->SetValue(to_string(int(m_matrix[m_number_of_extruders * j + i] * multiplier)));
                }
            }
            this->update_warning_texts();
            e.Skip();
        };
        m_flush_multiplier_ebox->Bind(wxEVT_TEXT_ENTER, on_apply_text_modify);
        m_flush_multiplier_ebox->Bind(wxEVT_KILL_FOCUS, on_apply_text_modify);
        m_sizer_advanced->AddSpacer(10);
    }
    this->update_warning_texts();
    m_page_advanced->Hide();
    // Now the same for simple mode:
    gridsizer_simple->Add(new wxStaticText(m_page_simple, wxID_ANY, wxString("")), 0, wxALIGN_CENTER | wxALIGN_CENTER_VERTICAL);
    gridsizer_simple->Add(new wxStaticText(m_page_simple, wxID_ANY, wxString(_(L("unloaded")))), 0, wxALIGN_CENTER | wxALIGN_CENTER_VERTICAL);
    gridsizer_simple->Add(new wxStaticText(m_page_simple,wxID_ANY,wxString(_(L("loaded")))), 0, wxALIGN_CENTER | wxALIGN_CENTER_VERTICAL);
    auto add_spin_ctrl = [this](std::vector<wxSpinCtrl*>& vec, float initial)
    {
        wxSpinCtrl* spin_ctrl = new wxSpinCtrl(m_page_simple, wxID_ANY, wxEmptyString, wxDefaultPosition, wxSize(ITEM_WIDTH(), -1), style | wxALIGN_RIGHT, 0, 300, (int)initial);
        update_ui(spin_ctrl);
        vec.push_back(spin_ctrl);
#ifdef __WXOSX__
        // On OSX / Cocoa, wxSpinCtrl::GetValue() doesn't return the new value
        // when it was changed from the text control, so the on_change callback
        // gets the old one, and on_kill_focus resets the control to the old value.
        // As a workaround, we get the new value from $event->GetString and store
        // here temporarily so that we can return it from get_value()
        spin_ctrl->Bind(wxEVT_TEXT, ([spin_ctrl](wxCommandEvent e)
        {
            long value;
            const bool parsed = e.GetString().ToLong(&value);
            int tmp_value = parsed && value >= INT_MIN && value <= INT_MAX ? (int)value : INT_MIN;
            // Forcibly set the input value for SpinControl, since the value
            // inserted from the keyboard or clipboard is not updated under OSX
            if (tmp_value != INT_MIN) {
                spin_ctrl->SetValue(tmp_value);
                // But in SetValue() is executed m_text_ctrl->SelectAll(), so
                // discard this selection and set insertion point to the end of string
                spin_ctrl->GetText()->SetInsertionPointEnd();
            }
        }), spin_ctrl->GetId());
#endif
    };
    for (unsigned int i=0;i<m_number_of_extruders;++i) {
        add_spin_ctrl(m_old, extruders[2 * i]);
        add_spin_ctrl(m_new, extruders[2 * i+1]);
        auto hsizer = new wxBoxSizer(wxHORIZONTAL);
        wxWindow* w = new wxWindow(m_page_simple, wxID_ANY, wxDefaultPosition, ICON_SIZE, wxBORDER_SIMPLE);
        w->SetCanFocus(false);
        w->SetBackgroundColour(m_colours[i]);
        hsizer->Add(w, wxALIGN_CENTER_VERTICAL);
        hsizer->AddSpacer(10);
        hsizer->Add(new wxStaticText(m_page_simple, wxID_ANY, wxString(_(L("Filament #"))) << i + 1 << ": "), 0, wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL);
        gridsizer_simple->Add(hsizer, 1, wxEXPAND | wxALIGN_CENTER_VERTICAL);
        gridsizer_simple->Add(m_old.back(),0);
        gridsizer_simple->Add(m_new.back(),0);
    }
    m_sizer = new wxBoxSizer(wxVERTICAL);
    m_sizer->Add(m_page_simple, 0, wxEXPAND, 0);
    m_sizer->Add(m_page_advanced, 0, wxEXPAND, 0);
    m_sizer->SetSizeHints(this);
    SetSizer(m_sizer);
    this->Layout();
    toggle_advanced(); // to show/hide what is appropriate
    header_line_panel->Bind(wxEVT_PAINT, [this](wxPaintEvent&) {
        wxPaintDC dc(header_line_panel);
        wxString from_text = _L("From");
        wxString to_text = _L("To");
        wxSize from_text_size = dc.GetTextExtent(from_text);
        wxSize to_text_size = dc.GetTextExtent(to_text);
        int base_y = (header_line_panel->GetSize().y - from_text_size.y - to_text_size.y) / 2;
        int vol_width = ROW_BEG_PADDING + EDIT_BOXES_GAP / 2 + ICON_SIZE.x;
        int base_x = (vol_width - from_text_size.x - to_text_size.x) / 2;
        // draw from text
        int x = base_x;
        int y = base_y + to_text_size.y;
        dc.DrawText(from_text, x, y);
        // draw to text
        x = base_x + from_text_size.x;
        y = base_y;
        dc.DrawText(to_text, x, y);
        // draw a line
        int p1_x = base_x + from_text_size.x - to_text_size.y;
        int p1_y = base_y;
        int p2_x = base_x + from_text_size.x + from_text_size.y;
        int p2_y = base_y + from_text_size.y + to_text_size.y;
        dc.SetPen(wxPen(wxColour(172, 172, 172, 1)));
        dc.DrawLine(p1_x, p1_y, p2_x, p2_y);
    });
}
References _, _L, BTN_SIZE, create_panels(), edit_boxes, EDIT_BOXES_GAP, g_max_flush_multiplier, g_min_flush_multiplier, g_text_color, get_flush_multiplier(), HEADER_BEG_PADDING, HEADER_END_PADDING, header_line_panel, HEADER_VERT_PADDING, ICON_GAP, ICON_SIZE, int, ITEM_WIDTH(), L, m_colours, m_flush_multiplier_ebox, m_gridsizer_advanced, m_matrix, m_max_flush_volume, m_min_flush_label, m_min_flush_volume, m_new, m_number_of_extruders, m_old, m_page_advanced, m_page_simple, m_sizer, m_sizer_advanced, m_sizer_simple, MAX_FLUSH_VALUE, ROW_BEG_PADDING, Slic3r::GUI::DPIAware< P >::ShowModal(), sqrt(), style, TABLE_BORDER, TEXT_BEG_PADDING, to_string(), toggle_advanced(), update_ui(), update_warning_texts(), wxButton, and wxStaticText.
Member Function Documentation
advanced_matches_simple()
bool WipingPanel::advanced_matches_simple () private
{
    for (unsigned i=0;i<m_number_of_extruders;++i) {
        for (unsigned j=0;j<m_number_of_extruders;++j) {
            if (i==j) continue;
            if (edit_boxes[j][i]->GetValue() != (wxString("")<< (m_old[i]->GetValue() + m_new[j]->GetValue())))
                return false;
        }
    }
    return true;
}
References edit_boxes, m_new, m_number_of_extruders, and m_old.
calc_flushing_volume()
int WipingPanel::calc_flushing_volume (const wxColour & from, const wxColour & to) private
{
    float from_hsv_h, from_hsv_s, from_hsv_v;
    float to_hsv_h, to_hsv_s, to_hsv_v;
    // Calculate color distance in HSV color space
    RGB2HSV((float)from.Red() / 255.f, (float)from.Green() / 255.f, (float)from.Blue() / 255.f, &from_hsv_h, &from_hsv_s, &from_hsv_v);
    RGB2HSV((float)to.Red() / 255.f, (float)to.Green() / 255.f, (float)to.Blue() / 255.f, &to_hsv_h, &to_hsv_s, &to_hsv_v);
    float hs_dist = DeltaHS_BBS(from_hsv_h, from_hsv_s, from_hsv_v, to_hsv_h, to_hsv_s, to_hsv_v);
    // 1. Color difference is more obvious if the dest color has high luminance
    // 2. Color difference is more obvious if the source color has low luminance
    float from_lumi = get_luminance((float)from.Red() / 255.f, (float)from.Green() / 255.f, (float)from.Blue() / 255.f);
    float to_lumi = get_luminance((float)to.Red() / 255.f, (float)to.Green() / 255.f, (float)to.Blue() / 255.f);
    float lumi_flush = 0.f;
    if (to_lumi >= from_lumi) {
        lumi_flush = std::pow(to_lumi - from_lumi, 0.7f) * 560.f;
    }
    else {
        lumi_flush = (from_lumi - to_lumi) * 80.f;
        float inter_hsv_v = 0.67 * to_hsv_v + 0.33 * from_hsv_v;
        hs_dist = std::min(inter_hsv_v, hs_dist);
    }
    float hs_flush = 230.f * hs_dist;
    float flush_volume = calc_triangle_3rd_edge(hs_flush, lumi_flush, 120.f);
    flush_volume = std::max(flush_volume, 60.f);
    //float flush_multiplier = std::atof(m_flush_multiplier_ebox->GetValue().c_str());
    flush_volume += m_min_flush_volume;
    return std::min((int)flush_volume, m_max_flush_volume);
}
References calc_triangle_3rd_edge(), DeltaHS_BBS(), get_luminance(), m_max_flush_volume, m_min_flush_volume, and RGB2HSV().
Referenced by calc_flushing_volumes().
calc_flushing_volumes()
void WipingPanel::calc_flushing_volumes ()
{
    for (int from_idx = 0; from_idx < m_colours.size(); from_idx++) {
        const wxColour& from = m_colours[from_idx];
        bool is_from_support = is_support_filament(from_idx);
        for (int to_idx = 0; to_idx < m_colours.size(); to_idx++) {
            bool is_to_support = is_support_filament(to_idx);
            if (from_idx == to_idx) {
                edit_boxes[to_idx][from_idx]->SetValue(std::to_string(0));
            }
            else {
                int flushing_volume = 0;
                if (is_to_support) {
                    flushing_volume = g_flush_volume_to_support;
                }
                else {
                    const wxColour& to = m_colours[to_idx];
                    flushing_volume = calc_flushing_volume(from, to);
                    if (is_from_support) {
                        flushing_volume = std::max(g_min_flush_volume_from_support, flushing_volume);
                    }
                }
                m_matrix[m_number_of_extruders * from_idx + to_idx] = flushing_volume;
                flushing_volume = int(flushing_volume * get_flush_multiplier());
                edit_boxes[to_idx][from_idx]->SetValue(std::to_string(flushing_volume));
            }
        }
    }
    this->update_warning_texts();
}
References calc_flushing_volume(), edit_boxes, g_flush_volume_to_support, g_min_flush_volume_from_support, get_flush_multiplier(), int, Slic3r::GUI::is_support_filament(), m_colours, m_matrix, m_number_of_extruders, and update_warning_texts().
Referenced by WipingDialog::WipingDialog().
create_panels()
void WipingPanel::create_panels (wxWindow * parent, const int num)
{
    for (size_t i = 0; i < num; i++)
    {
        wxPanel* panel = new wxPanel(parent);
        panel->SetBackgroundColour(i % 2 == 0 ? *wxWHITE : wxColour(238, 238, 238));
        auto sizer = new wxBoxSizer(wxHORIZONTAL);
        panel->SetSizer(sizer);
        wxButton *icon = new wxButton(panel, wxID_ANY, wxString("") << i + 1, wxDefaultPosition, ICON_SIZE, wxBORDER_NONE | wxBU_AUTODRAW);
        icon->SetBackgroundColour(m_colours[i]);
        //auto icon_style = icon->GetWindowStyle() & ~(wxBORDER_NONE | wxBORDER_SIMPLE);
        //icon->SetWindowStyle(m_colours[i].Red() > 224 && m_colours[i].Blue() > 224 && m_colours[i].Green() > 224 ? (icon_style | wxBORDER_SIMPLE) : (icon_style | wxBORDER_NONE));
        auto label_clr = m_colours[i].GetLuminance() < 0.51 ? *wxWHITE : *wxBLACK;
        icon->SetForegroundColour(label_clr);
        icon->SetCanFocus(false);
        sizer->AddSpacer(ROW_BEG_PADDING);
        sizer->Add(icon, 0, wxALIGN_CENTER_VERTICAL | wxTOP | wxBOTTOM, ROW_VERT_PADDING);
        for (unsigned int j = 0; j < num; ++j) {
            edit_boxes[j][i]->Reparent(panel);
            edit_boxes[j][i]->SetBackgroundColour(panel->GetBackgroundColour());
            sizer->AddSpacer(EDIT_BOXES_GAP);
            sizer->Add(edit_boxes[j][i], 0, wxALIGN_CENTER_VERTICAL, 0);
        }
        sizer->AddSpacer(ROW_END_PADDING);
        m_sizer_advanced->Add(panel, 0, wxRIGHT | wxLEFT | wxEXPAND, TABLE_BORDER);
        panel->Layout();
    }
}
References edit_boxes, EDIT_BOXES_GAP, ICON_SIZE, m_colours, m_sizer_advanced, ROW_BEG_PADDING, ROW_END_PADDING, ROW_VERT_PADDING, TABLE_BORDER, and wxButton.
Referenced by WipingPanel().
fill_in_matrix()
void WipingPanel::fill_in_matrix () private
{
    for (unsigned i=0;i<m_number_of_extruders;++i) {
        for (unsigned j=0;j<m_number_of_extruders;++j) {
            if (i==j) continue;
                edit_boxes[j][i]->SetValue(wxString("")<< (m_old[i]->GetValue() + m_new[j]->GetValue()));
        }
    }
}
References edit_boxes, m_new, m_number_of_extruders, and m_old.
Referenced by read_matrix_values(), and toggle_advanced().
get_flush_multiplier()
float WipingPanel::get_flush_multiplier () inline
    {
        if (m_flush_multiplier_ebox == nullptr)
            return 1.f;
        return std::atof(m_flush_multiplier_ebox->GetValue().c_str());
    }
References m_flush_multiplier_ebox.
Referenced by WipingPanel(), calc_flushing_volumes(), WipingDialog::get_flush_multiplier(), and read_matrix_values().
read_extruders_values()
std::vector< float > WipingPanel::read_extruders_values ()
{
    std::vector<float> output;
    for (unsigned int i=0;i<m_number_of_extruders;++i) {
        output.push_back(m_old[i]->GetValue());
        output.push_back(m_new[i]->GetValue());
    }
    return output;
}
References m_new, m_number_of_extruders, and m_old.
Referenced by WipingDialog::WipingDialog().
read_matrix_values()
std::vector< float > WipingPanel::read_matrix_values ()
{
    if (!m_advanced)
        fill_in_matrix();
    std::vector<float> output;
    for (unsigned int i=0;i<m_number_of_extruders;++i) {
        for (unsigned int j=0;j<m_number_of_extruders;++j) {
            double val = 0.;
            float  flush_multipler = get_flush_multiplier();
            if (flush_multipler == 0) {
                output.push_back(0.);
            }
            else {
                edit_boxes[j][i]->GetValue().ToDouble(&val);
                output.push_back((float) val / get_flush_multiplier());
            }
        }
    }
    return output;
}
References edit_boxes, fill_in_matrix(), get_flush_multiplier(), m_advanced, and m_number_of_extruders.
Referenced by WipingDialog::WipingDialog().
toggle_advanced()
void WipingPanel::toggle_advanced (bool user_action = false)
{
    if (user_action)
        m_advanced = !m_advanced;                // user demands a change -> toggle
    else {
        // BBS: show advanced mode by default
        //m_advanced = !advanced_matches_simple(); // if called from constructor, show what is appropriate
        m_advanced = true;
    }
    (m_advanced ? m_page_advanced : m_page_simple)->Show();
    (!m_advanced ? m_page_advanced : m_page_simple)->Hide();
    if (m_advanced)
        if (user_action) fill_in_matrix();  // otherwise keep values loaded from config
   m_sizer->Layout();
   Refresh();
}
References fill_in_matrix(), m_advanced, m_page_advanced, m_page_simple, and m_sizer.
Referenced by WipingPanel().
update_warning_texts()
void WipingPanel::update_warning_texts () private
{
    static const wxColour g_warning_color = *wxRED;
    static const wxColour g_normal_color = *wxBLACK;
    wxString multi_str = m_flush_multiplier_ebox->GetValue();
    float multiplier = wxAtof(multi_str);
    bool has_exception_flush = false;
    for (int i = 0; i < edit_boxes.size(); i++) {
        auto& box_vec = edit_boxes[i];
        for (int j = 0; j < box_vec.size(); j++) {
            if (i == j)
                continue;
            auto text_box = box_vec[j];
            wxString str = text_box->GetValue();
            int actual_volume = wxAtoi(str);
            if (actual_volume < m_min_flush_volume || actual_volume > m_max_flush_volume) {
                if (text_box->GetForegroundColour() != g_warning_color) {
                    text_box->SetForegroundColour(g_warning_color);
                    text_box->Refresh();
                }
                has_exception_flush = true;
            }
            else {
                if (text_box->GetForegroundColour() != g_normal_color) {
                    text_box->SetForegroundColour(StateColor::darkModeColorFor(g_normal_color));
                    text_box->Refresh();
                }
            }
        }
    }
    if (has_exception_flush && m_min_flush_label->GetForegroundColour() != g_warning_color) {
        m_min_flush_label->SetForegroundColour(g_warning_color);
        m_min_flush_label->Refresh();
    }
    else if (!has_exception_flush && m_min_flush_label->GetForegroundColour() != g_text_color) {
        m_min_flush_label->SetForegroundColour(g_text_color);
        m_min_flush_label->Refresh();
    }
}
References StateColor::darkModeColorFor(), edit_boxes, g_text_color, m_flush_multiplier_ebox, m_max_flush_volume, and m_min_flush_label.
Referenced by WipingPanel(), and calc_flushing_volumes().
Member Data Documentation
edit_boxes
std::vector<std::vector<wxTextCtrl*> > WipingPanel::edit_boxes private
Referenced by WipingPanel(), advanced_matches_simple(), calc_flushing_volumes(), create_panels(), fill_in_matrix(), read_matrix_values(), and update_warning_texts().
header_line_panel
wxPanel* WipingPanel::header_line_panel = nullptr private
Referenced by WipingPanel().
m_advanced
bool WipingPanel::m_advanced = false private
Referenced by read_matrix_values(), and toggle_advanced().
m_colours
std::vector<wxColour> WipingPanel::m_colours private
Referenced by WipingPanel(), calc_flushing_volumes(), and create_panels().
m_flush_multiplier_ebox
wxTextCtrl* WipingPanel::m_flush_multiplier_ebox = nullptr private
Referenced by WipingPanel(), get_flush_multiplier(), and update_warning_texts().
m_gridsizer_advanced
wxGridSizer* WipingPanel::m_gridsizer_advanced = nullptr private
Referenced by WipingPanel().
m_matrix
std::vector<float> WipingPanel::m_matrix private
Referenced by WipingPanel(), and calc_flushing_volumes().
m_max_flush_volume
const int WipingPanel::m_max_flush_volume private
Referenced by WipingPanel(), calc_flushing_volume(), and update_warning_texts().
m_min_flush_label
wxStaticText* WipingPanel::m_min_flush_label = nullptr private
Referenced by WipingPanel(), and update_warning_texts().
m_min_flush_volume
const int WipingPanel::m_min_flush_volume private
Referenced by WipingPanel(), and calc_flushing_volume().
m_new
std::vector<wxSpinCtrl*> WipingPanel::m_new private
Referenced by WipingPanel(), advanced_matches_simple(), fill_in_matrix(), and read_extruders_values().
m_number_of_extruders
unsigned int WipingPanel::m_number_of_extruders = 0 private
Referenced by WipingPanel(), advanced_matches_simple(), calc_flushing_volumes(), fill_in_matrix(), read_extruders_values(), and read_matrix_values().
m_old
std::vector<wxSpinCtrl*> WipingPanel::m_old private
Referenced by WipingPanel(), advanced_matches_simple(), fill_in_matrix(), and read_extruders_values().
m_page_advanced
wxPanel* WipingPanel::m_page_advanced = nullptr private
Referenced by WipingPanel(), and toggle_advanced().
m_page_simple
wxPanel* WipingPanel::m_page_simple = nullptr private
Referenced by WipingPanel(), and toggle_advanced().
m_sizer
wxBoxSizer* WipingPanel::m_sizer = nullptr private
Referenced by WipingPanel(), and toggle_advanced().
m_sizer_advanced
wxBoxSizer* WipingPanel::m_sizer_advanced = nullptr private
Referenced by WipingPanel(), and create_panels().
m_sizer_simple
wxBoxSizer* WipingPanel::m_sizer_simple = nullptr private
Referenced by WipingPanel().
m_widget_button
wxButton* WipingPanel::m_widget_button = nullptr private
The documentation for this class was generated from the following files:
src/slic3r/GUI/WipeTowerDialog.hpp
src/slic3r/GUI/WipeTowerDialog.cpp