OrcaSlicer: Notebook Class Reference
Notebook Class Reference
#include <src/slic3r/GUI/Notebook.hpp>
Public Member Functions
Notebook (wxWindow *parent, wxWindowID winid=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, wxBoxSizer *side_tools=NULL, long style=0)
bool Create (wxWindow *parent, wxWindowID winid=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, wxBoxSizer *side_tools=NULL, long style=0)
bool ShowNewPage (wxWindow *page)
void SetEffects (wxShowEffect showEffect, wxShowEffect hideEffect)
void SetEffect (wxShowEffect effect)
void SetEffectsTimeouts (unsigned showTimeout, unsigned hideTimeout)
void SetEffectTimeout (unsigned timeout)
bool AddPage (wxWindow *page, const wxString &text, const std::string &bmp_name, const std::string &inactive_bmp_name, bool bSelect=false)
virtual bool InsertPage (size_t n, wxWindow *page, const wxString &text, bool bSelect=false, int imageId=NO_IMAGE) override
bool InsertPage (size_t n, wxWindow *page, const wxString &text, const std::string &bmp_name="", const std::string &inactive_bmp_name="", bool bSelect=false)
virtual int SetSelection (size_t n) override
virtual int ChangeSelection (size_t n) override
virtual bool SetPageText (size_t n, const wxString &strText) override
virtual wxString GetPageText (size_t n) const override
virtual bool SetPageImage (size_t WXUNUSED(n), int WXUNUSED(imageId)) override
virtual int GetPageImage (size_t WXUNUSED(n)) const override
bool SetPageImage (size_t n, const std::string &bmp_name)
virtual void SetFocus () override
ButtonsListCtrl * GetBtnsListCtrl () const
void UpdateMode ()
void Rescale ()
void OnNavigationKey (wxNavigationKeyEvent &event)
Protected Member Functions
virtual void UpdateSelectedPage (size_t WXUNUSED(newsel)) override
virtual wxBookCtrlEvent * CreatePageChangingEvent () const override
virtual void MakeChangedEvent (wxBookCtrlEvent &event) override
virtual wxWindow * DoRemovePage (size_t page) override
virtual void DoSize () override
virtual void DoShowPage (wxWindow *page, bool show) override
Private Member Functions
void Init ()
Private Attributes
wxShowEffect m_showEffect
wxShowEffect m_hideEffect
unsigned m_showTimeout
unsigned m_hideTimeout
ButtonsListCtrl * m_ctrl { nullptr }
Detailed Description
Constructor & Destructor Documentation
Notebook()
Notebook::Notebook (wxWindow * parent, wxWindowID winid = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, wxBoxSizer * side_tools = NULL, long style = 0) inline
    {
        Init();
        Create(parent, winid, pos, size, side_tools, style);
    }
References Create(), Init(), size, and style.
Member Function Documentation
AddPage()
bool Notebook::AddPage (wxWindow * page, const wxString & text, const std::string & bmp_name, const std::string & inactive_bmp_name, bool bSelect = false) inline
    {
        DoInvalidateBestSize();
        return InsertPage(GetPageCount(), page, text, bmp_name, inactive_bmp_name, bSelect);
    }
References InsertPage().
Referenced by ShowNewPage().
ChangeSelection()
virtual int Notebook::ChangeSelection (size_t n) inline override virtual
    {
        GetBtnsListCtrl()->SetSelection(n);
        return DoSetSelection(n);
    }
References GetBtnsListCtrl(), n, and ButtonsListCtrl::SetSelection().
Create()
bool Notebook::Create (wxWindow * parent, wxWindowID winid = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, wxBoxSizer * side_tools = NULL, long style = 0) inline
    {
        if (!wxBookCtrlBase::Create(parent, winid, pos, size, style | wxBK_TOP))
            return false;
        m_bookctrl = new ButtonsListCtrl(this, side_tools);
        wxSizer* mainSizer = new wxBoxSizer(IsVertical() ? wxVERTICAL : wxHORIZONTAL);
        if (style & wxBK_RIGHT || style & wxBK_BOTTOM)
            mainSizer->Add(0, 0, 1, wxEXPAND, 0);
        m_controlSizer = new wxBoxSizer(IsVertical() ? wxHORIZONTAL : wxVERTICAL);
        m_controlSizer->Add(m_bookctrl, wxSizerFlags(1).Expand());
        wxSizerFlags flags;
        if (IsVertical())
            flags.Expand();
        else
            flags.CentreVertical();
        mainSizer->Add(m_controlSizer, flags.Border(wxALL, m_controlMargin));
        SetSizer(mainSizer);
        this->Bind(wxCUSTOMEVT_NOTEBOOK_SEL_CHANGED, [this](wxCommandEvent& evt)
        {
            if (int page_idx = evt.GetId(); page_idx >= 0)
                SetSelection(page_idx);
        });
        this->Bind(wxEVT_NAVIGATION_KEY, &Notebook::OnNavigationKey, this);
        return true;
    }
References OnNavigationKey(), SetSelection(), size, and style.
Referenced by Notebook().
CreatePageChangingEvent()
virtual wxBookCtrlEvent * Notebook::CreatePageChangingEvent () const inline override protected virtual
    {
        return new wxBookCtrlEvent(wxEVT_BOOKCTRL_PAGE_CHANGING,
                                   GetId());
    }
DoRemovePage()
virtual wxWindow * Notebook::DoRemovePage (size_t page) inline override protected virtual
    {
        wxWindow* const win = wxBookCtrlBase::DoRemovePage(page);
        if (win)
        {
            GetBtnsListCtrl()->RemovePage(page);
            DoSetSelectionAfterRemoval(page);
        }
        return win;
    }
References GetBtnsListCtrl(), and ButtonsListCtrl::RemovePage().
DoShowPage()
virtual void Notebook::DoShowPage (wxWindow * page, bool show) inline override protected virtual
    {
        if (show)
            page->ShowWithEffect(m_showEffect, m_showTimeout);
        else
            page->HideWithEffect(m_hideEffect, m_hideTimeout);
    }
References m_hideEffect, m_hideTimeout, m_showEffect, and m_showTimeout.
DoSize()
virtual void Notebook::DoSize () inline override protected virtual
    {
        wxWindow* const page = GetCurrentPage();
        if (page)
            page->SetSize(GetPageRect());
    }
GetBtnsListCtrl()
ButtonsListCtrl * Notebook::GetBtnsListCtrl () const inline
{ return static_cast<ButtonsListCtrl*>(m_bookctrl); }
Referenced by ChangeSelection(), DoRemovePage(), GetPageText(), InsertPage(), InsertPage(), Rescale(), SetPageImage(), SetPageText(), SetSelection(), and UpdateMode().
GetPageImage()
virtual int Notebook::GetPageImage (size_t WXUNUSEDn) const inline override virtual
    {
        return NO_IMAGE;
    }
GetPageText()
virtual wxString Notebook::GetPageText (size_t n) const inline override virtual
    {
        wxCHECK_MSG(n < GetPageCount(), wxString(), wxS("Invalid page"));
        return GetBtnsListCtrl()->GetPageText(n);
    }
References GetBtnsListCtrl(), ButtonsListCtrl::GetPageText(), and n.
Init()
void Notebook::Init () private
{
    // We don't need any border as we don't have anything to separate the
    // page contents from.
    SetInternalBorder(0);
    // No effects by default.
    m_showEffect = m_hideEffect = wxSHOW_EFFECT_NONE;
    m_showTimeout = m_hideTimeout = 0;
    /* On Linux, Gstreamer wxMediaCtrl does not seem to get along well with
     * 32-bit X11 visuals (the overlay does not work).  Is this a wxWindows
     * bug?  Is this a Gstreamer bug?  No idea, but it is our problem ...
     * and anyway, this transparency thing just isn't all that interesting,
     * so we just don't do it on Linux.
     */
#ifndef __WXGTK__
    SetBackgroundStyle(wxBG_STYLE_TRANSPARENT);
#endif
}
References m_hideEffect, m_hideTimeout, m_showEffect, and m_showTimeout.
Referenced by Notebook().
InsertPage() [1/2]
virtual bool Notebook::InsertPage (size_t n, wxWindow * page, const wxString & text, bool bSelect = false, int imageId = NO_IMAGE) inline override virtual
    {
        if (!wxBookCtrlBase::InsertPage(n, page, text, bSelect, imageId))
            return false;
        GetBtnsListCtrl()->InsertPage(n, text, bSelect);
        if (!DoSetSelectionAfterInsertion(n, bSelect))
            page->Hide();
        return true;
    }
References GetBtnsListCtrl(), ButtonsListCtrl::InsertPage(), and n.
Referenced by AddPage(), and Slic3r::GUI::Tab::load_current_preset().
InsertPage() [2/2]
bool Notebook::InsertPage (size_t n, wxWindow * page, const wxString & text, const std::string & bmp_name = "", const std::string & inactive_bmp_name = "", bool bSelect = false) inline
    {
        if (!wxBookCtrlBase::InsertPage(n, page, text, bSelect))
            return false;
        GetBtnsListCtrl()->InsertPage(n, text, bSelect, bmp_name, inactive_bmp_name);
        if (bSelect)
            SetSelection(n);
        return true;
    }
References GetBtnsListCtrl(), ButtonsListCtrl::InsertPage(), n, and SetSelection().
MakeChangedEvent()
virtual void Notebook::MakeChangedEvent (wxBookCtrlEvent & event) inline override protected virtual
    {
        event.SetEventType(wxEVT_BOOKCTRL_PAGE_CHANGED);
    }
OnNavigationKey()
void Notebook::OnNavigationKey (wxNavigationKeyEvent & event) inline
    {
        if (event.IsWindowChange()) {
            // change pages
            AdvanceSelection(event.GetDirection());
        }
        else {
            // we get this event in 3 cases
            //
            // a) one of our pages might have generated it because the user TABbed
            // out from it in which case we should propagate the event upwards and
            // our parent will take care of setting the focus to prev/next sibling
            //
            // or
            //
            // b) the parent panel wants to give the focus to us so that we
            // forward it to our selected page. We can't deal with this in
            // OnSetFocus() because we don't know which direction the focus came
            // from in this case and so can't choose between setting the focus to
            // first or last panel child
            //
            // or
            //
            // c) we ourselves (see MSWTranslateMessage) generated the event
            //
            wxWindow* const parent = GetParent();
            // the wxObject* casts are required to avoid MinGW GCC 2.95.3 ICE
            const bool isFromParent = event.GetEventObject() == (wxObject*)parent;
            const bool isFromSelf = event.GetEventObject() == (wxObject*)this;
            const bool isForward = event.GetDirection();
            if (isFromSelf && !isForward)
            {
                // focus is currently on notebook tab and should leave
                // it backwards (Shift-TAB)
                event.SetCurrentFocus(this);
                parent->HandleWindowEvent(event);
            }
            else if (isFromParent || isFromSelf)
            {
                // no, it doesn't come from child, case (b) or (c): forward to a
                // page but only if entering notebook page (i.e. direction is
                // backwards (Shift-TAB) comething from out-of-notebook, or
                // direction is forward (TAB) from ourselves),
                if (m_selection != wxNOT_FOUND &&
                    (!event.GetDirection() || isFromSelf))
                {
                    // so that the page knows that the event comes from it's parent
                    // and is being propagated downwards
                    event.SetEventObject(this);
                    wxWindow* page = m_pages[m_selection];
                    if (!page->HandleWindowEvent(event))
                    {
                        page->SetFocus();
                    }
                    //else: page manages focus inside it itself
                }
                else // otherwise set the focus to the notebook itself
                {
                    SetFocus();
                }
            }
            else
            {
                // it comes from our child, case (a), pass to the parent, but only
                // if the direction is forwards. Otherwise set the focus to the
                // notebook itself. The notebook is always the 'first' control of a
                // page.
                if (!isForward)
                {
                    SetFocus();
                }
                else if (parent)
                {
                    event.SetCurrentFocus(this);
                    parent->HandleWindowEvent(event);
                }
            }
        }
    }
References SetFocus().
Referenced by Create().
Rescale()
void Notebook::Rescale () inline
    {
        GetBtnsListCtrl()->Rescale();
    }
References GetBtnsListCtrl(), and ButtonsListCtrl::Rescale().
Referenced by Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::MainFrame::on_dpi_changed(), and Slic3r::GUI::MainFrame::on_sys_color_changed().
SetEffect()
void Notebook::SetEffect (wxShowEffect effect) inline
    {
        SetEffects(effect, effect);
    }
References SetEffects().
SetEffects()
void Notebook::SetEffects (wxShowEffect showEffect, wxShowEffect hideEffect) inline
    {
        m_showEffect = showEffect;
        m_hideEffect = hideEffect;
    }
References m_hideEffect, and m_showEffect.
Referenced by SetEffect().
SetEffectsTimeouts()
void Notebook::SetEffectsTimeouts (unsigned showTimeout, unsigned hideTimeout) inline
    {
        m_showTimeout = showTimeout;
        m_hideTimeout = hideTimeout;
    }
References m_hideTimeout, and m_showTimeout.
Referenced by SetEffectTimeout().
SetEffectTimeout()
void Notebook::SetEffectTimeout (unsigned timeout) inline
    {
        SetEffectsTimeouts(timeout, timeout);
    }
References SetEffectsTimeouts().
SetFocus()
virtual void Notebook::SetFocus () inline override virtual
    {
        wxWindow* const page = GetCurrentPage();
        if (page)
            page->SetFocus();
    }
Referenced by OnNavigationKey().
SetPageImage() [1/2]
bool Notebook::SetPageImage (size_t n, const std::string & bmp_name) inline
    {
        return GetBtnsListCtrl()->SetPageImage(n, bmp_name);
    }
References GetBtnsListCtrl(), n, and ButtonsListCtrl::SetPageImage().
SetPageImage() [2/2]
virtual bool Notebook::SetPageImage (size_t WXUNUSEDn, int WXUNUSEDimageId) inline override virtual
    {
        return false;
    }
SetPageText()
virtual bool Notebook::SetPageText (size_t n, const wxString & strText) inline override virtual
    {
        wxCHECK_MSG(n < GetPageCount(), false, wxS("Invalid page"));
        GetBtnsListCtrl()->SetPageText(n, strText);
        return true;
    }
References GetBtnsListCtrl(), n, and ButtonsListCtrl::SetPageText().
SetSelection()
virtual int Notebook::SetSelection (size_t n) inline override virtual
    {
        int ret = DoSetSelection(n, SetSelection_SendEvent);
        int new_sel = GetSelection();
        //check the new_sel firstly
        if (new_sel != n) {
            //not allowed, skip it
            return ret;
        }
        GetBtnsListCtrl()->SetSelection(n);
        // check that only the selected page is visible and others are hidden:
        for (size_t page = 0; page < m_pages.size(); page++) {
            wxWindow* win_a = GetPage(page);
            wxWindow* win_b = GetPage(n);
            if (page != n && GetPage(page) != GetPage(n)) {
                m_pages[page]->Hide();
            }
        }
        return ret;
    }
References GetBtnsListCtrl(), n, and ButtonsListCtrl::SetSelection().
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Create(), and InsertPage().
ShowNewPage()
bool Notebook::ShowNewPage (wxWindow * page) inline
    {
        return AddPage(page, wxString(), "", "");
    }
References AddPage().
UpdateMode()
void Notebook::UpdateMode () inline
    {
        GetBtnsListCtrl()->UpdateMode();
    }
References GetBtnsListCtrl(), and ButtonsListCtrl::UpdateMode().
UpdateSelectedPage()
virtual void Notebook::UpdateSelectedPage (size_t WXUNUSEDnewsel) inline override protected virtual
    {
        // Nothing to do here, but must be overridden to avoid the assert in
        // the base class version.
    }
Member Data Documentation
m_ctrl
ButtonsListCtrl* Notebook::m_ctrl { nullptr } private
m_hideEffect
wxShowEffect Notebook::m_hideEffect private
Referenced by DoShowPage(), Init(), and SetEffects().
m_hideTimeout
unsigned Notebook::m_hideTimeout private
Referenced by DoShowPage(), Init(), and SetEffectsTimeouts().
m_showEffect
wxShowEffect Notebook::m_showEffect private
Referenced by DoShowPage(), Init(), and SetEffects().
m_showTimeout
unsigned Notebook::m_showTimeout private
Referenced by DoShowPage(), Init(), and SetEffectsTimeouts().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Notebook.hpp
src/slic3r/GUI/Notebook.cpp