OrcaSlicer: Slic3r::GUI::Plater::priv::Jobs Class Reference
Slic3r::GUI::Plater::priv::Jobs Class Reference
Public Member Functions
Jobs (priv *_m)
void arrange ()
void orient ()
void fill_bed ()
void optimize_rotation ()
void import_sla_arch ()
void print ()
size_t add_job (std::unique_ptr< GUI::Job > &&job)
void start (size_t jid)
void cancel_all ()
void join_all (int wait_ms=0)
void stop_all ()
bool is_any_running () const
Private Member Functions
void before_start () override
Private Attributes
priv * m
size_t m_arrange_id
size_t m_fill_bed_id
size_t m_rotoptimize_id
size_t m_sla_import_id
size_t m_orient_id
std::shared_ptr< NotificationProgressIndicator > m_pri
size_t m_print_id
std::vector< std::unique_ptr< GUI::Job > > m_jobs
Static Private Attributes
static const int ABORT_WAIT_MAX_MS = 10000
Detailed Description
Constructor & Destructor Documentation
Jobs()
Slic3r::GUI::Plater::priv::Jobs::Jobs (priv * _m) inline
                       :
            m(_m),
            m_pri{std::make_shared<NotificationProgressIndicator>(m->notification_manager.get())}
        {
            m_arrange_id = add_job(std::make_unique<ArrangeJob>(m_pri, m->q));
            m_orient_id = add_job(std::make_unique<OrientJob>(m_pri, m->q));
            m_fill_bed_id = add_job(std::make_unique<FillBedJob>(m_pri, m->q));
            m_rotoptimize_id = add_job(std::make_unique<RotoptimizeJob>(m_pri, m->q));
            m_sla_import_id = add_job(std::make_unique<SLAImportJob>(m_pri, m->q));
            //BBS add print id
            m_print_id = add_job(std::make_unique<PrintJob>(m_pri, m->q));
        }
References Slic3r::GUI::ExclusiveJobGroup::add_job(), m, m_arrange_id, m_fill_bed_id, m_orient_id, m_pri, m_print_id, m_rotoptimize_id, m_sla_import_id, and Slic3r::GUI::Plater::priv::q.
Member Function Documentation
add_job()
size_t Slic3r::GUI::ExclusiveJobGroup::add_job (std::unique_ptr< GUI::Job > && job) inline inherited
    {
        m_jobs.emplace_back(std::move(job));
        return m_jobs.size() - 1;
    }
References Slic3r::GUI::ExclusiveJobGroup::m_jobs.
Referenced by Jobs().
arrange()
void Slic3r::GUI::Plater::priv::Jobs::arrange () inline
        {
            m->take_snapshot("Arrange");
            start(m_arrange_id);
        }
References m, m_arrange_id, start, and Slic3r::GUI::Plater::priv::take_snapshot().
before_start()
void Slic3r::GUI::Plater::priv::Jobs::before_start () inline override private virtual
Reimplemented from Slic3r::GUI::ExclusiveJobGroup.
{ m->background_process.stop(); }
References Slic3r::GUI::Plater::priv::background_process, m, and Slic3r::BackgroundSlicingProcess::stop().
cancel_all()
void Slic3r::GUI::ExclusiveJobGroup::cancel_all () inline inherited
{ for (auto& j : m_jobs) j->cancel(); }
References Slic3r::GUI::ExclusiveJobGroup::m_jobs.
Referenced by Slic3r::GUI::ExclusiveJobGroup::stop_all().
fill_bed()
void Slic3r::GUI::Plater::priv::Jobs::fill_bed () inline
        {
            m->take_snapshot("Fill bed");
            start(m_fill_bed_id);
        }
References m, m_fill_bed_id, start, and Slic3r::GUI::Plater::priv::take_snapshot().
import_sla_arch()
void Slic3r::GUI::Plater::priv::Jobs::import_sla_arch () inline
        {
            m->take_snapshot("Import SLA archive");
            start(m_sla_import_id);
        }
References m, m_sla_import_id, start, and Slic3r::GUI::Plater::priv::take_snapshot().
is_any_running()
bool Slic3r::GUI::ExclusiveJobGroup::is_any_running () const inherited
{
    return std::any_of(m_jobs.begin(), m_jobs.end(),
                       [](const std::unique_ptr<GUI::Job> &j) {
        return j->is_running();
    });
}
join_all()
void Slic3r::GUI::ExclusiveJobGroup::join_all (int wait_ms = 0) inherited
{
    std::vector<bool> aborted(m_jobs.size(), false);
    for (size_t jid = 0; jid < m_jobs.size(); ++jid)
        aborted[jid] = m_jobs[jid]->join(wait_ms);
    if (!std::all_of(aborted.begin(), aborted.end(), [](bool t) { return t; }))
        BOOST_LOG_TRIVIAL(error) << "Could not abort a job!";
}
References error.
Referenced by Slic3r::GUI::ExclusiveJobGroup::stop_all().
optimize_rotation()
void Slic3r::GUI::Plater::priv::Jobs::optimize_rotation () inline
        {
            m->take_snapshot("Optimize Rotation");
            start(m_rotoptimize_id);
        }
References m, m_rotoptimize_id, start, and Slic3r::GUI::Plater::priv::take_snapshot().
orient()
void Slic3r::GUI::Plater::priv::Jobs::orient () inline
        {
            m->take_snapshot("Orient");
            start(m_orient_id);
        }
References m, m_orient_id, start, and Slic3r::GUI::Plater::priv::take_snapshot().
print()
void Slic3r::GUI::Plater::priv::Jobs::print () inline
        {
            start(m_print_id);
        }
References m_print_id, and start.
start()
void Slic3r::GUI::ExclusiveJobGroup::start (size_t jid) inherited
{
    assert(jid < m_jobs.size());
    stop_all();
    m_jobs[jid]->start();
}
stop_all()
void Slic3r::GUI::ExclusiveJobGroup::stop_all () inline inherited
{ cancel_all(); join_all(ABORT_WAIT_MAX_MS); }
References Slic3r::GUI::ExclusiveJobGroup::ABORT_WAIT_MAX_MS, Slic3r::GUI::ExclusiveJobGroup::cancel_all(), and Slic3r::GUI::ExclusiveJobGroup::join_all().
Member Data Documentation
ABORT_WAIT_MAX_MS
const int Slic3r::GUI::ExclusiveJobGroup::ABORT_WAIT_MAX_MS = 10000 static private inherited
Referenced by Slic3r::GUI::ExclusiveJobGroup::stop_all().
m
priv* Slic3r::GUI::Plater::priv::Jobs::m private
Referenced by Jobs(), arrange(), before_start(), fill_bed(), import_sla_arch(), optimize_rotation(), and orient().
m_arrange_id
size_t Slic3r::GUI::Plater::priv::Jobs::m_arrange_id private
Referenced by Jobs(), and arrange().
m_fill_bed_id
size_t Slic3r::GUI::Plater::priv::Jobs::m_fill_bed_id private
Referenced by Jobs(), and fill_bed().
m_jobs
std::vector<std::unique_ptr<GUI::Job> > Slic3r::GUI::ExclusiveJobGroup::m_jobs private inherited
Referenced by Slic3r::GUI::ExclusiveJobGroup::add_job(), and Slic3r::GUI::ExclusiveJobGroup::cancel_all().
m_orient_id
size_t Slic3r::GUI::Plater::priv::Jobs::m_orient_id private
Referenced by Jobs(), and orient().
m_pri
std::shared_ptr<NotificationProgressIndicator> Slic3r::GUI::Plater::priv::Jobs::m_pri private
Referenced by Jobs().
m_print_id
size_t Slic3r::GUI::Plater::priv::Jobs::m_print_id private
Referenced by Jobs(), and print().
m_rotoptimize_id
size_t Slic3r::GUI::Plater::priv::Jobs::m_rotoptimize_id private
Referenced by Jobs(), and optimize_rotation().
m_sla_import_id
size_t Slic3r::GUI::Plater::priv::Jobs::m_sla_import_id private
Referenced by Jobs(), and import_sla_arch().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Plater.cpp