OrcaSlicer: Slic3r::GUI::PrinterWebView Class Reference
Slic3r::GUI::PrinterWebView Class Reference
#include <src/slic3r/GUI/PrinterWebView.hpp>
Public Member Functions
PrinterWebView (wxWindow *parent)
virtual ~PrinterWebView ()
void load_url (wxString &url)
void UpdateState ()
void OnClose (wxCloseEvent &evt)
void OnError (wxWebViewEvent &evt)
Private Attributes
wxWebView * m_browser
long m_zoomFactor
Detailed Description
Constructor & Destructor Documentation
PrinterWebView()
Slic3r::GUI::PrinterWebView::PrinterWebView (wxWindow * parent)
        : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize)
 {
    wxBoxSizer* topsizer = new wxBoxSizer(wxVERTICAL);
      // Create the webview
    m_browser = WebView::CreateWebView(this, "");
    if (m_browser == nullptr) {
        wxLogError("Could not init m_browser");
        return;
    }
    Bind(wxEVT_WEBVIEW_ERROR, &PrinterWebView::OnError, this);
    SetSizer(topsizer);
    topsizer->Add(m_browser, wxSizerFlags().Expand().Proportion(1));
    // Log backend information
    if (wxGetApp().get_mode() == comDevelop) {
        wxLogMessage(wxWebView::GetBackendVersionInfo().ToString());
        wxLogMessage("Backend: %s Version: %s", m_browser->GetClassInfo()->GetClassName(),
            wxWebView::GetBackendVersionInfo().ToString());
        wxLogMessage("User Agent: %s", m_browser->GetUserAgent());
    }
    //Zoom
    m_zoomFactor = 100;
    //Connect the idle events
    Bind(wxEVT_CLOSE_WINDOW, &PrinterWebView::OnClose, this);
 }
References Slic3r::comDevelop, WebView::CreateWebView(), m_browser, m_zoomFactor, OnClose(), and OnError().
~PrinterWebView()
Slic3r::GUI::PrinterWebView::~PrinterWebView () virtual
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << " Start";
    SetEvtHandlerEnabled(false);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << " End";
}
Member Function Documentation
load_url()
void Slic3r::GUI::PrinterWebView::load_url (wxString & url)
{
//    this->Show();
//    this->Raise();
    if (m_browser == nullptr)
        return;
    m_browser->LoadURL(url);
    //m_browser->SetFocus();
    UpdateState();
}
References m_browser, and UpdateState().
OnClose()
void Slic3r::GUI::PrinterWebView::OnClose (wxCloseEvent & evt)
{
    this->Hide();
}
Referenced by PrinterWebView().
OnError()
void Slic3r::GUI::PrinterWebView::OnError (wxWebViewEvent & evt)
{
    auto e = "unknown error";
    switch (evt.GetInt()) {
      case wxWEBVIEW_NAV_ERR_CONNECTION:
        e = "wxWEBVIEW_NAV_ERR_CONNECTION";
        break;
      case wxWEBVIEW_NAV_ERR_CERTIFICATE:
        e = "wxWEBVIEW_NAV_ERR_CERTIFICATE";
        break;
      case wxWEBVIEW_NAV_ERR_AUTH:
        e = "wxWEBVIEW_NAV_ERR_AUTH";
        break;
      case wxWEBVIEW_NAV_ERR_SECURITY:
        e = "wxWEBVIEW_NAV_ERR_SECURITY";
        break;
      case wxWEBVIEW_NAV_ERR_NOT_FOUND:
        e = "wxWEBVIEW_NAV_ERR_NOT_FOUND";
        break;
      case wxWEBVIEW_NAV_ERR_REQUEST:
        e = "wxWEBVIEW_NAV_ERR_REQUEST";
        break;
      case wxWEBVIEW_NAV_ERR_USER_CANCELLED:
        e = "wxWEBVIEW_NAV_ERR_USER_CANCELLED";
        break;
      case wxWEBVIEW_NAV_ERR_OTHER:
        e = "wxWEBVIEW_NAV_ERR_OTHER";
        break;
      }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": error loading page %1% %2% %3% %4%") %evt.GetURL() %evt.GetTarget() %e %evt.GetString();
}
Referenced by PrinterWebView().
UpdateState()
void Slic3r::GUI::PrinterWebView::UpdateState ()
Method that retrieves the current state from the web control and updates the GUI the reflect this current state.
{
  // SetTitle(m_browser->GetCurrentTitle());
}
Referenced by load_url().
Member Data Documentation
m_browser
wxWebView* Slic3r::GUI::PrinterWebView::m_browser private
Referenced by PrinterWebView(), and load_url().
m_zoomFactor
long Slic3r::GUI::PrinterWebView::m_zoomFactor private
Referenced by PrinterWebView().
The documentation for this class was generated from the following files:
src/slic3r/GUI/PrinterWebView.hpp
src/slic3r/GUI/PrinterWebView.cpp