OrcaSlicer: Slic3r::_3DScene Struct Reference
Slic3r::_3DScene Struct Reference
#include <src/slic3r/GUI/3DScene.hpp>
Static Public Member Functions
static void thick_lines_to_verts (const Lines &lines, const std::vector< double > &widths, const std::vector< double > &heights, bool closed, double top_z, GLVolume &volume)
static void thick_lines_to_verts (const Lines3 &lines, const std::vector< double > &widths, const std::vector< double > &heights, bool closed, GLVolume &volume)
static void extrusionentity_to_verts (const Polyline &polyline, float width, float height, float print_z, GLVolume &volume)
static void extrusionentity_to_verts (const ExtrusionPath &extrusion_path, float print_z, GLVolume &volume)
static void extrusionentity_to_verts (const ExtrusionPath &extrusion_path, float print_z, const Point &copy, GLVolume &volume)
static void extrusionentity_to_verts (const ExtrusionLoop &extrusion_loop, float print_z, const Point &copy, GLVolume &volume)
static void extrusionentity_to_verts (const ExtrusionMultiPath &extrusion_multi_path, float print_z, const Point &copy, GLVolume &volume)
static void extrusionentity_to_verts (const ExtrusionEntityCollection &extrusion_entity_collection, float print_z, const Point &copy, GLVolume &volume)
static void extrusionentity_to_verts (const ExtrusionEntity *extrusion_entity, float print_z, const Point &copy, GLVolume &volume)
static void polyline3_to_verts (const Polyline3 &polyline, double width, double height, GLVolume &volume)
static void point3_to_verts (const Vec3crd &point, double width, double height, GLVolume &volume)
Detailed Description
Member Function Documentation
extrusionentity_to_verts() [1/7]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionEntity * extrusion_entity, float print_z, const Point & copy, GLVolume & volume) static
{
    if (extrusion_entity != nullptr) {
        auto *extrusion_path = dynamic_cast<const ExtrusionPath*>(extrusion_entity);
        if (extrusion_path != nullptr)
            extrusionentity_to_verts(*extrusion_path, print_z, copy, volume);
        else {
            auto *extrusion_loop = dynamic_cast<const ExtrusionLoop*>(extrusion_entity);
            if (extrusion_loop != nullptr)
                extrusionentity_to_verts(*extrusion_loop, print_z, copy, volume);
            else {
                auto *extrusion_multi_path = dynamic_cast<const ExtrusionMultiPath*>(extrusion_entity);
                if (extrusion_multi_path != nullptr)
                    extrusionentity_to_verts(*extrusion_multi_path, print_z, copy, volume);
                else {
                    auto *extrusion_entity_collection = dynamic_cast<const ExtrusionEntityCollection*>(extrusion_entity);
                    if (extrusion_entity_collection != nullptr)
                        extrusionentity_to_verts(*extrusion_entity_collection, print_z, copy, volume);
                    else {
                        throw Slic3r::RuntimeError("Unexpected extrusion_entity type in to_verts()");
                    }
                }
            }
        }
    }
}
References extrusionentity_to_verts().
extrusionentity_to_verts() [2/7]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionEntityCollection & extrusion_entity_collection, float print_z, const Point & copy, GLVolume & volume) static
{
    for (const ExtrusionEntity *extrusion_entity : extrusion_entity_collection.entities)
        extrusionentity_to_verts(extrusion_entity, print_z, copy, volume);
}
References Slic3r::ExtrusionEntityCollection::entities, and extrusionentity_to_verts().
extrusionentity_to_verts() [3/7]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionLoop & extrusion_loop, float print_z, const Point & copy, GLVolume & volume) static
{
    Lines               lines;
    std::vector<double> widths;
    std::vector<double> heights;
    for (const ExtrusionPath &extrusion_path : extrusion_loop.paths) {
        Polyline            polyline = extrusion_path.polyline;
        polyline.remove_duplicate_points();
        polyline.translate(copy);
        Lines lines_this = polyline.lines();
        append(lines, lines_this);
        widths.insert(widths.end(), lines_this.size(), extrusion_path.width);
        heights.insert(heights.end(), lines_this.size(), extrusion_path.height);
    }
    thick_lines_to_verts(lines, widths, heights, true, print_z, volume);
}
References Slic3r::append(), Slic3r::Polyline::lines(), Slic3r::ExtrusionLoop::paths, Slic3r::MultiPoint::remove_duplicate_points(), thick_lines_to_verts(), and Slic3r::MultiPoint::translate().
extrusionentity_to_verts() [4/7]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionMultiPath & extrusion_multi_path, float print_z, const Point & copy, GLVolume & volume) static
{
    Lines               lines;
    std::vector<double> widths;
    std::vector<double> heights;
    for (const ExtrusionPath &extrusion_path : extrusion_multi_path.paths) {
        Polyline            polyline = extrusion_path.polyline;
        polyline.remove_duplicate_points();
        polyline.translate(copy);
        Lines lines_this = polyline.lines();
        append(lines, lines_this);
        widths.insert(widths.end(), lines_this.size(), extrusion_path.width);
        heights.insert(heights.end(), lines_this.size(), extrusion_path.height);
    }
    thick_lines_to_verts(lines, widths, heights, false, print_z, volume);
}
References Slic3r::append(), Slic3r::Polyline::lines(), Slic3r::ExtrusionMultiPath::paths, Slic3r::MultiPoint::remove_duplicate_points(), thick_lines_to_verts(), and Slic3r::MultiPoint::translate().
extrusionentity_to_verts() [5/7]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionPath & extrusion_path, float print_z, const Point & copy, GLVolume & volume) static
{
    Polyline            polyline = extrusion_path.polyline;
    polyline.remove_duplicate_points();
    polyline.translate(copy);
    Lines               lines = polyline.lines();
    std::vector<double> widths(lines.size(), extrusion_path.width);
    std::vector<double> heights(lines.size(), extrusion_path.height);
    thick_lines_to_verts(lines, widths, heights, false, print_z, volume);
}
References Slic3r::ExtrusionPath::height, Slic3r::Polyline::lines(), Slic3r::ExtrusionPath::polyline, Slic3r::MultiPoint::remove_duplicate_points(), thick_lines_to_verts(), Slic3r::MultiPoint::translate(), and Slic3r::ExtrusionPath::width.
extrusionentity_to_verts() [6/7]
void Slic3r::_3DScene::extrusionentity_to_verts (const ExtrusionPath & extrusion_path, float print_z, GLVolume & volume) static
{
  extrusionentity_to_verts(extrusion_path.polyline, extrusion_path.width, extrusion_path.height, print_z, volume);
}
References extrusionentity_to_verts(), Slic3r::ExtrusionPath::height, Slic3r::ExtrusionPath::polyline, and Slic3r::ExtrusionPath::width.
extrusionentity_to_verts() [7/7]
void Slic3r::_3DScene::extrusionentity_to_verts (const Polyline & polyline, float width, float height, float print_z, GLVolume & volume) static
{
  if (polyline.size() >= 2) {
    size_t num_segments = polyline.size() - 1;
    thick_lines_to_verts(polyline.lines(), std::vector<double>(num_segments, width), std::vector<double>(num_segments, height), false, print_z, volume);
  }
}
References Slic3r::Polyline::lines(), Slic3r::MultiPoint::size(), and thick_lines_to_verts().
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), extrusionentity_to_verts(), extrusionentity_to_verts(), extrusionentity_to_verts(), and Slic3r::GUI::GLGizmoFdmSupports::run_thread().
point3_to_verts()
void Slic3r::_3DScene::point3_to_verts (const Vec3crd & point, double width, double height, GLVolume & volume) static
{
    thick_point_to_verts(point, width, height, volume);
}
References Slic3r::thick_point_to_verts().
polyline3_to_verts()
void Slic3r::_3DScene::polyline3_to_verts (const Polyline3 & polyline, double width, double height, GLVolume & volume) static
{
    Lines3 lines = polyline.lines();
    std::vector<double> widths(lines.size(), width);
    std::vector<double> heights(lines.size(), height);
    thick_lines_to_verts(lines, widths, heights, false, volume);
}
References Slic3r::Polyline3::lines(), and thick_lines_to_verts().
thick_lines_to_verts() [1/2]
void Slic3r::_3DScene::thick_lines_to_verts (const Lines & lines, const std::vector< double > & widths, const std::vector< double > & heights, bool closed, double top_z, GLVolume & volume) static
{
    thick_lines_to_indexed_vertex_array(lines, widths, heights, closed, top_z, volume.indexed_vertex_array);
}
References Slic3r::thick_lines_to_indexed_vertex_array().
Referenced by Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), extrusionentity_to_verts(), extrusionentity_to_verts(), extrusionentity_to_verts(), extrusionentity_to_verts(), and polyline3_to_verts().
thick_lines_to_verts() [2/2]
void Slic3r::_3DScene::thick_lines_to_verts (const Lines3 & lines, const std::vector< double > & widths, const std::vector< double > & heights, bool closed, GLVolume & volume) static
{
    thick_lines_to_indexed_vertex_array(lines, widths, heights, closed, volume.indexed_vertex_array);
}
References Slic3r::thick_lines_to_indexed_vertex_array().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/3DScene.hpp
src/slic3r/GUI/3DScene.cpp