OrcaSlicer: Slic3r::GUI::AmsHumidityTipPopup Class Reference
Slic3r::GUI::AmsHumidityTipPopup Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
AmsHumidityTipPopup (wxWindow *parent)
~AmsHumidityTipPopup ()
void paintEvent (wxPaintEvent &evt)
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Public Attributes
wxStaticBitmap * m_img
Label * m_staticText1
Label * m_staticText2
Label * m_staticText3
Label * m_staticText4
Label * m_staticText_note
Button * m_button_confirm
Detailed Description
Constructor & Destructor Documentation
AmsHumidityTipPopup()
Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup (wxWindow * parent)
    :PopupWindow(parent, wxBORDER_NONE)
{
    SetBackgroundColour(*wxWHITE);
    wxBoxSizer* main_sizer;
    main_sizer = new wxBoxSizer(wxVERTICAL);
    main_sizer->Add(0, 0, 0, wxTOP, 28);
    wxBoxSizer* m_sizer_body;
    m_sizer_body = new wxBoxSizer(wxHORIZONTAL);
    m_img = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("ams_humidity_tips", this, 125), wxDefaultPosition, wxSize(FromDIP(125), FromDIP(145)), 0);
    m_sizer_body->Add(m_img, 0, wxEXPAND | wxALL, 2);
    m_sizer_body->Add(0, 0, 0, wxEXPAND | wxLEFT, FromDIP(18));
    wxBoxSizer* m_sizer_tips = new wxBoxSizer(wxVERTICAL);
    m_staticText1 = new Label(this, _L("Cabin humidity"));
    m_staticText1->SetFont(::Label::Head_13);
    m_staticText2 = new Label(this, _L("Green means that AMS humidity is normal, orange represent humidity is high, red represent humidity is too high.(Hygrometer: lower the better.)"));
    m_staticText2->SetFont(::Label::Body_13);
    m_staticText2->SetSize(wxSize(FromDIP(357), -1));
    m_staticText2->SetMinSize(wxSize(FromDIP(357), -1));
    m_staticText2->SetMaxSize(wxSize(FromDIP(357), -1));
    m_staticText2->Wrap(FromDIP(357));
    m_staticText3 = new Label(this, _L("Desiccant status"));
    m_staticText3->SetFont(::Label::Head_13);
    m_staticText4 = new Label(this, _L("A desiccant status lower than two bars indicates that desiccant may be inactive. Please change the desiccant.(The bars: higher the better.)"));
    m_staticText4->SetFont(::Label::Body_13);
    m_staticText4->SetSize(wxSize(FromDIP(357), -1));
    m_staticText4->SetMinSize(wxSize(FromDIP(357), -1));
    m_staticText4->SetMaxSize(wxSize(FromDIP(357), -1));
    m_staticText4->Wrap(FromDIP(357));
    m_sizer_tips->Add(m_staticText1, 0, wxLEFT|wxRIGHT, 3);
    m_sizer_tips->Add(0,0,0,wxTOP,2);
    m_sizer_tips->Add(m_staticText2, 0, wxLEFT|wxRIGHT, 3);
    m_sizer_tips->Add(0,0,0,wxTOP,8);
    m_sizer_tips->Add(m_staticText3, 0, wxLEFT|wxRIGHT, 3);
    m_sizer_tips->Add(0,0,0,wxTOP,2);
    m_sizer_tips->Add(m_staticText4, 0, wxLEFT|wxRIGHT, 3);
    m_sizer_body->Add(m_sizer_tips, 0, wxEXPAND, 0);
    main_sizer->Add(m_sizer_body, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(20));
    m_staticText_note = new Label(this, _L("Note: When the lid is open or the desiccant pack is changed, it can take hours or a night to absorb the moisture. Low temperatures also slow down the process. During this time, the indicator may not represent the chamber accurately."));
    m_staticText4->SetFont(::Label::Body_13);
    m_staticText_note->SetMinSize(wxSize(FromDIP(523), -1));
    m_staticText_note->SetMaxSize(wxSize(FromDIP(523), -1));
    m_staticText_note->Wrap(FromDIP(523));
    main_sizer->Add(m_staticText_note, 0, wxALL | wxLEFT | wxRIGHT, 22);
    m_button_confirm = new Button(this, _L("OK"));
    StateColor btn_bg_green(std::pair<wxColour, int>(wxColour(27, 136, 68), StateColor::Pressed), std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    m_button_confirm->SetBackgroundColor(btn_bg_green);
    m_button_confirm->SetBorderColor(wxColour(0, 150, 136));
    m_button_confirm->SetTextColor(wxColour(0xFFFFFE));
    m_button_confirm->SetSize(wxSize(FromDIP(72), FromDIP(24)));
    m_button_confirm->SetMinSize(wxSize(FromDIP(72), FromDIP(24)));
    m_button_confirm->SetCornerRadius(FromDIP(12));
    m_button_confirm->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {
         Dismiss();
    });
    Bind(wxEVT_LEFT_UP, [this](auto& e) {
        auto mouse_pos = ClientToScreen(e.GetPosition());
        auto rect = m_button_confirm->ClientToScreen(wxPoint(0, 0));
        if (mouse_pos.x > rect.x && mouse_pos.y > rect.y
            && mouse_pos.x < (rect.x + m_button_confirm->GetSize().x)
            && mouse_pos.y < (rect.y + m_button_confirm->GetSize().y))
        {
            Dismiss();
        }
    });
    main_sizer->Add(m_button_confirm, 0, wxALIGN_CENTER | wxALL, 0);
    main_sizer->Add(0, 0, 0, wxEXPAND | wxTOP, 18);
    SetSizer(main_sizer);
    Layout();
    Fit();
    Bind(wxEVT_PAINT, &AmsHumidityTipPopup::paintEvent, this);
    wxGetApp().UpdateDarkUIWin(this);
}
References _L, Label::Body_13, create_scaled_bitmap(), Label::Head_13, m_button_confirm, m_img, m_staticText1, m_staticText2, m_staticText3, m_staticText4, m_staticText_note, StateColor::Normal, paintEvent(), StateColor::Pressed, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetMinSize(), Button::SetTextColor(), and Label::Wrap().
~AmsHumidityTipPopup()
Slic3r::GUI::AmsHumidityTipPopup::~AmsHumidityTipPopup () inline
{};
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
OnDismiss()
void Slic3r::GUI::AmsHumidityTipPopup::OnDismiss () virtual
{}
paintEvent()
void Slic3r::GUI::AmsHumidityTipPopup::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRoundedRectangle(0, 0, GetSize().x, GetSize().y, 0);
}
Referenced by AmsHumidityTipPopup().
ProcessLeftDown()
bool Slic3r::GUI::AmsHumidityTipPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
Member Data Documentation
m_button_confirm
Button* Slic3r::GUI::AmsHumidityTipPopup::m_button_confirm
Referenced by AmsHumidityTipPopup().
m_img
wxStaticBitmap* Slic3r::GUI::AmsHumidityTipPopup::m_img
Referenced by AmsHumidityTipPopup().
m_staticText1
Label* Slic3r::GUI::AmsHumidityTipPopup::m_staticText1
Referenced by AmsHumidityTipPopup().
m_staticText2
Label* Slic3r::GUI::AmsHumidityTipPopup::m_staticText2
Referenced by AmsHumidityTipPopup().
m_staticText3
Label* Slic3r::GUI::AmsHumidityTipPopup::m_staticText3
Referenced by AmsHumidityTipPopup().
m_staticText4
Label* Slic3r::GUI::AmsHumidityTipPopup::m_staticText4
Referenced by AmsHumidityTipPopup().
m_staticText_note
Label* Slic3r::GUI::AmsHumidityTipPopup::m_staticText_note
Referenced by AmsHumidityTipPopup().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp