OrcaSlicer: ModeButton Class Reference
ModeButton Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
ModeButton (wxWindow *parent, wxWindowID id, const std::string &icon_name="", const wxString &mode=wxEmptyString, const wxSize &size=wxDefaultSize, const wxPoint &pos=wxDefaultPosition)
ModeButton (wxWindow *parent, const wxString &mode=wxEmptyString, const std::string &icon_name="", int px_cnt=16)
~ModeButton ()
void Init (const wxString &mode)
void OnButton (wxCommandEvent &event)
void OnEnterBtn (wxMouseEvent &event)
void OnLeaveBtn (wxMouseEvent &event)
void SetState (const bool state)
bool is_selected ()
void SetBitmap_ (const ScalableBitmap &bmp)
bool SetBitmap_ (const std::string &bmp_name)
void SetBitmapDisabled_ (const ScalableBitmap &bmp)
int GetBitmapHeight ()
void UseDefaultBitmapDisabled ()
void msw_rescale ()
Protected Member Functions
void focus_button (const bool focus)
Private Attributes
bool m_is_selected = false
wxString m_tt_selected
wxString m_tt_focused
wxWindow * m_parent { nullptr }
std::string m_current_icon_name
std::string m_disabled_icon_name
int m_width {-1}
int m_height {-1}
bool m_use_default_disabled_bitmap {false}
int m_px_cnt { 16 }
bool m_has_border {false}
Detailed Description
Constructor & Destructor Documentation
ModeButton() [1/2]
ModeButton::ModeButton (wxWindow * parent, wxWindowID id, const std::string & icon_name = "", const wxString & mode = wxEmptyString, const wxSize & size = wxDefaultSize, const wxPoint & pos = wxDefaultPosition)
                                                           :
    ScalableButton(parent, id, icon_name, mode, size, pos, wxBU_EXACTFIT)
{
    Init(mode);
}
References Init().
ModeButton() [2/2]
ModeButton::ModeButton (wxWindow * parent, const wxString & mode = wxEmptyString, const std::string & icon_name = "", int px_cnt = 16)
                                                     :
    ScalableButton(parent, wxID_ANY, ScalableBitmap(parent, icon_name, px_cnt), mode, wxBU_EXACTFIT)
{
    Init(mode);
}
References Init().
~ModeButton()
ModeButton::~ModeButton () inline
{}
Member Function Documentation
focus_button()
void ModeButton::focus_button (const bool focus) protected
{
    const wxFont& new_font = focus ?
                             Slic3r::GUI::wxGetApp().bold_font() :
                             Slic3r::GUI::wxGetApp().normal_font();
    SetFont(new_font);
#ifdef _WIN32
    GetParent()->Refresh(); // force redraw a background of the selected mode button
#else
    SetForegroundColour(wxSystemSettings::GetColour(focus ? wxSYS_COLOUR_BTNTEXT :
#if defined (__linux__) && defined (__WXGTK3__)
        wxSYS_COLOUR_GRAYTEXT
#elif defined (__linux__) && defined (__WXGTK2__)
        wxSYS_COLOUR_BTNTEXT
#else
        wxSYS_COLOUR_BTNSHADOW
#endif
    ));
#endif /* no _WIN32 */
    Refresh();
    Update();
}
Referenced by OnButton(), OnEnterBtn(), OnLeaveBtn(), and SetState().
GetBitmapHeight()
int ScalableButton::GetBitmapHeight () inherited
{
#ifdef __APPLE__
    return GetBitmap().GetScaledHeight();
#else
    return GetBitmap().GetHeight();
#endif
}
Init()
void ModeButton::Init (const wxString & mode)
{
    std::string mode_str = std::string(mode.ToUTF8());
    //m_tt_focused  = Slic3r::GUI::from_u8((boost::format(_utf8(L("Switch to the %s mode"))) % mode_str).str());
    //m_tt_selected = Slic3r::GUI::from_u8((boost::format(_utf8(L("Current mode is %s"))) % mode_str).str());
    SetBitmapMargins(3, 0);
    //button events
    Bind(wxEVT_BUTTON,          &ModeButton::OnButton, this);
    Bind(wxEVT_ENTER_WINDOW,    &ModeButton::OnEnterBtn, this);
    Bind(wxEVT_LEAVE_WINDOW,    &ModeButton::OnLeaveBtn, this);
}
References OnButton(), OnEnterBtn(), OnLeaveBtn(), and wxEVT_BUTTON.
Referenced by ModeButton(), and ModeButton().
is_selected()
bool ModeButton::is_selected () inline
{ return m_is_selected; }
References m_is_selected.
Referenced by ButtonsListCtrl::OnPaint().
msw_rescale()
void ScalableButton::msw_rescale () inherited
{
    Slic3r::GUI::wxGetApp().UpdateDarkUI(this, m_has_border);
    if (!m_current_icon_name.empty()) {
        wxBitmap bmp = create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt);
        SetBitmap(bmp);
        // BBS: why disappear on hover? why current HBITMAP differ from other
        //SetBitmapCurrent(bmp);
        //SetBitmapPressed(bmp);
        //SetBitmapFocus(bmp);
        if (!m_disabled_icon_name.empty())
            SetBitmapDisabled(create_scaled_bitmap(m_disabled_icon_name, m_parent, m_px_cnt));
        else if (m_use_default_disabled_bitmap)
            SetBitmapDisabled(create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt, true));
    }
    if (m_width > 0 || m_height>0)
    {
        const int em = em_unit(m_parent);
        wxSize size(m_width * em, m_height * em);
        SetMinSize(size);
    }
}
References create_scaled_bitmap(), em_unit(), ScalableButton::m_current_icon_name, ScalableButton::m_disabled_icon_name, ScalableButton::m_has_border, ScalableButton::m_height, ScalableButton::m_parent, ScalableButton::m_px_cnt, ScalableButton::m_use_default_disabled_bitmap, ScalableButton::m_width, and size.
Referenced by Slic3r::GUI::ObjectLayers::msw_rescale(), Slic3r::GUI::ConfigOptionsGroup::msw_rescale(), Slic3r::GUI::ParamsPanel::msw_rescale(), Slic3r::GUI::PlaterPresetComboBox::msw_rescale(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::StatusPanel::on_sys_color_changed(), and Slic3r::GUI::ObjectLayers::sys_color_changed().
OnButton()
void ModeButton::OnButton (wxCommandEvent & event)
{
    m_is_selected = true;
    focus_button(m_is_selected);
    event.Skip();
}
References focus_button(), and m_is_selected.
Referenced by Init().
OnEnterBtn()
void ModeButton::OnEnterBtn (wxMouseEvent & event) inline
{ focus_button(true); event.Skip(); }
References focus_button().
Referenced by Init().
OnLeaveBtn()
void ModeButton::OnLeaveBtn (wxMouseEvent & event) inline
{ focus_button(m_is_selected); event.Skip(); }
References focus_button(), and m_is_selected.
Referenced by Init().
SetBitmap_() [1/2]
void ScalableButton::SetBitmap_ (const ScalableBitmap & bmp) inherited
{
    SetBitmap(bmp.bmp());
    m_current_icon_name = bmp.name();
}
References ScalableBitmap::bmp(), ScalableButton::m_current_icon_name, and ScalableBitmap::name().
Referenced by Slic3r::GUI::StatusPanel::StatusPanel(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::StatusPanel::reset_printing_values(), and Slic3r::GUI::StatusPanel::update_subtask().
SetBitmap_() [2/2]
bool ScalableButton::SetBitmap_ (const std::string & bmp_name) inherited
{
    m_current_icon_name = bmp_name;
    if (m_current_icon_name.empty())
        return false;
    wxBitmap bmp = create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt);
    SetBitmap(bmp);
    SetBitmapCurrent(bmp);
    SetBitmapPressed(bmp);
    SetBitmapFocus(bmp);
    if (m_use_default_disabled_bitmap)
        SetBitmapDisabled(create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt, true));
    return true;
}
References create_scaled_bitmap(), ScalableButton::m_current_icon_name, ScalableButton::m_parent, ScalableButton::m_px_cnt, and ScalableButton::m_use_default_disabled_bitmap.
SetBitmapDisabled_()
void ScalableButton::SetBitmapDisabled_ (const ScalableBitmap & bmp) inherited
{
    SetBitmapDisabled(bmp.bmp());
    m_disabled_icon_name = bmp.name();
}
References ScalableBitmap::bmp(), ScalableButton::m_disabled_icon_name, and ScalableBitmap::name().
SetState()
void ModeButton::SetState (const bool state)
{
    m_is_selected = state;
    focus_button(m_is_selected);
    SetToolTip(state ? m_tt_selected : m_tt_focused);
}
References focus_button(), m_is_selected, m_tt_focused, and m_tt_selected.
UseDefaultBitmapDisabled()
void ScalableButton::UseDefaultBitmapDisabled () inherited
{
    m_use_default_disabled_bitmap = true;
    SetBitmapDisabled(create_scaled_bitmap(m_current_icon_name, m_parent, m_px_cnt, true));
}
References create_scaled_bitmap(), ScalableButton::m_current_icon_name, ScalableButton::m_parent, ScalableButton::m_px_cnt, and ScalableButton::m_use_default_disabled_bitmap.
Member Data Documentation
m_current_icon_name
std::string ScalableButton::m_current_icon_name private inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::msw_rescale(), ScalableButton::SetBitmap_(), ScalableButton::SetBitmap_(), and ScalableButton::UseDefaultBitmapDisabled().
m_disabled_icon_name
std::string ScalableButton::m_disabled_icon_name private inherited
Referenced by ScalableButton::msw_rescale(), and ScalableButton::SetBitmapDisabled_().
m_has_border
bool ScalableButton::m_has_border {false} private inherited
Referenced by ScalableButton::msw_rescale().
m_height
int ScalableButton::m_height {-1} private inherited
Referenced by ScalableButton::ScalableButton(), and ScalableButton::msw_rescale().
m_is_selected
bool ModeButton::m_is_selected = false private
Referenced by is_selected(), OnButton(), OnLeaveBtn(), and SetState().
m_parent
wxWindow* ScalableButton::m_parent { nullptr } private inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::msw_rescale(), ScalableButton::SetBitmap_(), and ScalableButton::UseDefaultBitmapDisabled().
m_px_cnt
int ScalableButton::m_px_cnt { 16 } private inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::msw_rescale(), ScalableButton::SetBitmap_(), and ScalableButton::UseDefaultBitmapDisabled().
m_tt_focused
wxString ModeButton::m_tt_focused private
Referenced by SetState().
m_tt_selected
wxString ModeButton::m_tt_selected private
Referenced by SetState().
m_use_default_disabled_bitmap
bool ScalableButton::m_use_default_disabled_bitmap {false} private inherited
Referenced by ScalableButton::ScalableButton(), ScalableButton::msw_rescale(), ScalableButton::SetBitmap_(), and ScalableButton::UseDefaultBitmapDisabled().
m_width
int ScalableButton::m_width {-1} private inherited
Referenced by ScalableButton::ScalableButton(), and ScalableButton::msw_rescale().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp