OrcaSlicer: Slic3r::BoundingBox Class Reference
Slic3r::BoundingBox Class Reference
#include <src/libslic3r/BoundingBox.hpp>
Public Member Functions
void polygon (Polygon *polygon) const
Polygon polygon () const
BoundingBox rotated (double angle) const
BoundingBox rotated (double angle, const Point &center) const
void rotate (double angle)
void rotate (double angle, const Point &center)
void align_to_grid (const coord_t cell_size)
BoundingBox ()
BoundingBox (const Point &pmin, const Point &pmax)
BoundingBox (const Points &points)
BoundingBox inflated (coordf_t delta) const throw ()
void reset ()
void merge (const Point &point)
void merge (const std::vector< Point > &points)
void merge (const BoundingBoxBase< Point > &bb)
void scale (double factor)
Point size () const
double radius () const
double area () const
void translate (coordf_t x, coordf_t y)
void translate (const Vec2d &v0)
void offset (coordf_t delta)
Point center () const
bool contains (const Point &point) const
bool contains (const BoundingBoxBase< Point > &other) const
bool overlap (const BoundingBoxBase< Point > &other) const
Point operator[] (size_t idx) const
bool operator== (const BoundingBoxBase< Point > &rhs)
bool operator!= (const BoundingBoxBase< Point > &rhs)
Public Attributes
Point min
Point max
bool defined
Friends
BoundingBox get_extents_rotated (const Points &points, double angle)
Detailed Description
Constructor & Destructor Documentation
BoundingBox() [1/3]
Slic3r::BoundingBox::BoundingBox () inline
: BoundingBoxBase<Point>() {}
BoundingBox() [2/3]
Slic3r::BoundingBox::BoundingBox (const Point & pmin, const Point & pmax) inline
: BoundingBoxBase<Point>(pmin, pmax) {}
BoundingBox() [3/3]
Slic3r::BoundingBox::BoundingBox (const Points & points) inline
: BoundingBoxBase<Point>(points) {}
Member Function Documentation
align_to_grid()
void Slic3r::BoundingBox::align_to_grid (const coord_t cell_size)
{
    if (this->defined) {
        min(0) = Slic3r::align_to_grid(min(0), cell_size);
        min(1) = Slic3r::align_to_grid(min(1), cell_size);
    }
}
References Slic3r::align_to_grid(), Slic3r::BoundingBoxBase< Point >::defined, and Slic3r::BoundingBoxBase< Point >::min.
Referenced by Slic3r::SupportGridPattern::SupportGridPattern().
area()
double Slic3r::BoundingBoxBase< Point >::area () const inline inherited
{ return double(this->max(0) - this->min(0)) * (this->max(1) - this->min(1));    } // BBS
center()
template Vec2d Slic3r::BoundingBoxBase< Point >::center inherited
{
    return (this->min + this->max) / 2;
}
contains() [1/2]
bool Slic3r::BoundingBoxBase< Point >::contains (const BoundingBoxBase< Point > & other) const inline inherited
{
        return contains(other.min) && contains(other.max);
    }
contains() [2/2]
bool Slic3r::BoundingBoxBase< Point >::contains (const Point & point) const inline inherited
{
        return point(0) >= this->min(0) && point(0) <= this->max(0)
            && point(1) >= this->min(1) && point(1) <= this->max(1);
    }
inflated()
BoundingBox Slic3r::BoundingBox::inflated (coordf_t delta) const throw () inline
{ BoundingBox out(*this); out.offset(delta); return out; }
References out.
Referenced by Slic3r::FillPlanePath::_fill_surface_single(), Slic3r::connect_brim_lines(), Slic3r::ExPolygon::contains(), Slic3r::create_boundary_infill_graph(), Slic3r::TreeSupport::generate_contact_points(), Slic3r::FillLightning::Generator::generateTrees(), Slic3r::FillLightning::Generator::generateTreesforSupport(), Slic3r::mark_boundary_segments_touching_infill(), and Slic3r::GCode::needs_retraction().
merge() [1/3]
void Slic3r::BoundingBoxBase< Point >::merge (const BoundingBoxBase< Point > & bb) inherited
{
    assert(bb.defined || bb.min(0) >= bb.max(0) || bb.min(1) >= bb.max(1));
    if (bb.defined) {
        if (this->defined) {
            this->min = this->min.cwiseMin(bb.min);
            this->max = this->max.cwiseMax(bb.max);
        } else {
            this->min = bb.min;
            this->max = bb.max;
            this->defined = true;
        }
    }
}
merge() [2/3]
void Slic3r::BoundingBoxBase< Point >::merge (const Point & point) inherited
{
    if (this->defined) {
        this->min = this->min.cwiseMin(point);
        this->max = this->max.cwiseMax(point);
    } else {
        this->min = point;
        this->max = point;
        this->defined = true;
    }
}
merge() [3/3]
void Slic3r::BoundingBoxBase< Point >::merge (const std::vector< Point > & points) inherited
{
    this->merge(BoundingBoxBase(points));
}
offset()
template void Slic3r::BoundingBoxBase< Point >::offset (coordf_t delta) inherited
{
    PointClass v(delta, delta);
    this->min -= v;
    this->max += v;
}
operator!=()
bool Slic3r::BoundingBoxBase< Point >::operator!= (const BoundingBoxBase< Point > & rhs) inline inherited
{ return ! (*this == rhs); }
operator==()
bool Slic3r::BoundingBoxBase< Point >::operator== (const BoundingBoxBase< Point > & rhs) inline inherited
{ return this->min == rhs.min && this->max == rhs.max; }
operator[]()
Point Slic3r::BoundingBoxBase< Point >::operator[] (size_t idx) const inline inherited
{
        switch (idx) {
        case 0:
            return min;
            break;
        case 1:
            return PointClass(max(0), min(1));
            break;
        case 2:
            return max;
            break;
        case 3:
            return PointClass(min(0), max(1));
            break;
        default:
            return PointClass();
            break;
        }
        return PointClass();
    }
overlap()
bool Slic3r::BoundingBoxBase< Point >::overlap (const BoundingBoxBase< Point > & other) const inline inherited
{
        return ! (this->max(0) < other.min(0) || this->min(0) > other.max(0) ||
                  this->max(1) < other.min(1) || this->min(1) > other.max(1));
    }
polygon() [1/2]
Polygon Slic3r::BoundingBox::polygon () const
{
    Polygon p;
    this->polygon(&p);
    return p;
}
References polygon().
Referenced by polygon(), and polygon().
polygon() [2/2]
void Slic3r::BoundingBox::polygon (Polygon * polygon) const
{
    polygon->points.clear();
    polygon->points.resize(4);
    polygon->points[0](0) = this->min(0);
    polygon->points[0](1) = this->min(1);
    polygon->points[1](0) = this->max(0);
    polygon->points[1](1) = this->min(1);
    polygon->points[2](0) = this->max(0);
    polygon->points[2](1) = this->max(1);
    polygon->points[3](0) = this->min(0);
    polygon->points[3](1) = this->max(1);
}
References Slic3r::BoundingBoxBase< Point >::max, Slic3r::BoundingBoxBase< Point >::min, Slic3r::MultiPoint::points, and polygon().
Referenced by Slic3r::FillHoneycomb::_fill_surface_single(), Slic3r::GCode::needs_retraction(), and Slic3r::GUI::PartPlateList::preprocess_nonprefered_areas().
radius()
template double Slic3r::BoundingBoxBase< Point >::radius inherited
{
    assert(this->defined);
    double x = this->max(0) - this->min(0);
    double y = this->max(1) - this->min(1);
    return 0.5 * sqrt(x*x+y*y);
}
reset()
void Slic3r::BoundingBoxBase< Point >::reset () inline inherited
{ this->defined = false; this->min = PointClass::Zero(); this->max = PointClass::Zero(); }
rotate() [1/2]
void Slic3r::BoundingBox::rotate (double angle) inline
{ (*this) = this->rotated(angle); }
References Slic3r::angle().
rotate() [2/2]
void Slic3r::BoundingBox::rotate (double angle, const Point & center) inline
{ (*this) = this->rotated(angle, center); }
References Slic3r::angle().
rotated() [1/2]
BoundingBox Slic3r::BoundingBox::rotated (double angle) const
{
    BoundingBox out;
    out.merge(this->min.rotated(angle));
    out.merge(this->max.rotated(angle));
    out.merge(Point(this->min(0), this->max(1)).rotated(angle));
    out.merge(Point(this->max(0), this->min(1)).rotated(angle));
    return out;
}
References Slic3r::BoundingBoxBase< Point >::max, Slic3r::BoundingBoxBase< Point >::min, out, rotated(), and Slic3r::Point::rotated().
Referenced by Slic3r::FillPlanePath::_fill_surface_single(), and rotated().
rotated() [2/2]
BoundingBox Slic3r::BoundingBox::rotated (double angle, const Point & center) const
{
    BoundingBox out;
    out.merge(this->min.rotated(angle, center));
    out.merge(this->max.rotated(angle, center));
    out.merge(Point(this->min(0), this->max(1)).rotated(angle, center));
    out.merge(Point(this->max(0), this->min(1)).rotated(angle, center));
    return out;
}
References Slic3r::BoundingBoxBase< Point >::center(), Slic3r::BoundingBoxBase< Point >::min, out, and Slic3r::Point::rotated().
scale()
template void Slic3r::BoundingBoxBase< Point >::scale (double factor) inherited
{
    this->min *= factor;
    this->max *= factor;
}
size()
template Vec2d Slic3r::BoundingBoxBase< Point >::size inherited
{
    return PointClass(this->max(0) - this->min(0), this->max(1) - this->min(1));
}
translate() [1/2]
void Slic3r::BoundingBoxBase< Point >::translate (const Vec2d & v0) inline inherited
{ PointClass v(v0.x(), v0.y()); this->min += v; this->max += v; }
translate() [2/2]
void Slic3r::BoundingBoxBase< Point >::translate (coordf_t x, coordf_t y) inline inherited
{ assert(this->defined); PointClass v(x, y); this->min += v; this->max += v; }
Friends And Related Symbol Documentation
get_extents_rotated
BoundingBox get_extents_rotated (const Points & points, double angle) friend
{
    BoundingBox bbox;
    if (! points.empty()) {
        double s = sin(angle);
        double c = cos(angle);
        Points::const_iterator it = points.begin();
        double cur_x = (double)(*it)(0);
        double cur_y = (double)(*it)(1);
        bbox.min(0) = bbox.max(0) = (coord_t)round(c * cur_x - s * cur_y);
        bbox.min(1) = bbox.max(1) = (coord_t)round(c * cur_y + s * cur_x);
        for (++it; it != points.end(); ++it) {
            double cur_x = (double)(*it)(0);
            double cur_y = (double)(*it)(1);
            coord_t x = (coord_t)round(c * cur_x - s * cur_y);
            coord_t y = (coord_t)round(c * cur_y + s * cur_x);
            bbox.min(0) = std::min(x, bbox.min(0));
            bbox.min(1) = std::min(y, bbox.min(1));
            bbox.max(0) = std::max(x, bbox.max(0));
            bbox.max(1) = std::max(y, bbox.max(1));
        }
        bbox.defined = true;
    }
    return bbox;
}
Member Data Documentation
defined
bool Slic3r::BoundingBoxBase< Point >::defined inherited
max
Point Slic3r::BoundingBoxBase< Point >::max inherited
min
Point Slic3r::BoundingBoxBase< Point >::min inherited
The documentation for this class was generated from the following files:
src/libslic3r/BoundingBox.hpp
src/libslic3r/BoundingBox.cpp