OrcaSlicer: Slic3r::BBLStatusBarBind Class Reference
Slic3r::BBLStatusBarBind Class Reference
#include <src/slic3r/GUI/BBLStatusBarBind.hpp>
Public Types
using CancelFn = std::function< void()>
Cancel callback function type.
Public Member Functions
BBLStatusBarBind (wxWindow *parent=nullptr, int id=-1)
~BBLStatusBarBind ()=default
int get_progress () const
void set_prog_block ()
void set_progress (int) override
int get_range () const override
void set_range (int=100) override
void clear_percent () override
void show_networking_test (wxString msg) override
void show_progress (bool)
void start_busy (int=100)
void stop_busy ()
void set_cancel_callback_fina (BBLStatusBarBind::CancelFn ccb)
bool is_busy () const
void set_cancel_callback (CancelFn=CancelFn()) override
void reset_cancel_callback ()
wxPanel * get_panel ()
void set_status_text (const wxString &txt)
void set_percent_text (const wxString &txt)
void msw_rescale ()
void set_status_text (const std::string &txt)
void set_status_text (const char *txt) override
wxString get_status_text () const
void set_font (const wxFont &font)
void set_object_info (const wxString &txt)
void set_slice_info (const wxString &txt)
void show_slice_info (bool show)
bool is_slice_info_shown ()
bool update_status (wxString &msg, bool &was_cancel, int percent=-1, bool yield=true)
void reset ()
void show_cancel_button ()
void hide_cancel_button ()
Private Attributes
wxPanel * m_self
wxGauge * m_prog
Button * m_cancelbutton
wxStaticText * m_status_text
wxStaticText * m_stext_percent
wxBoxSizer * m_sizer
wxBoxSizer * m_sizer_eline
bool m_busy = false
bool m_was_cancelled = false
CancelFn m_cancel_cb
CancelFn m_cancel_cb_fina
Detailed Description
Member Typedef Documentation
CancelFn
using Slic3r::ProgressIndicator::CancelFn = std::function<void()> inherited
Cancel callback function type.
Constructor & Destructor Documentation
BBLStatusBarBind()
Slic3r::BBLStatusBarBind::BBLStatusBarBind (wxWindow * parent = nullptr, int id = -1)
 : m_self{new wxPanel(parent, id == -1 ? wxID_ANY : id)}
    , m_sizer(new wxBoxSizer(wxHORIZONTAL))
{
    m_self->SetBackgroundColour(wxColour(255,255,255));
    m_self->SetMinSize(wxSize(m_self->FromDIP(450), m_self->FromDIP(30)));
    //wxBoxSizer *m_sizer_bottom = new wxBoxSizer(wxHORIZONTAL);
   /* m_status_text = new wxStaticText(m_self, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, 0);
    m_status_text->SetForegroundColour(wxColour(107, 107, 107));
    m_status_text->SetFont(::Label::Body_13);
    m_status_text->Wrap(-1);
    m_sizer_body->Add(m_status_text, 0, 0, 0);*/
    m_prog = new wxGauge(m_self, wxID_ANY, 100, wxDefaultPosition, wxSize(m_self->FromDIP(400), m_self->FromDIP(6)), wxGA_HORIZONTAL);
    m_prog->SetValue(0);
    m_stext_percent = new wxStaticText(m_self, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, 0);
    m_stext_percent->SetForegroundColour(wxColour(107, 107, 107));
    m_stext_percent->SetFont(::Label::Body_13);
    m_stext_percent->Wrap(-1);
    m_sizer->Add(m_prog, 1, wxALIGN_CENTER, 0);
    m_sizer->Add(0, 0, 1, wxEXPAND, 0);
    m_sizer->Add(m_stext_percent, 1, wxALIGN_CENTER, 0);
    //m_sizer->Add(m_sizer_bottom, 1, wxALIGN_CENTER, 0);
    m_self->SetSizer(m_sizer);
    m_self->Layout();
    m_sizer->Fit(m_self);
    //set_prog_block();
}
References Label::Body_13, m_prog, m_self, m_sizer, m_stext_percent, wxGauge, and wxStaticText.
~BBLStatusBarBind()
Slic3r::BBLStatusBarBind::~BBLStatusBarBind () default
Member Function Documentation
clear_percent()
void Slic3r::BBLStatusBarBind::clear_percent () override virtual
Implements Slic3r::ProgressIndicator.
{
}
get_panel()
wxPanel * Slic3r::BBLStatusBarBind::get_panel ()
{
    return m_self;
}
References m_self.
get_progress()
int Slic3r::BBLStatusBarBind::get_progress () const
{
    return m_prog->GetValue();
}
References m_prog.
get_range()
int Slic3r::BBLStatusBarBind::get_range () const override virtual
Implements Slic3r::ProgressIndicator.
{
    return m_prog->GetRange();
}
References m_prog.
get_status_text()
wxString Slic3r::BBLStatusBarBind::get_status_text () const
{
    return m_status_text->GetLabelText();
}
References m_status_text.
hide_cancel_button()
void Slic3r::BBLStatusBarBind::hide_cancel_button ()
{
    m_sizer->Hide(m_cancelbutton);
    m_sizer->Layout();
}
References m_cancelbutton, and m_sizer.
Referenced by stop_busy().
is_busy()
bool Slic3r::BBLStatusBarBind::is_busy () const inline
{ return m_busy; }
References m_busy.
is_slice_info_shown()
bool Slic3r::BBLStatusBarBind::is_slice_info_shown ()
msw_rescale()
void Slic3r::BBLStatusBarBind::msw_rescale ()
{
    set_prog_block();
    m_cancelbutton->SetMinSize(wxSize(m_self->FromDIP(56), m_self->FromDIP(24)));
}
References m_cancelbutton, m_self, set_prog_block(), and Button::SetMinSize().
reset()
void Slic3r::BBLStatusBarBind::reset ()
{
    set_status_text("");
    m_was_cancelled = false;
    set_progress(0);
}
References m_was_cancelled, set_progress(), and set_status_text().
reset_cancel_callback()
void Slic3r::BBLStatusBarBind::reset_cancel_callback () inline
{ set_cancel_callback(); }
References set_cancel_callback().
set_cancel_callback()
void Slic3r::BBLStatusBarBind::set_cancel_callback (BBLStatusBarBind::CancelFn ccb = CancelFn()) override virtual
Implements Slic3r::ProgressIndicator.
{
    /*  m_cancel_cb = ccb;
      if (ccb) {
          m_sizer->Show(m_cancelbutton);
      }
      else {
          m_sizer->Hide(m_cancelbutton);
      }
      m_sizer->Layout();*/
}
Referenced by reset_cancel_callback().
set_cancel_callback_fina()
void Slic3r::BBLStatusBarBind::set_cancel_callback_fina (BBLStatusBarBind::CancelFn ccb)
{
    m_cancel_cb_fina = ccb;
     if (ccb) {
        m_sizer->Show(m_cancelbutton);
    } else {
        m_sizer->Hide(m_cancelbutton);
    }
}
References m_cancel_cb_fina, m_cancelbutton, and m_sizer.
set_font()
void Slic3r::BBLStatusBarBind::set_font (const wxFont & font)
{
    m_self->SetFont(font);
}
References m_self.
set_object_info()
void Slic3r::BBLStatusBarBind::set_object_info (const wxString & txt)
set_percent_text()
void Slic3r::BBLStatusBarBind::set_percent_text (const wxString & txt)
{
    m_stext_percent->SetLabelText(txt);
}
References m_stext_percent.
Referenced by set_progress().
set_prog_block()
void Slic3r::BBLStatusBarBind::set_prog_block ()
{
}
Referenced by msw_rescale(), and set_progress().
set_progress()
void Slic3r::BBLStatusBarBind::set_progress (int val) override virtual
Implements Slic3r::ProgressIndicator.
{
    set_prog_block();
    if(val < 0)
        return;
    if (!m_sizer->IsShown(m_prog)) {
        m_sizer->Show(m_prog);
        m_sizer->Show(m_cancelbutton);
    }
    m_prog->SetValue(val);
    set_percent_text(wxString::Format("%d%%", val));
    m_sizer->Layout();
}
References m_cancelbutton, m_prog, m_sizer, set_percent_text(), and set_prog_block().
Referenced by reset(), and update_status().
set_range()
void Slic3r::BBLStatusBarBind::set_range (int val = 100) override virtual
Implements Slic3r::ProgressIndicator.
{
    if(val != m_prog->GetRange()) {
        m_prog->SetRange(val);
    }
}
References m_prog.
set_slice_info()
void Slic3r::BBLStatusBarBind::set_slice_info (const wxString & txt)
set_status_text() [1/3]
void Slic3r::BBLStatusBarBind::set_status_text (const char * txt) override virtual
Implements Slic3r::ProgressIndicator.
{
    this->set_status_text(wxString::FromUTF8(txt));
}
References set_status_text().
set_status_text() [2/3]
void Slic3r::BBLStatusBarBind::set_status_text (const std::string & txt)
{
    this->set_status_text(txt.c_str());
}
References set_status_text().
set_status_text() [3/3]
void Slic3r::BBLStatusBarBind::set_status_text (const wxString & txt)
{
    //auto txtss = "Sending the printing task has timed out.\nPlease try again!";
    //auto txtss = "The printing project is being uploaded... 25%%";
    //m_status_text->SetLabelText(txtss);
    //m_status_text->SetLabelText(txt);
}
Referenced by reset(), set_status_text(), set_status_text(), and update_status().
show_cancel_button()
void Slic3r::BBLStatusBarBind::show_cancel_button ()
{
    m_sizer->Show(m_cancelbutton);
    m_sizer->Layout();
}
References m_cancelbutton, and m_sizer.
Referenced by start_busy().
show_networking_test()
void Slic3r::BBLStatusBarBind::show_networking_test (wxString msg) override virtual
Implements Slic3r::ProgressIndicator.
{
}
show_progress()
void Slic3r::BBLStatusBarBind::show_progress (bool show)
{
    if (show) {
        m_sizer->Show(m_prog);
        m_sizer->Layout();
    }
    else {
        //m_sizer->Hide(m_prog);
        m_sizer->Layout();
    }
}
References m_prog, and m_sizer.
Referenced by start_busy(), and stop_busy().
show_slice_info()
void Slic3r::BBLStatusBarBind::show_slice_info (bool show)
start_busy()
void Slic3r::BBLStatusBarBind::start_busy (int rate = 100)
{
    m_busy = true;
    show_progress(true);
    show_cancel_button();
}
References m_busy, show_cancel_button(), and show_progress().
stop_busy()
void Slic3r::BBLStatusBarBind::stop_busy ()
{
    show_progress(false);
    hide_cancel_button();
    m_prog->SetValue(0);
    m_sizer->Layout();
    m_busy = false;
}
References hide_cancel_button(), m_busy, m_prog, m_sizer, and show_progress().
update_status()
bool Slic3r::BBLStatusBarBind::update_status (wxString & msg, bool & was_cancel, int percent = -1, bool yield = true)
{
    set_status_text(msg);
    if (percent >= 0)
        this->set_progress(percent);
    if (yield)
        wxEventLoopBase::GetActive()->YieldFor(wxEVT_CATEGORY_UI | wxEVT_CATEGORY_USER_INPUT);
    was_cancel = m_was_cancelled;
    return true;
}
References m_was_cancelled, set_progress(), and set_status_text().
Member Data Documentation
m_busy
bool Slic3r::BBLStatusBarBind::m_busy = false private
Referenced by is_busy(), start_busy(), and stop_busy().
m_cancel_cb
CancelFn Slic3r::BBLStatusBarBind::m_cancel_cb private
m_cancel_cb_fina
CancelFn Slic3r::BBLStatusBarBind::m_cancel_cb_fina private
Referenced by set_cancel_callback_fina().
m_cancelbutton
Button* Slic3r::BBLStatusBarBind::m_cancelbutton private
Referenced by hide_cancel_button(), msw_rescale(), set_cancel_callback_fina(), set_progress(), and show_cancel_button().
m_prog
wxGauge* Slic3r::BBLStatusBarBind::m_prog private
Referenced by BBLStatusBarBind(), get_progress(), get_range(), set_progress(), set_range(), show_progress(), and stop_busy().
m_self
wxPanel* Slic3r::BBLStatusBarBind::m_self private
Referenced by BBLStatusBarBind(), get_panel(), msw_rescale(), and set_font().
m_sizer
wxBoxSizer* Slic3r::BBLStatusBarBind::m_sizer private
Referenced by BBLStatusBarBind(), hide_cancel_button(), set_cancel_callback_fina(), set_progress(), show_cancel_button(), show_progress(), and stop_busy().
m_sizer_eline
wxBoxSizer* Slic3r::BBLStatusBarBind::m_sizer_eline private
m_status_text
wxStaticText* Slic3r::BBLStatusBarBind::m_status_text private
Referenced by get_status_text().
m_stext_percent
wxStaticText* Slic3r::BBLStatusBarBind::m_stext_percent private
Referenced by BBLStatusBarBind(), and set_percent_text().
m_was_cancelled
bool Slic3r::BBLStatusBarBind::m_was_cancelled = false private
Referenced by reset(), and update_status().
The documentation for this class was generated from the following files:
src/slic3r/GUI/BBLStatusBarBind.hpp
src/slic3r/GUI/BBLStatusBarBind.cpp