OrcaSlicer: libnest2d::svg::SVGWriter< RawShape > Class Template Reference
libnest2d::svg::SVGWriter< RawShape > Class Template Reference
#include <src/libnest2d/tools/svgtools.hpp>
Classes
struct Config
Public Types
enum OrigoLocation { TOPLEFT , BOTTOMLEFT }
Public Member Functions
SVGWriter (const Config &conf=Config())
void setSize (const Box &box)
void writeShape (RawShape tsh, std::string fill="none", std::string stroke="black", float stroke_width=1)
void writeItem (const Item &item, std::string fill="none", std::string stroke="black", float stroke_width=1)
void writePackGroup (const PackGroup &result)
template<class ItemIt >
void writeItems (ItemIt from, ItemIt to)
void draw_text (float x, float y, const std::string text, const std::string color, int font_size)
void addLayer ()
void finishLayer ()
void save (const std::string &filepath)
void save (const boost::filesystem::path &filepath)
Public Attributes
Config conf_
Private Types
using Item = _Item< RawShape >
using Coord = TCoord< TPoint< RawShape > >
using Box = _Box< TPoint< RawShape > >
using PackGroup = _PackGroup< RawShape >
Private Member Functions
std::string & currentLayer ()
const std::string header () const
Private Attributes
std::vector< std::string > svg_layers_
bool finished_ = false
Detailed Description
template<class RawShape>
class libnest2d::svg::SVGWriter< RawShape >
Member Typedef Documentation
Box
template<class RawShape > using libnest2d::svg::SVGWriter< RawShape >::Box = _Box<TPoint<RawShape> > private
Coord
template<class RawShape > using libnest2d::svg::SVGWriter< RawShape >::Coord = TCoord<TPoint<RawShape> > private
Item
template<class RawShape > using libnest2d::svg::SVGWriter< RawShape >::Item = _Item<RawShape> private
PackGroup
template<class RawShape > using libnest2d::svg::SVGWriter< RawShape >::PackGroup = _PackGroup<RawShape> private
Member Enumeration Documentation
OrigoLocation
template<class RawShape > enum libnest2d::svg::SVGWriter::OrigoLocation
Enumerator
TOPLEFT
BOTTOMLEFT
                       {
        TOPLEFT,
        BOTTOMLEFT
    };
Constructor & Destructor Documentation
SVGWriter()
template<class RawShape > libnest2d::svg::SVGWriter< RawShape >::SVGWriter (const Config & conf = Config()) inline
                                            :
        conf_(conf) {}
Member Function Documentation
addLayer()
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::addLayer () inline
                    {
        svg_layers_.emplace_back(header());
        finished_ = false;
    }
References libnest2d::svg::SVGWriter< RawShape >::finished_, libnest2d::svg::SVGWriter< RawShape >::header(), and libnest2d::svg::SVGWriter< RawShape >::svg_layers_.
Referenced by libnest2d::svg::SVGWriter< RawShape >::writePackGroup(), and libnest2d::svg::SVGWriter< RawShape >::writeShape().
currentLayer()
template<class RawShape > std::string & libnest2d::svg::SVGWriter< RawShape >::currentLayer () inline private
{ return svg_layers_.back(); }
References libnest2d::svg::SVGWriter< RawShape >::svg_layers_.
Referenced by libnest2d::svg::SVGWriter< RawShape >::draw_text(), libnest2d::svg::SVGWriter< RawShape >::finishLayer(), and libnest2d::svg::SVGWriter< RawShape >::writeShape().
draw_text()
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::draw_text (float x, float y, const std::string text, const std::string color, int font_size) inline
    {
        char s[500];
        sprintf(s,
            "<text x=\"%f\" y=\"%f\" font-family=\"sans-serif\" font-size=\"%dpx\" fill=\"%s\">%s</text>\n",
            x,y, font_size, color.c_str(), text.c_str());
        currentLayer() += s;
    }
References libnest2d::svg::SVGWriter< RawShape >::currentLayer().
finishLayer()
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::finishLayer () inline
                       {
        currentLayer() += "\n</svg>\n";
        finished_ = true;
    }
References libnest2d::svg::SVGWriter< RawShape >::currentLayer(), and libnest2d::svg::SVGWriter< RawShape >::finished_.
Referenced by libnest2d::svg::SVGWriter< RawShape >::writePackGroup().
header()
template<class RawShape > const std::string libnest2d::svg::SVGWriter< RawShape >::header () const inline private
{
        std::string svg_header =
R"raw(<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.0//EN" "http://www.w3.org/TR/2001/REC-SVG-20010904/DTD/svg10.dtd">
<svg height=")raw";
        svg_header += std::to_string(conf_.height) + "\" width=\"" + std::to_string(conf_.width) + "\" ";
        svg_header += R"raw(xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">)raw";
References libnest2d::svg::SVGWriter< RawShape >::conf_, libnest2d::svg::SVGWriter< RawShape >::Config::height, and libnest2d::svg::SVGWriter< RawShape >::Config::width.
Referenced by libnest2d::svg::SVGWriter< RawShape >::addLayer().
save() [1/2]
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::save (const boost::filesystem::path & filepath) inline
    {
        size_t lyrc = svg_layers_.size() > 1 ? 1 : 0;
        size_t last = svg_layers_.size() > 1 ? svg_layers_.size() : 0;
        for (auto &lyr : svg_layers_) {
            boost::filesystem::ofstream out(filepath, std::fstream::out);
            if (out.is_open()) out << lyr;
            if (lyrc == last && !finished_) out << "\n</svg>\n";
            out.flush();
            out.close();
            lyrc++;
        };
    }
References libnest2d::svg::SVGWriter< RawShape >::finished_, out, and libnest2d::svg::SVGWriter< RawShape >::svg_layers_.
save() [2/2]
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::save (const std::string & filepath) inline
{
        size_t lyrc = svg_layers_.size() > 1? 1 : 0;
        size_t last = svg_layers_.size() > 1? svg_layers_.size() : 0;
        for(auto& lyr : svg_layers_) {
            std::fstream out(filepath + (lyrc > 0? std::to_string(lyrc) : "") +
                             ".svg", std::fstream::out);
            if(out.is_open()) out << lyr;
            if(lyrc == last && !finished_) out << "\n</svg>\n";
            out.flush(); out.close(); lyrc++;
        };
    }
References libnest2d::svg::SVGWriter< RawShape >::finished_, out, and libnest2d::svg::SVGWriter< RawShape >::svg_layers_.
Referenced by libnest2d::selections::_FirstFitSelection< RawShape >::packItems().
setSize()
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::setSize (const Box & box) inline
{
        conf_.x0     = box.width() / 5;
        conf_.x0     = box.height() / 5;
        conf_.height = static_cast<double>(box.height() + conf_.y0*2) /
                conf_.mm_in_coord_units;
        conf_.width  = static_cast<double>(box.width() + conf_.x0*2) /
                conf_.mm_in_coord_units;
    }
References libnest2d::svg::SVGWriter< RawShape >::conf_, libnest2d::_Box< P >::height(), libnest2d::svg::SVGWriter< RawShape >::Config::height, libnest2d::svg::SVGWriter< RawShape >::Config::mm_in_coord_units, libnest2d::_Box< P >::width(), libnest2d::svg::SVGWriter< RawShape >::Config::width, libnest2d::svg::SVGWriter< RawShape >::Config::x0, and libnest2d::svg::SVGWriter< RawShape >::Config::y0.
writeItem()
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::writeItem (const Item & item, std::string fill = "none", std::string stroke = "black", float stroke_width = 1) inline
{
        writeShape(item.transformedShape(), fill, stroke, stroke_width);
    }
References libnest2d::_Item< RawShape >::transformedShape(), and libnest2d::svg::SVGWriter< RawShape >::writeShape().
Referenced by libnest2d::svg::SVGWriter< RawShape >::writePackGroup().
writeItems()
template<class RawShape > template<class ItemIt > void libnest2d::svg::SVGWriter< RawShape >::writeItems (ItemIt from, ItemIt to) inline
{
        auto it = from;
        PackGroup pg;
        while(it != to) {
            if(it->binId() == BIN_ID_UNSET) continue;
            while(pg.size() <= size_t(it->binId())) pg.emplace_back();
            pg[it->binId()].emplace_back(*it);
            ++it;
        }
        writePackGroup(pg);
    }
References libnest2d::BIN_ID_UNSET, and libnest2d::svg::SVGWriter< RawShape >::writePackGroup().
writePackGroup()
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::writePackGroup (const PackGroup & result) inline
{
        for(auto r : result) {
            addLayer();
            for(Item& sh : r) {
                writeItem(sh);
            }
            finishLayer();
        }
    }
References libnest2d::svg::SVGWriter< RawShape >::addLayer(), libnest2d::svg::SVGWriter< RawShape >::finishLayer(), and libnest2d::svg::SVGWriter< RawShape >::writeItem().
Referenced by libnest2d::svg::SVGWriter< RawShape >::writeItems().
writeShape()
template<class RawShape > void libnest2d::svg::SVGWriter< RawShape >::writeShape (RawShape tsh, std::string fill = "none", std::string stroke = "black", float stroke_width = 1) inline
{
        if(svg_layers_.empty()) addLayer();
        if(conf_.origo_location == BOTTOMLEFT) {
            auto d = static_cast<Coord>(
                std::round(conf_.height*conf_.mm_in_coord_units) );
            auto& contour = shapelike::contour(tsh);
            for (auto &v : contour) {
                setX(v, getX(v) + conf_.x0); // right shift so we can draw outside the bounding box
                setY(v, -getY(v) + d + conf_.y0);
            }
            auto& holes = shapelike::holes(tsh);
            for (auto &h : holes)
                for (auto &v : h) {
                    setX(v, getX(v) + conf_.x0);
                    setY(v, -getY(v) + d + conf_.y0);
                }
        }
        currentLayer() +=
            shapelike::serialize<Formats::SVG>(tsh,
                                               1.0 / conf_.mm_in_coord_units, fill, stroke, stroke_width) +
            "\n";
    }
References libnest2d::svg::SVGWriter< RawShape >::addLayer(), libnest2d::svg::SVGWriter< RawShape >::BOTTOMLEFT, libnest2d::svg::SVGWriter< RawShape >::conf_, libnest2d::shapelike::contour(), libnest2d::svg::SVGWriter< RawShape >::currentLayer(), libnest2d::getX(), libnest2d::getY(), libnest2d::svg::SVGWriter< RawShape >::Config::height, libnest2d::shapelike::holes(), libnest2d::svg::SVGWriter< RawShape >::Config::mm_in_coord_units, libnest2d::svg::SVGWriter< RawShape >::Config::origo_location, libnest2d::setX(), libnest2d::setY(), libnest2d::svg::SVGWriter< RawShape >::svg_layers_, libnest2d::svg::SVGWriter< RawShape >::Config::x0, and libnest2d::svg::SVGWriter< RawShape >::Config::y0.
Referenced by libnest2d::selections::_FirstFitSelection< RawShape >::packItems(), and libnest2d::svg::SVGWriter< RawShape >::writeItem().
Member Data Documentation
conf_
template<class RawShape > Config libnest2d::svg::SVGWriter< RawShape >::conf_
Referenced by libnest2d::svg::SVGWriter< RawShape >::header(), libnest2d::svg::SVGWriter< RawShape >::setSize(), and libnest2d::svg::SVGWriter< RawShape >::writeShape().
finished_
template<class RawShape > bool libnest2d::svg::SVGWriter< RawShape >::finished_ = false private
Referenced by libnest2d::svg::SVGWriter< RawShape >::addLayer(), libnest2d::svg::SVGWriter< RawShape >::finishLayer(), libnest2d::svg::SVGWriter< RawShape >::save(), and libnest2d::svg::SVGWriter< RawShape >::save().
svg_layers_
template<class RawShape > std::vector<std::string> libnest2d::svg::SVGWriter< RawShape >::svg_layers_ private
Referenced by libnest2d::svg::SVGWriter< RawShape >::addLayer(), libnest2d::svg::SVGWriter< RawShape >::currentLayer(), libnest2d::svg::SVGWriter< RawShape >::save(), libnest2d::svg::SVGWriter< RawShape >::save(), and libnest2d::svg::SVGWriter< RawShape >::writeShape().
The documentation for this class was generated from the following file:
src/libnest2d/tools/svgtools.hpp