OrcaSlicer: src/qhull/src/libqhull_r/random_r.h File Reference
random_r.h File Reference
#include "libqhull_r.h"
Functions
int qh_argv_to_command (int argc, char *argv[], char *command, int max_size)
int qh_argv_to_command_size (int argc, char *argv[])
int qh_rand (qhT *qh)
void qh_srand (qhT *qh, int seed)
realT qh_randomfactor (qhT *qh, realT scale, realT offset)
void qh_randommatrix (qhT *qh, realT *buffer, int dim, realT **row)
int qh_strtol (const char *s, char **endp)
double qh_strtod (const char *s, char **endp)
Function Documentation
qh_argv_to_command()
int qh_argv_to_command (int argc, char * argv[], char * command, int max_size)
{
  int i, remaining;
  char *s;
  *command= '\0';  /* max_size > 0 */
  if (argc) {
    if ((s= strrchr( argv[0], '\\')) /* get filename w/o .exe extension */
    || (s= strrchr( argv[0], '/')))
        s++;
    else
        s= argv[0];
    if ((int)strlen(s) < max_size)   /* WARN64 */
        strcpy(command, s);
    else
        goto error_argv;
    if ((s= strstr(command, ".EXE"))
    ||  (s= strstr(command, ".exe")))
        *s= '\0';
  }
  for (i=1; i < argc; i++) {
    s= argv[i];
    remaining= max_size - (int)strlen(command) - (int)strlen(s) - 2;   /* WARN64 */
    if (!*s || strchr(s, ' ')) {
      char *t= command + strlen(command);
      remaining -= 2;
      if (remaining < 0) {
        goto error_argv;
      }
      *t++= ' ';
      *t++= '"';
      while (*s) {
        if (*s == '"') {
          if (--remaining < 0)
            goto error_argv;
          *t++= '\\';
        }
        *t++= *s++;
      }
      *t++= '"';
      *t= '\0';
    }else if (remaining < 0) {
      goto error_argv;
    }else
      strcat(command, " ");
      strcat(command, s);
  }
  return 1;
error_argv:
  return 0;
} /* argv_to_command */
References int.
Referenced by main(), qh_init_qhull_command(), and qh_init_qhull_command().
qh_argv_to_command_size()
int qh_argv_to_command_size (int argc, char * argv[])
{
    unsigned int count= 1; /* null-terminator if argc==0 */
    int i;
    char *s;
    for (i=0; i<argc; i++){
      count += (int)strlen(argv[i]) + 1;   /* WARN64 */
      if (i>0 && strchr(argv[i], ' ')) {
        count += 2;  /* quote delimiters */
        for (s=argv[i]; *s; s++) {
          if (*s == '"') {
            count++;
          }
        }
      }
    }
    return count;
} /* argv_to_command_size */
References count, and int.
Referenced by main().
qh_rand()
int qh_rand (qhT * qh)
                     {
    int lo, hi, test;
    int seed = qh->last_random;
    hi = seed / qh_rand_q;  /* seed div q */
    lo = seed % qh_rand_q;  /* seed mod q */
    test = qh_rand_a * lo - qh_rand_r * hi;
    if (test > 0)
        seed= test;
    else
        seed= test + qh_rand_m;
    qh->last_random= seed;
    /* seed = seed < qh_RANDOMmax/2 ? 0 : qh_RANDOMmax;  for testing */
    /* seed = qh_RANDOMmax;  for testing */
    return seed;
} /* rand */
qh_randomfactor()
realT qh_randomfactor (qhT * qh, realT scale, realT offset)
{
    realT randr;
    randr= qh_RANDOMint;
    return randr * scale + offset;
} /* randomfactor */
References realT, and scale().
qh_randommatrix()
void qh_randommatrix (qhT * qh, realT * buffer, int dim, realT ** row)
{
    int i, k;
    realT **rowi, *coord, realr;
    coord= buffer;
    rowi= rows;
    for (i=0; i < dim; i++) {
        *(rowi++)= coord;
        for (k=0; k < dim; k++) {
            realr= qh_RANDOMint;
            *(coord++)= 2.0 * realr/(qh_RANDOMmax+1) - 1.0;
        }
    }
    *rowi= coord;
} /* randommatrix */
qh_srand()
void qh_srand (qhT * qh, int seed)
{
    if (seed < 1)
        qh->last_random= 1;
    else if (seed >= qh_rand_m)
        qh->last_random= qh_rand_m - 1;
    else
        qh->last_random= seed;
} /* qh_srand */
qh_strtod()
double qh_strtod (const char * s, char ** endp)
{
  double result;
  result= strtod(s, endp);
  if (s < (*endp) && (*endp)[-1] == ' ')
    (*endp)--;
  return result;
} /* strtod */
Referenced by qh_checkflags(), qh_checkflags(), qh_initflags(), qh_initflags(), qh_initthresholds(), qh_initthresholds(), qh_rboxpoints(), qh_rboxpoints(), qh_readfeasible(), qh_readfeasible(), qh_readpoints(), qh_readpoints(), qh_setfeasible(), and qh_setfeasible().
qh_strtol()
int qh_strtol (const char * s, char ** endp)
{
  int result;
  result= (int) strtol(s, endp, 10);     /* WARN64 */
  if (s< (*endp) && (*endp)[-1] == ' ')
    (*endp)--;
  return result;
} /* strtol */
References int.
Referenced by qh_initflags(), qh_initflags(), qh_initthresholds(), qh_initthresholds(), qh_rboxpoints(), qh_rboxpoints(), qh_readpoints(), and qh_readpoints().