OrcaSlicer: src/mcut/include/mcut/mcut.h File Reference
mcut.h File Reference
API-function implementations.
#include "platform.h"
Macros
#define MC_MAKE_VERSION(major, minor, patch) (((major) << 22) | ((minor) << 12) | (patch))
#define MC_API_VERSION_1_0 MC_MAKE_VERSION(1, 0, 0)
#define MC_API_VERSION_1_1 MC_MAKE_VERSION(1, 1, 0)
#define MC_API_VERSION_1_2 MC_MAKE_VERSION(1, 2, 0)
#define MC_VERSION_MAJOR(version) ((uint32_t)(version) >> 22)
#define MC_VERSION_MINOR(version) (((uint32_t)(version) >> 12) & 0x3ff)
#define MC_VERSION_PATCH(version) ((uint32_t)(version)&0xfff)
#define MC_HEADER_VERSION 100
#define MC_HEADER_VERSION_COMPLETE MC_MAKE_VERSION(1, 2, MC_HEADER_VERSION)
#define MC_NULL_HANDLE 0
#define MC_DEFINE_HANDLE(object) typedef struct object##_T* object;
#define MC_UNDEFINED_VALUE UINT32_MAX
#define MC_TRUE (1)
Boolean constant for "true".
#define MC_FALSE (0)
Boolean constant for "false".
Typedefs
typedef struct McConnectedComponent_T * McConnectedComponent
Connected component handle.
typedef struct McContext_T * McContext
Context handle.
typedef struct McEvent_T * McEvent
Event handle.
typedef void McVoid
typedef int8_t McChar
8 bit signed char.
typedef int32_t McInt32
32 bit signed integer.
typedef uint32_t McUint32
32 bit unsigned integer.
typedef uint32_t McFlags
Bitfield type.
typedef size_t McSize
Byte size type.
typedef uint32_t McIndex
32-bit unsigned type.
typedef float McFloat
32-bit floating point type.
typedef double McDouble
64-bit floating point type.
typedef uint32_t McBool
32-bit type.
typedef enum McResult McResult
typedef enum McConnectedComponentType McConnectedComponentType
typedef enum McFragmentLocation McFragmentLocation
typedef enum McFragmentSealType McFragmentSealType
typedef enum McPatchLocation McPatchLocation
typedef enum McSeamOrigin McSeamOrigin
typedef enum McInputOrigin McInputOrigin
typedef enum McConnectedComponentData McConnectedComponentData
typedef enum McDebugSource McDebugSource
typedef enum McDebugType McDebugType
typedef enum McDebugSeverity McDebugSeverity
typedef enum McContextCreationFlags McContextCreationFlags
typedef enum McDispatchFlags McDispatchFlags
typedef enum McEventCommandExecStatus McEventCommandExecStatus
typedef enum McCommandType McCommandType
typedef enum McConnectedComponentFaceWindingOrder McConnectedComponentFaceWindingOrder
typedef enum McQueryFlags McQueryFlags
typedef void(MCAPI_PTR * pfn_mcDebugOutput_CALLBACK) (McDebugSource source, McDebugType type, unsigned int id, McDebugSeverity severity, size_t length, const char *message, const McVoid *userParam)
Debug callback function signature type.
typedef void(MCAPI_PTR * pfn_McEvent_CALLBACK) (McEvent event, McVoid *data)
Event callback function signature type.
Enumerations
enum McResult {
MC_NO_ERROR = 0 , MC_INVALID_OPERATION = -(1 << 1) , MC_INVALID_VALUE = -(1 << 2) , MC_OUT_OF_MEMORY = -(1 << 3) ,
MC_RESULT_MAX_ENUM = 0xFFFFFFFF
}
API return codes.
enum McConnectedComponentType {
MC_CONNECTED_COMPONENT_TYPE_FRAGMENT = (1 << 0) , MC_CONNECTED_COMPONENT_TYPE_PATCH = (1 << 2) , MC_CONNECTED_COMPONENT_TYPE_SEAM = (1 << 3) , MC_CONNECTED_COMPONENT_TYPE_INPUT = (1 << 4) ,
MC_CONNECTED_COMPONENT_TYPE_ALL = 0xFFFFFFFF
}
The possible types of connected components.
enum McFragmentLocation { MC_FRAGMENT_LOCATION_ABOVE = 1 << 0 , MC_FRAGMENT_LOCATION_BELOW = 1 << 1 , MC_FRAGMENT_LOCATION_UNDEFINED = 1 << 2 , MC_FRAGMENT_LOCATION_ALL = 0xFFFFFFFF }
The possible geometrical locations of a fragment (connected component), which are defined with-respect-to the cut-mesh.
enum McFragmentSealType { MC_FRAGMENT_SEAL_TYPE_COMPLETE = 1 << 0 , MC_FRAGMENT_SEAL_TYPE_NONE = 1 << 2 , MC_FRAGMENT_SEAL_TYPE_ALL = 0xFFFFFFFF }
Topological configurations of a fragment as defined with-respect-to hole-filling/sealing.
enum McPatchLocation { MC_PATCH_LOCATION_INSIDE = 1 << 0 , MC_PATCH_LOCATION_OUTSIDE = 1 << 1 , MC_PATCH_LOCATION_UNDEFINED = 1 << 2 , MC_PATCH_LOCATION_ALL = 0xFFFFFFFF }
The possible geometrical locations of a patch as defined with-respect-to the source-mesh.
enum McSeamOrigin { MC_SEAM_ORIGIN_SRCMESH = 1 << 0 , MC_SEAM_ORIGIN_CUTMESH = 1 << 1 , MC_SEAM_ORIGIN_ALL = 0xFFFFFFFF }
The input mesh from which a seam is derived.
enum McInputOrigin { MC_INPUT_ORIGIN_SRCMESH = 1 << 0 , MC_INPUT_ORIGIN_CUTMESH = 1 << 1 , MC_INPUT_ORIGIN_ALL = 0xFFFFFFFF }
The user-provided input mesh from which an input connected component is derived.
enum McConnectedComponentData {
MC_CONNECTED_COMPONENT_DATA_VERTEX_FLOAT = (1 << 1) , MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE = (1 << 2) , MC_CONNECTED_COMPONENT_DATA_DISPATCH_PERTURBATION_VECTOR = (1 << 4) , MC_CONNECTED_COMPONENT_DATA_FACE = (1 << 5) ,
MC_CONNECTED_COMPONENT_DATA_FACE_SIZE = (1 << 6) , MC_CONNECTED_COMPONENT_DATA_EDGE = (1 << 8) , MC_CONNECTED_COMPONENT_DATA_TYPE = (1 << 9) , MC_CONNECTED_COMPONENT_DATA_FRAGMENT_LOCATION = (1 << 10) ,
MC_CONNECTED_COMPONENT_DATA_PATCH_LOCATION = (1 << 11) , MC_CONNECTED_COMPONENT_DATA_FRAGMENT_SEAL_TYPE = (1 << 12) , MC_CONNECTED_COMPONENT_DATA_SEAM_VERTEX = (1 << 13) , MC_CONNECTED_COMPONENT_DATA_ORIGIN = (1 << 14) ,
MC_CONNECTED_COMPONENT_DATA_VERTEX_MAP = (1 << 15) , MC_CONNECTED_COMPONENT_DATA_FACE_MAP = (1 << 16) , MC_CONNECTED_COMPONENT_DATA_FACE_ADJACENT_FACE = (1 << 17) , MC_CONNECTED_COMPONENT_DATA_FACE_ADJACENT_FACE_SIZE = (1 << 18) ,
MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION = (1 << 19) , MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION_MAP = (1 << 20)
}
Data that can be queried about a connected component.
enum McDebugSource {
MC_DEBUG_SOURCE_API = 1 << 0 , MC_DEBUG_SOURCE_KERNEL = 1 << 1 , MC_DEBUG_SOURCE_FRONTEND = 1 << 2 , MC_DEBUG_SOURCE_IGNORE = 1 << 3 ,
MC_DEBUG_SOURCE_ALL = 0xFFFFFFFF
}
Source of a debug log message.
enum McDebugType {
MC_DEBUG_TYPE_ERROR = 1 << 0 , MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 1 << 1 , MC_DEBUG_TYPE_OTHER = 1 << 2 , MC_DEBUG_TYPE_IGNORE = 1 << 3 ,
MC_DEBUG_TYPE_ALL = 0xFFFFFFFF
}
Type of debug messages.
enum McDebugSeverity {
MC_DEBUG_SEVERITY_HIGH = 1 << 0 , MC_DEBUG_SEVERITY_MEDIUM = 1 << 1 , MC_DEBUG_SEVERITY_LOW = 1 << 2 , MC_DEBUG_SEVERITY_NOTIFICATION = 1 << 3 ,
MC_DEBUG_SEVERITY_IGNORE = 1 << 3 , MC_DEBUG_SEVERITY_ALL = 0xFFFFFFFF
}
Severity levels of messages.
enum McContextCreationFlags { MC_DEBUG = (1 << 0) , MC_OUT_OF_ORDER_EXEC_MODE_ENABLE = (1 << 1) , MC_PROFILING_ENABLE = (1 << 2) }
Context creation flags.
enum McDispatchFlags {
MC_DISPATCH_VERTEX_ARRAY_FLOAT = (1 << 0) , MC_DISPATCH_VERTEX_ARRAY_DOUBLE = (1 << 1) , MC_DISPATCH_REQUIRE_THROUGH_CUTS = (1 << 2) , MC_DISPATCH_INCLUDE_VERTEX_MAP = (1 << 3) ,
MC_DISPATCH_INCLUDE_FACE_MAP = (1 << 4) , MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE = (1 << 5) , MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW = (1 << 6) , MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED = (1 << 7) ,
MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE = (1 << 8) , MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE = (1 << 9) , MC_DISPATCH_FILTER_FRAGMENT_SEALING_NONE = (1 << 10) , MC_DISPATCH_FILTER_PATCH_INSIDE = (1 << 11) ,
MC_DISPATCH_FILTER_PATCH_OUTSIDE = (1 << 12) , MC_DISPATCH_FILTER_SEAM_SRCMESH = (1 << 13) , MC_DISPATCH_FILTER_SEAM_CUTMESH = (1 << 14) , MC_DISPATCH_FILTER_ALL ,
MC_DISPATCH_ENFORCE_GENERAL_POSITION = (1 << 15) , MC_DISPATCH_ENFORCE_GENERAL_POSITION_ABSOLUTE = (1 << 16)
}
Dispatch configuration flags.
enum McEventCommandExecStatus { MC_SUBMITTED = 1 << 0 , MC_RUNNING = 1 << 1 , MC_COMPLETE = 1 << 2 }
enum McCommandType {
MC_COMMAND_DISPATCH = 1 << 0 , MC_COMMAND_GET_CONNECTED_COMPONENTS = 1 << 1 , MC_COMMAND_GET_CONNECTED_COMPONENT_DATA = 1 << 2 , MC_COMMAND_USER = 1 << 3 ,
MC_COMMAND_UKNOWN
}
Flags for identifying event commands.
enum McConnectedComponentFaceWindingOrder { MC_CONNECTED_COMPONENT_FACE_WINDING_ORDER_AS_GIVEN = 1 << 0 , MC_CONNECTED_COMPONENT_FACE_WINDING_ORDER_REVERSED = 1 << 1 }
Flags for specifying the state used to determine winding order of queried faces.
enum McQueryFlags {
MC_CONTEXT_FLAGS = 1 << 0 , MC_DONT_CARE = 1 << 1 , MC_EVENT_RUNTIME_EXECUTION_STATUS = 1 << 2 , MC_EVENT_TIMESTAMP_SUBMIT = 1 << 3 ,
MC_EVENT_TIMESTAMP_START = 1 << 4 , MC_EVENT_TIMESTAMP_END = 1 << 5 , MC_EVENT_COMMAND_EXECUTION_STATUS = 1 << 6 , MC_EVENT_CONTEXT = 1 << 7 ,
MC_EVENT_COMMAND_TYPE = 1 << 8 , MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH = 1 << 9 , MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT = 1 << 10 , MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS = 1<<11 ,
MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER = 1<<12
}
Flags for querying fixed API state.
Functions
MCAPI_ATTR McResult MCAPI_CALL mcCreateContext (McContext *pContext, McFlags flags)
Create an MCUT context.
MCAPI_ATTR McResult MCAPI_CALL mcCreateContextWithHelpers (McContext *pOutContext, McFlags contextFlags, uint32_t helperThreadCount)
Create an MCUT context object with N helper threads.
MCAPI_ATTR McResult MCAPI_CALL mcDebugMessageCallback (McContext context, pfn_mcDebugOutput_CALLBACK cb, const McVoid *userParam)
Specify a callback to receive debugging messages from the MCUT library.
MCAPI_ATTR McResult MCAPI_CALL mcGetDebugMessageLog (McContext context, McUint32 count, McSize bufSize, McDebugSource *sources, McDebugType *types, McDebugSeverity *severities, McSize *lengths, McChar *messageLog, McUint32 *numFetched)
Returns messages stored in an internal log.
MCAPI_ATTR McResult MCAPI_CALL mcDebugMessageControl (McContext context, McDebugSource source, McDebugType type, McDebugSeverity severity, bool enabled)
MCAPI_ATTR McResult MCAPI_CALL mcCreateUserEvent (McEvent *event, McContext context)
To create a user event object, call the function.
MCAPI_ATTR McResult MCAPI_CALL mcSetUserEventStatus (McEvent event, McInt32 execution_status)
To set the execution status of a user event object, call the function.
MCAPI_ATTR McResult MCAPI_CALL mcGetEventInfo (const McEvent event, McFlags info, McSize bytes, McVoid *pMem, McSize *pNumBytes)
Returns information about the event object..
MCAPI_ATTR McResult MCAPI_CALL mcSetEventCallback (McEvent event, pfn_McEvent_CALLBACK pfn_notify, McVoid *user_data)
Registers a user callback function.
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueDispatch (const McContext context, McFlags dispatchFlags, const McVoid *pSrcMeshVertices, const uint32_t *pSrcMeshFaceIndices, const uint32_t *pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid *pCutMeshVertices, const uint32_t *pCutMeshFaceIndices, const uint32_t *pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent)
Execute a cutting operation with two meshes - the source mesh, and the cut mesh.
MCAPI_ATTR McResult MCAPI_CALL mcDispatch (McContext context, McFlags flags, const McVoid *pSrcMeshVertices, const uint32_t *pSrcMeshFaceIndices, const uint32_t *pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid *pCutMeshVertices, const uint32_t *pCutMeshFaceIndices, const uint32_t *pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces)
Blocking version of mcEnqueueDispatch.
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueDispatchPlanarSection (const McContext context, McFlags dispatchFlags, const McVoid *pSrcMeshVertices, const uint32_t *pSrcMeshFaceIndices, const uint32_t *pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McDouble *pNormalVector, const McDouble sectionOffset, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent)
MCAPI_ATTR McResult MCAPI_CALL mcGetInfo (const McContext context, McFlags info, McSize bytes, McVoid *pMem, McSize *pNumBytes)
Return the value of a selected parameter.
MCAPI_ATTR McResult MCAPI_CALL mcBindState (const McContext context, McFlags stateInfo, McSize bytes, const McVoid *pMem)
Set the value of a selected parameter of a context.
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueGetConnectedComponents (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent *pConnComps, uint32_t *numConnComps, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent)
Query the connected components available in a context.
MCAPI_ATTR McResult MCAPI_CALL mcGetConnectedComponents (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent *pConnComps, uint32_t *numConnComps)
Blocking version of mcEnqueueGetConnectedComponents.
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueGetConnectedComponentData (const McContext context, const McConnectedComponent connCompId, McFlags queryFlags, McSize bytes, McVoid *pMem, McSize *pNumBytes, uint32_t numEventsInWaitlist, const McEvent *pEventWaitList, McEvent *pEvent)
Query specific information about a connected component.
MCAPI_ATTR McResult MCAPI_CALL mcGetConnectedComponentData (const McContext context, const McConnectedComponent connCompId, McFlags flags, McSize bytes, McVoid *pMem, McSize *pNumBytes)
Blocking version of mcEnqueueGetConnectedComponents.
MCAPI_ATTR McResult MCAPI_CALL mcWaitForEvents (uint32_t numEventsInWaitlist, const McEvent *pEventWaitList)
Waits on the user thread for commands identified by event objects to complete.
MCAPI_ATTR McResult MCAPI_CALL mcReleaseEvents (uint32_t numEvents, const McEvent *pEvents)
Decrements the event reference count.
MCAPI_ATTR McResult MCAPI_CALL mcReleaseConnectedComponents (const McContext context, uint32_t numConnComps, const McConnectedComponent *pConnComps)
To release the memory of a connected component, call this function.
MCAPI_ATTR McResult MCAPI_CALL mcReleaseContext (McContext context)
To release the memory of a context, call this function.
Detailed Description
API-function implementations.
File containing the MCUT applications programming interface (API).
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
Author
Floyd M. Chitalu
Date
11 July 2022
NOTE: This header file defines the pre- and post-cutting processing of mesh data, which includes any intermediate correctons/modifications to the user's input meshes like 'polygon partitioning'.
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
Author
Floyd M. Chitalu
Date
22 July 2022
NOTE: This header file defines the frontend implementation of mcDispatch, which handles mesh preparation (BVH building, traversal, polygon partitioning etc).
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
Author
Floyd M. Chitalu
Date
1 Jan 2021
NOTE: This header file defines all the functionality and accessible features of MCUT. The interface is a standard C API.
Definition in file mcut.h.
Macro Definition Documentation
MC_API_VERSION_1_0
#define MC_API_VERSION_1_0 MC_MAKE_VERSION(1, 0, 0)
MCUT 1.0 version number
MC_API_VERSION_1_1
#define MC_API_VERSION_1_1 MC_MAKE_VERSION(1, 1, 0)
MCUT 1.1 version number
MC_API_VERSION_1_2
#define MC_API_VERSION_1_2 MC_MAKE_VERSION(1, 2, 0)
MCUT 1.2 version number
MC_DEFINE_HANDLE
#define MC_DEFINE_HANDLE (object) typedef struct object##_T* object;
Helper-macro to define opaque handles
MC_FALSE
#define MC_FALSE (0)
Boolean constant for "false".
Integral constant representing a boolean value evaluating to false.
MC_HEADER_VERSION
#define MC_HEADER_VERSION 100
Version of this file
MC_HEADER_VERSION_COMPLETE
#define MC_HEADER_VERSION_COMPLETE MC_MAKE_VERSION(1, 2, MC_HEADER_VERSION)
Complete version of this file
MC_MAKE_VERSION
#define MC_MAKE_VERSION (major, minor, patch) (((major) << 22) | ((minor) << 12) | (patch))
Macro to encode MCUT version
MC_NULL_HANDLE
#define MC_NULL_HANDLE 0
Constant value assigned to null variables and parameters
MC_TRUE
#define MC_TRUE (1)
Boolean constant for "true".
Integral constant representing a boolean value evaluating to true.
MC_UNDEFINED_VALUE
#define MC_UNDEFINED_VALUE UINT32_MAX
A garbage value that is assigned to undefined index values
MC_VERSION_MAJOR
#define MC_VERSION_MAJOR (version) ((uint32_t)(version) >> 22)
Macro to decode MCUT version (MAJOR) from MC_HEADER_VERSION_COMPLETE
MC_VERSION_MINOR
#define MC_VERSION_MINOR (version) (((uint32_t)(version) >> 12) & 0x3ff)
Macro to decode MCUT version (MINOR) from MC_HEADER_VERSION_COMPLETE
MC_VERSION_PATCH
#define MC_VERSION_PATCH (version) ((uint32_t)(version)&0xfff)
Macro to decode MCUT version (PATCH) from MC_HEADER_VERSION_COMPLETE
Typedef Documentation
McBool
typedef uint32_t McBool
32-bit type.
Integral type representing a boolean value (MC_TRUE or MC_FALSE).
McChar
typedef int8_t McChar
8 bit signed char.
Integral type representing a 8-bit signed char.
McCommandType
typedef enum McCommandType McCommandType
McConnectedComponent
typedef struct McConnectedComponent_T* McConnectedComponent
Connected component handle.
Opaque type referencing a connected component which the client/user must use to access mesh data after a dispatch call.
McConnectedComponentData
typedef enum McConnectedComponentData McConnectedComponentData
McConnectedComponentFaceWindingOrder
typedef enum McConnectedComponentFaceWindingOrder McConnectedComponentFaceWindingOrder
McConnectedComponentType
typedef enum McConnectedComponentType McConnectedComponentType
McContext
typedef struct McContext_T* McContext
Context handle.
Opaque type referencing a working state (e.g. independent thread) which the client/user must use to initialise, dispatch, and access data.
McContextCreationFlags
typedef enum McContextCreationFlags McContextCreationFlags
McDebugSeverity
typedef enum McDebugSeverity McDebugSeverity
McDebugSource
typedef enum McDebugSource McDebugSource
McDebugType
typedef enum McDebugType McDebugType
McDispatchFlags
typedef enum McDispatchFlags McDispatchFlags
McDouble
typedef double McDouble
64-bit floating point type.
Floating point type type representing a 64-bit real number value.
McEvent
typedef struct McEvent_T* McEvent
Event handle.
Opaque type that can be used to identify async tasks.
McEventCommandExecStatus
typedef enum McEventCommandExecStatus McEventCommandExecStatus
McFlags
typedef uint32_t McFlags
Bitfield type.
Integral type representing a 32-bit bitfield for storing parameter values.
McFloat
typedef float McFloat
32-bit floating point type.
Floating point type type representing a 32-bit real number value.
McFragmentLocation
typedef enum McFragmentLocation McFragmentLocation
McFragmentSealType
typedef enum McFragmentSealType McFragmentSealType
McIndex
typedef uint32_t McIndex
32-bit unsigned type.
Integral type representing an index value.
McInputOrigin
typedef enum McInputOrigin McInputOrigin
McInt32
typedef int32_t McInt32
32 bit signed integer.
Integral type representing a 32-bit signed integer.
McPatchLocation
typedef enum McPatchLocation McPatchLocation
McQueryFlags
typedef enum McQueryFlags McQueryFlags
McResult
typedef enum McResult McResult
McSeamOrigin
typedef enum McSeamOrigin McSeamOrigin
McSize
typedef size_t McSize
Byte size type.
Unsigned integer type of the result of the sizeof operator as well as the sizeof... operator and the alignof operator.
McUint32
typedef uint32_t McUint32
32 bit unsigned integer.
Integral type representing a 32-bit usigned integer.
McVoid
typedef void McVoid
pfn_mcDebugOutput_CALLBACK
typedef void(MCAPI_PTR * pfn_mcDebugOutput_CALLBACK) (McDebugSource source, McDebugType type, unsigned int id, McDebugSeverity severity, size_t length, const char *message, const McVoid *userParam)
Debug callback function signature type.
The callback function should have this prototype (in C), or be otherwise compatible with such a prototype.
pfn_McEvent_CALLBACK
typedef void(MCAPI_PTR * pfn_McEvent_CALLBACK) (McEvent event, McVoid *data)
Event callback function signature type.
The callback function should have this prototype (in C), or be otherwise compatible with such a prototype.
Enumeration Type Documentation
McCommandType
enum McCommandType
Flags for identifying event commands.
This enum structure defines the flags which are used for identifying the MCUT command associated with an event.
Enumerator
MC_COMMAND_DISPATCH
From McEnqueueDispatch.
MC_COMMAND_GET_CONNECTED_COMPONENTS
From McEnqueueGetConnectedComponents.
MC_COMMAND_GET_CONNECTED_COMPONENT_DATA
From McEnqueueGetConnectedComponentData.
MC_COMMAND_USER
From user application.
MC_COMMAND_UKNOWN
{
    MC_COMMAND_DISPATCH = 1 << 0,
    MC_COMMAND_GET_CONNECTED_COMPONENTS = 1 << 1,
    MC_COMMAND_GET_CONNECTED_COMPONENT_DATA = 1 << 2,
    MC_COMMAND_USER = 1 << 3,
    MC_COMMAND_UKNOWN
} McCommandType;
McConnectedComponentData
enum McConnectedComponentData
Data that can be queried about a connected component.
This enum structure defines the different types of data that are associated with a connected component and can be queried from the API after a dispatch call.
Enumerator
MC_CONNECTED_COMPONENT_DATA_VERTEX_FLOAT
List of vertex coordinates as an array of 32 bit floating-point numbers.
MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE
List of vertex coordinates as an array of 64 bit floating-point numbers.
MC_CONNECTED_COMPONENT_DATA_DISPATCH_PERTURBATION_VECTOR
Tuple of three real numbers represneting the vector that was used to nudge/perturb the source- and cut-mesh into general position to produce the respective connected component. This vector will represent the zero-vector if no perturbation was applied prior to the cutting operation that produced this connected component.
MC_CONNECTED_COMPONENT_DATA_FACE
List of faces as an array of indices. Each face can also be understood as a "planar straight line graph" (PSLG), which is a collection of vertices and segments that lie on the same plane. Segments are edges whose endpoints are vertices in the PSLG.
MC_CONNECTED_COMPONENT_DATA_FACE_SIZE
List of face sizes (vertices per face) as an array.
MC_CONNECTED_COMPONENT_DATA_EDGE
List of edges as an array of indices.
MC_CONNECTED_COMPONENT_DATA_TYPE
The type of a connected component (See also: McConnectedComponentType.).
MC_CONNECTED_COMPONENT_DATA_FRAGMENT_LOCATION
The location of a fragment connected component with respect to the cut mesh (See also: McFragmentLocation).
MC_CONNECTED_COMPONENT_DATA_PATCH_LOCATION
The location of a patch with respect to the source mesh (See also: McPatchLocation).
MC_CONNECTED_COMPONENT_DATA_FRAGMENT_SEAL_TYPE
The Hole-filling configuration of a fragment connected component (See also: McFragmentSealType).
MC_CONNECTED_COMPONENT_DATA_SEAM_VERTEX
List of unordered vertices as an array of indices. These vertices are introduced as a result of the cut and represent the intersection seam/path/contour.
MC_CONNECTED_COMPONENT_DATA_ORIGIN
The input mesh (source- or cut-mesh) from which a "seam" is derived (See also: McSeamOrigin).
MC_CONNECTED_COMPONENT_DATA_VERTEX_MAP
List of a subset of vertex indices from one of the input meshes (source-mesh or the cut-mesh). Each value will be the index of an input mesh vertex or MC_UNDEFINED_VALUE. This index-value corresponds to the connected component vertex at the accessed index. The value at index 0 of the queried array is the index of the vertex in the original input mesh. In order to clearly distinguish indices of the cut mesh from those of the source mesh, this index value corresponds to a cut mesh vertex index if it is great-than-or-equal-to the number of source-mesh vertices. Intersection points are mapped to MC_UNDEFINED_VALUE. The input mesh (i.e. source- or cut-mesh) will be deduced by the user from the type of connected component with which the information is queried. The input connected component (source-mesh or cut-mesh) that is referred to must be one stored internally by MCUT (i.e. a connected component queried from the API via McInputOrigin), to ensure consistency with any modification done internally by MCUT.
MC_CONNECTED_COMPONENT_DATA_FACE_MAP
List of a subset of face indices from one of the input meshes (source-mesh or the cut-mesh). Each value will be the index of an input mesh face. This index-value corresponds to the connected component face at the accessed index. Example: the value at index 0 of the queried array is the index of the face in the original input mesh. Note that all faces are mapped to a defined value. In order to clearly distinguish indices of the cut mesh from those of the source mesh, an input-mesh face index value corresponds to a cut-mesh vertex-index if it is great-than-or-equal-to the number of source-mesh faces. The input connected component (source-mesh or cut-mesh) that is referred to must be one stored internally by MCUT (i.e. a connected component queried from the API via McInputOrigin), to ensure consistency with any modification done internally by MCUT.
MC_CONNECTED_COMPONENT_DATA_FACE_ADJACENT_FACE
List of adjacent faces (their indices) per face.
MC_CONNECTED_COMPONENT_DATA_FACE_ADJACENT_FACE_SIZE
List of adjacent-face-list sizes (number of adjacent faces per face).
MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION
List of 3*N triangulated face indices, where N is the number of triangles that are produced using a [Constrained] Delaunay triangulation. Such a triangulation is similar to a Delaunay triangulation, but each (non-triangulated) face segment is present as a single edge in the triangulation. A constrained Delaunay triangulation is not truly a Delaunay triangulation. Some of its triangles might not be Delaunay, but they are all constrained Delaunay.
MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION_MAP
List of a subset of face indices from one of the input meshes (source-mesh or the cut-mesh). Each value will be the index of an input mesh face. This index-value corresponds to the connected-component face at the accessed index. Example: the value at index 0 of the queried array is the index of the face in the original input mesh. Note that all triangulated-faces are mapped to a defined value. In order to clearly distinguish indices of the cut mesh from those of the source mesh, an input-mesh face index value corresponds to a cut-mesh vertex-index if it is great-than-or-equal-to the number of source-mesh faces. The input connected component (source-mesh or cut-mesh) that is referred to must be one stored internally by MCUT (i.e. a connected component queried from the API via McInputOrigin), to ensure consistency with any modification done internally by MCUT.
{
    // MC_CONNECTED_COMPONENT_DATA_VERTEX_COUNT = (1 << 0), /**< Number of vertices. */
    MC_CONNECTED_COMPONENT_DATA_VERTEX_FLOAT = (1 << 1),
    MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE = (1 << 2),
    MC_CONNECTED_COMPONENT_DATA_DISPATCH_PERTURBATION_VECTOR = (1 << 4),
    MC_CONNECTED_COMPONENT_DATA_FACE = (1 << 5),
    MC_CONNECTED_COMPONENT_DATA_FACE_SIZE = (1 << 6),
    // MC_CONNECTED_COMPONENT_DATA_EDGE_COUNT = (1 << 7), /**< Number of edges. */
    MC_CONNECTED_COMPONENT_DATA_EDGE = (1 << 8),
    MC_CONNECTED_COMPONENT_DATA_TYPE = (1 << 9),
    MC_CONNECTED_COMPONENT_DATA_FRAGMENT_LOCATION = (1 << 10),
    MC_CONNECTED_COMPONENT_DATA_PATCH_LOCATION = (1 << 11),
    MC_CONNECTED_COMPONENT_DATA_FRAGMENT_SEAL_TYPE = (1 << 12),
    MC_CONNECTED_COMPONENT_DATA_SEAM_VERTEX = (1 << 13),
    MC_CONNECTED_COMPONENT_DATA_ORIGIN = (1 << 14),
    MC_CONNECTED_COMPONENT_DATA_VERTEX_MAP = (1 << 15),
    MC_CONNECTED_COMPONENT_DATA_FACE_MAP = (1 << 16),
    // incidence and adjacency information
    MC_CONNECTED_COMPONENT_DATA_FACE_ADJACENT_FACE = (1 << 17),
    MC_CONNECTED_COMPONENT_DATA_FACE_ADJACENT_FACE_SIZE = (1 << 18),
    MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION = (1 << 19),
    MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION_MAP = (1 << 20),
} McConnectedComponentData;
McConnectedComponentFaceWindingOrder
enum McConnectedComponentFaceWindingOrder
Flags for specifying the state used to determine winding order of queried faces.
This enum structure defines the flags which are used for identifying the winding order that is used to orient the vertex indices defining the faces of connected components.
Enumerator
MC_CONNECTED_COMPONENT_FACE_WINDING_ORDER_AS_GIVEN
Define the order of face-vertex indices using the orientation implied by the input meshes.
MC_CONNECTED_COMPONENT_FACE_WINDING_ORDER_REVERSED
Define the order of face-vertex indices using the reversed orientation implied by the input meshes.
{
    MC_CONNECTED_COMPONENT_FACE_WINDING_ORDER_AS_GIVEN = 1 << 0,
    MC_CONNECTED_COMPONENT_FACE_WINDING_ORDER_REVERSED = 1 << 1,
} McConnectedComponentFaceWindingOrder;
McConnectedComponentType
enum McConnectedComponentType
The possible types of connected components.
This enum structure defines the possible types of connected components which can be queried from the API after a dispatch call.
Enumerator
MC_CONNECTED_COMPONENT_TYPE_FRAGMENT
A connected component that originates from the source-mesh.
MC_CONNECTED_COMPONENT_TYPE_PATCH
A connected component that is originates from the cut-mesh.
MC_CONNECTED_COMPONENT_TYPE_SEAM
A connected component representing an input mesh (source-mesh or cut-mesh), but with additional vertices and edges that are introduced as as a result of the cut (i.e. the intersection contour/curve).
MC_CONNECTED_COMPONENT_TYPE_INPUT
A connected component that is copy of an input mesh (source-mesh or cut-mesh). Such a connected component may contain new faces and vertices, which will happen if MCUT internally performs polygon partitioning. Polygon partitioning occurs when an input mesh intersects the other without severing at least one edge. An example is splitting a tetrahedron (source-mesh) in two parts using one large triangle (cut-mesh): in this case, the large triangle would be partitioned into two faces to ensure that at least one of this cut-mesh are severed by the tetrahedron. This is what allows MCUT to reconnect topology after the cut.
MC_CONNECTED_COMPONENT_TYPE_ALL
Wildcard (match all) .
{
    MC_CONNECTED_COMPONENT_TYPE_FRAGMENT = (1 << 0),
    MC_CONNECTED_COMPONENT_TYPE_PATCH = (1 << 2),
    MC_CONNECTED_COMPONENT_TYPE_SEAM = (1 << 3),
    MC_CONNECTED_COMPONENT_TYPE_INPUT = (1 << 4),
    MC_CONNECTED_COMPONENT_TYPE_ALL = 0xFFFFFFFF
} McConnectedComponentType;
McContextCreationFlags
enum McContextCreationFlags
Context creation flags.
This enum structure defines the flags with which a context can be created.
Enumerator
MC_DEBUG
Enable debug mode (message logging etc.).
MC_OUT_OF_ORDER_EXEC_MODE_ENABLE
Determines whether the commands queued in the context-queue are executed in-order or out-of-order. If set, the commands in the context-queue are executed out-of-order. Otherwise, commands are executed in-order..
MC_PROFILING_ENABLE
Enable or disable profiling of commands in the context-queue. If set, the profiling of commands is enabled. Otherwise profiling of commands is disabled. See ::mcGetEventProfilingInfo for more information.
{
    MC_DEBUG = (1 << 0),
    MC_OUT_OF_ORDER_EXEC_MODE_ENABLE = (1 << 1),
    MC_PROFILING_ENABLE = (1 << 2)
} McContextCreationFlags;
McDebugSeverity
enum McDebugSeverity
Severity levels of messages.
This enum structure defines the different severities of error: low, medium or high severity messages.
Enumerator
MC_DEBUG_SEVERITY_HIGH
All MCUT Errors, mesh conversion/parsing errors, or undefined behavior.
MC_DEBUG_SEVERITY_MEDIUM
Major performance warnings, debugging warnings, or the use of deprecated functionality.
MC_DEBUG_SEVERITY_LOW
Redundant state change, or unimportant undefined behavior.
MC_DEBUG_SEVERITY_NOTIFICATION
Anything that isn't an error or performance issue.
MC_DEBUG_SEVERITY_IGNORE
This flag is passed to the API function mcDebugMessageControl (forth parameter). Its effect is to ignore the instruction to enable/disable the corresponding variant of debug output w.r.t. being logged into the provided callback
MC_DEBUG_SEVERITY_ALL
Match all (wildcard).
{
    MC_DEBUG_SEVERITY_HIGH = 1 << 0,
    MC_DEBUG_SEVERITY_MEDIUM = 1 << 1,
    MC_DEBUG_SEVERITY_LOW = 1 << 2,
    MC_DEBUG_SEVERITY_NOTIFICATION = 1 << 3,
    MC_DEBUG_SEVERITY_IGNORE = 1 << 3,
    MC_DEBUG_SEVERITY_ALL = 0xFFFFFFFF
} McDebugSeverity;
McDebugSource
enum McDebugSource
Source of a debug log message.
This enum structure defines the sources from which a message in a debug log may originate.
Enumerator
MC_DEBUG_SOURCE_API
messages generated by usage of the MCUT API.
MC_DEBUG_SOURCE_KERNEL
messages generated by internal logic implementing the kernel, which is responsible for resolving mesh intersections and connectivity.
MC_DEBUG_SOURCE_FRONTEND
messages generated by internal logic implementing the front-end, which is responsible for pre- and post-processing of meshes and connected components.
MC_DEBUG_SOURCE_IGNORE
This flag is passed to the API function mcDebugMessageControl (second parameter). Its effect is to ignore the instruction to enable/disable the corresponding variant of debug output w.r.t. being logged into the provided callback
MC_DEBUG_SOURCE_ALL
Wildcard (match all) .
{
    MC_DEBUG_SOURCE_API = 1 << 0,
    MC_DEBUG_SOURCE_KERNEL = 1 << 1,
    MC_DEBUG_SOURCE_FRONTEND = 1 << 2,
    MC_DEBUG_SOURCE_IGNORE = 1 << 3,
    MC_DEBUG_SOURCE_ALL = 0xFFFFFFFF
} McDebugSource;
McDebugType
enum McDebugType
Type of debug messages.
This enum structure defines the types of debug a message relating to an error.
Enumerator
MC_DEBUG_TYPE_ERROR
Explicit error message.
MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR
Attempted use of deprecated features.
MC_DEBUG_TYPE_OTHER
Other types of messages,.
MC_DEBUG_TYPE_IGNORE
This flag is passed to the API function mcDebugMessageControl (third parameter). Its effect is to ignore the instruction to enable/disable the corresponding variant of debug output w.r.t. being logged into the provided callback
MC_DEBUG_TYPE_ALL
Wildcard (match all) .
{
    MC_DEBUG_TYPE_ERROR = 1 << 0,
    MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 1 << 1,
    MC_DEBUG_TYPE_OTHER = 1 << 2,
    MC_DEBUG_TYPE_IGNORE = 1 << 3,
    MC_DEBUG_TYPE_ALL = 0xFFFFFFFF
} McDebugType;
McDispatchFlags
enum McDispatchFlags
Dispatch configuration flags.
This enum structure defines the flags indicating MCUT is to interprete input data, and execute the cutting pipeline.
Enumerator
MC_DISPATCH_VERTEX_ARRAY_FLOAT
Interpret the input mesh vertices as arrays of 32-bit floating-point numbers.
MC_DISPATCH_VERTEX_ARRAY_DOUBLE
Interpret the input mesh vertices as arrays of 64-bit floating-point numbers.
MC_DISPATCH_REQUIRE_THROUGH_CUTS
Require that all intersection paths/curves/contours partition the source-mesh into two (or more) fully disjoint parts. Otherwise, mcDispatch is a no-op. This flag enforces the requirement that only through-cuts are valid cuts i.e it disallows partial cuts. NOTE: This flag may not be used with MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED.
MC_DISPATCH_INCLUDE_VERTEX_MAP
Compute connected-component-to-input mesh vertex-id maps. See also: MC_CONNECTED_COMPONENT_DATA_VERTEX_MAP
MC_DISPATCH_INCLUDE_FACE_MAP
Compute connected-component-to-input mesh face-id maps. . See also: MC_CONNECTED_COMPONENT_DATA_FACE_MAP and :MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION_MAP
MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE
Compute fragments that are above the cut-mesh.
MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW
Compute fragments that are below the cut-mesh.
MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED
Compute fragments that are partially cut i.e. neither above nor below the cut-mesh. NOTE: This flag may not be used with MC_DISPATCH_REQUIRE_THROUGH_CUTS.
MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE
Compute fragments that are fully sealed (hole-filled) on the interior.
MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE
Compute fragments that are fully sealed (hole-filled) on the exterior.
MC_DISPATCH_FILTER_FRAGMENT_SEALING_NONE
Compute fragments that are not sealed (holes not filled).
MC_DISPATCH_FILTER_PATCH_INSIDE
Compute patches on the inside of the source mesh (those used to fill holes).
MC_DISPATCH_FILTER_PATCH_OUTSIDE
Compute patches on the outside of the source mesh.
MC_DISPATCH_FILTER_SEAM_SRCMESH
Compute the seam which is the same as the source-mesh but with new edges placed along the cut path. Note: a seam from the source-mesh will only be computed if the dispatch operation computes a complete (through) cut.
MC_DISPATCH_FILTER_SEAM_CUTMESH
Compute the seam which is the same as the cut-mesh but with new edges placed along the cut path. Note: a seam from the cut-mesh will only be computed if the dispatch operation computes a complete (through) cut.
MC_DISPATCH_FILTER_ALL
Keep all connected components resulting from the dispatched cut.
MC_DISPATCH_ENFORCE_GENERAL_POSITION
The following two flags allow MCUT to perturb the cut-mesh if the inputs are found not to be in general position.
MCUT is formulated for inputs in general position. Here the notion of general position is defined with respect to the orientation predicate (as evaluated on the intersecting polygons). Thus, a set of points is in general position if no three points are collinear and also no four points are coplanar.
MCUT uses the "MC_DISPATCH_ENFORCE_GENERAL_POSITION.." flags to inform of when to use perturbation (of the cut-mesh) so as to bring the input into general position. In such cases, the idea is to solve the cutting problem not on the given input, but on a nearby input. The nearby input is obtained by perturbing the given input. The perturbed input will then be in general position and, since it is near the original input, the result for the perturbed input will hopefully still be useful. This is justified by the fact that the task of MCUT is not to decide whether the input is in general position but rather to make perturbation on the input (if) necessary within the available precision of the computing device.
HOW GENERAL POSITION IS ENFORCED
When the inputs are found not to be in GP, MCUT will generate a pseudo-random 3d vector "p" representing a translation that will be applied to the cut-mesh.
A component "i" of "p" is computed as "p[i] = r() * c", where "r()" is a function returning a random variable from a uniform distribution on the interval [-1.0, 1.0), and "c" is a scalar computed from the general position enforcement constant (see MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT). Enforce general position such that the variable "c" (see detailed note above) is computed as the multiplication of the current general position enforcement constant (of current MCUT context) and the diagonal length of the bounding box of the cut-mesh. So this uses a relative perturbation of the cut-mesh based on its scale (see also MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT).
MC_DISPATCH_ENFORCE_GENERAL_POSITION_ABSOLUTE
Enforce general position such that the variable "c" (see detailed note above) is the current general position enforcement constant (of current MCUT context). So this uses an absolute perturbation of the cut-mesh based on the stored constant (see also MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT).
{
    MC_DISPATCH_VERTEX_ARRAY_FLOAT = (1 << 0),
    MC_DISPATCH_VERTEX_ARRAY_DOUBLE = (1 << 1),
    MC_DISPATCH_REQUIRE_THROUGH_CUTS = (1 << 2),
    MC_DISPATCH_INCLUDE_VERTEX_MAP = (1 << 3),
    MC_DISPATCH_INCLUDE_FACE_MAP = (1 << 4),
    //
    MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE = (1 << 5),
    MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW = (1 << 6),
    MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED = (1 << 7),
    //
    MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE = (1 << 8),
    MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE = (1 << 9),
    //
    MC_DISPATCH_FILTER_FRAGMENT_SEALING_NONE = (1 << 10),
    //
    MC_DISPATCH_FILTER_PATCH_INSIDE = (1 << 11),
    MC_DISPATCH_FILTER_PATCH_OUTSIDE = (1 << 12),
    //
    MC_DISPATCH_FILTER_SEAM_SRCMESH = (1 << 13),
    MC_DISPATCH_FILTER_SEAM_CUTMESH = (1 << 14),
    //
    MC_DISPATCH_FILTER_ALL = ( //
        MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE | //
        MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW | //
        MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED | //
        MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE | //
        MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE | //
        MC_DISPATCH_FILTER_FRAGMENT_SEALING_NONE | //
        MC_DISPATCH_FILTER_PATCH_INSIDE | //
        MC_DISPATCH_FILTER_PATCH_OUTSIDE | //
        MC_DISPATCH_FILTER_SEAM_SRCMESH | //
        MC_DISPATCH_FILTER_SEAM_CUTMESH),
    MC_DISPATCH_ENFORCE_GENERAL_POSITION = (1 << 15),
    MC_DISPATCH_ENFORCE_GENERAL_POSITION_ABSOLUTE= (1 << 16),
} McDispatchFlags;
McEventCommandExecStatus
enum McEventCommandExecStatus
Enumerator
MC_SUBMITTED
enqueued operation has been submitted by the client thread to the internal "device".
MC_RUNNING
Operation is currently running.
MC_COMPLETE
The operation has completed.
{
    MC_SUBMITTED = 1 << 0,
    MC_RUNNING = 1 << 1,
    MC_COMPLETE = 1 << 2
} McEventCommandExecStatus;
McFragmentLocation
enum McFragmentLocation
The possible geometrical locations of a fragment (connected component), which are defined with-respect-to the cut-mesh.
This enum structure defines the possible locations where a fragment can be relative to the cut-mesh. Note that the labels of 'above' or 'below' here are defined with-respect-to the winding-order (and hence, normal orientation) of the cut-mesh.
Enumerator
MC_FRAGMENT_LOCATION_ABOVE
Fragment is located above the cut-mesh.
MC_FRAGMENT_LOCATION_BELOW
Fragment is located below the cut-mesh.
MC_FRAGMENT_LOCATION_UNDEFINED
Fragment is located neither above nor below the cut-mesh. That is, it was produced due to a partial cut intersection.
MC_FRAGMENT_LOCATION_ALL
Wildcard (match all) .
{
    MC_FRAGMENT_LOCATION_ABOVE = 1 << 0,
    MC_FRAGMENT_LOCATION_BELOW = 1 << 1,
    MC_FRAGMENT_LOCATION_UNDEFINED = 1 << 2,
    MC_FRAGMENT_LOCATION_ALL = 0xFFFFFFFF
} McFragmentLocation;
McFragmentSealType
enum McFragmentSealType
Topological configurations of a fragment as defined with-respect-to hole-filling/sealing.
This enum structure defines the possible configurations that a fragment will be in regarding the hole-filling process. Here, hole-filling refers to the stage/phase when holes produced by a cut are filled with a subset of polygons of the cut-mesh.
Enumerator
MC_FRAGMENT_SEAL_TYPE_COMPLETE
Holes are completely sealed (watertight).
MC_FRAGMENT_SEAL_TYPE_NONE
Holes are not sealed (gaping hole).
MC_FRAGMENT_SEAL_TYPE_ALL
Wildcard (match all) .
{
    MC_FRAGMENT_SEAL_TYPE_COMPLETE = 1 << 0,
    MC_FRAGMENT_SEAL_TYPE_NONE = 1 << 2,
    MC_FRAGMENT_SEAL_TYPE_ALL = 0xFFFFFFFF
} McFragmentSealType;
McInputOrigin
enum McInputOrigin
The user-provided input mesh from which an input connected component is derived.
This enum structure defines the possible origins of an input connected component, which can be either the source-mesh or the cut-mesh. Note: the number of elements (faces and vertices) in an input connected component will be the same [or greater] than the corresponding user-provided input mesh from which the respective connected component came from. The input connect component will contain more elements if MCUT detected an intersection configuration where one input mesh will create a hole in a face of the other input mesh but without severing it edges (and vice versa).
Enumerator
MC_INPUT_ORIGIN_SRCMESH
Input connected component from the input source mesh.
MC_INPUT_ORIGIN_CUTMESH
Input connected component from the input cut mesh.
MC_INPUT_ORIGIN_ALL
Wildcard (match all) .
{
    MC_INPUT_ORIGIN_SRCMESH = 1 << 0,
    MC_INPUT_ORIGIN_CUTMESH = 1 << 1,
    MC_INPUT_ORIGIN_ALL = 0xFFFFFFFF
} McInputOrigin;
McPatchLocation
enum McPatchLocation
The possible geometrical locations of a patch as defined with-respect-to the source-mesh.
This enum structure defines the possible locations where a patch can be relative to the source-mesh. Note that the labels of 'inside' or 'outside' here are defined with-respect-to the winding-order (and hence, normal orientation) of the source-mesh.
Enumerator
MC_PATCH_LOCATION_INSIDE
Patch is located on the interior of the source-mesh (used to seal holes).
MC_PATCH_LOCATION_OUTSIDE
Patch is located on the exterior of the source-mesh. Rather than hole-filling these patches seal from the outside so-as to extrude the cut.
MC_PATCH_LOCATION_UNDEFINED
Patch is located neither on the interior nor exterior of the source-mesh.
MC_PATCH_LOCATION_ALL
Wildcard (match all) .
{
    MC_PATCH_LOCATION_INSIDE = 1 << 0,
    MC_PATCH_LOCATION_OUTSIDE = 1 << 1,
    MC_PATCH_LOCATION_UNDEFINED = 1 << 2,
    MC_PATCH_LOCATION_ALL = 0xFFFFFFFF
} McPatchLocation;
McQueryFlags
enum McQueryFlags
Flags for querying fixed API state.
This enum structure defines the flags which are used to query for specific information about the state of the API and/or a given context.
Enumerator
MC_CONTEXT_FLAGS
Flags used to create a context.
MC_DONT_CARE
wildcard.
MC_EVENT_RUNTIME_EXECUTION_STATUS
Error/status code associated with the runtime of the asynchronous/non-blocking part of the associated task. See also McResult
MC_EVENT_TIMESTAMP_SUBMIT
An unsigned 64-bit value that describes the current internal time counter in nanoseconds when the MCUT API function identified by event that has been enqueued is submitted by the internal scheduler for execution.
MC_EVENT_TIMESTAMP_START
An unsigned 64-bit value that describes the current internal time counter in nanoseconds when the MCUT API function identified by event starts execution.
MC_EVENT_TIMESTAMP_END
An unsigned 64-bit value that describes the current internal time counter in nanoseconds when the MCUT API function identified by event has finished execution.
MC_EVENT_COMMAND_EXECUTION_STATUS
the execution status of the command identified by event. See also McEventCommandExecStatus
MC_EVENT_CONTEXT
The context associated with event.
MC_EVENT_COMMAND_TYPE
The command associated with event. Can be one of the values in ::
MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH
The maximum length of a single message return from mcGetDebugMessageLog
MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT
A constant small real number representing the amount by which to perturb the cut-mesh when two intersecting polygon are found to not be in general position.
MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS
The number of times that a dispatch operation will attempt to perturb the cut-mesh if the input meshes are found to not be in general position.
MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER
The winding order that is used when specifying vertex indices that define the faces of connected components.
{
    MC_CONTEXT_FLAGS = 1 << 0,
    MC_DONT_CARE = 1 << 1,
    MC_EVENT_RUNTIME_EXECUTION_STATUS = 1 << 2,
    MC_EVENT_TIMESTAMP_SUBMIT = 1 << 3,
    MC_EVENT_TIMESTAMP_START = 1 << 4,
    MC_EVENT_TIMESTAMP_END = 1 << 5,
    MC_EVENT_COMMAND_EXECUTION_STATUS = 1 << 6,
    MC_EVENT_CONTEXT = 1 << 7,
    MC_EVENT_COMMAND_TYPE = 1 << 8,
    MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH = 1 << 9,
    MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT = 1 << 10,
    MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS = 1<<11,
    MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER = 1<<12
} McQueryFlags;
McResult
enum McResult
API return codes.
This enum structure defines the possible return values of API functions (integer). The values identify whether a function executed successfully or returned with an error.
Enumerator
MC_NO_ERROR
The function was successfully executed.
MC_INVALID_OPERATION
An internal operation could not be executed successively.
MC_INVALID_VALUE
An invalid value has been passed to the API.
MC_OUT_OF_MEMORY
Memory allocation operation cannot allocate memory.
MC_RESULT_MAX_ENUM
Wildcard (match all) .
                      {
    MC_NO_ERROR = 0,
    MC_INVALID_OPERATION = -(1 << 1),
    MC_INVALID_VALUE = -(1 << 2),
    MC_OUT_OF_MEMORY = -(1 << 3),
    MC_RESULT_MAX_ENUM = 0xFFFFFFFF
} McResult;
McSeamOrigin
enum McSeamOrigin
The input mesh from which a seam is derived.
This enum structure defines the possible origins of a seam connected component, which can be either the source-mesh or the cut-mesh.
Enumerator
MC_SEAM_ORIGIN_SRCMESH
Seam connected component is from the input source-mesh.
MC_SEAM_ORIGIN_CUTMESH
Seam connected component is from the input cut-mesh.
MC_SEAM_ORIGIN_ALL
Wildcard (match all) .
{
    MC_SEAM_ORIGIN_SRCMESH = 1 << 0,
    MC_SEAM_ORIGIN_CUTMESH = 1 << 1,
    MC_SEAM_ORIGIN_ALL = 0xFFFFFFFF
} McSeamOrigin;
Function Documentation
mcBindState()
MCAPI_ATTR McResult MCAPI_CALL mcBindState (const McContext context, McFlags stateInfo, McSize bytes, const McVoid * pMem)
Set the value of a selected parameter of a context.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] info Information being set. McQueryFlags
[in] bytes Size in bytes of memory pointed to by pMem.
[out] pMem Pointer to memory from where the appropriate result being copied.
This function effectively sets state variables of a context. All API functions using the respective context shall be effected by this state.
An example of usage:
McDouble epsilon = 1e-4;
McResult err =  mcBindState(context, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT, sizeof(McDouble), &epsilon);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
stateInfo is not an accepted flag.
bytes is 0
pMem is NULL
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (bytes == 0) {
        per_thread_api_log_str = "invalid bytes ";
    } else if (pMem == nullptr) {
        per_thread_api_log_str = "invalid ptr (pMem)";
    } else if (false == //
        (stateInfo == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT || //
            stateInfo == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS ||//
            stateInfo == MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER)) // check all possible values
    {
        per_thread_api_log_str = "invalid stateInfo ";
    } else if (
        ((stateInfo == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT) && bytes != sizeof(McDouble)) || //
        ((stateInfo == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS) && bytes != sizeof(McUint32))|| //
        ((stateInfo == MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER) && bytes != sizeof(McConnectedComponentFaceWindingOrder))) {
        per_thread_api_log_str = "invalid num bytes"; // leads to e.g. "out of bounds" memory access during memcpy
    } else {
        try {
            bind_state_impl(context, stateInfo, bytes, pMem);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References bind_state_impl(), CATCH_POSSIBLE_EXCEPTIONS, MC_CONTEXT_CONNECTED_COMPONENT_FACE_WINDING_ORDER, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT, and per_thread_api_log_str.
mcCreateContext()
MCAPI_ATTR McResult MCAPI_CALL mcCreateContext (McContext * pOutContext, McFlags contextFlags)
Create an MCUT context.
This method creates a context object, which is a handle used by a client application to control the API state and access data.
Parameters
[out] pContext a pointer to the allocated context handle
[in] flags bitfield containing the context creation flags
An example of usage:
McContext myContext = MC_NULL_HANDLE;
McResult err = mcCreateContext(&myContext, MC_NULL_HANDLE);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL
Failure to allocate resources
flags defines an invalid bitfield.
Copyright (c) 2021-2022 Floyd M. Chitalu. All rights reserved.
NOTE: This file is licensed under GPL-3.0-or-later (default). A commercial license can be purchased from Floyd M. Chitalu.
License details:
(A) GNU General Public License ("GPL"); a copy of which you should have recieved with this file.
see also: http://www.gnu.org/licenses/ (B) Commercial license.
email: floyd.nosp@m..m.c.nosp@m.hital.nosp@m.u@gm.nosp@m.ail.c.nosp@m.om
The commercial license options is for users that wish to use MCUT in their products for comercial purposes but do not wish to release their software products under the GPL license.
Author(s) : Floyd M. Chitalu
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pOutContext == nullptr) {
        per_thread_api_log_str = "context ptr undef (NULL)";
        return_value = McResult::MC_INVALID_VALUE;
    } else {
        try {
            // no helper threads
            // only manager threads (2 managers if context is created with MC_OUT_OF_ORDER_EXEC_MODE_ENABLE, otherwise 1 manager)
            create_context_impl(pOutContext, contextFlags, 0);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (return_value != McResult::MC_NO_ERROR) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, create_context_impl(), and per_thread_api_log_str.
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcCreateContextWithHelpers()
MCAPI_ATTR McResult MCAPI_CALL mcCreateContextWithHelpers (McContext * pOutContext, McFlags contextFlags, uint32_t helperThreadCount)
Create an MCUT context object with N helper threads.
This method creates a context object with an additonal number of threads that assist the internal scheduler with compute workloads. The returned a handle shall be used by a client applications to control the API state and access data.
Unless otherwise stated, MCUT runs asynchronously with the user application. Non-blocking commands issued with a given context run on a conceptual "device", which executes independently of the client application. This device is associated with one logical thread by default. Two logical threads will be associated with the device if MC_OUT_OF_ORDER_EXEC_MODE_ENABLE is provided as a flag.
Having one logical device thread means that MCUT commands shall execute in the order that they are provided by a client application. And if two logical threads are associated with the device then multiple API commands may also run concurrently subject to their dependency list.
Concurrent commands share the pool of N helper threads.
Parameters
[out] pContext a pointer to the allocated context handle
[in] flags bitfield containing the context creation flags
[in] helperThreadCount Number of helper-threads to assist device-threads with parallel work.
An example of usage:
McContext myContext = MC_NULL_HANDLE;
McResult err = mcCreateContextWithHelpers(&myContext, MC_OUT_OF_ORDER_EXEC_MODE_ENABLE, 2);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL
Failure to allocate resources
flags defines an invalid bitfield.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pOutContext == nullptr) {
        per_thread_api_log_str = "context ptr undef (NULL)";
        return_value = McResult::MC_INVALID_VALUE;
    } else {
        try {
            create_context_impl(pOutContext, contextFlags, helperThreadCount);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (return_value != McResult::MC_NO_ERROR) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, create_context_impl(), and per_thread_api_log_str.
mcCreateUserEvent()
MCAPI_ATTR McResult MCAPI_CALL mcCreateUserEvent (McEvent * event, McContext context)
To create a user event object, call the function.
Parameters
event Event handle
context must be a valid MCUT context.
User events allow applications to enqueue commands that wait on a user event to finish before the command is executed by the MCUT engine
mcCreateUserEvent returns a valid non-zero event object and return code is set to MC_NO_ERROR if the user event object is created successfully. Otherwise, it returns a NULL value with an error values.
Returns
MCAPI_ATTR
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (event == nullptr) {
        per_thread_api_log_str = "event ptr (param0) undef (NULL)";
    } else if (context == nullptr) {
        per_thread_api_log_str = "context handle undefined (NULL)";
    } else {
        try {
            create_user_event_impl(event, context);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, create_user_event_impl(), and per_thread_api_log_str.
mcDebugMessageCallback()
MCAPI_ATTR McResult MCAPI_CALL mcDebugMessageCallback (McContext context, pfn_mcDebugOutput_CALLBACK cb, const McVoid * userParam)
Specify a callback to receive debugging messages from the MCUT library.
mcDebugMessageCallback sets the current debug output callback function to the function whose address is given in callback.
This function is defined to have the same calling convention as the MCUT API functions. In most cases this is defined as MCAPI_ATTR, although it will vary depending on platform, language and compiler.
Each time a debug message is generated the debug callback function will be invoked with source, type, and severity associated with the message, and length set to the length of debug message whose character string is in the array pointed to by message userParam will be set to the value passed in the userParam parameter to the most recent call to mcDebugMessageCallback.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] cb The address of a callback function that will be called when a debug message is generated.
[in] userParam A user supplied pointer that will be passed on each invocation of callback.
An example of usage:
// define my callback (with type pfn_mcDebugOutput_CALLBACK)
void mcDebugOutput(McDebugSource source,   McDebugType type, unsigned int id, McDebugSeverity severity,size_t length, const char* message,const McVoid* userParam)
{
 // do stuff
}
// ...
McVoid* someData = NULL;
McResult err = mcDebugMessageCallback(myContext, mcDebugOutput, someData);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
cb is NULL.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pContext == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (cb == nullptr) {
        per_thread_api_log_str = "callback function ptr (param1) undef (NULL)";
    } else {
        try {
            debug_message_callback_impl(pContext, cb, userParam);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, debug_message_callback_impl(), and per_thread_api_log_str.
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcDebugMessageControl()
MCAPI_ATTR McResult MCAPI_CALL mcDebugMessageControl (McContext context, McDebugSource source, McDebugType type, McDebugSeverity severity, bool enabled)
Control the reporting of debug messages in a debug context.
Parameters
[in] context The context handle that was created by a previous call to
See also
mcCreateContext.
Parameters
[in] source The source of debug messages to enable or disable.
[in] type The type of debug messages to enable or disable.
[in] severity The severity of debug messages to enable or disable.
[in] enabled A Boolean flag determining whether the selected messages should be enabled or disabled.
mcDebugMessageControl controls the reporting of debug messages generated by a debug context. The parameters source, type and severity form a filter to select messages from the pool of potential messages generated by the MCUT library.
source may be MC_DEBUG_SOURCE_API, MC_DEBUG_SOURCE_KERNEL to select messages generated by usage of the MCUT API, the MCUT kernel or by the input, respectively. It may also take the value MC_DEBUG_SOURCE_ALL. If source is not MC_DEBUG_SOURCE_ALL then only messages whose source matches source will be referenced.
type may be one of MC_DEBUG_TYPE_ERROR, MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR, or MC_DEBUG_TYPE_OTHER to indicate the type of messages describing MCUT errors, attempted use of deprecated features, and other types of messages, respectively. It may also take the value MC_DONT_CARE. If type is not MC_DEBUG_TYPE_ALL then only messages whose type matches type will be referenced.
severity may be one of MC_DEBUG_SEVERITY_LOW, MC_DEBUG_SEVERITY_MEDIUM, or MC_DEBUG_SEVERITY_HIGH to select messages of low, medium or high severity messages or to MC_DEBUG_SEVERITY_NOTIFICATION for notifications. It may also take the value MC_DEBUG_SEVERITY_ALL. If severity is not MC_DEBUG_SEVERITY_ALL then only messages whose severity matches severity will be referenced.
If enabled is true then messages that match the filter formed by source, type and severity are enabled. Otherwise, those messages are disabled.
An example of usage:
// ... typically after setting debug callback with ::mcDebugMessageCallback
McResult err = mcDebugMessageControl(myContext, MC_DEBUG_SOURCE_ALL, MC_DEBUG_TYPE_ALL, MC_DEBUG_SEVERITY_ALL, true);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
source is not a value define in McDebugSource.
type is not a value define in McDebugType.
severity is not a value define in McDebugSeverity.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pContext == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (
        false == (source == McDebugSource::MC_DEBUG_SOURCE_ALL || //
            source == McDebugSource::MC_DEBUG_SOURCE_KERNEL || //
            source == McDebugSource::MC_DEBUG_SOURCE_ALL)) {
        per_thread_api_log_str = "debug source val (param1) invalid";
    } else if (
        false == (type == McDebugType::MC_DEBUG_TYPE_ALL || //
            type == McDebugType::MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR || //
            type == McDebugType::MC_DEBUG_TYPE_ERROR || //
            type == McDebugType::MC_DEBUG_TYPE_OTHER)) {
        per_thread_api_log_str = "debug type val (param2) invalid";
    } else if (
        false == (severity == McDebugSeverity::MC_DEBUG_SEVERITY_HIGH || //
            severity == McDebugSeverity::MC_DEBUG_SEVERITY_MEDIUM || //
            severity == McDebugSeverity::MC_DEBUG_SEVERITY_LOW || //
            severity == McDebugSeverity::MC_DEBUG_SEVERITY_NOTIFICATION || //
            severity == McDebugSeverity::MC_DEBUG_SEVERITY_ALL)) {
        per_thread_api_log_str = "debug severity val (param3) invalid";
    } else {
        try {
            debug_message_control_impl(pContext, source, type, severity, enabled);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, debug_message_control_impl(), and per_thread_api_log_str.
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcDispatch()
MCAPI_ATTR McResult MCAPI_CALL mcDispatch (McContext context, McFlags flags, const McVoid * pSrcMeshVertices, const uint32_t * pSrcMeshFaceIndices, const uint32_t * pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid * pCutMeshVertices, const uint32_t * pCutMeshFaceIndices, const uint32_t * pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces)
Blocking version of mcEnqueueDispatch.
{
    McEvent event = MC_NULL_HANDLE;
    McResult return_value = mcEnqueueDispatch(
        context,
        dispatchFlags,
        pSrcMeshVertices,
        pSrcMeshFaceIndices,
        pSrcMeshFaceSizes,
        numSrcMeshVertices,
        numSrcMeshFaces,
        pCutMeshVertices,
        pCutMeshFaceIndices,
        pCutMeshFaceSizes,
        numCutMeshVertices,
        numCutMeshFaces,
        0,
        nullptr,
        &event);
    if (return_value == MC_NO_ERROR) { // API parameter checks are fine
        if (event != MC_NULL_HANDLE) // event must exist to wait on and query
        {
            McResult waitliststatus = MC_NO_ERROR;
            wait_for_events_impl(1, &event, waitliststatus); // block until event of mcEnqueueDispatch is completed!
            if (waitliststatus != McResult::MC_NO_ERROR) {
                return_value = waitliststatus;
            }
            release_events_impl(1, &event); // destroy
        }
    }
    return return_value;
}
References MC_NO_ERROR, MC_NULL_HANDLE, mcEnqueueDispatch(), release_events_impl(), and wait_for_events_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcEnqueueDispatch()
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueDispatch (const McContext context, McFlags dispatchFlags, const McVoid * pSrcMeshVertices, const uint32_t * pSrcMeshFaceIndices, const uint32_t * pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McVoid * pCutMeshVertices, const uint32_t * pCutMeshFaceIndices, const uint32_t * pCutMeshFaceSizes, uint32_t numCutMeshVertices, uint32_t numCutMeshFaces, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
Execute a cutting operation with two meshes - the source mesh, and the cut mesh.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] flags The flags indicating how to interprete input data and configure the execution.
[in] pSrcMeshVertices The array of vertex coordinates (i.e. in xyzxyzxyz... format) of the source mesh.
[in] pSrcMeshFaceIndices The array of vertex indices of the faces (polygons) in the source mesh.
[in] pSrcMeshFaceSizes The array of the sizes (in terms of number of vertex indices) of the faces in the source mesh.
[in] numSrcMeshVertices The number of vertices in the source mesh.
[in] numSrcMeshFaces The number of faces in the source mesh.
[in] pCutMeshVertices The array of vertex coordinates (i.e. in xyzxyzxyz... format) of the cut mesh.
[in] pCutMeshFaceIndices The array of vertex indices of the faces (polygons) in the cut mesh.
[in] pCutMeshFaceSizes The array of the sizes (in terms of number of vertex indices) of the faces in the cut mesh.
[in] numCutMeshVertices The number of vertices in the cut mesh.
[in] numCutMeshFaces The number of faces in the cut mesh.
[in] numEventsInWaitlist Number of events in the waitlist.
[in] pEventWaitList Events that need to complete before this particular command can be executed.
[out] pEvent Returns an event object that identifies this particular command and can be used to query or queue a wait for this particular command to complete. pEvent can be NULL in which case it will not be possible for the application to query the status of this command or queue a wait for this command to complete. If the pEventWaitList and the event arguments are not NULL, the pEvent argument should not refer to an element of the pEventWaitList array.
This function specifies the two mesh objects to operate on. The 'source mesh' is the mesh to be cut (i.e. partitioned) along intersection paths prescribed by the 'cut mesh'.
If pEventWaitList is NULL, then this particular command does not wait on any event to complete. If pEventWaitList is NULL, numEventsInWaitlist must be 0. If pEventWaitList is not NULL, the list of events pointed to by pEventWaitList must be valid and numEventsInWaitlist must be greater than 0. The events specified in pEventWaitList act as synchronization points. The memory associated with pEventWaitList can be reused or freed after the function returns.
An example of usage:
 McEvent event;
 //...
 McResult err = mcEnqueueDispatch(..., 0, NULL, &event);
if(err != MC_NO_ERROR)
{
 // deal with error...
}
err = mcWaitForEvents(1, &event);
if(err != MC_NO_ERROR)
{
 // deal with error...
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
flags contains an invalid value.
A vertex index in pSrcMeshFaceIndices or pCutMeshFaceIndices is out of bounds.
Invalid face/polygon definition (vertex list) implying non-manifold mesh pSrcMeshFaceIndices or pCutMeshFaceIndices is out of bounds.
The MC_DISPATCH_VERTEX_ARRAY_... value has not been specified in flags
An input mesh contains multiple connected components.
pSrcMeshVertices is NULL.
pSrcMeshFaceIndices is NULL.
pSrcMeshFaceSizes is NULL.
numSrcMeshVertices is less than three.
numSrcMeshFaces is less than one.
pCutMeshVertices is NULL.
pCutMeshFaceIndices is NULL.
pCutMeshFaceSizes is NULL.
numCutMeshVertices is less than three.
numCutMeshFaces is less than one.
numEventsInWaitlist Number of events in the waitlist.
pEventWaitList events that need to complete before this particular command can be executed
MC_DISPATCH_ENFORCE_GENERAL_POSITION or MC_DISPATCH_ENFORCE_GENERAL_POSITION_ABSOLUTE is not set and: 1) Found two intersecting edges between the source-mesh and the cut-mesh and/or 2) An intersection test between a face and an edge failed because an edge vertex only touches (but does not penetrate) the face, and/or 3) One or more source-mesh vertices are colocated with one or more cut-mesh vertices.
MC_OUT_OF_MEMORY
Insufficient memory to perform operation.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (dispatchFlags == 0) {
        per_thread_api_log_str = "dispatch flags unspecified";
    } else if ((dispatchFlags & MC_DISPATCH_REQUIRE_THROUGH_CUTS) && //
        (dispatchFlags & MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED)) {
        // The user states that she does not want a partial cut but yet also states that she
        // wants to keep fragments with partial cuts. These two options are mutually exclusive!
        per_thread_api_log_str = "use of mutually-exclusive flags: MC_DISPATCH_REQUIRE_THROUGH_CUTS & MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED";
    } else if ((dispatchFlags & MC_DISPATCH_VERTEX_ARRAY_FLOAT) == 0 && (dispatchFlags & MC_DISPATCH_VERTEX_ARRAY_DOUBLE) == 0) {
        per_thread_api_log_str = "dispatch vertex aray type unspecified";
    } else if (pSrcMeshVertices == nullptr) {
        per_thread_api_log_str = "source-mesh vertex-position array ptr undef (NULL)";
    } else if (numSrcMeshVertices < 3) {
        per_thread_api_log_str = "invalid source-mesh vertex count";
    } else if (pSrcMeshFaceIndices == nullptr) {
        per_thread_api_log_str = "source-mesh face-index array ptr undef (NULL)";
    } /*else if (pSrcMeshFaceSizes == nullptr) {
        per_thread_api_log_str = "source-mesh face-size array ptr undef (NULL)";
    }*/
    else if (numSrcMeshFaces < 1) {
        per_thread_api_log_str = "invalid source-mesh vertex count";
    } else if (pCutMeshVertices == nullptr) {
        per_thread_api_log_str = "cut-mesh vertex-position array ptr undef (NULL)";
    } else if (numCutMeshVertices < 3) {
        per_thread_api_log_str = "invalid cut-mesh vertex count";
    } else if (pCutMeshFaceIndices == nullptr) {
        per_thread_api_log_str = "cut-mesh face-index array ptr undef (NULL)";
    } /*else if (pCutMeshFaceSizes == nullptr) {
        per_thread_api_log_str = "cut-mesh face-size array ptr undef (NULL)";
    } */
    else if (numCutMeshFaces < 1) {
        per_thread_api_log_str = "invalid cut-mesh vertex count";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist == 0 && pEvent == nullptr) {
        per_thread_api_log_str = "invalid event ptr (zero)";
    } else {
        try {
            dispatch_impl(
                context,
                dispatchFlags,
                pSrcMeshVertices,
                pSrcMeshFaceIndices,
                pSrcMeshFaceSizes,
                numSrcMeshVertices,
                numSrcMeshFaces,
                pCutMeshVertices,
                pCutMeshFaceIndices,
                pCutMeshFaceSizes,
                numCutMeshVertices,
                numCutMeshFaces,
                numEventsInWaitlist,
                pEventWaitList,
                pEvent);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, dispatch_impl(), MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED, MC_DISPATCH_REQUIRE_THROUGH_CUTS, MC_DISPATCH_VERTEX_ARRAY_DOUBLE, MC_DISPATCH_VERTEX_ARRAY_FLOAT, and per_thread_api_log_str.
Referenced by mcDispatch().
mcEnqueueDispatchPlanarSection()
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueDispatchPlanarSection (const McContext context, McFlags dispatchFlags, const McVoid * pSrcMeshVertices, const uint32_t * pSrcMeshFaceIndices, const uint32_t * pSrcMeshFaceSizes, uint32_t numSrcMeshVertices, uint32_t numSrcMeshFaces, const McDouble * pNormalVector, const McDouble sectionOffset, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
    {
        McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (dispatchFlags == 0) {
        per_thread_api_log_str = "dispatch flags unspecified";
    } else if ((dispatchFlags & MC_DISPATCH_REQUIRE_THROUGH_CUTS) && //
        (dispatchFlags & MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED)) {
        // The user states that she does not want a partial cut but yet also states that she
        // wants to keep fragments with partial cuts. These two options are mutually exclusive!
        per_thread_api_log_str = "use of mutually-exclusive flags: MC_DISPATCH_REQUIRE_THROUGH_CUTS & MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED";
    } else if ((dispatchFlags & MC_DISPATCH_VERTEX_ARRAY_FLOAT) == 0 && (dispatchFlags & MC_DISPATCH_VERTEX_ARRAY_DOUBLE) == 0) {
        per_thread_api_log_str = "dispatch vertex aray type unspecified";
    } else if (pSrcMeshVertices == nullptr) {
        per_thread_api_log_str = "source-mesh vertex-position array ptr undef (NULL)";
    } else if (numSrcMeshVertices < 3) {
        per_thread_api_log_str = "invalid source-mesh vertex count";
    } else if (pSrcMeshFaceIndices == nullptr) {
        per_thread_api_log_str = "source-mesh face-index array ptr undef (NULL)";
    } /*else if (pSrcMeshFaceSizes == nullptr) {
        per_thread_api_log_str = "source-mesh face-size array ptr undef (NULL)";
    }*/
    else if (numSrcMeshFaces < 1) {
        per_thread_api_log_str = "invalid source-mesh vertex count";
    } else if (pNormalVector == nullptr) {
        per_thread_api_log_str = "normal vector ptr undef (NULL)";
    } else if (pNormalVector[0] == 0.0 && pNormalVector[1] == 0.0 && pNormalVector[2] == 0.0) {
        per_thread_api_log_str = "invalid normal vector (zero vector)";
    }else if (sectionOffset <= 0 && sectionOffset >= 1.0) {
        per_thread_api_log_str = "invalid section offset parameter";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist == 0 && pEvent == nullptr) {
        per_thread_api_log_str = "invalid event ptr (zero)";
    } else {
        try {
            dispatch_planar_section_impl(
                context,
                dispatchFlags,
                pSrcMeshVertices,
                pSrcMeshFaceIndices,
                pSrcMeshFaceSizes,
                numSrcMeshVertices,
                numSrcMeshFaces,
                pNormalVector,
                sectionOffset,
                numEventsInWaitlist,
                pEventWaitList,
                pEvent);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
    }
References CATCH_POSSIBLE_EXCEPTIONS, dispatch_planar_section_impl(), MC_DISPATCH_FILTER_FRAGMENT_LOCATION_UNDEFINED, MC_DISPATCH_REQUIRE_THROUGH_CUTS, MC_DISPATCH_VERTEX_ARRAY_DOUBLE, MC_DISPATCH_VERTEX_ARRAY_FLOAT, and per_thread_api_log_str.
mcEnqueueGetConnectedComponentData()
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueGetConnectedComponentData (const McContext context, const McConnectedComponent connCompId, McFlags queryFlags, McSize bytes, McVoid * pMem, McSize * pNumBytes, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
Query specific information about a connected component.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] connCompId A connected component returned by mcGetConnectedComponents whose data is to be read.
[in] flags An enumeration constant that identifies the connected component information being queried.
[in] bytes Specifies the size in bytes of memory pointed to by flags.
[out] pMem A pointer to memory location where appropriate values for a given flags will be returned. If pMem is NULL, it is ignored.
[out] pNumBytes Returns the actual size in bytes of data being queried by flags. If pNumBytes is NULL, it is ignored.
The connected component queries described in the McConnectedComponentData should return the same information for a connected component returned by mcGetConnectedComponents. If pEventWaitList is NULL, then this particular command does not wait on any event to complete. If pEventWaitList is NULL, numEventsInWaitlist must be 0. If pEventWaitList is not NULL, the list of events pointed to by pEventWaitList must be valid and numEventsInWaitlist must be greater than 0. The events specified in pEventWaitList act as synchronization points. The memory associated with pEventWaitList can be reused or freed after the function returns.
An example of usage:
McSize numBytes = 0;
McEvent bytesQueryEvent=MC_NULL_HANDLE;
McEvent ev = MC_NULL_HANDLE;
McResult err = mcEnqueueGetConnectedComponentData(myContext,  connCompHandle, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, 0, NULL, &numBytes, 0, NULL, &bytesQueryEvent, 0, NULL, &ev);
if(err != MC_NO_ERROR)
{
 // deal with error
}
double* pVertices = (double*)malloc(numBytes);
// this operation shall happen AFTER the preceding operation associated with "bytesQueryEvent".
err = mcEnqueueGetConnectedComponentData(context, connCompHandle, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, numBytes, (McVoid*)pVertices, NULL, 1, &bytesQueryEvent, NULL, 1, &ev, NULL);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
connectedComponentType is not a value in McConnectedComponentType.
pMem and pNumBytes are both NULL (or not NULL).
bytes is zero and pMem is not NULL.
flag is MC_CONNECTED_COMPONENT_DATA_VERTEX_MAP when context dispatch flags did not include flag MC_DISPATCH_INCLUDE_VERTEX_MAP
flag is MC_CONNECTED_COMPONENT_DATA_FACE_MAP when context dispatch flags did not include flag MC_DISPATCH_INCLUDE_FACE_MAP
numEventsInWaitlist Number of events in the waitlist.
pEventWaitList events that need to complete before this particular command can be executed
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    }
    if (connCompId == nullptr) {
        per_thread_api_log_str = "connected component ptr (param1) undef (NULL)";
    } else if (queryFlags == 0) {
        per_thread_api_log_str = "flags (param1) undef (0)";
    } else if (bytes != 0 && pMem == nullptr) {
        per_thread_api_log_str = "null parameter (param3 & param4)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist == 0 && pEvent == nullptr) {
        per_thread_api_log_str = "invalid event ptr (zero)";
    } else {
        try {
            get_connected_component_data_impl(context, connCompId, queryFlags, bytes, pMem, pNumBytes, numEventsInWaitlist, pEventWaitList, pEvent);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, get_connected_component_data_impl(), and per_thread_api_log_str.
Referenced by mcGetConnectedComponentData().
mcEnqueueGetConnectedComponents()
MCAPI_ATTR McResult MCAPI_CALL mcEnqueueGetConnectedComponents (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent * pConnComps, uint32_t * numConnComps, uint32_t numEventsInWaitlist, const McEvent * pEventWaitList, McEvent * pEvent)
Query the connected components available in a context.
This function will return an array of connected components matching the given description of flags.
Parameters
[in] context The context handle
[in] connectedComponentType The type(s) of connected component sought. See also McConnectedComponentType.
[in] numEntries The number of McConnectedComponent entries that can be added to pConnComps. If pConnComps is not NULL, numEntries must be the number of elements in pConnComps.
[out] pConnComps Returns a list of connected components found. The McConnectedComponentType values returned in pConnComps can be used to identify a specific connected component. If pConnComps is NULL, this argument is ignored. The number of connected components returned is the minimum of the value specified by numEntries or the number of connected components whose type matches connectedComponentType.
[out] numConnComps Returns the number of connected components available that match connectedComponentType. If numConnComps is NULL, this argument is ignored.
[in] numEventsInWaitlist Number of events in the waitlist.
[in] pEventWaitList Events that need to complete before this particular command can be executed.
[out] pEvent Returns an event object that identifies this particular command and can be used to query or queue a wait for this particular command to complete. pEvent can be NULL in which case it will not be possible for the application to query the status of this command or queue a wait for this command to complete. If the pEventWaitList and the event arguments are not NULL, the pEvent argument should not refer to an element of the pEventWaitList array.
If pEventWaitList is NULL, then this particular command does not wait on any event to complete. If pEventWaitList is NULL, numEventsInWaitlist must be 0. If pEventWaitList is not NULL, the list of events pointed to by pEventWaitList must be valid and numEventsInWaitlist must be greater than 0. The events specified in pEventWaitList act as synchronization points. The memory associated with pEventWaitList can be reused or freed after the function returns.
An example of usage:
uint32_t numConnComps = 0;
McConnectedComponent* pConnComps;
McEvent ev = MC_NULL_HANDLE;
McResult err =  err = mcGetConnectedComponents(myContext, MC_CONNECTED_COMPONENT_TYPE_ALL, 0, NULL, &numConnComps, 0, NULL, &ev);
if(err != MC_NO_ERROR)
{
 // deal with error
}
if (numConnComps == 0) {
   // ...
}
pConnComps = (McConnectedComponent*)malloc(sizeof(McConnectedComponent) * numConnComps);
err = mcGetConnectedComponents(myContext, MC_CONNECTED_COMPONENT_TYPE_ALL, numConnComps, pConnComps, NULL, 1, &ev, NULL);
if(err != MC_NO_ERROR)
{
 // deal with error
}
...
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
connectedComponentType is not a value in McConnectedComponentType.
numConnComps and pConnComps are both NULL.
numConnComps is zero and pConnComps is not NULL.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (connectedComponentType == 0) {
        per_thread_api_log_str = "invalid type-parameter (param1) (0)";
    } else if (numConnComps == nullptr && pConnComps == nullptr) {
        per_thread_api_log_str = "output parameters undef (param3 & param4)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else if (pEventWaitList == nullptr && numEventsInWaitlist == 0 && pEvent == nullptr) {
        per_thread_api_log_str = "invalid event ptr (zero)";
    } else {
        try {
            get_connected_components_impl(context, connectedComponentType, numEntries, pConnComps, numConnComps, numEventsInWaitlist, pEventWaitList, pEvent);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, get_connected_components_impl(), and per_thread_api_log_str.
Referenced by mcGetConnectedComponents().
mcGetConnectedComponentData()
MCAPI_ATTR McResult MCAPI_CALL mcGetConnectedComponentData (const McContext context, const McConnectedComponent connCompId, McFlags flags, McSize bytes, McVoid * pMem, McSize * pNumBytes)
Blocking version of mcEnqueueGetConnectedComponents.
{
    McEvent event = MC_NULL_HANDLE;
    McResult return_value = mcEnqueueGetConnectedComponentData(context, connCompId, queryFlags, bytes, pMem, pNumBytes, 0, nullptr, &event);
    if (event != MC_NULL_HANDLE) // event must exist to wait on and query
    {
        McResult waitliststatus = MC_NO_ERROR;
        wait_for_events_impl(1, &event, waitliststatus); // block until event of mcEnqueueDispatch is completed!
        if (waitliststatus != McResult::MC_NO_ERROR) {
            return_value = waitliststatus;
        }
        release_events_impl(1, &event); // destroy
    }
    return return_value;
}
References MC_NO_ERROR, MC_NULL_HANDLE, mcEnqueueGetConnectedComponentData(), release_events_impl(), and wait_for_events_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcGetConnectedComponents()
MCAPI_ATTR McResult MCAPI_CALL mcGetConnectedComponents (const McContext context, const McConnectedComponentType connectedComponentType, const uint32_t numEntries, McConnectedComponent * pConnComps, uint32_t * numConnComps)
Blocking version of mcEnqueueGetConnectedComponents.
{
    McEvent event = MC_NULL_HANDLE;
    McResult return_value = mcEnqueueGetConnectedComponents(context, connectedComponentType, numEntries, pConnComps, numConnComps, 0, nullptr, &event);
    if (event != MC_NULL_HANDLE) // event must exist to wait on and query
    {
        McResult waitliststatus = MC_NO_ERROR;
        wait_for_events_impl(1, &event, waitliststatus); // block until event of mcEnqueueDispatch is completed!
        if (waitliststatus != McResult::MC_NO_ERROR) {
            return_value = waitliststatus;
        }
        release_events_impl(1, &event); // destroy
    }
    return return_value;
}
References MC_NO_ERROR, MC_NULL_HANDLE, mcEnqueueGetConnectedComponents(), release_events_impl(), and wait_for_events_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcGetDebugMessageLog()
MCAPI_ATTR McResult MCAPI_CALL mcGetDebugMessageLog (McContext context, McUint32 count, McSize bufSize, McDebugSource * sources, McDebugType * types, McDebugSeverity * severities, McSize * lengths, McChar * messageLog, McUint32 * numFetched)
Returns messages stored in an internal log.
Parameters
context The context handle that was created by a previous call to
See also
mcCreateContext.
Parameters
count The number of debug messages to retrieve from the log.
bufSize The size of the buffer whose address is given by messageLog.
sources The address of an array of variables to receive the sources of the retrieved messages.
types The address of an array of variables to receive the types of the retrieved messages.
severities The address of an array of variables to receive the severites of the retrieved messages.
lengths The address of an array of variables to receive the lengths of the received messages.
messageLog The address of an array of variables to receive the lengths of the received messages..
mcGetDebugMessageLog retrieves messages from the debug message log. A maximum of count messages are retrieved from the log. If sources is not NULL then the source of each message is written into up to count elements of the array. If types is not NULL then the type of each message is written into up to count elements of the array. If severities is not NULL then the severity of each message is written into up to count elements of the array. If lengths is not NULL then the length of each message is written into up to count elements of the array.
messageLog specifies the address of a character array into which the debug messages will be written. Each message will be concatenated onto the array starting at the first element of messageLog. bufSize specifies the size of the array messageLog. If a message will not fit into the remaining space in messageLog then the function terminates and returns the number of messages written so far, which may be zero.
If mcGetDebugMessageLog returns zero then no messages are present in the debug log, or there was not enough space in messageLog to retrieve the first message in the queue. If messageLog is NULL then no messages are written and the value of bufSize is ignored..
Here is an example of code that can get the first N messages:
 {.c++}
McResult GetFirstNMessages(McContext context, McUint32 numMsgs)
{
     McSize maxMsgLen = 0;
     mcGetInfo(MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH, &maxMsgLen);
      std::vector<McChar> msgData(numMsgs * maxMsgLen);
     std::vector<McDebugSource> sources(numMsgs);
     std::vector<McDebugType> types(numMsgs);
     std::vector<McDebugSeverity> severities(numMsgs);
     std::vector<McSize> lengths(numMsgs);
     McUint32 numFound;
     McResult err = mcGetDebugMessageLog(context, numMsgs, numMsgs, &sources[0], &types[0], &severities[0], &lengths[0], &msgData[0], &numFound);
     if(err != MC_NO_ERROR)
     {
         // deal with error ...
     }
     sources.resize(numFound);
     types.resize(numFound);
     severities.resize(numFound);
     ids.resize(numFound);
     lengths.resize(numFound);
     std::vector<std::string> messages;
     messages.reserve(numFound);
     std::vector<McChar>::iterator currPos = msgData.begin();
     for(size_t msg = 0; msg < lengths.size(); ++msg)
     {
         messages.push_back(std::string(currPos, currPos + lengths[msg] - 1));
         currPos = currPos + lengths[msg];
     }
 }
Returns
error code
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (
        count == 0) {
        per_thread_api_log_str = "count must be > 0";
    } else if (bufSize == 0) {
        per_thread_api_log_str = "bufSize must be > 0";
    } else if (numFetched == nullptr) {
        per_thread_api_log_str = "numFetched  undef (NULL)";
    } else {
        try {
            get_debug_message_log_impl(context,
                count, bufSize,
                sources, types, severities,
                lengths, messageLog, *numFetched);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, count, get_debug_message_log_impl(), and per_thread_api_log_str.
mcGetEventInfo()
MCAPI_ATTR McResult MCAPI_CALL mcGetEventInfo (const McEvent event, McFlags info, McSize bytes, McVoid * pMem, McSize * pNumBytes)
Returns information about the event object..
Parameters
[in] event Specifies the event object being queried..
[in] info Specifies the information to query. See::
[in] bytes Specifies the size in bytes of memory pointed to by pMem. This size must be >= size of the return type as described in the table below..
[in] pMem A pointer to memory where the appropriate result being queried is returned. If param_value is NULL, it is ignored.
[in] pNumBytes Returns the actual size in bytes of data copied to pMem. If pNumBytes is NULL, it is ignored.
Using mcGetEventInfo to determine if a operation identified by event has finished execution (i.e. MC_EVENT_COMMAND_EXECUTION_STATUS returns MC_COMPLETE) is not a synchronization point. There are no guarantees that the memory objects being modified by the operation associated with event will be visible to other enqueued commands.
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
event is not a valid object
bytes is greater than zero but pMem is null.
bytes is zero but pMem is not null.
bytes is zero pMem is null and pNumBytes is null.
bytes is incompatible with info.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (event == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (bytes != 0 && pMem == nullptr) {
        per_thread_api_log_str = "invalid specification (param2 & param3)";
    } else if ((info == MC_EVENT_RUNTIME_EXECUTION_STATUS) && (pMem != nullptr && bytes != sizeof(McResult))) {
        per_thread_api_log_str = "invalid byte size (param2)"; // leads to e.g. "out of bounds" memory access during memcpy
    } else if ((info == MC_EVENT_COMMAND_EXECUTION_STATUS) && (pMem != nullptr && bytes != sizeof(McFlags))) {
        per_thread_api_log_str = "invalid byte size (param2)"; // leads to e.g. "out of bounds" memory access during memcpy
    } else if ((info == MC_EVENT_TIMESTAMP_SUBMIT || info == MC_EVENT_TIMESTAMP_START || info == MC_EVENT_TIMESTAMP_END) && (pMem != nullptr && bytes != sizeof(McSize))) {
        per_thread_api_log_str = "invalid byte size (param2)"; // leads to e.g. "out of bounds" memory access during memcpy
    } else {
        try {
            get_event_info_impl(event, info, bytes, pMem, pNumBytes);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, get_event_info_impl(), MC_EVENT_COMMAND_EXECUTION_STATUS, MC_EVENT_RUNTIME_EXECUTION_STATUS, MC_EVENT_TIMESTAMP_END, MC_EVENT_TIMESTAMP_START, MC_EVENT_TIMESTAMP_SUBMIT, and per_thread_api_log_str.
mcGetInfo()
MCAPI_ATTR McResult MCAPI_CALL mcGetInfo (const McContext context, McFlags info, McSize bytes, McVoid * pMem, McSize * pNumBytes)
Return the value of a selected parameter.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] info Information object being queried. McQueryFlags
[in] bytes Size in bytes of memory pointed to by pMem. This size must be great than or equal to the return type size of data type queried.
[out] pMem Pointer to memory where the appropriate result being queried is returned. If pMem is NULL, it is ignored.
[out] pNumBytes returns the actual size in bytes of data being queried by info. If pNumBytes is NULL, it is ignored.
An example of usage:
McSize numBytes = 0;
McFlags contextFlags;
McResult err =  mcGetInfo(context, MC_CONTEXT_FLAGS, 0, nullptr, &numBytes);
if(err != MC_NO_ERROR)
{
 // deal with error
}
  err = mcGetInfo(context, MC_CONTEXT_FLAGS, numBytes, &contextFlags, nullptr);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
bytes is greater than the returned size of data type queried
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (bytes != 0 && pMem == nullptr) {
        per_thread_api_log_str = "invalid specification (param2 & param3)";
    } else if (false == //
        (info == MC_CONTEXT_FLAGS || //
            info == MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH || //
            info == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT || //
            info == MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS)) // check all possible values
    {
        per_thread_api_log_str = "invalid info flag val (param1)";
    } else if ((info == MC_CONTEXT_FLAGS) && (pMem != nullptr && bytes != sizeof(McFlags))) {
        per_thread_api_log_str = "invalid byte size (param2)"; // leads to e.g. "out of bounds" memory access during memcpy
    } else {
        try {
            get_info_impl(context, info, bytes, pMem, pNumBytes);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, get_info_impl(), MC_CONTEXT_FLAGS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_ATTEMPTS, MC_CONTEXT_GENERAL_POSITION_ENFORCEMENT_CONSTANT, MC_CONTEXT_MAX_DEBUG_MESSAGE_LENGTH, and per_thread_api_log_str.
mcReleaseConnectedComponents()
MCAPI_ATTR McResult MCAPI_CALL mcReleaseConnectedComponents (const McContext context, uint32_t numConnComps, const McConnectedComponent * pConnComps)
To release the memory of a connected component, call this function.
If numConnComps is zero and pConnComps is NULL, the memory of all connected components associated with the context is freed.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
[in] numConnComps Number of connected components in pConnComps whose memory to release.
[in] pConnComps The connected components whose memory will be released.
An example of usage:
McResult err = mcReleaseConnectedComponents(myContext, pConnComps, numConnComps);
// OR (delete all connected components in context)
//McResult err = mcReleaseConnectedComponents(myContext, NULL, 0);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
numConnComps is zero and pConnComps is not NULL (and vice versa).
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else if (numConnComps > 0 && pConnComps == NULL) {
        per_thread_api_log_str = "invalid pointer to connected components";
    } else if (numConnComps == 0 && pConnComps != NULL) {
        per_thread_api_log_str = "number of connected components not set";
    } else {
        try {
            release_connected_components_impl(context, numConnComps, pConnComps);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, NULL, per_thread_api_log_str, and release_connected_components_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcReleaseContext()
MCAPI_ATTR McResult MCAPI_CALL mcReleaseContext (McContext context)
To release the memory of a context, call this function.
This function ensures that all the state attached to context (such as unreleased connected components, and threads) are released, and the memory is deleted.
Parameters
[in] context The context handle that was created by a previous call to mcCreateContext.
An example of usage:
McResult err = mcReleaseContext(myContext);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
pContext is NULL or pContext is not an existing context.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (context == nullptr) {
        per_thread_api_log_str = "context ptr (param0) undef (NULL)";
    } else {
        try {
            release_context_impl(context);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, per_thread_api_log_str, and release_context_impl().
Referenced by Slic3r::MeshBoolean::mcut::do_boolean(), and Slic3r::MeshBoolean::mcut::make_boolean().
mcReleaseEvents()
MCAPI_ATTR McResult MCAPI_CALL mcReleaseEvents (uint32_t numEvents, const McEvent * pEvents)
Decrements the event reference count.
Parameters
numEvents Number of event objects to release
pEvents Array of event objects to release
The event object is deleted once the reference count becomes zero, the specific command identified by this event has completed (or terminated) and there are no commands in the internal-queue of a context that require a wait for this event to complete.
Returns
Error code.
proper exit
MC_INVALID_VALUE
numEvents is greater than 0 and pEvents is NULL (and vice versa).
If an event object in pEvents is not a valid event object.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (numEvents > 0 && pEvents == NULL) {
        per_thread_api_log_str = "invalid pointer to events";
    } else if (numEvents == 0 && pEvents != NULL) {
        per_thread_api_log_str = "number of events not set";
    } else {
        try {
            release_events_impl(numEvents, pEvents);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, NULL, per_thread_api_log_str, and release_events_impl().
mcSetEventCallback()
MCAPI_ATTR McResult MCAPI_CALL mcSetEventCallback (McEvent event, pfn_McEvent_CALLBACK pfn_notify, McVoid * user_data)
Registers a user callback function.
Parameters
[in] event A valid event object returned by the MCUT API.
[in] pfn_notify The event callback function that can be registered by the application..
[in] user_data Will be passed as the user_data argument when pfn_notify is called. user_data can be NULL.
The registered callback function will be called when the execution of the command associated with event is complete. Each call to clSetEventCallback registers the specified user callback function and replaces any previously specified callback. An enqueued callback shall be called before the event object is destroyed. The callback must return promptly. The behavior of calling expensive system routines, or calling blocking MCUT operations etc. in a callback is undefined. It is the application's responsibility to ensure that the callback function is thread-safe.
An example of usage:
McResult err = mcSetEventCallback(ev, someFunctionPointer, NULL);
if(err != MC_NO_ERROR)
{
 // deal with error
}
Returns
Error code.
Error codes
MC_NO_ERROR
proper exit
MC_INVALID_VALUE
event is not a valid object
eventCallback is NULL
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (eventHandle == nullptr) {
        per_thread_api_log_str = "invalid event ptr (NULL)";
    }
    if (eventCallback == nullptr) {
        per_thread_api_log_str = "invalid event callback function ptr (NULL)";
    } else {
        try {
            set_event_callback_impl(eventHandle, eventCallback, data);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, per_thread_api_log_str, and set_event_callback_impl().
mcSetUserEventStatus()
MCAPI_ATTR McResult MCAPI_CALL mcSetUserEventStatus (McEvent event, McInt32 execution_status)
To set the execution status of a user event object, call the function.
Parameters
event is a user event object created using mcCreateUserEvent.
execution_status specifies the new execution status to be set and can be MC_COMPLETE or an McResult value to indicate an error. Thus a negative integer value causes all enqueued commands that wait on this user event to be terminated. mcSetUserEventStatus can only be called once to change the execution status of event.
If there are enqueued commands with user events in the event_wait_list argument of mcEnqueue* commands, the user must ensure that the status of these user events being waited on are set using mcSetUserEventStatus before any MCUT APIs that release MCUT objects except for event objects are called; otherwise the behavior is undefined.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (event == nullptr) {
        per_thread_api_log_str = "event ptr (param0) undef (NULL)";
    } else {
        try {
            set_user_event_status_impl(event, execution_status);
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, per_thread_api_log_str, and set_user_event_status_impl().
mcWaitForEvents()
MCAPI_ATTR McResult MCAPI_CALL mcWaitForEvents (uint32_t numEventsInWaitlist, const McEvent * pEventWaitList)
Waits on the user thread for commands identified by event objects to complete.
Parameters
[in] numEventsInWaitlist Number of events to wait for
[in] pEventWaitList List of events to wait for
Waits on the user thread for commands identified by event objects in pEventWaitList to complete. The events specified in pEventWaitList act as synchronization points.
Returns
Error code.
proper exit
MC_INVALID_VALUE
numEventsInWaitlist is greater than 0 and pEventWaitList is NULL (and vice versa).
If an event object in pEventWaitList is not a valid event object.
{
    McResult return_value = McResult::MC_NO_ERROR;
    per_thread_api_log_str.clear();
    if (pEventWaitList == nullptr && numEventsInWaitlist > 0) {
        per_thread_api_log_str = "invalid event waitlist ptr (NULL)";
    } else if (pEventWaitList != nullptr && numEventsInWaitlist == 0) {
        per_thread_api_log_str = "invalid event waitlist size (zero)";
    } else {
        try {
            McResult waitliststatus = MC_NO_ERROR;
            wait_for_events_impl(numEventsInWaitlist, pEventWaitList, waitliststatus);
            if (waitliststatus != McResult::MC_NO_ERROR) {
                per_thread_api_log_str = "event in waitlist has an error";
            }
        }
        CATCH_POSSIBLE_EXCEPTIONS(per_thread_api_log_str);
    }
    if (!per_thread_api_log_str.empty()) {
        std::fprintf(stderr, "%s(...) -> %s\n", __FUNCTION__, per_thread_api_log_str.c_str());
        if (return_value == McResult::MC_NO_ERROR) // i.e. problem with basic local parameter checks
        {
            return_value = McResult::MC_INVALID_VALUE;
        }
    }
    return return_value;
}
References CATCH_POSSIBLE_EXCEPTIONS, MC_NO_ERROR, per_thread_api_log_str, and wait_for_events_impl().