OrcaSlicer: Slic3r::ObjectWithTimestamp Class Reference
Slic3r::ObjectWithTimestamp Class Reference
#include <src/libslic3r/ObjectID.hpp>
Public Types
using Timestamp = uint64_t
Public Member Functions
Timestamp timestamp () const override throw ()
bool timestamp_matches (const ObjectWithTimestamp &rhs) const throw ()
bool object_id_and_timestamp_match (const ObjectWithTimestamp &rhs) const throw ()
void touch ()
ObjectID id () const
Protected Member Functions
ObjectWithTimestamp ()=default
ObjectWithTimestamp (int)
virtual ~ObjectWithTimestamp ()=default
void copy_timestamp (const ObjectWithTimestamp &rhs)
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Private Member Functions
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
Timestamp m_timestamp { 1 }
ObjectID m_id
Static Private Attributes
static Timestamp s_last_timestamp = 1
static size_t s_last_id = 0
Friends
class cereal::access
class Slic3r::UndoRedo::StackImpl
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
ObjectWithTimestamp() [1/2]
Slic3r::ObjectWithTimestamp::ObjectWithTimestamp () protected default
ObjectWithTimestamp() [2/2]
Slic3r::ObjectWithTimestamp::ObjectWithTimestamp (int) inline protected
: ObjectBase(-1) {}
~ObjectWithTimestamp()
virtual Slic3r::ObjectWithTimestamp::~ObjectWithTimestamp () protected virtual default
Member Function Documentation
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
copy_timestamp()
void Slic3r::ObjectWithTimestamp::copy_timestamp (const ObjectWithTimestamp & rhs) inline protected
{ m_timestamp = rhs.m_timestamp; }
References m_timestamp.
Referenced by Slic3r::FacetsAnnotation::assign(), Slic3r::LayerHeightProfile::assign(), Slic3r::FacetsAnnotation::assign(), and Slic3r::LayerHeightProfile::assign().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
object_id_and_timestamp_match()
bool Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match (const ObjectWithTimestamp & rhs) const throw () inline
{ return this->id() == rhs.id() && m_timestamp == rhs.m_timestamp; }
References Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), and m_timestamp.
serialize()
template<class Archive > void Slic3r::ObjectWithTimestamp::serialize (Archive & ar) inline private
{ ar(m_timestamp); }
References m_timestamp.
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
timestamp()
Timestamp Slic3r::ObjectWithTimestamp::timestamp () const throw () inline override virtual
Reimplemented from Slic3r::ObjectBase.
{ return m_timestamp; }
References m_timestamp.
Referenced by Slic3r::ModelVolume::get_extruders(), Slic3r::ModelVolume::load(), Slic3r::GLVolume::render(), Slic3r::GLVolume::simple_render(), and Slic3r::ModelObject::split().
timestamp_matches()
bool Slic3r::ObjectWithTimestamp::timestamp_matches (const ObjectWithTimestamp & rhs) const throw () inline
{ return m_timestamp == rhs.m_timestamp; }
References m_timestamp.
Referenced by Slic3r::Print::apply(), Slic3r::FacetsAnnotation::assign(), Slic3r::LayerHeightProfile::assign(), Slic3r::FacetsAnnotation::assign(), Slic3r::LayerHeightProfile::assign(), Slic3r::model_custom_seam_data_changed(), Slic3r::model_custom_supports_data_changed(), and Slic3r::model_mmu_segmentation_data_changed().
touch()
void Slic3r::ObjectWithTimestamp::touch () inline
{ m_timestamp = ++ s_last_timestamp; }
References m_timestamp, and s_last_timestamp.
Referenced by Slic3r::LayerHeightProfile::clear(), Slic3r::FacetsAnnotation::reset(), Slic3r::LayerHeightProfile::set(), Slic3r::FacetsAnnotation::set(), and Slic3r::LayerHeightProfile::set().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Slic3r::UndoRedo::StackImpl
friend class Slic3r::UndoRedo::StackImpl friend
Member Data Documentation
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_timestamp
Timestamp Slic3r::ObjectWithTimestamp::m_timestamp { 1 } private
Referenced by copy_timestamp(), object_id_and_timestamp_match(), serialize(), timestamp(), timestamp_matches(), and touch().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
s_last_timestamp
ObjectWithTimestamp::Timestamp Slic3r::ObjectWithTimestamp::s_last_timestamp = 1 static private
Referenced by touch().
The documentation for this class was generated from the following files:
src/libslic3r/ObjectID.hpp
src/libslic3r/ObjectID.cpp