OrcaSlicer: StepIndicator Class Reference
StepIndicator Class Reference
#include <src/slic3r/GUI/Widgets/StepCtrl.hpp>
Public Member Functions
StepIndicator (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
virtual void Rescale ()
void SelectNext ()
void SetHint (wxString hint)
bool SetTipFont (wxFont const &font)
int AppendItem (const wxString &item, wxString const &tip={})
void DeleteAllItems ()
unsigned int GetCount () const
int GetSelection () const
void SelectItem (int item)
void Idle ()
wxString GetItemText (unsigned int item) const
void SetItemText (unsigned int item, wxString const &value)
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void SetCornerRadius (double radius)
void SetBorderWidth (int width)
void SetBorderColor (StateColor const &color)
void SetBorderColorNormal (wxColor const &color)
void SetBackgroundColor (StateColor const &color)
void SetBackgroundColorNormal (wxColor const &color)
void SetBackgroundColor2 (StateColor const &color)
Static Public Member Functions
static wxColor GetParentBackgroundColor (wxWindow *parent)
Protected Member Functions
void eraseEvent (wxEraseEvent &evt)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
Protected Attributes
wxFont font_tip
StateColor clr_bar
StateColor clr_step
StateColor clr_text
StateColor clr_tip
int radius = 7
int bar_width = 4
std::vector< wxString > steps
std::vector< wxString > tips
wxString hint
int step = -1
wxPoint drag_offset
wxPoint pos_thumb
int border_width = 1
StateHandler state_handler
StateColor border_color
StateColor background_color
StateColor background_color2
Private Member Functions
void doRender (wxDC &dc) override
bool sendStepCtrlEvent (bool changing=false)
Private Attributes
ScalableBitmap bmp_ok
Detailed Description
Constructor & Destructor Documentation
StepIndicator()
StepIndicator::StepIndicator (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
    : StepCtrlBase(parent, id, pos, size, style)
    , bmp_ok(this, "step_ok", 12)
{
    SetFont(Label::Body_12);
    font_tip = Label::Body_10;
    clr_bar = 0xE1E1E1;
    clr_step = StateColor(
            std::make_pair(0xACACAC, (int) StateColor::Disabled),
            std::make_pair(0x009688, 0));
    clr_text = StateColor(
            std::make_pair(0xACACAC, (int) StateColor::Disabled),
            std::make_pair(0x323A3D, (int) StateColor::Checked),
            std::make_pair(0x6B6B6B, 0));
    clr_tip = *wxWHITE;
    StaticBox::border_width = 0;
    radius    = bmp_ok.GetBmpHeight() / 2;
    bar_width = bmp_ok.GetBmpHeight() / 20;
    if (bar_width < 2) bar_width = 2;
}
References StepCtrlBase::bar_width, bmp_ok, Label::Body_10, Label::Body_12, StaticBox::border_width, StateColor::Checked, StepCtrlBase::clr_bar, StepCtrlBase::clr_step, StepCtrlBase::clr_text, StepCtrlBase::clr_tip, StateColor::Disabled, StepCtrlBase::font_tip, ScalableBitmap::GetBmpHeight(), and StepCtrlBase::radius.
Member Function Documentation
AppendItem()
int StepCtrlBase::AppendItem (const wxString & item, wxString const & tip = {}) inherited
{
    steps.push_back(item);
    tips.push_back(tip);
    return steps.size() - 1;
}
References StepCtrlBase::steps, and StepCtrlBase::tips.
Referenced by Slic3r::GUI::PublishDialog::create_publish_step_sizer(), Slic3r::GUI::CalibrationDialog::update_cali(), and Slic3r::GUI::AMSControl::UpdateStepCtrl().
Create()
bool StaticBox::Create (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0) inherited
{
    if (style & wxBORDER_NONE)
        border_width = 0;
    wxWindow::Create(parent, id, pos, size, style);
    state_handler.attach({&border_color, &background_color, &background_color2});
    state_handler.update_binds();
    SetBackgroundColour(GetParentBackgroundColor(parent));
    return true;
}
References StateHandler::attach(), StaticBox::background_color, StaticBox::background_color2, StaticBox::border_color, StaticBox::border_width, StaticBox::GetParentBackgroundColor(), size, StaticBox::state_handler, style, and StateHandler::update_binds().
Referenced by FanSwitchButton::FanSwitchButton(), ImageSwitchButton::ImageSwitchButton(), StaticBox::StaticBox(), Button::Create(), SpinInput::Create(), TextInput::Create(), and TempInput::Create().
DeleteAllItems()
void StepCtrlBase::DeleteAllItems () inherited
{
    steps.clear();
    tips.clear();
    if (step >= 0) {
        step = -1;
        sendStepCtrlEvent();
    }
}
References StepCtrlBase::sendStepCtrlEvent(), StepCtrlBase::step, StepCtrlBase::steps, and StepCtrlBase::tips.
Referenced by Slic3r::GUI::CalibrationDialog::update_cali(), and Slic3r::GUI::AMSControl::UpdateStepCtrl().
doRender()
void StepIndicator::doRender (wxDC & dc) override private virtual
Reimplemented from StaticBox.
{
    if (steps.empty()) return;
    StaticBox::doRender(dc);
    wxSize size   = GetSize();
    int    states = state_handler.states();
    if (!IsEnabled()) {
        states = clr_step.Disabled;
    }
    int textWidth = size.x - radius * 5;
    dc.SetFont(GetFont());
    wxString firstLine;
    if (step == 0) dc.SetFont(GetFont().Bold());
    wxSize   firstLineSize = Label::split_lines(dc, textWidth, steps.front(), firstLine);
    wxString lastLine;
    if (step == steps.size() - 1) dc.SetFont(GetFont().Bold());
    wxSize   lastLineSize = Label::split_lines(dc, textWidth, steps.back(), lastLine);
    int      firstPadding = std::max(0, firstLineSize.y / 2 - radius);
    int      lastPadding  = std::max(0, lastLineSize.y / 2 - radius);
    wxRect rcBar = {radius * 2 - bar_width / 2, radius * 2 + firstPadding, bar_width, size.y - radius * 6 - firstPadding - lastPadding};
    int    itemWidth = steps.size() == 1 ? size.y : rcBar.height / (steps.size() - 1);
    // Draw thin bar stick
    dc.SetPen(wxPen(clr_bar.colorForStates(states)));
    dc.SetBrush(wxBrush(clr_bar.colorForStates(states)));
    dc.DrawRectangle(rcBar);
    int circleX = radius * 2;
    int circleY = radius * 3 + firstPadding;
    dc.SetPen(wxPen(clr_step.colorForStates(states)));
    dc.SetBrush(wxBrush(clr_step.colorForStates(states)));
    for (int i = 0; i < steps.size(); ++i) {
        bool disabled = step > i;
        bool checked = step == i;
        // Draw circle point & texts in it
        dc.DrawEllipse(circleX - radius, circleY - radius, radius * 2, radius * 2);
        // Draw content ( icon or text ) in circle
        if (disabled) {
            wxSize sz = bmp_ok.GetBmpSize();
            dc.DrawBitmap(bmp_ok.bmp(), circleX - radius, circleY - radius);
        } else {
            dc.SetFont(font_tip);
            dc.SetTextForeground(clr_tip.colorForStates(states));
            auto tip = tips[i];
            if (tip.IsEmpty()) tip.append(1, wchar_t(L'0' + i + 1));
            wxSize sz = dc.GetTextExtent(tip);
            dc.DrawText(tip, circleX - sz.x / 2, circleY - sz.y / 2 + 1);
        }
        // Draw step text
        dc.SetTextForeground(clr_text.colorForStates(states
                | (disabled ? StateColor::Disabled : checked ? StateColor::Checked : 0)));
        dc.SetFont(checked ? GetFont().Bold() : GetFont());
        wxString text;
        wxSize textSize;
        if (i == 0) {
            text = firstLine;
            textSize = firstLineSize;
        } else if (i == steps.size() - 1) {
            text = lastLine;
            textSize = lastLineSize;
        } else {
            textSize = Label::split_lines(dc, textWidth, steps[i], text);
        }
        dc.DrawText(text, circleX + radius * 3, circleY - (textSize.y / 2));
        circleY += itemWidth;
    }
}
References StepCtrlBase::bar_width, ScalableBitmap::bmp(), bmp_ok, StateColor::Checked, StepCtrlBase::clr_bar, StepCtrlBase::clr_step, StepCtrlBase::clr_text, StepCtrlBase::clr_tip, StateColor::colorForStates(), StateColor::Disabled, StaticBox::doRender(), StepCtrlBase::font_tip, ScalableBitmap::GetBmpSize(), L, StepCtrlBase::radius, size, Label::split_lines(), StaticBox::state_handler, StateHandler::states(), StepCtrlBase::step, StepCtrlBase::steps, and StepCtrlBase::tips.
eraseEvent()
void StaticBox::eraseEvent (wxEraseEvent & evt) protected inherited
{
    // for transparent background, but not work
#ifdef __WXMSW__
    wxDC *dc = evt.GetDC();
    wxSize size = GetSize();
    wxClientDC dc2(GetParent());
    dc->Blit({0, 0}, size, &dc2, GetPosition());
#endif
}
References size.
GetCount()
unsigned int StepCtrlBase::GetCount () const inherited
{ return steps.size(); }
References StepCtrlBase::steps.
GetItemText()
wxString StepCtrlBase::GetItemText (unsigned int item) const inherited
{
    return item < steps.size() ? steps[item] : wxString{};
}
References StepCtrlBase::steps.
GetParentBackgroundColor()
wxColor StaticBox::GetParentBackgroundColor (wxWindow * parent) static inherited
{
    if (auto box = dynamic_cast<StaticBox*>(parent)) {
        if (box->background_color.count() > 0) {
            if (box->background_color2.count() == 0)
                return box->background_color.defaultColor();
            auto s = box->background_color.defaultColor();
            auto e = box->background_color2.defaultColor();
            int r = (s.Red() + e.Red()) / 2;
            int g = (s.Green() + e.Green()) / 2;
            int b = (s.Blue() + e.Blue()) / 2;
            return wxColor(r, g, b);
        }
    }
    if (parent)
        return parent->GetBackgroundColour();
    return *wxWHITE;
}
Referenced by Label::Label(), ScalableButton::ScalableButton(), SwitchButton::SwitchButton(), StaticBox::Create(), and SwitchButton::Rescale().
GetSelection()
int StepCtrlBase::GetSelection () const inherited
{ return step; }
References StepCtrlBase::step.
Idle()
void StepCtrlBase::Idle () inherited
{
    step = -1;
    sendStepCtrlEvent();
    Refresh();
}
References StepCtrlBase::sendStepCtrlEvent(), and StepCtrlBase::step.
Referenced by Slic3r::GUI::AMSControl::SetFilamentStep().
paintEvent()
void StaticBox::paintEvent (wxPaintEvent & evt) protected inherited
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    render(dc);
}
References StaticBox::render().
render()
void StaticBox::render (wxDC & dc) protected inherited
{
#ifdef __WXMSW__
    if (radius == 0) {
        doRender(dc);
        return;
    }
  wxSize size = GetSize();
    if (size.x <= 0 || size.y <= 0)
        return;
    wxMemoryDC memdc;
    wxBitmap bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    //memdc.Blit({0, 0}, size, &dc, {0, 0});
    memdc.SetBackground(wxBrush(GetBackgroundColour()));
    memdc.Clear();
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
  dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References StaticBox::doRender(), StaticBox::radius, and size.
Referenced by StaticBox::paintEvent(), Button::render(), ImageSwitchButton::render(), FanSwitchButton::render(), SpinInput::render(), TempInput::render(), and TextInput::render().
Rescale()
void StepIndicator::Rescale () virtual
{
    bmp_ok.msw_rescale();
    radius    = bmp_ok.GetBmpHeight() / 2;
    bar_width = bmp_ok.GetBmpHeight() / 20;
    if (bar_width < 2) bar_width = 2;
}
References StepCtrlBase::bar_width, bmp_ok, ScalableBitmap::GetBmpHeight(), ScalableBitmap::msw_rescale(), and StepCtrlBase::radius.
SelectItem()
void StepCtrlBase::SelectItem (int item) inherited
{
    if (item == step || item < -1 || item >= steps.size() || !sendStepCtrlEvent(true))
        return;
    step = item;
    sendStepCtrlEvent();
    Refresh();
}
References StepCtrlBase::sendStepCtrlEvent(), StepCtrlBase::step, and StepCtrlBase::steps.
Referenced by StepCtrl::mouseDown(), StepCtrl::mouseUp(), SelectNext(), Slic3r::GUI::AMSControl::SetFilamentStep(), Slic3r::GUI::PublishDialog::SetPublishStep(), and Slic3r::GUI::CalibrationDialog::update_cali().
SelectNext()
void StepIndicator::SelectNext ()
{ SelectItem(step + 1); }
References StepCtrlBase::SelectItem(), and StepCtrlBase::step.
sendStepCtrlEvent()
bool StepCtrlBase::sendStepCtrlEvent (bool changing = false) private inherited
{
    wxCommandEvent event(changing ? EVT_STEP_CHANGING : EVT_STEP_CHANGED, GetId());
    event.SetEventObject(this);
    event.SetInt(step);
    GetEventHandler()->ProcessEvent(event);
    return true;
}
References StepCtrlBase::step.
Referenced by StepCtrlBase::DeleteAllItems(), StepCtrlBase::Idle(), and StepCtrlBase::SelectItem().
SetBackgroundColor()
void StaticBox::SetBackgroundColor (StateColor const & color) inherited
{
    background_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::ParamsPanel::ParamsPanel(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::PublishDialog::create_publish_step_sizer(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::InputIpAddressDialog::on_check_ip_address_failed(), Slic3r::GUI::ColorPickerPopup::on_custom_clr_picker(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), ButtonsListCtrl::OnPaint(), TabButtonsListCtrl::OnPaint(), Slic3r::GUI::ColorPickerPopup::set_def_colour(), and Slic3r::GUI::MonitorPanel::show_status().
SetBackgroundColor2()
void StaticBox::SetBackgroundColor2 (StateColor const & color) inherited
{
    background_color2 = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color2, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::ParamsPanel::ParamsPanel().
SetBackgroundColorNormal()
void StaticBox::SetBackgroundColorNormal (wxColor const & color) inherited
{
    background_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::background_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderColor()
void StaticBox::SetBorderColor (StateColor const & color) inherited
{
    border_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::border_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), TabCtrl::TabCtrl(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), and Slic3r::GUI::MonitorPanel::show_status().
SetBorderColorNormal()
void StaticBox::SetBorderColorNormal (wxColor const & color) inherited
{
    border_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::border_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderWidth()
void StaticBox::SetBorderWidth (int width) inherited
{
    border_width = width;
    Refresh();
}
References StaticBox::border_width.
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::StatusBasePanel::create_bed_control(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), and Slic3r::GUI::StatusBasePanel::create_misc_control().
SetCornerRadius()
void StaticBox::SetCornerRadius (double radius) inherited
{
    this->radius = radius;
    Refresh();
}
References StaticBox::radius.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::ProgressDialog::Create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), SpinInput::createButton(), Slic3r::GUI::StatusPanel::init_scaled_buttons(), Slic3r::GUI::AMSControl::init_scaled_buttons(), Slic3r::GUI::MonitorPanel::init_tabpanel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::MonitorPanel::msw_rescale(), Slic3r::GUI::ConnectPrinterDialog::on_dpi_changed(), Slic3r::GUI::RecenterDialog::on_dpi_changed(), and Slic3r::GUI::SelectMachineDialog::on_dpi_changed().
SetHint()
void StepCtrlBase::SetHint (wxString hint) inherited
{
    this->hint = hint;
}
References StepCtrlBase::hint.
SetItemText()
void StepCtrlBase::SetItemText (unsigned int item, wxString const & value) inherited
{
    if (item >= steps.size()) return;
    steps[item] = value;
}
References StepCtrlBase::steps.
SetTipFont()
bool StepCtrlBase::SetTipFont (wxFont const & font) inherited
{
    font_tip = font;
    return true;
}
References StepCtrlBase::font_tip.
Member Data Documentation
background_color
StateColor StaticBox::background_color protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), StaticBox::SetBackgroundColor(), and StaticBox::SetBackgroundColorNormal().
background_color2
StateColor StaticBox::background_color2 protected inherited
Referenced by StaticBox::Create(), StaticBox::doRender(), and StaticBox::SetBackgroundColor2().
bar_width
int StepCtrlBase::bar_width = 4 protected inherited
Referenced by StepCtrl::StepCtrl(), StepIndicator(), StepCtrl::doRender(), doRender(), StepCtrl::Rescale(), and Rescale().
bmp_ok
ScalableBitmap StepIndicator::bmp_ok private
Referenced by StepIndicator(), doRender(), and Rescale().
border_color
StateColor StaticBox::border_color protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), TabCtrl::doRender(), StaticBox::SetBorderColor(), and StaticBox::SetBorderColorNormal().
border_width
int StaticBox::border_width = 1 protected inherited
Referenced by StepCtrl::StepCtrl(), StepIndicator(), TabCtrl::TabCtrl(), StaticBox::Create(), StaticBox::doRender(), TabCtrl::doRender(), and StaticBox::SetBorderWidth().
clr_bar
StateColor StepCtrlBase::clr_bar protected inherited
Referenced by StepIndicator(), StepCtrl::doRender(), and doRender().
clr_step
StateColor StepCtrlBase::clr_step protected inherited
Referenced by StepIndicator(), StepCtrl::doRender(), and doRender().
clr_text
StateColor StepCtrlBase::clr_text protected inherited
Referenced by StepIndicator(), StepCtrl::doRender(), and doRender().
clr_tip
StateColor StepCtrlBase::clr_tip protected inherited
Referenced by StepIndicator(), StepCtrl::doRender(), and doRender().
drag_offset
wxPoint StepCtrlBase::drag_offset protected inherited
Referenced by StepCtrl::mouseDown(), and StepCtrl::mouseMove().
font_tip
wxFont StepCtrlBase::font_tip protected inherited
Referenced by StepIndicator(), StepCtrl::doRender(), doRender(), and StepCtrlBase::SetTipFont().
hint
wxString StepCtrlBase::hint protected inherited
Referenced by StepCtrl::doRender(), and StepCtrlBase::SetHint().
pos_thumb
wxPoint StepCtrlBase::pos_thumb protected inherited
Referenced by StepCtrl::doRender(), StepCtrl::mouseDown(), StepCtrl::mouseMove(), and StepCtrl::mouseUp().
radius
int StepCtrlBase::radius = 7 protected inherited
Referenced by StepCtrl::StepCtrl(), StepIndicator(), StepCtrl::doRender(), doRender(), StepCtrl::Rescale(), and Rescale().
state_handler
StateHandler StaticBox::state_handler protected inherited
Referenced by Button::Create(), StaticBox::Create(), StaticBox::doRender(), StepCtrl::doRender(), doRender(), TabCtrl::doRender(), Button::GetValue(), Button::render(), ImageSwitchButton::render(), FanSwitchButton::render(), StaticBox::SetBackgroundColor(), StaticBox::SetBackgroundColor2(), StaticBox::SetBorderColor(), Button::SetTextColor(), ImageSwitchButton::SetTextColor(), FanSwitchButton::SetTextColor(), and Button::SetValue().
step
int StepCtrlBase::step = -1 protected inherited
Referenced by StepCtrlBase::DeleteAllItems(), StepCtrl::doRender(), doRender(), StepCtrlBase::GetSelection(), StepCtrlBase::Idle(), StepCtrl::mouseDown(), StepCtrlBase::SelectItem(), SelectNext(), and StepCtrlBase::sendStepCtrlEvent().
steps
std::vector<wxString> StepCtrlBase::steps protected inherited
Referenced by StepCtrlBase::AppendItem(), StepCtrlBase::DeleteAllItems(), StepCtrl::doRender(), doRender(), StepCtrlBase::GetCount(), StepCtrlBase::GetItemText(), StepCtrl::mouseDown(), StepCtrl::mouseMove(), StepCtrl::mouseUp(), StepCtrlBase::SelectItem(), and StepCtrlBase::SetItemText().
tips
std::vector<wxString> StepCtrlBase::tips protected inherited
Referenced by StepCtrlBase::AppendItem(), StepCtrlBase::DeleteAllItems(), StepCtrl::doRender(), and doRender().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/StepCtrl.hpp
src/slic3r/GUI/Widgets/StepCtrl.cpp