OrcaSlicer: Slic3r::GUI::GLToolbar Class Reference
Slic3r::GUI::GLToolbar Class Reference
#include <src/slic3r/GUI/GLToolbar.hpp>
Classes
struct Layout
struct MouseCapture
Public Types
enum EType : unsigned char { Normal , Radio , Num_Types }
Public Member Functions
GLToolbar (EType type, const std::string &name)
~GLToolbar ()
bool init (const BackgroundTexture::Metadata &background_texture)
bool init_arrow (const BackgroundTexture::Metadata &arrow_texture)
Layout::EType get_layout_type () const
void set_layout_type (Layout::EType type)
void set_icon_dirty ()
Layout::EHorizontalOrientation get_horizontal_orientation () const
void set_horizontal_orientation (Layout::EHorizontalOrientation orientation)
Layout::EVerticalOrientation get_vertical_orientation () const
void set_vertical_orientation (Layout::EVerticalOrientation orientation)
void set_position (float top, float left)
void set_border (float border)
void set_separator_size (float size)
void set_gap_size (float size)
void set_icons_size (float size)
void set_text_size (float size)
void set_scale (float scale)
bool is_enabled () const
void set_enabled (bool enable)
bool add_item (const GLToolbarItem::Data &data, GLToolbarItem::EType type=GLToolbarItem::Action)
bool add_separator ()
bool del_all_item ()
float get_icons_size ()
float get_width ()
float get_height ()
void select_item (const std::string &name)
bool is_item_pressed (const std::string &name) const
bool is_item_disabled (const std::string &name) const
bool is_item_visible (const std::string &name) const
bool is_any_item_pressed () const
unsigned int get_items_count () const
int get_item_id (const std::string &name) const
void force_left_action (int item_id, GLCanvas3D &parent)
void force_right_action (int item_id, GLCanvas3D &parent)
std::string get_tooltip () const
void get_additional_tooltip (int item_id, std::string &text)
void set_additional_tooltip (int item_id, const std::string &text)
void set_tooltip (int item_id, const std::string &text)
int get_visible_items_cnt () const
bool update_items_state ()
void render (const GLCanvas3D &parent, GLToolbarItem::EType type=GLToolbarItem::Action)
void render_arrow (const GLCanvas3D &parent, GLToolbarItem *highlighted_item)
bool on_mouse (wxMouseEvent &evt, GLCanvas3D &parent)
GLToolbarItem * get_item (const std::string &item_name)
int generate_button_text_textures (wxFont &font)
int generate_image_textures ()
float get_scaled_icon_size ()
Static Public Attributes
static const float Default_Icons_Size = 40.0f
Private Types
typedef std::vector< GLToolbarItem * > ItemsList
Private Member Functions
void calc_layout ()
float get_width_horizontal () const
float get_width_vertical () const
float get_height_horizontal () const
float get_height_vertical () const
float get_main_size () const
void do_action (GLToolbarItem::EActionType type, int item_id, GLCanvas3D &parent, bool check_hover)
void update_hover_state (const Vec2d &mouse_pos, GLCanvas3D &parent)
void update_hover_state_horizontal (const Vec2d &mouse_pos, GLCanvas3D &parent)
void update_hover_state_vertical (const Vec2d &mouse_pos, GLCanvas3D &parent)
int contains_mouse (const Vec2d &mouse_pos, const GLCanvas3D &parent) const
int contains_mouse_horizontal (const Vec2d &mouse_pos, const GLCanvas3D &parent) const
int contains_mouse_vertical (const Vec2d &mouse_pos, const GLCanvas3D &parent) const
void render_background (float left, float top, float right, float bottom, float border) const
void render_horizontal (const GLCanvas3D &parent, GLToolbarItem::EType type)
void render_vertical (const GLCanvas3D &parent)
bool generate_icons_texture ()
bool update_items_visibility ()
bool update_items_enabled_state ()
Private Attributes
EType m_type
std::string m_name
bool m_enabled
GLTexture m_icons_texture
bool m_icons_texture_dirty
GLTexture m_images_texture
bool m_images_texture_dirty
BackgroundTexture m_background_texture
BackgroundTexture m_arrow_texture
Layout m_layout
ItemsList m_items
MouseCapture m_mouse_capture
int m_pressed_toggable_id
Detailed Description
Member Typedef Documentation
ItemsList
typedef std::vector<GLToolbarItem*> Slic3r::GUI::GLToolbar::ItemsList private
Member Enumeration Documentation
EType
enum Slic3r::GUI::GLToolbar::EType : unsigned char
Enumerator
Normal
Radio
Num_Types
    {
        Normal,
        Radio,
        Num_Types
    };
Constructor & Destructor Documentation
GLToolbar()
Slic3r::GUI::GLToolbar::GLToolbar (GLToolbar::EType type, const std::string & name)
    : m_type(type)
    , m_name(name)
    , m_enabled(false)
    , m_icons_texture_dirty(true)
    , m_pressed_toggable_id(-1)
{
}
~GLToolbar()
Slic3r::GUI::GLToolbar::~GLToolbar ()
{
    for (GLToolbarItem* item : m_items)
    {
        delete item;
    }
}
References m_items.
Member Function Documentation
add_item()
bool Slic3r::GUI::GLToolbar::add_item (const GLToolbarItem::Data & data, GLToolbarItem::EType type = GLToolbarItem::Action)
{
    GLToolbarItem* item = new GLToolbarItem(type, data);
    if (item == nullptr)
        return false;
    m_items.push_back(item);
    m_layout.dirty = true;
    return true;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, m_items, and m_layout.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_separator_toolbar().
add_separator()
bool Slic3r::GUI::GLToolbar::add_separator ()
{
    GLToolbarItem::Data data;
    GLToolbarItem* item = new GLToolbarItem(GLToolbarItem::Separator, data);
    if (item == nullptr)
        return false;
    m_items.push_back(item);
    m_layout.dirty = true;
    return true;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, m_items, m_layout, and Slic3r::GUI::GLToolbarItem::Separator.
Referenced by Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
calc_layout()
void Slic3r::GUI::GLToolbar::calc_layout () private
{
    switch (m_layout.type)
    {
    default:
    case Layout::Horizontal:
    {
        m_layout.width = get_width_horizontal();
        m_layout.height = get_height_horizontal();
        break;
    }
    case Layout::Vertical:
    {
        m_layout.width = get_width_vertical();
        m_layout.height = get_height_vertical();
        break;
    }
    }
    m_layout.dirty = false;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, get_height_horizontal(), get_height_vertical(), get_width_horizontal(), get_width_vertical(), Slic3r::GUI::GLToolbar::Layout::height, Slic3r::GUI::GLToolbar::Layout::Horizontal, m_layout, Slic3r::GUI::GLToolbar::Layout::type, Slic3r::GUI::GLToolbar::Layout::Vertical, and Slic3r::GUI::GLToolbar::Layout::width.
Referenced by get_height(), and get_width().
contains_mouse()
int Slic3r::GUI::GLToolbar::contains_mouse (const Vec2d & mouse_pos, const GLCanvas3D & parent) const private
{
    if (!m_enabled)
        return -1;
    switch (m_layout.type)
    {
    default:
    case Layout::Horizontal: { return contains_mouse_horizontal(mouse_pos, parent); }
    case Layout::Vertical: { return contains_mouse_vertical(mouse_pos, parent); }
    }
}
References contains_mouse_horizontal(), contains_mouse_vertical(), Slic3r::GUI::GLToolbar::Layout::Horizontal, m_enabled, m_layout, Slic3r::GUI::GLToolbar::Layout::type, and Slic3r::GUI::GLToolbar::Layout::Vertical.
Referenced by on_mouse().
contains_mouse_horizontal()
int Slic3r::GUI::GLToolbar::contains_mouse_horizontal (const Vec2d & mouse_pos, const GLCanvas3D & parent) const private
{
    // NB: mouse_pos is already scaled appropriately
    float inv_zoom = (float)wxGetApp().plater()->get_camera().get_inv_zoom();
    float factor = m_layout.scale * inv_zoom;
    Size cnv_size = parent.get_canvas_size();
    Vec2d scaled_mouse_pos((mouse_pos(0) - 0.5 * (double)cnv_size.get_width()) * inv_zoom, (0.5 * (double)cnv_size.get_height() - mouse_pos(1)) * inv_zoom);
    float scaled_icons_size = m_layout.icons_size * factor;
    float scaled_separator_size = m_layout.separator_size * factor;
    float scaled_gap_size = m_layout.gap_size * factor;
    float scaled_border = m_layout.border * factor;
    float left = m_layout.left + scaled_border;
    float top = m_layout.top - scaled_border;
    for (size_t id=0; id<m_items.size(); ++id)
    {
        GLToolbarItem* item = m_items[id];
        if (!item->is_visible())
            continue;
        if (item->is_separator())
        {
            float right = left + scaled_separator_size;
            float bottom = top - scaled_icons_size;
            // mouse inside the separator
            if ((left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top))
                return id;
            left = right;
            right += scaled_gap_size;
            if (id < m_items.size() - 1)
            {
                // mouse inside the gap
                if ((left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top))
                    return -2;
            }
            left = right;
        }
        else
        {
            float right = left + scaled_icons_size;
            float bottom = top - scaled_icons_size;
            //BBS: GUI refactor: GLToolbar
            if (item->is_action_with_text())
                right += scaled_icons_size * item->get_extra_size_ratio();
            // mouse inside the icon
            if ((left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top))
                return id;
            left = right;
            right += scaled_gap_size;
            if (id < m_items.size() - 1)
            {
                // mouse inside the gap
                if ((left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top))
                    return -2;
            }
            left = right;
        }
    }
    return -1;
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::gap_size, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::GLToolbarItem::get_extra_size_ratio(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLToolbar::Layout::icons_size, Slic3r::GUI::GLToolbarItem::is_action_with_text(), Slic3r::GUI::GLToolbarItem::is_separator(), Slic3r::GUI::GLToolbarItem::is_visible(), Slic3r::GUI::GLToolbar::Layout::left, m_items, m_layout, Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, and Slic3r::GUI::GLToolbar::Layout::top.
Referenced by contains_mouse().
contains_mouse_vertical()
int Slic3r::GUI::GLToolbar::contains_mouse_vertical (const Vec2d & mouse_pos, const GLCanvas3D & parent) const private
{
    // NB: mouse_pos is already scaled appropriately
    float inv_zoom = (float)wxGetApp().plater()->get_camera().get_inv_zoom();
    float factor = m_layout.scale * inv_zoom;
    Size cnv_size = parent.get_canvas_size();
    Vec2d scaled_mouse_pos((mouse_pos(0) - 0.5 * (double)cnv_size.get_width()) * inv_zoom, (0.5 * (double)cnv_size.get_height() - mouse_pos(1)) * inv_zoom);
    float scaled_icons_size = m_layout.icons_size * factor;
    float scaled_separator_size = m_layout.separator_size * factor;
    float scaled_gap_size = m_layout.gap_size * factor;
    float scaled_border = m_layout.border * factor;
    float left = m_layout.left + scaled_border;
    float top = m_layout.top - scaled_border;
    for (size_t id=0; id<m_items.size(); ++id)
    {
        GLToolbarItem* item = m_items[id];
        if (!item->is_visible())
            continue;
        if (item->is_separator())
        {
            float right = left + scaled_icons_size;
            float bottom = top - scaled_separator_size;
            // mouse inside the separator
            if ((left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top))
                return id;
            top = bottom;
            bottom -= scaled_gap_size;
            if (id < m_items.size() - 1)
            {
                // mouse inside the gap
                if ((left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top))
                    return -2;
            }
            top = bottom;
        }
        else
        {
            float right = left + scaled_icons_size;
            float bottom = top - scaled_icons_size;
            if (item->is_action_with_text_image())
                right += m_layout.text_size * factor;
            //BBS: GUI refactor: GLToolbar
            if (item->is_action_with_text())
                right += scaled_icons_size * item->get_extra_size_ratio();
            // mouse inside the icon
            if ((left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top))
                return id;
            top = bottom;
            bottom -= scaled_gap_size;
            if (id < m_items.size() - 1)
            {
                // mouse inside the gap
                if ((left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top))
                    return -2;
            }
            top = bottom;
        }
    }
    return -1;
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::gap_size, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::GLToolbarItem::get_extra_size_ratio(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLToolbar::Layout::icons_size, Slic3r::GUI::GLToolbarItem::is_action_with_text(), Slic3r::GUI::GLToolbarItem::is_action_with_text_image(), Slic3r::GUI::GLToolbarItem::is_separator(), Slic3r::GUI::GLToolbarItem::is_visible(), Slic3r::GUI::GLToolbar::Layout::left, m_items, m_layout, Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, Slic3r::GUI::GLToolbar::Layout::text_size, and Slic3r::GUI::GLToolbar::Layout::top.
Referenced by contains_mouse().
del_all_item()
bool Slic3r::GUI::GLToolbar::del_all_item ()
{
    for (int i = 0; i < m_items.size(); i++) {
        delete m_items[i];
        m_items[i] = nullptr;
    }
    m_items.clear();
    m_layout.dirty = true;
    return true;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, m_items, and m_layout.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_separator_toolbar().
do_action()
void Slic3r::GUI::GLToolbar::do_action (GLToolbarItem::EActionType type, int item_id, GLCanvas3D & parent, bool check_hover) private
{
    if ((m_pressed_toggable_id == -1) || (m_pressed_toggable_id == item_id))
    {
        if ((0 <= item_id) && (item_id < (int)m_items.size()))
        {
            GLToolbarItem* item = m_items[item_id];
            if ((item != nullptr) && !item->is_separator() && !item->is_disabled() && (!check_hover || item->is_hovered()))
            {
                if (((type == GLToolbarItem::Right) && item->is_right_toggable()) ||
                    ((type == GLToolbarItem::Left) && item->is_left_toggable()))
                {
                    GLToolbarItem::EState state = item->get_state();
                    if (state == GLToolbarItem::Hover)
                        item->set_state(GLToolbarItem::HoverPressed);
                    else if (state == GLToolbarItem::HoverPressed)
                        item->set_state(GLToolbarItem::Hover);
                    else if (state == GLToolbarItem::Pressed)
                        item->set_state(GLToolbarItem::Normal);
                    else if (state == GLToolbarItem::Normal)
                        item->set_state(GLToolbarItem::Pressed);
                    m_pressed_toggable_id = item->is_pressed() ? item_id : -1;
                    item->reset_last_action_type();
                    parent.render();
                    switch (type)
                    {
                    default:
                    case GLToolbarItem::Left: { item->do_left_action(); break; }
                    case GLToolbarItem::Right: { item->do_right_action(); break; }
                    }
                }
                else
                {
                    if (m_type == Radio)
                        select_item(item->get_name());
                    else
                        item->set_state(item->is_hovered() ? GLToolbarItem::HoverPressed : GLToolbarItem::Pressed);
                    item->reset_last_action_type();
                    parent.render();
                    switch (type)
                    {
                    default:
                    case GLToolbarItem::Left: { item->do_left_action(); break; }
                    case GLToolbarItem::Right: { item->do_right_action(); break; }
                    }
                    if ((m_type == Normal) && (item->get_state() != GLToolbarItem::Disabled))
                    {
                        // the item may get disabled during the action, if not, set it back to normal state
                        item->set_state(GLToolbarItem::Normal);
                        parent.render();
                    }
                }
            }
        }
    }
}
References Slic3r::GUI::GLToolbarItem::Disabled, Slic3r::GUI::GLToolbarItem::do_left_action(), Slic3r::GUI::GLToolbarItem::do_right_action(), Slic3r::GUI::GLToolbarItem::get_name(), Slic3r::GUI::GLToolbarItem::get_state(), Slic3r::GUI::GLToolbarItem::Hover, Slic3r::GUI::GLToolbarItem::HoverPressed, Slic3r::GUI::GLToolbarItem::is_disabled(), Slic3r::GUI::GLToolbarItem::is_hovered(), Slic3r::GUI::GLToolbarItem::is_left_toggable(), Slic3r::GUI::GLToolbarItem::is_pressed(), Slic3r::GUI::GLToolbarItem::is_right_toggable(), Slic3r::GUI::GLToolbarItem::is_separator(), Slic3r::GUI::GLToolbarItem::Left, m_items, m_pressed_toggable_id, m_type, Slic3r::GUI::GLToolbarItem::Normal, Normal, Slic3r::GUI::GLToolbarItem::Pressed, Radio, Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLToolbarItem::reset_last_action_type(), Slic3r::GUI::GLToolbarItem::Right, select_item(), and Slic3r::GUI::GLToolbarItem::set_state().
Referenced by force_left_action(), force_right_action(), and on_mouse().
force_left_action()
void Slic3r::GUI::GLToolbar::force_left_action (int item_id, GLCanvas3D & parent) inline
{ do_action(GLToolbarItem::Left, item_id, parent, false); }
References do_action(), and Slic3r::GUI::GLToolbarItem::Left.
Referenced by Slic3r::GUI::GLCanvas3D::_deactivate_collapse_toolbar_items(), and Slic3r::GUI::GLCanvas3D::force_main_toolbar_left_action().
force_right_action()
void Slic3r::GUI::GLToolbar::force_right_action (int item_id, GLCanvas3D & parent) inline
{ do_action(GLToolbarItem::Right, item_id, parent, false); }
References do_action(), and Slic3r::GUI::GLToolbarItem::Right.
Referenced by Slic3r::GUI::GLCanvas3D::force_main_toolbar_right_action().
generate_button_text_textures()
int Slic3r::GUI::GLToolbar::generate_button_text_textures (wxFont & font)
{
    int ret = 0;
    for (int i = 0; i < (int)m_items.size(); ++i)
    {
        GLToolbarItem* item = m_items[i];
        if (item->is_action_with_text())
        {
            ret |= item->generate_texture(font);
        }
        if (item->is_action_with_text_image())
        {
            ret |= item->generate_texture(font);
        }
    }
    return ret;
}
References Slic3r::GUI::GLToolbarItem::generate_texture(), int, Slic3r::GUI::GLToolbarItem::is_action_with_text(), Slic3r::GUI::GLToolbarItem::is_action_with_text_image(), and m_items.
generate_icons_texture()
bool Slic3r::GUI::GLToolbar::generate_icons_texture () private
{
    std::string path = resources_dir() + "/images/";
    std::vector<std::string> filenames;
    for (GLToolbarItem* item : m_items) {
        const std::string& icon_filename = item->get_icon_filename();
        if (!icon_filename.empty())
            filenames.push_back(path + icon_filename);
    }
    std::vector<std::pair<int, bool>> states;
    //1: white only, 2: gray only, 0 : normal
    //true/false: apply background or not
    if (m_type == Normal) {
        states.push_back({ 1, false }); // Normal
        states.push_back({ 0, false }); // Pressed
        states.push_back({ 2, false }); // Disabled
        states.push_back({ 0, false }); // Hover
        states.push_back({ 0, false }); // HoverPressed
        states.push_back({ 2, false }); // HoverDisabled
        states.push_back({ 0, false }); // HighlightedShown
        states.push_back({ 2, false }); // HighlightedHidden
    }
    else {
        states.push_back({ 1, false }); // Normal
        states.push_back({ 0, true });  // Pressed
        states.push_back({ 2, false }); // Disabled
        states.push_back({ 0, false }); // Hover
        states.push_back({ 1, true });  // HoverPressed
        states.push_back({ 1, false }); // HoverDisabled
        states.push_back({ 0, false }); // HighlightedShown
        states.push_back({ 1, false }); // HighlightedHidden
    }
    unsigned int sprite_size_px = (unsigned int)(m_layout.icons_size * m_layout.scale);
//    // force even size
//    if (sprite_size_px % 2 != 0)
//        sprite_size_px += 1;
    bool res = m_icons_texture.load_from_svg_files_as_sprites_array(filenames, states, sprite_size_px, false);
    if (res)
        m_icons_texture_dirty = false;
    return res;
}
References Slic3r::GUI::GLToolbar::Layout::icons_size, int, Slic3r::GUI::GLTexture::load_from_svg_files_as_sprites_array(), m_icons_texture, m_icons_texture_dirty, m_items, m_layout, m_type, Normal, Slic3r::resources_dir(), and Slic3r::GUI::GLToolbar::Layout::scale.
Referenced by render().
generate_image_textures()
int Slic3r::GUI::GLToolbar::generate_image_textures ()
{
    int ret = 0;
    for (int i = 0; i < (int)m_items.size(); ++i)
    {
        GLToolbarItem* item = m_items[i];
        if (item->is_action_with_text_image()) {
            ret |= item->generate_image_texture();
        }
    }
    return ret;
}
References Slic3r::GUI::GLToolbarItem::generate_image_texture(), int, Slic3r::GUI::GLToolbarItem::is_action_with_text_image(), and m_items.
get_additional_tooltip()
void Slic3r::GUI::GLToolbar::get_additional_tooltip (int item_id, std::string & text)
{
    if (0 <= item_id && item_id < (int)m_items.size())
    {
        text = m_items[item_id]->get_additional_tooltip();
        return;
    }
    text.clear();
}
References m_items.
get_height()
float Slic3r::GUI::GLToolbar::get_height ()
{
    if (m_layout.dirty)
        calc_layout();
    return m_layout.height;
}
References calc_layout(), Slic3r::GUI::GLToolbar::Layout::dirty, Slic3r::GUI::GLToolbar::Layout::height, and m_layout.
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_render_main_toolbar(), Slic3r::GUI::GLCanvas3D::_render_orient_menu(), Slic3r::GUI::GLCanvas3D::get_assemble_view_toolbar_height(), Slic3r::GUI::GLCanvas3D::get_collapse_toolbar_height(), Slic3r::GUI::GLCanvas3D::get_main_toolbar_height(), Slic3r::GUI::GLCanvas3D::get_separator_toolbar_height(), render_horizontal(), Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog(), and render_vertical().
get_height_horizontal()
float Slic3r::GUI::GLToolbar::get_height_horizontal () const private
{
    return (2.0f * m_layout.border + m_layout.icons_size) * m_layout.scale;
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::icons_size, m_layout, and Slic3r::GUI::GLToolbar::Layout::scale.
Referenced by calc_layout().
get_height_vertical()
float Slic3r::GUI::GLToolbar::get_height_vertical () const private
{
    return get_main_size();
}
References get_main_size().
Referenced by calc_layout().
get_horizontal_orientation()
Layout::EHorizontalOrientation Slic3r::GUI::GLToolbar::get_horizontal_orientation () const inline
{ return m_layout.horizontal_orientation; }
References Slic3r::GUI::GLToolbar::Layout::horizontal_orientation, and m_layout.
get_icons_size()
float Slic3r::GUI::GLToolbar::get_icons_size () inline
{ return m_layout.icons_size; }
References Slic3r::GUI::GLToolbar::Layout::icons_size, and m_layout.
get_item()
GLToolbarItem * Slic3r::GUI::GLToolbar::get_item (const std::string & item_name)
{
    if (!m_enabled)
        return nullptr;
    for (GLToolbarItem* item : m_items)
    {
        if (item->get_name() == item_name)
        {
            return item;
        }
    }
    return nullptr;
}
References m_enabled, and m_items.
Referenced by Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_switch_toolbars_icon_filename(), and Slic3r::GUI::GLCanvas3D::LayersEditing::render_variable_layer_height_dialog().
get_item_id()
int Slic3r::GUI::GLToolbar::get_item_id (const std::string & name) const
{
    for (int i = 0; i < (int)m_items.size(); ++i)
    {
        if (m_items[i]->get_name() == name)
            return i;
    }
    return -1;
}
References int, and m_items.
Referenced by Slic3r::GUI::GLCanvas3D::_deactivate_collapse_toolbar_items(), and Slic3r::GUI::GLCanvas3D::get_main_toolbar_item_id().
get_items_count()
unsigned int Slic3r::GUI::GLToolbar::get_items_count () const inline
{ return (unsigned int)m_items.size(); }
References m_items.
get_layout_type()
GLToolbar::Layout::EType Slic3r::GUI::GLToolbar::get_layout_type () const
{
    return m_layout.type;
}
References m_layout, and Slic3r::GUI::GLToolbar::Layout::type.
get_main_size()
float Slic3r::GUI::GLToolbar::get_main_size () const private
{
    float size = 2.0f * m_layout.border;
    for (unsigned int i = 0; i < (unsigned int)m_items.size(); ++i)
    {
        if (!m_items[i]->is_visible())
            continue;
        if (m_items[i]->is_separator())
            size += m_layout.separator_size;
        else
            size += (float)m_layout.icons_size;
    }
    if (m_items.size() > 1)
        size += ((float)m_items.size() - 1.0f) * m_layout.gap_size;
    return size * m_layout.scale;
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::gap_size, Slic3r::GUI::GLToolbar::Layout::icons_size, int, m_items, m_layout, Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, and size.
Referenced by get_height_vertical().
get_scaled_icon_size()
float Slic3r::GUI::GLToolbar::get_scaled_icon_size ()
{
    return m_layout.icons_size * m_layout.scale;
}
References Slic3r::GUI::GLToolbar::Layout::icons_size, m_layout, and Slic3r::GUI::GLToolbar::Layout::scale.
get_tooltip()
std::string Slic3r::GUI::GLToolbar::get_tooltip () const
{
    std::string tooltip;
    for (GLToolbarItem* item : m_items)
    {
        if (item->is_hovered())
        {
            tooltip = item->get_tooltip();
            if (!item->is_pressed())
            {
                const std::string& additional_tooltip = item->get_additional_tooltip();
                if (!additional_tooltip.empty())
                    tooltip += "\n" + additional_tooltip;
                break;
            }
        }
    }
    return tooltip;
}
References m_items.
Referenced by Slic3r::GUI::GLCanvas3D::render().
get_vertical_orientation()
Layout::EVerticalOrientation Slic3r::GUI::GLToolbar::get_vertical_orientation () const inline
{ return m_layout.vertical_orientation; }
References m_layout, and Slic3r::GUI::GLToolbar::Layout::vertical_orientation.
get_visible_items_cnt()
int Slic3r::GUI::GLToolbar::get_visible_items_cnt () const
{
    int cnt = 0;
    for (unsigned int i = 0; i < (unsigned int)m_items.size(); ++i)
        if (m_items[i]->is_visible() && !m_items[i]->is_separator())
            cnt++;
    return cnt;
}
References int, and m_items.
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale().
get_width()
float Slic3r::GUI::GLToolbar::get_width ()
{
    if (m_layout.dirty)
        calc_layout();
    return m_layout.width;
}
References calc_layout(), Slic3r::GUI::GLToolbar::Layout::dirty, m_layout, and Slic3r::GUI::GLToolbar::Layout::width.
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::GLCanvas3D::_render_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_render_main_toolbar(), Slic3r::GUI::GLCanvas3D::_render_orient_menu(), Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_left(), Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_right(), Slic3r::GUI::GLCanvas3D::get_assemble_view_toolbar_width(), Slic3r::GUI::GLCanvas3D::get_collapse_toolbar_width(), Slic3r::GUI::GLCanvas3D::get_main_toolbar_width(), Slic3r::GUI::GLCanvas3D::get_separator_toolbar_width(), render_horizontal(), and render_vertical().
get_width_horizontal()
float Slic3r::GUI::GLToolbar::get_width_horizontal () const private
{
    float size = 2.0f * m_layout.border;
    for (unsigned int i = 0; i < (unsigned int)m_items.size(); ++i)
    {
        if (!m_items[i]->is_visible())
            continue;
        if (m_items[i]->is_separator())
            size += m_layout.separator_size;
        else
        {
            size += (float)m_layout.icons_size;
            if (m_items[i]->is_action_with_text())
                size += m_items[i]->get_extra_size_ratio() * m_layout.icons_size;
            if (m_items[i]->is_action_with_text_image())
                size += m_layout.text_size;
        }
    }
    if (m_items.size() > 1)
        size += ((float)m_items.size() - 1.0f) * m_layout.gap_size;
    return size * m_layout.scale;
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::gap_size, Slic3r::GUI::GLToolbar::Layout::icons_size, int, m_items, m_layout, Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, size, and Slic3r::GUI::GLToolbar::Layout::text_size.
Referenced by calc_layout().
get_width_vertical()
float Slic3r::GUI::GLToolbar::get_width_vertical () const private
{
    float max_extra_text_size = 0.0;
    for (unsigned int i = 0; i < (unsigned int)m_items.size(); ++i)
    {
        if (m_items[i]->is_action_with_text())
        {
            float temp_size = m_items[i]->get_extra_size_ratio() * m_layout.icons_size;
            max_extra_text_size = (temp_size > max_extra_text_size) ? temp_size : max_extra_text_size;
        }
        if (m_items[i]->is_action_with_text_image())
        {
            max_extra_text_size = m_layout.text_size;
        }
    }
    return (2.0f * m_layout.border + m_layout.icons_size + max_extra_text_size) * m_layout.scale;
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::icons_size, int, m_items, m_layout, Slic3r::GUI::GLToolbar::Layout::scale, and Slic3r::GUI::GLToolbar::Layout::text_size.
Referenced by calc_layout().
init()
bool Slic3r::GUI::GLToolbar::init (const BackgroundTexture::Metadata & background_texture)
{
    std::string path = resources_dir() + "/images/";
    bool res = false;
    if (!background_texture.filename.empty())
        res = m_background_texture.texture.load_from_file(path + background_texture.filename, false, GLTexture::SingleThreaded, false);
    if (res)
        m_background_texture.metadata = background_texture;
    return res;
}
References Slic3r::GUI::BackgroundTexture::Metadata::filename, Slic3r::GUI::GLTexture::load_from_file(), m_background_texture, Slic3r::GUI::BackgroundTexture::metadata, Slic3r::resources_dir(), Slic3r::GUI::GLTexture::SingleThreaded, and Slic3r::GUI::BackgroundTexture::texture.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), Slic3r::GUI::GLCanvas3D::_init_separator_toolbar(), and Slic3r::GUI::GLCanvas3D::_switch_toolbars_icon_filename().
init_arrow()
bool Slic3r::GUI::GLToolbar::init_arrow (const BackgroundTexture::Metadata & arrow_texture)
{
    if (m_arrow_texture.texture.get_id() != 0)
        return true;
    std::string path = resources_dir() + "/images/";
    bool res = false;
    if (!arrow_texture.filename.empty()) {
        res = m_arrow_texture.texture.load_from_svg_file(path + arrow_texture.filename, false, false, false, 1000);
    }
    if (res)
        m_arrow_texture.metadata = arrow_texture;
    return res;
}
References Slic3r::GUI::BackgroundTexture::Metadata::filename, Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::GLTexture::load_from_svg_file(), m_arrow_texture, Slic3r::GUI::BackgroundTexture::metadata, Slic3r::resources_dir(), and Slic3r::GUI::BackgroundTexture::texture.
Referenced by Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
is_any_item_pressed()
bool Slic3r::GUI::GLToolbar::is_any_item_pressed () const
{
    for (const GLToolbarItem* item : m_items)
    {
        if (item->is_pressed())
            return true;
    }
    return false;
}
References m_items.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), and update_items_state().
is_enabled()
bool Slic3r::GUI::GLToolbar::is_enabled () const inline
{ return m_enabled; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), Slic3r::GUI::GLCanvas3D::_init_separator_toolbar(), Slic3r::GUI::GLCanvas3D::_max_bounding_box(), Slic3r::GUI::GLCanvas3D::_render_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_render_bed(), Slic3r::GUI::GLCanvas3D::_render_main_toolbar(), Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_left(), Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_right(), Slic3r::GUI::GLCanvas3D::get_collapse_toolbar_height(), Slic3r::GUI::GLCanvas3D::get_collapse_toolbar_width(), Slic3r::GUI::GLCanvas3D::init(), and Slic3r::GUI::GLCanvas3D::render().
is_item_disabled()
bool Slic3r::GUI::GLToolbar::is_item_disabled (const std::string & name) const
{
    for (const GLToolbarItem* item : m_items)
    {
        if (item->get_name() == name)
            return item->is_disabled();
    }
    return false;
}
References m_items.
Referenced by select_item().
is_item_pressed()
bool Slic3r::GUI::GLToolbar::is_item_pressed (const std::string & name) const
{
    for (const GLToolbarItem* item : m_items)
    {
        if (item->get_name() == name)
            return item->is_pressed();
    }
    return false;
}
References m_items.
Referenced by Slic3r::GUI::GLCanvas3D::_deactivate_collapse_toolbar_items(), and Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
is_item_visible()
bool Slic3r::GUI::GLToolbar::is_item_visible (const std::string & name) const
{
    for (const GLToolbarItem* item : m_items)
    {
        if (item->get_name() == name)
            return item->is_visible();
    }
    return false;
}
References m_items.
Referenced by Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
on_mouse()
bool Slic3r::GUI::GLToolbar::on_mouse (wxMouseEvent & evt, GLCanvas3D & parent)
{
    if (!m_enabled)
        return false;
    Vec2d mouse_pos((double)evt.GetX(), (double)evt.GetY());
    bool processed = false;
    // mouse anywhere
    if (!evt.Dragging() && !evt.Leaving() && !evt.Entering() && m_mouse_capture.parent != nullptr) {
        if (m_mouse_capture.any() && (evt.LeftUp() || evt.MiddleUp() || evt.RightUp())) {
            // prevents loosing selection into the scene if mouse down was done inside the toolbar and mouse up was down outside it,
            // as when switching between views
            m_mouse_capture.reset();
            return true;
        }
        m_mouse_capture.reset();
    }
    if (evt.Moving())
        update_hover_state(mouse_pos, parent);
    else if (evt.LeftUp()) {
        if (m_mouse_capture.left) {
            processed = true;
            m_mouse_capture.left = false;
        }
        else
            return false;
    }
    else if (evt.MiddleUp()) {
        if (m_mouse_capture.middle) {
            processed = true;
            m_mouse_capture.middle = false;
        }
        else
            return false;
    }
    else if (evt.RightUp()) {
        if (m_mouse_capture.right) {
            processed = true;
            m_mouse_capture.right = false;
        }
        else
            return false;
    }
    else if (evt.Dragging()) {
        if (m_mouse_capture.any())
            // if the button down was done on this toolbar, prevent from dragging into the scene
            processed = true;
        else
            return false;
    }
    int item_id = contains_mouse(mouse_pos, parent);
    if (item_id != -1) {
        // mouse inside toolbar
        if (evt.LeftDown() || evt.LeftDClick()) {
            m_mouse_capture.left = true;
            m_mouse_capture.parent = &parent;
            processed = true;
            if (item_id != -2 && !m_items[item_id]->is_separator() && !m_items[item_id]->is_disabled() &&
                (m_pressed_toggable_id == -1 || m_items[item_id]->get_last_action_type() == GLToolbarItem::Left)) {
                // mouse is inside an icon
                do_action(GLToolbarItem::Left, item_id, parent, true);
                parent.set_as_dirty();
            }
        }
        else if (evt.MiddleDown()) {
            m_mouse_capture.middle = true;
            m_mouse_capture.parent = &parent;
        }
        else if (evt.RightDown()) {
            m_mouse_capture.right = true;
            m_mouse_capture.parent = &parent;
            processed = true;
            if (item_id != -2 && !m_items[item_id]->is_separator() && !m_items[item_id]->is_disabled() &&
                (m_pressed_toggable_id == -1 || m_items[item_id]->get_last_action_type() == GLToolbarItem::Right)) {
                // mouse is inside an icon
                do_action(GLToolbarItem::Right, item_id, parent, true);
                parent.set_as_dirty();
            }
        }
    }
    return processed;
}
References Slic3r::GUI::GLToolbar::MouseCapture::any(), contains_mouse(), do_action(), Slic3r::GUI::GLToolbarItem::Left, Slic3r::GUI::GLToolbar::MouseCapture::left, m_enabled, m_items, m_mouse_capture, m_pressed_toggable_id, Slic3r::GUI::GLToolbar::MouseCapture::middle, Slic3r::GUI::GLToolbar::MouseCapture::parent, Slic3r::GUI::GLToolbar::MouseCapture::reset(), Slic3r::GUI::GLToolbarItem::Right, Slic3r::GUI::GLToolbar::MouseCapture::right, Slic3r::GUI::GLCanvas3D::set_as_dirty(), and update_hover_state().
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse().
render()
void Slic3r::GUI::GLToolbar::render (const GLCanvas3D & parent, GLToolbarItem::EType type = GLToolbarItem::Action)
{
    if (!m_enabled || m_items.empty())
        return;
    if (m_icons_texture_dirty)
        generate_icons_texture();
    switch (m_layout.type)
    {
    default:
    case Layout::Horizontal: { render_horizontal(parent,type); break; }
    case Layout::Vertical: { render_vertical(parent); break; }
    }
}
References generate_icons_texture(), Slic3r::GUI::GLToolbar::Layout::Horizontal, m_enabled, m_icons_texture_dirty, m_items, m_layout, render_horizontal(), render_vertical(), Slic3r::GUI::GLToolbar::Layout::type, and Slic3r::GUI::GLToolbar::Layout::Vertical.
Referenced by Slic3r::GUI::GLCanvas3D::_render_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_render_collapse_toolbar(), Slic3r::GUI::GLCanvas3D::_render_main_toolbar(), Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_left(), and Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_right().
render_arrow()
void Slic3r::GUI::GLToolbar::render_arrow (const GLCanvas3D & parent, GLToolbarItem * highlighted_item)
{
    // arrow texture not initialized
    if (m_arrow_texture.texture.get_id() == 0)
        return;
    float inv_zoom = (float)wxGetApp().plater()->get_camera().get_inv_zoom();
    float factor = inv_zoom * m_layout.scale;
    float scaled_icons_size = m_layout.icons_size * factor;
    float scaled_separator_size = m_layout.separator_size * factor;
    float scaled_gap_size = m_layout.gap_size * factor;
    float border = m_layout.border * factor;
    float separator_stride = scaled_separator_size + scaled_gap_size;
    float icon_stride = scaled_icons_size + scaled_gap_size;
    float left = m_layout.left;
    float top = m_layout.top - icon_stride;
    bool found = false;
    for (const GLToolbarItem* item : m_items) {
        if (!item->is_visible())
            continue;
        if (item->is_separator())
            left += separator_stride;
        else {
            if (item->get_name() == highlighted_item->get_name()) {
                found = true;
                break;
            }
            left += icon_stride;
        }
    }
    if (!found)
        return;
    left += border;
    top -= separator_stride;
    float right = left + scaled_icons_size;
    unsigned int tex_id = m_arrow_texture.texture.get_id();
    // arrow width and height
    float arr_tex_width = (float)m_arrow_texture.texture.get_width();
    float arr_tex_height = (float)m_arrow_texture.texture.get_height();
    if ((tex_id != 0) && (arr_tex_width > 0) && (arr_tex_height > 0)) {
        float inv_tex_width = (arr_tex_width != 0.0f) ? 1.0f / arr_tex_width : 0.0f;
        float inv_tex_height = (arr_tex_height != 0.0f) ? 1.0f / arr_tex_height : 0.0f;
        float internal_left = left + border - scaled_icons_size * 1.5f; // add scaled_icons_size for huge arrow
        float internal_right = right - border + scaled_icons_size * 1.5f;
        float internal_top = top - border;
        // bottom is not moving and should be calculated from arrow texture sides ratio
        float arrow_sides_ratio = (float)m_arrow_texture.texture.get_height() / (float)m_arrow_texture.texture.get_width();
        float internal_bottom = internal_top - (internal_right - internal_left) * arrow_sides_ratio ;
        float internal_left_uv = (float)m_arrow_texture.metadata.left * inv_tex_width;
        float internal_right_uv = 1.0f - (float)m_arrow_texture.metadata.right * inv_tex_width;
        float internal_top_uv = 1.0f - (float)m_arrow_texture.metadata.top * inv_tex_height;
        float internal_bottom_uv = (float)m_arrow_texture.metadata.bottom * inv_tex_height;
        GLTexture::render_sub_texture(tex_id, internal_left, internal_right, internal_bottom, internal_top, { { internal_left_uv, internal_top_uv }, { internal_right_uv, internal_top_uv }, { internal_right_uv, internal_bottom_uv }, { internal_left_uv, internal_bottom_uv } });
    }
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::GUI::GLToolbar::Layout::gap_size, Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::GLToolbarItem::get_name(), Slic3r::GUI::GLTexture::get_width(), Slic3r::GUI::GLToolbar::Layout::icons_size, Slic3r::GUI::BackgroundTexture::Metadata::left, Slic3r::GUI::GLToolbar::Layout::left, m_arrow_texture, m_items, m_layout, Slic3r::GUI::BackgroundTexture::metadata, Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, Slic3r::GUI::BackgroundTexture::texture, Slic3r::GUI::BackgroundTexture::Metadata::top, and Slic3r::GUI::GLToolbar::Layout::top.
Referenced by Slic3r::GUI::GLCanvas3D::_render_main_toolbar().
render_background()
void Slic3r::GUI::GLToolbar::render_background (float left, float top, float right, float bottom, float border) const private
{
    unsigned int tex_id = m_background_texture.texture.get_id();
    float tex_width = (float)m_background_texture.texture.get_width();
    float tex_height = (float)m_background_texture.texture.get_height();
    if ((tex_id != 0) && (tex_width > 0) && (tex_height > 0))
    {
        float inv_tex_width = (tex_width != 0.0f) ? 1.0f / tex_width : 0.0f;
        float inv_tex_height = (tex_height != 0.0f) ? 1.0f / tex_height : 0.0f;
        float internal_left = left + border;
        float internal_right = right - border;
        float internal_top = top - border;
        float internal_bottom = bottom + border;
        float left_uv = 0.0f;
        float right_uv = 1.0f;
        float top_uv = 1.0f;
        float bottom_uv = 0.0f;
        float internal_left_uv = (float)m_background_texture.metadata.left * inv_tex_width;
        float internal_right_uv = 1.0f - (float)m_background_texture.metadata.right * inv_tex_width;
        float internal_top_uv = 1.0f - (float)m_background_texture.metadata.top * inv_tex_height;
        float internal_bottom_uv = (float)m_background_texture.metadata.bottom * inv_tex_height;
        // top-left corner
        if ((m_layout.horizontal_orientation == Layout::HO_Left) || (m_layout.vertical_orientation == Layout::VO_Top))
            GLTexture::render_sub_texture(tex_id, left, internal_left, internal_top, top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        else
            GLTexture::render_sub_texture(tex_id, left, internal_left, internal_top, top, { { left_uv, internal_top_uv }, { internal_left_uv, internal_top_uv }, { internal_left_uv, top_uv }, { left_uv, top_uv } });
        // top edge
        if (m_layout.vertical_orientation == Layout::VO_Top)
            GLTexture::render_sub_texture(tex_id, internal_left, internal_right, internal_top, top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        else
            GLTexture::render_sub_texture(tex_id, internal_left, internal_right, internal_top, top, { { internal_left_uv, internal_top_uv }, { internal_right_uv, internal_top_uv }, { internal_right_uv, top_uv }, { internal_left_uv, top_uv } });
        // top-right corner
        if ((m_layout.horizontal_orientation == Layout::HO_Right) || (m_layout.vertical_orientation == Layout::VO_Top))
            GLTexture::render_sub_texture(tex_id, internal_right, right, internal_top, top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        else
            GLTexture::render_sub_texture(tex_id, internal_right, right, internal_top, top, { { internal_right_uv, internal_top_uv }, { right_uv, internal_top_uv }, { right_uv, top_uv }, { internal_right_uv, top_uv } });
        // center-left edge
        if (m_layout.horizontal_orientation == Layout::HO_Left)
            GLTexture::render_sub_texture(tex_id, left, internal_left, internal_bottom, internal_top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        else
            GLTexture::render_sub_texture(tex_id, left, internal_left, internal_bottom, internal_top, { { left_uv, internal_bottom_uv }, { internal_left_uv, internal_bottom_uv }, { internal_left_uv, internal_top_uv }, { left_uv, internal_top_uv } });
        // center
        GLTexture::render_sub_texture(tex_id, internal_left, internal_right, internal_bottom, internal_top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        // center-right edge
        if (m_layout.horizontal_orientation == Layout::HO_Right)
            GLTexture::render_sub_texture(tex_id, internal_right, right, internal_bottom, internal_top, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        else
            GLTexture::render_sub_texture(tex_id, internal_right, right, internal_bottom, internal_top, { { internal_right_uv, internal_bottom_uv }, { right_uv, internal_bottom_uv }, { right_uv, internal_top_uv }, { internal_right_uv, internal_top_uv } });
        // bottom-left corner
        if ((m_layout.horizontal_orientation == Layout::HO_Left) || (m_layout.vertical_orientation == Layout::VO_Bottom))
            GLTexture::render_sub_texture(tex_id, left, internal_left, bottom, internal_bottom, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        else
            GLTexture::render_sub_texture(tex_id, left, internal_left, bottom, internal_bottom, { { left_uv, bottom_uv }, { internal_left_uv, bottom_uv }, { internal_left_uv, internal_bottom_uv }, { left_uv, internal_bottom_uv } });
        // bottom edge
        if (m_layout.vertical_orientation == Layout::VO_Bottom)
            GLTexture::render_sub_texture(tex_id, internal_left, internal_right, bottom, internal_bottom, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        else
            GLTexture::render_sub_texture(tex_id, internal_left, internal_right, bottom, internal_bottom, { { internal_left_uv, bottom_uv }, { internal_right_uv, bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_left_uv, internal_bottom_uv } });
        // bottom-right corner
        if ((m_layout.horizontal_orientation == Layout::HO_Right) || (m_layout.vertical_orientation == Layout::VO_Bottom))
            GLTexture::render_sub_texture(tex_id, internal_right, right, bottom, internal_bottom, { { internal_left_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv }, { internal_right_uv, internal_top_uv }, { internal_left_uv, internal_top_uv } });
        else
            GLTexture::render_sub_texture(tex_id, internal_right, right, bottom, internal_bottom, { { internal_right_uv, bottom_uv }, { right_uv, bottom_uv }, { right_uv, internal_bottom_uv }, { internal_right_uv, internal_bottom_uv } });
    }
}
References Slic3r::GUI::BackgroundTexture::Metadata::bottom, Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), Slic3r::GUI::GLTexture::get_width(), Slic3r::GUI::GLToolbar::Layout::HO_Left, Slic3r::GUI::GLToolbar::Layout::HO_Right, Slic3r::GUI::GLToolbar::Layout::horizontal_orientation, Slic3r::GUI::BackgroundTexture::Metadata::left, m_background_texture, m_layout, Slic3r::GUI::BackgroundTexture::metadata, Slic3r::GUI::GLTexture::render_sub_texture(), Slic3r::GUI::BackgroundTexture::Metadata::right, Slic3r::GUI::BackgroundTexture::texture, Slic3r::GUI::BackgroundTexture::Metadata::top, Slic3r::GUI::GLToolbar::Layout::vertical_orientation, Slic3r::GUI::GLToolbar::Layout::VO_Bottom, and Slic3r::GUI::GLToolbar::Layout::VO_Top.
Referenced by render_horizontal(), and render_vertical().
render_horizontal()
void Slic3r::GUI::GLToolbar::render_horizontal (const GLCanvas3D & parent, GLToolbarItem::EType type) private
{
    float inv_zoom = (float)wxGetApp().plater()->get_camera().get_inv_zoom();
    float factor = inv_zoom * m_layout.scale;
    float scaled_icons_size = m_layout.icons_size * factor;
    float scaled_separator_size = m_layout.separator_size * factor;
    float scaled_gap_size = m_layout.gap_size * factor;
    float scaled_border = m_layout.border * factor;
    float scaled_width = get_width() * inv_zoom;
    float scaled_height = get_height() * inv_zoom;
    float separator_stride = scaled_separator_size + scaled_gap_size;
    float icon_stride = scaled_icons_size + scaled_gap_size;
    float left = m_layout.left;
    float top = m_layout.top;
    float right = left + scaled_width;
    if (type == GLToolbarItem::SeparatorLine)
        right = left + scaled_width * 0.5;
    float bottom = top - scaled_height;
    render_background(left, top, right, bottom, scaled_border);
    left += scaled_border;
    top -= scaled_border;
    // renders icons
    for (const GLToolbarItem* item : m_items)
    {
        if (!item->is_visible())
            continue;
        if (item->is_separator())
            left += separator_stride;
        else
        {
            //BBS GUI refactor
            item->render_left_pos = left;
            if (!item->is_action_with_text_image()) {
                unsigned int tex_id = m_icons_texture.get_id();
                int tex_width = m_icons_texture.get_width();
                int tex_height = m_icons_texture.get_height();
                if ((tex_id == 0) || (tex_width <= 0) || (tex_height <= 0))
                    return;
                item->render(tex_id, left, left + scaled_icons_size, top - scaled_icons_size, top, (unsigned int)tex_width, (unsigned int)tex_height, (unsigned int)(m_layout.icons_size * m_layout.scale));
            }
            //BBS: GUI refactor: GLToolbar
            if (item->is_action_with_text())
            {
                float scaled_text_size = item->get_extra_size_ratio() * scaled_icons_size;
                item->render_text(left + scaled_icons_size, left + scaled_icons_size + scaled_text_size, top - scaled_icons_size, top);
                left += scaled_text_size;
            }
            left += icon_stride;
        }
    }
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::gap_size, get_height(), Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), get_width(), Slic3r::GUI::GLTexture::get_width(), Slic3r::GUI::GLToolbar::Layout::icons_size, int, Slic3r::GUI::GLToolbar::Layout::left, m_icons_texture, m_items, m_layout, render_background(), Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, Slic3r::GUI::GLToolbarItem::SeparatorLine, and Slic3r::GUI::GLToolbar::Layout::top.
Referenced by render().
render_vertical()
void Slic3r::GUI::GLToolbar::render_vertical (const GLCanvas3D & parent) private
{
    float inv_zoom = (float)wxGetApp().plater()->get_camera().get_inv_zoom();
    float factor = inv_zoom * m_layout.scale;
    float scaled_icons_size = m_layout.icons_size * factor;
    float scaled_separator_size = m_layout.separator_size * factor;
    float scaled_gap_size = m_layout.gap_size * factor;
    float scaled_border = m_layout.border * factor;
    float scaled_width = get_width() * inv_zoom;
    float scaled_height = get_height() * inv_zoom;
    float separator_stride = scaled_separator_size + scaled_gap_size;
    float icon_stride = scaled_icons_size + scaled_gap_size;
    float left = m_layout.left;
    float top = m_layout.top;
    float right = left + scaled_width;
    float bottom = top - scaled_height;
    render_background(left, top, right, bottom, scaled_border);
    left += scaled_border;
    top -= scaled_border;
    // renders icons
    for (const GLToolbarItem* item : m_items) {
        if (!item->is_visible())
            continue;
        if (item->is_separator())
            top -= separator_stride;
        else {
            unsigned int tex_id;
            int tex_width, tex_height;
            if (item->is_action_with_text_image()) {
                float scaled_text_size = m_layout.text_size * factor;
                float scaled_text_width = item->get_extra_size_ratio() * scaled_icons_size;
                float scaled_text_border = 2.5 * factor;
                float scaled_text_height = scaled_icons_size / 2.0f;
                item->render_text(left, left + scaled_text_size, top - scaled_text_border - scaled_text_height, top - scaled_text_border);
                float image_left = left + scaled_text_size;
                tex_id = item->m_data.image_texture.get_id();
                tex_width = item->m_data.image_texture.get_width();
                tex_height = item->m_data.image_texture.get_height();
                if ((tex_id == 0) || (tex_width <= 0) || (tex_height <= 0))
                    return;
                item->render_image(tex_id, image_left, image_left + scaled_icons_size, top - scaled_icons_size, top, (unsigned int)tex_width, (unsigned int)tex_height, (unsigned int)(m_layout.icons_size * m_layout.scale));
            }
            else {
                tex_id = m_icons_texture.get_id();
                tex_width = m_icons_texture.get_width();
                tex_height = m_icons_texture.get_height();
                if ((tex_id == 0) || (tex_width <= 0) || (tex_height <= 0))
                    return;
                item->render(tex_id, left, left + scaled_icons_size, top - scaled_icons_size, top, (unsigned int)tex_width, (unsigned int)tex_height, (unsigned int)(m_layout.icons_size * m_layout.scale));
                //BBS: GUI refactor: GLToolbar
            }
            if (item->is_action_with_text())
            {
                float scaled_text_width = item->get_extra_size_ratio() * scaled_icons_size;
                float scaled_text_height = scaled_icons_size;
                item->render_text(left + scaled_icons_size, left + scaled_icons_size + scaled_text_width, top - scaled_text_height, top);
            }
            top -= icon_stride;
        }
    }
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::gap_size, get_height(), Slic3r::GUI::GLTexture::get_height(), Slic3r::GUI::GLTexture::get_id(), get_width(), Slic3r::GUI::GLTexture::get_width(), Slic3r::GUI::GLToolbar::Layout::icons_size, int, Slic3r::GUI::GLToolbar::Layout::left, m_icons_texture, m_items, m_layout, render_background(), Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, Slic3r::GUI::GLToolbar::Layout::text_size, and Slic3r::GUI::GLToolbar::Layout::top.
Referenced by render().
select_item()
void Slic3r::GUI::GLToolbar::select_item (const std::string & name)
{
    if (is_item_disabled(name))
        return;
    for (GLToolbarItem* item : m_items)
    {
        if (!item->is_disabled())
        {
            bool hover = item->is_hovered();
            item->set_state((item->get_name() == name) ? (hover ? GLToolbarItem::HoverPressed : GLToolbarItem::Pressed) : (hover ? GLToolbarItem::Hover : GLToolbarItem::Normal));
        }
    }
}
References Slic3r::GUI::GLToolbarItem::Hover, Slic3r::GUI::GLToolbarItem::HoverPressed, is_item_disabled(), m_items, Slic3r::GUI::GLToolbarItem::Normal, and Slic3r::GUI::GLToolbarItem::Pressed.
Referenced by do_action().
set_additional_tooltip()
void Slic3r::GUI::GLToolbar::set_additional_tooltip (int item_id, const std::string & text)
{
    if (0 <= item_id && item_id < (int)m_items.size())
        m_items[item_id]->set_additional_tooltip(text);
}
References m_items.
set_border()
void Slic3r::GUI::GLToolbar::set_border (float border)
{
    m_layout.border = border;
    m_layout.dirty = true;
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbar::Layout::dirty, and m_layout.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_separator_toolbar().
set_enabled()
void Slic3r::GUI::GLToolbar::set_enabled (bool enable) inline
{ m_enabled = enable; }
References m_enabled.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), Slic3r::GUI::GLCanvas3D::_init_separator_toolbar(), Slic3r::GUI::GLCanvas3D::enable_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::enable_main_toolbar(), and Slic3r::GUI::GLCanvas3D::enable_separator_toolbar().
set_gap_size()
void Slic3r::GUI::GLToolbar::set_gap_size (float size)
{
    m_layout.gap_size = size;
    m_layout.dirty = true;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, Slic3r::GUI::GLToolbar::Layout::gap_size, m_layout, and size.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
set_horizontal_orientation()
void Slic3r::GUI::GLToolbar::set_horizontal_orientation (Layout::EHorizontalOrientation orientation) inline
{ m_layout.horizontal_orientation = orientation; }
References Slic3r::GUI::GLToolbar::Layout::horizontal_orientation, and m_layout.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_separator_toolbar().
set_icon_dirty()
void Slic3r::GUI::GLToolbar::set_icon_dirty () inline
{ m_icons_texture_dirty = true; }
References m_icons_texture_dirty.
Referenced by Slic3r::GUI::GLCanvas3D::on_change_color_mode().
set_icons_size()
void Slic3r::GUI::GLToolbar::set_icons_size (float size)
{
    if (m_layout.icons_size != size)
    {
        m_layout.icons_size = size;
        m_layout.dirty = true;
        m_icons_texture_dirty = true;
    }
}
References Slic3r::GUI::GLToolbar::Layout::dirty, Slic3r::GUI::GLToolbar::Layout::icons_size, m_icons_texture_dirty, m_layout, and size.
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), and Slic3r::GUI::GLCanvas3D::_render_overlays().
set_layout_type()
void Slic3r::GUI::GLToolbar::set_layout_type (Layout::EType type)
{
    m_layout.type = type;
    m_layout.dirty = true;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, m_layout, and Slic3r::GUI::GLToolbar::Layout::type.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_separator_toolbar().
set_position()
void Slic3r::GUI::GLToolbar::set_position (float top, float left)
{
    m_layout.top = top;
    m_layout.left = left;
}
References Slic3r::GUI::GLToolbar::Layout::left, m_layout, and Slic3r::GUI::GLToolbar::Layout::top.
Referenced by Slic3r::GUI::GLCanvas3D::_render_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_render_collapse_toolbar(), Slic3r::GUI::GLCanvas3D::_render_main_toolbar(), Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_left(), and Slic3r::GUI::GLCanvas3D::_render_separator_toolbar_right().
set_scale()
void Slic3r::GUI::GLToolbar::set_scale (float scale)
{
    if (m_layout.scale != scale) {
        m_layout.scale = scale;
        m_layout.dirty = true;
        m_icons_texture_dirty = true;
    }
}
References Slic3r::GUI::GLToolbar::Layout::dirty, m_icons_texture_dirty, m_layout, Slic3r::GUI::GLToolbar::Layout::scale, and scale().
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), and Slic3r::GUI::GLCanvas3D::_render_overlays().
set_separator_size()
void Slic3r::GUI::GLToolbar::set_separator_size (float size)
{
    m_layout.separator_size = size;
    m_layout.dirty = true;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, m_layout, Slic3r::GUI::GLToolbar::Layout::separator_size, and size.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_main_toolbar().
set_text_size()
void Slic3r::GUI::GLToolbar::set_text_size (float size)
{
    if (m_layout.text_size != size)
    {
        m_layout.text_size = size;
        m_layout.dirty = true;
    }
}
References Slic3r::GUI::GLToolbar::Layout::dirty, m_layout, size, and Slic3r::GUI::GLToolbar::Layout::text_size.
set_tooltip()
void Slic3r::GUI::GLToolbar::set_tooltip (int item_id, const std::string & text)
{
    if (0 <= item_id && item_id < (int)m_items.size())
        m_items[item_id]->set_tooltip(text);
}
References m_items.
set_vertical_orientation()
void Slic3r::GUI::GLToolbar::set_vertical_orientation (Layout::EVerticalOrientation orientation) inline
{ m_layout.vertical_orientation = orientation; }
References m_layout, and Slic3r::GUI::GLToolbar::Layout::vertical_orientation.
Referenced by Slic3r::GUI::GLCanvas3D::_init_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::_init_main_toolbar(), and Slic3r::GUI::GLCanvas3D::_init_separator_toolbar().
update_hover_state()
void Slic3r::GUI::GLToolbar::update_hover_state (const Vec2d & mouse_pos, GLCanvas3D & parent) private
{
    if (!m_enabled)
        return;
    switch (m_layout.type)
    {
    default:
    case Layout::Horizontal: { update_hover_state_horizontal(mouse_pos, parent); break; }
    case Layout::Vertical: { update_hover_state_vertical(mouse_pos, parent); break; }
    }
}
References Slic3r::GUI::GLToolbar::Layout::Horizontal, m_enabled, m_layout, Slic3r::GUI::GLToolbar::Layout::type, update_hover_state_horizontal(), update_hover_state_vertical(), and Slic3r::GUI::GLToolbar::Layout::Vertical.
Referenced by on_mouse().
update_hover_state_horizontal()
void Slic3r::GUI::GLToolbar::update_hover_state_horizontal (const Vec2d & mouse_pos, GLCanvas3D & parent) private
{
    // NB: mouse_pos is already scaled appropriately
    float inv_zoom = (float)wxGetApp().plater()->get_camera().get_inv_zoom();
    float factor = m_layout.scale * inv_zoom;
    Size cnv_size = parent.get_canvas_size();
    Vec2d scaled_mouse_pos((mouse_pos(0) - 0.5 * (double)cnv_size.get_width()) * inv_zoom, (0.5 * (double)cnv_size.get_height() - mouse_pos(1)) * inv_zoom);
    float scaled_icons_size = m_layout.icons_size * factor;
    float scaled_separator_size = m_layout.separator_size * factor;
    float scaled_gap_size = m_layout.gap_size * factor;
    float scaled_border = m_layout.border * factor;
    float separator_stride = scaled_separator_size + scaled_gap_size;
    float icon_stride = scaled_icons_size + scaled_gap_size;
    float left = m_layout.left + scaled_border;
    float top = m_layout.top - scaled_border;
    for (GLToolbarItem* item : m_items)
    {
        if (!item->is_visible())
            continue;
        if (item->is_separator())
            left += separator_stride;
        else
        {
            float right = left + scaled_icons_size;
            float bottom = top - scaled_icons_size;
            //BBS: GUI refactor: GLToolbar
            if (item->is_action_with_text())
                right += scaled_icons_size * item->get_extra_size_ratio();
            GLToolbarItem::EState state = item->get_state();
            bool inside = (left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top);
            switch (state)
            {
            case GLToolbarItem::Normal:
            {
                if (inside)
                {
                    item->set_state(GLToolbarItem::Hover);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::Hover:
            {
                if (!inside)
                {
                    item->set_state(GLToolbarItem::Normal);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::Pressed:
            {
                if (inside)
                {
                    item->set_state(GLToolbarItem::HoverPressed);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::HoverPressed:
            {
                if (!inside)
                {
                    item->set_state(GLToolbarItem::Pressed);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::Disabled:
            {
                if (inside)
                {
                    item->set_state(GLToolbarItem::HoverDisabled);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::HoverDisabled:
            {
                if (!inside)
                {
                    item->set_state(GLToolbarItem::Disabled);
                    parent.set_as_dirty();
                }
                break;
            }
            default:
            {
                break;
            }
            }
            left += icon_stride;
            //BBS: GUI refactor: GLToolbar
            if (item->is_action_with_text())
                left += scaled_icons_size * item->get_extra_size_ratio();
        }
    }
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbarItem::Disabled, Slic3r::GUI::GLToolbar::Layout::gap_size, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLToolbarItem::Hover, Slic3r::GUI::GLToolbarItem::HoverDisabled, Slic3r::GUI::GLToolbarItem::HoverPressed, Slic3r::GUI::GLToolbar::Layout::icons_size, Slic3r::GUI::GLToolbar::Layout::left, m_items, m_layout, Slic3r::GUI::GLToolbarItem::Normal, Slic3r::GUI::GLToolbarItem::Pressed, Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::GLToolbar::Layout::top.
Referenced by update_hover_state().
update_hover_state_vertical()
void Slic3r::GUI::GLToolbar::update_hover_state_vertical (const Vec2d & mouse_pos, GLCanvas3D & parent) private
{
    // NB: mouse_pos is already scaled appropriately
    float inv_zoom = (float)wxGetApp().plater()->get_camera().get_inv_zoom();
    float factor = m_layout.scale * inv_zoom;
    Size cnv_size = parent.get_canvas_size();
    Vec2d scaled_mouse_pos((mouse_pos(0) - 0.5 * (double)cnv_size.get_width()) * inv_zoom, (0.5 * (double)cnv_size.get_height() - mouse_pos(1)) * inv_zoom);
    float scaled_icons_size = m_layout.icons_size * factor;
    float scaled_separator_size = m_layout.separator_size * factor;
    float scaled_gap_size = m_layout.gap_size * factor;
    float scaled_border = m_layout.border * factor;
    float separator_stride = scaled_separator_size + scaled_gap_size;
    float icon_stride = scaled_icons_size + scaled_gap_size;
    float left = m_layout.left + scaled_border;
    float top = m_layout.top - scaled_border;
    for (GLToolbarItem* item : m_items)
    {
        if (!item->is_visible())
            continue;
        if (item->is_separator())
            top -= separator_stride;
        else
        {
            float right = left + scaled_icons_size;
            float bottom = top - scaled_icons_size;
            if (item->is_action_with_text_image())
                right += m_layout.text_size * factor;
            //BBS: GUI refactor: GLToolbar
            if (item->is_action_with_text())
                right += scaled_icons_size * item->get_extra_size_ratio();
            GLToolbarItem::EState state = item->get_state();
            bool inside = (left <= (float)scaled_mouse_pos(0)) && ((float)scaled_mouse_pos(0) <= right) && (bottom <= (float)scaled_mouse_pos(1)) && ((float)scaled_mouse_pos(1) <= top);
            switch (state)
            {
            case GLToolbarItem::Normal:
            {
                if (inside)
                {
                    item->set_state(GLToolbarItem::Hover);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::Hover:
            {
                if (!inside)
                {
                    item->set_state(GLToolbarItem::Normal);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::Pressed:
            {
                if (inside)
                {
                    item->set_state(GLToolbarItem::HoverPressed);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::HoverPressed:
            {
                if (!inside)
                {
                    item->set_state(GLToolbarItem::Pressed);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::Disabled:
            {
                if (inside)
                {
                    item->set_state(GLToolbarItem::HoverDisabled);
                    parent.set_as_dirty();
                }
                break;
            }
            case GLToolbarItem::HoverDisabled:
            {
                if (!inside)
                {
                    item->set_state(GLToolbarItem::Disabled);
                    parent.set_as_dirty();
                }
                break;
            }
            default:
            {
                break;
            }
            }
            top -= icon_stride;
        }
    }
}
References Slic3r::GUI::GLToolbar::Layout::border, Slic3r::GUI::GLToolbarItem::Disabled, Slic3r::GUI::GLToolbar::Layout::gap_size, Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLToolbarItem::Hover, Slic3r::GUI::GLToolbarItem::HoverDisabled, Slic3r::GUI::GLToolbarItem::HoverPressed, Slic3r::GUI::GLToolbar::Layout::icons_size, Slic3r::GUI::GLToolbar::Layout::left, m_items, m_layout, Slic3r::GUI::GLToolbarItem::Normal, Slic3r::GUI::GLToolbarItem::Pressed, Slic3r::GUI::GLToolbar::Layout::scale, Slic3r::GUI::GLToolbar::Layout::separator_size, Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::GLToolbar::Layout::text_size, and Slic3r::GUI::GLToolbar::Layout::top.
Referenced by update_hover_state().
update_items_enabled_state()
bool Slic3r::GUI::GLToolbar::update_items_enabled_state () private
{
    bool ret = false;
    for (int i = 0; i < (int)m_items.size(); ++i)
    {
        GLToolbarItem* item = m_items[i];
        ret |= item->update_enabled_state();
        if (item->is_enabled() && (m_pressed_toggable_id != -1) && (m_pressed_toggable_id != i))
        {
            ret = true;
            item->set_state(GLToolbarItem::Disabled);
        }
    }
    if (ret)
        m_layout.dirty = true;
    return ret;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, Slic3r::GUI::GLToolbarItem::Disabled, int, Slic3r::GUI::GLToolbarItem::is_enabled(), m_items, m_layout, m_pressed_toggable_id, Slic3r::GUI::GLToolbarItem::set_state(), and Slic3r::GUI::GLToolbarItem::update_enabled_state().
Referenced by update_items_state().
update_items_state()
bool Slic3r::GUI::GLToolbar::update_items_state ()
{
    bool ret = false;
    ret |= update_items_visibility();
    ret |= update_items_enabled_state();
    if (!is_any_item_pressed())
        m_pressed_toggable_id = -1;
    return ret;
}
References is_any_item_pressed(), m_pressed_toggable_id, update_items_enabled_state(), and update_items_visibility().
Referenced by Slic3r::GUI::GLCanvas3D::on_idle().
update_items_visibility()
bool Slic3r::GUI::GLToolbar::update_items_visibility () private
{
    bool ret = false;
    for (GLToolbarItem* item : m_items) {
        ret |= item->update_visibility();
    }
    if (ret)
        m_layout.dirty = true;
    // updates separators visibility to avoid having two of them consecutive
    bool any_item_visible = false;
    for (GLToolbarItem* item : m_items) {
        if (!item->is_separator())
            any_item_visible |= item->is_visible();
        else {
            item->set_visible(any_item_visible);
            any_item_visible = false;
        }
    }
    return ret;
}
References Slic3r::GUI::GLToolbar::Layout::dirty, m_items, and m_layout.
Referenced by update_items_state().
Member Data Documentation
Default_Icons_Size
const float Slic3r::GUI::GLToolbar::Default_Icons_Size = 40.0f static
Referenced by Slic3r::GUI::GLCanvas3D::_check_and_update_toolbar_icon_scale(), and Slic3r::GUI::GLCanvas3D::_render_overlays().
m_arrow_texture
BackgroundTexture Slic3r::GUI::GLToolbar::m_arrow_texture private
Referenced by init_arrow(), and render_arrow().
m_background_texture
BackgroundTexture Slic3r::GUI::GLToolbar::m_background_texture private
Referenced by init(), and render_background().
m_enabled
bool Slic3r::GUI::GLToolbar::m_enabled private
Referenced by contains_mouse(), get_item(), is_enabled(), on_mouse(), render(), set_enabled(), and update_hover_state().
m_icons_texture
GLTexture Slic3r::GUI::GLToolbar::m_icons_texture private
Referenced by generate_icons_texture(), render_horizontal(), and render_vertical().
m_icons_texture_dirty
bool Slic3r::GUI::GLToolbar::m_icons_texture_dirty private
Referenced by generate_icons_texture(), render(), set_icon_dirty(), set_icons_size(), and set_scale().
m_images_texture
GLTexture Slic3r::GUI::GLToolbar::m_images_texture mutable private
m_images_texture_dirty
bool Slic3r::GUI::GLToolbar::m_images_texture_dirty mutable private
m_items
ItemsList Slic3r::GUI::GLToolbar::m_items private
Referenced by ~GLToolbar(), add_item(), add_separator(), contains_mouse_horizontal(), contains_mouse_vertical(), del_all_item(), do_action(), generate_button_text_textures(), generate_icons_texture(), generate_image_textures(), get_additional_tooltip(), get_item(), get_item_id(), get_items_count(), get_main_size(), get_tooltip(), get_visible_items_cnt(), get_width_horizontal(), get_width_vertical(), is_any_item_pressed(), is_item_disabled(), is_item_pressed(), is_item_visible(), on_mouse(), render(), render_arrow(), render_horizontal(), render_vertical(), select_item(), set_additional_tooltip(), set_tooltip(), update_hover_state_horizontal(), update_hover_state_vertical(), update_items_enabled_state(), and update_items_visibility().
m_layout
Layout Slic3r::GUI::GLToolbar::m_layout private
Referenced by add_item(), add_separator(), calc_layout(), contains_mouse(), contains_mouse_horizontal(), contains_mouse_vertical(), del_all_item(), generate_icons_texture(), get_height(), get_height_horizontal(), get_horizontal_orientation(), get_icons_size(), get_layout_type(), get_main_size(), get_scaled_icon_size(), get_vertical_orientation(), get_width(), get_width_horizontal(), get_width_vertical(), render(), render_arrow(), render_background(), render_horizontal(), render_vertical(), set_border(), set_gap_size(), set_horizontal_orientation(), set_icons_size(), set_layout_type(), set_position(), set_scale(), set_separator_size(), set_text_size(), set_vertical_orientation(), update_hover_state(), update_hover_state_horizontal(), update_hover_state_vertical(), update_items_enabled_state(), and update_items_visibility().
m_mouse_capture
MouseCapture Slic3r::GUI::GLToolbar::m_mouse_capture private
Referenced by on_mouse().
m_name
std::string Slic3r::GUI::GLToolbar::m_name private
m_pressed_toggable_id
int Slic3r::GUI::GLToolbar::m_pressed_toggable_id private
Referenced by do_action(), on_mouse(), update_items_enabled_state(), and update_items_state().
m_type
EType Slic3r::GUI::GLToolbar::m_type private
Referenced by do_action(), and generate_icons_texture().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLToolbar.hpp
src/slic3r/GUI/GLToolbar.cpp