OrcaSlicer: Slic3r::Extruder Class Reference
Slic3r::Extruder Class Reference
#include <src/libslic3r/Extruder.hpp>
Public Member Functions
Extruder (unsigned int id, GCodeConfig *config, bool share_extruder)
virtual ~Extruder ()
void reset ()
unsigned int id () const
double extrude (double dE)
double retract (double length, double restart_extra)
double unretract ()
double E () const
void reset_E ()
double e_per_mm (double mm3_per_mm) const
double e_per_mm3 () const
double extruded_volume () const
double used_filament () const
double filament_diameter () const
double filament_crossection () const
double filament_density () const
double filament_cost () const
double filament_flow_ratio () const
double retract_before_wipe () const
double retraction_length () const
double retract_lift () const
int retract_speed () const
int deretract_speed () const
double retract_restart_extra () const
double retract_length_toolchange () const
double retract_restart_extra_toolchange () const
bool use_firmware_retraction () const
Private Member Functions
Extruder (unsigned int id)
Private Attributes
GCodeConfig * m_config
unsigned int m_id
double m_E
double m_absolute_E
double m_retracted
double m_restart_extra
double m_e_per_mm3
bool m_share_extruder
Static Private Attributes
static double m_share_E = 0.
static double m_share_retracted = 0.
Detailed Description
Constructor & Destructor Documentation
Extruder() [1/2]
Slic3r::Extruder::Extruder (unsigned int id, GCodeConfig * config, bool share_extruder)
                                                                            :
    m_id(id),
    m_config(config),
    m_share_extruder(m_share_extruder)
{
    reset();
    // cache values that are going to be called often
    m_e_per_mm3 = this->filament_flow_ratio();
    m_e_per_mm3 /= this->filament_crossection();
}
References filament_crossection(), filament_flow_ratio(), m_e_per_mm3, and reset().
~Extruder()
virtual Slic3r::Extruder::~Extruder () inline virtual
{}
Extruder() [2/2]
Slic3r::Extruder::Extruder (unsigned int id) inline private
: m_id(id) {}
Member Function Documentation
deretract_speed()
int Slic3r::Extruder::deretract_speed () const
{
    int speed = int(floor(m_config->deretraction_speed.get_at(m_id)+0.5));
    return (speed > 0) ? speed : this->retract_speed();
}
References floor(), int, m_config, m_id, and retract_speed().
Referenced by Slic3r::GCodeWriter::unretract().
E()
double Slic3r::Extruder::E () const inline
{ return m_share_extruder ? m_share_E : m_E; }
References m_E, m_share_E, and m_share_extruder.
Referenced by Slic3r::GCodeWriter::_retract(), Slic3r::GCodeWriter::extrude_arc_to_xy(), Slic3r::GCodeWriter::extrude_to_xy(), Slic3r::GCodeWriter::extrude_to_xyz(), Slic3r::GCodeWriter::reset_e(), and Slic3r::GCodeWriter::unretract().
e_per_mm()
double Slic3r::Extruder::e_per_mm (double mm3_per_mm) const inline
{ return mm3_per_mm * m_e_per_mm3; }
References m_e_per_mm3.
Referenced by Slic3r::Print::_make_skirt().
e_per_mm3()
double Slic3r::Extruder::e_per_mm3 () const inline
{ return m_e_per_mm3; }
References m_e_per_mm3.
extrude()
double Slic3r::Extruder::extrude (double dE)
{
    // BBS
    if (m_share_extruder) {
        if (m_config->use_relative_e_distances)
            m_share_E = 0.;
        m_share_E += dE;
        m_absolute_E += dE;
        if (dE < 0.)
            m_share_retracted -= dE;
    } else {
        // in case of relative E distances we always reset to 0 before any output
        if (m_config->use_relative_e_distances)
            m_E = 0.;
        m_E          += dE;
        m_absolute_E += dE;
        if (dE < 0.)
            m_retracted -= dE;
    }
    return dE;
}
References m_absolute_E, m_config, m_E, m_retracted, m_share_E, m_share_extruder, and m_share_retracted.
Referenced by Slic3r::GCodeWriter::extrude_arc_to_xy(), Slic3r::GCodeWriter::extrude_to_xy(), Slic3r::GCodeWriter::extrude_to_xyz(), and unretract().
extruded_volume()
double Slic3r::Extruder::extruded_volume () const
{
    // BBS
    if (m_share_extruder) {
        // FIXME: need to count m_retracted for share extruder machine
        return this->used_filament() * this->filament_crossection();
    } else {
        return this->used_filament() * this->filament_crossection();
    }
}
References filament_crossection(), m_share_extruder, and used_filament().
filament_cost()
double Slic3r::Extruder::filament_cost () const
{
    return m_config->filament_cost.get_at(m_id);
}
References m_config, and m_id.
filament_crossection()
double Slic3r::Extruder::filament_crossection () const inline
{ return this->filament_diameter() * this->filament_diameter() * 0.25 * PI; }
References filament_diameter(), and PI.
Referenced by Extruder(), and extruded_volume().
filament_density()
double Slic3r::Extruder::filament_density () const
{
    return m_config->filament_density.get_at(m_id);
}
References m_config, and m_id.
filament_diameter()
double Slic3r::Extruder::filament_diameter () const
{
    return m_config->filament_diameter.get_at(m_id);
}
References m_config, and m_id.
Referenced by filament_crossection().
filament_flow_ratio()
double Slic3r::Extruder::filament_flow_ratio () const
{
    return m_config->filament_flow_ratio.get_at(m_id);
}
References m_config, and m_id.
Referenced by Extruder().
id()
unsigned int Slic3r::Extruder::id () const inline
{ return m_id; }
References m_id.
Referenced by Slic3r::GCode::_do_export(), Slic3r::OozePrevention::_get_temp(), Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::GCodeWriter::lift(), Slic3r::GCodeWriter::need_toolchange(), Slic3r::need_wipe(), Slic3r::operator!=(), Slic3r::operator<(), Slic3r::operator==(), Slic3r::operator>(), Slic3r::OozePrevention::post_toolchange(), Slic3r::OozePrevention::pre_toolchange(), and Slic3r::Wipe::wipe().
reset()
void Slic3r::Extruder::reset () inline
                   {
        // BBS
        if (m_share_extruder) {
            m_share_E = 0.;
            m_share_retracted = 0.;
        } else {
            m_E             = 0;
            m_retracted     = 0;
            m_restart_extra = 0;
        }
        m_absolute_E    = 0;
    }
References m_absolute_E, m_E, m_restart_extra, m_retracted, m_share_E, m_share_extruder, and m_share_retracted.
Referenced by Extruder().
reset_E()
void Slic3r::Extruder::reset_E () inline
{ m_E = 0.; m_share_E = 0.; }
References m_E, and m_share_E.
Referenced by Slic3r::GCodeWriter::reset_e().
retract()
double Slic3r::Extruder::retract (double length, double restart_extra)
{
    // BBS
    if (m_share_extruder) {
        if (m_config->use_relative_e_distances)
            m_share_E = 0.;
        double to_retract = std::max(0., length - m_share_retracted);
        if (to_retract > 0.) {
            m_share_E             -= to_retract;
            m_absolute_E          -= to_retract;
            m_share_retracted     += to_retract;
            m_restart_extra = restart_extra;
        }
        return to_retract;
    } else {
        // in case of relative E distances we always reset to 0 before any output
        if (m_config->use_relative_e_distances)
            m_E = 0.;
        double to_retract = std::max(0., length - m_retracted);
        if (to_retract > 0.) {
            m_E             -= to_retract;
            m_absolute_E    -= to_retract;
            m_retracted     += to_retract;
            m_restart_extra = restart_extra;
        }
        return to_retract;
    }
}
References Slic3r::length(), m_absolute_E, m_config, m_E, m_restart_extra, m_retracted, m_share_E, m_share_extruder, and m_share_retracted.
Referenced by Slic3r::GCodeWriter::_retract().
retract_before_wipe()
double Slic3r::Extruder::retract_before_wipe () const
{
    return std::min(1., std::max(0., m_config->retract_before_wipe.get_at(m_id) * 0.01));
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::retract(), Slic3r::GCodeWriter::retract_for_toolchange(), and Slic3r::Wipe::wipe().
retract_length_toolchange()
double Slic3r::Extruder::retract_length_toolchange () const
{
    return m_config->retract_length_toolchange.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::GCodeWriter::retract_for_toolchange(), and Slic3r::Wipe::wipe().
retract_lift()
double Slic3r::Extruder::retract_lift () const
{
    return m_config->z_hop.get_at(m_id);
}
References m_config, and m_id.
retract_restart_extra()
double Slic3r::Extruder::retract_restart_extra () const
{
    return m_config->retract_restart_extra.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::retract().
retract_restart_extra_toolchange()
double Slic3r::Extruder::retract_restart_extra_toolchange () const
{
    return m_config->retract_restart_extra_toolchange.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::GCodeWriter::retract_for_toolchange().
retract_speed()
int Slic3r::Extruder::retract_speed () const
{
    return int(floor(m_config->retraction_speed.get_at(m_id)+0.5));
}
References floor(), int, m_config, and m_id.
Referenced by Slic3r::GCodeWriter::_retract(), and deretract_speed().
retraction_length()
double Slic3r::Extruder::retraction_length () const
{
    return m_config->retraction_length.get_at(m_id);
}
References m_config, and m_id.
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::GCodeWriter::retract(), and Slic3r::Wipe::wipe().
unretract()
double Slic3r::Extruder::unretract ()
{
    // BBS
    if (m_share_extruder) {
        double dE = m_share_retracted + m_restart_extra;
        this->extrude(dE);
        m_share_retracted     = 0.;
        m_restart_extra = 0.;
        return dE;
    } else {
        double dE = m_retracted + m_restart_extra;
        this->extrude(dE);
        m_retracted     = 0.;
        m_restart_extra = 0.;
        return dE;
    }
}
References extrude(), m_restart_extra, m_retracted, m_share_extruder, and m_share_retracted.
Referenced by Slic3r::GCodeWriter::unretract().
use_firmware_retraction()
bool Slic3r::Extruder::use_firmware_retraction () const
{
    return m_config->use_firmware_retraction;
}
References m_config.
used_filament()
double Slic3r::Extruder::used_filament () const
{
    // BBS
    if (m_share_extruder) {
        // FIXME: need to count retracted length for share-extruder machine
        return m_absolute_E;
    } else {
        return m_absolute_E + m_retracted;
    }
}
References m_absolute_E, m_retracted, and m_share_extruder.
Referenced by extruded_volume().
Member Data Documentation
m_absolute_E
double Slic3r::Extruder::m_absolute_E private
Referenced by extrude(), reset(), retract(), and used_filament().
m_config
GCodeConfig* Slic3r::Extruder::m_config private
Referenced by deretract_speed(), extrude(), filament_cost(), filament_density(), filament_diameter(), filament_flow_ratio(), retract(), retract_before_wipe(), retract_length_toolchange(), retract_lift(), retract_restart_extra(), retract_restart_extra_toolchange(), retract_speed(), retraction_length(), and use_firmware_retraction().
m_E
double Slic3r::Extruder::m_E private
Referenced by E(), extrude(), reset(), reset_E(), and retract().
m_e_per_mm3
double Slic3r::Extruder::m_e_per_mm3 private
Referenced by Extruder(), e_per_mm(), and e_per_mm3().
m_id
unsigned int Slic3r::Extruder::m_id private
Referenced by deretract_speed(), filament_cost(), filament_density(), filament_diameter(), filament_flow_ratio(), id(), retract_before_wipe(), retract_length_toolchange(), retract_lift(), retract_restart_extra(), retract_restart_extra_toolchange(), retract_speed(), and retraction_length().
m_restart_extra
double Slic3r::Extruder::m_restart_extra private
Referenced by reset(), retract(), and unretract().
m_retracted
double Slic3r::Extruder::m_retracted private
Referenced by extrude(), reset(), retract(), unretract(), and used_filament().
m_share_E
double Slic3r::Extruder::m_share_E = 0. static private
Referenced by E(), extrude(), reset(), reset_E(), and retract().
m_share_extruder
bool Slic3r::Extruder::m_share_extruder private
Referenced by E(), extrude(), extruded_volume(), reset(), retract(), unretract(), and used_filament().
m_share_retracted
double Slic3r::Extruder::m_share_retracted = 0. static private
Referenced by extrude(), reset(), retract(), and unretract().
The documentation for this class was generated from the following files:
src/libslic3r/Extruder.hpp
src/libslic3r/Extruder.cpp