OrcaSlicer: Slic3r::GUI::GLModel::InitializationData Struct Reference
Slic3r::GUI::GLModel::InitializationData Struct Reference
#include <src/slic3r/GUI/GLModel.hpp>
Classes
struct Entity
Public Member Functions
size_t vertices_count () const
size_t vertices_size_floats () const
size_t vertices_size_bytes () const
size_t indices_count () const
size_t indices_size_bytes () const
Public Attributes
std::vector< Entity > entities
Detailed Description
Class Documentation
Slic3r::GUI::GLModel::InitializationData::Entity
struct Slic3r::GUI::GLModel::InitializationData::Entity
Class Members
array< float, 4 > color { 1.0f, 1.0f, 1.0f, 1.0f }
vector< unsigned int > indices
vector< Vec3f > normals
vector< Vec3f > positions
PrimitiveType type
Member Function Documentation
indices_count()
size_t Slic3r::GUI::GLModel::InitializationData::indices_count () const
{
    size_t ret = 0;
    for (const Entity& entity : entities) {
        ret += entity.indices.size();
    }
    return ret;
}
Referenced by Slic3r::GUI::GCodeViewer::TBuffer::has_data(), and indices_size_bytes().
indices_size_bytes()
size_t Slic3r::GUI::GLModel::InitializationData::indices_size_bytes () const inline
{ return indices_count() * sizeof(unsigned int); }
References indices_count(), and int.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
vertices_count()
size_t Slic3r::GUI::GLModel::InitializationData::vertices_count () const
{
    size_t ret = 0;
    for (const Entity& entity : entities) {
        ret += entity.positions.size();
    }
    return ret;
}
References entities.
Referenced by Slic3r::GUI::GCodeViewer::TBuffer::has_data(), Slic3r::GUI::GCodeViewer::load_toolpaths(), and vertices_size_floats().
vertices_size_bytes()
size_t Slic3r::GUI::GLModel::InitializationData::vertices_size_bytes () const inline
{ return vertices_size_floats() * sizeof(float); }
References vertices_size_floats().
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
vertices_size_floats()
size_t Slic3r::GUI::GLModel::InitializationData::vertices_size_floats () const inline
{ return vertices_count() * 6; }
References vertices_count().
Referenced by vertices_size_bytes().
Member Data Documentation
entities
std::vector<Entity> Slic3r::GUI::GLModel::InitializationData::entities
Referenced by Slic3r::GUI::circular_arrow(), Slic3r::GUI::diamond(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_polygons(), Slic3r::GUI::stilized_arrow(), Slic3r::GUI::straight_arrow(), Slic3r::GLVolume::SinkingContours::update(), and vertices_count().
The documentation for this struct was generated from the following files:
src/slic3r/GUI/GLModel.hpp
src/slic3r/GUI/GLModel.cpp