OrcaSlicer: Slic3r::GUI::UpgradePanel Class Reference
Slic3r::GUI::UpgradePanel Class Reference
#include <src/slic3r/GUI/UpgradePanel.hpp>
Public Member Functions
UpgradePanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~UpgradePanel ()
void clean_push_upgrade_panel ()
void msw_rescale ()
bool Show (bool show=true) override
void refresh_version_and_firmware (MachineObject *obj)
void update (MachineObject *obj)
void show_status (int status)
void on_sys_color_changed ()
Public Attributes
MachineObject * m_obj { nullptr }
Protected Attributes
wxScrolledWindow * m_scrolledWindow
wxBoxSizer * m_machine_list_sizer
MachineInfoPanel * m_push_upgrade_panel {nullptr}
bool enable_select_firmware = false
bool m_need_update = false
int last_forced_hint_status = -1
int last_consistency_hint_status = -1
int last_status
bool m_show_forced_hint = true
bool m_show_consistency_hint = true
SecondaryCheckDialog * force_dlg { nullptr }
SecondaryCheckDialog * consistency_dlg { nullptr }
Detailed Description
Constructor & Destructor Documentation
UpgradePanel()
Slic3r::GUI::UpgradePanel::UpgradePanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
    :wxPanel(parent, id, pos, size, style)
{
    this->SetBackgroundColour(wxColour(238, 238, 238));
    auto m_main_sizer = new wxBoxSizer(wxVERTICAL);
    m_scrolledWindow = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxVSCROLL);
    m_scrolledWindow->SetScrollRate(5, 5);
    m_machine_list_sizer = new wxBoxSizer(wxVERTICAL);
    m_scrolledWindow->SetSizerAndFit(m_machine_list_sizer);
    m_main_sizer->Add(m_scrolledWindow, 1, wxEXPAND, 0);
    this->SetSizerAndFit(m_main_sizer);
    Layout();
}
References m_machine_list_sizer, and m_scrolledWindow.
~UpgradePanel()
Slic3r::GUI::UpgradePanel::~UpgradePanel ()
{
    if (force_dlg != nullptr)
        delete force_dlg ;
    if (consistency_dlg != nullptr)
        delete consistency_dlg ;
}
References consistency_dlg, and force_dlg.
Member Function Documentation
clean_push_upgrade_panel()
void Slic3r::GUI::UpgradePanel::clean_push_upgrade_panel ()
{
    if (m_push_upgrade_panel) {
        delete m_push_upgrade_panel;
        m_push_upgrade_panel = nullptr;
    }
}
References m_push_upgrade_panel.
Referenced by update().
msw_rescale()
void Slic3r::GUI::UpgradePanel::msw_rescale ()
{
    if (m_push_upgrade_panel)
        m_push_upgrade_panel->msw_rescale();
}
References m_push_upgrade_panel, and Slic3r::GUI::MachineInfoPanel::msw_rescale().
Referenced by Slic3r::GUI::MonitorPanel::msw_rescale().
on_sys_color_changed()
void Slic3r::GUI::UpgradePanel::on_sys_color_changed ()
{
    //add some protection for Dark mode
    if (m_push_upgrade_panel) {
        m_push_upgrade_panel->on_sys_color_changed();
    }
}
References m_push_upgrade_panel, and Slic3r::GUI::MachineInfoPanel::on_sys_color_changed().
Referenced by Slic3r::GUI::MonitorPanel::on_sys_color_changed().
refresh_version_and_firmware()
void Slic3r::GUI::UpgradePanel::refresh_version_and_firmware (MachineObject * obj)
{
    BOOST_LOG_TRIVIAL(trace) << "refresh version";
    if (obj) {
        obj->command_get_version();
        obj->get_firmware_info();
        m_need_update = true;
    }
}
References Slic3r::MachineObject::command_get_version(), Slic3r::MachineObject::get_firmware_info(), m_need_update, and Slic3r::trace().
Referenced by Show(), and update().
Show()
bool Slic3r::GUI::UpgradePanel::Show (bool show = true) override
{
    if (show) {
        DeviceManager* dev = wxGetApp().getDeviceManager();
        if (dev) {
            MachineObject* obj = dev->get_default_machine();
            refresh_version_and_firmware(obj);
        }
    }
    return wxPanel::Show(show);
}
References Slic3r::DeviceManager::get_default_machine(), and refresh_version_and_firmware().
show_status()
void Slic3r::GUI::UpgradePanel::show_status (int status)
{
    if (last_status == status) return;
    last_status = status;
    if (((status & (int)MonitorStatus::MONITOR_DISCONNECTED) != 0)
        || ((status & (int)MonitorStatus::MONITOR_DISCONNECTED_SERVER) != 0)
        || ((status & (int)MonitorStatus::MONITOR_CONNECTING) != 0)
        || ((status & (int)MonitorStatus::MONITOR_NO_PRINTER) != 0)
        ) {
        ;
    }
    else if ((status & (int)MonitorStatus::MONITOR_NORMAL) != 0) {
        ;
    }
}
References last_status, Slic3r::GUI::MONITOR_CONNECTING, Slic3r::GUI::MONITOR_DISCONNECTED, Slic3r::GUI::MONITOR_DISCONNECTED_SERVER, Slic3r::GUI::MONITOR_NO_PRINTER, and Slic3r::GUI::MONITOR_NORMAL.
Referenced by Slic3r::GUI::MonitorPanel::show_status().
update()
void Slic3r::GUI::UpgradePanel::update (MachineObject * obj)
{
    if (m_obj != obj) {
        m_obj = obj;
        refresh_version_and_firmware(obj);
    }
    Freeze();
    if (m_obj && m_need_update) {
        if (m_obj->is_firmware_info_valid()) {
            clean_push_upgrade_panel();
            m_push_upgrade_panel = new MachineInfoPanel(m_scrolledWindow);
            m_machine_list_sizer->Add(m_push_upgrade_panel, 0, wxTOP | wxALIGN_CENTER_HORIZONTAL, FromDIP(8));
            m_need_update = false;
        }
    }
    //force upgrade
    //unlock hint
    if (m_obj && (m_obj->upgrade_display_state == (int) MachineObject::UpgradingDisplayState::UpgradingFinished) && (last_forced_hint_status != m_obj->upgrade_display_state)) {
        last_forced_hint_status = m_obj->upgrade_display_state;
        m_show_forced_hint = true;
    }
    if (m_obj && m_show_forced_hint) {
        if (m_obj->upgrade_force_upgrade) {
            m_show_forced_hint = false;   //lock hint
            if (force_dlg == nullptr) {
                force_dlg = new SecondaryCheckDialog(this->GetParent(), wxID_ANY, _L("Update firmware"), SecondaryCheckDialog::ButtonStyle::CONFIRM_AND_CANCEL, wxDefaultPosition, wxDefaultSize);
                force_dlg->Bind(EVT_SECONDARY_CHECK_CONFIRM, [this](wxCommandEvent& e) {
                    if (m_obj) {
                        m_obj->command_upgrade_confirm();
                        m_obj->upgrade_display_state = MachineObject::UpgradingDisplayState::UpgradingInProgress;
                        m_obj->upgrade_display_hold_count = HOLD_COUNT_MAX;
                    }
                });
            }
            force_dlg->update_text(_L(
                 "An important update was detected and needs to be run before printing can continue. Do you want to update now? You can also update later from 'Upgrade firmware'."
            ));
            force_dlg->on_show();
        }
    }
    //consistency upgrade
    if (m_obj && (m_obj->upgrade_display_state == (int) MachineObject::UpgradingDisplayState::UpgradingFinished) && (last_consistency_hint_status != m_obj->upgrade_display_state)) {
        last_consistency_hint_status = m_obj->upgrade_display_state;
        m_show_consistency_hint = true;
    }
    if (m_obj && m_show_consistency_hint) {
        if (m_obj->upgrade_consistency_request) {
            m_show_consistency_hint = false;
            if (consistency_dlg == nullptr) {
                consistency_dlg = new SecondaryCheckDialog(this->GetParent(), wxID_ANY, _L("Update firmware"), SecondaryCheckDialog::ButtonStyle::CONFIRM_AND_CANCEL, wxDefaultPosition, wxDefaultSize);
                consistency_dlg->Bind(EVT_SECONDARY_CHECK_CONFIRM, [this](wxCommandEvent& e) {
                    if (m_obj) {
                        m_obj->command_consistency_upgrade_confirm();
                    }
                });
            }
            consistency_dlg->update_text(_L(
                 "The firmware version is abnormal. Repairing and updating are required before printing. Do you want to update now? You can also update later on printer or update next time starting the studio."
            ));
            consistency_dlg->on_show();
      }
    }
    //update panels
    if (m_push_upgrade_panel) {
        m_push_upgrade_panel->update(obj);
    }
    if (!obj)
        clean_push_upgrade_panel();
    this->Layout();
    Thaw();
    m_obj = obj;
}
References _L, clean_push_upgrade_panel(), Slic3r::MachineObject::command_consistency_upgrade_confirm(), Slic3r::MachineObject::command_upgrade_confirm(), Slic3r::GUI::SecondaryCheckDialog::CONFIRM_AND_CANCEL, consistency_dlg, force_dlg, HOLD_COUNT_MAX, Slic3r::MachineObject::is_firmware_info_valid(), last_consistency_hint_status, last_forced_hint_status, m_machine_list_sizer, m_need_update, m_obj, m_push_upgrade_panel, m_scrolledWindow, m_show_consistency_hint, m_show_forced_hint, Slic3r::GUI::SecondaryCheckDialog::on_show(), refresh_version_and_firmware(), Slic3r::GUI::MachineInfoPanel::update(), Slic3r::GUI::SecondaryCheckDialog::update_text(), Slic3r::MachineObject::upgrade_consistency_request, Slic3r::MachineObject::upgrade_display_hold_count, Slic3r::MachineObject::upgrade_display_state, Slic3r::MachineObject::upgrade_force_upgrade, Slic3r::MachineObject::UpgradingFinished, and Slic3r::MachineObject::UpgradingInProgress.
Referenced by Slic3r::GUI::MonitorPanel::show_status(), and Slic3r::GUI::MonitorPanel::update_all().
Member Data Documentation
consistency_dlg
SecondaryCheckDialog* Slic3r::GUI::UpgradePanel::consistency_dlg { nullptr } protected
Referenced by ~UpgradePanel(), and update().
enable_select_firmware
bool Slic3r::GUI::UpgradePanel::enable_select_firmware = false protected
force_dlg
SecondaryCheckDialog* Slic3r::GUI::UpgradePanel::force_dlg { nullptr } protected
Referenced by ~UpgradePanel(), and update().
last_consistency_hint_status
int Slic3r::GUI::UpgradePanel::last_consistency_hint_status = -1 protected
Referenced by update().
last_forced_hint_status
int Slic3r::GUI::UpgradePanel::last_forced_hint_status = -1 protected
Referenced by update().
last_status
int Slic3r::GUI::UpgradePanel::last_status protected
Referenced by show_status().
m_machine_list_sizer
wxBoxSizer* Slic3r::GUI::UpgradePanel::m_machine_list_sizer protected
Referenced by UpgradePanel(), and update().
m_need_update
bool Slic3r::GUI::UpgradePanel::m_need_update = false protected
Referenced by refresh_version_and_firmware(), and update().
m_obj
MachineObject* Slic3r::GUI::UpgradePanel::m_obj { nullptr }
Referenced by update().
m_push_upgrade_panel
MachineInfoPanel* Slic3r::GUI::UpgradePanel::m_push_upgrade_panel {nullptr} protected
Referenced by clean_push_upgrade_panel(), msw_rescale(), on_sys_color_changed(), and update().
m_scrolledWindow
wxScrolledWindow* Slic3r::GUI::UpgradePanel::m_scrolledWindow protected
Referenced by UpgradePanel(), and update().
m_show_consistency_hint
bool Slic3r::GUI::UpgradePanel::m_show_consistency_hint = true protected
Referenced by update().
m_show_forced_hint
bool Slic3r::GUI::UpgradePanel::m_show_forced_hint = true protected
Referenced by update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UpgradePanel.hpp
src/slic3r/GUI/UpgradePanel.cpp