OrcaSlicer: Slic3r::ThumbnailData Struct Reference
Slic3r::ThumbnailData Struct Reference
#include <src/libslic3r/GCode/ThumbnailData.hpp>
Public Member Functions
ThumbnailData ()
void set (unsigned int w, unsigned int h)
void reset ()
bool is_valid () const
void load_from (ThumbnailData &data)
Public Attributes
unsigned int width
unsigned int height
std::vector< unsigned char > pixels
Detailed Description
Constructor & Destructor Documentation
ThumbnailData()
Slic3r::ThumbnailData::ThumbnailData () inline
{ reset(); }
References reset().
Member Function Documentation
is_valid()
bool Slic3r::ThumbnailData::is_valid () const
{
    return (width != 0) && (height != 0) && ((unsigned int)pixels.size() == 4 * width * height);
}
References height, pixels, and width.
Referenced by Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::GUI::GCodeViewer::_render_calibration_thumbnail_framebuffer(), Slic3r::_3MF_Exporter::_save_model_to_file(), Slic3r::GUI::GLCanvas3D::_update_imgui_select_plate_toolbar(), Slic3r::GUI::Plater::export_3mf(), Slic3r::GUI::GLCanvas3D::render_thumbnail_framebuffer(), Slic3r::GUI::GLCanvas3D::render_thumbnail_framebuffer_ext(), Slic3r::GUI::GLCanvas3D::render_thumbnail_legacy(), Slic3r::CLI::run(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::SendToPrinterDialog::set_default(), and Slic3r::GUI::Plater::update_all_plate_thumbnails().
load_from()
void Slic3r::ThumbnailData::load_from (ThumbnailData & data) inline
{
        this->set(data.width, data.height);
        pixels = data.pixels;
    }
References height, pixels, set(), and width.
Referenced by Slic3r::GUI::PartPlateList::store_to_3mf_structure().
reset()
void Slic3r::ThumbnailData::reset ()
{
    width = 0;
    height = 0;
    pixels.clear();
}
References height, pixels, and width.
Referenced by ThumbnailData(), Slic3r::GUI::Plater::invalid_all_plate_thumbnails(), Slic3r::GUI::PartPlateList::notify_instance_removed(), Slic3r::GUI::PartPlateList::notify_instance_update(), and Slic3r::CLI::run().
set()
void Slic3r::ThumbnailData::set (unsigned int w, unsigned int h)
{
    if ((w == 0) || (h == 0))
        return;
    if ((width != w) || (height != h))
    {
        width = w;
        height = h;
        // defaults to white texture
        pixels.clear();
        pixels = std::vector<unsigned char>(width * height * 4, 255);
    }
}
References height, pixels, and width.
Referenced by Slic3r::GUI::GCodeViewer::_render_calibration_thumbnail_framebuffer(), load_from(), Slic3r::GUI::PartPlate::load_thumbnail_data(), Slic3r::GUI::GLCanvas3D::render_thumbnail_framebuffer(), Slic3r::GUI::GLCanvas3D::render_thumbnail_framebuffer_ext(), and Slic3r::GUI::GLCanvas3D::render_thumbnail_legacy().
Member Data Documentation
height
unsigned int Slic3r::ThumbnailData::height
Referenced by Slic3r::_3MF_Exporter::_add_thumbnail_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_thumbnail_file_to_archive(), Slic3r::GUI::GCodeViewer::_render_calibration_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::_update_imgui_select_plate_toolbar(), Slic3r::GUI::get_data_from_svg(), Slic3r::GUI::IMReturnToolbar::init(), is_valid(), load_from(), Slic3r::GUI::GLCanvas3D::render_thumbnail_internal(), reset(), Slic3r::CLI::run(), set(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::SendToPrinterDialog::set_default(), Slic3r::GUI::PartPlateList::store_to_3mf_structure(), and Slic3r::write_thumbnail().
pixels
std::vector<unsigned char> Slic3r::ThumbnailData::pixels
Referenced by Slic3r::_3MF_Exporter::_add_thumbnail_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_thumbnail_file_to_archive(), Slic3r::GUI::GCodeViewer::_render_calibration_thumbnail_framebuffer(), Slic3r::GUI::GLCanvas3D::_update_imgui_select_plate_toolbar(), Slic3r::GUI::get_data_from_svg(), Slic3r::GUI::IMReturnToolbar::init(), is_valid(), load_from(), Slic3r::GUI::PartPlate::load_thumbnail_data(), Slic3r::GUI::GLCanvas3D::render_thumbnail_framebuffer(), Slic3r::GUI::GLCanvas3D::render_thumbnail_framebuffer_ext(), Slic3r::GUI::GLCanvas3D::render_thumbnail_legacy(), reset(), set(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::SendToPrinterDialog::set_default(), Slic3r::GUI::PartPlateList::store_to_3mf_structure(), and Slic3r::write_thumbnail().
width
unsigned int Slic3r::ThumbnailData::width
Referenced by Slic3r::_3MF_Exporter::_add_thumbnail_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_thumbnail_file_to_archive(), Slic3r::GUI::GCodeViewer::_render_calibration_thumbnail_internal(), Slic3r::GUI::GLCanvas3D::_update_imgui_select_plate_toolbar(), Slic3r::GUI::get_data_from_svg(), Slic3r::GUI::IMReturnToolbar::init(), is_valid(), load_from(), Slic3r::GUI::GLCanvas3D::render_thumbnail_internal(), reset(), Slic3r::CLI::run(), set(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::SendToPrinterDialog::set_default(), Slic3r::GUI::PartPlateList::store_to_3mf_structure(), and Slic3r::write_thumbnail().
The documentation for this struct was generated from the following files:
src/libslic3r/GCode/ThumbnailData.hpp
src/libslic3r/GCode/ThumbnailData.cpp