OrcaSlicer: src/expat/xmltok.c File Reference
xmltok.c File Reference
#include <stddef.h>
#include "expat_config.h"
#include "expat_external.h"
#include "internal.h"
#include "xmltok.h"
#include "nametab.h"
#include "xmltok_impl.h"
#include "ascii.h"
#include "xmltok_impl.inc"
#include "asciitab.h"
#include "utf8tab.h"
#include "iasciitab.h"
#include "latin1tab.h"
#include "xmltok_ns.inc"
Classes
struct normal_encoding
struct unknown_encoding
Macros
#define IGNORE_SECTION_TOK_VTABLE , PREFIX(ignoreSectionTok)
#define VTABLE1
#define VTABLE VTABLE1, PREFIX(toUtf8), PREFIX(toUtf16)
#define UCS2_GET_NAMING(pages, hi, lo) (namingBitmap[(pages[hi] << 3) + ((lo) >> 5)] & (1u << ((lo) & 0x1F)))
#define UTF8_GET_NAMING2(pages, byte)
#define UTF8_GET_NAMING3(pages, byte)
#define UTF8_GET_NAMING(pages, p, n)
#define UTF8_INVALID2(p) ((*p) < 0xC2 || ((p)[1] & 0x80) == 0 || ((p)[1] & 0xC0) == 0xC0)
#define UTF8_INVALID3(p)
#define UTF8_INVALID4(p)
#define utf8_isName4 isNever
#define utf8_isNmstrt4 isNever
#define AS_NORMAL_ENCODING(enc) ((const struct normal_encoding *) (enc))
#define STANDARD_VTABLE(E) /* as nothing */
#define NORMAL_VTABLE(E)
#define NULL_VTABLE
#define MINBPC(enc) 1
#define SB_BYTE_TYPE(enc, p) (((struct normal_encoding *)(enc))->type[(unsigned char)*(p)])
#define BYTE_TYPE(enc, p) SB_BYTE_TYPE(enc, p)
#define BYTE_TO_ASCII(enc, p) (*(p))
#define IS_NAME_CHAR(enc, p, n) (AS_NORMAL_ENCODING(enc)->isName ## n(enc, p))
#define IS_NMSTRT_CHAR(enc, p, n) (AS_NORMAL_ENCODING(enc)->isNmstrt ## n(enc, p))
#define IS_INVALID_CHAR(enc, p, n) (AS_NORMAL_ENCODING(enc)->isInvalid ## n(enc, p))
#define IS_NAME_CHAR_MINBPC(enc, p) (0)
#define IS_NMSTRT_CHAR_MINBPC(enc, p) (0)
#define CHAR_MATCHES(enc, p, c) (*(p) == c)
#define PREFIX(ident) normal_ ## ident
#define XML_TOK_IMPL_C
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define DEFINE_UTF16_TO_UTF8(E)
#define DEFINE_UTF16_TO_UTF16(E)
#define SET2(ptr, ch) (((ptr)[0] = ((ch) & 0xff)), ((ptr)[1] = ((ch) >> 8)))
#define GET_LO(ptr) ((unsigned char)(ptr)[0])
#define GET_HI(ptr) ((unsigned char)(ptr)[1])
#define SET2(ptr, ch) (((ptr)[0] = ((ch) >> 8)), ((ptr)[1] = ((ch) & 0xFF)))
#define GET_LO(ptr) ((unsigned char)(ptr)[1])
#define GET_HI(ptr) ((unsigned char)(ptr)[0])
#define LITTLE2_BYTE_TYPE(enc, p)
#define LITTLE2_BYTE_TO_ASCII(enc, p) ((p)[1] == 0 ? (p)[0] : -1)
#define LITTLE2_CHAR_MATCHES(enc, p, c) ((p)[1] == 0 && (p)[0] == c)
#define LITTLE2_IS_NAME_CHAR_MINBPC(enc, p) UCS2_GET_NAMING(namePages, (unsigned char)p[1], (unsigned char)p[0])
#define LITTLE2_IS_NMSTRT_CHAR_MINBPC(enc, p) UCS2_GET_NAMING(nmstrtPages, (unsigned char)p[1], (unsigned char)p[0])
#define PREFIX(ident) little2_ ## ident
#define MINBPC(enc) 2
#define BYTE_TYPE(enc, p) LITTLE2_BYTE_TYPE(enc, p)
#define BYTE_TO_ASCII(enc, p) LITTLE2_BYTE_TO_ASCII(enc, p)
#define CHAR_MATCHES(enc, p, c) LITTLE2_CHAR_MATCHES(enc, p, c)
#define IS_NAME_CHAR(enc, p, n) 0
#define IS_NAME_CHAR_MINBPC(enc, p) LITTLE2_IS_NAME_CHAR_MINBPC(enc, p)
#define IS_NMSTRT_CHAR(enc, p, n) (0)
#define IS_NMSTRT_CHAR_MINBPC(enc, p) LITTLE2_IS_NMSTRT_CHAR_MINBPC(enc, p)
#define XML_TOK_IMPL_C
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define BIG2_BYTE_TYPE(enc, p)
#define BIG2_BYTE_TO_ASCII(enc, p) ((p)[0] == 0 ? (p)[1] : -1)
#define BIG2_CHAR_MATCHES(enc, p, c) ((p)[0] == 0 && (p)[1] == c)
#define BIG2_IS_NAME_CHAR_MINBPC(enc, p) UCS2_GET_NAMING(namePages, (unsigned char)p[0], (unsigned char)p[1])
#define BIG2_IS_NMSTRT_CHAR_MINBPC(enc, p) UCS2_GET_NAMING(nmstrtPages, (unsigned char)p[0], (unsigned char)p[1])
#define PREFIX(ident) big2_ ## ident
#define MINBPC(enc) 2
#define BYTE_TYPE(enc, p) BIG2_BYTE_TYPE(enc, p)
#define BYTE_TO_ASCII(enc, p) BIG2_BYTE_TO_ASCII(enc, p)
#define CHAR_MATCHES(enc, p, c) BIG2_CHAR_MATCHES(enc, p, c)
#define IS_NAME_CHAR(enc, p, n) 0
#define IS_NAME_CHAR_MINBPC(enc, p) BIG2_IS_NAME_CHAR_MINBPC(enc, p)
#define IS_NMSTRT_CHAR(enc, p, n) (0)
#define IS_NMSTRT_CHAR_MINBPC(enc, p) BIG2_IS_NMSTRT_CHAR_MINBPC(enc, p)
#define XML_TOK_IMPL_C
#define BT_COLON BT_NMSTRT
#define BT_COLON BT_NMSTRT
#define AS_UNKNOWN_ENCODING(enc) ((const struct unknown_encoding *) (enc))
#define INIT_ENC_INDEX(enc) ((int)(enc)->initEnc.isUtf16)
#define SET_INIT_ENC_INDEX(enc, i) ((enc)->initEnc.isUtf16 = (char)i)
#define NS(x) x
#define ns(x) x
#define XML_TOK_NS_C
#define NS(x) x ## NS
#define ns(x) x ## _ns
#define XML_TOK_NS_C
Enumerations
enum { UTF8_cval1 = 0x00 , UTF8_cval2 = 0xc0 , UTF8_cval3 = 0xe0 , UTF8_cval4 = 0xf0 }
enum {
UNKNOWN_ENC = -1 , ISO_8859_1_ENC = 0 , US_ASCII_ENC , UTF_8_ENC ,
UTF_16_ENC , UTF_16BE_ENC , UTF_16LE_ENC , NO_ENC
}
Functions
static int PTRFASTCALL isNever (const ENCODING *UNUSED_P(enc), const char *UNUSED_P(p))
static int PTRFASTCALL utf8_isName2 (const ENCODING *UNUSED_P(enc), const char *p)
static int PTRFASTCALL utf8_isName3 (const ENCODING *UNUSED_P(enc), const char *p)
static int PTRFASTCALL utf8_isNmstrt2 (const ENCODING *UNUSED_P(enc), const char *p)
static int PTRFASTCALL utf8_isNmstrt3 (const ENCODING *UNUSED_P(enc), const char *p)
static int PTRFASTCALL utf8_isInvalid2 (const ENCODING *UNUSED_P(enc), const char *p)
static int PTRFASTCALL utf8_isInvalid3 (const ENCODING *UNUSED_P(enc), const char *p)
static int PTRFASTCALL utf8_isInvalid4 (const ENCODING *UNUSED_P(enc), const char *p)
static int FASTCALL checkCharRefNumber (int)
void align_limit_to_full_utf8_characters (const char *from, const char **fromLimRef)
static enum XML_Convert_Result PTRCALL utf8_toUtf8 (const ENCODING *UNUSED_P(enc), const char **fromP, const char *fromLim, char **toP, const char *toLim)
static enum XML_Convert_Result PTRCALL utf8_toUtf16 (const ENCODING *enc, const char **fromP, const char *fromLim, unsigned short **toP, const unsigned short *toLim)
static enum XML_Convert_Result PTRCALL latin1_toUtf8 (const ENCODING *UNUSED_P(enc), const char **fromP, const char *fromLim, char **toP, const char *toLim)
static enum XML_Convert_Result PTRCALL latin1_toUtf16 (const ENCODING *UNUSED_P(enc), const char **fromP, const char *fromLim, unsigned short **toP, const unsigned short *toLim)
static enum XML_Convert_Result PTRCALL ascii_toUtf8 (const ENCODING *UNUSED_P(enc), const char **fromP, const char *fromLim, char **toP, const char *toLim)
static int PTRFASTCALL unicode_byte_type (char hi, char lo)
static int FASTCALL streqci (const char *s1, const char *s2)
static void PTRCALL initUpdatePosition (const ENCODING *UNUSED_P(enc), const char *ptr, const char *end, POSITION *pos)
static int toAscii (const ENCODING *enc, const char *ptr, const char *end)
static int FASTCALL isSpace (int c)
static int parsePseudoAttribute (const ENCODING *enc, const char *ptr, const char *end, const char **namePtr, const char **nameEndPtr, const char **valPtr, const char **nextTokPtr)
static int doParseXmlDecl (const ENCODING *(*encodingFinder)(const ENCODING *, const char *, const char *), int isGeneralTextEntity, const ENCODING *enc, const char *ptr, const char *end, const char **badPtr, const char **versionPtr, const char **versionEndPtr, const char **encodingName, const ENCODING **encoding, int *standalone)
int FASTCALL XmlUtf8Encode (int c, char *buf)
int FASTCALL XmlUtf16Encode (int charNum, unsigned short *buf)
int XmlSizeOfUnknownEncoding (void)
static int PTRFASTCALL unknown_isName (const ENCODING *enc, const char *p)
static int PTRFASTCALL unknown_isNmstrt (const ENCODING *enc, const char *p)
static int PTRFASTCALL unknown_isInvalid (const ENCODING *enc, const char *p)
static enum XML_Convert_Result PTRCALL unknown_toUtf8 (const ENCODING *enc, const char **fromP, const char *fromLim, char **toP, const char *toLim)
static enum XML_Convert_Result PTRCALL unknown_toUtf16 (const ENCODING *enc, const char **fromP, const char *fromLim, unsigned short **toP, const unsigned short *toLim)
ENCODING * XmlInitUnknownEncoding (void *mem, int *table, CONVERTER convert, void *userData)
static int FASTCALL getEncodingIndex (const char *name)
static int initScan (const ENCODING *const *encodingTable, const INIT_ENCODING *enc, int state, const char *ptr, const char *end, const char **nextTokPtr)
ENCODING * XmlInitUnknownEncodingNS (void *mem, int *table, CONVERTER convert, void *userData)
Variables
static const struct normal_encoding utf8_encoding_ns
static const struct normal_encoding utf8_encoding
static const struct normal_encoding internal_utf8_encoding_ns
static const struct normal_encoding internal_utf8_encoding
static const struct normal_encoding latin1_encoding_ns
static const struct normal_encoding latin1_encoding
static const struct normal_encoding ascii_encoding_ns
static const struct normal_encoding ascii_encoding
static const struct normal_encoding little2_encoding_ns
static const struct normal_encoding little2_encoding
static const struct normal_encoding internal_little2_encoding_ns
static const struct normal_encoding internal_little2_encoding
static const struct normal_encoding big2_encoding_ns
static const struct normal_encoding big2_encoding
static const struct normal_encoding internal_big2_encoding_ns
static const struct normal_encoding internal_big2_encoding
static const char KW_version []
static const char KW_encoding []
static const char KW_standalone []
static const char KW_yes []
static const char KW_no []
static const char KW_ISO_8859_1 []
static const char KW_US_ASCII []
static const char KW_UTF_8 []
static const char KW_UTF_16 []
static const char KW_UTF_16BE []
static const char KW_UTF_16LE []
Class Documentation
unknown_encoding
struct unknown_encoding
Class Members
CONVERTER convert
struct normal_encoding normal
void * userData
unsigned short utf16[256]
char utf8[256][4]
Macro Definition Documentation
AS_NORMAL_ENCODING
#define AS_NORMAL_ENCODING (enc) ((const struct normal_encoding *) (enc))
AS_UNKNOWN_ENCODING
#define AS_UNKNOWN_ENCODING (enc) ((const struct unknown_encoding *) (enc))
BIG2_BYTE_TO_ASCII
#define BIG2_BYTE_TO_ASCII (enc, p) ((p)[0] == 0 ? (p)[1] : -1)
BIG2_BYTE_TYPE
#define BIG2_BYTE_TYPE (enc, p)
Value:
 ((p)[0] == 0 \
  ? ((struct normal_encoding *)(enc))->type[(unsigned char)(p)[1]] \
  : unicode_byte_type((p)[0], (p)[1]))
BIG2_CHAR_MATCHES
#define BIG2_CHAR_MATCHES (enc, p, c) ((p)[0] == 0 && (p)[1] == c)
BIG2_IS_NAME_CHAR_MINBPC
#define BIG2_IS_NAME_CHAR_MINBPC (enc, p) UCS2_GET_NAMING(namePages, (unsigned char)p[0], (unsigned char)p[1])
BIG2_IS_NMSTRT_CHAR_MINBPC
#define BIG2_IS_NMSTRT_CHAR_MINBPC (enc, p) UCS2_GET_NAMING(nmstrtPages, (unsigned char)p[0], (unsigned char)p[1])
BT_COLON [1/8]
#define BT_COLON BT_NMSTRT
BT_COLON [2/8]
#define BT_COLON BT_NMSTRT
BT_COLON [3/8]
#define BT_COLON BT_NMSTRT
BT_COLON [4/8]
#define BT_COLON BT_NMSTRT
BT_COLON [5/8]
#define BT_COLON BT_NMSTRT
BT_COLON [6/8]
#define BT_COLON BT_NMSTRT
BT_COLON [7/8]
#define BT_COLON BT_NMSTRT
BT_COLON [8/8]
#define BT_COLON BT_NMSTRT
BYTE_TO_ASCII [1/3]
#define BYTE_TO_ASCII (enc, p) (*(p))
BYTE_TO_ASCII [2/3]
#define BYTE_TO_ASCII (enc, p) LITTLE2_BYTE_TO_ASCII(enc, p)
BYTE_TO_ASCII [3/3]
#define BYTE_TO_ASCII (enc, p) BIG2_BYTE_TO_ASCII(enc, p)
BYTE_TYPE [1/3]
#define BYTE_TYPE (enc, p) SB_BYTE_TYPE(enc, p)
BYTE_TYPE [2/3]
#define BYTE_TYPE (enc, p) LITTLE2_BYTE_TYPE(enc, p)
BYTE_TYPE [3/3]
#define BYTE_TYPE (enc, p) BIG2_BYTE_TYPE(enc, p)
CHAR_MATCHES [1/3]
#define CHAR_MATCHES (enc, p, c) (*(p) == c)
CHAR_MATCHES [2/3]
#define CHAR_MATCHES (enc, p, c) LITTLE2_CHAR_MATCHES(enc, p, c)
CHAR_MATCHES [3/3]
#define CHAR_MATCHES (enc, p, c) BIG2_CHAR_MATCHES(enc, p, c)
DEFINE_UTF16_TO_UTF16
#define DEFINE_UTF16_TO_UTF16 (E)
Value:
static enum XML_Convert_Result  PTRCALL \
E ## toUtf16(const ENCODING *UNUSED_P(enc), \
             const char **fromP, const char *fromLim, \
             unsigned short **toP, const unsigned short *toLim) \
{ \
  enum XML_Convert_Result res = XML_CONVERT_COMPLETED; \
  fromLim = *fromP + (((fromLim - *fromP) >> 1) << 1);  /* shrink to even */ \
  /* Avoid copying first half only of surrogate */ \
  if (fromLim - *fromP > ((toLim - *toP) << 1) \
      && (GET_HI(fromLim - 2) & 0xF8) == 0xD8) { \
    fromLim -= 2; \
    res = XML_CONVERT_INPUT_INCOMPLETE; \
  } \
  for (; *fromP < fromLim && *toP < toLim; *fromP += 2) \
    *(*toP)++ = (GET_HI(*fromP) << 8) | GET_LO(*fromP); \
  if ((*toP == toLim) && (*fromP < fromLim)) \
    return XML_CONVERT_OUTPUT_EXHAUSTED; \
  else \
    return res; \
}
DEFINE_UTF16_TO_UTF8
#define DEFINE_UTF16_TO_UTF8 (E)
GET_HI [1/2]
#define GET_HI (ptr) ((unsigned char)(ptr)[1])
GET_HI [2/2]
#define GET_HI (ptr) ((unsigned char)(ptr)[0])
GET_LO [1/2]
#define GET_LO (ptr) ((unsigned char)(ptr)[0])
GET_LO [2/2]
#define GET_LO (ptr) ((unsigned char)(ptr)[1])
IGNORE_SECTION_TOK_VTABLE
#define IGNORE_SECTION_TOK_VTABLE , PREFIX(ignoreSectionTok)
INIT_ENC_INDEX
#define INIT_ENC_INDEX (enc) ((int)(enc)->initEnc.isUtf16)
IS_INVALID_CHAR
#define IS_INVALID_CHAR (enc, p, n) (AS_NORMAL_ENCODING(enc)->isInvalid ## n(enc, p))
IS_NAME_CHAR [1/3]
#define IS_NAME_CHAR (enc, p, n) (AS_NORMAL_ENCODING(enc)->isName ## n(enc, p))
IS_NAME_CHAR [2/3]
#define IS_NAME_CHAR (enc, p, n) 0
IS_NAME_CHAR [3/3]
#define IS_NAME_CHAR (enc, p, n) 0
IS_NAME_CHAR_MINBPC [1/3]
#define IS_NAME_CHAR_MINBPC (enc, p) (0)
IS_NAME_CHAR_MINBPC [2/3]
#define IS_NAME_CHAR_MINBPC (enc, p) LITTLE2_IS_NAME_CHAR_MINBPC(enc, p)
IS_NAME_CHAR_MINBPC [3/3]
#define IS_NAME_CHAR_MINBPC (enc, p) BIG2_IS_NAME_CHAR_MINBPC(enc, p)
IS_NMSTRT_CHAR [1/3]
#define IS_NMSTRT_CHAR (enc, p, n) (AS_NORMAL_ENCODING(enc)->isNmstrt ## n(enc, p))
IS_NMSTRT_CHAR [2/3]
#define IS_NMSTRT_CHAR (enc, p, n) (0)
IS_NMSTRT_CHAR [3/3]
#define IS_NMSTRT_CHAR (enc, p, n) (0)
IS_NMSTRT_CHAR_MINBPC [1/3]
#define IS_NMSTRT_CHAR_MINBPC (enc, p) (0)
IS_NMSTRT_CHAR_MINBPC [2/3]
#define IS_NMSTRT_CHAR_MINBPC (enc, p) LITTLE2_IS_NMSTRT_CHAR_MINBPC(enc, p)
IS_NMSTRT_CHAR_MINBPC [3/3]
#define IS_NMSTRT_CHAR_MINBPC (enc, p) BIG2_IS_NMSTRT_CHAR_MINBPC(enc, p)
LITTLE2_BYTE_TO_ASCII
#define LITTLE2_BYTE_TO_ASCII (enc, p) ((p)[1] == 0 ? (p)[0] : -1)
LITTLE2_BYTE_TYPE
#define LITTLE2_BYTE_TYPE (enc, p)
Value:
 ((p)[1] == 0 \
  ? ((struct normal_encoding *)(enc))->type[(unsigned char)*(p)] \
  : unicode_byte_type((p)[1], (p)[0]))
LITTLE2_CHAR_MATCHES
#define LITTLE2_CHAR_MATCHES (enc, p, c) ((p)[1] == 0 && (p)[0] == c)
LITTLE2_IS_NAME_CHAR_MINBPC
#define LITTLE2_IS_NAME_CHAR_MINBPC (enc, p) UCS2_GET_NAMING(namePages, (unsigned char)p[1], (unsigned char)p[0])
LITTLE2_IS_NMSTRT_CHAR_MINBPC
#define LITTLE2_IS_NMSTRT_CHAR_MINBPC (enc, p) UCS2_GET_NAMING(nmstrtPages, (unsigned char)p[1], (unsigned char)p[0])
MINBPC [1/3]
#define MINBPC (enc) 1
MINBPC [2/3]
#define MINBPC (enc) 2
MINBPC [3/3]
#define MINBPC (enc) 2
NORMAL_VTABLE
#define NORMAL_VTABLE (E)
Value:
 E ## isName2, \
 E ## isName3, \
 E ## isName4, \
 E ## isNmstrt2, \
 E ## isNmstrt3, \
 E ## isNmstrt4, \
 E ## isInvalid2, \
 E ## isInvalid3, \
 E ## isInvalid4
NS [1/2]
#define NS (x) x
ns [1/2]
#define ns (x) x
NS [2/2]
#define NS (x) x ## NS
ns [2/2]
#define ns (x) x ## _ns
NULL_VTABLE
#define NULL_VTABLE
Value:
 /* isName2 */ NULL, \
 /* isName3 */ NULL, \
 /* isName4 */ NULL, \
 /* isNmstrt2 */ NULL, \
 /* isNmstrt3 */ NULL, \
 /* isNmstrt4 */ NULL, \
 /* isInvalid2 */ NULL, \
 /* isInvalid3 */ NULL, \
 /* isInvalid4 */ NULL
PREFIX [1/3]
#define PREFIX (ident) normal_ ## ident
PREFIX [2/3]
#define PREFIX (ident) little2_ ## ident
PREFIX [3/3]
#define PREFIX (ident) big2_ ## ident
SB_BYTE_TYPE
#define SB_BYTE_TYPE (enc, p) (((struct normal_encoding *)(enc))->type[(unsigned char)*(p)])
SET2 [1/2]
#define SET2 (ptr, ch) (((ptr)[0] = ((ch) & 0xff)), ((ptr)[1] = ((ch) >> 8)))
SET2 [2/2]
#define SET2 (ptr, ch) (((ptr)[0] = ((ch) >> 8)), ((ptr)[1] = ((ch) & 0xFF)))
SET_INIT_ENC_INDEX
#define SET_INIT_ENC_INDEX (enc, i) ((enc)->initEnc.isUtf16 = (char)i)
STANDARD_VTABLE
#define STANDARD_VTABLE (E) /* as nothing */
UCS2_GET_NAMING
#define UCS2_GET_NAMING (pages, hi, lo) (namingBitmap[(pages[hi] << 3) + ((lo) >> 5)] & (1u << ((lo) & 0x1F)))
UTF8_GET_NAMING
#define UTF8_GET_NAMING (pages, p, n)
Value:
  ((n) == 2 \
  ? UTF8_GET_NAMING2(pages, (const unsigned char *)(p)) \
  : ((n) == 3 \
     ? UTF8_GET_NAMING3(pages, (const unsigned char *)(p)) \
     : 0))
UTF8_GET_NAMING2
#define UTF8_GET_NAMING2 (pages, byte)
Value:
    (namingBitmap[((pages)[(((byte)[0]) >> 2) & 7] << 3) \
                      + ((((byte)[0]) & 3) << 1) \
                      + ((((byte)[1]) >> 5) & 1)] \
         & (1u << (((byte)[1]) & 0x1F)))
UTF8_GET_NAMING3
#define UTF8_GET_NAMING3 (pages, byte)
Value:
  (namingBitmap[((pages)[((((byte)[0]) & 0xF) << 4) \
                             + ((((byte)[1]) >> 2) & 0xF)] \
                       << 3) \
                      + ((((byte)[1]) & 3) << 1) \
                      + ((((byte)[2]) >> 5) & 1)] \
         & (1u << (((byte)[2]) & 0x1F)))
UTF8_INVALID2
#define UTF8_INVALID2 (p) ((*p) < 0xC2 || ((p)[1] & 0x80) == 0 || ((p)[1] & 0xC0) == 0xC0)
UTF8_INVALID3
#define UTF8_INVALID3 (p)
Value:
  (((p)[2] & 0x80) == 0 \
  || \
  ((*p) == 0xEF && (p)[1] == 0xBF \
    ? \
    (p)[2] > 0xBD \
    : \
    ((p)[2] & 0xC0) == 0xC0) \
  || \
  ((*p) == 0xE0 \
    ? \
    (p)[1] < 0xA0 || ((p)[1] & 0xC0) == 0xC0 \
    : \
    ((p)[1] & 0x80) == 0 \
    || \
    ((*p) == 0xED ? (p)[1] > 0x9F : ((p)[1] & 0xC0) == 0xC0)))
UTF8_INVALID4
#define UTF8_INVALID4 (p)
Value:
  (((p)[3] & 0x80) == 0 || ((p)[3] & 0xC0) == 0xC0 \
  || \
  ((p)[2] & 0x80) == 0 || ((p)[2] & 0xC0) == 0xC0 \
  || \
  ((*p) == 0xF0 \
    ? \
    (p)[1] < 0x90 || ((p)[1] & 0xC0) == 0xC0 \
    : \
    ((p)[1] & 0x80) == 0 \
    || \
    ((*p) == 0xF4 ? (p)[1] > 0x8F : ((p)[1] & 0xC0) == 0xC0)))
utf8_isName4
#define utf8_isName4 isNever
utf8_isNmstrt4
#define utf8_isNmstrt4 isNever
VTABLE
#define VTABLE VTABLE1, PREFIX(toUtf8), PREFIX(toUtf16)
VTABLE1
#define VTABLE1
Value:
  { PREFIX(prologTok), PREFIX(contentTok), \
    PREFIX(cdataSectionTok) IGNORE_SECTION_TOK_VTABLE }, \
  { PREFIX(attributeValueTok), PREFIX(entityValueTok) }, \
  PREFIX(sameName), \
  PREFIX(nameMatchesAscii), \
  PREFIX(nameLength), \
  PREFIX(skipS), \
  PREFIX(getAtts), \
  PREFIX(charRefNumber), \
  PREFIX(predefinedEntityName), \
  PREFIX(updatePosition), \
  PREFIX(isPublicId)
XML_TOK_IMPL_C [1/3]
#define XML_TOK_IMPL_C
XML_TOK_IMPL_C [2/3]
#define XML_TOK_IMPL_C
XML_TOK_IMPL_C [3/3]
#define XML_TOK_IMPL_C
XML_TOK_NS_C [1/2]
#define XML_TOK_NS_C
XML_TOK_NS_C [2/2]
#define XML_TOK_NS_C
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
UTF8_cval1
UTF8_cval2
UTF8_cval3
UTF8_cval4
     {  /* UTF8_cvalN is value of masked first byte of N byte sequence */
  UTF8_cval1 = 0x00,
  UTF8_cval2 = 0xc0,
  UTF8_cval3 = 0xe0,
  UTF8_cval4 = 0xf0
};
anonymous enum
anonymous enum
Enumerator
UNKNOWN_ENC
ISO_8859_1_ENC
US_ASCII_ENC
UTF_8_ENC
UTF_16_ENC
UTF_16BE_ENC
UTF_16LE_ENC
NO_ENC
     {
  UNKNOWN_ENC = -1,
  ISO_8859_1_ENC = 0,
  US_ASCII_ENC,
  UTF_8_ENC,
  UTF_16_ENC,
  UTF_16BE_ENC,
  UTF_16LE_ENC,
  /* must match encodingNames up to here */
  NO_ENC
};
Function Documentation
align_limit_to_full_utf8_characters()
void align_limit_to_full_utf8_characters (const char * from, const char ** fromLimRef)
{
  const char * fromLim = *fromLimRef;
  size_t walked = 0;
  for (; fromLim > from; fromLim--, walked++) {
    const unsigned char prev = (unsigned char)fromLim[-1];
    if ((prev & 0xf8u) == 0xf0u) { /* 4-byte character, lead by 0b11110xxx byte */
      if (walked + 1 >= 4) {
        fromLim += 4 - 1;
        break;
      } else {
        walked = 0;
      }
    } else if ((prev & 0xf0u) == 0xe0u) { /* 3-byte character, lead by 0b1110xxxx byte */
      if (walked + 1 >= 3) {
        fromLim += 3 - 1;
        break;
      } else {
        walked = 0;
      }
    } else if ((prev & 0xe0u) == 0xc0u) { /* 2-byte character, lead by 0b110xxxxx byte */
      if (walked + 1 >= 2) {
        fromLim += 2 - 1;
        break;
      } else {
        walked = 0;
      }
    } else if ((prev & 0x80u) == 0x00u) { /* 1-byte character, matching 0b0xxxxxxx */
      break;
    }
  }
  *fromLimRef = fromLim;
}
Referenced by utf8_toUtf8().
ascii_toUtf8()
static enum XML_Convert_Result PTRCALL ascii_toUtf8 (const ENCODING * UNUSED_Penc, const char ** fromP, const char * fromLim, char ** toP, const char * toLim) static
{
  while (*fromP < fromLim && *toP < toLim)
    *(*toP)++ = *(*fromP)++;
  if ((*toP == toLim) && (*fromP < fromLim))
    return XML_CONVERT_OUTPUT_EXHAUSTED;
  else
    return XML_CONVERT_COMPLETED;
}
References XML_CONVERT_COMPLETED, and XML_CONVERT_OUTPUT_EXHAUSTED.
checkCharRefNumber()
static int FASTCALL checkCharRefNumber (int result) static
{
  switch (result >> 8) {
  case 0xD8: case 0xD9: case 0xDA: case 0xDB:
  case 0xDC: case 0xDD: case 0xDE: case 0xDF:
    return -1;
  case 0:
    if (latin1_encoding.type[result] == BT_NONXML)
      return -1;
    break;
  case 0xFF:
    if (result == 0xFFFE || result == 0xFFFF)
      return -1;
    break;
  }
  return result;
}
References BT_NONXML, latin1_encoding, and normal_encoding::type.
Referenced by unknown_isInvalid(), and XmlInitUnknownEncoding().
doParseXmlDecl()
static int doParseXmlDecl (const ENCODING *(*)(const ENCODING *, const char *, const char *) encodingFinder, int isGeneralTextEntity, const ENCODING * enc, const char * ptr, const char * end, const char ** badPtr, const char ** versionPtr, const char ** versionEndPtr, const char ** encodingName, const ENCODING ** encoding, int * standalone) static
{
  const char *val = NULL;
  const char *name = NULL;
  const char *nameEnd = NULL;
  ptr += 5 * enc->minBytesPerChar;
  end -= 2 * enc->minBytesPerChar;
  if (!parsePseudoAttribute(enc, ptr, end, &name, &nameEnd, &val, &ptr)
      || !name) {
    *badPtr = ptr;
    return 0;
  }
  if (!XmlNameMatchesAscii(enc, name, nameEnd, KW_version)) {
    if (!isGeneralTextEntity) {
      *badPtr = name;
      return 0;
    }
  }
  else {
    if (versionPtr)
      *versionPtr = val;
    if (versionEndPtr)
      *versionEndPtr = ptr;
    if (!parsePseudoAttribute(enc, ptr, end, &name, &nameEnd, &val, &ptr)) {
      *badPtr = ptr;
      return 0;
    }
    if (!name) {
      if (isGeneralTextEntity) {
        /* a TextDecl must have an EncodingDecl */
        *badPtr = ptr;
        return 0;
      }
      return 1;
    }
  }
  if (XmlNameMatchesAscii(enc, name, nameEnd, KW_encoding)) {
    int c = toAscii(enc, val, end);
    if (!(ASCII_a <= c && c <= ASCII_z) && !(ASCII_A <= c && c <= ASCII_Z)) {
      *badPtr = val;
      return 0;
    }
    if (encodingName)
      *encodingName = val;
    if (encoding)
      *encoding = encodingFinder(enc, val, ptr - enc->minBytesPerChar);
    if (!parsePseudoAttribute(enc, ptr, end, &name, &nameEnd, &val, &ptr)) {
      *badPtr = ptr;
      return 0;
    }
    if (!name)
      return 1;
  }
  if (!XmlNameMatchesAscii(enc, name, nameEnd, KW_standalone)
      || isGeneralTextEntity) {
    *badPtr = name;
    return 0;
  }
  if (XmlNameMatchesAscii(enc, val, ptr - enc->minBytesPerChar, KW_yes)) {
    if (standalone)
      *standalone = 1;
  }
  else if (XmlNameMatchesAscii(enc, val, ptr - enc->minBytesPerChar, KW_no)) {
    if (standalone)
      *standalone = 0;
  }
  else {
    *badPtr = val;
    return 0;
  }
  while (isSpace(toAscii(enc, ptr, end)))
    ptr += enc->minBytesPerChar;
  if (ptr != end) {
    *badPtr = ptr;
    return 0;
  }
  return 1;
}
References ASCII_A, ASCII_a, ASCII_Z, ASCII_z, badPtr, enc, end, isSpace(), KW_encoding, KW_no, KW_standalone, KW_version, KW_yes, NULL, parsePseudoAttribute(), ptr, toAscii(), and XmlNameMatchesAscii.
getEncodingIndex()
static int FASTCALL getEncodingIndex (const char * name) static
{
  static const char * const encodingNames[] = {
    KW_ISO_8859_1,
    KW_US_ASCII,
    KW_UTF_8,
    KW_UTF_16,
    KW_UTF_16BE,
    KW_UTF_16LE,
  };
  int i;
  if (name == NULL)
    return NO_ENC;
  for (i = 0; i < (int)(sizeof(encodingNames)/sizeof(encodingNames[0])); i++)
    if (streqci(name, encodingNames[i]))
      return i;
  return UNKNOWN_ENC;
}
References int, KW_ISO_8859_1, KW_US_ASCII, KW_UTF_16, KW_UTF_16BE, KW_UTF_16LE, KW_UTF_8, NO_ENC, NULL, streqci(), and UNKNOWN_ENC.
initScan()
static int initScan (const ENCODING *const * encodingTable, const INIT_ENCODING * enc, int state, const char * ptr, const char * end, const char ** nextTokPtr) static
{
  const ENCODING **encPtr;
  if (ptr >= end)
    return XML_TOK_NONE;
  encPtr = enc->encPtr;
  if (ptr + 1 == end) {
    /* only a single byte available for auto-detection */
#ifndef XML_DTD /* FIXME */
    /* a well-formed document entity must have more than one byte */
    if (state != XML_CONTENT_STATE)
      return XML_TOK_PARTIAL;
#endif
    /* so we're parsing an external text entity... */
    /* if UTF-16 was externally specified, then we need at least 2 bytes */
    switch (INIT_ENC_INDEX(enc)) {
    case UTF_16_ENC:
    case UTF_16LE_ENC:
    case UTF_16BE_ENC:
      return XML_TOK_PARTIAL;
    }
    switch ((unsigned char)*ptr) {
    case 0xFE:
    case 0xFF:
    case 0xEF: /* possibly first byte of UTF-8 BOM */
      if (INIT_ENC_INDEX(enc) == ISO_8859_1_ENC
          && state == XML_CONTENT_STATE)
        break;
      /* fall through */
    case 0x00:
    case 0x3C:
      return XML_TOK_PARTIAL;
    }
  }
  else {
    switch (((unsigned char)ptr[0] << 8) | (unsigned char)ptr[1]) {
    case 0xFEFF:
      if (INIT_ENC_INDEX(enc) == ISO_8859_1_ENC
          && state == XML_CONTENT_STATE)
        break;
      *nextTokPtr = ptr + 2;
      *encPtr = encodingTable[UTF_16BE_ENC];
      return XML_TOK_BOM;
    /* 00 3C is handled in the default case */
    case 0x3C00:
      if ((INIT_ENC_INDEX(enc) == UTF_16BE_ENC
           || INIT_ENC_INDEX(enc) == UTF_16_ENC)
          && state == XML_CONTENT_STATE)
        break;
      *encPtr = encodingTable[UTF_16LE_ENC];
      return XmlTok(*encPtr, state, ptr, end, nextTokPtr);
    case 0xFFFE:
      if (INIT_ENC_INDEX(enc) == ISO_8859_1_ENC
          && state == XML_CONTENT_STATE)
        break;
      *nextTokPtr = ptr + 2;
      *encPtr = encodingTable[UTF_16LE_ENC];
      return XML_TOK_BOM;
    case 0xEFBB:
      /* Maybe a UTF-8 BOM (EF BB BF) */
      /* If there's an explicitly specified (external) encoding
         of ISO-8859-1 or some flavour of UTF-16
         and this is an external text entity,
         don't look for the BOM,
         because it might be a legal data.
      */
      if (state == XML_CONTENT_STATE) {
        int e = INIT_ENC_INDEX(enc);
        if (e == ISO_8859_1_ENC || e == UTF_16BE_ENC
            || e == UTF_16LE_ENC || e == UTF_16_ENC)
          break;
      }
      if (ptr + 2 == end)
        return XML_TOK_PARTIAL;
      if ((unsigned char)ptr[2] == 0xBF) {
        *nextTokPtr = ptr + 3;
        *encPtr = encodingTable[UTF_8_ENC];
        return XML_TOK_BOM;
      }
      break;
    default:
      if (ptr[0] == '\0') {
        /* 0 isn't a legal data character. Furthermore a document
           entity can only start with ASCII characters.  So the only
           way this can fail to be big-endian UTF-16 if it it's an
           external parsed general entity that's labelled as
           UTF-16LE.
        */
        if (state == XML_CONTENT_STATE && INIT_ENC_INDEX(enc) == UTF_16LE_ENC)
          break;
        *encPtr = encodingTable[UTF_16BE_ENC];
        return XmlTok(*encPtr, state, ptr, end, nextTokPtr);
      }
      else if (ptr[1] == '\0') {
        /* We could recover here in the case:
            - parsing an external entity
            - second byte is 0
            - no externally specified encoding
            - no encoding declaration
           by assuming UTF-16LE.  But we don't, because this would mean when
           presented just with a single byte, we couldn't reliably determine
           whether we needed further bytes.
        */
        if (state == XML_CONTENT_STATE)
          break;
        *encPtr = encodingTable[UTF_16LE_ENC];
        return XmlTok(*encPtr, state, ptr, end, nextTokPtr);
      }
      break;
    }
  }
  *encPtr = encodingTable[INIT_ENC_INDEX(enc)];
  return XmlTok(*encPtr, state, ptr, end, nextTokPtr);
}
References enc, end, INIT_ENC_INDEX, ISO_8859_1_ENC, nextTokPtr, ptr, UTF_16_ENC, UTF_16BE_ENC, UTF_16LE_ENC, UTF_8_ENC, XML_CONTENT_STATE, XML_TOK_BOM, XML_TOK_NONE, XML_TOK_PARTIAL, and XmlTok.
initUpdatePosition()
static void PTRCALL initUpdatePosition (const ENCODING * UNUSED_Penc, const char * ptr, const char * end, POSITION * pos) static
{
  normal_updatePosition(&utf8_encoding.enc, ptr, end, pos);
}
References normal_encoding::enc, end, ptr, and utf8_encoding.
isNever()
static int PTRFASTCALL isNever (const ENCODING * UNUSED_Penc, const char * UNUSED_Pp) static
{
  return 0;
}
isSpace()
static int FASTCALL isSpace (int c) static
{
  switch (c) {
  case 0x20:
  case 0xD:
  case 0xA:
  case 0x9:
    return 1;
  }
  return 0;
}
Referenced by doParseXmlDecl(), and parsePseudoAttribute().
latin1_toUtf16()
static enum XML_Convert_Result PTRCALL latin1_toUtf16 (const ENCODING * UNUSED_Penc, const char ** fromP, const char * fromLim, unsigned short ** toP, const unsigned short * toLim) static
{
  while (*fromP < fromLim && *toP < toLim)
    *(*toP)++ = (unsigned char)*(*fromP)++;
  if ((*toP == toLim) && (*fromP < fromLim))
    return XML_CONVERT_OUTPUT_EXHAUSTED;
  else
    return XML_CONVERT_COMPLETED;
}
References XML_CONVERT_COMPLETED, and XML_CONVERT_OUTPUT_EXHAUSTED.
latin1_toUtf8()
static enum XML_Convert_Result PTRCALL latin1_toUtf8 (const ENCODING * UNUSED_Penc, const char ** fromP, const char * fromLim, char ** toP, const char * toLim) static
{
  for (;;) {
    unsigned char c;
    if (*fromP == fromLim)
      return XML_CONVERT_COMPLETED;
    c = (unsigned char)**fromP;
    if (c & 0x80) {
      if (toLim - *toP < 2)
        return XML_CONVERT_OUTPUT_EXHAUSTED;
      *(*toP)++ = (char)((c >> 6) | UTF8_cval2);
      *(*toP)++ = (char)((c & 0x3f) | 0x80);
      (*fromP)++;
    }
    else {
      if (*toP == toLim)
        return XML_CONVERT_OUTPUT_EXHAUSTED;
      *(*toP)++ = *(*fromP)++;
    }
  }
}
References UTF8_cval2, XML_CONVERT_COMPLETED, and XML_CONVERT_OUTPUT_EXHAUSTED.
parsePseudoAttribute()
static int parsePseudoAttribute (const ENCODING * enc, const char * ptr, const char * end, const char ** namePtr, const char ** nameEndPtr, const char ** valPtr, const char ** nextTokPtr) static
{
  int c;
  char open;
  if (ptr == end) {
    *namePtr = NULL;
    return 1;
  }
  if (!isSpace(toAscii(enc, ptr, end))) {
    *nextTokPtr = ptr;
    return 0;
  }
  do {
    ptr += enc->minBytesPerChar;
  } while (isSpace(toAscii(enc, ptr, end)));
  if (ptr == end) {
    *namePtr = NULL;
    return 1;
  }
  *namePtr = ptr;
  for (;;) {
    c = toAscii(enc, ptr, end);
    if (c == -1) {
      *nextTokPtr = ptr;
      return 0;
    }
    if (c == ASCII_EQUALS) {
      *nameEndPtr = ptr;
      break;
    }
    if (isSpace(c)) {
      *nameEndPtr = ptr;
      do {
        ptr += enc->minBytesPerChar;
      } while (isSpace(c = toAscii(enc, ptr, end)));
      if (c != ASCII_EQUALS) {
        *nextTokPtr = ptr;
        return 0;
      }
      break;
    }
    ptr += enc->minBytesPerChar;
  }
  if (ptr == *namePtr) {
    *nextTokPtr = ptr;
    return 0;
  }
  ptr += enc->minBytesPerChar;
  c = toAscii(enc, ptr, end);
  while (isSpace(c)) {
    ptr += enc->minBytesPerChar;
    c = toAscii(enc, ptr, end);
  }
  if (c != ASCII_QUOT && c != ASCII_APOS) {
    *nextTokPtr = ptr;
    return 0;
  }
  open = (char)c;
  ptr += enc->minBytesPerChar;
  *valPtr = ptr;
  for (;; ptr += enc->minBytesPerChar) {
    c = toAscii(enc, ptr, end);
    if (c == open)
      break;
    if (!(ASCII_a <= c && c <= ASCII_z)
        && !(ASCII_A <= c && c <= ASCII_Z)
        && !(ASCII_0 <= c && c <= ASCII_9)
        && c != ASCII_PERIOD
        && c != ASCII_MINUS
        && c != ASCII_UNDERSCORE) {
      *nextTokPtr = ptr;
      return 0;
    }
  }
  *nextTokPtr = ptr + enc->minBytesPerChar;
  return 1;
}
References ASCII_0, ASCII_9, ASCII_A, ASCII_a, ASCII_APOS, ASCII_EQUALS, ASCII_MINUS, ASCII_PERIOD, ASCII_QUOT, ASCII_UNDERSCORE, ASCII_Z, ASCII_z, enc, end, isSpace(), nextTokPtr, NULL, open, ptr, and toAscii().
Referenced by doParseXmlDecl().
streqci()
static int FASTCALL streqci (const char * s1, const char * s2) static
{
  for (;;) {
    char c1 = *s1++;
    char c2 = *s2++;
    if (ASCII_a <= c1 && c1 <= ASCII_z)
      c1 += ASCII_A - ASCII_a;
    if (ASCII_a <= c2 && c2 <= ASCII_z)
      c2 += ASCII_A - ASCII_a;
    if (c1 != c2)
      return 0;
    if (!c1)
      break;
  }
  return 1;
}
References ASCII_A, ASCII_a, and ASCII_z.
Referenced by getEncodingIndex().
toAscii()
static int toAscii (const ENCODING * enc, const char * ptr, const char * end) static
{
  char buf[1];
  char *p = buf;
  XmlUtf8Convert(enc, &ptr, end, &p, p + 1);
  if (p == buf)
    return -1;
  else
    return buf[0];
}
References enc, end, ptr, and XmlUtf8Convert.
Referenced by doParseXmlDecl(), and parsePseudoAttribute().
unicode_byte_type()
static int PTRFASTCALL unicode_byte_type (char hi, char lo) static
{
  switch ((unsigned char)hi) {
  case 0xD8: case 0xD9: case 0xDA: case 0xDB:
    return BT_LEAD4;
  case 0xDC: case 0xDD: case 0xDE: case 0xDF:
    return BT_TRAIL;
  case 0xFF:
    switch ((unsigned char)lo) {
    case 0xFF:
    case 0xFE:
      return BT_NONXML;
    }
    break;
  }
  return BT_NONASCII;
}
References BT_LEAD4, BT_NONASCII, BT_NONXML, and BT_TRAIL.
unknown_isInvalid()
static int PTRFASTCALL unknown_isInvalid (const ENCODING * enc, const char * p) static
{
  const struct unknown_encoding *uenc = AS_UNKNOWN_ENCODING(enc);
  int c = uenc->convert(uenc->userData, p);
  return (c & ~0xFFFF) || checkCharRefNumber(c) < 0;
}
References AS_UNKNOWN_ENCODING, checkCharRefNumber(), unknown_encoding::convert, enc, and unknown_encoding::userData.
Referenced by XmlInitUnknownEncoding().
unknown_isName()
static int PTRFASTCALL unknown_isName (const ENCODING * enc, const char * p) static
{
  const struct unknown_encoding *uenc = AS_UNKNOWN_ENCODING(enc);
  int c = uenc->convert(uenc->userData, p);
  if (c & ~0xFFFF)
    return 0;
  return UCS2_GET_NAMING(namePages, c >> 8, c & 0xFF);
}
References AS_UNKNOWN_ENCODING, unknown_encoding::convert, enc, namePages, UCS2_GET_NAMING, and unknown_encoding::userData.
Referenced by XmlInitUnknownEncoding().
unknown_isNmstrt()
static int PTRFASTCALL unknown_isNmstrt (const ENCODING * enc, const char * p) static
{
  const struct unknown_encoding *uenc = AS_UNKNOWN_ENCODING(enc);
  int c = uenc->convert(uenc->userData, p);
  if (c & ~0xFFFF)
    return 0;
  return UCS2_GET_NAMING(nmstrtPages, c >> 8, c & 0xFF);
}
References AS_UNKNOWN_ENCODING, unknown_encoding::convert, enc, nmstrtPages, UCS2_GET_NAMING, and unknown_encoding::userData.
Referenced by XmlInitUnknownEncoding().
unknown_toUtf16()
static enum XML_Convert_Result PTRCALL unknown_toUtf16 (const ENCODING * enc, const char ** fromP, const char * fromLim, unsigned short ** toP, const unsigned short * toLim) static
{
  const struct unknown_encoding *uenc = AS_UNKNOWN_ENCODING(enc);
  while (*fromP < fromLim && *toP < toLim) {
    unsigned short c = uenc->utf16[(unsigned char)**fromP];
    if (c == 0) {
      c = (unsigned short)
          uenc->convert(uenc->userData, *fromP);
      *fromP += (AS_NORMAL_ENCODING(enc)->type[(unsigned char)**fromP]
                 - (BT_LEAD2 - 2));
    }
    else
      (*fromP)++;
    *(*toP)++ = c;
  }
  if ((*toP == toLim) && (*fromP < fromLim))
    return XML_CONVERT_OUTPUT_EXHAUSTED;
  else
    return XML_CONVERT_COMPLETED;
}
References AS_NORMAL_ENCODING, AS_UNKNOWN_ENCODING, BT_LEAD2, unknown_encoding::convert, enc, unknown_encoding::userData, unknown_encoding::utf16, XML_CONVERT_COMPLETED, and XML_CONVERT_OUTPUT_EXHAUSTED.
Referenced by XmlInitUnknownEncoding().
unknown_toUtf8()
static enum XML_Convert_Result PTRCALL unknown_toUtf8 (const ENCODING * enc, const char ** fromP, const char * fromLim, char ** toP, const char * toLim) static
{
  const struct unknown_encoding *uenc = AS_UNKNOWN_ENCODING(enc);
  char buf[XML_UTF8_ENCODE_MAX];
  for (;;) {
    const char *utf8;
    int n;
    if (*fromP == fromLim)
      return XML_CONVERT_COMPLETED;
    utf8 = uenc->utf8[(unsigned char)**fromP];
    n = *utf8++;
    if (n == 0) {
      int c = uenc->convert(uenc->userData, *fromP);
      n = XmlUtf8Encode(c, buf);
      if (n > toLim - *toP)
        return XML_CONVERT_OUTPUT_EXHAUSTED;
      utf8 = buf;
      *fromP += (AS_NORMAL_ENCODING(enc)->type[(unsigned char)**fromP]
                 - (BT_LEAD2 - 2));
    }
    else {
      if (n > toLim - *toP)
        return XML_CONVERT_OUTPUT_EXHAUSTED;
      (*fromP)++;
    }
    do {
      *(*toP)++ = *utf8++;
    } while (--n != 0);
  }
}
References AS_NORMAL_ENCODING, AS_UNKNOWN_ENCODING, BT_LEAD2, unknown_encoding::convert, enc, n, unknown_encoding::userData, unknown_encoding::utf8, XML_CONVERT_COMPLETED, XML_CONVERT_OUTPUT_EXHAUSTED, XML_UTF8_ENCODE_MAX, and XmlUtf8Encode().
Referenced by XmlInitUnknownEncoding().
utf8_isInvalid2()
static int PTRFASTCALL utf8_isInvalid2 (const ENCODING * UNUSED_Penc, const char * p) static
{
  return UTF8_INVALID2((const unsigned char *)p);
}
References UTF8_INVALID2.
utf8_isInvalid3()
static int PTRFASTCALL utf8_isInvalid3 (const ENCODING * UNUSED_Penc, const char * p) static
{
  return UTF8_INVALID3((const unsigned char *)p);
}
References UTF8_INVALID3.
utf8_isInvalid4()
static int PTRFASTCALL utf8_isInvalid4 (const ENCODING * UNUSED_Penc, const char * p) static
{
  return UTF8_INVALID4((const unsigned char *)p);
}
References UTF8_INVALID4.
utf8_isName2()
static int PTRFASTCALL utf8_isName2 (const ENCODING * UNUSED_Penc, const char * p) static
{
  return UTF8_GET_NAMING2(namePages, (const unsigned char *)p);
}
References namePages, and UTF8_GET_NAMING2.
utf8_isName3()
static int PTRFASTCALL utf8_isName3 (const ENCODING * UNUSED_Penc, const char * p) static
{
  return UTF8_GET_NAMING3(namePages, (const unsigned char *)p);
}
References namePages, and UTF8_GET_NAMING3.
utf8_isNmstrt2()
static int PTRFASTCALL utf8_isNmstrt2 (const ENCODING * UNUSED_Penc, const char * p) static
{
  return UTF8_GET_NAMING2(nmstrtPages, (const unsigned char *)p);
}
References nmstrtPages, and UTF8_GET_NAMING2.
utf8_isNmstrt3()
static int PTRFASTCALL utf8_isNmstrt3 (const ENCODING * UNUSED_Penc, const char * p) static
{
  return UTF8_GET_NAMING3(nmstrtPages, (const unsigned char *)p);
}
References nmstrtPages, and UTF8_GET_NAMING3.
utf8_toUtf16()
static enum XML_Convert_Result PTRCALL utf8_toUtf16 (const ENCODING * enc, const char ** fromP, const char * fromLim, unsigned short ** toP, const unsigned short * toLim) static
{
  enum XML_Convert_Result res = XML_CONVERT_COMPLETED;
  unsigned short *to = *toP;
  const char *from = *fromP;
  while (from < fromLim && to < toLim) {
    switch (((struct normal_encoding *)enc)->type[(unsigned char)*from]) {
    case BT_LEAD2:
      if (fromLim - from < 2) {
        res = XML_CONVERT_INPUT_INCOMPLETE;
        break;
      }
      *to++ = (unsigned short)(((from[0] & 0x1f) << 6) | (from[1] & 0x3f));
      from += 2;
      break;
    case BT_LEAD3:
      if (fromLim - from < 3) {
        res = XML_CONVERT_INPUT_INCOMPLETE;
        break;
      }
      *to++ = (unsigned short)(((from[0] & 0xf) << 12)
                               | ((from[1] & 0x3f) << 6) | (from[2] & 0x3f));
      from += 3;
      break;
    case BT_LEAD4:
      {
        unsigned long n;
        if (toLim - to < 2) {
          res = XML_CONVERT_OUTPUT_EXHAUSTED;
          goto after;
        }
        if (fromLim - from < 4) {
          res = XML_CONVERT_INPUT_INCOMPLETE;
          goto after;
        }
        n = ((from[0] & 0x7) << 18) | ((from[1] & 0x3f) << 12)
            | ((from[2] & 0x3f) << 6) | (from[3] & 0x3f);
        n -= 0x10000;
        to[0] = (unsigned short)((n >> 10) | 0xD800);
        to[1] = (unsigned short)((n & 0x3FF) | 0xDC00);
        to += 2;
        from += 4;
      }
      break;
    default:
      *to++ = *from++;
      break;
    }
  }
after:
  *fromP = from;
  *toP = to;
  return res;
}
References BT_LEAD2, BT_LEAD3, BT_LEAD4, enc, n, XML_CONVERT_COMPLETED, XML_CONVERT_INPUT_INCOMPLETE, and XML_CONVERT_OUTPUT_EXHAUSTED.
utf8_toUtf8()
static enum XML_Convert_Result PTRCALL utf8_toUtf8 (const ENCODING * UNUSED_Penc, const char ** fromP, const char * fromLim, char ** toP, const char * toLim) static
{
  enum XML_Convert_Result res = XML_CONVERT_COMPLETED;
  char *to;
  const char *from;
  if (fromLim - *fromP > toLim - *toP) {
    /* Avoid copying partial characters. */
    res = XML_CONVERT_OUTPUT_EXHAUSTED;
    fromLim = *fromP + (toLim - *toP);
    align_limit_to_full_utf8_characters(*fromP, &fromLim);
  }
  for (to = *toP, from = *fromP; (from < fromLim) && (to < toLim); from++, to++)
    *to = *from;
  *fromP = from;
  *toP = to;
  if ((to == toLim) && (from < fromLim))
    return XML_CONVERT_OUTPUT_EXHAUSTED;
  else
    return res;
}
References align_limit_to_full_utf8_characters(), XML_CONVERT_COMPLETED, and XML_CONVERT_OUTPUT_EXHAUSTED.
XmlInitUnknownEncoding()
ENCODING * XmlInitUnknownEncoding (void * mem, int * table, CONVERTER convert, void * userData)
{
  int i;
  struct unknown_encoding *e = (struct unknown_encoding *)mem;
  for (i = 0; i < (int)sizeof(struct normal_encoding); i++)
    ((char *)mem)[i] = ((char *)&latin1_encoding)[i];
  for (i = 0; i < 128; i++)
    if (latin1_encoding.type[i] != BT_OTHER
        && latin1_encoding.type[i] != BT_NONXML
        && table[i] != i)
      return 0;
  for (i = 0; i < 256; i++) {
    int c = table[i];
    if (c == -1) {
      e->normal.type[i] = BT_MALFORM;
      /* This shouldn't really get used. */
      e->utf16[i] = 0xFFFF;
      e->utf8[i][0] = 1;
      e->utf8[i][1] = 0;
    }
    else if (c < 0) {
      if (c < -4)
        return 0;
      e->normal.type[i] = (unsigned char)(BT_LEAD2 - (c + 2));
      e->utf8[i][0] = 0;
      e->utf16[i] = 0;
    }
    else if (c < 0x80) {
      if (latin1_encoding.type[c] != BT_OTHER
          && latin1_encoding.type[c] != BT_NONXML
          && c != i)
        return 0;
      e->normal.type[i] = latin1_encoding.type[c];
      e->utf8[i][0] = 1;
      e->utf8[i][1] = (char)c;
      e->utf16[i] = (unsigned short)(c == 0 ? 0xFFFF : c);
    }
    else if (checkCharRefNumber(c) < 0) {
      e->normal.type[i] = BT_NONXML;
      /* This shouldn't really get used. */
      e->utf16[i] = 0xFFFF;
      e->utf8[i][0] = 1;
      e->utf8[i][1] = 0;
    }
    else {
      if (c > 0xFFFF)
        return 0;
      if (UCS2_GET_NAMING(nmstrtPages, c >> 8, c & 0xff))
        e->normal.type[i] = BT_NMSTRT;
      else if (UCS2_GET_NAMING(namePages, c >> 8, c & 0xff))
        e->normal.type[i] = BT_NAME;
      else
        e->normal.type[i] = BT_OTHER;
      e->utf8[i][0] = (char)XmlUtf8Encode(c, e->utf8[i] + 1);
      e->utf16[i] = (unsigned short)c;
    }
  }
  e->userData = userData;
  e->convert = convert;
  if (convert) {
    e->normal.isName2 = unknown_isName;
    e->normal.isName3 = unknown_isName;
    e->normal.isName4 = unknown_isName;
    e->normal.isNmstrt2 = unknown_isNmstrt;
    e->normal.isNmstrt3 = unknown_isNmstrt;
    e->normal.isNmstrt4 = unknown_isNmstrt;
    e->normal.isInvalid2 = unknown_isInvalid;
    e->normal.isInvalid3 = unknown_isInvalid;
    e->normal.isInvalid4 = unknown_isInvalid;
  }
  e->normal.enc.utf8Convert = unknown_toUtf8;
  e->normal.enc.utf16Convert = unknown_toUtf16;
  return &(e->normal.enc);
}
References BT_LEAD2, BT_MALFORM, BT_NAME, BT_NMSTRT, BT_NONXML, BT_OTHER, checkCharRefNumber(), unknown_encoding::convert, convert(), normal_encoding::enc, int, latin1_encoding, namePages, nmstrtPages, unknown_encoding::normal, normal_encoding::type, UCS2_GET_NAMING, unknown_isInvalid(), unknown_isName(), unknown_isNmstrt(), unknown_toUtf16(), unknown_toUtf8(), userData, unknown_encoding::userData, unknown_encoding::utf16, unknown_encoding::utf8, and XmlUtf8Encode().
Referenced by handleUnknownEncoding(), and XmlInitUnknownEncodingNS().
XmlInitUnknownEncodingNS()
ENCODING * XmlInitUnknownEncodingNS (void * mem, int * table, CONVERTER convert, void * userData)
{
  ENCODING *enc = XmlInitUnknownEncoding(mem, table, convert, userData);
  if (enc)
    ((struct normal_encoding *)enc)->type[ASCII_COLON] = BT_COLON;
  return enc;
}
References ASCII_COLON, BT_COLON, convert(), enc, userData, and XmlInitUnknownEncoding().
Referenced by handleUnknownEncoding().
XmlSizeOfUnknownEncoding()
int XmlSizeOfUnknownEncoding (void)
{
  return sizeof(struct unknown_encoding);
}
Referenced by handleUnknownEncoding().
XmlUtf16Encode()
int FASTCALL XmlUtf16Encode (int charNum, unsigned short * buf)
{
  if (charNum < 0)
    return 0;
  if (charNum < 0x10000) {
    buf[0] = (unsigned short)charNum;
    return 1;
  }
  if (charNum < 0x110000) {
    charNum -= 0x10000;
    buf[0] = (unsigned short)((charNum >> 10) + 0xD800);
    buf[1] = (unsigned short)((charNum & 0x3FF) + 0xDC00);
    return 2;
  }
  return 0;
}
XmlUtf8Encode()
int FASTCALL XmlUtf8Encode (int c, char * buf)
{
  enum {
    /* minN is minimum legal resulting value for N byte sequence */
    min2 = 0x80,
    min3 = 0x800,
    min4 = 0x10000
  };
  if (c < 0)
    return 0;
  if (c < min2) {
    buf[0] = (char)(c | UTF8_cval1);
    return 1;
  }
  if (c < min3) {
    buf[0] = (char)((c >> 6) | UTF8_cval2);
    buf[1] = (char)((c & 0x3f) | 0x80);
    return 2;
  }
  if (c < min4) {
    buf[0] = (char)((c >> 12) | UTF8_cval3);
    buf[1] = (char)(((c >> 6) & 0x3f) | 0x80);
    buf[2] = (char)((c & 0x3f) | 0x80);
    return 3;
  }
  if (c < 0x110000) {
    buf[0] = (char)((c >> 18) | UTF8_cval4);
    buf[1] = (char)(((c >> 12) & 0x3f) | 0x80);
    buf[2] = (char)(((c >> 6) & 0x3f) | 0x80);
    buf[3] = (char)((c & 0x3f) | 0x80);
    return 4;
  }
  return 0;
}
References UTF8_cval1, UTF8_cval2, UTF8_cval3, and UTF8_cval4.
Referenced by unknown_toUtf8(), and XmlInitUnknownEncoding().
Variable Documentation
ascii_encoding
const struct normal_encoding ascii_encoding static
Initial value:
= {
  { VTABLE1, ascii_toUtf8, latin1_toUtf16, 1, 1, 0 },
  {
#define BT_COLON
  },
  STANDARD_VTABLE(sb_) NULL_VTABLE
}
ascii_encoding_ns
const struct normal_encoding ascii_encoding_ns static
Initial value:
= {
  { VTABLE1, ascii_toUtf8, latin1_toUtf16, 1, 1, 0 },
  {
  },
  STANDARD_VTABLE(sb_) NULL_VTABLE
}
big2_encoding
const struct normal_encoding big2_encoding static
Initial value:
= {
  { VTABLE, 2, 0,
  0
  },
  {
#define BT_COLON
  },
  STANDARD_VTABLE(big2_) NULL_VTABLE
}
big2_encoding_ns
const struct normal_encoding big2_encoding_ns static
Initial value:
= {
  { VTABLE, 2, 0,
  0
  },
  {
  },
  STANDARD_VTABLE(big2_) NULL_VTABLE
}
internal_big2_encoding
const struct normal_encoding internal_big2_encoding static
Initial value:
= {
  { VTABLE, 2, 0, 1 },
  {
#define BT_COLON
  },
  STANDARD_VTABLE(big2_) NULL_VTABLE
}
internal_big2_encoding_ns
const struct normal_encoding internal_big2_encoding_ns static
Initial value:
= {
  { VTABLE, 2, 0, 1 },
  {
  },
  STANDARD_VTABLE(big2_) NULL_VTABLE
}
internal_little2_encoding
const struct normal_encoding internal_little2_encoding static
Initial value:
= {
  { VTABLE, 2, 0, 1 },
  {
#define BT_COLON
  },
  STANDARD_VTABLE(little2_) NULL_VTABLE
}
internal_little2_encoding_ns
const struct normal_encoding internal_little2_encoding_ns static
Initial value:
= {
  { VTABLE, 2, 0, 1 },
  {
  },
  STANDARD_VTABLE(little2_) NULL_VTABLE
}
internal_utf8_encoding
const struct normal_encoding internal_utf8_encoding static
Initial value:
= {
  { VTABLE1, utf8_toUtf8, utf8_toUtf16, 1, 1, 0 },
  {
#define BT_COLON
  },
  STANDARD_VTABLE(sb_) NORMAL_VTABLE(utf8_)
}
internal_utf8_encoding_ns
const struct normal_encoding internal_utf8_encoding_ns static
Initial value:
= {
  { VTABLE1, utf8_toUtf8, utf8_toUtf16, 1, 1, 0 },
  {
  },
  STANDARD_VTABLE(sb_) NORMAL_VTABLE(utf8_)
}
KW_encoding
const char KW_encoding[] static
Initial value:
= {
  ASCII_e, ASCII_n, ASCII_c, ASCII_o, ASCII_d, ASCII_i, ASCII_n, ASCII_g, '\0'
}
Referenced by doParseXmlDecl().
KW_ISO_8859_1
const char KW_ISO_8859_1[] static
Initial value:
= {
  ASCII_I, ASCII_S, ASCII_O, ASCII_MINUS, ASCII_8, ASCII_8, ASCII_5, ASCII_9,
  ASCII_MINUS, ASCII_1, '\0'
}
Referenced by getEncodingIndex().
KW_no
const char KW_no[] static
Initial value:
= {
  ASCII_n, ASCII_o,  '\0'
}
Referenced by doParseXmlDecl().
KW_standalone
const char KW_standalone[] static
Initial value:
= {
  ASCII_s, ASCII_t, ASCII_a, ASCII_n, ASCII_d, ASCII_a, ASCII_l, ASCII_o,
  ASCII_n, ASCII_e, '\0'
}
Referenced by doParseXmlDecl().
KW_US_ASCII
const char KW_US_ASCII[] static
Initial value:
= {
  ASCII_U, ASCII_S, ASCII_MINUS, ASCII_A, ASCII_S, ASCII_C, ASCII_I, ASCII_I,
  '\0'
}
Referenced by getEncodingIndex().
KW_UTF_16
const char KW_UTF_16[] static
Initial value:
= {
  ASCII_U, ASCII_T, ASCII_F, ASCII_MINUS, ASCII_1, ASCII_6, '\0'
}
Referenced by getEncodingIndex().
KW_UTF_16BE
const char KW_UTF_16BE[] static
Initial value:
= {
  ASCII_U, ASCII_T, ASCII_F, ASCII_MINUS, ASCII_1, ASCII_6, ASCII_B, ASCII_E,
  '\0'
}
Referenced by getEncodingIndex().
KW_UTF_16LE
const char KW_UTF_16LE[] static
Initial value:
= {
  ASCII_U, ASCII_T, ASCII_F, ASCII_MINUS, ASCII_1, ASCII_6, ASCII_L, ASCII_E,
  '\0'
}
Referenced by getEncodingIndex().
KW_UTF_8
const char KW_UTF_8[] static
Initial value:
=  {
  ASCII_U, ASCII_T, ASCII_F, ASCII_MINUS, ASCII_8, '\0'
}
Referenced by getEncodingIndex().
KW_version
const char KW_version[] static
Initial value:
= {
  ASCII_v, ASCII_e, ASCII_r, ASCII_s, ASCII_i, ASCII_o, ASCII_n, '\0'
}
Referenced by doParseXmlDecl().
KW_yes
const char KW_yes[] static
Initial value:
= {
  ASCII_y, ASCII_e, ASCII_s,  '\0'
}
Referenced by doParseXmlDecl().
latin1_encoding
const struct normal_encoding latin1_encoding static
Initial value:
= {
  { VTABLE1, latin1_toUtf8, latin1_toUtf16, 1, 0, 0 },
  {
#define BT_COLON
  },
  STANDARD_VTABLE(sb_) NULL_VTABLE
}
Referenced by checkCharRefNumber(), and XmlInitUnknownEncoding().
latin1_encoding_ns
const struct normal_encoding latin1_encoding_ns static
Initial value:
= {
  { VTABLE1, latin1_toUtf8, latin1_toUtf16, 1, 0, 0 },
  {
  },
  STANDARD_VTABLE(sb_) NULL_VTABLE
}
little2_encoding
const struct normal_encoding little2_encoding static
Initial value:
= {
  { VTABLE, 2, 0,
    0
  },
  {
#define BT_COLON
  },
  STANDARD_VTABLE(little2_) NULL_VTABLE
}
little2_encoding_ns
const struct normal_encoding little2_encoding_ns static
Initial value:
= {
  { VTABLE, 2, 0,
    0
  },
  {
  },
  STANDARD_VTABLE(little2_) NULL_VTABLE
}
utf8_encoding
const struct normal_encoding utf8_encoding static
Initial value:
= {
  { VTABLE1, utf8_toUtf8, utf8_toUtf16, 1, 1, 0 },
  {
#define BT_COLON
  },
  STANDARD_VTABLE(sb_) NORMAL_VTABLE(utf8_)
}
Referenced by initUpdatePosition().
utf8_encoding_ns
const struct normal_encoding utf8_encoding_ns static
Initial value:
= {
  { VTABLE1, utf8_toUtf8, utf8_toUtf16, 1, 1, 0 },
  {
  },
  STANDARD_VTABLE(sb_) NORMAL_VTABLE(utf8_)
}