OrcaSlicer: Slic3r::GUI::Bed3D::Axes Class Reference
Slic3r::GUI::Bed3D::Axes Class Reference
#include <src/slic3r/GUI/3DBed.hpp>
Public Member Functions
const Vec3d & get_origin () const
void set_origin (const Vec3d &origin)
void set_stem_length (float length)
float get_total_length () const
void render () const
Static Public Attributes
static const float DefaultStemRadius = 0.5f
static const float DefaultStemLength = 25.0f
static const float DefaultTipRadius = 2.5f * Bed3D::Axes::DefaultStemRadius
static const float DefaultTipLength = 5.0f
Private Attributes
Vec3d m_origin { Vec3d::Zero() }
float m_stem_length { DefaultStemLength }
GLModel m_arrow
Detailed Description
Member Function Documentation
get_origin()
const Vec3d & Slic3r::GUI::Bed3D::Axes::get_origin () const inline
{ return m_origin; }
References m_origin.
get_total_length()
float Slic3r::GUI::Bed3D::Axes::get_total_length () const inline
{ return m_stem_length + DefaultTipLength; }
References DefaultTipLength, and m_stem_length.
Referenced by Slic3r::GUI::Bed3D::calc_extended_bounding_box().
render()
void Slic3r::GUI::Bed3D::Axes::render () const
{
    auto render_axis = [this](const Transform3f& transform) {
        glsafe(::glPushMatrix());
        glsafe(::glMultMatrixf(transform.data()));
        m_arrow.render();
        glsafe(::glPopMatrix());
    };
    if (!m_arrow.is_initialized())
        const_cast<GLModel*>(&m_arrow)->init_from(stilized_arrow(16, DefaultTipRadius, DefaultTipLength, DefaultStemRadius, m_stem_length));
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    glsafe(::glEnable(GL_DEPTH_TEST));
    shader->start_using();
    shader->set_uniform("emission_factor", 0.0f);
    // x axis
    const_cast<GLModel*>(&m_arrow)->set_color(-1, AXIS_X_COLOR);
    render_axis(Geometry::assemble_transform(m_origin, { 0.0, 0.5 * M_PI, 0.0 }).cast<float>());
    // y axis
    const_cast<GLModel*>(&m_arrow)->set_color(-1, AXIS_Y_COLOR);
    render_axis(Geometry::assemble_transform(m_origin, { -0.5 * M_PI, 0.0, 0.0 }).cast<float>());
    // z axis
    const_cast<GLModel*>(&m_arrow)->set_color(-1, AXIS_Z_COLOR);
    render_axis(Geometry::assemble_transform(m_origin).cast<float>());
    shader->stop_using();
    glsafe(::glDisable(GL_DEPTH_TEST));
}
References Slic3r::Geometry::assemble_transform(), Slic3r::GUI::Bed3D::AXIS_X_COLOR, Slic3r::GUI::Bed3D::AXIS_Y_COLOR, Slic3r::GUI::Bed3D::AXIS_Z_COLOR, DefaultStemRadius, DefaultTipLength, DefaultTipRadius, glsafe, Slic3r::GUI::GLModel::is_initialized(), m_arrow, m_origin, M_PI, m_stem_length, Slic3r::GUI::GLModel::render(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GUI::stilized_arrow(), Slic3r::GLShaderProgram::stop_using(), and Slic3r::transform().
Referenced by Slic3r::GUI::Bed3D::render_axes().
set_origin()
void Slic3r::GUI::Bed3D::Axes::set_origin (const Vec3d & origin) inline
{ m_origin = origin; }
References m_origin.
Referenced by Slic3r::GUI::Bed3D::set_axes_mode(), and Slic3r::GUI::Bed3D::set_shape().
set_stem_length()
void Slic3r::GUI::Bed3D::Axes::set_stem_length (float length) inline
{
            m_stem_length = length;
            m_arrow.reset();
        }
References Slic3r::length(), m_arrow, m_stem_length, and Slic3r::GUI::GLModel::reset().
Referenced by Slic3r::GUI::Bed3D::set_shape().
Member Data Documentation
DefaultStemLength
const float Slic3r::GUI::Bed3D::Axes::DefaultStemLength = 25.0f static
DefaultStemRadius
const float Slic3r::GUI::Bed3D::Axes::DefaultStemRadius = 0.5f static
Referenced by render().
DefaultTipLength
const float Slic3r::GUI::Bed3D::Axes::DefaultTipLength = 5.0f static
Referenced by get_total_length(), and render().
DefaultTipRadius
const float Slic3r::GUI::Bed3D::Axes::DefaultTipRadius = 2.5f * Bed3D::Axes::DefaultStemRadius static
Referenced by Slic3r::GUI::Bed3D::calc_extended_bounding_box(), Slic3r::GUI::Plater::priv::load_files(), render(), and Slic3r::GUI::Plater::priv::set_bed_shape().
m_arrow
GLModel Slic3r::GUI::Bed3D::Axes::m_arrow private
Referenced by render(), and set_stem_length().
m_origin
Vec3d Slic3r::GUI::Bed3D::Axes::m_origin { Vec3d::Zero() } private
Referenced by get_origin(), render(), and set_origin().
m_stem_length
float Slic3r::GUI::Bed3D::Axes::m_stem_length { DefaultStemLength } private
Referenced by get_total_length(), render(), and set_stem_length().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DBed.hpp
src/slic3r/GUI/3DBed.cpp