OrcaSlicer: Slic3r::GUI::UnsavedChangesDialog Class Reference
Slic3r::GUI::UnsavedChangesDialog Class Reference
#include <src/slic3r/GUI/UnsavedChangesDialog.hpp>
Classes
struct PresetData
Public Types
enum ActionButtons {
TRANSFER = 1 , KEEP = 2 , SAVE = 4 , DONT_SAVE = 8 ,
REMEMBER_CHOISE = 0x10000
}
Public Member Functions
UnsavedChangesDialog (Preset::Type type, PresetCollection *dependent_presets, const std::string &new_selected_preset, bool no_transfer=false)
UnsavedChangesDialog (const wxString &caption, const wxString &header, const std::string &app_config_key, int act_buttons)
~UnsavedChangesDialog ()
int ShowModal ()
void build (Preset::Type type, PresetCollection *dependent_presets, const std::string &new_selected_preset, const wxString &header="")
void update (Preset::Type type, PresetCollection *dependent_presets, const std::string &new_selected_preset, const wxString &header)
void update_list ()
std::string subreplace (std::string resource_str, std::string sub_str, std::string new_str)
void update_tree (Preset::Type type, PresetCollection *presets)
void show_info_line (Action action, std::string preset_name="")
void update_config (Action action)
void close (Action action)
bool save (PresetCollection *dependent_presets, bool show_save_preset_dialog=true)
bool save_preset () const
bool transfer_changes () const
bool discard () const
const std::vector< UnsavedChangesDialog::PresetData > & get_names_and_types ()
bool get_save_to_project_option ()
std::string get_preset_name ()
std::vector< std::string > get_unselected_options (Preset::Type type)
std::vector< std::string > get_selected_options (Preset::Type type)
std::vector< std::string > get_selected_options ()
bool has_unselected_options ()
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
Protected Types
enum class Action { Undef , Transfer , Save , Discard }
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
void on_sys_color_changed () override
bool check_option_valid ()
Protected Attributes
wxPanel * m_top_line
wxPanel * m_panel_tab
wxPanel * m_table_top
wxPanel * title_block_middle
wxPanel * title_block_right
wxStaticText * static_temp_title
wxStaticText * static_oldv_title
wxStaticText * static_newv_title
wxBoxSizer * m_sizer_bottom
Button * m_save_btn { nullptr }
Button * m_transfer_btn { nullptr }
Button * m_discard_btn { nullptr }
Button * m_cancel_btn { nullptr }
wxStaticText * m_action_line { nullptr }
wxStaticText * m_info_line { nullptr }
wxScrolledWindow * m_scrolledWindow { nullptr }
bool m_has_long_strings { false }
int m_save_btn_id { wxID_ANY }
int m_move_btn_id { wxID_ANY }
int m_continue_btn_id { wxID_ANY }
std::string m_app_config_key
Action m_exit_action {Action::Undef}
Static Protected Attributes
static constexpr char ActTransfer [] = "transfer"
static constexpr char ActDiscard [] = "discard"
static constexpr char ActSave [] = "save"
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
std::vector< PresetItem > m_presetitems
std::vector< PresetData > names_and_types
int m_buttons { ActionButtons::TRANSFER | ActionButtons::SAVE }
std::string m_new_selected_preset_name
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Member Enumeration Documentation
Action
enum class Slic3r::GUI::UnsavedChangesDialog::Action strong protected
Enumerator
Undef
Transfer
Save
Discard
                      {
        Undef,
        Transfer, // Or KEEP
        Save,
        Discard,
    };
ActionButtons
enum Slic3r::GUI::UnsavedChangesDialog::ActionButtons
Enumerator
TRANSFER
KEEP
SAVE
DONT_SAVE
REMEMBER_CHOISE
                       {
        TRANSFER  = 1,
        KEEP      = 2,
        SAVE      = 4,
        DONT_SAVE = 8,
        REMEMBER_CHOISE = 0x10000
    };
Constructor & Destructor Documentation
UnsavedChangesDialog() [1/2]
Slic3r::GUI::UnsavedChangesDialog::UnsavedChangesDialog (Preset::Type type, PresetCollection * dependent_presets, const std::string & new_selected_preset, bool no_transfer = false)
    : m_new_selected_preset_name(new_selected_preset)
    , DPIDialog(static_cast<wxWindow *>(wxGetApp().mainframe),
                wxID_ANY,
                _L("Discard or Keep changes"),
                wxDefaultPosition,
                wxDefaultSize,
                wxCAPTION | wxCLOSE_BOX)
{
    if (new_selected_preset.empty() || no_transfer)
        m_buttons &= ~ActionButtons::TRANSFER;
    build(type, dependent_presets, new_selected_preset);
    this->CenterOnScreen();
    wxGetApp().UpdateDlgDarkUI(this);
}
References build(), m_buttons, and TRANSFER.
UnsavedChangesDialog() [2/2]
Slic3r::GUI::UnsavedChangesDialog::UnsavedChangesDialog (const wxString & caption, const wxString & header, const std::string & app_config_key, int act_buttons)
    : DPIDialog(static_cast<wxWindow *>(wxGetApp().mainframe),
                wxID_ANY,
                caption + ": " + _L("Unsaved Changes"),
                wxDefaultPosition,
                wxDefaultSize,
                wxCAPTION | wxCLOSE_BOX)
    , m_app_config_key(app_config_key)
    , m_buttons(act_buttons)
{
    build(Preset::TYPE_INVALID, nullptr, "", header);
    this->CenterOnScreen();
    wxGetApp().UpdateDlgDarkUI(this);
}
References build(), and Slic3r::Preset::TYPE_INVALID.
~UnsavedChangesDialog()
Slic3r::GUI::UnsavedChangesDialog::~UnsavedChangesDialog () inline
{};
Member Function Documentation
build()
void Slic3r::GUI::UnsavedChangesDialog::build (Preset::Type type, PresetCollection * dependent_presets, const std::string & new_selected_preset, const wxString & header = "")
{
    SetBackgroundColour(*wxWHITE);
    // icon
    std::string icon_path = (boost::format("%1%/images/OrcaSlicerTitle.ico") % resources_dir()).str();
    SetIcon(wxIcon(encode_path(icon_path.c_str()), wxBITMAP_TYPE_ICO));
    wxBoxSizer *m_sizer_main = new wxBoxSizer(wxVERTICAL);
    m_top_line = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    m_top_line->SetBackgroundColour(wxColour(166, 169, 170));
    m_sizer_main->Add(m_top_line, 0, wxEXPAND, 0);
    m_sizer_main->Add(0, 0, 0, wxTOP, 20);
    m_action_line = new wxStaticText(this, wxID_ANY, wxEmptyString, wxDefaultPosition, UNSAVE_CHANGE_DIALOG_ACTION_LINE_SIZE, 0);
    m_action_line->SetFont(::Label::Body_13);
    m_action_line->SetForegroundColour(GREY900);
    m_action_line->Wrap(-1);
    m_sizer_main->Add(m_action_line, 0, wxLEFT | wxRIGHT, 20);
    m_sizer_main->Add(0, 0, 0, wxTOP, 12);
    m_panel_tab = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(UNSAVE_CHANGE_DIALOG_SCROLL_WINDOW_SIZE.x, -1), wxTAB_TRAVERSAL);
    m_panel_tab->SetBackgroundColour(GREY200);
    wxBoxSizer *m_sizer_tab = new wxBoxSizer(wxVERTICAL);
    m_table_top = new wxPanel(m_panel_tab, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_table_top->SetBackgroundColour(wxColour(107, 107, 107));
    wxBoxSizer *m_sizer_top = new wxBoxSizer(wxHORIZONTAL);
    //m_sizer_top->Add(0, 0, 0, wxLEFT, UNSAVE_CHANGE_DIALOG_FIRST_VALUE_WIDTH);
    auto        m_panel_temp   = new wxPanel(m_table_top, wxID_ANY, wxDefaultPosition, wxSize(UNSAVE_CHANGE_DIALOG_FIRST_VALUE_WIDTH, -1), wxTAB_TRAVERSAL);
    wxBoxSizer *top_title_temp_v = new wxBoxSizer(wxVERTICAL);
    top_title_temp_v->SetMinSize(wxSize(UNSAVE_CHANGE_DIALOG_VALUE_WIDTH, -1));
    wxBoxSizer *top_title_temp_h = new wxBoxSizer(wxHORIZONTAL);
    static_temp_title            = new wxStaticText(m_panel_temp, wxID_ANY, _L("Settings"), wxDefaultPosition, wxDefaultSize, 0);
    static_temp_title->SetFont(::Label::Body_13);
    static_temp_title->Wrap(-1);
    static_temp_title->SetForegroundColour(*wxWHITE);
    top_title_temp_h->Add(static_temp_title, 0, wxALIGN_CENTER | wxBOTTOM | wxTOP, 5);
    top_title_temp_v->Add(top_title_temp_h, 1, wxALIGN_CENTER, 0);
    m_panel_temp->SetSizer(top_title_temp_v);
    m_panel_temp->Layout();
    m_sizer_top->Add(m_panel_temp, 1, wxALIGN_CENTER, 0);
    title_block_middle = new wxPanel(m_table_top, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    title_block_middle->SetBackgroundColour(wxColour(172, 172, 172));
    m_sizer_top->Add(title_block_middle, 0, wxBOTTOM | wxEXPAND | wxTOP, 2);
    auto m_panel_oldv = new wxPanel( m_table_top, wxID_ANY, wxDefaultPosition, wxSize(UNSAVE_CHANGE_DIALOG_VALUE_WIDTH,-1), wxTAB_TRAVERSAL );
    wxBoxSizer *top_title_oldv = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *top_title_oldv_h = new wxBoxSizer(wxHORIZONTAL);
    static_oldv_title = new wxStaticText(m_panel_oldv, wxID_ANY, _L("Old Value"), wxDefaultPosition, wxDefaultSize, 0);
    static_oldv_title->SetFont(::Label::Body_13);
    static_oldv_title->Wrap(-1);
    static_oldv_title->SetForegroundColour(*wxWHITE);
    top_title_oldv_h->Add(static_oldv_title, 0, wxALIGN_CENTER | wxBOTTOM | wxTOP, 5);
    top_title_oldv->Add(top_title_oldv_h, 1, wxALIGN_CENTER, 0);
    m_panel_oldv->SetSizer(top_title_oldv);
    m_panel_oldv->Layout();
    m_sizer_top->Add(m_panel_oldv, 0, wxALIGN_CENTER, 0);
    title_block_right = new wxPanel(m_table_top, wxID_ANY, wxDefaultPosition, wxSize(1, -1), wxTAB_TRAVERSAL);
    title_block_right->SetBackgroundColour(wxColour(172, 172, 172));
    m_sizer_top->Add(title_block_right, 0, wxBOTTOM | wxEXPAND | wxTOP, 2);
    auto m_panel_newv = new wxPanel( m_table_top, wxID_ANY, wxDefaultPosition, wxSize( UNSAVE_CHANGE_DIALOG_VALUE_WIDTH,-1 ), wxTAB_TRAVERSAL );
    wxBoxSizer *top_title_newv = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *top_title_newv_h = new wxBoxSizer(wxHORIZONTAL);
    static_newv_title = new wxStaticText(m_panel_newv, wxID_ANY, _L("New Value"), wxDefaultPosition, wxDefaultSize, 0);
    static_newv_title->SetFont(::Label::Body_13);
    static_newv_title->Wrap(-1);
    static_newv_title->SetForegroundColour(*wxWHITE);
    top_title_newv_h->Add(static_newv_title, 0, wxALIGN_CENTER | wxBOTTOM | wxTOP, 5);
    top_title_newv->Add(top_title_newv_h, 1, wxALIGN_CENTER, 0);
    m_panel_newv->SetSizer(top_title_newv);
    m_panel_newv->Layout();
    m_sizer_top->Add(m_panel_newv, 0, wxALIGN_CENTER, 0);
    //m_sizer_top->Add(top_title_newv, 1, wxALIGN_CENTER, 0);
    m_table_top->SetSizer(m_sizer_top);
    m_table_top->Layout();
    m_sizer_top->Fit(m_table_top);
    m_sizer_tab->Add(m_table_top, 1, 0, 0);
    m_scrolledWindow = new wxScrolledWindow(m_panel_tab, wxID_ANY, wxDefaultPosition, UNSAVE_CHANGE_DIALOG_SCROLL_WINDOW_SIZE,  wxNO_BORDER|wxVSCROLL);
    m_scrolledWindow->SetScrollRate(0, 5);
    m_scrolledWindow->SetBackgroundColour(GREY200);
    m_sizer_bottom = new wxBoxSizer(wxVERTICAL);
    m_sizer_bottom->Add(m_scrolledWindow, 1, wxEXPAND, 0);
    m_sizer_tab->Add(m_sizer_bottom, 0, wxEXPAND, 0);
    m_panel_tab->SetSizer(m_sizer_tab);
    m_panel_tab->Layout();
    m_sizer_tab->Fit(m_panel_tab);
    m_sizer_main->Add(m_panel_tab, 0, wxEXPAND | wxLEFT | wxRIGHT, 20);
    m_sizer_main->Add(0, 0, 0, wxTOP, 9);
   /* m_info_line = new wxStaticText(this, wxID_ANY, wxEmptyString, wxDefaultPosition, wxSize(-1, 44), 0);
     m_info_line->SetFont(::Label::Body_13);
     m_info_line->Wrap(-1);
     m_info_line->SetForegroundColour(wxColour(255, 111, 0));
     m_sizer_main->Add(m_info_line, 0, wxLEFT | wxRIGHT, 20);*/
    wxBoxSizer *m_sizer_button = new wxBoxSizer(wxHORIZONTAL);
    auto checkbox_sizer = new wxBoxSizer(wxHORIZONTAL);
    auto checkbox       = new ::CheckBox(this, wxID_APPLY);
    checkbox_sizer->Add(checkbox, 0, wxALL | wxALIGN_CENTER, FromDIP(2));
    auto checkbox_text = new wxStaticText(this, wxID_ANY, _L("Remember my choice."), wxDefaultPosition, wxDefaultSize, 0);
    checkbox_sizer->Add(checkbox_text, 0, wxALL | wxALIGN_CENTER, FromDIP(2));
    checkbox_text->SetFont(::Label::Body_13);
    checkbox_text->SetForegroundColour(StateColor::darkModeColorFor(wxColour("#323A3D")));
    m_sizer_button->Add(checkbox_sizer, 0, wxLEFT, FromDIP(22));
    checkbox_sizer->Show(bool(m_buttons & REMEMBER_CHOISE));
    m_sizer_button->Add(0, 0, 1, 0, 0);
     // Add Buttons
    wxFont      btn_font = this->GetFont().Scaled(1.4f);
    StateColor btn_bg_green(std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed), std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
                            std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    auto add_btn = [this, m_sizer_button, btn_font, dependent_presets, btn_bg_green](Button **btn, int &btn_id, const std::string &icon_name, Action close_act, const wxString &label,
                                                                              bool focus, bool process_enable = true) {
        *btn = new Button(this, _L(label));
        if (focus) {
            (*btn)->SetBackgroundColor(btn_bg_green);
            (*btn)->SetBorderColor(wxColour(0, 150, 136));
            (*btn)->SetTextColor(wxColour("#FFFFFE"));
        } else {
            (*btn)->SetTextColor(wxColour(107, 107, 107));
        }
        //(*btn)->SetMinSize(UNSAVE_CHANGE_DIALOG_BUTTON_SIZE);
        (*btn)->SetMinSize(wxSize(-1,-1));
        (*btn)->SetCornerRadius(FromDIP(12));
        (*btn)->Bind(wxEVT_BUTTON, [this, close_act, dependent_presets](wxEvent &) {
            bool save_names_and_types = close_act == Action::Save || (close_act == Action::Transfer && ActionButtons::KEEP & m_buttons);
            if (save_names_and_types && !save(dependent_presets, close_act == Action::Save)) return;
            close(close_act);
        });
        // if (process_enable) (*btn)->Bind(wxEVT_UPDATE_UI, [this](wxUpdateUIEvent &evt) { evt.Enable(m_tree->has_selection()); });
        (*btn)->Bind(wxEVT_LEAVE_WINDOW, [this](wxMouseEvent &e) {
            show_info_line(Action::Undef);
            e.Skip();
        });
        m_sizer_button->Add(*btn, 0, wxLEFT, 5);
    };
    // "Transfer" / "Keep" button
    if (ActionButtons::TRANSFER & m_buttons) {
        const PresetCollection* switched_presets = type == Preset::TYPE_INVALID ? nullptr : wxGetApp().get_tab(type)->get_presets();
        if (dependent_presets && switched_presets && (type == dependent_presets->type() ?
            dependent_presets->get_edited_preset().printer_technology() == dependent_presets->find_preset(new_selected_preset)->printer_technology() :
            switched_presets->get_edited_preset().printer_technology() == switched_presets->find_preset(new_selected_preset)->printer_technology()))
            add_btn(&m_transfer_btn, m_move_btn_id, "menu_paste", Action::Transfer, switched_presets->get_edited_preset().name == new_selected_preset ? _L("Transfer") : _L("Transfer"), true);
    }
    if (!m_transfer_btn && (ActionButtons::KEEP & m_buttons))
        add_btn(&m_transfer_btn, m_move_btn_id, "menu_paste", Action::Transfer, _L("Transfer"), true);
    { // "Don't save" / "Discard" button
        std::string btn_icon    = (ActionButtons::DONT_SAVE & m_buttons) ? "" : (dependent_presets || (ActionButtons::KEEP & m_buttons)) ? "blank_16" : "exit";
        wxString    btn_label   = (ActionButtons::DONT_SAVE & m_buttons) ? _L("Don't save") : _L("Discard");
        add_btn(&m_discard_btn, m_continue_btn_id, btn_icon, Action::Discard, btn_label, false);
    }
    // "Save" button
    if (ActionButtons::SAVE & m_buttons) add_btn(&m_save_btn, m_save_btn_id, "save", Action::Save, _L("Save"), false);
    /* ScalableButton *cancel_btn = new ScalableButton(this, wxID_CANCEL, "cross", _L("Cancel"), wxDefaultSize, wxDefaultPosition, wxBORDER_DEFAULT, true, 24);
      buttons->Add(cancel_btn, 1, wxLEFT | wxRIGHT, 5);
      cancel_btn->SetFont(btn_font);*/
    /* m_cancel_btn = new Button(this, _L("Cancel"));
     m_cancel_btn->SetTextColor(wxColour(107, 107, 107));
     m_cancel_btn->Bind(wxEVT_LEFT_DOWN, [this](wxEvent &) { this->EndModal(wxID_CANCEL); });
     m_cancel_btn->SetMinSize(UNSAVE_CHANGE_DIALOG_BUTTON_SIZE);
     m_cancel_btn->SetCornerRadius(12);
     m_sizer_button->Add(m_cancel_btn, 0, wxLEFT, 5);
     m_sizer_button->Add(0,0,0,wxRIGHT,20);*/
    if (!m_app_config_key.empty()) {}
    m_sizer_button->Add(0, 0, 0, wxRIGHT, 20);
    m_sizer_main->Add(m_sizer_button, 0, wxEXPAND | wxTOP, 6);
    m_sizer_main->Add(0, 0, 1, wxTOP, 18);
    SetSizer(m_sizer_main);
    Layout();
    Fit();
    Centre(wxBOTH);
    update(type, dependent_presets, new_selected_preset, header);
    //SetSizer(topSizer);
    //topSizer->SetSizeHints(this);
    show_info_line(Action::Undef);
}
References _L, Label::Body_13, close(), StateColor::darkModeColorFor(), Discard, DONT_SAVE, Slic3r::encode_path(), Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::get_edited_preset(), GREY200, GREY900, StateColor::Hovered, KEEP, m_action_line, m_app_config_key, m_buttons, m_continue_btn_id, m_discard_btn, m_move_btn_id, m_panel_tab, m_save_btn, m_save_btn_id, m_scrolledWindow, m_sizer_bottom, m_table_top, m_top_line, m_transfer_btn, Slic3r::Preset::name, StateColor::Normal, StateColor::Pressed, Slic3r::Preset::printer_technology(), REMEMBER_CHOISE, Slic3r::resources_dir(), Save, SAVE, save(), show_info_line(), static_newv_title, static_oldv_title, static_temp_title, title_block_middle, title_block_right, Transfer, TRANSFER, Slic3r::PresetCollection::type(), Slic3r::Preset::TYPE_INVALID, Undef, UNSAVE_CHANGE_DIALOG_ACTION_LINE_SIZE, UNSAVE_CHANGE_DIALOG_FIRST_VALUE_WIDTH, UNSAVE_CHANGE_DIALOG_SCROLL_WINDOW_SIZE, UNSAVE_CHANGE_DIALOG_VALUE_WIDTH, update(), wxEVT_BUTTON, Slic3r::GUI::wxMouseEvent, and wxStaticText.
Referenced by UnsavedChangesDialog(), and UnsavedChangesDialog().
check_option_valid()
bool Slic3r::GUI::UnsavedChangesDialog::check_option_valid () protected
{
    return true;
}
Referenced by close().
close()
void Slic3r::GUI::UnsavedChangesDialog::close (Action action)
{
    if (action == Action::Transfer) {
        check_option_valid();
    }
    m_exit_action = action;
    this->EndModal(wxID_CLOSE);
}
References check_option_valid(), m_exit_action, and Transfer.
Referenced by build().
discard()
bool Slic3r::GUI::UnsavedChangesDialog::discard () const inline
{ return m_exit_action == Action::Discard;  }
References Discard, and m_exit_action.
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
get_names_and_types()
const std::vector< UnsavedChangesDialog::PresetData > & Slic3r::GUI::UnsavedChangesDialog::get_names_and_types () inline
{ return names_and_types; }
References names_and_types.
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), and Slic3r::GUI::GUI_App::check_and_save_current_preset_changes().
get_preset_name()
std::string Slic3r::GUI::UnsavedChangesDialog::get_preset_name () inline
{ return names_and_types[0].name; }
References names_and_types.
Referenced by Slic3r::GUI::Tab::may_discard_current_dirty_preset().
get_save_to_project_option()
bool Slic3r::GUI::UnsavedChangesDialog::get_save_to_project_option () inline
{ return names_and_types[0].save_to_project; }
References names_and_types.
Referenced by Slic3r::GUI::Tab::may_discard_current_dirty_preset().
get_selected_options() [1/2]
std::vector< std::string > Slic3r::GUI::UnsavedChangesDialog::get_selected_options () inline
{
        //return m_tree->selected_options();
        std::vector<std::string> tmp;
        for (int i = 0; i < m_presetitems.size(); i++)
        {
           tmp.push_back(m_presetitems[i].opt_key);
        }
        return tmp;
    }
References m_presetitems.
get_selected_options() [2/2]
std::vector< std::string > Slic3r::GUI::UnsavedChangesDialog::get_selected_options (Preset::Type type) inline
{
        //return m_tree->options(type, true);
         std::vector<std::string> tmp;
        for (int i = 0; i < m_presetitems.size(); i++) {
            if (m_presetitems[i].type == type) {
                tmp.push_back(m_presetitems[i].opt_key);
            }
        }
        return tmp;
    }
References m_presetitems.
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), and Slic3r::GUI::Tab::may_discard_current_dirty_preset().
get_unselected_options()
std::vector< std::string > Slic3r::GUI::UnsavedChangesDialog::get_unselected_options (Preset::Type type) inline
{ /* return m_tree->options(type, false);*/return std::vector<std::string>();}
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::GUI_App::check_and_save_current_preset_changes(), and Slic3r::GUI::Tab::may_discard_current_dirty_preset().
has_unselected_options()
bool Slic3r::GUI::UnsavedChangesDialog::has_unselected_options () inline
{ /*return m_tree->has_unselected_options();*/return false;}
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_dpi_changed()
void Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    int em = em_unit();
    msw_buttons_rescale(this, em, { wxID_CANCEL, m_move_btn_id, m_continue_btn_id });
    for (auto btn : {m_transfer_btn, m_discard_btn, m_discard_btn})
        if (btn) btn->SetMinSize(UNSAVE_CHANGE_DIALOG_BUTTON_SIZE);
    //m_cancel_btn->SetMinSize(UNSAVE_CHANGE_DIALOG_BUTTON_SIZE);
    const wxSize& size = wxSize(70 * em, 30 * em);
    SetMinSize(size);
    //m_tree->Rescale(em);
    Fit();
    Refresh();
}
References Slic3r::GUI::DPIAware< P >::em_unit(), m_continue_btn_id, m_discard_btn, m_move_btn_id, m_transfer_btn, msw_buttons_rescale(), size, and UNSAVE_CHANGE_DIALOG_BUTTON_SIZE.
on_sys_color_changed()
void Slic3r::GUI::UnsavedChangesDialog::on_sys_color_changed () override protected virtual
Reimplemented from Slic3r::GUI::DPIAware< P >.
{
    //for (auto btn : { m_save_btn, m_transfer_btn, m_discard_btn } )
        //btn->msw_rescale();
    // msw_rescale updates just icons, so use it
    //m_tree->Rescale();
    Refresh();
}
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
save()
bool Slic3r::GUI::UnsavedChangesDialog::save (PresetCollection * dependent_presets, bool show_save_preset_dialog = true)
{
    names_and_types.clear();
    // save one preset
    if (dependent_presets) {
        const Preset& preset = dependent_presets->get_edited_preset();
        std::string name = preset.name;
        // for system/default/external presets we should take an edited name
        //BBS: add project embedded preset logic and refine is_external
        bool save_to_project = false;
        if (preset.is_system || preset.is_default) {
        //if (preset.is_system || preset.is_default || preset.is_external) {
            SavePresetDialog save_dlg(this, preset.type);
            if (save_dlg.ShowModal() != wxID_OK) {
                m_exit_action = Action::Discard;
                return false;
            }
            name = save_dlg.get_name();
            save_to_project = save_dlg.get_save_to_project_selection(preset.type);
        }
        //BBS: add project embedded preset relate logic
        PresetData preset_data(name, preset.type, save_to_project);
        names_and_types.emplace_back(preset_data);
        //names_and_types.emplace_back(make_pair(name, preset.type));
    }
    // save all presets
    else
    {
        std::vector<Preset::Type> types_for_save;
        PrinterTechnology printer_technology = wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology();
        for (Tab* tab : wxGetApp().tabs_list)
            if (tab->supports_printer_technology(printer_technology) && tab->current_preset_is_dirty()) {
                const Preset& preset = tab->get_presets()->get_edited_preset();
                //BBS: add project embedded preset logic and refine is_external
                if (preset.is_system || preset.is_default)
                //if (preset.is_system || preset.is_default || preset.is_external)
                    types_for_save.emplace_back(preset.type);
                //BBS: add project embedded preset relate logic
                PresetData preset_data(preset.name, preset.type, preset.is_project_embedded);
                names_and_types.emplace_back(preset_data);
                //names_and_types.emplace_back(make_pair(preset.name, preset.type));
            }
        if (show_save_preset_dialog && !types_for_save.empty()) {
            SavePresetDialog save_dlg(this, types_for_save);
            if (save_dlg.ShowModal() != wxID_OK) {
                m_exit_action = Action::Discard;
                return false;
            }
            //BBS: add project embedded preset relate logic
            for (PresetData& nt : names_and_types) {
                const std::string& name = save_dlg.get_name(nt.type);
                if (!name.empty())
                    nt.name = name;
                nt.save_to_project = save_dlg.get_save_to_project_selection(nt.type);
            }
            //for (std::pair<std::string, Preset::Type>& nt : names_and_types) {
            //    const std::string& name = save_dlg.get_name(nt.second);
            //    if (!name.empty())
            //        nt.first = name;
            //}
        }
    }
    return true;
}
References Discard, Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::SavePresetDialog::get_name(), Slic3r::GUI::SavePresetDialog::get_save_to_project_selection(), Slic3r::Preset::is_default, Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_system, m_exit_action, Slic3r::Preset::name, names_and_types, Slic3r::GUI::printer_technology(), Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::Preset::type.
Referenced by build().
save_preset()
bool Slic3r::GUI::UnsavedChangesDialog::save_preset () const inline
{ return m_exit_action == Action::Save;     }
References m_exit_action, and Save.
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::GUI_App::check_and_save_current_preset_changes(), and Slic3r::GUI::Tab::may_discard_current_dirty_preset().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
show_info_line()
void Slic3r::GUI::UnsavedChangesDialog::show_info_line (Action action, std::string preset_name = "")
{
    return;
    if (action == Action::Undef && !m_has_long_strings)
        m_info_line->SetLabel(wxEmptyString);
    else {
        wxString text;
        if (action == Action::Undef)
            text = _L("Click the right mouse button to display the full text.");
        else if (action == Action::Discard)
            text = ActionButtons::DONT_SAVE & m_buttons ? _L("All changes will not be saved") :_L("All changes will be discarded.");
        else {
            if (preset_name.empty())
                text = action == Action::Save           ? _L("Save the selected options.") :
                       ActionButtons::KEEP & m_buttons  ? _L("Keep the selected options.") :
                                                          _L("Transfer the selected options to the newly selected preset.");
            else
                text = format_wxstr(
                    action == Action::Save ?
                        _L("Save the selected options to preset \n\"%1%\".") :
                        _L("Transfer the selected options to the newly selected preset \n\"%1%\"."),
                    preset_name);
            //text += "\n" + _L("Unselected options will be reverted.");
        }
        m_info_line->SetLabel(text);
        m_info_line->Show();
    }
    //Layout();
    //Refresh();
}
References _L, Discard, DONT_SAVE, Slic3r::GUI::format_wxstr(), KEEP, m_buttons, m_has_long_strings, m_info_line, Save, and Undef.
Referenced by build(), and update().
ShowModal()
int Slic3r::GUI::UnsavedChangesDialog::ShowModal () inline
{
    auto choise_key = "save_preset_choise";
    auto choise     = wxGetApp().app_config->get(choise_key);
    long result = 0;
    if ((m_buttons & REMEMBER_CHOISE) && !choise.empty() && wxString(choise).ToLong(&result) && (1 << result) & (m_buttons | DONT_SAVE)) {
        m_exit_action = Action(result);
        return 0;
    }
    int r = wxDialog::ShowModal();
    if (r != wxID_CANCEL && dynamic_cast<::CheckBox*>(FindWindowById(wxID_APPLY))->GetValue()) {
        wxGetApp().app_config->set(choise_key, std::to_string(int(m_exit_action)));
    }
    return r;
}
References DONT_SAVE, m_buttons, m_exit_action, and REMEMBER_CHOISE.
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::GUI_App::check_and_save_current_preset_changes(), and Slic3r::GUI::Tab::may_discard_current_dirty_preset().
subreplace()
std::string Slic3r::GUI::UnsavedChangesDialog::subreplace (std::string resource_str, std::string sub_str, std::string new_str)
{
    std::string            dst_str = resource_str;
    std::string::size_type pos     = 0;
    while ((pos = dst_str.find(sub_str)) != std::string::npos)
    {
        dst_str.replace(pos, sub_str.length(), new_str);
    }
    return dst_str;
}
Referenced by update_list().
transfer_changes()
bool Slic3r::GUI::UnsavedChangesDialog::transfer_changes () const inline
{ return m_exit_action == Action::Transfer; }
References m_exit_action, and Transfer.
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), and Slic3r::GUI::Tab::may_discard_current_dirty_preset().
update()
void Slic3r::GUI::UnsavedChangesDialog::update (Preset::Type type, PresetCollection * dependent_presets, const std::string & new_selected_preset, const wxString & header)
{
    PresetCollection* presets = dependent_presets;
    // activate buttons and labels
    if (m_save_btn)
        m_save_btn->Bind(wxEVT_ENTER_WINDOW, [this, presets](wxMouseEvent &e) {
            show_info_line(Action::Save, presets ? presets->get_selected_preset().name : "");
            e.Skip();
        });
    if (m_transfer_btn) {
        bool is_empty_name = dependent_presets && type != dependent_presets->type();
        m_transfer_btn->Bind(wxEVT_ENTER_WINDOW, [this, new_selected_preset, is_empty_name](wxMouseEvent& e) { show_info_line(Action::Transfer, is_empty_name ? "" : new_selected_preset); e.Skip(); });
    }
    if (m_discard_btn)
        m_discard_btn ->Bind(wxEVT_ENTER_WINDOW, [this]                                    (wxMouseEvent& e) { show_info_line(Action::Discard); e.Skip(); });
    if (type == Preset::TYPE_INVALID) {
        PrinterTechnology printer_technology = wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology();
        int presets_cnt = 0;
        for (Tab* tab : wxGetApp().tabs_list)
            if (tab->supports_printer_technology(printer_technology) && tab->current_preset_is_dirty())
                presets_cnt++;
        /*m_action_line->SetLabel((header.IsEmpty() ? "" : header + "\n\n") +
                                _L_PLURAL("The following preset was modified",
                                          "The following presets were modified", presets_cnt));*/
    }
    else {
        wxString action_msg;
        if (type == dependent_presets->type()) {
            action_msg = format_wxstr(_L("Preset \"%1%\" contains the following unsaved changes:"), presets->get_edited_preset().name);
        }
        else {
            action_msg = format_wxstr(type == Preset::TYPE_PRINTER ?
                _L("Preset \"%1%\" is not compatible with the new printer profile and it contains the following unsaved changes:") :
                _L("Preset \"%1%\" is not compatible with the new process profile and it contains the following unsaved changes:"),
                presets->get_edited_preset().name);
        }
        //m_action_line->SetLabel(action_msg);
    }
    wxString action_msg;
    if (dependent_presets)
        action_msg = format_wxstr(_L("You have changed some settings of preset \"%1%\". \nWould you like to keep these changed settings (new value) after switching preset?"),
                              dependent_presets->get_edited_preset().name);
    else
        action_msg = format_wxstr(_L("You have changed some preset settings. \nWould you like to keep these changed settings (new value) after switching preset?"));
    m_action_line->SetLabel(action_msg);
    update_tree(type, presets);
    update_list();
}
References _L, Discard, Slic3r::GUI::format_wxstr(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset(), m_action_line, m_discard_btn, m_save_btn, m_transfer_btn, Slic3r::Preset::name, Slic3r::GUI::printer_technology(), Save, show_info_line(), Transfer, Slic3r::PresetCollection::type(), Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINTER, update_list(), update_tree(), and Slic3r::GUI::wxMouseEvent.
Referenced by build().
update_config()
void Slic3r::GUI::UnsavedChangesDialog::update_config (Action action)
update_list()
void Slic3r::GUI::UnsavedChangesDialog::update_list ()
{
    std::map<wxString, std::vector<PresetItem>> class_g_list;
    std::map<wxString, std::vector<wxString>>   class_c_list;
    // group
    for (auto i = 0; i < m_presetitems.size(); i++) {
        if (class_g_list.count(m_presetitems[i].group_name) <= 0) {
            std::vector<PresetItem> vp;
            vp.push_back(m_presetitems[i]);
            class_g_list.emplace(m_presetitems[i].group_name, vp);
        } else {
            //for (auto iter = class_g_list.begin(); iter != class_g_list.end(); iter++) iter->second.push_back(m_presetitems[i]);
            class_g_list[m_presetitems[i].group_name].push_back(m_presetitems[i]);
        }
    }
    // category
    for (auto i = 0; i < m_presetitems.size(); i++) {
        if (class_c_list.count(m_presetitems[i].category_name) <= 0) {
            std::vector<wxString> vp;
            vp.push_back(m_presetitems[i].group_name);
            class_c_list.emplace(m_presetitems[i].category_name, vp);
        } else {
            /*for (auto iter = class_c_list.begin(); iter != class_c_list.end(); iter++)
                iter->second.push_back(m_presetitems[i].group_name);*/
            //class_c_list[m_presetitems[i].category_name].push_back(m_presetitems[i].group_name);
            std::vector<wxString>::iterator it;
            it = find(class_c_list[m_presetitems[i].category_name].begin(), class_c_list[m_presetitems[i].category_name].end(), m_presetitems[i].group_name);
            if (it == class_c_list[m_presetitems[i].category_name].end()) {
                class_c_list[m_presetitems[i].category_name].push_back(m_presetitems[i].group_name);
            }
        }
    }
    auto m_listsizer = new wxBoxSizer(wxVERTICAL);
    for (auto iter = class_c_list.begin(); iter != class_c_list.end(); iter++) {
        //category
        auto panel_category = new wxPanel(m_scrolledWindow, wxID_ANY, wxDefaultPosition, wxSize(-1, UNSAVE_CHANGE_DIALOG_ITEM_HEIGHT), wxTAB_TRAVERSAL);
        panel_category->SetBackgroundColour(GREY300);
        wxBoxSizer *sizer_category   = new wxBoxSizer(wxHORIZONTAL);
        wxBoxSizer *sizer_category_v = new wxBoxSizer(wxHORIZONTAL);
        auto text_category = new wxStaticText(panel_category, wxID_ANY, iter->first, wxDefaultPosition, wxSize(-1, -1), 0);
        text_category->SetFont(::Label::Head_13);
        text_category->SetForegroundColour(GREY900);
        text_category->Wrap(-1);
        sizer_category_v->Add(text_category, 0, wxALIGN_CENTER | wxLEFT, 23);
        sizer_category->Add(sizer_category_v, 1, wxEXPAND, 0);
        panel_category->SetSizer(sizer_category);
        panel_category->Layout();
        m_listsizer->Add(panel_category, 0, wxEXPAND, 0);
        /*auto item_line = new wxStaticLine(list, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_HORIZONTAL);
        item_line->SetForegroundColour(wxColour(206, 206, 206));
        item_line->SetBackgroundColour(wxColour(206, 206, 206));
        sizer_list->Add(item_line, 0, wxALL, 0); */
        // isset group
        for (auto i = 0; i < iter->second.size(); i++) {
            auto gname = iter->second[i];
            for (auto g = 0; g < class_g_list[gname].size(); g++) {
                 //first group
                // if (g == 0) {
                //    auto citem_title = new wxStaticText(citem, wxID_ANY, gname, wxDefaultPosition, wxDefaultSize, 0);
                //    //citem_title->SetForegroundColour(GREY900);
                //    auto block_title = new wxWindow(citem, wxID_ANY, wxDefaultPosition, wxSize(0, 0));
                //
                //    sizer_citem->Add(block_title, 0, wxEXPAND | wxLEFT, 20);
                //    sizer_citem->Add(citem_title, 0, wxALL, (list_item_height - citem_title->GetSize().GetHeight()) / 2);
                //}
                auto data = class_g_list[gname][g];
                auto panel_item = new wxWindow(m_scrolledWindow, -1, wxDefaultPosition, wxSize(-1, UNSAVE_CHANGE_DIALOG_ITEM_HEIGHT));
                panel_item->SetBackgroundColour(GREY200);
                wxBoxSizer *sizer_item = new wxBoxSizer(wxHORIZONTAL);
                auto panel_left = new wxPanel(panel_item, wxID_ANY, wxDefaultPosition, wxSize(UNSAVE_CHANGE_DIALOG_FIRST_VALUE_WIDTH , -1), wxTAB_TRAVERSAL);
                panel_left->SetBackgroundColour(GREY200);
                wxBoxSizer *sizer_left_v = new wxBoxSizer(wxVERTICAL);
                auto text_left = new wxStaticText(panel_left, wxID_ANY, data.option_name, wxDefaultPosition, wxSize(-1, -1), 0);
                text_left->SetFont(::Label::Body_13);
                text_left->Wrap(-1);
                text_left->SetForegroundColour(GREY700);
                text_left->SetForegroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_INFOTEXT));
                sizer_left_v->Add(text_left, 0, wxLEFT, 37 );
                panel_left->SetSizer(sizer_left_v);
                panel_left->Layout();
                sizer_item->Add(panel_left, 0, wxALIGN_CENTER, 0);
                auto        panel_oldv  = new wxPanel(panel_item, wxID_ANY, wxDefaultPosition, wxSize(UNSAVE_CHANGE_DIALOG_VALUE_WIDTH, -1), wxTAB_TRAVERSAL);
                wxBoxSizer *sizer_old_v = new wxBoxSizer(wxVERTICAL);
                data.old_value = subreplace(data.old_value.ToStdString(), "\n", " ");
                auto text_oldv = new wxStaticText(panel_oldv, wxID_ANY, data.old_value, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
                text_oldv->SetFont(::Label::Body_13);
                text_oldv->Wrap(-1);
                text_oldv->SetForegroundColour(GREY700);
                sizer_old_v->Add(text_oldv, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT, 5);
                panel_oldv->SetSizer(sizer_old_v);
                panel_oldv->Layout();
                sizer_item->Add(panel_oldv, 0, wxALIGN_CENTER, 0);
                auto        panel_newv  = new wxPanel(panel_item, wxID_ANY, wxDefaultPosition, wxSize(UNSAVE_CHANGE_DIALOG_VALUE_WIDTH, -1), wxTAB_TRAVERSAL);
                wxBoxSizer *sizer_new_v = new wxBoxSizer(wxVERTICAL);
                data.new_value = subreplace(data.new_value.ToStdString(), "\n", " ");
                auto text_newv = new wxStaticText(panel_newv, wxID_ANY, data.new_value, wxDefaultPosition, wxDefaultSize, wxST_ELLIPSIZE_END);
                text_newv->SetFont(::Label::Body_13);
                text_newv->Wrap(-1);
                text_newv->SetForegroundColour(GREY700);
                sizer_new_v->Add(text_newv, 0, wxALIGN_CENTER|wxLEFT|wxRIGHT, 5);
                panel_newv->SetSizer(sizer_new_v);
                panel_newv->Layout();
                sizer_item->Add(panel_newv, 0, wxALIGN_CENTER, 0);
                panel_item->SetSizer(sizer_item);
                panel_item->Layout();
                m_listsizer->Add(panel_item, 0, wxEXPAND, 0);
                //    auto item_line = new wxStaticLine(list, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxLI_HORIZONTAL);
                //    item_line->SetForegroundColour(wxColour(206, 206, 206));
                //    item_line->SetBackgroundColour(wxColour(206, 206, 206));
                //    sizer_list->Add(item_line, 0, wxALL, 0);
            }
        }
    }
       m_scrolledWindow->SetSizer(m_listsizer);
    // m_scrolledWindow->Layout();
}
References Label::Body_13, end, GREY200, GREY300, GREY700, GREY900, Label::Head_13, m_presetitems, m_scrolledWindow, subreplace(), UNSAVE_CHANGE_DIALOG_FIRST_VALUE_WIDTH, UNSAVE_CHANGE_DIALOG_ITEM_HEIGHT, UNSAVE_CHANGE_DIALOG_VALUE_WIDTH, and wxStaticText.
Referenced by update().
update_tree()
void Slic3r::GUI::UnsavedChangesDialog::update_tree (Preset::Type type, PresetCollection * presets)
{
    Search::OptionsSearcher& searcher = wxGetApp().sidebar().get_searcher();
    searcher.sort_options_by_key();
    // list of the presets with unsaved changes
    std::vector<PresetCollection*> presets_list;
    if (type == Preset::TYPE_INVALID)
    {
        PrinterTechnology printer_technology = wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology();
        for (Tab* tab : wxGetApp().tabs_list)
            if (tab->supports_printer_technology(printer_technology) && tab->current_preset_is_dirty())
                presets_list.emplace_back(tab->get_presets());
    }
    else
        presets_list.emplace_back(presets_);
    // Display a dialog showing the dirty options in a human readable form.
    for (PresetCollection* presets : presets_list)
    {
        const DynamicPrintConfig& old_config = presets->get_selected_preset().config;
        const PrinterTechnology&  old_pt     = presets->get_selected_preset().printer_technology();
        const DynamicPrintConfig& new_config = presets->get_edited_preset().config;
        type = presets->type();
        const std::map<wxString, std::string>& category_icon_map = wxGetApp().get_tab(type)->get_category_icon_map();
        //m_tree->model->AddPreset(type, from_u8(presets->get_edited_preset().name), old_pt);
        // Collect dirty options.
        const bool deep_compare = (type == Preset::TYPE_PRINTER || type == Preset::TYPE_SLA_MATERIAL);
        auto dirty_options = presets->current_dirty_options(deep_compare);
        // process changes of extruders count
        if (type == Preset::TYPE_PRINTER && old_pt == ptFFF &&
            old_config.opt<ConfigOptionStrings>("extruder_colour")->values.size() != new_config.opt<ConfigOptionStrings>("extruder_colour")->values.size()) {
            wxString local_label = _L("Extruders count");
            wxString old_val = from_u8((boost::format("%1%") % old_config.opt<ConfigOptionStrings>("extruder_colour")->values.size()).str());
            wxString new_val = from_u8((boost::format("%1%") % new_config.opt<ConfigOptionStrings>("extruder_colour")->values.size()).str());
            //BBS: the page "General" changed to "Basic information" instead
            //m_tree->Append("extruders_count", type, _L("General"), _L("Capabilities"), local_label, old_val, new_val, category_icon_map.at("Basic information"));
            //m_tree->Append("extruders_count", type, _L("General"), _L("Capabilities"), local_label, old_val, new_val, category_icon_map.at("General"));
            PresetItem pi = {type, "extruders_count", _L("General"), _L("Capabilities"), local_label, old_val, new_val};
            m_presetitems.push_back(pi);
        }
        for (const std::string& opt_key : dirty_options) {
            const Search::Option& option = searcher.get_option(opt_key, type);
            if (option.opt_key() != opt_key) {
                // When founded option isn't the correct one.
                // It can be for dirty_options: "default_print_profile", "printer_model", "printer_settings_id",
                // because of they don't exist in searcher
                continue;
            }
            /*m_tree->Append(opt_key, type, option.category_local, option.group_local, option.label_local,
                get_string_value(opt_key, old_config), get_string_value(opt_key, new_config), category_icon_map.at(option.category));*/
            //PresetItem pi = {opt_key, type, 1983};
            //m_presetitems.push_back()
            PresetItem pi = {type, opt_key, option.category_local, option.group_local, option.label_local, get_string_value(opt_key, old_config), get_string_value(opt_key, new_config)};
            m_presetitems.push_back(pi);
        }
    }
    // Revert sort of searcher back
    searcher.sort_options_by_label();
}
References _L, Slic3r::Search::Option::category_local, Slic3r::GUI::from_u8(), Slic3r::Search::OptionsSearcher::get_option(), Slic3r::GUI::get_string_value(), Slic3r::Search::Option::group_local, Slic3r::Search::Option::label_local, m_presetitems, Slic3r::DynamicConfig::opt(), Slic3r::Search::Option::opt_key(), Slic3r::GUI::printer_technology(), Slic3r::ptFFF, Slic3r::ConfigOptionVector< T >::size(), Slic3r::Search::OptionsSearcher::sort_options_by_key(), Slic3r::Search::OptionsSearcher::sort_options_by_label(), Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, and Slic3r::ConfigOptionVector< T >::values.
Referenced by update().
Member Data Documentation
ActDiscard
constexpr char Slic3r::GUI::UnsavedChangesDialog::ActDiscard[] = "discard" static constexpr protected
ActSave
constexpr char Slic3r::GUI::UnsavedChangesDialog::ActSave[] = "save" static constexpr protected
ActTransfer
constexpr char Slic3r::GUI::UnsavedChangesDialog::ActTransfer[] = "transfer" static constexpr protected
m_action_line
wxStaticText* Slic3r::GUI::UnsavedChangesDialog::m_action_line { nullptr } protected
Referenced by build(), and update().
m_app_config_key
std::string Slic3r::GUI::UnsavedChangesDialog::m_app_config_key protected
Referenced by build().
m_buttons
int Slic3r::GUI::UnsavedChangesDialog::m_buttons { ActionButtons::TRANSFER | ActionButtons::SAVE } private
Referenced by UnsavedChangesDialog(), build(), show_info_line(), and ShowModal().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_cancel_btn
Button* Slic3r::GUI::UnsavedChangesDialog::m_cancel_btn { nullptr } protected
m_continue_btn_id
int Slic3r::GUI::UnsavedChangesDialog::m_continue_btn_id { wxID_ANY } protected
Referenced by build(), and on_dpi_changed().
m_discard_btn
Button* Slic3r::GUI::UnsavedChangesDialog::m_discard_btn { nullptr } protected
Referenced by build(), on_dpi_changed(), and update().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_exit_action
Action Slic3r::GUI::UnsavedChangesDialog::m_exit_action {Action::Undef} protected
Referenced by close(), discard(), save(), save_preset(), ShowModal(), and transfer_changes().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_has_long_strings
bool Slic3r::GUI::UnsavedChangesDialog::m_has_long_strings { false } protected
Referenced by show_info_line().
m_info_line
wxStaticText* Slic3r::GUI::UnsavedChangesDialog::m_info_line { nullptr } protected
Referenced by show_info_line().
m_move_btn_id
int Slic3r::GUI::UnsavedChangesDialog::m_move_btn_id { wxID_ANY } protected
Referenced by build(), and on_dpi_changed().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_new_selected_preset_name
std::string Slic3r::GUI::UnsavedChangesDialog::m_new_selected_preset_name private
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_panel_tab
wxPanel* Slic3r::GUI::UnsavedChangesDialog::m_panel_tab protected
Referenced by build().
m_presetitems
std::vector<PresetItem> Slic3r::GUI::UnsavedChangesDialog::m_presetitems private
Referenced by get_selected_options(), get_selected_options(), update_list(), and update_tree().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_save_btn
Button* Slic3r::GUI::UnsavedChangesDialog::m_save_btn { nullptr } protected
Referenced by build(), and update().
m_save_btn_id
int Slic3r::GUI::UnsavedChangesDialog::m_save_btn_id { wxID_ANY } protected
Referenced by build().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_scrolledWindow
wxScrolledWindow* Slic3r::GUI::UnsavedChangesDialog::m_scrolledWindow { nullptr } protected
Referenced by build(), and update_list().
m_sizer_bottom
wxBoxSizer* Slic3r::GUI::UnsavedChangesDialog::m_sizer_bottom protected
Referenced by build().
m_table_top
wxPanel* Slic3r::GUI::UnsavedChangesDialog::m_table_top protected
Referenced by build().
m_top_line
wxPanel* Slic3r::GUI::UnsavedChangesDialog::m_top_line protected
Referenced by build().
m_transfer_btn
Button* Slic3r::GUI::UnsavedChangesDialog::m_transfer_btn { nullptr } protected
Referenced by build(), on_dpi_changed(), and update().
names_and_types
std::vector<PresetData> Slic3r::GUI::UnsavedChangesDialog::names_and_types private
Referenced by get_names_and_types(), get_preset_name(), get_save_to_project_option(), and save().
static_newv_title
wxStaticText* Slic3r::GUI::UnsavedChangesDialog::static_newv_title protected
Referenced by build().
static_oldv_title
wxStaticText* Slic3r::GUI::UnsavedChangesDialog::static_oldv_title protected
Referenced by build().
static_temp_title
wxStaticText* Slic3r::GUI::UnsavedChangesDialog::static_temp_title protected
Referenced by build().
title_block_middle
wxPanel* Slic3r::GUI::UnsavedChangesDialog::title_block_middle protected
Referenced by build().
title_block_right
wxPanel* Slic3r::GUI::UnsavedChangesDialog::title_block_right protected
Referenced by build().
The documentation for this class was generated from the following files:
src/slic3r/GUI/UnsavedChangesDialog.hpp
src/slic3r/GUI/UnsavedChangesDialog.cpp