OrcaSlicer: Slic3r::GUI::MachineObjectPanel Class Reference
Slic3r::GUI::MachineObjectPanel Class Reference
#include <src/slic3r/GUI/SelectMachine.hpp>
Public Member Functions
MachineObjectPanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL, const wxString &name=wxEmptyString)
~MachineObjectPanel ()
void show_bind_dialog ()
void set_printer_state (PrinterState state)
void show_printer_bind (bool show, PrinterBindState state)
void show_edit_printer_name (bool show)
void update_machine_info (MachineObject *info, bool is_my_devices=false)
Protected Member Functions
void OnPaint (wxPaintEvent &event)
void render (wxDC &dc)
void doRender (wxDC &dc)
void on_mouse_enter (wxMouseEvent &evt)
void on_mouse_leave (wxMouseEvent &evt)
void on_mouse_left_up (wxMouseEvent &evt)
Protected Attributes
wxStaticBitmap * m_bitmap_info
wxStaticBitmap * m_bitmap_bind
Private Attributes
bool m_is_my_devices {false}
bool m_show_edit {false}
bool m_show_bind {false}
bool m_hover {false}
PrinterBindState m_bind_state
PrinterState m_state
ScalableBitmap m_unbind_img
ScalableBitmap m_edit_name_img
ScalableBitmap m_select_unbind_img
ScalableBitmap m_printer_status_offline
ScalableBitmap m_printer_status_busy
ScalableBitmap m_printer_status_idle
ScalableBitmap m_printer_status_lock
ScalableBitmap m_printer_in_lan
MachineObject * m_info
Detailed Description
Constructor & Destructor Documentation
MachineObjectPanel()
Slic3r::GUI::MachineObjectPanel::MachineObjectPanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL, const wxString & name = wxEmptyString)
{
    wxPanel::Create(parent, id, pos, SELECT_MACHINE_ITEM_SIZE, style, name);
    Bind(wxEVT_PAINT, &MachineObjectPanel::OnPaint, this);
    SetBackgroundColour(StateColor::darkModeColorFor(*wxWHITE));
    m_unbind_img        = ScalableBitmap(this, "unbind", 18);
    m_edit_name_img     = ScalableBitmap(this, "edit_button", 18);
    m_select_unbind_img = ScalableBitmap(this, "unbind_selected", 18);
    m_printer_status_offline = ScalableBitmap(this, "printer_status_offline", 12);
    m_printer_status_busy    = ScalableBitmap(this, "printer_status_busy", 12);
    m_printer_status_idle    = ScalableBitmap(this, "printer_status_idle", 12);
    m_printer_status_lock    = ScalableBitmap(this, "printer_status_lock", 16);
    m_printer_in_lan         = ScalableBitmap(this, "printer_in_lan", 16);
    this->Bind(wxEVT_ENTER_WINDOW, &MachineObjectPanel::on_mouse_enter, this);
    this->Bind(wxEVT_LEAVE_WINDOW, &MachineObjectPanel::on_mouse_leave, this);
    this->Bind(wxEVT_LEFT_UP, &MachineObjectPanel::on_mouse_left_up, this);
}
References StateColor::darkModeColorFor(), m_edit_name_img, m_printer_in_lan, m_printer_status_busy, m_printer_status_idle, m_printer_status_lock, m_printer_status_offline, m_select_unbind_img, m_unbind_img, on_mouse_enter(), on_mouse_leave(), on_mouse_left_up(), OnPaint(), SELECT_MACHINE_ITEM_SIZE, and style.
~MachineObjectPanel()
Slic3r::GUI::MachineObjectPanel::~MachineObjectPanel ()
{}
Member Function Documentation
doRender()
void Slic3r::GUI::MachineObjectPanel::doRender (wxDC & dc) protected
{
    auto   left = 10;
    wxSize size = GetSize();
    dc.SetPen(*wxTRANSPARENT_PEN);
    auto dwbitmap = m_printer_status_offline;
    if (m_state == PrinterState::IDLE) { dwbitmap = m_printer_status_idle; }
    if (m_state == PrinterState::BUSY) { dwbitmap = m_printer_status_busy; }
    if (m_state == PrinterState::OFFLINE) { dwbitmap = m_printer_status_offline; }
    if (m_state == PrinterState::LOCK) { dwbitmap = m_printer_status_lock; }
    if (m_state == PrinterState::IN_LAN) { dwbitmap = m_printer_in_lan; }
    // dc.DrawCircle(left, size.y / 2, 3);
    dc.DrawBitmap(dwbitmap.bmp(), wxPoint(left, (size.y - dwbitmap.GetBmpSize().y) / 2));
    left += dwbitmap.GetBmpSize().x + 8;
    dc.SetFont(Label::Body_13);
    dc.SetBackgroundMode(wxTRANSPARENT);
    dc.SetTextForeground(StateColor::darkModeColorFor(SELECT_MACHINE_GREY900));
    wxString dev_name = "";
    if (m_info) {
        dev_name = from_u8(m_info->dev_name);
         if (m_state == PrinterState::IN_LAN) {
             dev_name += _L("(LAN)");
         }
    }
    auto        sizet        = dc.GetTextExtent(dev_name);
    auto        text_end     = 0;
    if (m_show_edit) {
        text_end = size.x - m_unbind_img.GetBmpSize().x - 30;
    }
    else {
        text_end = size.x - m_unbind_img.GetBmpSize().x;
    }
    wxString finally_name =  dev_name;
    if (sizet.x > (text_end - left)) {
        auto limit_width = text_end - left - dc.GetTextExtent("...").x - 15;
        for (auto i = 0; i < dev_name.length(); i++) {
            auto curr_width = dc.GetTextExtent(dev_name.substr(0, i));
            if (curr_width.x >= limit_width) {
                finally_name = dev_name.substr(0, i) + "...";
                break;
            }
        }
    }
    dc.DrawText(finally_name, wxPoint(left, (size.y - sizet.y) / 2));
    if (m_hover) {
        dc.SetPen(SELECT_MACHINE_BRAND);
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawRectangle(0, 0, size.x, size.y);
        if (m_show_bind) {
            if (m_bind_state == ALLOW_UNBIND) {
                left = size.x - m_unbind_img.GetBmpSize().x - 6;
                dc.DrawBitmap(m_unbind_img.bmp(), left, (size.y - m_unbind_img.GetBmpSize().y) / 2);
            }
        }
        if (m_show_edit) {
            left = size.x - m_unbind_img.GetBmpSize().x - 6 - m_edit_name_img.GetBmpSize().x - 6;
            dc.DrawBitmap(m_edit_name_img.bmp(), left, (size.y - m_edit_name_img.GetBmpSize().y) / 2);
        }
    }
}
References _L, Slic3r::GUI::ALLOW_UNBIND, ScalableBitmap::bmp(), Label::Body_13, Slic3r::GUI::BUSY, StateColor::darkModeColorFor(), Slic3r::MachineObject::dev_name, Slic3r::GUI::from_u8(), ScalableBitmap::GetBmpSize(), Slic3r::GUI::IDLE, Slic3r::GUI::IN_LAN, Slic3r::GUI::LOCK, m_bind_state, m_edit_name_img, m_hover, m_info, m_printer_in_lan, m_printer_status_busy, m_printer_status_idle, m_printer_status_lock, m_printer_status_offline, m_show_bind, m_show_edit, m_state, m_unbind_img, Slic3r::GUI::OFFLINE, SELECT_MACHINE_BRAND, SELECT_MACHINE_GREY900, and size.
Referenced by OnPaint(), and render().
on_mouse_enter()
void Slic3r::GUI::MachineObjectPanel::on_mouse_enter (wxMouseEvent & evt) protected
{
    m_hover = true;
    Refresh();
}
References m_hover.
Referenced by MachineObjectPanel().
on_mouse_leave()
void Slic3r::GUI::MachineObjectPanel::on_mouse_leave (wxMouseEvent & evt) protected
{
    m_hover = false;
    Refresh();
}
References m_hover.
Referenced by MachineObjectPanel().
on_mouse_left_up()
void Slic3r::GUI::MachineObjectPanel::on_mouse_left_up (wxMouseEvent & evt) protected
{
    if (m_is_my_devices) {
        // show edit
        if (m_show_edit) {
            auto edit_left   = GetSize().x - m_unbind_img.GetBmpSize().x - 6 - m_edit_name_img.GetBmpSize().x - 6;
            auto edit_right  = edit_left + m_edit_name_img.GetBmpSize().x;
            auto edit_top    = (GetSize().y - m_edit_name_img.GetBmpSize().y) / 2;
            auto edit_bottom = (GetSize().y - m_edit_name_img.GetBmpSize().y) / 2 + m_edit_name_img.GetBmpSize().y;
            if ((evt.GetPosition().x >= edit_left && evt.GetPosition().x <= edit_right) && evt.GetPosition().y >= edit_top && evt.GetPosition().y <= edit_bottom) {
                wxCommandEvent event(EVT_EDIT_PRINT_NAME);
                event.SetEventObject(this);
                wxPostEvent(this, event);
                return;
            }
        }
        if (m_show_bind) {
            auto left   = GetSize().x - m_unbind_img.GetBmpSize().x - 6;
            auto right  = left + m_unbind_img.GetBmpSize().x;
            auto top    = (GetSize().y - m_unbind_img.GetBmpSize().y) / 2;
            auto bottom = (GetSize().y - m_unbind_img.GetBmpSize().y) / 2 + m_unbind_img.GetBmpSize().y;
            if ((evt.GetPosition().x >= left && evt.GetPosition().x <= right) && evt.GetPosition().y >= top && evt.GetPosition().y <= bottom) {
                wxCommandEvent event(EVT_UNBIND_MACHINE, GetId());
                event.SetEventObject(this);
                GetEventHandler()->ProcessEvent(event);
            } else {
                if (m_info) {
                    wxGetApp().mainframe->jump_to_monitor(m_info->dev_id);
                }
                //wxGetApp().mainframe->SetFocus();
                wxCommandEvent event(EVT_DISSMISS_MACHINE_LIST);
                event.SetEventObject(this->GetParent());
                wxPostEvent(this->GetParent(), event);
            }
            return;
        }
        if (m_info && m_info->is_lan_mode_printer()) {
            if (m_info->has_access_right() && m_info->is_avaliable()) {
                wxGetApp().mainframe->jump_to_monitor(m_info->dev_id);
            } else {
                wxCommandEvent event(EVT_CONNECT_LAN_PRINT);
                event.SetEventObject(this);
                wxPostEvent(this, event);
            }
        } else {
            wxGetApp().mainframe->jump_to_monitor(m_info->dev_id);
        }
    } else {
        if (m_info && m_info->is_lan_mode_printer()) {
            wxCommandEvent event(EVT_CONNECT_LAN_PRINT);
            event.SetEventObject(this);
            wxPostEvent(this, event);
        } else {
            wxCommandEvent event(EVT_BIND_MACHINE);
            event.SetEventObject(this);
            wxPostEvent(this, event);
        }
    }
}
References Slic3r::MachineObject::dev_id, ScalableBitmap::GetBmpSize(), Slic3r::MachineObject::has_access_right(), Slic3r::MachineObject::is_avaliable(), Slic3r::MachineObject::is_lan_mode_printer(), m_edit_name_img, m_info, m_is_my_devices, m_show_bind, m_show_edit, and m_unbind_img.
Referenced by MachineObjectPanel().
OnPaint()
void Slic3r::GUI::MachineObjectPanel::OnPaint (wxPaintEvent & event) protected
{
    wxPaintDC dc(this);
    doRender(dc);
}
References doRender().
Referenced by MachineObjectPanel().
render()
void Slic3r::GUI::MachineObjectPanel::render (wxDC & dc) protected
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
set_printer_state()
void Slic3r::GUI::MachineObjectPanel::set_printer_state (PrinterState state)
{
    m_state = state;
    Refresh();
}
References m_state.
Referenced by Slic3r::GUI::SelectMachinePopup::update_other_devices().
show_bind_dialog()
void Slic3r::GUI::MachineObjectPanel::show_bind_dialog ()
{
    if (wxGetApp().is_user_login()) {
        BindMachineDialog dlg;
        dlg.update_machine_info(m_info);
        dlg.ShowModal();
    }
}
References m_info, Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::GUI::BindMachineDialog::update_machine_info().
show_edit_printer_name()
void Slic3r::GUI::MachineObjectPanel::show_edit_printer_name (bool show)
{
    m_show_edit = show;
    Refresh();
}
References m_show_edit.
Referenced by Slic3r::GUI::SelectMachinePopup::update_other_devices().
show_printer_bind()
void Slic3r::GUI::MachineObjectPanel::show_printer_bind (bool show, PrinterBindState state)
{
    m_show_bind   = show;
    m_bind_state  = state;
    Refresh();
}
References m_bind_state, and m_show_bind.
Referenced by Slic3r::GUI::SelectMachinePopup::update_other_devices().
update_machine_info()
void Slic3r::GUI::MachineObjectPanel::update_machine_info (MachineObject * info, bool is_my_devices = false)
{
    m_info = info;
    m_is_my_devices = is_my_devices;
    Refresh();
}
References m_info, and m_is_my_devices.
Referenced by Slic3r::GUI::SelectMachinePopup::update_other_devices().
Member Data Documentation
m_bind_state
PrinterBindState Slic3r::GUI::MachineObjectPanel::m_bind_state private
Referenced by doRender(), and show_printer_bind().
m_bitmap_bind
wxStaticBitmap* Slic3r::GUI::MachineObjectPanel::m_bitmap_bind protected
m_bitmap_info
wxStaticBitmap* Slic3r::GUI::MachineObjectPanel::m_bitmap_info protected
m_edit_name_img
ScalableBitmap Slic3r::GUI::MachineObjectPanel::m_edit_name_img private
Referenced by MachineObjectPanel(), doRender(), and on_mouse_left_up().
m_hover
bool Slic3r::GUI::MachineObjectPanel::m_hover {false} private
Referenced by doRender(), on_mouse_enter(), and on_mouse_leave().
m_info
MachineObject* Slic3r::GUI::MachineObjectPanel::m_info private
Referenced by doRender(), on_mouse_left_up(), show_bind_dialog(), and update_machine_info().
m_is_my_devices
bool Slic3r::GUI::MachineObjectPanel::m_is_my_devices {false} private
Referenced by on_mouse_left_up(), and update_machine_info().
m_printer_in_lan
ScalableBitmap Slic3r::GUI::MachineObjectPanel::m_printer_in_lan private
Referenced by MachineObjectPanel(), and doRender().
m_printer_status_busy
ScalableBitmap Slic3r::GUI::MachineObjectPanel::m_printer_status_busy private
Referenced by MachineObjectPanel(), and doRender().
m_printer_status_idle
ScalableBitmap Slic3r::GUI::MachineObjectPanel::m_printer_status_idle private
Referenced by MachineObjectPanel(), and doRender().
m_printer_status_lock
ScalableBitmap Slic3r::GUI::MachineObjectPanel::m_printer_status_lock private
Referenced by MachineObjectPanel(), and doRender().
m_printer_status_offline
ScalableBitmap Slic3r::GUI::MachineObjectPanel::m_printer_status_offline private
Referenced by MachineObjectPanel(), and doRender().
m_select_unbind_img
ScalableBitmap Slic3r::GUI::MachineObjectPanel::m_select_unbind_img private
Referenced by MachineObjectPanel().
m_show_bind
bool Slic3r::GUI::MachineObjectPanel::m_show_bind {false} private
Referenced by doRender(), on_mouse_left_up(), and show_printer_bind().
m_show_edit
bool Slic3r::GUI::MachineObjectPanel::m_show_edit {false} private
Referenced by doRender(), on_mouse_left_up(), and show_edit_printer_name().
m_state
PrinterState Slic3r::GUI::MachineObjectPanel::m_state private
Referenced by doRender(), and set_printer_state().
m_unbind_img
ScalableBitmap Slic3r::GUI::MachineObjectPanel::m_unbind_img private
Referenced by MachineObjectPanel(), doRender(), and on_mouse_left_up().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SelectMachine.hpp
src/slic3r/GUI/SelectMachine.cpp