OrcaSlicer: src/slic3r/GUI/PartPlate.hpp File Reference
PartPlate.hpp File Reference
#include <vector>
#include <set>
#include <array>
#include <thread>
#include <mutex>
#include "libslic3r/ObjectID.hpp"
#include "libslic3r/GCode/GCodeProcessor.hpp"
#include "libslic3r/Format/bbs_3mf.hpp"
#include "libslic3r/Slicing.hpp"
#include "libslic3r/Arrange.hpp"
#include "Plater.hpp"
#include "libslic3r/Model.hpp"
#include "libslic3r/Print.hpp"
#include "libslic3r/PrintConfig.hpp"
#include "GLCanvas3D.hpp"
#include "GLTexture.hpp"
#include "3DScene.hpp"
#include "GLModel.hpp"
#include "3DBed.hpp"
Classes
class Slic3r::GUI::PartPlate
class Slic3r::GUI::PartPlateList
class Slic3r::GUI::PartPlateList::BedTextureInfo
class Slic3r::GUI::PartPlateList::BedTextureInfo::TexturePart
struct cereal::specialize< Archive, Slic3r::GUI::PartPlate, cereal::specialization::member_load_save >
Namespaces
namespace Slic3r
namespace Slic3r::GUI
namespace cereal
Macros
#define PLATE_CURRENT_IDX -1
#define PLATE_ALL_IDX -2
#define MAX_PLATE_COUNT 36
Typedefs
typedef class GLUquadric GLUquadricObject
using Slic3r::GUI::GCodeResult = GCodeProcessorResult
Functions
int compute_colum_count (int count)
Class Documentation
Slic3r::GUI::PartPlateList::BedTextureInfo
class Slic3r::GUI::PartPlateList::BedTextureInfo
Class Members
vector< TexturePart > parts
cereal::specialize< Archive, Slic3r::GUI::PartPlate, cereal::specialization::member_load_save >
struct cereal::specialize< Archive, Slic3r::GUI::PartPlate, cereal::specialization::member_load_save >
template<class Archive>
struct cereal::specialize< Archive, Slic3r::GUI::PartPlate, cereal::specialization::member_load_save >
Macro Definition Documentation
MAX_PLATE_COUNT
#define MAX_PLATE_COUNT 36
PLATE_ALL_IDX
#define PLATE_ALL_IDX -2
PLATE_CURRENT_IDX
#define PLATE_CURRENT_IDX -1
Typedef Documentation
GLUquadricObject
typedef class GLUquadric GLUquadricObject
Function Documentation
compute_colum_count()
int compute_colum_count (int count) inline
{
    float value = sqrt((float)count);
    float round_value = round(value);
    int cols;
    if (value > round_value)
        cols = round_value +1;
    else
        cols = round_value;
    return cols;
}
References count, round(), and sqrt().
Referenced by Slic3r::GUI::PartPlateList::create_plate(), Slic3r::GUI::PartPlateList::delete_plate(), and Slic3r::GUI::PartPlateList::update_plate_cols().