OrcaSlicer: Slic3r::GUI::HMSPanel Class Reference
Slic3r::GUI::HMSPanel Class Reference
#include <src/slic3r/GUI/HMSPanel.hpp>
Public Member Functions
HMSPanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~HMSPanel ()
void msw_rescale ()
bool Show (bool show=true) override
void update (MachineObject *obj_)
void show_status (int status)
Public Attributes
MachineObject * obj { nullptr }
Protected Member Functions
void append_hms_panel (HMSItem &item)
void delete_hms_panels ()
Protected Attributes
wxScrolledWindow * m_scrolledWindow
wxBoxSizer * m_top_sizer
HMSNotifyItem * m_notify_item
int last_status
Detailed Description
Constructor & Destructor Documentation
HMSPanel()
Slic3r::GUI::HMSPanel::HMSPanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
    :wxPanel(parent, id, pos, size, style)
{
    this->SetBackgroundColour(wxColour(238, 238, 238));
    auto m_main_sizer = new wxBoxSizer(wxVERTICAL);
    m_scrolledWindow = new wxScrolledWindow(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxVSCROLL);
    m_scrolledWindow->SetScrollRate(5, 5);
    m_top_sizer = new wxBoxSizer(wxVERTICAL);
    m_top_sizer->AddSpacer(FromDIP(30));
    m_scrolledWindow->SetSizerAndFit(m_top_sizer);
    m_main_sizer->Add(m_scrolledWindow, 1, wxEXPAND, 0);
    this->SetSizerAndFit(m_main_sizer);
    Layout();
}
References m_scrolledWindow, and m_top_sizer.
~HMSPanel()
Slic3r::GUI::HMSPanel::~HMSPanel ()
                    {
    ;
}
Member Function Documentation
append_hms_panel()
void Slic3r::GUI::HMSPanel::append_hms_panel (HMSItem & item) protected
{
    m_notify_item = new HMSNotifyItem(m_scrolledWindow, item);
    wxString msg = wxGetApp().get_hms_query()->query_hms_msg(item.get_long_error_code());
    if (!msg.empty())
        m_top_sizer->Add(m_notify_item, 0, wxALIGN_CENTER_HORIZONTAL);
    else {
        // debug for hms display error info
        // m_top_sizer->Add(m_notify_item, 0, wxALIGN_CENTER_HORIZONTAL);
        BOOST_LOG_TRIVIAL(info) << "hms: do not display empty_item";
    }
}
References Slic3r::HMSItem::get_long_error_code(), m_notify_item, m_scrolledWindow, and m_top_sizer.
Referenced by update().
delete_hms_panels()
void Slic3r::GUI::HMSPanel::delete_hms_panels () protected
{
    m_scrolledWindow->DestroyChildren();
}
References m_scrolledWindow.
Referenced by show_status(), and update().
msw_rescale()
void Slic3r::GUI::HMSPanel::msw_rescale () inline
{}
Referenced by Slic3r::GUI::MonitorPanel::msw_rescale().
Show()
bool Slic3r::GUI::HMSPanel::Show (bool show = true) override
{
    return wxPanel::Show(show);
}
show_status()
void Slic3r::GUI::HMSPanel::show_status (int status)
{
    if (last_status == status) return;
    last_status = status;
    if (((status & (int)MonitorStatus::MONITOR_DISCONNECTED) != 0)
        || ((status & (int)MonitorStatus::MONITOR_DISCONNECTED_SERVER) != 0)
        || ((status & (int)MonitorStatus::MONITOR_CONNECTING) != 0)
        || ((status & (int)MonitorStatus::MONITOR_NO_PRINTER) != 0)
        ) {
        delete_hms_panels();
        Layout();
    }
}
References delete_hms_panels(), last_status, Slic3r::GUI::MONITOR_CONNECTING, Slic3r::GUI::MONITOR_DISCONNECTED, Slic3r::GUI::MONITOR_DISCONNECTED_SERVER, and Slic3r::GUI::MONITOR_NO_PRINTER.
Referenced by Slic3r::GUI::MonitorPanel::show_status().
update()
void Slic3r::GUI::HMSPanel::update (MachineObject * obj_)
{
    if (obj) {
        this->Freeze();
        delete_hms_panels();
        wxString hms_text;
        for (auto item : obj->hms_list) {
            if (wxGetApp().get_hms_query()) {
                append_hms_panel(item);
            }
        }
        Layout();
        this->Thaw();
    } else {
        delete_hms_panels();
        Layout();
    }
}
References append_hms_panel(), delete_hms_panels(), Slic3r::MachineObject::hms_list, and obj.
Referenced by Slic3r::GUI::MonitorPanel::update_all().
Member Data Documentation
last_status
int Slic3r::GUI::HMSPanel::last_status protected
Referenced by show_status().
m_notify_item
HMSNotifyItem* Slic3r::GUI::HMSPanel::m_notify_item protected
Referenced by append_hms_panel().
m_scrolledWindow
wxScrolledWindow* Slic3r::GUI::HMSPanel::m_scrolledWindow protected
Referenced by HMSPanel(), append_hms_panel(), and delete_hms_panels().
m_top_sizer
wxBoxSizer* Slic3r::GUI::HMSPanel::m_top_sizer protected
Referenced by HMSPanel(), and append_hms_panel().
obj
MachineObject* Slic3r::GUI::HMSPanel::obj { nullptr }
Referenced by update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/HMSPanel.hpp
src/slic3r/GUI/HMSPanel.cpp