OrcaSlicer: Clipper2Lib::RectClip Class Reference
Clipper2Lib::RectClip Class Reference
#include <src/clipper2/Clipper2Lib/include/clipper2/clipper.rectclip.h>
Public Member Functions
RectClip (const Rect64 &rect)
Path64 Execute (const Path64 &path)
Protected Member Functions
void GetNextLocation (const Path64 &path, Location &loc, int &i, int highI)
void AddCorner (Location prev, Location curr)
void AddCorner (Location &loc, bool isClockwise)
Protected Attributes
const Rect64 rect_
const Point64 mp_
const Path64 rectPath_
Path64 result_
std::vector< Location > start_locs_
Detailed Description
Constructor & Destructor Documentation
RectClip()
Clipper2Lib::RectClip::RectClip (const Rect64 & rect) inline
                                 :
      rect_(rect),
      mp_(rect.MidPoint()),
      rectPath_(rect.AsPath()) {}
Member Function Documentation
AddCorner() [1/2]
void Clipper2Lib::RectClip::AddCorner (Location & loc, bool isClockwise) protected
  {
    if (isClockwise)
    {
      result_.push_back(rectPath_[static_cast<int>(loc)]);
      loc = GetAdjacentLocation(loc, true);
    }
    else
    {
      loc = GetAdjacentLocation(loc, false);
      result_.push_back(rectPath_[static_cast<int>(loc)]);
    }
  }
References Clipper2Lib::GetAdjacentLocation(), rectPath_, and result_.
AddCorner() [2/2]
void Clipper2Lib::RectClip::AddCorner (Location prev, Location curr) protected
  {
    if (HeadingClockwise(prev, curr))
      result_.push_back(rectPath_[static_cast<int>(prev)]);
    else
      result_.push_back(rectPath_[static_cast<int>(curr)]);
  }
References Clipper2Lib::HeadingClockwise(), rectPath_, and result_.
Referenced by Execute().
Execute()
Path64 Clipper2Lib::RectClip::Execute (const Path64 & path)
  {
    if (rect_.IsEmpty() || path.size() < 3) return Path64();
    result_.clear();
    start_locs_.clear();
    int i = 0, highI = static_cast<int>(path.size()) - 1;
    Location prev = Location::Inside, loc;
    Location crossing_loc = Location::Inside;
    Location first_cross_ = Location::Inside;
    if (!GetLocation(rect_, path[highI], loc))
    {
      i = highI - 1;
      while (i >= 0 && !GetLocation(rect_, path[i], prev)) --i;
      if (i < 0) return path;
      if (prev == Location::Inside) loc = Location::Inside;
      i = 0;
    }
    Location starting_loc = loc;
    while (i <= highI)
    {
      prev = loc;
      Location crossing_prev = crossing_loc;
      GetNextLocation(path, loc, i, highI);
      if (i > highI) break;
      Point64 ip, ip2;
      Point64 prev_pt = (i) ? path[static_cast<size_t>(i - 1)] : path[highI];
      crossing_loc = loc;
      if (!GetIntersection(rectPath_, path[i], prev_pt, crossing_loc, ip))
      {
        // ie remaining outside
        if (crossing_prev == Location::Inside)
        {
          bool isClockw = IsClockwise(prev, loc, prev_pt, path[i], mp_);
          do {
            start_locs_.push_back(prev);
            prev = GetAdjacentLocation(prev, isClockw);
          } while (prev != loc);
          crossing_loc = crossing_prev; // still not crossed
        }
        else if (prev != Location::Inside && prev != loc)
        {
          bool isClockw = IsClockwise(prev, loc, prev_pt, path[i], mp_);
          do {
            AddCorner(prev, isClockw);
          } while (prev != loc);
        }
        ++i;
        continue;
      }
      // we must be crossing the rect boundary to get here
      if (loc == Location::Inside) // path must be entering rect
      {
        if (first_cross_ == Location::Inside)
        {
          first_cross_ = crossing_loc;
          start_locs_.push_back(prev);
        }
        else if (prev != crossing_loc)
        {
          bool isClockw = IsClockwise(prev, crossing_loc, prev_pt, path[i], mp_);
          do {
            AddCorner(prev, isClockw);
          } while (prev != crossing_loc);
        }
      }
      else if (prev != Location::Inside)
      {
        // passing right through rect. 'ip' here will be the second
        // intersect pt but we'll also need the first intersect pt (ip2)
        loc = prev;
        GetIntersection(rectPath_, prev_pt, path[i], loc, ip2);
        if (crossing_prev != Location::Inside)
          AddCorner(crossing_prev, loc);
        if (first_cross_ == Location::Inside)
        {
          first_cross_ = loc;
          start_locs_.push_back(prev);
        }
        loc = crossing_loc;
        result_.push_back(ip2);
        if (ip == ip2)
        {
          // it's very likely that path[i] is on rect
          GetLocation(rect_, path[i], loc);
          AddCorner(crossing_loc, loc);
          crossing_loc = loc;
          continue;
        }
      }
      else // path must be exiting rect
      {
        loc = crossing_loc;
        if (first_cross_ == Location::Inside)
          first_cross_ = crossing_loc;
      }
      result_.push_back(ip);
    } //while i <= highI
    if (first_cross_ == Location::Inside)
    {
      if (starting_loc == Location::Inside) return path;
      Rect64 tmp_rect = Bounds(path);
      if (tmp_rect.Contains(rect_) &&
        Path1ContainsPath2(path, rectPath_) !=
        PointInPolygonResult::IsOutside) return rectPath_;
      else
        return Path64();
    }
    if (loc != Location::Inside &&
      (loc != first_cross_ || start_locs_.size() > 2))
    {
      if (start_locs_.size() > 0)
      {
        prev = loc;
        for (auto loc2 : start_locs_)
        {
          if (prev == loc2) continue;
          AddCorner(prev, HeadingClockwise(prev, loc2));
          prev = loc2;
        }
        loc = prev;
      }
      if (loc != first_cross_)
        AddCorner(loc, HeadingClockwise(loc, first_cross_));
    }
    if (result_.size() < 3) return Path64();
    // tidy up duplicates and collinear segments
    Path64 res;
    res.reserve(result_.size());
    size_t k = 0; highI = static_cast<int>(result_.size()) - 1;
    Point64 prev_pt = result_[highI];
    res.push_back(result_[0]);
    Path64::const_iterator cit;
    for (cit = result_.cbegin() + 1; cit != result_.cend(); ++cit)
    {
      if (CrossProduct(prev_pt, res[k], *cit))
      {
        prev_pt = res[k++];
        res.push_back(*cit);
      }
      else
        res[k] = *cit;
    }
    if (k < 2) return Path64();
    // and a final check for collinearity
    else if (!CrossProduct(res[0], res[k - 1], res[k])) res.pop_back();
    return res;
  }
References AddCorner(), Clipper2Lib::Bounds(), Clipper2Lib::Rect< T >::Contains(), Clipper2Lib::CrossProduct(), Clipper2Lib::GetAdjacentLocation(), Clipper2Lib::GetIntersection(), Clipper2Lib::GetLocation(), GetNextLocation(), Clipper2Lib::HeadingClockwise(), Clipper2Lib::Inside, Clipper2Lib::IsClockwise(), Clipper2Lib::Rect< T >::IsEmpty(), Clipper2Lib::IsOutside, mp_, Clipper2Lib::Path1ContainsPath2(), rect_, rectPath_, result_, and start_locs_.
Referenced by Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip(), Clipper2Lib::RectClip64(), and Clipper2Lib::RectClipD().
GetNextLocation()
void Clipper2Lib::RectClip::GetNextLocation (const Path64 & path, Location & loc, int & i, int highI) protected
  {
    switch (loc)
    {
    case Location::Left:
      while (i <= highI && path[i].x <= rect_.left) ++i;
      if (i > highI) break;
      else if (path[i].x >= rect_.right) loc = Location::Right;
      else if (path[i].y <= rect_.top) loc = Location::Top;
      else if (path[i].y >= rect_.bottom) loc = Location::Bottom;
      else loc = Location::Inside;
      break;
    case Location::Top:
      while (i <= highI && path[i].y <= rect_.top) ++i;
      if (i > highI) break;
      else if (path[i].y >= rect_.bottom) loc = Location::Bottom;
      else if (path[i].x <= rect_.left) loc = Location::Left;
      else if (path[i].x >= rect_.right) loc = Location::Right;
      else loc = Location::Inside;
      break;
    case Location::Right:
      while (i <= highI && path[i].x >= rect_.right) ++i;
      if (i > highI) break;
      else if (path[i].x <= rect_.left) loc = Location::Left;
      else if (path[i].y <= rect_.top) loc = Location::Top;
      else if (path[i].y >= rect_.bottom) loc = Location::Bottom;
      else loc = Location::Inside;
      break;
    case Location::Bottom:
      while (i <= highI && path[i].y >= rect_.bottom) ++i;
      if (i > highI) break;
      else if (path[i].y <= rect_.top) loc = Location::Top;
      else if (path[i].x <= rect_.left) loc = Location::Left;
      else if (path[i].x >= rect_.right) loc = Location::Right;
      else loc = Location::Inside;
      break;
    case Location::Inside:
      while (i <= highI)
      {
        if (path[i].x < rect_.left) loc = Location::Left;
        else if (path[i].x > rect_.right) loc = Location::Right;
        else if (path[i].y > rect_.bottom) loc = Location::Bottom;
        else if (path[i].y < rect_.top) loc = Location::Top;
        else { result_.push_back(path[i]); ++i; continue; }
        break; //inner loop
      }
      break;
    } //switch
  }
References Clipper2Lib::Rect< T >::bottom, Clipper2Lib::Bottom, Clipper2Lib::Inside, Clipper2Lib::Rect< T >::left, Clipper2Lib::Left, rect_, result_, Clipper2Lib::Rect< T >::right, Clipper2Lib::Right, Clipper2Lib::Rect< T >::top, and Clipper2Lib::Top.
Referenced by Execute(), and Clipper2Lib::RectClipLines::Execute().
Member Data Documentation
mp_
const Point64 Clipper2Lib::RectClip::mp_ protected
Referenced by Execute().
rect_
const Rect64 Clipper2Lib::RectClip::rect_ protected
Referenced by Execute(), Clipper2Lib::RectClipLines::Execute(), and GetNextLocation().
rectPath_
const Path64 Clipper2Lib::RectClip::rectPath_ protected
Referenced by AddCorner(), AddCorner(), Execute(), and Clipper2Lib::RectClipLines::Execute().
result_
Path64 Clipper2Lib::RectClip::result_ protected
Referenced by AddCorner(), AddCorner(), Execute(), Clipper2Lib::RectClipLines::Execute(), and GetNextLocation().
start_locs_
std::vector<Location> Clipper2Lib::RectClip::start_locs_ protected
Referenced by Execute().
The documentation for this class was generated from the following files:
src/clipper2/Clipper2Lib/include/clipper2/clipper.rectclip.h
src/clipper2/Clipper2Lib/src/clipper.rectclip.cpp