OrcaSlicer: Slic3r::client::MyContext Struct Reference
Slic3r::client::MyContext Struct Reference
Public Member Functions
const ConfigOption * optptr (const t_config_option_key &opt_key) const override
const ConfigOption * resolve_symbol (const std::string &opt_key) const
bool has (const t_config_option_key &opt_key) const
const ConfigOption * option (const t_config_option_key &opt_key) const
template<typename TYPE >
const TYPE * option (const t_config_option_key &opt_key) const
const ConfigOption * option_throw (const t_config_option_key &opt_key) const
template<typename TYPE >
const TYPE * option_throw (const t_config_option_key &opt_key) const
Static Public Member Functions
static void evaluate_full_macro (const MyContext *ctx, bool &result)
template<typename Iterator >
static void legacy_variable_expansion (const MyContext *ctx, boost::iterator_range< Iterator > &opt_key, std::string &output)
template<typename Iterator >
static void legacy_variable_expansion2 (const MyContext *ctx, boost::iterator_range< Iterator > &opt_key, boost::iterator_range< Iterator > &opt_vector_index, std::string &output)
template<typename Iterator >
static void resolve_variable (const MyContext *ctx, boost::iterator_range< Iterator > &opt_key, OptWithPos< Iterator > &output)
template<typename Iterator >
static void scalar_variable_reference (const MyContext *ctx, OptWithPos< Iterator > &opt, expr< Iterator > &output)
template<typename Iterator >
static void vector_variable_reference (const MyContext *ctx, OptWithPos< Iterator > &opt, int &index, Iterator it_end, expr< Iterator > &output)
template<typename Iterator >
static void evaluate_index (expr< Iterator > &expr_index, int &output)
template<typename Iterator >
static void random (const MyContext *ctx, expr< Iterator > &param1, expr< Iterator > &param2)
template<typename Iterator >
static void throw_exception (const std::string &msg, const boost::iterator_range< Iterator > &it_range)
template<typename Iterator >
static void process_error_message (const MyContext *context, const boost::spirit::info &info, const Iterator &it_begin, const Iterator &it_end, const Iterator &it_error)
Public Attributes
const DynamicConfig * external_config = nullptr
const DynamicConfig * config = nullptr
const DynamicConfig * config_override = nullptr
size_t current_extruder_id = 0
PlaceholderParser::ContextData * context_data = nullptr
bool just_boolean_expression = false
std::string error_message
Static Public Attributes
static std::map< std::string, std::string > tag_to_error_message
Detailed Description
Member Function Documentation
evaluate_full_macro()
static void Slic3r::client::MyContext::evaluate_full_macro (const MyContext * ctx, bool & result) inline static
{ result = ! ctx->just_boolean_expression; }
References just_boolean_expression.
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
evaluate_index()
template<typename Iterator > static void Slic3r::client::MyContext::evaluate_index (expr< Iterator > & expr_index, int & output) inline static
        {
            if (expr_index.type != expr<Iterator>::TYPE_INT)
                expr_index.throw_exception("Non-integer index is not allowed to address a vector variable.");
            output = expr_index.i();
        }
References Slic3r::client::expr< Iterator >::i(), Slic3r::client::expr< Iterator >::throw_exception(), and Slic3r::client::expr< Iterator >::type.
has()
bool Slic3r::ConfigOptionResolver::has (const t_config_option_key & opt_key) const inline inherited
{ return this->optptr(opt_key) != nullptr; }
References Slic3r::ConfigOptionResolver::optptr().
Referenced by Slic3r::GUI::change_opt_value(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::Bed3D::detect_type(), Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::dirty_options_without_option_list(), Slic3r::GUI::PartPlate::get_bed_type(), Slic3r::anonymous_namespace{SL1.cpp}::get_cfg_value(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::Preset::get_default_bed_type(), Slic3r::GUI::Plater::get_extruder_colors_from_plater_config(), Slic3r::get_instance_arrange_poly(), Slic3r::GUI::ConfigOptionsGroup::get_option(), Slic3r::GUI::PartPlate::get_print_seq(), Slic3r::GUI::PresetComboBox::get_tooltip(), Slic3r::handle_legacy_project_loaded(), Slic3r::handle_legacy_sla(), Slic3r::ModelConfig::has(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetCollection::is_dirty(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::DynamicPrintConfig::normalize_fdm(), Slic3r::DynamicPrintConfig::normalize_fdm_1(), Slic3r::DynamicConfig::read_cli(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::Preset::remove_invalid_keys(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::GUI::PartPlate::render_logo(), Slic3r::GUI::PartPlate::set_bed_type(), Slic3r::GUI::Plater::setExtruderParams(), Slic3r::GUI::Plater::setPrintSpeedTable(), and Slic3r::PresetBundle::update_compatible().
legacy_variable_expansion()
template<typename Iterator > static void Slic3r::client::MyContext::legacy_variable_expansion (const MyContext * ctx, boost::iterator_range< Iterator > & opt_key, std::string & output) inline static
        {
            std::string         opt_key_str(opt_key.begin(), opt_key.end());
            const ConfigOption *opt = ctx->resolve_symbol(opt_key_str);
            size_t              idx = ctx->current_extruder_id;
            if (opt == nullptr) {
                // Check whether this is a legacy vector indexing.
                idx = opt_key_str.rfind('_');
                if (idx != std::string::npos) {
                    opt = ctx->resolve_symbol(opt_key_str.substr(0, idx));
                    if (opt != nullptr) {
                        if (! opt->is_vector())
                            ctx->throw_exception("Trying to index a scalar variable", opt_key);
                        char *endptr = nullptr;
                        idx = strtol(opt_key_str.c_str() + idx + 1, &endptr, 10);
                        if (endptr == nullptr || *endptr != 0)
                            ctx->throw_exception("Invalid vector index", boost::iterator_range<Iterator>(opt_key.begin() + idx + 1, opt_key.end()));
                    }
                }
            }
            if (opt == nullptr)
                ctx->throw_exception("Variable does not exist", boost::iterator_range<Iterator>(opt_key.begin(), opt_key.end()));
            if (opt->is_scalar())
                output = opt->serialize();
            else {
                const ConfigOptionVectorBase *vec = static_cast<const ConfigOptionVectorBase*>(opt);
                if (vec->empty())
                    ctx->throw_exception("Indexing an empty vector variable", opt_key);
                output = vec->vserialize()[(idx >= vec->size()) ? 0 : idx];
            }
        }
References current_extruder_id, Slic3r::ConfigOptionVectorBase::empty(), Slic3r::ConfigOption::is_scalar(), Slic3r::ConfigOption::is_vector(), resolve_symbol(), Slic3r::ConfigOption::serialize(), Slic3r::ConfigOptionVectorBase::size(), throw_exception(), and Slic3r::ConfigOptionVectorBase::vserialize().
legacy_variable_expansion2()
template<typename Iterator > static void Slic3r::client::MyContext::legacy_variable_expansion2 (const MyContext * ctx, boost::iterator_range< Iterator > & opt_key, boost::iterator_range< Iterator > & opt_vector_index, std::string & output) inline static
        {
            std::string         opt_key_str(opt_key.begin(), opt_key.end());
            const ConfigOption *opt = ctx->resolve_symbol(opt_key_str);
            if (opt == nullptr) {
                // Check whether the opt_key ends with '_'.
                if (opt_key_str.back() == '_')
                    opt_key_str.resize(opt_key_str.size() - 1);
                opt = ctx->resolve_symbol(opt_key_str);
            }
            if (! opt->is_vector())
                ctx->throw_exception("Trying to index a scalar variable", opt_key);
            const ConfigOptionVectorBase *vec = static_cast<const ConfigOptionVectorBase*>(opt);
            if (vec->empty())
                ctx->throw_exception("Indexing an empty vector variable", boost::iterator_range<Iterator>(opt_key.begin(), opt_key.end()));
            const ConfigOption *opt_index = ctx->resolve_symbol(std::string(opt_vector_index.begin(), opt_vector_index.end()));
            if (opt_index == nullptr)
                ctx->throw_exception("Variable does not exist", opt_key);
            if (opt_index->type() != coInt)
                ctx->throw_exception("Indexing variable has to be integer", opt_key);
      int idx = opt_index->getInt();
      if (idx < 0)
                ctx->throw_exception("Negative vector index", opt_key);
      output = vec->vserialize()[(idx >= (int)vec->size()) ? 0 : idx];
        }
References Slic3r::coInt, Slic3r::ConfigOptionVectorBase::empty(), Slic3r::ConfigOption::getInt(), int, Slic3r::ConfigOption::is_vector(), resolve_symbol(), Slic3r::ConfigOptionVectorBase::size(), throw_exception(), Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionVectorBase::vserialize().
option() [1/2]
const ConfigOption * Slic3r::ConfigOptionResolver::option (const t_config_option_key & opt_key) const inline inherited
{ return this->optptr(opt_key); }
References Slic3r::ConfigOptionResolver::optptr().
Referenced by Slic3r::Flow::extrusion_width(), Slic3r::Flow::extrusion_width(), and Slic3r::PrintObject::invalidate_state_by_config_options().
option() [2/2]
template<typename TYPE > const TYPE * Slic3r::ConfigOptionResolver::option (const t_config_option_key & opt_key) const inline inherited
    {
        const ConfigOption* opt = this->optptr(opt_key);
        return (opt == nullptr || opt->type() != TYPE::static_type()) ? nullptr : static_cast<const TYPE*>(opt);
    }
References Slic3r::ConfigOptionResolver::optptr(), and Slic3r::ConfigOption::type().
option_throw() [1/2]
const ConfigOption * Slic3r::ConfigOptionResolver::option_throw (const t_config_option_key & opt_key) const inline inherited
    {
        const ConfigOption* opt = this->optptr(opt_key);
        if (opt == nullptr)
            throw UnknownOptionException(opt_key);
        return opt;
    }
References Slic3r::ConfigOptionResolver::optptr().
Referenced by Slic3r::ConfigOptionResolver::option_throw().
option_throw() [2/2]
template<typename TYPE > const TYPE * Slic3r::ConfigOptionResolver::option_throw (const t_config_option_key & opt_key) const inline inherited
    {
        const ConfigOption* opt = this->option_throw(opt_key);
        if (opt->type() != TYPE::static_type())
            throw BadOptionTypeException("Conversion to a wrong type");
        return static_cast<TYPE*>(opt);
    }
References Slic3r::ConfigOptionResolver::option_throw(), and Slic3r::ConfigOption::type().
optptr()
const ConfigOption * Slic3r::client::MyContext::optptr (const t_config_option_key & opt_key) const inline override virtual
Implements Slic3r::ConfigOptionResolver.
        {
            const ConfigOption *opt = nullptr;
            if (config_override != nullptr)
                opt = config_override->option(opt_key);
            if (opt == nullptr)
                opt = config->option(opt_key);
            if (opt == nullptr && external_config != nullptr)
                opt = external_config->option(opt_key);
            return opt;
        }
References config, config_override, external_config, and Slic3r::ConfigBase::option().
Referenced by resolve_symbol().
process_error_message()
template<typename Iterator > static void Slic3r::client::MyContext::process_error_message (const MyContext * context, const boost::spirit::info & info, const Iterator & it_begin, const Iterator & it_end, const Iterator & it_error) inline static
        {
            std::string &msg = const_cast<MyContext*>(context)->error_message;
            std::string  first(it_begin, it_error);
            std::string  last(it_error, it_end);
            auto         first_pos  = first.rfind('\n');
            auto         last_pos   = last.find('\n');
            int          line_nr    = 1;
            if (first_pos == std::string::npos)
                first_pos = 0;
            else {
                // Calculate the current line number.
                for (size_t i = 0; i <= first_pos; ++ i)
                    if (first[i] == '\n')
                        ++ line_nr;
                ++ first_pos;
            }
            auto error_line = std::string(first, first_pos) + std::string(last, 0, last_pos);
            // Position of the it_error from the start of its line.
            auto error_pos  = (it_error - it_begin) - first_pos;
            msg += "Parsing error at line " + std::to_string(line_nr);
            if (! info.tag.empty() && info.tag.front() == '*') {
                // The gat contains an explanatory string.
                msg += ": ";
                msg += info.tag.substr(1);
            } else {
                auto it = tag_to_error_message.find(info.tag);
                if (it == tag_to_error_message.end()) {
                    // A generic error report based on the nonterminal or terminal symbol name.
                    msg += ". Expecting tag ";
                    msg += info.tag;
                } else {
                    // Use the human readable error message.
                    msg += ". ";
                    msg += it->second;
                }
            }
            msg += '\n';
            // This hack removes all non-UTF8 characters from the source line, so that the upstream wxWidgets conversions
            // from UTF8 to UTF16 don't bail out.
            msg += boost::nowide::narrow(boost::nowide::widen(error_line));
            msg += '\n';
            for (size_t i = 0; i < error_pos; ++ i)
                msg += ' ';
            msg += "^\n";
        }
References error_message, boost::nowide::narrow(), tag_to_error_message, and boost::nowide::widen().
random()
template<typename Iterator > static void Slic3r::client::MyContext::random (const MyContext * ctx, expr< Iterator > & param1, expr< Iterator > & param2) inline static
        {
            if (ctx->context_data == nullptr)
                ctx->throw_exception("Random number generator not available in this context.",
                    boost::iterator_range<Iterator>(param1.it_range.begin(), param2.it_range.end()));
            expr<Iterator>::random(param1, param2, ctx->context_data->rng);
        }
References context_data, Slic3r::client::expr< Iterator >::it_range, Slic3r::PlaceholderParser::ContextData::rng, and throw_exception().
resolve_symbol()
const ConfigOption * Slic3r::client::MyContext::resolve_symbol (const std::string & opt_key) const inline
{ return this->optptr(opt_key); }
References optptr().
Referenced by legacy_variable_expansion(), legacy_variable_expansion2(), resolve_variable(), and scalar_variable_reference().
resolve_variable()
template<typename Iterator > static void Slic3r::client::MyContext::resolve_variable (const MyContext * ctx, boost::iterator_range< Iterator > & opt_key, OptWithPos< Iterator > & output) inline static
        {
            const ConfigOption *opt = ctx->resolve_symbol(std::string(opt_key.begin(), opt_key.end()));
            if (opt == nullptr)
                ctx->throw_exception("Not a variable name", opt_key);
            output.opt = opt;
            output.it_range = opt_key;
        }
References Slic3r::client::OptWithPos< Iterator >::it_range, Slic3r::client::OptWithPos< Iterator >::opt, resolve_symbol(), and throw_exception().
scalar_variable_reference()
template<typename Iterator > static void Slic3r::client::MyContext::scalar_variable_reference (const MyContext * ctx, OptWithPos< Iterator > & opt, expr< Iterator > & output) inline static
        {
            if (opt.opt->is_vector())
                ctx->throw_exception("Referencing a vector variable when scalar is expected", opt.it_range);
            switch (opt.opt->type()) {
            case coFloat:   output.set_d(opt.opt->getFloat());   break;
            case coInt:     output.set_i(opt.opt->getInt());     break;
            case coString:  output.set_s(static_cast<const ConfigOptionString*>(opt.opt)->value); break;
            case coPercent: output.set_d(opt.opt->getFloat());   break;
            case coPoint:   output.set_s(opt.opt->serialize());  break;
            case coBool:    output.set_b(opt.opt->getBool());    break;
            case coFloatOrPercent:
            {
                std::string opt_key(opt.it_range.begin(), opt.it_range.end());
                if (boost::ends_with(opt_key, "line_width")) {
                  // Extrusion width supports defaults and a complex graph of dependencies.
                    output.set_d(Flow::extrusion_width(opt_key, *ctx, static_cast<unsigned int>(ctx->current_extruder_id)));
                } else if (! static_cast<const ConfigOptionFloatOrPercent*>(opt.opt)->percent) {
                  // Not a percent, just return the value.
                    output.set_d(opt.opt->getFloat());
                } else {
                  // Resolve dependencies using the "ratio_over" link to a parent value.
              const ConfigOptionDef  *opt_def = print_config_def.get(opt_key);
              assert(opt_def != nullptr);
              double v = opt.opt->getFloat() * 0.01; // percent to ratio
              for (;;) {
                const ConfigOption *opt_parent = opt_def->ratio_over.empty() ? nullptr : ctx->resolve_symbol(opt_def->ratio_over);
                if (opt_parent == nullptr)
                      ctx->throw_exception("FloatOrPercent variable failed to resolve the \"ratio_over\" dependencies", opt.it_range);
                  if (boost::ends_with(opt_def->ratio_over, "line_width")) {
                      // Extrusion width supports defaults and a complex graph of dependencies.
                            assert(opt_parent->type() == coFloatOrPercent);
                        v *= Flow::extrusion_width(opt_def->ratio_over, static_cast<const ConfigOptionFloatOrPercent*>(opt_parent), *ctx, static_cast<unsigned int>(ctx->current_extruder_id));
                        break;
                      }
                      if (opt_parent->type() == coFloat || opt_parent->type() == coFloatOrPercent) {
                  v *= opt_parent->getFloat();
                  if (opt_parent->type() == coFloat || ! static_cast<const ConfigOptionFloatOrPercent*>(opt_parent)->percent)
                    break;
                  v *= 0.01; // percent to ratio
                }
                // Continue one level up in the "ratio_over" hierarchy.
                opt_def = print_config_def.get(opt_def->ratio_over);
                assert(opt_def != nullptr);
              }
                    output.set_d(v);
              }
            break;
        }
            //BBS: Add enum. Otherwise enum can not be judged in placeholder
            case coEnum:    output.set_s(opt.opt->serialize());  break;
            default:
                ctx->throw_exception("Unknown scalar variable type", opt.it_range);
            }
            output.it_range = opt.it_range;
        }
References Slic3r::coBool, Slic3r::coEnum, Slic3r::coFloat, Slic3r::coFloatOrPercent, Slic3r::coInt, Slic3r::coPercent, Slic3r::coPoint, Slic3r::coString, current_extruder_id, Slic3r::Flow::extrusion_width(), Slic3r::ConfigDef::get(), Slic3r::ConfigOption::getBool(), Slic3r::ConfigOption::getFloat(), Slic3r::ConfigOption::getInt(), Slic3r::ConfigOption::is_vector(), Slic3r::client::OptWithPos< Iterator >::it_range, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::OptWithPos< Iterator >::opt, Slic3r::ConfigOptionFloatOrPercent::percent, Slic3r::print_config_def, Slic3r::ConfigOptionDef::ratio_over, resolve_symbol(), Slic3r::ConfigOption::serialize(), Slic3r::client::expr< Iterator >::set_b(), Slic3r::client::expr< Iterator >::set_d(), Slic3r::client::expr< Iterator >::set_i(), Slic3r::client::expr< Iterator >::set_s(), throw_exception(), Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionSingle< T >::value.
throw_exception()
template<typename Iterator > static void Slic3r::client::MyContext::throw_exception (const std::string & msg, const boost::iterator_range< Iterator > & it_range) inline static
        {
            // An asterix is added to the start of the string to differentiate the boost::spirit::info::tag content
            // between the grammer terminal / non-terminal symbol name and a free-form error message.
            boost::throw_exception(qi::expectation_failure<Iterator>(it_range.begin(), it_range.end(), spirit::info(std::string("*") + msg)));
        }
Referenced by legacy_variable_expansion(), legacy_variable_expansion2(), Slic3r::client::utf8_char_skipper_parser::parse(), random(), resolve_variable(), scalar_variable_reference(), and vector_variable_reference().
vector_variable_reference()
template<typename Iterator > static void Slic3r::client::MyContext::vector_variable_reference (const MyContext * ctx, OptWithPos< Iterator > & opt, int & index, Iterator it_end, expr< Iterator > & output) inline static
        {
            if (opt.opt->is_scalar())
                ctx->throw_exception("Referencing a scalar variable when vector is expected", opt.it_range);
            const ConfigOptionVectorBase *vec = static_cast<const ConfigOptionVectorBase*>(opt.opt);
            if (vec->empty())
                ctx->throw_exception("Indexing an empty vector variable", opt.it_range);
            size_t idx = (index < 0) ? 0 : (index >= int(vec->size())) ? 0 : size_t(index);
            switch (opt.opt->type()) {
            case coFloats:   output.set_d(static_cast<const ConfigOptionFloats  *>(opt.opt)->values[idx]); break;
            case coInts:     output.set_i(static_cast<const ConfigOptionInts    *>(opt.opt)->values[idx]); break;
            case coStrings:  output.set_s(static_cast<const ConfigOptionStrings *>(opt.opt)->values[idx]); break;
            case coPercents: output.set_d(static_cast<const ConfigOptionPercents*>(opt.opt)->values[idx]); break;
            case coPoints:   output.set_s(to_string(static_cast<const ConfigOptionPoints  *>(opt.opt)->values[idx])); break;
            case coBools:    output.set_b(static_cast<const ConfigOptionBools   *>(opt.opt)->values[idx] != 0); break;
            // BBS
            case coEnums:    output.set_i(static_cast<const ConfigOptionInts    *>(opt.opt)->values[idx]); break;
            default:
                ctx->throw_exception("Unknown vector variable type", opt.it_range);
            }
            output.it_range = boost::iterator_range<Iterator>(opt.it_range.begin(), it_end);
        }
References Slic3r::coBools, Slic3r::coEnums, Slic3r::coFloats, Slic3r::coInts, Slic3r::coPercents, Slic3r::coPoints, Slic3r::coStrings, Slic3r::ConfigOptionVectorBase::empty(), int, Slic3r::ConfigOption::is_scalar(), Slic3r::client::OptWithPos< Iterator >::it_range, Slic3r::client::expr< Iterator >::it_range, Slic3r::client::OptWithPos< Iterator >::opt, Slic3r::client::expr< Iterator >::set_b(), Slic3r::client::expr< Iterator >::set_d(), Slic3r::client::expr< Iterator >::set_i(), Slic3r::client::expr< Iterator >::set_s(), Slic3r::ConfigOptionVectorBase::size(), throw_exception(), Slic3r::to_string(), Slic3r::ConfigOption::type(), and Slic3r::ConfigOptionVector< T >::values.
Member Data Documentation
config
const DynamicConfig* Slic3r::client::MyContext::config = nullptr
Referenced by Slic3r::PlaceholderParser::evaluate_boolean_expression(), optptr(), and Slic3r::PlaceholderParser::process().
config_override
const DynamicConfig* Slic3r::client::MyContext::config_override = nullptr
Referenced by Slic3r::PlaceholderParser::evaluate_boolean_expression(), optptr(), and Slic3r::PlaceholderParser::process().
context_data
PlaceholderParser::ContextData* Slic3r::client::MyContext::context_data = nullptr
Referenced by Slic3r::PlaceholderParser::process(), and random().
current_extruder_id
size_t Slic3r::client::MyContext::current_extruder_id = 0
Referenced by legacy_variable_expansion(), Slic3r::PlaceholderParser::process(), and scalar_variable_reference().
error_message
std::string Slic3r::client::MyContext::error_message
Referenced by process_error_message(), and Slic3r::process_macro().
external_config
const DynamicConfig* Slic3r::client::MyContext::external_config = nullptr
Referenced by optptr(), and Slic3r::PlaceholderParser::process().
just_boolean_expression
bool Slic3r::client::MyContext::just_boolean_expression = false
Referenced by Slic3r::PlaceholderParser::evaluate_boolean_expression(), and evaluate_full_macro().
tag_to_error_message
std::map< std::string, std::string > Slic3r::client::MyContext::tag_to_error_message static
Initial value:
= {
        { "eoi",                        "Unknown syntax error" },
        { "start",                      "Unknown syntax error" },
        { "text",                       "Invalid text." },
        { "text_block",                 "Invalid text block." },
        { "macro",                      "Invalid macro." },
        { "if_else_output",             "Not an {if}{else}{endif} macro." },
        { "switch_output",              "Not a {switch} macro." },
        { "legacy_variable_expansion",  "Expecting a legacy variable expansion format" },
        { "identifier",                 "Expecting an identifier." },
        { "conditional_expression",     "Expecting a conditional expression." },
        { "logical_or_expression",      "Expecting a boolean expression." },
        { "logical_and_expression",     "Expecting a boolean expression." },
        { "equality_expression",        "Expecting an expression." },
        { "bool_expr_eval",             "Expecting a boolean expression."},
        { "relational_expression",      "Expecting an expression." },
        { "additive_expression",        "Expecting an expression." },
        { "multiplicative_expression",  "Expecting an expression." },
        { "unary_expression",           "Expecting an expression." },
        { "optional_parameter",         "Expecting a closing brace or an optional parameter." },
        { "scalar_variable_reference",  "Expecting a scalar variable reference."},
        { "variable_reference",         "Expecting a variable reference."},
        { "regular_expression",         "Expecting a regular expression."}
    }
Referenced by process_error_message().
The documentation for this struct was generated from the following file:
src/libslic3r/PlaceholderParser.cpp