OrcaSlicer: Slic3r::GUI::BBLSplashScreen Class Reference
Slic3r::GUI::BBLSplashScreen Class Reference
Classes
struct ConstantText
Public Member Functions
BBLSplashScreen (const wxBitmap &bitmap, long splashStyle, int milliseconds, wxPoint pos=wxDefaultPosition)
void SetText (const wxString &text)
void Decorate (wxBitmap &bmp)
void set_bitmap (wxBitmap &bmp)
void scale_bitmap (wxBitmap &bmp, float scale)
void scale_font (wxFont &font, float scale)
Static Public Member Functions
static wxBitmap MakeBitmap ()
Private Attributes
wxStaticText * m_staticText_slicer_name
wxStaticText * m_staticText_slicer_version
wxStaticBitmap * m_bitmap
wxStaticText * m_staticText_loading
wxBitmap m_main_bitmap
wxFont m_action_font
int m_action_line_y_position
float m_scale {1.0}
struct Slic3r::GUI::BBLSplashScreen::ConstantText m_constant_text
Detailed Description
Constructor & Destructor Documentation
BBLSplashScreen()
Slic3r::GUI::BBLSplashScreen::BBLSplashScreen (const wxBitmap & bitmap, long splashStyle, int milliseconds, wxPoint pos = wxDefaultPosition) inline
        : wxSplashScreen(bitmap, splashStyle, milliseconds, static_cast<wxWindow*>(wxGetApp().mainframe), wxID_ANY, wxDefaultPosition, wxDefaultSize,
#ifdef __APPLE__
            wxBORDER_NONE | wxFRAME_NO_TASKBAR | wxSTAY_ON_TOP
#else
            wxBORDER_NONE | wxFRAME_NO_TASKBAR
#endif // !__APPLE__
        )
    {
        int init_dpi = get_dpi_for_window(this);
        this->SetPosition(pos);
        this->CenterOnScreen();
        int new_dpi = get_dpi_for_window(this);
        m_scale = (float)(new_dpi) / (float)(init_dpi);
        m_main_bitmap = bitmap;
        scale_bitmap(m_main_bitmap, m_scale);
        // init constant texts and scale fonts
        m_constant_text.init(Label::Body_16);
        scale_font(m_constant_text.title_font, 2.0f);
        scale_font(m_constant_text.version_font, 1.2f);
        // this font will be used for the action string
        m_action_font = m_constant_text.credits_font;
        // draw logo and constant info text
        Decorate(m_main_bitmap);
        wxGetApp().UpdateFrameDarkUI(this);
    }
References Label::Body_16, Slic3r::GUI::BBLSplashScreen::ConstantText::credits_font, Decorate(), Slic3r::GUI::get_dpi_for_window(), Slic3r::GUI::BBLSplashScreen::ConstantText::init(), m_action_font, m_constant_text, m_main_bitmap, m_scale, scale_bitmap(), scale_font(), Slic3r::GUI::BBLSplashScreen::ConstantText::title_font, and Slic3r::GUI::BBLSplashScreen::ConstantText::version_font.
Member Function Documentation
Decorate()
void Slic3r::GUI::BBLSplashScreen::Decorate (wxBitmap & bmp) inline
    {
        if (!bmp.IsOk())
            return;
        // use a memory DC to draw directly onto the bitmap
        wxMemoryDC memDc(bmp);
        int top_margin = FromDIP(75 * m_scale);
        int width = bmp.GetWidth();
        // draw title and version
        int text_padding = FromDIP(3 * m_scale);
        memDc.SetFont(m_constant_text.title_font);
        int title_height = memDc.GetTextExtent(m_constant_text.title).GetHeight();
        int title_width = memDc.GetTextExtent(m_constant_text.title).GetWidth();
        memDc.SetFont(m_constant_text.version_font);
        int version_height = memDc.GetTextExtent(m_constant_text.version).GetHeight();
        int version_width = memDc.GetTextExtent(m_constant_text.version).GetWidth();
        int split_width = (width + title_width - version_width) / 2;
        wxRect title_rect(wxPoint(0, top_margin), wxPoint(split_width - text_padding, top_margin + title_height));
        memDc.SetTextForeground(StateColor::darkModeColorFor(wxColour(38, 46, 48)));
        memDc.SetFont(m_constant_text.title_font);
        memDc.DrawLabel(m_constant_text.title, title_rect, wxALIGN_RIGHT | wxALIGN_BOTTOM);
        //BBS align bottom of title and version text
        wxRect version_rect(wxPoint(split_width + text_padding, top_margin), wxPoint(width, top_margin + title_height - text_padding));
        memDc.SetFont(m_constant_text.version_font);
        memDc.SetTextForeground(StateColor::darkModeColorFor(wxColor(134, 134, 134)));
        memDc.DrawLabel(m_constant_text.version, version_rect, wxALIGN_LEFT | wxALIGN_BOTTOM);
        auto bs_version = wxString::Format("Based on BambuStudio and PrusaSlicer").ToStdString();
        memDc.SetFont(Label::Body_12);
        wxSize text_rect = memDc.GetTextExtent(bs_version);
        int start_x = (title_rect.GetLeft() + version_rect.GetRight()) / 2 - text_rect.GetWidth()/2;
        int start_y = version_rect.GetBottom() + 10;
        wxRect internal_sign_rect(wxPoint(start_x, start_y), wxSize(text_rect));
        memDc.DrawLabel(bs_version, internal_sign_rect, wxALIGN_RIGHT);
        // load bitmap for logo
        BitmapCache bmp_cache;
        int logo_margin = FromDIP(72 * m_scale);
        int logo_size = FromDIP(122 * m_scale);
        int logo_width = FromDIP(94 * m_scale);
        wxBitmap logo_bmp = *bmp_cache.load_svg("splash_logo", logo_size, logo_size);
        int logo_y = top_margin + title_rect.GetHeight() + logo_margin;
        memDc.DrawBitmap(logo_bmp, (width - logo_width) / 2, logo_y, true);
        // calculate position for the dynamic text
        int text_margin = FromDIP(80 * m_scale);
        m_action_line_y_position = logo_y + logo_size + text_margin;
    }
References Label::Body_12, StateColor::darkModeColorFor(), Slic3r::GUI::BitmapCache::load_svg(), m_action_line_y_position, m_constant_text, m_scale, Slic3r::GUI::BBLSplashScreen::ConstantText::title, Slic3r::GUI::BBLSplashScreen::ConstantText::title_font, Slic3r::GUI::BBLSplashScreen::ConstantText::version, and Slic3r::GUI::BBLSplashScreen::ConstantText::version_font.
Referenced by BBLSplashScreen().
MakeBitmap()
static wxBitmap Slic3r::GUI::BBLSplashScreen::MakeBitmap () inline static
    {
        int width = FromDIP(480, nullptr);
        int height = FromDIP(480, nullptr);
        wxImage image(width, height);
        wxBitmap new_bmp(image);
        wxMemoryDC memDC;
        memDC.SelectObject(new_bmp);
        memDC.SetBrush(StateColor::darkModeColorFor(*wxWHITE));
        memDC.DrawRectangle(-1, -1, width + 2, height + 2);
        memDC.DrawBitmap(new_bmp, 0, 0, true);
        return new_bmp;
    }
References StateColor::darkModeColorFor().
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
scale_bitmap()
void Slic3r::GUI::BBLSplashScreen::scale_bitmap (wxBitmap & bmp, float scale) inline
    {
        if (scale == 1.0)
            return;
        wxImage image = bmp.ConvertToImage();
        if (!image.IsOk() || image.GetWidth() == 0 || image.GetHeight() == 0)
            return;
        int width   = int(scale * image.GetWidth());
        int height  = int(scale * image.GetHeight());
        image.Rescale(width, height, wxIMAGE_QUALITY_BILINEAR);
        bmp = wxBitmap(std::move(image));
    }
References int, and scale().
Referenced by BBLSplashScreen().
scale_font()
void Slic3r::GUI::BBLSplashScreen::scale_font (wxFont & font, float scale) inline
    {
#ifdef __WXMSW__
        // Workaround for the font scaling in respect to the current active display,
        // not for the primary display, as it's implemented in Font.cpp
        // See https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/font.cpp
        // void wxNativeFontInfo::SetFractionalPointSize(float pointSizeNew)
        wxNativeFontInfo nfi= *font.GetNativeFontInfo();
        float pointSizeNew  = scale * font.GetPointSize();
        nfi.lf.lfHeight     = nfi.GetLogFontHeightAtPPI(pointSizeNew, get_dpi_for_window(this));
        nfi.pointSize       = pointSizeNew;
        font = wxFont(nfi);
#else
        font.Scale(scale);
#endif //__WXMSW__
    }
References Slic3r::GUI::get_dpi_for_window(), and scale().
Referenced by BBLSplashScreen().
set_bitmap()
void Slic3r::GUI::BBLSplashScreen::set_bitmap (wxBitmap & bmp) inline
    {
        m_window->SetBitmap(bmp);
        m_window->Refresh();
        m_window->Update();
    }
Referenced by SetText().
SetText()
void Slic3r::GUI::BBLSplashScreen::SetText (const wxString & text) inline
    {
        set_bitmap(m_main_bitmap);
        if (!text.empty()) {
            wxBitmap bitmap(m_main_bitmap);
            wxMemoryDC memDC;
            memDC.SelectObject(bitmap);
            memDC.SetFont(m_action_font);
            memDC.SetTextForeground(StateColor::darkModeColorFor(wxColour(144, 144, 144)));
            int width = bitmap.GetWidth();
            int text_height = memDC.GetTextExtent(text).GetHeight();
            int text_width = memDC.GetTextExtent(text).GetWidth();
            wxRect text_rect(wxPoint(0, m_action_line_y_position), wxPoint(width, m_action_line_y_position + text_height));
            memDC.DrawLabel(text, text_rect, wxALIGN_CENTER);
            memDC.SelectObject(wxNullBitmap);
            set_bitmap(bitmap);
#ifdef __WXOSX__
            // without this code splash screen wouldn't be updated under OSX
            wxYield();
#endif
        }
    }
References StateColor::darkModeColorFor(), m_action_font, m_action_line_y_position, m_main_bitmap, and set_bitmap().
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
Member Data Documentation
m_action_font
wxFont Slic3r::GUI::BBLSplashScreen::m_action_font private
Referenced by BBLSplashScreen(), and SetText().
m_action_line_y_position
int Slic3r::GUI::BBLSplashScreen::m_action_line_y_position private
Referenced by Decorate(), and SetText().
m_bitmap
wxStaticBitmap* Slic3r::GUI::BBLSplashScreen::m_bitmap private
m_constant_text
struct Slic3r::GUI::BBLSplashScreen::ConstantText Slic3r::GUI::BBLSplashScreen::m_constant_text private
Referenced by BBLSplashScreen(), and Decorate().
m_main_bitmap
wxBitmap Slic3r::GUI::BBLSplashScreen::m_main_bitmap private
Referenced by BBLSplashScreen(), and SetText().
m_scale
float Slic3r::GUI::BBLSplashScreen::m_scale {1.0} private
Referenced by BBLSplashScreen(), and Decorate().
m_staticText_loading
wxStaticText* Slic3r::GUI::BBLSplashScreen::m_staticText_loading private
m_staticText_slicer_name
wxStaticText* Slic3r::GUI::BBLSplashScreen::m_staticText_slicer_name private
m_staticText_slicer_version
wxStaticText* Slic3r::GUI::BBLSplashScreen::m_staticText_slicer_version private
The documentation for this class was generated from the following file:
src/slic3r/GUI/GUI_App.cpp