OrcaSlicer: Slic3r::Search::SearchItem Class Reference
Slic3r::Search::SearchItem Class Reference
#include <src/slic3r/GUI/Search.hpp>
Public Member Functions
SearchItem (wxWindow *parent, wxString text, int index, SearchDialog *sdialog)
~SearchItem ()
wxSize DrawTextString (wxDC &dc, const wxString &text, const wxPoint &pt, bool bold)
void OnPaint (wxPaintEvent &event)
void on_mouse_enter (wxMouseEvent &evt)
void on_mouse_leave (wxMouseEvent &evt)
void on_mouse_left_down (wxMouseEvent &evt)
void on_mouse_left_up (wxMouseEvent &evt)
Public Attributes
wxString m_text
int m_index
SearchDialog * m_sdialog
Detailed Description
Constructor & Destructor Documentation
SearchItem()
Slic3r::Search::SearchItem::SearchItem (wxWindow * parent, wxString text, int index, SearchDialog * sdialog)
    : wxWindow(parent, wxID_ANY, wxDefaultPosition, wxSize(parent->GetSize().GetWidth(), 3 * GUI::wxGetApp().em_unit()))
{
    m_sdialog = sdialog;
    m_text  = text;
    m_index = index;
    SetBackgroundColour(StateColor::darkModeColorFor(wxColour("#FFFFFF")));
    Bind(wxEVT_ENTER_WINDOW, &SearchItem::on_mouse_enter, this);
    Bind(wxEVT_LEAVE_WINDOW, &SearchItem::on_mouse_leave, this);
    Bind(wxEVT_LEFT_DOWN, &SearchItem::on_mouse_left_down, this);
    Bind(wxEVT_LEFT_UP, &SearchItem::on_mouse_left_up, this);
    Bind(wxEVT_PAINT, &SearchItem::OnPaint, this);
}
References StateColor::darkModeColorFor(), m_index, m_sdialog, m_text, on_mouse_enter(), on_mouse_leave(), on_mouse_left_down(), on_mouse_left_up(), and OnPaint().
~SearchItem()
Slic3r::Search::SearchItem::~SearchItem () inline
{};
Member Function Documentation
DrawTextString()
wxSize Slic3r::Search::SearchItem::DrawTextString (wxDC & dc, const wxString & text, const wxPoint & pt, bool bold)
{
    if (bold) {
        dc.SetFont(Label::Head_14);
    } else {
        dc.SetFont(Label::Body_14);
    }
    dc.SetBackgroundMode(wxTRANSPARENT);
    dc.SetTextForeground(StateColor::darkModeColorFor(wxColour("#323A3C")));
    dc.DrawText(text, pt);
    return dc.GetTextExtent(text);
}
References Label::Body_14, StateColor::darkModeColorFor(), and Label::Head_14.
Referenced by OnPaint().
on_mouse_enter()
void Slic3r::Search::SearchItem::on_mouse_enter (wxMouseEvent & evt)
{
    SetBackgroundColour(StateColor::darkModeColorFor(wxColour(238, 238, 238)));
    Refresh();
}
References StateColor::darkModeColorFor().
Referenced by SearchItem().
on_mouse_leave()
void Slic3r::Search::SearchItem::on_mouse_leave (wxMouseEvent & evt)
{
    SetBackgroundColour(StateColor::darkModeColorFor(wxColour(255, 255, 255)));
    Refresh();
}
References StateColor::darkModeColorFor().
Referenced by SearchItem().
on_mouse_left_down()
void Slic3r::Search::SearchItem::on_mouse_left_down (wxMouseEvent & evt)
{
    SetBackgroundColour(StateColor::darkModeColorFor(wxColour(228, 228, 228)));
    Refresh();
}
References StateColor::darkModeColorFor().
Referenced by SearchItem().
on_mouse_left_up()
void Slic3r::Search::SearchItem::on_mouse_left_up (wxMouseEvent & evt)
{
    //if (m_sdialog->prevent_list_events) return;
    // if (wxGetMouseState().LeftIsDown())
    m_sdialog->Die();
    wxCommandEvent event(wxCUSTOMEVT_JUMP_TO_OPTION);
    event.SetInt(m_index);
    wxPostEvent(GUI::wxGetApp().plater(), event);
}
References Slic3r::Search::SearchDialog::Die(), m_index, and m_sdialog.
Referenced by SearchItem().
OnPaint()
void Slic3r::Search::SearchItem::OnPaint (wxPaintEvent & event)
{
    wxPaintDC dc(this);
    auto      top  = 5;
    int       left = 20;
    auto bold_pair = std::vector<std::pair<int, int>>();
    auto index     = 0;
    auto b_first_list  = std::vector<int>();
    auto b_second_list = std::vector<int>();
    auto position      = 0;
    while ((position = m_text.find("<b>", position)) != wxString::npos) {
        b_first_list.push_back(position);
        position++;
    }
    position = 0;
    while ((position = m_text.find("</b>", position)) != wxString::npos) {
        b_second_list.push_back(position + 3);
        position++;
    }
    if (b_first_list.size() != b_second_list.size()) { return; }
    for (auto i = 0; i < b_first_list.size(); i++) {
        auto pair = std::make_pair(b_first_list[i], b_second_list[i]);
        bold_pair.push_back(pair);
    }
    //DrawTextString(dc, m_text, wxPoint(left, top), false);
    /*if (bold_pair.size() <= 0) {
        DrawTextString(dc, m_text, wxPoint(left, top), false);
    } else {
        auto index = 0;
        for (auto i = 0; i < bold_pair.size(); i++) { DrawTextString(dc, m_text.SubString(index, bold_pair[i].second), wxPoint(left, top), true); }
    }*/
    auto str = wxString("");
    for (auto c = 0; c < m_text.length(); c++) {
        str = m_text[c];
        auto inset = false;
        auto pair_index = 0;
        for (auto o = 0; o < bold_pair.size(); o++) {
            if (c >= bold_pair[o].first && c <= bold_pair[o].second) {
                pair_index = o;
                inset = true;
                break;
            }
        }
        if (!inset) {
            left += DrawTextString(dc, str, wxPoint(left, top), false).GetWidth();
        } else {
            //str = str.erase(bold_pair[pair_index].first, 3);
            //str = str.erase(bold_pair[pair_index].second, 4);
            if (c - bold_pair[pair_index].first >= 3 && bold_pair[pair_index].second - c > 3) {
                left += DrawTextString(dc, str, wxPoint(left, top), true).GetWidth();
            }
        }
    }
}
References DrawTextString(), and m_text.
Referenced by SearchItem().
Member Data Documentation
m_index
int Slic3r::Search::SearchItem::m_index
Referenced by SearchItem(), and on_mouse_left_up().
m_sdialog
SearchDialog* Slic3r::Search::SearchItem::m_sdialog
Referenced by SearchItem(), and on_mouse_left_up().
m_text
wxString Slic3r::Search::SearchItem::m_text
Referenced by SearchItem(), and OnPaint().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Search.hpp
src/slic3r/GUI/Search.cpp