OrcaSlicer: vec2_< T > Class Template Reference
vec2_< T > Class Template Reference
#include <src/mcut/include/mcut/internal/math.h>
Public Types
typedef T element_type
Public Member Functions
vec2_ ()
vec2_ (const T &value)
vec2_ (const T &x, const T &y)
virtual ~vec2_ ()
bool operator== (const vec2_< T > &other) const
const T & operator[] (int index) const
T & operator[] (int index)
const vec2_ operator- (const vec2_ &other) const
const vec2_ operator+ (const vec2_ &other) const
const vec2_ operator/ (const T &number) const
const vec2_ operator* (const T &number) const
const T & x () const
const T & y () const
T & x ()
T & y ()
Static Public Member Functions
static vec2_ make (const T x, const T y)
static int cardinality ()
Protected Attributes
T m_x
T m_y
Detailed Description
template<typename T = double>
class vec2_< T >
Member Typedef Documentation
element_type
template<typename T = double> typedef T vec2_< T >::element_type
Constructor & Destructor Documentation
vec2_() [1/3]
template<typename T = double> vec2_< T >::vec2_ () inline
        : m_x(0.0)
        , m_y(0.0)
    {
    }
Referenced by vec2_< T >::operator*(), vec2_< T >::operator+(), vec2_< T >::operator-(), and vec2_< T >::operator/().
vec2_() [2/3]
template<typename T = double> vec2_< T >::vec2_ (const T & value) inline
        : m_x(value)
        , m_y(value)
    {
    }
vec2_() [3/3]
template<typename T = double> vec2_< T >::vec2_ (const T & x, const T & y) inline
        : m_x(x)
        , m_y(y)
    {
    }
~vec2_()
template<typename T = double> virtual vec2_< T >::~vec2_ () inline virtual
    {
    }
Member Function Documentation
cardinality()
template<typename T = double> static int vec2_< T >::cardinality () inline static
    {
        return 2;
    }
Referenced by matrix_t< T >::operator*().
make()
template<typename T = double> static vec2_ vec2_< T >::make (const T x, const T y) inline static
    {
        return vec2_<T>(x, y);
    }
References vec2_< T >::x(), and vec2_< T >::y().
Referenced by cdt::detail::get_intersection_point_coords(), and cdt::locator_kdtree_t< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initialize().
operator*()
template<typename T = double> const vec2_ vec2_< T >::operator* (const T & number) const inline
    {
        return vec2_(m_x * number, m_y * number);
    }
References vec2_< T >::vec2_(), vec2_< T >::m_x, and vec2_< T >::m_y.
operator+()
template<typename T = double> const vec2_ vec2_< T >::operator+ (const vec2_< T > & other) const inline
    {
        return vec2_(m_x + other.m_x, m_y + other.m_y);
    }
References vec2_< T >::vec2_(), vec2_< T >::m_x, and vec2_< T >::m_y.
operator-()
template<typename T = double> const vec2_ vec2_< T >::operator- (const vec2_< T > & other) const inline
    {
        return vec2_(m_x - other.m_x, m_y - other.m_y);
    }
References vec2_< T >::vec2_(), vec2_< T >::m_x, and vec2_< T >::m_y.
operator/()
template<typename T = double> const vec2_ vec2_< T >::operator/ (const T & number) const inline
    {
        return vec2_(m_x / number, m_y / number);
    }
References vec2_< T >::vec2_(), vec2_< T >::m_x, and vec2_< T >::m_y.
operator==()
template<typename T = double> bool vec2_< T >::operator== (const vec2_< T > & other) const inline
    {
        return this->m_x == other.x() && this->m_y == other.y();
    }
References vec2_< T >::m_x, vec2_< T >::m_y, vec2_< T >::x(), and vec2_< T >::y().
operator[]() [1/2]
template<typename T = double> T & vec2_< T >::operator[] (int index) inline
    {
        MCUT_ASSERT(index >= 0 && index <= 1);
        if (index == 0) {
            return m_x;
        }
            return m_y;
    }
References vec2_< T >::m_x, vec2_< T >::m_y, and MCUT_ASSERT.
operator[]() [2/2]
template<typename T = double> const T & vec2_< T >::operator[] (int index) const inline
    {
        MCUT_ASSERT(index >= 0 && index <= 1);
        if (index == 0) {
            return m_x;
        } else {
            return m_y;
        }
    }
References vec2_< T >::m_x, vec2_< T >::m_y, and MCUT_ASSERT.
x() [1/2]
template<typename T = double> T & vec2_< T >::x () inline
    {
        return m_x;
    }
References vec2_< T >::m_x.
x() [2/2]
template<typename T = double> const T & vec2_< T >::x () const inline
    {
        return m_x;
    }
References vec2_< T >::m_x.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::add_super_triangle(), hmesh_t::add_vertex(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo(), cdt::check_is_in_circumcircle(), compute_point_in_polygon_test(), Clipper2Lib::CrossProduct(), Clipper2Lib::DotProduct(), cdt::box2d_t< T >::expand_with_point(), cdt::box2d_t< T >::expand_with_point(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), cdt::get_x_coord_vec2d(), Clipper2Lib::GetAvgUnitVector(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), intersect_bounding_boxes(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::isInsideBox(), vec2_< T >::make(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest(), std::hash< vec2_< T > >::operator()(), operator<<(), cdt::operator==(), vec2_< T >::operator==(), orient2d(), orient3d(), point_in_bounding_box(), point_in_bounding_box(), resolve_floating_polygons(), triangulate_face(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::whichChild(), and write_off().
y() [1/2]
template<typename T = double> T & vec2_< T >::y () inline
    {
        return m_y;
    }
References vec2_< T >::m_y.
y() [2/2]
template<typename T = double> const T & vec2_< T >::y () const inline
    {
        return m_y;
    }
References vec2_< T >::m_y.
Referenced by cdt::triangulator_t< T, TNearPointLocator >::add_super_triangle(), hmesh_t::add_vertex(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::calcSplitInfo(), cdt::check_is_in_circumcircle(), compute_point_in_polygon_test(), Clipper2Lib::CrossProduct(), Clipper2Lib::DotProduct(), cdt::box2d_t< T >::expand_with_point(), cdt::box2d_t< T >::expand_with_point(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::extendTree(), cdt::get_y_coord_vec2d(), Clipper2Lib::GetAvgUnitVector(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::initializeRootBox(), intersect_bounding_boxes(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::isInsideBox(), vec2_< T >::make(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::nearest(), std::hash< vec2_< T > >::operator()(), operator<<(), cdt::operator==(), vec2_< T >::operator==(), orient2d(), orient3d(), point_in_bounding_box(), point_in_bounding_box(), resolve_floating_polygons(), triangulate_face(), kdt::kdtree_t_< TCoordType, NumVerticesInLeaf, InitialStackDepth, StackDepthIncrement >::whichChild(), and write_off().
Member Data Documentation
m_x
template<typename T = double> T vec2_< T >::m_x protected
Referenced by vec2_< T >::operator*(), vec3_< T >::operator*(), vec2_< T >::operator+(), vec3_< T >::operator+(), vec2_< T >::operator-(), vec3_< T >::operator-(), vec2_< T >::operator/(), vec3_< T >::operator/(), vec2_< T >::operator==(), vec2_< T >::operator[](), vec3_< T >::operator[](), vec2_< T >::operator[](), vec3_< T >::operator[](), vec2_< T >::x(), and vec2_< T >::x().
m_y
template<typename T = double> T vec2_< T >::m_y protected
Referenced by vec2_< T >::operator*(), vec3_< T >::operator*(), vec2_< T >::operator+(), vec3_< T >::operator+(), vec2_< T >::operator-(), vec3_< T >::operator-(), vec2_< T >::operator/(), vec3_< T >::operator/(), vec2_< T >::operator==(), vec2_< T >::operator[](), vec3_< T >::operator[](), vec2_< T >::operator[](), vec3_< T >::operator[](), vec2_< T >::y(), and vec2_< T >::y().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/math.h