OrcaSlicer: src/qhull/src/libqhullcpp/RboxPoints.cpp File Reference
RboxPoints.cpp File Reference
#include "libqhullcpp/RboxPoints.h"
#include "libqhullcpp/QhullError.h"
#include <iostream>
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global functions
void qh_fprintf_rbox (qhT *qh, FILE *, int msgcode, const char *fmt,...)
Function Documentation
qh_fprintf_rbox()
void qh_fprintf_rbox (qhT * qh, FILE * fp, int msgcode, const char * fmt, ...)
{
    va_list args;
    using namespace orgQhull;
    if(!qh->cpp_object){
        qh_errexit_rbox(qh, 10072);
    }
    RboxPoints *out= reinterpret_cast<RboxPoints *>(qh->cpp_object);
    va_start(args, fmt);
    if(msgcode<MSG_OUTPUT){
        char newMessage[MSG_MAXLEN];
        // RoadError provides the message tag
        vsnprintf(newMessage, sizeof(newMessage), fmt, args);
        out->rbox_message += newMessage;
        if(out->rbox_status<MSG_ERROR || out->rbox_status>=MSG_STDERR){
            out->rbox_status= msgcode;
        }
        va_end(args);
        return;
    }
    switch(msgcode){
    case 9391:
    case 9392:
        out->rbox_message += "RboxPoints error: options 'h', 'n' not supported.\n";
        qh_errexit_rbox(qh, 10010);
        /* never returns */
    case 9393:  // FIXUP QH11026 countT vs. int
        {
            int dimension= va_arg(args, int);
            string command(va_arg(args, char*));
            countT count= va_arg(args, countT);
            out->setDimension(dimension);
            out->appendComment(" \"");
            out->appendComment(command.substr(command.find(' ')+1));
            out->appendComment("\"");
            out->setNewCount(count);
            out->reservePoints();
        }
        break;
    case 9407:
        *out << va_arg(args, int);
        // fall through
    case 9405:
        *out << va_arg(args, int);
        // fall through
    case 9403:
        *out << va_arg(args, int);
        break;
    case 9408:
        *out << va_arg(args, double);
        // fall through
    case 9406:
        *out << va_arg(args, double);
        // fall through
    case 9404:
        *out << va_arg(args, double);
        break;
    }
    va_end(args);
} /* qh_fprintf_rbox */
References count, MSG_ERROR, MSG_MAXLEN, MSG_OUTPUT, MSG_STDERR, out, qh, qh_errexit_rbox(), and qh_fprintf_stderr().
Referenced by qh_out1(), qh_out2n(), qh_out3n(), qh_outcoincident(), qh_outcoord(), qh_rboxpoints(), and qh_roundi().