OrcaSlicer: orgQhull::QhullError Class Reference
orgQhull::QhullError Class Reference
#include <src/qhull/src/libqhullcpp/QhullError.h>
Public Types
Constants
enum { QHULLfirstError = 10000 , QHULLlastError = 10078 , NOthrow = 1 }
Public Member Functions
Constructors
QhullError ()
QhullError (const QhullError &other)
QhullError (int code, const std::string &message)
QhullError (int code, const char *fmt)
QhullError (int code, const char *fmt, int d)
QhullError (int code, const char *fmt, int d, int d2)
QhullError (int code, const char *fmt, int d, int d2, float f)
QhullError (int code, const char *fmt, int d, int d2, float f, const char *s)
QhullError (int code, const char *fmt, int d, int d2, float f, const void *x)
QhullError (int code, const char *fmt, int d, int d2, float f, int i)
QhullError (int code, const char *fmt, int d, int d2, float f, long long i)
QhullError (int code, const char *fmt, int d, int d2, float f, double e)
QhullError & operator= (const QhullError &other)
~QhullError () throw ()
Virtual
virtual const char * what () const throw ()
GetSet
bool isValid () const
int errorCode () const
RoadLogEvent roadLogEvent () const
Update
void logErrorLastResort () const
Log error instead of throwing it. Not reentrant, so avoid using it if possible.
Static Public Member Functions
Class methods
static void clearGlobalLog ()
static bool emptyGlobalLog ()
static const char * stringGlobalLog ()
Private Attributes
Fields
int error_code
RoadLogEvent log_event
Non-zero code (not logged), maybe returned as program status.
std::string error_message
Format string w/ arguments.
Static Private Attributes
Class fields
Formated error message. Must be after log_event.
static const char * ROADtag = "QH"
Identifies error messages from Qhull and Road for web searches. See QhullError.h::QHULLlastError and user.h::MSG_ERROR.
static std::ostringstream global_log
May be replaced with any ostream object Not reentrant – only used by RoadError::logErrorLastResort()
Detailed Description
Member Enumeration Documentation
anonymous enum
anonymous enum
Enumerator
QHULLfirstError
QHULLlastError
NOthrow
         {
        QHULLfirstError= 10000, //MSG_QHULL_ERROR in Qhull's user.h
        QHULLlastError= 10078,
        NOthrow= 1
    };
Constructor & Destructor Documentation
QhullError() [1/12]
orgQhull::QhullError::QhullError () inline
: RoadError() {};
QhullError() [2/12]
orgQhull::QhullError::QhullError (const QhullError & other) inline
: RoadError(other) {}
QhullError() [3/12]
orgQhull::QhullError::QhullError (int code, const std::string & message) inline
: RoadError(code, message) {};
QhullError() [4/12]
orgQhull::QhullError::QhullError (int code, const char * fmt) inline
: RoadError(code, fmt) {};
QhullError() [5/12]
orgQhull::QhullError::QhullError (int code, const char * fmt, int d) inline
: RoadError(code, fmt, d) {};
QhullError() [6/12]
orgQhull::QhullError::QhullError (int code, const char * fmt, int d, int d2) inline
: RoadError(code, fmt, d, d2) {};
QhullError() [7/12]
orgQhull::QhullError::QhullError (int code, const char * fmt, int d, int d2, float f) inline
: RoadError(code, fmt, d, d2, f) {};
QhullError() [8/12]
orgQhull::QhullError::QhullError (int code, const char * fmt, int d, int d2, float f, const char * s) inline
: RoadError(code, fmt, d, d2, f, s) {};
QhullError() [9/12]
orgQhull::QhullError::QhullError (int code, const char * fmt, int d, int d2, float f, const void * x) inline
: RoadError(code, fmt, d, d2, f, x) {};
QhullError() [10/12]
orgQhull::QhullError::QhullError (int code, const char * fmt, int d, int d2, float f, int i) inline
: RoadError(code, fmt, d, d2, f, i) {};
QhullError() [11/12]
orgQhull::QhullError::QhullError (int code, const char * fmt, int d, int d2, float f, long long i) inline
: RoadError(code, fmt, d, d2, f, i) {};
QhullError() [12/12]
orgQhull::QhullError::QhullError (int code, const char * fmt, int d, int d2, float f, double e) inline
: RoadError(code, fmt, d, d2, f, e) {};
~QhullError()
orgQhull::QhullError::~QhullError () throw () inline
{}
Member Function Documentation
clearGlobalLog()
static void orgQhull::RoadError::clearGlobalLog () inline static inherited
{ global_log.seekp(0); }
References orgQhull::RoadError::global_log.
Referenced by orgQhull::QhullQh::clearQhullMessage(), and orgQhull::main().
emptyGlobalLog()
static bool orgQhull::RoadError::emptyGlobalLog () inline static inherited
{ return global_log.tellp()<=0; }
References orgQhull::RoadError::global_log.
Referenced by orgQhull::main().
errorCode()
int orgQhull::RoadError::errorCode () const inline inherited
{ return error_code; };
References orgQhull::RoadError::error_code.
Referenced by main().
isValid()
bool orgQhull::RoadError::isValid () const inline inherited
{ return log_event.isValid(); }
References orgQhull::RoadLogEvent::isValid(), and orgQhull::RoadError::log_event.
logErrorLastResort()
void orgQhull::RoadError::logErrorLastResort () const inherited
Log error instead of throwing it. Not reentrant, so avoid using it if possible.
{
    global_log << what() << endl;
}//logError
References orgQhull::RoadError::global_log, and orgQhull::RoadError::what().
Referenced by orgQhull::QhullQh::maybeThrowQhullMessage().
operator=()
QhullError & orgQhull::QhullError::operator= (const QhullError & other) inline
{ this->RoadError::operator=(other); return *this; }
References orgQhull::RoadError::operator=().
roadLogEvent()
RoadLogEvent orgQhull::RoadError::roadLogEvent () const inline inherited
{ return log_event; };
References orgQhull::RoadError::log_event.
stringGlobalLog()
static const char * orgQhull::RoadError::stringGlobalLog () inline static inherited
{ return global_log.str().c_str(); }
References orgQhull::RoadError::global_log.
Referenced by orgQhull::main().
what()
const char * orgQhull::RoadError::what () const throw () virtual inherited
{
    if(error_message.empty()){
        error_message= log_event.toString(ROADtag, error_code);
    }
    return error_message.c_str();
}//what
References orgQhull::RoadError::error_code, orgQhull::RoadError::error_message, orgQhull::RoadError::log_event, orgQhull::RoadError::ROADtag, and orgQhull::RoadLogEvent::toString().
Referenced by orgQhull::RoadError::logErrorLastResort(), main(), operator<<(), and operator<<().
Member Data Documentation
error_code
int orgQhull::RoadError::error_code private inherited
Referenced by orgQhull::RoadError::errorCode(), orgQhull::RoadError::operator=(), and orgQhull::RoadError::what().
error_message
std::string orgQhull::RoadError::error_message mutable private inherited
Format string w/ arguments.
Referenced by orgQhull::RoadError::RoadError(), orgQhull::RoadError::operator=(), and orgQhull::RoadError::what().
global_log
std::ostringstream orgQhull::RoadError::global_log static private inherited
May be replaced with any ostream object Not reentrant – only used by RoadError::logErrorLastResort()
Referenced by orgQhull::RoadError::clearGlobalLog(), orgQhull::RoadError::emptyGlobalLog(), orgQhull::RoadError::logErrorLastResort(), and orgQhull::RoadError::stringGlobalLog().
log_event
RoadLogEvent orgQhull::RoadError::log_event private inherited
Non-zero code (not logged), maybe returned as program status.
Referenced by orgQhull::RoadError::RoadError(), orgQhull::RoadError::isValid(), orgQhull::RoadError::operator=(), orgQhull::RoadError::roadLogEvent(), and orgQhull::RoadError::what().
ROADtag
const char * orgQhull::RoadError::ROADtag = "QH" static private inherited
Identifies error messages from Qhull and Road for web searches. See QhullError.h::QHULLlastError and user.h::MSG_ERROR.
Referenced by orgQhull::RoadError::what().
The documentation for this class was generated from the following file:
src/qhull/src/libqhullcpp/QhullError.h