OrcaSlicer: Slic3r::GUI::BundleMap Struct Reference
Slic3r::GUI::BundleMap Struct Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Public Member Functions
Bundle & bbl_bundle ()
const Bundle & bbl_bundle () const
Static Public Member Functions
static BundleMap load ()
Public Attributes
K keys
STL member.
T elements
STL member.
Detailed Description
Member Function Documentation
bbl_bundle() [1/2]
Bundle & Slic3r::GUI::BundleMap::bbl_bundle ()
{
    //BBS: add BBL as default
    auto it = find(PresetBundle::BBL_BUNDLE);
    if (it == end()) {
        throw Slic3r::RuntimeError("ConfigWizard: Internal error in BundleMap: BBL_BUNDLE not loaded");
    }
    return it->second;
}
References Slic3r::PresetBundle::BBL_BUNDLE, and end.
Referenced by bbl_bundle(), and load().
bbl_bundle() [2/2]
const Bundle & Slic3r::GUI::BundleMap::bbl_bundle () const
{
    return const_cast<BundleMap*>(this)->bbl_bundle();
}
References bbl_bundle().
load()
BundleMap Slic3r::GUI::BundleMap::load () static
{
    BundleMap res;
    //BBS: change directories by design
    const auto vendor_dir = (boost::filesystem::path(Slic3r::data_dir()) / PRESET_SYSTEM_DIR).make_preferred();
    const auto rsrc_vendor_dir = (boost::filesystem::path(resources_dir()) / "profiles").make_preferred();
    //BBS: add BBL as default
    //BBS: add json logic for vendor bundle
    auto bbl_bundle_path = (vendor_dir / PresetBundle::BBL_BUNDLE).replace_extension(".json");
    auto bbl_bundle_rsrc = false;
    if (!boost::filesystem::exists(bbl_bundle_path)) {
        bbl_bundle_path = (rsrc_vendor_dir / PresetBundle::BBL_BUNDLE).replace_extension(".json");
        bbl_bundle_rsrc = true;
    }
    {
        Bundle bbl_bundle;
        if (bbl_bundle.load(std::move(bbl_bundle_path), bbl_bundle_rsrc, true))
            res.emplace(PresetBundle::BBL_BUNDLE, std::move(bbl_bundle));
    }
    // Load the other bundles in the datadir/vendor directory
    // and then additionally from resources/profiles.
    bool is_in_resources = false;
    for (auto dir : { &vendor_dir, &rsrc_vendor_dir }) {
        for (const auto &dir_entry : boost::filesystem::directory_iterator(*dir)) {
            //BBS: add json logic for vendor bundle
            if (Slic3r::is_json_file(dir_entry.path().string())) {
                std::string id = dir_entry.path().stem().string();  // stem() = filename() without the trailing ".json" part
                // Don't load this bundle if we've already loaded it.
                if (res.find(id) != res.end()) { continue; }
                Bundle bundle;
                if (bundle.load(dir_entry.path(), is_in_resources))
                    res.emplace(std::move(id), std::move(bundle));
            }
        }
        is_in_resources = true;
    }
    return res;
}
References Slic3r::PresetBundle::BBL_BUNDLE, bbl_bundle(), Slic3r::data_dir(), Slic3r::is_json_file(), Slic3r::GUI::Bundle::load(), PRESET_SYSTEM_DIR, and Slic3r::resources_dir().
Referenced by Slic3r::GUI::ConfigWizard::priv::load_vendors().
Member Data Documentation
elements
T std::unordered_map< K, T >::elements inherited
STL member.
keys
K std::unordered_map< K, T >::keys inherited
STL member.
The documentation for this struct was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp