OrcaSlicer: Slic3r::Print Class Reference
Slic3r::Print Class Reference
#include <src/libslic3r/Print.hpp>
Public Types
enum ApplyStatus { APPLY_STATUS_UNCHANGED , APPLY_STATUS_CHANGED , APPLY_STATUS_INVALIDATED }
enum CancelStatus { NOT_CANCELED = 0 , CANCELED_BY_USER = 1 , CANCELED_INTERNAL = 2 }
typedef std::function< void(const SlicingStatus &)> status_callback_type
typedef std::function< void()> cancel_callback_type
using Timestamp = uint64_t
Public Member Functions
Print ()=default
virtual ~Print ()
PrinterTechnology technology () const noexcept override
void clear () override
bool empty () const override
std::vector< ObjectID > print_object_ids () const override
ApplyStatus apply (const Model &model, DynamicPrintConfig config) override
void process (bool use_cache=false) override
std::string export_gcode (const std::string &path_template, GCodeProcessorResult *result, ThumbnailsGeneratorCallback thumbnail_cb=nullptr)
int export_cached_data (const std::string &dir_path, bool with_space=false)
int load_cached_data (const std::string &directory)
bool is_step_done (PrintStep step) const
bool is_step_done (PrintObjectStep step) const
bool finished () const override
bool has_infinite_skirt () const
bool has_skirt () const
bool has_brim () const
bool has_auto_brim () const
StringObjectException validate (StringObjectException *warning=nullptr, Polygons *collison_polygons=nullptr, std::vector< std::pair< Polygon, float > > *height_polygons=nullptr) const override
double skirt_first_layer_height () const
Flow brim_flow () const
Flow skirt_flow () const
std::vector< unsigned int > object_extruders () const
std::vector< unsigned int > support_material_extruders () const
std::vector< unsigned int > extruders (bool conside_custom_gcode=false) const
double max_allowed_layer_height () const
bool has_support_material () const
void auto_assign_extruders (ModelObject *model_object) const
const PrintConfig & config () const
const PrintObjectConfig & default_object_config () const
const PrintRegionConfig & default_region_config () const
ConstPrintObjectPtrsAdaptor objects () const
PrintObject * get_object (size_t idx)
const PrintObject * get_object (size_t idx) const
const PrintObject * get_object (ObjectID object_id) const
std::map< ObjectID, ExtrusionEntityCollection > & get_brimMap ()
unsigned int num_object_instances () const
PrintObjectPtrs & objects_mutable ()
PrintRegionPtrs & print_regions_mutable ()
std::vector< size_t > layers_sorted_for_object (float start, float end, std::vector< LayerPtrs > &layers_of_objects, std::vector< BoundingBox > &boundingBox_for_objects, std::vector< Points > &objects_instances_shift)
const ExtrusionEntityCollection & skirt () const
const Polygon & first_layer_convex_hull () const
const PrintStatistics & print_statistics () const
PrintStatistics & print_statistics ()
bool has_wipe_tower () const
const WipeTowerData & wipe_tower_data (size_t filaments_cnt=0) const
const ToolOrdering & tool_ordering () const
bool enable_timelapse_print () const
std::string output_filename (const std::string &filename_base=std::string()) const override
size_t num_print_regions () const throw ()
const PrintRegion & get_print_region (size_t idx) const
const ToolOrdering & get_tool_ordering () const
void set_plate_origin (Vec3d origin)
const Vec3d get_plate_origin () const
void set_gcode_file_ready ()
void set_gcode_file_invalidated ()
void export_gcode_from_previous_file (const std::string &file, GCodeProcessorResult *result, ThumbnailsGeneratorCallback thumbnail_cb=nullptr)
int get_modified_count () const
bool is_support_used () const
std::string get_conflict_string () const
ConflictResultOpt get_conflict_result () const
std::vector< Point > first_layer_wipe_tower_corners (bool check_wipe_tower_existance=true) const
bool & is_BBL_printer ()
const bool is_BBL_printer () const
CalibMode & calib_mode ()
const CalibMode calib_mode () const
void set_calib_params (const Calib_Params &params)
const Calib_Params & calib_params () const
Vec2d translate_to_print_space (const Vec2d &point) const
Vec2d translate_to_print_space (const Point &point) const
PrintStateBase::StateWithTimeStamp step_state_with_timestamp (PrintStep step) const
PrintStateBase::StateWithWarnings step_state_with_warnings (PrintStep step) const
const Model & model () const
virtual void set_task (const TaskParams &params)
virtual void finalize ()
void set_status_default ()
void set_status_silent ()
void set_status_callback (status_callback_type cb)
void set_status (int percent, const std::string &message, unsigned int flags=SlicingStatus::DEFAULT, int warning_step=-1) const
void set_cancel_callback (cancel_callback_type cancel_callback)
CancelStatus cancel_status () const
bool canceled () const
void cancel ()
void cancel_internal ()
void restart ()
const PlaceholderParser & placeholder_parser () const
const DynamicPrintConfig & full_print_config () const
std::string output_filepath (const std::string &path, const std::string &filename_base=std::string()) const
int get_plate_index () const
void set_plate_index (int index)
bool get_no_check_flag () const
void set_no_check_flag (bool no_check)
std::string get_plate_name () const
void set_plate_name (const std::string &name)
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Member Functions
static StringObjectException sequential_print_clearance_valid (const Print &print, Polygons *polygons=nullptr, std::vector< std::pair< Polygon, float > > *height_polygons=nullptr)
static bool check_multi_filaments_compatibility (const std::vector< std::string > &filament_types)
Static Public Attributes
static float min_skirt_length = 0
Protected Member Functions
bool invalidate_step (PrintStep step)
bool set_started (PrintStep step)
PrintStateBase::TimeStamp set_done (PrintStep step)
bool invalidate_steps (StepTypeIterator step_begin, StepTypeIterator step_end)
bool invalidate_steps (std::initializer_list< PrintStep > il)
bool invalidate_all_steps ()
bool is_step_started_unguarded (PrintStep step) const
bool is_step_done_unguarded (PrintStep step) const
void active_step_add_warning (PrintStateBase::WarningLevel warning_level, const std::string &message, PrintStateBase::SlicingNotificationType message_id=PrintStateBase::SlicingDefaultNotification)
std::string output_filename (const std::string &format, const std::string &default_ext, const std::string &filename_base, const DynamicConfig *config_override=nullptr) const
std::mutex & state_mutex () const
std::function< void()> cancel_callback ()
void call_cancel_callback ()
void status_update_warnings (int step, PrintStateBase::WarningLevel warning_level, const std::string &message, const PrintObjectBase *print_object=nullptr, PrintStateBase::SlicingNotificationType message_id=PrintStateBase::SlicingDefaultNotification)
void status_update_warnings (int step, PrintStateBase::WarningLevel, const std::string &message, PrintObjectBase &object, PrintStateBase::SlicingNotificationType message_id=PrintStateBase::SlicingDefaultNotification)
void throw_if_canceled () const
PrintTryCancel make_try_cancel () const
void update_object_placeholders (DynamicConfig &config, const std::string &default_ext) const
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Protected Attributes
Model m_model
DynamicPrintConfig m_full_print_config
PlaceholderParser m_placeholder_parser
int m_plate_index { 0 }
bool m_no_check = false
std::string m_plate_name
status_callback_type m_status_callback
Private Types
typedef PrintBaseWithState< PrintStep, psCount > Inherited
typedef std::pair< PrintObject *, bool > PrintObjectInfo
Private Member Functions
bool invalidate_state_by_config_options (const ConfigOptionResolver &new_config, const std::vector< t_config_option_key > &opt_keys)
void _make_skirt ()
void _make_wipe_tower ()
void finalize_first_layer_convex_hull ()
Polygons first_layer_islands () const
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static StringObjectException check_multi_filament_valid (const Print &print)
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
PrintConfig m_config
PrintObjectConfig m_default_object_config
PrintRegionConfig m_default_region_config
PrintObjectPtrs m_objects
PrintRegionPtrs m_print_regions
bool m_isBBLPrinter
ExtrusionEntityCollection m_skirt
std::map< ObjectID, ExtrusionEntityCollection > m_brimMap
std::map< ObjectID, ExtrusionEntityCollection > m_supportBrimMap
Polygon m_first_layer_convex_hull
Points m_skirt_convex_hull
ToolOrdering m_tool_ordering
WipeTowerData m_wipe_tower_data {m_tool_ordering}
PrintStatistics m_print_statistics
bool m_support_used {false}
Vec3d m_origin
int m_modified_count {0}
ConflictResultOpt m_conflict_result
FakeWipeTower m_fake_wipe_tower
Calib_Params m_calib_params
PrintState< PrintStep, COUNT > m_state
std::atomic< CancelStatus > m_cancel_status
cancel_callback_type m_cancel_callback = [](){}
std::mutex m_state_mutex
friend PrintTryCancel
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class GCode
class PrintObject
Detailed Description
Member Typedef Documentation
cancel_callback_type
typedef std::function<void()> Slic3r::PrintBase::cancel_callback_type inherited
Inherited
typedef PrintBaseWithState<PrintStep, psCount> Slic3r::Print::Inherited private
PrintObjectInfo
typedef std::pair<PrintObject *, bool> Slic3r::Print::PrintObjectInfo private
status_callback_type
typedef std::function<void(const SlicingStatus&)> Slic3r::PrintBase::status_callback_type inherited
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Member Enumeration Documentation
ApplyStatus
enum Slic3r::PrintBase::ApplyStatus inherited
Enumerator
APPLY_STATUS_UNCHANGED
APPLY_STATUS_CHANGED
APPLY_STATUS_INVALIDATED
                     {
        // No change after the Print::apply() call.
        APPLY_STATUS_UNCHANGED,
        // Some of the Print / PrintObject / PrintObjectInstance data was changed,
        // but no result was invalidated (only data influencing not yet calculated results were changed).
        APPLY_STATUS_CHANGED,
        // Some data was changed, which in turn invalidated already calculated steps.
        APPLY_STATUS_INVALIDATED,
    };
CancelStatus
enum Slic3r::PrintBase::CancelStatus inherited
Enumerator
NOT_CANCELED
CANCELED_BY_USER
CANCELED_INTERNAL
                    {
    // No cancelation, background processing should run.
    NOT_CANCELED = 0,
    // Canceled by user from the user interface (user pressed the "Cancel" button or user closed the application).
    CANCELED_BY_USER = 1,
    // Canceled internally from Print::apply() through the Print/PrintObject::invalidate_step() or ::invalidate_all_steps().
    CANCELED_INTERNAL = 2
  };
Constructor & Destructor Documentation
Print()
Slic3r::Print::Print () default
~Print()
virtual Slic3r::Print::~Print () inline virtual
{ this->clear(); }
References clear().
Member Function Documentation
_make_skirt()
void Slic3r::Print::_make_skirt () private
{
    // First off we need to decide how tall the skirt must be.
    // The skirt_height option from config is expressed in layers, but our
    // object might have different layer heights, so we need to find the print_z
    // of the highest layer involved.
    // Note that unless has_infinite_skirt() == true
    // the actual skirt might not reach this $skirt_height_z value since the print
    // order of objects on each layer is not guaranteed and will not generally
    // include the thickest object first. It is just guaranteed that a skirt is
    // prepended to the first 'n' layers (with 'n' = skirt_height).
    // $skirt_height_z in this case is the highest possible skirt height for safety.
    coordf_t skirt_height_z = 0.;
    for (const PrintObject *object : m_objects) {
        size_t skirt_layers = this->has_infinite_skirt() ?
            object->layer_count() :
            std::min(size_t(m_config.skirt_height.value), object->layer_count());
        skirt_height_z = std::max(skirt_height_z, object->m_layers[skirt_layers-1]->print_z);
    }
    // Collect points from all layers contained in skirt height.
    Points points;
    // BBS
    std::map<PrintObject*, Polygon> object_convex_hulls;
    for (PrintObject *object : m_objects) {
        Points object_points;
        // Get object layers up to skirt_height_z.
        for (const Layer *layer : object->m_layers) {
            if (layer->print_z > skirt_height_z)
                break;
            for (const ExPolygon &expoly : layer->lslices)
                // Collect the outer contour points only, ignore holes for the calculation of the convex hull.
                append(object_points, expoly.contour.points);
        }
        // Get support layers up to skirt_height_z.
        for (const SupportLayer *layer : object->support_layers()) {
            if (layer->print_z > skirt_height_z)
                break;
            layer->support_fills.collect_points(object_points);
        }
        object_convex_hulls.insert({ object, Slic3r::Geometry::convex_hull(object_points) });
        // Repeat points for each object copy.
        for (const PrintInstance &instance : object->instances()) {
            Points copy_points = object_points;
            for (Point &pt : copy_points)
                pt += instance.shift;
            append(points, copy_points);
        }
    }
    // Include the wipe tower.
    append(points, this->first_layer_wipe_tower_corners());
    // Unless draft shield is enabled, include all brims as well.
    if (config().draft_shield == dsDisabled)
        append(points, m_first_layer_convex_hull.points);
    if (points.size() < 3)
        // At least three points required for a convex hull.
        return;
    this->throw_if_canceled();
    Polygon convex_hull = Slic3r::Geometry::convex_hull(points);
    // Skirt may be printed on several layers, having distinct layer heights,
    // but loops must be aligned so can't vary width/spacing
    // TODO: use each extruder's own flow
    double initial_layer_print_height = this->skirt_first_layer_height();
    Flow   flow = this->skirt_flow();
    float  spacing = flow.spacing();
    double mm3_per_mm = flow.mm3_per_mm();
    std::vector<size_t> extruders;
    std::vector<double> extruders_e_per_mm;
    {
        auto set_extruders = this->extruders();
        extruders.reserve(set_extruders.size());
        extruders_e_per_mm.reserve(set_extruders.size());
        for (auto &extruder_id : set_extruders) {
            extruders.push_back(extruder_id);
            extruders_e_per_mm.push_back(Extruder((unsigned int)extruder_id, &m_config, m_config.single_extruder_multi_material).e_per_mm(mm3_per_mm));
        }
    }
    // Number of skirt loops per skirt layer.
    size_t n_skirts = m_config.skirt_loops.value;
    if (this->has_infinite_skirt() && n_skirts == 0)
        n_skirts = 1;
    // Initial offset of the brim inner edge from the object (possible with a support & raft).
    // The skirt will touch the brim if the brim is extruded.
    auto   distance = float(scale_(m_config.skirt_distance.value) - spacing/2.);
    // Draw outlines from outside to inside.
    // Loop while we have less skirts than required or any extruder hasn't reached the min length if any.
    std::vector<coordf_t> extruded_length(extruders.size(), 0.);
    for (size_t i = n_skirts, extruder_idx = 0; i > 0; -- i) {
        this->throw_if_canceled();
        // Offset the skirt outside.
        distance += float(scale_(spacing));
        // Generate the skirt centerline.
        Polygon loop;
        {
            // BBS. skirt_distance is defined as the gap between skirt and outer most brim, so no need to add max_brim_width
            Polygons loops = offset(convex_hull, distance, ClipperLib::jtRound, float(scale_(0.1)));
            Geometry::simplify_polygons(loops, scale_(0.05), &loops);
      if (loops.empty())
        break;
      loop = loops.front();
        }
        // Extrude the skirt loop.
        ExtrusionLoop eloop(elrSkirt);
        eloop.paths.emplace_back(ExtrusionPath(
            ExtrusionPath(
                erSkirt,
                (float)mm3_per_mm,         // this will be overridden at G-code export time
                flow.width(),
        (float)initial_layer_print_height  // this will be overridden at G-code export time
            )));
        eloop.paths.back().polyline = loop.split_at_first_point();
        m_skirt.append(eloop);
        if (Print::min_skirt_length > 0) {
            // The skirt length is limited. Sum the total amount of filament length extruded, in mm.
            extruded_length[extruder_idx] += unscale<double>(loop.length()) * extruders_e_per_mm[extruder_idx];
            if (extruded_length[extruder_idx] < Print::min_skirt_length) {
                // Not extruded enough yet with the current extruder. Add another loop.
                if (i == 1)
                    ++ i;
            } else {
                assert(extruded_length[extruder_idx] >= Print::min_skirt_length);
                // Enough extruded with the current extruder. Extrude with the next one,
                // until the prescribed number of skirt loops is extruded.
                if (extruder_idx + 1 < extruders.size())
                    ++ extruder_idx;
            }
        } else {
            // The skirt lenght is not limited, extrude the skirt with the 1st extruder only.
        }
    }
    // Brims were generated inside out, reverse to print the outmost contour first.
    m_skirt.reverse();
    // Remember the outer edge of the last skirt line extruded as m_skirt_convex_hull.
    for (Polygon &poly : offset(convex_hull, distance + 0.5f * float(scale_(spacing)), ClipperLib::jtRound, float(scale_(0.1))))
        append(m_skirt_convex_hull, std::move(poly.points));
    // BBS
    const int n_object_skirts = 1;
    const double object_skirt_distance = scale_(1.0);
    for (auto obj_cvx_hull : object_convex_hulls) {
        PrintObject* object = obj_cvx_hull.first;
        for (int i = 0; i < n_object_skirts; i++) {
            distance += float(scale_(spacing));
            Polygon loop;
            {
                // BBS. skirt_distance is defined as the gap between skirt and outer most brim, so no need to add max_brim_width
                Polygons loops = offset(obj_cvx_hull.second, object_skirt_distance, ClipperLib::jtRound, float(scale_(0.1)));
                Geometry::simplify_polygons(loops, scale_(0.05), &loops);
                if (loops.empty())
                    break;
                loop = loops.front();
            }
            // Extrude the skirt loop.
            ExtrusionLoop eloop(elrSkirt);
            eloop.paths.emplace_back(ExtrusionPath(
                ExtrusionPath(
                    erSkirt,
                    (float)mm3_per_mm,         // this will be overridden at G-code export time
                    flow.width(),
                    (float)initial_layer_print_height  // this will be overridden at G-code export time
                )));
            eloop.paths.back().polyline = loop.split_at_first_point();
            object->m_skirt.append(std::move(eloop));
        }
    }
}
References Slic3r::append(), Slic3r::Geometry::convex_hull(), Slic3r::dsDisabled, Slic3r::Extruder::e_per_mm(), Slic3r::elrSkirt, Slic3r::erSkirt, ClipperLib::jtRound, Slic3r::Flow::mm3_per_mm(), Slic3r::ExtrusionLoop::paths, scale_, Slic3r::Flow::spacing(), and Slic3r::Flow::width().
_make_wipe_tower()
void Slic3r::Print::_make_wipe_tower () private
{
    m_wipe_tower_data.clear();
    // Get wiping matrix to get number of extruders and convert vector<double> to vector<float>:
    std::vector<float> flush_matrix(cast<float>(m_config.flush_volumes_matrix.values));
    // BBS
    const unsigned int number_of_extruders = (unsigned int)(sqrt(flush_matrix.size()) + EPSILON);
    // Extract purging volumes for each extruder pair:
    std::vector<std::vector<float>> wipe_volumes;
    for (unsigned int i = 0; i<number_of_extruders; ++i)
        wipe_volumes.push_back(std::vector<float>(flush_matrix.begin()+i*number_of_extruders, flush_matrix.begin()+(i+1)*number_of_extruders));
    // Let the ToolOrdering class know there will be initial priming extrusions at the start of the print.
    // BBS: priming logic is removed, so don't consider it in tool ordering
    m_wipe_tower_data.tool_ordering = ToolOrdering(*this, (unsigned int)-1, false);
    if (!m_wipe_tower_data.tool_ordering.has_wipe_tower())
        // Don't generate any wipe tower.
        return;
    // Check whether there are any layers in m_tool_ordering, which are marked with has_wipe_tower,
    // they print neither object, nor support. These layers are above the raft and below the object, and they
    // shall be added to the support layers to be printed.
    // see https://github.com/prusa3d/PrusaSlicer/issues/607
    {
        size_t idx_begin = size_t(-1);
        size_t idx_end   = m_wipe_tower_data.tool_ordering.layer_tools().size();
        // Find the first wipe tower layer, which does not have a counterpart in an object or a support layer.
        for (size_t i = 0; i < idx_end; ++ i) {
            const LayerTools &lt = m_wipe_tower_data.tool_ordering.layer_tools()[i];
            if (lt.has_wipe_tower && ! lt.has_object && ! lt.has_support) {
                idx_begin = i;
                break;
            }
        }
        if (idx_begin != size_t(-1)) {
            // Find the position in m_objects.first()->support_layers to insert these new support layers.
            double wipe_tower_new_layer_print_z_first = m_wipe_tower_data.tool_ordering.layer_tools()[idx_begin].print_z;
            auto it_layer = m_objects.front()->support_layers().begin();
            auto it_end   = m_objects.front()->support_layers().end();
            for (; it_layer != it_end && (*it_layer)->print_z - EPSILON < wipe_tower_new_layer_print_z_first; ++ it_layer);
            // Find the stopper of the sequence of wipe tower layers, which do not have a counterpart in an object or a support layer.
            for (size_t i = idx_begin; i < idx_end; ++ i) {
                LayerTools &lt = const_cast<LayerTools&>(m_wipe_tower_data.tool_ordering.layer_tools()[i]);
                if (! (lt.has_wipe_tower && ! lt.has_object && ! lt.has_support))
                    break;
                lt.has_support = true;
                // Insert the new support layer.
                double height    = lt.print_z - (i == 0 ? 0. : m_wipe_tower_data.tool_ordering.layer_tools()[i-1].print_z);
                //FIXME the support layer ID is set to -1, as Vojtech hopes it is not being used anyway.
                it_layer = m_objects.front()->insert_support_layer(it_layer, -1, 0, height, lt.print_z, lt.print_z - 0.5 * height);
                ++ it_layer;
            }
        }
    }
    this->throw_if_canceled();
    // Initialize the wipe tower.
    // BBS: in BBL machine, wipe tower is only use to prime extruder. So just use a global wipe volume.
    WipeTower wipe_tower(m_config, m_plate_index, m_origin, m_config.prime_volume, m_wipe_tower_data.tool_ordering.first_extruder(),
        m_wipe_tower_data.tool_ordering.empty() ? 0.f : m_wipe_tower_data.tool_ordering.back().print_z);
    //wipe_tower.set_retract();
    //wipe_tower.set_zhop();
    // Set the extruder & material properties at the wipe tower object.
    for (size_t i = 0; i < number_of_extruders; ++ i)
        wipe_tower.set_extruder(i, m_config);
    // BBS: remove priming logic
    //m_wipe_tower_data.priming = Slic3r::make_unique<std::vector<WipeTower::ToolChangeResult>>(
    //    wipe_tower.prime((float)this->skirt_first_layer_height(), m_wipe_tower_data.tool_ordering.all_extruders(), false));
    // Lets go through the wipe tower layers and determine pairs of extruder changes for each
    // to pass to wipe_tower (so that it can use it for planning the layout of the tower)
    {
        // BBS: priming logic is removed, so get the initial extruder by first_extruder()
        unsigned int current_extruder_id = m_wipe_tower_data.tool_ordering.first_extruder();
        for (auto &layer_tools : m_wipe_tower_data.tool_ordering.layer_tools()) { // for all layers
            if (!layer_tools.has_wipe_tower) continue;
            bool first_layer = &layer_tools == &m_wipe_tower_data.tool_ordering.front();
            wipe_tower.plan_toolchange((float)layer_tools.print_z, (float)layer_tools.wipe_tower_layer_height, current_extruder_id, current_extruder_id);
            for (const auto extruder_id : layer_tools.extruders) {
                // BBS: priming logic is removed, so no need to do toolchange for first extruder
                if (/*(first_layer && extruder_id == m_wipe_tower_data.tool_ordering.all_extruders().back()) || */extruder_id != current_extruder_id) {
                    float volume_to_purge = wipe_volumes[current_extruder_id][extruder_id];
                    volume_to_purge *= m_config.flush_multiplier;
                    // Not all of that can be used for infill purging:
                    //volume_to_purge -= (float)m_config.filament_minimal_purge_on_wipe_tower.get_at(extruder_id);
                    // try to assign some infills/objects for the wiping:
                    volume_to_purge = layer_tools.wiping_extrusions().mark_wiping_extrusions(*this, current_extruder_id, extruder_id, volume_to_purge);
                    // add back the minimal amount toforce on the wipe tower:
                    //volume_to_purge += (float)m_config.filament_minimal_purge_on_wipe_tower.get_at(extruder_id);
                    // request a toolchange at the wipe tower with at least volume_to_wipe purging amount
                    wipe_tower.plan_toolchange((float)layer_tools.print_z, (float)layer_tools.wipe_tower_layer_height,
                                               current_extruder_id, extruder_id, m_config.prime_volume, volume_to_purge);
                    current_extruder_id = extruder_id;
                }
            }
            layer_tools.wiping_extrusions().ensure_perimeters_infills_order(*this);
            // if enable timelapse, slice all layer
            if (enable_timelapse_print()) {
                if (layer_tools.wipe_tower_partitions == 0)
                    wipe_tower.set_last_layer_extruder_fill(false);
                continue;
            }
            if (&layer_tools == &m_wipe_tower_data.tool_ordering.back() || (&layer_tools + 1)->wipe_tower_partitions == 0)
                break;
        }
    }
    // Generate the wipe tower layers.
    m_wipe_tower_data.tool_changes.reserve(m_wipe_tower_data.tool_ordering.layer_tools().size());
    wipe_tower.generate(m_wipe_tower_data.tool_changes);
    m_wipe_tower_data.depth = wipe_tower.get_depth();
    m_wipe_tower_data.brim_width = wipe_tower.get_brim_width();
    // Unload the current filament over the purge tower.
    coordf_t layer_height = m_objects.front()->config().layer_height.value;
    if (m_wipe_tower_data.tool_ordering.back().wipe_tower_partitions > 0) {
        // The wipe tower goes up to the last layer of the print.
        if (wipe_tower.layer_finished()) {
            // The wipe tower is printed to the top of the print and it has no space left for the final extruder purge.
            // Lift Z to the next layer.
            wipe_tower.set_layer(float(m_wipe_tower_data.tool_ordering.back().print_z + layer_height), float(layer_height), 0, false, true);
        } else {
            // There is yet enough space at this layer of the wipe tower for the final purge.
        }
    } else {
        // The wipe tower does not reach the last print layer, perform the pruge at the last print layer.
        assert(m_wipe_tower_data.tool_ordering.back().wipe_tower_partitions == 0);
        wipe_tower.set_layer(float(m_wipe_tower_data.tool_ordering.back().print_z), float(layer_height), 0, false, true);
    }
    m_wipe_tower_data.final_purge = Slic3r::make_unique<WipeTower::ToolChangeResult>(
        wipe_tower.tool_change((unsigned int)(-1)));
    m_wipe_tower_data.used_filament         = wipe_tower.get_used_filament();
    m_wipe_tower_data.number_of_toolchanges = wipe_tower.get_number_of_toolchanges();
    const Vec3d origin                      = this->get_plate_origin();
    m_fake_wipe_tower.set_fake_extrusion_data(wipe_tower.position(), wipe_tower.width(), wipe_tower.get_height(), wipe_tower.get_layer_height(), m_wipe_tower_data.depth,
                                              m_wipe_tower_data.brim_width, {scale_(origin.x()), scale_(origin.y())});
}
References EPSILON, Slic3r::LayerTools::has_object, Slic3r::LayerTools::has_support, Slic3r::LayerTools::has_wipe_tower, int, Slic3r::layer_height(), Slic3r::LayerTools::print_z, Slic3r::WipeTower::set_extruder(), and sqrt().
active_step_add_warning()
void Slic3r::PrintBaseWithState< PrintStep , COUNT >::active_step_add_warning (PrintStateBase::WarningLevel warning_level, const std::string & message, PrintStateBase::SlicingNotificationType message_id = PrintStateBase::SlicingDefaultNotification) inline protected inherited
    {
        std::pair<PrintStepEnum, bool> active_step = m_state.active_step_add_warning(warning_level, message, (int)message_id, this->state_mutex());
        if (active_step.second)
            // Update UI.
            this->status_update_warnings(static_cast<int>(active_step.first), warning_level, message, nullptr, message_id);
    }
apply()
Print::ApplyStatus Slic3r::Print::apply (const Model & model, DynamicPrintConfig config) override virtual
Implements Slic3r::PrintBase.
{
#ifdef _DEBUG
    check_model_ids_validity(model);
#endif /* _DEBUG */
    //BBS: add more logs
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: enter")%__LINE__;
    // Normalize the config.
  new_full_config.option("print_settings_id",            true);
  new_full_config.option("filament_settings_id",         true);
  new_full_config.option("printer_settings_id",          true);
    // BBS
    int used_filaments = this->extruders(true).size();
    //new_full_config.normalize_fdm(used_filaments);
    new_full_config.normalize_fdm_1();
    t_config_option_keys changed_keys = new_full_config.normalize_fdm_2(objects().size(), used_filaments);
    if (changed_keys.size() > 0) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", got changed_keys, size=%1%")%changed_keys.size();
        for (int i = 0; i < changed_keys.size(); i++)
        {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", i=%1%, key=%2%")%i %changed_keys[i];
        }
    }
    const ConfigOption* enable_support_option = new_full_config.option("enable_support");
    if (enable_support_option && enable_support_option->getBool())
        m_support_used = true;
    else
        m_support_used = false;
    // Find modified keys of the various configs. Resolve overrides extruder retract values by filament profiles.
    DynamicPrintConfig   filament_overrides;
    //BBS: add plate index
    t_config_option_keys print_diff       = print_config_diffs(m_config, new_full_config, filament_overrides, this->m_plate_index);
    t_config_option_keys full_config_diff = full_print_config_diffs(m_full_print_config, new_full_config, this->m_plate_index);
    // Collect changes to object and region configs.
    t_config_option_keys object_diff      = m_default_object_config.diff(new_full_config);
    t_config_option_keys region_diff      = m_default_region_config.diff(new_full_config);
    // Do not use the ApplyStatus as we will use the max function when updating apply_status.
    unsigned int apply_status = APPLY_STATUS_UNCHANGED;
    auto update_apply_status = [&apply_status](bool invalidated)
        { apply_status = std::max<unsigned int>(apply_status, invalidated ? APPLY_STATUS_INVALIDATED : APPLY_STATUS_CHANGED); };
    if (! (print_diff.empty() && object_diff.empty() && region_diff.empty())) {
        update_apply_status(false);
        //BBS: add more logs
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", got print_diff %1%, object_diff %2%, region_diff %3%, set status to APPLY_STATUS_CHANGED")%print_diff.size() %object_diff.size() %region_diff.size();
    }
    // Grab the lock for the Print / PrintObject milestones.
  std::scoped_lock<std::mutex> lock(this->state_mutex());
    // The following call may stop the background processing.
    if (! print_diff.empty())
        update_apply_status(this->invalidate_state_by_config_options(new_full_config, print_diff));
    // Apply variables to placeholder parser. The placeholder parser is used by G-code export,
    // which should be stopped if print_diff is not empty.
    size_t num_extruders  = m_config.filament_diameter.size();
    bool   num_extruders_changed  = false;
    if (! full_config_diff.empty()) {
        //BBS: add more logs
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: found full_config_diff changed.")%__LINE__;
        update_apply_status(this->invalidate_step(psGCodeExport));
        m_placeholder_parser.clear_config();
        // Set the profile aliases for the PrintBase::output_filename()
    m_placeholder_parser.set("print_preset",              new_full_config.option("print_settings_id")->clone());
    m_placeholder_parser.set("filament_preset",           new_full_config.option("filament_settings_id")->clone());
    m_placeholder_parser.set("printer_preset",            new_full_config.option("printer_settings_id")->clone());
    // We want the filament overrides to be applied over their respective extruder parameters by the PlaceholderParser.
    // see "Placeholders do not respect filament overrides." GH issue #3649
    m_placeholder_parser.apply_config(filament_overrides);
      // It is also safe to change m_config now after this->invalidate_state_by_config_options() call.
      m_config.apply_only(new_full_config, print_diff, true);
      //FIXME use move semantics once ConfigBase supports it.
        // Some filament_overrides may contain values different from new_full_config, but equal to m_config.
        // As long as these config options don't reallocate memory when copying, we are safe overriding a value, which is in use by a worker thread.
      m_config.apply(filament_overrides);
      // Handle changes to object config defaults
      m_default_object_config.apply_only(new_full_config, object_diff, true);
      // Handle changes to regions config defaults
      m_default_region_config.apply_only(new_full_config, region_diff, true);
        //m_full_print_config = std::move(new_full_config);
        m_full_print_config = new_full_config;
        if (num_extruders  != m_config.filament_diameter.size()) {
            num_extruders  = m_config.filament_diameter.size();
            num_extruders_changed  = true;
        }
    }
    ModelObjectStatusDB model_object_status_db;
    // 1) Synchronize model objects.
    bool print_regions_reshuffled = false;
    if (model.id() != m_model.id()) {
        // Kill everything, initialize from scratch.
        // Stop background processing.
        this->call_cancel_callback();
        update_apply_status(this->invalidate_all_steps());
        for (PrintObject *object : m_objects) {
            model_object_status_db.add(*object->model_object(), ModelObjectStatus::Deleted);
      update_apply_status(object->invalidate_all_steps());
      delete object;
        }
        m_objects.clear();
        print_regions_reshuffled = true;
        m_model.assign_copy(model);
    for (const ModelObject *model_object : m_model.objects)
      model_object_status_db.add(*model_object, ModelObjectStatus::New);
    } else {
        //BBS: replace model custom gcode with current plate custom gcode
        m_model.curr_plate_index = model.curr_plate_index;
        if (m_model.get_curr_plate_custom_gcodes() != model.get_curr_plate_custom_gcodes()) {
            update_apply_status(num_extruders_changed ||
                // Tool change G-codes are applied as color changes for a single extruder printer, no need to invalidate tool ordering.
                //FIXME The tool ordering may be invalidated unnecessarily if the custom_gcode_per_print_z.mode is not applicable
                // to the active print / model state, and then it is reset, so it is being applicable, but empty, thus the effect is the same.
                (num_extruders > 1 && custom_per_printz_gcodes_tool_changes_differ(m_model.get_curr_plate_custom_gcodes().gcodes, model.get_curr_plate_custom_gcodes().gcodes)) ?
                // The Tool Ordering and the Wipe Tower are no more valid.
                this->invalidate_steps({ psWipeTower, psGCodeExport }) :
                // There is no change in Tool Changes stored in custom_gcode_per_print_z, therefore there is no need to update Tool Ordering.
                this->invalidate_step(psGCodeExport));
            m_model.plates_custom_gcodes[m_model.curr_plate_index] = model.get_curr_plate_custom_gcodes();
        }
        if (model_object_list_equal(m_model, model)) {
            // The object list did not change.
      for (const ModelObject *model_object : m_model.objects)
        model_object_status_db.add(*model_object, ModelObjectStatus::Old);
        } else if (model_object_list_extended(m_model, model)) {
            // Add new objects. Their volumes and configs will be synchronized later.
            //BBS: we don't need to set invalid here, we judge it by comparing the print_object list
            //update_apply_status(this->invalidate_step(psGCodeExport));
            for (const ModelObject *model_object : m_model.objects)
                model_object_status_db.add(*model_object, ModelObjectStatus::Old);
            for (size_t i = m_model.objects.size(); i < model.objects.size(); ++ i) {
                model_object_status_db.add(*model.objects[i], ModelObjectStatus::New);
                m_model.objects.emplace_back(ModelObject::new_copy(*model.objects[i]));
        m_model.objects.back()->set_model(&m_model);
            }
            //BBS: add more logs
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: new model objects added.")%__LINE__;
        } else {
            //BBS: add more logs
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: model object changed.")%__LINE__;
            // Reorder the objects, add new objects.
            // First stop background processing before shuffling or deleting the PrintObjects in the object list.
            this->call_cancel_callback();
            //BBS: we don't need to set invalid here, we judge it by comparing the print_object list
            //update_apply_status(this->invalidate_step(psGCodeExport));
            // Second create a new list of objects.
            std::vector<ModelObject*> model_objects_old(std::move(m_model.objects));
            m_model.objects.clear();
            m_model.objects.reserve(model.objects.size());
            auto by_id_lower = [](const ModelObject *lhs, const ModelObject *rhs){ return lhs->id() < rhs->id(); };
            std::sort(model_objects_old.begin(), model_objects_old.end(), by_id_lower);
            for (const ModelObject *mobj : model.objects) {
                auto it = std::lower_bound(model_objects_old.begin(), model_objects_old.end(), mobj, by_id_lower);
                if (it == model_objects_old.end() || (*it)->id() != mobj->id()) {
                    // New ModelObject added.
          m_model.objects.emplace_back(ModelObject::new_copy(*mobj));
          m_model.objects.back()->set_model(&m_model);
                    model_object_status_db.add(*mobj, ModelObjectStatus::New);
                } else {
                    // Existing ModelObject re-added (possibly moved in the list).
                    m_model.objects.emplace_back(*it);
                    model_object_status_db.add(*mobj, ModelObjectStatus::Moved);
                }
            }
            bool deleted_any = false;
      for (ModelObject *&model_object : model_objects_old)
                if (model_object_status_db.add_if_new(*model_object, ModelObjectStatus::Deleted))
                    deleted_any = true;
                else
                    // Do not delete this ModelObject instance.
                    model_object = nullptr;
            if (deleted_any) {
                // Delete PrintObjects of the deleted ModelObjects.
                PrintObjectPtrs print_objects_old = std::move(m_objects);
                m_objects.clear();
                m_objects.reserve(print_objects_old.size());
                for (PrintObject *print_object : print_objects_old) {
                    const ModelObjectStatus &status = model_object_status_db.get(*print_object->model_object());
                    if (status.status == ModelObjectStatus::Deleted) {
                        update_apply_status(print_object->invalidate_all_steps());
                        delete print_object;
                    } else
                        m_objects.emplace_back(print_object);
                }
                for (ModelObject *model_object : model_objects_old)
                    delete model_object;
                print_regions_reshuffled = true;
            }
        }
    }
    // 2) Map print objects including their transformation matrices.
    PrintObjectStatusDB print_object_status_db(m_objects);
    // 3) Synchronize ModelObjects & PrintObjects.
    const std::initializer_list<ModelVolumeType> solid_or_modifier_types { ModelVolumeType::MODEL_PART, ModelVolumeType::NEGATIVE_VOLUME, ModelVolumeType::PARAMETER_MODIFIER };
    for (size_t idx_model_object = 0; idx_model_object < model.objects.size(); ++ idx_model_object) {
        ModelObject       &model_object        = *m_model.objects[idx_model_object];
        ModelObjectStatus &model_object_status = const_cast<ModelObjectStatus&>(model_object_status_db.reuse(model_object));
    const ModelObject &model_object_new    = *model.objects[idx_model_object];
        if (model_object_status.status == ModelObjectStatus::New)
            // PrintObject instances will be added in the next loop.
            continue;
        // Update the ModelObject instance, possibly invalidate the linked PrintObjects.
        assert(model_object_status.status == ModelObjectStatus::Old || model_object_status.status == ModelObjectStatus::Moved);
        // Check whether a model part volume was added or removed, their transformations or order changed.
        // Only volume IDs, volume types, transformation matrices and their order are checked, configuration and other parameters are NOT checked.
        bool solid_or_modifier_differ   = model_volume_list_changed(model_object, model_object_new, solid_or_modifier_types) ||
                                          model_mmu_segmentation_data_changed(model_object, model_object_new) ||
                                          (model_object_new.is_mm_painted() && num_extruders_changed );
        bool supports_differ            = model_volume_list_changed(model_object, model_object_new, ModelVolumeType::SUPPORT_BLOCKER) ||
                                          model_volume_list_changed(model_object, model_object_new, ModelVolumeType::SUPPORT_ENFORCER);
        bool layer_height_ranges_differ = ! layer_height_ranges_equal(model_object.layer_config_ranges, model_object_new.layer_config_ranges, model_object_new.layer_height_profile.empty());
        bool model_origin_translation_differ = model_object.origin_translation != model_object_new.origin_translation;
        auto print_objects_range        = print_object_status_db.get_range(model_object);
        // The list actually can be empty if all instances are out of the print bed.
        //assert(print_objects_range.begin() != print_objects_range.end());
        // All PrintObjects in print_objects_range shall point to the same prints_objects_regions
        if (print_objects_range.begin() != print_objects_range.end()) {
            model_object_status.print_object_regions = print_objects_range.begin()->print_object->m_shared_regions;
            model_object_status.print_object_regions->ref_cnt_inc();
        }
        if (solid_or_modifier_differ || model_origin_translation_differ || layer_height_ranges_differ ||
            ! model_object.layer_height_profile.timestamp_matches(model_object_new.layer_height_profile)) {
            // The very first step (the slicing step) is invalidated. One may freely remove all associated PrintObjects.
            model_object_status.print_object_regions_status =
                model_object_status.print_object_regions == nullptr || model_origin_translation_differ || layer_height_ranges_differ ?
                // Drop print_objects_regions.
                ModelObjectStatus::PrintObjectRegionsStatus::Invalid :
                // Reuse bounding boxes of print_objects_regions for ModelVolumes with unmodified transformation.
                ModelObjectStatus::PrintObjectRegionsStatus::PartiallyValid;
            for (const PrintObjectStatus &print_object_status : print_objects_range) {
                update_apply_status(print_object_status.print_object->invalidate_all_steps());
                const_cast<PrintObjectStatus&>(print_object_status).status = PrintObjectStatus::Deleted;
            }
            if (model_object_status.print_object_regions_status == ModelObjectStatus::PrintObjectRegionsStatus::PartiallyValid)
                // Drop everything from PrintObjectRegions but those VolumeExtents (of their particular ModelVolumes) that are still valid.
                print_objects_regions_invalidate_keep_some_volumes(*model_object_status.print_object_regions, model_object.volumes, model_object_new.volumes);
            else if (model_object_status.print_object_regions != nullptr)
                model_object_status.print_object_regions->clear();
            // Copy content of the ModelObject including its ID, do not change the parent.
            model_object.assign_copy(model_object_new);
        } else {
            model_object_status.print_object_regions_status = ModelObjectStatus::PrintObjectRegionsStatus::Valid;
            if (supports_differ || model_custom_supports_data_changed(model_object, model_object_new)) {
                // First stop background processing before shuffling or deleting the ModelVolumes in the ModelObject's list.
                if (supports_differ) {
                    this->call_cancel_callback();
                    update_apply_status(false);
                }
                // Invalidate just the supports step.
                for (const PrintObjectStatus &print_object_status : print_objects_range)
                    update_apply_status(print_object_status.print_object->invalidate_step(posSupportMaterial));
                if (supports_differ) {
                    // Copy just the support volumes.
                    model_volume_list_update_supports(model_object, model_object_new);
                }
            } else if (model_custom_seam_data_changed(model_object, model_object_new)) {
                update_apply_status(this->invalidate_step(psGCodeExport));
            }
        }
        if (! solid_or_modifier_differ) {
            // Synchronize Object's config.
            bool object_config_changed = ! model_object.config.timestamp_matches(model_object_new.config);
      if (object_config_changed)
        model_object.config.assign_config(model_object_new.config);
            if (! object_diff.empty() || object_config_changed || num_extruders_changed ) {
                PrintObjectConfig new_config = PrintObject::object_config_from_model_object(m_default_object_config, model_object, num_extruders );
                for (const PrintObjectStatus &print_object_status : print_object_status_db.get_range(model_object)) {
                    t_config_option_keys diff = print_object_status.print_object->config().diff(new_config);
                    if (! diff.empty()) {
                        update_apply_status(print_object_status.print_object->invalidate_state_by_config_options(print_object_status.print_object->config(), new_config, diff));
                        print_object_status.print_object->config_apply_only(new_config, diff, true);
                    }
                }
            }
            // Synchronize (just copy) the remaining data of ModelVolumes (name, config, custom supports data).
            //FIXME What to do with m_material_id?
      model_volume_list_copy_configs(model_object /* dst */, model_object_new /* src */, ModelVolumeType::MODEL_PART);
      model_volume_list_copy_configs(model_object /* dst */, model_object_new /* src */, ModelVolumeType::PARAMETER_MODIFIER);
            layer_height_ranges_copy_configs(model_object.layer_config_ranges /* dst */, model_object_new.layer_config_ranges /* src */);
            // Copy the ModelObject name, input_file and instances. The instances will be compared against PrintObject instances in the next step.
            model_object.name       = model_object_new.name;
            model_object.input_file = model_object_new.input_file;
            // Only refresh ModelInstances if there is any change.
            if (model_object.instances.size() != model_object_new.instances.size() ||
              ! std::equal(model_object.instances.begin(), model_object.instances.end(), model_object_new.instances.begin(), [](auto l, auto r){ return l->id() == r->id(); })) {
              // G-code generator accesses model_object.instances to generate sequential print ordering matching the Plater object list.
              update_apply_status(this->invalidate_step(psGCodeExport));
              model_object.clear_instances();
              model_object.instances.reserve(model_object_new.instances.size());
              for (const ModelInstance *model_instance : model_object_new.instances) {
                  model_object.instances.emplace_back(new ModelInstance(*model_instance));
                  model_object.instances.back()->set_model_object(&model_object);
              }
          } else if (! std::equal(model_object.instances.begin(), model_object.instances.end(), model_object_new.instances.begin(),
              [](auto l, auto r){ return l->print_volume_state == r->print_volume_state && l->printable == r->printable &&
                                 l->get_transformation().get_matrix().isApprox(r->get_transformation().get_matrix()); })) {
            // If some of the instances changed, the bounding box of the updated ModelObject is likely no more valid.
            // This is safe as the ModelObject's bounding box is only accessed from this function, which is called from the main thread only.
        model_object.invalidate_bounding_box();
            // Synchronize the content of instances.
            auto new_instance = model_object_new.instances.begin();
        for (auto old_instance = model_object.instances.begin(); old_instance != model_object.instances.end(); ++ old_instance, ++ new_instance) {
          (*old_instance)->set_transformation((*new_instance)->get_transformation());
                    (*old_instance)->print_volume_state = (*new_instance)->print_volume_state;
                    (*old_instance)->printable        = (*new_instance)->printable;
          }
          }
        }
    }
    // 4) Generate PrintObjects from ModelObjects and their instances.
    {
        PrintObjectPtrs print_objects_new;
        print_objects_new.reserve(std::max(m_objects.size(), m_model.objects.size()));
        bool new_objects = false;
        // Walk over all new model objects and check, whether there are matching PrintObjects.
        for (ModelObject *model_object : m_model.objects) {
            ModelObjectStatus &model_object_status = const_cast<ModelObjectStatus&>(model_object_status_db.reuse(*model_object));
            model_object_status.print_instances    = print_objects_from_model_object(*model_object);
            std::vector<const PrintObjectStatus*> old;
            old.reserve(print_object_status_db.count(*model_object));
            for (const PrintObjectStatus &print_object_status : print_object_status_db.get_range(*model_object))
                if (print_object_status.status != PrintObjectStatus::Deleted)
                    old.emplace_back(&print_object_status);
            // Generate a list of trafos and XY offsets for instances of a ModelObject
            // Producing the config for PrintObject on demand, caching it at print_object_last.
            const PrintObject *print_object_last = nullptr;
            auto print_object_apply_config = [this, &print_object_last, model_object, num_extruders ](PrintObject *print_object) {
                print_object->config_apply(print_object_last ?
                    print_object_last->config() :
                    PrintObject::object_config_from_model_object(m_default_object_config, *model_object, num_extruders ));
                print_object_last = print_object;
            };
            if (old.empty()) {
                // Simple case, just generate new instances.
                for (PrintObjectTrafoAndInstances &print_instances : model_object_status.print_instances) {
                    PrintObject *print_object = new PrintObject(this, model_object, print_instances.trafo, std::move(print_instances.instances));
                    print_object_apply_config(print_object);
                    print_objects_new.emplace_back(print_object);
                    // print_object_status.emplace(PrintObjectStatus(print_object, PrintObjectStatus::New));
                    new_objects = true;
                }
                continue;
            }
            // Complex case, try to merge the two lists.
            // Sort the old lexicographically by their trafos.
            std::sort(old.begin(), old.end(), [](const PrintObjectStatus *lhs, const PrintObjectStatus *rhs){ return transform3d_lower(lhs->trafo, rhs->trafo); });
            // Merge the old / new lists.
            auto it_old = old.begin();
            for (PrintObjectTrafoAndInstances &new_instances : model_object_status.print_instances) {
        for (; it_old != old.end() && transform3d_lower((*it_old)->trafo, new_instances.trafo); ++ it_old);
        if (it_old == old.end() || ! transform3d_equal((*it_old)->trafo, new_instances.trafo)) {
                    // This is a new instance (or a set of instances with the same trafo). Just add it.
                    PrintObject *print_object = new PrintObject(this, model_object, new_instances.trafo, std::move(new_instances.instances));
                    print_object_apply_config(print_object);
                    print_objects_new.emplace_back(print_object);
                    // print_object_status.emplace(PrintObjectStatus(print_object, PrintObjectStatus::New));
                    new_objects = true;
                    if (it_old != old.end())
                        const_cast<PrintObjectStatus*>(*it_old)->status = PrintObjectStatus::Deleted;
                } else {
                    // The PrintObject already exists and the copies differ.
          PrintBase::ApplyStatus status = (*it_old)->print_object->set_instances(std::move(new_instances.instances));
                    if (status != PrintBase::APPLY_STATUS_UNCHANGED)
            update_apply_status(status == PrintBase::APPLY_STATUS_INVALIDATED);
          print_objects_new.emplace_back((*it_old)->print_object);
          const_cast<PrintObjectStatus*>(*it_old)->status = PrintObjectStatus::Reused;
        }
            }
        }
        if (m_objects != print_objects_new) {
            //BBS: add more logs
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: found print object changed.")%__LINE__;
            this->call_cancel_callback();
      update_apply_status(this->invalidate_all_steps());
            m_objects = print_objects_new;
            // Delete the PrintObjects marked as Unknown or Deleted.
            bool deleted_objects = false;
            for (const PrintObjectStatus &pos : print_object_status_db)
                if (pos.status == PrintObjectStatus::Unknown || pos.status == PrintObjectStatus::Deleted) {
                    update_apply_status(pos.print_object->invalidate_all_steps());
                    delete pos.print_object;
          deleted_objects = true;
                }
      if (new_objects || deleted_objects)
                update_apply_status(this->invalidate_steps({ psSkirtBrim, psWipeTower, psGCodeExport }));
      if (new_objects)
              update_apply_status(false);
            print_regions_reshuffled = true;
        }
        print_object_status_db.clear();
        // BBS
        for (PrintObject* object : m_objects) {
            auto ept_iter = std::find(print_diff.begin(), print_diff.end(), "enable_prime_tower");
            if (/*object->config().adaptive_layer_height &&*/ ept_iter != print_diff.end()) {
                update_apply_status(object->invalidate_step(posSlice));
            }
        }
    }
    //BBS: check the config again
    int new_used_filaments = this->extruders(true).size();
    t_config_option_keys new_changed_keys = new_full_config.normalize_fdm_2(objects().size(), new_used_filaments);
    if (new_changed_keys.size() > 0) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", got new_changed_keys, size=%1%")%new_changed_keys.size();
        for (int i = 0; i < new_changed_keys.size(); i++)
        {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", i=%1%, key=%2%")%i %new_changed_keys[i];
        }
        update_apply_status(false);
        // The following call may stop the background processing.
        update_apply_status(this->invalidate_state_by_config_options(new_full_config, new_changed_keys));
        update_apply_status(this->invalidate_step(psGCodeExport));
        if (full_config_diff.empty()) {
            //BBS: previous empty
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: full_config_diff previous empty, need to apply now.")%__LINE__;
            m_placeholder_parser.clear_config();
            // Set the profile aliases for the PrintBase::output_filename()
            m_placeholder_parser.set("print_preset",              new_full_config.option("print_settings_id")->clone());
            m_placeholder_parser.set("filament_preset",           new_full_config.option("filament_settings_id")->clone());
            m_placeholder_parser.set("printer_preset",            new_full_config.option("printer_settings_id")->clone());
            //m_placeholder_parser.apply_config(filament_overrides);
        }
        // It is also safe to change m_config now after this->invalidate_state_by_config_options() call.
        m_config.apply_only(new_full_config, new_changed_keys, true);
        // Handle changes to object config defaults
        m_default_object_config.apply_only(new_full_config, new_changed_keys, true);
        // Handle changes to regions config defaults
        m_default_region_config.apply_only(new_full_config, new_changed_keys, true);
        m_full_print_config = std::move(new_full_config);
    }
    // All regions now have distinct settings.
    // Check whether applying the new region config defaults we would get different regions,
    // update regions or create regions from scratch.
    for (auto it_print_object = m_objects.begin(); it_print_object != m_objects.end();) {
        // Find the range of PrintObjects sharing the same associated ModelObject.
        auto                it_print_object_end  = it_print_object;
        PrintObject        &print_object         = *(*it_print_object);
        const ModelObject  &model_object         = *print_object.model_object();
        ModelObjectStatus  &model_object_status  = const_cast<ModelObjectStatus&>(model_object_status_db.reuse(model_object));
        PrintObjectRegions *print_object_regions = model_object_status.print_object_regions;
        for (++ it_print_object_end; it_print_object_end != m_objects.end() && (*it_print_object)->model_object() == (*it_print_object_end)->model_object(); ++ it_print_object_end)
            assert((*it_print_object_end)->m_shared_regions == nullptr || (*it_print_object_end)->m_shared_regions == print_object_regions);
        if (print_object_regions == nullptr) {
            print_object_regions = new PrintObjectRegions{};
            model_object_status.print_object_regions = print_object_regions;
            print_object_regions->ref_cnt_inc();
        }
        std::vector<unsigned int> painting_extruders;
        if (const auto &volumes = print_object.model_object()->volumes;
            num_extruders  > 1 &&
            std::find_if(volumes.begin(), volumes.end(), [](const ModelVolume *v) { return ! v->mmu_segmentation_facets.empty(); }) != volumes.end()) {
            //FIXME be more specific! Don't enumerate extruders that are not used for painting!
            painting_extruders.assign(num_extruders , 0);
            std::iota(painting_extruders.begin(), painting_extruders.end(), 1);
        }
        if (model_object_status.print_object_regions_status == ModelObjectStatus::PrintObjectRegionsStatus::Valid) {
            // Verify that the trafo for regions & volume bounding boxes thus for regions is still applicable.
            auto invalidate = [it_print_object, it_print_object_end, update_apply_status]() {
                for (auto it = it_print_object; it != it_print_object_end; ++ it)
                    if ((*it)->m_shared_regions != nullptr)
                        update_apply_status((*it)->invalidate_all_steps());
            };
            if (print_object_regions && ! trafos_differ_in_rotation_by_z_and_mirroring_by_xy_only(print_object_regions->trafo_bboxes, model_object_status.print_instances.front().trafo)) {
                invalidate();
                print_object_regions->clear();
                model_object_status.print_object_regions_status = ModelObjectStatus::PrintObjectRegionsStatus::Invalid;
                print_regions_reshuffled = true;
            } else if (print_object_regions &&
                verify_update_print_object_regions(
                    print_object.model_object()->volumes,
                    m_default_region_config,
                    num_extruders ,
                    painting_extruders,
                    *print_object_regions,
                    [it_print_object, it_print_object_end, &update_apply_status](const PrintRegionConfig &old_config, const PrintRegionConfig &new_config, const t_config_option_keys &diff_keys) {
                        for (auto it = it_print_object; it != it_print_object_end; ++it)
                            if ((*it)->m_shared_regions != nullptr)
                                update_apply_status((*it)->invalidate_state_by_config_options(old_config, new_config, diff_keys));
                    })) {
                // Regions are valid, just keep them.
            } else {
                // Regions were reshuffled.
                invalidate();
                // At least reuse layer ranges and bounding boxes of ModelVolumes.
                model_object_status.print_object_regions_status = ModelObjectStatus::PrintObjectRegionsStatus::PartiallyValid;
                print_regions_reshuffled = true;
            }
        }
        if (print_object_regions == nullptr || model_object_status.print_object_regions_status != ModelObjectStatus::PrintObjectRegionsStatus::Valid) {
            // Layer ranges with their associated configurations. Remove overlaps between the ranges
            // and create the regions from scratch.
            print_object_regions = generate_print_object_regions(
                print_object_regions,
                print_object.model_object()->volumes,
                LayerRanges(print_object.model_object()->layer_config_ranges),
                m_default_region_config,
                model_object_status.print_instances.front().trafo,
                num_extruders ,
                print_object.is_mm_painted() ? 0.f : float(print_object.config().xy_contour_compensation.value),
                painting_extruders);
        }
        for (auto it = it_print_object; it != it_print_object_end; ++it)
            if ((*it)->m_shared_regions) {
                assert((*it)->m_shared_regions == print_object_regions);
            } else {
                (*it)->m_shared_regions = print_object_regions;
                print_object_regions->ref_cnt_inc();
            }
        it_print_object = it_print_object_end;
    }
    if (print_regions_reshuffled) {
        // Update Print::m_print_regions from objects.
        struct cmp { bool operator() (const PrintRegion *l, const PrintRegion *r) const { return l->config_hash() == r->config_hash() && l->config() == r->config(); } };
        std::set<const PrintRegion*, cmp> region_set;
        m_print_regions.clear();
        PrintObjectRegions *print_object_regions = nullptr;
        for (PrintObject *print_object : m_objects)
            if (print_object_regions != print_object->m_shared_regions) {
                print_object_regions = print_object->m_shared_regions;
                for (std::unique_ptr<Slic3r::PrintRegion> &print_region : print_object_regions->all_regions)
                    if (auto it = region_set.find(print_region.get()); it == region_set.end()) {
                        int print_region_id = int(m_print_regions.size());
                        m_print_regions.emplace_back(print_region.get());
                        print_region->m_print_region_id = print_region_id;
                    } else {
                        print_region->m_print_region_id = (*it)->print_region_id();
                    }
            }
    }
    // Update SlicingParameters for each object where the SlicingParameters is not valid.
    // If it is not valid, then it is ensured that PrintObject.m_slicing_params is not in use
    // (posSlicing and posSupportMaterial was invalidated).
    for (PrintObject *object : m_objects)
    {
        object->update_slicing_parameters();
        m_support_used |= object->config().enable_support;
    }
#ifdef _DEBUG
    check_model_ids_equal(m_model, model);
#endif /* _DEBUG */
  //BBS: add timestamp logic
  if (apply_status != APPLY_STATUS_UNCHANGED)
    m_modified_count++;
  BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: finished,  this %2%, m_modified_count %3%, apply_status %4%, m_support_used %5%")%__LINE__ %this %m_modified_count %apply_status %m_support_used;
  return static_cast<ApplyStatus>(apply_status);
}
References Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::PrintObjectRegions::all_regions, Slic3r::ModelConfig::assign_config(), Slic3r::check_model_ids_equal(), Slic3r::check_model_ids_validity(), Slic3r::PrintObjectRegions::clear(), Slic3r::PrintObjectStatusDB::clear(), Slic3r::ModelObject::clear_instances(), Slic3r::ConfigOption::clone(), Slic3r::ModelObject::config, Slic3r::PrintRegion::config(), Slic3r::PrintObject::config(), Slic3r::PrintObject::config_apply(), Slic3r::PrintRegion::config_hash(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::curr_plate_index, Slic3r::custom_per_printz_gcodes_tool_changes_differ(), Slic3r::diff(), Slic3r::LayerHeightProfile::empty(), Slic3r::full_print_config_diffs(), Slic3r::CustomGCode::Info::gcodes, Slic3r::generate_print_object_regions(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_curr_plate_custom_gcodes(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::ConfigOption::getBool(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), Slic3r::ModelObject::input_file, Slic3r::ModelObject::instances, int, Slic3r::ModelObject::invalidate_bounding_box(), Slic3r::ModelObject::is_mm_painted(), Slic3r::PrintObject::is_mm_painted(), Slic3r::ModelObject::layer_config_ranges, Slic3r::ModelObject::layer_height_profile, Slic3r::layer_height_ranges_copy_configs(), Slic3r::layer_height_ranges_equal(), Slic3r::model_custom_seam_data_changed(), Slic3r::model_custom_supports_data_changed(), Slic3r::model_mmu_segmentation_data_changed(), Slic3r::PrintObjectBase::model_object(), Slic3r::model_object_list_equal(), Slic3r::model_object_list_extended(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::model_volume_list_update_supports(), Slic3r::ModelObject::name, Slic3r::DynamicPrintConfig::normalize_fdm_1(), Slic3r::DynamicPrintConfig::normalize_fdm_2(), Slic3r::Model::objects, Slic3r::ConfigBase::option(), Slic3r::ModelObject::origin_translation, Slic3r::posSlice, Slic3r::posSupportMaterial, Slic3r::print_config_diffs(), Slic3r::ModelObjectStatus::print_instances, Slic3r::ModelObjectStatus::print_object_regions, Slic3r::ModelObjectStatus::print_object_regions_status, Slic3r::print_objects_from_model_object(), Slic3r::print_objects_regions_invalidate_keep_some_volumes(), Slic3r::PrintObjectConfig, Slic3r::PrintRegionConfig, Slic3r::psGCodeExport, Slic3r::psSkirtBrim, Slic3r::psWipeTower, Slic3r::PrintObjectRegions::ref_cnt_inc(), Slic3r::ModelObjectStatusDB::reuse(), Slic3r::DynamicConfig::size(), size, Slic3r::ModelObjectStatus::status, Slic3r::PrintObjectStatus::status, Slic3r::ModelConfig::timestamp_matches(), Slic3r::ObjectWithTimestamp::timestamp_matches(), Slic3r::PrintObjectRegions::trafo_bboxes, Slic3r::trafos_differ_in_rotation_by_z_and_mirroring_by_xy_only(), Slic3r::transform3d_equal(), Slic3r::transform3d_lower(), Slic3r::verify_update_print_object_regions(), and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::Plater::load_gcode(), and Slic3r::GUI::PartPlate::load_gcode_from_file().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
auto_assign_extruders()
void Slic3r::Print::auto_assign_extruders (ModelObject * model_object) const
{
    // only assign extruders if object has more than one volume
    if (model_object->volumes.size() < 2)
        return;
//    size_t extruders = m_config.nozzle_diameter.values.size();
    for (size_t volume_id = 0; volume_id < model_object->volumes.size(); ++ volume_id) {
        ModelVolume *volume = model_object->volumes[volume_id];
        //FIXME Vojtech: This assigns an extruder ID even to a modifier volume, if it has a material assigned.
        if ((volume->is_model_part() || volume->is_modifier()) && ! volume->material_id().empty() && ! volume->config.has("extruder"))
            volume->config.set("extruder", int(volume_id + 1));
    }
}
References Slic3r::ModelObject::volumes.
brim_flow()
Flow Slic3r::Print::brim_flow () const
{
    ConfigOptionFloatOrPercent width = m_config.initial_layer_line_width;
    if (width.value <= 0)
        width = m_print_regions.front()->config().inner_wall_line_width;
    if (width.value <= 0)
        width = m_objects.front()->config().line_width;
    /* We currently use a random region's perimeter extruder.
       While this works for most cases, we should probably consider all of the perimeter
       extruders and take the one with, say, the smallest index.
       The same logic should be applied to the code that selects the extruder during G-code
       generation as well. */
    return Flow::new_from_config_width(
        frPerimeter,
        // Flow::new_from_config_width takes care of the percent to value substitution
    width,
        (float)m_config.nozzle_diameter.get_at(m_print_regions.front()->config().wall_filament-1),
    (float)this->skirt_first_layer_height());
}
References Slic3r::frPerimeter, m_config, m_objects, m_print_regions, and Slic3r::Flow::new_from_config_width().
Referenced by Slic3r::inner_brim_area(), Slic3r::make_brim(), Slic3r::make_brim(), Slic3r::make_inner_brim(), Slic3r::make_inner_brim(), Slic3r::make_inner_island_brim(), Slic3r::makeBrimInfill(), Slic3r::outer_inner_brim_area(), Slic3r::top_level_outer_brim_area(), and Slic3r::tryExPolygonOffset().
calib_mode() [1/2]
CalibMode & Slic3r::Print::calib_mode () inline
{ return m_calib_params.mode; }
References m_calib_params, and Slic3r::Calib_Params::mode.
Referenced by Slic3r::GCode::process_layer().
calib_mode() [2/2]
const CalibMode Slic3r::Print::calib_mode () const inline
{ return m_calib_params.mode; }
References m_calib_params, and Slic3r::Calib_Params::mode.
calib_params()
const Calib_Params & Slic3r::Print::calib_params () const inline
{ return m_calib_params; }
References m_calib_params.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::GCode::process_layer().
call_cancel_callback()
void Slic3r::PrintBase::call_cancel_callback () inline protected inherited
{ m_cancel_callback(); }
References Slic3r::PrintBase::m_cancel_callback.
Referenced by Slic3r::SLAPrint::apply(), and Slic3r::SLAPrint::set_task().
cancel()
void Slic3r::PrintBase::cancel () inline inherited
{ m_cancel_status = CANCELED_BY_USER; }
References Slic3r::PrintBase::CANCELED_BY_USER, and Slic3r::PrintBase::m_cancel_status.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::invalid_support_volumes(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), and Slic3r::BackgroundSlicingProcess::stop().
cancel_callback()
std::function< void()> Slic3r::PrintBase::cancel_callback () inline protected inherited
{ return m_cancel_callback; }
References Slic3r::PrintBase::m_cancel_callback.
Referenced by Slic3r::PrintObjectBase::cancel_callback(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::invalidate_all_steps(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::invalidate_step(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::invalidate_steps(), and Slic3r::PrintBase::set_cancel_callback().
cancel_internal()
void Slic3r::PrintBase::cancel_internal () inline inherited
{ m_cancel_status = CANCELED_INTERNAL; }
References Slic3r::PrintBase::CANCELED_INTERNAL, and Slic3r::PrintBase::m_cancel_status.
Referenced by Slic3r::BackgroundSlicingProcess::stop_internal().
cancel_status()
CancelStatus Slic3r::PrintBase::cancel_status () const inline inherited
{ return m_cancel_status.load(std::memory_order_acquire); }
References Slic3r::PrintBase::m_cancel_status.
Referenced by Slic3r::BackgroundSlicingProcess::thread_proc().
canceled()
bool Slic3r::PrintBase::canceled () const inline inherited
{ return m_cancel_status.load(std::memory_order_acquire) != NOT_CANCELED; }
References Slic3r::PrintBase::m_cancel_status, and Slic3r::PrintBase::NOT_CANCELED.
Referenced by Slic3r::SLAPrint::Steps::canceled(), Slic3r::BackgroundSlicingProcess::execute_ui_task(), Slic3r::SLAPrint::Steps::rasterize(), Slic3r::SLAPrint::Steps::support_tree(), Slic3r::BackgroundSlicingProcess::thread_proc(), and Slic3r::BackgroundSlicingProcess::throw_if_canceled().
check_multi_filament_valid()
StringObjectException Slic3r::Print::check_multi_filament_valid (const Print & print) static private
{
    auto print_config = print.config();
    std::vector<unsigned int> extruders = print.extruders();
    std::vector<std::string> filament_types;
    filament_types.reserve(extruders.size());
    for (const auto& extruder_idx : extruders)
        filament_types.push_back(print_config.filament_type.get_at(extruder_idx));
    if (!check_multi_filaments_compatibility(filament_types))
        return { L("Can not print multiple filaments which have large difference of temperature together. Otherwise, the extruder and nozzle may be blocked or damaged during printing") };
    return {std::string()};
}
References check_multi_filaments_compatibility(), config(), extruders(), and L.
Referenced by validate().
check_multi_filaments_compatibility()
bool Slic3r::Print::check_multi_filaments_compatibility (const std::vector< std::string > & filament_types) static
{
    static std::map<std::string, bool> filament_is_high_temp{
            {"PLA",     false},
            {"PLA-CF",  false},
            //{"PETG",    true},
            {"ABS",     true},
            {"TPU",     false},
            {"PA",      true},
            {"PA-CF",   true},
            {"PET-CF",  true},
            {"PC",      true},
            {"ASA",     true},
            {"HIPS",    true}
    };
    bool has_high_temperature_filament = false;
    bool has_low_temperature_filament = false;
    for (const auto& type : filament_types)
        if (filament_is_high_temp.find(type) != filament_is_high_temp.end()) {
            if (filament_is_high_temp[type])
                has_high_temperature_filament = true;
            else
                has_low_temperature_filament = true;
        }
    if (has_high_temperature_filament && has_low_temperature_filament)
        return false;
    return true;
}
Referenced by check_multi_filament_valid().
clear()
void Slic3r::Print::clear () override virtual
Implements Slic3r::PrintBase.
{
  std::scoped_lock<std::mutex> lock(this->state_mutex());
    // The following call should stop background processing if it is running.
    this->invalidate_all_steps();
  for (PrintObject *object : m_objects)
    delete object;
  m_objects.clear();
    m_print_regions.clear();
    m_model.clear_objects();
}
References Slic3r::Model::clear_objects(), Slic3r::PrintBaseWithState< PrintStep, psCount >::invalidate_all_steps(), Slic3r::PrintBase::m_model, m_objects, m_print_regions, and Slic3r::PrintBase::state_mutex().
Referenced by ~Print().
config()
const PrintConfig & Slic3r::Print::config () const inline
{ return m_config; }
References m_config.
Referenced by Slic3r::FillLightning::Generator::Generator(), Slic3r::FillLightning::Generator::Generator(), Slic3r::ToolOrdering::ToolOrdering(), Slic3r::TreeSupport::TreeSupport(), Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::GUI::GLCanvas3D::_max_bounding_box(), Slic3r::GCode::_print_first_layer_bed_temperature(), Slic3r::GCode::_print_first_layer_extruder_temperatures(), Slic3r::FillAdaptive::adaptive_fill_line_spacing(), Slic3r::ToolOrdering::assign_custom_gcodes(), Slic3r::LayerRegion::bridging_flow(), check_multi_filament_valid(), Slic3r::PrintRegion::collect_object_printing_extruders(), Slic3r::TreeSupport::detect_overhangs(), Slic3r::GCode::do_export(), Slic3r::TreeSupport::draw_circles(), Slic3r::WipingExtrusions::ensure_perimeters_infills_order(), Slic3r::ToolOrdering::generate_first_layer_tool_order(), Slic3r::get_default_perimeter_spacing(), Slic3r::get_path_of_change_filament(), Slic3r::get_wipe_tower_extrusions_extents(), Slic3r::getObjectExtruderMap(), Slic3r::DoExport::init_ooze_prevention(), Slic3r::inner_brim_area(), Slic3r::layered_print_cleareance_valid(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::make_brim(), Slic3r::make_brim(), Slic3r::Layer::make_fills(), Slic3r::make_inner_brim(), Slic3r::make_inner_island_brim(), Slic3r::Layer::make_ironing(), Slic3r::LayerRegion::make_perimeters(), Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers(), Slic3r::WipingExtrusions::mark_wiping_extrusions(), Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::multi_material_segmentation_by_painting(), Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::LayerRegion::prepare_fill_surfaces(), Slic3r::GCode::print_machine_envelope(), Slic3r::GCode::process_layer(), Slic3r::GUI::PartPlate::render_height_limit(), sequential_print_clearance_valid(), Slic3r::GCode::set_object_info(), Slic3r::LayerRegion::simplify_loop(), Slic3r::LayerRegion::simplify_multi_path(), Slic3r::LayerRegion::simplify_path(), Slic3r::Layer::simplify_support_loop(), Slic3r::Layer::simplify_support_multi_path(), Slic3r::Layer::simplify_support_path(), Slic3r::Skirt::skirt_loops_per_extruder_all_printing(), Slic3r::PrintObject::slice_volumes(), Slic3r::top_level_outer_brim_area(), Slic3r::tryExPolygonOffset(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), validate(), and Slic3r::DoExport::validate_custom_gcode().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
default_object_config()
const PrintObjectConfig & Slic3r::Print::default_object_config () const inline
{ return m_default_object_config; }
References m_default_object_config.
default_region_config()
const PrintRegionConfig & Slic3r::Print::default_region_config () const inline
{ return m_default_region_config; }
References m_default_region_config.
Referenced by Slic3r::GCode::_do_export(), Slic3r::WipingExtrusions::ensure_perimeters_infills_order(), and Slic3r::GCode::process_layer().
empty()
bool Slic3r::Print::empty () const inline override virtual
Implements Slic3r::PrintBase.
{ return m_objects.empty(); }
References m_objects.
Referenced by Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), and sequential_print_clearance_valid().
enable_timelapse_print()
bool Slic3r::Print::enable_timelapse_print () const
{
    return m_config.timelapse_type.value == TimelapseType::tlSmooth;
}
Referenced by Slic3r::GUI::GCodeViewer::load_shells().
export_cached_data()
int Slic3r::Print::export_cached_data (const std::string & dir_path, bool with_space = false) virtual
Reimplemented from Slic3r::PrintBase.
{
    int ret = 0;
    boost::filesystem::path directory_path(directory);
    auto convert_layer_to_json = [](json& layer_json, const Layer* layer) {
        json slice_polygons_json = json::array(), slice_bboxs_json = json::array(), layer_regions_json = json::array();
        layer_json[JSON_LAYER_PRINT_Z] = layer->print_z;
        layer_json[JSON_LAYER_HEIGHT] = layer->height;
        layer_json[JSON_LAYER_SLICE_Z] = layer->slice_z;
        layer_json[JSON_LAYER_ID] = layer->id();
        //layer_json["slicing_errors"] = layer->slicing_errors;
        //sliced_polygons
        for (const ExPolygon& slice_polygon : layer->lslices) {
            json slice_polygon_json = slice_polygon;
            slice_polygons_json.push_back(std::move(slice_polygon_json));
        }
        layer_json[JSON_LAYER_SLICED_POLYGONS] = std::move(slice_polygons_json);
        //sliced_bbox
        for (const BoundingBox& slice_bbox : layer->lslices_bboxes) {
            json bbox_json = json::array();
            bbox_json = slice_bbox;
            slice_bboxs_json.push_back(std::move(bbox_json));
        }
        layer_json[JSON_LAYER_SLLICED_BBOXES] = std::move(slice_bboxs_json);
        for (const LayerRegion *layer_region : layer->regions()) {
            json region_json = *layer_region;
            layer_regions_json.push_back(std::move(region_json));
        }
        layer_json[JSON_LAYER_REGIONS] = std::move(layer_regions_json);
        return;
    };
    //firstly clear this directory
    if (fs::exists(directory_path)) {
        fs::remove_all(directory_path);
    }
    try {
        if (!fs::create_directory(directory_path)) {
            BOOST_LOG_TRIVIAL(error) << boost::format("create directory %1% failed")%directory;
            return CLI_EXPORT_CACHE_DIRECTORY_CREATE_FAILED;
        }
    }
    catch (...)
    {
        BOOST_LOG_TRIVIAL(error) << boost::format("create directory %1% failed")%directory;
        return CLI_EXPORT_CACHE_DIRECTORY_CREATE_FAILED;
    }
    int count = 0;
    std::vector<std::string> filename_vector;
    std::vector<json> json_vector;
    for (PrintObject *obj : m_objects) {
        const ModelObject* model_obj = obj->model_object();
        if (obj->get_shared_object()) {
            BOOST_LOG_TRIVIAL(info) << boost::format("shared object %1%, skip directly")%model_obj->name;
            continue;
        }
        const PrintInstance &print_instance = obj->instances()[0];
        const ModelInstance *model_instance = print_instance.model_instance;
        size_t identify_id = (model_instance->loaded_id > 0)?model_instance->loaded_id: model_instance->id().id;
        std::string file_name = directory +"/obj_"+std::to_string(identify_id)+".json";
        BOOST_LOG_TRIVIAL(info) << boost::format("begin to dump object %1%, identify_id %2% to %3%")%model_obj->name %identify_id %file_name;
        try {
            json root_json, layers_json = json::array(), support_layers_json = json::array(), first_layer_groups = json::array();
            root_json[JSON_OBJECT_NAME] = model_obj->name;
            root_json[JSON_IDENTIFY_ID] = identify_id;
            //export the layers
            std::vector<json> layers_json_vector(obj->layer_count());
            tbb::parallel_for(
                tbb::blocked_range<size_t>(0, obj->layer_count()),
                [&layers_json_vector, obj, convert_layer_to_json](const tbb::blocked_range<size_t>& layer_range) {
                    for (size_t layer_index = layer_range.begin(); layer_index < layer_range.end(); ++ layer_index) {
                        const Layer *layer = obj->get_layer(layer_index);
                        json layer_json;
                        convert_layer_to_json(layer_json, layer);
                        layers_json_vector[layer_index] = std::move(layer_json);
                    }
                }
            );
            for (int l_index = 0; l_index < layers_json_vector.size(); l_index++) {
                layers_json.push_back(std::move(layers_json_vector[l_index]));
            }
            layers_json_vector.clear();
            /*for (const Layer *layer : obj->layers()) {
                // for each layer
                json layer_json;
                convert_layer_to_json(layer_json, layer);
                layers_json.push_back(std::move(layer_json));
            }*/
            root_json[JSON_LAYERS] = std::move(layers_json);
            //export the support layers
            std::vector<json> support_layers_json_vector(obj->support_layer_count());
            tbb::parallel_for(
                tbb::blocked_range<size_t>(0, obj->support_layer_count()),
                [&support_layers_json_vector, obj, convert_layer_to_json](const tbb::blocked_range<size_t>& support_layer_range) {
                    for (size_t s_layer_index = support_layer_range.begin(); s_layer_index < support_layer_range.end(); ++ s_layer_index) {
                        const SupportLayer *support_layer = obj->get_support_layer(s_layer_index);
                        json support_layer_json, support_islands_json = json::array(), support_fills_json, supportfills_entities_json = json::array();
                        convert_layer_to_json(support_layer_json, support_layer);
                        support_layer_json[JSON_SUPPORT_LAYER_INTERFACE_ID] = support_layer->interface_id();
                        support_layer_json[JSON_SUPPORT_LAYER_TYPE] = support_layer->support_type;
                        //support_islands
                        for (const ExPolygon& support_island : support_layer->support_islands) {
                            json support_island_json = support_island;
                            support_islands_json.push_back(std::move(support_island_json));
                        }
                        support_layer_json[JSON_SUPPORT_LAYER_ISLANDS] = std::move(support_islands_json);
                        //support_fills
                        support_fills_json[JSON_EXTRUSION_NO_SORT] = support_layer->support_fills.no_sort;
                        support_fills_json[JSON_EXTRUSION_ENTITY_TYPE] = JSON_EXTRUSION_TYPE_COLLECTION;
                        for (const ExtrusionEntity* extrusion_entity : support_layer->support_fills.entities) {
                            json supportfill_entity_json, supportfill_entity_paths_json = json::array();
                            bool ret = convert_extrusion_to_json(supportfill_entity_json, supportfill_entity_paths_json, extrusion_entity);
                            if (!ret)
                                continue;
                            supportfills_entities_json.push_back(std::move(supportfill_entity_json));
                        }
                        support_fills_json[JSON_EXTRUSION_ENTITIES] = std::move(supportfills_entities_json);
                        support_layer_json[JSON_SUPPORT_LAYER_FILLS] = std::move(support_fills_json);
                        support_layers_json_vector[s_layer_index] = std::move(support_layer_json);
                    }
                }
            );
            for (int s_index = 0; s_index < support_layers_json_vector.size(); s_index++) {
                support_layers_json.push_back(std::move(support_layers_json_vector[s_index]));
            }
            support_layers_json_vector.clear();
            /*for (const SupportLayer *support_layer : obj->support_layers()) {
                json support_layer_json, support_islands_json = json::array(), support_fills_json, supportfills_entities_json = json::array();
                convert_layer_to_json(support_layer_json, support_layer);
                support_layer_json[JSON_SUPPORT_LAYER_INTERFACE_ID] = support_layer->interface_id();
                //support_islands
                for (const ExPolygon& support_island : support_layer->support_islands.expolygons) {
                    json support_island_json = support_island;
                    support_islands_json.push_back(std::move(support_island_json));
                }
                support_layer_json[JSON_SUPPORT_LAYER_ISLANDS] = std::move(support_islands_json);
                //support_fills
                support_fills_json[JSON_EXTRUSION_NO_SORT] = support_layer->support_fills.no_sort;
                support_fills_json[JSON_EXTRUSION_ENTITY_TYPE] = JSON_EXTRUSION_TYPE_COLLECTION;
                for (const ExtrusionEntity* extrusion_entity : support_layer->support_fills.entities) {
                    json supportfill_entity_json, supportfill_entity_paths_json = json::array();
                    bool ret = convert_extrusion_to_json(supportfill_entity_json, supportfill_entity_paths_json, extrusion_entity);
                    if (!ret)
                        continue;
                    supportfills_entities_json.push_back(std::move(supportfill_entity_json));
                }
                support_fills_json[JSON_EXTRUSION_ENTITIES] = std::move(supportfills_entities_json);
                support_layer_json[JSON_SUPPORT_LAYER_FILLS] = std::move(support_fills_json);
                support_layers_json.push_back(std::move(support_layer_json));
            } // for each layer*/
            root_json[JSON_SUPPORT_LAYERS] = std::move(support_layers_json);
            const std::vector<groupedVolumeSlices> &first_layer_obj_groups =  obj->firstLayerObjGroups();
            for (size_t s_group_index = 0; s_group_index < first_layer_obj_groups.size(); ++ s_group_index) {
                groupedVolumeSlices group = first_layer_obj_groups[s_group_index];
                //convert the id
                for (ObjectID& obj_id : group.volume_ids)
                {
                    const ModelVolume* currentModelVolumePtr = nullptr;
                    //BBS: support shared object logic
                    const PrintObject* shared_object = obj->get_shared_object();
                    if (!shared_object)
                        shared_object = obj;
                    const ModelVolumePtrs& volumes_ptr = shared_object->model_object()->volumes;
                    size_t volume_count = volumes_ptr.size();
                    for (size_t index = 0; index < volume_count; index ++) {
                        currentModelVolumePtr = volumes_ptr[index];
                        if (currentModelVolumePtr->id() == obj_id) {
                            obj_id.id = index;
                            break;
                        }
                    }
                }
                json first_layer_group_json;
                first_layer_group_json = group;
                first_layer_groups.push_back(std::move(first_layer_group_json));
            }
            root_json[JSON_FIRSTLAYER_GROUPS] = std::move(first_layer_groups);
            filename_vector.push_back(file_name);
            json_vector.push_back(std::move(root_json));
            /*boost::nowide::ofstream c;
            c.open(file_name, std::ios::out | std::ios::trunc);
            if (with_space)
                c << std::setw(4) << root_json << std::endl;
            else
                c << root_json.dump(0) << std::endl;
            c.close();*/
            count ++;
            BOOST_LOG_TRIVIAL(info) << boost::format("will dump object %1%'s json to %2%.")%model_obj->name%file_name;
        }
        catch(std::exception &err) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": save to "<<file_name<<" got a generic exception, reason = " << err.what();
            ret = CLI_EXPORT_CACHE_WRITE_FAILED;
        }
    }
    boost::mutex mutex;
    tbb::parallel_for(
        tbb::blocked_range<size_t>(0, filename_vector.size()),
        [filename_vector, &json_vector, with_space, &ret, &mutex](const tbb::blocked_range<size_t>& output_range) {
            for (size_t object_index = output_range.begin(); object_index < output_range.end(); ++ object_index) {
                try {
                    boost::nowide::ofstream c;
                    c.open(filename_vector[object_index], std::ios::out | std::ios::trunc);
                    if (with_space)
                        c << std::setw(4) << json_vector[object_index] << std::endl;
                    else
                        c << json_vector[object_index].dump(0) << std::endl;
                    c.close();
                }
                catch(std::exception &err) {
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": save to "<<filename_vector[object_index]<<" got a generic exception, reason = " << err.what();
                    boost::unique_lock l(mutex);
                    ret = CLI_EXPORT_CACHE_WRITE_FAILED;
                }
            }
        }
    );
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": total printobject count %1%, saved %2%, ret=%3%")%m_objects.size() %count %ret;
    return ret;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::array, CLI_EXPORT_CACHE_DIRECTORY_CREATE_FAILED, count, error, Slic3r::PrintObject::get_shared_object(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), JSON_FIRSTLAYER_GROUPS, JSON_IDENTIFY_ID, JSON_LAYER_HEIGHT, JSON_LAYER_ID, JSON_LAYER_PRINT_Z, JSON_LAYER_REGIONS, JSON_LAYER_SLICE_Z, JSON_LAYER_SLICED_POLYGONS, JSON_LAYER_SLLICED_BBOXES, JSON_LAYERS, JSON_OBJECT_NAME, JSON_SUPPORT_LAYERS, Slic3r::ModelInstance::loaded_id, Slic3r::PrintInstance::model_instance, Slic3r::PrintObjectBase::model_object(), Slic3r::ModelObject::name, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::push_back(), Slic3r::groupedVolumeSlices::volume_ids, and Slic3r::ModelObject::volumes.
export_gcode()
std::string Slic3r::Print::export_gcode (const std::string & path_template, GCodeProcessorResult * result, ThumbnailsGeneratorCallback thumbnail_cb = nullptr)
{
    // output everything to a G-code file
    // The following call may die if the filename_format template substitution fails.
    std::string path = this->output_filepath(path_template);
    std::string message;
    if (!path.empty() && result == nullptr) {
        // Only show the path if preview_data is not set -> running from command line.
        message = L("Exporting G-code");
        message += " to ";
        message += path;
    } else
        message = L("Generating G-code");
    this->set_status(80, message);
    // The following line may die for multiple reasons.
    GCode gcode;
    //BBS: compute plate offset for gcode-generator
    const Vec3d origin = this->get_plate_origin();
    gcode.set_gcode_offset(origin(0), origin(1));
    gcode.do_export(this, path.c_str(), result, thumbnail_cb);
    //BBS
    result->conflict_result = m_conflict_result;
    return path.c_str();
}
References Slic3r::GCodeProcessorResult::conflict_result, and L.
Referenced by Slic3r::BackgroundSlicingProcess::process_fff().
export_gcode_from_previous_file()
void Slic3r::Print::export_gcode_from_previous_file (const std::string & file, GCodeProcessorResult * result, ThumbnailsGeneratorCallback thumbnail_cb = nullptr)
{
    try {
        GCodeProcessor processor;
        const Vec3d origin = this->get_plate_origin();
        processor.set_xy_offset(origin(0), origin(1));
        //processor.enable_producers(true);
        processor.process_file(file);
        *result = std::move(processor.extract_result());
    } catch (std::exception & /* ex */) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ <<  boost::format(": found errors when process gcode file %1%") %file.c_str();
        throw Slic3r::RuntimeError(
            std::string("Failed to process the G-code file ") + file + " from previous 3mf\n");
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ <<  boost::format(":  process the G-code file %1% successfully")%file.c_str();
}
References error, and processor.
Referenced by Slic3r::BackgroundSlicingProcess::process_fff().
extruders()
std::vector< unsigned int > Slic3r::Print::extruders (bool conside_custom_gcode = false) const
{
    std::vector<unsigned int> extruders = this->object_extruders();
    append(extruders, this->support_material_extruders());
    if (conside_custom_gcode) {
        //BBS
        int num_extruders = m_config.filament_colour.size();
        for (auto plate_data : m_model.plates_custom_gcodes) {
            for (auto item : plate_data.second.gcodes) {
                if (item.type == CustomGCode::Type::ToolChange && item.extruder <= num_extruders)
                    extruders.push_back((unsigned int)(item.extruder - 1));
            }
        }
    }
    sort_remove_duplicates(extruders);
    return extruders;
}
References Slic3r::append(), extruders(), m_config, Slic3r::PrintBase::m_model, object_extruders(), Slic3r::Model::plates_custom_gcodes, Slic3r::sort_remove_duplicates(), support_material_extruders(), and Slic3r::CustomGCode::ToolChange.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GCode::_print_first_layer_extruder_temperatures(), check_multi_filament_valid(), extruders(), has_infinite_skirt(), Slic3r::DoExport::init_ooze_prevention(), Slic3r::layered_print_cleareance_valid(), Slic3r::GUI::Preview::load_print_as_fff(), Slic3r::GUI::GCodeViewer::load_shells(), max_allowed_layer_height(), object_extruders(), Slic3r::GCode::process_layer(), support_material_extruders(), and validate().
finalize()
virtual void Slic3r::PrintBase::finalize () inline virtual inherited
Reimplemented in Slic3r::SLAPrint.
{}
Referenced by Slic3r::BackgroundSlicingProcess::thread_proc().
finalize_first_layer_convex_hull()
void Slic3r::Print::finalize_first_layer_convex_hull () private
{
    append(m_first_layer_convex_hull.points, m_skirt_convex_hull);
    if (m_first_layer_convex_hull.empty()) {
        // Neither skirt nor brim was extruded. Collect points of printed objects from 1st layer.
        for (Polygon &poly : this->first_layer_islands())
            append(m_first_layer_convex_hull.points, std::move(poly.points));
    }
    append(m_first_layer_convex_hull.points, this->first_layer_wipe_tower_corners());
    m_first_layer_convex_hull = Geometry::convex_hull(m_first_layer_convex_hull.points);
}
References Slic3r::append().
finished()
bool Slic3r::Print::finished () const inline override virtual
Implements Slic3r::PrintBase.
{ return this->is_step_done(psGCodeExport); }
References is_step_done(), and Slic3r::psGCodeExport.
first_layer_convex_hull()
const Polygon & Slic3r::Print::first_layer_convex_hull () const inline
{ return m_first_layer_convex_hull; }
References m_first_layer_convex_hull.
Referenced by Slic3r::GCode::_do_export().
first_layer_islands()
Polygons Slic3r::Print::first_layer_islands () const private
{
    Polygons islands;
    for (PrintObject *object : m_objects) {
        Polygons object_islands;
        for (ExPolygon &expoly : object->m_layers.front()->lslices)
            object_islands.push_back(expoly.contour);
        if (!object->support_layers().empty()) {
            if (object->support_layers().front()->support_type==stInnerNormal)
                object->support_layers().front()->support_fills.polygons_covered_by_spacing(object_islands, float(SCALED_EPSILON));
            else if(object->support_layers().front()->support_type==stInnerTree) {
                ExPolygons &expolys_first_layer = object->m_support_layers.front()->lslices;
                for (ExPolygon &expoly : expolys_first_layer) { object_islands.push_back(expoly.contour); }
            }
        }
        islands.reserve(islands.size() + object_islands.size() * object->instances().size());
        for (const PrintInstance &instance : object->instances())
            for (Polygon &poly : object_islands) {
                islands.push_back(poly);
                islands.back().translate(instance.shift);
            }
    }
    return islands;
}
References SCALED_EPSILON, Slic3r::stInnerNormal, and Slic3r::stInnerTree.
first_layer_wipe_tower_corners()
std::vector< Point > Slic3r::Print::first_layer_wipe_tower_corners (bool check_wipe_tower_existance = true) const
{
    std::vector<Point> corners;
    if (check_wipe_tower_existance && (!has_wipe_tower() || m_wipe_tower_data.tool_changes.empty()))
        return corners;
    {
        double width = m_config.prime_tower_width + 2*m_wipe_tower_data.brim_width;
        double depth = m_wipe_tower_data.depth + 2*m_wipe_tower_data.brim_width;
        Vec2d pt0(-m_wipe_tower_data.brim_width, -m_wipe_tower_data.brim_width);
        for (Vec2d pt : {
                pt0,
                Vec2d(pt0.x()+width, pt0.y()      ),
                Vec2d(pt0.x()+width, pt0.y()+depth),
                Vec2d(pt0.x(),       pt0.y()+depth)
            }) {
            pt = Eigen::Rotation2Dd(Geometry::deg2rad(m_config.wipe_tower_rotation_angle.value)) * pt;
            // BBS: add partplate logic
            pt += Vec2d(m_config.wipe_tower_x.get_at(m_plate_index) + m_origin(0), m_config.wipe_tower_y.get_at(m_plate_index) + m_origin(1));
            corners.emplace_back(Point(scale_(pt.x()), scale_(pt.y())));
        }
    }
    return corners;
}
References scale_.
Referenced by Slic3r::CLI::run().
full_print_config()
const DynamicPrintConfig & Slic3r::PrintBase::full_print_config () const inline inherited
{ return m_full_print_config; }
References Slic3r::PrintBase::m_full_print_config.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GCode::append_full_config(), Slic3r::anonymous_namespace{SL1.cpp}::fill_iniconf(), Slic3r::anonymous_namespace{SL1.cpp}::fill_slicerconf(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::BackgroundSlicingProcess::finalize_gcode(), Slic3r::BackgroundSlicingProcess::prepare_upload(), and Slic3r::GUI::SLAImportJob::reset().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_brimMap()
std::map< ObjectID, ExtrusionEntityCollection > & Slic3r::Print::get_brimMap () inline
{ return m_brimMap; }
References m_brimMap.
get_conflict_result()
ConflictResultOpt Slic3r::Print::get_conflict_result () const inline
{ return m_conflict_result; }
References m_conflict_result.
get_conflict_string()
std::string Slic3r::Print::get_conflict_string () const inline
    {
        std::string result;
        if (m_conflict_result) {
            result = "Found gcode path conflicts between object " + m_conflict_result.value()._objName1 + " and " + m_conflict_result.value()._objName2;
        }
        return result;
    }
References m_conflict_result.
get_modified_count()
int Slic3r::Print::get_modified_count () const inline
{return m_modified_count;}
References m_modified_count.
Referenced by Slic3r::GUI::GCodeViewer::load_shells().
get_no_check_flag()
bool Slic3r::PrintBase::get_no_check_flag () const inline inherited
{ return m_no_check; }
References Slic3r::PrintBase::m_no_check.
get_object() [1/3]
const PrintObject * Slic3r::Print::get_object (ObjectID object_id) const inline
{
        auto it = std::find_if(m_objects.begin(), m_objects.end(),
            [object_id](const PrintObject *obj) { return obj->id() == object_id; });
        return (it == m_objects.end()) ? nullptr : *it;
    }
References m_objects.
get_object() [2/3]
PrintObject * Slic3r::Print::get_object (size_t idx) inline
{ return const_cast<PrintObject*>(m_objects[idx]); }
References m_objects.
Referenced by Slic3r::make_brim(), and Slic3r::GCode::process_layer().
get_object() [3/3]
const PrintObject * Slic3r::Print::get_object (size_t idx) const inline
{ return m_objects[idx]; }
References m_objects.
get_plate_index()
int Slic3r::PrintBase::get_plate_index () const inline inherited
{ return m_plate_index; }
References Slic3r::PrintBase::m_plate_index.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::GCode::append_full_config(), Slic3r::GUI::get_wipe_tower_arrangepoly(), Slic3r::get_wipe_tower_extrusions_extents(), Slic3r::layered_print_cleareance_valid(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::GCode::process_layer(), and validate().
get_plate_name()
std::string Slic3r::PrintBase::get_plate_name () const inline inherited
{ return m_plate_name; }
References Slic3r::PrintBase::m_plate_name.
Referenced by Slic3r::GCode::_do_export().
get_plate_origin()
const Vec3d Slic3r::Print::get_plate_origin () const inline
{ return m_origin; }
References m_origin.
Referenced by Slic3r::TreeSupport::TreeSupport(), Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::get_wipe_tower_extrusions_extents(), Slic3r::layered_print_cleareance_valid(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::make_brim(), sequential_print_clearance_valid(), and Slic3r::PrintInstance::shift_without_plate_offset().
get_print_region()
const PrintRegion & Slic3r::Print::get_print_region (size_t idx) const inline
{ return *m_print_regions[idx]; }
References m_print_regions.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GCode::extrude_infill(), Slic3r::GCode::extrude_perimeters(), and Slic3r::GCode::process_layer().
get_tool_ordering()
const ToolOrdering & Slic3r::Print::get_tool_ordering () const inline
{ return m_wipe_tower_data.tool_ordering; }
References m_wipe_tower_data, and Slic3r::WipeTowerData::tool_ordering.
Referenced by Slic3r::CLI::run().
has_auto_brim()
bool Slic3r::Print::has_auto_brim () const inline
{
        return std::any_of(m_objects.begin(), m_objects.end(), [](PrintObject* object) { return object->config().brim_type == btAutoBrim; });
    }
References m_objects.
has_brim()
bool Slic3r::Print::has_brim () const
{
    return std::any_of(m_objects.begin(), m_objects.end(), [](PrintObject *object) { return object->has_brim(); });
}
References m_objects.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::PrintRegion::collect_object_printing_extruders(), Slic3r::TreeSupport::draw_circles(), and Slic3r::GCode::process_layer().
has_infinite_skirt()
bool Slic3r::Print::has_infinite_skirt () const
{
    return (m_config.draft_shield == dsEnabled && m_config.skirt_loops > 0) || (m_config.ooze_prevention && this->extruders().size() > 1);
}
References Slic3r::dsEnabled, extruders(), and m_config.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::TreeSupport::draw_circles(), Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers(), and Slic3r::GCode::process_layer().
has_skirt()
bool Slic3r::Print::has_skirt () const
{
    return (m_config.skirt_height > 0 && m_config.skirt_loops > 0) || m_config.draft_shield != dsDisabled;
}
References Slic3r::dsDisabled, and m_config.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::Skirt::make_skirt_loops_per_extruder_1st_layer(), and Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers().
has_support_material()
bool Slic3r::Print::has_support_material () const
{
    for (const PrintObject *object : m_objects)
        if (object->has_support_material())
            return true;
    return false;
}
References m_objects.
Referenced by Slic3r::GCode::_do_export(), Slic3r::inner_brim_area(), Slic3r::make_inner_island_brim(), and Slic3r::top_level_outer_brim_area().
has_wipe_tower()
bool Slic3r::Print::has_wipe_tower () const
{
    if (m_config.enable_prime_tower.value == true) {
        if (enable_timelapse_print())
            return true;
        return !m_config.spiral_mode.value && m_config.filament_diameter.values.size() > 1;
    }
    return false;
}
Referenced by Slic3r::GCode::_do_export(), Slic3r::layered_print_cleareance_valid(), Slic3r::CLI::run(), and validate().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
invalidate_all_steps()
bool Slic3r::PrintBaseWithState< PrintStep , COUNT >::invalidate_all_steps () inline protected inherited
        { return m_state.invalidate_all(this->cancel_callback()); }
invalidate_state_by_config_options()
bool Slic3r::Print::invalidate_state_by_config_options (const ConfigOptionResolver & new_config, const std::vector< t_config_option_key > & opt_keys) private
{
    if (opt_keys.empty())
        return false;
    // Cache the plenty of parameters, which influence the G-code generator only,
    // or they are only notes not influencing the generated G-code.
    static std::unordered_set<std::string> steps_gcode = {
        //BBS
        "additional_cooling_fan_speed",
        "reduce_crossing_wall",
        "max_travel_detour_distance",
        "printable_area",
        //BBS: add bed_exclude_area
        "bed_exclude_area",
        "before_layer_change_gcode",
        "enable_pressure_advance",
        "pressure_advance",
        "enable_overhang_bridge_fan",
        "overhang_fan_speed",
        "overhang_fan_threshold",
        "slow_down_for_layer_cooling",
        "default_acceleration",
        "deretraction_speed",
        "close_fan_the_first_x_layers",
        "machine_end_gcode",
        "filament_end_gcode",
        "post_process",
        "extruder_clearance_height_to_rod",
        "extruder_clearance_height_to_lid",
        "extruder_clearance_radius",
        "extruder_colour",
        "extruder_offset",
        "filament_flow_ratio",
        "reduce_fan_stop_start_freq",
        "fan_cooling_layer_time",
        "full_fan_speed_layer",
        "fan_kickstart",
        "fan_speedup_overhangs",
        "fan_speedup_time",
        "filament_colour",
        "default_filament_colour",
        "filament_diameter",
        "filament_density",
        "filament_cost",
        "outer_wall_acceleration",
        "inner_wall_acceleration",
        "initial_layer_acceleration",
        "top_surface_acceleration",
        "bridge_acceleration",
        "travel_acceleration",
        "sparse_infill_acceleration",
        "internal_solid_infill_acceleration"
        // BBS
        "cool_plate_temp_initial_layer",
        "eng_plate_temp_initial_layer",
        "hot_plate_temp_initial_layer",
        "textured_plate_temp_initial_layer",
        "gcode_add_line_number",
        "layer_change_gcode",
        "fan_min_speed",
        "fan_max_speed",
        "printable_height",
        "slow_down_min_speed",
#ifdef HAS_PRESSURE_EQUALIZER
        "max_volumetric_extrusion_rate_slope_positive",
        "max_volumetric_extrusion_rate_slope_negative",
#endif /* HAS_PRESSURE_EQUALIZER */
        "reduce_infill_retraction",
        "filename_format",
        "retraction_minimum_travel",
        "retract_before_wipe",
        "retract_when_changing_layer",
        "retraction_length",
        "retract_length_toolchange",
        "z_hop",
        "retract_lift_above",
        "retract_lift_below",
        "retract_lift_enforce",
        "retract_restart_extra",
        "retract_restart_extra_toolchange",
        "retraction_speed",
        "use_firmware_retraction",
        "slow_down_layer_time",
        "standby_temperature_delta",
        "machine_start_gcode",
        "filament_start_gcode",
        "change_filament_gcode",
        "wipe",
        // BBS
        "wipe_distance",
        "curr_bed_type",
        "nozzle_volume",
        "chamber_temperature",
        "thumbnails",
        "nozzle_hrc",
        "required_nozzle_HRC",
        "upward_compatible_machine",
        // SoftFever
        "seam_gap",
        "role_based_wipe_speed",
        "wipe_speed",
        "use_relative_e_distances",
        "accel_to_decel_enable",
        "accel_to_decel_factor",
        "wipe_on_loops",
        "gcode_comments",
        "gcode_label_objects",
        "exclude_object",
        "support_material_interface_fan_speed"
    };
    static std::unordered_set<std::string> steps_ignore;
    std::vector<PrintStep> steps;
    std::vector<PrintObjectStep> osteps;
    bool invalidated = false;
    for (const t_config_option_key &opt_key : opt_keys) {
        if (steps_gcode.find(opt_key) != steps_gcode.end()) {
            // These options only affect G-code export or they are just notes without influence on the generated G-code,
            // so there is nothing to invalidate.
            steps.emplace_back(psGCodeExport);
        } else if (steps_ignore.find(opt_key) != steps_ignore.end()) {
            // These steps have no influence on the G-code whatsoever. Just ignore them.
        } else if (
               opt_key == "skirt_loops"
            || opt_key == "skirt_speed"
            || opt_key == "skirt_height"
            || opt_key == "draft_shield"
            || opt_key == "skirt_distance"
            || opt_key == "ooze_prevention"
            || opt_key == "wipe_tower_x"
            || opt_key == "wipe_tower_y"
            || opt_key == "wipe_tower_rotation_angle") {
            steps.emplace_back(psSkirtBrim);
        } else if (
               opt_key == "initial_layer_print_height"
            || opt_key == "nozzle_diameter"
            || opt_key == "filament_shrink"
            || opt_key == "resolution"
            // Spiral Vase forces different kind of slicing than the normal model:
            // In Spiral Vase mode, holes are closed and only the largest area contour is kept at each layer.
            // Therefore toggling the Spiral Vase on / off requires complete reslicing.
            || opt_key == "spiral_mode") {
            osteps.emplace_back(posSlice);
        } else if (
               opt_key == "print_sequence"
            || opt_key == "filament_type"
            || opt_key == "chamber_temperature"
            || opt_key == "nozzle_temperature_initial_layer"
            || opt_key == "filament_minimal_purge_on_wipe_tower"
            || opt_key == "filament_max_volumetric_speed"
            || opt_key == "gcode_flavor"
            || opt_key == "single_extruder_multi_material"
            || opt_key == "nozzle_temperature"
            // BBS
            || opt_key == "cool_plate_temp"
            || opt_key == "eng_plate_temp"
            || opt_key == "hot_plate_temp"
            || opt_key == "textured_plate_temp"
            || opt_key == "enable_prime_tower"
            || opt_key == "prime_tower_width"
            || opt_key == "prime_tower_brim_width"
            //|| opt_key == "wipe_tower_bridging"
            || opt_key == "wipe_tower_no_sparse_layers"
            || opt_key == "flush_volumes_matrix"
            || opt_key == "prime_volume"
            || opt_key == "flush_into_infill"
            || opt_key == "flush_into_support"
            || opt_key == "initial_layer_infill_speed"
            || opt_key == "travel_speed"
            || opt_key == "travel_speed_z"
            || opt_key == "initial_layer_speed"
            || opt_key == "initial_layer_travel_speed"
            || opt_key == "slow_down_layers") {
            //|| opt_key == "z_offset") {
            steps.emplace_back(psWipeTower);
            steps.emplace_back(psSkirtBrim);
        } else if (opt_key == "filament_soluble"
                || opt_key == "filament_is_support"
                || opt_key == "independent_support_layer_height") {
            steps.emplace_back(psWipeTower);
            // Soluble support interface / non-soluble base interface produces non-soluble interface layers below soluble interface layers.
            // Thus switching between soluble / non-soluble interface layer material may require recalculation of supports.
            //FIXME Killing supports on any change of "filament_soluble" is rough. We should check for each object whether that is necessary.
            osteps.emplace_back(posSupportMaterial);
            osteps.emplace_back(posSimplifySupportPath);
        } else if (
               opt_key == "initial_layer_line_width"
            || opt_key == "min_layer_height"
            || opt_key == "max_layer_height"
            //|| opt_key == "resolution"
            //BBS: when enable arc fitting, we must re-generate perimeter
            || opt_key == "enable_arc_fitting"
            || opt_key == "wall_infill_order") {
            osteps.emplace_back(posPerimeters);
            osteps.emplace_back(posInfill);
            osteps.emplace_back(posSupportMaterial);
      osteps.emplace_back(posSimplifyPath);
            osteps.emplace_back(posSimplifyInfill);
            osteps.emplace_back(posSimplifySupportPath);
            steps.emplace_back(psSkirtBrim);
        }
        else if (opt_key == "z_hop_types") {
            osteps.emplace_back(posDetectOverhangsForLift);
        } else {
            // for legacy, if we can't handle this option let's invalidate all steps
            //FIXME invalidate all steps of all objects as well?
            invalidated |= this->invalidate_all_steps();
            // Continue with the other opt_keys to possibly invalidate any object specific steps.
        }
    }
    sort_remove_duplicates(steps);
    for (PrintStep step : steps)
        invalidated |= this->invalidate_step(step);
    sort_remove_duplicates(osteps);
    for (PrintObjectStep ostep : osteps)
        for (PrintObject *object : m_objects)
            invalidated |= object->invalidate_step(ostep);
    return invalidated;
}
References Slic3r::PrintBaseWithState< PrintStep, psCount >::invalidate_all_steps(), invalidate_step(), m_objects, Slic3r::posDetectOverhangsForLift, Slic3r::posInfill, Slic3r::posPerimeters, Slic3r::posSimplifyInfill, Slic3r::posSimplifyPath, Slic3r::posSimplifySupportPath, Slic3r::posSlice, Slic3r::posSupportMaterial, Slic3r::psGCodeExport, Slic3r::psSkirtBrim, Slic3r::psWipeTower, and Slic3r::sort_remove_duplicates().
invalidate_step()
bool Slic3r::Print::invalidate_step (PrintStep step) protected
{
  bool invalidated = Inherited::invalidate_step(step);
    // Propagate to dependent steps.
    if (step != psGCodeExport)
        invalidated |= Inherited::invalidate_step(psGCodeExport);
    return invalidated;
}
References Slic3r::PrintBaseWithState< PrintStep, psCount >::invalidate_step(), and Slic3r::psGCodeExport.
Referenced by invalidate_state_by_config_options(), and Slic3r::PrintObject::set_instances().
invalidate_steps() [1/2]
bool Slic3r::PrintBaseWithState< PrintStep , COUNT >::invalidate_steps (std::initializer_list< PrintStep > il) inline protected inherited
        { return m_state.invalidate_multiple(il.begin(), il.end(), this->cancel_callback()); }
invalidate_steps() [2/2]
bool Slic3r::PrintBaseWithState< PrintStep , COUNT >::invalidate_steps (StepTypeIterator step_begin, StepTypeIterator step_end) inline protected inherited
        { return m_state.invalidate_multiple(step_begin, step_end, this->cancel_callback()); }
is_BBL_printer() [1/2]
bool & Slic3r::Print::is_BBL_printer () inline
{ return m_isBBLPrinter; }
References m_isBBLPrinter.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GCode::do_export(), Slic3r::GCode::is_BBL_Printer(), Slic3r::BackgroundSlicingProcess::process_fff(), Slic3r::GCode::process_layer(), and validate().
is_BBL_printer() [2/2]
const bool Slic3r::Print::is_BBL_printer () const inline
{ return m_isBBLPrinter; }
References m_isBBLPrinter.
is_step_done() [1/2]
bool Slic3r::Print::is_step_done (PrintObjectStep step) const
{
    if (m_objects.empty())
        return false;
    std::scoped_lock<std::mutex> lock(this->state_mutex());
    for (const PrintObject *object : m_objects)
        if (! object->is_step_done_unguarded(step))
            return false;
    return true;
}
References m_objects, and Slic3r::PrintBase::state_mutex().
is_step_done() [2/2]
bool Slic3r::Print::is_step_done (PrintStep step) const inline
{ return Inherited::is_step_done(step); }
References Slic3r::PrintBaseWithState< PrintStep, psCount >::is_step_done().
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::BackgroundSlicingProcess::apply(), Slic3r::GCode::do_export(), finished(), Slic3r::GUI::Preview::load_print_as_fff(), and Slic3r::GUI::GCodeViewer::load_shells().
is_step_done_unguarded()
bool Slic3r::PrintBaseWithState< PrintStep , COUNT >::is_step_done_unguarded (PrintStep step) const inline protected inherited
{ return m_state.is_done_unguarded(step); }
is_step_started_unguarded()
bool Slic3r::PrintBaseWithState< PrintStep , COUNT >::is_step_started_unguarded (PrintStep step) const inline protected inherited
{ return m_state.is_started_unguarded(step); }
is_support_used()
bool Slic3r::Print::is_support_used () const inline
{return m_support_used;}
References m_support_used.
layers_sorted_for_object()
std::vector< size_t > Slic3r::Print::layers_sorted_for_object (float start, float end, std::vector< LayerPtrs > & layers_of_objects, std::vector< BoundingBox > & boundingBox_for_objects, std::vector< Points > & objects_instances_shift)
{
    std::vector<size_t> idx_of_object_sorted;
    size_t              idx = 0;
    for (const auto &object : m_objects) {
        idx_of_object_sorted.push_back(idx++);
        object->get_certain_layers(start, end, layers_of_objects, boundingBox_for_objects);
    }
    std::sort(idx_of_object_sorted.begin(), idx_of_object_sorted.end(),
              [boundingBox_for_objects](auto left, auto right) { return boundingBox_for_objects[left].area() > boundingBox_for_objects[right].area(); });
    objects_instances_shift.clear();
    objects_instances_shift.reserve(m_objects.size());
    for (const auto& object : m_objects)
        objects_instances_shift.emplace_back(object->get_instances_shift_without_plate_offset());
    return idx_of_object_sorted;
};
References end, m_objects, and start.
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
load_cached_data()
int Slic3r::Print::load_cached_data (const std::string & directory) virtual
Reimplemented from Slic3r::PrintBase.
{
    int ret = 0;
    boost::filesystem::path directory_path(directory);
    if (!fs::exists(directory_path)) {
        BOOST_LOG_TRIVIAL(info) << boost::format("directory %1% not exist.")%directory;
        return CLI_IMPORT_CACHE_NOT_FOUND;
    }
    auto find_region = [this](PrintObject* object, size_t config_hash) -> const PrintRegion* {
        int regions_count = object->num_printing_regions();
        for (int index = 0; index < regions_count; index++ )
        {
            const PrintRegion&  print_region = object->printing_region(index);
            if (print_region.config_hash() == config_hash ) {
                return &print_region;
            }
        }
        return NULL;
    };
    int count = 0;
    std::vector<std::pair<std::string, PrintObject*>> object_filenames;
    for (PrintObject *obj : m_objects) {
        const ModelObject* model_obj = obj->model_object();
        const PrintInstance &print_instance = obj->instances()[0];
        const ModelInstance *model_instance = print_instance.model_instance;
        obj->clear_layers();
        obj->clear_support_layers();
        int identify_id = model_instance->loaded_id;
        if (identify_id <= 0) {
            //for old 3mf
            identify_id = model_instance->id().id;
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": object %1%'s loaded_id is 0, need to use the instance_id %2%")%model_obj->name %identify_id;
            //continue;
        }
        std::string file_name = directory +"/obj_"+std::to_string(identify_id)+".json";
        if (!fs::exists(file_name)) {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(": file %1% not exist, maybe a shared object, skip it")%file_name;
            continue;
        }
        object_filenames.push_back({file_name, obj});
    }
    boost::mutex mutex;
    std::vector<json> object_jsons(object_filenames.size());
    tbb::parallel_for(
        tbb::blocked_range<size_t>(0, object_filenames.size()),
        [object_filenames, &ret, &object_jsons, &mutex](const tbb::blocked_range<size_t>& filename_range) {
            for (size_t filename_index = filename_range.begin(); filename_index < filename_range.end(); ++ filename_index) {
                try {
                    json root_json;
                    boost::nowide::ifstream ifs(object_filenames[filename_index].first);
                    ifs >> root_json;
                    object_jsons[filename_index] = std::move(root_json);
                }
                catch(std::exception &err) {
                    BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": load from "<<object_filenames[filename_index].first<<" got a generic exception, reason = " << err.what();
                    boost::unique_lock l(mutex);
                    ret = CLI_IMPORT_CACHE_LOAD_FAILED;
                }
            }
        }
    );
    if (ret) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< boost::format(": load json failed.");
        return ret;
    }
    for (int obj_index = 0; obj_index < object_jsons.size(); obj_index++) {
        json& root_json = object_jsons[obj_index];
        PrintObject *obj = object_filenames[obj_index].second;
        try {
            //boost::nowide::ifstream ifs(file_name);
            //ifs >> root_json;
            std::string name = root_json.at(JSON_OBJECT_NAME);
            int identify_id = root_json.at(JSON_IDENTIFY_ID);
            int layer_count = 0, support_layer_count = 0, firstlayer_group_count = 0;
            layer_count = root_json[JSON_LAYERS].size();
            support_layer_count = root_json[JSON_SUPPORT_LAYERS].size();
            firstlayer_group_count = root_json[JSON_FIRSTLAYER_GROUPS].size();
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(":will load %1%, identify_id %2%, layer_count %3%, support_layer_count %4%, firstlayer_group_count %5%")
                %name %identify_id %layer_count %support_layer_count %firstlayer_group_count;
            Layer* previous_layer = NULL;
            //create layer and layer regions
            for (int index = 0; index < layer_count; index++)
            {
                json& layer_json = root_json[JSON_LAYERS][index];
                Layer* new_layer = obj->add_layer(layer_json[JSON_LAYER_ID], layer_json[JSON_LAYER_HEIGHT], layer_json[JSON_LAYER_PRINT_Z], layer_json[JSON_LAYER_SLICE_Z]);
                if (!new_layer) {
                    BOOST_LOG_TRIVIAL(error) <<__FUNCTION__<< boost::format(":create_layer failed, out of memory");
                    return CLI_OUT_OF_MEMORY;
                }
                if (previous_layer) {
                    previous_layer->upper_layer = new_layer;
                    new_layer->lower_layer = previous_layer;
                }
                previous_layer = new_layer;
                //layer regions
                int layer_regions_count = layer_json[JSON_LAYER_REGIONS].size();
                for (int region_index = 0; region_index < layer_regions_count; region_index++)
                {
                    json& region_json = layer_json[JSON_LAYER_REGIONS][region_index];
                    size_t config_hash = region_json[JSON_LAYER_REGION_CONFIG_HASH];
                    const PrintRegion *print_region = find_region(obj, config_hash);
                    if (!print_region){
                        BOOST_LOG_TRIVIAL(error) <<__FUNCTION__<< boost::format(":can not find print region of object %1%, layer %2%, print_z %3%, layer_region %4%")
                            %name % index %new_layer->print_z %region_index;
                        //delete new_layer;
                        return CLI_IMPORT_CACHE_DATA_CAN_NOT_USE;
                    }
                    new_layer->add_region(print_region);
                }
            }
            //load the layer data parallel
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(": load the layers in parallel");
            tbb::parallel_for(
                tbb::blocked_range<size_t>(0, obj->layer_count()),
                [&root_json, &obj](const tbb::blocked_range<size_t>& layer_range) {
                    for (size_t layer_index = layer_range.begin(); layer_index < layer_range.end(); ++ layer_index) {
                        const json& layer_json = root_json[JSON_LAYERS][layer_index];
                        Layer* layer = obj->get_layer(layer_index);
                        extract_layer(layer_json, *layer);
                    }
                }
            );
            //support layers
            Layer* previous_support_layer = NULL;
            //create support_layers
            for (int index = 0; index < support_layer_count; index++)
            {
                json& layer_json = root_json[JSON_SUPPORT_LAYERS][index];
                SupportLayer* new_support_layer = obj->add_support_layer(layer_json[JSON_LAYER_ID], layer_json[JSON_SUPPORT_LAYER_INTERFACE_ID], layer_json[JSON_LAYER_HEIGHT], layer_json[JSON_LAYER_PRINT_Z]);
                if (!new_support_layer) {
                    BOOST_LOG_TRIVIAL(error) <<__FUNCTION__<< boost::format(":add_support_layer failed, out of memory");
                    return CLI_OUT_OF_MEMORY;
                }
                if (previous_support_layer) {
                    previous_support_layer->upper_layer = new_support_layer;
                    new_support_layer->lower_layer = previous_support_layer;
                }
                previous_support_layer = new_support_layer;
            }
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": finished load layers, start to load support_layers.");
            tbb::parallel_for(
                tbb::blocked_range<size_t>(0, obj->support_layer_count()),
                [&root_json, &obj](const tbb::blocked_range<size_t>& support_layer_range) {
                    for (size_t layer_index = support_layer_range.begin(); layer_index < support_layer_range.end(); ++ layer_index) {
                        const json& layer_json = root_json[JSON_SUPPORT_LAYERS][layer_index];
                        SupportLayer* support_layer = obj->get_support_layer(layer_index);
                        extract_support_layer(layer_json, *support_layer);
                    }
                }
            );
            //load first group volumes
            std::vector<groupedVolumeSlices>& firstlayer_objgroups = obj->firstLayerObjGroupsMod();
            for (int index = 0; index < firstlayer_group_count; index++)
            {
                json& firstlayer_group_json = root_json[JSON_FIRSTLAYER_GROUPS][index];
                groupedVolumeSlices firstlayer_group = firstlayer_group_json;
                //convert the id
                for (ObjectID& obj_id : firstlayer_group.volume_ids)
                {
                    ModelVolume* currentModelVolumePtr = nullptr;
                    ModelVolumePtrs& volumes_ptr = obj->model_object()->volumes;
                    size_t volume_count = volumes_ptr.size();
                    if (obj_id.id < volume_count) {
                        currentModelVolumePtr = volumes_ptr[obj_id.id];
                        obj_id = currentModelVolumePtr->id();
                    }
                    else {
                        BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< boost::format(": can not find volume_id %1% from object file %2% in firstlayer groups, volume_count %3%!")
                            %obj_id.id %object_filenames[obj_index].first %volume_count;
                        return CLI_IMPORT_CACHE_LOAD_FAILED;
                    }
                }
                firstlayer_objgroups.push_back(std::move(firstlayer_group));
            }
            count ++;
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": load object %1% from %2% successfully.")%count%object_filenames[obj_index].first;
        }
        catch(nlohmann::detail::parse_error &err) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": parse "<<object_filenames[obj_index].first<<" got a nlohmann::detail::parse_error, reason = " << err.what();
            return CLI_IMPORT_CACHE_LOAD_FAILED;
        }
        catch(std::exception &err) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__<< ": load from "<<object_filenames[obj_index].first<<" got a generic exception, reason = " << err.what();
            ret = CLI_IMPORT_CACHE_LOAD_FAILED;
        }
    }
    object_jsons.clear();
    object_filenames.clear();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<< boost::format(": total printobject count %1%, loaded %2%, ret=%3%")%m_objects.size() %count %ret;
    return ret;
}
References CLI_IMPORT_CACHE_NOT_FOUND, Slic3r::PrintRegion::config_hash(), count, Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), Slic3r::ModelInstance::loaded_id, Slic3r::PrintInstance::model_instance, Slic3r::ModelObject::name, and NULL.
make_try_cancel()
PrintTryCancel Slic3r::PrintBase::make_try_cancel () const inline protected inherited
{ return PrintTryCancel(this); }
References Slic3r::PrintBase::PrintTryCancel.
max_allowed_layer_height()
double Slic3r::Print::max_allowed_layer_height () const
{
    double nozzle_diameter_max = 0.;
    for (unsigned int extruder_id : this->extruders())
        nozzle_diameter_max = std::max(nozzle_diameter_max, m_config.nozzle_diameter.get_at(extruder_id));
    return nozzle_diameter_max;
}
References extruders(), and m_config.
model()
const Model & Slic3r::PrintBase::model () const inline inherited
{ return m_model; }
References Slic3r::PrintBase::m_model.
Referenced by Slic3r::ToolOrdering::ToolOrdering(), Slic3r::GUI::Plater::priv::actualize_object_warnings(), Slic3r::SLAPrint::apply(), Slic3r::ToolOrdering::assign_custom_gcodes(), Slic3r::GUI::GLCanvas3D::reload_scene(), sequential_print_clearance_valid(), and Slic3r::sort_object_instances_by_model_order().
num_object_instances()
unsigned int Slic3r::Print::num_object_instances () const
{
  unsigned int instances = 0;
    for (const PrintObject *print_object : m_objects)
        instances += (unsigned int)print_object->instances().size();
    return instances;
}
References m_objects.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::sort_object_instances_by_model_order().
num_print_regions()
size_t Slic3r::Print::num_print_regions () const throw () inline
{ return m_print_regions.size(); }
References m_print_regions.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::GCode::process_layer().
object_extruders()
std::vector< unsigned int > Slic3r::Print::object_extruders () const
{
    std::vector<unsigned int> extruders;
    extruders.reserve(m_print_regions.size() * m_objects.size() * 3);
    // BBS
#if 0
    for (const PrintObject *object : m_objects)
    for (const PrintRegion &region : object->all_regions())
          region.collect_object_printing_extruders(*this, extruders);
#else
    for (const PrintObject* object : m_objects) {
        const ModelObject* mo = object->model_object();
        for (const ModelVolume* mv : mo->volumes) {
            std::vector<int> volume_extruders = mv->get_extruders();
            for (int extruder : volume_extruders) {
                assert(extruder > 0);
                extruders.push_back(extruder - 1);
            }
        }
        // layer range
        for (auto layer_range : mo->layer_config_ranges) {
            if (layer_range.second.has("extruder")) {
                //BBS: actually when user doesn't change filament by height range(value is default 0), height range should not save key "extruder".
                //Don't know why height range always save key "extruder" because of no change(should only save difference)...
                //Add protection here to avoid overflow
                auto value = layer_range.second.option("extruder")->getInt();
                if (value > 0)
                    extruders.push_back(value - 1);
            }
        }
    }
#endif
    sort_remove_duplicates(extruders);
    return extruders;
}
References extruders(), Slic3r::ModelObject::layer_config_ranges, m_objects, m_print_regions, Slic3r::sort_remove_duplicates(), and Slic3r::ModelObject::volumes.
Referenced by Slic3r::ToolOrdering::ToolOrdering(), Slic3r::ToolOrdering::assign_custom_gcodes(), extruders(), and support_material_extruders().
objects()
ConstPrintObjectPtrsAdaptor Slic3r::Print::objects () const inline
{ return ConstPrintObjectPtrsAdaptor(&m_objects); }
References m_objects.
Referenced by Slic3r::ToolOrdering::ToolOrdering(), Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::GUI::GLCanvas3D::_render_overlays(), Slic3r::chain_print_object_instances(), Slic3r::GCode::collect_layers_to_print(), Slic3r::TreeSupport::draw_circles(), Slic3r::WipingExtrusions::ensure_perimeters_infills_order(), Slic3r::ToolOrdering::generate_first_layer_tool_order(), Slic3r::get_boundary_external(), Slic3r::get_path_of_change_filament(), Slic3r::get_perimeter_spacing_external(), Slic3r::get_print_bottom_layers_expolygons(), Slic3r::get_top_level_objects_with_brim(), Slic3r::getObjectExtruderMap(), Slic3r::SeamPlacer::init(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::inner_brim_area(), Slic3r::GUI::IMSlider::IsNewPrint(), Slic3r::GUI::Preview::load_print_as_fff(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::make_inner_brim(), Slic3r::make_inner_brim(), Slic3r::WipingExtrusions::mark_wiping_extrusions(), Slic3r::GCode::process_layer(), Slic3r::CLI::run(), sequential_print_clearance_valid(), Slic3r::GCode::set_object_info(), Slic3r::sort_object_instances_by_model_order(), Slic3r::top_level_outer_brim_area(), and Slic3r::GUI::Preview::update_layers_slider().
objects_mutable()
PrintObjectPtrs & Slic3r::Print::objects_mutable () inline
{ return m_objects; }
References m_objects.
output_filename() [1/2]
std::string Slic3r::Print::output_filename (const std::string & filename_base = std::string()) const override virtual
Implements Slic3r::PrintBase.
{
    // Set the placeholders for the data know first after the G-code export is finished.
    // These values will be just propagated into the output file name.
    DynamicConfig config = this->finished() ? this->print_statistics().config() : this->print_statistics().placeholders();
    config.set_key_value("num_filaments", new ConfigOptionInt((int)m_config.nozzle_diameter.size()));
    config.set_key_value("plate_name", new ConfigOptionString(get_plate_name()));
    return this->PrintBase::output_filename(m_config.filename_format.value, ".gcode", filename_base, &config);
}
References Slic3r::DynamicConfig::set_key_value().
output_filename() [2/2]
std::string Slic3r::PrintBase::output_filename (const std::string & format, const std::string & default_ext, const std::string & filename_base, const DynamicConfig * config_override = nullptr) const protected inherited
{
    DynamicConfig cfg;
    if (config_override != nullptr)
      cfg = *config_override;
    cfg.set_key_value("version", new ConfigOptionString(std::string(SoftFever_VERSION)));
    PlaceholderParser::update_timestamp(cfg);
    this->update_object_placeholders(cfg, default_ext);
    if (! filename_base.empty()) {
    cfg.set_key_value("input_filename", new ConfigOptionString(filename_base + default_ext));
    cfg.set_key_value("input_filename_base", new ConfigOptionString(filename_base));
    }
    try {
    boost::filesystem::path filename = format.empty() ?
      cfg.opt_string("input_filename_base") + default_ext :
      this->placeholder_parser().process(format, 0, &cfg);
        if (filename.extension().empty())
            filename = boost::filesystem::change_extension(filename, default_ext);
        return filename.string();
    } catch (std::runtime_error &err) {
        throw Slic3r::PlaceholderParserError(L("Failed processing of the filename_format template.") + "\n" + err.what());
    }
}
References Slic3r::format(), L, Slic3r::DynamicConfig::opt_string(), Slic3r::PrintBase::placeholder_parser(), Slic3r::PlaceholderParser::process(), Slic3r::DynamicConfig::set_key_value(), Slic3r::PrintBase::update_object_placeholders(), and Slic3r::PlaceholderParser::update_timestamp().
output_filepath()
std::string Slic3r::PrintBase::output_filepath (const std::string & path, const std::string & filename_base = std::string()) const inherited
{
    // if we were supplied no path, generate an automatic one based on our first object's input file
    if (path.empty())
        // get the first input file name
        return (boost::filesystem::path(m_model.propose_export_file_name_and_path()).parent_path() / this->output_filename(filename_base)).make_preferred().string();
    // if we were supplied a directory, use it and append our automatically generated filename
    boost::filesystem::path p(path);
    if (boost::filesystem::is_directory(p))
        return (p / this->output_filename(filename_base)).make_preferred().string();
    // if we were supplied a file which is not a directory, use it
    return path;
}
References Slic3r::PrintBase::m_model, Slic3r::PrintBase::output_filename(), and Slic3r::Model::propose_export_file_name_and_path().
Referenced by Slic3r::BackgroundSlicingProcess::output_filepath_for_project().
placeholder_parser()
const PlaceholderParser & Slic3r::PrintBase::placeholder_parser () const inline inherited
{ return m_placeholder_parser; }
References Slic3r::PrintBase::m_placeholder_parser.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::PrintBase::output_filename().
print_object_ids()
std::vector< ObjectID > Slic3r::Print::print_object_ids () const override virtual
Implements Slic3r::PrintBase.
{
    std::vector<ObjectID> out;
    // Reserve one more for the caller to append the ID of the Print itself.
    out.reserve(m_objects.size() + 1);
    for (const PrintObject *print_object : m_objects)
        out.emplace_back(print_object->id());
    return out;
}
References m_objects, and out.
Referenced by Slic3r::make_brim().
print_regions_mutable()
PrintRegionPtrs & Slic3r::Print::print_regions_mutable () inline
{ return m_print_regions; }
References m_print_regions.
print_statistics() [1/2]
PrintStatistics & Slic3r::Print::print_statistics () inline
{ return m_print_statistics; }
References m_print_statistics.
print_statistics() [2/2]
const PrintStatistics & Slic3r::Print::print_statistics () const inline
{ return m_print_statistics; }
References m_print_statistics.
Referenced by Slic3r::BackgroundSlicingProcess::finalize_gcode(), Slic3r::BackgroundSlicingProcess::prepare_upload(), and Slic3r::GUI::SelectMachineDialog::set_default().
process()
void Slic3r::Print::process (bool use_cache = false) override virtual
Implements Slic3r::PrintBase.
{
    name_tbb_thread_pool_threads_set_locale();
    //compute the PrintObject with the same geometries
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": this=%1%, enter, use_cache=%2%, object size=%3%")%this%use_cache%m_objects.size();
    if (m_objects.empty())
        return;
    for (PrintObject *obj : m_objects)
        obj->clear_shared_object();
    //add the print_object share check logic
    auto is_print_object_the_same = [this](const PrintObject* object1, const PrintObject* object2) -> bool{
        if (object1->trafo().matrix() != object2->trafo().matrix())
            return false;
        const ModelObject* model_obj1 = object1->model_object();
        const ModelObject* model_obj2 = object2->model_object();
        if (model_obj1->volumes.size() != model_obj2->volumes.size())
            return false;
        bool has_extruder1 = model_obj1->config.has("extruder");
        bool has_extruder2 = model_obj2->config.has("extruder");
        if ((has_extruder1 != has_extruder2)
            || (has_extruder1 && model_obj1->config.extruder() != model_obj2->config.extruder()))
            return false;
        for (int index = 0; index < model_obj1->volumes.size(); index++) {
            const ModelVolume &model_volume1 = *model_obj1->volumes[index];
            const ModelVolume &model_volume2 = *model_obj2->volumes[index];
            if (model_volume1.type() != model_volume2.type())
                return false;
            if (model_volume1.mesh_ptr() != model_volume2.mesh_ptr())
                return false;
            if (!(model_volume1.get_transformation() == model_volume2.get_transformation()))
                return false;
            has_extruder1 = model_volume1.config.has("extruder");
            has_extruder2 = model_volume2.config.has("extruder");
            if ((has_extruder1 != has_extruder2)
                || (has_extruder1 && model_volume1.config.extruder() != model_volume2.config.extruder()))
                return false;
            if (!model_volume1.supported_facets.equals(model_volume2.supported_facets))
                return false;
            if (!model_volume1.seam_facets.equals(model_volume2.seam_facets))
                return false;
            if (!model_volume1.mmu_segmentation_facets.equals(model_volume2.mmu_segmentation_facets))
                return false;
            if (model_volume1.config.get() != model_volume2.config.get())
                return false;
        }
        //if (!object1->config().equals(object2->config()))
        //    return false;
        if (model_obj1->config.get() != model_obj2->config.get())
            return false;
        return true;
    };
    int object_count = m_objects.size();
    std::set<PrintObject*> need_slicing_objects;
    std::set<PrintObject*> re_slicing_objects;
    if (!use_cache) {
        for (int index = 0; index < object_count; index++)
        {
            PrintObject *obj =  m_objects[index];
            for (PrintObject *slicing_obj : need_slicing_objects)
            {
                if (is_print_object_the_same(obj, slicing_obj)) {
                    obj->set_shared_object(slicing_obj);
                    break;
                }
            }
            if (!obj->get_shared_object())
                need_slicing_objects.insert(obj);
        }
    }
    else {
        for (int index = 0; index < object_count; index++)
        {
            PrintObject *obj =  m_objects[index];
            if (obj->layer_count() > 0)
                need_slicing_objects.insert(obj);
        }
        for (int index = 0; index < object_count; index++)
        {
            PrintObject *obj =  m_objects[index];
            bool found_shared = false;
            if (need_slicing_objects.find(obj) == need_slicing_objects.end()) {
                for (PrintObject *slicing_obj : need_slicing_objects)
                {
                    if (is_print_object_the_same(obj, slicing_obj)) {
                        obj->set_shared_object(slicing_obj);
                        found_shared = true;
                        break;
                    }
                }
                if (!found_shared) {
                    BOOST_LOG_TRIVIAL(warning) << boost::format("Also can not find the shared object, identify_id %1%, maybe shared object is skipped")%obj->model_object()->instances[0]->loaded_id;
                    //throw Slic3r::SlicingError("Can not find the cached data.");
                    //don't report errot, set use_cache to false, and reslice these objects
                    need_slicing_objects.insert(obj);
                    re_slicing_objects.insert(obj);
                    //use_cache = false;
                }
            }
        }
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": total object counts %1% in current print, need to slice %2%")%m_objects.size()%need_slicing_objects.size();
    BOOST_LOG_TRIVIAL(info) << "Starting the slicing process." << log_memory_info();
    if (!use_cache) {
        for (PrintObject *obj : m_objects) {
            if (need_slicing_objects.count(obj) != 0) {
                obj->make_perimeters();
            }
            else {
                if (obj->set_started(posSlice))
                    obj->set_done(posSlice);
                if (obj->set_started(posPerimeters))
                    obj->set_done(posPerimeters);
            }
        }
        for (PrintObject *obj : m_objects) {
            if (need_slicing_objects.count(obj) != 0) {
                obj->infill();
            }
            else {
                if (obj->set_started(posPrepareInfill))
                    obj->set_done(posPrepareInfill);
                if (obj->set_started(posInfill))
                    obj->set_done(posInfill);
            }
        }
        for (PrintObject *obj : m_objects) {
            if (need_slicing_objects.count(obj) != 0) {
                obj->ironing();
            }
            else {
                if (obj->set_started(posIroning))
                    obj->set_done(posIroning);
            }
        }
        tbb::parallel_for(tbb::blocked_range<int>(0, int(m_objects.size())),
            [this, need_slicing_objects](const tbb::blocked_range<int>& range) {
                for (int i = range.begin(); i < range.end(); i++) {
                    PrintObject* obj = m_objects[i];
                    if (need_slicing_objects.count(obj) != 0) {
                        obj->generate_support_material();
                    }
                    else {
                        if (obj->set_started(posSupportMaterial))
                            obj->set_done(posSupportMaterial);
                    }
                }
            }
        );
    }
    else {
        for (PrintObject *obj : m_objects) {
            if (re_slicing_objects.count(obj) == 0) {
                if (obj->set_started(posSlice))
                    obj->set_done(posSlice);
                if (obj->set_started(posPerimeters))
                    obj->set_done(posPerimeters);
                if (obj->set_started(posPrepareInfill))
                    obj->set_done(posPrepareInfill);
                if (obj->set_started(posInfill))
                    obj->set_done(posInfill);
                if (obj->set_started(posIroning))
                    obj->set_done(posIroning);
                if (obj->set_started(posSupportMaterial))
                    obj->set_done(posSupportMaterial);
            }
            else {
                obj->make_perimeters();
                obj->infill();
                obj->ironing();
                obj->generate_support_material();
            }
        }
    }
    for (PrintObject *obj : m_objects)
    {
        if (need_slicing_objects.count(obj) == 0)
            obj->copy_layers_from_shared_object();
    }
    if (this->set_started(psWipeTower)) {
        m_wipe_tower_data.clear();
        m_tool_ordering.clear();
        if (this->has_wipe_tower()) {
            this->_make_wipe_tower();
        } else if (this->config().print_sequence != PrintSequence::ByObject) {
          // Initialize the tool ordering, so it could be used by the G-code preview slider for planning tool changes and filament switches.
          m_tool_ordering = ToolOrdering(*this, -1, false);
            if (m_tool_ordering.empty() || m_tool_ordering.last_extruder() == unsigned(-1))
                throw Slic3r::SlicingError("The print is empty. The model is not printable with current print settings.");
        }
        this->set_done(psWipeTower);
    }
    if (this->set_started(psSkirtBrim)) {
        this->set_status(70, L("Generating skirt & brim"));
        m_skirt.clear();
        m_skirt_convex_hull.clear();
        m_first_layer_convex_hull.points.clear();
        const bool draft_shield = config().draft_shield != dsDisabled;
        if (this->has_skirt() && draft_shield) {
            // In case that draft shield is active, generate skirt first so brim
            // can be trimmed to make room for it.
            _make_skirt();
        }
        //BBS: get the objects' indices when GCodes are generated
        ToolOrdering tool_ordering;
        unsigned int initial_extruder_id = (unsigned int)-1;
        unsigned int final_extruder_id = (unsigned int)-1;
        bool         has_wipe_tower = false;
        std::vector<const PrintInstance*>           print_object_instances_ordering;
        std::vector<const PrintInstance*>::const_iterator   print_object_instance_sequential_active;
        std::vector<std::pair<coordf_t, std::vector<GCode::LayerToPrint>>> layers_to_print = GCode::collect_layers_to_print(*this);
        std::vector<unsigned int> printExtruders;
        if (this->config().print_sequence == PrintSequence::ByObject) {
            // Order object instances for sequential print.
            print_object_instances_ordering = sort_object_instances_by_model_order(*this);
            //        print_object_instances_ordering = sort_object_instances_by_max_z(print);
            print_object_instance_sequential_active = print_object_instances_ordering.begin();
            for (; print_object_instance_sequential_active != print_object_instances_ordering.end(); ++print_object_instance_sequential_active) {
                tool_ordering = ToolOrdering(*(*print_object_instance_sequential_active)->print_object, initial_extruder_id);
                if ((initial_extruder_id = tool_ordering.first_extruder()) != static_cast<unsigned int>(-1)) {
                    append(printExtruders, tool_ordering.tools_for_layer(layers_to_print.front().first).extruders);
                }
            }
        }
        else {
            tool_ordering = this->tool_ordering();
            tool_ordering.assign_custom_gcodes(*this);
            has_wipe_tower = this->has_wipe_tower() && tool_ordering.has_wipe_tower();
            //BBS: have no single_extruder_multi_material_priming
#if 0
            initial_extruder_id = (has_wipe_tower && !this->config().single_extruder_multi_material_priming) ?
                // The priming towers will be skipped.
                tool_ordering.all_extruders().back() :
                // Don't skip the priming towers.
                tool_ordering.first_extruder();
#endif
            initial_extruder_id = tool_ordering.first_extruder();
            print_object_instances_ordering = chain_print_object_instances(*this);
            append(printExtruders, tool_ordering.tools_for_layer(layers_to_print.front().first).extruders);
        }
        auto objectExtruderMap = getObjectExtruderMap(*this);
        std::vector<std::pair<ObjectID, unsigned int>> objPrintVec;
        for (const PrintInstance* instance : print_object_instances_ordering) {
            const ObjectID& print_object_ID = instance->print_object->id();
            bool existObject = false;
            for (auto& objIDPair : objPrintVec) {
                if (print_object_ID == objIDPair.first) existObject = true;
            }
            if (!existObject && objectExtruderMap.find(print_object_ID) != objectExtruderMap.end())
                objPrintVec.push_back(std::make_pair(print_object_ID, objectExtruderMap.at(print_object_ID)));
        }
        // BBS: m_brimMap and m_supportBrimMap are used instead of m_brim to generate brim of objs and supports seperately
        m_brimMap.clear();
        m_supportBrimMap.clear();
        m_first_layer_convex_hull.points.clear();
        if (this->has_brim()) {
            Polygons islands_area;
            make_brim(*this, this->make_try_cancel(), islands_area, m_brimMap,
                m_supportBrimMap, objPrintVec, printExtruders);
            for (Polygon& poly_ex : islands_area)
                poly_ex.douglas_peucker(SCALED_RESOLUTION);
            for (Polygon &poly : union_(this->first_layer_islands(), islands_area))
                append(m_first_layer_convex_hull.points, std::move(poly.points));
        }
        if (has_skirt() && ! draft_shield) {
            // In case that draft shield is NOT active, generate skirt now.
            // It will be placed around the brim, so brim has to be ready.
            assert(m_skirt.empty());
            _make_skirt();
        }
        this->finalize_first_layer_convex_hull();
        this->set_done(psSkirtBrim);
    }
    //BBS
    for (PrintObject *obj : m_objects) {
        if (((!use_cache)&&(need_slicing_objects.count(obj) != 0))
            || (use_cache &&(re_slicing_objects.count(obj) != 0))){
            obj->simplify_extrusion_path();
        }
        else {
            if (obj->set_started(posSimplifyPath))
                obj->set_done(posSimplifyPath);
            if (obj->set_started(posSimplifyInfill))
                obj->set_done(posSimplifyInfill);
            if (obj->set_started(posSimplifySupportPath))
                obj->set_done(posSimplifySupportPath);
        }
    }
    // BBS
    for (PrintObject* obj : m_objects) {
        if (need_slicing_objects.count(obj) != 0) {
            obj->detect_overhangs_for_lift();
        }
        else {
            obj->copy_layers_overhang_from_shared_object();
            if (obj->set_started(posDetectOverhangsForLift))
                obj->set_done(posDetectOverhangsForLift);
        }
    }
    // BBS
    if(!m_no_check)
    {
        using Clock                 = std::chrono::high_resolution_clock;
        auto            startTime   = Clock::now();
        std::optional<const FakeWipeTower *> wipe_tower_opt = {};
        if (this->has_wipe_tower()) {
            m_fake_wipe_tower.set_pos({m_config.wipe_tower_x.get_at(m_plate_index), m_config.wipe_tower_y.get_at(m_plate_index)});
            wipe_tower_opt = std::make_optional<const FakeWipeTower *>(&m_fake_wipe_tower);
        }
        auto            conflictRes = ConflictChecker::find_inter_of_lines_in_diff_objs(m_objects, wipe_tower_opt);
        auto            endTime     = Clock::now();
        volatile double seconds     = std::chrono::duration_cast<std::chrono::milliseconds>(endTime - startTime).count() / (double) 1000;
        BOOST_LOG_TRIVIAL(info) << "gcode path conflicts check takes " << seconds << " secs.";
        m_conflict_result = conflictRes;
        if (conflictRes.has_value()) {
            BOOST_LOG_TRIVIAL(error) << boost::format("gcode path conflicts found between %1% and %2%")%conflictRes.value()._objName1 %conflictRes.value()._objName2;
        }
    }
    BOOST_LOG_TRIVIAL(info) << "Slicing process finished." << log_memory_info();
}
References Slic3r::ModelObject::config, Slic3r::ModelVolume::config, Slic3r::FacetsAnnotation::equals(), Slic3r::ModelConfig::extruder(), Slic3r::ModelConfig::get(), Slic3r::PrintObject::get_shared_object(), Slic3r::ModelVolume::get_transformation(), Slic3r::ModelConfig::has(), Slic3r::ModelObject::instances, Slic3r::PrintObject::layer_count(), Slic3r::log_memory_info(), m_objects, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::ModelVolume::mesh_ptr(), Slic3r::ModelVolume::mmu_segmentation_facets, Slic3r::PrintObjectBase::model_object(), Slic3r::name_tbb_thread_pool_threads_set_locale(), Slic3r::posInfill, Slic3r::posIroning, Slic3r::posPerimeters, Slic3r::posPrepareInfill, Slic3r::posSlice, Slic3r::range(), Slic3r::ModelVolume::seam_facets, Slic3r::PrintObject::set_shared_object(), Slic3r::ModelVolume::supported_facets, Slic3r::PrintObject::trafo(), Slic3r::ModelVolume::type(), and Slic3r::ModelObject::volumes.
restart()
void Slic3r::PrintBase::restart () inline inherited
{ m_cancel_status = NOT_CANCELED; }
References Slic3r::PrintBase::m_cancel_status, and Slic3r::PrintBase::NOT_CANCELED.
Referenced by Slic3r::PrintBase::PrintBase(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), and Slic3r::BackgroundSlicingProcess::thread_proc().
sequential_print_clearance_valid()
StringObjectException Slic3r::Print::sequential_print_clearance_valid (const Print & print, Polygons * polygons = nullptr, std::vector< std::pair< Polygon, float > > * height_polygons = nullptr) static
{
    StringObjectException single_object_exception;
    auto print_config = print.config();
    Pointfs excluse_area_points = print_config.bed_exclude_area.values;
    Polygons exclude_polys;
    Polygon exclude_poly;
    const Vec3d print_origin = print.get_plate_origin();
    for (int i = 0; i < excluse_area_points.size(); i++) {
        auto pt = excluse_area_points[i];
        exclude_poly.points.emplace_back(scale_(pt.x() + print_origin.x()), scale_(pt.y() + print_origin.y()));
        if (i % 4 == 3) {  // exclude areas are always rectangle
            exclude_polys.push_back(exclude_poly);
            exclude_poly.points.clear();
        }
    }
    std::map<ObjectID, Polygon> map_model_object_to_convex_hull;
    struct print_instance_info
    {
        const PrintInstance *print_instance;
        BoundingBox    bounding_box;
        Polygon        hull_polygon;
        int                  object_index;
        double         arrange_score;
        double               height;
    };
    auto find_object_index = [](const Model& model, const ModelObject* obj) {
        for (int index = 0; index < model.objects.size(); index++)
        {
            if (model.objects[index] == obj)
                return index;
        }
        return -1;
    };
    std::vector<struct print_instance_info> print_instance_with_bounding_box;
    {
        // sequential_print_horizontal_clearance_valid
        Polygons convex_hulls_other;
        if (polygons != nullptr)
            polygons->clear();
        std::vector<size_t> intersecting_idxs;
        for (const PrintObject *print_object : print.objects()) {
            assert(! print_object->model_object()->instances.empty());
            assert(! print_object->instances().empty());
            ObjectID model_object_id = print_object->model_object()->id();
            auto it_convex_hull = map_model_object_to_convex_hull.find(model_object_id);
            // Get convex hull of all printable volumes assigned to this print object.
            ModelInstance *model_instance0 = print_object->model_object()->instances.front();
            if (it_convex_hull == map_model_object_to_convex_hull.end()) {
                // Calculate the convex hull of a printable object.
                // Grow convex hull with the clearance margin.
                // FIXME: Arrangement has different parameters for offsetting (jtMiter, limit 2)
                // which causes that the warning will be showed after arrangement with the
                // appropriate object distance. Even if I set this to jtMiter the warning still shows up.
                it_convex_hull = map_model_object_to_convex_hull.emplace_hint(it_convex_hull, model_object_id,
                            print_object->model_object()->convex_hull_2d(Geometry::assemble_transform(
                            { 0.0, 0.0, model_instance0->get_offset().z() }, model_instance0->get_rotation(), model_instance0->get_scaling_factor(), model_instance0->get_mirror())));
            }
            // Make a copy, so it may be rotated for instances.
            Polygon convex_hull0 = it_convex_hull->second;
            const double z_diff = Geometry::rotation_diff_z(model_instance0->get_rotation(), print_object->instances().front().model_instance->get_rotation());
            if (std::abs(z_diff) > EPSILON)
                convex_hull0.rotate(z_diff);
            // Now we check that no instance of convex_hull intersects any of the previously checked object instances.
            for (const PrintInstance &instance : print_object->instances()) {
                Polygon convex_hull_no_offset = convex_hull0, convex_hull;
                auto tmp = offset(convex_hull_no_offset,
                        // Shrink the extruder_clearance_radius a tiny bit, so that if the object arrangement algorithm placed the objects
                        // exactly by satisfying the extruder_clearance_radius, this test will not trigger collision.
                        float(scale_(0.5 * print.config().extruder_clearance_radius.value - EPSILON)),
                        jtRound, scale_(0.1));
                if (!tmp.empty()) { // tmp may be empty due to clipper's bug, see STUDIO-2452
                    convex_hull = tmp.front();
                    // instance.shift is a position of a centered object, while model object may not be centered.
                    // Convert the shift from the PrintObject's coordinates into ModelObject's coordinates by removing the centering offset.
                    convex_hull.translate(instance.shift - print_object->center_offset());
                }
                convex_hull_no_offset.translate(instance.shift - print_object->center_offset());
                //juedge the exclude area
                if (!intersection(exclude_polys, convex_hull_no_offset).empty()) {
                    if (single_object_exception.string.empty()) {
                        single_object_exception.string = (boost::format(L("%1% is too close to exclusion area, there may be collisions when printing.")) %instance.model_instance->get_object()->name).str();
                        single_object_exception.object = instance.model_instance->get_object();
                    }
                    else {
                        single_object_exception.string += "\n"+(boost::format(L("%1% is too close to exclusion area, there may be collisions when printing.")) %instance.model_instance->get_object()->name).str();
                        single_object_exception.object = nullptr;
                    }
                    //if (polygons) {
                    //    intersecting_idxs.emplace_back(convex_hulls_other.size());
                    //}
                }
                // if output needed, collect indices (inside convex_hulls_other) of intersecting hulls
                for (size_t i = 0; i < convex_hulls_other.size(); ++i) {
                    if (! intersection(convex_hulls_other[i], convex_hull).empty()) {
                        bool has_exception = false;
                        if (single_object_exception.string.empty()) {
                            single_object_exception.string = (boost::format(L("%1% is too close to others, and collisions may be caused.")) %instance.model_instance->get_object()->name).str();
                            single_object_exception.object = instance.model_instance->get_object();
                            has_exception                  = true;
                        }
                        else {
                            single_object_exception.string += "\n"+(boost::format(L("%1% is too close to others, and collisions may be caused.")) %instance.model_instance->get_object()->name).str();
                            single_object_exception.object = nullptr;
                            has_exception                  = true;
                        }
                        if (polygons) {
                            intersecting_idxs.emplace_back(i);
                            intersecting_idxs.emplace_back(convex_hulls_other.size());
                        }
                        if (has_exception) break;
                    }
                }
                struct print_instance_info print_info {&instance, convex_hull.bounding_box(), convex_hull};
                print_info.height = instance.print_object->height();
                print_info.object_index = find_object_index(print.model(), print_object->model_object());
                print_instance_with_bounding_box.push_back(std::move(print_info));
                convex_hulls_other.emplace_back(std::move(convex_hull));
            }
        }
        if (!intersecting_idxs.empty()) {
            // use collected indices (inside convex_hulls_other) to update output
            std::sort(intersecting_idxs.begin(), intersecting_idxs.end());
            intersecting_idxs.erase(std::unique(intersecting_idxs.begin(), intersecting_idxs.end()), intersecting_idxs.end());
            for (size_t i : intersecting_idxs) {
                polygons->emplace_back(std::move(convex_hulls_other[i]));
            }
        }
    }
    // calc sort order
    double hc1              = scale_(print.config().extruder_clearance_height_to_lid); // height to lid
    double hc2              = scale_(print.config().extruder_clearance_height_to_rod); // height to rod
    double printable_height = scale_(print.config().printable_height);
#if 0 //do not sort anymore, use the order in object list
    auto bed_points = get_bed_shape(print_config);
    float bed_width = bed_points[1].x() - bed_points[0].x();
    //
    float unsafe_dist = scale_(print_config.extruder_clearance_max_radius.value - print_config.extruder_clearance_radius.value);
    struct VecHash
    {
        size_t operator()(const Vec2i &n1) const
        {
            return std::hash<coord_t>()(int(n1(0) * 100 + 100)) + std::hash<coord_t>()(int(n1(1) * 100 + 100)) * 101;
        }
    };
    std::unordered_set<Vec2i, VecHash> left_right_pair; // pairs in this vector must strictly obey the left-right order
    for (size_t i = 0; i < print_instance_with_bounding_box.size();i++) {
        auto &inst         = print_instance_with_bounding_box[i];
        inst.index         = i;
        Point pt           = inst.bounding_box.center();
        inst.arrange_score = pt.x() / 2 + pt.y(); // we prefer print row-by-row, so cost on x-direction is smaller
    }
    for (size_t i = 0; i < print_instance_with_bounding_box.size(); i++) {
        auto &inst         = print_instance_with_bounding_box[i];
        auto &l            = print_instance_with_bounding_box[i];
        for (size_t j = 0; j < print_instance_with_bounding_box.size(); j++) {
            if (j != i) {
                auto &r        = print_instance_with_bounding_box[j];
                auto ly1       = l.bounding_box.min.y();
                auto ly2       = l.bounding_box.max.y();
                auto ry1       = r.bounding_box.min.y();
                auto ry2       = r.bounding_box.max.y();
                auto lx1       = l.bounding_box.min.x();
                auto rx1       = r.bounding_box.min.x();
                auto lx2       = l.bounding_box.max.x();
                auto rx2       = r.bounding_box.max.x();
                auto inter_min = std::max(ly1, ry1);
                auto inter_max = std::min(ly2, ry2);
                auto inter_y   = inter_max - inter_min;
                // yx
                if (inter_y > scale_(0.5 * print.config().extruder_clearance_radius.value)) {
                    if (std::max(rx1 - lx2, lx1 - rx2) < unsafe_dist) {
                        if (lx1 > rx1) {
                            left_right_pair.insert({j, i});
                            BOOST_LOG_TRIVIAL(debug) << "in-a-row, print_instance " << r.print_instance->model_instance->get_object()->name << "(" << r.arrange_score << ")"
                                                     << " -> " << l.print_instance->model_instance->get_object()->name << "(" << l.arrange_score << ")";
                        } else {
                            left_right_pair.insert({i, j});
                            BOOST_LOG_TRIVIAL(debug) << "in-a-row, print_instance " << l.print_instance->model_instance->get_object()->name << "(" << l.arrange_score << ")"
                                                     << " -> " << r.print_instance->model_instance->get_object()->name << "(" << r.arrange_score << ")";
                        }
                    }
                }
                if (l.height > hc1 && r.height < hc1) {
                    //
                    left_right_pair.insert({j, i});
                    BOOST_LOG_TRIVIAL(debug) << "height>hc1, print_instance " << r.print_instance->model_instance->get_object()->name << "(" << r.arrange_score << ")"
                                             << " -> " << l.print_instance->model_instance->get_object()->name << "(" << l.arrange_score << ")";
                }
                else if (l.height > hc2 && l.height > r.height && l.arrange_score<r.arrange_score) {
                    // r
                    if (l.arrange_score < r.arrange_score)
                        l.arrange_score = r.arrange_score + 10;
                    BOOST_LOG_TRIVIAL(debug) << "height>hc2, print_instance " << inst.print_instance->model_instance->get_object()->name
                                             << ", right=" << r.print_instance->model_instance->get_object()->name << ", l.score: " << l.arrange_score
                                             << ", r.score: " << r.arrange_score;
                }
            }
        }
    }
    //
    // TODO
    for (int k=0;k<5;k++)
    for (auto p : left_right_pair) {
        auto &l = print_instance_with_bounding_box[p(0)];
        auto &r = print_instance_with_bounding_box[p(1)];
        if(r.arrange_score<l.arrange_score)
            r.arrange_score = l.arrange_score + 10;
    }
    BOOST_LOG_TRIVIAL(debug) << "bed width: " << unscale_(bed_width) << ", unsafe_dist:" << unscale_(unsafe_dist) << ", height_to_lid: " << unscale_(hc1) << ", height_to_rod:" << unscale_(hc2) << ", final dependency:";
    for (auto p : left_right_pair) {
        auto &l         = print_instance_with_bounding_box[p(0)];
        auto &r         = print_instance_with_bounding_box[p(1)];
        BOOST_LOG_TRIVIAL(debug) << "print_instance " << I18N::translate(l.print_instance->model_instance->get_object()->name) << "(" << l.arrange_score << ")"
                                 << " -> " << I18N::translate(r.print_instance->model_instance->get_object()->name) << "(" << r.arrange_score << ")";
    }
    // sort the print instance
    std::sort(print_instance_with_bounding_box.begin(), print_instance_with_bounding_box.end(),
        [](print_instance_info& l, print_instance_info& r) {return l.arrange_score < r.arrange_score;});
    for (auto &inst : print_instance_with_bounding_box)
        BOOST_LOG_TRIVIAL(debug) << "after sorting print_instance " << inst.print_instance->model_instance->get_object()->name << ", score: " << inst.arrange_score
                                 << ", height:"<< inst.height;
#else
    // sort the print instance
    std::sort(print_instance_with_bounding_box.begin(), print_instance_with_bounding_box.end(),
        [](print_instance_info& l, print_instance_info& r) {return l.object_index < r.object_index;});
    for (auto &inst : print_instance_with_bounding_box)
        BOOST_LOG_TRIVIAL(debug) << "after sorting print_instance " << inst.print_instance->model_instance->get_object()->name << ", object_index: " << inst.object_index
                                 << ", height:"<< inst.height;
#endif
    // sequential_print_vertical_clearance_valid
    {
        // Ignore the last instance printed.
        //print_instance_with_bounding_box.pop_back();
        /*bool has_interlaced_objects = false;
        for (int k = 0; k < print_instance_count; k++)
        {
            auto inst = print_instance_with_bounding_box[k].print_instance;
            auto bbox = print_instance_with_bounding_box[k].bounding_box;
            auto iy1 = bbox.min.y();
            auto iy2 = bbox.max.y();
            for (int i = 0; i < k; i++)
            {
                auto& p = print_instance_with_bounding_box[i].print_instance;
                auto bbox2 = print_instance_with_bounding_box[i].bounding_box;
                auto py1 = bbox2.min.y();
                auto py2 = bbox2.max.y();
                auto inter_min = std::max(iy1, py1); // min y of intersection
                auto inter_max = std::min(iy2, py2); // max y of intersection. length=max_y-min_y>0 means intersection exists
                if (inter_max - inter_min > 0) {
                    has_interlaced_objects = true;
                    break;
                }
            }
            if (has_interlaced_objects)
                break;
        }*/
        // if objects are not overlapped on y-axis, they will not collide even if they are taller than extruder_clearance_height_to_rod
        int print_instance_count = print_instance_with_bounding_box.size();
        std::map<const PrintInstance*, std::pair<Polygon, float>> too_tall_instances;
        for (int k = 0; k < print_instance_count; k++)
        {
            auto inst = print_instance_with_bounding_box[k].print_instance;
            //
            auto bbox = print_instance_with_bounding_box[k].bounding_box.inflated(-scale_(0.5 * print.config().extruder_clearance_radius.value));
            auto iy1 = bbox.min.y();
            auto iy2 = bbox.max.y();
            (const_cast<ModelInstance*>(inst->model_instance))->arrange_order = k+1;
            double height = (k == (print_instance_count - 1))?printable_height:hc1;
            /*if (has_interlaced_objects) {
                if ((k < (print_instance_count - 1)) && (inst->print_object->height() > hc2)) {
                    too_tall_instances[inst] = std::make_pair(print_instance_with_bounding_box[k].hull_polygon, unscaled<double>(hc2));
                }
            }
            else {
                if ((k < (print_instance_count - 1)) && (inst->print_object->height() > hc1)) {
                    too_tall_instances[inst] = std::make_pair(print_instance_with_bounding_box[k].hull_polygon, unscaled<double>(hc1));
                }
            }*/
            for (int i = k+1; i < print_instance_count; i++)
            {
                auto& p = print_instance_with_bounding_box[i].print_instance;
                auto bbox2 = print_instance_with_bounding_box[i].bounding_box;
                auto py1 = bbox2.min.y();
                auto py2 = bbox2.max.y();
                auto inter_min = std::max(iy1, py1); // min y of intersection
                auto inter_max = std::min(iy2, py2); // max y of intersection. length=max_y-min_y>0 means intersection exists
                if (inter_max - inter_min > 0) {
                    height = hc2;
                    break;
                }
            }
            if (height < inst->print_object->height())
                too_tall_instances[inst] = std::make_pair(print_instance_with_bounding_box[k].hull_polygon, unscaled<double>(height));
        }
        if (too_tall_instances.size() > 0) {
            //return {, inst->model_instance->get_object()};
            for (auto& iter: too_tall_instances) {
                if (single_object_exception.string.empty()) {
                    single_object_exception.string = (boost::format(L("%1% is too tall, and collisions will be caused.")) %iter.first->model_instance->get_object()->name).str();
                    single_object_exception.object = iter.first->model_instance->get_object();
                }
                else {
                    single_object_exception.string += "\n" + (boost::format(L("%1% is too tall, and collisions will be caused.")) %iter.first->model_instance->get_object()->name).str();
                    single_object_exception.object = nullptr;
                }
                if (height_polygons)
                    height_polygons->emplace_back(std::move(iter.second));
            }
        }
    }
    return single_object_exception;
}
References Slic3r::Geometry::assemble_transform(), config(), empty(), EPSILON, Slic3r::get_bed_shape(), Slic3r::ModelInstance::get_mirror(), get_plate_origin(), Slic3r::ModelInstance::get_rotation(), Slic3r::ModelInstance::get_scaling_factor(), Slic3r::ObjectID::id, int, Slic3r::intersection(), L, Slic3r::PrintBase::model(), Slic3r::StringObjectException::object, Slic3r::Model::objects, objects(), Slic3r::offset(), Slic3r::MultiPoint::points, Slic3r::printable_height(), Slic3r::MultiPoint::rotate(), Slic3r::Geometry::rotation_diff_z(), scale_, Slic3r::StringObjectException::string, Slic3r::I18N::translate(), Slic3r::MultiPoint::translate(), and unscale_.
Referenced by validate().
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_calib_params()
void Slic3r::Print::set_calib_params (const Calib_Params & params)
{
    m_calib_params = params;
    m_calib_params.mode = params.mode;
}
References m_calib_params, and Slic3r::Calib_Params::mode.
set_cancel_callback()
void Slic3r::PrintBase::set_cancel_callback (cancel_callback_type cancel_callback) inline inherited
{ m_cancel_callback = cancel_callback; }
References Slic3r::PrintBase::cancel_callback(), and Slic3r::PrintBase::m_cancel_callback.
Referenced by Slic3r::BackgroundSlicingProcess::start(), Slic3r::BackgroundSlicingProcess::stop(), and Slic3r::BackgroundSlicingProcess::stop_internal().
set_done()
PrintStateBase::TimeStamp Slic3r::PrintBaseWithState< PrintStep , COUNT >::set_done (PrintStep step) inline protected inherited
{
    std::pair<PrintStateBase::TimeStamp, bool> status = m_state.set_done(step, this->state_mutex(), [this](){ this->throw_if_canceled(); });
        if (status.second)
            this->status_update_warnings(static_cast<int>(step), PrintStateBase::WarningLevel::NON_CRITICAL, std::string());
        return status.first;
  }
set_gcode_file_invalidated()
void Slic3r::Print::set_gcode_file_invalidated ()
{
    this->invalidate_step(psGCodeExport);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ <<  boost::format(": done");
}
References Slic3r::psGCodeExport.
set_gcode_file_ready()
void Slic3r::Print::set_gcode_file_ready ()
{
    this->set_started(psGCodeExport);
  this->set_done(psGCodeExport);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ <<  boost::format(": done");
}
References Slic3r::psGCodeExport.
Referenced by Slic3r::GUI::Plater::load_gcode(), and Slic3r::GUI::PartPlate::load_gcode_from_file().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_no_check_flag()
void Slic3r::PrintBase::set_no_check_flag (bool no_check) inline inherited
{ m_no_check = no_check; }
References Slic3r::PrintBase::m_no_check.
Referenced by Slic3r::CLI::run().
set_plate_index()
void Slic3r::PrintBase::set_plate_index (int index) inline inherited
{ m_plate_index = index; }
References Slic3r::PrintBase::m_plate_index.
Referenced by Slic3r::GUI::PartPlate::set_index().
set_plate_name()
void Slic3r::PrintBase::set_plate_name (const std::string & name) inline inherited
{ m_plate_name = name; }
References Slic3r::PrintBase::m_plate_name.
Referenced by Slic3r::GUI::PartPlate::set_plate_name().
set_plate_origin()
void Slic3r::Print::set_plate_origin (Vec3d origin) inline
{ m_origin = origin; }
References m_origin.
Referenced by Slic3r::GUI::PartPlate::set_pos_and_size(), and Slic3r::GUI::PartPlate::set_print().
set_started()
bool Slic3r::PrintBaseWithState< PrintStep , COUNT >::set_started (PrintStep step) inline protected inherited
{ return m_state.set_started(step, this->state_mutex(), [this](){ this->throw_if_canceled(); }); }
set_status()
void Slic3r::PrintBase::set_status (int percent, const std::string & message, unsigned int flags = SlicingStatus::DEFAULT, int warning_step = -1) const inherited
{
  if (m_status_callback)
        m_status_callback(SlicingStatus(percent, message, flags, warning_step));
    else
        BOOST_LOG_TRIVIAL(debug) <<boost::format("Percent %1%: %2%\n")%percent %message.c_str();
}
References Slic3r::PrintBase::m_status_callback.
Referenced by Slic3r::BackgroundSlicingProcess::finalize_gcode(), Slic3r::PrintObject::make_perimeters(), Slic3r::SLAPrint::StatusReporter::operator()(), Slic3r::BackgroundSlicingProcess::prepare_upload(), Slic3r::BackgroundSlicingProcess::process_fff(), Slic3r::GCode::process_layers(), Slic3r::GCode::process_layers(), Slic3r::BackgroundSlicingProcess::process_sla(), and Slic3r::GUI::GLGizmoFdmSupports::run_thread().
set_status_callback()
void Slic3r::PrintBase::set_status_callback (status_callback_type cb) inline inherited
{ m_status_callback = cb; }
References Slic3r::PrintBase::m_status_callback.
Referenced by Slic3r::CLI::run(), and Slic3r::GUI::PartPlate::update_slice_context().
set_status_default()
void Slic3r::PrintBase::set_status_default () inline inherited
{ m_status_callback = nullptr; }
References Slic3r::PrintBase::m_status_callback.
set_status_silent()
void Slic3r::PrintBase::set_status_silent () inline inherited
{ m_status_callback = [](const SlicingStatus&){}; }
References Slic3r::PrintBase::m_status_callback.
set_task()
virtual void Slic3r::PrintBase::set_task (const TaskParams & params) inline virtual inherited
Reimplemented in Slic3r::SLAPrint.
{}
Referenced by Slic3r::BackgroundSlicingProcess::set_task().
skirt()
const ExtrusionEntityCollection & Slic3r::Print::skirt () const inline
{ return m_skirt; }
References m_skirt.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::get_print_extrusions_extents(), Slic3r::DoExport::init_ooze_prevention(), Slic3r::Skirt::make_skirt_loops_per_extruder_1st_layer(), Slic3r::Skirt::make_skirt_loops_per_extruder_other_layers(), Slic3r::GCode::process_layer(), and Slic3r::Skirt::skirt_loops_per_extruder_all_printing().
skirt_first_layer_height()
double Slic3r::Print::skirt_first_layer_height () const
{
    return m_config.initial_layer_print_height.value;
}
References m_config.
Referenced by Slic3r::make_inner_brim(), and Slic3r::make_inner_island_brim().
skirt_flow()
Flow Slic3r::Print::skirt_flow () const
{
    ConfigOptionFloatOrPercent width = m_config.initial_layer_line_width;
    if (width.value <= 0)
        width = m_objects.front()->config().line_width;
    /* We currently use a random object's support material extruder.
       While this works for most cases, we should probably consider all of the support material
       extruders and take the one with, say, the smallest index;
       The same logic should be applied to the code that selects the extruder during G-code
       generation as well. */
    return Flow::new_from_config_width(
        frPerimeter,
        // Flow::new_from_config_width takes care of the percent to value substitution
    width,
    (float)m_config.nozzle_diameter.get_at(m_objects.front()->config().support_filament-1),
    (float)this->skirt_first_layer_height());
}
References Slic3r::frPerimeter, m_config, m_objects, and Slic3r::Flow::new_from_config_width().
Referenced by Slic3r::GCode::process_layer().
state_mutex()
std::mutex & Slic3r::PrintBase::state_mutex () const inline protected inherited
{ return m_state_mutex; }
References Slic3r::PrintBase::m_state_mutex.
Referenced by Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::active_step_add_warning(), Slic3r::SLAPrint::apply(), clear(), Slic3r::SLAPrint::clear(), Slic3r::BackgroundSlicingProcess::is_step_done(), is_step_done(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::is_step_done(), Slic3r::SLAPrint::is_step_done(), Slic3r::BackgroundSlicingProcess::reset_export(), Slic3r::BackgroundSlicingProcess::schedule_export(), Slic3r::BackgroundSlicingProcess::schedule_upload(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_done(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_started(), Slic3r::BackgroundSlicingProcess::set_step_done(), Slic3r::BackgroundSlicingProcess::set_step_started(), Slic3r::SLAPrint::set_task(), Slic3r::PrintObjectBase::state_mutex(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::step_state_with_timestamp(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::step_state_with_warnings(), and Slic3r::BackgroundSlicingProcess::stop_internal().
status_update_warnings() [1/2]
void Slic3r::PrintBase::status_update_warnings (int step, PrintStateBase::WarningLevel warning_level, const std::string & message, const PrintObjectBase * print_object = nullptr, PrintStateBase::SlicingNotificationType message_id = PrintStateBase::SlicingDefaultNotification) protected inherited
{
    if (this->m_status_callback) {
        auto status = print_object ? SlicingStatus(*print_object, step, message, message_id) : SlicingStatus(*this, step, message, message_id);
        m_status_callback(status);
    }
    else if (! message.empty())
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Print warning: %1%\n")% message.c_str();
}
References Slic3r::PrintBase::m_status_callback.
Referenced by Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::active_step_add_warning(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_done(), and Slic3r::PrintObjectBase::status_update_warnings().
status_update_warnings() [2/2]
void Slic3r::PrintBase::status_update_warnings (int step, PrintStateBase::WarningLevel , const std::string & message, PrintObjectBase & object, PrintStateBase::SlicingNotificationType message_id = PrintStateBase::SlicingDefaultNotification) protected inherited
{
    //BBS: add object it into slicing status
    if (this->m_status_callback) {
        m_status_callback(SlicingStatus(object, step, message, message_id));
    }
    else if (!message.empty())
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", PrintObject warning: %1%\n")% message.c_str();
}
References Slic3r::PrintBase::m_status_callback.
step_state_with_timestamp()
PrintStateBase::StateWithTimeStamp Slic3r::PrintBaseWithState< PrintStep , COUNT >::step_state_with_timestamp (PrintStep step) const inline inherited
{ return m_state.state_with_timestamp(step, this->state_mutex()); }
step_state_with_warnings()
PrintStateBase::StateWithWarnings Slic3r::PrintBaseWithState< PrintStep , COUNT >::step_state_with_warnings (PrintStep step) const inline inherited
{ return m_state.state_with_warnings(step, this->state_mutex()); }
support_material_extruders()
std::vector< unsigned int > Slic3r::Print::support_material_extruders () const
{
    std::vector<unsigned int> extruders;
    bool support_uses_current_extruder = false;
    // BBS
    auto num_extruders = (unsigned int)m_config.filament_diameter.size();
    for (PrintObject *object : m_objects) {
        if (object->has_support_material()) {
          assert(object->config().support_filament >= 0);
            if (object->config().support_filament == 0)
                support_uses_current_extruder = true;
            else {
              unsigned int i = (unsigned int)object->config().support_filament - 1;
                extruders.emplace_back((i >= num_extruders) ? 0 : i);
            }
          assert(object->config().support_interface_filament >= 0);
            if (object->config().support_interface_filament == 0)
                support_uses_current_extruder = true;
            else {
              unsigned int i = (unsigned int)object->config().support_interface_filament - 1;
                extruders.emplace_back((i >= num_extruders) ? 0 : i);
            }
        }
    }
    if (support_uses_current_extruder)
        // Add all object extruders to the support extruders as it is not know which one will be used to print supports.
        append(extruders, this->object_extruders());
    sort_remove_duplicates(extruders);
    return extruders;
}
References Slic3r::append(), extruders(), int, m_config, m_objects, object_extruders(), and Slic3r::sort_remove_duplicates().
Referenced by extruders().
technology()
PrinterTechnology Slic3r::Print::technology () const inline override virtual noexcept
Implements Slic3r::PrintBase.
{ return ptFFF; }
References Slic3r::ptFFF.
throw_if_canceled()
void Slic3r::PrintBase::throw_if_canceled () const inline protected inherited
{ if (m_cancel_status.load(std::memory_order_acquire)) throw CanceledException(); }
References Slic3r::PrintBase::m_cancel_status.
Referenced by Slic3r::GCode::_do_export(), Slic3r::SLAPrint::Steps::generate_pad(), Slic3r::PrintObject::make_perimeters(), Slic3r::PrintTryCancel::operator()(), Slic3r::SLAPrint::process(), Slic3r::GCode::process_layers(), Slic3r::GCode::process_layers(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_done(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_started(), Slic3r::PrintObject::slice_support_volumes(), Slic3r::PrintObject::slice_volumes(), Slic3r::SLAPrint::Steps::support_points(), Slic3r::SLAPrint::Steps::support_tree(), and Slic3r::SLAPrint::Steps::throw_if_canceled().
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
tool_ordering()
const ToolOrdering & Slic3r::Print::tool_ordering () const inline
{ return m_tool_ordering; }
References m_tool_ordering.
Referenced by Slic3r::GCode::_do_export().
translate_to_print_space() [1/2]
Vec2d Slic3r::Print::translate_to_print_space (const Point & point) const
{
    return Vec2d(unscaled(point.x()) - m_origin(0), unscaled(point.y()) - m_origin(1));
}
References Slic3r::unscaled().
translate_to_print_space() [2/2]
Vec2d Slic3r::Print::translate_to_print_space (const Vec2d & point) const
{
    //const BoundingBoxf bed_bbox(config().printable_area.values);
    return Vec2d(point(0) - m_origin(0), point(1) - m_origin(1));
}
Referenced by Slic3r::GCode::_do_export(), Slic3r::polygon_to_string(), and Slic3r::GCode::set_object_info().
update_object_placeholders()
void Slic3r::PrintBase::update_object_placeholders (DynamicConfig & config, const std::string & default_ext) const protected inherited
{
    // get the first input file name
    std::string input_file;
    std::vector<std::string> v_scale;
    int num_objects = 0;
    int num_instances = 0;
  for (const ModelObject *model_object : m_model.objects) {
    ModelInstance *printable = nullptr;
    for (ModelInstance *model_instance : model_object->instances)
      if (model_instance->is_printable()) {
        printable = model_instance;
        ++ num_instances;
      }
    if (printable) {
            ++ num_objects;
          // CHECK_ME -> Is the following correct ?
      v_scale.push_back("x:" + boost::lexical_cast<std::string>(printable->get_scaling_factor(X) * 100) +
        "% y:" + boost::lexical_cast<std::string>(printable->get_scaling_factor(Y) * 100) +
        "% z:" + boost::lexical_cast<std::string>(printable->get_scaling_factor(Z) * 100) + "%");
          if (input_file.empty())
              input_file = model_object->name.empty() ? model_object->input_file : model_object->name;
      }
    }
    config.set_key_value("num_objects", new ConfigOptionInt(num_objects));
    config.set_key_value("num_instances", new ConfigOptionInt(num_instances));
    config.set_key_value("scale", new ConfigOptionStrings(v_scale));
    if (! input_file.empty()) {
        // get basename with and without suffix
        const std::string input_filename = boost::filesystem::path(input_file).filename().string();
        const std::string input_filename_base = input_filename.substr(0, input_filename.find_last_of("."));
        config.set_key_value("input_filename", new ConfigOptionString(input_filename_base + default_ext));
        config.set_key_value("input_filename_base", new ConfigOptionString(input_filename_base));
    }
}
References Slic3r::ModelInstance::get_scaling_factor(), Slic3r::PrintBase::m_model, Slic3r::Model::objects, Slic3r::DynamicConfig::set_key_value(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::PrintBase::output_filename().
validate()
StringObjectException Slic3r::Print::validate (StringObjectException * warning = nullptr, Polygons * collison_polygons = nullptr, std::vector< std::pair< Polygon, float > > * height_polygons = nullptr) const override virtual
Reimplemented from Slic3r::PrintBase.
{
    std::vector<unsigned int> extruders = this->extruders();
    if (m_objects.empty())
        return {std::string()};
    if (extruders.empty())
        return { L("No extrusions under current settings.") };
    if (extruders.size() > 1 && m_config.print_sequence != PrintSequence::ByObject) {
        auto ret = check_multi_filament_valid(*this);
        if (!ret.string.empty())
        {
            ret.type = STRING_EXCEPT_FILAMENTS_DIFFERENT_TEMP;
            return ret;
        }
    }
    if (m_config.print_sequence == PrintSequence::ByObject) {
        if (m_config.timelapse_type == TimelapseType::tlSmooth)
            return {L("Smooth mode of timelapse is not supported when \"by object\" sequence is enabled.")};
        //BBS: refine seq-print validation logic
        auto ret = sequential_print_clearance_valid(*this, collison_polygons, height_polygons);
        if (!ret.string.empty()) {
            ret.type = STRING_EXCEPT_OBJECT_COLLISION_IN_SEQ_PRINT;
            return ret;
        }
    }
    else {
        //BBS
        auto ret = layered_print_cleareance_valid(*this, warning);
        if (!ret.string.empty()) {
            ret.type = STRING_EXCEPT_OBJECT_COLLISION_IN_LAYER_PRINT;
            return ret;
        }
    }
    if (m_config.spiral_mode) {
        size_t total_copies_count = 0;
        for (const PrintObject *object : m_objects)
            total_copies_count += object->instances().size();
        // #4043
        if (total_copies_count > 1 && m_config.print_sequence != PrintSequence::ByObject)
            return {L("Please select \"By object\" print sequence to print multiple objects in spiral vase mode."), nullptr, "spiral_mode"};
        assert(m_objects.size() == 1);
        if (m_objects.front()->all_regions().size() > 1)
            return {L("The spiral vase mode does not work when an object contains more than one materials."), nullptr, "spiral_mode"};
    }
    if (this->has_wipe_tower() && ! m_objects.empty()) {
        // Make sure all extruders use same diameter filament and have the same nozzle diameter
        // EPSILON comparison is used for nozzles and 10 % tolerance is used for filaments
        double first_nozzle_diam = m_config.nozzle_diameter.get_at(extruders.front());
        double first_filament_diam = m_config.filament_diameter.get_at(extruders.front());
        for (const auto& extruder_idx : extruders) {
            double nozzle_diam = m_config.nozzle_diameter.get_at(extruder_idx);
            double filament_diam = m_config.filament_diameter.get_at(extruder_idx);
            if (nozzle_diam - EPSILON > first_nozzle_diam || nozzle_diam + EPSILON < first_nozzle_diam
                || std::abs((filament_diam - first_filament_diam) / first_filament_diam) > 0.1)
                // BBS: remove L()
                return { ("Different nozzle diameters and different filament diameters is not allowed when prime tower is enabled.") };
        }
        if (! m_config.use_relative_e_distances)
            return { ("The Wipe Tower is currently only supported with the relative extruder addressing (use_relative_e_distances=1).") };
        if (m_config.ooze_prevention)
            return { ("Ooze prevention is currently not supported with the prime tower enabled.") };
        // BBS: remove following logic and _L()
#if 0
        if (m_config.gcode_flavor != gcfRepRapSprinter && m_config.gcode_flavor != gcfRepRapFirmware &&
            m_config.gcode_flavor != gcfRepetier && m_config.gcode_flavor != gcfMarlinLegacy && m_config.gcode_flavor != gcfMarlinFirmware)
            return {("The prime tower is currently only supported for the Marlin, RepRap/Sprinter, RepRapFirmware and Repetier G-code flavors.")};
        if ((m_config.print_sequence == PrintSequence::ByObject) && extruders.size() > 1)
            return { L("The prime tower is not supported in \"By object\" print."), nullptr, "enable_prime_tower" };
        // BBS: When prime tower is on, object layer and support layer must be aligned. So support gap should be multiple of object layer height.
        for (size_t i = 0; i < m_objects.size(); i++) {
            const PrintObject* object = m_objects[i];
            const SlicingParameters& slicing_params = object->slicing_parameters();
            if (object->config().adaptive_layer_height) {
                return  { L("The prime tower is not supported when adaptive layer height is on. It requires that all objects have the same layer height."), object, "adaptive_layer_height" };
            }
            if (!object->config().enable_support)
                continue;
            double gap_layers = slicing_params.gap_object_support / slicing_params.layer_height;
            if (gap_layers - (int)gap_layers > EPSILON) {
                return  { L("The prime tower requires \"support gap\" to be multiple of layer height"), object };
            }
        }
#endif
        if (m_objects.size() > 1) {
            bool                                has_custom_layering = false;
            std::vector<std::vector<coordf_t>>  layer_height_profiles;
            for (const PrintObject *object : m_objects) {
                has_custom_layering = ! object->model_object()->layer_config_ranges.empty() || ! object->model_object()->layer_height_profile.empty();
                if (has_custom_layering) {
                    layer_height_profiles.assign(m_objects.size(), std::vector<coordf_t>());
                    break;
                }
            }
            const SlicingParameters &slicing_params0 = m_objects.front()->slicing_parameters();
            size_t            tallest_object_idx = 0;
            if (has_custom_layering)
                PrintObject::update_layer_height_profile(*m_objects.front()->model_object(), slicing_params0, layer_height_profiles.front());
            for (size_t i = 1; i < m_objects.size(); ++ i) {
                const PrintObject       *object         = m_objects[i];
                const SlicingParameters &slicing_params = object->slicing_parameters();
                if (std::abs(slicing_params.first_print_layer_height - slicing_params0.first_print_layer_height) > EPSILON ||
                    std::abs(slicing_params.layer_height             - slicing_params0.layer_height            ) > EPSILON)
                    return {L("The prime tower requires that all objects have the same layer heights"), object, "initial_layer_print_height"};
                if (slicing_params.raft_layers() != slicing_params0.raft_layers())
                    return {L("The prime tower requires that all objects are printed over the same number of raft layers"), object, "raft_layers"};
                // BBS: support gap can be multiple of object layer height, remove _L()
#if 0
                if (slicing_params0.gap_object_support != slicing_params.gap_object_support ||
                    slicing_params0.gap_support_object != slicing_params.gap_support_object)
                    return  {("The prime tower is only supported for multiple objects if they are printed with the same support_top_z_distance"), object};
#endif
                if (!equal_layering(slicing_params, slicing_params0))
                    return  { L("The prime tower requires that all objects are sliced with the same layer heights."), object };
                if (has_custom_layering) {
                    PrintObject::update_layer_height_profile(*object->model_object(), slicing_params, layer_height_profiles[i]);
                    if (*(layer_height_profiles[i].end()-2) > *(layer_height_profiles[tallest_object_idx].end()-2))
                        tallest_object_idx = i;
                }
            }
            // BBS: remove obsolete logics and _L()
            if (has_custom_layering) {
                for (size_t idx_object = 0; idx_object < m_objects.size(); ++idx_object) {
                    if (idx_object == tallest_object_idx) continue;
                    // Check that the layer height profiles are equal. This will happen when one object is
                    // a copy of another, or when a layer height modifier is used the same way on both objects.
                    // The latter case might create a floating point inaccuracy mismatch, so compare
                    // element-wise using an epsilon check.
                    size_t         i   = 0;
                    const coordf_t eps = 0.5 * EPSILON; // layers closer than EPSILON will be merged later. Let's make
                    // this check a bit more sensitive to make sure we never consider two different layers as one.
                    while (i < layer_height_profiles[idx_object].size() && i < layer_height_profiles[tallest_object_idx].size()) {
                        // BBS: remove the break condition, because a variable layer height object and a new object will not be checked when slicing
                        //if (i % 2 == 0 && layer_height_profiles[tallest_object_idx][i] > layer_height_profiles[idx_object][layer_height_profiles[idx_object].size() - 2])
                        //    break;
                        if (std::abs(layer_height_profiles[idx_object][i] - layer_height_profiles[tallest_object_idx][i]) > eps)
                            return {L("The prime tower is only supported if all objects have the same variable layer height")};
                        ++i;
                    }
                }
            }
        }
    }
  {
    // Find the smallest used nozzle diameter and the number of unique nozzle diameters.
    double min_nozzle_diameter = std::numeric_limits<double>::max();
    double max_nozzle_diameter = 0;
    for (unsigned int extruder_id : extruders) {
      double dmr = m_config.nozzle_diameter.get_at(extruder_id);
      min_nozzle_diameter = std::min(min_nozzle_diameter, dmr);
      max_nozzle_diameter = std::max(max_nozzle_diameter, dmr);
    }
        // BBS: remove L()
#if 0
        // We currently allow one to assign extruders with a higher index than the number
        // of physical extruders the machine is equipped with, as the Printer::apply() clamps them.
        unsigned int total_extruders_count = m_config.nozzle_diameter.size();
        for (const auto& extruder_idx : extruders)
            if ( extruder_idx >= total_extruders_count )
                return ("One or more object were assigned an extruder that the printer does not have.");
#endif
        auto validate_extrusion_width = [min_nozzle_diameter, max_nozzle_diameter](const ConfigBase &config, const char *opt_key, double layer_height, std::string &err_msg) -> bool {
            double extrusion_width_min = config.get_abs_value(opt_key, min_nozzle_diameter);
            double extrusion_width_max = config.get_abs_value(opt_key, max_nozzle_diameter);
          if (extrusion_width_min == 0) {
            // Default "auto-generated" extrusion width is always valid.
          } else if (extrusion_width_min <= layer_height) {
                err_msg = L("Too small line width");
        return false;
      } else if (extrusion_width_max > max_nozzle_diameter * 5) {
                err_msg = L("Too large line width");
        return false;
      }
      return true;
    };
        for (PrintObject *object : m_objects) {
            if (object->has_support_material()) {
                // BBS: remove useless logics and L()
#if 0
        if ((object->config().support_filament == 0 || object->config().support_interface_filament == 0) && max_nozzle_diameter - min_nozzle_diameter > EPSILON) {
                    // The object has some form of support and either support_filament or support_interface_filament
                    // will be printed with the current tool without a forced tool change. Play safe, assert that all object nozzles
                    // are of the same diameter.
                    return {("Printing with multiple extruders of differing nozzle diameters. "
                           "If support is to be printed with the current filament (support_filament == 0 or support_interface_filament == 0), "
                           "all nozzles have to be of the same diameter."), object, "support_filament"};
                }
#endif
                // BBS
#if 0
                if (this->has_wipe_tower() && object->config().independent_support_layer_height) {
                    return {L("The prime tower requires that support has the same layer height with object."), object, "support_filament"};
                }
#endif
            }
            // Do we have custom support data that would not be used?
            // Notify the user in that case.
            if (! object->has_support() && warning) {
                for (const ModelVolume* mv : object->model_object()->volumes) {
                    bool has_enforcers = mv->is_support_enforcer() ||
                        (mv->is_model_part() && mv->supported_facets.has_facets(*mv, EnforcerBlockerType::ENFORCER));
                    if (has_enforcers) {
                        warning->string = L("Support enforcers are used but support is not enabled. Please enable support.");
                        warning->object = object;
                        break;
                    }
                }
            }
            double initial_layer_print_height = m_config.initial_layer_print_height.value;
            double first_layer_min_nozzle_diameter;
            if (object->has_raft()) {
                // if we have raft layers, only support material extruder is used on first layer
                size_t first_layer_extruder = object->config().raft_layers == 1
                    ? object->config().support_interface_filament-1
                    : object->config().support_filament-1;
                first_layer_min_nozzle_diameter = (first_layer_extruder == size_t(-1)) ?
                    min_nozzle_diameter :
                    m_config.nozzle_diameter.get_at(first_layer_extruder);
            } else {
                // if we don't have raft layers, any nozzle diameter is potentially used in first layer
                first_layer_min_nozzle_diameter = min_nozzle_diameter;
            }
            if (initial_layer_print_height > first_layer_min_nozzle_diameter)
                return  {L("Layer height cannot exceed nozzle diameter"), object, "initial_layer_print_height"};
            // validate layer_height
            double layer_height = object->config().layer_height.value;
            if (layer_height > min_nozzle_diameter)
                return  {L("Layer height cannot exceed nozzle diameter"), object, "layer_height"};
            for (auto range : object->m_model_object->layer_config_ranges) {
                double range_layer_height = range.second.opt_float("layer_height");
                if (range_layer_height > object->m_slicing_params.max_layer_height ||
                    range_layer_height < object->m_slicing_params.min_layer_height)
                    return  { L("Layer height cannot exceed nozzle diameter"), nullptr, "layer_height" };
            }
            // Validate extrusion widths.
            std::string err_msg;
            if (!validate_extrusion_width(object->config(), "line_width", layer_height, err_msg))
              return {err_msg, object, "line_width"};
            if (object->has_support() || object->has_raft()) {
                if (!validate_extrusion_width(object->config(), "support_line_width", layer_height, err_msg))
                    return {err_msg, object, "support_line_width"};
            }
            for (const char *opt_key : { "inner_wall_line_width", "outer_wall_line_width", "sparse_infill_line_width", "internal_solid_infill_line_width", "top_surface_line_width" })
        for (const PrintRegion &region : object->all_regions())
                    if (!validate_extrusion_width(region.config(), opt_key, layer_height, err_msg))
                  return  {err_msg, object, opt_key};
        }
    }
    const ConfigOptionDef* bed_type_def = print_config_def.get("curr_bed_type");
    assert(bed_type_def != nullptr);
      if (is_BBL_printer()) {
      const t_config_enum_values* bed_type_keys_map = bed_type_def->enum_keys_map;
      for (unsigned int extruder_id : extruders) {
          const ConfigOptionInts* bed_temp_opt = m_config.option<ConfigOptionInts>(get_bed_temp_key(m_config.curr_bed_type));
          for (unsigned int extruder_id : extruders) {
              int curr_bed_temp = bed_temp_opt->get_at(extruder_id);
              if (curr_bed_temp == 0 && bed_type_keys_map != nullptr) {
                  std::string bed_type_name;
                  for (auto item : *bed_type_keys_map) {
                      if (item.second == m_config.curr_bed_type) {
                          bed_type_name = item.first;
                          break;
                      }
                  }
                  StringObjectException except;
                  except.string = format(L("Plate %d: %s does not support filament %s"), this->get_plate_index() + 1, L(bed_type_name), extruder_id + 1);
                  except.string += "\n";
                  except.type   = STRING_EXCEPT_FILAMENT_NOT_MATCH_BED_TYPE;
                  except.params.push_back(std::to_string(this->get_plate_index() + 1));
                  except.params.push_back(L(bed_type_name));
                  except.params.push_back(std::to_string(extruder_id+1));
                  except.object = nullptr;
                  return except;
             }
            }
        }
    }
    return {};
}
References Slic3r::ByObject, check_multi_filament_valid(), config(), end, Slic3r::ENFORCER, Slic3r::ConfigOptionDef::enum_keys_map, EPSILON, Slic3r::equal_layering(), extruders(), Slic3r::SlicingParameters::first_print_layer_height, Slic3r::format(), Slic3r::SlicingParameters::gap_object_support, Slic3r::SlicingParameters::gap_support_object, Slic3r::gcfMarlinFirmware, Slic3r::gcfMarlinLegacy, Slic3r::gcfRepetier, Slic3r::gcfRepRapFirmware, Slic3r::gcfRepRapSprinter, Slic3r::ConfigDef::get(), Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::get_bed_temp_key(), Slic3r::PrintBase::get_plate_index(), has_wipe_tower(), is_BBL_printer(), L, Slic3r::layer_height(), Slic3r::SlicingParameters::layer_height, Slic3r::layered_print_cleareance_valid(), m_config, m_objects, Slic3r::StringObjectException::object, Slic3r::StringObjectException::params, Slic3r::print_config_def, Slic3r::SlicingParameters::raft_layers(), Slic3r::range(), sequential_print_clearance_valid(), size, Slic3r::StringObjectException::string, Slic3r::STRING_EXCEPT_FILAMENT_NOT_MATCH_BED_TYPE, Slic3r::STRING_EXCEPT_FILAMENTS_DIFFERENT_TEMP, Slic3r::STRING_EXCEPT_OBJECT_COLLISION_IN_LAYER_PRINT, Slic3r::STRING_EXCEPT_OBJECT_COLLISION_IN_SEQ_PRINT, Slic3r::tlSmooth, Slic3r::StringObjectException::type, and Slic3r::PrintObject::update_layer_height_profile().
wipe_tower_data()
const WipeTowerData & Slic3r::Print::wipe_tower_data (size_t filaments_cnt = 0) const
{
    // If the wipe tower wasn't created yet, make sure the depth and brim_width members are set to default.
    if (! is_step_done(psWipeTower) && filaments_cnt !=0) {
        // BBS
        double width = m_config.prime_tower_width;
        double layer_height = 0.2; // hard code layer height
        double wipe_volume = m_config.prime_volume;
        if (filaments_cnt == 1 && enable_timelapse_print()) {
            const_cast<Print *>(this)->m_wipe_tower_data.depth = wipe_volume / (layer_height * width);
        } else {
            const_cast<Print *>(this)->m_wipe_tower_data.depth = wipe_volume * (filaments_cnt - 1) / (layer_height * width);
        }
        const_cast<Print*>(this)->m_wipe_tower_data.brim_width = m_config.prime_tower_brim_width;
    }
    return m_wipe_tower_data;
}
References Slic3r::layer_height(), and Slic3r::psWipeTower.
Referenced by Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::get_wipe_tower_extrusions_extents(), Slic3r::get_wipe_tower_priming_extrusions_extents(), Slic3r::layered_print_cleareance_valid(), Slic3r::GUI::GCodeViewer::load_shells(), and Slic3r::GUI::GLCanvas3D::reload_scene().
Friends And Related Symbol Documentation
GCode
friend class GCode friend
PrintObject
friend class PrintObject friend
Member Data Documentation
m_brimMap
std::map<ObjectID, ExtrusionEntityCollection> Slic3r::Print::m_brimMap private
Referenced by Slic3r::GCode::_do_export(), get_brimMap(), and Slic3r::GCode::process_layer().
m_calib_params
Calib_Params Slic3r::Print::m_calib_params private
Referenced by calib_mode(), calib_mode(), calib_params(), and set_calib_params().
m_cancel_callback
cancel_callback_type Slic3r::PrintBase::m_cancel_callback = [](){} private inherited
Referenced by Slic3r::PrintBase::call_cancel_callback(), Slic3r::PrintBase::cancel_callback(), and Slic3r::PrintBase::set_cancel_callback().
m_cancel_status
std::atomic<CancelStatus> Slic3r::PrintBase::m_cancel_status private inherited
Referenced by Slic3r::PrintBase::cancel(), Slic3r::PrintBase::cancel_internal(), Slic3r::PrintBase::cancel_status(), Slic3r::PrintBase::canceled(), Slic3r::PrintBase::restart(), and Slic3r::PrintBase::throw_if_canceled().
m_config
PrintConfig Slic3r::Print::m_config private
Referenced by brim_flow(), config(), extruders(), has_infinite_skirt(), has_skirt(), max_allowed_layer_height(), skirt_first_layer_height(), skirt_flow(), support_material_extruders(), and validate().
m_conflict_result
ConflictResultOpt Slic3r::Print::m_conflict_result private
Referenced by get_conflict_result(), and get_conflict_string().
m_default_object_config
PrintObjectConfig Slic3r::Print::m_default_object_config private
Referenced by default_object_config().
m_default_region_config
PrintRegionConfig Slic3r::Print::m_default_region_config private
Referenced by default_region_config().
m_fake_wipe_tower
FakeWipeTower Slic3r::Print::m_fake_wipe_tower private
m_first_layer_convex_hull
Polygon Slic3r::Print::m_first_layer_convex_hull private
Referenced by first_layer_convex_hull().
m_full_print_config
DynamicPrintConfig Slic3r::PrintBase::m_full_print_config protected inherited
Referenced by Slic3r::SLAPrint::apply(), and Slic3r::PrintBase::full_print_config().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_isBBLPrinter
bool Slic3r::Print::m_isBBLPrinter private
Referenced by is_BBL_printer(), and is_BBL_printer().
m_model
Model Slic3r::PrintBase::m_model protected inherited
Referenced by Slic3r::SLAPrint::apply(), clear(), Slic3r::SLAPrint::clear(), extruders(), Slic3r::PrintBase::model(), Slic3r::PrintBase::output_filepath(), and Slic3r::PrintBase::update_object_placeholders().
m_modified_count
int Slic3r::Print::m_modified_count {0} private
Referenced by get_modified_count().
m_no_check
bool Slic3r::PrintBase::m_no_check = false protected inherited
Referenced by Slic3r::PrintBase::get_no_check_flag(), and Slic3r::PrintBase::set_no_check_flag().
m_objects
PrintObjectPtrs Slic3r::Print::m_objects private
Referenced by brim_flow(), clear(), empty(), get_object(), get_object(), get_object(), has_auto_brim(), has_brim(), has_support_material(), invalidate_state_by_config_options(), is_step_done(), layers_sorted_for_object(), num_object_instances(), object_extruders(), objects(), objects_mutable(), print_object_ids(), process(), skirt_flow(), support_material_extruders(), and validate().
m_origin
Vec3d Slic3r::Print::m_origin private
Referenced by get_plate_origin(), and set_plate_origin().
m_placeholder_parser
PlaceholderParser Slic3r::PrintBase::m_placeholder_parser protected inherited
Referenced by Slic3r::SLAPrint::apply(), and Slic3r::PrintBase::placeholder_parser().
m_plate_index
int Slic3r::PrintBase::m_plate_index { 0 } protected inherited
Referenced by Slic3r::PrintBase::get_plate_index(), and Slic3r::PrintBase::set_plate_index().
m_plate_name
std::string Slic3r::PrintBase::m_plate_name protected inherited
Referenced by Slic3r::PrintBase::get_plate_name(), and Slic3r::PrintBase::set_plate_name().
m_print_regions
PrintRegionPtrs Slic3r::Print::m_print_regions private
Referenced by brim_flow(), clear(), get_print_region(), num_print_regions(), object_extruders(), and print_regions_mutable().
m_print_statistics
PrintStatistics Slic3r::Print::m_print_statistics private
Referenced by Slic3r::GCode::_do_export(), Slic3r::GCode::do_export(), print_statistics(), and print_statistics().
m_skirt
ExtrusionEntityCollection Slic3r::Print::m_skirt private
Referenced by skirt().
m_skirt_convex_hull
Points Slic3r::Print::m_skirt_convex_hull private
m_state
PrintState<PrintStep , COUNT> Slic3r::PrintBaseWithState< PrintStep , COUNT >::m_state private inherited
m_state_mutex
std::mutex Slic3r::PrintBase::m_state_mutex mutable private inherited
Referenced by Slic3r::PrintBase::state_mutex().
m_status_callback
status_callback_type Slic3r::PrintBase::m_status_callback protected inherited
Referenced by Slic3r::PrintBase::set_status(), Slic3r::PrintBase::set_status_callback(), Slic3r::PrintBase::set_status_default(), Slic3r::PrintBase::set_status_silent(), Slic3r::PrintBase::status_update_warnings(), and Slic3r::PrintBase::status_update_warnings().
m_support_used
bool Slic3r::Print::m_support_used {false} private
Referenced by is_support_used().
m_supportBrimMap
std::map<ObjectID, ExtrusionEntityCollection> Slic3r::Print::m_supportBrimMap private
Referenced by Slic3r::GCode::_do_export(), and Slic3r::GCode::process_layer().
m_tool_ordering
ToolOrdering Slic3r::Print::m_tool_ordering private
Referenced by tool_ordering().
m_wipe_tower_data
WipeTowerData Slic3r::Print::m_wipe_tower_data {m_tool_ordering} private
Referenced by get_tool_ordering().
min_skirt_length
float Slic3r::Print::min_skirt_length = 0 static
PrintTryCancel
friend Slic3r::PrintBase::PrintTryCancel private inherited
Referenced by Slic3r::PrintBase::make_try_cancel().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
The documentation for this class was generated from the following files:
src/libslic3r/Print.hpp
src/libslic3r/Print.cpp
src/libslic3r/PrintApply.cpp