OrcaSlicer: Tabbook Class Reference
Tabbook Class Reference
#include <src/slic3r/GUI/Tabbook.hpp>
Public Member Functions
Tabbook (wxWindow *parent, wxWindowID winid=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, wxBoxSizer *side_tools=NULL, long style=0)
bool Create (wxWindow *parent, wxWindowID winid=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, wxBoxSizer *side_tools=NULL, long style=0)
bool ShowNewPage (wxWindow *page)
void SetEffects (wxShowEffect showEffect, wxShowEffect hideEffect)
void SetEffect (wxShowEffect effect)
void SetEffectsTimeouts (unsigned showTimeout, unsigned hideTimeout)
void SetEffectTimeout (unsigned timeout)
bool AddPage (wxWindow *page, const wxString &text, const std::string &bmp_name, bool bSelect=false)
virtual bool InsertPage (size_t n, wxWindow *page, const wxString &text, bool bSelect=false, int imageId=NO_IMAGE) override
bool InsertNewPage (size_t n, wxWindow *page, const wxString &text, const std::string &bmp_name="", bool bSelect=false)
bool RemovePage (size_t n)
virtual int SetSelection (size_t n) override
virtual int ChangeSelection (size_t n) override
virtual bool SetPageText (size_t n, const wxString &strText) override
virtual wxString GetPageText (size_t n) const override
virtual bool SetPageImage (size_t WXUNUSED(n), int WXUNUSED(imageId)) override
virtual int GetPageImage (size_t WXUNUSED(n)) const override
bool SetPageImage (size_t n, const std::string &bmp_name)
virtual void SetFocus () override
TabButtonsListCtrl * GetBtnsListCtrl () const
void Rescale ()
void OnNavigationKey (wxNavigationKeyEvent &event)
Protected Member Functions
virtual void UpdateSelectedPage (size_t WXUNUSED(newsel)) override
virtual wxBookCtrlEvent * CreatePageChangingEvent () const override
virtual void MakeChangedEvent (wxBookCtrlEvent &event) override
virtual wxWindow * DoRemovePage (size_t page) override
virtual void DoSize () override
virtual void DoShowPage (wxWindow *page, bool show) override
Private Member Functions
void Init ()
Private Attributes
wxShowEffect m_showEffect
wxShowEffect m_hideEffect
unsigned m_showTimeout
unsigned m_hideTimeout
TabButtonsListCtrl * m_ctrl {nullptr}
Detailed Description
Constructor & Destructor Documentation
Tabbook()
Tabbook::Tabbook (wxWindow * parent, wxWindowID winid = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, wxBoxSizer * side_tools = NULL, long style = 0) inline
    {
        Init();
        Create(parent, winid, pos, size, side_tools, style);
    }
References Create(), Init(), size, and style.
Member Function Documentation
AddPage()
bool Tabbook::AddPage (wxWindow * page, const wxString & text, const std::string & bmp_name, bool bSelect = false) inline
    {
        DoInvalidateBestSize();
        return InsertNewPage(GetPageCount(), page, text, bmp_name, bSelect);
    }
References InsertNewPage().
Referenced by Slic3r::GUI::AuxiliaryPanel::init_tabpanel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), and ShowNewPage().
ChangeSelection()
virtual int Tabbook::ChangeSelection (size_t n) inline override virtual
    {
        GetBtnsListCtrl()->SetSelection(n);
        return DoSetSelection(n);
    }
References GetBtnsListCtrl(), n, and TabButtonsListCtrl::SetSelection().
Referenced by Slic3r::GUI::Plater::print_job_finished().
Create()
bool Tabbook::Create (wxWindow * parent, wxWindowID winid = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, wxBoxSizer * side_tools = NULL, long style = 0) inline
    {
        if (!wxBookCtrlBase::Create(parent, winid, pos, size, style))
            return false;
        m_bookctrl = new TabButtonsListCtrl(this, side_tools);
        wxSizer* mainSizer = new wxBoxSizer(IsVertical() ? wxVERTICAL : wxHORIZONTAL);
        if (style & wxBK_RIGHT || style & wxBK_BOTTOM)
            mainSizer->Add(0, 0, 1, wxEXPAND, 0);
        m_controlSizer = new wxBoxSizer(IsVertical() ? wxHORIZONTAL : wxVERTICAL);
        m_controlSizer->Add(m_bookctrl, wxSizerFlags(0).Expand());
        wxSizerFlags flags;
        if (IsVertical())
            flags.Expand();
        else
            flags.Expand();
        mainSizer->Add(m_controlSizer, flags.Border(wxALL, m_controlMargin));
        SetSizer(mainSizer);
        this->Bind(wxCUSTOMEVT_TABBOOK_SEL_CHANGED, [this](wxCommandEvent& evt)
        {
            if (int page_idx = evt.GetId(); page_idx >= 0)
                SetSelection(page_idx);
        });
        this->Bind(wxEVT_NAVIGATION_KEY, &Tabbook::OnNavigationKey, this);
        return true;
    }
References OnNavigationKey(), SetSelection(), size, and style.
Referenced by Tabbook().
CreatePageChangingEvent()
virtual wxBookCtrlEvent * Tabbook::CreatePageChangingEvent () const inline override protected virtual
    {
        return new wxBookCtrlEvent(wxEVT_BOOKCTRL_PAGE_CHANGING,
                                   GetId());
    }
DoRemovePage()
virtual wxWindow * Tabbook::DoRemovePage (size_t page) inline override protected virtual
    {
        wxWindow* const win = wxBookCtrlBase::DoRemovePage(page);
        if (win)
        {
            GetBtnsListCtrl()->RemovePage(page);
            DoSetSelectionAfterRemoval(page);
        }
        return win;
    }
References GetBtnsListCtrl(), and TabButtonsListCtrl::RemovePage().
DoShowPage()
virtual void Tabbook::DoShowPage (wxWindow * page, bool show) inline override protected virtual
    {
        if (show)
            page->ShowWithEffect(m_showEffect, m_showTimeout);
        else
            page->HideWithEffect(m_hideEffect, m_hideTimeout);
    }
References m_hideEffect, m_hideTimeout, m_showEffect, and m_showTimeout.
DoSize()
virtual void Tabbook::DoSize () inline override protected virtual
    {
        wxWindow* const page = GetCurrentPage();
        if (page)
            page->SetSize(GetPageRect());
    }
GetBtnsListCtrl()
TabButtonsListCtrl * Tabbook::GetBtnsListCtrl () const inline
{ return static_cast<TabButtonsListCtrl *>(m_bookctrl); }
Referenced by ChangeSelection(), DoRemovePage(), GetPageText(), InsertNewPage(), InsertPage(), Rescale(), SetPageImage(), SetPageText(), and SetSelection().
GetPageImage()
virtual int Tabbook::GetPageImage (size_t WXUNUSEDn) const inline override virtual
    {
        return NO_IMAGE;
    }
GetPageText()
virtual wxString Tabbook::GetPageText (size_t n) const inline override virtual
    {
        wxCHECK_MSG(n < GetPageCount(), wxString(), wxS("Invalid page"));
        return GetBtnsListCtrl()->GetPageText(n);
    }
References GetBtnsListCtrl(), TabButtonsListCtrl::GetPageText(), and n.
Init()
void Tabbook::Init () inline private
    {
        // We don't need any border as we don't have anything to separate the
        // page contents from.
        SetInternalBorder(0);
        // No effects by default.
        m_showEffect =
        m_hideEffect = wxSHOW_EFFECT_NONE;
        m_showTimeout =
        m_hideTimeout = 0;
    }
References m_hideEffect, m_hideTimeout, m_showEffect, and m_showTimeout.
Referenced by Tabbook().
InsertNewPage()
bool Tabbook::InsertNewPage (size_t n, wxWindow * page, const wxString & text, const std::string & bmp_name = "", bool bSelect = false) inline
    {
        if (!wxBookCtrlBase::InsertPage(n, page, text, bSelect))
            return false;
        GetBtnsListCtrl()->InsertPage(n, text, bSelect, bmp_name);
        if (bSelect)
            SetSelection(n);
        return true;
    }
References GetBtnsListCtrl(), TabButtonsListCtrl::InsertPage(), n, and SetSelection().
Referenced by AddPage().
InsertPage()
virtual bool Tabbook::InsertPage (size_t n, wxWindow * page, const wxString & text, bool bSelect = false, int imageId = NO_IMAGE) inline override virtual
    {
        if (!wxBookCtrlBase::InsertPage(n, page, text, bSelect, imageId))
            return false;
        GetBtnsListCtrl()->InsertPage(n, text, bSelect);
        if (!DoSetSelectionAfterInsertion(n, bSelect))
            page->Hide();
        return true;
    }
References GetBtnsListCtrl(), TabButtonsListCtrl::InsertPage(), and n.
MakeChangedEvent()
virtual void Tabbook::MakeChangedEvent (wxBookCtrlEvent & event) inline override protected virtual
    {
        event.SetEventType(wxEVT_BOOKCTRL_PAGE_CHANGED);
    }
OnNavigationKey()
void Tabbook::OnNavigationKey (wxNavigationKeyEvent & event) inline
    {
        if (event.IsWindowChange()) {
            // change pages
            AdvanceSelection(event.GetDirection());
        }
        else {
            // we get this event in 3 cases
            //
            // a) one of our pages might have generated it because the user TABbed
            // out from it in which case we should propagate the event upwards and
            // our parent will take care of setting the focus to prev/next sibling
            //
            // or
            //
            // b) the parent panel wants to give the focus to us so that we
            // forward it to our selected page. We can't deal with this in
            // OnSetFocus() because we don't know which direction the focus came
            // from in this case and so can't choose between setting the focus to
            // first or last panel child
            //
            // or
            //
            // c) we ourselves (see MSWTranslateMessage) generated the event
            //
            wxWindow* const parent = GetParent();
            // the wxObject* casts are required to avoid MinGW GCC 2.95.3 ICE
            const bool isFromParent = event.GetEventObject() == (wxObject*)parent;
            const bool isFromSelf = event.GetEventObject() == (wxObject*)this;
            const bool isForward = event.GetDirection();
            if (isFromSelf && !isForward)
            {
                // focus is currently on notebook tab and should leave
                // it backwards (Shift-TAB)
                event.SetCurrentFocus(this);
                parent->HandleWindowEvent(event);
            }
            else if (isFromParent || isFromSelf)
            {
                // no, it doesn't come from child, case (b) or (c): forward to a
                // page but only if entering notebook page (i.e. direction is
                // backwards (Shift-TAB) comething from out-of-notebook, or
                // direction is forward (TAB) from ourselves),
                if (m_selection != wxNOT_FOUND &&
                    (!event.GetDirection() || isFromSelf))
                {
                    // so that the page knows that the event comes from it's parent
                    // and is being propagated downwards
                    event.SetEventObject(this);
                    wxWindow* page = m_pages[m_selection];
                    if (!page->HandleWindowEvent(event))
                    {
                        page->SetFocus();
                    }
                    //else: page manages focus inside it itself
                }
                else // otherwise set the focus to the notebook itself
                {
                    SetFocus();
                }
            }
            else
            {
                // it comes from our child, case (a), pass to the parent, but only
                // if the direction is forwards. Otherwise set the focus to the
                // notebook itself. The notebook is always the 'first' control of a
                // page.
                if (!isForward)
                {
                    SetFocus();
                }
                else if (parent)
                {
                    event.SetCurrentFocus(this);
                    parent->HandleWindowEvent(event);
                }
            }
        }
    }
References SetFocus().
Referenced by Create().
RemovePage()
bool Tabbook::RemovePage (size_t n) inline
    {
        if (!wxBookCtrlBase::RemovePage(n))
            return false;
        SetSelection(0);
        return true;
    }
References n, and SetSelection().
Rescale()
void Tabbook::Rescale () inline
    {
        GetBtnsListCtrl()->Rescale();
    }
References GetBtnsListCtrl(), and TabButtonsListCtrl::Rescale().
Referenced by Slic3r::GUI::MonitorPanel::msw_rescale().
SetEffect()
void Tabbook::SetEffect (wxShowEffect effect) inline
    {
        SetEffects(effect, effect);
    }
References SetEffects().
SetEffects()
void Tabbook::SetEffects (wxShowEffect showEffect, wxShowEffect hideEffect) inline
    {
        m_showEffect = showEffect;
        m_hideEffect = hideEffect;
    }
References m_hideEffect, and m_showEffect.
Referenced by SetEffect().
SetEffectsTimeouts()
void Tabbook::SetEffectsTimeouts (unsigned showTimeout, unsigned hideTimeout) inline
    {
        m_showTimeout = showTimeout;
        m_hideTimeout = hideTimeout;
    }
References m_hideTimeout, and m_showTimeout.
Referenced by SetEffectTimeout().
SetEffectTimeout()
void Tabbook::SetEffectTimeout (unsigned timeout) inline
    {
        SetEffectsTimeouts(timeout, timeout);
    }
References SetEffectsTimeouts().
SetFocus()
virtual void Tabbook::SetFocus () inline override virtual
    {
        wxWindow* const page = GetCurrentPage();
        if (page)
            page->SetFocus();
    }
Referenced by OnNavigationKey().
SetPageImage() [1/2]
bool Tabbook::SetPageImage (size_t n, const std::string & bmp_name) inline
    {
        return GetBtnsListCtrl()->SetPageImage(n, bmp_name);
    }
References GetBtnsListCtrl(), n, and TabButtonsListCtrl::SetPageImage().
SetPageImage() [2/2]
virtual bool Tabbook::SetPageImage (size_t WXUNUSEDn, int WXUNUSEDimageId) inline override virtual
    {
        return false;
    }
SetPageText()
virtual bool Tabbook::SetPageText (size_t n, const wxString & strText) inline override virtual
    {
        wxCHECK_MSG(n < GetPageCount(), false, wxS("Invalid page"));
        GetBtnsListCtrl()->SetPageText(n, strText);
        return true;
    }
References GetBtnsListCtrl(), n, and TabButtonsListCtrl::SetPageText().
SetSelection()
virtual int Tabbook::SetSelection (size_t n) inline override virtual
    {
        GetBtnsListCtrl()->SetSelection(n);
        int ret = DoSetSelection(n, SetSelection_SendEvent);
        // check that only the selected page is visible and others are hidden:
        for (size_t page = 0; page < m_pages.size(); page++) {
            wxWindow* win_a = GetPage(page);
            wxWindow* win_b = GetPage(n);
            if (page != n && GetPage(page) != GetPage(n)) {
                m_pages[page]->Hide();
            }
        }
        return ret;
    }
References GetBtnsListCtrl(), n, and TabButtonsListCtrl::SetSelection().
Referenced by Create(), InsertNewPage(), and RemovePage().
ShowNewPage()
bool Tabbook::ShowNewPage (wxWindow * page) inline
    {
        return AddPage(page, wxString(), ""/*true *//* select it */);
    }
References AddPage().
UpdateSelectedPage()
virtual void Tabbook::UpdateSelectedPage (size_t WXUNUSEDnewsel) inline override protected virtual
    {
        // Nothing to do here, but must be overridden to avoid the assert in
        // the base class version.
    }
Member Data Documentation
m_ctrl
TabButtonsListCtrl* Tabbook::m_ctrl {nullptr} private
m_hideEffect
wxShowEffect Tabbook::m_hideEffect private
Referenced by DoShowPage(), Init(), and SetEffects().
m_hideTimeout
unsigned Tabbook::m_hideTimeout private
Referenced by DoShowPage(), Init(), and SetEffectsTimeouts().
m_showEffect
wxShowEffect Tabbook::m_showEffect private
Referenced by DoShowPage(), Init(), and SetEffects().
m_showTimeout
unsigned Tabbook::m_showTimeout private
Referenced by DoShowPage(), Init(), and SetEffectsTimeouts().
The documentation for this class was generated from the following file:
src/slic3r/GUI/Tabbook.hpp