OrcaSlicer: Slic3r::GUI::SideTools Class Reference
Slic3r::GUI::SideTools Class Reference
#include <src/slic3r/GUI/Widgets/SideTools.hpp>
Public Member Functions
SideTools (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~SideTools ()
void set_none_printer_mode ()
void on_timer (wxTimerEvent &event)
void set_current_printer_name (std::string dev_name)
void set_current_printer_signal (WifiSignal sign)
void start_interval ()
void stop_interval (wxTimerEvent &event)
bool is_in_interval ()
void msw_rescale ()
Protected Member Functions
void OnPaint (wxPaintEvent &event)
void render (wxDC &dc)
void doRender (wxDC &dc)
void on_mouse_enter (wxMouseEvent &evt)
void on_mouse_leave (wxMouseEvent &evt)
void on_mouse_left_down (wxMouseEvent &evt)
void on_mouse_left_up (wxMouseEvent &evt)
Protected Attributes
wxStaticBitmap * m_bitmap_info
wxStaticBitmap * m_bitmap_bind
wxTimer * m_intetval_timer {nullptr}
bool m_is_in_interval {false}
Private Attributes
WifiSignal m_wifi_type {WifiSignal::NONE}
wxString m_dev_name
bool m_hover {false}
bool m_click {false}
bool m_none_printer {true}
int last_printer_signal = 0
ScalableBitmap m_printing_img
ScalableBitmap m_arrow_img
ScalableBitmap m_none_printing_img
ScalableBitmap m_none_arrow_img
ScalableBitmap m_none_add_img
ScalableBitmap m_wifi_none_img
ScalableBitmap m_wifi_weak_img
ScalableBitmap m_wifi_middle_img
ScalableBitmap m_wifi_strong_img
Detailed Description
Constructor & Destructor Documentation
SideTools()
Slic3r::GUI::SideTools::SideTools (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{
    wxPanel::Create(parent, id, pos, wxSize(0, FromDIP(50)));
    Bind(wxEVT_PAINT, &SideTools::OnPaint, this);
    SetBackgroundColour(wxColour("#FEFFFF"));
    m_printing_img = ScalableBitmap(this, "printer", 16);
    m_arrow_img    = ScalableBitmap(this, "monitor_arrow", 14);
    m_none_printing_img = ScalableBitmap(this, "tab_monitor_active", 24);
    m_none_arrow_img    = ScalableBitmap(this, "monitor_none_arrow", 14);
    m_none_add_img      = ScalableBitmap(this, "monitor_none_add", 14);
    m_wifi_none_img     = ScalableBitmap(this, "monitor_signal_no", 18);
    m_wifi_weak_img     = ScalableBitmap(this, "monitor_signal_weak", 18);
    m_wifi_middle_img   = ScalableBitmap(this, "monitor_signal_middle", 18);
    m_wifi_strong_img   = ScalableBitmap(this, "monitor_signal_strong", 18);
    m_intetval_timer = new wxTimer();
    m_intetval_timer->SetOwner(this);
    this->Bind(wxEVT_TIMER, &SideTools::stop_interval, this);
    this->Bind(wxEVT_ENTER_WINDOW, &SideTools::on_mouse_enter, this);
    this->Bind(wxEVT_LEAVE_WINDOW, &SideTools::on_mouse_leave, this);
    this->Bind(wxEVT_LEFT_DOWN, &SideTools::on_mouse_left_down, this);
    this->Bind(wxEVT_LEFT_UP, &SideTools::on_mouse_left_up, this);
}
References m_arrow_img, m_intetval_timer, m_none_add_img, m_none_arrow_img, m_none_printing_img, m_printing_img, m_wifi_middle_img, m_wifi_none_img, m_wifi_strong_img, m_wifi_weak_img, on_mouse_enter(), on_mouse_leave(), on_mouse_left_down(), on_mouse_left_up(), OnPaint(), and stop_interval().
~SideTools()
Slic3r::GUI::SideTools::~SideTools ()
{ delete m_intetval_timer; }
References m_intetval_timer.
Member Function Documentation
doRender()
void Slic3r::GUI::SideTools::doRender (wxDC & dc) protected
{
    auto   left = FromDIP(15);
    wxSize size = GetSize();
    //if (m_none_printer) {
    //    dc.SetPen(SIDE_TOOLS_LIGHT_GREEN);
    //    dc.SetBrush(SIDE_TOOLS_LIGHT_GREEN);
    //    dc.DrawRectangle(0, 0, size.x, size.y);
    //}
    if (m_none_printer) {
        dc.SetPen(SIDE_TOOLS_BRAND);
        dc.SetBrush(SIDE_TOOLS_BRAND);
        dc.DrawRectangle(0, 0, size.x, size.y);
        dc.DrawBitmap(m_none_printing_img.bmp(), left, (size.y - m_none_printing_img.GetBmpSize().y) / 2);
        left += (m_none_printing_img.GetBmpSize().x + FromDIP(15));
        dc.DrawBitmap(m_none_arrow_img.bmp(), left, (size.y - m_none_arrow_img.GetBmpSize().y) / 2);
        left += (m_none_arrow_img.GetBmpSize().x + FromDIP(6));
        dc.SetFont(::Label::Body_14);
        dc.SetBackgroundMode(wxTRANSPARENT);
        dc.SetTextForeground(*wxWHITE);
        wxString no_printer_str = _L("No printer");
        auto sizet = dc.GetTextExtent(no_printer_str);
        auto left_add_bitmap = size.x - FromDIP(30) - m_wifi_none_img.GetBmpSize().x - m_none_add_img.GetBmpSize().x;
        auto size_width = left_add_bitmap - left;
        if (sizet.x > size_width) {
            wxString temp_str = wxEmptyString;
            for (auto i = 0; i < no_printer_str.Len(); i++) {
                if (dc.GetTextExtent(L("...") + temp_str).x < size_width) {
                    temp_str += no_printer_str[i];
                }
                else {
                    break;
                }
            }
            no_printer_str = temp_str + L("...");
        }
        dc.DrawText(no_printer_str, wxPoint(left, (size.y - sizet.y) / 2));
        left = size.x - FromDIP(30) - m_wifi_none_img.GetBmpSize().x;
        dc.DrawBitmap(m_none_add_img.bmp(), left, (size.y - m_none_add_img.GetBmpSize().y) / 2);
    } else {
        dc.DrawBitmap(m_printing_img.bmp(), left, (size.y - m_printing_img.GetBmpSize().y) / 2);
        left += (m_printing_img.GetBmpSize().x + FromDIP(5));
        dc.DrawBitmap(m_arrow_img.bmp(), left, (size.y - m_arrow_img.GetBmpSize().y) / 2);
        left += (m_arrow_img.GetBmpSize().x + FromDIP(6));
        dc.SetFont(::Label::Body_14);
        dc.SetBackgroundMode(wxTRANSPARENT);
        dc.SetTextForeground(StateColor::darkModeColorFor(SIDE_TOOLS_GREY900));
        auto sizet = dc.GetTextExtent(m_dev_name);
        auto text_end = size.x - m_wifi_none_img.GetBmpSize().x - 20;
        std::string finally_name = m_dev_name.ToStdString();
        if (sizet.x > (text_end - left)) {
            auto limit_width = text_end - left - dc.GetTextExtent("...").x - 20;
            for (auto i = 0; i < m_dev_name.length(); i++) {
                auto curr_width = dc.GetTextExtent(m_dev_name.substr(0, i));
                if (curr_width.x >= limit_width) {
                    finally_name = (m_dev_name.substr(0, i) + wxString("...")).ToStdString();
                    break;
                }
            }
        }
        dc.DrawText(finally_name, wxPoint(left, (size.y - sizet.y) / 2));
        left = size.x - FromDIP(18) - m_wifi_none_img.GetBmpSize().x;
        if (m_wifi_type == WifiSignal::NONE) dc.DrawBitmap(m_wifi_none_img.bmp(), left, (size.y - m_wifi_none_img.GetBmpSize().y) / 2);
        if (m_wifi_type == WifiSignal::WEAK) dc.DrawBitmap(m_wifi_weak_img.bmp(), left, (size.y - m_wifi_weak_img.GetBmpSize().y) / 2);
        if (m_wifi_type == WifiSignal::MIDDLE) dc.DrawBitmap(m_wifi_middle_img.bmp(), left, (size.y - m_wifi_middle_img.GetBmpSize().y) / 2);
        if (m_wifi_type == WifiSignal::STRONG) dc.DrawBitmap(m_wifi_strong_img.bmp(), left, (size.y - m_wifi_strong_img.GetBmpSize().y) / 2);
    }
    if (m_hover) {
        dc.SetPen(SIDE_TOOLS_BRAND);
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawRectangle(0, 0, size.x, size.y);
    }
}
References _L, ScalableBitmap::bmp(), Label::Body_14, StateColor::darkModeColorFor(), ScalableBitmap::GetBmpSize(), L, m_arrow_img, m_dev_name, m_hover, m_none_add_img, m_none_arrow_img, m_none_printer, m_none_printing_img, m_printing_img, m_wifi_middle_img, m_wifi_none_img, m_wifi_strong_img, m_wifi_type, m_wifi_weak_img, MIDDLE, NONE, SIDE_TOOLS_BRAND, SIDE_TOOLS_GREY900, size, STRONG, and WEAK.
Referenced by OnPaint(), and render().
is_in_interval()
bool Slic3r::GUI::SideTools::is_in_interval ()
{
    return m_is_in_interval;
}
References m_is_in_interval.
Referenced by Slic3r::GUI::MonitorPanel::on_printer_clicked().
msw_rescale()
void Slic3r::GUI::SideTools::msw_rescale ()
{
    Refresh();
}
Referenced by Slic3r::GUI::MonitorPanel::msw_rescale().
on_mouse_enter()
void Slic3r::GUI::SideTools::on_mouse_enter (wxMouseEvent & evt) protected
{
    m_hover = true;
    Refresh();
}
References m_hover.
Referenced by SideTools().
on_mouse_leave()
void Slic3r::GUI::SideTools::on_mouse_leave (wxMouseEvent & evt) protected
{
    m_hover = false;
    Refresh();
}
References m_hover.
Referenced by SideTools().
on_mouse_left_down()
void Slic3r::GUI::SideTools::on_mouse_left_down (wxMouseEvent & evt) protected
{
    m_click = true;
    Refresh();
}
References m_click.
Referenced by SideTools().
on_mouse_left_up()
void Slic3r::GUI::SideTools::on_mouse_left_up (wxMouseEvent & evt) protected
{
     m_click = false;
     Refresh();
}
References m_click.
Referenced by SideTools().
on_timer()
void Slic3r::GUI::SideTools::on_timer (wxTimerEvent & event)
{
}
OnPaint()
void Slic3r::GUI::SideTools::OnPaint (wxPaintEvent & event) protected
{
    wxPaintDC dc(this);
    doRender(dc);
}
References doRender().
Referenced by SideTools().
render()
void Slic3r::GUI::SideTools::render (wxDC & dc) protected
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
set_current_printer_name()
void Slic3r::GUI::SideTools::set_current_printer_name (std::string dev_name)
{
     m_none_printer = false;
     m_dev_name     = from_u8(dev_name);
     Refresh();
}
References Slic3r::GUI::from_u8(), m_dev_name, and m_none_printer.
Referenced by Slic3r::GUI::MonitorPanel::update_status().
set_current_printer_signal()
void Slic3r::GUI::SideTools::set_current_printer_signal (WifiSignal sign)
{
     if (last_printer_signal == sign) return;
     last_printer_signal = sign;
     m_none_printer = false;
     m_wifi_type    = sign;
     Refresh();
}
References last_printer_signal, m_none_printer, m_wifi_type, and sign().
Referenced by Slic3r::GUI::MonitorPanel::show_status(), and Slic3r::GUI::MonitorPanel::update_status().
set_none_printer_mode()
void Slic3r::GUI::SideTools::set_none_printer_mode ()
{
    m_none_printer = true;
    Refresh();
}
References m_none_printer.
Referenced by Slic3r::GUI::MonitorPanel::show_status(), and Slic3r::GUI::MonitorPanel::update_side_panel().
start_interval()
void Slic3r::GUI::SideTools::start_interval ()
{
    m_intetval_timer->Start(SIDE_TOOL_CLICK_INTERVAL);
    m_is_in_interval = true;
}
References m_intetval_timer, m_is_in_interval, and SIDE_TOOL_CLICK_INTERVAL.
Referenced by Slic3r::GUI::MonitorPanel::MonitorPanel().
stop_interval()
void Slic3r::GUI::SideTools::stop_interval (wxTimerEvent & event)
{
    m_is_in_interval = false;
    m_intetval_timer->Stop();
}
References m_intetval_timer, and m_is_in_interval.
Referenced by SideTools().
Member Data Documentation
last_printer_signal
int Slic3r::GUI::SideTools::last_printer_signal = 0 private
Referenced by set_current_printer_signal().
m_arrow_img
ScalableBitmap Slic3r::GUI::SideTools::m_arrow_img private
Referenced by SideTools(), and doRender().
m_bitmap_bind
wxStaticBitmap* Slic3r::GUI::SideTools::m_bitmap_bind protected
m_bitmap_info
wxStaticBitmap* Slic3r::GUI::SideTools::m_bitmap_info protected
m_click
bool Slic3r::GUI::SideTools::m_click {false} private
Referenced by on_mouse_left_down(), and on_mouse_left_up().
m_dev_name
wxString Slic3r::GUI::SideTools::m_dev_name private
Referenced by doRender(), and set_current_printer_name().
m_hover
bool Slic3r::GUI::SideTools::m_hover {false} private
Referenced by doRender(), on_mouse_enter(), and on_mouse_leave().
m_intetval_timer
wxTimer* Slic3r::GUI::SideTools::m_intetval_timer {nullptr} protected
Referenced by SideTools(), ~SideTools(), start_interval(), and stop_interval().
m_is_in_interval
bool Slic3r::GUI::SideTools::m_is_in_interval {false} protected
Referenced by is_in_interval(), start_interval(), and stop_interval().
m_none_add_img
ScalableBitmap Slic3r::GUI::SideTools::m_none_add_img private
Referenced by SideTools(), and doRender().
m_none_arrow_img
ScalableBitmap Slic3r::GUI::SideTools::m_none_arrow_img private
Referenced by SideTools(), and doRender().
m_none_printer
bool Slic3r::GUI::SideTools::m_none_printer {true} private
Referenced by doRender(), set_current_printer_name(), set_current_printer_signal(), and set_none_printer_mode().
m_none_printing_img
ScalableBitmap Slic3r::GUI::SideTools::m_none_printing_img private
Referenced by SideTools(), and doRender().
m_printing_img
ScalableBitmap Slic3r::GUI::SideTools::m_printing_img private
Referenced by SideTools(), and doRender().
m_wifi_middle_img
ScalableBitmap Slic3r::GUI::SideTools::m_wifi_middle_img private
Referenced by SideTools(), and doRender().
m_wifi_none_img
ScalableBitmap Slic3r::GUI::SideTools::m_wifi_none_img private
Referenced by SideTools(), and doRender().
m_wifi_strong_img
ScalableBitmap Slic3r::GUI::SideTools::m_wifi_strong_img private
Referenced by SideTools(), and doRender().
m_wifi_type
WifiSignal Slic3r::GUI::SideTools::m_wifi_type {WifiSignal::NONE} private
Referenced by doRender(), and set_current_printer_signal().
m_wifi_weak_img
ScalableBitmap Slic3r::GUI::SideTools::m_wifi_weak_img private
Referenced by SideTools(), and doRender().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/SideTools.hpp
src/slic3r/GUI/Widgets/SideTools.cpp