OrcaSlicer: Slic3r::FillLightning::Generator Class Reference
Slic3r::FillLightning::Generator Class Reference
#include <src/libslic3r/Fill/Lightning/Generator.hpp>
Public Member Functions
Generator (const PrintObject &print_object, const std::function< void()> &throw_on_cancel_callback)
const Layer & getTreesForLayer (const size_t &layer_id) const
std::vector< Polygons > & Overhangs ()
float infilll_extrusion_width () const
Generator (PrintObject *m_object, std::vector< Polygons > &contours, std::vector< Polygons > &overhangs, const std::function< void()> &throw_on_cancel_callback, float density=0.15)
Protected Member Functions
void generateInitialInternalOverhangs (const PrintObject &print_object, const std::function< void()> &throw_on_cancel_callback)
void generateTrees (const PrintObject &print_object, const std::function< void()> &throw_on_cancel_callback)
void generateTreesforSupport (std::vector< Polygons > &contours, const std::function< void()> &throw_on_cancel_callback)
Protected Attributes
float m_infill_extrusion_width
coord_t m_supporting_radius
coord_t m_wall_supporting_radius
coord_t m_prune_length
coord_t m_straightening_max_distance
std::vector< Polygons > m_overhang_per_layer
std::vector< Layer > m_lightning_layers
std::vector< BoundingBox > bboxs
Detailed Description
Generates the Lightning Infill pattern.
The lightning infill pattern is designed to use a minimal amount of material to support the top skin of the print, while still printing with reasonably consistently flowing lines. It sacrifices strength completely in favour of top surface quality and reduced print time / material usage.
Lightning Infill is so named because the patterns it creates resemble a forked path with one main path and many small lines on the side. These paths grow out from the sides of the model just below where the top surface needs to be supported from the inside, so that minimal material is needed.
This pattern is based on a paper called "Ribbed Support Vaults for 3D Printing of Hollowed Objects" by Tricard, Claux and Lefebvre: https://www.researchgate.net/publication/333808588_Ribbed_Support_Vaults_for_3D_Printing_of_Hollowed_Objects
Constructor & Destructor Documentation
Generator() [1/2]
Slic3r::FillLightning::Generator::Generator (const PrintObject & print_object, const std::function< void()> & throw_on_cancel_callback) explicit
Create a generator to fill a certain mesh with infill.
This generator will pre-compute things in preparation of generating Lightning Infill for the infill areas in that mesh. The infill areas must already be calculated at this point.
{
    const PrintConfig         &print_config         = print_object.print()->config();
    const PrintObjectConfig   &object_config        = print_object.config();
    const PrintRegionConfig   &region_config        = print_object.shared_regions()->all_regions.front()->config();
    const std::vector<double> &nozzle_diameters     = print_config.nozzle_diameter.values;
    double                     max_nozzle_diameter  = *std::max_element(nozzle_diameters.begin(), nozzle_diameters.end());
//    const int                  infill_extruder      = region_config.infill_extruder.value;
    const double               default_infill_extrusion_width = Flow::auto_extrusion_width(FlowRole::frInfill, float(max_nozzle_diameter));
    // Note: There's not going to be a layer below the first one, so the 'initial layer height' doesn't have to be taken into account.
    const double               layer_thickness      = scaled<double>(object_config.layer_height.value);
    m_infill_extrusion_width = scaled<float>(region_config.sparse_infill_line_width.get_abs_value(max_nozzle_diameter));
    m_supporting_radius = coord_t(m_infill_extrusion_width) * 100 / region_config.sparse_infill_density;
    const double lightning_infill_overhang_angle      = M_PI / 4; // 45 degrees
    const double lightning_infill_prune_angle         = M_PI / 4; // 45 degrees
    const double lightning_infill_straightening_angle = M_PI / 4; // 45 degrees
    m_wall_supporting_radius                          = coord_t(layer_thickness * std::tan(lightning_infill_overhang_angle));
    m_prune_length                                    = coord_t(layer_thickness * std::tan(lightning_infill_prune_angle));
    m_straightening_max_distance                      = coord_t(layer_thickness * std::tan(lightning_infill_straightening_angle));
    generateInitialInternalOverhangs(print_object, throw_on_cancel_callback);
    generateTrees(print_object, throw_on_cancel_callback);
}
References Slic3r::PrintObjectRegions::all_regions, Slic3r::Flow::auto_extrusion_width(), Slic3r::PrintObject::config(), Slic3r::Print::config(), Slic3r::frInfill, generateInitialInternalOverhangs(), generateTrees(), m_infill_extrusion_width, M_PI, m_prune_length, m_straightening_max_distance, m_supporting_radius, m_wall_supporting_radius, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::print(), Slic3r::PrintObjectConfig, Slic3r::PrintRegionConfig, and Slic3r::PrintObject::shared_regions().
Generator() [2/2]
Slic3r::FillLightning::Generator::Generator (PrintObject * m_object, std::vector< Polygons > & contours, std::vector< Polygons > & overhangs, const std::function< void()> & throw_on_cancel_callback, float density = 0.15)
{
    const PrintConfig         &print_config         = m_object->print()->config();
    const PrintObjectConfig   &object_config        = m_object->config();
    const PrintRegionConfig   &region_config        = m_object->shared_regions()->all_regions.front()->config();
    const std::vector<double> &nozzle_diameters     = print_config.nozzle_diameter.values;
    double                     max_nozzle_diameter  = *std::max_element(nozzle_diameters.begin(), nozzle_diameters.end());
//    const int                  infill_extruder      = region_config.infill_extruder.value;
    const double               default_infill_extrusion_width = Flow::auto_extrusion_width(FlowRole::frInfill, float(max_nozzle_diameter));
    // Note: There's not going to be a layer below the first one, so the 'initial layer height' doesn't have to be taken into account.
    const double               layer_thickness      = scaled<double>(object_config.layer_height.value);
    m_infill_extrusion_width = scaled<float>(region_config.sparse_infill_line_width.get_abs_value(max_nozzle_diameter));
    //m_supporting_radius: against to the density of lightning, failures may happen if set to high density
    //higher density lightning makes support harder, more time-consuming on computing and printing, but more reliable on supporting overhangs
    //lower density lightning performs opposite
    //TODO: decide whether enable density controller in advanced options or not
    density = std::max(0.15f, density);
    m_supporting_radius = coord_t(m_infill_extrusion_width) / density;
    const double lightning_infill_overhang_angle = M_PI / 4; // 45 degrees
    const double lightning_infill_prune_angle = M_PI / 4; // 45 degrees
    const double lightning_infill_straightening_angle = M_PI / 4; // 45 degrees
    m_wall_supporting_radius = layer_thickness * std::tan(lightning_infill_overhang_angle);
    m_prune_length = layer_thickness * std::tan(lightning_infill_prune_angle);
    m_straightening_max_distance = layer_thickness * std::tan(lightning_infill_straightening_angle);
    m_overhang_per_layer = overhangs;
    generateTreesforSupport(contours, throw_on_cancel_callback);
    //for (size_t i = 0; i < overhangs.size(); i++)
    //{
    //    auto svg = draw_two_overhangs_to_svg(i, to_expolygons(contours[i]), to_expolygons(overhangs[i]));
    //    for (auto& root : m_lightning_layers[i].tree_roots)
    //        root->draw_tree(svg);
    //}
}
References Slic3r::PrintObjectRegions::all_regions, Slic3r::Flow::auto_extrusion_width(), Slic3r::PrintObject::config(), Slic3r::Print::config(), Slic3r::frInfill, generateTreesforSupport(), m_infill_extrusion_width, m_overhang_per_layer, M_PI, m_prune_length, m_straightening_max_distance, m_supporting_radius, m_wall_supporting_radius, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::print(), Slic3r::PrintObjectConfig, Slic3r::PrintRegionConfig, and Slic3r::PrintObject::shared_regions().
Member Function Documentation
generateInitialInternalOverhangs()
void Slic3r::FillLightning::Generator::generateInitialInternalOverhangs (const PrintObject & print_object, const std::function< void()> & throw_on_cancel_callback) protected
Calculate the overhangs above the infill areas that need to be supported by infill.
Normally, overhangs are only generated for the outside of the model and only when support is generated. For this pattern, we also need to generate overhang areas for the inside of the model.
{
    m_overhang_per_layer.resize(print_object.layers().size());
    Polygons infill_area_above;
    //Iterate from top to bottom, to subtract the overhang areas above from the overhang areas on the layer below, to get only overhang in the top layer where it is overhanging.
    for (int layer_nr = int(print_object.layers().size()) - 1; layer_nr >= 0; --layer_nr) {
        throw_on_cancel_callback();
        Polygons infill_area_here;
        for (const LayerRegion* layerm : print_object.get_layer(layer_nr)->regions())
            for (const Surface& surface : layerm->fill_surfaces.surfaces)
                if (surface.surface_type == stInternal || surface.surface_type == stInternalVoid)
                    append(infill_area_here, to_polygons(surface.expolygon));
        //Remove the part of the infill area that is already supported by the walls.
        Polygons overhang = diff(offset(infill_area_here, -float(m_wall_supporting_radius)), infill_area_above);
        m_overhang_per_layer[layer_nr] = overhang;
        infill_area_above = std::move(infill_area_here);
    }
}
References Slic3r::append(), Slic3r::diff(), Slic3r::PrintObject::get_layer(), Slic3r::PrintObject::layers(), m_overhang_per_layer, m_wall_supporting_radius, Slic3r::offset(), Slic3r::Layer::regions(), Slic3r::ConstVectorOfPtrsAdaptor< T >::size(), Slic3r::stInternal, Slic3r::stInternalVoid, and Slic3r::to_polygons().
Referenced by Generator().
generateTrees()
void Slic3r::FillLightning::Generator::generateTrees (const PrintObject & print_object, const std::function< void()> & throw_on_cancel_callback) protected
Calculate the tree structure of all layers.
{
    m_lightning_layers.resize(print_object.layers().size());
    bboxs.resize(print_object.layers().size());
    std::vector<Polygons> infill_outlines(print_object.layers().size(), Polygons());
    // For-each layer from top to bottom:
    for (int layer_id = int(print_object.layers().size()) - 1; layer_id >= 0; layer_id--) {
        throw_on_cancel_callback();
        for (const LayerRegion *layerm : print_object.get_layer(layer_id)->regions())
            for (const Surface &surface : layerm->fill_surfaces.surfaces)
                if (surface.surface_type == stInternal || surface.surface_type == stInternalVoid)
                    append(infill_outlines[layer_id], to_polygons(surface.expolygon));
    }
    // For various operations its beneficial to quickly locate nearby features on the polygon:
    const size_t top_layer_id = print_object.layers().size() - 1;
    EdgeGrid::Grid outlines_locator(get_extents(infill_outlines[top_layer_id]).inflated(SCALED_EPSILON));
    outlines_locator.create(infill_outlines[top_layer_id], locator_cell_size);
    // For-each layer from top to bottom:
    for (int layer_id = int(top_layer_id); layer_id >= 0; layer_id--) {
        throw_on_cancel_callback();
        Layer             &current_lightning_layer = m_lightning_layers[layer_id];
        const Polygons    &current_outlines        = infill_outlines[layer_id];
        const BoundingBox &current_outlines_bbox   = get_extents(current_outlines);
        bboxs[layer_id] = get_extents(current_outlines);
        // register all trees propagated from the previous layer as to-be-reconnected
        std::vector<NodeSPtr> to_be_reconnected_tree_roots = current_lightning_layer.tree_roots;
        current_lightning_layer.generateNewTrees(m_overhang_per_layer[layer_id], current_outlines, current_outlines_bbox, outlines_locator, m_supporting_radius, m_wall_supporting_radius, throw_on_cancel_callback);
        current_lightning_layer.reconnectRoots(to_be_reconnected_tree_roots, current_outlines, current_outlines_bbox, outlines_locator, m_supporting_radius, m_wall_supporting_radius);
        // Initialize trees for next lower layer from the current one.
        if (layer_id == 0)
            return;
        const Polygons &below_outlines      = infill_outlines[layer_id - 1];
        BoundingBox     below_outlines_bbox = get_extents(below_outlines).inflated(SCALED_EPSILON);
        if (const BoundingBox &outlines_locator_bbox = outlines_locator.bbox(); outlines_locator_bbox.defined)
            below_outlines_bbox.merge(outlines_locator_bbox);
        if (!current_lightning_layer.tree_roots.empty())
            below_outlines_bbox.merge(get_extents(current_lightning_layer.tree_roots).inflated(SCALED_EPSILON));
        outlines_locator.set_bbox(below_outlines_bbox);
        outlines_locator.create(below_outlines, locator_cell_size);
        std::vector<NodeSPtr>& lower_trees = m_lightning_layers[layer_id - 1].tree_roots;
        for (auto& tree : current_lightning_layer.tree_roots)
            tree->propagateToNextLayer(lower_trees, below_outlines, outlines_locator, m_prune_length, m_straightening_max_distance, locator_cell_size / 2);
    }
}
References Slic3r::append(), Slic3r::EdgeGrid::Grid::bbox(), bboxs, Slic3r::EdgeGrid::Grid::create(), Slic3r::FillLightning::Layer::generateNewTrees(), Slic3r::FillLightning::get_extents(), Slic3r::PrintObject::get_layer(), Slic3r::BoundingBox::inflated(), Slic3r::PrintObject::layers(), Slic3r::FillLightning::locator_cell_size, m_lightning_layers, m_overhang_per_layer, m_prune_length, m_straightening_max_distance, m_supporting_radius, m_wall_supporting_radius, Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::FillLightning::Layer::reconnectRoots(), Slic3r::Layer::regions(), SCALED_EPSILON, Slic3r::EdgeGrid::Grid::set_bbox(), Slic3r::ConstVectorOfPtrsAdaptor< T >::size(), Slic3r::stInternal, Slic3r::stInternalVoid, Slic3r::to_polygons(), and Slic3r::FillLightning::Layer::tree_roots.
Referenced by Generator().
generateTreesforSupport()
void Slic3r::FillLightning::Generator::generateTreesforSupport (std::vector< Polygons > & contours, const std::function< void()> & throw_on_cancel_callback) protected
{
    if (contours.empty()) return;
    m_lightning_layers.resize(contours.size());
    bboxs.resize(contours.size());
    // For various operations its beneficial to quickly locate nearby features on the polygon:
    const size_t top_layer_id = contours.size() - 1;
    EdgeGrid::Grid outlines_locator(get_extents(contours[top_layer_id]).inflated(SCALED_EPSILON));
    outlines_locator.create(contours[top_layer_id], locator_cell_size);
    // For-each layer from top to bottom:
    for (int layer_id = int(top_layer_id); layer_id >= 0; layer_id--) {
    throw_on_cancel_callback();
        Layer& current_lightning_layer = m_lightning_layers[layer_id];
        const Polygons& current_outlines = contours[layer_id];
        const BoundingBox& current_outlines_bbox = get_extents(current_outlines);
        bboxs[layer_id] = get_extents(current_outlines);
        // register all trees propagated from the previous layer as to-be-reconnected
        std::vector<NodeSPtr> to_be_reconnected_tree_roots = current_lightning_layer.tree_roots;
        current_lightning_layer.generateNewTrees(m_overhang_per_layer[layer_id], current_outlines, current_outlines_bbox, outlines_locator, m_supporting_radius, m_wall_supporting_radius, throw_on_cancel_callback);
        current_lightning_layer.reconnectRoots(to_be_reconnected_tree_roots, current_outlines, current_outlines_bbox, outlines_locator, m_supporting_radius, m_wall_supporting_radius);
        // Initialize trees for next lower layer from the current one.
        if (layer_id == 0)
            return;
        const Polygons& below_outlines = contours[layer_id - 1];
        BoundingBox     below_outlines_bbox = get_extents(below_outlines).inflated(SCALED_EPSILON);
        if (const BoundingBox& outlines_locator_bbox = outlines_locator.bbox(); outlines_locator_bbox.defined)
            below_outlines_bbox.merge(outlines_locator_bbox);
        if (!current_lightning_layer.tree_roots.empty())
            below_outlines_bbox.merge(get_extents(current_lightning_layer.tree_roots).inflated(SCALED_EPSILON));
        outlines_locator.set_bbox(below_outlines_bbox);
        outlines_locator.create(below_outlines, locator_cell_size);
        std::vector<NodeSPtr>& lower_trees = m_lightning_layers[layer_id - 1].tree_roots;
        for (auto& tree : current_lightning_layer.tree_roots)
            tree->propagateToNextLayer(lower_trees, below_outlines, outlines_locator, m_prune_length, m_straightening_max_distance, locator_cell_size / 2);
    }
}
References Slic3r::EdgeGrid::Grid::bbox(), bboxs, Slic3r::EdgeGrid::Grid::create(), Slic3r::FillLightning::Layer::generateNewTrees(), Slic3r::FillLightning::get_extents(), Slic3r::BoundingBox::inflated(), Slic3r::FillLightning::locator_cell_size, m_lightning_layers, m_overhang_per_layer, m_prune_length, m_straightening_max_distance, m_supporting_radius, m_wall_supporting_radius, Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::FillLightning::Layer::reconnectRoots(), SCALED_EPSILON, Slic3r::EdgeGrid::Grid::set_bbox(), and Slic3r::FillLightning::Layer::tree_roots.
Referenced by Generator().
getTreesForLayer()
const Layer & Slic3r::FillLightning::Generator::getTreesForLayer (const size_t & layer_id) const
Get a tree of paths generated for a certain layer of the mesh.
This tree represents the paths that must be traced to print the infill.
Parameters
layer_id The layer number to get the path tree for. This is within the range of layers of the mesh (not the global layer numbers).
Returns
A tree structure representing paths to print to create the Lightning Infill pattern.
{
    assert(layer_id < m_lightning_layers.size());
    return m_lightning_layers[layer_id];
}
References m_lightning_layers.
Referenced by Slic3r::FillLightning::Filler::_fill_surface_single().
infilll_extrusion_width()
float Slic3r::FillLightning::Generator::infilll_extrusion_width () const inline
{ return m_infill_extrusion_width; }
References m_infill_extrusion_width.
Overhangs()
std::vector< Polygons > & Slic3r::FillLightning::Generator::Overhangs () inline
{ return m_overhang_per_layer; }
References m_overhang_per_layer.
Member Data Documentation
bboxs
std::vector<BoundingBox> Slic3r::FillLightning::Generator::bboxs protected
Referenced by generateTrees(), and generateTreesforSupport().
m_infill_extrusion_width
float Slic3r::FillLightning::Generator::m_infill_extrusion_width protected
Referenced by Generator(), Generator(), and infilll_extrusion_width().
m_lightning_layers
std::vector<Layer> Slic3r::FillLightning::Generator::m_lightning_layers protected
For each layer, the generated lightning paths.
This is generated by generateTrees.
Referenced by generateTrees(), generateTreesforSupport(), and getTreesForLayer().
m_overhang_per_layer
std::vector<Polygons> Slic3r::FillLightning::Generator::m_overhang_per_layer protected
For each layer, the overhang that needs to be supported by the pattern.
This is generated by generateInitialInternalOverhangs.
Referenced by Generator(), generateInitialInternalOverhangs(), generateTrees(), generateTreesforSupport(), and Overhangs().
m_prune_length
coord_t Slic3r::FillLightning::Generator::m_prune_length protected
How far each piece of infill can support other infill in the layer above.
This may be different than supporting_radius, because the infill is printed with one end floating in mid-air. This endpoint will sag more, so an infill line may need to be supported more than a skin line.
Referenced by Generator(), Generator(), generateTrees(), and generateTreesforSupport().
m_straightening_max_distance
coord_t Slic3r::FillLightning::Generator::m_straightening_max_distance protected
How far a line may be shifted in order to straighten the line out.
Straightening the line reduces material and time usage and reduces accelerations needed to print the pattern. However it makes the infill weak if lines are partially suspended next to the line on the previous layer.
Referenced by Generator(), Generator(), generateTrees(), and generateTreesforSupport().
m_supporting_radius
coord_t Slic3r::FillLightning::Generator::m_supporting_radius protected
How far each piece of infill can support skin in the layer above.
Referenced by Generator(), Generator(), generateTrees(), and generateTreesforSupport().
m_wall_supporting_radius
coord_t Slic3r::FillLightning::Generator::m_wall_supporting_radius protected
How far a wall can support the wall above it. If a wall completely supports the wall above it, no infill needs to support that.
This is similar to the overhang distance calculated for support. It is determined by the lightning_infill_overhang_angle setting.
Referenced by Generator(), Generator(), generateInitialInternalOverhangs(), generateTrees(), and generateTreesforSupport().
The documentation for this class was generated from the following files:
src/libslic3r/Fill/Lightning/Generator.hpp
src/libslic3r/Fill/Lightning/Generator.cpp