OrcaSlicer: Slic3r::GUI::AmsIntroducePopup Class Reference
Slic3r::GUI::AmsIntroducePopup Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
AmsIntroducePopup (wxWindow *parent)
~AmsIntroducePopup ()
void set_mode (bool enable_ams)
void paintEvent (wxPaintEvent &evt)
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Public Attributes
bool is_enable_ams = {false}
Label * m_staticText_top
Label * m_staticText_bottom
wxStaticBitmap * m_img_enable_ams
wxStaticBitmap * m_img_disable_ams
Detailed Description
Constructor & Destructor Documentation
AmsIntroducePopup()
Slic3r::GUI::AmsIntroducePopup::AmsIntroducePopup (wxWindow * parent)
:PopupWindow(parent, wxBORDER_NONE)
{
    Bind(wxEVT_PAINT, &AmsIntroducePopup::paintEvent, this);
    SetBackgroundColour(*wxWHITE);
    SetMinSize(wxSize(FromDIP(200), FromDIP(200)));
    SetMaxSize(wxSize(FromDIP(200), FromDIP(200)));
    wxBoxSizer* bSizer4 = new wxBoxSizer(wxVERTICAL);
    m_staticText_top = new Label(this, _L("Do not Enable AMS"));
    m_staticText_top->SetFont(::Label::Head_13);
   // m_staticText_top->SetForegroundColour(wxColour(0x323A3D));
    m_staticText_top->Wrap(-1);
    bSizer4->Add(m_staticText_top, 0, wxALL, 5);
    m_staticText_bottom =  new Label(this, _L("Print using materials mounted on the back of the case"));
    m_staticText_bottom->Wrap(-1);
    m_staticText_bottom->SetFont(::Label::Body_13);
    m_staticText_bottom->SetForegroundColour(wxColour(0x6B6B6B));
    bSizer4->Add(m_staticText_bottom, 0, wxALL, 5);
    wxBoxSizer* bSizer5;
    bSizer5 = new wxBoxSizer(wxHORIZONTAL);
    m_img_enable_ams = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("monitor_upgrade_ams", this, FromDIP(140)), wxDefaultPosition, wxDefaultSize, 0);
    m_img_disable_ams = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("disable_ams_demo_icon", this, FromDIP(110)), wxDefaultPosition, wxDefaultSize, 0);
    m_img_enable_ams->SetMinSize(wxSize(FromDIP(96), FromDIP(110)));
    m_img_disable_ams->SetMinSize(wxSize(FromDIP(96), FromDIP(110)));
    bSizer5->Add(m_img_enable_ams, 0, wxALIGN_CENTER, 0);
    bSizer5->Add(m_img_disable_ams, 0, wxALIGN_CENTER, 0);
    m_img_disable_ams->Hide();
    m_img_disable_ams->Hide();
    bSizer4->Add(bSizer5, 0, wxALIGN_CENTER | wxBOTTOM, FromDIP(1));
    SetSizer(bSizer4);
    Layout();
    Fit();
    wxGetApp().UpdateDarkUIWin(this);
}
References _L, Label::Body_13, create_scaled_bitmap(), Label::Head_13, m_img_disable_ams, m_img_enable_ams, m_staticText_bottom, m_staticText_top, paintEvent(), and Label::Wrap().
~AmsIntroducePopup()
Slic3r::GUI::AmsIntroducePopup::~AmsIntroducePopup () inline
{};
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
OnDismiss()
void Slic3r::GUI::AmsIntroducePopup::OnDismiss () virtual
{}
paintEvent()
void Slic3r::GUI::AmsIntroducePopup::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRoundedRectangle(0, 0, GetSize().x, GetSize().y, 0);
}
Referenced by AmsIntroducePopup().
ProcessLeftDown()
bool Slic3r::GUI::AmsIntroducePopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
set_mode()
void Slic3r::GUI::AmsIntroducePopup::set_mode (bool enable_ams)
{
    if (enable_ams) {
        m_staticText_top->SetLabelText(_L("Enable AMS"));
        m_staticText_bottom->SetLabelText(_L("Print with filaments in ams"));
        m_img_enable_ams->Show();
        m_img_disable_ams->Hide();
    }
    else {
        m_staticText_top->SetLabelText(_L("Do not Enable AMS"));
        m_staticText_bottom->SetLabelText(_L("Print with filaments mounted on the back of the chassis"));
        m_staticText_bottom->SetMinSize(wxSize(FromDIP(180), -1));
        m_staticText_bottom->Wrap(FromDIP(180));
        m_img_enable_ams->Hide();
        m_img_disable_ams->Show();
    }
    Layout();
    Fit();
}
References _L, m_img_disable_ams, m_img_enable_ams, m_staticText_bottom, m_staticText_top, and Label::Wrap().
Referenced by Slic3r::GUI::AMSControl::AMSControl().
Member Data Documentation
is_enable_ams
bool Slic3r::GUI::AmsIntroducePopup::is_enable_ams = {false}
m_img_disable_ams
wxStaticBitmap* Slic3r::GUI::AmsIntroducePopup::m_img_disable_ams
Referenced by AmsIntroducePopup(), and set_mode().
m_img_enable_ams
wxStaticBitmap* Slic3r::GUI::AmsIntroducePopup::m_img_enable_ams
Referenced by AmsIntroducePopup(), and set_mode().
m_staticText_bottom
Label* Slic3r::GUI::AmsIntroducePopup::m_staticText_bottom
Referenced by AmsIntroducePopup(), and set_mode().
m_staticText_top
Label* Slic3r::GUI::AmsIntroducePopup::m_staticText_top
Referenced by AmsIntroducePopup(), and set_mode().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp