OrcaSlicer: Slic3r::GUI::Bed3D Class Reference
Slic3r::GUI::Bed3D Class Reference
#include <src/slic3r/GUI/3DBed.hpp>
Classes
class Axes
Public Types
enum class Type : unsigned char { System , Custom }
Public Member Functions
Bed3D ()=default
~Bed3D ()
bool set_shape (const Pointfs &printable_area, const double printable_height, const std::string &custom_model, bool force_as_custom=false, const Vec2d position=Vec2d::Zero(), bool with_reset=true)
void set_position (Vec2d &position)
void set_axes_mode (bool origin)
const Vec2d & get_position () const
const BuildVolume & build_volume () const
Type get_type () const
bool is_custom () const
BuildVolume_Type get_build_volume_type () const
const BoundingBoxf3 & extended_bounding_box () const
bool contains (const Point &point) const
Point point_projection (const Point &point) const
void render (GLCanvas3D &canvas, bool bottom, float scale_factor, bool show_axes)
void on_change_color_mode (bool is_dark)
Static Public Member Functions
static void update_render_colors ()
static void load_render_colors ()
Static Public Attributes
static std::array< float, 4 > AXIS_X_COLOR = decode_color_to_float_array("#FF0000")
static std::array< float, 4 > AXIS_Y_COLOR = decode_color_to_float_array("#52c7b8")
static std::array< float, 4 > AXIS_Z_COLOR = decode_color_to_float_array("#0000FF")
Private Member Functions
BoundingBoxf3 calc_extended_bounding_box (bool consider_model_offset=true) const
void calc_triangles (const ExPolygon &poly)
void calc_gridlines (const ExPolygon &poly, const BoundingBox &bed_bbox)
void update_model_offset () const
GeometryBuffer update_bed_triangles () const
void render_internal (GLCanvas3D &canvas, bool bottom, float scale_factor, bool show_axes)
void render_axes () const
void render_system (GLCanvas3D &canvas, bool bottom) const
void render_model () const
void render_custom (GLCanvas3D &canvas, bool bottom) const
void render_default (bool bottom) const
void release_VBOs ()
Static Private Member Functions
static std::tuple< Type, std::string, std::string > detect_type (const Pointfs &shape)
Private Attributes
BuildVolume m_build_volume
Type m_type { Type::System }
std::string m_model_filename
BoundingBoxf3 m_extended_bounding_box
GeometryBuffer m_triangles
GLTexture m_texture
GLModel m_model
Vec3d m_model_offset { Vec3d::Zero() }
unsigned int m_vbo_id { 0 }
Axes m_axes
float m_scale_factor { 1.0f }
Vec2d m_position { Vec2d::Zero() }
std::vector< Vec2d > m_bed_shape
bool m_is_dark = false
Detailed Description
Member Enumeration Documentation
Type
enum class Slic3r::GUI::Bed3D::Type : unsigned char strong
Enumerator
System
Custom
    {
        // The print bed model and texture are available from some printer preset.
        System,
        // The print bed model is unknown, thus it is rendered procedurally.
        Custom
    };
Constructor & Destructor Documentation
Bed3D()
Slic3r::GUI::Bed3D::Bed3D () default
~Bed3D()
Slic3r::GUI::Bed3D::~Bed3D () inline
{ release_VBOs(); }
References release_VBOs().
Member Function Documentation
build_volume()
const BuildVolume & Slic3r::GUI::Bed3D::build_volume () const inline
{ return m_build_volume; }
References m_build_volume.
Referenced by Slic3r::GUI::GLCanvas3D::_max_bounding_box(), Slic3r::GUI::GLCanvas3D::_render_objects(), Slic3r::GUI::GLCanvas3D::check_volumes_outside_state(), Slic3r::GUI::GLCanvas3D::get_size_proportional_to_max_bed_size(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::GLCanvas3D::render(), Slic3r::GUI::GLCanvas3D::scene_bounding_box(), update_bed_triangles(), and Slic3r::GUI::GLCanvas3D::zoom_to_bed().
calc_extended_bounding_box()
BoundingBoxf3 Slic3r::GUI::Bed3D::calc_extended_bounding_box (bool consider_model_offset = true) const private
{
    BoundingBoxf3 out { m_build_volume.bounding_volume() };
    const Vec3d size = out.size();
    // ensures that the bounding box is set as defined or the following calls to merge() will not work as intented
    if (size.x() > 0.0 && size.y() > 0.0 && !out.defined)
        out.defined = true;
    // Reset the build volume Z, we don't want to zoom to the top of the build volume if it is empty.
    out.min.z() = 0.0;
    out.max.z() = 0.0;
    // extend to contain axes
    //BBS: add part plate related logic.
    Vec3d offset{ m_position.x(), m_position.y(), 0.f };
    //out.merge(m_axes.get_origin() + offset + m_axes.get_total_length() * Vec3d::Ones());
    out.merge(Vec3d(0.f, 0.f, GROUND_Z) + offset + m_axes.get_total_length() * Vec3d::Ones());
    out.merge(out.min + Vec3d(-Axes::DefaultTipRadius, -Axes::DefaultTipRadius, out.max.z()));
    //BBS: add part plate related logic.
    if (consider_model_offset) {
        // extend to contain model, if any
        BoundingBoxf3 model_bb = m_model.get_bounding_box();
        if (model_bb.defined) {
            model_bb.translate(m_model_offset);
            out.merge(model_bb);
        }
    }
    return out;
}
References Slic3r::BuildVolume::bounding_volume(), Slic3r::GUI::Bed3D::Axes::DefaultTipRadius, Slic3r::BoundingBoxBase< PointClass >::defined, Slic3r::GUI::GLModel::get_bounding_box(), Slic3r::GUI::Bed3D::Axes::get_total_length(), GROUND_Z, m_axes, m_build_volume, m_model, m_model_offset, m_position, Slic3r::offset(), out, size, and Slic3r::BoundingBox3Base< PointClass >::translate().
Referenced by set_shape(), update_bed_triangles(), and update_model_offset().
calc_gridlines()
void Slic3r::GUI::Bed3D::calc_gridlines (const ExPolygon & poly, const BoundingBox & bed_bbox) private
{
    /*Polylines axes_lines;
    for (coord_t x = bed_bbox.min.x(); x <= bed_bbox.max.x(); x += scale_(10.0)) {
        Polyline line;
        line.append(Point(x, bed_bbox.min.y()));
        line.append(Point(x, bed_bbox.max.y()));
        axes_lines.push_back(line);
    }
    for (coord_t y = bed_bbox.min.y(); y <= bed_bbox.max.y(); y += scale_(10.0)) {
        Polyline line;
        line.append(Point(bed_bbox.min.x(), y));
        line.append(Point(bed_bbox.max.x(), y));
        axes_lines.push_back(line);
    }
    // clip with a slightly grown expolygon because our lines lay on the contours and may get erroneously clipped
    Lines gridlines = to_lines(intersection_pl(axes_lines, offset(poly, (float)SCALED_EPSILON)));
    // append bed contours
    Lines contour_lines = to_lines(poly);
    std::copy(contour_lines.begin(), contour_lines.end(), std::back_inserter(gridlines));
    if (!m_gridlines.set_from_lines(gridlines, GROUND_Z))
        BOOST_LOG_TRIVIAL(error) << "Unable to create bed grid lines\n";*/
}
calc_triangles()
void Slic3r::GUI::Bed3D::calc_triangles (const ExPolygon & poly) private
{
    if (! m_triangles.set_from_triangles(triangulate_expolygon_2f(poly, NORMALS_UP), GROUND_Z))
        BOOST_LOG_TRIVIAL(error) << "Unable to create bed triangles";
}
References error, GROUND_Z, m_triangles, Slic3r::NORMALS_UP, Slic3r::GUI::GeometryBuffer::set_from_triangles(), and Slic3r::triangulate_expolygon_2f().
Referenced by set_shape().
contains()
bool Slic3r::GUI::Bed3D::contains (const Point & point) const
detect_type()
std::tuple< Bed3D::Type, std::string, std::string > Slic3r::GUI::Bed3D::detect_type (const Pointfs & shape) static private
{
    auto bundle = wxGetApp().preset_bundle;
    if (bundle != nullptr) {
        const Preset* curr = &bundle->printers.get_selected_preset();
        while (curr != nullptr) {
            if (curr->config.has("printable_area")) {
                std::string texture_filename, model_filename;
                if (shape == dynamic_cast<const ConfigOptionPoints*>(curr->config.option("printable_area"))->values) {
                    if (curr->is_system)
                        model_filename = PresetUtils::system_printer_bed_model(*curr);
                    else {
                        auto *printer_model = curr->config.opt<ConfigOptionString>("printer_model");
                        if (printer_model != nullptr && ! printer_model->value.empty()) {
                            model_filename = bundle->get_stl_model_for_printer_model(printer_model->value);
                        }
                    }
                    //std::string model_filename = PresetUtils::system_printer_bed_model(*curr);
                    //std::string texture_filename = PresetUtils::system_printer_bed_texture(*curr);
                    if (!model_filename.empty())
                        return { Type::System, model_filename, texture_filename };
                }
            }
            curr = bundle->printers.get_preset_parent(*curr);
        }
    }
    return { Type::Custom, {}, {} };
}
References Slic3r::Preset::config, Custom, Slic3r::ConfigOptionResolver::has(), Slic3r::Preset::is_system, Slic3r::DynamicConfig::opt(), Slic3r::ConfigBase::option(), Slic3r::printer_model(), System, Slic3r::PresetUtils::system_printer_bed_model(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by set_shape().
extended_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::Bed3D::extended_bounding_box () const inline
{ return m_extended_bounding_box; }
References m_extended_bounding_box.
Referenced by Slic3r::GUI::GLCanvas3D::_max_bounding_box(), and Slic3r::GUI::GLCanvas3D::scene_bounding_box().
get_build_volume_type()
BuildVolume_Type Slic3r::GUI::Bed3D::get_build_volume_type () const inline
{ return m_build_volume.type(); }
References m_build_volume, and Slic3r::BuildVolume::type().
get_position()
const Vec2d & Slic3r::GUI::Bed3D::get_position () const inline
{ return m_position; }
References m_position.
get_type()
Type Slic3r::GUI::Bed3D::get_type () const inline
{ return m_type; }
References m_type.
is_custom()
bool Slic3r::GUI::Bed3D::is_custom () const inline
{ return m_type == Type::Custom; }
References Custom, and m_type.
load_render_colors()
void Slic3r::GUI::Bed3D::load_render_colors () static
{
    RenderColor::colors[RenderCol_Axis_X] = IMColor(Bed3D::AXIS_X_COLOR);
    RenderColor::colors[RenderCol_Axis_Y] = IMColor(Bed3D::AXIS_Y_COLOR);
    RenderColor::colors[RenderCol_Axis_Z] = IMColor(Bed3D::AXIS_Z_COLOR);
}
References AXIS_X_COLOR, AXIS_Y_COLOR, AXIS_Z_COLOR, Slic3r::RenderColor::colors, Slic3r::IMColor(), RenderCol_Axis_X, RenderCol_Axis_Y, and RenderCol_Axis_Z.
Referenced by Slic3r::GUI::GLCanvas3D::init().
on_change_color_mode()
void Slic3r::GUI::Bed3D::on_change_color_mode (bool is_dark)
{
    m_is_dark = is_dark;
}
References m_is_dark.
Referenced by Slic3r::GUI::GLCanvas3D::on_change_color_mode().
point_projection()
Point Slic3r::GUI::Bed3D::point_projection (const Point & point) const
release_VBOs()
void Slic3r::GUI::Bed3D::release_VBOs () private
{
    if (m_vbo_id > 0) {
        glsafe(::glDeleteBuffers(1, &m_vbo_id));
        m_vbo_id = 0;
    }
}
References glsafe, and m_vbo_id.
Referenced by ~Bed3D(), and set_shape().
render()
void Slic3r::GUI::Bed3D::render (GLCanvas3D & canvas, bool bottom, float scale_factor, bool show_axes)
{
    render_internal(canvas, bottom, scale_factor, show_axes);
}
References render_internal().
Referenced by Slic3r::GUI::GLCanvas3D::_render_bed().
render_axes()
void Slic3r::GUI::Bed3D::render_axes () const private
{
    if (m_build_volume.valid())
        m_axes.render();
}
References m_axes, m_build_volume, Slic3r::GUI::Bed3D::Axes::render(), and Slic3r::BuildVolume::valid().
Referenced by render_internal().
render_custom()
void Slic3r::GUI::Bed3D::render_custom (GLCanvas3D & canvas, bool bottom) const private
{
    if (m_model_filename.empty()) {
        render_default(bottom);
        return;
    }
    if (!bottom)
        render_model();
    /*if (show_texture)
        render_texture(bottom, canvas);*/
}
References m_model_filename, render_default(), and render_model().
Referenced by render_internal().
render_default()
void Slic3r::GUI::Bed3D::render_default (bool bottom) const private
{
    bool picking = false;
    const_cast<GLTexture*>(&m_texture)->reset();
    unsigned int triangles_vcount = m_triangles.get_vertices_count();
    GeometryBuffer default_triangles = update_bed_triangles();
    if (triangles_vcount > 0) {
        bool has_model = !m_model.get_filename().empty();
        glsafe(::glEnable(GL_DEPTH_TEST));
        glsafe(::glEnable(GL_BLEND));
        glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
        glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
        if (!has_model && !bottom) {
            // draw background
            glsafe(::glDepthMask(GL_FALSE));
            glsafe(::glColor4fv(picking ? PICKING_MODEL_COLOR.data() : DEFAULT_MODEL_COLOR.data()));
            glsafe(::glNormal3d(0.0f, 0.0f, 1.0f));
            glsafe(::glVertexPointer(3, GL_FLOAT, default_triangles.get_vertex_data_size(), (GLvoid*)default_triangles.get_vertices_data()));
            glsafe(::glDrawArrays(GL_TRIANGLES, 0, (GLsizei)triangles_vcount));
            glsafe(::glDepthMask(GL_TRUE));
        }
        /*if (!picking) {
            // draw grid
            glsafe(::glLineWidth(1.5f * m_scale_factor));
            if (has_model && !bottom)
                glsafe(::glColor4f(0.9f, 0.9f, 0.9f, 1.0f));
            else
                glsafe(::glColor4f(0.9f, 0.9f, 0.9f, 0.6f));
            glsafe(::glVertexPointer(3, GL_FLOAT, default_triangles.get_vertex_data_size(), (GLvoid*)m_gridlines.get_vertices_data()));
            glsafe(::glDrawArrays(GL_LINES, 0, (GLsizei)m_gridlines.get_vertices_count()));
        }*/
        glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
        glsafe(::glDisable(GL_BLEND));
    }
}
References DEFAULT_MODEL_COLOR, Slic3r::GUI::GLModel::get_filename(), Slic3r::GUI::GeometryBuffer::get_vertex_data_size(), Slic3r::GUI::GeometryBuffer::get_vertices_count(), Slic3r::GUI::GeometryBuffer::get_vertices_data(), GL_FALSE, GL_TRIANGLES, GL_TRUE, glsafe, m_model, m_texture, m_triangles, PICKING_MODEL_COLOR, and update_bed_triangles().
Referenced by render_custom().
render_internal()
void Slic3r::GUI::Bed3D::render_internal (GLCanvas3D & canvas, bool bottom, float scale_factor, bool show_axes) private
{
    float* factor = const_cast<float*>(&m_scale_factor);
    *factor = scale_factor;
    if (show_axes)
        render_axes();
    glsafe(::glEnable(GL_DEPTH_TEST));
    m_model.set_color(-1, m_is_dark ? DEFAULT_MODEL_COLOR_DARK : DEFAULT_MODEL_COLOR);
    switch (m_type)
    {
    case Type::System: { render_system(canvas, bottom); break; }
    default:
    case Type::Custom: { render_custom(canvas, bottom); break; }
    }
    glsafe(::glDisable(GL_DEPTH_TEST));
}
References Custom, DEFAULT_MODEL_COLOR, DEFAULT_MODEL_COLOR_DARK, glsafe, m_is_dark, m_model, m_scale_factor, m_type, render_axes(), render_custom(), render_system(), Slic3r::GUI::GLModel::set_color(), and System.
Referenced by render().
render_model()
void Slic3r::GUI::Bed3D::render_model () const private
{
    if (m_model_filename.empty())
        return;
    GLModel* model = const_cast<GLModel*>(&m_model);
    if (model->get_filename() != m_model_filename && model->init_from_file(m_model_filename)) {
        model->set_color(-1, m_is_dark ? DEFAULT_MODEL_COLOR_DARK : DEFAULT_MODEL_COLOR);
        update_model_offset();
    }
    if (!model->get_filename().empty()) {
        GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
        if (shader != nullptr) {
            shader->start_using();
            shader->set_uniform("emission_factor", 0.0f);
            glsafe(::glPushMatrix());
            glsafe(::glTranslated(m_model_offset.x(), m_model_offset.y(), m_model_offset.z()));
            model->render();
            glsafe(::glPopMatrix());
            shader->stop_using();
        }
    }
}
References DEFAULT_MODEL_COLOR, DEFAULT_MODEL_COLOR_DARK, Slic3r::GUI::GLModel::get_filename(), glsafe, Slic3r::GUI::GLModel::init_from_file(), m_is_dark, m_model, m_model_filename, m_model_offset, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), and update_model_offset().
Referenced by render_custom(), and render_system().
render_system()
void Slic3r::GUI::Bed3D::render_system (GLCanvas3D & canvas, bool bottom) const private
{
    if (!bottom)
        render_model();
    /*if (show_texture)
        render_texture(bottom, canvas);*/
}
References render_model().
Referenced by render_internal().
set_axes_mode()
void Slic3r::GUI::Bed3D::set_axes_mode (bool origin)
{
    if (origin) {
        m_axes.set_origin({ 0.0, 0.0, static_cast<double>(GROUND_Z) });
    }
    else {
        m_axes.set_origin({ m_position.x(), m_position.y(), static_cast<double>(GROUND_Z) });
    }
}
References GROUND_Z, m_axes, m_position, and Slic3r::GUI::Bed3D::Axes::set_origin().
Referenced by Slic3r::GUI::GLCanvas3D::_render_bed().
set_position()
void Slic3r::GUI::Bed3D::set_position (Vec2d & position)
{
    set_shape(m_bed_shape, m_build_volume.printable_height(), m_model_filename, false, position, false);
}
References m_bed_shape, m_build_volume, m_model_filename, Slic3r::BuildVolume::printable_height(), and set_shape().
set_shape()
bool Slic3r::GUI::Bed3D::set_shape (const Pointfs & printable_area, const double printable_height, const std::string & custom_model, bool force_as_custom = false, const Vec2d position = Vec2d::Zero(), bool with_reset = true)
{
    /*auto check_texture = [](const std::string& texture) {
        boost::system::error_code ec; // so the exists call does not throw (e.g. after a permission problem)
        return !texture.empty() && (boost::algorithm::iends_with(texture, ".png") || boost::algorithm::iends_with(texture, ".svg")) && boost::filesystem::exists(texture, ec);
    };*/
    auto check_model = [](const std::string& model) {
        boost::system::error_code ec;
        return !model.empty() && boost::algorithm::iends_with(model, ".stl") && boost::filesystem::exists(model, ec);
    };
    Type type;
    std::string model;
    std::string texture;
    if (force_as_custom)
        type = Type::Custom;
    else {
        auto [new_type, system_model, system_texture] = detect_type(printable_area);
        type = new_type;
        model = system_model;
        texture = system_texture;
    }
    /*std::string texture_filename = custom_texture.empty() ? texture : custom_texture;
    if (! texture_filename.empty() && ! check_texture(texture_filename)) {
        BOOST_LOG_TRIVIAL(error) << "Unable to load bed texture: " << texture_filename;
        texture_filename.clear();
    }*/
    std::string model_filename = custom_model.empty() ? model : custom_model;
    if (! model_filename.empty() && ! check_model(model_filename)) {
        BOOST_LOG_TRIVIAL(error) << "Unable to load bed model: " << model_filename;
        model_filename.clear();
    }
    //BBS: add position related logic
    if (m_bed_shape == printable_area && m_build_volume.printable_height() == printable_height && m_type == type && m_model_filename == model_filename && position == m_position)
        // No change, no need to update the UI.
        return false;
    //BBS: add part plate logic, apply position to bed shape
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(":current position {%1%,%2%}, new position {%3%, %4%}") % m_position.x() % m_position.y() % position.x() % position.y();
    m_position = position;
    m_bed_shape = printable_area;
    if ((position(0) != 0) || (position(1) != 0)) {
        Pointfs new_bed_shape;
        for (const Vec2d& p : m_bed_shape) {
            Vec2d point(p(0) + m_position.x(), p(1) + m_position.y());
            new_bed_shape.push_back(point);
        }
        m_build_volume = BuildVolume { new_bed_shape, printable_height };
    }
    else
        m_build_volume = BuildVolume { printable_area, printable_height };
    m_type = type;
    //m_texture_filename = texture_filename;
    m_model_filename = model_filename;
    //BBS: add part plate logic
    m_extended_bounding_box = this->calc_extended_bounding_box(false);
    //BBS: add part plate logic
    //BBS add default bed
#if 1
    ExPolygon poly{ Polygon::new_scale(printable_area) };
#else
    ExPolygon poly;
    for (const Vec2d& p : printable_area) {
        poly.contour.append(Point(scale_(p(0) + m_position.x()), scale_(p(1) + m_position.y())));
    }
#endif
    calc_triangles(poly);
    //no need gridline for 3dbed
    //const BoundingBox& bed_bbox = poly.contour.bounding_box();
    //calc_gridlines(poly, bed_bbox);
    //m_polygon = offset(poly.contour, (float)bed_bbox.radius() * 1.7f, jtRound, scale_(0.5))[0];
    if (with_reset) {
        this->release_VBOs();
        //m_texture.reset();
        m_model.reset();
    }
    //BBS: add part plate logic, always update model offset
    //else {
        update_model_offset();
    //}
    // Set the origin and size for rendering the coordinate system axes.
    m_axes.set_origin({ 0.0, 0.0, static_cast<double>(GROUND_Z) });
    m_axes.set_stem_length(0.1f * static_cast<float>(m_build_volume.bounding_volume().max_size()));
    // Let the calee to update the UI.
    return true;
}
References Slic3r::MultiPoint::append(), Slic3r::BuildVolume::bounding_volume(), calc_extended_bounding_box(), calc_triangles(), Slic3r::ExPolygon::contour, Custom, detect_type(), error, GROUND_Z, m_axes, m_bed_shape, m_build_volume, m_extended_bounding_box, m_model, m_model_filename, m_position, m_type, Slic3r::BoundingBox3Base< PointClass >::max_size(), Slic3r::Polygon::new_scale(), Slic3r::printable_height(), Slic3r::BuildVolume::printable_height(), release_VBOs(), Slic3r::GUI::GLModel::reset(), scale_, Slic3r::GUI::Bed3D::Axes::set_origin(), Slic3r::GUI::Bed3D::Axes::set_stem_length(), and update_model_offset().
Referenced by set_position().
update_bed_triangles()
GeometryBuffer Slic3r::GUI::Bed3D::update_bed_triangles () const private
{
    GeometryBuffer new_triangles;
    Vec3d shift = m_extended_bounding_box.center();
    shift(2) = -0.03;
    Vec3d* model_offset_ptr = const_cast<Vec3d*>(&m_model_offset);
    *model_offset_ptr = shift;
    //BBS: TODO: hack for default bed
    BoundingBoxf3 build_volume;
    if (!m_build_volume.valid()) return new_triangles;
    auto bed_ext = get_extents(m_bed_shape);
    (*model_offset_ptr)(0) = m_build_volume.bounding_volume2d().min.x() - bed_ext.min.x();
    (*model_offset_ptr)(1) = m_build_volume.bounding_volume2d().min.y() - bed_ext.min.y();
    (*model_offset_ptr)(2) = -0.41 + GROUND_Z;
    std::vector<Vec2d> new_bed_shape;
    for (auto point: m_bed_shape) {
        Vec2d new_point(point.x() + model_offset_ptr->x(), point.y() + model_offset_ptr->y());
        new_bed_shape.push_back(new_point);
    }
    ExPolygon poly{ Polygon::new_scale(new_bed_shape) };
    if (!new_triangles.set_from_triangles(triangulate_expolygon_2f(poly, NORMALS_UP), GROUND_Z)) {
        ;
    }
    // update extended bounding box
    const_cast<BoundingBoxf3&>(m_extended_bounding_box) = calc_extended_bounding_box();
    return new_triangles;
}
References Slic3r::BuildVolume::bounding_volume2d(), build_volume(), calc_extended_bounding_box(), Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::get_extents(), GROUND_Z, m_bed_shape, m_build_volume, m_extended_bounding_box, m_model_offset, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::Polygon::new_scale(), Slic3r::NORMALS_UP, Slic3r::GUI::GeometryBuffer::set_from_triangles(), Slic3r::triangulate_expolygon_2f(), and Slic3r::BuildVolume::valid().
Referenced by render_default().
update_model_offset()
void Slic3r::GUI::Bed3D::update_model_offset () const private
{
    // move the model so that its origin (0.0, 0.0, 0.0) goes into the bed shape center and a bit down to avoid z-fighting with the texture quad
    Vec3d shift = m_extended_bounding_box.center();
    shift(2) = -0.03;
    Vec3d* model_offset_ptr = const_cast<Vec3d*>(&m_model_offset);
    *model_offset_ptr = shift;
    //BBS: TODO: hack for current stl for BBL printer
    if (std::string::npos != m_model_filename.find("bbl-3dp-"))
    {
        (*model_offset_ptr)(0) -= 128.f;
        (*model_offset_ptr)(1) -= 128.f;
    }
    (*model_offset_ptr)(2) = -0.41 + GROUND_Z;
    // update extended bounding box
    const_cast<BoundingBoxf3&>(m_extended_bounding_box) = calc_extended_bounding_box();
}
References calc_extended_bounding_box(), Slic3r::BoundingBox3Base< PointClass >::center(), GROUND_Z, m_extended_bounding_box, m_model_filename, and m_model_offset.
Referenced by render_model(), and set_shape().
update_render_colors()
void Slic3r::GUI::Bed3D::update_render_colors () static
{
    Bed3D::AXIS_X_COLOR = GLColor(RenderColor::colors[RenderCol_Axis_X]);
    Bed3D::AXIS_Y_COLOR = GLColor(RenderColor::colors[RenderCol_Axis_Y]);
    Bed3D::AXIS_Z_COLOR = GLColor(RenderColor::colors[RenderCol_Axis_Z]);
}
References AXIS_X_COLOR, AXIS_Y_COLOR, AXIS_Z_COLOR, Slic3r::RenderColor::colors, Slic3r::GLColor(), RenderCol_Axis_X, RenderCol_Axis_Y, and RenderCol_Axis_Z.
Referenced by Slic3r::GUI::GLCanvas3D::_render_style_editor().
Member Data Documentation
AXIS_X_COLOR
std::array< float, 4 > Slic3r::GUI::Bed3D::AXIS_X_COLOR = decode_color_to_float_array("#FF0000") static
Referenced by load_render_colors(), Slic3r::GUI::Bed3D::Axes::render(), and update_render_colors().
AXIS_Y_COLOR
std::array< float, 4 > Slic3r::GUI::Bed3D::AXIS_Y_COLOR = decode_color_to_float_array("#52c7b8") static
Referenced by load_render_colors(), Slic3r::GUI::Bed3D::Axes::render(), and update_render_colors().
AXIS_Z_COLOR
std::array< float, 4 > Slic3r::GUI::Bed3D::AXIS_Z_COLOR = decode_color_to_float_array("#0000FF") static
Referenced by load_render_colors(), Slic3r::GUI::Bed3D::Axes::render(), and update_render_colors().
m_axes
Axes Slic3r::GUI::Bed3D::m_axes private
Referenced by calc_extended_bounding_box(), render_axes(), set_axes_mode(), and set_shape().
m_bed_shape
std::vector<Vec2d> Slic3r::GUI::Bed3D::m_bed_shape private
Referenced by set_position(), set_shape(), and update_bed_triangles().
m_build_volume
BuildVolume Slic3r::GUI::Bed3D::m_build_volume private
Referenced by build_volume(), calc_extended_bounding_box(), get_build_volume_type(), render_axes(), set_position(), set_shape(), and update_bed_triangles().
m_extended_bounding_box
BoundingBoxf3 Slic3r::GUI::Bed3D::m_extended_bounding_box private
Referenced by extended_bounding_box(), set_shape(), update_bed_triangles(), and update_model_offset().
m_is_dark
bool Slic3r::GUI::Bed3D::m_is_dark = false private
Referenced by on_change_color_mode(), render_internal(), and render_model().
m_model
GLModel Slic3r::GUI::Bed3D::m_model private
Referenced by calc_extended_bounding_box(), render_default(), render_internal(), render_model(), and set_shape().
m_model_filename
std::string Slic3r::GUI::Bed3D::m_model_filename private
Referenced by render_custom(), render_model(), set_position(), set_shape(), and update_model_offset().
m_model_offset
Vec3d Slic3r::GUI::Bed3D::m_model_offset { Vec3d::Zero() } private
Referenced by calc_extended_bounding_box(), render_model(), update_bed_triangles(), and update_model_offset().
m_position
Vec2d Slic3r::GUI::Bed3D::m_position { Vec2d::Zero() } private
Referenced by calc_extended_bounding_box(), get_position(), set_axes_mode(), and set_shape().
m_scale_factor
float Slic3r::GUI::Bed3D::m_scale_factor { 1.0f } private
Referenced by render_internal().
m_texture
GLTexture Slic3r::GUI::Bed3D::m_texture private
Referenced by render_default().
m_triangles
GeometryBuffer Slic3r::GUI::Bed3D::m_triangles private
Referenced by calc_triangles(), and render_default().
m_type
Type Slic3r::GUI::Bed3D::m_type { Type::System } private
Referenced by get_type(), is_custom(), render_internal(), and set_shape().
m_vbo_id
unsigned int Slic3r::GUI::Bed3D::m_vbo_id { 0 } private
Referenced by release_VBOs().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DBed.hpp
src/slic3r/GUI/3DBed.cpp