OrcaSlicer: Slic3r::MachineObject Class Reference
Slic3r::MachineObject Class Reference
#include <src/slic3r/GUI/DeviceManager.hpp>
Classes
class ExtrusionRatioInfo
class ModuleVersionInfo
Public Types
enum LIGHT_EFFECT { LIGHT_EFFECT_ON , LIGHT_EFFECT_OFF , LIGHT_EFFECT_FLASHING , LIGHT_EFFECT_UNKOWN }
enum FanType { COOLING_FAN = 1 , BIG_COOLING_FAN = 2 , CHAMBER_FAN = 3 }
enum UpgradingDisplayState { UpgradingUnavaliable = 0 , UpgradingAvaliable = 1 , UpgradingInProgress = 2 , UpgradingFinished = 3 }
enum ExtruderAxisStatus { LOAD = 0 , UNLOAD =1 , STATUS_NUMS = 2 }
enum PrintOption { PRINT_OP_AUTO_RECOVERY = 0 , PRINT_OP_MAX }
enum SdcardState { NO_SDCARD = 0 , HAS_SDCARD_NORMAL = 1 , HAS_SDCARD_ABNORMAL = 2 , SDCARD_STATE_NUM = 3 }
typedef std::function< void()> UploadedFn
typedef std::function< void(int progress)> UploadProgressFn
typedef std::function< void(std::string error)> ErrorFn
typedef std::function< void(int result, std::string info)> ResultFn
typedef std::function< void(std::string topic, std::string payload)> MsgFn
Public Member Functions
std::string connection_type ()
void set_dev_ip (std::string ip)
bool has_access_right ()
std::string get_ftp_folder ()
void set_access_code (std::string code)
std::string get_access_code ()
void set_user_access_code (std::string code)
std::string get_user_access_code ()
bool is_lan_mode_printer ()
wxString get_printer_type_display_str ()
std::string get_printer_thumbnail_img_str ()
bool is_avaliable ()
void set_lan_mode_connection_state (bool state)
bool get_lan_mode_connection_state ()
bool is_in_extrusion_cali ()
bool is_extrusion_cali_finished ()
void _parse_tray_now (std::string tray_now)
bool is_filament_move ()
bool is_ams_unload ()
Ams * get_curr_Ams ()
AmsTray * get_curr_tray ()
AmsTray * get_ams_tray (std::string ams_id, std::string tray_id)
void _parse_ams_status (int ams_status)
bool has_ams ()
bool can_unload_filament ()
bool is_U0_firmware ()
bool is_support_ams_mapping ()
int ams_filament_mapping (std::vector< FilamentInfo > filaments, std::vector< FilamentInfo > &result, std::vector< int > exclude_id=std::vector< int >())
bool is_valid_mapping_result (std::vector< FilamentInfo > &result, bool check_empty_slot=false)
bool is_mapping_exceed_filament (std::vector< FilamentInfo > &result, int &exceed_index)
void reset_mapping_result (std::vector< FilamentInfo > &result)
std::string light_effect_str (LIGHT_EFFECT effect)
LIGHT_EFFECT light_effect_parse (std::string effect_str)
std::string get_firmware_type_str ()
bool is_in_upgrading ()
bool is_upgrading_avalable ()
int get_upgrade_percent ()
std::string get_ota_version ()
bool check_version_valid ()
wxString get_upgrade_result_str (int upgrade_err_code)
std::map< int, ModuleVersionInfo > get_ams_version ()
bool is_system_printing ()
bool is_axis_at_home (std::string axis)
bool is_filament_at_extruder ()
wxString get_curr_stage ()
int get_curr_stage_idx ()
bool is_in_calibration ()
bool is_calibration_running ()
bool is_calibration_done ()
void parse_state_changed_event ()
void parse_status (int flag)
PrintingSpeedLevel _parse_printing_speed_lvl (int lvl)
int get_bed_temperature_limit ()
MachineObject::SdcardState get_sdcard_state ()
int connect (bool is_anonymous=false)
int disconnect ()
bool is_sdcard_printing ()
bool has_sdcard ()
bool is_timelapse ()
bool is_recording_enable ()
bool is_recording ()
MachineObject (NetworkAgent *agent, std::string name, std::string id, std::string ip)
~MachineObject ()
void parse_version_func ()
bool is_studio_cmd (int seq)
int command_get_version (bool with_retry=true)
int command_request_push_all ()
int command_pushing (std::string cmd)
int command_clean_print_error (std::string task_id, int print_error)
int command_upgrade_confirm ()
int command_consistency_upgrade_confirm ()
int command_upgrade_firmware (FirmwareInfo info)
int command_upgrade_module (std::string url, std::string module_type, std::string version)
int command_xyz_abs ()
int command_auto_leveling ()
int command_go_home ()
int command_control_fan (FanType fan_type, bool on_off)
int command_control_fan_val (FanType fan_type, int val)
int command_task_abort ()
int command_task_pause ()
int command_task_resume ()
int command_set_bed (int temp)
int command_set_nozzle (int temp)
int command_ams_switch (int tray_index, int old_temp=210, int new_temp=210)
int command_ams_change_filament (int tray_id, int old_temp=210, int new_temp=210)
int command_ams_user_settings (int ams_id, bool start_read_opt, bool tray_read_opt, bool remain_flag=false)
int command_ams_user_settings (int ams_id, AmsOptionType op, bool value)
int command_ams_switch_filament (bool switch_filament)
int command_ams_calibrate (int ams_id)
int command_ams_filament_settings (int ams_id, int tray_id, std::string filament_id, std::string setting_id, std::string tray_color, std::string tray_type, int nozzle_temp_min, int nozzle_temp_max)
int command_ams_select_tray (std::string tray_id)
int command_ams_refresh_rfid (std::string tray_id)
int command_ams_control (std::string action)
int command_set_chamber_light (LIGHT_EFFECT effect, int on_time=500, int off_time=500, int loops=1, int interval=1000)
int command_set_work_light (LIGHT_EFFECT effect, int on_time=500, int off_time=500, int loops=1, int interval=1000)
int command_start_extrusion_cali (int tray_index, int nozzle_temp, int bed_temp, float max_volumetric_speed, std::string setting_id="")
int command_stop_extrusion_cali ()
int command_extrusion_cali_set (int tray_index, std::string setting_id, std::string name, float k, float n, int bed_temp=-1, int nozzle_temp=-1, float max_volumetric_speed=-1)
int command_set_printing_speed (PrintingSpeedLevel lvl)
int command_set_printing_option (bool auto_recovery)
int command_axis_control (std::string axis, double unit=1.0f, double value=1.0f, int speed=3000)
bool is_support_command_calibration ()
int command_start_calibration (bool vibration, bool bed_leveling, bool xcam_cali)
int command_unload_filament ()
int command_ipcam_record (bool on_off)
int command_ipcam_timelapse (bool on_off)
int command_ipcam_resolution_set (std::string resolution)
int command_xcam_control (std::string module_name, bool on_off, std::string lvl="")
int command_xcam_control_ai_monitoring (bool on_off, std::string lvl)
int command_xcam_control_first_layer_inspector (bool on_off, bool print_halt)
int command_xcam_control_buildplate_marker_detector (bool on_off)
int command_xcam_control_auto_recovery_step_loss (bool on_off)
bool is_local ()
void set_bind_status (std::string status)
std::string get_bind_str ()
bool can_print ()
bool can_resume ()
bool can_pause ()
bool can_abort ()
bool is_in_printing ()
bool is_in_prepare ()
bool is_printing_finished ()
void reset_update_time ()
void reset ()
void set_print_state (std::string status)
bool is_connected ()
bool is_connecting ()
void set_online_state (bool on_off)
bool is_online ()
bool is_info_ready ()
bool is_function_supported (PrinterFunction func)
std::vector< std::string > get_resolution_supported ()
bool is_support_print_with_timelapse ()
int publish_json (std::string json_str, int qos=0)
int cloud_publish_json (std::string json_str, int qos=0)
int local_publish_json (std::string json_str, int qos=0)
int parse_json (std::string payload)
int publish_gcode (std::string gcode_str)
BBLSubTask * get_subtask ()
void update_slice_info (std::string project_id, std::string profile_id, std::string subtask_id, int plate_idx)
void get_firmware_info ()
bool is_firmware_info_valid ()
Static Public Member Functions
static std::string parse_printer_type (std::string type_str)
static std::string get_preset_printer_model_name (std::string printer_type)
static std::string get_preset_printer_thumbnail_img (std::string printer_type)
static bool is_bbl_filament (std::string tag_uid)
static bool is_support_ams_mapping_version (std::string module, std::string version)
static bool is_in_printing_status (std::string status)
Public Attributes
enum ExtruderAxisStatus extruder_axis_status = LOAD
std::string dev_name
std::string dev_ip
std::string dev_id
bool local_use_ssl { false }
float nozzle_diameter { 0.0f }
std::string dev_connection_type
std::string printer_type
std::string printer_thumbnail_img
std::string monitor_upgrade_printer_img
std::string product_name
std::vector< int > filam_bak
std::string bind_user_name
std::string bind_user_id
std::string bind_state
std::string bind_sec_link
time_t last_alive
bool m_is_online
bool m_lan_mode_connection_state {false}
int parse_msg_count = 0
std::chrono::system_clock::time_point last_update_time
std::chrono::system_clock::time_point last_push_time
std::chrono::system_clock::time_point last_request_push
std::chrono::system_clock::time_point last_request_start
std::map< std::string, Ams * > amsList
AmsTray vt_tray
long ams_exist_bits = 0
long tray_exist_bits = 0
long tray_is_bbl_bits = 0
long tray_read_done_bits = 0
long tray_reading_bits = 0
int ams_rfid_status = 0
bool ams_insert_flag { false }
bool ams_power_on_flag { false }
bool ams_calibrate_remain_flag { false }
bool ams_support_auto_switch_filament_flag { true }
bool ams_auto_switch_filament_flag { false }
bool ams_support_use_ams { false }
bool ams_support_remain { true }
bool ams_support_virtual_tray { true }
int ams_humidity
int ams_user_setting_hold_count = 0
AmsStatusMain ams_status_main
int ams_status_sub
int ams_version = 0
std::string m_ams_id
std::string m_tray_id
std::string m_tray_now
std::string m_tray_tar
int extrusion_cali_hold_count = 0
std::chrono::system_clock::time_point last_extrusion_cali_start_time
int extrusion_cali_set_tray_id = -1
std::chrono::system_clock::time_point extrusion_cali_set_hold_start
bool is_ams_need_update
bool online_rfid
bool online_ahb
int online_version = -1
int last_online_version = -1
float nozzle_temp
float nozzle_temp_target
float bed_temp
float bed_temp_target
float chamber_temp
float frame_temp
int heatbreak_fan_speed = 0
int cooling_fan_speed = 0
int big_fan1_speed = 0
int big_fan2_speed = 0
uint32_t fan_gear = 0
std::string wifi_signal
std::string link_th
std::string link_ams
LIGHT_EFFECT chamber_light
LIGHT_EFFECT work_light
bool upgrade_force_upgrade { false }
bool upgrade_new_version { false }
bool upgrade_consistency_request { false }
int upgrade_display_state = 0
int upgrade_display_hold_count = 0
PrinterFirmwareType firmware_type
std::string upgrade_progress
std::string upgrade_message
std::string upgrade_status
std::string upgrade_module
std::string ams_new_version_number
std::string ota_new_version_number
std::string ahb_new_version_number
int get_version_retry = 0
std::map< std::string, ModuleVersionInfo > module_vers
std::map< std::string, ModuleVersionInfo > new_ver_list
std::map< std::string, ExtrusionRatioInfo > extrusion_ratio_map
bool m_new_ver_list_exist = false
int upgrade_err_code = 0
std::vector< FirmwareInfo > firmware_list
std::string print_type
float nozzle { 0.0f }
bool is_220V_voltage { false }
int mc_print_stage
int mc_print_sub_stage
int mc_print_error_code
int mc_print_line_number
int mc_print_percent
int mc_left_time
int last_mc_print_stage
int home_flag
int hw_switch_state
int print_error
int curr_layer = 0
int total_layers = 0
bool is_support_layer_num { false }
std::vector< int > stage_list_info
int stage_curr = 0
int m_push_count = 0
bool calibration_done { false }
std::string print_status
int queue_number = 0
std::string iot_print_status
PrintingSpeedLevel printing_speed_lvl
int printing_speed_mag = 100
bool has_ipcam { false }
bool camera_recording { false }
bool camera_recording_when_printing { false }
bool camera_timelapse { false }
int camera_recording_hold_count = 0
int camera_timelapse_hold_count = 0
int camera_resolution_hold_count = 0
std::string camera_resolution = ""
bool xcam_first_layer_inspector { false }
int xcam_first_layer_hold_count = 0
bool xcam_ai_monitoring { false }
int xcam_ai_monitoring_hold_count = 0
std::string xcam_ai_monitoring_sensitivity
bool is_xcam_buildplate_supported { true }
bool xcam_buildplate_marker_detector { false }
int xcam_buildplate_marker_hold_count = 0
bool xcam_support_recovery_step_loss { true }
bool xcam_auto_recovery_step_loss { false }
int xcam_auto_recovery_hold_count = 0
int ams_print_option_count = 0
bool is_support_1080dpi {false}
bool is_support_ai_monitoring {false}
bool is_support_ams_humidity {true}
bool is_support_filament_edit_virtual_tray {true}
bool is_cloud_print_only {false}
MachineObject::SdcardState sdcard_state { NO_SDCARD }
bool is_support_send_to_sdcard { true }
std::vector< HMSItem > hms_list
json_diff print_json
std::string project_id_
std::string profile_id_
std::string task_id_
std::string subtask_id_
BBLSliceInfo * slice_info {nullptr}
boost::thread * get_slice_info_thread { nullptr }
int plate_index { -1 }
std::string m_gcode_file
int gcode_file_prepare_percent = 0
BBLSubTask * subtask_
std::string obj_subtask_id
std::string subtask_name
bool m_firmware_valid { false }
bool m_firmware_thread_started { false }
Static Public Attributes
static int m_sequence_id = START_SEQ_ID
Private Member Functions
bool check_valid_ip ()
void _parse_print_option_ack (int option)
Private Attributes
NetworkAgent * m_agent { nullptr }
std::string access_code
std::string user_access_code
Detailed Description
Class Documentation
Slic3r::MachineObject::ExtrusionRatioInfo
class Slic3r::MachineObject::ExtrusionRatioInfo
Class Members
float k = 0.0
float n = 0.0
string name
string setting_id
Slic3r::MachineObject::ModuleVersionInfo
class Slic3r::MachineObject::ModuleVersionInfo
Class Members
string hw_ver
string name
string sn
string sw_new_ver
string sw_ver
Member Typedef Documentation
ErrorFn
typedef std::function<void(std::string error)> Slic3r::MachineObject::ErrorFn
MsgFn
typedef std::function<void(std::string topic, std::string payload)> Slic3r::MachineObject::MsgFn
ResultFn
typedef std::function<void(int result, std::string info)> Slic3r::MachineObject::ResultFn
UploadedFn
typedef std::function<void()> Slic3r::MachineObject::UploadedFn
UploadProgressFn
typedef std::function<void(int progress)> Slic3r::MachineObject::UploadProgressFn
Member Enumeration Documentation
ExtruderAxisStatus
enum Slic3r::MachineObject::ExtruderAxisStatus
Enumerator
LOAD
UNLOAD
STATUS_NUMS
{
        LOAD = 0,
        UNLOAD =1,
        STATUS_NUMS = 2
    };
FanType
enum Slic3r::MachineObject::FanType
Enumerator
COOLING_FAN
BIG_COOLING_FAN
CHAMBER_FAN
                 {
        COOLING_FAN = 1,
        BIG_COOLING_FAN = 2,
        CHAMBER_FAN = 3,
    };
LIGHT_EFFECT
enum Slic3r::MachineObject::LIGHT_EFFECT
Enumerator
LIGHT_EFFECT_ON
LIGHT_EFFECT_OFF
LIGHT_EFFECT_FLASHING
LIGHT_EFFECT_UNKOWN
                      {
        LIGHT_EFFECT_ON,
        LIGHT_EFFECT_OFF,
        LIGHT_EFFECT_FLASHING,
        LIGHT_EFFECT_UNKOWN,
    };
PrintOption
enum Slic3r::MachineObject::PrintOption
Enumerator
PRINT_OP_AUTO_RECOVERY
PRINT_OP_MAX
                     {
        PRINT_OP_AUTO_RECOVERY = 0,
        PRINT_OP_MAX,
    };
SdcardState
enum Slic3r::MachineObject::SdcardState
Enumerator
NO_SDCARD
HAS_SDCARD_NORMAL
HAS_SDCARD_ABNORMAL
SDCARD_STATE_NUM
                     {
        NO_SDCARD = 0,
        HAS_SDCARD_NORMAL = 1,
        HAS_SDCARD_ABNORMAL = 2,
        SDCARD_STATE_NUM = 3
    };
UpgradingDisplayState
enum Slic3r::MachineObject::UpgradingDisplayState
Enumerator
UpgradingUnavaliable
UpgradingAvaliable
UpgradingInProgress
UpgradingFinished
{
        UpgradingUnavaliable = 0,
        UpgradingAvaliable = 1,
        UpgradingInProgress = 2,
        UpgradingFinished = 3
    };
Constructor & Destructor Documentation
MachineObject()
Slic3r::MachineObject::MachineObject (NetworkAgent * agent, std::string name, std::string id, std::string ip)
    :dev_name(name),
    dev_id(id),
    dev_ip(ip),
    subtask_(nullptr),
    slice_info(nullptr),
    m_is_online(false),
    vt_tray(std::to_string(VIRTUAL_TRAY_ID))
{
    m_agent = agent;
    reset();
    /* temprature fields */
    nozzle_temp         = 0.0f;
    nozzle_temp_target  = 0.0f;
    bed_temp            = 0.0f;
    bed_temp_target     = 0.0f;
    chamber_temp        = 0.0f;
    frame_temp          = 0.0f;
    /* ams fileds */
    ams_exist_bits = 0;
    tray_exist_bits = 0;
    tray_is_bbl_bits = 0;
    ams_rfid_status = 0;
    is_ams_need_update = false;
    ams_insert_flag = false;
    ams_power_on_flag = false;
    ams_support_use_ams = false;
    ams_calibrate_remain_flag = false;
    ams_humidity = 5;
    /* signals */
    wifi_signal = "";
    /* upgrade */
    upgrade_force_upgrade = false;
    upgrade_new_version = false;
    upgrade_consistency_request = false;
    /* cooling */
    heatbreak_fan_speed = 0;
    cooling_fan_speed = 0;
    big_fan1_speed = 0;
    big_fan2_speed = 0;
    fan_gear = 0;
    /* printing */
    mc_print_stage = 0;
    mc_print_error_code = 0;
    print_error = 0;
    mc_print_line_number = 0;
    mc_print_percent = 0;
    mc_print_sub_stage = 0;
    mc_left_time = 0;
    home_flag = -1;
    hw_switch_state = 0;
    printing_speed_lvl   = PrintingSpeedLevel::SPEED_LEVEL_INVALID;
    has_ipcam = true; // default true
}
References ams_calibrate_remain_flag, ams_exist_bits, ams_humidity, ams_insert_flag, ams_power_on_flag, ams_rfid_status, ams_support_use_ams, bed_temp, bed_temp_target, big_fan1_speed, big_fan2_speed, chamber_temp, cooling_fan_speed, fan_gear, frame_temp, has_ipcam, heatbreak_fan_speed, home_flag, hw_switch_state, is_ams_need_update, m_agent, mc_left_time, mc_print_error_code, mc_print_line_number, mc_print_percent, mc_print_stage, mc_print_sub_stage, nozzle_temp, nozzle_temp_target, print_error, printing_speed_lvl, reset(), Slic3r::SPEED_LEVEL_INVALID, tray_exist_bits, tray_is_bbl_bits, upgrade_consistency_request, upgrade_force_upgrade, upgrade_new_version, and wifi_signal.
~MachineObject()
Slic3r::MachineObject::~MachineObject ()
{
    if (subtask_) {
        delete subtask_;
        subtask_ = nullptr;
    }
    if (get_slice_info_thread) {
        if (get_slice_info_thread->joinable()) {
            get_slice_info_thread->join();
            get_slice_info_thread = nullptr;
        }
    }
    if (slice_info) {
        delete slice_info;
        slice_info = nullptr;
    }
    for (auto it = amsList.begin(); it != amsList.end(); it++) {
        for (auto tray_it = it->second->trayList.begin(); tray_it != it->second->trayList.end(); tray_it++) {
            if (tray_it->second) {
                delete tray_it->second;
                tray_it->second = nullptr;
            }
        }
        it->second->trayList.clear();
    }
    amsList.clear();
}
References amsList, get_slice_info_thread, slice_info, and subtask_.
Member Function Documentation
_parse_ams_status()
void Slic3r::MachineObject::_parse_ams_status (int ams_status)
{
    ams_status_sub = ams_status & 0xFF;
    int ams_status_main_int = (ams_status & 0xFF00) >> 8;
    if (ams_status_main_int == (int)AmsStatusMain::AMS_STATUS_MAIN_IDLE) {
        ams_status_main = AmsStatusMain::AMS_STATUS_MAIN_IDLE;
    } else if (ams_status_main_int == (int) AmsStatusMain::AMS_STATUS_MAIN_FILAMENT_CHANGE) {
        ams_status_main = AmsStatusMain::AMS_STATUS_MAIN_FILAMENT_CHANGE;
    } else if (ams_status_main_int == (int) AmsStatusMain::AMS_STATUS_MAIN_RFID_IDENTIFYING) {
        ams_status_main = AmsStatusMain::AMS_STATUS_MAIN_RFID_IDENTIFYING;
    } else if (ams_status_main_int == (int) AmsStatusMain::AMS_STATUS_MAIN_ASSIST) {
        ams_status_main = AmsStatusMain::AMS_STATUS_MAIN_ASSIST;
    } else if (ams_status_main_int == (int) AmsStatusMain::AMS_STATUS_MAIN_CALIBRATION) {
        ams_status_main = AmsStatusMain::AMS_STATUS_MAIN_CALIBRATION;
    } else if (ams_status_main_int == (int) AmsStatusMain::AMS_STATUS_MAIN_SELF_CHECK) {
        ams_status_main = AmsStatusMain::AMS_STATUS_MAIN_SELF_CHECK;
    } else if (ams_status_main_int == (int) AmsStatusMain::AMS_STATUS_MAIN_DEBUG) {
        ams_status_main = AmsStatusMain::AMS_STATUS_MAIN_DEBUG;
    } else {
        ams_status_main = AmsStatusMain::AMS_STATUS_MAIN_UNKNOWN;
    }
    BOOST_LOG_TRIVIAL(trace) << "ams_debug: main = " << ams_status_main_int << ", sub = " << ams_status_sub;
}
References ams_status_main, Slic3r::AMS_STATUS_MAIN_ASSIST, Slic3r::AMS_STATUS_MAIN_CALIBRATION, Slic3r::AMS_STATUS_MAIN_DEBUG, Slic3r::AMS_STATUS_MAIN_FILAMENT_CHANGE, Slic3r::AMS_STATUS_MAIN_IDLE, Slic3r::AMS_STATUS_MAIN_RFID_IDENTIFYING, Slic3r::AMS_STATUS_MAIN_SELF_CHECK, Slic3r::AMS_STATUS_MAIN_UNKNOWN, ams_status_sub, and Slic3r::trace().
Referenced by parse_json().
_parse_print_option_ack()
void Slic3r::MachineObject::_parse_print_option_ack (int option) private
{
    xcam_auto_recovery_step_loss = ((option >> (int)PRINT_OP_AUTO_RECOVERY) & 0x01) != 0;
}
References int, PRINT_OP_AUTO_RECOVERY, and xcam_auto_recovery_step_loss.
Referenced by parse_json().
_parse_printing_speed_lvl()
PrintingSpeedLevel Slic3r::MachineObject::_parse_printing_speed_lvl (int lvl)
{
    if (lvl < (int)SPEED_LEVEL_COUNT)
        return PrintingSpeedLevel(lvl);
    return PrintingSpeedLevel::SPEED_LEVEL_INVALID;
}
References Slic3r::SPEED_LEVEL_COUNT, and Slic3r::SPEED_LEVEL_INVALID.
_parse_tray_now()
void Slic3r::MachineObject::_parse_tray_now (std::string tray_now)
{
    m_tray_now = tray_now;
    if (tray_now.empty()) {
        return;
    } else {
        try {
            int tray_now_int = atoi(tray_now.c_str());
            if (tray_now_int >= 0 && tray_now_int < 16) {
                m_ams_id = std::to_string(tray_now_int >> 2);
                m_tray_id = std::to_string(tray_now_int & 0x3);
            }
            else if (tray_now_int == 255) {
                m_ams_id = "0";
                m_tray_id = "0";
            }
        }
        catch(...) {
        }
    }
}
References m_ams_id, m_tray_id, and m_tray_now.
Referenced by parse_json().
ams_filament_mapping()
int Slic3r::MachineObject::ams_filament_mapping (std::vector< FilamentInfo > filaments, std::vector< FilamentInfo > & result, std::vector< int > exclude_id = std::vector<int>())
{
    if (filaments.empty())
        return -1;
    // tray_index : tray_color
    std::map<int, FilamentInfo> tray_filaments;
    for (auto ams = amsList.begin(); ams != amsList.end(); ams++) {
        for (auto tray = ams->second->trayList.begin(); tray != ams->second->trayList.end(); tray++) {
            int ams_id = atoi(ams->first.c_str());
            int tray_id = atoi(tray->first.c_str());
            int tray_index = ams_id * 4 + tray_id;
            // skip exclude id
            for (int i = 0; i < exclude_id.size(); i++) {
                if (tray_index == exclude_id[i])
                    continue;
            }
            // push
            if (tray->second->is_tray_info_ready()) {
                FilamentInfo info;
                info.color = tray->second->color;
                info.type = tray->second->get_filament_type();
                info.id = tray_index;
                tray_filaments.emplace(std::make_pair(tray_index, info));
            }
        }
    }
    // tray info list
    std::vector<FilamentInfo> tray_info_list;
    for (auto it = amsList.begin(); it != amsList.end(); it++) {
        for (int i = 0; i < 4; i++) {
            FilamentInfo info;
            auto tray_it = it->second->trayList.find(std::to_string(i));
            if (tray_it != it->second->trayList.end()) {
                info.id = atoi(tray_it->first.c_str()) + atoi(it->first.c_str()) * 4;
                info.tray_id = atoi(tray_it->first.c_str()) + atoi(it->first.c_str()) * 4;
                info.color = tray_it->second->color;
                info.type = tray_it->second->get_filament_type();
            }
            else {
                info.id = -1;
                info.tray_id = -1;
            }
            tray_info_list.push_back(info);
        }
    }
    // is_support_ams_mapping
    if (!is_support_ams_mapping()) {
        BOOST_LOG_TRIVIAL(info) << "ams_mapping: do not support, use order mapping";
        result.clear();
        for (int i = 0; i < filaments.size(); i++) {
            FilamentInfo info;
            info.id = filaments[i].id;
            int ams_id = filaments[i].id / 4;
            auto ams_it = amsList.find(std::to_string(ams_id));
            if (ams_it == amsList.end()) {
                info.tray_id = -1;
                info.mapping_result = (int)MappingResult::MAPPING_RESULT_EXCEED;
            } else {
                info.tray_id = filaments[i].id;
                int tray_id = filaments[i].id % 4;
                auto tray_it = ams_it->second->trayList.find(std::to_string(tray_id));
                if (tray_it != ams_it->second->trayList.end()) {
                    if (!tray_it->second->is_exists || tray_it->second->is_unset_third_filament()) {
                        ;
                    } else {
                        if (filaments[i].type == tray_it->second->get_filament_type()) {
                            info.color = tray_it->second->color;
                            info.type = tray_it->second->get_filament_type();
                        } else {
                            info.tray_id = -1;
                            info.mapping_result = (int)MappingResult::MAPPING_RESULT_TYPE_MISMATCH;
                        }
                    }
                }
            }
            result.push_back(info);
        }
        return 1;
    }
    char buffer[256];
    std::vector<std::vector<DisValue>> distance_map;
    // print title
    ::sprintf(buffer, "F(id)");
    std::string line = std::string(buffer);
    for (auto tray = tray_filaments.begin(); tray != tray_filaments.end(); tray++) {
        ::sprintf(buffer, "   AMS%02d", tray->second.id+1);
        line += std::string(buffer);
    }
    BOOST_LOG_TRIVIAL(info) << "ams_mapping_distance:" << line;
    for (int i = 0; i < filaments.size(); i++) {
        std::vector<DisValue> rol;
        ::sprintf(buffer, "F(%02d)", filaments[i].id+1);
        line = std::string(buffer);
        for (auto tray = tray_filaments.begin(); tray != tray_filaments.end(); tray++) {
            DisValue val;
            val.tray_id = tray->second.id;
            wxColour c = wxColour(filaments[i].color);
            val.distance = calc_color_distance(c, AmsTray::decode_color(tray->second.color));
            if (filaments[i].type != tray->second.type) {
                val.distance = 999999;
                val.is_type_match = false;
            } else {
                val.is_type_match = true;
            }
            ::sprintf(buffer, "  %6.0f", val.distance);
            line += std::string(buffer);
            rol.push_back(val);
        }
        BOOST_LOG_TRIVIAL(info) << "ams_mapping_distance:" << line;
        distance_map.push_back(rol);
    }
    // mapping algorithm
    for (int i = 0; i < filaments.size(); i++) {
        FilamentInfo info;
        info.id = filaments[i].id;
        info.tray_id = -1;
        result.push_back(info);
    }
    std::set<int> picked_src;
    std::set<int> picked_tar;
    for (int k = 0; k < distance_map.size(); k++) {
        float min_val = INT_MAX;
        int picked_src_idx = -1;
        int picked_tar_idx = -1;
        for (int i = 0; i < distance_map.size(); i++) {
            if (picked_src.find(i) != picked_src.end())
                continue;
            for (int j = 0; j < distance_map[i].size(); j++) {
                if (picked_tar.find(j) != picked_tar.end())
                    continue;
                if (distance_map[i][j].is_same_color
                    && distance_map[i][j].is_type_match) {
                    if (min_val > distance_map[i][j].distance) {
                        min_val = distance_map[i][j].distance;
                        picked_src_idx = i;
                        picked_tar_idx = j;
                    }
                }
            }
        }
        if (picked_src_idx >= 0 && picked_tar_idx >= 0) {
            auto tray = tray_filaments.find(distance_map[k][picked_tar_idx].tray_id);
            if (tray != tray_filaments.end()) {
                result[picked_src_idx].tray_id  = tray->first;
                result[picked_src_idx].color    = tray->second.color;
                result[picked_src_idx].type     = tray->second.type;
                result[picked_src_idx].distance = tray->second.distance;
            }
            else {
                FilamentInfo info;
                info.tray_id = -1;
            }
            ::sprintf(buffer, "ams_mapping, picked F(%02d) AMS(%02d), distance=%6.0f", picked_src_idx+1, picked_tar_idx+1,
                distance_map[picked_src_idx][picked_tar_idx].distance);
            BOOST_LOG_TRIVIAL(info) << std::string(buffer);
            picked_src.insert(picked_src_idx);
            picked_tar.insert(picked_tar_idx);
        }
    }
    std::vector<FilamentInfo> cache_map_result = result;
    //check ams mapping result
    if (is_valid_mapping_result(result, true)) {
        return 0;
    }
    reset_mapping_result(result);
    try {
        // try to use ordering ams mapping
        bool order_mapping_result = true;
        for (int i = 0; i < filaments.size(); i++) {
            if (i >= tray_info_list.size()) {
                order_mapping_result = false;
                break;
            }
            if (tray_info_list[i].tray_id == -1) {
                result[i].tray_id = tray_info_list[i].tray_id;
            } else {
                if (!tray_info_list[i].type.empty() && tray_info_list[i].type != filaments[i].type) {
                    order_mapping_result = false;
                    break;
                } else {
                    result[i].tray_id = tray_info_list[i].tray_id;
                    result[i].color = tray_info_list[i].color;
                    result[i].type = tray_info_list[i].type;
                }
            }
        }
        //check order mapping result
        if (is_valid_mapping_result(result, true)) {
            return 0;
        }
    } catch(...) {
        reset_mapping_result(result);
        return -1;
    }
    // try to match some color
    reset_mapping_result(result);
    result = cache_map_result;
    for (auto it = result.begin(); it != result.end(); it++) {
        if (it->distance >= 6000) {
            it->tray_id = -1;
        }
    }
    return 0;
}
References amsList, buffer, Slic3r::calc_color_distance(), Slic3r::FilamentInfo::color, Slic3r::AmsTray::decode_color(), std::distance(), Slic3r::DisValue::distance, Slic3r::FilamentInfo::id, int, is_support_ams_mapping(), Slic3r::DisValue::is_type_match, is_valid_mapping_result(), Slic3r::FilamentInfo::mapping_result, Slic3r::MAPPING_RESULT_EXCEED, Slic3r::MAPPING_RESULT_TYPE_MISMATCH, reset_mapping_result(), Slic3r::FilamentInfo::tray_id, Slic3r::DisValue::tray_id, and Slic3r::FilamentInfo::type.
Referenced by Slic3r::GUI::SelectMachineDialog::do_ams_mapping().
can_abort()
bool Slic3r::MachineObject::can_abort ()
{
    return MachineObject::is_in_printing_status(print_status);
}
References is_in_printing_status(), and print_status.
Referenced by is_sdcard_printing(), and Slic3r::GUI::MachineInfoPanel::update().
can_pause()
bool Slic3r::MachineObject::can_pause ()
{
    if (print_status.compare("RUNNING") == 0)
        return true;
    return false;
}
References print_status.
can_print()
bool Slic3r::MachineObject::can_print ()
{
    if (print_status.compare("RUNNING") == 0) {
        return false;
    }
    if (print_status.compare("IDLE") == 0 || print_status.compare("FINISH") == 0) {
        return true;
    }
    return true;
}
References print_status.
can_resume()
bool Slic3r::MachineObject::can_resume ()
{
    if (print_status.compare("PAUSE") == 0)
        return true;
    return false;
}
References print_status.
Referenced by Slic3r::GUI::AMSMaterialsSetting::on_clr_picker(), Slic3r::GUI::StatusPanel::on_subtask_pause_resume(), Slic3r::GUI::AMSMaterialsSetting::update(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::StatusPanel::update_ams_control_state(), and Slic3r::GUI::StatusPanel::update_subtask().
can_unload_filament()
bool Slic3r::MachineObject::can_unload_filament ()
{
    bool result = false;
    if (!has_ams())
        return true;
    if (ams_status_main == AMS_STATUS_MAIN_IDLE && hw_switch_state == 1 && m_tray_now == "255") {
        return true;
    }
    return result;
}
References ams_status_main, Slic3r::AMS_STATUS_MAIN_IDLE, has_ams(), hw_switch_state, and m_tray_now.
Referenced by Slic3r::GUI::StatusPanel::update_misc_ctrl().
check_valid_ip()
bool Slic3r::MachineObject::check_valid_ip () private
{
    if (dev_ip.empty()) {
        return false;
    }
    return true;
}
References dev_ip.
check_version_valid()
bool Slic3r::MachineObject::check_version_valid ()
{
    bool valid = true;
    for (auto module : module_vers) {
        if (module.second.sn.empty()
            && module.first != "ota"
            && module.first != "xm")
            return false;
        if (module.second.sw_ver.empty())
            return false;
    }
    get_version_retry = 0;
    return valid;
}
References get_version_retry, module, and module_vers.
Referenced by parse_json().
cloud_publish_json()
int Slic3r::MachineObject::cloud_publish_json (std::string json_str, int qos = 0)
{
    int result = -1;
    if (m_agent)
        result = m_agent->send_message(dev_id, json_str, qos);
    return result;
}
References dev_id, m_agent, and Slic3r::NetworkAgent::send_message().
Referenced by publish_json().
command_ams_calibrate()
int Slic3r::MachineObject::command_ams_calibrate (int ams_id)
{
    std::string gcode_cmd = (boost::format("M620 C%1% \n") % ams_id).str();
    BOOST_LOG_TRIVIAL(trace) << "ams_debug: gcode_cmd" << gcode_cmd;
    return this->publish_gcode(gcode_cmd);
}
References publish_gcode(), and Slic3r::trace().
Referenced by Slic3r::GUI::AMSSetting::on_select_ok().
command_ams_change_filament()
int Slic3r::MachineObject::command_ams_change_filament (int tray_id, int old_temp = 210, int new_temp = 210)
{
    json j;
    j["print"]["command"] = "ams_change_filament";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["target"] = tray_id;
    j["print"]["curr_temp"] = old_temp;
    j["print"]["tar_temp"] = new_temp;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
command_ams_control()
int Slic3r::MachineObject::command_ams_control (std::string action)
{
    //valid actions
    if (action == "resume" || action == "reset" || action == "pause" || action == "done") {
        json j;
        j["print"]["command"] = "ams_control";
        j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
        j["print"]["param"] = action;
        return this->publish_json(j.dump());
    }
    return -1;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::StatusPanel::on_ams_retry(), and Slic3r::GUI::StatusPanel::on_print_error_func().
command_ams_filament_settings()
int Slic3r::MachineObject::command_ams_filament_settings (int ams_id, int tray_id, std::string filament_id, std::string setting_id, std::string tray_color, std::string tray_type, int nozzle_temp_min, int nozzle_temp_max)
{
    BOOST_LOG_TRIVIAL(info) << "command_ams_filament_settings, ams_id = " << ams_id << ", tray_id = " << tray_id << ", tray_color = " << tray_color
                            << ", tray_type = " << tray_type << ", setting_id = " << setting_id;
    json j;
    j["print"]["command"]       = "ams_filament_setting";
    j["print"]["sequence_id"]   = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["ams_id"]        = ams_id;
    j["print"]["tray_id"]       = tray_id;
    j["print"]["tray_info_idx"] = filament_id;
    j["print"]["setting_id"]    = setting_id;
    // format "FFFFFFFF"   RGBA
    j["print"]["tray_color"]        = tray_color;
    j["print"]["nozzle_temp_min"]   = nozzle_temp_min;
    j["print"]["nozzle_temp_max"]   = nozzle_temp_max;
    j["print"]["tray_type"]         = tray_type;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), and Slic3r::GUI::AMSMaterialsSetting::on_select_reset().
command_ams_refresh_rfid()
int Slic3r::MachineObject::command_ams_refresh_rfid (std::string tray_id)
{
    std::string gcode_cmd = (boost::format("M620 R%1% \n") % tray_id).str();
    BOOST_LOG_TRIVIAL(trace) << "ams_debug: gcode_cmd" << gcode_cmd;
    return this->publish_gcode(gcode_cmd);
}
References publish_gcode(), and Slic3r::trace().
Referenced by Slic3r::GUI::StatusPanel::on_ams_refresh_rfid().
command_ams_select_tray()
int Slic3r::MachineObject::command_ams_select_tray (std::string tray_id)
{
    std::string gcode_cmd = (boost::format("M620 P%1% \n") % tray_id).str();
    BOOST_LOG_TRIVIAL(trace) << "ams_debug: gcode_cmd" << gcode_cmd;
    return this->publish_gcode(gcode_cmd);
}
References publish_gcode(), and Slic3r::trace().
Referenced by Slic3r::GUI::StatusPanel::on_ams_selected().
command_ams_switch()
int Slic3r::MachineObject::command_ams_switch (int tray_index, int old_temp = 210, int new_temp = 210)
{
    BOOST_LOG_TRIVIAL(trace) << "ams_switch to " << tray_index << " with temp: " << old_temp << ", " << new_temp;
    if (old_temp < 0) old_temp = FILAMENT_DEF_TEMP;
    if (new_temp < 0) new_temp = FILAMENT_DEF_TEMP;
    int tray_id_int = tray_index;
    std::string gcode = "";
    if (tray_index == 255) {
        gcode = DeviceManager::load_gcode(printer_type, "ams_unload.gcode");
    } else {
        // include VIRTUAL_TRAY_ID
        gcode = DeviceManager::load_gcode(printer_type, "ams_load.gcode");
        boost::replace_all(gcode, "[next_extruder]", std::to_string(tray_index));
        boost::replace_all(gcode, "[new_filament_temp]", std::to_string(new_temp));
    }
    return this->publish_gcode(gcode);
}
References FILAMENT_DEF_TEMP, Slic3r::DeviceManager::load_gcode(), printer_type, publish_gcode(), and Slic3r::trace().
Referenced by Slic3r::GUI::StatusPanel::on_ams_load_curr(), and Slic3r::GUI::StatusPanel::on_ams_unload().
command_ams_switch_filament()
int Slic3r::MachineObject::command_ams_switch_filament (bool switch_filament)
{
    json j;
    j["print"]["command"] = "print_option";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["auto_switch_filament"] = switch_filament;
    ams_auto_switch_filament_flag = switch_filament;
    BOOST_LOG_TRIVIAL(trace) << "command_ams_filament_settings:" << switch_filament;
    ams_print_option_count = HOLD_COUNT_MAX;
    return this->publish_json(j.dump());
}
References ams_auto_switch_filament_flag, ams_print_option_count, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), HOLD_COUNT_MAX, m_sequence_id, publish_json(), and Slic3r::trace().
Referenced by Slic3r::GUI::AMSSetting::on_switch_filament().
command_ams_user_settings() [1/2]
int Slic3r::MachineObject::command_ams_user_settings (int ams_id, AmsOptionType op, bool value)
{
    json j;
    j["print"]["command"]               = "ams_user_setting";
    j["print"]["sequence_id"]           = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["ams_id"]                = ams_id;
    if (op == AmsOptionType::AMS_OP_STARTUP_READ) {
        j["print"]["startup_read_option"] = value;
        ams_power_on_flag                 = value;
    } else if (op == AmsOptionType::AMS_OP_TRAY_READ) {
        j["print"]["tray_read_option"] = value;
        ams_insert_flag                = value;
    } else if (op == AmsOptionType::AMS_OP_CALIBRATE_REMAIN) {
        j["print"]["calibrate_remain_flag"] = value;
        ams_calibrate_remain_flag = value;
    } else {
        return -1;
    }
    ams_user_setting_hold_count = HOLD_COUNT_MAX;
    return this->publish_json(j.dump());
}
References ams_calibrate_remain_flag, ams_insert_flag, Slic3r::AMS_OP_CALIBRATE_REMAIN, Slic3r::AMS_OP_STARTUP_READ, Slic3r::AMS_OP_TRAY_READ, ams_power_on_flag, ams_user_setting_hold_count, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), HOLD_COUNT_MAX, m_sequence_id, and publish_json().
command_ams_user_settings() [2/2]
int Slic3r::MachineObject::command_ams_user_settings (int ams_id, bool start_read_opt, bool tray_read_opt, bool remain_flag = false)
{
    json j;
    j["print"]["command"] = "ams_user_setting";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["ams_id"] = ams_id;
    j["print"]["startup_read_option"]   = start_read_opt;
    j["print"]["tray_read_option"]      = tray_read_opt;
    j["print"]["calibrate_remain_flag"] = remain_flag;
    ams_insert_flag = tray_read_opt;
    ams_power_on_flag = start_read_opt;
    ams_calibrate_remain_flag = remain_flag;
    ams_user_setting_hold_count = HOLD_COUNT_MAX;
    return this->publish_json(j.dump());
}
References ams_calibrate_remain_flag, ams_insert_flag, ams_power_on_flag, ams_user_setting_hold_count, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), HOLD_COUNT_MAX, m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::AMSSetting::on_insert_material_read(), Slic3r::GUI::AMSSetting::on_remain(), and Slic3r::GUI::AMSSetting::on_starting_read().
command_auto_leveling()
int Slic3r::MachineObject::command_auto_leveling ()
{
    return this->publish_gcode("G29 \n");
}
References publish_gcode().
Referenced by Slic3r::GUI::StatusPanel::on_auto_leveling().
command_axis_control()
int Slic3r::MachineObject::command_axis_control (std::string axis, double unit = 1.0f, double value = 1.0f, int speed = 3000)
{
    char cmd[256];
    if (axis.compare("X") == 0
        || axis.compare("Y") == 0
        || axis.compare("Z") == 0) {
        sprintf(cmd, "M211 S \nM211 X1 Y1 Z1\nM1002 push_ref_mode\nG91 \nG1 %s%0.1f F%d\nM1002 pop_ref_mode\nM211 R\n", axis.c_str(), value * unit, speed);
    }
    else if (axis.compare("E") == 0) {
        sprintf(cmd, "M83 \nG0 %s%0.1f F%d\n", axis.c_str(), value * unit, speed);
        extruder_axis_status = (value >= 0.0f)? LOAD : UNLOAD;
    }
    else {
        return -1;
    }
    return this->publish_gcode(cmd);
}
References extruder_axis_status, LOAD, publish_gcode(), and UNLOAD.
Referenced by Slic3r::GUI::StatusPanel::axis_ctrl_e_hint(), Slic3r::GUI::StatusPanel::on_axis_ctrl_e_down_10(), Slic3r::GUI::StatusPanel::on_axis_ctrl_e_up_10(), Slic3r::GUI::StatusPanel::on_axis_ctrl_xy(), Slic3r::GUI::StatusPanel::on_axis_ctrl_z_down_1(), Slic3r::GUI::StatusPanel::on_axis_ctrl_z_down_10(), Slic3r::GUI::StatusPanel::on_axis_ctrl_z_up_1(), and Slic3r::GUI::StatusPanel::on_axis_ctrl_z_up_10().
command_clean_print_error()
int Slic3r::MachineObject::command_clean_print_error (std::string task_id, int print_error)
{
    BOOST_LOG_TRIVIAL(info) << "command_clean_print_error, id = " << subtask_id;
    json j;
    j["print"]["command"] = "clean_print_error";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["subtask_id"] = subtask_id;
    j["print"]["print_error"] = print_error;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, print_error, and publish_json().
Referenced by Slic3r::GUI::StatusPanel::show_error_message().
command_consistency_upgrade_confirm()
int Slic3r::MachineObject::command_consistency_upgrade_confirm ()
{
    BOOST_LOG_TRIVIAL(info) << "command_consistency_upgrade_confirm";
    json j;
    j["upgrade"]["command"] = "consistency_confirm";
    j["upgrade"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["upgrade"]["src_id"] = 1; // 1 for slicer
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::MachineInfoPanel::on_consisitency_upgrade_firmware(), and Slic3r::GUI::UpgradePanel::update().
command_control_fan()
int Slic3r::MachineObject::command_control_fan (FanType fan_type, bool on_off)
{
    std::string gcode = (boost::format("M106 P%1% S%2% \n") % (int)fan_type % (on_off ? 255 : 0)).str();
    return this->publish_gcode(gcode);
}
References int, and publish_gcode().
command_control_fan_val()
int Slic3r::MachineObject::command_control_fan_val (FanType fan_type, int val)
{
    std::string gcode = (boost::format("M106 P%1% S%2% \n") % (int)fan_type % (val)).str();
    return this->publish_gcode(gcode);
}
References int, and publish_gcode().
Referenced by Slic3r::GUI::FanControl::command_control_fan().
command_extrusion_cali_set()
int Slic3r::MachineObject::command_extrusion_cali_set (int tray_index, std::string setting_id, std::string name, float k, float n, int bed_temp = -1, int nozzle_temp = -1, float max_volumetric_speed = -1)
{
    BOOST_LOG_TRIVIAL(info) << "extrusion_cali: tray_id = " << tray_index << ", setting_id = " << setting_id << ", k = " << k
                            << ", n = " << n;
    json j;
    j["print"]["command"] = "extrusion_cali_set";
    j["print"]["sequence_id"]   = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["tray_id"]       = tray_index;
    //j["print"]["setting_id"]    = setting_id;
    //j["print"]["name"]          = name;
    j["print"]["k_value"]       = k;
    j["print"]["n_coef"]        = 1.4f;     // fixed n
    //j["print"]["n_coef"]        = n;
    if (bed_temp >= 0 && nozzle_temp >= 0 && max_volumetric_speed >= 0) {
        j["print"]["bed_temp"]      = bed_temp;
        j["print"]["nozzle_temp"]   = nozzle_temp;
        j["print"]["max_volumetric_speed"] = max_volumetric_speed;
    }
    return this->publish_json(j.dump());
}
References bed_temp, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, n, nozzle_temp, and publish_json().
Referenced by Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), and Slic3r::GUI::AMSMaterialsSetting::on_select_reset().
command_get_version()
int Slic3r::MachineObject::command_get_version (bool with_retry = true)
{
    BOOST_LOG_TRIVIAL(info) << "command_get_version";
    json j;
    j["info"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["info"]["command"] = "get_version";
    if (with_retry)
        get_version_retry = GET_VERSION_RETRYS;
    return this->publish_json(j.dump(), 1);
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), get_version_retry, GET_VERSION_RETRYS, m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::SendToPrinterDialog::on_selection_changed(), parse_json(), and Slic3r::GUI::UpgradePanel::refresh_version_and_firmware().
command_go_home()
int Slic3r::MachineObject::command_go_home ()
{
    return this->publish_gcode("G28 \n");
}
References publish_gcode().
Referenced by Slic3r::GUI::StatusPanel::on_axis_ctrl_xy(), and Slic3r::GUI::StatusPanel::show_recenter_dialog().
command_ipcam_record()
int Slic3r::MachineObject::command_ipcam_record (bool on_off)
{
    BOOST_LOG_TRIVIAL(info) << "command_ipcam_record = " << on_off;
    json j;
    j["camera"]["command"] = "ipcam_record_set";
    j["camera"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["camera"]["control"] = on_off ? "enable" : "disable";
    camera_recording_hold_count = HOLD_COUNT_CAMERA;
    this->camera_recording_when_printing = on_off;
    return this->publish_json(j.dump());
}
References camera_recording_hold_count, camera_recording_when_printing, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), HOLD_COUNT_CAMERA, m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::CameraPopup::on_switch_recording().
command_ipcam_resolution_set()
int Slic3r::MachineObject::command_ipcam_resolution_set (std::string resolution)
{
    BOOST_LOG_TRIVIAL(info) << "command:ipcam_resolution_set" << ", resolution:" << resolution;
    json j;
    j["camera"]["command"] = "ipcam_resolution_set";
    j["camera"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["camera"]["resolution"] = resolution;
    camera_resolution_hold_count = HOLD_COUNT_CAMERA;
    camera_recording_hold_count = HOLD_COUNT_CAMERA;
    this->camera_resolution = resolution;
    return this->publish_json(j.dump());
}
References camera_recording_hold_count, camera_resolution, camera_resolution_hold_count, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), HOLD_COUNT_CAMERA, m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::CameraPopup::on_set_resolution().
command_ipcam_timelapse()
int Slic3r::MachineObject::command_ipcam_timelapse (bool on_off)
{
    BOOST_LOG_TRIVIAL(info) << "command_ipcam_timelapse " << on_off;
    json j;
    j["camera"]["command"] = "ipcam_timelapse";
    j["camera"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["camera"]["control"] = on_off ? "enable" : "disable";
    camera_timelapse_hold_count = HOLD_COUNT_CAMERA;
    this->camera_timelapse = on_off;
    return this->publish_json(j.dump());
}
References camera_timelapse, camera_timelapse_hold_count, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), HOLD_COUNT_CAMERA, m_sequence_id, and publish_json().
command_pushing()
int Slic3r::MachineObject::command_pushing (std::string cmd)
{
    auto curr_time = std::chrono::system_clock::now();
    auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(curr_time - last_request_start);
    if (diff.count() < REQUEST_START_MIN_TIME) {
        BOOST_LOG_TRIVIAL(trace) << "static: command_request_start: send request too fast, dev_id=" << dev_id;
        return -1;
    }
    else {
        BOOST_LOG_TRIVIAL(trace) << "static: command_request_start, dev_id=" << dev_id;
        last_request_start = std::chrono::system_clock::now();
    }
    if (cmd == "start" || cmd == "stop") {
        json j;
        j["pushing"]["command"] = cmd;
        j["pushing"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
        return this->publish_json(j.dump());
    }
    return -1;
}
References dev_id, Slic3r::diff(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), last_request_start, m_sequence_id, publish_json(), REQUEST_START_MIN_TIME, and Slic3r::trace().
Referenced by Slic3r::DeviceManager::check_pushing().
command_request_push_all()
int Slic3r::MachineObject::command_request_push_all ()
{
    auto curr_time = std::chrono::system_clock::now();
    auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(curr_time - last_request_push);
    if (diff.count() < REQUEST_PUSH_MIN_TIME) {
        BOOST_LOG_TRIVIAL(trace) << "static: command_request_push_all: send request too fast, dev_id=" << dev_id;
        return -1;
    } else {
        BOOST_LOG_TRIVIAL(trace) << "static: command_request_push_all, dev_id=" << dev_id;
        last_request_push = std::chrono::system_clock::now();
    }
    json j;
    j["pushing"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["pushing"]["command"]     = "pushall";
    return this->publish_json(j.dump());
}
References dev_id, Slic3r::diff(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), last_request_push, m_sequence_id, publish_json(), REQUEST_PUSH_MIN_TIME, and Slic3r::trace().
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), and parse_json().
command_set_bed()
int Slic3r::MachineObject::command_set_bed (int temp)
{
    std::string gcode_str = (boost::format("M140 S%1%\n") % temp).str();
    return this->publish_gcode(gcode_str);
}
References publish_gcode().
Referenced by Slic3r::GUI::StatusPanel::on_set_bed_temp().
command_set_chamber_light()
int Slic3r::MachineObject::command_set_chamber_light (LIGHT_EFFECT effect, int on_time = 500, int off_time = 500, int loops = 1, int interval = 1000)
{
    json j;
    j["system"]["command"] = "ledctrl";
    j["system"]["led_node"] = "chamber_light";
    j["system"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["system"]["led_mode"] = light_effect_str(effect);
    j["system"]["led_on_time"] = on_time;
    j["system"]["led_off_time"] = off_time;
    j["system"]["loop_times"] = loops;
    j["system"]["interval_time"] = interval;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), light_effect_str(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::StatusPanel::on_lamp_switch().
command_set_nozzle()
int Slic3r::MachineObject::command_set_nozzle (int temp)
{
    std::string gcode_str = (boost::format("M104 S%1%\n") % temp).str();
    return this->publish_gcode(gcode_str);
}
References publish_gcode().
Referenced by Slic3r::GUI::StatusPanel::on_set_nozzle_temp().
command_set_printing_option()
int Slic3r::MachineObject::command_set_printing_option (bool auto_recovery)
{
    int print_option = (int)auto_recovery << (int)PRINT_OP_AUTO_RECOVERY;
    json j;
    j["print"]["command"]       = "print_option";
    j["print"]["sequence_id"]   = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["option"]        = print_option;
    j["print"]["auto_recovery"] = auto_recovery;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), int, m_sequence_id, PRINT_OP_AUTO_RECOVERY, and publish_json().
Referenced by command_xcam_control_auto_recovery_step_loss().
command_set_printing_speed()
int Slic3r::MachineObject::command_set_printing_speed (PrintingSpeedLevel lvl)
{
    json j;
    j["print"]["command"] = "print_speed";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["param"] = std::to_string((int)lvl);
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::StatusPanel::on_switch_speed().
command_set_work_light()
int Slic3r::MachineObject::command_set_work_light (LIGHT_EFFECT effect, int on_time = 500, int off_time = 500, int loops = 1, int interval = 1000)
{
    json j;
    j["system"]["command"] = "ledctrl";
    j["system"]["led_node"] = "work_light";
    j["system"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["system"]["led_mode"] = light_effect_str(effect);
    j["system"]["led_on_time"] = on_time;
    j["system"]["led_off_time"] = off_time;
    j["system"]["loop_times"] = loops;
    j["system"]["interval_time"] = interval;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), light_effect_str(), m_sequence_id, and publish_json().
command_start_calibration()
int Slic3r::MachineObject::command_start_calibration (bool vibration, bool bed_leveling, bool xcam_cali)
{
    if (!is_support_command_calibration()) {
        // fixed gcode file
        json j;
        j["print"]["command"] = "gcode_file";
        j["print"]["param"] = "/usr/etc/print/auto_cali_for_user.gcode";
        j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
        return this->publish_json(j.dump());
    } else {
        json j;
        j["print"]["command"] = "calibration";
        j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
        j["print"]["option"] =      (vibration    ? 1 << 2 : 0)
                                +   (bed_leveling ? 1 << 1 : 0)
                                +   (xcam_cali    ? 1 << 0 : 0);
        return this->publish_json(j.dump());
    }
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), is_support_command_calibration(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::CalibrationDialog::on_start_calibration().
command_start_extrusion_cali()
int Slic3r::MachineObject::command_start_extrusion_cali (int tray_index, int nozzle_temp, int bed_temp, float max_volumetric_speed, std::string setting_id = "")
{
    BOOST_LOG_TRIVIAL(info) << "extrusion_cali: tray_id = " << tray_index << ", nozzle_temp = " << nozzle_temp << ", bed_temp = " << bed_temp
                            << ", max_volumetric_speed = " << max_volumetric_speed;
    json j;
    j["print"]["command"] = "extrusion_cali";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["print"]["tray_id"] = tray_index;
    //j["print"]["setting_id"] = setting_id;
    //j["print"]["name"] = "";
    j["print"]["nozzle_temp"] = nozzle_temp;
    j["print"]["bed_temp"] = bed_temp;
    j["print"]["max_volumetric_speed"] = max_volumetric_speed;
    // enter extusion cali
    last_extrusion_cali_start_time = std::chrono::system_clock::now();
    return this->publish_json(j.dump());
}
References bed_temp, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), last_extrusion_cali_start_time, m_sequence_id, nozzle_temp, and publish_json().
Referenced by Slic3r::GUI::ExtrusionCalibration::on_click_cali().
command_stop_extrusion_cali()
int Slic3r::MachineObject::command_stop_extrusion_cali ()
{
    BOOST_LOG_TRIVIAL(info) << "extrusion_cali: stop";
    if (is_in_extrusion_cali()) {
        return command_task_abort();
    }
    return 0;
}
References command_task_abort(), and is_in_extrusion_cali().
Referenced by Slic3r::GUI::ExtrusionCalibration::on_click_cancel().
command_task_abort()
int Slic3r::MachineObject::command_task_abort ()
{
    json j;
    j["print"]["command"] = "stop";
    j["print"]["param"] = "";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    return this->publish_json(j.dump(), 1);
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by command_stop_extrusion_cali(), and Slic3r::GUI::StatusPanel::on_subtask_abort().
command_task_pause()
int Slic3r::MachineObject::command_task_pause ()
{
    json j;
    j["print"]["command"] = "pause";
    j["print"]["param"] = "";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    return this->publish_json(j.dump(), 1);
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::StatusPanel::on_subtask_pause_resume().
command_task_resume()
int Slic3r::MachineObject::command_task_resume ()
{
    json j;
    j["print"]["command"] = "resume";
    j["print"]["param"] = "";
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    return this->publish_json(j.dump(), 1);
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::StatusPanel::on_subtask_pause_resume().
command_unload_filament()
int Slic3r::MachineObject::command_unload_filament ()
{
    if ((printer_type == "BL-P001" || printer_type == "BL-P002")
        && !this->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY)) {
        // fixed gcode file
        json j;
        j["print"]["command"] = "gcode_file";
        j["print"]["param"] = "/usr/etc/print/filament_unload.gcode";
        j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
        return this->publish_json(j.dump());
    }
    else if (printer_type == "C11"
        || ((printer_type == "BL-P001" || printer_type == "BL-P002")
        && this->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY))
        ) {
        std::string gcode = DeviceManager::load_gcode(printer_type, "ams_unload.gcode");
        if (gcode.empty()) {
            return -1;
        }
        json j;
        j["print"]["command"] = "gcode_line";
        j["print"]["param"] = gcode;
        j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
        if (m_agent)
            j["print"]["user_id"] = m_agent->get_user_id();
        return this->publish_json(j.dump());
    }
    else {
        json j;
        j["print"]["command"] = "unload_filament";
        j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
        return this->publish_json(j.dump());
    }
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), Slic3r::FUNC_VIRTUAL_TYAY, Slic3r::NetworkAgent::get_user_id(), is_function_supported(), Slic3r::DeviceManager::load_gcode(), m_agent, m_sequence_id, printer_type, and publish_json().
Referenced by Slic3r::GUI::StatusPanel::on_start_unload().
command_upgrade_confirm()
int Slic3r::MachineObject::command_upgrade_confirm ()
{
    BOOST_LOG_TRIVIAL(info) << "command_upgrade_confirm";
    json j;
    j["upgrade"]["command"] = "upgrade_confirm";
    j["upgrade"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["upgrade"]["src_id"] = 1; // 1 for slicer
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by Slic3r::GUI::MachineInfoPanel::confirm_upgrade(), and Slic3r::GUI::UpgradePanel::update().
command_upgrade_firmware()
int Slic3r::MachineObject::command_upgrade_firmware (FirmwareInfo info)
{
    std::string version     = info.version;
    std::string dst_url     = info.url;
    std::string module_name = info.module_type;
    json j;
    j["upgrade"]["command"]     = "start";
    j["upgrade"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["upgrade"]["url"]         = info.url;
    j["upgrade"]["module"]      = info.module_type;
    j["upgrade"]["version"]     = info.version;
    j["upgrade"]["src_id"]      = 1;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, Slic3r::FirmwareInfo::module_type, publish_json(), Slic3r::FirmwareInfo::url, and Slic3r::FirmwareInfo::version.
Referenced by Slic3r::GUI::MachineInfoPanel::upgrade_firmware_internal().
command_upgrade_module()
int Slic3r::MachineObject::command_upgrade_module (std::string url, std::string module_type, std::string version)
{
    json j;
    j["upgrade"]["command"] = "start";
    j["upgrade"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["upgrade"]["url"] = url;
    j["upgrade"]["module"] = module_type;
    j["upgrade"]["version"] = version;
    j["upgrade"]["src_id"] = 1;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
command_xcam_control()
int Slic3r::MachineObject::command_xcam_control (std::string module_name, bool on_off, std::string lvl = "")
{
    json j;
    j["xcam"]["command"] = "xcam_control_set";
    j["xcam"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    j["xcam"]["module_name"] = module_name;
    j["xcam"]["control"] = on_off;
    j["xcam"]["enable"] = on_off;       //old protocol
    j["xcam"]["print_halt"]  = true;    //old protocol
    if (!lvl.empty()) {
        j["xcam"]["halt_print_sensitivity"] = lvl;
    }
    BOOST_LOG_TRIVIAL(info) << "command:xcam_control_set" << ", module_name:" << module_name << ", control:" << on_off << ", halt_print_sensitivity:" << lvl;
    return this->publish_json(j.dump());
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), m_sequence_id, and publish_json().
Referenced by command_xcam_control_ai_monitoring(), command_xcam_control_buildplate_marker_detector(), and command_xcam_control_first_layer_inspector().
command_xcam_control_ai_monitoring()
int Slic3r::MachineObject::command_xcam_control_ai_monitoring (bool on_off, std::string lvl)
{
    bool print_halt = (lvl == "never_halt") ? false:true;
    xcam_ai_monitoring = on_off;
    xcam_ai_monitoring_hold_count = HOLD_COUNT_MAX;
    xcam_ai_monitoring_sensitivity = lvl;
    return command_xcam_control("printing_monitor", on_off, lvl);
}
References command_xcam_control(), HOLD_COUNT_MAX, xcam_ai_monitoring, xcam_ai_monitoring_hold_count, and xcam_ai_monitoring_sensitivity.
Referenced by Slic3r::GUI::PrintOptionsDialog::PrintOptionsDialog(), and Slic3r::GUI::PrintOptionsDialog::set_ai_monitor_sensitivity().
command_xcam_control_auto_recovery_step_loss()
int Slic3r::MachineObject::command_xcam_control_auto_recovery_step_loss (bool on_off)
{
    xcam_auto_recovery_step_loss = on_off;
    xcam_auto_recovery_hold_count = HOLD_COUNT_MAX;
    return command_set_printing_option(on_off);
}
References command_set_printing_option(), HOLD_COUNT_MAX, xcam_auto_recovery_hold_count, and xcam_auto_recovery_step_loss.
Referenced by Slic3r::GUI::PrintOptionsDialog::PrintOptionsDialog().
command_xcam_control_buildplate_marker_detector()
int Slic3r::MachineObject::command_xcam_control_buildplate_marker_detector (bool on_off)
{
    xcam_buildplate_marker_detector = on_off;
    xcam_buildplate_marker_hold_count = HOLD_COUNT_MAX;
    return command_xcam_control("buildplate_marker_detector", on_off);
}
References command_xcam_control(), HOLD_COUNT_MAX, xcam_buildplate_marker_detector, and xcam_buildplate_marker_hold_count.
Referenced by Slic3r::GUI::PrintOptionsDialog::PrintOptionsDialog().
command_xcam_control_first_layer_inspector()
int Slic3r::MachineObject::command_xcam_control_first_layer_inspector (bool on_off, bool print_halt)
{
    xcam_first_layer_inspector = on_off;
    xcam_first_layer_hold_count = HOLD_COUNT_MAX;
    return command_xcam_control("first_layer_inspector", on_off);
}
References command_xcam_control(), HOLD_COUNT_MAX, xcam_first_layer_hold_count, and xcam_first_layer_inspector.
Referenced by Slic3r::GUI::PrintOptionsDialog::PrintOptionsDialog().
command_xyz_abs()
int Slic3r::MachineObject::command_xyz_abs ()
{
    return this->publish_gcode("G90 \n");
}
References publish_gcode().
Referenced by Slic3r::GUI::StatusPanel::on_xyz_abs().
connect()
int Slic3r::MachineObject::connect (bool is_anonymous = false)
{
    std::string username;
    std::string password;
    if (!is_anonymous) {
        username = "bblp";
        password = get_access_code();
    }
    if (m_agent) {
        try {
            return m_agent->connect_printer(dev_id, dev_ip, username, password);
        } catch (...) {
            ;
        }
    }
    return -1;
}
References Slic3r::NetworkAgent::connect_printer(), dev_id, dev_ip, get_access_code(), and m_agent.
connection_type()
std::string Slic3r::MachineObject::connection_type () inline
{ return dev_connection_type; }
References dev_connection_type.
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SendToPrinterDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_ok(), and Slic3r::GUI::MonitorPanel::update_all().
disconnect()
int Slic3r::MachineObject::disconnect ()
{
    if (m_agent) {
        return m_agent->disconnect_printer();
    }
    return -1;
}
References Slic3r::NetworkAgent::disconnect_printer(), and m_agent.
get_access_code()
std::string Slic3r::MachineObject::get_access_code ()
{
    if (get_user_access_code().empty())
        return access_code;
    return get_user_access_code();
}
References access_code, Slic3r::empty(), and get_user_access_code().
Referenced by connect(), has_access_right(), Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SendToPrinterDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::set_machine_obj(), Slic3r::GUI::MediaFilePanel::SetMachineObject(), and Slic3r::GUI::MediaPlayCtrl::SetMachineObject().
get_ams_tray()
AmsTray * Slic3r::MachineObject::get_ams_tray (std::string ams_id, std::string tray_id)
{
    auto it = amsList.find(ams_id);
    if (it == amsList.end()) return nullptr;
    if (!it->second) return nullptr;
    auto iter = it->second->trayList.find(tray_id);
    if (iter != it->second->trayList.end())
        return iter->second;
    else
        return nullptr;
}
References amsList.
Referenced by Slic3r::GUI::StatusPanel::on_ams_load_curr().
get_ams_version()
std::map< int, MachineObject::ModuleVersionInfo > Slic3r::MachineObject::get_ams_version ()
{
    std::map<int, ModuleVersionInfo> result;
    for (int i = 0; i < 4; i++) {
        std::string ams_id = "ams/" + std::to_string(i);
        auto it = module_vers.find(ams_id);
        if (it != module_vers.end()) {
            result.emplace(std::pair(i, it->second));
        }
    }
    return result;
}
References module_vers.
Referenced by Slic3r::GUI::MachineInfoPanel::update_ams_ext().
get_bed_temperature_limit()
int Slic3r::MachineObject::get_bed_temperature_limit ()
{
    if (printer_type == "BL-P001" || printer_type == "BL-P002") {
        if (is_220V_voltage)
            return 110;
        else {
            return 120;
        }
    } else {
        int limit = BED_TEMP_LIMIT;
        DeviceManager::get_bed_temperature_limit(printer_type, limit);
        return limit;
    }
    return BED_TEMP_LIMIT;
}
References BED_TEMP_LIMIT, Slic3r::DeviceManager::get_bed_temperature_limit(), is_220V_voltage, and printer_type.
Referenced by Slic3r::GUI::StatusPanel::on_set_bed_temp(), and Slic3r::GUI::StatusPanel::update_temp_ctrl().
get_bind_str()
std::string Slic3r::MachineObject::get_bind_str ()
{
    std::string default_result = "N/A";
    if (bind_user_name.compare("null") == 0) {
        return "Free";
    }
    else if (!bind_user_name.empty()) {
        return bind_user_name;
    }
    return default_result;
}
References bind_user_name.
get_curr_Ams()
Ams * Slic3r::MachineObject::get_curr_Ams ()
{
    auto it = amsList.find(m_ams_id);
    if (it != amsList.end())
        return it->second;
    return nullptr;
}
References amsList, and m_ams_id.
Referenced by get_curr_tray().
get_curr_stage()
wxString Slic3r::MachineObject::get_curr_stage ()
{
    if (stage_list_info.empty()) {
        return "";
    }
    return get_stage_string(stage_curr);
}
References get_stage_string(), stage_curr, and stage_list_info.
Referenced by Slic3r::GUI::StatusPanel::update_subtask().
get_curr_stage_idx()
int Slic3r::MachineObject::get_curr_stage_idx ()
{
    int result = -1;
    for (int i = 0; i < stage_list_info.size(); i++) {
        if (stage_list_info[i] == stage_curr) {
            return i;
        }
    }
    return -1;
}
References stage_curr, and stage_list_info.
Referenced by Slic3r::GUI::CalibrationDialog::update_cali().
get_curr_tray()
AmsTray * Slic3r::MachineObject::get_curr_tray ()
{
    if (m_tray_now.compare(std::to_string(VIRTUAL_TRAY_ID)) == 0) {
        return &vt_tray;
    }
    Ams* curr_ams = get_curr_Ams();
    if (!curr_ams) return nullptr;
    try {
        int tray_index = atoi(m_tray_now.c_str());
        int ams_index = atoi(curr_ams->id.c_str());
        std::string tray_now_index = std::to_string(tray_index - ams_index * 4);
        auto it = curr_ams->trayList.find(tray_now_index);
        if (it != curr_ams->trayList.end())
            return it->second;
    }
    catch (...) {
        ;
    }
    return nullptr;
}
References get_curr_Ams(), Slic3r::Ams::id, m_tray_now, Slic3r::Ams::trayList, VIRTUAL_TRAY_ID, and vt_tray.
Referenced by Slic3r::GUI::StatusPanel::on_ams_load_curr().
get_firmware_info()
void Slic3r::MachineObject::get_firmware_info ()
{
    m_firmware_valid = false;
    if (m_firmware_thread_started)
        return;
    boost::thread update_info_thread = Slic3r::create_thread(
        [&] {
            m_firmware_thread_started = true;
            int          result = 0;
            unsigned int http_code;
            std::string  http_body;
            if (!m_agent) return;
            result = m_agent->get_printer_firmware(dev_id, &http_code, &http_body);
            if (result < 0) {
                // get upgrade list failed
                return;
            }
            try {
                json j = json::parse(http_body);
                if (j.contains("devices") && !j["devices"].is_null()) {
                    firmware_list.clear();
                    for (json::iterator it = j["devices"].begin(); it != j["devices"].end(); it++) {
                        if ((*it)["dev_id"].get<std::string>() == this->dev_id) {
                            try {
                                json firmware = (*it)["firmware"];
                                for (json::iterator firmware_it = firmware.begin(); firmware_it != firmware.end(); firmware_it++) {
                                    FirmwareInfo item;
                                    item.version = (*firmware_it)["version"].get<std::string>();
                                    item.url = (*firmware_it)["url"].get<std::string>();
                                    if ((*firmware_it).contains("description"))
                                        item.description = (*firmware_it)["description"].get<std::string>();
                                    item.module_type = "ota";
                                    int name_start = item.url.find_last_of('/') + 1;
                                    if (name_start > 0) {
                                        item.name = item.url.substr(name_start, item.url.length() - name_start);
                                        firmware_list.push_back(item);
                                    }
                                    else {
                                        BOOST_LOG_TRIVIAL(trace) << "skip";
                                    }
                                }
                            }
                            catch (...) {}
                            try {
                                if ((*it).contains("ams")) {
                                    json ams_list = (*it)["ams"];
                                    if (ams_list.size() > 0) {
                                        auto ams_front = ams_list.front();
                                        json firmware_ams = (ams_front)["firmware"];
                                        for (json::iterator ams_it = firmware_ams.begin(); ams_it != firmware_ams.end(); ams_it++) {
                                            FirmwareInfo item;
                                            item.version = (*ams_it)["version"].get<std::string>();
                                            item.url = (*ams_it)["url"].get<std::string>();
                                            if ((*ams_it).contains("description"))
                                                item.description = (*ams_it)["description"].get<std::string>();
                                            item.module_type = "ams";
                                            int name_start = item.url.find_last_of('/') + 1;
                                            if (name_start > 0) {
                                                item.name = item.url.substr(name_start, item.url.length() - name_start);
                                                firmware_list.push_back(item);
                                            }
                                            else {
                                                BOOST_LOG_TRIVIAL(trace) << "skip";
                                            }
                                        }
                                    }
                                }
                            }
                            catch (...) {
                                ;
                            }
                        }
                    }
                }
            }
            catch (...) {
                return;
            }
            m_firmware_thread_started = false;
            m_firmware_valid = true;
        }
    );
    return;
}
References nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), Slic3r::create_thread(), Slic3r::FirmwareInfo::description, dev_id, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), firmware_list, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::front(), Slic3r::NetworkAgent::get_printer_firmware(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::is_null(), m_agent, m_firmware_thread_started, m_firmware_valid, Slic3r::FirmwareInfo::module_type, Slic3r::FirmwareInfo::name, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::size(), Slic3r::trace(), Slic3r::FirmwareInfo::url, and Slic3r::FirmwareInfo::version.
Referenced by Slic3r::GUI::UpgradePanel::refresh_version_and_firmware().
get_firmware_type_str()
std::string Slic3r::MachineObject::get_firmware_type_str ()
{
    if (firmware_type == PrinterFirmwareType::FIRMWARE_TYPE_ENGINEER)
        return "engineer";
    else if (firmware_type == PrinterFirmwareType::FIRMWARE_TYPE_PRODUCTION)
        return "product";
    // return engineer by default;
    return "engineer";
}
References firmware_type, Slic3r::FIRMWARE_TYPE_ENGINEER, and Slic3r::FIRMWARE_TYPE_PRODUCTION.
get_ftp_folder()
std::string Slic3r::MachineObject::get_ftp_folder ()
{
    return DeviceManager::get_ftp_folder(printer_type);
}
References Slic3r::DeviceManager::get_ftp_folder(), and printer_type.
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok().
get_lan_mode_connection_state()
bool Slic3r::MachineObject::get_lan_mode_connection_state () inline
{return m_lan_mode_connection_state;};
References m_lan_mode_connection_state.
Referenced by Slic3r::GUI::SelectMachineDialog::on_selection_changed(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
get_ota_version()
std::string Slic3r::MachineObject::get_ota_version ()
{
    auto it = module_vers.find("ota");
    if (it != module_vers.end()) {
        //double check name
        if (it->second.name == "ota") {
            return it->second.sw_ver;
        }
    }
    return "";
}
References module_vers.
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok(), and Slic3r::GUI::MachineInfoPanel::on_show_release_note().
get_preset_printer_model_name()
std::string Slic3r::MachineObject::get_preset_printer_model_name (std::string printer_type) static
{
    return DeviceManager::get_printer_display_name(printer_type);
}
References Slic3r::DeviceManager::get_printer_display_name(), and printer_type.
Referenced by get_printer_type_display_str(), and Slic3r::GUI::AMSMaterialsSetting::Popup().
get_preset_printer_thumbnail_img()
std::string Slic3r::MachineObject::get_preset_printer_thumbnail_img (std::string printer_type) static
{
    return DeviceManager::get_printer_thumbnail_img(printer_type);
}
References Slic3r::DeviceManager::get_printer_thumbnail_img(), and printer_type.
Referenced by get_printer_thumbnail_img_str().
get_printer_thumbnail_img_str()
std::string Slic3r::MachineObject::get_printer_thumbnail_img_str ()
{
    std::string img_str = get_preset_printer_thumbnail_img(printer_type);
    if (!img_str.empty())
        return img_str;
    else
        return "printer_thumbnail";
}
References get_preset_printer_thumbnail_img(), and printer_type.
Referenced by Slic3r::GUI::MachineInfoPanel::Update_printer_img().
get_printer_type_display_str()
wxString Slic3r::MachineObject::get_printer_type_display_str ()
{
    std::string display_name = get_preset_printer_model_name(printer_type);
    if (!display_name.empty())
        return display_name;
    else
        return _L("Unknown");
}
References _L, get_preset_printer_model_name(), and printer_type.
Referenced by Slic3r::GUI::MachineInfoPanel::update().
get_resolution_supported()
std::vector< std::string > Slic3r::MachineObject::get_resolution_supported ()
{
    return DeviceManager::get_resolution_supported(printer_type);
}
References Slic3r::DeviceManager::get_resolution_supported(), and printer_type.
Referenced by Slic3r::GUI::CameraPopup::check_func_supported().
get_sdcard_state()
MachineObject::SdcardState Slic3r::MachineObject::get_sdcard_state ()
{
    return sdcard_state;
}
References sdcard_state.
Referenced by Slic3r::GUI::SelectMachineDialog::has_tips(), Slic3r::GUI::StatusPanel::rescale_camera_icons(), Slic3r::GUI::StatusPanel::update_camera_state(), Slic3r::GUI::SelectMachineDialog::update_show_status(), and Slic3r::GUI::SendToPrinterDialog::update_show_status().
get_subtask()
BBLSubTask * Slic3r::MachineObject::get_subtask ()
{
    if (!subtask_)
        subtask_ = new BBLSubTask(nullptr);
    return subtask_;
}
References subtask_.
Referenced by parse_json().
get_upgrade_percent()
int Slic3r::MachineObject::get_upgrade_percent ()
{
    if (upgrade_progress.empty())
        return 0;
    try {
        int result = atoi(upgrade_progress.c_str());
        return result;
    } catch(...) {
        ;
    }
    return 0;
}
References upgrade_progress.
Referenced by Slic3r::GUI::MachineInfoPanel::update().
get_upgrade_result_str()
wxString Slic3r::MachineObject::get_upgrade_result_str (int upgrade_err_code)
{
    switch(err_code) {
    case UpgradeNoError:
        return _L("Update successful.");
    case UpgradeDownloadFailed:
        return _L("Downloading failed.");
    case UpgradeVerfifyFailed:
        return _L("Verification failed.");
    case UpgradeFlashFailed:
        return _L("Update failed.");
    case UpgradePrinting:
        return _L("Update failed.");
    default:
        return _L("Update failed.");
    }
    return "";
}
References _L, UpgradeDownloadFailed, UpgradeFlashFailed, UpgradeNoError, UpgradePrinting, and UpgradeVerfifyFailed.
Referenced by Slic3r::GUI::MachineInfoPanel::update().
get_user_access_code()
std::string Slic3r::MachineObject::get_user_access_code ()
{
    AppConfig* config = GUI::wxGetApp().app_config;
    if (config) {
        return GUI::wxGetApp().app_config->get("user_access_code", dev_id);
    }
    return "";
}
References dev_id, and Slic3r::AppConfig::get().
Referenced by get_access_code().
has_access_right()
bool Slic3r::MachineObject::has_access_right () inline
{ return !get_access_code().empty(); }
References get_access_code().
Referenced by Slic3r::GUI::MachineObjectPanel::on_mouse_left_up(), Slic3r::GUI::SelectMachineDialog::update_lan_machine_list(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
has_ams()
bool Slic3r::MachineObject::has_ams () inline
{ return ams_exist_bits != 0; }
References ams_exist_bits.
Referenced by can_unload_filament(), is_support_ams_mapping(), Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SelectMachineDialog::on_ok_btn(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::SelectMachineDialog::update_ams_check(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
has_sdcard()
bool Slic3r::MachineObject::has_sdcard ()
{
    return (sdcard_state == MachineObject::SdcardState::HAS_SDCARD_NORMAL);
}
References HAS_SDCARD_NORMAL, and sdcard_state.
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SendToPrinterDialog::on_ok(), and Slic3r::GUI::InputIpAddressDialog::on_ok().
is_ams_unload()
bool Slic3r::MachineObject::is_ams_unload () inline
{ return m_tray_tar.compare("255") == 0; }
References m_tray_tar.
Referenced by Slic3r::GUI::StatusPanel::update_ams().
is_avaliable()
bool Slic3r::MachineObject::is_avaliable () inline
{ return bind_state == "free"; }
References bind_state.
Referenced by Slic3r::GUI::MachineObjectPanel::on_mouse_left_up(), Slic3r::GUI::SelectMachineDialog::update_lan_machine_list(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
is_axis_at_home()
bool Slic3r::MachineObject::is_axis_at_home (std::string axis)
{
    if (home_flag < 0)
        return true;
    if (axis == "X") {
        return home_flag & 1 == 1;
    } else if (axis == "Y") {
        return home_flag >> 1 & 1 == 1;
    } else if (axis == "Z") {
        return home_flag >> 2 & 1 == 1;
    } else {
        return true;
    }
}
References home_flag.
Referenced by Slic3r::GUI::StatusPanel::check_axis_z_at_home(), and Slic3r::GUI::StatusPanel::on_axis_ctrl_xy().
is_bbl_filament()
bool Slic3r::MachineObject::is_bbl_filament (std::string tag_uid) static
{
    if (tag_uid.empty())
        return false;
    for (int i = 0; i < tag_uid.length(); i++) {
        if (tag_uid[i] != '0')
            return true;
    }
    return false;
}
Referenced by Slic3r::GUI::StatusPanel::on_ext_spool_edit(), Slic3r::GUI::StatusPanel::on_filament_edit(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), and Slic3r::GUI::AMSinfo::parse_ams_info().
is_calibration_done()
bool Slic3r::MachineObject::is_calibration_done ()
{
    return calibration_done;
}
References calibration_done.
Referenced by Slic3r::GUI::CalibrationDialog::on_start_calibration(), and Slic3r::GUI::CalibrationDialog::update_cali().
is_calibration_running()
bool Slic3r::MachineObject::is_calibration_running ()
{
    if (is_in_calibration() && is_in_printing_status(print_status))
        return true;
    return false;
}
References is_in_calibration(), is_in_printing_status(), and print_status.
Referenced by Slic3r::GUI::CalibrationDialog::update_cali(), and Slic3r::GUI::StatusPanel::update_cali().
is_connected()
bool Slic3r::MachineObject::is_connected ()
{
    std::chrono::system_clock::time_point curr_time = std::chrono::system_clock::now();
    auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(curr_time - last_update_time);
    if (diff.count() > DISCONNECT_TIMEOUT) {
        BOOST_LOG_TRIVIAL(trace) << "machine_object: dev_id=" << dev_id <<", diff count = " << diff.count();
        return false;
    }
    if (!is_lan_mode_printer()) {
        NetworkAgent* m_agent = Slic3r::GUI::wxGetApp().getAgent();
        if (m_agent) {
            return m_agent->is_server_connected();
        }
    }
    return true;
}
References dev_id, Slic3r::diff(), DISCONNECT_TIMEOUT, is_lan_mode_printer(), Slic3r::NetworkAgent::is_server_connected(), last_update_time, m_agent, and Slic3r::trace().
Referenced by is_connecting(), Slic3r::GUI::MachineInfoPanel::update(), Slic3r::GUI::MonitorPanel::update_all(), Slic3r::GUI::StatusPanel::update_ams(), and Slic3r::GUI::MonitorPanel::update_status().
is_connecting()
bool Slic3r::MachineObject::is_connecting ()
{
    return is_connected() && m_push_count == 0;
}
References is_connected(), and m_push_count.
Referenced by Slic3r::GUI::MonitorPanel::update_all(), and Slic3r::GUI::MonitorPanel::update_status().
is_extrusion_cali_finished()
bool Slic3r::MachineObject::is_extrusion_cali_finished ()
{
    auto curr_time = std::chrono::system_clock::now();
    auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(curr_time - last_extrusion_cali_start_time);
    if (diff.count() < EXTRUSION_OMIT_TIME) {
        return false;
    }
    if (boost::contains(m_gcode_file, "extrusion_cali")
        && this->mc_print_percent == 100)
        return true;
    else
        return false;
}
References Slic3r::diff(), EXTRUSION_OMIT_TIME, last_extrusion_cali_start_time, m_gcode_file, and mc_print_percent.
Referenced by Slic3r::GUI::ExtrusionCalibration::update().
is_filament_at_extruder()
bool Slic3r::MachineObject::is_filament_at_extruder ()
{
    if (hw_switch_state == 1)
        return true;
    else if (hw_switch_state == 0)
        return false;
    else {
       //default
        return true;
    }
}
References hw_switch_state.
Referenced by Slic3r::GUI::StatusPanel::on_ams_load_curr(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::StatusPanel::update_ams(), Slic3r::GUI::StatusPanel::update_ams_control_state(), and Slic3r::GUI::StatusPanel::update_extruder_status().
is_filament_move()
bool Slic3r::MachineObject::is_filament_move () inline
{ return atoi(m_tray_now.c_str()) == 255 ? false : true; };
References m_tray_now.
is_firmware_info_valid()
bool Slic3r::MachineObject::is_firmware_info_valid ()
{
    return m_firmware_valid;
}
References m_firmware_valid.
Referenced by Slic3r::GUI::UpgradePanel::update().
is_function_supported()
bool Slic3r::MachineObject::is_function_supported (PrinterFunction func)
{
    std::string func_name;
    switch (func) {
    case FUNC_MONITORING:
        func_name = "FUNC_MONITORING";
        break;
    case FUNC_TIMELAPSE:
        func_name = "FUNC_TIMELAPSE";
        break;
    case FUNC_RECORDING:
        func_name = "FUNC_RECORDING";
        break;
    case FUNC_FIRSTLAYER_INSPECT:
        func_name = "FUNC_FIRSTLAYER_INSPECT";
        break;
    case FUNC_AI_MONITORING:
        parse_version_func();
        if (!is_support_ai_monitoring)
            return false;
        func_name = "FUNC_AI_MONITORING";
        break;
    case FUNC_BUILDPLATE_MARKER_DETECT:
        parse_version_func();
        if (!is_xcam_buildplate_supported)
            return false;
        func_name = "FUNC_BUILDPLATE_MARKER_DETECT";
        break;
    case FUNC_AUTO_RECOVERY_STEP_LOSS:
        parse_version_func();
        if (!xcam_support_recovery_step_loss)
            return false;
        func_name = "FUNC_AUTO_RECOVERY_STEP_LOSS";
        break;
    case FUNC_FLOW_CALIBRATION:
        func_name = "FUNC_FLOW_CALIBRATION";
        break;
    case FUNC_AUTO_LEVELING:
        func_name = "FUNC_AUTO_LEVELING";
        break;
    case FUNC_CHAMBER_TEMP:
        func_name = "FUNC_CHAMBER_TEMP";
        break;
    case FUNC_CAMERA_VIDEO:
        func_name = "FUNC_CAMERA_VIDEO";
        break;
    case FUNC_MEDIA_FILE:
        func_name = "FUNC_MEDIA_FILE";
        break;
    case FUNC_REMOTE_TUNNEL:
        func_name = "FUNC_REMOTE_TUNNEL";
        break;
    case FUNC_LOCAL_TUNNEL:
        func_name = "FUNC_LOCAL_TUNNEL";
        break;
    case FUNC_PRINT_WITHOUT_SD:
        func_name = "FUNC_PRINT_WITHOUT_SD";
        break;
    case FUNC_USE_AMS:
        func_name = "FUNC_USE_AMS";
        break;
    case FUNC_ALTER_RESOLUTION:
        func_name = "FUNC_ALTER_RESOLUTION";
        break;
    case FUNC_SEND_TO_SDCARD:
        parse_version_func();
        if (!is_support_send_to_sdcard)
            return false;
        func_name = "FUNC_SEND_TO_SDCARD";
        break;
    case FUNC_AUTO_SWITCH_FILAMENT:
        parse_version_func();
        if (!ams_support_auto_switch_filament_flag)
            return false;
        func_name = "FUNC_AUTO_SWITCH_FILAMENT";
        break;
    case FUNC_VIRTUAL_CAMERA:
        func_name = "FUNC_VIRTUAL_CAMERA";
        break;
    case FUNC_CHAMBER_FAN:
        func_name = "FUNC_CHAMBER_FAN";
        break;
    case FUNC_EXTRUSION_CALI:
        if (!ams_support_virtual_tray)
            return false;
        func_name = "FUNC_EXTRUSION_CALI";
        break;
    case FUNC_PRINT_ALL:
        func_name = "FUNC_PRINT_ALL";
        break;
    case FUNC_VIRTUAL_TYAY:
        if (!ams_support_virtual_tray)
            return false;
        func_name = "FUNC_VIRTUAL_TYAY";
        break;
    case FUNC_FILAMENT_BACKUP:
        func_name = "FUNC_FILAMENT_BACKUP";
        break;
    default:
        return true;
    }
    return DeviceManager::is_function_supported(printer_type, func_name);
}
References ams_support_auto_switch_filament_flag, ams_support_virtual_tray, Slic3r::FUNC_AI_MONITORING, Slic3r::FUNC_ALTER_RESOLUTION, Slic3r::FUNC_AUTO_LEVELING, Slic3r::FUNC_AUTO_RECOVERY_STEP_LOSS, Slic3r::FUNC_AUTO_SWITCH_FILAMENT, Slic3r::FUNC_BUILDPLATE_MARKER_DETECT, Slic3r::FUNC_CAMERA_VIDEO, Slic3r::FUNC_CHAMBER_FAN, Slic3r::FUNC_CHAMBER_TEMP, Slic3r::FUNC_EXTRUSION_CALI, Slic3r::FUNC_FILAMENT_BACKUP, Slic3r::FUNC_FIRSTLAYER_INSPECT, Slic3r::FUNC_FLOW_CALIBRATION, Slic3r::FUNC_LOCAL_TUNNEL, Slic3r::FUNC_MEDIA_FILE, Slic3r::FUNC_MONITORING, Slic3r::FUNC_PRINT_ALL, Slic3r::FUNC_PRINT_WITHOUT_SD, Slic3r::FUNC_RECORDING, Slic3r::FUNC_REMOTE_TUNNEL, Slic3r::FUNC_SEND_TO_SDCARD, Slic3r::FUNC_TIMELAPSE, Slic3r::FUNC_USE_AMS, Slic3r::FUNC_VIRTUAL_CAMERA, Slic3r::FUNC_VIRTUAL_TYAY, Slic3r::DeviceManager::is_function_supported(), is_support_ai_monitoring, is_support_send_to_sdcard, is_xcam_buildplate_supported, parse_version_func(), printer_type, and xcam_support_recovery_step_loss.
Referenced by Slic3r::GUI::CameraPopup::check_func_supported(), command_unload_filament(), Slic3r::GUI::StatusPanel::on_nozzle_fan_switch(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::AMSLib::render(), Slic3r::GUI::MediaFilePanel::SetMachineObject(), Slic3r::GUI::MediaPlayCtrl::SetMachineObject(), Slic3r::GUI::AMSMaterialsSetting::Show(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::StatusPanel::update_ams(), Slic3r::GUI::SelectMachineDialog::update_ams_check(), Slic3r::GUI::CalibrationDialog::update_cali(), Slic3r::GUI::StatusPanel::update_camera_state(), Slic3r::GUI::FanControlPopup::update_fan_data(), Slic3r::GUI::StatusPanel::update_misc_ctrl(), Slic3r::GUI::PrintOptionsDialog::update_options(), Slic3r::GUI::SelectMachineDialog::update_select_layout(), Slic3r::GUI::SelectMachineDialog::update_show_status(), Slic3r::GUI::SendToPrinterDialog::update_show_status(), Slic3r::GUI::AMSSetting::update_switch_filament(), and Slic3r::GUI::AMSMaterialsSetting::update_widgets().
is_in_calibration()
bool Slic3r::MachineObject::is_in_calibration ()
{
    // gcode file: auto_cali_for_user.gcode or auto_cali_for_user_param
    if (boost::contains(m_gcode_file, "auto_cali_for_user")
        && stage_curr != 0) {
        return true;
    } else {
        // reset
        if (stage_curr != 0) {
            calibration_done = false;
        }
    }
    return false;
}
References calibration_done, m_gcode_file, and stage_curr.
Referenced by is_calibration_running(), is_system_printing(), and Slic3r::GUI::StatusPanel::update_subtask().
is_in_extrusion_cali()
bool Slic3r::MachineObject::is_in_extrusion_cali ()
{
    auto curr_time = std::chrono::system_clock::now();
    auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(curr_time - last_extrusion_cali_start_time);
    if (diff.count() < EXTRUSION_OMIT_TIME) {
        mc_print_percent = 0;
        return true;
    }
    if (is_in_printing_status(print_status)
        && print_type == "system"
        && boost::contains(m_gcode_file, "extrusion_cali")
        )
    {
        return true;
    }
    return false;
}
References Slic3r::diff(), EXTRUSION_OMIT_TIME, is_in_printing_status(), last_extrusion_cali_start_time, m_gcode_file, mc_print_percent, print_status, and print_type.
Referenced by command_stop_extrusion_cali(), Slic3r::GUI::ExtrusionCalibration::update(), and Slic3r::GUI::StatusPanel::update_ams_control_state().
is_in_prepare()
bool Slic3r::MachineObject::is_in_prepare ()
{
    return print_status == "PREPARE";
}
References print_status.
Referenced by Slic3r::GUI::MediaPlayCtrl::SetMachineObject(), and Slic3r::GUI::StatusPanel::update_subtask().
is_in_printing()
bool Slic3r::MachineObject::is_in_printing ()
{
    /* use print_status if print_status is valid */
    if (!print_status.empty())
        return MachineObject::is_in_printing_status(print_status);
    else {
        return MachineObject::is_in_printing_status(iot_print_status);
    }
    return false;
}
References iot_print_status, is_in_printing_status(), and print_status.
Referenced by Slic3r::GUI::AMSMaterialsSetting::on_clr_picker(), Slic3r::GUI::StatusPanel::on_switch_speed(), Slic3r::GUI::AMSMaterialsSetting::update(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::StatusPanel::update_ams_control_state(), Slic3r::GUI::CalibrationDialog::update_cali(), Slic3r::GUI::StatusPanel::update_cali(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::SelectMachineDialog::update_show_status(), and Slic3r::GUI::StatusPanel::update_subtask().
is_in_printing_status()
bool Slic3r::MachineObject::is_in_printing_status (std::string status) static
{
    if (status.compare("PAUSE") == 0
        || status.compare("RUNNING") == 0
        || status.compare("SLICING") == 0
        || status.compare("PREPARE") == 0) {
        return true;
    }
    return false;
}
Referenced by can_abort(), is_calibration_running(), is_in_extrusion_cali(), is_in_printing(), and is_system_printing().
is_in_upgrading()
bool Slic3r::MachineObject::is_in_upgrading ()
{
    return upgrade_display_state == (int)UpgradingInProgress;
}
References int, upgrade_display_state, and UpgradingInProgress.
Referenced by Slic3r::GUI::MediaPlayCtrl::SetMachineObject(), Slic3r::GUI::SelectMachineDialog::update_show_status(), and Slic3r::GUI::SendToPrinterDialog::update_show_status().
is_info_ready()
bool Slic3r::MachineObject::is_info_ready ()
{
    if (module_vers.empty())
        return false;
    std::chrono::system_clock::time_point curr_time = std::chrono::system_clock::now();
    auto diff = std::chrono::duration_cast<std::chrono::microseconds>(last_push_time - curr_time);
    if (m_push_count > 0 && diff.count() < PUSHINFO_TIMEOUT) {
        return true;
    }
    return false;
}
References Slic3r::diff(), last_push_time, m_push_count, module_vers, and PUSHINFO_TIMEOUT.
Referenced by Slic3r::GUI::SelectMachineDialog::update_show_status(), and Slic3r::GUI::SendToPrinterDialog::update_show_status().
is_lan_mode_printer()
bool Slic3r::MachineObject::is_lan_mode_printer ()
{
    bool result = false;
    if (!dev_connection_type.empty() && dev_connection_type == "lan")
        return true;
    return result;
}
References dev_connection_type.
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks(), is_connected(), Slic3r::GUI::MachineObjectPanel::on_mouse_left_up(), Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SendToPrinterDialog::on_ok(), publish_json(), Slic3r::GUI::MediaFilePanel::SetMachineObject(), Slic3r::GUI::MediaPlayCtrl::SetMachineObject(), Slic3r::GUI::SelectMachineDialog::update_lan_machine_list(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::SelectMachineDialog::update_show_status(), Slic3r::GUI::SendToPrinterDialog::update_show_status(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
is_local()
bool Slic3r::MachineObject::is_local () inline
{ return !dev_ip.empty(); }
References dev_ip.
is_mapping_exceed_filament()
bool Slic3r::MachineObject::is_mapping_exceed_filament (std::vector< FilamentInfo > & result, int & exceed_index)
{
    bool is_exceed = false;
    for (int i = 0; i < result.size(); i++) {
        int ams_id = result[i].tray_id / 4;
        if (amsList.find(std::to_string(ams_id)) == amsList.end()) {
            exceed_index = result[i].tray_id;
            result[i].tray_id = -1;
            is_exceed = true;
            break;
        }
        if (result[i].mapping_result == MappingResult::MAPPING_RESULT_EXCEED) {
            exceed_index = result[i].id;
            is_exceed = true;
            break;
        }
    }
    return is_exceed;
}
References amsList, and Slic3r::MAPPING_RESULT_EXCEED.
Referenced by Slic3r::GUI::SelectMachineDialog::update_show_status().
is_online()
bool Slic3r::MachineObject::is_online () inline
{ return m_is_online; }
References m_is_online.
Referenced by Slic3r::GUI::MachineListModel::add_machine(), Slic3r::GUI::SelectMachineDialog::update_lan_machine_list(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
is_printing_finished()
bool Slic3r::MachineObject::is_printing_finished ()
{
    if (print_status.compare("FINISH") == 0
        || print_status.compare("FAILED") == 0) {
        return true;
    }
    return false;
}
References print_status.
is_recording()
bool Slic3r::MachineObject::is_recording ()
{
    return camera_recording;
}
References camera_recording.
Referenced by Slic3r::GUI::StatusPanel::rescale_camera_icons(), and Slic3r::GUI::StatusPanel::update_camera_state().
is_recording_enable()
bool Slic3r::MachineObject::is_recording_enable ()
{
    return camera_recording_when_printing;
}
References camera_recording_when_printing.
is_sdcard_printing()
bool Slic3r::MachineObject::is_sdcard_printing ()
{
    if (can_abort()
        && (obj_subtask_id.compare("0") == 0 || obj_subtask_id.empty())
        && (profile_id_ == "0" || profile_id_.empty())
        && (project_id_ == "0" || project_id_.empty()))
        return true;
    else
        return false;
}
References can_abort(), obj_subtask_id, profile_id_, and project_id_.
Referenced by Slic3r::GUI::StatusPanel::update_subtask().
is_studio_cmd()
bool Slic3r::MachineObject::is_studio_cmd (int seq)
{
    if (sequence_id >= START_SEQ_ID && sequence_id < END_SEQ_ID) {
        return true;
    }
    return false;
}
References END_SEQ_ID, and START_SEQ_ID.
Referenced by parse_json().
is_support_ams_mapping()
bool Slic3r::MachineObject::is_support_ams_mapping ()
{
    if (printer_type == "BL-P001" || printer_type == "BL-P002") {
        AppConfig* config = Slic3r::GUI::wxGetApp().app_config;
        if (config) {
            if (config->get("check_ams_version") == "0")
                return true;
        }
        bool need_upgrade = false;
        if (has_ams()) {
            // compare ota version and ams version
            auto ota_ver_it = module_vers.find("ota");
            if (ota_ver_it != module_vers.end()) {
                if (!MachineObject::is_support_ams_mapping_version("ota", ota_ver_it->second.sw_ver)) {
                    need_upgrade = true;
                }
            }
            for (int i = 0; i < 4; i++) {
                std::string ams_id = (boost::format("ams/%1%") % i).str();
                auto ams_ver_it = module_vers.find(ams_id);
                if (ams_ver_it != module_vers.end()) {
                    if (!MachineObject::is_support_ams_mapping_version("ams", ams_ver_it->second.sw_ver)) {
                        need_upgrade = true;
                    }
                }
            }
        }
        return !need_upgrade;
    }
    else {
        return true;
    }
}
References Slic3r::AppConfig::get(), has_ams(), is_support_ams_mapping_version(), module_vers, and printer_type.
Referenced by ams_filament_mapping(), Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SelectMachineDialog::set_default(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
is_support_ams_mapping_version()
bool Slic3r::MachineObject::is_support_ams_mapping_version (std::string module, std::string version) static
{
    bool result = true;
    if (module == "ota") {
        if (version.compare("00.01.04.03") < 0)
            return false;
    }
    else if (module == "ams") {
        // omit ams version is empty
        if (version.empty())
            return true;
        if (version.compare("00.00.04.10") < 0)
            return false;
    }
    return result;
}
References module.
Referenced by is_support_ams_mapping().
is_support_command_calibration()
bool Slic3r::MachineObject::is_support_command_calibration ()
{
    if (printer_type == "BL-P001"
        || printer_type == "BL-P002") {
        auto ap_ver_it = module_vers.find("rv1126");
        if (ap_ver_it != module_vers.end()) {
            if (ap_ver_it->second.sw_ver.compare("00.00.15.79") < 0)
                return false;
        }
    }
    return true;
}
References module_vers, and printer_type.
Referenced by command_start_calibration().
is_support_print_with_timelapse()
bool Slic3r::MachineObject::is_support_print_with_timelapse ()
{
    //TODO version check, set true by default
    return true;
}
Referenced by Slic3r::GUI::SelectMachineDialog::update_select_layout().
is_system_printing()
bool Slic3r::MachineObject::is_system_printing ()
{
    if (is_in_calibration() && is_in_printing_status(print_status))
        return true;
    //FIXME
    //if (print_type == "system" && is_in_printing_status(print_status))
        //return true;
    return false;
}
References is_in_calibration(), is_in_printing_status(), and print_status.
Referenced by Slic3r::GUI::SelectMachineDialog::update_show_status(), Slic3r::GUI::SendToPrinterDialog::update_show_status(), and Slic3r::GUI::StatusPanel::update_subtask().
is_timelapse()
bool Slic3r::MachineObject::is_timelapse ()
{
    return camera_timelapse;
}
References camera_timelapse.
Referenced by Slic3r::GUI::StatusPanel::rescale_camera_icons(), and Slic3r::GUI::StatusPanel::update_camera_state().
is_U0_firmware()
bool Slic3r::MachineObject::is_U0_firmware ()
{
    auto ota_ver_it = module_vers.find("ota");
    if (ota_ver_it != module_vers.end()) {
        if (ota_ver_it->second.sw_ver.compare("00.01.04.00") < 0)
            return true;
    }
    return false;
}
References module_vers.
Referenced by Slic3r::GUI::StatusPanel::set_hold_count().
is_upgrading_avalable()
bool Slic3r::MachineObject::is_upgrading_avalable ()
{
    return upgrade_display_state == (int)UpgradingAvaliable;
}
References int, upgrade_display_state, and UpgradingAvaliable.
is_valid_mapping_result()
bool Slic3r::MachineObject::is_valid_mapping_result (std::vector< FilamentInfo > & result, bool check_empty_slot = false)
{
    bool valid_ams_mapping_result = true;
    if (result.empty()) return false;
    for (int i = 0; i < result.size(); i++) {
        // invalid mapping result
        if (result[i].tray_id < 0)
            valid_ams_mapping_result = false;
        else {
            int ams_id = result[i].tray_id / 4;
            auto ams_item = amsList.find(std::to_string(ams_id));
            if (ams_item == amsList.end()) {
                result[i].tray_id = -1;
                valid_ams_mapping_result = false;
            } else {
                if (check_empty_slot) {
                    int  tray_id   = result[i].tray_id % 4;
                    auto tray_item = ams_item->second->trayList.find(std::to_string(tray_id));
                    if (tray_item == ams_item->second->trayList.end()) {
                        result[i].tray_id        = -1;
                        valid_ams_mapping_result = false;
                    } else {
                        if (!tray_item->second->is_exists) {
                            result[i].tray_id        = -1;
                            valid_ams_mapping_result = false;
                        }
                    }
                }
            }
        }
    }
    return valid_ams_mapping_result;
}
References amsList.
Referenced by ams_filament_mapping(), Slic3r::GUI::SelectMachineDialog::do_ams_mapping(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
light_effect_parse()
MachineObject::LIGHT_EFFECT Slic3r::MachineObject::light_effect_parse (std::string effect_str)
{
    if (effect_str.compare("on") == 0)
        return LIGHT_EFFECT::LIGHT_EFFECT_ON;
    else if (effect_str.compare("off") == 0)
        return LIGHT_EFFECT::LIGHT_EFFECT_OFF;
    else if (effect_str.compare("flashing") == 0)
        return LIGHT_EFFECT::LIGHT_EFFECT_FLASHING;
    else
        return LIGHT_EFFECT::LIGHT_EFFECT_UNKOWN;
    return LIGHT_EFFECT::LIGHT_EFFECT_UNKOWN;
}
References LIGHT_EFFECT_FLASHING, LIGHT_EFFECT_OFF, LIGHT_EFFECT_ON, and LIGHT_EFFECT_UNKOWN.
Referenced by parse_json().
light_effect_str()
std::string Slic3r::MachineObject::light_effect_str (LIGHT_EFFECT effect)
{
    switch (effect)
    {
    case LIGHT_EFFECT::LIGHT_EFFECT_ON:
        return "on";
    case LIGHT_EFFECT::LIGHT_EFFECT_OFF:
        return "off";
    case LIGHT_EFFECT::LIGHT_EFFECT_FLASHING:
        return "flashing";
    default:
        return "unknown";
    }
    return "unknown";
}
References LIGHT_EFFECT_FLASHING, LIGHT_EFFECT_OFF, and LIGHT_EFFECT_ON.
Referenced by command_set_chamber_light(), and command_set_work_light().
local_publish_json()
int Slic3r::MachineObject::local_publish_json (std::string json_str, int qos = 0)
{
    int result = -1;
    if (m_agent) {
        result = m_agent->send_message_to_printer(dev_id, json_str, qos);
    }
    return result;
}
References dev_id, m_agent, and Slic3r::NetworkAgent::send_message_to_printer().
Referenced by publish_json().
parse_json()
int Slic3r::MachineObject::parse_json (std::string payload)
{
    parse_msg_count++;
    std::chrono::system_clock::time_point clock_start = std::chrono::system_clock::now();
    this->set_online_state(true);
    /* update last received time */
    last_update_time = std::chrono::system_clock::now();
    try {
        bool restored_json = false;
        json j;
        json j_pre = json::parse(payload);
        if (j_pre.empty()) {
            return 0;
        }
        if (j_pre.contains("print")) {
            if (j_pre["print"].contains("command")) {
                if (j_pre["print"]["command"].get<std::string>() == "push_status") {
                    if (j_pre["print"].contains("msg")) {
                        if (j_pre["print"]["msg"].get<int>() == 0) {           //all message
                            BOOST_LOG_TRIVIAL(trace) << "static: get push_all msg, dev_id=" << dev_id;
                            m_push_count++;
                            print_json.diff2all_base_reset(j_pre);
                        } else if (j_pre["print"]["msg"].get<int>() == 1) {    //diff message
                            if (print_json.diff2all(j_pre, j) == 0) {
                                restored_json = true;
                            } else {
                                BOOST_LOG_TRIVIAL(trace) << "parse_json: restore failed! count = " << parse_msg_count;
                                if (print_json.is_need_request()) {
                                    BOOST_LOG_TRIVIAL(trace) << "parse_json: need request pushall, count = " << parse_msg_count;
                                    // request new push
                                    GUI::wxGetApp().CallAfter([this]{
                                        this->command_request_push_all();
                                    });
                                    return -1;
                                }
                                return -1;
                            }
                        } else {
                            BOOST_LOG_TRIVIAL(warning) << "unsupported msg_type=" << j_pre["print"]["msg"].get<std::string>();
                        }
                    }
                }
            }
        }
        if (!restored_json) {
            j = json::parse(payload);
        }
        BOOST_LOG_TRIVIAL(trace) << "parse_json: dev_id=" << dev_id << ", playload=" << j.dump(4);
        if (j.contains("print")) {
            json jj = j["print"];
            int sequence_id = 0;
            if (jj.contains("sequence_id")) {
                if (jj["sequence_id"].is_string()) {
                    std::string str_seq = jj["sequence_id"].get<std::string>();
                    try {
                        sequence_id = stoi(str_seq);
                    }
                    catch(...) {
                        ;
                    }
                }
            }
            if (jj.contains("command")) {
                if (jj["command"].get<std::string>() == "push_status") {
                    m_push_count++;
                    last_push_time = std::chrono::system_clock::now();
#pragma region printing
                    // U0 firmware
                    if (jj.contains("print_type")) {
                        print_type = jj["print_type"].get<std::string>();
                    }
                    if (jj.contains("home_flag")) {
                        home_flag = jj["home_flag"].get<int>();
                        parse_status(home_flag);
                    }
                    if (jj.contains("hw_switch_state")) {
                        hw_switch_state = jj["hw_switch_state"].get<int>();
                    }
                    if (jj.contains("mc_remaining_time")) {
                        if (jj["mc_remaining_time"].is_string())
                            mc_left_time = stoi(j["print"]["mc_remaining_time"].get<std::string>()) * 60;
                        else if (jj["mc_remaining_time"].is_number_integer())
                            mc_left_time = j["print"]["mc_remaining_time"].get<int>() * 60;
                    }
                    if (jj.contains("mc_percent")) {
                        if (jj["mc_percent"].is_string())
                            mc_print_percent = stoi(j["print"]["mc_percent"].get<std::string>());
                        else if (jj["mc_percent"].is_number_integer())
                            mc_print_percent = j["print"]["mc_percent"].get<int>();
                    }
                    if (jj.contains("mc_print_sub_stage")) {
                        if (jj["mc_print_sub_stage"].is_number_integer())
                            mc_print_sub_stage = j["print"]["mc_print_sub_stage"].get<int>();
                    }
                    /* printing */
                    if (jj.contains("mc_print_stage")) {
                        if (jj["mc_print_stage"].is_string())
                            mc_print_stage = atoi(jj["mc_print_stage"].get<std::string>().c_str());
                        if (jj["mc_print_stage"].is_number())
                            mc_print_stage = jj["mc_print_stage"].get<int>();
                    }
                    if (jj.contains("mc_print_error_code")) {
                        if (jj["mc_print_error_code"].is_number())
                            mc_print_error_code = jj["mc_print_error_code"].get<int>();
                    }
                    if (jj.contains("mc_print_line_number")) {
                        if (jj["mc_print_line_number"].is_string() && !jj["mc_print_line_number"].is_null())
                            mc_print_line_number = atoi(jj["mc_print_line_number"].get<std::string>().c_str());
                    }
                    if (jj.contains("print_error")) {
                        if (jj["print_error"].is_number())
                            print_error = jj["print_error"].get<int>();
                    }
#pragma endregion
#pragma region online
                    // parse online info
                    try {
                        if (jj.contains("online")) {
                            if (jj["online"].contains("ahb")) {
                                if (jj["online"]["ahb"].get<bool>()) {
                                    online_ahb = true;
                                } else {
                                    online_ahb = false;
                                }
                            }
                            if (jj["online"].contains("rfid")) {
                                if (jj["online"]["rfid"].get<bool>()) {
                                    online_rfid = true;
                                } else {
                                    online_rfid = false;
                                }
                            }
                            if (jj["online"].contains("version")) {
                                online_version = jj["online"]["version"].get<int>();
                            }
                            if (last_online_version != online_version) {
                                last_online_version = online_version;
                                GUI::wxGetApp().CallAfter([this] {
                                    this->command_get_version();
                                    });
                            }
                        }
                    } catch (...) {
                        ;
                    }
#pragma endregion
#pragma region print_task
                    if (jj.contains("printer_type")) {
                        printer_type = parse_printer_type(jj["printer_type"].get<std::string>());
                    }
                    if (jj.contains("subtask_name")) {
                        subtask_name = jj["subtask_name"].get<std::string>();
                    }
                    if (jj.contains("layer_num")) {
                        curr_layer = jj["layer_num"].get<int>();
                    }
                    if (jj.contains("total_layer_num")) {
                        total_layers = jj["total_layer_num"].get<int>();
                        if (total_layers == 0)
                            is_support_layer_num = false;
                        else
                            is_support_layer_num = true;
                    } else {
                        is_support_layer_num = false;
                    }
                    if (jj.contains("gcode_state")) {
                        this->set_print_state(jj["gcode_state"].get<std::string>());
                    }
                    if (jj.contains("queue_number")) {
                        this->queue_number = jj["queue_number"].get<int>();
                    } else {
                        this->queue_number = 0;
                    }
                    if (jj.contains("task_id")) {
                        this->task_id_ = jj["task_id"].get<std::string>();
                    }
                    if (jj.contains("gcode_file"))
                        this->m_gcode_file = jj["gcode_file"].get<std::string>();
                    if (jj.contains("gcode_file_prepare_percent")) {
                        std::string percent_str = jj["gcode_file_prepare_percent"].get<std::string>();
                        if (!percent_str.empty()) {
                            try{
                                this->gcode_file_prepare_percent = atoi(percent_str.c_str());
                            } catch(...) {}
                        }
                    }
                    if (jj.contains("project_id")
                        && jj.contains("profile_id")
                        && jj.contains("subtask_id")
                        ){
                        obj_subtask_id = jj["subtask_id"].get<std::string>();
                        int plate_index = -1;
                        /* parse local plate_index from task */
                        if (obj_subtask_id.compare("0") == 0 && jj["profile_id"].get<std::string>() != "0") {
                            if (jj.contains("gcode_file")) {
                                m_gcode_file = jj["gcode_file"].get<std::string>();
                                int idx_start = m_gcode_file.find_last_of("_") + 1;
                                int idx_end = m_gcode_file.find_last_of(".");
                                if (idx_start > 0 && idx_end > idx_start) {
                                    try {
                                        plate_index = atoi(m_gcode_file.substr(idx_start, idx_end - idx_start).c_str());
                                    }
                                    catch (...) {
                                        ;
                                    }
                                }
                            }
                        }
                        update_slice_info(jj["project_id"].get<std::string>(), jj["profile_id"].get<std::string>(), jj["subtask_id"].get<std::string>(), plate_index);
                        BBLSubTask* curr_task = get_subtask();
                        if (curr_task) {
                            curr_task->task_progress = mc_print_percent;
                            curr_task->printing_status = print_status;
                            curr_task->task_id = jj["subtask_id"].get<std::string>();
                        }
                    }
#pragma endregion
#pragma region status
                    /* temperature */
                    if (jj.contains("bed_temper")) {
                        if (jj["bed_temper"].is_number()) {
                            bed_temp = jj["bed_temper"].get<float>();
                        }
                    }
                    if (jj.contains("bed_target_temper")) {
                        if (jj["bed_target_temper"].is_number()) {
                            bed_temp_target = jj["bed_target_temper"].get<float>();
                        }
                    }
                    if (jj.contains("frame_temper")) {
                        if (jj["frame_temper"].is_number()) {
                            frame_temp = jj["frame_temper"].get<float>();
                        }
                    }
                    if (jj.contains("nozzle_temper")) {
                        if (jj["nozzle_temper"].is_number()) {
                            nozzle_temp = jj["nozzle_temper"].get<float>();
                        }
                    }
                    if (jj.contains("nozzle_target_temper")) {
                        if (jj["nozzle_target_temper"].is_number()) {
                            nozzle_temp_target = jj["nozzle_target_temper"].get<float>();
                        }
                    }
                    if (jj.contains("chamber_temper")) {
                        if (jj["chamber_temper"].is_number()) {
                            chamber_temp = jj["chamber_temper"].get<float>();
                        }
                    }
                    /* signals */
                    if (jj.contains("link_th_state"))
                        link_th = jj["link_th_state"].get<std::string>();
                    if (jj.contains("link_ams_state"))
                        link_ams = jj["link_ams_state"].get<std::string>();
                    if (jj.contains("wifi_signal"))
                        wifi_signal = jj["wifi_signal"].get<std::string>();
                    /* cooling */
                    if (jj.contains("fan_gear")) {
                        fan_gear = jj["fan_gear"].get<std::uint32_t>();
                        big_fan2_speed = (int)((fan_gear & 0x00FF0000) >> 16);
                        big_fan1_speed = (int)((fan_gear & 0x0000FF00) >> 8);
                        cooling_fan_speed= (int)((fan_gear & 0x000000FF) >> 0);
                    }
                    else {
                        if (jj.contains("cooling_fan_speed")) {
                            cooling_fan_speed = stoi(jj["cooling_fan_speed"].get<std::string>());
                            cooling_fan_speed = round( floor(cooling_fan_speed / float(1.5)) * float(25.5) );
                        }
                        else {
                            cooling_fan_speed = 0;
                        }
                        if (jj.contains("big_fan1_speed")) {
                            big_fan1_speed = stoi(jj["big_fan1_speed"].get<std::string>());
                            big_fan1_speed = round( floor(big_fan1_speed / float(1.5)) * float(25.5) );
                        }
                        else {
                            big_fan1_speed = 0;
                        }
                        if (jj.contains("big_fan2_speed")) {
                            big_fan2_speed = stoi(jj["big_fan2_speed"].get<std::string>());
                            big_fan2_speed = round( floor(big_fan2_speed / float(1.5)) * float(25.5) );
                        }
                        else {
                            big_fan2_speed = 0;
                        }
                    }
                    if (jj.contains("heatbreak_fan_speed")) {
                        heatbreak_fan_speed = stoi(jj["heatbreak_fan_speed"].get<std::string>());
                    }
                    /* parse speed */
                    try {
                        if (jj.contains("spd_lvl")) {
                            printing_speed_lvl = (PrintingSpeedLevel)jj["spd_lvl"].get<int>();
                        }
                        if (jj.contains("spd_mag")) {
                            printing_speed_mag = jj["spd_mag"].get<int>();
                        }
                    }
                    catch (...) {
                        ;
                    }
                    try {
                        if (jj.contains("stg")) {
                            stage_list_info.clear();
                            if (jj["stg"].is_array()) {
                                for (auto it = jj["stg"].begin(); it != jj["stg"].end(); it++) {
                                    for (auto kv = (*it).begin(); kv != (*it).end(); kv++) {
                                        stage_list_info.push_back(kv.value().get<int>());
                                    }
                                }
                            }
                        }
                        if (jj.contains("stg_cur")) {
                            stage_curr = jj["stg_cur"].get<int>();
                        }
                    }
                    catch (...) {
                        ;
                    }
                    /*get filam_bak*/
                    try {
                        if (jj.contains("filam_bak")) {
                            filam_bak.clear();
                            if (jj["filam_bak"].is_array()) {
                                for (auto it = jj["filam_bak"].begin(); it != jj["filam_bak"].end(); it++) {
                                    filam_bak.push_back(it.value().get<int>());
                                }
                            }
                        }
                    }
                    catch (...) {
                        ;
                    }
                    /* get fimware type */
                    try {
                        if (jj.contains("lifecycle")) {
                            if (jj["lifecycle"].get<std::string>() == "engineer")
                                firmware_type = PrinterFirmwareType::FIRMWARE_TYPE_ENGINEER;
                            else if (jj["lifecycle"].get<std::string>() == "product")
                                firmware_type = PrinterFirmwareType::FIRMWARE_TYPE_PRODUCTION;
                        }
                    }
                    catch (...) {
                        ;
                    }
                    try {
                        if (jj.contains("lights_report") && jj["lights_report"].is_array()) {
                            for (auto it = jj["lights_report"].begin(); it != jj["lights_report"].end(); it++) {
                                if ((*it)["node"].get<std::string>().compare("chamber_light") == 0)
                                    chamber_light = light_effect_parse((*it)["mode"].get<std::string>());
                                if ((*it)["node"].get<std::string>().compare("work_light") == 0)
                                    work_light = light_effect_parse((*it)["mode"].get<std::string>());
                            }
                        }
                    }
                    catch (...) {
                        ;
                    }
                    // media
                    try {
                        if (jj.contains("sdcard")) {
                            if (jj["sdcard"].get<bool>())
                                sdcard_state = MachineObject::SdcardState::HAS_SDCARD_NORMAL;
                            else
                                sdcard_state = MachineObject::SdcardState::NO_SDCARD;
                        } else {
                            //do not check sdcard if no sdcard field
                            sdcard_state = MachineObject::SdcardState::NO_SDCARD;
                        }
                    }
                    catch (...) {
                        ;
                    }
#pragma endregion
                    try {
                        if (jj.contains("nozzle_diameter")) {
                            if (jj["nozzle_diameter"].is_number_float()) {
                                nozzle_diameter = jj["nozzle_diameter"].get<float>();
                            } else if (jj["nozzle_diameter"].is_string()) {
                                nozzle_diameter = stof(jj["nozzle_diameter"].get<std::string>().c_str());
                            }
                        }
                    }
                    catch(...) {
                        ;
                    }
#pragma region upgrade
                    try {
                        if (jj.contains("upgrade_state")) {
                            if (jj["upgrade_state"].contains("status"))
                                upgrade_status = jj["upgrade_state"]["status"].get<std::string>();
                            if (jj["upgrade_state"].contains("progress")) {
                                upgrade_progress = jj["upgrade_state"]["progress"].get<std::string>();
                            } if (jj["upgrade_state"].contains("new_version_state"))
                                upgrade_new_version = jj["upgrade_state"]["new_version_state"].get<int>() == 1 ? true : false;
                            if (jj["upgrade_state"].contains("ams_new_version_number"))
                                ams_new_version_number = jj["upgrade_state"]["ams_new_version_number"].get<std::string>();
                            if (jj["upgrade_state"].contains("ota_new_version_number"))
                                ota_new_version_number = jj["upgrade_state"]["ota_new_version_number"].get<std::string>();
                            if (jj["upgrade_state"].contains("ahb_new_version_number"))
                                ahb_new_version_number = jj["upgrade_state"]["ahb_new_version_number"].get<std::string>();
                            if (jj["upgrade_state"].contains("module"))
                                upgrade_module = jj["upgrade_state"]["module"].get<std::string>();
                            if (jj["upgrade_state"].contains("message"))
                                upgrade_message = jj["upgrade_state"]["message"].get<std::string>();
                            if (jj["upgrade_state"].contains("consistency_request"))
                                upgrade_consistency_request = jj["upgrade_state"]["consistency_request"].get<bool>();
                            if (jj["upgrade_state"].contains("force_upgrade"))
                                upgrade_force_upgrade = jj["upgrade_state"]["force_upgrade"].get<bool>();
                            if (jj["upgrade_state"].contains("err_code"))
                                upgrade_err_code = jj["upgrade_state"]["err_code"].get<int>();
                            if (jj["upgrade_state"].contains("dis_state")) {
                                if (upgrade_display_state != jj["upgrade_state"]["dis_state"].get<int>()
                                    && jj["upgrade_state"]["dis_state"].get<int>() == 3) {
                                    GUI::wxGetApp().CallAfter([this] {
                                        this->command_get_version();
                                    });
                                }
                                if (upgrade_display_hold_count > 0)
                                    upgrade_display_hold_count--;
                                else
                                    upgrade_display_state = jj["upgrade_state"]["dis_state"].get<int>();
                            } else {
                                if (upgrade_display_hold_count > 0)
                                    upgrade_display_hold_count--;
                                else {
                                    //BBS compatibility with old version
                                    if (upgrade_status == "DOWNLOADING"
                                        || upgrade_status == "FLASHING"
                                        || upgrade_status == "UPGRADE_REQUEST"
                                        || upgrade_status == "PRE_FLASH_START"
                                        || upgrade_status == "PRE_FLASH_SUCCESS") {
                                        upgrade_display_state = (int)UpgradingDisplayState::UpgradingInProgress;
                                    }
                                    else if (upgrade_status == "UPGRADE_SUCCESS"
                                        || upgrade_status == "DOWNLOAD_FAIL"
                                        || upgrade_status == "FLASH_FAIL"
                                        || upgrade_status == "PRE_FLASH_FAIL"
                                        || upgrade_status == "UPGRADE_FAIL") {
                                        upgrade_display_state = (int)UpgradingDisplayState::UpgradingFinished;
                                    }
                                    else {
                                        if (upgrade_new_version) {
                                            upgrade_display_state = (int)UpgradingDisplayState::UpgradingAvaliable;
                                        }
                                        else {
                                            upgrade_display_state = (int)UpgradingDisplayState::UpgradingUnavaliable;
                                        }
                                    }
                                }
                            }
                            // new ver list
                            if (jj["upgrade_state"].contains("new_ver_list")) {
                                m_new_ver_list_exist = true;
                                new_ver_list.clear();
                                for (auto ver_item = jj["upgrade_state"]["new_ver_list"].begin(); ver_item != jj["upgrade_state"]["new_ver_list"].end(); ver_item++) {
                                    ModuleVersionInfo ver_info;
                                    if (ver_item->contains("name"))
                                        ver_info.name = (*ver_item)["name"].get<std::string>();
                                    else
                                        continue;
                                    if (ver_item->contains("cur_ver"))
                                        ver_info.sw_ver = (*ver_item)["cur_ver"].get<std::string>();
                                    if (ver_item->contains("new_ver"))
                                        ver_info.sw_new_ver = (*ver_item)["new_ver"].get<std::string>();
                                    if (ver_info.name == "ota") {
                                        ota_new_version_number = ver_info.sw_new_ver;
                                    }
                                    new_ver_list.insert(std::make_pair(ver_info.name, ver_info));
                                }
                            } else {
                                new_ver_list.clear();
                            }
                        }
                    }
                    catch (...) {
                        ;
                    }
#pragma endregion
#pragma region  camera
                    // parse camera info
                    try {
                        if (jj.contains("ipcam")) {
                            if (jj["ipcam"].contains("ipcam_record")) {
                                if (camera_recording_hold_count > 0)
                                    camera_recording_hold_count--;
                                else {
                                    if (jj["ipcam"]["ipcam_record"].get<std::string>() == "enable") {
                                        camera_recording_when_printing = true;
                                    }
                                    else {
                                        camera_recording_when_printing = false;
                                    }
                                }
                            }
                            if (jj["ipcam"].contains("timelapse")) {
                                if (camera_timelapse_hold_count > 0)
                                    camera_timelapse_hold_count--;
                                else {
                                    if (jj["ipcam"]["timelapse"].get<std::string>() == "enable") {
                                        camera_timelapse = true;
                                    }
                                    else {
                                        camera_timelapse = false;
                                    }
                                }
                            }
                            if (jj["ipcam"].contains("ipcam_dev")) {
                                if (jj["ipcam"]["ipcam_dev"].get<std::string>() == "1") {
                                    has_ipcam = true;
                                } else {
                                    has_ipcam = false;
                                }
                            }
                            if (jj["ipcam"].contains("resolution")) {
                                if (camera_resolution_hold_count > 0)
                                    camera_resolution_hold_count--;
                                else {
                                    camera_resolution = jj["ipcam"]["resolution"].get<std::string>();
                                }
                            }
                        }
                    }
                    catch (...) {
                        ;
                    }
                    try {
                        if (jj.contains("xcam")) {
                            if (xcam_ai_monitoring_hold_count > 0)
                                xcam_ai_monitoring_hold_count--;
                            else {
                                if (jj["xcam"].contains("printing_monitor")) {
                                    // new protocol
                                    xcam_ai_monitoring = jj["xcam"]["printing_monitor"].get<bool>();
                                } else {
                                    // old version protocol
                                    if (jj["xcam"].contains("spaghetti_detector")) {
                                        xcam_ai_monitoring = jj["xcam"]["spaghetti_detector"].get<bool>();
                                        if (jj["xcam"].contains("print_halt")) {
                                            bool print_halt = jj["xcam"]["print_halt"].get<bool>();
                                            if (print_halt) { xcam_ai_monitoring_sensitivity = "medium"; }
                                        }
                                    }
                                }
                                if (jj["xcam"].contains("halt_print_sensitivity")) {
                                    xcam_ai_monitoring_sensitivity = jj["xcam"]["halt_print_sensitivity"].get<std::string>();
                                }
                            }
                            if (xcam_first_layer_hold_count > 0)
                                xcam_first_layer_hold_count--;
                            else {
                                if (jj["xcam"].contains("first_layer_inspector")) {
                                    xcam_first_layer_inspector = jj["xcam"]["first_layer_inspector"].get<bool>();
                                }
                            }
                            if (xcam_buildplate_marker_hold_count > 0)
                                xcam_buildplate_marker_hold_count--;
                            else {
                                if (jj["xcam"].contains("buildplate_marker_detector")) {
                                    xcam_buildplate_marker_detector = jj["xcam"]["buildplate_marker_detector"].get<bool>();
                                    is_xcam_buildplate_supported = true;
                                } else {
                                    is_xcam_buildplate_supported = false;
                                }
                            }
                        }
                    }
                    catch (...) {
                        ;
                    }
#pragma endregion
#pragma region hms
                    // parse hms msg
                    try {
                        hms_list.clear();
                        if (jj.contains("hms")) {
                            if (jj["hms"].is_array()) {
                                for (auto it = jj["hms"].begin(); it != jj["hms"].end(); it++) {
                                    HMSItem item;
                                    if ((*it).contains("attr") && (*it).contains("code")) {
                                        unsigned attr = (*it)["attr"].get<unsigned>();
                                        unsigned code = (*it)["code"].get<unsigned>();
                                        item.parse_hms_info(attr, code);
                                    }
                                    hms_list.push_back(item);
                                }
                            }
                        }
                    }
                    catch (...) {
                        ;
                    }
#pragma endregion
#pragma region push_ams
                    /* ams status */
                    try {
                        if (jj.contains("ams_status")) {
                            int ams_status = jj["ams_status"].get<int>();
                            this->_parse_ams_status(ams_status);
                        }
                    }
                    catch (...) {
                        ;
                    }
                    if (jj.contains("ams")) {
                        if (jj["ams"].contains("ams")) {
                            long int last_ams_exist_bits = ams_exist_bits;
                            long int last_tray_exist_bits = tray_exist_bits;
                            long int last_is_bbl_bits = tray_is_bbl_bits;
                            long int last_read_done_bits = tray_read_done_bits;
                            long int last_ams_version = ams_version;
                            if (jj["ams"].contains("ams_exist_bits")) {
                                ams_exist_bits = stol(jj["ams"]["ams_exist_bits"].get<std::string>(), nullptr, 16);
                            }
                            if (jj["ams"].contains("tray_exist_bits")) {
                                tray_exist_bits = stol(jj["ams"]["tray_exist_bits"].get<std::string>(), nullptr, 16);
                            }
                            if (jj["ams"].contains("tray_read_done_bits")) {
                                tray_read_done_bits = stol(jj["ams"]["tray_read_done_bits"].get<std::string>(), nullptr, 16);
                            }
                            if (jj["ams"].contains("tray_reading_bits")) {
                                tray_reading_bits = stol(jj["ams"]["tray_reading_bits"].get<std::string>(), nullptr, 16);
                                ams_support_use_ams = true;
                            }
                            if (jj["ams"].contains("tray_is_bbl_bits")) {
                                tray_is_bbl_bits = stol(jj["ams"]["tray_is_bbl_bits"].get<std::string>(), nullptr, 16);
                            }
                            if (jj["ams"].contains("version")) {
                                if (jj["ams"]["version"].is_number())
                                    ams_version = jj["ams"]["version"].get<int>();
                            }
                            if (jj["ams"].contains("tray_now")) {
                                this->_parse_tray_now(jj["ams"]["tray_now"].get<std::string>());
                            }
                            if (jj["ams"].contains("tray_tar")) {
                                m_tray_tar = jj["ams"]["tray_tar"].get<std::string>();
                            }
                            if (jj["ams"].contains("ams_rfid_status"))
                                ams_rfid_status = jj["ams"]["ams_rfid_status"].get<int>();
                            if (jj["ams"].contains("humidity")) {
                                if (jj["ams"]["humidity"].is_string()) {
                                    std::string humidity_str = jj["ams"]["humidity"].get<std::string>();
                                    try {
                                        ams_humidity = atoi(humidity_str.c_str());
                                    } catch (...) {
                                        ;
                                    }
                                }
                            }
                            if (jj["ams"].contains("insert_flag") || jj["ams"].contains("power_on_flag")
                                || jj["ams"].contains("calibrate_remain_flag")) {
                                if (ams_user_setting_hold_count > 0) {
                                    ams_user_setting_hold_count--;
                                } else {
                                    if (jj["ams"].contains("insert_flag")) {
                                        ams_insert_flag = jj["ams"]["insert_flag"].get<bool>();
                                    }
                                    if (jj["ams"].contains("power_on_flag")) {
                                        ams_power_on_flag = jj["ams"]["power_on_flag"].get<bool>();
                                    }
                                    if (jj["ams"].contains("calibrate_remain_flag")) {
                                        ams_calibrate_remain_flag = jj["ams"]["calibrate_remain_flag"].get<bool>();
                                    }
                                }
                            }
                            if (ams_exist_bits != last_ams_exist_bits
                                || last_tray_exist_bits != last_tray_exist_bits
                                || tray_is_bbl_bits != last_is_bbl_bits
                                || tray_read_done_bits != last_read_done_bits
                                || last_ams_version != ams_version) {
                                is_ams_need_update = true;
                            }
                            else {
                                is_ams_need_update = false;
                            }
                            json j_ams = jj["ams"]["ams"];
                            std::set<std::string> ams_id_set;
                            for (auto it = amsList.begin(); it != amsList.end(); it++) {
                                ams_id_set.insert(it->first);
                            }
                            for (auto it = j_ams.begin(); it != j_ams.end(); it++) {
                                if (!it->contains("id")) continue;
                                std::string ams_id = (*it)["id"].get<std::string>();
                                ams_id_set.erase(ams_id);
                                Ams* curr_ams = nullptr;
                                auto ams_it = amsList.find(ams_id);
                                if (ams_it == amsList.end()) {
                                    Ams* new_ams = new Ams(ams_id);
                                    try {
                                        if (!ams_id.empty()) {
                                            int ams_id_int = atoi(ams_id.c_str());
                                            new_ams->is_exists = (ams_exist_bits & (1 << ams_id_int)) != 0 ? true : false;
                                        }
                                    }
                                    catch (...) {
                                        ;
                                    }
                                    amsList.insert(std::make_pair(ams_id, new_ams));
                                    // new ams added event
                                    curr_ams = new_ams;
                                } else {
                                    curr_ams = ams_it->second;
                                }
                                if (!curr_ams) continue;
                                if (it->contains("humidity")) {
                                    std::string humidity = (*it)["humidity"].get<std::string>();
                                    try {
                                        curr_ams->humidity = atoi(humidity.c_str());
                                    }
                                    catch (...) {
                                        ;
                                    }
                                }
                                if (it->contains("tray")) {
                                    std::set<std::string> tray_id_set;
                                    for (auto it = curr_ams->trayList.begin(); it != curr_ams->trayList.end(); it++) {
                                        tray_id_set.insert(it->first);
                                    }
                                    for (auto tray_it = (*it)["tray"].begin(); tray_it != (*it)["tray"].end(); tray_it++) {
                                        if (!tray_it->contains("id")) continue;
                                        std::string tray_id = (*tray_it)["id"].get<std::string>();
                                        tray_id_set.erase(tray_id);
                                        // compare tray_list
                                        AmsTray* curr_tray = nullptr;
                                        auto tray_iter = curr_ams->trayList.find(tray_id);
                                        if (tray_iter == curr_ams->trayList.end()) {
                                            AmsTray* new_tray = new AmsTray(tray_id);
                                            curr_ams->trayList.insert(std::make_pair(tray_id, new_tray));
                                            curr_tray = new_tray;
                                        }
                                        else {
                                            curr_tray = tray_iter->second;
                                        }
                                        if (!curr_tray) continue;
                                        if (curr_tray->hold_count > 0) {
                                            curr_tray->hold_count--;
                                            continue;
                                        }
                                        curr_tray->id = (*tray_it)["id"].get<std::string>();
                                        if (tray_it->contains("tag_uid"))
                                            curr_tray->tag_uid          = (*tray_it)["tag_uid"].get<std::string>();
                                        else
                                            curr_tray->tag_uid = "0";
                                        if (tray_it->contains("tray_info_idx") && tray_it->contains("tray_type")) {
                                            curr_tray->setting_id       = (*tray_it)["tray_info_idx"].get<std::string>();
                                            std::string type            = (*tray_it)["tray_type"].get<std::string>();
                                            if (curr_tray->setting_id == "GFS00") {
                                                curr_tray->type = "PLA-S";
                                            }
                                            else if (curr_tray->setting_id == "GFS01") {
                                                curr_tray->type = "PA-S";
                                            } else {
                                                curr_tray->type = type;
                                            }
                                        } else {
                                            curr_tray->setting_id = "";
                                            curr_tray->type       = "";
                                        }
                                        if (tray_it->contains("tray_sub_brands"))
                                            curr_tray->sub_brands       = (*tray_it)["tray_sub_brands"].get<std::string>();
                                        else
                                            curr_tray->sub_brands = "";
                                        if (tray_it->contains("tray_weight"))
                                            curr_tray->weight           = (*tray_it)["tray_weight"].get<std::string>();
                                        else
                                            curr_tray->weight = "";
                                        if (tray_it->contains("tray_diameter"))
                                            curr_tray->diameter         = (*tray_it)["tray_diameter"].get<std::string>();
                                        else
                                            curr_tray->diameter = "";
                                        if (tray_it->contains("tray_temp"))
                                            curr_tray->temp             = (*tray_it)["tray_temp"].get<std::string>();
                                        else
                                            curr_tray->temp = "";
                                        if (tray_it->contains("tray_time"))
                                            curr_tray->time             = (*tray_it)["tray_time"].get<std::string>();
                                        else
                                            curr_tray->time = "";
                                        if (tray_it->contains("bed_temp_type"))
                                            curr_tray->bed_temp_type    = (*tray_it)["bed_temp_type"].get<std::string>();
                                        else
                                            curr_tray->bed_temp_type = "";
                                        if (tray_it->contains("bed_temp"))
                                            curr_tray->bed_temp         = (*tray_it)["bed_temp"].get<std::string>();
                                        else
                                            curr_tray->bed_temp = "";
                                        if (tray_it->contains("nozzle_temp_max"))
                                            curr_tray->nozzle_temp_max = (*tray_it)["nozzle_temp_max"].get<std::string>();
                                        else
                                            curr_tray->nozzle_temp_max = "";
                                        if (tray_it->contains("nozzle_temp_min"))
                                            curr_tray->nozzle_temp_min = (*tray_it)["nozzle_temp_min"].get<std::string>();
                                        else
                                            curr_tray->nozzle_temp_min = "";
                                        if (tray_it->contains("xcam_info"))
                                            curr_tray->xcam_info = (*tray_it)["xcam_info"].get<std::string>();
                                        else
                                            curr_tray->xcam_info = "";
                                        if (tray_it->contains("tray_uuid"))
                                            curr_tray->uuid = (*tray_it)["tray_uuid"].get<std::string>();
                                        else
                                            curr_tray->uuid = "0";
                                        if (tray_it->contains("tray_color")) {
                                            auto color = (*tray_it)["tray_color"].get<std::string>();
                                            curr_tray->update_color_from_str(color);
                                        } else {
                                            curr_tray->color = "";
                                        }
                                        curr_tray->cols.clear();
                                        if (tray_it->contains("cols")) {
                                            if ((*tray_it)["cols"].is_array()) {
                                                for (auto it = (*tray_it)["cols"].begin(); it != (*tray_it)["cols"].end(); it++) {
                                                   curr_tray->cols.push_back(it.value().get<std::string>());
                                                }
                                            }
                                        }
                                        if (tray_it->contains("remain")) {
                                            curr_tray->remain = (*tray_it)["remain"].get<int>();
                                        } else {
                                            curr_tray->remain = -1;
                                        }
                                        int ams_id_int = 0;
                                        int tray_id_int = 0;
                                        try {
                                            if (!ams_id.empty() && !curr_tray->id.empty()) {
                                                ams_id_int = atoi(ams_id.c_str());
                                                tray_id_int = atoi(curr_tray->id.c_str());
                                                curr_tray->is_exists = (tray_exist_bits & (1 << (ams_id_int * 4 + tray_id_int))) != 0 ? true : false;
                                            }
                                        }
                                        catch (...) {
                                        }
                                        if (tray_it->contains("setting_id")) {
                                            curr_tray->filament_setting_id = (*tray_it)["setting_id"].get<std::string>();
                                        }
                                        auto curr_time = std::chrono::system_clock::now();
                                        auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(curr_time - extrusion_cali_set_hold_start);
                                        if (diff.count() > HOLD_TIMEOUT || diff.count() < 0
                                            || ams_id_int != (extrusion_cali_set_tray_id / 4)
                                            || tray_id_int != (extrusion_cali_set_tray_id % 4)) {
                                            if (tray_it->contains("k")) {
                                                curr_tray->k = (*tray_it)["k"].get<float>();
                                            }
                                            if (tray_it->contains("n")) {
                                                curr_tray->n = (*tray_it)["n"].get<float>();
                                            }
                                        }
                                    }
                                    // remove not in trayList
                                    for (auto tray_it = tray_id_set.begin(); tray_it != tray_id_set.end(); tray_it++) {
                                        std::string tray_id = *tray_it;
                                        auto tray = curr_ams->trayList.find(tray_id);
                                        if (tray != curr_ams->trayList.end()) {
                                            curr_ams->trayList.erase(tray_id);
                                            BOOST_LOG_TRIVIAL(trace) << "parse_json: remove ams_id=" << ams_id << ", tray_id=" << tray_id;
                                        }
                                    }
                                }
                            }
                            // remove not in amsList
                            for (auto it = ams_id_set.begin(); it != ams_id_set.end(); it++) {
                                std::string ams_id = *it;
                                auto ams = amsList.find(ams_id);
                                if (ams != amsList.end()) {
                                    BOOST_LOG_TRIVIAL(trace) << "parse_json: remove ams_id=" << ams_id;
                                    amsList.erase(ams_id);
                                }
                            }
                        }
                    }
                    /* vitrual tray*/
                    try {
                        if (jj.contains("vt_tray")) {
                            if (jj["vt_tray"].contains("id"))
                                vt_tray.id = jj["vt_tray"]["id"].get<std::string>();
                            auto curr_time = std::chrono::system_clock::now();
                            auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(curr_time - extrusion_cali_set_hold_start);
                            if (diff.count() > HOLD_TIMEOUT || diff.count() < 0
                                || extrusion_cali_set_tray_id != VIRTUAL_TRAY_ID) {
                                if (jj["vt_tray"].contains("k"))
                                    vt_tray.k = jj["vt_tray"]["k"].get<float>();
                                if (jj["vt_tray"].contains("n"))
                                    vt_tray.n = jj["vt_tray"]["n"].get<float>();
                            }
                            ams_support_virtual_tray = true;
                            if (vt_tray.hold_count > 0) {
                                vt_tray.hold_count--;
                            } else {
                                if (jj["vt_tray"].contains("tag_uid"))
                                    vt_tray.tag_uid = jj["vt_tray"]["tag_uid"].get<std::string>();
                                else
                                    vt_tray.tag_uid = "0";
                                if (jj["vt_tray"].contains("tray_info_idx") && jj["vt_tray"].contains("tray_type")) {
                                    vt_tray.setting_id = jj["vt_tray"]["tray_info_idx"].get<std::string>();
                                    std::string type = jj["vt_tray"]["tray_type"].get<std::string>();
                                    if (vt_tray.setting_id == "GFS00") {
                                        vt_tray.type = "PLA-S";
                                    }
                                    else if (vt_tray.setting_id == "GFS01") {
                                        vt_tray.type = "PA-S";
                                    }
                                    else {
                                        vt_tray.type = type;
                                    }
                                }
                                else {
                                    vt_tray.setting_id = "";
                                    vt_tray.type = "";
                                }
                                if (jj["vt_tray"].contains("tray_sub_brands"))
                                    vt_tray.sub_brands = jj["vt_tray"]["tray_sub_brands"].get<std::string>();
                                else
                                    vt_tray.sub_brands = "";
                                if (jj["vt_tray"].contains("tray_weight"))
                                    vt_tray.weight = jj["vt_tray"]["tray_weight"].get<std::string>();
                                else
                                    vt_tray.weight = "";
                                if (jj["vt_tray"].contains("tray_diameter"))
                                    vt_tray.diameter = jj["vt_tray"]["tray_diameter"].get<std::string>();
                                else
                                    vt_tray.diameter = "";
                                if (jj["vt_tray"].contains("tray_temp"))
                                    vt_tray.temp = jj["vt_tray"]["tray_temp"].get<std::string>();
                                else
                                    vt_tray.temp = "";
                                if (jj["vt_tray"].contains("tray_time"))
                                    vt_tray.time = jj["vt_tray"]["tray_time"].get<std::string>();
                                else
                                    vt_tray.time = "";
                                if (jj["vt_tray"].contains("bed_temp_type"))
                                    vt_tray.bed_temp_type = jj["vt_tray"]["bed_temp_type"].get<std::string>();
                                else
                                    vt_tray.bed_temp_type = "";
                                if (jj["vt_tray"].contains("bed_temp"))
                                    vt_tray.bed_temp = jj["vt_tray"]["bed_temp"].get<std::string>();
                                else
                                    vt_tray.bed_temp = "";
                                if (jj["vt_tray"].contains("nozzle_temp_max"))
                                    vt_tray.nozzle_temp_max = jj["vt_tray"]["nozzle_temp_max"].get<std::string>();
                                else
                                    vt_tray.nozzle_temp_max = "";
                                if (jj["vt_tray"].contains("nozzle_temp_min"))
                                    vt_tray.nozzle_temp_min = jj["vt_tray"]["nozzle_temp_min"].get<std::string>();
                                else
                                    vt_tray.nozzle_temp_min = "";
                                if (jj["vt_tray"].contains("xcam_info"))
                                    vt_tray.xcam_info = jj["vt_tray"]["xcam_info"].get<std::string>();
                                else
                                    vt_tray.xcam_info = "";
                                if (jj["vt_tray"].contains("tray_uuid"))
                                    vt_tray.uuid = jj["vt_tray"]["tray_uuid"].get<std::string>();
                                else
                                    vt_tray.uuid = "0";
                                if (jj["vt_tray"].contains("tray_color")) {
                                    auto color = jj["vt_tray"]["tray_color"].get<std::string>();
                                    vt_tray.update_color_from_str(color);
                                }
                                else {
                                    vt_tray.color = "";
                                }
                                vt_tray.cols.clear();
                                if (jj["vt_tray"].contains("cols")) {
                                    if (jj["vt_tray"].is_array()) {
                                        for (auto it = jj["vt_tray"].begin(); it != jj["vt_tray"].end(); it++) {
                                            vt_tray.cols.push_back(it.value().get<std::string>());
                                        }
                                    }
                                }
                                if (jj["vt_tray"].contains("remain")) {
                                    vt_tray.remain = jj["vt_tray"]["remain"].get<int>();
                                }
                                else {
                                    vt_tray.remain = -1;
                                }
                            }
                        } else {
                            ams_support_virtual_tray = false;
                        }
                    }
                    catch (...) {
                        ;
                    }
#pragma endregion
                } else if (jj["command"].get<std::string>() == "gcode_line") {
                    //ack of gcode_line
                    BOOST_LOG_TRIVIAL(debug) << "parse_json, ack of gcode_line = " << j.dump(4);
                    if (m_agent && is_studio_cmd(sequence_id)) {
                        json t;
                        t["dev_id"] = this->dev_id;
                        t["signal"] = this->wifi_signal;
                        m_agent->track_event("ack_cmd_gcode_line", t.dump());
                    }
                } else if (jj["command"].get<std::string>() == "project_file") {
                    //ack of project file
                    BOOST_LOG_TRIVIAL(debug) << "parse_json, ack of project_file = " << j.dump(4);
                    if (m_agent && is_studio_cmd(sequence_id)) {
                        json t;
                        t["dev_id"] = this->dev_id;
                        t["signal"] = this->wifi_signal;
                        m_agent->track_event("ack_cmd_project_file", t.dump());
                    }
                    std::string result;
                    if (jj.contains("result")) {
                        result = jj["result"].get<std::string>();
                        if (result == "FAIL") {
                            wxString text = _L("Failed to start printing job");
                            GUI::wxGetApp().show_dialog(text);
                        }
                    }
                } else if (jj["command"].get<std::string>() == "ams_filament_setting") {
                    // BBS trigger ams UI update
                    ams_version = -1;
                    if (jj["ams_id"].is_number()) {
                        int ams_id = jj["ams_id"].get<int>();
                        int tray_id = 0;
                        if (jj.contains("tray_id")) {
                            tray_id = jj["tray_id"].get<int>();
                        }
                        if (ams_id == 255 && tray_id == VIRTUAL_TRAY_ID) {
                            BOOST_LOG_TRIVIAL(trace) << "ams_filament_setting, parse tray info";
                            vt_tray.nozzle_temp_max = std::to_string(jj["nozzle_temp_max"].get<int>());
                            vt_tray.nozzle_temp_min = std::to_string(jj["nozzle_temp_min"].get<int>());
                            vt_tray.type = jj["tray_type"].get<std::string>();
                            vt_tray.color = jj["tray_color"].get<std::string>();
                            vt_tray.setting_id = jj["tray_info_idx"].get<std::string>();
                            // delay update
                            vt_tray.set_hold_count();
                        } else {
                            auto ams_it = amsList.find(std::to_string(ams_id));
                            if (ams_it != amsList.end()) {
                                tray_id = jj["tray_id"].get<int>();
                                auto tray_it = ams_it->second->trayList.find(std::to_string(tray_id));
                                if (tray_it != ams_it->second->trayList.end()) {
                                    BOOST_LOG_TRIVIAL(trace) << "ams_filament_setting, parse tray info";
                                    tray_it->second->nozzle_temp_max = std::to_string(jj["nozzle_temp_max"].get<int>());
                                    tray_it->second->nozzle_temp_min = std::to_string(jj["nozzle_temp_min"].get<int>());
                                    tray_it->second->type = jj["tray_type"].get<std::string>();
                                    tray_it->second->color = jj["tray_color"].get<std::string>();
                                    /*tray_it->second->cols.clear();
                                    if (jj.contains("cols")) {
                                        if (jj["cols"].is_array()) {
                                            for (auto it = jj["cols"].begin(); it != jj["cols"].end(); it++) {
                                                tray_it->second->cols.push_back(it.value().get<std::string>());
                                            }
                                        }
                                    }*/
                                    tray_it->second->setting_id = jj["tray_info_idx"].get<std::string>();
                                    // delay update
                                    tray_it->second->set_hold_count();
                                } else {
                                    BOOST_LOG_TRIVIAL(warning) << "ams_filament_setting, can not find in trayList, tray_id=" << tray_id;
                                }
                            } else {
                                BOOST_LOG_TRIVIAL(warning) << "ams_filament_setting, can not find in amsList, ams_id=" << ams_id;
                            }
                        }
                    }
                } else if (jj["command"].get<std::string>() == "xcam_control_set") {
                    if (jj.contains("module_name")) {
                        if (jj.contains("enable") || jj.contains("control")) {
                            bool enable = false;
                            if (jj.contains("enable"))
                                enable = jj["enable"].get<bool>();
                            else if (jj.contains("control"))
                                enable = jj["control"].get<bool>();
                            else {
                                ;
                            }
                            if (jj["module_name"].get<std::string>() == "first_layer_inspector") {
                                xcam_first_layer_inspector = enable;
                                xcam_first_layer_hold_count = HOLD_COUNT_MAX;
                            }
                            else if (jj["module_name"].get<std::string>() == "buildplate_marker_detector") {
                                xcam_buildplate_marker_detector = enable;
                                xcam_buildplate_marker_hold_count = HOLD_COUNT_MAX;
                            }
                            else if (jj["module_name"].get<std::string>() == "printing_monitor") {
                                xcam_ai_monitoring = enable;
                                xcam_ai_monitoring_hold_count = HOLD_COUNT_MAX;
                                if (jj.contains("halt_print_sensitivity")) {
                                    xcam_ai_monitoring_sensitivity = jj["halt_print_sensitivity"].get<std::string>();
                                }
                            }
                            else if (jj["module_name"].get<std::string>() == "spaghetti_detector") {
                                // old protocol
                                xcam_ai_monitoring = enable;
                                xcam_ai_monitoring_hold_count = HOLD_COUNT_MAX;
                                if (jj.contains("print_halt")) {
                                    if (jj["print_halt"].get<bool>())
                                        xcam_ai_monitoring_sensitivity = "medium";
                                }
                            }
                        }
                    }
                } else if(jj["command"].get<std::string>() == "print_option") {
                     try {
                          if (jj.contains("option")) {
                              if (jj["option"].is_number()) {
                                  int option = jj["option"].get<int>();
                                  _parse_print_option_ack(option);
                              }
                          }
                          if (jj.contains("auto_recovery")) {
                              xcam_auto_recovery_step_loss = jj["auto_recovery"].get<bool>();
                          }
                     }
                     catch(...) {
                     }
                } else if (jj["command"].get<std::string>() == "extrusion_cali") {
                    if (jj.contains("result") && jj["result"].get<std::string>() == "success") {
                        // enter extrusion cali
                    }
                } else if (jj["command"].get<std::string>() == "extrusion_cali_set") {
                    int ams_id = -1;
                    int tray_id = -1;
                    int curr_tray_id = -1;
                    if (jj.contains("tray_id")) {
                        try {
                            curr_tray_id = jj["tray_id"].get<int>();
                            if (curr_tray_id == VIRTUAL_TRAY_ID)
                                tray_id = curr_tray_id;
                            else if (curr_tray_id >= 0 && curr_tray_id < 16){
                                ams_id = curr_tray_id / 4;
                                tray_id = curr_tray_id % 4;
                            } else {
                                BOOST_LOG_TRIVIAL(trace) << "extrusion_cali_set: unsupported tray_id = " << curr_tray_id;
                            }
                        }
                        catch(...) {
                            ;
                        }
                    }
                    if (tray_id == VIRTUAL_TRAY_ID) {
                        if (jj.contains("k_value"))
                            vt_tray.k = jj["k_value"].get<float>();
                        if (jj.contains("n_coef"))
                            vt_tray.n = jj["n_coef"].get<float>();
                    } else {
                        auto ams_item = this->amsList.find(std::to_string(ams_id));
                        if (ams_item != this->amsList.end()) {
                            auto tray_item = ams_item->second->trayList.find(std::to_string(tray_id));
                            if (tray_item != ams_item->second->trayList.end()) {
                                if (jj.contains("k_value"))
                                    tray_item->second->k = jj["k_value"].get<float>();
                                if (jj.contains("n_coef"))
                                    tray_item->second->n = jj["n_coef"].get<float>();
                            }
                        }
                    }
                    extrusion_cali_set_tray_id = curr_tray_id;
                    extrusion_cali_set_hold_start = std::chrono::system_clock::now();
                }
            }
        }
        try {
            if (j.contains("info")) {
                if (j["info"].contains("command") && j["info"]["command"].get<std::string>() == "get_version") {
                    json j_module = j["info"]["module"];
                    module_vers.clear();
                    for (auto it = j_module.begin(); it != j_module.end(); it++) {
                        ModuleVersionInfo ver_info;
                        ver_info.name = (*it)["name"].get<std::string>();
                        if ((*it).contains("sw_ver"))
                            ver_info.sw_ver = (*it)["sw_ver"].get<std::string>();
                        if ((*it).contains("sn"))
                            ver_info.sn = (*it)["sn"].get<std::string>();
                        if ((*it).contains("hw_ver"))
                            ver_info.hw_ver = (*it)["hw_ver"].get<std::string>();
                        module_vers.emplace(ver_info.name, ver_info);
                    }
                    parse_version_func();
                    bool get_version_result = true;
                    if (j["info"].contains("result"))
                        if (j["info"]["result"].get<std::string>() == "fail")
                            get_version_result = false;
                    if ((!check_version_valid() && get_version_retry-- >= 0)
                        && get_version_result) {
                            BOOST_LOG_TRIVIAL(info) << "get_version_retry = " << get_version_retry;
                            boost::thread retry = boost::thread([this] {
                                boost::this_thread::sleep_for(boost::chrono::milliseconds(RETRY_INTERNAL));
                                GUI::wxGetApp().CallAfter([this] {
                                    this->command_get_version(false);
                            });
                        });
                    }
                }
            }
        } catch (...) {}
        try {
            if (j.contains("camera")) {
                if (j["camera"].contains("command")) {
                    if (j["camera"]["command"].get<std::string>() == "ipcam_timelapse") {
                        if (j["camera"]["control"].get<std::string>() == "enable")
                            this->camera_timelapse = true;
                        if (j["camera"]["control"].get<std::string>() == "disable")
                            this->camera_timelapse = false;
                        BOOST_LOG_TRIVIAL(info) << "ack of timelapse = " << camera_timelapse;
                    } else if (j["camera"]["command"].get<std::string>() == "ipcam_record_set") {
                        if (j["camera"]["control"].get<std::string>() == "enable")
                            this->camera_recording_when_printing = true;
                        if (j["camera"]["control"].get<std::string>() == "disable")
                            this->camera_recording_when_printing = false;
                        BOOST_LOG_TRIVIAL(info) << "ack of ipcam_record_set " << camera_recording_when_printing;
                    } else if (j["camera"]["command"].get<std::string>() == "ipcam_resolution_set") {
                        this->camera_resolution = j["camera"]["resolution"].get<std::string>();
                        BOOST_LOG_TRIVIAL(info) << "ack of resolution = " << camera_resolution;
                    }
                }
            }
        } catch (...) {}
        // upgrade
        try {
            if (j.contains("upgrade")) {
                if (j["upgrade"].contains("command")) {
                    if (j["upgrade"]["command"].get<std::string>() == "upgrade_confirm") {
                        this->upgrade_display_state = (int)UpgradingDisplayState::UpgradingInProgress;
                        upgrade_display_hold_count = HOLD_COUNT_MAX;
                        BOOST_LOG_TRIVIAL(info) << "ack of upgrade_confirm";
                    }
                }
            }
        }
        catch (...) {
            ;
        }
        // event info
        try {
            if (j.contains("event")) {
                if (j["event"].contains("event")) {
                    if (j["event"]["event"].get<std::string>() == "client.disconnected")
                        set_online_state(false);
                    else if (j["event"]["event"].get<std::string>() == "client.connected")
                        set_online_state(true);
                }
            }
        }
        catch (...)  {}
        parse_state_changed_event();
    }
    catch (...) {
        BOOST_LOG_TRIVIAL(trace) << "parse_json failed! dev_id=" << this->dev_id <<", payload = " << payload;
    }
    std::chrono::system_clock::time_point clock_stop = std::chrono::system_clock::now();
    auto diff = std::chrono::duration_cast<std::chrono::milliseconds>(clock_stop - clock_start);
    if (diff.count() > 10.0f) {
        BOOST_LOG_TRIVIAL(trace) << "parse_json timeout = " << diff.count();
    }
    return 0;
}
References _L, _parse_ams_status(), _parse_print_option_ack(), _parse_tray_now(), ahb_new_version_number, ams_calibrate_remain_flag, ams_exist_bits, ams_humidity, ams_insert_flag, ams_new_version_number, ams_power_on_flag, ams_rfid_status, ams_support_use_ams, ams_support_virtual_tray, ams_user_setting_hold_count, ams_version, amsList, Slic3r::AmsTray::bed_temp, bed_temp, bed_temp_target, Slic3r::AmsTray::bed_temp_type, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::begin(), big_fan1_speed, big_fan2_speed, camera_recording_hold_count, camera_recording_when_printing, camera_resolution, camera_resolution_hold_count, camera_timelapse, camera_timelapse_hold_count, chamber_light, chamber_temp, check_version_valid(), Slic3r::AmsTray::color, Slic3r::AmsTray::cols, command_get_version(), command_request_push_all(), Slic3r::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::contains(), cooling_fan_speed, curr_layer, dev_id, Slic3r::AmsTray::diameter, Slic3r::diff(), json_diff::diff2all(), json_diff::diff2all_base_reset(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::empty(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::end(), extrusion_cali_set_hold_start, extrusion_cali_set_tray_id, fan_gear, filam_bak, Slic3r::AmsTray::filament_setting_id, firmware_type, Slic3r::FIRMWARE_TYPE_ENGINEER, Slic3r::FIRMWARE_TYPE_PRODUCTION, floor(), frame_temp, gcode_file_prepare_percent, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), get_subtask(), get_version_retry, has_ipcam, HAS_SDCARD_NORMAL, heatbreak_fan_speed, hms_list, Slic3r::AmsTray::hold_count, HOLD_COUNT_MAX, HOLD_TIMEOUT, home_flag, Slic3r::Ams::humidity, hw_switch_state, Slic3r::MachineObject::ModuleVersionInfo::hw_ver, Slic3r::AmsTray::id, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::insert(), int, is_ams_need_update, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::is_array(), Slic3r::AmsTray::is_exists, Slic3r::Ams::is_exists, json_diff::is_need_request(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::is_null(), is_studio_cmd(), is_support_layer_num, is_xcam_buildplate_supported, Slic3r::AmsTray::k, last_online_version, last_push_time, last_update_time, light_effect_parse(), link_ams, link_th, m_agent, m_gcode_file, m_new_ver_list_exist, m_push_count, m_tray_tar, mc_left_time, mc_print_error_code, mc_print_line_number, mc_print_percent, mc_print_stage, mc_print_sub_stage, module_vers, Slic3r::AmsTray::n, Slic3r::MachineObject::ModuleVersionInfo::name, new_ver_list, NO_SDCARD, nozzle_diameter, nozzle_temp, Slic3r::AmsTray::nozzle_temp_max, Slic3r::AmsTray::nozzle_temp_min, nozzle_temp_target, obj_subtask_id, online_ahb, online_rfid, online_version, ota_new_version_number, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), Slic3r::HMSItem::parse_hms_info(), parse_msg_count, parse_printer_type(), parse_state_changed_event(), parse_status(), parse_version_func(), plate_index, print_error, print_json, print_status, print_type, printer_type, printing_speed_lvl, printing_speed_mag, Slic3r::BBLSubTask::printing_status, queue_number, Slic3r::AmsTray::remain, RETRY_INTERNAL, round(), sdcard_state, Slic3r::AmsTray::set_hold_count(), set_online_state(), set_print_state(), Slic3r::AmsTray::setting_id, Slic3r::MachineObject::ModuleVersionInfo::sn, stage_curr, stage_list_info, Slic3r::AmsTray::sub_brands, subtask_name, Slic3r::MachineObject::ModuleVersionInfo::sw_new_ver, Slic3r::MachineObject::ModuleVersionInfo::sw_ver, Slic3r::AmsTray::tag_uid, Slic3r::BBLSubTask::task_id, task_id_, Slic3r::BBLSubTask::task_progress, Slic3r::AmsTray::temp, Slic3r::AmsTray::time, total_layers, Slic3r::trace(), Slic3r::NetworkAgent::track_event(), tray_exist_bits, tray_is_bbl_bits, tray_read_done_bits, tray_reading_bits, Slic3r::Ams::trayList, Slic3r::AmsTray::type, Slic3r::AmsTray::update_color_from_str(), update_slice_info(), upgrade_consistency_request, upgrade_display_hold_count, upgrade_display_state, upgrade_err_code, upgrade_force_upgrade, upgrade_message, upgrade_module, upgrade_new_version, upgrade_progress, upgrade_status, UpgradingAvaliable, UpgradingFinished, UpgradingInProgress, UpgradingUnavaliable, Slic3r::AmsTray::uuid, VIRTUAL_TRAY_ID, vt_tray, Slic3r::AmsTray::weight, wifi_signal, work_light, xcam_ai_monitoring, xcam_ai_monitoring_hold_count, xcam_ai_monitoring_sensitivity, xcam_auto_recovery_step_loss, xcam_buildplate_marker_detector, xcam_buildplate_marker_hold_count, xcam_first_layer_hold_count, xcam_first_layer_inspector, and Slic3r::AmsTray::xcam_info.
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks().
parse_printer_type()
std::string Slic3r::MachineObject::parse_printer_type (std::string type_str) static
{
    if (type_str.compare("3DPrinter-X1") == 0) {
        return "BL-P002";
    } else if (type_str.compare("3DPrinter-X1-Carbon") == 0) {
        return "BL-P001";
    } else if (type_str.compare("BL-P001") == 0) {
        return type_str;
    } else if (type_str.compare("BL-P003") == 0) {
        return type_str;
    } else {
        return DeviceManager::parse_printer_type(type_str);
    }
    return "";
}
References Slic3r::DeviceManager::parse_printer_type().
Referenced by Slic3r::DeviceManager::on_machine_alive(), and parse_json().
parse_state_changed_event()
void Slic3r::MachineObject::parse_state_changed_event ()
{
    // parse calibration done
    if (last_mc_print_stage != mc_print_stage) {
        if (mc_print_stage == 1 && boost::contains(m_gcode_file, "auto_cali_for_user")) {
            calibration_done = true;
        } else {
            calibration_done = false;
        }
    }
    last_mc_print_stage = mc_print_stage;
}
References calibration_done, last_mc_print_stage, m_gcode_file, and mc_print_stage.
Referenced by parse_json().
parse_status()
void Slic3r::MachineObject::parse_status (int flag)
{
    is_220V_voltage             = ((flag >> 3) & 0x1) != 0;
    if (xcam_auto_recovery_hold_count > 0)
        xcam_auto_recovery_hold_count--;
    else {
        xcam_auto_recovery_step_loss = ((flag >> 4) & 0x1) != 0;
    }
    camera_recording            = ((flag >> 5) & 0x1) != 0;
    ams_calibrate_remain_flag   = ((flag >> 7) & 0x1) != 0;
    if (ams_print_option_count > 0)
        ams_print_option_count--;
    else {
        ams_auto_switch_filament_flag = ((flag >> 10) & 0x1) != 0;
    }
    sdcard_state = MachineObject::SdcardState((flag >> 8) & 0x11);
}
References ams_auto_switch_filament_flag, ams_calibrate_remain_flag, ams_print_option_count, camera_recording, is_220V_voltage, sdcard_state, xcam_auto_recovery_hold_count, and xcam_auto_recovery_step_loss.
Referenced by parse_json().
parse_version_func()
void Slic3r::MachineObject::parse_version_func ()
{
    auto ota_version = module_vers.find("ota");
    auto esp32_version = module_vers.find("esp32");
    if (printer_type == "BL-P001" ||
        printer_type == "BL-P002") {
        if (ota_version != module_vers.end()) {
            if (ota_version->second.sw_ver.compare("01.01.01.00") <= 0) {
                ams_support_remain                      = false;
                ams_support_auto_switch_filament_flag   = false;
                is_xcam_buildplate_supported            = false;
                xcam_support_recovery_step_loss         = false;
                is_support_send_to_sdcard               = false;
                is_support_1080dpi                      = false;
                is_support_ai_monitoring                = false;
                is_support_ams_humidity                 = false;
            } else {
                ams_support_remain                      = true;
                ams_support_auto_switch_filament_flag   = true;
                is_xcam_buildplate_supported            = true;
                xcam_support_recovery_step_loss         = true;
                is_support_send_to_sdcard               = true;
                is_support_1080dpi                      = true;
                is_support_ai_monitoring                = true;
                is_support_ams_humidity                 = true;
            }
            if (firmware_type == PrinterFirmwareType::FIRMWARE_TYPE_ENGINEER)
                local_use_ssl = false;
            else {
                local_use_ssl = ota_version->second.sw_ver.compare("01.03.01.04") >= 0;
            }
        }
    } else if (printer_type == "C11") {
        if (firmware_type == PrinterFirmwareType::FIRMWARE_TYPE_ENGINEER)
            local_use_ssl = false;
        else {
            local_use_ssl = true;
        }
        is_cloud_print_only = true;
        if (ota_version != module_vers.end()) {
            is_support_send_to_sdcard = ota_version->second.sw_ver.compare("01.02.00.00") >= 0;
        }
        if (esp32_version != module_vers.end()) {
            ams_support_auto_switch_filament_flag = esp32_version->second.sw_ver.compare("00.03.11.50") >= 0;
        }
    }
}
References ams_support_auto_switch_filament_flag, ams_support_remain, firmware_type, Slic3r::FIRMWARE_TYPE_ENGINEER, is_cloud_print_only, is_support_1080dpi, is_support_ai_monitoring, is_support_ams_humidity, is_support_send_to_sdcard, is_xcam_buildplate_supported, local_use_ssl, module_vers, printer_type, and xcam_support_recovery_step_loss.
Referenced by is_function_supported(), and parse_json().
publish_gcode()
int Slic3r::MachineObject::publish_gcode (std::string gcode_str)
{
    json j;
    j["print"]["command"] = "gcode_line";
    j["print"]["param"] = gcode_str;
    j["print"]["sequence_id"] = std::to_string(MachineObject::m_sequence_id++);
    if (m_agent) {
        j["print"]["user_id"] = m_agent->get_user_id();
        json t;
        t["dev_id"] = this->dev_id;
        t["signal"] = this->wifi_signal;
        m_agent->track_event("cmd_gcode_line", t.dump());
    }
    return publish_json(j.dump());
}
References dev_id, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), Slic3r::NetworkAgent::get_user_id(), m_agent, m_sequence_id, publish_json(), Slic3r::NetworkAgent::track_event(), and wifi_signal.
Referenced by command_ams_calibrate(), command_ams_refresh_rfid(), command_ams_select_tray(), command_ams_switch(), command_auto_leveling(), command_axis_control(), command_control_fan(), command_control_fan_val(), command_go_home(), command_set_bed(), command_set_nozzle(), and command_xyz_abs().
publish_json()
int Slic3r::MachineObject::publish_json (std::string json_str, int qos = 0)
{
    if (is_lan_mode_printer()) {
        return local_publish_json(json_str, qos);
    } else {
        return cloud_publish_json(json_str, qos);
    }
}
References cloud_publish_json(), is_lan_mode_printer(), and local_publish_json().
Referenced by command_ams_change_filament(), command_ams_control(), command_ams_filament_settings(), command_ams_switch_filament(), command_ams_user_settings(), command_ams_user_settings(), command_clean_print_error(), command_consistency_upgrade_confirm(), command_extrusion_cali_set(), command_get_version(), command_ipcam_record(), command_ipcam_resolution_set(), command_ipcam_timelapse(), command_pushing(), command_request_push_all(), command_set_chamber_light(), command_set_printing_option(), command_set_printing_speed(), command_set_work_light(), command_start_calibration(), command_start_extrusion_cali(), command_task_abort(), command_task_pause(), command_task_resume(), command_unload_filament(), command_upgrade_confirm(), command_upgrade_firmware(), command_upgrade_module(), command_xcam_control(), and publish_gcode().
reset()
void Slic3r::MachineObject::reset ()
{
    BOOST_LOG_TRIVIAL(trace) << "reset dev_id=" << dev_id;
    last_update_time = std::chrono::system_clock::now();
    m_push_count = 0;
    is_220V_voltage = false;
    get_version_retry = 0;
    camera_recording = false;
    camera_recording_when_printing = false;
    camera_timelapse = false;
    camera_resolution = "";
    printing_speed_mag = 100;
    gcode_file_prepare_percent = 0;
    iot_print_status = "";
    print_status = "";
    last_mc_print_stage = -1;
    m_new_ver_list_exist = false;
    extruder_axis_status = LOAD;
    nozzle_diameter = 0.0f;
    vt_tray.reset();
    subtask_ = nullptr;
}
References camera_recording, camera_recording_when_printing, camera_resolution, camera_timelapse, dev_id, extruder_axis_status, gcode_file_prepare_percent, get_version_retry, iot_print_status, is_220V_voltage, last_mc_print_stage, last_update_time, LOAD, m_new_ver_list_exist, m_push_count, nozzle_diameter, print_status, printing_speed_mag, Slic3r::AmsTray::reset(), subtask_, Slic3r::trace(), and vt_tray.
Referenced by MachineObject().
reset_mapping_result()
void Slic3r::MachineObject::reset_mapping_result (std::vector< FilamentInfo > & result)
{
    for (int i = 0; i < result.size(); i++) {
        result[i].tray_id = -1;
        result[i].distance = 99999;
        result[i].mapping_result = 0;
    }
}
Referenced by ams_filament_mapping().
reset_update_time()
void Slic3r::MachineObject::reset_update_time ()
{
    BOOST_LOG_TRIVIAL(trace) << "reset reset_update_time, dev_id =" << dev_id;
    last_update_time = std::chrono::system_clock::now();
}
References dev_id, last_update_time, and Slic3r::trace().
Referenced by Slic3r::GUI::MonitorPanel::Show().
set_access_code()
void Slic3r::MachineObject::set_access_code (std::string code)
{
    this->access_code = code;
    AppConfig *config = GUI::wxGetApp().app_config;
    if (config && !code.empty()) {
        GUI::wxGetApp().app_config->set_str("access_code", dev_id, code);
    }
}
References access_code, dev_id, and Slic3r::AppConfig::set_str().
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::DeviceManager::on_machine_alive(), Slic3r::GUI::UnBindMachineDialog::on_unbind_printer(), and Slic3r::DeviceManager::parse_user_print_info().
set_bind_status()
void Slic3r::MachineObject::set_bind_status (std::string status)
{
    bind_user_name = status;
}
References bind_user_name.
Referenced by Slic3r::DeviceManager::parse_user_print_info().
set_dev_ip()
void Slic3r::MachineObject::set_dev_ip (std::string ip) inline
{dev_ip = ip;};
References dev_ip.
set_lan_mode_connection_state()
void Slic3r::MachineObject::set_lan_mode_connection_state (bool state) inline
{m_lan_mode_connection_state = state;};
References m_lan_mode_connection_state.
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks().
set_online_state()
void Slic3r::MachineObject::set_online_state (bool on_off)
{
    m_is_online = on_off;
}
References m_is_online.
Referenced by parse_json().
set_print_state()
void Slic3r::MachineObject::set_print_state (std::string status)
{
    print_status = status;
}
References print_status.
Referenced by parse_json().
set_user_access_code()
void Slic3r::MachineObject::set_user_access_code (std::string code)
{
    this->user_access_code = code;
    AppConfig* config = GUI::wxGetApp().app_config;
    if (config) {
        GUI::wxGetApp().app_config->set_str("user_access_code", dev_id, code);
    }
}
References dev_id, Slic3r::AppConfig::set_str(), and user_access_code.
Referenced by Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::GUI::ConnectPrinterDialog::on_button_confirm(), and Slic3r::DeviceManager::on_machine_alive().
update_slice_info()
void Slic3r::MachineObject::update_slice_info (std::string project_id, std::string profile_id, std::string subtask_id, int plate_idx)
{
    if (!m_agent) return;
    if (project_id_ != project_id || profile_id_ != profile_id || slice_info == nullptr || subtask_id_ != subtask_id) {
        project_id_ = project_id;
        profile_id_ = profile_id;
        subtask_id_ = subtask_id;
        if (project_id.empty()
            || profile_id.empty()
            || subtask_id.empty()) {
            return;
        }
        if (project_id.compare("0") == 0
            || profile_id.compare("0") == 0) return;
        BOOST_LOG_TRIVIAL(trace) << "slice_info: start";
        slice_info = new BBLSliceInfo();
        get_slice_info_thread = new boost::thread([this, project_id, profile_id, subtask_id, plate_idx] {
                int plate_index = -1;
                if (!m_agent) return;
                if (plate_idx >= 0) {
                    plate_index = plate_idx;
                } else {
                    if (subtask_id.compare("0") == 0)
                        return;
                    m_agent->get_task_plate_index(subtask_id, &plate_index);
                }
                if (plate_index >= 0) {
                    std::string slice_json;
                    m_agent->get_slice_info(project_id, profile_id, plate_index, &slice_json);
                    if (slice_json.empty()) return;
                    //parse json
                    try {
                        json j = json::parse(slice_json);
                        if (!j["prediction"].is_null())
                            slice_info->prediction = j["prediction"].get<int>();
                        if (!j["weight"].is_null())
                            slice_info->weight = j["weight"].get<float>();
                        if (!j["thumbnail"].is_null()) {
                            slice_info->thumbnail_url = j["thumbnail"]["url"].get<std::string>();
                            BOOST_LOG_TRIVIAL(trace) << "slice_info: thumbnail url=" << slice_info->thumbnail_url;
                        }
                        if (!j["filaments"].is_null()) {
                            for (auto filament : j["filaments"]) {
                                FilamentInfo f;
                                f.color = filament["color"].get<std::string>();
                                f.type = filament["type"].get<std::string>();
                                f.used_g = stof(filament["used_g"].get<std::string>());
                                f.used_m = stof(filament["used_m"].get<std::string>());
                                slice_info->filaments_info.push_back(f);
                            }
                        }
                    } catch(...) {
                        ;
                    }
                }
            });
    }
}
References Slic3r::f(), Slic3r::BBLSliceInfo::filaments_info, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), Slic3r::NetworkAgent::get_slice_info(), get_slice_info_thread, Slic3r::NetworkAgent::get_task_plate_index(), m_agent, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), plate_index, Slic3r::BBLSliceInfo::prediction, profile_id_, project_id_, slice_info, subtask_id_, Slic3r::BBLSliceInfo::thumbnail_url, Slic3r::trace(), and Slic3r::BBLSliceInfo::weight.
Referenced by parse_json().
Member Data Documentation
access_code
std::string Slic3r::MachineObject::access_code private
Referenced by get_access_code(), and set_access_code().
ahb_new_version_number
std::string Slic3r::MachineObject::ahb_new_version_number
Referenced by parse_json(), and Slic3r::GUI::MachineInfoPanel::update_ams_ext().
ams_auto_switch_filament_flag
bool Slic3r::MachineObject::ams_auto_switch_filament_flag { false }
Referenced by command_ams_switch_filament(), parse_status(), and Slic3r::GUI::StatusPanel::update_ams().
ams_calibrate_remain_flag
bool Slic3r::MachineObject::ams_calibrate_remain_flag { false }
Referenced by MachineObject(), command_ams_user_settings(), command_ams_user_settings(), parse_json(), parse_status(), and Slic3r::GUI::StatusPanel::update_ams().
ams_exist_bits
long Slic3r::MachineObject::ams_exist_bits = 0
Referenced by MachineObject(), has_ams(), parse_json(), Slic3r::GUI::StatusPanel::update_ams(), and Slic3r::GUI::MachineInfoPanel::update_ams_ext().
ams_humidity
int Slic3r::MachineObject::ams_humidity
Referenced by MachineObject(), and parse_json().
ams_insert_flag
bool Slic3r::MachineObject::ams_insert_flag { false }
Referenced by MachineObject(), command_ams_user_settings(), command_ams_user_settings(), Slic3r::GUI::StatusPanel::on_ams_setting_click(), parse_json(), and Slic3r::GUI::StatusPanel::update_ams().
ams_new_version_number
std::string Slic3r::MachineObject::ams_new_version_number
Referenced by parse_json(), and Slic3r::GUI::MachineInfoPanel::update_ams_ext().
ams_power_on_flag
bool Slic3r::MachineObject::ams_power_on_flag { false }
Referenced by MachineObject(), command_ams_user_settings(), command_ams_user_settings(), Slic3r::GUI::StatusPanel::on_ams_setting_click(), parse_json(), and Slic3r::GUI::StatusPanel::update_ams().
ams_print_option_count
int Slic3r::MachineObject::ams_print_option_count = 0
Referenced by command_ams_switch_filament(), and parse_status().
ams_rfid_status
int Slic3r::MachineObject::ams_rfid_status = 0
Referenced by MachineObject(), and parse_json().
ams_status_main
AmsStatusMain Slic3r::MachineObject::ams_status_main
Referenced by _parse_ams_status(), can_unload_filament(), Slic3r::GUI::StatusPanel::update_ams(), and Slic3r::GUI::StatusPanel::update_ams_control_state().
ams_status_sub
int Slic3r::MachineObject::ams_status_sub
Referenced by _parse_ams_status(), and Slic3r::GUI::StatusPanel::update_ams().
ams_support_auto_switch_filament_flag
bool Slic3r::MachineObject::ams_support_auto_switch_filament_flag { true }
Referenced by is_function_supported(), and parse_version_func().
ams_support_remain
bool Slic3r::MachineObject::ams_support_remain { true }
Referenced by Slic3r::GUI::StatusPanel::on_ams_setting_click(), and parse_version_func().
ams_support_use_ams
bool Slic3r::MachineObject::ams_support_use_ams { false }
Referenced by MachineObject(), parse_json(), Slic3r::GUI::SelectMachineDialog::update_ams_check(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
ams_support_virtual_tray
bool Slic3r::MachineObject::ams_support_virtual_tray { true }
Referenced by is_function_supported(), and parse_json().
ams_user_setting_hold_count
int Slic3r::MachineObject::ams_user_setting_hold_count = 0
Referenced by command_ams_user_settings(), command_ams_user_settings(), and parse_json().
ams_version
int Slic3r::MachineObject::ams_version = 0
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_ams().
amsList
std::map<std::string, Ams*> Slic3r::MachineObject::amsList
Referenced by ~MachineObject(), ams_filament_mapping(), get_ams_tray(), get_curr_Ams(), Slic3r::GUI::MonitorPanel::init_timer(), is_mapping_exceed_filament(), is_valid_mapping_result(), Slic3r::GUI::StatusPanel::on_ams_load_curr(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::StatusPanel::on_ams_selected(), Slic3r::GUI::StatusPanel::on_ams_setting_click(), Slic3r::GUI::AMSMaterialsSetting::on_clr_picker(), Slic3r::GUI::StatusPanel::on_filament_edit(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::SelectMachineDialog::on_ok_btn(), Slic3r::GUI::MonitorPanel::on_select_printer(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), parse_json(), Slic3r::GUI::SelectMachineDialog::set_default(), Slic3r::GUI::MonitorPanel::Show(), Slic3r::GUI::TrayListModel::update(), Slic3r::GUI::StatusPanel::update_ams(), Slic3r::GUI::MachineInfoPanel::update_ams_ext(), and Slic3r::GUI::AmsReplaceMaterialDialog::update_machine_obj().
bed_temp
float Slic3r::MachineObject::bed_temp
Referenced by MachineObject(), command_extrusion_cali_set(), command_start_extrusion_cali(), parse_json(), and Slic3r::GUI::StatusPanel::update_temp_ctrl().
bed_temp_target
float Slic3r::MachineObject::bed_temp_target
Referenced by MachineObject(), parse_json(), and Slic3r::GUI::StatusPanel::update_temp_ctrl().
big_fan1_speed
int Slic3r::MachineObject::big_fan1_speed = 0
Referenced by MachineObject(), parse_json(), Slic3r::GUI::FanControlPopup::update_fan_data(), and Slic3r::GUI::StatusPanel::update_misc_ctrl().
big_fan2_speed
int Slic3r::MachineObject::big_fan2_speed = 0
Referenced by MachineObject(), parse_json(), Slic3r::GUI::FanControlPopup::update_fan_data(), and Slic3r::GUI::StatusPanel::update_misc_ctrl().
bind_sec_link
std::string Slic3r::MachineObject::bind_sec_link
Referenced by Slic3r::DeviceManager::on_machine_alive().
bind_state
std::string Slic3r::MachineObject::bind_state
Referenced by is_avaliable(), and Slic3r::DeviceManager::on_machine_alive().
bind_user_id
std::string Slic3r::MachineObject::bind_user_id
bind_user_name
std::string Slic3r::MachineObject::bind_user_name
Referenced by get_bind_str(), and set_bind_status().
calibration_done
bool Slic3r::MachineObject::calibration_done { false }
Referenced by is_calibration_done(), is_in_calibration(), Slic3r::GUI::CalibrationDialog::on_start_calibration(), and parse_state_changed_event().
camera_recording
bool Slic3r::MachineObject::camera_recording { false }
Referenced by is_recording(), parse_status(), and reset().
camera_recording_hold_count
int Slic3r::MachineObject::camera_recording_hold_count = 0
Referenced by command_ipcam_record(), command_ipcam_resolution_set(), and parse_json().
camera_recording_when_printing
bool Slic3r::MachineObject::camera_recording_when_printing { false }
Referenced by Slic3r::GUI::CameraPopup::CameraPopup(), command_ipcam_record(), is_recording_enable(), parse_json(), reset(), and Slic3r::GUI::CameraPopup::update().
camera_resolution
std::string Slic3r::MachineObject::camera_resolution = ""
Referenced by Slic3r::GUI::CameraPopup::CameraPopup(), command_ipcam_resolution_set(), parse_json(), reset(), and Slic3r::GUI::CameraPopup::update().
camera_resolution_hold_count
int Slic3r::MachineObject::camera_resolution_hold_count = 0
Referenced by command_ipcam_resolution_set(), and parse_json().
camera_timelapse
bool Slic3r::MachineObject::camera_timelapse { false }
Referenced by command_ipcam_timelapse(), is_timelapse(), parse_json(), and reset().
camera_timelapse_hold_count
int Slic3r::MachineObject::camera_timelapse_hold_count = 0
Referenced by command_ipcam_timelapse(), and parse_json().
chamber_light
LIGHT_EFFECT Slic3r::MachineObject::chamber_light
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_misc_ctrl().
chamber_temp
float Slic3r::MachineObject::chamber_temp
Referenced by MachineObject(), parse_json(), and Slic3r::GUI::StatusPanel::update_temp_ctrl().
cooling_fan_speed
int Slic3r::MachineObject::cooling_fan_speed = 0
Referenced by MachineObject(), parse_json(), Slic3r::GUI::FanControlPopup::update_fan_data(), and Slic3r::GUI::StatusPanel::update_misc_ctrl().
curr_layer
int Slic3r::MachineObject::curr_layer = 0
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_subtask().
dev_connection_type
std::string Slic3r::MachineObject::dev_connection_type
Referenced by connection_type(), is_lan_mode_printer(), Slic3r::DeviceManager::on_machine_alive(), and Slic3r::GUI::StatusPanel::update().
dev_id
std::string Slic3r::MachineObject::dev_id
Referenced by Slic3r::GUI::MachineListModel::add_machine(), cloud_publish_json(), command_pushing(), command_request_push_all(), connect(), get_firmware_info(), get_user_access_code(), Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::GUI::MonitorPanel::init_timer(), is_connected(), Slic3r::GUI::SelectMachineDialog::is_same_printer_model(), local_publish_json(), Slic3r::GUI::ConnectPrinterDialog::on_button_confirm(), Slic3r::GUI::EditDevNameDialog::on_edit_name(), Slic3r::GUI::MachineObjectPanel::on_mouse_left_up(), Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SendToPrinterDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::MonitorPanel::on_select_printer(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::SendToPrinterDialog::on_selection_changed(), parse_json(), Slic3r::DeviceManager::parse_user_print_info(), publish_gcode(), reset(), reset_update_time(), set_access_code(), Slic3r::GUI::SelectMachineDialog::set_default(), set_user_access_code(), Slic3r::GUI::MediaFilePanel::SetMachineObject(), Slic3r::GUI::MediaPlayCtrl::SetMachineObject(), Slic3r::GUI::MonitorPanel::Show(), Slic3r::GUI::MonitorPanel::show_status(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::MachineInfoPanel::update(), Slic3r::GUI::MonitorPanel::update_all(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::SelectMachineDialog::update_user_printer(), and Slic3r::GUI::SendToPrinterDialog::update_user_printer().
dev_ip
std::string Slic3r::MachineObject::dev_ip
Referenced by Slic3r::GUI::MachineListModel::add_machine(), check_valid_ip(), connect(), is_local(), Slic3r::DeviceManager::on_machine_alive(), Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SendToPrinterDialog::on_ok(), Slic3r::DeviceManager::parse_user_print_info(), Slic3r::GUI::SelectMachinePopup::search_for_printer(), set_dev_ip(), Slic3r::GUI::InputIpAddressDialog::set_machine_obj(), Slic3r::GUI::MediaFilePanel::SetMachineObject(), Slic3r::GUI::MediaPlayCtrl::SetMachineObject(), and Slic3r::GUI::SendToPrinterDialog::update_show_status().
dev_name
std::string Slic3r::MachineObject::dev_name
Referenced by Slic3r::GUI::MachineListModel::add_machine(), Slic3r::GUI::MachineObjectPanel::doRender(), Slic3r::GUI::GUI_App::init_networking_callbacks(), Slic3r::DeviceManager::parse_user_print_info(), Slic3r::GUI::SelectMachinePopup::search_for_printer(), Slic3r::GUI::EditDevNameDialog::set_machine_obj(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::MachineInfoPanel::update(), Slic3r::GUI::StatusPanel::update_ams(), Slic3r::GUI::SelectMachineDialog::update_lan_machine_list(), Slic3r::GUI::MonitorPanel::update_status(), and Slic3r::GUI::SelectMachineDialog::update_user_printer().
extruder_axis_status
enum ExtruderAxisStatus Slic3r::MachineObject::extruder_axis_status = LOAD
Referenced by command_axis_control(), reset(), and Slic3r::GUI::StatusPanel::update_extruder_status().
extrusion_cali_hold_count
int Slic3r::MachineObject::extrusion_cali_hold_count = 0
extrusion_cali_set_hold_start
std::chrono::system_clock::time_point Slic3r::MachineObject::extrusion_cali_set_hold_start
Referenced by parse_json().
extrusion_cali_set_tray_id
int Slic3r::MachineObject::extrusion_cali_set_tray_id = -1
Referenced by parse_json().
extrusion_ratio_map
std::map<std::string, ExtrusionRatioInfo> Slic3r::MachineObject::extrusion_ratio_map
fan_gear
uint32_t Slic3r::MachineObject::fan_gear = 0
Referenced by MachineObject(), and parse_json().
filam_bak
std::vector<int> Slic3r::MachineObject::filam_bak
Referenced by Slic3r::GUI::StatusPanel::on_ams_filament_backup(), parse_json(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), and Slic3r::GUI::AmsReplaceMaterialDialog::update_machine_obj().
firmware_list
std::vector<FirmwareInfo> Slic3r::MachineObject::firmware_list
Referenced by get_firmware_info(), and Slic3r::GUI::MachineInfoPanel::on_show_release_note().
firmware_type
PrinterFirmwareType Slic3r::MachineObject::firmware_type
Referenced by get_firmware_type_str(), parse_json(), and parse_version_func().
frame_temp
float Slic3r::MachineObject::frame_temp
Referenced by MachineObject(), and parse_json().
gcode_file_prepare_percent
int Slic3r::MachineObject::gcode_file_prepare_percent = 0
Referenced by parse_json(), reset(), and Slic3r::GUI::StatusPanel::update_subtask().
get_slice_info_thread
boost::thread* Slic3r::MachineObject::get_slice_info_thread { nullptr }
Referenced by ~MachineObject(), and update_slice_info().
get_version_retry
int Slic3r::MachineObject::get_version_retry = 0
Referenced by check_version_valid(), command_get_version(), parse_json(), and reset().
has_ipcam
bool Slic3r::MachineObject::has_ipcam { false }
Referenced by MachineObject(), Slic3r::GUI::CameraPopup::check_func_supported(), parse_json(), and Slic3r::GUI::MediaPlayCtrl::SetMachineObject().
heatbreak_fan_speed
int Slic3r::MachineObject::heatbreak_fan_speed = 0
Referenced by MachineObject(), and parse_json().
hms_list
std::vector<HMSItem> Slic3r::MachineObject::hms_list
Referenced by parse_json(), and Slic3r::GUI::HMSPanel::update().
home_flag
int Slic3r::MachineObject::home_flag
Referenced by MachineObject(), is_axis_at_home(), and parse_json().
hw_switch_state
int Slic3r::MachineObject::hw_switch_state
Referenced by MachineObject(), can_unload_filament(), is_filament_at_extruder(), and parse_json().
iot_print_status
std::string Slic3r::MachineObject::iot_print_status
Referenced by is_in_printing(), Slic3r::DeviceManager::parse_user_print_info(), and reset().
is_220V_voltage
bool Slic3r::MachineObject::is_220V_voltage { false }
Referenced by get_bed_temperature_limit(), parse_status(), and reset().
is_ams_need_update
bool Slic3r::MachineObject::is_ams_need_update
Referenced by MachineObject(), Slic3r::GUI::GUI_App::init_networking_callbacks(), and parse_json().
is_cloud_print_only
bool Slic3r::MachineObject::is_cloud_print_only {false}
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok(), and parse_version_func().
is_support_1080dpi
bool Slic3r::MachineObject::is_support_1080dpi {false}
Referenced by Slic3r::GUI::CameraPopup::check_func_supported(), and parse_version_func().
is_support_ai_monitoring
bool Slic3r::MachineObject::is_support_ai_monitoring {false}
Referenced by is_function_supported(), and parse_version_func().
is_support_ams_humidity
bool Slic3r::MachineObject::is_support_ams_humidity {true}
Referenced by parse_version_func(), and Slic3r::GUI::StatusPanel::update_ams().
is_support_filament_edit_virtual_tray
bool Slic3r::MachineObject::is_support_filament_edit_virtual_tray {true}
Referenced by Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::StatusPanel::update_ams(), and Slic3r::GUI::AMSMaterialsSetting::update_widgets().
is_support_layer_num
bool Slic3r::MachineObject::is_support_layer_num { false }
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_subtask().
is_support_send_to_sdcard
bool Slic3r::MachineObject::is_support_send_to_sdcard { true }
Referenced by is_function_supported(), and parse_version_func().
is_xcam_buildplate_supported
bool Slic3r::MachineObject::is_xcam_buildplate_supported { true }
Referenced by is_function_supported(), parse_json(), and parse_version_func().
last_alive
time_t Slic3r::MachineObject::last_alive
Referenced by Slic3r::DeviceManager::on_machine_alive().
last_extrusion_cali_start_time
std::chrono::system_clock::time_point Slic3r::MachineObject::last_extrusion_cali_start_time
Referenced by command_start_extrusion_cali(), is_extrusion_cali_finished(), and is_in_extrusion_cali().
last_mc_print_stage
int Slic3r::MachineObject::last_mc_print_stage
Referenced by parse_state_changed_event(), and reset().
last_online_version
int Slic3r::MachineObject::last_online_version = -1
Referenced by parse_json().
last_push_time
std::chrono::system_clock::time_point Slic3r::MachineObject::last_push_time
Referenced by is_info_ready(), and parse_json().
last_request_push
std::chrono::system_clock::time_point Slic3r::MachineObject::last_request_push
Referenced by command_request_push_all().
last_request_start
std::chrono::system_clock::time_point Slic3r::MachineObject::last_request_start
Referenced by command_pushing().
last_update_time
std::chrono::system_clock::time_point Slic3r::MachineObject::last_update_time
Referenced by Slic3r::DeviceManager::check_pushing(), is_connected(), parse_json(), reset(), and reset_update_time().
link_ams
std::string Slic3r::MachineObject::link_ams
Referenced by parse_json().
link_th
std::string Slic3r::MachineObject::link_th
Referenced by parse_json().
local_use_ssl
bool Slic3r::MachineObject::local_use_ssl { false }
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok(), Slic3r::GUI::SendToPrinterDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_ok(), and parse_version_func().
m_agent
NetworkAgent* Slic3r::MachineObject::m_agent { nullptr } private
Referenced by MachineObject(), cloud_publish_json(), command_unload_filament(), connect(), disconnect(), get_firmware_info(), is_connected(), local_publish_json(), parse_json(), publish_gcode(), and update_slice_info().
m_ams_id
std::string Slic3r::MachineObject::m_ams_id
Referenced by _parse_tray_now(), get_curr_Ams(), and Slic3r::GUI::StatusPanel::update_ams().
m_firmware_thread_started
bool Slic3r::MachineObject::m_firmware_thread_started { false }
Referenced by get_firmware_info().
m_firmware_valid
bool Slic3r::MachineObject::m_firmware_valid { false }
Referenced by get_firmware_info(), and is_firmware_info_valid().
m_gcode_file
std::string Slic3r::MachineObject::m_gcode_file
Referenced by is_extrusion_cali_finished(), is_in_calibration(), is_in_extrusion_cali(), parse_json(), and parse_state_changed_event().
m_is_online
bool Slic3r::MachineObject::m_is_online
Referenced by is_online(), Slic3r::DeviceManager::on_machine_alive(), Slic3r::DeviceManager::parse_user_print_info(), and set_online_state().
m_lan_mode_connection_state
bool Slic3r::MachineObject::m_lan_mode_connection_state {false}
Referenced by get_lan_mode_connection_state(), and set_lan_mode_connection_state().
m_new_ver_list_exist
bool Slic3r::MachineObject::m_new_ver_list_exist = false
Referenced by parse_json(), reset(), Slic3r::GUI::MachineInfoPanel::update_ams_ext(), and Slic3r::GUI::MachineInfoPanel::update_version_text().
m_push_count
int Slic3r::MachineObject::m_push_count = 0
Referenced by is_connecting(), is_info_ready(), parse_json(), and reset().
m_sequence_id
int Slic3r::MachineObject::m_sequence_id = START_SEQ_ID inline static
Referenced by command_ams_change_filament(), command_ams_control(), command_ams_filament_settings(), command_ams_switch_filament(), command_ams_user_settings(), command_ams_user_settings(), command_clean_print_error(), command_consistency_upgrade_confirm(), command_extrusion_cali_set(), command_get_version(), command_ipcam_record(), command_ipcam_resolution_set(), command_ipcam_timelapse(), command_pushing(), command_request_push_all(), command_set_chamber_light(), command_set_printing_option(), command_set_printing_speed(), command_set_work_light(), command_start_calibration(), command_start_extrusion_cali(), command_task_abort(), command_task_pause(), command_task_resume(), command_unload_filament(), command_upgrade_confirm(), command_upgrade_firmware(), command_upgrade_module(), command_xcam_control(), and publish_gcode().
m_tray_id
std::string Slic3r::MachineObject::m_tray_id
Referenced by _parse_tray_now(), and Slic3r::GUI::StatusPanel::update_ams().
m_tray_now
std::string Slic3r::MachineObject::m_tray_now
Referenced by _parse_tray_now(), can_unload_filament(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), get_curr_tray(), is_filament_move(), and Slic3r::GUI::StatusPanel::update_ams().
m_tray_tar
std::string Slic3r::MachineObject::m_tray_tar
Referenced by is_ams_unload(), parse_json(), and Slic3r::GUI::StatusPanel::update_ams().
mc_left_time
int Slic3r::MachineObject::mc_left_time
Referenced by MachineObject(), parse_json(), and Slic3r::GUI::StatusPanel::update_subtask().
mc_print_error_code
int Slic3r::MachineObject::mc_print_error_code
Referenced by MachineObject(), and parse_json().
mc_print_line_number
int Slic3r::MachineObject::mc_print_line_number
Referenced by MachineObject(), and parse_json().
mc_print_percent
int Slic3r::MachineObject::mc_print_percent
Referenced by MachineObject(), is_extrusion_cali_finished(), is_in_extrusion_cali(), parse_json(), and Slic3r::GUI::ExtrusionCalibration::update().
mc_print_stage
int Slic3r::MachineObject::mc_print_stage
Referenced by MachineObject(), parse_json(), and parse_state_changed_event().
mc_print_sub_stage
int Slic3r::MachineObject::mc_print_sub_stage
Referenced by MachineObject(), and parse_json().
module_vers
std::map<std::string, ModuleVersionInfo> Slic3r::MachineObject::module_vers
Referenced by check_version_valid(), get_ams_version(), get_ota_version(), is_info_ready(), is_support_ams_mapping(), is_support_command_calibration(), is_U0_firmware(), parse_json(), parse_version_func(), Slic3r::GUI::MachineInfoPanel::update_ams_ext(), and Slic3r::GUI::MachineInfoPanel::update_version_text().
monitor_upgrade_printer_img
std::string Slic3r::MachineObject::monitor_upgrade_printer_img
new_ver_list
std::map<std::string, ModuleVersionInfo> Slic3r::MachineObject::new_ver_list
Referenced by parse_json(), Slic3r::GUI::MachineInfoPanel::update_ams_ext(), and Slic3r::GUI::MachineInfoPanel::update_version_text().
nozzle
float Slic3r::MachineObject::nozzle { 0.0f }
nozzle_diameter
float Slic3r::MachineObject::nozzle_diameter { 0.0f }
Referenced by parse_json(), and reset().
nozzle_temp
float Slic3r::MachineObject::nozzle_temp
Referenced by MachineObject(), command_extrusion_cali_set(), command_start_extrusion_cali(), Slic3r::GUI::StatusPanel::on_axis_ctrl_e_down_10(), Slic3r::GUI::StatusPanel::on_axis_ctrl_e_up_10(), parse_json(), and Slic3r::GUI::StatusPanel::update_temp_ctrl().
nozzle_temp_target
float Slic3r::MachineObject::nozzle_temp_target
Referenced by MachineObject(), parse_json(), and Slic3r::GUI::StatusPanel::update_temp_ctrl().
obj_subtask_id
std::string Slic3r::MachineObject::obj_subtask_id
Referenced by is_sdcard_printing(), and parse_json().
online_ahb
bool Slic3r::MachineObject::online_ahb
Referenced by parse_json(), and Slic3r::GUI::MachineInfoPanel::update_ams_ext().
online_rfid
bool Slic3r::MachineObject::online_rfid
Referenced by parse_json().
online_version
int Slic3r::MachineObject::online_version = -1
Referenced by parse_json().
ota_new_version_number
std::string Slic3r::MachineObject::ota_new_version_number
Referenced by Slic3r::GUI::MachineInfoPanel::on_show_release_note(), parse_json(), and Slic3r::GUI::MachineInfoPanel::update_version_text().
parse_msg_count
int Slic3r::MachineObject::parse_msg_count = 0
Referenced by parse_json().
plate_index
int Slic3r::MachineObject::plate_index { -1 }
Referenced by parse_json(), and update_slice_info().
print_error
int Slic3r::MachineObject::print_error
Referenced by MachineObject(), command_clean_print_error(), Slic3r::GUI::StatusPanel::on_print_error_clean(), parse_json(), Slic3r::GUI::StatusPanel::show_error_message(), and Slic3r::GUI::StatusPanel::update_error_message().
print_json
json_diff Slic3r::MachineObject::print_json
Referenced by parse_json().
print_status
std::string Slic3r::MachineObject::print_status
Referenced by Slic3r::GUI::MachineListModel::add_machine(), can_abort(), can_pause(), can_print(), can_resume(), is_calibration_running(), is_in_extrusion_cali(), is_in_prepare(), is_in_printing(), is_printing_finished(), is_system_printing(), Slic3r::GUI::StatusPanel::on_thumbnail_enter(), parse_json(), reset(), set_print_state(), and Slic3r::GUI::StatusPanel::update_subtask().
print_type
std::string Slic3r::MachineObject::print_type
Referenced by is_in_extrusion_cali(), and parse_json().
printer_thumbnail_img
std::string Slic3r::MachineObject::printer_thumbnail_img
printer_type
std::string Slic3r::MachineObject::printer_type
Referenced by command_ams_switch(), command_unload_filament(), get_bed_temperature_limit(), get_ftp_folder(), get_preset_printer_model_name(), get_preset_printer_thumbnail_img(), get_printer_thumbnail_img_str(), get_printer_type_display_str(), get_resolution_supported(), is_function_supported(), Slic3r::GUI::SelectMachineDialog::is_same_printer_model(), is_support_ams_mapping(), is_support_command_calibration(), Slic3r::DeviceManager::on_machine_alive(), Slic3r::GUI::SelectMachineDialog::on_ok_btn(), parse_json(), Slic3r::DeviceManager::parse_user_print_info(), parse_version_func(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::InputIpAddressDialog::set_machine_obj(), and Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments().
printing_speed_lvl
PrintingSpeedLevel Slic3r::MachineObject::printing_speed_lvl
Referenced by MachineObject(), Slic3r::GUI::StatusPanel::on_switch_speed(), parse_json(), and Slic3r::GUI::StatusPanel::update_misc_ctrl().
printing_speed_mag
int Slic3r::MachineObject::printing_speed_mag = 100
Referenced by parse_json(), reset(), and Slic3r::GUI::StatusPanel::update_misc_ctrl().
product_name
std::string Slic3r::MachineObject::product_name
Referenced by Slic3r::DeviceManager::parse_user_print_info().
profile_id_
std::string Slic3r::MachineObject::profile_id_
Referenced by is_sdcard_printing(), Slic3r::GUI::StatusPanel::is_task_changed(), and update_slice_info().
project_id_
std::string Slic3r::MachineObject::project_id_
Referenced by is_sdcard_printing(), and update_slice_info().
queue_number
int Slic3r::MachineObject::queue_number = 0
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_subtask().
sdcard_state
MachineObject::SdcardState Slic3r::MachineObject::sdcard_state { NO_SDCARD }
Referenced by get_sdcard_state(), has_sdcard(), Slic3r::GUI::CameraPopup::on_switch_recording(), parse_json(), and parse_status().
slice_info
BBLSliceInfo* Slic3r::MachineObject::slice_info {nullptr}
Referenced by ~MachineObject(), Slic3r::GUI::StatusPanel::on_thumbnail_enter(), Slic3r::GUI::StatusPanel::refresh_thumbnail_webrequest(), Slic3r::GUI::StatusPanel::update_basic_print_data(), Slic3r::GUI::StatusPanel::update_cloud_subtask(), and update_slice_info().
stage_curr
int Slic3r::MachineObject::stage_curr = 0
Referenced by get_curr_stage(), get_curr_stage_idx(), is_in_calibration(), and parse_json().
stage_list_info
std::vector<int> Slic3r::MachineObject::stage_list_info
Referenced by get_curr_stage(), get_curr_stage_idx(), Slic3r::GUI::CalibrationDialog::is_stage_list_info_changed(), Slic3r::GUI::StatusPanel::is_stage_list_info_changed(), parse_json(), and Slic3r::GUI::CalibrationDialog::update_cali().
subtask_
BBLSubTask* Slic3r::MachineObject::subtask_
Referenced by ~MachineObject(), get_subtask(), Slic3r::GUI::StatusPanel::is_task_changed(), Slic3r::GUI::StatusPanel::on_thumbnail_enter(), reset(), Slic3r::GUI::StatusPanel::update_cloud_subtask(), and Slic3r::GUI::StatusPanel::update_subtask().
subtask_id_
std::string Slic3r::MachineObject::subtask_id_
Referenced by Slic3r::GUI::StatusPanel::show_error_message(), and update_slice_info().
subtask_name
std::string Slic3r::MachineObject::subtask_name
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_subtask().
task_id_
std::string Slic3r::MachineObject::task_id_
Referenced by Slic3r::GUI::StatusPanel::is_task_changed(), and parse_json().
total_layers
int Slic3r::MachineObject::total_layers = 0
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_subtask().
tray_exist_bits
long Slic3r::MachineObject::tray_exist_bits = 0
Referenced by MachineObject(), parse_json(), and Slic3r::GUI::StatusPanel::update_ams().
tray_is_bbl_bits
long Slic3r::MachineObject::tray_is_bbl_bits = 0
Referenced by MachineObject(), parse_json(), and Slic3r::GUI::StatusPanel::update_ams().
tray_read_done_bits
long Slic3r::MachineObject::tray_read_done_bits = 0
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_ams().
tray_reading_bits
long Slic3r::MachineObject::tray_reading_bits = 0
Referenced by parse_json(), and Slic3r::GUI::StatusPanel::update_ams().
upgrade_consistency_request
bool Slic3r::MachineObject::upgrade_consistency_request { false }
Referenced by MachineObject(), parse_json(), Slic3r::GUI::UpgradePanel::update(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
upgrade_display_hold_count
int Slic3r::MachineObject::upgrade_display_hold_count = 0
Referenced by Slic3r::GUI::MachineInfoPanel::confirm_upgrade(), parse_json(), and Slic3r::GUI::UpgradePanel::update().
upgrade_display_state
int Slic3r::MachineObject::upgrade_display_state = 0
Referenced by Slic3r::GUI::MachineInfoPanel::confirm_upgrade(), is_in_upgrading(), is_upgrading_avalable(), parse_json(), Slic3r::GUI::MachineInfoPanel::update(), Slic3r::GUI::UpgradePanel::update(), Slic3r::GUI::MachineInfoPanel::update_ams_ext(), and Slic3r::GUI::MachineInfoPanel::update_version_text().
upgrade_err_code
int Slic3r::MachineObject::upgrade_err_code = 0
Referenced by parse_json(), and Slic3r::GUI::MachineInfoPanel::update().
upgrade_force_upgrade
bool Slic3r::MachineObject::upgrade_force_upgrade { false }
Referenced by MachineObject(), parse_json(), Slic3r::GUI::UpgradePanel::update(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
upgrade_message
std::string Slic3r::MachineObject::upgrade_message
Referenced by parse_json().
upgrade_module
std::string Slic3r::MachineObject::upgrade_module
Referenced by parse_json().
upgrade_new_version
bool Slic3r::MachineObject::upgrade_new_version { false }
Referenced by MachineObject(), parse_json(), Slic3r::GUI::MachineInfoPanel::update_ams_ext(), and Slic3r::GUI::MachineInfoPanel::update_version_text().
upgrade_progress
std::string Slic3r::MachineObject::upgrade_progress
Referenced by get_upgrade_percent(), and parse_json().
upgrade_status
std::string Slic3r::MachineObject::upgrade_status
Referenced by parse_json(), and Slic3r::GUI::MachineInfoPanel::update().
user_access_code
std::string Slic3r::MachineObject::user_access_code private
Referenced by set_user_access_code().
vt_tray
AmsTray Slic3r::MachineObject::vt_tray
Referenced by get_curr_tray(), Slic3r::GUI::StatusPanel::on_ams_load_curr(), Slic3r::GUI::StatusPanel::on_ext_spool_edit(), Slic3r::GUI::StatusPanel::on_filament_edit(), parse_json(), reset(), and Slic3r::GUI::StatusPanel::update_ams().
wifi_signal
std::string Slic3r::MachineObject::wifi_signal
Referenced by MachineObject(), Slic3r::DeviceManager::on_machine_alive(), parse_json(), publish_gcode(), and Slic3r::GUI::MonitorPanel::update_status().
work_light
LIGHT_EFFECT Slic3r::MachineObject::work_light
Referenced by parse_json().
xcam_ai_monitoring
bool Slic3r::MachineObject::xcam_ai_monitoring { false }
Referenced by command_xcam_control_ai_monitoring(), parse_json(), and Slic3r::GUI::PrintOptionsDialog::update_options().
xcam_ai_monitoring_hold_count
int Slic3r::MachineObject::xcam_ai_monitoring_hold_count = 0
Referenced by command_xcam_control_ai_monitoring(), and parse_json().
xcam_ai_monitoring_sensitivity
std::string Slic3r::MachineObject::xcam_ai_monitoring_sensitivity
Referenced by command_xcam_control_ai_monitoring(), parse_json(), and Slic3r::GUI::PrintOptionsDialog::update_options().
xcam_auto_recovery_hold_count
int Slic3r::MachineObject::xcam_auto_recovery_hold_count = 0
Referenced by command_xcam_control_auto_recovery_step_loss(), and parse_status().
xcam_auto_recovery_step_loss
bool Slic3r::MachineObject::xcam_auto_recovery_step_loss { false }
Referenced by _parse_print_option_ack(), command_xcam_control_auto_recovery_step_loss(), parse_json(), parse_status(), and Slic3r::GUI::PrintOptionsDialog::update_options().
xcam_buildplate_marker_detector
bool Slic3r::MachineObject::xcam_buildplate_marker_detector { false }
Referenced by command_xcam_control_buildplate_marker_detector(), parse_json(), and Slic3r::GUI::PrintOptionsDialog::update_options().
xcam_buildplate_marker_hold_count
int Slic3r::MachineObject::xcam_buildplate_marker_hold_count = 0
Referenced by command_xcam_control_buildplate_marker_detector(), and parse_json().
xcam_first_layer_hold_count
int Slic3r::MachineObject::xcam_first_layer_hold_count = 0
Referenced by command_xcam_control_first_layer_inspector(), and parse_json().
xcam_first_layer_inspector
bool Slic3r::MachineObject::xcam_first_layer_inspector { false }
Referenced by command_xcam_control_first_layer_inspector(), parse_json(), and Slic3r::GUI::PrintOptionsDialog::update_options().
xcam_support_recovery_step_loss
bool Slic3r::MachineObject::xcam_support_recovery_step_loss { true }
Referenced by is_function_supported(), and parse_version_func().
The documentation for this class was generated from the following files:
src/slic3r/GUI/DeviceManager.hpp
src/slic3r/GUI/DeviceManager.cpp