OrcaSlicer: Slic3r::GUI::ParamsPanel Class Reference
Slic3r::GUI::ParamsPanel Class Reference
Class ParamsPanel.
#include <src/slic3r/GUI/ParamsPanel.hpp>
Classes
struct Highlighter
Public Member Functions
ParamsPanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(1800, 1080), long style=wxTAB_TRAVERSAL, const wxString &type=wxEmptyString)
~ParamsPanel ()
void rebuild_panels ()
void create_layout ()
void clear_page ()
void OnActivate ()
void set_active_tab (wxPanel *tab)
bool is_active_and_shown_tab (wxPanel *tab)
void update_mode ()
void msw_rescale ()
void switch_to_global ()
void switch_to_object (bool with_tips=false)
void notify_object_config_changed ()
void switch_to_object_if_has_object_configs ()
StaticBox * get_top_panel ()
wxPanel * filament_panel ()
wxScrolledWindow * get_paged_view ()
wxPanel * get_current_tab ()
Protected Member Functions
void OnToggled (wxCommandEvent &event)
Protected Attributes
wxBoxSizer * m_top_sizer { nullptr }
wxBoxSizer * m_left_sizer { nullptr }
wxBoxSizer * m_mode_sizer { nullptr }
StaticBox * m_top_panel { nullptr }
ScalableButton * m_process_icon { nullptr }
wxStaticText * m_title_label { nullptr }
SwitchButton * m_mode_region { nullptr }
ScalableButton * m_tips_arrow {nullptr}
bool m_tips_arror_blink {false}
wxStaticText * m_title_view { nullptr }
SwitchButton * m_mode_view { nullptr }
wxStaticLine * m_staticline_print { nullptr }
wxPanel * m_tab_print { nullptr }
wxPanel * m_tab_print_object { nullptr }
wxStaticLine * m_staticline_print_object { nullptr }
wxPanel * m_tab_print_part { nullptr }
wxPanel * m_tab_print_layer { nullptr }
wxStaticLine * m_staticline_print_part { nullptr }
wxStaticLine * m_staticline_filament { nullptr }
wxPanel * m_tab_filament { nullptr }
wxStaticLine * m_staticline_printer { nullptr }
wxPanel * m_tab_printer { nullptr }
wxBoxSizer * m_button_sizer { nullptr }
wxWindow * m_export_to_file { nullptr }
wxWindow * m_import_from_file { nullptr }
wxScrolledWindow * m_page_view { nullptr }
wxBoxSizer * m_page_sizer { nullptr }
ScalableButton * m_setting_btn { nullptr }
ScalableButton * m_search_btn { nullptr }
ScalableButton * m_compare_btn { nullptr }
wxBitmap m_toggle_on_icon
wxBitmap m_toggle_off_icon
wxPanel * m_current_tab { nullptr }
bool m_has_object_config { false }
struct Slic3r::GUI::ParamsPanel::Highlighter m_highlighter
Private Member Functions
void free_sizers ()
void delete_subwindows ()
void refresh_tabs ()
Detailed Description
Class ParamsPanel.
Constructor & Destructor Documentation
ParamsPanel()
Slic3r::GUI::ParamsPanel::ParamsPanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(1800,1080), long style = wxTAB_TRAVERSAL, const wxString & type = wxEmptyString)
    : wxPanel( parent, id, pos, size, style, name )
{
    // BBS: new layout
    SetBackgroundColour(*wxWHITE);
#if __WXOSX__
    m_top_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_top_sizer->SetSizeHints(this);
    this->SetSizer(m_top_sizer);
    // Create additional panel to Fit() it from OnActivate()
    // It's needed for tooltip showing on OSX
    m_tmp_panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBK_LEFT | wxTAB_TRAVERSAL);
    auto  sizer = new wxBoxSizer(wxHORIZONTAL);
    m_tmp_panel->SetSizer(sizer);
    m_tmp_panel->Layout();
#else
    ParamsPanel*panel = this;
    m_top_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_top_sizer->SetSizeHints(panel);
    panel->SetSizer(m_top_sizer);
#endif //__WXOSX__
    if (dynamic_cast<Notebook*>(parent)) {
        // BBS: new layout
        m_top_panel = new StaticBox(this, wxID_ANY, wxDefaultPosition);
        m_top_panel->SetBackgroundColor(0xF8F8F8);
        m_top_panel->SetBackgroundColor2(0xF1F1F1);
        m_process_icon = new ScalableButton(m_top_panel, wxID_ANY, "process");
        m_title_label = new Label(m_top_panel, _L("Process"));
        //int width, height;
        // BBS: new layout
        m_mode_region = new SwitchButton(m_top_panel);
        m_mode_region->SetMaxSize({em_unit(this) * 12, -1});
        m_mode_region->SetLabels(_L("Global"), _L("Objects"));
        //m_mode_region->GetSize(&width, &height);
        m_tips_arrow = new ScalableButton(m_top_panel, wxID_ANY, "tips_arrow");
        m_tips_arrow->Hide();
        m_title_view = new Label(m_top_panel, _L("Advance"));
        m_mode_view = new SwitchButton(m_top_panel, wxID_ABOUT);
        // BBS: new layout
        //m_search_btn = new ScalableButton(m_top_panel, wxID_ANY, "search", wxEmptyString, wxDefaultSize, wxDefaultPosition, wxBU_EXACTFIT | wxNO_BORDER, true);
        //m_search_btn->SetToolTip(format_wxstr(_L("Search in settings [%1%]"), "Ctrl+F"));
        //m_search_btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent &) { wxGetApp().plater()->search(false); });
        m_compare_btn = new ScalableButton(m_top_panel, wxID_ANY, "compare", wxEmptyString, wxDefaultSize, wxDefaultPosition, wxBU_EXACTFIT | wxNO_BORDER, true);
        m_compare_btn->SetToolTip(_L("Compare presets"));
        m_compare_btn->Bind(wxEVT_BUTTON, ([this](wxCommandEvent e) { wxGetApp().mainframe->diff_dialog.show(); }));
        m_setting_btn = new ScalableButton(m_top_panel, wxID_ANY, "table", wxEmptyString, wxDefaultSize, wxDefaultPosition, wxBU_EXACTFIT | wxNO_BORDER, true);
        m_setting_btn->SetToolTip(_L("View all object's settings"));
        m_setting_btn->Bind(wxEVT_BUTTON, [this](wxCommandEvent &) { wxGetApp().plater()->PopupObjectTable(-1, -1, {0, 0}); });
        m_highlighter.set_timer_owner(this, 0);
        this->Bind(wxEVT_TIMER, [this](wxTimerEvent &)
        {
            m_highlighter.blink();
        });
    }
    //m_export_to_file = new Button( this, wxT("Export To File"), "");
    //m_import_from_file = new Button( this, wxT("Import From File") );
    // Initialize the page.
#if __WXOSX__
    auto page_parent = m_tmp_panel;
#else
    auto page_parent = this;
#endif
    // BBS: fix scroll to tip view
    class PageScrolledWindow : public wxScrolledWindow
    {
    public:
        PageScrolledWindow(wxWindow *parent)
            : wxScrolledWindow(parent,
                               wxID_ANY,
                               wxDefaultPosition,
                               wxDefaultSize,
                               wxVSCROLL) // hide hori-bar will cause hidden field mis-position
        {
            // ShowScrollBar(GetHandle(), SB_BOTH, FALSE);
            Bind(wxEVT_SCROLL_CHANGED, [this](auto &e) {
                wxWindow *child = dynamic_cast<wxWindow *>(e.GetEventObject());
                if (child != this)
                    EnsureVisible(child);
            });
        }
        virtual bool ShouldScrollToChildOnFocus(wxWindow *child)
        {
            EnsureVisible(child);
            return false;
        }
        void EnsureVisible(wxWindow* win)
        {
            const wxRect viewRect(m_targetWindow->GetClientRect());
            const wxRect winRect(m_targetWindow->ScreenToClient(win->GetScreenPosition()), win->GetSize());
            if (viewRect.Contains(winRect)) {
                return;
            }
            if (winRect.GetWidth() > viewRect.GetWidth() || winRect.GetHeight() > viewRect.GetHeight()) {
                return;
            }
            int stepx, stepy;
            GetScrollPixelsPerUnit(&stepx, &stepy);
            int startx, starty;
            GetViewStart(&startx, &starty);
            // first in vertical direction:
            if (stepy > 0) {
                int diff = 0;
                if (winRect.GetTop() < 0) {
                    diff = winRect.GetTop();
                } else if (winRect.GetBottom() > viewRect.GetHeight()) {
                    diff = winRect.GetBottom() - viewRect.GetHeight() + 1;
                    // round up to next scroll step if we can't get exact position,
                    // so that the window is fully visible:
                    diff += stepy - 1;
                }
                starty = (starty * stepy + diff) / stepy;
            }
            // then horizontal:
            if (stepx > 0) {
                int diff = 0;
                if (winRect.GetLeft() < 0) {
                    diff = winRect.GetLeft();
                } else if (winRect.GetRight() > viewRect.GetWidth()) {
                    diff = winRect.GetRight() - viewRect.GetWidth() + 1;
                    // round up to next scroll step if we can't get exact position,
                    // so that the window is fully visible:
                    diff += stepx - 1;
                }
                startx = (startx * stepx + diff) / stepx;
            }
            Scroll(startx, starty);
        }
    };
    m_page_view = new PageScrolledWindow(page_parent);
    m_page_view->SetBackgroundColour(*wxWHITE);
    m_page_sizer = new wxBoxSizer(wxVERTICAL);
    m_page_view->SetSizer(m_page_sizer);
    m_page_view->SetScrollbars(1, 20, 1, 2);
    //m_page_view->SetScrollRate( 5, 5 );
    if (m_mode_region)
        m_mode_region->Bind(wxEVT_TOGGLEBUTTON, &ParamsPanel::OnToggled, this);
    if (m_mode_view)
        m_mode_view->Bind(wxEVT_TOGGLEBUTTON, &ParamsPanel::OnToggled, this);
    Bind(wxEVT_TOGGLEBUTTON, &ParamsPanel::OnToggled, this); // For Tab's mode switch
    //Bind(wxEVT_BUTTON, [this](wxCommandEvent &) { wxGetApp().plater()->search(false); }, wxID_FIND);
    //m_export_to_file->Bind(wxEVT_BUTTON, [this](wxCommandEvent &) { wxGetApp().mainframe->export_config(); });
    //m_import_from_file->Bind(wxEVT_BUTTON, [this](wxCommandEvent &) { wxGetApp().mainframe->load_config_file(); });
}
References _L, Slic3r::GUI::ParamsPanel::Highlighter::blink(), Slic3r::diff(), em_unit(), m_compare_btn, m_highlighter, m_mode_region, m_mode_view, m_page_sizer, m_page_view, m_process_icon, m_setting_btn, m_tips_arrow, m_title_label, m_title_view, m_top_panel, m_top_sizer, OnToggled(), Slic3r::GUI::ParamsPanel::Highlighter::set_timer_owner(), StaticBox::SetBackgroundColor(), StaticBox::SetBackgroundColor2(), SwitchButton::SetLabels(), and wxEVT_BUTTON.
~ParamsPanel()
Slic3r::GUI::ParamsPanel::~ParamsPanel ()
{
#if 0
    free_sizers();
    delete m_top_sizer;
    delete_subwindows();
#endif
    // BBS: fix double destruct of OG_CustomCtrl
    Tab* cur_tab = dynamic_cast<Tab*> (m_current_tab);
    if (cur_tab)
        cur_tab->clear_pages();
}
References Slic3r::GUI::Tab::clear_pages(), delete_subwindows(), free_sizers(), m_current_tab, and m_top_sizer.
Member Function Documentation
clear_page()
void Slic3r::GUI::ParamsPanel::clear_page ()
{
    if (m_page_sizer)
        m_page_sizer->Clear(true);
}
References m_page_sizer.
Referenced by Slic3r::GUI::Tab::clear_pages(), and Slic3r::GUI::Tab::update_current_page_in_background().
create_layout()
void Slic3r::GUI::ParamsPanel::create_layout ()
{
#ifdef __WINDOWS__
    this->SetDoubleBuffered(true);
    m_page_view->SetDoubleBuffered(true);
#endif //__WINDOWS__
    m_left_sizer = new wxBoxSizer( wxVERTICAL );
    // BBS: new layout
    m_left_sizer->SetMinSize( wxSize(40 * em_unit(this), -1 ) );
    if (m_top_panel) {
        m_mode_sizer = new wxBoxSizer( wxHORIZONTAL );
        m_mode_sizer->AddSpacer(FromDIP(11));
        m_mode_sizer->Add(m_process_icon, 0, wxALIGN_CENTER);
        m_mode_sizer->AddSpacer(FromDIP(11));
        m_mode_sizer->Add( m_title_label, 0, wxALIGN_CENTER );
        m_mode_sizer->AddStretchSpacer(2);
        m_mode_sizer->Add(m_mode_region, 0, wxALIGN_CENTER);
        m_mode_sizer->AddStretchSpacer(1);
        m_mode_sizer->Add(m_tips_arrow, 0, wxALIGN_CENTER);
        m_mode_sizer->AddStretchSpacer(8);
        m_mode_sizer->Add( m_title_view, 0, wxALIGN_CENTER );
        m_mode_sizer->AddSpacer(FromDIP(2));
        m_mode_sizer->Add(m_mode_view, 0, wxALIGN_CENTER);
        m_mode_sizer->AddStretchSpacer(2);
        m_mode_sizer->Add(m_setting_btn, 0, wxALIGN_CENTER);
        m_mode_sizer->AddSpacer(FromDIP(2));
        m_mode_sizer->Add(m_compare_btn, 0, wxALIGN_CENTER);
        m_mode_sizer->AddSpacer(FromDIP(8));
        //m_mode_sizer->Add( m_search_btn, 0, wxALIGN_CENTER );
        //m_mode_sizer->AddSpacer(16);
        m_mode_sizer->SetMinSize(-1, FromDIP(30));
        m_top_panel->SetSizer(m_mode_sizer);
        //m_left_sizer->Add( m_top_panel, 0, wxEXPAND );
    }
    if (m_tab_print) {
        //m_print_sizer = new wxBoxSizer( wxHORIZONTAL );
        //m_print_sizer->Add( m_tab_print, 1, wxEXPAND | wxALL, 5 );
        //m_left_sizer->Add( m_print_sizer, 1, wxEXPAND, 5 );
        m_left_sizer->Add( m_tab_print, 0, wxEXPAND );
    }
    if (m_tab_print_object) {
        if (m_staticline_print_object)
            m_left_sizer->Add( m_staticline_print_object, 0, wxEXPAND );
        m_left_sizer->Add( m_tab_print_object, 0, wxEXPAND );
    }
    if (m_tab_print_part) {
        if (m_staticline_print_part)
            m_left_sizer->Add( m_staticline_print_part, 0, wxEXPAND );
        m_left_sizer->Add( m_tab_print_part, 0, wxEXPAND );
    }
    if (m_tab_print_layer) {
        m_left_sizer->Add(m_tab_print_layer, 0, wxEXPAND);
    }
    if (m_tab_filament) {
        if (m_staticline_filament)
            m_left_sizer->Add(m_staticline_filament, 0, wxEXPAND);
        //m_filament_sizer = new wxBoxSizer( wxVERTICAL );
        //m_filament_sizer->Add( m_tab_filament, 1, wxEXPAND | wxALL, 5 );
       // m_left_sizer->Add( m_filament_sizer, 1, wxEXPAND, 5 );
        m_left_sizer->Add( m_tab_filament, 0, wxEXPAND );
    }
    if (m_tab_printer) {
        if (m_staticline_printer)
            m_left_sizer->Add( m_staticline_printer, 0, wxEXPAND );
        //m_printer_sizer = new wxBoxSizer( wxVERTICAL );
        //m_printer_sizer->Add( m_tab_printer, 1, wxEXPAND | wxALL, 5 );
        m_left_sizer->Add( m_tab_printer, 0, wxEXPAND );
    }
    //m_left_sizer->Add( m_printer_sizer, 1, wxEXPAND, 1 );
    //m_button_sizer = new wxBoxSizer( wxHORIZONTAL );
    //m_button_sizer->Add( m_export_to_file, 0, wxALL, 5 );
    //m_button_sizer->Add( m_import_from_file, 0, wxALL, 5 );
    //m_left_sizer->Add( m_button_sizer, 0, wxALIGN_CENTER, 5 );
    m_top_sizer->Add(m_left_sizer, 1, wxEXPAND);
    //m_right_sizer = new wxBoxSizer( wxVERTICAL );
    //m_right_sizer->Add( m_page_view, 1, wxEXPAND | wxALL, 5 );
    //m_top_sizer->Add( m_right_sizer, 1, wxEXPAND, 5 );
    // BBS: new layout
    m_left_sizer->AddSpacer(6 * em_unit(this) / 10);
#if __WXOSX__
    m_left_sizer->Add(m_tmp_panel, 1, wxEXPAND | wxALL, 0);
    m_tmp_panel->GetSizer()->Add( m_page_view, 1, wxEXPAND );
#else
    m_left_sizer->Add( m_page_view, 1, wxEXPAND );
#endif
    //this->SetSizer( m_top_sizer );
    this->Layout();
}
References em_unit(), m_compare_btn, m_left_sizer, m_mode_region, m_mode_sizer, m_mode_view, m_page_view, m_process_icon, m_setting_btn, m_staticline_filament, m_staticline_print_object, m_staticline_print_part, m_staticline_printer, m_tab_filament, m_tab_print, m_tab_print_layer, m_tab_print_object, m_tab_print_part, m_tab_printer, m_tips_arrow, m_title_label, m_title_view, m_top_panel, and m_top_sizer.
Referenced by rebuild_panels().
delete_subwindows()
void Slic3r::GUI::ParamsPanel::delete_subwindows () private
{
    if (m_title_label)
    {
        delete m_title_label;
        m_title_label = nullptr;
    }
    if (m_mode_region)
    {
        delete m_mode_region;
        m_mode_region = nullptr;
    }
    if (m_mode_view)
    {
        delete m_mode_view;
        m_mode_view = nullptr;
    }
    if (m_title_view)
    {
        delete m_title_view;
        m_title_view = nullptr;
    }
    if (m_search_btn)
    {
        delete m_search_btn;
        m_search_btn = nullptr;
    }
    if (m_staticline_print)
    {
        delete m_staticline_print;
        m_staticline_print = nullptr;
    }
    if (m_staticline_print_part)
    {
        delete m_staticline_print_part;
        m_staticline_print_part = nullptr;
    }
    if (m_staticline_print_object)
    {
        delete m_staticline_print_object;
        m_staticline_print_object = nullptr;
    }
    if (m_staticline_filament)
    {
        delete m_staticline_filament;
        m_staticline_filament = nullptr;
    }
    if (m_staticline_printer)
    {
        delete m_staticline_printer;
        m_staticline_printer = nullptr;
    }
    if (m_export_to_file)
    {
        delete m_export_to_file;
        m_export_to_file = nullptr;
    }
    if (m_import_from_file)
    {
        delete m_import_from_file;
        m_import_from_file = nullptr;
    }
    if (m_page_view)
    {
        delete m_page_view;
        m_page_view = nullptr;
    }
}
References m_export_to_file, m_import_from_file, m_mode_region, m_mode_view, m_page_view, m_search_btn, m_staticline_filament, m_staticline_print, m_staticline_print_object, m_staticline_print_part, m_staticline_printer, m_title_label, and m_title_view.
Referenced by ~ParamsPanel().
filament_panel()
wxPanel * Slic3r::GUI::ParamsPanel::filament_panel () inline
{ return m_tab_filament; }
References m_tab_filament.
free_sizers()
void Slic3r::GUI::ParamsPanel::free_sizers () private
{
    if (m_top_sizer)
    {
        m_top_sizer->Clear(false);
        //m_top_sizer = nullptr;
    }
    m_left_sizer = nullptr;
    //m_right_sizer = nullptr;
    m_mode_sizer = nullptr;
    //m_print_sizer = nullptr;
    //m_filament_sizer = nullptr;
    //m_printer_sizer = nullptr;
    m_button_sizer = nullptr;
}
References m_button_sizer, m_left_sizer, m_mode_sizer, and m_top_sizer.
Referenced by ~ParamsPanel(), and rebuild_panels().
get_current_tab()
wxPanel * Slic3r::GUI::ParamsPanel::get_current_tab () inline
{ return m_current_tab; }
References m_current_tab.
Referenced by Slic3r::GUI::ParamsDialog::ParamsDialog(), and Slic3r::GUI::Tab::tree_sel_change_delayed().
get_paged_view()
wxScrolledWindow * Slic3r::GUI::ParamsPanel::get_paged_view () inline
{ return m_page_view;}
References m_page_view.
get_top_panel()
StaticBox * Slic3r::GUI::ParamsPanel::get_top_panel () inline
{ return m_top_panel; }
References m_top_panel.
is_active_and_shown_tab()
bool Slic3r::GUI::ParamsPanel::is_active_and_shown_tab (wxPanel * tab)
{
    if (m_current_tab == tab)
        return true;
    else
        return false;
}
References m_current_tab.
Referenced by Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::update_current_page_in_background().
msw_rescale()
void Slic3r::GUI::ParamsPanel::msw_rescale ()
{
    if (m_process_icon) m_process_icon->msw_rescale();
    if (m_setting_btn) m_setting_btn->msw_rescale();
    if (m_search_btn) m_search_btn->msw_rescale();
    if (m_compare_btn) m_compare_btn->msw_rescale();
    if (m_tips_arrow) m_tips_arrow->msw_rescale();
    m_left_sizer->SetMinSize(wxSize(40 * em_unit(this), -1));
    if (m_mode_sizer)
        m_mode_sizer->SetMinSize(-1, 3 * em_unit(this));
    if (m_mode_region)
        ((SwitchButton* )m_mode_region)->Rescale();
    if (m_mode_view)
        ((SwitchButton* )m_mode_view)->Rescale();
    for (auto tab : {m_tab_print, m_tab_print_object, m_tab_print_part, m_tab_print_layer, m_tab_filament, m_tab_printer}) {
        if (tab) dynamic_cast<Tab*>(tab)->msw_rescale();
    }
    //((Button*)m_export_to_file)->Rescale();
    //((Button*)m_import_from_file)->Rescale();
}
References em_unit(), m_compare_btn, m_left_sizer, m_mode_region, m_mode_sizer, m_mode_view, m_process_icon, m_search_btn, m_setting_btn, m_tab_filament, m_tab_print, m_tab_print_layer, m_tab_print_object, m_tab_print_part, m_tab_printer, m_tips_arrow, msw_rescale(), and ScalableButton::msw_rescale().
Referenced by msw_rescale(), and Slic3r::GUI::ParamsDialog::on_dpi_changed().
notify_object_config_changed()
void Slic3r::GUI::ParamsPanel::notify_object_config_changed ()
{
    auto & model = wxGetApp().model();
    bool has_config = false;
    for (auto obj : model.objects) {
        if (!obj->config.empty()) {
            SettingsFactory::Bundle cat_options = SettingsFactory::get_bundle(&obj->config.get(), true);
            if (cat_options.size() > 0) {
                has_config = true;
                break;
            }
        }
        for (auto volume : obj->volumes) {
            if (!volume->config.empty()) {
                SettingsFactory::Bundle cat_options = SettingsFactory::get_bundle(&volume->config.get(), true);
                if (cat_options.size() > 0) {
                    has_config = true;
                    break;
                }
            }
        }
        if (has_config) break;
    }
    if (has_config == m_has_object_config) return;
    m_has_object_config = has_config;
    if (has_config)
        m_mode_region->SetTextColor2(StateColor(std::pair{0xfffffe, (int) StateColor::Checked}, std::pair{wxGetApp().get_label_clr_modified(), 0}));
    else
        m_mode_region->SetTextColor2(StateColor());
    m_mode_region->Rescale();
}
References StateColor::Checked, Slic3r::GUI::SettingsFactory::get_bundle(), int, m_has_object_config, m_mode_region, SwitchButton::Rescale(), and SwitchButton::SetTextColor2().
OnActivate()
void Slic3r::GUI::ParamsPanel::OnActivate ()
{
    if (m_current_tab == NULL)
    {
        //the first time
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": first time opened, set current tab to print");
        // BBS: open/close tab
        //m_current_tab = m_tab_print;
        set_active_tab(m_tab_print ? m_tab_print : m_tab_filament);
    }
    Tab* cur_tab = dynamic_cast<Tab *> (m_current_tab);
    if (cur_tab)
        cur_tab->OnActivate();
}
References m_current_tab, m_tab_filament, m_tab_print, NULL, Slic3r::GUI::Tab::OnActivate(), and set_active_tab().
OnToggled()
void Slic3r::GUI::ParamsPanel::OnToggled (wxCommandEvent & event) protected
{
    if (m_mode_region && m_mode_region->GetId() == event.GetId()) {
        wxWindowUpdateLocker locker(GetParent());
        set_active_tab(nullptr);
        event.Skip();
        return;
    }
    if (wxID_ABOUT != event.GetId()) {
        return;
    }
    // this is from tab's mode switch
    bool value = dynamic_cast<SwitchButton*>(event.GetEventObject())->GetValue();
    int mode_id;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": Advanced mode toogle to %1%") % value;
    if (value)
    {
        //m_mode_region->SetBitmap(m_toggle_on_icon);
        mode_id = comAdvanced;
    }
    else
    {
        //m_mode_region->SetBitmap(m_toggle_off_icon);
        mode_id = comSimple;
    }
    Slic3r::GUI::wxGetApp().save_mode(mode_id);
}
References Slic3r::comAdvanced, Slic3r::comSimple, m_mode_region, and set_active_tab().
Referenced by ParamsPanel().
rebuild_panels()
void Slic3r::GUI::ParamsPanel::rebuild_panels ()
{
    refresh_tabs();
    free_sizers();
    create_layout();
}
References create_layout(), free_sizers(), and refresh_tabs().
refresh_tabs()
void Slic3r::GUI::ParamsPanel::refresh_tabs () private
{
    auto& tabs_list = wxGetApp().tabs_list;
    auto print_tech = wxGetApp().preset_bundle->printers.get_selected_preset().printer_technology();
    for (auto tab : tabs_list)
        if (tab->supports_printer_technology(print_tech))
        {
            if (tab->GetParent() != this) continue;
            switch (tab->type())
            {
                case Preset::TYPE_PRINT:
                case Preset::TYPE_SLA_PRINT:
                    m_tab_print = tab;
                    break;
                case Preset::TYPE_FILAMENT:
                case Preset::TYPE_SLA_MATERIAL:
                    m_tab_filament = tab;
                    break;
                case Preset::TYPE_PRINTER:
                    m_tab_printer = tab;
                    break;
                default:
                    break;
            }
        }
    if (m_top_panel) {
        m_tab_print_object = wxGetApp().get_model_tab();
        m_tab_print_part = wxGetApp().get_model_tab(true);
        m_tab_print_layer = wxGetApp().get_layer_tab();
    }
    return;
}
References m_tab_filament, m_tab_print, m_tab_print_layer, m_tab_print_object, m_tab_print_part, m_tab_printer, m_top_panel, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, and Slic3r::Preset::TYPE_SLA_PRINT.
Referenced by rebuild_panels().
set_active_tab()
void Slic3r::GUI::ParamsPanel::set_active_tab (wxPanel * tab)
{
    Tab* cur_tab = dynamic_cast<Tab *> (tab);
    if (cur_tab == nullptr) {
        if (!m_mode_region->GetValue()) {
            cur_tab = (Tab*) m_tab_print;
        } else if (m_tab_print_part && ((TabPrintModel*) m_tab_print_part)->has_model_config()) {
            cur_tab = (Tab*) m_tab_print_part;
        } else if (m_tab_print_layer && ((TabPrintModel*)m_tab_print_layer)->has_model_config()) {
            cur_tab = (Tab*)m_tab_print_layer;
        } else if (m_tab_print_object && ((TabPrintModel*) m_tab_print_object)->has_model_config()) {
            cur_tab = (Tab*) m_tab_print_object;
        }
        Show(cur_tab != nullptr);
        wxGetApp().sidebar().show_object_list(m_mode_region->GetValue());
        if (m_current_tab == cur_tab)
            return;
        if (cur_tab)
            cur_tab->restore_last_select_item();
        return;
    }
    m_current_tab = tab;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": set current to %1%, type=%2%") % cur_tab % cur_tab?cur_tab->type():-1;
    update_mode();
    // BBS: open/close tab
    for (auto t : std::vector<std::pair<wxPanel*, wxStaticLine*>>({
            {m_tab_print, m_staticline_print},
            {m_tab_print_object, m_staticline_print_object},
            {m_tab_print_part, m_staticline_print_part},
            {m_tab_print_layer, nullptr},
            {m_tab_filament, m_staticline_filament},
            {m_tab_printer, m_staticline_printer}})) {
        if (!t.first) continue;
        t.first->Show(tab == t.first);
        if (!t.second) continue;
        t.second->Show(tab == t.first);
        //m_left_sizer->GetItem(t)->SetProportion(tab == t ? 1 : 0);
    }
    m_left_sizer->Layout();
    if (auto dialog = dynamic_cast<wxDialog*>(GetParent())) {
        wxString title = cur_tab->type() == Preset::TYPE_FILAMENT ? _L("Filament settings") : _L("Printer settings");
        dialog->SetTitle(title);
    }
    auto tab_print = dynamic_cast<Tab*>(m_tab_print);
    if (cur_tab == m_tab_print) {
        if (tab_print)
            tab_print->toggle_line("print_flow_ratio", false);
    }
    else {
        if (tab_print)
            tab_print->toggle_line("print_flow_ratio", false);
    }
}
References _L, m_current_tab, m_left_sizer, m_mode_region, m_staticline_filament, m_staticline_print, m_staticline_print_object, m_staticline_print_part, m_staticline_printer, m_tab_filament, m_tab_print, m_tab_print_layer, m_tab_print_object, m_tab_print_part, m_tab_printer, Slic3r::GUI::Tab::restore_last_select_item(), Slic3r::GUI::Tab::toggle_line(), Slic3r::GUI::Tab::type(), Slic3r::Preset::TYPE_FILAMENT, and update_mode().
Referenced by OnActivate(), OnToggled(), switch_to_global(), switch_to_object(), and Slic3r::GUI::Tab::tree_sel_change_delayed().
switch_to_global()
void Slic3r::GUI::ParamsPanel::switch_to_global ()
{
    m_mode_region->SetValue(false);
    set_active_tab(nullptr);
}
References m_mode_region, set_active_tab(), and SwitchButton::SetValue().
switch_to_object()
void Slic3r::GUI::ParamsPanel::switch_to_object (bool with_tips = false)
{
    m_mode_region->SetValue(true);
    set_active_tab(nullptr);
    if (with_tips) {
        m_highlighter.init(std::pair(m_tips_arrow, &m_tips_arror_blink), m_top_panel);
        m_highlighter.blink();
    }
}
References Slic3r::GUI::ParamsPanel::Highlighter::blink(), Slic3r::GUI::ParamsPanel::Highlighter::init(), m_highlighter, m_mode_region, m_tips_arror_blink, m_tips_arrow, m_top_panel, set_active_tab(), and SwitchButton::SetValue().
switch_to_object_if_has_object_configs()
void Slic3r::GUI::ParamsPanel::switch_to_object_if_has_object_configs ()
{
    if (m_has_object_config) m_mode_region->SetValue(true);
}
References m_has_object_config, m_mode_region, and SwitchButton::SetValue().
update_mode()
void Slic3r::GUI::ParamsPanel::update_mode ()
{
    int app_mode = Slic3r::GUI::wxGetApp().get_mode();
    SwitchButton * mode_view = m_current_tab ? dynamic_cast<Tab*>(m_current_tab)->m_mode_view : nullptr;
    if (mode_view == nullptr) mode_view = m_mode_view;
    if (mode_view == nullptr) return;
    //BBS: disable the mode tab and return directly when enable develop mode
    if (app_mode == comDevelop)
    {
        mode_view->Disable();
        return;
    }
    if (!mode_view->IsEnabled())
        mode_view->Enable();
    if (app_mode == comAdvanced)
    {
        mode_view->SetValue(true);
    }
    else
    {
        mode_view->SetValue(false);
    }
}
References Slic3r::comAdvanced, Slic3r::comDevelop, m_current_tab, m_mode_view, and SwitchButton::SetValue().
Referenced by set_active_tab(), and Slic3r::GUI::GUI_App::update_mode().
Member Data Documentation
m_button_sizer
wxBoxSizer* Slic3r::GUI::ParamsPanel::m_button_sizer { nullptr } protected
Referenced by free_sizers().
m_compare_btn
ScalableButton* Slic3r::GUI::ParamsPanel::m_compare_btn { nullptr } protected
Referenced by ParamsPanel(), create_layout(), and msw_rescale().
m_current_tab
wxPanel* Slic3r::GUI::ParamsPanel::m_current_tab { nullptr } protected
Referenced by ~ParamsPanel(), get_current_tab(), is_active_and_shown_tab(), OnActivate(), set_active_tab(), and update_mode().
m_export_to_file
wxWindow* Slic3r::GUI::ParamsPanel::m_export_to_file { nullptr } protected
Referenced by delete_subwindows().
m_has_object_config
bool Slic3r::GUI::ParamsPanel::m_has_object_config { false } protected
Referenced by notify_object_config_changed(), and switch_to_object_if_has_object_configs().
m_highlighter
struct Slic3r::GUI::ParamsPanel::Highlighter Slic3r::GUI::ParamsPanel::m_highlighter protected
Referenced by ParamsPanel(), and switch_to_object().
m_import_from_file
wxWindow* Slic3r::GUI::ParamsPanel::m_import_from_file { nullptr } protected
Referenced by delete_subwindows().
m_left_sizer
wxBoxSizer* Slic3r::GUI::ParamsPanel::m_left_sizer { nullptr } protected
Referenced by create_layout(), free_sizers(), msw_rescale(), and set_active_tab().
m_mode_region
SwitchButton* Slic3r::GUI::ParamsPanel::m_mode_region { nullptr } protected
Referenced by ParamsPanel(), create_layout(), delete_subwindows(), msw_rescale(), notify_object_config_changed(), OnToggled(), set_active_tab(), switch_to_global(), switch_to_object(), and switch_to_object_if_has_object_configs().
m_mode_sizer
wxBoxSizer* Slic3r::GUI::ParamsPanel::m_mode_sizer { nullptr } protected
Referenced by create_layout(), free_sizers(), and msw_rescale().
m_mode_view
SwitchButton* Slic3r::GUI::ParamsPanel::m_mode_view { nullptr } protected
Referenced by ParamsPanel(), create_layout(), delete_subwindows(), msw_rescale(), and update_mode().
m_page_sizer
wxBoxSizer* Slic3r::GUI::ParamsPanel::m_page_sizer { nullptr } protected
Referenced by ParamsPanel(), and clear_page().
m_page_view
wxScrolledWindow* Slic3r::GUI::ParamsPanel::m_page_view { nullptr } protected
Referenced by ParamsPanel(), create_layout(), delete_subwindows(), and get_paged_view().
m_process_icon
ScalableButton* Slic3r::GUI::ParamsPanel::m_process_icon { nullptr } protected
Referenced by ParamsPanel(), create_layout(), and msw_rescale().
m_search_btn
ScalableButton* Slic3r::GUI::ParamsPanel::m_search_btn { nullptr } protected
Referenced by delete_subwindows(), and msw_rescale().
m_setting_btn
ScalableButton* Slic3r::GUI::ParamsPanel::m_setting_btn { nullptr } protected
Referenced by ParamsPanel(), create_layout(), and msw_rescale().
m_staticline_filament
wxStaticLine* Slic3r::GUI::ParamsPanel::m_staticline_filament { nullptr } protected
Referenced by create_layout(), delete_subwindows(), and set_active_tab().
m_staticline_print
wxStaticLine* Slic3r::GUI::ParamsPanel::m_staticline_print { nullptr } protected
Referenced by delete_subwindows(), and set_active_tab().
m_staticline_print_object
wxStaticLine* Slic3r::GUI::ParamsPanel::m_staticline_print_object { nullptr } protected
Referenced by create_layout(), delete_subwindows(), and set_active_tab().
m_staticline_print_part
wxStaticLine* Slic3r::GUI::ParamsPanel::m_staticline_print_part { nullptr } protected
Referenced by create_layout(), delete_subwindows(), and set_active_tab().
m_staticline_printer
wxStaticLine* Slic3r::GUI::ParamsPanel::m_staticline_printer { nullptr } protected
Referenced by create_layout(), delete_subwindows(), and set_active_tab().
m_tab_filament
wxPanel* Slic3r::GUI::ParamsPanel::m_tab_filament { nullptr } protected
Referenced by create_layout(), filament_panel(), msw_rescale(), OnActivate(), refresh_tabs(), and set_active_tab().
m_tab_print
wxPanel* Slic3r::GUI::ParamsPanel::m_tab_print { nullptr } protected
Referenced by create_layout(), msw_rescale(), OnActivate(), refresh_tabs(), and set_active_tab().
m_tab_print_layer
wxPanel* Slic3r::GUI::ParamsPanel::m_tab_print_layer { nullptr } protected
Referenced by create_layout(), msw_rescale(), refresh_tabs(), and set_active_tab().
m_tab_print_object
wxPanel* Slic3r::GUI::ParamsPanel::m_tab_print_object { nullptr } protected
Referenced by create_layout(), msw_rescale(), refresh_tabs(), and set_active_tab().
m_tab_print_part
wxPanel* Slic3r::GUI::ParamsPanel::m_tab_print_part { nullptr } protected
Referenced by create_layout(), msw_rescale(), refresh_tabs(), and set_active_tab().
m_tab_printer
wxPanel* Slic3r::GUI::ParamsPanel::m_tab_printer { nullptr } protected
Referenced by create_layout(), msw_rescale(), refresh_tabs(), and set_active_tab().
m_tips_arror_blink
bool Slic3r::GUI::ParamsPanel::m_tips_arror_blink {false} protected
Referenced by switch_to_object().
m_tips_arrow
ScalableButton* Slic3r::GUI::ParamsPanel::m_tips_arrow {nullptr} protected
Referenced by ParamsPanel(), create_layout(), msw_rescale(), and switch_to_object().
m_title_label
wxStaticText* Slic3r::GUI::ParamsPanel::m_title_label { nullptr } protected
Referenced by ParamsPanel(), create_layout(), and delete_subwindows().
m_title_view
wxStaticText* Slic3r::GUI::ParamsPanel::m_title_view { nullptr } protected
Referenced by ParamsPanel(), create_layout(), and delete_subwindows().
m_toggle_off_icon
wxBitmap Slic3r::GUI::ParamsPanel::m_toggle_off_icon protected
m_toggle_on_icon
wxBitmap Slic3r::GUI::ParamsPanel::m_toggle_on_icon protected
m_top_panel
StaticBox* Slic3r::GUI::ParamsPanel::m_top_panel { nullptr } protected
Referenced by ParamsPanel(), create_layout(), get_top_panel(), refresh_tabs(), and switch_to_object().
m_top_sizer
wxBoxSizer* Slic3r::GUI::ParamsPanel::m_top_sizer { nullptr } protected
Referenced by ParamsPanel(), ~ParamsPanel(), create_layout(), and free_sizers().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ParamsPanel.hpp
src/slic3r/GUI/ParamsPanel.cpp