OrcaSlicer: logger_t Class Reference
logger_t Class Reference
#include <src/mcut/include/mcut/internal/utils.h>
Public Types
typedef std::ostream &(* ManipFn) (std::ostream &)
typedef std::ios_base &(* FlagsFn) (std::ios_base &)
Public Member Functions
logger_t ()
logger_t (const logger_t &other)=delete
logger_t & operator= (const logger_t &other)=delete
~logger_t ()
std::string get_log_string ()
void set_reason_for_failure (const std::string &msg)
std::string get_reason_for_failure ()
bool verbose ()
void set_verbose (bool b)
void reset ()
void indent ()
void unindent ()
template<class T >
logger_t & operator<< (const T &output)
logger_t & operator<< (ManipFn manip)
endl, flush, setw, setfill, etc.
logger_t & operator<< (FlagsFn manip)
setiosflags, resetiosflags
void flush ()
Private Attributes
std::stringstream m_buffer
bool m_verbose
std::string m_prepend
std::string m_reason_for_failure
Detailed Description
Member Typedef Documentation
FlagsFn
typedef std::ios_base &(* logger_t::FlagsFn) (std::ios_base &)
ManipFn
typedef std::ostream &(* logger_t::ManipFn) (std::ostream &)
Constructor & Destructor Documentation
logger_t() [1/2]
logger_t::logger_t () inline
        : m_buffer()
        , m_verbose(false)
        , m_prepend()
        , m_reason_for_failure()
    {
    }
logger_t() [2/2]
logger_t::logger_t (const logger_t & other) delete
~logger_t()
logger_t::~logger_t () inline
    {
    }
Member Function Documentation
flush()
void logger_t::flush () inline
    {
        if (!(verbose())) {
            return;
        }
#if 0 // dump log to terminal [immediately]
            std::cout << m_prepend << "::" << m_buffer.str();
            m_buffer.str(std::string());
            m_buffer.clear();
#endif
    }
References m_buffer, m_prepend, and verbose().
Referenced by operator<<().
get_log_string()
std::string logger_t::get_log_string () inline
    {
        return m_buffer.str();
    }
References m_buffer.
get_reason_for_failure()
std::string logger_t::get_reason_for_failure () inline
    {
        std::string s(m_reason_for_failure); // copy
        return s;
    }
References m_reason_for_failure.
Referenced by preproc().
indent()
void logger_t::indent () inline
    {
        if (!verbose()) {
            return;
        }
        m_prepend.append("  ");
    }
References m_prepend, and verbose().
operator<<() [1/3]
template<class T > logger_t & logger_t::operator<< (const T & output) inline
    {
        if (verbose()) {
            m_buffer << output;
        }
        return *this;
    }
References m_buffer, and verbose().
operator<<() [2/3]
logger_t & logger_t::operator<< (FlagsFn manip) inline
setiosflags, resetiosflags
    {
        if (verbose()) {
            manip(m_buffer);
        }
        return *this;
    }
References m_buffer, and verbose().
operator<<() [3/3]
logger_t & logger_t::operator<< (ManipFn manip) inline
endl, flush, setw, setfill, etc.
    {
        if (verbose()) {
            manip(m_buffer);
            if (manip == static_cast<ManipFn>(std::flush) || manip == static_cast<ManipFn>(std::endl)) {
                this->flush();
            }
        }
        return *this;
    }
References flush(), m_buffer, and verbose().
operator=()
logger_t & logger_t::operator= (const logger_t & other) delete
reset()
void logger_t::reset () inline
    {
        m_prepend.clear();
    }
References m_prepend.
Referenced by dispatch().
set_reason_for_failure()
void logger_t::set_reason_for_failure (const std::string & msg) inline
    {
        if (m_reason_for_failure.empty()) // NOTE
            m_reason_for_failure = msg;
    }
References m_reason_for_failure.
Referenced by dispatch().
set_verbose()
void logger_t::set_verbose (bool b) inline
    {
        m_verbose = b;
    }
References m_verbose.
Referenced by dispatch().
unindent()
void logger_t::unindent () inline
    {
        if (!verbose()) {
            return;
        }
        m_prepend.pop_back();
        m_prepend.pop_back();
    }
References m_prepend, and verbose().
verbose()
bool logger_t::verbose () inline
    {
        return m_verbose;
    }
References m_verbose.
Referenced by flush(), indent(), operator<<(), operator<<(), operator<<(), and unindent().
Member Data Documentation
m_buffer
std::stringstream logger_t::m_buffer private
Referenced by flush(), get_log_string(), operator<<(), operator<<(), and operator<<().
m_prepend
std::string logger_t::m_prepend private
Referenced by flush(), indent(), reset(), and unindent().
m_reason_for_failure
std::string logger_t::m_reason_for_failure private
Referenced by get_reason_for_failure(), and set_reason_for_failure().
m_verbose
bool logger_t::m_verbose private
Referenced by set_verbose(), and verbose().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/utils.h