OrcaSlicer: Helpers
Helpers
hidapi API
Classes
struct cdt::duplicates_info_t
Functions
std::vector< std::vector< std::uint32_t > > cdt::get_vertex_to_triangles_map (const std::vector< triangle_t > &triangles, const std::uint32_t verticesSize)
template<class ForwardIt , class SortUniqIndsFwdIt >
ForwardIt cdt::remove_at (ForwardIt first, ForwardIt last, SortUniqIndsFwdIt ii_first, SortUniqIndsFwdIt ii_last)
template<typename T , typename TVertexIter , typename TGetVertexCoordX , typename TGetVertexCoordY >
duplicates_info_t cdt::find_duplicates (TVertexIter first, TVertexIter last, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord)
template<typename TVertex , typename TAllocator >
void cdt::remove_duplicates (std::vector< TVertex, TAllocator > &vertices, const std::vector< std::size_t > &duplicates)
template<typename T >
duplicates_info_t cdt::remove_duplicates (std::vector< vec2_< T > > &vertices)
template<typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd , typename TMakeEdgeFromStartAndEnd >
void cdt::remap_edges (TEdgeIter first, const TEdgeIter last, const std::vector< std::size_t > &mapping, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd, TMakeEdgeFromStartAndEnd makeEdge)
void cdt::remap_edges (std::vector< edge_t > &edges, const std::vector< std::size_t > &mapping)
template<typename T , typename TVertex , typename TGetVertexCoordX , typename TGetVertexCoordY , typename TVertexAllocator , typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd , typename TMakeEdgeFromStartAndEnd >
duplicates_info_t cdt::remove_duplicates_and_remap_edges (std::vector< TVertex, TVertexAllocator > &vertices, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord, const TEdgeIter edgesFirst, const TEdgeIter edgesLast, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd, TMakeEdgeFromStartAndEnd makeEdge)
template<typename T >
duplicates_info_t cdt::remove_duplicates_and_remap_edges (std::vector< vec2_< T > > &vertices, std::vector< edge_t > &edges)
std::unordered_set< edge_t > cdt::extract_edges_from_triangles (const std::vector< triangle_t > &triangles)
std::unordered_map< edge_t, std::vector< edge_t > > cdt::edge_to_pieces_mapping (const std::unordered_map< edge_t, std::vector< edge_t > > &pieceToOriginals)
template<typename T >
std::unordered_map< edge_t, std::vector< std::uint32_t > > cdt::get_edge_to_split_vertices_map (const std::unordered_map< edge_t, std::vector< edge_t > > &edgeToPieces, const std::vector< vec2_< T > > &vertices)
Detailed Description
Helpers for working with cdt::triangulator_t.
Class Documentation
cdt::duplicates_info_t
struct cdt::duplicates_info_t
Information about removed duplicated vertices.
Contains mapping information and removed duplicates indices.
Note
vertices {0,1,2,3,4} where 0 and 3 are the same will produce mapping {0,1,2,0,3} (to new vertices {0,1,2,3}) and duplicates {3}
Class Members
vector< size_t > duplicates duplicates' indices
vector< size_t > mapping vertex index mapping
Function Documentation
edge_to_pieces_mapping()
std::unordered_map< edge_t, std::vector< edge_t > > cdt::edge_to_pieces_mapping (const std::unordered_map< edge_t, std::vector< edge_t > > & pieceToOriginals) inline
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Converts piece->original_edges mapping to original_edge->pieces
Parameters
pieceToOriginals maps pieces to original edges
Returns
mapping of original edges to pieces
{
    std::unordered_map<edge_t, std::vector<edge_t>> originalToPieces;
    typedef std::unordered_map<edge_t, std::vector<edge_t>>::const_iterator Cit;
    for (Cit ptoIt = pieceToOriginals.begin(); ptoIt != pieceToOriginals.end();
         ++ptoIt) {
        const edge_t piece = ptoIt->first;
        const std::vector<edge_t>& originals = ptoIt->second;
        for (std::vector<edge_t>::const_iterator origIt = originals.begin();
             origIt != originals.end();
             ++origIt) {
            originalToPieces[*origIt].push_back(piece);
        }
    }
    return originalToPieces;
}
extract_edges_from_triangles()
std::unordered_set< edge_t > cdt::extract_edges_from_triangles (const std::vector< triangle_t > & triangles) inline
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Extract all edges of triangles
Parameters
triangles triangles used to extract edges
Returns
an unordered set of all edges of triangulation
{
    std::unordered_set<edge_t> edges;
    for (std::vector<triangle_t>::const_iterator t = triangles.begin(); t != triangles.end(); ++t) {
        edges.insert(edge_t(std::uint32_t(t->vertices[0]), std::uint32_t(t->vertices[1])));
        edges.insert(edge_t(std::uint32_t(t->vertices[1]), std::uint32_t(t->vertices[2])));
        edges.insert(edge_t(std::uint32_t(t->vertices[2]), std::uint32_t(t->vertices[0])));
    }
    return edges;
}
find_duplicates()
template<typename T , typename TVertexIter , typename TGetVertexCoordX , typename TGetVertexCoordY > duplicates_info_t cdt::find_duplicates (TVertexIter first, TVertexIter last, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord)
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Find duplicates in given custom point-type range
Note
duplicates are points with exactly same X and Y coordinates
Template Parameters
TVertexIter iterator that dereferences to custom point type
TGetVertexCoordX function object getting x coordinate from vertex. Getter signature: const TVertexIter::value_type& -> T
TGetVertexCoordY function object getting y coordinate from vertex. Getter signature: const TVertexIter::value_type& -> T
Parameters
first beginning of the range of vertices
last end of the range of vertices
get_x_coord getter of X-coordinate
get_y_coord getter of Y-coordinate
Returns
information about vertex duplicates
{
    std::unordered_map<vec2_<T>, std::size_t> uniqueVerts; // position to index map
    const std::size_t verticesSize = std::distance(first, last);
    duplicates_info_t di = {
        std::vector<std::size_t>(verticesSize),
        std::vector<std::size_t>()
    };
    for (std::size_t iIn = 0, iOut = iIn; iIn < verticesSize; ++iIn, ++first) {
        typename std::unordered_map<vec2_<T>, std::size_t>::const_iterator it;
        bool isUnique;
        // check if the coordinates match [exactly] (in the bitwise sense)
        std::tie(it, isUnique) = uniqueVerts.insert(
            std::make_pair(
                vec2_<T>::make(get_x_coord(*first), get_y_coord(*first)),
                iOut));
        if (isUnique) {
            di.mapping[iIn] = iOut++;
            continue;
        }
        di.mapping[iIn] = it->second; // found a duplicate
        di.duplicates.push_back(iIn);
    }
    return di;
}
References std::distance(), cdt::duplicates_info_t::duplicates, and cdt::duplicates_info_t::mapping.
get_edge_to_split_vertices_map()
template<typename T > std::unordered_map< edge_t, std::vector< std::uint32_t > > cdt::get_edge_to_split_vertices_map (const std::unordered_map< edge_t, std::vector< edge_t > > & edgeToPieces, const std::vector< vec2_< T > > & vertices)
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Convert edge-to-pieces mapping into edge-to-split-vertices mapping
Template Parameters
T type of vertex coordinates (e.g., float, double)
Parameters
edgeToPieces edge-to-pieces mapping
vertices vertex buffer
Returns
mapping of edge-to-split-points. Split points are sorted from edge's start (v1) to end (v2)
{
    typedef std::pair<std::uint32_t, T> VertCoordPair;
    struct ComparePred {
        bool operator()(const VertCoordPair& a, const VertCoordPair& b) const
        {
            return a.second < b.second;
        }
    } comparePred;
    std::unordered_map<edge_t, std::vector<std::uint32_t>> edgeToSplitVerts;
    for (std::unordered_map<edge_t, std::vector<edge_t>>::const_iterator it = edgeToPieces.begin();
         it != edgeToPieces.end();
         ++it) {
        const edge_t& e = it->first;
        const T dX = vertices[e.v2()].x() - vertices[e.v1()].x();
        const T dY = vertices[e.v2()].y() - vertices[e.v1()].y();
        const bool isX = std::abs(dX) >= std::abs(dY); // X-coord longer
        const bool isAscending = isX ? dX >= 0 : dY >= 0; // Longer coordinate ascends
        const std::vector<edge_t>& pieces = it->second;
        std::vector<VertCoordPair> splitVerts;
        // size is:  2[ends] + (pieces - 1)[split vertices] = pieces + 1
        splitVerts.reserve(pieces.size() + 1);
        for (std::vector<edge_t>::const_iterator it = pieces.begin(); it != pieces.end(); ++it) {
            const std::array<std::uint32_t, 2> vv = { it->v1(), it->v2() };
            for (std::array<std::uint32_t, 2>::const_iterator v = vv.begin(); v != vv.end(); ++v) {
                const T c = isX ? vertices[*v].x() : vertices[*v].y();
                splitVerts.push_back(std::make_pair(*v, isAscending ? c : -c));
            }
        }
        // sort by longest coordinate
        std::sort(splitVerts.begin(), splitVerts.end(), comparePred);
        // remove duplicates
        splitVerts.erase(
            std::unique(splitVerts.begin(), splitVerts.end()),
            splitVerts.end());
        MCUT_ASSERT(splitVerts.size() > 2); // 2 end points with split vertices
        std::pair<edge_t, std::vector<std::uint32_t>> val = std::make_pair(e, std::vector<std::uint32_t>());
        val.second.reserve(splitVerts.size());
        for (typename std::vector<VertCoordPair>::const_iterator it = splitVerts.begin() + 1;
             it != splitVerts.end() - 1;
             ++it) {
            val.second.push_back(it->first);
        }
        edgeToSplitVerts.insert(val);
    }
    return edgeToSplitVerts;
}
References dX, dY, MCUT_ASSERT, cdt::edge_t::v1(), and cdt::edge_t::v2().
get_vertex_to_triangles_map()
std::vector< std::vector< std::uint32_t > > cdt::get_vertex_to_triangles_map (const std::vector< triangle_t > & triangles, const std::uint32_t verticesSize) inline
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Calculate triangles adjacent to vertices (triangles by vertex index)
Parameters
triangles triangulation
verticesSize total number of vertices to pre-allocate the output
Returns
triangles by vertex index (array of size V, where V is the number of vertices; each element is a list of triangles incident to corresponding vertex).
{
    std::vector<std::vector<std::uint32_t>> map(verticesSize);
    for (std::uint32_t i = 0; i < (std::uint32_t)triangles.size(); ++i) {
        const std::uint32_t triangle_index = i;
        const triangle_t& triangle = triangles[triangle_index];
        const std::array<std::uint32_t, 3>& vertices = triangle.vertices;
        for (std::array<std::uint32_t, 3>::const_iterator j = vertices.begin(); j != vertices.end(); ++j) {
            const std::uint32_t vertex_index = *j;
            map[vertex_index].push_back(i);
        }
    }
    return map;
}
References cdt::triangle_t::vertices.
Referenced by cdt::check_topology().
remap_edges() [1/2]
void cdt::remap_edges (std::vector< edge_t > & edges, const std::vector< std::size_t > & mapping) inline
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Remap vertex indices in edges (in-place) using given vertex-index mapping.
Note
Mapping can be a result of remove_duplicates function
Parameters
[in,out] edges collection of edges to remap
mapping vertex-index mapping
{
    remap_edges(
        edges.begin(),
        edges.end(),
        mapping,
        edge_get_v1,
        edge_get_v2,
        edge_make);
}
References cdt::edge_get_v1(), cdt::edge_get_v2(), cdt::edge_make(), and cdt::remap_edges().
remap_edges() [2/2]
template<typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd , typename TMakeEdgeFromStartAndEnd > void cdt::remap_edges (TEdgeIter first, const TEdgeIter last, const std::vector< std::size_t > & mapping, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd, TMakeEdgeFromStartAndEnd makeEdge)
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Remap vertex indices in edges (in-place) using given vertex-index mapping.
Template Parameters
TEdgeIter iterator that dereferences to custom edge type
TGetEdgeVertexStart function object getting start vertex index from an edge. Getter signature: const TEdgeIter::value_type& -> std::uint32_t
TGetEdgeVertexEnd function object getting end vertex index from an edge. Getter signature: const TEdgeIter::value_type& -> std::uint32_t
TMakeEdgeFromStartAndEnd function object that makes new edge from start and end vertices
Parameters
first beginning of the range of edges
last end of the range of edges
mapping vertex-index mapping
getStart getter of edge start vertex index
getEnd getter of edge end vertex index
makeEdge factory for making edge from vetices
{
    for (; first != last; ++first) {
        *first = makeEdge(
            static_cast<std::uint32_t>(mapping[getStart(*first)]),
            static_cast<std::uint32_t>(mapping[getEnd(*first)]));
    }
}
Referenced by cdt::remap_edges(), and cdt::remove_duplicates_and_remap_edges().
remove_at()
template<class ForwardIt , class SortUniqIndsFwdIt > ForwardIt cdt::remove_at (ForwardIt first, ForwardIt last, SortUniqIndsFwdIt ii_first, SortUniqIndsFwdIt ii_last) inline
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Remove elements in the range [first; last) with indices from the sorted unique range [ii_first, ii_last)
{
    if (ii_first == ii_last) // no indices-to-remove are given
        return last;
    typedef typename std::iterator_traits<ForwardIt>::difference_type diff_t;
    typedef typename std::iterator_traits<SortUniqIndsFwdIt>::value_type ind_t;
    ForwardIt destination = first + static_cast<diff_t>(*ii_first);
    while (ii_first != ii_last) {
        // advance to an index after a chunk of elements-to-keep
        for (ind_t cur = *ii_first++; ii_first != ii_last; ++ii_first) {
            const ind_t nxt = *ii_first;
            if (nxt - cur > 1)
                break;
            cur = nxt;
        }
        // move the chunk of elements-to-keep to new destination
        const ForwardIt source_first = first + static_cast<diff_t>(*(ii_first - 1)) + 1;
        const ForwardIt source_last = ii_first != ii_last ? first + static_cast<diff_t>(*ii_first) : last;
        std::move(source_first, source_last, destination);
        destination += source_last - source_first;
    }
    return destination;
}
Referenced by cdt::remove_duplicates().
remove_duplicates() [1/2]
template<typename TVertex , typename TAllocator > void cdt::remove_duplicates (std::vector< TVertex, TAllocator > & vertices, const std::vector< std::size_t > & duplicates)
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Remove duplicates in-place from vector of custom points
Template Parameters
TVertex vertex type
TAllocator allocator used by input vector of vertices
Parameters
vertices vertices to remove duplicates from
duplicates information about duplicates
{
    vertices.erase(
        remove_at(
            vertices.begin(),
            vertices.end(),
            duplicates.begin(),
            duplicates.end()),
        vertices.end());
}
References cdt::remove_at().
Referenced by cdt::remove_duplicates(), and cdt::remove_duplicates_and_remap_edges().
remove_duplicates() [2/2]
template<typename T > duplicates_info_t cdt::remove_duplicates (std::vector< vec2_< T > > & vertices)
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Remove duplicated points in-place
Template Parameters
T type of vertex coordinates (e.g., float, double)
Parameters
[in,out] vertices collection of vertices to remove duplicates from
Returns
information about duplicated vertices that were removed.
{
    const duplicates_info_t di = find_duplicates<T>(
        vertices.begin(),
        vertices.end(),
        get_x_coord_vec2d<T>,
        get_y_coord_vec2d<T>);
    remove_duplicates(vertices, di.duplicates);
    return di;
}
References cdt::duplicates_info_t::duplicates, and cdt::remove_duplicates().
remove_duplicates_and_remap_edges() [1/2]
template<typename T , typename TVertex , typename TGetVertexCoordX , typename TGetVertexCoordY , typename TVertexAllocator , typename TEdgeIter , typename TGetEdgeVertexStart , typename TGetEdgeVertexEnd , typename TMakeEdgeFromStartAndEnd > duplicates_info_t cdt::remove_duplicates_and_remap_edges (std::vector< TVertex, TVertexAllocator > & vertices, TGetVertexCoordX get_x_coord, TGetVertexCoordY get_y_coord, const TEdgeIter edgesFirst, const TEdgeIter edgesLast, TGetEdgeVertexStart getStart, TGetEdgeVertexEnd getEnd, TMakeEdgeFromStartAndEnd makeEdge)
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Find point duplicates, remove them from vector (in-place) and remap edges (in-place)
Note
Same as a chained call of cdt::find_duplicates, cdt::remove_duplicates, and cdt::remap_edges
Template Parameters
T type of vertex coordinates (e.g., float, double)
TVertex type of vertex
TGetVertexCoordX function object getting x coordinate from vertex. Getter signature: const TVertexIter::value_type& -> T
TGetVertexCoordY function object getting y coordinate from vertex. Getter signature: const TVertexIter::value_type& -> T
TEdgeIter iterator that dereferences to custom edge type
TGetEdgeVertexStart function object getting start vertex index from an edge. Getter signature: const TEdgeIter::value_type& -> std::uint32_t
TGetEdgeVertexEnd function object getting end vertex index from an edge. Getter signature: const TEdgeIter::value_type& -> std::uint32_t
TMakeEdgeFromStartAndEnd function object that makes new edge from start and end vertices
Parameters
[in,out] vertices vertices to remove duplicates from
[in,out] edges collection of edges connecting vertices
get_x_coord getter of X-coordinate
get_y_coord getter of Y-coordinate
edgesFirst beginning of the range of edges
edgesLast end of the range of edges
getStart getter of edge start vertex index
getEnd getter of edge end vertex index
makeEdge factory for making edge from vetices
Returns
information about vertex duplicates
{
    const duplicates_info_t di = find_duplicates<T>(vertices.begin(), vertices.end(), get_x_coord, get_y_coord);
    remove_duplicates(vertices, di.duplicates);
    remap_edges(edgesFirst, edgesLast, di.mapping, getStart, getEnd, makeEdge);
    return di;
}
References cdt::duplicates_info_t::duplicates, cdt::duplicates_info_t::mapping, cdt::remap_edges(), and cdt::remove_duplicates().
remove_duplicates_and_remap_edges() [2/2]
template<typename T > duplicates_info_t cdt::remove_duplicates_and_remap_edges (std::vector< vec2_< T > > & vertices, std::vector< edge_t > & edges)
#include <src/mcut/include/mcut/internal/cdt/cdt.h>
Same as a chained call of cdt::remove_duplicates + cdt::remap_edges
Template Parameters
T type of vertex coordinates (e.g., float, double)
Parameters
[in,out] vertices collection of vertices to remove duplicates from
[in,out] edges collection of edges to remap
{
    return remove_duplicates_and_remap_edges<T>(
        vertices,
        get_x_coord_vec2d<T>,
        get_y_coord_vec2d<T>,
        edges.begin(),
        edges.end(),
        edge_get_v1,
        edge_get_v2,
        edge_make);
}
References cdt::edge_get_v1(), cdt::edge_get_v2(), and cdt::edge_make().