OrcaSlicer: src/expat/expat.h File Reference
expat.h File Reference
#include <stdlib.h>
#include "expat_external.h"
Classes
struct XML_cp
struct XML_Memory_Handling_Suite
struct XML_Encoding
struct XML_ParsingStatus
struct XML_Expat_Version
struct XML_Feature
Macros
#define XML_TRUE ((XML_Bool) 1)
#define XML_FALSE ((XML_Bool) 0)
#define XML_STATUS_ERROR XML_STATUS_ERROR
#define XML_STATUS_OK XML_STATUS_OK
#define XML_STATUS_SUSPENDED XML_STATUS_SUSPENDED
#define XML_GetUserData(parser) (*(void **)(parser))
#define XML_GetErrorLineNumber XML_GetCurrentLineNumber
#define XML_GetErrorColumnNumber XML_GetCurrentColumnNumber
#define XML_GetErrorByteIndex XML_GetCurrentByteIndex
#define XML_MAJOR_VERSION 2
#define XML_MINOR_VERSION 2
#define XML_MICRO_VERSION 0
Typedefs
typedef struct XML_ParserStruct * XML_Parser
typedef unsigned char XML_Bool
typedef struct XML_cp XML_Content
typedef void(XMLCALL * XML_ElementDeclHandler) (void *userData, const XML_Char *name, XML_Content *model)
typedef void(XMLCALL * XML_AttlistDeclHandler) (void *userData, const XML_Char *elname, const XML_Char *attname, const XML_Char *att_type, const XML_Char *dflt, int isrequired)
typedef void(XMLCALL * XML_XmlDeclHandler) (void *userData, const XML_Char *version, const XML_Char *encoding, int standalone)
typedef void(XMLCALL * XML_StartElementHandler) (void *userData, const XML_Char *name, const XML_Char **atts)
typedef void(XMLCALL * XML_EndElementHandler) (void *userData, const XML_Char *name)
typedef void(XMLCALL * XML_CharacterDataHandler) (void *userData, const XML_Char *s, int len)
typedef void(XMLCALL * XML_ProcessingInstructionHandler) (void *userData, const XML_Char *target, const XML_Char *data)
typedef void(XMLCALL * XML_CommentHandler) (void *userData, const XML_Char *data)
typedef void(XMLCALL * XML_StartCdataSectionHandler) (void *userData)
typedef void(XMLCALL * XML_EndCdataSectionHandler) (void *userData)
typedef void(XMLCALL * XML_DefaultHandler) (void *userData, const XML_Char *s, int len)
typedef void(XMLCALL * XML_StartDoctypeDeclHandler) (void *userData, const XML_Char *doctypeName, const XML_Char *sysid, const XML_Char *pubid, int has_internal_subset)
typedef void(XMLCALL * XML_EndDoctypeDeclHandler) (void *userData)
typedef void(XMLCALL * XML_EntityDeclHandler) (void *userData, const XML_Char *entityName, int is_parameter_entity, const XML_Char *value, int value_length, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId, const XML_Char *notationName)
typedef void(XMLCALL * XML_UnparsedEntityDeclHandler) (void *userData, const XML_Char *entityName, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId, const XML_Char *notationName)
typedef void(XMLCALL * XML_NotationDeclHandler) (void *userData, const XML_Char *notationName, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId)
typedef void(XMLCALL * XML_StartNamespaceDeclHandler) (void *userData, const XML_Char *prefix, const XML_Char *uri)
typedef void(XMLCALL * XML_EndNamespaceDeclHandler) (void *userData, const XML_Char *prefix)
typedef int(XMLCALL * XML_NotStandaloneHandler) (void *userData)
typedef int(XMLCALL * XML_ExternalEntityRefHandler) (XML_Parser parser, const XML_Char *context, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId)
typedef void(XMLCALL * XML_SkippedEntityHandler) (void *userData, const XML_Char *entityName, int is_parameter_entity)
typedef int(XMLCALL * XML_UnknownEncodingHandler) (void *encodingHandlerData, const XML_Char *name, XML_Encoding *info)
Enumerations
enum XML_Status {
XML_STATUS_ERROR = 0 , XML_STATUS_ERROR = 0 , XML_STATUS_OK = 1 , XML_STATUS_OK = 1 ,
XML_STATUS_SUSPENDED
}
enum XML_Error {
XML_ERROR_NONE , XML_ERROR_NO_MEMORY , XML_ERROR_SYNTAX , XML_ERROR_NO_ELEMENTS ,
XML_ERROR_INVALID_TOKEN , XML_ERROR_UNCLOSED_TOKEN , XML_ERROR_PARTIAL_CHAR , XML_ERROR_TAG_MISMATCH ,
XML_ERROR_DUPLICATE_ATTRIBUTE , XML_ERROR_JUNK_AFTER_DOC_ELEMENT , XML_ERROR_PARAM_ENTITY_REF , XML_ERROR_UNDEFINED_ENTITY ,
XML_ERROR_RECURSIVE_ENTITY_REF , XML_ERROR_ASYNC_ENTITY , XML_ERROR_BAD_CHAR_REF , XML_ERROR_BINARY_ENTITY_REF ,
XML_ERROR_ATTRIBUTE_EXTERNAL_ENTITY_REF , XML_ERROR_MISPLACED_XML_PI , XML_ERROR_UNKNOWN_ENCODING , XML_ERROR_INCORRECT_ENCODING ,
XML_ERROR_UNCLOSED_CDATA_SECTION , XML_ERROR_EXTERNAL_ENTITY_HANDLING , XML_ERROR_NOT_STANDALONE , XML_ERROR_UNEXPECTED_STATE ,
XML_ERROR_ENTITY_DECLARED_IN_PE , XML_ERROR_FEATURE_REQUIRES_XML_DTD , XML_ERROR_CANT_CHANGE_FEATURE_ONCE_PARSING , XML_ERROR_UNBOUND_PREFIX ,
XML_ERROR_UNDECLARING_PREFIX , XML_ERROR_INCOMPLETE_PE , XML_ERROR_XML_DECL , XML_ERROR_TEXT_DECL ,
XML_ERROR_PUBLICID , XML_ERROR_SUSPENDED , XML_ERROR_NOT_SUSPENDED , XML_ERROR_ABORTED ,
XML_ERROR_FINISHED , XML_ERROR_SUSPEND_PE , XML_ERROR_RESERVED_PREFIX_XML , XML_ERROR_RESERVED_PREFIX_XMLNS ,
XML_ERROR_RESERVED_NAMESPACE_URI
}
enum XML_Content_Type {
XML_CTYPE_EMPTY = 1 , XML_CTYPE_ANY , XML_CTYPE_MIXED , XML_CTYPE_NAME ,
XML_CTYPE_CHOICE , XML_CTYPE_SEQ
}
enum XML_Content_Quant { XML_CQUANT_NONE , XML_CQUANT_OPT , XML_CQUANT_REP , XML_CQUANT_PLUS }
enum XML_Parsing { XML_INITIALIZED , XML_PARSING , XML_FINISHED , XML_SUSPENDED }
enum XML_ParamEntityParsing { XML_PARAM_ENTITY_PARSING_NEVER , XML_PARAM_ENTITY_PARSING_UNLESS_STANDALONE , XML_PARAM_ENTITY_PARSING_ALWAYS }
enum XML_FeatureEnum {
XML_FEATURE_END = 0 , XML_FEATURE_UNICODE , XML_FEATURE_UNICODE_WCHAR_T , XML_FEATURE_DTD ,
XML_FEATURE_CONTEXT_BYTES , XML_FEATURE_MIN_SIZE , XML_FEATURE_SIZEOF_XML_CHAR , XML_FEATURE_SIZEOF_XML_LCHAR ,
XML_FEATURE_NS , XML_FEATURE_LARGE_SIZE , XML_FEATURE_ATTR_INFO
}
Functions
XML_SetElementDeclHandler (XML_Parser parser, XML_ElementDeclHandler eldecl)
XML_SetAttlistDeclHandler (XML_Parser parser, XML_AttlistDeclHandler attdecl)
XML_SetXmlDeclHandler (XML_Parser parser, XML_XmlDeclHandler xmldecl)
XML_ParserCreate (const XML_Char *encoding)
XML_ParserCreateNS (const XML_Char *encoding, XML_Char namespaceSeparator)
XML_ParserCreate_MM (const XML_Char *encoding, const XML_Memory_Handling_Suite *memsuite, const XML_Char *namespaceSeparator)
XML_ParserReset (XML_Parser parser, const XML_Char *encoding)
XML_SetEntityDeclHandler (XML_Parser parser, XML_EntityDeclHandler handler)
XML_SetElementHandler (XML_Parser parser, XML_StartElementHandler start, XML_EndElementHandler end)
XML_SetStartElementHandler (XML_Parser parser, XML_StartElementHandler handler)
XML_SetEndElementHandler (XML_Parser parser, XML_EndElementHandler handler)
XML_SetCharacterDataHandler (XML_Parser parser, XML_CharacterDataHandler handler)
XML_SetProcessingInstructionHandler (XML_Parser parser, XML_ProcessingInstructionHandler handler)
XML_SetCommentHandler (XML_Parser parser, XML_CommentHandler handler)
XML_SetCdataSectionHandler (XML_Parser parser, XML_StartCdataSectionHandler start, XML_EndCdataSectionHandler end)
XML_SetStartCdataSectionHandler (XML_Parser parser, XML_StartCdataSectionHandler start)
XML_SetEndCdataSectionHandler (XML_Parser parser, XML_EndCdataSectionHandler end)
XML_SetDefaultHandler (XML_Parser parser, XML_DefaultHandler handler)
XML_SetDefaultHandlerExpand (XML_Parser parser, XML_DefaultHandler handler)
XML_SetDoctypeDeclHandler (XML_Parser parser, XML_StartDoctypeDeclHandler start, XML_EndDoctypeDeclHandler end)
XML_SetStartDoctypeDeclHandler (XML_Parser parser, XML_StartDoctypeDeclHandler start)
XML_SetEndDoctypeDeclHandler (XML_Parser parser, XML_EndDoctypeDeclHandler end)
XML_SetUnparsedEntityDeclHandler (XML_Parser parser, XML_UnparsedEntityDeclHandler handler)
XML_SetNotationDeclHandler (XML_Parser parser, XML_NotationDeclHandler handler)
XML_SetNamespaceDeclHandler (XML_Parser parser, XML_StartNamespaceDeclHandler start, XML_EndNamespaceDeclHandler end)
XML_SetStartNamespaceDeclHandler (XML_Parser parser, XML_StartNamespaceDeclHandler start)
XML_SetEndNamespaceDeclHandler (XML_Parser parser, XML_EndNamespaceDeclHandler end)
XML_SetNotStandaloneHandler (XML_Parser parser, XML_NotStandaloneHandler handler)
XML_SetExternalEntityRefHandler (XML_Parser parser, XML_ExternalEntityRefHandler handler)
XML_SetExternalEntityRefHandlerArg (XML_Parser parser, void *arg)
XML_SetSkippedEntityHandler (XML_Parser parser, XML_SkippedEntityHandler handler)
XML_SetUnknownEncodingHandler (XML_Parser parser, XML_UnknownEncodingHandler handler, void *encodingHandlerData)
XML_DefaultCurrent (XML_Parser parser)
XML_SetReturnNSTriplet (XML_Parser parser, int do_nst)
XML_SetUserData (XML_Parser parser, void *userData)
XML_SetEncoding (XML_Parser parser, const XML_Char *encoding)
XML_UseParserAsHandlerArg (XML_Parser parser)
XML_UseForeignDTD (XML_Parser parser, XML_Bool useDTD)
XML_SetBase (XML_Parser parser, const XML_Char *base)
XML_GetBase (XML_Parser parser)
XML_GetSpecifiedAttributeCount (XML_Parser parser)
XML_GetIdAttributeIndex (XML_Parser parser)
XML_Parse (XML_Parser parser, const char *s, int len, int isFinal)
XML_GetBuffer (XML_Parser parser, int len)
XML_ParseBuffer (XML_Parser parser, int len, int isFinal)
XML_StopParser (XML_Parser parser, XML_Bool resumable)
XML_ResumeParser (XML_Parser parser)
XML_GetParsingStatus (XML_Parser parser, XML_ParsingStatus *status)
XML_ExternalEntityParserCreate (XML_Parser parser, const XML_Char *context, const XML_Char *encoding)
XML_SetParamEntityParsing (XML_Parser parser, enum XML_ParamEntityParsing parsing)
XML_SetHashSalt (XML_Parser parser, unsigned long hash_salt)
XML_GetErrorCode (XML_Parser parser)
XMLPARSEAPI (XML_Size) XML_GetCurrentLineNumber(XML_Parser parser)
XMLPARSEAPI (XML_Index) XML_GetCurrentByteIndex(XML_Parser parser)
XML_GetCurrentByteCount (XML_Parser parser)
XML_GetInputContext (XML_Parser parser, int *offset, int *size)
XML_FreeContentModel (XML_Parser parser, XML_Content *model)
XML_ATTR_MALLOC XML_MemMalloc (XML_Parser parser, size_t size)
XML_MemRealloc (XML_Parser parser, void *ptr, size_t size)
XML_MemFree (XML_Parser parser, void *ptr)
XML_ParserFree (XML_Parser parser)
XML_ErrorString (enum XML_Error code)
XML_ExpatVersion (void)
XML_ExpatVersionInfo (void)
XML_GetFeatureList (void)
Class Documentation
XML_cp
struct XML_cp
Class Members
XML_Content * children
XML_Char * name
unsigned int numchildren
enum XML_Content_Quant quant
enum XML_Content_Type type
XML_ParsingStatus
struct XML_ParsingStatus
Class Members
XML_Bool finalBuffer
enum XML_Parsing parsing
XML_Expat_Version
struct XML_Expat_Version
Class Members
int major
int micro
int minor
XML_Feature
struct XML_Feature
Class Members
enum XML_FeatureEnum feature
const XML_LChar * name
long int value
Macro Definition Documentation
XML_FALSE
#define XML_FALSE ((XML_Bool) 0)
XML_GetErrorByteIndex
#define XML_GetErrorByteIndex XML_GetCurrentByteIndex
XML_GetErrorColumnNumber
#define XML_GetErrorColumnNumber XML_GetCurrentColumnNumber
XML_GetErrorLineNumber
#define XML_GetErrorLineNumber XML_GetCurrentLineNumber
XML_GetUserData
#define XML_GetUserData (parser) (*(void **)(parser))
XML_MAJOR_VERSION
#define XML_MAJOR_VERSION 2
XML_MICRO_VERSION
#define XML_MICRO_VERSION 0
XML_MINOR_VERSION
#define XML_MINOR_VERSION 2
XML_STATUS_ERROR
#define XML_STATUS_ERROR XML_STATUS_ERROR
XML_STATUS_OK
#define XML_STATUS_OK XML_STATUS_OK
XML_STATUS_SUSPENDED
#define XML_STATUS_SUSPENDED XML_STATUS_SUSPENDED
XML_TRUE
#define XML_TRUE ((XML_Bool) 1)
Typedef Documentation
XML_AttlistDeclHandler
typedef void(XMLCALL * XML_AttlistDeclHandler) (void *userData, const XML_Char *elname, const XML_Char *attname, const XML_Char *att_type, const XML_Char *dflt, int isrequired)
XML_Bool
typedef unsigned char XML_Bool
XML_CharacterDataHandler
typedef void(XMLCALL * XML_CharacterDataHandler) (void *userData, const XML_Char *s, int len)
XML_CommentHandler
typedef void(XMLCALL * XML_CommentHandler) (void *userData, const XML_Char *data)
XML_Content
typedef struct XML_cp XML_Content
XML_DefaultHandler
typedef void(XMLCALL * XML_DefaultHandler) (void *userData, const XML_Char *s, int len)
XML_ElementDeclHandler
typedef void(XMLCALL * XML_ElementDeclHandler) (void *userData, const XML_Char *name, XML_Content *model)
XML_EndCdataSectionHandler
typedef void(XMLCALL * XML_EndCdataSectionHandler) (void *userData)
XML_EndDoctypeDeclHandler
typedef void(XMLCALL * XML_EndDoctypeDeclHandler) (void *userData)
XML_EndElementHandler
typedef void(XMLCALL * XML_EndElementHandler) (void *userData, const XML_Char *name)
XML_EndNamespaceDeclHandler
typedef void(XMLCALL * XML_EndNamespaceDeclHandler) (void *userData, const XML_Char *prefix)
XML_EntityDeclHandler
typedef void(XMLCALL * XML_EntityDeclHandler) (void *userData, const XML_Char *entityName, int is_parameter_entity, const XML_Char *value, int value_length, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId, const XML_Char *notationName)
XML_ExternalEntityRefHandler
typedef int(XMLCALL * XML_ExternalEntityRefHandler) (XML_Parser parser, const XML_Char *context, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId)
XML_NotationDeclHandler
typedef void(XMLCALL * XML_NotationDeclHandler) (void *userData, const XML_Char *notationName, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId)
XML_NotStandaloneHandler
typedef int(XMLCALL * XML_NotStandaloneHandler) (void *userData)
XML_Parser
typedef struct XML_ParserStruct* XML_Parser
XML_ProcessingInstructionHandler
typedef void(XMLCALL * XML_ProcessingInstructionHandler) (void *userData, const XML_Char *target, const XML_Char *data)
XML_SkippedEntityHandler
typedef void(XMLCALL * XML_SkippedEntityHandler) (void *userData, const XML_Char *entityName, int is_parameter_entity)
XML_StartCdataSectionHandler
typedef void(XMLCALL * XML_StartCdataSectionHandler) (void *userData)
XML_StartDoctypeDeclHandler
typedef void(XMLCALL * XML_StartDoctypeDeclHandler) (void *userData, const XML_Char *doctypeName, const XML_Char *sysid, const XML_Char *pubid, int has_internal_subset)
XML_StartElementHandler
typedef void(XMLCALL * XML_StartElementHandler) (void *userData, const XML_Char *name, const XML_Char **atts)
XML_StartNamespaceDeclHandler
typedef void(XMLCALL * XML_StartNamespaceDeclHandler) (void *userData, const XML_Char *prefix, const XML_Char *uri)
XML_UnknownEncodingHandler
typedef int(XMLCALL * XML_UnknownEncodingHandler) (void *encodingHandlerData, const XML_Char *name, XML_Encoding *info)
XML_UnparsedEntityDeclHandler
typedef void(XMLCALL * XML_UnparsedEntityDeclHandler) (void *userData, const XML_Char *entityName, const XML_Char *base, const XML_Char *systemId, const XML_Char *publicId, const XML_Char *notationName)
XML_XmlDeclHandler
typedef void(XMLCALL * XML_XmlDeclHandler) (void *userData, const XML_Char *version, const XML_Char *encoding, int standalone)
Enumeration Type Documentation
XML_Content_Quant
enum XML_Content_Quant
Enumerator
XML_CQUANT_NONE
XML_CQUANT_OPT
XML_CQUANT_REP
XML_CQUANT_PLUS
                       {
  XML_CQUANT_NONE,
  XML_CQUANT_OPT,
  XML_CQUANT_REP,
  XML_CQUANT_PLUS
};
XML_Content_Type
enum XML_Content_Type
Enumerator
XML_CTYPE_EMPTY
XML_CTYPE_ANY
XML_CTYPE_MIXED
XML_CTYPE_NAME
XML_CTYPE_CHOICE
XML_CTYPE_SEQ
                      {
  XML_CTYPE_EMPTY = 1,
  XML_CTYPE_ANY,
  XML_CTYPE_MIXED,
  XML_CTYPE_NAME,
  XML_CTYPE_CHOICE,
  XML_CTYPE_SEQ
};
XML_Error
enum XML_Error
Enumerator
XML_ERROR_NONE
XML_ERROR_NO_MEMORY
XML_ERROR_SYNTAX
XML_ERROR_NO_ELEMENTS
XML_ERROR_INVALID_TOKEN
XML_ERROR_UNCLOSED_TOKEN
XML_ERROR_PARTIAL_CHAR
XML_ERROR_TAG_MISMATCH
XML_ERROR_DUPLICATE_ATTRIBUTE
XML_ERROR_JUNK_AFTER_DOC_ELEMENT
XML_ERROR_PARAM_ENTITY_REF
XML_ERROR_UNDEFINED_ENTITY
XML_ERROR_RECURSIVE_ENTITY_REF
XML_ERROR_ASYNC_ENTITY
XML_ERROR_BAD_CHAR_REF
XML_ERROR_BINARY_ENTITY_REF
XML_ERROR_ATTRIBUTE_EXTERNAL_ENTITY_REF
XML_ERROR_MISPLACED_XML_PI
XML_ERROR_UNKNOWN_ENCODING
XML_ERROR_INCORRECT_ENCODING
XML_ERROR_UNCLOSED_CDATA_SECTION
XML_ERROR_EXTERNAL_ENTITY_HANDLING
XML_ERROR_NOT_STANDALONE
XML_ERROR_UNEXPECTED_STATE
XML_ERROR_ENTITY_DECLARED_IN_PE
XML_ERROR_FEATURE_REQUIRES_XML_DTD
XML_ERROR_CANT_CHANGE_FEATURE_ONCE_PARSING
XML_ERROR_UNBOUND_PREFIX
XML_ERROR_UNDECLARING_PREFIX
XML_ERROR_INCOMPLETE_PE
XML_ERROR_XML_DECL
XML_ERROR_TEXT_DECL
XML_ERROR_PUBLICID
XML_ERROR_SUSPENDED
XML_ERROR_NOT_SUSPENDED
XML_ERROR_ABORTED
XML_ERROR_FINISHED
XML_ERROR_SUSPEND_PE
XML_ERROR_RESERVED_PREFIX_XML
XML_ERROR_RESERVED_PREFIX_XMLNS
XML_ERROR_RESERVED_NAMESPACE_URI
               {
  XML_ERROR_NONE,
  XML_ERROR_NO_MEMORY,
  XML_ERROR_SYNTAX,
  XML_ERROR_NO_ELEMENTS,
  XML_ERROR_INVALID_TOKEN,
  XML_ERROR_UNCLOSED_TOKEN,
  XML_ERROR_PARTIAL_CHAR,
  XML_ERROR_TAG_MISMATCH,
  XML_ERROR_DUPLICATE_ATTRIBUTE,
  XML_ERROR_JUNK_AFTER_DOC_ELEMENT,
  XML_ERROR_PARAM_ENTITY_REF,
  XML_ERROR_UNDEFINED_ENTITY,
  XML_ERROR_RECURSIVE_ENTITY_REF,
  XML_ERROR_ASYNC_ENTITY,
  XML_ERROR_BAD_CHAR_REF,
  XML_ERROR_BINARY_ENTITY_REF,
  XML_ERROR_ATTRIBUTE_EXTERNAL_ENTITY_REF,
  XML_ERROR_MISPLACED_XML_PI,
  XML_ERROR_UNKNOWN_ENCODING,
  XML_ERROR_INCORRECT_ENCODING,
  XML_ERROR_UNCLOSED_CDATA_SECTION,
  XML_ERROR_EXTERNAL_ENTITY_HANDLING,
  XML_ERROR_NOT_STANDALONE,
  XML_ERROR_UNEXPECTED_STATE,
  XML_ERROR_ENTITY_DECLARED_IN_PE,
  XML_ERROR_FEATURE_REQUIRES_XML_DTD,
  XML_ERROR_CANT_CHANGE_FEATURE_ONCE_PARSING,
  /* Added in 1.95.7. */
  XML_ERROR_UNBOUND_PREFIX,
  /* Added in 1.95.8. */
  XML_ERROR_UNDECLARING_PREFIX,
  XML_ERROR_INCOMPLETE_PE,
  XML_ERROR_XML_DECL,
  XML_ERROR_TEXT_DECL,
  XML_ERROR_PUBLICID,
  XML_ERROR_SUSPENDED,
  XML_ERROR_NOT_SUSPENDED,
  XML_ERROR_ABORTED,
  XML_ERROR_FINISHED,
  XML_ERROR_SUSPEND_PE,
  /* Added in 2.0. */
  XML_ERROR_RESERVED_PREFIX_XML,
  XML_ERROR_RESERVED_PREFIX_XMLNS,
  XML_ERROR_RESERVED_NAMESPACE_URI
};
XML_FeatureEnum
enum XML_FeatureEnum
Enumerator
XML_FEATURE_END
XML_FEATURE_UNICODE
XML_FEATURE_UNICODE_WCHAR_T
XML_FEATURE_DTD
XML_FEATURE_CONTEXT_BYTES
XML_FEATURE_MIN_SIZE
XML_FEATURE_SIZEOF_XML_CHAR
XML_FEATURE_SIZEOF_XML_LCHAR
XML_FEATURE_NS
XML_FEATURE_LARGE_SIZE
XML_FEATURE_ATTR_INFO
                     {
  XML_FEATURE_END = 0,
  XML_FEATURE_UNICODE,
  XML_FEATURE_UNICODE_WCHAR_T,
  XML_FEATURE_DTD,
  XML_FEATURE_CONTEXT_BYTES,
  XML_FEATURE_MIN_SIZE,
  XML_FEATURE_SIZEOF_XML_CHAR,
  XML_FEATURE_SIZEOF_XML_LCHAR,
  XML_FEATURE_NS,
  XML_FEATURE_LARGE_SIZE,
  XML_FEATURE_ATTR_INFO
  /* Additional features must be added to the end of this enum. */
};
XML_ParamEntityParsing
enum XML_ParamEntityParsing
Enumerator
XML_PARAM_ENTITY_PARSING_NEVER
XML_PARAM_ENTITY_PARSING_UNLESS_STANDALONE
XML_PARAM_ENTITY_PARSING_ALWAYS
{
  XML_PARAM_ENTITY_PARSING_NEVER,
  XML_PARAM_ENTITY_PARSING_UNLESS_STANDALONE,
  XML_PARAM_ENTITY_PARSING_ALWAYS
};
XML_Parsing
enum XML_Parsing
Enumerator
XML_INITIALIZED
XML_PARSING
XML_FINISHED
XML_SUSPENDED
                 {
  XML_INITIALIZED,
  XML_PARSING,
  XML_FINISHED,
  XML_SUSPENDED
};
XML_Status
enum XML_Status
Enumerator
XML_STATUS_ERROR
XML_STATUS_ERROR
XML_STATUS_OK
XML_STATUS_OK
XML_STATUS_SUSPENDED
                {
  XML_STATUS_ERROR = 0,
#define XML_STATUS_ERROR XML_STATUS_ERROR
  XML_STATUS_OK = 1,
#define XML_STATUS_OK XML_STATUS_OK
  XML_STATUS_SUSPENDED = 2
#define XML_STATUS_SUSPENDED XML_STATUS_SUSPENDED
};
Function Documentation
XML_DefaultCurrent()
XML_DefaultCurrent (XML_Parser parser)
{
  if (defaultHandler) {
    if (openInternalEntities)
      reportDefault(parser,
                    internalEncoding,
                    openInternalEntities->internalEventPtr,
                    openInternalEntities->internalEventEndPtr);
    else
      reportDefault(parser, encoding, eventPtr, eventEndPtr);
  }
}
References defaultHandler, eventEndPtr, eventPtr, internalEncoding, openInternalEntities, and reportDefault().
XML_ErrorString()
XML_ErrorString (enum XML_Error code)
{
  static const XML_LChar* const message[] = {
    0,
    XML_L("out of memory"),
    XML_L("syntax error"),
    XML_L("no element found"),
    XML_L("not well-formed (invalid token)"),
    XML_L("unclosed token"),
    XML_L("partial character"),
    XML_L("mismatched tag"),
    XML_L("duplicate attribute"),
    XML_L("junk after document element"),
    XML_L("illegal parameter entity reference"),
    XML_L("undefined entity"),
    XML_L("recursive entity reference"),
    XML_L("asynchronous entity"),
    XML_L("reference to invalid character number"),
    XML_L("reference to binary entity"),
    XML_L("reference to external entity in attribute"),
    XML_L("XML or text declaration not at start of entity"),
    XML_L("unknown encoding"),
    XML_L("encoding specified in XML declaration is incorrect"),
    XML_L("unclosed CDATA section"),
    XML_L("error in processing external entity reference"),
    XML_L("document is not standalone"),
    XML_L("unexpected parser state - please send a bug report"),
    XML_L("entity declared in parameter entity"),
    XML_L("requested feature requires XML_DTD support in Expat"),
    XML_L("cannot change setting once parsing has begun"),
    XML_L("unbound prefix"),
    XML_L("must not undeclare prefix"),
    XML_L("incomplete markup in parameter entity"),
    XML_L("XML declaration not well-formed"),
    XML_L("text declaration not well-formed"),
    XML_L("illegal character(s) in public id"),
    XML_L("parser suspended"),
    XML_L("parser not suspended"),
    XML_L("parsing aborted"),
    XML_L("parsing finished"),
    XML_L("cannot suspend in external parameter entity"),
    XML_L("reserved prefix (xml) must not be undeclared or bound to another namespace name"),
    XML_L("reserved prefix (xmlns) must not be declared or undeclared"),
    XML_L("prefix must not be bound to one of the reserved namespace names")
  };
  if (code > 0 && code < sizeof(message)/sizeof(message[0]))
    return message[code];
  return NULL;
}
References NULL, and XML_L.
Referenced by Slic3r::_3MF_Importer::_extract_model_config_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_xml_from_archive(), Slic3r::AMFParserContext::error_message(), Slic3r::_BBS_3MF_Importer::ObjectImporter::object_parse_error_message(), Slic3r::_3MF_Importer::parse_error_message(), and Slic3r::_BBS_3MF_Importer::parse_error_message().
XML_ExpatVersion()
XML_ExpatVersion (void)
                       {
  /* V1 is used to string-ize the version number. However, it would
     string-ize the actual version macro *names* unless we get them
     substituted before being passed to V1. CPP is defined to expand
     a macro, then rescan for more expansions. Thus, we use V2 to expand
     the version macros, then CPP will expand the resulting V1() macro
     with the correct numerals. */
  /* ### I'm assuming cpp is portable in this respect... */
#define V1(a,b,c) XML_L(#a)XML_L(".")XML_L(#b)XML_L(".")XML_L(#c)
#define V2(a,b,c) XML_L("expat_")V1(a,b,c)
  return V2(XML_MAJOR_VERSION, XML_MINOR_VERSION, XML_MICRO_VERSION);
#undef V1
#undef V2
}
References V2, XML_MAJOR_VERSION, XML_MICRO_VERSION, and XML_MINOR_VERSION.
XML_ExpatVersionInfo()
XML_ExpatVersionInfo (void)
{
  XML_Expat_Version version;
  version.major = XML_MAJOR_VERSION;
  version.minor = XML_MINOR_VERSION;
  version.micro = XML_MICRO_VERSION;
  return version;
}
References XML_Expat_Version::major, XML_Expat_Version::micro, XML_Expat_Version::minor, XML_MAJOR_VERSION, XML_MICRO_VERSION, and XML_MINOR_VERSION.
XML_ExternalEntityParserCreate()
XML_ExternalEntityParserCreate (XML_Parser parser, const XML_Char * context, const XML_Char * encoding)
{
  XML_Parser parser = oldParser;
  DTD *newDtd = NULL;
  DTD *oldDtd = _dtd;
  XML_StartElementHandler oldStartElementHandler = startElementHandler;
  XML_EndElementHandler oldEndElementHandler = endElementHandler;
  XML_CharacterDataHandler oldCharacterDataHandler = characterDataHandler;
  XML_ProcessingInstructionHandler oldProcessingInstructionHandler
      = processingInstructionHandler;
  XML_CommentHandler oldCommentHandler = commentHandler;
  XML_StartCdataSectionHandler oldStartCdataSectionHandler
      = startCdataSectionHandler;
  XML_EndCdataSectionHandler oldEndCdataSectionHandler
      = endCdataSectionHandler;
  XML_DefaultHandler oldDefaultHandler = defaultHandler;
  XML_UnparsedEntityDeclHandler oldUnparsedEntityDeclHandler
      = unparsedEntityDeclHandler;
  XML_NotationDeclHandler oldNotationDeclHandler = notationDeclHandler;
  XML_StartNamespaceDeclHandler oldStartNamespaceDeclHandler
      = startNamespaceDeclHandler;
  XML_EndNamespaceDeclHandler oldEndNamespaceDeclHandler
      = endNamespaceDeclHandler;
  XML_NotStandaloneHandler oldNotStandaloneHandler = notStandaloneHandler;
  XML_ExternalEntityRefHandler oldExternalEntityRefHandler
      = externalEntityRefHandler;
  XML_SkippedEntityHandler oldSkippedEntityHandler = skippedEntityHandler;
  XML_UnknownEncodingHandler oldUnknownEncodingHandler
      = unknownEncodingHandler;
  XML_ElementDeclHandler oldElementDeclHandler = elementDeclHandler;
  XML_AttlistDeclHandler oldAttlistDeclHandler = attlistDeclHandler;
  XML_EntityDeclHandler oldEntityDeclHandler = entityDeclHandler;
  XML_XmlDeclHandler oldXmlDeclHandler = xmlDeclHandler;
  ELEMENT_TYPE * oldDeclElementType = declElementType;
  void *oldUserData = userData;
  void *oldHandlerArg = handlerArg;
  XML_Bool oldDefaultExpandInternalEntities = defaultExpandInternalEntities;
  XML_Parser oldExternalEntityRefHandlerArg = externalEntityRefHandlerArg;
#ifdef XML_DTD
  enum XML_ParamEntityParsing oldParamEntityParsing = paramEntityParsing;
  int oldInEntityValue = prologState.inEntityValue;
#endif
  XML_Bool oldns_triplets = ns_triplets;
  /* Note that the new parser shares the same hash secret as the old
     parser, so that dtdCopy and copyEntityTable can lookup values
     from hash tables associated with either parser without us having
     to worry which hash secrets each table has.
  */
  unsigned long oldhash_secret_salt = hash_secret_salt;
#ifdef XML_DTD
  if (!context)
    newDtd = oldDtd;
#endif /* XML_DTD */
  /* Note that the magical uses of the pre-processor to make field
     access look more like C++ require that `parser' be overwritten
     here.  This makes this function more painful to follow than it
     would be otherwise.
  */
  if (ns) {
    XML_Char tmp[2];
    *tmp = namespaceSeparator;
    parser = parserCreate(encodingName, &parser->m_mem, tmp, newDtd);
  }
  else {
    parser = parserCreate(encodingName, &parser->m_mem, NULL, newDtd);
  }
  if (!parser)
    return NULL;
  startElementHandler = oldStartElementHandler;
  endElementHandler = oldEndElementHandler;
  characterDataHandler = oldCharacterDataHandler;
  processingInstructionHandler = oldProcessingInstructionHandler;
  commentHandler = oldCommentHandler;
  startCdataSectionHandler = oldStartCdataSectionHandler;
  endCdataSectionHandler = oldEndCdataSectionHandler;
  defaultHandler = oldDefaultHandler;
  unparsedEntityDeclHandler = oldUnparsedEntityDeclHandler;
  notationDeclHandler = oldNotationDeclHandler;
  startNamespaceDeclHandler = oldStartNamespaceDeclHandler;
  endNamespaceDeclHandler = oldEndNamespaceDeclHandler;
  notStandaloneHandler = oldNotStandaloneHandler;
  externalEntityRefHandler = oldExternalEntityRefHandler;
  skippedEntityHandler = oldSkippedEntityHandler;
  unknownEncodingHandler = oldUnknownEncodingHandler;
  elementDeclHandler = oldElementDeclHandler;
  attlistDeclHandler = oldAttlistDeclHandler;
  entityDeclHandler = oldEntityDeclHandler;
  xmlDeclHandler = oldXmlDeclHandler;
  declElementType = oldDeclElementType;
  userData = oldUserData;
  if (oldUserData == oldHandlerArg)
    handlerArg = userData;
  else
    handlerArg = parser;
  if (oldExternalEntityRefHandlerArg != oldParser)
    externalEntityRefHandlerArg = oldExternalEntityRefHandlerArg;
  defaultExpandInternalEntities = oldDefaultExpandInternalEntities;
  ns_triplets = oldns_triplets;
  hash_secret_salt = oldhash_secret_salt;
  parentParser = oldParser;
#ifdef XML_DTD
  paramEntityParsing = oldParamEntityParsing;
  prologState.inEntityValue = oldInEntityValue;
  if (context) {
#endif /* XML_DTD */
    if (!dtdCopy(oldParser, _dtd, oldDtd, &parser->m_mem)
      || !setContext(parser, context)) {
      XML_ParserFree(parser);
      return NULL;
    }
    processor = externalEntityInitProcessor;
#ifdef XML_DTD
  }
  else {
    /* The DTD instance referenced by _dtd is shared between the document's
       root parser and external PE parsers, therefore one does not need to
       call setContext. In addition, one also *must* not call setContext,
       because this would overwrite existing prefix->binding pointers in
       _dtd with ones that get destroyed with the external PE parser.
       This would leave those prefixes with dangling pointers.
    */
    isParamEntity = XML_TRUE;
    XmlPrologStateInitExternalEntity(&prologState);
    processor = externalParEntInitProcessor;
  }
#endif /* XML_DTD */
  return parser;
}
References _dtd, attlistDeclHandler, characterDataHandler, commentHandler, declElementType, defaultExpandInternalEntities, defaultHandler, dtdCopy(), elementDeclHandler, endCdataSectionHandler, endElementHandler, endNamespaceDeclHandler, entityDeclHandler, externalEntityInitProcessor, externalEntityRefHandler, externalEntityRefHandlerArg, externalParEntInitProcessor, handlerArg, hash_secret_salt, isParamEntity, XML_ParserStruct::m_mem, namespaceSeparator, notationDeclHandler, notStandaloneHandler, ns, ns_triplets, NULL, paramEntityParsing, parentParser, parserCreate(), processingInstructionHandler, processor, prologState, setContext(), skippedEntityHandler, startCdataSectionHandler, startElementHandler, startNamespaceDeclHandler, unknownEncodingHandler, unparsedEntityDeclHandler, userData, XML_ParserFree(), XML_TRUE, xmlDeclHandler, and XmlPrologStateInitExternalEntity().
XML_FreeContentModel()
XML_FreeContentModel (XML_Parser parser, XML_Content * model)
{
  FREE(model);
}
References FREE.
XML_GetBase()
XML_GetBase (XML_Parser parser)
{
  return curBase;
}
References curBase.
XML_GetBuffer()
XML_GetBuffer (XML_Parser parser, int len)
{
  if (len < 0) {
    errorCode = XML_ERROR_NO_MEMORY;
    return NULL;
  }
  switch (ps_parsing) {
  case XML_SUSPENDED:
    errorCode = XML_ERROR_SUSPENDED;
    return NULL;
  case XML_FINISHED:
    errorCode = XML_ERROR_FINISHED;
    return NULL;
  default: ;
  }
  if (len > bufferLim - bufferEnd) {
#ifdef XML_CONTEXT_BYTES
    int keep;
#endif  /* defined XML_CONTEXT_BYTES */
    /* Do not invoke signed arithmetic overflow: */
    int neededSize = (int) ((unsigned)len + (unsigned)(bufferEnd - bufferPtr));
    if (neededSize < 0) {
      errorCode = XML_ERROR_NO_MEMORY;
      return NULL;
    }
#ifdef XML_CONTEXT_BYTES
    keep = (int)(bufferPtr - buffer);
    if (keep > XML_CONTEXT_BYTES)
      keep = XML_CONTEXT_BYTES;
    neededSize += keep;
#endif  /* defined XML_CONTEXT_BYTES */
    if (neededSize  <= bufferLim - buffer) {
#ifdef XML_CONTEXT_BYTES
      if (keep < bufferPtr - buffer) {
        int offset = (int)(bufferPtr - buffer) - keep;
        memmove(buffer, &buffer[offset], bufferEnd - bufferPtr + keep);
        bufferEnd -= offset;
        bufferPtr -= offset;
      }
#else
      memmove(buffer, bufferPtr, bufferEnd - bufferPtr);
      bufferEnd = buffer + (bufferEnd - bufferPtr);
      bufferPtr = buffer;
#endif  /* not defined XML_CONTEXT_BYTES */
    }
    else {
      char *newBuf;
      int bufferSize = (int)(bufferLim - bufferPtr);
      if (bufferSize == 0)
        bufferSize = INIT_BUFFER_SIZE;
      do {
        /* Do not invoke signed arithmetic overflow: */
        bufferSize = (int) (2U * (unsigned) bufferSize);
      } while (bufferSize < neededSize && bufferSize > 0);
      if (bufferSize <= 0) {
        errorCode = XML_ERROR_NO_MEMORY;
        return NULL;
      }
      newBuf = (char *)MALLOC(bufferSize);
      if (newBuf == 0) {
        errorCode = XML_ERROR_NO_MEMORY;
        return NULL;
      }
      bufferLim = newBuf + bufferSize;
#ifdef XML_CONTEXT_BYTES
      if (bufferPtr) {
        int keep = (int)(bufferPtr - buffer);
        if (keep > XML_CONTEXT_BYTES)
          keep = XML_CONTEXT_BYTES;
        memcpy(newBuf, &bufferPtr[-keep], bufferEnd - bufferPtr + keep);
        FREE(buffer);
        buffer = newBuf;
        bufferEnd = buffer + (bufferEnd - bufferPtr) + keep;
        bufferPtr = buffer + keep;
      }
      else {
        bufferEnd = newBuf + (bufferEnd - bufferPtr);
        bufferPtr = buffer = newBuf;
      }
#else
      if (bufferPtr) {
        memcpy(newBuf, bufferPtr, bufferEnd - bufferPtr);
        FREE(buffer);
      }
      bufferEnd = newBuf + (bufferEnd - bufferPtr);
      bufferPtr = buffer = newBuf;
#endif  /* not defined XML_CONTEXT_BYTES */
    }
    eventPtr = eventEndPtr = NULL;
    positionPtr = NULL;
  }
  return bufferEnd;
}
References buffer, bufferEnd, bufferLim, bufferPtr, errorCode, eventEndPtr, eventPtr, FREE, INIT_BUFFER_SIZE, int, MALLOC, memcpy, memmove, NULL, positionPtr, ps_parsing, XML_CONTEXT_BYTES, XML_ERROR_FINISHED, XML_ERROR_NO_MEMORY, XML_ERROR_SUSPENDED, XML_FINISHED, and XML_SUSPENDED.
Referenced by Slic3r::_3MF_Importer::_extract_model_config_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_xml_from_archive(), Slic3r::PrusaFileParser::check_3mf_from_prusa(), and XML_Parse().
XML_GetCurrentByteCount()
XML_GetCurrentByteCount (XML_Parser parser)
{
  if (eventEndPtr && eventPtr)
    return (int)(eventEndPtr - eventPtr);
  return 0;
}
References eventEndPtr, and eventPtr.
XML_GetErrorCode()
XML_GetErrorCode (XML_Parser parser)
{
  return errorCode;
}
References errorCode.
Referenced by Slic3r::_3MF_Importer::_extract_model_config_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_xml_from_archive(), Slic3r::AMFParserContext::error_message(), Slic3r::_BBS_3MF_Importer::ObjectImporter::object_parse_error_message(), Slic3r::_3MF_Importer::parse_error_message(), and Slic3r::_BBS_3MF_Importer::parse_error_message().
XML_GetFeatureList()
XML_GetFeatureList (void)
{
  static const XML_Feature features[] = {
    {XML_FEATURE_SIZEOF_XML_CHAR,  XML_L("sizeof(XML_Char)"),
     sizeof(XML_Char)},
    {XML_FEATURE_SIZEOF_XML_LCHAR, XML_L("sizeof(XML_LChar)"),
     sizeof(XML_LChar)},
#ifdef XML_UNICODE
    {XML_FEATURE_UNICODE,          XML_L("XML_UNICODE"), 0},
#endif
#ifdef XML_UNICODE_WCHAR_T
    {XML_FEATURE_UNICODE_WCHAR_T,  XML_L("XML_UNICODE_WCHAR_T"), 0},
#endif
#ifdef XML_DTD
    {XML_FEATURE_DTD,              XML_L("XML_DTD"), 0},
#endif
#ifdef XML_CONTEXT_BYTES
    {XML_FEATURE_CONTEXT_BYTES,    XML_L("XML_CONTEXT_BYTES"),
     XML_CONTEXT_BYTES},
#endif
#ifdef XML_MIN_SIZE
    {XML_FEATURE_MIN_SIZE,         XML_L("XML_MIN_SIZE"), 0},
#endif
#ifdef XML_NS
    {XML_FEATURE_NS,               XML_L("XML_NS"), 0},
#endif
#ifdef XML_LARGE_SIZE
    {XML_FEATURE_LARGE_SIZE,       XML_L("XML_LARGE_SIZE"), 0},
#endif
#ifdef XML_ATTR_INFO
    {XML_FEATURE_ATTR_INFO,        XML_L("XML_ATTR_INFO"), 0},
#endif
    {XML_FEATURE_END,              NULL, 0}
  };
  return features;
}
References NULL, XML_CONTEXT_BYTES, XML_FEATURE_ATTR_INFO, XML_FEATURE_CONTEXT_BYTES, XML_FEATURE_DTD, XML_FEATURE_END, XML_FEATURE_LARGE_SIZE, XML_FEATURE_MIN_SIZE, XML_FEATURE_NS, XML_FEATURE_SIZEOF_XML_CHAR, XML_FEATURE_SIZEOF_XML_LCHAR, XML_FEATURE_UNICODE, XML_FEATURE_UNICODE_WCHAR_T, and XML_L.
XML_GetIdAttributeIndex()
XML_GetIdAttributeIndex (XML_Parser parser)
{
  return idAttIndex;
}
References idAttIndex.
XML_GetInputContext()
XML_GetInputContext (XML_Parser parser, int * offset, int * size)
{
#ifdef XML_CONTEXT_BYTES
  if (eventPtr && buffer) {
    *offset = (int)(eventPtr - buffer);
    *size   = (int)(bufferEnd - buffer);
    return buffer;
  }
#endif /* defined XML_CONTEXT_BYTES */
  return (char *) 0;
}
References buffer, bufferEnd, eventPtr, int, and size.
XML_GetParsingStatus()
XML_GetParsingStatus (XML_Parser parser, XML_ParsingStatus * status)
{
  assert(status != NULL);
  *status = parser->m_parsingStatus;
}
References XML_ParserStruct::m_parsingStatus, and NULL.
XML_GetSpecifiedAttributeCount()
XML_GetSpecifiedAttributeCount (XML_Parser parser)
{
  return nSpecifiedAtts;
}
References nSpecifiedAtts.
Referenced by Slic3r::_BBS_3MF_Importer::ObjectImporter::_handle_object_start_model_xml_element(), Slic3r::_3MF_Importer::_handle_start_config_xml_element(), Slic3r::_BBS_3MF_Importer::_handle_start_config_xml_element(), Slic3r::_3MF_Importer::_handle_start_model_xml_element(), Slic3r::_BBS_3MF_Importer::_handle_start_model_xml_element(), Slic3r::_BBS_3MF_Importer::_handle_start_relationships_element(), and Slic3r::PrusaFileParser::_start_element_handler().
XML_MemFree()
XML_MemFree (XML_Parser parser, void * ptr)
{
  FREE(ptr);
}
References FREE, and ptr.
XML_MemMalloc()
XML_ATTR_MALLOC XML_MemMalloc (XML_Parser parser, size_t size)
{
  return MALLOC(size);
}
References MALLOC, and size.
XML_MemRealloc()
XML_MemRealloc (XML_Parser parser, void * ptr, size_t size)
{
  return REALLOC(ptr, size);
}
References ptr, REALLOC, and size.
XML_Parse()
XML_Parse (XML_Parser parser, const char * s, int len, int isFinal)
{
  switch (ps_parsing) {
  case XML_SUSPENDED:
    errorCode = XML_ERROR_SUSPENDED;
    return XML_STATUS_ERROR;
  case XML_FINISHED:
    errorCode = XML_ERROR_FINISHED;
    return XML_STATUS_ERROR;
  case XML_INITIALIZED:
    if (parentParser == NULL && !startParsing(parser)) {
      errorCode = XML_ERROR_NO_MEMORY;
      return XML_STATUS_ERROR;
    }
  default:
    ps_parsing = XML_PARSING;
  }
  if (len == 0) {
    ps_finalBuffer = (XML_Bool)isFinal;
    if (!isFinal)
      return XML_STATUS_OK;
    positionPtr = bufferPtr;
    parseEndPtr = bufferEnd;
    /* If data are left over from last buffer, and we now know that these
       data are the final chunk of input, then we have to check them again
       to detect errors based on that fact.
    */
    errorCode = processor(parser, bufferPtr, parseEndPtr, &bufferPtr);
    if (errorCode == XML_ERROR_NONE) {
      switch (ps_parsing) {
      case XML_SUSPENDED:
        XmlUpdatePosition(encoding, positionPtr, bufferPtr, &position);
        positionPtr = bufferPtr;
        return XML_STATUS_SUSPENDED;
      case XML_INITIALIZED:
      case XML_PARSING:
        ps_parsing = XML_FINISHED;
        /* fall through */
      default:
        return XML_STATUS_OK;
      }
    }
    eventEndPtr = eventPtr;
    processor = errorProcessor;
    return XML_STATUS_ERROR;
  }
#ifndef XML_CONTEXT_BYTES
  else if (bufferPtr == bufferEnd) {
    const char *end;
    int nLeftOver;
    enum XML_Status result;
    parseEndByteIndex += len;
    positionPtr = s;
    ps_finalBuffer = (XML_Bool)isFinal;
    errorCode = processor(parser, s, parseEndPtr = s + len, &end);
    if (errorCode != XML_ERROR_NONE) {
      eventEndPtr = eventPtr;
      processor = errorProcessor;
      return XML_STATUS_ERROR;
    }
    else {
      switch (ps_parsing) {
      case XML_SUSPENDED:
        result = XML_STATUS_SUSPENDED;
        break;
      case XML_INITIALIZED:
      case XML_PARSING:
        if (isFinal) {
          ps_parsing = XML_FINISHED;
          return XML_STATUS_OK;
        }
      /* fall through */
      default:
        result = XML_STATUS_OK;
      }
    }
    XmlUpdatePosition(encoding, positionPtr, end, &position);
    nLeftOver = s + len - end;
    if (nLeftOver) {
      if (buffer == NULL || nLeftOver > bufferLim - buffer) {
        /* FIXME avoid integer overflow */
        char *temp;
        temp = (buffer == NULL
                ? (char *)MALLOC(len * 2)
                : (char *)REALLOC(buffer, len * 2));
        if (temp == NULL) {
          errorCode = XML_ERROR_NO_MEMORY;
          eventPtr = eventEndPtr = NULL;
          processor = errorProcessor;
          return XML_STATUS_ERROR;
        }
        buffer = temp;
        bufferLim = buffer + len * 2;
      }
      memcpy(buffer, end, nLeftOver);
    }
    bufferPtr = buffer;
    bufferEnd = buffer + nLeftOver;
    positionPtr = bufferPtr;
    parseEndPtr = bufferEnd;
    eventPtr = bufferPtr;
    eventEndPtr = bufferPtr;
    return result;
  }
#endif  /* not defined XML_CONTEXT_BYTES */
  else {
    void *buff = XML_GetBuffer(parser, len);
    if (buff == NULL)
      return XML_STATUS_ERROR;
    else {
      memcpy(buff, s, len);
      return XML_ParseBuffer(parser, len, isFinal);
    }
  }
}
References buffer, bufferEnd, bufferLim, bufferPtr, end, errorCode, errorProcessor, eventEndPtr, eventPtr, MALLOC, memcpy, NULL, parentParser, parseEndByteIndex, parseEndPtr, positionPtr, processor, ps_finalBuffer, ps_parsing, REALLOC, startParsing(), XML_ERROR_FINISHED, XML_ERROR_NO_MEMORY, XML_ERROR_NONE, XML_ERROR_SUSPENDED, XML_FINISHED, XML_GetBuffer(), XML_INITIALIZED, XML_ParseBuffer(), XML_PARSING, XML_STATUS_ERROR, XML_STATUS_OK, XML_STATUS_SUSPENDED, XML_SUSPENDED, and XmlUpdatePosition.
Referenced by Slic3r::_BBS_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::ObjectImporter::_extract_object_from_archive(), and Slic3r::load_amf_file().
XML_ParseBuffer()
XML_ParseBuffer (XML_Parser parser, int len, int isFinal)
{
  const char *start;
  enum XML_Status result = XML_STATUS_OK;
  switch (ps_parsing) {
  case XML_SUSPENDED:
    errorCode = XML_ERROR_SUSPENDED;
    return XML_STATUS_ERROR;
  case XML_FINISHED:
    errorCode = XML_ERROR_FINISHED;
    return XML_STATUS_ERROR;
  case XML_INITIALIZED:
    if (parentParser == NULL && !startParsing(parser)) {
      errorCode = XML_ERROR_NO_MEMORY;
      return XML_STATUS_ERROR;
    }
  default:
    ps_parsing = XML_PARSING;
  }
  start = bufferPtr;
  positionPtr = start;
  bufferEnd += len;
  parseEndPtr = bufferEnd;
  parseEndByteIndex += len;
  ps_finalBuffer = (XML_Bool)isFinal;
  errorCode = processor(parser, start, parseEndPtr, &bufferPtr);
  if (errorCode != XML_ERROR_NONE) {
    eventEndPtr = eventPtr;
    processor = errorProcessor;
    return XML_STATUS_ERROR;
  }
  else {
    switch (ps_parsing) {
    case XML_SUSPENDED:
      result = XML_STATUS_SUSPENDED;
      break;
    case XML_INITIALIZED:
    case XML_PARSING:
      if (isFinal) {
        ps_parsing = XML_FINISHED;
        return result;
      }
    default: ;  /* should not happen */
    }
  }
  XmlUpdatePosition(encoding, positionPtr, bufferPtr, &position);
  positionPtr = bufferPtr;
  return result;
}
References bufferEnd, bufferPtr, errorCode, errorProcessor, eventEndPtr, eventPtr, NULL, parentParser, parseEndByteIndex, parseEndPtr, positionPtr, processor, ps_finalBuffer, ps_parsing, start, startParsing(), XML_ERROR_FINISHED, XML_ERROR_NO_MEMORY, XML_ERROR_NONE, XML_ERROR_SUSPENDED, XML_FINISHED, XML_INITIALIZED, XML_PARSING, XML_STATUS_ERROR, XML_STATUS_OK, XML_STATUS_SUSPENDED, XML_SUSPENDED, and XmlUpdatePosition.
Referenced by Slic3r::_3MF_Importer::_extract_model_config_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_xml_from_archive(), Slic3r::PrusaFileParser::check_3mf_from_prusa(), and XML_Parse().
XML_ParserCreate()
XML_ParserCreate (const XML_Char * encoding)
{
  return XML_ParserCreate_MM(encodingName, NULL, NULL);
}
References NULL, and XML_ParserCreate_MM().
Referenced by Slic3r::_3MF_Importer::_extract_model_config_from_archive(), Slic3r::_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::ObjectImporter::_extract_object_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_xml_from_archive(), Slic3r::PrusaFileParser::check_3mf_from_prusa(), Slic3r::extract_model_from_archive(), and Slic3r::load_amf_file().
XML_ParserCreate_MM()
XML_ParserCreate_MM (const XML_Char * encoding, const XML_Memory_Handling_Suite * memsuite, const XML_Char * namespaceSeparator)
{
  return parserCreate(encodingName, memsuite, nameSep, NULL);
}
References NULL, and parserCreate().
Referenced by XML_ParserCreate(), and XML_ParserCreateNS().
XML_ParserCreateNS()
XML_ParserCreateNS (const XML_Char * encoding, XML_Char namespaceSeparator)
{
  XML_Char tmp[2];
  *tmp = nsSep;
  return XML_ParserCreate_MM(encodingName, NULL, tmp);
}
References NULL, and XML_ParserCreate_MM().
XML_ParserFree()
XML_ParserFree (XML_Parser parser)
{
  TAG *tagList;
  OPEN_INTERNAL_ENTITY *entityList;
  if (parser == NULL)
    return;
  /* free tagStack and freeTagList */
  tagList = tagStack;
  for (;;) {
    TAG *p;
    if (tagList == NULL) {
      if (freeTagList == NULL)
        break;
      tagList = freeTagList;
      freeTagList = NULL;
    }
    p = tagList;
    tagList = tagList->parent;
    FREE(p->buf);
    destroyBindings(p->bindings, parser);
    FREE(p);
  }
  /* free openInternalEntities and freeInternalEntities */
  entityList = openInternalEntities;
  for (;;) {
    OPEN_INTERNAL_ENTITY *openEntity;
    if (entityList == NULL) {
      if (freeInternalEntities == NULL)
        break;
      entityList = freeInternalEntities;
      freeInternalEntities = NULL;
    }
    openEntity = entityList;
    entityList = entityList->next;
    FREE(openEntity);
  }
  destroyBindings(freeBindingList, parser);
  destroyBindings(inheritedBindings, parser);
  poolDestroy(&tempPool);
  poolDestroy(&temp2Pool);
#ifdef XML_DTD
  /* external parameter entity parsers share the DTD structure
     parser->m_dtd with the root parser, so we must not destroy it
  */
  if (!isParamEntity && _dtd)
#else
  if (_dtd)
#endif /* XML_DTD */
    dtdDestroy(_dtd, (XML_Bool)!parentParser, &parser->m_mem);
  FREE((void *)atts);
#ifdef XML_ATTR_INFO
  FREE((void *)attInfo);
#endif
  FREE(groupConnector);
  FREE(buffer);
  FREE(dataBuf);
  FREE(nsAtts);
  FREE(unknownEncodingMem);
  if (unknownEncodingRelease)
    unknownEncodingRelease(unknownEncodingData);
  FREE(parser);
}
References _dtd, attInfo, atts, tag::bindings, tag::buf, buffer, dataBuf, destroyBindings(), dtdDestroy(), FREE, freeBindingList, freeInternalEntities, freeTagList, groupConnector, inheritedBindings, isParamEntity, XML_ParserStruct::m_mem, open_internal_entity::next, nsAtts, NULL, openInternalEntities, tag::parent, parentParser, poolDestroy(), tagStack, temp2Pool, tempPool, unknownEncodingData, unknownEncodingMem, and unknownEncodingRelease.
Referenced by Slic3r::_BBS_3MF_Importer::ObjectImporter::_destroy_object_xml_parser(), Slic3r::_3MF_Importer::_destroy_xml_parser(), Slic3r::_BBS_3MF_Importer::_destroy_xml_parser(), Slic3r::load_amf_file(), parserCreate(), and XML_ExternalEntityParserCreate().
XML_ParserReset()
XML_ParserReset (XML_Parser parser, const XML_Char * encoding)
{
  TAG *tStk;
  OPEN_INTERNAL_ENTITY *openEntityList;
  if (parentParser)
    return XML_FALSE;
  /* move tagStack to freeTagList */
  tStk = tagStack;
  while (tStk) {
    TAG *tag = tStk;
    tStk = tStk->parent;
    tag->parent = freeTagList;
    moveToFreeBindingList(parser, tag->bindings);
    tag->bindings = NULL;
    freeTagList = tag;
  }
  /* move openInternalEntities to freeInternalEntities */
  openEntityList = openInternalEntities;
  while (openEntityList) {
    OPEN_INTERNAL_ENTITY *openEntity = openEntityList;
    openEntityList = openEntity->next;
    openEntity->next = freeInternalEntities;
    freeInternalEntities = openEntity;
  }
  moveToFreeBindingList(parser, inheritedBindings);
  FREE(unknownEncodingMem);
  if (unknownEncodingRelease)
    unknownEncodingRelease(unknownEncodingData);
  poolClear(&tempPool);
  poolClear(&temp2Pool);
  parserInit(parser, encodingName);
  dtdReset(_dtd, &parser->m_mem);
  return XML_TRUE;
}
References _dtd, tag::bindings, dtdReset(), FREE, freeInternalEntities, freeTagList, inheritedBindings, XML_ParserStruct::m_mem, moveToFreeBindingList(), open_internal_entity::next, NULL, openInternalEntities, tag::parent, parentParser, parserInit(), poolClear(), tagStack, temp2Pool, tempPool, unknownEncodingData, unknownEncodingMem, unknownEncodingRelease, XML_FALSE, and XML_TRUE.
XML_ResumeParser()
XML_ResumeParser (XML_Parser parser)
{
  enum XML_Status result = XML_STATUS_OK;
  if (ps_parsing != XML_SUSPENDED) {
    errorCode = XML_ERROR_NOT_SUSPENDED;
    return XML_STATUS_ERROR;
  }
  ps_parsing = XML_PARSING;
  errorCode = processor(parser, bufferPtr, parseEndPtr, &bufferPtr);
  if (errorCode != XML_ERROR_NONE) {
    eventEndPtr = eventPtr;
    processor = errorProcessor;
    return XML_STATUS_ERROR;
  }
  else {
    switch (ps_parsing) {
    case XML_SUSPENDED:
      result = XML_STATUS_SUSPENDED;
      break;
    case XML_INITIALIZED:
    case XML_PARSING:
      if (ps_finalBuffer) {
        ps_parsing = XML_FINISHED;
        return result;
      }
    default: ;
    }
  }
  XmlUpdatePosition(encoding, positionPtr, bufferPtr, &position);
  positionPtr = bufferPtr;
  return result;
}
References bufferPtr, errorCode, errorProcessor, eventEndPtr, eventPtr, parseEndPtr, positionPtr, processor, ps_finalBuffer, ps_parsing, XML_ERROR_NONE, XML_ERROR_NOT_SUSPENDED, XML_FINISHED, XML_INITIALIZED, XML_PARSING, XML_STATUS_ERROR, XML_STATUS_OK, XML_STATUS_SUSPENDED, XML_SUSPENDED, and XmlUpdatePosition.
XML_SetAttlistDeclHandler()
XML_SetAttlistDeclHandler (XML_Parser parser, XML_AttlistDeclHandler attdecl)
{
  attlistDeclHandler = attdecl;
}
References attlistDeclHandler.
XML_SetBase()
XML_SetBase (XML_Parser parser, const XML_Char * base)
{
  if (p) {
    p = poolCopyString(&_dtd->pool, p);
    if (!p)
      return XML_STATUS_ERROR;
    curBase = p;
  }
  else
    curBase = NULL;
  return XML_STATUS_OK;
}
References _dtd, curBase, NULL, poolCopyString(), XML_STATUS_ERROR, and XML_STATUS_OK.
XML_SetCdataSectionHandler()
XML_SetCdataSectionHandler (XML_Parser parser, XML_StartCdataSectionHandler start, XML_EndCdataSectionHandler end)
{
  startCdataSectionHandler = start;
  endCdataSectionHandler = end;
}
References end, endCdataSectionHandler, start, and startCdataSectionHandler.
XML_SetCharacterDataHandler()
XML_SetCharacterDataHandler (XML_Parser parser, XML_CharacterDataHandler handler)
{
  characterDataHandler = handler;
}
References characterDataHandler.
Referenced by Slic3r::_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::ObjectImporter::_extract_object_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_xml_from_archive(), Slic3r::PrusaFileParser::check_3mf_from_prusa(), Slic3r::extract_model_from_archive(), and Slic3r::load_amf_file().
XML_SetCommentHandler()
XML_SetCommentHandler (XML_Parser parser, XML_CommentHandler handler)
{
  commentHandler = handler;
}
References commentHandler.
XML_SetDefaultHandler()
XML_SetDefaultHandler (XML_Parser parser, XML_DefaultHandler handler)
{
  defaultHandler = handler;
  defaultExpandInternalEntities = XML_FALSE;
}
References defaultExpandInternalEntities, defaultHandler, and XML_FALSE.
XML_SetDefaultHandlerExpand()
XML_SetDefaultHandlerExpand (XML_Parser parser, XML_DefaultHandler handler)
{
  defaultHandler = handler;
  defaultExpandInternalEntities = XML_TRUE;
}
References defaultExpandInternalEntities, defaultHandler, and XML_TRUE.
XML_SetDoctypeDeclHandler()
XML_SetDoctypeDeclHandler (XML_Parser parser, XML_StartDoctypeDeclHandler start, XML_EndDoctypeDeclHandler end)
{
  startDoctypeDeclHandler = start;
  endDoctypeDeclHandler = end;
}
References end, endDoctypeDeclHandler, start, and startDoctypeDeclHandler.
XML_SetElementDeclHandler()
XML_SetElementDeclHandler (XML_Parser parser, XML_ElementDeclHandler eldecl)
{
  elementDeclHandler = eldecl;
}
References elementDeclHandler.
XML_SetElementHandler()
XML_SetElementHandler (XML_Parser parser, XML_StartElementHandler start, XML_EndElementHandler end)
{
  startElementHandler = start;
  endElementHandler = end;
}
References end, endElementHandler, start, and startElementHandler.
Referenced by Slic3r::_3MF_Importer::_extract_model_config_from_archive(), Slic3r::_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::ObjectImporter::_extract_object_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_xml_from_archive(), Slic3r::PrusaFileParser::check_3mf_from_prusa(), Slic3r::extract_model_from_archive(), and Slic3r::load_amf_file().
XML_SetEncoding()
XML_SetEncoding (XML_Parser parser, const XML_Char * encoding)
{
  /* Block after XML_Parse()/XML_ParseBuffer() has been called.
     XXX There's no way for the caller to determine which of the
     XXX possible error cases caused the XML_STATUS_ERROR return.
  */
  if (ps_parsing == XML_PARSING || ps_parsing == XML_SUSPENDED)
    return XML_STATUS_ERROR;
  if (encodingName == NULL)
    protocolEncodingName = NULL;
  else {
    protocolEncodingName = poolCopyString(&tempPool, encodingName);
    if (!protocolEncodingName)
      return XML_STATUS_ERROR;
  }
  return XML_STATUS_OK;
}
References NULL, poolCopyString(), protocolEncodingName, ps_parsing, tempPool, XML_PARSING, XML_STATUS_ERROR, XML_STATUS_OK, and XML_SUSPENDED.
XML_SetEndCdataSectionHandler()
XML_SetEndCdataSectionHandler (XML_Parser parser, XML_EndCdataSectionHandler end)
{
  endCdataSectionHandler = end;
}
References end, and endCdataSectionHandler.
XML_SetEndDoctypeDeclHandler()
XML_SetEndDoctypeDeclHandler (XML_Parser parser, XML_EndDoctypeDeclHandler end)
{
  endDoctypeDeclHandler = end;
}
References end, and endDoctypeDeclHandler.
XML_SetEndElementHandler()
XML_SetEndElementHandler (XML_Parser parser, XML_EndElementHandler handler)
{
  endElementHandler = end;
}
References end, and endElementHandler.
XML_SetEndNamespaceDeclHandler()
XML_SetEndNamespaceDeclHandler (XML_Parser parser, XML_EndNamespaceDeclHandler end)
{
  endNamespaceDeclHandler = end;
}
References end, and endNamespaceDeclHandler.
XML_SetEntityDeclHandler()
XML_SetEntityDeclHandler (XML_Parser parser, XML_EntityDeclHandler handler)
{
  entityDeclHandler = handler;
}
References entityDeclHandler.
XML_SetExternalEntityRefHandler()
XML_SetExternalEntityRefHandler (XML_Parser parser, XML_ExternalEntityRefHandler handler)
{
  externalEntityRefHandler = handler;
}
References externalEntityRefHandler.
XML_SetExternalEntityRefHandlerArg()
XML_SetExternalEntityRefHandlerArg (XML_Parser parser, void * arg)
{
  if (arg)
    externalEntityRefHandlerArg = (XML_Parser)arg;
  else
    externalEntityRefHandlerArg = parser;
}
References arg(), and externalEntityRefHandlerArg.
XML_SetHashSalt()
XML_SetHashSalt (XML_Parser parser, unsigned long hash_salt)
{
  /* block after XML_Parse()/XML_ParseBuffer() has been called */
  if (ps_parsing == XML_PARSING || ps_parsing == XML_SUSPENDED)
    return 0;
  hash_secret_salt = hash_salt;
  return 1;
}
References hash_secret_salt, ps_parsing, XML_PARSING, and XML_SUSPENDED.
XML_SetNamespaceDeclHandler()
XML_SetNamespaceDeclHandler (XML_Parser parser, XML_StartNamespaceDeclHandler start, XML_EndNamespaceDeclHandler end)
{
  startNamespaceDeclHandler = start;
  endNamespaceDeclHandler = end;
}
References end, endNamespaceDeclHandler, start, and startNamespaceDeclHandler.
XML_SetNotationDeclHandler()
XML_SetNotationDeclHandler (XML_Parser parser, XML_NotationDeclHandler handler)
{
  notationDeclHandler = handler;
}
References notationDeclHandler.
XML_SetNotStandaloneHandler()
XML_SetNotStandaloneHandler (XML_Parser parser, XML_NotStandaloneHandler handler)
{
  notStandaloneHandler = handler;
}
References notStandaloneHandler.
XML_SetParamEntityParsing()
XML_SetParamEntityParsing (XML_Parser parser, enum XML_ParamEntityParsing parsing)
{
  /* block after XML_Parse()/XML_ParseBuffer() has been called */
  if (ps_parsing == XML_PARSING || ps_parsing == XML_SUSPENDED)
    return 0;
#ifdef XML_DTD
  paramEntityParsing = peParsing;
  return 1;
#else
  return peParsing == XML_PARAM_ENTITY_PARSING_NEVER;
#endif
}
References paramEntityParsing, ps_parsing, XML_PARAM_ENTITY_PARSING_NEVER, XML_PARSING, and XML_SUSPENDED.
XML_SetProcessingInstructionHandler()
XML_SetProcessingInstructionHandler (XML_Parser parser, XML_ProcessingInstructionHandler handler)
{
  processingInstructionHandler = handler;
}
References processingInstructionHandler.
XML_SetReturnNSTriplet()
XML_SetReturnNSTriplet (XML_Parser parser, int do_nst)
{
  /* block after XML_Parse()/XML_ParseBuffer() has been called */
  if (ps_parsing == XML_PARSING || ps_parsing == XML_SUSPENDED)
    return;
  ns_triplets = do_nst ? XML_TRUE : XML_FALSE;
}
References ns_triplets, ps_parsing, XML_FALSE, XML_PARSING, XML_SUSPENDED, and XML_TRUE.
XML_SetSkippedEntityHandler()
XML_SetSkippedEntityHandler (XML_Parser parser, XML_SkippedEntityHandler handler)
{
  skippedEntityHandler = handler;
}
References skippedEntityHandler.
XML_SetStartCdataSectionHandler()
XML_SetStartCdataSectionHandler (XML_Parser parser, XML_StartCdataSectionHandler start)
{
  startCdataSectionHandler = start;
}
References start, and startCdataSectionHandler.
XML_SetStartDoctypeDeclHandler()
XML_SetStartDoctypeDeclHandler (XML_Parser parser, XML_StartDoctypeDeclHandler start)
{
  startDoctypeDeclHandler = start;
}
References start, and startDoctypeDeclHandler.
XML_SetStartElementHandler()
XML_SetStartElementHandler (XML_Parser parser, XML_StartElementHandler handler)
{
  startElementHandler = start;
}
References start, and startElementHandler.
XML_SetStartNamespaceDeclHandler()
XML_SetStartNamespaceDeclHandler (XML_Parser parser, XML_StartNamespaceDeclHandler start)
{
  startNamespaceDeclHandler = start;
}
References start, and startNamespaceDeclHandler.
XML_SetUnknownEncodingHandler()
XML_SetUnknownEncodingHandler (XML_Parser parser, XML_UnknownEncodingHandler handler, void * encodingHandlerData)
{
  unknownEncodingHandler = handler;
  unknownEncodingHandlerData = data;
}
References unknownEncodingHandler, and unknownEncodingHandlerData.
XML_SetUnparsedEntityDeclHandler()
XML_SetUnparsedEntityDeclHandler (XML_Parser parser, XML_UnparsedEntityDeclHandler handler)
{
  unparsedEntityDeclHandler = handler;
}
References unparsedEntityDeclHandler.
XML_SetUserData()
XML_SetUserData (XML_Parser parser, void * userData)
{
  if (handlerArg == userData)
    handlerArg = userData = p;
  else
    userData = p;
}
References handlerArg, and userData.
Referenced by Slic3r::_3MF_Importer::_extract_model_config_from_archive(), Slic3r::_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_model_from_archive(), Slic3r::_BBS_3MF_Importer::ObjectImporter::_extract_object_from_archive(), Slic3r::_BBS_3MF_Importer::_extract_xml_from_archive(), Slic3r::PrusaFileParser::check_3mf_from_prusa(), Slic3r::extract_model_from_archive(), and Slic3r::load_amf_file().
XML_SetXmlDeclHandler()
XML_SetXmlDeclHandler (XML_Parser parser, XML_XmlDeclHandler xmldecl)
{
  xmlDeclHandler = handler;
}
References xmlDeclHandler.
XML_StopParser()
XML_StopParser (XML_Parser parser, XML_Bool resumable)
{
  switch (ps_parsing) {
  case XML_SUSPENDED:
    if (resumable) {
      errorCode = XML_ERROR_SUSPENDED;
      return XML_STATUS_ERROR;
    }
    ps_parsing = XML_FINISHED;
    break;
  case XML_FINISHED:
    errorCode = XML_ERROR_FINISHED;
    return XML_STATUS_ERROR;
  default:
    if (resumable) {
#ifdef XML_DTD
      if (isParamEntity) {
        errorCode = XML_ERROR_SUSPEND_PE;
        return XML_STATUS_ERROR;
      }
#endif
      ps_parsing = XML_SUSPENDED;
    }
    else
      ps_parsing = XML_FINISHED;
  }
  return XML_STATUS_OK;
}
References errorCode, isParamEntity, ps_parsing, XML_ERROR_FINISHED, XML_ERROR_SUSPEND_PE, XML_ERROR_SUSPENDED, XML_FINISHED, XML_STATUS_ERROR, XML_STATUS_OK, and XML_SUSPENDED.
Referenced by Slic3r::_BBS_3MF_Importer::ObjectImporter::_stop_object_xml_parser(), Slic3r::_3MF_Importer::_stop_xml_parser(), Slic3r::_BBS_3MF_Importer::_stop_xml_parser(), and Slic3r::AMFParserContext::stop().
XML_UseForeignDTD()
XML_UseForeignDTD (XML_Parser parser, XML_Bool useDTD)
{
#ifdef XML_DTD
  /* block after XML_Parse()/XML_ParseBuffer() has been called */
  if (ps_parsing == XML_PARSING || ps_parsing == XML_SUSPENDED)
    return XML_ERROR_CANT_CHANGE_FEATURE_ONCE_PARSING;
  useForeignDTD = useDTD;
  return XML_ERROR_NONE;
#else
  return XML_ERROR_FEATURE_REQUIRES_XML_DTD;
#endif
}
References ps_parsing, useForeignDTD, XML_ERROR_CANT_CHANGE_FEATURE_ONCE_PARSING, XML_ERROR_FEATURE_REQUIRES_XML_DTD, XML_ERROR_NONE, XML_PARSING, and XML_SUSPENDED.
XML_UseParserAsHandlerArg()
XML_UseParserAsHandlerArg (XML_Parser parser)
{
  handlerArg = parser;
}
References handlerArg.
XMLPARSEAPI() [1/2]
XMLPARSEAPI (XML_Index)
XMLPARSEAPI() [2/2]
XMLPARSEAPI (XML_Size)