OrcaSlicer: PrinterFileSystem Class Reference
PrinterFileSystem Class Reference
#include <src/slic3r/GUI/Printer/PrinterFileSystem.h>
Classes
struct File
struct Progress
struct Session
struct Thumbnail
struct Void
Public Types
enum FileType { F_TIMELAPSE , F_VIDEO }
enum GroupMode { G_NONE , G_MONTH , G_YEAR }
enum Flags { FF_SELECT = 1 , FF_THUMNAIL = 2 , FF_DOWNLOAD = 4 , FF_DELETED = 8 }
enum Status {
Initializing , Connecting , ListSyncing , ListReady ,
Failed
}
template<typename T >
using Callback = std::function< void(int, T)>
typedef std::vector< File > FileList
Public Member Functions
PrinterFileSystem ()
~PrinterFileSystem ()
void SetFileType (FileType type)
void SetGroupMode (GroupMode mode)
size_t EnterSubGroup (size_t index)
GroupMode GetFileType () const
GroupMode GetGroupMode () const
void ListAllFiles ()
void DeleteFiles (size_t index)
void DownloadFiles (size_t index, std::string const &path)
void DownloadCheckFiles (std::string const &path)
bool DownloadCheckFile (size_t index)
void DownloadCancel (size_t index)
size_t GetCount () const
size_t GetIndexAtTime (boost::uint32_t time)
void ToggleSelect (size_t index)
void SelectAll (bool select)
size_t GetSelectCount () const
void SetFocusRange (size_t start, size_t count)
File const & GetFile (size_t index)
File const & GetFile (size_t index, bool &select)
Status GetStatus () const
int GetLastError () const
void Attached ()
void Start ()
void Retry ()
void SetUrl (std::string const &url)
void Stop (bool quit=false)
Protected Attributes
FileType m_file_type = F_TIMELAPSE
GroupMode m_group_mode = G_NONE
FileList m_file_list
FileList m_file_list2
std::vector< size_t > m_group_year
std::vector< size_t > m_group_month
std::vector< int > m_group_flags
Private Types
enum {
LIST_INFO = 0x0001 , THUMBNAIL = 0x0002 , FILE_DEL = 0x0003 , FILE_DOWNLOAD = 0X0004 ,
NOTIFY_FIRST = 0x0100 , LIST_CHANGE_NOTIFY = 0x0100 , LIST_RESYNC_NOTIFY = 0x0101 , TASK_CANCEL = 0x1000
}
enum {
SUCCESS = 0 , CONTINUE = 1 , ERROR_JSON = 2 , ERROR_PIPE = 3 ,
ERROR_CANCEL = 4 , FILE_NO_EXIST = 10 , FILE_NAME_INVALID = 11 , FILE_SIZE_ERR = 12 ,
FILE_OPEN_ERR = 13 , FILE_READ_ERR = 14 , FILE_CHECK_ERR = 15
}
template<typename T >
using Translator = std::function< int(json const &, T &, unsigned char const *)>
typedef std::function< void(int, json const &resp)> callback_t
typedef std::function< void(int, json const &resp, unsigned char const *data)> callback_t2
template<typename T >
using Applier = std::function< void(T const &)>
Private Member Functions
void BuildGroups ()
void UpdateGroupSelect ()
void DeleteFilesContinue ()
void DownloadNextFile ()
void UpdateFocusThumbnail ()
void FileRemoved (size_t index, std::string const &name)
size_t FindFile (size_t index, std::string const &name)
void SendChangedEvent (wxEventType type, size_t index=(size_t) -1, std::string const &str={}, long extra=0)
template<typename T >
boost::uint32_t SendRequest (int type, json const &req, Translator< T > const &translator, Callback< T > const &callback)
template<typename T >
void InstallNotify (int type, Translator< T > const &translator, Applier< T > const &applier)
boost::uint32_t SendRequest (int type, json const &req, callback_t2 const &callback)
void InstallNotify (int type, callback_t2 const &callback)
void CancelRequest (boost::uint32_t seq)
void RecvMessageThread ()
void HandleResponse (boost::unique_lock< boost::mutex > &l, Bambu_Sample const &sample)
void Reconnect (boost::unique_lock< boost::mutex > &l, int result)
int RecvData (std::function< int(Bambu_Sample &sample)> const &callback)
template<typename T >
void PostCallback (Callback< T > const &callback, int result, T const &resp)
void PostCallback (std::function< void(void)> const &callback)
Static Private Member Functions
static void DumpLog (void *context, int level, tchar const *msg)
Private Attributes
size_t m_select_count = 0
size_t m_lock_start = 0
size_t m_lock_end = 0
int m_task_flags = 0
Session m_session
boost::uint32_t m_sequence = 0
boost::uint32_t m_download_seq = 0
std::deque< std::string > m_messages
std::deque< callback_t2 > m_callbacks
std::deque< callback_t2 > m_notifies
bool m_stopped = true
boost::mutex m_mutex
boost::condition_variable m_cond
boost::thread m_recv_thread
Status m_status
int m_last_error = 0
Static Private Attributes
static const int CTRL_TYPE = 0x3001
Detailed Description
Class Documentation
PrinterFileSystem::Progress
struct PrinterFileSystem::Progress
Class Members
wxInt64 size
wxInt64 total
PrinterFileSystem::Session
struct PrinterFileSystem::Session
Class Members
PrinterFileSystem * owner
Bambu_Tunnel tunnel = nullptr
PrinterFileSystem::Thumbnail
struct PrinterFileSystem::Thumbnail
Class Members
string name
wxBitmap thumbnail
PrinterFileSystem::Void
struct PrinterFileSystem::Void
Member Typedef Documentation
Applier
template<typename T > using PrinterFileSystem::Applier = std::function<void(T const &)> private
Callback
template<typename T > using PrinterFileSystem::Callback = std::function<void(int, T)>
callback_t
typedef std::function<void(int, json const & resp)> PrinterFileSystem::callback_t private
callback_t2
typedef std::function<void(int, json const &resp, unsigned char const *data)> PrinterFileSystem::callback_t2 private
FileList
typedef std::vector<File> PrinterFileSystem::FileList
Translator
template<typename T > using PrinterFileSystem::Translator = std::function<int(json const &, T &, unsigned char const *)> private
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
LIST_INFO
THUMBNAIL
FILE_DEL
FILE_DOWNLOAD
NOTIFY_FIRST
LIST_CHANGE_NOTIFY
LIST_RESYNC_NOTIFY
TASK_CANCEL
         {
        LIST_INFO       = 0x0001,
        THUMBNAIL       = 0x0002,
        FILE_DEL        = 0x0003,
        FILE_DOWNLOAD   = 0X0004,
        NOTIFY_FIRST    = 0x0100,
        LIST_CHANGE_NOTIFY = 0x0100,
        LIST_RESYNC_NOTIFY = 0x0101,
        TASK_CANCEL     = 0x1000
    };
anonymous enum
anonymous enum private
Enumerator
SUCCESS
CONTINUE
ERROR_JSON
ERROR_PIPE
ERROR_CANCEL
FILE_NO_EXIST
FILE_NAME_INVALID
FILE_SIZE_ERR
FILE_OPEN_ERR
FILE_READ_ERR
FILE_CHECK_ERR
         {
        SUCCESS             = 0,
        CONTINUE            = 1,
        ERROR_JSON          = 2,
        ERROR_PIPE          = 3,
        ERROR_CANCEL        = 4,
        FILE_NO_EXIST       = 10,
        FILE_NAME_INVALID   = 11,
        FILE_SIZE_ERR       = 12,
        FILE_OPEN_ERR       = 13,
        FILE_READ_ERR       = 14,
        FILE_CHECK_ERR      = 15,
    };
FileType
enum PrinterFileSystem::FileType
Enumerator
F_TIMELAPSE
F_VIDEO
                  {
        F_TIMELAPSE,
        F_VIDEO,
    };
Flags
enum PrinterFileSystem::Flags
Enumerator
FF_SELECT
FF_THUMNAIL
FF_DOWNLOAD
FF_DELETED
               {
        FF_SELECT = 1,
        FF_THUMNAIL = 2,    // Thumbnail ready
        FF_DOWNLOAD = 4,    // Request download
        FF_DELETED = 8,     // Request delete
    };
GroupMode
enum PrinterFileSystem::GroupMode
Enumerator
G_NONE
G_MONTH
G_YEAR
                   {
        G_NONE,
        G_MONTH,
        G_YEAR,
    };
Status
enum PrinterFileSystem::Status
Enumerator
Initializing
Connecting
ListSyncing
ListReady
Failed
                {
        Initializing,
        Connecting,
        ListSyncing,
        ListReady,
        Failed,
    };
Constructor & Destructor Documentation
PrinterFileSystem()
PrinterFileSystem::PrinterFileSystem ()
    : BambuLib(StaticBambuLib::get())
{
    if (!default_thumbnail.IsOk()) {
        default_thumbnail = *Slic3r::GUI::BitmapCache().load_svg("printer_file", 0, 0);
#ifdef __APPLE__
        default_thumbnail = wxBitmap(default_thumbnail.ConvertToImage(), -1, 1);
#endif
    }
    m_session.owner = this;
#ifdef PRINTER_FILE_SYSTEM_TEST
    auto time = wxDateTime::Now();
    for (int i = 0; i < 100; ++i) {
        auto name = wxString::Format(L"img-%03d.jpg", i + 1);
        wxImage im(L"D:\\work\\pic\\" + name);
        m_file_list.push_back({name.ToUTF8().data(), time.GetTicks(), 26937, i > 3 ? im : default_thumbnail, i < 20 ? FF_DOWNLOAD : 0, i * 10 - 40 - 1});
        time.Add(wxDateSpan::Days(-1));
    }
    m_file_list[0].thumbnail = default_thumbnail;
    BuildGroups();
#endif
}
References BuildGroups(), default_thumbnail, FF_DOWNLOAD, L, Slic3r::GUI::BitmapCache::load_svg(), m_file_list, m_session, and PrinterFileSystem::Session::owner.
~PrinterFileSystem()
PrinterFileSystem::~PrinterFileSystem ()
{
    m_recv_thread.detach();
}
References m_recv_thread.
Member Function Documentation
Attached()
void PrinterFileSystem::Attached ()
{
    boost::unique_lock lock(m_mutex);
    m_recv_thread = std::move(boost::thread([w = weak_from_this()] {
        boost::shared_ptr<PrinterFileSystem> s = w.lock();
        if (s) s->RecvMessageThread();
    }));
}
References m_mutex, and m_recv_thread.
BuildGroups()
void PrinterFileSystem::BuildGroups () private
{
    if (m_file_list.empty())
        return;
    m_group_year.clear();
    m_group_month.clear();
    wxDateTime t = wxDateTime((time_t) m_file_list.front().time);
    m_group_year.push_back(0);
    m_group_month.push_back(0);
    for (size_t i = 0; i < m_file_list.size(); ++i) {
        wxDateTime s = wxDateTime((time_t) m_file_list[i].time);
        if (s.GetYear() != t.GetYear()) {
            m_group_year.push_back(m_group_month.size());
            m_group_month.push_back(i);
        } else if (s.GetMonth() != t.GetMonth()) {
            m_group_month.push_back(i);
        }
        t = s;
    }
}
References m_file_list, m_group_month, and m_group_year.
Referenced by PrinterFileSystem(), and ListAllFiles().
CancelRequest()
void PrinterFileSystem::CancelRequest (boost::uint32_t seq) private
{
    json req;
    json arr;
    arr.push_back(seq);
    req["tasks"] = arr;
    SendRequest(TASK_CANCEL, req, [this](int result, json const &resp, unsigned char const *) {
        if (result != 0) return;
        json tasks = resp["tasks"];
        std::deque<callback_t2> callbacks;
        boost::unique_lock      l(m_mutex);
        for (auto &f : tasks) {
            boost::uint32_t seq = f;
            seq -= m_sequence;
            if (size_t(seq) >= m_callbacks.size()) continue;
            auto & c = m_callbacks[seq];
            if (c == nullptr) continue;
            callbacks.push_back(c);
            m_callbacks[seq] = callback_t2();
        }
        while (!m_callbacks.empty() && m_callbacks.front() == nullptr) {
            m_callbacks.pop_front();
            ++m_sequence;
        }
        l.unlock();
        for (auto &c : callbacks) c(ERROR_CANCEL, json(), nullptr);
    });
}
References ERROR_CANCEL, m_callbacks, m_mutex, m_sequence, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::push_back(), SendRequest(), and TASK_CANCEL.
Referenced by DownloadCancel().
DeleteFiles()
void PrinterFileSystem::DeleteFiles (size_t index)
{
    if (index == size_t(-1)) {
        size_t n = 0;
        for (size_t i = 0; i < m_file_list.size(); ++i) {
            auto &file = m_file_list[i];
            if ((file.flags & FF_SELECT) != 0 && (file.flags & FF_DELETED) == 0) {
                file.flags |= FF_DELETED;
                ++n;
            }
        }
        if (n == 0) return;
    } else {
        if (index >= m_file_list.size())
            return;
        auto &file = m_file_list[index];
        if ((file.flags & FF_DELETED) != 0)
            return;
        file.flags |= FF_DELETED;
    }
    if ((m_task_flags & FF_DELETED) == 0)
        DeleteFilesContinue();
}
References DeleteFilesContinue(), FF_DELETED, FF_SELECT, m_file_list, m_task_flags, and n.
DeleteFilesContinue()
void PrinterFileSystem::DeleteFilesContinue () private
{
    std::vector<size_t> indexes;
    std::vector<std::string> names;
    for (size_t i = 0; i < m_file_list.size(); ++i)
        if ((m_file_list[i].flags & FF_DELETED) && !m_file_list[i].name.empty()) {
            indexes.push_back(i);
            names.push_back(m_file_list[i].name);
            if (names.size() >= 64)
                break;
        }
    m_task_flags &= ~FF_DELETED;
    if (names.empty())
        return;
    json req;
    json arr;
    for (auto &name : names) arr.push_back(name);
    req["delete"] = arr;
    m_task_flags |= FF_DELETED;
    SendRequest<Void>(
        FILE_DEL, req, nullptr,
        [indexes, names, this](int, Void const &) {
            // TODO:
            for (size_t i = indexes.size() - 1; i != size_t(-1); --i)
                FileRemoved(indexes[i], names[i]);
            SendChangedEvent(EVT_FILE_CHANGED, indexes.size());
            DeleteFilesContinue();
        });
}
References DeleteFilesContinue(), FF_DELETED, FILE_DEL, FileRemoved(), m_file_list, m_task_flags, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::push_back(), and SendChangedEvent().
Referenced by DeleteFiles(), and DeleteFilesContinue().
DownloadCancel()
void PrinterFileSystem::DownloadCancel (size_t index)
{
    if (index == (size_t) -1) return;
    if (index >= m_file_list.size()) return;
    auto &file = m_file_list[index];
    if ((file.flags & FF_DOWNLOAD) == 0) return;
    if (file.progress >= 0)
        CancelRequest(m_download_seq);
    else
        file.flags &= ~FF_DOWNLOAD;
}
References CancelRequest(), FF_DOWNLOAD, m_download_seq, and m_file_list.
DownloadCheckFile()
bool PrinterFileSystem::DownloadCheckFile (size_t index)
{
    if (index >= m_file_list.size()) return false;
    auto &file = m_file_list[index];
    if ((file.flags & FF_DOWNLOAD) == 0) return false;
    if (!boost::filesystem::exists(file.path)) {
        file.flags &= ~FF_DOWNLOAD;
        file.progress = 0;
        file.path.clear();
        SendChangedEvent(EVT_DOWNLOAD, index, file.path);
        return false;
    }
    return true;
}
References FF_DOWNLOAD, m_file_list, and SendChangedEvent().
DownloadCheckFiles()
void PrinterFileSystem::DownloadCheckFiles (std::string const & path)
{
    for (size_t i = 0; i < m_file_list.size(); ++i) {
        auto &file = m_file_list[i];
        if ((file.flags & FF_DOWNLOAD) != 0 && file.progress >= 0) continue;
        auto path2 = boost::filesystem::path(path) / file.name;
        boost::system::error_code ec;
        if (boost::filesystem::file_size(path2, ec) == file.size) {
            file.flags |= FF_DOWNLOAD;
            file.progress = 100;
            file.path     = path2.string();
        }
    }
}
References FF_DOWNLOAD, and m_file_list.
DownloadFiles()
void PrinterFileSystem::DownloadFiles (size_t index, std::string const & path)
{
    if (index == (size_t) -1) {
        size_t n = 0;
        for (size_t i = 0; i < m_file_list.size(); ++i) {
            auto &file = m_file_list[i];
            if ((file.flags & FF_SELECT) == 0) continue;
            if ((file.flags & FF_DOWNLOAD) != 0 && file.progress >= 0) continue;
            file.flags |= FF_DOWNLOAD;
            file.progress = -1;
            file.path = (boost::filesystem::path(path) / file.name).string();
            ++n;
        }
        if (n == 0) return;
    } else {
        if (index >= m_file_list.size())
            return;
        auto &file = m_file_list[index];
        if ((file.flags & FF_DOWNLOAD) != 0 && file.progress >= 0)
            return;
        file.flags |= FF_DOWNLOAD;
        file.progress = -1;
        file.path = (boost::filesystem::path(path) / file.name).string();
    }
    if ((m_task_flags & FF_DOWNLOAD) == 0)
        DownloadNextFile();
}
References DownloadNextFile(), FF_DOWNLOAD, FF_SELECT, m_file_list, m_task_flags, and n.
DownloadNextFile()
void PrinterFileSystem::DownloadNextFile () private
{
    size_t index = size_t(-1);
    for (size_t i = 0; i < m_file_list.size(); ++i) {
        if ((m_file_list[i].flags & FF_DOWNLOAD) != 0 && m_file_list[i].progress == -1) {
            index = i;
            break;
        }
    }
    m_task_flags &= ~FF_DOWNLOAD;
    if (index >= m_file_list.size())
        return;
    json req;
    req["file"] = m_file_list[index].name;
    m_file_list[index].progress = 0;
    SendChangedEvent(EVT_DOWNLOAD, index, m_file_list[index].name);
    struct Download
    {
        size_t                      index;
        std::string                 name;
        std::string                 path;
        boost::filesystem::ofstream ofs;
        boost::uuids::detail::md5   boost_md5;
    };
    std::shared_ptr<Download> download(new Download);
    download->index = index;
    download->name  = m_file_list[index].name;
    download->path  = m_file_list[index].path;
    m_task_flags |= FF_DOWNLOAD;
    m_download_seq = SendRequest<Progress>(
        FILE_DOWNLOAD, req,
        [this, download](json const &resp, Progress &prog, unsigned char const *data) -> int {
            // in work thread, continue recv
            size_t size = resp["size"];
            prog.size   = resp["offset"];
            prog.total  = resp["total"];
            if (prog.size == 0) {
                download->ofs.open(download->path, std::ios::binary);
                if (!download->ofs) return FILE_OPEN_ERR;
            }
            // receive data
            download->ofs.write((char const *) data, size);
            download->boost_md5.process_bytes(data, size);
            prog.size += size;
            if (prog.size < prog.total) { return CONTINUE; }
            download->ofs.close();
            int         result = 0;
            std::string md5    = resp["file_md5"];
            // check size and md5
            if (prog.size == prog.total) {
                boost::uuids::detail::md5::digest_type digest;
                download->boost_md5.get_digest(digest);
                for (int i = 0; i < 4; ++i) digest[i] = boost::endian::endian_reverse(digest[i]);
                std::string str_md5;
                const auto  char_digest = reinterpret_cast<const char *>(&digest[0]);
                boost::algorithm::hex(char_digest, char_digest + sizeof(digest), std::back_inserter(str_md5));
                if (!boost::iequals(str_md5, md5)) result = FILE_CHECK_ERR;
            } else {
                result = FILE_SIZE_ERR;
            }
            if (result != 0) {
                boost::system::error_code ec;
                boost::filesystem::remove(download->path, ec);
            }
            return result;
        },
        [this, download](int result, Progress const &data) {
            if (download->index != size_t(-1))
                download->index = FindFile(download->index, download->name);
            if (download->index != size_t(-1)) {
                int progress = data.size * 100 / data.total;
                auto & file = m_file_list[download->index];
                if (result == ERROR_CANCEL)
                    file.flags &= ~FF_DOWNLOAD;
                else if (file.progress != progress) {
                    file.progress = progress;
                    SendChangedEvent(EVT_DOWNLOAD, download->index, file.path, result);
                }
            }
            if (result != CONTINUE) DownloadNextFile();
        });
}
References CONTINUE, DownloadNextFile(), ERROR_CANCEL, FF_DOWNLOAD, FILE_CHECK_ERR, FILE_DOWNLOAD, FILE_SIZE_ERR, FindFile(), m_download_seq, m_file_list, m_task_flags, SendChangedEvent(), size, PrinterFileSystem::Progress::size, and PrinterFileSystem::Progress::total.
Referenced by DownloadFiles(), and DownloadNextFile().
DumpLog()
void PrinterFileSystem::DumpLog (void * context, int level, tchar const * msg) static private
{
    BOOST_LOG_TRIVIAL(info) << "PrinterFileSystem: " << msg;
    static_cast<PrinterFileSystem*>(thiz)->Bambu_FreeLogMsg(msg);
}
References Bambu_FreeLogMsg().
Referenced by Reconnect().
EnterSubGroup()
size_t PrinterFileSystem::EnterSubGroup (size_t index)
{
    if (m_group_mode == G_NONE)
        return index;
    index = m_group_mode == G_YEAR ? m_group_year[index] : m_group_month[index];
    SetGroupMode((GroupMode)(m_group_mode - 1));
    return index;
}
References G_NONE, G_YEAR, m_group_mode, m_group_month, m_group_year, and SetGroupMode().
FileRemoved()
void PrinterFileSystem::FileRemoved (size_t index, std::string const & name) private
{
    index = FindFile(index, name);
    if (index == size_t(-1))
        return;
    auto removeFromGroup = [](std::vector<size_t> &group, size_t index, int total) {
        for (auto iter = group.begin(); iter != group.end(); ++iter) {
            size_t index2 = -1;
            if (*iter < index) continue;
            if (*iter == index) {
                auto iter2 = iter + 1;
                if (iter2 == group.end() ? index == total - 1 : *iter2 == index + 1) {
                    index2 = std::distance(group.begin(), iter);
                }
                ++iter;
            }
            for (; iter != group.end(); ++iter) {
                --*iter;
            }
            return index2;
        }
        return size_t(-1);
    };
    size_t index2 = removeFromGroup(m_group_month, index, m_file_list.size());
    if (index2 < m_group_month.size()) {
        int index3 = removeFromGroup(m_group_year, index, m_group_month.size());
        if (index3 < m_group_year.size()) {
            m_group_year.erase(m_group_year.begin() + index3);
            if (m_group_mode == G_YEAR)
                m_group_flags.erase(m_group_flags.begin() + index2);
        }
        m_group_month.erase(m_group_month.begin() + index2);
        if (m_group_mode == G_MONTH)
            m_group_flags.erase(m_group_flags.begin() + index2);
    }
    m_file_list.erase(m_file_list.begin() + index);
}
References std::distance(), FindFile(), G_MONTH, G_YEAR, m_file_list, m_group_flags, m_group_mode, m_group_month, and m_group_year.
Referenced by DeleteFilesContinue().
FindFile()
size_t PrinterFileSystem::FindFile (size_t index, std::string const & name) private
{
    if (index >= m_file_list.size() || m_file_list[index].name != name) {
        auto iter = std::find_if(m_file_list.begin(), m_file_list.end(), [name](File &f) { return f.name == name; });
        if (iter == m_file_list.end()) return -1;
        index = std::distance(m_file_list.begin(), iter);
    }
    return index;
}
References std::distance(), and m_file_list.
Referenced by DownloadNextFile(), and FileRemoved().
GetCount()
size_t PrinterFileSystem::GetCount () const
{
    if (m_group_mode == G_NONE)
        return m_file_list.size();
    return m_group_mode == G_YEAR ? m_group_year.size() : m_group_month.size();
}
References G_NONE, G_YEAR, m_file_list, m_group_mode, m_group_month, and m_group_year.
Referenced by UpdateFocusThumbnail().
GetFile() [1/2]
PrinterFileSystem::File const & PrinterFileSystem::GetFile (size_t index)
{
    if (m_group_mode == G_NONE)
        return m_file_list[index];
    if (m_group_mode == G_YEAR) index = m_group_year[index];
    return m_file_list[m_group_month[index]];
}
References G_NONE, G_YEAR, m_file_list, m_group_mode, m_group_month, and m_group_year.
Referenced by UpdateFocusThumbnail().
GetFile() [2/2]
PrinterFileSystem::File const & PrinterFileSystem::GetFile (size_t index, bool & select)
{
    if (m_group_mode == G_NONE) {
        select = m_file_list[index].IsSelect();
        return m_file_list[index];
    }
    select = m_group_flags[index] & FF_SELECT;
    if (m_group_mode == G_YEAR)
        index = m_group_year[index];
    return m_file_list[m_group_month[index]];
}
References FF_SELECT, G_NONE, G_YEAR, m_file_list, m_group_flags, m_group_mode, m_group_month, and m_group_year.
GetFileType()
GroupMode PrinterFileSystem::GetFileType () const inline
{ return m_group_mode; }
References m_group_mode.
GetGroupMode()
GroupMode PrinterFileSystem::GetGroupMode () const inline
{ return m_group_mode; }
References m_group_mode.
GetIndexAtTime()
size_t PrinterFileSystem::GetIndexAtTime (boost::uint32_t time)
{
    auto iter = std::upper_bound(m_file_list.begin(), m_file_list.end(), File{"", time});
    size_t n = std::distance(m_file_list.begin(), iter) - 1;
    if (m_group_mode == G_NONE) {
        return n;
    }
    auto & group = m_group_mode == G_YEAR ? m_group_year : m_group_month;
    auto iter2 = std::upper_bound(group.begin(), group.end(), n);
    return std::distance(group.begin(), iter2) - 1;
}
References std::distance(), G_NONE, G_YEAR, m_file_list, m_group_mode, m_group_month, m_group_year, and n.
GetLastError()
int PrinterFileSystem::GetLastError () const inline
{ return m_last_error; }
References m_last_error.
GetSelectCount()
size_t PrinterFileSystem::GetSelectCount () const
{ return m_select_count; }
References m_select_count.
GetStatus()
Status PrinterFileSystem::GetStatus () const inline
{ return m_status; }
References m_status.
HandleResponse()
void PrinterFileSystem::HandleResponse (boost::unique_lock< boost::mutex > & l, Bambu_Sample const & sample) private
{
    unsigned char const *end      = sample.buffer + sample.size;
    unsigned char const *json_end = (unsigned char const *) memchr(sample.buffer, '\n', sample.size);
    while (json_end && json_end + 3 < end && json_end[1] != '\n') json_end = (unsigned char const *) memchr(json_end + 2, '\n', end - json_end - 2);
    if (json_end)
        json_end += 2;
    else
        json_end = end;
    std::string msg((char const *) sample.buffer, json_end - sample.buffer);
    json        root;
    // OutputDebugStringA(msg.c_str());
    // OutputDebugStringA("\n");
    std::istringstream iss(msg);
    int                cmd    = 0;
    int                seq    = -1;
    int                result = 0;
    json               resp;
    try {
        iss >> root;
        if (!root["result"].is_null()) {
            result = root["result"];
            seq    = root["sequence"];
            resp   = root["reply"];
        } else {
            // maybe notify
            cmd  = root["cmdtype"];
            seq  = root["sequence"];
            resp = root["notify"];
        }
    } catch (...) {
        result = ERROR_JSON;
        return;
    }
    if (cmd > 0) {
        if (cmd < NOTIFY_FIRST) return;
        cmd -= NOTIFY_FIRST;
        if (size_t(cmd) >= m_notifies.size()) return;
        auto n = m_notifies[cmd];
        l.unlock();
        n(result, resp, json_end);
        l.lock();
    } else {
        seq -= m_sequence;
        if (size_t(seq) >= m_callbacks.size()) return;
        auto c = m_callbacks[seq];
        if (c == nullptr) return;
        if (result != CONTINUE) {
            m_callbacks[seq] = callback_t2();
            if (seq == 0) {
                while (!m_callbacks.empty() && m_callbacks.front() == nullptr) {
                    m_callbacks.pop_front();
                    ++m_sequence;
                }
            }
        }
        l.unlock();
        c(result, resp, json_end);
        l.lock();
    }
}
References __Bambu_Sample::buffer, CONTINUE, end, ERROR_JSON, m_callbacks, m_notifies, m_sequence, n, NOTIFY_FIRST, and __Bambu_Sample::size.
Referenced by RecvMessageThread().
InstallNotify() [1/2]
void PrinterFileSystem::InstallNotify (int type, callback_t2 const & callback) private
{
    type -= NOTIFY_FIRST;
    if (m_notifies.size() <= size_t(type)) m_notifies.resize(type + 1);
    m_notifies[type] = callback;
}
References m_notifies, and NOTIFY_FIRST.
InstallNotify() [2/2]
template<typename T > void PrinterFileSystem::InstallNotify (int type, Translator< T > const & translator, Applier< T > const & applier) inline private
    {
        auto c = [translator, applier, this](int result, json const &resp, unsigned char const *data)
        {
            T t;
            if (result == 0 || result == CONTINUE) {
                try {
                    int n  = (translator != nullptr) ? translator(resp, t, data) : 0;
                    result = n == 0 ? result : n;
                }
                catch (...) {
                    result = ERROR_JSON;
                }
            }
            if (result == 0 && applier) {
                PostCallback<T>([applier](int, T const & t) {
                    applier(t);
                }, 0, t);
            }
        };
        InstallNotify(type, c);
    }
References CONTINUE, ERROR_JSON, InstallNotify(), and n.
Referenced by InstallNotify().
ListAllFiles()
void PrinterFileSystem::ListAllFiles ()
{
    json req;
    req["type"] = m_file_type == F_VIDEO ? "video" : "timelapse";
    req["notify"] = "DETAIL";
    SendRequest<FileList>(LIST_INFO, req, [this](json const& resp, FileList & list, auto) {
        json files = resp["file_lists"];
        for (auto& f : files) {
            std::string name = f["name"];
            time_t time = f.value("time", 0);
            boost::uint64_t size = f["size"];
            File ff = {name, time, size, default_thumbnail};
            list.push_back(ff);
        }
        return 0;
    }, [this](int result, FileList list) {
        m_file_list.swap(list);
        std::sort(m_file_list.begin(), m_file_list.end());
        auto iter1 = m_file_list.begin();
        auto end1  = m_file_list.end();
        auto iter2 = list.begin();
        auto end2  = list.end();
        while (iter1 != end1 && iter2 != end2) {
            if (iter1->name == iter2->name) {
                iter1->thumbnail = iter2->thumbnail;
                iter1->flags = iter2->flags;
                if (!iter1->thumbnail.IsOk())
                    iter1->flags &= ~FF_THUMNAIL;
                iter1->progress = iter2->progress;
                iter1->path = iter2->path;
                ++iter1; ++iter2;
            } else if (*iter1 < *iter2) {
                ++iter1;
            } else if (*iter2 < *iter1) {
                ++iter2;
            } else {
                ++iter1;
                ++iter2;
            }
        }
        BuildGroups();
        UpdateGroupSelect();
        m_status = Status::ListReady;
        SendChangedEvent(EVT_STATUS_CHANGED, m_status);
        SendChangedEvent(EVT_FILE_CHANGED);
        return 0;
    });
}
References BuildGroups(), default_thumbnail, F_VIDEO, LIST_INFO, ListReady, m_file_list, m_file_type, m_status, SendChangedEvent(), size, UpdateGroupSelect(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value().
Referenced by Reconnect(), and SetFileType().
PostCallback() [1/2]
template<typename T > void PrinterFileSystem::PostCallback (Callback< T > const & callback, int result, T const & resp) inline private
    {
        PostCallback([=] { callback(result, resp); });
    }
References PostCallback().
Referenced by PostCallback(), and Reconnect().
PostCallback() [2/2]
void PrinterFileSystem::PostCallback (std::function< void(void)> const & callback) private
{
    wxCommandEvent *e = new CallbackEvent(callback, boost::weak_ptr(shared_from_this()));
    wxQueueEvent(this, e);
}
Reconnect()
void PrinterFileSystem::Reconnect (boost::unique_lock< boost::mutex > & l, int result) private
{
    if (m_session.tunnel) {
        auto tunnel = m_session.tunnel;
        m_session.tunnel = nullptr;
        l.unlock();
        Bambu_Close(tunnel);
        Bambu_Destroy(tunnel);
        l.lock();
    }
    if (m_session.owner == nullptr)
        return;
    json r;
    while (!m_callbacks.empty()) {
        auto c = m_callbacks.front();
        m_callbacks.pop_front();
        ++m_sequence;
        if (c) c(result, r, nullptr);
    }
    m_messages.clear();
    while (true) {
        while (m_stopped) {
            if (m_session.owner == nullptr)
                return;
            m_cond.wait(l);
        }
        m_status = Status::Initializing;
        SendChangedEvent(EVT_STATUS_CHANGED, m_status);
        // wait for url
        while (!m_stopped && m_messages.empty())
            m_cond.wait(l);
        if (m_stopped || m_messages.empty()) continue;
        std::string url = m_messages.front();
        m_messages.clear();
        if (url.empty()) {
            m_last_error = 1;
        } else {
            l.unlock();
            m_status = Status::Connecting;
            SendChangedEvent(EVT_STATUS_CHANGED, m_status);
            Bambu_Tunnel tunnel = nullptr;
            int ret = Bambu_Create(&tunnel, url.c_str());
            if (ret == 0) {
                Bambu_SetLogger(tunnel, DumpLog, this);
                ret = Bambu_Open(tunnel);
            }
            if (ret == 0)
                ret = Bambu_StartStream(tunnel, false);
            l.lock();
            m_session.tunnel = tunnel;
            if (ret == 0)
                break;
            m_last_error = ret;
        }
        m_status     = Status::Failed;
        SendChangedEvent(EVT_STATUS_CHANGED, m_status);
        m_cond.timed_wait(l, boost::posix_time::seconds(10));
    }
    m_status = Status::ListSyncing;
    SendChangedEvent(EVT_STATUS_CHANGED, m_status);
#ifdef PRINTER_FILE_SYSTEM_TEST
    PostCallback([this] { SendChangedEvent(EVT_FILE_CHANGED); });
#else
    PostCallback([this] { ListAllFiles(); });
#endif
}
References Bambu_Close(), Bambu_Create(), Bambu_Destroy(), Bambu_Open(), Bambu_SetLogger(), Bambu_StartStream(), Connecting, DumpLog(), Failed, Initializing, ListAllFiles(), ListSyncing, m_callbacks, m_cond, m_last_error, m_messages, m_sequence, m_session, m_status, m_stopped, PrinterFileSystem::Session::owner, PostCallback(), SendChangedEvent(), and PrinterFileSystem::Session::tunnel.
Referenced by RecvMessageThread().
RecvData()
int PrinterFileSystem::RecvData (std::function< int(Bambu_Sample &sample)> const & callback) private
{
    int result = 0;
    while (true) {
        Bambu_Sample sample;
        result = Bambu_ReadSample(m_session.tunnel, &sample);
        if (result == Bambu_success) {
            result = callback(sample);
            if (result == 1)
                continue;
        } else if (result == Bambu_would_block) {
            boost::this_thread::sleep(boost::posix_time::seconds(1));
            continue;
        } else if (result == Bambu_stream_end) {
            result = 0;
        } else {
            result = ERROR_PIPE;
        }
        break;
    }
    return result;
}
References Bambu_ReadSample(), Bambu_stream_end, Bambu_success, Bambu_would_block, ERROR_PIPE, m_session, and PrinterFileSystem::Session::tunnel.
RecvMessageThread()
void PrinterFileSystem::RecvMessageThread () private
{
    Bambu_Sample sample;
    boost::unique_lock l(m_mutex);
    Reconnect(l, 0);
    while (true) {
        if (m_stopped && (m_session.owner == nullptr || (m_messages.empty() && m_callbacks.empty()))) {
            Reconnect(l, 0); // Close and wait start again
            if (m_session.owner == nullptr) {
                // clear callbacks first
                auto callbacks(std::move(m_callbacks));
                break;
            }
        }
        if (!m_messages.empty()) {
            auto & msg = m_messages.front();
            l.unlock();
            int n = Bambu_SendMessage(m_session.tunnel, CTRL_TYPE, msg.c_str(), msg.length());
            l.lock();
            if (n == 0)
                m_messages.pop_front();
            else if (n != Bambu_would_block) {
                Reconnect(l, n);
                continue;
            }
        }
        l.unlock();
        int n = Bambu_ReadSample(m_session.tunnel, &sample);
        l.lock();
        if (n == 0) {
            HandleResponse(l, sample);
        } else if (n == Bambu_would_block) {
            m_cond.timed_wait(l, boost::posix_time::milliseconds(m_messages.empty() && m_callbacks.empty() ? 1000 : 20));
        } else {
            Reconnect(l, n);
        }
    } // while
}
References Bambu_ReadSample(), Bambu_SendMessage(), Bambu_would_block, CTRL_TYPE, HandleResponse(), m_callbacks, m_cond, m_messages, m_mutex, m_session, m_stopped, n, PrinterFileSystem::Session::owner, Reconnect(), and PrinterFileSystem::Session::tunnel.
Retry()
void PrinterFileSystem::Retry ()
{
    boost::unique_lock l(m_mutex);
    m_cond.notify_all();
}
References m_cond, and m_mutex.
SelectAll()
void PrinterFileSystem::SelectAll (bool select)
{
    if (select) {
        for (auto &f : m_file_list) f.flags |= FF_SELECT;
        m_select_count = m_file_list.size();
        for (auto &s : m_group_flags) s |= FF_SELECT;
    } else {
        for (auto &f : m_file_list) f.flags &= ~FF_SELECT;
        m_select_count = 0;
        for (auto &s : m_group_flags) s &= ~FF_SELECT;
    }
    SendChangedEvent(EVT_SELECT_CHANGED, m_select_count);
}
References FF_SELECT, m_file_list, m_group_flags, m_select_count, and SendChangedEvent().
SendChangedEvent()
void PrinterFileSystem::SendChangedEvent (wxEventType type, size_t index = (size_t)-1, std::string const & str = {}, long extra = 0) private
{
    wxCommandEvent event(type);
    event.SetEventObject(this);
    event.SetInt(index);
    if (!str.empty())
        event.SetString(wxString::FromUTF8(str.c_str()));
    event.SetExtraLong(extra);
    if (wxThread::IsMain())
        ProcessEventLocally(event);
    else
        wxPostEvent(this, event);
}
Referenced by DeleteFilesContinue(), DownloadCheckFile(), DownloadNextFile(), ListAllFiles(), Reconnect(), SelectAll(), SetFileType(), SetGroupMode(), ToggleSelect(), and UpdateFocusThumbnail().
SendRequest() [1/2]
boost::uint32_t PrinterFileSystem::SendRequest (int type, json const & req, callback_t2 const & callback) private
{
    if (m_session.tunnel == nullptr) {
        boost::unique_lock l(m_mutex);
        m_cond.notify_all();
        return 0;
    }
    boost::uint32_t seq = m_sequence + m_callbacks.size();
    json root;
    root["cmdtype"] = type;
    root["sequence"] = seq;
    root["req"] = req;
    std::ostringstream oss;
    oss << root;
    auto msg = oss.str();
    //OutputDebugStringA(msg.c_str());
    //OutputDebugStringA("\n");
    BOOST_LOG_TRIVIAL(info) << "PrinterFileSystem::SendRequest: " << type << " msg: " << msg;
    boost::unique_lock l(m_mutex);
    m_messages.push_back(msg);
    m_callbacks.push_back(callback);
    m_cond.notify_all();
    return seq;
}
References m_callbacks, m_cond, m_messages, m_mutex, m_sequence, m_session, and PrinterFileSystem::Session::tunnel.
SendRequest() [2/2]
template<typename T > boost::uint32_t PrinterFileSystem::SendRequest (int type, json const & req, Translator< T > const & translator, Callback< T > const & callback) inline private
    {
        auto c = [translator, callback, this](int result, json const &resp, unsigned char const *data)
        {
            T t;
            if (result == 0 || result == CONTINUE) {
                try {
                    int n  = (translator != nullptr) ? translator(resp, t, data) : 0;
                    result = n == 0 ? result : n;
                }
                catch (...) {
                    result = ERROR_JSON;
                }
            }
            PostCallback<T>(callback, result, t);
        };
        return SendRequest(type, req, c);
    }
References CONTINUE, ERROR_JSON, n, and SendRequest().
Referenced by CancelRequest(), and SendRequest().
SetFileType()
void PrinterFileSystem::SetFileType (FileType type)
{
    if (this->m_file_type == type)
        return;
    this->m_file_type = type;
    m_file_list.swap(m_file_list2);
    m_lock_start = m_lock_end = 0;
    SendChangedEvent(EVT_FILE_CHANGED);
    m_status = Status::ListSyncing;
    SendChangedEvent(EVT_STATUS_CHANGED, m_status);
    ListAllFiles();
}
References ListAllFiles(), ListSyncing, m_file_list, m_file_list2, m_file_type, m_lock_end, m_lock_start, m_status, and SendChangedEvent().
SetFocusRange()
void PrinterFileSystem::SetFocusRange (size_t start, size_t count)
{
    m_lock_start = start;
    m_lock_end = start + count;
    if (!m_stopped && (m_task_flags & FF_THUMNAIL) == 0)
        UpdateFocusThumbnail();
}
References count, FF_THUMNAIL, m_lock_end, m_lock_start, m_stopped, m_task_flags, start, and UpdateFocusThumbnail().
SetGroupMode()
void PrinterFileSystem::SetGroupMode (GroupMode mode)
{
    if (this->m_group_mode == mode)
        return;
    this->m_group_mode = mode;
    m_lock_start = m_lock_end = 0;
    UpdateGroupSelect();
    SendChangedEvent(EVT_MODE_CHANGED);
}
References m_group_mode, m_lock_end, m_lock_start, SendChangedEvent(), and UpdateGroupSelect().
Referenced by EnterSubGroup().
SetUrl()
void PrinterFileSystem::SetUrl (std::string const & url)
{
    boost::unique_lock l(m_mutex);
    m_messages.push_back(url);
    m_cond.notify_all();
}
References m_cond, m_messages, and m_mutex.
Start()
void PrinterFileSystem::Start ()
{
    boost::unique_lock l(m_mutex);
    if (!m_stopped) return;
    m_stopped = false;
    m_cond.notify_all();
}
References m_cond, m_mutex, and m_stopped.
Stop()
void PrinterFileSystem::Stop (bool quit = false)
{
    boost::unique_lock l(m_mutex);
    if (quit) {
        m_session.owner = nullptr;
    } else if (m_stopped) {
        return;
    }
    m_stopped = true;
    m_cond.notify_all();
}
References m_cond, m_mutex, m_session, m_stopped, and PrinterFileSystem::Session::owner.
ToggleSelect()
void PrinterFileSystem::ToggleSelect (size_t index)
{
    if (m_group_mode != G_NONE) {
        size_t beg = m_group_mode == G_YEAR ? m_group_month[m_group_year[index]] : m_group_month[index];
        size_t end_month = m_group_mode == G_YEAR ? ((index + 1) < m_group_year.size() ? m_group_year[index + 1] : m_group_month.size()) : index + 1;
        size_t end       = end_month < m_group_month.size() ? m_group_month[end_month] : m_file_list.size();
        if ((m_group_flags[index] & FF_SELECT) == 0) {
            for (int i = beg; i < end; ++i) {
                if ((m_file_list[i].flags & FF_SELECT) == 0) {
                    m_file_list[i].flags |= FF_SELECT;
                    ++m_select_count;
                }
            }
            m_group_flags[index] |= FF_SELECT;
        } else {
            for (int i = beg; i < end; ++i) {
                if (m_file_list[i].flags & FF_SELECT) {
                    m_file_list[i].flags &= ~FF_SELECT;
                    --m_select_count;
                }
            }
            m_group_flags[index] &= ~FF_SELECT;
        }
    } else if (index < m_file_list.size()) {
        m_file_list[index].flags ^= FF_SELECT;
        if (m_file_list[index].flags & FF_SELECT)
            ++m_select_count;
        else
            --m_select_count;
    }
    SendChangedEvent(EVT_SELECT_CHANGED, m_select_count);
}
References end, FF_SELECT, G_NONE, G_YEAR, m_file_list, m_group_flags, m_group_mode, m_group_month, m_group_year, m_select_count, and SendChangedEvent().
UpdateFocusThumbnail()
void PrinterFileSystem::UpdateFocusThumbnail () private
{
    m_task_flags &= ~FF_THUMNAIL;
    if (m_lock_start >= m_file_list.size() || m_lock_start >= m_lock_end)
        return;
    size_t start = m_lock_start;
    size_t end   = std::min(m_lock_end, GetCount());
    std::vector<std::string> names;
    for (; start < end; ++start) {
        auto &file = GetFile(start);
        if ((file.flags & FF_THUMNAIL) == 0) {
            names.push_back(file.name);
            if (names.size() >= 5)
                break;
        }
    }
    if (names.empty())
        return;
    json req;
    json arr;
    for (auto &name : names) arr.push_back(name);
    req["files"] = arr;
    m_task_flags |= FF_THUMNAIL;
    SendRequest<Thumbnail>(
        THUMBNAIL, req,
        [this](json const &resp, Thumbnail &thumb, unsigned char const *data) -> int {
            // in work thread, continue recv
            // receive data
            wxString            mimetype  = resp.value("mimetype", "image/jpeg");
            std::string         thumbnail = resp["thumbnail"];
            boost::uint32_t     size      = resp["size"];
            thumb.name = thumbnail;
            if (size > 0) {
                wxMemoryInputStream mis(data, size);
                thumb.thumbnail = wxImage(mis, mimetype);
            }
            return 0;
        },
        [this](int result, Thumbnail const &thumb) {
            auto n = thumb.name.find_last_of('.');
            auto name = n == std::string::npos ? thumb.name : thumb.name.substr(0, n);
            auto iter = std::find_if(m_file_list.begin(), m_file_list.end(), [&name](auto &f) { return boost::algorithm::starts_with(f.name, name); });
            if (iter != m_file_list.end()) {
                iter->flags |= FF_THUMNAIL; // DOTO: retry on fail
                if (thumb.thumbnail.IsOk()) {
                    iter->thumbnail = thumb.thumbnail;
                    int index = iter - m_file_list.begin();
                    SendChangedEvent(EVT_THUMBNAIL, index, thumb.name);
                }
            }
            if (result == 0)
                UpdateFocusThumbnail();
        });
}
References end, FF_THUMNAIL, GetCount(), GetFile(), m_file_list, m_lock_end, m_lock_start, m_task_flags, n, PrinterFileSystem::Thumbnail::name, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::push_back(), SendChangedEvent(), size, start, THUMBNAIL, PrinterFileSystem::Thumbnail::thumbnail, UpdateFocusThumbnail(), and nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::value().
Referenced by SetFocusRange(), and UpdateFocusThumbnail().
UpdateGroupSelect()
void PrinterFileSystem::UpdateGroupSelect () private
{
    m_group_flags.clear();
    int beg = 0;
    if (m_group_mode != G_NONE) {
        auto group = m_group_mode == G_YEAR ? m_group_year : m_group_month;
        if (m_group_mode == G_YEAR)
            for (auto &g : group) g = m_group_month[g];
        m_group_flags.resize(group.size(), FF_SELECT);
        for (int i = 0; i < m_file_list.size(); ++i) {
            if ((m_file_list[i].flags & FF_SELECT) == 0) {
                auto iter = std::upper_bound(group.begin(), group.end(), i);
                m_group_flags[iter - group.begin() - 1] &= ~FF_SELECT;
                if (iter == group.end()) break;
                i = *iter - 1; // start from next group
            }
        }
    }
}
References FF_SELECT, G_NONE, G_YEAR, m_file_list, m_group_flags, m_group_mode, m_group_month, and m_group_year.
Referenced by ListAllFiles(), and SetGroupMode().
Member Data Documentation
CTRL_TYPE
const int PrinterFileSystem::CTRL_TYPE = 0x3001 static private
Referenced by RecvMessageThread().
m_callbacks
std::deque<callback_t2> PrinterFileSystem::m_callbacks private
Referenced by CancelRequest(), HandleResponse(), Reconnect(), RecvMessageThread(), and SendRequest().
m_cond
boost::condition_variable PrinterFileSystem::m_cond private
Referenced by Reconnect(), RecvMessageThread(), Retry(), SendRequest(), SetUrl(), Start(), and Stop().
m_download_seq
boost::uint32_t PrinterFileSystem::m_download_seq = 0 private
Referenced by DownloadCancel(), and DownloadNextFile().
m_file_list
FileList PrinterFileSystem::m_file_list protected
Referenced by PrinterFileSystem(), BuildGroups(), DeleteFiles(), DeleteFilesContinue(), DownloadCancel(), DownloadCheckFile(), DownloadCheckFiles(), DownloadFiles(), DownloadNextFile(), FileRemoved(), FindFile(), GetCount(), GetFile(), GetFile(), GetIndexAtTime(), ListAllFiles(), SelectAll(), SetFileType(), ToggleSelect(), UpdateFocusThumbnail(), and UpdateGroupSelect().
m_file_list2
FileList PrinterFileSystem::m_file_list2 protected
Referenced by SetFileType().
m_file_type
FileType PrinterFileSystem::m_file_type = F_TIMELAPSE protected
Referenced by ListAllFiles(), and SetFileType().
m_group_flags
std::vector<int> PrinterFileSystem::m_group_flags protected
Referenced by FileRemoved(), GetFile(), SelectAll(), ToggleSelect(), and UpdateGroupSelect().
m_group_mode
GroupMode PrinterFileSystem::m_group_mode = G_NONE protected
Referenced by EnterSubGroup(), FileRemoved(), GetCount(), GetFile(), GetFile(), GetFileType(), GetGroupMode(), GetIndexAtTime(), SetGroupMode(), ToggleSelect(), and UpdateGroupSelect().
m_group_month
std::vector<size_t> PrinterFileSystem::m_group_month protected
Referenced by BuildGroups(), EnterSubGroup(), FileRemoved(), GetCount(), GetFile(), GetFile(), GetIndexAtTime(), ToggleSelect(), and UpdateGroupSelect().
m_group_year
std::vector<size_t> PrinterFileSystem::m_group_year protected
Referenced by BuildGroups(), EnterSubGroup(), FileRemoved(), GetCount(), GetFile(), GetFile(), GetIndexAtTime(), ToggleSelect(), and UpdateGroupSelect().
m_last_error
int PrinterFileSystem::m_last_error = 0 private
Referenced by GetLastError(), and Reconnect().
m_lock_end
size_t PrinterFileSystem::m_lock_end = 0 private
Referenced by SetFileType(), SetFocusRange(), SetGroupMode(), and UpdateFocusThumbnail().
m_lock_start
size_t PrinterFileSystem::m_lock_start = 0 private
Referenced by SetFileType(), SetFocusRange(), SetGroupMode(), and UpdateFocusThumbnail().
m_messages
std::deque<std::string> PrinterFileSystem::m_messages private
Referenced by Reconnect(), RecvMessageThread(), SendRequest(), and SetUrl().
m_mutex
boost::mutex PrinterFileSystem::m_mutex private
Referenced by Attached(), CancelRequest(), RecvMessageThread(), Retry(), SendRequest(), SetUrl(), Start(), and Stop().
m_notifies
std::deque<callback_t2> PrinterFileSystem::m_notifies private
Referenced by HandleResponse(), and InstallNotify().
m_recv_thread
boost::thread PrinterFileSystem::m_recv_thread private
Referenced by ~PrinterFileSystem(), and Attached().
m_select_count
size_t PrinterFileSystem::m_select_count = 0 private
Referenced by GetSelectCount(), SelectAll(), and ToggleSelect().
m_sequence
boost::uint32_t PrinterFileSystem::m_sequence = 0 private
Referenced by CancelRequest(), HandleResponse(), Reconnect(), and SendRequest().
m_session
Session PrinterFileSystem::m_session private
Referenced by PrinterFileSystem(), Reconnect(), RecvData(), RecvMessageThread(), SendRequest(), and Stop().
m_status
Status PrinterFileSystem::m_status private
Referenced by GetStatus(), ListAllFiles(), Reconnect(), and SetFileType().
m_stopped
bool PrinterFileSystem::m_stopped = true private
Referenced by Reconnect(), RecvMessageThread(), SetFocusRange(), Start(), and Stop().
m_task_flags
int PrinterFileSystem::m_task_flags = 0 private
Referenced by DeleteFiles(), DeleteFilesContinue(), DownloadFiles(), DownloadNextFile(), SetFocusRange(), and UpdateFocusThumbnail().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Printer/PrinterFileSystem.h
src/slic3r/GUI/Printer/PrinterFileSystem.cpp