OrcaSlicer: Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh Class Reference
Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
HollowedMesh (CommonGizmosDataPool *cgdp)
CommonGizmosDataID get_dependencies () const override
const sla::DrainHoles & get_drainholes () const
const TriangleMesh * get_hollowed_mesh () const
const TriangleMesh * get_hollowed_interior () const
void update ()
void release ()
bool is_valid () const
Protected Member Functions
void on_update () override
void on_release () override
CommonGizmosDataPool * get_pool () const
Private Attributes
std::unique_ptr< TriangleMesh > m_hollowed_mesh_transformed
std::unique_ptr< TriangleMesh > m_hollowed_interior_transformed
size_t m_old_hollowing_timestamp = 0
int m_print_object_idx = -1
int m_print_objects_count = 0
sla::DrainHoles m_drainholes
bool m_is_valid = false
CommonGizmosDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
HollowedMesh()
Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::HollowedMesh (CommonGizmosDataPool * cgdp) inline explicit
        : CommonGizmosDataBase(cgdp) {}
Member Function Documentation
get_dependencies()
CommonGizmosDataID Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::get_dependencies () const inline override virtual
Reimplemented from Slic3r::GUI::CommonGizmosDataBase.
{ return CommonGizmosDataID::SelectionInfo; }
References Slic3r::GUI::SelectionInfo.
get_drainholes()
const sla::DrainHoles & Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::get_drainholes () const inline
{ return m_drainholes; }
References m_drainholes.
Referenced by Slic3r::GUI::GLGizmoHollow::render_points().
get_hollowed_interior()
const TriangleMesh * Slic3r::GUI::HollowedMesh::get_hollowed_interior () const
{
    return m_hollowed_interior_transformed.get();
}
References m_hollowed_interior_transformed.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::on_update().
get_hollowed_mesh()
const TriangleMesh * Slic3r::GUI::HollowedMesh::get_hollowed_mesh () const
{
    return m_hollowed_mesh_transformed.get();
}
References m_hollowed_mesh_transformed.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::on_update(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), and Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh().
get_pool()
CommonGizmosDataPool * Slic3r::GUI::CommonGizmosDataBase::get_pool () const inline protected inherited
{ return m_common; }
References Slic3r::GUI::CommonGizmosDataBase::m_common.
Referenced by Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_release(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::on_update(), on_update(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::on_update(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::render_cut(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position(), and Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_range_and_pos().
is_valid()
bool Slic3r::GUI::CommonGizmosDataBase::is_valid () const inline inherited
{ return m_is_valid; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid.
Referenced by Slic3r::GUI::CommonGizmosDataPool::hollowed_mesh(), Slic3r::GUI::CommonGizmosDataPool::instances_hider(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::InstancesHider::render_cut(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::CommonGizmosDataPool::supports_clipper().
on_release()
void Slic3r::GUI::HollowedMesh::on_release () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    m_hollowed_mesh_transformed.reset();
    m_old_hollowing_timestamp = 0;
    m_print_object_idx = -1;
}
References m_hollowed_mesh_transformed, m_old_hollowing_timestamp, and m_print_object_idx.
on_update()
void Slic3r::GUI::HollowedMesh::on_update () override protected virtual
Implements Slic3r::GUI::CommonGizmosDataBase.
{
    const ModelObject* mo = get_pool()->selection_info()->model_object();
    bool is_sla = wxGetApp().preset_bundle->printers.get_selected_preset().printer_technology() == ptSLA;
    if (! mo || ! is_sla)
        return;
    const GLCanvas3D* canvas = get_pool()->get_canvas();
    const PrintObjects& print_objects = canvas->sla_print()->objects();
    const SLAPrintObject* print_object = m_print_object_idx != -1
            ? print_objects[m_print_object_idx]
            : nullptr;
    // Find the respective SLAPrintObject.
    if (m_print_object_idx < 0 || m_print_objects_count != int(print_objects.size())) {
        m_print_objects_count = print_objects.size();
        m_print_object_idx = -1;
        for (const SLAPrintObject* po : print_objects) {
            ++m_print_object_idx;
            if (po->model_object()->id() == mo->id()) {
                print_object = po;
                break;
            }
        }
    }
    // If there is a valid SLAPrintObject, check state of Hollowing step.
    if (print_object) {
        if (print_object->is_step_done(slaposDrillHoles) && print_object->has_mesh(slaposDrillHoles)) {
            size_t timestamp = print_object->step_state_with_timestamp(slaposDrillHoles).timestamp;
            if (timestamp > m_old_hollowing_timestamp) {
                const TriangleMesh& backend_mesh = print_object->get_mesh_to_slice();
                if (! backend_mesh.empty()) {
                    m_hollowed_mesh_transformed.reset(new TriangleMesh(backend_mesh));
                    Transform3d trafo_inv = canvas->sla_print()->sla_trafo(*mo).inverse();
                    m_hollowed_mesh_transformed->transform(trafo_inv);
                    m_drainholes = print_object->model_object()->sla_drain_holes;
                    m_old_hollowing_timestamp = timestamp;
                    indexed_triangle_set interior = print_object->hollowed_interior_mesh();
                    its_flip_triangles(interior);
                    m_hollowed_interior_transformed = std::make_unique<TriangleMesh>(std::move(interior));
                    m_hollowed_interior_transformed->transform(trafo_inv);
                }
                else {
                    m_hollowed_mesh_transformed.reset(nullptr);
                }
            }
        }
        else
            m_hollowed_mesh_transformed.reset(nullptr);
    }
}
References Slic3r::TriangleMesh::empty(), Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::SLAPrintObject::get_mesh_to_slice(), Slic3r::GUI::CommonGizmosDataBase::get_pool(), Slic3r::SLAPrintObject::has_mesh(), Slic3r::SLAPrintObject::hollowed_interior_mesh(), Slic3r::ObjectBase::id(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::is_step_done(), Slic3r::its_flip_triangles(), m_drainholes, m_hollowed_interior_transformed, m_hollowed_mesh_transformed, m_old_hollowing_timestamp, m_print_object_idx, m_print_objects_count, Slic3r::PrintObjectBase::model_object(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::SLAPrint::objects(), Slic3r::ptSLA, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::ModelObject::sla_drain_holes, Slic3r::GUI::GLCanvas3D::sla_print(), Slic3r::SLAPrint::sla_trafo(), Slic3r::slaposDrillHoles, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::step_state_with_timestamp(), and Slic3r::PrintStateBase::StateWithTimeStamp::timestamp.
release()
void Slic3r::GUI::CommonGizmosDataBase::release () inline inherited
{ on_release(); m_is_valid = false; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_release().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_set_state().
update()
void Slic3r::GUI::CommonGizmosDataBase::update () inline inherited
{ on_update(); m_is_valid = true; }
References Slic3r::GUI::CommonGizmosDataBase::m_is_valid, and Slic3r::GUI::CommonGizmosDataBase::on_update().
Member Data Documentation
m_common
CommonGizmosDataPool* Slic3r::GUI::CommonGizmosDataBase::m_common = nullptr private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::get_pool().
m_drainholes
sla::DrainHoles Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::m_drainholes private
Referenced by get_drainholes(), and on_update().
m_hollowed_interior_transformed
std::unique_ptr<TriangleMesh> Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::m_hollowed_interior_transformed private
Referenced by get_hollowed_interior(), and on_update().
m_hollowed_mesh_transformed
std::unique_ptr<TriangleMesh> Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::m_hollowed_mesh_transformed private
Referenced by get_hollowed_mesh(), on_release(), and on_update().
m_is_valid
bool Slic3r::GUI::CommonGizmosDataBase::m_is_valid = false private inherited
Referenced by Slic3r::GUI::CommonGizmosDataBase::is_valid(), Slic3r::GUI::CommonGizmosDataBase::release(), and Slic3r::GUI::CommonGizmosDataBase::update().
m_old_hollowing_timestamp
size_t Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::m_old_hollowing_timestamp = 0 private
Referenced by on_release(), and on_update().
m_print_object_idx
int Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::m_print_object_idx = -1 private
Referenced by on_release(), and on_update().
m_print_objects_count
int Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::m_print_objects_count = 0 private
Referenced by on_update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp
src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp