OrcaSlicer: nlohmann::ordered_map< Key, T, IgnoredLess, Allocator > Struct Template Reference
nlohmann::ordered_map< Key, T, IgnoredLess, Allocator > Struct Template Reference
ordered_map: a minimal map-like container that preserves insertion order for use within nlohmann::basic_json<ordered_map>
#include <src/nlohmann/ordered_map.hpp>
Public Types
using key_type = Key
using mapped_type = T
using Container = std::vector< std::pair< const Key, T >, Allocator >
template<typename InputIt >
using require_input_iter = typename std::enable_if< std::is_convertible< typename std::iterator_traits< InputIt >::iterator_category, std::input_iterator_tag >::value >::type
Public Member Functions
ordered_map (const Allocator &alloc=Allocator())
template<class It >
ordered_map (It first, It last, const Allocator &alloc=Allocator())
ordered_map (std::initializer_list< T > init, const Allocator &alloc=Allocator())
std::pair< iterator, bool > emplace (const key_type &key, T &&t)
T & operator[] (const Key &key)
const T & operator[] (const Key &key) const
T & at (const Key &key)
const T & at (const Key &key) const
size_type erase (const Key &key)
iterator erase (iterator pos)
size_type count (const Key &key) const
iterator find (const Key &key)
const_iterator find (const Key &key) const
std::pair< iterator, bool > insert (value_type &&value)
std::pair< iterator, bool > insert (const value_type &value)
template<typename InputIt , typename = require_input_iter<InputIt>>
void insert (InputIt first, InputIt last)
Detailed Description
template<class Key, class T, class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>>
struct nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >
ordered_map: a minimal map-like container that preserves insertion order for use within nlohmann::basic_json<ordered_map>
Member Typedef Documentation
Container
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::Container = std::vector<std::pair<const Key, T>, Allocator>
key_type
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::key_type = Key
mapped_type
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::mapped_type = T
require_input_iter
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> template<typename InputIt > using nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::require_input_iter = typename std::enable_if<std::is_convertible<typename std::iterator_traits<InputIt>::iterator_category, std::input_iterator_tag>::value>::type
Constructor & Destructor Documentation
ordered_map() [1/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::ordered_map (const Allocator & alloc = Allocator()) inline
: Container{alloc} {}
ordered_map() [2/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> template<class It > nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::ordered_map (It first, It last, const Allocator & alloc = Allocator()) inline
        : Container{first, last, alloc} {}
ordered_map() [3/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::ordered_map (std::initializer_list< T > init, const Allocator & alloc = Allocator()) inline
        : Container{init, alloc} {}
Member Function Documentation
at() [1/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> T & nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::at (const Key & key) inline
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == key)
            {
                return it->second;
            }
        }
        JSON_THROW(std::out_of_range("key not found"));
    }
References end, and JSON_THROW.
Referenced by nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::operator[]().
at() [2/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> const T & nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::at (const Key & key) const inline
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == key)
            {
                return it->second;
            }
        }
        JSON_THROW(std::out_of_range("key not found"));
    }
References end, and JSON_THROW.
count()
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> size_type nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::count (const Key & key) const inline
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == key)
            {
                return 1;
            }
        }
        return 0;
    }
References end.
emplace()
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> std::pair< iterator, bool > nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::emplace (const key_type & key, T && t) inline
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == key)
            {
                return {it, false};
            }
        }
        Container::emplace_back(key, t);
        return {--this->end(), true};
    }
References end.
Referenced by nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert(), and nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::operator[]().
erase() [1/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> size_type nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::erase (const Key & key) inline
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == key)
            {
                // Since we cannot move const Keys, re-construct them in place
                for (auto next = it; ++next != this->end(); ++it)
                {
                    it->~value_type(); // Destroy but keep allocation
                    new (&*it) value_type{std::move(*next)};
                }
                Container::pop_back();
                return 1;
            }
        }
        return 0;
    }
References end.
erase() [2/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> iterator nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::erase (iterator pos) inline
    {
        auto it = pos;
        // Since we cannot move const Keys, re-construct them in place
        for (auto next = it; ++next != this->end(); ++it)
        {
            it->~value_type(); // Destroy but keep allocation
            new (&*it) value_type{std::move(*next)};
        }
        Container::pop_back();
        return pos;
    }
References end.
find() [1/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> iterator nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::find (const Key & key) inline
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == key)
            {
                return it;
            }
        }
        return Container::end();
    }
References end.
find() [2/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> const_iterator nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::find (const Key & key) const inline
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == key)
            {
                return it;
            }
        }
        return Container::end();
    }
References end.
insert() [1/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> std::pair< iterator, bool > nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert (const value_type & value) inline
    {
        for (auto it = this->begin(); it != this->end(); ++it)
        {
            if (it->first == value.first)
            {
                return {it, false};
            }
        }
        Container::push_back(value);
        return {--this->end(), true};
    }
References end.
insert() [2/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> template<typename InputIt , typename = require_input_iter<InputIt>> void nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert (InputIt first, InputIt last) inline
    {
        for (auto it = first; it != last; ++it)
        {
            insert(*it);
        }
    }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert().
insert() [3/3]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> std::pair< iterator, bool > nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert (value_type && value) inline
    {
        return emplace(value.first, std::move(value.second));
    }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::emplace().
Referenced by nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::insert().
operator[]() [1/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> T & nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::operator[] (const Key & key) inline
    {
        return emplace(key, T{}).first->second;
    }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::emplace().
operator[]() [2/2]
template<class Key , class T , class IgnoredLess = std::less<Key>, class Allocator = std::allocator<std::pair<const Key, T>>> const T & nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::operator[] (const Key & key) const inline
    {
        return at(key);
    }
References nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >::at().
The documentation for this struct was generated from the following files:
src/nlohmann/json_fwd.hpp
src/nlohmann/ordered_map.hpp