OrcaSlicer: src/qhull/src/rbox/rbox.c File Reference
rbox.c File Reference
#include "libqhull/libqhull.h"
#include "libqhull/random.h"
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
int main (int argc, char **argv)
Variables
char prompt []
Function Documentation
main()
int main (int argc, char ** argv)
{
  char *command;
  int command_size;
  int return_status;
  QHULL_LIB_CHECK_RBOX
  if (argc == 1) {
    printf(prompt, qh_DEFAULTbox, qh_DEFAULTzbox);
    return 1;
  }
  if (argc == 2 && strcmp(argv[1], "D4")==0)
    qh_fprintf_stderr(0, "\nStarting the rbox smoketest for qhull.  An immediate failure indicates\nthat non-reentrant rbox was linked to reentrant routines.  An immediate\nfailure of qhull may indicate that qhull was linked to the wrong\nqhull library.  Also try 'rbox D4 | qhull T1'\n");
  command_size= qh_argv_to_command_size(argc, argv);
  if ((command= (char *)qh_malloc((size_t)command_size))) {
    if (!qh_argv_to_command(argc, argv, command, command_size)) {
      qh_fprintf_stderr(6264, "rbox internal error: allocated insufficient memory (%d) for arguments\n", command_size);
      return_status= qh_ERRinput;
    }else{
      return_status= qh_rboxpoints(stdout, stderr, command);
    }
    qh_free(command);
  }else {
    qh_fprintf_stderr(6265, "rbox error: insufficient memory for %d bytes\n", command_size);
    return_status= qh_ERRmem;
  }
  return return_status;
}/*main*/
References prompt, qh_argv_to_command(), qh_argv_to_command_size(), qh_DEFAULTbox, qh_DEFAULTzbox, qh_ERRinput, qh_ERRmem, qh_fprintf_stderr(), qh_free(), qh_malloc(), qh_rboxpoints(), and QHULL_LIB_CHECK_RBOX.
Variable Documentation
prompt
char prompt[]
Referenced by Slic3r::GUI::GetNumberFromUser(), and main().