OrcaSlicer: Slic3r::PrintObject Class Reference
Slic3r::PrintObject Class Reference
#include <src/libslic3r/Print.hpp>
Public Types
typedef PrintState< PrintObjectStep, COUNT > PrintObjectState
using Timestamp = uint64_t
Public Member Functions
const Vec3crd & size () const
const PrintObjectConfig & config () const
void configBrimWidth (double m)
ConstLayerPtrsAdaptor layers () const
ConstSupportLayerPtrsAdaptor support_layers () const
const Transform3d & trafo () const
Transform3d trafo_centered () const
const PrintInstances & instances () const
PrintInstances & instances ()
LayerPtrs & layers ()
SupportLayerPtrs & support_layers ()
BoundingBox bounding_box () const
coord_t height () const
const Point & center_offset () const
void generate_support_preview ()
const std::vector< VolumeSlices > & firstLayerObjSlice () const
std::vector< VolumeSlices > & firstLayerObjSliceMod ()
const std::vector< groupedVolumeSlices > & firstLayerObjGroups () const
std::vector< groupedVolumeSlices > & firstLayerObjGroupsMod ()
bool has_brim () const
const ExtrusionEntityCollection & object_skirt () const
size_t total_layer_count () const
size_t layer_count () const
void clear_layers ()
const Layer * get_layer (int idx) const
Layer * get_layer (int idx)
const Layer * get_layer_at_printz (coordf_t print_z) const
Layer * get_layer_at_printz (coordf_t print_z)
const Layer * get_layer_at_printz (coordf_t print_z, coordf_t epsilon) const
Layer * get_layer_at_printz (coordf_t print_z, coordf_t epsilon)
int get_layer_idx_get_printz (coordf_t print_z, coordf_t epsilon)
const Layer * get_layer_at_bottomz (coordf_t bottom_z, coordf_t epsilon) const
Layer * get_layer_at_bottomz (coordf_t bottom_z, coordf_t epsilon)
const Layer * get_first_layer_bellow_printz (coordf_t print_z, coordf_t epsilon) const
Layer * add_layer (int id, coordf_t height, coordf_t print_z, coordf_t slice_z)
SupportLayer * add_tree_support_layer (int id, coordf_t height, coordf_t print_z, coordf_t slice_z)
std::shared_ptr< TreeSupportData > alloc_tree_support_preview_cache ()
void clear_tree_support_preview_cache ()
size_t support_layer_count () const
void clear_support_layers ()
SupportLayer * get_support_layer (int idx)
const SupportLayer * get_support_layer_at_printz (coordf_t print_z, coordf_t epsilon) const
SupportLayer * get_support_layer_at_printz (coordf_t print_z, coordf_t epsilon)
SupportLayer * add_support_layer (int id, int interface_id, coordf_t height, coordf_t print_z)
SupportLayerPtrs::iterator insert_support_layer (SupportLayerPtrs::iterator pos, size_t id, size_t interface_id, coordf_t height, coordf_t print_z, coordf_t slice_z)
const SlicingParameters & slicing_parameters () const
size_t num_printing_regions () const throw ()
const PrintRegion & printing_region (size_t idx) const throw ()
std::vector< std::reference_wrapper< const PrintRegion > > all_regions () const
const PrintObjectRegions * shared_regions () const throw ()
bool has_support () const
bool has_raft () const
bool has_support_material () const
bool is_mm_painted () const
std::vector< unsigned int > object_extruders () const
void slice ()
std::vector< Polygons > slice_support_volumes (const ModelVolumeType model_volume_type) const
std::vector< Polygons > slice_support_blockers () const
std::vector< Polygons > slice_support_enforcers () const
void project_and_append_custom_facets (bool seam, EnforcerBlockerType type, std::vector< Polygons > &expolys) const
BoundingBox get_first_layer_bbox (float &area, float &layer_height, std::string &name)
void get_certain_layers (float start, float end, std::vector< LayerPtrs > &out, std::vector< BoundingBox > &boundingbox_objects)
std::vector< Point > get_instances_shift_without_plate_offset ()
PrintObject * get_shared_object () const
void set_shared_object (PrintObject *object)
void clear_shared_object ()
void copy_layers_from_shared_object ()
void copy_layers_overhang_from_shared_object ()
size_t get_id () const
void set_id (size_t id)
Print * print ()
const Print * print () const
bool is_step_done (PrintObjectStep step) const
PrintStateBase::StateWithTimeStamp step_state_with_timestamp (PrintObjectStep step) const
PrintStateBase::StateWithWarnings step_state_with_warnings (PrintObjectStep step) const
const ModelObject * model_object () const
ModelObject * model_object ()
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Member Functions
template<typename PolysType >
static void remove_bridges_from_contacts (const Layer *lower_layer, const Layer *current_layer, float extrusion_width, PolysType *overhang_regions, float max_bridge_length=scale_(10), bool break_bridge=false)
static bool update_layer_height_profile (const ModelObject &model_object, const SlicingParameters &slicing_parameters, std::vector< coordf_t > &layer_height_profile)
static SlicingParameters slicing_parameters (const DynamicPrintConfig &full_config, const ModelObject &model_object, float object_max_z)
Public Attributes
BoundingBox firstLayerObjectBrimBoundingBox
Static Public Attributes
static bool clip_multipart_objects = true
static bool infill_only_where_needed = false
Protected Member Functions
bool set_started (PrintObjectStep step)
PrintStateBase::TimeStamp set_done (PrintObjectStep step)
bool invalidate_steps (StepTypeIterator step_begin, StepTypeIterator step_end)
bool invalidate_steps (std::initializer_list< PrintObjectStep > il)
bool invalidate_all_steps_without_cancel ()
bool is_step_started_unguarded (PrintObjectStep step) const
bool is_step_done_unguarded (PrintObjectStep step) const
void active_step_add_warning (PrintStateBase::WarningLevel warning_level, const std::string &message, PrintStateBase::SlicingNotificationType message_id=PrintStateBase::SlicingDefaultNotification)
void throw_if_canceled ()
void status_update_warnings (PrintBase *print, int step, PrintStateBase::WarningLevel warning_level, const std::string &message, PrintStateBase::SlicingNotificationType message_id=PrintStateBase::SlicingDefaultNotification)
void emptylayer_update_msg (PrintBase *print, int type, const std::string &message, bool overwrite)
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
virtual void assign_new_unique_ids_recursive ()
Static Protected Member Functions
static std::mutex & state_mutex (PrintBase *print)
static std::function< void()> cancel_callback (PrintBase *print)
Protected Attributes
friend PrintType
Print * m_print
ModelObject * m_model_object
Private Types
typedef PrintObjectBaseWithState< Print, PrintObjectStep, posCount > Inherited
Private Member Functions
PrintObject (Print *print, ModelObject *model_object, const Transform3d &trafo, PrintInstances &&instances)
~PrintObject ()
void config_apply (const ConfigBase &other, bool ignore_nonexistent=false)
void config_apply_only (const ConfigBase &other, const t_config_option_keys &keys, bool ignore_nonexistent=false)
PrintBase::ApplyStatus set_instances (PrintInstances &&instances)
bool invalidate_step (PrintObjectStep step)
bool invalidate_all_steps ()
bool invalidate_state_by_config_options (const ConfigOptionResolver &old_config, const ConfigOptionResolver &new_config, const std::vector< t_config_option_key > &opt_keys)
void update_slicing_parameters ()
void make_perimeters ()
void prepare_infill ()
void infill ()
void ironing ()
void generate_support_material ()
void simplify_extrusion_path ()
void slice_volumes ()
ExPolygons _shrink_contour_holes (double contour_delta, double hole_delta, const ExPolygons &polys) const
void detect_overhangs_for_lift ()
void clear_overhangs_for_lift ()
void detect_surfaces_type ()
void process_external_surfaces ()
void discover_vertical_shells ()
void bridge_over_infill ()
void clip_fill_surfaces ()
void discover_horizontal_shells ()
void combine_infill ()
void _generate_support_material ()
std::pair< FillAdaptive::OctreePtr, FillAdaptive::OctreePtr > prepare_adaptive_infill_data ()
FillLightning::GeneratorPtr prepare_lightning_infill_data ()
SupportNecessaryType is_support_necessary ()
void apply_conical_overhang ()
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static PrintObjectConfig object_config_from_model_object (const PrintObjectConfig &default_object_config, const ModelObject &object, size_t num_extruders)
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
Vec3crd m_size
PrintObjectConfig m_config
Transform3d m_trafo = Transform3d::Identity()
std::vector< PrintInstance > m_instances
Point m_center_offset
PrintObjectRegions * m_shared_regions { nullptr }
SlicingParameters m_slicing_params
LayerPtrs m_layers
SupportLayerPtrs m_support_layers
std::shared_ptr< TreeSupportData > m_tree_support_preview_cache
bool m_typed_slices = false
std::vector< VolumeSlices > firstLayerObjSliceByVolume
std::vector< groupedVolumeSlices > firstLayerObjSliceByGroups
ExtrusionEntityCollection m_skirt
PrintObject * m_shared_object { nullptr }
size_t m_id
PrintState< PrintObjectStep, COUNT > m_state
Static Private Attributes
static size_t s_last_id = 0
Friends
class Print
Detailed Description
Member Typedef Documentation
Inherited
typedef PrintObjectBaseWithState<Print, PrintObjectStep, posCount> Slic3r::PrintObject::Inherited private
PrintObjectState
typedef PrintState<PrintObjectStep , COUNT> Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::PrintObjectState inherited
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
PrintObject()
Slic3r::PrintObject::PrintObject (Print * print, ModelObject * model_object, const Transform3d & trafo, PrintInstances && instances) private
                                                                                                                      :
    PrintObjectBaseWithState(print, model_object),
    m_trafo(trafo),
    // BBS
    m_tree_support_preview_cache(nullptr)
{
    // Compute centering offet to be applied to our meshes so that we work with smaller coordinates
    // requiring less bits to represent Clipper coordinates.
  // Snug bounding box of a rotated and scaled object by the 1st instantion, without the instance translation applied.
  // All the instances share the transformation matrix with the exception of translation in XY and rotation by Z,
  // therefore a bounding box from 1st instance of a ModelObject is good enough for calculating the object center,
  // snug height and an approximate bounding box in XY.
    BoundingBoxf3  bbox        = model_object->raw_bounding_box();
    Vec3d        bbox_center = bbox.center();
  // We may need to rotate the bbox / bbox_center from the original instance to the current instance.
  double z_diff = Geometry::rotation_diff_z(model_object->instances.front()->get_rotation(), instances.front().model_instance->get_rotation());
  if (std::abs(z_diff) > EPSILON) {
    auto z_rot  = Eigen::AngleAxisd(z_diff, Vec3d::UnitZ());
    bbox    = bbox.transformed(Transform3d(z_rot));
    bbox_center = (z_rot * bbox_center).eval();
  }
    // Center of the transformed mesh (without translation).
    m_center_offset = Point::new_scale(bbox_center.x(), bbox_center.y());
    // Size of the transformed mesh. This bounding may not be snug in XY plane, but it is snug in Z.
    m_size = (bbox.size() * (1. / SCALING_FACTOR)).cast<coord_t>();
    this->set_instances(std::move(instances));
}
References Slic3r::BoundingBox3Base< PointClass >::center(), EPSILON, Slic3r::ModelObject::instances, instances(), m_center_offset, m_size, Slic3r::PrintObjectBase::model_object(), Slic3r::ModelObject::raw_bounding_box(), Slic3r::Geometry::rotation_diff_z(), SCALING_FACTOR, set_instances(), Slic3r::BoundingBox3Base< PointClass >::size(), and Slic3r::BoundingBoxf3::transformed().
~PrintObject()
Slic3r::PrintObject::~PrintObject () private
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": this=%1%, m_shared_object %2%")%this%m_shared_object;
    if (m_shared_regions && -- m_shared_regions->m_ref_cnt == 0) delete m_shared_regions;
    clear_layers();
    clear_support_layers();
}
References clear_layers(), clear_support_layers(), Slic3r::PrintObjectRegions::m_ref_cnt, m_shared_object, and m_shared_regions.
Member Function Documentation
_generate_support_material()
void Slic3r::PrintObject::_generate_support_material () private
{
    PrintObjectSupportMaterial support_material(this, m_slicing_params);
    support_material.generate(*this);
_shrink_contour_holes()
ExPolygons Slic3r::PrintObject::_shrink_contour_holes (double contour_delta, double hole_delta, const ExPolygons & polys) const private
{
    ExPolygons new_ex_polys;
    for (const ExPolygon& ex_poly : polys) {
        Polygons contours;
        Polygons holes;
        //BBS: modify hole
        for (const Polygon& hole : ex_poly.holes) {
            if (hole_delta != 0) {
                for (Polygon& newHole : offset(hole, -hole_delta)) {
                    newHole.make_counter_clockwise();
                    holes.emplace_back(std::move(newHole));
                }
            } else {
                holes.push_back(hole);
                holes.back().make_counter_clockwise();
            }
        }
        //BBS: modify contour
        if (contour_delta != 0) {
            Polygons new_contours = offset(ex_poly.contour, contour_delta);
            if (new_contours.size() == 0)
                continue;
            contours.insert(contours.end(), std::make_move_iterator(new_contours.begin()), std::make_move_iterator(new_contours.end()));
        } else {
            contours.push_back(ex_poly.contour);
        }
        ExPolygons temp = diff_ex(union_(contours), union_(holes));
        new_ex_polys.insert(new_ex_polys.end(), std::make_move_iterator(temp.begin()), std::make_move_iterator(temp.end()));
    }
    return union_ex(new_ex_polys);
}
References Slic3r::diff_ex(), Slic3r::union_(), and Slic3r::union_ex().
active_step_add_warning()
void Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::active_step_add_warning (PrintStateBase::WarningLevel warning_level, const std::string & message, PrintStateBase::SlicingNotificationType message_id = PrintStateBase::SlicingDefaultNotification) inline protected inherited
{
      std::pair<PrintObjectStepEnum, bool> active_step = m_state.active_step_add_warning(warning_level, message,(int) message_id, PrintObjectBase::state_mutex(m_print));
      if (active_step.second)
        this->status_update_warnings(m_print, static_cast<int>(active_step.first), warning_level, message, message_id);
    }
add_layer()
Layer * Slic3r::PrintObject::add_layer (int id, coordf_t height, coordf_t print_z, coordf_t slice_z)
{
    m_layers.emplace_back(new Layer(id, this, height, print_z, slice_z));
    return m_layers.back();
}
add_support_layer()
SupportLayer * Slic3r::PrintObject::add_support_layer (int id, int interface_id, coordf_t height, coordf_t print_z)
{
    m_support_layers.emplace_back(new SupportLayer(id, interface_id, this, height, print_z, -1));
    return m_support_layers.back();
}
add_tree_support_layer()
SupportLayer * Slic3r::PrintObject::add_tree_support_layer (int id, coordf_t height, coordf_t print_z, coordf_t slice_z)
{
    m_support_layers.emplace_back(new SupportLayer(id, 0, this, height, print_z, slice_z));
    m_support_layers.back()->support_type = stInnerTree;
    return m_support_layers.back();
}
References Slic3r::stInnerTree, and Slic3r::SupportLayer::support_type.
all_regions()
std::vector< std::reference_wrapper< const PrintRegion > > Slic3r::PrintObject::all_regions () const
{
    std::vector<std::reference_wrapper<const PrintRegion>> out;
    out.reserve(m_shared_regions->all_regions.size());
    for (const std::unique_ptr<Slic3r::PrintRegion> &region : m_shared_regions->all_regions)
        out.emplace_back(*region.get());
    return out;
}
References Slic3r::PrintObjectRegions::all_regions, m_shared_regions, and out.
alloc_tree_support_preview_cache()
std::shared_ptr< TreeSupportData > Slic3r::PrintObject::alloc_tree_support_preview_cache ()
{
    if (!m_tree_support_preview_cache) {
        const coordf_t layer_height = m_config.layer_height.value;
        const coordf_t xy_distance = m_config.support_object_xy_distance.value;
        const double angle = m_config.tree_support_branch_angle.value * M_PI / 180.;
        const coordf_t max_move_distance
            = (angle < M_PI / 2) ? (coordf_t)(tan(angle) * layer_height) : std::numeric_limits<coordf_t>::max();
        const coordf_t radius_sample_resolution = g_config_tree_support_collision_resolution;
        m_tree_support_preview_cache = std::make_shared<TreeSupportData>(*this, xy_distance, max_move_distance, radius_sample_resolution);
    }
    return m_tree_support_preview_cache;
}
References Slic3r::angle(), g_config_tree_support_collision_resolution, Slic3r::layer_height(), M_PI, and tan().
apply_conical_overhang()
void Slic3r::PrintObject::apply_conical_overhang () private
{
    BOOST_LOG_TRIVIAL(info) << "Make overhang printable...";
    if (m_layers.empty()) {
        return;
    }
    const double conical_overhang_angle = this->config().make_overhang_printable_angle;
    if (conical_overhang_angle == 90.0) {
        return;
    }
    const double angle_radians = conical_overhang_angle * M_PI / 180.;
    const double max_hole_area = this->config().make_overhang_printable_hole_size; // in MM^2
    const double tan_angle = tan(angle_radians); // the XY-component of the angle
    BOOST_LOG_TRIVIAL(info) << "angle " << angle_radians << " maxHoleArea " << max_hole_area << " tan_angle "
                            << tan_angle;
    const coordf_t layer_thickness = m_config.layer_height.value;
    const coordf_t max_dist_from_lower_layer = tan_angle * layer_thickness; // max dist which can be bridged, in MM
    BOOST_LOG_TRIVIAL(info) << "layer_thickness " << layer_thickness << " max_dist_from_lower_layer "
                            << max_dist_from_lower_layer;
    // Pre-scale config
    const coordf_t scaled_max_dist_from_lower_layer = -float(scale_(max_dist_from_lower_layer));
    const coordf_t scaled_max_hole_area = float(scale_(scale_(max_hole_area)));
    for (auto i = m_layers.rbegin() + 1; i != m_layers.rend(); ++i) {
        m_print->throw_if_canceled();
        Layer *layer = *i;
        Layer *upper_layer = layer->upper_layer;
        if (upper_layer->empty()) {
          continue;
        }
        // Skip if entire layer has this disabled
        if (std::all_of(layer->m_regions.begin(), layer->m_regions.end(),
                        [](const LayerRegion *r) { return  r->slices.empty() || !r->region().config().make_overhang_printable; })) {
            continue;
        }
        //layer->export_region_slices_to_svg_debug("layer_before_conical_overhang");
        //upper_layer->export_region_slices_to_svg_debug("upper_layer_before_conical_overhang");
        // Merge the upper layer because we want to offset the entire layer uniformly, otherwise
        // the model could break at the region boundary.
        auto upper_poly = upper_layer->merged(float(SCALED_EPSILON));
        upper_poly = union_ex(upper_poly);
        // Avoid closing up of recessed holes in the base of a model.
        // Detects when a hole is completely covered by the layer above and removes the hole from the layer above before
        // adding it in.
        // This should have no effect any time a hole in a layer interacts with any polygon in the layer above
        if (scaled_max_hole_area > 0.0) {
            // Merge layer for the same reason
            auto current_poly = layer->merged(float(SCALED_EPSILON));
            current_poly = union_ex(current_poly);
            // Now go through all the holes in the current layer and check if they intersect anything in the layer above
            // If not, then they're the top of a hole and should be cut from the layer above before the union
            for (auto layer_polygon : current_poly) {
                for (auto hole : layer_polygon.holes) {
                    if (std::abs(hole.area()) < scaled_max_hole_area) {
                        ExPolygon hole_poly(hole);
                        auto hole_with_above = intersection_ex(upper_poly, hole_poly);
                        if (!hole_with_above.empty()) {
                            // The hole had some intersection with the above layer, check if it's a complete overlap
                            auto hole_difference = xor_ex(hole_with_above, hole_poly);
                            if (hole_difference.empty()) {
                                // The layer above completely cover it, remove it from the layer above
                                upper_poly = diff_ex(upper_poly, hole_poly);
                            }
                        }
                    }
                }
            }
        }
        // Now offset the upper layer to be added into current layer
        upper_poly = offset_ex(upper_poly, scaled_max_dist_from_lower_layer);
        for (size_t region_id = 0; region_id < this->num_printing_regions(); ++region_id) {
            // export_to_svg(debug_out_path("Surface-obj-%d-layer-%d-region-%d.svg", id().id, layer->id(), region_id).c_str(),
            //               layer->m_regions[region_id]->slices.surfaces);
            // Disable on given region
            if (!upper_layer->m_regions[region_id]->region().config().make_overhang_printable) {
                continue;
            }
            // Calculate the scaled upper poly that belongs to current region
            auto p = intersection_ex(upper_layer->m_regions[region_id]->slices.surfaces, upper_poly);
            // And now union it
            ExPolygons layer_polygons = to_expolygons(layer->m_regions[region_id]->slices.surfaces);
            layer->m_regions[region_id]->slices.set(union_ex(layer_polygons, p), stInternal);
        }
        //layer->export_region_slices_to_svg_debug("layer_after_conical_overhang");
    }
}
References Slic3r::Polygon::area(), Slic3r::diff_ex(), Slic3r::Layer::empty(), Slic3r::intersection_ex(), M_PI, Slic3r::Layer::m_regions, Slic3r::Layer::merged(), Slic3r::offset_ex(), scale_, SCALED_EPSILON, Slic3r::stInternal, tan(), Slic3r::to_expolygons(), Slic3r::union_ex(), Slic3r::Layer::upper_layer, and Slic3r::xor_ex().
assign_new_unique_ids_recursive()
virtual void Slic3r::ObjectBase::assign_new_unique_ids_recursive () inline protected virtual inherited
Reimplemented in Slic3r::Model, Slic3r::ModelObject, and Slic3r::ModelVolume.
{ this->set_new_unique_id(); }
References Slic3r::ObjectBase::set_new_unique_id().
bounding_box()
BoundingBox Slic3r::PrintObject::bounding_box () const inline
{ return BoundingBox(Point(- m_size.x() / 2, - m_size.y() / 2), Point(m_size.x() / 2, m_size.y() / 2)); }
References m_size.
Referenced by Slic3r::TreeSupport::TreeSupport(), Slic3r::SeamPlacer::init(), and Slic3r::Layer::make_fills().
bridge_over_infill()
void Slic3r::PrintObject::bridge_over_infill () private
{
    BOOST_LOG_TRIVIAL(info) << "Bridge over infill..." << log_memory_info();
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        const PrintRegion &region = this->printing_region(region_id);
        // skip bridging in case there are no voids
        if (region.config().sparse_infill_density.value == 100)
            continue;
    for (LayerPtrs::iterator layer_it = m_layers.begin(); layer_it != m_layers.end(); ++ layer_it) {
            // skip first layer
      if (layer_it == m_layers.begin())
                continue;
            Layer       *layer       = *layer_it;
            LayerRegion *layerm      = layer->m_regions[region_id];
            const PrintObjectConfig& object_config = layer->object()->config();
            //BBS: enable thick bridge for internal bridge only
            Flow         bridge_flow = layerm->bridging_flow(frSolidInfill, true);
            // extract the stInternalSolid surfaces that might be transformed into bridges
            Polygons internal_solid;
            layerm->fill_surfaces.filter_by_type(stInternalSolid, &internal_solid);
            // check whether the lower area is deep enough for absorbing the extra flow
            // (for obvious physical reasons but also for preventing the bridge extrudates
            // from overflowing in 3D preview)
            ExPolygons to_bridge;
            {
                Polygons to_bridge_pp = internal_solid;
                // iterate through lower layers spanned by bridge_flow
                double bottom_z = layer->print_z - bridge_flow.height() - EPSILON;
                for (int i = int(layer_it - m_layers.begin()) - 1; i >= 0; --i) {
                    const Layer* lower_layer = m_layers[i];
                    // stop iterating if layer is lower than bottom_z
                    if (lower_layer->print_z < bottom_z) break;
                    // iterate through regions and collect internal surfaces
                    Polygons lower_internal;
                    for (LayerRegion *lower_layerm : lower_layer->m_regions)
                        lower_layerm->fill_surfaces.filter_by_type(stInternal, &lower_internal);
                    // intersect such lower internal surfaces with the candidate solid surfaces
                    to_bridge_pp = intersection(to_bridge_pp, lower_internal);
                }
                // BBS: expand to make avoid gap between bridge and inner wall
                to_bridge_pp = expand(to_bridge_pp, bridge_flow.scaled_width());
                to_bridge_pp = intersection(to_bridge_pp, internal_solid);
                // there's no point in bridging too thin/short regions
                //FIXME Vojtech: The offset2 function is not a geometric offset,
                // therefore it may create 1) gaps, and 2) sharp corners, which are outside the original contour.
                // The gaps will be filled by a separate region, which makes the infill less stable and it takes longer.
                {
                    float min_width = float(bridge_flow.scaled_width()) * 3.f;
                    to_bridge_pp = opening(to_bridge_pp, min_width);
                }
                if (to_bridge_pp.empty()) continue;
                // convert into ExPolygons
                to_bridge = union_ex(to_bridge_pp);
            }
            #ifdef SLIC3R_DEBUG
            printf("Bridging %zu internal areas at layer %zu\n", to_bridge.size(), layer->id());
            #endif
            // compute the remaning internal solid surfaces as difference
            ExPolygons not_to_bridge = diff_ex(internal_solid, to_bridge, ApplySafetyOffset::Yes);
            to_bridge = intersection_ex(to_bridge, internal_solid, ApplySafetyOffset::Yes);
            // build the new collection of fill_surfaces
            layerm->fill_surfaces.remove_type(stInternalSolid);
            for (ExPolygon &ex : to_bridge) {
                layerm->fill_surfaces.surfaces.push_back(Surface(stInternalBridge, ex));
                // BBS: detect angle for internal bridge infill
                InternalBridgeDetector ibd(ex, layerm->fill_no_overlap_expolygons, bridge_flow.scaled_spacing());
                if (ibd.detect_angle()) {
                    (layerm->fill_surfaces.surfaces.end() - 1)->bridge_angle = ibd.angle;
                }
            }
            for (ExPolygon &ex : not_to_bridge)
                layerm->fill_surfaces.surfaces.push_back(Surface(stInternalSolid, ex));
            //BBS: modify stInternal to be stInternalWithLoop to give better support to internal bridge
            if (!to_bridge.empty()){
                float internal_loop_thickness = object_config.internal_bridge_support_thickness.value;
                double bottom_z = layer->print_z - layer->height - internal_loop_thickness + EPSILON;
                //BBS: lighting infill doesn't support this feature. Don't need to add loop when infill density is high than 50%
                if (region.config().sparse_infill_pattern != InfillPattern::ipLightning && region.config().sparse_infill_density.value < 50)
                    for (int i = int(layer_it - m_layers.begin()) - 1; i >= 0; --i) {
                        const Layer* lower_layer = m_layers[i];
                        if (lower_layer->print_z < bottom_z) break;
                        for (LayerRegion* lower_layerm : lower_layer->m_regions) {
                            Polygons lower_internal;
                            lower_layerm->fill_surfaces.filter_by_type(stInternal, &lower_internal);
                            ExPolygons internal_with_loop = intersection_ex(lower_internal, to_bridge);
                            ExPolygons internal = diff_ex(lower_internal, to_bridge);
                            if (internal_with_loop.empty()) {
                                //BBS: don't need to do anything
                            }
                            else if (internal.empty()) {
                                lower_layerm->fill_surfaces.change_to_new_type(stInternal, stInternalWithLoop);
                            }
                            else {
                                lower_layerm->fill_surfaces.remove_type(stInternal);
                                for (ExPolygon& ex : internal_with_loop)
                                    lower_layerm->fill_surfaces.surfaces.push_back(Surface(stInternalWithLoop, ex));
                                for (ExPolygon& ex : internal)
                                    lower_layerm->fill_surfaces.surfaces.push_back(Surface(stInternal, ex));
                            }
                        }
                    }
            }
            /*
            # exclude infill from the layers below if needed
            # see discussion at https://github.com/alexrj/Slic3r/issues/240
            # Update: do not exclude any infill. Sparse infill is able to absorb the excess material.
            if (0) {
                my $excess = $layerm->extruders->{infill}->bridge_flow->width - $layerm->height;
                for (my $i = $layer_id-1; $excess >= $self->get_layer($i)->height; $i--) {
                    Slic3r::debugf "  skipping infill below those areas at layer %d\n", $i;
                    foreach my $lower_layerm (@{$self->get_layer($i)->regions}) {
                        my @new_surfaces = ();
                        # subtract the area from all types of surfaces
                        foreach my $group (@{$lower_layerm->fill_surfaces->group}) {
                            push @new_surfaces, map $group->[0]->clone(expolygon => $_),
                                @{diff_ex(
                                    [ map $_->p, @$group ],
                                    [ map @$_, @$to_bridge ],
                                )};
                            push @new_surfaces, map Slic3r::Surface->new(
                                expolygon       => $_,
                                surface_type    => stInternalVoid,
                            ), @{intersection_ex(
                                [ map $_->p, @$group ],
                                [ map @$_, @$to_bridge ],
                            )};
                        }
                        $lower_layerm->fill_surfaces->clear;
                        $lower_layerm->fill_surfaces->append($_) for @new_surfaces;
                    }
                    $excess -= $self->get_layer($i)->height;
                }
            }
            */
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
            layerm->export_region_slices_to_svg_debug("7_bridge_over_infill");
            layerm->export_region_fill_surfaces_to_svg_debug("7_bridge_over_infill");
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
            m_print->throw_if_canceled();
References Slic3r::InternalBridgeDetector::angle, Slic3r::bridge_angle(), Slic3r::LayerRegion::bridging_flow(), Slic3r::PrintRegion::config(), config(), Slic3r::InternalBridgeDetector::detect_angle(), Slic3r::diff_ex(), EPSILON, Slic3r::expand(), Slic3r::LayerRegion::export_region_fill_surfaces_to_svg_debug(), Slic3r::LayerRegion::export_region_slices_to_svg_debug(), Slic3r::LayerRegion::fill_no_overlap_expolygons, Slic3r::LayerRegion::fill_surfaces, Slic3r::SurfaceCollection::filter_by_type(), Slic3r::frSolidInfill, Slic3r::Flow::height(), Slic3r::Layer::height, Slic3r::Layer::id(), Slic3r::intersection(), Slic3r::intersection_ex(), Slic3r::log_memory_info(), Slic3r::Layer::m_regions, Slic3r::Layer::object(), Slic3r::opening(), Slic3r::Layer::print_z, Slic3r::PrintObjectConfig, Slic3r::SurfaceCollection::remove_type(), Slic3r::Flow::scaled_spacing(), Slic3r::Flow::scaled_width(), Slic3r::stInternal, Slic3r::stInternalBridge, Slic3r::stInternalSolid, Slic3r::stInternalWithLoop, Slic3r::SurfaceCollection::surfaces, and Slic3r::union_ex().
cancel_callback()
std::function< void()> Slic3r::PrintObjectBase::cancel_callback (PrintBase * print) static protected inherited
{
  return print->cancel_callback();
}
References Slic3r::PrintBase::cancel_callback().
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::invalidate_all_steps(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::invalidate_step(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::invalidate_steps(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::invalidate_steps().
center_offset()
const Point & Slic3r::PrintObject::center_offset () const inline
{ return m_center_offset; }
References m_center_offset.
clear_layers()
void Slic3r::PrintObject::clear_layers ()
{
    if (!m_shared_object) {
        for (Layer *l : m_layers)
            delete l;
        m_layers.clear();
    }
}
Referenced by ~PrintObject().
clear_overhangs_for_lift()
void Slic3r::PrintObject::clear_overhangs_for_lift () private
{
    if (!m_shared_object) {
        for (Layer* l : m_layers)
            l->loverhangs.clear();
    }
}
clear_shared_object()
void Slic3r::PrintObject::clear_shared_object ()
{
    if (m_shared_object) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": this=%1%, clear previous shared object data %2%")%this %m_shared_object;
        m_layers.clear();
        m_support_layers.clear();
        m_shared_object = nullptr;
        invalidate_all_steps_without_cancel();
    }
}
References Slic3r::PrintObjectBaseWithState< Print, PrintObjectStep, posCount >::invalidate_all_steps_without_cancel(), m_layers, m_shared_object, and m_support_layers.
clear_support_layers()
void Slic3r::PrintObject::clear_support_layers ()
{
    if (!m_shared_object) {
        for (SupportLayer* l : m_support_layers)
            delete l;
        m_support_layers.clear();
        for (auto l : m_layers) {
            l->sharp_tails.clear();
            l->sharp_tails_height.clear();
            l->cantilevers.clear();
        }
    }
}
References Slic3r::Layer::sharp_tails.
Referenced by ~PrintObject(), and Slic3r::TreeSupport::detect_overhangs().
clear_tree_support_preview_cache()
void Slic3r::PrintObject::clear_tree_support_preview_cache () inline
{ m_tree_support_preview_cache.reset(); }
References m_tree_support_preview_cache.
Referenced by Slic3r::TreeSupport::detect_overhangs().
clip_fill_surfaces()
void Slic3r::PrintObject::clip_fill_surfaces () private
{
    if (! PrintObject::infill_only_where_needed)
        return;
    bool has_infill = false;
    for (size_t i = 0; i < this->num_printing_regions(); ++ i)
        if (this->printing_region(i).config().sparse_infill_density > 0) {
            has_infill = true;
            break;
        }
    if (! has_infill)
        return;
    // We only want infill under ceilings; this is almost like an
    // internal support material.
    // Proceed top-down, skipping the bottom layer.
    Polygons upper_internal;
    for (int layer_id = int(m_layers.size()) - 1; layer_id > 0; -- layer_id) {
        Layer *layer       = m_layers[layer_id];
        Layer *lower_layer = m_layers[layer_id - 1];
        // Detect things that we need to support.
        // Cummulative fill surfaces.
        Polygons fill_surfaces;
        // Solid surfaces to be supported.
        Polygons overhangs;
        for (const LayerRegion *layerm : layer->m_regions)
            for (const Surface &surface : layerm->fill_surfaces.surfaces) {
                Polygons polygons = to_polygons(surface.expolygon);
                if (surface.is_solid())
                    polygons_append(overhangs, polygons);
                polygons_append(fill_surfaces, std::move(polygons));
            }
        Polygons lower_layer_fill_surfaces;
        Polygons lower_layer_internal_surfaces;
        for (const LayerRegion *layerm : lower_layer->m_regions)
            for (const Surface &surface : layerm->fill_surfaces.surfaces) {
                Polygons polygons = to_polygons(surface.expolygon);
                if (surface.surface_type == stInternal || surface.surface_type == stInternalVoid)
                    polygons_append(lower_layer_internal_surfaces, polygons);
                polygons_append(lower_layer_fill_surfaces, std::move(polygons));
            }
        // We also need to support perimeters when there's at least one full unsupported loop
        {
            // Get perimeters area as the difference between slices and fill_surfaces
            // Only consider the area that is not supported by lower perimeters
            Polygons perimeters = intersection(diff(layer->lslices, fill_surfaces), lower_layer_fill_surfaces);
            // Only consider perimeter areas that are at least one extrusion width thick.
            //FIXME Offset2 eats out from both sides, while the perimeters are create outside in.
            //Should the pw not be half of the current value?
            float pw = FLT_MAX;
            for (const LayerRegion *layerm : layer->m_regions)
                pw = std::min(pw, (float)layerm->flow(frPerimeter).scaled_width());
            // Append such thick perimeters to the areas that need support
            polygons_append(overhangs, opening(perimeters, pw));
        }
        // Merge the new overhangs, find new internal infill.
        polygons_append(upper_internal, std::move(overhangs));
        static constexpr const auto closing_radius = scaled<float>(2.f);
        upper_internal = intersection(
            // Regularize the overhang regions, so that the infill areas will not become excessively jagged.
            smooth_outward(
                closing(upper_internal, closing_radius, ClipperLib::jtSquare, 0.),
                scaled<coord_t>(0.1)),
            lower_layer_internal_surfaces);
        // Apply new internal infill to regions.
        for (LayerRegion *layerm : lower_layer->m_regions) {
            if (layerm->region().config().sparse_infill_density.value == 0)
                continue;
            SurfaceType internal_surface_types[] = { stInternal, stInternalVoid };
            Polygons internal;
            for (Surface &surface : layerm->fill_surfaces.surfaces)
                if (surface.surface_type == stInternal || surface.surface_type == stInternalVoid)
                    polygons_append(internal, std::move(surface.expolygon));
            layerm->fill_surfaces.remove_types(internal_surface_types, 2);
            layerm->fill_surfaces.append(intersection_ex(internal, upper_internal, ApplySafetyOffset::Yes), stInternal);
            layerm->fill_surfaces.append(diff_ex        (internal, upper_internal, ApplySafetyOffset::Yes), stInternalVoid);
            // If there are voids it means that our internal infill is not adjacent to
            // perimeters. In this case it would be nice to add a loop around infill to
            // make it more robust and nicer. TODO.
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
            layerm->export_region_fill_surfaces_to_svg_debug("6_clip_fill_surfaces");
#endif
        }
References Slic3r::closing(), Slic3r::diff(), Slic3r::diff_ex(), Slic3r::frPerimeter, Slic3r::intersection(), Slic3r::intersection_ex(), ClipperLib::jtSquare, Slic3r::Layer::lslices, Slic3r::Layer::m_regions, Slic3r::opening(), Slic3r::polygons_append(), Slic3r::smooth_outward(), Slic3r::stInternal, Slic3r::stInternalVoid, and Slic3r::to_polygons().
combine_infill()
void Slic3r::PrintObject::combine_infill () private
{
    // Work on each region separately.
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        const PrintRegion &region = this->printing_region(region_id);
        //BBS
        const bool enable_combine_infill = region.config().infill_combination.value;
        if (enable_combine_infill == false || region.config().sparse_infill_density == 0.)
            continue;
        // Limit the number of combined layers to the maximum height allowed by this regions' nozzle.
        //FIXME limit the layer height to max_layer_height
        double nozzle_diameter = std::min(
            this->print()->config().nozzle_diameter.get_at(region.config().sparse_infill_filament.value - 1),
            this->print()->config().nozzle_diameter.get_at(region.config().solid_infill_filament.value - 1));
        // define the combinations
        std::vector<size_t> combine(m_layers.size(), 0);
        {
            double current_height = 0.;
            size_t num_layers = 0;
            for (size_t layer_idx = 0; layer_idx < m_layers.size(); ++ layer_idx) {
                m_print->throw_if_canceled();
                const Layer *layer = m_layers[layer_idx];
                if (layer->id() == 0)
                    // Skip first print layer (which may not be first layer in array because of raft).
                    continue;
                // Check whether the combination of this layer with the lower layers' buffer
                // would exceed max layer height or max combined layer count.
                // BBS: automatically calculate how many layers should be combined
                if (current_height + layer->height >= nozzle_diameter + EPSILON) {
                    // Append combination to lower layer.
                    combine[layer_idx - 1] = num_layers;
                    current_height = 0.;
                    num_layers = 0;
                }
                current_height += layer->height;
                ++ num_layers;
            }
            // Append lower layers (if any) to uppermost layer.
            combine[m_layers.size() - 1] = num_layers;
        }
        // loop through layers to which we have assigned layers to combine
        for (size_t layer_idx = 0; layer_idx < m_layers.size(); ++ layer_idx) {
            m_print->throw_if_canceled();
            size_t num_layers = combine[layer_idx];
      if (num_layers <= 1)
                continue;
            // Get all the LayerRegion objects to be combined.
            std::vector<LayerRegion*> layerms;
            layerms.reserve(num_layers);
      for (size_t i = layer_idx + 1 - num_layers; i <= layer_idx; ++ i)
                layerms.emplace_back(m_layers[i]->regions()[region_id]);
            // We need to perform a multi-layer intersection, so let's split it in pairs.
            // Initialize the intersection with the candidates of the lowest layer.
            ExPolygons intersection = to_expolygons(layerms.front()->fill_surfaces.filter_by_type(stInternal));
            // Start looping from the second layer and intersect the current intersection with it.
            for (size_t i = 1; i < layerms.size(); ++ i)
                intersection = intersection_ex(layerms[i]->fill_surfaces.filter_by_type(stInternal), intersection);
            double area_threshold = layerms.front()->infill_area_threshold();
            if (! intersection.empty() && area_threshold > 0.)
                intersection.erase(std::remove_if(intersection.begin(), intersection.end(),
                    [area_threshold](const ExPolygon &expoly) { return expoly.area() <= area_threshold; }),
                    intersection.end());
            if (intersection.empty())
                continue;
//            Slic3r::debugf "  combining %d %s regions from layers %d-%d\n",
//                scalar(@$intersection),
//                ($type == stInternal ? 'internal' : 'internal-solid'),
//                $layer_idx-($every-1), $layer_idx;
            // intersection now contains the regions that can be combined across the full amount of layers,
            // so let's remove those areas from all layers.
            Polygons intersection_with_clearance;
            intersection_with_clearance.reserve(intersection.size());
            float clearance_offset =
                0.5f * layerms.back()->flow(frPerimeter).scaled_width() +
             // Because fill areas for rectilinear and honeycomb are grown
             // later to overlap perimeters, we need to counteract that too.
                ((region.config().sparse_infill_pattern == ipRectilinear   ||
                  region.config().sparse_infill_pattern == ipMonotonic     ||
                  region.config().sparse_infill_pattern == ipGrid          ||
                  region.config().sparse_infill_pattern == ipLine          ||
                  region.config().sparse_infill_pattern == ipHoneycomb) ? 1.5f : 0.5f) *
                    layerms.back()->flow(frSolidInfill).scaled_width();
            for (ExPolygon &expoly : intersection)
                polygons_append(intersection_with_clearance, offset(expoly, clearance_offset));
            for (LayerRegion *layerm : layerms) {
                Polygons internal = to_polygons(std::move(layerm->fill_surfaces.filter_by_type(stInternal)));
                layerm->fill_surfaces.remove_type(stInternal);
                layerm->fill_surfaces.append(diff_ex(internal, intersection_with_clearance), stInternal);
                if (layerm == layerms.back()) {
                    // Apply surfaces back with adjusted depth to the uppermost layer.
                    Surface templ(stInternal, ExPolygon());
                    templ.thickness = 0.;
                    for (LayerRegion *layerm2 : layerms)
                        templ.thickness += layerm2->layer()->height;
                    templ.thickness_layers = (unsigned short)layerms.size();
                    layerm->fill_surfaces.append(intersection, templ);
                } else {
                    // Save void surfaces.
                    layerm->fill_surfaces.append(
                        intersection_ex(internal, intersection_with_clearance),
                        stInternalVoid);
                }
            }
References Slic3r::PrintRegion::config(), Slic3r::diff_ex(), EPSILON, Slic3r::frPerimeter, Slic3r::frSolidInfill, Slic3r::Layer::height, Slic3r::Layer::id(), Slic3r::intersection(), Slic3r::intersection_ex(), Slic3r::ipGrid, Slic3r::ipHoneycomb, Slic3r::ipLine, Slic3r::ipMonotonic, Slic3r::ipRectilinear, Slic3r::polygons_append(), Slic3r::stInternal, Slic3r::stInternalVoid, Slic3r::Surface::thickness, Slic3r::Surface::thickness_layers, Slic3r::to_expolygons(), and Slic3r::to_polygons().
config()
const PrintObjectConfig & Slic3r::PrintObject::config () const inline
{ return m_config; }
References m_config.
Referenced by Slic3r::FillLightning::Generator::Generator(), Slic3r::FillLightning::Generator::Generator(), Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::Print::apply(), bridge_over_infill(), Slic3r::TreeSupport::detect_overhangs(), Slic3r::group_fills(), has_brim(), Slic3r::SeamPlacer::init(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::Layer::make_fills(), Slic3r::Layer::make_ironing(), Slic3r::LayerRegion::make_perimeters(), Slic3r::SeamPlacer::place_seam(), Slic3r::LayerRegion::process_external_surfaces(), Slic3r::GCode::process_layer(), remove_bridges_from_contacts(), and Slic3r::SupportMaterialInternal::remove_bridges_from_contacts().
config_apply()
void Slic3r::PrintObject::config_apply (const ConfigBase & other, bool ignore_nonexistent = false) inline private
{ m_config.apply(other, ignore_nonexistent); }
References m_config.
Referenced by Slic3r::Print::apply().
config_apply_only()
void Slic3r::PrintObject::config_apply_only (const ConfigBase & other, const t_config_option_keys & keys, bool ignore_nonexistent = false) inline private
{ m_config.apply_only(other, keys, ignore_nonexistent); }
References m_config.
configBrimWidth()
void Slic3r::PrintObject::configBrimWidth (double m) inline
{m_config.brim_width.value = m; }
References m_config.
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
copy_layers_from_shared_object()
void Slic3r::PrintObject::copy_layers_from_shared_object ()
{
    if (m_shared_object) {
        m_layers.clear();
        m_support_layers.clear();
        firstLayerObjSliceByVolume.clear();
        firstLayerObjSliceByGroups.clear();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": this=%1%, copied layers from object %2%")%this%m_shared_object;
        m_layers = m_shared_object->layers();
        m_support_layers = m_shared_object->support_layers();
        firstLayerObjSliceByVolume = m_shared_object->firstLayerObjSlice();
        firstLayerObjSliceByGroups = m_shared_object->firstLayerObjGroups();
    }
}
References firstLayerObjGroups(), firstLayerObjSlice(), firstLayerObjSliceByGroups, firstLayerObjSliceByVolume, layers(), m_layers, m_shared_object, m_support_layers, and support_layers().
copy_layers_overhang_from_shared_object()
void Slic3r::PrintObject::copy_layers_overhang_from_shared_object ()
{
    if (m_shared_object) {
        for (size_t index = 0; index <  m_layers.size() && index <  m_shared_object->m_layers.size(); index++)
        {
            Layer* layer_src = m_layers[index];
            layer_src->loverhangs = m_shared_object->m_layers[index]->loverhangs;
            layer_src->loverhangs_bbox = m_shared_object->m_layers[index]->loverhangs_bbox;
        }
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": this=%1%, copied layer overhang from object %2%")%this%m_shared_object;
    }
}
References Slic3r::Layer::loverhangs, Slic3r::Layer::loverhangs_bbox, m_layers, and m_shared_object.
detect_overhangs_for_lift()
void Slic3r::PrintObject::detect_overhangs_for_lift () private
{
    if (this->set_started(posDetectOverhangsForLift)) {
        const double nozzle_diameter = m_print->config().nozzle_diameter.get_at(0);
        const coordf_t line_width = this->config().get_abs_value("line_width", nozzle_diameter);
        const float min_overlap = line_width * g_min_overhang_percent_for_lift;
        size_t num_layers = this->layer_count();
        size_t num_raft_layers = m_slicing_params.raft_layers();
        m_print->set_status(78, L("Detect overhangs for auto-lift"));
        this->clear_overhangs_for_lift();
        tbb::spin_mutex layer_storage_mutex;
        tbb::parallel_for(tbb::blocked_range<size_t>(num_raft_layers + 1, num_layers),
            [this, min_overlap, line_width](const tbb::blocked_range<size_t>& range)
            {
                for (size_t layer_id = range.begin(); layer_id < range.end(); ++layer_id) {
                    Layer& layer = *m_layers[layer_id];
                    Layer& lower_layer = *layer.lower_layer;
                    ExPolygons overhangs = diff_ex(layer.lslices, offset_ex(lower_layer.lslices, scale_(min_overlap)));
                    layer.loverhangs = std::move(offset2_ex(overhangs, -0.1f * scale_(line_width), 0.1f * scale_(line_width)));
                    layer.loverhangs_bbox = get_extents(layer.loverhangs);
                }
            });
        this->set_done(posDetectOverhangsForLift);
    }
}
References Slic3r::diff_ex(), Slic3r::g_min_overhang_percent_for_lift, Slic3r::get_extents(), L, Slic3r::Layer::loverhangs, Slic3r::Layer::loverhangs_bbox, Slic3r::Layer::lower_layer, Slic3r::Layer::lslices, Slic3r::offset2_ex(), Slic3r::offset_ex(), Slic3r::posDetectOverhangsForLift, Slic3r::range(), and scale_.
detect_surfaces_type()
void Slic3r::PrintObject::detect_surfaces_type () private
{
    BOOST_LOG_TRIVIAL(info) << "Detecting solid surfaces..." << log_memory_info();
    // Interface shells: the intersecting parts are treated as self standing objects supporting each other.
    // Each of the objects will have a full number of top / bottom layers, even if these top / bottom layers
    // are completely hidden inside a collective body of intersecting parts.
    // This is useful if one of the parts is to be dissolved, or if it is transparent and the internal shells
    // should be visible.
    bool spiral_mode      = this->print()->config().spiral_mode.value;
    bool interface_shells = ! spiral_mode && m_config.interface_shells.value;
    size_t num_layers     = spiral_mode ? std::min(size_t(this->printing_region(0).config().bottom_shell_layers), m_layers.size()) : m_layers.size();
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        BOOST_LOG_TRIVIAL(debug) << "Detecting solid surfaces for region " << region_id << " in parallel - start";
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
        for (Layer *layer : m_layers)
            layer->m_regions[region_id]->export_region_fill_surfaces_to_svg_debug("1_detect_surfaces_type-initial");
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
        // If interface shells are allowed, the region->surfaces cannot be overwritten as they may be used by other threads.
        // Cache the result of the following parallel_loop.
        std::vector<Surfaces> surfaces_new;
        if (interface_shells)
            surfaces_new.assign(num_layers, Surfaces());
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0,
              spiral_mode ?
                // In spiral vase mode, reserve the last layer for the top surface if more than 1 layer is planned for the vase bottom.
                ((num_layers > 1) ? num_layers - 1 : num_layers) :
                // In non-spiral vase mode, go over all layers.
                m_layers.size()),
            [this, region_id, interface_shells, &surfaces_new](const tbb::blocked_range<size_t>& range) {
                // If we have soluble support material, don't bridge. The overhang will be squished against a soluble layer separating
                // the support from the print.
                // BBS: the above logic only applys for normal(auto) support. Complete logic:
                // 1. has support, top z distance=0 (soluble material), auto support
                // 2. for normal(auto), bridge_no_support is off
                // 3. for tree(auto), interface top layers=0, max bridge length=0, support_critical_regions_only=false (only in this way the bridge is fully supported)
                bool bottom_is_fully_supported = this->has_support() && m_config.support_top_z_distance.value == 0 && is_auto(m_config.support_type.value);
                if (m_config.support_type.value == stNormalAuto)
                    bottom_is_fully_supported &= !m_config.bridge_no_support.value;
                else if (m_config.support_type.value == stTreeAuto) {
                    bottom_is_fully_supported &= (m_config.support_interface_top_layers.value > 0 && m_config.max_bridge_length.value == 0 && m_config.support_critical_regions_only.value==false);
                }
                SurfaceType surface_type_bottom_other = bottom_is_fully_supported ? stBottom : stBottomBridge;
                for (size_t idx_layer = range.begin(); idx_layer < range.end(); ++ idx_layer) {
                    m_print->throw_if_canceled();
                    // BOOST_LOG_TRIVIAL(trace) << "Detecting solid surfaces for region " << region_id << " and layer " << layer->print_z;
                    Layer       *layer  = m_layers[idx_layer];
                    LayerRegion *layerm = layer->m_regions[region_id];
                    // comparison happens against the *full* slices (considering all regions)
                    // unless internal shells are requested
                    Layer       *upper_layer = (idx_layer + 1 < this->layer_count()) ? m_layers[idx_layer + 1] : nullptr;
                    Layer       *lower_layer = (idx_layer > 0) ? m_layers[idx_layer - 1] : nullptr;
                    // collapse very narrow parts (using the safety offset in the diff is not enough)
                    float        offset = layerm->flow(frExternalPerimeter).scaled_width() / 10.f;
                    // find top surfaces (difference between current surfaces
                    // of current layer and upper one)
                    Surfaces top;
                    if (upper_layer) {
                        ExPolygons upper_slices = interface_shells ?
                            diff_ex(layerm->slices.surfaces, upper_layer->m_regions[region_id]->slices.surfaces, ApplySafetyOffset::Yes) :
                            diff_ex(layerm->slices.surfaces, upper_layer->lslices, ApplySafetyOffset::Yes);
                        surfaces_append(top, opening_ex(upper_slices, offset), stTop);
                    } else {
                        // if no upper layer, all surfaces of this one are solid
                        // we clone surfaces because we're going to clear the slices collection
                        top = layerm->slices.surfaces;
                        for (Surface &surface : top)
                            surface.surface_type = stTop;
                    }
                    // Find bottom surfaces (difference between current surfaces of current layer and lower one).
                    Surfaces bottom;
                    if (lower_layer) {
#if 0
                        //FIXME Why is this branch failing t\multi.t ?
                        Polygons lower_slices = interface_shells ?
                            to_polygons(lower_layer->get_region(region_id)->slices.surfaces) :
                            to_polygons(lower_layer->slices);
                        surfaces_append(bottom,
                            opening_ex(diff(layerm->slices.surfaces, lower_slices, true), offset),
                            surface_type_bottom_other);
#else
                        // Any surface lying on the void is a true bottom bridge (an overhang)
                        surfaces_append(
                            bottom,
                            opening_ex(
                                diff_ex(layerm->slices.surfaces, lower_layer->lslices, ApplySafetyOffset::Yes),
                                offset),
                            surface_type_bottom_other);
                        // if user requested internal shells, we need to identify surfaces
                        // lying on other slices not belonging to this region
                        if (interface_shells) {
                            // non-bridging bottom surfaces: any part of this layer lying
                            // on something else, excluding those lying on our own region
                            surfaces_append(
                                bottom,
                                opening_ex(
                                    diff_ex(
                                        intersection(layerm->slices.surfaces, lower_layer->lslices), // supported
                                        lower_layer->m_regions[region_id]->slices.surfaces,
                                        ApplySafetyOffset::Yes),
                                    offset),
                                stBottom);
                        }
#endif
                    } else {
                        // if no lower layer, all surfaces of this one are solid
                        // we clone surfaces because we're going to clear the slices collection
                        bottom = layerm->slices.surfaces;
                        for (Surface &surface : bottom)
                            surface.surface_type = stBottom;
                    }
                    // now, if the object contained a thin membrane, we could have overlapping bottom
                    // and top surfaces; let's do an intersection to discover them and consider them
                    // as bottom surfaces (to allow for bridge detection)
                    if (! top.empty() && ! bottom.empty()) {
        //                Polygons overlapping = intersection(to_polygons(top), to_polygons(bottom));
        //                Slic3r::debugf "  layer %d contains %d membrane(s)\n", $layerm->layer->id, scalar(@$overlapping)
        //                    if $Slic3r::debug;
                        Polygons top_polygons = to_polygons(std::move(top));
                        top.clear();
                        surfaces_append(top, diff_ex(top_polygons, bottom), stTop);
                    }
        #ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    {
                        static int iRun = 0;
                        std::vector<std::pair<Slic3r::ExPolygons, SVG::ExPolygonAttributes>> expolygons_with_attributes;
                        expolygons_with_attributes.emplace_back(std::make_pair(union_ex(top),                           SVG::ExPolygonAttributes("green")));
                        expolygons_with_attributes.emplace_back(std::make_pair(union_ex(bottom),                        SVG::ExPolygonAttributes("brown")));
                        expolygons_with_attributes.emplace_back(std::make_pair(to_expolygons(layerm->slices.surfaces),  SVG::ExPolygonAttributes("black")));
                        SVG::export_expolygons(debug_out_path("1_detect_surfaces_type_%d_region%d-layer_%f.svg", iRun ++, region_id, layer->print_z).c_str(), expolygons_with_attributes);
                    }
        #endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    // save surfaces to layer
                    Surfaces &surfaces_out = interface_shells ? surfaces_new[idx_layer] : layerm->slices.surfaces;
                    Surfaces  surfaces_backup;
                    if (! interface_shells) {
                        surfaces_backup = std::move(surfaces_out);
                        surfaces_out.clear();
                    }
                    const Surfaces &surfaces_prev = interface_shells ? layerm->slices.surfaces : surfaces_backup;
                    // find internal surfaces (difference between top/bottom surfaces and others)
                    {
                        Polygons topbottom = to_polygons(top);
                        polygons_append(topbottom, to_polygons(bottom));
                        surfaces_append(surfaces_out, diff_ex(surfaces_prev, topbottom), stInternal);
                    }
                    surfaces_append(surfaces_out, std::move(top));
                    surfaces_append(surfaces_out, std::move(bottom));
        //            Slic3r::debugf "  layer %d has %d bottom, %d top and %d internal surfaces\n",
        //                $layerm->layer->id, scalar(@bottom), scalar(@top), scalar(@internal) if $Slic3r::debug;
        #ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    layerm->export_region_slices_to_svg_debug("detect_surfaces_type-final");
        #endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                }
            }
        ); // for each layer of a region
        m_print->throw_if_canceled();
        if (interface_shells) {
            // Move surfaces_new to layerm->slices.surfaces
            for (size_t idx_layer = 0; idx_layer < num_layers; ++ idx_layer)
                m_layers[idx_layer]->m_regions[region_id]->slices.surfaces = std::move(surfaces_new[idx_layer]);
        }
        if (spiral_mode) {
          if (num_layers > 1)
            // Turn the last bottom layer infill to a top infill, so it will be extruded with a proper pattern.
            m_layers[num_layers - 1]->m_regions[region_id]->slices.set_type(stTop);
          for (size_t i = num_layers; i < m_layers.size(); ++ i)
            m_layers[i]->m_regions[region_id]->slices.set_type(stInternal);
        }
        BOOST_LOG_TRIVIAL(debug) << "Detecting solid surfaces for region " << region_id << " - clipping in parallel - start";
        // Fill in layerm->fill_surfaces by trimming the layerm->slices by the cummulative layerm->fill_surfaces.
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, m_layers.size()),
            [this, region_id](const tbb::blocked_range<size_t>& range) {
                for (size_t idx_layer = range.begin(); idx_layer < range.end(); ++ idx_layer) {
                    m_print->throw_if_canceled();
                    LayerRegion *layerm = m_layers[idx_layer]->m_regions[region_id];
                    layerm->slices_to_fill_surfaces_clipped();
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    layerm->export_region_fill_surfaces_to_svg_debug("1_detect_surfaces_type-final");
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                } // for each layer of a region
            });
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Detecting solid surfaces for region " << region_id << " - clipping in parallel - end";
    } // for each this->print->region_count
    // Mark the object to have the region slices classified (typed, which also means they are split based on whether they are supported, bridging, top layers etc.)
    m_typed_slices = true;
}
References Slic3r::bottom_shell_layers(), Slic3r::debug_out_path(), Slic3r::diff(), Slic3r::diff_ex(), Slic3r::LayerRegion::export_region_slices_to_svg_debug(), Slic3r::LayerRegion::flow(), Slic3r::frExternalPerimeter, Slic3r::Layer::get_region(), Slic3r::intersection(), Slic3r::is_auto(), Slic3r::log_memory_info(), Slic3r::Layer::lslices, Slic3r::Layer::m_regions, Slic3r::opening_ex(), Slic3r::polygons_append(), Slic3r::Layer::print_z, Slic3r::range(), Slic3r::Flow::scaled_width(), Slic3r::LayerRegion::slices, Slic3r::stBottom, Slic3r::stBottomBridge, Slic3r::stInternal, Slic3r::stNormalAuto, Slic3r::stTop, Slic3r::stTreeAuto, Slic3r::SurfaceCollection::surfaces, Slic3r::surfaces_append(), Slic3r::to_expolygons(), Slic3r::to_polygons(), and Slic3r::union_ex().
discover_horizontal_shells()
void Slic3r::PrintObject::discover_horizontal_shells () private
{
    BOOST_LOG_TRIVIAL(trace) << "discover_horizontal_shells()";
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        for (size_t i = 0; i < m_layers.size(); ++ i) {
            m_print->throw_if_canceled();
            Layer           *layer  = m_layers[i];
            LayerRegion             *layerm = layer->regions()[region_id];
            const PrintRegionConfig &region_config = layerm->region().config();
#if 0
            if (region_config.solid_infill_every_layers.value > 0 && region_config.sparse_infill_density.value > 0 &&
                (i % region_config.solid_infill_every_layers) == 0) {
                // Insert a solid internal layer. Mark stInternal surfaces as stInternalSolid or stInternalBridge.
                SurfaceType type = (region_config.sparse_infill_density == 100 || region_config.solid_infill_every_layers == 1) ? stInternalSolid : stInternalBridge;
                for (Surface &surface : layerm->fill_surfaces.surfaces)
                    if (surface.surface_type == stInternal)
                        surface.surface_type = type;
            }
#endif
            // If ensure_vertical_shell_thickness, then the rest has already been performed by discover_vertical_shells().
            if (region_config.ensure_vertical_shell_thickness.value)
                continue;
            coordf_t print_z  = layer->print_z;
            coordf_t bottom_z = layer->bottom_z();
            for (size_t idx_surface_type = 0; idx_surface_type < 3; ++ idx_surface_type) {
                m_print->throw_if_canceled();
                SurfaceType type = (idx_surface_type == 0) ? stTop : (idx_surface_type == 1) ? stBottom : stBottomBridge;
                int num_solid_layers = (type == stTop) ? region_config.top_shell_layers.value : region_config.bottom_shell_layers.value;
                if (num_solid_layers == 0)
                  continue;
                // Find slices of current type for current layer.
                // Use slices instead of fill_surfaces, because they also include the perimeter area,
                // which needs to be propagated in shells; we need to grow slices like we did for
                // fill_surfaces though. Using both ungrown slices and grown fill_surfaces will
                // not work in some situations, as there won't be any grown region in the perimeter
                // area (this was seen in a model where the top layer had one extra perimeter, thus
                // its fill_surfaces were thinner than the lower layer's infill), however it's the best
                // solution so far. Growing the external slices by EXTERNAL_INFILL_MARGIN will put
                // too much solid infill inside nearly-vertical slopes.
                // Surfaces including the area of perimeters. Everything, that is visible from the top / bottom
                // (not covered by a layer above / below).
                // This does not contain the areas covered by perimeters!
                Polygons solid;
                for (const Surface &surface : layerm->slices.surfaces)
                    if (surface.surface_type == type)
                        polygons_append(solid, to_polygons(surface.expolygon));
                // Infill areas (slices without the perimeters).
                for (const Surface &surface : layerm->fill_surfaces.surfaces)
                    if (surface.surface_type == type)
                        polygons_append(solid, to_polygons(surface.expolygon));
                if (solid.empty())
                    continue;
//                Slic3r::debugf "Layer %d has %s surfaces\n", $i, ($type == stTop) ? 'top' : 'bottom';
                // Scatter top / bottom regions to other layers. Scattering process is inherently serial, it is difficult to parallelize without locking.
                for (int n = (type == stTop) ? int(i) - 1 : int(i) + 1;
                  (type == stTop) ?
                    (n >= 0                   && (int(i) - n < num_solid_layers ||
                                    print_z - m_layers[n]->print_z < region_config.top_shell_thickness.value - EPSILON)) :
                    (n < int(m_layers.size()) && (n - int(i) < num_solid_layers ||
                                    m_layers[n]->bottom_z() - bottom_z < region_config.bottom_shell_thickness.value - EPSILON));
                  (type == stTop) ? -- n : ++ n)
                {
//                    Slic3r::debugf "  looking for neighbors on layer %d...\n", $n;
                    // Reference to the lower layer of a TOP surface, or an upper layer of a BOTTOM surface.
                    LayerRegion *neighbor_layerm = m_layers[n]->regions()[region_id];
                    // find intersection between neighbor and current layer's surfaces
                    // intersections have contours and holes
                    // we update $solid so that we limit the next neighbor layer to the areas that were
                    // found on this one - in other words, solid shells on one layer (for a given external surface)
                    // are always a subset of the shells found on the previous shell layer
                    // this approach allows for DWIM in hollow sloping vases, where we want bottom
                    // shells to be generated in the base but not in the walls (where there are many
                    // narrow bottom surfaces): reassigning $solid will consider the 'shadow' of the
                    // upper perimeter as an obstacle and shell will not be propagated to more upper layers
                    //FIXME How does it work for stInternalBRIDGE? This is set for sparse infill. Likely this does not work.
                    Polygons new_internal_solid;
                    {
                        Polygons internal;
                        for (const Surface &surface : neighbor_layerm->fill_surfaces.surfaces)
                            if (surface.surface_type == stInternal || surface.surface_type == stInternalSolid)
                                polygons_append(internal, to_polygons(surface.expolygon));
                        new_internal_solid = intersection(solid, internal, ApplySafetyOffset::Yes);
                    }
                    if (new_internal_solid.empty()) {
                        // No internal solid needed on this layer. In order to decide whether to continue
                        // searching on the next neighbor (thus enforcing the configured number of solid
                        // layers, use different strategies according to configured infill density:
                        if (region_config.sparse_infill_density.value == 0) {
                            // If user expects the object to be void (for example a hollow sloping vase),
                            // don't continue the search. In this case, we only generate the external solid
                            // shell if the object would otherwise show a hole (gap between perimeters of
                            // the two layers), and internal solid shells are a subset of the shells found
                            // on each previous layer.
                            goto EXTERNAL;
                        } else {
                            // If we have internal infill, we can generate internal solid shells freely.
                            continue;
                        }
                    }
                    if (region_config.sparse_infill_density.value == 0) {
                        // if we're printing a hollow object we discard any solid shell thinner
                        // than a perimeter width, since it's probably just crossing a sloping wall
                        // and it's not wanted in a hollow print even if it would make sense when
                        // obeying the solid shell count option strictly (DWIM!)
                        float margin = float(neighbor_layerm->flow(frExternalPerimeter).scaled_width());
                        Polygons too_narrow = diff(
                            new_internal_solid,
                            opening(new_internal_solid, margin, margin + ClipperSafetyOffset, jtMiter, 5));
                        // Trim the regularized region by the original region.
                        if (! too_narrow.empty())
                            new_internal_solid = solid = diff(new_internal_solid, too_narrow);
                    }
                    // make sure the new internal solid is wide enough, as it might get collapsed
                    // when spacing is added in Fill.pm
                    {
                        //FIXME Vojtech: Disable this and you will be sorry.
                        float margin = 3.f * layerm->flow(frSolidInfill).scaled_width(); // require at least this size
                        // we use a higher miterLimit here to handle areas with acute angles
                        // in those cases, the default miterLimit would cut the corner and we'd
                        // get a triangle in $too_narrow; if we grow it below then the shell
                        // would have a different shape from the external surface and we'd still
                        // have the same angle, so the next shell would be grown even more and so on.
                        Polygons too_narrow = diff(
                            new_internal_solid,
                            opening(new_internal_solid, margin, margin + ClipperSafetyOffset, ClipperLib::jtMiter, 5));
                        if (! too_narrow.empty()) {
                            // grow the collapsing parts and add the extra area to  the neighbor layer
                            // as well as to our original surfaces so that we support this
                            // additional area in the next shell too
                            // make sure our grown surfaces don't exceed the fill area
                            Polygons internal;
                            for (const Surface &surface : neighbor_layerm->fill_surfaces.surfaces)
                                if (surface.is_internal() && !surface.is_bridge())
                                    polygons_append(internal, to_polygons(surface.expolygon));
                            polygons_append(new_internal_solid,
                                intersection(
                                    expand(too_narrow, +margin),
                                    // Discard bridges as they are grown for anchoring and we can't
                                    // remove such anchors. (This may happen when a bridge is being
                                    // anchored onto a wall where little space remains after the bridge
                                    // is grown, and that little space is an internal solid shell so
                                    // it triggers this too_narrow logic.)
                                    internal));
                            // solid = new_internal_solid;
                        }
                    }
                    // internal-solid are the union of the existing internal-solid surfaces
                    // and new ones
                    SurfaceCollection backup = std::move(neighbor_layerm->fill_surfaces);
                    polygons_append(new_internal_solid, to_polygons(backup.filter_by_type(stInternalSolid)));
                    ExPolygons internal_solid = union_ex(new_internal_solid);
                    // assign new internal-solid surfaces to layer
                    neighbor_layerm->fill_surfaces.set(internal_solid, stInternalSolid);
                    // subtract intersections from layer surfaces to get resulting internal surfaces
                    Polygons polygons_internal = to_polygons(std::move(internal_solid));
                    ExPolygons internal = diff_ex(backup.filter_by_type(stInternal), polygons_internal, ApplySafetyOffset::Yes);
                    // assign resulting internal surfaces to layer
                    neighbor_layerm->fill_surfaces.append(internal, stInternal);
                    polygons_append(polygons_internal, to_polygons(std::move(internal)));
                    // assign top and bottom surfaces to layer
                    SurfaceType surface_types_solid[] = { stTop, stBottom, stBottomBridge };
                    backup.keep_types(surface_types_solid, 3);
                    std::vector<SurfacesPtr> top_bottom_groups;
                    backup.group(&top_bottom_groups);
                    for (SurfacesPtr &group : top_bottom_groups)
                        neighbor_layerm->fill_surfaces.append(
                            diff_ex(group, polygons_internal),
                            // Use an existing surface as a template, it carries the bridge angle etc.
                            *group.front());
                }
    EXTERNAL:;
            } // foreach type (stTop, stBottom, stBottomBridge)
        } // for each layer
    } // for each region
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        for (const Layer *layer : m_layers) {
            const LayerRegion *layerm = layer->m_regions[region_id];
            layerm->export_region_slices_to_svg_debug("5_discover_horizontal_shells");
            layerm->export_region_fill_surfaces_to_svg_debug("5_discover_horizontal_shells");
        } // for each layer
discover_vertical_shells()
void Slic3r::PrintObject::discover_vertical_shells () private
{
    PROFILE_FUNC();
    BOOST_LOG_TRIVIAL(info) << "Discovering vertical shells..." << log_memory_info();
    struct DiscoverVerticalShellsCacheEntry
    {
        // Collected polygons, offsetted
        Polygons    top_surfaces;
        Polygons    bottom_surfaces;
        Polygons    holes;
    };
    bool     spiral_mode      = this->print()->config().spiral_mode.value;
    size_t   num_layers       = spiral_mode ? std::min(size_t(this->printing_region(0).config().bottom_shell_layers), m_layers.size()) : m_layers.size();
    coordf_t min_layer_height = this->slicing_parameters().min_layer_height;
    // Does this region possibly produce more than 1 top or bottom layer?
    auto has_extra_layers_fn = [min_layer_height](const PrintRegionConfig &config) {
      auto num_extra_layers = [min_layer_height](int num_solid_layers, coordf_t min_shell_thickness) {
        if (num_solid_layers == 0)
          return 0;
        int n = num_solid_layers - 1;
        int n2 = int(ceil(min_shell_thickness / min_layer_height));
        return std::max(n, n2 - 1);
      };
      return num_extra_layers(config.top_shell_layers, config.top_shell_thickness) +
           num_extra_layers(config.bottom_shell_layers, config.bottom_shell_thickness) > 0;
    };
    std::vector<DiscoverVerticalShellsCacheEntry> cache_top_botom_regions(num_layers, DiscoverVerticalShellsCacheEntry());
    bool top_bottom_surfaces_all_regions = this->num_printing_regions() > 1 && ! m_config.interface_shells.value;
    if (top_bottom_surfaces_all_regions) {
        // This is a multi-material print and interface_shells are disabled, meaning that the vertical shell thickness
        // is calculated over all materials.
        // Is the "ensure vertical wall thickness" applicable to any region?
        bool has_extra_layers = false;
        for (size_t region_id = 0; region_id < this->num_printing_regions(); ++region_id) {
            const PrintRegionConfig &config = this->printing_region(region_id).config();
            if (config.ensure_vertical_shell_thickness.value && has_extra_layers_fn(config)) {
                has_extra_layers = true;
                break;
            }
        }
        if (! has_extra_layers)
            // The "ensure vertical wall thickness" feature is not applicable to any of the regions. Quit.
            return;
        BOOST_LOG_TRIVIAL(debug) << "Discovering vertical shells in parallel - start : cache top / bottom";
        //FIXME Improve the heuristics for a grain size.
        size_t grain_size = std::max(num_layers / 16, size_t(1));
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, num_layers, grain_size),
            [this, &cache_top_botom_regions](const tbb::blocked_range<size_t>& range) {
                const SurfaceType surfaces_bottom[2] = { stBottom, stBottomBridge };
                const size_t num_regions = this->num_printing_regions();
                for (size_t idx_layer = range.begin(); idx_layer < range.end(); ++ idx_layer) {
                    m_print->throw_if_canceled();
                    const Layer                      &layer = *m_layers[idx_layer];
                    DiscoverVerticalShellsCacheEntry &cache = cache_top_botom_regions[idx_layer];
                    // Simulate single set of perimeters over all merged regions.
                    float                             perimeter_offset = 0.f;
                    float                             perimeter_min_spacing = FLT_MAX;
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    static size_t debug_idx = 0;
                    ++ debug_idx;
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    for (size_t region_id = 0; region_id < num_regions; ++ region_id) {
                        LayerRegion &layerm                       = *layer.m_regions[region_id];
                        float        min_perimeter_infill_spacing = float(layerm.flow(frSolidInfill).scaled_spacing()) * 1.05f;
                        // Top surfaces.
                        append(cache.top_surfaces, offset(layerm.slices.filter_by_type(stTop), min_perimeter_infill_spacing));
                        append(cache.top_surfaces, offset(layerm.fill_surfaces.filter_by_type(stTop), min_perimeter_infill_spacing));
                        // Bottom surfaces.
                        append(cache.bottom_surfaces, offset(layerm.slices.filter_by_types(surfaces_bottom, 2), min_perimeter_infill_spacing));
                        append(cache.bottom_surfaces, offset(layerm.fill_surfaces.filter_by_types(surfaces_bottom, 2), min_perimeter_infill_spacing));
                        // Calculate the maximum perimeter offset as if the slice was extruded with a single extruder only.
                        // First find the maxium number of perimeters per region slice.
                        unsigned int perimeters = 0;
                        for (Surface &s : layerm.slices.surfaces)
                            perimeters = std::max<unsigned int>(perimeters, s.extra_perimeters);
                        perimeters += layerm.region().config().wall_loops.value;
                        // Then calculate the infill offset.
                        if (perimeters > 0) {
                            Flow extflow = layerm.flow(frExternalPerimeter);
                            Flow flow    = layerm.flow(frPerimeter);
                            perimeter_offset = std::max(perimeter_offset,
                                0.5f * float(extflow.scaled_width() + extflow.scaled_spacing()) + (float(perimeters) - 1.f) * flow.scaled_spacing());
                            perimeter_min_spacing = std::min(perimeter_min_spacing, float(std::min(extflow.scaled_spacing(), flow.scaled_spacing())));
                        }
                        polygons_append(cache.holes, to_polygons(layerm.fill_expolygons));
                    }
                    // Save some computing time by reducing the number of polygons.
                    cache.top_surfaces    = union_(cache.top_surfaces);
                    cache.bottom_surfaces = union_(cache.bottom_surfaces);
                    // For a multi-material print, simulate perimeter / infill split as if only a single extruder has been used for the whole print.
                    if (perimeter_offset > 0.) {
                        // The layer.lslices are forced to merge by expanding them first.
                        polygons_append(cache.holes, offset2(layer.lslices, 0.3f * perimeter_min_spacing, - perimeter_offset - 0.3f * perimeter_min_spacing));
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
{
                            Slic3r::SVG svg(debug_out_path("discover_vertical_shells-extra-holes-%d.svg", debug_idx), get_extents(layer.lslices));
                            svg.draw(layer.lslices, "blue");
                            svg.draw(union_ex(cache.holes), "red");
                            svg.draw_outline(union_ex(cache.holes), "black", "blue", scale_(0.05));
                            svg.Close();
                        }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    }
                    cache.holes = union_(cache.holes);
                }
            });
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Discovering vertical shells in parallel - end : cache top / bottom";
    }
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        PROFILE_BLOCK(discover_vertical_shells_region);
        const PrintRegion &region = this->printing_region(region_id);
        if (! region.config().ensure_vertical_shell_thickness.value)
            // This region will be handled by discover_horizontal_shells().
            continue;
        if (! has_extra_layers_fn(region.config()))
            // Zero or 1 layer, there is no additional vertical wall thickness enforced.
            continue;
        //FIXME Improve the heuristics for a grain size.
        size_t grain_size = std::max(num_layers / 16, size_t(1));
        if (! top_bottom_surfaces_all_regions) {
            // This is either a single material print, or a multi-material print and interface_shells are enabled, meaning that the vertical shell thickness
            // is calculated over a single material.
            BOOST_LOG_TRIVIAL(debug) << "Discovering vertical shells for region " << region_id << " in parallel - start : cache top / bottom";
            tbb::parallel_for(
                tbb::blocked_range<size_t>(0, num_layers, grain_size),
                [this, region_id, &cache_top_botom_regions](const tbb::blocked_range<size_t>& range) {
                    const SurfaceType surfaces_bottom[2] = { stBottom, stBottomBridge };
                    for (size_t idx_layer = range.begin(); idx_layer < range.end(); ++ idx_layer) {
                        m_print->throw_if_canceled();
                        Layer       &layer                        = *m_layers[idx_layer];
                        LayerRegion &layerm                       = *layer.m_regions[region_id];
                        float        min_perimeter_infill_spacing = float(layerm.flow(frSolidInfill).scaled_spacing()) * 1.05f;
                        // Top surfaces.
                        auto &cache = cache_top_botom_regions[idx_layer];
                        cache.top_surfaces = offset(layerm.slices.filter_by_type(stTop), min_perimeter_infill_spacing);
                        append(cache.top_surfaces, offset(layerm.fill_surfaces.filter_by_type(stTop), min_perimeter_infill_spacing));
                        // Bottom surfaces.
                        cache.bottom_surfaces = offset(layerm.slices.filter_by_types(surfaces_bottom, 2), min_perimeter_infill_spacing);
                        append(cache.bottom_surfaces, offset(layerm.fill_surfaces.filter_by_types(surfaces_bottom, 2), min_perimeter_infill_spacing));
                        // Holes over all regions. Only collect them once, they are valid for all region_id iterations.
                        if (cache.holes.empty()) {
                            for (size_t region_id = 0; region_id < layer.regions().size(); ++ region_id)
                                polygons_append(cache.holes, to_polygons(layer.regions()[region_id]->fill_expolygons));
                        }
                    }
                });
            m_print->throw_if_canceled();
            BOOST_LOG_TRIVIAL(debug) << "Discovering vertical shells for region " << region_id << " in parallel - end : cache top / bottom";
        }
        BOOST_LOG_TRIVIAL(debug) << "Discovering vertical shells for region " << region_id << " in parallel - start : ensure vertical wall thickness";
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, num_layers, grain_size),
            [this, region_id, &cache_top_botom_regions]
            (const tbb::blocked_range<size_t>& range) {
                // printf("discover_vertical_shells from %d to %d\n", range.begin(), range.end());
                for (size_t idx_layer = range.begin(); idx_layer < range.end(); ++ idx_layer) {
                    PROFILE_BLOCK(discover_vertical_shells_region_layer);
                    m_print->throw_if_canceled();
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
              static size_t debug_idx = 0;
              ++ debug_idx;
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    Layer                 *layer          = m_layers[idx_layer];
                    LayerRegion           *layerm         = layer->m_regions[region_id];
                    const PrintRegionConfig &region_config  = layerm->region().config();
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    layerm->export_region_slices_to_svg_debug("4_discover_vertical_shells-initial");
                    layerm->export_region_fill_surfaces_to_svg_debug("4_discover_vertical_shells-initial");
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    Flow         solid_infill_flow   = layerm->flow(frSolidInfill);
                    coord_t      infill_line_spacing = solid_infill_flow.scaled_spacing();
                    // Find a union of perimeters below / above this surface to guarantee a minimum shell thickness.
                    Polygons shell;
                    Polygons holes;
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    ExPolygons shell_ex;
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    float min_perimeter_infill_spacing = float(infill_line_spacing) * 1.05f;
                    {
                        PROFILE_BLOCK(discover_vertical_shells_region_layer_collect);
#if 0
// #ifdef SLIC3R_DEBUG_SLICE_PROCESSING
{
                  Slic3r::SVG svg_cummulative(debug_out_path("discover_vertical_shells-perimeters-before-union-run%d.svg", debug_idx), this->bounding_box());
                            for (int n = (int)idx_layer - n_extra_bottom_layers; n <= (int)idx_layer + n_extra_top_layers; ++ n) {
                                if (n < 0 || n >= (int)m_layers.size())
                                    continue;
                                ExPolygons &expolys = m_layers[n]->perimeter_expolygons;
                                for (size_t i = 0; i < expolys.size(); ++ i) {
                      Slic3r::SVG svg(debug_out_path("discover_vertical_shells-perimeters-before-union-run%d-layer%d-expoly%d.svg", debug_idx, n, i), get_extents(expolys[i]));
                                    svg.draw(expolys[i]);
                                    svg.draw_outline(expolys[i].contour, "black", scale_(0.05));
                                    svg.draw_outline(expolys[i].holes, "blue", scale_(0.05));
                                    svg.Close();
                                    svg_cummulative.draw(expolys[i]);
                                    svg_cummulative.draw_outline(expolys[i].contour, "black", scale_(0.05));
                                    svg_cummulative.draw_outline(expolys[i].holes, "blue", scale_(0.05));
                                }
                            }
                        }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                polygons_append(holes, cache_top_botom_regions[idx_layer].holes);
                if (int n_top_layers = region_config.top_shell_layers.value; n_top_layers > 0) {
                            // Gather top regions projected to this layer.
                            coordf_t print_z = layer->print_z;
                          for (int i = int(idx_layer) + 1;
                            i < int(cache_top_botom_regions.size()) &&
                              (i < int(idx_layer) + n_top_layers ||
                               m_layers[i]->print_z - print_z < region_config.top_shell_thickness - EPSILON);
                            ++ i) {
                              const DiscoverVerticalShellsCacheEntry &cache = cache_top_botom_regions[i];
                if (! holes.empty())
                  holes = intersection(holes, cache.holes);
                if (! cache.top_surfaces.empty()) {
                                polygons_append(shell, cache.top_surfaces);
                                // Running the union_ using the Clipper library piece by piece is cheaper
                                // than running the union_ all at once.
                                 shell = union_(shell);
                             }
                          }
                      }
                      if (int n_bottom_layers = region_config.bottom_shell_layers.value; n_bottom_layers > 0) {
                            // Gather bottom regions projected to this layer.
                            coordf_t bottom_z = layer->bottom_z();
                          for (int i = int(idx_layer) - 1;
                            i >= 0 &&
                              (i > int(idx_layer) - n_bottom_layers ||
                               bottom_z - m_layers[i]->bottom_z() < region_config.bottom_shell_thickness - EPSILON);
                            -- i) {
                              const DiscoverVerticalShellsCacheEntry &cache = cache_top_botom_regions[i];
                if (! holes.empty())
                  holes = intersection(holes, cache.holes);
                if (! cache.bottom_surfaces.empty()) {
                                polygons_append(shell, cache.bottom_surfaces);
                                // Running the union_ using the Clipper library piece by piece is cheaper
                                // than running the union_ all at once.
                                shell = union_(shell);
                            }
                          }
                      }
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
{
                  Slic3r::SVG svg(debug_out_path("discover_vertical_shells-perimeters-before-union-%d.svg", debug_idx), get_extents(shell));
                            svg.draw(shell);
                            svg.draw_outline(shell, "black", scale_(0.05));
                            svg.Close();
                        }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
#if 0
{
                            PROFILE_BLOCK(discover_vertical_shells_region_layer_shell_);
        //                    shell = union_(shell, true);
                            shell = union_(shell, false);
                        }
#endif
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                        shell_ex = union_safety_offset_ex(shell);
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    }
                    //if (shell.empty())
                    //    continue;
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    {
                        Slic3r::SVG svg(debug_out_path("discover_vertical_shells-perimeters-after-union-%d.svg", debug_idx), get_extents(shell));
                        svg.draw(shell_ex);
                        svg.draw_outline(shell_ex, "black", "blue", scale_(0.05));
                        svg.Close();
                    }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    {
                        Slic3r::SVG svg(debug_out_path("discover_vertical_shells-internal-wshell-%d.svg", debug_idx), get_extents(shell));
                        svg.draw(layerm->fill_surfaces.filter_by_type(stInternal), "yellow", 0.5);
                        svg.draw_outline(layerm->fill_surfaces.filter_by_type(stInternal), "black", "blue", scale_(0.05));
                        svg.draw(shell_ex, "blue", 0.5);
                        svg.draw_outline(shell_ex, "black", "blue", scale_(0.05));
                        svg.Close();
                    }
                    {
                        Slic3r::SVG svg(debug_out_path("discover_vertical_shells-internalvoid-wshell-%d.svg", debug_idx), get_extents(shell));
                        svg.draw(layerm->fill_surfaces.filter_by_type(stInternalVoid), "yellow", 0.5);
                        svg.draw_outline(layerm->fill_surfaces.filter_by_type(stInternalVoid), "black", "blue", scale_(0.05));
                        svg.draw(shell_ex, "blue", 0.5);
                        svg.draw_outline(shell_ex, "black", "blue", scale_(0.05));
                        svg.Close();
                    }
                    {
                        Slic3r::SVG svg(debug_out_path("discover_vertical_shells-internalvoid-wshell-%d.svg", debug_idx), get_extents(shell));
                        svg.draw(layerm->fill_surfaces.filter_by_type(stInternalVoid), "yellow", 0.5);
                        svg.draw_outline(layerm->fill_surfaces.filter_by_type(stInternalVoid), "black", "blue", scale_(0.05));
                        svg.draw(shell_ex, "blue", 0.5);
                        svg.draw_outline(shell_ex, "black", "blue", scale_(0.05));
                        svg.Close();
                    }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    // Trim the shells region by the internal & internal void surfaces.
                    const SurfaceType surfaceTypesInternal[] = { stInternal, stInternalVoid, stInternalSolid };
                    const Polygons    polygonsInternal = to_polygons(layerm->fill_surfaces.filter_by_types(surfaceTypesInternal, 3));
                    shell = intersection(shell, polygonsInternal, ApplySafetyOffset::Yes);
                    polygons_append(shell, diff(polygonsInternal, holes));
                    if (shell.empty())
                        continue;
                    // Append the internal solids, so they will be merged with the new ones.
                    polygons_append(shell, to_polygons(layerm->fill_surfaces.filter_by_type(stInternalSolid)));
                    // These regions will be filled by a rectilinear full infill. Currently this type of infill
                    // only fills regions, which fit at least a single line. To avoid gaps in the sparse infill,
                    // make sure that this region does not contain parts narrower than the infill spacing width.
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    Polygons shell_before = shell;
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
#if 1
                    // Intentionally inflate a bit more than how much the region has been shrunk,
                    // so there will be some overlap between this solid infill and the other infill regions (mainly the sparse infill).
                    shell = opening(union_(shell), 0.5f * min_perimeter_infill_spacing, 0.8f * min_perimeter_infill_spacing, ClipperLib::jtSquare);
                    if (shell.empty())
                        continue;
#else
                    // Ensure each region is at least 3x infill line width wide, so it could be filled in.
        //            float margin = float(infill_line_spacing) * 3.f;
                    float margin = float(infill_line_spacing) * 1.5f;
                    // we use a higher miterLimit here to handle areas with acute angles
                    // in those cases, the default miterLimit would cut the corner and we'd
                    // get a triangle in $too_narrow; if we grow it below then the shell
                    // would have a different shape from the external surface and we'd still
                    // have the same angle, so the next shell would be grown even more and so on.
                    Polygons too_narrow = diff(shell, opening(shell, margin, ClipperLib::jtMiter, 5.), true);
                    if (! too_narrow.empty()) {
                        // grow the collapsing parts and add the extra area to  the neighbor layer
                        // as well as to our original surfaces so that we support this
                        // additional area in the next shell too
                        // make sure our grown surfaces don't exceed the fill area
                        polygons_append(shell, intersection(offset(too_narrow, margin), polygonsInternal));
                    }
#endif
                    ExPolygons new_internal_solid = intersection_ex(polygonsInternal, shell);
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    {
                        Slic3r::SVG svg(debug_out_path("discover_vertical_shells-regularized-%d.svg", debug_idx), get_extents(shell_before));
                        // Source shell.
                        svg.draw(union_safety_offset_ex(shell_before));
                        // Shell trimmed to the internal surfaces.
                        svg.draw_outline(union_safety_offset_ex(shell), "black", "blue", scale_(0.05));
                        // Regularized infill region.
                        svg.draw_outline(new_internal_solid, "red", "magenta", scale_(0.05));
                        svg.Close();
                    }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    // Trim the internal & internalvoid by the shell.
                    Slic3r::ExPolygons new_internal = diff_ex(layerm->fill_surfaces.filter_by_type(stInternal), shell);
                    Slic3r::ExPolygons new_internal_void = diff_ex(layerm->fill_surfaces.filter_by_type(stInternalVoid), shell);
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
                    {
                        SVG::export_expolygons(debug_out_path("discover_vertical_shells-new_internal-%d.svg", debug_idx), get_extents(shell), new_internal, "black", "blue", scale_(0.05));
                SVG::export_expolygons(debug_out_path("discover_vertical_shells-new_internal_void-%d.svg", debug_idx), get_extents(shell), new_internal_void, "black", "blue", scale_(0.05));
                SVG::export_expolygons(debug_out_path("discover_vertical_shells-new_internal_solid-%d.svg", debug_idx), get_extents(shell), new_internal_solid, "black", "blue", scale_(0.05));
                    }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
                    // Assign resulting internal surfaces to layer.
                    const SurfaceType surfaceTypesKeep[] = { stTop, stBottom, stBottomBridge };
                    layerm->fill_surfaces.keep_types(surfaceTypesKeep, sizeof(surfaceTypesKeep)/sizeof(SurfaceType));
                    layerm->fill_surfaces.append(new_internal,       stInternal);
                    layerm->fill_surfaces.append(new_internal_void,  stInternalVoid);
                    layerm->fill_surfaces.append(new_internal_solid, stInternalSolid);
                } // for each layer
            });
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Discovering vertical shells for region " << region_id << " in parallel - end";
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
    for (size_t idx_layer = 0; idx_layer < m_layers.size(); ++idx_layer) {
      LayerRegion *layerm = m_layers[idx_layer]->get_region(region_id);
      layerm->export_region_slices_to_svg_debug("4_discover_vertical_shells-final");
      layerm->export_region_fill_surfaces_to_svg_debug("4_discover_vertical_shells-final");
    }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
    } // for each region
    // Write the profiler measurements to file
//    PROFILE_UPDATE();
//    PROFILE_OUTPUT(debug_out_path("discover_vertical_shells-profile.txt").c_str());
}
References Slic3r::SurfaceCollection::append(), Slic3r::append(), Slic3r::bottom_shell_layers(), Slic3r::Layer::bottom_z(), ceil(), Slic3r::SVG::Close(), Slic3r::PrintRegion::config(), Slic3r::debug_out_path(), Slic3r::diff(), Slic3r::diff_ex(), Slic3r::SVG::draw(), Slic3r::SVG::draw_outline(), EPSILON, Slic3r::LayerRegion::export_region_fill_surfaces_to_svg_debug(), Slic3r::LayerRegion::export_region_slices_to_svg_debug(), Slic3r::LayerRegion::fill_expolygons, Slic3r::LayerRegion::fill_surfaces, Slic3r::SurfaceCollection::filter_by_type(), Slic3r::SurfaceCollection::filter_by_types(), Slic3r::LayerRegion::flow(), Slic3r::frExternalPerimeter, Slic3r::frPerimeter, Slic3r::frSolidInfill, Slic3r::get_extents(), int, Slic3r::intersection(), Slic3r::intersection_ex(), ClipperLib::jtMiter, ClipperLib::jtSquare, Slic3r::SurfaceCollection::keep_types(), Slic3r::log_memory_info(), Slic3r::Layer::lslices, Slic3r::Layer::m_regions, Slic3r::min_layer_height(), n, Slic3r::offset2(), Slic3r::opening(), Slic3r::polygons_append(), Slic3r::Layer::print_z, Slic3r::PrintRegionConfig, PROFILE_BLOCK, PROFILE_FUNC, Slic3r::range(), Slic3r::LayerRegion::region(), Slic3r::Layer::regions(), scale_, Slic3r::Flow::scaled_spacing(), Slic3r::Flow::scaled_width(), size, Slic3r::LayerRegion::slices, Slic3r::stBottom, Slic3r::stBottomBridge, Slic3r::stInternal, Slic3r::stInternalSolid, Slic3r::stInternalVoid, Slic3r::stTop, Slic3r::SurfaceCollection::surfaces, Slic3r::to_polygons(), Slic3r::union_(), Slic3r::union_ex(), and Slic3r::union_safety_offset_ex().
emptylayer_update_msg()
void Slic3r::PrintObjectBase::emptylayer_update_msg (PrintBase * print, int type, const std::string & message, bool overwrite) protected inherited
firstLayerObjGroups()
const std::vector< groupedVolumeSlices > & Slic3r::PrintObject::firstLayerObjGroups () const inline
{ return firstLayerObjSliceByGroups; }
References firstLayerObjSliceByGroups.
Referenced by copy_layers_from_shared_object().
firstLayerObjGroupsMod()
std::vector< groupedVolumeSlices > & Slic3r::PrintObject::firstLayerObjGroupsMod () inline
{ return firstLayerObjSliceByGroups; }
References firstLayerObjSliceByGroups.
firstLayerObjSlice()
const std::vector< VolumeSlices > & Slic3r::PrintObject::firstLayerObjSlice () const inline
{ return firstLayerObjSliceByVolume; }
References firstLayerObjSliceByVolume.
Referenced by copy_layers_from_shared_object().
firstLayerObjSliceMod()
std::vector< VolumeSlices > & Slic3r::PrintObject::firstLayerObjSliceMod () inline
{ return firstLayerObjSliceByVolume; }
References firstLayerObjSliceByVolume.
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
generate_support_material()
void Slic3r::PrintObject::generate_support_material () private
{
    if (this->set_started(posSupportMaterial)) {
        this->clear_support_layers();
        if ((this->has_support() && m_layers.size() > 1) || (this->has_raft() && ! m_layers.empty())) {
            m_print->set_status(50, L("Generating support"));
            this->_generate_support_material();
            m_print->throw_if_canceled();
        } else if(!m_print->get_no_check_flag()) {
            // BBS: pop a warning if objects have significant amount of overhangs but support material is not enabled
            m_print->set_status(50, L("Checking support necessity"));
            typedef std::chrono::high_resolution_clock clock_;
            typedef std::chrono::duration<double, std::ratio<1> > second_;
            std::chrono::time_point<clock_> t0{ clock_::now() };
            SupportNecessaryType sntype = this->is_support_necessary();
            double duration{ std::chrono::duration_cast<second_>(clock_::now() - t0).count() };
            BOOST_LOG_TRIVIAL(info) << std::fixed << std::setprecision(0) << "is_support_necessary takes " << duration << " secs.";
            if (sntype != NoNeedSupp) {
                std::map<SupportNecessaryType, std::string> reasons = {
                    {SharpTail,L("floating regions")},
                    {Cantilever,L("floating cantilever")},
                    {LargeOverhang,L("large overhangs")} };
                std::string warning_message = format(L("It seems object %s has %s. Please re-orient the object or enable support generation."),
                    this->model_object()->name, reasons[sntype]);
                this->active_step_add_warning(PrintStateBase::WarningLevel::CRITICAL, warning_message, PrintStateBase::SlicingNeedSupportOn);
            }
#if 0
            // Printing without supports. Empty layer means some objects or object parts are levitating,
            // therefore they cannot be printed without supports.
            for (const Layer *layer : m_layers)
                if (layer->empty())
                    throw Slic3r::SlicingError("Levitating objects cannot be printed without supports.");
#endif
        }
        this->set_done(posSupportMaterial);
    }
}
References Slic3r::Cantilever, Slic3r::format(), L, Slic3r::LargeOverhang, Slic3r::NoNeedSupp, Slic3r::posSupportMaterial, and Slic3r::SharpTail.
generate_support_preview()
void Slic3r::PrintObject::generate_support_preview ()
{
    POProfiler profiler;
    boost::posix_time::ptime ts1 = boost::posix_time::microsec_clock::local_time();
    this->slice();
    boost::posix_time::ptime ts2 = boost::posix_time::microsec_clock::local_time();
    profiler.duration1 = (ts2 - ts1).total_milliseconds();
    this->generate_support_material();
Referenced by Slic3r::GUI::GLGizmoFdmSupports::run_thread().
get_certain_layers()
void Slic3r::PrintObject::get_certain_layers (float start, float end, std::vector< LayerPtrs > & out, std::vector< BoundingBox > & boundingbox_objects)
{
    BoundingBox temp;
    LayerPtrs   out_temp;
    for (const auto &layer : layers()) {
        if (layer->print_z < start) continue;
        if (layer->print_z > end + EPSILON) break;
        temp.merge(layer->loverhangs_bbox);
        out_temp.emplace_back(layer);
    }
get_first_layer_bbox()
BoundingBox Slic3r::PrintObject::get_first_layer_bbox (float & area, float & layer_height, std::string & name)
{
    BoundingBox bbox;
    a = 0;
    name = this->model_object()->name;
    if (layer_count() > 0) {
        auto layer = get_layer(0);
        layer_height = layer->height;
        // only work for object with single instance
        auto shift = instances()[0].shift_without_plate_offset();
        for (auto bb : layer->lslices_bboxes)
        {
            bb.translate(shift.x(), shift.y());
            bbox.merge(bb);
        }
        for (auto slice : layer->lslices) {
            a += area(slice);
        }
    }
    if (has_brim())
        bbox = firstLayerObjectBrimBoundingBox;
    return bbox;
}
References Slic3r::area(), firstLayerObjectBrimBoundingBox, get_layer(), has_brim(), instances(), layer_count(), Slic3r::layer_height(), Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::PrintObjectBase::model_object(), Slic3r::ModelObject::name, and slice().
get_first_layer_bellow_printz()
const Layer * Slic3r::PrintObject::get_first_layer_bellow_printz (coordf_t print_z, coordf_t epsilon) const
                                                                          { return const_cast<Layer*>(std::as_const(*this).get_layer_at_printz(print_z, epsilon)); }
const Layer *PrintObject::get_first_layer_bellow_printz(coordf_t print_z, coordf_t epsilon) const
{
    coordf_t limit = print_z + epsilon;
Referenced by Slic3r::get_boundary().
get_id()
size_t Slic3r::PrintObject::get_id () const inline
{ return m_id; }
References m_id.
get_instances_shift_without_plate_offset()
std::vector< Point > Slic3r::PrintObject::get_instances_shift_without_plate_offset ()
{
    std::vector<Point> out;
    out.reserve(m_instances.size());
    for (const auto& instance : m_instances)
        out.push_back(instance.shift_without_plate_offset());
get_layer() [1/2]
Layer * Slic3r::PrintObject::get_layer (int idx) inline
{ return m_layers[idx]; }
References m_layers.
get_layer() [2/2]
const Layer * Slic3r::PrintObject::get_layer (int idx) const inline
{ return m_layers[idx]; }
References m_layers.
Referenced by Slic3r::apply_mm_segmentation(), Slic3r::SeamPlacer::find_seam_string(), Slic3r::FillLightning::Generator::generateInitialInternalOverhangs(), Slic3r::FillLightning::Generator::generateTrees(), and get_first_layer_bbox().
get_layer_at_bottomz() [1/2]
Layer * Slic3r::PrintObject::get_layer_at_bottomz (coordf_t bottom_z, coordf_t epsilon)
get_layer_at_bottomz() [2/2]
const Layer * Slic3r::PrintObject::get_layer_at_bottomz (coordf_t bottom_z, coordf_t epsilon) const
                                         : std::distance(m_layers.begin(), it);
}
// BBS
const Layer* PrintObject::get_layer_at_bottomz(coordf_t bottom_z, coordf_t epsilon) const {
    coordf_t limit_upper = bottom_z + epsilon;
    coordf_t limit_lower = bottom_z - epsilon;
    for (const Layer* layer : m_layers) {
        if (layer->bottom_z() > limit_lower)
            return layer->bottom_z() < limit_upper ? layer : nullptr;
    }
get_layer_at_printz() [1/4]
Layer * Slic3r::PrintObject::get_layer_at_printz (coordf_t print_z)
get_layer_at_printz() [2/4]
const Layer * Slic3r::PrintObject::get_layer_at_printz (coordf_t print_z) const
{
get_layer_at_printz() [3/4]
Layer * Slic3r::PrintObject::get_layer_at_printz (coordf_t print_z, coordf_t epsilon)
get_layer_at_printz() [4/4]
const Layer * Slic3r::PrintObject::get_layer_at_printz (coordf_t print_z, coordf_t epsilon) const
{
    coordf_t limit = print_z - epsilon;
References Slic3r::lower_bound_by_predicate().
get_layer_idx_get_printz()
int Slic3r::PrintObject::get_layer_idx_get_printz (coordf_t print_z, coordf_t epsilon)
                                                                                                           { return layer->print_z < limit; });
    return (it == m_layers.begin()) ? nullptr : *(--it);
}
int PrintObject::get_layer_idx_get_printz(coordf_t print_z, coordf_t epsilon) {
    coordf_t limit = print_z + epsilon;
get_shared_object()
PrintObject * Slic3r::PrintObject::get_shared_object () const inline
{ return m_shared_object; }
References m_shared_object.
Referenced by Slic3r::Print::export_cached_data(), and Slic3r::Print::process().
get_support_layer()
SupportLayer * Slic3r::PrintObject::get_support_layer (int idx) inline
{ return m_support_layers[idx]; }
References m_support_layers.
get_support_layer_at_printz() [1/2]
SupportLayer * Slic3r::PrintObject::get_support_layer_at_printz (coordf_t print_z, coordf_t epsilon)
{
    return const_cast<SupportLayer*>(std::as_const(*this).get_support_layer_at_printz(print_z, epsilon));
}
get_support_layer_at_printz() [2/2]
const SupportLayer * Slic3r::PrintObject::get_support_layer_at_printz (coordf_t print_z, coordf_t epsilon) const
{
    coordf_t limit = print_z - epsilon;
    auto it = Slic3r::lower_bound_by_predicate(m_support_layers.begin(), m_support_layers.end(), [limit](const SupportLayer* layer) { return layer->print_z < limit; });
    return (it == m_support_layers.end() || (*it)->print_z > print_z + epsilon) ? nullptr : *it;
}
References Slic3r::lower_bound_by_predicate().
has_brim()
bool Slic3r::PrintObject::has_brim () const inline
{
        return ((this->config().brim_type != btNoBrim && this->config().brim_width.value > 0.) || this->config().brim_type == btAutoBrim)
            && ! this->has_raft();
    }
References Slic3r::btAutoBrim, Slic3r::btNoBrim, config(), and has_raft().
Referenced by get_first_layer_bbox().
has_raft()
bool Slic3r::PrintObject::has_raft () const inline
{ return m_config.raft_layers > 0; }
References m_config.
Referenced by has_brim(), and has_support_material().
has_support()
bool Slic3r::PrintObject::has_support () const inline
{ return m_config.enable_support || m_config.enforce_support_layers > 0; }
References m_config.
Referenced by has_support_material().
has_support_material()
bool Slic3r::PrintObject::has_support_material () const inline
{ return this->has_support() || this->has_raft(); }
References has_raft(), and has_support().
height()
coord_t Slic3r::PrintObject::height () const inline
{ return m_size.z(); }
References m_size.
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
infill()
void Slic3r::PrintObject::infill () private
{
    // prerequisites
    this->prepare_infill();
    if (this->set_started(posInfill)) {
        m_print->set_status(35, L("Generating infill toolpath"));
        auto [adaptive_fill_octree, support_fill_octree] = this->prepare_adaptive_infill_data();
        auto lightning_generator = this->prepare_lightning_infill_data();
        BOOST_LOG_TRIVIAL(debug) << "Filling layers in parallel - start";
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, m_layers.size()),
            [this, &adaptive_fill_octree = adaptive_fill_octree, &support_fill_octree = support_fill_octree, &lightning_generator](const tbb::blocked_range<size_t>& range) {
                for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx) {
                    m_print->throw_if_canceled();
                    m_layers[layer_idx]->make_fills(adaptive_fill_octree.get(), support_fill_octree.get(), lightning_generator.get());
                }
            }
        );
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Filling layers in parallel - end";
        /*  we could free memory now, but this would make this step not idempotent
        ### $_->fill_surfaces->clear for map @{$_->regions}, @{$object->layers};
        */
        this->set_done(posInfill);
    }
}
References L, Slic3r::posInfill, and Slic3r::range().
insert_support_layer()
SupportLayerPtrs::iterator Slic3r::PrintObject::insert_support_layer (SupportLayerPtrs::iterator pos, size_t id, size_t interface_id, coordf_t height, coordf_t print_z, coordf_t slice_z)
{
    return m_support_layers.insert(pos, new SupportLayer(id, interface_id, this, height, print_z, slice_z));
}
instances() [1/2]
PrintInstances & Slic3r::PrintObject::instances () inline
{ return m_instances; }
References m_instances.
instances() [2/2]
const PrintInstances & Slic3r::PrintObject::instances () const inline
{ return m_instances; }
References m_instances.
Referenced by PrintObject(), Slic3r::TreeSupport::TreeSupport(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), get_first_layer_bbox(), Slic3r::get_print_object_extrusions_extents(), Slic3r::getadhesionCoeff(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), set_instances(), and Slic3r::GCode::sort_print_object_instances().
invalidate_all_steps()
bool Slic3r::PrintObject::invalidate_all_steps () private
{
  // First call the "invalidate" functions, which may cancel background processing.
    bool result = Inherited::invalidate_all_steps() | m_print->invalidate_all_steps();
  // Then reset some of the depending values.
  m_slicing_params.valid = false;
  return result;
}
invalidate_all_steps_without_cancel()
bool Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::invalidate_all_steps_without_cancel () inline protected inherited
        { return m_state.invalidate_all([](){}); }
invalidate_state_by_config_options()
bool Slic3r::PrintObject::invalidate_state_by_config_options (const ConfigOptionResolver & old_config, const ConfigOptionResolver & new_config, const std::vector< t_config_option_key > & opt_keys) private
{
    if (opt_keys.empty())
        return false;
    std::vector<PrintObjectStep> steps;
    bool invalidated = false;
    for (const t_config_option_key &opt_key : opt_keys) {
        if (   opt_key == "brim_width"
            || opt_key == "brim_object_gap"
            || opt_key == "brim_type"
            || opt_key == "brim_ears_max_angle"
            || opt_key == "brim_ears_detection_length"
            // BBS: brim generation depends on printing speed
            || opt_key == "outer_wall_speed"
            || opt_key == "small_perimeter_speed"
            || opt_key == "small_perimeter_threshold"
            || opt_key == "sparse_infill_speed"
            || opt_key == "inner_wall_speed"
            || opt_key == "support_speed"
            || opt_key == "internal_solid_infill_speed"
            || opt_key == "top_surface_speed") {
            // Brim is printed below supports, support invalidates brim and skirt.
            steps.emplace_back(posSupportMaterial);
            if (opt_key == "brim_type") {
                const auto* old_brim_type = old_config.option<ConfigOptionEnum<BrimType>>(opt_key);
                const auto* new_brim_type = new_config.option<ConfigOptionEnum<BrimType>>(opt_key);
                //BBS: When switch to manual brim, the object must have brim, then re-generate perimeter
                //to make the wall order of first layer to be outer-first
                if (old_brim_type->value == btOuterOnly || new_brim_type->value == btOuterOnly)
                    steps.emplace_back(posPerimeters);
            }
        } else if (
               opt_key == "wall_loops"
            || opt_key == "only_one_wall_top"
            || opt_key == "only_one_wall_first_layer"
            || opt_key == "initial_layer_line_width"
            || opt_key == "inner_wall_line_width"
            || opt_key == "infill_wall_overlap"
            || opt_key == "seam_gap"
            || opt_key == "role_based_wipe_speed"
            || opt_key == "wipe_on_loops"
            || opt_key == "wipe_speed") {
            steps.emplace_back(posPerimeters);
        } else if (opt_key == "gap_infill_speed"
            || opt_key == "filter_out_gap_fill" ) {
            // Return true if gap-fill speed has changed from zero value to non-zero or from non-zero value to zero.
            auto is_gap_fill_changed_state_due_to_speed = [&opt_key, &old_config, &new_config]() -> bool {
                if (opt_key == "gap_infill_speed") {
                    const auto *old_gap_fill_speed = old_config.option<ConfigOptionFloat>(opt_key);
                    const auto *new_gap_fill_speed = new_config.option<ConfigOptionFloat>(opt_key);
                    assert(old_gap_fill_speed && new_gap_fill_speed);
                    return (old_gap_fill_speed->value > 0.f && new_gap_fill_speed->value == 0.f) ||
                           (old_gap_fill_speed->value == 0.f && new_gap_fill_speed->value > 0.f);
                }
                return false;
            };
            // Filtering of unprintable regions in multi-material segmentation depends on if gap-fill is enabled or not.
            // So step posSlice is invalidated when gap-fill was enabled/disabled by option "filter_out_gap_fill" or by
            // changing "gap_infill_speed" to force recomputation of the multi-material segmentation.
            if (this->is_mm_painted() && (opt_key == "filter_out_gap_fill" && (opt_key == "gap_infill_speed" && is_gap_fill_changed_state_due_to_speed())))
                steps.emplace_back(posSlice);
            steps.emplace_back(posPerimeters);
        } else if (
               opt_key == "layer_height"
            || opt_key == "raft_layers"
            || opt_key == "raft_contact_distance"
            || opt_key == "slice_closing_radius"
            || opt_key == "slicing_mode"
            || opt_key == "make_overhang_printable"
            || opt_key == "make_overhang_printable_angle"
            || opt_key == "make_overhang_printable_hole_size") {
            steps.emplace_back(posSlice);
    } else if (
               opt_key == "elefant_foot_compensation"
            || opt_key == "support_top_z_distance"
            || opt_key == "support_bottom_z_distance"
            || opt_key == "xy_hole_compensation"
            || opt_key == "xy_contour_compensation"
            //BBS: [Arthur] the following params affect bottomBridge surface type detection
            || opt_key == "support_type"
            || opt_key == "bridge_no_support"
            || opt_key == "max_bridge_length"
            || opt_key == "support_interface_top_layers"
            || opt_key == "support_critical_regions_only"
            ) {
            steps.emplace_back(posSlice);
        } else if (opt_key == "enable_support") {
            steps.emplace_back(posSupportMaterial);
            if (m_config.support_top_z_distance == 0.) {
              // Enabling / disabling supports while soluble support interface is enabled.
              // This changes the bridging logic (bridging enabled without supports, disabled with supports).
              // Reset everything.
              // See GH #1482 for details.
              steps.emplace_back(posSlice);
          }
        } else if (
             opt_key == "support_type"
            || opt_key == "support_angle"
            || opt_key == "support_on_build_plate_only"
            || opt_key == "support_critical_regions_only"
            || opt_key == "support_remove_small_overhang"
            || opt_key == "enforce_support_layers"
            || opt_key == "support_filament"
            || opt_key == "support_line_width"
            || opt_key == "support_interface_top_layers"
            || opt_key == "support_interface_bottom_layers"
            || opt_key == "support_interface_pattern"
            || opt_key == "support_interface_loop_pattern"
            || opt_key == "support_interface_filament"
            || opt_key == "support_interface_spacing"
            || opt_key == "support_bottom_interface_spacing" //BBS
            || opt_key == "support_base_pattern"
            || opt_key == "support_style"
            || opt_key == "support_object_xy_distance"
            || opt_key == "support_base_pattern_spacing"
            || opt_key == "support_expansion"
            //|| opt_key == "independent_support_layer_height" // BBS
            || opt_key == "support_threshold_angle"
            || opt_key == "raft_expansion"
            || opt_key == "raft_first_layer_density"
            || opt_key == "raft_first_layer_expansion"
            || opt_key == "bridge_no_support"
            || opt_key == "max_bridge_length"
            || opt_key == "initial_layer_line_width"
            || opt_key == "tree_support_adaptive_layer_height"
            || opt_key == "tree_support_auto_brim"
            || opt_key == "tree_support_brim_width"
            || opt_key == "tree_support_branch_distance"
            || opt_key == "tree_support_branch_diameter"
            || opt_key == "tree_support_branch_angle"
            || opt_key == "tree_support_wall_count") {
            steps.emplace_back(posSupportMaterial);
        } else if (
               opt_key == "bottom_shell_layers"
            || opt_key == "top_shell_layers") {
            steps.emplace_back(posPrepareInfill);
            const auto *old_shell_layers = old_config.option<ConfigOptionInt>(opt_key);
            const auto *new_shell_layers = new_config.option<ConfigOptionInt>(opt_key);
            assert(old_shell_layers && new_shell_layers);
            bool value_changed = (old_shell_layers->value == 0 && new_shell_layers->value > 0) ||
                                 (old_shell_layers->value > 0 && new_shell_layers->value == 0);
            if (value_changed && this->object_extruders().size() > 1) {
                steps.emplace_back(posSlice);
            }
            else if (m_print->config().spiral_mode && opt_key == "bottom_shell_layers") {
                // Changing the number of bottom layers when a spiral vase is enabled requires re-slicing the object again.
                // Otherwise, holes in the bottom layers could be filled, as is reported in GH #5528.
                steps.emplace_back(posSlice);
            }
        } else if (
               opt_key == "interface_shells"
            || opt_key == "infill_combination"
            || opt_key == "bottom_shell_thickness"
            || opt_key == "top_shell_thickness"
            || opt_key == "minimum_sparse_infill_area"
            || opt_key == "sparse_infill_filament"
            || opt_key == "solid_infill_filament"
            || opt_key == "sparse_infill_line_width"
            || opt_key == "infill_direction"
            || opt_key == "ensure_vertical_shell_thickness"
            || opt_key == "bridge_angle"
            //BBS
            || opt_key == "internal_bridge_support_thickness"
            || opt_key == "bridge_density") {
            steps.emplace_back(posPrepareInfill);
        } else if (
               opt_key == "top_surface_pattern"
            || opt_key == "bottom_surface_pattern"
            || opt_key == "internal_solid_infill_pattern"
            || opt_key == "external_fill_link_max_length"
            || opt_key == "sparse_infill_pattern"
            || opt_key == "infill_anchor"
            || opt_key == "infill_anchor_max"
            || opt_key == "top_surface_line_width"
            || opt_key == "initial_layer_line_width") {
            steps.emplace_back(posInfill);
        } else if (opt_key == "sparse_infill_pattern") {
            steps.emplace_back(posInfill);
            const auto *old_fill_pattern = old_config.option<ConfigOptionEnum<InfillPattern>>(opt_key);
            const auto *new_fill_pattern = new_config.option<ConfigOptionEnum<InfillPattern>>(opt_key);
            assert(old_fill_pattern && new_fill_pattern);
            // We need to recalculate infill surfaces when infill_only_where_needed is enabled, and we are switching from
            // the Lightning infill to another infill or vice versa.
            if (PrintObject::infill_only_where_needed && (new_fill_pattern->value == ipLightning || old_fill_pattern->value == ipLightning))
                steps.emplace_back(posPrepareInfill);
        } else if (opt_key == "sparse_infill_density") {
            // One likely wants to reslice only when switching between zero infill to simulate boolean difference (subtracting volumes),
            // normal infill and 100% (solid) infill.
            const auto *old_density = old_config.option<ConfigOptionPercent>(opt_key);
            const auto *new_density = new_config.option<ConfigOptionPercent>(opt_key);
            assert(old_density && new_density);
            //FIXME Vojtech is not quite sure about the 100% here, maybe it is not needed.
            if (is_approx(old_density->value, 0.) || is_approx(old_density->value, 100.) ||
                is_approx(new_density->value, 0.) || is_approx(new_density->value, 100.))
                steps.emplace_back(posPerimeters);
            steps.emplace_back(posPrepareInfill);
        } else if (opt_key == "internal_solid_infill_line_width") {
            // This value is used for calculating perimeter - infill overlap, thus perimeters need to be recalculated.
            steps.emplace_back(posPerimeters);
            steps.emplace_back(posPrepareInfill);
        } else if (
               opt_key == "outer_wall_line_width"
            || opt_key == "wall_filament"
            || opt_key == "fuzzy_skin"
            || opt_key == "fuzzy_skin_thickness"
            || opt_key == "fuzzy_skin_point_distance"
            || opt_key == "detect_overhang_wall"
            //BBS
            || opt_key == "enable_overhang_speed"
            || opt_key == "detect_thin_wall"
            || opt_key == "precise_outer_wall"
            || opt_key == "overhang_speed_classic") {
            steps.emplace_back(posPerimeters);
            steps.emplace_back(posSupportMaterial);
        } else if (opt_key == "bridge_flow") {
            if (m_config.support_top_z_distance > 0.) {
              // Only invalidate due to bridging if bridging is enabled.
              // If later "support_top_z_distance" is modified, the complete PrintObject is invalidated anyway.
              steps.emplace_back(posPerimeters);
              steps.emplace_back(posInfill);
              steps.emplace_back(posSupportMaterial);
          }
        } else if (
                opt_key == "wall_generator"
            || opt_key == "wall_transition_length"
            || opt_key == "wall_transition_filter_deviation"
            || opt_key == "wall_transition_angle"
            || opt_key == "wall_distribution_count"
            || opt_key == "min_feature_size"
            || opt_key == "min_bead_width") {
            steps.emplace_back(posSlice);
        } else if (
               opt_key == "seam_position"
            || opt_key == "support_speed"
            || opt_key == "support_interface_speed"
            || opt_key == "overhang_1_4_speed"
            || opt_key == "overhang_2_4_speed"
            || opt_key == "overhang_3_4_speed"
            || opt_key == "overhang_4_4_speed"
            || opt_key == "bridge_speed"
            || opt_key == "internal_bridge_speed"
            || opt_key == "outer_wall_speed"
            || opt_key == "small_perimeter_speed"
            || opt_key == "small_perimeter_threshold"
            || opt_key == "sparse_infill_speed"
            || opt_key == "inner_wall_speed"
            || opt_key == "internal_solid_infill_speed"
            || opt_key == "top_surface_speed") {
            invalidated |= m_print->invalidate_step(psGCodeExport);
        } else if (
               opt_key == "flush_into_infill"
            || opt_key == "flush_into_objects"
            || opt_key == "flush_into_support") {
            invalidated |= m_print->invalidate_step(psWipeTower);
            invalidated |= m_print->invalidate_step(psGCodeExport);
        } else {
            // for legacy, if we can't handle this option let's invalidate all steps
            this->invalidate_all_steps();
            invalidated = true;
        }
    }
    sort_remove_duplicates(steps);
    for (PrintObjectStep step : steps)
        invalidated |= this->invalidate_step(step);
    return invalidated;
}
References Slic3r::btOuterOnly, Slic3r::ipLightning, Slic3r::is_approx(), Slic3r::ConfigOptionResolver::option(), Slic3r::posInfill, Slic3r::posPerimeters, Slic3r::posPrepareInfill, Slic3r::posSlice, Slic3r::posSupportMaterial, Slic3r::psGCodeExport, Slic3r::psWipeTower, Slic3r::sort_remove_duplicates(), and Slic3r::ConfigOptionSingle< T >::value.
invalidate_step()
bool Slic3r::PrintObject::invalidate_step (PrintObjectStep step) private
{
  bool invalidated = Inherited::invalidate_step(step);
    // propagate to dependent steps
    if (step == posPerimeters) {
    invalidated |= this->invalidate_steps({ posPrepareInfill, posInfill, posIroning, posSimplifyPath, posSimplifyInfill });
        invalidated |= m_print->invalidate_steps({ psSkirtBrim });
    } else if (step == posPrepareInfill) {
        invalidated |= this->invalidate_steps({ posInfill, posIroning, posSimplifyPath, posSimplifyInfill });
    } else if (step == posInfill) {
        invalidated |= this->invalidate_steps({ posIroning, posSimplifyInfill });
        invalidated |= m_print->invalidate_steps({ psSkirtBrim });
    } else if (step == posSlice) {
    invalidated |= this->invalidate_steps({ posPerimeters, posPrepareInfill, posInfill, posIroning, posSupportMaterial, posSimplifyPath, posSimplifyInfill });
        invalidated |= m_print->invalidate_steps({ psSkirtBrim });
        m_slicing_params.valid = false;
    } else if (step == posSupportMaterial) {
        invalidated |= this->invalidate_steps({ posSimplifySupportPath });
        invalidated |= m_print->invalidate_steps({ psSkirtBrim });
        m_slicing_params.valid = false;
    }
    // Wipe tower depends on the ordering of extruders, which in turn depends on everything.
    // It also decides about what the flush_into_infill / wipe_into_object / flush_into_support features will do,
    // and that too depends on many of the settings.
    invalidated |= m_print->invalidate_step(psWipeTower);
    // Invalidate G-code export in any case.
    invalidated |= m_print->invalidate_step(psGCodeExport);
    return invalidated;
}
References Slic3r::posInfill, Slic3r::posIroning, Slic3r::posPerimeters, Slic3r::posPrepareInfill, Slic3r::posSimplifyInfill, Slic3r::posSimplifyPath, Slic3r::posSimplifySupportPath, Slic3r::posSlice, Slic3r::posSupportMaterial, Slic3r::psGCodeExport, Slic3r::psSkirtBrim, and Slic3r::psWipeTower.
invalidate_steps() [1/2]
bool Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::invalidate_steps (std::initializer_list< PrintObjectStep > il) inline protected inherited
        { return m_state.invalidate_multiple(il.begin(), il.end(), PrintObjectBase::cancel_callback(m_print)); }
invalidate_steps() [2/2]
bool Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::invalidate_steps (StepTypeIterator step_begin, StepTypeIterator step_end) inline protected inherited
        { return m_state.invalidate_multiple(step_begin, step_end, PrintObjectBase::cancel_callback(m_print)); }
ironing()
void Slic3r::PrintObject::ironing () private
{
    if (this->set_started(posIroning)) {
        BOOST_LOG_TRIVIAL(debug) << "Ironing in parallel - start";
        tbb::parallel_for(
            // Ironing starting with layer 0 to support ironing all surfaces.
            tbb::blocked_range<size_t>(0, m_layers.size()),
            [this](const tbb::blocked_range<size_t>& range) {
                for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx) {
                    m_print->throw_if_canceled();
                    m_layers[layer_idx]->make_ironing();
                }
            }
        );
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Ironing in parallel - end";
        this->set_done(posIroning);
    }
}
References Slic3r::posIroning, and Slic3r::range().
is_mm_painted()
bool Slic3r::PrintObject::is_mm_painted () const inline
{ return this->model_object()->is_mm_painted(); }
References Slic3r::ModelObject::is_mm_painted(), and Slic3r::PrintObjectBase::model_object().
Referenced by Slic3r::Print::apply().
is_step_done()
bool Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::is_step_done (PrintObjectStep step) const inline inherited
{ return m_state.is_done(step, PrintObjectBase::state_mutex(m_print)); }
is_step_done_unguarded()
bool Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::is_step_done_unguarded (PrintObjectStep step) const inline protected inherited
{ return m_state.is_done_unguarded(step); }
is_step_started_unguarded()
bool Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::is_step_started_unguarded (PrintObjectStep step) const inline protected inherited
{ return m_state.is_started_unguarded(step); }
is_support_necessary()
SupportNecessaryType Slic3r::PrintObject::is_support_necessary () private
{
    static const double super_overhang_area_threshold = SQ(scale_(5.0));
    const double cantilevel_dist_thresh = scale_(6);
#if 0
    double threshold_rad = (m_config.support_threshold_angle.value < EPSILON ? 30 : m_config.support_threshold_angle.value + 1) * M_PI / 180.;
    int enforce_support_layers = m_config.enforce_support_layers;
    // not fixing in extrusion width % PR b/c never called
    const coordf_t extrusion_width = m_config.line_width.value;
    const coordf_t extrusion_width_scaled = scale_(extrusion_width);
    float max_bridge_length = scale_(m_config.max_bridge_length.value);
    const bool bridge_no_support = max_bridge_length > 0;// config.bridge_no_support.value;
    for (size_t layer_nr = enforce_support_layers + 1; layer_nr < this->layer_count(); layer_nr++) {
        Layer* layer = m_layers[layer_nr];
        Layer* lower_layer = layer->lower_layer;
        coordf_t support_offset_scaled = extrusion_width_scaled * 0.9;
        ExPolygons lower_layer_offseted = offset_ex(lower_layer->lslices, support_offset_scaled, SUPPORT_SURFACES_OFFSET_PARAMETERS);
        // 1. check sharp tail
        for (const LayerRegion* layerm : layer->regions()) {
            for (const ExPolygon& expoly : layerm->raw_slices) {
                // detect sharp tail
                if (intersection_ex({ expoly }, lower_layer_offseted).empty())
                    return SharpTail;
            }
        }
        // 2. check overhang area
        ExPolygons super_overhang_expolys = std::move(diff_ex(layer->lslices, lower_layer_offseted));
        super_overhang_expolys.erase(std::remove_if(
            super_overhang_expolys.begin(),
            super_overhang_expolys.end(),
            [extrusion_width_scaled](ExPolygon& area) {
                return offset_ex(area, -0.1 * extrusion_width_scaled).empty();
            }),
            super_overhang_expolys.end());
        // remove bridge
        if (bridge_no_support)
            remove_bridges_from_contacts(lower_layer, layer, extrusion_width_scaled, &super_overhang_expolys, max_bridge_length);
        Polygons super_overhang_polys = to_polygons(super_overhang_expolys);
        super_overhang_polys.erase(std::remove_if(
            super_overhang_polys.begin(),
            super_overhang_polys.end(),
            [extrusion_width_scaled](Polygon& area) {
                return offset_ex(area, -0.1 * extrusion_width_scaled).empty();
            }),
            super_overhang_polys.end());
        double super_overhang_area = 0.0;
        for (Polygon& poly : super_overhang_polys) {
            bool is_ccw = poly.is_counter_clockwise();
            double area_  = poly.area();
            if (is_ccw) {
                if (area_ > super_overhang_area_threshold)
                    return LargeOverhang;
                super_overhang_area += area_;
            }
            else {
                super_overhang_area -= area_;
            }
        }
        //if (super_overhang_area > super_overhang_area_threshold)
        //    return LargeOverhang;
        // 3. check overhang distance
        const double distance_threshold_scaled = extrusion_width_scaled * 2;
        ExPolygons lower_layer_offseted_2 = offset_ex(lower_layer->lslices, distance_threshold_scaled, SUPPORT_SURFACES_OFFSET_PARAMETERS);
        ExPolygons exceed_overhang = std::move(diff_ex(super_overhang_polys, lower_layer_offseted_2));
        exceed_overhang.erase(std::remove_if(
            exceed_overhang.begin(),
            exceed_overhang.end(),
            [extrusion_width_scaled](ExPolygon& area) {
                // tolerance for 1 extrusion width offset
                return offset_ex(area, -0.5 * extrusion_width_scaled).empty();
            }),
            exceed_overhang.end());
        if (!exceed_overhang.empty())
            return LargeOverhang;
    }
#else
    TreeSupport tree_support(*this, m_slicing_params);
    tree_support.support_type = SupportType::stTreeAuto; // need to set support type to fully utilize the power of feature detection
    tree_support.detect_overhangs(true);
    this->clear_support_layers();
    if (tree_support.has_sharp_tails)
        return SharpTail;
    else if (tree_support.has_cantilever && tree_support.max_cantilever_dist > cantilevel_dist_thresh)
        return Cantilever;
References Slic3r::intersection_ex(), and Slic3r::offset_ex().
layer_count()
size_t Slic3r::PrintObject::layer_count () const inline
{ return m_layers.size(); }
References m_layers.
Referenced by Slic3r::apply_mm_segmentation(), Slic3r::TreeSupport::detect_overhangs(), Slic3r::SeamPlacer::gather_seam_candidates(), get_first_layer_bbox(), Slic3r::Print::process(), and total_layer_count().
layers() [1/2]
LayerPtrs & Slic3r::PrintObject::layers () inline
{ return m_layers; }
References m_layers.
layers() [2/2]
ConstLayerPtrsAdaptor Slic3r::PrintObject::layers () const inline
{ return ConstLayerPtrsAdaptor(&m_layers); }
References m_layers.
Referenced by Slic3r::PrintObjectSupportMaterial::PrintObjectSupportMaterial(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::FillAdaptive::adaptive_fill_line_spacing(), Slic3r::SeamPlacer::calculate_overhangs_and_layer_embedding(), copy_layers_from_shared_object(), Slic3r::SeamPlacer::gather_seam_candidates(), Slic3r::FillLightning::Generator::generateInitialInternalOverhangs(), Slic3r::FillLightning::Generator::generateTrees(), Slic3r::get_print_object_bottom_layer_expolygons(), Slic3r::get_print_object_extrusions_extents(), Slic3r::getadhesionCoeff(), Slic3r::getAllLayersExtrusionPathsFromObject(), Slic3r::getTemperatureFromExtruder(), Slic3r::mmu_segmentation_top_and_bottom_layers(), and Slic3r::multi_material_segmentation_by_painting().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
make_perimeters()
void Slic3r::PrintObject::make_perimeters () private
{
    // prerequisites
    this->slice();
    if (! this->set_started(posPerimeters))
        return;
    m_print->set_status(15, L("Generating walls"));
    BOOST_LOG_TRIVIAL(info) << "Generating walls..." << log_memory_info();
    // Revert the typed slices into untyped slices.
    if (m_typed_slices) {
        for (Layer *layer : m_layers) {
            layer->restore_untyped_slices();
            m_print->throw_if_canceled();
        }
        m_typed_slices = false;
    }
    // compare each layer to the one below, and mark those slices needing
    // one additional inner perimeter, like the top of domed objects-
    // this algorithm makes sure that at least one perimeter is overlapping
    // but we don't generate any extra perimeter if fill density is zero, as they would be floating
    // inside the object - infill_only_where_needed should be the method of choice for printing
    // hollow objects
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        const PrintRegion &region = this->printing_region(region_id);
        //BBS: remove extra_perimeters, always false
        //if (! region.config().extra_perimeters || region.config().wall_loops == 0 || region.config().sparse_infill_density == 0 || this->layer_count() < 2)
            continue;
        BOOST_LOG_TRIVIAL(debug) << "Generating extra perimeters for region " << region_id << " in parallel - start";
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, m_layers.size() - 1),
            [this, &region, region_id](const tbb::blocked_range<size_t>& range) {
                for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx) {
                    m_print->throw_if_canceled();
                    LayerRegion &layerm                     = *m_layers[layer_idx]->get_region(region_id);
                    const LayerRegion &upper_layerm         = *m_layers[layer_idx+1]->get_region(region_id);
                    const Polygons upper_layerm_polygons    = to_polygons(upper_layerm.slices.surfaces);
                    // Filter upper layer polygons in intersection_ppl by their bounding boxes?
                    // my $upper_layerm_poly_bboxes= [ map $_->bounding_box, @{$upper_layerm_polygons} ];
                    const double total_loop_length      = total_length(upper_layerm_polygons);
                    const coord_t perimeter_spacing     = layerm.flow(frPerimeter).scaled_spacing();
                    const Flow ext_perimeter_flow       = layerm.flow(frExternalPerimeter);
                    const coord_t ext_perimeter_width   = ext_perimeter_flow.scaled_width();
                    const coord_t ext_perimeter_spacing = ext_perimeter_flow.scaled_spacing();
                    for (Surface &slice : layerm.slices.surfaces) {
                        for (;;) {
                            // compute the total thickness of perimeters
                            const coord_t perimeters_thickness = ext_perimeter_width/2 + ext_perimeter_spacing/2
                                + (region.config().wall_loops-1 + slice.extra_perimeters) * perimeter_spacing;
                            // define a critical area where we don't want the upper slice to fall into
                            // (it should either lay over our perimeters or outside this area)
                            const coord_t critical_area_depth = coord_t(perimeter_spacing * 1.5);
                            const Polygons critical_area = diff(
                                offset(slice.expolygon, float(- perimeters_thickness)),
                                offset(slice.expolygon, float(- perimeters_thickness - critical_area_depth))
                            );
                            // check whether a portion of the upper slices falls inside the critical area
                            const Polylines intersection = intersection_pl(to_polylines(upper_layerm_polygons), critical_area);
                            // only add an additional loop if at least 30% of the slice loop would benefit from it
                            if (total_length(intersection) <=  total_loop_length*0.3)
                                break;
                            /*
                            if (0) {
                                require "Slic3r/SVG.pm";
                                Slic3r::SVG::output(
                                    "extra.svg",
                                    no_arrows   => 1,
                                    expolygons  => union_ex($critical_area),
                                    polylines   => [ map $_->split_at_first_point, map $_->p, @{$upper_layerm->slices} ],
                                );
                            }
                            */
                            ++ slice.extra_perimeters;
                        }
                        #ifdef DEBUG
                            if (slice.extra_perimeters > 0)
                                printf("  adding %d more perimeter(s) at layer %zu\n", slice.extra_perimeters, layer_idx);
                        #endif
                    }
                }
            });
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Generating extra perimeters for region " << region_id << " in parallel - end";
    }
    BOOST_LOG_TRIVIAL(debug) << "Generating perimeters in parallel - start";
    tbb::parallel_for(
        tbb::blocked_range<size_t>(0, m_layers.size()),
        [this](const tbb::blocked_range<size_t>& range) {
            for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx) {
                m_print->throw_if_canceled();
                m_layers[layer_idx]->make_perimeters();
            }
        }
    );
    m_print->throw_if_canceled();
    BOOST_LOG_TRIVIAL(debug) << "Generating perimeters in parallel - end";
    this->set_done(posPerimeters);
}
References L, Slic3r::log_memory_info(), m_layers, Slic3r::PrintObjectBaseWithState< Print, PrintObjectStep, posCount >::m_print, m_typed_slices, num_printing_regions(), Slic3r::posPerimeters, printing_region(), Slic3r::range(), Slic3r::PrintObjectBaseWithState< Print, PrintObjectStep, posCount >::set_started(), Slic3r::PrintBase::set_status(), slice(), and Slic3r::PrintBase::throw_if_canceled().
model_object() [1/2]
ModelObject * Slic3r::PrintObjectBase::model_object () inline inherited
{ return m_model_object; }
References Slic3r::PrintObjectBase::m_model_object.
model_object() [2/2]
const ModelObject * Slic3r::PrintObjectBase::model_object () const inline inherited
{ return m_model_object; }
References Slic3r::PrintObjectBase::m_model_object.
Referenced by PrintObject(), Slic3r::GUI::GLCanvas3D::_set_warning_notification(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::SeamPlacerImpl::compute_global_occlusion(), Slic3r::Print::export_cached_data(), Slic3r::SeamPlacerImpl::gather_enforcers_blockers(), get_first_layer_bbox(), is_mm_painted(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::multi_material_segmentation_by_painting(), Slic3r::GUI::Plater::priv::on_process_completed(), Slic3r::GUI::Plater::priv::on_slicing_update(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::Print::process(), Slic3r::GUI::Plater::priv::process_validation_warning(), and Slic3r::GUI::NotificationManager::push_validate_error_notification().
num_printing_regions()
size_t Slic3r::PrintObject::num_printing_regions () const throw () inline
{ return m_shared_regions->all_regions.size(); }
References Slic3r::PrintObjectRegions::all_regions, and m_shared_regions.
Referenced by Slic3r::FillAdaptive::adaptive_fill_line_spacing(), make_perimeters(), and Slic3r::mmu_segmentation_top_and_bottom_layers().
object_config_from_model_object()
PrintObjectConfig Slic3r::PrintObject::object_config_from_model_object (const PrintObjectConfig & default_object_config, const ModelObject & object, size_t num_extruders) static private
{
    PrintObjectConfig config = default_object_config;
    {
        DynamicPrintConfig src_normalized(object.config.get());
        src_normalized.normalize_fdm();
        config.apply(src_normalized, true);
    }
    // Clamp invalid extruders to the default extruder (with index 1).
    clamp_exturder_to_default(config.support_filament,           num_extruders);
object_extruders()
std::vector< unsigned int > Slic3r::PrintObject::object_extruders () const
{
    std::vector<unsigned int> extruders;
    extruders.reserve(this->all_regions().size() * 3);
#if 0
    for (const PrintRegion &region : this->all_regions())
        region.collect_object_printing_extruders(*this->print(), extruders);
#else
    const ModelObject* mo = this->model_object();
    for (const ModelVolume* mv : mo->volumes) {
        std::vector<int> volume_extruders = mv->get_extruders();
        for (int extruder : volume_extruders) {
            assert(extruder > 0);
            extruders.push_back(extruder - 1);
        }
    }
#endif
Referenced by Slic3r::PrintObjectSupportMaterial::PrintObjectSupportMaterial(), and Slic3r::get_default_perimeter_spacing().
object_skirt()
const ExtrusionEntityCollection & Slic3r::PrintObject::object_skirt () const inline
{
        return m_skirt;
    }
References m_skirt.
Referenced by Slic3r::GCode::process_layer().
prepare_adaptive_infill_data()
std::pair< FillAdaptive::OctreePtr, FillAdaptive::OctreePtr > Slic3r::PrintObject::prepare_adaptive_infill_data () private
{
    using namespace FillAdaptive;
    auto [adaptive_line_spacing, support_line_spacing] = adaptive_fill_line_spacing(*this);
    if ((adaptive_line_spacing == 0. && support_line_spacing == 0.) || this->layers().empty())
        return std::make_pair(OctreePtr(), OctreePtr());
    indexed_triangle_set mesh = this->model_object()->raw_indexed_triangle_set();
    // Rotate mesh and build octree on it with axis-aligned (standart base) cubes.
    auto to_octree = transform_to_octree().toRotationMatrix();
    its_transform(mesh, to_octree * this->trafo_centered(), true);
    // Triangulate internal bridging surfaces.
    std::vector<std::vector<Vec3d>> overhangs(this->layers().size());
    tbb::parallel_for(
        tbb::blocked_range<int>(0, int(m_layers.size()) - 1),
        [this, &to_octree, &overhangs](const tbb::blocked_range<int> &range) {
            std::vector<Vec3d> &out = overhangs[range.begin()];
            for (int idx_layer = range.begin(); idx_layer < range.end(); ++ idx_layer) {
                m_print->throw_if_canceled();
                const Layer *layer = this->layers()[idx_layer];
                for (const LayerRegion *layerm : layer->regions())
                    for (const Surface &surface : layerm->fill_surfaces.surfaces)
                        if (surface.surface_type == stInternalBridge)
                            append(out, triangulate_expolygon_3d(surface.expolygon, layer->bottom_z()));
            }
            for (Vec3d &p : out)
                p = (to_octree * p).eval();
        });
    // and gather them.
    for (size_t i = 1; i < overhangs.size(); ++ i)
        append(overhangs.front(), std::move(overhangs[i]));
    return std::make_pair(
        adaptive_line_spacing ? build_octree(mesh, overhangs.front(), adaptive_line_spacing, false) : OctreePtr(),
        support_line_spacing  ? build_octree(mesh, overhangs.front(), support_line_spacing, true) : OctreePtr());
}
References Slic3r::empty(), its_transform(), out, Slic3r::range(), size, and Eigen::QuaternionBase< Derived >::toRotationMatrix().
prepare_infill()
void Slic3r::PrintObject::prepare_infill () private
{
    if (! this->set_started(posPrepareInfill))
        return;
    m_print->set_status(25, L("Generating infill regions"));
    if (m_typed_slices) {
        // To improve robustness of detect_surfaces_type() when reslicing (working with typed slices), see GH issue #7442.
        // The preceding step (perimeter generator) only modifies extra_perimeters and the extra perimeters are only used by discover_vertical_shells()
        // with more than a single region. If this step does not use Surface::extra_perimeters or Surface::extra_perimeters is always zero, it is safe
        // to reset to the untyped slices before re-runnning detect_surfaces_type().
        for (Layer* layer : m_layers) {
            layer->restore_untyped_slices_no_extra_perimeters();
            m_print->throw_if_canceled();
        }
    }
    // This will assign a type (top/bottom/internal) to $layerm->slices.
    // Then the classifcation of $layerm->slices is transfered onto
    // the $layerm->fill_surfaces by clipping $layerm->fill_surfaces
    // by the cummulative area of the previous $layerm->fill_surfaces.
    this->detect_surfaces_type();
    m_print->throw_if_canceled();
    // Decide what surfaces are to be filled.
    // Here the stTop / stBottomBridge / stBottom infill is turned to just stInternal if zero top / bottom infill layers are configured.
    // Also tiny stInternal surfaces are turned to stInternalSolid.
    BOOST_LOG_TRIVIAL(info) << "Preparing fill surfaces..." << log_memory_info();
    for (auto *layer : m_layers)
        for (auto *region : layer->m_regions) {
            region->prepare_fill_surfaces();
            m_print->throw_if_canceled();
        }
    // this will detect bridges and reverse bridges
    // and rearrange top/bottom/internal surfaces
    // It produces enlarged overlapping bridging areas.
    //
    // 1) stBottomBridge / stBottom infill is grown by 3mm and clipped by the total infill area. Bridges are detected. The areas may overlap.
    // 2) stTop is grown by 3mm and clipped by the grown bottom areas. The areas may overlap.
    // 3) Clip the internal surfaces by the grown top/bottom surfaces.
    // 4) Merge surfaces with the same style. This will mostly get rid of the overlaps.
    //FIXME This does not likely merge surfaces, which are supported by a material with different colors, but same properties.
    this->process_external_surfaces();
    m_print->throw_if_canceled();
    // Add solid fills to ensure the shell vertical thickness.
    this->discover_vertical_shells();
    m_print->throw_if_canceled();
    // Debugging output.
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        for (const Layer *layer : m_layers) {
            LayerRegion *layerm = layer->m_regions[region_id];
            layerm->export_region_slices_to_svg_debug("6_discover_vertical_shells-final");
            layerm->export_region_fill_surfaces_to_svg_debug("6_discover_vertical_shells-final");
        } // for each layer
    } // for each region
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
    // Detect, which fill surfaces are near external layers.
    // They will be split in internal and internal-solid surfaces.
    // The purpose is to add a configurable number of solid layers to support the TOP surfaces
    // and to add a configurable number of solid layers above the BOTTOM / BOTTOMBRIDGE surfaces
    // to close these surfaces reliably.
    //FIXME Vojtech: Is this a good place to add supporting infills below sloping perimeters?
    this->discover_horizontal_shells();
    m_print->throw_if_canceled();
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        for (const Layer *layer : m_layers) {
            LayerRegion *layerm = layer->m_regions[region_id];
            layerm->export_region_slices_to_svg_debug("7_discover_horizontal_shells-final");
            layerm->export_region_fill_surfaces_to_svg_debug("7_discover_horizontal_shells-final");
        } // for each layer
    } // for each region
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
    // Only active if config->infill_only_where_needed. This step trims the sparse infill,
    // so it acts as an internal support. It maintains all other infill types intact.
    // Here the internal surfaces and perimeters have to be supported by the sparse infill.
    //FIXME The surfaces are supported by a sparse infill, but the sparse infill is only as large as the area to support.
    // Likely the sparse infill will not be anchored correctly, so it will not work as intended.
    // Also one wishes the perimeters to be supported by a full infill.
    this->clip_fill_surfaces();
    m_print->throw_if_canceled();
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        for (const Layer *layer : m_layers) {
            LayerRegion *layerm = layer->m_regions[region_id];
            layerm->export_region_slices_to_svg_debug("8_clip_surfaces-final");
            layerm->export_region_fill_surfaces_to_svg_debug("8_clip_surfaces-final");
        } // for each layer
    } // for each region
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
    // the following step needs to be done before combination because it may need
    // to remove only half of the combined infill
    this->bridge_over_infill();
    m_print->throw_if_canceled();
    // combine fill surfaces to honor the "infill every N layers" option
    this->combine_infill();
    m_print->throw_if_canceled();
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id) {
        for (const Layer *layer : m_layers) {
            LayerRegion *layerm = layer->m_regions[region_id];
            layerm->export_region_slices_to_svg_debug("9_prepare_infill-final");
            layerm->export_region_fill_surfaces_to_svg_debug("9_prepare_infill-final");
        } // for each layer
    } // for each region
    for (const Layer *layer : m_layers) {
        layer->export_region_slices_to_svg_debug("9_prepare_infill-final");
        layer->export_region_fill_surfaces_to_svg_debug("9_prepare_infill-final");
    } // for each layer
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
    this->set_done(posPrepareInfill);
}
References Slic3r::LayerRegion::export_region_fill_surfaces_to_svg_debug(), Slic3r::LayerRegion::export_region_slices_to_svg_debug(), L, Slic3r::log_memory_info(), and Slic3r::posPrepareInfill.
prepare_lightning_infill_data()
FillLightning::GeneratorPtr Slic3r::PrintObject::prepare_lightning_infill_data () private
{
    bool has_lightning_infill = false;
    for (size_t region_id = 0; region_id < this->num_printing_regions(); ++region_id)
        if (const PrintRegionConfig& config = this->printing_region(region_id).config(); config.sparse_infill_density > 0 && config.sparse_infill_pattern == ipLightning) {
            has_lightning_infill = true;
            break;
        }
    return has_lightning_infill ? FillLightning::build_generator(std::as_const(*this), [this]() -> void { this->throw_if_canceled(); }) : FillLightning::GeneratorPtr();
}
References Slic3r::ipLightning, and Slic3r::PrintRegionConfig.
print() [1/2]
Print * Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::print () inline inherited
{ return m_print; }
print() [2/2]
const Print * Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::print () const inline inherited
{ return m_print; }
printing_region()
const PrintRegion & Slic3r::PrintObject::printing_region (size_t idx) const throw () inline
{ return *m_shared_regions->all_regions[idx].get(); }
References Slic3r::PrintObjectRegions::all_regions, and m_shared_regions.
Referenced by Slic3r::FillAdaptive::adaptive_fill_line_spacing(), make_perimeters(), and Slic3r::mmu_segmentation_top_and_bottom_layers().
process_external_surfaces()
void Slic3r::PrintObject::process_external_surfaces () private
{
    BOOST_LOG_TRIVIAL(info) << "Processing external surfaces..." << log_memory_info();
    // Cached surfaces covered by some extrusion, defining regions, over which the from the surfaces one layer higher are allowed to expand.
    std::vector<Polygons> surfaces_covered;
    // Is there any printing region, that has zero infill? If so, then we don't want the expansion to be performed over the complete voids, but only
    // over voids, which are supported by the layer below.
    bool          has_voids = false;
  for (size_t region_id = 0; region_id < this->num_printing_regions(); ++ region_id)
    if (this->printing_region(region_id).config().sparse_infill_density == 0) {
      has_voids = true;
      break;
    }
  if (has_voids && m_layers.size() > 1) {
      // All but stInternal fill surfaces will get expanded and possibly trimmed.
      std::vector<unsigned char> layer_expansions_and_voids(m_layers.size(), false);
      for (size_t layer_idx = 0; layer_idx < m_layers.size(); ++ layer_idx) {
        const Layer *layer = m_layers[layer_idx];
        bool expansions = false;
        bool voids      = false;
        for (const LayerRegion *layerm : layer->regions()) {
          for (const Surface &surface : layerm->fill_surfaces.surfaces) {
            if (surface.surface_type == stInternal)
              voids = true;
            else
              expansions = true;
            if (voids && expansions) {
              layer_expansions_and_voids[layer_idx] = true;
              goto end;
            }
          }
        }
    end:;
    }
      BOOST_LOG_TRIVIAL(debug) << "Collecting surfaces covered with extrusions in parallel - start";
      surfaces_covered.resize(m_layers.size() - 1, Polygons());
      auto unsupported_width = - float(scale_(0.3 * EXTERNAL_INFILL_MARGIN));
      tbb::parallel_for(
          tbb::blocked_range<size_t>(0, m_layers.size() - 1),
          [this, &surfaces_covered, &layer_expansions_and_voids, unsupported_width](const tbb::blocked_range<size_t>& range) {
              for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx)
                if (layer_expansions_and_voids[layer_idx + 1]) {
                    m_print->throw_if_canceled();
                    Polygons voids;
                    for (const LayerRegion *layerm : m_layers[layer_idx]->regions()) {
                      if (layerm->region().config().sparse_infill_density.value == 0.)
                        for (const Surface &surface : layerm->fill_surfaces.surfaces)
                          // Shrink the holes, let the layer above expand slightly inside the unsupported areas.
                          polygons_append(voids, offset(surface.expolygon, unsupported_width));
                    }
                    surfaces_covered[layer_idx] = diff(m_layers[layer_idx]->lslices, voids);
                }
          }
      );
      m_print->throw_if_canceled();
      BOOST_LOG_TRIVIAL(debug) << "Collecting surfaces covered with extrusions in parallel - end";
  }
  for (size_t region_id = 0; region_id < this->num_printing_regions(); ++region_id) {
        BOOST_LOG_TRIVIAL(debug) << "Processing external surfaces for region " << region_id << " in parallel - start";
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, m_layers.size()),
            [this, &surfaces_covered, region_id](const tbb::blocked_range<size_t>& range) {
                for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx) {
                    m_print->throw_if_canceled();
                    // BOOST_LOG_TRIVIAL(trace) << "Processing external surface, layer" << m_layers[layer_idx]->print_z;
                    m_layers[layer_idx]->get_region(int(region_id))->process_external_surfaces(
                      (layer_idx == 0) ? nullptr : m_layers[layer_idx - 1],
                      (layer_idx == 0 || surfaces_covered.empty() || surfaces_covered[layer_idx - 1].empty()) ? nullptr : &surfaces_covered[layer_idx - 1]);
                }
            }
        );
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Processing external surfaces for region " << region_id << " in parallel - end";
    }
}
References end, EXTERNAL_INFILL_MARGIN, Slic3r::log_memory_info(), Slic3r::range(), Slic3r::Layer::regions(), scale_, and Slic3r::stInternal.
project_and_append_custom_facets()
void Slic3r::PrintObject::project_and_append_custom_facets (bool seam, EnforcerBlockerType type, std::vector< Polygons > & expolys) const
{
    for (const ModelVolume* mv : this->model_object()->volumes)
        if (mv->is_model_part()) {
            const indexed_triangle_set custom_facets = seam
                    ? mv->seam_facets.get_facets_strict(*mv, type)
                    : mv->supported_facets.get_facets_strict(*mv, type);
            if (! custom_facets.indices.empty()) {
                if (seam)
                    project_triangles_to_slabs(this->layers(), custom_facets,
                        (this->trafo_centered() * mv->get_matrix()).cast<float>(),
                        seam, out);
                else {
                    std::vector<Polygons> projected;
                    // Support blockers or enforcers. Project downward facing painted areas upwards to their respective slicing plane.
                    slice_mesh_slabs(custom_facets, zs_from_layers(this->layers()), this->trafo_centered() * mv->get_matrix(), nullptr, &projected, [](){});
                    // Merge these projections with the output, layer by layer.
                    assert(! projected.empty());
                    assert(out.empty() || out.size() == projected.size());
                    if (out.empty())
                        out = std::move(projected);
                    else
                        for (size_t i = 0; i < out.size(); ++ i)
                            append(out[i], std::move(projected[i]));
                }
remove_bridges_from_contacts()
template<typename PolysType > template void Slic3r::PrintObject::remove_bridges_from_contacts< Polygons > (const Layer * lower_layer, const Layer * current_layer, float extrusion_width, PolysType * overhang_regions, float max_bridge_length = scale_(10), bool break_bridge = false) static
{
    // Extrusion width accounts for the roundings of the extrudates.
    // It is the maximum widh of the extrudate.
    float fw = extrusion_width;
    Lines overhang_perimeters = to_lines(*overhang_regions);
    auto layer_regions = current_layer->regions();
    Polygons lower_layer_polygons = to_polygons(lower_layer->lslices);
    const PrintObjectConfig& object_config = current_layer->object()->config();
    Polygons all_bridges;
    for (LayerRegion* layerm : layer_regions)
    {
        Polygons bridges;
        // Surface supporting this layer, expanded by 0.5 * nozzle_diameter, as we consider this kind of overhang to be sufficiently supported.
        Polygons lower_grown_slices = offset(lower_layer_polygons,
            //FIXME to mimic the decision in the perimeter generator, we should use half the external perimeter width.
            0.5f * fw, SUPPORT_SURFACES_OFFSET_PARAMETERS);
        Polylines overhang_perimeters = diff_pl(layerm->perimeters.as_polylines(), lower_grown_slices);
        // only consider straight overhangs
            // only consider overhangs having endpoints inside layer's slices
            // convert bridging polylines into polygons by inflating them with their thickness
            // since we're dealing with bridges, we can't assume width is larger than spacing,
            // so we take the largest value and also apply safety offset to be ensure no gaps
            // are left in between
        Flow bridge_flow = layerm->bridging_flow(frPerimeter, object_config.thick_bridges);
        float w = float(std::max(bridge_flow.scaled_width(), bridge_flow.scaled_spacing()));
        for (Polyline& polyline : overhang_perimeters)
            if (polyline.is_straight()) {
                // This is a bridge
                polyline.extend_start(fw);
                polyline.extend_end(fw);
                // Is the straight perimeter segment supported at both sides?
                Point pts[2] = { polyline.first_point(), polyline.last_point() };
                bool  supported[2] = { false, false };
                for (size_t i = 0; i < lower_layer->lslices.size() && !(supported[0] && supported[1]); ++i)
                    for (int j = 0; j < 2; ++j)
                        if (!supported[j] && lower_layer->lslices_bboxes[i].contains(pts[j]) && lower_layer->lslices[i].contains(pts[j]))
                            supported[j] = true;
                if (supported[0] && supported[1]) {
                    Polylines lines;
                    if (polyline.length() > max_bridge_length + 10) {
                        if (break_bridge) {
                            // equally divide the polyline
                            float len = polyline.length() / ceil(polyline.length() / max_bridge_length);
                            lines = polyline.equally_spaced_lines(len);
                            for (auto& line : lines) {
                                if (line.is_valid())
                                    line.clip_start(fw);
                                if (line.is_valid())
                                    line.clip_end(fw);
                            }
                        }
                    }
                    else
                        lines.push_back(polyline);
                    // Offset a polyline into a thick line.
                    polygons_append(bridges, offset(lines, 0.5f * w + 10.f));
                }
            }
        bridges = union_(bridges);
        // remove the entire bridges and only support the unsupported edges
        //FIXME the brided regions are already collected as layerm->bridged. Use it?
        for (const Surface& surface : layerm->fill_surfaces.surfaces)
            if (surface.surface_type == stBottomBridge && surface.bridge_angle != -1) {
                auto bbox      = get_extents(surface.expolygon);
                auto bbox_size = bbox.size();
                if (bbox_size[0] < max_bridge_length && bbox_size[1] < max_bridge_length)
                    polygons_append(bridges, surface.expolygon);
                else {
                    if (break_bridge) {
                        Polygons holes;
                        coord_t  x0 = bbox.min.x();
                        coord_t  x1 = bbox.max.x();
                        coord_t  y0 = bbox.min.y();
                        coord_t  y1 = bbox.max.y();
                        const int grid_lw = int(w/2); // grid line width
                        Vec2f bridge_direction{ cos(surface.bridge_angle),sin(surface.bridge_angle) };
                        if (fabs(bridge_direction(0)) > fabs(bridge_direction(1)))
                        {   // cut bridge along x-axis if bridge direction is aligned to x-axis more than to y-axis
                            // Note: surface.bridge_angle may be pi, so we can't compare it to 0 & pi/2.
                            int step = bbox_size(0) / ceil(bbox_size(0) / max_bridge_length);
                            for (int x = x0 + step; x < x1; x += step) {
                                Polygon poly;
                                poly.points = {Point(x - grid_lw, y0), Point(x + grid_lw, y0), Point(x + grid_lw, y1), Point(x - grid_lw, y1)};
                                holes.emplace_back(poly);
                            }
                        } else {
                            int step = bbox_size(1) / ceil(bbox_size(1) / max_bridge_length);
                            for (int y = y0 + step; y < y1; y += step) {
                                Polygon poly;
                                poly.points = {Point(x0, y - grid_lw), Point(x0, y + grid_lw), Point(x1, y + grid_lw), Point(x1, y - grid_lw)};
                                holes.emplace_back(poly);
                            }
                        }
                        auto expoly = diff_ex(surface.expolygon, holes);
                        polygons_append(bridges, expoly);
                    }
                }
            }
        //FIXME add the gap filled areas. Extrude the gaps with a bridge flow?
        // Remove the unsupported ends of the bridges from the bridged areas.
        //FIXME add supports at regular intervals to support long bridges!
        bridges = diff(bridges,
            // Offset unsupported edges into polygons.
            offset(layerm->unsupported_bridge_edges, scale_(SUPPORT_MATERIAL_MARGIN), SUPPORT_SURFACES_OFFSET_PARAMETERS));
        append(all_bridges, bridges);
    }
    if (typeid(overhang_regions) == typeid(ExPolygons*)) {
        *(ExPolygons*)overhang_regions = diff_ex(*overhang_regions, all_bridges, ApplySafetyOffset::Yes);
    }
    else if (typeid(overhang_regions) == typeid(Polygons*)) {
References Slic3r::append(), Slic3r::Flow::bridging_flow(), ceil(), config(), cos(), Slic3r::diff(), Slic3r::diff_ex(), Slic3r::diff_pl(), Slic3r::frPerimeter, Slic3r::get_extents(), int, Slic3r::Layer::lslices, Slic3r::Layer::lslices_bboxes, Slic3r::Layer::object(), Slic3r::MultiPoint::points, Slic3r::polygons_append(), Slic3r::PrintObjectConfig, Slic3r::Layer::regions(), scale_, Slic3r::Flow::scaled_spacing(), Slic3r::Flow::scaled_width(), sin(), Slic3r::stBottomBridge, SUPPORT_MATERIAL_MARGIN, SUPPORT_SURFACES_OFFSET_PARAMETERS, Slic3r::to_lines(), Slic3r::to_polygons(), and Slic3r::union_().
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_done()
PrintStateBase::TimeStamp Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::set_done (PrintObjectStep step) inline protected inherited
{
    std::pair<PrintStateBase::TimeStamp, bool> status = m_state.set_done(step, PrintObjectBase::state_mutex(m_print), [this](){ this->throw_if_canceled(); });
        if (status.second)
            this->status_update_warnings(m_print, static_cast<int>(step), PrintStateBase::WarningLevel::NON_CRITICAL, std::string());
        return status.first;
  }
set_id()
void Slic3r::PrintObject::set_id (size_t id) inline
{ m_id = id; }
References Slic3r::ObjectBase::id(), and m_id.
set_instances()
PrintBase::ApplyStatus Slic3r::PrintObject::set_instances (PrintInstances && instances) private
{
    for (PrintInstance &i : instances)
      // Add the center offset, which will be subtracted from the mesh when slicing.
      i.shift += m_center_offset;
    // Invalidate and set copies.
    PrintBase::ApplyStatus status = PrintBase::APPLY_STATUS_UNCHANGED;
    bool equal_length = instances.size() == m_instances.size();
    bool equal = equal_length && std::equal(instances.begin(), instances.end(), m_instances.begin(),
      [](const PrintInstance& lhs, const PrintInstance& rhs) { return lhs.model_instance == rhs.model_instance && lhs.shift == rhs.shift; });
    if (! equal) {
        status = PrintBase::APPLY_STATUS_CHANGED;
        if (m_print->invalidate_steps({ psSkirtBrim, psGCodeExport }) ||
            (! equal_length && m_print->invalidate_step(psWipeTower)))
            status = PrintBase::APPLY_STATUS_INVALIDATED;
        m_instances = std::move(instances);
      for (PrintInstance &i : m_instances)
        i.print_object = this;
    }
    return status;
}
References Slic3r::PrintBase::APPLY_STATUS_CHANGED, Slic3r::PrintBase::APPLY_STATUS_INVALIDATED, Slic3r::PrintBase::APPLY_STATUS_UNCHANGED, instances(), Slic3r::Print::invalidate_step(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::invalidate_steps(), m_center_offset, m_instances, Slic3r::PrintObjectBaseWithState< Print, PrintObjectStep, posCount >::m_print, and Slic3r::psWipeTower.
Referenced by PrintObject().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), Slic3r::Model::assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_shared_object()
void Slic3r::PrintObject::set_shared_object (PrintObject * object)
{
    m_shared_object = object;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": this=%1%, found shared object from %2%")%this%m_shared_object;
}
References m_shared_object.
Referenced by Slic3r::Print::process().
set_started()
bool Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::set_started (PrintObjectStep step) inline protected inherited
        { return m_state.set_started(step, PrintObjectBase::state_mutex(m_print), [this](){ this->throw_if_canceled(); }); }
shared_regions()
const PrintObjectRegions * Slic3r::PrintObject::shared_regions () const throw () inline
{ return m_shared_regions; }
References m_shared_regions.
Referenced by Slic3r::FillLightning::Generator::Generator(), and Slic3r::FillLightning::Generator::Generator().
simplify_extrusion_path()
void Slic3r::PrintObject::simplify_extrusion_path () private
{
    if (this->set_started(posSimplifyPath)) {
        m_print->set_status(75, L("Optimizing toolpath"));
        BOOST_LOG_TRIVIAL(debug) << "Simplify extrusion path of object in parallel - start";
        //BBS: infill and walls
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, m_layers.size()),
            [this](const tbb::blocked_range<size_t>& range) {
                for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx) {
                    m_print->throw_if_canceled();
                    m_layers[layer_idx]->simplify_wall_extrusion_path();
                }
            }
        );
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Simplify wall extrusion path of object in parallel - end";
        this->set_done(posSimplifyPath);
    }
    if (this->set_started(posSimplifyInfill)) {
        m_print->set_status(75, L("Optimizing toolpath"));
        BOOST_LOG_TRIVIAL(debug) << "Simplify infill extrusion path of object in parallel - start";
        //BBS: infills
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, m_layers.size()),
            [this](const tbb::blocked_range<size_t>& range) {
                for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++layer_idx) {
                    m_print->throw_if_canceled();
                    m_layers[layer_idx]->simplify_infill_extrusion_path();
                }
            }
        );
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Simplify infill extrusion path of object in parallel - end";
        this->set_done(posSimplifyInfill);
    }
    if (this->set_started(posSimplifySupportPath)) {
        //BBS: share same progress
        m_print->set_status(75, L("Optimizing toolpath"));
        BOOST_LOG_TRIVIAL(debug) << "Simplify extrusion path of support in parallel - start";
        tbb::parallel_for(
            tbb::blocked_range<size_t>(0, m_support_layers.size()),
            [this](const tbb::blocked_range<size_t>& range) {
                for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx) {
                    m_print->throw_if_canceled();
                    m_support_layers[layer_idx]->simplify_support_extrusion_path();
                }
            }
        );
        m_print->throw_if_canceled();
        BOOST_LOG_TRIVIAL(debug) << "Simplify extrusion path of support in parallel - end";
        this->set_done(posSimplifySupportPath);
    }
}
References L, Slic3r::posSimplifyPath, and Slic3r::range().
size()
const Vec3crd & Slic3r::PrintObject::size () const inline
{ return m_size; }
References m_size.
Referenced by Slic3r::TreeSupport::detect_overhangs().
slice()
void Slic3r::PrintObject::slice ()
{
    if (! this->set_started(posSlice))
        return;
    //BBS: add flag to reload scene for shell rendering
    m_print->set_status(5, L("Slicing mesh"), PrintBase::SlicingStatus::RELOAD_SCENE);
    std::vector<coordf_t> layer_height_profile;
    this->update_layer_height_profile(*this->model_object(), m_slicing_params, layer_height_profile);
    m_print->throw_if_canceled();
    m_typed_slices = false;
    this->clear_layers();
    m_layers = new_layers(this, generate_object_layers(m_slicing_params, layer_height_profile));
    this->slice_volumes();
    m_print->throw_if_canceled();
    int firstLayerReplacedBy = 0;
#if 1
    // Fix the model.
    //FIXME is this the right place to do? It is done repeateadly at the UI and now here at the backend.
    std::string warning = fix_slicing_errors(this, m_layers, [this](){ m_print->throw_if_canceled(); }, firstLayerReplacedBy);
    m_print->throw_if_canceled();
    //BBS: send warning message to slicing callback
    if (!warning.empty()) {
        BOOST_LOG_TRIVIAL(info) << warning;
        this->active_step_add_warning(PrintStateBase::WarningLevel::CRITICAL, warning, PrintStateBase::SlicingReplaceInitEmptyLayers);
    }
#endif
    // BBS: the actual first layer slices stored in layers are re-sorted by volume group and will be used to generate brim
    groupingVolumesForBrim(this, m_layers, firstLayerReplacedBy);
    // Update bounding boxes, back up raw slices of complex models.
    tbb::parallel_for(
        tbb::blocked_range<size_t>(0, m_layers.size()),
        [this](const tbb::blocked_range<size_t>& range) {
            for (size_t layer_idx = range.begin(); layer_idx < range.end(); ++ layer_idx) {
                m_print->throw_if_canceled();
                Layer &layer = *m_layers[layer_idx];
                layer.lslices_bboxes.clear();
                layer.lslices_bboxes.reserve(layer.lslices.size());
                for (const ExPolygon &expoly : layer.lslices)
                  layer.lslices_bboxes.emplace_back(get_extents(expoly));
                layer.backup_untyped_slices();
            }
        });
    if (m_layers.empty())
        throw Slic3r::SlicingError(L("No layers were detected. You might want to repair your STL file(s) or check their size or thickness and retry.\n"));
    // BBS
    this->set_done(posSlice);
}
References Slic3r::fix_slicing_errors(), Slic3r::generate_object_layers(), Slic3r::groupingVolumesForBrim(), L, Slic3r::new_layers(), Slic3r::posSlice, and Slic3r::range().
Referenced by get_first_layer_bbox(), and make_perimeters().
slice_support_blockers()
std::vector< Polygons > Slic3r::PrintObject::slice_support_blockers () const inline
{ return this->slice_support_volumes(ModelVolumeType::SUPPORT_BLOCKER); }
References slice_support_volumes(), and Slic3r::SUPPORT_BLOCKER.
slice_support_enforcers()
std::vector< Polygons > Slic3r::PrintObject::slice_support_enforcers () const inline
{ return this->slice_support_volumes(ModelVolumeType::SUPPORT_ENFORCER); }
References slice_support_volumes(), and Slic3r::SUPPORT_ENFORCER.
slice_support_volumes()
std::vector< Polygons > Slic3r::PrintObject::slice_support_volumes (const ModelVolumeType model_volume_type) const
{
    auto it_volume     = this->model_object()->volumes.begin();
    auto it_volume_end = this->model_object()->volumes.end();
    for (; it_volume != it_volume_end && (*it_volume)->type() != model_volume_type; ++ it_volume) ;
    std::vector<Polygons> slices;
    if (it_volume != it_volume_end) {
        // Found at least a single support volume of model_volume_type.
        std::vector<float> zs = zs_from_layers(this->layers());
        std::vector<char>  merge_layers;
        bool               merge = false;
        const Print       *print = this->print();
        auto               throw_on_cancel_callback = std::function<void()>([print](){ print->throw_if_canceled(); });
        MeshSlicingParamsEx params;
        params.trafo = this->trafo_centered();
        for (; it_volume != it_volume_end; ++ it_volume)
            if ((*it_volume)->type() == model_volume_type) {
                std::vector<ExPolygons> slices2 = slice_volume(*(*it_volume), zs, params, throw_on_cancel_callback);
                if (slices.empty()) {
                    slices.reserve(slices2.size());
                    for (ExPolygons &src : slices2)
                        slices.emplace_back(to_polygons(std::move(src)));
                } else if (!slices2.empty()) {
                    if (merge_layers.empty())
                        merge_layers.assign(zs.size(), false);
                    for (size_t i = 0; i < zs.size(); ++ i) {
                        if (slices[i].empty())
                            slices[i] = to_polygons(std::move(slices2[i]));
                        else if (! slices2[i].empty()) {
                            append(slices[i], to_polygons(std::move(slices2[i])));
                            merge_layers[i] = true;
                            merge = true;
                        }
                    }
                }
            }
        if (merge) {
            std::vector<Polygons*> to_merge;
            to_merge.reserve(zs.size());
            for (size_t i = 0; i < zs.size(); ++ i)
                if (merge_layers[i])
                    to_merge.emplace_back(&slices[i]);
            tbb::parallel_for(
                tbb::blocked_range<size_t>(0, to_merge.size()),
                [&to_merge](const tbb::blocked_range<size_t> &range) {
                    for (size_t i = range.begin(); i < range.end(); ++ i)
                        *to_merge[i] = union_(*to_merge[i]);
            });
        }
    }
    return slices;
}
References Slic3r::append(), Slic3r::empty(), Slic3r::range(), Slic3r::slice_volume(), Slic3r::PrintBase::throw_if_canceled(), Slic3r::to_polygons(), Slic3r::MeshSlicingParams::trafo, and Slic3r::zs_from_layers().
Referenced by slice_support_blockers(), and slice_support_enforcers().
slice_volumes()
void Slic3r::PrintObject::slice_volumes () private
{
    BOOST_LOG_TRIVIAL(info) << "Slicing volumes..." << log_memory_info();
    const Print *print                      = this->print();
    const auto   throw_on_cancel_callback   = std::function<void()>([print](){ print->throw_if_canceled(); });
    // Clear old LayerRegions, allocate for new PrintRegions.
    for (Layer* layer : m_layers) {
        //BBS: should delete all LayerRegionPtr to avoid memory leak
        while (!layer->m_regions.empty()) {
            if (layer->m_regions.back())
                delete layer->m_regions.back();
            layer->m_regions.pop_back();
        }
        layer->m_regions.reserve(m_shared_regions->all_regions.size());
        for (const std::unique_ptr<PrintRegion> &pr : m_shared_regions->all_regions)
            layer->m_regions.emplace_back(new LayerRegion(layer, pr.get()));
    }
    std::vector<float>                   slice_zs      = zs_from_layers(m_layers);
    std::vector<VolumeSlices> objSliceByVolume;
    if (!slice_zs.empty()) {
        objSliceByVolume = slice_volumes_inner(
            print->config(), this->config(), this->trafo_centered(),
            this->model_object()->volumes, m_shared_regions->layer_ranges, slice_zs, throw_on_cancel_callback);
    }
    //BBS: "model_part" volumes are grouded according to their connections
    //const auto           scaled_resolution = scaled<double>(print->config().resolution.value);
    //firstLayerObjSliceByVolume = findPartVolumes(objSliceByVolume, this->model_object()->volumes);
    //groupingVolumes(objSliceByVolumeParts, firstLayerObjSliceByGroups, scaled_resolution);
    //applyNegtiveVolumes(this->model_object()->volumes, objSliceByVolume, firstLayerObjSliceByGroups, scaled_resolution);
    firstLayerObjSliceByVolume = objSliceByVolume;
    std::vector<std::vector<ExPolygons>> region_slices =
        slices_to_regions(print->config(), *this, this->model_object()->volumes, *m_shared_regions, slice_zs,
                          std::move(objSliceByVolume), PrintObject::clip_multipart_objects, throw_on_cancel_callback);
    for (size_t region_id = 0; region_id < region_slices.size(); ++ region_id) {
        std::vector<ExPolygons> &by_layer = region_slices[region_id];
        for (size_t layer_id = 0; layer_id < by_layer.size(); ++ layer_id)
            m_layers[layer_id]->regions()[region_id]->slices.append(std::move(by_layer[layer_id]), stInternal);
    }
    region_slices.clear();
    BOOST_LOG_TRIVIAL(debug) << "Slicing volumes - removing top empty layers";
    while (! m_layers.empty()) {
        const Layer *layer = m_layers.back();
        if (! layer->empty())
            break;
        delete layer;
        m_layers.pop_back();
    }
    if (! m_layers.empty())
        m_layers.back()->upper_layer = nullptr;
    m_print->throw_if_canceled();
    // Is any ModelVolume MMU painted?
    if (const auto& volumes = this->model_object()->volumes;
        m_print->config().filament_diameter.size() > 1 && // BBS
        std::find_if(volumes.begin(), volumes.end(), [](const ModelVolume* v) { return !v->mmu_segmentation_facets.empty(); }) != volumes.end()) {
        // If XY Size compensation is also enabled, notify the user that XY Size compensation
        // would not be used because the object is multi-material painted.
        if (m_config.xy_hole_compensation.value != 0.f || m_config.xy_contour_compensation.value != 0.f) {
            this->active_step_add_warning(
                PrintStateBase::WarningLevel::CRITICAL,
                L("An object's XY size compensation will not be used because it is also color-painted.\nXY Size "
                  "compensation can not be combined with color-painting."));
            BOOST_LOG_TRIVIAL(info) << "xy compensation will not work for object " << this->model_object()->name << " for multi filament.";
        }
        BOOST_LOG_TRIVIAL(debug) << "Slicing volumes - MMU segmentation";
        apply_mm_segmentation(*this, [print]() { print->throw_if_canceled(); });
    }
    this->apply_conical_overhang();
    m_print->throw_if_canceled();
    BOOST_LOG_TRIVIAL(debug) << "Slicing volumes - make_slices in parallel - begin";
    {
        // Compensation value, scaled. Only applying the negative scaling here, as the positive scaling has already been applied during slicing.
        const size_t num_extruders = print->config().filament_diameter.size();
        const auto   xy_hole_scaled = (num_extruders > 1 && this->is_mm_painted()) ? scaled<float>(0.f) : scaled<float>(m_config.xy_hole_compensation.value);
        const auto   xy_contour_scaled            = (num_extruders > 1 && this->is_mm_painted()) ? scaled<float>(0.f) : scaled<float>(m_config.xy_contour_compensation.value);
        const float  elephant_foot_compensation_scaled = (m_config.raft_layers == 0) ?
          // Only enable Elephant foot compensation if printing directly on the print bed.
            float(scale_(m_config.elefant_foot_compensation.value)) :
          0.f;
        // Uncompensated slices for the first layer in case the Elephant foot compensation is applied.
      ExPolygons  lslices_1st_layer;
        //BBS: this part has been changed a lot to support seperated contour and hole size compensation
      tbb::parallel_for(
          tbb::blocked_range<size_t>(0, m_layers.size()),
      [this, xy_hole_scaled, xy_contour_scaled, elephant_foot_compensation_scaled, &lslices_1st_layer](const tbb::blocked_range<size_t>& range) {
              for (size_t layer_id = range.begin(); layer_id < range.end(); ++ layer_id) {
                  m_print->throw_if_canceled();
                  Layer *layer = m_layers[layer_id];
                  // Apply size compensation and perform clipping of multi-part objects.
                  float elfoot = (layer_id == 0) ? elephant_foot_compensation_scaled : 0.f;
                  if (layer->m_regions.size() == 1) {
                      // Optimized version for a single region layer.
                      // Single region, growing or shrinking.
                      LayerRegion *layerm = layer->m_regions.front();
                        if (elfoot > 0) {
                        // Apply the elephant foot compensation and store the 1st layer slices without the Elephant foot compensation applied.
                        lslices_1st_layer = to_expolygons(std::move(layerm->slices.surfaces));
                            if (xy_contour_scaled > 0 || xy_hole_scaled > 0) {
                                lslices_1st_layer = _shrink_contour_holes(std::max(0.f, xy_contour_scaled),
                                                                   std::max(0.f, xy_hole_scaled),
                                                                   lslices_1st_layer);
                            }
                            if (xy_contour_scaled < 0 || xy_hole_scaled < 0) {
                                lslices_1st_layer = _shrink_contour_holes(std::min(0.f, xy_contour_scaled),
                                                                   std::min(0.f, xy_hole_scaled),
                                                                   lslices_1st_layer);
                            }
              layerm->slices.set(
                union_ex(
                  Slic3r::elephant_foot_compensation(lslices_1st_layer,
                                  layerm->flow(frExternalPerimeter), unscale<double>(elfoot))),
                stInternal);
                      } else {
                          // Apply the XY contour and hole size compensation.
                            if (xy_contour_scaled != 0.0f || xy_hole_scaled != 0.0f) {
                                ExPolygons expolygons = to_expolygons(std::move(layerm->slices.surfaces));
                                if (xy_contour_scaled > 0 || xy_hole_scaled > 0) {
                                    expolygons = _shrink_contour_holes(std::max(0.f, xy_contour_scaled),
                                                                       std::max(0.f, xy_hole_scaled),
                                                                       expolygons);
                                }
                                if (xy_contour_scaled < 0 || xy_hole_scaled < 0) {
                                    expolygons = _shrink_contour_holes(std::min(0.f, xy_contour_scaled),
                                                                       std::min(0.f, xy_hole_scaled),
                                                                       expolygons);
                                }
                                layerm->slices.set(std::move(expolygons), stInternal);
                            }
                      }
                  } else {
                        float max_growth = std::max(xy_hole_scaled, xy_contour_scaled);
                        float min_growth = std::min(xy_hole_scaled, xy_contour_scaled);
                        ExPolygons merged_poly_for_holes_growing;
                        if (max_growth > 0) {
                            //BBS: merge polygons because region can cut "holes".
                            //Then, cut them to give them again later to their region
                            merged_poly_for_holes_growing = layer->merged(float(SCALED_EPSILON));
                            merged_poly_for_holes_growing = _shrink_contour_holes(std::max(0.f, xy_contour_scaled),
                                                                                  std::max(0.f, xy_hole_scaled),
                                                                                  union_ex(merged_poly_for_holes_growing));
                            // BBS: clipping regions, priority is given to the first regions.
                            Polygons processed;
                            for (size_t region_id = 0; region_id < layer->regions().size(); ++region_id) {
                                ExPolygons slices = to_expolygons(std::move(layer->m_regions[region_id]->slices.surfaces));
                                if (max_growth > 0.f) {
                                    slices = intersection_ex(offset_ex(slices, max_growth), merged_poly_for_holes_growing);
                                }
                                //BBS: Trim by the slices of already processed regions.
                                if (region_id > 0)
                                    slices = diff_ex(to_polygons(std::move(slices)), processed);
                                if (region_id + 1 < layer->regions().size())
                                    // Collect the already processed regions to trim the to be processed regions.
                                    polygons_append(processed, slices);
                                layer->m_regions[region_id]->slices.set(std::move(slices), stInternal);
                            }
                        }
                        if (min_growth < 0.f || elfoot > 0.f) {
                            // Apply the negative XY compensation. (the ones that is <0)
                            ExPolygons trimming;
                            static const float eps = float(scale_(m_config.slice_closing_radius.value) * 1.5);
                            if (elfoot > 0.f) {
                                lslices_1st_layer = offset_ex(layer->merged(eps), -eps);
                                trimming = Slic3r::elephant_foot_compensation(lslices_1st_layer,
                                    layer->m_regions.front()->flow(frExternalPerimeter), unscale<double>(elfoot));
                            } else {
                                trimming = layer->merged(float(SCALED_EPSILON));
                            }
                            if (min_growth < 0.0f)
                                trimming = _shrink_contour_holes(std::min(0.f, xy_contour_scaled),
                                                                 std::min(0.f, xy_hole_scaled),
                                                                 trimming);
                            //BBS: trim surfaces
                            for (size_t region_id = 0; region_id < layer->regions().size(); ++region_id) {
                                // BBS: split trimming result by region
                                ExPolygons contour_exp = to_expolygons(std::move(layer->regions()[region_id]->slices.surfaces));
                                layer->regions()[region_id]->slices.set(intersection_ex(contour_exp, to_polygons(trimming)), stInternal);
                            }
                        }
                  }
                  // Merge all regions' slices to get islands, chain them by a shortest path.
                  layer->make_slices();
              }
          });
      if (elephant_foot_compensation_scaled > 0.f && ! m_layers.empty()) {
        // The Elephant foot has been compensated, therefore the 1st layer's lslices are shrank with the Elephant foot compensation value.
        // Store the uncompensated value there.
        assert(m_layers.front()->id() == 0);
            //BBS: sort the lslices_1st_layer according to shortest path before saving
            //Otherwise the travel of first layer would be mess.
            Points ordering_points;
            ordering_points.reserve(lslices_1st_layer.size());
            for (const ExPolygon& ex : lslices_1st_layer)
                ordering_points.push_back(ex.contour.first_point());
            std::vector<Points::size_type> order = chain_points(ordering_points);
            ExPolygons lslices_1st_layer_sorted;
            lslices_1st_layer_sorted.reserve(lslices_1st_layer.size());
            for (size_t i : order)
                lslices_1st_layer_sorted.emplace_back(std::move(lslices_1st_layer[i]));
            m_layers.front()->lslices = std::move(lslices_1st_layer_sorted);
    }
  }
    m_print->throw_if_canceled();
    BOOST_LOG_TRIVIAL(debug) << "Slicing volumes - make_slices in parallel - end";
}
References Slic3r::apply_mm_segmentation(), Slic3r::chain_points(), Slic3r::Print::config(), Slic3r::Layer::empty(), L, Slic3r::log_memory_info(), Slic3r::range(), scale_, Slic3r::slice_volumes_inner(), Slic3r::slices_to_regions(), Slic3r::stInternal, Slic3r::PrintBase::throw_if_canceled(), Slic3r::Layer::upper_layer, and Slic3r::zs_from_layers().
slicing_parameters() [1/2]
const SlicingParameters & Slic3r::PrintObject::slicing_parameters () const inline
{ return m_slicing_params; }
References m_slicing_params.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), Slic3r::SeamPlacer::place_seam(), and Slic3r::GCode::process_layer().
slicing_parameters() [2/2]
SlicingParameters Slic3r::PrintObject::slicing_parameters (const DynamicPrintConfig & full_config, const ModelObject & model_object, float object_max_z) static
{
  PrintConfig         print_config;
  PrintObjectConfig   object_config;
  PrintRegionConfig   default_region_config;
  print_config.apply(full_config, true);
  object_config.apply(full_config, true);
  default_region_config.apply(full_config, true);
    // BBS
  size_t              filament_extruders = print_config.filament_diameter.size();
  object_config = object_config_from_model_object(object_config, model_object, filament_extruders);
  std::vector<unsigned int> object_extruders;
  for (const ModelVolume* model_volume : model_object.volumes)
    if (model_volume->is_model_part()) {
      PrintRegion::collect_object_printing_extruders(
        print_config,
        region_config_from_model_volume(default_region_config, nullptr, *model_volume, filament_extruders),
                object_config.brim_type != btNoBrim && object_config.brim_width > 0.,
        object_extruders);
      for (const std::pair<const t_layer_height_range, ModelConfig> &range_and_config : model_object.layer_config_ranges)
        if (range_and_config.second.has("wall_filament") ||
          range_and_config.second.has("sparse_infill_filament") ||
          range_and_config.second.has("solid_infill_filament"))
          PrintRegion::collect_object_printing_extruders(
            print_config,
            region_config_from_model_volume(default_region_config, &range_and_config.second.get(), *model_volume, filament_extruders),
                        object_config.brim_type != btNoBrim && object_config.brim_width > 0.,
            object_extruders);
    }
    sort_remove_duplicates(object_extruders);
    //FIXME add painting extruders
    if (object_max_z <= 0.f)
state_mutex()
std::mutex & Slic3r::PrintObjectBase::state_mutex (PrintBase * print) static protected inherited
{
  return print->state_mutex();
}
References Slic3r::PrintBase::state_mutex().
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::active_step_add_warning(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::is_step_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::set_done(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::set_started(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::step_state_with_timestamp(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::step_state_with_warnings().
status_update_warnings()
void Slic3r::PrintObjectBase::status_update_warnings (PrintBase * print, int step, PrintStateBase::WarningLevel warning_level, const std::string & message, PrintStateBase::SlicingNotificationType message_id = PrintStateBase::SlicingDefaultNotification) protected inherited
{
    print->status_update_warnings(step, warning_level, message, this, message_id);
}
References Slic3r::PrintBase::status_update_warnings().
Referenced by Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::active_step_add_warning(), and Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::set_done().
step_state_with_timestamp()
PrintStateBase::StateWithTimeStamp Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::step_state_with_timestamp (PrintObjectStep step) const inline inherited
{ return m_state.state_with_timestamp(step, PrintObjectBase::state_mutex(m_print)); }
step_state_with_warnings()
PrintStateBase::StateWithWarnings Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::step_state_with_warnings (PrintObjectStep step) const inline inherited
{ return m_state.state_with_warnings(step, PrintObjectBase::state_mutex(m_print)); }
support_layer_count()
size_t Slic3r::PrintObject::support_layer_count () const inline
{ return m_support_layers.size(); }
References m_support_layers.
Referenced by Slic3r::TreeSupport::detect_overhangs(), and total_layer_count().
support_layers() [1/2]
SupportLayerPtrs & Slic3r::PrintObject::support_layers () inline
{ return m_support_layers; }
References m_support_layers.
support_layers() [2/2]
ConstSupportLayerPtrsAdaptor Slic3r::PrintObject::support_layers () const inline
{ return ConstSupportLayerPtrsAdaptor(&m_support_layers); }
References m_support_layers.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_print_toolpaths(), copy_layers_from_shared_object(), Slic3r::getAllLayersExtrusionPathsFromObject(), and Slic3r::GUI::GLGizmoFdmSupports::run_thread().
throw_if_canceled()
void Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::throw_if_canceled () inline protected inherited
{ if (m_print->canceled()) throw CanceledException(); }
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
total_layer_count()
size_t Slic3r::PrintObject::total_layer_count () const inline
{ return this->layer_count() + this->support_layer_count(); }
References layer_count(), and support_layer_count().
trafo()
const Transform3d & Slic3r::PrintObject::trafo () const inline
{ return m_trafo; }
References m_trafo.
Referenced by Slic3r::multi_material_segmentation_by_painting(), Slic3r::Print::process(), and trafo_centered().
trafo_centered()
Transform3d Slic3r::PrintObject::trafo_centered () const inline
        { Transform3d t = this->trafo(); t.pretranslate(Vec3d(- unscale<double>(m_center_offset.x()), - unscale<double>(m_center_offset.y()), 0)); return t; }
References m_center_offset, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::pretranslate(), and trafo().
Referenced by Slic3r::SeamPlacerImpl::compute_global_occlusion(), Slic3r::SeamPlacerImpl::gather_enforcers_blockers(), and Slic3r::mmu_segmentation_top_and_bottom_layers().
update_layer_height_profile()
bool Slic3r::PrintObject::update_layer_height_profile (const ModelObject & model_object, const SlicingParameters & slicing_parameters, std::vector< coordf_t > & layer_height_profile) static
{
    bool updated = false;
    if (layer_height_profile.empty()) {
        // use the constructor because the assignement is crashing on ASAN OsX
        layer_height_profile = std::vector<coordf_t>(model_object.layer_height_profile.get());
//        layer_height_profile = model_object.layer_height_profile;
        updated = true;
    }
    // Verify the layer_height_profile.
    if (!layer_height_profile.empty() &&
        // Must not be of even length.
        ((layer_height_profile.size() & 1) != 0 ||
            // Last entry must be at the top of the object.
            std::abs(layer_height_profile[layer_height_profile.size() - 2] - slicing_parameters.object_print_z_max + slicing_parameters.object_print_z_min) > 1e-3))
        layer_height_profile.clear();
    if (layer_height_profile.empty() || layer_height_profile[1] != slicing_parameters.first_object_layer_height) {
        //layer_height_profile = layer_height_profile_adaptive(slicing_parameters, model_object.layer_config_ranges, model_object.volumes);
        layer_height_profile = layer_height_profile_from_ranges(slicing_parameters, model_object.layer_config_ranges);
        updated = true;
    }
Referenced by Slic3r::Print::validate().
update_slicing_parameters()
void Slic3r::PrintObject::update_slicing_parameters () private
{
    if (!m_slicing_params.valid)
References Slic3r::profiler.
Friends And Related Symbol Documentation
Print
friend class Print friend
Member Data Documentation
clip_multipart_objects
bool Slic3r::PrintObject::clip_multipart_objects = true static
firstLayerObjectBrimBoundingBox
BoundingBox Slic3r::PrintObject::firstLayerObjectBrimBoundingBox
Referenced by get_first_layer_bbox().
firstLayerObjSliceByGroups
std::vector<groupedVolumeSlices> Slic3r::PrintObject::firstLayerObjSliceByGroups private
Referenced by copy_layers_from_shared_object(), firstLayerObjGroups(), and firstLayerObjGroupsMod().
firstLayerObjSliceByVolume
std::vector< VolumeSlices > Slic3r::PrintObject::firstLayerObjSliceByVolume private
Referenced by copy_layers_from_shared_object(), firstLayerObjSlice(), and firstLayerObjSliceMod().
infill_only_where_needed
bool Slic3r::PrintObject::infill_only_where_needed = false static
Referenced by Slic3r::LayerRegion::prepare_fill_surfaces().
m_center_offset
Point Slic3r::PrintObject::m_center_offset private
Referenced by PrintObject(), center_offset(), set_instances(), and trafo_centered().
m_config
PrintObjectConfig Slic3r::PrintObject::m_config private
Referenced by config(), config_apply(), config_apply_only(), configBrimWidth(), has_raft(), and has_support().
m_id
size_t Slic3r::PrintObject::m_id private
Referenced by get_id(), and set_id().
m_instances
std::vector<PrintInstance> Slic3r::PrintObject::m_instances private
Referenced by instances(), instances(), and set_instances().
m_layers
LayerPtrs Slic3r::PrintObject::m_layers private
Referenced by clear_shared_object(), copy_layers_from_shared_object(), copy_layers_overhang_from_shared_object(), get_layer(), get_layer(), layer_count(), layers(), layers(), and make_perimeters().
m_model_object
ModelObject* Slic3r::PrintObjectBase::m_model_object protected inherited
Referenced by Slic3r::SLAPrintObject::SLAPrintObject(), Slic3r::PrintObjectBase::model_object(), Slic3r::PrintObjectBase::model_object(), Slic3r::SLAPrint::Steps::support_points(), Slic3r::SLAPrintObject::transformed_drainhole_points(), and Slic3r::SLAPrintObject::transformed_support_points().
m_print
Print * Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::m_print protected inherited
m_shared_object
PrintObject* Slic3r::PrintObject::m_shared_object { nullptr } private
Referenced by ~PrintObject(), clear_shared_object(), copy_layers_from_shared_object(), copy_layers_overhang_from_shared_object(), get_shared_object(), and set_shared_object().
m_shared_regions
PrintObjectRegions* Slic3r::PrintObject::m_shared_regions { nullptr } private
Referenced by ~PrintObject(), all_regions(), num_printing_regions(), printing_region(), and shared_regions().
m_size
Vec3crd Slic3r::PrintObject::m_size private
Referenced by PrintObject(), bounding_box(), height(), and size().
m_skirt
ExtrusionEntityCollection Slic3r::PrintObject::m_skirt private
Referenced by object_skirt().
m_slicing_params
SlicingParameters Slic3r::PrintObject::m_slicing_params private
Referenced by slicing_parameters().
m_state
PrintState<PrintObjectStep , COUNT> Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::m_state private inherited
m_support_layers
SupportLayerPtrs Slic3r::PrintObject::m_support_layers private
Referenced by clear_shared_object(), copy_layers_from_shared_object(), get_support_layer(), support_layer_count(), support_layers(), and support_layers().
m_trafo
Transform3d Slic3r::PrintObject::m_trafo = Transform3d::Identity() private
Referenced by trafo().
m_tree_support_preview_cache
std::shared_ptr<TreeSupportData> Slic3r::PrintObject::m_tree_support_preview_cache private
Referenced by clear_tree_support_preview_cache().
m_typed_slices
bool Slic3r::PrintObject::m_typed_slices = false private
Referenced by make_perimeters().
PrintType
friend Slic3r::PrintObjectBaseWithState< Print , PrintObjectStep , COUNT >::Print protected inherited
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
The documentation for this class was generated from the following files:
src/libslic3r/Print.hpp
src/libslic3r/Print.cpp
src/libslic3r/PrintObject.cpp
src/libslic3r/PrintObjectSlice.cpp