OrcaSlicer: src/qhull/src/libqhullcpp/QhullFacetSet.cpp File Reference
QhullFacetSet.cpp File Reference
#include "libqhullcpp/QhullFacetSet.h"
#include "libqhullcpp/QhullFacet.h"
#include "libqhullcpp/QhullPoint.h"
#include "libqhullcpp/QhullRidge.h"
#include "libqhullcpp/QhullVertex.h"
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global functions
ostream & operator<< (ostream &os, const QhullFacetSet &fs)
ostream & operator<< (ostream &os, const QhullFacetSet::PrintFacetSet &pr)
ostream & operator<< (ostream &os, const QhullFacetSet::PrintIdentifiers &p)
Print facet identifiers to stream. Space prefix. From qh_printfacetheader [io_r.c].
Function Documentation
operator<<() [1/3]
ostream & operator<< (ostream & os, const QhullFacetSet & fs)
{
    os << fs.print("");
    return os;
}//<<QhullFacetSet
operator<<() [2/3]
ostream & operator<< (ostream & os, const QhullFacetSet::PrintFacetSet & pr)
{
    os << pr.print_message;
    QhullFacetSet fs= *pr.facet_set;
    for(QhullFacetSet::iterator i=fs.begin(); i != fs.end(); ++i){
        QhullFacet f= *i;
        if(fs.isSelectAll() || f.isGood()){
            os << f;
        }
    }
    return os;
}//<< QhullFacetSet::PrintFacetSet
References orgQhull::QhullFacet::isGood().
operator<<() [3/3]
ostream & operator<< (ostream & os, const QhullFacetSet::PrintIdentifiers & p)
Print facet identifiers to stream. Space prefix. From qh_printfacetheader [io_r.c].
{
    os << p.print_message;
    for(QhullFacetSet::const_iterator i=p.facet_set->begin(); i!=p.facet_set->end(); ++i){
        const QhullFacet f= *i;
        if(f.getFacetT()==qh_MERGEridge){
            os << " MERGE";
        }else if(f.getFacetT()==qh_DUPLICATEridge){
            os << " DUP";
        }else if(p.facet_set->isSelectAll() || f.isGood()){
            os << " f" << f.id();
        }
    }
    os << endl;
    return os;
}//<<QhullFacetSet::PrintIdentifiers
References orgQhull::QhullFacet::getFacetT(), orgQhull::QhullFacet::id(), orgQhull::QhullFacet::isGood(), qh_DUPLICATEridge, and qh_MERGEridge.