OrcaSlicer: Slic3r::Model Class Reference
Slic3r::Model Class Reference final
#include <src/libslic3r/Model.hpp>
Public Types
using Timestamp = uint64_t
Public Member Functions
void SetDesigner (std::string designer, std::string designer_user_id)
const CustomGCode::Info get_curr_plate_custom_gcodes () const
Model ()
~Model ()
Model (const Model &rhs)
Model (Model &&rhs)
Model & operator= (const Model &rhs)
Model & operator= (Model &&rhs)
ModelObject * add_object ()
ModelObject * add_object (const char *name, const char *path, const TriangleMesh &mesh)
ModelObject * add_object (const char *name, const char *path, TriangleMesh &&mesh)
ModelObject * add_object (const ModelObject &other)
void delete_object (size_t idx)
bool delete_object (ObjectID id)
bool delete_object (ModelObject *object)
void clear_objects ()
void collect_reusable_objects (std::vector< ObjectBase * > &objects)
void set_object_backup_id (ModelObject const &object, int uuid)
int get_object_backup_id (ModelObject const &object)
int get_object_backup_id (ModelObject const &object) const
ModelMaterial * add_material (t_model_material_id material_id)
ModelMaterial * add_material (t_model_material_id material_id, const ModelMaterial &other)
ModelMaterial * get_material (t_model_material_id material_id)
void delete_material (t_model_material_id material_id)
void clear_materials ()
bool add_default_instances ()
BoundingBoxf3 bounding_box () const
unsigned int update_print_volume_state (const BuildVolume &build_volume)
bool center_instances_around_point (const Vec2d &point)
void translate (coordf_t x, coordf_t y, coordf_t z)
TriangleMesh mesh () const
void duplicate_objects_grid (size_t x, size_t y, coordf_t dist)
bool looks_like_multipart_object () const
void convert_multipart_object (unsigned int max_extruders)
bool looks_like_imperial_units () const
void convert_from_imperial_units (bool only_small_volumes)
bool looks_like_saved_in_meters () const
void convert_from_meters (bool only_small_volumes)
int removed_objects_with_zero_volume ()
void adjust_min_z ()
void print_info () const
std::string propose_export_file_name_and_path () const
std::string propose_export_file_name_and_path (const std::string &new_extension) const
std::string get_auxiliary_file_temp_path ()
std::string get_backup_path ()
std::string get_backup_path (const std::string &sub_path)
void set_backup_path (const std::string &path)
void load_from (Model &model)
bool is_need_backup ()
void set_need_backup ()
void remove_backup_path_if_exist ()
bool is_fdm_support_painted () const
bool is_seam_painted () const
bool is_mm_painted () const
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Member Functions
static Model read_from_file (const std::string &input_file, DynamicPrintConfig *config=nullptr, ConfigSubstitutionContext *config_substitutions=nullptr, LoadStrategy options=LoadStrategy::AddDefaultInstances, PlateDataPtrs *plate_data=nullptr, std::vector< Preset * > *project_presets=nullptr, bool *is_xxx=nullptr, Semver *file_version=nullptr, Import3mfProgressFn proFn=nullptr, ImportstlProgressFn stlFn=nullptr, ImportStepProgressFn stepFn=nullptr, StepIsUtf8Fn stepIsUtf8Fn=nullptr, BBLProject *project=nullptr, int plate_id=0)
static double findMaxSpeed (const ModelObject *object)
static double getThermalLength (const ModelVolume *modelVolumePtr)
static double getThermalLength (const std::vector< ModelVolume * > modelVolumePtrs)
static Polygon getBedPolygon ()
static Model read_from_archive (const std::string &input_file, DynamicPrintConfig *config, ConfigSubstitutionContext *config_substitutions, En3mfType &out_file_type, LoadStrategy options=LoadStrategy::AddDefaultInstances, PlateDataPtrs *plate_data=nullptr, std::vector< Preset * > *project_presets=nullptr, Semver *file_version=nullptr, Import3mfProgressFn proFn=nullptr, BBLProject *project=nullptr)
Public Attributes
ModelMaterialMap materials
ModelObjectPtrs objects
ModelWipeTower wipe_tower
std::shared_ptr< ModelDesignInfo > design_info = nullptr
std::shared_ptr< ModelInfo > model_info = nullptr
std::shared_ptr< ModelProfileInfo > profile_info = nullptr
int curr_plate_index { 0 }
std::map< int, CustomGCode::Info > plates_custom_gcodes
std::unique_ptr< CalibPressureAdvancePattern > calib_pa_pattern
Static Public Attributes
static std::map< size_t, ExtruderParams > extruderParamsMap = { {0,{"",0,0}}}
static GlobalSpeedMap printSpeedMap {}
Protected Member Functions
void set_new_unique_id ()
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
Private Member Functions
Model (int)
void assign_new_unique_ids_recursive ()
void update_links_bottom_up_recursive ()
template<class Archive >
void load (Archive &ar)
template<class Archive >
void save (Archive &ar) const
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
std::string backup_path
bool need_backup = false
std::map< int, int > object_backup_id_map
int next_object_backup_id = 1
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class cereal::access
class UndoRedo::StackImpl
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
Model() [1/4]
Slic3r::Model::Model () inline
{ assert(this->id().valid()); }
~Model()
Slic3r::Model::~Model ()
{
    this->clear_objects();
    this->clear_materials();
    // BBS: clear backup dir of temparary model
    if (!backup_path.empty())
        Slic3r::remove_backup(*this, true);
}
References backup_path, clear_materials(), clear_objects(), and Slic3r::remove_backup().
Model() [2/4]
Slic3r::Model::Model (const Model & rhs) inline
: ObjectBase(-1) { assert(this->id().invalid()); this->assign_copy(rhs); assert(this->id().valid()); assert(this->id() == rhs.id()); }
References Slic3r::ObjectBase::id().
Model() [3/4]
Slic3r::Model::Model (Model && rhs) inline
: ObjectBase(-1) { assert(this->id().invalid()); this->assign_copy(std::move(rhs)); assert(this->id().valid()); assert(this->id() == rhs.id()); }
Model() [4/4]
Slic3r::Model::Model (int) inline explicit private
                        : ObjectBase(-1)
        {
        assert(this->id().invalid());
    }
Member Function Documentation
add_default_instances()
bool Slic3r::Model::add_default_instances ()
{
    // apply a default position to all objects not having one
    for (ModelObject *o : this->objects)
        if (o->instances.empty())
            o->add_instance();
    return true;
}
References objects.
Referenced by read_from_archive(), read_from_file(), and Slic3r::CLI::run().
add_material() [1/2]
ModelMaterial * Slic3r::Model::add_material (t_model_material_id material_id)
{
    assert(! material_id.empty());
    ModelMaterial* material = this->get_material(material_id);
    if (material == nullptr)
        material = this->materials[material_id] = new ModelMaterial(this);
    return material;
}
References get_material(), and materials.
Referenced by Slic3r::AMFParserContext::startElement().
add_material() [2/2]
ModelMaterial * Slic3r::Model::add_material (t_model_material_id material_id, const ModelMaterial & other)
{
    assert(! material_id.empty());
    // delete existing material if any
    ModelMaterial* material = this->get_material(material_id);
    delete material;
    // set new material
  material = new ModelMaterial(other);
  material->set_model(this);
    this->materials[material_id] = material;
    return material;
}
References get_material(), materials, and Slic3r::ModelMaterial::set_model().
add_object() [1/4]
ModelObject * Slic3r::Model::add_object ()
{
    this->objects.emplace_back(new ModelObject(this));
    return this->objects.back();
}
References objects.
Referenced by Slic3r::_BBS_3MF_Importer::_create_object_instance(), Slic3r::_3MF_Importer::_handle_start_object(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::GUI::Selection::Clipboard::add_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::AMFParserContext::endDocument(), Slic3r::GUI::ObjectList::instances_to_separated_object(), Slic3r::GUI::ObjectList::instances_to_separated_objects(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::load_obj(), Slic3r::load_stl(), Slic3r::load_svg(), Slic3r::GUI::ObjectList::merge(), Slic3r::GUI::Selection::paste_objects_from_clipboard(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::CLI::run(), Slic3r::ModelObject::split(), and Slic3r::AMFParserContext::startElement().
add_object() [2/4]
ModelObject * Slic3r::Model::add_object (const char * name, const char * path, const TriangleMesh & mesh)
{
    ModelObject* new_object = new ModelObject(this);
    this->objects.push_back(new_object);
    new_object->name = name;
    new_object->input_file = path;
    ModelVolume *new_volume = new_object->add_volume(mesh);
    new_volume->name = name;
    new_volume->source.input_file = path;
    new_volume->source.object_idx = (int)this->objects.size() - 1;
    new_volume->source.volume_idx = (int)new_object->volumes.size() - 1;
    // BBS: set extruder id to 1
    if (!new_object->config.has("extruder") || new_object->config.extruder() == 0)
        new_object->config.set_key_value("extruder", new ConfigOptionInt(1));
    new_object->invalidate_bounding_box();
    return new_object;
}
References Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::config, Slic3r::ModelConfig::extruder(), Slic3r::ModelConfig::has(), Slic3r::ModelObject::input_file, Slic3r::ModelVolume::Source::input_file, int, Slic3r::ModelObject::invalidate_bounding_box(), mesh(), Slic3r::ModelObject::name, Slic3r::ModelVolume::name, Slic3r::ModelVolume::Source::object_idx, objects, Slic3r::ModelConfig::set_key_value(), Slic3r::ModelVolume::source, Slic3r::ModelVolume::Source::volume_idx, and Slic3r::ModelObject::volumes.
add_object() [3/4]
ModelObject * Slic3r::Model::add_object (const char * name, const char * path, TriangleMesh && mesh)
{
    ModelObject* new_object = new ModelObject(this);
    this->objects.push_back(new_object);
    new_object->name = name;
    new_object->input_file = path;
    ModelVolume *new_volume = new_object->add_volume(std::move(mesh));
    new_volume->name = name;
    new_volume->source.input_file = path;
    new_volume->source.object_idx = (int)this->objects.size() - 1;
    new_volume->source.volume_idx = (int)new_object->volumes.size() - 1;
    // BBS: set default extruder id to 1
    if (!new_object->config.has("extruder") || new_object->config.extruder() == 0)
        new_object->config.set_key_value("extruder", new ConfigOptionInt(1));
    new_object->invalidate_bounding_box();
    return new_object;
}
References Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::config, Slic3r::ModelConfig::extruder(), Slic3r::ModelConfig::has(), Slic3r::ModelObject::input_file, Slic3r::ModelVolume::Source::input_file, int, Slic3r::ModelObject::invalidate_bounding_box(), mesh(), Slic3r::ModelObject::name, Slic3r::ModelVolume::name, Slic3r::ModelVolume::Source::object_idx, objects, Slic3r::ModelConfig::set_key_value(), Slic3r::ModelVolume::source, Slic3r::ModelVolume::Source::volume_idx, and Slic3r::ModelObject::volumes.
add_object() [4/4]
ModelObject * Slic3r::Model::add_object (const ModelObject & other)
{
  ModelObject* new_object = ModelObject::new_clone(other);
    new_object->set_model(this);
    // BBS: set default extruder id to 1
    if (!new_object->config.has("extruder") || new_object->config.extruder() == 0)
        new_object->config.set_key_value("extruder", new ConfigOptionInt(1));
    this->objects.push_back(new_object);
    // BBS: backup
    if (need_backup) {
        if (auto model = other.get_model()) {
            auto iter = object_backup_id_map.find(other.id().id);
            if (iter != object_backup_id_map.end()) {
                object_backup_id_map.emplace(new_object->id().id, iter->second);
                object_backup_id_map.erase(iter);
                return new_object;
            }
        }
        Slic3r::save_object_mesh(*new_object);
    }
    return new_object;
}
References Slic3r::ModelObject::config, Slic3r::ModelConfig::extruder(), Slic3r::ModelObject::get_model(), Slic3r::ModelConfig::has(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), need_backup, object_backup_id_map, objects, Slic3r::save_object_mesh(), Slic3r::ModelConfig::set_key_value(), and Slic3r::ModelObject::set_model().
adjust_min_z()
void Slic3r::Model::adjust_min_z ()
{
    if (objects.empty())
        return;
    if (bounding_box().min(2) < 0.0)
    {
        for (ModelObject* obj : objects)
        {
            if (obj != nullptr)
            {
                coordf_t obj_min_z = obj->bounding_box().min(2);
                if (obj_min_z < 0.0)
                    obj->translate_instances(Vec3d(0.0, 0.0, -obj_min_z));
            }
        }
    }
}
References bounding_box(), min(), and objects.
assign_new_unique_ids_recursive()
void Slic3r::Model::assign_new_unique_ids_recursive () private virtual
Reimplemented from Slic3r::ObjectBase.
{
    this->set_new_unique_id();
    for (std::pair<const t_model_material_id, ModelMaterial*> &m : this->materials)
        m.second->assign_new_unique_ids_recursive();
    for (ModelObject *model_object : this->objects)
        model_object->assign_new_unique_ids_recursive();
}
References materials, objects, and Slic3r::ObjectBase::set_new_unique_id().
bounding_box()
BoundingBoxf3 Slic3r::Model::bounding_box () const
{
    BoundingBoxf3 bb;
    for (ModelObject *o : this->objects)
        bb.merge(o->bounding_box());
    return bb;
}
References Slic3r::BoundingBox3Base< PointClass >::merge(), and objects.
Referenced by adjust_min_z().
center_instances_around_point()
bool Slic3r::Model::center_instances_around_point (const Vec2d & point)
{
    BoundingBoxf3 bb;
    for (ModelObject *o : this->objects)
        for (size_t i = 0; i < o->instances.size(); ++ i)
            bb.merge(o->instance_bounding_box(i, false));
    Vec2d shift2 = point - to_2d(bb.center());
  if (std::abs(shift2(0)) < EPSILON && std::abs(shift2(1)) < EPSILON)
    // No significant shift, don't do anything.
    return false;
  Vec3d shift3 = Vec3d(shift2(0), shift2(1), 0.0);
  for (ModelObject *o : this->objects) {
    for (ModelInstance *i : o->instances)
      i->set_offset(i->get_offset() + shift3);
    o->invalidate_bounding_box();
  }
  return true;
}
References Slic3r::BoundingBox3Base< PointClass >::center(), EPSILON, Slic3r::BoundingBox3Base< PointClass >::merge(), objects, and Slic3r::to_2d().
Referenced by Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::ObjectList::load_modifier(), and Slic3r::GUI::Plater::priv::update().
clear_materials()
void Slic3r::Model::clear_materials ()
{
    for (auto &m : this->materials)
        delete m.second;
    this->materials.clear();
}
References materials.
Referenced by ~Model(), and Slic3r::UndoRedo::StackImpl::load_snapshot().
clear_objects()
void Slic3r::Model::clear_objects ()
{
    for (ModelObject* o : this->objects) {
        // BBS: backup
        Slic3r::delete_object_mesh(*o);
        delete o;
    }
    this->objects.clear();
    object_backup_id_map.clear();
    next_object_backup_id = 1;
}
References Slic3r::delete_object_mesh(), next_object_backup_id, object_backup_id_map, and objects.
Referenced by ~Model(), Slic3r::Print::clear(), Slic3r::SLAPrint::clear(), convert_multipart_object(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::GUI::Selection::Clipboard::reset(), and Slic3r::GUI::Plater::priv::reset().
collect_reusable_objects()
void Slic3r::Model::collect_reusable_objects (std::vector< ObjectBase * > & objects)
{
    for (ModelObject* model_object : this->objects) {
        objects.push_back(model_object);
        for (ModelVolume* model_volume : model_object->volumes)
            objects.push_back(model_volume);
        std::transform(model_object->volumes.begin(),
                       model_object->volumes.end(),
                       std::back_inserter(model_object->volume_ids),
                       std::mem_fn(&ObjectBase::id));
        model_object->volumes.clear();
    }
    // we never own these objects
    this->objects.clear();
}
References Slic3r::ObjectBase::id(), and objects.
Referenced by Slic3r::UndoRedo::StackImpl::load_snapshot().
convert_from_imperial_units()
void Slic3r::Model::convert_from_imperial_units (bool only_small_volumes)
{
    static constexpr const float in_to_mm = 25.4f;
    for (ModelObject* obj : this->objects)
        if (! only_small_volumes || obj->get_object_stl_stats().volume < volume_threshold_inches) {
            obj->scale_mesh_after_creation(in_to_mm);
            for (ModelVolume* v : obj->volumes) {
                assert(! v->source.is_converted_from_meters);
                v->source.is_converted_from_inches = true;
            }
        }
}
References objects, and Slic3r::volume_threshold_inches.
Referenced by Slic3r::GUI::Plater::priv::load_files().
convert_from_meters()
void Slic3r::Model::convert_from_meters (bool only_small_volumes)
{
    static constexpr const double m_to_mm = 1000;
    for (ModelObject* obj : this->objects)
        if (! only_small_volumes || obj->get_object_stl_stats().volume < volume_threshold_meters) {
            obj->scale_mesh_after_creation(m_to_mm);
            for (ModelVolume* v : obj->volumes) {
                assert(! v->source.is_converted_from_inches);
                v->source.is_converted_from_meters = true;
            }
        }
}
References objects, and Slic3r::volume_threshold_meters.
Referenced by Slic3r::GUI::Plater::priv::load_files().
convert_multipart_object()
void Slic3r::Model::convert_multipart_object (unsigned int max_extruders)
{
    assert(this->objects.size() >= 2);
    if (this->objects.size() < 2)
        return;
    ModelObject* object = new ModelObject(this);
    object->input_file = this->objects.front()->input_file;
    object->name = boost::filesystem::path(this->objects.front()->input_file).stem().string();
    //FIXME copy the config etc?
    unsigned int extruder_counter = 0;
  for (const ModelObject* o : this->objects)
      for (const ModelVolume* v : o->volumes) {
            // If there are more than one object, put all volumes together
            // Each object may contain any number of volumes and instances
            // The volumes transformations are relative to the object containing them...
            Geometry::Transformation trafo_volume = v->get_transformation();
            // Revert the centering operation.
            trafo_volume.set_offset(trafo_volume.get_offset() - o->origin_translation);
            int counter = 1;
            auto copy_volume = [o, v, max_extruders, &counter, &extruder_counter](ModelVolume *new_v) {
                assert(new_v != nullptr);
                new_v->name = (counter > 1) ? o->name + "_" + std::to_string(counter++) : o->name;
                //BBS: Use extruder priority: volumn > object > default
                if (v->config.option("extruder"))
                    new_v->config.set("extruder", v->config.extruder());
                else if (o->config.option("extruder"))
                    new_v->config.set("extruder", o->config.extruder());
                return new_v;
            };
            if (o->instances.empty()) {
                copy_volume(object->add_volume(*v))->set_transformation(trafo_volume);
            } else {
                for (const ModelInstance* i : o->instances)
                    // ...so, transform everything to a common reference system (world)
                    copy_volume(object->add_volume(*v))->set_transformation(i->get_transformation() * trafo_volume);
            }
        }
    // commented-out to fix #2868
//    object->add_instance();
//    object->instances[0]->set_offset(object->raw_mesh_bounding_box().center());
    this->clear_objects();
    this->objects.push_back(object);
}
References clear_objects(), Slic3r::Geometry::Transformation::get_offset(), objects, and Slic3r::Geometry::Transformation::set_offset().
Referenced by Slic3r::GUI::Plater::priv::load_files().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
delete_material()
void Slic3r::Model::delete_material (t_model_material_id material_id)
{
    ModelMaterialMap::iterator i = this->materials.find(material_id);
    if (i != this->materials.end()) {
        delete i->second;
        this->materials.erase(i);
    }
}
References materials.
delete_object() [1/3]
bool Slic3r::Model::delete_object (ModelObject * object)
{
    if (object != nullptr) {
        size_t idx = 0;
        for (ModelObject *model_object : objects) {
            if (model_object == object) {
                // BBS: backup
                Slic3r::delete_object_mesh(*model_object);
                delete model_object;
                objects.erase(objects.begin() + idx);
                return true;
            }
            ++ idx;
        }
    }
    return false;
}
References Slic3r::delete_object_mesh(), and objects.
delete_object() [2/3]
bool Slic3r::Model::delete_object (ObjectID id)
{
    if (id.id != 0) {
        size_t idx = 0;
        for (ModelObject *model_object : objects) {
            if (model_object->id() == id) {
                // BBS: backup
                Slic3r::delete_object_mesh(*model_object);
                delete model_object;
                objects.erase(objects.begin() + idx);
                return true;
            }
            ++ idx;
        }
    }
    return false;
}
References Slic3r::delete_object_mesh(), Slic3r::ObjectBase::id(), and objects.
delete_object() [3/3]
void Slic3r::Model::delete_object (size_t idx)
{
    ModelObjectPtrs::iterator i = this->objects.begin() + idx;
    // BBS: backup
    Slic3r::delete_object_mesh(**i);
    delete *i;
    this->objects.erase(i);
}
References Slic3r::delete_object_mesh(), and objects.
Referenced by Slic3r::_3MF_Importer::_handle_end_model(), Slic3r::_BBS_3MF_Importer::_handle_end_model(), Slic3r::_3MF_Importer::_handle_end_object(), Slic3r::GUI::ObjectList::delete_all_connectors_for_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::Plater::priv::remove(), and removed_objects_with_zero_volume().
duplicate_objects_grid()
void Slic3r::Model::duplicate_objects_grid (size_t x, size_t y, coordf_t dist)
{
    if (this->objects.size() > 1) throw "Grid duplication is not supported with multiple objects";
    if (this->objects.empty()) throw "No objects!";
    ModelObject* object = this->objects.front();
    object->clear_instances();
    Vec3d ext_size = object->bounding_box().size() + dist * Vec3d::Ones();
    for (size_t x_copy = 1; x_copy <= x; ++x_copy) {
        for (size_t y_copy = 1; y_copy <= y; ++y_copy) {
            ModelInstance* instance = object->add_instance();
            instance->set_offset(Vec3d(ext_size(0) * (double)(x_copy - 1), ext_size(1) * (double)(y_copy - 1), 0.0));
        }
    }
}
References objects, and Slic3r::ModelInstance::set_offset().
findMaxSpeed()
double Slic3r::Model::findMaxSpeed (const ModelObject * object) static
{
    auto objectKeys = object->config.keys();
    double objMaxSpeed = -1.;
    if (objectKeys.empty())
        return Model::printSpeedMap.maxSpeed;
    double perimeterSpeedObj = Model::printSpeedMap.perimeterSpeed;
    double externalPerimeterSpeedObj = Model::printSpeedMap.externalPerimeterSpeed;
    double infillSpeedObj = Model::printSpeedMap.infillSpeed;
    double solidInfillSpeedObj = Model::printSpeedMap.solidInfillSpeed;
    double topSolidInfillSpeedObj = Model::printSpeedMap.topSolidInfillSpeed;
    double supportSpeedObj = Model::printSpeedMap.supportSpeed;
    double smallPerimeterSpeedObj = Model::printSpeedMap.smallPerimeterSpeed;
    for (std::string objectKey : objectKeys) {
        if (objectKey == "inner_wall_speed"){
            perimeterSpeedObj = object->config.opt_float(objectKey);
            externalPerimeterSpeedObj = Model::printSpeedMap.externalPerimeterSpeed / Model::printSpeedMap.perimeterSpeed * perimeterSpeedObj;
        }
        if (objectKey == "sparse_infill_speed")
            infillSpeedObj = object->config.opt_float(objectKey);
        if (objectKey == "internal_solid_infill_speed")
            solidInfillSpeedObj = object->config.opt_float(objectKey);
        if (objectKey == "top_surface_speed")
            topSolidInfillSpeedObj = object->config.opt_float(objectKey);
        if (objectKey == "support_speed")
            supportSpeedObj = object->config.opt_float(objectKey);
        if (objectKey == "outer_wall_speed")
            externalPerimeterSpeedObj = object->config.opt_float(objectKey);
        if (objectKey == "small_perimeter_speed")
            smallPerimeterSpeedObj = object->config.opt_float(objectKey);
    }
    objMaxSpeed = std::max(perimeterSpeedObj, std::max(externalPerimeterSpeedObj, std::max(infillSpeedObj, std::max(solidInfillSpeedObj, std::max(topSolidInfillSpeedObj, std::max(supportSpeedObj, std::max(smallPerimeterSpeedObj, objMaxSpeed)))))));
    if (objMaxSpeed <= 0) objMaxSpeed = 250.;
    return objMaxSpeed;
}
References Slic3r::GlobalSpeedMap::externalPerimeterSpeed, Slic3r::GlobalSpeedMap::infillSpeed, Slic3r::GlobalSpeedMap::maxSpeed, Slic3r::GlobalSpeedMap::perimeterSpeed, printSpeedMap, Slic3r::GlobalSpeedMap::smallPerimeterSpeed, Slic3r::GlobalSpeedMap::solidInfillSpeed, Slic3r::GlobalSpeedMap::supportSpeed, and Slic3r::GlobalSpeedMap::topSolidInfillSpeed.
Referenced by Slic3r::ModelInstance::get_auto_brim_width().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_auxiliary_file_temp_path()
std::string Slic3r::Model::get_auxiliary_file_temp_path ()
{
    return get_backup_path("/Auxiliaries");
}
References get_backup_path().
Referenced by Slic3r::_BBS_3MF_Importer::_extract_auxiliary_file_from_archive(), Slic3r::_BBS_3MF_Exporter::_save_model_to_file(), Slic3r::GUI::AuxiliaryPanel::init_auxiliary(), and AuxiliaryList::init_auxiliary().
get_backup_path() [1/2]
std::string Slic3r::Model::get_backup_path ()
{
    if (backup_path.empty())
    {
        auto pid = get_current_pid();
        boost::filesystem::path parent_path(temporary_dir());
        std::time_t t = std::time(0);
        std::tm* now_time = std::localtime(&t);
        std::stringstream buf;
        buf << "/orcaslicer_model/";
        buf << std::put_time(now_time, "%a_%b_%d/%H_%M_%S#");
        buf << pid << "#";
        buf << this->id().id;
        backup_path = parent_path.string() + buf.str();
        BOOST_LOG_TRIVIAL(info) << boost::format("model %1%, id %2%, backup_path empty, set to %3%")%this%this->id().id%backup_path;
        boost::filesystem::path temp_path(backup_path);
        if (boost::filesystem::exists(temp_path))
        {
            BOOST_LOG_TRIVIAL(info) << boost::format("model %1%, id %2%, remove previous %3%")%this%this->id().id%backup_path;
            boost::filesystem::remove_all(temp_path);
        }
    }
    boost::filesystem::path temp_path(backup_path);
    try {
        if (!boost::filesystem::exists(temp_path))
        {
            BOOST_LOG_TRIVIAL(info) << "create /3D/Objects in " << temp_path;
            boost::filesystem::create_directories(backup_path + "/3D/Objects");
            BOOST_LOG_TRIVIAL(info) << "create /Metadata in " << temp_path;
            boost::filesystem::create_directories(backup_path + "/Metadata");
            BOOST_LOG_TRIVIAL(info) << "create /lock.txt in " << temp_path;
            boost::filesystem::save_string_file(backup_path + "/lock.txt",
                boost::lexical_cast<std::string>(get_current_pid()));
        }
    } catch (std::exception &ex) {
        BOOST_LOG_TRIVIAL(error) << "Failed to create backup path" << temp_path << ": " << ex.what();
    }
    return backup_path;
}
References backup_path, error, Slic3r::get_current_pid(), Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), and Slic3r::temporary_dir().
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::_BBS_3MF_Exporter::_add_project_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_project_embedded_presets_to_archive(), Slic3r::_BBS_3MF_Importer::_extract_project_config_from_archive(), get_auxiliary_file_temp_path(), get_backup_path(), Slic3r::GUI::PartPlate::get_temp_config_3mf_path(), Slic3r::GUI::PartPlate::get_tmp_gcode_path(), load_from(), Slic3r::_BBS_3MF_Importer::load_model_from_file(), Slic3r::_BBS_Backup_Manager::remove_backup(), and Slic3r::_BBS_3MF_Exporter::save_model_to_file().
get_backup_path() [2/2]
std::string Slic3r::Model::get_backup_path (const std::string & sub_path)
{
    auto path = get_backup_path() + "/" + sub_path;
    try {
        if (!boost::filesystem::exists(path)) {
            BOOST_LOG_TRIVIAL(info) << "create missing sub_path" << path;
            boost::filesystem::create_directories(path);
        }
    } catch (std::exception &ex) {
        BOOST_LOG_TRIVIAL(error) << "Failed to create missing sub_path" << path << ": " << ex.what();
    }
    return path;
}
References error, and get_backup_path().
get_curr_plate_custom_gcodes()
const CustomGCode::Info Slic3r::Model::get_curr_plate_custom_gcodes () const inline
{
        if (plates_custom_gcodes.find(curr_plate_index) != plates_custom_gcodes.end()) {
            return plates_custom_gcodes.at(curr_plate_index);
        }
        return CustomGCode::Info();
    }
References curr_plate_index, and plates_custom_gcodes.
Referenced by Slic3r::ToolOrdering::ToolOrdering(), Slic3r::Print::apply(), Slic3r::ToolOrdering::assign_custom_gcodes(), and Slic3r::GUI::Preview::update_layers_slider().
get_material()
ModelMaterial * Slic3r::Model::get_material (t_model_material_id material_id) inline
{
        ModelMaterialMap::iterator i = this->materials.find(material_id);
        return (i == this->materials.end()) ? nullptr : i->second;
    }
Referenced by add_material(), add_material(), and Slic3r::ModelVolume::material().
get_object_backup_id() [1/2]
int Slic3r::Model::get_object_backup_id (ModelObject const & object)
{
    auto i = object_backup_id_map.find(object.id().id);
    if (i == object_backup_id_map.end()) {
        i = object_backup_id_map.insert(std::make_pair(object.id().id, next_object_backup_id++)).first;
    }
    return i->second;
}
References next_object_backup_id, and object_backup_id_map.
Referenced by Slic3r::ModelObject::get_backup_id().
get_object_backup_id() [2/2]
int Slic3r::Model::get_object_backup_id (ModelObject const & object) const
{
    return object_backup_id_map.find(object.id().id)->second;
}
References object_backup_id_map.
getBedPolygon()
static Polygon Slic3r::Model::getBedPolygon () inline static
{ return Model::printSpeedMap.bed_poly; }
References Slic3r::GlobalSpeedMap::bed_poly, and printSpeedMap.
getThermalLength() [1/2]
double Slic3r::Model::getThermalLength (const ModelVolume * modelVolumePtr) static
{
    double thermalLength = 200.;
    auto aa = modelVolumePtr->extruder_id();
    if (Model::extruderParamsMap.find(aa) != Model::extruderParamsMap.end()) {
        if (Model::extruderParamsMap.at(aa).materialName == "ABS" ||
            Model::extruderParamsMap.at(aa).materialName == "PA-CF" ||
            Model::extruderParamsMap.at(aa).materialName == "PET-CF") {
            thermalLength = 100;
        }
        if (Model::extruderParamsMap.at(aa).materialName == "PC") {
            thermalLength = 40;
        }
        if (Model::extruderParamsMap.at(aa).materialName == "TPU") {
            thermalLength = 1000;
        }
    }
    return thermalLength;
}
References end, Slic3r::ModelVolume::extruder_id(), and extruderParamsMap.
Referenced by Slic3r::ModelInstance::get_auto_brim_width(), and getThermalLength().
getThermalLength() [2/2]
double Slic3r::Model::getThermalLength (const std::vector< ModelVolume * > modelVolumePtrs) static
{
    double thermalLength = 1250.;
    for (const auto& modelVolumePtr : modelVolumePtrs) {
        if (modelVolumePtr != nullptr) {
            // the thermal length of a group is decided by the volume with shortest thermal length
            thermalLength = std::min(thermalLength, getThermalLength(modelVolumePtr));
        }
    }
    return thermalLength;
}
References getThermalLength().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::ModelVolume::ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
is_fdm_support_painted()
bool Slic3r::Model::is_fdm_support_painted () const
{
    return std::any_of(this->objects.cbegin(), this->objects.cend(), [](const ModelObject *mo) { return mo->is_fdm_support_painted(); });
}
References objects.
Referenced by Slic3r::_3MF_Exporter::_add_model_file_to_archive().
is_mm_painted()
bool Slic3r::Model::is_mm_painted () const
{
    return std::any_of(this->objects.cbegin(), this->objects.cend(), [](const ModelObject *mo) { return mo->is_mm_painted(); });
}
References objects.
Referenced by Slic3r::_3MF_Exporter::_add_model_file_to_archive().
is_need_backup()
bool Slic3r::Model::is_need_backup () inline
{ return need_backup;  }
References need_backup.
Referenced by Slic3r::_BBS_Backup_Manager::remove_backup().
is_seam_painted()
bool Slic3r::Model::is_seam_painted () const
{
    return std::any_of(this->objects.cbegin(), this->objects.cend(), [](const ModelObject *mo) { return mo->is_seam_painted(); });
}
References objects.
Referenced by Slic3r::_3MF_Exporter::_add_model_file_to_archive().
load()
template<class Archive > void Slic3r::Model::load (Archive & ar) inline private
{
        Internal::StaticSerializationWrapper<ModelWipeTower> wipe_tower_wrapper(wipe_tower);
        ar(materials, objects, wipe_tower_wrapper);
    }
References materials, objects, and wipe_tower.
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
load_from()
void Slic3r::Model::load_from (Model & model)
{
    set_backup_path(model.get_backup_path());
    model.backup_path.clear();
    object_backup_id_map = model.object_backup_id_map;
    next_object_backup_id = model.next_object_backup_id;
    design_info = model.design_info;
    model_info  = model.model_info;
    profile_info  = model.profile_info;
    model.design_info.reset();
    model.model_info.reset();
    model.profile_info.reset();
    model.calib_pa_pattern.reset();
}
References backup_path, calib_pa_pattern, design_info, get_backup_path(), model_info, next_object_backup_id, object_backup_id_map, profile_info, and set_backup_path().
Referenced by Slic3r::GUI::Plater::new_project().
looks_like_imperial_units()
bool Slic3r::Model::looks_like_imperial_units () const
{
    if (this->objects.size() == 0)
        return false;
    for (ModelObject* obj : this->objects)
        if (obj->get_object_stl_stats().volume < volume_threshold_inches) {
            if (!obj->is_cut())
                return true;
            bool all_cut_parts_look_like_imperial_units = true;
            for (ModelObject* obj_other : this->objects) {
                if (obj_other == obj)
                    continue;
                if (obj_other->cut_id.is_equal(obj->cut_id) && obj_other->get_object_stl_stats().volume >= volume_threshold_inches) {
                    all_cut_parts_look_like_imperial_units = false;
                    break;
                }
            }
            if (all_cut_parts_look_like_imperial_units)
                return true;
        }
    return false;
}
References objects, and Slic3r::volume_threshold_inches.
Referenced by Slic3r::GUI::Plater::priv::load_files().
looks_like_multipart_object()
bool Slic3r::Model::looks_like_multipart_object () const
{
    if (this->objects.size() <= 1)
        return false;
    double zmin = std::numeric_limits<double>::max();
    for (const ModelObject *obj : this->objects) {
        if (obj->volumes.size() > 1 || obj->config.keys().size() > 1)
            return false;
        double zmin_this = obj->get_min_z();
        if (zmin == std::numeric_limits<double>::max())
            zmin = zmin_this;
        else if (std::abs(zmin - zmin_this) > EPSILON)
            // The Object don't share zmin.
            return true;
    }
    return false;
}
References EPSILON, objects, and zmin.
Referenced by Slic3r::GUI::Plater::priv::load_files().
looks_like_saved_in_meters()
bool Slic3r::Model::looks_like_saved_in_meters () const
{
    if (this->objects.size() == 0)
        return false;
    for (ModelObject* obj : this->objects)
        if (obj->get_object_stl_stats().volume < volume_threshold_meters)
            return true;
    return false;
}
References objects, and Slic3r::volume_threshold_meters.
Referenced by Slic3r::GUI::Plater::priv::load_files().
mesh()
TriangleMesh Slic3r::Model::mesh () const
{
    TriangleMesh mesh;
    for (const ModelObject *o : this->objects)
        mesh.merge(o->mesh());
    return mesh;
}
References Slic3r::TriangleMesh::merge(), mesh(), and objects.
Referenced by add_object(), add_object(), Slic3r::GUI::GLModel::init_from_file(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::BedShapePanel::load_stl(), mesh(), Slic3r::store_obj(), and Slic3r::store_stl().
operator=() [1/2]
Model & Slic3r::Model::operator= (const Model & rhs) inline
{ this->assign_copy(rhs); assert(this->id().valid()); assert(this->id() == rhs.id()); return *this; }
References Slic3r::ObjectBase::id().
operator=() [2/2]
Model & Slic3r::Model::operator= (Model && rhs) inline
{ this->assign_copy(std::move(rhs)); assert(this->id().valid()); assert(this->id() == rhs.id()); return *this; }
print_info()
void Slic3r::Model::print_info () const inline
{ for (const ModelObject *o : this->objects) o->print_info(); }
References objects.
propose_export_file_name_and_path() [1/2]
std::string Slic3r::Model::propose_export_file_name_and_path () const
{
    std::string input_file;
    for (const ModelObject *model_object : this->objects)
        for (ModelInstance *model_instance : model_object->instances)
            if (model_instance->is_printable()) {
                input_file = model_object->get_export_filename();
                if (!input_file.empty())
                    goto end;
                // Other instances will produce the same name, skip them.
                break;
            }
end:
    return input_file;
}
References end, and objects.
Referenced by Slic3r::CLI::output_filepath(), Slic3r::PrintBase::output_filepath(), and propose_export_file_name_and_path().
propose_export_file_name_and_path() [2/2]
std::string Slic3r::Model::propose_export_file_name_and_path (const std::string & new_extension) const
{
    return boost::filesystem::path(this->propose_export_file_name_and_path()).replace_extension(new_extension).string();
}
References propose_export_file_name_and_path().
read_from_archive()
Model Slic3r::Model::read_from_archive (const std::string & input_file, DynamicPrintConfig * config, ConfigSubstitutionContext * config_substitutions, En3mfType & out_file_type, LoadStrategy options = LoadStrategy::AddDefaultInstances, PlateDataPtrs * plate_data = nullptr, std::vector< Preset * > * project_presets = nullptr, Semver * file_version = nullptr, Import3mfProgressFn proFn = nullptr, BBLProject * project = nullptr) static
{
    assert(config != nullptr);
    assert(config_substitutions != nullptr);
    Model model;
    bool result = false;
    bool is_bbl_3mf;
    if (boost::algorithm::iends_with(input_file, ".3mf")) {
        PrusaFileParser prusa_file_parser;
        if (prusa_file_parser.check_3mf_from_prusa(input_file)) {
            // for Prusa 3mf
            result = load_3mf(input_file.c_str(), *config, *config_substitutions, &model, true);
            out_file_type = En3mfType::From_Prusa;
        } else {
            // BBS: add part plate related logic
            // BBS: backup & restore
            result = load_bbs_3mf(input_file.c_str(), config, config_substitutions, &model, plate_data, project_presets, &is_bbl_3mf, file_version, proFn, options, project);
        }
    }
    else if (boost::algorithm::iends_with(input_file, ".zip.amf"))
        result = load_amf(input_file.c_str(), config, config_substitutions, &model, &is_bbl_3mf);
    else
        throw Slic3r::RuntimeError(_L("Unknown file format. Input file must have .3mf or .zip.amf extension."));
    if (out_file_type != En3mfType::From_Prusa) {
        out_file_type = is_bbl_3mf ? En3mfType::From_BBS : En3mfType::From_Other;
    }
    if (!result)
        throw Slic3r::RuntimeError(_L("Loading of a model file failed."));
    for (ModelObject *o : model.objects) {
//        if (boost::algorithm::iends_with(input_file, ".zip.amf"))
//        {
//            // we remove the .zip part of the extension to avoid it be added to filenames when exporting
//            o->input_file = boost::ireplace_last_copy(input_file, ".zip.", ".");
//        }
//        else
            o->input_file = input_file;
    }
    bool cb_cancel;
    if (options & LoadStrategy::AddDefaultInstances) {
        model.add_default_instances();
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" <<__LINE__ << boost::format("import 3mf IMPORT_STAGE_ADD_INSTANCE\n");
        if (proFn) {
            proFn(IMPORT_STAGE_ADD_INSTANCE, 0, 1, cb_cancel);
            if (cb_cancel)
                throw Slic3r::RuntimeError(_L("Canceled"));
        }
    }
    //BBS
    //CustomGCode::update_custom_gcode_per_print_z_from_config(model.custom_gcode_per_print_z, config);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format("import 3mf IMPORT_STAGE_UPDATE_GCODE\n");
    if (proFn) {
        proFn(IMPORT_STAGE_UPDATE_GCODE, 0, 1, cb_cancel);
        if (cb_cancel)
            throw Slic3r::RuntimeError(_L("Canceled"));
    }
    //BBS
    for (auto& plate_gcodes : model.plates_custom_gcodes)
        CustomGCode::check_mode_for_custom_gcode_per_print_z(plate_gcodes.second);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << ":" << __LINE__ << boost::format("import 3mf IMPORT_STAGE_CHECK_MODE_GCODE\n");
    if (proFn) {
        proFn(IMPORT_STAGE_CHECK_MODE_GCODE, 0, 1, cb_cancel);
        if (cb_cancel)
            throw Slic3r::RuntimeError(_L("Canceled"));
    }
    handle_legacy_sla(*config);
    return model;
}
References _L, add_default_instances(), Slic3r::AddDefaultInstances, Slic3r::PrusaFileParser::check_3mf_from_prusa(), Slic3r::CustomGCode::check_mode_for_custom_gcode_per_print_z(), Slic3r::From_BBS, Slic3r::From_Other, Slic3r::From_Prusa, Slic3r::handle_legacy_sla(), Slic3r::IMPORT_STAGE_ADD_INSTANCE, Slic3r::IMPORT_STAGE_CHECK_MODE_GCODE, Slic3r::IMPORT_STAGE_UPDATE_GCODE, Slic3r::load_3mf(), Slic3r::load_amf(), Slic3r::load_bbs_3mf(), objects, and plates_custom_gcodes.
Referenced by Slic3r::GUI::Plater::priv::load_files().
read_from_file()
Model Slic3r::Model::read_from_file (const std::string & input_file, DynamicPrintConfig * config = nullptr, ConfigSubstitutionContext * config_substitutions = nullptr, LoadStrategy options = LoadStrategy::AddDefaultInstances, PlateDataPtrs * plate_data = nullptr, std::vector< Preset * > * project_presets = nullptr, bool * is_xxx = nullptr, Semver * file_version = nullptr, Import3mfProgressFn proFn = nullptr, ImportstlProgressFn stlFn = nullptr, ImportStepProgressFn stepFn = nullptr, StepIsUtf8Fn stepIsUtf8Fn = nullptr, BBLProject * project = nullptr, int plate_id = 0) static
{
    Model model;
    DynamicPrintConfig temp_config;
    ConfigSubstitutionContext temp_config_substitutions_context(ForwardCompatibilitySubstitutionRule::EnableSilent);
    if (config == nullptr)
        config = &temp_config;
    if (config_substitutions == nullptr)
        config_substitutions = &temp_config_substitutions_context;
    //BBS: plate_data
    PlateDataPtrs temp_plate_data;
    bool temp_is_xxx;
    Semver temp_version;
    if (plate_data == nullptr)
        plate_data = &temp_plate_data;
    if (is_xxx == nullptr)
        is_xxx = &temp_is_xxx;
    if (file_version == nullptr)
        file_version = &temp_version;
    bool result = false;
    bool is_cb_cancel = false;
    std::string message;
    if (boost::algorithm::iends_with(input_file, ".stp") ||
        boost::algorithm::iends_with(input_file, ".step"))
        result = load_step(input_file.c_str(), &model, is_cb_cancel, stepFn, stepIsUtf8Fn);
    else if (boost::algorithm::iends_with(input_file, ".stl"))
        result = load_stl(input_file.c_str(), &model, nullptr, stlFn);
    else if (boost::algorithm::iends_with(input_file, ".obj"))
        result = load_obj(input_file.c_str(), &model, message);
    else if (boost::algorithm::iends_with(input_file, ".svg"))
        result = load_svg(input_file.c_str(), &model, message);
    //BBS: remove the old .amf.xml files
    //else if (boost::algorithm::iends_with(input_file, ".amf") || boost::algorithm::iends_with(input_file, ".amf.xml"))
    else if (boost::algorithm::iends_with(input_file, ".amf"))
        //BBS: is_xxx is used for is_inches when load amf
        result = load_amf(input_file.c_str(), config, config_substitutions, &model, is_xxx);
    else if (boost::algorithm::iends_with(input_file, ".3mf"))
        //BBS: add part plate related logic
        // BBS: backup & restore
        //FIXME options & LoadStrategy::CheckVersion ?
        //BBS: is_xxx is used for is_bbs_3mf when load 3mf
        result = load_bbs_3mf(input_file.c_str(), config, config_substitutions, &model, plate_data, project_presets, is_xxx, file_version, proFn, options, project, plate_id);
    else
        throw Slic3r::RuntimeError(_L("Unknown file format. Input file must have .stl, .obj, .amf(.xml) extension."));
    if (is_cb_cancel) {
        Model empty_model;
        return empty_model;
    }
    if (!result) {
        if (message.empty())
            throw Slic3r::RuntimeError(_L("Loading of a model file failed."));
        else
            throw Slic3r::RuntimeError(message);
    }
    if (model.objects.empty())
        throw Slic3r::RuntimeError(_L("The supplied file couldn't be read because it's empty"));
    for (ModelObject *o : model.objects)
        o->input_file = input_file;
    if (options & LoadStrategy::AddDefaultInstances)
        model.add_default_instances();
    //BBS
    //CustomGCode::update_custom_gcode_per_print_z_from_config(model.custom_gcode_per_print_z, config);
    //BBS
    for (auto& plate_gcodes : model.plates_custom_gcodes)
        CustomGCode::check_mode_for_custom_gcode_per_print_z(plate_gcodes.second);
    sort_remove_duplicates(config_substitutions->substitutions);
    return model;
}
References _L, add_default_instances(), Slic3r::AddDefaultInstances, Slic3r::CustomGCode::check_mode_for_custom_gcode_per_print_z(), Slic3r::EnableSilent, Slic3r::load_amf(), Slic3r::load_bbs_3mf(), Slic3r::load_obj(), Slic3r::load_step(), Slic3r::load_stl(), Slic3r::load_svg(), objects, plates_custom_gcodes, Slic3r::sort_remove_duplicates(), and Slic3r::ConfigSubstitutionContext::substitutions.
Referenced by Slic3r::GUI::GLModel::init_from_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::BedShapePanel::load_stl(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), and Slic3r::CLI::run().
remove_backup_path_if_exist()
void Slic3r::Model::remove_backup_path_if_exist ()
{
    if (!backup_path.empty()) {
        boost::filesystem::path temp_path(backup_path);
        if (boost::filesystem::exists(temp_path))
        {
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("model %1%, id %2% remove backup_path %3%")%this%this->id().id%backup_path;
            boost::filesystem::remove_all(temp_path);
        }
  backup_path.clear();
    }
}
References backup_path, Slic3r::ObjectID::id, and Slic3r::ObjectBase::id().
removed_objects_with_zero_volume()
int Slic3r::Model::removed_objects_with_zero_volume ()
{
    if (objects.size() == 0)
        return 0;
    int removed = 0;
    for (int i = int(objects.size()) - 1; i >= 0; i--)
        if (objects[i]->get_object_stl_stats().volume < zero_volume) {
            delete_object(size_t(i));
            removed++;
        }
    return removed;
}
References delete_object(), objects, and Slic3r::zero_volume.
Referenced by Slic3r::GUI::Plater::priv::load_files().
save()
template<class Archive > void Slic3r::Model::save (Archive & ar) const inline private
{
        Internal::StaticSerializationWrapper<ModelWipeTower const> wipe_tower_wrapper(wipe_tower);
        ar(materials, objects, wipe_tower_wrapper);
    }
References materials, objects, and wipe_tower.
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_backup_path()
void Slic3r::Model::set_backup_path (const std::string & path)
{
    if (backup_path == path)
        return;
    if ("detach" == path) {
        backup_path.clear();
        return;
    }
    if (!backup_path.empty()) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(", model %1%, id %2%, remove previous backup %3%")%this%this->id().id%backup_path;
        Slic3r::remove_backup(*this, true);
    }
    backup_path = path;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(", model %1%, id %2%, set backup to %3%")%this%this->id().id%backup_path;
}
References backup_path, Slic3r::ObjectID::id, Slic3r::ObjectBase::id(), and Slic3r::remove_backup().
Referenced by Slic3r::GUI::Plater::close_with_confirm(), load_from(), Slic3r::_BBS_3MF_Importer::load_model_from_file(), and Slic3r::CLI::run().
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_need_backup()
void Slic3r::Model::set_need_backup ()
{
    need_backup = true;
}
References need_backup.
set_new_unique_id()
void Slic3r::ObjectBase::set_new_unique_id () inline protected inherited
{ m_id = generate_new_id(); }
References Slic3r::ObjectBase::generate_new_id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::ModelVolume::ModelVolume(), assign_new_unique_ids_recursive(), Slic3r::ObjectBase::assign_new_unique_ids_recursive(), Slic3r::ModelObject::assign_new_unique_ids_recursive(), Slic3r::ModelVolume::assign_new_unique_ids_recursive(), Slic3r::CutObjectBase::init(), Slic3r::ModelMaterial::set_new_unique_id(), Slic3r::ModelObject::set_new_unique_id(), and Slic3r::ModelVolume::set_new_unique_id().
set_object_backup_id()
void Slic3r::Model::set_object_backup_id (ModelObject const & object, int uuid)
{
    object_backup_id_map[object.id().id] = uuid;
    if (uuid >= next_object_backup_id) next_object_backup_id = uuid + 1;
}
References next_object_backup_id, and object_backup_id_map.
Referenced by Slic3r::_BBS_3MF_Importer::_create_object_instance().
SetDesigner()
void Slic3r::Model::SetDesigner (std::string designer, std::string designer_user_id) inline
{
        if (design_info == nullptr) {
            design_info = std::make_shared<ModelDesignInfo>();
        }
        design_info->Designer = designer;
        //BBS tips: clean design user id when set designer
        design_info->DesignerUserId = designer_user_id;
    }
References design_info.
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
translate()
void Slic3r::Model::translate (coordf_t x, coordf_t y, coordf_t z) inline
{ for (ModelObject *o : this->objects) o->translate(x, y, z); }
References objects.
update_links_bottom_up_recursive()
void Slic3r::Model::update_links_bottom_up_recursive () private
{
  for (std::pair<const t_model_material_id, ModelMaterial*> &kvp : this->materials)
    kvp.second->set_model(this);
  for (ModelObject *model_object : this->objects) {
    model_object->set_model(this);
    for (ModelInstance *model_instance : model_object->instances)
      model_instance->set_model_object(model_object);
    for (ModelVolume *model_volume : model_object->volumes)
      model_volume->set_model_object(model_object);
  }
}
References materials, and objects.
Referenced by Slic3r::UndoRedo::StackImpl::load_snapshot().
update_print_volume_state()
unsigned int Slic3r::Model::update_print_volume_state (const BuildVolume & build_volume)
{
    unsigned int num_printable = 0;
    for (ModelObject* model_object : this->objects)
        num_printable += model_object->update_instances_print_volume_state(build_volume);
    //BBS: add logs for build_volume
    const BoundingBoxf3& print_volume = build_volume.bounding_volume();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", print_volume {%1%, %2%, %3%} to {%4%, %5%, %6%}, got %7% printable istances")\
        %print_volume.min.x() %print_volume.min.y() %print_volume.min.z()%print_volume.max.x() %print_volume.max.y() %print_volume.max.z() %num_printable;
    return num_printable;
}
References Slic3r::BuildVolume::bounding_volume(), Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, and objects.
Referenced by Slic3r::GUI::PartPlateList::load_gcode_files(), and Slic3r::CLI::run().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
UndoRedo::StackImpl
friend class UndoRedo::StackImpl friend
Member Data Documentation
backup_path
std::string Slic3r::Model::backup_path private
Referenced by ~Model(), get_backup_path(), load_from(), remove_backup_path_if_exist(), and set_backup_path().
calib_pa_pattern
std::unique_ptr<CalibPressureAdvancePattern> Slic3r::Model::calib_pa_pattern
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), load_from(), Slic3r::GUI::Plater::priv::reset(), and Slic3r::GUI::Plater::reslice().
curr_plate_index
int Slic3r::Model::curr_plate_index { 0 }
Referenced by Slic3r::Print::apply(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), get_curr_plate_custom_gcodes(), and Slic3r::GUI::PartPlateList::select_plate().
design_info
std::shared_ptr<ModelDesignInfo> Slic3r::Model::design_info = nullptr
Referenced by Slic3r::_BBS_3MF_Exporter::_add_model_file_to_archive(), Slic3r::GUI::Plater::priv::load_files(), load_from(), Slic3r::_BBS_3MF_Importer::load_gcode_3mf_from_stream(), Slic3r::GUI::ProjectPanel::on_reload(), and SetDesigner().
extruderParamsMap
std::map< size_t, ExtruderParams > Slic3r::Model::extruderParamsMap = { {0,{"",0,0}}} static
Referenced by Slic3r::getadhesionCoeff(), Slic3r::getTemperatureFromExtruder(), getThermalLength(), Slic3r::GUI::Plater::priv::on_action_slice_all(), Slic3r::GUI::Plater::priv::on_action_slice_plate(), Slic3r::GUI::ArrangeJob::prepare(), and Slic3r::GUI::Plater::priv::select_view_3D().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
materials
ModelMaterialMap Slic3r::Model::materials
Referenced by add_material(), add_material(), assign_new_unique_ids_recursive(), Slic3r::check_model_ids_equal(), Slic3r::check_model_ids_validity(), clear_materials(), delete_material(), load(), save(), and update_links_bottom_up_recursive().
model_info
std::shared_ptr<ModelInfo> Slic3r::Model::model_info = nullptr
Referenced by Slic3r::_BBS_3MF_Exporter::_add_model_file_to_archive(), Slic3r::GUI::Plater::priv::load_files(), load_from(), Slic3r::_BBS_3MF_Importer::load_gcode_3mf_from_stream(), Slic3r::GUI::ProjectPanel::on_reload(), Slic3r::_BBS_3MF_Exporter::save_model_to_file(), and Slic3r::GUI::ProjectPanel::update_model_data().
need_backup
bool Slic3r::Model::need_backup = false private
Referenced by add_object(), is_need_backup(), and set_need_backup().
next_object_backup_id
int Slic3r::Model::next_object_backup_id = 1 private
Referenced by clear_objects(), get_object_backup_id(), load_from(), and set_object_backup_id().
object_backup_id_map
std::map<int, int> Slic3r::Model::object_backup_id_map private
Referenced by add_object(), clear_objects(), get_object_backup_id(), get_object_backup_id(), load_from(), and set_object_backup_id().
objects
ModelObjectPtrs Slic3r::Model::objects
Referenced by Slic3r::_BBS_3MF_Exporter::_add_cut_information_file_to_archive(), Slic3r::_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_layer_config_ranges_file_to_archive(), Slic3r::_3MF_Exporter::_add_layer_height_profile_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_layer_height_profile_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_3MF_Exporter::_add_model_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_model_file_to_archive(), Slic3r::_3MF_Exporter::_add_sla_drain_holes_file_to_archive(), Slic3r::_3MF_Exporter::_add_sla_support_points_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::_calib_pa_tower(), Slic3r::_3MF_Importer::_create_object_instance(), Slic3r::_BBS_3MF_Importer::_create_object_instance(), Slic3r::_3MF_Importer::_handle_end_model(), Slic3r::_BBS_3MF_Importer::_handle_end_model(), Slic3r::_BBS_3MF_Importer::_handle_start_assemble_item(), Slic3r::_3MF_Importer::_handle_start_object(), Slic3r::_3MF_Importer::_load_model_from_file(), Slic3r::CalibPressureAdvancePattern::_refresh_starting_point(), Slic3r::CalibPressureAdvancePattern::_refresh_writer(), Slic3r::GUI::Plater::priv::actualize_object_warnings(), Slic3r::GUI::Selection::add_curr_plate(), add_default_instances(), Slic3r::GUI::PartPlate::add_instance(), add_object(), add_object(), add_object(), add_object(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), adjust_min_z(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), assign_new_unique_ids_recursive(), bounding_box(), Slic3r::GUI::Plater::calib_flowrate(), Slic3r::GUI::Plater::calib_max_vol_speed(), Slic3r::GUI::Plater::calib_retraction(), Slic3r::GUI::Plater::calib_temp(), Slic3r::GUI::Plater::calib_VFA(), Slic3r::GUI::Plater::priv::can_arrange(), Slic3r::GUI::Plater::priv::can_decrease_instances(), Slic3r::GUI::Plater::priv::can_delete_all(), Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::Plater::priv::can_fix_through_netfabb(), Slic3r::GUI::Plater::priv::can_increase_instances(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::Plater::priv::can_set_instance_to_object(), center_instances_around_point(), Slic3r::GUI::Plater::changed_mesh(), Slic3r::GUI::Plater::changed_objects(), Slic3r::check_model_ids_equal(), Slic3r::check_model_ids_validity(), Slic3r::GUI::PartPlate::check_outside(), Slic3r::GLVolumeCollection::check_outside_state(), Slic3r::GUI::Plater::clear_before_change_mesh(), Slic3r::GUI::ArrangeJob::clear_input(), Slic3r::GUI::OrientJob::clear_input(), clear_objects(), collect_reusable_objects(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::PartPlateList::construct_objects_list_for_new_plate(), Slic3r::GUI::PartPlate::contain_instance_totally(), convert_from_imperial_units(), convert_from_meters(), Slic3r::_BBS_3MF_Exporter::convert_instance_id_to_resource_id(), convert_multipart_object(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::GUI::Plater::cut(), delete_object(), delete_object(), delete_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::GLGizmoText::delete_temp_preview_text_volume(), Slic3r::GUI::GLCanvas3D::do_mirror(), Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::duplicate(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::duplicate_objects(), duplicate_objects_grid(), Slic3r::AMFParserContext::endDocument(), Slic3r::AMFParserContext::endElement(), Slic3r::GUI::Selection::erase(), Slic3r::GUI::PartPlate::estimate_wipe_tower_size(), Slic3r::GUI::Plater::priv::export_gcode(), Slic3r::GUI::Plater::priv::export_gcode(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::get_arrange_poly(), Slic3r::get_arrange_polys(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::GUI::Plater::priv::get_export_file_path(), Slic3r::GUI::Plater::priv::get_export_gcode_filename(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::GUI::PartPlate::get_extruders_without_support(), Slic3r::GUI::PartPlate::get_instance(), Slic3r::GUI::get_model_volume(), Slic3r::GUI::Selection::Clipboard::get_object(), Slic3r::GUI::PartPlate::get_objects(), Slic3r::GUI::Selection::Clipboard::get_objects(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::Plater::priv::get_selected_volume_idx(), Slic3r::GUI::GLGizmoText::get_text_mesh(), Slic3r::GUI::PartPlate::get_used_extruders(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::Plater::priv::has_assemble_view(), Slic3r::GUI::PartPlate::has_printable_instances(), Slic3r::GUI::PartPlate::intersect_instance(), Slic3r::GUI::PartPlate::is_all_instances_unprintable(), Slic3r::GUI::Selection::Clipboard::is_empty(), is_fdm_support_painted(), Slic3r::GUI::Selection::is_from_fully_selected_instance(), Slic3r::GUI::PartPlate::is_left_top_of(), is_mm_painted(), is_seam_painted(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::Clipboard::is_sla_compliant(), Slic3r::GUI::Plater::priv::layers_height_allowed(), load(), Slic3r::load_amf_archive(), Slic3r::load_amf_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::GLCanvas3D::load_object(), Slic3r::load_svg(), looks_like_imperial_units(), looks_like_multipart_object(), looks_like_saved_in_meters(), Slic3r::GUI::Plater::merge(), mesh(), Slic3r::model_has_advanced_features(), Slic3r::model_has_multi_part_objects(), Slic3r::model_object_list_equal(), Slic3r::model_object_list_extended(), Slic3r::GUI::PartPlateList::notify_instance_removed(), Slic3r::GUI::PartPlateList::notify_instance_update(), Slic3r::GUI::Selection::notify_instance_update(), Slic3r::GUI::Plater::priv::object_list_changed(), Slic3r::GUI::Plater::priv::on_process_completed(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::on_update(), Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), Slic3r::GUI::ObjectGridTable::OnCellValueChanged(), Slic3r::GUI::ObjectGridTable::OnSelectCell(), Slic3r::GUI::Selection::paste_objects_from_clipboard(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), print_info(), Slic3r::GUI::PartPlate::printable_instance_size(), Slic3r::GUI::RotoptimizeJob::process(), propose_export_file_name_and_path(), read_from_archive(), read_from_file(), Slic3r::GUI::PartPlateList::rebuild_plates_after_arrangement(), Slic3r::CalibPressureAdvancePattern::refresh_setup(), Slic3r::GUI::Plater::priv::reload_all_from_disk(), Slic3r::GUI::PartPlateList::reload_all_objects(), Slic3r::GUI::ObjectGridTable::reload_cell_data(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::GUI::Selection::remove_curr_plate(), removed_objects_with_zero_volume(), Slic3r::GUI::GLCanvas3D::Labels::render(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::ObjectGridTable::resetValuesInCurrentCell(), Slic3r::GUI::Plater::reslice(), Slic3r::GUI::Selection::rotate(), Slic3r::CLI::run(), save(), Slic3r::GUI::Selection::scale(), Slic3r::GUI::Plater::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::Print::sequential_print_clearance_valid(), Slic3r::GUI::Plater::priv::set_current_panel(), Slic3r::GUI::PartPlate::set_pos_and_size(), Slic3r::GUI::Selection::set_printable(), Slic3r::GUI::Plater::show_object_info(), Slic3r::sort_object_instances_by_model_order(), Slic3r::GUI::Plater::priv::split_object(), Slic3r::AMFParserContext::startElement(), Slic3r::ModelObject::synchronize_model_after_cut(), Slic3r::GUI::GLCanvas3D::toggle_model_objects_visibility(), Slic3r::GUI::GLCanvas3D::toggle_sla_auxiliaries_visibility(), translate(), Slic3r::GUI::PartPlate::translate_all_instance(), Slic3r::GLVolume::SinkingContours::update(), Slic3r::GUI::GLCanvas3D::update_instance_printable_state_for_object(), update_links_bottom_up_recursive(), Slic3r::PrintBase::update_object_placeholders(), update_print_volume_state(), Slic3r::GUI::GLCanvas3D::update_sequential_clearance(), Slic3r::GUI::GLGizmoText::update_text_positions(), Slic3r::GUI::Selection::update_type(), Slic3r::GUI::ObjectGridTable::update_value_to_object(), Slic3r::GUI::PartPlate::valid_instance(), and Slic3r::GUI::verify_instances_rotation_synchronized().
plates_custom_gcodes
std::map<int, CustomGCode::Info> Slic3r::Model::plates_custom_gcodes
Referenced by Slic3r::_BBS_3MF_Exporter::_add_custom_gcode_per_print_z_file_to_archive(), Slic3r::_BBS_3MF_Importer::_extract_custom_gcode_per_print_z_from_archive(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::Print::extruders(), Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), get_curr_plate_custom_gcodes(), Slic3r::GUI::PartPlate::get_extruders(), Slic3r::GUI::PartPlate::get_extruders_under_cli(), Slic3r::GUI::PartPlate::get_extruders_without_support(), Slic3r::GUI::Plater::priv::load_files(), read_from_archive(), read_from_file(), and Slic3r::GUI::Plater::priv::reset().
printSpeedMap
GlobalSpeedMap Slic3r::Model::printSpeedMap {} static
Referenced by findMaxSpeed(), getBedPolygon(), Slic3r::GUI::Plater::priv::on_action_slice_all(), Slic3r::GUI::Plater::priv::on_action_slice_plate(), Slic3r::GUI::ArrangeJob::prepare(), and Slic3r::GUI::Plater::priv::select_view_3D().
profile_info
std::shared_ptr<ModelProfileInfo> Slic3r::Model::profile_info = nullptr
Referenced by load_from(), Slic3r::_BBS_3MF_Importer::load_gcode_3mf_from_stream(), and Slic3r::GUI::ProjectPanel::on_reload().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
wipe_tower
ModelWipeTower Slic3r::Model::wipe_tower
Referenced by load(), save(), Slic3r::GUI::Plater::priv::take_snapshot(), and Slic3r::GUI::Plater::priv::undo_redo_to().
The documentation for this class was generated from the following files:
src/libslic3r/Model.hpp
src/libslic3r/Model.cpp