OrcaSlicer: Slic3r::client::macro_processor< Iterator > Struct Template Reference
Slic3r::client::macro_processor< Iterator > Struct Template Reference
Public Types
typedef qi::rule< Iterator, expr< Iterator >(const MyContext *), spirit_encoding::space_type > RuleExpression
Public Member Functions
macro_processor ()
Public Attributes
qi::rule< Iterator, std::string(const MyContext *), qi::locals< bool >, spirit_encoding::space_type > start
qi::rule< Iterator, std::string(), spirit_encoding::space_type > text
qi::rule< Iterator, std::string(const MyContext *), spirit_encoding::space_type > text_block
qi::rule< Iterator, std::string(const MyContext *), spirit_encoding::space_type > macro
qi::rule< Iterator, std::string(const MyContext *), spirit_encoding::space_type > legacy_variable_expansion
qi::rule< Iterator, boost::iterator_range< Iterator >(), spirit_encoding::space_type > identifier
RuleExpression conditional_expression
RuleExpression logical_or_expression
RuleExpression logical_and_expression
RuleExpression relational_expression
RuleExpression additive_expression
RuleExpression equality_expression
RuleExpression multiplicative_expression
RuleExpression unary_expression
RuleExpression optional_parameter
qi::rule< Iterator, boost::iterator_range< Iterator >(), spirit_encoding::space_type > regular_expression
qi::rule< Iterator, bool(const MyContext *), spirit_encoding::space_type > bool_expr_eval
qi::rule< Iterator, expr< Iterator >(const MyContext *), qi::locals< OptWithPos< Iterator >, int >, spirit_encoding::space_type > scalar_variable_reference
qi::rule< Iterator, OptWithPos< Iterator >(const MyContext *), spirit_encoding::space_type > variable_reference
qi::rule< Iterator, std::string(const MyContext *), qi::locals< bool, bool >, spirit_encoding::space_type > if_else_output
qi::symbols< char > keywords
Detailed Description
template<typename Iterator>
struct Slic3r::client::macro_processor< Iterator >
Member Typedef Documentation
RuleExpression
template<typename Iterator > typedef qi::rule<Iterator, expr<Iterator>(const MyContext*), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::RuleExpression
Constructor & Destructor Documentation
macro_processor()
template<typename Iterator > Slic3r::client::macro_processor< Iterator >::macro_processor () inline
                          : macro_processor::base_type(start)
        {
            using namespace qi::labels;
            qi::alpha_type              alpha;
            qi::alnum_type              alnum;
            qi::eps_type                eps;
            qi::raw_type                raw;
            qi::lit_type                lit;
            qi::lexeme_type             lexeme;
            qi::no_skip_type            no_skip;
            qi::real_parser<double, strict_real_policies_without_nan_inf> strict_double;
            spirit_encoding::char_type  char_;
            utf8_char_skipper_parser    utf8char;
            spirit::bool_type           bool_;
            spirit::int_type            int_;
            spirit::double_type         double_;
            spirit_encoding::string_type string;
      spirit::eoi_type      eoi;
      spirit::repository::qi::iter_pos_type iter_pos;
            auto                        kw = spirit::repository::qi::distinct(qi::copy(alnum | '_'));
            qi::_val_type               _val;
            qi::_1_type                 _1;
            qi::_2_type                 _2;
            qi::_3_type                 _3;
            qi::_4_type                 _4;
            qi::_a_type                 _a;
            qi::_b_type                 _b;
            qi::_r1_type                _r1;
            // Starting symbol of the grammer.
            // The leading eps is required by the "expectation point" operator ">".
            // Without it, some of the errors would not trigger the error handler.
            // Also the start symbol switches between the "full macro syntax" and a "boolean expression only",
            // depending on the context->just_boolean_expression flag. This way a single static expression parser
            // could serve both purposes.
            start = eps[px::bind(&MyContext::evaluate_full_macro, _r1, _a)] >
                (       (eps(_a==true) > text_block(_r1) [_val=_1])
                    |   conditional_expression(_r1) [ px::bind(&expr<Iterator>::evaluate_boolean_to_string, _1, _val) ]
        ) > eoi;
            start.name("start");
            qi::on_error<qi::fail>(start, px::bind(&MyContext::process_error_message<Iterator>, _r1, _4, _1, _2, _3));
            text_block = *(
                        text [_val+=_1]
                        // Allow back tracking after '{' in case of a text_block embedded inside a condition.
                        // In that case the inner-most {else} wins and the {if}/{elsif}/{else} shall be paired.
                        // {elsif}/{else} without an {if} will be allowed to back track from the embedded text_block.
                    |   (lit('{') >> macro(_r1) [_val+=_1] > '}')
                    |   (lit('[') > legacy_variable_expansion(_r1) [_val+=_1] > ']')
                );
            text_block.name("text_block");
            // Free-form text up to a first brace, including spaces and newlines.
            // The free-form text will be inserted into the processed text without a modification.
            text = no_skip[raw[+(utf8char - char_('[') - char_('{'))]];
            text.name("text");
            // New style of macro expansion.
            // The macro expansion may contain numeric or string expressions, ifs and cases.
            macro =
                    (kw["if"]     > if_else_output(_r1) [_val = _1])
//                |   (kw["switch"] > switch_output(_r1)  [_val = _1])
                |   additive_expression(_r1) [ px::bind(&expr<Iterator>::to_string2, _1, _val) ];
            macro.name("macro");
            // An if expression enclosed in {} (the outmost {} are already parsed by the caller).
            if_else_output =
                eps[_b=true] >
                bool_expr_eval(_r1)[_a=_1] > '}' >
                    text_block(_r1)[px::bind(&expr<Iterator>::set_if, _a, _b, _1, _val)] > '{' >
                *(kw["elsif"] > bool_expr_eval(_r1)[_a=_1] > '}' >
                    text_block(_r1)[px::bind(&expr<Iterator>::set_if, _a, _b, _1, _val)] > '{') >
                -(kw["else"] > lit('}') >
                    text_block(_r1)[px::bind(&expr<Iterator>::set_if, _b, _b, _1, _val)] > '{') >
                kw["endif"];
            if_else_output.name("if_else_output");
            // A switch expression enclosed in {} (the outmost {} are already parsed by the caller).
/*
            switch_output =
                eps[_b=true] >
                omit[expr(_r1)[_a=_1]] > '}' > text_block(_r1)[px::bind(&expr<Iterator>::set_if_equal, _a, _b, _1, _val)] > '{' >
                *("elsif" > omit[bool_expr_eval(_r1)[_a=_1]] > '}' > text_block(_r1)[px::bind(&expr<Iterator>::set_if, _a, _b, _1, _val)]) >>
                -("else" > '}' >> text_block(_r1)[px::bind(&expr<Iterator>::set_if, _b, _b, _1, _val)]) >
                "endif";
*/
            // Legacy variable expansion of the original Slic3r, in the form of [scalar_variable] or [vector_variable_index].
            legacy_variable_expansion =
                    (identifier >> &lit(']'))
                        [ px::bind(&MyContext::legacy_variable_expansion<Iterator>, _r1, _1, _val) ]
                |   (identifier > lit('[') > identifier > ']')
                        [ px::bind(&MyContext::legacy_variable_expansion2<Iterator>, _r1, _1, _2, _val) ]
                ;
            legacy_variable_expansion.name("legacy_variable_expansion");
            identifier =
                ! kw[keywords] >>
                raw[lexeme[(alpha | '_') >> *(alnum | '_')]];
            identifier.name("identifier");
            conditional_expression =
                logical_or_expression(_r1)                [_val = _1]
                >> -('?' > conditional_expression(_r1) > ':' > conditional_expression(_r1)) [px::bind(&expr<Iterator>::ternary_op, _val, _1, _2)];
            conditional_expression.name("conditional_expression");
            logical_or_expression =
                logical_and_expression(_r1)                [_val = _1]
                >> *(   ((kw["or"] | "||") > logical_and_expression(_r1) ) [px::bind(&expr<Iterator>::logical_or, _val, _1)] );
            logical_or_expression.name("logical_or_expression");
            logical_and_expression =
                equality_expression(_r1)                   [_val = _1]
                >> *(   ((kw["and"] | "&&") > equality_expression(_r1) ) [px::bind(&expr<Iterator>::logical_and, _val, _1)] );
            logical_and_expression.name("logical_and_expression");
            equality_expression =
                relational_expression(_r1)                   [_val = _1]
                >> *(   ("==" > relational_expression(_r1) ) [px::bind(&expr<Iterator>::equal,     _val, _1)]
                    |   ("!=" > relational_expression(_r1) ) [px::bind(&expr<Iterator>::not_equal, _val, _1)]
                    |   ("<>" > relational_expression(_r1) ) [px::bind(&expr<Iterator>::not_equal, _val, _1)]
                    |   ("=~" > regular_expression         ) [px::bind(&expr<Iterator>::regex_matches, _val, _1)]
                    |   ("!~" > regular_expression         ) [px::bind(&expr<Iterator>::regex_doesnt_match, _val, _1)]
                    );
            equality_expression.name("bool expression");
            // Evaluate a boolean expression stored as expr into a boolean value.
            // Throw if the equality_expression does not produce a expr of boolean type.
            bool_expr_eval = conditional_expression(_r1) [ px::bind(&expr<Iterator>::evaluate_boolean, _1, _val) ];
            bool_expr_eval.name("bool_expr_eval");
            relational_expression =
                    additive_expression(_r1)                [_val  = _1]
                >> *(   ("<="     > additive_expression(_r1) ) [px::bind(&expr<Iterator>::leq,     _val, _1)]
                    |   (">="     > additive_expression(_r1) ) [px::bind(&expr<Iterator>::geq,     _val, _1)]
                    |   (lit('<') > additive_expression(_r1) ) [px::bind(&expr<Iterator>::lower,   _val, _1)]
                    |   (lit('>') > additive_expression(_r1) ) [px::bind(&expr<Iterator>::greater, _val, _1)]
                    );
            relational_expression.name("relational_expression");
            additive_expression =
                multiplicative_expression(_r1)                       [_val  = _1]
                >> *(   (lit('+') > multiplicative_expression(_r1) ) [_val += _1]
                    |   (lit('-') > multiplicative_expression(_r1) ) [_val -= _1]
                    );
            additive_expression.name("additive_expression");
            multiplicative_expression =
                unary_expression(_r1)                       [_val  = _1]
                >> *(   (lit('*') > unary_expression(_r1) ) [_val *= _1]
                    |   (lit('/') > unary_expression(_r1) ) [_val /= _1]
                    |   (lit('%') > unary_expression(_r1) ) [_val %= _1]
                    );
            multiplicative_expression.name("multiplicative_expression");
            struct FactorActions {
                static void set_start_pos(Iterator &start_pos, expr<Iterator> &out)
                        { out.it_range = boost::iterator_range<Iterator>(start_pos, start_pos); }
                static void int_(int &value, Iterator &end_pos, expr<Iterator> &out)
                        { out = expr<Iterator>(value, out.it_range.begin(), end_pos); }
                static void double_(double &value, Iterator &end_pos, expr<Iterator> &out)
                        { out = expr<Iterator>(value, out.it_range.begin(), end_pos); }
                static void bool_(bool &value, Iterator &end_pos, expr<Iterator> &out)
                        { out = expr<Iterator>(value, out.it_range.begin(), end_pos); }
                static void string_(boost::iterator_range<Iterator> &it_range, expr<Iterator> &out)
                        { out = expr<Iterator>(std::string(it_range.begin() + 1, it_range.end() - 1), it_range.begin(), it_range.end()); }
                static void expr_(expr<Iterator> &value, Iterator &end_pos, expr<Iterator> &out)
                        { auto begin_pos = out.it_range.begin(); out = expr<Iterator>(std::move(value), begin_pos, end_pos); }
                static void minus_(expr<Iterator> &value, expr<Iterator> &out)
                        { out = value.unary_minus(out.it_range.begin()); }
                static void not_(expr<Iterator> &value, expr<Iterator> &out)
                        { out = value.unary_not(out.it_range.begin()); }
                static void to_int(expr<Iterator> &value, expr<Iterator> &out)
                        { out = value.unary_integer(out.it_range.begin()); }
                static void round(expr<Iterator> &value, expr<Iterator> &out)
                        { out = value.round(out.it_range.begin()); }
                // For indicating "no optional parameter".
                static void noexpr(expr<Iterator> &out) { out.reset(); }
            };
            unary_expression = iter_pos[px::bind(&FactorActions::set_start_pos, _1, _val)] >> (
                    scalar_variable_reference(_r1)                  [ _val = _1 ]
                |   (lit('(')  > conditional_expression(_r1) > ')' > iter_pos) [ px::bind(&FactorActions::expr_, _1, _2, _val) ]
                |   (lit('-')  > unary_expression(_r1)           )  [ px::bind(&FactorActions::minus_,  _1,     _val) ]
                |   (lit('+')  > unary_expression(_r1) > iter_pos)  [ px::bind(&FactorActions::expr_,   _1, _2, _val) ]
                |   ((kw["not"] | '!') > unary_expression(_r1) > iter_pos) [ px::bind(&FactorActions::not_, _1, _val) ]
                |   (kw["min"] > '(' > conditional_expression(_r1) [_val = _1] > ',' > conditional_expression(_r1) > ')')
                                                                    [ px::bind(&expr<Iterator>::min, _val, _2) ]
                |   (kw["max"] > '(' > conditional_expression(_r1) [_val = _1] > ',' > conditional_expression(_r1) > ')')
                                                                    [ px::bind(&expr<Iterator>::max, _val, _2) ]
                |   (kw["random"] > '(' > conditional_expression(_r1) [_val = _1] > ',' > conditional_expression(_r1) > ')')
                                                                    [ px::bind(&MyContext::random<Iterator>, _r1, _val, _2) ]
                |   (kw["digits"] > '(' > conditional_expression(_r1) [_val = _1] > ',' > conditional_expression(_r1) > optional_parameter(_r1))
                                                                    [ px::bind(&expr<Iterator>::template digits<false>, _val, _2, _3) ]
                |   (kw["zdigits"] > '(' > conditional_expression(_r1) [_val = _1] > ',' > conditional_expression(_r1) > optional_parameter(_r1))
                                                                    [ px::bind(&expr<Iterator>::template digits<true>, _val, _2, _3) ]
                |   (kw["int"]   > '(' > conditional_expression(_r1) > ')') [ px::bind(&FactorActions::to_int,  _1, _val) ]
                |   (kw["round"] > '(' > conditional_expression(_r1) > ')') [ px::bind(&FactorActions::round,   _1, _val) ]
                |   (strict_double > iter_pos)                      [ px::bind(&FactorActions::double_, _1, _2, _val) ]
                |   (int_      > iter_pos)                          [ px::bind(&FactorActions::int_,    _1, _2, _val) ]
                |   (kw[bool_] > iter_pos)                          [ px::bind(&FactorActions::bool_,   _1, _2, _val) ]
                |   raw[lexeme['"' > *((utf8char - char_('\\') - char_('"')) | ('\\' > char_)) > '"']]
                                                                    [ px::bind(&FactorActions::string_, _1,     _val) ]
                );
            unary_expression.name("unary_expression");
            optional_parameter = iter_pos[px::bind(&FactorActions::set_start_pos, _1, _val)] >> (
                    lit(')')                                       [ px::bind(&FactorActions::noexpr, _val) ]
                |   (lit(',') > conditional_expression(_r1) > ')') [ _val = _1 ]
                );
            optional_parameter.name("optional_parameter");
            scalar_variable_reference =
                variable_reference(_r1)[_a=_1] >>
                (
                        ('[' > additive_expression(_r1)[px::bind(&MyContext::evaluate_index<Iterator>, _1, _b)] > ']' >
                            iter_pos[px::bind(&MyContext::vector_variable_reference<Iterator>, _r1, _a, _b, _1, _val)])
                    |   eps[px::bind(&MyContext::scalar_variable_reference<Iterator>, _r1, _a, _val)]
                );
            scalar_variable_reference.name("scalar variable reference");
            variable_reference = identifier
                [ px::bind(&MyContext::resolve_variable<Iterator>, _r1, _1, _val) ];
            variable_reference.name("variable reference");
            regular_expression = raw[lexeme['/' > *((utf8char - char_('\\') - char_('/')) | ('\\' > char_)) > '/']];
            regular_expression.name("regular_expression");
            keywords.add
                ("and")
                ("digits")
                ("zdigits")
                ("if")
                ("int")
                //("inf")
                ("else")
                ("elsif")
                ("endif")
                ("false")
                ("min")
                ("max")
                ("random")
                ("round")
                ("not")
                ("or")
                ("true");
            if (0) {
                debug(start);
                debug(text);
                debug(text_block);
                debug(macro);
                debug(if_else_output);
//                debug(switch_output);
                debug(legacy_variable_expansion);
                debug(identifier);
                debug(conditional_expression);
                debug(logical_or_expression);
                debug(logical_and_expression);
                debug(equality_expression);
                debug(bool_expr_eval);
                debug(relational_expression);
                debug(additive_expression);
                debug(multiplicative_expression);
                debug(unary_expression);
                debug(optional_parameter);
                debug(scalar_variable_reference);
                debug(variable_reference);
                debug(regular_expression);
            }
        }
References Slic3r::client::macro_processor< Iterator >::additive_expression, Slic3r::client::macro_processor< Iterator >::bool_expr_eval, Slic3r::client::macro_processor< Iterator >::conditional_expression, Slic3r::client::macro_processor< Iterator >::equality_expression, Slic3r::client::MyContext::evaluate_full_macro(), Slic3r::client::macro_processor< Iterator >::identifier, Slic3r::client::macro_processor< Iterator >::if_else_output, Slic3r::client::macro_processor< Iterator >::keywords, Slic3r::client::macro_processor< Iterator >::legacy_variable_expansion, Slic3r::client::macro_processor< Iterator >::logical_and_expression, Slic3r::client::macro_processor< Iterator >::logical_or_expression, Slic3r::client::macro_processor< Iterator >::macro, Slic3r::client::macro_processor< Iterator >::multiplicative_expression, Slic3r::client::macro_processor< Iterator >::optional_parameter, out, Slic3r::client::macro_processor< Iterator >::regular_expression, Slic3r::client::macro_processor< Iterator >::relational_expression, round(), Slic3r::client::macro_processor< Iterator >::scalar_variable_reference, Slic3r::client::macro_processor< Iterator >::start, Slic3r::client::macro_processor< Iterator >::text, Slic3r::client::macro_processor< Iterator >::text_block, Slic3r::client::macro_processor< Iterator >::unary_expression, and Slic3r::client::macro_processor< Iterator >::variable_reference.
Member Data Documentation
additive_expression
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::additive_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
bool_expr_eval
template<typename Iterator > qi::rule<Iterator, bool(const MyContext*), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::bool_expr_eval
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
conditional_expression
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::conditional_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
equality_expression
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::equality_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
identifier
template<typename Iterator > qi::rule<Iterator, boost::iterator_range<Iterator>(), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::identifier
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
if_else_output
template<typename Iterator > qi::rule<Iterator, std::string(const MyContext*), qi::locals<bool, bool>, spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::if_else_output
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
keywords
template<typename Iterator > qi::symbols<char> Slic3r::client::macro_processor< Iterator >::keywords
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
legacy_variable_expansion
template<typename Iterator > qi::rule<Iterator, std::string(const MyContext*), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::legacy_variable_expansion
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
logical_and_expression
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::logical_and_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
logical_or_expression
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::logical_or_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
macro
template<typename Iterator > qi::rule<Iterator, std::string(const MyContext*), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::macro
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
multiplicative_expression
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::multiplicative_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
optional_parameter
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::optional_parameter
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
regular_expression
template<typename Iterator > qi::rule<Iterator, boost::iterator_range<Iterator>(), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::regular_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
relational_expression
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::relational_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
scalar_variable_reference
template<typename Iterator > qi::rule<Iterator, expr<Iterator>(const MyContext*), qi::locals<OptWithPos<Iterator>, int>, spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::scalar_variable_reference
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
start
template<typename Iterator > qi::rule<Iterator, std::string(const MyContext*), qi::locals<bool>, spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::start
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
text
template<typename Iterator > qi::rule<Iterator, std::string(), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::text
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
text_block
template<typename Iterator > qi::rule<Iterator, std::string(const MyContext*), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::text_block
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
unary_expression
template<typename Iterator > RuleExpression Slic3r::client::macro_processor< Iterator >::unary_expression
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
variable_reference
template<typename Iterator > qi::rule<Iterator, OptWithPos<Iterator>(const MyContext*), spirit_encoding::space_type> Slic3r::client::macro_processor< Iterator >::variable_reference
Referenced by Slic3r::client::macro_processor< Iterator >::macro_processor().
The documentation for this struct was generated from the following file:
src/libslic3r/PlaceholderParser.cpp