OrcaSlicer: Slic3r::GCode Class Reference
Slic3r::GCode Class Reference
#include <src/libslic3r/GCode.hpp>
Classes
class GCodeOutputStream
struct InstanceToPrint
struct LayerResult
struct LayerToPrint
struct ObjectByExtruder
Public Member Functions
GCode ()
~GCode ()=default
void do_export (Print *print, const char *path, GCodeProcessorResult *result=nullptr, ThumbnailsGeneratorCallback thumbnail_cb=nullptr)
void set_gcode_offset (double x, double y)
const Vec2d & origin () const
void set_origin (const Vec2d &pointf)
void set_origin (const coordf_t x, const coordf_t y)
const Point & last_pos () const
Vec2d point_to_gcode (const Point &point) const
Point gcode_to_point (const Vec2d &point) const
Vec2d point_to_gcode_quantized (const Point &point) const
const FullPrintConfig & config () const
const Layer * layer () const
GCodeWriter & writer ()
const GCodeWriter & writer () const
PlaceholderParser & placeholder_parser ()
const PlaceholderParser & placeholder_parser () const
std::string placeholder_parser_process (const std::string &name, const std::string &templ, unsigned int current_extruder_id, const DynamicConfig *config_override=nullptr)
bool enable_cooling_markers () const
unsigned int layer_count () const
void set_layer_count (unsigned int value)
void apply_print_config (const PrintConfig &print_config)
std::string travel_to (const Point &point, ExtrusionRole role, std::string comment)
bool needs_retraction (const Polyline &travel, ExtrusionRole role, LiftType &lift_type)
std::string retract (bool toolchange=false, bool is_last_retraction=false, LiftType lift_type=LiftType::SpiralLift)
std::string unretract ()
std::string set_extruder (unsigned int extruder_id, double print_z)
bool is_BBL_Printer ()
std::string set_object_info (Print *print)
Static Public Member Functions
static void append_full_config (const Print &print, std::string &str)
Private Member Functions
void _do_export (Print &print, GCodeOutputStream &file, ThumbnailsGeneratorCallback thumbnail_cb)
LayerResult process_layer (const Print &print, const std::vector< LayerToPrint > &layers, const LayerTools &layer_tools, const bool last_layer, const std::vector< const PrintInstance * > *ordering, const size_t single_object_idx=size_t(-1), const bool prime_extruder=false)
void process_layers (const Print &print, const ToolOrdering &tool_ordering, const std::vector< const PrintInstance * > &print_object_instances_ordering, const std::vector< std::pair< coordf_t, std::vector< LayerToPrint > > > &layers_to_print, GCodeOutputStream &output_stream)
void process_layers (const Print &print, const ToolOrdering &tool_ordering, std::vector< LayerToPrint > layers_to_print, const size_t single_object_idx, GCodeOutputStream &output_stream, const bool prime_extruder=false)
void check_placeholder_parser_failed ()
void set_last_pos (const Point &pos)
bool last_pos_defined () const
void set_extruders (const std::vector< unsigned int > &extruder_ids)
std::string preamble ()
std::string change_layer (coordf_t print_z, bool lazy_raise=false)
std::string extrude_entity (const ExtrusionEntity &entity, std::string description="", double speed=-1.)
std::string extrude_loop (ExtrusionLoop loop, std::string description, double speed=-1.)
std::string extrude_multi_path (ExtrusionMultiPath multipath, std::string description="", double speed=-1.)
std::string extrude_path (ExtrusionPath path, std::string description="", double speed=-1.)
std::vector< InstanceToPrint > sort_print_object_instances (std::vector< ObjectByExtruder > &objects_by_extruder, const std::vector< LayerToPrint > &layers, const std::vector< const PrintInstance * > *ordering, const size_t single_object_instance_idx)
std::string extrude_perimeters (const Print &print, const std::vector< ObjectByExtruder::Island::Region > &by_region)
std::string extrude_infill (const Print &print, const std::vector< ObjectByExtruder::Island::Region > &by_region, bool ironing)
std::string extrude_support (const ExtrusionEntityCollection &support_fills)
LiftType to_lift_type (ZHopType z_hop_types)
std::string _encode_label_ids_to_base64 (std::vector< size_t > ids)
int get_bed_temperature (const int extruder_id, const bool is_first_layer, const BedType bed_type) const
std::string _extrude (const ExtrusionPath &path, std::string description="", double speed=-1)
void print_machine_envelope (GCodeOutputStream &file, Print &print)
void _print_first_layer_bed_temperature (GCodeOutputStream &file, Print &print, const std::string &gcode, unsigned int first_printing_extruder_id, bool wait)
void _print_first_layer_extruder_temperatures (GCodeOutputStream &file, Print &print, const std::string &gcode, unsigned int first_printing_extruder_id, bool wait)
bool on_first_layer () const
int layer_id () const
bool object_layer_over_raft () const
Static Private Member Functions
static std::vector< LayerToPrint > collect_layers_to_print (const PrintObject &object)
static std::vector< std::pair< coordf_t, std::vector< LayerToPrint > > > collect_layers_to_print (const Print &print)
Private Attributes
std::set< ObjectID > m_objsWithBrim
std::set< ObjectID > m_objSupportsWithBrim
SeamPlacer m_seam_placer
ExtrusionQualityEstimator m_extrusion_quality_estimator
Vec2d m_origin
FullPrintConfig m_config
DynamicConfig m_calib_config
double m_scaled_resolution
GCodeWriter m_writer
PlaceholderParser m_placeholder_parser
PlaceholderParser::ContextData m_placeholder_parser_context
std::map< std::string, std::string > m_placeholder_parser_failed_templates
OozePrevention m_ooze_prevention
Wipe m_wipe
AvoidCrossingPerimeters m_avoid_crossing_perimeters
RetractWhenCrossingPerimeters m_retract_when_crossing_perimeters
bool m_enable_loop_clipping
bool m_enable_cooling_markers
bool m_enable_exclude_object
std::vector< size_t > m_label_objects_ids
bool m_is_overhang_fan_on
bool m_is_supp_interface_fan_on
bool m_enable_extrusion_role_markers
ExtrusionRole m_last_processor_extrusion_role
unsigned int m_layer_count
int m_layer_index
const Layer * m_layer
bool m_object_layer_over_raft
ExtrusionRole m_last_extrusion_role
ExtrusionRole m_last_notgapfill_extrusion_role
float m_last_height { 0.0f }
float m_last_layer_z { 0.0f }
float m_max_layer_z { 0.0f }
float m_last_width { 0.0f }
Point m_last_pos
bool m_last_pos_defined
std::unique_ptr< CoolingBuffer > m_cooling_buffer
std::unique_ptr< SpiralVase > m_spiral_vase
std::unique_ptr< WipeTowerIntegration > m_wipe_tower
std::vector< coordf_t > m_skirt_done
bool m_brim_done
bool m_second_layer_things_done
std::pair< const PrintObject *, Point > m_last_obj_copy
bool m_silent_time_estimator_enabled
GCodeProcessor m_processor
std::unique_ptr< FanMover > m_fan_mover
Print * m_curr_print = nullptr
unsigned int m_toolchange_count
coordf_t m_nominal_z
bool m_need_change_layer_lift_z = false
int m_start_gcode_filament = -1
Friends
class Wipe
class WipeTowerIntegration
class Print
ObjectByExtruder & object_by_extruder (std::map< unsigned int, std::vector< ObjectByExtruder > > &by_extruder, unsigned int extruder_id, size_t object_idx, size_t num_objects)
std::vector< ObjectByExtruder::Island > & object_islands_by_extruder (std::map< unsigned int, std::vector< ObjectByExtruder > > &by_extruder, unsigned int extruder_id, size_t object_idx, size_t num_objects, size_t num_islands)
Detailed Description
Class Documentation
Slic3r::GCode::LayerResult
struct Slic3r::GCode::LayerResult
Class Members
bool cooling_buffer_flush { false }
string gcode
size_t layer_id
bool spiral_vase_enable { false }
Constructor & Destructor Documentation
GCode()
Slic3r::GCode::GCode () inline
            :
      m_origin(Vec2d::Zero()),
        m_enable_loop_clipping(true),
        m_enable_cooling_markers(false),
        m_enable_extrusion_role_markers(false),
        m_last_processor_extrusion_role(erNone),
        m_layer_count(0),
        m_layer_index(-1),
        m_layer(nullptr),
        m_object_layer_over_raft(false),
        //m_volumetric_speed(0),
        m_last_pos_defined(false),
        m_last_extrusion_role(erNone),
        m_last_width(0.0f),
#if ENABLE_GCODE_VIEWER_DATA_CHECKING
        m_last_mm3_per_mm(0.0),
#endif // ENABLE_GCODE_VIEWER_DATA_CHECKING
        m_brim_done(false),
        m_second_layer_things_done(false),
        m_silent_time_estimator_enabled(false),
        m_last_obj_copy(nullptr, Point(std::numeric_limits<coord_t>::max(), std::numeric_limits<coord_t>::max())),
        // BBS
        m_toolchange_count(0),
        m_nominal_z(0.)
        {}
~GCode()
Slic3r::GCode::~GCode () default
Member Function Documentation
_do_export()
void Slic3r::GCode::_do_export (Print & print, GCodeOutputStream & file, ThumbnailsGeneratorCallback thumbnail_cb) private
{
    PROFILE_FUNC();
    // modifies m_silent_time_estimator_enabled
    DoExport::init_gcode_processor(print.config(), m_processor, m_silent_time_estimator_enabled);
    const bool is_bbl_printers = print.is_BBL_printer();
    m_calib_config.clear();
    // resets analyzer's tracking data
    m_last_height  = 0.f;
    m_last_layer_z = 0.f;
    m_max_layer_z  = 0.f;
    m_last_width = 0.f;
    m_is_overhang_fan_on = false;
    m_is_supp_interface_fan_on = false;
#if ENABLE_GCODE_VIEWER_DATA_CHECKING
    m_last_mm3_per_mm = 0.;
#endif // ENABLE_GCODE_VIEWER_DATA_CHECKING
    m_fan_mover.release();
    m_writer.set_is_bbl_machine(is_bbl_printers);
    // How many times will be change_layer() called?
    // change_layer() in turn increments the progress bar status.
    m_layer_count = 0;
    if (print.config().print_sequence == PrintSequence::ByObject) {
        // Add each of the object's layers separately.
        for (auto object : print.objects()) {
            std::vector<coordf_t> zs;
            zs.reserve(object->layers().size() + object->support_layers().size());
            for (auto layer : object->layers())
                zs.push_back(layer->print_z);
            for (auto layer : object->support_layers())
                zs.push_back(layer->print_z);
            std::sort(zs.begin(), zs.end());
            //BBS: merge numerically very close Z values.
            auto end_it = std::unique(zs.begin(), zs.end());
            unsigned int temp_layer_count = (unsigned int)(end_it - zs.begin());
            for (auto it = zs.begin(); it != end_it - 1; it++) {
                if (abs(*it - *(it + 1)) < EPSILON)
                    temp_layer_count--;
            }
            m_layer_count += (unsigned int)(object->instances().size() * temp_layer_count);
        }
    } else {
        // Print all objects with the same print_z together.
        std::vector<coordf_t> zs;
        for (auto object : print.objects()) {
            zs.reserve(zs.size() + object->layers().size() + object->support_layers().size());
            for (auto layer : object->layers())
                zs.push_back(layer->print_z);
            for (auto layer : object->support_layers())
                zs.push_back(layer->print_z);
        }
        if (!zs.empty())
        {
            std::sort(zs.begin(), zs.end());
            //BBS: merge numerically very close Z values.
            auto end_it = std::unique(zs.begin(), zs.end());
            m_layer_count = (unsigned int)(end_it - zs.begin());
            for (auto it = zs.begin(); it != end_it - 1; it++) {
                if (abs(*it - *(it + 1)) < EPSILON)
                    m_layer_count--;
            }
        }
    }
    print.throw_if_canceled();
    m_enable_cooling_markers = true;
    this->apply_print_config(print.config());
    //m_volumetric_speed = DoExport::autospeed_volumetric_limit(print);
    print.throw_if_canceled();
    if (print.config().spiral_mode.value)
        m_spiral_vase = make_unique<SpiralVase>(print.config());
#ifdef HAS_PRESSURE_EQUALIZER
    if (print.config().max_volumetric_extrusion_rate_slope_positive.value > 0 ||
        print.config().max_volumetric_extrusion_rate_slope_negative.value > 0)
        m_pressure_equalizer = make_unique<PressureEqualizer>(&print.config());
    m_enable_extrusion_role_markers = (bool)m_pressure_equalizer;
#else /* HAS_PRESSURE_EQUALIZER */
    m_enable_extrusion_role_markers = false;
#endif /* HAS_PRESSURE_EQUALIZER */
    file.write_format("; HEADER_BLOCK_START\n");
    // Write information on the generator.
    file.write_format("; generated by %s on %s\n", Slic3r::header_slic3r_generated().c_str(), Slic3r::Utils::local_timestamp().c_str());
    if (is_bbl_printers)
        file.write_format(";%s\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Estimated_Printing_Time_Placeholder).c_str());
    //BBS: total layer number
    file.write_format(";%s\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Total_Layer_Number_Placeholder).c_str());
    m_enable_exclude_object = config().exclude_object;
    //Orca: extra check for bbl printer
    if (is_bbl_printers) {
        if (print.extruders(true).size() == 1 &&                  // Don't support multi-color
            print.calib_params().mode == CalibMode::Calib_None) { // Don't support skipping in cali mode
            // list all label_object_id with sorted order here
            m_enable_exclude_object = true;
            m_label_objects_ids.clear();
            m_label_objects_ids.reserve(print.num_object_instances());
            for (const PrintObject *print_object : print.objects())
                for (const PrintInstance &print_instance : print_object->instances())
                    m_label_objects_ids.push_back(print_instance.model_instance->get_labeled_id());
            std::sort(m_label_objects_ids.begin(), m_label_objects_ids.end());
            std::string objects_id_list = "; model label id: ";
            for (auto it = m_label_objects_ids.begin(); it != m_label_objects_ids.end(); it++)
                objects_id_list += (std::to_string(*it) + (it != m_label_objects_ids.end() - 1 ? "," : "\n"));
            file.writeln(objects_id_list);
        } else {
            m_enable_exclude_object = false;
            m_label_objects_ids.clear();
        }
    }
    file.write_format("; HEADER_BLOCK_END\n\n");
      // BBS: write global config at the beginning of gcode file because printer
      // need these config information
      // Append full config, delimited by two 'phony' configuration keys
      // CONFIG_BLOCK_START and CONFIG_BLOCK_END. The delimiters are structured
      // as configuration key / value pairs to be parsable by older versions of
      // PrusaSlicer G-code viewer.
    {
      if (is_bbl_printers) {
        file.write("; CONFIG_BLOCK_START\n");
        std::string full_config;
        append_full_config(print, full_config);
        if (!full_config.empty())
          file.write(full_config);
        // SoftFever: write compatiple image
        int first_layer_bed_temperature = get_bed_temperature(0, true, print.config().curr_bed_type);
        file.write_format("; first_layer_bed_temperature = %d\n",
                          first_layer_bed_temperature);
        file.write_format(
            "; first_layer_temperature = %d\n",
            print.config().nozzle_temperature_initial_layer.get_at(0));
        file.write("; CONFIG_BLOCK_END\n\n");
      } else {
        DoExport::export_thumbnails_to_file(
            thumbnail_cb, print.get_plate_index(), print.full_print_config().option<ConfigOptionPoints>("thumbnails")->values,
            [&file](const char *sz) { file.write(sz); },
            [&print]() { print.throw_if_canceled(); });
      }
    }
    // Write some terse information on the slicing parameters.
    const PrintObject *first_object         = print.objects().front();
    const double       layer_height         = first_object->config().layer_height.value;
    const double       initial_layer_print_height   = print.config().initial_layer_print_height.value;
    for (size_t region_id = 0; region_id < print.num_print_regions(); ++ region_id) {
        const PrintRegion &region = print.get_print_region(region_id);
        file.write_format("; external perimeters extrusion width = %.2fmm\n", region.flow(*first_object, frExternalPerimeter, layer_height).width());
        file.write_format("; perimeters extrusion width = %.2fmm\n",          region.flow(*first_object, frPerimeter,         layer_height).width());
        file.write_format("; infill extrusion width = %.2fmm\n",              region.flow(*first_object, frInfill,            layer_height).width());
        file.write_format("; solid infill extrusion width = %.2fmm\n",        region.flow(*first_object, frSolidInfill,       layer_height).width());
        file.write_format("; top infill extrusion width = %.2fmm\n",          region.flow(*first_object, frTopSolidInfill,    layer_height).width());
        if (print.has_support_material())
            file.write_format("; support material extrusion width = %.2fmm\n", support_material_flow(first_object).width());
        if (print.config().initial_layer_line_width.value > 0)
            file.write_format("; first layer extrusion width = %.2fmm\n",   region.flow(*first_object, frPerimeter, initial_layer_print_height, true).width());
        file.write_format("\n");
    }
    file.write_format("; EXECUTABLE_BLOCK_START\n");
    // SoftFever
    file.write(set_object_info(&print));
    // adds tags for time estimators
    file.write_format(";%s\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::First_Line_M73_Placeholder).c_str());
    // Prepare the helper object for replacing placeholders in custom G-code and output filename.
    m_placeholder_parser = print.placeholder_parser();
    m_placeholder_parser.update_timestamp();
    m_placeholder_parser_context.rng = std::mt19937(std::chrono::high_resolution_clock::now().time_since_epoch().count());
    print.update_object_placeholders(m_placeholder_parser.config_writable(), ".gcode");
    // Get optimal tool ordering to minimize tool switches of a multi-exruder print.
    // For a print by objects, find the 1st printing object.
    ToolOrdering tool_ordering;
    unsigned int initial_extruder_id = (unsigned int)-1;
    //BBS: first non-support filament extruder
    unsigned int initial_non_support_extruder_id;
    unsigned int final_extruder_id   = (unsigned int)-1;
    bool         has_wipe_tower      = false;
    std::vector<const PrintInstance*>           print_object_instances_ordering;
    std::vector<const PrintInstance*>::const_iterator   print_object_instance_sequential_active;
    if (print.config().print_sequence == PrintSequence::ByObject) {
        // Order object instances for sequential print.
        print_object_instances_ordering = sort_object_instances_by_model_order(print);
//        print_object_instances_ordering = sort_object_instances_by_max_z(print);
        // Find the 1st printing object, find its tool ordering and the initial extruder ID.
        print_object_instance_sequential_active = print_object_instances_ordering.begin();
        for (; print_object_instance_sequential_active != print_object_instances_ordering.end(); ++ print_object_instance_sequential_active) {
            tool_ordering = ToolOrdering(*(*print_object_instance_sequential_active)->print_object, initial_extruder_id);
            if ((initial_extruder_id = tool_ordering.first_extruder()) != static_cast<unsigned int>(-1)) {
                //BBS: try to find the non-support filament extruder if is multi color and initial_extruder is support filament
                initial_non_support_extruder_id = initial_extruder_id;
                if (tool_ordering.all_extruders().size() > 1 && print.config().filament_is_support.get_at(initial_extruder_id)) {
                    bool has_non_support_filament = false;
                    for (unsigned int extruder : tool_ordering.all_extruders()) {
                        if (!print.config().filament_is_support.get_at(extruder)) {
                            has_non_support_filament = true;
                            break;
                        }
                    }
                    //BBS: find the non-support filament extruder of object
                    if (has_non_support_filament)
                        for (LayerTools layer_tools : tool_ordering.layer_tools()) {
                            if (!layer_tools.has_object)
                                continue;
                            for (unsigned int extruder : layer_tools.extruders) {
                                if (print.config().filament_is_support.get_at(extruder))
                                    continue;
                                initial_non_support_extruder_id = extruder;
                                break;
                            }
                        }
                }
                break;
            }
        }
        if (initial_extruder_id == static_cast<unsigned int>(-1))
            // No object to print was found, cancel the G-code export.
            throw Slic3r::SlicingError(_(L("No object can be printed. Maybe too small")));
        // We don't allow switching of extruders per layer by Model::custom_gcode_per_print_z in sequential mode.
        // Use the extruder IDs collected from Regions.
        this->set_extruders(print.extruders());
        has_wipe_tower = print.has_wipe_tower() && tool_ordering.has_wipe_tower();
    } else {
        // Find tool ordering for all the objects at once, and the initial extruder ID.
        // If the tool ordering has been pre-calculated by Print class for wipe tower already, reuse it.
        tool_ordering = print.tool_ordering();
        tool_ordering.assign_custom_gcodes(print);
        if (tool_ordering.all_extruders().empty())
            // No object to print was found, cancel the G-code export.
            throw Slic3r::SlicingError(_(L("No object can be printed. Maybe too small")));
        has_wipe_tower = print.has_wipe_tower() && tool_ordering.has_wipe_tower();
        // BBS: priming logic is removed, so 1st layer tool_ordering also respect the object tool sequence
#if 0
        initial_extruder_id = (has_wipe_tower && !print.config().single_extruder_multi_material_priming) ?
            // The priming towers will be skipped.
            tool_ordering.all_extruders().back() :
            // Don't skip the priming towers.
            tool_ordering.first_extruder();
#else
        initial_extruder_id = tool_ordering.first_extruder();
#endif
        //BBS: try to find the non-support filament extruder if is multi color and initial_extruder is support filament
        if (initial_extruder_id != static_cast<unsigned int>(-1)) {
            initial_non_support_extruder_id = initial_extruder_id;
            if (tool_ordering.all_extruders().size() > 1 && print.config().filament_is_support.get_at(initial_extruder_id)) {
                bool has_non_support_filament = false;
                for (unsigned int extruder : tool_ordering.all_extruders()) {
                    if (!print.config().filament_is_support.get_at(extruder)) {
                        has_non_support_filament = true;
                        break;
                    }
                }
                //BBS: find the non-support filament extruder of object
                if (has_non_support_filament)
                    for (LayerTools layer_tools : tool_ordering.layer_tools()) {
                        if (!layer_tools.has_object)
                            continue;
                        for (unsigned int extruder : layer_tools.extruders) {
                            if (print.config().filament_is_support.get_at(extruder))
                                continue;
                            initial_non_support_extruder_id = extruder;
                            break;
                        }
                    }
            }
        }
        // In non-sequential print, the printing extruders may have been modified by the extruder switches stored in Model::custom_gcode_per_print_z.
        // Therefore initialize the printing extruders from there.
        this->set_extruders(tool_ordering.all_extruders());
        // Order object instances using a nearest neighbor search.
        print_object_instances_ordering = chain_print_object_instances(print);
    }
    if (initial_extruder_id == (unsigned int)-1) {
        // Nothing to print!
        initial_extruder_id = 0;
        initial_non_support_extruder_id = 0;
        final_extruder_id   = 0;
    } else {
        final_extruder_id = tool_ordering.last_extruder();
        assert(final_extruder_id != (unsigned int)-1);
    }
    print.throw_if_canceled();
    m_cooling_buffer = make_unique<CoolingBuffer>(*this);
    m_cooling_buffer->set_current_extruder(initial_extruder_id);
    // Emit machine envelope limits for the Marlin firmware.
    this->print_machine_envelope(file, print);
    // Disable fan.
    if (m_config.auxiliary_fan.value && print.config().close_fan_the_first_x_layers.get_at(initial_extruder_id)) {
        file.write(m_writer.set_fan(0));
        //BBS: disable additional fan
        file.write(m_writer.set_additional_fan(0));
    }
    // Let the start-up script prime the 1st printing tool.
    m_placeholder_parser.set("initial_tool", initial_extruder_id);
    m_placeholder_parser.set("initial_extruder", initial_extruder_id);
    //BBS
    m_placeholder_parser.set("initial_no_support_tool", initial_non_support_extruder_id);
    m_placeholder_parser.set("initial_no_support_extruder", initial_non_support_extruder_id);
    m_placeholder_parser.set("current_extruder", initial_extruder_id);
    //Set variable for total layer count so it can be used in custom gcode.
    m_placeholder_parser.set("total_layer_count", m_layer_count);
    // Useful for sequential prints.
    m_placeholder_parser.set("current_object_idx", 0);
    // For the start / end G-code to do the priming and final filament pull in case there is no wipe tower provided.
    m_placeholder_parser.set("has_wipe_tower", has_wipe_tower);
    //m_placeholder_parser.set("has_single_extruder_multi_material_priming", has_wipe_tower && print.config().single_extruder_multi_material_priming);
    m_placeholder_parser.set("total_toolchanges", std::max(0, print.wipe_tower_data().number_of_toolchanges)); // Check for negative toolchanges (single extruder mode) and set to 0 (no tool change).
    // PlaceholderParser currently substitues non-existent vector values with the zero'th value, which is harmful in the
    // case of "is_extruder_used[]" as Slicer may lie about availability of such non-existent extruder. We rather
    // sacrifice 256B of memory before we change the behavior of the PlaceholderParser, which should really only fill in
    // the non-existent vector elements for filament parameters.
    std::vector<unsigned char> is_extruder_used(std::max(size_t(255), print.config().filament_diameter.size()), 0);
    for (unsigned int extruder : tool_ordering.all_extruders())
        is_extruder_used[extruder] = true;
    m_placeholder_parser.set("is_extruder_used", new ConfigOptionBools(is_extruder_used));
    Vec2f plate_offset = m_writer.get_xy_offset();
    {
        BoundingBoxf bbox(print.config().printable_area.values);
        m_placeholder_parser.set("print_bed_min", new ConfigOptionFloats({ bbox.min.x() - plate_offset.x(), bbox.min.y() - plate_offset.y() }));
        m_placeholder_parser.set("print_bed_max", new ConfigOptionFloats({ bbox.max.x() - plate_offset.x(), bbox.max.y() - plate_offset.y() }));
        m_placeholder_parser.set("print_bed_size", new ConfigOptionFloats({ bbox.size().x(), bbox.size().y() }));
    }
    {
        // Convex hull of the 1st layer extrusions, for bed leveling and placing the initial purge line.
        // It encompasses the object extrusions, support extrusions, skirt, brim, wipe tower.
        // It does NOT encompass user extrusions generated by custom G-code,
        // therefore it does NOT encompass the initial purge line.
        // It does NOT encompass MMU/MMU2 starting (wipe) areas.
        auto pts = std::make_unique<ConfigOptionPoints>();
        pts->values.reserve(print.first_layer_convex_hull().size());
        for (const Point& pt : print.first_layer_convex_hull().points)
            pts->values.emplace_back(print.translate_to_print_space(pt));
        BoundingBoxf bbox(pts->values);
        m_placeholder_parser.set("first_layer_print_convex_hull", pts.release());
        m_placeholder_parser.set("first_layer_print_min", new ConfigOptionFloats({bbox.min.x(), bbox.min.y()}));
        m_placeholder_parser.set("first_layer_print_max", new ConfigOptionFloats({bbox.max.x(), bbox.max.y()}));
        m_placeholder_parser.set("first_layer_print_size", new ConfigOptionFloats({ bbox.size().x(), bbox.size().y() }));
    }
    float outer_wall_volumetric_speed = 0.0f;
    {
        int curr_bed_type = m_config.curr_bed_type.getInt();
        std::string first_layer_bed_temp_str;
        const ConfigOptionInts* first_bed_temp_opt = m_config.option<ConfigOptionInts>(get_bed_temp_1st_layer_key((BedType)curr_bed_type));
        const ConfigOptionInts* bed_temp_opt = m_config.option<ConfigOptionInts>(get_bed_temp_key((BedType)curr_bed_type));
        m_placeholder_parser.set("bbl_bed_temperature_gcode", new ConfigOptionBool(false));
        m_placeholder_parser.set("bed_temperature_initial_layer", new ConfigOptionInts(*first_bed_temp_opt));
        m_placeholder_parser.set("bed_temperature", new ConfigOptionInts(*bed_temp_opt));
        m_placeholder_parser.set("bed_temperature_initial_layer_single", new ConfigOptionInt(first_bed_temp_opt->get_at(initial_extruder_id)));
        m_placeholder_parser.set("bed_temperature_initial_layer_vector", new ConfigOptionString(""));
        m_placeholder_parser.set("chamber_temperature",new ConfigOptionInts(m_config.chamber_temperature));
        // SoftFever: support variables `first_layer_temperature` and `first_layer_bed_temperature`
        m_placeholder_parser.set("first_layer_bed_temperature", new ConfigOptionInts(*first_bed_temp_opt));
        m_placeholder_parser.set("first_layer_temperature", new ConfigOptionInts(m_config.nozzle_temperature_initial_layer));
        m_placeholder_parser.set("max_print_height",new ConfigOptionInt(m_config.printable_height));
        m_placeholder_parser.set("z_offset", new ConfigOptionFloat(0.0f));
        m_placeholder_parser.set("plate_name", new ConfigOptionString(print.get_plate_name()));
        m_placeholder_parser.set("first_layer_height", new ConfigOptionFloat(m_config.initial_layer_print_height.value));
        //BBS: calculate the volumetric speed of outer wall. Ignore pre-object setting and multi-filament, and just use the default setting
        {
            float filament_max_volumetric_speed = m_config.option<ConfigOptionFloats>("filament_max_volumetric_speed")->get_at(initial_non_support_extruder_id);
            const double nozzle_diameter = m_config.nozzle_diameter.get_at(initial_non_support_extruder_id);
            float outer_wall_line_width = this->config().get_abs_value("outer_wall_line_width", nozzle_diameter);
            if (outer_wall_line_width == 0.0) {
                float default_line_width =  this->config().get_abs_value("line_width", nozzle_diameter);
                outer_wall_line_width = default_line_width == 0.0 ? nozzle_diameter : default_line_width;
            }
            Flow outer_wall_flow = Flow(outer_wall_line_width, m_config.layer_height, m_config.nozzle_diameter.get_at(initial_non_support_extruder_id));
            float outer_wall_speed = print.default_region_config().outer_wall_speed.value;
            outer_wall_volumetric_speed = outer_wall_speed * outer_wall_flow.mm3_per_mm();
            if (outer_wall_volumetric_speed > filament_max_volumetric_speed)
                outer_wall_volumetric_speed = filament_max_volumetric_speed;
            m_placeholder_parser.set("outer_wall_volumetric_speed", new ConfigOptionFloat(outer_wall_volumetric_speed));
        }
    }
    std::string machine_start_gcode = this->placeholder_parser_process("machine_start_gcode", print.config().machine_start_gcode.value, initial_extruder_id);
    if (print.config().gcode_flavor != gcfKlipper) {
        // Set bed temperature if the start G-code does not contain any bed temp control G-codes.
        this->_print_first_layer_bed_temperature(file, print, machine_start_gcode, initial_extruder_id, true);
        // Set extruder(s) temperature before and after start G-code.
        this->_print_first_layer_extruder_temperatures(file, print, machine_start_gcode, initial_extruder_id, false);
    }
    // adds tag for processor
    file.write_format(";%s%s\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Role).c_str(), ExtrusionEntity::role_to_string(erCustom).c_str());
    // Write the custom start G-code
    file.writeln(machine_start_gcode);
    //BBS: gcode writer doesn't know where the real position of extruder is after inserting custom gcode
    m_writer.set_current_position_clear(false);
    m_start_gcode_filament = GCodeProcessor::get_gcode_last_filament(machine_start_gcode);
    //flush FanMover buffer to avoid modifying the start gcode if it's manual.
    if (!machine_start_gcode.empty() && this->m_fan_mover.get() != nullptr)
        file.write(this->m_fan_mover.get()->process_gcode("", true));
    // Process filament-specific gcode.
   /* if (has_wipe_tower) {
        // Wipe tower will control the extruder switching, it will call the filament_start_gcode.
    } else {
            DynamicConfig config;
            config.set_key_value("filament_extruder_id", new ConfigOptionInt(int(initial_extruder_id)));
            file.writeln(this->placeholder_parser_process("filament_start_gcode", print.config().filament_start_gcode.values[initial_extruder_id], initial_extruder_id, &config));
    }
*/
    if (is_bbl_printers)
        this->_print_first_layer_extruder_temperatures(file, print, machine_start_gcode, initial_extruder_id, true);
    print.throw_if_canceled();
    // Set other general things.
    file.write(this->preamble());
    // Calculate wiping points if needed
    DoExport::init_ooze_prevention(print, m_ooze_prevention);
    print.throw_if_canceled();
    // Collect custom seam data from all objects.
    std::function<void(void)> throw_if_canceled_func = [&print]() { print.throw_if_canceled(); };
    m_seam_placer.init(print, throw_if_canceled_func);
    // BBS: get path for change filament
    if (m_writer.multiple_extruders) {
        std::vector<Vec2d> points = get_path_of_change_filament(print);
        if (points.size() == 3) {
            travel_point_1 = points[0];
            travel_point_2 = points[1];
            travel_point_3 = points[2];
        }
    }
    // BBS: priming logic is removed, always set first extruer here.
    //if (! (has_wipe_tower && print.config().single_extruder_multi_material_priming))
    {
        // Set initial extruder only after custom start G-code.
        // Ugly hack: Do not set the initial extruder if the extruder is primed using the MMU priming towers at the edge of the print bed.
        file.write(this->set_extruder(initial_extruder_id, 0.));
    }
    // BBS: set that indicates objs with brim
    for (auto iter = print.m_brimMap.begin(); iter != print.m_brimMap.end(); ++iter) {
        if (!iter->second.empty())
            this->m_objsWithBrim.insert(iter->first);
    }
    for (auto iter = print.m_supportBrimMap.begin(); iter != print.m_supportBrimMap.end(); ++iter) {
        if (!iter->second.empty())
            this->m_objSupportsWithBrim.insert(iter->first);
    }
    if (this->m_objsWithBrim.empty() && this->m_objSupportsWithBrim.empty()) m_brim_done = true;
    // SoftFever: calib
    if (print.calib_params().mode == CalibMode::Calib_PA_Line) {
        std::string gcode;
        if ((m_config.default_acceleration.value > 0 && m_config.outer_wall_acceleration.value > 0)) {
            gcode += m_writer.set_acceleration((unsigned int)floor(m_config.outer_wall_acceleration.value + 0.5));
        }
        if (m_config.default_jerk.value > 0) {
            double jerk = m_config.outer_wall_jerk.value;
            gcode += m_writer.set_jerk_xy(jerk);
        }
        auto params = print.calib_params();
        CalibPressureAdvanceLine pa_test(this);
        auto fast_speed = CalibPressureAdvance::find_optimal_PA_speed(print.full_print_config(), pa_test.line_width(), 0.2);
        auto slow_speed = std::max(20.0, fast_speed / 10.0);
        pa_test.set_speed(fast_speed, slow_speed);
        pa_test.draw_numbers() = print.calib_params().print_numbers;
        gcode += pa_test.generate_test(params.start, params.step, std::llround(std::ceil((params.end - params.start) / params.step)));
        file.write(gcode);
    } else {
        //BBS: open spaghetti detector
        if (is_bbl_printers) {
            // if (print.config().spaghetti_detector.value)
            file.write("M981 S1 P20000 ;open spaghetti detector\n");
        }
        // Do all objects for each layer.
        if (print.config().print_sequence == PrintSequence::ByObject && !has_wipe_tower) {
            size_t finished_objects = 0;
            const PrintObject *prev_object = (*print_object_instance_sequential_active)->print_object;
            for (; print_object_instance_sequential_active != print_object_instances_ordering.end(); ++ print_object_instance_sequential_active) {
                const PrintObject &object = *(*print_object_instance_sequential_active)->print_object;
                if (&object != prev_object || tool_ordering.first_extruder() != final_extruder_id) {
                    tool_ordering = ToolOrdering(object, final_extruder_id);
                    unsigned int new_extruder_id = tool_ordering.first_extruder();
                    if (new_extruder_id == (unsigned int)-1)
                        // Skip this object.
                        continue;
                    initial_extruder_id = new_extruder_id;
                    final_extruder_id   = tool_ordering.last_extruder();
                    assert(final_extruder_id != (unsigned int)-1);
                }
                print.throw_if_canceled();
                this->set_origin(unscale((*print_object_instance_sequential_active)->shift));
                // BBS: prime extruder if extruder change happens before this object instance
                bool prime_extruder = false;
                if (finished_objects > 0) {
                    // Move to the origin position for the copy we're going to print.
                    // This happens before Z goes down to layer 0 again, so that no collision happens hopefully.
                    m_enable_cooling_markers = false; // we're not filtering these moves through CoolingBuffer
                    m_avoid_crossing_perimeters.use_external_mp_once();
                    // BBS. change tool before moving to origin point.
                    if (m_writer.need_toolchange(initial_extruder_id)) {
                        const PrintObjectConfig& object_config = object.config();
                        coordf_t initial_layer_print_height = print.config().initial_layer_print_height.value;
                        file.write(this->set_extruder(initial_extruder_id, initial_layer_print_height));
                        prime_extruder = true;
                    }
                    else {
                        file.write(this->retract());
                    }
                    file.write(m_writer.travel_to_z(m_max_layer_z));
                    file.write(this->travel_to(Point(0, 0), erNone, "move to origin position for next object"));
                    m_enable_cooling_markers = true;
                    // Disable motion planner when traveling to first object point.
                    m_avoid_crossing_perimeters.disable_once();
                    // Ff we are printing the bottom layer of an object, and we have already finished
                    // another one, set first layer temperatures. This happens before the Z move
                    // is triggered, so machine has more time to reach such temperatures.
                    m_placeholder_parser.set("current_object_idx", int(finished_objects));
                    //BBS: remove printing_by_object_gcode
                    //std::string printing_by_object_gcode = this->placeholder_parser_process("printing_by_object_gcode", print.config().printing_by_object_gcode.value, initial_extruder_id);
                    std::string printing_by_object_gcode;
                    // Set first layer bed and extruder temperatures, don't wait for it to reach the temperature.
                    this->_print_first_layer_bed_temperature(file, print, printing_by_object_gcode, initial_extruder_id, false);
                    this->_print_first_layer_extruder_temperatures(file, print, printing_by_object_gcode, initial_extruder_id, false);
                    file.writeln(printing_by_object_gcode);
                }
                // Reset the cooling buffer internal state (the current position, feed rate, accelerations).
                m_cooling_buffer->reset(this->writer().get_position());
                m_cooling_buffer->set_current_extruder(initial_extruder_id);
                // Process all layers of a single object instance (sequential mode) with a parallel pipeline:
                // Generate G-code, run the filters (vase mode, cooling buffer), run the G-code analyser
                // and export G-code into file.
                this->process_layers(print, tool_ordering, collect_layers_to_print(object), *print_object_instance_sequential_active - object.instances().data(), file, prime_extruder);
                //BBS: close powerlost recovery
                {
                    if (is_bbl_printers && m_second_layer_things_done) {
                        file.write("; close powerlost recovery\n");
                        file.write("M1003 S0\n");
                    }
                }
    #ifdef HAS_PRESSURE_EQUALIZER
                if (m_pressure_equalizer)
                    file.write(m_pressure_equalizer->process("", true));
    #endif /* HAS_PRESSURE_EQUALIZER */
                ++ finished_objects;
                // Flag indicating whether the nozzle temperature changes from 1st to 2nd layer were performed.
                // Reset it when starting another object from 1st layer.
                m_second_layer_things_done = false;
                prev_object = &object;
            }
        } else {
            // Sort layers by Z.
            // All extrusion moves with the same top layer height are extruded uninterrupted.
            std::vector<std::pair<coordf_t, std::vector<LayerToPrint>>> layers_to_print = collect_layers_to_print(print);
            // Prusa Multi-Material wipe tower.
            if (has_wipe_tower && ! layers_to_print.empty()) {
                m_wipe_tower.reset(new WipeTowerIntegration(print.config(), print.get_plate_index(), print.get_plate_origin(), * print.wipe_tower_data().priming.get(), print.wipe_tower_data().tool_changes, *print.wipe_tower_data().final_purge.get()));
                //BBS
                //file.write(m_writer.travel_to_z(initial_layer_print_height + m_config.z_offset.value, "Move to the first layer height"));
                file.write(m_writer.travel_to_z(initial_layer_print_height, "Move to the first layer height"));
    #if 0
                if (print.config().single_extruder_multi_material_priming) {
                    file.write(m_wipe_tower->prime(*this));
                    // Verify, whether the print overaps the priming extrusions.
                    BoundingBoxf bbox_print(get_print_extrusions_extents(print));
                    coordf_t twolayers_printz = ((layers_to_print.size() == 1) ? layers_to_print.front() : layers_to_print[1]).first + EPSILON;
                    for (const PrintObject *print_object : print.objects())
                        bbox_print.merge(get_print_object_extrusions_extents(*print_object, twolayers_printz));
                    bbox_print.merge(get_wipe_tower_extrusions_extents(print, twolayers_printz));
                    BoundingBoxf bbox_prime(get_wipe_tower_priming_extrusions_extents(print));
                    bbox_prime.offset(0.5f);
                    bool overlap = bbox_prime.overlap(bbox_print);
                    if (print.config().gcode_flavor == gcfMarlinLegacy || print.config().gcode_flavor == gcfMarlinFirmware) {
                        file.write(this->retract());
                        file.write("M300 S800 P500\n"); // Beep for 500ms, tone 800Hz.
                        if (overlap) {
                            // Wait for the user to remove the priming extrusions.
                            file.write("M1 Remove priming towers and click button.\n");
                        } else {
                            // Just wait for a bit to let the user check, that the priming succeeded.
                            //TODO Add a message explaining what the printer is waiting for. This needs a firmware fix.
                            file.write("M1 S10\n");
                        }
                    }
                    //BBS: only support Marlin
                    //else {
                        // This is not Marlin, M1 command is probably not supported.
                        //if (overlap) {
                        //    print.active_step_add_warning(PrintStateBase::WarningLevel::CRITICAL,
                        //        _(L("Your print is very close to the priming regions. "
                        //          "Make sure there is no collision.")));
                        //} else {
                        //    // Just continue printing, no action necessary.
                        //}
                    //}
                }
    #endif
                print.throw_if_canceled();
            }
            // Process all layers of all objects (non-sequential mode) with a parallel pipeline:
            // Generate G-code, run the filters (vase mode, cooling buffer), run the G-code analyser
            // and export G-code into file.
            this->process_layers(print, tool_ordering, print_object_instances_ordering, layers_to_print, file);
            //BBS: close powerlost recovery
            {
                if (is_bbl_printers && m_second_layer_things_done) {
                    file.write("; close powerlost recovery\n");
                    file.write("M1003 S0\n");
                }
            }
    #ifdef HAS_PRESSURE_EQUALIZER
            if (m_pressure_equalizer)
                file.write(m_pressure_equalizer->process("", true));
    #endif /* HAS_PRESSURE_EQUALIZER */
            if (m_wipe_tower)
                // Purge the extruder, pull out the active filament.
                file.write(m_wipe_tower->finalize(*this));
        }
    }
    //BBS: the last retraction
    // Write end commands to file.
    file.write(this->retract(false, true));
    // if needed, write the gcode_label_objects_end
    {
        std::string gcode;
        m_writer.add_object_change_labels(gcode);
        file.write(gcode);
    }
    file.write(m_writer.set_fan(0));
    //BBS: make sure the additional fan is closed when end
    if(m_config.auxiliary_fan.value)
        file.write(m_writer.set_additional_fan(0));
    if (is_bbl_printers) {
        //BBS: close spaghetti detector
        //Note: M981 is also used to tell xcam the last layer is finished, so we need always send it even if spaghetti option is disabled.
        //if (print.config().spaghetti_detector.value)
        file.write("M981 S0 P20000 ; close spaghetti detector\n");
    }
    // adds tag for processor
    file.write_format(";%s%s\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Role).c_str(), ExtrusionEntity::role_to_string(erCustom).c_str());
    // Process filament-specific gcode in extruder order.
    {
        DynamicConfig config;
        config.set_key_value("layer_num", new ConfigOptionInt(m_layer_index));
        //BBS
        //config.set_key_value("layer_z",   new ConfigOptionFloat(m_writer.get_position()(2) - m_config.z_offset.value));
        config.set_key_value("layer_z",   new ConfigOptionFloat(m_writer.get_position()(2)));
        config.set_key_value("max_layer_z", new ConfigOptionFloat(m_max_layer_z));
        if (print.config().single_extruder_multi_material) {
            // Process the filament_end_gcode for the active filament only.
            int extruder_id = m_writer.extruder()->id();
            config.set_key_value("filament_extruder_id", new ConfigOptionInt(extruder_id));
            file.writeln(this->placeholder_parser_process("filament_end_gcode", print.config().filament_end_gcode.get_at(extruder_id), extruder_id, &config));
        } else {
            for (const std::string &end_gcode : print.config().filament_end_gcode.values) {
                int extruder_id = (unsigned int)(&end_gcode - &print.config().filament_end_gcode.values.front());
                config.set_key_value("filament_extruder_id", new ConfigOptionInt(extruder_id));
                file.writeln(this->placeholder_parser_process("filament_end_gcode", end_gcode, extruder_id, &config));
            }
        }
        file.writeln(this->placeholder_parser_process("machine_end_gcode", print.config().machine_end_gcode, m_writer.extruder()->id(), &config));
    }
    file.write(m_writer.update_progress(m_layer_count, m_layer_count, true)); // 100%
    file.write(m_writer.postamble());
    // adds tags for time estimators
    file.write_format(";%s\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Last_Line_M73_Placeholder).c_str());
    file.write_format("; EXECUTABLE_BLOCK_END\n\n");
    print.throw_if_canceled();
    // Get filament stats.
    file.write(DoExport::update_print_stats_and_format_filament_stats(
      // Const inputs
        has_wipe_tower, print.wipe_tower_data(),
        m_writer.extruders(),
        // Modifies
        print.m_print_statistics));
    if (!is_bbl_printers) {
        file.write_format("; total filament used [g] = %.2lf\n",
            print.m_print_statistics.total_weight);
        file.write_format("; total filament cost = %.2lf\n",
            print.m_print_statistics.total_cost);
        if (print.m_print_statistics.total_toolchanges > 0)
            file.write_format("; total filament change = %i\n",
                print.m_print_statistics.total_toolchanges);
        file.write_format("; total layers count = %i\n", m_layer_count);
        file.write_format(
            ";%s\n",
            GCodeProcessor::reserved_tag(
                GCodeProcessor::ETags::Estimated_Printing_Time_Placeholder)
            .c_str());
      file.write("\n");
      file.write("; CONFIG_BLOCK_START\n");
      std::string full_config;
      append_full_config(print, full_config);
      if (!full_config.empty())
        file.write(full_config);
      // SoftFever: write compatiple info
      int first_layer_bed_temperature = get_bed_temperature(0, true, print.config().curr_bed_type);
      file.write_format("; first_layer_bed_temperature = %d\n", first_layer_bed_temperature);
      file.write_format("; bed_shape = %s\n", print.full_print_config().opt_serialize("printable_area").c_str());
      file.write_format("; first_layer_temperature = %d\n", print.config().nozzle_temperature_initial_layer.get_at(0));
      file.write_format("; first_layer_height = %.3f\n", print.config().initial_layer_print_height.value);
        //SF TODO
//      file.write_format("; variable_layer_height = %d\n", print.ad.adaptive_layer_height ? 1 : 0);
      file.write("; CONFIG_BLOCK_END\n\n");
    }
    file.write("\n");
    print.throw_if_canceled();
}
References _, _print_first_layer_bed_temperature(), _print_first_layer_extruder_temperatures(), Slic3r::GCodeWriter::add_object_change_labels(), Slic3r::ToolOrdering::all_extruders(), append_full_config(), apply_print_config(), Slic3r::ToolOrdering::assign_custom_gcodes(), Slic3r::ByObject, Slic3r::Calib_None, Slic3r::Calib_PA_Line, Slic3r::Print::calib_params(), Slic3r::chain_print_object_instances(), Slic3r::DynamicConfig::clear(), collect_layers_to_print(), config(), Slic3r::PrintObject::config(), Slic3r::Print::config(), Slic3r::PlaceholderParser::config_writable(), count, Slic3r::Print::default_region_config(), Slic3r::AvoidCrossingPerimeters::disable_once(), Slic3r::CalibPressureAdvanceLine::draw_numbers(), EPSILON, Slic3r::erCustom, Slic3r::erNone, Slic3r::GCodeProcessor::Estimated_Printing_Time_Placeholder, Slic3r::DoExport::export_thumbnails_to_file(), Slic3r::GCodeWriter::extruder(), Slic3r::GCodeWriter::extruders(), Slic3r::Print::extruders(), Slic3r::WipeTowerData::final_purge, Slic3r::CalibPressureAdvance::find_optimal_PA_speed(), Slic3r::ToolOrdering::first_extruder(), Slic3r::Print::first_layer_convex_hull(), Slic3r::GCodeProcessor::First_Line_M73_Placeholder, floor(), Slic3r::PrintRegion::flow(), Slic3r::frExternalPerimeter, Slic3r::frInfill, Slic3r::ConstVectorOfPtrsAdaptor< T >::front(), Slic3r::frPerimeter, Slic3r::frSolidInfill, Slic3r::frTopSolidInfill, Slic3r::PrintBase::full_print_config(), Slic3r::gcfKlipper, Slic3r::gcfMarlinFirmware, Slic3r::gcfMarlinLegacy, Slic3r::CalibPressureAdvanceLine::generate_test(), Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::get_bed_temp_1st_layer_key(), Slic3r::get_bed_temp_key(), get_bed_temperature(), Slic3r::GCodeProcessor::get_gcode_last_filament(), Slic3r::get_path_of_change_filament(), Slic3r::PrintBase::get_plate_index(), Slic3r::PrintBase::get_plate_name(), Slic3r::Print::get_plate_origin(), Slic3r::GCodeWriter::get_position(), Slic3r::get_print_extrusions_extents(), Slic3r::get_print_object_extrusions_extents(), Slic3r::Print::get_print_region(), Slic3r::get_wipe_tower_extrusions_extents(), Slic3r::get_wipe_tower_priming_extrusions_extents(), Slic3r::GCodeWriter::get_xy_offset(), Slic3r::Print::has_support_material(), Slic3r::ToolOrdering::has_wipe_tower(), Slic3r::Print::has_wipe_tower(), Slic3r::header_slic3r_generated(), Slic3r::Extruder::id(), Slic3r::SeamPlacer::init(), Slic3r::DoExport::init_gcode_processor(), Slic3r::DoExport::init_ooze_prevention(), int, Slic3r::Print::is_BBL_printer(), L, Slic3r::ToolOrdering::last_extruder(), Slic3r::GCodeProcessor::Last_Line_M73_Placeholder, layer(), Slic3r::layer_height(), Slic3r::ToolOrdering::layer_tools(), Slic3r::CalibPressureAdvanceLine::line_width(), Slic3r::Utils::local_timestamp(), m_avoid_crossing_perimeters, m_brim_done, Slic3r::Print::m_brimMap, m_calib_config, m_config, m_cooling_buffer, m_enable_cooling_markers, m_enable_exclude_object, m_enable_extrusion_role_markers, m_fan_mover, m_is_overhang_fan_on, m_is_supp_interface_fan_on, m_label_objects_ids, m_last_height, m_last_layer_z, m_last_width, m_layer_count, m_layer_index, m_max_layer_z, m_objSupportsWithBrim, m_objsWithBrim, m_ooze_prevention, m_placeholder_parser, m_placeholder_parser_context, Slic3r::Print::m_print_statistics, m_processor, m_seam_placer, m_second_layer_things_done, m_silent_time_estimator_enabled, m_spiral_vase, m_start_gcode_filament, Slic3r::Print::m_supportBrimMap, m_wipe_tower, m_writer, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::Flow::mm3_per_mm(), Slic3r::Calib_Params::mode, Slic3r::GCodeWriter::multiple_extruders, Slic3r::GCodeWriter::need_toolchange(), Slic3r::Print::num_object_instances(), Slic3r::Print::num_print_regions(), Slic3r::WipeTowerData::number_of_toolchanges, Slic3r::Print::objects(), Slic3r::BoundingBoxBase< PointClass >::offset(), Slic3r::ConfigBase::opt_serialize(), Slic3r::ConfigBase::option(), Slic3r::outer_wall_line_width(), Slic3r::BoundingBoxBase< PointClass >::overlap(), Slic3r::PrintBase::placeholder_parser(), placeholder_parser_process(), Slic3r::MultiPoint::points, Slic3r::GCodeWriter::postamble(), preamble(), Slic3r::WipeTowerData::priming, print_machine_envelope(), Slic3r::Calib_Params::print_numbers, Slic3r::Layer::print_z, Slic3r::PrintObjectConfig, process_layers(), PROFILE_FUNC, Slic3r::GCodeProcessor::reserved_tag(), retract(), Slic3r::PlaceholderParser::ContextData::rng, Slic3r::GCodeProcessor::Role, Slic3r::ExtrusionEntity::role_to_string(), Slic3r::PlaceholderParser::set(), Slic3r::GCodeWriter::set_acceleration(), Slic3r::GCodeWriter::set_additional_fan(), Slic3r::GCodeWriter::set_current_position_clear(), set_extruder(), set_extruders(), Slic3r::GCodeWriter::set_fan(), Slic3r::GCodeWriter::set_is_bbl_machine(), Slic3r::GCodeWriter::set_jerk_xy(), set_object_info(), set_origin(), Slic3r::CalibPressureAdvanceLine::set_speed(), Slic3r::BoundingBoxBase< PointClass >::size(), Slic3r::MultiPoint::size(), Slic3r::sort_object_instances_by_model_order(), Slic3r::support_material_flow(), Slic3r::PrintBase::throw_if_canceled(), Slic3r::WipeTowerData::tool_changes, Slic3r::Print::tool_ordering(), Slic3r::PrintStatistics::total_cost, Slic3r::GCodeProcessor::Total_Layer_Number_Placeholder, Slic3r::PrintStatistics::total_toolchanges, Slic3r::PrintStatistics::total_weight, Slic3r::Print::translate_to_print_space(), Slic3r::travel_point_1, Slic3r::travel_point_2, Slic3r::travel_point_3, travel_to(), Slic3r::GCodeWriter::travel_to_z(), Slic3r::unscale(), Slic3r::PrintBase::update_object_placeholders(), Slic3r::DoExport::update_print_stats_and_format_filament_stats(), Slic3r::GCodeWriter::update_progress(), Slic3r::PlaceholderParser::update_timestamp(), Slic3r::AvoidCrossingPerimeters::use_external_mp_once(), Slic3r::ConfigOptionVector< T >::values, void(), Slic3r::Flow::width(), Slic3r::Print::wipe_tower_data(), WipeTowerIntegration, Slic3r::GCode::GCodeOutputStream::write(), Slic3r::GCode::GCodeOutputStream::write_format(), Slic3r::GCode::GCodeOutputStream::writeln(), and writer().
Referenced by do_export().
_encode_label_ids_to_base64()
std::string Slic3r::GCode::_encode_label_ids_to_base64 (std::vector< size_t > ids) private
{
    assert(m_label_objects_ids.size() < 64);
    uint64_t bitset = 0;
    for (size_t id : ids) {
        auto index = std::lower_bound(m_label_objects_ids.begin(), m_label_objects_ids.end(), id);
        if (index != m_label_objects_ids.end() && *index == id)
            bitset |= (1ull << (index - m_label_objects_ids.begin()));
        else
            throw Slic3r::LogicError("Unknown label object id!");
    }
    if (bitset == 0)
        throw Slic3r::LogicError("Label object id error!");
    return encodeBase64(bitset);
}
References Slic3r::encodeBase64().
_extrude()
std::string Slic3r::GCode::_extrude (const ExtrusionPath & path, std::string description = "", double speed = -1) private
{
    std::string gcode;
    if (is_bridge(path.role()))
        description += " (bridge)";
    // go to first point of extrusion path
    //BBS: path.first_point is 2D point. But in lazy raise case, lift z is done in travel_to function.
    //Add m_need_change_layer_lift_z when change_layer in case of no lift if m_last_pos is equal to path.first_point() by chance
    if (!m_last_pos_defined || m_last_pos != path.first_point() || m_need_change_layer_lift_z) {
        gcode += this->travel_to(
            path.first_point(),
            path.role(),
            "move to first " + description + " point"
        );
        m_need_change_layer_lift_z = false;
    }
    // if needed, write the gcode_label_objects_end then gcode_label_objects_start
    // should be already done by travel_to, but just in case
    m_writer.add_object_change_labels(gcode);
    // compensate retraction
    gcode += this->unretract();
    m_config.apply(m_calib_config);
    // adjust acceleration
    if (m_config.default_acceleration.value > 0) {
        double acceleration;
        if (this->on_first_layer() && m_config.initial_layer_acceleration.value > 0) {
            acceleration = m_config.initial_layer_acceleration.value;
#if 0
        } else if (this->object_layer_over_raft() && m_config.first_layer_acceleration_over_raft.value > 0) {
            acceleration = m_config.first_layer_acceleration_over_raft.value;
#endif
        } else if (m_config.get_abs_value("bridge_acceleration") > 0 && is_bridge(path.role())) {
            acceleration = m_config.get_abs_value("bridge_acceleration");
        } else if (m_config.get_abs_value("sparse_infill_acceleration") > 0 && (path.role() == erInternalInfill)) {
            acceleration = m_config.get_abs_value("sparse_infill_acceleration");
        } else if (m_config.get_abs_value("internal_solid_infill_acceleration") > 0 && (path.role() == erSolidInfill)) {
            acceleration = m_config.get_abs_value("internal_solid_infill_acceleration");
        } else if (m_config.outer_wall_acceleration.value > 0 && is_external_perimeter(path.role())) {
            acceleration = m_config.outer_wall_acceleration.value;
        } else if (m_config.inner_wall_acceleration.value > 0 && is_internal_perimeter(path.role())) {
            acceleration = m_config.inner_wall_acceleration.value;
        } else if (m_config.top_surface_acceleration.value > 0 && is_top_surface(path.role())) {
            acceleration = m_config.top_surface_acceleration.value;
        } else {
            acceleration = m_config.default_acceleration.value;
        }
        gcode += m_writer.set_acceleration((unsigned int)floor(acceleration + 0.5));
    }
    // adjust X Y jerk
    if (m_config.default_jerk.value > 0) {
        double jerk;
        if (this->on_first_layer() && m_config.initial_layer_jerk.value > 0) {
            jerk = m_config.initial_layer_jerk.value;
        } else if (m_config.outer_wall_jerk.value > 0 && is_external_perimeter(path.role())) {
             jerk = m_config.outer_wall_jerk.value;
        } else if (m_config.inner_wall_jerk.value > 0 && is_internal_perimeter(path.role())) {
            jerk = m_config.inner_wall_jerk.value;
        } else if (m_config.top_surface_jerk.value > 0 && is_top_surface(path.role())) {
            jerk = m_config.top_surface_jerk.value;
        } else if (m_config.infill_jerk.value > 0 && is_infill(path.role())) {
            jerk = m_config.infill_jerk.value;
        }
        else {
            jerk = m_config.default_jerk.value;
        }
        gcode += m_writer.set_jerk_xy(jerk);
    }
    // calculate extrusion length per distance unit
    auto _mm3_per_mm = path.mm3_per_mm * this->config().print_flow_ratio;
    if (path.role() == erTopSolidInfill)
        _mm3_per_mm *= m_config.top_solid_infill_flow_ratio;
    else if (path.role() == erBottomSurface)
        _mm3_per_mm *= m_config.bottom_solid_infill_flow_ratio;
    double e_per_mm = m_writer.extruder()->e_per_mm3() * _mm3_per_mm;
    double min_speed = double(m_config.slow_down_min_speed.get_at(m_writer.extruder()->id()));
    // set speed
    if (speed == -1) {
        int overhang_degree = path.get_overhang_degree();
        if (path.role() == erPerimeter) {
            speed = m_config.get_abs_value("inner_wall_speed");
            if (m_config.overhang_speed_classic.value && m_config.enable_overhang_speed.value && overhang_degree > 0 &&
                overhang_degree <= 5) {
                double new_speed = m_config.get_abs_value(overhang_speed_key_map[overhang_degree].c_str());
                speed = new_speed == 0.0 ? speed : new_speed;
            }
        } else if (path.role() == erExternalPerimeter) {
            speed = m_config.get_abs_value("outer_wall_speed");
            if (m_config.overhang_speed_classic.value && m_config.enable_overhang_speed.value &&
                overhang_degree > 0 && overhang_degree <= 5) {
                double new_speed = m_config.get_abs_value(overhang_speed_key_map[overhang_degree].c_str());
                speed = new_speed == 0.0 ? speed : new_speed;
            }
        }
        else if(path.role() == erInternalBridgeInfill) {
            speed = m_config.get_abs_value("internal_bridge_speed");
        } else if (path.role() == erOverhangPerimeter || path.role() == erSupportTransition || path.role() == erBridgeInfill) {
            speed = m_config.get_abs_value("bridge_speed");
        } else if (path.role() == erInternalInfill) {
            speed = m_config.get_abs_value("sparse_infill_speed");
        } else if (path.role() == erSolidInfill) {
            speed = m_config.get_abs_value("internal_solid_infill_speed");
        } else if (path.role() == erTopSolidInfill) {
            speed = m_config.get_abs_value("top_surface_speed");
        } else if (path.role() == erIroning) {
            speed = m_config.get_abs_value("ironing_speed");
        } else if (path.role() == erBottomSurface) {
            speed = m_config.get_abs_value("initial_layer_infill_speed");
        } else if (path.role() == erGapFill) {
            speed = m_config.get_abs_value("gap_infill_speed");
        }
        else if (path.role() == erSupportMaterial ||
                 path.role() == erSupportMaterialInterface) {
            const double  support_speed = m_config.support_speed.value;
            const double  support_interface_speed = m_config.get_abs_value("support_interface_speed");
            speed = (path.role() == erSupportMaterial) ? support_speed : support_interface_speed;
        } else {
            throw Slic3r::InvalidArgument("Invalid speed");
        }
    }
    //BBS: if not set the speed, then use the filament_max_volumetric_speed directly
    if (speed == 0)
        speed = EXTRUDER_CONFIG(filament_max_volumetric_speed) / _mm3_per_mm;
    if (this->on_first_layer()) {
        //BBS: for solid infill of initial layer, speed can be higher as long as
        //wall lines have be attached
        if (path.role() != erBottomSurface)
            speed = m_config.get_abs_value("initial_layer_speed");
    }
    else if(m_config.slow_down_layers > 1){
        const auto _layer = layer_id() + 1;
        if (_layer > 0 && _layer < m_config.slow_down_layers) {
            const auto first_layer_speed =
                is_perimeter(path.role())
                    ? m_config.get_abs_value("initial_layer_speed")
                    : m_config.get_abs_value("initial_layer_infill_speed");
            if (first_layer_speed < speed) {
                speed = std::min(
                    speed,
                    Slic3r::lerp(first_layer_speed, speed,
                                 (double)_layer / m_config.slow_down_layers));
            }
        }
    }
    // Override skirt speed if set
    if (path.role() == erSkirt) {
        const double skirt_speed = m_config.get_abs_value("skirt_speed");
        if (skirt_speed > 0.0)
        speed = skirt_speed;
    }
    //BBS: remove this config
    //else if (this->object_layer_over_raft())
    //    speed = m_config.get_abs_value("first_layer_speed_over_raft", speed);
    //if (m_config.max_volumetric_speed.value > 0) {
    //    // cap speed with max_volumetric_speed anyway (even if user is not using autospeed)
    //    speed = std::min(
    //        speed,
    //        m_config.max_volumetric_speed.value / _mm3_per_mm
    //    );
    //}
    if (EXTRUDER_CONFIG(filament_max_volumetric_speed) > 0) {
        // cap speed with max_volumetric_speed anyway (even if user is not using autospeed)
        speed = std::min(
            speed,
            EXTRUDER_CONFIG(filament_max_volumetric_speed) / _mm3_per_mm
        );
    }
    bool variable_speed = false;
    std::vector<ProcessedPoint> new_points {};
    if (m_config.enable_overhang_speed && !m_config.overhang_speed_classic && !this->on_first_layer() &&
        (is_bridge(path.role()) || is_perimeter(path.role()))) {
        ConfigOptionPercents overhang_overlap_levels({75, 50, 25, 13,12.99,0});
        ConfigOptionFloatsOrPercents dynamic_overhang_speeds(
            {(m_config.get_abs_value("overhang_1_4_speed") < 0.5)
                 ? FloatOrPercent{100, true}
                 : FloatOrPercent{m_config.get_abs_value("overhang_1_4_speed"), false},
             (m_config.get_abs_value("overhang_2_4_speed") < 0.5)
                 ? FloatOrPercent{100, true}
                 : FloatOrPercent{m_config.get_abs_value("overhang_2_4_speed"), false},
             (m_config.get_abs_value("overhang_3_4_speed") < 0.5)
                 ? FloatOrPercent{100, true}
                 : FloatOrPercent{m_config.get_abs_value("overhang_3_4_speed"), false},
             (m_config.get_abs_value("overhang_4_4_speed") < 0.5)
                 ? FloatOrPercent{100, true}
                 : FloatOrPercent{m_config.get_abs_value("overhang_4_4_speed"), false},
             FloatOrPercent{m_config.get_abs_value("bridge_speed"), false},
             FloatOrPercent{m_config.get_abs_value("bridge_speed"), false}});
        new_points = m_extrusion_quality_estimator.estimate_extrusion_quality(
            path, overhang_overlap_levels, dynamic_overhang_speeds, m_config.get_abs_value("outer_wall_speed"), speed);
        variable_speed = std::any_of(new_points.begin(), new_points.end(),
                                     [speed](const ProcessedPoint &p) { return p.speed != speed; });
    }
    double F = speed * 60;  // convert mm/sec to mm/min
    // extrude arc or line
    if (m_enable_extrusion_role_markers) {
        if (path.role() != m_last_extrusion_role) {
            char buf[32];
            sprintf(buf, ";_EXTRUSION_ROLE:%d\n", int(path.role()));
            gcode += buf;
      }
    }
    m_last_extrusion_role = path.role();
    // adds processor tags and updates processor tracking data
    // PrusaMultiMaterial::Writer may generate GCodeProcessor::Height_Tag lines without updating m_last_height
    // so, if the last role was erWipeTower we force export of GCodeProcessor::Height_Tag lines
    bool last_was_wipe_tower = (m_last_processor_extrusion_role == erWipeTower);
    char buf[64];
    assert(is_decimal_separator_point());
    if (path.role() != m_last_processor_extrusion_role) {
        m_last_processor_extrusion_role = path.role();
        sprintf(buf, ";%s%s\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Role).c_str(), ExtrusionEntity::role_to_string(m_last_processor_extrusion_role).c_str());
        gcode += buf;
    }
    if (last_was_wipe_tower || m_last_width != path.width) {
        m_last_width = path.width;
        sprintf(buf, ";%s%g\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Width).c_str(), m_last_width);
        gcode += buf;
    }
#if ENABLE_GCODE_VIEWER_DATA_CHECKING
    if (last_was_wipe_tower || (m_last_mm3_per_mm != path.mm3_per_mm)) {
        m_last_mm3_per_mm = path.mm3_per_mm;
        sprintf(buf, ";%s%f\n", GCodeProcessor::Mm3_Per_Mm_Tag.c_str(), m_last_mm3_per_mm);
        gcode += buf;
    }
#endif // ENABLE_GCODE_VIEWER_DATA_CHECKING
    if (last_was_wipe_tower || std::abs(m_last_height - path.height) > EPSILON) {
        m_last_height = path.height;
        sprintf(buf, ";%s%g\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Height).c_str(), m_last_height);
        gcode += buf;
    }
    auto overhang_fan_threshold = EXTRUDER_CONFIG(overhang_fan_threshold);
    auto enable_overhang_bridge_fan = EXTRUDER_CONFIG(enable_overhang_bridge_fan);
    auto supp_interface_fan_speed = EXTRUDER_CONFIG(support_material_interface_fan_speed);
    //    { "0%", Overhang_threshold_none },
    //    { "5%", Overhang_threshold_1_4 },
    //    { "25%", Overhang_threshold_2_4 },
    //    { "50%", Overhang_threshold_3_4 },
    //    { "75%", Overhang_threshold_4_4 },
    //    { "95%", Overhang_threshold_bridge }
    auto check_overhang_fan = [&overhang_fan_threshold](float overlap) {
      switch (overhang_fan_threshold) {
      case (int)Overhang_threshold_1_4:
        return overlap <= 0.95f;
        break;
      case (int)Overhang_threshold_2_4:
        return overlap <= 0.75f;
        break;
      case (int)Overhang_threshold_3_4:
        return overlap <= 0.5f;
        break;
      case (int)Overhang_threshold_4_4:
        return overlap <= 0.25f;
        break;
      case (int)Overhang_threshold_bridge:
        return overlap <= 0.1f;
        break;
      case (int)Overhang_threshold_none:
        return true;
        break;
      default:
        return false;
      }
    };
    std::string comment;
    if (m_enable_cooling_markers) {
        comment = ";_EXTRUDE_SET_SPEED";
        if (is_external_perimeter(path.role()))
            comment += ";_EXTERNAL_PERIMETER";
    }
    if (!variable_speed) {
        // F is mm per minute.
        gcode += m_writer.set_speed(F, "", comment);
        double path_length = 0.;
        {
            if (m_enable_cooling_markers) {
                if (enable_overhang_bridge_fan) {
                    // BBS: Overhang_threshold_none means Overhang_threshold_1_4 and forcing cooling for all external
                    // perimeter
                    int overhang_threshold = overhang_fan_threshold == Overhang_threshold_none ? Overhang_threshold_none
                    : overhang_fan_threshold - 1;
                    if ((overhang_fan_threshold == Overhang_threshold_none && is_perimeter(path.role())) ||
                        (path.get_overhang_degree() > overhang_threshold || is_bridge(path.role()))) {
                        if (!m_is_overhang_fan_on) {
                            gcode += ";_OVERHANG_FAN_START\n";
                            m_is_overhang_fan_on = true;
                        }
                    } else {
                        if (m_is_overhang_fan_on) {
                            m_is_overhang_fan_on = false;
                            gcode += ";_OVERHANG_FAN_END\n";
                        }
                    }
                }
                if (supp_interface_fan_speed >= 0 && path.role() == erSupportMaterialInterface) {
                    if (!m_is_supp_interface_fan_on) {
                        gcode += ";_SUPP_INTERFACE_FAN_START\n";
                        m_is_supp_interface_fan_on = true;
                    }
                } else {
                    if (m_is_supp_interface_fan_on) {
                        gcode += ";_SUPP_INTERFACE_FAN_END\n";
                        m_is_supp_interface_fan_on = false;
                    }
                }
            }
            // BBS: use G1 if not enable arc fitting or has no arc fitting result or in spiral_mode mode
            // Attention: G2 and G3 is not supported in spiral_mode mode
            if (!m_config.enable_arc_fitting || path.polyline.fitting_result.empty() || m_config.spiral_mode) {
                for (const Line& line : path.polyline.lines()) {
                    const double line_length = line.length() * SCALING_FACTOR;
                    path_length += line_length;
                    gcode += m_writer.extrude_to_xy(
                        this->point_to_gcode(line.b),
                        e_per_mm * line_length,
                        GCodeWriter::full_gcode_comment ? description : "", path.is_force_no_extrusion());
                }
            } else {
                // BBS: start to generate gcode from arc fitting data which includes line and arc
                const std::vector<PathFittingData>& fitting_result = path.polyline.fitting_result;
                for (size_t fitting_index = 0; fitting_index < fitting_result.size(); fitting_index++) {
                    switch (fitting_result[fitting_index].path_type) {
                    case EMovePathType::Linear_move: {
                        size_t start_index = fitting_result[fitting_index].start_point_index;
                        size_t end_index = fitting_result[fitting_index].end_point_index;
                        for (size_t point_index = start_index + 1; point_index < end_index + 1; point_index++) {
                            const Line line = Line(path.polyline.points[point_index - 1], path.polyline.points[point_index]);
                            const double line_length = line.length() * SCALING_FACTOR;
                            path_length += line_length;
                            gcode += m_writer.extrude_to_xy(
                                this->point_to_gcode(line.b),
                                e_per_mm * line_length,
                                GCodeWriter::full_gcode_comment ? description : "", path.is_force_no_extrusion());
                        }
                        break;
                    }
                    case EMovePathType::Arc_move_cw:
                    case EMovePathType::Arc_move_ccw: {
                        const ArcSegment& arc = fitting_result[fitting_index].arc_data;
                        const double arc_length = fitting_result[fitting_index].arc_data.length * SCALING_FACTOR;
                        const Vec2d center_offset = this->point_to_gcode(arc.center) - this->point_to_gcode(arc.start_point);
                        path_length += arc_length;
                        gcode += m_writer.extrude_arc_to_xy(
                            this->point_to_gcode(arc.end_point),
                            center_offset,
                            e_per_mm * arc_length,
                            arc.direction == ArcDirection::Arc_Dir_CCW,
                            GCodeWriter::full_gcode_comment ? description : "", path.is_force_no_extrusion());
                        break;
                    }
                    default:
                        // BBS: should never happen that a empty path_type has been stored
                        assert(0);
                        break;
                    }
                }
            }
        }
    } else {
        double last_set_speed = std::max((float)EXTRUDER_CONFIG(slow_down_min_speed), new_points[0].speed) * 60.0;
        gcode += m_writer.set_speed(last_set_speed, "", comment);
        Vec2d prev = this->point_to_gcode_quantized(new_points[0].p);
        bool pre_fan_enabled = false;
        bool cur_fan_enabled = false;
        if( m_enable_cooling_markers && enable_overhang_bridge_fan)
            pre_fan_enabled = check_overhang_fan(new_points[0].overlap);
        for (size_t i = 1; i < new_points.size(); i++) {
            const ProcessedPoint &processed_point = new_points[i];
            Vec2d p = this->point_to_gcode_quantized(processed_point.p);
            if (m_enable_cooling_markers) {
                if (enable_overhang_bridge_fan) {
                    cur_fan_enabled = check_overhang_fan(processed_point.overlap);
                    if (is_bridge(path.role()) ||
                        (is_perimeter(path.role()) &&
                         pre_fan_enabled && pre_fan_enabled)) {
                        if (!m_is_overhang_fan_on) {
                            gcode += ";_OVERHANG_FAN_START\n";
                            m_is_overhang_fan_on = true;
                        }
                    } else {
                        if (m_is_overhang_fan_on) {
                            m_is_overhang_fan_on = false;
                            gcode += ";_OVERHANG_FAN_END\n";
                        }
                    }
                    pre_fan_enabled = cur_fan_enabled;
                }
                if (supp_interface_fan_speed >= 0 && path.role() == erSupportMaterialInterface) {
                    if (!m_is_supp_interface_fan_on) {
                        gcode += ";_SUPP_INTERFACE_FAN_START\n";
                        m_is_supp_interface_fan_on = true;
                    }
                } else {
                    if (m_is_supp_interface_fan_on) {
                        gcode += ";_SUPP_INTERFACE_FAN_END\n";
                        m_is_supp_interface_fan_on = false;
                    }
                }
            }
            const double line_length = (p - prev).norm();
            double new_speed = std::max((float)EXTRUDER_CONFIG(slow_down_min_speed), processed_point.speed) * 60.0;
            if (last_set_speed != new_speed) {
                gcode += m_writer.set_speed(new_speed, "", comment);
                last_set_speed = new_speed;
            }
            gcode +=
                m_writer.extrude_to_xy(p, e_per_mm * line_length, GCodeWriter::full_gcode_comment ? description : "");
            prev = p;
        }
    }
    if (m_enable_cooling_markers) {
            gcode += ";_EXTRUDE_END\n";
    }
    if (path.role() != ExtrusionRole::erGapFill) {
      m_last_notgapfill_extrusion_role = path.role();
    }
    this->set_last_pos(path.last_point());
    return gcode;
}
References Slic3r::Line::b, Slic3r::Circle::center, Slic3r::ArcSegment::direction, Slic3r::enable_overhang_bridge_fan(), Slic3r::ArcSegment::end_point, EPSILON, Slic3r::erBottomSurface, Slic3r::erBridgeInfill, Slic3r::erExternalPerimeter, Slic3r::erGapFill, Slic3r::erInternalBridgeInfill, Slic3r::erInternalInfill, Slic3r::erIroning, Slic3r::erOverhangPerimeter, Slic3r::erPerimeter, Slic3r::erSkirt, Slic3r::erSolidInfill, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erTopSolidInfill, Slic3r::erWipeTower, EXTRUDER_CONFIG, Slic3r::F, Slic3r::ExtrusionPath::first_point(), Slic3r::Polyline::fitting_result, floor(), Slic3r::ExtrusionPath::get_overhang_degree(), Slic3r::ExtrusionPath::height, Slic3r::is_bridge(), Slic3r::is_decimal_separator_point(), Slic3r::is_external_perimeter(), Slic3r::ExtrusionPath::is_force_no_extrusion(), Slic3r::is_infill(), Slic3r::is_internal_perimeter(), Slic3r::is_perimeter(), Slic3r::is_top_surface(), Slic3r::ExtrusionPath::last_point(), Slic3r::ArcSegment::length, Slic3r::Line::length(), Slic3r::lerp(), Slic3r::Polyline::lines(), Slic3r::ExtrusionPath::mm3_per_mm, Slic3r::overhang_fan_threshold(), Slic3r::overhang_speed_key_map, Slic3r::Overhang_threshold_1_4, Slic3r::Overhang_threshold_2_4, Slic3r::Overhang_threshold_3_4, Slic3r::Overhang_threshold_4_4, Slic3r::Overhang_threshold_bridge, Slic3r::Overhang_threshold_none, Slic3r::ProcessedPoint::overlap, Slic3r::ProcessedPoint::p, Slic3r::MultiPoint::points, Slic3r::ExtrusionPath::polyline, Slic3r::ExtrusionPath::role(), SCALING_FACTOR, Slic3r::slow_down_min_speed(), Slic3r::ProcessedPoint::speed, Slic3r::ArcSegment::start_point, and Slic3r::ExtrusionPath::width.
_print_first_layer_bed_temperature()
void Slic3r::GCode::_print_first_layer_bed_temperature (GCodeOutputStream & file, Print & print, const std::string & gcode, unsigned int first_printing_extruder_id, bool wait) private
{
    // Initial bed temperature based on the first extruder.
    // BBS
    std::vector<int> temps_per_bed;
    int bed_temp = get_bed_temperature(first_printing_extruder_id, true, print.config().curr_bed_type);
    // Is the bed temperature set by the provided custom G-code?
    int  temp_by_gcode     = -1;
    bool temp_set_by_gcode = custom_gcode_sets_temperature(gcode, 140, 190, false, temp_by_gcode);
    // BBS
#if 0
    if (temp_set_by_gcode && temp_by_gcode >= 0 && temp_by_gcode < 1000)
        temp = temp_by_gcode;
#endif
    // Always call m_writer.set_bed_temperature() so it will set the internal "current" state of the bed temp as if
    // the custom start G-code emited these.
    std::string set_temp_gcode = m_writer.set_bed_temperature(bed_temp, wait);
    if (! temp_set_by_gcode)
        file.write(set_temp_gcode);
}
References Slic3r::Print::config(), Slic3r::custom_gcode_sets_temperature(), and Slic3r::GCode::GCodeOutputStream::write().
Referenced by _do_export().
_print_first_layer_extruder_temperatures()
void Slic3r::GCode::_print_first_layer_extruder_temperatures (GCodeOutputStream & file, Print & print, const std::string & gcode, unsigned int first_printing_extruder_id, bool wait) private
{
    // Is the bed temperature set by the provided custom G-code?
    int  temp_by_gcode = -1;
    bool include_g10   = print.config().gcode_flavor == gcfRepRapFirmware;
    if (custom_gcode_sets_temperature(gcode, 104, 109, include_g10, temp_by_gcode)) {
        // Set the extruder temperature at m_writer, but throw away the generated G-code as it will be written with the custom G-code.
        int temp = print.config().nozzle_temperature_initial_layer.get_at(first_printing_extruder_id);
        if (temp_by_gcode >= 0 && temp_by_gcode < 1000)
            temp = temp_by_gcode;
        m_writer.set_temperature(temp, wait, first_printing_extruder_id);
    } else {
        // Custom G-code does not set the extruder temperature. Do it now.
        if (print.config().single_extruder_multi_material.value) {
            // Set temperature of the first printing extruder only.
            int temp = print.config().nozzle_temperature_initial_layer.get_at(first_printing_extruder_id);
            if (temp > 0)
                file.write(m_writer.set_temperature(temp, wait, first_printing_extruder_id));
        } else {
            // Set temperatures of all the printing extruders.
            for (unsigned int tool_id : print.extruders()) {
                int temp = print.config().nozzle_temperature_initial_layer.get_at(tool_id);
                if (print.config().ooze_prevention.value)
                    temp += print.config().standby_temperature_delta.value;
                if (temp > 0)
                    file.write(m_writer.set_temperature(temp, wait, tool_id));
            }
        }
    }
}
References Slic3r::Print::config(), Slic3r::custom_gcode_sets_temperature(), Slic3r::Print::extruders(), Slic3r::gcfRepRapFirmware, and Slic3r::GCode::GCodeOutputStream::write().
Referenced by _do_export().
append_full_config()
void Slic3r::GCode::append_full_config (const Print & print, std::string & str) static
{
    const DynamicPrintConfig &cfg = print.full_print_config();
    // Sorted list of config keys, which shall not be stored into the G-code. Initializer list.
    static constexpr auto banned_keys = {
        "compatible_printers"sv,
        "compatible_prints"sv
    };
    assert(std::is_sorted(banned_keys.begin(), banned_keys.end()));
    auto is_banned = [](const std::string &key) {
        return std::binary_search(banned_keys.begin(), banned_keys.end(), key);
    };
    std::ostringstream ss;
    for (const std::string& key : cfg.keys()) {
        if (!is_banned(key) && !cfg.option(key)->is_nil()) {
            if (key == "wipe_tower_x" || key == "wipe_tower_y") {
                ss << std::fixed << std::setprecision(3) << "; " << key << " = " << dynamic_cast<const ConfigOptionFloats*>(cfg.option(key))->get_at(print.get_plate_index()) << "\n";
            }
            else
                ss << "; " << key << " = " << cfg.opt_serialize(key) << "\n";
        }
    }
    str += ss.str();
}
References Slic3r::PrintBase::full_print_config(), Slic3r::PrintBase::get_plate_index(), Slic3r::ConfigOption::is_nil(), Slic3r::DynamicConfig::keys(), Slic3r::ConfigBase::opt_serialize(), and Slic3r::ConfigBase::option().
Referenced by _do_export().
apply_print_config()
void Slic3r::GCode::apply_print_config (const PrintConfig & print_config)
{
    m_writer.apply_print_config(print_config);
    m_config.apply(print_config);
    m_scaled_resolution = scaled<double>(print_config.resolution.value);
}
Referenced by _do_export().
change_layer()
std::string Slic3r::GCode::change_layer (coordf_t print_z, bool lazy_raise = false) private
{
    std::string gcode;
    if (m_layer_count > 0)
        // Increment a progress bar indicator.
        gcode += m_writer.update_progress(++ m_layer_index, m_layer_count);
    //BBS
    //coordf_t z = print_z + m_config.z_offset.value;  // in unscaled coordinates
    coordf_t z = print_z;  // in unscaled coordinates
    if (EXTRUDER_CONFIG(retract_when_changing_layer) && m_writer.will_move_z(z)) {
        LiftType lift_type = this->to_lift_type(ZHopType(EXTRUDER_CONFIG(z_hop_types)));
        //BBS: force to use SpiralLift when change layer if lift type is auto
        gcode += this->retract(false, false, ZHopType(EXTRUDER_CONFIG(z_hop_types)) == ZHopType::zhtAuto ? LiftType::SpiralLift : lift_type);
    }
    m_writer.add_object_change_labels(gcode);
    if (!lazy_raise) {
        std::ostringstream comment;
        comment << "move to next layer (" << m_layer_index << ")";
        gcode += m_writer.travel_to_z(z, comment.str());
    } else {
        //BBS: set m_need_change_layer_lift_z to be true so that z lift can be done in travel_to() function
        m_need_change_layer_lift_z = true;
    }
    m_nominal_z = print_z;
    // forget last wiping path as wiping after raising Z is pointless
    // BBS. Dont forget wiping path to reduce stringing.
    //m_wipe.reset_path();
    return gcode;
}
References EXTRUDER_CONFIG.
Referenced by Slic3r::WipeTowerIntegration::finalize().
check_placeholder_parser_failed()
void Slic3r::GCode::check_placeholder_parser_failed () private
{
    if (! m_placeholder_parser_failed_templates.empty()) {
        // G-code export proceeded, but some of the PlaceholderParser substitutions failed.
        std::string msg = Slic3r::format(_(L("Failed to generate gcode for invalid custom G-code.\n\n")));
        for (const auto &name_and_error : m_placeholder_parser_failed_templates)
            msg += name_and_error.first + " " + name_and_error.second + "\n";
        msg += Slic3r::format(_(L("Please check the custom G-code or use the default custom G-code.")));
        throw Slic3r::PlaceholderParserError(msg);
    }
}
References _, Slic3r::format(), L, and m_placeholder_parser_failed_templates.
Referenced by do_export(), and process_layers().
collect_layers_to_print() [1/2]
std::vector< std::pair< coordf_t, std::vector< GCode::LayerToPrint > > > Slic3r::GCode::collect_layers_to_print (const Print & print) static private
{
    struct OrderingItem {
        coordf_t    print_z;
        size_t      object_idx;
        size_t      layer_idx;
    };
    std::vector<std::vector<LayerToPrint>>  per_object(print.objects().size(), std::vector<LayerToPrint>());
    std::vector<OrderingItem>               ordering;
    std::vector<Slic3r::SlicingError> errors;
    for (size_t i = 0; i < print.objects().size(); ++i) {
        try {
            per_object[i] = collect_layers_to_print(*print.objects()[i]);
        } catch (const Slic3r::SlicingError &e) {
            errors.push_back(e);
            continue;
        }
        OrderingItem ordering_item;
        ordering_item.object_idx = i;
        ordering.reserve(ordering.size() + per_object[i].size());
        const LayerToPrint& front = per_object[i].front();
        for (const LayerToPrint& ltp : per_object[i]) {
            ordering_item.print_z = ltp.print_z();
            ordering_item.layer_idx = &ltp - &front;
            ordering.emplace_back(ordering_item);
        }
    }
    if (!errors.empty()) { throw Slic3r::SlicingErrors(errors); }
    std::sort(ordering.begin(), ordering.end(), [](const OrderingItem& oi1, const OrderingItem& oi2) { return oi1.print_z < oi2.print_z; });
    std::vector<std::pair<coordf_t, std::vector<LayerToPrint>>> layers_to_print;
    // Merge numerically very close Z values.
    for (size_t i = 0; i < ordering.size();) {
        // Find the last layer with roughly the same print_z.
        size_t j = i + 1;
        coordf_t zmax = ordering[i].print_z + EPSILON;
        for (; j < ordering.size() && ordering[j].print_z <= zmax; ++j);
        // Merge into layers_to_print.
        std::pair<coordf_t, std::vector<LayerToPrint>> merged;
        // Assign an average print_z to the set of layers with nearly equal print_z.
        merged.first = 0.5 * (ordering[i].print_z + ordering[j - 1].print_z);
        merged.second.assign(print.objects().size(), LayerToPrint());
        for (; i < j; ++i) {
            const OrderingItem& oi = ordering[i];
            assert(merged.second[oi.object_idx].layer() == nullptr);
            merged.second[oi.object_idx] = std::move(per_object[oi.object_idx][oi.layer_idx]);
        }
        layers_to_print.emplace_back(std::move(merged));
    }
    return layers_to_print;
}
References collect_layers_to_print(), EPSILON, Slic3r::Print::objects(), Slic3r::ConstVectorOfPtrsAdaptor< T >::size(), size, and zmax.
collect_layers_to_print() [2/2]
std::vector< GCode::LayerToPrint > Slic3r::GCode::collect_layers_to_print (const PrintObject & object) static private
{
    std::vector<GCode::LayerToPrint> layers_to_print;
    layers_to_print.reserve(object.layers().size() + object.support_layers().size());
    /*
    // Calculate a minimum support layer height as a minimum over all extruders, but not smaller than 10um.
    // This is the same logic as in support generator.
    //FIXME should we use the printing extruders instead?
    double gap_over_supports = object.config().support_top_z_distance;
    // FIXME should we test object.config().support_material_synchronize_layers ? Currently the support layers are synchronized with object layers iff soluble supports.
    assert(!object.has_support() || gap_over_supports != 0. || object.config().support_material_synchronize_layers);
    if (gap_over_supports != 0.) {
        gap_over_supports = std::max(0., gap_over_supports);
        // Not a soluble support,
        double support_layer_height_min = 1000000.;
        for (auto lh : object.print()->config().min_layer_height.values)
            support_layer_height_min = std::min(support_layer_height_min, std::max(0.01, lh));
        gap_over_supports += support_layer_height_min;
    }*/
    std::vector<std::pair<double, double>> warning_ranges;
    // Pair the object layers with the support layers by z.
    size_t idx_object_layer = 0;
    size_t idx_support_layer = 0;
    const LayerToPrint* last_extrusion_layer = nullptr;
    while (idx_object_layer < object.layers().size() || idx_support_layer < object.support_layers().size()) {
        LayerToPrint layer_to_print;
        double print_z_min = std::numeric_limits<double>::max();
        if (idx_object_layer < object.layers().size()) {
            layer_to_print.object_layer = object.layers()[idx_object_layer++];
            print_z_min = std::min(print_z_min, layer_to_print.object_layer->print_z);
        }
        if (idx_support_layer < object.support_layers().size()) {
            layer_to_print.support_layer = object.support_layers()[idx_support_layer++];
            print_z_min = std::min(print_z_min, layer_to_print.support_layer->print_z);
        }
        if (layer_to_print.object_layer && layer_to_print.object_layer->print_z > print_z_min + EPSILON) {
            layer_to_print.object_layer = nullptr;
            --idx_object_layer;
        }
        if (layer_to_print.support_layer && layer_to_print.support_layer->print_z > print_z_min + EPSILON) {
            layer_to_print.support_layer = nullptr;
            --idx_support_layer;
        }
        layer_to_print.original_object = &object;
        layers_to_print.push_back(layer_to_print);
        bool has_extrusions = (layer_to_print.object_layer && layer_to_print.object_layer->has_extrusions())
            || (layer_to_print.support_layer && layer_to_print.support_layer->has_extrusions());
        // Check that there are extrusions on the very first layer. The case with empty
        // first layer may result in skirt/brim in the air and maybe other issues.
        if (layers_to_print.size() == 1u) {
            if (!has_extrusions)
                throw Slic3r::SlicingError(_(L("One object has empty initial layer and can't be printed. Please Cut the bottom or enable supports.")), object.id().id);
        }
        // In case there are extrusions on this layer, check there is a layer to lay it on.
        if ((layer_to_print.object_layer && layer_to_print.object_layer->has_extrusions())
            // Allow empty support layers, as the support generator may produce no extrusions for non-empty support regions.
            || (layer_to_print.support_layer /* && layer_to_print.support_layer->has_extrusions() */)) {
            double top_cd = object.config().support_top_z_distance;
            //double bottom_cd = object.config().support_bottom_z_distance == 0. ? top_cd : object.config().support_bottom_z_distance;
            double bottom_cd = top_cd;
            double extra_gap = (layer_to_print.support_layer ? bottom_cd : top_cd);
            // raft contact distance should not trigger any warning
            if(last_extrusion_layer && last_extrusion_layer->support_layer)
                extra_gap = std::max(extra_gap, object.config().raft_contact_distance.value);
            double maximal_print_z = (last_extrusion_layer ? last_extrusion_layer->print_z() : 0.)
                + layer_to_print.layer()->height
                + std::max(0., extra_gap);
            // Negative support_contact_z is not taken into account, it can result in false positives in cases
            if (has_extrusions && layer_to_print.print_z() > maximal_print_z + 2. * EPSILON)
                warning_ranges.emplace_back(std::make_pair((last_extrusion_layer ? last_extrusion_layer->print_z() : 0.), layers_to_print.back().print_z()));
        }
        // Remember last layer with extrusions.
        if (has_extrusions)
            last_extrusion_layer = &layers_to_print.back();
    }
    if (! warning_ranges.empty()) {
        std::string warning;
        size_t i = 0;
        for (i = 0; i < std::min(warning_ranges.size(), size_t(5)); ++i)
            warning += Slic3r::format(_(L("Object can't be printed for empty layer between %1% and %2%.")),
                                      warning_ranges[i].first, warning_ranges[i].second) + "\n";
        warning += Slic3r::format(_(L("Object: %1%")), object.model_object()->name) + "\n"
            + _(L("Maybe parts of the object at these height are too thin, or the object has faulty mesh"));
        const_cast<Print*>(object.print())->active_step_add_warning(
            PrintStateBase::WarningLevel::CRITICAL, warning, PrintStateBase::SlicingEmptyGcodeLayers);
    }
    return layers_to_print;
}
References _, config(), Slic3r::PrintStateBase::CRITICAL, EPSILON, Slic3r::format(), Slic3r::Layer::has_extrusions(), Slic3r::SupportLayer::has_extrusions(), Slic3r::Layer::height, L, Slic3r::GCode::LayerToPrint::layer(), Slic3r::GCode::LayerToPrint::object_layer, Slic3r::GCode::LayerToPrint::original_object, Slic3r::GCode::LayerToPrint::print_z(), Slic3r::Layer::print_z, size, Slic3r::PrintStateBase::SlicingEmptyGcodeLayers, and Slic3r::GCode::LayerToPrint::support_layer.
Referenced by _do_export(), and collect_layers_to_print().
config()
const FullPrintConfig & Slic3r::GCode::config () const inline
{ return m_config; }
References m_config.
Referenced by _do_export(), Slic3r::OozePrevention::_get_temp(), Slic3r::WipeTowerIntegration::append_tcr(), collect_layers_to_print(), Slic3r::CalibPressureAdvanceLine::generate_test(), Slic3r::CalibPressureAdvanceLine::is_delta(), Slic3r::need_wipe(), Slic3r::OozePrevention::post_toolchange(), Slic3r::OozePrevention::pre_toolchange(), Slic3r::CalibPressureAdvanceLine::print_pa_lines(), Slic3r::WipeTowerIntegration::tool_change(), Slic3r::AvoidCrossingPerimeters::travel_to(), and Slic3r::Wipe::wipe().
do_export()
void Slic3r::GCode::do_export (Print * print, const char * path, GCodeProcessorResult * result = nullptr, ThumbnailsGeneratorCallback thumbnail_cb = nullptr)
{
    PROFILE_CLEAR();
    // BBS
    m_curr_print = print;
    GCodeWriter::full_gcode_comment = print->config().gcode_comments;
    CNumericLocalesSetter locales_setter;
    // Does the file exist? If so, we hope that it is still valid.
    if (print->is_step_done(psGCodeExport) && boost::filesystem::exists(boost::filesystem::path(path)))
        return;
    BOOST_LOG_TRIVIAL(info) << boost::format("Will export G-code to %1% soon")%path;
    GCodeProcessor::s_IsBBLPrinter = print->is_BBL_printer();
    print->set_started(psGCodeExport);
    // check if any custom gcode contains keywords used by the gcode processor to
    // produce time estimation and gcode toolpaths
    std::vector<std::pair<std::string, std::string>> validation_res = DoExport::validate_custom_gcode(*print);
    if (!validation_res.empty()) {
        std::string reports;
        for (const auto& [source, keyword] : validation_res) {
            reports += source + ": \"" + keyword + "\"\n";
        }
        //print->active_step_add_warning(PrintStateBase::WarningLevel::NON_CRITICAL,
        //    _(L("In the custom G-code were found reserved keywords:")) + "\n" +
        //    reports +
        //    _(L("This may cause problems in g-code visualization and printing time estimation.")));
        std::string temp = "Dangerous keywords in custom Gcode: " + reports + "\nThis may cause problems in g-code visualization and printing time estimation.";
        BOOST_LOG_TRIVIAL(warning) << temp;
    }
    BOOST_LOG_TRIVIAL(info) << "Exporting G-code..." << log_memory_info();
    // Remove the old g-code if it exists.
    boost::nowide::remove(path);
    fs::path file_path(path);
    fs::path folder = file_path.parent_path();
    if (!fs::exists(folder)) {
        fs::create_directory(folder);
        BOOST_LOG_TRIVIAL(error) << "[WARNING]: the parent path " + folder.string() +" is not there, create it!" << std::endl;
    }
    std::string path_tmp(path);
    path_tmp += ".tmp";
    m_processor.initialize(path_tmp);
    GCodeOutputStream file(boost::nowide::fopen(path_tmp.c_str(), "wb"), m_processor);
    if (! file.is_open()) {
        BOOST_LOG_TRIVIAL(error) << std::string("G-code export to ") + path + " failed.\nCannot open the file for writing.\n" << std::endl;
        if (!fs::exists(folder)) {
            //fs::create_directory(folder);
            BOOST_LOG_TRIVIAL(error) << "the parent path " + folder.string() +" is not there!!!" << std::endl;
        }
        throw Slic3r::RuntimeError(std::string("G-code export to ") + path + " failed.\nCannot open the file for writing.\n");
    }
    try {
        m_placeholder_parser_failed_templates.clear();
        this->_do_export(*print, file, thumbnail_cb);
        file.flush();
        if (file.is_error()) {
            file.close();
            boost::nowide::remove(path_tmp.c_str());
            throw Slic3r::RuntimeError(std::string("G-code export to ") + path + " failed\nIs the disk full?\n");
        }
    } catch (std::exception & /* ex */) {
        // Rethrow on any exception. std::runtime_exception and CanceledException are expected to be thrown.
        // Close and remove the file.
        file.close();
        boost::nowide::remove(path_tmp.c_str());
        throw;
    }
    file.close();
    check_placeholder_parser_failed();
    BOOST_LOG_TRIVIAL(debug) << "Start processing gcode, " << log_memory_info();
    // Post-process the G-code to update time stamps.
    m_processor.finalize(true);
//    DoExport::update_print_estimated_times_stats(m_processor, print->m_print_statistics);
    DoExport::update_print_estimated_stats(m_processor, m_writer.extruders(), print->m_print_statistics);
    if (result != nullptr) {
        *result = std::move(m_processor.extract_result());
        // set the filename to the correct value
        result->filename = path;
    }
    //BBS: add some log for error output
    BOOST_LOG_TRIVIAL(debug) << boost::format("Finished processing gcode to %1% ") % path_tmp;
    std::error_code ret = rename_file(path_tmp, path);
    if (ret) {
        throw Slic3r::RuntimeError(
            std::string("Failed to rename the output G-code file from ") + path_tmp + " to " + path + '\n' + "error code " + ret.message() + '\n' +
            "Is " + path_tmp + " locked?" + '\n');
    }
    else {
        BOOST_LOG_TRIVIAL(info) << boost::format("rename_file from %1% to %2% successfully")% path_tmp % path;
    }
    BOOST_LOG_TRIVIAL(info) << "Exporting G-code finished" << log_memory_info();
    print->set_done(psGCodeExport);
    if(is_BBL_Printer())
        result->label_object_enabled = m_enable_exclude_object;
    // Write the profiler measurements to file
    PROFILE_UPDATE();
    PROFILE_OUTPUT(debug_out_path("gcode-export-profile.txt").c_str());
}
References _do_export(), check_placeholder_parser_failed(), Slic3r::GCode::GCodeOutputStream::close(), Slic3r::Print::config(), Slic3r::debug_out_path(), error, Slic3r::GCodeProcessor::extract_result(), Slic3r::GCodeWriter::extruders(), Slic3r::GCodeProcessorResult::filename, Slic3r::GCodeProcessor::finalize(), Slic3r::GCode::GCodeOutputStream::flush(), Slic3r::GCodeWriter::full_gcode_comment, Slic3r::GCodeProcessor::initialize(), is_BBL_Printer(), Slic3r::Print::is_BBL_printer(), Slic3r::GCode::GCodeOutputStream::is_error(), Slic3r::GCode::GCodeOutputStream::is_open(), Slic3r::Print::is_step_done(), Slic3r::GCodeProcessorResult::label_object_enabled, Slic3r::log_memory_info(), m_curr_print, m_enable_exclude_object, m_placeholder_parser_failed_templates, Slic3r::Print::m_print_statistics, m_processor, m_writer, PROFILE_CLEAR, PROFILE_OUTPUT, PROFILE_UPDATE, Slic3r::psGCodeExport, Slic3r::rename_file(), Slic3r::GCodeProcessor::s_IsBBLPrinter, Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_done(), Slic3r::PrintBaseWithState< PrintStepEnum, COUNT >::set_started(), Slic3r::DoExport::update_print_estimated_stats(), and Slic3r::DoExport::validate_custom_gcode().
enable_cooling_markers()
bool Slic3r::GCode::enable_cooling_markers () const inline
{ return m_enable_cooling_markers; }
References m_enable_cooling_markers.
Referenced by Slic3r::Wipe::wipe().
extrude_entity()
std::string Slic3r::GCode::extrude_entity (const ExtrusionEntity & entity, std::string description = "", double speed = -1.) private
{
    if (const ExtrusionPath* path = dynamic_cast<const ExtrusionPath*>(&entity))
        return this->extrude_path(*path, description, speed);
    else if (const ExtrusionMultiPath* multipath = dynamic_cast<const ExtrusionMultiPath*>(&entity))
        return this->extrude_multi_path(*multipath, description, speed);
    else if (const ExtrusionLoop* loop = dynamic_cast<const ExtrusionLoop*>(&entity))
        return this->extrude_loop(*loop, description, speed);
    else
        throw Slic3r::InvalidArgument("Invalid argument supplied to extrude()");
    return "";
}
extrude_infill()
std::string Slic3r::GCode::extrude_infill (const Print & print, const std::vector< ObjectByExtruder::Island::Region > & by_region, bool ironing) private
{
    std::string      gcode;
    ExtrusionEntitiesPtr extrusions;
    const char*          extrusion_name = ironing ? "ironing" : "infill";
    for (const ObjectByExtruder::Island::Region &region : by_region)
        if (! region.infills.empty()) {
            extrusions.clear();
            extrusions.reserve(region.infills.size());
            for (ExtrusionEntity *ee : region.infills)
                if ((ee->role() == erIroning) == ironing)
                    extrusions.emplace_back(ee);
            if (! extrusions.empty()) {
                m_config.apply(print.get_print_region(&region - &by_region.front()).config());
                chain_and_reorder_extrusion_entities(extrusions, &m_last_pos);
                for (const ExtrusionEntity *fill : extrusions) {
                    auto *eec = dynamic_cast<const ExtrusionEntityCollection*>(fill);
                    if (eec) {
                        for (ExtrusionEntity *ee : eec->chained_path_from(m_last_pos).entities)
                            gcode += this->extrude_entity(*ee, extrusion_name);
                    } else
                        gcode += this->extrude_entity(*fill, extrusion_name);
                }
            }
        }
    return gcode;
}
References Slic3r::chain_and_reorder_extrusion_entities(), Slic3r::PrintRegion::config(), Slic3r::erIroning, and Slic3r::Print::get_print_region().
extrude_loop()
std::string Slic3r::GCode::extrude_loop (ExtrusionLoop loop, std::string description, double speed = -1.) private
{
    // get a copy; don't modify the orientation of the original loop object otherwise
    // next copies (if any) would not detect the correct orientation
    // extrude all loops ccw
    bool was_clockwise = loop.make_counter_clockwise();
    // find the point of the loop that is closest to the current extruder position
    // or randomize if requested
    Point last_pos = this->last_pos();
    if (!m_config.spiral_mode && description == "perimeter") {
        assert(m_layer != nullptr);
        bool is_outer_wall_first = m_config.wall_infill_order == WallInfillOrder::OuterInnerInfill
                                || m_config.wall_infill_order == WallInfillOrder::InfillOuterInner
                                || m_config.wall_infill_order == WallInfillOrder::InnerOuterInnerInfill;
        m_seam_placer.place_seam(m_layer, loop, is_outer_wall_first, this->last_pos());
    } else
        loop.split_at(last_pos, false);
    // clip the path to avoid the extruder to get exactly on the first point of the loop;
    // if polyline was shorter than the clipping distance we'd get a null polyline, so
    // we discard it in that case
    double clip_length = m_enable_loop_clipping ?
    scale_(m_config.seam_gap.get_abs_value(EXTRUDER_CONFIG(nozzle_diameter))) : 0;
    // get paths
    ExtrusionPaths paths;
    loop.clip_end(clip_length, &paths);
    if (paths.empty()) return "";
    // SoftFever: check loop lenght for small perimeter.
    double small_peri_speed = -1;
    if (speed == -1 && loop.length() <= SMALL_PERIMETER_LENGTH(m_config.small_perimeter_threshold.value))
        small_peri_speed = m_config.small_perimeter_speed.get_abs_value(m_config.outer_wall_speed);
    // extrude along the path
    std::string gcode;
    bool is_small_peri = false;
    for (ExtrusionPaths::iterator path = paths.begin(); path != paths.end(); ++path) {
//    description += ExtrusionLoop::role_to_string(loop.loop_role());
//    description += ExtrusionEntity::role_to_string(path->role);
        // don't apply small perimeter setting for overhangs/bridges/non-perimeters
        is_small_peri = is_perimeter(path->role()) && !is_bridge(path->role()) && small_peri_speed > 0 && (path->get_overhang_degree() == 0 || path->get_overhang_degree() > 5);
        gcode += this->_extrude(*path, description, is_small_peri ? small_peri_speed : speed);
    }
    // BBS
    if (m_wipe.enable) {
        m_wipe.path = Polyline();
        for (ExtrusionPath &path : paths) {
            //BBS: Don't need to save duplicated point into wipe path
            if (!m_wipe.path.empty() && !path.empty() &&
                m_wipe.path.last_point() == path.first_point())
                m_wipe.path.append(path.polyline.points.begin() + 1, path.polyline.points.end());
            else
                m_wipe.path.append(path.polyline);  // TODO: don't limit wipe to last path
        }
    }
    // make a little move inwards before leaving loop
    if (m_config.wipe_on_loops.value && paths.back().role() == erExternalPerimeter && m_layer != NULL && m_config.wall_loops.value > 1 && paths.front().size() >= 2 && paths.back().polyline.points.size() >= 3) {
        // detect angle between last and first segment
        // the side depends on the original winding order of the polygon (left for contours, right for holes)
        //FIXME improve the algorithm in case the loop is tiny.
        //FIXME improve the algorithm in case the loop is split into segments with a low number of points (see the Point b query).
        Point a = paths.front().polyline.points[1];  // second point
        Point b = *(paths.back().polyline.points.end()-3);       // second to last point
        if (was_clockwise) {
            // swap points
            Point c = a; a = b; b = c;
    //    double angle = paths.front().first_point().ccw_angle(a, b) / 3;
    //    // turn left if contour, turn right if hole
    //    if (was_clockwise) angle *= -1;
        }
        double angle = paths.front().first_point().ccw_angle(a, b) / 3;
        // turn left if contour, turn right if hole
        if (was_clockwise) angle *= -1;
        // create the destination point along the first segment and rotate it
        // we make sure we don't exceed the segment length because we don't know
        // the rotation of the second segment so we might cross the object boundary
        Vec2d  p1 = paths.front().polyline.points.front().cast<double>();
        Vec2d  p2 = paths.front().polyline.points[1].cast<double>();
        Vec2d  v  = p2 - p1;
        double nd = scale_(EXTRUDER_CONFIG(nozzle_diameter));
        double l2 = v.squaredNorm();
        // Shift by no more than a nozzle diameter.
        //FIXME Hiding the seams will not work nicely for very densely discretized contours!
        //BBS. shorten the travel distant before the wipe path
        double threshold = 0.2;
        Point  pt = (p1 + v * threshold).cast<coord_t>();
        if (nd * nd < l2)
            pt = (p1 + threshold * v * (nd / sqrt(l2))).cast<coord_t>();
        //Point pt = ((nd * nd >= l2) ? (p1+v*0.4): (p1 + 0.2 * v * (nd / sqrt(l2)))).cast<coord_t>();
        pt.rotate(angle, paths.front().polyline.points.front());
        // generate the travel move
        gcode += m_writer.extrude_to_xy(this->point_to_gcode(pt), 0,"move inwards before travel",true);
    }
    return gcode;
}
References Slic3r::angle(), Slic3r::erExternalPerimeter, EXTRUDER_CONFIG, Slic3r::is_bridge(), Slic3r::is_perimeter(), Slic3r::l2(), NULL, Slic3r::Point::rotate(), scale_, SMALL_PERIMETER_LENGTH, and sqrt().
extrude_multi_path()
std::string Slic3r::GCode::extrude_multi_path (ExtrusionMultiPath multipath, std::string description = "", double speed = -1.) private
{
    // extrude along the path
    std::string gcode;
    for (ExtrusionPath path : multipath.paths)
        gcode += this->_extrude(path, description, speed);
    // BBS
    if (m_wipe.enable) {
        m_wipe.path = Polyline();
        for (ExtrusionPath &path : multipath.paths) {
            //BBS: Don't need to save duplicated point into wipe path
            if (!m_wipe.path.empty() && !path.empty() &&
                m_wipe.path.last_point() == path.first_point())
                m_wipe.path.append(path.polyline.points.begin() + 1, path.polyline.points.end());
            else
                m_wipe.path.append(path.polyline); // TODO: don't limit wipe to last path
        }
        m_wipe.path.reverse();
    }
    return gcode;
}
References Slic3r::ExtrusionMultiPath::paths.
extrude_path()
std::string Slic3r::GCode::extrude_path (ExtrusionPath path, std::string description = "", double speed = -1.) private
{
//    description += ExtrusionEntity::role_to_string(path.role());
    std::string gcode = this->_extrude(path, description, speed);
    if (m_wipe.enable) {
        m_wipe.path = std::move(path.polyline);
        m_wipe.path.reverse();
    }
    return gcode;
}
References Slic3r::ExtrusionPath::polyline.
extrude_perimeters()
std::string Slic3r::GCode::extrude_perimeters (const Print & print, const std::vector< ObjectByExtruder::Island::Region > & by_region) private
{
    std::string gcode;
    for (const ObjectByExtruder::Island::Region &region : by_region)
        if (! region.perimeters.empty()) {
            m_config.apply(print.get_print_region(&region - &by_region.front()).config());
            for (const ExtrusionEntity* ee : region.perimeters)
                gcode += this->extrude_entity(*ee, "perimeter", -1.);
        }
    return gcode;
}
References Slic3r::PrintRegion::config(), and Slic3r::Print::get_print_region().
extrude_support()
std::string Slic3r::GCode::extrude_support (const ExtrusionEntityCollection & support_fills) private
{
    static constexpr const char *support_label            = "support material";
    static constexpr const char *support_interface_label  = "support material interface";
    const char* support_transition_label = "support transition";
    std::string gcode;
    if (! support_fills.entities.empty()) {
        const double  support_speed            = m_config.support_speed.value;
        const double  support_interface_speed  = m_config.get_abs_value("support_interface_speed");
        for (const ExtrusionEntity *ee : support_fills.entities) {
            ExtrusionRole role = ee->role();
            assert(role == erSupportMaterial || role == erSupportMaterialInterface || role == erSupportTransition);
            const char* label = (role == erSupportMaterial) ? support_label :
                ((role == erSupportMaterialInterface) ? support_interface_label : support_transition_label);
            // BBS
            //const double speed = (role == erSupportMaterial) ? support_speed : support_interface_speed;
            const double speed = -1.0;
            const ExtrusionPath* path = dynamic_cast<const ExtrusionPath*>(ee);
            const ExtrusionMultiPath* multipath = dynamic_cast<const ExtrusionMultiPath*>(ee);
            const ExtrusionLoop* loop = dynamic_cast<const ExtrusionLoop*>(ee);
            const ExtrusionEntityCollection* collection = dynamic_cast<const ExtrusionEntityCollection*>(ee);
            if (path)
                gcode += this->extrude_path(*path, label, speed);
            else if (multipath) {
                gcode += this->extrude_multi_path(*multipath, label, speed);
            }
            else if (loop) {
                gcode += this->extrude_loop(*loop, label, speed);
            }
            else if (collection) {
                gcode += extrude_support(*collection);
            }
            else {
                throw Slic3r::InvalidArgument("Unknown extrusion type");
            }
        }
    }
    return gcode;
}
References Slic3r::ExtrusionEntityCollection::entities, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, and Slic3r::erSupportTransition.
gcode_to_point()
Point Slic3r::GCode::gcode_to_point (const Vec2d & point) const
{
    Vec2d extruder_offset = EXTRUDER_CONFIG(extruder_offset);
    return Point(
        scale_(point(0) - m_origin(0) + extruder_offset(0)),
        scale_(point(1) - m_origin(1) + extruder_offset(1)));
}
References EXTRUDER_CONFIG, Slic3r::extruder_offset(), and scale_.
get_bed_temperature()
int Slic3r::GCode::get_bed_temperature (const int extruder_id, const bool is_first_layer, const BedType bed_type) const private
{
    std::string bed_temp_key = is_first_layer ? get_bed_temp_1st_layer_key(bed_type) : get_bed_temp_key(bed_type);
    const ConfigOptionInts* bed_temp_opt = m_config.option<ConfigOptionInts>(bed_temp_key);
    return bed_temp_opt->get_at(extruder_id);
}
References Slic3r::ConfigOptionVector< T >::get_at().
Referenced by _do_export().
is_BBL_Printer()
bool Slic3r::GCode::is_BBL_Printer ()
{
    if (m_curr_print)
        return m_curr_print->is_BBL_printer();
    return false;
}
References Slic3r::Print::is_BBL_printer(), and m_curr_print.
Referenced by do_export().
last_pos()
const Point & Slic3r::GCode::last_pos () const inline
{ return m_last_pos; }
References m_last_pos.
Referenced by Slic3r::AvoidCrossingPerimeters::travel_to(), and Slic3r::Wipe::wipe().
last_pos_defined()
bool Slic3r::GCode::last_pos_defined () const inline private
{ return m_last_pos_defined; }
References m_last_pos_defined.
layer()
const Layer * Slic3r::GCode::layer () const inline
{ return m_layer; }
References m_layer.
Referenced by _do_export(), Slic3r::OozePrevention::_get_temp(), Slic3r::need_wipe(), process_layers(), and Slic3r::AvoidCrossingPerimeters::travel_to().
layer_count()
unsigned int Slic3r::GCode::layer_count () const inline
{ return m_layer_count; }
References m_layer_count.
layer_id()
int Slic3r::GCode::layer_id () const inline private
{
        if (m_layer == nullptr)
            return -1;
        return m_layer->id();
    }
References Slic3r::Layer::id(), and m_layer.
needs_retraction()
bool Slic3r::GCode::needs_retraction (const Polyline & travel, ExtrusionRole role, LiftType & lift_type)
{
    if (travel.length() < scale_(EXTRUDER_CONFIG(retraction_minimum_travel))) {
        // skip retraction if the move is shorter than the configured threshold
        return false;
    }
    //BBS: input travel polyline must be in current plate coordinate system
    auto is_through_overhang = [this](const Polyline& travel) {
        BoundingBox travel_bbox = get_extents(travel);
        travel_bbox.inflated(1);
        travel_bbox.defined = true;
        const float protect_z_scaled = scale_(0.4);
        std::pair<float, float> z_range;
        z_range.second = m_layer ? m_layer->print_z : 0.f;
        z_range.first = std::max(0.f, z_range.second - protect_z_scaled);
        std::vector<LayerPtrs> layers_of_objects;
        std::vector<BoundingBox> boundingBox_for_objects;
        std::vector<Points> objects_instances_shift;
        std::vector<size_t> idx_of_object_sorted = m_curr_print->layers_sorted_for_object(z_range.first, z_range.second, layers_of_objects, boundingBox_for_objects, objects_instances_shift);
        std::vector<bool> is_layers_of_objects_sorted(layers_of_objects.size(), false);
        for (size_t idx : idx_of_object_sorted) {
            for (const Point & instance_shift : objects_instances_shift[idx]) {
                BoundingBox instance_bbox = boundingBox_for_objects[idx];
                if (!instance_bbox.defined)  //BBS: Don't need to check when bounding box of overhang area is empty(undefined)
                    continue;
                instance_bbox.offset(scale_(EPSILON));
                instance_bbox.translate(instance_shift.x(), instance_shift.y());
                if (!instance_bbox.overlap(travel_bbox))
                    continue;
                Polygons temp;
                temp.emplace_back(std::move(instance_bbox.polygon()));
                if (intersection_pl(travel, temp).empty())
                    continue;
                if (!is_layers_of_objects_sorted[idx]) {
                    std::sort(layers_of_objects[idx].begin(), layers_of_objects[idx].end(), [](auto left, auto right) { return left->loverhangs_bbox.area() > right->loverhangs_bbox.area();});
                    is_layers_of_objects_sorted[idx] = true;
                }
                for (const auto& layer : layers_of_objects[idx]) {
                    for (ExPolygon overhang : layer->loverhangs) {
                        overhang.translate(instance_shift);
                        BoundingBox bbox1 = get_extents(overhang);
                        if (!bbox1.overlap(travel_bbox))
                            continue;
                        if (intersection_pl(travel, overhang).empty())
                            continue;
                        return true;
                    }
                }
            }
        }
        return false;
    };
    float max_z_hop = 0.f;
    for (int i = 0; i < m_config.z_hop.size(); i++)
        max_z_hop = std::max(max_z_hop, (float)m_config.z_hop.get_at(i));
    float travel_len_thresh = max_z_hop / tan(GCodeWriter::slope_threshold);
    float accum_len = 0.f;
    Polyline clipped_travel;
    clipped_travel.append(Polyline(travel.points[0], travel.points[1]));
    if (clipped_travel.length() > travel_len_thresh)
        clipped_travel.points.back() = clipped_travel.points.front()+(clipped_travel.points.back() - clipped_travel.points.front()) * (travel_len_thresh / clipped_travel.length());
    //BBS: translate to current plate coordinate system
    clipped_travel.translate(Point::new_scale(double(m_origin.x() - m_writer.get_xy_offset().x()), double(m_origin.y() - m_writer.get_xy_offset().y())));
    //BBS: force to retract when leave from external perimeter for a long travel
    //Better way is judging whether the travel move direction is same with last extrusion move.
    if (is_perimeter(m_last_processor_extrusion_role) && m_last_processor_extrusion_role != erPerimeter) {
        if (ZHopType(EXTRUDER_CONFIG(z_hop_types)) == ZHopType::zhtAuto) {
            lift_type = is_through_overhang(clipped_travel) ? LiftType::SpiralLift : LiftType::LazyLift;
        }
        else {
            lift_type = to_lift_type(ZHopType(EXTRUDER_CONFIG(z_hop_types)));
        }
        return true;
    }
    if (role == erSupportMaterial || role == erSupportTransition) {
        const SupportLayer* support_layer = dynamic_cast<const SupportLayer*>(m_layer);
        //FIXME support_layer->support_islands.contains should use some search structure!
        if (support_layer != NULL)
            // skip retraction if this is a travel move inside a support material island
            //FIXME not retracting over a long path may cause oozing, which in turn may result in missing material
            // at the end of the extrusion path!
            for (const ExPolygon& support_island : support_layer->support_islands)
                if (support_island.contains(travel))
                    return false;
        //reduce the retractions in lightning infills for tree support
        if (support_layer != NULL && support_layer->support_type==stInnerTree)
            for (auto &area : support_layer->base_areas)
                if (area.contains(travel))
                    return false;
    }
    //BBS: need retract when long moving to print perimeter to avoid dropping of material
    if (!is_perimeter(role) && m_config.reduce_infill_retraction && m_layer != nullptr &&
        m_config.sparse_infill_density.value > 0 && m_retract_when_crossing_perimeters.travel_inside_internal_regions(*m_layer, travel))
        // Skip retraction if travel is contained in an internal slice *and*
        // internal infill is enabled (so that stringing is entirely not visible).
        //FIXME any_internal_region_slice_contains() is potentionally very slow, it shall test for the bounding boxes first.
        return false;
    // retract if reduce_infill_retraction is disabled or doesn't apply when role is perimeter
    if (ZHopType(EXTRUDER_CONFIG(z_hop_types)) == ZHopType::zhtAuto) {
        lift_type = is_through_overhang(clipped_travel) ? LiftType::SpiralLift : LiftType::LazyLift;
    }
    else {
        lift_type = to_lift_type(ZHopType(EXTRUDER_CONFIG(z_hop_types)));
    }
    return true;
}
References Slic3r::Polyline::append(), Slic3r::SupportLayer::base_areas, Slic3r::BoundingBoxBase< PointClass >::defined, Slic3r::empty(), end, EPSILON, Slic3r::erPerimeter, Slic3r::erSupportMaterial, Slic3r::erSupportTransition, EXTRUDER_CONFIG, Slic3r::get_extents(), Slic3r::BoundingBox::inflated(), Slic3r::intersection_pl(), Slic3r::is_perimeter(), Slic3r::MultiPoint::length(), NULL, Slic3r::BoundingBoxBase< PointClass >::offset(), Slic3r::BoundingBoxBase< PointClass >::overlap(), Slic3r::MultiPoint::points, Slic3r::BoundingBox::polygon(), Slic3r::retraction_minimum_travel(), scale_, Slic3r::stInnerTree, Slic3r::SupportLayer::support_islands, Slic3r::SupportLayer::support_type, tan(), Slic3r::BoundingBoxBase< PointClass >::translate(), and Slic3r::MultiPoint::translate().
object_layer_over_raft()
bool Slic3r::GCode::object_layer_over_raft () const inline private
{ return m_object_layer_over_raft; }
References m_object_layer_over_raft.
on_first_layer()
bool Slic3r::GCode::on_first_layer () const inline private
{ return m_layer != nullptr && m_layer->id() == 0 && abs(m_layer->bottom_z()) < EPSILON; }
References Slic3r::Layer::bottom_z(), EPSILON, Slic3r::Layer::id(), and m_layer.
Referenced by Slic3r::WipeTowerIntegration::append_tcr().
origin()
const Vec2d & Slic3r::GCode::origin () const inline
{ return m_origin; }
References m_origin.
Referenced by Slic3r::AvoidCrossingPerimeters::travel_to(), and Slic3r::wipe_tower_point_to_object_point().
placeholder_parser() [1/2]
PlaceholderParser & Slic3r::GCode::placeholder_parser () inline
{ return m_placeholder_parser; }
References m_placeholder_parser.
Referenced by Slic3r::WipeTowerIntegration::append_tcr().
placeholder_parser() [2/2]
const PlaceholderParser & Slic3r::GCode::placeholder_parser () const inline
{ return m_placeholder_parser; }
References m_placeholder_parser.
placeholder_parser_process()
std::string Slic3r::GCode::placeholder_parser_process (const std::string & name, const std::string & templ, unsigned int current_extruder_id, const DynamicConfig * config_override = nullptr)
{
    try {
        return m_placeholder_parser.process(templ, current_extruder_id, config_override, &m_placeholder_parser_context);
    } catch (std::runtime_error &err) {
        // Collect the names of failed template substitutions for error reporting.
        auto it = m_placeholder_parser_failed_templates.find(name);
        if (it == m_placeholder_parser_failed_templates.end())
            // Only if there was no error reported for this template, store the first error message into the map to be reported.
            // We don't want to collect error message for each and every occurence of a single custom G-code section.
            m_placeholder_parser_failed_templates.insert(it, std::make_pair(name, std::string(err.what())));
        // Insert the macro error message into the G-code.
        return
            std::string("\n!!!!! Failed to process the custom G-code template ") + name + "\n" +
            err.what() +
            "!!!!! End of an error report for the custom G-code template " + name + "\n\n";
    }
}
Referenced by _do_export(), Slic3r::WipeTowerIntegration::append_tcr(), and Slic3r::ProcessLayer::emit_custom_gcode_per_print_z().
point_to_gcode()
Vec2d Slic3r::GCode::point_to_gcode (const Point & point) const
{
    Vec2d extruder_offset = EXTRUDER_CONFIG(extruder_offset);
    return unscale(point) + m_origin - extruder_offset;
}
References EXTRUDER_CONFIG, Slic3r::extruder_offset(), and Slic3r::unscale().
Referenced by Slic3r::Wipe::wipe().
point_to_gcode_quantized()
Vec2d Slic3r::GCode::point_to_gcode_quantized (const Point & point) const
{
    Vec2d p = this->point_to_gcode(point);
    return { GCodeFormatter::quantize_xyzf(p.x()), GCodeFormatter::quantize_xyzf(p.y()) };
}
preamble()
std::string Slic3r::GCode::preamble () private
{
    std::string gcode = m_writer.preamble();
    /*  Perform a *silent* move to z_offset: we need this to initialize the Z
        position of our writer object so that any initial lift taking place
        before the first layer change will raise the extruder from the correct
        initial Z instead of 0.  */
    //m_writer.travel_to_z(m_config.z_offset.value);
    m_writer.travel_to_z(0.0);
    return gcode;
}
Referenced by _do_export().
print_machine_envelope()
void Slic3r::GCode::print_machine_envelope (GCodeOutputStream & file, Print & print) private
{
    const auto flavor = print.config().gcode_flavor.value;
    if (flavor == gcfMarlinLegacy || flavor == gcfMarlinFirmware) {
        int factor = flavor == gcfRepRapFirmware ? 60 : 1; // RRF M203 and M566 are in mm/min
        file.write_format("M201 X%d Y%d Z%d E%d\n",
            int(print.config().machine_max_acceleration_x.values.front() + 0.5),
            int(print.config().machine_max_acceleration_y.values.front() + 0.5),
            int(print.config().machine_max_acceleration_z.values.front() + 0.5),
            int(print.config().machine_max_acceleration_e.values.front() + 0.5));
        file.write_format("M203 X%d Y%d Z%d E%d\n",
            int(print.config().machine_max_speed_x.values.front() * factor + 0.5),
            int(print.config().machine_max_speed_y.values.front() * factor + 0.5),
            int(print.config().machine_max_speed_z.values.front() * factor + 0.5),
            int(print.config().machine_max_speed_e.values.front() * factor + 0.5));
        // Now M204 - acceleration. This one is quite hairy thanks to how Marlin guys care about
        // Legacy Marlin should export travel acceleration the same as printing acceleration.
        // MarlinFirmware has the two separated.
        int travel_acc = flavor == gcfMarlinLegacy
                       ? int(print.config().machine_max_acceleration_extruding.values.front() + 0.5)
                       : int(print.config().machine_max_acceleration_travel.values.front() + 0.5);
        if (flavor == gcfRepRapFirmware)
            file.write_format("M204 P%d T%d ; sets acceleration (P, T), mm/sec^2\n",
                int(print.config().machine_max_acceleration_extruding.values.front() + 0.5),
                travel_acc);
        else
            file.write_format("M204 P%d R%d T%d\n",
                int(print.config().machine_max_acceleration_extruding.values.front() + 0.5),
                int(print.config().machine_max_acceleration_retracting.values.front() + 0.5),
                travel_acc);
        assert(is_decimal_separator_point());
        file.write_format(flavor == gcfRepRapFirmware
            ? "M566 X%.2lf Y%.2lf Z%.2lf E%.2lf ; sets the jerk limits, mm/min\n"
            : "M205 X%.2lf Y%.2lf Z%.2lf E%.2lf ; sets the jerk limits, mm/sec\n",
            print.config().machine_max_jerk_x.values.front() * factor,
            print.config().machine_max_jerk_y.values.front() * factor,
            print.config().machine_max_jerk_z.values.front() * factor,
            print.config().machine_max_jerk_e.values.front() * factor);
    }
}
References Slic3r::Print::config(), Slic3r::gcfMarlinFirmware, Slic3r::gcfMarlinLegacy, Slic3r::gcfRepRapFirmware, int, Slic3r::is_decimal_separator_point(), and Slic3r::GCode::GCodeOutputStream::write_format().
Referenced by _do_export().
process_layer()
GCode::LayerResult Slic3r::GCode::process_layer (const Print & print, const std::vector< LayerToPrint > & layers, const LayerTools & layer_tools, const bool last_layer, const std::vector< const PrintInstance * > * ordering, const size_t single_object_idx = size_t(-1), const bool prime_extruder = false) private
{
    assert(! layers.empty());
    // Either printing all copies of all objects, or just a single copy of a single object.
    assert(single_object_instance_idx == size_t(-1) || layers.size() == 1);
    // First object, support and raft layer, if available.
    const Layer         *object_layer  = nullptr;
    const SupportLayer  *support_layer = nullptr;
    const SupportLayer  *raft_layer    = nullptr;
    for (const LayerToPrint &l : layers) {
        if (l.object_layer && ! object_layer)
            object_layer = l.object_layer;
        if (l.support_layer) {
            if (! support_layer)
                support_layer = l.support_layer;
            if (! raft_layer && support_layer->id() < support_layer->object()->slicing_parameters().raft_layers())
                raft_layer = support_layer;
        }
    }
    const Layer* layer_ptr = nullptr;
    if (object_layer != nullptr)
        layer_ptr = object_layer;
    else if (support_layer != nullptr)
        layer_ptr = support_layer;
    const Layer& layer = *layer_ptr;
    GCode::LayerResult   result { {}, layer.id(), false, last_layer };
    if (layer_tools.extruders.empty())
        // Nothing to extrude.
        return result;
    // Extract 1st object_layer and support_layer of this set of layers with an equal print_z.
    coordf_t             print_z       = layer.print_z;
    //BBS: using layer id to judge whether the layer is first layer is wrong. Because if the normal
    //support is attached above the object, and support layers has independent layer height, then the lowest support
    //interface layer id is 0.
    bool                 first_layer   = (layer.id() == 0 && abs(layer.bottom_z()) < EPSILON);
    m_writer.set_is_first_layer(first_layer);
    unsigned int         first_extruder_id = layer_tools.extruders.front();
    // Initialize config with the 1st object to be printed at this layer.
    m_config.apply(layer.object()->config(), true);
    // Check whether it is possible to apply the spiral vase logic for this layer.
    // Just a reminder: A spiral vase mode is allowed for a single object, single material print only.
    m_enable_loop_clipping = true;
    if (m_spiral_vase && layers.size() == 1 && support_layer == nullptr) {
        bool enable = (layer.id() > 0 || !print.has_brim()) && (layer.id() >= (size_t)print.config().skirt_height.value && ! print.has_infinite_skirt());
        if (enable) {
            for (const LayerRegion *layer_region : layer.regions())
                if (size_t(layer_region->region().config().bottom_shell_layers.value) > layer.id() ||
                    layer_region->perimeters.items_count() > 1u ||
                    layer_region->fills.items_count() > 0) {
                    enable = false;
                    break;
                }
        }
        result.spiral_vase_enable = enable;
        // If we're going to apply spiralvase to this layer, disable loop clipping.
        m_enable_loop_clipping = !enable;
    }
    std::string gcode;
    assert(is_decimal_separator_point()); // for the sprintfs
    // add tag for processor
    gcode += ";" + GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Layer_Change) + "\n";
    // export layer z
    char buf[64];
    sprintf(buf, print.is_BBL_printer() ? "; Z_HEIGHT: %g\n" : ";Z:%g\n", print_z);
    gcode += buf;
    // export layer height
    float height = first_layer ? static_cast<float>(print_z) : static_cast<float>(print_z) - m_last_layer_z;
    sprintf(buf, ";%s%g\n", GCodeProcessor::reserved_tag(GCodeProcessor::ETags::Height).c_str(), height);
    gcode += buf;
    // update caches
    m_last_layer_z = static_cast<float>(print_z);
    m_max_layer_z  = std::max(m_max_layer_z, m_last_layer_z);
    m_last_height = height;
    // Set new layer - this will change Z and force a retraction if retract_when_changing_layer is enabled.
    if (! print.config().before_layer_change_gcode.value.empty()) {
        DynamicConfig config;
        config.set_key_value("layer_num",   new ConfigOptionInt(m_layer_index + 1));
        config.set_key_value("layer_z",     new ConfigOptionFloat(print_z));
        config.set_key_value("max_layer_z", new ConfigOptionFloat(m_max_layer_z));
        gcode += this->placeholder_parser_process("before_layer_change_gcode",
            print.config().before_layer_change_gcode.value, m_writer.extruder()->id(), &config)
            + "\n";
    }
    if (print.calib_mode() == CalibMode::Calib_PA_Tower) {
        gcode += writer().set_pressure_advance(print.calib_params().start + static_cast<int>(print_z) * print.calib_params().step);
    } else if (print.calib_mode() == CalibMode::Calib_Temp_Tower) {
        auto offset = static_cast<unsigned int>(print_z / 10.001) * 5;
        gcode += writer().set_temperature(print.calib_params().start - offset);
    } else if (print.calib_mode() == CalibMode::Calib_VFA_Tower) {
        auto _speed = print.calib_params().start + std::floor(print_z / 5.0) * print.calib_params().step;
        m_calib_config.set_key_value("outer_wall_speed", new ConfigOptionFloat(std::round(_speed)));
    } else if (print.calib_mode() == CalibMode::Calib_Vol_speed_Tower) {
        auto _speed = print.calib_params().start + print_z * print.calib_params().step;
        m_calib_config.set_key_value("outer_wall_speed", new ConfigOptionFloat(std::round(_speed)));
    }
    else if (print.calib_mode() == CalibMode::Calib_Retraction_tower) {
        auto _length = print.calib_params().start + std::floor(std::max(0.0,print_z-0.4)) * print.calib_params().step;
        DynamicConfig _cfg;
        _cfg.set_key_value("retraction_length", new ConfigOptionFloats{_length});
        writer().config.apply(_cfg);
        sprintf(buf, "; Calib_Retraction_tower: Z_HEIGHT: %g, length:%g\n", print_z, _length);
        gcode += buf;
    }
    // BBS: don't use lazy_raise when enable spiral vase
    gcode += this->change_layer(print_z, !m_spiral_vase);  // this will increase m_layer_index
    m_layer = &layer;
    m_object_layer_over_raft = false;
    if (! print.config().layer_change_gcode.value.empty()) {
        DynamicConfig config;
        config.set_key_value("layer_num", new ConfigOptionInt(m_layer_index));
        config.set_key_value("layer_z",   new ConfigOptionFloat(print_z));
        gcode += this->placeholder_parser_process("layer_change_gcode",
            print.config().layer_change_gcode.value, m_writer.extruder()->id(), &config)
            + "\n";
        config.set_key_value("max_layer_z", new ConfigOptionFloat(m_max_layer_z));
    }
    //BBS
    if (first_layer) {
        if (m_config.default_acceleration.value > 0 && m_config.initial_layer_acceleration.value > 0) {
            gcode += m_writer.set_acceleration((unsigned int)floor(m_config.initial_layer_acceleration.value + 0.5));
        }
        if (m_config.default_jerk.value > 0 && m_config.initial_layer_jerk.value > 0) {
            gcode += m_writer.set_jerk_xy(m_config.initial_layer_jerk.value);
        }
    }
    if (! first_layer && ! m_second_layer_things_done) {
      if (print.is_BBL_printer()) {
        // BBS: open powerlost recovery
        {
          gcode += "; open powerlost recovery\n";
          gcode += "M1003 S1\n";
        }
        // BBS: open first layer inspection at second layer
        if (print.config().scan_first_layer.value) {
          // BBS: retract first to avoid droping when scan model
          gcode += this->retract();
          gcode += "M976 S1 P1 ; scan model before printing 2nd layer\n";
          gcode += "M400 P100\n";
          gcode += this->unretract();
        }
      }
      // BBS:  reset acceleration at sencond layer
      if (m_config.default_acceleration.value > 0 && m_config.initial_layer_acceleration.value > 0) {
        gcode += m_writer.set_acceleration((unsigned int)floor(m_config.default_acceleration.value + 0.5));
      }
      if (m_config.default_jerk.value > 0 && m_config.initial_layer_jerk.value > 0) {
        gcode += m_writer.set_jerk_xy(m_config.default_jerk.value);
      }
        // Transition from 1st to 2nd layer. Adjust nozzle temperatures as prescribed by the nozzle dependent
        // nozzle_temperature_initial_layer vs. temperature settings.
        for (const Extruder &extruder : m_writer.extruders()) {
            if (print.config().single_extruder_multi_material.value && extruder.id() != m_writer.extruder()->id())
                // In single extruder multi material mode, set the temperature for the current extruder only.
                continue;
            int temperature = print.config().nozzle_temperature.get_at(extruder.id());
            if (temperature > 0 && temperature != print.config().nozzle_temperature_initial_layer.get_at(extruder.id()))
                gcode += m_writer.set_temperature(temperature, false, extruder.id());
        }
        // BBS
        int bed_temp = get_bed_temperature(first_extruder_id, false, print.config().curr_bed_type);
        gcode += m_writer.set_bed_temperature(bed_temp);
        // Mark the temperature transition from 1st to 2nd layer to be finished.
        m_second_layer_things_done = true;
    }
    // Map from extruder ID to <begin, end> index of skirt loops to be extruded with that extruder.
    std::map<unsigned int, std::pair<size_t, size_t>> skirt_loops_per_extruder;
    if (single_object_instance_idx == size_t(-1)) {
        // Normal (non-sequential) print.
        gcode += ProcessLayer::emit_custom_gcode_per_print_z(*this, layer_tools.custom_gcode, m_writer.extruder()->id(), first_extruder_id, print.config());
    }
    // Extrude skirt at the print_z of the raft layers and normal object layers
    // not at the print_z of the interlaced support material layers.
    skirt_loops_per_extruder = first_layer ?
        Skirt::make_skirt_loops_per_extruder_1st_layer(print, layer_tools, m_skirt_done) :
        Skirt::make_skirt_loops_per_extruder_other_layers(print, layer_tools, m_skirt_done);
    if (m_config.enable_overhang_speed && !m_config.overhang_speed_classic) {
        for (const auto &layer_to_print : layers) {
            m_extrusion_quality_estimator.prepare_for_new_layer(layer_to_print.original_object,
                                                                layer_to_print.object_layer);
        }
    }
    // Group extrusions by an extruder, then by an object, an island and a region.
    std::map<unsigned int, std::vector<ObjectByExtruder>> by_extruder;
    bool is_anything_overridden = const_cast<LayerTools&>(layer_tools).wiping_extrusions().is_anything_overridden();
    for (const LayerToPrint &layer_to_print : layers) {
        if (layer_to_print.support_layer != nullptr) {
            const SupportLayer &support_layer = *layer_to_print.support_layer;
            const PrintObject& object = *layer_to_print.original_object;
            if (! support_layer.support_fills.entities.empty()) {
                ExtrusionRole   role               = support_layer.support_fills.role();
                bool            has_support        = role == erMixed || role == erSupportMaterial || role == erSupportTransition;
                bool            has_interface      = role == erMixed || role == erSupportMaterialInterface;
                // Extruder ID of the support base. -1 if "don't care".
                unsigned int    support_extruder   = object.config().support_filament.value - 1;
                // Shall the support be printed with the active extruder, preferably with non-soluble, to avoid tool changes?
                bool            support_dontcare   = object.config().support_filament.value == 0;
                // Extruder ID of the support interface. -1 if "don't care".
                unsigned int    interface_extruder = object.config().support_interface_filament.value - 1;
                // Shall the support interface be printed with the active extruder, preferably with non-soluble, to avoid tool changes?
                bool            interface_dontcare = object.config().support_interface_filament.value == 0;
                // BBS: apply wiping overridden extruders
                WipingExtrusions& wiping_extrusions = const_cast<LayerTools&>(layer_tools).wiping_extrusions();
                if (support_dontcare) {
                    int extruder_override = wiping_extrusions.get_support_extruder_overrides(&object);
                    if (extruder_override >= 0) {
                        support_extruder = extruder_override;
                        support_dontcare = false;
                    }
                }
                if (interface_dontcare) {
                    int extruder_override = wiping_extrusions.get_support_interface_extruder_overrides(&object);
                    if (extruder_override >= 0) {
                        interface_extruder = extruder_override;
                        interface_dontcare = false;
                    }
                }
                // BBS: try to print support base with a filament other than interface filament
                if (support_dontcare && !interface_dontcare) {
                    unsigned int dontcare_extruder = first_extruder_id;
                    for (unsigned int extruder_id : layer_tools.extruders) {
                        if (print.config().filament_soluble.get_at(extruder_id))
                            continue;
                        if (extruder_id == interface_extruder)
                            continue;
                        dontcare_extruder = extruder_id;
                        break;
                    }
                    if (support_dontcare)
                        support_extruder = dontcare_extruder;
                }
                else if (support_dontcare || interface_dontcare) {
                    // Some support will be printed with "don't care" material, preferably non-soluble.
                    // Is the current extruder assigned a soluble filament?
                    unsigned int dontcare_extruder = first_extruder_id;
                    if (print.config().filament_soluble.get_at(dontcare_extruder)) {
                        // The last extruder printed on the previous layer extrudes soluble filament.
                        // Try to find a non-soluble extruder on the same layer.
                        for (unsigned int extruder_id : layer_tools.extruders)
                            if (! print.config().filament_soluble.get_at(extruder_id)) {
                                dontcare_extruder = extruder_id;
                                break;
                            }
                    }
                    if (support_dontcare)
                        support_extruder = dontcare_extruder;
                    if (interface_dontcare)
                        interface_extruder = dontcare_extruder;
                }
                // Both the support and the support interface are printed with the same extruder, therefore
                // the interface may be interleaved with the support base.
                bool single_extruder = ! has_support || support_extruder == interface_extruder;
                // Assign an extruder to the base.
                ObjectByExtruder &obj = object_by_extruder(by_extruder, has_support ? support_extruder : interface_extruder, &layer_to_print - layers.data(), layers.size());
                obj.support = &support_layer.support_fills;
                obj.support_extrusion_role = single_extruder ? erMixed : erSupportMaterial;
                if (! single_extruder && has_interface) {
                    ObjectByExtruder &obj_interface = object_by_extruder(by_extruder, interface_extruder, &layer_to_print - layers.data(), layers.size());
                    obj_interface.support = &support_layer.support_fills;
                    obj_interface.support_extrusion_role = erSupportMaterialInterface;
                }
            }
        }
        if (layer_to_print.object_layer != nullptr) {
            const Layer &layer = *layer_to_print.object_layer;
            // We now define a strategy for building perimeters and fills. The separation
            // between regions doesn't matter in terms of printing order, as we follow
            // another logic instead:
            // - we group all extrusions by extruder so that we minimize toolchanges
            // - we start from the last used extruder
            // - for each extruder, we group extrusions by island
            // - for each island, we extrude perimeters first, unless user set the infill_first
            //   option
            // (Still, we have to keep track of regions because we need to apply their config)
            size_t n_slices = layer.lslices.size();
            const std::vector<BoundingBox> &layer_surface_bboxes = layer.lslices_bboxes;
            // Traverse the slices in an increasing order of bounding box size, so that the islands inside another islands are tested first,
            // so we can just test a point inside ExPolygon::contour and we may skip testing the holes.
            std::vector<size_t> slices_test_order;
            slices_test_order.reserve(n_slices);
            for (size_t i = 0; i < n_slices; ++ i)
                slices_test_order.emplace_back(i);
            std::sort(slices_test_order.begin(), slices_test_order.end(), [&layer_surface_bboxes](size_t i, size_t j) {
                const Vec2d s1 = layer_surface_bboxes[i].size().cast<double>();
                const Vec2d s2 = layer_surface_bboxes[j].size().cast<double>();
                return s1.x() * s1.y() < s2.x() * s2.y();
            });
            auto point_inside_surface = [&layer, &layer_surface_bboxes](const size_t i, const Point &point) {
                const BoundingBox &bbox = layer_surface_bboxes[i];
                return point(0) >= bbox.min(0) && point(0) < bbox.max(0) &&
                       point(1) >= bbox.min(1) && point(1) < bbox.max(1) &&
                       layer.lslices[i].contour.contains(point);
            };
            for (size_t region_id = 0; region_id < layer.regions().size(); ++ region_id) {
                const LayerRegion *layerm = layer.regions()[region_id];
                if (layerm == nullptr)
                    continue;
                // PrintObjects own the PrintRegions, thus the pointer to PrintRegion would be unique to a PrintObject, they would not
                // identify the content of PrintRegion accross the whole print uniquely. Translate to a Print specific PrintRegion.
                const PrintRegion &region = print.get_print_region(layerm->region().print_region_id());
                // Now we must process perimeters and infills and create islands of extrusions in by_region std::map.
                // It is also necessary to save which extrusions are part of MM wiping and which are not.
                // The process is almost the same for perimeters and infills - we will do it in a cycle that repeats twice:
                std::vector<unsigned int> printing_extruders;
                for (const ObjectByExtruder::Island::Region::Type entity_type : { ObjectByExtruder::Island::Region::INFILL, ObjectByExtruder::Island::Region::PERIMETERS }) {
                    for (const ExtrusionEntity *ee : (entity_type == ObjectByExtruder::Island::Region::INFILL) ? layerm->fills.entities : layerm->perimeters.entities) {
                        // extrusions represents infill or perimeter extrusions of a single island.
                        assert(dynamic_cast<const ExtrusionEntityCollection*>(ee) != nullptr);
                        const auto *extrusions = static_cast<const ExtrusionEntityCollection*>(ee);
                        if (extrusions->entities.empty()) // This shouldn't happen but first_point() would fail.
                            continue;
                        // This extrusion is part of certain Region, which tells us which extruder should be used for it:
                        int correct_extruder_id = layer_tools.extruder(*extrusions, region);
                        // Let's recover vector of extruder overrides:
                        const WipingExtrusions::ExtruderPerCopy *entity_overrides = nullptr;
                        if (! layer_tools.has_extruder(correct_extruder_id)) {
                            // this entity is not overridden, but its extruder is not in layer_tools - we'll print it
                            // by last extruder on this layer (could happen e.g. when a wiping object is taller than others - dontcare extruders are eradicated from layer_tools)
                            correct_extruder_id = layer_tools.extruders.back();
                        }
                        printing_extruders.clear();
                        if (is_anything_overridden) {
                            entity_overrides = const_cast<LayerTools&>(layer_tools).wiping_extrusions().get_extruder_overrides(extrusions, layer_to_print.original_object, correct_extruder_id, layer_to_print.object()->instances().size());
                            if (entity_overrides == nullptr) {
                                printing_extruders.emplace_back(correct_extruder_id);
                            } else {
                                printing_extruders.reserve(entity_overrides->size());
                                for (int extruder : *entity_overrides)
                                    printing_extruders.emplace_back(extruder >= 0 ?
                                        // at least one copy is overridden to use this extruder
                                        extruder :
                                        // at least one copy would normally be printed with this extruder (see get_extruder_overrides function for explanation)
                                        static_cast<unsigned int>(- extruder - 1));
                                Slic3r::sort_remove_duplicates(printing_extruders);
                            }
                        } else
                            printing_extruders.emplace_back(correct_extruder_id);
                        // Now we must add this extrusion into the by_extruder map, once for each extruder that will print it:
                        for (unsigned int extruder : printing_extruders)
{
                            std::vector<ObjectByExtruder::Island> &islands = object_islands_by_extruder(
                                by_extruder,
                                extruder,
                                &layer_to_print - layers.data(),
                                layers.size(), n_slices+1);
                            for (size_t i = 0; i <= n_slices; ++ i) {
                                bool   last = i == n_slices;
                                size_t island_idx = last ? n_slices : slices_test_order[i];
                                if (// extrusions->first_point does not fit inside any slice
                                    last ||
                                    // extrusions->first_point fits inside ith slice
                                    point_inside_surface(island_idx, extrusions->first_point())) {
                                    if (islands[island_idx].by_region.empty())
                                        islands[island_idx].by_region.assign(print.num_print_regions(), ObjectByExtruder::Island::Region());
                                    islands[island_idx].by_region[region.print_region_id()].append(entity_type, extrusions, entity_overrides);
                                    break;
                                }
                            }
                        }
                    }
                }
            } // for regions
        }
    } // for objects
    if (m_wipe_tower)
        m_wipe_tower->set_is_first_print(true);
    // Extrude the skirt, brim, support, perimeters, infill ordered by the extruders.
    for (unsigned int extruder_id : layer_tools.extruders)
    {
        gcode += (layer_tools.has_wipe_tower && m_wipe_tower) ?
            m_wipe_tower->tool_change(*this, extruder_id, extruder_id == layer_tools.extruders.back()) :
            this->set_extruder(extruder_id, print_z);
        // let analyzer tag generator aware of a role type change
        if (layer_tools.has_wipe_tower && m_wipe_tower)
            m_last_processor_extrusion_role = erWipeTower;
        if (auto loops_it = skirt_loops_per_extruder.find(extruder_id); loops_it != skirt_loops_per_extruder.end()) {
            const std::pair<size_t, size_t> loops = loops_it->second;
            this->set_origin(0., 0.);
            m_avoid_crossing_perimeters.use_external_mp();
            Flow layer_skirt_flow = print.skirt_flow().with_height(float(m_skirt_done.back() - (m_skirt_done.size() == 1 ? 0. : m_skirt_done[m_skirt_done.size() - 2])));
            double mm3_per_mm = layer_skirt_flow.mm3_per_mm();
            for (size_t i = loops.first; i < loops.second; ++i) {
                // Adjust flow according to this layer's layer height.
                ExtrusionLoop loop = *dynamic_cast<const ExtrusionLoop*>(print.skirt().entities[i]);
                for (ExtrusionPath &path : loop.paths) {
                    path.height = layer_skirt_flow.height();
                    path.mm3_per_mm = mm3_per_mm;
                }
                //FIXME using the support_speed of the 1st object printed.
                gcode += this->extrude_loop(loop, "skirt", m_config.support_speed.value);
            }
            m_avoid_crossing_perimeters.use_external_mp(false);
            // Allow a straight travel move to the first object point if this is the first layer (but don't in next layers).
            if (first_layer && loops.first == 0)
                m_avoid_crossing_perimeters.disable_once();
        }
        auto objects_by_extruder_it = by_extruder.find(extruder_id);
        if (objects_by_extruder_it == by_extruder.end())
            continue;
        // BBS: ordering instances by extruder
        std::vector<InstanceToPrint> instances_to_print;
        bool has_prime_tower = print.config().enable_prime_tower
            && print.extruders().size() > 1
            && (print.config().print_sequence == PrintSequence::ByLayer
                || (print.config().print_sequence == PrintSequence::ByObject && print.objects().size() == 1));
        if (has_prime_tower) {
            int plate_idx = print.get_plate_index();
            Point wt_pos(print.config().wipe_tower_x.get_at(plate_idx), print.config().wipe_tower_y.get_at(plate_idx));
            std::vector<GCode::ObjectByExtruder>& objects_by_extruder = objects_by_extruder_it->second;
            std::vector<const PrintObject*> print_objects;
            for (int obj_idx = 0; obj_idx < objects_by_extruder.size(); obj_idx++) {
                auto& object_by_extruder = objects_by_extruder[obj_idx];
                if (object_by_extruder.islands.empty() && (object_by_extruder.support == nullptr || object_by_extruder.support->empty()))
                    continue;
                print_objects.push_back(print.get_object(obj_idx));
            }
            std::vector<const PrintInstance*> new_ordering = chain_print_object_instances(print_objects, &wt_pos);
            std::reverse(new_ordering.begin(), new_ordering.end());
            instances_to_print = sort_print_object_instances(objects_by_extruder_it->second, layers, &new_ordering, single_object_instance_idx);
        }
        else {
            instances_to_print = sort_print_object_instances(objects_by_extruder_it->second, layers, ordering, single_object_instance_idx);
        }
        // BBS
        if (print.config().print_sequence == PrintSequence::ByObject && prime_extruder && first_layer && extruder_id == first_extruder_id) {
            for (InstanceToPrint& instance_to_print : instances_to_print) {
                if (this->m_objSupportsWithBrim.find(instance_to_print.print_object.id()) != this->m_objSupportsWithBrim.end() &&
                    print.m_supportBrimMap.at(instance_to_print.print_object.id()).entities.size() > 0)
                    continue;
                if (this->m_objsWithBrim.find(instance_to_print.print_object.id()) != this->m_objsWithBrim.end() &&
                    print.m_brimMap.at(instance_to_print.print_object.id()).entities.size() > 0)
                    continue;
                const Point& offset = instance_to_print.print_object.instances()[instance_to_print.instance_id].shift;
                set_origin(unscaled(offset));
                for (ExtrusionEntity* ee : layer.object()->object_skirt().entities)
                    //FIXME using the support_speed of the 1st object printed.
                    gcode += this->extrude_entity(*ee, "skirt", m_config.support_speed.value);
            }
        }
        // We are almost ready to print. However, we must go through all the objects twice to print the the overridden extrusions first (infill/perimeter wiping feature):
        std::vector<ObjectByExtruder::Island::Region> by_region_per_copy_cache;
        for (int print_wipe_extrusions = is_anything_overridden; print_wipe_extrusions>=0; --print_wipe_extrusions) {
            if (is_anything_overridden && print_wipe_extrusions == 0)
                gcode+="; PURGING FINISHED\n";
            for (InstanceToPrint &instance_to_print : instances_to_print) {
                const auto& inst = instance_to_print.print_object.instances()[instance_to_print.instance_id];
                const LayerToPrint &layer_to_print = layers[instance_to_print.layer_id];
                // To control print speed of the 1st object layer printed over raft interface.
                bool object_layer_over_raft = layer_to_print.object_layer && layer_to_print.object_layer->id() > 0 &&
                    instance_to_print.print_object.slicing_parameters().raft_layers() == layer_to_print.object_layer->id();
                m_config.apply(instance_to_print.print_object.config(), true);
                m_layer = layer_to_print.layer();
                m_object_layer_over_raft = object_layer_over_raft;
                if (m_config.reduce_crossing_wall)
                    m_avoid_crossing_perimeters.init_layer(*m_layer);
                if (this->config().gcode_label_objects) {
                    gcode += std::string("; printing object ") + instance_to_print.print_object.model_object()->name +
                             " id:" + std::to_string(instance_to_print.print_object.get_id()) + " copy " +
                             std::to_string(inst.id) + "\n";
                }
                // exclude objects
                if (m_enable_exclude_object) {
                    if (is_BBL_Printer()) {
                        m_writer.set_object_start_str(
                            std::string("; start printing object, unique label id: ") +
                            std::to_string(instance_to_print.label_object_id) + "\n" + "M624 " +
                            _encode_label_ids_to_base64({instance_to_print.label_object_id}) + "\n");
                    } else if (print.config().gcode_flavor.value == gcfKlipper) {
                        m_writer.set_object_start_str(std::string("EXCLUDE_OBJECT_START NAME=") +
                                                      get_instance_name(&instance_to_print.print_object, inst.id) +
                                                      "\n");
                    }
                }
                if (m_config.enable_overhang_speed && !m_config.overhang_speed_classic)
                    m_extrusion_quality_estimator.set_current_object(&instance_to_print.print_object);
                // When starting a new object, use the external motion planner for the first travel move.
                const Point &offset = instance_to_print.print_object.instances()[instance_to_print.instance_id].shift;
                std::pair<const PrintObject*, Point> this_object_copy(&instance_to_print.print_object, offset);
                if (m_last_obj_copy != this_object_copy)
                    m_avoid_crossing_perimeters.use_external_mp_once();
                m_last_obj_copy = this_object_copy;
                this->set_origin(unscale(offset));
                if (instance_to_print.object_by_extruder.support != nullptr) {
                    m_layer = layers[instance_to_print.layer_id].support_layer;
                    m_object_layer_over_raft = false;
                    //BBS: print supports' brims first
                    if (this->m_objSupportsWithBrim.find(instance_to_print.print_object.id()) != this->m_objSupportsWithBrim.end() && !print_wipe_extrusions) {
                        this->set_origin(0., 0.);
                        m_avoid_crossing_perimeters.use_external_mp();
                        for (const ExtrusionEntity* ee : print.m_supportBrimMap.at(instance_to_print.print_object.id()).entities) {
                            gcode += this->extrude_entity(*ee, "brim", m_config.support_speed.value);
                        }
                        m_avoid_crossing_perimeters.use_external_mp(false);
                        // Allow a straight travel move to the first object point.
                        m_avoid_crossing_perimeters.disable_once();
                        this->m_objSupportsWithBrim.erase(instance_to_print.print_object.id());
                    }
                    // When starting a new object, use the external motion planner for the first travel move.
                    const Point& offset = instance_to_print.print_object.instances()[instance_to_print.instance_id].shift;
                    std::pair<const PrintObject*, Point> this_object_copy(&instance_to_print.print_object, offset);
                    if (m_last_obj_copy != this_object_copy)
                        m_avoid_crossing_perimeters.use_external_mp_once();
                    m_last_obj_copy = this_object_copy;
                    this->set_origin(unscale(offset));
                    ExtrusionEntityCollection support_eec;
                    // BBS
                    WipingExtrusions& wiping_extrusions = const_cast<LayerTools&>(layer_tools).wiping_extrusions();
                    bool support_overridden = wiping_extrusions.is_support_overridden(layer_to_print.original_object);
                    bool support_intf_overridden = wiping_extrusions.is_support_interface_overridden(layer_to_print.original_object);
                    ExtrusionRole support_extrusion_role = instance_to_print.object_by_extruder.support_extrusion_role;
                    bool is_overridden = support_extrusion_role == erSupportMaterialInterface ? support_intf_overridden : support_overridden;
                    if (is_overridden == (print_wipe_extrusions != 0))
                        gcode += this->extrude_support(
                            // support_extrusion_role is erSupportMaterial, erSupportTransition, erSupportMaterialInterface or erMixed for all extrusion paths.
                            instance_to_print.object_by_extruder.support->chained_path_from(m_last_pos, support_extrusion_role));
                    m_layer = layer_to_print.layer();
                    m_object_layer_over_raft = object_layer_over_raft;
                }
                //FIXME order islands?
                // Sequential tool path ordering of multiple parts within the same object, aka. perimeter tracking (#5511)
                for (ObjectByExtruder::Island &island : instance_to_print.object_by_extruder.islands) {
                    const auto& by_region_specific = is_anything_overridden ? island.by_region_per_copy(by_region_per_copy_cache, static_cast<unsigned int>(instance_to_print.instance_id), extruder_id, print_wipe_extrusions != 0) : island.by_region;
                    //BBS: add brim by obj by extruder
                    if (this->m_objsWithBrim.find(instance_to_print.print_object.id()) != this->m_objsWithBrim.end() && !print_wipe_extrusions) {
                        this->set_origin(0., 0.);
                        m_avoid_crossing_perimeters.use_external_mp();
                        for (const ExtrusionEntity* ee : print.m_brimMap.at(instance_to_print.print_object.id()).entities) {
                            gcode += this->extrude_entity(*ee, "brim", m_config.support_speed.value);
                        }
                        m_avoid_crossing_perimeters.use_external_mp(false);
                        // Allow a straight travel move to the first object point.
                        m_avoid_crossing_perimeters.disable_once();
                        this->m_objsWithBrim.erase(instance_to_print.print_object.id());
                    }
                    // When starting a new object, use the external motion planner for the first travel move.
                    const Point& offset = instance_to_print.print_object.instances()[instance_to_print.instance_id].shift;
                    std::pair<const PrintObject*, Point> this_object_copy(&instance_to_print.print_object, offset);
                    if (m_last_obj_copy != this_object_copy)
                        m_avoid_crossing_perimeters.use_external_mp_once();
                    m_last_obj_copy = this_object_copy;
                    this->set_origin(unscale(offset));
                    //FIXME the following code prints regions in the order they are defined, the path is not optimized in any way.
                    bool is_infill_first = print.default_region_config().wall_infill_order == WallInfillOrder::InfillInnerOuter ||
                                           print.default_region_config().wall_infill_order == WallInfillOrder::InfillOuterInner;
                    //BBS: for first layer, we always print wall firstly to get better bed adhesive force
                    //This behaviour is same with cura
                    if (is_infill_first && !first_layer) {
                        gcode += this->extrude_infill(print, by_region_specific, false);
                        gcode += this->extrude_perimeters(print, by_region_specific);
                    } else {
                        gcode += this->extrude_perimeters(print, by_region_specific);
                        gcode += this->extrude_infill(print,by_region_specific, false);
                    }
                    // ironing
                    gcode += this->extrude_infill(print,by_region_specific, true);
                }
                if (this->config().gcode_label_objects) {
                    gcode += std::string("; stop printing object ") +
                             instance_to_print.print_object.model_object()->name +
                             " id:" + std::to_string(instance_to_print.print_object.get_id()) + " copy " +
                             std::to_string(inst.id) + "\n";
                }
                // exclude objects
                // Don't set m_gcode_label_objects_end if you don't had to write the m_gcode_label_objects_start.
                if (!m_writer.is_object_start_str_empty()) {
                    m_writer.set_object_start_str("");
                } else if (m_enable_exclude_object) {
                    if (is_BBL_Printer()) {
                        m_writer.set_object_end_str(std::string("; stop printing object, unique label id: ") +
                                                    std::to_string(instance_to_print.label_object_id) + "\n" +
                                                    "M625\n");
                    } else if (print.config().gcode_flavor.value == gcfKlipper) {
                        m_writer.set_object_end_str(std::string("EXCLUDE_OBJECT_END NAME=") +
                                                    get_instance_name(&instance_to_print.print_object, inst.id) + "\n");
                    }
                }
            }
        }
    }
#if 0
    // Apply spiral vase post-processing if this layer contains suitable geometry
    // (we must feed all the G-code into the post-processor, including the first
    // bottom non-spiral layers otherwise it will mess with positions)
    // we apply spiral vase at this stage because it requires a full layer.
    // Just a reminder: A spiral vase mode is allowed for a single object per layer, single material print only.
    if (m_spiral_vase)
        gcode = m_spiral_vase->process_layer(std::move(gcode));
    // Apply cooling logic; this may alter speeds.
    if (m_cooling_buffer)
        gcode = m_cooling_buffer->process_layer(std::move(gcode), layer.id(),
            // Flush the cooling buffer at each object layer or possibly at the last layer, even if it contains just supports (This should not happen).
            object_layer || last_layer);
#ifdef HAS_PRESSURE_EQUALIZER
    // Apply pressure equalization if enabled;
    // printf("G-code before filter:\n%s\n", gcode.c_str());
    if (m_pressure_equalizer)
        gcode = m_pressure_equalizer->process(gcode.c_str(), false);
    // printf("G-code after filter:\n%s\n", out.c_str());
#endif /* HAS_PRESSURE_EQUALIZER */
    file.write(gcode);
#endif
    BOOST_LOG_TRIVIAL(trace) << "Exported layer " << layer.id() << " print_z " << print_z <<
    log_memory_info();
    result.gcode = std::move(gcode);
    result.cooling_buffer_flush = object_layer || raft_layer || last_layer;
    return result;
}
References Slic3r::Layer::bottom_z(), Slic3r::Print::calib_mode(), Slic3r::Print::calib_params(), Slic3r::chain_print_object_instances(), Slic3r::PrintObject::config(), Slic3r::Print::config(), Slic3r::LayerTools::custom_gcode, Slic3r::Print::default_region_config(), Slic3r::ExtrusionEntityCollection::empty(), Slic3r::ExtrusionEntityCollection::entities, EPSILON, Slic3r::erMixed, Slic3r::erSupportMaterial, Slic3r::erSupportMaterialInterface, Slic3r::erSupportTransition, Slic3r::erWipeTower, Slic3r::CustomGCode::Item::extruder, Slic3r::LayerTools::extruder(), Slic3r::LayerTools::extruders, Slic3r::Print::extruders(), Slic3r::LayerRegion::fills, floor(), Slic3r::gcfKlipper, Slic3r::get_instance_name(), Slic3r::Print::get_object(), Slic3r::PrintBase::get_plate_index(), Slic3r::Print::get_print_region(), Slic3r::WipingExtrusions::get_support_extruder_overrides(), Slic3r::WipingExtrusions::get_support_interface_extruder_overrides(), Slic3r::Print::has_brim(), Slic3r::LayerTools::has_extruder(), Slic3r::Print::has_infinite_skirt(), Slic3r::has_prime_tower(), Slic3r::LayerTools::has_wipe_tower, Slic3r::Flow::height(), Slic3r::Layer::id(), Slic3r::Print::is_BBL_printer(), Slic3r::is_decimal_separator_point(), Slic3r::WipingExtrusions::is_support_interface_overridden(), Slic3r::WipingExtrusions::is_support_overridden(), Slic3r::GCode::ObjectByExtruder::islands, Slic3r::GCode::LayerToPrint::layer(), Slic3r::log_memory_info(), Slic3r::Layer::lslices, Slic3r::Layer::lslices_bboxes, Slic3r::Print::m_brimMap, Slic3r::Print::m_supportBrimMap, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::Flow::mm3_per_mm(), Slic3r::Print::num_print_regions(), Slic3r::Layer::object(), Slic3r::object_by_extruder(), Slic3r::object_islands_by_extruder(), Slic3r::GCode::LayerToPrint::object_layer, Slic3r::PrintObject::object_skirt(), Slic3r::Print::objects(), Slic3r::GCode::LayerToPrint::original_object, Slic3r::LayerRegion::perimeters, Slic3r::PrintRegion::print_region_id(), Slic3r::Layer::print_z, Slic3r::SlicingParameters::raft_layers(), Slic3r::LayerRegion::region(), Slic3r::Layer::regions(), Slic3r::ExtrusionEntityCollection::role(), Slic3r::DynamicConfig::set_key_value(), Slic3r::ConstVectorOfPtrsAdaptor< T >::size(), size, Slic3r::Print::skirt(), Slic3r::Print::skirt_flow(), Slic3r::PrintObject::slicing_parameters(), Slic3r::sort_remove_duplicates(), Slic3r::Calib_Params::start, Slic3r::Calib_Params::step, Slic3r::GCode::ObjectByExtruder::support, Slic3r::GCode::ObjectByExtruder::support_extrusion_role, Slic3r::SupportLayer::support_fills, Slic3r::trace(), Slic3r::unscale(), Slic3r::unscaled(), and Slic3r::Flow::with_height().
Referenced by process_layers().
process_layers() [1/2]
void Slic3r::GCode::process_layers (const Print & print, const ToolOrdering & tool_ordering, const std::vector< const PrintInstance * > & print_object_instances_ordering, const std::vector< std::pair< coordf_t, std::vector< LayerToPrint > > > & layers_to_print, GCodeOutputStream & output_stream) private
{
    // The pipeline is variable: The vase mode filter is optional.
    size_t layer_to_print_idx = 0;
    const auto generator = tbb::make_filter<void, GCode::LayerResult>(slic3r_tbb_filtermode::serial_in_order,
        [this, &print, &tool_ordering, &print_object_instances_ordering, &layers_to_print, &layer_to_print_idx](tbb::flow_control& fc) -> GCode::LayerResult {
            if (layer_to_print_idx == layers_to_print.size()) {
                fc.stop();
                return {};
            } else {
                const std::pair<coordf_t, std::vector<LayerToPrint>>& layer = layers_to_print[layer_to_print_idx++];
                const LayerTools& layer_tools = tool_ordering.tools_for_layer(layer.first);
                print.set_status(80, Slic3r::format(_(L("Generating G-code: layer %1%")), std::to_string(layer_to_print_idx)));
                if (m_wipe_tower && layer_tools.has_wipe_tower)
                    m_wipe_tower->next_layer();
                //BBS
                check_placeholder_parser_failed();
                print.throw_if_canceled();
                return this->process_layer(print, layer.second, layer_tools, &layer == &layers_to_print.back(), &print_object_instances_ordering, size_t(-1));
            }
        });
    const auto spiral_mode = tbb::make_filter<GCode::LayerResult, GCode::LayerResult>(slic3r_tbb_filtermode::serial_in_order,
        [&spiral_mode = *this->m_spiral_vase.get()](GCode::LayerResult in) -> GCode::LayerResult {
            spiral_mode.enable(in.spiral_vase_enable);
            return { spiral_mode.process_layer(std::move(in.gcode)), in.layer_id, in.spiral_vase_enable, in.cooling_buffer_flush };
        });
    const auto cooling = tbb::make_filter<GCode::LayerResult, std::string>(slic3r_tbb_filtermode::serial_in_order,
        [&cooling_buffer = *this->m_cooling_buffer.get()](GCode::LayerResult in) -> std::string {
            return cooling_buffer.process_layer(std::move(in.gcode), in.layer_id, in.cooling_buffer_flush);
        });
    const auto output = tbb::make_filter<std::string, void>(slic3r_tbb_filtermode::serial_in_order,
        [&output_stream](std::string s) { output_stream.write(s); }
    );
    const auto fan_mover = tbb::make_filter<std::string, std::string>(slic3r_tbb_filtermode::serial_in_order,
            [&fan_mover = this->m_fan_mover, &config = this->config(), &writer = this->m_writer](std::string in)->std::string {
        CNumericLocalesSetter locales_setter;
        if (config.fan_speedup_time.value != 0 || config.fan_kickstart.value > 0) {
            if (fan_mover.get() == nullptr)
                fan_mover.reset(new Slic3r::FanMover(
                    writer,
                    std::abs((float)config.fan_speedup_time.value),
                    config.fan_speedup_time.value > 0,
                    config.use_relative_e_distances.value,
                    config.fan_speedup_overhangs.value,
                    (float)config.fan_kickstart.value));
            //flush as it's a whole layer
            return fan_mover->process_gcode(in, true);
        }
        return in;
    });
    // The pipeline elements are joined using const references, thus no copying is performed.
    if (m_spiral_vase)
        tbb::parallel_pipeline(12, generator & spiral_mode & cooling & fan_mover & output);
    else
        tbb::parallel_pipeline(12, generator & cooling & fan_mover & output);
}
References _, check_placeholder_parser_failed(), Slic3r::format(), Slic3r::LayerTools::has_wipe_tower, L, layer(), m_wipe_tower, process_layer(), Slic3r::PrintBase::set_status(), Slic3r::PrintBase::throw_if_canceled(), and Slic3r::ToolOrdering::tools_for_layer().
Referenced by _do_export().
process_layers() [2/2]
void Slic3r::GCode::process_layers (const Print & print, const ToolOrdering & tool_ordering, std::vector< LayerToPrint > layers_to_print, const size_t single_object_idx, GCodeOutputStream & output_stream, const bool prime_extruder = false) private
{
    // The pipeline is variable: The vase mode filter is optional.
    size_t layer_to_print_idx = 0;
    const auto generator = tbb::make_filter<void, GCode::LayerResult>(slic3r_tbb_filtermode::serial_in_order,
        [this, &print, &tool_ordering, &layers_to_print, &layer_to_print_idx, single_object_idx, prime_extruder](tbb::flow_control& fc) -> GCode::LayerResult {
            if (layer_to_print_idx == layers_to_print.size()) {
                fc.stop();
                return {};
            } else {
                LayerToPrint &layer = layers_to_print[layer_to_print_idx ++];
                print.set_status(80, Slic3r::format(_(L("Generating G-code: layer %1%")), std::to_string(layer_to_print_idx)));
                //BBS
                check_placeholder_parser_failed();
                print.throw_if_canceled();
                return this->process_layer(print, { std::move(layer) }, tool_ordering.tools_for_layer(layer.print_z()), &layer == &layers_to_print.back(), nullptr, single_object_idx, prime_extruder);
            }
        });
    const auto spiral_mode = tbb::make_filter<GCode::LayerResult, GCode::LayerResult>(slic3r_tbb_filtermode::serial_in_order,
        [&spiral_mode = *this->m_spiral_vase.get()](GCode::LayerResult in)->GCode::LayerResult {
            spiral_mode.enable(in.spiral_vase_enable);
            return { spiral_mode.process_layer(std::move(in.gcode)), in.layer_id, in.spiral_vase_enable, in.cooling_buffer_flush };
        });
    const auto cooling = tbb::make_filter<GCode::LayerResult, std::string>(slic3r_tbb_filtermode::serial_in_order,
        [&cooling_buffer = *this->m_cooling_buffer.get()](GCode::LayerResult in)->std::string {
            return cooling_buffer.process_layer(std::move(in.gcode), in.layer_id, in.cooling_buffer_flush);
        });
    const auto output = tbb::make_filter<std::string, void>(slic3r_tbb_filtermode::serial_in_order,
        [&output_stream](std::string s) { output_stream.write(s); }
    );
    const auto fan_mover = tbb::make_filter<std::string, std::string>(slic3r_tbb_filtermode::serial_in_order,
        [&fan_mover = this->m_fan_mover, &config = this->config(), &writer = this->m_writer](std::string in)->std::string {
        if (config.fan_speedup_time.value != 0 || config.fan_kickstart.value > 0) {
            if (fan_mover.get() == nullptr)
                fan_mover.reset(new Slic3r::FanMover(
                    writer,
                    std::abs((float)config.fan_speedup_time.value),
                    config.fan_speedup_time.value > 0,
                    config.use_relative_e_distances.value,
                    config.fan_speedup_overhangs.value,
                    (float)config.fan_kickstart.value));
            //flush as it's a whole layer
            return fan_mover->process_gcode(in, true);
        }
        return in;
    });
    // The pipeline elements are joined using const references, thus no copying is performed.
    if (m_spiral_vase)
        tbb::parallel_pipeline(12, generator & spiral_mode & cooling & fan_mover & output);
    else
        tbb::parallel_pipeline(12, generator & cooling & fan_mover & output);
}
References _, Slic3r::format(), L, Slic3r::GCode::LayerToPrint::print_z(), Slic3r::PrintBase::set_status(), Slic3r::PrintBase::throw_if_canceled(), and Slic3r::ToolOrdering::tools_for_layer().
retract()
std::string Slic3r::GCode::retract (bool toolchange = false, bool is_last_retraction = false, LiftType lift_type = LiftType::SpiralLift)
{
    std::string gcode;
    if (m_writer.extruder() == nullptr)
        return gcode;
    // wipe (if it's enabled for this extruder and we have a stored wipe path and no-zero wipe distance)
    if (EXTRUDER_CONFIG(wipe) && m_wipe.has_path() && scale_(EXTRUDER_CONFIG(wipe_distance)) > SCALED_EPSILON) {
        gcode += toolchange ? m_writer.retract_for_toolchange(true) : m_writer.retract(true);
        gcode += m_wipe.wipe(*this, toolchange, is_last_retraction);
    }
    /*  The parent class will decide whether we need to perform an actual retraction
        (the extruder might be already retracted fully or partially). We call these
        methods even if we performed wipe, since this will ensure the entire retraction
        length is honored in case wipe path was too short.  */
    gcode += toolchange ? m_writer.retract_for_toolchange() : m_writer.retract();
    gcode += m_writer.reset_e();
    // check if should + can lift (roughly from SuperSlicer)
    RetractLiftEnforceType retract_lift_type = RetractLiftEnforceType(EXTRUDER_CONFIG(retract_lift_enforce));
    bool needs_lift = toolchange
        || m_writer.extruder()->retraction_length() > 0
        || m_config.use_firmware_retraction;
    bool last_fill_extrusion_role_top_infill = (this->m_last_notgapfill_extrusion_role == ExtrusionRole::erTopSolidInfill || this->m_last_notgapfill_extrusion_role == ExtrusionRole::erIroning);
    // assume we can lift on retraction; conditions left explicit
    bool can_lift = true;
    if (retract_lift_type == RetractLiftEnforceType::rletAllSurfaces) {
        can_lift = true;
    }
    else if (this->m_layer_index == 0 && (retract_lift_type == RetractLiftEnforceType::rletBottomOnly || retract_lift_type == RetractLiftEnforceType::rletTopAndBottom)) {
        can_lift = true;
    }
    else if (retract_lift_type == RetractLiftEnforceType::rletTopOnly || retract_lift_type == RetractLiftEnforceType::rletTopAndBottom) {
        can_lift = last_fill_extrusion_role_top_infill;
    }
    else {
        can_lift = false;
    }
    if (needs_lift && can_lift) {
        size_t extruder_id = m_writer.extruder()->id();
        gcode += m_writer.lift(!m_spiral_vase ? lift_type : LiftType::NormalLift);
    }
    return gcode;
}
References EXTRUDER_CONFIG, scale_, and SCALED_EPSILON.
Referenced by _do_export(), and Slic3r::WipeTowerIntegration::append_tcr().
set_extruder()
std::string Slic3r::GCode::set_extruder (unsigned int extruder_id, double print_z)
{
    if (!m_writer.need_toolchange(extruder_id))
        return "";
    // if we are running a single-extruder setup, just set the extruder and return nothing
    if (!m_writer.multiple_extruders) {
        m_placeholder_parser.set("current_extruder", extruder_id);
        std::string gcode;
        // Append the filament start G-code.
        const std::string &filament_start_gcode = m_config.filament_start_gcode.get_at(extruder_id);
        if (! filament_start_gcode.empty()) {
            // Process the filament_start_gcode for the filament.
            gcode += this->placeholder_parser_process("filament_start_gcode", filament_start_gcode, extruder_id);
            check_add_eol(gcode);
        }
        if (m_config.enable_pressure_advance.get_at(extruder_id)) {
            gcode += m_writer.set_pressure_advance(m_config.pressure_advance.get_at(extruder_id));
        }
        gcode += m_writer.toolchange(extruder_id);
        return gcode;
    }
    // BBS. Should be placed before retract.
    m_toolchange_count++;
    // prepend retraction on the current extruder
    std::string gcode = this->retract(true, false);
    // Always reset the extrusion path, even if the tool change retract is set to zero.
    m_wipe.reset_path();
    if (m_writer.extruder() != nullptr) {
        // Process the custom filament_end_gcode. set_extruder() is only called if there is no wipe tower
        // so it should not be injected twice.
        unsigned int        old_extruder_id     = m_writer.extruder()->id();
        const std::string  &filament_end_gcode  = m_config.filament_end_gcode.get_at(old_extruder_id);
        if (! filament_end_gcode.empty()) {
            gcode += placeholder_parser_process("filament_end_gcode", filament_end_gcode, old_extruder_id);
            check_add_eol(gcode);
        }
    }
    // If ooze prevention is enabled, park current extruder in the nearest
    // standby point and set it to the standby temperature.
    if (m_ooze_prevention.enable && m_writer.extruder() != nullptr)
        gcode += m_ooze_prevention.pre_toolchange(*this);
    // BBS
    float new_retract_length = m_config.retraction_length.get_at(extruder_id);
    float new_retract_length_toolchange = m_config.retract_length_toolchange.get_at(extruder_id);
    int new_filament_temp = this->on_first_layer() ? m_config.nozzle_temperature_initial_layer.get_at(extruder_id): m_config.nozzle_temperature.get_at(extruder_id);
    // BBS: if print_z == 0 use first layer temperature
    if (abs(print_z) < EPSILON)
        new_filament_temp = m_config.nozzle_temperature_initial_layer.get_at(extruder_id);
    Vec3d nozzle_pos = m_writer.get_position();
    float old_retract_length, old_retract_length_toolchange, wipe_volume;
    int old_filament_temp, old_filament_e_feedrate;
    float filament_area = float((M_PI / 4.f) * pow(m_config.filament_diameter.get_at(extruder_id), 2));
    //BBS: add handling for filament change in start gcode
    int previous_extruder_id = -1;
    if (m_writer.extruder() != nullptr || m_start_gcode_filament != -1) {
        std::vector<float> flush_matrix(cast<float>(m_config.flush_volumes_matrix.values));
        const unsigned int number_of_extruders = (unsigned int)(sqrt(flush_matrix.size()) + EPSILON);
        if (m_writer.extruder() != nullptr)
            assert(m_writer.extruder()->id() < number_of_extruders);
        else
            assert(m_start_gcode_filament < number_of_extruders);
        previous_extruder_id = m_writer.extruder() != nullptr ? m_writer.extruder()->id() : m_start_gcode_filament;
        old_retract_length = m_config.retraction_length.get_at(previous_extruder_id);
        old_retract_length_toolchange = m_config.retract_length_toolchange.get_at(previous_extruder_id);
        old_filament_temp = this->on_first_layer()? m_config.nozzle_temperature_initial_layer.get_at(previous_extruder_id) : m_config.nozzle_temperature.get_at(previous_extruder_id);
        wipe_volume = flush_matrix[previous_extruder_id * number_of_extruders + extruder_id];
        wipe_volume *= m_config.flush_multiplier;
        old_filament_e_feedrate = (int)(60.0 * m_config.filament_max_volumetric_speed.get_at(previous_extruder_id) / filament_area);
        old_filament_e_feedrate = old_filament_e_feedrate == 0 ? 100 : old_filament_e_feedrate;
        //BBS: must clean m_start_gcode_filament
        m_start_gcode_filament = -1;
    } else {
        old_retract_length = 0.f;
        old_retract_length_toolchange = 0.f;
        old_filament_temp = 0;
        wipe_volume = 0.f;
        old_filament_e_feedrate = 200;
    }
    float wipe_length = wipe_volume / filament_area;
    int new_filament_e_feedrate = (int)(60.0 * m_config.filament_max_volumetric_speed.get_at(extruder_id) / filament_area);
    new_filament_e_feedrate = new_filament_e_feedrate == 0 ? 100 : new_filament_e_feedrate;
    DynamicConfig dyn_config;
    dyn_config.set_key_value("previous_extruder", new ConfigOptionInt(previous_extruder_id));
    dyn_config.set_key_value("next_extruder", new ConfigOptionInt((int)extruder_id));
    dyn_config.set_key_value("layer_num", new ConfigOptionInt(m_layer_index));
    dyn_config.set_key_value("layer_z", new ConfigOptionFloat(print_z));
    dyn_config.set_key_value("max_layer_z", new ConfigOptionFloat(m_max_layer_z));
    dyn_config.set_key_value("relative_e_axis", new ConfigOptionBool(m_config.use_relative_e_distances));
    dyn_config.set_key_value("toolchange_count", new ConfigOptionInt((int)m_toolchange_count));
    //BBS: fan speed is useless placeholer now, but we don't remove it to avoid
    //slicing error in old change_filament_gcode in old 3MF
    dyn_config.set_key_value("fan_speed", new ConfigOptionInt((int)0));
    dyn_config.set_key_value("old_retract_length", new ConfigOptionFloat(old_retract_length));
    dyn_config.set_key_value("new_retract_length", new ConfigOptionFloat(new_retract_length));
    dyn_config.set_key_value("old_retract_length_toolchange", new ConfigOptionFloat(old_retract_length_toolchange));
    dyn_config.set_key_value("new_retract_length_toolchange", new ConfigOptionFloat(new_retract_length_toolchange));
    dyn_config.set_key_value("old_filament_temp", new ConfigOptionInt(old_filament_temp));
    dyn_config.set_key_value("new_filament_temp", new ConfigOptionInt(new_filament_temp));
    dyn_config.set_key_value("x_after_toolchange", new ConfigOptionFloat(nozzle_pos(0)));
    dyn_config.set_key_value("y_after_toolchange", new ConfigOptionFloat(nozzle_pos(1)));
    dyn_config.set_key_value("z_after_toolchange", new ConfigOptionFloat(nozzle_pos(2)));
    dyn_config.set_key_value("first_flush_volume", new ConfigOptionFloat(wipe_length / 2.f));
    dyn_config.set_key_value("second_flush_volume", new ConfigOptionFloat(wipe_length / 2.f));
    dyn_config.set_key_value("old_filament_e_feedrate", new ConfigOptionInt(old_filament_e_feedrate));
    dyn_config.set_key_value("new_filament_e_feedrate", new ConfigOptionInt(new_filament_e_feedrate));
    dyn_config.set_key_value("travel_point_1_x", new ConfigOptionFloat(float(travel_point_1.x())));
    dyn_config.set_key_value("travel_point_1_y", new ConfigOptionFloat(float(travel_point_1.y())));
    dyn_config.set_key_value("travel_point_2_x", new ConfigOptionFloat(float(travel_point_2.x())));
    dyn_config.set_key_value("travel_point_2_y", new ConfigOptionFloat(float(travel_point_2.y())));
    dyn_config.set_key_value("travel_point_3_x", new ConfigOptionFloat(float(travel_point_3.x())));
    dyn_config.set_key_value("travel_point_3_y", new ConfigOptionFloat(float(travel_point_3.y())));
    int flush_count = std::min(g_max_flush_count, (int)std::round(wipe_volume / g_purge_volume_one_time));
    float flush_unit = wipe_length / flush_count;
    int flush_idx = 0;
    for (; flush_idx < flush_count; flush_idx++) {
        char key_value[64] = { 0 };
        snprintf(key_value, sizeof(key_value), "flush_length_%d", flush_idx + 1);
        dyn_config.set_key_value(key_value, new ConfigOptionFloat(flush_unit));
    }
    for (; flush_idx < g_max_flush_count; flush_idx++) {
        char key_value[64] = { 0 };
        snprintf(key_value, sizeof(key_value), "flush_length_%d", flush_idx + 1);
        dyn_config.set_key_value(key_value, new ConfigOptionFloat(0.f));
    }
    // Process the custom change_filament_gcode.
    const std::string& change_filament_gcode = m_config.change_filament_gcode.value;
    std::string toolchange_gcode_parsed;
    if (!change_filament_gcode.empty()) {
        toolchange_gcode_parsed = placeholder_parser_process("change_filament_gcode", change_filament_gcode, extruder_id, &dyn_config);
        check_add_eol(toolchange_gcode_parsed);
        gcode += toolchange_gcode_parsed;
        //BBS
        {
            //BBS: gcode writer doesn't know where the extruder is and whether fan speed is changed after inserting tool change gcode
            //Set this flag so that normal lift will be used the first time after tool change.
            gcode += ";_FORCE_RESUME_FAN_SPEED\n";
            m_writer.set_current_position_clear(false);
            //BBS: check whether custom gcode changes the z position. Update if changed
            double temp_z_after_tool_change;
            if (GCodeProcessor::get_last_z_from_gcode(toolchange_gcode_parsed, temp_z_after_tool_change)) {
                Vec3d pos = m_writer.get_position();
                pos(2) = temp_z_after_tool_change;
                m_writer.set_position(pos);
            }
        }
    }
    // BBS. Reset old extruder E-value.
    // Keep retract length because Custom GCode will guarantee retract length be the same as toolchange
    if (m_config.single_extruder_multi_material) {
        m_writer.reset_e();
    }
    // We inform the writer about what is happening, but we may not use the resulting gcode.
    std::string toolchange_command = m_writer.toolchange(extruder_id);
    if (! custom_gcode_changes_tool(toolchange_gcode_parsed, m_writer.toolchange_prefix(), extruder_id))
        gcode += toolchange_command;
    else {
        // user provided his own toolchange gcode, no need to do anything
    }
    // Set the temperature if the wipe tower didn't (not needed for non-single extruder MM)
    if (m_config.single_extruder_multi_material && !m_config.enable_prime_tower) {
        int temp = (m_layer_index <= 0 ? m_config.nozzle_temperature_initial_layer.get_at(extruder_id) :
                                         m_config.nozzle_temperature.get_at(extruder_id));
        gcode += m_writer.set_temperature(temp, false);
    }
    m_placeholder_parser.set("current_extruder", extruder_id);
    // Append the filament start G-code.
    const std::string &filament_start_gcode = m_config.filament_start_gcode.get_at(extruder_id);
    if (! filament_start_gcode.empty()) {
        // Process the filament_start_gcode for the new filament.
        gcode += this->placeholder_parser_process("filament_start_gcode", filament_start_gcode, extruder_id);
        check_add_eol(gcode);
    }
    // Set the new extruder to the operating temperature.
    if (m_ooze_prevention.enable)
        gcode += m_ooze_prevention.post_toolchange(*this);
    if (m_config.enable_pressure_advance.get_at(extruder_id)) {
        gcode += m_writer.set_pressure_advance(m_config.pressure_advance.get_at(extruder_id));
    }
    return gcode;
}
References Slic3r::check_add_eol(), Slic3r::custom_gcode_changes_tool(), EPSILON, Slic3r::g_max_flush_count, Slic3r::g_purge_volume_one_time, int, M_PI, Slic3r::DynamicConfig::set_key_value(), sqrt(), Slic3r::travel_point_1, Slic3r::travel_point_2, and Slic3r::travel_point_3.
Referenced by _do_export().
set_extruders()
void Slic3r::GCode::set_extruders (const std::vector< unsigned int > & extruder_ids) private
{
    m_writer.set_extruders(extruder_ids);
    // enable wipe path generation if any extruder has wipe enabled
    m_wipe.enable = false;
    for (auto id : extruder_ids)
        if (m_config.wipe.get_at(id)) {
            m_wipe.enable = true;
            break;
        }
}
Referenced by _do_export().
set_gcode_offset()
void Slic3r::GCode::set_gcode_offset (double x, double y) inline
{ m_writer.set_xy_offset(x, y); m_processor.set_xy_offset(x, y);}
References m_processor, m_writer, Slic3r::GCodeProcessor::set_xy_offset(), and Slic3r::GCodeWriter::set_xy_offset().
set_last_pos()
void Slic3r::GCode::set_last_pos (const Point & pos) inline private
{ m_last_pos = pos; m_last_pos_defined = true; }
References m_last_pos, and m_last_pos_defined.
Referenced by Slic3r::WipeTowerIntegration::append_tcr(), and Slic3r::Wipe::wipe().
set_layer_count()
void Slic3r::GCode::set_layer_count (unsigned int value) inline
{ m_layer_count = value; }
References m_layer_count.
set_object_info()
std::string Slic3r::GCode::set_object_info (Print * print)
{
    std::ostringstream gcode;
    size_t object_id = 0;
    for (PrintObject *object : print->objects()) {
        object->set_id(object_id++);
        size_t inst_id = 0;
        for (PrintInstance &inst : object->instances()) {
            inst.id = inst_id++;
            if (this->config().exclude_object && print->config().gcode_flavor.value == gcfKlipper) {
                auto bbox = inst.get_bounding_box();
                auto center = print->translate_to_print_space(Vec2d(bbox.center().x(), bbox.center().y()));
                gcode << "EXCLUDE_OBJECT_DEFINE NAME=" << get_instance_name(object, inst) << " CENTER=" << center.x()
                      << "," << center.y() << " POLYGON=" << polygon_to_string(inst.get_convex_hull_2d(), print)
                      << "\n";
            }
        }
    }
    return gcode.str();
}
References Slic3r::Print::config(), Slic3r::gcfKlipper, Slic3r::get_instance_name(), Slic3r::Print::objects(), Slic3r::polygon_to_string(), and Slic3r::Print::translate_to_print_space().
Referenced by _do_export().
set_origin() [1/2]
void Slic3r::GCode::set_origin (const coordf_t x, const coordf_t y) inline
{ this->set_origin(Vec2d(x, y)); }
References set_origin().
Referenced by set_origin().
set_origin() [2/2]
void Slic3r::GCode::set_origin (const Vec2d & pointf)
{
    // if origin increases (goes towards right), last_pos decreases because it goes towards left
    const Point translate(
        scale_(m_origin(0) - pointf(0)),
        scale_(m_origin(1) - pointf(1))
    );
    m_last_pos += translate;
    m_wipe.path.translate(translate);
    m_origin = pointf;
}
References scale_.
Referenced by _do_export().
sort_print_object_instances()
std::vector< GCode::InstanceToPrint > Slic3r::GCode::sort_print_object_instances (std::vector< ObjectByExtruder > & objects_by_extruder, const std::vector< LayerToPrint > & layers, const std::vector< const PrintInstance * > * ordering, const size_t single_object_instance_idx) private
{
    std::vector<InstanceToPrint> out;
    if (ordering == nullptr) {
        // Sequential print, single object is being printed.
        for (ObjectByExtruder &object_by_extruder : objects_by_extruder) {
            const size_t       layer_id     = &object_by_extruder - objects_by_extruder.data();
            //BBS:add the support of shared print object
            const PrintObject *print_object = layers[layer_id].original_object;
            //const PrintObject *print_object = layers[layer_id].object();
            if (print_object)
                out.emplace_back(object_by_extruder, layer_id, *print_object, single_object_instance_idx, print_object->instances()[single_object_instance_idx].model_instance->get_labeled_id());
        }
    } else {
        // Create mapping from PrintObject* to ObjectByExtruder*.
        std::vector<std::pair<const PrintObject*, ObjectByExtruder*>> sorted;
        sorted.reserve(objects_by_extruder.size());
        for (ObjectByExtruder &object_by_extruder : objects_by_extruder) {
            const size_t       layer_id     = &object_by_extruder - objects_by_extruder.data();
            //BBS:add the support of shared print object
            const PrintObject *print_object = layers[layer_id].original_object;
            //const PrintObject *print_object = layers[layer_id].object();
            if (print_object)
                sorted.emplace_back(print_object, &object_by_extruder);
        }
        std::sort(sorted.begin(), sorted.end());
        if (! sorted.empty()) {
            out.reserve(sorted.size());
            for (const PrintInstance *instance : *ordering) {
                const PrintObject &print_object = *instance->print_object;
                //BBS:add the support of shared print object
                //const PrintObject* print_obj_ptr = &print_object;
                //if (print_object.get_shared_object())
                //    print_obj_ptr = print_object.get_shared_object();
                std::pair<const PrintObject*, ObjectByExtruder*> key(&print_object, nullptr);
                auto it = std::lower_bound(sorted.begin(), sorted.end(), key);
                if (it != sorted.end() && it->first == &print_object)
                    // ObjectByExtruder for this PrintObject was found.
                    out.emplace_back(*it->second, it->second - objects_by_extruder.data(), print_object, instance - print_object.instances().data(), instance->model_instance->get_labeled_id());
            }
        }
    }
    return out;
}
References Slic3r::PrintObject::instances(), Slic3r::object_by_extruder(), and out.
to_lift_type()
LiftType Slic3r::GCode::to_lift_type (ZHopType z_hop_types) private
{
    switch (z_hop_types)
    {
    case ZHopType::zhtNormal:
        return LiftType::NormalLift;
    case ZHopType::zhtSlope:
        return LiftType::LazyLift;
    case ZHopType::zhtSpiral:
        return LiftType::SpiralLift;
    default:
        // if no corresponding lift type, use normal lift
        return LiftType::NormalLift;
    }
};
travel_to()
std::string Slic3r::GCode::travel_to (const Point & point, ExtrusionRole role, std::string comment)
{
    /*  Define the travel move as a line between current position and the taget point.
        This is expressed in print coordinates, so it will need to be translated by
        this->origin in order to get G-code coordinates.  */
    Polyline travel { this->last_pos(), point };
    // check whether a straight travel move would need retraction
    LiftType lift_type = LiftType::SpiralLift;
    bool needs_retraction = this->needs_retraction(travel, role, lift_type);
    // check whether wipe could be disabled without causing visible stringing
    bool could_be_wipe_disabled       = false;
    // Save state of use_external_mp_once for the case that will be needed to call twice m_avoid_crossing_perimeters.travel_to.
    const bool used_external_mp_once  = m_avoid_crossing_perimeters.used_external_mp_once();
    std::string gcode;
    // SoftFever
    if (this->on_first_layer()) {
        if (m_config.default_acceleration.value > 0 && m_config.initial_layer_acceleration.value > 0) {
            gcode += m_writer.set_acceleration((unsigned int)floor(m_config.initial_layer_acceleration.value + 0.5));
        }
        if (m_config.default_jerk.value > 0 && m_config.initial_layer_jerk.value > 0) {
            gcode += m_writer.set_jerk_xy(m_config.initial_layer_jerk.value);
        }
    } else {
        if (m_config.default_acceleration.value > 0 && m_config.travel_acceleration.value > 0) {
            gcode += m_writer.set_acceleration((unsigned int)floor(m_config.travel_acceleration.value + 0.5));
        }
        if (m_config.default_jerk.value > 0 && m_config.travel_jerk.value > 0) {
            gcode += m_writer.set_jerk_xy(m_config.travel_jerk.value);
        }
    }
    // if a retraction would be needed, try to use reduce_crossing_wall to plan a
    // multi-hop travel path inside the configuration space
    if (needs_retraction
        && m_config.reduce_crossing_wall
        && ! m_avoid_crossing_perimeters.disabled_once()
        //BBS: don't generate detour travel paths when current position is unclear
        && m_writer.is_current_position_clear()) {
        travel = m_avoid_crossing_perimeters.travel_to(*this, point, &could_be_wipe_disabled);
        // check again whether the new travel path still needs a retraction
        needs_retraction = this->needs_retraction(travel, role, lift_type);
        //if (needs_retraction && m_layer_index > 1) exit(0);
    }
    // Re-allow reduce_crossing_wall for the next travel moves
    m_avoid_crossing_perimeters.reset_once_modifiers();
    // generate G-code for the travel move
    if (needs_retraction) {
        if (m_config.reduce_crossing_wall && could_be_wipe_disabled)
            m_wipe.reset_path();
        Point last_post_before_retract = this->last_pos();
        gcode += this->retract(false, false, lift_type);
        // When "Wipe while retracting" is enabled, then extruder moves to another position, and travel from this position can cross perimeters.
        // Because of it, it is necessary to call avoid crossing perimeters again with new starting point after calling retraction()
        // FIXME Lukas H.: Try to predict if this second calling of avoid crossing perimeters will be needed or not. It could save computations.
        if (last_post_before_retract != this->last_pos() && m_config.reduce_crossing_wall) {
            // If in the previous call of m_avoid_crossing_perimeters.travel_to was use_external_mp_once set to true restore this value for next call.
            if (used_external_mp_once)
                m_avoid_crossing_perimeters.use_external_mp_once();
            travel = m_avoid_crossing_perimeters.travel_to(*this, point);
            // If state of use_external_mp_once was changed reset it to right value.
            if (used_external_mp_once)
                m_avoid_crossing_perimeters.reset_once_modifiers();
        }
    } else
        // Reset the wipe path when traveling, so one would not wipe along an old path.
        m_wipe.reset_path();
    // if needed, write the gcode_label_objects_end then gcode_label_objects_start
    m_writer.add_object_change_labels(gcode);
    // use G1 because we rely on paths being straight (G0 may make round paths)
    if (travel.size() >= 2) {
        for (size_t i = 1; i < travel.size(); ++ i) {
            // BBS. Process lazy layer change, but don't do lazy layer change when enable spiral vase
            Vec3d curr_pos = m_writer.get_position();
            if (i == 1 && !m_spiral_vase) {
                Vec2d dest2d = this->point_to_gcode(travel.points[i]);
                Vec3d dest3d(dest2d(0), dest2d(1), m_nominal_z);
                gcode += m_writer.travel_to_xyz(dest3d, comment+" travel_to_xyz");
            } else {
                gcode += m_writer.travel_to_xy(this->point_to_gcode(travel.points[i]), comment+" travel_to_xy");
            }
        }
        this->set_last_pos(travel.points.back());
    }
    return gcode;
}
References floor().
Referenced by _do_export(), and Slic3r::WipeTowerIntegration::append_tcr().
unretract()
std::string Slic3r::GCode::unretract () inline
{ return m_writer.unlift() + m_writer.unretract(); }
References m_writer, Slic3r::GCodeWriter::unlift(), and Slic3r::GCodeWriter::unretract().
Referenced by Slic3r::WipeTowerIntegration::append_tcr().
writer() [1/2]
GCodeWriter & Slic3r::GCode::writer () inline
{ return m_writer; }
References m_writer.
Referenced by Slic3r::CoolingBuffer::CoolingBuffer(), _do_export(), Slic3r::OozePrevention::_get_temp(), Slic3r::WipeTowerIntegration::append_tcr(), Slic3r::ProcessLayer::emit_custom_gcode_per_print_z(), Slic3r::WipeTowerIntegration::finalize(), Slic3r::need_wipe(), Slic3r::OozePrevention::post_toolchange(), Slic3r::OozePrevention::pre_toolchange(), Slic3r::CalibPressureAdvanceLine::print_pa_lines(), Slic3r::WipeTowerIntegration::tool_change(), and Slic3r::Wipe::wipe().
writer() [2/2]
const GCodeWriter & Slic3r::GCode::writer () const inline
{ return m_writer; }
References m_writer.
Friends And Related Symbol Documentation
object_by_extruder
ObjectByExtruder & object_by_extruder (std::map< unsigned int, std::vector< ObjectByExtruder > > & by_extruder, unsigned int extruder_id, size_t object_idx, size_t num_objects) friend
{
    std::vector<GCode::ObjectByExtruder> &objects_by_extruder = by_extruder[extruder_id];
    if (objects_by_extruder.empty())
        objects_by_extruder.assign(num_objects, GCode::ObjectByExtruder());
    return objects_by_extruder[object_idx];
}
object_islands_by_extruder
std::vector< ObjectByExtruder::Island > & object_islands_by_extruder (std::map< unsigned int, std::vector< ObjectByExtruder > > & by_extruder, unsigned int extruder_id, size_t object_idx, size_t num_objects, size_t num_islands) friend
{
    std::vector<GCode::ObjectByExtruder::Island> &islands = object_by_extruder(by_extruder, extruder_id, object_idx, num_objects).islands;
    if (islands.empty())
        islands.assign(num_islands, GCode::ObjectByExtruder::Island());
    return islands;
}
Print
friend class Print friend
Wipe
friend class Wipe friend
WipeTowerIntegration
friend class WipeTowerIntegration friend
Referenced by _do_export().
Member Data Documentation
m_avoid_crossing_perimeters
AvoidCrossingPerimeters Slic3r::GCode::m_avoid_crossing_perimeters private
Referenced by _do_export(), and Slic3r::WipeTowerIntegration::append_tcr().
m_brim_done
bool Slic3r::GCode::m_brim_done private
Referenced by _do_export().
m_calib_config
DynamicConfig Slic3r::GCode::m_calib_config private
Referenced by _do_export().
m_config
FullPrintConfig Slic3r::GCode::m_config private
Referenced by _do_export(), Slic3r::WipeTowerIntegration::append_tcr(), and config().
m_cooling_buffer
std::unique_ptr<CoolingBuffer> Slic3r::GCode::m_cooling_buffer private
Referenced by _do_export().
m_curr_print
Print* Slic3r::GCode::m_curr_print = nullptr private
Referenced by do_export(), and is_BBL_Printer().
m_enable_cooling_markers
bool Slic3r::GCode::m_enable_cooling_markers private
Referenced by _do_export(), and enable_cooling_markers().
m_enable_exclude_object
bool Slic3r::GCode::m_enable_exclude_object private
Referenced by _do_export(), and do_export().
m_enable_extrusion_role_markers
bool Slic3r::GCode::m_enable_extrusion_role_markers private
Referenced by _do_export().
m_enable_loop_clipping
bool Slic3r::GCode::m_enable_loop_clipping private
m_extrusion_quality_estimator
ExtrusionQualityEstimator Slic3r::GCode::m_extrusion_quality_estimator private
m_fan_mover
std::unique_ptr<FanMover> Slic3r::GCode::m_fan_mover private
Referenced by _do_export().
m_is_overhang_fan_on
bool Slic3r::GCode::m_is_overhang_fan_on private
Referenced by _do_export().
m_is_supp_interface_fan_on
bool Slic3r::GCode::m_is_supp_interface_fan_on private
Referenced by _do_export().
m_label_objects_ids
std::vector<size_t> Slic3r::GCode::m_label_objects_ids private
Referenced by _do_export().
m_last_extrusion_role
ExtrusionRole Slic3r::GCode::m_last_extrusion_role private
m_last_height
float Slic3r::GCode::m_last_height { 0.0f } private
Referenced by _do_export().
m_last_layer_z
float Slic3r::GCode::m_last_layer_z { 0.0f } private
Referenced by _do_export().
m_last_notgapfill_extrusion_role
ExtrusionRole Slic3r::GCode::m_last_notgapfill_extrusion_role private
m_last_obj_copy
std::pair<const PrintObject*, Point> Slic3r::GCode::m_last_obj_copy private
m_last_pos
Point Slic3r::GCode::m_last_pos private
Referenced by last_pos(), and set_last_pos().
m_last_pos_defined
bool Slic3r::GCode::m_last_pos_defined private
Referenced by last_pos_defined(), and set_last_pos().
m_last_processor_extrusion_role
ExtrusionRole Slic3r::GCode::m_last_processor_extrusion_role private
m_last_width
float Slic3r::GCode::m_last_width { 0.0f } private
Referenced by _do_export().
m_layer
const Layer* Slic3r::GCode::m_layer private
Referenced by layer(), layer_id(), and on_first_layer().
m_layer_count
unsigned int Slic3r::GCode::m_layer_count private
Referenced by _do_export(), layer_count(), and set_layer_count().
m_layer_index
int Slic3r::GCode::m_layer_index private
Referenced by _do_export(), and Slic3r::WipeTowerIntegration::append_tcr().
m_max_layer_z
float Slic3r::GCode::m_max_layer_z { 0.0f } private
Referenced by _do_export(), and Slic3r::WipeTowerIntegration::append_tcr().
m_need_change_layer_lift_z
bool Slic3r::GCode::m_need_change_layer_lift_z = false private
m_nominal_z
coordf_t Slic3r::GCode::m_nominal_z private
m_object_layer_over_raft
bool Slic3r::GCode::m_object_layer_over_raft private
Referenced by object_layer_over_raft().
m_objSupportsWithBrim
std::set<ObjectID> Slic3r::GCode::m_objSupportsWithBrim private
Referenced by _do_export().
m_objsWithBrim
std::set<ObjectID> Slic3r::GCode::m_objsWithBrim private
Referenced by _do_export().
m_ooze_prevention
OozePrevention Slic3r::GCode::m_ooze_prevention private
Referenced by _do_export().
m_origin
Vec2d Slic3r::GCode::m_origin private
Referenced by origin().
m_placeholder_parser
PlaceholderParser Slic3r::GCode::m_placeholder_parser private
Referenced by _do_export(), placeholder_parser(), and placeholder_parser().
m_placeholder_parser_context
PlaceholderParser::ContextData Slic3r::GCode::m_placeholder_parser_context private
Referenced by _do_export().
m_placeholder_parser_failed_templates
std::map<std::string, std::string> Slic3r::GCode::m_placeholder_parser_failed_templates private
Referenced by check_placeholder_parser_failed(), and do_export().
m_processor
GCodeProcessor Slic3r::GCode::m_processor private
Referenced by _do_export(), do_export(), and set_gcode_offset().
m_retract_when_crossing_perimeters
RetractWhenCrossingPerimeters Slic3r::GCode::m_retract_when_crossing_perimeters private
m_scaled_resolution
double Slic3r::GCode::m_scaled_resolution private
m_seam_placer
SeamPlacer Slic3r::GCode::m_seam_placer private
Referenced by _do_export().
m_second_layer_things_done
bool Slic3r::GCode::m_second_layer_things_done private
Referenced by _do_export().
m_silent_time_estimator_enabled
bool Slic3r::GCode::m_silent_time_estimator_enabled private
Referenced by _do_export().
m_skirt_done
std::vector<coordf_t> Slic3r::GCode::m_skirt_done private
m_spiral_vase
std::unique_ptr<SpiralVase> Slic3r::GCode::m_spiral_vase private
Referenced by _do_export().
m_start_gcode_filament
int Slic3r::GCode::m_start_gcode_filament = -1 private
Referenced by _do_export().
m_toolchange_count
unsigned int Slic3r::GCode::m_toolchange_count private
Referenced by Slic3r::WipeTowerIntegration::append_tcr().
m_wipe
Wipe Slic3r::GCode::m_wipe private
Referenced by Slic3r::WipeTowerIntegration::append_tcr().
m_wipe_tower
std::unique_ptr<WipeTowerIntegration> Slic3r::GCode::m_wipe_tower private
Referenced by _do_export(), and process_layers().
m_writer
GCodeWriter Slic3r::GCode::m_writer private
Referenced by _do_export(), Slic3r::WipeTowerIntegration::append_tcr(), do_export(), set_gcode_offset(), unretract(), writer(), and writer().
The documentation for this class was generated from the following files:
src/libslic3r/GCode.hpp
src/libslic3r/GCode.cpp