OrcaSlicer: Slic3r::GUI::OG_CustomCtrl::CtrlLine Struct Reference
Slic3r::GUI::OG_CustomCtrl::CtrlLine Struct Reference
Public Member Functions
CtrlLine (wxCoord height, OG_CustomCtrl *ctrl, const Line &og_line, bool draw_just_act_buttons=false, bool draw_mode_bitmap=true)
~CtrlLine ()
int get_max_win_width ()
void correct_items_positions ()
void msw_rescale ()
void update_visibility (ConfigOptionMode mode)
void render_separator (wxDC &dc, wxCoord v_pos)
void render (wxDC &dc, wxCoord h_pos, wxCoord v_pos)
wxCoord draw_text (wxDC &dc, wxPoint pos, const wxString &text, const wxColour *color, int width, bool is_url=false, bool is_main=false)
wxPoint draw_blinking_bmp (wxDC &dc, wxPoint pos, bool is_blinking)
wxCoord draw_act_bmps (wxDC &dc, wxPoint pos, const wxBitmap &bmp_undo_to_sys, const wxBitmap &bmp_undo, bool is_blinking, size_t rect_id=0)
bool launch_browser () const
bool is_separator () const
Public Attributes
wxCoord width { wxDefaultCoord }
wxCoord height { wxDefaultCoord }
OG_CustomCtrl * ctrl { nullptr }
const Line & og_line
bool draw_just_act_buttons { false }
bool draw_mode_bitmap { true }
bool is_visible { true }
bool is_focused { false }
std::vector< wxRect > rects_undo_icon
std::vector< wxRect > rects_undo_to_sys_icon
wxRect rect_label
Detailed Description
Constructor & Destructor Documentation
CtrlLine()
Slic3r::GUI::OG_CustomCtrl::CtrlLine::CtrlLine (wxCoord height, OG_CustomCtrl * ctrl, const Line & og_line, bool draw_just_act_buttons = false, bool draw_mode_bitmap = true)
                                                                      :
    height(height),
    ctrl(ctrl),
    og_line(og_line),
    draw_just_act_buttons(draw_just_act_buttons),
    draw_mode_bitmap(draw_mode_bitmap)
{
    for (size_t i = 0; i < og_line.get_options().size(); i++) {
        rects_undo_icon.emplace_back(wxRect());
        rects_undo_to_sys_icon.emplace_back(wxRect());
    }
}
References Slic3r::GUI::Line::get_options(), og_line, rects_undo_icon, rects_undo_to_sys_icon, and size.
~CtrlLine()
Slic3r::GUI::OG_CustomCtrl::CtrlLine::~CtrlLine () inline
{ ctrl = nullptr; }
References ctrl.
Member Function Documentation
correct_items_positions()
void Slic3r::GUI::OG_CustomCtrl::CtrlLine::correct_items_positions ()
{
    if (draw_just_act_buttons || !is_visible)
        return;
    if (og_line.near_label_widget_win)
        ctrl->correct_window_position(og_line.near_label_widget_win, og_line);
    if (og_line.widget_sizer)
        ctrl->correct_widgets_position(og_line.widget_sizer, og_line);
    if (og_line.extra_widget_sizer)
        ctrl->correct_widgets_position(og_line.extra_widget_sizer, og_line);
    const std::vector<Option>& option_set = og_line.get_options();
    for (auto opt : option_set) {
        Field* field = ctrl->opt_group->get_field(opt.opt_id);
        if (!field)
            continue;
        if (field->getSizer())
            ctrl->correct_widgets_position(field->getSizer(), og_line, field);
        else if (field->getWindow())
            ctrl->correct_window_position(field->getWindow(), og_line, field);
    }
}
References Slic3r::GUI::ctrl, Slic3r::GUI::Field::getSizer(), and Slic3r::GUI::Field::getWindow().
draw_act_bmps()
wxCoord Slic3r::GUI::OG_CustomCtrl::CtrlLine::draw_act_bmps (wxDC & dc, wxPoint pos, const wxBitmap & bmp_undo_to_sys, const wxBitmap & bmp_undo, bool is_blinking, size_t rect_id = 0)
{
#ifndef DISABLE_BLINKING
    pos = draw_blinking_bmp(dc, pos, is_blinking);
#else
    if (ctrl->opt_group->split_multi_line) { // BBS
        const std::vector<Option> &option_set = og_line.get_options();
        if (option_set.size() > 1)
            pos.y += lround(((height - ctrl->m_v_gap + ctrl->m_v_gap2) / option_set.size() - get_bitmap_size(bmp_undo).GetHeight()) / 2);
        else
            pos.y += lround((height - get_bitmap_size(bmp_undo).GetHeight()) / 2);
    } else {
        pos.y += lround((height - get_bitmap_size(bmp_undo).GetHeight()) / 2);
    }
#endif
    wxCoord h_pos = pos.x;
    wxCoord v_pos = pos.y;
#ifndef DISABLE_UNDO_SYS
    //BBS: GUI refactor
    dc.DrawBitmap(bmp_undo_to_sys, h_pos, v_pos);
    int bmp_dim = get_bitmap_size(bmp_undo_to_sys).GetWidth();
    rects_undo_to_sys_icon[rect_id] = wxRect(h_pos, v_pos, bmp_dim, bmp_dim);
    h_pos += bmp_dim + ctrl->m_h_gap;
#endif
    dc.DrawBitmap(og_line.undo_to_sys ? bmp_undo_to_sys : bmp_undo, h_pos, v_pos);
    int bmp_dim2 = get_bitmap_size(bmp_undo).GetWidth();
    (og_line.undo_to_sys ? rects_undo_to_sys_icon[rect_id] : rects_undo_icon[rect_id]) = wxRect(h_pos, v_pos, bmp_dim2, bmp_dim2);
    h_pos += bmp_dim2 + ctrl->m_h_gap;
    return h_pos;
}
References Slic3r::GUI::ctrl, and Slic3r::GUI::get_bitmap_size().
draw_blinking_bmp()
wxPoint Slic3r::GUI::OG_CustomCtrl::CtrlLine::draw_blinking_bmp (wxDC & dc, wxPoint pos, bool is_blinking)
{
    wxBitmap bmp_blinking = create_scaled_bitmap(is_blinking ? "blank_16" : "empty", ctrl);
    wxCoord h_pos = pos.x;
    wxCoord v_pos = pos.y + lround((height - get_bitmap_size(bmp_blinking).GetHeight()) / 2);
    dc.DrawBitmap(bmp_blinking, h_pos, v_pos);
    int bmp_dim = get_bitmap_size(bmp_blinking).GetWidth();
    h_pos += bmp_dim + ctrl->m_h_gap;
    return wxPoint(h_pos, v_pos);
}
References create_scaled_bitmap(), Slic3r::GUI::ctrl, and Slic3r::GUI::get_bitmap_size().
draw_text()
wxCoord Slic3r::GUI::OG_CustomCtrl::CtrlLine::draw_text (wxDC & dc, wxPoint pos, const wxString & text, const wxColour * color, int width, bool is_url = false, bool is_main = false)
{
    wxString multiline_text;
    auto size = Label::split_lines(dc, width, text, multiline_text);
    if (!text.IsEmpty()) {
        const wxString& out_text = multiline_text.IsEmpty() ? text : multiline_text;
        if (ctrl->opt_group->split_multi_line && !is_main) { // BBS
            const std::vector<Option> &option_set = og_line.get_options();
            pos.y = pos.y + lround(((height - ctrl->m_v_gap + ctrl->m_v_gap2) / option_set.size() - size.y) / 2);
        } else {
            pos.y = pos.y + lround((height - size.y) / 2);
        }
        if (width > 0)
            rect_label = wxRect(pos, wxSize(size.x, size.y));
        wxColour old_clr = dc.GetTextForeground();
        wxFont old_font = dc.GetFont();
        wxColor clr_url = StateColor::darkModeColorFor("#009688");
        if (is_focused && is_url) {
        // temporary workaround for the OSX because of strange Bold font behavior on BigSerf
#ifdef __APPLE__
            dc.SetFont(old_font.Underlined());
#else
            dc.SetFont(old_font.Bold().Underlined());
#endif
            color = &clr_url;
        }
        dc.SetTextForeground(color ? *color :
#ifdef _WIN32
            wxGetApp().get_label_clr_default());
#else
            wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOWTEXT));
#endif /* _WIN32 */
        dc.DrawText(out_text, pos);
        dc.SetTextForeground(old_clr);
        dc.SetFont(old_font);
        if (width < 1)
            width = size.x;
    }
    return pos.x + width + ctrl->m_h_gap;
}
References Slic3r::GUI::ctrl, StateColor::darkModeColorFor(), size, and Label::split_lines().
get_max_win_width()
int Slic3r::GUI::OG_CustomCtrl::CtrlLine::get_max_win_width ()
{
    int max_win_width = 0;
    if (!draw_just_act_buttons) {
        const std::vector<Option>& option_set = og_line.get_options();
        for (auto opt : option_set) {
            Field* field = ctrl->opt_group->get_field(opt.opt_id);
            if (field && field->getWindow())
                max_win_width = field->getWindow()->GetSize().GetWidth();
        }
    }
    return max_win_width;
}
References Slic3r::GUI::ctrl, and Slic3r::GUI::Field::getWindow().
is_separator()
bool Slic3r::GUI::OG_CustomCtrl::CtrlLine::is_separator () const inline
{ return og_line.is_separator(); }
References Slic3r::GUI::Line::is_separator(), and og_line.
launch_browser()
bool Slic3r::GUI::OG_CustomCtrl::CtrlLine::launch_browser () const
{
    if (!is_focused || og_line.label_path.empty())
        return false;
    return OptionsGroup::launch_browser(og_line.label_path);
}
References Slic3r::GUI::OptionsGroup::launch_browser().
msw_rescale()
void Slic3r::GUI::OG_CustomCtrl::CtrlLine::msw_rescale ()
{
    // if we have a single option with no label, no sidetext
    if (draw_just_act_buttons)
        height = get_bitmap_size(create_scaled_bitmap("empty")).GetHeight();
    if (ctrl->opt_group->label_width != 0 && !og_line.label.IsEmpty()) {
        wxSize label_sz = ctrl->GetTextExtent(og_line.label);
        if (ctrl->opt_group->split_multi_line) { // BBS
            const std::vector<Option> &option_set = og_line.get_options();
            if (option_set.size() > 1)
                height = (label_sz.y + ctrl->m_v_gap2) * option_set.size() + ctrl->m_v_gap - ctrl->m_v_gap2;
            else
                height = label_sz.y * (label_sz.GetWidth() > int(ctrl->opt_group->label_width * ctrl->m_em_unit) ? 2 : 1) + ctrl->m_v_gap;
        } else {
            height = label_sz.y * (label_sz.GetWidth() > int(ctrl->opt_group->label_width * ctrl->m_em_unit) ? 2 : 1) + ctrl->m_v_gap;
        }
    }
    correct_items_positions();
}
References create_scaled_bitmap(), Slic3r::GUI::ctrl, Slic3r::GUI::get_bitmap_size(), and int.
render()
void Slic3r::GUI::OG_CustomCtrl::CtrlLine::render (wxDC & dc, wxCoord h_pos, wxCoord v_pos)
To correct translation by context have to use wxGETTEXT_IN_CONTEXT macro from wxWidget 3.1.1
istead of (opt != option_set.back())
{
    if (is_separator()) {
        render_separator(dc, v_pos);
        return;
    }
    Field* field = ctrl->opt_group->get_field(og_line.get_options().front().opt_id);
    bool suppress_hyperlinks = false;
    if (draw_just_act_buttons) {
        //BBS: GUI refactor
        if (field && field->undo_bitmap())
        //if (field)
            // BBS: new layout
            draw_act_bmps(dc, wxPoint(h_pos, v_pos), field->undo_to_sys_bitmap()->bmp(), field->undo_bitmap()->bmp(), field->blink());
        return;
    }
    if (og_line.near_label_widget_win)
        h_pos += og_line.near_label_widget_win->GetSize().x + ctrl->m_h_gap;
    const std::vector<Option>& option_set = og_line.get_options();
    wxString label = og_line.label;
    wxColour blink_color = StateColor::darkModeColorFor("#009688");
    bool is_url_string = false;
    if (ctrl->opt_group->label_width != 0 && !label.IsEmpty()) {
        const wxColour* text_clr = field ? field->label_color() : og_line.full_Label_color;
        for (const Option& opt : option_set) {
            Field* field = ctrl->opt_group->get_field(opt.opt_id);
            if (field && field->blink()) {
                text_clr = &blink_color;
                break;
            }
        }
        is_url_string = !suppress_hyperlinks && !og_line.label_path.empty();
        // BBS
        h_pos = draw_text(dc, wxPoint(h_pos, v_pos), label /* + ":" */, text_clr, ctrl->opt_group->label_width * ctrl->m_em_unit, is_url_string, true);
    }
    // If there's a widget, build it and set result to the correct position.
#ifndef DISABLE_BLINKING
    if (og_line.widget != nullptr) {
        draw_blinking_bmp(dc, wxPoint(h_pos, v_pos), og_line.blink);
        return;
    }
#endif
    // If we're here, we have more than one option or a single option with sidetext
    // so we need a horizontal sizer to arrange these things
    auto add_field_width = [&h_pos, this] (Field* field) {
        if (field) {
            if (field->getSizer())
            {
                auto children = field->getSizer()->GetChildren();
                for (auto child : children)
                    if (child->IsWindow())
                        h_pos += child->GetWindow()->GetSize().x + ctrl->m_h_gap;
            }
            else if (field->getWindow()) {
                h_pos += field->getWindow()->GetSize().x + ctrl->m_h_gap;
            }
        }
    };
    auto draw_buttons = [&h_pos, &dc, &v_pos, this](Field* field, size_t bmp_rect_id = 0) {
        if (field && field->undo_to_sys_bitmap()) {
            h_pos = draw_act_bmps(dc, wxPoint(h_pos, v_pos), field->undo_to_sys_bitmap()->bmp(), field->undo_bitmap()->bmp(), field->blink(), bmp_rect_id);
        }
#ifndef DISABLE_BLINKING
        else if (field && !field->undo_to_sys_bitmap() && field->blink())
            draw_blinking_bmp(dc, wxPoint(h_pos, v_pos), field->blink());
#endif
    };
    wxCoord h_pos2 = h_pos;
    // If we have a single option with no sidetext just add it directly to the grid sizer
    if (option_set.size() == 1 && option_set.front().opt.sidetext.size() == 0 &&
        option_set.front().side_widget == nullptr && og_line.get_extra_widgets().size() == 0)
    {
        // BBS: new layout
        if (ctrl->opt_group->option_label_at_right)
            draw_buttons(field);
        add_field_width(field);
        wxCoord h_pos3 = h_pos;
        if (!ctrl->opt_group->option_label_at_right)
            draw_buttons(field);
        // update width for full_width fields
        if (option_set.front().opt.full_width && field && field->getWindow())
            field->getWindow()->SetSize(ctrl->GetSize().x - h_pos2 + h_pos3 - h_pos, -1);
        return;
    }
    size_t bmp_rect_id = 0;
    bool is_multioption_line = option_set.size() > 1;
    for (const Option& opt : option_set) {
        field = ctrl->opt_group->get_field(opt.opt_id);
        ConfigOptionDef option = opt.opt;
        if (ctrl->opt_group->option_label_at_right)
            draw_buttons(field, bmp_rect_id++);
        if (ctrl->opt_group->option_label_at_right) // BBS
            add_field_width(field);
        // add label if any
        if (is_multioption_line && !option.label.empty()) {
            label = (option.label == L_CONTEXT("Top", "Layers") || option.label == L_CONTEXT("Bottom", "Layers")) ?
                    _CTX(option.label, "Layers") : _(option.label);
            //if (!ctrl->opt_group->option_label_at_right) // BBS
                //label += ":";
            if (is_url_string)
                is_url_string = false;
            else if(opt == option_set.front())
                is_url_string = !suppress_hyperlinks && !og_line.label_path.empty();
            wxColor c = StateColor::darkModeColorFor("#6B6B6B");
            h_pos = draw_text(dc, wxPoint(h_pos, v_pos), label, field ? (field->blink() ? &blink_color : &c) : nullptr, ctrl->opt_group->sublabel_width * ctrl->m_em_unit, is_url_string);
            h_pos += 8;
        }
        // BBS: new layout
        // add field
        if (option_set.size() == 1 && option_set.front().opt.full_width)
            break;
        if (!ctrl->opt_group->option_label_at_right) // BBS
            add_field_width(field);
        // add sidetext if any
        // BBS: new layout
        wxCoord offset = 0;
        if (!field->combine_side_text() && (!option.sidetext.empty() || ctrl->opt_group->sidetext_width > 0)) {
            wxCoord h_pos2 = h_pos + dc.GetTextExtent(_(option.sidetext)).x;
            h_pos = draw_text(dc, wxPoint(h_pos, v_pos), _(option.sidetext), nullptr, ctrl->opt_group->sidetext_width * ctrl->m_em_unit);
            offset = h_pos - h_pos2;
        }
        // BBS: new layout
        if (!ctrl->opt_group->option_label_at_right) {
            offset -= ctrl->m_h_gap; h_pos -= offset;
            draw_buttons(field, bmp_rect_id++);
            h_pos += offset;
        }
        if (opt.opt_id != option_set.back().opt_id)
            h_pos += lround(0.6 * ctrl->m_em_unit);
        if (ctrl->opt_group->split_multi_line) { // BBS
            v_pos += (height - ctrl->m_v_gap + ctrl->m_v_gap2) / option_set.size();
            h_pos = h_pos2;
        }
    }
}
References _, _CTX, Slic3r::GUI::Field::blink(), ScalableBitmap::bmp(), Slic3r::GUI::Field::combine_side_text(), Slic3r::GUI::ctrl, StateColor::darkModeColorFor(), Slic3r::GUI::Field::getSizer(), Slic3r::GUI::Field::getWindow(), L_CONTEXT, Slic3r::ConfigOptionDef::label, Slic3r::GUI::Field::label_color(), Slic3r::offset(), Slic3r::ConfigOptionDef::sidetext, Slic3r::GUI::Field::undo_bitmap(), and Slic3r::GUI::Field::undo_to_sys_bitmap().
render_separator()
void Slic3r::GUI::OG_CustomCtrl::CtrlLine::render_separator (wxDC & dc, wxCoord v_pos)
{
    wxPoint begin(ctrl->m_h_gap, v_pos);
    wxPoint end(ctrl->GetSize().GetWidth() - ctrl->m_h_gap, v_pos);
    wxPen old_pen = dc.GetPen();
    // pen.SetColour(*wxLIGHT_GREY);
    dc.SetPen(*wxTRANSPARENT_PEN);
    dc.DrawLine(begin, end);
    dc.SetPen(old_pen);
}
References Slic3r::GUI::ctrl, and end.
update_visibility()
void Slic3r::GUI::OG_CustomCtrl::CtrlLine::update_visibility (ConfigOptionMode mode)
{
    if (og_line.is_separator())
        return;
    const std::vector<Option>& option_set = og_line.get_options();
    const ConfigOptionMode& line_mode = option_set.front().opt.mode;
    is_visible = og_line.toggle_visible && line_mode <= mode;
    if (draw_just_act_buttons)
        return;
    if (og_line.near_label_widget_win)
        og_line.near_label_widget_win->Show(is_visible);
    if (og_line.widget_sizer)
        og_line.widget_sizer->ShowItems(is_visible);
    if (og_line.extra_widget_sizer)
        og_line.extra_widget_sizer->ShowItems(is_visible);
    for (auto opt : option_set) {
        Field* field = ctrl->opt_group->get_field(opt.opt_id);
        if (!field)
            continue;
        if (field->getSizer()) {
            auto children = field->getSizer()->GetChildren();
            for (auto child : children)
                if (child->IsWindow())
                    child->GetWindow()->Show(is_visible);
        }
        else if (field->getWindow())
            field->getWindow()->Show(is_visible);
    }
    correct_items_positions();
}
References Slic3r::GUI::ctrl, Slic3r::GUI::Field::getSizer(), and Slic3r::GUI::Field::getWindow().
Member Data Documentation
ctrl
OG_CustomCtrl* Slic3r::GUI::OG_CustomCtrl::CtrlLine::ctrl { nullptr }
Referenced by ~CtrlLine().
draw_just_act_buttons
bool Slic3r::GUI::OG_CustomCtrl::CtrlLine::draw_just_act_buttons { false }
draw_mode_bitmap
bool Slic3r::GUI::OG_CustomCtrl::CtrlLine::draw_mode_bitmap { true }
height
wxCoord Slic3r::GUI::OG_CustomCtrl::CtrlLine::height { wxDefaultCoord }
is_focused
bool Slic3r::GUI::OG_CustomCtrl::CtrlLine::is_focused { false }
Referenced by Slic3r::GUI::OG_CustomCtrl::OnMotion().
is_visible
bool Slic3r::GUI::OG_CustomCtrl::CtrlLine::is_visible { true }
og_line
const Line& Slic3r::GUI::OG_CustomCtrl::CtrlLine::og_line
Referenced by CtrlLine(), is_separator(), and Slic3r::GUI::OG_CustomCtrl::OnMotion().
rect_label
wxRect Slic3r::GUI::OG_CustomCtrl::CtrlLine::rect_label
Referenced by Slic3r::GUI::OG_CustomCtrl::OnMotion().
rects_undo_icon
std::vector<wxRect> Slic3r::GUI::OG_CustomCtrl::CtrlLine::rects_undo_icon
Referenced by CtrlLine().
rects_undo_to_sys_icon
std::vector<wxRect> Slic3r::GUI::OG_CustomCtrl::CtrlLine::rects_undo_to_sys_icon
Referenced by CtrlLine().
width
wxCoord Slic3r::GUI::OG_CustomCtrl::CtrlLine::width { wxDefaultCoord }
The documentation for this struct was generated from the following files:
src/slic3r/GUI/OG_CustomCtrl.hpp
src/slic3r/GUI/OG_CustomCtrl.cpp