OrcaSlicer: Slic3r::Layer Class Reference
Slic3r::Layer Class Reference
#include <src/libslic3r/Layer.hpp>
Public Member Functions
size_t id () const
void set_id (size_t id)
PrintObject * object ()
const PrintObject * object () const
coordf_t bottom_z () const
size_t region_count () const
const LayerRegion * get_region (int idx) const
LayerRegion * get_region (int idx)
LayerRegion * add_region (const PrintRegion *print_region)
const LayerRegionPtrs & regions () const
bool empty () const
void make_slices ()
void backup_untyped_slices ()
void restore_untyped_slices ()
void restore_untyped_slices_no_extra_perimeters ()
ExPolygons merged (float offset) const
template<class T >
bool any_internal_region_slice_contains (const T &item) const
template<class T >
bool any_bottom_region_slice_contains (const T &item) const
void make_perimeters ()
void make_fills ()
void make_fills (FillAdaptive::Octree *adaptive_fill_octree, FillAdaptive::Octree *support_fill_octree, FillLightning::Generator *lightning_generator=nullptr)
void make_ironing ()
void export_region_slices_to_svg (const char *path) const
void export_region_fill_surfaces_to_svg (const char *path) const
void export_region_slices_to_svg_debug (const char *name) const
void export_region_fill_surfaces_to_svg_debug (const char *name) const
virtual bool has_extrusions () const
void simplify_wall_extrusion_path ()
void simplify_infill_extrusion_path ()
coordf_t get_sparse_infill_max_void_area ()
Static Public Member Functions
template<typename IteratorType , typename IndexType , typename FN_HIGHER_EQUAL >
static IndexType idx_higher_or_equal (IteratorType begin, IteratorType end, IndexType idx, FN_HIGHER_EQUAL fn_higher_equal)
Public Attributes
Layer * upper_layer
Layer * lower_layer
bool slicing_errors
coordf_t slice_z
coordf_t print_z
coordf_t height
ExPolygons sharp_tails
ExPolygons cantilevers
std::map< const ExPolygon *, float > sharp_tails_height
ExPolygons lslices
std::vector< BoundingBox > lslices_bboxes
ExPolygons loverhangs
BoundingBox loverhangs_bbox
Protected Member Functions
Layer (size_t id, PrintObject *object, coordf_t height, coordf_t print_z, coordf_t slice_z)
virtual ~Layer ()
void simplify_support_entity_collection (ExtrusionEntityCollection *entity_collection)
void simplify_support_path (ExtrusionPath *path)
void simplify_support_multi_path (ExtrusionMultiPath *multipath)
void simplify_support_loop (ExtrusionLoop *loop)
Private Attributes
size_t m_id
PrintObject * m_object
LayerRegionPtrs m_regions
Friends
class PrintObject
std::vector< Layer * > new_layers (PrintObject *, const std::vector< coordf_t > &)
std::string fix_slicing_errors (PrintObject *object, LayerPtrs &, const std::function< void()> &, int &)
Detailed Description
Constructor & Destructor Documentation
Layer()
Slic3r::Layer::Layer (size_t id, PrintObject * object, coordf_t height, coordf_t print_z, coordf_t slice_z) inline protected
                                                                                               :
        upper_layer(nullptr), lower_layer(nullptr), slicing_errors(false),
        slice_z(slice_z), print_z(print_z), height(height),
        m_id(id), m_object(object) {}
~Layer()
Slic3r::Layer::~Layer () protected virtual
{
    this->lower_layer = this->upper_layer = nullptr;
    for (LayerRegion *region : m_regions)
        delete region;
    m_regions.clear();
}
References lower_layer, m_regions, and upper_layer.
Member Function Documentation
add_region()
LayerRegion * Slic3r::Layer::add_region (const PrintRegion * print_region)
{
    m_regions.emplace_back(new LayerRegion(this, print_region));
    return m_regions.back();
}
References m_regions.
any_bottom_region_slice_contains()
template<class T > bool Slic3r::Layer::any_bottom_region_slice_contains (const T & item) const inline
{
        for (const LayerRegion *layerm : m_regions) if (layerm->slices.any_bottom_contains(item)) return true;
        return false;
    }
References m_regions.
any_internal_region_slice_contains()
template<class T > bool Slic3r::Layer::any_internal_region_slice_contains (const T & item) const inline
{
        for (const LayerRegion *layerm : m_regions) if (layerm->slices.any_internal_contains(item)) return true;
        return false;
    }
References m_regions.
backup_untyped_slices()
void Slic3r::Layer::backup_untyped_slices ()
{
    if (layer_needs_raw_backup(this)) {
        for (LayerRegion *layerm : m_regions)
            layerm->raw_slices = to_expolygons(layerm->slices.surfaces);
    } else {
        assert(m_regions.size() == 1);
        m_regions.front()->raw_slices.clear();
    }
}
References Slic3r::layer_needs_raw_backup(), m_regions, and Slic3r::to_expolygons().
bottom_z()
coordf_t Slic3r::Layer::bottom_z () const inline
{ return this->print_z - this->height; }
References height.
Referenced by Slic3r::PrintObject::discover_vertical_shells(), Slic3r::TreeSupport::get_trim_support_regions(), Slic3r::getExtrusionPathsFromSupportLayer(), Slic3r::new_contact_layer(), Slic3r::GCode::on_first_layer(), Slic3r::GCode::process_layer(), and Slic3r::PrintObjectSupportMaterial::trim_support_layers_by_object().
empty()
bool Slic3r::Layer::empty () const
{
  for (const LayerRegion *layerm : m_regions)
        if (layerm != nullptr && ! layerm->slices.empty())
            // Non empty layer.
            return false;
    return true;
}
References m_regions.
Referenced by Slic3r::PrintObject::apply_conical_overhang(), Slic3r::LayerRegion::process_external_surfaces(), and Slic3r::PrintObject::slice_volumes().
export_region_fill_surfaces_to_svg()
void Slic3r::Layer::export_region_fill_surfaces_to_svg (const char * path) const
{
    BoundingBox bbox;
    for (const auto *region : m_regions)
        for (const auto &surface : region->slices.surfaces)
            bbox.merge(get_extents(surface.expolygon));
    Point legend_size = export_surface_type_legend_to_svg_box_size();
    Point legend_pos(bbox.min(0), bbox.max(1));
    bbox.merge(Point(std::max(bbox.min(0) + legend_size(0), bbox.max(0)), bbox.max(1) + legend_size(1)));
    SVG svg(path, bbox);
    const float transparency = 0.5f;
    for (const auto *region : m_regions)
        for (const auto &surface : region->slices.surfaces)
            svg.draw(surface.expolygon, surface_type_to_color_name(surface.surface_type), transparency);
    export_surface_type_legend_to_svg(svg, legend_pos);
    svg.Close();
}
References Slic3r::SVG::Close(), Slic3r::SVG::draw(), Slic3r::export_surface_type_legend_to_svg(), Slic3r::export_surface_type_legend_to_svg_box_size(), Slic3r::get_extents(), m_regions, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::min, and Slic3r::surface_type_to_color_name().
Referenced by export_region_fill_surfaces_to_svg_debug().
export_region_fill_surfaces_to_svg_debug()
void Slic3r::Layer::export_region_fill_surfaces_to_svg_debug (const char * name) const
{
    static size_t idx = 0;
    this->export_region_fill_surfaces_to_svg(debug_out_path("Layer-fill_surfaces-%s-%d.svg", name, idx ++).c_str());
}
References Slic3r::debug_out_path(), and export_region_fill_surfaces_to_svg().
export_region_slices_to_svg()
void Slic3r::Layer::export_region_slices_to_svg (const char * path) const
{
    BoundingBox bbox;
    for (const auto *region : m_regions)
        for (const auto &surface : region->slices.surfaces)
            bbox.merge(get_extents(surface.expolygon));
    Point legend_size = export_surface_type_legend_to_svg_box_size();
    Point legend_pos(bbox.min(0), bbox.max(1));
    bbox.merge(Point(std::max(bbox.min(0) + legend_size(0), bbox.max(0)), bbox.max(1) + legend_size(1)));
    SVG svg(path, bbox);
    const float transparency = 0.5f;
    for (const auto *region : m_regions)
        for (const auto &surface : region->slices.surfaces)
            svg.draw(surface.expolygon, surface_type_to_color_name(surface.surface_type), transparency);
    export_surface_type_legend_to_svg(svg, legend_pos);
    svg.Close();
}
References Slic3r::SVG::Close(), Slic3r::SVG::draw(), Slic3r::export_surface_type_legend_to_svg(), Slic3r::export_surface_type_legend_to_svg_box_size(), Slic3r::get_extents(), m_regions, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::min, and Slic3r::surface_type_to_color_name().
Referenced by export_region_slices_to_svg_debug().
export_region_slices_to_svg_debug()
void Slic3r::Layer::export_region_slices_to_svg_debug (const char * name) const
{
    static size_t idx = 0;
    this->export_region_slices_to_svg(debug_out_path("Layer-slices-%s-%d.svg", name, idx ++).c_str());
}
References Slic3r::debug_out_path(), and export_region_slices_to_svg().
get_region() [1/2]
LayerRegion * Slic3r::Layer::get_region (int idx) inline
{ return m_regions[idx]; }
References m_regions.
get_region() [2/2]
const LayerRegion * Slic3r::Layer::get_region (int idx) const inline
{ return m_regions[idx]; }
References m_regions.
Referenced by Slic3r::apply_mm_segmentation(), Slic3r::PrintObject::detect_surfaces_type(), and Slic3r::extract_layer().
get_sparse_infill_max_void_area()
coordf_t Slic3r::Layer::get_sparse_infill_max_void_area ()
{
    double max_void_area = 0.;
    for (auto layerm : m_regions) {
        Flow flow = layerm->flow(frInfill);
        float density = layerm->region().config().sparse_infill_density;
        InfillPattern pattern = layerm->region().config().sparse_infill_pattern;
        if (density == 0.)
            return -1;
        //BBS: rough estimation and need to be optimized
        double spacing = flow.scaled_spacing() * (100 - density) / density;
        switch (pattern) {
            case ipConcentric:
            case ipRectilinear:
            case ipLine:
            case ipGyroid:
            case ipAlignedRectilinear:
            case ipOctagramSpiral:
            case ipHilbertCurve:
            case ip3DHoneycomb:
            case ipArchimedeanChords:
                max_void_area = std::max(max_void_area, spacing * spacing);
                break;
            case ipGrid:
            case ipHoneycomb:
            case ipLightning:
                max_void_area = std::max(max_void_area, 4.0 * spacing * spacing);
                break;
            case ipCubic:
            case ipAdaptiveCubic:
            case ipTriangles:
            case ipStars:
            case ipSupportCubic:
                max_void_area = std::max(max_void_area, 4.5 * spacing * spacing);
                break;
            default:
                max_void_area = std::max(max_void_area, spacing * spacing);
                break;
        }
    };
    return max_void_area;
}
References Slic3r::frInfill, Slic3r::ip3DHoneycomb, Slic3r::ipAdaptiveCubic, Slic3r::ipAlignedRectilinear, Slic3r::ipArchimedeanChords, Slic3r::ipConcentric, Slic3r::ipCubic, Slic3r::ipGrid, Slic3r::ipGyroid, Slic3r::ipHilbertCurve, Slic3r::ipHoneycomb, Slic3r::ipLightning, Slic3r::ipLine, Slic3r::ipOctagramSpiral, Slic3r::ipRectilinear, Slic3r::ipStars, Slic3r::ipSupportCubic, Slic3r::ipTriangles, m_regions, and Slic3r::Flow::scaled_spacing().
Referenced by Slic3r::LayerRegion::process_external_surfaces().
has_extrusions()
virtual bool Slic3r::Layer::has_extrusions () const inline virtual
Reimplemented in Slic3r::SupportLayer.
{ for (auto layerm : m_regions) if (layerm->has_extrusions()) return true; return false; }
References m_regions.
Referenced by Slic3r::GCode::collect_layers_to_print().
id()
size_t Slic3r::Layer::id () const inline
{ return m_id; }
References m_id.
Referenced by Slic3r::OozePrevention::_get_temp(), Slic3r::avoid_perimeters(), Slic3r::PrintObject::bridge_over_infill(), Slic3r::PrintObject::combine_infill(), Slic3r::convert_layer_region_from_json(), Slic3r::TreeSupport::create_tree_support_layers(), Slic3r::extract_support_layer(), Slic3r::LayerRegion::flow(), Slic3r::group_fills(), Slic3r::GCode::layer_id(), make_fills(), make_ironing(), make_perimeters(), Slic3r::LayerRegion::make_perimeters(), Slic3r::new_contact_layer(), Slic3r::GCode::on_first_layer(), Slic3r::SeamPlacer::place_seam(), Slic3r::GCode::process_layer(), and set_id().
idx_higher_or_equal()
template<typename IteratorType , typename IndexType , typename FN_HIGHER_EQUAL > static IndexType Slic3r::Layer::idx_higher_or_equal (IteratorType begin, IteratorType end, IndexType idx, FN_HIGHER_EQUAL fn_higher_equal) inline static
    {
        auto size = int(end - begin);
        if (size == 0) {
            idx = 0;
            }
        else if (idx == IndexType(-1)) {
            // First of the batch of layers per thread pool invocation. Use binary search.
            int idx_low = 0;
            int idx_high = std::max(0, size - 1);
            while (idx_low + 1 < idx_high) {
                int idx_mid = (idx_low + idx_high) / 2;
                if (fn_higher_equal(begin[idx_mid]))
                    idx_high = idx_mid;
                else
                    idx_low = idx_mid;
                }
            idx = fn_higher_equal(begin[idx_low]) ? idx_low :
                (fn_higher_equal(begin[idx_high]) ? idx_high : size);
            }
        else {
            // For the other layers of this batch of layers, search incrementally, which is cheaper than the binary search.
            while (int(idx) < size && !fn_higher_equal(begin[idx]))
                ++idx;
            }
        return idx;
    }
References end, int, and size.
make_fills() [1/2]
void Slic3r::Layer::make_fills () inline
{ this->make_fills(nullptr, nullptr); }
References make_fills().
Referenced by make_fills().
make_fills() [2/2]
void Slic3r::Layer::make_fills (FillAdaptive::Octree * adaptive_fill_octree, FillAdaptive::Octree * support_fill_octree, FillLightning::Generator * lightning_generator = nullptr)
{
  for (LayerRegion *layerm : m_regions)
    layerm->fills.clear();
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
//  this->export_region_fill_surfaces_to_svg_debug("10_fill-initial");
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
  std::vector<SurfaceFill>  surface_fills = group_fills(*this);
  const Slic3r::BoundingBox bbox      = this->object()->bounding_box();
  const auto                resolution  = this->object()->print()->config().resolution.value;
#ifdef SLIC3R_DEBUG_SLICE_PROCESSING
  {
    static int iRun = 0;
    export_group_fills_to_svg(debug_out_path("Layer-fill_surfaces-10_fill-final-%d.svg", iRun ++).c_str(), surface_fills);
  }
#endif /* SLIC3R_DEBUG_SLICE_PROCESSING */
    for (SurfaceFill &surface_fill : surface_fills) {
        // Create the filler object.
        std::unique_ptr<Fill> f = std::unique_ptr<Fill>(Fill::new_from_type(surface_fill.params.pattern));
        f->set_bounding_box(bbox);
        f->layer_id = this->id();
        f->z    = this->print_z;
        f->angle  = surface_fill.params.angle;
        f->adapt_fill_octree = (surface_fill.params.pattern == ipSupportCubic) ? support_fill_octree : adaptive_fill_octree;
    if (surface_fill.params.pattern == ipConcentricInternal) {
            FillConcentricInternal *fill_concentric = dynamic_cast<FillConcentricInternal *>(f.get());
            assert(fill_concentric != nullptr);
            fill_concentric->print_config        = &this->object()->print()->config();
            fill_concentric->print_object_config = &this->object()->config();
        } else if (surface_fill.params.pattern == ipConcentric) {
            FillConcentric *fill_concentric = dynamic_cast<FillConcentric *>(f.get());
            assert(fill_concentric != nullptr);
            fill_concentric->print_config = &this->object()->print()->config();
            fill_concentric->print_object_config = &this->object()->config();
        } else if (surface_fill.params.pattern == ipLightning)
            dynamic_cast<FillLightning::Filler*>(f.get())->generator = lightning_generator;
        // calculate flow spacing for infill pattern generation
        bool using_internal_flow = ! surface_fill.surface.is_solid() && ! surface_fill.params.bridge;
        double link_max_length = 0.;
        if (! surface_fill.params.bridge) {
#if 0
            link_max_length = layerm.region()->config().get_abs_value(surface.is_external() ? "external_fill_link_max_length" : "fill_link_max_length", flow.spacing());
//            printf("flow spacing: %f,  is_external: %d, link_max_length: %lf\n", flow.spacing(), int(surface.is_external()), link_max_length);
#else
            if (surface_fill.params.density > 80.) // 80%
                link_max_length = 3. * f->spacing;
#endif
        }
        LayerRegion* layerm = this->m_regions[surface_fill.region_id];
        // Maximum length of the perimeter segment linking two infill lines.
        f->link_max_length = (coord_t)scale_(link_max_length);
        // Used by the concentric infill pattern to clip the loops to create extrusion paths.
        f->loop_clipping = coord_t(scale_(layerm->region().config().seam_gap.get_abs_value(surface_fill.params.flow.nozzle_diameter())));
        // apply half spacing using this flow's own spacing and generate infill
        FillParams params;
        params.density         = float(0.01 * surface_fill.params.density);
    params.dont_adjust     = false; //  surface_fill.params.dont_adjust;
        params.anchor_length     = surface_fill.params.anchor_length;
    params.anchor_length_max = surface_fill.params.anchor_length_max;
    params.resolution        = resolution;
    params.use_arachne = surface_fill.params.pattern == ipConcentric;
    params.layer_height      = m_regions[surface_fill.region_id]->layer()->height;
    // BBS
    params.flow = surface_fill.params.flow;
    params.extrusion_role = surface_fill.params.extrusion_role;
    params.using_internal_flow = using_internal_flow;
    params.no_extrusion_overlap = surface_fill.params.overlap;
    params.with_loop = surface_fill.params.with_loop;
    params.config = &layerm->region().config();
    if (surface_fill.params.pattern == ipGrid)
      params.can_reverse = false;
    for (ExPolygon& expoly : surface_fill.expolygons) {
            f->no_overlap_expolygons = intersection_ex(surface_fill.no_overlap_expolygons, ExPolygons() = {expoly}, ApplySafetyOffset::Yes);
      // Spacing is modified by the filler to indicate adjustments. Reset it for each expolygon.
      f->spacing = surface_fill.params.spacing;
      surface_fill.surface.expolygon = std::move(expoly);
      if(surface_fill.params.bridge && surface_fill.surface.is_external() && surface_fill.params.density > 99.0){
        params.density = layerm->region().config().bridge_density.get_abs_value(1.0);
        params.dont_adjust = true;
      }
      // BBS: make fill
      f->fill_surface_extrusion(&surface_fill.surface,
        params,
        m_regions[surface_fill.region_id]->fills.entities);
    }
    }
    // add thin fill regions
    // Unpacks the collection, creates multiple collections per path.
    // The path type could be ExtrusionPath, ExtrusionLoop or ExtrusionEntityCollection.
    // Why the paths are unpacked?
  for (LayerRegion *layerm : m_regions)
      for (const ExtrusionEntity *thin_fill : layerm->thin_fills.entities) {
          ExtrusionEntityCollection &collection = *(new ExtrusionEntityCollection());
          layerm->fills.entities.push_back(&collection);
          collection.entities.push_back(thin_fill->clone());
      }
#ifndef NDEBUG
  for (LayerRegion *layerm : m_regions)
      for (size_t i = 0; i < layerm->fills.entities.size(); ++ i)
          assert(dynamic_cast<ExtrusionEntityCollection*>(layerm->fills.entities[i]) != nullptr);
#endif
}
References Slic3r::FillParams::anchor_length, Slic3r::FillParams::anchor_length_max, Slic3r::PrintObject::bounding_box(), Slic3r::FillParams::can_reverse, Slic3r::FillParams::config, Slic3r::PrintRegion::config(), Slic3r::PrintObject::config(), Slic3r::Print::config(), Slic3r::debug_out_path(), Slic3r::FillParams::density, Slic3r::FillParams::dont_adjust, Slic3r::ExtrusionEntityCollection::entities, Slic3r::FillParams::extrusion_role, Slic3r::f(), Slic3r::FillParams::flow, Slic3r::group_fills(), id(), Slic3r::intersection_ex(), Slic3r::ipConcentric, Slic3r::ipConcentricInternal, Slic3r::ipGrid, Slic3r::ipLightning, Slic3r::ipSupportCubic, Slic3r::FillParams::layer_height, m_regions, Slic3r::Fill::new_from_type(), Slic3r::FillParams::no_extrusion_overlap, object(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::print(), Slic3r::FillConcentric::print_config, Slic3r::FillConcentricInternal::print_config, Slic3r::FillConcentric::print_object_config, Slic3r::FillConcentricInternal::print_object_config, print_z, Slic3r::LayerRegion::region(), Slic3r::FillParams::resolution, scale_, Slic3r::FillParams::use_arachne, Slic3r::FillParams::using_internal_flow, Slic3r::FillParams::with_loop, and Slic3r::Yes.
make_ironing()
void Slic3r::Layer::make_ironing ()
{
  // LayerRegion::slices contains surfaces marked with SurfaceType.
  // Here we want to collect top surfaces extruded with the same extruder.
  // A surface will be ironed with the same extruder to not contaminate the print with another material leaking from the nozzle.
  // First classify regions based on the extruder used.
  struct IroningParams {
    InfillPattern pattern;
    int     extruder  = -1;
    bool    just_infill = false;
    // Spacing of the ironing lines, also to calculate the extrusion flow from.
    double    line_spacing;
    // Height of the extrusion, to calculate the extrusion flow from.
    double    height;
    double    speed;
    double    angle;
    bool operator<(const IroningParams &rhs) const {
      if (this->extruder < rhs.extruder)
        return true;
      if (this->extruder > rhs.extruder)
        return false;
      if (int(this->just_infill) < int(rhs.just_infill))
        return true;
      if (int(this->just_infill) > int(rhs.just_infill))
        return false;
      if (this->line_spacing < rhs.line_spacing)
        return true;
      if (this->line_spacing > rhs.line_spacing)
        return false;
      if (this->height < rhs.height)
        return true;
      if (this->height > rhs.height)
        return false;
      if (this->speed < rhs.speed)
        return true;
      if (this->speed > rhs.speed)
        return false;
      if (this->angle < rhs.angle)
        return true;
      if (this->angle > rhs.angle)
        return false;
      return false;
    }
    bool operator==(const IroningParams &rhs) const {
      return this->extruder == rhs.extruder && this->just_infill == rhs.just_infill &&
           this->line_spacing == rhs.line_spacing && this->height == rhs.height && this->speed == rhs.speed && this->angle == rhs.angle && this->pattern == rhs.pattern;
    }
    LayerRegion *layerm   = nullptr;
    // IdeaMaker: ironing
    // ironing flowrate (5% percent)
    // ironing speed (10 mm/sec)
    // Kisslicer:
    // iron off, Sweep, Group
    // ironing speed: 15 mm/sec
    // Cura:
    // Pattern (zig-zag / concentric)
    // line spacing (0.1mm)
    // flow: from normal layer height. 10%
    // speed: 20 mm/sec
  };
  std::vector<IroningParams> by_extruder;
    double default_layer_height = this->object()->config().layer_height;
  for (LayerRegion *layerm : m_regions)
    if (! layerm->slices.empty()) {
      IroningParams ironing_params;
      const PrintRegionConfig &config = layerm->region().config();
      if (config.ironing_type != IroningType::NoIroning &&
        (config.ironing_type == IroningType::AllSolid ||
          (config.top_shell_layers > 0 &&
            (config.ironing_type == IroningType::TopSurfaces ||
            (config.ironing_type == IroningType::TopmostOnly && layerm->layer()->upper_layer == nullptr))))) {
        if (config.wall_filament == config.solid_infill_filament || config.wall_loops == 0) {
          // Iron the whole face.
          ironing_params.extruder = config.solid_infill_filament;
        } else {
          // Iron just the infill.
          ironing_params.extruder = config.solid_infill_filament;
        }
      }
      if (ironing_params.extruder != -1) {
        //TODO just_infill is currently not used.
        ironing_params.just_infill  = false;
        ironing_params.line_spacing = config.ironing_spacing;
        ironing_params.height     = default_layer_height * 0.01 * config.ironing_flow;
        ironing_params.speed    = config.ironing_speed;
        ironing_params.angle    = config.infill_direction * M_PI / 180.;
        ironing_params.pattern      = config.ironing_pattern;
        ironing_params.layerm     = layerm;
        by_extruder.emplace_back(ironing_params);
      }
    }
  std::sort(by_extruder.begin(), by_extruder.end());
    FillParams      fill_params;
    fill_params.density    = 1.;
    fill_params.monotonic    = true;
    InfillPattern         f_pattern = ipRectilinear;
    std::unique_ptr<Fill> f         = std::unique_ptr<Fill>(Fill::new_from_type(f_pattern));
    f->set_bounding_box(this->object()->bounding_box());
    f->layer_id = this->id();
    f->z        = this->print_z;
    f->overlap  = 0;
  for (size_t i = 0; i < by_extruder.size();) {
    // Find span of regions equivalent to the ironing operation.
    IroningParams &ironing_params = by_extruder[i];
    // Create the filler object.
    if( f_pattern != ironing_params.pattern )
    {
            f_pattern               = ironing_params.pattern;
            f = std::unique_ptr<Fill>(Fill::new_from_type(f_pattern));
            f->set_bounding_box(this->object()->bounding_box());
            f->layer_id = this->id();
            f->z        = this->print_z;
            f->overlap  = 0;
    }
    size_t j = i;
    for (++ j; j < by_extruder.size() && ironing_params == by_extruder[j]; ++ j) ;
    // Create the ironing extrusions for regions <i, j)
    ExPolygons ironing_areas;
    double nozzle_dmr = this->object()->print()->config().nozzle_diameter.get_at(ironing_params.extruder - 1);
    if (ironing_params.just_infill) {
      //TODO just_infill is currently not used.
      // Just infill.
    } else {
      // Infill and perimeter.
      // Merge top surfaces with the same ironing parameters.
      Polygons polys;
      Polygons infills;
      for (size_t k = i; k < j; ++ k) {
        const IroningParams    &ironing_params  = by_extruder[k];
        const PrintRegionConfig  &region_config   = ironing_params.layerm->region().config();
        bool            iron_everything = region_config.ironing_type == IroningType::AllSolid;
        bool            iron_completely = iron_everything;
        if (iron_everything) {
          // Check whether there is any non-solid hole in the regions.
          bool internal_infill_solid = region_config.sparse_infill_density.value > 95.;
          for (const Surface &surface : ironing_params.layerm->fill_surfaces.surfaces)
            if ((! internal_infill_solid && surface.surface_type == stInternal) || surface.surface_type == stInternalBridge || surface.surface_type == stInternalVoid) {
              // Some fill region is not quite solid. Don't iron over the whole surface.
              iron_completely = false;
              break;
            }
        }
        if (iron_completely) {
          // Iron everything. This is likely only good for solid transparent objects.
          for (const Surface &surface : ironing_params.layerm->slices.surfaces)
            polygons_append(polys, surface.expolygon);
        } else {
          for (const Surface &surface : ironing_params.layerm->slices.surfaces)
            if (surface.surface_type == stTop || (iron_everything && surface.surface_type == stBottom))
              // stBottomBridge is not being ironed on purpose, as it would likely destroy the bridges.
              polygons_append(polys, surface.expolygon);
        }
        if (iron_everything && ! iron_completely) {
          // Add solid fill surfaces. This may not be ideal, as one will not iron perimeters touching these
          // solid fill surfaces, but it is likely better than nothing.
          for (const Surface &surface : ironing_params.layerm->fill_surfaces.surfaces)
            if (surface.surface_type == stInternalSolid)
              polygons_append(infills, surface.expolygon);
        }
      }
      if (! infills.empty() || j > i + 1) {
        // Ironing over more than a single region or over solid internal infill.
        if (! infills.empty())
          // For IroningType::AllSolid only:
          // Add solid infill areas for layers, that contain some non-ironable infil (sparse infill, bridge infill).
          append(polys, std::move(infills));
        polys = union_safety_offset(polys);
      }
      // Trim the top surfaces with half the nozzle diameter.
      ironing_areas = intersection_ex(polys, offset(this->lslices, - float(scale_(0.5 * nozzle_dmr))));
    }
        // Create the filler object.
        f->spacing = ironing_params.line_spacing;
        f->angle = float(ironing_params.angle + 0.25 * M_PI);
        f->link_max_length = (coord_t) scale_(3. * f->spacing);
    double  extrusion_height = ironing_params.height * f->spacing / nozzle_dmr;
    float  extrusion_width  = Flow::rounded_rectangle_extrusion_width_from_spacing(float(nozzle_dmr), float(extrusion_height));
    double flow_mm3_per_mm = nozzle_dmr * extrusion_height;
        Surface surface_fill(stTop, ExPolygon());
        for (ExPolygon &expoly : ironing_areas) {
      surface_fill.expolygon = std::move(expoly);
      Polylines polylines;
      try {
        polylines = f->fill_surface(&surface_fill, fill_params);
      } catch (InfillFailedException &) {
      }
          if (! polylines.empty()) {
            // Save into layer.
        ExtrusionEntityCollection *eec = nullptr;
            ironing_params.layerm->fills.entities.push_back(eec = new ExtrusionEntityCollection());
            // Don't sort the ironing infill lines as they are monotonicly ordered.
        eec->no_sort = true;
            extrusion_entities_append_paths(
                eec->entities, std::move(polylines),
                erIroning,
                flow_mm3_per_mm, extrusion_width, float(extrusion_height));
        }
    }
    // Regions up to j were processed.
    i = j;
  }
}
References Slic3r::AllSolid, Slic3r::angle(), Slic3r::append(), Slic3r::bounding_box(), Slic3r::PrintObject::config(), Slic3r::Print::config(), Slic3r::FillParams::density, Slic3r::ExtrusionEntityCollection::entities, Slic3r::erIroning, Slic3r::Surface::expolygon, Slic3r::extrusion_entities_append_paths(), Slic3r::f(), id(), Slic3r::intersection_ex(), Slic3r::ipRectilinear, lslices, M_PI, m_regions, Slic3r::FillParams::monotonic, Slic3r::Fill::new_from_type(), Slic3r::ExtrusionEntityCollection::no_sort, Slic3r::NoIroning, object(), Slic3r::offset(), operator<(), operator==(), Slic3r::polygons_append(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::print(), print_z, Slic3r::PrintRegionConfig, Slic3r::Flow::rounded_rectangle_extrusion_width_from_spacing(), scale_, Slic3r::stBottom, Slic3r::stInternal, Slic3r::stInternalBridge, Slic3r::stInternalSolid, Slic3r::stInternalVoid, Slic3r::stTop, Slic3r::TopmostOnly, Slic3r::TopSurfaces, and Slic3r::union_safety_offset().
make_perimeters()
void Slic3r::Layer::make_perimeters ()
{
    BOOST_LOG_TRIVIAL(trace) << "Generating perimeters for layer " << this->id();
    // keep track of regions whose perimeters we have already generated
    std::vector<unsigned char> done(m_regions.size(), false);
    for (LayerRegionPtrs::iterator layerm = m_regions.begin(); layerm != m_regions.end(); ++ layerm)
      if ((*layerm)->slices.empty()) {
      (*layerm)->perimeters.clear();
      (*layerm)->fills.clear();
      (*layerm)->thin_fills.clear();
      } else {
          size_t region_id = layerm - m_regions.begin();
          if (done[region_id])
              continue;
          BOOST_LOG_TRIVIAL(trace) << "Generating perimeters for layer " << this->id() << ", region " << region_id;
          done[region_id] = true;
          const PrintRegionConfig &config = (*layerm)->region().config();
          // find compatible regions
          LayerRegionPtrs layerms;
          layerms.push_back(*layerm);
          for (LayerRegionPtrs::const_iterator it = layerm + 1; it != m_regions.end(); ++it)
              if (! (*it)->slices.empty()) {
                LayerRegion* other_layerm = *it;
                const PrintRegionConfig &other_config = other_layerm->region().config();
                if (config.wall_filament             == other_config.wall_filament
                    && config.wall_loops                  == other_config.wall_loops
                    && config.inner_wall_speed             == other_config.inner_wall_speed
                    && config.outer_wall_speed    == other_config.outer_wall_speed
                    && config.small_perimeter_speed    == other_config.small_perimeter_speed
                        && config.gap_infill_speed.value == other_config.gap_infill_speed.value
                        && config.filter_out_gap_fill.value == other_config.filter_out_gap_fill.value
                    && config.detect_overhang_wall                   == other_config.detect_overhang_wall
                    && config.opt_serialize("inner_wall_line_width") == other_config.opt_serialize("inner_wall_line_width")
                    && config.opt_serialize("outer_wall_line_width") == other_config.opt_serialize("outer_wall_line_width")
                    && config.detect_thin_wall                  == other_config.detect_thin_wall
                    //&& config.wall_infill_order   == other_config.wall_infill_order
                    && config.infill_wall_overlap              == other_config.infill_wall_overlap
                        && config.fuzzy_skin                  == other_config.fuzzy_skin
                        && config.fuzzy_skin_thickness        == other_config.fuzzy_skin_thickness
                        && config.fuzzy_skin_point_distance       == other_config.fuzzy_skin_point_distance)
                {
            other_layerm->perimeters.clear();
            other_layerm->fills.clear();
            other_layerm->thin_fills.clear();
                    layerms.push_back(other_layerm);
                    done[it - m_regions.begin()] = true;
                }
            }
          if (layerms.size() == 1) {  // optimization
              (*layerm)->fill_surfaces.surfaces.clear();
              (*layerm)->make_perimeters((*layerm)->slices, &(*layerm)->fill_surfaces, &(*layerm)->fill_no_overlap_expolygons);
              (*layerm)->fill_expolygons = to_expolygons((*layerm)->fill_surfaces.surfaces);
          } else {
              SurfaceCollection new_slices;
              // Use the region with highest infill rate, as the make_perimeters() function below decides on the gap fill based on the infill existence.
              LayerRegion *layerm_config = layerms.front();
              {
                  // group slices (surfaces) according to number of extra perimeters
                  std::map<unsigned short, Surfaces> slices;  // extra_perimeters => [ surface, surface... ]
                  for (LayerRegion *layerm : layerms) {
                      for (const Surface &surface : layerm->slices.surfaces)
                          slices[surface.extra_perimeters].emplace_back(surface);
                      if (layerm->region().config().sparse_infill_density > layerm_config->region().config().sparse_infill_density)
                        layerm_config = layerm;
                  }
                  // merge the surfaces assigned to each group
                  for (std::pair<const unsigned short,Surfaces> &surfaces_with_extra_perimeters : slices)
                      new_slices.append(offset_ex(surfaces_with_extra_perimeters.second, ClipperSafetyOffset), surfaces_with_extra_perimeters.second.front());
              }
              // make perimeters
              SurfaceCollection fill_surfaces;
                //BBS
                ExPolygons fill_no_overlap;
              layerm_config->make_perimeters(new_slices, &fill_surfaces, &fill_no_overlap);
              // assign fill_surfaces to each layer
              if (!fill_surfaces.surfaces.empty()) {
                  for (LayerRegionPtrs::iterator l = layerms.begin(); l != layerms.end(); ++l) {
                      // Separate the fill surfaces.
                      ExPolygons expp = intersection_ex(fill_surfaces.surfaces, (*l)->slices.surfaces);
                      (*l)->fill_expolygons = expp;
                      (*l)->fill_surfaces.set(std::move(expp), fill_surfaces.surfaces.front());
                        //BBS: Separate fill_no_overlap
                        (*l)->fill_no_overlap_expolygons = intersection_ex((*l)->slices.surfaces, fill_no_overlap);
                  }
              }
          }
      }
    BOOST_LOG_TRIVIAL(trace) << "Generating perimeters for layer " << this->id() << " - Done";
}
References Slic3r::SurfaceCollection::append(), Slic3r::ExtrusionEntityCollection::clear(), Slic3r::ClipperSafetyOffset, Slic3r::PrintRegion::config(), Slic3r::LayerRegion::fills, id(), Slic3r::intersection_ex(), m_regions, Slic3r::LayerRegion::make_perimeters(), Slic3r::offset_ex(), Slic3r::LayerRegion::perimeters, Slic3r::PrintRegionConfig, Slic3r::LayerRegion::region(), Slic3r::SurfaceCollection::surfaces, Slic3r::LayerRegion::thin_fills, Slic3r::to_expolygons(), and Slic3r::trace().
make_slices()
void Slic3r::Layer::make_slices ()
{
    ExPolygons slices;
    if (m_regions.size() == 1) {
        // optimization: if we only have one region, take its slices
        slices = to_expolygons(m_regions.front()->slices.surfaces);
    } else {
        Polygons slices_p;
        for (LayerRegion *layerm : m_regions)
            polygons_append(slices_p, to_polygons(layerm->slices.surfaces));
        slices = union_safety_offset_ex(slices_p);
    }
    this->lslices.clear();
    this->lslices.reserve(slices.size());
    // prepare ordering points
    Points ordering_points;
    ordering_points.reserve(slices.size());
    for (const ExPolygon &ex : slices)
        ordering_points.push_back(ex.contour.first_point());
    // sort slices
    std::vector<Points::size_type> order = chain_points(ordering_points);
    // populate slices vector
    for (size_t i : order)
        this->lslices.emplace_back(std::move(slices[i]));
}
References Slic3r::chain_points(), lslices, m_regions, Slic3r::polygons_append(), Slic3r::to_expolygons(), Slic3r::to_polygons(), and Slic3r::union_safety_offset_ex().
merged()
ExPolygons Slic3r::Layer::merged (float offset) const
{
  assert(offset_scaled >= 0.f);
    // If no offset is set, apply EPSILON offset before union, and revert it afterwards.
  float offset_scaled2 = 0;
  if (offset_scaled == 0.f) {
    offset_scaled  = float(  EPSILON);
    offset_scaled2 = float(- EPSILON);
    }
    Polygons polygons;
  for (LayerRegion *layerm : m_regions) {
    const PrintRegionConfig &config = layerm->region().config();
    // Our users learned to bend Slic3r to produce empty volumes to act as subtracters. Only add the region if it is non-empty.
    if (config.bottom_shell_layers > 0 || config.top_shell_layers > 0 || config.sparse_infill_density > 0. || config.wall_loops > 0)
      append(polygons, offset(layerm->slices.surfaces, offset_scaled));
  }
    ExPolygons out = union_ex(polygons);
  if (offset_scaled2 != 0.f)
    out = offset_ex(out, offset_scaled2);
    return out;
}
References Slic3r::append(), EPSILON, m_regions, Slic3r::offset(), Slic3r::offset_ex(), out, Slic3r::PrintRegionConfig, and Slic3r::union_ex().
Referenced by Slic3r::PrintObject::apply_conical_overhang().
object() [1/2]
PrintObject * Slic3r::Layer::object () inline
{ return m_object; }
References m_object.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::PrintObject::bridge_over_infill(), Slic3r::LayerRegion::bridging_flow(), Slic3r::LayerRegion::flow(), Slic3r::get_boundary(), Slic3r::get_boundary_external(), Slic3r::get_perimeter_spacing(), Slic3r::get_perimeter_spacing_external(), Slic3r::group_fills(), make_fills(), make_ironing(), Slic3r::LayerRegion::make_perimeters(), Slic3r::GCode::LayerToPrint::object(), Slic3r::SeamPlacer::place_seam(), Slic3r::LayerRegion::prepare_fill_surfaces(), Slic3r::LayerRegion::process_external_surfaces(), Slic3r::GCode::process_layer(), Slic3r::PrintObject::remove_bridges_from_contacts(), Slic3r::SupportMaterialInternal::remove_bridges_from_contacts(), Slic3r::LayerRegion::simplify_loop(), Slic3r::LayerRegion::simplify_multi_path(), Slic3r::LayerRegion::simplify_path(), simplify_support_loop(), simplify_support_multi_path(), and simplify_support_path().
object() [2/2]
const PrintObject * Slic3r::Layer::object () const inline
{ return m_object; }
References m_object.
region_count()
size_t Slic3r::Layer::region_count () const inline
{ return m_regions.size(); }
References m_regions.
Referenced by Slic3r::apply_mm_segmentation(), and Slic3r::extract_layer().
regions()
const LayerRegionPtrs & Slic3r::Layer::regions () const inline
{ return m_regions; }
References m_regions.
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::collect_region_slices_by_type(), Slic3r::detect_contacts(), Slic3r::detect_overhangs(), Slic3r::PrintObject::discover_vertical_shells(), Slic3r::WipingExtrusions::ensure_perimeters_infills_order(), Slic3r::SeamPlacerImpl::extract_perimeter_polygons(), Slic3r::FillLightning::Generator::generateInitialInternalOverhangs(), Slic3r::FillLightning::Generator::generateTrees(), Slic3r::get_boundary(), Slic3r::get_perimeter_spacing(), Slic3r::get_print_object_bottom_layer_expolygons(), Slic3r::TreeSupport::get_trim_support_regions(), Slic3r::getadhesionCoeff(), Slic3r::getTemperatureFromExtruder(), Slic3r::group_fills(), Slic3r::SupportMaterialInternal::has_bridging_extrusions(), Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::new_contact_layer(), Slic3r::PrintObject::process_external_surfaces(), Slic3r::GCode::process_layer(), Slic3r::PrintObject::remove_bridges_from_contacts(), Slic3r::RetractWhenCrossingPerimeters::travel_inside_internal_regions(), and Slic3r::PrintObjectSupportMaterial::trim_support_layers_by_object().
restore_untyped_slices()
void Slic3r::Layer::restore_untyped_slices ()
{
    if (layer_needs_raw_backup(this)) {
        for (LayerRegion *layerm : m_regions)
            layerm->slices.set(layerm->raw_slices, stInternal);
    } else {
        assert(m_regions.size() == 1);
        m_regions.front()->slices.set(this->lslices, stInternal);
    }
}
References Slic3r::layer_needs_raw_backup(), lslices, m_regions, and Slic3r::stInternal.
restore_untyped_slices_no_extra_perimeters()
void Slic3r::Layer::restore_untyped_slices_no_extra_perimeters ()
{
    if (layer_needs_raw_backup(this)) {
        for (LayerRegion *layerm : m_regions)
            //BBS: remove extra_perimeters. Always false
          //if (! layerm->region().config().extra_perimeters.value)
              layerm->slices.set(layerm->raw_slices, stInternal);
    } else {
      assert(m_regions.size() == 1);
      LayerRegion *layerm = m_regions.front();
      // This optimization is correct, as extra_perimeters are only reused by prepare_infill() with multi-regions.
        //if (! layerm->region().config().extra_perimeters.value)
          layerm->slices.set(this->lslices, stInternal);
    }
}
References Slic3r::layer_needs_raw_backup(), lslices, m_regions, Slic3r::SurfaceCollection::set(), Slic3r::LayerRegion::slices, and Slic3r::stInternal.
set_id()
void Slic3r::Layer::set_id (size_t id) inline
{ m_id = id; }
References id(), and m_id.
simplify_infill_extrusion_path()
void Slic3r::Layer::simplify_infill_extrusion_path () inline
{ for (auto layerm : m_regions) layerm->simplify_infill_extrusion_entity(); }
References m_regions.
simplify_support_entity_collection()
void Slic3r::Layer::simplify_support_entity_collection (ExtrusionEntityCollection * entity_collection) protected
{
    for (size_t i = 0; i < entity_collection->entities.size(); i++) {
        if (ExtrusionEntityCollection* collection = dynamic_cast<ExtrusionEntityCollection*>(entity_collection->entities[i]))
            this->simplify_support_entity_collection(collection);
        else if (ExtrusionPath* path = dynamic_cast<ExtrusionPath*>(entity_collection->entities[i]))
            this->simplify_support_path(path);
        else if (ExtrusionMultiPath* multipath = dynamic_cast<ExtrusionMultiPath*>(entity_collection->entities[i]))
            this->simplify_support_multi_path(multipath);
        else if (ExtrusionLoop* loop = dynamic_cast<ExtrusionLoop*>(entity_collection->entities[i]))
            this->simplify_support_loop(loop);
        else
            throw Slic3r::InvalidArgument("Invalid extrusion entity supplied to simplify_support_entity_collection()");
    }
}
References Slic3r::ExtrusionEntityCollection::entities, simplify_support_entity_collection(), simplify_support_loop(), simplify_support_multi_path(), and simplify_support_path().
Referenced by simplify_support_entity_collection(), and Slic3r::SupportLayer::simplify_support_extrusion_path().
simplify_support_loop()
void Slic3r::Layer::simplify_support_loop (ExtrusionLoop * loop) protected
{
    const auto print_config = this->object()->print()->config();
    const bool spiral_mode = print_config.spiral_mode;
    const bool enable_arc_fitting = print_config.enable_arc_fitting;
    const auto scaled_resolution = scaled<double>(print_config.resolution.value);
    for (size_t i = 0; i < loop->paths.size(); ++i) {
        if (enable_arc_fitting &&
            !spiral_mode) {
            loop->paths[i].simplify_by_fitting_arc(SCALED_SUPPORT_RESOLUTION);
        } else {
            loop->paths[i].simplify(scaled_resolution);
        }
    }
}
References Slic3r::Print::config(), object(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::print(), and SCALED_SUPPORT_RESOLUTION.
Referenced by simplify_support_entity_collection().
simplify_support_multi_path()
void Slic3r::Layer::simplify_support_multi_path (ExtrusionMultiPath * multipath) protected
{
    const auto print_config = this->object()->print()->config();
    const bool spiral_mode = print_config.spiral_mode;
    const bool enable_arc_fitting = print_config.enable_arc_fitting;
    const auto scaled_resolution = scaled<double>(print_config.resolution.value);
    for (size_t i = 0; i < multipath->paths.size(); ++i) {
        if (enable_arc_fitting &&
            !spiral_mode) {
            multipath->paths[i].simplify_by_fitting_arc(SCALED_SUPPORT_RESOLUTION);
        } else {
            multipath->paths[i].simplify(scaled_resolution);
        }
    }
}
References Slic3r::Print::config(), object(), Slic3r::ExtrusionMultiPath::paths, Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::print(), and SCALED_SUPPORT_RESOLUTION.
Referenced by simplify_support_entity_collection().
simplify_support_path()
void Slic3r::Layer::simplify_support_path (ExtrusionPath * path) protected
{
    const auto print_config = this->object()->print()->config();
    const bool spiral_mode = print_config.spiral_mode;
    const bool enable_arc_fitting = print_config.enable_arc_fitting;
    const auto scaled_resolution = scaled<double>(print_config.resolution.value);
    if (enable_arc_fitting &&
        !spiral_mode) {
        path->simplify_by_fitting_arc(SCALED_SUPPORT_RESOLUTION);
    } else {
        path->simplify(scaled_resolution);
    }
}
References Slic3r::Print::config(), object(), Slic3r::PrintObjectBaseWithState< PrintType, PrintObjectStepEnum, COUNT >::print(), SCALED_SUPPORT_RESOLUTION, Slic3r::ExtrusionPath::simplify(), and Slic3r::ExtrusionPath::simplify_by_fitting_arc().
Referenced by simplify_support_entity_collection().
simplify_wall_extrusion_path()
void Slic3r::Layer::simplify_wall_extrusion_path () inline
{ for (auto layerm : m_regions) layerm->simplify_wall_extrusion_entity();}
References m_regions.
Friends And Related Symbol Documentation
fix_slicing_errors
std::string fix_slicing_errors (PrintObject * object, LayerPtrs & layers, const std::function< void()> & throw_if_canceled, int & firstLayerReplacedBy) friend
{
    std::string error_msg;//BBS
    if (layers.size() == 0) return error_msg;
    // Collect layers with slicing errors.
    // These layers will be fixed in parallel.
    std::vector<size_t> buggy_layers;
    buggy_layers.reserve(layers.size());
    // BBS: get largest external perimenter width of all layers
    auto get_ext_peri_width = [](Layer* layer) {return layer->m_regions.empty() ? 0 : layer->m_regions[0]->flow(frExternalPerimeter).scaled_width(); };
    auto it = std::max_element(layers.begin(), layers.end(), [get_ext_peri_width](auto& a, auto& b) {return get_ext_peri_width(a) < get_ext_peri_width(b); });
    coord_t thresh = get_ext_peri_width(*it) * 0.5;// half of external perimeter width  // 0.5 * scale_(this->config().line_width);
    for (size_t idx_layer = 0; idx_layer < layers.size(); ++idx_layer) {
        // BBS: detect empty layers (layers with very small regions) and mark them as problematic, then these layers will copy the nearest good layer
        auto layer = layers[idx_layer];
        ExPolygons lslices;
        for (size_t region_id = 0; region_id < layer->m_regions.size(); ++region_id) {
            LayerRegion* layerm = layer->m_regions[region_id];
            for (auto& surface : layerm->slices.surfaces) {
                auto expoly = offset_ex(surface.expolygon, -thresh);
                lslices.insert(lslices.begin(), expoly.begin(), expoly.end());
            }
        }
        if (lslices.empty()) {
            layer->slicing_errors = true;
        }
        if (layers[idx_layer]->slicing_errors) {
            buggy_layers.push_back(idx_layer);
        }
        else
            break; // only detect empty layers near bed
    }
    BOOST_LOG_TRIVIAL(debug) << "Slicing objects - fixing slicing errors in parallel - begin";
    std::atomic<bool> is_replaced = false;
    tbb::parallel_for(
        tbb::blocked_range<size_t>(0, buggy_layers.size()),
        [&layers, &throw_if_canceled, &buggy_layers, &is_replaced](const tbb::blocked_range<size_t>& range) {
            for (size_t buggy_layer_idx = range.begin(); buggy_layer_idx < range.end(); ++ buggy_layer_idx) {
                throw_if_canceled();
                size_t idx_layer = buggy_layers[buggy_layer_idx];
                // BBS: only replace empty layers lower than 1mm
                const coordf_t thresh_empty_layer_height = 1;
                Layer* layer = layers[idx_layer];
                if (layer->print_z>= thresh_empty_layer_height)
                    continue;
                assert(layer->slicing_errors);
                // Try to repair the layer surfaces by merging all contours and all holes from neighbor layers.
                // BOOST_LOG_TRIVIAL(trace) << "Attempting to repair layer" << idx_layer;
                for (size_t region_id = 0; region_id < layer->region_count(); ++ region_id) {
                    LayerRegion *layerm = layer->get_region(region_id);
                    // Find the first valid layer below / above the current layer.
                    const Surfaces *upper_surfaces = nullptr;
                    const Surfaces *lower_surfaces = nullptr;
                    //BBS: only repair empty layers lowers than 1mm
                    for (size_t j = idx_layer + 1; j < layers.size(); ++j) {
                        if (!layers[j]->slicing_errors) {
                            upper_surfaces = &layers[j]->regions()[region_id]->slices.surfaces;
                            break;
                        }
                        if (layers[j]->print_z >= thresh_empty_layer_height) break;
                    }
                    for (int j = int(idx_layer) - 1; j >= 0; --j) {
                        if (layers[j]->print_z >= thresh_empty_layer_height) continue;
                        if (!layers[j]->slicing_errors) {
                            lower_surfaces = &layers[j]->regions()[region_id]->slices.surfaces;
                            break;
                        }
                    }
                    // Collect outer contours and holes from the valid layers above & below.
                    ExPolygons expolys;
                    expolys.reserve(
                        ((upper_surfaces == nullptr) ? 0 : upper_surfaces->size()) +
                        ((lower_surfaces == nullptr) ? 0 : lower_surfaces->size()));
                    if (upper_surfaces)
                        for (const auto &surface : *upper_surfaces) {
                            expolys.emplace_back(surface.expolygon);
                        }
                    if (lower_surfaces)
                        for (const auto &surface : *lower_surfaces) {
                            expolys.emplace_back(surface.expolygon);
                        }
                    if (!expolys.empty()) {
                        //BBS
                        is_replaced = true;
                        layerm->slices.set(union_ex(expolys), stInternal);
                    }
                }
                // Update layer slices after repairing the single regions.
                layer->make_slices();
            }
        });
    throw_if_canceled();
    BOOST_LOG_TRIVIAL(debug) << "Slicing objects - fixing slicing errors in parallel - end";
    if(is_replaced)
        error_msg = L("Empty layers around bottom are replaced by nearest normal layers.");
    // remove empty layers from bottom
    while (! layers.empty() && (layers.front()->lslices.empty() || layers.front()->empty())) {
        delete layers.front();
        layers.erase(layers.begin());
        layers.front()->lower_layer = nullptr;
        for (size_t i = 0; i < layers.size(); ++ i)
            layers[i]->set_id(layers[i]->id() - 1);
    }
    //BBS
    if(error_msg.empty() && !buggy_layers.empty())
        error_msg = L("The model has too many empty layers.");
    // BBS: first layer slices are sorted by volume group, if the first layer is empty and replaced by the 2nd layer
// the later will be stored in "object->firstLayerObjGroupsMod()"
    if (!buggy_layers.empty() && buggy_layers.front() == 0 && layers.size() > 1)
        firstLayerReplacedBy = 1;
    return error_msg;
}
new_layers
std::vector< Layer * > new_layers (PrintObject * print_object, const std::vector< coordf_t > & object_layers) friend
{
    LayerPtrs out;
    out.reserve(object_layers.size());
    auto     id   = int(print_object->slicing_parameters().raft_layers());
    coordf_t zmin = print_object->slicing_parameters().object_print_z_min;
    Layer   *prev = nullptr;
    for (size_t i_layer = 0; i_layer < object_layers.size(); i_layer += 2) {
        coordf_t lo = object_layers[i_layer];
        coordf_t hi = object_layers[i_layer + 1];
        coordf_t slice_z = 0.5 * (lo + hi);
        Layer *layer = new Layer(id ++, print_object, hi - lo, hi + zmin, slice_z);
        out.emplace_back(layer);
        if (prev != nullptr) {
            prev->upper_layer = layer;
            layer->lower_layer = prev;
        }
        prev = layer;
    }
    return out;
}
PrintObject
friend class PrintObject friend
Member Data Documentation
cantilevers
ExPolygons Slic3r::Layer::cantilevers mutable
Referenced by Slic3r::detect_overhangs(), and Slic3r::PrintObjectSupportMaterial::top_contact_layers().
height
coordf_t Slic3r::Layer::height
Referenced by bottom_z(), Slic3r::PrintObject::bridge_over_infill(), Slic3r::GCode::collect_layers_to_print(), Slic3r::PrintObject::combine_infill(), Slic3r::detect_overhangs(), Slic3r::LayerRegion::flow(), Slic3r::TreeSupport::generate_toolpaths(), Slic3r::getExtrusionPathsFromSupportLayer(), Slic3r::group_fills(), Slic3r::mmu_segmentation_top_and_bottom_layers(), Slic3r::new_contact_layer(), and Slic3r::PrintObjectSupportMaterial::top_contact_layers().
loverhangs
ExPolygons Slic3r::Layer::loverhangs
Referenced by Slic3r::PrintObject::copy_layers_overhang_from_shared_object(), and Slic3r::PrintObject::detect_overhangs_for_lift().
loverhangs_bbox
BoundingBox Slic3r::Layer::loverhangs_bbox
Referenced by Slic3r::PrintObject::copy_layers_overhang_from_shared_object(), and Slic3r::PrintObject::detect_overhangs_for_lift().
lower_layer
Layer* Slic3r::Layer::lower_layer
Referenced by ~Layer(), Slic3r::TreeSupport::create_tree_support_layers(), Slic3r::detect_contacts(), Slic3r::detect_overhangs(), Slic3r::PrintObject::detect_overhangs_for_lift(), Slic3r::LayerRegion::make_perimeters(), Slic3r::new_contact_layer(), Slic3r::LayerRegion::process_external_surfaces(), and Slic3r::PrintObjectSupportMaterial::top_contact_layers().
lslices
ExPolygons Slic3r::Layer::lslices
Referenced by Slic3r::TreeSupportData::TreeSupportData(), Slic3r::PrintObjectSupportMaterial::buildplate_covered(), Slic3r::calculate_layer_edge_grid(), Slic3r::GUI::check_color_change(), Slic3r::PrintObject::clip_fill_surfaces(), Slic3r::collect_slices_outer(), Slic3r::detect_contacts(), Slic3r::detect_overhangs(), Slic3r::PrintObject::detect_overhangs_for_lift(), Slic3r::PrintObject::detect_surfaces_type(), Slic3r::PrintObject::discover_vertical_shells(), Slic3r::extract_layer(), Slic3r::TreeSupport::generate_toolpaths(), Slic3r::get_boundary(), Slic3r::TreeSupport::get_trim_support_regions(), Slic3r::AvoidCrossingPerimeters::init_layer(), make_ironing(), Slic3r::LayerRegion::make_perimeters(), make_slices(), Slic3r::need_wipe(), Slic3r::ExtrusionQualityEstimator::prepare_for_new_layer(), Slic3r::LayerRegion::process_external_surfaces(), Slic3r::GCode::process_layer(), Slic3r::project_support_to_grid(), Slic3r::PrintObject::remove_bridges_from_contacts(), Slic3r::SupportMaterialInternal::remove_bridges_from_contacts(), restore_untyped_slices(), restore_untyped_slices_no_extra_perimeters(), Slic3r::PrintObjectSupportMaterial::top_contact_layers(), Slic3r::AvoidCrossingPerimeters::travel_to(), and Slic3r::PrintObjectSupportMaterial::trim_support_layers_by_object().
lslices_bboxes
std::vector<BoundingBox> Slic3r::Layer::lslices_bboxes
Referenced by Slic3r::extract_layer(), Slic3r::need_wipe(), Slic3r::GCode::process_layer(), Slic3r::PrintObject::remove_bridges_from_contacts(), Slic3r::SupportMaterialInternal::remove_bridges_from_contacts(), and Slic3r::AvoidCrossingPerimeters::travel_to().
m_id
size_t Slic3r::Layer::m_id private
Referenced by id(), and set_id().
m_object
PrintObject* Slic3r::Layer::m_object private
Referenced by object(), and object().
m_regions
LayerRegionPtrs Slic3r::Layer::m_regions private
Referenced by ~Layer(), add_region(), any_bottom_region_slice_contains(), any_internal_region_slice_contains(), Slic3r::PrintObject::apply_conical_overhang(), backup_untyped_slices(), Slic3r::PrintObject::bridge_over_infill(), Slic3r::PrintObject::clip_fill_surfaces(), Slic3r::PrintObject::detect_surfaces_type(), Slic3r::PrintObject::discover_vertical_shells(), empty(), export_region_fill_surfaces_to_svg(), export_region_slices_to_svg(), get_region(), get_region(), get_sparse_infill_max_void_area(), has_extrusions(), make_fills(), make_ironing(), make_perimeters(), make_slices(), merged(), region_count(), regions(), restore_untyped_slices(), restore_untyped_slices_no_extra_perimeters(), simplify_infill_extrusion_path(), and simplify_wall_extrusion_path().
print_z
coordf_t Slic3r::Layer::print_z
Referenced by Slic3r::GCode::_do_export(), Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::PrintObjectSupportMaterial::bottom_contact_layers_and_layer_support_areas(), Slic3r::PrintObject::bridge_over_infill(), Slic3r::GCode::collect_layers_to_print(), Slic3r::convert_layer_region_from_json(), Slic3r::detect_bottom_contacts(), Slic3r::PrintObject::detect_surfaces_type(), Slic3r::PrintObject::discover_vertical_shells(), Slic3r::TreeSupport::drop_nodes(), Slic3r::extract_support_layer(), Slic3r::get_boundary(), Slic3r::get_boundary_external(), Slic3r::get_perimeter_spacing_external(), Slic3r::TreeSupport::get_trim_support_regions(), make_fills(), make_ironing(), Slic3r::LayerRegion::make_perimeters(), Slic3r::new_contact_layer(), Slic3r::GCode::LayerToPrint::print_z(), Slic3r::LayerRegion::process_external_surfaces(), Slic3r::GCode::process_layer(), Slic3r::project_support_to_grid(), Slic3r::to_json(), Slic3r::PrintObjectSupportMaterial::top_contact_layers(), and Slic3r::PrintObjectSupportMaterial::trim_support_layers_by_object().
sharp_tails
ExPolygons Slic3r::Layer::sharp_tails mutable
Referenced by Slic3r::PrintObject::clear_support_layers(), Slic3r::detect_contacts(), Slic3r::detect_overhangs(), Slic3r::TreeSupport::get_trim_support_regions(), Slic3r::PrintObjectSupportMaterial::top_contact_layers(), and Slic3r::PrintObjectSupportMaterial::trim_support_layers_by_object().
sharp_tails_height
std::map<const ExPolygon*, float> Slic3r::Layer::sharp_tails_height mutable
Referenced by Slic3r::detect_overhangs(), and Slic3r::PrintObjectSupportMaterial::top_contact_layers().
slice_z
coordf_t Slic3r::Layer::slice_z
Referenced by Slic3r::apply_mm_segmentation(), Slic3r::SeamPlacer::find_seam_string(), and Slic3r::SeamPlacer::place_seam().
slicing_errors
bool Slic3r::Layer::slicing_errors
upper_layer
Layer* Slic3r::Layer::upper_layer
Referenced by ~Layer(), Slic3r::PrintObject::apply_conical_overhang(), Slic3r::TreeSupport::create_tree_support_layers(), Slic3r::LayerRegion::make_perimeters(), and Slic3r::PrintObject::slice_volumes().
The documentation for this class was generated from the following files:
src/libslic3r/Layer.hpp
src/libslic3r/Fill/Fill.cpp
src/libslic3r/Layer.cpp