OrcaSlicer: Slic3r::GUI::AMSextruder Class Reference
Slic3r::GUI::AMSextruder Class Reference
#include <src/slic3r/GUI/Widgets/AMSControl.hpp>
Public Member Functions
void TurnOn (wxColour col)
void TurnOff ()
void create (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size)
void OnVamsLoading (bool load, wxColour col=AMS_CONTROL_GRAY500)
void OnAmsLoading (bool load, wxColour col=AMS_CONTROL_GRAY500)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
void msw_rescale ()
void has_ams (bool hams)
void no_ams_mode (bool mode)
AMSextruder (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~AMSextruder ()
Public Attributes
bool m_none_ams_mode {false}
bool m_has_vams {false}
bool m_vams_loading {false}
bool m_ams_loading {false}
wxColour m_current_colur
wxBoxSizer * m_bitmap_sizer {nullptr}
wxPanel * m_bitmap_panel {nullptr}
AMSextruderImage * m_amsSextruder {nullptr}
ScalableBitmap monitor_ams_extruder
Detailed Description
Constructor & Destructor Documentation
AMSextruder()
Slic3r::GUI::AMSextruder::AMSextruder (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{ create(parent, id, pos, size); }
References create(), and size.
~AMSextruder()
Slic3r::GUI::AMSextruder::~AMSextruder ()
{}
Member Function Documentation
create()
void Slic3r::GUI::AMSextruder::create (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size)
{
    wxWindow::Create(parent, id, pos, AMS_EXTRUDER_SIZE, wxBORDER_NONE);
    SetBackgroundColour(AMS_CONTROL_WHITE_COLOUR);
    wxBoxSizer *m_sizer_body = new wxBoxSizer(wxVERTICAL);
    m_bitmap_panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, AMS_EXTRUDER_BITMAP_SIZE, wxTAB_TRAVERSAL);
    m_bitmap_panel->SetBackgroundColour(AMS_EXTRUDER_DEF_COLOUR);
    m_bitmap_panel->SetDoubleBuffered(true);
    m_bitmap_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_amsSextruder = new AMSextruderImage(m_bitmap_panel, wxID_ANY, wxDefaultPosition, AMS_EXTRUDER_BITMAP_SIZE);
    m_bitmap_sizer->Add(m_amsSextruder, 0, wxALIGN_CENTER, 0);
    m_bitmap_panel->SetSizer(m_bitmap_sizer);
    m_bitmap_panel->Layout();
    m_sizer_body->Add( 0, 0, 1, wxEXPAND, 0 );
    m_sizer_body->Add(m_bitmap_panel, 0, wxALIGN_CENTER, 0);
    SetSizer(m_sizer_body);
    Bind(wxEVT_PAINT, &AMSextruder::paintEvent, this);
    Layout();
}
References AMS_CONTROL_WHITE_COLOUR, AMS_EXTRUDER_BITMAP_SIZE, AMS_EXTRUDER_DEF_COLOUR, AMS_EXTRUDER_SIZE, m_amsSextruder, m_bitmap_panel, m_bitmap_sizer, and paintEvent().
Referenced by AMSextruder().
doRender()
void Slic3r::GUI::AMSextruder::doRender (wxDC & dc)
{
    //m_current_colur =
    wxSize size = GetSize();
    dc.SetPen(wxPen(AMS_CONTROL_GRAY500, 2, wxSOLID));
    dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
    if (!m_none_ams_mode) {
        dc.DrawLine(size.x / 2, -1, size.x / 2, size.y * 0.6 - 1);
    }
    if (m_has_vams) {
        dc.DrawRoundedRectangle(-size.x / 2, size.y * 0.1, size.x, size.y, 4);
        if (m_vams_loading) {
            dc.SetPen(wxPen(m_current_colur, 6, wxSOLID));
            dc.DrawRoundedRectangle(-size.x / 2, size.y * 0.1, size.x, size.y, 4);
            if (m_current_colur == *wxWHITE && !wxGetApp().dark_mode()) {
                dc.SetPen(wxPen(AMS_CONTROL_DEF_BLOCK_BK_COLOUR, 1, wxSOLID));
                dc.DrawRoundedRectangle(-size.x / 2 - FromDIP(3), size.y * 0.1 + FromDIP(3), size.x, size.y, 3);
                dc.DrawRoundedRectangle(-size.x / 2 + FromDIP(3), size.y * 0.1 - FromDIP(3), size.x, size.y, 5);
            }
        }
        if (m_ams_loading && !m_none_ams_mode) {
            dc.SetPen(wxPen(m_current_colur, 6, wxSOLID));
            dc.DrawLine(size.x / 2, -1, size.x / 2, size.y * 0.6 - 1);
            if (m_current_colur == *wxWHITE && !wxGetApp().dark_mode()) {
                dc.SetPen(wxPen(AMS_CONTROL_DEF_BLOCK_BK_COLOUR, 1, wxSOLID));
                dc.DrawLine(size.x / 2 - FromDIP(4), -1, size.x / 2 - FromDIP(3), size.y * 0.6 - 1);
                dc.DrawLine(size.x / 2 + FromDIP(3), -1, size.x / 2 + FromDIP(3), size.y * 0.6 - 1);
            }
        }
    }
    else {
        if (m_ams_loading) {
            dc.SetPen(wxPen(m_current_colur, 6, wxSOLID));
            dc.DrawLine(size.x / 2, -1, size.x / 2, size.y * 0.6 - 1);
            if (m_current_colur == *wxWHITE && !wxGetApp().dark_mode()) {
                dc.SetPen(wxPen(AMS_CONTROL_DEF_BLOCK_BK_COLOUR, 1, wxSOLID));
                dc.DrawLine(size.x / 2 - FromDIP(4), -1, size.x / 2 - FromDIP(3), size.y * 0.6 - 1);
                dc.DrawLine(size.x / 2 + FromDIP(3), -1, size.x / 2 + FromDIP(3), size.y * 0.6 - 1);
            }
        }
    }
}
References AMS_CONTROL_DEF_BLOCK_BK_COLOUR, AMS_CONTROL_GRAY500, m_ams_loading, m_current_colur, m_has_vams, m_none_ams_mode, m_vams_loading, and size.
Referenced by render().
has_ams()
void Slic3r::GUI::AMSextruder::has_ams (bool hams) inline
{m_has_vams = hams; Refresh();};
References m_has_vams.
Referenced by Slic3r::GUI::AMSControl::show_vams().
msw_rescale()
void Slic3r::GUI::AMSextruder::msw_rescale ()
{
    m_amsSextruder->msw_rescale();
    Layout();
    Update();
    Refresh();
}
References m_amsSextruder, and Slic3r::GUI::AMSextruderImage::msw_rescale().
Referenced by Slic3r::GUI::AMSControl::msw_rescale().
no_ams_mode()
void Slic3r::GUI::AMSextruder::no_ams_mode (bool mode) inline
{m_none_ams_mode = mode; Refresh();};
References m_none_ams_mode.
Referenced by Slic3r::GUI::AMSControl::EnterNoneAMSMode(), and Slic3r::GUI::AMSControl::ExitNoneAMSMode().
OnAmsLoading()
void Slic3r::GUI::AMSextruder::OnAmsLoading (bool load, wxColour col = AMS_CONTROL_GRAY500)
{
    m_ams_loading = load;
    if (load)m_current_colur = col;
    Refresh();
}
References col(), m_ams_loading, and m_current_colur.
Referenced by Slic3r::GUI::AMSControl::SetAmsStep(), Slic3r::GUI::AMSControl::SetExtruder(), and Slic3r::GUI::AMSControl::SwitchAms().
OnVamsLoading()
void Slic3r::GUI::AMSextruder::OnVamsLoading (bool load, wxColour col = AMS_CONTROL_GRAY500)
{
    m_vams_loading = load;
    if (load)m_current_colur = col;
    Refresh();
}
References col(), m_current_colur, and m_vams_loading.
Referenced by Slic3r::GUI::AMSControl::SetAmsStep(), and Slic3r::GUI::AMSControl::SetExtruder().
paintEvent()
void Slic3r::GUI::AMSextruder::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by create().
render()
void Slic3r::GUI::AMSextruder::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
TurnOff()
void Slic3r::GUI::AMSextruder::TurnOff ()
{
    m_amsSextruder->TurnOff();
}
References m_amsSextruder, and Slic3r::GUI::AMSextruderImage::TurnOff().
Referenced by Slic3r::GUI::AMSControl::SetExtruder(), and Slic3r::GUI::AMSControl::SwitchAms().
TurnOn()
void Slic3r::GUI::AMSextruder::TurnOn (wxColour col)
{
    m_amsSextruder->TurnOn(col);
}
References col(), m_amsSextruder, and Slic3r::GUI::AMSextruderImage::TurnOn().
Referenced by Slic3r::GUI::AMSControl::SetExtruder(), and Slic3r::GUI::AMSControl::SwitchAms().
Member Data Documentation
m_ams_loading
bool Slic3r::GUI::AMSextruder::m_ams_loading {false}
Referenced by doRender(), and OnAmsLoading().
m_amsSextruder
AMSextruderImage* Slic3r::GUI::AMSextruder::m_amsSextruder {nullptr}
Referenced by create(), msw_rescale(), TurnOff(), and TurnOn().
m_bitmap_panel
wxPanel* Slic3r::GUI::AMSextruder::m_bitmap_panel {nullptr}
Referenced by create().
m_bitmap_sizer
wxBoxSizer* Slic3r::GUI::AMSextruder::m_bitmap_sizer {nullptr}
Referenced by create().
m_current_colur
wxColour Slic3r::GUI::AMSextruder::m_current_colur
Referenced by doRender(), OnAmsLoading(), and OnVamsLoading().
m_has_vams
bool Slic3r::GUI::AMSextruder::m_has_vams {false}
Referenced by doRender(), and has_ams().
m_none_ams_mode
bool Slic3r::GUI::AMSextruder::m_none_ams_mode {false}
Referenced by doRender(), and no_ams_mode().
m_vams_loading
bool Slic3r::GUI::AMSextruder::m_vams_loading {false}
Referenced by doRender(), and OnVamsLoading().
monitor_ams_extruder
ScalableBitmap Slic3r::GUI::AMSextruder::monitor_ams_extruder
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AMSControl.hpp
src/slic3r/GUI/Widgets/AMSControl.cpp