OrcaSlicer: Slic3r::GUI::ZUserLogin Class Reference
Slic3r::GUI::ZUserLogin Class Reference
#include <src/slic3r/GUI/WebUserLoginDialog.hpp>
Public Member Functions
ZUserLogin ()
virtual ~ZUserLogin ()
void load_url (wxString &url)
std::string w2s (wxString sSrc)
void UpdateState ()
void OnIdle (wxIdleEvent &evt)
void OnNavigationRequest (wxWebViewEvent &evt)
void OnNavigationComplete (wxWebViewEvent &evt)
void OnDocumentLoaded (wxWebViewEvent &evt)
void OnNewWindow (wxWebViewEvent &evt)
void OnError (wxWebViewEvent &evt)
void OnTitleChanged (wxWebViewEvent &evt)
void OnFullScreenChanged (wxWebViewEvent &evt)
void OnScriptMessage (wxWebViewEvent &evt)
void OnScriptResponseMessage (wxCommandEvent &evt)
void RunScript (const wxString &javascript)
bool ShowErrorPage ()
bool run ()
Public Attributes
bool m_networkOk
Static Public Attributes
static int web_sequence_id = 20000
Private Member Functions
void OnTimer (wxTimerEvent &event)
Private Attributes
wxTimer * m_timer { nullptr }
wxString TargetUrl
wxWebView * m_browser
std::string m_AutotestToken
wxString m_javascript
wxString m_response_js
wxString m_bbl_user_agent
Detailed Description
Constructor & Destructor Documentation
ZUserLogin()
Slic3r::GUI::ZUserLogin::ZUserLogin ()
                       : wxDialog((wxWindow *) (wxGetApp().mainframe), wxID_ANY, "OrcaSlicer")
{
    SetBackgroundColour(*wxWHITE);
    // Url
    AppConfig * config   = wxGetApp().app_config;
    NetworkAgent* agent = wxGetApp().getAgent();
    if (!agent) return;
    std::string host_url = agent->get_bambulab_host();
    TargetUrl = host_url + "/sign-in";
    m_networkOk = false;
    std::string strlang = config->get("language");
    if (strlang != "") {
        replace_str(strlang, "_", "-");
        TargetUrl = host_url + "/" + strlang + "/sign-in";
    }
    BOOST_LOG_TRIVIAL(info) << "login url = " << TargetUrl.ToStdString();
    m_bbl_user_agent = wxString::Format("BBL-Slicer/v%s", SLIC3R_VERSION);
    // set the frame icon
    // Create the webview
    m_browser = WebView::CreateWebView(this, TargetUrl);
    if (m_browser == nullptr) {
        wxLogError("Could not init m_browser");
        return;
    }
    m_browser->Hide();
    m_browser->SetSize(0, 0);
    // Log backend information
    // wxLogMessage(wxWebView::GetBackendVersionInfo().ToString());
    // wxLogMessage("Backend: %s Version: %s",
    // m_browser->GetClassInfo()->GetClassName(),wxWebView::GetBackendVersionInfo().ToString());
    // wxLogMessage("User Agent: %s", m_browser->GetUserAgent());
    // Connect the webview events
    Bind(wxEVT_WEBVIEW_NAVIGATING, &ZUserLogin::OnNavigationRequest, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_NAVIGATED, &ZUserLogin::OnNavigationComplete, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_LOADED, &ZUserLogin::OnDocumentLoaded, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_ERROR, &ZUserLogin::OnError, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_NEWWINDOW, &ZUserLogin::OnNewWindow, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_TITLE_CHANGED, &ZUserLogin::OnTitleChanged, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_FULLSCREEN_CHANGED, &ZUserLogin::OnFullScreenChanged, this, m_browser->GetId());
    Bind(wxEVT_WEBVIEW_SCRIPT_MESSAGE_RECEIVED, &ZUserLogin::OnScriptMessage, this, m_browser->GetId());
    // Connect the idle events
    // Bind(wxEVT_IDLE, &ZUserLogin::OnIdle, this);
    // Bind(wxEVT_CLOSE_WINDOW, &ZUserLogin::OnClose, this);
    // UI
    SetTitle( _L("Login"));
    // Set a more sensible size for web browsing
    wxSize pSize = FromDIP(wxSize(650, 840));
    SetSize(pSize);
    int screenheight = wxSystemSettings::GetMetric(wxSYS_SCREEN_Y, NULL);
    int screenwidth  = wxSystemSettings::GetMetric(wxSYS_SCREEN_X, NULL);
    int MaxY         = (screenheight - pSize.y) > 0 ? (screenheight - pSize.y) / 2 : 0;
    wxPoint tmpPT((screenwidth - pSize.x) / 2, MaxY);
    Move(tmpPT);
    //Param
    m_AutotestToken = "";
    wxGetApp().UpdateDlgDarkUI(this);
}
References _L, WebView::CreateWebView(), Slic3r::AppConfig::get(), Slic3r::NetworkAgent::get_bambulab_host(), m_AutotestToken, m_bbl_user_agent, m_browser, m_networkOk, NULL, OnDocumentLoaded(), OnError(), OnFullScreenChanged(), OnNavigationComplete(), OnNavigationRequest(), OnNewWindow(), OnScriptMessage(), OnTitleChanged(), Slic3r::GUI::replace_str(), and TargetUrl.
~ZUserLogin()
Slic3r::GUI::ZUserLogin::~ZUserLogin () virtual
{
    if (m_timer != NULL) {
        m_timer->Stop();
        delete m_timer;
        m_timer = NULL;
    }
}
References m_timer, and NULL.
Member Function Documentation
load_url()
void Slic3r::GUI::ZUserLogin::load_url (wxString & url)
{
    m_browser->LoadURL(url);
    m_browser->SetFocus();
    UpdateState();
}
References m_browser, and UpdateState().
Referenced by ShowErrorPage().
OnDocumentLoaded()
void Slic3r::GUI::ZUserLogin::OnDocumentLoaded (wxWebViewEvent & evt)
Callback invoked when a page is finished loading
{
    // Only notify if the document is the main frame, not a subframe
    wxString tmpUrl = evt.GetURL();
    NetworkAgent* agent = wxGetApp().getAgent();
    std::string strHost = agent->get_bambulab_host();
    if ( tmpUrl.Contains(strHost) ) {
        m_networkOk = true;
        // wxLogMessage("%s", "Document loaded; url='" + evt.GetURL() + "'");
    }
    UpdateState();
}
References Slic3r::NetworkAgent::get_bambulab_host(), m_networkOk, and UpdateState().
Referenced by ZUserLogin().
OnError()
void Slic3r::GUI::ZUserLogin::OnError (wxWebViewEvent & evt)
Callback invoked when a loading error occurs
{
#define WX_ERROR_CASE(type) \
    case type: category = #type; break;
    wxString category;
    switch (evt.GetInt()) {
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_CONNECTION);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_CERTIFICATE);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_AUTH);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_SECURITY);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_NOT_FOUND);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_REQUEST);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_USER_CANCELLED);
        WX_ERROR_CASE(wxWEBVIEW_NAV_ERR_OTHER);
    }
    if( evt.GetInt()==wxWEBVIEW_NAV_ERR_CONNECTION )
    {
        if(m_timer!=NULL)
            m_timer->Stop();
        if (m_networkOk==false)
            ShowErrorPage();
    }
    // wxLogMessage("%s", "Error; url='" + evt.GetURL() + "', error='" +
    // category + " (" + evt.GetString() + ")'");
    // Show the info bar with an error
    // m_info->ShowMessage(_L("An error occurred loading ") + evt.GetURL() +
    // "\n" + "'" + category + "'", wxICON_ERROR);
    UpdateState();
}
References m_networkOk, m_timer, NULL, ShowErrorPage(), UpdateState(), and WX_ERROR_CASE.
Referenced by ZUserLogin().
OnFullScreenChanged()
void Slic3r::GUI::ZUserLogin::OnFullScreenChanged (wxWebViewEvent & evt)
{
    // wxLogMessage("Full screen changed; status = %d", evt.GetInt());
    ShowFullScreen(evt.GetInt() != 0);
}
Referenced by ZUserLogin().
OnIdle()
void Slic3r::GUI::ZUserLogin::OnIdle (wxIdleEvent & evt)
{
    if (m_browser->IsBusy()) {
        wxSetCursor(wxCURSOR_ARROWWAIT);
    } else {
        wxSetCursor(wxNullCursor);
    }
}
References m_browser.
OnNavigationComplete()
void Slic3r::GUI::ZUserLogin::OnNavigationComplete (wxWebViewEvent & evt)
Callback invoked when a navigation request was accepted
{
    // wxLogMessage("%s", "Navigation complete; url='" + evt.GetURL() + "'");
    m_browser->Show();
    Layout();
    UpdateState();
}
References m_browser, and UpdateState().
Referenced by ZUserLogin().
OnNavigationRequest()
void Slic3r::GUI::ZUserLogin::OnNavigationRequest (wxWebViewEvent & evt)
Callback invoked when there is a request to load a new page (for instance when the user clicks a link)
{
    //wxLogMessage("%s", "Navigation request to '" + evt.GetURL() + "'(target='" + evt.GetTarget() + "')");
    UpdateState();
}
References UpdateState().
Referenced by ZUserLogin().
OnNewWindow()
void Slic3r::GUI::ZUserLogin::OnNewWindow (wxWebViewEvent & evt)
On new window, we veto to stop extra windows appearing
{
    wxString flag = " (other)";
    if (evt.GetNavigationAction() == wxWEBVIEW_NAV_ACTION_USER) { flag = " (user)"; }
    // wxLogMessage("%s", "New window; url='" + evt.GetURL() + "'" + flag);
    // If we handle new window events then just load them in this window as we
    // are a single window browser
    m_browser->LoadURL(evt.GetURL());
    UpdateState();
}
References m_browser, and UpdateState().
Referenced by ZUserLogin().
OnScriptMessage()
void Slic3r::GUI::ZUserLogin::OnScriptMessage (wxWebViewEvent & evt)
{
    wxString str_input = evt.GetString();
    try {
        json j = json::parse(str_input);
        wxString strCmd = j["command"];
        if (strCmd == "autotest_token")
        {
            m_AutotestToken = j["data"]["token"];
        }
        if (strCmd == "user_login") {
            j["data"]["autotest_token"] = m_AutotestToken;
            wxGetApp().handle_script_message(j.dump());
            Close();
        }
        else if (strCmd == "get_localhost_url") {
            BOOST_LOG_TRIVIAL(info) << "thirdparty_login: get_localhost_url";
            wxGetApp().start_http_server();
            std::string sequence_id = j["sequence_id"].get<std::string>();
            CallAfter([this, sequence_id] {
                json ack_j;
                ack_j["command"] = "get_localhost_url";
                ack_j["response"]["base_url"] = std::string(LOCALHOST_URL) + std::to_string(LOCALHOST_PORT);
                ack_j["response"]["result"] = "success";
                ack_j["sequence_id"] = sequence_id;
                wxString str_js = wxString::Format("window.postMessage(%s)", ack_j.dump());
                this->RunScript(str_js);
            });
        }
        else if (strCmd == "thirdparty_login") {
            BOOST_LOG_TRIVIAL(info) << "thirdparty_login: thirdparty_login";
            if (j["data"].contains("url")) {
                std::string jump_url = j["data"]["url"].get<std::string>();
                CallAfter([this, jump_url] {
                    wxString url = wxString::FromUTF8(jump_url);
                    wxLaunchDefaultBrowser(url);
                    });
            }
        }
        else if (strCmd == "new_webpage") {
            if (j["data"].contains("url")) {
                std::string jump_url = j["data"]["url"].get<std::string>();
                CallAfter([this, jump_url] {
                    wxString url = wxString::FromUTF8(jump_url);
                    wxLaunchDefaultBrowser(url);
                    });
            }
            return;
        }
    } catch (std::exception &e) {
        wxMessageBox(e.what(), "parse json failed", wxICON_WARNING);
        Close();
    }
}
References Slic3r::contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::get(), LOCALHOST_PORT, LOCALHOST_URL, m_AutotestToken, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::parse(), and RunScript().
Referenced by ZUserLogin().
OnScriptResponseMessage()
void Slic3r::GUI::ZUserLogin::OnScriptResponseMessage (wxCommandEvent & evt)
{
    // if (!m_response_js.empty())
    //{
    //    RunScript(m_response_js);
    //}
    // RunScript("This is a message to Web!");
    // RunScript("postMessage(\"AABBCCDD\");");
}
OnTimer()
void Slic3r::GUI::ZUserLogin::OnTimer (wxTimerEvent & event) private
{
    m_timer->Stop();
    if (m_networkOk == false)
    {
        ShowErrorPage();
    }
}
References m_networkOk, m_timer, and ShowErrorPage().
OnTitleChanged()
void Slic3r::GUI::ZUserLogin::OnTitleChanged (wxWebViewEvent & evt)
{
    // SetTitle(evt.GetString());
    // wxLogMessage("%s", "Title changed; title='" + evt.GetString() + "'");
}
Referenced by ZUserLogin().
run()
bool Slic3r::GUI::ZUserLogin::run ()
                     {
    m_timer = new wxTimer(this, NETWORK_OFFLINE_TIMER_ID);
    m_timer->Start(8000);
    if (this->ShowModal() == wxID_OK) {
        return true;
    } else {
        return false;
    }
}
References m_timer, and NETWORK_OFFLINE_TIMER_ID.
Referenced by Slic3r::GUI::login().
RunScript()
void Slic3r::GUI::ZUserLogin::RunScript (const wxString & javascript)
{
    // Remember the script we run in any case, so the next time the user opens
    // the "Run Script" dialog box, it is shown there for convenient updating.
    m_javascript = javascript;
    if (!m_browser) return;
    WebView::RunScript(m_browser, javascript);
}
References m_browser, m_javascript, and WebView::RunScript().
Referenced by OnScriptMessage().
ShowErrorPage()
bool Slic3r::GUI::ZUserLogin::ShowErrorPage ()
{
    wxString ErrortUrl = from_u8((boost::filesystem::path(resources_dir()) / "web\\login\\error.html").make_preferred().string());
    load_url(ErrortUrl);
    return true;
}
References Slic3r::GUI::from_u8(), load_url(), and Slic3r::resources_dir().
Referenced by OnError(), and OnTimer().
UpdateState()
void Slic3r::GUI::ZUserLogin::UpdateState ()
Method that retrieves the current state from the web control and updates the GUI the reflect this current state.
{
    // SetTitle(m_browser->GetCurrentTitle());
}
Referenced by load_url(), OnDocumentLoaded(), OnError(), OnNavigationComplete(), OnNavigationRequest(), and OnNewWindow().
w2s()
std::string Slic3r::GUI::ZUserLogin::w2s (wxString sSrc)
Member Data Documentation
m_AutotestToken
std::string Slic3r::GUI::ZUserLogin::m_AutotestToken private
Referenced by ZUserLogin(), and OnScriptMessage().
m_bbl_user_agent
wxString Slic3r::GUI::ZUserLogin::m_bbl_user_agent private
Referenced by ZUserLogin().
m_browser
wxWebView* Slic3r::GUI::ZUserLogin::m_browser private
Referenced by ZUserLogin(), load_url(), OnIdle(), OnNavigationComplete(), OnNewWindow(), and RunScript().
m_javascript
wxString Slic3r::GUI::ZUserLogin::m_javascript private
Referenced by RunScript().
m_networkOk
bool Slic3r::GUI::ZUserLogin::m_networkOk
Referenced by ZUserLogin(), OnDocumentLoaded(), OnError(), and OnTimer().
m_response_js
wxString Slic3r::GUI::ZUserLogin::m_response_js private
m_timer
wxTimer* Slic3r::GUI::ZUserLogin::m_timer { nullptr } private
Referenced by ~ZUserLogin(), OnError(), OnTimer(), and run().
TargetUrl
wxString Slic3r::GUI::ZUserLogin::TargetUrl private
Referenced by ZUserLogin().
web_sequence_id
int Slic3r::GUI::ZUserLogin::web_sequence_id = 20000 static
The documentation for this class was generated from the following files:
src/slic3r/GUI/WebUserLoginDialog.hpp
src/slic3r/GUI/WebUserLoginDialog.cpp