OrcaSlicer: ErrorMsgStaticText Class Reference
ErrorMsgStaticText Class Reference
#include <src/slic3r/GUI/Widgets/ErrorMsgStaticText.hpp>
Public Member Functions
ErrorMsgStaticText ()
ErrorMsgStaticText (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(0, 0))
void paintEvent (wxPaintEvent &evt)
void SetLabel (wxString msg)
Public Attributes
wxString m_msg
Detailed Description
Constructor & Destructor Documentation
ErrorMsgStaticText() [1/2]
ErrorMsgStaticText::ErrorMsgStaticText ()
{}
ErrorMsgStaticText() [2/2]
ErrorMsgStaticText::ErrorMsgStaticText (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(0,0))
{
    Create(parent, id, pos, size);
    Bind(wxEVT_PAINT, &ErrorMsgStaticText::paintEvent, this);
}
References paintEvent(), and size.
Member Function Documentation
paintEvent()
void ErrorMsgStaticText::paintEvent (wxPaintEvent & evt)
{
    auto size = GetSize();
    wxPaintDC dc(this);
    auto text_height = dc.GetCharHeight();
    wxString  out_txt = m_msg;
    wxString  count_txt  = "";
    int line_count  = 1;
    int new_line_pos = 0;
    bool is_ch = false;
    if (m_msg[0] > 0x80 && m_msg[1] > 0x80)is_ch = true;
    for (int i = 0; i < m_msg.length(); i++) {
        auto text_size = dc.GetTextExtent(count_txt);
        if (text_size.x < (size.x)) {
            count_txt += m_msg[i];
            if (m_msg[i] == ' ' ||
                m_msg[i] == ',' ||
                m_msg[i] == '.' ||
                m_msg[i] == '\n')
            {
                new_line_pos = i;
            }
        } else {
            if (!is_ch)
            {
                out_txt[new_line_pos] = '\n';
                i = new_line_pos;
            } else {
                out_txt.insert(i-1,'\n');
            }
            count_txt = "";
            line_count++;
        }
    }
    SetSize(wxSize(-1, line_count * text_height));
    SetMinSize(wxSize(-1, line_count * text_height));
    SetMaxSize(wxSize(-1, line_count * text_height));
    dc.DrawText(out_txt, 0, 0);
}
References m_msg, and size.
Referenced by ErrorMsgStaticText().
SetLabel()
void ErrorMsgStaticText::SetLabel (wxString msg) inline
{m_msg = msg;};
Referenced by Slic3r::GUI::StatusPanel::error_info_reset(), and Slic3r::GUI::StatusPanel::show_error_message().
Member Data Documentation
m_msg
wxString ErrorMsgStaticText::m_msg
Referenced by paintEvent().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/ErrorMsgStaticText.hpp
src/slic3r/GUI/Widgets/ErrorMsgStaticText.cpp