OrcaSlicer: Slic3r::GUI::AMSextruderImage Class Reference
Slic3r::GUI::AMSextruderImage Class Reference
#include <src/slic3r/GUI/Widgets/AMSControl.hpp>
Public Member Functions
void TurnOn (wxColour col)
void TurnOff ()
void msw_rescale ()
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
AMSextruderImage (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~AMSextruderImage ()
Public Attributes
bool m_turn_on = {false}
wxColour m_colour
ScalableBitmap m_ams_extruder
Detailed Description
Constructor & Destructor Documentation
AMSextruderImage()
Slic3r::GUI::AMSextruderImage::AMSextruderImage (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{
    wxWindow::Create(parent, id, pos, AMS_EXTRUDER_BITMAP_SIZE);
    SetBackgroundColour(*wxWHITE);
    m_ams_extruder = ScalableBitmap(this, "monitor_ams_extruder",55);
    SetSize(AMS_EXTRUDER_BITMAP_SIZE);
    SetMinSize(AMS_EXTRUDER_BITMAP_SIZE);
    SetMaxSize(AMS_EXTRUDER_BITMAP_SIZE);
    Bind(wxEVT_PAINT, &AMSextruderImage::paintEvent, this);
}
References AMS_EXTRUDER_BITMAP_SIZE, m_ams_extruder, and paintEvent().
~AMSextruderImage()
Slic3r::GUI::AMSextruderImage::~AMSextruderImage ()
{}
Member Function Documentation
doRender()
void Slic3r::GUI::AMSextruderImage::doRender (wxDC & dc)
{
    auto size = GetSize();
    dc.SetPen(*wxTRANSPARENT_PEN);
    dc.SetBrush(m_colour);
    dc.DrawRectangle(0, FromDIP(18), size.x, size.y - FromDIP(18) - FromDIP(5));
    dc.DrawBitmap(m_ams_extruder.bmp(), wxPoint((size.x - m_ams_extruder.GetBmpSize().x) / 2, (size.y - m_ams_extruder.GetBmpSize().y) / 2));
}
References ScalableBitmap::bmp(), ScalableBitmap::GetBmpSize(), m_ams_extruder, m_colour, and size.
Referenced by render().
msw_rescale()
void Slic3r::GUI::AMSextruderImage::msw_rescale ()
{
    //m_ams_extruder.SetSize(AMS_EXTRUDER_BITMAP_SIZE);
    //auto image     = m_ams_extruder.ConvertToImage();
    m_ams_extruder = ScalableBitmap(this, "monitor_ams_extruder", 55);
    Refresh();
}
References m_ams_extruder.
Referenced by Slic3r::GUI::AMSextruder::msw_rescale().
paintEvent()
void Slic3r::GUI::AMSextruderImage::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by AMSextruderImage().
render()
void Slic3r::GUI::AMSextruderImage::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
TurnOff()
void Slic3r::GUI::AMSextruderImage::TurnOff ()
{
    m_colour = AMS_EXTRUDER_DEF_COLOUR;
    Refresh();
}
References AMS_EXTRUDER_DEF_COLOUR, and m_colour.
Referenced by Slic3r::GUI::AMSextruder::TurnOff().
TurnOn()
void Slic3r::GUI::AMSextruderImage::TurnOn (wxColour col)
{
    m_colour  = col;
    Refresh();
}
References col(), and m_colour.
Referenced by Slic3r::GUI::AMSextruder::TurnOn().
Member Data Documentation
m_ams_extruder
ScalableBitmap Slic3r::GUI::AMSextruderImage::m_ams_extruder
Referenced by AMSextruderImage(), doRender(), and msw_rescale().
m_colour
wxColour Slic3r::GUI::AMSextruderImage::m_colour
Referenced by doRender(), TurnOff(), and TurnOn().
m_turn_on
bool Slic3r::GUI::AMSextruderImage::m_turn_on = {false}
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AMSControl.hpp
src/slic3r/GUI/Widgets/AMSControl.cpp