OrcaSlicer: src/qhull/src/libqhullcpp/QhullPoint.cpp File Reference
QhullPoint.cpp File Reference
#include "libqhullcpp/QhullPoint.h"
#include "libqhullcpp/QhullError.h"
#include "libqhullcpp/Qhull.h"
#include <iostream>
#include <algorithm>
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global functions
ostream & operator<< (ostream &os, const QhullPoint::PrintPoint &pr)
Same as qh_printpointid [io.c].
ostream & operator<< (ostream &os, const QhullPoint &p)
Function Documentation
operator<<() [1/2]
ostream & operator<< (ostream & os, const QhullPoint & p)
{
    os << p.print("");
    return os;
}//operator<<
References orgQhull::QhullPoint::print().
operator<<() [2/2]
ostream & operator<< (ostream & os, const QhullPoint::PrintPoint & pr)
Same as qh_printpointid [io.c].
{
    QhullPoint p= *pr.point;
    countT i= p.id();
    if(pr.point_message){
        if(*pr.point_message){
            os << pr.point_message << " ";
        }
        if(pr.with_identifier && (i!=qh_IDunknown) && (i!=qh_IDnone)){
            os << "p" << i << ": ";
        }
    }
    const realT *c= p.coordinates();
    for(int k=p.dimension(); k--; ){
        realT r= *c++;
        if(pr.point_message){
            os << " " << r; // FIXUP QH11010 %8.4g
        }else{
            os << " " << r; // FIXUP QH11010 qh_REAL_1
        }
    }
    os << std::endl;
    return os;
}//printPoint
References orgQhull::QhullPoint::coordinates(), orgQhull::QhullPoint::dimension(), orgQhull::QhullPoint::id(), qh_IDnone, qh_IDunknown, and realT.