OrcaSlicer: Slic3r::GUI::AMSMaterialsSetting Class Reference
Slic3r::GUI::AMSMaterialsSetting Class Reference
#include <src/slic3r/GUI/AMSMaterialsSetting.hpp>
Public Member Functions
AMSMaterialsSetting (wxWindow *parent, wxWindowID id)
~AMSMaterialsSetting ()
void create ()
void paintEvent (wxPaintEvent &evt)
void input_min_finish ()
void input_max_finish ()
void update ()
void enable_confirm_button (bool en)
bool Show (bool show) override
void Popup (wxString filament=wxEmptyString, wxString sn=wxEmptyString, wxString temp_min=wxEmptyString, wxString temp_max=wxEmptyString, wxString k=wxEmptyString, wxString n=wxEmptyString)
void post_select_event ()
void msw_rescale ()
void set_color (wxColour color)
void set_colors (std::vector< wxColour > colors)
void on_picker_color (wxCommandEvent &color)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Public Attributes
MachineObject * obj { nullptr }
int ams_id { 0 }
int tray_id { 0 }
std::string ams_filament_id
std::string ams_setting_id
bool m_is_third
wxString m_brand_filament
wxString m_brand_sn
wxString m_brand_tmp
wxColour m_brand_colour
std::string m_filament_type
ColorPickerPopup m_color_picker_popup
Protected Member Functions
void create_panel_normal (wxWindow *parent)
void create_panel_kn (wxWindow *parent)
void on_dpi_changed (const wxRect &suggested_rect) override
void on_select_filament (wxCommandEvent &evt)
void on_select_ok (wxCommandEvent &event)
void on_select_reset (wxCommandEvent &event)
void on_select_close (wxCommandEvent &event)
void on_clr_picker (wxMouseEvent &event)
bool is_virtual_tray ()
void update_widgets ()
virtual void on_sys_color_changed ()
Protected Attributes
StateColor m_btn_bg_green
StateColor m_btn_bg_gray
wxPanel * m_panel_normal
wxPanel * m_panel_SN
wxStaticText * m_sn_number
wxStaticText * warning_text
wxStaticText * m_title_filament
wxStaticText * m_title_colour
wxStaticText * m_title_temperature
TextInput * m_input_nozzle_min
TextInput * m_input_nozzle_max
Button * m_button_reset
Button * m_button_confirm
wxStaticText * m_tip_readonly
Button * m_button_close
ColorPicker * m_clr_picker
wxColourData * m_clrData
wxPanel * m_panel_kn
wxStaticText * m_ratio_text
wxStaticText * m_k_param
TextInput * m_input_k_val
wxStaticText * m_n_param
TextInput * m_input_n_val
int m_filament_selection
ComboBox * m_comboBox_filament
TextInput * m_readonly_filament
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
AMSMaterialsSetting()
Slic3r::GUI::AMSMaterialsSetting::AMSMaterialsSetting (wxWindow * parent, wxWindowID id)
    : DPIDialog(parent, id, _L("AMS Materials Setting"), wxDefaultPosition, wxDefaultSize, wxBORDER_NONE)
    , m_color_picker_popup(ColorPickerPopup(this))
{
    create();
    wxGetApp().UpdateDlgDarkUI(this);
}
References create().
~AMSMaterialsSetting()
Slic3r::GUI::AMSMaterialsSetting::~AMSMaterialsSetting ()
{
    m_comboBox_filament->Disconnect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(AMSMaterialsSetting::on_select_filament), NULL, this);
}
References m_comboBox_filament, NULL, and on_select_filament().
Member Function Documentation
create()
void Slic3r::GUI::AMSMaterialsSetting::create ()
{
    SetBackgroundColour(*wxWHITE);
    wxBoxSizer *m_sizer_main = new wxBoxSizer(wxVERTICAL);
    m_panel_normal = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    create_panel_normal(m_panel_normal);
    m_panel_kn = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    create_panel_kn(m_panel_kn);
    wxBoxSizer *m_sizer_button = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_button->Add(0, 0, 1, wxEXPAND, 0);
    m_button_confirm = new Button(this, _L("Confirm"));
    m_btn_bg_green   = StateColor(std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed), std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
                            std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    m_button_confirm->SetBackgroundColor(m_btn_bg_green);
    m_button_confirm->SetBorderColor(wxColour(0, 150, 136));
    m_button_confirm->SetTextColor(wxColour("#FFFFFE"));
    m_button_confirm->SetMinSize(AMS_MATERIALS_SETTING_BUTTON_SIZE);
    m_button_confirm->SetCornerRadius(FromDIP(12));
    m_button_confirm->Bind(wxEVT_BUTTON, &AMSMaterialsSetting::on_select_ok, this);
    m_button_reset = new Button(this, _L("Reset"));
    m_btn_bg_gray = StateColor(std::pair<wxColour, int>(wxColour(206, 206, 206), StateColor::Pressed), std::pair<wxColour, int>(*wxWHITE, StateColor::Focused),
        std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Hovered),
        std::pair<wxColour, int>(*wxWHITE, StateColor::Normal));
    m_button_reset->SetBackgroundColor(m_btn_bg_gray);
    m_button_reset->SetBorderColor(AMS_MATERIALS_SETTING_GREY900);
    m_button_reset->SetTextColor(AMS_MATERIALS_SETTING_GREY900);
    m_button_reset->SetMinSize(AMS_MATERIALS_SETTING_BUTTON_SIZE);
    m_button_reset->SetCornerRadius(FromDIP(12));
    m_button_reset->Bind(wxEVT_BUTTON, &AMSMaterialsSetting::on_select_reset, this);
    m_button_close = new Button(this, _L("Close"));
    m_button_close->SetBackgroundColor(m_btn_bg_gray);
    m_button_close->SetBorderColor(AMS_MATERIALS_SETTING_GREY900);
    m_button_close->SetTextColor(AMS_MATERIALS_SETTING_GREY900);
    m_button_close->SetMinSize(AMS_MATERIALS_SETTING_BUTTON_SIZE);
    m_button_close->SetCornerRadius(FromDIP(12));
    m_button_close->Bind(wxEVT_BUTTON, &AMSMaterialsSetting::on_select_close, this);
    m_sizer_button->Add(m_button_confirm, 0, wxALIGN_CENTER | wxRIGHT, FromDIP(20));
    m_sizer_button->Add(m_button_reset, 0, wxALIGN_CENTER | wxRIGHT, FromDIP(20));
    m_sizer_button->Add(m_button_close, 0, wxALIGN_CENTER, 0);
    m_sizer_main->Add(m_panel_normal, 0, wxALL, FromDIP(2));
    m_sizer_main->Add(m_panel_kn, 0, wxALL, FromDIP(2));
    m_sizer_main->Add(0, 0, 0, wxTOP, FromDIP(24));
    m_sizer_main->Add(m_sizer_button, 0,  wxEXPAND | wxLEFT | wxRIGHT, FromDIP(20));
    m_sizer_main->Add(0, 0, 0,  wxTOP, FromDIP(16));
    SetSizer(m_sizer_main);
    Layout();
    Fit();
    m_input_nozzle_min->GetTextCtrl()->Bind(wxEVT_SET_FOCUS, [this](wxFocusEvent& e) {
        warning_text->Hide();
        Layout();
        Fit();
        e.Skip();
        });
    m_input_nozzle_min->GetTextCtrl()->Bind(wxEVT_TEXT_ENTER, [this](wxCommandEvent& e) {
        input_min_finish();
        e.Skip();
        });
    m_input_nozzle_min->GetTextCtrl()->Bind(wxEVT_KILL_FOCUS, [this](wxFocusEvent& e) {
        input_min_finish();
        e.Skip();
        });
    m_input_nozzle_max->GetTextCtrl()->Bind(wxEVT_SET_FOCUS, [this](wxFocusEvent& e) {
        warning_text->Hide();
        Layout();
        Fit();
        e.Skip();
        });
    m_input_nozzle_max->GetTextCtrl()->Bind(wxEVT_TEXT_ENTER, [this](wxCommandEvent& e) {
        input_max_finish();
        e.Skip();
        });
    m_input_nozzle_max->GetTextCtrl()->Bind(wxEVT_KILL_FOCUS, [this](wxFocusEvent& e) {
        input_max_finish();
        e.Skip();
        });
    Bind(wxEVT_PAINT, &AMSMaterialsSetting::paintEvent, this);
    Bind(EVT_SELECTED_COLOR, &AMSMaterialsSetting::on_picker_color, this);
     m_comboBox_filament->Connect(wxEVT_COMMAND_COMBOBOX_SELECTED, wxCommandEventHandler(AMSMaterialsSetting::on_select_filament), NULL, this);
}
References _L, AMS_MATERIALS_SETTING_BUTTON_SIZE, AMS_MATERIALS_SETTING_GREY900, create_panel_kn(), create_panel_normal(), StateColor::Focused, TextInput::GetTextCtrl(), StateColor::Hovered, input_max_finish(), input_min_finish(), m_btn_bg_gray, m_btn_bg_green, m_button_close, m_button_confirm, m_button_reset, m_comboBox_filament, m_input_nozzle_max, m_input_nozzle_min, m_panel_kn, m_panel_normal, StateColor::Normal, NULL, on_picker_color(), on_select_close(), on_select_filament(), on_select_ok(), on_select_reset(), paintEvent(), StateColor::Pressed, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetMinSize(), Button::SetTextColor(), warning_text, and wxEVT_BUTTON.
Referenced by AMSMaterialsSetting().
create_panel_kn()
void Slic3r::GUI::AMSMaterialsSetting::create_panel_kn (wxWindow * parent) protected
{
    auto sizer = new wxBoxSizer(wxVERTICAL);
    // title
    m_ratio_text = new wxStaticText(parent, wxID_ANY, _L("Factors of dynamic flow cali"));
    m_ratio_text->SetForegroundColour(wxColour(50, 58, 61));
    m_ratio_text->SetFont(Label::Head_14);
    auto kn_val_sizer = new wxFlexGridSizer(0, 2, 0, 0);
    kn_val_sizer->SetFlexibleDirection(wxBOTH);
    kn_val_sizer->SetNonFlexibleGrowMode(wxFLEX_GROWMODE_SPECIFIED);
    kn_val_sizer->AddGrowableCol(1);
    // k params input
    m_k_param = new wxStaticText(parent, wxID_ANY, _L("Factor K"), wxDefaultPosition, wxDefaultSize, 0);
    m_k_param->SetFont(::Label::Body_13);
    m_k_param->SetForegroundColour(wxColour(50, 58, 61));
    m_k_param->Wrap(-1);
    kn_val_sizer->Add(m_k_param, 0, wxALL | wxALIGN_CENTER_VERTICAL, FromDIP(5));
    m_input_k_val = new TextInput(parent, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_CENTRE | wxTE_PROCESS_ENTER);
    m_input_k_val->GetTextCtrl()->SetValidator(wxTextValidator(wxFILTER_NUMERIC));
    kn_val_sizer->Add(m_input_k_val, 0, wxALL | wxEXPAND | wxALIGN_CENTER_VERTICAL, FromDIP(5));
    // n params input
    wxBoxSizer* n_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_n_param = new wxStaticText(parent, wxID_ANY, _L("Factor N"), wxDefaultPosition, wxDefaultSize, 0);
    m_n_param->SetFont(::Label::Body_13);
    m_n_param->SetForegroundColour(wxColour(50, 58, 61));
    m_n_param->Wrap(-1);
    kn_val_sizer->Add(m_n_param, 1, wxALL | wxALIGN_CENTER_VERTICAL, FromDIP(5));
    m_input_n_val = new TextInput(parent, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxTE_CENTRE | wxTE_PROCESS_ENTER);
    m_input_n_val->GetTextCtrl()->SetValidator(wxTextValidator(wxFILTER_NUMERIC));
    kn_val_sizer->Add(m_input_n_val, 0, wxALL | wxEXPAND | wxALIGN_CENTER_VERTICAL, FromDIP(5));
    // hide n
    m_n_param->Hide();
    m_input_n_val->Hide();
    sizer->Add(0, 0, 0, wxTOP, FromDIP(10));
    sizer->Add(m_ratio_text, 0, wxLEFT | wxRIGHT | wxEXPAND, FromDIP(20));
    sizer->Add(0, 0, 0, wxTOP, FromDIP(10));
    sizer->Add(kn_val_sizer, 0, wxLEFT | wxRIGHT | wxEXPAND, FromDIP(20));
    sizer->Add(0, 0, 0, wxTOP, FromDIP(10));
    parent->SetSizer(sizer);
}
References _L, Label::Body_13, TextInput::GetTextCtrl(), Label::Head_14, m_input_k_val, m_input_n_val, m_k_param, m_n_param, m_ratio_text, and wxStaticText.
Referenced by create().
create_panel_normal()
void Slic3r::GUI::AMSMaterialsSetting::create_panel_normal (wxWindow * parent) protected
{
    auto sizer = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* m_sizer_filament = new wxBoxSizer(wxHORIZONTAL);
    m_title_filament = new wxStaticText(parent, wxID_ANY, _L("Filament"), wxDefaultPosition, wxSize(AMS_MATERIALS_SETTING_LABEL_WIDTH, -1), 0);
    m_title_filament->SetFont(::Label::Body_13);
    m_title_filament->SetForegroundColour(AMS_MATERIALS_SETTING_GREY800);
    m_title_filament->Wrap(-1);
    m_sizer_filament->Add(m_title_filament, 0, wxALIGN_CENTER, 0);
    m_sizer_filament->Add(0, 0, 0, wxEXPAND, 0);
#ifdef __APPLE__
    m_comboBox_filament = new wxComboBox(parent, wxID_ANY, wxEmptyString, wxDefaultPosition, AMS_MATERIALS_SETTING_COMBOX_WIDTH, 0, nullptr, wxCB_READONLY);
#else
    m_comboBox_filament = new ::ComboBox(parent, wxID_ANY, wxEmptyString, wxDefaultPosition, AMS_MATERIALS_SETTING_COMBOX_WIDTH, 0, nullptr, wxCB_READONLY);
#endif
    m_sizer_filament->Add(m_comboBox_filament, 1, wxALIGN_CENTER, 0);
    m_readonly_filament = new TextInput(parent, wxEmptyString, "", "", wxDefaultPosition, AMS_MATERIALS_SETTING_COMBOX_WIDTH, wxTE_READONLY | wxRIGHT);
    m_readonly_filament->SetBorderColor(StateColor(std::make_pair(0xDBDBDB, (int)StateColor::Focused), std::make_pair(0x009688, (int)StateColor::Hovered),
        std::make_pair(0xDBDBDB, (int)StateColor::Normal)));
    m_readonly_filament->SetFont(::Label::Body_14);
    m_readonly_filament->SetLabelColor(AMS_MATERIALS_SETTING_GREY800);
    m_readonly_filament->GetTextCtrl()->Bind(wxEVT_SET_FOCUS, [](auto& e) {});
    m_readonly_filament->GetTextCtrl()->Hide();
    m_sizer_filament->Add(m_readonly_filament, 1, wxALIGN_CENTER, 0);
    m_readonly_filament->Hide();
    wxBoxSizer* m_sizer_colour = new wxBoxSizer(wxHORIZONTAL);
    m_title_colour = new wxStaticText(parent, wxID_ANY, _L("Colour"), wxDefaultPosition, wxSize(AMS_MATERIALS_SETTING_LABEL_WIDTH, -1), 0);
    m_title_colour->SetFont(::Label::Body_13);
    m_title_colour->SetForegroundColour(AMS_MATERIALS_SETTING_GREY800);
    m_title_colour->Wrap(-1);
    m_sizer_colour->Add(m_title_colour, 0, wxALIGN_CENTER, 0);
    m_sizer_colour->Add(0, 0, 0, wxEXPAND, 0);
    m_clr_picker = new ColorPicker(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    m_clr_picker->set_show_full(true);
    m_clr_picker->SetBackgroundColour(*wxWHITE);
    m_clr_picker->Bind(wxEVT_LEFT_DOWN, &AMSMaterialsSetting::on_clr_picker, this);
    m_sizer_colour->Add(m_clr_picker, 0, 0, 0);
    wxBoxSizer* m_sizer_temperature = new wxBoxSizer(wxHORIZONTAL);
    m_title_temperature = new wxStaticText(parent, wxID_ANY, _L("Nozzle\nTemperature"), wxDefaultPosition, wxSize(AMS_MATERIALS_SETTING_LABEL_WIDTH, -1), 0);
    m_title_temperature->SetFont(::Label::Body_13);
    m_title_temperature->SetForegroundColour(AMS_MATERIALS_SETTING_GREY800);
    m_title_temperature->Wrap(-1);
    m_sizer_temperature->Add(m_title_temperature, 0, wxALIGN_CENTER, 0);
    m_sizer_temperature->Add(0, 0, 0, wxEXPAND, 0);
    wxBoxSizer* sizer_other = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_tempinput = new wxBoxSizer(wxHORIZONTAL);
    m_input_nozzle_max = new ::TextInput(parent, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, AMS_MATERIALS_SETTING_INPUT_SIZE, wxTE_CENTRE | wxTE_PROCESS_ENTER);
    m_input_nozzle_min = new ::TextInput(parent, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, AMS_MATERIALS_SETTING_INPUT_SIZE, wxTE_CENTRE | wxTE_PROCESS_ENTER);
    m_input_nozzle_max->Enable(false);
    m_input_nozzle_min->Enable(false);
    m_input_nozzle_max->GetTextCtrl()->SetValidator(wxTextValidator(wxFILTER_NUMERIC));
    m_input_nozzle_max->GetTextCtrl()->SetSize(wxSize(-1, FromDIP(20)));
    m_input_nozzle_min->GetTextCtrl()->SetValidator(wxTextValidator(wxFILTER_NUMERIC));
    m_input_nozzle_min->GetTextCtrl()->SetSize(wxSize(-1, FromDIP(20)));
    auto bitmap_max_degree = new wxStaticBitmap(parent, -1, create_scaled_bitmap("degree", nullptr, 16), wxDefaultPosition, wxDefaultSize);
    auto bitmap_min_degree = new wxStaticBitmap(parent, -1, create_scaled_bitmap("degree", nullptr, 16), wxDefaultPosition, wxDefaultSize);
    sizer_tempinput->Add(m_input_nozzle_max, 1, wxALIGN_CENTER, 0);
    sizer_tempinput->Add(bitmap_min_degree, 0, wxALIGN_CENTER, 0);
    sizer_tempinput->Add(FromDIP(10), 0, 0, 0);
    sizer_tempinput->Add(m_input_nozzle_min, 1, wxALIGN_CENTER, 0);
    sizer_tempinput->Add(bitmap_max_degree, 0, wxALIGN_CENTER, 0);
    wxBoxSizer* sizer_temp_txt = new wxBoxSizer(wxHORIZONTAL);
    auto        m_title_max = new wxStaticText(parent, wxID_ANY, _L("max"), wxDefaultPosition, AMS_MATERIALS_SETTING_INPUT_SIZE);
    m_title_max->SetForegroundColour(AMS_MATERIALS_SETTING_GREY800);
    m_title_max->SetFont(::Label::Body_13);
    auto m_title_min = new wxStaticText(parent, wxID_ANY, _L("min"), wxDefaultPosition, AMS_MATERIALS_SETTING_INPUT_SIZE);
    m_title_min->SetForegroundColour(AMS_MATERIALS_SETTING_GREY800);
    m_title_min->SetFont(::Label::Body_13);
    sizer_temp_txt->Add(m_title_max, 1, wxALIGN_CENTER, 0);
    sizer_temp_txt->Add(FromDIP(10), 0, 0, 0);
    sizer_temp_txt->Add(m_title_min, 1, wxALIGN_CENTER | wxRIGHT, FromDIP(16));
    sizer_other->Add(sizer_temp_txt, 0, wxALIGN_CENTER, 0);
    sizer_other->Add(sizer_tempinput, 0, wxALIGN_CENTER, 0);
    m_sizer_temperature->Add(sizer_other, 0, wxALL | wxALIGN_CENTER, 0);
    m_sizer_temperature->AddStretchSpacer();
    wxString warning_string = wxString::FromUTF8(
        (boost::format(_u8L("The input value should be greater than %1% and less than %2%")) % FILAMENT_MIN_TEMP % FILAMENT_MAX_TEMP).str());
    warning_text = new wxStaticText(parent, wxID_ANY, warning_string, wxDefaultPosition, wxDefaultSize, 0);
    warning_text->SetFont(::Label::Body_13);
    warning_text->SetForegroundColour(wxColour(255, 111, 0));
    warning_text->Wrap(AMS_MATERIALS_SETTING_BODY_WIDTH);
    warning_text->SetMinSize(wxSize(AMS_MATERIALS_SETTING_BODY_WIDTH, -1));
    warning_text->Hide();
    m_panel_SN = new wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    wxBoxSizer* m_sizer_SN = new wxBoxSizer(wxVERTICAL);
    m_sizer_SN->AddSpacer(FromDIP(16));
    wxBoxSizer* m_sizer_SN_inside = new wxBoxSizer(wxHORIZONTAL);
    auto m_title_SN = new wxStaticText(m_panel_SN, wxID_ANY, _L("SN"), wxDefaultPosition, wxSize(AMS_MATERIALS_SETTING_LABEL_WIDTH, -1), 0);
    m_title_SN->SetFont(::Label::Body_13);
    m_title_SN->SetForegroundColour(AMS_MATERIALS_SETTING_GREY800);
    m_title_SN->Wrap(-1);
    m_sizer_SN_inside->Add(m_title_SN, 0, wxALIGN_CENTER, 0);
    m_sizer_SN_inside->Add(0, 0, 0, wxEXPAND, 0);
    m_sn_number = new wxStaticText(m_panel_SN, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize);
    m_sn_number->SetForegroundColour(*wxBLACK);
    m_sizer_SN_inside->Add(m_sn_number, 0, wxALIGN_CENTER, 0);
    m_sizer_SN->Add(m_sizer_SN_inside);
    m_panel_SN->SetSizer(m_sizer_SN);
    m_panel_SN->Layout();
    m_panel_SN->Fit();
    wxBoxSizer* m_tip_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_tip_readonly = new wxStaticText(parent, wxID_ANY, _L("Setting AMS slot information while printing is not supported"), wxDefaultPosition, wxSize(-1, AMS_MATERIALS_SETTING_INPUT_SIZE.y));
    m_tip_readonly->SetForegroundColour(*wxBLACK);
    m_tip_readonly->Hide();
    m_tip_sizer->Add(m_tip_readonly, 0, wxALIGN_CENTER | wxRIGHT, FromDIP(20));
    sizer->Add(0, 0, 0, wxTOP, FromDIP(16));
    sizer->Add(m_sizer_filament, 0, wxLEFT | wxRIGHT, FromDIP(20));
    sizer->Add(0, 0, 0, wxTOP, FromDIP(16));
    sizer->Add(m_sizer_colour, 0, wxLEFT | wxRIGHT, FromDIP(20));
    sizer->Add(0, 0, 0, wxTOP, FromDIP(16));
    sizer->Add(m_sizer_temperature, 0, wxLEFT | wxRIGHT, FromDIP(20));
    sizer->Add(0, 0, 0, wxTOP, FromDIP(5));
    sizer->Add(warning_text, 0, wxLEFT | wxRIGHT, FromDIP(20));
    sizer->Add(m_panel_SN, 0, wxLEFT, FromDIP(20));
    sizer->Add(0, 0, 0, wxTOP, FromDIP(24));
    sizer->Add(m_tip_sizer, 0, wxLEFT, FromDIP(20));
    parent->SetSizer(sizer);
}
References _L, _u8L, AMS_MATERIALS_SETTING_BODY_WIDTH, AMS_MATERIALS_SETTING_COMBOX_WIDTH, AMS_MATERIALS_SETTING_GREY800, AMS_MATERIALS_SETTING_INPUT_SIZE, AMS_MATERIALS_SETTING_LABEL_WIDTH, Label::Body_13, Label::Body_14, create_scaled_bitmap(), TextInput::Enable(), FILAMENT_MAX_TEMP, FILAMENT_MIN_TEMP, StateColor::Focused, TextInput::GetTextCtrl(), StateColor::Hovered, m_clr_picker, m_comboBox_filament, m_input_nozzle_max, m_input_nozzle_min, m_panel_SN, m_readonly_filament, m_sn_number, m_tip_readonly, m_title_colour, m_title_filament, m_title_temperature, StateColor::Normal, on_clr_picker(), Slic3r::GUI::ColorPicker::set_show_full(), TextInput::SetLabelColor(), warning_text, and wxStaticText.
Referenced by create().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_confirm_button()
void Slic3r::GUI::AMSMaterialsSetting::enable_confirm_button (bool en)
{
    m_button_confirm->Show(en);
    if (!m_is_third) {
        m_tip_readonly->Hide();
    }
    else {
        m_comboBox_filament->Show(en);
        m_readonly_filament->Show(!en);
        if ( !is_virtual_tray() ) {
            m_tip_readonly->SetLabelText(_L("Setting AMS slot information while printing is not supported"));
        }
        else {
            m_tip_readonly->SetLabelText(_L("Setting Virtual slot information while printing is not supported"));
        }
        m_tip_readonly->Show(!en);
    }
}
References _L, is_virtual_tray(), m_button_confirm, m_comboBox_filament, m_is_third, m_readonly_filament, and m_tip_readonly.
Referenced by update().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
input_max_finish()
void Slic3r::GUI::AMSMaterialsSetting::input_max_finish ()
{
    if (m_input_nozzle_max->GetTextCtrl()->GetValue().empty()) return;
    auto val = std::atoi(m_input_nozzle_max->GetTextCtrl()->GetValue().c_str());
    if (val < FILAMENT_MIN_TEMP || val > FILAMENT_MAX_TEMP) {
        warning_text->Show();
    }
    else {
        warning_text->Hide();
    }
    Layout();
    Fit();
}
References FILAMENT_MAX_TEMP, TextInput::GetTextCtrl(), m_input_nozzle_max, and warning_text.
Referenced by create().
input_min_finish()
void Slic3r::GUI::AMSMaterialsSetting::input_min_finish ()
{
    if (m_input_nozzle_min->GetTextCtrl()->GetValue().empty()) return;
    auto val = std::atoi(m_input_nozzle_min->GetTextCtrl()->GetValue().c_str());
    if (val < FILAMENT_MIN_TEMP || val > FILAMENT_MAX_TEMP) {
        warning_text->Show();
    } else {
        warning_text->Hide();
    }
    Layout();
    Fit();
}
References FILAMENT_MAX_TEMP, TextInput::GetTextCtrl(), m_input_nozzle_min, and warning_text.
Referenced by create().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
is_virtual_tray()
bool Slic3r::GUI::AMSMaterialsSetting::is_virtual_tray () protected
{
    if (tray_id == VIRTUAL_TRAY_ID)
        return true;
    return false;
}
References tray_id, and VIRTUAL_TRAY_ID.
Referenced by enable_confirm_button(), on_select_ok(), on_select_reset(), Popup(), and update_widgets().
msw_rescale()
void Slic3r::GUI::AMSMaterialsSetting::msw_rescale ()
{
    m_clr_picker->msw_rescale();
}
References m_clr_picker, and Slic3r::GUI::ColorPicker::msw_rescale().
Referenced by Slic3r::GUI::StatusPanel::on_sys_color_changed().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_clr_picker()
void Slic3r::GUI::AMSMaterialsSetting::on_clr_picker (wxMouseEvent & event) protected
{
    if(!m_is_third || obj->is_in_printing() || obj->can_resume())
        return;
    std::vector<wxColour> ams_colors;
    for (auto ams_it = obj->amsList.begin(); ams_it != obj->amsList.end(); ++ams_it) {
        for (auto tray_id = ams_it->second->trayList.begin(); tray_id != ams_it->second->trayList.end(); ++tray_id) {
            std::vector<wxColour>::iterator iter = find(ams_colors.begin(), ams_colors.end(), AmsTray::decode_color(tray_id->second->color));
            if (iter == ams_colors.end()) {
                ams_colors.push_back(AmsTray::decode_color(tray_id->second->color));
            }
        }
    }
    wxPoint img_pos = m_clr_picker->ClientToScreen(wxPoint(0, 0));
    wxPoint popup_pos(img_pos.x + FromDIP(50), img_pos.y);
    m_color_picker_popup.Position(popup_pos, wxSize(0, 0));
    m_color_picker_popup.set_ams_colours(ams_colors);
    m_color_picker_popup.set_def_colour(m_clr_picker->m_colour);
    m_color_picker_popup.Popup();
}
References Slic3r::MachineObject::amsList, Slic3r::MachineObject::can_resume(), Slic3r::AmsTray::decode_color(), Slic3r::MachineObject::is_in_printing(), m_clr_picker, m_color_picker_popup, Slic3r::GUI::ColorPicker::m_colour, m_is_third, obj, Slic3r::GUI::ColorPickerPopup::Popup(), Slic3r::GUI::ColorPickerPopup::set_ams_colours(), Slic3r::GUI::ColorPickerPopup::set_def_colour(), and tray_id.
Referenced by create_panel_normal().
on_dpi_changed()
void Slic3r::GUI::AMSMaterialsSetting::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{ this->Refresh(); }
on_picker_color()
void Slic3r::GUI::AMSMaterialsSetting::on_picker_color (wxCommandEvent & color)
{
    unsigned int color_num  = event.GetInt();
    set_color(wxColour(color_num>>16&0xFF, color_num>>8&0xFF, color_num&0xFF));
}
References set_color().
Referenced by create().
on_select_close()
void Slic3r::GUI::AMSMaterialsSetting::on_select_close (wxCommandEvent & event) protected
{
    Close();
}
Referenced by create().
on_select_filament()
void Slic3r::GUI::AMSMaterialsSetting::on_select_filament (wxCommandEvent & evt) protected
{
    m_filament_type = "";
    PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    if (preset_bundle) {
        for (auto it = preset_bundle->filaments.begin(); it != preset_bundle->filaments.end(); it++) {
            if (!m_comboBox_filament->GetValue().IsEmpty() && it->alias.compare(m_comboBox_filament->GetValue().ToStdString()) == 0) {
                // ) if nozzle_temperature_range is found
                ConfigOption* opt_min = it->config.option("nozzle_temperature_range_low");
                if (opt_min) {
                    ConfigOptionInts* opt_min_ints = dynamic_cast<ConfigOptionInts*>(opt_min);
                    if (opt_min_ints) {
                        wxString text_nozzle_temp_min = wxString::Format("%d", opt_min_ints->get_at(0));
                        m_input_nozzle_min->GetTextCtrl()->SetValue(text_nozzle_temp_min);
                    }
                }
                ConfigOption* opt_max = it->config.option("nozzle_temperature_range_high");
                if (opt_max) {
                    ConfigOptionInts* opt_max_ints = dynamic_cast<ConfigOptionInts*>(opt_max);
                    if (opt_max_ints) {
                        wxString text_nozzle_temp_max = wxString::Format("%d", opt_max_ints->get_at(0));
                        m_input_nozzle_max->GetTextCtrl()->SetValue(text_nozzle_temp_max);
                    }
                }
                ConfigOption* opt_type = it->config.option("filament_type");
                bool found_filament_type = false;
                if (opt_type) {
                    ConfigOptionStrings* opt_type_strs = dynamic_cast<ConfigOptionStrings*>(opt_type);
                    if (opt_type_strs) {
                        found_filament_type = true;
                        //m_filament_type = opt_type_strs->get_at(0);
                        std::string display_filament_type;
                        m_filament_type = it->config.get_filament_type(display_filament_type);
                    }
                }
                if (!found_filament_type)
                    m_filament_type = "";
                break;
            }
        }
    }
    if (m_input_nozzle_min->GetTextCtrl()->GetValue().IsEmpty()) {
         m_input_nozzle_min->GetTextCtrl()->SetValue("0");
    }
    if (m_input_nozzle_max->GetTextCtrl()->GetValue().IsEmpty()) {
         m_input_nozzle_max->GetTextCtrl()->SetValue("0");
    }
    m_filament_selection = evt.GetSelection();
}
References Slic3r::PresetCollection::begin(), Slic3r::PresetCollection::end(), Slic3r::PresetBundle::filaments, Slic3r::ConfigOptionVector< T >::get_at(), TextInput::GetTextCtrl(), ComboBox::GetValue(), m_comboBox_filament, m_filament_selection, m_filament_type, m_input_nozzle_max, and m_input_nozzle_min.
Referenced by ~AMSMaterialsSetting(), and create().
on_select_ok()
void Slic3r::GUI::AMSMaterialsSetting::on_select_ok (wxCommandEvent & event) protected
{
    wxString k_text = m_input_k_val->GetTextCtrl()->GetValue();
    wxString n_text = m_input_n_val->GetTextCtrl()->GetValue();
    if (is_virtual_tray() && obj && !obj->is_support_filament_edit_virtual_tray) {
        if (!ExtrusionCalibration::check_k_validation(k_text)) {
            wxString k_tips = _L("Please input a valid value (K in 0~0.5)");
            wxString kn_tips = _L("Please input a valid value (K in 0~0.5, N in 0.6~2.0)");
            MessageDialog msg_dlg(nullptr, k_tips, wxEmptyString, wxICON_WARNING | wxOK);
            msg_dlg.ShowModal();
            return;
        }
        double k = 0.0;
        try {
            k_text.ToDouble(&k);
        }
        catch (...) {
            ;
        }
        double n = 0.0;
        try {
            n_text.ToDouble(&n);
        }
        catch (...) {
            ;
        }
        obj->command_extrusion_cali_set(VIRTUAL_TRAY_ID, "", "", k, n);
        Close();
    }
    else {
        if (!m_is_third) {
            // check and set k n
            if (obj->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY)) {
                if (!ExtrusionCalibration::check_k_validation(k_text)) {
                    wxString k_tips = _L("Please input a valid value (K in 0~0.5)");
                    wxString kn_tips = _L("Please input a valid value (K in 0~0.5, N in 0.6~2.0)");
                    MessageDialog msg_dlg(nullptr, k_tips, wxEmptyString, wxICON_WARNING | wxOK);
                    msg_dlg.ShowModal();
                    return;
                }
            }
            // set k / n value
            if (obj->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY)) {
                // set extrusion cali ratio
                int cali_tray_id = ams_id * 4 + tray_id;
                double k = 0.0;
                try {
                    k_text.ToDouble(&k);
                }
                catch (...) {
                    ;
                }
                double n = 0.0;
                try {
                    n_text.ToDouble(&n);
                }
                catch (...) {
                    ;
                }
                obj->command_extrusion_cali_set(cali_tray_id, "", "", k, n);
            }
            Close();
            return;
        }
        wxString nozzle_temp_min = m_input_nozzle_min->GetTextCtrl()->GetValue();
        auto     filament = m_comboBox_filament->GetValue();
        wxString nozzle_temp_max = m_input_nozzle_max->GetTextCtrl()->GetValue();
        long nozzle_temp_min_int, nozzle_temp_max_int;
        nozzle_temp_min.ToLong(&nozzle_temp_min_int);
        nozzle_temp_max.ToLong(&nozzle_temp_max_int);
        wxColour color = m_clr_picker->m_colour;
        char col_buf[10];
        sprintf(col_buf, "%02X%02X%02XFF", (int)color.Red(), (int)color.Green(), (int)color.Blue());
        ams_filament_id = "";
        ams_setting_id = "";
        PresetBundle* preset_bundle = wxGetApp().preset_bundle;
        if (preset_bundle) {
            for (auto it = preset_bundle->filaments.begin(); it != preset_bundle->filaments.end(); it++) {
                if (it->alias.compare(m_comboBox_filament->GetValue().ToStdString()) == 0) {
                    //check is it in the filament blacklist
                    if(!is_virtual_tray()){
                        bool in_blacklist = false;
                        std::string action;
                        std::string info;
                        std::string filamnt_type;
                        it->get_filament_type(filamnt_type);
                        if (it->vendor) {
                            DeviceManager::check_filaments_in_blacklist(it->vendor->name, filamnt_type, in_blacklist, action, info);
                        }
                        if (in_blacklist) {
                            if (action == "prohibition") {
                                MessageDialog msg_wingow(nullptr, info, _L("Error"), wxICON_WARNING | wxOK);
                                msg_wingow.ShowModal();
                                //m_comboBox_filament->SetSelection(m_filament_selection);
                                return;
                            }
                            else if (action == "warning") {
                                MessageDialog msg_wingow(nullptr, info, _L("Warning"), wxICON_INFORMATION | wxOK);
                                msg_wingow.ShowModal();
                            }
                        }
                    }
                    ams_filament_id = it->filament_id;
                    ams_setting_id = it->setting_id;
                    break;
                }
            }
        }
        if (ams_filament_id.empty() || nozzle_temp_min.empty() || nozzle_temp_max.empty() || m_filament_type.empty()) {
            BOOST_LOG_TRIVIAL(trace) << "Invalid Setting id";
            MessageDialog msg_dlg(nullptr, _L("You need to select the material type and color first."), wxEmptyString, wxICON_WARNING | wxOK);
            msg_dlg.ShowModal();
            return;
        }
        else {
            if (obj) {
                if (obj->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY)) {
                    if (!ExtrusionCalibration::check_k_validation(k_text)) {
                        wxString k_tips = _L("Please input a valid value (K in 0~0.5)");
                        wxString kn_tips = _L("Please input a valid value (K in 0~0.5, N in 0.6~2.0)");
                        MessageDialog msg_dlg(nullptr, k_tips, wxEmptyString, wxICON_WARNING | wxOK);
                        msg_dlg.ShowModal();
                        return;
                    }
                }
                // set filament
                if (obj->is_support_filament_edit_virtual_tray || !is_virtual_tray()) {
                    if (is_virtual_tray()) {
                        obj->command_ams_filament_settings(255, VIRTUAL_TRAY_ID, ams_filament_id, ams_setting_id, std::string(col_buf), m_filament_type, nozzle_temp_min_int, nozzle_temp_max_int);
                    }
                    else {
                        obj->command_ams_filament_settings(ams_id, tray_id, ams_filament_id, ams_setting_id, std::string(col_buf), m_filament_type, nozzle_temp_min_int, nozzle_temp_max_int);
                    }
                }
                // set k / n value
                if (obj->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY)) {
                    // set extrusion cali ratio
                    int cali_tray_id = ams_id * 4 + tray_id;
                    double k = 0.0;
                    try {
                        k_text.ToDouble(&k);
                    }
                    catch (...) {
                        ;
                    }
                    double n = 0.0;
                    try {
                        n_text.ToDouble(&n);
                    }
                    catch (...) {
                        ;
                    }
                    obj->command_extrusion_cali_set(cali_tray_id, "", "", k, n);
                }
            }
        }
    }
    Close();
}
References _L, ams_filament_id, ams_id, ams_setting_id, Slic3r::PresetCollection::begin(), Slic3r::DeviceManager::check_filaments_in_blacklist(), Slic3r::GUI::ExtrusionCalibration::check_k_validation(), Slic3r::MachineObject::command_ams_filament_settings(), Slic3r::MachineObject::command_extrusion_cali_set(), Slic3r::PresetCollection::end(), Slic3r::PresetBundle::filaments, Slic3r::FUNC_VIRTUAL_TYAY, TextInput::GetTextCtrl(), ComboBox::GetValue(), Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_support_filament_edit_virtual_tray, is_virtual_tray(), m_clr_picker, Slic3r::GUI::ColorPicker::m_colour, m_comboBox_filament, m_filament_type, m_input_k_val, m_input_n_val, m_input_nozzle_max, m_input_nozzle_min, m_is_third, n, obj, Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::trace(), tray_id, and VIRTUAL_TRAY_ID.
Referenced by create().
on_select_reset()
void Slic3r::GUI::AMSMaterialsSetting::on_select_reset (wxCommandEvent & event) protected
{
    MessageDialog msg_dlg(nullptr, _L("Are you sure you want to clear the filament information?"), wxEmptyString, wxICON_WARNING | wxOK | wxCANCEL);
    auto result = msg_dlg.ShowModal();
    if (result != wxID_OK)
        return;
    m_input_nozzle_min->GetTextCtrl()->SetValue("");
    m_input_nozzle_max->GetTextCtrl()->SetValue("");
    ams_filament_id = "";
    ams_setting_id = "";
    wxString k_text = "0.000";
    wxString n_text = "0.000";
    m_filament_type = "";
    long nozzle_temp_min_int = 0;
    long nozzle_temp_max_int = 0;
    wxColour color = *wxWHITE;
    char col_buf[10];
    sprintf(col_buf, "%02X%02X%02XFF", (int)color.Red(), (int)color.Green(), (int)color.Blue());
    if (obj) {
        // set filament
        if (obj->is_support_filament_edit_virtual_tray || !is_virtual_tray()) {
            if (is_virtual_tray()) {
                obj->command_ams_filament_settings(255, VIRTUAL_TRAY_ID, ams_filament_id, ams_setting_id, std::string(col_buf), m_filament_type, nozzle_temp_min_int, nozzle_temp_max_int);
            }
            else {
                obj->command_ams_filament_settings(ams_id, tray_id, ams_filament_id, ams_setting_id, std::string(col_buf), m_filament_type, nozzle_temp_min_int, nozzle_temp_max_int);
            }
        }
        // set k / n value
        if (obj->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY)) {
            // set extrusion cali ratio
            int cali_tray_id = ams_id * 4 + tray_id;
            double k = 0.0;
            try {
                k_text.ToDouble(&k);
            }
            catch (...) {
                ;
            }
            double n = 0.0;
            try {
                n_text.ToDouble(&n);
            }
            catch (...) {
                ;
            }
            obj->command_extrusion_cali_set(cali_tray_id, "", "", k, n);
        }
    }
    Close();
}
References _L, ams_filament_id, ams_id, ams_setting_id, Slic3r::MachineObject::command_ams_filament_settings(), Slic3r::MachineObject::command_extrusion_cali_set(), Slic3r::FUNC_VIRTUAL_TYAY, TextInput::GetTextCtrl(), Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_support_filament_edit_virtual_tray, is_virtual_tray(), m_filament_type, m_input_nozzle_max, m_input_nozzle_min, n, obj, Slic3r::GUI::DPIAware< P >::ShowModal(), tray_id, and VIRTUAL_TRAY_ID.
Referenced by create().
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
paintEvent()
void Slic3r::GUI::AMSMaterialsSetting::paintEvent (wxPaintEvent & evt)
{
    auto      size = GetSize();
    wxPaintDC dc(this);
    dc.SetPen(wxPen(StateColor::darkModeColorFor(wxColour("#000000")), 1, wxSOLID));
    dc.SetBrush(wxBrush(*wxTRANSPARENT_BRUSH));
    dc.DrawRectangle(0, 0, size.x, size.y);
}
References StateColor::darkModeColorFor(), and size.
Referenced by create().
Popup()
void Slic3r::GUI::AMSMaterialsSetting::Popup (wxString filament = wxEmptyString, wxString sn = wxEmptyString, wxString temp_min = wxEmptyString, wxString temp_max = wxEmptyString, wxString k = wxEmptyString, wxString n = wxEmptyString)
{
    update_widgets();
    // set default value
    if (k.IsEmpty())
        k = "0.000";
    if (n.IsEmpty())
        n = "0.000";
    m_input_k_val->GetTextCtrl()->SetValue(k);
    m_input_n_val->GetTextCtrl()->SetValue(n);
    if (is_virtual_tray() && obj && !obj->is_support_filament_edit_virtual_tray) {
        m_button_reset->Show();
        m_button_confirm->Show();
        update();
        Layout();
        Fit();
        ShowModal();
        return;
    } else {
       /* m_clr_picker->set_color(wxColour(
            m_clrData->GetColour().Red(),
            m_clrData->GetColour().Green(),
            m_clrData->GetColour().Blue(),
            254
        ));*/
        if (!m_is_third) {
            m_button_reset->Hide();
            if (obj && obj->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY)) {
                m_button_confirm->Show();
            } else {
                m_button_confirm->Hide();
            }
            m_sn_number->SetLabel(sn);
            m_panel_SN->Show();
            m_comboBox_filament->Hide();
            m_readonly_filament->Show();
            //m_readonly_filament->GetTextCtrl()->SetLabel("Bambu " + filament);
            m_readonly_filament->SetLabel("Bambu " + filament);
            m_input_nozzle_min->GetTextCtrl()->SetValue(temp_min);
            m_input_nozzle_max->GetTextCtrl()->SetValue(temp_max);
            update();
            Layout();
            Fit();
            ShowModal();
            return;
        }
        m_button_reset->Show();
        m_button_confirm->Show();
        m_panel_SN->Hide();
        m_comboBox_filament->Show();
        m_readonly_filament->Hide();
        int selection_idx = -1, idx = 0;
        wxArrayString filament_items;
        std::set<std::string> filament_id_set;
        PresetBundle* preset_bundle = wxGetApp().preset_bundle;
        if (preset_bundle) {
            BOOST_LOG_TRIVIAL(trace) << "system_preset_bundle filament number=" << preset_bundle->filaments.size();
            for (auto filament_it = preset_bundle->filaments.begin(); filament_it != preset_bundle->filaments.end(); filament_it++) {
                // filter by system preset
                if (!filament_it->is_system) continue;
                for (auto printer_it = preset_bundle->printers.begin(); printer_it != preset_bundle->printers.end(); printer_it++) {
                    // filter by system preset
                    if (!printer_it->is_system) continue;
                    // get printer_model
                    ConfigOption* printer_model_opt = printer_it->config.option("printer_model");
                    ConfigOptionString* printer_model_str = dynamic_cast<ConfigOptionString*>(printer_model_opt);
                    if (!printer_model_str || !obj)
                        continue;
                    // use printer_model as printer type
                    if (printer_model_str->value != MachineObject::get_preset_printer_model_name(obj->printer_type))
                        continue;
                    ConfigOption* printer_opt = filament_it->config.option("compatible_printers");
                    ConfigOptionStrings* printer_strs = dynamic_cast<ConfigOptionStrings*>(printer_opt);
                    for (auto printer_str : printer_strs->values) {
                        if (printer_it->name == printer_str) {
                            if (filament_id_set.find(filament_it->filament_id) != filament_id_set.end()) {
                                continue;
                            }
                            else {
                                filament_id_set.insert(filament_it->filament_id);
                                // name matched
                                filament_items.push_back(filament_it->alias);
                                if (filament_it->filament_id == ams_filament_id) {
                                    selection_idx = idx;
                                    // update if nozzle_temperature_range is found
                                    ConfigOption* opt_min = filament_it->config.option("nozzle_temperature_range_low");
                                    if (opt_min) {
                                        ConfigOptionInts* opt_min_ints = dynamic_cast<ConfigOptionInts*>(opt_min);
                                        if (opt_min_ints) {
                                            wxString text_nozzle_temp_min = wxString::Format("%d", opt_min_ints->get_at(0));
                                            m_input_nozzle_min->GetTextCtrl()->SetValue(text_nozzle_temp_min);
                                        }
                                    }
                                    ConfigOption* opt_max = filament_it->config.option("nozzle_temperature_range_high");
                                    if (opt_max) {
                                        ConfigOptionInts* opt_max_ints = dynamic_cast<ConfigOptionInts*>(opt_max);
                                        if (opt_max_ints) {
                                            wxString text_nozzle_temp_max = wxString::Format("%d", opt_max_ints->get_at(0));
                                            m_input_nozzle_max->GetTextCtrl()->SetValue(text_nozzle_temp_max);
                                        }
                                    }
                                }
                                idx++;
                            }
                        }
                    }
                }
            }
            m_comboBox_filament->Set(filament_items);
            m_comboBox_filament->SetSelection(selection_idx);
            post_select_event();
        }
    }
    update();
    Layout();
    Fit();
    ShowModal();
}
References ams_filament_id, Slic3r::PresetCollection::begin(), Slic3r::PresetCollection::end(), Slic3r::PresetBundle::filaments, Slic3r::FUNC_VIRTUAL_TYAY, Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::MachineObject::get_preset_printer_model_name(), TextInput::GetTextCtrl(), Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_support_filament_edit_virtual_tray, is_virtual_tray(), m_button_confirm, m_button_reset, m_comboBox_filament, m_input_k_val, m_input_n_val, m_input_nozzle_max, m_input_nozzle_min, m_is_third, m_panel_SN, m_readonly_filament, m_sn_number, n, obj, post_select_event(), Slic3r::MachineObject::printer_type, Slic3r::PresetBundle::printers, TextInput::SetLabel(), ComboBox::SetSelection(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::PresetCollection::size(), Slic3r::trace(), update(), update_widgets(), Slic3r::ConfigOptionSingle< T >::value, and Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::StatusPanel::on_ext_spool_edit(), and Slic3r::GUI::StatusPanel::on_filament_edit().
post_select_event()
void Slic3r::GUI::AMSMaterialsSetting::post_select_event ()
{
    wxCommandEvent event(wxEVT_COMBOBOX);
    event.SetEventObject(m_comboBox_filament);
    wxPostEvent(m_comboBox_filament, event);
}
References m_comboBox_filament.
Referenced by Popup().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
set_color()
void Slic3r::GUI::AMSMaterialsSetting::set_color (wxColour color)
{
    //m_clrData->SetColour(color);
    m_clr_picker->set_color(color);
}
References m_clr_picker, and Slic3r::GUI::ColorPicker::set_color().
Referenced by Slic3r::GUI::StatusPanel::on_ext_spool_edit(), Slic3r::GUI::StatusPanel::on_filament_edit(), and on_picker_color().
set_colors()
void Slic3r::GUI::AMSMaterialsSetting::set_colors (std::vector< wxColour > colors)
{
    //m_clrData->SetColour(color);
    m_clr_picker->set_colors(colors);
}
References m_clr_picker, and Slic3r::GUI::ColorPicker::set_colors().
Referenced by Slic3r::GUI::StatusPanel::on_filament_edit().
Show()
bool Slic3r::GUI::AMSMaterialsSetting::Show (bool show) override
{
    if (show) {
        m_button_confirm->SetMinSize(AMS_MATERIALS_SETTING_BUTTON_SIZE);
        m_input_nozzle_max->GetTextCtrl()->SetSize(wxSize(-1, FromDIP(20)));
        m_input_nozzle_min->GetTextCtrl()->SetSize(wxSize(-1, FromDIP(20)));
        //m_clr_picker->set_color(m_clr_picker->GetParent()->GetBackgroundColour());
        if (obj && obj->is_function_supported(PrinterFunction::FUNC_EXTRUSION_CALI)) {
            m_ratio_text->Show();
            m_k_param->Show();
            m_input_k_val->Show();
        }
        else {
            m_ratio_text->Hide();
            m_k_param->Hide();
            m_input_k_val->Hide();
        }
        Layout();
        Fit();
        wxGetApp().UpdateDarkUI(this);
    }
    return DPIDialog::Show(show);
}
References AMS_MATERIALS_SETTING_BUTTON_SIZE, Slic3r::FUNC_EXTRUSION_CALI, TextInput::GetTextCtrl(), Slic3r::MachineObject::is_function_supported(), m_button_confirm, m_input_k_val, m_input_nozzle_max, m_input_nozzle_min, m_k_param, m_ratio_text, obj, and Button::SetMinSize().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), on_select_ok(), on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
update()
void Slic3r::GUI::AMSMaterialsSetting::update ()
{
    if (obj) {
        update_widgets();
        if (obj->is_in_printing() || obj->can_resume()) {
            enable_confirm_button(false);
        } else {
            enable_confirm_button(true);
        }
    }
}
References Slic3r::MachineObject::can_resume(), enable_confirm_button(), Slic3r::MachineObject::is_in_printing(), obj, and update_widgets().
Referenced by Popup(), and Slic3r::GUI::StatusPanel::update_ams().
update_widgets()
void Slic3r::GUI::AMSMaterialsSetting::update_widgets () protected
{
    // virtual tray
    if (is_virtual_tray()) {
        if (obj && obj->is_support_filament_edit_virtual_tray)
            m_panel_normal->Show();
        else
            m_panel_normal->Hide();
        m_panel_kn->Show();
    } else if (obj && obj->is_function_supported(PrinterFunction::FUNC_VIRTUAL_TYAY)) {
        m_panel_normal->Show();
        m_panel_kn->Show();
    } else {
        m_panel_normal->Show();
        m_panel_kn->Hide();
    }
    Layout();
}
References Slic3r::FUNC_VIRTUAL_TYAY, Slic3r::MachineObject::is_function_supported(), Slic3r::MachineObject::is_support_filament_edit_virtual_tray, is_virtual_tray(), m_panel_kn, m_panel_normal, and obj.
Referenced by Popup(), and update().
Member Data Documentation
ams_filament_id
std::string Slic3r::GUI::AMSMaterialsSetting::ams_filament_id
Referenced by Slic3r::GUI::StatusPanel::on_ext_spool_edit(), Slic3r::GUI::StatusPanel::on_filament_edit(), on_select_ok(), on_select_reset(), and Popup().
ams_id
int Slic3r::GUI::AMSMaterialsSetting::ams_id { 0 }
Referenced by Slic3r::GUI::StatusPanel::on_filament_edit(), on_select_ok(), and on_select_reset().
ams_setting_id
std::string Slic3r::GUI::AMSMaterialsSetting::ams_setting_id
Referenced by on_select_ok(), and on_select_reset().
m_brand_colour
wxColour Slic3r::GUI::AMSMaterialsSetting::m_brand_colour
m_brand_filament
wxString Slic3r::GUI::AMSMaterialsSetting::m_brand_filament
m_brand_sn
wxString Slic3r::GUI::AMSMaterialsSetting::m_brand_sn
m_brand_tmp
wxString Slic3r::GUI::AMSMaterialsSetting::m_brand_tmp
m_btn_bg_gray
StateColor Slic3r::GUI::AMSMaterialsSetting::m_btn_bg_gray protected
Referenced by create().
m_btn_bg_green
StateColor Slic3r::GUI::AMSMaterialsSetting::m_btn_bg_green protected
Referenced by create().
m_button_close
Button* Slic3r::GUI::AMSMaterialsSetting::m_button_close protected
Referenced by create().
m_button_confirm
Button* Slic3r::GUI::AMSMaterialsSetting::m_button_confirm protected
Referenced by create(), enable_confirm_button(), Popup(), and Show().
m_button_reset
Button* Slic3r::GUI::AMSMaterialsSetting::m_button_reset protected
Referenced by create(), and Popup().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_clr_picker
ColorPicker* Slic3r::GUI::AMSMaterialsSetting::m_clr_picker protected
Referenced by create_panel_normal(), msw_rescale(), on_clr_picker(), on_select_ok(), set_color(), and set_colors().
m_clrData
wxColourData* Slic3r::GUI::AMSMaterialsSetting::m_clrData protected
m_color_picker_popup
ColorPickerPopup Slic3r::GUI::AMSMaterialsSetting::m_color_picker_popup
Referenced by on_clr_picker().
m_comboBox_filament
ComboBox* Slic3r::GUI::AMSMaterialsSetting::m_comboBox_filament protected
Referenced by ~AMSMaterialsSetting(), create(), create_panel_normal(), enable_confirm_button(), on_select_filament(), on_select_ok(), Popup(), and post_select_event().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_filament_selection
int Slic3r::GUI::AMSMaterialsSetting::m_filament_selection protected
Referenced by on_select_filament().
m_filament_type
std::string Slic3r::GUI::AMSMaterialsSetting::m_filament_type
Referenced by on_select_filament(), on_select_ok(), and on_select_reset().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_input_k_val
TextInput* Slic3r::GUI::AMSMaterialsSetting::m_input_k_val protected
Referenced by create_panel_kn(), on_select_ok(), Popup(), and Show().
m_input_n_val
TextInput* Slic3r::GUI::AMSMaterialsSetting::m_input_n_val protected
Referenced by create_panel_kn(), on_select_ok(), and Popup().
m_input_nozzle_max
TextInput* Slic3r::GUI::AMSMaterialsSetting::m_input_nozzle_max protected
Referenced by create(), create_panel_normal(), input_max_finish(), on_select_filament(), on_select_ok(), on_select_reset(), Popup(), and Show().
m_input_nozzle_min
TextInput* Slic3r::GUI::AMSMaterialsSetting::m_input_nozzle_min protected
Referenced by create(), create_panel_normal(), input_min_finish(), on_select_filament(), on_select_ok(), on_select_reset(), Popup(), and Show().
m_is_third
bool Slic3r::GUI::AMSMaterialsSetting::m_is_third
Referenced by enable_confirm_button(), on_clr_picker(), Slic3r::GUI::StatusPanel::on_ext_spool_edit(), Slic3r::GUI::StatusPanel::on_filament_edit(), on_select_ok(), and Popup().
m_k_param
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::m_k_param protected
Referenced by create_panel_kn(), and Show().
m_n_param
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::m_n_param protected
Referenced by create_panel_kn().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_panel_kn
wxPanel* Slic3r::GUI::AMSMaterialsSetting::m_panel_kn protected
Referenced by create(), and update_widgets().
m_panel_normal
wxPanel* Slic3r::GUI::AMSMaterialsSetting::m_panel_normal protected
Referenced by create(), and update_widgets().
m_panel_SN
wxPanel* Slic3r::GUI::AMSMaterialsSetting::m_panel_SN protected
Referenced by create_panel_normal(), and Popup().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_ratio_text
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::m_ratio_text protected
Referenced by create_panel_kn(), and Show().
m_readonly_filament
TextInput* Slic3r::GUI::AMSMaterialsSetting::m_readonly_filament protected
Referenced by create_panel_normal(), enable_confirm_button(), and Popup().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_sn_number
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::m_sn_number protected
Referenced by create_panel_normal(), and Popup().
m_tip_readonly
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::m_tip_readonly protected
Referenced by create_panel_normal(), and enable_confirm_button().
m_title_colour
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::m_title_colour protected
Referenced by create_panel_normal().
m_title_filament
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::m_title_filament protected
Referenced by create_panel_normal().
m_title_temperature
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::m_title_temperature protected
Referenced by create_panel_normal().
obj
MachineObject* Slic3r::GUI::AMSMaterialsSetting::obj { nullptr }
Referenced by on_clr_picker(), Slic3r::GUI::StatusPanel::on_ext_spool_edit(), Slic3r::GUI::StatusPanel::on_filament_edit(), on_select_ok(), on_select_reset(), Popup(), Show(), update(), Slic3r::GUI::StatusPanel::update_ams(), and update_widgets().
tray_id
int Slic3r::GUI::AMSMaterialsSetting::tray_id { 0 }
Referenced by is_virtual_tray(), on_clr_picker(), Slic3r::GUI::StatusPanel::on_ext_spool_edit(), Slic3r::GUI::StatusPanel::on_filament_edit(), on_select_ok(), and on_select_reset().
warning_text
wxStaticText* Slic3r::GUI::AMSMaterialsSetting::warning_text protected
Referenced by create(), create_panel_normal(), input_max_finish(), and input_min_finish().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AMSMaterialsSetting.hpp
src/slic3r/GUI/AMSMaterialsSetting.cpp