OrcaSlicer: TextInput Class Reference
TextInput Class Reference
#include <src/slic3r/GUI/Widgets/TextInput.hpp>
Public Member Functions
TextInput ()
TextInput (wxWindow *parent, wxString text, wxString label="", wxString icon="", const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void Create (wxWindow *parent, wxString text, wxString label="", wxString icon="", const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void SetCornerRadius (double radius)
void SetLabel (const wxString &label)
void SetIcon (const wxBitmap &icon)
void SetLabelColor (StateColor const &color)
void SetTextColor (StateColor const &color)
virtual void Rescale ()
virtual bool Enable (bool enable=true) override
virtual void SetMinSize (const wxSize &size) override
wxTextCtrl * GetTextCtrl ()
wxTextCtrl const * GetTextCtrl () const
Protected Member Functions
virtual void OnEdit ()
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
void DoSetToolTipText (wxString const &tip) override
Private Member Functions
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void messureSize ()
Private Attributes
wxSize labelSize
ScalableBitmap icon
StateColor label_color
StateColor text_color
wxTextCtrl * text_ctrl
Static Private Attributes
static const int TextInputWidth = 200
static const int TextInputHeight = 50
Detailed Description
Constructor & Destructor Documentation
TextInput() [1/2]
TextInput::TextInput ()
    : label_color(std::make_pair(0x909090, (int) StateColor::Disabled),
                 std::make_pair(0x6B6B6B, (int) StateColor::Normal))
    , text_color(std::make_pair(0x909090, (int) StateColor::Disabled),
                 std::make_pair(0x262E30, (int) StateColor::Normal))
{
    radius = 0;
    border_width = 1;
    border_color = StateColor(std::make_pair(0xDBDBDB, (int) StateColor::Disabled), std::make_pair(0x009688, (int) StateColor::Hovered),
                              std::make_pair(0xDBDBDB, (int) StateColor::Normal));
    background_color = StateColor(std::make_pair(0xF0F0F1, (int) StateColor::Disabled), std::make_pair(*wxWHITE, (int) StateColor::Normal));
    SetFont(Label::Body_12);
}
References Label::Body_12, StateColor::Disabled, StateColor::Hovered, and StateColor::Normal.
TextInput() [2/2]
TextInput::TextInput (wxWindow * parent, wxString text, wxString label = "", wxString icon = "", const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
    : TextInput()
{
    Create(parent, text, label, icon, pos, size, style);
}
References Create(), icon, size, and style.
Member Function Documentation
Create()
void TextInput::Create (wxWindow * parent, wxString text, wxString label = "", wxString icon = "", const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
{
        text_ctrl = nullptr;
    StaticBox::Create(parent, wxID_ANY, pos, size, style);
    wxWindow::SetLabel(label);
    style &= ~wxRIGHT;
    state_handler.attach({&label_color, & text_color});
    state_handler.update_binds();
    text_ctrl = new TextCtrl(this, wxID_ANY, text, {4, 4}, wxDefaultSize, style | wxBORDER_NONE | wxTE_PROCESS_ENTER);
    text_ctrl->SetFont(Label::Body_14);
    text_ctrl->SetInitialSize(text_ctrl->GetBestSize());
    text_ctrl->SetBackgroundColour(background_color.colorForStates(state_handler.states()));
    text_ctrl->SetForegroundColour(text_color.colorForStates(state_handler.states()));
    state_handler.attach_child(text_ctrl);
    text_ctrl->Bind(wxEVT_KILL_FOCUS, [this](auto &e) {
        OnEdit();
        e.SetId(GetId());
        ProcessEventLocally(e);
        e.Skip();
    });
    text_ctrl->Bind(wxEVT_TEXT_ENTER, [this](auto &e) {
        OnEdit();
        e.SetId(GetId());
        ProcessEventLocally(e);
    });
    text_ctrl->Bind(wxEVT_RIGHT_DOWN, [this](auto &e) {}); // disable context menu
    if (!icon.IsEmpty()) {
        this->icon = ScalableBitmap(this, icon.ToStdString(), 16);
    }
    messureSize();
}
References Label::Body_14, StateColor::colorForStates(), StaticBox::Create(), icon, label_color, messureSize(), OnEdit(), size, style, text_color, and text_ctrl.
Referenced by ComboBox::ComboBox(), and TextInput().
DoSetSize()
void TextInput::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) protected virtual
{
    wxWindow::DoSetSize(x, y, width, height, sizeFlags);
    if (sizeFlags & wxSIZE_USE_EXISTING) return;
    wxSize size = GetSize();
    wxPoint textPos = {5, 0};
    if (this->icon.bmp().IsOk()) {
        wxSize szIcon = this->icon.GetBmpSize();
        textPos.x += szIcon.x;
    }
    bool align_right = GetWindowStyle() & wxRIGHT;
    if (align_right)
        textPos.x += labelSize.x;
    if (text_ctrl) {
        wxSize textSize = text_ctrl->GetSize();
        textSize.x = size.x - textPos.x - labelSize.x - 10;
        text_ctrl->SetSize(textSize);
        text_ctrl->SetPosition({textPos.x, (size.y - textSize.y) / 2});
    }
}
References ScalableBitmap::bmp(), ScalableBitmap::GetBmpSize(), icon, labelSize, size, and text_ctrl.
DoSetToolTipText()
void TextInput::DoSetToolTipText (wxString const & tip) override protected
{
    wxWindow::DoSetToolTipText(tip);
    text_ctrl->SetToolTip(tip);
}
References text_ctrl.
Enable()
bool TextInput::Enable (bool enable = true) override virtual
{
    bool result = text_ctrl->Enable(enable) && wxWindow::Enable(enable);
    if (result) {
        wxCommandEvent e(EVT_ENABLE_CHANGED);
        e.SetEventObject(this);
        GetEventHandler()->ProcessEvent(e);
        text_ctrl->SetBackgroundColour(background_color.colorForStates(state_handler.states()));
        text_ctrl->SetForegroundColour(text_color.colorForStates(state_handler.states()));
    }
    return result;
}
References StateColor::colorForStates(), text_color, and text_ctrl.
Referenced by Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::PreferencesDialog::create_item_checkbox(), Slic3r::GUI::AMSMaterialsSetting::create_panel_normal(), and Slic3r::GUI::TextCtrl::enable().
GetTextCtrl() [1/2]
wxTextCtrl * TextInput::GetTextCtrl () inline
{ return text_ctrl; }
References text_ctrl.
Referenced by Slic3r::GUI::AuFile::AuFile(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::DesignerPanel::DesignerPanel(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::Search::SearchDialog::SearchDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::GridCellTextEditor::BeginEdit(), Slic3r::GUI::SelectMachineDialog::check_focus(), Slic3r::GUI::SendToPrinterDialog::check_focus(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::AMSMaterialsSetting::create_panel_kn(), Slic3r::GUI::AMSMaterialsSetting::create_panel_normal(), Slic3r::GUI::GridCellTextEditor::EndEdit(), Slic3r::GUI::AuFile::enter_rename_mode(), Slic3r::GUI::PlateSettingsDialog::get_plate_name(), Slic3r::GUI::AMSMaterialsSetting::input_max_finish(), Slic3r::GUI::AMSMaterialsSetting::input_min_finish(), Slic3r::GUI::SavePresetDialog::input_name_from_other(), Slic3r::GUI::DesignerPanel::msw_rescale(), Slic3r::GUI::ConnectPrinterDialog::on_button_confirm(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::ConnectPrinterDialog::on_dpi_changed(), Slic3r::GUI::EditDevNameDialog::on_edit_name(), Slic3r::GUI::Temp_Calibration_Dlg::on_filament_type_changed(), Slic3r::GUI::AuFile::on_input_enter(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::SelectMachineDialog::on_rename_click(), Slic3r::GUI::SendToPrinterDialog::on_rename_click(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::AMSMaterialsSetting::on_select_filament(), Slic3r::GUI::ExtrusionCalibration::on_select_filament(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::InputIpAddressDialog::on_text(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::PA_Calibration_Dlg::reset_params(), Slic3r::GUI::InputIpAddressDialog::set_machine_obj(), Slic3r::GUI::EditDevNameDialog::set_machine_obj(), Slic3r::GUI::PlateSettingsDialog::set_plate_name(), Slic3r::GUI::AMSMaterialsSetting::Show(), Slic3r::GUI::DesignerPanel::Show(), Slic3r::GUI::ExtrusionCalibration::Show(), Slic3r::GUI::ExtrusionCalibration::update(), Slic3r::GUI::ExtrusionCalibration::update_filament_info(), and Slic3r::GUI::DesignerPanel::update_info().
GetTextCtrl() [2/2]
wxTextCtrl const * TextInput::GetTextCtrl () const inline
{ return text_ctrl; }
References text_ctrl.
messureSize()
void TextInput::messureSize () private
{
    wxSize size = GetSize();
    wxClientDC dc(this);
    bool   align_right = GetWindowStyle() & wxRIGHT;
    if (align_right)
        dc.SetFont(GetFont());
    else
        dc.SetFont(Label::Body_12);
    labelSize = dc.GetTextExtent(wxWindow::GetLabel());
    wxSize textSize = text_ctrl->GetSize();
    int h = textSize.y + 8;
    if (size.y < h) {
        size.y = h;
    }
    wxSize minSize = size;
    minSize.x = GetMinWidth();
    SetMinSize(minSize);
    SetSize(size);
}
References Label::Body_12, labelSize, SetMinSize(), size, and text_ctrl.
Referenced by Create(), Rescale(), and SetLabel().
OnEdit()
virtual void TextInput::OnEdit () inline protected virtual
{}
Referenced by Create().
paintEvent()
void TextInput::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    render(dc);
}
References render().
render()
void TextInput::render (wxDC & dc) private
{
    StaticBox::render(dc);
    int states = state_handler.states();
    wxSize size = GetSize();
    bool   align_right = GetWindowStyle() & wxRIGHT;
    // start draw
    wxPoint pt = {5, 0};
    if (icon.bmp().IsOk()) {
        wxSize szIcon = icon.GetBmpSize();
        pt.y = (size.y - szIcon.y) / 2;
        dc.DrawBitmap(icon.bmp(), pt);
        pt.x += szIcon.x + 0;
    }
    auto text = wxWindow::GetLabel();
    if (!text.IsEmpty()) {
        wxSize textSize = text_ctrl->GetSize();
        if (align_right) {
            if (pt.x + labelSize.x > size.x)
                text = wxControl::Ellipsize(text, dc, wxELLIPSIZE_END, size.x - pt.x);
            pt.y = (size.y - labelSize.y) / 2;
        } else {
            pt.x += textSize.x;
            pt.y = (size.y + textSize.y) / 2 - labelSize.y;
        }
        dc.SetTextForeground(label_color.colorForStates(states));
        if(align_right)
            dc.SetFont(GetFont());
        else
            dc.SetFont(Label::Body_12);
        dc.DrawText(text, pt);
    }
}
References ScalableBitmap::bmp(), Label::Body_12, StateColor::colorForStates(), ScalableBitmap::GetBmpSize(), icon, label_color, labelSize, StaticBox::render(), size, and text_ctrl.
Referenced by paintEvent().
Rescale()
void TextInput::Rescale () virtual
{
    if (!this->icon.name().empty())
        this->icon.msw_rescale();
    messureSize();
    Refresh();
}
References icon, messureSize(), ScalableBitmap::msw_rescale(), and ScalableBitmap::name().
Referenced by ComboBox::Rescale(), and SetIcon().
SetCornerRadius()
void TextInput::SetCornerRadius (double radius)
{
    this->radius = radius;
    Refresh();
}
Referenced by Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog().
SetIcon()
void TextInput::SetIcon (const wxBitmap & icon)
{
    this->icon.bmp() = icon;
    Rescale();
}
References icon, and Rescale().
SetLabel()
void TextInput::SetLabel (const wxString & label)
{
    wxWindow::SetLabel(label);
    messureSize();
    Refresh();
}
References messureSize().
Referenced by Slic3r::GUI::AMSMaterialsSetting::Popup(), ComboBox::SetLabel(), and ComboBox::SetTextLabel().
SetLabelColor()
void TextInput::SetLabelColor (StateColor const & color)
{
    label_color = color;
    state_handler.update_binds();
}
References label_color.
Referenced by ComboBox::ComboBox(), and Slic3r::GUI::AMSMaterialsSetting::create_panel_normal().
SetMinSize()
void TextInput::SetMinSize (const wxSize & size) override virtual
{
    wxSize size2 = size;
    if (size2.y < 0) {
#ifdef __WXMAC__
        if (GetPeer()) // peer is not ready in Create on mac
#endif
        size2.y = GetSize().y;
    }
    wxWindow::SetMinSize(size2);
}
References size.
Referenced by Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), and messureSize().
SetTextColor()
void TextInput::SetTextColor (StateColor const & color)
{
    text_color= color;
    state_handler.update_binds();
}
References text_color.
Member Data Documentation
icon
ScalableBitmap TextInput::icon private
Referenced by TextInput(), Create(), DoSetSize(), render(), Rescale(), and SetIcon().
label_color
StateColor TextInput::label_color private
Referenced by Create(), render(), and SetLabelColor().
labelSize
wxSize TextInput::labelSize private
Referenced by DoSetSize(), messureSize(), and render().
text_color
StateColor TextInput::text_color private
Referenced by Create(), Enable(), and SetTextColor().
text_ctrl
wxTextCtrl* TextInput::text_ctrl private
Referenced by Create(), DoSetSize(), DoSetToolTipText(), Enable(), GetTextCtrl(), GetTextCtrl(), messureSize(), and render().
TextInputHeight
const int TextInput::TextInputHeight = 50 static private
TextInputWidth
const int TextInput::TextInputWidth = 200 static private
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/TextInput.hpp
src/slic3r/GUI/Widgets/TextInput.cpp