OrcaSlicer: Slic3r::GUI::AuxiliaryPanel Class Reference
Slic3r::GUI::AuxiliaryPanel Class Reference
#include <src/slic3r/GUI/Auxiliary.hpp>
Public Member Functions
AuxiliaryPanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~AuxiliaryPanel ()
void init_bitmap ()
void init_tabpanel ()
void Split (const std::string &src, const std::string &separator, std::vector< std::string > &dest)
void msw_rescale ()
void on_size (wxSizeEvent &event)
bool Show (bool show)
void init_auxiliary ()
void create_folder (wxString name=wxEmptyString)
std::string replaceSpace (std::string s, std::string ts, std::string ns)
void on_import_file (wxCommandEvent &event)
void Reload (wxString aux_path)
void update_all_panel ()
void update_all_cover ()
Public Attributes
std::map< std::string, std::vector< fs::path > > m_paths_list
wxString m_root_dir
Private Member Functions
wxWindow * create_side_tools ()
Private Attributes
Tabbook * m_tabpanel = {nullptr}
wxSizer * m_main_sizer = {nullptr}
AuFolderPanel * m_pictures_panel = {nullptr}
AuFolderPanel * m_bill_of_materials_panel = {nullptr}
AuFolderPanel * m_assembly_panel = {nullptr}
AuFolderPanel * m_others_panel = {nullptr}
DesignerPanel * m_designer_panel = {nullptr}
wxBitmap m_signal_strong_img
wxBitmap m_signal_middle_img
wxBitmap m_signal_weak_img
wxBitmap m_signal_no_img
wxBitmap m_printer_img
wxBitmap m_arrow_img
Detailed Description
Constructor & Destructor Documentation
AuxiliaryPanel()
Slic3r::GUI::AuxiliaryPanel::AuxiliaryPanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
                                                                                                                  : wxPanel(parent, id, pos, size, style)
{
    init_tabpanel();
    // init_auxiliary();
    m_main_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_main_sizer->Add(m_tabpanel, 1, wxEXPAND | wxLEFT, 0);
    SetSizerAndFit(m_main_sizer);
    Bind(wxEVT_SIZE, &AuxiliaryPanel::on_size, this);
    Bind(EVT_AUXILIARY_IMPORT, &AuxiliaryPanel::on_import_file, this);
    // cover -event
    Bind(EVT_AUXILIARY_UPDATE_COVER, [this](wxCommandEvent &e) { update_all_cover(); });
    // delete event
    Bind(EVT_AUXILIARY_UPDATE_DELETE, [this](wxCommandEvent &e) {
        auto info_str = e.GetString();
        wxArrayString     parems;
        wxStringTokenizer tokenizer(info_str, "|");
        while (tokenizer.HasMoreTokens()) {
            wxString token = tokenizer.GetNextToken();
            parems.Add(token);
        }
        auto model = parems[0];
        auto name  = parems[1];
        auto iter = m_paths_list.find(model.ToStdString());
        if (iter != m_paths_list.end()) {
            auto list = iter->second;
            for (auto i = 0; i < list.size(); i++) {
                if (list[i].wstring() == name) {
                    list.erase(std::begin(list) + i);
                    break;
                }
            }
            m_paths_list[model.ToStdString()] = list;
            update_all_panel();
            update_all_cover();
        }
    });
    // rename event
    Bind(EVT_AUXILIARY_UPDATE_RENAME, [this](wxCommandEvent &e) {
        auto info_str = e.GetString();
        wxArrayString     parems;
        wxStringTokenizer tokenizer(info_str, "|");
        while (tokenizer.HasMoreTokens()) {
            wxString token = tokenizer.GetNextToken();
            parems.Add(token);
        }
        auto model    = parems[0];
        auto old_name = parems[1];
        auto new_name = parems[2];
        auto iter = m_paths_list.find(model.ToStdString());
        if (iter != m_paths_list.end()) {
            auto list = iter->second;
            for (auto i = 0; i < list.size(); i++) {
                if (list[i].wstring() == old_name) {
                    list[i] = fs::path(new_name.ToStdWstring());
                    break;
                }
            }
            m_paths_list[model.ToStdString()] = list;
        }
    });
}
References init_tabpanel(), m_main_sizer, m_paths_list, m_tabpanel, on_import_file(), on_size(), update_all_cover(), and update_all_panel().
~AuxiliaryPanel()
Slic3r::GUI::AuxiliaryPanel::~AuxiliaryPanel ()
{}
Member Function Documentation
create_folder()
void Slic3r::GUI::AuxiliaryPanel::create_folder (wxString name = wxEmptyString)
{
    wxString folder_name = name;
    // Create folder in file system
    fs::path bfs_path((m_root_dir + "/" + folder_name).ToStdWstring());
    if (fs::exists(bfs_path)) {
        try {
            bool is_done = fs::remove_all(bfs_path);
        } catch (...) {
            BOOST_LOG_TRIVIAL(error) << "Failed  removing the auxiliary directory " << m_root_dir.c_str();
        }
    }
    fs::create_directory(bfs_path);
}
References error, and m_root_dir.
Referenced by init_auxiliary().
create_side_tools()
wxWindow * Slic3r::GUI::AuxiliaryPanel::create_side_tools () private
{
    wxBoxSizer *sizer = new wxBoxSizer(wxVERTICAL);
    auto        panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(0, FromDIP(50)));
    panel->SetBackgroundColour(wxColour(135, 206, 250));
    panel->SetSizer(sizer);
    sizer->Layout();
    panel->Fit();
    return panel;
}
init_auxiliary()
void Slic3r::GUI::AuxiliaryPanel::init_auxiliary ()
{
    Model &model = wxGetApp().plater()->model();
    m_root_dir   = encode_path(model.get_auxiliary_file_temp_path().c_str());
    if (wxDirExists(m_root_dir)) {
        fs::path path_to_del(m_root_dir.ToStdWstring());
        try {
            fs::remove_all(path_to_del);
        } catch (...) {
            BOOST_LOG_TRIVIAL(error) << "Failed  removing the auxiliary directory " << m_root_dir.c_str();
        }
    }
    fs::path top_dir_path(m_root_dir.ToStdWstring());
    fs::create_directory(top_dir_path);
    for (auto folder : s_default_folders) create_folder(folder);
}
References create_folder(), Slic3r::encode_path(), error, Slic3r::Model::get_auxiliary_file_temp_path(), m_root_dir, and s_default_folders.
init_bitmap()
void Slic3r::GUI::AuxiliaryPanel::init_bitmap ()
{
    /*m_signal_strong_img = create_scaled_bitmap("monitor_signal_strong", nullptr, 24);
    m_signal_middle_img = create_scaled_bitmap("monitor_signal_middle", nullptr, 24);
    m_signal_weak_img   = create_scaled_bitmap("monitor_signal_weak", nullptr, 24);
    m_signal_no_img     = create_scaled_bitmap("monitor_signal_no", nullptr, 24);
    m_printer_img       = create_scaled_bitmap("monitor_printer", nullptr, 26);
    m_arrow_img         = create_scaled_bitmap("monitor_arrow", nullptr, 14);*/
}
init_tabpanel()
void Slic3r::GUI::AuxiliaryPanel::init_tabpanel ()
{
    auto        m_side_tools     = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(FromDIP(220), FromDIP(18)));
    wxBoxSizer *sizer_side_tools = new wxBoxSizer(wxVERTICAL);
    sizer_side_tools->Add(m_side_tools, 1, wxEXPAND, 0);
    m_tabpanel = new Tabbook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, sizer_side_tools, wxNB_LEFT | wxTAB_TRAVERSAL | wxNB_NOPAGETHEME);
    m_tabpanel->SetBackgroundColour(wxColour("#FEFFFF"));
    m_tabpanel->Bind(wxEVT_BOOKCTRL_PAGE_CHANGED, [this](wxBookCtrlEvent &e) { ; });
    m_designer_panel = new DesignerPanel(m_tabpanel, AuxiliaryFolderType::DESIGNER);
    m_pictures_panel          = new AuFolderPanel(m_tabpanel, AuxiliaryFolderType::MODEL_PICTURE);
    m_bill_of_materials_panel = new AuFolderPanel(m_tabpanel, AuxiliaryFolderType::BILL_OF_MATERIALS);
    m_assembly_panel          = new AuFolderPanel(m_tabpanel, AuxiliaryFolderType::ASSEMBLY_GUIDE);
    m_others_panel            = new AuFolderPanel(m_tabpanel, AuxiliaryFolderType::OTHERS);
    m_tabpanel->AddPage(m_designer_panel, _L("Basic Info"), "", true);
    m_tabpanel->AddPage(m_pictures_panel, _L("Pictures"), "", false);
    m_tabpanel->AddPage(m_bill_of_materials_panel, _L("Bill of Materials"), "", false);
    m_tabpanel->AddPage(m_assembly_panel, _L("Assembly Guide"), "", false);
    m_tabpanel->AddPage(m_others_panel, _L("Others"), "", false);
}
References _L, Tabbook::AddPage(), ASSEMBLY_GUIDE, BILL_OF_MATERIALS, DESIGNER, m_assembly_panel, m_bill_of_materials_panel, m_designer_panel, m_others_panel, m_pictures_panel, m_tabpanel, MODEL_PICTURE, and OTHERS.
Referenced by AuxiliaryPanel().
msw_rescale()
void Slic3r::GUI::AuxiliaryPanel::msw_rescale ()
{
    m_pictures_panel->msw_rescale();
    m_bill_of_materials_panel->msw_rescale();
    m_assembly_panel->msw_rescale();
    m_others_panel->msw_rescale();
    m_designer_panel->msw_rescale();
}
References m_assembly_panel, m_bill_of_materials_panel, m_designer_panel, m_others_panel, m_pictures_panel, Slic3r::GUI::AuFolderPanel::msw_rescale(), and Slic3r::GUI::DesignerPanel::msw_rescale().
on_import_file()
void Slic3r::GUI::AuxiliaryPanel::on_import_file (wxCommandEvent & event)
{
    auto file_model = event.GetString();
    wxString     src_path;
    wxString     dst_path;
     wxString wildcard = wxFileSelectorDefaultWildcardStr;
    if (file_model == s_default_folders[MODEL_PICTURE]) {
        //wildcard = wxT("JPEG files (*.jpeg)|*.jpeg|BMP files (*.bmp)|*.bmp|GIF files (*.gif)|*.gif|PNG files (*.png)|*.png|JPG files (*.jpg)|*.jpg");
        wildcard = wxT("files (*.png;*.jpg;*.jpeg;*.bmp)|*.png;*.jpg;*.jpeg;*.bmp");
    }
    if (file_model == s_default_folders[OTHERS]) {  wildcard = wxT("TXT files (*.txt)|*.txt"); }
    if (file_model == s_default_folders[BILL_OF_MATERIALS]){ wildcard = wxT("EXCEL files (*.xls)|*.xls|EXCEL files (*.xlsx)|*.xlsx|PDF files (*.pdf)|*.pdf"); }
    if (file_model == s_default_folders[ASSEMBLY_GUIDE]) { wildcard = wxT("PDF files (*.pdf)|*.pdf"); }
    wxFileDialog dialog(this, _L("Choose files"), wxEmptyString, wxEmptyString, wildcard, wxFD_OPEN | wxFD_FILE_MUST_EXIST | wxFD_MULTIPLE);
    if (dialog.ShowModal() == wxID_OK) {
        wxArrayString file_paths;
        dialog.GetPaths(file_paths);
        for (wxString file_path : file_paths) {
            // Copy imported file to project temp directory
            fs::path src_bfs_path(file_path.ToStdWstring());
            wxString dir_path = m_root_dir;
            dir_path += "/" + file_model;
            auto is_exist = false;
            auto iter = m_paths_list.find(file_model.ToStdString());
            if (iter != m_paths_list.end()) {
                std::vector<fs::path> list = iter->second;
                for (auto i = 0; i < list.size(); i++) {
                    if (src_bfs_path.filename() == list[i].filename()) {
                        is_exist = true;
                        break;
                    }
                }
            }
            if (!is_exist) {
                dir_path += "/" + src_bfs_path.filename().generic_wstring();
            } else {
                time_t t1 = time(0);
                char   ch1[64];
                strftime(ch1, sizeof(ch1), "%T", localtime(&t1));
                std::string time_text = ch1;
                wxString name = src_bfs_path.filename().generic_wstring();
                auto before_name = replaceSpace(name.ToStdString(), src_bfs_path.extension().string(), "");
                time_text = replaceSpace(time_text, ":", "_");
                dir_path += "/" + before_name + "_" + time_text + src_bfs_path.extension().wstring();
            }
            boost::system::error_code ec;
            if (!fs::copy_file(src_bfs_path, fs::path(dir_path.ToStdWstring()), fs::copy_option::overwrite_if_exists, ec)) continue;
            Slic3r::put_other_changes();
            // add in file list
            iter = m_paths_list.find(file_model.ToStdString());
            auto file_fs_path = fs::path(dir_path.ToStdWstring());
            if (iter != m_paths_list.end()) {
                m_paths_list[file_model.ToStdString()].push_back(file_fs_path);
            } else {
                m_paths_list[file_model.ToStdString()] = std::vector<fs::path>{file_fs_path};
            }
        }
        update_all_panel();
        update_all_cover();
    }
}
References _L, ASSEMBLY_GUIDE, BILL_OF_MATERIALS, m_paths_list, m_root_dir, MODEL_PICTURE, OTHERS, Slic3r::put_other_changes(), replaceSpace(), s_default_folders, update_all_cover(), and update_all_panel().
Referenced by AuxiliaryPanel().
on_size()
void Slic3r::GUI::AuxiliaryPanel::on_size (wxSizeEvent & event)
{
    if (!wxGetApp().mainframe) return;
    Layout();
    Refresh();
}
Referenced by AuxiliaryPanel().
Reload()
void Slic3r::GUI::AuxiliaryPanel::Reload (wxString aux_path)
{
    fs::path new_aux_path(aux_path.ToStdWstring());
    try {
        fs::remove_all(fs::path(m_root_dir.ToStdWstring()));
    } catch (...) {
        BOOST_LOG_TRIVIAL(error) << "Failed  removing the auxiliary directory " << m_root_dir.c_str();
    }
    m_root_dir = aux_path;
    m_paths_list.clear();
    // Check new path. If not exist, create a new one.
    if (!fs::exists(new_aux_path)) {
        fs::create_directory(new_aux_path);
        // Create default folders if they are not loaded
        for (auto folder : s_default_folders) {
            wxString folder_path = aux_path + "/" + folder;
            if (fs::exists(folder_path.ToStdWstring())) continue;
            fs::create_directory(folder_path.ToStdWstring());
        }
        update_all_panel();
        m_designer_panel->update_info();
        return;
    }
    // Load from new path
    std::vector<fs::path>  dir_cache;
    fs::directory_iterator iter_end;
    for (fs::directory_iterator iter(new_aux_path); iter != iter_end; iter++) {
        wxString path = iter->path().generic_wstring();
        dir_cache.push_back(iter->path());
    }
    for (auto dir : dir_cache) {
        for (fs::directory_iterator iter(dir); iter != iter_end; iter++) {
            if (fs::is_directory(iter->path())) continue;
            wxString file_path     = iter->path().generic_wstring();
            //auto     file_path_str = encode_path(file_path.c_str());
            for (auto folder : s_default_folders) {
                auto idx = file_path.find(folder.ToStdString());
                if (idx != std::string::npos) {
                    auto iter = m_paths_list.find(folder.ToStdString());
                    auto     file_path_str = fs::path(file_path.ToStdWstring());
                    if (iter != m_paths_list.end()) {
                        m_paths_list[folder.ToStdString()].push_back(file_path_str);
                        break;
                    } else {
                        m_paths_list[folder.ToStdString()] = std::vector<fs::path>{file_path_str};
                        break;
                    }
                }
            }
        }
    }
    // Create default folders if they are not loaded
    wxDataViewItemArray default_items;
    for (auto folder : s_default_folders) {
        wxString folder_path = aux_path + "/" + folder;
        if (fs::exists(folder_path.ToStdWstring())) continue;
        fs::create_directory(folder_path.ToStdWstring());
    }
    update_all_panel();
    update_all_cover();
    m_designer_panel->update_info();
}
References error, m_designer_panel, m_paths_list, m_root_dir, s_default_folders, update_all_cover(), update_all_panel(), and Slic3r::GUI::DesignerPanel::update_info().
replaceSpace()
std::string Slic3r::GUI::AuxiliaryPanel::replaceSpace (std::string s, std::string ts, std::string ns)
{
    int    index   = -1;
    while ((index = s.find(ts.c_str())) >= 0) { s = s.replace(index, ts.length(), ns.c_str()); }
    return s;
}
References ns.
Referenced by on_import_file().
Show()
bool Slic3r::GUI::AuxiliaryPanel::Show (bool show)
{ return wxPanel::Show(show); }
Split()
void Slic3r::GUI::AuxiliaryPanel::Split (const std::string & src, const std::string & separator, std::vector< std::string > & dest)
{
    std::string            str = src;
    std::string            substring;
    std::string::size_type start = 0, index;
    dest.clear();
    index = str.find_first_of(separator, start);
    do {
        if (index != string::npos) {
            substring = str.substr(start, index - start);
            dest.push_back(substring);
            start = index + separator.size();
            index = str.find(separator, start);
            if (start == string::npos) break;
        }
    } while (index != string::npos);
    // the last part
    substring = str.substr(start);
    dest.push_back(substring);
}
References start.
update_all_cover()
void Slic3r::GUI::AuxiliaryPanel::update_all_cover ()
{
    std::map<std::string, std::vector<fs::path>>::iterator mit;
    for (mit = m_paths_list.begin(); mit != m_paths_list.end(); mit++) {
        if (mit->first == "Model Pictures") { m_pictures_panel->update_cover(); }
    }
}
References m_paths_list, m_pictures_panel, and Slic3r::GUI::AuFolderPanel::update_cover().
Referenced by AuxiliaryPanel(), on_import_file(), and Reload().
update_all_panel()
void Slic3r::GUI::AuxiliaryPanel::update_all_panel ()
{
    std::map<std::string, std::vector<fs::path>>::iterator mit;
    Freeze();
    m_pictures_panel->clear();
    m_bill_of_materials_panel->clear();
    m_assembly_panel->clear();
    m_others_panel->clear();
    for (mit = m_paths_list.begin(); mit != m_paths_list.end(); mit++) {
        if (mit->first == "Model Pictures") { m_pictures_panel->update(mit->second); }
        if (mit->first == "Bill of Materials") { m_bill_of_materials_panel->update(mit->second); }
        if (mit->first == "Assembly Guide") { m_assembly_panel->update(mit->second); }
        if (mit->first == "Others") { m_others_panel->update(mit->second); }
    }
    Thaw();
}
References Slic3r::GUI::AuFolderPanel::clear(), m_assembly_panel, m_bill_of_materials_panel, m_others_panel, m_paths_list, m_pictures_panel, and Slic3r::GUI::AuFolderPanel::update().
Referenced by AuxiliaryPanel(), on_import_file(), and Reload().
Member Data Documentation
m_arrow_img
wxBitmap Slic3r::GUI::AuxiliaryPanel::m_arrow_img private
m_assembly_panel
AuFolderPanel* Slic3r::GUI::AuxiliaryPanel::m_assembly_panel = {nullptr} private
Referenced by init_tabpanel(), msw_rescale(), and update_all_panel().
m_bill_of_materials_panel
AuFolderPanel* Slic3r::GUI::AuxiliaryPanel::m_bill_of_materials_panel = {nullptr} private
Referenced by init_tabpanel(), msw_rescale(), and update_all_panel().
m_designer_panel
DesignerPanel* Slic3r::GUI::AuxiliaryPanel::m_designer_panel = {nullptr} private
Referenced by init_tabpanel(), msw_rescale(), and Reload().
m_main_sizer
wxSizer* Slic3r::GUI::AuxiliaryPanel::m_main_sizer = {nullptr} private
Referenced by AuxiliaryPanel().
m_others_panel
AuFolderPanel* Slic3r::GUI::AuxiliaryPanel::m_others_panel = {nullptr} private
Referenced by init_tabpanel(), msw_rescale(), and update_all_panel().
m_paths_list
std::map<std::string, std::vector<fs::path> > Slic3r::GUI::AuxiliaryPanel::m_paths_list
Referenced by AuxiliaryPanel(), on_import_file(), Reload(), update_all_cover(), and update_all_panel().
m_pictures_panel
AuFolderPanel* Slic3r::GUI::AuxiliaryPanel::m_pictures_panel = {nullptr} private
Referenced by init_tabpanel(), msw_rescale(), update_all_cover(), and update_all_panel().
m_printer_img
wxBitmap Slic3r::GUI::AuxiliaryPanel::m_printer_img private
m_root_dir
wxString Slic3r::GUI::AuxiliaryPanel::m_root_dir
Referenced by create_folder(), init_auxiliary(), on_import_file(), and Reload().
m_signal_middle_img
wxBitmap Slic3r::GUI::AuxiliaryPanel::m_signal_middle_img private
m_signal_no_img
wxBitmap Slic3r::GUI::AuxiliaryPanel::m_signal_no_img private
m_signal_strong_img
wxBitmap Slic3r::GUI::AuxiliaryPanel::m_signal_strong_img private
m_signal_weak_img
wxBitmap Slic3r::GUI::AuxiliaryPanel::m_signal_weak_img private
m_tabpanel
Tabbook* Slic3r::GUI::AuxiliaryPanel::m_tabpanel = {nullptr} private
Referenced by AuxiliaryPanel(), and init_tabpanel().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Auxiliary.hpp
src/slic3r/GUI/Auxiliary.cpp