OrcaSlicer: SwitchButton Class Reference
SwitchButton Class Reference
#include <src/slic3r/GUI/Widgets/SwitchButton.hpp>
Public Member Functions
SwitchButton (wxWindow *parent=NULL, wxWindowID id=wxID_ANY)
void SetLabels (wxString const &lbl_on, wxString const &lbl_off)
void SetTextColor (StateColor const &color)
void SetTextColor2 (StateColor const &color)
void SetTrackColor (StateColor const &color)
void SetThumbColor (StateColor const &color)
void SetValue (bool value) override
void Rescale ()
Private Member Functions
void update ()
Private Attributes
ScalableBitmap m_on
ScalableBitmap m_off
wxString labels [2]
StateColor text_color
StateColor text_color2
StateColor track_color
StateColor thumb_color
Detailed Description
Constructor & Destructor Documentation
SwitchButton()
SwitchButton::SwitchButton (wxWindow * parent = NULL, wxWindowID id = wxID_ANY)
  : wxBitmapToggleButton(parent, id, wxNullBitmap, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE | wxBU_EXACTFIT)
  , m_on(this, "toggle_on", 16)
  , m_off(this, "toggle_off", 16)
    , text_color(std::pair{0xfffffe, (int) StateColor::Checked}, std::pair{0x6B6B6B, (int) StateColor::Normal})
  , track_color(0xD9D9D9)
    , thumb_color(std::pair{0x009688, (int) StateColor::Checked}, std::pair{0xD9D9D9, (int) StateColor::Normal})
{
  SetBackgroundColour(StaticBox::GetParentBackgroundColor(parent));
  Bind(wxEVT_TOGGLEBUTTON, [this](auto& e) { update(); e.Skip(); });
  SetFont(Label::Body_12);
  Rescale();
}
References Label::Body_12, StaticBox::GetParentBackgroundColor(), Rescale(), and update().
Member Function Documentation
Rescale()
void SwitchButton::Rescale ()
{
  if (labels[0].IsEmpty()) {
    m_on.msw_rescale();
    m_off.msw_rescale();
  }
  else {
        SetBackgroundColour(StaticBox::GetParentBackgroundColor(GetParent()));
#ifdef __WXOSX__
        auto scale = Slic3r::GUI::mac_max_scaling_factor();
        int BS = (int) scale;
#else
        constexpr int BS = 1;
#endif
    wxSize thumbSize;
    wxSize trackSize;
    wxClientDC dc(this);
#ifdef __WXOSX__
        dc.SetFont(dc.GetFont().Scaled(scale));
#endif
        wxSize textSize[2];
    {
      textSize[0] = dc.GetTextExtent(labels[0]);
      textSize[1] = dc.GetTextExtent(labels[1]);
    }
    {
      thumbSize = textSize[0];
      auto size = textSize[1];
      if (size.x > thumbSize.x) thumbSize.x = size.x;
      else size.x = thumbSize.x;
      thumbSize.x += BS * 12;
      thumbSize.y += BS * 6;
      trackSize.x = thumbSize.x + size.x + BS * 10;
      trackSize.y = thumbSize.y + BS * 2;
            auto maxWidth = GetMaxWidth();
#ifdef __WXOSX__
            maxWidth *= scale;
#endif
      if (trackSize.x > maxWidth) {
                thumbSize.x -= (trackSize.x - maxWidth) / 2;
                trackSize.x = maxWidth;
      }
    }
    for (int i = 0; i < 2; ++i) {
      wxMemoryDC memdc(&dc);
#ifdef __WXMSW__
      wxBitmap bmp(trackSize.x, trackSize.y);
      memdc.SelectObject(bmp);
      memdc.SetBackground(wxBrush(GetBackgroundColour()));
      memdc.Clear();
#else
            wxImage image(trackSize);
            image.InitAlpha();
            memset(image.GetAlpha(), 0, trackSize.GetWidth() * trackSize.GetHeight());
            wxBitmap bmp(std::move(image));
            memdc.SelectObject(bmp);
#endif
            memdc.SetFont(dc.GetFont());
      auto state = i == 0 ? StateColor::Enabled : (StateColor::Checked | StateColor::Enabled);
            {
#ifdef __WXMSW__
        wxGCDC dc2(memdc);
#else
                wxDC &dc2(memdc);
#endif
        dc2.SetBrush(wxBrush(track_color.colorForStates(state)));
        dc2.SetPen(wxPen(track_color.colorForStates(state)));
                dc2.DrawRoundedRectangle(wxRect({0, 0}, trackSize), trackSize.y / 2);
        dc2.SetBrush(wxBrush(thumb_color.colorForStates(StateColor::Checked | StateColor::Enabled)));
        dc2.SetPen(wxPen(thumb_color.colorForStates(StateColor::Checked | StateColor::Enabled)));
        dc2.DrawRoundedRectangle(wxRect({ i == 0 ? BS : (trackSize.x - thumbSize.x - BS), BS}, thumbSize), thumbSize.y / 2);
      }
            memdc.SetTextForeground(text_color.colorForStates(state ^ StateColor::Checked));
            memdc.DrawText(labels[0], {BS + (thumbSize.x - textSize[0].x) / 2, BS + (thumbSize.y - textSize[0].y) / 2});
            memdc.SetTextForeground(text_color2.count() == 0 ? text_color.colorForStates(state) : text_color2.colorForStates(state));
            memdc.DrawText(labels[1], {trackSize.x - thumbSize.x - BS + (thumbSize.x - textSize[1].x) / 2, BS + (thumbSize.y - textSize[1].y) / 2});
      memdc.SelectObject(wxNullBitmap);
#ifdef __WXOSX__
            bmp = wxBitmap(bmp.ConvertToImage(), -1, scale);
#endif
      (i == 0 ? m_off : m_on).bmp() = bmp;
    }
  }
  SetSize(m_on.GetBmpSize());
  update();
}
References StateColor::Checked, StateColor::colorForStates(), StateColor::count(), StateColor::Enabled, ScalableBitmap::GetBmpSize(), StaticBox::GetParentBackgroundColor(), int, labels, m_off, m_on, Slic3r::GUI::mac_max_scaling_factor(), memset, ScalableBitmap::msw_rescale(), scale(), size, text_color, text_color2, thumb_color, track_color, and update().
Referenced by SwitchButton(), Slic3r::GUI::StatusPanel::msw_rescale(), Slic3r::GUI::ParamsPanel::notify_object_config_changed(), and SetLabels().
SetLabels()
void SwitchButton::SetLabels (wxString const & lbl_on, wxString const & lbl_off)
{
  labels[0] = lbl_on;
  labels[1] = lbl_off;
  Rescale();
}
References labels, and Rescale().
Referenced by Slic3r::GUI::ParamsPanel::ParamsPanel().
SetTextColor()
void SwitchButton::SetTextColor (StateColor const & color)
{
  text_color = color;
}
References text_color.
SetTextColor2()
void SwitchButton::SetTextColor2 (StateColor const & color)
{
  text_color2 = color;
}
References text_color2.
Referenced by Slic3r::GUI::ParamsPanel::notify_object_config_changed().
SetThumbColor()
void SwitchButton::SetThumbColor (StateColor const & color)
{
  thumb_color = color;
}
References thumb_color.
SetTrackColor()
void SwitchButton::SetTrackColor (StateColor const & color)
{
  track_color = color;
}
References track_color.
SetValue()
void SwitchButton::SetValue (bool value) override
{
  if (value != GetValue())
    wxBitmapToggleButton::SetValue(value);
  update();
}
References update().
Referenced by Slic3r::GUI::CameraPopup::CameraPopup(), Slic3r::GUI::CameraPopup::on_switch_recording(), Slic3r::GUI::ParamsPanel::switch_to_global(), Slic3r::GUI::ParamsPanel::switch_to_object(), Slic3r::GUI::ParamsPanel::switch_to_object_if_has_object_configs(), Slic3r::GUI::CameraPopup::sync_vcamera_state(), Slic3r::GUI::CameraPopup::update(), and Slic3r::GUI::ParamsPanel::update_mode().
update()
void SwitchButton::update () private
{
  SetBitmap((GetValue() ? m_on : m_off).bmp());
}
References m_off, and m_on.
Referenced by SwitchButton(), Rescale(), and SetValue().
Member Data Documentation
labels
wxString SwitchButton::labels[2] private
Referenced by Rescale(), and SetLabels().
m_off
ScalableBitmap SwitchButton::m_off private
Referenced by Rescale(), and update().
m_on
ScalableBitmap SwitchButton::m_on private
Referenced by Rescale(), and update().
text_color
StateColor SwitchButton::text_color private
Referenced by Rescale(), and SetTextColor().
text_color2
StateColor SwitchButton::text_color2 private
Referenced by Rescale(), and SetTextColor2().
thumb_color
StateColor SwitchButton::thumb_color private
Referenced by Rescale(), and SetThumbColor().
track_color
StateColor SwitchButton::track_color private
Referenced by Rescale(), and SetTrackColor().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/SwitchButton.hpp
src/slic3r/GUI/Widgets/SwitchButton.cpp