OrcaSlicer: PopupWindow Class Reference
PopupWindow Class Reference
#include <src/slic3r/GUI/Widgets/PopupWindow.hpp>
Public Member Functions
PopupWindow ()
~PopupWindow ()
PopupWindow (wxWindow *parent, int style=wxBORDER_NONE)
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Detailed Description
Constructor & Destructor Documentation
PopupWindow() [1/2]
PopupWindow::PopupWindow () inline
{}
~PopupWindow()
PopupWindow::~PopupWindow ()
{
#ifdef __WXGTK__
    GetTopParent(this)->Unbind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
}
References GetTopParent().
PopupWindow() [2/2]
PopupWindow::PopupWindow (wxWindow * parent, int style = wxBORDER_NONE) inline
        { Create(parent, style); }
References Create(), and style.
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE)
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow(), and DropDown::Create().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/PopupWindow.hpp
src/slic3r/GUI/Widgets/PopupWindow.cpp