OrcaSlicer: Slic3r::Http Class Reference
Slic3r::Http Class Reference
Represetns a Http request.
#include <src/slic3r/Utils/Http.hpp>
Classes
struct priv
struct Progress
Public Types
typedef std::shared_ptr< Http > Ptr
typedef std::function< void(std::string, unsigned)> CompleteFn
typedef std::function< void(std::string, std::string, unsigned)> ErrorFn
typedef std::function< void(Progress, bool &)> ProgressFn
typedef std::function< void(std::string)> IPResolveFn
typedef std::function< void(std::string headers)> HeaderCallbackFn
Public Member Functions
Http (Http &&other)
~Http ()
Http (const Http &)=delete
Http & operator= (const Http &)=delete
Http & operator= (Http &&)=delete
Http & timeout_connect (long timeout)
Http & timeout_max (long timeout)
Http & size_limit (size_t sizeLimit)
Http & header (std::string name, const std::string &value)
Http & remove_header (std::string name)
Http & auth_digest (const std::string &user, const std::string &password)
Http & auth_basic (const std::string &user, const std::string &password)
Http & ca_file (const std::string &filename)
Http & form_add (const std::string &name, const std::string &contents)
Http & form_add_file (const std::string &name, const boost::filesystem::path &path)
Http & mime_form_add_text (std::string &name, std::string &value)
Http & mime_form_add_file (std::string &name, const char *path)
Http & form_add_file (const std::wstring &name, const boost::filesystem::path &path)
Http & form_add_file (const std::string &name, const boost::filesystem::path &path, const std::string &filename)
Http & set_post_body (const boost::filesystem::path &path)
Http & set_post_body (const std::string &body)
Http & set_put_body (const boost::filesystem::path &path)
Http & set_del_body (const std::string &body)
Http & on_complete (CompleteFn fn)
Http & on_error (ErrorFn fn)
Http & on_progress (ProgressFn fn)
Http & on_ip_resolve (IPResolveFn fn)
Http & on_header_callback (HeaderCallbackFn fn)
Ptr perform ()
void perform_sync ()
void cancel ()
Static Public Member Functions
static Http get (std::string url)
static Http post (std::string url)
static Http put (std::string url)
static Http del (std::string url)
static Http put2 (std::string url)
static Http patch (std::string url)
static void set_extra_headers (std::map< std::string, std::string > headers)
static bool ca_file_supported ()
static std::string tls_global_init ()
static std::string tls_system_cert_store ()
static std::string url_encode (const std::string &str)
static std::string url_decode (const std::string &str)
static std::string get_filename_from_url (const std::string &url)
Private Member Functions
Http (const std::string &url)
Private Attributes
std::unique_ptr< priv > p
Detailed Description
Represetns a Http request.
Member Typedef Documentation
CompleteFn
typedef std::function<void(std::string , unsigned)> Slic3r::Http::CompleteFn
ErrorFn
typedef std::function<void(std::string , std::string , unsigned)> Slic3r::Http::ErrorFn
HeaderCallbackFn
typedef std::function<void(std::string headers)> Slic3r::Http::HeaderCallbackFn
IPResolveFn
typedef std::function<void(std::string)> Slic3r::Http::IPResolveFn
ProgressFn
typedef std::function<void(Progress, bool&)> Slic3r::Http::ProgressFn
Ptr
typedef std::shared_ptr<Http> Slic3r::Http::Ptr
Constructor & Destructor Documentation
Http() [1/3]
Slic3r::Http::Http (Http && other)
: p(std::move(other.p)) {}
~Http()
Slic3r::Http::~Http ()
{
    assert(! p || ! p->putFile);
  if (p && p->io_thread.joinable()) {
    p->io_thread.detach();
  }
}
References p.
Http() [2/3]
Slic3r::Http::Http (const Http &) delete
Http() [3/3]
Slic3r::Http::Http (const std::string & url) private
                               : p(new priv(url)) {
  for (auto it = extra_headers.begin(); it != extra_headers.end(); it++)
    this->header(it->first, it->second);
}
References Slic3r::extra_headers, and header().
Member Function Documentation
auth_basic()
Http & Slic3r::Http::auth_basic (const std::string & user, const std::string & password)
{
    curl_easy_setopt(p->curl, CURLOPT_USERNAME, user.c_str());
    curl_easy_setopt(p->curl, CURLOPT_PASSWORD, password.c_str());
    curl_easy_setopt(p->curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);
    return *this;
}
References p.
auth_digest()
Http & Slic3r::Http::auth_digest (const std::string & user, const std::string & password)
{
  curl_easy_setopt(p->curl, CURLOPT_USERNAME, user.c_str());
  curl_easy_setopt(p->curl, CURLOPT_PASSWORD, password.c_str());
  curl_easy_setopt(p->curl, CURLOPT_HTTPAUTH, CURLAUTH_DIGEST);
  return *this;
}
References p.
Referenced by Slic3r::SL1Host::set_auth(), and Slic3r::PrusaLink::set_auth().
ca_file()
Http & Slic3r::Http::ca_file (const std::string & filename)
{
  if (p && priv::ca_file_supported(p->curl)) {
    ::curl_easy_setopt(p->curl, CURLOPT_CAINFO, name.c_str());
  }
  return *this;
}
References Slic3r::Http::priv::ca_file_supported(), and p.
Referenced by Slic3r::AstroBox::set_auth(), Slic3r::OctoPrint::set_auth(), Slic3r::Repetier::set_auth(), Slic3r::SL1Host::set_auth(), and Slic3r::PrusaLink::set_auth().
ca_file_supported()
bool Slic3r::Http::ca_file_supported () static
{
  ::CURL *curl = ::curl_easy_init();
  bool res = priv::ca_file_supported(curl);
  if (curl != nullptr) { ::curl_easy_cleanup(curl); }
    return res;
}
References Slic3r::Http::priv::ca_file_supported().
Referenced by Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
cancel()
void Slic3r::Http::cancel ()
{
  if (p) { p->cancel = true; }
}
References p.
Referenced by Slic3r::Http::priv::http_perform().
del()
Http Slic3r::Http::del (std::string url) static
{
  Http http{ std::move(url) };
  curl_easy_setopt(http.p->curl, CURLOPT_CUSTOMREQUEST, "DELETE");
  return http;
}
form_add()
Http & Slic3r::Http::form_add (const std::string & name, const std::string & contents)
{
  if (p) {
    ::curl_formadd(&p->form, &p->form_end,
      CURLFORM_COPYNAME, name.c_str(),
      CURLFORM_COPYCONTENTS, contents.c_str(),
      CURLFORM_END
    );
  }
  return *this;
}
References p.
form_add_file() [1/3]
Http & Slic3r::Http::form_add_file (const std::string & name, const boost::filesystem::path & path)
form_add_file() [2/3]
Http & Slic3r::Http::form_add_file (const std::string & name, const boost::filesystem::path & path, const std::string & filename)
form_add_file() [3/3]
Http & Slic3r::Http::form_add_file (const std::wstring & name, const boost::filesystem::path & path)
get()
Http Slic3r::Http::get (std::string url) static
{
    return Http{std::move(url)};
}
Referenced by Slic3r::GUI::GUI_App::check_new_version(), Slic3r::GUI::GUI_App::check_new_version_sf(), Slic3r::GUI::GUI_App::check_privacy_version(), Slic3r::Duet::connect(), Slic3r::Duet::disconnect(), Slic3r::GUI::HMSQuery::download_hms_info(), Slic3r::GUI::GUI_App::download_plugin(), Slic3r::GUI::get_error_message(), Slic3r::PresetUpdater::priv::get_file(), Slic3r::Repetier::get_groups(), Slic3r::GUI::get_hms_info_version(), Slic3r::Repetier::get_printers(), Slic3r::GUI::Plater::import_model_id(), Slic3r::Duet::start_print(), Slic3r::GUI::NetworkTestDialog::start_test_bambulab(), Slic3r::GUI::NetworkTestDialog::start_test_bing(), Slic3r::GUI::NetworkTestDialog::start_test_oss(), Slic3r::GUI::NetworkTestDialog::start_test_oss_download(), Slic3r::GUI::NetworkTestDialog::start_test_oss_upgrade(), Slic3r::PresetUpdater::priv::sync_config(), Slic3r::PresetUpdater::priv::sync_resources(), Slic3r::PresetUpdater::priv::sync_version(), Slic3r::AstroBox::test(), Slic3r::FlashAir::test(), Slic3r::OctoPrint::test(), Slic3r::Repetier::test(), and Slic3r::FlashAir::upload().
get_filename_from_url()
std::string Slic3r::Http::get_filename_from_url (const std::string & url) static
{
    int end_pos = url.find_first_of('?');
  if (end_pos <= 0) return "";
  std::string path_url = url.substr(0, end_pos);
  int start_pos = path_url.find_last_of("/");
  if (start_pos < 0) return "";
  return path_url.substr(start_pos + 1, path_url.length() - start_pos - 1);
}
header()
Http & Slic3r::Http::header (std::string name, const std::string & value)
{
  if (!p) { return * this; }
  if (name.size() > 0) {
    name.append(": ").append(value);
  } else {
    name.push_back(':');
  }
  p->headerlist = curl_slist_append(p->headerlist, name.c_str());
  return *this;
}
References p.
Referenced by Http(), Slic3r::GUI::GUI_App::check_new_version(), Slic3r::GUI::GUI_App::check_privacy_version(), Slic3r::GUI::get_error_message(), Slic3r::GUI::SendSystemInfoDialog::send_info(), Slic3r::AstroBox::set_auth(), Slic3r::OctoPrint::set_auth(), Slic3r::Repetier::set_auth(), Slic3r::SL1Host::set_auth(), Slic3r::PrusaLink::set_auth(), and Slic3r::GUI::NetworkTestDialog::start_test_bambulab().
mime_form_add_file()
Http & Slic3r::Http::mime_form_add_file (std::string & name, const char * path)
{
  if (p) { p->mime_form_add_file(name.c_str(), path); }
  return *this;
}
References p.
mime_form_add_text()
Http & Slic3r::Http::mime_form_add_text (std::string & name, std::string & value)
{
  if (p) { p->mime_form_add_text(name.c_str(), value.c_str()); }
  return *this;
}
References p.
on_complete()
Http & Slic3r::Http::on_complete (CompleteFn fn)
{
  if (p) { p->completefn = std::move(fn); }
  return *this;
}
References p.
Referenced by Slic3r::GUI::GUI_App::check_new_version(), Slic3r::GUI::GUI_App::check_new_version_sf(), Slic3r::GUI::GUI_App::check_privacy_version(), Slic3r::GUI::HMSQuery::download_hms_info(), Slic3r::GUI::GUI_App::download_plugin(), Slic3r::GUI::get_error_message(), Slic3r::GUI::get_hms_info_version(), Slic3r::GUI::SendSystemInfoDialog::send_info(), Slic3r::GUI::NetworkTestDialog::start_test_bambulab(), Slic3r::GUI::NetworkTestDialog::start_test_bing(), Slic3r::GUI::NetworkTestDialog::start_test_oss(), Slic3r::GUI::NetworkTestDialog::start_test_oss_download(), and Slic3r::GUI::NetworkTestDialog::start_test_oss_upgrade().
on_error()
Http & Slic3r::Http::on_error (ErrorFn fn)
{
  if (p) { p->errorfn = std::move(fn); }
  return *this;
}
References p.
Referenced by Slic3r::GUI::GUI_App::check_new_version_sf(), and Slic3r::GUI::HMSQuery::download_hms_info().
on_header_callback()
Http & Slic3r::Http::on_header_callback (HeaderCallbackFn fn)
{
  if (p) { p->headerfn = std::move(fn); }
  return *this;
}
References p.
on_ip_resolve()
Http & Slic3r::Http::on_ip_resolve (IPResolveFn fn)
{
  if (p) { p->ipresolvefn = std::move(fn); }
  return *this;
}
References p.
on_progress()
Http & Slic3r::Http::on_progress (ProgressFn fn)
{
  if (p) { p->progressfn = std::move(fn); }
  return *this;
}
References p.
Referenced by Slic3r::GUI::GUI_App::download_plugin(), Slic3r::PresetUpdater::priv::get_file(), Slic3r::GUI::NetworkTestDialog::start_test_oss_download(), Slic3r::PresetUpdater::priv::sync_config(), Slic3r::PresetUpdater::priv::sync_resources(), and Slic3r::PresetUpdater::priv::sync_version().
operator=() [1/2]
Http & Slic3r::Http::operator= (const Http &) delete
operator=() [2/2]
Http & Slic3r::Http::operator= (Http &&) delete
patch()
Http Slic3r::Http::patch (std::string url) static
{
  Http http{ std::move(url) };
  curl_easy_setopt(http.p->curl, CURLOPT_CUSTOMREQUEST, "PATCH");
  return http;
}
perform()
Http::Ptr Slic3r::Http::perform ()
{
  auto self = std::make_shared<Http>(std::move(*this));
  if (self->p) {
    auto io_thread = std::thread([self](){
        self->p->http_perform();
      });
    self->p->io_thread = std::move(io_thread);
  }
  return self;
}
perform_sync()
void Slic3r::Http::perform_sync ()
{
  if (p) { p->http_perform(); }
}
References p.
Referenced by Slic3r::GUI::GUI_App::download_plugin(), and Slic3r::GUI::NetworkTestDialog::start_test_oss_download().
post()
Http Slic3r::Http::post (std::string url) static
{
  Http http{std::move(url)};
  curl_easy_setopt(http.p->curl, CURLOPT_POST, 1L);
  return http;
}
Referenced by Slic3r::GUI::SendSystemInfoDialog::send_info(), Slic3r::Duet::start_print(), Slic3r::AstroBox::upload(), Slic3r::Duet::upload(), Slic3r::FlashAir::upload(), Slic3r::MKS::upload(), Slic3r::OctoPrint::upload(), and Slic3r::Repetier::upload().
put()
Http Slic3r::Http::put (std::string url) static
{
  Http http{std::move(url)};
  curl_easy_setopt(http.p->curl, CURLOPT_UPLOAD, 1L);
  return http;
}
Referenced by Slic3r::Duet::upload().
put2()
Http Slic3r::Http::put2 (std::string url) static
{
  Http http{ std::move(url) };
  curl_easy_setopt(http.p->curl, CURLOPT_CUSTOMREQUEST, "PUT");
  return http;
}
remove_header()
Http & Slic3r::Http::remove_header (std::string name)
{
  if (p) {
    name.push_back(':');
    p->headerlist = curl_slist_append(p->headerlist, name.c_str());
  }
  return *this;
}
References p.
set_del_body()
Http & Slic3r::Http::set_del_body (const std::string & body)
{
  if (p) { p->set_del_body(body); }
  return *this;
}
References p.
set_extra_headers()
void Slic3r::Http::set_extra_headers (std::map< std::string, std::string > headers) static
{
  extra_headers.swap(headers);
}
References Slic3r::extra_headers.
Referenced by Slic3r::GUI::GUI_App::on_init_inner(), and Slic3r::GUI::GUI_App::update_http_extra_header().
set_post_body() [1/2]
Http & Slic3r::Http::set_post_body (const boost::filesystem::path & path)
Referenced by Slic3r::GUI::SendSystemInfoDialog::send_info().
set_post_body() [2/2]
Http & Slic3r::Http::set_post_body (const std::string & body)
{
  if (p) { p->set_post_body(body); }
  return *this;
}
References p.
set_put_body()
Http & Slic3r::Http::set_put_body (const boost::filesystem::path & path)
{
  if (p) { p->set_put_body(path);}
  return *this;
}
References p.
size_limit()
Http & Slic3r::Http::size_limit (size_t sizeLimit)
{
  if (p) { p->limit = sizeLimit; }
  return *this;
}
References p.
Referenced by Slic3r::PresetUpdater::priv::sync_version().
timeout_connect()
Http & Slic3r::Http::timeout_connect (long timeout)
{
  if (timeout < 1) { timeout = priv::DEFAULT_TIMEOUT_CONNECT; }
  if (p) { p->set_timeout_connect(timeout); }
  return *this;
}
References Slic3r::Http::priv::DEFAULT_TIMEOUT_CONNECT, and p.
Referenced by Slic3r::GUI::GUI_App::check_new_version(), Slic3r::GUI::GUI_App::check_privacy_version(), and Slic3r::GUI::GUI_App::download_plugin().
timeout_max()
Http & Slic3r::Http::timeout_max (long timeout)
{
    if (timeout < 1) { timeout = priv::DEFAULT_TIMEOUT_MAX; }
    if (p) { p->set_timeout_max(timeout); }
    return *this;
}
References Slic3r::Http::priv::DEFAULT_TIMEOUT_MAX, and p.
Referenced by Slic3r::GUI::GUI_App::check_new_version(), Slic3r::GUI::GUI_App::check_privacy_version(), Slic3r::GUI::GUI_App::download_plugin(), Slic3r::GUI::get_error_message(), Slic3r::GUI::get_hms_info_version(), Slic3r::GUI::SendSystemInfoDialog::send_info(), Slic3r::GUI::NetworkTestDialog::start_test_bambulab(), Slic3r::GUI::NetworkTestDialog::start_test_bing(), Slic3r::GUI::NetworkTestDialog::start_test_oss(), and Slic3r::GUI::NetworkTestDialog::start_test_oss_upgrade().
tls_global_init()
std::string Slic3r::Http::tls_global_init () static
{
    if (!CurlGlobalInit::instance)
        CurlGlobalInit::instance = std::make_unique<CurlGlobalInit>();
    return CurlGlobalInit::instance->message;
}
References Slic3r::CurlGlobalInit::instance.
Referenced by Slic3r::Http::priv::priv(), and Slic3r::GUI::GUI_App::on_init_inner().
tls_system_cert_store()
std::string Slic3r::Http::tls_system_cert_store () static
{
    std::string ret;
#ifdef OPENSSL_CERT_OVERRIDE
    ret = ::getenv(X509_get_default_cert_file_env());
#endif
    return ret;
}
Referenced by Slic3r::GUI::GUI_App::on_init_inner().
url_decode()
std::string Slic3r::Http::url_decode (const std::string & str) static
{
    ::CURL *curl = ::curl_easy_init();
    if (curl == nullptr) { return str; }
    int outlen = 0;
    char *ce = ::curl_easy_unescape(curl, str.c_str(), str.length(), &outlen);
    std::string dencoded = std::string(ce, outlen);
    ::curl_free(ce);
    ::curl_easy_cleanup(curl);
    return dencoded;
}
Referenced by Slic3r::GUI::http_headers::get_response(), and Slic3r::GUI::GUI_App::url_decode().
url_encode()
std::string Slic3r::Http::url_encode (const std::string & str) static
{
  ::CURL *curl = ::curl_easy_init();
  if (curl == nullptr) {
    return str;
  }
  char *ce = ::curl_easy_escape(curl, str.c_str(), str.length());
  std::string encoded = std::string(ce);
  ::curl_free(ce);
  ::curl_easy_cleanup(curl);
  return encoded;
}
Referenced by Slic3r::MKS::get_upload_url(), Slic3r::Duet::get_upload_url(), Slic3r::Duet::start_print(), and Slic3r::GUI::GUI_App::url_encode().
Member Data Documentation
p
std::unique_ptr<priv> Slic3r::Http::p private
Referenced by ~Http(), auth_basic(), auth_digest(), ca_file(), cancel(), form_add(), header(), mime_form_add_file(), mime_form_add_text(), on_complete(), on_error(), on_header_callback(), on_ip_resolve(), on_progress(), perform_sync(), remove_header(), set_del_body(), set_post_body(), set_put_body(), size_limit(), timeout_connect(), and timeout_max().
The documentation for this class was generated from the following files:
src/slic3r/Utils/Http.hpp
src/slic3r/Utils/Http.cpp