OrcaSlicer: Slic3r::GUI::ArrangeJob Class Reference
Slic3r::GUI::ArrangeJob Class Reference
#include <src/slic3r/GUI/Jobs/ArrangeJob.hpp>
Public Types
enum JobPrepareState { PREPARE_STATE_DEFAULT = 0 , PREPARE_STATE_MENU = 1 }
Public Member Functions
ArrangeJob (std::shared_ptr< ProgressIndicator > pri, Plater *plater)
int status_range () const override
void finalize () override
bool is_finalized () const
void start ()
bool join (int timeout_ms=0)
bool is_running () const
void cancel ()
Protected Member Functions
void prepare () override
void check_unprintable ()
void on_exception (const std::exception_ptr &) override
void process () override
void update_status (int st, const wxString &msg="")
void update_percent_finish ()
void show_networking_test (wxString msg)
bool was_canceled () const
Protected Attributes
Plater * m_plater
bool only_on_partplate {false}
Private Types
using ArrangePolygon = arrangement::ArrangePolygon
using ArrangePolygons = arrangement::ArrangePolygons
Private Member Functions
void clear_input ()
void prepare_selected ()
void prepare_all ()
void prepare_partplate ()
void prepare_wipe_tower ()
ArrangePolygon prepare_arrange_polygon (void *instance)
void run (std::exception_ptr &)
Private Attributes
ArrangePolygons m_selected
ArrangePolygons m_unselected
ArrangePolygons m_unprintable
ArrangePolygons m_locked
std::vector< ModelInstance * > m_unarranged
std::map< int, ArrangePolygons > m_selected_groups
arrangement::ArrangeParams params
int current_plate_index = 0
Polygon bed_poly
int m_range = 100
int m_thread_evt_id = wxID_ANY
boost::thread m_thread
std::atomic< bool > m_running {false}
std::atomic< bool > m_canceled {false}
bool m_finalized = false
bool m_finalizing = false
std::shared_ptr< ProgressIndicator > m_progress
std::exception_ptr m_worker_error = nullptr
Detailed Description
Member Typedef Documentation
ArrangePolygon
using Slic3r::GUI::ArrangeJob::ArrangePolygon = arrangement::ArrangePolygon private
ArrangePolygons
using Slic3r::GUI::ArrangeJob::ArrangePolygons = arrangement::ArrangePolygons private
Member Enumeration Documentation
JobPrepareState
enum Slic3r::GUI::Job::JobPrepareState inherited
Enumerator
PREPARE_STATE_DEFAULT
PREPARE_STATE_MENU
{
        PREPARE_STATE_DEFAULT = 0,
        PREPARE_STATE_MENU = 1,
    };
Constructor & Destructor Documentation
ArrangeJob()
Slic3r::GUI::ArrangeJob::ArrangeJob (std::shared_ptr< ProgressIndicator > pri, Plater * plater) inline
        : PlaterJob{std::move(pri), plater}
    {}
Member Function Documentation
cancel()
void Slic3r::GUI::Job::cancel () inline inherited
{ m_canceled.store(true); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::UpgradeNetworkJob::process().
check_unprintable()
void Slic3r::GUI::ArrangeJob::check_unprintable () protected
{
    for (auto it = m_selected.begin(); it != m_selected.end();) {
        if (it->poly.area() < 0.001)
        {
#if SAVE_ARRANGE_POLY
            SVG svg("SVG/arrange_unprintable_"+it->name+".svg", get_extents(it->poly));
            if (svg.is_opened())
                svg.draw_outline(it->poly);
#endif
            m_unprintable.push_back(*it);
            auto msg = (boost::format(
                _utf8("Object %s has zero size and can't be arranged."))
                % _utf8(it->name)).str();
            m_plater->get_notification_manager()->push_notification(NotificationType::BBLPlateInfo,
                                NotificationManager::NotificationLevel::WarningNotificationLevel, msg);
            it = m_selected.erase(it);
        }
        else
            it++;
    }
}
References _utf8, Slic3r::GUI::BBLPlateInfo, Slic3r::SVG::draw_outline(), Slic3r::get_extents(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::SVG::is_opened(), Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unprintable, Slic3r::GUI::NotificationManager::push_notification(), and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
Referenced by prepare().
clear_input()
void Slic3r::GUI::ArrangeJob::clear_input () private
{
    const Model &model = m_plater->model();
    size_t count = 0, cunprint = 0; // To know how much space to reserve
    for (auto obj : model.objects)
        for (auto mi : obj->instances)
            mi->printable ? count++ : cunprint++;
    params.nonprefered_regions.clear();
    m_selected.clear();
    m_unselected.clear();
    m_unprintable.clear();
    m_locked.clear();
    m_unarranged.clear();
    m_selected.reserve(count + 1 /* for optional wti */);
    m_unselected.reserve(count + 1 /* for optional wti */);
    m_unprintable.reserve(cunprint /* for optional wti */);
    m_locked.reserve(count + 1 /* for optional wti */);
    current_plate_index = 0;
}
References count, current_plate_index, m_locked, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unarranged, m_unprintable, m_unselected, Slic3r::GUI::Plater::model(), Slic3r::arrangement::ArrangeParams::nonprefered_regions, Slic3r::Model::objects, and params.
Referenced by prepare_all(), prepare_partplate(), and prepare_selected().
finalize()
void Slic3r::GUI::ArrangeJob::finalize () override virtual
Reimplemented from Slic3r::GUI::Job.
{
    // Ignore the arrange result if aborted.
    if (was_canceled()) return;
    // Unprintable items go to the last virtual bed
    int beds = 0;
    //BBS: partplate
    PartPlateList& plate_list = m_plater->get_partplate_list();
    //clear all the relations before apply the arrangement results
    if (only_on_partplate) {
        plate_list.clear(false, false, true, current_plate_index);
    }
    else
        plate_list.clear(false, false, true, -1);
    //BBS: adjust the bed_index, create new plates, get the max bed_index
    for (ArrangePolygon& ap : m_selected) {
        //if (ap.bed_idx < 0) continue;  // bed_idx<0 means unarrangable
        //BBS: partplate postprocess
        if (only_on_partplate)
            plate_list.postprocess_bed_index_for_current_plate(ap);
        else
            plate_list.postprocess_bed_index_for_selected(ap);
        beds = std::max(ap.bed_idx, beds);
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": arrange selected %4%: bed_id %1%, trans {%2%,%3%}") % ap.bed_idx % unscale<double>(ap.translation(X)) % unscale<double>(ap.translation(Y)) % ap.name;
    }
    //BBS: adjust the bed_index, create new plates, get the max bed_index
    for (ArrangePolygon& ap : m_unselected)
    {
        if (ap.is_virt_object)
            continue;
        //BBS: partplate postprocess
        if (!only_on_partplate)
            plate_list.postprocess_bed_index_for_unselected(ap);
        beds = std::max(ap.bed_idx, beds);
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":arrange unselected %4%: bed_id %1%, trans {%2%,%3%}") % ap.bed_idx % unscale<double>(ap.translation(X)) % unscale<double>(ap.translation(Y)) % ap.name;
    }
    for (ArrangePolygon& ap : m_locked) {
        beds = std::max(ap.bed_idx, beds);
        plate_list.postprocess_arrange_polygon(ap, false);
        ap.apply();
    }
    // Apply the arrange result to all selected objects
    for (ArrangePolygon& ap : m_selected) {
        //BBS: partplate postprocess
        plate_list.postprocess_arrange_polygon(ap, true);
        ap.apply();
    }
    // Apply the arrange result to unselected objects(due to the sukodu-style column changes, the position of unselected may also be modified)
    for (ArrangePolygon& ap : m_unselected)
    {
        if (ap.is_virt_object)
            continue;
        //BBS: partplate postprocess
        plate_list.postprocess_arrange_polygon(ap, false);
        ap.apply();
    }
    // Move the unprintable items to the last virtual bed.
    // Note ap.apply() moves relatively according to bed_idx, so we need to subtract the orignal bed_idx
    for (ArrangePolygon& ap : m_unprintable) {
        ap.bed_idx = beds + 1;
        plate_list.postprocess_arrange_polygon(ap, true);
        ap.apply();
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(":arrange m_unprintable: name: %4%, bed_id %1%, trans {%2%,%3%}") % ap.bed_idx % unscale<double>(ap.translation(X)) % unscale<double>(ap.translation(Y)) % ap.name;
    }
    m_plater->update();
    // BBS
    //wxGetApp().obj_manipul()->set_dirty();
    if (!m_unarranged.empty()) {
        std::set<std::string> names;
        for (ModelInstance *mi : m_unarranged)
            names.insert(mi->get_object()->name);
        m_plater->get_notification_manager()->push_notification(GUI::format(
            _L("Arrangement ignored the following objects which can't fit into a single bed:\n%s"),
            concat_strings(names, "\n")));
    }
    m_plater->get_notification_manager()->close_notification_of_type(NotificationType::ArrangeOngoing);
    //BBS: reload all objects due to arrange
    if (only_on_partplate) {
        plate_list.rebuild_plates_after_arrangement(!only_on_partplate, true, current_plate_index);
    }
    else {
        plate_list.rebuild_plates_after_arrangement(!only_on_partplate, true);
    }
    // BBS: update slice context and gcode result.
    m_plater->update_slicing_context_to_current_partplate();
    wxGetApp().obj_list()->reload_all_plates();
    m_plater->update();
    Job::finalize();
    m_plater->m_arrange_running.store(false);
}
References _L, Slic3r::GUI::ArrangeOngoing, Slic3r::GUI::PartPlateList::clear(), Slic3r::GUI::NotificationManager::close_notification_of_type(), Slic3r::GUI::concat_strings(), current_plate_index, Slic3r::GUI::Job::finalize(), Slic3r::GUI::format(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::Plater::m_arrange_running, m_locked, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unarranged, m_unprintable, m_unselected, Slic3r::GUI::PlaterJob::only_on_partplate, Slic3r::GUI::PartPlateList::postprocess_arrange_polygon(), Slic3r::GUI::PartPlateList::postprocess_bed_index_for_current_plate(), Slic3r::GUI::PartPlateList::postprocess_bed_index_for_selected(), Slic3r::GUI::PartPlateList::postprocess_bed_index_for_unselected(), Slic3r::GUI::NotificationManager::push_notification(), Slic3r::GUI::PartPlateList::rebuild_plates_after_arrangement(), Slic3r::GUI::Plater::update(), Slic3r::GUI::Plater::update_slicing_context_to_current_partplate(), Slic3r::GUI::Job::was_canceled(), Slic3r::X, and Slic3r::Y.
is_finalized()
bool Slic3r::GUI::Job::is_finalized () const inline inherited
{ return m_finalized; }
References Slic3r::GUI::Job::m_finalized.
is_running()
bool Slic3r::GUI::Job::is_running () const inline inherited
{ return m_running.load(); }
References Slic3r::GUI::Job::m_running.
join()
bool Slic3r::GUI::Job::join (int timeout_ms = 0) inherited
{
    if (!m_thread.joinable()) return true;
    if (timeout_ms <= 0)
        m_thread.join();
    else if (!m_thread.try_join_for(boost::chrono::milliseconds(timeout_ms)))
        return false;
    return true;
}
on_exception()
void Slic3r::GUI::ArrangeJob::on_exception (const std::exception_ptr & eptr) override protected virtual
Reimplemented from Slic3r::GUI::Job.
{
    try {
        if (eptr)
            std::rethrow_exception(eptr);
    } catch (libnest2d::GeometryException &) {
        show_error(m_plater, _(L("Arrange failed. "
                                 "Found some exceptions when processing object geometries.")));
    } catch (std::exception &) {
        PlaterJob::on_exception(eptr);
    }
}
References _, L, Slic3r::GUI::PlaterJob::m_plater, Slic3r::GUI::PlaterJob::on_exception(), and Slic3r::GUI::show_error().
prepare()
void Slic3r::GUI::ArrangeJob::prepare () override protected virtual
Reimplemented from Slic3r::GUI::Job.
{
    m_plater->get_notification_manager()->push_notification(NotificationType::ArrangeOngoing,
        NotificationManager::NotificationLevel::RegularNotificationLevel, _u8L("Arranging..."));
    m_plater->get_notification_manager()->bbl_close_plateinfo_notification();
    params = init_arrange_params(m_plater);
    //BBS update extruder params and speed table before arranging
    Plater::setExtruderParams(Model::extruderParamsMap);
    Plater::setPrintSpeedTable(Model::printSpeedMap);
    int state = m_plater->get_prepare_state();
    if (state == Job::JobPrepareState::PREPARE_STATE_DEFAULT) {
        only_on_partplate = false;
        prepare_all();
    }
    else if (state == Job::JobPrepareState::PREPARE_STATE_MENU) {
        only_on_partplate = true;   // only arrange items on current plate
        prepare_partplate();
    }
#if SAVE_ARRANGE_POLY
    if (1)
    { // subtract excluded region and get a polygon bed
        auto& print = wxGetApp().plater()->get_partplate_list().get_current_fff_print();
        auto print_config = print.config();
        bed_poly.points = get_bed_shape(*m_plater->config());
        Pointfs excluse_area_points = print_config.bed_exclude_area.values;
        Polygons exclude_polys;
        Polygon exclude_poly;
        for (int i = 0; i < excluse_area_points.size(); i++) {
            auto pt = excluse_area_points[i];
            exclude_poly.points.emplace_back(scale_(pt.x()), scale_(pt.y()));
            if (i % 4 == 3) {  // exclude areas are always rectangle
                exclude_polys.push_back(exclude_poly);
                exclude_poly.points.clear();
            }
        }
        bed_poly = diff({ bed_poly }, exclude_polys)[0];
    }
    BoundingBox bbox = bed_poly.bounding_box();
    Point center = bbox.center();
    auto polys_to_draw = m_selected;
    for (auto it = polys_to_draw.begin(); it != polys_to_draw.end(); it++) {
        it->poly.translate(center);
        bbox.merge(it->poly);
    }
    SVG svg("SVG/arrange_poly.svg", bbox);
    if (svg.is_opened()) {
        svg.draw_outline(bed_poly);
        //svg.draw_grid(bbox, "gray", scale_(0.05));
        std::vector<std::string> color_array = { "red","black","yellow","gree","blue" };
        for (auto it = polys_to_draw.begin(); it != polys_to_draw.end(); it++) {
            std::string color = color_array[(it - polys_to_draw.begin()) % color_array.size()];
            svg.add_comment(it->name);
            svg.draw_text(get_extents(it->poly).min, it->name.c_str(), color.c_str());
            svg.draw_outline(it->poly, color);
        }
    }
#endif
    check_unprintable();
}
References _u8L, Slic3r::SVG::add_comment(), Slic3r::GUI::ArrangeOngoing, Slic3r::GUI::NotificationManager::bbl_close_plateinfo_notification(), bed_poly, Slic3r::MultiPoint::bounding_box(), Slic3r::BoundingBoxBase< PointClass >::center(), check_unprintable(), Slic3r::GUI::Plater::config(), Slic3r::diff(), Slic3r::SVG::draw_outline(), Slic3r::SVG::draw_text(), Slic3r::Model::extruderParamsMap, Slic3r::get_bed_shape(), Slic3r::get_extents(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::GUI::Plater::get_prepare_state(), Slic3r::GUI::init_arrange_params(), Slic3r::SVG::is_opened(), Slic3r::GUI::PlaterJob::m_plater, m_selected, Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::GUI::PlaterJob::only_on_partplate, params, Slic3r::MultiPoint::points, prepare_all(), prepare_partplate(), Slic3r::GUI::Job::PREPARE_STATE_DEFAULT, Slic3r::GUI::Job::PREPARE_STATE_MENU, Slic3r::Model::printSpeedMap, Slic3r::GUI::NotificationManager::push_notification(), Slic3r::GUI::NotificationManager::RegularNotificationLevel, scale_, Slic3r::GUI::Plater::setExtruderParams(), and Slic3r::GUI::Plater::setPrintSpeedTable().
prepare_all()
void Slic3r::GUI::ArrangeJob::prepare_all () private
{
    PartPlateList& plate_list = m_plater->get_partplate_list();
    clear_input();
    Model &model = m_plater->model();
    bool selected_is_locked = false;
    // Go through the objects and check if inside the selection
    for (size_t oidx = 0; oidx < model.objects.size(); ++oidx) {
        ModelObject *mo = model.objects[oidx];
        for (size_t i = 0; i < mo->instances.size(); ++i) {
            ModelInstance * mi = mo->instances[i];
            ArrangePolygon&& ap = prepare_arrange_polygon(mo->instances[i]);
            //BBS: partplate_list preprocess
            //remove the locked plate's instances, neither in selected, nor in un-selected
            bool locked = plate_list.preprocess_arrange_polygon(oidx, i, ap, true);
            if (!locked)
            {
                ArrangePolygons& cont = mo->instances[i]->printable ? m_selected :m_unprintable;
                ap.itemid = cont.size();
                cont.emplace_back(std::move(ap));
            }
            else
            {
                //skip this object due to be locked in plate
                ap.itemid = m_locked.size();
                m_locked.emplace_back(std::move(ap));
                selected_is_locked = true;
                BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": skip locked instance, obj_id %1%, instance_id %2%") % oidx % i;
            }
        }
    }
    // If the selection was empty arrange everything
    //if (m_selected.empty()) m_selected.swap(m_unselected);
    if (m_selected.empty()) {
        if (!selected_is_locked) {
            m_plater->get_notification_manager()->push_notification(NotificationType::BBLPlateInfo,
                NotificationManager::NotificationLevel::WarningNotificationLevel, into_u8(_L("No arrangable objects are selected.")));
        }
        else {
            m_plater->get_notification_manager()->push_notification(NotificationType::BBLPlateInfo,
                NotificationManager::NotificationLevel::WarningNotificationLevel, into_u8(_L("All the selected objects are on the locked plate,\nWe can not do auto-arrange on these objects.")));
        }
    }
    prepare_wipe_tower();
    // add the virtual object into unselect list if has
    plate_list.preprocess_exclude_areas(m_unselected, MAX_NUM_PLATES);
}
References _L, Slic3r::GUI::BBLPlateInfo, clear_input(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::ModelObject::instances, Slic3r::GUI::into_u8(), Slic3r::arrangement::ArrangePolygon::itemid, m_locked, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unprintable, m_unselected, MAX_NUM_PLATES, Slic3r::GUI::Plater::model(), Slic3r::Model::objects, prepare_arrange_polygon(), prepare_wipe_tower(), Slic3r::GUI::PartPlateList::preprocess_arrange_polygon(), Slic3r::GUI::PartPlateList::preprocess_exclude_areas(), Slic3r::GUI::NotificationManager::push_notification(), and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
Referenced by prepare().
prepare_arrange_polygon()
ArrangePolygon Slic3r::GUI::ArrangeJob::prepare_arrange_polygon (void * instance) private
{
    ModelInstance* instance = (ModelInstance*)model_instance;
    const Slic3r::DynamicPrintConfig& config = wxGetApp().preset_bundle->full_config();
    return get_instance_arrange_poly(instance, config);
}
References Slic3r::get_instance_arrange_poly().
Referenced by prepare_all(), prepare_partplate(), and prepare_selected().
prepare_partplate()
void Slic3r::GUI::ArrangeJob::prepare_partplate () private
{
    clear_input();
    PartPlateList& plate_list = m_plater->get_partplate_list();
    PartPlate* plate = plate_list.get_curr_plate();
    current_plate_index = plate_list.get_curr_plate_index();
    assert(plate != nullptr);
    if (plate->empty())
    {
        //no instances on this plate
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": no instances in current plate!");
        return;
    }
    if (plate->is_locked()) {
        m_plater->get_notification_manager()->push_notification(NotificationType::BBLPlateInfo,
            NotificationManager::NotificationLevel::WarningNotificationLevel, into_u8(_L("This plate is locked,\nWe can not do auto-arrange on this plate.")));
        return;
    }
    params.is_seq_print = plate->get_real_print_seq() == PrintSequence::ByObject;
    Model& model = m_plater->model();
    // Go through the objects and check if inside the selection
    for (size_t oidx = 0; oidx < model.objects.size(); ++oidx)
    {
        ModelObject* mo = model.objects[oidx];
        for (size_t inst_idx = 0; inst_idx < mo->instances.size(); ++inst_idx)
        {
            bool             in_plate = plate->contain_instance(oidx, inst_idx) || plate->intersect_instance(oidx, inst_idx);
            ArrangePolygon&& ap = prepare_arrange_polygon(mo->instances[inst_idx]);
            ArrangePolygons& cont = mo->instances[inst_idx]->printable ?
                (in_plate ? m_selected : m_unselected) :
                m_unprintable;
            bool locked = plate_list.preprocess_arrange_polygon_other_locked(oidx, inst_idx, ap, in_plate);
            if (!locked)
            {
                ap.itemid = cont.size();
                cont.emplace_back(std::move(ap));
            }
            else
            {
                //skip this object due to be not in current plate, treated as locked
                ap.itemid = m_locked.size();
                m_locked.emplace_back(std::move(ap));
                BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": skip locked instance, obj_id %1%, name %2%") % oidx % mo->name;
            }
        }
    }
    // BBS
    if (auto wti = get_wipe_tower(*m_plater, current_plate_index)) {
        ArrangePolygon&& ap = get_wipetower_arrange_poly(&wti);
        m_unselected.emplace_back(std::move(ap));
    }
    // add the virtual object into unselect list if has
    plate_list.preprocess_exclude_areas(m_unselected, current_plate_index + 1);
}
References _L, Slic3r::GUI::BBLPlateInfo, Slic3r::ByObject, clear_input(), Slic3r::GUI::PartPlate::contain_instance(), current_plate_index, Slic3r::GUI::PartPlate::empty(), Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::PartPlateList::get_curr_plate_index(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::PartPlate::get_real_print_seq(), Slic3r::GUI::get_wipe_tower(), Slic3r::GUI::get_wipetower_arrange_poly(), Slic3r::ModelObject::instances, Slic3r::GUI::PartPlate::intersect_instance(), Slic3r::GUI::into_u8(), Slic3r::GUI::PartPlate::is_locked(), Slic3r::arrangement::ArrangeParams::is_seq_print, Slic3r::arrangement::ArrangePolygon::itemid, m_locked, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unprintable, m_unselected, Slic3r::GUI::Plater::model(), Slic3r::ModelObject::name, Slic3r::Model::objects, params, prepare_arrange_polygon(), Slic3r::GUI::PartPlateList::preprocess_arrange_polygon_other_locked(), Slic3r::GUI::PartPlateList::preprocess_exclude_areas(), Slic3r::GUI::NotificationManager::push_notification(), and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
Referenced by prepare().
prepare_selected()
void Slic3r::GUI::ArrangeJob::prepare_selected () private
{
    PartPlateList& plate_list = m_plater->get_partplate_list();
    clear_input();
    Model& model = m_plater->model();
    bool selected_is_locked = false;
    //BBS: remove logic for unselected object
    //double stride = bed_stride_x(m_plater);
    std::vector<const Selection::InstanceIdxsList*>
        obj_sel(model.objects.size(), nullptr);
    for (auto& s : m_plater->get_selection().get_content())
        if (s.first < int(obj_sel.size()))
            obj_sel[size_t(s.first)] = &s.second;
    // Go through the objects and check if inside the selection
    for (size_t oidx = 0; oidx < model.objects.size(); ++oidx) {
        const Selection::InstanceIdxsList* instlist = obj_sel[oidx];
        ModelObject* mo = model.objects[oidx];
        std::vector<bool> inst_sel(mo->instances.size(), false);
        if (instlist)
            for (auto inst_id : *instlist)
                inst_sel[size_t(inst_id)] = true;
        for (size_t i = 0; i < inst_sel.size(); ++i) {
            ModelInstance* mi = mo->instances[i];
            ArrangePolygon&& ap = prepare_arrange_polygon(mo->instances[i]);
            //BBS: partplate_list preprocess
            //remove the locked plate's instances, neither in selected, nor in un-selected
            bool locked = plate_list.preprocess_arrange_polygon(oidx, i, ap, inst_sel[i]);
            if (!locked)
                {
                ArrangePolygons& cont = mo->instances[i]->printable ?
                    (inst_sel[i] ? m_selected :
                        m_unselected) :
                    m_unprintable;
                ap.itemid = cont.size();
                cont.emplace_back(std::move(ap));
                }
            else
                {
                //skip this object due to be locked in plate
                ap.itemid = m_locked.size();
                m_locked.emplace_back(std::move(ap));
                if (inst_sel[i])
                    selected_is_locked = true;
                BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": skip locked instance, obj_id %1%, instance_id %2%, name %3%") % oidx % i % mo->name;
                }
            }
        }
    // If the selection was empty arrange everything
    //if (m_selected.empty()) m_selected.swap(m_unselected);
    if (m_selected.empty()) {
        if (!selected_is_locked)
            m_selected.swap(m_unselected);
        else {
            m_plater->get_notification_manager()->push_notification(NotificationType::BBLPlateInfo,
                NotificationManager::NotificationLevel::WarningNotificationLevel, into_u8(_L("All the selected objects are on the locked plate,\nWe can not do auto-arrange on these objects.")));
            }
        }
    prepare_wipe_tower();
    // The strides have to be removed from the fixed items. For the
    // arrangeable (selected) items bed_idx is ignored and the
    // translation is irrelevant.
    //BBS: remove logic for unselected object
    //for (auto &p : m_unselected) p.translation(X) -= p.bed_idx * stride;
}
References _L, Slic3r::GUI::BBLPlateInfo, clear_input(), Slic3r::GUI::Selection::get_content(), Slic3r::GUI::Plater::get_notification_manager(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::Plater::get_selection(), Slic3r::ModelObject::instances, Slic3r::GUI::into_u8(), Slic3r::arrangement::ArrangePolygon::itemid, m_locked, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unprintable, m_unselected, Slic3r::GUI::Plater::model(), Slic3r::ModelObject::name, Slic3r::Model::objects, prepare_arrange_polygon(), prepare_wipe_tower(), Slic3r::GUI::PartPlateList::preprocess_arrange_polygon(), Slic3r::GUI::NotificationManager::push_notification(), and Slic3r::GUI::NotificationManager::WarningNotificationLevel.
prepare_wipe_tower()
void Slic3r::GUI::ArrangeJob::prepare_wipe_tower () private
{
    bool need_wipe_tower = false;
    // if wipe tower is explicitly disabled, no need to estimate
    DynamicPrintConfig &current_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
    auto                op             = current_config.option("enable_prime_tower");
    if (op && op->getBool() == false || params.is_seq_print) return;
    // estimate if we need wipe tower for all plates:
    // need wipe tower if some object has multiple extruders (has paint-on colors or support material)
    for (const auto &item : m_selected) {
        std::set<int> obj_extruders;
        obj_extruders.insert(item.extrude_ids.begin(), item.extrude_ids.end());
        if (obj_extruders.size() > 1) {
            need_wipe_tower = true;
            BOOST_LOG_TRIVIAL(info) << "arrange: need wipe tower because object " << item.name << " has multiple extruders (has paint-on colors)";
            break;
        }
    }
    // if multile extruders have same bed temp, we need wipe tower
    //
     if (params.allow_multi_materials_on_same_plate) {
        std::map<int, std::set<int>> bedTemp2extruderIds;
        for (const auto &item : m_selected)
            for (auto id : item.extrude_ids) { bedTemp2extruderIds[item.bed_temp].insert(id); }
        for (const auto &be : bedTemp2extruderIds) {
            if (be.second.size() > 1) {
                need_wipe_tower = true;
                BOOST_LOG_TRIVIAL(info) << "arrange: need wipe tower because allow_multi_materials_on_same_plate=true and we have multiple extruders of same type";
                break;
            }
        }
    }
    BOOST_LOG_TRIVIAL(info) << "arrange: need_wipe_tower=" << need_wipe_tower;
    if (need_wipe_tower) {
        // check all plates to see if wipe tower is already there
        ArrangePolygon    wipe_tower_ap;
        std::vector<bool> plates_have_wipe_tower(MAX_NUM_PLATES, false);
        for (int bedid = 0; bedid < MAX_NUM_PLATES; bedid++)
            if (auto wti = get_wipe_tower(*m_plater, bedid)) {
                ArrangePolygon &&ap = get_wipetower_arrange_poly(&wti);
                wipe_tower_ap       = ap;
                ap.bed_idx          = bedid;
                m_unselected.emplace_back(std::move(ap));
                plates_have_wipe_tower[bedid] = true;
            }
        // if wipe tower is not init yet (no wipe tower in any plate before arrangement)
        //if (wipe_tower_ap.poly.empty()) {
        //    auto &print                       = wxGetApp().plater()->get_partplate_list().get_current_fff_print();
        //    wipe_tower_ap.poly.contour.points = print.first_layer_wipe_tower_corners(false);
            wipe_tower_ap.name                = "WipeTower";
            wipe_tower_ap.is_virt_object      = true;
            wipe_tower_ap.is_wipe_tower       = true;
        //}
        const GLCanvas3D* canvas3D=static_cast<const GLCanvas3D *>(m_plater->canvas3D());
        for (int bedid = 0; bedid < MAX_NUM_PLATES; bedid++) {
            if (!plates_have_wipe_tower[bedid]) {
                wipe_tower_ap.translation = {0, 0};
                wipe_tower_ap.poly.contour.points = canvas3D->estimate_wipe_tower_points(bedid, !only_on_partplate);
                wipe_tower_ap.bed_idx             = bedid;
                m_unselected.emplace_back(wipe_tower_ap);
            }
        }
    }
}
References Slic3r::arrangement::ArrangeParams::allow_multi_materials_on_same_plate, Slic3r::arrangement::ArrangePolygon::bed_idx, Slic3r::GUI::Plater::canvas3D(), Slic3r::ExPolygon::contour, Slic3r::GUI::GLCanvas3D::estimate_wipe_tower_points(), Slic3r::GUI::get_wipe_tower(), Slic3r::GUI::get_wipetower_arrange_poly(), Slic3r::arrangement::ArrangeParams::is_seq_print, Slic3r::arrangement::ArrangePolygon::is_virt_object, Slic3r::arrangement::ArrangePolygon::is_wipe_tower, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unselected, MAX_NUM_PLATES, Slic3r::arrangement::ArrangePolygon::name, Slic3r::GUI::PlaterJob::only_on_partplate, Slic3r::ConfigBase::option(), params, Slic3r::MultiPoint::points, Slic3r::arrangement::ArrangePolygon::poly, and Slic3r::arrangement::ArrangePolygon::translation.
Referenced by prepare_all(), and prepare_selected().
process()
void Slic3r::GUI::ArrangeJob::process () override protected virtual
Implements Slic3r::GUI::Job.
{
    const GLCanvas3D::ArrangeSettings &settings =
        static_cast<const GLCanvas3D*>(m_plater->canvas3D())->get_arrange_settings();
    auto & partplate_list = m_plater->get_partplate_list();
    auto& print = wxGetApp().plater()->get_partplate_list().get_current_fff_print();
    const Slic3r::DynamicPrintConfig& global_config = wxGetApp().preset_bundle->full_config();
    PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    const bool has_lidar = preset_bundle->printers.get_edited_preset().has_lidar(preset_bundle);
    if (has_lidar && params.avoid_extrusion_cali_region && global_config.opt_bool("scan_first_layer"))
        partplate_list.preprocess_nonprefered_areas(m_unselected, MAX_NUM_PLATES);
    update_arrange_params(params, *m_plater, m_selected);
    update_selected_items_inflation(m_selected, *m_plater, params);
    update_unselected_items_inflation(m_unselected, *m_plater, params);
    Points      bedpts = get_shrink_bedpts(*m_plater,params);
    double scaled_exclusion_gap = scale_(1);
    partplate_list.preprocess_exclude_areas(params.excluded_regions, 1, scaled_exclusion_gap);
    BOOST_LOG_TRIVIAL(debug) << "arrange bed_shrink_x=" << params.bed_shrink_x
        << "; bedpts:" << bedpts[0].transpose() << ", " << bedpts[1].transpose() << ", " << bedpts[2].transpose() << ", " << bedpts[3].transpose();
    params.stopcondition = [this]() { return was_canceled(); };
    params.progressind = [this](unsigned num_finished, std::string str = "") {
        update_status(num_finished, _L("Arranging") + " "+ wxString::FromUTF8(str));
    };
    {
        BOOST_LOG_TRIVIAL(debug) << "items selected before arrange: ";
        for (auto selected : m_selected)
            BOOST_LOG_TRIVIAL(debug) << selected.name << ", extruder: " << selected.extrude_ids.back() << ", bed: " << selected.bed_idx
            << ", bed_temp: " << selected.first_bed_temp << ", print_temp: " << selected.print_temp;
        BOOST_LOG_TRIVIAL(debug) << "items unselected before arrange: ";
        for (auto item : m_unselected)
            if (!item.is_virt_object)
            BOOST_LOG_TRIVIAL(debug) << item.name << ", extruder: " << item.extrude_ids.back() << ", bed: " << item.bed_idx << ", trans: " << item.translation.transpose();
    }
    arrangement::arrange(m_selected, m_unselected, bedpts, params);
    // sort by item id
    std::sort(m_selected.begin(), m_selected.end(), [](auto a, auto b) {return a.itemid < b.itemid; });
    {
        BOOST_LOG_TRIVIAL(debug) << "items selected after arrange: ";
        for (auto selected : m_selected)
            BOOST_LOG_TRIVIAL(debug) << selected.name << ", extruder: " << selected.extrude_ids.back() << ", bed: " << selected.bed_idx
                                     << ", bed_temp: " << selected.first_bed_temp << ", print_temp: " << selected.print_temp
                                     << ", trans: " << unscale<double>(selected.translation(X)) << ","<< unscale<double>(selected.translation(Y));
        BOOST_LOG_TRIVIAL(debug) << "items unselected after arrange: ";
        for (auto item : m_unselected)
            if (!item.is_virt_object)
                BOOST_LOG_TRIVIAL(debug) << item.name << ", extruder: " << item.extrude_ids.back() << ", bed: " << item.bed_idx
                << ", trans: " << item.translation.transpose();
    }
    arrangement::arrange(m_unprintable, {}, bedpts, params);
    // put unpackable items to m_unprintable so they goes outside
    bool we_have_unpackable_items = false;
    for (auto item : m_selected) {
        if (item.bed_idx < 0) {
            //BBS: already processed in m_selected
            //m_unprintable.push_back(std::move(item));
            we_have_unpackable_items = true;
        }
    }
    // finalize just here.
    update_status(status_range(),
        was_canceled() ? _(L("Arranging canceled.")) :
        we_have_unpackable_items ? _(L("Arranging is done but there are unpacked items. Reduce spacing and try again.")) : _(L("Arranging done.")));
}
References _, _L, Slic3r::arrangement::arrange(), Slic3r::arrangement::ArrangeParams::avoid_extrusion_cali_region, Slic3r::arrangement::ArrangeParams::bed_shrink_x, Slic3r::GUI::Plater::canvas3D(), Slic3r::arrangement::ArrangeParams::excluded_regions, Slic3r::GUI::PartPlateList::get_current_fff_print(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::Plater::get_partplate_list(), Slic3r::GUI::get_shrink_bedpts(), Slic3r::Preset::has_lidar(), L, Slic3r::GUI::PlaterJob::m_plater, m_selected, m_unprintable, m_unselected, MAX_NUM_PLATES, Slic3r::DynamicConfig::opt_bool(), params, Slic3r::PresetBundle::printers, Slic3r::arrangement::ArrangeParams::progressind, scale_, status_range(), Slic3r::arrangement::ArrangeParams::stopcondition, Slic3r::GUI::update_arrange_params(), Slic3r::GUI::update_selected_items_inflation(), Slic3r::GUI::Job::update_status(), Slic3r::GUI::update_unselected_items_inflation(), Slic3r::GUI::Job::was_canceled(), Slic3r::X, and Slic3r::Y.
run()
void Slic3r::GUI::Job::run (std::exception_ptr & eptr) private inherited
{
    m_running.store(true);
    try {
        process();
    } catch (...) {
        eptr = std::current_exception();
    }
    m_running.store(false);
    // ensure to call the last status to finalize the job
    update_status(status_range(), "");
}
References Slic3r::GUI::Job::m_running, Slic3r::GUI::Job::process(), Slic3r::GUI::Job::status_range(), and Slic3r::GUI::Job::update_status().
show_networking_test()
void Slic3r::GUI::Job::show_networking_test (wxString msg) protected inherited
{
    m_progress->show_networking_test(msg);
}
Referenced by Slic3r::GUI::PrintJob::process().
start()
void Slic3r::GUI::Job::start () inherited
{ // Start the job. No effect if the job is already running
    if (!m_running.load()) {
        prepare();
        // Save the current status indicatior range and push the new one
        m_range = m_progress->get_range();
        m_progress->set_range(status_range());
        // init cancellation flag and set the cancel callback
        m_canceled.store(false);
        m_progress->set_cancel_callback(
                    [this]() { m_canceled.store(true); });
        m_finalized  = false;
        m_finalizing = false;
        // Changing cursor to busy
        wxBeginBusyCursor();
        try { // Execute the job
            m_worker_error = nullptr;
            m_thread = create_thread([this] { this->run(m_worker_error); });
        } catch (std::exception &) {
            update_status(status_range(),
                          _(L("Error! Unable to create thread!")));
        }
        // The state changes will be undone when the process hits the
        // last status value, in the status update handler (see ctor)
    }
}
References _, Slic3r::create_thread(), and L.
Referenced by Slic3r::GUI::OrientJob::process().
status_range()
int Slic3r::GUI::ArrangeJob::status_range () const inline override virtual
Reimplemented from Slic3r::GUI::Job.
    {
        // ensure finalize() is called after all operations in process() is finished.
        return int(m_selected.size() + m_unprintable.size() + 1);
    }
References int, m_selected, and m_unprintable.
Referenced by process().
update_percent_finish()
void Slic3r::GUI::Job::update_percent_finish () protected inherited
{
    m_progress->clear_percent();
}
Referenced by Slic3r::GUI::PrintJob::process().
update_status()
void Slic3r::GUI::Job::update_status (int st, const wxString & msg = "") protected inherited
{
    auto evt = new wxThreadEvent(wxEVT_THREAD, m_thread_evt_id);
    evt->SetInt(st);
    evt->SetString(msg);
    wxQueueEvent(this, evt);
}
Referenced by process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), Slic3r::GUI::Job::run(), Slic3r::GUI::BindJob::update_status(), and Slic3r::GUI::UpgradeNetworkJob::update_status().
was_canceled()
bool Slic3r::GUI::Job::was_canceled () const inline protected inherited
{ return m_canceled.load(); }
References Slic3r::GUI::Job::m_canceled.
Referenced by finalize(), Slic3r::GUI::BindJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::PrintJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SendJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::UpgradeNetworkJob::finalize(), process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), and Slic3r::GUI::UpgradeNetworkJob::process().
Member Data Documentation
bed_poly
Polygon Slic3r::GUI::ArrangeJob::bed_poly private
Referenced by prepare().
current_plate_index
int Slic3r::GUI::ArrangeJob::current_plate_index = 0 private
Referenced by clear_input(), finalize(), and prepare_partplate().
m_canceled
std::atomic<bool> Slic3r::GUI::Job::m_canceled {false} private inherited
Referenced by Slic3r::GUI::Job::cancel(), and Slic3r::GUI::Job::was_canceled().
m_finalized
bool Slic3r::GUI::Job::m_finalized = false private inherited
Referenced by Slic3r::GUI::Job::Job(), Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::is_finalized().
m_finalizing
bool Slic3r::GUI::Job::m_finalizing = false private inherited
Referenced by Slic3r::GUI::Job::Job().
m_locked
ArrangePolygons Slic3r::GUI::ArrangeJob::m_locked private
Referenced by clear_input(), finalize(), prepare_all(), prepare_partplate(), and prepare_selected().
m_plater
Plater* Slic3r::GUI::PlaterJob::m_plater protected inherited
Referenced by check_unprintable(), clear_input(), Slic3r::GUI::OrientJob::clear_input(), finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), on_exception(), Slic3r::GUI::PlaterJob::on_exception(), prepare(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::OrientJob::prepare(), Slic3r::GUI::PrintJob::prepare(), Slic3r::GUI::RotoptimizeJob::prepare(), Slic3r::GUI::SendJob::prepare(), prepare_all(), prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), prepare_wipe_tower(), process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), and Slic3r::GUI::SLAImportJob::reset().
m_progress
std::shared_ptr<ProgressIndicator> Slic3r::GUI::Job::m_progress private inherited
Referenced by Slic3r::GUI::Job::Job().
m_range
int Slic3r::GUI::Job::m_range = 100 private inherited
Referenced by Slic3r::GUI::Job::Job().
m_running
std::atomic<bool> Slic3r::GUI::Job::m_running {false} private inherited
Referenced by Slic3r::GUI::Job::is_running(), and Slic3r::GUI::Job::run().
m_selected
ArrangePolygons Slic3r::GUI::ArrangeJob::m_selected private
Referenced by check_unprintable(), clear_input(), finalize(), prepare(), prepare_all(), prepare_partplate(), prepare_selected(), prepare_wipe_tower(), process(), and status_range().
m_selected_groups
std::map<int, ArrangePolygons> Slic3r::GUI::ArrangeJob::m_selected_groups private
m_thread
boost::thread Slic3r::GUI::Job::m_thread private inherited
m_thread_evt_id
int Slic3r::GUI::Job::m_thread_evt_id = wxID_ANY private inherited
Referenced by Slic3r::GUI::Job::Job().
m_unarranged
std::vector<ModelInstance*> Slic3r::GUI::ArrangeJob::m_unarranged private
Referenced by clear_input(), and finalize().
m_unprintable
ArrangePolygons Slic3r::GUI::ArrangeJob::m_unprintable private
Referenced by check_unprintable(), clear_input(), finalize(), prepare_all(), prepare_partplate(), prepare_selected(), process(), and status_range().
m_unselected
ArrangePolygons Slic3r::GUI::ArrangeJob::m_unselected private
Referenced by clear_input(), finalize(), prepare_all(), prepare_partplate(), prepare_selected(), prepare_wipe_tower(), and process().
m_worker_error
std::exception_ptr Slic3r::GUI::Job::m_worker_error = nullptr private inherited
Referenced by Slic3r::GUI::Job::Job().
only_on_partplate
bool Slic3r::GUI::PlaterJob::only_on_partplate {false} protected inherited
Referenced by finalize(), prepare(), Slic3r::GUI::OrientJob::prepare(), and prepare_wipe_tower().
params
arrangement::ArrangeParams Slic3r::GUI::ArrangeJob::params private
Referenced by clear_input(), prepare(), prepare_partplate(), prepare_wipe_tower(), and process().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/ArrangeJob.hpp
src/slic3r/GUI/Jobs/ArrangeJob.cpp