OrcaSlicer: BlinkingBitmap Class Reference
BlinkingBitmap Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
BlinkingBitmap ()
BlinkingBitmap (wxWindow *parent, const std::string &icon_name="blank_16")
~BlinkingBitmap ()
void msw_rescale ()
void invalidate ()
void activate ()
void blink ()
const wxBitmap & get_bmp () const
Private Attributes
ScalableBitmap bmp
bool show {false}
Detailed Description
Constructor & Destructor Documentation
BlinkingBitmap() [1/2]
BlinkingBitmap::BlinkingBitmap () inline
{};
BlinkingBitmap() [2/2]
BlinkingBitmap::BlinkingBitmap (wxWindow * parent, const std::string & icon_name = "blank_16")
                                                                           :
    wxStaticBitmap(parent, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxSize(int(1.6 * Slic3r::GUI::wxGetApp().em_unit()), -1))
{
    bmp = ScalableBitmap(parent, icon_name);
}
References bmp.
~BlinkingBitmap()
BlinkingBitmap::~BlinkingBitmap () inline
{}
Member Function Documentation
activate()
void BlinkingBitmap::activate ()
{
    this->SetBitmap(bmp.bmp());
    show = true;
}
References ScalableBitmap::bmp(), bmp, and show.
blink()
void BlinkingBitmap::blink ()
{
    show = !show;
    this->SetBitmap(show ? bmp.bmp() : wxNullBitmap);
}
References ScalableBitmap::bmp(), bmp, and show.
get_bmp()
const wxBitmap & BlinkingBitmap::get_bmp () const inline
{ return bmp.bmp(); }
References ScalableBitmap::bmp(), and bmp.
invalidate()
void BlinkingBitmap::invalidate ()
{
    this->SetBitmap(wxNullBitmap);
}
msw_rescale()
void BlinkingBitmap::msw_rescale ()
{
    bmp.msw_rescale();
    this->SetSize(bmp.GetBmpSize());
    this->SetMinSize(bmp.GetBmpSize());
}
References bmp, ScalableBitmap::GetBmpSize(), and ScalableBitmap::msw_rescale().
Member Data Documentation
bmp
ScalableBitmap BlinkingBitmap::bmp private
Referenced by BlinkingBitmap(), activate(), blink(), get_bmp(), and msw_rescale().
show
bool BlinkingBitmap::show {false} private
Referenced by activate(), and blink().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp