OrcaSlicer: src/minilzo/minilzo.c File Reference
minilzo.c File Reference
#include <limits.h>
#include <stddef.h>
#include "minilzo.h"
#include <string.h>
#include <assert.h>
Classes
struct lzo_memops_TU2_struct
struct lzo_memops_TU4_struct
struct lzo_memops_TU8_struct
union lzo_config_check_union
Macros
#define __LZO_IN_MINILZO 1
#define __LZO_CONF_H 1
#define __LZO_NOEXPORT1 /*empty*/
#define __LZO_NOEXPORT2 /*empty*/
#define LZO_PUBLIC_DECL(r) LZO_EXTERN(r)
#define LZO_PUBLIC_IMPL(r) LZO_PUBLIC(r)
#define LZO_LOCAL_DECL(r) __LZO_EXTERN_C LZO_LOCAL_IMPL(r)
#define LZO_LOCAL_IMPL(r) __LZO_NOEXPORT1 r __LZO_NOEXPORT2 __LZO_CDECL
#define LZO_STATIC_DECL(r) LZO_PRIVATE(r)
#define LZO_STATIC_IMPL(r) LZO_PRIVATE(r)
#define HAVE_STRING_H 1
#define HAVE_MEMCMP 1
#define HAVE_MEMCPY 1
#define HAVE_MEMMOVE 1
#define HAVE_MEMSET 1
#define memcmp(a, b, c) lzo_memcmp(a,b,c)
#define memcpy(a, b, c) lzo_memcpy(a,b,c)
#define memmove(a, b, c) lzo_memmove(a,b,c)
#define memset(a, b, c) lzo_memset(a,b,c)
#define NDEBUG 1
#define BOUNDS_CHECKING_OFF_DURING(stmt) stmt
#define BOUNDS_CHECKING_OFF_IN_EXPR(expr) (expr)
#define LZO_BYTE(x) ((unsigned char) (x))
#define LZO_MAX(a, b) ((a) >= (b) ? (a) : (b))
#define LZO_MIN(a, b) ((a) <= (b) ? (a) : (b))
#define LZO_MAX3(a, b, c) ((a) >= (b) ? LZO_MAX(a,c) : LZO_MAX(b,c))
#define LZO_MIN3(a, b, c) ((a) <= (b) ? LZO_MIN(a,c) : LZO_MIN(b,c))
#define lzo_sizeof(type) ((lzo_uint) (sizeof(type)))
#define LZO_HIGH(array) ((lzo_uint) (sizeof(array)/sizeof(*(array))))
#define LZO_SIZE(bits) (1u << (bits))
#define LZO_MASK(bits) (LZO_SIZE(bits) - 1)
#define LZO_USIZE(bits) ((lzo_uint) 1 << (bits))
#define LZO_UMASK(bits) (LZO_USIZE(bits) - 1)
#define DMUL(a, b) ((lzo_xint) ((a) * (b)))
#define __LZO_FUNC_H 1
#define lzo_memops_TU0p void __LZO_MMODEL *
#define lzo_memops_TU1p unsigned char __LZO_MMODEL *
#define lzo_memops_TU2p lzo_memops_TU2 *
#define lzo_memops_TU4p lzo_memops_TU4 __LZO_MMODEL *
#define lzo_memops_TU8p lzo_memops_TU8 __LZO_MMODEL *
#define lzo_memops_set_TU1p volatile lzo_memops_TU1p
#define lzo_memops_move_TU1p lzo_memops_TU1p
#define LZO_MEMOPS_SET1(dd, cc)
#define LZO_MEMOPS_SET2(dd, cc)
#define LZO_MEMOPS_SET3(dd, cc)
#define LZO_MEMOPS_SET4(dd, cc)
#define LZO_MEMOPS_MOVE1(dd, ss)
#define LZO_MEMOPS_MOVE2(dd, ss)
#define LZO_MEMOPS_MOVE3(dd, ss)
#define LZO_MEMOPS_MOVE4(dd, ss)
#define LZO_MEMOPS_MOVE8(dd, ss)
#define LZO_MEMOPS_COPY1(dd, ss) LZO_MEMOPS_MOVE1(dd,ss)
#define LZO_MEMOPS_COPY2(dd, ss) LZO_MEMOPS_MOVE2(dd,ss)
#define LZO_MEMOPS_COPY4(dd, ss) LZO_MEMOPS_MOVE4(dd,ss)
#define LZO_MEMOPS_COPY8(dd, ss) LZO_BLOCK_BEGIN LZO_MEMOPS_COPY4(dd,ss); LZO_MEMOPS_COPY4((lzo_memops_TU1p)(lzo_memops_TU0p)(dd)+4,(const lzo_memops_TU1p)(const lzo_memops_TU0p)(ss)+4); LZO_BLOCK_END
#define LZO_MEMOPS_COPYN(dd, ss, nn)
#define LZO_MEMOPS_GET_LE16(ss) lzo_memops_get_le16(ss)
#define LZO_MEMOPS_GET_LE32(ss) lzo_memops_get_le32(ss)
#define LZO_MEMOPS_GET_NE16(ss) lzo_memops_get_ne16(ss)
#define LZO_MEMOPS_GET_NE32(ss) lzo_memops_get_ne32(ss)
#define LZO_MEMOPS_PUT_LE16(dd, vv) lzo_memops_put_le16(dd,vv)
#define LZO_MEMOPS_PUT_LE32(dd, vv) lzo_memops_put_le32(dd,vv)
#define LZO_MEMOPS_PUT_NE16(dd, vv) lzo_memops_put_ne16(dd,vv)
#define LZO_MEMOPS_PUT_NE32(dd, vv) lzo_memops_put_ne32(dd,vv)
#define UA_SET1 LZO_MEMOPS_SET1
#define UA_SET2 LZO_MEMOPS_SET2
#define UA_SET3 LZO_MEMOPS_SET3
#define UA_SET4 LZO_MEMOPS_SET4
#define UA_MOVE1 LZO_MEMOPS_MOVE1
#define UA_MOVE2 LZO_MEMOPS_MOVE2
#define UA_MOVE3 LZO_MEMOPS_MOVE3
#define UA_MOVE4 LZO_MEMOPS_MOVE4
#define UA_MOVE8 LZO_MEMOPS_MOVE8
#define UA_COPY1 LZO_MEMOPS_COPY1
#define UA_COPY2 LZO_MEMOPS_COPY2
#define UA_COPY3 LZO_MEMOPS_COPY3
#define UA_COPY4 LZO_MEMOPS_COPY4
#define UA_COPY8 LZO_MEMOPS_COPY8
#define UA_COPYN LZO_MEMOPS_COPYN
#define UA_COPYN_X LZO_MEMOPS_COPYN
#define UA_GET_LE16 LZO_MEMOPS_GET_LE16
#define UA_GET_LE32 LZO_MEMOPS_GET_LE32
#define UA_GET_NE16 LZO_MEMOPS_GET_NE16
#define UA_GET_NE32 LZO_MEMOPS_GET_NE32
#define UA_PUT_LE16 LZO_MEMOPS_PUT_LE16
#define UA_PUT_LE32 LZO_MEMOPS_PUT_LE32
#define UA_PUT_NE16 LZO_MEMOPS_PUT_NE16
#define UA_PUT_NE32 LZO_MEMOPS_PUT_NE32
#define MEMCPY8_DS(dest, src, len) lzo_memcpy(dest,src,len); dest += len; src += len
#define BZERO8_PTR(s, l, n) lzo_memset((lzo_voidp)(s),0,(lzo_uint)(l)*(n))
#define MEMCPY_DS(dest, src, len) do *dest++ = *src++; while (--len > 0)
#define __LZO_PTR_H 1
#define PTR(a) ((lzo_uintptr_t) (a))
#define PTR_LINEAR(a) PTR(a)
#define PTR_ALIGNED_4(a) ((PTR_LINEAR(a) & 3) == 0)
#define PTR_ALIGNED_8(a) ((PTR_LINEAR(a) & 7) == 0)
#define PTR_ALIGNED2_4(a, b) (((PTR_LINEAR(a) | PTR_LINEAR(b)) & 3) == 0)
#define PTR_ALIGNED2_8(a, b) (((PTR_LINEAR(a) | PTR_LINEAR(b)) & 7) == 0)
#define PTR_LT(a, b) (PTR(a) < PTR(b))
#define PTR_GE(a, b) (PTR(a) >= PTR(b))
#define PTR_DIFF(a, b) (PTR(a) - PTR(b))
#define pd(a, b) ((lzo_uint) ((a)-(b)))
#define LZO_DETERMINISTIC 1
#define LZO_DICT_USE_PTR 1
#define lzo_dict_t lzo_uint
#define lzo_dict_p lzo_dict_t *
#define LZO_BASE 65521u
#define LZO_NMAX 5552
#define LZO_DO1(buf, i) s1 += buf[i]; s2 += s1
#define LZO_DO2(buf, i) LZO_DO1(buf,i); LZO_DO1(buf,i+1)
#define LZO_DO4(buf, i) LZO_DO2(buf,i); LZO_DO2(buf,i+2)
#define LZO_DO8(buf, i) LZO_DO4(buf,i); LZO_DO4(buf,i+4)
#define LZO_DO16(buf, i) LZO_DO8(buf,i); LZO_DO8(buf,i+8)
#define lzo_hsize_t lzo_uint
#define lzo_hvoid_p lzo_voidp
#define lzo_hbyte_p lzo_bytep
#define LZOLIB_PUBLIC(r, f) LZO_PUBLIC(r) f
#define lzo_hmemcmp lzo_memcmp
#define lzo_hmemcpy lzo_memcpy
#define lzo_hmemmove lzo_memmove
#define lzo_hmemset lzo_memset
#define __LZOLIB_HMEMCPY_CH_INCLUDED 1
#define LZO1X 1
#define LZO_EOF_CODE 1
#define M2_MAX_OFFSET 0x0800
#define LZO_DICT_USE_PTR 0
#define lzo_dict_t lzo_uint16_t
#define LZO_NEED_DICT_H 1
#define D_BITS 14
#define D_INDEX1(d, p) d = DM(DMUL(0x21,DX3(p,5,5,6)) >> 5)
#define D_INDEX2(d, p) d = (d & (D_MASK & 0x7ff)) ^ (D_HIGH | 0x1f)
#define DINDEX(dv, p) DM(((DMUL(0x1824429d,dv)) >> (32-D_BITS)))
#define __LZO_CONFIG1X_H 1
#define M1_MAX_OFFSET 0x0400
#define M3_MAX_OFFSET 0x4000
#define M4_MAX_OFFSET 0xbfff
#define MX_MAX_OFFSET (M1_MAX_OFFSET + M2_MAX_OFFSET)
#define M1_MIN_LEN 2
#define M1_MAX_LEN 2
#define M2_MIN_LEN 3
#define M2_MAX_LEN 8
#define M3_MIN_LEN 3
#define M3_MAX_LEN 33
#define M4_MIN_LEN 3
#define M4_MAX_LEN 9
#define M1_MARKER 0
#define M2_MARKER 64
#define M3_MARKER 32
#define M4_MARKER 16
#define MIN_LOOKAHEAD (M2_MAX_LEN + 1)
#define LZO_HASH LZO_HASH_LZO_INCREMENTAL_B
#define DL_MIN_LEN M2_MIN_LEN
#define __LZO_DICT_H 1
#define D_SIZE LZO_SIZE(D_BITS)
#define D_MASK LZO_MASK(D_BITS)
#define D_HIGH ((D_MASK >> 1) + 1)
#define DD_BITS 0
#define DD_SIZE LZO_SIZE(DD_BITS)
#define DD_MASK LZO_MASK(DD_BITS)
#define DL_BITS (D_BITS - DD_BITS)
#define DL_SIZE LZO_SIZE(DL_BITS)
#define DL_MASK LZO_MASK(DL_BITS)
#define DL_SHIFT ((DL_BITS + (DL_MIN_LEN - 1)) / DL_MIN_LEN)
#define LZO_HASH_GZIP 1
#define LZO_HASH_GZIP_INCREMENTAL 2
#define LZO_HASH_LZO_INCREMENTAL_A 3
#define LZO_HASH_LZO_INCREMENTAL_B 4
#define _DV_A(p, shift) _DV2_A(p,shift,shift)
#define _DV_B(p, shift) _DV2_B(p,shift,shift)
#define DA2(p, s1, s2) (((((lzo_xint)((p)[2]) << (s2)) + (p)[1]) << (s1)) + (p)[0])
#define DS2(p, s1, s2) (((((lzo_xint)((p)[2]) << (s2)) - (p)[1]) << (s1)) - (p)[0])
#define DX2(p, s1, s2) (((((lzo_xint)((p)[2]) << (s2)) ^ (p)[1]) << (s1)) ^ (p)[0])
#define DA3(p, s1, s2, s3) ((DA2((p)+1,s2,s3) << (s1)) + (p)[0])
#define DS3(p, s1, s2, s3) ((DS2((p)+1,s2,s3) << (s1)) - (p)[0])
#define DX3(p, s1, s2, s3) ((DX2((p)+1,s2,s3) << (s1)) ^ (p)[0])
#define DMS(v, s) ((lzo_uint) (((v) & (D_MASK >> (s))) << (s)))
#define DM(v) DMS(v,0)
#define _DINDEX(dv, p) (_DV_A((p),DL_SHIFT))
#define DINDEX1 D_INDEX1
#define DINDEX2 D_INDEX2
#define DVAL_FIRST(dv, p) ((void) 0)
#define DVAL_NEXT(dv, p) ((void) 0)
#define DVAL_LOOKAHEAD 0
#define DVAL_ASSERT(dv, p) ((void) 0)
#define DENTRY(p, in) ((lzo_dict_t) pd(p, in))
#define GINDEX(m_pos, m_off, dict, dindex, in) m_off = dict[dindex]
#define UPDATE_D(dict, drun, dv, p, in) dict[ DINDEX(dv,p) ] = DENTRY(p,in)
#define UPDATE_I(dict, drun, index, p, in) dict[index] = DENTRY(p,in)
#define UPDATE_P(ptr, drun, p, in) (ptr)[0] = DENTRY(p,in)
#define LZO_CHECK_MPOS_DET(m_pos, m_off, in, ip, max_offset)
#define LZO_CHECK_MPOS_NON_DET(m_pos, m_off, in, ip, max_offset)
#define LZO_CHECK_MPOS LZO_CHECK_MPOS_NON_DET
#define LZO_DETERMINISTIC !(LZO_DICT_USE_PTR)
#define DO_COMPRESS lzo1x_1_compress
#define do_compress LZO_PP_ECONCAT2(DO_COMPRESS,_core)
#define DO_DECOMPRESS lzo1x_decompress
#define TEST_LB(m_pos) ((void) 0)
#define TEST_LBO(m_pos, o) ((void) 0)
#define TEST_IP 1
#define TEST_OP 1
#define TEST_IP_AND_TEST_OP 1
#define NEED_IP(x) ((void) 0)
#define TEST_IV(x) ((void) 0)
#define NEED_OP(x) ((void) 0)
#define TEST_OV(x) ((void) 0)
#define LZO_TEST_OVERRUN 1
#define DO_DECOMPRESS lzo1x_decompress_safe
#define LZO_TEST_OVERRUN_INPUT 2
#define LZO_TEST_OVERRUN_OUTPUT 2
#define LZO_TEST_OVERRUN_LOOKBEHIND 1
#define TEST_LB(m_pos) if (PTR_LT(m_pos,out) || PTR_GE(m_pos,op)) goto lookbehind_overrun
#define TEST_LBO(m_pos, o) if (PTR_LT(m_pos,out) || PTR_GE(m_pos,op-(o))) goto lookbehind_overrun
#define TEST_IP 1
#define TEST_OP 1
#define TEST_IP_AND_TEST_OP 1
#define NEED_IP(x) ((void) 0)
#define TEST_IV(x) ((void) 0)
#define NEED_OP(x) ((void) 0)
#define TEST_OV(x) ((void) 0)
Typedefs
typedef struct lzo_memops_TU2_struct lzo_memops_TU2
typedef struct lzo_memops_TU4_struct lzo_memops_TU4
typedef struct lzo_memops_TU8_struct lzo_memops_TU8
Functions
__lzo_static_forceinline unsigned lzo_bitops_ctlz32_func (lzo_uint32_t v)
__lzo_static_forceinline unsigned lzo_bitops_cttz32_func (lzo_uint32_t v)
lzo_unused_funcs_impl (void, lzo_bitops_unused_funcs)
LZO_COMPILE_TIME_ASSERT_HEADER (sizeof(*(lzo_memops_TU1p) 0)==1)
__lzo_static_forceinline lzo_uint32_t lzo_memops_get_le32 (const lzo_voidp ss)
__lzo_static_forceinline lzo_uint16_t lzo_memops_get_ne16 (const lzo_voidp ss)
__lzo_static_forceinline lzo_uint32_t lzo_memops_get_ne32 (const lzo_voidp ss)
__lzo_static_forceinline void lzo_memops_put_le16 (lzo_voidp dd, lzo_uint16_t vv)
__lzo_static_forceinline void lzo_memops_put_le32 (lzo_voidp dd, lzo_uint32_t vv)
__lzo_static_forceinline void lzo_memops_put_ne16 (lzo_voidp dd, lzo_uint16_t vv)
__lzo_static_forceinline void lzo_memops_put_ne32 (lzo_voidp dd, lzo_uint32_t vv)
lzo_unused_funcs_impl (void, lzo_memops_unused_funcs)
LZO_EXTERN (const lzo_bytep)
__lzo_ptr_linear (const lzo_voidp ptr)
__lzo_align_gap (const lzo_voidp ptr, lzo_uint size)
lzo_copyright (void)
lzo_version (void)
lzo_version_string (void)
lzo_version_date (void)
_lzo_version_string (void)
_lzo_version_date (void)
lzo_adler32 (lzo_uint32_t adler, const lzo_bytep buf, lzo_uint len)
LZOLIB_PUBLIC (int, lzo_hmemcmp) const
LZOLIB_PUBLIC (lzo_hvoid_p, lzo_hmemcpy)
LZOLIB_PUBLIC (lzo_hvoid_p, lzo_hmemmove)
LZOLIB_PUBLIC (lzo_hvoid_p, lzo_hmemset)
static __lzo_noinline lzo_voidp u2p (lzo_voidp ptr, lzo_uint off)
_lzo_config_check (void)
__lzo_init_v2 (unsigned v, int s1, int s2, int s3, int s4, int s5, int s6, int s7, int s8, int s9)
static __lzo_noinline lzo_uint do_compress (const lzo_bytep in, lzo_uint in_len, lzo_bytep out, lzo_uintp out_len, lzo_uint ti, lzo_voidp wrkmem)
DO_COMPRESS (const lzo_bytep in, lzo_uint in_len, lzo_bytep out, lzo_uintp out_len, lzo_voidp wrkmem)
DO_DECOMPRESS (const lzo_bytep in, lzo_uint in_len, lzo_bytep out, lzo_uintp out_len, lzo_voidp wrkmem)
Variables
struct lzo_memops_TU2_struct __lzo_may_alias
lzo_full_align_t
static const char lzo_copyright_ []
static const char lzo_version_string_ [] = LZO_VERSION_STRING
static const char lzo_version_date_ [] = LZO_VERSION_DATE
Class Documentation
lzo_memops_TU2_struct
struct lzo_memops_TU2_struct
Class Members
unsigned char a[2]
lzo_memops_TU4_struct
struct lzo_memops_TU4_struct
Class Members
unsigned char a[4]
lzo_memops_TU8_struct
struct lzo_memops_TU8_struct
Class Members
unsigned char a[8]
lzo_config_check_union
union lzo_config_check_union
Class Members
lzo_uint a[2]
unsigned char b[2 *LZO_MAX(8, sizeof(lzo_uint))]
Macro Definition Documentation
__LZO_CONF_H
#define __LZO_CONF_H 1
__LZO_CONFIG1X_H
#define __LZO_CONFIG1X_H 1
__LZO_DICT_H
#define __LZO_DICT_H 1
__LZO_FUNC_H
#define __LZO_FUNC_H 1
__LZO_IN_MINILZO
#define __LZO_IN_MINILZO 1
__LZO_NOEXPORT1
#define __LZO_NOEXPORT1 /*empty*/
__LZO_NOEXPORT2
#define __LZO_NOEXPORT2 /*empty*/
__LZO_PTR_H
#define __LZO_PTR_H 1
__LZOLIB_HMEMCPY_CH_INCLUDED
#define __LZOLIB_HMEMCPY_CH_INCLUDED 1
_DINDEX
#define _DINDEX (dv, p) (_DV_A((p),DL_SHIFT))
_DV_A
#define _DV_A (p, shift) _DV2_A(p,shift,shift)
_DV_B
#define _DV_B (p, shift) _DV2_B(p,shift,shift)
BOUNDS_CHECKING_OFF_DURING
#define BOUNDS_CHECKING_OFF_DURING (stmt) stmt
BOUNDS_CHECKING_OFF_IN_EXPR
#define BOUNDS_CHECKING_OFF_IN_EXPR (expr) (expr)
BZERO8_PTR
#define BZERO8_PTR (s, l, n) lzo_memset((lzo_voidp)(s),0,(lzo_uint)(l)*(n))
D_BITS
#define D_BITS 14
D_HIGH
#define D_HIGH ((D_MASK >> 1) + 1)
D_INDEX1
#define D_INDEX1 (d, p) d = DM(DMUL(0x21,DX3(p,5,5,6)) >> 5)
D_INDEX2
#define D_INDEX2 (d, p) d = (d & (D_MASK & 0x7ff)) ^ (D_HIGH | 0x1f)
D_MASK
#define D_MASK LZO_MASK(D_BITS)
D_SIZE
#define D_SIZE LZO_SIZE(D_BITS)
DA2
#define DA2 (p, s1, s2) (((((lzo_xint)((p)[2]) << (s2)) + (p)[1]) << (s1)) + (p)[0])
DA3
#define DA3 (p, s1, s2, s3) ((DA2((p)+1,s2,s3) << (s1)) + (p)[0])
DD_BITS
#define DD_BITS 0
DD_MASK
#define DD_MASK LZO_MASK(DD_BITS)
DD_SIZE
#define DD_SIZE LZO_SIZE(DD_BITS)
DENTRY
#define DENTRY (p, in) ((lzo_dict_t) pd(p, in))
DINDEX
#define DINDEX (dv, p) DM(((DMUL(0x1824429d,dv)) >> (32-D_BITS)))
DINDEX1
#define DINDEX1 D_INDEX1
DINDEX2
#define DINDEX2 D_INDEX2
DL_BITS
#define DL_BITS (D_BITS - DD_BITS)
DL_MASK
#define DL_MASK LZO_MASK(DL_BITS)
DL_MIN_LEN
#define DL_MIN_LEN M2_MIN_LEN
DL_SHIFT
#define DL_SHIFT ((DL_BITS + (DL_MIN_LEN - 1)) / DL_MIN_LEN)
DL_SIZE
#define DL_SIZE LZO_SIZE(DL_BITS)
DM
#define DM (v) DMS(v,0)
DMS
#define DMS (v, s) ((lzo_uint) (((v) & (D_MASK >> (s))) << (s)))
DMUL
#define DMUL (a, b) ((lzo_xint) ((a) * (b)))
DO_COMPRESS
#define DO_COMPRESS lzo1x_1_compress
do_compress
#define do_compress LZO_PP_ECONCAT2(DO_COMPRESS,_core)
DO_DECOMPRESS [1/2]
#define DO_DECOMPRESS lzo1x_decompress
DO_DECOMPRESS [2/2]
#define DO_DECOMPRESS lzo1x_decompress_safe
DS2
#define DS2 (p, s1, s2) (((((lzo_xint)((p)[2]) << (s2)) - (p)[1]) << (s1)) - (p)[0])
DS3
#define DS3 (p, s1, s2, s3) ((DS2((p)+1,s2,s3) << (s1)) - (p)[0])
DVAL_ASSERT
#define DVAL_ASSERT (dv, p) ((void) 0)
DVAL_FIRST
#define DVAL_FIRST (dv, p) ((void) 0)
DVAL_LOOKAHEAD
#define DVAL_LOOKAHEAD 0
DVAL_NEXT
#define DVAL_NEXT (dv, p) ((void) 0)
DX2
#define DX2 (p, s1, s2) (((((lzo_xint)((p)[2]) << (s2)) ^ (p)[1]) << (s1)) ^ (p)[0])
DX3
#define DX3 (p, s1, s2, s3) ((DX2((p)+1,s2,s3) << (s1)) ^ (p)[0])
GINDEX
#define GINDEX (m_pos, m_off, dict, dindex, in) m_off = dict[dindex]
HAVE_MEMCMP
#define HAVE_MEMCMP 1
HAVE_MEMCPY
#define HAVE_MEMCPY 1
HAVE_MEMMOVE
#define HAVE_MEMMOVE 1
HAVE_MEMSET
#define HAVE_MEMSET 1
HAVE_STRING_H
#define HAVE_STRING_H 1
LZO1X
#define LZO1X 1
LZO_BASE
#define LZO_BASE 65521u
LZO_BYTE
#define LZO_BYTE (x) ((unsigned char) (x))
LZO_CHECK_MPOS
#define LZO_CHECK_MPOS LZO_CHECK_MPOS_NON_DET
LZO_CHECK_MPOS_DET
#define LZO_CHECK_MPOS_DET (m_pos, m_off, in, ip, max_offset)
Value:
        (m_off == 0 || \
         ((m_off = pd(ip, in) - m_off) > max_offset) || \
         (m_pos = (ip) - (m_off), 0) )
LZO_CHECK_MPOS_NON_DET
#define LZO_CHECK_MPOS_NON_DET (m_pos, m_off, in, ip, max_offset)
Value:
        (pd(ip, in) <= m_off || \
         ((m_off = pd(ip, in) - m_off) > max_offset) || \
         (m_pos = (ip) - (m_off), 0) )
LZO_DETERMINISTIC [1/2]
#define LZO_DETERMINISTIC 1
LZO_DETERMINISTIC [2/2]
#define LZO_DETERMINISTIC !(LZO_DICT_USE_PTR)
lzo_dict_p
#define lzo_dict_p lzo_dict_t *
lzo_dict_t [1/2]
#define lzo_dict_t lzo_uint
lzo_dict_t [2/2]
#define lzo_dict_t lzo_uint16_t
LZO_DICT_USE_PTR [1/2]
#define LZO_DICT_USE_PTR 1
LZO_DICT_USE_PTR [2/2]
#define LZO_DICT_USE_PTR 0
LZO_DO1
#define LZO_DO1 (buf, i) s1 += buf[i]; s2 += s1
LZO_DO16
#define LZO_DO16 (buf, i) LZO_DO8(buf,i); LZO_DO8(buf,i+8)
LZO_DO2
#define LZO_DO2 (buf, i) LZO_DO1(buf,i); LZO_DO1(buf,i+1)
LZO_DO4
#define LZO_DO4 (buf, i) LZO_DO2(buf,i); LZO_DO2(buf,i+2)
LZO_DO8
#define LZO_DO8 (buf, i) LZO_DO4(buf,i); LZO_DO4(buf,i+4)
LZO_EOF_CODE
#define LZO_EOF_CODE 1
LZO_HASH
#define LZO_HASH LZO_HASH_LZO_INCREMENTAL_B
LZO_HASH_GZIP
#define LZO_HASH_GZIP 1
LZO_HASH_GZIP_INCREMENTAL
#define LZO_HASH_GZIP_INCREMENTAL 2
LZO_HASH_LZO_INCREMENTAL_A
#define LZO_HASH_LZO_INCREMENTAL_A 3
LZO_HASH_LZO_INCREMENTAL_B
#define LZO_HASH_LZO_INCREMENTAL_B 4
lzo_hbyte_p
#define lzo_hbyte_p lzo_bytep
LZO_HIGH
#define LZO_HIGH (array) ((lzo_uint) (sizeof(array)/sizeof(*(array))))
lzo_hmemcmp
#define lzo_hmemcmp lzo_memcmp
lzo_hmemcpy
#define lzo_hmemcpy lzo_memcpy
lzo_hmemmove
#define lzo_hmemmove lzo_memmove
lzo_hmemset
#define lzo_hmemset lzo_memset
lzo_hsize_t
#define lzo_hsize_t lzo_uint
lzo_hvoid_p
#define lzo_hvoid_p lzo_voidp
LZO_LOCAL_DECL
#define LZO_LOCAL_DECL (r) __LZO_EXTERN_C LZO_LOCAL_IMPL(r)
LZO_LOCAL_IMPL
#define LZO_LOCAL_IMPL (r) __LZO_NOEXPORT1 r __LZO_NOEXPORT2 __LZO_CDECL
LZO_MASK
#define LZO_MASK (bits) (LZO_SIZE(bits) - 1)
LZO_MAX
#define LZO_MAX (a, b) ((a) >= (b) ? (a) : (b))
LZO_MAX3
#define LZO_MAX3 (a, b, c) ((a) >= (b) ? LZO_MAX(a,c) : LZO_MAX(b,c))
LZO_MEMOPS_COPY1
#define LZO_MEMOPS_COPY1 (dd, ss) LZO_MEMOPS_MOVE1(dd,ss)
LZO_MEMOPS_COPY2
#define LZO_MEMOPS_COPY2 (dd, ss) LZO_MEMOPS_MOVE2(dd,ss)
LZO_MEMOPS_COPY4
#define LZO_MEMOPS_COPY4 (dd, ss) LZO_MEMOPS_MOVE4(dd,ss)
LZO_MEMOPS_COPY8
#define LZO_MEMOPS_COPY8 (dd, ss) LZO_BLOCK_BEGIN LZO_MEMOPS_COPY4(dd,ss); LZO_MEMOPS_COPY4((lzo_memops_TU1p)(lzo_memops_TU0p)(dd)+4,(const lzo_memops_TU1p)(const lzo_memops_TU0p)(ss)+4); LZO_BLOCK_END
LZO_MEMOPS_COPYN
#define LZO_MEMOPS_COPYN (dd, ss, nn)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_TU1p d__n = (lzo_memops_TU1p) (lzo_memops_TU0p) (dd); \
    const lzo_memops_TU1p s__n = (const lzo_memops_TU1p) (const lzo_memops_TU0p) (ss); \
    lzo_uint n__n = (nn); \
    while ((void)0, n__n >= 8) { LZO_MEMOPS_COPY8(d__n, s__n); d__n += 8; s__n += 8; n__n -= 8; } \
    if ((void)0, n__n >= 4) { LZO_MEMOPS_COPY4(d__n, s__n); d__n += 4; s__n += 4; n__n -= 4; } \
    if ((void)0, n__n > 0) do { *d__n++ = *s__n++; } while (--n__n > 0); \
    LZO_BLOCK_END
LZO_MEMOPS_GET_LE16
#define LZO_MEMOPS_GET_LE16 (ss) lzo_memops_get_le16(ss)
LZO_MEMOPS_GET_LE32
#define LZO_MEMOPS_GET_LE32 (ss) lzo_memops_get_le32(ss)
LZO_MEMOPS_GET_NE16
#define LZO_MEMOPS_GET_NE16 (ss) lzo_memops_get_ne16(ss)
LZO_MEMOPS_GET_NE32
#define LZO_MEMOPS_GET_NE32 (ss) lzo_memops_get_ne32(ss)
LZO_MEMOPS_MOVE1
#define LZO_MEMOPS_MOVE1 (dd, ss)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_move_TU1p d__1 = (lzo_memops_move_TU1p) (lzo_memops_TU0p) (dd); \
    const lzo_memops_move_TU1p s__1 = (const lzo_memops_move_TU1p) (const lzo_memops_TU0p) (ss); \
    d__1[0] = s__1[0]; \
    LZO_BLOCK_END
LZO_MEMOPS_MOVE2
#define LZO_MEMOPS_MOVE2 (dd, ss)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_move_TU1p d__2 = (lzo_memops_move_TU1p) (lzo_memops_TU0p) (dd); \
    const lzo_memops_move_TU1p s__2 = (const lzo_memops_move_TU1p) (const lzo_memops_TU0p) (ss); \
    d__2[0] = s__2[0]; d__2[1] = s__2[1]; \
    LZO_BLOCK_END
LZO_MEMOPS_MOVE3
#define LZO_MEMOPS_MOVE3 (dd, ss)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_move_TU1p d__3 = (lzo_memops_move_TU1p) (lzo_memops_TU0p) (dd); \
    const lzo_memops_move_TU1p s__3 = (const lzo_memops_move_TU1p) (const lzo_memops_TU0p) (ss); \
    d__3[0] = s__3[0]; d__3[1] = s__3[1]; d__3[2] = s__3[2]; \
    LZO_BLOCK_END
LZO_MEMOPS_MOVE4
#define LZO_MEMOPS_MOVE4 (dd, ss)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_move_TU1p d__4 = (lzo_memops_move_TU1p) (lzo_memops_TU0p) (dd); \
    const lzo_memops_move_TU1p s__4 = (const lzo_memops_move_TU1p) (const lzo_memops_TU0p) (ss); \
    d__4[0] = s__4[0]; d__4[1] = s__4[1]; d__4[2] = s__4[2]; d__4[3] = s__4[3]; \
    LZO_BLOCK_END
LZO_MEMOPS_MOVE8
#define LZO_MEMOPS_MOVE8 (dd, ss)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_move_TU1p d__8 = (lzo_memops_move_TU1p) (lzo_memops_TU0p) (dd); \
    const lzo_memops_move_TU1p s__8 = (const lzo_memops_move_TU1p) (const lzo_memops_TU0p) (ss); \
    d__8[0] = s__8[0]; d__8[1] = s__8[1]; d__8[2] = s__8[2]; d__8[3] = s__8[3]; \
    d__8[4] = s__8[4]; d__8[5] = s__8[5]; d__8[6] = s__8[6]; d__8[7] = s__8[7]; \
    LZO_BLOCK_END
lzo_memops_move_TU1p
#define lzo_memops_move_TU1p lzo_memops_TU1p
LZO_MEMOPS_PUT_LE16
#define LZO_MEMOPS_PUT_LE16 (dd, vv) lzo_memops_put_le16(dd,vv)
LZO_MEMOPS_PUT_LE32
#define LZO_MEMOPS_PUT_LE32 (dd, vv) lzo_memops_put_le32(dd,vv)
LZO_MEMOPS_PUT_NE16
#define LZO_MEMOPS_PUT_NE16 (dd, vv) lzo_memops_put_ne16(dd,vv)
LZO_MEMOPS_PUT_NE32
#define LZO_MEMOPS_PUT_NE32 (dd, vv) lzo_memops_put_ne32(dd,vv)
LZO_MEMOPS_SET1
#define LZO_MEMOPS_SET1 (dd, cc)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_set_TU1p d__1 = (lzo_memops_set_TU1p) (lzo_memops_TU0p) (dd); \
    d__1[0] = LZO_BYTE(cc); \
    LZO_BLOCK_END
LZO_MEMOPS_SET2
#define LZO_MEMOPS_SET2 (dd, cc)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_set_TU1p d__2 = (lzo_memops_set_TU1p) (lzo_memops_TU0p) (dd); \
    d__2[0] = LZO_BYTE(cc); d__2[1] = LZO_BYTE(cc); \
    LZO_BLOCK_END
LZO_MEMOPS_SET3
#define LZO_MEMOPS_SET3 (dd, cc)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_set_TU1p d__3 = (lzo_memops_set_TU1p) (lzo_memops_TU0p) (dd); \
    d__3[0] = LZO_BYTE(cc); d__3[1] = LZO_BYTE(cc); d__3[2] = LZO_BYTE(cc); \
    LZO_BLOCK_END
LZO_MEMOPS_SET4
#define LZO_MEMOPS_SET4 (dd, cc)
Value:
    LZO_BLOCK_BEGIN \
    lzo_memops_set_TU1p d__4 = (lzo_memops_set_TU1p) (lzo_memops_TU0p) (dd); \
    d__4[0] = LZO_BYTE(cc); d__4[1] = LZO_BYTE(cc); d__4[2] = LZO_BYTE(cc); d__4[3] = LZO_BYTE(cc); \
    LZO_BLOCK_END
lzo_memops_set_TU1p
#define lzo_memops_set_TU1p volatile lzo_memops_TU1p
lzo_memops_TU0p
#define lzo_memops_TU0p void __LZO_MMODEL *
lzo_memops_TU1p
#define lzo_memops_TU1p unsigned char __LZO_MMODEL *
lzo_memops_TU2p
#define lzo_memops_TU2p lzo_memops_TU2 *
lzo_memops_TU4p
#define lzo_memops_TU4p lzo_memops_TU4 __LZO_MMODEL *
lzo_memops_TU8p
#define lzo_memops_TU8p lzo_memops_TU8 __LZO_MMODEL *
LZO_MIN
#define LZO_MIN (a, b) ((a) <= (b) ? (a) : (b))
LZO_MIN3
#define LZO_MIN3 (a, b, c) ((a) <= (b) ? LZO_MIN(a,c) : LZO_MIN(b,c))
LZO_NEED_DICT_H
#define LZO_NEED_DICT_H 1
LZO_NMAX
#define LZO_NMAX 5552
LZO_PUBLIC_DECL
#define LZO_PUBLIC_DECL (r) LZO_EXTERN(r)
LZO_PUBLIC_IMPL
#define LZO_PUBLIC_IMPL (r) LZO_PUBLIC(r)
LZO_SIZE
#define LZO_SIZE (bits) (1u << (bits))
lzo_sizeof
#define lzo_sizeof (type) ((lzo_uint) (sizeof(type)))
LZO_STATIC_DECL
#define LZO_STATIC_DECL (r) LZO_PRIVATE(r)
LZO_STATIC_IMPL
#define LZO_STATIC_IMPL (r) LZO_PRIVATE(r)
LZO_TEST_OVERRUN
#define LZO_TEST_OVERRUN 1
LZO_TEST_OVERRUN_INPUT
#define LZO_TEST_OVERRUN_INPUT 2
LZO_TEST_OVERRUN_LOOKBEHIND
#define LZO_TEST_OVERRUN_LOOKBEHIND 1
LZO_TEST_OVERRUN_OUTPUT
#define LZO_TEST_OVERRUN_OUTPUT 2
LZO_UMASK
#define LZO_UMASK (bits) (LZO_USIZE(bits) - 1)
LZO_USIZE
#define LZO_USIZE (bits) ((lzo_uint) 1 << (bits))
LZOLIB_PUBLIC
#define LZOLIB_PUBLIC (r, f) LZO_PUBLIC(r) f
M1_MARKER
#define M1_MARKER 0
M1_MAX_LEN
#define M1_MAX_LEN 2
M1_MAX_OFFSET
#define M1_MAX_OFFSET 0x0400
M1_MIN_LEN
#define M1_MIN_LEN 2
M2_MARKER
#define M2_MARKER 64
M2_MAX_LEN
#define M2_MAX_LEN 8
M2_MAX_OFFSET
#define M2_MAX_OFFSET 0x0800
M2_MIN_LEN
#define M2_MIN_LEN 3
M3_MARKER
#define M3_MARKER 32
M3_MAX_LEN
#define M3_MAX_LEN 33
M3_MAX_OFFSET
#define M3_MAX_OFFSET 0x4000
M3_MIN_LEN
#define M3_MIN_LEN 3
M4_MARKER
#define M4_MARKER 16
M4_MAX_LEN
#define M4_MAX_LEN 9
M4_MAX_OFFSET
#define M4_MAX_OFFSET 0xbfff
M4_MIN_LEN
#define M4_MIN_LEN 3
memcmp
#define memcmp (a, b, c) lzo_memcmp(a,b,c)
memcpy
#define memcpy (a, b, c) lzo_memcpy(a,b,c)
MEMCPY8_DS
#define MEMCPY8_DS (dest, src, len) lzo_memcpy(dest,src,len); dest += len; src += len
MEMCPY_DS
#define MEMCPY_DS (dest, src, len) do *dest++ = *src++; while (--len > 0)
memmove
#define memmove (a, b, c) lzo_memmove(a,b,c)
memset
#define memset (a, b, c) lzo_memset(a,b,c)
MIN_LOOKAHEAD
#define MIN_LOOKAHEAD (M2_MAX_LEN + 1)
MX_MAX_OFFSET
#define MX_MAX_OFFSET (M1_MAX_OFFSET + M2_MAX_OFFSET)
NDEBUG
#define NDEBUG 1
NEED_IP [1/2]
#define NEED_IP (x) ((void) 0)
NEED_IP [2/2]
#define NEED_IP (x) ((void) 0)
NEED_OP [1/2]
#define NEED_OP (x) ((void) 0)
NEED_OP [2/2]
#define NEED_OP (x) ((void) 0)
pd
#define pd (a, b) ((lzo_uint) ((a)-(b)))
PTR
#define PTR (a) ((lzo_uintptr_t) (a))
PTR_ALIGNED2_4
#define PTR_ALIGNED2_4 (a, b) (((PTR_LINEAR(a) | PTR_LINEAR(b)) & 3) == 0)
PTR_ALIGNED2_8
#define PTR_ALIGNED2_8 (a, b) (((PTR_LINEAR(a) | PTR_LINEAR(b)) & 7) == 0)
PTR_ALIGNED_4
#define PTR_ALIGNED_4 (a) ((PTR_LINEAR(a) & 3) == 0)
PTR_ALIGNED_8
#define PTR_ALIGNED_8 (a) ((PTR_LINEAR(a) & 7) == 0)
PTR_DIFF
#define PTR_DIFF (a, b) (PTR(a) - PTR(b))
PTR_GE
#define PTR_GE (a, b) (PTR(a) >= PTR(b))
PTR_LINEAR
#define PTR_LINEAR (a) PTR(a)
PTR_LT
#define PTR_LT (a, b) (PTR(a) < PTR(b))
TEST_IP [1/2]
#define TEST_IP 1
TEST_IP [2/2]
#define TEST_IP 1
TEST_IP_AND_TEST_OP [1/2]
#define TEST_IP_AND_TEST_OP 1
TEST_IP_AND_TEST_OP [2/2]
#define TEST_IP_AND_TEST_OP 1
TEST_IV [1/2]
#define TEST_IV (x) ((void) 0)
TEST_IV [2/2]
#define TEST_IV (x) ((void) 0)
TEST_LB [1/2]
#define TEST_LB (m_pos) ((void) 0)
TEST_LB [2/2]
#define TEST_LB (m_pos) if (PTR_LT(m_pos,out) || PTR_GE(m_pos,op)) goto lookbehind_overrun
TEST_LBO [1/2]
#define TEST_LBO (m_pos, o) ((void) 0)
TEST_LBO [2/2]
#define TEST_LBO (m_pos, o) if (PTR_LT(m_pos,out) || PTR_GE(m_pos,op-(o))) goto lookbehind_overrun
TEST_OP [1/2]
#define TEST_OP 1
TEST_OP [2/2]
#define TEST_OP 1
TEST_OV [1/2]
#define TEST_OV (x) ((void) 0)
TEST_OV [2/2]
#define TEST_OV (x) ((void) 0)
UA_COPY1
#define UA_COPY1 LZO_MEMOPS_COPY1
UA_COPY2
#define UA_COPY2 LZO_MEMOPS_COPY2
UA_COPY3
#define UA_COPY3 LZO_MEMOPS_COPY3
UA_COPY4
#define UA_COPY4 LZO_MEMOPS_COPY4
UA_COPY8
#define UA_COPY8 LZO_MEMOPS_COPY8
UA_COPYN
#define UA_COPYN LZO_MEMOPS_COPYN
UA_COPYN_X
#define UA_COPYN_X LZO_MEMOPS_COPYN
UA_GET_LE16
#define UA_GET_LE16 LZO_MEMOPS_GET_LE16
UA_GET_LE32
#define UA_GET_LE32 LZO_MEMOPS_GET_LE32
UA_GET_NE16
#define UA_GET_NE16 LZO_MEMOPS_GET_NE16
UA_GET_NE32
#define UA_GET_NE32 LZO_MEMOPS_GET_NE32
UA_MOVE1
#define UA_MOVE1 LZO_MEMOPS_MOVE1
UA_MOVE2
#define UA_MOVE2 LZO_MEMOPS_MOVE2
UA_MOVE3
#define UA_MOVE3 LZO_MEMOPS_MOVE3
UA_MOVE4
#define UA_MOVE4 LZO_MEMOPS_MOVE4
UA_MOVE8
#define UA_MOVE8 LZO_MEMOPS_MOVE8
UA_PUT_LE16
#define UA_PUT_LE16 LZO_MEMOPS_PUT_LE16
UA_PUT_LE32
#define UA_PUT_LE32 LZO_MEMOPS_PUT_LE32
UA_PUT_NE16
#define UA_PUT_NE16 LZO_MEMOPS_PUT_NE16
UA_PUT_NE32
#define UA_PUT_NE32 LZO_MEMOPS_PUT_NE32
UA_SET1
#define UA_SET1 LZO_MEMOPS_SET1
UA_SET2
#define UA_SET2 LZO_MEMOPS_SET2
UA_SET3
#define UA_SET3 LZO_MEMOPS_SET3
UA_SET4
#define UA_SET4 LZO_MEMOPS_SET4
UPDATE_D
#define UPDATE_D (dict, drun, dv, p, in) dict[ DINDEX(dv,p) ] = DENTRY(p,in)
UPDATE_I
#define UPDATE_I (dict, drun, index, p, in) dict[index] = DENTRY(p,in)
UPDATE_P
#define UPDATE_P (ptr, drun, p, in) (ptr)[0] = DENTRY(p,in)
Typedef Documentation
lzo_memops_TU2
typedef struct lzo_memops_TU2_struct lzo_memops_TU2
lzo_memops_TU4
typedef struct lzo_memops_TU4_struct lzo_memops_TU4
lzo_memops_TU8
typedef struct lzo_memops_TU8_struct lzo_memops_TU8
Function Documentation
__lzo_align_gap()
__lzo_align_gap (const lzo_voidp ptr, lzo_uint size)
{
#if (__LZO_UINTPTR_T_IS_POINTER)
#error "__LZO_UINTPTR_T_IS_POINTER is unsupported"
#else
    lzo_uintptr_t p, n;
    if (size < 2) return 0;
    p = __lzo_ptr_linear(ptr);
#if 0
    n = (((p + size - 1) / size) * size) - p;
#else
    if ((size & (size - 1)) != 0)
        return 0;
    n = size; n = ((p + n - 1) & ~(n - 1)) - p;
#endif
#endif
    assert((long)n >= 0);
    assert(n <= size);
    return (unsigned)n;
}
References __lzo_ptr_linear(), lzo_uintptr_t, n, ptr, and size.
__lzo_init_v2()
__lzo_init_v2 (unsigned v, int s1, int s2, int s3, int s4, int s5, int s6, int s7, int s8, int s9)
{
    int r;
#if defined(__LZO_IN_MINILZO)
#elif (LZO_CC_MSC && ((_MSC_VER) < 700))
#else
#define LZO_WANT_ACC_CHK_CH 1
#undef LZOCHK_ASSERT
#define LZOCHK_ASSERT(expr)  LZO_COMPILE_TIME_ASSERT(expr)
#endif
#undef LZOCHK_ASSERT
    if (v == 0)
        return LZO_E_ERROR;
    r = (s1 == -1 || s1 == (int) sizeof(short)) &&
        (s2 == -1 || s2 == (int) sizeof(int)) &&
        (s3 == -1 || s3 == (int) sizeof(long)) &&
        (s4 == -1 || s4 == (int) sizeof(lzo_uint32_t)) &&
        (s5 == -1 || s5 == (int) sizeof(lzo_uint)) &&
        (s6 == -1 || s6 == (int) lzo_sizeof_dict_t) &&
        (s7 == -1 || s7 == (int) sizeof(char *)) &&
        (s8 == -1 || s8 == (int) sizeof(lzo_voidp)) &&
        (s9 == -1 || s9 == (int) sizeof(lzo_callback_t));
    if (!r)
        return LZO_E_ERROR;
    r = _lzo_config_check();
    if (r != LZO_E_OK)
        return r;
    return r;
}
References _lzo_config_check(), int, LZO_E_ERROR, LZO_E_OK, lzo_sizeof_dict_t, and lzo_voidp.
__lzo_ptr_linear()
__lzo_ptr_linear (const lzo_voidp ptr)
{
    lzo_uintptr_t p;
#if (LZO_ARCH_I086)
#error "LZO_ARCH_I086 is unsupported"
#elif (LZO_MM_PVP)
#error "LZO_MM_PVP is unsupported"
#else
    p = (lzo_uintptr_t) PTR_LINEAR(ptr);
#endif
    return p;
}
References lzo_uintptr_t, ptr, and PTR_LINEAR.
Referenced by __lzo_align_gap().
_lzo_config_check()
_lzo_config_check (void)
{
#if (LZO_CC_CLANG && (LZO_CC_CLANG >= 0x030100ul && LZO_CC_CLANG < 0x030300ul))
# if 0
    volatile
# endif
#endif
    union lzo_config_check_union u;
    lzo_voidp p;
    unsigned r = 1;
    u.a[0] = u.a[1] = 0;
    p = u2p(&u, 0);
    r &= ((* (lzo_bytep) p) == 0);
#if !(LZO_CFG_NO_CONFIG_CHECK)
#if (LZO_ABI_BIG_ENDIAN)
    u.a[0] = u.a[1] = 0; u.b[sizeof(lzo_uint) - 1] = 128;
    p = u2p(&u, 0);
    r &= ((* (lzo_uintp) p) == 128);
#endif
#if (LZO_ABI_LITTLE_ENDIAN)
    u.a[0] = u.a[1] = 0; u.b[0] = 128;
    p = u2p(&u, 0);
    r &= ((* (lzo_uintp) p) == 128);
#endif
    u.a[0] = u.a[1] = 0;
    u.b[0] = 1; u.b[3] = 2;
    p = u2p(&u, 1);
    r &= UA_GET_NE16(p) == 0;
    r &= UA_GET_LE16(p) == 0;
    u.b[1] = 128;
    r &= UA_GET_LE16(p) == 128;
    u.b[2] = 129;
    r &= UA_GET_LE16(p) == LZO_UINT16_C(0x8180);
#if (LZO_ABI_BIG_ENDIAN)
    r &= UA_GET_NE16(p) == LZO_UINT16_C(0x8081);
#endif
#if (LZO_ABI_LITTLE_ENDIAN)
    r &= UA_GET_NE16(p) == LZO_UINT16_C(0x8180);
#endif
    u.a[0] = u.a[1] = 0;
    u.b[0] = 3; u.b[5] = 4;
    p = u2p(&u, 1);
    r &= UA_GET_NE32(p) == 0;
    r &= UA_GET_LE32(p) == 0;
    u.b[1] = 128;
    r &= UA_GET_LE32(p) == 128;
    u.b[2] = 129; u.b[3] = 130; u.b[4] = 131;
    r &= UA_GET_LE32(p) == LZO_UINT32_C(0x83828180);
#if (LZO_ABI_BIG_ENDIAN)
    r &= UA_GET_NE32(p) == LZO_UINT32_C(0x80818283);
#endif
#if (LZO_ABI_LITTLE_ENDIAN)
    r &= UA_GET_NE32(p) == LZO_UINT32_C(0x83828180);
#endif
#if defined(UA_GET_NE64)
    u.c[0] = u.c[1] = 0;
    u.b[0] = 5; u.b[9] = 6;
    p = u2p(&u, 1);
    u.c[0] = u.c[1] = 0;
    r &= UA_GET_NE64(p) == 0;
#if defined(UA_GET_LE64)
    r &= UA_GET_LE64(p) == 0;
    u.b[1] = 128;
    r &= UA_GET_LE64(p) == 128;
#endif
#endif
#if defined(lzo_bitops_ctlz32)
    { unsigned i = 0; lzo_uint32_t v;
    for (v = 1; v != 0 && r == 1; v <<= 1, i++) {
        r &= lzo_bitops_ctlz32(v) == 31 - i;
        r &= lzo_bitops_ctlz32_func(v) == 31 - i;
    }}
#endif
#if defined(lzo_bitops_ctlz64)
    { unsigned i = 0; lzo_uint64_t v;
    for (v = 1; v != 0 && r == 1; v <<= 1, i++) {
        r &= lzo_bitops_ctlz64(v) == 63 - i;
        r &= lzo_bitops_ctlz64_func(v) == 63 - i;
    }}
#endif
#if defined(lzo_bitops_cttz32)
    { unsigned i = 0; lzo_uint32_t v;
    for (v = 1; v != 0 && r == 1; v <<= 1, i++) {
        r &= lzo_bitops_cttz32(v) == i;
        r &= lzo_bitops_cttz32_func(v) == i;
    }}
#endif
#if defined(lzo_bitops_cttz64)
    { unsigned i = 0; lzo_uint64_t v;
    for (v = 1; v != 0 && r == 1; v <<= 1, i++) {
        r &= lzo_bitops_cttz64(v) == i;
        r &= lzo_bitops_cttz64_func(v) == i;
    }}
#endif
#endif
    LZO_UNUSED_FUNC(lzo_bitops_unused_funcs);
    return r == 1 ? LZO_E_OK : LZO_E_ERROR;
}
References lzo_config_check_union::a, lzo_config_check_union::b, lzo_bitops_ctlz32_func(), lzo_bitops_cttz32_func(), lzo_bytep, LZO_E_ERROR, LZO_E_OK, lzo_uintp, LZO_UNUSED_FUNC, lzo_voidp, u2p(), UA_GET_LE16, UA_GET_LE32, UA_GET_NE16, and UA_GET_NE32.
Referenced by __lzo_init_v2().
_lzo_version_date()
_lzo_version_date (void)
{
    return lzo_version_date_;
}
References lzo_version_date_.
_lzo_version_string()
_lzo_version_string (void)
{
    return lzo_version_string_;
}
References lzo_version_string_.
do_compress()
static __lzo_noinline lzo_uint do_compress (const lzo_bytep in, lzo_uint in_len, lzo_bytep out, lzo_uintp out_len, lzo_uint ti, lzo_voidp wrkmem) static
{
    const lzo_bytep ip;
    lzo_bytep op;
    const lzo_bytep const in_end = in + in_len;
    const lzo_bytep const ip_end = in + in_len - 20;
    const lzo_bytep ii;
    lzo_dict_p const dict = (lzo_dict_p) wrkmem;
    op = out;
    ip = in;
    ii = ip;
    ip += ti < 4 ? 4 - ti : 0;
    for (;;)
    {
        const lzo_bytep m_pos;
#if !(LZO_DETERMINISTIC)
        LZO_DEFINE_UNINITIALIZED_VAR(lzo_uint, m_off, 0);
        lzo_uint m_len;
        lzo_uint dindex;
next:
        if __lzo_unlikely(ip >= ip_end)
            break;
        DINDEX1(dindex,ip);
        GINDEX(m_pos,m_off,dict,dindex,in);
        if (LZO_CHECK_MPOS_NON_DET(m_pos,m_off,in,ip,M4_MAX_OFFSET))
            goto literal;
#if 1
        if (m_off <= M2_MAX_OFFSET || m_pos[3] == ip[3])
            goto try_match;
        DINDEX2(dindex,ip);
#endif
        GINDEX(m_pos,m_off,dict,dindex,in);
        if (LZO_CHECK_MPOS_NON_DET(m_pos,m_off,in,ip,M4_MAX_OFFSET))
            goto literal;
        if (m_off <= M2_MAX_OFFSET || m_pos[3] == ip[3])
            goto try_match;
        goto literal;
try_match:
#if (LZO_OPT_UNALIGNED32)
        if (UA_GET_NE32(m_pos) != UA_GET_NE32(ip))
#else
        if (m_pos[0] != ip[0] || m_pos[1] != ip[1] || m_pos[2] != ip[2] || m_pos[3] != ip[3])
#endif
        {
literal:
            UPDATE_I(dict,0,dindex,ip,in);
            ip += 1 + ((ip - ii) >> 5);
            continue;
        }
        UPDATE_I(dict,0,dindex,ip,in);
#else
        lzo_uint m_off;
        lzo_uint m_len;
        {
        lzo_uint32_t dv;
        lzo_uint dindex;
literal:
        ip += 1 + ((ip - ii) >> 5);
next:
        if __lzo_unlikely(ip >= ip_end)
            break;
        dv = UA_GET_LE32(ip);
        dindex = DINDEX(dv,ip);
        GINDEX(m_off,m_pos,in+dict,dindex,in);
        UPDATE_I(dict,0,dindex,ip,in);
        if __lzo_unlikely(dv != UA_GET_LE32(m_pos))
            goto literal;
        }
#endif
        ii -= ti; ti = 0;
        {
        lzo_uint t = pd(ip,ii);
        if (t != 0)
        {
            if (t <= 3)
            {
                op[-2] = LZO_BYTE(op[-2] | t);
#if (LZO_OPT_UNALIGNED32)
                UA_COPY4(op, ii);
                op += t;
#else
                { do *op++ = *ii++; while (--t > 0); }
#endif
            }
#if (LZO_OPT_UNALIGNED32) || (LZO_OPT_UNALIGNED64)
            else if (t <= 16)
            {
                *op++ = LZO_BYTE(t - 3);
                UA_COPY8(op, ii);
                UA_COPY8(op+8, ii+8);
                op += t;
            }
#endif
            else
            {
                if (t <= 18)
                    *op++ = LZO_BYTE(t - 3);
                else
                {
                    lzo_uint tt = t - 18;
                    *op++ = 0;
                    while __lzo_unlikely(tt > 255)
                    {
                        tt -= 255;
                        UA_SET1(op, 0);
                        op++;
                    }
                    assert(tt > 0);
                    *op++ = LZO_BYTE(tt);
                }
#if (LZO_OPT_UNALIGNED32) || (LZO_OPT_UNALIGNED64)
                do {
                    UA_COPY8(op, ii);
                    UA_COPY8(op+8, ii+8);
                    op += 16; ii += 16; t -= 16;
                } while (t >= 16); if (t > 0)
#endif
                { do *op++ = *ii++; while (--t > 0); }
            }
        }
        }
        m_len = 4;
        {
#if (LZO_OPT_UNALIGNED64)
        lzo_uint64_t v;
        v = UA_GET_NE64(ip + m_len) ^ UA_GET_NE64(m_pos + m_len);
        if __lzo_unlikely(v == 0) {
            do {
                m_len += 8;
                v = UA_GET_NE64(ip + m_len) ^ UA_GET_NE64(m_pos + m_len);
                if __lzo_unlikely(ip + m_len >= ip_end)
                    goto m_len_done;
            } while (v == 0);
        }
#if (LZO_ABI_BIG_ENDIAN) && defined(lzo_bitops_ctlz64)
        m_len += lzo_bitops_ctlz64(v) / CHAR_BIT;
#elif (LZO_ABI_BIG_ENDIAN)
        if ((v >> (64 - CHAR_BIT)) == 0) do {
            v <<= CHAR_BIT;
            m_len += 1;
        } while ((v >> (64 - CHAR_BIT)) == 0);
#elif (LZO_ABI_LITTLE_ENDIAN) && defined(lzo_bitops_cttz64)
        m_len += lzo_bitops_cttz64(v) / CHAR_BIT;
#elif (LZO_ABI_LITTLE_ENDIAN)
        if ((v & UCHAR_MAX) == 0) do {
            v >>= CHAR_BIT;
            m_len += 1;
        } while ((v & UCHAR_MAX) == 0);
#else
        if (ip[m_len] == m_pos[m_len]) do {
            m_len += 1;
        } while (ip[m_len] == m_pos[m_len]);
#endif
#elif (LZO_OPT_UNALIGNED32)
        lzo_uint32_t v;
        v = UA_GET_NE32(ip + m_len) ^ UA_GET_NE32(m_pos + m_len);
        if __lzo_unlikely(v == 0) {
            do {
                m_len += 4;
                v = UA_GET_NE32(ip + m_len) ^ UA_GET_NE32(m_pos + m_len);
                if (v != 0)
                    break;
                m_len += 4;
                v = UA_GET_NE32(ip + m_len) ^ UA_GET_NE32(m_pos + m_len);
                if __lzo_unlikely(ip + m_len >= ip_end)
                    goto m_len_done;
            } while (v == 0);
        }
#if (LZO_ABI_BIG_ENDIAN) && defined(lzo_bitops_ctlz32)
        m_len += lzo_bitops_ctlz32(v) / CHAR_BIT;
#elif (LZO_ABI_BIG_ENDIAN)
        if ((v >> (32 - CHAR_BIT)) == 0) do {
            v <<= CHAR_BIT;
            m_len += 1;
        } while ((v >> (32 - CHAR_BIT)) == 0);
#elif (LZO_ABI_LITTLE_ENDIAN) && defined(lzo_bitops_cttz32)
        m_len += lzo_bitops_cttz32(v) / CHAR_BIT;
#elif (LZO_ABI_LITTLE_ENDIAN)
        if ((v & UCHAR_MAX) == 0) do {
            v >>= CHAR_BIT;
            m_len += 1;
        } while ((v & UCHAR_MAX) == 0);
#else
        if (ip[m_len] == m_pos[m_len]) do {
            m_len += 1;
        } while (ip[m_len] == m_pos[m_len]);
#endif
#else
        if __lzo_unlikely(ip[m_len] == m_pos[m_len]) {
            do {
                m_len += 1;
                if (ip[m_len] != m_pos[m_len])
                    break;
                m_len += 1;
                if (ip[m_len] != m_pos[m_len])
                    break;
                m_len += 1;
                if (ip[m_len] != m_pos[m_len])
                    break;
                m_len += 1;
                if (ip[m_len] != m_pos[m_len])
                    break;
                m_len += 1;
                if (ip[m_len] != m_pos[m_len])
                    break;
                m_len += 1;
                if (ip[m_len] != m_pos[m_len])
                    break;
                m_len += 1;
                if (ip[m_len] != m_pos[m_len])
                    break;
                m_len += 1;
                if __lzo_unlikely(ip + m_len >= ip_end)
                    goto m_len_done;
            } while (ip[m_len] == m_pos[m_len]);
        }
#endif
        }
m_len_done:
        m_off = pd(ip,m_pos);
        ip += m_len;
        ii = ip;
        if (m_len <= M2_MAX_LEN && m_off <= M2_MAX_OFFSET)
        {
            m_off -= 1;
#if defined(LZO1X)
            *op++ = LZO_BYTE(((m_len - 1) << 5) | ((m_off & 7) << 2));
            *op++ = LZO_BYTE(m_off >> 3);
#elif defined(LZO1Y)
            *op++ = LZO_BYTE(((m_len + 1) << 4) | ((m_off & 3) << 2));
            *op++ = LZO_BYTE(m_off >> 2);
#endif
        }
        else if (m_off <= M3_MAX_OFFSET)
        {
            m_off -= 1;
            if (m_len <= M3_MAX_LEN)
                *op++ = LZO_BYTE(M3_MARKER | (m_len - 2));
            else
            {
                m_len -= M3_MAX_LEN;
                *op++ = M3_MARKER | 0;
                while __lzo_unlikely(m_len > 255)
                {
                    m_len -= 255;
                    UA_SET1(op, 0);
                    op++;
                }
                *op++ = LZO_BYTE(m_len);
            }
            *op++ = LZO_BYTE(m_off << 2);
            *op++ = LZO_BYTE(m_off >> 6);
        }
        else
        {
            m_off -= 0x4000;
            if (m_len <= M4_MAX_LEN)
                *op++ = LZO_BYTE(M4_MARKER | ((m_off >> 11) & 8) | (m_len - 2));
            else
            {
                m_len -= M4_MAX_LEN;
                *op++ = LZO_BYTE(M4_MARKER | ((m_off >> 11) & 8));
                while __lzo_unlikely(m_len > 255)
                {
                    m_len -= 255;
                    UA_SET1(op, 0);
                    op++;
                }
                *op++ = LZO_BYTE(m_len);
            }
            *op++ = LZO_BYTE(m_off << 2);
            *op++ = LZO_BYTE(m_off >> 6);
        }
        goto next;
    }
    *out_len = pd(op, out);
    return pd(in_end,ii-ti);
}
References __lzo_unlikely, CHAR_BIT, DINDEX, DINDEX1, DINDEX2, GINDEX, in, LZO_BYTE, lzo_bytep, LZO_CHECK_MPOS_NON_DET, LZO_DEFINE_UNINITIALIZED_VAR, lzo_dict_p, M2_MAX_LEN, M2_MAX_OFFSET, M3_MARKER, M3_MAX_LEN, M3_MAX_OFFSET, M4_MARKER, M4_MAX_LEN, M4_MAX_OFFSET, out, pd, UA_COPY4, UA_COPY8, UA_GET_LE32, UA_GET_NE32, UA_SET1, UPDATE_I, and wrkmem.
DO_COMPRESS()
DO_COMPRESS (const lzo_bytep in, lzo_uint in_len, lzo_bytep out, lzo_uintp out_len, lzo_voidp wrkmem)
{
    const lzo_bytep ip = in;
    lzo_bytep op = out;
    lzo_uint l = in_len;
    lzo_uint t = 0;
    while (l > 20)
    {
        lzo_uint ll = l;
        lzo_uintptr_t ll_end;
#if 0 || (LZO_DETERMINISTIC)
        ll = LZO_MIN(ll, 49152);
#endif
        ll_end = (lzo_uintptr_t)ip + ll;
        if ((ll_end + ((t + ll) >> 5)) <= ll_end || (const lzo_bytep)(ll_end + ((t + ll) >> 5)) <= ip + ll)
            break;
#if (LZO_DETERMINISTIC)
        lzo_memset(wrkmem, 0, ((lzo_uint)1 << D_BITS) * sizeof(lzo_dict_t));
#endif
        t = do_compress(ip,ll,op,out_len,t,wrkmem);
        ip += ll;
        op += *out_len;
        l  -= ll;
    }
    t += l;
    if (t > 0)
    {
        const lzo_bytep ii = in + in_len - t;
        if (op == out && t <= 238)
            *op++ = LZO_BYTE(17 + t);
        else if (t <= 3)
            op[-2] = LZO_BYTE(op[-2] | t);
        else if (t <= 18)
            *op++ = LZO_BYTE(t - 3);
        else
        {
            lzo_uint tt = t - 18;
            *op++ = 0;
            while (tt > 255)
            {
                tt -= 255;
                UA_SET1(op, 0);
                op++;
            }
            assert(tt > 0);
            *op++ = LZO_BYTE(tt);
        }
        UA_COPYN(op, ii, t);
        op += t;
    }
    *op++ = M4_MARKER | 1;
    *op++ = 0;
    *op++ = 0;
    *out_len = pd(op, out);
    return LZO_E_OK;
}
References D_BITS, do_compress, in, LZO_BYTE, lzo_bytep, lzo_dict_t, LZO_E_OK, lzo_memset(), LZO_MIN, lzo_uintptr_t, M4_MARKER, out, pd, UA_COPYN, UA_SET1, and wrkmem.
DO_DECOMPRESS()
DO_DECOMPRESS (const lzo_bytep in, lzo_uint in_len, lzo_bytep out, lzo_uintp out_len, lzo_voidp wrkmem)
{
    lzo_bytep op;
    const lzo_bytep ip;
    lzo_uint t;
#if defined(COPY_DICT)
    lzo_uint m_off;
    const lzo_bytep dict_end;
#else
    const lzo_bytep m_pos;
#endif
    const lzo_bytep const ip_end = in + in_len;
#if defined(HAVE_ANY_OP)
    lzo_bytep const op_end = out + *out_len;
#endif
#if defined(LZO1Z)
    lzo_uint last_m_off = 0;
#endif
    LZO_UNUSED(wrkmem);
#if defined(COPY_DICT)
    if (dict)
    {
        if (dict_len > M4_MAX_OFFSET)
        {
            dict += dict_len - M4_MAX_OFFSET;
            dict_len = M4_MAX_OFFSET;
        }
        dict_end = dict + dict_len;
    }
    else
    {
        dict_len = 0;
        dict_end = NULL;
    }
#endif
    *out_len = 0;
    op = out;
    ip = in;
    NEED_IP(1);
    if (*ip > 17)
    {
        t = *ip++ - 17;
        if (t < 4)
            goto match_next;
        assert(t > 0); NEED_OP(t); NEED_IP(t+3);
        do *op++ = *ip++; while (--t > 0);
        goto first_literal_run;
    }
    for (;;)
    {
        NEED_IP(3);
        t = *ip++;
        if (t >= 16)
            goto match;
        if (t == 0)
        {
            while (*ip == 0)
            {
                t += 255;
                ip++;
                TEST_IV(t);
                NEED_IP(1);
            }
            t += 15 + *ip++;
        }
        assert(t > 0); NEED_OP(t+3); NEED_IP(t+6);
#if (LZO_OPT_UNALIGNED64) && (LZO_OPT_UNALIGNED32)
        t += 3;
        if (t >= 8) do
        {
            UA_COPY8(op,ip);
            op += 8; ip += 8; t -= 8;
        } while (t >= 8);
        if (t >= 4)
        {
            UA_COPY4(op,ip);
            op += 4; ip += 4; t -= 4;
        }
        if (t > 0)
        {
            *op++ = *ip++;
            if (t > 1) { *op++ = *ip++; if (t > 2) { *op++ = *ip++; } }
        }
#elif (LZO_OPT_UNALIGNED32) || (LZO_ALIGNED_OK_4)
#if !(LZO_OPT_UNALIGNED32)
        if (PTR_ALIGNED2_4(op,ip))
        {
#endif
        UA_COPY4(op,ip);
        op += 4; ip += 4;
        if (--t > 0)
        {
            if (t >= 4)
            {
                do {
                    UA_COPY4(op,ip);
                    op += 4; ip += 4; t -= 4;
                } while (t >= 4);
                if (t > 0) do *op++ = *ip++; while (--t > 0);
            }
            else
                do *op++ = *ip++; while (--t > 0);
        }
#if !(LZO_OPT_UNALIGNED32)
        }
        else
#endif
#endif
#if !(LZO_OPT_UNALIGNED32)
        {
            *op++ = *ip++; *op++ = *ip++; *op++ = *ip++;
            do *op++ = *ip++; while (--t > 0);
        }
#endif
first_literal_run:
        t = *ip++;
        if (t >= 16)
            goto match;
#if defined(COPY_DICT)
#if defined(LZO1Z)
        m_off = (1 + M2_MAX_OFFSET) + (t << 6) + (*ip++ >> 2);
        last_m_off = m_off;
#else
        m_off = (1 + M2_MAX_OFFSET) + (t >> 2) + (*ip++ << 2);
#endif
        NEED_OP(3);
        t = 3; COPY_DICT(t,m_off)
#else
#if defined(LZO1Z)
        t = (1 + M2_MAX_OFFSET) + (t << 6) + (*ip++ >> 2);
        m_pos = op - t;
        last_m_off = t;
#else
        m_pos = op - (1 + M2_MAX_OFFSET);
        m_pos -= t >> 2;
        m_pos -= *ip++ << 2;
#endif
        TEST_LB(m_pos); NEED_OP(3);
        *op++ = *m_pos++; *op++ = *m_pos++; *op++ = *m_pos;
#endif
        goto match_done;
        for (;;) {
match:
            if (t >= 64)
            {
#if defined(COPY_DICT)
#if defined(LZO1X)
                m_off = 1 + ((t >> 2) & 7) + (*ip++ << 3);
                t = (t >> 5) - 1;
#elif defined(LZO1Y)
                m_off = 1 + ((t >> 2) & 3) + (*ip++ << 2);
                t = (t >> 4) - 3;
#elif defined(LZO1Z)
                m_off = t & 0x1f;
                if (m_off >= 0x1c)
                    m_off = last_m_off;
                else
                {
                    m_off = 1 + (m_off << 6) + (*ip++ >> 2);
                    last_m_off = m_off;
                }
                t = (t >> 5) - 1;
#endif
#else
#if defined(LZO1X)
                m_pos = op - 1;
                m_pos -= (t >> 2) & 7;
                m_pos -= *ip++ << 3;
                t = (t >> 5) - 1;
#elif defined(LZO1Y)
                m_pos = op - 1;
                m_pos -= (t >> 2) & 3;
                m_pos -= *ip++ << 2;
                t = (t >> 4) - 3;
#elif defined(LZO1Z)
                {
                    lzo_uint off = t & 0x1f;
                    m_pos = op;
                    if (off >= 0x1c)
                    {
                        assert(last_m_off > 0);
                        m_pos -= last_m_off;
                    }
                    else
                    {
                        off = 1 + (off << 6) + (*ip++ >> 2);
                        m_pos -= off;
                        last_m_off = off;
                    }
                }
                t = (t >> 5) - 1;
#endif
                TEST_LB(m_pos); assert(t > 0); NEED_OP(t+3-1);
                goto copy_match;
#endif
            }
            else if (t >= 32)
            {
                t &= 31;
                if (t == 0)
                {
                    while (*ip == 0)
                    {
                        t += 255;
                        ip++;
                        TEST_OV(t);
                        NEED_IP(1);
                    }
                    t += 31 + *ip++;
                    NEED_IP(2);
                }
#if defined(COPY_DICT)
#if defined(LZO1Z)
                m_off = 1 + (ip[0] << 6) + (ip[1] >> 2);
                last_m_off = m_off;
#else
                m_off = 1 + (ip[0] >> 2) + (ip[1] << 6);
#endif
#else
#if defined(LZO1Z)
                {
                    lzo_uint off = 1 + (ip[0] << 6) + (ip[1] >> 2);
                    m_pos = op - off;
                    last_m_off = off;
                }
#elif (LZO_OPT_UNALIGNED16) && (LZO_ABI_LITTLE_ENDIAN)
                m_pos = op - 1;
                m_pos -= UA_GET_LE16(ip) >> 2;
#else
                m_pos = op - 1;
                m_pos -= (ip[0] >> 2) + (ip[1] << 6);
#endif
#endif
                ip += 2;
            }
            else if (t >= 16)
            {
#if defined(COPY_DICT)
                m_off = (t & 8) << 11;
#else
                m_pos = op;
                m_pos -= (t & 8) << 11;
#endif
                t &= 7;
                if (t == 0)
                {
                    while (*ip == 0)
                    {
                        t += 255;
                        ip++;
                        TEST_OV(t);
                        NEED_IP(1);
                    }
                    t += 7 + *ip++;
                    NEED_IP(2);
                }
#if defined(COPY_DICT)
#if defined(LZO1Z)
                m_off += (ip[0] << 6) + (ip[1] >> 2);
#else
                m_off += (ip[0] >> 2) + (ip[1] << 6);
#endif
                ip += 2;
                if (m_off == 0)
                    goto eof_found;
                m_off += 0x4000;
#if defined(LZO1Z)
                last_m_off = m_off;
#endif
#else
#if defined(LZO1Z)
                m_pos -= (ip[0] << 6) + (ip[1] >> 2);
#elif (LZO_OPT_UNALIGNED16) && (LZO_ABI_LITTLE_ENDIAN)
                m_pos -= UA_GET_LE16(ip) >> 2;
#else
                m_pos -= (ip[0] >> 2) + (ip[1] << 6);
#endif
                ip += 2;
                if (m_pos == op)
                    goto eof_found;
                m_pos -= 0x4000;
#if defined(LZO1Z)
                last_m_off = pd((const lzo_bytep)op, m_pos);
#endif
#endif
            }
            else
            {
#if defined(COPY_DICT)
#if defined(LZO1Z)
                m_off = 1 + (t << 6) + (*ip++ >> 2);
                last_m_off = m_off;
#else
                m_off = 1 + (t >> 2) + (*ip++ << 2);
#endif
                NEED_OP(2);
                t = 2; COPY_DICT(t,m_off)
#else
#if defined(LZO1Z)
                t = 1 + (t << 6) + (*ip++ >> 2);
                m_pos = op - t;
                last_m_off = t;
#else
                m_pos = op - 1;
                m_pos -= t >> 2;
                m_pos -= *ip++ << 2;
#endif
                TEST_LB(m_pos); NEED_OP(2);
                *op++ = *m_pos++; *op++ = *m_pos;
#endif
                goto match_done;
            }
#if defined(COPY_DICT)
            NEED_OP(t+3-1);
            t += 3-1; COPY_DICT(t,m_off)
#else
            TEST_LB(m_pos); assert(t > 0); NEED_OP(t+3-1);
#if (LZO_OPT_UNALIGNED64) && (LZO_OPT_UNALIGNED32)
            if (op - m_pos >= 8)
            {
                t += (3 - 1);
                if (t >= 8) do
                {
                    UA_COPY8(op,m_pos);
                    op += 8; m_pos += 8; t -= 8;
                } while (t >= 8);
                if (t >= 4)
                {
                    UA_COPY4(op,m_pos);
                    op += 4; m_pos += 4; t -= 4;
                }
                if (t > 0)
                {
                    *op++ = m_pos[0];
                    if (t > 1) { *op++ = m_pos[1]; if (t > 2) { *op++ = m_pos[2]; } }
                }
            }
            else
#elif (LZO_OPT_UNALIGNED32) || (LZO_ALIGNED_OK_4)
#if !(LZO_OPT_UNALIGNED32)
            if (t >= 2 * 4 - (3 - 1) && PTR_ALIGNED2_4(op,m_pos))
            {
                assert((op - m_pos) >= 4);
#else
            if (t >= 2 * 4 - (3 - 1) && (op - m_pos) >= 4)
            {
#endif
                UA_COPY4(op,m_pos);
                op += 4; m_pos += 4; t -= 4 - (3 - 1);
                do {
                    UA_COPY4(op,m_pos);
                    op += 4; m_pos += 4; t -= 4;
                } while (t >= 4);
                if (t > 0) do *op++ = *m_pos++; while (--t > 0);
            }
            else
#endif
            {
copy_match:
                *op++ = *m_pos++; *op++ = *m_pos++;
                do *op++ = *m_pos++; while (--t > 0);
            }
#endif
match_done:
#if defined(LZO1Z)
            t = ip[-1] & 3;
#else
            t = ip[-2] & 3;
#endif
            if (t == 0)
                break;
match_next:
            assert(t > 0); assert(t < 4); NEED_OP(t); NEED_IP(t+3);
#if 0
            do *op++ = *ip++; while (--t > 0);
#else
            *op++ = *ip++;
            if (t > 1) { *op++ = *ip++; if (t > 2) { *op++ = *ip++; } }
#endif
            t = *ip++;
        }
    }
eof_found:
    *out_len = pd(op, out);
    return (ip == ip_end ? LZO_E_OK :
           (ip < ip_end  ? LZO_E_INPUT_NOT_CONSUMED : LZO_E_INPUT_OVERRUN));
#if defined(HAVE_NEED_IP)
input_overrun:
    *out_len = pd(op, out);
    return LZO_E_INPUT_OVERRUN;
#endif
#if defined(HAVE_NEED_OP)
output_overrun:
    *out_len = pd(op, out);
    return LZO_E_OUTPUT_OVERRUN;
#endif
#if defined(LZO_TEST_OVERRUN_LOOKBEHIND)
lookbehind_overrun:
    *out_len = pd(op, out);
    return LZO_E_LOOKBEHIND_OVERRUN;
#endif
}
References in, lzo_bytep, LZO_E_INPUT_NOT_CONSUMED, LZO_E_INPUT_OVERRUN, LZO_E_LOOKBEHIND_OVERRUN, LZO_E_OK, LZO_E_OUTPUT_OVERRUN, LZO_UNUSED, M2_MAX_OFFSET, M4_MAX_OFFSET, NEED_IP, NEED_OP, NULL, out, pd, PTR_ALIGNED2_4, TEST_IV, TEST_LB, TEST_OV, UA_COPY4, UA_COPY8, UA_GET_LE16, and wrkmem.
lzo_adler32()
lzo_adler32 (lzo_uint32_t adler, const lzo_bytep buf, lzo_uint len)
{
    lzo_uint32_t s1 = adler & 0xffff;
    lzo_uint32_t s2 = (adler >> 16) & 0xffff;
    unsigned k;
    if (buf == NULL)
        return 1;
    while (len > 0)
    {
        k = len < LZO_NMAX ? (unsigned) len : LZO_NMAX;
        len -= k;
        if (k >= 16) do
        {
            LZO_DO16(buf,0);
            buf += 16;
            k -= 16;
        } while (k >= 16);
        if (k != 0) do
        {
            s1 += *buf++;
            s2 += s1;
        } while (--k > 0);
        s1 %= LZO_BASE;
        s2 %= LZO_BASE;
    }
    return (s2 << 16) | s1;
}
References LZO_BASE, LZO_DO16, LZO_NMAX, and NULL.
lzo_bitops_ctlz32_func()
__lzo_static_forceinline unsigned lzo_bitops_ctlz32_func (lzo_uint32_t v)
{
#if (LZO_BITOPS_USE_MSC_BITSCAN) && (LZO_ARCH_AMD64 || LZO_ARCH_I386)
    unsigned long r; (void) _BitScanReverse(&r, v); return (unsigned) r ^ 31;
#define lzo_bitops_ctlz32(v)    lzo_bitops_ctlz32_func(v)
#elif (LZO_BITOPS_USE_ASM_BITSCAN) && (LZO_ARCH_AMD64 || LZO_ARCH_I386) && (LZO_ASM_SYNTAX_GNUC)
    lzo_uint32_t r;
    __asm__("bsr %1,%0" : "=r" (r) : "rm" (v) __LZO_ASM_CLOBBER_LIST_CC);
    return (unsigned) r ^ 31;
#define lzo_bitops_ctlz32(v)    lzo_bitops_ctlz32_func(v)
#elif (LZO_BITOPS_USE_GNUC_BITSCAN) && (LZO_SIZEOF_INT == 4)
    unsigned r; r = (unsigned) __builtin_clz(v); return r;
#define lzo_bitops_ctlz32(v)    ((unsigned) __builtin_clz(v))
#elif (LZO_BITOPS_USE_GNUC_BITSCAN) && (LZO_SIZEOF_LONG == 8) && (LZO_WORDSIZE >= 8)
    unsigned r; r = (unsigned) __builtin_clzl(v); return r ^ 32;
#define lzo_bitops_ctlz32(v)    (((unsigned) __builtin_clzl(v)) ^ 32)
#else
    LZO_UNUSED(v); return 0;
#endif
}
References LZO_UNUSED, and void().
Referenced by _lzo_config_check(), and lzo_unused_funcs_impl().
lzo_bitops_cttz32_func()
__lzo_static_forceinline unsigned lzo_bitops_cttz32_func (lzo_uint32_t v)
{
#if (LZO_BITOPS_USE_MSC_BITSCAN) && (LZO_ARCH_AMD64 || LZO_ARCH_I386)
    unsigned long r; (void) _BitScanForward(&r, v); return (unsigned) r;
#define lzo_bitops_cttz32(v)    lzo_bitops_cttz32_func(v)
#elif (LZO_BITOPS_USE_ASM_BITSCAN) && (LZO_ARCH_AMD64 || LZO_ARCH_I386) && (LZO_ASM_SYNTAX_GNUC)
    lzo_uint32_t r;
    __asm__("bsf %1,%0" : "=r" (r) : "rm" (v) __LZO_ASM_CLOBBER_LIST_CC);
    return (unsigned) r;
#define lzo_bitops_cttz32(v)    lzo_bitops_cttz32_func(v)
#elif (LZO_BITOPS_USE_GNUC_BITSCAN) && (LZO_SIZEOF_INT >= 4)
    unsigned r; r = (unsigned) __builtin_ctz(v); return r;
#define lzo_bitops_cttz32(v)    ((unsigned) __builtin_ctz(v))
#else
    LZO_UNUSED(v); return 0;
#endif
}
References LZO_UNUSED, and void().
Referenced by _lzo_config_check(), and lzo_unused_funcs_impl().
LZO_COMPILE_TIME_ASSERT_HEADER()
LZO_COMPILE_TIME_ASSERT_HEADER (sizeof(*(lzo_memops_TU1p) 0) = =1)
                                                                 { \
        * (lzo_memops_TU2p) (lzo_memops_TU0p) (dd) = * (const lzo_memops_TU2p) (const lzo_memops_TU0p) (ss); \
    } else { LZO_MEMOPS_MOVE2(dd,ss); } LZO_BLOCK_END
#else
#define LZO_MEMOPS_COPY2(dd,ss) LZO_MEMOPS_MOVE2(dd,ss)
#endif
#if (LZO_OPT_UNALIGNED32)
LZO_COMPILE_TIME_ASSERT_HEADER(sizeof(*(lzo_memops_TU4p)0)==4)
#define LZO_MEMOPS_COPY4(dd,ss) \
    * (lzo_memops_TU4p) (lzo_memops_TU0p) (dd) = * (const lzo_memops_TU4p) (const lzo_memops_TU0p) (ss)
#elif defined(lzo_memops_tcheck__)
#define LZO_MEMOPS_COPY4(dd,ss) \
    LZO_BLOCK_BEGIN if (lzo_memops_tcheck__(lzo_memops_TU4,4,1)) { \
        * (lzo_memops_TU4p) (lzo_memops_TU0p) (dd) = * (const lzo_memops_TU4p) (const lzo_memops_TU0p) (ss); \
    } else { LZO_MEMOPS_MOVE4(dd,ss); } LZO_BLOCK_END
#else
#define LZO_MEMOPS_COPY4(dd,ss) LZO_MEMOPS_MOVE4(dd,ss)
#endif
#if (LZO_WORDSIZE != 8)
#define LZO_MEMOPS_COPY8(dd,ss) \
    LZO_BLOCK_BEGIN LZO_MEMOPS_COPY4(dd,ss); LZO_MEMOPS_COPY4((lzo_memops_TU1p)(lzo_memops_TU0p)(dd)+4,(const lzo_memops_TU1p)(const lzo_memops_TU0p)(ss)+4); LZO_BLOCK_END
#else
#if (LZO_OPT_UNALIGNED64)
LZO_COMPILE_TIME_ASSERT_HEADER(sizeof(*(lzo_memops_TU8p)0)==8)
#define LZO_MEMOPS_COPY8(dd,ss) \
    * (lzo_memops_TU8p) (lzo_memops_TU0p) (dd) = * (const lzo_memops_TU8p) (const lzo_memops_TU0p) (ss)
#elif (LZO_OPT_UNALIGNED32)
#define LZO_MEMOPS_COPY8(dd,ss) \
    LZO_BLOCK_BEGIN LZO_MEMOPS_COPY4(dd,ss); LZO_MEMOPS_COPY4((lzo_memops_TU1p)(lzo_memops_TU0p)(dd)+4,(const lzo_memops_TU1p)(const lzo_memops_TU0p)(ss)+4); LZO_BLOCK_END
#elif defined(lzo_memops_tcheck__)
#define LZO_MEMOPS_COPY8(dd,ss) \
    LZO_BLOCK_BEGIN if (lzo_memops_tcheck__(lzo_memops_TU8,8,1)) { \
        * (lzo_memops_TU8p) (lzo_memops_TU0p) (dd) = * (const lzo_memops_TU8p) (const lzo_memops_TU0p) (ss); \
    } else { LZO_MEMOPS_MOVE8(dd,ss); } LZO_BLOCK_END
#else
#define LZO_MEMOPS_COPY8(dd,ss) LZO_MEMOPS_MOVE8(dd,ss)
#endif
#endif
#define LZO_MEMOPS_COPYN(dd,ss,nn) \
    LZO_BLOCK_BEGIN \
    lzo_memops_TU1p d__n = (lzo_memops_TU1p) (lzo_memops_TU0p) (dd); \
    const lzo_memops_TU1p s__n = (const lzo_memops_TU1p) (const lzo_memops_TU0p) (ss); \
    lzo_uint n__n = (nn); \
    while ((void)0, n__n >= 8) { LZO_MEMOPS_COPY8(d__n, s__n); d__n += 8; s__n += 8; n__n -= 8; } \
    if ((void)0, n__n >= 4) { LZO_MEMOPS_COPY4(d__n, s__n); d__n += 4; s__n += 4; n__n -= 4; } \
    if ((void)0, n__n > 0) do { *d__n++ = *s__n++; } while (--n__n > 0); \
    LZO_BLOCK_END
__lzo_static_forceinline lzo_uint16_t lzo_memops_get_le16(const lzo_voidp ss)
{
    lzo_uint16_t v;
#if (LZO_ABI_LITTLE_ENDIAN)
    LZO_MEMOPS_COPY2(&v, ss);
#elif (LZO_OPT_UNALIGNED16 && LZO_ARCH_POWERPC && LZO_ABI_BIG_ENDIAN) && (LZO_ASM_SYNTAX_GNUC)
    const lzo_memops_TU2p s = (const lzo_memops_TU2p) ss;
    unsigned long vv;
    __asm__("lhbrx %0,0,%1" : "=r" (vv) : "r" (s), "m" (*s));
    v = (lzo_uint16_t) vv;
#else
    const lzo_memops_TU1p s = (const lzo_memops_TU1p) ss;
    v = (lzo_uint16_t) (((lzo_uint16_t)s[0]) | ((lzo_uint16_t)s[1] << 8));
#endif
    return v;
}
References LZO_MEMOPS_COPY2, lzo_memops_TU1p, and lzo_memops_TU2p.
lzo_copyright()
lzo_copyright (void)
{
    return (const lzo_bytep) lzo_copyright_;
}
References lzo_bytep, and lzo_copyright_.
LZO_EXTERN()
LZO_EXTERN (const lzo_bytep)
           {
#endif
#if (LZO_ARCH_I086)
#error "LZO_ARCH_I086 is unsupported"
#elif (LZO_MM_PVP)
#error "LZO_MM_PVP is unsupported"
#else
#define PTR(a)              ((lzo_uintptr_t) (a))
#define PTR_LINEAR(a)       PTR(a)
#define PTR_ALIGNED_4(a)    ((PTR_LINEAR(a) & 3) == 0)
#define PTR_ALIGNED_8(a)    ((PTR_LINEAR(a) & 7) == 0)
#define PTR_ALIGNED2_4(a,b) (((PTR_LINEAR(a) | PTR_LINEAR(b)) & 3) == 0)
#define PTR_ALIGNED2_8(a,b) (((PTR_LINEAR(a) | PTR_LINEAR(b)) & 7) == 0)
#endif
#define PTR_LT(a,b)         (PTR(a) < PTR(b))
#define PTR_GE(a,b)         (PTR(a) >= PTR(b))
#define PTR_DIFF(a,b)       (PTR(a) - PTR(b))
#define pd(a,b)             ((lzo_uint) ((a)-(b)))
LZO_EXTERN(lzo_uintptr_t)
__lzo_ptr_linear(const lzo_voidp ptr);
typedef union
{
    char            a_char;
    unsigned char   a_uchar;
    short           a_short;
    unsigned short  a_ushort;
    int             a_int;
    unsigned int    a_uint;
    long            a_long;
    unsigned long   a_ulong;
    lzo_int         a_lzo_int;
    lzo_uint        a_lzo_uint;
    lzo_xint        a_lzo_xint;
    lzo_int16_t     a_lzo_int16_t;
    lzo_uint16_t    a_lzo_uint16_t;
    lzo_int32_t     a_lzo_int32_t;
    lzo_uint32_t    a_lzo_uint32_t;
#if defined(lzo_uint64_t)
    lzo_int64_t     a_lzo_int64_t;
    lzo_uint64_t    a_lzo_uint64_t;
#endif
    size_t          a_size_t;
    ptrdiff_t       a_ptrdiff_t;
    lzo_uintptr_t   a_lzo_uintptr_t;
    void *          a_void_p;
    char *          a_char_p;
    unsigned char * a_uchar_p;
    const void *          a_c_void_p;
    const char *          a_c_char_p;
    const unsigned char * a_c_uchar_p;
    lzo_voidp       a_lzo_voidp;
    lzo_bytep       a_lzo_bytep;
    const lzo_voidp a_c_lzo_voidp;
    const lzo_bytep a_c_lzo_bytep;
}
lzo_memops_get_le32()
__lzo_static_forceinline lzo_uint32_t lzo_memops_get_le32 (const lzo_voidp ss)
{
    lzo_uint32_t v;
#if (LZO_ABI_LITTLE_ENDIAN)
    LZO_MEMOPS_COPY4(&v, ss);
#elif (LZO_OPT_UNALIGNED32 && LZO_ARCH_POWERPC && LZO_ABI_BIG_ENDIAN) && (LZO_ASM_SYNTAX_GNUC)
    const lzo_memops_TU4p s = (const lzo_memops_TU4p) ss;
    unsigned long vv;
    __asm__("lwbrx %0,0,%1" : "=r" (vv) : "r" (s), "m" (*s));
    v = (lzo_uint32_t) vv;
#else
    const lzo_memops_TU1p s = (const lzo_memops_TU1p) ss;
    v = (lzo_uint32_t) (((lzo_uint32_t)s[0]) | ((lzo_uint32_t)s[1] << 8) | ((lzo_uint32_t)s[2] << 16) | ((lzo_uint32_t)s[3] << 24));
#endif
    return v;
}
References LZO_MEMOPS_COPY4, lzo_memops_TU1p, and lzo_memops_TU4p.
Referenced by lzo_unused_funcs_impl().
lzo_memops_get_ne16()
__lzo_static_forceinline lzo_uint16_t lzo_memops_get_ne16 (const lzo_voidp ss)
{
    lzo_uint16_t v;
    LZO_MEMOPS_COPY2(&v, ss);
    return v;
}
References LZO_MEMOPS_COPY2.
Referenced by lzo_unused_funcs_impl().
lzo_memops_get_ne32()
__lzo_static_forceinline lzo_uint32_t lzo_memops_get_ne32 (const lzo_voidp ss)
{
    lzo_uint32_t v;
    LZO_MEMOPS_COPY4(&v, ss);
    return v;
}
References LZO_MEMOPS_COPY4.
Referenced by lzo_unused_funcs_impl().
lzo_memops_put_le16()
__lzo_static_forceinline void lzo_memops_put_le16 (lzo_voidp dd, lzo_uint16_t vv)
{
#if (LZO_ABI_LITTLE_ENDIAN)
    LZO_MEMOPS_COPY2(dd, &vv);
#elif (LZO_OPT_UNALIGNED16 && LZO_ARCH_POWERPC && LZO_ABI_BIG_ENDIAN) && (LZO_ASM_SYNTAX_GNUC)
    lzo_memops_TU2p d = (lzo_memops_TU2p) dd;
    unsigned long v = vv;
    __asm__("sthbrx %2,0,%1" : "=m" (*d) : "r" (d), "r" (v));
#else
    lzo_memops_TU1p d = (lzo_memops_TU1p) dd;
    d[0] = LZO_BYTE((vv      ) & 0xff);
    d[1] = LZO_BYTE((vv >>  8) & 0xff);
#endif
}
References LZO_BYTE, LZO_MEMOPS_COPY2, lzo_memops_TU1p, and lzo_memops_TU2p.
Referenced by lzo_unused_funcs_impl().
lzo_memops_put_le32()
__lzo_static_forceinline void lzo_memops_put_le32 (lzo_voidp dd, lzo_uint32_t vv)
{
#if (LZO_ABI_LITTLE_ENDIAN)
    LZO_MEMOPS_COPY4(dd, &vv);
#elif (LZO_OPT_UNALIGNED32 && LZO_ARCH_POWERPC && LZO_ABI_BIG_ENDIAN) && (LZO_ASM_SYNTAX_GNUC)
    lzo_memops_TU4p d = (lzo_memops_TU4p) dd;
    unsigned long v = vv;
    __asm__("stwbrx %2,0,%1" : "=m" (*d) : "r" (d), "r" (v));
#else
    lzo_memops_TU1p d = (lzo_memops_TU1p) dd;
    d[0] = LZO_BYTE((vv      ) & 0xff);
    d[1] = LZO_BYTE((vv >>  8) & 0xff);
    d[2] = LZO_BYTE((vv >> 16) & 0xff);
    d[3] = LZO_BYTE((vv >> 24) & 0xff);
#endif
}
References LZO_BYTE, LZO_MEMOPS_COPY4, lzo_memops_TU1p, and lzo_memops_TU4p.
Referenced by lzo_unused_funcs_impl().
lzo_memops_put_ne16()
__lzo_static_forceinline void lzo_memops_put_ne16 (lzo_voidp dd, lzo_uint16_t vv)
{
    LZO_MEMOPS_COPY2(dd, &vv);
}
References LZO_MEMOPS_COPY2.
Referenced by lzo_unused_funcs_impl().
lzo_memops_put_ne32()
__lzo_static_forceinline void lzo_memops_put_ne32 (lzo_voidp dd, lzo_uint32_t vv)
{
    LZO_MEMOPS_COPY4(dd, &vv);
}
References LZO_MEMOPS_COPY4.
Referenced by lzo_unused_funcs_impl().
lzo_unused_funcs_impl() [1/2]
lzo_unused_funcs_impl (void , lzo_bitops_unused_funcs)
{
    LZO_UNUSED_FUNC(lzo_bitops_unused_funcs);
    LZO_UNUSED_FUNC(lzo_bitops_ctlz32_func);
    LZO_UNUSED_FUNC(lzo_bitops_cttz32_func);
#if defined(lzo_uint64_t)
    LZO_UNUSED_FUNC(lzo_bitops_ctlz64_func);
    LZO_UNUSED_FUNC(lzo_bitops_cttz64_func);
#endif
}
References lzo_bitops_ctlz32_func(), lzo_bitops_cttz32_func(), and LZO_UNUSED_FUNC.
lzo_unused_funcs_impl() [2/2]
lzo_unused_funcs_impl (void , lzo_memops_unused_funcs)
{
    LZO_UNUSED_FUNC(lzo_memops_unused_funcs);
    LZO_UNUSED_FUNC(lzo_memops_get_le16);
    LZO_UNUSED_FUNC(lzo_memops_get_le32);
    LZO_UNUSED_FUNC(lzo_memops_get_ne16);
    LZO_UNUSED_FUNC(lzo_memops_get_ne32);
    LZO_UNUSED_FUNC(lzo_memops_put_le16);
    LZO_UNUSED_FUNC(lzo_memops_put_le32);
    LZO_UNUSED_FUNC(lzo_memops_put_ne16);
    LZO_UNUSED_FUNC(lzo_memops_put_ne32);
}
References lzo_memops_get_le32(), lzo_memops_get_ne16(), lzo_memops_get_ne32(), lzo_memops_put_le16(), lzo_memops_put_le32(), lzo_memops_put_ne16(), lzo_memops_put_ne32(), and LZO_UNUSED_FUNC.
lzo_version()
lzo_version (void)
{
    return LZO_VERSION;
}
References LZO_VERSION.
lzo_version_date()
lzo_version_date (void)
{
    return lzo_version_date_;
}
References lzo_version_date_.
Referenced by main().
lzo_version_string()
lzo_version_string (void)
{
    return lzo_version_string_;
}
References lzo_version_string_.
Referenced by main().
LZOLIB_PUBLIC() [1/4]
LZOLIB_PUBLIC (int , lzo_hmemcmp) const
{
#if (LZO_HAVE_MM_HUGE_PTR) || !(HAVE_MEMCMP)
    const lzo_hbyte_p p1 = LZO_STATIC_CAST(const lzo_hbyte_p, s1);
    const lzo_hbyte_p p2 = LZO_STATIC_CAST(const lzo_hbyte_p, s2);
    if __lzo_likely(len > 0) do
    {
        int d = *p1 - *p2;
        if (d != 0)
            return d;
        p1++; p2++;
    } while __lzo_likely(--len > 0);
    return 0;
#else
    return memcmp(s1, s2, len);
#endif
}
References __lzo_likely, lzo_hbyte_p, LZO_STATIC_CAST, and memcmp.
LZOLIB_PUBLIC() [2/4]
LZOLIB_PUBLIC (lzo_hvoid_p , lzo_hmemcpy)
{
#if (LZO_HAVE_MM_HUGE_PTR) || !(HAVE_MEMCPY)
    lzo_hbyte_p p1 = LZO_STATIC_CAST(lzo_hbyte_p, dest);
    const lzo_hbyte_p p2 = LZO_STATIC_CAST(const lzo_hbyte_p, src);
    if (!(len > 0) || p1 == p2)
        return dest;
    do
        *p1++ = *p2++;
    while __lzo_likely(--len > 0);
    return dest;
#else
    return memcpy(dest, src, len);
#endif
}
References __lzo_likely, lzo_hbyte_p, LZO_STATIC_CAST, and memcpy.
LZOLIB_PUBLIC() [3/4]
LZOLIB_PUBLIC (lzo_hvoid_p , lzo_hmemmove)
{
#if (LZO_HAVE_MM_HUGE_PTR) || !(HAVE_MEMMOVE)
    lzo_hbyte_p p1 = LZO_STATIC_CAST(lzo_hbyte_p, dest);
    const lzo_hbyte_p p2 = LZO_STATIC_CAST(const lzo_hbyte_p, src);
    if (!(len > 0) || p1 == p2)
        return dest;
    if (p1 < p2)
    {
        do
            *p1++ = *p2++;
        while __lzo_likely(--len > 0);
    }
    else
    {
        p1 += len;
        p2 += len;
        do
            *--p1 = *--p2;
        while __lzo_likely(--len > 0);
    }
    return dest;
#else
    return memmove(dest, src, len);
#endif
}
References __lzo_likely, lzo_hbyte_p, LZO_STATIC_CAST, and memmove.
LZOLIB_PUBLIC() [4/4]
LZOLIB_PUBLIC (lzo_hvoid_p , lzo_hmemset)
{
#if (LZO_HAVE_MM_HUGE_PTR) || !(HAVE_MEMSET)
    lzo_hbyte_p p = LZO_STATIC_CAST(lzo_hbyte_p, s);
    unsigned char c = LZO_ITRUNC(unsigned char, cc);
    if __lzo_likely(len > 0) do
        *p++ = c;
    while __lzo_likely(--len > 0);
    return s;
#else
    return memset(s, cc, len);
#endif
}
References __lzo_likely, lzo_hbyte_p, LZO_ITRUNC, LZO_STATIC_CAST, and memset.
u2p()
static __lzo_noinline lzo_voidp u2p (lzo_voidp ptr, lzo_uint off) static
{
    return (lzo_voidp) ((lzo_bytep) ptr + off);
}
References lzo_bytep, lzo_voidp, and ptr.
Referenced by _lzo_config_check().
Variable Documentation
__lzo_may_alias
struct lzo_memops_TU8_struct __lzo_may_alias
lzo_copyright_
const char lzo_copyright_[] static
Initial value:
=
    LZO_VERSION_STRING
Referenced by lzo_copyright().
lzo_full_align_t
lzo_full_align_t
lzo_version_date_
const char lzo_version_date_[] = LZO_VERSION_DATE static
Referenced by _lzo_version_date(), and lzo_version_date().
lzo_version_string_
const char lzo_version_string_[] = LZO_VERSION_STRING static
Referenced by _lzo_version_string(), and lzo_version_string().