OrcaSlicer: Slic3r::InternalBridgeDetector Class Reference
Slic3r::InternalBridgeDetector Class Reference
#include <src/libslic3r/InternalBridgeDetector.hpp>
Classes
struct InternalBridgeDirection
Public Member Functions
InternalBridgeDetector (ExPolygon _internal_bridge, const ExPolygons &_fill_no_overlap, coord_t _spacing)
bool detect_angle ()
Public Attributes
ExPolygons fill_no_overlap
ExPolygons internal_bridge_infill
coord_t spacing
double angle = -1.
Private Member Functions
void initialize ()
std::vector< double > bridge_direction_candidates () const
Private Attributes
double resolution = PI/36.0
ExPolygons m_anchor_regions
Detailed Description
Constructor & Destructor Documentation
InternalBridgeDetector()
Slic3r::InternalBridgeDetector::InternalBridgeDetector (ExPolygon _internal_bridge, const ExPolygons & _fill_no_overlap, coord_t _spacing)
                                                                                      :
    fill_no_overlap(_fill_no_overlap),
    spacing(_spacing)
{
    this->internal_bridge_infill.push_back(std::move(_internal_bridge));
    initialize();
}
References initialize(), and internal_bridge_infill.
Member Function Documentation
bridge_direction_candidates()
std::vector< double > Slic3r::InternalBridgeDetector::bridge_direction_candidates () const private
{
    std::vector<double> angles;
    for (int i = 0; i <= PI/this->resolution; ++i)
        angles.push_back(i * this->resolution);
    // we also test angles of each bridge contour
    {
        Lines lines = to_lines(this->internal_bridge_infill);
        for (Lines::const_iterator line = lines.begin(); line != lines.end(); ++line)
            angles.push_back(line->direction());
    }
    // remove duplicates
    double min_resolution = PI/180.0;
    std::sort(angles.begin(), angles.end());
    for (size_t i = 1; i < angles.size(); ++i) {
        if (Slic3r::Geometry::directions_parallel(angles[i], angles[i-1], min_resolution)) {
            angles.erase(angles.begin() + i);
            --i;
        }
    }
    if (Slic3r::Geometry::directions_parallel(angles.front(), angles.back(), min_resolution))
        angles.pop_back();
    return angles;
}
References Slic3r::Geometry::directions_parallel(), internal_bridge_infill, PI, resolution, and Slic3r::to_lines().
Referenced by detect_angle().
detect_angle()
bool Slic3r::InternalBridgeDetector::detect_angle ()
{
    if (this->m_anchor_regions.empty())
        return false;
    std::vector<InternalBridgeDirection> candidates;
    std::vector<double> angles = bridge_direction_candidates();
    candidates.reserve(angles.size());
    for (size_t i = 0; i < angles.size(); ++ i)
        candidates.emplace_back(InternalBridgeDirection(angles[i]));
    Polygons clip_area = offset(this->internal_bridge_infill, 0.5f * float(this->spacing));
    bool have_coverage = false;
    for (size_t i_angle = 0; i_angle < candidates.size(); ++ i_angle)
    {
        const double angle = candidates[i_angle].angle;
        Lines lines;
        {
            BoundingBox bbox = get_extents_rotated(this->m_anchor_regions, - angle);
            // Cover the region with line segments.
            lines.reserve((bbox.max(1) - bbox.min(1) + this->spacing) / this->spacing);
            double s = sin(angle);
            double c = cos(angle);
            for (coord_t y = bbox.min(1); y <= bbox.max(1); y += this->spacing)
                lines.push_back(Line(
                    Point((coord_t)round(c * bbox.min(0) - s * y), (coord_t)round(c * y + s * bbox.min(0))),
                    Point((coord_t)round(c * bbox.max(0) - s * y), (coord_t)round(c * y + s * bbox.max(0)))));
        }
        double total_length = 0;
        double anchored_length = 0;
        double max_length = 0;
        {
            Lines clipped_lines = intersection_ln(lines, clip_area);
            for (size_t i = 0; i < clipped_lines.size(); ++i) {
                const Line &line = clipped_lines[i];
                double len = line.length();
                total_length += len;
                if (expolygons_contain(this->m_anchor_regions, line.a) && expolygons_contain(this->m_anchor_regions, line.b)) {
                    // This line could be anchored.
                    anchored_length += len;
                    max_length = std::max(max_length, len);
                }
            }
        }
        if (anchored_length == 0.)
            continue;
        have_coverage = true;
        candidates[i_angle].coverage = anchored_length/total_length;
        candidates[i_angle].max_length = max_length;
    }
    if (! have_coverage)
        return false;
    std::sort(candidates.begin(), candidates.end());
    size_t i_best = 0;
    this->angle = candidates[i_best].angle;
    if (this->angle >= PI)
        this->angle -= PI;
    return true;
}
References Slic3r::Line::a, angle, Slic3r::Line::b, bridge_direction_candidates(), cos(), Slic3r::expolygons_contain(), Slic3r::get_extents_rotated(), internal_bridge_infill, Slic3r::intersection_ln(), Slic3r::Line::length(), m_anchor_regions, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::offset(), PI, round(), sin(), spacing, and Slic3r::total_length().
Referenced by Slic3r::PrintObject::bridge_over_infill().
initialize()
void Slic3r::InternalBridgeDetector::initialize () private
{
    Polygons grown = offset(this->internal_bridge_infill, float(this->spacing));
    this->m_anchor_regions = diff_ex(grown, offset(this->fill_no_overlap, 10.f));
#ifdef INTERNAL_BRIDGE_DETECTOR_DEBUG_TO_SVG
    static int irun = 0;
    BoundingBox bbox_svg;
    bbox_svg.merge(get_extents(this->internal_bridge_infill));
    bbox_svg.merge(get_extents(this->fill_no_overlap));
    bbox_svg.merge(get_extents(this->m_anchor_regions));
    {
        std::stringstream stri;
        stri << "InternalBridgeDetector_" << irun << ".svg";
        SVG svg(stri.str(), bbox_svg);
        svg.draw(to_polylines(this->internal_bridge_infill), "blue");
        svg.draw(to_polylines(this->fill_no_overlap), "yellow");
        svg.draw(to_polylines(m_anchor_regions), "red");
        svg.Close();
    }
    ++ irun;
#endif
}
References Slic3r::SVG::Close(), Slic3r::diff_ex(), Slic3r::SVG::draw(), fill_no_overlap, Slic3r::get_extents(), internal_bridge_infill, m_anchor_regions, Slic3r::BoundingBoxBase< PointClass >::merge(), Slic3r::offset(), spacing, and Slic3r::to_polylines().
Referenced by InternalBridgeDetector().
Member Data Documentation
angle
double Slic3r::InternalBridgeDetector::angle = -1.
Referenced by Slic3r::PrintObject::bridge_over_infill(), and detect_angle().
fill_no_overlap
ExPolygons Slic3r::InternalBridgeDetector::fill_no_overlap
Referenced by initialize().
internal_bridge_infill
ExPolygons Slic3r::InternalBridgeDetector::internal_bridge_infill
Referenced by InternalBridgeDetector(), bridge_direction_candidates(), detect_angle(), and initialize().
m_anchor_regions
ExPolygons Slic3r::InternalBridgeDetector::m_anchor_regions private
Referenced by detect_angle(), and initialize().
resolution
double Slic3r::InternalBridgeDetector::resolution = PI/36.0 private
Referenced by bridge_direction_candidates().
spacing
coord_t Slic3r::InternalBridgeDetector::spacing
Referenced by detect_angle(), and initialize().
The documentation for this class was generated from the following files:
src/libslic3r/InternalBridgeDetector.hpp
src/libslic3r/InternalBridgeDetector.cpp