OrcaSlicer: Slic3r::WipeTowerIntegration Class Reference
Slic3r::WipeTowerIntegration Class Reference
#include <src/libslic3r/GCode.hpp>
Public Member Functions
WipeTowerIntegration (const PrintConfig &print_config, const int plate_idx, const Vec3d plate_origin, const std::vector< WipeTower::ToolChangeResult > &priming, const std::vector< std::vector< WipeTower::ToolChangeResult > > &tool_changes, const WipeTower::ToolChangeResult &final_purge)
std::string prime (GCode &gcodegen)
void next_layer ()
std::string tool_change (GCode &gcodegen, int extruder_id, bool finish_layer)
std::string finalize (GCode &gcodegen)
std::vector< float > used_filament_length () const
bool is_first_print () const
void set_is_first_print (bool is)
bool enable_timelapse_print () const
Private Member Functions
WipeTowerIntegration & operator= (const WipeTowerIntegration &)
std::string append_tcr (GCode &gcodegen, const WipeTower::ToolChangeResult &tcr, int new_extruder_id, double z=-1.) const
std::string post_process_wipe_tower_moves (const WipeTower::ToolChangeResult &tcr, const Vec2f &translation, float angle) const
Private Attributes
const float m_left
const float m_right
const Vec2f m_wipe_tower_pos
const float m_wipe_tower_rotation
const std::vector< Vec2d > m_extruder_offsets
const std::vector< WipeTower::ToolChangeResult > & m_priming
const std::vector< std::vector< WipeTower::ToolChangeResult > > & m_tool_changes
const WipeTower::ToolChangeResult & m_final_purge
int m_layer_idx
int m_tool_change_idx
double m_last_wipe_tower_print_z = 0.f
Vec3d m_plate_origin
bool m_single_extruder_multi_material
bool m_enable_timelapse_print
bool m_is_first_print
Detailed Description
Constructor & Destructor Documentation
WipeTowerIntegration()
Slic3r::WipeTowerIntegration::WipeTowerIntegration (const PrintConfig & print_config, const int plate_idx, const Vec3d plate_origin, const std::vector< WipeTower::ToolChangeResult > & priming, const std::vector< std::vector< WipeTower::ToolChangeResult > > & tool_changes, const WipeTower::ToolChangeResult & final_purge) inline
                                                                                :
        m_left(/*float(print_config.wipe_tower_x.value)*/ 0.f),
        m_right(float(/*print_config.wipe_tower_x.value +*/ print_config.prime_tower_width.value)),
        m_wipe_tower_pos(float(print_config.wipe_tower_x.get_at(plate_idx)), float(print_config.wipe_tower_y.get_at(plate_idx))),
        m_wipe_tower_rotation(float(print_config.wipe_tower_rotation_angle)),
        m_extruder_offsets(print_config.extruder_offset.values),
        m_priming(priming),
        m_tool_changes(tool_changes),
        m_final_purge(final_purge),
        m_layer_idx(-1),
        m_tool_change_idx(0),
        m_plate_origin(plate_origin),
        m_single_extruder_multi_material(print_config.single_extruder_multi_material),
        m_enable_timelapse_print(print_config.timelapse_type.value == TimelapseType::tlSmooth),
        m_is_first_print(true)
    {}
Member Function Documentation
append_tcr()
std::string Slic3r::WipeTowerIntegration::append_tcr (GCode & gcodegen, const WipeTower::ToolChangeResult & tcr, int new_extruder_id, double z = -1.) const private
    {
        if (new_extruder_id != -1 && new_extruder_id != tcr.new_tool)
            throw Slic3r::InvalidArgument("Error: WipeTowerIntegration::append_tcr was asked to do a toolchange it didn't expect.");
        std::string gcode;
        // Toolchangeresult.gcode assumes the wipe tower corner is at the origin (except for priming lines)
        // We want to rotate and shift all extrusions (gcode postprocessing) and starting and ending position
        float alpha = m_wipe_tower_rotation / 180.f * float(M_PI);
        auto transform_wt_pt = [&alpha, this](const Vec2f& pt) -> Vec2f {
            Vec2f out = Eigen::Rotation2Df(alpha) * pt;
            out += m_wipe_tower_pos;
            return out;
        };
        Vec2f start_pos = tcr.start_pos;
        Vec2f end_pos = tcr.end_pos;
        if (! tcr.priming) {
            start_pos = transform_wt_pt(start_pos);
            end_pos = transform_wt_pt(end_pos);
        }
        Vec2f wipe_tower_offset = tcr.priming ? Vec2f::Zero() : m_wipe_tower_pos;
        float wipe_tower_rotation = tcr.priming ? 0.f : alpha;
        std::string tcr_rotated_gcode = post_process_wipe_tower_moves(tcr, wipe_tower_offset, wipe_tower_rotation);
        // BBS: add partplate logic
        Vec2f plate_origin_2d(m_plate_origin(0), m_plate_origin(1));
        // BBS: toolchange gcode will move to start_pos,
        // so only perform movement when printing sparse partition to support upper layer.
        // start_pos is the position in plate coordinate.
        if (! tcr.priming && tcr.is_finish_first) {
            // Move over the wipe tower.
            gcode += gcodegen.retract();
            gcodegen.m_avoid_crossing_perimeters.use_external_mp_once();
            gcode += gcodegen.travel_to(
                wipe_tower_point_to_object_point(gcodegen, start_pos + plate_origin_2d),
                erMixed,
                "Travel to a Wipe Tower");
            gcode += gcodegen.unretract();
        }
        //BBS: if needed, write the gcode_label_objects_end then priming tower, if the retract, didn't did it.
        gcodegen.m_writer.add_object_end_labels(gcode);
        double current_z = gcodegen.writer().get_position().z();
        if (z == -1.) // in case no specific z was provided, print at current_z pos
            z = current_z;
        if (! is_approx(z, current_z)) {
            gcode += gcodegen.writer().retract();
            gcode += gcodegen.writer().travel_to_z(z, "Travel down to the last wipe tower layer.");
            gcode += gcodegen.writer().unretract();
        }
        // Process the end filament gcode.
        std::string end_filament_gcode_str;
        if (gcodegen.writer().extruder() != nullptr) {
            // Process the custom filament_end_gcode in case of single_extruder_multi_material.
            unsigned int        old_extruder_id = gcodegen.writer().extruder()->id();
            const std::string& filament_end_gcode = gcodegen.config().filament_end_gcode.get_at(old_extruder_id);
            if (gcodegen.writer().extruder() != nullptr && !filament_end_gcode.empty()) {
                end_filament_gcode_str = gcodegen.placeholder_parser_process("filament_end_gcode", filament_end_gcode, old_extruder_id);
                check_add_eol(end_filament_gcode_str);
            }
        }
        //BBS: increase toolchange count
        gcodegen.m_toolchange_count++;
        // BBS: should be placed before toolchange parsing
        std::string toolchange_retract_str = gcodegen.retract(true, false);
        check_add_eol(toolchange_retract_str);
        // Process the custom change_filament_gcode. If it is empty, provide a simple Tn command to change the filament.
        // Otherwise, leave control to the user completely.
        std::string toolchange_gcode_str;
        const std::string& change_filament_gcode = gcodegen.config().change_filament_gcode.value;
//        m_max_layer_z = std::max(m_max_layer_z, tcr.print_z);
        if (! change_filament_gcode.empty()) {
            DynamicConfig config;
            int previous_extruder_id = gcodegen.writer().extruder() ? (int)gcodegen.writer().extruder()->id() : -1;
            config.set_key_value("previous_extruder", new ConfigOptionInt(previous_extruder_id));
            config.set_key_value("next_extruder", new ConfigOptionInt((int)new_extruder_id));
            config.set_key_value("layer_num", new ConfigOptionInt(gcodegen.m_layer_index));
            config.set_key_value("layer_z", new ConfigOptionFloat(tcr.print_z));
            config.set_key_value("toolchange_z", new ConfigOptionFloat(z));
//            config.set_key_value("max_layer_z", new ConfigOptionFloat(m_max_layer_z));
            // BBS
            {
                GCodeWriter& gcode_writer = gcodegen.m_writer;
                FullPrintConfig& full_config = gcodegen.m_config;
                float old_retract_length = gcode_writer.extruder() != nullptr ? full_config.retraction_length.get_at(previous_extruder_id) : 0;
                float new_retract_length = full_config.retraction_length.get_at(new_extruder_id);
                float old_retract_length_toolchange = gcode_writer.extruder() != nullptr ? full_config.retract_length_toolchange.get_at(previous_extruder_id) : 0;
                float new_retract_length_toolchange = full_config.retract_length_toolchange.get_at(new_extruder_id);
                int old_filament_temp = gcode_writer.extruder() != nullptr ? (gcodegen.on_first_layer()? full_config.nozzle_temperature_initial_layer.get_at(previous_extruder_id) : full_config.nozzle_temperature.get_at(previous_extruder_id)) : 210;
                int new_filament_temp = gcodegen.on_first_layer() ? full_config.nozzle_temperature_initial_layer.get_at(new_extruder_id) : full_config.nozzle_temperature.get_at(new_extruder_id);
                Vec3d nozzle_pos = gcode_writer.get_position();
                float purge_volume = tcr.purge_volume < EPSILON ? 0 : std::max(tcr.purge_volume, g_min_purge_volume);
                float filament_area = float((M_PI / 4.f) * pow(full_config.filament_diameter.get_at(new_extruder_id), 2));
                float purge_length = purge_volume / filament_area;
                int old_filament_e_feedrate = gcode_writer.extruder() != nullptr ? (int)(60.0 * full_config.filament_max_volumetric_speed.get_at(previous_extruder_id) / filament_area) : 200;
                old_filament_e_feedrate = old_filament_e_feedrate == 0 ? 100 : old_filament_e_feedrate;
                int new_filament_e_feedrate = (int)(60.0 * full_config.filament_max_volumetric_speed.get_at(new_extruder_id) / filament_area);
                new_filament_e_feedrate = new_filament_e_feedrate == 0 ? 100 : new_filament_e_feedrate;
                config.set_key_value("max_layer_z", new ConfigOptionFloat(gcodegen.m_max_layer_z));
                config.set_key_value("relative_e_axis", new ConfigOptionBool(full_config.use_relative_e_distances));
                config.set_key_value("toolchange_count", new ConfigOptionInt((int)gcodegen.m_toolchange_count));
                //BBS: fan speed is useless placeholer now, but we don't remove it to avoid
                //slicing error in old change_filament_gcode in old 3MF
                config.set_key_value("fan_speed", new ConfigOptionInt((int)0));
                config.set_key_value("old_retract_length", new ConfigOptionFloat(old_retract_length));
                config.set_key_value("new_retract_length", new ConfigOptionFloat(new_retract_length));
                config.set_key_value("old_retract_length_toolchange", new ConfigOptionFloat(old_retract_length_toolchange));
                config.set_key_value("new_retract_length_toolchange", new ConfigOptionFloat(new_retract_length_toolchange));
                config.set_key_value("old_filament_temp", new ConfigOptionInt(old_filament_temp));
                config.set_key_value("new_filament_temp", new ConfigOptionInt(new_filament_temp));
                config.set_key_value("x_after_toolchange", new ConfigOptionFloat(start_pos(0)));
                config.set_key_value("y_after_toolchange", new ConfigOptionFloat(start_pos(1)));
                config.set_key_value("z_after_toolchange", new ConfigOptionFloat(nozzle_pos(2)));
                config.set_key_value("first_flush_volume", new ConfigOptionFloat(purge_length / 2.f));
                config.set_key_value("second_flush_volume", new ConfigOptionFloat(purge_length / 2.f));
                config.set_key_value("old_filament_e_feedrate", new ConfigOptionInt(old_filament_e_feedrate));
                config.set_key_value("new_filament_e_feedrate", new ConfigOptionInt(new_filament_e_feedrate));
                config.set_key_value("travel_point_1_x", new ConfigOptionFloat(float(travel_point_1.x())));
                config.set_key_value("travel_point_1_y", new ConfigOptionFloat(float(travel_point_1.y())));
                config.set_key_value("travel_point_2_x", new ConfigOptionFloat(float(travel_point_2.x())));
                config.set_key_value("travel_point_2_y", new ConfigOptionFloat(float(travel_point_2.y())));
                config.set_key_value("travel_point_3_x", new ConfigOptionFloat(float(travel_point_3.x())));
                config.set_key_value("travel_point_3_y", new ConfigOptionFloat(float(travel_point_3.y())));
                int flush_count = std::min(g_max_flush_count, (int)std::round(purge_volume / g_purge_volume_one_time));
                float flush_unit = purge_length / flush_count;
                int flush_idx = 0;
                for (; flush_idx < flush_count; flush_idx++) {
                    char key_value[64] = { 0 };
                    snprintf(key_value, sizeof(key_value), "flush_length_%d", flush_idx + 1);
                    config.set_key_value(key_value, new ConfigOptionFloat(flush_unit));
                }
                for (; flush_idx < g_max_flush_count; flush_idx++) {
                    char key_value[64] = { 0 };
                    snprintf(key_value, sizeof(key_value), "flush_length_%d", flush_idx + 1);
                    config.set_key_value(key_value, new ConfigOptionFloat(0.f));
                }
            }
            toolchange_gcode_str = gcodegen.placeholder_parser_process("change_filament_gcode", change_filament_gcode, new_extruder_id, &config);
            check_add_eol(toolchange_gcode_str);
            // retract before toolchange
            toolchange_gcode_str = toolchange_retract_str + toolchange_gcode_str;
            //BBS
            {
                //BBS: current position and fan_speed is unclear after interting change_filament_gcode
                check_add_eol(toolchange_gcode_str);
                toolchange_gcode_str += ";_FORCE_RESUME_FAN_SPEED\n";
                gcodegen.writer().set_current_position_clear(false);
                //BBS: check whether custom gcode changes the z position. Update if changed
                double temp_z_after_tool_change;
                if (GCodeProcessor::get_last_z_from_gcode(toolchange_gcode_str, temp_z_after_tool_change)) {
                    Vec3d pos = gcodegen.writer().get_position();
                    pos(2) = temp_z_after_tool_change;
                    gcodegen.writer().set_position(pos);
                }
            }
            // move to start_pos for wiping after toolchange
            std::string start_pos_str;
            start_pos_str = gcodegen.travel_to(wipe_tower_point_to_object_point(gcodegen, start_pos + plate_origin_2d), erMixed, "Move to start pos");
            check_add_eol(start_pos_str);
            toolchange_gcode_str += start_pos_str;
            // unretract before wiping
            toolchange_gcode_str += gcodegen.unretract();
            check_add_eol(toolchange_gcode_str);
        }
        std::string toolchange_command;
        if (tcr.priming || (new_extruder_id >= 0 && gcodegen.writer().need_toolchange(new_extruder_id)))
            toolchange_command = gcodegen.writer().toolchange(new_extruder_id);
        if (!custom_gcode_changes_tool(toolchange_gcode_str, gcodegen.writer().toolchange_prefix(), new_extruder_id))
            toolchange_gcode_str += toolchange_command;
        else {
            // We have informed the m_writer about the current extruder_id, we can ignore the generated G-code.
        }
        gcodegen.placeholder_parser().set("current_extruder", new_extruder_id);
        // Process the start filament gcode.
        std::string start_filament_gcode_str;
        const std::string& filament_start_gcode = gcodegen.config().filament_start_gcode.get_at(new_extruder_id);
        if (!filament_start_gcode.empty()) {
            // Process the filament_start_gcode for the active filament only.
            DynamicConfig config;
            config.set_key_value("filament_extruder_id", new ConfigOptionInt(new_extruder_id));
            start_filament_gcode_str = gcodegen.placeholder_parser_process("filament_start_gcode", filament_start_gcode, new_extruder_id, &config);
            check_add_eol(start_filament_gcode_str);
        }
        // Insert the end filament, toolchange, and start filament gcode into the generated gcode.
        DynamicConfig config;
        config.set_key_value("filament_end_gcode", new ConfigOptionString(end_filament_gcode_str));
        config.set_key_value("change_filament_gcode", new ConfigOptionString(toolchange_gcode_str));
        config.set_key_value("filament_start_gcode", new ConfigOptionString(start_filament_gcode_str));
        std::string tcr_gcode, tcr_escaped_gcode = gcodegen.placeholder_parser_process("tcr_rotated_gcode", tcr_rotated_gcode, new_extruder_id, &config);
        unescape_string_cstyle(tcr_escaped_gcode, tcr_gcode);
        gcode += tcr_gcode;
        check_add_eol(toolchange_gcode_str);
        //SoftFever: set new PA for new filament
        if (gcodegen.config().enable_pressure_advance.get_at(new_extruder_id)) {
            gcode += gcodegen.writer().set_pressure_advance(gcodegen.config().pressure_advance.get_at(new_extruder_id));
        }
        // A phony move to the end position at the wipe tower.
        gcodegen.writer().travel_to_xy(end_pos.cast<double>());
        gcodegen.set_last_pos(wipe_tower_point_to_object_point(gcodegen, end_pos + plate_origin_2d));
        if (!is_approx(z, current_z)) {
            gcode += gcodegen.writer().retract();
            gcode += gcodegen.writer().travel_to_z(current_z, "Travel back up to the topmost object layer.");
            gcode += gcodegen.writer().unretract();
        }
        else {
            // Prepare a future wipe.
            gcodegen.m_wipe.reset_path();
            for (const Vec2f& wipe_pt : tcr.wipe_path)
                gcodegen.m_wipe.path.points.emplace_back(wipe_tower_point_to_object_point(gcodegen, transform_wt_pt(wipe_pt)));
        }
        // Let the planner know we are traveling between objects.
        gcodegen.m_avoid_crossing_perimeters.use_external_mp_once();
        return gcode;
    }
References Slic3r::GCodeWriter::add_object_end_labels(), Slic3r::check_add_eol(), Slic3r::GCode::config(), Slic3r::custom_gcode_changes_tool(), Slic3r::WipeTower::ToolChangeResult::end_pos, EPSILON, Slic3r::erMixed, Slic3r::GCodeWriter::extruder(), Slic3r::g_max_flush_count, Slic3r::g_min_purge_volume, Slic3r::g_purge_volume_one_time, Slic3r::GCodeProcessor::get_last_z_from_gcode(), Slic3r::GCodeWriter::get_position(), Slic3r::Extruder::id(), int, Slic3r::is_approx(), Slic3r::WipeTower::ToolChangeResult::is_finish_first, Slic3r::GCode::m_avoid_crossing_perimeters, Slic3r::GCode::m_config, Slic3r::GCode::m_layer_index, Slic3r::GCode::m_max_layer_z, M_PI, m_plate_origin, Slic3r::GCode::m_toolchange_count, Slic3r::GCode::m_wipe, m_wipe_tower_pos, m_wipe_tower_rotation, Slic3r::GCode::m_writer, Slic3r::GCodeWriter::need_toolchange(), Slic3r::WipeTower::ToolChangeResult::new_tool, Slic3r::GCode::on_first_layer(), out, Slic3r::Wipe::path, Slic3r::GCode::placeholder_parser(), Slic3r::GCode::placeholder_parser_process(), Slic3r::MultiPoint::points, post_process_wipe_tower_moves(), Slic3r::WipeTower::ToolChangeResult::priming, Slic3r::WipeTower::ToolChangeResult::print_z, Slic3r::WipeTower::ToolChangeResult::purge_volume, Slic3r::Wipe::reset_path(), Slic3r::GCodeWriter::retract(), Slic3r::GCode::retract(), Slic3r::Extruder::retract_length_toolchange(), Slic3r::Extruder::retraction_length(), Slic3r::PlaceholderParser::set(), Slic3r::GCodeWriter::set_current_position_clear(), Slic3r::DynamicConfig::set_key_value(), Slic3r::GCode::set_last_pos(), Slic3r::GCodeWriter::set_position(), Slic3r::GCodeWriter::set_pressure_advance(), Slic3r::WipeTower::ToolChangeResult::start_pos, Slic3r::GCodeWriter::toolchange(), Slic3r::GCodeWriter::toolchange_prefix(), Slic3r::travel_point_1, Slic3r::travel_point_2, Slic3r::travel_point_3, Slic3r::GCode::travel_to(), Slic3r::GCodeWriter::travel_to_xy(), Slic3r::GCodeWriter::travel_to_z(), Slic3r::unescape_string_cstyle(), Slic3r::GCode::unretract(), Slic3r::GCodeWriter::unretract(), Slic3r::AvoidCrossingPerimeters::use_external_mp_once(), Slic3r::WipeTower::ToolChangeResult::wipe_path, Slic3r::wipe_tower_point_to_object_point(), and Slic3r::GCode::writer().
Referenced by finalize(), prime(), and tool_change().
enable_timelapse_print()
bool Slic3r::WipeTowerIntegration::enable_timelapse_print () const inline
{ return m_enable_timelapse_print; }
References m_enable_timelapse_print.
finalize()
std::string Slic3r::WipeTowerIntegration::finalize (GCode & gcodegen)
    {
        std::string gcode;
        // BBS
#if 0
        if (std::abs(gcodegen.writer().get_position()(2) - m_final_purge.print_z) > EPSILON)
            gcode += gcodegen.change_layer(m_final_purge.print_z);
        gcode += append_tcr(gcodegen, m_final_purge, -1);
#endif
        return gcode;
    }
References append_tcr(), Slic3r::GCode::change_layer(), EPSILON, Slic3r::GCodeWriter::get_position(), m_final_purge, Slic3r::WipeTower::ToolChangeResult::print_z, and Slic3r::GCode::writer().
is_first_print()
bool Slic3r::WipeTowerIntegration::is_first_print () const inline
{ return m_is_first_print;}
References m_is_first_print.
next_layer()
void Slic3r::WipeTowerIntegration::next_layer () inline
{ ++ m_layer_idx; m_tool_change_idx = 0; }
References m_layer_idx, and m_tool_change_idx.
operator=()
WipeTowerIntegration & Slic3r::WipeTowerIntegration::operator= (const WipeTowerIntegration &) private
post_process_wipe_tower_moves()
std::string Slic3r::WipeTowerIntegration::post_process_wipe_tower_moves (const WipeTower::ToolChangeResult & tcr, const Vec2f & translation, float angle) const private
    {
        Vec2f extruder_offset;
        if (m_single_extruder_multi_material)
            extruder_offset = m_extruder_offsets[0].cast<float>();
        else
            extruder_offset = m_extruder_offsets[tcr.initial_tool].cast<float>();
        std::istringstream gcode_str(tcr.gcode);
        std::string gcode_out;
        std::string line;
        Vec2f pos = tcr.start_pos;
        Vec2f transformed_pos = pos;
        Vec2f old_pos(-1000.1f, -1000.1f);
        while (gcode_str) {
            std::getline(gcode_str, line);  // we read the gcode line by line
            // All G1 commands should be translated and rotated. X and Y coords are
            // only pushed to the output when they differ from last time.
            // WT generator can override this by appending the never_skip_tag
            if (line.find("G1 ") == 0) {
                bool never_skip = false;
                auto it = line.find(WipeTower::never_skip_tag());
                if (it != std::string::npos) {
                    // remove the tag and remember we saw it
                    never_skip = true;
                    line.erase(it, it + WipeTower::never_skip_tag().size());
                }
                std::ostringstream line_out;
                std::istringstream line_str(line);
                line_str >> std::noskipws;  // don't skip whitespace
                char ch = 0;
                while (line_str >> ch) {
                    if (ch == 'X' || ch == 'Y')
                        line_str >> (ch == 'X' ? pos.x() : pos.y());
                    else
                        line_out << ch;
                }
                transformed_pos = Eigen::Rotation2Df(angle) * pos + translation;
                if (transformed_pos != old_pos || never_skip) {
                    line = line_out.str();
                    std::ostringstream oss;
                    oss << std::fixed << std::setprecision(3) << "G1 ";
                    if (transformed_pos.x() != old_pos.x() || never_skip)
                        oss << " X" << transformed_pos.x() - extruder_offset.x();
                    if (transformed_pos.y() != old_pos.y() || never_skip)
                        oss << " Y" << transformed_pos.y() - extruder_offset.y();
                    oss << " ";
                    line.replace(line.find("G1 "), 3, oss.str());
                    old_pos = transformed_pos;
                }
            }
            gcode_out += line + "\n";
            // If this was a toolchange command, we should change current extruder offset
            if (line == "[change_filament_gcode]") {
                // BBS
                if (!m_single_extruder_multi_material) {
                    extruder_offset = m_extruder_offsets[tcr.new_tool].cast<float>();
                    // If the extruder offset changed, add an extra move so everything is continuous
                    if (extruder_offset != m_extruder_offsets[tcr.initial_tool].cast<float>()) {
                        std::ostringstream oss;
                        oss << std::fixed << std::setprecision(3)
                            << "G1 X" << transformed_pos.x() - extruder_offset.x()
                            << " Y" << transformed_pos.y() - extruder_offset.y()
                            << "\n";
                        gcode_out += oss.str();
                    }
                }
            }
        }
        return gcode_out;
    }
References Slic3r::angle(), Slic3r::extruder_offset(), Slic3r::WipeTower::ToolChangeResult::gcode, Slic3r::WipeTower::ToolChangeResult::initial_tool, m_extruder_offsets, m_single_extruder_multi_material, Slic3r::WipeTower::never_skip_tag(), Slic3r::WipeTower::ToolChangeResult::new_tool, size, and Slic3r::WipeTower::ToolChangeResult::start_pos.
Referenced by append_tcr().
prime()
std::string Slic3r::WipeTowerIntegration::prime (GCode & gcodegen)
    {
        std::string gcode;
#if 0
        for (const WipeTower::ToolChangeResult& tcr : m_priming) {
            if (! tcr.extrusions.empty())
                gcode += append_tcr(gcodegen, tcr, tcr.new_tool);
        }
#endif
        return gcode;
    }
References append_tcr(), and m_priming.
set_is_first_print()
void Slic3r::WipeTowerIntegration::set_is_first_print (bool is) inline
{ m_is_first_print = is; }
References m_is_first_print.
tool_change()
std::string Slic3r::WipeTowerIntegration::tool_change (GCode & gcodegen, int extruder_id, bool finish_layer)
    {
        std::string gcode;
        assert(m_layer_idx >= 0);
        if (m_layer_idx >= (int) m_tool_changes.size()) return gcode;
        // Calculate where the wipe tower layer will be printed. -1 means that print z will not change,
        // resulting in a wipe tower with sparse layers.
        double wipe_tower_z  = -1;
        bool   ignore_sparse = false;
        if (gcodegen.config().wipe_tower_no_sparse_layers.value) {
            wipe_tower_z  = m_last_wipe_tower_print_z;
            ignore_sparse = (m_tool_changes[m_layer_idx].size() == 1 && m_tool_changes[m_layer_idx].front().initial_tool == m_tool_changes[m_layer_idx].front().new_tool);
            if (m_tool_change_idx == 0 && !ignore_sparse)
                wipe_tower_z = m_last_wipe_tower_print_z + m_tool_changes[m_layer_idx].front().layer_height;
        }
        if (m_enable_timelapse_print && m_is_first_print) {
            gcode += append_tcr(gcodegen, m_tool_changes[m_layer_idx][0], m_tool_changes[m_layer_idx][0].new_tool, wipe_tower_z);
            m_tool_change_idx++;
            m_is_first_print = false;
        }
        if (gcodegen.writer().need_toolchange(extruder_id) || finish_layer) {
            if (!(size_t(m_tool_change_idx) < m_tool_changes[m_layer_idx].size())) throw Slic3r::RuntimeError("Wipe tower generation failed, possibly due to empty first layer.");
            if (!ignore_sparse) {
                gcode += append_tcr(gcodegen, m_tool_changes[m_layer_idx][m_tool_change_idx++], extruder_id, wipe_tower_z);
                m_last_wipe_tower_print_z = wipe_tower_z;
            }
        }
        return gcode;
    }
References append_tcr(), Slic3r::GCode::config(), m_enable_timelapse_print, m_is_first_print, m_last_wipe_tower_print_z, m_layer_idx, m_tool_change_idx, m_tool_changes, Slic3r::GCodeWriter::need_toolchange(), size, and Slic3r::GCode::writer().
used_filament_length()
std::vector< float > Slic3r::WipeTowerIntegration::used_filament_length () const
Member Data Documentation
m_enable_timelapse_print
bool Slic3r::WipeTowerIntegration::m_enable_timelapse_print private
Referenced by enable_timelapse_print(), and tool_change().
m_extruder_offsets
const std::vector<Vec2d> Slic3r::WipeTowerIntegration::m_extruder_offsets private
Referenced by post_process_wipe_tower_moves().
m_final_purge
const WipeTower::ToolChangeResult& Slic3r::WipeTowerIntegration::m_final_purge private
Referenced by finalize().
m_is_first_print
bool Slic3r::WipeTowerIntegration::m_is_first_print private
Referenced by is_first_print(), set_is_first_print(), and tool_change().
m_last_wipe_tower_print_z
double Slic3r::WipeTowerIntegration::m_last_wipe_tower_print_z = 0.f private
Referenced by tool_change().
m_layer_idx
int Slic3r::WipeTowerIntegration::m_layer_idx private
Referenced by next_layer(), and tool_change().
m_left
const float Slic3r::WipeTowerIntegration::m_left private
m_plate_origin
Vec3d Slic3r::WipeTowerIntegration::m_plate_origin private
Referenced by append_tcr().
m_priming
const std::vector<WipeTower::ToolChangeResult>& Slic3r::WipeTowerIntegration::m_priming private
Referenced by prime().
m_right
const float Slic3r::WipeTowerIntegration::m_right private
m_single_extruder_multi_material
bool Slic3r::WipeTowerIntegration::m_single_extruder_multi_material private
Referenced by post_process_wipe_tower_moves().
m_tool_change_idx
int Slic3r::WipeTowerIntegration::m_tool_change_idx private
Referenced by next_layer(), and tool_change().
m_tool_changes
const std::vector<std::vector<WipeTower::ToolChangeResult> >& Slic3r::WipeTowerIntegration::m_tool_changes private
Referenced by tool_change().
m_wipe_tower_pos
const Vec2f Slic3r::WipeTowerIntegration::m_wipe_tower_pos private
Referenced by append_tcr().
m_wipe_tower_rotation
const float Slic3r::WipeTowerIntegration::m_wipe_tower_rotation private
Referenced by append_tcr().
The documentation for this class was generated from the following files:
src/libslic3r/GCode.hpp
src/libslic3r/GCode.cpp