OrcaSlicer: Slic3r::MeshBoolean::cgal Namespace Reference
Slic3r::MeshBoolean::cgal Namespace Reference
Classes
struct CGALMesh
struct CGALMeshDeleter
Typedefs
using EpecKernel = CGAL::Exact_predicates_exact_constructions_kernel
using EpicKernel = CGAL::Exact_predicates_inexact_constructions_kernel
using _EpicMesh = CGAL::Surface_mesh< EpicKernel::Point_3 >
using _EpecMesh = CGAL::Surface_mesh< EpecKernel::Point_3 >
using CGALMeshPtr = std::unique_ptr< CGALMesh, CGALMeshDeleter >
Functions
void save_CGALMesh (const std::string &fname, const CGALMesh &cgal_mesh)
template<class _Mesh >
void triangle_mesh_to_cgal (const TriangleMesh &M, _Mesh &out)
template<class _Mesh >
void triangle_mesh_to_cgal (const std::vector< stl_vertex > &V, const std::vector< stl_triangle_vertex_indices > &F, _Mesh &out)
Vec3f to_vec3f (const _EpicMesh::Point &v)
Vec3f to_vec3f (const _EpecMesh::Point &v)
template<class _Mesh >
indexed_triangle_set cgal_to_indexed_triangle_set (const _Mesh &cgalmesh)
std::unique_ptr< CGALMesh, CGALMeshDeleter > triangle_mesh_to_cgal (const std::vector< stl_vertex > &V, const std::vector< stl_triangle_vertex_indices > &F)
TriangleMesh cgal_to_triangle_mesh (const CGALMesh &cgalmesh)
indexed_triangle_set cgal_to_indexed_triangle_set (const CGALMesh &cgalmesh)
static bool _cgal_diff (CGALMesh &A, CGALMesh &B, CGALMesh &R)
static bool _cgal_union (CGALMesh &A, CGALMesh &B, CGALMesh &R)
static bool _cgal_intersection (CGALMesh &A, CGALMesh &B, CGALMesh &R)
template<class Op >
void _cgal_do (Op &&op, CGALMesh &A, CGALMesh &B)
void minus (CGALMesh &A, CGALMesh &B)
void plus (CGALMesh &A, CGALMesh &B)
void intersect (CGALMesh &A, CGALMesh &B)
bool does_self_intersect (const CGALMesh &mesh)
void segment (CGALMesh &src, std::vector< CGALMesh > &dst, double smoothing_alpha=0.5, int segment_number=5)
std::vector< TriangleMesh > segment (const TriangleMesh &src, double smoothing_alpha, int segment_number)
void merge (std::vector< _EpicMesh > &srcs, _EpicMesh &dst)
TriangleMesh merge (std::vector< TriangleMesh > meshes)
template<class Op >
void _mesh_boolean_do (Op &&op, indexed_triangle_set &A, const indexed_triangle_set &B)
template<class Op >
void _mesh_boolean_do (Op &&op, TriangleMesh &A, const TriangleMesh &B)
void minus (TriangleMesh &A, const TriangleMesh &B)
void plus (TriangleMesh &A, const TriangleMesh &B)
void intersect (TriangleMesh &A, const TriangleMesh &B)
void minus (indexed_triangle_set &A, const indexed_triangle_set &B)
void plus (indexed_triangle_set &A, const indexed_triangle_set &B)
void intersect (indexed_triangle_set &A, const indexed_triangle_set &B)
bool does_self_intersect (const TriangleMesh &mesh)
bool does_bound_a_volume (const CGALMesh &mesh)
bool empty (const CGALMesh &mesh)
CGALMeshPtr clone (const CGALMesh &m)
CGALMeshPtr triangle_mesh_to_cgal (const indexed_triangle_set &M)
CGALMeshPtr triangle_mesh_to_cgal (const TriangleMesh &M)
Typedef Documentation
_EpecMesh
using Slic3r::MeshBoolean::cgal::_EpecMesh = typedef CGAL::Surface_mesh<EpecKernel::Point_3>
_EpicMesh
using Slic3r::MeshBoolean::cgal::_EpicMesh = typedef CGAL::Surface_mesh<EpicKernel::Point_3>
CGALMeshPtr
using Slic3r::MeshBoolean::cgal::CGALMeshPtr = typedef std::unique_ptr<CGALMesh, CGALMeshDeleter>
EpecKernel
using Slic3r::MeshBoolean::cgal::EpecKernel = typedef CGAL::Exact_predicates_exact_constructions_kernel
EpicKernel
using Slic3r::MeshBoolean::cgal::EpicKernel = typedef CGAL::Exact_predicates_inexact_constructions_kernel
Function Documentation
_cgal_diff()
static bool Slic3r::MeshBoolean::cgal::_cgal_diff (CGALMesh & A, CGALMesh & B, CGALMesh & R) static
{
    const auto &p = CGALParams::throw_on_self_intersection(true);
    return CGALProc::corefine_and_compute_difference(A.m, B.m, R.m, p, p);
}
References _cgal_diff(), and Slic3r::MeshBoolean::cgal::CGALMesh::m.
Referenced by _cgal_diff(), minus(), minus(), and minus().
_cgal_do()
template<class Op > void Slic3r::MeshBoolean::cgal::_cgal_do (Op && op, CGALMesh & A, CGALMesh & B)
{
    bool success = false;
    bool hw_fail = false;
    try {
        CGALMesh result;
        try_catch_signal({SIGSEGV, SIGFPE}, [&success, &A, &B, &result, &op] {
            success = op(A, B, result);
        }, [&] { hw_fail = true; });
        A = std::move(result);      // In-place operation does not work
    } catch (...) {
        success = false;
    }
    if (hw_fail)
        throw Slic3r::HardCrash("CGAL mesh boolean operation crashed.");
    if (! success)
        throw Slic3r::RuntimeError("CGAL mesh boolean operation failed.");
}
References _cgal_do(), and Slic3r::try_catch_signal().
Referenced by _cgal_do(), _mesh_boolean_do(), _mesh_boolean_do(), intersect(), minus(), and plus().
_cgal_intersection()
static bool Slic3r::MeshBoolean::cgal::_cgal_intersection (CGALMesh & A, CGALMesh & B, CGALMesh & R) static
{
    const auto &p = CGALParams::throw_on_self_intersection(true);
    return CGALProc::corefine_and_compute_intersection(A.m, B.m, R.m, p, p);
}
References _cgal_intersection(), and Slic3r::MeshBoolean::cgal::CGALMesh::m.
Referenced by _cgal_intersection(), intersect(), intersect(), and intersect().
_cgal_union()
static bool Slic3r::MeshBoolean::cgal::_cgal_union (CGALMesh & A, CGALMesh & B, CGALMesh & R) static
{
    const auto &p = CGALParams::throw_on_self_intersection(true);
    return CGALProc::corefine_and_compute_union(A.m, B.m, R.m, p, p);
}
References _cgal_union(), and Slic3r::MeshBoolean::cgal::CGALMesh::m.
Referenced by _cgal_union(), plus(), plus(), and plus().
_mesh_boolean_do() [1/2]
template<class Op > void Slic3r::MeshBoolean::cgal::_mesh_boolean_do (Op && op, indexed_triangle_set & A, const indexed_triangle_set & B)
{
    CGALMesh meshA;
    CGALMesh meshB;
    triangle_mesh_to_cgal(A.vertices, A.indices, meshA.m);
    triangle_mesh_to_cgal(B.vertices, B.indices, meshB.m);
    _cgal_do(op, meshA, meshB);
    A = cgal_to_indexed_triangle_set(meshA.m);
}
References _cgal_do(), _mesh_boolean_do(), cgal_to_indexed_triangle_set(), indexed_triangle_set::indices, Slic3r::MeshBoolean::cgal::CGALMesh::m, triangle_mesh_to_cgal(), and indexed_triangle_set::vertices.
Referenced by _mesh_boolean_do(), _mesh_boolean_do(), intersect(), intersect(), minus(), minus(), plus(), and plus().
_mesh_boolean_do() [2/2]
template<class Op > void Slic3r::MeshBoolean::cgal::_mesh_boolean_do (Op && op, TriangleMesh & A, const TriangleMesh & B)
{
    CGALMesh meshA;
    CGALMesh meshB;
    triangle_mesh_to_cgal(A.its.vertices, A.its.indices, meshA.m);
    triangle_mesh_to_cgal(B.its.vertices, B.its.indices, meshB.m);
    _cgal_do(op, meshA, meshB);
    A = cgal_to_triangle_mesh(meshA);
}
References _cgal_do(), _mesh_boolean_do(), cgal_to_triangle_mesh(), indexed_triangle_set::indices, Slic3r::TriangleMesh::its, Slic3r::MeshBoolean::cgal::CGALMesh::m, triangle_mesh_to_cgal(), and indexed_triangle_set::vertices.
cgal_to_indexed_triangle_set() [1/2]
template<class _Mesh > indexed_triangle_set Slic3r::MeshBoolean::cgal::cgal_to_indexed_triangle_set (const _Mesh & cgalmesh)
{
    indexed_triangle_set its;
    its.vertices.reserve(cgalmesh.num_vertices());
    its.indices.reserve(cgalmesh.num_faces());
    const auto &faces = cgalmesh.faces();
    const auto &vertices = cgalmesh.vertices();
    int vsize = int(vertices.size());
    for (auto &vi : vertices) {
        auto &v = cgalmesh.point(vi); // Don't ask...
        its.vertices.emplace_back(to_vec3f(v));
    }
    for (auto &face : faces) {
        auto vtc = cgalmesh.vertices_around_face(cgalmesh.halfedge(face));
        int i = 0;
        Vec3i facet;
        for (auto v : vtc) {
            int iv = v;
            if (i > 2 || iv < 0 || iv >= vsize) { i = 0; break; }
            facet(i++) = iv;
        }
        if (i == 3)
            its.indices.emplace_back(facet);
    }
    return its;
}
References cgal_to_indexed_triangle_set(), indexed_triangle_set::indices, int, Slic3r::to_vec3f(), and indexed_triangle_set::vertices.
Referenced by _mesh_boolean_do(), cgal_to_indexed_triangle_set(), cgal_to_indexed_triangle_set(), and cgal_to_triangle_mesh().
cgal_to_indexed_triangle_set() [2/2]
indexed_triangle_set Slic3r::MeshBoolean::cgal::cgal_to_indexed_triangle_set (const CGALMesh & cgalmesh)
{
    return cgal_to_indexed_triangle_set(cgalmesh.m);
}
References cgal_to_indexed_triangle_set(), and Slic3r::MeshBoolean::cgal::CGALMesh::m.
cgal_to_triangle_mesh()
TriangleMesh Slic3r::MeshBoolean::cgal::cgal_to_triangle_mesh (const CGALMesh & cgalmesh)
{
    return TriangleMesh{cgal_to_indexed_triangle_set(cgalmesh.m)};
}
References cgal_to_indexed_triangle_set(), cgal_to_triangle_mesh(), and Slic3r::MeshBoolean::cgal::CGALMesh::m.
Referenced by _mesh_boolean_do(), cgal_to_triangle_mesh(), Slic3r::GUI::Plater::combine_mesh_fff(), merge(), and segment().
clone()
CGALMeshPtr Slic3r::MeshBoolean::cgal::clone (const CGALMesh & m)
{
    return CGALMeshPtr{new CGALMesh{m}};
}
References clone().
Referenced by clone().
does_bound_a_volume()
bool Slic3r::MeshBoolean::cgal::does_bound_a_volume (const CGALMesh & mesh)
{
    return CGAL::is_closed(mesh.m) && CGALProc::does_bound_a_volume(mesh.m);
}
References does_bound_a_volume(), and Slic3r::MeshBoolean::cgal::CGALMesh::m.
Referenced by Slic3r::csg::check_csgmesh_booleans(), and does_bound_a_volume().
does_self_intersect() [1/2]
bool Slic3r::MeshBoolean::cgal::does_self_intersect (const CGALMesh & mesh)
{ return CGALProc::does_self_intersect(mesh.m); }
References does_self_intersect(), and Slic3r::MeshBoolean::cgal::CGALMesh::m.
Referenced by Slic3r::csg::check_csgmesh_booleans(), does_self_intersect(), and does_self_intersect().
does_self_intersect() [2/2]
bool Slic3r::MeshBoolean::cgal::does_self_intersect (const TriangleMesh & mesh)
{
    CGALMesh cgalm;
    triangle_mesh_to_cgal(mesh.its.vertices, mesh.its.indices, cgalm.m);
    return CGALProc::does_self_intersect(cgalm.m);
}
References does_self_intersect(), indexed_triangle_set::indices, Slic3r::TriangleMesh::its, Slic3r::MeshBoolean::cgal::CGALMesh::m, triangle_mesh_to_cgal(), and indexed_triangle_set::vertices.
empty()
bool Slic3r::MeshBoolean::cgal::empty (const CGALMesh & mesh)
{
    return mesh.m.is_empty();
}
References Slic3r::MeshBoolean::cgal::CGALMesh::m.
Referenced by Slic3r::csg::check_csgmesh_booleans().
intersect() [1/3]
void Slic3r::MeshBoolean::cgal::intersect (CGALMesh & A, CGALMesh & B)
{ _cgal_do(_cgal_intersection, A, B); }
References _cgal_do(), and _cgal_intersection().
Referenced by Slic3r::csg::detail_cgal::perform_csg().
intersect() [2/3]
void Slic3r::MeshBoolean::cgal::intersect (indexed_triangle_set & A, const indexed_triangle_set & B)
{
    _mesh_boolean_do(_cgal_intersection, A, B);
}
References _cgal_intersection(), and _mesh_boolean_do().
intersect() [3/3]
void Slic3r::MeshBoolean::cgal::intersect (TriangleMesh & A, const TriangleMesh & B)
{
    _mesh_boolean_do(_cgal_intersection, A, B);
}
References _cgal_intersection(), and _mesh_boolean_do().
merge() [1/2]
void Slic3r::MeshBoolean::cgal::merge (std::vector< _EpicMesh > & srcs, _EpicMesh & dst)
{
    _EpicMesh mesh_merged;
    for (size_t i = 0; i < srcs.size(); i++)
    {
        mesh_merged.join(srcs[i]);
    }
    if (mesh_merged.is_empty() == false) {
        CGAL::Polygon_mesh_processing::stitch_borders(mesh_merged);
        dst = std::move(mesh_merged);
    }
}
Referenced by Slic3r::ModelObject::merge_volumes().
merge() [2/2]
TriangleMesh Slic3r::MeshBoolean::cgal::merge (std::vector< TriangleMesh > meshes)
{
    std::vector<_EpicMesh> srcs(meshes.size());
    for (size_t i = 0; i < meshes.size(); i++)
    {
        MeshBoolean::cgal::triangle_mesh_to_cgal(meshes[i], srcs[i]);
    }
    _EpicMesh dst;
    merge(srcs, dst);
    return cgal_to_triangle_mesh(dst);
}
References cgal_to_triangle_mesh(), and triangle_mesh_to_cgal().
minus() [1/3]
void Slic3r::MeshBoolean::cgal::minus (CGALMesh & A, CGALMesh & B)
{ _cgal_do(_cgal_diff, A, B); }
References _cgal_diff(), and _cgal_do().
Referenced by Slic3r::csg::detail_cgal::perform_csg().
minus() [2/3]
void Slic3r::MeshBoolean::cgal::minus (indexed_triangle_set & A, const indexed_triangle_set & B)
{
    _mesh_boolean_do(_cgal_diff, A, B);
}
References _cgal_diff(), and _mesh_boolean_do().
minus() [3/3]
void Slic3r::MeshBoolean::cgal::minus (TriangleMesh & A, const TriangleMesh & B)
{
    _mesh_boolean_do(_cgal_diff, A, B);
}
References _cgal_diff(), and _mesh_boolean_do().
plus() [1/3]
void Slic3r::MeshBoolean::cgal::plus (CGALMesh & A, CGALMesh & B)
{ _cgal_do(_cgal_union, A, B); }
References _cgal_do(), _cgal_union(), and plus().
Referenced by Slic3r::csg::detail_cgal::perform_csg(), plus(), plus(), and plus().
plus() [2/3]
void Slic3r::MeshBoolean::cgal::plus (indexed_triangle_set & A, const indexed_triangle_set & B)
{
    _mesh_boolean_do(_cgal_union, A, B);
}
References _cgal_union(), _mesh_boolean_do(), and plus().
plus() [3/3]
void Slic3r::MeshBoolean::cgal::plus (TriangleMesh & A, const TriangleMesh & B)
{
    _mesh_boolean_do(_cgal_union, A, B);
}
References _cgal_union(), _mesh_boolean_do(), and plus().
save_CGALMesh()
void Slic3r::MeshBoolean::cgal::save_CGALMesh (const std::string & fname, const CGALMesh & cgal_mesh)
{
    std::ofstream os(fname);
    os << cgal_mesh.m;
    os.close();
}
References Slic3r::MeshBoolean::cgal::CGALMesh::m.
segment() [1/2]
void Slic3r::MeshBoolean::cgal::segment (CGALMesh & src, std::vector< CGALMesh > & dst, double smoothing_alpha = 0.5, int segment_number = 5)
{
    typedef boost::graph_traits<_EpicMesh>::face_descriptor face_descriptor;
    typedef _EpicMesh::Property_map<face_descriptor, double> Facet_double_map;
    typedef CGAL::Face_filtered_graph<_EpicMesh> Filtered_graph;
    _EpicMesh mesh = src.m;
    Facet_double_map sdf_property_map;
    sdf_property_map = mesh.add_property_map<face_descriptor, double>("f:sdf").first;
    CGAL::sdf_values(mesh, sdf_property_map);
    // create a property-map for segment-ids
    typedef _EpicMesh::Property_map<face_descriptor, std::size_t> Facet_int_map;
    Facet_int_map segment_property_map = mesh.add_property_map<face_descriptor, std::size_t>("f:sid").first;;
    // segment the mesh using default parameters for number of levels, and smoothing lambda
    // Any other scalar values can be used instead of using SDF values computed using the CGAL function
    std::size_t number_of_segments = CGAL::segmentation_from_sdf_values(mesh, sdf_property_map, segment_property_map, segment_number, smoothing_alpha);
    //print area of each segment and then put it in a Mesh and print it in an OFF file
    Filtered_graph segment_mesh(mesh);
    _EpicMesh mesh_merged;
    for (std::size_t id = 0; id < number_of_segments; ++id)
    {
        segment_mesh.set_selected_faces(id, segment_property_map);
        //std::cout << "Segment " << id << "'s area is : " << CGAL::Polygon_mesh_processing::area(segment_mesh) << std::endl;
        _EpicMesh out;
        CGAL::copy_face_graph(segment_mesh, out);
        // save_CGALMesh("out.off", out);
        // fill holes
        typedef boost::graph_traits<_EpicMesh>::halfedge_descriptor      halfedge_descriptor;
        typedef boost::graph_traits<_EpicMesh>::vertex_descriptor        vertex_descriptor;
        std::vector<halfedge_descriptor> border_cycles;
        CGAL::Polygon_mesh_processing::extract_boundary_cycles(out, std::back_inserter(border_cycles));
        for (halfedge_descriptor h : border_cycles)
        {
            std::vector<face_descriptor>  patch_facets;
#if 0
            std::vector<vertex_descriptor> patch_vertices;
            CGAL::Polygon_mesh_processing::triangulate_and_refine_hole(out, h, std::back_inserter(patch_facets),
                std::back_inserter(patch_vertices));
            std::cout << "* Number of facets in constructed patch: " << patch_facets.size() << std::endl;
            std::cout << "  Number of vertices in constructed patch: " << patch_vertices.size() << std::endl;
#else
            CGAL::Polygon_mesh_processing::triangulate_hole(out, h, std::back_inserter(patch_facets));
#endif
        }
        //if (id > 2) {
        //    mesh_merged.join(out);
        //}
        //else
        {
            dst.emplace_back(std::move(CGALMesh(out)));
        }
    }
    //if (mesh_merged.is_empty() == false) {
    //    CGAL::Polygon_mesh_processing::stitch_borders(mesh_merged);
    //    dst.emplace_back(std::move(CGALMesh(mesh_merged)));
    //}
}
References Slic3r::MeshBoolean::cgal::CGALMesh::m, and out.
Referenced by Slic3r::ModelObject::segment().
segment() [2/2]
std::vector< TriangleMesh > Slic3r::MeshBoolean::cgal::segment (const TriangleMesh & src, double smoothing_alpha, int segment_number)
{
    CGALMesh in_cgal_mesh;
    MeshBoolean::cgal::triangle_mesh_to_cgal(src, in_cgal_mesh.m);
    std::vector<CGALMesh> out_cgal_meshes;
    segment(in_cgal_mesh, out_cgal_meshes, smoothing_alpha, segment_number);
    std::vector<TriangleMesh> out_meshes;
    for (auto& outf_cgal_mesh: out_cgal_meshes)
    {
        out_meshes.emplace_back(std::move(cgal_to_triangle_mesh(outf_cgal_mesh.m)));
    }
    return out_meshes;
}
References cgal_to_triangle_mesh(), Slic3r::MeshBoolean::cgal::CGALMesh::m, segment(), and triangle_mesh_to_cgal().
to_vec3f() [1/2]
Vec3f Slic3r::MeshBoolean::cgal::to_vec3f (const _EpecMesh::Point & v) inline
{
    CGAL::Cartesian_converter<EpecKernel, EpicKernel> cvt;
    auto iv = cvt(v);
    return { float(iv.x()), float(iv.y()), float(iv.z()) };
}
to_vec3f() [2/2]
Vec3f Slic3r::MeshBoolean::cgal::to_vec3f (const _EpicMesh::Point & v) inline
{
    return { float(v.x()), float(v.y()), float(v.z()) };
}
triangle_mesh_to_cgal() [1/5]
CGALMeshPtr Slic3r::MeshBoolean::cgal::triangle_mesh_to_cgal (const indexed_triangle_set & M) inline
{
    return triangle_mesh_to_cgal(M.vertices, M.indices);
}
References indexed_triangle_set::indices, triangle_mesh_to_cgal(), and indexed_triangle_set::vertices.
triangle_mesh_to_cgal() [2/5]
CGALMeshPtr Slic3r::MeshBoolean::cgal::triangle_mesh_to_cgal (const std::vector< stl_vertex > & V, const std::vector< stl_triangle_vertex_indices > & F)
{
    std::unique_ptr<CGALMesh, CGALMeshDeleter> out(new CGALMesh{});
    triangle_mesh_to_cgal(V, F, out->m);
    return out;
}
References Slic3r::F, out, and triangle_mesh_to_cgal().
triangle_mesh_to_cgal() [3/5]
template<class _Mesh > void Slic3r::MeshBoolean::cgal::triangle_mesh_to_cgal (const std::vector< stl_vertex > & V, const std::vector< stl_triangle_vertex_indices > & F, _Mesh & out)
{
    if (F.empty()) return;
    size_t vertices_count = V.size();
    size_t edges_count    = (F.size()* 3) / 2;
    size_t faces_count    = F.size();
    out.reserve(vertices_count, edges_count, faces_count);
    for (auto &v : V)
        out.add_vertex(typename _Mesh::Point{v.x(), v.y(), v.z()});
    using VI = typename _Mesh::Vertex_index;
    for (auto &f : F)
        out.add_face(VI(f(0)), VI(f(1)), VI(f(2)));
}
References Slic3r::F, and out.
triangle_mesh_to_cgal() [4/5]
CGALMeshPtr Slic3r::MeshBoolean::cgal::triangle_mesh_to_cgal (const TriangleMesh & M) inline
{
    return triangle_mesh_to_cgal(M.its);
}
References Slic3r::TriangleMesh::its, and triangle_mesh_to_cgal().
triangle_mesh_to_cgal() [5/5]
template<class _Mesh > void Slic3r::MeshBoolean::cgal::triangle_mesh_to_cgal (const TriangleMesh & M, _Mesh & out)
{
    using Index3 = std::array<size_t, 3>;
    if (M.empty()) return;
    std::vector<typename _Mesh::Point> points;
    std::vector<Index3> indices;
    points.reserve(M.its.vertices.size());
    indices.reserve(M.its.indices.size());
    for (auto& v : M.its.vertices) points.emplace_back(v.x(), v.y(), v.z());
    for (auto& _f : M.its.indices) {
        auto f = _f.cast<size_t>();
        indices.emplace_back(Index3{ f(0), f(1), f(2) });
    }
    CGALProc::orient_polygon_soup(points, indices);
    CGALProc::polygon_soup_to_polygon_mesh(points, indices, out);
    // Number the faces because 'orient_to_bound_a_volume' needs a face <--> index map
    unsigned index = 0;
    for (auto face : out.faces()) face = CGAL::SM_Face_index(index++);
    if (CGAL::is_closed(out))
        CGALProc::orient_to_bound_a_volume(out);
    else
        throw Slic3r::RuntimeError("Mesh not watertight");
}
References Slic3r::TriangleMesh::empty(), Slic3r::f(), indexed_triangle_set::indices, Slic3r::TriangleMesh::its, out, and indexed_triangle_set::vertices.
Referenced by _mesh_boolean_do(), _mesh_boolean_do(), Slic3r::csg::check_csgmesh_booleans(), does_self_intersect(), Slic3r::csg::get_cgalmesh(), merge(), Slic3r::csg::perform_csgmesh_booleans(), segment(), triangle_mesh_to_cgal(), triangle_mesh_to_cgal(), and triangle_mesh_to_cgal().