OrcaSlicer: Slic3r::GCode::GCodeOutputStream Class Reference
Slic3r::GCode::GCodeOutputStream Class Reference
Public Member Functions
GCodeOutputStream (FILE *f, GCodeProcessor &processor)
~GCodeOutputStream ()
bool is_open () const
bool is_error () const
void flush ()
void close ()
void write (const std::string &what)
void write (const char *what)
void writeln (const std::string &what)
void write_format (const char *format,...)
Private Attributes
FILE * f = nullptr
GCodeProcessor & m_processor
Detailed Description
Constructor & Destructor Documentation
GCodeOutputStream()
Slic3r::GCode::GCodeOutputStream::GCodeOutputStream (FILE * f, GCodeProcessor & processor) inline
: f(f), m_processor(processor) {}
~GCodeOutputStream()
Slic3r::GCode::GCodeOutputStream::~GCodeOutputStream () inline
{ this->close(); }
References close().
Member Function Documentation
close()
void Slic3r::GCode::GCodeOutputStream::close ()
{
    if (this->f) {
        ::fclose(this->f);
        this->f = nullptr;
    }
}
Referenced by ~GCodeOutputStream(), and Slic3r::GCode::do_export().
flush()
void Slic3r::GCode::GCodeOutputStream::flush ()
{
    ::fflush(this->f);
}
Referenced by Slic3r::GCode::do_export().
is_error()
bool Slic3r::GCode::GCodeOutputStream::is_error () const
{
    return ::ferror(this->f);
}
Referenced by Slic3r::GCode::do_export().
is_open()
bool Slic3r::GCode::GCodeOutputStream::is_open () const inline
{ return f; }
References f.
Referenced by Slic3r::GCode::do_export().
write() [1/2]
void Slic3r::GCode::GCodeOutputStream::write (const char * what)
{
    if (what != nullptr) {
        const char* gcode = what;
        // writes string to file
        fwrite(gcode, 1, ::strlen(gcode), this->f);
        //FIXME don't allocate a string, maybe process a batch of lines?
        m_processor.process_buffer(std::string(gcode));
    }
}
write() [2/2]
void Slic3r::GCode::GCodeOutputStream::write (const std::string & what) inline
{ this->write(what.c_str()); }
References write().
Referenced by Slic3r::GCode::_do_export(), Slic3r::GCode::_print_first_layer_bed_temperature(), Slic3r::GCode::_print_first_layer_extruder_temperatures(), and write().
write_format()
void Slic3r::GCode::GCodeOutputStream::write_format (const char * format, ...)
{
    va_list args;
    va_start(args, format);
    int buflen;
    {
        va_list args2;
        va_copy(args2, args);
        buflen =
    #ifdef _MSC_VER
            ::_vscprintf(format, args2)
    #else
            ::vsnprintf(nullptr, 0, format, args2)
    #endif
            + 1;
        va_end(args2);
    }
    char buffer[1024];
    bool buffer_dynamic = buflen > 1024;
    char *bufptr = buffer_dynamic ? (char*)malloc(buflen) : buffer;
    int res = ::vsnprintf(bufptr, buflen, format, args);
    if (res > 0)
        this->write(bufptr);
    if (buffer_dynamic)
        free(bufptr);
    va_end(args);
}
References buffer, Slic3r::format(), and va_copy.
Referenced by Slic3r::GCode::_do_export(), and Slic3r::GCode::print_machine_envelope().
writeln()
void Slic3r::GCode::GCodeOutputStream::writeln (const std::string & what)
{
    if (! what.empty())
        this->write(what.back() == '\n' ? what : what + '\n');
}
Referenced by Slic3r::GCode::_do_export().
Member Data Documentation
f
FILE* Slic3r::GCode::GCodeOutputStream::f = nullptr private
Referenced by is_open().
m_processor
GCodeProcessor& Slic3r::GCode::GCodeOutputStream::m_processor private
The documentation for this class was generated from the following files:
src/libslic3r/GCode.hpp
src/libslic3r/GCode.cpp