OrcaSlicer: Slic3r::GUI::MeshClipper Class Reference
Slic3r::GUI::MeshClipper Class Reference
#include <src/slic3r/GUI/MeshUtils.hpp>
Classes
struct ClipResult
struct CutIsland
Public Member Functions
void set_plane (const ClippingPlane &plane)
void set_limiting_plane (const ClippingPlane &plane)
void set_mesh (const TriangleMesh &mesh)
void set_negative_mesh (const TriangleMesh &mesh)
void set_transformation (const Geometry::Transformation &trafo)
void render_cut ()
bool is_projection_inside_cut (const Vec3d &point) const
bool has_valid_contour () const
Private Member Functions
void recalculate_triangles ()
Private Attributes
Geometry::Transformation m_trafo
const TriangleMesh * m_mesh = nullptr
const TriangleMesh * m_negative_mesh = nullptr
ClippingPlane m_plane
ClippingPlane m_limiting_plane = ClippingPlane::ClipsNothing()
std::vector< Vec2f > m_triangles2d
GLIndexedVertexArray m_vertex_array
bool m_triangles_valid = false
std::optional< ClipResult > m_result
Detailed Description
Class Documentation
Slic3r::GUI::MeshClipper::ClipResult
struct Slic3r::GUI::MeshClipper::ClipResult
Class Members
vector< CutIsland > cut_islands
Transform3d trafo
Slic3r::GUI::MeshClipper::CutIsland
struct Slic3r::GUI::MeshClipper::CutIsland
Class Members
ExPolygon expoly
BoundingBox expoly_bb
Member Function Documentation
has_valid_contour()
bool Slic3r::GUI::MeshClipper::has_valid_contour () const
{
    return m_result && std::any_of(m_result->cut_islands.begin(), m_result->cut_islands.end(), [](const CutIsland &isl) { return !isl.expoly.empty(); });
}
References m_result.
is_projection_inside_cut()
bool Slic3r::GUI::MeshClipper::is_projection_inside_cut (const Vec3d & point) const
{
    if (!m_result || m_result->cut_islands.empty())
        return false;
    Vec3d point = m_result->trafo.inverse() * point_in;
    Point pt_2d = Point::new_scale(Vec2d(point.x(), point.y()));
    for (const CutIsland &isl : m_result->cut_islands) {
        if (isl.expoly_bb.contains(pt_2d) && isl.expoly.contains(pt_2d))
            return true;
    }
    return false;
}
References m_result.
recalculate_triangles()
void Slic3r::GUI::MeshClipper::recalculate_triangles () private
{
    const Transform3f& instance_matrix_no_translation_no_scaling = m_trafo.get_matrix(true,false,true).cast<float>();
    // Calculate clipping plane normal in mesh coordinates.
    const Vec3f up_noscale = instance_matrix_no_translation_no_scaling.inverse() * m_plane.get_normal().cast<float>();
    const Vec3d up = up_noscale.cast<double>().cwiseProduct(m_trafo.get_scaling_factor());
    // Calculate distance from mesh origin to the clipping plane (in mesh coordinates).
    const float height_mesh = m_plane.distance(m_trafo.get_offset()) * (up_noscale.norm()/up.norm());
    // Now do the cutting
    MeshSlicingParams slicing_params;
    slicing_params.trafo.rotate(Eigen::Quaternion<double, Eigen::DontAlign>::FromTwoVectors(up, Vec3d::UnitZ()));
    ExPolygons expolys = union_ex(slice_mesh(m_mesh->its, height_mesh, slicing_params));
    if (m_negative_mesh && !m_negative_mesh->empty()) {
        const ExPolygons neg_expolys = union_ex(slice_mesh(m_negative_mesh->its, height_mesh, slicing_params));
        expolys = diff_ex(expolys, neg_expolys);
    }
    // Triangulate and rotate the cut into world coords:
    Eigen::Quaterniond q;
    q.setFromTwoVectors(Vec3d::UnitZ(), up);
    Transform3d tr = Transform3d::Identity();
    tr.rotate(q);
    tr = m_trafo.get_matrix() * tr;
    m_result = ClipResult();
    m_result->trafo = tr;
    if (m_limiting_plane != ClippingPlane::ClipsNothing())
    {
        // Now remove whatever ended up below the limiting plane (e.g. sinking objects).
        // First transform the limiting plane from world to mesh coords.
        // Note that inverse of tr transforms the plane from world to horizontal.
        const Vec3d normal_old = m_limiting_plane.get_normal().normalized();
        const Vec3d normal_new = (tr.matrix().block<3,3>(0,0).transpose() * normal_old).normalized();
        // normal_new should now be the plane normal in mesh coords. To find the offset,
        // transform a point and set offset so it belongs to the transformed plane.
        Vec3d pt = Vec3d::Zero();
        const double plane_offset = m_limiting_plane.get_data()[3];
        if (std::abs(normal_old.z()) > 0.5) // normal is normalized, at least one of the coords if larger than sqrt(3)/3 = 0.57
            pt.z() = - plane_offset / normal_old.z();
        else if (std::abs(normal_old.y()) > 0.5)
            pt.y() = - plane_offset / normal_old.y();
        else
            pt.x() = - plane_offset / normal_old.x();
        pt = tr.inverse() * pt;
        const double offset = -(normal_new.dot(pt));
        if (std::abs(normal_old.dot(m_plane.get_normal().normalized())) > 0.99) {
            // The cuts are parallel, show all or nothing.
            if (normal_old.dot(m_plane.get_normal().normalized()) < 0.0 && offset < height_mesh)
                expolys.clear();
        } else {
            // The cut is a horizontal plane defined by z=height_mesh.
            // ax+by+e=0 is the line of intersection with the limiting plane.
            // Normalized so a^2 + b^2 = 1.
            const double len = std::hypot(normal_new.x(), normal_new.y());
            if (len == 0.)
                return;
            const double a = normal_new.x() / len;
            const double b = normal_new.y() / len;
            const double e = (normal_new.z() * height_mesh + offset) / len;
            // We need a half-plane to limit the cut. Get angle of the intersecting line.
            double angle = (b != 0.0) ? std::atan(-a / b) : ((a < 0.0) ? -0.5 * M_PI : 0.5 * M_PI);
            if (b > 0) // select correct half-plane
                angle += M_PI;
            // We'll take a big rectangle above x-axis and rotate and translate
            // it so it lies on our line. This will be the figure to subtract
            // from the cut. The coordinates must not overflow after the transform,
            // make the rectangle a bit smaller.
            const coord_t size = (std::numeric_limits<coord_t>::max() - scale_(std::max(std::abs(e*a), std::abs(e*b)))) / 4;
            Polygons ep {Polygon({Point(-size, 0), Point(size, 0), Point(size, 2*size), Point(-size, 2*size)})};
            ep.front().rotate(angle);
            ep.front().translate(scale_(-e * a), scale_(-e * b));
            expolys = diff_ex(expolys, ep);
        }
    }
     for (const ExPolygon &exp : expolys) {
        m_result->cut_islands.push_back(CutIsland());
        CutIsland &isl = m_result->cut_islands.back();
        isl.expoly     = std::move(exp);
        isl.expoly_bb  = get_extents(exp);
    }
    m_triangles2d = triangulate_expolygons_2f(expolys, m_trafo.get_matrix().matrix().determinant() < 0.);
    tr.pretranslate(0.001 * m_plane.get_normal().normalized()); // to avoid z-fighting
    m_vertex_array.release_geometry();
    for (auto it=m_triangles2d.cbegin(); it != m_triangles2d.cend(); it=it+3) {
        m_vertex_array.push_geometry(tr * Vec3d((*(it+0))(0), (*(it+0))(1), height_mesh), up);
        m_vertex_array.push_geometry(tr * Vec3d((*(it+1))(0), (*(it+1))(1), height_mesh), up);
        m_vertex_array.push_geometry(tr * Vec3d((*(it+2))(0), (*(it+2))(1), height_mesh), up);
        const size_t idx = it - m_triangles2d.cbegin();
        m_vertex_array.push_triangle(idx, idx+1, idx+2);
    }
    m_vertex_array.finalize_geometry(true);
    m_triangles_valid = true;
}
References Slic3r::angle(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::cast(), Slic3r::GUI::ClippingPlane::ClipsNothing(), Slic3r::diff_ex(), Slic3r::GUI::ClippingPlane::distance(), Slic3r::TriangleMesh::empty(), exp(), Slic3r::GUI::MeshClipper::CutIsland::expoly, Slic3r::GUI::MeshClipper::CutIsland::expoly_bb, Slic3r::GLIndexedVertexArray::finalize_geometry(), Slic3r::MultiPoint::front(), Slic3r::GUI::ClippingPlane::get_data(), Slic3r::get_extents(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::GUI::ClippingPlane::get_normal(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::Geometry::Transformation::get_scaling_factor(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::TriangleMesh::its, m_limiting_plane, m_mesh, m_negative_mesh, M_PI, m_plane, m_result, m_trafo, m_triangles2d, m_triangles_valid, m_vertex_array, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::offset(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::pretranslate(), Slic3r::GLIndexedVertexArray::push_geometry(), Slic3r::GLIndexedVertexArray::push_triangle(), Slic3r::GLIndexedVertexArray::release_geometry(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::rotate(), Slic3r::Point::rotate(), scale_, Eigen::QuaternionBase< Derived >::setFromTwoVectors(), size, Slic3r::slice_mesh(), Slic3r::MeshSlicingParams::trafo, Slic3r::triangulate_expolygons_2f(), and Slic3r::union_ex().
Referenced by render_cut().
render_cut()
void Slic3r::GUI::MeshClipper::render_cut ()
{
    if (! m_triangles_valid)
        recalculate_triangles();
    if (m_vertex_array.has_VBOs())
        m_vertex_array.render();
}
References Slic3r::GLIndexedVertexArray::has_VBOs(), m_triangles_valid, m_vertex_array, recalculate_triangles(), and Slic3r::GLIndexedVertexArray::render().
set_limiting_plane()
void Slic3r::GUI::MeshClipper::set_limiting_plane (const ClippingPlane & plane)
{
    if (m_limiting_plane != plane) {
        m_limiting_plane = plane;
        m_triangles_valid = false;
    }
}
References m_limiting_plane, and m_triangles_valid.
set_mesh()
void Slic3r::GUI::MeshClipper::set_mesh (const TriangleMesh & mesh)
{
    if (m_mesh != &mesh) {
        m_mesh = &mesh;
        m_triangles_valid = false;
        m_triangles2d.resize(0);
    }
}
References m_mesh, m_triangles2d, and m_triangles_valid.
set_negative_mesh()
void Slic3r::GUI::MeshClipper::set_negative_mesh (const TriangleMesh & mesh)
{
    if (m_negative_mesh != &mesh) {
        m_negative_mesh = &mesh;
        m_triangles_valid = false;
        m_triangles2d.resize(0);
    }
}
References m_negative_mesh, m_triangles2d, and m_triangles_valid.
set_plane()
void Slic3r::GUI::MeshClipper::set_plane (const ClippingPlane & plane)
{
    if (m_plane != plane) {
        m_plane = plane;
        m_triangles_valid = false;
    }
}
References m_plane, and m_triangles_valid.
set_transformation()
void Slic3r::GUI::MeshClipper::set_transformation (const Geometry::Transformation & trafo)
{
    if (! m_trafo.get_matrix().isApprox(trafo.get_matrix())) {
        m_trafo = trafo;
        m_triangles_valid = false;
        m_triangles2d.resize(0);
    }
}
References Slic3r::Geometry::Transformation::get_matrix(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::isApprox(), m_trafo, m_triangles2d, and m_triangles_valid.
Member Data Documentation
m_limiting_plane
ClippingPlane Slic3r::GUI::MeshClipper::m_limiting_plane = ClippingPlane::ClipsNothing() private
Referenced by recalculate_triangles(), and set_limiting_plane().
m_mesh
const TriangleMesh* Slic3r::GUI::MeshClipper::m_mesh = nullptr private
Referenced by recalculate_triangles(), and set_mesh().
m_negative_mesh
const TriangleMesh* Slic3r::GUI::MeshClipper::m_negative_mesh = nullptr private
Referenced by recalculate_triangles(), and set_negative_mesh().
m_plane
ClippingPlane Slic3r::GUI::MeshClipper::m_plane private
Referenced by recalculate_triangles(), and set_plane().
m_result
std::optional<ClipResult> Slic3r::GUI::MeshClipper::m_result private
Referenced by has_valid_contour(), is_projection_inside_cut(), and recalculate_triangles().
m_trafo
Geometry::Transformation Slic3r::GUI::MeshClipper::m_trafo private
Referenced by recalculate_triangles(), and set_transformation().
m_triangles2d
std::vector<Vec2f> Slic3r::GUI::MeshClipper::m_triangles2d private
Referenced by recalculate_triangles(), set_mesh(), set_negative_mesh(), and set_transformation().
m_triangles_valid
bool Slic3r::GUI::MeshClipper::m_triangles_valid = false private
Referenced by recalculate_triangles(), render_cut(), set_limiting_plane(), set_mesh(), set_negative_mesh(), set_plane(), and set_transformation().
m_vertex_array
GLIndexedVertexArray Slic3r::GUI::MeshClipper::m_vertex_array private
Referenced by recalculate_triangles(), and render_cut().
The documentation for this class was generated from the following files:
src/slic3r/GUI/MeshUtils.hpp
src/slic3r/GUI/MeshUtils.cpp