OrcaSlicer: Slic3r::GUI::ColorPicker Class Reference
Slic3r::GUI::ColorPicker Class Reference
#include <src/slic3r/GUI/AMSMaterialsSetting.hpp>
Public Member Functions
ColorPicker (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~ColorPicker ()
void msw_rescale ()
void set_color (wxColour col)
void set_colors (std::vector< wxColour > cols)
void set_selected (bool sel)
void set_show_full (bool full)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
Public Attributes
wxBitmap m_bitmap_border
wxColour m_colour
std::vector< wxColour > m_cols
bool m_selected {false}
bool m_show_full {false}
Detailed Description
Constructor & Destructor Documentation
ColorPicker()
Slic3r::GUI::ColorPicker::ColorPicker (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{
    wxWindow::Create(parent, id, pos, size);
    SetSize(wxSize(FromDIP(25), FromDIP(25)));
    SetMinSize(wxSize(FromDIP(25), FromDIP(25)));
    SetMaxSize(wxSize(FromDIP(25), FromDIP(25)));
    Bind(wxEVT_PAINT, &ColorPicker::paintEvent, this);
    m_bitmap_border = create_scaled_bitmap("color_picker_border", nullptr, 25);
}
References create_scaled_bitmap(), m_bitmap_border, paintEvent(), and size.
~ColorPicker()
Slic3r::GUI::ColorPicker::~ColorPicker ()
{}
Member Function Documentation
doRender()
void Slic3r::GUI::ColorPicker::doRender (wxDC & dc)
{
    wxSize     size = GetSize();
    auto radius = m_show_full?size.x / 2:size.x / 2 - FromDIP(1);
    if (m_selected) radius -= FromDIP(1);
    dc.SetPen(wxPen(m_colour));
    dc.SetBrush(wxBrush(m_colour));
    dc.DrawCircle(size.x / 2, size.x / 2, radius);
    if (m_selected) {
        dc.SetPen(wxPen(m_colour));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawCircle(size.x / 2, size.x / 2, size.x / 2);
    }
    if (m_show_full) {
        dc.SetPen(wxPen(wxColour(0x6B6B6B)));
        dc.SetBrush(*wxTRANSPARENT_BRUSH);
        dc.DrawCircle(size.x / 2, size.x / 2, radius);
        if (m_cols.size() > 1) {
            int left = FromDIP(0);
            float total_width = size.x;
            int gwidth = std::round(total_width / (m_cols.size() - 1));
            for (int i = 0; i < m_cols.size() - 1; i++) {
                if ((left + gwidth) > (size.x)) {
                    gwidth = size.x - left;
                }
                auto rect = wxRect(left, 0, gwidth, size.y);
                dc.GradientFillLinear(rect, m_cols[i], m_cols[i + 1], wxEAST);
                left += gwidth;
            }
            dc.DrawBitmap(m_bitmap_border, wxPoint(0, 0));
        }
    }
}
References m_bitmap_border, m_colour, m_cols, m_selected, m_show_full, and size.
Referenced by render().
msw_rescale()
void Slic3r::GUI::ColorPicker::msw_rescale ()
{
    m_bitmap_border = create_scaled_bitmap("color_picker_border", nullptr, 25);
    Refresh();
}
References create_scaled_bitmap(), and m_bitmap_border.
Referenced by Slic3r::GUI::AMSMaterialsSetting::msw_rescale().
paintEvent()
void Slic3r::GUI::ColorPicker::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by ColorPicker().
render()
void Slic3r::GUI::ColorPicker::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
set_color()
void Slic3r::GUI::ColorPicker::set_color (wxColour col)
{
    m_colour = col;
    Refresh();
}
References col(), and m_colour.
Referenced by Slic3r::GUI::AMSMaterialsSetting::set_color().
set_colors()
void Slic3r::GUI::ColorPicker::set_colors (std::vector< wxColour > cols)
{
    m_cols = cols;
    Refresh();
}
References m_cols.
Referenced by Slic3r::GUI::AMSMaterialsSetting::set_colors().
set_selected()
void Slic3r::GUI::ColorPicker::set_selected (bool sel) inline
{m_selected = sel;Refresh();};
References m_selected.
set_show_full()
void Slic3r::GUI::ColorPicker::set_show_full (bool full) inline
{m_show_full = full;Refresh();};
References m_show_full.
Referenced by Slic3r::GUI::AMSMaterialsSetting::create_panel_normal().
Member Data Documentation
m_bitmap_border
wxBitmap Slic3r::GUI::ColorPicker::m_bitmap_border
Referenced by ColorPicker(), doRender(), and msw_rescale().
m_colour
wxColour Slic3r::GUI::ColorPicker::m_colour
Referenced by doRender(), Slic3r::GUI::AMSMaterialsSetting::on_clr_picker(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), and set_color().
m_cols
std::vector<wxColour> Slic3r::GUI::ColorPicker::m_cols
Referenced by doRender(), and set_colors().
m_selected
bool Slic3r::GUI::ColorPicker::m_selected {false}
Referenced by doRender(), and set_selected().
m_show_full
bool Slic3r::GUI::ColorPicker::m_show_full {false}
Referenced by doRender(), and set_show_full().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AMSMaterialsSetting.hpp
src/slic3r/GUI/AMSMaterialsSetting.cpp