OrcaSlicer: ZipUnicodePathExtraField Struct Reference
ZipUnicodePathExtraField Struct Reference
Static Public Member Functions
static std::string encode (std::string const &u8path, std::string const &path)
static std::string decode (std::string const &extra, std::string const &path={})
Detailed Description
Member Function Documentation
decode()
static std::string ZipUnicodePathExtraField::decode (std::string const & extra, std::string const & path = {}) inline static
                                                                            {}) {
        char const * p = extra.data();
        char const * e = p + extra.length();
        while (p + 4 < e) {
            boost::uint16_t len = ((boost::uint16_t)p[2]) | ((boost::uint16_t)p[3] << 8);
            if (p[0] == '\x75' && p[1] == '\x70' && len >= 5 && p + 4 + len < e && p[4] == '\x01') {
                return std::string(p + 9, p + 4 + len);
            }
            else {
                p += 4 + len;
            }
        }
        return Slic3r::decode_path(path.c_str());
    }
Referenced by Slic3r::_BBS_3MF_Importer::_extract_auxiliary_file_from_archive(), and Slic3r::_BBS_3MF_Importer::_extract_from_archive().
encode()
static std::string ZipUnicodePathExtraField::encode (std::string const & u8path, std::string const & path) inline static
{
        std::string extra;
        if (u8path != path) {
            // 0x7075 - for Unicode filenames
            extra.push_back('\x75');
            extra.push_back('\x70');
            boost::uint16_t len = 5 + u8path.length();
            extra.push_back((char)(len & 0xff));
            extra.push_back((char)(len >> 8));
            auto crc = mz_crc32(0, (unsigned char *) path.c_str(), path.length());
            extra.push_back('\x01'); // version 1
            extra.append((char *)&crc, (char *)&crc + 4); // Little Endian
            extra.append(u8path);
        }
        return extra;
    }
References mz_crc32().
Referenced by Slic3r::_BBS_3MF_Exporter::_add_file_to_archive(), and Slic3r::_BBS_3MF_Exporter::_add_model_file_to_archive().
The documentation for this struct was generated from the following file:
src/libslic3r/Format/bbs_3mf.cpp