OrcaSlicer: Slic3r::PrinterPresetCollection Class Reference
Slic3r::PrinterPresetCollection Class Reference
#include <src/libslic3r/Preset.hpp>
Public Types
enum class LoadAndSelect { Never , Always , OnlyIfModified }
typedef std::deque< Preset >::iterator Iterator
typedef std::deque< Preset >::const_iterator ConstIterator
typedef std::function< void(Preset *preset, std::string sync_info)> SyncFunc
Public Member Functions
PrinterPresetCollection (Preset::Type type, const std::vector< std::string > &keys, const Slic3r::StaticPrintConfig &defaults, const std::string &default_name="Default Printer")
const Preset & default_preset_for (const DynamicPrintConfig &config) const override
const Preset * find_system_preset_by_model_and_variant (const std::string &model_id, const std::string &variant) const
bool only_default_printers () const
Iterator lbegin ()
bool validate_printers (const std::string &name, DynamicPrintConfig &config, std::string &inherit)
Iterator begin ()
ConstIterator begin () const
ConstIterator cbegin () const
Iterator end ()
ConstIterator end () const
ConstIterator cend () const
Iterator erase (Iterator it)
void set_sync_func (SyncFunc func)
void lock ()
void unlock ()
void reset (bool delete_files)
Preset::Type type () const
std::string name () const
std::string section_name () const
const std::deque< Preset > & operator() () const
void add_default_preset (const std::vector< std::string > &keys, const Slic3r::StaticPrintConfig &defaults, const std::string &preset_name)
void load_presets (const std::string &dir_path, const std::string &subdir, PresetsConfigSubstitutions &substitutions, ForwardCompatibilitySubstitutionRule rule)
void update_user_presets_directory (const std::string &dir_path, const std::string &type)
void save_user_presets (const std::string &dir_path, const std::string &type, std::vector< std::string > &need_to_delete_list)
bool load_user_preset (std::string name, std::map< std::string, std::string > preset_values, PresetsConfigSubstitutions &substitutions, ForwardCompatibilitySubstitutionRule rule)
void update_after_user_presets_loaded ()
int get_user_presets (std::vector< Preset > &result_presets)
void set_sync_info_and_save (std::string name, std::string setting_id, std::string syncinfo)
Preset * get_preset_differed_for_save (Preset &preset)
int get_differed_values_to_update (Preset &preset, std::map< std::string, std::string > &key_values)
void load_project_embedded_presets (std::vector< Preset * > &project_presets, const std::string &type, PresetsConfigSubstitutions &substitutions, ForwardCompatibilitySubstitutionRule rule)
std::vector< Preset * > get_project_embedded_presets ()
bool reset_project_embedded_presets ()
Preset & load_preset (const std::string &path, const std::string &name, const DynamicPrintConfig &config, bool select=true, Semver file_version=Semver(), bool is_custom_defined=false)
Preset & load_preset (const std::string &path, const std::string &name, DynamicPrintConfig &&config, bool select=true, Semver file_version=Semver(), bool is_custom_defined=false)
std::pair< Preset *, bool > load_external_preset (const std::string &path, const std::string &name, const std::string &original_name, const DynamicPrintConfig &config, const std::set< std::string > &different_settings_list, LoadAndSelect select=LoadAndSelect::Always, const Semver file_version=Semver(), const std::string filament_id=std::string())
void save_current_preset (const std::string &new_name, bool detach=false, bool save_to_project=false, Preset *_curr_preset=nullptr)
bool delete_current_preset ()
bool delete_preset (const std::string &name)
void set_default_suppressed (bool default_suppressed)
bool is_default_suppressed () const
Preset & select_preset (size_t idx)
Preset & get_selected_preset ()
const Preset & get_selected_preset () const
size_t get_selected_idx () const
std::string get_selected_preset_name () const
const Preset * get_selected_preset_parent () const
const Preset * get_preset_parent (const Preset &child) const
Preset & get_edited_preset ()
const Preset & get_edited_preset () const
PresetWithVendorProfile get_preset_with_vendor_profile (const Preset &preset) const
PresetWithVendorProfile get_edited_preset_with_vendor_profile () const
const std::string & get_preset_name_by_alias (const std::string &alias) const
const std::string * get_preset_name_renamed (const std::string &old_name) const
const std::deque< Preset > & get_presets () const
size_t get_idx_selected ()
Preset & default_preset (size_t idx=0)
const Preset & default_preset (size_t idx=0) const
Preset & preset (size_t idx, bool real=false)
const Preset & preset (size_t idx) const
void discard_current_changes ()
Preset * find_preset (const std::string &name, bool first_visible_if_not_found=false, bool real=false)
const Preset * find_preset (const std::string &name, bool first_visible_if_not_found=false) const
size_t first_visible_idx () const
template<typename PreferedCondition >
size_t first_compatible_idx (PreferedCondition prefered_condition) const
size_t first_compatible_idx () const
Preset & first_visible ()
const Preset & first_visible () const
Preset & first_compatible ()
template<typename PreferedCondition >
Preset & first_compatible (PreferedCondition prefered_condition)
const Preset & first_compatible () const
size_t size () const
bool has_defaults_only () const
template<typename PreferedCondition >
void update_compatible (const PresetWithVendorProfile &active_printer, const PresetWithVendorProfile *active_print, PresetSelectCompatibleType select_other_if_incompatible, PreferedCondition prefered_condition)
void update_compatible (const PresetWithVendorProfile &active_printer, const PresetWithVendorProfile *active_print, PresetSelectCompatibleType select_other_if_incompatible)
size_t num_visible () const
bool current_is_dirty () const
std::vector< std::string > current_dirty_options (const bool deep_compare=false) const
std::vector< std::string > current_different_from_parent_options (const bool deep_compare=false) const
bool saved_is_dirty () const
void update_saved_preset_from_current_preset ()
std::vector< std::string > system_preset_names () const
bool update_dirty ()
bool select_preset_by_name (const std::string &name, bool force)
std::string path_from_name (const std::string &new_name) const
size_t num_default_presets ()
Static Public Member Functions
static const std::string & get_suffix_modified ()
static bool is_dirty (const Preset *edited, const Preset *reference)
static std::vector< std::string > dirty_options (const Preset *edited, const Preset *reference, const bool deep_compare=false)
static std::vector< std::string > dirty_options_without_option_list (const Preset *edited, const Preset *reference, const std::set< std::string > &option_ignore_list, const bool deep_compare=false)
Public Attributes
SyncFunc sync_func { nullptr }
Protected Member Functions
void update_vendor_ptrs_after_copy (const VendorMap &vendors)
bool select_preset_by_name_strict (const std::string &name)
std::vector< std::string > merge_presets (PresetCollection &&other, const VendorMap &new_vendors)
void update_map_alias_to_profile_name ()
void update_map_system_profile_renamed ()
Private Member Functions
PrinterPresetCollection ()=default
PrinterPresetCollection (const PrinterPresetCollection &other)=default
PrinterPresetCollection & operator= (const PrinterPresetCollection &other)=default
std::deque< Preset >::iterator find_preset_internal (const std::string &name)
std::deque< Preset >::const_iterator find_preset_internal (const std::string &name) const
std::deque< Preset >::iterator find_preset_renamed (const std::string &name)
std::deque< Preset >::const_iterator find_preset_renamed (const std::string &name) const
size_t update_compatible_internal (const PresetWithVendorProfile &active_printer, const PresetWithVendorProfile *active_print, PresetSelectCompatibleType unselect_if_incompatible)
Private Attributes
Preset::Type m_type
std::deque< Preset > m_presets
std::vector< std::pair< std::string, std::string > > m_map_alias_to_profile_name
std::map< std::string, std::string > m_map_system_profile_renamed
Preset m_edited_preset
Preset m_saved_preset
size_t m_idx_selected
bool m_default_suppressed = true
size_t m_num_default_presets = 0
std::string m_dir_path
std::mutex m_mutex
Friends
class PresetBundle
Detailed Description
Member Typedef Documentation
ConstIterator
typedef std::deque<Preset>::const_iterator Slic3r::PresetCollection::ConstIterator inherited
Iterator
typedef std::deque<Preset>::iterator Slic3r::PresetCollection::Iterator inherited
SyncFunc
typedef std::function<void(Preset* preset, std::string sync_info)> Slic3r::PresetCollection::SyncFunc inherited
Member Enumeration Documentation
LoadAndSelect
enum class Slic3r::PresetCollection::LoadAndSelect strong inherited
Enumerator
Never
Always
OnlyIfModified
{
        // Never select
        Never,
        // Always select
        Always,
        // Select a profile only if it was modified.
        OnlyIfModified,
    };
Constructor & Destructor Documentation
PrinterPresetCollection() [1/3]
Slic3r::PrinterPresetCollection::PrinterPresetCollection (Preset::Type type, const std::vector< std::string > & keys, const Slic3r::StaticPrintConfig & defaults, const std::string & default_name = "Default Printer") inline
                                                                                                                                                                           :
    PresetCollection(type, keys, defaults, default_name) {}
PrinterPresetCollection() [2/3]
Slic3r::PrinterPresetCollection::PrinterPresetCollection () private default
PrinterPresetCollection() [3/3]
Slic3r::PrinterPresetCollection::PrinterPresetCollection (const PrinterPresetCollection & other) private default
Member Function Documentation
add_default_preset()
void Slic3r::PresetCollection::add_default_preset (const std::vector< std::string > & keys, const Slic3r::StaticPrintConfig & defaults, const std::string & preset_name) inherited
{
    // Insert just the default preset.
    m_presets.emplace_back(Preset(this->type(), preset_name, true));
    m_presets.back().config.apply_only(defaults, keys.empty() ? defaults.keys() : keys);
    m_presets.back().loaded = true;
    ++ m_num_default_presets;
}
References Slic3r::StaticConfig::keys(), Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, and Slic3r::PresetCollection::type().
Referenced by Slic3r::PresetCollection::PresetCollection().
begin() [1/2]
Iterator Slic3r::PresetCollection::begin () inline inherited
{ return m_presets.begin() + m_num_default_presets; }
References Slic3r::PresetCollection::m_num_default_presets, and Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::GUI::ExtrusionCalibration::get_bed_type_incompatible(), Slic3r::GUI::ExtrusionCalibration::on_click_cali(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::AMSMaterialsSetting::on_select_filament(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::sync_ams_list(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), and Slic3r::GUI::ExtrusionCalibration::update_filament_info().
begin() [2/2]
ConstIterator Slic3r::PresetCollection::begin () const inline inherited
{ return m_presets.cbegin() + m_num_default_presets; }
References Slic3r::PresetCollection::m_num_default_presets, and Slic3r::PresetCollection::m_presets.
cbegin()
ConstIterator Slic3r::PresetCollection::cbegin () const inline inherited
{ return m_presets.cbegin() + m_num_default_presets; }
References Slic3r::PresetCollection::m_num_default_presets, and Slic3r::PresetCollection::m_presets.
Referenced by find_system_preset_by_model_and_variant().
cend()
ConstIterator Slic3r::PresetCollection::cend () const inline inherited
{ return m_presets.cend(); }
References Slic3r::PresetCollection::m_presets.
Referenced by find_system_preset_by_model_and_variant().
current_different_from_parent_options()
std::vector< std::string > Slic3r::PresetCollection::current_different_from_parent_options (const bool deep_compare = false) const inline inherited
        { return dirty_options(&this->get_edited_preset(), this->get_selected_preset_parent(), deep_compare); }
References Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::get_edited_preset(), and Slic3r::PresetCollection::get_selected_preset_parent().
current_dirty_options()
std::vector< std::string > Slic3r::PresetCollection::current_dirty_options (const bool deep_compare = false) const inline inherited
        { return dirty_options(&this->get_edited_preset(), &this->get_selected_preset(), deep_compare); }
References Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::get_edited_preset(), and Slic3r::PresetCollection::get_selected_preset().
current_is_dirty()
bool Slic3r::PresetCollection::current_is_dirty () const inline inherited
        { return is_dirty(&this->get_edited_preset(), &this->get_selected_preset()); }
References Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset(), and Slic3r::PresetCollection::is_dirty().
Referenced by Slic3r::GUI::Tab::current_preset_is_dirty(), Slic3r::GUI::PresetComboBox::OnSelect(), Slic3r::GUI::PlaterPresetComboBox::OnSelect(), Slic3r::GUI::TabPresetComboBox::OnSelect(), Slic3r::GUI::Tab::select_preset(), and Slic3r::PresetCollection::update_dirty().
default_preset() [1/2]
Preset & Slic3r::PresetCollection::default_preset (size_t idx = 0) inline inherited
{ assert(idx < m_num_default_presets); return m_presets[idx]; }
References Slic3r::PresetCollection::m_num_default_presets, and Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::PresetBundle::PresetBundle(), Slic3r::PresetCollection::default_preset_for(), default_preset_for(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), and Slic3r::GUI::Tab::select_preset().
default_preset() [2/2]
const Preset & Slic3r::PresetCollection::default_preset (size_t idx = 0) const inline inherited
{ assert(idx < m_num_default_presets); return m_presets[idx]; }
References Slic3r::PresetCollection::m_num_default_presets, and Slic3r::PresetCollection::m_presets.
default_preset_for()
const Preset & Slic3r::PrinterPresetCollection::default_preset_for (const DynamicPrintConfig & config) const override virtual
Reimplemented from Slic3r::PresetCollection.
{
    const ConfigOptionEnumGeneric *opt_printer_technology = config.opt<ConfigOptionEnumGeneric>("printer_technology");
    return this->default_preset((opt_printer_technology == nullptr || opt_printer_technology->value == ptFFF) ? 0 : 1);
}
References Slic3r::PresetCollection::default_preset(), Slic3r::DynamicConfig::opt(), Slic3r::ptFFF, and Slic3r::ConfigOptionSingle< T >::value.
delete_current_preset()
bool Slic3r::PresetCollection::delete_current_preset () inherited
{
    Preset &selected = this->get_selected_preset();
    if (selected.is_default)
        return false;
    //BBS: add project embedded preset logic and refine is_external
    //if (! selected.is_external && ! selected.is_system) {
    if (! selected.is_system) {
        //BBS Erase the preset file.
        selected.remove_files();
    }
    //BBS: add lock logic for sync preset in background
    lock();
    // Remove the preset from the list.
    m_presets.erase(m_presets.begin() + m_idx_selected);
    unlock();
    // Find the next visible preset.
    size_t new_selected_idx = m_idx_selected;
    if (new_selected_idx < m_presets.size())
        for (; new_selected_idx < m_presets.size() && ! m_presets[new_selected_idx].is_visible; ++ new_selected_idx) ;
    if (new_selected_idx == m_presets.size())
        for (--new_selected_idx; new_selected_idx > 0 && !m_presets[new_selected_idx].is_visible; --new_selected_idx);
    this->select_preset(new_selected_idx);
    return true;
}
References Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::is_default, Slic3r::Preset::is_system, Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_presets, Slic3r::Preset::remove_files(), Slic3r::PresetCollection::select_preset(), and Slic3r::PresetCollection::unlock().
Referenced by Slic3r::GUI::Tab::select_preset().
delete_preset()
bool Slic3r::PresetCollection::delete_preset (const std::string & name) inherited
{
    auto it = this->find_preset_internal(name);
    Preset& preset = *it;
    if (preset.is_default)
        return false;
    //BBS: add project embedded preset logic and refine is_external
    //if (!preset.is_external && !preset.is_system) {
    if (! preset.is_system) {
        preset.remove_files();
    }
    //BBS: add lock logic for sync preset in background
    lock();
    m_presets.erase(it);
    unlock();
    return true;
}
References Slic3r::PresetCollection::find_preset_internal(), Slic3r::Preset::is_default, Slic3r::Preset::is_system, Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::preset(), Slic3r::Preset::remove_files(), and Slic3r::PresetCollection::unlock().
Referenced by Slic3r::PresetCollection::save_user_presets().
dirty_options()
std::vector< std::string > Slic3r::PresetCollection::dirty_options (const Preset * edited, const Preset * reference, const bool deep_compare = false) static inherited
{
    std::vector<std::string> changed;
    if (edited != nullptr && reference != nullptr) {
        // Only compares options existing in both configs.
        changed = deep_compare ?
                deep_diff(edited->config, reference->config) :
                reference->config.diff(edited->config);
        // The "compatible_printers" option key is handled differently from the others:
        // It is not mandatory. If the key is missing, it means it is compatible with any printer.
        // If the key exists and it is empty, it means it is compatible with no printer.
        for (auto &opt_key : optional_keys)
            if (reference->config.has(opt_key) != edited->config.has(opt_key))
                changed.emplace_back(opt_key);
    }
    return changed;
}
References Slic3r::Preset::config, Slic3r::deep_diff(), Slic3r::DynamicConfig::diff(), Slic3r::ConfigOptionResolver::has(), and Slic3r::optional_keys.
Referenced by Slic3r::PresetCollection::current_different_from_parent_options(), Slic3r::PresetCollection::current_dirty_options(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetCollection::get_preset_differed_for_save(), and Slic3r::GUI::DiffPresetDialog::update_tree().
dirty_options_without_option_list()
std::vector< std::string > Slic3r::PresetCollection::dirty_options_without_option_list (const Preset * edited, const Preset * reference, const std::set< std::string > & option_ignore_list, const bool deep_compare = false) static inherited
{
    std::vector<std::string> changed;
    if (edited != nullptr && reference != nullptr) {
        // Only compares options existing in both configs.
        changed = deep_compare ?
                deep_diff(edited->config, reference->config) :
                reference->config.diff(edited->config);
        // The "compatible_printers" option key is handled differently from the others:
        // It is not mandatory. If the key is missing, it means it is compatible with any printer.
        // If the key exists and it is empty, it means it is compatible with no printer.
        for (auto &opt_key : optional_keys) {
            if (reference->config.has(opt_key) != edited->config.has(opt_key))
                changed.emplace_back(opt_key);
        }
        auto iter = changed.begin();
        while (iter != changed.end()) {
            if (option_ignore_list.find(*iter) != option_ignore_list.end()) {
                iter = changed.erase(iter);
            }
            else {
                ++iter;
            }
        }
    }
    return changed;
}
References Slic3r::Preset::config, Slic3r::deep_diff(), Slic3r::DynamicConfig::diff(), Slic3r::ConfigOptionResolver::has(), and Slic3r::optional_keys.
Referenced by Slic3r::PresetBundle::full_fff_config().
discard_current_changes()
void Slic3r::PresetCollection::discard_current_changes () inline inherited
{
        m_presets[m_idx_selected].reset_dirty();
        m_edited_preset = m_presets[m_idx_selected];
//        update_saved_preset_from_current_preset();
    }
References Slic3r::PresetCollection::m_edited_preset, Slic3r::PresetCollection::m_idx_selected, and Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), and Slic3r::GUI::Tab::select_preset().
end() [1/2]
Iterator Slic3r::PresetCollection::end () inline inherited
{ return m_presets.end(); }
References Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::GUI::ExtrusionCalibration::get_bed_type_incompatible(), Slic3r::PresetBundle::load_selections(), Slic3r::GUI::ExtrusionCalibration::on_click_cali(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::AMSMaterialsSetting::on_select_filament(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::sync_ams_list(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), Slic3r::GUI::ExtrusionCalibration::update_filament_info(), and Slic3r::PresetBundle::update_selections().
end() [2/2]
ConstIterator Slic3r::PresetCollection::end () const inline inherited
{ return m_presets.cend(); }
References Slic3r::PresetCollection::m_presets.
erase()
Iterator Slic3r::PresetCollection::erase (Iterator it) inline inherited
{ return m_presets.erase(it); }
References Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::PresetBundle::remove_users_preset().
find_preset() [1/2]
const Preset * Slic3r::PresetCollection::find_preset (const std::string & name, bool first_visible_if_not_found = false) const inline inherited
        { return const_cast<PresetCollection*>(this)->find_preset(name, first_visible_if_not_found); }
References Slic3r::PresetCollection::find_preset(), and Slic3r::PresetCollection::name().
find_preset() [2/2]
Preset * Slic3r::PresetCollection::find_preset (const std::string & name, bool first_visible_if_not_found = false, bool real = false) inherited
{
    Preset key(m_type, name, false);
    auto it = this->find_preset_internal(name);
    // Ensure that a temporary copy is returned if the preset found is currently selected.
    return (it != m_presets.end() && it->name == key.name) ? &this->preset(it - m_presets.begin(), real) :
        first_visible_if_not_found ? &this->first_visible() : nullptr;
}
References Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::PresetCollection::name(), Slic3r::PresetCollection::preset(), and real().
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::TabPrinter::build(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::PresetBundle::export_current_configs(), Slic3r::PresetCollection::find_preset(), Slic3r::GUI::Plater::force_filament_colors_update(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::PresetCollection::get_preset_parent(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetBundle::load_installed_filaments(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetCollection::load_user_preset(), Slic3r::GUI::ConfigWizard::priv::load_vendors(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::reset_project_embedded_presets(), Slic3r::PresetCollection::save_current_preset(), Slic3r::GUI::Tab::save_preset(), Slic3r::PresetCollection::save_user_presets(), Slic3r::GUI::Tab::select_preset(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::PresetComboBox::update_ams_color(), Slic3r::GUI::DiffPresetDialog::update_compatibility(), Slic3r::PresetBundle::update_compatible(), Slic3r::GUI::TabPresetComboBox::update_dirty(), Slic3r::PresetBundle::update_multi_material_filament_presets(), Slic3r::GUI::PhysicalPrinterDialog::update_preset_input(), Slic3r::PresetBundle::update_system_preset_setting_ids(), and Slic3r::GUI::DiffPresetDialog::update_tree().
find_preset_internal() [1/2]
std::deque< Preset >::iterator Slic3r::PresetCollection::find_preset_internal (const std::string & name) inline private inherited
    {
        auto it = Slic3r::lower_bound_by_predicate(m_presets.begin() + m_num_default_presets, m_presets.end(), [&name](const auto& l) { return l.name < name;  });
        if (it == m_presets.end() || it->name != name) {
            // Preset has not been not found in the sorted list of non-default presets. Try the defaults.
            for (size_t i = 0; i < m_num_default_presets; ++ i)
                if (m_presets[i].name == name) {
                    it = m_presets.begin() + i;
                    break;
                }
        }
        return it;
    }
References Slic3r::lower_bound_by_predicate(), Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, and Slic3r::PresetCollection::name().
Referenced by Slic3r::PresetCollection::delete_preset(), Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::get_preset_name_by_alias(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::select_preset_by_name_strict(), Slic3r::PresetBundle::update_selections(), and Slic3r::PresetCollection::validate_printers().
find_preset_internal() [2/2]
std::deque< Preset >::const_iterator Slic3r::PresetCollection::find_preset_internal (const std::string & name) const inline private inherited
        { return const_cast<PresetCollection*>(this)->find_preset_internal(name); }
References Slic3r::PresetCollection::find_preset_internal(), and Slic3r::PresetCollection::name().
find_preset_renamed() [1/2]
std::deque< Preset >::iterator Slic3r::PresetCollection::find_preset_renamed (const std::string & name) inline private inherited
{
      auto it_renamed = m_map_system_profile_renamed.find(name);
      auto it = (it_renamed == m_map_system_profile_renamed.end()) ? m_presets.end() : this->find_preset_internal(it_renamed->second);
      assert((it_renamed == m_map_system_profile_renamed.end()) || (it != m_presets.end() && it->name == it_renamed->second));
      return it;
    }
References Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::m_map_system_profile_renamed, Slic3r::PresetCollection::m_presets, and Slic3r::PresetCollection::name().
Referenced by Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::get_preset_parent(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::PresetCollection::load_external_preset(), and Slic3r::PresetCollection::validate_printers().
find_preset_renamed() [2/2]
std::deque< Preset >::const_iterator Slic3r::PresetCollection::find_preset_renamed (const std::string & name) const inline private inherited
        { return const_cast<PresetCollection*>(this)->find_preset_renamed(name); }
References Slic3r::PresetCollection::find_preset_renamed(), and Slic3r::PresetCollection::name().
find_system_preset_by_model_and_variant()
const Preset * Slic3r::PrinterPresetCollection::find_system_preset_by_model_and_variant (const std::string & model_id, const std::string & variant) const
{
    if (model_id.empty()) { return nullptr; }
    const auto it = std::find_if(cbegin(), cend(), [&](const Preset &preset) {
        if (!preset.is_system || preset.config.opt_string("printer_model") != model_id)
            return false;
        if (variant.empty())
            return true;
        return preset.config.opt_string("printer_variant") == variant;
    });
    return it != cend() ? &*it : nullptr;
}
References Slic3r::PresetCollection::cbegin(), Slic3r::PresetCollection::cend(), Slic3r::Preset::config, Slic3r::Preset::is_system, Slic3r::DynamicConfig::opt_string(), and Slic3r::PresetCollection::preset().
Referenced by Slic3r::PresetBundle::load_selections().
first_compatible() [1/3]
Preset & Slic3r::PresetCollection::first_compatible () inline inherited
{ return this->preset(this->first_compatible_idx()); }
References Slic3r::PresetCollection::first_compatible_idx(), and Slic3r::PresetCollection::preset().
Referenced by Slic3r::PresetBundle::load_selections(), Slic3r::PresetBundle::update_compatible(), and Slic3r::PresetBundle::update_selections().
first_compatible() [2/3]
const Preset & Slic3r::PresetCollection::first_compatible () const inline inherited
{ return this->preset(this->first_compatible_idx()); }
References Slic3r::PresetCollection::first_compatible_idx(), and Slic3r::PresetCollection::preset().
first_compatible() [3/3]
template<typename PreferedCondition > Preset & Slic3r::PresetCollection::first_compatible (PreferedCondition prefered_condition) inline inherited
{ return this->preset(this->first_compatible_idx(prefered_condition)); }
References Slic3r::PresetCollection::first_compatible_idx(), and Slic3r::PresetCollection::preset().
first_compatible_idx() [1/2]
size_t Slic3r::PresetCollection::first_compatible_idx () const inline inherited
{ return this->first_compatible_idx([](const Preset&) -> int { return 0; }); }
References Slic3r::PresetCollection::first_compatible_idx().
Referenced by Slic3r::PresetCollection::first_compatible(), Slic3r::PresetCollection::first_compatible(), Slic3r::PresetCollection::first_compatible(), Slic3r::PresetCollection::first_compatible_idx(), and Slic3r::PresetCollection::update_compatible().
first_compatible_idx() [2/2]
template<typename PreferedCondition > size_t Slic3r::PresetCollection::first_compatible_idx (PreferedCondition prefered_condition) const inline inherited
    {
        size_t i = m_default_suppressed ? m_num_default_presets : 0;
        size_t n = this->m_presets.size();
        size_t i_compatible = n;
        int    match_quality = -1;
        for (; i < n; ++ i)
            // Since we use the filament selection from Wizard, it's needed to control the preset visibility too
            if (m_presets[i].is_compatible && m_presets[i].is_visible) {
                int this_match_quality = prefered_condition(m_presets[i]);
                if (this_match_quality > match_quality) {
                    if (match_quality == std::numeric_limits<int>::max())
                        // Better match will not be found.
                        return i;
                    // Store the first compatible profile with highest match quality into i_compatible.
                    i_compatible = i;
                    match_quality = this_match_quality;
                }
            }
        return (i_compatible == n) ?
            // No compatible preset found, return the default preset.
            0 :
            // Compatible preset found.
            i_compatible;
    }
References Slic3r::PresetCollection::m_default_suppressed, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, and n.
first_visible() [1/2]
Preset & Slic3r::PresetCollection::first_visible () inline inherited
{ return this->preset(this->first_visible_idx()); }
References Slic3r::PresetCollection::first_visible_idx(), and Slic3r::PresetCollection::preset().
Referenced by Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::first_visible_idx(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::reset_project_embedded_presets(), and Slic3r::PresetBundle::update_multi_material_filament_presets().
first_visible() [2/2]
const Preset & Slic3r::PresetCollection::first_visible () const inline inherited
{ return this->preset(this->first_visible_idx()); }
References Slic3r::PresetCollection::first_visible_idx(), and Slic3r::PresetCollection::preset().
first_visible_idx()
size_t Slic3r::PresetCollection::first_visible_idx () const inherited
{
    //BBS: set first visible filament to fla
    size_t first_visible = -1;
    size_t idx = m_default_suppressed ? m_num_default_presets : 0;
    for (; idx < m_presets.size(); ++ idx)
        if (m_presets[idx].is_visible) {
            if (first_visible == -1)
                first_visible = idx;
            if (m_type != Preset::TYPE_FILAMENT)
                break;
            else {
                if (m_presets[idx].name.find("PLA") != std::string::npos) {
                    first_visible = idx;
                    break;
                }
            }
        }
    if (first_visible == -1)
        first_visible = 0;
    return first_visible;
}
References Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::m_default_suppressed, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::PresetCollection::name(), and Slic3r::Preset::TYPE_FILAMENT.
Referenced by Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetBundle::reset_project_embedded_presets(), and Slic3r::PresetCollection::select_preset().
get_differed_values_to_update()
int Slic3r::PresetCollection::get_differed_values_to_update (Preset & preset, std::map< std::string, std::string > & key_values) inherited
{
    if (preset.is_system || preset.is_default || preset.is_project_embedded) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(" Error: not a user preset! Should not happen, name %1%") %preset.name;
        return -1;
    }
    //BBS: only save difference for user preset
    std::string& inherit_preset = preset.inherits();
    Preset* parent_preset = nullptr;
    if (!inherit_preset.empty()) {
        parent_preset = this->find_preset(inherit_preset, false, true);
    }
    if (parent_preset) {
        DynamicPrintConfig temp_config;
        std::vector<std::string> dirty_options = preset.config.diff(parent_preset->config);
        for (auto option: dirty_options)
        {
            ConfigOption *opt_src = preset.config.option(option);
            if (opt_src)
                key_values[option] = opt_src->serialize();
        }
        //add other values
        key_values[BBL_JSON_KEY_VERSION] = preset.version.to_string();
        key_values[BBL_JSON_KEY_BASE_ID] = preset.base_id;
        key_values[BBL_JSON_KEY_UPDATE_TIME] = std::to_string(preset.updated_time);
        key_values[BBL_JSON_KEY_TYPE] = Preset::get_iot_type_string(preset.type);
    }
    else {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(" Error: can not find the parent! Should not happen, name %1%") %preset.name;
        return -1;
    }
    return 0;
}
References Slic3r::Preset::base_id, BBL_JSON_KEY_BASE_ID, BBL_JSON_KEY_TYPE, BBL_JSON_KEY_UPDATE_TIME, BBL_JSON_KEY_VERSION, Slic3r::Preset::config, Slic3r::DynamicConfig::diff(), Slic3r::PresetCollection::dirty_options(), error, Slic3r::PresetCollection::find_preset(), Slic3r::Preset::get_iot_type_string(), Slic3r::Preset::inherits(), Slic3r::Preset::is_default, Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_system, Slic3r::Preset::name, Slic3r::ConfigBase::option(), Slic3r::PresetCollection::preset(), Slic3r::ConfigOption::serialize(), Slic3r::Semver::to_string(), Slic3r::Preset::type, Slic3r::Preset::updated_time, and Slic3r::Preset::version.
Referenced by Slic3r::PresetBundle::get_differed_values_to_update().
get_edited_preset() [1/2]
Preset & Slic3r::PresetCollection::get_edited_preset () inline inherited
{ return m_edited_preset; }
References Slic3r::PresetCollection::m_edited_preset.
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::GLCanvas3D::_render_arrange_menu(), Slic3r::GUI::TabPrinter::apply_extruder_cnt_from_cache(), Slic3r::GUI::GUI_App::apply_keeped_preset_modifications(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::TabPrinter::cache_extruder_cnt(), Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::PresetCollection::current_different_from_parent_options(), Slic3r::PresetCollection::current_dirty_options(), Slic3r::PresetCollection::current_is_dirty(), Slic3r::GUI::Tab::delete_preset(), Slic3r::PresetBundle::export_current_configs(), Slic3r::PresetBundle::export_selections(), Slic3r::GUI::TabPrinter::extruders_count_changed(), Slic3r::GUI::GUI_App::extruders_edited_cnt(), Slic3r::PresetBundle::full_config(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::PresetCollection::get_edited_preset_with_vendor_profile(), Slic3r::Preset::get_printer_type(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::GUI::GUI_App::get_selected_presets(), Slic3r::GUI::GUI_App::has_current_preset_changes(), Slic3r::Preset::has_lidar(), Slic3r::GUI::GUI_App::has_unsaved_preset_changes(), Slic3r::GUI::SelectMachineDialog::is_same_printer_model(), Slic3r::PresetBundle::is_the_only_edited_filament(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::GUI_App::load_current_presets(), Slic3r::PresetCollection::load_external_preset(), Slic3r::GUI::MainFrame::load_printer_url(), Slic3r::PhysicalPrinterCollection::load_printers_from_presets(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::GUI::Plater::merge(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::BackgroundSlicingProcess::process_fff(), Slic3r::GUI::Plater::reslice(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::GUI::Tab::save_preset(), Slic3r::PresetCollection::saved_is_dirty(), Slic3r::GUI::Plater::segment(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::GUI::TabFilament::toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::TabPrinter::update(), Slic3r::GUI::UnsavedChangesDialog::update(), Slic3r::GUI::Sidebar::update_all_preset_comboboxes(), Slic3r::GUI::Tab::update_btns_enabling(), Slic3r::PresetBundle::update_compatible(), Slic3r::GUI::TabFilament::update_description_lines(), Slic3r::PresetCollection::update_dirty(), Slic3r::PresetBundle::update_multi_material_filament_presets(), Slic3r::GUI::TabPrinter::update_pages(), Slic3r::GUI::Sidebar::update_presets(), and Slic3r::GUI::GUI_App::update_saved_preset_from_current_preset().
get_edited_preset() [2/2]
const Preset & Slic3r::PresetCollection::get_edited_preset () const inline inherited
{ return m_edited_preset; }
References Slic3r::PresetCollection::m_edited_preset.
get_edited_preset_with_vendor_profile()
PresetWithVendorProfile Slic3r::PresetCollection::get_edited_preset_with_vendor_profile () const inline inherited
{ return this->get_preset_with_vendor_profile(this->get_edited_preset()); }
References Slic3r::PresetCollection::get_edited_preset(), and Slic3r::PresetCollection::get_preset_with_vendor_profile().
Referenced by Slic3r::GUI::Tab::select_preset(), and Slic3r::PresetBundle::update_compatible().
get_idx_selected()
size_t Slic3r::PresetCollection::get_idx_selected () inline inherited
{ return m_idx_selected; }
References Slic3r::PresetCollection::m_idx_selected.
Referenced by Slic3r::GUI::Tab::select_preset().
get_preset_differed_for_save()
Preset * Slic3r::PresetCollection::get_preset_differed_for_save (Preset & preset) inherited
{
    if (preset.is_system || preset.is_default)
        return nullptr;
    Preset* new_preset = new Preset();
    *new_preset = preset;
    //BBS: only save difference for user preset
    std::string& inherits = preset.inherits();
    Preset* parent_preset = nullptr;
    if (!inherits.empty()) {
        parent_preset = this->find_preset(inherits, false, true);
    }
    if (parent_preset) {
        DynamicPrintConfig temp_config;
        std::vector<std::string> dirty_options = preset.config.diff(parent_preset->config);
        for (auto option: dirty_options)
        {
            ConfigOption *opt_src = preset.config.option(option);
            ConfigOption *opt_dst = temp_config.option(option, true);
            opt_dst->set(opt_src);
        }
        new_preset->config = temp_config;
    }
    return new_preset;
}
References Slic3r::Preset::config, Slic3r::DynamicConfig::diff(), Slic3r::PresetCollection::dirty_options(), Slic3r::PresetCollection::find_preset(), Slic3r::Preset::inherits(), Slic3r::Preset::is_default, Slic3r::Preset::is_system, Slic3r::ConfigBase::option(), Slic3r::PresetCollection::preset(), and Slic3r::ConfigOption::set().
Referenced by Slic3r::PresetBundle::get_preset_differed_for_save(), and Slic3r::PresetCollection::get_project_embedded_presets().
get_preset_name_by_alias()
const std::string & Slic3r::PresetCollection::get_preset_name_by_alias (const std::string & alias) const inherited
{
  for (
    // Find the 1st profile name with the alias.
    auto it = Slic3r::lower_bound_by_predicate(m_map_alias_to_profile_name.begin(), m_map_alias_to_profile_name.end(), [&alias](auto &l){ return l.first < alias; });
    // Continue over all profile names with the same alias.
    it != m_map_alias_to_profile_name.end() && it->first == alias; ++ it)
    if (auto it_preset = this->find_preset_internal(it->second);
      it_preset != m_presets.end() && it_preset->name == it->second &&
            it_preset->is_visible && (it_preset->is_compatible || size_t(it_preset - m_presets.begin()) == m_idx_selected))
          return it_preset->name;
    return alias;
}
References Slic3r::PresetCollection::find_preset_internal(), Slic3r::lower_bound_by_predicate(), Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_map_alias_to_profile_name, and Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::PresetBundle::get_preset_name_by_alias(), and Slic3r::GUI::PhysicalPrinterDialog::update_preset_input().
get_preset_name_renamed()
const std::string * Slic3r::PresetCollection::get_preset_name_renamed (const std::string & old_name) const inherited
{
  auto it_renamed = m_map_system_profile_renamed.find(old_name);
  if (it_renamed != m_map_system_profile_renamed.end())
    return &it_renamed->second;
  return nullptr;
}
References Slic3r::PresetCollection::m_map_system_profile_renamed.
Referenced by Slic3r::GUI::ConfigWizard::priv::load_vendors().
get_preset_parent()
const Preset * Slic3r::PresetCollection::get_preset_parent (const Preset & child) const inherited
{
    const std::string &inherits = child.inherits();
    if (inherits.empty())
//    return this->get_selected_preset().is_system ? &this->get_selected_preset() : nullptr;
        return nullptr;
    const Preset* preset = this->find_preset(inherits, false);
    if (preset == nullptr) {
      auto it = this->find_preset_renamed(inherits);
    if (it != m_presets.end())
      preset = &(*it);
    }
    return
         // not found
        (preset == nullptr/* || preset->is_default */||
         // this should not happen, user profile should not derive from an external profile
         //BBS: add project embedded preset logic and refine is_external
         /*preset->is_external ||*/
         // this should not happen, however people are creative, see GH #4996
         preset == &child) ?
            nullptr :
            preset;
}
References Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_renamed(), Slic3r::Preset::inherits(), Slic3r::PresetCollection::m_presets, and Slic3r::PresetCollection::preset().
Referenced by Slic3r::PresetCollection::get_preset_with_vendor_profile().
get_preset_with_vendor_profile()
PresetWithVendorProfile Slic3r::PresetCollection::get_preset_with_vendor_profile (const Preset & preset) const inherited
{
  const Preset    *p = &preset;
  const VendorProfile *v = nullptr;
  do {
    if (p->vendor != nullptr) {
      v = p->vendor;
      break;
    }
    p = this->get_preset_parent(*p);
  } while (p != nullptr);
  return PresetWithVendorProfile(preset, v);
}
References Slic3r::PresetCollection::get_preset_parent(), Slic3r::PresetCollection::preset(), and Slic3r::Preset::vendor.
Referenced by Slic3r::PresetCollection::get_edited_preset_with_vendor_profile(), Slic3r::PresetBundle::load_installed_sla_materials(), Slic3r::GUI::Tab::select_preset(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::PresetBundle::update_compatible(), and Slic3r::PresetCollection::update_compatible_internal().
get_presets()
const std::deque< Preset > & Slic3r::PresetCollection::get_presets () const inline inherited
{ return m_presets; }
References Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::GUI::PresetComboBox::add_ams_filaments(), Slic3r::GUI::GUI_App::get_selected_presets(), only_default_printers(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
get_project_embedded_presets()
std::vector< Preset * > Slic3r::PresetCollection::get_project_embedded_presets () inherited
{
    std::vector<Preset*> project_presets;
    lock();
    for (Preset &preset : m_presets) {
        //if (preset.type != Preset::get_type_from_string(type)) continue;
        if (!preset.is_project_embedded) continue;
        Preset* new_preset = get_preset_differed_for_save(preset);
        project_presets.push_back(new_preset);
    }
    unlock();
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, type %1% , total preset counts %2%")%Preset::get_type_string(m_type) %project_presets.size();
    return project_presets;
}
References Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::Preset::get_type_string(), Slic3r::Preset::is_project_embedded, Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::PresetCollection::preset(), and Slic3r::PresetCollection::unlock().
Referenced by Slic3r::PresetBundle::get_current_project_embedded_presets().
get_selected_idx()
size_t Slic3r::PresetCollection::get_selected_idx () const inline inherited
{ return m_idx_selected; }
References Slic3r::PresetCollection::m_idx_selected.
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::PresetBundle::load_user_presets(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::PresetBundle::update_compatible().
get_selected_preset() [1/2]
Preset & Slic3r::PresetCollection::get_selected_preset () inline inherited
{
        //BBS fix crash when m_idx_selected == -1, give a default value
        if ((m_idx_selected < 0) || (m_idx_selected >= m_presets.size())) {
            select_preset(first_visible_idx());
        }
        return m_presets[m_idx_selected];
    }
References Slic3r::PresetCollection::first_visible_idx(), Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_presets, and Slic3r::PresetCollection::select_preset().
Referenced by Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::TabPrinter::build(), Slic3r::PresetCollection::current_dirty_options(), Slic3r::PresetCollection::current_is_dirty(), Slic3r::PresetCollection::delete_current_preset(), Slic3r::GUI::Tab::delete_preset(), Slic3r::PresetBundle::export_current_configs(), Slic3r::GUI::GUI_App::extruders_cnt(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::GUI::GCodeViewer::init(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetBundle::load_user_presets(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::reset_project_embedded_presets(), Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::PresetCollection::save_current_preset(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::TabPrintModel::set_model_config(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabFilament::update(), Slic3r::GUI::TabSLAMaterial::update(), Slic3r::GUI::TabSLAPrint::update(), Slic3r::GUI::UnsavedChangesDialog::update(), Slic3r::GUI::DiffPresetDialog::update_compatibility(), Slic3r::PresetCollection::update_dirty(), and Slic3r::GUI::PresetComboBox::update_from_bundle().
get_selected_preset() [2/2]
const Preset & Slic3r::PresetCollection::get_selected_preset () const inline inherited
{ return m_presets[m_idx_selected]; }
References Slic3r::PresetCollection::m_idx_selected, and Slic3r::PresetCollection::m_presets.
get_selected_preset_name()
std::string Slic3r::PresetCollection::get_selected_preset_name () const inline inherited
{
        if (m_idx_selected == size_t(-1) || m_idx_selected >= m_presets.size())
            return std::string();
        return this->get_selected_preset().name;
    }
References Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_presets, and Slic3r::Preset::name.
Referenced by Slic3r::PresetBundle::export_selections(), Slic3r::PresetBundle::full_fff_config(), Slic3r::PresetBundle::full_sla_config(), Slic3r::GUI::GUI_App::get_selected_presets(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetBundle::load_user_presets(), Slic3r::GUI::Plater::priv::on_select_bed_type(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::reset(), Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::PresetCollection::update_after_user_presets_loaded(), Slic3r::GUI::Sidebar::update_all_preset_comboboxes(), Slic3r::GUI::PhysicalPrinterDialog::update_preset_input(), Slic3r::GUI::Sidebar::update_presets(), and Slic3r::PresetBundle::update_selections().
get_selected_preset_parent()
const Preset * Slic3r::PresetCollection::get_selected_preset_parent () const inherited
{
    if (this->get_selected_idx() == size_t(-1))
        // This preset collection has no preset activated yet. Only the get_edited_preset() is valid.
        return nullptr;
    const Preset    &selected_preset = this->get_selected_preset();
    if (selected_preset.is_system || selected_preset.is_default)
        return &selected_preset;
    const Preset    &edited_preset   = this->get_edited_preset();
    const std::string &inherits        = edited_preset.inherits();
    const Preset      *preset          = nullptr;
    if (inherits.empty()) {
        if (selected_preset.is_external)
            return nullptr;
        preset = &this->default_preset(m_type == Preset::Type::TYPE_PRINTER && edited_preset.printer_technology() == ptSLA ? 1 : 0);
    } else
        preset = this->find_preset(inherits, false);
    if (preset == nullptr) {
      // Resolve the "renamed_from" field.
      assert(! inherits.empty());
      auto it = this->find_preset_renamed(inherits);
    if (it != m_presets.end())
      preset = &(*it);
    }
    //BBS: add project embedded preset logic and refine is_external
    return (preset == nullptr/* || preset->is_default || preset->is_external*/) ? nullptr : preset;
    //return (preset == nullptr/* || preset->is_default*/ || preset->is_external) ? nullptr : preset;
}
References Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_idx(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::inherits(), Slic3r::Preset::is_default, Slic3r::Preset::is_external, Slic3r::Preset::is_system, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::PresetCollection::preset(), Slic3r::Preset::printer_technology(), Slic3r::ptSLA, and Slic3r::Preset::TYPE_PRINTER.
Referenced by Slic3r::GUI::TabPrinter::build_fff(), Slic3r::PresetCollection::current_different_from_parent_options(), Slic3r::PresetBundle::full_fff_config(), Slic3r::GUI::Tab::load_current_preset(), and Slic3r::GUI::Tab::save_preset().
get_suffix_modified()
const std::string & Slic3r::PresetCollection::get_suffix_modified () static inherited
{
    return g_suffix_modified;
}
References Slic3r::g_suffix_modified.
Referenced by Slic3r::GUI::EditDevNameDialog::on_edit_name(), Slic3r::GUI::AuFile::on_input_enter(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::SavePresetDialog::Item::update(), and Slic3r::GUI::PhysicalPrinterDialog::update_preset_input().
get_user_presets()
int Slic3r::PresetCollection::get_user_presets (std::vector< Preset > & result_presets) inherited
{
    int count = 0;
    result_presets.clear();
    lock();
    for (Preset &preset : m_presets) {
        if (!preset.is_user()) continue;
        result_presets.push_back(preset);
        count++;
    }
    unlock();
    return count;
}
References count, Slic3r::Preset::is_user(), Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::preset(), and Slic3r::PresetCollection::unlock().
Referenced by Slic3r::GUI::GUI_App::start_sync_user_preset().
has_defaults_only()
bool Slic3r::PresetCollection::has_defaults_only () const inline inherited
{ return m_presets.size() <= m_num_default_presets; }
References Slic3r::PresetCollection::m_num_default_presets, and Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::PresetBundle::has_defauls_only().
is_default_suppressed()
bool Slic3r::PresetCollection::is_default_suppressed () const inline inherited
{ return m_default_suppressed; }
References Slic3r::PresetCollection::m_default_suppressed.
is_dirty()
bool Slic3r::PresetCollection::is_dirty (const Preset * edited, const Preset * reference) static inherited
{
    if (edited != nullptr && reference != nullptr) {
        // Only compares options existing in both configs.
        if (! reference->config.equals(edited->config, &skipped_in_dirty))
            return true;
        // The "compatible_printers" option key is handled differently from the others:
        // It is not mandatory. If the key is missing, it means it is compatible with any printer.
        // If the key exists and it is empty, it means it is compatible with no printer.
        for (auto &opt_key : optional_keys)
            if (reference->config.has(opt_key) != edited->config.has(opt_key))
                return true;
    }
    return false;
}
References Slic3r::Preset::config, Slic3r::DynamicConfig::equals(), Slic3r::ConfigOptionResolver::has(), Slic3r::optional_keys, and Slic3r::skipped_in_dirty.
Referenced by Slic3r::PresetCollection::current_is_dirty(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::saved_is_dirty(), and Slic3r::PresetCollection::update_dirty().
lbegin()
Iterator Slic3r::PresetCollection::lbegin () inline inherited
{ return m_presets.begin(); }
References Slic3r::PresetCollection::m_presets.
load_external_preset()
std::pair< Preset *, bool > Slic3r::PresetCollection::load_external_preset (const std::string & path, const std::string & name, const std::string & original_name, const DynamicPrintConfig & config, const std::set< std::string > & different_settings_list, LoadAndSelect select = LoadAndSelect::Always, const Semver file_version = Semver(), const std::string filament_id = std::string()) inherited
{
    // Load the preset over a default preset, so that the missing fields are filled in from the default preset.
    DynamicPrintConfig cfg(this->default_preset_for(combined_config).config);
    // SoftFever: ignore print connection info from project
    auto        keys = cfg.keys();
    keys.erase(std::remove_if(keys.begin(), keys.end(),
                              [](std::string &val) {
                                return val == "print_host" || val == "print_host_webui" || val == "printhost_apikey" ||
                                       val == "printhost_cafile";
                              }),
               keys.end());
    cfg.apply_only(combined_config, keys, true);
    std::string                 &inherits = Preset::inherits(cfg);
    //BBS: add different settings check logic, replace the old system preset's default value with new system preset's default values
    std::deque<Preset>::iterator it       = this->find_preset_internal(original_name);
    bool                         found    = it != m_presets.end() && it->name == original_name;
    if (! found) {
        // Try to match the original_name against the "renamed_from" profile names of loaded system profiles.
        it = this->find_preset_renamed(original_name);
        found = it != m_presets.end();
    }
    if (!inherits.empty() && (different_settings_list.size() > 0)) {
        auto iter = this->find_preset_internal(inherits);
        if (iter != m_presets.end() && iter->name == inherits) {
            //std::vector<std::string> dirty_options = cfg.diff(iter->config);
            for (auto &opt : keys) {
                if (different_settings_list.find(opt) != different_settings_list.end())
                    continue;
                ConfigOption *opt_src = iter->config.option(opt);
                ConfigOption *opt_dst = cfg.option(opt);
                if (opt_src && opt_dst && (*opt_src != *opt_dst)) {
                    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" change key %1% from old_value %2% to inherit's value %3%, preset_name %4%, inherits_name %5%")
                            %opt %(opt_dst->serialize()) %(opt_src->serialize()) %original_name %inherits;
                    opt_dst->set(opt_src);
                }
            }
        }
    }
    else if (found && it->is_system && (different_settings_list.size() > 0)) {
        for (auto &opt : keys) {
            if (different_settings_list.find(opt) != different_settings_list.end())
                continue;
            ConfigOption *opt_src = it->config.option(opt);
            ConfigOption *opt_dst = cfg.option(opt);
            if (opt_src && opt_dst && (*opt_src != *opt_dst)) {
                BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" change key %1% from old_value %2% to new_value %3%, preset_name %4%")
                        %opt %(opt_dst->serialize()) %(opt_src->serialize()) %original_name;
                opt_dst->set(opt_src);
            }
        }
    }
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, type %1% , path %2%, name %3%, original_name %4%, inherits %5%")%Preset::get_type_string(m_type) %path %name %original_name %inherits;
    if (select == LoadAndSelect::Never) {
        // Some filament profile has been selected and modified already.
        // Check whether this profile is equal to the modified edited profile.
        const Preset &edited = this->get_edited_preset();
        if ((edited.name == original_name || edited.name == inherits) && profile_print_params_same(edited.config, cfg)) {
            // Just point to that already selected and edited profile.
            //BBS: add config related logs
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" Just point to that already selected and edited profile %1%")%edited.name;
            return std::make_pair(&(*this->find_preset_internal(edited.name)), false);
        }
    }
    // Is there a preset already loaded with the name stored inside the config?
    /*std::deque<Preset>::iterator it       = this->find_preset_internal(original_name);
    bool                         found    = it != m_presets.end() && it->name == original_name;
    if (! found) {
        // Try to match the original_name against the "renamed_from" profile names of loaded system profiles.
        it = this->find_preset_renamed(original_name);
        found = it != m_presets.end();
    }*/
    if (found && profile_print_params_same(it->config, cfg)) {
        // The preset exists and it matches the values stored inside config.
        if (select == LoadAndSelect::Always)
            this->select_preset(it - m_presets.begin());
        //BBS: set the preset to visible
        if ( !it->is_visible ) {
            it->is_visible = true;
            //AppConfig* app_config = get_app_config();
            //if (app_config)
            //    app_config->set(AppConfig::SECTION_FILAMENTS, it->name, "1");
        }
        //BBS: add config related logs
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" The preset exists and it matches the values stored inside config. using original_name %1%")%original_name;
        return std::make_pair(&(*it), false);
    }
    if (! found && select != LoadAndSelect::Never && ! inherits.empty()) {
        // Try to use a system profile as a base to select the system profile
        // and override its settings with the loaded ones.
        assert(it == m_presets.end());
        it    = this->find_preset_internal(inherits);
        found = it != m_presets.end() && it->name == inherits;
        if (found && profile_print_params_same(it->config, cfg)) {
            // The system preset exists and it matches the values stored inside config.
            if (select == LoadAndSelect::Always)
                this->select_preset(it - m_presets.begin());
            //BBS: set the preset to visible
            if ( !it->is_visible ) {
                it->is_visible = true;
                //AppConfig* app_config = get_app_config();
                //if (app_config)
                //    app_config->set(AppConfig::SECTION_FILAMENTS, it->name, "1");
            }
            //BBS: add config related logs
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" The preset exists and it matches the values stored inside config. using inherits %1%")%inherits;
            return std::make_pair(&(*it), false);
        }
    }
    if (found) {
        //BBS: only select preset for always
        //if (select != LoadAndSelect::Never) {
        if (select == LoadAndSelect::Always) {
            // Select the existing preset and override it with new values, so that
            // the differences will be shown in the preset editor against the referenced profile.
            this->select_preset(it - m_presets.begin());
            // The source config may contain keys from many possible preset types. Just copy those that relate to this preset.
            //this->get_edited_preset().config.apply_only(combined_config, keys, true);
            this->get_edited_preset().config.apply_only(cfg, keys, true);
            this->update_dirty();
            update_saved_preset_from_current_preset();
            assert(this->get_edited_preset().is_dirty);
            //BBS: set the preset to visible
            if ( !it->is_visible ) {
                it->is_visible = true;
                //AppConfig* app_config = get_app_config();
                //if (app_config)
                //    app_config->set(AppConfig::SECTION_FILAMENTS, it->name, "1");
            }
            //BBS: add config related logs
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" Select the existing preset %1% and override it with new values")%it->name;
            return std::make_pair(&(*it), this->get_edited_preset().is_dirty);
        }
        //BBS: for other filaments under AMS
        if (it->is_project_embedded) {
            //update the properties back to the preset
            it->config.apply_only(cfg, keys, true);
            it->is_dirty = false;
            return std::make_pair(&(*it), false);
        }
        if (inherits.empty()) {
            // Update the "inherits" field.
            // There is a profile with the same name already loaded. Should we update the "inherits" field?
            inherits = it->vendor ? it->name : it->inherits();
        }
    }
    // The external preset does not match an internal preset, load the external preset.
    std::string new_name;
    //BBS: add project embedded preset logic
    //BBS: refine the name logic
    for (size_t idx = 0;; ++ idx) {
        std::string prefix;
        if (original_name.empty()) {
            if (!inherits.empty()) {
                if (idx == 0)
                    prefix = inherits;
                else
                    prefix = inherits + "-" + std::to_string(idx);
            }
            else {
                if (idx > 0)
                    prefix =  std::to_string(idx);
            }
        } else {
            std::string reduced_name = original_name;
            //TODO
            //boost::regex rx("3mf\‍(*\‍)");
            //boost::iterator_range<std::string::iterator> result = boost::algorithm::find_regex(reduced_name, rx);
            //if (!result.empty()) {
            //    reduced_name = std::string(result.begin(), result.end());
            //}
            if (idx == 0)
                prefix = reduced_name;
            else
                prefix = reduced_name + "-" + std::to_string(idx) ;
        }
        //new_name = name + suffix;
        new_name = prefix + "(" + name + ")";
        it = this->find_preset_internal(new_name);
        if (it == m_presets.end() || it->name != new_name)
            // Unique profile name. Insert a new profile.
            break;
        if (profile_print_params_same(it->config, cfg)) {
            // The preset exists and it matches the values stored inside config.
            if (select == LoadAndSelect::Always)
                this->select_preset(it - m_presets.begin());
            //BBS: add config related logs
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" The preset %1% exists and it matches the values stored inside config.")%new_name;
            return std::make_pair(&(*it), false);
        }
        // Form another profile name.
    }
    // Insert a new profile.
    //BBS: add project embedded preset logic
    bool from_project = boost::algorithm::iends_with(name, ".3mf");
    if (m_type == Preset::TYPE_PRINT)
        cfg.option<ConfigOptionString >("print_settings_id", true)->value  = new_name;
    else if (m_type == Preset::TYPE_FILAMENT)
        cfg.option<ConfigOptionStrings>("filament_settings_id", true)->values[0] = new_name;
    else if (m_type == Preset::TYPE_PRINTER)
        cfg.option<ConfigOptionString>("printer_settings_id", true)->value = new_name;
    Preset &preset = this->load_preset(path, new_name, std::move(cfg), select == LoadAndSelect::Always);
    preset.is_external = true;
    preset.version = file_version;
    if (!filament_id.empty())
        preset.filament_id = filament_id;
    else {
        if (!inherits.empty()) {
            Preset *parent = this->find_preset(inherits, false, true);
            if (parent)
                preset.filament_id = parent->filament_id;
        }
    }
    if (from_project) {
        preset.is_project_embedded = true;
    }
    else {
        //external config
        preset.file = path_from_name(preset.name);
        //BBS: save full config here for external
        //we can not reach here
        preset.save(nullptr);
    }
    if (&this->get_selected_preset() == &preset)
        this->get_edited_preset().is_external = true;
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", type %1% added a preset, name %2%, path %3%, is_system %4%, is_default %5% is_external %6%")%Preset::get_type_string(m_type) %preset.name %preset.file %preset.is_system %preset.is_default %preset.is_external;
    return std::make_pair(&preset, false);
}
References Slic3r::PresetCollection::Always, Slic3r::ConfigBase::apply_only(), Slic3r::Preset::config, Slic3r::PresetCollection::default_preset_for(), Slic3r::Preset::filament_id, Slic3r::Preset::file, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::get_type_string(), Slic3r::Preset::inherits(), Slic3r::Preset::is_default, Slic3r::PresetCollection::is_dirty(), Slic3r::Preset::is_external, Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_system, Slic3r::DynamicConfig::keys(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::Preset::name, Slic3r::PresetCollection::name(), Slic3r::PresetCollection::Never, Slic3r::ConfigBase::option(), Slic3r::PresetCollection::path_from_name(), Slic3r::PresetCollection::preset(), Slic3r::profile_print_params_same(), Slic3r::Preset::save(), Slic3r::PresetCollection::select_preset(), Slic3r::ConfigOption::serialize(), Slic3r::ConfigOption::set(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::PresetCollection::update_dirty(), Slic3r::PresetCollection::update_saved_preset_from_current_preset(), and Slic3r::Preset::version.
Referenced by Slic3r::PresetBundle::load_config_file_config().
load_preset() [1/2]
Preset & Slic3r::PresetCollection::load_preset (const std::string & path, const std::string & name, const DynamicPrintConfig & config, bool select = true, Semver file_version = Semver(), bool is_custom_defined = false) inherited
{
    DynamicPrintConfig cfg(this->default_preset().config);
    cfg.apply_only(config, cfg.keys(), true);
    return this->load_preset(path, name, std::move(cfg), select, file_version, is_custom_defined);
}
References Slic3r::ConfigBase::apply_only(), Slic3r::PresetCollection::default_preset(), Slic3r::DynamicConfig::keys(), Slic3r::PresetCollection::load_preset(), and Slic3r::PresetCollection::name().
Referenced by Slic3r::PresetBundle::import_presets(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), and Slic3r::PresetCollection::load_preset().
load_preset() [2/2]
Preset & Slic3r::PresetCollection::load_preset (const std::string & path, const std::string & name, DynamicPrintConfig && config, bool select = true, Semver file_version = Semver(), bool is_custom_defined = false) inherited
{
    lock();
    auto it = this->find_preset_internal(name);
    if (it == m_presets.end() || it->name != name) {
        // The preset was not found. Create a new preset.
        if (m_presets.begin() + m_idx_selected >= it)
            ++m_idx_selected;
        it = m_presets.emplace(it, Preset(m_type, name, false));
    }
    Preset &preset = *it;
    preset.file = path;
    preset.config = std::move(config);
    preset.loaded = true;
    preset.is_dirty = false;
    preset.custom_defined = is_custom_defined ? "1": "0";
    //BBS
    if (file_version.valid())
        preset.version = file_version;
    if (select)
        this->select_preset_by_name(name, true);
    unlock();
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", preset type %1%, name %2%, path %3%, is_system %4%, is_default %5% is_visible %6%")%Preset::get_type_string(m_type) %preset.name %preset.file %preset.is_system %preset.is_default %preset.is_visible;
    return preset;
}
References Slic3r::Preset::config, Slic3r::Preset::custom_defined, Slic3r::Preset::file, Slic3r::PresetCollection::find_preset_internal(), Slic3r::Preset::get_type_string(), Slic3r::Preset::is_default, Slic3r::Preset::is_dirty, Slic3r::Preset::is_system, Slic3r::Preset::is_visible, Slic3r::Preset::loaded, Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::Preset::name, Slic3r::PresetCollection::name(), Slic3r::PresetCollection::preset(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::unlock(), Slic3r::Semver::valid(), and Slic3r::Preset::version.
load_presets()
void Slic3r::PresetCollection::load_presets (const std::string & dir_path, const std::string & subdir, PresetsConfigSubstitutions & substitutions, ForwardCompatibilitySubstitutionRule rule) inherited
{
    // Don't use boost::filesystem::canonical() on Windows, it is broken in regard to reparse points,
    // see https://github.com/prusa3d/PrusaSlicer/issues/732
    boost::filesystem::path dir = boost::filesystem::absolute(boost::filesystem::path(dir_path) / subdir).make_preferred();
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, load presets from %1%, current type %2%")%dir %Preset::get_type_string(m_type);
    //BBS do not parse folder if not exists
    m_dir_path = dir.string();
    if (!fs::exists(dir)) {
        fs::create_directory(dir);
        return;
    }
    std::string errors_cummulative;
    // Store the loaded presets into a new vector, otherwise the binary search for already existing presets would be broken.
    // (see the "Preset already present, not loading" message).
    std::deque<Preset> presets_loaded;
    //BBS: change to json format
    for (auto &dir_entry : boost::filesystem::directory_iterator(dir))
    {
        std::string file_name = dir_entry.path().filename().string();
        //if (Slic3r::is_ini_file(dir_entry)) {
        if (Slic3r::is_json_file(file_name)) {
            // Remove the .ini suffix.
            std::string name = file_name.erase(file_name.size() - 5);
            if (this->find_preset(name, false)) {
                // This happens when there's is a preset (most likely legacy one) with the same name as a system preset
                // that's already been loaded from a bundle.
                BOOST_LOG_TRIVIAL(warning) << "Preset already present, not loading: " << name;
                continue;
            }
            try {
                Preset preset(m_type, name, false);
                preset.file = dir_entry.path().string();
                // Load the preset file, apply preset values on top of defaults.
                try {
                    fs::path idx_path(preset.file);
                    idx_path.replace_extension(".info");
                    if (fs::exists(idx_path)) {
                        preset.load_info(idx_path.string());
                    }
                    DynamicPrintConfig config;
                    //BBS: change to json format
                    //ConfigSubstitutions config_substitutions = config.load_from_ini(preset.file, substitution_rule);
                    std::map<std::string, std::string> key_values;
                    std::string reason;
                    ConfigSubstitutions config_substitutions = config.load_from_json(preset.file, substitution_rule, key_values, reason);
                    if (! config_substitutions.empty())
                        substitutions.push_back({ preset.name, m_type, PresetConfigSubstitutions::Source::UserFile, preset.file, std::move(config_substitutions) });
                    if (!reason.empty()) {
                        fs::path file_path(preset.file);
                        if (fs::exists(file_path))
                            fs::remove(file_path);
                        file_path.replace_extension(".info");
                        if (fs::exists(file_path))
                            fs::remove(file_path);
                        BOOST_LOG_TRIVIAL(error) << boost::format("parse config %1% failed")%preset.file;
                        continue;
                    }
                    std::string version_str = key_values[BBL_JSON_KEY_VERSION];
                    boost::optional<Semver> version = Semver::parse(version_str);
                    if (!version) continue;
                    Semver app_version = *(Semver::parse(SLIC3R_VERSION));
                    if ( version->maj() !=  app_version.maj()) {
                        BOOST_LOG_TRIVIAL(warning) << "Preset incompatibla, not loading: " << name;
                        continue;
                    }
                    preset.version = *version;
                    if (key_values.find(BBL_JSON_KEY_IS_CUSTOM) != key_values.end())
                        preset.custom_defined = key_values[BBL_JSON_KEY_IS_CUSTOM];
                    //BBS: use inherit config as the base
                    Preset* inherit_preset = nullptr;
                    ConfigOption* inherits_config = config.option(BBL_JSON_KEY_INHERITS);
                    // check inherits_config
                    if (inherits_config) {
                        ConfigOptionString * option_str = dynamic_cast<ConfigOptionString *> (inherits_config);
                        std::string inherits_value = option_str->value;
                        inherit_preset = this->find_preset(inherits_value, false, true);
                    } else {
                        ;
                    }
                    const Preset& default_preset = this->default_preset_for(config);
                    if (inherit_preset) {
                        preset.config = inherit_preset->config;
                        preset.filament_id = inherit_preset->filament_id;
                    }
                    else {
                        if (!preset.is_custom_defined()) {
                            BOOST_LOG_TRIVIAL(error) << boost::format("can not find parent for config %1%!")%preset.file;
                            continue;
                        }
                        //should not happen
                        //BOOST_LOG_TRIVIAL(error) << boost::format("can not find parent for config %1%!")%preset.file;
                        // Find a default preset for the config. The PrintPresetCollection provides different default preset based on the "printer_technology" field.
                        preset.config = default_preset.config;
                    }
                    preset.config.apply(std::move(config));
                    Preset::normalize(preset.config);
                    // Report configuration fields, which are misplaced into a wrong group.
                    std::string incorrect_keys = Preset::remove_invalid_keys(preset.config, default_preset.config);
                    if (!incorrect_keys.empty())
                        BOOST_LOG_TRIVIAL(error) << "Error in a preset file: The preset \"" <<
                        preset.file << "\" contains the following incorrect keys: " << incorrect_keys << ", which were removed";
                    preset.loaded = true;
                    //BBS: add some workaround for previous incorrect settings
                    if ((!preset.setting_id.empty())&&(preset.setting_id == preset.base_id))
                        preset.setting_id.clear();
                    //BBS: add config related logs
                    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", preset type %1%, name %2%, path %3%, is_system %4%, is_default %5% is_visible %6%")%Preset::get_type_string(m_type) %preset.name %preset.file %preset.is_system %preset.is_default %preset.is_visible;
                } catch (const std::ifstream::failure &err) {
                    BOOST_LOG_TRIVIAL(error) << boost::format("The user-config cannot be loaded: %1%. Reason: %2%")%preset.file %err.what();
                    fs::path file_path(preset.file);
                    if (fs::exists(file_path))
                        fs::remove(file_path);
                    file_path.replace_extension(".info");
                    if (fs::exists(file_path))
                        fs::remove(file_path);
                    //throw Slic3r::RuntimeError(std::string("The selected preset cannot be loaded: ") + preset.file + "\n\tReason: " + err.what());
                } catch (const std::runtime_error &err) {
                    BOOST_LOG_TRIVIAL(error) << boost::format("Failed loading the user-config file: %1%. Reason: %2%")%preset.file %err.what();
                    //throw Slic3r::RuntimeError(std::string("Failed loading the preset file: ") + preset.file + "\n\tReason: " + err.what());
                    fs::path file_path(preset.file);
                    if (fs::exists(file_path))
                        fs::remove(file_path);
                    file_path.replace_extension(".info");
                    if (fs::exists(file_path))
                        fs::remove(file_path);
                }
                presets_loaded.emplace_back(preset);
            } catch (const std::runtime_error &err) {
                errors_cummulative += err.what();
                errors_cummulative += "\n";
            }
        }
    }
    if (presets_loaded.size() > 0)
        m_presets.insert(m_presets.end(), std::make_move_iterator(presets_loaded.begin()), std::make_move_iterator(presets_loaded.end()));
    std::sort(m_presets.begin() + m_num_default_presets, m_presets.end());
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": loaded %1% presets from %2%, type %3%")%presets_loaded.size() %dir %Preset::get_type_string(m_type);
    //this->select_preset(first_visible_idx());
    if (! errors_cummulative.empty())
        throw Slic3r::RuntimeError(errors_cummulative);
}
References Slic3r::ConfigBase::apply(), Slic3r::Preset::base_id, BBL_JSON_KEY_INHERITS, BBL_JSON_KEY_IS_CUSTOM, BBL_JSON_KEY_VERSION, Slic3r::Preset::config, Slic3r::Preset::custom_defined, Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::default_preset_for(), error, Slic3r::Preset::filament_id, Slic3r::Preset::file, Slic3r::PresetCollection::find_preset(), Slic3r::Preset::get_type_string(), Slic3r::Preset::is_custom_defined(), Slic3r::Preset::is_default, Slic3r::is_json_file(), Slic3r::Preset::is_system, Slic3r::Preset::is_visible, Slic3r::ConfigBase::load_from_json(), Slic3r::Preset::load_info(), Slic3r::Preset::loaded, Slic3r::PresetCollection::m_dir_path, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::Semver::maj(), Slic3r::Preset::name, Slic3r::PresetCollection::name(), Slic3r::Preset::normalize(), Slic3r::ConfigBase::option(), Slic3r::Semver::parse(), Slic3r::PresetCollection::preset(), Slic3r::Preset::remove_invalid_keys(), Slic3r::Preset::setting_id, Slic3r::PresetConfigSubstitutions::UserFile, Slic3r::ConfigOptionSingle< T >::value, and Slic3r::Preset::version.
Referenced by Slic3r::PresetBundle::load_user_presets().
load_project_embedded_presets()
void Slic3r::PresetCollection::load_project_embedded_presets (std::vector< Preset * > & project_presets, const std::string & type, PresetsConfigSubstitutions & substitutions, ForwardCompatibilitySubstitutionRule rule) inherited
{
    std::string errors_cummulative;
    // Store the loaded presets into a new vector, otherwise the binary search for already existing presets would be broken.
    // (see the "Preset already present, not loading" message).
    std::deque<Preset> presets_loaded;
    std::vector<Preset*>::iterator it;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, type %1% , total preset counts %2%")%Preset::get_type_string(m_type) %project_presets.size();
    lock();
    for (it = project_presets.begin(); it != project_presets.end(); it++) {
        Preset* preset = *it;
        if (preset->type != Preset::get_type_from_string(type)) continue;
        if (!preset->is_project_embedded) continue;
        std::string name = preset->name;
        if (this->find_preset(name, false)) {
            BOOST_LOG_TRIVIAL(warning) << "Preset already present, not loading: " << name;
            continue;
        }
        try {
            DynamicPrintConfig config = preset->config;
            if (preset->loading_substitutions && ! preset->loading_substitutions->empty()) {
                substitutions.push_back({ preset->name, m_type, PresetConfigSubstitutions::Source::ProjectFile, preset->name, std::move(*(preset->loading_substitutions))});
                free(preset->loading_substitutions);
                preset->loading_substitutions = NULL;
            }
            //BBS: use inherit config as the base
            Preset* inherit_preset = nullptr;
            ConfigOption* inherits_config = config.option(BBL_JSON_KEY_INHERITS);
            if (inherits_config) {
                ConfigOptionString * option_str = dynamic_cast<ConfigOptionString *> (inherits_config);
                std::string inherits_value = option_str->value;
                /*size_t pos = inherits_value.find_first_of('*');
                if (pos != std::string::npos) {
                    inherits_value.replace(pos, 1, 1, '~');
                    option_str->value = inherits_value;
                }*/
                inherit_preset = this->find_preset(inherits_value, false, true);
            }
            const Preset& default_preset = this->default_preset_for(config);
            if (inherit_preset) {
                preset->config = inherit_preset->config;
                preset->filament_id = inherit_preset->filament_id;
            }
            else {
                // Find a default preset for the config. The PrintPresetCollection provides different default preset based on the "printer_technology" field.
                preset->config = default_preset.config;
                BOOST_LOG_TRIVIAL(warning) << boost::format("can not find parent for config %1%!")%preset->file;
                //continue;
            }
            preset->config.apply(std::move(config));
            Preset::normalize(preset->config);
            // Report configuration fields, which are misplaced into a wrong group.
            std::string incorrect_keys = Preset::remove_invalid_keys(preset->config, default_preset.config);
            if (! incorrect_keys.empty())
                BOOST_LOG_TRIVIAL(error) << "Error in a preset file: The preset \"" <<
                    preset->name << "\" contains the following incorrect keys: " << incorrect_keys << ", which were removed";
            preset->loaded = true;
            presets_loaded.emplace_back(*preset);
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", %1% got preset, name %2%, path %3%, is_system %4%, is_default %5% is_visible %6%")%Preset::get_type_string(m_type) %preset->name %preset->file %preset->is_system %preset->is_default %preset->is_visible;
        } catch (const std::runtime_error &err) {
            errors_cummulative += err.what();
            errors_cummulative += "\n";
        }
    }
    m_presets.insert(m_presets.end(), std::make_move_iterator(presets_loaded.begin()), std::make_move_iterator(presets_loaded.end()));
    std::sort(m_presets.begin() + m_num_default_presets, m_presets.end());
    //don't select it here
    //this->select_preset(first_visible_idx());
    unlock();
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" finished, %1% got %2% presets, errors_cummulative %3%")%Preset::get_type_string(m_type) %presets_loaded.size() %errors_cummulative;
    if (! errors_cummulative.empty())
        throw Slic3r::RuntimeError(errors_cummulative);
}
References Slic3r::ConfigBase::apply(), BBL_JSON_KEY_INHERITS, Slic3r::Preset::config, Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::default_preset_for(), error, Slic3r::Preset::filament_id, Slic3r::Preset::file, Slic3r::PresetCollection::find_preset(), Slic3r::Preset::get_type_from_string(), Slic3r::Preset::get_type_string(), Slic3r::Preset::is_default, Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_system, Slic3r::Preset::is_visible, Slic3r::Preset::loaded, Slic3r::Preset::loading_substitutions, Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::Preset::name, Slic3r::PresetCollection::name(), Slic3r::Preset::normalize(), NULL, Slic3r::ConfigBase::option(), Slic3r::PresetCollection::preset(), Slic3r::PresetConfigSubstitutions::ProjectFile, Slic3r::Preset::remove_invalid_keys(), Slic3r::Preset::type, Slic3r::PresetCollection::type(), Slic3r::PresetCollection::unlock(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::PresetBundle::load_project_embedded_presets().
load_user_preset()
bool Slic3r::PresetCollection::load_user_preset (std::string name, std::map< std::string, std::string > preset_values, PresetsConfigSubstitutions & substitutions, ForwardCompatibilitySubstitutionRule rule) inherited
{
    std::string errors_cummulative;
    // Store the loaded presets into a new vector, otherwise the binary search for already existing presets would be broken.
    // (see the "Preset already present, not loading" message).
    //std::deque<Preset> presets_loaded;
    int count = 0;
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" enter, name %1% , total value counts %2%")%name %preset_values.size();
    //if the version is not matching, skip it
    if (preset_values.find(BBL_JSON_KEY_VERSION) == preset_values.end()) {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format("can not find version, not loading for user preset %1%")%name;
        return false;
    }
    std::string version_str = preset_values[BBL_JSON_KEY_VERSION];
    boost::optional<Semver> cloud_version = Semver::parse(version_str);
    if (!cloud_version) {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format("invalid version %1%, not loading for user preset %2%")%version_str %name;
        return false;
    }
    Semver app_version = *(Semver::parse(SLIC3R_VERSION));
    if ( cloud_version->maj() !=  app_version.maj()) {
        BOOST_LOG_TRIVIAL(warning)<< __FUNCTION__ << boost::format("version %1% mismatch with app version %2%, not loading for user preset %3%")%version_str %SLIC3R_VERSION %name;
        return false;
    }
    //setting_id
    if (preset_values.find(BBL_JSON_KEY_SETTING_ID) == preset_values.end()) {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format("can not find setting_id, not loading for user preset %1%")%name;
        return false;
    }
    std::string cloud_setting_id = preset_values[BBL_JSON_KEY_SETTING_ID];
    //base_id
    if (preset_values.find(BBL_JSON_KEY_BASE_ID) == preset_values.end()) {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format("can not find base_id, not loading for user preset %1%")%name;
        return false;
    }
    std::string cloud_base_id = preset_values[BBL_JSON_KEY_BASE_ID];
    //update_time
    long long cloud_update_time = 0;
    if (preset_values.find(BBL_JSON_KEY_UPDATE_TIME) != preset_values.end()) {
        cloud_update_time = std::atoll(preset_values[BBL_JSON_KEY_UPDATE_TIME].c_str());
    }
    //user_id
    if (preset_values.find(BBL_JSON_KEY_USER_ID) == preset_values.end()) {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format("can not find user_id, not loading for user preset %1%")%name;
        return false;
    }
    std::string cloud_user_id = preset_values[BBL_JSON_KEY_USER_ID];
    //filament_id
    std::string cloud_filament_id;
    if ((m_type == Preset::TYPE_FILAMENT) && preset_values.find(BBL_JSON_KEY_FILAMENT_ID) != preset_values.end()) {
        cloud_filament_id = preset_values[BBL_JSON_KEY_FILAMENT_ID];
    }
    lock();
    //std::string name = preset->name;
    auto iter = this->find_preset_internal(name);
    bool need_update = false;
    if ((iter != m_presets.end()) && (iter->name == name)) {
        BOOST_LOG_TRIVIAL(info) << "Found the Preset locally: " << name;
        //BBS: we should compare the time between cloud and local
        if ((cloud_update_time == 0) || (cloud_update_time <= iter->updated_time)) {
            if (cloud_update_time < iter->updated_time)
                iter->sync_info = "update";
            else
                iter->sync_info.clear();
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("preset %1%'s update_time is eqaul or newer, cloud  update_time %2%, local update_time %3%")%name %cloud_update_time %iter->updated_time;
            unlock();
            return false;
        }
        else {
            //update the one from cloud which is newer
            need_update = true;
            iter->sync_info.clear();
        }
    }
    DynamicPrintConfig  new_config, cloud_config;
    try {
        ConfigSubstitutions config_substitutions = cloud_config.load_string_map(preset_values, rule);
        if (! config_substitutions.empty())
            substitutions.push_back({ name, m_type, PresetConfigSubstitutions::Source::UserCloud, name, std::move(config_substitutions) });
        //BBS: use inherit config as the base
        Preset* inherit_preset = nullptr;
        ConfigOption* inherits_config = cloud_config.option(BBL_JSON_KEY_INHERITS);
        if (inherits_config) {
            ConfigOptionString * option_str = dynamic_cast<ConfigOptionString *> (inherits_config);
            std::string inherits_value = option_str->value;
            /*size_t pos = inherits_value.find_first_of('*');
            if (pos != std::string::npos) {
                inherits_value.replace(pos, 1, 1, '~');
                option_str->value = inherits_value;
            }*/
            inherit_preset = this->find_preset(inherits_value, false, true);
        }
        const Preset& default_preset = this->default_preset_for(cloud_config);
        if (inherit_preset) {
            new_config = inherit_preset->config;
        }
        else {
            // Find a default preset for the config. The PrintPresetCollection provides different default preset based on the "printer_technology" field.
            //new_config = default_preset.config;
            //we should skip this preset here
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(", can not find inherit preset for user preset %1%, just skip")%name;
            unlock();
            return false;
        }
        new_config.apply(std::move(cloud_config));
        Preset::normalize(new_config);
        // Report configuration fields, which are misplaced into a wrong group.
        std::string incorrect_keys = Preset::remove_invalid_keys(new_config, default_preset.config);
        if (! incorrect_keys.empty())
            BOOST_LOG_TRIVIAL(error) << "Error in a preset file: The preset \"" <<
                name << "\" contains the following incorrect keys: " << incorrect_keys << ", which were removed";
        if (need_update) {
            if (iter->name == m_edited_preset.name && iter->is_dirty) {
                // Keep modifies when update from remote
                new_config.apply_only(m_edited_preset.config, m_edited_preset.config.diff(iter->config));
            }
            iter->config = new_config;
            iter->updated_time = cloud_update_time;
            iter->version = cloud_version.value();
            iter->user_id = cloud_user_id;
            iter->setting_id = cloud_setting_id;
            iter->base_id = cloud_base_id;
            iter->filament_id = cloud_filament_id;
            //presets_loaded.emplace_back(*it->second);
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", update the user preset %1% from cloud, type %2%, setting_id %3%, base_id %4%, sync_info %5% inherits %6%")
               % iter->name %Preset::get_type_string(m_type) %iter->setting_id %iter->base_id %iter->sync_info %iter->inherits();
        }
        else {
            //create a new one
            Preset preset(m_type, name, false);
            preset.is_system = false;
            preset.loaded = true;
            preset.config = new_config;
            preset.updated_time = cloud_update_time;
            preset.version = cloud_version.value();
            preset.user_id = cloud_user_id;
            preset.setting_id = cloud_setting_id;
            preset.base_id = cloud_base_id;
            preset.filament_id = cloud_filament_id;
            size_t cur_index = iter - m_presets.begin();
            m_presets.insert(iter, preset);
            //m_presets.emplace_back (preset);
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", insert a new user preset %1%, type %2%, setting_id %3%, base_id %4%, sync_info %5% inherits %6%")
               %preset.name %Preset::get_type_string(m_type) %preset.setting_id %preset.base_id %preset.sync_info %preset.inherits();
            if (cur_index <= m_idx_selected) {
                m_idx_selected ++;
                BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(", increase m_idx_selected to %1%, due to user preset inserted")%m_idx_selected;
            }
        }
    } catch (const std::runtime_error &err) {
        errors_cummulative += err.what();
        errors_cummulative += "\n";
    }
    unlock();
    if (! errors_cummulative.empty())
        throw Slic3r::RuntimeError(errors_cummulative);
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" finished, load user preset %1% , type %2%, errors_cummulative %3%")%name %Preset::get_type_string(m_type) %errors_cummulative;
    return (need_update)?false:true;
}
References Slic3r::ConfigBase::apply(), Slic3r::ConfigBase::apply_only(), Slic3r::Preset::base_id, BBL_JSON_KEY_BASE_ID, BBL_JSON_KEY_FILAMENT_ID, BBL_JSON_KEY_INHERITS, BBL_JSON_KEY_SETTING_ID, BBL_JSON_KEY_UPDATE_TIME, BBL_JSON_KEY_USER_ID, BBL_JSON_KEY_VERSION, Slic3r::Preset::config, count, Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::default_preset_for(), Slic3r::DynamicConfig::diff(), error, Slic3r::Preset::filament_id, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::Preset::get_type_string(), Slic3r::Preset::inherits(), Slic3r::Preset::is_system, Slic3r::ConfigBase::load_string_map(), Slic3r::Preset::loaded, Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_edited_preset, Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::Semver::maj(), Slic3r::Preset::name, Slic3r::PresetCollection::name(), Slic3r::Preset::normalize(), Slic3r::ConfigBase::option(), Slic3r::Semver::parse(), Slic3r::PresetCollection::preset(), Slic3r::Preset::remove_invalid_keys(), Slic3r::Preset::setting_id, Slic3r::Preset::sync_info, Slic3r::Preset::TYPE_FILAMENT, Slic3r::PresetCollection::unlock(), Slic3r::Preset::updated_time, Slic3r::Preset::user_id, Slic3r::PresetConfigSubstitutions::UserCloud, Slic3r::ConfigOptionSingle< T >::value, and Slic3r::Preset::version.
Referenced by Slic3r::PresetBundle::load_user_presets().
lock()
void Slic3r::PresetCollection::lock () inline inherited
{ m_mutex.lock(); }
References Slic3r::PresetCollection::m_mutex.
Referenced by Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::delete_preset(), Slic3r::PresetCollection::get_project_embedded_presets(), Slic3r::PresetCollection::get_user_presets(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::reset(), Slic3r::PresetCollection::reset_project_embedded_presets(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::set_sync_info_and_save(), and Slic3r::PresetCollection::update_after_user_presets_loaded().
merge_presets()
std::vector< std::string > Slic3r::PresetCollection::merge_presets (PresetCollection && other, const VendorMap & new_vendors) protected inherited
{
    std::vector<std::string> duplicates;
    for (Preset &preset : other.m_presets) {
        if (preset.is_default || preset.is_external)
            continue;
        Preset key(m_type, preset.name);
        auto it = std::lower_bound(m_presets.begin() + m_num_default_presets, m_presets.end(), key);
        if (it == m_presets.end() || it->name != preset.name) {
            if (preset.vendor != nullptr) {
                // Re-assign a pointer to the vendor structure in the new PresetBundle.
                auto it = new_vendors.find(preset.vendor->id);
                assert(it != new_vendors.end());
                preset.vendor = &it->second;
            }
            m_presets.emplace(it, std::move(preset));
        } else
            duplicates.emplace_back(std::move(preset.name));
    }
    return duplicates;
}
References Slic3r::VendorProfile::id, Slic3r::Preset::is_default, Slic3r::Preset::is_external, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::Preset::name, Slic3r::PresetCollection::preset(), and Slic3r::Preset::vendor.
Referenced by Slic3r::PresetBundle::merge_presets().
name()
std::string Slic3r::PresetCollection::name () const inherited
{
    switch (this->type()) {
    case Preset::TYPE_PRINT:        return L(PRESET_PRINT_NAME);
    case Preset::TYPE_FILAMENT:     return L(PRESET_FILAMENT_NAME);
    //case Preset::TYPE_SLA_PRINT:    return L("SLA print");
    //case Preset::TYPE_SLA_MATERIAL: return L("SLA material");
    case Preset::TYPE_PRINTER:      return L(PRESET_PRINTER_NAME);
    default:                        return "invalid";
    }
}
References L, PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, Slic3r::PresetCollection::type(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, and Slic3r::Preset::TYPE_PRINTER.
Referenced by Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::first_visible_idx(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::GUI::Tab::name(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::select_preset_by_name_strict(), Slic3r::PresetCollection::set_sync_info_and_save(), and Slic3r::PresetCollection::validate_printers().
num_default_presets()
size_t Slic3r::PresetCollection::num_default_presets () inline inherited
{ return m_num_default_presets; }
References Slic3r::PresetCollection::m_num_default_presets.
Referenced by Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::GUI::PlaterPresetComboBox::update(), Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::PresetComboBox::update().
num_visible()
size_t Slic3r::PresetCollection::num_visible () const inline inherited
{ return std::count_if(m_presets.begin(), m_presets.end(), [](const Preset &preset){return preset.is_visible;}); }
References Slic3r::PresetCollection::m_presets, and Slic3r::PresetCollection::preset().
only_default_printers()
bool Slic3r::PrinterPresetCollection::only_default_printers () const
{
    for (const auto& printer : get_presets()) {
        if (!boost::starts_with(printer.name,"Default") && printer.is_visible)
            return false;
    }
    return true;
}
References Slic3r::PresetCollection::get_presets().
Referenced by Slic3r::GUI::GUI_App::config_wizard_startup(), and Slic3r::GUI::GuideFrame::run().
operator()()
const std::deque< Preset > & Slic3r::PresetCollection::operator() () const inline inherited
{ return m_presets; }
References Slic3r::PresetCollection::m_presets.
operator=()
PrinterPresetCollection & Slic3r::PrinterPresetCollection::operator= (const PrinterPresetCollection & other) private default
path_from_name()
std::string Slic3r::PresetCollection::path_from_name (const std::string & new_name) const inherited
{
     //BBS: change to json format
    //std::string file_name = boost::iends_with(new_name, ".ini") ? new_name : (new_name + ".ini");
    std::string file_name = boost::iends_with(new_name, ".json") ? new_name : (new_name + ".json");
    return (boost::filesystem::path(m_dir_path) / file_name).make_preferred().string();
}
References Slic3r::PresetCollection::m_dir_path.
Referenced by Slic3r::PresetBundle::import_presets(), Slic3r::PresetBundle::load_config_file_config(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::save_current_preset(), and Slic3r::PresetCollection::save_user_presets().
preset() [1/2]
const Preset & Slic3r::PresetCollection::preset (size_t idx) const inline inherited
{ return const_cast<PresetCollection*>(this)->preset(idx); }
References Slic3r::PresetCollection::preset().
Referenced by Slic3r::PresetCollection::preset().
preset() [2/2]
Preset & Slic3r::PresetCollection::preset (size_t idx, bool real = false) inline inherited
{
        if (real) return m_presets[idx];
        return (idx == m_idx_selected) ? m_edited_preset : m_presets[idx];
    }
References Slic3r::PresetCollection::m_edited_preset, Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_presets, and real().
Referenced by Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::PresetCollection::delete_preset(), Slic3r::PresetCollection::find_preset(), find_system_preset_by_model_and_variant(), Slic3r::PresetCollection::first_compatible(), Slic3r::PresetCollection::first_compatible(), Slic3r::PresetCollection::first_compatible(), Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::first_visible(), Slic3r::PresetCollection::get_differed_values_to_update(), Slic3r::PresetCollection::get_preset_differed_for_save(), Slic3r::PresetCollection::get_preset_parent(), Slic3r::PresetCollection::get_preset_with_vendor_profile(), Slic3r::PresetCollection::get_project_embedded_presets(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::PresetCollection::get_user_presets(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::merge_presets(), Slic3r::PresetCollection::num_visible(), Slic3r::PresetCollection::reset(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::save_user_presets(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::set_sync_info_and_save(), Slic3r::PresetCollection::system_preset_names(), Slic3r::PresetCollection::update_map_alias_to_profile_name(), Slic3r::PresetCollection::update_map_system_profile_renamed(), and Slic3r::PresetCollection::update_vendor_ptrs_after_copy().
reset()
void Slic3r::PresetCollection::reset (bool delete_files) inherited
{
    //BBS: add lock logic for sync preset in background
    lock();
    if (m_presets.size() > m_num_default_presets) {
        if (delete_files) {
            // Erase the preset files.
            for (Preset &preset : m_presets)
                if (! preset.is_default && ! preset.is_external && ! preset.is_system) {
                    //BBS remove idx and ini files
                    preset.remove_files();
                }
        }
        // Don't use m_presets.resize() here as it requires a default constructor for Preset.
        m_presets.erase(m_presets.begin() + m_num_default_presets, m_presets.end());
        this->select_preset(0);
    }
    //BBS: add lock logic for sync preset in background
    unlock();
    m_map_alias_to_profile_name.clear();
    m_map_system_profile_renamed.clear();
}
References Slic3r::Preset::is_default, Slic3r::Preset::is_external, Slic3r::Preset::is_system, Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_map_alias_to_profile_name, Slic3r::PresetCollection::m_map_system_profile_renamed, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::preset(), Slic3r::Preset::remove_files(), Slic3r::PresetCollection::select_preset(), and Slic3r::PresetCollection::unlock().
Referenced by Slic3r::PresetBundle::reset().
reset_project_embedded_presets()
bool Slic3r::PresetCollection::reset_project_embedded_presets () inherited
{
    std::deque<Preset>::iterator it = m_presets.begin();
    bool re_select = false;
    int count = -1;
    lock();
    while ( it!=m_presets.end() )
    {
        count++;
        //if (preset.type != Preset::get_type_from_string(type)) continue;
        if (it->is_project_embedded) {
            BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" type %1% , delete preset %2%")%Preset::get_type_string(m_type) % it->name;
            if ((!re_select) && (m_idx_selected == count))
                re_select = true;
            if (m_idx_selected > count) {
                m_idx_selected--;
                count--;
            }
            it = m_presets.erase(it);
        }
        else
            it++;
    }
    if (re_select)
        m_idx_selected = -1;
    unlock();
    return re_select;
}
References count, Slic3r::Preset::get_type_string(), Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, and Slic3r::PresetCollection::unlock().
Referenced by Slic3r::PresetBundle::reset_project_embedded_presets().
save_current_preset()
void Slic3r::PresetCollection::save_current_preset (const std::string & new_name, bool detach = false, bool save_to_project = false, Preset * _curr_preset = nullptr) inherited
{
    Preset curr_preset = _curr_preset ? *_curr_preset : m_edited_preset;
    //BBS: add lock logic for sync preset in background
    std::string final_inherits;
    lock();
    // 1) Find the preset with a new_name or create a new one,
    // initialize it with the edited config.
    auto it = this->find_preset_internal(new_name);
    if (it != m_presets.end() && it->name == new_name) {
        // Preset with the same name found.
        Preset &preset = *it;
        //BBS: add project embedded preset logic
        if (preset.is_default || preset.is_system) {
        //if (preset.is_default || preset.is_external || preset.is_system)
            // Cannot overwrite the default preset.
            //BBS: add lock logic for sync preset in background
            unlock();
            return;
        }
        // Overwriting an existing preset.
        preset.config = std::move(curr_preset.config);
        // The newly saved preset will be activated -> make it visible.
        preset.is_visible = true;
        //TODO: remove the detach logic
        if (detach) {
            // Clear the link to the parent profile.
            preset.vendor = nullptr;
      preset.inherits().clear();
      preset.alias.clear();
      preset.renamed_from.clear();
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": save preset %1% , with detach")%new_name;
        }
        //BBS: add lock logic for sync preset in background
        final_inherits = preset.inherits();
        unlock();
    } else {
        // Creating a new preset.
        Preset       &preset   = *m_presets.insert(it, curr_preset);
        std::string  &inherits = preset.inherits();
        std::string   old_name = preset.name;
        preset.name = new_name;
        preset.file = this->path_from_name(new_name);
        preset.vendor = nullptr;
    preset.alias.clear();
        preset.renamed_from.clear();
        preset.setting_id.clear();
        if (detach) {
          // Clear the link to the parent profile.
          inherits.clear();
            BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": save preset %1% , with detach")%new_name;
        } else if (preset.is_system) {
            // Inheriting from a system preset.
            inherits = /* preset.vendor->name + "/" + */ old_name;
        } else if (inherits.empty()) {
            // Inheriting from a user preset. Link the new preset to the old preset.
            // inherits = old_name;
        } else {
            // Inherited from a user preset. Just maintain the "inherited" flag,
            // meaning it will inherit from either the system preset, or the inherited user preset.
        }
        preset.is_default  = false;
        preset.is_system   = false;
        preset.is_external = false;
        // The newly saved preset will be activated -> make it visible.
        preset.is_visible  = true;
        // Just system presets have aliases
        preset.alias.clear();
        //BBS: add project embedded preset logic
        if (save_to_project) {
            preset.is_project_embedded = true;
        }
        else
            preset.is_project_embedded = false;
        if (m_type == Preset::TYPE_PRINT)
            preset.config.option<ConfigOptionString >("print_settings_id", true)->value  = preset.name;
        else if (m_type == Preset::TYPE_FILAMENT)
            preset.config.option<ConfigOptionStrings>("filament_settings_id", true)->values[0] = preset.name;
        else if (m_type == Preset::TYPE_PRINTER)
            preset.config.option<ConfigOptionString>("printer_settings_id", true)->value = preset.name;
        //BBS: add lock logic for sync preset in background
        final_inherits = inherits;
        unlock();
    }
    // 2) Activate the saved preset.
    this->select_preset_by_name(new_name, true);
    // 2) Store the active preset to disk.
    //BBS: only save difference for user preset
    Preset* parent_preset = nullptr;
    if (!final_inherits.empty()) {
        parent_preset = this->find_preset(final_inherits, false, true);
        if (parent_preset && this->get_selected_preset().base_id.empty()) {
            this->get_selected_preset().base_id = parent_preset->setting_id;
        }
    }
    this->get_selected_preset().updated_time = (long long)Slic3r::Utils::get_current_time_utc();
    if (parent_preset)
        this->get_selected_preset().save(&(parent_preset->config));
    else
        this->get_selected_preset().save(nullptr);
}
References Slic3r::Preset::alias, Slic3r::Preset::base_id, Slic3r::Preset::config, Slic3r::Preset::file, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::Utils::get_current_time_utc(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::inherits(), Slic3r::Preset::is_default, Slic3r::Preset::is_external, Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_system, Slic3r::Preset::is_visible, Slic3r::PresetCollection::lock(), long, Slic3r::PresetCollection::m_edited_preset, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::Preset::name, Slic3r::ConfigBase::option(), Slic3r::PresetCollection::path_from_name(), Slic3r::PresetCollection::preset(), Slic3r::Preset::renamed_from, Slic3r::Preset::save(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::Preset::setting_id, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::PresetCollection::unlock(), Slic3r::Preset::updated_time, and Slic3r::Preset::vendor.
Referenced by Slic3r::PresetBundle::save_changes_for_preset(), and Slic3r::GUI::Tab::save_preset().
save_user_presets()
void Slic3r::PresetCollection::save_user_presets (const std::string & dir_path, const std::string & type, std::vector< std::string > & need_to_delete_list) inherited
{
    boost::filesystem::path dir = boost::filesystem::absolute(boost::filesystem::path(dir_path) / type).make_preferred();
    if (!fs::exists(dir))
        fs::create_directory(dir);
    m_dir_path = dir.string();
    std::vector<std::string> delete_name_list;
    //std::map<std::string, Preset*>::iterator it;
    //for (it = my_presets.begin(); it != my_presets.end(); it++) {
    for (auto it = m_presets.begin(); it != m_presets.end(); it++) {
        Preset* preset = &m_presets[it - m_presets.begin()];
        if (!preset->is_user()) continue;
        preset->file = path_from_name(preset->name);
        if (preset->is_custom_defined()) {
            preset->save(nullptr);
        } else {
            //BBS: only save difference for user preset
            std::string inherits = Preset::inherits(preset->config);
            if (inherits.empty()) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(" can not find inherits for %1% , should not happen")%preset->name;
                // BBS add sync info
                preset->sync_info = "delete";
                need_to_delete_list.push_back(preset->setting_id);
                delete_name_list.push_back(preset->name);
                continue;
            }
            Preset* parent_preset = this->find_preset(inherits, false, true);
            if (!parent_preset) {
                BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(" can not find parent preset for %1% , inherits %2%")%preset->name %inherits;
                continue;
            }
            if (preset->base_id.empty())
                preset->base_id = parent_preset->setting_id;
            preset->save(&(parent_preset->config));
        }
    }
    for (auto delete_name: delete_name_list)
    {
        this->delete_preset(delete_name);
    }
    delete_name_list.clear();
    return;
}
References Slic3r::Preset::base_id, Slic3r::Preset::config, Slic3r::PresetCollection::delete_preset(), error, Slic3r::Preset::file, Slic3r::PresetCollection::find_preset(), Slic3r::Preset::inherits(), Slic3r::Preset::is_custom_defined(), Slic3r::Preset::is_user(), Slic3r::PresetCollection::m_dir_path, Slic3r::PresetCollection::m_presets, Slic3r::Preset::name, Slic3r::PresetCollection::path_from_name(), Slic3r::PresetCollection::preset(), Slic3r::Preset::save(), Slic3r::Preset::setting_id, Slic3r::Preset::sync_info, and Slic3r::PresetCollection::type().
Referenced by Slic3r::PresetBundle::save_user_presets().
saved_is_dirty()
bool Slic3r::PresetCollection::saved_is_dirty () const inline inherited
        { return is_dirty(&this->get_edited_preset(), &m_saved_preset); }
References Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::is_dirty(), and Slic3r::PresetCollection::m_saved_preset.
Referenced by Slic3r::GUI::Tab::saved_preset_is_dirty().
section_name()
std::string Slic3r::PresetCollection::section_name () const inherited
{
    switch (this->type()) {
    case Preset::TYPE_PRINT:        return PRESET_PRINT_NAME;
    case Preset::TYPE_FILAMENT:     return PRESET_FILAMENT_NAME;
    //case Preset::TYPE_SLA_PRINT:    return PRESET_SLA_PRINT_NAME;
    //case Preset::TYPE_SLA_MATERIAL: return PRESET_SLA_MATERIALS_NAME;
    case Preset::TYPE_PRINTER:      return PRESET_PRINTER_NAME;
    default:                        return "invalid";
    }
}
References PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, Slic3r::PresetCollection::type(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, and Slic3r::Preset::TYPE_PRINTER.
select_preset()
Preset & Slic3r::PresetCollection::select_preset (size_t idx) inherited
{
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1% try to select preset %2%")%Preset::get_type_string(m_type) %idx;
    for (Preset &preset : m_presets)
        preset.is_dirty = false;
    if (idx >= m_presets.size())
        idx = first_visible_idx();
    m_idx_selected = idx;
    m_edited_preset = m_presets[idx];
    update_saved_preset_from_current_preset();
    bool default_visible = ! m_default_suppressed || m_idx_selected < m_num_default_presets;
    for (size_t i = 0; i < m_num_default_presets; ++i)
        m_presets[i].is_visible = default_visible;
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1% select success, m_idx_selected %2%, name %3%, is_system %4%, is_default %5%")%Preset::get_type_string(m_type) % m_idx_selected % m_edited_preset.name % m_edited_preset.is_system % m_edited_preset.is_default;
    return m_presets[idx];
}
References Slic3r::PresetCollection::first_visible_idx(), Slic3r::Preset::get_type_string(), Slic3r::Preset::is_default, Slic3r::Preset::is_dirty, Slic3r::Preset::is_system, Slic3r::PresetCollection::m_default_suppressed, Slic3r::PresetCollection::m_edited_preset, Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::Preset::name, Slic3r::PresetCollection::preset(), and Slic3r::PresetCollection::update_saved_preset_from_current_preset().
Referenced by Slic3r::PresetBundle::PresetBundle(), Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::reset(), Slic3r::PresetBundle::reset_project_embedded_presets(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::select_preset_by_name_strict(), and Slic3r::PresetCollection::update_compatible().
select_preset_by_name()
bool Slic3r::PresetCollection::select_preset_by_name (const std::string & name, bool force) inherited
{
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, try to select by name %2%, force %3%")%Preset::get_type_string(m_type) %name_w_suffix %force;
    std::string name = Preset::remove_suffix_modified(name_w_suffix);
    // 1) Try to find the preset by its name.
    auto it = this->find_preset_internal(name);
    size_t idx = 0;
    if (it != m_presets.end() && it->name == name && it->is_visible)
        // Preset found by its name and it is visible.
        idx = it - m_presets.begin();
    else {
        // Find the first visible preset.
        for (size_t i = m_default_suppressed ? m_num_default_presets : 0; i < m_presets.size(); ++ i)
            if (m_presets[i].is_visible) {
                idx = i;
                break;
            }
        // If the first visible preset was not found, return the 0th element, which is the default preset.
    }
    // 2) Select the new preset.
    if (m_idx_selected != idx || force) {
        this->select_preset(idx);
        //BBS: add config related logs
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, select %2%, success")%Preset::get_type_string(m_type) %name_w_suffix;
        return true;
    }
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, select %2%, failed")%Preset::get_type_string(m_type) %name_w_suffix;
    return false;
}
References Slic3r::PresetCollection::find_preset_internal(), Slic3r::Preset::get_type_string(), Slic3r::PresetCollection::m_default_suppressed, Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::PresetCollection::name(), Slic3r::Preset::remove_suffix_modified(), and Slic3r::PresetCollection::select_preset().
Referenced by Slic3r::PresetCollection::load_preset(), Slic3r::PresetBundle::load_selections(), Slic3r::PresetBundle::load_user_presets(), Slic3r::PresetBundle::remove_users_preset(), Slic3r::PresetBundle::reset_project_embedded_presets(), Slic3r::PresetCollection::save_current_preset(), Slic3r::GUI::Tab::select_preset(), Slic3r::PresetCollection::update_after_user_presets_loaded(), and Slic3r::GUI::DiffPresetDialog::update_compatibility().
select_preset_by_name_strict()
bool Slic3r::PresetCollection::select_preset_by_name_strict (const std::string & name) protected inherited
{
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, try to select by name %2%")%Preset::get_type_string(m_type) %name;
    // 1) Try to find the preset by its name.
    auto it = this->find_preset_internal(name);
    size_t idx = (size_t)-1;
    if (it != m_presets.end() && it->name == name && it->is_visible)
        // Preset found by its name.
        idx = it - m_presets.begin();
    // 2) Select the new preset.
    if (idx != (size_t)-1) {
        this->select_preset(idx);
        //BBS: add config related logs
        BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, select %2%, success")%Preset::get_type_string(m_type) %name;
        return true;
    }
    m_idx_selected = idx;
    //BBS: add config related logs
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(": %1%, select %2%, failed")%Preset::get_type_string(m_type) %name;
    return false;
}
References Slic3r::PresetCollection::find_preset_internal(), Slic3r::Preset::get_type_string(), Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::PresetCollection::name(), and Slic3r::PresetCollection::select_preset().
Referenced by Slic3r::PresetBundle::load_selections(), and Slic3r::PresetBundle::update_selections().
set_default_suppressed()
void Slic3r::PresetCollection::set_default_suppressed (bool default_suppressed) inherited
{
    if (m_default_suppressed != default_suppressed) {
        m_default_suppressed = default_suppressed;
        bool default_visible = ! default_suppressed || m_idx_selected < m_num_default_presets;
        for (size_t i = 0; i < m_num_default_presets; ++ i)
            m_presets[i].is_visible = default_visible;
    }
}
References Slic3r::PresetCollection::m_default_suppressed, Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_num_default_presets, and Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::PresetBundle::set_default_suppressed().
set_sync_func()
void Slic3r::PresetCollection::set_sync_func (SyncFunc func) inline inherited
{ sync_func = func; }
References Slic3r::PresetCollection::sync_func.
set_sync_info_and_save()
void Slic3r::PresetCollection::set_sync_info_and_save (std::string name, std::string setting_id, std::string syncinfo) inherited
{
    lock();
    for (auto it = m_presets.begin(); it != m_presets.end(); it++) {
        Preset* preset = &m_presets[it - m_presets.begin()];
        if (preset->name == name) {
            if (syncinfo.empty())
                preset->sync_info.clear();
            else
                preset->sync_info = syncinfo;
            preset->setting_id = setting_id;
            preset->save_info();
            break;
        }
    }
    unlock();
}
References Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_presets, Slic3r::Preset::name, Slic3r::PresetCollection::name(), Slic3r::PresetCollection::preset(), Slic3r::Preset::save_info(), Slic3r::Preset::setting_id, Slic3r::Preset::sync_info, and Slic3r::PresetCollection::unlock().
Referenced by Slic3r::GUI::Tab::select_preset(), and Slic3r::GUI::GUI_App::sync_preset().
size()
size_t Slic3r::PresetCollection::size () const inline inherited
{ return m_presets.size(); }
References Slic3r::PresetCollection::m_presets.
Referenced by Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::GUI::TabPresetComboBox::update(), Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments(), and Slic3r::PresetBundle::update_multi_material_filament_presets().
system_preset_names()
std::vector< std::string > Slic3r::PresetCollection::system_preset_names () const inherited
{
    size_t num = 0;
    for (const Preset &preset : m_presets)
        if (preset.is_system)
            ++ num;
    std::vector<std::string> out;
    out.reserve(num);
    for (const Preset &preset : m_presets)
        if (preset.is_system) {
            out.emplace_back(preset.name);
            out.insert(out.end(), preset.renamed_from.begin(), preset.renamed_from.end());
        }
    std::sort(out.begin(), out.end());
    return out;
}
References Slic3r::Preset::is_system, Slic3r::PresetCollection::m_presets, Slic3r::Preset::name, out, Slic3r::PresetCollection::preset(), and Slic3r::Preset::renamed_from.
type()
Preset::Type Slic3r::PresetCollection::type () const inline inherited
{ return m_type; }
References Slic3r::PresetCollection::m_type.
Referenced by Slic3r::PresetCollection::add_default_preset(), Slic3r::GUI::UnsavedChangesDialog::build(), Slic3r::GUI::GUI_App::get_selected_presets(), Slic3r::PresetBundle::import_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::PresetCollection::name(), Slic3r::PresetCollection::save_user_presets(), Slic3r::PresetCollection::section_name(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::UnsavedChangesDialog::update(), and Slic3r::PresetCollection::update_user_presets_directory().
unlock()
void Slic3r::PresetCollection::unlock () inline inherited
{ m_mutex.unlock(); }
References Slic3r::PresetCollection::m_mutex.
Referenced by Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::delete_preset(), Slic3r::PresetCollection::get_project_embedded_presets(), Slic3r::PresetCollection::get_user_presets(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::reset(), Slic3r::PresetCollection::reset_project_embedded_presets(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::set_sync_info_and_save(), and Slic3r::PresetCollection::update_after_user_presets_loaded().
update_after_user_presets_loaded()
void Slic3r::PresetCollection::update_after_user_presets_loaded () inherited
{
    lock();
    std::string     selected_name = get_selected_preset_name();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", before sort, type %1%, selected_idx %2%, selected_name %3%") %m_type %m_idx_selected %selected_name;
    std::sort(m_presets.begin() + m_num_default_presets, m_presets.end());
    this->select_preset_by_name(selected_name, false);
    unlock();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", after sort, type %1%, selected_idx %2%") %m_type %m_idx_selected;
    return;
}
References Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::PresetCollection::lock(), Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::m_type, Slic3r::PresetCollection::select_preset_by_name(), and Slic3r::PresetCollection::unlock().
update_compatible() [1/2]
void Slic3r::PresetCollection::update_compatible (const PresetWithVendorProfile & active_printer, const PresetWithVendorProfile * active_print, PresetSelectCompatibleType select_other_if_incompatible) inline inherited
        { this->update_compatible(active_printer, active_print, select_other_if_incompatible, [](const Preset&) -> int { return 0; }); }
References Slic3r::PresetCollection::update_compatible().
update_compatible() [2/2]
template<typename PreferedCondition > void Slic3r::PresetCollection::update_compatible (const PresetWithVendorProfile & active_printer, const PresetWithVendorProfile * active_print, PresetSelectCompatibleType select_other_if_incompatible, PreferedCondition prefered_condition) inline inherited
    {
        if (this->update_compatible_internal(active_printer, active_print, select_other_if_incompatible) == (size_t)-1)
            // Find some other compatible preset, or the "-- default --" preset.
            this->select_preset(this->first_compatible_idx(prefered_condition));
    }
References Slic3r::PresetCollection::first_compatible_idx(), Slic3r::PresetCollection::select_preset(), and Slic3r::PresetCollection::update_compatible_internal().
Referenced by Slic3r::PresetCollection::update_compatible(), and Slic3r::PresetBundle::update_compatible().
update_compatible_internal()
size_t Slic3r::PresetCollection::update_compatible_internal (const PresetWithVendorProfile & active_printer, const PresetWithVendorProfile * active_print, PresetSelectCompatibleType unselect_if_incompatible) private inherited
{
    DynamicPrintConfig config;
    config.set_key_value("printer_preset", new ConfigOptionString(active_printer.preset.name));
    const ConfigOption *opt = active_printer.preset.config.option("nozzle_diameter");
    if (opt)
        config.set_key_value("num_extruders", new ConfigOptionInt((int)static_cast<const ConfigOptionFloats*>(opt)->values.size()));
    bool some_compatible = false;
    for (size_t idx_preset = m_num_default_presets; idx_preset < m_presets.size(); ++ idx_preset) {
        bool    selected        = idx_preset == m_idx_selected;
        Preset &preset_selected = m_presets[idx_preset];
        Preset &preset_edited   = selected ? m_edited_preset : preset_selected;
        const PresetWithVendorProfile this_preset_with_vendor_profile = this->get_preset_with_vendor_profile(preset_edited);
        bool    was_compatible  = preset_edited.is_compatible;
        preset_edited.is_compatible = is_compatible_with_printer(this_preset_with_vendor_profile, active_printer, &config);
        some_compatible |= preset_edited.is_compatible;
      if (active_print != nullptr)
          preset_edited.is_compatible &= is_compatible_with_print(this_preset_with_vendor_profile, *active_print, active_printer);
        if (! preset_edited.is_compatible && selected &&
          (unselect_if_incompatible == PresetSelectCompatibleType::Always || (unselect_if_incompatible == PresetSelectCompatibleType::OnlyIfWasCompatible && was_compatible)))
            m_idx_selected = size_t(-1);
        if (selected)
            preset_selected.is_compatible = preset_edited.is_compatible;
    }
    // Update visibility of the default profiles here if the defaults are suppressed, the current profile is not compatible and we don't want to select another compatible profile.
    if (m_idx_selected >= m_num_default_presets && m_default_suppressed)
      for (size_t i = 0; i < m_num_default_presets; ++ i)
          m_presets[i].is_visible = ! some_compatible;
    return m_idx_selected;
}
References Slic3r::Always, Slic3r::Preset::config, Slic3r::PresetCollection::get_preset_with_vendor_profile(), Slic3r::Preset::is_compatible, Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::PresetCollection::m_default_suppressed, Slic3r::PresetCollection::m_edited_preset, Slic3r::PresetCollection::m_idx_selected, Slic3r::PresetCollection::m_num_default_presets, Slic3r::PresetCollection::m_presets, Slic3r::Preset::name, Slic3r::OnlyIfWasCompatible, Slic3r::ConfigBase::option(), Slic3r::PresetWithVendorProfile::preset, Slic3r::DynamicConfig::set_key_value(), and Slic3r::ConfigOptionVector< T >::size().
Referenced by Slic3r::PresetCollection::update_compatible().
update_dirty()
bool Slic3r::PresetCollection::update_dirty () inherited
{
    bool was_dirty = this->get_selected_preset().is_dirty;
    bool is_dirty  = current_is_dirty();
    this->get_selected_preset().is_dirty = is_dirty;
    this->get_edited_preset().is_dirty = is_dirty;
    return was_dirty != is_dirty;
}
References Slic3r::PresetCollection::current_is_dirty(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::Preset::is_dirty, and Slic3r::PresetCollection::is_dirty().
Referenced by Slic3r::PresetCollection::load_external_preset(), and Slic3r::GUI::TabPresetComboBox::update_dirty().
update_map_alias_to_profile_name()
void Slic3r::PresetCollection::update_map_alias_to_profile_name () protected inherited
{
  m_map_alias_to_profile_name.clear();
  for (const Preset &preset : m_presets)
    m_map_alias_to_profile_name.emplace_back(preset.alias, preset.name);
  std::sort(m_map_alias_to_profile_name.begin(), m_map_alias_to_profile_name.end(), [](auto &l, auto &r) { return l.first < r.first; });
}
References Slic3r::Preset::alias, Slic3r::PresetCollection::m_map_alias_to_profile_name, Slic3r::PresetCollection::m_presets, Slic3r::Preset::name, and Slic3r::PresetCollection::preset().
Referenced by Slic3r::PresetBundle::update_system_maps().
update_map_system_profile_renamed()
void Slic3r::PresetCollection::update_map_system_profile_renamed () protected inherited
{
  m_map_system_profile_renamed.clear();
  for (Preset &preset : m_presets)
    for (const std::string &renamed_from : preset.renamed_from) {
            const auto [it, success] = m_map_system_profile_renamed.insert(std::pair<std::string, std::string>(renamed_from, preset.name));
      if (! success)
                BOOST_LOG_TRIVIAL(error) << boost::format("Preset name \"%1%\" was marked as renamed from \"%2%\", though preset name \"%3%\" was marked as renamed from \"%2%\" as well.") % preset.name % renamed_from % it->second;
    }
}
References error, Slic3r::PresetCollection::m_map_system_profile_renamed, Slic3r::PresetCollection::m_presets, Slic3r::Preset::name, Slic3r::PresetCollection::preset(), and Slic3r::Preset::renamed_from.
Referenced by Slic3r::PresetBundle::update_system_maps().
update_saved_preset_from_current_preset()
void Slic3r::PresetCollection::update_saved_preset_from_current_preset () inline inherited
{ m_saved_preset = m_edited_preset; }
References Slic3r::PresetCollection::m_edited_preset, and Slic3r::PresetCollection::m_saved_preset.
Referenced by Slic3r::PresetCollection::PresetCollection(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::select_preset(), and Slic3r::GUI::Tab::update_saved_preset_from_current_preset().
update_user_presets_directory()
void Slic3r::PresetCollection::update_user_presets_directory (const std::string & dir_path, const std::string & type) inherited
{
    boost::filesystem::path dir = boost::filesystem::absolute(boost::filesystem::path(dir_path) / type).make_preferred();
    if (!fs::exists(dir))
        fs::create_directory(dir);
    m_dir_path = dir.string();
}
References Slic3r::PresetCollection::m_dir_path, and Slic3r::PresetCollection::type().
Referenced by Slic3r::PresetBundle::update_user_presets_directory().
update_vendor_ptrs_after_copy()
void Slic3r::PresetCollection::update_vendor_ptrs_after_copy (const VendorMap & vendors) protected inherited
{
    for (Preset &preset : m_presets)
        if (preset.vendor != nullptr) {
            assert(! preset.is_default && ! preset.is_external);
            // Re-assign a pointer to the vendor structure in the new PresetBundle.
            auto it = new_vendors.find(preset.vendor->id);
            assert(it != new_vendors.end());
            preset.vendor = &it->second;
        }
}
References Slic3r::VendorProfile::id, Slic3r::Preset::is_default, Slic3r::Preset::is_external, Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::preset(), and Slic3r::Preset::vendor.
Referenced by Slic3r::PresetBundle::operator=().
validate_printers()
bool Slic3r::PresetCollection::validate_printers (const std::string & name, DynamicPrintConfig & config, std::string & inherit) inherited
{
    std::string&                 original_name = config.opt_string("printer_settings_id", true);
    std::deque<Preset>::iterator it       = this->find_preset_internal(original_name);
    bool                         found    = it != m_presets.end() && it->name == original_name && (it->is_system || it->is_default);
    if (!found) {
        it = this->find_preset_renamed(original_name);
        found = it != m_presets.end() && (it->is_system || it->is_default);
    }
    if (!found) {
        if (!inherit.empty()) {
            it    = this->find_preset_internal(inherit);
            found = it != m_presets.end() && it->name == inherit && (it->is_system || it->is_default);
        }
        else {
            //inherit is null , should not happen , just consider it as valid
            found = false;
            BOOST_LOG_TRIVIAL(warning) << boost::format(": name %1%, printer_settings %2%, no inherit, set to not found")%name %original_name;
        }
    }
    BOOST_LOG_TRIVIAL(warning) << boost::format(": name %1%, printer_settings %2%, inherit %3%, found result %4%")%name %original_name % inherit % found;
    return found;
}
References Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::m_presets, Slic3r::PresetCollection::name(), and Slic3r::DynamicConfig::opt_string().
Referenced by Slic3r::PresetBundle::validate_printers().
Friends And Related Symbol Documentation
PresetBundle
friend class PresetBundle friend
Member Data Documentation
m_default_suppressed
bool Slic3r::PresetCollection::m_default_suppressed = true private inherited
Referenced by Slic3r::PresetCollection::first_compatible_idx(), Slic3r::PresetCollection::first_visible_idx(), Slic3r::PresetCollection::is_default_suppressed(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::set_default_suppressed(), and Slic3r::PresetCollection::update_compatible_internal().
m_dir_path
std::string Slic3r::PresetCollection::m_dir_path private inherited
Referenced by Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::path_from_name(), Slic3r::PresetCollection::save_user_presets(), and Slic3r::PresetCollection::update_user_presets_directory().
m_edited_preset
Preset Slic3r::PresetCollection::m_edited_preset private inherited
Referenced by Slic3r::PresetCollection::PresetCollection(), Slic3r::PresetCollection::discard_current_changes(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::preset(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::update_compatible_internal(), and Slic3r::PresetCollection::update_saved_preset_from_current_preset().
m_idx_selected
size_t Slic3r::PresetCollection::m_idx_selected private inherited
Referenced by Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::discard_current_changes(), Slic3r::PresetCollection::get_idx_selected(), Slic3r::PresetCollection::get_preset_name_by_alias(), Slic3r::PresetCollection::get_selected_idx(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::preset(), Slic3r::PresetCollection::reset_project_embedded_presets(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::select_preset_by_name_strict(), Slic3r::PresetCollection::set_default_suppressed(), Slic3r::PresetCollection::update_after_user_presets_loaded(), and Slic3r::PresetCollection::update_compatible_internal().
m_map_alias_to_profile_name
std::vector<std::pair<std::string, std::string> > Slic3r::PresetCollection::m_map_alias_to_profile_name private inherited
Referenced by Slic3r::PresetCollection::get_preset_name_by_alias(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::reset(), and Slic3r::PresetCollection::update_map_alias_to_profile_name().
m_map_system_profile_renamed
std::map<std::string, std::string> Slic3r::PresetCollection::m_map_system_profile_renamed private inherited
Referenced by Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::get_preset_name_renamed(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::reset(), and Slic3r::PresetCollection::update_map_system_profile_renamed().
m_mutex
std::mutex Slic3r::PresetCollection::m_mutex private inherited
Referenced by Slic3r::PresetCollection::lock(), and Slic3r::PresetCollection::unlock().
m_num_default_presets
size_t Slic3r::PresetCollection::m_num_default_presets = 0 private inherited
Referenced by Slic3r::PresetCollection::add_default_preset(), Slic3r::PresetCollection::begin(), Slic3r::PresetCollection::begin(), Slic3r::PresetCollection::cbegin(), Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::first_compatible_idx(), Slic3r::PresetCollection::first_visible_idx(), Slic3r::PresetCollection::has_defaults_only(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::merge_presets(), Slic3r::PresetCollection::num_default_presets(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::reset(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::set_default_suppressed(), Slic3r::PresetCollection::update_after_user_presets_loaded(), and Slic3r::PresetCollection::update_compatible_internal().
m_presets
std::deque<Preset> Slic3r::PresetCollection::m_presets private inherited
Referenced by Slic3r::PresetCollection::PresetCollection(), Slic3r::PresetCollection::add_default_preset(), Slic3r::PresetCollection::begin(), Slic3r::PresetCollection::begin(), Slic3r::PresetCollection::cbegin(), Slic3r::PresetCollection::cend(), Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::delete_preset(), Slic3r::PresetCollection::discard_current_changes(), Slic3r::PresetCollection::end(), Slic3r::PresetCollection::end(), Slic3r::PresetCollection::erase(), Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::find_preset_internal(), Slic3r::PresetCollection::find_preset_renamed(), Slic3r::PresetCollection::first_compatible_idx(), Slic3r::PresetCollection::first_visible_idx(), Slic3r::PresetCollection::get_preset_name_by_alias(), Slic3r::PresetCollection::get_preset_parent(), Slic3r::PresetCollection::get_presets(), Slic3r::PresetCollection::get_project_embedded_presets(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::get_selected_preset_name(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::PresetCollection::get_user_presets(), Slic3r::PresetCollection::has_defaults_only(), Slic3r::PresetCollection::lbegin(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::merge_presets(), Slic3r::PresetCollection::num_visible(), Slic3r::PresetCollection::operator()(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::preset(), Slic3r::PresetCollection::reset(), Slic3r::PresetCollection::reset_project_embedded_presets(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::save_user_presets(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::select_preset_by_name_strict(), Slic3r::PresetBundle::set_calibrate_printer(), Slic3r::PresetCollection::set_default_suppressed(), Slic3r::PresetCollection::set_sync_info_and_save(), Slic3r::PresetCollection::size(), Slic3r::PresetCollection::system_preset_names(), Slic3r::PresetCollection::update_after_user_presets_loaded(), Slic3r::PresetCollection::update_compatible_internal(), Slic3r::PresetCollection::update_map_alias_to_profile_name(), Slic3r::PresetCollection::update_map_system_profile_renamed(), Slic3r::PresetCollection::update_vendor_ptrs_after_copy(), and Slic3r::PresetCollection::validate_printers().
m_saved_preset
Preset Slic3r::PresetCollection::m_saved_preset private inherited
Referenced by Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::saved_is_dirty(), and Slic3r::PresetCollection::update_saved_preset_from_current_preset().
m_type
Preset::Type Slic3r::PresetCollection::m_type private inherited
Referenced by Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::first_visible_idx(), Slic3r::PresetCollection::get_project_embedded_presets(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::PresetCollection::load_external_preset(), Slic3r::PresetCollection::load_preset(), Slic3r::PresetCollection::load_presets(), Slic3r::PresetCollection::load_project_embedded_presets(), Slic3r::PresetCollection::load_user_preset(), Slic3r::PresetCollection::merge_presets(), Slic3r::PresetCollection::operator=(), Slic3r::PresetCollection::reset_project_embedded_presets(), Slic3r::PresetCollection::save_current_preset(), Slic3r::PresetCollection::select_preset(), Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PresetCollection::select_preset_by_name_strict(), Slic3r::PresetCollection::type(), and Slic3r::PresetCollection::update_after_user_presets_loaded().
sync_func
SyncFunc Slic3r::PresetCollection::sync_func { nullptr } inherited
Referenced by Slic3r::PresetCollection::set_sync_func().
The documentation for this class was generated from the following files:
src/libslic3r/Preset.hpp
src/libslic3r/Preset.cpp