OrcaSlicer: Slic3r::GUI::ConfigWizardIndex Class Reference
Slic3r::GUI::ConfigWizardIndex Class Reference
#include <src/slic3r/GUI/ConfigWizard_private.hpp>
Classes
struct Item
Public Member Functions
ConfigWizardIndex (wxWindow *parent)
void add_page (ConfigWizardPage *page)
void add_label (wxString label, unsigned indent=0)
size_t active_item () const
ConfigWizardPage * active_page () const
bool active_is_last () const
void go_prev ()
void go_next ()
void go_to (size_t i)
void go_to (const ConfigWizardPage *page)
void clear ()
void msw_rescale ()
int em () const
Static Public Attributes
static const size_t NO_ITEM = size_t(-1)
Private Member Functions
int item_height () const
void on_paint (wxPaintEvent &evt)
void on_mouse_move (wxMouseEvent &evt)
Private Attributes
int em_w
int em_h
ScalableBitmap bg
ScalableBitmap bullet_black
ScalableBitmap bullet_blue
ScalableBitmap bullet_white
std::vector< Item > items
size_t item_active
ssize_t item_hover
size_t last_page
Detailed Description
Constructor & Destructor Documentation
ConfigWizardIndex()
Slic3r::GUI::ConfigWizardIndex::ConfigWizardIndex (wxWindow * parent)
    : wxPanel(parent)
    , bg(ScalableBitmap(parent, "OrcaSlicer_192px_transparent.png", 192))
    , bullet_black(ScalableBitmap(parent, "bullet_black.png"))
    , bullet_blue(ScalableBitmap(parent, "bullet_blue.png"))
    , bullet_white(ScalableBitmap(parent, "bullet_white.png"))
    , item_active(NO_ITEM)
    , item_hover(NO_ITEM)
    , last_page((size_t)-1)
{
#ifndef __WXOSX__
    SetDoubleBuffered(true);// SetDoubleBuffered exists on Win and Linux/GTK, but is missing on OSX
#endif //__WXOSX__
    SetMinSize(bg.bmp().GetSize());
    const wxSize size = GetTextExtent("m");
    em_w = size.x;
    em_h = size.y;
    Bind(wxEVT_PAINT, &ConfigWizardIndex::on_paint, this);
    Bind(wxEVT_SIZE, [this](wxEvent& e) { e.Skip(); Refresh(); });
    Bind(wxEVT_MOTION, &ConfigWizardIndex::on_mouse_move, this);
    Bind(wxEVT_LEAVE_WINDOW, [this](wxMouseEvent &evt) {
        if (item_hover != -1) {
            item_hover = -1;
            Refresh();
        }
        evt.Skip();
    });
    Bind(wxEVT_LEFT_UP, [this](wxMouseEvent &evt) {
        if (item_hover >= 0) { go_to(item_hover); }
    });
}
References em_h, em_w, go_to(), item_hover, on_mouse_move(), on_paint(), size, and Slic3r::GUI::wxMouseEvent.
Member Function Documentation
active_is_last()
bool Slic3r::GUI::ConfigWizardIndex::active_is_last () const inline
{ return item_active < items.size() && item_active == last_page; }
References item_active, items, and last_page.
active_item()
size_t Slic3r::GUI::ConfigWizardIndex::active_item () const inline
{ return item_active; }
References item_active.
active_page()
ConfigWizardPage * Slic3r::GUI::ConfigWizardIndex::active_page () const
{
    if (item_active >= items.size()) { return nullptr; }
    return items[item_active].page;
}
References item_active, and items.
Referenced by clear(), go_to(), and Slic3r::GUI::ConfigWizard::priv::load_pages().
add_label()
void Slic3r::GUI::ConfigWizardIndex::add_label (wxString label, unsigned indent = 0)
{
    items.emplace_back(Item { std::move(label), indent, nullptr });
    Refresh();
}
References items.
add_page()
void Slic3r::GUI::ConfigWizardIndex::add_page (ConfigWizardPage * page)
{
    if (!page)
        return;
    last_page = items.size();
    items.emplace_back(Item { page->shortname, page->indent, page });
    Refresh();
}
References Slic3r::GUI::ConfigWizardPage::indent, items, last_page, and Slic3r::GUI::ConfigWizardPage::shortname.
Referenced by Slic3r::GUI::ConfigWizard::priv::load_pages().
clear()
void Slic3r::GUI::ConfigWizardIndex::clear ()
{
    auto *former_active = active_page();
    if (former_active != nullptr) { former_active->Hide(); }
    items.clear();
    item_active = NO_ITEM;
}
References active_page(), item_active, items, and NO_ITEM.
Referenced by Slic3r::GUI::ConfigWizard::priv::load_pages().
em()
int Slic3r::GUI::ConfigWizardIndex::em () const inline
{ return em_w; }
References em_w.
go_next()
void Slic3r::GUI::ConfigWizardIndex::go_next ()
{
    // Search for a next item that is a page (not a label, ie. page != nullptr)
    if (item_active == NO_ITEM) { return; }
    for (size_t i = item_active + 1; i < items.size(); i++) {
        if (items[i].page != nullptr) {
            go_to(i);
            return;
        }
    }
}
References go_to(), item_active, items, and NO_ITEM.
go_prev()
void Slic3r::GUI::ConfigWizardIndex::go_prev ()
{
    // Search for a preceiding item that is a page (not a label, ie. page != nullptr)
    if (item_active == NO_ITEM) { return; }
    for (size_t i = item_active; i > 0; i--) {
        if (items[i - 1].page != nullptr) {
            go_to(i - 1);
            return;
        }
    }
}
References go_to(), item_active, items, and NO_ITEM.
go_to() [1/2]
void Slic3r::GUI::ConfigWizardIndex::go_to (const ConfigWizardPage * page)
{
    if (page == nullptr) { return; }
    for (size_t i = 0; i < items.size(); i++) {
        if (items[i].page == page) {
            go_to(i);
            return;
        }
    }
}
References go_to(), and items.
go_to() [2/2]
void Slic3r::GUI::ConfigWizardIndex::go_to (size_t i)
{
    if (i != item_active
        && i < items.size()
        && items[i].page != nullptr) {
        auto *new_active = items[i].page;
        auto *former_active = active_page();
        if (former_active != nullptr) {
            former_active->Hide();
        }
        item_active = i;
        new_active->Show();
        wxCommandEvent evt(EVT_INDEX_PAGE, GetId());
        AddPendingEvent(evt);
        Refresh();
        new_active->on_activate();
    }
}
References active_page(), item_active, and items.
Referenced by ConfigWizardIndex(), go_next(), go_prev(), go_to(), and Slic3r::GUI::ConfigWizard::priv::load_pages().
item_height()
int Slic3r::GUI::ConfigWizardIndex::item_height () const inline private
{ return std::max(bullet_black.bmp().GetSize().GetHeight(), em_w) + em_w; }
References ScalableBitmap::bmp(), bullet_black, and em_w.
Referenced by on_mouse_move(), and on_paint().
msw_rescale()
void Slic3r::GUI::ConfigWizardIndex::msw_rescale ()
{
    const wxSize size = GetTextExtent("m");
    em_w = size.x;
    em_h = size.y;
    bg.msw_rescale();
    SetMinSize(bg.bmp().GetSize());
    bullet_black.msw_rescale();
    bullet_blue.msw_rescale();
    bullet_white.msw_rescale();
    Refresh();
}
References bullet_black, bullet_blue, bullet_white, em_h, em_w, ScalableBitmap::msw_rescale(), and size.
on_mouse_move()
void Slic3r::GUI::ConfigWizardIndex::on_mouse_move (wxMouseEvent & evt) private
{
    const wxClientDC dc(this);
    const wxPoint pos = evt.GetLogicalPosition(dc);
    const ssize_t item_hover_new = pos.y / item_height();
    if (item_hover_new < ssize_t(items.size()) && item_hover_new != item_hover) {
        item_hover = item_hover_new;
        Refresh();
    }
    evt.Skip();
}
References item_height(), item_hover, and items.
Referenced by ConfigWizardIndex().
on_paint()
void Slic3r::GUI::ConfigWizardIndex::on_paint (wxPaintEvent & evt) private
{
    const auto size = GetClientSize();
    if (size.GetHeight() == 0 || size.GetWidth() == 0) { return; }
    wxPaintDC dc(this);
    const auto bullet_w = bullet_black.bmp().GetSize().GetWidth();
    const auto bullet_h = bullet_black.bmp().GetSize().GetHeight();
    const int yoff_icon = bullet_h < em_h ? (em_h - bullet_h) / 2 : 0;
    const int yoff_text = bullet_h > em_h ? (bullet_h - em_h) / 2 : 0;
    const int yinc = item_height();
    int index_width = 0;
    unsigned y = 0;
    for (size_t i = 0; i < items.size(); i++) {
        const Item& item = items[i];
        unsigned x = em_w/2 + item.indent * em_w;
        if (i == item_active || (item_hover >= 0 && i == (size_t)item_hover)) {
            dc.DrawBitmap(bullet_blue.bmp(), x, y + yoff_icon, false);
        }
        else if (i < item_active)  { dc.DrawBitmap(bullet_black.bmp(), x, y + yoff_icon, false); }
        else if (i > item_active)  { dc.DrawBitmap(bullet_white.bmp(), x, y + yoff_icon, false); }
        x += + bullet_w + em_w/2;
        const auto text_size = dc.GetTextExtent(item.label);
        dc.SetTextForeground(wxGetApp().get_label_clr_default());
        dc.DrawText(item.label, x, y + yoff_text);
        y += yinc;
        index_width = std::max(index_width, (int)x + text_size.x);
    }
    //draw logo
    if (int y = size.y - bg.GetBmpHeight(); y>=0) {
        dc.DrawBitmap(bg.bmp(), 0, y, false);
        index_width = std::max(index_width, bg.GetBmpWidth() + em_w / 2);
    }
    if (GetMinSize().x < index_width) {
        CallAfter([this, index_width]() {
            SetMinSize(wxSize(index_width, GetMinSize().y));
            Refresh();
        });
    }
}
References ScalableBitmap::bmp(), bullet_black, bullet_blue, bullet_white, em_h, em_w, Slic3r::GUI::ConfigWizardIndex::Item::indent, item_active, item_height(), item_hover, items, Slic3r::GUI::ConfigWizardIndex::Item::label, and size.
Referenced by ConfigWizardIndex().
Member Data Documentation
bg
ScalableBitmap Slic3r::GUI::ConfigWizardIndex::bg private
bullet_black
ScalableBitmap Slic3r::GUI::ConfigWizardIndex::bullet_black private
Referenced by item_height(), msw_rescale(), and on_paint().
bullet_blue
ScalableBitmap Slic3r::GUI::ConfigWizardIndex::bullet_blue private
Referenced by msw_rescale(), and on_paint().
bullet_white
ScalableBitmap Slic3r::GUI::ConfigWizardIndex::bullet_white private
Referenced by msw_rescale(), and on_paint().
em_h
int Slic3r::GUI::ConfigWizardIndex::em_h private
Referenced by ConfigWizardIndex(), msw_rescale(), and on_paint().
em_w
int Slic3r::GUI::ConfigWizardIndex::em_w private
Referenced by ConfigWizardIndex(), em(), item_height(), msw_rescale(), and on_paint().
item_active
size_t Slic3r::GUI::ConfigWizardIndex::item_active private
Referenced by active_is_last(), active_item(), active_page(), clear(), go_next(), go_prev(), go_to(), and on_paint().
item_hover
ssize_t Slic3r::GUI::ConfigWizardIndex::item_hover private
Referenced by ConfigWizardIndex(), on_mouse_move(), and on_paint().
items
std::vector<Item> Slic3r::GUI::ConfigWizardIndex::items private
Referenced by active_is_last(), active_page(), add_label(), add_page(), clear(), go_next(), go_prev(), go_to(), go_to(), on_mouse_move(), and on_paint().
last_page
size_t Slic3r::GUI::ConfigWizardIndex::last_page private
Referenced by active_is_last(), and add_page().
NO_ITEM
const size_t Slic3r::GUI::ConfigWizardIndex::NO_ITEM = size_t(-1) static
Referenced by clear(), go_next(), and go_prev().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ConfigWizard_private.hpp
src/slic3r/GUI/ConfigWizard.cpp