OrcaSlicer: orgQhull::RoadLogEvent Struct Reference
orgQhull::RoadLogEvent Struct Reference
#include <src/qhull/src/libqhullcpp/RoadLogEvent.h>
Public Member Functions
Constructors
RoadLogEvent ()
RoadLogEvent (const char *fmt)
RoadLogEvent (const char *fmt, int d)
RoadLogEvent (const char *fmt, int d, int d2)
RoadLogEvent (const char *fmt, int d, int d2, float f)
RoadLogEvent (const char *fmt, int d, int d2, float f, const char *s)
RoadLogEvent (const char *fmt, int d, int d2, float f, const void *x)
RoadLogEvent (const char *fmt, int d, int d2, float f, int i)
RoadLogEvent (const char *fmt, int d, int d2, float f, long long i)
RoadLogEvent (const char *fmt, int d, int d2, float f, double g)
~RoadLogEvent ()
GetSet
Default copy constructor and assignment
bool isValid () const
int int1 () const
int int2 () const
float float1 () const
const char * format () const
const char * cstr1 () const
const void * void1 () const
long long int64 () const
double double1 () const
Conversion
std::string toString (const char *tag, int code) const
Public Attributes
Fields
const char * format_string
int int_1
Format string (a literal with format codes, for logging)
int int_2
Integer argument (d, for logging)
float float_1
Integer argument (d, for logging)
union {
const char * cstr_1
One additional argument (for logging)
const void * void_1
Cstr argument (s) – type checked at construct-time.
long long int64_1
Void* argument (x) – Use upper-case codes for object types.
double double_1
signed int64 (i). Ambiguous if unsigned is also defined.
};
Float argument (f, for logging)
Static Private Member Functions
Class helpers
static bool firstExtraCode (std::ostream &os, char c, char *extraCode)
True if this char is the first extra code.
Detailed Description
Constructor & Destructor Documentation
RoadLogEvent() [1/10]
orgQhull::RoadLogEvent::RoadLogEvent () inline
: format_string(0), int_1(0), int_2(0), float_1(0), int64_1(0) {};
RoadLogEvent() [2/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt) inline explicit
: format_string(fmt), int_1(0), int_2(0), float_1(0), int64_1(0) {};
RoadLogEvent() [3/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt, int d) inline
: format_string(fmt), int_1(d), int_2(0), float_1(0), int64_1(0) {};
RoadLogEvent() [4/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt, int d, int d2) inline
: format_string(fmt), int_1(d), int_2(d2), float_1(0), int64_1(0) {};
RoadLogEvent() [5/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt, int d, int d2, float f) inline
: format_string(fmt), int_1(d), int_2(d2), float_1(f), int64_1(0) {};
RoadLogEvent() [6/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt, int d, int d2, float f, const char * s) inline
: format_string(fmt), int_1(d), int_2(d2), float_1(f), cstr_1(s) {};
RoadLogEvent() [7/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt, int d, int d2, float f, const void * x) inline
: format_string(fmt), int_1(d), int_2(d2), float_1(f), void_1(x) {};
RoadLogEvent() [8/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt, int d, int d2, float f, int i) inline
: format_string(fmt), int_1(d), int_2(d2), float_1(f), int64_1(i) {};
RoadLogEvent() [9/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt, int d, int d2, float f, long long i) inline
: format_string(fmt), int_1(d), int_2(d2), float_1(f), int64_1(i) {};
RoadLogEvent() [10/10]
orgQhull::RoadLogEvent::RoadLogEvent (const char * fmt, int d, int d2, float f, double g) inline
: format_string(fmt), int_1(d), int_2(d2), float_1(f), double_1(g) {};
~RoadLogEvent()
orgQhull::RoadLogEvent::~RoadLogEvent () inline
{};
Member Function Documentation
cstr1()
const char * orgQhull::RoadLogEvent::cstr1 () const inline
{ return cstr_1; };
double1()
double orgQhull::RoadLogEvent::double1 () const inline
{ return double_1; };
firstExtraCode()
bool orgQhull::RoadLogEvent::firstExtraCode (std::ostream & os, char c, char * extraCode) static private
True if this char is the first extra code.
{
    if(*extraCode){
        os << " ERROR_%" << *extraCode << "_and_%" << c << "_in_format ";
        return false;
    }
    *extraCode= c;
    return true;
}//firstExtraCode
Referenced by toString().
float1()
float orgQhull::RoadLogEvent::float1 () const inline
{ return float_1; };
References float_1.
format()
const char * orgQhull::RoadLogEvent::format () const inline
{ return format_string; };
References format_string.
int1()
int orgQhull::RoadLogEvent::int1 () const inline
{ return int_1; };
References int_1.
Referenced by orgQhull::RboxPoints_test::t_error().
int2()
int orgQhull::RoadLogEvent::int2 () const inline
{ return int_2; };
References int_2.
int64()
long long orgQhull::RoadLogEvent::int64 () const inline
{ return int64_1; };
isValid()
bool orgQhull::RoadLogEvent::isValid () const inline
{ return format_string!=0; }
References format_string.
Referenced by orgQhull::RoadError::isValid().
toString()
string orgQhull::RoadLogEvent::toString (const char * tag, int code) const
{
    ostringstream os;
    if(tag && code){
        os << tag << code;
        if(format_string){
            os << " ";
        }
    }
    if(!format_string){
        return os.str();
    }
    const char *s= format_string;
    int dCount= 0;  // Count of %d
    int fCount= 0;  // Count of %f
    char extraCode= '\0';
    while(*s){
        if(*s!='%'){
            os << *s++;
        }else{
            char c= *++s;
            s++;
            switch(c){
            case 'd':
                if(++dCount>2){
                    os << " ERROR_three_%d_in_format ";
                }else if(dCount==2){
                    os << int_2;
                }else{
                    os << int_1;
                }
                break;
            case 'e':
                if(firstExtraCode(os, c, &extraCode)){
                    os << double_1;
                }
                break;
            case 'f':
                if(++fCount>1){
                    os << " ERROR_two_%f_in_format ";
                }else{
                    os << float_1;
                }
                break;
            case 'i':
                if(firstExtraCode(os, c, &extraCode)){
                    os << int64_1;
                }
                break;
            case 's':
                if(firstExtraCode(os, c, &extraCode)){
                    os << cstr_1;
                }
                break;
            case 'u':
                if(firstExtraCode(os, c, &extraCode)){
                    os << "0x" << std::hex << int64_1 << std::dec;
                }
                break;
            case 'x':
                if(firstExtraCode(os, c, &extraCode)){
                    os << void_1;
                }
                break;
            case '%':
                os << c;
                break;
            default:
                os << " ERROR_%" << c << "_not_defined_in_format";
                break;
            }
        }
    }
    if(s[-1]!='\n'){
        os << endl;
    }
    return os.str();
}//toString
References firstExtraCode(), float_1, format_string, int_1, and int_2.
Referenced by orgQhull::RoadError::what().
void1()
const void * orgQhull::RoadLogEvent::void1 () const inline
{ return void_1; };
Member Data Documentation
[union]
union { ... } orgQhull::RoadLogEvent
Float argument (f, for logging)
float_1
float orgQhull::RoadLogEvent::float_1
Integer argument (d, for logging)
Referenced by float1(), and toString().
format_string
const char* orgQhull::RoadLogEvent::format_string
Referenced by format(), isValid(), and toString().
int_1
int orgQhull::RoadLogEvent::int_1
Format string (a literal with format codes, for logging)
Referenced by int1(), and toString().
int_2
int orgQhull::RoadLogEvent::int_2
Integer argument (d, for logging)
Referenced by int2(), and toString().
The documentation for this struct was generated from the following files:
src/qhull/src/libqhullcpp/RoadLogEvent.h
src/qhull/src/libqhullcpp/RoadLogEvent.cpp