OrcaSlicer: Slic3r::GUI::MonitorPanel Class Reference
Slic3r::GUI::MonitorPanel Class Reference
#include <src/slic3r/GUI/Monitor.hpp>
Public Types
enum PrinterTab {
PT_STATUS = 0 , PT_MEDIA = 1 , PT_UPDATE = 2 , PT_HMS = 3 ,
PT_DEBUG = 4 , PT_MAX_NUM = 5
}
Public Member Functions
MonitorPanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~MonitorPanel ()
void init_bitmap ()
void init_timer ()
void init_tabpanel ()
Tabbook * get_tabpanel ()
void set_default ()
wxWindow * create_side_tools ()
void on_sys_color_changed ()
void msw_rescale ()
void select_machine (std::string machine_sn)
void on_update_all (wxMouseEvent &event)
void on_timer (wxTimerEvent &event)
void on_select_printer (wxCommandEvent &event)
void on_printer_clicked (wxMouseEvent &event)
void on_size (wxSizeEvent &event)
void update_status (MachineObject *obj)
void update_all ()
bool Show (bool show)
void update_side_panel ()
void show_status (int status)
Public Attributes
MachineObject * obj { nullptr }
std::string last_conn_type = "undedefined"
Private Attributes
Tabbook * m_tabpanel { nullptr }
wxSizer * m_main_sizer { nullptr }
AddMachinePanel * m_status_add_machine_panel
StatusPanel * m_status_info_panel
MediaFilePanel * m_media_file_panel
UpgradePanel * m_upgrade_panel
HMSPanel * m_hms_panel
Button * m_connection_info {nullptr}
wxHyperlinkCtrl * m_hyperlink {nullptr}
SideTools * m_side_tools {nullptr}
wxStaticBitmap * m_bitmap_printer_type
wxStaticBitmap * m_bitmap_arrow
wxStaticText * m_staticText_printer_name
wxStaticBitmap * m_bitmap_wifi_signal
wxBoxSizer * m_side_tools_sizer
SelectMachinePopup m_select_machine
wxBitmap m_signal_strong_img
wxBitmap m_signal_middle_img
wxBitmap m_signal_weak_img
wxBitmap m_signal_no_img
wxBitmap m_printer_img
wxBitmap m_arrow_img
int last_wifi_signal = -1
wxTimer * m_refresh_timer = nullptr
int last_status
bool m_initialized { false }
Detailed Description
Member Enumeration Documentation
PrinterTab
enum Slic3r::GUI::MonitorPanel::PrinterTab
Enumerator
PT_STATUS
PT_MEDIA
PT_UPDATE
PT_HMS
PT_DEBUG
PT_MAX_NUM
                    {
        PT_STATUS  = 0,
        PT_MEDIA   = 1,
        PT_UPDATE  = 2,
        PT_HMS     = 3,
        PT_DEBUG   = 4,
        PT_MAX_NUM = 5
    };
Constructor & Destructor Documentation
MonitorPanel()
Slic3r::GUI::MonitorPanel::MonitorPanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
    : wxPanel(parent, id, pos, size, style),
     m_select_machine(SelectMachinePopup(this))
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    init_bitmap();
    init_tabpanel();
    m_main_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_main_sizer->Add(m_tabpanel, 1, wxEXPAND | wxLEFT, 0);
    SetSizerAndFit(m_main_sizer);
    init_timer();
    m_side_tools->Connect(wxEVT_LEFT_DOWN, wxMouseEventHandler(MonitorPanel::on_printer_clicked), NULL, this);
    Bind(wxEVT_TIMER, &MonitorPanel::on_timer, this);
    Bind(wxEVT_SIZE, &MonitorPanel::on_size, this);
    Bind(wxEVT_COMMAND_CHOICE_SELECTED, &MonitorPanel::on_select_printer, this);
    m_select_machine.Bind(EVT_FINISHED_UPDATE_MACHINE_LIST, [this](wxCommandEvent& e) {
        m_side_tools->start_interval();
    });
}
References init_bitmap(), init_tabpanel(), init_timer(), m_main_sizer, m_select_machine, m_side_tools, m_tabpanel, NULL, on_printer_clicked(), on_select_printer(), on_size(), on_timer(), and Slic3r::GUI::SideTools::start_interval().
~MonitorPanel()
Slic3r::GUI::MonitorPanel::~MonitorPanel ()
{
    m_side_tools->Disconnect(wxEVT_LEFT_DOWN, wxMouseEventHandler(MonitorPanel::on_printer_clicked), NULL, this);
    if (m_refresh_timer)
        m_refresh_timer->Stop();
    delete m_refresh_timer;
}
References m_refresh_timer, m_side_tools, NULL, and on_printer_clicked().
Member Function Documentation
create_side_tools()
wxWindow * Slic3r::GUI::MonitorPanel::create_side_tools ()
{
    //TEST function
    //m_bitmap_wifi_signal->Connect(wxEVT_LEFT_DCLICK, wxMouseEventHandler(MonitorPanel::on_update_all), NULL, this);
    wxBoxSizer* sizer = new wxBoxSizer(wxVERTICAL);
    auto        panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(0, FromDIP(50)));
    panel->SetBackgroundColour(wxColour(135,206,250));
    panel->SetSizer(sizer);
    sizer->Layout();
    panel->Fit();
    return panel;
}
get_tabpanel()
Tabbook * Slic3r::GUI::MonitorPanel::get_tabpanel () inline
{ return m_tabpanel; };
References m_tabpanel.
Referenced by Slic3r::GUI::Plater::print_job_finished().
init_bitmap()
void Slic3r::GUI::MonitorPanel::init_bitmap ()
{
    m_signal_strong_img = create_scaled_bitmap("monitor_signal_strong", nullptr, 24);
    m_signal_middle_img = create_scaled_bitmap("monitor_signal_middle", nullptr, 24);
    m_signal_weak_img = create_scaled_bitmap("monitor_signal_weak", nullptr, 24);
    m_signal_no_img   = create_scaled_bitmap("monitor_signal_no", nullptr, 24);
    m_printer_img = create_scaled_bitmap("monitor_printer", nullptr, 26);
    m_arrow_img = create_scaled_bitmap("monitor_arrow",nullptr, 14);
}
References create_scaled_bitmap(), m_arrow_img, m_printer_img, m_signal_middle_img, m_signal_no_img, m_signal_strong_img, and m_signal_weak_img.
Referenced by MonitorPanel(), and msw_rescale().
init_tabpanel()
void Slic3r::GUI::MonitorPanel::init_tabpanel ()
{
    m_side_tools = new SideTools(this, wxID_ANY);
    wxBoxSizer* sizer_side_tools = new wxBoxSizer(wxVERTICAL);
   /* auto warning_panel = new wxPanel(this, wxID_ANY);
    warning_panel->SetBackgroundColour(wxColour(255, 111, 0));
    warning_panel->SetSize(wxSize(FromDIP(220), FromDIP(25)));
    warning_panel->SetMinSize(wxSize(FromDIP(220), FromDIP(25)));
    warning_panel->SetMaxSize(wxSize(FromDIP(220), FromDIP(25)));
    sizer_side_tools->Add(warning_panel, 0, wxEXPAND, 0);
    wxBoxSizer *sizer_boxh = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *sizer_boxv = new wxBoxSizer(wxHORIZONTAL);*/
    m_connection_info = new Button(this, "Failed to connect to the printer");
    m_connection_info->SetBackgroundColor(wxColour(255, 111, 0));
    m_connection_info->SetBorderColor(wxColour(255, 111, 0));
    m_connection_info->SetTextColor(*wxWHITE);
    m_connection_info->SetFont(::Label::Body_13);
    m_connection_info->SetCornerRadius(0);
    m_connection_info->SetSize(wxSize(FromDIP(-1), FromDIP(25)));
    m_connection_info->SetMinSize(wxSize(FromDIP(-1), FromDIP(25)));
    m_connection_info->SetMaxSize(wxSize(FromDIP(-1), FromDIP(25)));
    wxBoxSizer* connection_sizer = new wxBoxSizer(wxVERTICAL);
    m_hyperlink = new wxHyperlinkCtrl(m_connection_info, wxID_ANY, _L("Failed to connect to the server"), wxT("https://wiki.bambulab.com/en/software/bambu-studio/failed-to-connect-printer"), wxDefaultPosition, wxDefaultSize, wxHL_DEFAULT_STYLE);
    connection_sizer->Add(m_hyperlink, 0, wxALIGN_CENTER | wxALL, 5);
    m_hyperlink->SetBackgroundColour(wxColour(255, 111, 0));
    m_connection_info->SetSizer(connection_sizer);
    m_connection_info->Layout();
    connection_sizer->Fit(m_connection_info);
    m_connection_info->Hide();
    sizer_side_tools->Add(m_connection_info, 0, wxEXPAND, 0);
    sizer_side_tools->Add(m_side_tools, 1, wxEXPAND, 0);
    m_tabpanel             = new Tabbook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, sizer_side_tools, wxNB_LEFT | wxTAB_TRAVERSAL | wxNB_NOPAGETHEME);
    m_tabpanel->SetBackgroundColour(wxColour("#FEFFFF"));
    m_tabpanel->Bind(wxEVT_BOOKCTRL_PAGE_CHANGED, [this](wxBookCtrlEvent& e) {
        ;
    });
    //m_status_add_machine_panel = new AddMachinePanel(m_tabpanel);
    m_status_info_panel        = new StatusPanel(m_tabpanel);
    m_tabpanel->AddPage(m_status_info_panel, _L("Status"), "", true);
    m_media_file_panel = new MediaFilePanel(m_tabpanel);
    m_tabpanel->AddPage(m_media_file_panel, _L("Media"), "", false);
    m_upgrade_panel = new UpgradePanel(m_tabpanel);
    m_tabpanel->AddPage(m_upgrade_panel, _L("Update"), "", false);
    m_hms_panel = new HMSPanel(m_tabpanel);
    m_tabpanel->AddPage(m_hms_panel, _L("HMS"),"", false);
    m_initialized = true;
    show_status((int)MonitorStatus::MONITOR_NO_PRINTER);
}
References _L, Tabbook::AddPage(), Label::Body_13, m_connection_info, m_hms_panel, m_hyperlink, m_initialized, m_media_file_panel, m_side_tools, m_status_info_panel, m_tabpanel, m_upgrade_panel, Slic3r::GUI::MONITOR_NO_PRINTER, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetFont(), Button::SetMinSize(), Button::SetTextColor(), and show_status().
Referenced by MonitorPanel().
init_timer()
void Slic3r::GUI::MonitorPanel::init_timer ()
{
    m_refresh_timer = new wxTimer();
    m_refresh_timer->SetOwner(this);
    m_refresh_timer->Start(REFRESH_INTERVAL);
    wxPostEvent(this, wxTimerEvent());
    Slic3r::DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    MachineObject *obj_ = dev->get_selected_machine();
    if (obj_)
        GUI::wxGetApp().sidebar().load_ams_list(obj_->dev_id, obj_->amsList);
}
References Slic3r::MachineObject::amsList, Slic3r::MachineObject::dev_id, Slic3r::DeviceManager::get_selected_machine(), m_refresh_timer, and REFRESH_INTERVAL.
Referenced by MonitorPanel().
msw_rescale()
void Slic3r::GUI::MonitorPanel::msw_rescale ()
{
    init_bitmap();
    /* side_tool rescale */
    m_side_tools->msw_rescale();
    m_tabpanel->Rescale();
    //m_status_add_machine_panel->msw_rescale();
    m_status_info_panel->msw_rescale();
    m_media_file_panel->Rescale();
    m_upgrade_panel->msw_rescale();
    m_hms_panel->msw_rescale();
    m_connection_info->SetCornerRadius(0);
    m_connection_info->SetSize(wxSize(FromDIP(220), FromDIP(25)));
    m_connection_info->SetMinSize(wxSize(FromDIP(220), FromDIP(25)));
    m_connection_info->SetMaxSize(wxSize(FromDIP(220), FromDIP(25)));
    Layout();
    Refresh();
}
References init_bitmap(), m_connection_info, m_hms_panel, m_media_file_panel, m_side_tools, m_status_info_panel, m_tabpanel, m_upgrade_panel, Slic3r::GUI::HMSPanel::msw_rescale(), Slic3r::GUI::StatusPanel::msw_rescale(), Slic3r::GUI::UpgradePanel::msw_rescale(), Slic3r::GUI::SideTools::msw_rescale(), Slic3r::GUI::MediaFilePanel::Rescale(), Tabbook::Rescale(), StaticBox::SetCornerRadius(), and Button::SetMinSize().
on_printer_clicked()
void Slic3r::GUI::MonitorPanel::on_printer_clicked (wxMouseEvent & event)
{
    auto mouse_pos = ClientToScreen(event.GetPosition());
    wxPoint rect = m_side_tools->ClientToScreen(wxPoint(0, 0));
    if (!m_side_tools->is_in_interval()) {
        wxPoint pos = m_side_tools->ClientToScreen(wxPoint(0, 0));
        pos.y += m_side_tools->GetRect().height;
        //pos.x = pos.x < 0? 0:pos.x;
        m_select_machine.Move(pos);
#ifdef __linux__
        m_select_machine.SetSize(wxSize(m_side_tools->GetSize().x, -1));
        m_select_machine.SetMaxSize(wxSize(m_side_tools->GetSize().x, -1));
        m_select_machine.SetMinSize(wxSize(m_side_tools->GetSize().x, -1));
#endif
        m_select_machine.Popup();
    }
}
References Slic3r::GUI::SideTools::is_in_interval(), m_select_machine, m_side_tools, and Slic3r::GUI::SelectMachinePopup::Popup().
Referenced by MonitorPanel(), and ~MonitorPanel().
on_select_printer()
void Slic3r::GUI::MonitorPanel::on_select_printer (wxCommandEvent & event)
{
    Slic3r::DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    if (!dev->set_selected_machine(event.GetString().ToStdString()))
        return;
    set_default();
    update_all();
    MachineObject *obj_ = dev->get_selected_machine();
    if (obj_)
        GUI::wxGetApp().sidebar().load_ams_list(obj_->dev_id, obj_->amsList);
    Layout();
    Refresh();
}
References Slic3r::MachineObject::amsList, Slic3r::MachineObject::dev_id, Slic3r::DeviceManager::get_selected_machine(), set_default(), Slic3r::DeviceManager::set_selected_machine(), and update_all().
Referenced by MonitorPanel().
on_size()
void Slic3r::GUI::MonitorPanel::on_size (wxSizeEvent & event)
{
    Layout();
    Refresh();
}
Referenced by MonitorPanel().
on_sys_color_changed()
void Slic3r::GUI::MonitorPanel::on_sys_color_changed ()
{
    m_status_info_panel->on_sys_color_changed();
    m_upgrade_panel->on_sys_color_changed();
}
References m_status_info_panel, m_upgrade_panel, Slic3r::GUI::StatusPanel::on_sys_color_changed(), and Slic3r::GUI::UpgradePanel::on_sys_color_changed().
on_timer()
void Slic3r::GUI::MonitorPanel::on_timer (wxTimerEvent & event)
{
    update_all();
    Layout();
    Refresh();
}
References update_all().
Referenced by MonitorPanel().
on_update_all()
void Slic3r::GUI::MonitorPanel::on_update_all (wxMouseEvent & event)
{
    update_all();
    Layout();
    Refresh();
}
References update_all().
select_machine()
void Slic3r::GUI::MonitorPanel::select_machine (std::string machine_sn)
{
    wxCommandEvent *event = new wxCommandEvent(wxEVT_COMMAND_CHOICE_SELECTED);
    event->SetString(machine_sn);
    wxQueueEvent(this, event);
}
set_default()
void Slic3r::GUI::MonitorPanel::set_default ()
{
    obj = nullptr;
    last_conn_type = "undefined";
    /* reset status panel*/
    m_status_info_panel->set_default();
    /* reset side tool*/
    //m_bitmap_wifi_signal->SetBitmap(wxNullBitmap);
    wxGetApp().sidebar().load_ams_list({}, {});
}
References last_conn_type, m_status_info_panel, obj, and Slic3r::GUI::StatusPanel::set_default().
Referenced by on_select_printer(), and show_status().
Show()
bool Slic3r::GUI::MonitorPanel::Show (bool show)
{
#ifdef __APPLE__
    wxGetApp().mainframe->SetMinSize(wxGetApp().plater()->GetMinSize());
#endif
    NetworkAgent* m_agent = wxGetApp().getAgent();
    DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (show) {
        m_refresh_timer->Stop();
        m_refresh_timer->SetOwner(this);
        m_refresh_timer->Start(REFRESH_INTERVAL);
        wxPostEvent(this, wxTimerEvent());
        if (dev) {
            //set a default machine when obj is null
            obj = dev->get_selected_machine();
            if (obj == nullptr) {
                dev->load_last_machine();
                obj = dev->get_selected_machine();
                if (obj)
                    GUI::wxGetApp().sidebar().load_ams_list(obj->dev_id, obj->amsList);
            } else {
                obj->reset_update_time();
            }
        }
    } else {
        m_refresh_timer->Stop();
    }
    return wxPanel::Show(show);
}
References Slic3r::MachineObject::amsList, Slic3r::MachineObject::dev_id, Slic3r::DeviceManager::get_selected_machine(), Slic3r::DeviceManager::load_last_machine(), m_refresh_timer, obj, Slic3r::GUI::plater(), REFRESH_INTERVAL, and Slic3r::MachineObject::reset_update_time().
show_status()
void Slic3r::GUI::MonitorPanel::show_status (int status)
{
    if (!m_initialized) return;
    if (last_status == status)
        return;
    if (last_status & (int)MonitorStatus::MONITOR_CONNECTING != 0) {
        NetworkAgent* agent = wxGetApp().getAgent();
        json j;
        j["dev_id"] = obj ? obj->dev_id : "obj_nullptr";
        if (status & (int)MonitorStatus::MONITOR_DISCONNECTED != 0) {
            j["result"] = "failed";
            if (agent) {
                agent->track_event("connect_dev", j.dump());
            }
        }
        else if (status & (int)MonitorStatus::MONITOR_NORMAL != 0) {
            j["result"] = "success";
            if (agent) {
                agent->track_event("connect_dev", j.dump());
            }
        }
    }
    last_status = status;
    BOOST_LOG_TRIVIAL(info) << "monitor: show_status = " << status;
    if (((status & (int) MonitorStatus::MONITOR_DISCONNECTED) != 0) || ((status & (int) MonitorStatus::MONITOR_DISCONNECTED_SERVER) != 0)) {
        if ((status & (int) MonitorStatus::MONITOR_DISCONNECTED_SERVER))
            m_hyperlink->SetLabel(_L("Failed to connect to the server"));
            //m_connection_info->SetLabel(_L("Failed to connect to the server"));
        else
            m_hyperlink->SetLabel(_L("Failed to connect to the printer"));
            //m_connection_info->SetLabel(_L("Failed to connect to the printer"));
        m_hyperlink->Show();
        m_connection_info->SetLabel(wxEmptyString);
        m_connection_info->Show();
        m_connection_info->SetBackgroundColor(wxColour(255, 111, 0));
        m_connection_info->SetBorderColor(wxColour(255, 111, 0));
#if !BBL_RELEASE_TO_PUBLIC
        m_upgrade_panel->update(nullptr);
#endif
    } else if ((status & (int) MonitorStatus::MONITOR_NORMAL) != 0) {
        m_connection_info->Hide();
    } else if ((status & (int) MonitorStatus::MONITOR_CONNECTING) != 0) {
        m_hyperlink->Hide();
        m_connection_info->SetLabel(_L("Connecting..."));
        m_connection_info->SetBackgroundColor(wxColour(0, 150, 136));
        m_connection_info->SetBorderColor(wxColour(0, 150, 136));
        m_connection_info->Show();
    }
    Freeze();
    // update panels
    m_status_info_panel->show_status(status);
    m_hms_panel->show_status(status);
    m_upgrade_panel->show_status(status);
    if ((status & (int)MonitorStatus::MONITOR_NO_PRINTER) != 0) {
        set_default();
        m_side_tools->set_none_printer_mode();
        m_connection_info->Hide();
        m_tabpanel->Refresh();
        m_tabpanel->Layout();
#if !BBL_RELEASE_TO_PUBLIC
        m_upgrade_panel->update(nullptr);
#endif
    } else if (((status & (int)MonitorStatus::MONITOR_NORMAL) != 0)
        || ((status & (int)MonitorStatus::MONITOR_DISCONNECTED) != 0)
        || ((status & (int) MonitorStatus::MONITOR_DISCONNECTED_SERVER) != 0)
        || ((status & (int)MonitorStatus::MONITOR_CONNECTING) != 0)
        ) {
        if (((status & (int) MonitorStatus::MONITOR_DISCONNECTED) != 0)
            || ((status & (int) MonitorStatus::MONITOR_DISCONNECTED_SERVER) != 0)
            || ((status & (int)MonitorStatus::MONITOR_CONNECTING) != 0)) {
            m_side_tools->set_current_printer_signal(WifiSignal::NONE);
            set_default();
        }
        m_tabpanel->Refresh();
        m_tabpanel->Layout();
    }
    Layout();
    Thaw();
}
References _L, Slic3r::MachineObject::dev_id, nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::dump(), last_status, m_connection_info, m_hms_panel, m_hyperlink, m_initialized, m_side_tools, m_status_info_panel, m_tabpanel, m_upgrade_panel, Slic3r::GUI::MONITOR_CONNECTING, Slic3r::GUI::MONITOR_DISCONNECTED, Slic3r::GUI::MONITOR_DISCONNECTED_SERVER, Slic3r::GUI::MONITOR_NO_PRINTER, Slic3r::GUI::MONITOR_NORMAL, NONE, obj, Slic3r::GUI::SideTools::set_current_printer_signal(), set_default(), Slic3r::GUI::SideTools::set_none_printer_mode(), StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), Button::SetLabel(), Slic3r::GUI::HMSPanel::show_status(), Slic3r::GUI::StatusPanel::show_status(), Slic3r::GUI::UpgradePanel::show_status(), Slic3r::NetworkAgent::track_event(), and Slic3r::GUI::UpgradePanel::update().
Referenced by init_tabpanel(), and update_all().
update_all()
void Slic3r::GUI::MonitorPanel::update_all ()
{
    NetworkAgent* m_agent = wxGetApp().getAgent();
    Slic3r::DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev)
        return;
    obj = dev->get_selected_machine();
    // check valid machine
    if (obj && dev->get_my_machine(obj->dev_id) == nullptr) {
        dev->set_selected_machine("");
        if (m_agent)
            m_agent->set_user_selected_machine("");
        show_status((int)MONITOR_NO_PRINTER);
        return;
    }
    //BBS check mqtt connections if user is login
    if (wxGetApp().is_user_login()) {
        dev->check_pushing();
        // check mqtt connection and reconnect if disconnected
        try {
            m_agent->refresh_connection();
        }
        catch (...) {
            ;
        }
    }
    if (obj) {
        wxGetApp().reset_to_active();
        if (obj->connection_type() != last_conn_type) {
            last_conn_type = obj->connection_type();
        }
    }
    m_status_info_panel->obj = obj;
    m_upgrade_panel->update(obj);
    m_status_info_panel->m_media_play_ctrl->SetMachineObject(obj);
    m_media_file_panel->SetMachineObject(obj);
    update_status(obj);
    if (!obj) {
        show_status((int)MONITOR_NO_PRINTER);
        return;
    }
    if (obj->is_connecting()) {
        show_status(MONITOR_CONNECTING);
        return;
    } else if (!obj->is_connected()) {
        int server_status = 0;
        // only disconnected server in cloud mode
        if (obj->connection_type() != "lan") {
            if (m_agent) {
                server_status = m_agent->is_server_connected() ? 0 : (int)MONITOR_DISCONNECTED_SERVER;
            }
        }
        show_status((int) MONITOR_DISCONNECTED + server_status);
        return;
    }
    show_status(MONITOR_NORMAL);
    if (m_status_info_panel->IsShown()) {
        m_status_info_panel->update(obj);
    }
    if (m_hms_panel->IsShown()) {
        m_hms_panel->update(obj);
    }
#if !BBL_RELEASE_TO_PUBLIC
    if (m_upgrade_panel->IsShown()) {
        m_upgrade_panel->update(obj);
    }
#endif
}
References Slic3r::DeviceManager::check_pushing(), Slic3r::MachineObject::connection_type(), Slic3r::MachineObject::dev_id, Slic3r::DeviceManager::get_my_machine(), Slic3r::DeviceManager::get_selected_machine(), int, Slic3r::MachineObject::is_connected(), Slic3r::MachineObject::is_connecting(), Slic3r::NetworkAgent::is_server_connected(), last_conn_type, m_hms_panel, m_media_file_panel, Slic3r::GUI::StatusBasePanel::m_media_play_ctrl, m_status_info_panel, m_upgrade_panel, Slic3r::GUI::MONITOR_CONNECTING, Slic3r::GUI::MONITOR_DISCONNECTED, Slic3r::GUI::MONITOR_DISCONNECTED_SERVER, Slic3r::GUI::MONITOR_NO_PRINTER, Slic3r::GUI::MONITOR_NORMAL, obj, Slic3r::GUI::StatusPanel::obj, Slic3r::NetworkAgent::refresh_connection(), Slic3r::DeviceManager::set_selected_machine(), Slic3r::NetworkAgent::set_user_selected_machine(), Slic3r::GUI::MediaFilePanel::SetMachineObject(), Slic3r::GUI::MediaPlayCtrl::SetMachineObject(), show_status(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::UpgradePanel::update(), Slic3r::GUI::HMSPanel::update(), and update_status().
Referenced by on_select_printer(), on_timer(), and on_update_all().
update_side_panel()
void Slic3r::GUI::MonitorPanel::update_side_panel ()
{
    Slic3r::DeviceManager *dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    auto is_next_machine = false;
    if (!dev->get_first_online_user_machine().empty()) {
        wxCommandEvent* event = new wxCommandEvent(wxEVT_COMMAND_CHOICE_SELECTED);
        event->SetString(dev->get_first_online_user_machine());
        wxQueueEvent(this, event);
        is_next_machine = true;
        return;
    }
    if (!is_next_machine) { m_side_tools->set_none_printer_mode(); }
}
References Slic3r::DeviceManager::get_first_online_user_machine(), m_side_tools, and Slic3r::GUI::SideTools::set_none_printer_mode().
update_status()
void Slic3r::GUI::MonitorPanel::update_status (MachineObject * obj)
{
    if (!obj) return;
    /* Update Device Info */
    m_side_tools->set_current_printer_name(obj->dev_name);
    // update wifi signal image
    int wifi_signal_val = 0;
    if (!obj->is_connected() || obj->is_connecting()) {
        m_side_tools->set_current_printer_signal(WifiSignal::NONE);
    } else {
        if (!obj->wifi_signal.empty() && boost::ends_with(obj->wifi_signal, "dBm")) {
            try {
                wifi_signal_val = std::stoi(obj->wifi_signal.substr(0, obj->wifi_signal.size() - 3));
            }
            catch (...) {
                ;
            }
            if (wifi_signal_val > -45) {
                m_side_tools->set_current_printer_signal(WifiSignal::STRONG);
            }
            else if (wifi_signal_val <= -45 && wifi_signal_val >= -60) {
                m_side_tools->set_current_printer_signal(WifiSignal::MIDDLE);
            }
            else {
                m_side_tools->set_current_printer_signal(WifiSignal::WEAK);
            }
        }
        else {
            m_side_tools->set_current_printer_signal(WifiSignal::MIDDLE);
        }
    }
}
References Slic3r::MachineObject::dev_name, Slic3r::MachineObject::is_connected(), Slic3r::MachineObject::is_connecting(), m_side_tools, MIDDLE, NONE, obj, Slic3r::GUI::SideTools::set_current_printer_name(), Slic3r::GUI::SideTools::set_current_printer_signal(), STRONG, WEAK, and Slic3r::MachineObject::wifi_signal.
Referenced by update_all().
Member Data Documentation
last_conn_type
std::string Slic3r::GUI::MonitorPanel::last_conn_type = "undedefined"
Referenced by set_default(), and update_all().
last_status
int Slic3r::GUI::MonitorPanel::last_status private
Referenced by show_status().
last_wifi_signal
int Slic3r::GUI::MonitorPanel::last_wifi_signal = -1 private
m_arrow_img
wxBitmap Slic3r::GUI::MonitorPanel::m_arrow_img private
Referenced by init_bitmap().
m_bitmap_arrow
wxStaticBitmap* Slic3r::GUI::MonitorPanel::m_bitmap_arrow private
m_bitmap_printer_type
wxStaticBitmap* Slic3r::GUI::MonitorPanel::m_bitmap_printer_type private
m_bitmap_wifi_signal
wxStaticBitmap* Slic3r::GUI::MonitorPanel::m_bitmap_wifi_signal private
m_connection_info
Button* Slic3r::GUI::MonitorPanel::m_connection_info {nullptr} private
Referenced by init_tabpanel(), msw_rescale(), and show_status().
m_hms_panel
HMSPanel* Slic3r::GUI::MonitorPanel::m_hms_panel private
Referenced by init_tabpanel(), msw_rescale(), show_status(), and update_all().
m_hyperlink
wxHyperlinkCtrl* Slic3r::GUI::MonitorPanel::m_hyperlink {nullptr} private
Referenced by init_tabpanel(), and show_status().
m_initialized
bool Slic3r::GUI::MonitorPanel::m_initialized { false } private
Referenced by init_tabpanel(), and show_status().
m_main_sizer
wxSizer* Slic3r::GUI::MonitorPanel::m_main_sizer { nullptr } private
Referenced by MonitorPanel().
m_media_file_panel
MediaFilePanel* Slic3r::GUI::MonitorPanel::m_media_file_panel private
Referenced by init_tabpanel(), msw_rescale(), and update_all().
m_printer_img
wxBitmap Slic3r::GUI::MonitorPanel::m_printer_img private
Referenced by init_bitmap().
m_refresh_timer
wxTimer* Slic3r::GUI::MonitorPanel::m_refresh_timer = nullptr private
Referenced by ~MonitorPanel(), init_timer(), and Show().
m_select_machine
SelectMachinePopup Slic3r::GUI::MonitorPanel::m_select_machine private
Referenced by MonitorPanel(), and on_printer_clicked().
m_side_tools
SideTools* Slic3r::GUI::MonitorPanel::m_side_tools {nullptr} private
Referenced by MonitorPanel(), ~MonitorPanel(), init_tabpanel(), msw_rescale(), on_printer_clicked(), show_status(), update_side_panel(), and update_status().
m_side_tools_sizer
wxBoxSizer* Slic3r::GUI::MonitorPanel::m_side_tools_sizer private
m_signal_middle_img
wxBitmap Slic3r::GUI::MonitorPanel::m_signal_middle_img private
Referenced by init_bitmap().
m_signal_no_img
wxBitmap Slic3r::GUI::MonitorPanel::m_signal_no_img private
Referenced by init_bitmap().
m_signal_strong_img
wxBitmap Slic3r::GUI::MonitorPanel::m_signal_strong_img private
Referenced by init_bitmap().
m_signal_weak_img
wxBitmap Slic3r::GUI::MonitorPanel::m_signal_weak_img private
Referenced by init_bitmap().
m_staticText_printer_name
wxStaticText* Slic3r::GUI::MonitorPanel::m_staticText_printer_name private
m_status_add_machine_panel
AddMachinePanel* Slic3r::GUI::MonitorPanel::m_status_add_machine_panel private
m_status_info_panel
StatusPanel* Slic3r::GUI::MonitorPanel::m_status_info_panel private
Referenced by init_tabpanel(), msw_rescale(), on_sys_color_changed(), set_default(), show_status(), and update_all().
m_tabpanel
Tabbook* Slic3r::GUI::MonitorPanel::m_tabpanel { nullptr } private
Referenced by MonitorPanel(), get_tabpanel(), init_tabpanel(), msw_rescale(), and show_status().
m_upgrade_panel
UpgradePanel* Slic3r::GUI::MonitorPanel::m_upgrade_panel private
Referenced by init_tabpanel(), msw_rescale(), on_sys_color_changed(), show_status(), and update_all().
obj
MachineObject* Slic3r::GUI::MonitorPanel::obj { nullptr }
Referenced by set_default(), Show(), show_status(), update_all(), and update_status().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Monitor.hpp
src/slic3r/GUI/Monitor.cpp