OrcaSlicer: Button Class Reference
Button Class Reference
#include <src/slic3r/GUI/Widgets/Button.hpp>
Public Member Functions
Button ()
Button (wxWindow *parent, wxString text, wxString icon="", long style=0, int iconSize=0, wxWindowID btn_id=wxID_ANY)
bool Create (wxWindow *parent, wxString text, wxString icon="", long style=0, int iconSize=0, wxWindowID btn_id=wxID_ANY)
void SetLabel (const wxString &label) override
bool SetFont (const wxFont &font) override
void SetIcon (const wxString &icon)
void SetInactiveIcon (const wxString &icon)
void SetMinSize (const wxSize &size) override
void SetPaddingSize (const wxSize &size)
void SetTextColor (StateColor const &color)
void SetTextColorNormal (wxColor const &color)
void SetSelected (bool selected=true)
bool Enable (bool enable=true) override
void SetCanFocus (bool canFocus) override
void SetValue (bool state)
bool GetValue () const
void Rescale ()
bool Create (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
void SetCornerRadius (double radius)
void SetBorderWidth (int width)
void SetBorderColor (StateColor const &color)
void SetBorderColorNormal (wxColor const &color)
void SetBackgroundColor (StateColor const &color)
void SetBackgroundColorNormal (wxColor const &color)
void SetBackgroundColor2 (StateColor const &color)
Static Public Member Functions
static wxColor GetParentBackgroundColor (wxWindow *parent)
Protected Member Functions
bool AcceptsFocus () const override
void eraseEvent (wxEraseEvent &evt)
virtual void doRender (wxDC &dc)
Protected Attributes
double radius
int border_width = 1
StateHandler state_handler
StateColor border_color
StateColor background_color
StateColor background_color2
Private Member Functions
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void messureSize ()
void mouseDown (wxMouseEvent &event)
void mouseReleased (wxMouseEvent &event)
void mouseCaptureLost (wxMouseCaptureLostEvent &event)
void keyDownUp (wxKeyEvent &event)
void sendButtonEvent ()
Private Attributes
wxRect textSize
wxSize minSize
wxSize paddingSize
ScalableBitmap active_icon
ScalableBitmap inactive_icon
StateColor text_color
bool pressedDown = false
bool m_selected = true
bool canFocus = true
Static Private Attributes
static const int buttonWidth = 200
static const int buttonHeight = 50
Detailed Description
Constructor & Destructor Documentation
Button() [1/2]
Button::Button ()
    : paddingSize(10, 8)
{
    background_color = StateColor(
        std::make_pair(0xF0F0F1, (int) StateColor::Disabled),
        std::make_pair(0x52c7b8, (int) StateColor::Hovered | StateColor::Checked),
        std::make_pair(0x009688, (int) StateColor::Checked),
        std::make_pair(*wxLIGHT_GREY, (int) StateColor::Hovered),
        std::make_pair(*wxWHITE, (int) StateColor::Normal));
    text_color       = StateColor(
        std::make_pair(*wxLIGHT_GREY, (int) StateColor::Disabled),
        std::make_pair(*wxBLACK, (int) StateColor::Normal));
}
References StateColor::Checked, StateColor::Disabled, StateColor::Hovered, StateColor::Normal, and text_color().
Button() [2/2]
Button::Button (wxWindow * parent, wxString text, wxString icon = "", long style = 0, int iconSize = 0, wxWindowID btn_id = wxID_ANY)
    : Button()
{
    Create(parent, text, icon, style, iconSize, btn_id);
}
References Create(), and style.
Member Function Documentation
AcceptsFocus()
bool Button::AcceptsFocus () const override protected
{ return canFocus; }
References canFocus.
Create() [1/2]
bool Button::Create (wxWindow * parent, wxString text, wxString icon = "", long style = 0, int iconSize = 0, wxWindowID btn_id = wxID_ANY)
{
    StaticBox::Create(parent, btn_id, wxDefaultPosition, wxDefaultSize, style);
    state_handler.attach({&text_color});
    state_handler.update_binds();
    //BBS set default font
    SetFont(Label::Body_14);
    wxWindow::SetLabel(text);
    if (!icon.IsEmpty()) {
        //BBS set button icon default size to 20
        this->active_icon = ScalableBitmap(this, icon.ToStdString(), iconSize > 0 ? iconSize : 20);
    }
    messureSize();
    return true;
}
References active_icon, StateHandler::attach(), Label::Body_14, StaticBox::Create(), messureSize(), SetFont(), StaticBox::state_handler, style, text_color, and StateHandler::update_binds().
Referenced by Button(), and TabCtrl::AppendItem().
Create() [2/2]
bool StaticBox::Create (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0) inherited
{
    if (style & wxBORDER_NONE)
        border_width = 0;
    wxWindow::Create(parent, id, pos, size, style);
    state_handler.attach({&border_color, &background_color, &background_color2});
    state_handler.update_binds();
    SetBackgroundColour(GetParentBackgroundColor(parent));
    return true;
}
References StateHandler::attach(), StaticBox::background_color, StaticBox::background_color2, StaticBox::border_color, StaticBox::border_width, StaticBox::GetParentBackgroundColor(), size, StaticBox::state_handler, style, and StateHandler::update_binds().
Referenced by FanSwitchButton::FanSwitchButton(), ImageSwitchButton::ImageSwitchButton(), StaticBox::StaticBox(), Create(), SpinInput::Create(), TextInput::Create(), and TempInput::Create().
doRender()
void StaticBox::doRender (wxDC & dc) protected virtual inherited
Reimplemented in StepCtrl, StepIndicator, and TabCtrl.
{
    wxSize size = GetSize();
    int states = state_handler.states();
    if (background_color2.count() == 0) {
        if ((border_width && border_color.count() > 0) || background_color.count() > 0) {
            wxRect rc(0, 0, size.x, size.y);
            if (border_width && border_color.count() > 0) {
                if (dc.GetContentScaleFactor() == 1.0) {
                    int d  = floor(border_width / 2.0);
                    int d2 = floor(border_width - 1);
                    rc.x += d;
                    rc.width -= d2;
                    rc.y += d;
                    rc.height -= d2;
                } else {
                    int d  = 1;
                    rc.x += d;
                    rc.width -= d;
                    rc.y += d;
                    rc.height -= d;
                }
                dc.SetPen(wxPen(border_color.colorForStates(states), border_width));
            } else {
                dc.SetPen(wxPen(background_color.colorForStates(states)));
            }
            if (background_color.count() > 0)
                dc.SetBrush(wxBrush(background_color.colorForStates(states)));
            else
                dc.SetBrush(wxBrush(GetBackgroundColour()));
            if (radius == 0) {
                dc.DrawRectangle(rc);
            }
            else {
                dc.DrawRoundedRectangle(rc, radius - border_width);
            }
        }
    }
    else {
        wxColor start = background_color.colorForStates(states);
        wxColor stop = background_color2.colorForStates(states);
        int r = start.Red(), g = start.Green(), b = start.Blue();
        int dr = (int) stop.Red() - r, dg = (int) stop.Green() - g, db = (int) stop.Blue() - b;
        int lr = 0, lg = 0, lb = 0;
        for (int y = 0; y < size.y; ++y) {
            dc.SetPen(wxPen(wxColor(r, g, b)));
            dc.DrawLine(0, y, size.x, y);
            lr += dr; while (lr >= size.y) { ++r, lr -= size.y; } while (lr <= -size.y) { --r, lr += size.y; }
            lg += dg; while (lg >= size.y) { ++g, lg -= size.y; } while (lg <= -size.y) { --g, lg += size.y; }
            lb += db; while (lb >= size.y) { ++b, lb -= size.y; } while (lb <= -size.y) { --b, lb += size.y; }
        }
    }
}
References StaticBox::background_color, StaticBox::background_color2, StaticBox::border_color, StaticBox::border_width, StateColor::colorForStates(), StateColor::count(), floor(), int, StaticBox::radius, size, start, StaticBox::state_handler, and StateHandler::states().
Referenced by StepCtrl::doRender(), StepIndicator::doRender(), and StaticBox::render().
Enable()
bool Button::Enable (bool enable = true) override
{
    bool result = wxWindow::Enable(enable);
    if (result) {
        wxCommandEvent e(EVT_ENABLE_CHANGED);
        e.SetEventObject(this);
        GetEventHandler()->ProcessEvent(e);
    }
    return result;
}
Referenced by Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PublishDialog::cancel(), Slic3r::GUI::ProgressDialog::Create(), Slic3r::GUI::AMSControl::Enable(), SpinInput::Enable(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::ExtrusionCalibration::get_bed_type_incompatible(), Slic3r::GUI::ConfigWizard::priv::load_pages(), Slic3r::GUI::InputIpAddressDialog::on_check_ip_address_failed(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), Slic3r::GUI::PublishDialog::reset(), Slic3r::GUI::ProgressDialog::Resume(), Slic3r::GUI::AMSControl::SetActionState(), Slic3r::GUI::MediaFilePanel::SetMachineObject(), Slic3r::GUI::StatusPanel::show_printing_status(), Slic3r::GUI::StatusPanel::show_status(), Slic3r::GUI::MachineInfoPanel::show_status(), Slic3r::GUI::ExtrusionCalibration::update(), Slic3r::GUI::CalibrationDialog::update_cali(), Slic3r::GUI::StatusPanel::update_cali(), and Slic3r::GUI::ExtrusionCalibration::update_combobox_filaments().
eraseEvent()
void StaticBox::eraseEvent (wxEraseEvent & evt) protected inherited
{
    // for transparent background, but not work
#ifdef __WXMSW__
    wxDC *dc = evt.GetDC();
    wxSize size = GetSize();
    wxClientDC dc2(GetParent());
    dc->Blit({0, 0}, size, &dc2, GetPosition());
#endif
}
References size.
GetParentBackgroundColor()
wxColor StaticBox::GetParentBackgroundColor (wxWindow * parent) static inherited
{
    if (auto box = dynamic_cast<StaticBox*>(parent)) {
        if (box->background_color.count() > 0) {
            if (box->background_color2.count() == 0)
                return box->background_color.defaultColor();
            auto s = box->background_color.defaultColor();
            auto e = box->background_color2.defaultColor();
            int r = (s.Red() + e.Red()) / 2;
            int g = (s.Green() + e.Green()) / 2;
            int b = (s.Blue() + e.Blue()) / 2;
            return wxColor(r, g, b);
        }
    }
    if (parent)
        return parent->GetBackgroundColour();
    return *wxWHITE;
}
Referenced by Label::Label(), ScalableButton::ScalableButton(), SwitchButton::SwitchButton(), StaticBox::Create(), and SwitchButton::Rescale().
GetValue()
bool Button::GetValue () const
{ return state_handler.states() & StateHandler::Checked; }
References StateHandler::Checked, StaticBox::state_handler, and StateHandler::states().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel(), and SetValue().
keyDownUp()
void Button::keyDownUp (wxKeyEvent & event) private
{
    if (event.GetKeyCode() == WXK_SPACE || event.GetKeyCode() == WXK_RETURN) {
        wxMouseEvent evt(event.GetEventType() == wxEVT_KEY_UP ? wxEVT_LEFT_UP : wxEVT_LEFT_DOWN);
        event.SetEventObject(this);
        GetEventHandler()->ProcessEvent(evt);
        return;
    }
    if (event.GetEventType() == wxEVT_KEY_DOWN &&
        (event.GetKeyCode() == WXK_TAB || event.GetKeyCode() == WXK_LEFT || event.GetKeyCode() == WXK_RIGHT
        || event.GetKeyCode() == WXK_UP || event.GetKeyCode() == WXK_DOWN))
        HandleAsNavigationKey(event);
    else
        event.Skip();
}
messureSize()
void Button::messureSize () private
{
    wxClientDC dc(this);
    dc.GetTextExtent(GetLabel(), &textSize.width, &textSize.height, &textSize.x, &textSize.y);
    wxSize szContent = textSize.GetSize();
    if (this->active_icon.bmp().IsOk()) {
        if (szContent.y > 0) {
            //BBS norrow size between text and icon
            szContent.x += 5;
        }
        wxSize szIcon = this->active_icon.GetBmpSize();
        szContent.x += szIcon.x;
        if (szIcon.y > szContent.y)
            szContent.y = szIcon.y;
    }
    wxSize size = szContent + paddingSize * 2;
    if (minSize.GetHeight() > 0)
        size.SetHeight(minSize.GetHeight());
    if (minSize.GetWidth() > size.GetWidth())
        wxWindow::SetMinSize(minSize);
    else
        wxWindow::SetMinSize(size);
}
References active_icon, ScalableBitmap::bmp(), ScalableBitmap::GetBmpSize(), minSize, paddingSize, size, and textSize.
Referenced by Create(), Rescale(), SetFont(), SetLabel(), SetMinSize(), and SetPaddingSize().
mouseCaptureLost()
void Button::mouseCaptureLost (wxMouseCaptureLostEvent & event) private
{
    wxMouseEvent evt;
    mouseReleased(evt);
}
References mouseReleased().
mouseDown()
void Button::mouseDown (wxMouseEvent & event) private
{
    event.Skip();
    pressedDown = true;
    if (canFocus)
        SetFocus();
    if (!HasCapture())
        CaptureMouse();
}
References canFocus, and pressedDown.
mouseReleased()
void Button::mouseReleased (wxMouseEvent & event) private
{
    event.Skip();
    if (pressedDown) {
        pressedDown = false;
        if (HasCapture())
            ReleaseMouse();
        if (wxRect({0, 0}, GetSize()).Contains(event.GetPosition()))
            sendButtonEvent();
    }
}
References pressedDown, and sendButtonEvent().
Referenced by mouseCaptureLost().
paintEvent()
void Button::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxPaintDC dc(this);
    render(dc);
}
References render().
render()
void Button::render (wxDC & dc) private
{
    StaticBox::render(dc);
    int states = state_handler.states();
    wxSize size = GetSize();
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    // calc content size
    wxSize szIcon;
    wxSize szContent = textSize.GetSize();
    ScalableBitmap icon;
    if (m_selected || ((states & (int)StateColor::State::Hovered) != 0))
        icon = active_icon;
    else
        icon = inactive_icon;
    int padding = 5;
    if (icon.bmp().IsOk()) {
        if (szContent.y > 0) {
            //BBS norrow size between text and icon
            szContent.x += padding;
        }
        szIcon = icon.GetBmpSize();
        szContent.x += szIcon.x;
        if (szIcon.y > szContent.y)
            szContent.y = szIcon.y;
        if (szContent.x > size.x) {
            int d = std::min(padding, szContent.x - size.x);
            padding -= d;
            szContent.x -= d;
        }
    }
    // move to center
    wxRect rcContent = { {0, 0}, size };
    wxSize offset = (size - szContent) / 2;
    if (offset.x < 0) offset.x = 0;
    rcContent.Deflate(offset.x, offset.y);
    // start draw
    wxPoint pt = rcContent.GetLeftTop();
    if (icon.bmp().IsOk()) {
        pt.y += (rcContent.height - szIcon.y) / 2;
        dc.DrawBitmap(icon.bmp(), pt);
        //BBS norrow size between text and icon
        pt.x += szIcon.x + padding;
        pt.y = rcContent.y;
    }
    auto text = GetLabel();
    if (!text.IsEmpty()) {
        if (pt.x + textSize.width > size.x)
            text = wxControl::Ellipsize(text, dc, wxELLIPSIZE_END, size.x - pt.x);
        pt.y += (rcContent.height - textSize.height) / 2;
        dc.SetTextForeground(text_color.colorForStates(states));
#if 0
        dc.SetBrush(*wxLIGHT_GREY);
        dc.SetPen(wxPen(*wxLIGHT_GREY));
        dc.DrawRectangle(pt, textSize.GetSize());
#endif
#ifdef __WXOSX__
        pt.y -= textSize.x / 2;
#endif
        dc.DrawText(text, pt);
    }
}
References active_icon, ScalableBitmap::bmp(), StateColor::colorForStates(), ScalableBitmap::GetBmpSize(), StateColor::Hovered, inactive_icon, m_selected, StaticBox::render(), size, StaticBox::state_handler, StateHandler::states(), text_color, and textSize.
Referenced by paintEvent().
Rescale()
void Button::Rescale ()
{
    if (this->active_icon.bmp().IsOk())
        this->active_icon.msw_rescale();
    if (this->inactive_icon.bmp().IsOk())
        this->inactive_icon.msw_rescale();
    messureSize();
}
References active_icon, ScalableBitmap::bmp(), inactive_icon, messureSize(), and ScalableBitmap::msw_rescale().
Referenced by Slic3r::GUI::StatusPanel::msw_rescale(), Slic3r::GUI::ConnectPrinterDialog::on_dpi_changed(), Slic3r::GUI::PlateSettingsDialog::on_dpi_changed(), Slic3r::GUI::UpdateVersionDialog::on_dpi_changed(), Slic3r::GUI::MediaFilePanel::Rescale(), Slic3r::GUI::PrivacyUpdateDialog::rescale(), Slic3r::GUI::SecondaryCheckDialog::rescale(), Slic3r::GUI::ConfirmBeforeSendDialog::rescale(), and SpinInput::Rescale().
sendButtonEvent()
void Button::sendButtonEvent () private
{
    wxCommandEvent event(wxEVT_COMMAND_BUTTON_CLICKED, GetId());
    event.SetEventObject(this);
    GetEventHandler()->ProcessEvent(event);
}
Referenced by mouseReleased().
SetBackgroundColor()
void StaticBox::SetBackgroundColor (StateColor const & color) inherited
{
    background_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::ParamsPanel::ParamsPanel(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::PublishDialog::create_publish_step_sizer(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::InputIpAddressDialog::on_check_ip_address_failed(), Slic3r::GUI::ColorPickerPopup::on_custom_clr_picker(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), ButtonsListCtrl::OnPaint(), TabButtonsListCtrl::OnPaint(), Slic3r::GUI::ColorPickerPopup::set_def_colour(), and Slic3r::GUI::MonitorPanel::show_status().
SetBackgroundColor2()
void StaticBox::SetBackgroundColor2 (StateColor const & color) inherited
{
    background_color2 = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::background_color2, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::ParamsPanel::ParamsPanel().
SetBackgroundColorNormal()
void StaticBox::SetBackgroundColorNormal (wxColor const & color) inherited
{
    background_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::background_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderColor()
void StaticBox::SetBorderColor (StateColor const & color) inherited
{
    border_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::border_color, StaticBox::state_handler, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), TabCtrl::TabCtrl(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::SelectMachineDialog::Enable_Refresh_Button(), Slic3r::GUI::SelectMachineDialog::Enable_Send_Button(), Slic3r::GUI::BedShapePanel::init_model_panel(), Slic3r::GUI::MonitorPanel::init_tabpanel(), Slic3r::GUI::BedShapePanel::init_texture_panel(), Slic3r::GUI::InputIpAddressDialog::on_ok(), Slic3r::GUI::InputIpAddressDialog::on_text(), and Slic3r::GUI::MonitorPanel::show_status().
SetBorderColorNormal()
void StaticBox::SetBorderColorNormal (wxColor const & color) inherited
{
    border_color.setColorForStates(color, 0);
    Refresh();
}
References StaticBox::border_color, and StateColor::setColorForStates().
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetBorderWidth()
void StaticBox::SetBorderWidth (int width) inherited
{
    border_width = width;
    Refresh();
}
References StaticBox::border_width.
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::StatusBasePanel::create_bed_control(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), and Slic3r::GUI::StatusBasePanel::create_misc_control().
SetCanFocus()
void Button::SetCanFocus (bool canFocus) override
{ this->canFocus = canFocus; }
References canFocus.
Referenced by Slic3r::GUI::MediaPlayCtrl::MediaPlayCtrl().
SetCornerRadius()
void StaticBox::SetCornerRadius (double radius) inherited
{
    this->radius = radius;
    Refresh();
}
References StaticBox::radius.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::ColorPickerPopup::ColorPickerPopup(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::ProgressDialog::Create(), Slic3r::GUI::StatusBasePanel::create_ams_group(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_misc_control(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), SpinInput::createButton(), Slic3r::GUI::StatusPanel::init_scaled_buttons(), Slic3r::GUI::AMSControl::init_scaled_buttons(), Slic3r::GUI::MonitorPanel::init_tabpanel(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::MonitorPanel::msw_rescale(), Slic3r::GUI::ConnectPrinterDialog::on_dpi_changed(), Slic3r::GUI::RecenterDialog::on_dpi_changed(), and Slic3r::GUI::SelectMachineDialog::on_dpi_changed().
SetFont()
bool Button::SetFont (const wxFont & font) override
{
    wxWindow::SetFont(font);
    messureSize();
    Refresh();
    return true;
}
References messureSize().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), TabCtrl::AppendItem(), Slic3r::GUI::ExtrusionCalibration::create(), Create(), Slic3r::GUI::StatusBasePanel::create_bed_control(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), and Slic3r::GUI::MonitorPanel::init_tabpanel().
SetIcon()
void Button::SetIcon (const wxString & icon)
{
    if (!icon.IsEmpty()) {
        //BBS set button icon default size to 20
        this->active_icon = ScalableBitmap(this, icon.ToStdString(), this->active_icon.px_cnt());
    }
    else
    {
        this->active_icon = ScalableBitmap();
    }
    Refresh();
}
References active_icon.
Referenced by Slic3r::GUI::MediaPlayCtrl::Play(), Slic3r::GUI::StatusPanel::show_printing_status(), and Slic3r::GUI::SelectMachineDialog::sys_color_changed().
SetInactiveIcon()
void Button::SetInactiveIcon (const wxString & icon)
{
    if (!icon.IsEmpty()) {
        // BBS set button icon default size to 20
        this->inactive_icon = ScalableBitmap(this, icon.ToStdString(), this->active_icon.px_cnt());
    } else {
        this->inactive_icon = ScalableBitmap();
    }
    Refresh();
}
References inactive_icon.
Referenced by ButtonsListCtrl::InsertPage().
SetLabel()
void Button::SetLabel (const wxString & label) override
{
    wxWindow::SetLabel(label);
    messureSize();
    Refresh();
}
References messureSize().
Referenced by Slic3r::BBLStatusBarSend::change_button_label(), ButtonsListCtrl::SetPageText(), Slic3r::GUI::MediaFilePanel::SetSelecting(), Slic3r::GUI::MonitorPanel::show_status(), Slic3r::GUI::PrivacyUpdateDialog::update_btn_label(), Slic3r::GUI::SecondaryCheckDialog::update_btn_label(), Slic3r::GUI::ConfirmBeforeSendDialog::update_btn_label(), Slic3r::GUI::CalibrationDialog::update_cali(), Slic3r::GUI::StatusPanel::update_cali(), and Slic3r::GUI::SecondaryCheckDialog::update_func_btn().
SetMinSize()
void Button::SetMinSize (const wxSize & size) override
{
    minSize = size;
    messureSize();
}
References messureSize(), minSize, and size.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::BBLStatusBarSend::BBLStatusBarSend(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::ProgressDialog::Create(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::ProgressDialog::DoSetSize(), Slic3r::GUI::StatusPanel::init_scaled_buttons(), Slic3r::GUI::AMSControl::init_scaled_buttons(), Slic3r::GUI::MonitorPanel::init_tabpanel(), ButtonsListCtrl::InsertPage(), Slic3r::BBLStatusBarBind::msw_rescale(), Slic3r::BBLStatusBarSend::msw_rescale(), Slic3r::GUI::MonitorPanel::msw_rescale(), Slic3r::GUI::StatusPanel::msw_rescale(), Slic3r::GUI::MachineInfoPanel::msw_rescale(), Slic3r::GUI::AMSControl::msw_rescale(), Slic3r::GUI::TipsDialog::on_dpi_changed(), Slic3r::GUI::ProjectDropDialog::on_dpi_changed(), Slic3r::GUI::RecenterDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SelectMachineDialog::on_dpi_changed(), Slic3r::GUI::EditDevNameDialog::on_dpi_changed(), and Slic3r::GUI::AMSMaterialsSetting::Show().
SetPaddingSize()
void Button::SetPaddingSize (const wxSize & size)
{
    paddingSize = size;
    messureSize();
}
References messureSize(), paddingSize, and size.
Referenced by TabCtrl::AppendItem().
SetSelected()
void Button::SetSelected (bool selected = true) inline
{ m_selected = selected; }
References m_selected.
Referenced by ButtonsListCtrl::InsertPage().
SetTextColor()
void Button::SetTextColor (StateColor const & color)
{
    text_color = color;
    state_handler.update_binds();
    Refresh();
}
References StaticBox::state_handler, text_color, and StateHandler::update_binds().
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::GUI::CalibrationDialog::CalibrationDialog(), Slic3r::GUI::ConfirmBeforeSendDialog::ConfirmBeforeSendDialog(), Slic3r::GUI::ConnectPrinterDialog::ConnectPrinterDialog(), Slic3r::GUI::EditDevNameDialog::EditDevNameDialog(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MachineInfoPanel::MachineInfoPanel(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::MaxVolumetricSpeed_Test_Dlg(), Slic3r::GUI::PA_Calibration_Dlg::PA_Calibration_Dlg(), Slic3r::GUI::PlateSettingsDialog::PlateSettingsDialog(), Slic3r::GUI::PrivacyUpdateDialog::PrivacyUpdateDialog(), Slic3r::GUI::ProjectDropDialog::ProjectDropDialog(), Slic3r::GUI::PublishDialog::PublishDialog(), Slic3r::GUI::RecenterDialog::RecenterDialog(), Slic3r::GUI::Retraction_Test_Dlg::Retraction_Test_Dlg(), Slic3r::GUI::SecondaryCheckDialog::SecondaryCheckDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), Slic3r::GUI::TipsDialog::TipsDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::VFA_Test_Dlg::VFA_Test_Dlg(), Slic3r::GUI::MsgDialog::add_button(), TabCtrl::AppendItem(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::AMSMaterialsSetting::create(), Slic3r::GUI::ExtrusionCalibration::create(), Slic3r::GUI::ProgressDialog::Create(), Slic3r::GUI::StatusBasePanel::create_bed_control(), WipingDialog::create_btn_sizer(), Slic3r::GUI::StatusBasePanel::create_extruder_control(), Slic3r::GUI::StatusBasePanel::create_machine_control_page(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::AmsReplaceMaterialDialog::create_split_line(), Slic3r::GUI::MonitorPanel::init_tabpanel(), ButtonsListCtrl::InsertPage(), Slic3r::GUI::InputIpAddressDialog::on_check_ip_address_failed(), and Slic3r::GUI::InputIpAddressDialog::on_text().
SetTextColorNormal()
void Button::SetTextColorNormal (wxColor const & color)
{
    text_color.setColorForStates(color, 0);
    Refresh();
}
References StateColor::setColorForStates(), and text_color.
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
SetValue()
void Button::SetValue (bool state)
{
    if (GetValue() == state) return;
    state_handler.set_state(state ? StateHandler::Checked : 0, StateHandler::Checked);
}
References StateHandler::Checked, GetValue(), StateHandler::set_state(), and StaticBox::state_handler.
Referenced by Slic3r::GUI::MediaFilePanel::MediaFilePanel().
Member Data Documentation
active_icon
ScalableBitmap Button::active_icon private
Referenced by Create(), messureSize(), render(), Rescale(), and SetIcon().
background_color
StateColor StaticBox::background_color protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), StaticBox::SetBackgroundColor(), and StaticBox::SetBackgroundColorNormal().
background_color2
StateColor StaticBox::background_color2 protected inherited
Referenced by StaticBox::Create(), StaticBox::doRender(), and StaticBox::SetBackgroundColor2().
border_color
StateColor StaticBox::border_color protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StaticBox::Create(), StaticBox::doRender(), TabCtrl::doRender(), StaticBox::SetBorderColor(), and StaticBox::SetBorderColorNormal().
border_width
int StaticBox::border_width = 1 protected inherited
Referenced by StepCtrl::StepCtrl(), StepIndicator::StepIndicator(), TabCtrl::TabCtrl(), StaticBox::Create(), StaticBox::doRender(), TabCtrl::doRender(), and StaticBox::SetBorderWidth().
buttonHeight
const int Button::buttonHeight = 50 static private
buttonWidth
const int Button::buttonWidth = 200 static private
canFocus
bool Button::canFocus = true private
Referenced by AcceptsFocus(), mouseDown(), and SetCanFocus().
inactive_icon
ScalableBitmap Button::inactive_icon private
Referenced by render(), Rescale(), and SetInactiveIcon().
m_selected
bool Button::m_selected = true private
Referenced by render(), and SetSelected().
minSize
wxSize Button::minSize private
Referenced by messureSize(), and SetMinSize().
paddingSize
wxSize Button::paddingSize private
Referenced by messureSize(), and SetPaddingSize().
pressedDown
bool Button::pressedDown = false private
Referenced by mouseDown(), and mouseReleased().
radius
double StaticBox::radius protected inherited
Referenced by FanSwitchButton::FanSwitchButton(), StepCtrlBase::StepCtrlBase(), TabCtrl::TabCtrl(), StaticBox::doRender(), TabCtrl::doRender(), StaticBox::render(), and StaticBox::SetCornerRadius().
state_handler
StateHandler StaticBox::state_handler protected inherited
Referenced by Create(), StaticBox::Create(), StaticBox::doRender(), StepCtrl::doRender(), StepIndicator::doRender(), TabCtrl::doRender(), GetValue(), render(), ImageSwitchButton::render(), FanSwitchButton::render(), StaticBox::SetBackgroundColor(), StaticBox::SetBackgroundColor2(), StaticBox::SetBorderColor(), SetTextColor(), ImageSwitchButton::SetTextColor(), FanSwitchButton::SetTextColor(), and SetValue().
text_color
StateColor Button::text_color private
Referenced by Create(), render(), SetTextColor(), and SetTextColorNormal().
textSize
wxRect Button::textSize private
Referenced by messureSize(), and render().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/Button.hpp
src/slic3r/GUI/Widgets/Button.cpp