OrcaSlicer: Slic3r::PresetUtils Namespace Reference
Slic3r::PresetUtils Namespace Reference
Functions
const VendorProfile::PrinterModel * system_printer_model (const Preset &preset)
std::string system_printer_bed_model (const Preset &preset)
std::string system_printer_bed_texture (const Preset &preset)
std::string system_printer_hotend_model (const Preset &preset)
Function Documentation
system_printer_bed_model()
std::string Slic3r::PresetUtils::system_printer_bed_model (const Preset & preset)
    {
        std::string out;
        const VendorProfile::PrinterModel* pm = PresetUtils::system_printer_model(preset);
        if (pm != nullptr && !pm->bed_model.empty()) {
            out = Slic3r::data_dir() + "/vendor/" + preset.vendor->id + "/" + pm->bed_model;
            if (!boost::filesystem::exists(boost::filesystem::path(out)))
                out = Slic3r::resources_dir() + "/profiles/" + preset.vendor->id + "/" + pm->bed_model;
        }
        return out;
    }
References Slic3r::VendorProfile::PrinterModel::bed_model, Slic3r::data_dir(), Slic3r::VendorProfile::id, out, Slic3r::resources_dir(), system_printer_model(), and Slic3r::Preset::vendor.
Referenced by Slic3r::GUI::Bed3D::detect_type(), and Slic3r::GUI::GCodeViewer::load().
system_printer_bed_texture()
std::string Slic3r::PresetUtils::system_printer_bed_texture (const Preset & preset)
    {
        std::string out;
        const VendorProfile::PrinterModel* pm = PresetUtils::system_printer_model(preset);
        if (pm != nullptr && !pm->bed_texture.empty()) {
            out = Slic3r::data_dir() + "/vendor/" + preset.vendor->id + "/" + pm->bed_texture;
            if (!boost::filesystem::exists(boost::filesystem::path(out)))
                out = Slic3r::resources_dir() + "/profiles/" + preset.vendor->id + "/" + pm->bed_texture;
        }
        return out;
    }
References Slic3r::VendorProfile::PrinterModel::bed_texture, Slic3r::data_dir(), Slic3r::VendorProfile::id, out, Slic3r::resources_dir(), system_printer_model(), and Slic3r::Preset::vendor.
Referenced by Slic3r::GUI::GCodeViewer::load(), and Slic3r::GUI::Plater::set_bed_shape().
system_printer_hotend_model()
std::string Slic3r::PresetUtils::system_printer_hotend_model (const Preset & preset)
    {
        std::string out;
        const VendorProfile::PrinterModel* pm = PresetUtils::system_printer_model(preset);
        if (pm != nullptr && !pm->hotend_model.empty()) {
            out = Slic3r::data_dir() + "/vendor/" + preset.vendor->id + "/" + pm->hotend_model;
            if (!boost::filesystem::exists(boost::filesystem::path(out)))
                out = Slic3r::resources_dir() + "/profiles/" + preset.vendor->id + "/" + pm->hotend_model;
        }
        if (out.empty() ||!boost::filesystem::exists(boost::filesystem::path(out)))
            out = Slic3r::resources_dir() + "/profiles/hotend.stl";
        return out;
    }
References Slic3r::data_dir(), Slic3r::VendorProfile::PrinterModel::hotend_model, Slic3r::VendorProfile::id, out, Slic3r::resources_dir(), system_printer_model(), and Slic3r::Preset::vendor.
Referenced by Slic3r::GUI::GCodeViewer::init().
system_printer_model()
const VendorProfile::PrinterModel * Slic3r::PresetUtils::system_printer_model (const Preset & preset)
  {
    const VendorProfile::PrinterModel *out = nullptr;
    if (preset.vendor != nullptr) {
      auto *printer_model = preset.config.opt<ConfigOptionString>("printer_model");
      if (printer_model != nullptr && ! printer_model->value.empty()) {
        auto it = std::find_if(preset.vendor->models.begin(), preset.vendor->models.end(), [printer_model](const VendorProfile::PrinterModel &pm) { return pm.id == printer_model->value; });
        if (it != preset.vendor->models.end())
          out = &(*it);
      }
    }
    return out;
  }
References Slic3r::Preset::config, Slic3r::VendorProfile::models, Slic3r::DynamicConfig::opt(), out, Slic3r::printer_model(), and Slic3r::Preset::vendor.
Referenced by Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::PresetBundle::load_installed_filaments(), system_printer_bed_model(), system_printer_bed_texture(), and system_printer_hotend_model().