OrcaSlicer: Slic3r::GUI::Plater Class Reference
Slic3r::GUI::Plater Class Reference
#include <src/slic3r/GUI/Plater.hpp>
Classes
struct priv
class SingleSnapshot
class SuppressSnapshots
class TakeSnapshot
Public Types
using fs_path = boost::filesystem::path
Public Member Functions
Plater (wxWindow *parent, MainFrame *main_frame)
Plater (Plater &&)=delete
Plater (const Plater &)=delete
Plater & operator= (Plater &&)=delete
Plater & operator= (const Plater &)=delete
~Plater ()=default
bool Show (bool show=true)
bool is_project_dirty () const
bool is_presets_dirty () const
void set_plater_dirty (bool is_dirty)
void update_project_dirty_from_presets ()
int save_project_if_dirty (const wxString &reason)
void reset_project_dirty_after_save ()
void reset_project_dirty_initial_presets ()
Sidebar & sidebar ()
const Model & model () const
Model & model ()
const Print & fff_print () const
Print & fff_print ()
const SLAPrint & sla_print () const
SLAPrint & sla_print ()
int new_project (bool skip_confirm=false, bool silent=false, const wxString &project_name=wxString())
void load_project (wxString const &filename="", wxString const &originfile="-")
int save_project (bool saveAs=false)
void import_model_id (const std::string &download_info)
void download_project (const wxString &project_id)
void request_model_download (std::string url)
void request_download_project (std::string project_id)
bool up_to_date (bool saved, bool backup)
bool open_3mf_file (const fs::path &file_path)
int get_3mf_file_count (std::vector< fs::path > paths)
void add_file ()
void add_model (bool imperial_units=false, std::string fname="")
void import_sl1_archive ()
void extract_config_from_project ()
void load_gcode ()
void load_gcode (const wxString &filename)
void reload_gcode_from_disk ()
void refresh_print ()
void calib_pa (const Calib_Params &params)
void calib_flowrate (int pass)
void calib_temp (const Calib_Params &params)
void calib_max_vol_speed (const Calib_Params &params)
void calib_retraction (const Calib_Params &params)
void calib_VFA (const Calib_Params &params)
BuildVolume_Type get_build_volume_type () const
bool only_gcode_mode ()
void set_only_gcode (bool only_gcode)
bool using_exported_file ()
void set_using_exported_file (bool exported_file)
wxString get_project_name ()
void update_all_plate_thumbnails (bool force_update=false)
void invalid_all_plate_thumbnails ()
void force_update_all_plate_thumbnails ()
std::vector< size_t > load_files (const std::vector< boost::filesystem::path > &input_files, LoadStrategy strategy=LoadStrategy::LoadModel|LoadStrategy::LoadConfig, bool ask_multi=false)
std::vector< size_t > load_files (const std::vector< std::string > &input_files, LoadStrategy strategy=LoadStrategy::LoadModel|LoadStrategy::LoadConfig, bool ask_multi=false)
bool load_files (const wxArrayString &filenames)
const wxString & get_last_loaded_gcode () const
void update (bool conside_update_flag=false)
void object_list_changed ()
void stop_jobs ()
bool is_any_job_running () const
void select_view (const std::string &direction)
void select_view_3D (const std::string &name, bool no_slice=true)
bool is_preview_shown () const
bool is_preview_loaded () const
bool is_view3D_shown () const
bool are_view3D_labels_shown () const
void show_view3D_labels (bool show)
bool is_view3D_overhang_shown () const
void show_view3D_overhang (bool show)
bool is_sidebar_collapsed () const
void collapse_sidebar (bool show)
void update_ui_from_settings ()
void select_curr_plate_all ()
void remove_curr_plate_all ()
void select_all ()
void deselect_all ()
void remove (size_t obj_idx)
void reset (bool apply_presets_change=false)
void reset_with_confirm ()
int close_with_confirm (std::function< bool(bool yes_or_no)> second_check=nullptr)
void trigger_restore_project (int skip_confirm=0)
bool delete_object_from_model (size_t obj_idx, bool refresh_immediately=true)
void delete_all_objects_from_model ()
void set_selected_visible (bool visible)
void remove_selected ()
void increase_instances (size_t num=1)
void decrease_instances (size_t num=1)
void set_number_of_copies ()
void fill_bed_with_instances ()
bool is_selection_empty () const
void scale_selection_to_fit_print_volume ()
void convert_unit (ConversionType conv_type)
void cut (size_t obj_idx, size_t instance_idx, std::array< Vec3d, 4 > plane_points, ModelObjectCutAttributes attributes)
void segment (size_t obj_idx, size_t instance_idx, double smoothing_alpha=0.5, int segment_number=5)
void merge (size_t obj_idx, std::vector< int > &vol_indeces)
void send_to_printer (bool isall=false)
void export_gcode (bool prefer_removable)
void export_gcode_3mf (bool export_all=false)
void send_gcode_finish (wxString name)
void export_core_3mf ()
void export_stl (bool extended=false, bool selection_only=false)
int export_3mf (const boost::filesystem::path &output_path=boost::filesystem::path(), SaveStrategy strategy=SaveStrategy::Default, int export_plate_idx=-1, Export3mfProgressFn proFn=nullptr)
void publish_project ()
void reload_from_disk ()
void replace_with_stl ()
void reload_all_from_disk ()
bool has_toolpaths_to_export () const
void export_toolpaths_to_obj () const
void reslice ()
void reslice_SLA_supports (const ModelObject &object, bool postpone_error_messages=false)
void reslice_SLA_hollowing (const ModelObject &object, bool postpone_error_messages=false)
void reslice_SLA_until_step (SLAPrintObjectStep step, const ModelObject &object, bool postpone_error_messages=false)
void clear_before_change_mesh (int obj_idx)
void changed_mesh (int obj_idx)
void changed_object (int obj_idx)
void changed_objects (const std::vector< size_t > &object_idxs)
void schedule_background_process (bool schedule=true)
bool is_background_process_update_scheduled () const
void suppress_background_process (const bool stop_background_process)
int send_gcode (int plate_idx=-1, Export3mfProgressFn proFn=nullptr)
void send_gcode_legacy (int plate_idx=-1, Export3mfProgressFn proFn=nullptr)
int export_config_3mf (int plate_idx=-1, Export3mfProgressFn proFn=nullptr)
void print_job_finished (wxCommandEvent &evt)
void send_job_finished (wxCommandEvent &evt)
void publish_job_finished (wxCommandEvent &evt)
void on_change_color_mode (SimpleEvent &evt)
void eject_drive ()
void take_snapshot (const std::string &snapshot_name)
void take_snapshot (const std::string &snapshot_name, UndoRedo::SnapshotType snapshot_type)
void undo ()
void redo ()
void undo_to (int selection)
void redo_to (int selection)
bool undo_redo_string_getter (const bool is_undo, int idx, const char **out_text)
void undo_redo_topmost_string_getter (const bool is_undo, std::string &out_text)
bool search_string_getter (int idx, const char **label, const char **tooltip)
const Slic3r::UndoRedo::Stack & undo_redo_stack_main () const
void clear_undo_redo_stack_main ()
void enter_gizmos_stack ()
bool leave_gizmos_stack ()
void on_filaments_change (size_t extruders_count)
void on_bed_type_change (BedType bed_type)
bool update_filament_colors_in_full_config ()
void config_change_notification (const DynamicPrintConfig &config, const std::string &key)
void on_config_change (const DynamicPrintConfig &config)
void force_filament_colors_update ()
void force_print_bed_update ()
void on_activate ()
std::vector< std::string > get_extruder_colors_from_plater_config (const GCodeProcessorResult *const result=nullptr) const
std::vector< std::string > get_colors_for_color_print (const GCodeProcessorResult *const result=nullptr) const
void update_menus ()
wxString get_project_filename (const wxString &extension=wxEmptyString) const
wxString get_export_gcode_filename (const wxString &extension=wxEmptyString, bool only_filename=false, bool export_all=false) const
void set_project_filename (const wxString &filename)
bool is_export_gcode_scheduled () const
const Selection & get_selection () const
int get_selected_object_idx ()
bool is_single_full_object_selection () const
GLCanvas3D * canvas3D ()
const GLCanvas3D * canvas3D () const
GLCanvas3D * get_current_canvas3D (bool exclude_preview=false)
GLCanvas3D * get_view3D_canvas3D ()
GLCanvas3D * get_preview_canvas3D ()
GLCanvas3D * get_assmeble_canvas3D ()
void arrange ()
void orient ()
void find_new_position (const ModelInstancePtrs &instances)
void set_prepare_state (int state)
int get_prepare_state ()
void get_print_job_data (PrintPrepareData *data)
int get_print_finished_event ()
int get_send_finished_event ()
int get_publish_finished_event ()
void set_current_canvas_as_dirty ()
void unbind_canvas_event_handlers ()
void reset_canvas_volumes ()
PrinterTechnology printer_technology () const
const DynamicPrintConfig * config () const
bool set_printer_technology (PrinterTechnology printer_technology)
void cut_selection_to_clipboard ()
void copy_selection_to_clipboard ()
void paste_from_clipboard ()
void clone_selection ()
void center_selection ()
void search (bool plater_is_active, Preset::Type type, wxWindow *tag, TextInput *etag, wxWindow *stag)
void mirror (Axis axis)
void split_object ()
void split_volume ()
void optimize_rotation ()
void fill_color (int extruder_id)
void edit_text ()
bool can_edit_text () const
bool can_delete () const
bool can_delete_all () const
bool can_add_model () const
bool can_add_plate () const
bool can_delete_plate () const
bool can_increase_instances () const
bool can_decrease_instances () const
bool can_set_instance_to_object () const
bool can_fix_through_netfabb () const
bool can_simplify () const
bool can_split_to_objects () const
bool can_split_to_volumes () const
bool can_arrange () const
bool can_cut_to_clipboard () const
bool can_layers_editing () const
bool can_paste_from_clipboard () const
bool can_copy_to_clipboard () const
bool can_undo () const
bool can_redo () const
bool can_reload_from_disk () const
bool can_replace_with_stl () const
bool can_mirror () const
bool can_split (bool to_objects) const
bool can_fillcolor () const
bool has_assmeble_view () const
void msw_rescale ()
void sys_color_changed ()
bool init_collapse_toolbar ()
void enable_collapse_toolbar (bool enable)
const Camera & get_camera () const
Camera & get_camera ()
PartPlateList & get_partplate_list ()
void validate_current_plate (bool &model_fits, bool &validate_error)
int select_plate (int plate_index, bool need_slice=false)
void apply_background_progress ()
int select_plate_by_hover_id (int hover_id, bool right_click=false)
int delete_plate (int plate_index=-1)
int select_sliced_plate (int plate_index)
void set_bed_position (Vec2d &pos)
bool is_background_process_slicing () const
void update_slicing_context_to_current_partplate ()
void show_object_info ()
bool show_publish_dialog (bool show=true)
void post_process_string_object_exception (StringObjectException &err)
const BuildVolume & build_volume () const
const GLToolbar & get_collapse_toolbar () const
GLToolbar & get_collapse_toolbar ()
void update_preview_bottom_toolbar ()
void update_preview_moves_slider ()
void enable_preview_moves_slider (bool enable)
void reset_gcode_toolpaths ()
void reset_last_loaded_gcode ()
const Mouse3DController & get_mouse3d_controller () const
Mouse3DController & get_mouse3d_controller ()
void set_bed_shape () const
void set_bed_shape (const Pointfs &shape, const Pointfs &exclude_area, const double printable_height, const std::string &custom_texture, const std::string &custom_model, bool force_as_custom=false) const
const NotificationManager * get_notification_manager () const
NotificationManager * get_notification_manager ()
void show_status_message (std::string s)
void init_notification_manager ()
void bring_instance_forward ()
bool need_update () const
void set_need_update (bool need_update)
bool inside_snapshot_capture ()
void toggle_render_statistic_dialog ()
bool is_render_statistic_dialog_visible () const
void toggle_show_wireframe ()
bool is_show_wireframe () const
void enable_wireframe (bool status)
bool is_wireframe_enabled () const
bool PopupMenu (wxMenu *menu, const wxPoint &pos=wxDefaultPosition)
bool PopupMenu (wxMenu *menu, int x, int y)
bool PopupObjectTable (int object_id, int volume_id, const wxPoint &position)
bool PopupObjectTableBySelection ()
wxMenu * plate_menu ()
wxMenu * object_menu ()
wxMenu * part_menu ()
wxMenu * sla_object_menu ()
wxMenu * default_menu ()
wxMenu * instance_menu ()
wxMenu * layer_menu ()
wxMenu * multi_selection_menu ()
int GetPlateIndexByRightMenuInLeftUI ()
void SetPlateIndexByRightMenuInLeftUI (int)
std::string get_preview_only_filename ()
bool last_arrange_job_is_finished ()
Static Public Member Functions
static void setPrintSpeedTable (Slic3r::GlobalSpeedMap &printSpeedMap)
static void setExtruderParams (std::map< size_t, Slic3r::ExtruderParams > &extParas)
static wxColour get_next_color_for_filament ()
static wxString get_slice_warning_string (GCodeProcessorResult::SliceWarning &warning)
static TriangleMesh combine_mesh_fff (const ModelObject &mo, int instance_id, std::function< void(const std::string &)> notify_func={})
static bool has_illegal_filename_characters (const wxString &name)
static bool has_illegal_filename_characters (const std::string &name)
static void show_illegal_characters_warning (wxWindow *parent)
Public Attributes
std::atomic< bool > m_arrange_running {false}
Private Member Functions
void suppress_snapshots ()
void allow_snapshots ()
void single_snapshots_enter (SingleSnapshot *single)
void single_snapshots_leave (SingleSnapshot *single)
int start_next_slice ()
void _calib_pa_pattern (const Calib_Params &params)
void _calib_pa_tower (const Calib_Params &params)
void _calib_pa_select_added_objects ()
Private Attributes
std::unique_ptr< priv > p
bool m_tracking_popup_menu = false
wxString m_tracking_popup_menu_error_message
wxString m_last_loaded_gcode
bool m_only_gcode { false }
bool m_exported_file { false }
bool skip_thumbnail_invalid { false }
bool m_loading_project {false }
std::string m_preview_only_filename
int m_valid_plates_count { 0 }
Friends
class SuppressBackgroundProcessingUpdate
Detailed Description
Member Typedef Documentation
fs_path
using Slic3r::GUI::Plater::fs_path = boost::filesystem::path
Constructor & Destructor Documentation
Plater() [1/3]
Slic3r::GUI::Plater::Plater (wxWindow * parent, MainFrame * main_frame)
    : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxGetApp().get_min_size())
    , p(new priv(this, main_frame))
{
    // Initialization performed in the private c-tor
    enable_wireframe(false);
}
References enable_wireframe().
Plater() [2/3]
Slic3r::GUI::Plater::Plater (Plater &&) delete
Plater() [3/3]
Slic3r::GUI::Plater::Plater (const Plater &) delete
~Plater()
Slic3r::GUI::Plater::~Plater () default
Member Function Documentation
_calib_pa_pattern()
void Slic3r::GUI::Plater::_calib_pa_pattern (const Calib_Params & params) private
{
    // add "handle" cube
    sidebar().obj_list()->load_generic_subobject("Cube", ModelVolumeType::INVALID);
    orient();
    changed_objects({ 0 });
    _calib_pa_select_added_objects();
    const DynamicPrintConfig& printer_config = wxGetApp().preset_bundle->printers.get_edited_preset().config;
    DynamicPrintConfig& print_config = wxGetApp().preset_bundle->prints.get_edited_preset().config;
    double nozzle_diameter = printer_config.option<ConfigOptionFloats>("nozzle_diameter")->get_at(0);
    for (const auto opt : SuggestedConfigCalibPAPattern().float_pairs) {
        print_config.set_key_value(
            opt.first,
            new ConfigOptionFloat(opt.second)
        );
    }
    print_config.set_key_value(
        "outer_wall_speed",
        new ConfigOptionFloat(CalibPressureAdvance::find_optimal_PA_speed(
            wxGetApp().preset_bundle->full_config(), print_config.get_abs_value("line_width", nozzle_diameter),
            print_config.get_abs_value("layer_height"), 0)));
    for (const auto opt : SuggestedConfigCalibPAPattern().nozzle_ratio_pairs) {
        print_config.set_key_value(
            opt.first,
            new ConfigOptionFloatOrPercent(nozzle_diameter * opt.second / 100, false)
        );
    }
    for (const auto opt : SuggestedConfigCalibPAPattern().int_pairs) {
        print_config.set_key_value(
            opt.first,
            new ConfigOptionInt(opt.second)
        );
    }
    print_config.set_key_value(
        SuggestedConfigCalibPAPattern().brim_pair.first,
        new ConfigOptionEnum<BrimType>(SuggestedConfigCalibPAPattern().brim_pair.second)
    );
    wxGetApp().get_tab(Preset::TYPE_PRINT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINT)->reload_config();
    const DynamicPrintConfig full_config = wxGetApp().preset_bundle->full_config();
    PresetBundle* preset_bundle = wxGetApp().preset_bundle;
    const bool is_bbl_machine = preset_bundle->printers.get_edited_preset().has_lidar(preset_bundle);
    const Vec3d plate_origin = get_partplate_list().get_current_plate_origin();
    CalibPressureAdvancePattern pa_pattern(
        params,
        full_config,
        is_bbl_machine,
        model(),
        plate_origin
    );
    // scale cube to suit test
    GizmoObjectManipulation& giz_obj_manip = p->view3D->get_canvas3d()->
        get_gizmos_manager().get_object_manipulation();
    giz_obj_manip.set_uniform_scaling(true);
    giz_obj_manip.on_change(
        "size",
        0,
        pa_pattern.handle_xy_size()
    );
    giz_obj_manip.set_uniform_scaling(false);
    giz_obj_manip.on_change(
        "size",
        2,
        pa_pattern.max_layer_z()
    );
    // start with pattern centered on plate
    center_selection();
    const Vec3d plate_center = get_partplate_list().get_curr_plate()->get_center_origin();
    giz_obj_manip.on_change(
        "position",
        0,
        plate_center.x() - (pa_pattern.print_size_x() / 2)
    );
    giz_obj_manip.on_change(
        "position",
        1,
        plate_center.y() -
            (pa_pattern.print_size_y() / 2) -
            pa_pattern.handle_spacing()
    );
    pa_pattern.generate_custom_gcodes(
        full_config,
        is_bbl_machine,
        model(),
        plate_origin
    );
    model().calib_pa_pattern = std::make_unique<CalibPressureAdvancePattern>(pa_pattern);
    changed_objects({ 0 });
}
References _calib_pa_select_added_objects(), Slic3r::SuggestedConfigCalibPAPattern::brim_pair, Slic3r::Model::calib_pa_pattern, center_selection(), changed_objects(), Slic3r::CalibPressureAdvance::find_optimal_PA_speed(), Slic3r::SuggestedConfigCalibPAPattern::float_pairs, Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes(), Slic3r::ConfigBase::get_abs_value(), Slic3r::GUI::PartPlate::get_center_origin(), Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::PartPlateList::get_current_plate_origin(), Slic3r::PresetCollection::get_edited_preset(), get_partplate_list(), Slic3r::CalibPressureAdvancePattern::handle_spacing(), Slic3r::CalibPressureAdvancePattern::handle_xy_size(), Slic3r::Preset::has_lidar(), Slic3r::SuggestedConfigCalibPAPattern::int_pairs, Slic3r::INVALID, Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::CalibPressureAdvancePattern::max_layer_z(), model(), Slic3r::SuggestedConfigCalibPAPattern::nozzle_ratio_pairs, Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::GizmoObjectManipulation::on_change(), Slic3r::ConfigBase::option(), orient(), p, Slic3r::CalibPressureAdvancePattern::print_size_x(), Slic3r::CalibPressureAdvancePattern::print_size_y(), Slic3r::GUI::printer_config(), Slic3r::PresetBundle::printers, Slic3r::DynamicConfig::set_key_value(), Slic3r::GUI::GizmoObjectManipulation::set_uniform_scaling(), sidebar(), and Slic3r::Preset::TYPE_PRINT.
Referenced by calib_pa().
_calib_pa_select_added_objects()
void Slic3r::GUI::Plater::_calib_pa_select_added_objects () private
{
    // update printable state for new volumes on canvas3D
    wxGetApp().plater()->canvas3D()->update_instance_printable_state_for_objects({0});
    Selection& selection = p->view3D->get_canvas3d()->get_selection();
    selection.clear();
    selection.add_object(0, false);
    // BBS: update object list selection
    p->sidebar->obj_list()->update_selections();
    selection.notify_instance_update(-1, -1);
    if (p->view3D->get_canvas3d()->get_gizmos_manager().is_enabled()) {
        // this is required because the selected object changed and the flatten on face an sla support gizmos need to be updated accordingly
        p->view3D->get_canvas3d()->update_gizmos_on_off_state();
    }
}
References Slic3r::GUI::Selection::add_object(), Slic3r::GUI::Selection::clear(), Slic3r::GUI::Selection::notify_instance_update(), and p.
Referenced by _calib_pa_pattern(), and _calib_pa_tower().
_calib_pa_tower()
void Slic3r::GUI::Plater::_calib_pa_tower (const Calib_Params & params) private
{
    add_model(false, Slic3r::resources_dir() + "/calib/PressureAdvance/tower_with_seam.stl");
    auto print_config = &wxGetApp().preset_bundle->prints.get_edited_preset().config;
    auto printer_config = &wxGetApp().preset_bundle->printers.get_edited_preset().config;
    auto filament_config = &wxGetApp().preset_bundle->filaments.get_edited_preset().config;
    const double nozzle_diameter = printer_config->option<ConfigOptionFloats>("nozzle_diameter")->get_at(0);
    filament_config->set_key_value("slow_down_layer_time", new ConfigOptionFloats{ 1.0f });
    print_config->set_key_value("default_jerk", new ConfigOptionFloat(1.0f));
    print_config->set_key_value("outer_wall_jerk", new ConfigOptionFloat(1.0f));
    print_config->set_key_value("inner_wall_jerk", new ConfigOptionFloat(1.0f));
    auto full_config = wxGetApp().preset_bundle->full_config();
    auto wall_speed = CalibPressureAdvance::find_optimal_PA_speed(
        full_config, full_config.get_abs_value("line_width", nozzle_diameter),
        full_config.get_abs_value("layer_height"), 0);
    print_config->set_key_value("outer_wall_speed", new ConfigOptionFloat(wall_speed));
    print_config->set_key_value("inner_wall_speed", new ConfigOptionFloat(wall_speed));
    // print_config->set_key_value("wall_generator", new ConfigOptionEnum<PerimeterGeneratorType>(PerimeterGeneratorType::Classic));
    const auto _wall_generator = print_config->option<ConfigOptionEnum<PerimeterGeneratorType>>("wall_generator");
    if (_wall_generator->value == PerimeterGeneratorType::Arachne)
        print_config->set_key_value("wall_transition_angle", new ConfigOptionFloat(25));
    model().objects[0]->config.set_key_value("seam_position", new ConfigOptionEnum<SeamPosition>(spRear));
    changed_objects({ 0 });
    wxGetApp().get_tab(Preset::TYPE_PRINT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINTER)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINT)->reload_config();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->reload_config();
    wxGetApp().get_tab(Preset::TYPE_PRINTER)->reload_config();
    auto new_height = std::ceil((params.end - params.start) / params.step) + 1;
    auto obj_bb = model().objects[0]->bounding_box();
    if (new_height < obj_bb.size().z()) {
        std::array<Vec3d, 4> plane_pts = get_cut_plane(obj_bb, new_height);
        cut(0, 0, plane_pts, ModelObjectCutAttribute::KeepLower);
    }
    _calib_pa_select_added_objects();
}
References _calib_pa_select_added_objects(), add_model(), Slic3r::Arachne, changed_objects(), cut(), Slic3r::Calib_Params::end, Slic3r::CalibPressureAdvance::find_optimal_PA_speed(), Slic3r::GUI::get_cut_plane(), Slic3r::KeepLower, model(), Slic3r::Model::objects, Slic3r::ConfigBase::option(), Slic3r::GUI::printer_config(), Slic3r::resources_dir(), Slic3r::spRear, Slic3r::Calib_Params::start, Slic3r::Calib_Params::step, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, and Slic3r::Preset::TYPE_PRINTER.
Referenced by calib_pa().
add_file()
void Slic3r::GUI::Plater::add_file ()
{
    wxArrayString input_files;
    wxGetApp().import_model(this, input_files);
    if (input_files.empty()) return;
    std::vector<fs::path> paths;
    for (const auto &file : input_files) paths.emplace_back(into_path(file));
    std::string snapshot_label;
    assert(!paths.empty());
    snapshot_label = "Import Objects";
    snapshot_label += ": ";
    snapshot_label += encode_path(paths.front().filename().string().c_str());
    for (size_t i = 1; i < paths.size(); ++i) {
        snapshot_label += ", ";
        snapshot_label += encode_path(paths[i].filename().string().c_str());
    }
    // BBS: check file types
    auto loadfiles_type  = LoadFilesType::NoFile;
    auto amf_files_count = get_3mf_file_count(paths);
    if (paths.size() > 1 && amf_files_count < paths.size()) { loadfiles_type = LoadFilesType::Multiple3MFOther; }
    if (paths.size() > 1 && amf_files_count == paths.size()) { loadfiles_type = LoadFilesType::Multiple3MF; }
    if (paths.size() > 1 && amf_files_count == 0) { loadfiles_type = LoadFilesType::MultipleOther; }
    if (paths.size() == 1 && amf_files_count == 1) { loadfiles_type = LoadFilesType::Single3MF; };
    if (paths.size() == 1 && amf_files_count == 0) { loadfiles_type = LoadFilesType::SingleOther; };
    auto first_file = std::vector<fs::path>{};
    auto tmf_file   = std::vector<fs::path>{};
    auto other_file = std::vector<fs::path>{};
    switch (loadfiles_type)
    {
    case LoadFilesType::Single3MF:
        open_3mf_file(paths[0]);
      break;
    case LoadFilesType::SingleOther: {
        Plater::TakeSnapshot snapshot(this, snapshot_label);
        if (!load_files(paths, LoadStrategy::LoadModel, false).empty()) { wxGetApp().mainframe->update_title(); }
        break;
    }
    case LoadFilesType::Multiple3MF:
        first_file = std::vector<fs::path>{paths[0]};
        for (auto i = 0; i < paths.size(); i++) {
            if (i > 0) { other_file.push_back(paths[i]); }
        };
        open_3mf_file(first_file[0]);
        if (!load_files(other_file, LoadStrategy::LoadModel).empty()) { wxGetApp().mainframe->update_title(); }
        break;
    case LoadFilesType::MultipleOther: {
        Plater::TakeSnapshot snapshot(this, snapshot_label);
        if (!load_files(paths, LoadStrategy::LoadModel, true).empty()) {
            wxGetApp().mainframe->update_title();
        }
        break;
    }
    case LoadFilesType::Multiple3MFOther:
        for (const auto &path : paths) {
            if (wxString(encode_path(path.filename().string().c_str())).EndsWith("3mf")) {
                if (first_file.size() <= 0)
                    first_file.push_back(path);
                else
                    tmf_file.push_back(path);
            } else {
                other_file.push_back(path);
            }
        }
        open_3mf_file(first_file[0]);
        load_files(tmf_file, LoadStrategy::LoadModel);
        if (!load_files(other_file, LoadStrategy::LoadModel, false).empty()) { wxGetApp().mainframe->update_title(); }
        break;
    default:break;
    }
}
References Slic3r::empty(), Slic3r::encode_path(), get_3mf_file_count(), Slic3r::GUI::into_path(), load_files(), Slic3r::LoadModel, Slic3r::GUI::Multiple3MF, Slic3r::GUI::Multiple3MFOther, Slic3r::GUI::MultipleOther, Slic3r::GUI::NoFile, open_3mf_file(), Slic3r::GUI::Single3MF, and Slic3r::GUI::SingleOther.
add_model()
void Slic3r::GUI::Plater::add_model (bool imperial_units = false, std::string fname = "")
{
    std::vector<fs::path> paths;
    if(fname.empty()){
    wxArrayString input_files;
        wxGetApp().import_model(this, input_files);
        if (input_files.empty())
            return;
        for (const auto &file : input_files)
            paths.emplace_back(into_path(file));
    }
    else{
        paths.emplace_back(fname);
    }
    std::string snapshot_label;
    assert(! paths.empty());
    if (paths.size() == 1) {
        snapshot_label = "Import Object";
        snapshot_label += ": ";
        snapshot_label += encode_path(paths.front().filename().string().c_str());
    } else {
        snapshot_label = "Import Objects";
        snapshot_label += ": ";
        snapshot_label += paths.front().filename().string().c_str();
        for (size_t i = 1; i < paths.size(); ++ i) {
            snapshot_label += ", ";
            snapshot_label += encode_path(paths[i].filename().string().c_str());
        }
    }
    Plater::TakeSnapshot snapshot(this, snapshot_label);
    // BBS: check file types
    auto loadfiles_type  = LoadFilesType::NoFile;
    auto amf_files_count = get_3mf_file_count(paths);
    if (paths.size() > 1 && amf_files_count < paths.size()) { loadfiles_type = LoadFilesType::Multiple3MFOther; }
    if (paths.size() > 1 && amf_files_count == paths.size()) { loadfiles_type = LoadFilesType::Multiple3MF; }
    if (paths.size() > 1 && amf_files_count == 0) { loadfiles_type = LoadFilesType::MultipleOther; }
    if (paths.size() == 1 && amf_files_count == 1) { loadfiles_type = LoadFilesType::Single3MF; };
    if (paths.size() == 1 && amf_files_count == 0) { loadfiles_type = LoadFilesType::SingleOther; };
    bool ask_multi = false;
    if (loadfiles_type == LoadFilesType::MultipleOther)
        ask_multi = true;
    auto strategy = LoadStrategy::LoadModel;
    if (imperial_units) strategy = strategy | LoadStrategy::ImperialUnits;
    if (!load_files(paths, strategy, ask_multi).empty()) {
        if (get_project_name() == _L("Untitled") && paths.size() > 0) {
            p->set_project_filename(wxString::FromUTF8(paths[0].string()));
        }
        wxGetApp().mainframe->update_title();
    }
}
References _L, Slic3r::empty(), Slic3r::encode_path(), get_3mf_file_count(), get_project_name(), Slic3r::ImperialUnits, Slic3r::GUI::into_path(), load_files(), Slic3r::LoadModel, Slic3r::GUI::Multiple3MF, Slic3r::GUI::Multiple3MFOther, Slic3r::GUI::MultipleOther, Slic3r::GUI::NoFile, p, Slic3r::GUI::Single3MF, and Slic3r::GUI::SingleOther.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), _calib_pa_tower(), calib_flowrate(), calib_max_vol_speed(), calib_pa(), calib_retraction(), calib_temp(), and calib_VFA().
allow_snapshots()
void Slic3r::GUI::Plater::allow_snapshots () private
{ p->allow_snapshots(); }
References p.
Referenced by Slic3r::GUI::Plater::SuppressSnapshots::~SuppressSnapshots(), and Slic3r::GUI::Plater::TakeSnapshot::~TakeSnapshot().
apply_background_progress()
void Slic3r::GUI::Plater::apply_background_progress ()
{
    PartPlate* part_plate = p->partplate_list.get_curr_plate();
    int plate_index = p->partplate_list.get_curr_plate_index();
    bool result_valid = part_plate->is_slice_result_valid();
    //always apply the current plate's print
    Print::ApplyStatus invalidated = p->background_process.apply(this->model(), wxGetApp().preset_bundle->full_config());
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: plate %2%, after apply, invalidated= %3%, previous result_valid %4% ") % __LINE__ % plate_index % invalidated % result_valid;
    if (invalidated & PrintBase::APPLY_STATUS_INVALIDATED)
    {
        part_plate->update_slice_result_valid_state(false);
        //p->ready_to_slice = true;
        p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, true);
    }
}
References Slic3r::PrintBase::APPLY_STATUS_INVALIDATED, Slic3r::GUI::MainFrame::eEventPlateUpdate, Slic3r::GUI::PartPlate::is_slice_result_valid(), model(), p, and Slic3r::GUI::PartPlate::update_slice_result_valid_state().
Referenced by Slic3r::GUI::MainFrame::MainFrame().
are_view3D_labels_shown()
bool Slic3r::GUI::Plater::are_view3D_labels_shown () const
{ return p->are_view3D_labels_shown(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_default_menu().
arrange()
void Slic3r::GUI::Plater::arrange ()
{
    if (!p->m_ui_jobs.is_any_running()) {
        p->m_ui_jobs.arrange();
    }
}
References p.
Referenced by Slic3r::GUI::MenuFactory::create_plate_menu(), increase_instances(), and select_plate_by_hover_id().
bring_instance_forward()
void Slic3r::GUI::Plater::bring_instance_forward ()
{
    p->bring_instance_forward();
}
References p.
build_volume()
const BuildVolume & Slic3r::GUI::Plater::build_volume () const
{
    return p->bed.build_volume();
}
References p.
Referenced by Slic3r::GUI::bed_stride_x(), Slic3r::GUI::bed_stride_y(), find_new_position(), and Slic3r::GUI::Plater::priv::update_print_volume_state().
calib_flowrate()
void Slic3r::GUI::Plater::calib_flowrate (int pass)
— scale —
{
    if (pass != 1 && pass != 2)
        return;
    const auto calib_name = wxString::Format(L"Flowrate Test - Pass%d", pass);
    new_project(false, false, calib_name);
    wxGetApp().mainframe->select_tab(size_t(MainFrame::tp3DEditor));
    if(pass == 1)
        add_model(false, (boost::filesystem::path(Slic3r::resources_dir()) / "calib" / "filament_flow" / "flowrate-test-pass1.3mf").string());
    else
        add_model(false, (boost::filesystem::path(Slic3r::resources_dir()) / "calib" / "filament_flow" / "flowrate-test-pass2.3mf").string());
    auto print_config = &wxGetApp().preset_bundle->prints.get_edited_preset().config;
    auto printerConfig = &wxGetApp().preset_bundle->printers.get_edited_preset().config;
    auto filament_config = &wxGetApp().preset_bundle->filaments.get_edited_preset().config;
    // model is created for a 0.4 nozzle, scale z with nozzle size.
    const ConfigOptionFloats* nozzle_diameter_config = printerConfig->option<ConfigOptionFloats>("nozzle_diameter");
    assert(nozzle_diameter_config->values.size() > 0);
    float nozzle_diameter = nozzle_diameter_config->values[0];
    float xyScale = nozzle_diameter / 0.6;
    //scale z to have 7 layers
    double first_layer_height = print_config->option<ConfigOptionFloat>("initial_layer_print_height")->value;
    double layer_height = nozzle_diameter / 2.0; // prefer 0.2 layer height for 0.4 nozzle
    first_layer_height = std::max(first_layer_height, layer_height);
    float zscale = (first_layer_height + 6 * layer_height) / 1.4;
    // only enlarge
    if (xyScale > 1.2) {
        for (auto _obj : model().objects)
            _obj->scale(xyScale, xyScale, zscale);
    }
    else {
        for (auto _obj : model().objects)
            _obj->scale(1, 1, zscale);
    }
    Flow infill_flow = Flow(nozzle_diameter * 1.2f, layer_height, nozzle_diameter);
    double filament_max_volumetric_speed = filament_config->option<ConfigOptionFloats>("filament_max_volumetric_speed")->get_at(0);
    double max_infill_speed = filament_max_volumetric_speed / (infill_flow.mm3_per_mm() * (pass == 1 ? 1.2 : 1));
    double internal_solid_speed = std::floor(std::min(print_config->opt_float("internal_solid_infill_speed"), max_infill_speed));
    double top_surface_speed = std::floor(std::min(print_config->opt_float("top_surface_speed"), max_infill_speed));
    // adjust parameters
    for (auto _obj : model().objects) {
        _obj->ensure_on_bed();
        _obj->config.set_key_value("wall_loops", new ConfigOptionInt(3));
        _obj->config.set_key_value("only_one_wall_top", new ConfigOptionBool(true));
        _obj->config.set_key_value("sparse_infill_density", new ConfigOptionPercent(35));
        _obj->config.set_key_value("bottom_shell_layers", new ConfigOptionInt(1));
        _obj->config.set_key_value("top_shell_layers", new ConfigOptionInt(5));
        _obj->config.set_key_value("detect_thin_wall", new ConfigOptionBool(true));
        _obj->config.set_key_value("filter_out_gap_fill", new ConfigOptionFloat(0));
        _obj->config.set_key_value("sparse_infill_pattern", new ConfigOptionEnum<InfillPattern>(ipRectilinear));
        _obj->config.set_key_value("top_surface_line_width", new ConfigOptionFloatOrPercent(nozzle_diameter * 1.2f, false));
        _obj->config.set_key_value("internal_solid_infill_line_width", new ConfigOptionFloatOrPercent(nozzle_diameter * 1.2f, false));
        _obj->config.set_key_value("top_surface_pattern", new ConfigOptionEnum<InfillPattern>(ipMonotonic));
        _obj->config.set_key_value("top_solid_infill_flow_ratio", new ConfigOptionFloat(1.0f));
        _obj->config.set_key_value("top_surface_pattern", new ConfigOptionEnum<InfillPattern>(ipMonotonic));
        _obj->config.set_key_value("infill_direction", new ConfigOptionFloat(45));
        _obj->config.set_key_value("ironing_type", new ConfigOptionEnum<IroningType>(IroningType::NoIroning));
        _obj->config.set_key_value("internal_solid_infill_speed", new ConfigOptionFloat(internal_solid_speed));
        _obj->config.set_key_value("top_surface_speed", new ConfigOptionFloat(top_surface_speed));
        // extract flowrate from name, filename format: flowrate_xxx
        std::string obj_name = _obj->name;
        assert(obj_name.length() > 9);
        obj_name = obj_name.substr(9);
        if (obj_name[0] == 'm')
            obj_name[0] = '-';
        auto modifier = stof(obj_name);
        _obj->config.set_key_value("print_flow_ratio", new ConfigOptionFloat(1.0f + modifier/100.f));
    }
    print_config->set_key_value("layer_height", new ConfigOptionFloat(layer_height));
    print_config->set_key_value("initial_layer_print_height", new ConfigOptionFloat(first_layer_height));
    print_config->set_key_value("reduce_crossing_wall", new ConfigOptionBool(true));
    //filament_config->set_key_value("filament_max_volumetric_speed", new ConfigOptionFloats{ 9. });
    wxGetApp().get_tab(Preset::TYPE_PRINT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINTER)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINT)->reload_config();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->reload_config();
    wxGetApp().get_tab(Preset::TYPE_PRINTER)->reload_config();
}
References add_model(), Slic3r::ipMonotonic, Slic3r::ipRectilinear, L, Slic3r::GUI::layer_height, Slic3r::Flow::mm3_per_mm(), model(), new_project(), Slic3r::NoIroning, Slic3r::Model::objects, Slic3r::resources_dir(), Slic3r::top_surface_speed(), Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, and Slic3r::ConfigOptionVector< T >::values.
calib_max_vol_speed()
void Slic3r::GUI::Plater::calib_max_vol_speed (const Calib_Params & params)
{
    const auto calib_vol_speed_name = wxString::Format(L"Max volumetric speed test");
    new_project(false, false, calib_vol_speed_name);
    wxGetApp().mainframe->select_tab(size_t(MainFrame::tp3DEditor));
    if (params.mode != CalibMode::Calib_Vol_speed_Tower)
        return;
    add_model(false, Slic3r::resources_dir() + "/calib/volumetric_speed/SpeedTestStructure.step");
    auto print_config = &wxGetApp().preset_bundle->prints.get_edited_preset().config;
    auto filament_config = &wxGetApp().preset_bundle->filaments.get_edited_preset().config;
    auto printer_config = &wxGetApp().preset_bundle->printers.get_edited_preset().config;
    auto obj = model().objects[0];
    auto bed_shape = printer_config->option<ConfigOptionPoints>("printable_area")->values;
    BoundingBoxf bed_ext = get_extents(bed_shape);
    auto scale_obj = (bed_ext.size().x() - 10) / obj->bounding_box().size().x();
    if (scale_obj < 1.0)
        obj->scale(scale_obj, 1, 1);
    const ConfigOptionFloats* nozzle_diameter_config = printer_config->option<ConfigOptionFloats>("nozzle_diameter");
    assert(nozzle_diameter_config->values.size() > 0);
    double nozzle_diameter = nozzle_diameter_config->values[0];
    double line_width = nozzle_diameter * 1.75;
    double layer_height = nozzle_diameter * 0.8;
    auto max_lh = printer_config->option<ConfigOptionFloats>("max_layer_height");
    if (max_lh->values[0] < layer_height)
        max_lh->values[0] = { layer_height };
    filament_config->set_key_value("filament_max_volumetric_speed", new ConfigOptionFloats { 200 });
    filament_config->set_key_value("slow_down_layer_time", new ConfigOptionFloats{0.0});
    print_config->set_key_value("enable_overhang_speed", new ConfigOptionBool { false });
    print_config->set_key_value("timelapse_type", new ConfigOptionEnum<TimelapseType>(tlTraditional));
    print_config->set_key_value("wall_loops", new ConfigOptionInt(1));
    print_config->set_key_value("top_shell_layers", new ConfigOptionInt(0));
    print_config->set_key_value("bottom_shell_layers", new ConfigOptionInt(1));
    print_config->set_key_value("sparse_infill_density", new ConfigOptionPercent(0));
    print_config->set_key_value("spiral_mode", new ConfigOptionBool(true));
    print_config->set_key_value("outer_wall_line_width", new ConfigOptionFloatOrPercent(line_width, false));
    print_config->set_key_value("initial_layer_print_height", new ConfigOptionFloat(layer_height));
    print_config->set_key_value("layer_height", new ConfigOptionFloat(layer_height));
    obj->config.set_key_value("brim_type", new ConfigOptionEnum<BrimType>(btOuterAndInner));
    obj->config.set_key_value("brim_width", new ConfigOptionFloat(3.0));
    obj->config.set_key_value("brim_object_gap", new ConfigOptionFloat(0.0));
    changed_objects({ 0 });
    wxGetApp().get_tab(Preset::TYPE_PRINT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINTER)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINT)->reload_config();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->reload_config();
    wxGetApp().get_tab(Preset::TYPE_PRINTER)->reload_config();
    //  cut upper
    auto obj_bb = obj->bounding_box();
    auto height = (params.end - params.start + 1) / params.step;
    if (height < obj_bb.size().z()) {
        std::array<Vec3d, 4> plane_pts = get_cut_plane(obj_bb, height);
        cut(0, 0, plane_pts, ModelObjectCutAttribute::KeepLower);
    }
    auto new_params = params;
    auto mm3_per_mm = Flow(line_width, layer_height, nozzle_diameter).mm3_per_mm() *
                      filament_config->option<ConfigOptionFloats>("filament_flow_ratio")->get_at(0);
    new_params.end = params.end / mm3_per_mm;
    new_params.start = params.start / mm3_per_mm;
    new_params.step = params.step / mm3_per_mm;
    p->background_process.fff_print()->set_calib_params(new_params);
}
References add_model(), Slic3r::btOuterAndInner, Slic3r::Calib_Vol_speed_Tower, changed_objects(), cut(), Slic3r::Calib_Params::end, Slic3r::GUI::get_cut_plane(), Slic3r::get_extents(), Slic3r::KeepLower, L, Slic3r::GUI::layer_height, Slic3r::Flow::mm3_per_mm(), Slic3r::Calib_Params::mode, model(), new_project(), Slic3r::Model::objects, Slic3r::ConfigBase::option(), p, Slic3r::GUI::printer_config(), Slic3r::resources_dir(), Slic3r::Calib_Params::start, Slic3r::Calib_Params::step, Slic3r::tlTraditional, Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, and Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start().
calib_pa()
void Slic3r::GUI::Plater::calib_pa (const Calib_Params & params)
{
    const auto calib_pa_name = wxString::Format(L"Pressure Advance Test");
    new_project(false, false, calib_pa_name);
    wxGetApp().mainframe->select_tab(size_t(MainFrame::tp3DEditor));
    switch (params.mode) {
        case CalibMode::Calib_PA_Line:
            add_model(false, Slic3r::resources_dir() + "/calib/PressureAdvance/pressure_advance_test.stl");
            break;
        case CalibMode::Calib_PA_Pattern:
            _calib_pa_pattern(params);
            break;
        case CalibMode::Calib_PA_Tower:
            _calib_pa_tower(params);
            break;
        default: break;
    }
    p->background_process.fff_print()->set_calib_params(params);
}
References _calib_pa_pattern(), _calib_pa_tower(), add_model(), Slic3r::Calib_PA_Line, Slic3r::Calib_PA_Pattern, Slic3r::Calib_PA_Tower, L, Slic3r::Calib_Params::mode, new_project(), p, Slic3r::resources_dir(), and Slic3r::GUI::MainFrame::tp3DEditor.
Referenced by Slic3r::GUI::PA_Calibration_Dlg::on_start().
calib_retraction()
void Slic3r::GUI::Plater::calib_retraction (const Calib_Params & params)
{
    const auto calib_retraction_name = wxString::Format(L"Retraction test");
    new_project(false, false, calib_retraction_name);
    wxGetApp().mainframe->select_tab(size_t(MainFrame::tp3DEditor));
    if (params.mode != CalibMode::Calib_Retraction_tower)
        return;
    add_model(false, Slic3r::resources_dir() + "/calib/retraction/retraction_tower.stl");
    auto print_config = &wxGetApp().preset_bundle->prints.get_edited_preset().config;
    auto filament_config = &wxGetApp().preset_bundle->filaments.get_edited_preset().config;
    auto printer_config = &wxGetApp().preset_bundle->printers.get_edited_preset().config;
    auto obj = model().objects[0];
    double layer_height = 0.2;
    auto max_lh = printer_config->option<ConfigOptionFloats>("max_layer_height");
    if (max_lh->values[0] < layer_height)
        max_lh->values[0] = { layer_height };
    obj->config.set_key_value("wall_loops", new ConfigOptionInt(2));
    obj->config.set_key_value("top_shell_layers", new ConfigOptionInt(0));
    obj->config.set_key_value("bottom_shell_layers", new ConfigOptionInt(3));
    obj->config.set_key_value("sparse_infill_density", new ConfigOptionPercent(0));
    obj->config.set_key_value("initial_layer_print_height", new ConfigOptionFloat(layer_height));
    obj->config.set_key_value("layer_height", new ConfigOptionFloat(layer_height));
    changed_objects({ 0 });
    //  cut upper
    auto obj_bb = obj->bounding_box();
    auto height = 1.0 + 0.4 + ((params.end - params.start)) / params.step;
    if (height < obj_bb.size().z()) {
        std::array<Vec3d, 4> plane_pts = get_cut_plane(obj_bb, height);
        cut(0, 0, plane_pts, ModelObjectCutAttribute::KeepLower);
    }
    p->background_process.fff_print()->set_calib_params(params);
}
References add_model(), Slic3r::Calib_Retraction_tower, changed_objects(), cut(), Slic3r::Calib_Params::end, Slic3r::GUI::get_cut_plane(), Slic3r::KeepLower, L, Slic3r::GUI::layer_height, Slic3r::Calib_Params::mode, model(), new_project(), Slic3r::Model::objects, Slic3r::ConfigBase::option(), p, Slic3r::GUI::printer_config(), Slic3r::resources_dir(), Slic3r::Calib_Params::start, Slic3r::Calib_Params::step, Slic3r::GUI::MainFrame::tp3DEditor, and Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::Retraction_Test_Dlg::on_start().
calib_temp()
void Slic3r::GUI::Plater::calib_temp (const Calib_Params & params)
{
    const auto calib_temp_name = wxString::Format(L"Nozzle temperature test");
    new_project(false, false, calib_temp_name);
    wxGetApp().mainframe->select_tab(size_t(MainFrame::tp3DEditor));
    if (params.mode != CalibMode::Calib_Temp_Tower)
        return;
    add_model(false, Slic3r::resources_dir() + "/calib/temperature_tower/temperature_tower.stl");
    auto filament_config = &wxGetApp().preset_bundle->filaments.get_edited_preset().config;
    auto start_temp = lround(params.start);
    filament_config->set_key_value("nozzle_temperature_initial_layer", new ConfigOptionInts(1,(int)start_temp));
    filament_config->set_key_value("nozzle_temperature", new ConfigOptionInts(1,(int)start_temp));
    model().objects[0]->config.set_key_value("brim_type", new ConfigOptionEnum<BrimType>(btOuterOnly));
    model().objects[0]->config.set_key_value("brim_width", new ConfigOptionFloat(5.0));
    model().objects[0]->config.set_key_value("brim_object_gap", new ConfigOptionFloat(0.0));
    changed_objects({ 0 });
    wxGetApp().get_tab(Preset::TYPE_PRINT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINT)->reload_config();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->reload_config();
    // cut upper
    auto obj_bb = model().objects[0]->bounding_box();
    auto block_count = lround((350 - params.end) / 5 + 1);
    if(block_count > 0){
        // add EPSILON offset to avoid cutting at the exact location where the flat surface is
        auto new_height = block_count * 10.0 + EPSILON;
        if (new_height < obj_bb.size().z()) {
            std::array<Vec3d, 4> plane_pts = get_cut_plane(obj_bb, new_height);
            cut(0, 0, plane_pts, ModelObjectCutAttribute::KeepLower);
        }
    }
    // cut bottom
    obj_bb = model().objects[0]->bounding_box();
    block_count = lround((350 - params.start) / 5);
    if(block_count > 0){
        auto new_height = block_count * 10.0 + EPSILON;
        if (new_height < obj_bb.size().z()) {
            std::array<Vec3d, 4> plane_pts = get_cut_plane(obj_bb, new_height);
            cut(0, 0, plane_pts, ModelObjectCutAttribute::KeepUpper);
        }
    }
    p->background_process.fff_print()->set_calib_params(params);
}
References add_model(), Slic3r::btOuterOnly, Slic3r::Calib_Temp_Tower, changed_objects(), cut(), Slic3r::Calib_Params::end, EPSILON, Slic3r::GUI::get_cut_plane(), Slic3r::KeepLower, Slic3r::KeepUpper, L, Slic3r::Calib_Params::mode, model(), new_project(), Slic3r::Model::objects, p, Slic3r::resources_dir(), Slic3r::Calib_Params::start, Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::Preset::TYPE_FILAMENT, and Slic3r::Preset::TYPE_PRINT.
Referenced by Slic3r::GUI::Temp_Calibration_Dlg::on_start().
calib_VFA()
void Slic3r::GUI::Plater::calib_VFA (const Calib_Params & params)
{
    const auto calib_vfa_name = wxString::Format(L"VFA test");
    new_project(false, false, calib_vfa_name);
    wxGetApp().mainframe->select_tab(size_t(MainFrame::tp3DEditor));
    if (params.mode != CalibMode::Calib_VFA_Tower)
        return;
    add_model(false, Slic3r::resources_dir() + "/calib/vfa/VFA.stl");
    auto print_config = &wxGetApp().preset_bundle->prints.get_edited_preset().config;
    auto filament_config = &wxGetApp().preset_bundle->filaments.get_edited_preset().config;
    filament_config->set_key_value("slow_down_layer_time", new ConfigOptionFloats { 0.0 });
    filament_config->set_key_value("filament_max_volumetric_speed", new ConfigOptionFloats { 200 });
    print_config->set_key_value("enable_overhang_speed", new ConfigOptionBool { false });
    print_config->set_key_value("timelapse_type", new ConfigOptionEnum<TimelapseType>(tlTraditional));
    print_config->set_key_value("wall_loops", new ConfigOptionInt(1));
    print_config->set_key_value("top_shell_layers", new ConfigOptionInt(0));
    print_config->set_key_value("bottom_shell_layers", new ConfigOptionInt(1));
    print_config->set_key_value("sparse_infill_density", new ConfigOptionPercent(0));
    print_config->set_key_value("spiral_mode", new ConfigOptionBool(true));
    model().objects[0]->config.set_key_value("brim_type", new ConfigOptionEnum<BrimType>(btOuterOnly));
    model().objects[0]->config.set_key_value("brim_width", new ConfigOptionFloat(3.0));
    model().objects[0]->config.set_key_value("brim_object_gap", new ConfigOptionFloat(0.0));
    changed_objects({ 0 });
    wxGetApp().get_tab(Preset::TYPE_PRINT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->update_dirty();
    wxGetApp().get_tab(Preset::TYPE_PRINT)->update_ui_from_settings();
    wxGetApp().get_tab(Preset::TYPE_FILAMENT)->update_ui_from_settings();
    // cut upper
    auto obj_bb = model().objects[0]->bounding_box();
    auto height = 5 * ((params.end - params.start) / params.step + 1);
    if (height < obj_bb.size().z()) {
        std::array<Vec3d, 4> plane_pts = get_cut_plane(obj_bb, height);
        cut(0, 0, plane_pts, ModelObjectCutAttribute::KeepLower);
    }
    p->background_process.fff_print()->set_calib_params(params);
}
References add_model(), Slic3r::btOuterOnly, Slic3r::Calib_VFA_Tower, changed_objects(), cut(), Slic3r::Calib_Params::end, Slic3r::GUI::get_cut_plane(), Slic3r::KeepLower, L, Slic3r::Calib_Params::mode, model(), new_project(), Slic3r::Model::objects, p, Slic3r::resources_dir(), Slic3r::Calib_Params::start, Slic3r::Calib_Params::step, Slic3r::tlTraditional, Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::Preset::TYPE_FILAMENT, and Slic3r::Preset::TYPE_PRINT.
Referenced by Slic3r::GUI::VFA_Test_Dlg::on_start().
can_add_model()
bool Slic3r::GUI::Plater::can_add_model () const
{ return !is_background_process_slicing(); }
References is_background_process_slicing().
can_add_plate()
bool Slic3r::GUI::Plater::can_add_plate () const
{ return !is_background_process_slicing() && p->can_add_plate(); }
References is_background_process_slicing(), and p.
can_arrange()
bool Slic3r::GUI::Plater::can_arrange () const
{ return p->can_arrange(); }
References p.
can_copy_to_clipboard()
bool Slic3r::GUI::Plater::can_copy_to_clipboard () const
{
    if (!IsShown() || !p->is_view3D_shown())
        return false;
    if (is_selection_empty())
        return false;
    const Selection& selection = p->view3D->get_canvas3d()->get_selection();
    if ((wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA) && !selection.is_sla_compliant())
        return false;
    return true;
}
References is_selection_empty(), Slic3r::GUI::Selection::is_sla_compliant(), p, and Slic3r::ptSLA.
Referenced by copy_selection_to_clipboard().
can_cut_to_clipboard()
bool Slic3r::GUI::Plater::can_cut_to_clipboard () const
{
    if (is_selection_empty())
        return false;
    return true;
}
References is_selection_empty().
Referenced by cut_selection_to_clipboard().
can_decrease_instances()
bool Slic3r::GUI::Plater::can_decrease_instances () const
{ return p->can_decrease_instances(); }
References p.
Referenced by decrease_instances().
can_delete()
bool Slic3r::GUI::Plater::can_delete () const
{ return p->can_delete(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_delete().
can_delete_all()
bool Slic3r::GUI::Plater::can_delete_all () const
{ return p->can_delete_all(); }
References p.
can_delete_plate()
bool Slic3r::GUI::Plater::can_delete_plate () const
{ return p->can_delete_plate(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_plate_menu().
can_edit_text()
bool Slic3r::GUI::Plater::can_edit_text () const
{ return p->can_edit_text(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_edit_text().
can_fillcolor()
bool Slic3r::GUI::Plater::can_fillcolor () const
{ return p->can_fillcolor(); }
References p.
Referenced by fill_color().
can_fix_through_netfabb()
bool Slic3r::GUI::Plater::can_fix_through_netfabb () const
{ return p->can_fix_through_netfabb(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_fix_through_netfabb().
can_increase_instances()
bool Slic3r::GUI::Plater::can_increase_instances () const
{ return p->can_increase_instances(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_fill_bed(), and increase_instances().
can_layers_editing()
bool Slic3r::GUI::Plater::can_layers_editing () const
{ return p->can_layers_editing(); }
References p.
can_mirror()
bool Slic3r::GUI::Plater::can_mirror () const
{ return p->can_mirror(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_items_mirror().
can_paste_from_clipboard()
bool Slic3r::GUI::Plater::can_paste_from_clipboard () const
{
    if (!IsShown() || !p->is_view3D_shown()) return false;
    const Selection& selection = p->view3D->get_canvas3d()->get_selection();
    const Selection::Clipboard& clipboard = selection.get_clipboard();
    if (clipboard.is_empty() && p->sidebar->obj_list()->clipboard_is_empty())
        return false;
    if ((wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptSLA) && !clipboard.is_sla_compliant())
        return false;
    Selection::EMode mode = clipboard.get_mode();
    if ((mode == Selection::Volume) && !selection.is_from_single_instance())
        return false;
    if ((mode == Selection::Instance) && (selection.get_mode() != Selection::Instance))
        return false;
    return true;
}
References Slic3r::GUI::Selection::get_clipboard(), Slic3r::GUI::Selection::Clipboard::get_mode(), Slic3r::GUI::Selection::get_mode(), Slic3r::GUI::Selection::Instance, Slic3r::GUI::Selection::Clipboard::is_empty(), Slic3r::GUI::Selection::is_from_single_instance(), Slic3r::GUI::Selection::Clipboard::is_sla_compliant(), p, Slic3r::ptSLA, and Slic3r::GUI::Selection::Volume.
Referenced by paste_from_clipboard().
can_redo()
bool Slic3r::GUI::Plater::can_redo () const
{ return IsShown() && p->is_view3D_shown() && p->undo_redo_stack().has_redo_snapshot(); }
References p.
can_reload_from_disk()
bool Slic3r::GUI::Plater::can_reload_from_disk () const
{ return p->can_reload_from_disk(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_reload_from_disk().
can_replace_with_stl()
bool Slic3r::GUI::Plater::can_replace_with_stl () const
{ return p->can_replace_with_stl(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_replace_with_stl().
can_set_instance_to_object()
bool Slic3r::GUI::Plater::can_set_instance_to_object () const
{ return p->can_set_instance_to_object(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_instance_to_object().
can_simplify()
bool Slic3r::GUI::Plater::can_simplify () const
{ return p->can_simplify(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_simplify().
can_split()
bool Slic3r::GUI::Plater::can_split (bool to_objects) const
{ return p->can_split(to_objects); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_bbl_part_menu(), Slic3r::GUI::MenuFactory::create_extra_object_menu(), Slic3r::GUI::MenuFactory::create_object_menu(), Slic3r::GUI::MenuFactory::create_part_menu(), Slic3r::GUI::MenuFactory::create_sla_object_menu(), and Slic3r::GUI::MenuFactory::multi_selection_menu().
can_split_to_objects()
bool Slic3r::GUI::Plater::can_split_to_objects () const
{ return p->can_split_to_objects(); }
References p.
can_split_to_volumes()
bool Slic3r::GUI::Plater::can_split_to_volumes () const
{ return p->can_split_to_volumes(); }
References p.
can_undo()
bool Slic3r::GUI::Plater::can_undo () const
{ return IsShown() && p->is_view3D_shown() && p->undo_redo_stack().has_undo_snapshot(); }
References p.
canvas3D() [1/2]
GLCanvas3D * Slic3r::GUI::Plater::canvas3D ()
{
    // BBS modify view3D->get_canvas3d() to current canvas
    return p->get_current_canvas3D();
}
References p.
Referenced by Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), Slic3r::GUI::MenuFactory::append_menu_item_center(), Slic3r::GUI::MenuFactory::append_menu_item_export_stl(), Slic3r::GUI::MenuFactory::append_menu_item_instance_to_object(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_process(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_settings(), Slic3r::GUI::MenuFactory::append_menu_item_set_printable(), Slic3r::GUI::MenuFactory::append_menu_item_set_visible(), Slic3r::GUI::call_after_if_active(), Slic3r::GUI::ObjectList::del_info_item(), Slic3r::GUI::get_arrange_params(), Slic3r::GUI::get_wipe_tower(), Slic3r::GUI::get_wipe_tower_arrangepoly(), increase_instances(), Slic3r::GUI::init_arrange_params(), Slic3r::GUI::ObjectList::list_manipulation(), Slic3r::GUI::ObjectList::OnEditingStarted(), Slic3r::GUI::GUI_App::post_init(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_wipe_tower(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), search(), Slic3r::GUI::update_arrange_params(), and Slic3r::GUI::GUI_App::update_mode().
canvas3D() [2/2]
const GLCanvas3D * Slic3r::GUI::Plater::canvas3D () const
{
    // BBS modify view3D->get_canvas3d() to current canvas
    return p->get_current_canvas3D();
}
References p.
center_selection()
void Slic3r::GUI::Plater::center_selection ()
{ p->center_selection(); }
References p.
Referenced by _calib_pa_pattern(), and Slic3r::GUI::MenuFactory::append_menu_item_center().
changed_mesh()
void Slic3r::GUI::Plater::changed_mesh (int obj_idx)
{
    ModelObject* mo = model().objects[obj_idx];
    sla::reproject_points_and_holes(mo);
    update();
    p->object_list_changed();
    p->schedule_background_process();
}
References model(), Slic3r::Model::objects, p, Slic3r::sla::reproject_points_and_holes(), and update().
Referenced by Slic3r::GUI::GLGizmoSimplify::apply_simplify(), and Slic3r::GUI::ObjectList::fix_through_netfabb().
changed_object()
void Slic3r::GUI::Plater::changed_object (int obj_idx)
{
    if (obj_idx < 0)
        return;
    // recenter and re - align to Z = 0
    p->model.objects[obj_idx]->ensure_on_bed(p->printer_technology != ptSLA);
    if (this->p->printer_technology == ptSLA) {
        // Update the SLAPrint from the current Model, so that the reload_scene()
        // pulls the correct data, update the 3D scene.
        this->p->update_restart_background_process(true, false);
    }
    else
        p->view3D->reload_scene(false);
    // update print
    this->p->schedule_background_process();
}
References p, and Slic3r::ptSLA.
changed_objects()
void Slic3r::GUI::Plater::changed_objects (const std::vector< size_t > & object_idxs)
{
    if (object_idxs.empty())
        return;
    for (size_t obj_idx : object_idxs) {
        if (obj_idx < p->model.objects.size()) {
            if (p->model.objects[obj_idx]->bounding_box().min.z() >= SINKING_Z_THRESHOLD)
                // re - align to Z = 0
                p->model.objects[obj_idx]->ensure_on_bed();
        }
    }
    if (this->p->printer_technology == ptSLA) {
        // Update the SLAPrint from the current Model, so that the reload_scene()
        // pulls the correct data, update the 3D scene.
        this->p->update_restart_background_process(true, false);
    }
    else {
        p->view3D->reload_scene(false);
        p->view3D->get_canvas3d()->update_instance_printable_state_for_objects(object_idxs);
    }
    // update print
    this->p->schedule_background_process();
}
References model(), Slic3r::Model::objects, p, Slic3r::ptSLA, and Slic3r::SINKING_Z_THRESHOLD.
Referenced by _calib_pa_pattern(), _calib_pa_tower(), calib_max_vol_speed(), calib_retraction(), calib_temp(), and calib_VFA().
clear_before_change_mesh()
void Slic3r::GUI::Plater::clear_before_change_mesh (int obj_idx)
{
    ModelObject* mo = model().objects[obj_idx];
    // If there are custom supports/seams/mmu segmentation, remove them. Fixed mesh
    // may be different and they would make no sense.
    bool paint_removed = false;
    for (ModelVolume* mv : mo->volumes) {
        paint_removed |= ! mv->supported_facets.empty() || ! mv->seam_facets.empty() || ! mv->mmu_segmentation_facets.empty();
        mv->supported_facets.reset();
        mv->seam_facets.reset();
        mv->mmu_segmentation_facets.reset();
    }
    if (paint_removed) {
        // snapshot_time is captured by copy so the lambda knows where to undo/redo to.
        get_notification_manager()->push_notification(
                    NotificationType::CustomSupportsAndSeamRemovedAfterRepair,
                    NotificationManager::NotificationLevel::PrintInfoNotificationLevel,
                    _u8L("Custom supports and color painting were removed before repairing."));
    }
}
References _u8L, Slic3r::GUI::CustomSupportsAndSeamRemovedAfterRepair, get_notification_manager(), model(), Slic3r::Model::objects, Slic3r::GUI::NotificationManager::PrintInfoNotificationLevel, Slic3r::GUI::NotificationManager::push_notification(), and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::GLGizmoSimplify::apply_simplify(), and Slic3r::GUI::ObjectList::fix_through_netfabb().
clear_undo_redo_stack_main()
void Slic3r::GUI::Plater::clear_undo_redo_stack_main ()
{ p->undo_redo_stack_main().clear(); }
References p.
clone_selection()
void Slic3r::GUI::Plater::clone_selection ()
{
    if (is_selection_empty())
        return;
    long res = wxGetNumberFromUser("",
        _L("Clone"),
        _L("Number of copies:"),
        1, 0, 100, this);
    wxString msg;
    if (res == -1) {
        msg = _L("Invalid number");
        return;
    }
    Selection& selection = p->get_selection();
    selection.clone(res);
}
References _L, Slic3r::GUI::Selection::clone(), is_selection_empty(), and p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_clone().
close_with_confirm()
int Slic3r::GUI::Plater::close_with_confirm (std::function< bool(bool yes_or_no)> second_check = nullptr)
{
    if (up_to_date(false, false)) {
        if (second_check && !second_check(false)) return wxID_CANCEL;
        model().set_backup_path("");
        return wxID_NO;
    }
    MessageDialog dlg(static_cast<wxWindow*>(this), _L("The current project has unsaved changes, save it before continue?"),
        wxString(SLIC3R_APP_FULL_NAME) + " - " + _L("Save"), wxYES_NO | wxCANCEL | wxYES_DEFAULT | wxCENTRE);
    dlg.show_dsa_button(_L("Remember my choice."));
    auto choise = wxGetApp().app_config->get("save_project_choise");
    auto result = choise.empty() ? dlg.ShowModal() : choise == "yes" ? wxID_YES : wxID_NO;
    if (result == wxID_CANCEL)
        return result;
    else {
        if (dlg.get_checkbox_state())
            wxGetApp().app_config->set("save_project_choise", result == wxID_YES ? "yes" : "no");
        if (result == wxID_YES) {
            result = save_project();
            if (result == wxID_CANCEL) {
                if (choise.empty())
                    return result;
                else
                    result = wxID_NO;
            }
        }
    }
    if (second_check && !second_check(result == wxID_YES)) return wxID_CANCEL;
    model().set_backup_path("");
    up_to_date(true, false);
    up_to_date(true, true);
    return result;
}
References _L, Slic3r::GUI::MsgDialog::get_checkbox_state(), Slic3r::Model::set_backup_path(), Slic3r::GUI::MsgDialog::show_dsa_button(), Slic3r::GUI::DPIAware< P >::ShowModal(), and SLIC3R_APP_FULL_NAME.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), load_project(), and new_project().
collapse_sidebar()
void Slic3r::GUI::Plater::collapse_sidebar (bool show)
{ p->collapse_sidebar(show); }
References p.
Referenced by load_project(), and new_project().
combine_mesh_fff()
TriangleMesh Slic3r::GUI::Plater::combine_mesh_fff (const ModelObject & mo, int instance_id, std::function< void(const std::string &)> notify_func = {}) static
{
    TriangleMesh mesh;
    std::vector<csg::CSGPart> csgmesh;
    csgmesh.reserve(2 * mo.volumes.size());
    bool has_splitable_volume = csg::model_to_csgmesh(mo, Transform3d::Identity(), std::back_inserter(csgmesh),
        csg::mpartsPositive | csg::mpartsNegative | csg::mpartsDoSplits);
    if (csg::check_csgmesh_booleans(Range{ std::begin(csgmesh), std::end(csgmesh) }) == csgmesh.end()) {
        try {
            MeshBoolean::mcut::McutMeshPtr meshPtr = csg::perform_csgmesh_booleans_mcut(Range{ std::begin(csgmesh), std::end(csgmesh) });
            mesh = MeshBoolean::mcut::mcut_to_triangle_mesh(*meshPtr);
            }
        catch (...) {}
#if 0
        // if mcut fails, try again with CGAL
        if (mesh.empty()) {
            try {
                auto meshPtr = csg::perform_csgmesh_booleans(Range{ std::begin(csgmesh), std::end(csgmesh) });
                mesh = MeshBoolean::cgal::cgal_to_triangle_mesh(*meshPtr);
                }
            catch (...) {}
        }
#endif
    }
    if (mesh.empty()) {
        if (notify_func)
            notify_func(_u8L("Unable to perform boolean operation on model meshes. "
                "Only positive parts will be exported."));
        for (const ModelVolume* v : mo.volumes)
            if (v->is_model_part()) {
                TriangleMesh vol_mesh(v->mesh());
                vol_mesh.transform(v->get_matrix(), true);
                mesh.merge(vol_mesh);
            }
    }
    if (instance_id == -1) {
        TriangleMesh vols_mesh(mesh);
        mesh = TriangleMesh();
        for (const ModelInstance* i : mo.instances) {
            TriangleMesh m = vols_mesh;
            m.transform(i->get_matrix(), true);
            mesh.merge(m);
        }
    }
    else if (0 <= instance_id && instance_id < int(mo.instances.size()))
        mesh.transform(mo.instances[instance_id]->get_matrix(), true);
    return mesh;
}
References _u8L, Slic3r::MeshBoolean::cgal::cgal_to_triangle_mesh(), Slic3r::csg::check_csgmesh_booleans(), Slic3r::TriangleMesh::empty(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::ModelObject::instances, Slic3r::MeshBoolean::mcut::mcut_to_triangle_mesh(), Slic3r::TriangleMesh::merge(), Slic3r::csg::model_to_csgmesh(), Slic3r::csg::mpartsDoSplits, Slic3r::csg::mpartsNegative, Slic3r::csg::mpartsPositive, Slic3r::csg::perform_csgmesh_booleans(), Slic3r::csg::perform_csgmesh_booleans_mcut(), Slic3r::TriangleMesh::transform(), and Slic3r::ModelObject::volumes.
Referenced by export_stl().
config()
const DynamicPrintConfig * Slic3r::GUI::Plater::config () const
{ return p->config; }
References p.
Referenced by Slic3r::GUI::Plater::priv::~priv(), config_change_notification(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), force_filament_colors_update(), get_extruder_colors_from_plater_config(), Slic3r::GUI::get_shrink_bedpts(), import_model_id(), Slic3r::GUI::ObjectTablePanel::init_filaments_and_colors(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::priv::load_model_objects(), on_config_change(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::Plater::priv::scale_selection_to_fit_print_volume(), Slic3r::GUI::Plater::priv::scaled_bed_shape_bb(), Slic3r::GUI::Plater::priv::schedule_background_process(), Slic3r::GUI::Plater::priv::set_bed_shape(), setExtruderParams(), setPrintSpeedTable(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::Plater::priv::undo_redo_to(), and Slic3r::GUI::Plater::priv::update_background_process().
config_change_notification()
void Slic3r::GUI::Plater::config_change_notification (const DynamicPrintConfig & config, const std::string & key)
{
    GLCanvas3D* view3d_canvas = get_view3D_canvas3D();
    if (key == std::string("print_sequence")) {
        auto seq_print = config.option<ConfigOptionEnum<PrintSequence>>("print_sequence");
        if (seq_print && view3d_canvas && view3d_canvas->is_initialized() && view3d_canvas->is_rendering_enabled()) {
            NotificationManager* notify_manager = get_notification_manager();
            if (seq_print->value == PrintSequence::ByObject) {
                std::string info_text = _u8L("Print By Object: \nSuggest to use auto-arrange to avoid collisions when printing.");
                notify_manager->bbl_show_seqprintinfo_notification(info_text);
            }
            else
                notify_manager->bbl_close_seqprintinfo_notification();
        }
    }
    // notification for more options
}
References _u8L, Slic3r::GUI::NotificationManager::bbl_close_seqprintinfo_notification(), Slic3r::GUI::NotificationManager::bbl_show_seqprintinfo_notification(), Slic3r::ByObject, config(), get_notification_manager(), get_view3D_canvas3D(), Slic3r::GUI::GLCanvas3D::is_initialized(), Slic3r::GUI::GLCanvas3D::is_rendering_enabled(), and Slic3r::ConfigBase::option().
Referenced by on_config_change().
convert_unit()
void Slic3r::GUI::Plater::convert_unit (ConversionType conv_type)
{
    std::vector<int> obj_idxs, volume_idxs;
    wxGetApp().obj_list()->get_selection_indexes(obj_idxs, volume_idxs);
    if (obj_idxs.empty() && volume_idxs.empty())
        return;
    TakeSnapshot snapshot(this, conv_type == ConversionType::CONV_FROM_INCH  ? "Convert from imperial units" :
                                conv_type == ConversionType::CONV_TO_INCH    ? "Revert conversion from imperial units" :
                                conv_type == ConversionType::CONV_FROM_METER ? "Convert from meters" : "Revert conversion from meters");
    wxBusyCursor wait;
    ModelObjectPtrs objects;
    std::reverse(obj_idxs.begin(), obj_idxs.end());
    for (int obj_idx : obj_idxs) {
        ModelObject *object = p->model.objects[obj_idx];
        object->convert_units(objects, conv_type, volume_idxs);
        remove(obj_idx);
    }
    std::reverse(objects.begin(), objects.end());
    p->load_model_objects(objects);
    Selection& selection = p->view3D->get_canvas3d()->get_selection();
    size_t last_obj_idx = p->model.objects.size() - 1;
    if (volume_idxs.empty()) {
        for (size_t i = 0; i < objects.size(); ++i)
            selection.add_object((unsigned int)(last_obj_idx - i), i == 0);
    }
    else {
        for (int vol_idx : volume_idxs)
            selection.add_volume(last_obj_idx, vol_idx, 0, false);
    }
}
References Slic3r::GUI::Selection::add_object(), Slic3r::GUI::Selection::add_volume(), Slic3r::CONV_FROM_INCH, Slic3r::CONV_FROM_METER, Slic3r::CONV_TO_INCH, p, and remove().
copy_selection_to_clipboard()
void Slic3r::GUI::Plater::copy_selection_to_clipboard ()
{
    // At first try to copy selected values to the ObjectList's clipboard
    // to check if Settings or Layers are selected in the list
    // and then copy to 3DCanvas's clipboard if not
    if (can_copy_to_clipboard() && !p->sidebar->obj_list()->copy_to_clipboard())
        p->view3D->get_canvas3d()->get_selection().copy_to_clipboard();
}
References can_copy_to_clipboard(), and p.
cut()
void Slic3r::GUI::Plater::cut (size_t obj_idx, size_t instance_idx, std::array< Vec3d, 4 > plane_points, ModelObjectCutAttributes attributes)
{
    wxCHECK_RET(obj_idx < p->model.objects.size(), "obj_idx out of bounds");
    auto *object = p->model.objects[obj_idx];
    wxCHECK_RET(instance_idx < object->instances.size(), "instance_idx out of bounds");
    if (! attributes.has(ModelObjectCutAttribute::KeepUpper) && ! attributes.has(ModelObjectCutAttribute::KeepLower))
        return;
    wxBusyCursor wait;
    // BBS: replace z with plane_points
    const auto new_objects = object->cut(instance_idx, plane_points, attributes);
    remove(obj_idx);
    p->load_model_objects(new_objects);
    // now process all updates of the 3d scene
    update();
    // Update InfoItems in ObjectList after update() to use of a correct value of the GLCanvas3D::is_sinking(),
    // which is updated after a view3D->reload_scene(false, flags & (unsigned int)UpdateParams::FORCE_FULL_SCREEN_REFRESH) call
    for (size_t idx = 0; idx < p->model.objects.size(); idx++)
        wxGetApp().obj_list()->update_info_items(idx);
    Selection& selection = p->get_selection();
    size_t last_id = p->model.objects.size() - 1;
    for (size_t i = 0; i < new_objects.size(); ++i)
        selection.add_object((unsigned int)(last_id - i), i == 0);
}
References Slic3r::GUI::Selection::add_object(), Slic3r::enum_bitmask< option_type, typename >::has(), Slic3r::KeepLower, Slic3r::KeepUpper, model(), Slic3r::Model::objects, p, remove(), and update().
Referenced by _calib_pa_tower(), calib_max_vol_speed(), calib_retraction(), calib_temp(), and calib_VFA().
cut_selection_to_clipboard()
void Slic3r::GUI::Plater::cut_selection_to_clipboard ()
{
    Plater::TakeSnapshot snapshot(this, "Cut Selected Objects");
    if (can_cut_to_clipboard() && !p->sidebar->obj_list()->cut_to_clipboard()) {
        p->view3D->get_canvas3d()->get_selection().cut_to_clipboard();
    }
}
References can_cut_to_clipboard(), and p.
decrease_instances()
void Slic3r::GUI::Plater::decrease_instances (size_t num = 1)
{
    // BBS
#if 0
    if (! can_decrease_instances()) { return; }
    Plater::TakeSnapshot snapshot(this, "Decrease Instances");
    int obj_idx = p->get_selected_object_idx();
    ModelObject* model_object = p->model.objects[obj_idx];
    if (model_object->instances.size() > num) {
        for (size_t i = 0; i < num; ++ i)
            model_object->delete_last_instance();
        p->update();
        // Delete object from Sidebar list. Do it after update, so that the GLScene selection is updated with the modified model.
        sidebar().obj_list()->decrease_object_instances(obj_idx, num);
    }
    else {
        remove(obj_idx);
    }
    if (!model_object->instances.empty())
        p->get_selection().add_instance(obj_idx, (int)model_object->instances.size() - 1);
    p->selection_changed();
    this->p->schedule_background_process();
#endif
}
References can_decrease_instances(), Slic3r::GUI::ObjectList::decrease_object_instances(), Slic3r::ModelObject::delete_last_instance(), Slic3r::ModelObject::instances, Slic3r::GUI::Sidebar::obj_list(), p, remove(), and sidebar().
Referenced by set_number_of_copies().
default_menu()
wxMenu * Slic3r::GUI::Plater::default_menu ()
{ return p->menus.default_menu();           }
References p.
Referenced by Slic3r::GUI::ObjectList::show_context_menu().
delete_all_objects_from_model()
void Slic3r::GUI::Plater::delete_all_objects_from_model ()
{
    p->delete_all_objects_from_model();
}
References p.
delete_object_from_model()
bool Slic3r::GUI::Plater::delete_object_from_model (size_t obj_idx, bool refresh_immediately = true)
{ return p->delete_object_from_model(obj_idx, refresh_immediately); }
References p.
delete_plate()
int Slic3r::GUI::Plater::delete_plate (int plate_index = -1)
{
    int index = plate_index, ret;
    if (plate_index == -1)
        index = p->partplate_list.get_curr_plate_index();
    take_snapshot("delete partplate");
    ret = p->partplate_list.delete_plate(index);
    //BBS: update the current print to the current plate
    p->partplate_list.update_slice_context_to_current_plate(p->background_process);
    p->preview->update_gcode_result(p->partplate_list.get_current_slice_result());
    p->sidebar->obj_list()->reload_all_plates();
    // BBS update default view
    //get_camera().select_view("topfront");
    //get_camera().requires_zoom_to_plate = REQUIRES_ZOOM_TO_ALL_PLATE;
    //need to call update
    update();
    return ret;
}
References p, take_snapshot(), and update().
Referenced by Slic3r::GUI::MenuFactory::create_plate_menu(), and select_plate_by_hover_id().
deselect_all()
void Slic3r::GUI::Plater::deselect_all ()
{ p->deselect_all(); }
References p.
download_project()
void Slic3r::GUI::Plater::download_project (const wxString & project_id)
{
    return;
}
edit_text()
void Slic3r::GUI::Plater::edit_text ()
{
    auto &manager = get_view3D_canvas3D()->get_gizmos_manager();
    manager.open_gizmo(GLGizmosManager::Text);
    update();
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), get_view3D_canvas3D(), Slic3r::GUI::GLGizmosManager::open_gizmo(), Slic3r::GUI::GLGizmosManager::Text, and update().
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_edit_text().
eject_drive()
void Slic3r::GUI::Plater::eject_drive ()
{
  wxBusyCursor wait;
    wxGetApp().removable_drive_manager()->set_and_verify_last_save_path(p->last_output_dir_path);
  wxGetApp().removable_drive_manager()->eject_drive();
}
References p.
enable_collapse_toolbar()
void Slic3r::GUI::Plater::enable_collapse_toolbar (bool enable)
{
    p->collapse_toolbar.set_enabled(enable);
}
References p.
enable_preview_moves_slider()
void Slic3r::GUI::Plater::enable_preview_moves_slider (bool enable)
enable_wireframe()
void Slic3r::GUI::Plater::enable_wireframe (bool status)
{
    p->wireframe_enabled = status;
}
References p.
Referenced by Plater().
enter_gizmos_stack()
void Slic3r::GUI::Plater::enter_gizmos_stack ()
{ p->enter_gizmos_stack(); }
References p.
export_3mf()
int Slic3r::GUI::Plater::export_3mf (const boost::filesystem::path & output_path = boost::filesystem::path(), SaveStrategy strategy = SaveStrategy::Default, int export_plate_idx = -1, Export3mfProgressFn proFn = nullptr)
{
    int ret = 0;
    //if (p->model.objects.empty()) {
    //    MessageDialog dialog(nullptr, _L("No objects to export."), _L("Save project"), wxYES);
    //    if (dialog.ShowModal() == wxYES)
    //        return -1;
    //}
    if (output_path.empty())
        return -1;
    bool export_config = true;
    wxString path = from_path(output_path);
    if (!path.Lower().EndsWith(".3mf"))
        return -1;
    DynamicPrintConfig cfg = wxGetApp().preset_bundle->full_config_secure();
    const std::string path_u8 = into_u8(path);
    wxBusyCursor wait;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": path=%1%, backup=%2%, export_plate_idx=%3%, SaveStrategy=%4%")
        %output_path.string()%(strategy & SaveStrategy::Backup)%export_plate_idx %(unsigned int)strategy;
    //BBS: add plate logic for thumbnail generate
    std::vector<ThumbnailData*> thumbnails;
    std::vector<ThumbnailData*> calibration_thumbnails;
    std::vector<ThumbnailData*> top_thumbnails;
    std::vector<ThumbnailData*> picking_thumbnails;
    std::vector<PlateBBoxData*> plate_bboxes;
    // BBS: backup
    if (!(strategy & SaveStrategy::Backup)) {
        for (int i = 0; i < p->partplate_list.get_plate_count(); i++) {
            ThumbnailData* thumbnail_data = &p->partplate_list.get_plate(i)->thumbnail_data;
            if (p->partplate_list.get_plate(i)->thumbnail_data.is_valid() &&  using_exported_file()) {
                //no need to generate thumbnail
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": non need to re-generate thumbnail for gcode/exported mode of plate %1%")%i;
            }
            else {
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": re-generate thumbnail for plate %1%") % i;
                const ThumbnailsParams thumbnail_params = { {}, false, true, true, true, i };
                p->generate_thumbnail(p->partplate_list.get_plate(i)->thumbnail_data, THUMBNAIL_SIZE_3MF.first, THUMBNAIL_SIZE_3MF.second,
                                    thumbnail_params, Camera::EType::Ortho);
            }
            thumbnails.push_back(thumbnail_data);
            //ThumbnailData* calibration_data = &p->partplate_list.get_plate(i)->cali_thumbnail_data;
            //calibration_thumbnails.push_back(calibration_data);
            PlateBBoxData* plate_bbox_data = &p->partplate_list.get_plate(i)->cali_bboxes_data;
            plate_bboxes.push_back(plate_bbox_data);
            //generate top and picking thumbnails
            ThumbnailData* top_thumbnail = &p->partplate_list.get_plate(i)->top_thumbnail_data;
            if (top_thumbnail->is_valid() &&  using_exported_file()) {
                //no need to generate thumbnail
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": non need to re-generate top_thumbnail for gcode/exported mode of plate %1%")%i;
            }
            else {
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": re-generate top_thumbnail for plate %1%") % i;
                const ThumbnailsParams thumbnail_params = { {}, false, true, false, true, i };
                p->generate_thumbnail(p->partplate_list.get_plate(i)->top_thumbnail_data, THUMBNAIL_SIZE_3MF.first, THUMBNAIL_SIZE_3MF.second,
                                    thumbnail_params, Camera::EType::Ortho, true, false);
            }
            top_thumbnails.push_back(top_thumbnail);
            ThumbnailData* picking_thumbnail = &p->partplate_list.get_plate(i)->pick_thumbnail_data;
            if (picking_thumbnail->is_valid() &&  using_exported_file()) {
                //no need to generate thumbnail
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": non need to re-generate pick_thumbnail for gcode/exported mode of plate %1%")%i;
            }
            else {
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": re-generate pick_thumbnail for plate %1%") % i;
                const ThumbnailsParams thumbnail_params = { {}, false, true, false, true, i };
                p->generate_thumbnail(p->partplate_list.get_plate(i)->pick_thumbnail_data, THUMBNAIL_SIZE_3MF.first, THUMBNAIL_SIZE_3MF.second,
                                    thumbnail_params, Camera::EType::Ortho, true, true);
            }
            picking_thumbnails.push_back(picking_thumbnail);
        }
        if (p->partplate_list.get_curr_plate()->is_slice_result_valid()) {
            //BBS generate BBS calibration thumbnails
            int index = p->partplate_list.get_curr_plate_index();
            //ThumbnailData* calibration_data = calibration_thumbnails[index];
            //const ThumbnailsParams calibration_params = { {}, false, true, true, true, p->partplate_list.get_curr_plate_index() };
            //p->generate_calibration_thumbnail(*calibration_data, PartPlate::cali_thumbnail_width, PartPlate::cali_thumbnail_height, calibration_params);
            if (using_exported_file()) {
                //do nothing
            }
            else
                *plate_bboxes[index] = p->generate_first_layer_bbox();
        }
    }
    //BBS: add bbs 3mf logic
    PlateDataPtrs plate_data_list;
    p->partplate_list.store_to_3mf_structure(plate_data_list, (strategy & SaveStrategy::WithGcode || strategy & SaveStrategy::WithSliceInfo), export_plate_idx);
    // BBS: backup
    PresetBundle& preset_bundle = *wxGetApp().preset_bundle;
    std::vector<Preset*> project_presets = preset_bundle.get_current_project_embedded_presets();
    StoreParams store_params;
    store_params.path  = path_u8.c_str();
    store_params.model = &p->model;
    store_params.plate_data_list = plate_data_list;
    store_params.export_plate_idx = export_plate_idx;
    store_params.project_presets = project_presets;
    store_params.config = export_config ? &cfg : nullptr;
    store_params.thumbnail_data = thumbnails;
    store_params.top_thumbnail_data = top_thumbnails;
    store_params.pick_thumbnail_data = picking_thumbnails;
    store_params.calibration_thumbnail_data = calibration_thumbnails;
    store_params.proFn = proFn;
    store_params.id_bboxes = plate_bboxes;//BBS
    store_params.project = &p->project;
    store_params.strategy = strategy | SaveStrategy::Zip64;
    // get type and color for platedata
    auto* filament_color = dynamic_cast<const ConfigOptionStrings*>(cfg.option("filament_colour"));
    for (int i = 0; i < plate_data_list.size(); i++) {
        PlateData *plate_data = plate_data_list[i];
        for (auto it = plate_data->slice_filaments_info.begin(); it != plate_data->slice_filaments_info.end(); it++) {
            std::string display_filament_type;
            it->type  = cfg.get_filament_type(display_filament_type, it->id);
            it->color = filament_color ? filament_color->get_at(it->id) : "#FFFFFF";
            // save filament info used in curr plate
            int index = p->partplate_list.get_curr_plate_index();
            if (store_params.id_bboxes.size() > index) {
                store_params.id_bboxes[index]->filament_ids.push_back(it->id);
                store_params.id_bboxes[index]->filament_colors.push_back(it->color);
            }
        }
    }
    // handle Design Info
    bool has_design_info = false;
    ModelDesignInfo designInfo;
    if (p->model.design_info != nullptr) {
        if (!p->model.design_info->Designer.empty()) {
            BOOST_LOG_TRIVIAL(trace) << "design_info, found designer = " << p->model.design_info->Designer;
            has_design_info = true;
        }
    }
    if (!has_design_info) {
        // add Designed Info
        if (p->model.design_info == nullptr) {
            // set designInfo before export and reset after export
            if (wxGetApp().is_user_login()) {
                p->model.design_info                 = std::make_shared<ModelDesignInfo>();
                //p->model.design_info->Designer       = wxGetApp().getAgent()->get_user_nickanme();
                p->model.design_info->Designer       = "";
                p->model.design_info->DesignerUserId = wxGetApp().getAgent()->get_user_id();
                BOOST_LOG_TRIVIAL(trace) << "design_info prepare, designer = "<< "";
                BOOST_LOG_TRIVIAL(trace) << "design_info prepare, designer_user_id = " << p->model.design_info->DesignerUserId;
            }
        }
    }
    bool store_result = Slic3r::store_bbs_3mf(store_params);
    // reset designed info
    if (!has_design_info)
        p->model.design_info = nullptr;
    if (store_result) {
        if (!(store_params.strategy & SaveStrategy::Silence)) {
            // Success
            p->set_project_filename(path);
        }
    }
    else {
        ret = -1;
    }
    if (project_presets.size() > 0)
    {
        for (unsigned int i = 0; i < project_presets.size(); i++)
        {
            delete project_presets[i];
        }
        project_presets.clear();
    }
    release_PlateData_list(plate_data_list);
    for (unsigned int i = 0; i < calibration_thumbnails.size(); i++)
    {
        //release the data here, as it will always be generated when export
        calibration_thumbnails[i]->reset();
    }
    for (unsigned int i = 0; i < top_thumbnails.size(); i++)
    {
        //release the data here, as it will always be generated when export
        top_thumbnails[i]->reset();
    }
    top_thumbnails.clear();
    for (unsigned int i = 0; i < picking_thumbnails.size(); i++)
    {
        //release the data here, as it will always be generated when export
        picking_thumbnails[i]->reset();;
    }
    picking_thumbnails.clear();
    return ret;
}
References Slic3r::Backup, Slic3r::StoreParams::calibration_thumbnail_data, Slic3r::StoreParams::config, Slic3r::StoreParams::export_plate_idx, Slic3r::GUI::from_path(), Slic3r::PresetBundle::get_current_project_embedded_presets(), Slic3r::DynamicPrintConfig::get_filament_type(), Slic3r::StoreParams::id_bboxes, Slic3r::GUI::into_u8(), Slic3r::ThumbnailData::is_valid(), Slic3r::StoreParams::model, Slic3r::ConfigBase::option(), Slic3r::GUI::Camera::Ortho, p, Slic3r::StoreParams::path, Slic3r::StoreParams::pick_thumbnail_data, Slic3r::StoreParams::plate_data_list, Slic3r::StoreParams::proFn, Slic3r::StoreParams::project, Slic3r::StoreParams::project_presets, Slic3r::release_PlateData_list(), Slic3r::Silence, Slic3r::PlateData::slice_filaments_info, Slic3r::store_bbs_3mf(), Slic3r::StoreParams::strategy, Slic3r::StoreParams::thumbnail_data, THUMBNAIL_SIZE_3MF, Slic3r::thumbnails(), Slic3r::StoreParams::top_thumbnail_data, Slic3r::trace(), using_exported_file(), Slic3r::WithGcode, Slic3r::WithSliceInfo, and Slic3r::Zip64.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), export_config_3mf(), export_core_3mf(), export_gcode_3mf(), save_project(), and send_gcode().
export_config_3mf()
int Slic3r::GUI::Plater::export_config_3mf (int plate_idx = -1, Export3mfProgressFn proFn = nullptr)
{
    int result = 0;
    /* generate 3mf */
    if (plate_idx == PLATE_CURRENT_IDX) {
        p->m_print_job_data.plate_idx = get_partplate_list().get_curr_plate_index();
    }
    else {
        p->m_print_job_data.plate_idx = plate_idx;
    }
    PartPlate* plate = get_partplate_list().get_curr_plate();
    try {
        p->m_print_job_data._3mf_config_path = fs::path(plate->get_temp_config_3mf_path());
    }
    catch (std::exception& e) {
        BOOST_LOG_TRIVIAL(error) << "generate 3mf path failed";
        return -1;
    }
    SaveStrategy strategy = SaveStrategy::Silence | SaveStrategy::SkipModel | SaveStrategy::WithSliceInfo | SaveStrategy::SkipAuxiliary;
    result = export_3mf(p->m_print_job_data._3mf_config_path, strategy, plate_idx, proFn);
    return result;
}
References error, export_3mf(), Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::PartPlateList::get_curr_plate_index(), get_partplate_list(), Slic3r::GUI::PartPlate::get_temp_config_3mf_path(), p, PLATE_CURRENT_IDX, Slic3r::Silence, Slic3r::SkipAuxiliary, Slic3r::SkipModel, and Slic3r::WithSliceInfo.
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok().
export_core_3mf()
void Slic3r::GUI::Plater::export_core_3mf ()
{
    wxString path = p->get_export_file(FT_3MF);
    if (path.empty()) { return; }
    const std::string path_u8 = into_u8(path);
    export_3mf(path_u8, SaveStrategy::Silence);
}
References export_3mf(), Slic3r::GUI::FT_3MF, Slic3r::GUI::into_u8(), p, and Slic3r::Silence.
export_gcode()
void Slic3r::GUI::Plater::export_gcode (bool prefer_removable)
{
    if (p->model.objects.empty())
        return;
    //if (get_view3D_canvas3D()->get_gizmos_manager().is_in_editing_mode(true))
    //    return;
    if (p->process_completed_with_error == p->partplate_list.get_curr_plate_index())
        return;
    // If possible, remove accents from accented latin characters.
    // This function is useful for generating file names to be processed by legacy firmwares.
    fs::path default_output_file;
    try {
        // Update the background processing, so that the placeholder parser will get the correct values for the ouput file template.
        // Also if there is something wrong with the current configuration, a pop-up dialog will be shown and the export will not be performed.
        unsigned int state = this->p->update_restart_background_process(false, false);
        if (state & priv::UPDATE_BACKGROUND_PROCESS_INVALID)
            return;
        default_output_file = this->p->background_process.output_filepath_for_project("");
    } catch (const Slic3r::PlaceholderParserError &ex) {
        // Show the error with monospaced font.
        show_error(this, ex.what(), true);
        return;
    } catch (const std::exception &ex) {
        show_error(this, ex.what(), false);
        return;
    }
    default_output_file = fs::path(Slic3r::fold_utf8_to_ascii(default_output_file.string()));
    AppConfig         &appconfig         = *wxGetApp().app_config;
    RemovableDriveManager   &removable_drive_manager = *wxGetApp().removable_drive_manager();
    // Get a last save path, either to removable media or to an internal media.
    std::string          start_dir         = appconfig.get_last_output_dir(default_output_file.parent_path().string(), prefer_removable);
    if (prefer_removable) {
        // Returns a path to a removable media if it exists, prefering start_dir. Update the internal removable drives database.
        start_dir = removable_drive_manager.get_removable_drive_path(start_dir);
        if (start_dir.empty())
            // Direct user to the last internal media.
            start_dir = appconfig.get_last_output_dir(default_output_file.parent_path().string(), false);
    }
    fs::path output_path;
    {
        std::string ext = default_output_file.extension().string();
        wxFileDialog dlg(this, (printer_technology() == ptFFF) ? _L("Save G-code file as:") : _devL("Save SLA file as:"),
            start_dir,
            from_path(default_output_file.filename()),
            GUI::file_wildcards((printer_technology() == ptFFF) ? FT_GCODE : FT_SL1, ext),
            wxFD_SAVE | wxFD_OVERWRITE_PROMPT
        );
        if (dlg.ShowModal() == wxID_OK) {
            output_path = into_path(dlg.GetPath());
            while (has_illegal_filename_characters(output_path.filename().string())) {
                show_error(this, _devL("The provided file name is not valid.") + "\n" +
                    _devL("The following characters are not allowed by a FAT file system:") + " <>:/\\|?*\"");
                dlg.SetFilename(from_path(output_path.filename()));
                if (dlg.ShowModal() == wxID_OK)
                    output_path = into_path(dlg.GetPath());
                else {
                    output_path.clear();
                    break;
                }
            }
        }
    }
    if (! output_path.empty()) {
        bool path_on_removable_media = removable_drive_manager.set_and_verify_last_save_path(output_path.string());
        //bool path_on_removable_media = false;
        p->notification_manager->new_export_began(path_on_removable_media);
        p->exporting_status = path_on_removable_media ? ExportingStatus::EXPORTING_TO_REMOVABLE : ExportingStatus::EXPORTING_TO_LOCAL;
        p->last_output_path = output_path.string();
        p->last_output_dir_path = output_path.parent_path().string();
        p->export_gcode(output_path, path_on_removable_media);
        // Storing a path to AppConfig either as path to removable media or a path to internal media.
        // is_path_on_removable_drive() is called with the "true" parameter to update its internal database as the user may have shuffled the external drives
        // while the dialog was open.
        appconfig.update_last_output_dir(output_path.parent_path().string(), path_on_removable_media);
    }
}
References _devL, _L, Slic3r::GUI::EXPORTING_TO_LOCAL, Slic3r::GUI::EXPORTING_TO_REMOVABLE, Slic3r::GUI::file_wildcards(), Slic3r::fold_utf8_to_ascii(), Slic3r::GUI::from_path(), Slic3r::GUI::FT_GCODE, Slic3r::GUI::FT_SL1, Slic3r::AppConfig::get_last_output_dir(), Slic3r::GUI::RemovableDriveManager::get_removable_drive_path(), has_illegal_filename_characters(), Slic3r::GUI::into_path(), p, printer_technology(), Slic3r::ptFFF, Slic3r::GUI::RemovableDriveManager::set_and_verify_last_save_path(), Slic3r::GUI::show_error(), Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_INVALID, and Slic3r::AppConfig::update_last_output_dir().
export_gcode_3mf()
void Slic3r::GUI::Plater::export_gcode_3mf (bool export_all = false)
{
    if (p->model.objects.empty())
        return;
    if (p->process_completed_with_error == p->partplate_list.get_curr_plate_index())
        return;
    //calc default_output_file, get default output file from background process
    fs::path default_output_file;
    AppConfig& appconfig = *wxGetApp().app_config;
    std::string start_dir;
    try {
        // Update the background processing, so that the placeholder parser will get the correct values for the ouput file template.
        // Also if there is something wrong with the current configuration, a pop-up dialog will be shown and the export will not be performed.
        unsigned int state = this->p->update_restart_background_process(false, false);
        if (state & priv::UPDATE_BACKGROUND_PROCESS_INVALID)
            return;
        default_output_file = this->p->background_process.output_filepath_for_project("");
    }
    catch (const Slic3r::PlaceholderParserError& ex) {
        // Show the error with monospaced font.
        show_error(this, ex.what(), true);
        return;
    }
    catch (const std::exception& ex) {
        show_error(this, ex.what(), false);
        return;
    }
    default_output_file.replace_extension(".3mf");
    default_output_file = fs::path(Slic3r::fold_utf8_to_ascii(default_output_file.string()));
    //Get a last save path
    start_dir = appconfig.get_last_output_dir(default_output_file.parent_path().string(), false);
    fs::path output_path;
    {
        std::string ext = default_output_file.extension().string();
        wxFileDialog dlg(this, _L("Save Sliced file as:"),
            start_dir,
            from_path(default_output_file.filename()),
            GUI::file_wildcards(FT_3MF, ext),
            wxFD_SAVE | wxFD_OVERWRITE_PROMPT
        );
        if (dlg.ShowModal() == wxID_OK) {
            output_path = into_path(dlg.GetPath());
            ext = output_path.extension().string();
            if (ext != ".3mf")
                output_path = output_path.string() + ".3mf";
        }
    }
    if (!output_path.empty()) {
        //BBS do not set to removable media path
        bool path_on_removable_media = false;
        p->notification_manager->new_export_began(path_on_removable_media);
        p->exporting_status = path_on_removable_media ? ExportingStatus::EXPORTING_TO_REMOVABLE : ExportingStatus::EXPORTING_TO_LOCAL;
        //BBS do not save last output path
        p->last_output_path = output_path.string();
        p->last_output_dir_path = output_path.parent_path().string();
        int plate_idx = get_partplate_list().get_curr_plate_index();
        if (export_all)
            plate_idx = PLATE_ALL_IDX;
        export_3mf(output_path, SaveStrategy::Silence | SaveStrategy::SplitModel | SaveStrategy::WithGcode | SaveStrategy::SkipModel, plate_idx); // BBS: silence
        RemovableDriveManager& removable_drive_manager = *wxGetApp().removable_drive_manager();
        bool on_removable = removable_drive_manager.is_path_on_removable_drive(p->last_output_dir_path);
        // update last output dir
        appconfig.update_last_output_dir(output_path.parent_path().string(), false);
        p->notification_manager->push_exporting_finished_notification(output_path.string(), p->last_output_dir_path, on_removable);
    }
}
References _L, export_3mf(), Slic3r::GUI::EXPORTING_TO_LOCAL, Slic3r::GUI::EXPORTING_TO_REMOVABLE, Slic3r::GUI::file_wildcards(), Slic3r::fold_utf8_to_ascii(), Slic3r::GUI::from_path(), Slic3r::GUI::FT_3MF, Slic3r::GUI::PartPlateList::get_curr_plate_index(), Slic3r::AppConfig::get_last_output_dir(), get_partplate_list(), Slic3r::GUI::into_path(), Slic3r::GUI::RemovableDriveManager::is_path_on_removable_drive(), p, PLATE_ALL_IDX, Slic3r::GUI::show_error(), Slic3r::Silence, Slic3r::SkipModel, Slic3r::SplitModel, Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_INVALID, Slic3r::AppConfig::update_last_output_dir(), and Slic3r::WithGcode.
export_stl()
void Slic3r::GUI::Plater::export_stl (bool extended = false, bool selection_only = false)
{
    if (p->model.objects.empty()) { return; }
    wxString path = p->get_export_file(FT_STL);
    if (path.empty()) { return; }
    const std::string path_u8 = into_u8(path);
    wxBusyCursor wait;
    const auto& selection = p->get_selection();
    const auto obj_idx = selection.get_object_idx();
#if EXPORT_WITH_BOOLEAN
    if (selection_only && (obj_idx == -1 || selection.is_wipe_tower()))
        return;
#else
    // BBS support selecting multiple objects
    if (selection_only && selection.is_wipe_tower()) return;
    // BBS
    if (selection_only) {
        // only support selection single full object and mulitiple full object
        if (!selection.is_single_full_object() && !selection.is_multiple_full_object()) return;
    }
    // Following lambda generates a combined mesh for export with normals pointing outwards.
    auto mesh_to_export_fff_no_boolean = [](const ModelObject &mo, int instance_id) {
        TriangleMesh mesh;
        for (const ModelVolume *v : mo.volumes)
            if (v->is_model_part()) {
                TriangleMesh vol_mesh(v->mesh());
                vol_mesh.transform(v->get_matrix(), true);
                mesh.merge(vol_mesh);
            }
        if (instance_id == -1) {
            TriangleMesh vols_mesh(mesh);
            mesh = TriangleMesh();
            for (const ModelInstance *i : mo.instances) {
                TriangleMesh m = vols_mesh;
                m.transform(i->get_matrix(), true);
                mesh.merge(m);
            }
        } else if (0 <= instance_id && instance_id < int(mo.instances.size()))
            mesh.transform(mo.instances[instance_id]->get_matrix(), true);
        return mesh;
    };
#endif
    auto mesh_to_export_sla = [&, this](const ModelObject& mo, int instance_id) {
        TriangleMesh mesh;
        const SLAPrintObject *object = this->p->sla_print.get_print_object_by_model_object_id(mo.id());
        if (auto m = object->get_mesh_to_print(); m.empty())
            mesh = combine_mesh_fff(mo, instance_id, [this](const std::string& msg) {return get_notification_manager()->push_plater_error_notification(msg); });
        else {
            const Transform3d mesh_trafo_inv = object->trafo().inverse();
            const bool is_left_handed = object->is_left_handed();
            auto pad_mesh = extended? object->pad_mesh() : TriangleMesh{};
            pad_mesh.transform(mesh_trafo_inv);
            auto supports_mesh = extended ? object->support_mesh() : TriangleMesh{};
            supports_mesh.transform(mesh_trafo_inv);
            const std::vector<SLAPrintObject::Instance>& obj_instances = object->instances();
            for (const SLAPrintObject::Instance& obj_instance : obj_instances) {
                auto it = std::find_if(object->model_object()->instances.begin(), object->model_object()->instances.end(),
                                       [&obj_instance](const ModelInstance *mi) { return mi->id() == obj_instance.instance_id; });
                assert(it != object->model_object()->instances.end());
                if (it != object->model_object()->instances.end()) {
                    const bool one_inst_only = selection_only && ! selection.is_single_full_object();
                    const int instance_idx = it - object->model_object()->instances.begin();
                    const Transform3d& inst_transform = one_inst_only
                                                            ? Transform3d::Identity()
                                                            : object->model_object()->instances[instance_idx]->get_transformation().get_matrix();
                    TriangleMesh inst_mesh;
                    if (!pad_mesh.empty()) {
                        TriangleMesh inst_pad_mesh = pad_mesh;
                        inst_pad_mesh.transform(inst_transform, is_left_handed);
                        inst_mesh.merge(inst_pad_mesh);
                    }
                    if (!supports_mesh.empty()) {
                        TriangleMesh inst_supports_mesh = supports_mesh;
                        inst_supports_mesh.transform(inst_transform, is_left_handed);
                        inst_mesh.merge(inst_supports_mesh);
                    }
                    TriangleMesh inst_object_mesh = object->get_mesh_to_print();
                    inst_object_mesh.transform(mesh_trafo_inv);
                    inst_object_mesh.transform(inst_transform, is_left_handed);
                    inst_mesh.merge(inst_object_mesh);
                           // ensure that the instance lays on the bed
                    inst_mesh.translate(0.0f, 0.0f, -inst_mesh.bounding_box().min.z());
                           // merge instance with global mesh
                    mesh.merge(inst_mesh);
                    if (one_inst_only)
                        break;
                }
            }
        }
        return mesh;
    };
    std::function<TriangleMesh(const ModelObject& mo, int instance_id)>
        mesh_to_export;
    if (p->printer_technology == ptFFF)
#if EXPORT_WITH_BOOLEAN
        mesh_to_export = [this](const ModelObject& mo, int instance_id) {return Plater::combine_mesh_fff(mo, instance_id,
            [this](const std::string& msg) {return get_notification_manager()->push_plater_error_notification(msg); }); };
#else
        mesh_to_export = mesh_to_export_fff_no_boolean;
#endif
    else
        mesh_to_export = mesh_to_export_sla;
    TriangleMesh mesh;
    if (selection_only) {
        if (selection.is_single_full_object()) {
            const auto obj_idx = selection.get_object_idx();
            const ModelObject* model_object = p->model.objects[obj_idx];
            if (selection.get_mode() == Selection::Instance)
                mesh = mesh_to_export(*model_object, (model_object->instances.size() > 1) ? -1 : selection.get_instance_idx());
            else {
                const GLVolume* volume = selection.get_volume(*selection.get_volume_idxs().begin());
                mesh = model_object->volumes[volume->volume_idx()]->mesh();
                mesh.transform(volume->get_volume_transformation().get_matrix(), true);
            }
            if (model_object->instances.size() == 1) mesh.translate(-model_object->origin_translation.cast<float>());
        }
        else if (selection.is_multiple_full_object()) {
            const std::set<std::pair<int, int>>& instances_idxs = p->get_selection().get_selected_object_instances();
            for (const std::pair<int, int>& i : instances_idxs) {
                ModelObject* object = p->model.objects[i.first];
                mesh.merge(mesh_to_export(*object, i.second));
            }
        }
    }
    else {
        for (const ModelObject* o : p->model.objects) {
            mesh.merge(mesh_to_export(*o, -1));
        }
    }
    Slic3r::store_stl(path_u8.c_str(), &mesh, true);
}
References Slic3r::TriangleMesh::bounding_box(), combine_mesh_fff(), Slic3r::GUI::FT_STL, Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_mode(), get_notification_manager(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::ObjectBase::id(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::Selection::Instance, Slic3r::ModelObject::instances, Slic3r::GUI::into_u8(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::GUI::Selection::is_multiple_full_object(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_wipe_tower(), Slic3r::TriangleMesh::merge(), Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::ModelObject::origin_translation, p, Slic3r::ptFFF, Slic3r::GUI::NotificationManager::push_plater_error_notification(), Slic3r::store_stl(), Slic3r::TriangleMesh::transform(), Slic3r::TriangleMesh::translate(), and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_export_stl().
export_toolpaths_to_obj()
void Slic3r::GUI::Plater::export_toolpaths_to_obj () const
{
    if ((printer_technology() != ptFFF) || !is_preview_loaded())
        return;
    wxString path = p->get_export_file(FT_OBJ);
    if (path.empty())
        return;
    wxBusyCursor wait;
    p->preview->get_canvas3d()->export_toolpaths_to_obj(into_u8(path).c_str());
}
References Slic3r::GUI::FT_OBJ, Slic3r::GUI::into_u8(), is_preview_loaded(), p, printer_technology(), and Slic3r::ptFFF.
extract_config_from_project()
void Slic3r::GUI::Plater::extract_config_from_project ()
{
    wxString input_file;
    wxGetApp().load_project(this, input_file);
    if (! input_file.empty())
        load_files({ into_path(input_file) }, LoadStrategy::LoadConfig);
}
References Slic3r::GUI::into_path(), load_files(), and Slic3r::LoadConfig.
fff_print() [1/2]
Print & Slic3r::GUI::Plater::fff_print ()
{ return p->fff_print; }
References p.
fff_print() [2/2]
const Print & Slic3r::GUI::Plater::fff_print () const
{ return p->fff_print; }
References p.
fill_bed_with_instances()
void Slic3r::GUI::Plater::fill_bed_with_instances ()
{
    if (!p->m_ui_jobs.is_any_running())
        p->m_ui_jobs.fill_bed();
}
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_fill_bed().
fill_color()
void Slic3r::GUI::Plater::fill_color (int extruder_id)
{
    if (can_fillcolor()) {
        p->assemble_view->get_canvas3d()->get_selection().fill_color(extruder_id);
    }
}
References can_fillcolor(), and p.
find_new_position()
void Slic3r::GUI::Plater::find_new_position (const ModelInstancePtrs & instances)
{
    arrangement::ArrangePolygons movable, fixed;
    arrangement::ArrangeParams arr_params = get_arrange_params(this);
    for (const ModelObject *mo : p->model.objects)
        for (ModelInstance *inst : mo->instances) {
            auto it = std::find(instances.begin(), instances.end(), inst);
            arrangement::ArrangePolygon arrpoly;
            inst->get_arrange_polygon(&arrpoly);
            if (it == instances.end())
                fixed.emplace_back(std::move(arrpoly));
            else {
                arrpoly.setter = [it](const arrangement::ArrangePolygon &p) {
                    if (p.is_arranged() && p.bed_idx == 0) {
                        Vec2d t = p.translation.cast<double>();
                        (*it)->apply_arrange_result(t, p.rotation);
                    }
                };
                movable.emplace_back(std::move(arrpoly));
            }
        }
    if (auto wt = get_wipe_tower_arrangepoly(*this))
        fixed.emplace_back(*wt);
    arrangement::arrange(movable, fixed, this->build_volume().polygon(), arr_params);
    for (auto & m : movable)
        m.apply();
}
References Slic3r::arrangement::arrange(), build_volume(), Slic3r::GUI::get_arrange_params(), Slic3r::GUI::get_wipe_tower_arrangepoly(), p, and Slic3r::arrangement::ArrangePolygon::setter.
force_filament_colors_update()
void Slic3r::GUI::Plater::force_filament_colors_update ()
{
//BBS: filament_color logic has been moved out of filament setting
#if 0
    bool update_scheduled = false;
    DynamicPrintConfig* config = p->config;
    const std::vector<std::string> filament_presets = wxGetApp().preset_bundle->filament_presets;
    if (filament_presets.size() > 1 &&
        p->config->option<ConfigOptionStrings>("filament_colour")->values.size() == filament_presets.size())
    {
        const PresetCollection& filaments = wxGetApp().preset_bundle->filaments;
        std::vector<std::string> filament_colors;
        filament_colors.reserve(filament_presets.size());
        for (const std::string& filament_preset : filament_presets)
            filament_colors.push_back(filaments.find_preset(filament_preset, true)->config.opt_string("filament_colour", (unsigned)0));
        if (config->option<ConfigOptionStrings>("filament_colour")->values != filament_colors) {
            config->option<ConfigOptionStrings>("filament_colour")->values = filament_colors;
            update_scheduled = true;
        }
    }
    if (update_scheduled) {
        update();
        p->sidebar->obj_list()->update_filament_colors();
    }
    if (p->main_frame->is_loaded())
        this->p->schedule_background_process();
#endif
}
References Slic3r::Preset::config, config(), Slic3r::PresetCollection::find_preset(), Slic3r::DynamicConfig::opt_string(), Slic3r::ConfigBase::option(), p, update(), and Slic3r::ConfigOptionVector< T >::values.
force_print_bed_update()
void Slic3r::GUI::Plater::force_print_bed_update ()
{
    // Fill in the printer model key with something which cannot possibly be valid, so that Plater::on_config_change() will update the print bed
    // once a new Printer profile config is loaded.
    p->config->opt_string("printer_model", true) = "bbl_empty";
}
References p.
Referenced by Slic3r::GUI::GUI_App::load_current_presets().
force_update_all_plate_thumbnails()
void Slic3r::GUI::Plater::force_update_all_plate_thumbnails ()
{
    if (using_exported_file() || skip_thumbnail_invalid) {
    }
    else {
        invalid_all_plate_thumbnails();
        update_all_plate_thumbnails(true);
    }
    get_preview_canvas3D()->update_plate_thumbnails();
}
References get_preview_canvas3D(), invalid_all_plate_thumbnails(), skip_thumbnail_invalid, update_all_plate_thumbnails(), Slic3r::GUI::GLCanvas3D::update_plate_thumbnails(), and using_exported_file().
get_3mf_file_count()
int Slic3r::GUI::Plater::get_3mf_file_count (std::vector< fs::path > paths)
{
    auto count = 0;
    for (const auto &path : paths) {
        if (wxString(encode_path(path.filename().string().c_str())).EndsWith("3mf")) count++;
    }
    return count;
}
References count, and Slic3r::encode_path().
Referenced by add_file(), add_model(), and load_files().
get_assmeble_canvas3D()
GLCanvas3D * Slic3r::GUI::Plater::get_assmeble_canvas3D ()
{
    if (p->assemble_view)
        return p->assemble_view->get_canvas3d();
    return nullptr;
}
References p.
get_build_volume_type()
BuildVolume_Type Slic3r::GUI::Plater::get_build_volume_type () const
{ return p->bed.get_build_volume_type(); }
References p.
Referenced by Slic3r::GUI::PartPlate::calc_vertex_for_icons().
get_camera() [1/2]
Camera & Slic3r::GUI::Plater::get_camera ()
{
    return p->camera;
}
References p.
get_camera() [2/2]
const Camera & Slic3r::GUI::Plater::get_camera () const
{
    return p->camera;
}
References p.
Referenced by Slic3r::GUI::Mouse3DController::disconnect_device(), and Slic3r::GUI::PartPlateList::select_plate_view().
get_collapse_toolbar() [1/2]
GLToolbar & Slic3r::GUI::Plater::get_collapse_toolbar ()
{
    return p->collapse_toolbar;
}
References p.
get_collapse_toolbar() [2/2]
const GLToolbar & Slic3r::GUI::Plater::get_collapse_toolbar () const
{
    return p->collapse_toolbar;
}
References p.
get_colors_for_color_print()
std::vector< std::string > Slic3r::GUI::Plater::get_colors_for_color_print (const GCodeProcessorResult *const result = nullptr) const
{
    std::vector<std::string> colors = get_extruder_colors_from_plater_config(result);
    if (wxGetApp().is_gcode_viewer() && result != nullptr) {
        for (const CustomGCode::Item& code : result->custom_gcode_per_print_z) {
            if (code.type == CustomGCode::ColorChange)
                colors.emplace_back(code.color);
        }
    }
    else {
        //BBS
        colors.reserve(colors.size() + p->model.get_curr_plate_custom_gcodes().gcodes.size());
        for (const CustomGCode::Item& code : p->model.get_curr_plate_custom_gcodes().gcodes) {
            if (code.type == CustomGCode::ColorChange)
                colors.emplace_back(code.color);
        }
    }
    return colors;
}
References Slic3r::CustomGCode::ColorChange, Slic3r::GCodeProcessorResult::custom_gcode_per_print_z, get_extruder_colors_from_plater_config(), and p.
get_current_canvas3D()
GLCanvas3D * Slic3r::GUI::Plater::get_current_canvas3D (bool exclude_preview = false)
{
    return p->get_current_canvas3D(exclude_preview);
}
References p.
Referenced by Slic3r::GUI::MenuFactory::create_default_menu(), Slic3r::GUI::Plater::priv::get_curr_selection(), Slic3r::GUI::get_selection(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::Plater::priv::undo(), Slic3r::GUI::Plater::priv::undo_redo_to(), and Slic3r::GUI::Plater::priv::update_after_undo_redo().
get_export_gcode_filename()
wxString Slic3r::GUI::Plater::get_export_gcode_filename (const wxString & extension = wxEmptyString, bool only_filename = false, bool export_all = false) const
{
    return p->get_export_gcode_filename(extension, only_filename, export_all);
}
References p.
Referenced by Slic3r::GUI::SelectMachineDialog::set_default().
get_extruder_colors_from_plater_config()
std::vector< std::string > Slic3r::GUI::Plater::get_extruder_colors_from_plater_config (const GCodeProcessorResult *const result = nullptr) const
{
    if (wxGetApp().is_gcode_viewer() && result != nullptr)
        return result->extruder_colors;
    else {
        const Slic3r::DynamicPrintConfig* config = &wxGetApp().preset_bundle->project_config;
        std::vector<std::string> filament_colors;
        if (!config->has("filament_colour")) // in case of a SLA print
            return filament_colors;
        filament_colors = (config->option<ConfigOptionStrings>("filament_colour"))->values;
        return filament_colors;
    }
}
References config(), Slic3r::GCodeProcessorResult::extruder_colors, Slic3r::ConfigOptionResolver::has(), and Slic3r::ConfigBase::option().
Referenced by get_colors_for_color_print(), and Slic3r::GUI::Preview::update_layers_slider().
get_last_loaded_gcode()
const wxString & Slic3r::GUI::Plater::get_last_loaded_gcode () const inline
{ return m_last_loaded_gcode; }
References m_last_loaded_gcode.
get_mouse3d_controller() [1/2]
Mouse3DController & Slic3r::GUI::Plater::get_mouse3d_controller ()
{
    return p->mouse3d_controller;
}
References p.
get_mouse3d_controller() [2/2]
const Mouse3DController & Slic3r::GUI::Plater::get_mouse3d_controller () const
{
    return p->mouse3d_controller;
}
References p.
get_next_color_for_filament()
wxColour Slic3r::GUI::Plater::get_next_color_for_filament () static
{
    static int curr_color_filamenet = 0;
    // refs to https://www.ebaomonthly.com/window/photo/lesson/colorList.htm
    wxColour colors[FILAMENT_SYSTEM_COLORS_NUM] = {
        *wxYELLOW,
        * wxRED,
        *wxBLUE,
        *wxCYAN,
        *wxLIGHT_GREY,
        *wxWHITE,
        *wxBLACK,
        wxColour(0,127,255),
        wxColour(139,0,255),
        wxColour(102,255,0),
        wxColour(255,215,0),
        wxColour(0,35,100),
        wxColour(255,0,255),
        wxColour(8,37,103),
        wxColour(127,255,212),
        wxColour(255,191,0)
    };
    return colors[curr_color_filamenet++ % FILAMENT_SYSTEM_COLORS_NUM];
}
References FILAMENT_SYSTEM_COLORS_NUM.
Referenced by Slic3r::GUI::Sidebar::Sidebar(), and Slic3r::GUI::Plater::priv::load_files().
get_notification_manager() [1/2]
NotificationManager * Slic3r::GUI::Plater::get_notification_manager ()
{
    return p->notification_manager.get();
}
References p.
get_notification_manager() [2/2]
const NotificationManager * Slic3r::GUI::Plater::get_notification_manager () const
{
    return p->notification_manager.get();
}
References p.
Referenced by Slic3r::GUI::ArrangeJob::check_unprintable(), clear_before_change_mesh(), config_change_notification(), export_stl(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), Slic3r::GUI::ObjectList::fix_through_netfabb(), load_project(), new_project(), Slic3r::GUI::GUI_App::notification_manager(), Slic3r::GUI::GUI_App::post_init(), Slic3r::GUI::ArrangeJob::prepare(), Slic3r::GUI::OrientJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::GUI::GUI_App::restart_networking(), and show_object_info().
get_partplate_list()
PartPlateList & Slic3r::GUI::Plater::get_partplate_list ()
{
    return p->partplate_list;
}
References p.
Referenced by _calib_pa_pattern(), Slic3r::GUI::MenuFactory::append_menu_item_center(), Slic3r::GUI::MenuFactory::append_menu_item_locked(), Slic3r::GUI::ObjectGridTable::construct_object_configs(), Slic3r::GUI::MenuFactory::create_plate_menu(), export_config_3mf(), export_gcode_3mf(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::ObjectList::fix_through_netfabb(), Slic3r::GUI::init_arrange_params(), invalid_all_plate_thumbnails(), Slic3r::GUI::SelectMachineDialog::is_show_timelapse(), new_project(), Slic3r::GUI::SelectMachineDialog::on_ok_btn(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::SendJob::process(), reslice(), send_gcode(), Slic3r::GUI::SelectMachineDialog::set_default(), update_all_plate_thumbnails(), and Slic3r::GUI::SelectMachineDialog::update_show_status().
get_prepare_state()
int Slic3r::GUI::Plater::get_prepare_state ()
{
    return p->m_job_prepare_state;
}
References p.
Referenced by Slic3r::GUI::init_arrange_params(), Slic3r::GUI::ArrangeJob::prepare(), and Slic3r::GUI::OrientJob::prepare().
get_preview_canvas3D()
GLCanvas3D * Slic3r::GUI::Plater::get_preview_canvas3D ()
{
    return p->preview->get_canvas3d();
}
References p.
Referenced by force_update_all_plate_thumbnails().
get_preview_only_filename()
std::string Slic3r::GUI::Plater::get_preview_only_filename () inline
{ return m_preview_only_filename; };
References m_preview_only_filename.
get_print_finished_event()
int Slic3r::GUI::Plater::get_print_finished_event ()
{
    return EVT_PRINT_FINISHED;
}
Referenced by Slic3r::GUI::PrintJob::PrintJob().
get_print_job_data()
void Slic3r::GUI::Plater::get_print_job_data (PrintPrepareData * data)
{
    if (data) {
        data->plate_idx = p->m_print_job_data.plate_idx;
        data->_3mf_path = p->m_print_job_data._3mf_path;
        data->_3mf_config_path = p->m_print_job_data._3mf_config_path;
    }
}
References Slic3r::GUI::PrintPrepareData::_3mf_config_path, Slic3r::GUI::PrintPrepareData::_3mf_path, p, and Slic3r::GUI::PrintPrepareData::plate_idx.
Referenced by Slic3r::GUI::PrintJob::prepare(), and Slic3r::GUI::SendJob::prepare().
get_project_filename()
wxString Slic3r::GUI::Plater::get_project_filename (const wxString & extension = wxEmptyString) const
{
    return p->get_project_filename(extension);
}
References p.
Referenced by Slic3r::GUI::Plater::priv::get_export_file_path(), save_project(), and Slic3r::GUI::ProjectDirtyStateManager::update_from_presets().
get_project_name()
wxString Slic3r::GUI::Plater::get_project_name ()
{
    return p->get_project_name();
}
References p.
Referenced by add_model(), and Slic3r::GUI::Plater::priv::get_export_file_path().
get_publish_finished_event()
int Slic3r::GUI::Plater::get_publish_finished_event ()
{
    return EVT_PUBLISH_FINISHED;
}
get_selected_object_idx()
int Slic3r::GUI::Plater::get_selected_object_idx ()
{
    return p->get_selected_object_idx();
}
References p.
Referenced by Slic3r::GUI::Plater::priv::can_decrease_instances(), Slic3r::GUI::Plater::priv::can_increase_instances(), Slic3r::GUI::Plater::priv::can_set_instance_to_object(), Slic3r::GUI::Plater::priv::can_simplify(), Slic3r::GUI::Plater::priv::layers_height_allowed(), Slic3r::GUI::Plater::priv::on_right_click(), Slic3r::GUI::FillBedJob::prepare(), and Slic3r::GUI::Plater::priv::split_object().
get_selection()
const Selection & Slic3r::GUI::Plater::get_selection () const
{
    return p->get_selection();
}
References p.
Referenced by Slic3r::GUI::Plater::priv::can_delete(), Slic3r::GUI::Plater::priv::can_mirror(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::Plater::priv::can_replace_with_stl(), Slic3r::GUI::Plater::priv::get_export_file_path(), Slic3r::GUI::Plater::priv::get_selected_object_idx(), Slic3r::GUI::Plater::priv::get_selected_volume_idx(), Slic3r::GUI::Plater::priv::on_right_click(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::RotoptimizeJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::Plater::priv::reload_all_from_disk(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::Plater::priv::replace_with_stl(), show_object_info(), and Slic3r::GUI::Plater::priv::split_object().
get_send_finished_event()
int Slic3r::GUI::Plater::get_send_finished_event ()
{
    return EVT_SEND_FINISHED;
}
Referenced by Slic3r::GUI::SendJob::SendJob().
get_slice_warning_string()
wxString Slic3r::GUI::Plater::get_slice_warning_string (GCodeProcessorResult::SliceWarning & warning) static
{
    if (warning.msg == BED_TEMP_TOO_HIGH_THAN_FILAMENT) {
        return _L("The bed temperature exceeds filament's vitrification temperature. Please open the front door of printer before printing to avoid nozzle clog.");
    } else if (warning.msg == NOZZLE_HRC_CHECKER) {
        return _L("The nozzle hardness required by the filament is higher than the default nozzle hardness of the printer. Please replace the hardened nozzle or filament, otherwise, the nozzle will be attrited or damaged.");
    } else {
        return wxString(warning.msg);
    }
}
References _L, BED_TEMP_TOO_HIGH_THAN_FILAMENT, Slic3r::GCodeProcessorResult::SliceWarning::msg, and NOZZLE_HRC_CHECKER.
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok_btn().
get_view3D_canvas3D()
GLCanvas3D * Slic3r::GUI::Plater::get_view3D_canvas3D ()
{
    return p->view3D->get_canvas3d();
}
References p.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), Slic3r::GUI::MenuFactory::append_menu_item_center(), config_change_notification(), edit_text(), reslice(), Slic3r::GUI::ObjectList::simplify(), and update_all_plate_thumbnails().
GetPlateIndexByRightMenuInLeftUI()
int Slic3r::GUI::Plater::GetPlateIndexByRightMenuInLeftUI ()
{ return p->m_is_RightClickInLeftUI; }
References p.
has_assmeble_view()
bool Slic3r::GUI::Plater::has_assmeble_view () const
{ return p->has_assemble_view(); }
References p.
has_illegal_filename_characters() [1/2]
bool Slic3r::GUI::Plater::has_illegal_filename_characters (const std::string & name) static
{
    const char* illegal_characters = "<>:/\\|?*\"";
    for (size_t i = 0; i < std::strlen(illegal_characters); i++)
        if (name.find_first_of(illegal_characters[i]) != std::string::npos)
            return true;
    return false;
}
has_illegal_filename_characters() [2/2]
bool Slic3r::GUI::Plater::has_illegal_filename_characters (const wxString & name) static
{
    std::string name = into_u8(wxs_name);
    return has_illegal_filename_characters(name);
}
References has_illegal_filename_characters(), and Slic3r::GUI::into_u8().
Referenced by export_gcode(), BitmapTextRenderer::GetValueFromEditorCtrl(), has_illegal_filename_characters(), and Slic3r::GUI::ObjectList::rename_item().
has_toolpaths_to_export()
bool Slic3r::GUI::Plater::has_toolpaths_to_export () const
{
    return  p->preview->get_canvas3d()->has_toolpaths_to_export();
}
References p.
import_model_id()
void Slic3r::GUI::Plater::import_model_id (const std::string & download_info)
{
    std::string download_url;
    std::string filename;
    std::string download_origin_url = wxGetApp().url_decode(download_info);
            fs::path download_path = fs::path(download_origin_url);
            download_url = download_origin_url;
            filename = download_path.filename().string();
    bool download_ok = false;
    /* save to a file */
    /* jump to 3D eidtor */
    wxGetApp().mainframe->select_tab((size_t)MainFrame::TabPosition::tp3DEditor);
    /* prepare progress dialog */
    bool cont = true;
    bool cont_dlg = true;
    bool cancel = false;
    wxString msg;
    wxString dlg_title = _L("Importing Model");
    int percent = 1;
    ProgressDialog dlg(dlg_title,
        wxString(' ', 100) + "\n\n\n\n",
        100,    // range
        this,   // parent
        wxPD_CAN_ABORT |
        wxPD_APP_MODAL |
        wxPD_AUTO_HIDE |
        wxPD_SMOOTH);
    boost::filesystem::path target_path;
    //reset params
    p->project.reset();
    /* prepare project and profile */
    boost::thread import_thread = Slic3r::create_thread([&percent, &cont, &cancel, &msg, &target_path, &download_ok, download_url, &filename] {
        NetworkAgent* m_agent = Slic3r::GUI::wxGetApp().getAgent();
        if (!m_agent) return;
        int res = 0;
        unsigned int http_code;
        std::string http_body;
        msg = _L("prepare 3mf file...");
        //gets the number of files with the same name
        std::vector<wxString>   vecFiles;
        bool                    is_already_exist = false;
        target_path = fs::path(wxGetApp().app_config->get("download_path"));
        try
        {
            vecFiles.clear();
            wxString extension = fs::path(filename).extension().c_str();
            auto name = filename.substr(0, filename.length() - extension.length() - 1);
            for (const auto& iter : boost::filesystem::directory_iterator(target_path))
            {
                if (boost::filesystem::is_directory(iter.path()))
                    continue;
                wxString sFile = iter.path().filename().string().c_str();
                if (strstr(sFile.c_str(), name.c_str()) != NULL) {
                    vecFiles.push_back(sFile);
                }
                if (sFile == filename) is_already_exist = true;
            }
        }
        catch (const std::exception& error)
        {
            //wxString sError = error.what();
        }
        //update filename
        if (is_already_exist && vecFiles.size() >= 1) {
            wxString extension = fs::path(filename).extension().c_str();
            wxString name = filename.substr(0, filename.length() - extension.length());
            filename = wxString::Format("%s(%d)%s", name, vecFiles.size() + 1, extension).ToStdString();
        }
        msg = _L("downloading project ...");
        //target_path = wxStandardPaths::Get().GetTempDir().utf8_str().data();
        //target_path = wxGetApp().get_local_models_path().c_str();
        boost::uuids::uuid uuid = boost::uuids::random_generator()();
        std::string unique = to_string(uuid).substr(0, 6);
        if (filename.empty()) {
            filename = "untitled.3mf";
        }
        //target_path /= (boost::format("%1%_%2%.3mf") % filename % unique).str();
        target_path /= fs::path(wxString(filename).wc_str());
        fs::path tmp_path = target_path;
        tmp_path += format(".%1%", ".download");
        auto url = download_url;
        auto http = Http::get(url);
        http.on_progress([&percent, &cont, &msg](Http::Progress progress, bool& cancel) {
            if (!cont) cancel = true;
            if (progress.dltotal != 0) {
                percent = progress.dlnow * 100 / progress.dltotal;
            }
            msg = wxString::Format(_L("Project downloaded %d%%"), percent);
            })
            .on_error([&msg, &cont](std::string body, std::string error, unsigned http_status) {
                (void)body;
                BOOST_LOG_TRIVIAL(error) << format("Error getting: `%1%`: HTTP %2%, %3%",
                    body,
                    http_status,
                    error);
                msg = wxString::Format("Download Failed! body=%s, error=%s, status=%d", body, error, http_status);
                cont = false;
                return;
                })
                .on_complete([&cont, &download_ok, tmp_path, target_path](std::string body, unsigned /* http_status */) {
                    fs::fstream file(tmp_path, std::ios::out | std::ios::binary | std::ios::trunc);
                    file.write(body.c_str(), body.size());
                    file.close();
                    fs::rename(tmp_path, target_path);
                    cont = false;
                    download_ok = true;
                    })
                    .perform_sync();
                    // for break while
                    cont = false;
        });
    while (cont && cont_dlg) {
        wxMilliSleep(50);
        cont_dlg = dlg.Update(percent, msg);
        if (!cont_dlg) {
            cont = cont_dlg;
            cancel = true;
        }
        if (download_ok)
            break;
    }
    if (import_thread.joinable())
        import_thread.join();
    dlg.Close();
    if (download_ok) {
        BOOST_LOG_TRIVIAL(trace) << "import_model_id: target_path = " << target_path.string();
        /* load project */
        this->load_project(encode_path(target_path.string().c_str()), "<silence>");
        /*BBS set project info after load project, project info is reset in load project */
        //p->project.project_model_id = model_id;
        //p->project.project_design_id = design_id;
        AppConfig* config = wxGetApp().app_config;
        if (config) {
            p->project.project_country_code = config->get_country_code();
        }
        // show save new project
        p->set_project_filename(wxString::FromUTF8(filename));
    }
    else {
        wxMessageBox(msg);
        return;
    }
}
References _L, config(), Slic3r::create_thread(), Slic3r::Http::Progress::dltotal, Slic3r::encode_path(), error, Slic3r::GUI::format(), Slic3r::Http::get(), load_project(), NULL, p, Slic3r::to_string(), Slic3r::GUI::MainFrame::tp3DEditor, Slic3r::trace(), Slic3r::GUI::ProgressDialog::Update(), and void().
import_sl1_archive()
void Slic3r::GUI::Plater::import_sl1_archive ()
{
    if (!p->m_ui_jobs.is_any_running())
        p->m_ui_jobs.import_sla_arch();
}
References p.
increase_instances()
void Slic3r::GUI::Plater::increase_instances (size_t num = 1)
{
    // BBS
#if 0
    if (! can_increase_instances()) { return; }
    Plater::TakeSnapshot snapshot(this, "Increase Instances");
    int obj_idx = p->get_selected_object_idx();
    ModelObject* model_object = p->model.objects[obj_idx];
    ModelInstance* model_instance = model_object->instances.back();
    bool was_one_instance = model_object->instances.size()==1;
    double offset_base = canvas3D()->get_size_proportional_to_max_bed_size(0.05);
    double offset = offset_base;
    for (size_t i = 0; i < num; i++, offset += offset_base) {
        Vec3d offset_vec = model_instance->get_offset() + Vec3d(offset, offset, 0.0);
        model_object->add_instance(offset_vec, model_instance->get_scaling_factor(), model_instance->get_rotation(), model_instance->get_mirror());
//        p->print.get_object(obj_idx)->add_copy(Slic3r::to_2d(offset_vec));
    }
#ifdef SUPPORT_AUTO_CENTER
    if (p->get_config("autocenter") == "true")
        arrange();
#endif
    p->update();
    p->get_selection().add_instance(obj_idx, (int)model_object->instances.size() - 1);
    sidebar().obj_list()->increase_object_instances(obj_idx, was_one_instance ? num + 1 : num);
    p->selection_changed();
    this->p->schedule_background_process();
#endif
}
References Slic3r::ModelObject::add_instance(), arrange(), can_increase_instances(), canvas3D(), Slic3r::ModelInstance::get_mirror(), Slic3r::ModelInstance::get_offset(), Slic3r::ModelInstance::get_rotation(), Slic3r::ModelInstance::get_scaling_factor(), Slic3r::GUI::GLCanvas3D::get_size_proportional_to_max_bed_size(), Slic3r::GUI::ObjectList::increase_object_instances(), Slic3r::ModelObject::instances, Slic3r::GUI::Sidebar::obj_list(), Slic3r::offset(), p, and sidebar().
Referenced by set_number_of_copies().
init_collapse_toolbar()
bool Slic3r::GUI::Plater::init_collapse_toolbar ()
{
    return p->init_collapse_toolbar();
}
References p.
init_notification_manager()
void Slic3r::GUI::Plater::init_notification_manager ()
{
    p->init_notification_manager();
}
References p.
inside_snapshot_capture()
bool Slic3r::GUI::Plater::inside_snapshot_capture ()
{ return p->inside_snapshot_capture(); }
References p.
instance_menu()
wxMenu * Slic3r::GUI::Plater::instance_menu ()
{ return p->menus.instance_menu();          }
References p.
Referenced by Slic3r::GUI::ObjectList::show_context_menu().
invalid_all_plate_thumbnails()
void Slic3r::GUI::Plater::invalid_all_plate_thumbnails ()
{
    if (using_exported_file() || skip_thumbnail_invalid)
        return;
    BOOST_LOG_TRIVIAL(info) << "thumb: invalid all";
    for (int i = 0; i < get_partplate_list().get_plate_count(); i++) {
        PartPlate* plate = get_partplate_list().get_plate(i);
        plate->thumbnail_data.reset();
    }
}
References get_partplate_list(), Slic3r::GUI::PartPlateList::get_plate(), Slic3r::GUI::PartPlateList::get_plate_count(), Slic3r::ThumbnailData::reset(), skip_thumbnail_invalid, Slic3r::GUI::PartPlate::thumbnail_data, and using_exported_file().
Referenced by force_update_all_plate_thumbnails().
is_any_job_running()
bool Slic3r::GUI::Plater::is_any_job_running () const
{
    return p->m_ui_jobs.is_any_running();
}
References p.
is_background_process_slicing()
bool Slic3r::GUI::Plater::is_background_process_slicing () const
{
    return p->m_is_slicing;
}
References p.
Referenced by can_add_model(), and can_add_plate().
is_background_process_update_scheduled()
bool Slic3r::GUI::Plater::is_background_process_update_scheduled () const
{
    return this->p->background_process_timer.IsRunning();
}
References p.
is_export_gcode_scheduled()
bool Slic3r::GUI::Plater::is_export_gcode_scheduled () const
{
    return p->background_process.is_export_scheduled();
}
References p.
is_presets_dirty()
bool Slic3r::GUI::Plater::is_presets_dirty () const
{ return p->is_presets_dirty(); }
References p.
is_preview_loaded()
bool Slic3r::GUI::Plater::is_preview_loaded () const
{ return p->is_preview_loaded(); }
References p.
Referenced by export_toolpaths_to_obj().
is_preview_shown()
bool Slic3r::GUI::Plater::is_preview_shown () const
{ return p->is_preview_shown(); }
References p.
Referenced by search(), and select_plate().
is_project_dirty()
bool Slic3r::GUI::Plater::is_project_dirty () const
{ return p->is_project_dirty(); }
References p.
is_render_statistic_dialog_visible()
bool Slic3r::GUI::Plater::is_render_statistic_dialog_visible () const
{
    return p->show_render_statistic_dialog;
}
References p.
is_selection_empty()
bool Slic3r::GUI::Plater::is_selection_empty () const
{
    return p->get_selection().is_empty() || p->get_selection().is_wipe_tower();
}
References p.
Referenced by can_copy_to_clipboard(), can_cut_to_clipboard(), and clone_selection().
is_show_wireframe()
bool Slic3r::GUI::Plater::is_show_wireframe () const
{
    return p->show_wireframe;
}
References p.
is_sidebar_collapsed()
bool Slic3r::GUI::Plater::is_sidebar_collapsed () const
{ return p->is_sidebar_collapsed(); }
References p.
Referenced by Slic3r::GUI::Plater::priv::init_collapse_toolbar().
is_single_full_object_selection()
bool Slic3r::GUI::Plater::is_single_full_object_selection () const
{
    return p->get_selection().is_single_full_object();
}
References p.
is_view3D_overhang_shown()
bool Slic3r::GUI::Plater::is_view3D_overhang_shown () const
{ return p->is_view3D_overhang_shown(); }
References p.
is_view3D_shown()
bool Slic3r::GUI::Plater::is_view3D_shown () const
{ return p->is_view3D_shown(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_default_menu(), and select_plate().
is_wireframe_enabled()
bool Slic3r::GUI::Plater::is_wireframe_enabled () const
{
    return p->wireframe_enabled;
}
References p.
last_arrange_job_is_finished()
bool Slic3r::GUI::Plater::last_arrange_job_is_finished () inline
    {
        bool prevRunning = false;
        return m_arrange_running.compare_exchange_strong(prevRunning, true);
    };
References m_arrange_running.
Referenced by select_plate_by_hover_id().
layer_menu()
wxMenu * Slic3r::GUI::Plater::layer_menu ()
{ return p->menus.layer_menu();             }
References p.
leave_gizmos_stack()
bool Slic3r::GUI::Plater::leave_gizmos_stack ()
{ return p->leave_gizmos_stack(); } // BBS: return false if not changed
References p.
load_files() [1/3]
std::vector< size_t > Slic3r::GUI::Plater::load_files (const std::vector< boost::filesystem::path > & input_files, LoadStrategy strategy = LoadStrategy::LoadModel|LoadStrategy::LoadConfig, bool ask_multi = false)
Referenced by add_file(), add_model(), Slic3r::GUI::MenuFactory::append_submenu_add_generic(), extract_config_from_project(), Slic3r::GUI::PlaterDropTarget::handleOnIdle(), load_files(), load_project(), open_3mf_file(), and Slic3r::GUI::GUI_App::post_init().
load_files() [2/3]
std::vector< size_t > Slic3r::GUI::Plater::load_files (const std::vector< std::string > & input_files, LoadStrategy strategy = LoadStrategy::LoadModel | LoadStrategy::LoadConfig, bool ask_multi = false)
{
    std::vector<fs::path> paths;
    paths.reserve(input_files.size());
    for (const std::string& path : input_files)
        paths.emplace_back(path);
    return p->load_files(paths, strategy, ask_multi);
}
References p.
load_files() [3/3]
bool Slic3r::GUI::Plater::load_files (const wxArrayString & filenames)
{
    const std::regex pattern_drop(".*[.](stp|step|stl|obj|amf|3mf|svg)", std::regex::icase);
    const std::regex pattern_gcode_drop(".*[.](gcode|g)", std::regex::icase);
    std::vector<fs::path> normal_paths;
    std::vector<fs::path> gcode_paths;
    for (const auto& filename : filenames) {
        fs::path path(into_path(filename));
        if (std::regex_match(path.string(), pattern_drop))
            normal_paths.push_back(std::move(path));
        else if (std::regex_match(path.string(), pattern_gcode_drop))
            gcode_paths.push_back(std::move(path));
        else
            continue;
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": normal_paths %1%, gcode_paths %2%")%normal_paths.size() %gcode_paths.size();
    if (normal_paths.empty() && gcode_paths.empty()) {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(": can not find valid path, return directly");
        // Likely no supported files
        return false;
    }
    else if (normal_paths.empty()){
        //only gcode files
        if (gcode_paths.size() > 1) {
            show_info(this, _L("Only one G-code file can be opened at the same time."), _L("G-code loading"));
            return false;
        }
        load_gcode(from_path(gcode_paths.front()));
        return true;
    }
    if (!gcode_paths.empty()) {
        show_info(this, _L("G-code files can not be loaded with models together!"), _L("G-code loading"));
        return false;
    }
    //for (std::vector<fs::path>::const_reverse_iterator it = normal_paths.rbegin(); it != normal_paths.rend(); ++it) {
    //    std::string filename = (*it).filename().string();
    //    ////BBS: only 3mf will be treated as project file
    //    if (open_3mf_file((*it)))
    //        return true;
    //}
    std::string snapshot_label;
    assert(!normal_paths.empty());
    if (normal_paths.size() == 1) {
        snapshot_label = "Load File";
        snapshot_label += ": ";
        snapshot_label += encode_path(normal_paths.front().filename().string().c_str());
    } else {
        snapshot_label = "Load Files";
        snapshot_label += ": ";
        snapshot_label += encode_path(normal_paths.front().filename().string().c_str());
        for (size_t i = 1; i < normal_paths.size(); ++i) {
            snapshot_label += ", ";
            snapshot_label += encode_path(normal_paths[i].filename().string().c_str());
        }
    }
    //Plater::TakeSnapshot snapshot(this, snapshot_label);
    //load_files(normal_paths, LoadStrategy::LoadModel);
    // BBS: check file types
    std::sort(normal_paths.begin(), normal_paths.end(), [](fs::path obj1, fs::path obj2) { return obj1.filename().string() < obj2.filename().string(); });
    auto loadfiles_type  = LoadFilesType::NoFile;
    auto amf_files_count = get_3mf_file_count(normal_paths);
    if (normal_paths.size() > 1 && amf_files_count < normal_paths.size()) { loadfiles_type = LoadFilesType::Multiple3MFOther; }
    if (normal_paths.size() > 1 && amf_files_count == normal_paths.size()) { loadfiles_type = LoadFilesType::Multiple3MF; }
    if (normal_paths.size() > 1 && amf_files_count == 0) { loadfiles_type = LoadFilesType::MultipleOther; }
    if (normal_paths.size() == 1 && amf_files_count == 1) { loadfiles_type = LoadFilesType::Single3MF; };
    if (normal_paths.size() == 1 && amf_files_count == 0) { loadfiles_type = LoadFilesType::SingleOther; };
    auto first_file = std::vector<fs::path>{};
    auto tmf_file   = std::vector<fs::path>{};
    auto other_file = std::vector<fs::path>{};
    auto res        = true;
    if (this->m_only_gcode || this->m_exported_file) {
        if ((loadfiles_type == LoadFilesType::SingleOther)
            || (loadfiles_type == LoadFilesType::MultipleOther)) {
            show_info(this, _L("Can not add models when in preview mode!"), _L("Add Models"));
            return false;
        }
    }
    switch (loadfiles_type) {
    case LoadFilesType::Single3MF:
        open_3mf_file(normal_paths[0]);
        break;
    case LoadFilesType::SingleOther: {
        Plater::TakeSnapshot snapshot(this, snapshot_label);
        if (load_files(normal_paths, LoadStrategy::LoadModel, false).empty()) { res = false; }
        break;
    }
    case LoadFilesType::Multiple3MF:
        first_file = std::vector<fs::path>{normal_paths[0]};
        for (auto i = 0; i < normal_paths.size(); i++) {
            if (i > 0) { other_file.push_back(normal_paths[i]); }
        };
        open_3mf_file(first_file[0]);
        if (load_files(other_file, LoadStrategy::LoadModel).empty()) {  res = false;  }
        break;
    case LoadFilesType::MultipleOther: {
        Plater::TakeSnapshot snapshot(this, snapshot_label);
        if (load_files(normal_paths, LoadStrategy::LoadModel, true).empty()) { res = false; }
        break;
    }
    case LoadFilesType::Multiple3MFOther:
        for (const auto &path : normal_paths) {
            if (wxString(encode_path(path.filename().string().c_str())).EndsWith("3mf")) {
                if (first_file.size() <= 0)
                    first_file.push_back(path);
                else
                    tmf_file.push_back(path);
            } else {
                other_file.push_back(path);
            }
        }
        open_3mf_file(first_file[0]);
        if (load_files(tmf_file, LoadStrategy::LoadModel).empty()) {  res = false;  }
        if (load_files(other_file, LoadStrategy::LoadModel, false).empty()) {  res = false;  }
        break;
    default: break;
    }
    return res;
}
References _L, Slic3r::empty(), Slic3r::encode_path(), error, Slic3r::GUI::from_path(), get_3mf_file_count(), Slic3r::GUI::into_path(), load_files(), load_gcode(), Slic3r::LoadModel, m_exported_file, m_only_gcode, Slic3r::GUI::Multiple3MF, Slic3r::GUI::Multiple3MFOther, Slic3r::GUI::MultipleOther, Slic3r::GUI::NoFile, open_3mf_file(), Slic3r::GUI::show_info(), Slic3r::GUI::Single3MF, and Slic3r::GUI::SingleOther.
load_gcode() [1/2]
void Slic3r::GUI::Plater::load_gcode ()
{
    // Ask user for a gcode file name.
    wxString input_file;
    wxGetApp().load_gcode(this, input_file);
    // And finally load the gcode file.
    load_gcode(input_file);
}
References load_gcode().
Referenced by load_files(), load_gcode(), Slic3r::GUI::GUI_App::post_init(), and reload_gcode_from_disk().
load_gcode() [2/2]
void Slic3r::GUI::Plater::load_gcode (const wxString & filename)
{
    if (! is_gcode_file(into_u8(filename))
        || (m_last_loaded_gcode == filename && m_only_gcode)
        )
        return;
    m_last_loaded_gcode = filename;
    // BSS: create a new project when load_gcode, force close previous one
    if (new_project(false, true) != wxID_YES)
        return;
    m_only_gcode = true;
    // cleanup view before to start loading/processing
    //BBS: update gcode to current partplate's
    GCodeProcessorResult* current_result = p->partplate_list.get_current_slice_result();
    Print& current_print = p->partplate_list.get_current_fff_print();
    //BBS:already reset in new_project
    //current_result->reset();
    //p->gcode_result.reset();
    //reset_gcode_toolpaths();
    p->preview->reload_print(false, m_only_gcode);
    wxGetApp().mainframe->select_tab(MainFrame::tpPreview);
    p->set_current_panel(p->preview, true);
    p->get_current_canvas3D()->render();
    //p->notification_manager->bbl_show_plateinfo_notification(into_u8(_L("Preview only mode for gcode file.")));
    current_print.apply(this->model(), wxGetApp().preset_bundle->full_config());
    wxBusyCursor wait;
    // process gcode
    GCodeProcessor processor;
    try
    {
        processor.process_file(filename.ToUTF8().data());
    }
    catch (const std::exception& ex)
    {
        show_error(this, ex.what());
        return;
    }
    *current_result = std::move(processor.extract_result());
    //current_result->filename = filename;
    BedType bed_type = current_result->bed_type;
    if (bed_type != BedType::btCount) {
        DynamicPrintConfig &proj_config = wxGetApp().preset_bundle->project_config;
        proj_config.set_key_value("curr_bed_type", new ConfigOptionEnum<BedType>(bed_type));
        on_bed_type_change(bed_type);
    }
    current_print.apply(this->model(), wxGetApp().preset_bundle->full_config());
    current_print.set_gcode_file_ready();
    // show results
    p->preview->reload_print(false, m_only_gcode);
    //BBS: zoom to bed 0 for gcode preview
    //p->preview->get_canvas3d()->zoom_to_gcode();
    p->preview->get_canvas3d()->zoom_to_plate(0);
    if (p->preview->get_canvas3d()->get_gcode_layers_zs().empty()) {
        MessageDialog(this, _L("The selected file") + ":\n" + filename + "\n" + _L("does not contain valid gcode."),
            wxString(GCODEVIEWER_APP_NAME) + " - " + _L("Error occurs while loading G-code file"), wxCLOSE | wxICON_WARNING | wxCENTRE).ShowModal();
        set_project_filename(DEFAULT_PROJECT_NAME);
    }
    else
        set_project_filename(filename);
}
References _L, Slic3r::Print::apply(), Slic3r::GCodeProcessorResult::bed_type, Slic3r::btCount, Slic3r::GUI::DEFAULT_PROJECT_NAME, GCODEVIEWER_APP_NAME, Slic3r::GUI::into_u8(), Slic3r::is_gcode_file(), m_last_loaded_gcode, m_only_gcode, model(), new_project(), on_bed_type_change(), p, processor, Slic3r::Print::set_gcode_file_ready(), Slic3r::DynamicConfig::set_key_value(), set_project_filename(), Slic3r::GUI::show_error(), Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::GUI::MainFrame::tpPreview.
load_project()
void Slic3r::GUI::Plater::load_project (wxString const & filename = "", wxString const & originfile = "-")
{
    auto filename = filename2;
    auto check = [&filename, this] (bool yes_or_no) {
        if (!yes_or_no && !wxGetApp().check_and_save_current_preset_changes(_L("Load project"),
                _L("Some presets are modified.")))
            return false;
        if (filename.empty()) {
            // Ask user for a project file name.
            wxGetApp().load_project(this, filename);
        }
        return !filename.empty();
    };
    // BSS: save project, force close
    int result;
    if ((result = close_with_confirm(check)) == wxID_CANCEL) {
        return;
    }
    //BBS: add only gcode mode
    bool previous_gcode = m_only_gcode;
    // BBS
    if (m_loading_project) {
        //some error cases happens
        //return directly
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": current loading other project, return directly");
        return;
    }
    else
        m_loading_project = true;
    m_only_gcode = false;
    m_exported_file = false;
    get_notification_manager()->bbl_close_plateinfo_notification();
    get_notification_manager()->bbl_close_preview_only_notification();
    get_notification_manager()->bbl_close_3mf_warn_notification();
    auto path     = into_path(filename);
    auto strategy = LoadStrategy::LoadModel | LoadStrategy::LoadConfig;
    if (originfile == "<silence>") {
        strategy = strategy | LoadStrategy::Silence;
    } else if (originfile != "-") {
        strategy = strategy | LoadStrategy::Restore;
    }
    bool load_restore = strategy & LoadStrategy::Restore;
    // Take the Undo / Redo snapshot.
    reset();
    Plater::TakeSnapshot snapshot(this, "Load Project", UndoRedo::SnapshotType::ProjectSeparator);
    std::vector<fs::path> input_paths;
    input_paths.push_back(path);
    if (strategy & LoadStrategy::Restore)
        input_paths.push_back(into_u8(originfile));
    std::vector<size_t> res = load_files(input_paths, strategy);
    reset_project_dirty_initial_presets();
    update_project_dirty_from_presets();
    wxGetApp().preset_bundle->export_selections(*wxGetApp().app_config);
    // if res is empty no data has been loaded
    if (!res.empty() && (load_restore || !(strategy & LoadStrategy::Silence))) {
        p->set_project_filename(load_restore ? originfile : filename);
        if (load_restore && originfile.IsEmpty())
            p->set_project_name(_L("Untitled"));
    } else {
        if (using_exported_file())
            p->set_project_filename(filename);
    }
    // BBS set default 3D view and direction after loading project
    //p->select_view_3D("3D");
    if (!m_exported_file) {
        p->select_view("topfront");
        p->camera.requires_zoom_to_plate = REQUIRES_ZOOM_TO_ALL_PLATE;
        wxGetApp().mainframe->select_tab(MainFrame::tp3DEditor);
    }
    else {
        p->partplate_list.select_plate_view();
    }
    if (previous_gcode)
        collapse_sidebar(false);
    wxGetApp().app_config->update_last_backup_dir(model().get_backup_path());
    if (load_restore && !originfile.empty()) {
        wxGetApp().app_config->update_skein_dir(into_path(originfile).parent_path().string());
        wxGetApp().app_config->update_config_dir(into_path(originfile).parent_path().string());
    }
    if (!load_restore)
        up_to_date(true, false);
    else
        p->dirty_state.update_from_undo_redo_stack(true);
    up_to_date(true, true);
    wxGetApp().params_panel()->switch_to_object_if_has_object_configs();
    m_loading_project = false;
}
References _L, Slic3r::GUI::NotificationManager::bbl_close_3mf_warn_notification(), Slic3r::GUI::NotificationManager::bbl_close_plateinfo_notification(), Slic3r::GUI::NotificationManager::bbl_close_preview_only_notification(), close_with_confirm(), collapse_sidebar(), get_notification_manager(), Slic3r::GUI::into_path(), Slic3r::GUI::into_u8(), load_files(), Slic3r::LoadConfig, Slic3r::LoadModel, m_exported_file, m_loading_project, m_only_gcode, model(), p, Slic3r::UndoRedo::ProjectSeparator, REQUIRES_ZOOM_TO_ALL_PLATE, reset(), reset_project_dirty_initial_presets(), Slic3r::Restore, Slic3r::Silence, Slic3r::GUI::MainFrame::tp3DEditor, up_to_date(), update_project_dirty_from_presets(), and using_exported_file().
Referenced by Slic3r::GUI::MainFrame::MainFrame(), import_model_id(), BBLTopbar::OnOpenProject(), open_3mf_file(), and Slic3r::GUI::GUI_App::request_open_project().
merge()
void Slic3r::GUI::Plater::merge (size_t obj_idx, std::vector< int > & vol_indeces)
{
    wxCHECK_RET(obj_idx < p->model.objects.size(), "obj_idx out of bounds");
    auto* object = p->model.objects[obj_idx];
    Plater::TakeSnapshot snapshot(this, "Merge");
    wxBusyCursor wait;
    // real process
    PresetBundle& preset_bundle = *wxGetApp().preset_bundle;
    const auto print_tech = preset_bundle.printers.get_edited_preset().printer_technology();
    // BBS
    const size_t filament_cnt = print_tech != ptFFF ? 1 : preset_bundle.filament_presets.size();
    const auto new_objects = object->merge_volumes(vol_indeces);
    remove(obj_idx);
    p->load_model_objects(new_objects);
    Selection& selection = p->get_selection();
    size_t last_id = p->model.objects.size() - 1;
    for (size_t i = 0; i < new_objects.size(); ++i)
    {
        selection.add_object((unsigned int)(last_id - i), i == 0);
    }
}
References Slic3r::GUI::Selection::add_object(), Slic3r::PresetBundle::filament_presets, Slic3r::PresetCollection::get_edited_preset(), model(), Slic3r::Model::objects, p, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptFFF, and remove().
mirror()
void Slic3r::GUI::Plater::mirror (Axis axis)
{ p->mirror(axis); }
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_items_mirror().
model() [1/2]
Model & Slic3r::GUI::Plater::model ()
{ return p->model; }
References p.
model() [2/2]
const Model & Slic3r::GUI::Plater::model () const
{ return p->model; }
References p.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), _calib_pa_pattern(), _calib_pa_tower(), Slic3r::GUI::GLGizmoSimplify::add_simplify_suggestion_notification(), apply_background_progress(), calib_flowrate(), calib_max_vol_speed(), calib_retraction(), calib_temp(), calib_VFA(), Slic3r::GUI::Plater::priv::can_arrange(), Slic3r::GUI::Plater::priv::can_decrease_instances(), Slic3r::GUI::Plater::priv::can_delete_all(), Slic3r::GUI::Plater::priv::can_fix_through_netfabb(), Slic3r::GUI::Plater::priv::can_increase_instances(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::Plater::priv::can_set_instance_to_object(), changed_mesh(), changed_objects(), clear_before_change_mesh(), Slic3r::GUI::ArrangeJob::clear_input(), Slic3r::GUI::OrientJob::clear_input(), cut(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::Plater::priv::export_gcode(), Slic3r::GUI::Plater::priv::export_gcode(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::Plater::priv::get_export_file_path(), Slic3r::GUI::Plater::priv::get_export_gcode_filename(), Slic3r::GUI::Plater::priv::get_selected_volume_idx(), Slic3r::GUI::Plater::priv::has_assemble_view(), Slic3r::GUI::Plater::priv::layers_height_allowed(), Slic3r::GUI::Plater::priv::load_files(), load_gcode(), Slic3r::GUI::Plater::priv::load_model_objects(), load_project(), merge(), Slic3r::GUI::GUI_App::model(), new_project(), Slic3r::GUI::Plater::priv::object_list_changed(), open_3mf_file(), Slic3r::GUI::Plater::priv::PopupObjectTable(), Slic3r::GUI::FillBedJob::prepare(), Slic3r::GUI::ArrangeJob::prepare_all(), Slic3r::GUI::ArrangeJob::prepare_partplate(), Slic3r::GUI::OrientJob::prepare_partplate(), Slic3r::GUI::ArrangeJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selected(), Slic3r::GUI::OrientJob::prepare_selection(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::Plater::priv::reload_all_from_disk(), Slic3r::GUI::Plater::priv::reload_from_disk(), Slic3r::GUI::Plater::priv::remove(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::Plater::priv::reset(), reslice(), save_project(), segment(), select_plate(), select_plate_by_hover_id(), show_object_info(), Slic3r::GUI::Plater::priv::split_object(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::Plater::priv::undo_redo_to(), Slic3r::GUI::Plater::priv::update(), and Slic3r::GUI::Preview::update_layers_slider().
msw_rescale()
void Slic3r::GUI::Plater::msw_rescale ()
{
    p->preview->msw_rescale();
    p->view3D->get_canvas3d()->msw_rescale();
    p->sidebar->msw_rescale();
    p->menus.msw_rescale();
    Layout();
    GetParent()->Layout();
}
References p.
multi_selection_menu()
wxMenu * Slic3r::GUI::Plater::multi_selection_menu ()
{ return p->menus.multi_selection_menu();   }
References p.
Referenced by Slic3r::GUI::ObjectList::show_context_menu().
need_update()
bool Slic3r::GUI::Plater::need_update () const
{
    return p->need_update();
}
References p.
Referenced by set_need_update(), Slic3r::GUI::Plater::priv::undo_redo_to(), and update().
new_project()
int Slic3r::GUI::Plater::new_project (bool skip_confirm = false, bool silent = false, const wxString & project_name = wxString())
{
    bool transfer_preset_changes = false;
    // BBS: save confirm
    auto check = [&transfer_preset_changes](bool yes_or_no) {
        wxString header = _L("Some presets are modified.") + "\n" +
            (yes_or_no ? _L("You can keep the modified presets to the new project or discard them") :
                _L("You can keep the modifield presets to the new project, discard or save changes as new presets."));
        using ab = UnsavedChangesDialog::ActionButtons;
        int act_buttons = ab::KEEP | ab::REMEMBER_CHOISE;
        if (!yes_or_no)
            act_buttons |= ab::SAVE;
        return wxGetApp().check_and_keep_current_preset_changes(_L("Creating a new project"), header, act_buttons, &transfer_preset_changes);
    };
    int result;
    if (!skip_confirm && (result = close_with_confirm(check)) == wxID_CANCEL)
        return wxID_CANCEL;
    //BBS: add only gcode mode
    bool previous_gcode = m_only_gcode;
    m_only_gcode = false;
    m_exported_file = false;
    m_loading_project = false;
    get_notification_manager()->bbl_close_plateinfo_notification();
    get_notification_manager()->bbl_close_preview_only_notification();
    get_notification_manager()->bbl_close_3mf_warn_notification();
    if (!silent)
        wxGetApp().mainframe->select_tab(MainFrame::tp3DEditor);
    //get_partplate_list().reinit();
    //get_partplate_list().update_slice_context_to_current_plate(p->background_process);
    //p->preview->update_gcode_result(p->partplate_list.get_current_slice_result());
    reset(transfer_preset_changes);
    reset_project_dirty_after_save();
    reset_project_dirty_initial_presets();
    wxGetApp().update_saved_preset_from_current_preset();
    update_project_dirty_from_presets();
    //reset project
    p->project.reset();
    //set project name
    if (project_name.empty())
        p->set_project_name(_L("Untitled"));
    else
        p->set_project_name(project_name);
    Plater::TakeSnapshot snapshot(this, "New Project", UndoRedo::SnapshotType::ProjectSeparator);
    Model m;
    model().load_from(m); // new id avoid same path name
    //select first plate
    get_partplate_list().select_plate(0);
    SimpleEvent event(EVT_GLCANVAS_PLATE_SELECT);
    p->on_plate_selected(event);
    p->load_auxiliary_files();
    wxGetApp().app_config->update_last_backup_dir(model().get_backup_path());
    // BBS set default view and zoom
    p->select_view_3D("3D");
    p->select_view("topfront");
    p->camera.requires_zoom_to_bed = true;
    if (previous_gcode)
        collapse_sidebar(false);
    up_to_date(true, false);
    up_to_date(true, true);
    return wxID_YES;
}
References _L, Slic3r::GUI::NotificationManager::bbl_close_3mf_warn_notification(), Slic3r::GUI::NotificationManager::bbl_close_plateinfo_notification(), Slic3r::GUI::NotificationManager::bbl_close_preview_only_notification(), close_with_confirm(), collapse_sidebar(), get_notification_manager(), get_partplate_list(), Slic3r::Model::load_from(), m_exported_file, m_loading_project, m_only_gcode, model(), p, Slic3r::UndoRedo::ProjectSeparator, reset(), reset_project_dirty_after_save(), reset_project_dirty_initial_presets(), Slic3r::GUI::PartPlateList::select_plate(), Slic3r::GUI::MainFrame::tp3DEditor, up_to_date(), and update_project_dirty_from_presets().
Referenced by Slic3r::GUI::MainFrame::MainFrame(), calib_flowrate(), calib_max_vol_speed(), calib_pa(), calib_retraction(), calib_temp(), calib_VFA(), load_gcode(), and Slic3r::GUI::GUI_App::request_open_project().
object_list_changed()
void Slic3r::GUI::Plater::object_list_changed ()
{ p->object_list_changed(); }
References p.
Referenced by Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::Plater::priv::remove(), and Slic3r::GUI::Plater::priv::reset().
object_menu()
wxMenu * Slic3r::GUI::Plater::object_menu ()
{ return p->menus.object_menu();            }
References p.
Referenced by Slic3r::GUI::ObjectList::show_context_menu().
on_activate()
void Slic3r::GUI::Plater::on_activate ()
{
    this->p->show_delayed_error_message();
}
References p.
Referenced by Slic3r::GUI::MainFrame::MainFrame().
on_bed_type_change()
void Slic3r::GUI::Plater::on_bed_type_change (BedType bed_type)
{
    sidebar().on_bed_type_change(bed_type);
}
References Slic3r::GUI::Sidebar::on_bed_type_change(), and sidebar().
Referenced by load_gcode().
on_change_color_mode()
void Slic3r::GUI::Plater::on_change_color_mode (SimpleEvent & evt)
on_config_change()
void Slic3r::GUI::Plater::on_config_change (const DynamicPrintConfig & config)
{
    bool update_scheduled = false;
    bool bed_shape_changed = false;
    //bool print_sequence_changed = false;
    t_config_option_keys diff_keys = p->config->diff(config);
    for (auto opt_key : diff_keys) {
        if (opt_key == "filament_colour") {
            update_scheduled = true; // update should be scheduled (for update 3DScene) #2738
            if (update_filament_colors_in_full_config()) {
                p->sidebar->obj_list()->update_filament_colors();
                dynamic_filament_list.update();
                continue;
            }
        }
        if (opt_key == "material_colour") {
            update_scheduled = true; // update should be scheduled (for update 3DScene)
        }
        p->config->set_key_value(opt_key, config.option(opt_key)->clone());
        if (opt_key == "printer_technology") {
            this->set_printer_technology(config.opt_enum<PrinterTechnology>(opt_key));
            // print technology is changed, so we should to update a search list
            p->sidebar->update_searcher();
            p->reset_gcode_toolpaths();
            p->view3D->get_canvas3d()->reset_sequential_print_clearance();
            //BBS: invalid all the slice results
            p->partplate_list.invalid_all_slice_result();
        }
        //BBS: add bed_exclude_area
        else if (opt_key == "printable_area" || opt_key == "bed_exclude_area"
            || opt_key == "bed_custom_texture" || opt_key == "bed_custom_model"
            || opt_key == "extruder_clearance_height_to_lid"
            || opt_key == "extruder_clearance_height_to_rod") {
            bed_shape_changed = true;
            update_scheduled = true;
        }
        else if (opt_key == "bed_shape" || opt_key == "bed_custom_texture" || opt_key == "bed_custom_model") {
            bed_shape_changed = true;
            update_scheduled = true;
        }
        else if (boost::starts_with(opt_key, "enable_prime_tower") ||
            boost::starts_with(opt_key, "prime_tower") ||
            boost::starts_with(opt_key, "wipe_tower") ||
            // opt_key == "filament_minimal_purge_on_wipe_tower" // ? #ys_FIXME
            opt_key == "single_extruder_multi_material" ||
            // BBS
            opt_key == "prime_volume") {
            update_scheduled = true;
        }
        else if(opt_key == "extruder_colour") {
            update_scheduled = true;
            //p->sidebar->obj_list()->update_extruder_colors();
        }
        else if (opt_key == "printable_height") {
            bed_shape_changed = true;
            update_scheduled = true;
        }
        else if (opt_key == "print_sequence") {
            update_scheduled = true;
            //print_sequence_changed = true;
        }
        else if (opt_key == "printer_model") {
            p->reset_gcode_toolpaths();
            // update to force bed selection(for texturing)
            bed_shape_changed = true;
            update_scheduled = true;
        }
        // BBS
        else if (opt_key == "support_interface_filament" ||
            opt_key == "support_filament") {
            update_scheduled = true;
        }
    }
    if (bed_shape_changed)
        set_bed_shape();
    config_change_notification(config, std::string("print_sequence"));
    if (update_scheduled)
        update();
    if (p->main_frame->is_loaded())
        this->p->schedule_background_process();
}
References Slic3r::ConfigOption::clone(), config(), config_change_notification(), Slic3r::GUI::dynamic_filament_list, Slic3r::DynamicConfig::opt_enum(), Slic3r::ConfigBase::option(), p, set_bed_shape(), set_printer_technology(), update(), Slic3r::GUI::DynamicFilamentList::update(), and update_filament_colors_in_full_config().
on_filaments_change()
void Slic3r::GUI::Plater::on_filaments_change (size_t extruders_count)
{
    // only update elements in plater
    update_filament_colors_in_full_config();
    sidebar().on_filaments_change(num_filaments);
    sidebar().obj_list()->update_objects_list_filament_column(num_filaments);
    for (ModelObject* mo : wxGetApp().model().objects) {
        for (ModelVolume* mv : mo->volumes) {
            mv->update_extruder_count(num_filaments);
        }
    }
}
References Slic3r::GUI::Sidebar::obj_list(), Slic3r::GUI::Sidebar::on_filaments_change(), sidebar(), update_filament_colors_in_full_config(), Slic3r::GUI::ObjectList::update_objects_list_filament_column(), and Slic3r::ModelObject::volumes.
only_gcode_mode()
bool Slic3r::GUI::Plater::only_gcode_mode () inline
{ return m_only_gcode; }
References m_only_gcode.
open_3mf_file()
bool Slic3r::GUI::Plater::open_3mf_file (const fs::path & file_path)
{
    std::string filename = encode_path(file_path.filename().string().c_str());
    if (!boost::algorithm::iends_with(filename, ".3mf")) {
        return false;
    }
    LoadType load_type = LoadType::Unknown;
    if (!model().objects.empty()) {
        bool show_drop_project_dialog = true;
        if (show_drop_project_dialog) {
            ProjectDropDialog dlg(filename);
            if (dlg.ShowModal() == wxID_OK) {
                int choice = dlg.get_action();
                load_type  = static_cast<LoadType>(choice);
                wxGetApp().app_config->set("import_project_action", std::to_string(choice));
                // BBS: jump to plater panel
                wxGetApp().mainframe->select_tab(MainFrame::tp3DEditor);
            }
        } else
            load_type = static_cast<LoadType>(
                std::clamp(std::stoi(wxGetApp().app_config->get("import_project_action")), static_cast<int>(LoadType::OpenProject), static_cast<int>(LoadType::LoadConfig)));
    } else
        load_type = LoadType::OpenProject;
    if (load_type == LoadType::Unknown) return false;
    switch (load_type) {
        case LoadType::OpenProject: {
            if (wxGetApp().can_load_project())
                load_project(from_path(file_path));
            break;
        }
        case LoadType::LoadGeometry: {
            Plater::TakeSnapshot snapshot(this, "Import Object");
            load_files({file_path}, LoadStrategy::LoadModel);
            break;
        }
        case LoadType::LoadConfig: {
            load_files({file_path}, LoadStrategy::LoadConfig);
            break;
        }
        case LoadType::Unknown: {
            assert(false);
            break;
        }
    }
    return true;
}
References Slic3r::encode_path(), Slic3r::GUI::from_path(), Slic3r::GUI::ProjectDropDialog::get_action(), load_files(), load_project(), Slic3r::LoadConfig, Slic3r::GUI::LoadConfig, Slic3r::GUI::LoadGeometry, Slic3r::LoadModel, model(), Slic3r::GUI::OpenProject, Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::GUI::MainFrame::tp3DEditor, and Slic3r::GUI::Unknown.
Referenced by add_file(), and load_files().
operator=() [1/2]
Plater & Slic3r::GUI::Plater::operator= (const Plater &) delete
operator=() [2/2]
Plater & Slic3r::GUI::Plater::operator= (Plater &&) delete
optimize_rotation()
void Slic3r::GUI::Plater::optimize_rotation ()
{ if (!p->m_ui_jobs.is_any_running()) p->m_ui_jobs.optimize_rotation(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_sla_object_menu().
orient()
void Slic3r::GUI::Plater::orient ()
{
    p->m_ui_jobs.orient();
}
References p.
Referenced by _calib_pa_pattern(), Slic3r::GUI::MenuFactory::create_plate_menu(), and select_plate_by_hover_id().
part_menu()
wxMenu * Slic3r::GUI::Plater::part_menu ()
{ return p->menus.part_menu();              }
References p.
Referenced by Slic3r::GUI::ObjectList::show_context_menu().
paste_from_clipboard()
void Slic3r::GUI::Plater::paste_from_clipboard ()
{
    if (!can_paste_from_clipboard())
        return;
    Plater::TakeSnapshot snapshot(this, "Paste From Clipboard");
    // At first try to paste values from the ObjectList's clipboard
    // to check if Settings or Layers were copied
    // and then paste from the 3DCanvas's clipboard if not
    if (!p->sidebar->obj_list()->paste_from_clipboard())
        p->view3D->get_canvas3d()->get_selection().paste_from_clipboard();
}
References can_paste_from_clipboard(), and p.
plate_menu()
wxMenu * Slic3r::GUI::Plater::plate_menu ()
{ return p->menus.plate_menu();             }
References p.
Referenced by Slic3r::GUI::ObjectList::show_context_menu().
PopupMenu() [1/2]
bool Slic3r::GUI::Plater::PopupMenu (wxMenu * menu, const wxPoint & pos = wxDefaultPosition)
{
    // Don't want to wake up and trigger reslicing while tracking the pop-up menu.
    SuppressBackgroundProcessingUpdate sbpu;
    // When tracking a pop-up menu, postpone error messages from the slicing result.
    m_tracking_popup_menu = true;
    bool out = this->wxPanel::PopupMenu(menu, pos);
    m_tracking_popup_menu = false;
    if (! m_tracking_popup_menu_error_message.empty()) {
        // Don't know whether the CallAfter is necessary, but it should not hurt.
        // The menus likely sends out some commands, so we may be safer if the dialog is shown after the menu command is processed.
        wxString message = std::move(m_tracking_popup_menu_error_message);
        wxTheApp->CallAfter([message, this]() { show_error(this, message); });
        m_tracking_popup_menu_error_message.clear();
    }
    return out;
}
References m_tracking_popup_menu, m_tracking_popup_menu_error_message, out, and Slic3r::GUI::show_error().
Referenced by Slic3r::GUI::ObjectList::show_context_menu().
PopupMenu() [2/2]
bool Slic3r::GUI::Plater::PopupMenu (wxMenu * menu, int x, int y) inline
{ return this->PopupMenu(menu, wxPoint(x, y)); }
References PopupMenu().
Referenced by PopupMenu().
PopupObjectTable()
bool Slic3r::GUI::Plater::PopupObjectTable (int object_id, int volume_id, const wxPoint & position)
{
    return p->PopupObjectTable(object_id, volume_id, position);
}
References p.
PopupObjectTableBySelection()
bool Slic3r::GUI::Plater::PopupObjectTableBySelection ()
{
    wxDataViewItem item;
    int obj_idx, vol_idx;
    const wxPoint pos = wxPoint(0, 0);  //Fake position
    wxGetApp().obj_list()->get_selected_item_indexes(obj_idx, vol_idx, item);
    return p->PopupObjectTable(obj_idx, vol_idx, pos);
}
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_per_object_settings().
post_process_string_object_exception()
void Slic3r::GUI::Plater::post_process_string_object_exception (StringObjectException & err)
{
    if (err.type == StringExceptionType::STRING_EXCEPT_FILAMENT_NOT_MATCH_BED_TYPE) {
        try {
            int extruder_id = atoi(err.params[2].c_str()) - 1;
            if (extruder_id < wxGetApp().preset_bundle->filament_presets.size()) {
                std::string filament_name = wxGetApp().preset_bundle->filament_presets[extruder_id];
                for (auto filament : wxGetApp().preset_bundle->filaments) {
                    if (filament.name == filament_name) {
                        filament_name = filament.alias;
                        break;
                    }
                }
                err.string = format(_L("Plate% d: %s is not suggested to be used to print filament %s(%s). If you still want to do this printing, please set this filament's bed temperature to non zero."),
                             err.params[0], err.params[1], err.params[2], filament_name);
                err.string += "\n";
            }
        } catch (...) {
            ;
        }
    }
    return;
}
References _L, Slic3r::GUI::format(), Slic3r::StringObjectException::params, Slic3r::StringObjectException::string, Slic3r::STRING_EXCEPT_FILAMENT_NOT_MATCH_BED_TYPE, and Slic3r::StringObjectException::type.
Referenced by validate_current_plate().
print_job_finished()
void Slic3r::GUI::Plater::print_job_finished (wxCommandEvent & evt)
{
    Slic3r::DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    dev->set_selected_machine(evt.GetString().ToStdString());
    p->hide_select_machine_dlg();
    p->main_frame->request_select_tab(MainFrame::TabPosition::tpMonitor);
    //jump to monitor and select device status panel
    MonitorPanel* curr_monitor = p->main_frame->m_monitor;
    if(curr_monitor)
       curr_monitor->get_tabpanel()->ChangeSelection(MonitorPanel::PrinterTab::PT_STATUS);
}
References Tabbook::ChangeSelection(), Slic3r::GUI::MonitorPanel::get_tabpanel(), p, Slic3r::GUI::MonitorPanel::PT_STATUS, Slic3r::DeviceManager::set_selected_machine(), and Slic3r::GUI::MainFrame::tpMonitor.
printer_technology()
PrinterTechnology Slic3r::GUI::Plater::printer_technology () const
{
    return p->printer_technology;
}
References p.
Referenced by Slic3r::GUI::Plater::priv::can_split_to_volumes(), export_gcode(), export_toolpaths_to_obj(), Slic3r::GUI::Plater::priv::init_notification_manager(), Slic3r::GUI::Plater::priv::layers_height_allowed(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::priv::on_process_completed(), Slic3r::GUI::Plater::priv::on_right_click(), Slic3r::GUI::Plater::priv::on_slicing_completed(), Slic3r::GUI::Plater::priv::on_slicing_update(), reslice(), Slic3r::GUI::Plater::priv::set_current_panel(), set_printer_technology(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::MainFrame::technology_changed(), Slic3r::GUI::Plater::priv::undo_redo_to(), Slic3r::GUI::Plater::priv::update(), Slic3r::GUI::Plater::priv::update_background_process(), and Slic3r::GUI::MainFrame::update_menubar().
publish_job_finished()
void Slic3r::GUI::Plater::publish_job_finished (wxCommandEvent & evt)
{
    p->m_publish_dlg->EndModal(wxID_OK);
   // GUI::wxGetApp().load_url(evt.GetString());
   //GUI::wxGetApp().open_publish_page_dialog(evt.GetString());
}
References p.
publish_project()
void Slic3r::GUI::Plater::publish_project ()
{
    return;
}
redo()
void Slic3r::GUI::Plater::redo ()
{ p->redo(); }
References p.
Referenced by BBLTopbar::OnRedo().
redo_to()
void Slic3r::GUI::Plater::redo_to (int selection)
{
    if (selection == 0) {
        p->redo();
        return;
    }
    const int idx = p->get_active_snapshot_index() + selection + 1;
    p->undo_redo_to(p->undo_redo_stack().snapshots()[idx].timestamp);
}
References p.
refresh_print()
void Slic3r::GUI::Plater::refresh_print ()
{
    p->preview->refresh_print();
}
References p.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::open_preferences(), select_plate(), and select_plate_by_hover_id().
reload_all_from_disk()
void Slic3r::GUI::Plater::reload_all_from_disk ()
{
    p->reload_all_from_disk();
}
References p.
reload_from_disk()
void Slic3r::GUI::Plater::reload_from_disk ()
{
    p->reload_from_disk();
}
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_reload_from_disk(), and Slic3r::GUI::Plater::priv::reload_all_from_disk().
reload_gcode_from_disk()
void Slic3r::GUI::Plater::reload_gcode_from_disk ()
{
    wxString filename(m_last_loaded_gcode);
    m_last_loaded_gcode.clear();
    load_gcode(filename);
}
References load_gcode(), and m_last_loaded_gcode.
remove()
void Slic3r::GUI::Plater::remove (size_t obj_idx)
{ p->remove(obj_idx); }
References p.
Referenced by convert_unit(), cut(), decrease_instances(), merge(), segment(), and Slic3r::GUI::Plater::priv::split_object().
remove_curr_plate_all()
void Slic3r::GUI::Plater::remove_curr_plate_all ()
{ p->remove_curr_plate_all(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_plate_menu().
remove_selected()
void Slic3r::GUI::Plater::remove_selected ()
{
    /*if (p->get_selection().is_empty())
        return;*/
    if (p->get_curr_selection().is_empty())
        return;
    // BBS: check before deleting object
    if (!p->can_delete())
        return;
    Plater::TakeSnapshot snapshot(this, "Delete Selected Objects");
    p->m_ui_jobs.cancel_all();
    //BBS delete current selected
    // p->view3D->delete_selected();
    p->get_current_canvas3D()->delete_selected();
}
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_delete().
replace_with_stl()
void Slic3r::GUI::Plater::replace_with_stl ()
{
    p->replace_with_stl();
}
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_replace_with_stl().
request_download_project()
void Slic3r::GUI::Plater::request_download_project (std::string project_id)
{
    wxCommandEvent* event = new wxCommandEvent(EVT_DOWNLOAD_PROJECT);
    event->SetString(project_id);
    wxQueueEvent(this, event);
}
Referenced by Slic3r::GUI::GUI_App::download_project().
request_model_download()
void Slic3r::GUI::Plater::request_model_download (std::string url)
{
    wxCommandEvent* event = new wxCommandEvent(EVT_IMPORT_MODEL_ID);
    event->SetString(url);
    wxQueueEvent(this, event);
}
Referenced by Slic3r::GUI::GUI_App::request_model_download().
reset()
void Slic3r::GUI::Plater::reset (bool apply_presets_change = false)
{ p->reset(apply_presets_change); }
References p.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), load_project(), new_project(), and reset_with_confirm().
reset_canvas_volumes()
void Slic3r::GUI::Plater::reset_canvas_volumes ()
{
    p->reset_canvas_volumes();
}
References p.
reset_gcode_toolpaths()
void Slic3r::GUI::Plater::reset_gcode_toolpaths ()
{
    //BBS: add some logs
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": reset the gcode viewer's toolpaths");
    p->reset_gcode_toolpaths();
}
References p.
Referenced by Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::GUI::PartPlateList::rebuild_plates_after_deserialize(), Slic3r::GUI::Plater::priv::reset(), reslice(), select_plate(), Slic3r::GUI::Plater::priv::set_current_panel(), and Slic3r::GUI::Plater::priv::update_background_process().
reset_last_loaded_gcode()
void Slic3r::GUI::Plater::reset_last_loaded_gcode () inline
{ m_last_loaded_gcode = ""; }
References m_last_loaded_gcode.
reset_project_dirty_after_save()
void Slic3r::GUI::Plater::reset_project_dirty_after_save ()
{ p->reset_project_dirty_after_save(); }
References p.
Referenced by new_project(), and save_project().
reset_project_dirty_initial_presets()
void Slic3r::GUI::Plater::reset_project_dirty_initial_presets ()
{ p->reset_project_dirty_initial_presets(); }
References p.
Referenced by load_project(), and new_project().
reset_with_confirm()
void Slic3r::GUI::Plater::reset_with_confirm ()
{
    if (p->model.objects.empty() || MessageDialog(static_cast<wxWindow *>(this), _L("All objects will be removed, continue?"),
                                                  wxString(SLIC3R_APP_FULL_NAME) + " - " + _L("Delete all"), wxYES_NO | wxCANCEL | wxYES_DEFAULT | wxCENTRE)
                                            .ShowModal() == wxID_YES) {
        reset();
        // BBS: jump to plater panel
        wxGetApp().mainframe->select_tab(size_t(0));
    }
}
References _L, p, reset(), and SLIC3R_APP_FULL_NAME.
reslice()
void Slic3r::GUI::Plater::reslice ()
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: enter, process_completed_with_error=%2%")%__LINE__ %p->process_completed_with_error;
    // There is "invalid data" button instead "slice now"
    if (p->process_completed_with_error == p->partplate_list.get_curr_plate_index())
    {
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": process_completed_with_error, return directly");
        reset_gcode_toolpaths();
        return;
    }
    // In case SLA gizmo is in editing mode, refuse to continue
    // and notify user that he should leave it first.
    if (get_view3D_canvas3D()->get_gizmos_manager().is_in_editing_mode(true))
        return;
    // Stop arrange and (or) optimize rotation tasks.
    this->stop_jobs();
    // regenerate CalibPressureAdvancePattern custom G-code to apply changes
    if (model().calib_pa_pattern) {
        PresetBundle* preset_bundle = wxGetApp().preset_bundle;
        model().calib_pa_pattern->generate_custom_gcodes(
            wxGetApp().preset_bundle->full_config(),
            preset_bundle->printers.get_edited_preset().has_lidar(preset_bundle),
            model(),
            get_partplate_list().get_current_plate_origin()
        );
    }
    if (printer_technology() == ptSLA) {
        for (auto& object : model().objects)
            if (object->sla_points_status == sla::PointsStatus::NoPoints)
                object->sla_points_status = sla::PointsStatus::Generating;
    }
    //FIXME Don't reslice if export of G-code or sending to OctoPrint is running.
    // bitmask of UpdateBackgroundProcessReturnState
    unsigned int state = this->p->update_background_process(true);
    if (state & priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE)
        this->p->view3D->reload_scene(false);
    // If the SLA processing of just a single object's supports is running, restart slicing for the whole object.
    this->p->background_process.set_task(PrintBase::TaskParams());
    // Only restarts if the state is valid.
    //BBS: jusdge the result
    bool result = this->p->restart_background_process(state | priv::UPDATE_BACKGROUND_PROCESS_FORCE_RESTART);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(", Line %1%: restart background,state=%2%, result=%3%")%__LINE__%state %result;
    if ((state & priv::UPDATE_BACKGROUND_PROCESS_INVALID) != 0)
    {
        //BBS: add logs
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": state %1% is UPDATE_BACKGROUND_PROCESS_INVALID, can not slice") % state;
        p->update_fff_scene_only_shells();
        return;
    }
    if ((!result) && p->m_slice_all && (p->m_cur_slice_plate < (p->partplate_list.get_plate_count() - 1)))
    {
        //slice next
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": in slicing all, current plate %1% already sliced, skip to next") % p->m_cur_slice_plate ;
        SlicingProcessCompletedEvent evt(EVT_PROCESS_COMPLETED, 0,
            SlicingProcessCompletedEvent::Finished, nullptr);
        // Post the "complete" callback message, so that it will slice the next plate soon
        wxQueueEvent(this, evt.Clone());
        p->m_is_slicing = true;
        this->SetDropTarget(nullptr);
        if (p->m_cur_slice_plate == 0)
            reset_gcode_toolpaths();
        return;
    }
    if (result) {
        p->m_is_slicing = true;
        this->SetDropTarget(nullptr);
    }
    bool clean_gcode_toolpaths = true;
    // BBS
    if (p->background_process.running())
    {
        //p->ready_to_slice = false;
        p->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, false);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": background process is running, m_is_slicing is true");
    }
    else if (!p->background_process.empty() && !p->background_process.idle()) {
        //p->show_action_buttons(true);
        //p->ready_to_slice = true;
        p->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, true);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": background process changes to not_idle, set ready_to_slice back to true");
    }
    else {
        //BBS: add reset logic for empty plate
        PartPlate * current_plate = p->background_process.get_current_plate();
        if (!current_plate->has_printable_instances()) {
            clean_gcode_toolpaths = true;
            current_plate->update_slice_result_valid_state(false);
        }
        else {
            clean_gcode_toolpaths = false;
            current_plate->update_slice_result_valid_state(true);
        }
        p->main_frame->update_slice_print_status(MainFrame::eEventSliceUpdate, false);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": background process in idle state, use previous result, clean_gcode_toolpaths=%1%")%clean_gcode_toolpaths;
    }
    if (clean_gcode_toolpaths)
        reset_gcode_toolpaths();
    p->preview->reload_print(!clean_gcode_toolpaths);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": finished, started slicing for plate %1%") % p->partplate_list.get_curr_plate_index();
}
References Slic3r::Model::calib_pa_pattern, Slic3r::SlicingProcessCompletedEvent::Clone(), Slic3r::GUI::MainFrame::eEventSliceUpdate, Slic3r::SlicingProcessCompletedEvent::Finished, Slic3r::PresetBundle::full_config(), Slic3r::sla::Generating, Slic3r::PresetCollection::get_edited_preset(), get_partplate_list(), get_view3D_canvas3D(), Slic3r::Preset::has_lidar(), Slic3r::GUI::PartPlate::has_printable_instances(), model(), Slic3r::sla::NoPoints, Slic3r::Model::objects, p, printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptSLA, reset_gcode_toolpaths(), stop_jobs(), Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_FORCE_RESTART, Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_INVALID, Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE, and Slic3r::GUI::PartPlate::update_slice_result_valid_state().
Referenced by select_plate().
reslice_SLA_hollowing()
void Slic3r::GUI::Plater::reslice_SLA_hollowing (const ModelObject & object, bool postpone_error_messages = false)
{
    reslice_SLA_until_step(slaposDrillHoles, object, postpone_error_messages);
}
References reslice_SLA_until_step(), and Slic3r::slaposDrillHoles.
reslice_SLA_supports()
void Slic3r::GUI::Plater::reslice_SLA_supports (const ModelObject & object, bool postpone_error_messages = false)
{
    reslice_SLA_until_step(slaposPad, object, postpone_error_messages);
}
References reslice_SLA_until_step(), and Slic3r::slaposPad.
reslice_SLA_until_step()
void Slic3r::GUI::Plater::reslice_SLA_until_step (SLAPrintObjectStep step, const ModelObject & object, bool postpone_error_messages = false)
{
    //FIXME Don't reslice if export of G-code or sending to OctoPrint is running.
    // bitmask of UpdateBackgroundProcessReturnState
    unsigned int state = this->p->update_background_process(true, postpone_error_messages);
    if (state & priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE)
        this->p->view3D->reload_scene(false);
    if (this->p->background_process.empty() || (state & priv::UPDATE_BACKGROUND_PROCESS_INVALID))
        // Nothing to do on empty input or invalid configuration.
        return;
    // Limit calculation to the single object only.
    PrintBase::TaskParams task;
    task.single_model_object = object.id();
    // If the background processing is not enabled, calculate supports just for the single instance.
    // Otherwise calculate everything, but start with the provided object.
    if (!this->p->background_processing_enabled()) {
        task.single_model_instance_only = true;
        task.to_object_step = step;
    }
    this->p->background_process.set_task(task);
    // and let the background processing start.
    this->p->restart_background_process(state | priv::UPDATE_BACKGROUND_PROCESS_FORCE_RESTART);
}
References Slic3r::ObjectID::id, p, Slic3r::PrintBase::TaskParams::single_model_instance_only, Slic3r::PrintBase::TaskParams::single_model_object, Slic3r::PrintBase::TaskParams::to_object_step, Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_FORCE_RESTART, Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_INVALID, and Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE.
Referenced by reslice_SLA_hollowing(), and reslice_SLA_supports().
save_project()
int Slic3r::GUI::Plater::save_project (bool saveAs = false)
{
    //if (up_to_date(false, false)) // should we always save
    //    return;
    auto filename = get_project_filename(".3mf");
    if (!saveAs && filename.IsEmpty())
        saveAs = true;
    if (saveAs)
        filename = p->get_export_file(FT_3MF);
    if (filename.empty())
        return wxID_NO;
    if (filename == "<cancel>")
        return wxID_CANCEL;
    //BBS export 3mf without gcode
    if (export_3mf(into_path(filename), SaveStrategy::SplitModel | SaveStrategy::ShareMesh) < 0) {
        MessageDialog(this, _L("Failed to save the project.\nPlease check whether the folder exists online or if other programs open the project file."),
            _L("Save project"), wxOK | wxICON_WARNING).ShowModal();
        return wxID_CANCEL;
    }
    Slic3r::remove_backup(model(), false);
    p->set_project_filename(filename);
    up_to_date(true, false);
    up_to_date(true, true);
    wxGetApp().update_saved_preset_from_current_preset();
    reset_project_dirty_after_save();
    return wxID_YES;
}
References _L, export_3mf(), Slic3r::GUI::FT_3MF, get_project_filename(), Slic3r::GUI::into_path(), model(), p, Slic3r::remove_backup(), reset_project_dirty_after_save(), Slic3r::ShareMesh, Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::SplitModel, and up_to_date().
Referenced by Slic3r::GUI::MainFrame::MainFrame(), and BBLTopbar::OnSaveProject().
save_project_if_dirty()
int Slic3r::GUI::Plater::save_project_if_dirty (const wxString & reason)
{ return p->save_project_if_dirty(reason); }
References p.
scale_selection_to_fit_print_volume()
void Slic3r::GUI::Plater::scale_selection_to_fit_print_volume ()
{
    p->scale_selection_to_fit_print_volume();
}
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_scale_selection_to_fit_print_volume().
schedule_background_process()
void Slic3r::GUI::Plater::schedule_background_process (bool schedule = true)
{
    if (schedule)
        this->p->schedule_background_process();
    this->p->suppressed_backround_processing_update = false;
}
References p.
Referenced by Slic3r::GUI::Plater::priv::load_model_objects(), select_plate_by_hover_id(), and Slic3r::GUI::Plater::priv::update().
search()
void Slic3r::GUI::Plater::search (bool plater_is_active, Preset::Type type, wxWindow * tag, TextInput * etag, wxWindow * stag)
{
    if (plater_is_active) {
        if (is_preview_shown())
            return;
        // plater should be focused for correct navigation inside search window
        this->SetFocus();
        wxKeyEvent evt;
#ifdef __APPLE__
        evt.m_keyCode = 'f';
#else /* __APPLE__ */
        evt.m_keyCode = WXK_CONTROL_F;
#endif /* __APPLE__ */
        evt.SetControlDown(true);
        canvas3D()->on_char(evt);
    }
    else
        p->sidebar->get_searcher().show_dialog(type, tag, etag, stag);
}
References canvas3D(), is_preview_shown(), Slic3r::GUI::GLCanvas3D::on_char(), and p.
search_string_getter()
bool Slic3r::GUI::Plater::search_string_getter (int idx, const char ** label, const char ** tooltip)
{
    const Search::OptionsSearcher& search_list = p->sidebar->get_searcher();
    if (0 <= idx && (size_t)idx < search_list.size()) {
        search_list[idx].get_marked_label_and_tooltip(label, tooltip);
        return true;
    }
    return false;
}
References p, and Slic3r::Search::OptionsSearcher::size().
segment()
void Slic3r::GUI::Plater::segment (size_t obj_idx, size_t instance_idx, double smoothing_alpha = 0.5, int segment_number = 5)
{
    wxCHECK_RET(obj_idx < p->model.objects.size(), "obj_idx out of bounds");
    auto* object = p->model.objects[obj_idx];
    wxCHECK_RET(instance_idx < object->instances.size(), "instance_idx out of bounds");
    Plater::TakeSnapshot snapshot(this, "Segment");
    wxBusyCursor wait;
    // real process
    PresetBundle& preset_bundle = *wxGetApp().preset_bundle;
    const auto print_tech = preset_bundle.printers.get_edited_preset().printer_technology();
    const size_t filament_cnt = print_tech != ptFFF ? 1 : preset_bundle.filament_presets.size();
    const auto new_objects = object->segment(instance_idx, filament_cnt, smoothing_alpha, segment_number);
    remove(obj_idx);
    p->load_model_objects(new_objects);
    Selection& selection = p->get_selection();
    size_t last_id = p->model.objects.size() - 1;
    for (size_t i = 0; i < new_objects.size(); ++i)
    {
        selection.add_object((unsigned int)(last_id - i), i == 0);
    }
}
References Slic3r::GUI::Selection::add_object(), Slic3r::PresetBundle::filament_presets, Slic3r::PresetCollection::get_edited_preset(), model(), Slic3r::Model::objects, p, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptFFF, and remove().
select_all()
void Slic3r::GUI::Plater::select_all ()
{ p->select_all(); }
References p.
Referenced by Slic3r::GUI::Plater::priv::reload_all_from_disk().
select_curr_plate_all()
void Slic3r::GUI::Plater::select_curr_plate_all ()
{ p->select_curr_plate_all(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_plate_menu().
select_plate()
int Slic3r::GUI::Plater::select_plate (int plate_index, bool need_slice = false)
{
    int ret;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: plate %2%, need_slice %3% ")%__LINE__ %plate_index  %need_slice;
    take_snapshot("select partplate!");
    ret = p->partplate_list.select_plate(plate_index);
    if (!ret) {
        if (is_view3D_shown())
            wxGetApp().plater()->canvas3D()->render();
    }
    if ((!ret) && (p->background_process.can_switch_print()))
    {
        //select successfully
        p->partplate_list.update_slice_context_to_current_plate(p->background_process);
        p->preview->update_gcode_result(p->partplate_list.get_current_slice_result());
        p->update_print_volume_state();
        PartPlate* part_plate = p->partplate_list.get_curr_plate();
        bool result_valid = part_plate->is_slice_result_valid();
        PrintBase* print = nullptr;
        GCodeResult* gcode_result = nullptr;
        Print::ApplyStatus invalidated;
        part_plate->get_print(&print, &gcode_result, NULL);
        //always apply the current plate's print
        invalidated = p->background_process.apply(this->model(), wxGetApp().preset_bundle->full_config());
        bool model_fits, validate_err;
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: plate %2%, after apply, invalidated= %3%, previous result_valid %4% ")%__LINE__ %plate_index  %invalidated %result_valid;
        if (result_valid)
        {
            if (is_preview_shown())
            {
                if (need_slice) { //from preview's thumbnail
                    if ((invalidated & PrintBase::APPLY_STATUS_INVALIDATED) || (gcode_result->moves.empty())){
                        if (invalidated & PrintBase::APPLY_STATUS_INVALIDATED)
                            part_plate->update_slice_result_valid_state(false);
                        p->process_completed_with_error = -1;
                        p->m_slice_all = false;
                        reset_gcode_toolpaths();
                        reslice();
                    }
                    else {
                        validate_current_plate(model_fits, validate_err);
                        //just refresh_print
                        refresh_print();
                        p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, false, true);
                    }
                }
                else {// from multiple slice's next
                    //do nothing
                }
            }
            else
            {
                validate_current_plate(model_fits, validate_err);
                if (invalidated & PrintBase::APPLY_STATUS_INVALIDATED)
                {
                    part_plate->update_slice_result_valid_state(false);
                    // BBS
                    //p->show_action_buttons(true);
                    //p->ready_to_slice = true;
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, true);
                }
                else
                {
                    // BBS
                    //p->show_action_buttons(false);
                    //p->ready_to_slice = false;
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, false);
                    refresh_print();
                }
            }
        }
        else
        {
            //check inside status
            //model_fits = p->view3D->get_canvas3d()->check_volumes_outside_state() != ModelInstancePVS_Partly_Outside;
            //bool validate_err = false;
            validate_current_plate(model_fits, validate_err);
            if (model_fits && !validate_err) {
                p->process_completed_with_error = -1;
            }
            else {
                p->process_completed_with_error = p->partplate_list.get_curr_plate_index();
            }
            if (is_preview_shown())
            {
                if (need_slice)
                {
                    //p->process_completed_with_error = -1;
                    p->m_slice_all = false;
                    reset_gcode_toolpaths();
                    if (model_fits && !validate_err)
                        reslice();
                    else {
                        p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, false);
                        //sometimes the previous print's sliced result is still valid, but the newly added object is laid over the boundary
                        //then the print toolpath will be shown, so we should not refresh print here, only onload shell
                        //refresh_print();
                        p->update_fff_scene_only_shells();
                    }
                }
                else {
                    //p->ready_to_slice = false;
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, false);
                    refresh_print();
                }
            }
            else
            {
                //validate_current_plate(model_fits, validate_err);
                //check inside status
                /*if (model_fits && !validate_err){
                    p->process_completed_with_error = -1;
                }
                else {
                    p->process_completed_with_error = p->partplate_list.get_curr_plate_index();
                }*/
                // BBS: don't show action buttons
                //p->show_action_buttons(true);
                //p->ready_to_slice = true;
                if (model_fits && part_plate->has_printable_instances())
                {
                    //p->view3D->get_canvas3d()->post_event(Event<bool>(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS, true));
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, true);
                }
                else
                {
                    //p->view3D->get_canvas3d()->post_event(Event<bool>(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS, false));
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, false);
                }
            }
        }
    }
    SimpleEvent event(EVT_GLCANVAS_PLATE_SELECT);
    p->on_plate_selected(event);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: plate %2%, return %3%")%__LINE__ %plate_index %ret;
    return ret;
}
References Slic3r::PrintBase::APPLY_STATUS_INVALIDATED, Slic3r::GUI::MainFrame::eEventPlateUpdate, Slic3r::GUI::PartPlate::get_print(), Slic3r::GUI::PartPlate::has_printable_instances(), is_preview_shown(), Slic3r::GUI::PartPlate::is_slice_result_valid(), is_view3D_shown(), model(), Slic3r::GCodeProcessorResult::moves, NULL, p, refresh_print(), reset_gcode_toolpaths(), reslice(), take_snapshot(), Slic3r::GUI::PartPlate::update_slice_result_valid_state(), and validate_current_plate().
Referenced by select_plate_by_hover_id(), and select_sliced_plate().
select_plate_by_hover_id()
int Slic3r::GUI::Plater::select_plate_by_hover_id (int hover_id, bool right_click = false)
{
    int ret;
    int action, plate_index;
    plate_index = hover_id / PartPlate::GRABBER_COUNT;
    action = hover_id % PartPlate::GRABBER_COUNT;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": enter, hover_id %1%, plate_index %2%, action %3%")%hover_id % plate_index %action;
    if (action == 0)
    {
        //select plate
        ret = p->partplate_list.select_plate(plate_index);
        if (!ret) {
            SimpleEvent event(EVT_GLCANVAS_PLATE_SELECT);
            p->on_plate_selected(event);
        }
        if ((!ret)&&(p->background_process.can_switch_print()))
        {
            //select successfully
            p->partplate_list.update_slice_context_to_current_plate(p->background_process);
            p->preview->update_gcode_result(p->partplate_list.get_current_slice_result());
            p->update_print_volume_state();
            PartPlate* part_plate = p->partplate_list.get_curr_plate();
            bool result_valid = part_plate->is_slice_result_valid();
            PrintBase* print = nullptr;
            GCodeResult* gcode_result = nullptr;
            Print::ApplyStatus invalidated;
            part_plate->get_print(&print, &gcode_result, NULL);
            //always apply the current plate's print
            invalidated = p->background_process.apply(this->model(), wxGetApp().preset_bundle->full_config());
            bool model_fits, validate_err;
            validate_current_plate(model_fits, validate_err);
            BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: after apply, invalidated= %2%, previous result_valid %3% ")%__LINE__ % invalidated %result_valid;
            if (result_valid)
            {
                if (invalidated & PrintBase::APPLY_STATUS_INVALIDATED)
                {
                    //bool model_fits, validate_err;
                    //validate_current_plate(model_fits, validate_err);
                    part_plate->update_slice_result_valid_state(false);
                    // BBS
                    //p->show_action_buttons(true);
                    //p->ready_to_slice = true;
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, true);
                }
                else
                {
                    // BBS
                    //p->show_action_buttons(false);
                    //validate_current_plate(model_fits, validate_err);
                    //p->ready_to_slice = false;
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, false);
                    refresh_print();
                }
            }
            else
            {
                //check inside status
                if (model_fits && !validate_err){
                    p->process_completed_with_error = -1;
                }
                else {
                    p->process_completed_with_error = p->partplate_list.get_curr_plate_index();
                }
                // BBS: don't show action buttons
                //p->show_action_buttons(true);
                //p->ready_to_slice = true;
                if (model_fits && part_plate->has_printable_instances())
                {
                    //p->view3D->get_canvas3d()->post_event(Event<bool>(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS, true));
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": will set can_slice to true");
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, true);
                }
                else
                {
                    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": will set can_slice to false, has_printable_instances %1%")%part_plate->has_printable_instances();
                    //p->view3D->get_canvas3d()->post_event(Event<bool>(EVT_GLCANVAS_ENABLE_ACTION_BUTTONS, false));
                    p->main_frame->update_slice_print_status(MainFrame::eEventPlateUpdate, false);
                }
            }
        }
    }
    else if ((action == 1)&&(!right_click))
    {
        //delete plate
        ret = delete_plate(plate_index);
    }
    else if ((action == 2)&&(!right_click))
    {
        //arrange the plate
        //take_snapshot("select_orient partplate");
        ret = select_plate(plate_index);
        if (!ret)
        {
            set_prepare_state(Job::PREPARE_STATE_MENU);
            orient();
        }
        else
        {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "can not select plate %1%" << plate_index;
            ret = -1;
        }
    }
    else if ((action == 3)&&(!right_click))
    {
        //arrange the plate
        //take_snapshot("select_arrange partplate");
        ret = select_plate(plate_index);
        if (!ret)
        {
            if (last_arrange_job_is_finished()) {
                set_prepare_state(Job::PREPARE_STATE_MENU);
                arrange();
            }
        }
        else
        {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "can not select plate %1%" << plate_index;
            ret = -1;
        }
    }
    else if ((action == 4)&&(!right_click))
    {
        //lock the plate
        take_snapshot("lock partplate");
        ret = p->partplate_list.lock_plate(plate_index, !p->partplate_list.is_locked(plate_index));
    }
    else if ((action == 5)&&(!right_click))
    {
        //set the plate type
        ret = select_plate(plate_index);
        if (!ret) {
            PlateSettingsDialog dlg(this, wxID_ANY, _L("Plate Settings"));
            PartPlate* curr_plate = p->partplate_list.get_curr_plate();
            dlg.sync_bed_type(curr_plate->get_bed_type());
            auto curr_print_seq = curr_plate->get_print_seq();
            if (curr_print_seq != PrintSequence::ByDefault) {
                dlg.sync_print_seq(int(curr_print_seq) + 1);
            }
            else
                dlg.sync_print_seq(0);
            dlg.set_plate_name(from_u8(curr_plate->get_plate_name()));
            dlg.Bind(EVT_SET_BED_TYPE_CONFIRM, [this, plate_index, &dlg](wxCommandEvent& e) {
                PartPlate *curr_plate = p->partplate_list.get_curr_plate();
                BedType old_bed_type = curr_plate->get_bed_type();
                auto bt_sel = BedType(dlg.get_bed_type_choice());
                if (old_bed_type != bt_sel) {
                    curr_plate->set_bed_type(bt_sel);
                    update_project_dirty_from_presets();
                    set_plater_dirty(true);
                }
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("select bed type %1% for plate %2% at plate side")%bt_sel %plate_index;
                int ps_sel = dlg.get_print_seq_choice();
                if (ps_sel != 0)
                    curr_plate->set_print_seq(PrintSequence(ps_sel - 1));
                else
                    curr_plate->set_print_seq(PrintSequence::ByDefault);
                update_project_dirty_from_presets();
                set_plater_dirty(true);
                BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("select print sequence %1% for plate %2% at plate side")%ps_sel %plate_index;
                auto plate_config = *(curr_plate->config());
                wxGetApp().plater()->config_change_notification(plate_config, std::string("print_sequence"));
                update();
                });
            dlg.ShowModal();
            curr_plate->set_plate_name(dlg.get_plate_name().ToUTF8().data());
            this->schedule_background_process();
        }
        else {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "can not select plate %1%" << plate_index;
            ret = -1;
        }
    }
    else
    {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << "invalid action %1%, with right_click=%2%" << action << right_click;
        ret = -1;
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(" %1%: return %2%")%__LINE__ % ret;
    return ret;
}
References _L, Slic3r::PrintBase::APPLY_STATUS_INVALIDATED, arrange(), Slic3r::ByDefault, Slic3r::GUI::PartPlate::config(), delete_plate(), Slic3r::GUI::MainFrame::eEventPlateUpdate, error, Slic3r::GUI::from_u8(), Slic3r::GUI::PartPlate::get_bed_type(), Slic3r::GUI::PlateSettingsDialog::get_bed_type_choice(), Slic3r::GUI::PartPlate::get_plate_name(), Slic3r::GUI::PlateSettingsDialog::get_plate_name(), Slic3r::GUI::PartPlate::get_print(), Slic3r::GUI::PartPlate::get_print_seq(), Slic3r::GUI::PlateSettingsDialog::get_print_seq_choice(), Slic3r::GUI::PartPlate::GRABBER_COUNT, Slic3r::GUI::PartPlate::has_printable_instances(), Slic3r::GUI::PartPlate::is_slice_result_valid(), last_arrange_job_is_finished(), model(), NULL, orient(), p, Slic3r::GUI::Job::PREPARE_STATE_MENU, refresh_print(), schedule_background_process(), select_plate(), Slic3r::GUI::PartPlate::set_bed_type(), Slic3r::GUI::PartPlate::set_plate_name(), Slic3r::GUI::PlateSettingsDialog::set_plate_name(), set_plater_dirty(), set_prepare_state(), Slic3r::GUI::PartPlate::set_print_seq(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::GUI::PlateSettingsDialog::sync_bed_type(), Slic3r::GUI::PlateSettingsDialog::sync_print_seq(), take_snapshot(), update(), update_project_dirty_from_presets(), Slic3r::GUI::PartPlate::update_slice_result_valid_state(), and validate_current_plate().
select_sliced_plate()
int Slic3r::GUI::Plater::select_sliced_plate (int plate_index)
{
    int ret = 0;
    BOOST_LOG_TRIVIAL(info) << "select_sliced_plate plate_idx=" << plate_index;
    Freeze();
    ret = select_plate(plate_index, true);
    if (ret)
    {
        BOOST_LOG_TRIVIAL(error) << "select_plate error for plate_idx=" << plate_index;
        Thaw();
        return -1;
    }
    p->partplate_list.select_plate_view();
    Thaw();
    return ret;
}
References error, p, and select_plate().
select_view()
void Slic3r::GUI::Plater::select_view (const std::string & direction)
{ p->select_view(direction); }
References p.
select_view_3D()
void Slic3r::GUI::Plater::select_view_3D (const std::string & name, bool no_slice = true)
{ p->select_view_3D(name, no_slice); }
References p.
Referenced by Slic3r::GUI::GUI_App::post_init().
send_gcode()
int Slic3r::GUI::Plater::send_gcode (int plate_idx = -1, Export3mfProgressFn proFn = nullptr)
{
    int result = 0;
    /* generate 3mf */
    if (plate_idx == PLATE_CURRENT_IDX) {
        p->m_print_job_data.plate_idx = get_partplate_list().get_curr_plate_index();
    }
    else {
        p->m_print_job_data.plate_idx = plate_idx;
    }
    PartPlate* plate = get_partplate_list().get_curr_plate();
    try {
        p->m_print_job_data._3mf_path = fs::path(plate->get_tmp_gcode_path());
        p->m_print_job_data._3mf_path.replace_extension("3mf");
    }
    catch (std::exception& e) {
        BOOST_LOG_TRIVIAL(error) << "generate 3mf path failed";
        return -1;
    }
    SaveStrategy strategy = SaveStrategy::Silence | SaveStrategy::SkipModel | SaveStrategy::WithGcode | SaveStrategy::SkipAuxiliary;
#if !BBL_RELEASE_TO_PUBLIC
    //only save model in QA environment
    std::string sel = get_app_config()->get("iot_environment");
    if (sel == ENV_PRE_HOST)
        strategy = SaveStrategy::Silence | SaveStrategy::SplitModel | SaveStrategy::WithGcode;
#endif
    result = export_3mf(p->m_print_job_data._3mf_path, strategy, plate_idx, proFn);
    return result;
}
References ENV_PRE_HOST, error, export_3mf(), Slic3r::AppConfig::get(), Slic3r::GUI::get_app_config(), Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::PartPlateList::get_curr_plate_index(), get_partplate_list(), Slic3r::GUI::PartPlate::get_tmp_gcode_path(), p, PLATE_CURRENT_IDX, Slic3r::Silence, Slic3r::SkipAuxiliary, Slic3r::SkipModel, Slic3r::SplitModel, and Slic3r::WithGcode.
Referenced by Slic3r::GUI::SelectMachineDialog::on_ok().
send_gcode_finish()
void Slic3r::GUI::Plater::send_gcode_finish (wxString name)
{
    auto out_str = GUI::format(_L("The file %s has been sent to the printer's storage space and can be viewed on the printer."), name);
    p->notification_manager->push_exporting_finished_notification(out_str, "", false);
}
References _L, Slic3r::GUI::format(), and p.
Referenced by send_job_finished().
send_gcode_legacy()
void Slic3r::GUI::Plater::send_gcode_legacy (int plate_idx = -1, Export3mfProgressFn proFn = nullptr)
{
    // if physical_printer is selected, send gcode for this printer
    // DynamicPrintConfig* physical_printer_config = wxGetApp().preset_bundle->physical_printers.get_selected_printer_config();
    DynamicPrintConfig* physical_printer_config = &Slic3r::GUI::wxGetApp().preset_bundle->printers.get_edited_preset().config;
    if (! physical_printer_config || p->model.objects.empty())
        return;
    PrintHostJob upload_job(physical_printer_config);
    if (upload_job.empty())
        return;
    // Obtain default output path
    fs::path default_output_file;
    try {
        // Update the background processing, so that the placeholder parser will get the correct values for the ouput file template.
        // Also if there is something wrong with the current configuration, a pop-up dialog will be shown and the export will not be performed.
        unsigned int state = this->p->update_restart_background_process(false, false);
        if (state & priv::UPDATE_BACKGROUND_PROCESS_INVALID)
            return;
        default_output_file = this->p->background_process.output_filepath_for_project("");
    } catch (const Slic3r::PlaceholderParserError& ex) {
        // Show the error with monospaced font.
        show_error(this, ex.what(), true);
        return;
    } catch (const std::exception& ex) {
        show_error(this, ex.what(), false);
        return;
    }
    default_output_file = fs::path(Slic3r::fold_utf8_to_ascii(default_output_file.string()));
    // Repetier specific: Query the server for the list of file groups.
    wxArrayString groups;
    {
        wxBusyCursor wait;
        upload_job.printhost->get_groups(groups);
    }
    PrintHostSendDialog dlg(default_output_file, upload_job.printhost->get_post_upload_actions(), groups);
    if (dlg.ShowModal() == wxID_OK) {
        upload_job.upload_data.upload_path = dlg.filename();
        upload_job.upload_data.post_action = dlg.post_action();
        upload_job.upload_data.group       = dlg.group();
        p->export_gcode(fs::path(), false, std::move(upload_job));
    }
}
References Slic3r::PrintHostJob::empty(), Slic3r::GUI::PrintHostSendDialog::filename(), Slic3r::fold_utf8_to_ascii(), Slic3r::GUI::PrintHostSendDialog::group(), Slic3r::PrintHostUpload::group, p, Slic3r::GUI::PrintHostSendDialog::post_action(), Slic3r::PrintHostUpload::post_action, Slic3r::PrintHostJob::printhost, Slic3r::GUI::show_error(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_INVALID, Slic3r::PrintHostJob::upload_data, and Slic3r::PrintHostUpload::upload_path.
send_job_finished()
void Slic3r::GUI::Plater::send_job_finished (wxCommandEvent & evt)
{
    Slic3r::DeviceManager* dev = Slic3r::GUI::wxGetApp().getDeviceManager();
    if (!dev) return;
    //dev->set_selected_machine(evt.GetString().ToStdString());
    send_gcode_finish(evt.GetString());
    p->hide_send_to_printer_dlg();
    //p->main_frame->request_select_tab(MainFrame::TabPosition::tpMonitor);
    //MonitorPanel* curr_monitor = p->main_frame->m_monitor;
    //if (curr_monitor)
    //    curr_monitor->get_tabpanel()->ChangeSelection(MonitorPanel::PrinterTab::PT_STATUS);
}
References p, and send_gcode_finish().
send_to_printer()
void Slic3r::GUI::Plater::send_to_printer (bool isall = false)
{
    p->on_action_send_to_printer(isall);
}
References p.
set_bed_position()
void Slic3r::GUI::Plater::set_bed_position (Vec2d & pos)
{
    p->bed.set_position(pos);
}
References p.
Referenced by Slic3r::GUI::PartPlateList::create_plate(), Slic3r::GUI::PartPlateList::delete_plate(), Slic3r::GUI::PartPlateList::rebuild_plates_after_deserialize(), and Slic3r::GUI::PartPlateList::select_plate().
set_bed_shape() [1/2]
void Slic3r::GUI::Plater::set_bed_shape () const
{
    std::string texture_filename;
    auto bundle = wxGetApp().preset_bundle;
    if (bundle != nullptr) {
        const Preset* curr = &bundle->printers.get_selected_preset();
        if (curr->is_system)
            texture_filename = PresetUtils::system_printer_bed_texture(*curr);
        else {
            auto *printer_model = curr->config.opt<ConfigOptionString>("printer_model");
            if (printer_model != nullptr && ! printer_model->value.empty()) {
                texture_filename = bundle->get_texture_for_printer_model(printer_model->value);
            }
        }
    }
    set_bed_shape(p->config->option<ConfigOptionPoints>("printable_area")->values,
        //BBS: add bed exclude areas
        p->config->option<ConfigOptionPoints>("bed_exclude_area")->values,
        p->config->option<ConfigOptionFloat>("printable_height")->value,
        p->config->option<ConfigOptionString>("bed_custom_texture")->value.empty() ? texture_filename : p->config->option<ConfigOptionString>("bed_custom_texture")->value,
        p->config->option<ConfigOptionString>("bed_custom_model")->value);
}
References Slic3r::Preset::config, Slic3r::Preset::is_system, Slic3r::DynamicConfig::opt(), p, Slic3r::printer_model(), set_bed_shape(), Slic3r::PresetUtils::system_printer_bed_texture(), Slic3r::ConfigOptionSingle< T >::value, and Slic3r::ConfigOptionVector< T >::values.
Referenced by on_config_change(), and set_bed_shape().
set_bed_shape() [2/2]
void Slic3r::GUI::Plater::set_bed_shape (const Pointfs & shape, const Pointfs & exclude_area, const double printable_height, const std::string & custom_texture, const std::string & custom_model, bool force_as_custom = false) const
{
    p->set_bed_shape(shape, exclude_area, printable_height, custom_texture, custom_model, force_as_custom);
}
References p, and Slic3r::printable_height().
set_current_canvas_as_dirty()
void Slic3r::GUI::Plater::set_current_canvas_as_dirty ()
{
    p->set_current_canvas_as_dirty();
}
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_locked(), Slic3r::GUI::MenuFactory::append_menu_item_printable(), Slic3r::GUI::Mouse3DController::disconnect_device(), and Slic3r::GUI::ObjectList::OnEditingDone().
set_need_update()
void Slic3r::GUI::Plater::set_need_update (bool need_update)
{
    p->set_need_update(need_update);
}
References need_update(), and p.
set_number_of_copies()
void Slic3r::GUI::Plater::set_number_of_copies ()
{
    int obj_idx = p->get_selected_object_idx();
    if (obj_idx == -1)
        return;
    ModelObject* model_object = p->model.objects[obj_idx];
    const int num = GetNumberFromUser( " ", _L("Number of copies:"),
                                    _L("Copies of the selected object"), model_object->instances.size(), 0, 1000, this );
    if (num < 0)
        return;
    Plater::TakeSnapshot snapshot(this, (boost::format("Set numbers of copies to %1%")%num).str());
    int diff = num - (int)model_object->instances.size();
    if (diff > 0)
        increase_instances(diff);
    else if (diff < 0)
        decrease_instances(-diff);
}
References _L, decrease_instances(), Slic3r::diff(), Slic3r::GUI::GetNumberFromUser(), increase_instances(), Slic3r::ModelObject::instances, int, and p.
set_only_gcode()
void Slic3r::GUI::Plater::set_only_gcode (bool only_gcode) inline
{ m_only_gcode = only_gcode; }
References m_only_gcode.
set_plater_dirty()
void Slic3r::GUI::Plater::set_plater_dirty (bool is_dirty)
{ p->set_plater_dirty(is_dirty); }
References p.
Referenced by select_plate_by_hover_id().
set_prepare_state()
void Slic3r::GUI::Plater::set_prepare_state (int state)
{
    p->m_job_prepare_state = state;
}
References p.
Referenced by Slic3r::GUI::MenuFactory::create_plate_menu(), and select_plate_by_hover_id().
set_printer_technology()
bool Slic3r::GUI::Plater::set_printer_technology (PrinterTechnology printer_technology)
{
    p->printer_technology = printer_technology;
    bool ret = p->background_process.select_technology(printer_technology);
    if (ret) {
        // Update the active presets.
    }
    //FIXME for SLA synchronize
    //p->background_process.apply(Model)!
    if (printer_technology == ptSLA) {
        for (ModelObject* model_object : p->model.objects) {
            model_object->ensure_on_bed();
        }
    }
    p->label_btn_export = printer_technology == ptFFF ? L("Export G-code") : L("Export");
    p->label_btn_send   = printer_technology == ptFFF ? L("Send G-code")   : L("Send to printer");
    if (wxGetApp().mainframe != nullptr)
        wxGetApp().mainframe->update_menubar();
    p->sidebar->get_searcher().set_printer_technology(printer_technology);
    p->notification_manager->set_fff(printer_technology == ptFFF);
    p->notification_manager->set_slicing_progress_hidden();
    return ret;
}
References L, p, printer_technology(), Slic3r::ptFFF, and Slic3r::ptSLA.
Referenced by Slic3r::GUI::MainFrame::load_config(), Slic3r::GUI::GUI_App::load_current_presets(), and on_config_change().
set_project_filename()
void Slic3r::GUI::Plater::set_project_filename (const wxString & filename)
{
    p->set_project_filename(filename);
}
References p.
Referenced by load_gcode(), Slic3r::GUI::GUI_App::post_init(), and Slic3r::GUI::Plater::priv::reset().
set_selected_visible()
void Slic3r::GUI::Plater::set_selected_visible (bool visible)
{
    if (p->get_curr_selection().is_empty())
        return;
    Plater::TakeSnapshot snapshot(this, "Set Selected Objects Visible in AssembleView");
    p->m_ui_jobs.cancel_all();
    p->get_current_canvas3D()->set_selected_visible(visible);
}
References p.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_set_visible().
set_using_exported_file()
void Slic3r::GUI::Plater::set_using_exported_file (bool exported_file) inline
{
        m_exported_file = exported_file;
    }
References m_exported_file.
setExtruderParams()
void Slic3r::GUI::Plater::setExtruderParams (std::map< size_t, Slic3r::ExtruderParams > & extParas) static
{
    extParas.clear();
    Slic3r::DynamicPrintConfig config = wxGetApp().preset_bundle->full_config();
    // BBS
    int numExtruders = wxGetApp().preset_bundle->filament_presets.size();
    for (unsigned int i = 0; i != numExtruders; ++i) {
        std::string matName = "";
        // BBS
        int bedTemp = 35;
        double endTemp = 0.f;
        if (config.has("filament_type")) {
            matName = config.opt_string("filament_type", i);
        }
        if (config.has("nozzle_temperature")) {
            endTemp = config.opt_int("nozzle_temperature", i);
        }
        // FIXME: curr_bed_type is now a plate config rather than a global config.
        // Currently bed temp is not used for brim generation, so just comment it for now.
#if 0
        if (config.has("curr_bed_type")) {
            BedType curr_bed_type = config.opt_enum<BedType>("curr_bed_type");
            bedTemp = config.opt_int(get_bed_temp_key(curr_bed_type), i);
        }
#endif
        if (i == 0) extParas.insert({ i,{matName, bedTemp, endTemp} });
        extParas.insert({ i + 1,{matName, bedTemp, endTemp} });
    }
}
References config(), Slic3r::get_bed_temp_key(), Slic3r::ConfigOptionResolver::has(), Slic3r::DynamicConfig::opt_enum(), Slic3r::DynamicConfig::opt_int(), Slic3r::DynamicConfig::opt_string(), and Slic3r::DynamicConfig::size().
Referenced by Slic3r::GUI::Plater::priv::on_action_slice_all(), Slic3r::GUI::Plater::priv::on_action_slice_plate(), Slic3r::GUI::ArrangeJob::prepare(), and Slic3r::GUI::Plater::priv::select_view_3D().
SetPlateIndexByRightMenuInLeftUI()
void Slic3r::GUI::Plater::SetPlateIndexByRightMenuInLeftUI (int index)
{ p->m_is_RightClickInLeftUI = index; }
References p.
setPrintSpeedTable()
void Slic3r::GUI::Plater::setPrintSpeedTable (Slic3r::GlobalSpeedMap & printSpeedMap) static
{
    Slic3r::DynamicPrintConfig config = wxGetApp().preset_bundle->full_config();
    printSpeedMap.maxSpeed = 0;
    if (config.has("inner_wall_speed")) {
        printSpeedMap.perimeterSpeed = config.opt_float("inner_wall_speed");
        if (printSpeedMap.perimeterSpeed > printSpeedMap.maxSpeed)
            printSpeedMap.maxSpeed = printSpeedMap.perimeterSpeed;
    }
    if (config.has("outer_wall_speed")) {
        printSpeedMap.externalPerimeterSpeed = config.opt_float("outer_wall_speed");
        printSpeedMap.maxSpeed = std::max(printSpeedMap.maxSpeed, printSpeedMap.externalPerimeterSpeed);
    }
    if (config.has("sparse_infill_speed")) {
        printSpeedMap.infillSpeed = config.opt_float("sparse_infill_speed");
        if (printSpeedMap.infillSpeed > printSpeedMap.maxSpeed)
            printSpeedMap.maxSpeed = printSpeedMap.infillSpeed;
    }
    if (config.has("internal_solid_infill_speed")) {
        printSpeedMap.solidInfillSpeed = config.opt_float("internal_solid_infill_speed");
        if (printSpeedMap.solidInfillSpeed > printSpeedMap.maxSpeed)
            printSpeedMap.maxSpeed = printSpeedMap.solidInfillSpeed;
    }
    if (config.has("top_surface_speed")) {
        printSpeedMap.topSolidInfillSpeed = config.opt_float("top_surface_speed");
        if (printSpeedMap.topSolidInfillSpeed > printSpeedMap.maxSpeed)
            printSpeedMap.maxSpeed = printSpeedMap.topSolidInfillSpeed;
    }
    if (config.has("support_speed")) {
        printSpeedMap.supportSpeed = config.opt_float("support_speed");
        if (printSpeedMap.supportSpeed > printSpeedMap.maxSpeed)
            printSpeedMap.maxSpeed = printSpeedMap.supportSpeed;
    }
    if (config.has("small_perimeter_speed")) {
        printSpeedMap.smallPerimeterSpeed = config.get_abs_value("small_perimeter_speed");
        if (printSpeedMap.smallPerimeterSpeed > printSpeedMap.maxSpeed)
            printSpeedMap.maxSpeed = printSpeedMap.smallPerimeterSpeed;
    }
    /*        "inner_wall_speed", "outer_wall_speed", "sparse_infill_speed", "internal_solid_infill_speed",
        "top_surface_speed", "support_speed", "support_object_xy_distance", "support_interface_speed",
        "bridge_speed", "gap_infill_speed", "travel_speed", "initial_layer_speed"*/
    auto& print = wxGetApp().plater()->get_partplate_list().get_current_fff_print();
    auto print_config = print.config();
    printSpeedMap.bed_poly.points = get_bed_shape(*(wxGetApp().plater()->config()));
    Pointfs excluse_area_points = print_config.bed_exclude_area.values;
    Polygons exclude_polys;
    Polygon exclude_poly;
    for (int i = 0; i < excluse_area_points.size(); i++) {
        auto pt = excluse_area_points[i];
        exclude_poly.points.emplace_back(scale_(pt.x()), scale_(pt.y()));
        if (i % 4 == 3) {  // exclude areas are always rectangle
            exclude_polys.push_back(exclude_poly);
            exclude_poly.points.clear();
        }
    }
    printSpeedMap.bed_poly = diff({ printSpeedMap.bed_poly }, exclude_polys)[0];
}
References Slic3r::GlobalSpeedMap::bed_poly, config(), Slic3r::diff(), Slic3r::GlobalSpeedMap::externalPerimeterSpeed, Slic3r::ConfigBase::get_abs_value(), Slic3r::get_bed_shape(), Slic3r::ConfigOptionResolver::has(), Slic3r::GlobalSpeedMap::infillSpeed, Slic3r::GlobalSpeedMap::maxSpeed, Slic3r::DynamicConfig::opt_float(), Slic3r::GlobalSpeedMap::perimeterSpeed, Slic3r::GUI::plater(), Slic3r::MultiPoint::points, scale_, Slic3r::GlobalSpeedMap::smallPerimeterSpeed, Slic3r::GlobalSpeedMap::solidInfillSpeed, Slic3r::GlobalSpeedMap::supportSpeed, and Slic3r::GlobalSpeedMap::topSolidInfillSpeed.
Referenced by Slic3r::GUI::Plater::priv::on_action_slice_all(), Slic3r::GUI::Plater::priv::on_action_slice_plate(), Slic3r::GUI::ArrangeJob::prepare(), and Slic3r::GUI::Plater::priv::select_view_3D().
Show()
bool Slic3r::GUI::Plater::Show (bool show = true)
{
    if (wxGetApp().mainframe)
        wxGetApp().mainframe->show_option(show);
    return wxPanel::Show(show);
}
show_illegal_characters_warning()
void Slic3r::GUI::Plater::show_illegal_characters_warning (wxWindow * parent) static
{
    show_error(parent, _L("Invalid name, the following characters are not allowed:") + " <>:/\\|?*\"");
}
References _L, and Slic3r::GUI::show_error().
Referenced by Slic3r::GUI::ObjectList::OnEditingDone(), and Slic3r::GUI::ObjectList::rename_item().
show_object_info()
void Slic3r::GUI::Plater::show_object_info ()
{
    NotificationManager *notify_manager = get_notification_manager();
    const Selection& selection = get_selection();
    int selCount = selection.get_volume_idxs().size();
    ModelObjectPtrs objects = model().objects;
    int obj_idx = selection.get_object_idx();
    std::string info_text;
    if (selCount > 1 && !selection.is_single_full_object()) {
        notify_manager->bbl_close_objectsinfo_notification();
        if (selection.get_mode() == Selection::EMode::Volume) {
            info_text += (boost::format(_utf8(L("Number of currently selected parts: %1%\n"))) % selCount).str();
        } else if (selection.get_mode() == Selection::EMode::Instance) {
            int content_count = selection.get_content().size();
            info_text += (boost::format(_utf8(L("Number of currently selected objects: %1%\n"))) % content_count).str();
        }
        notify_manager->bbl_show_objectsinfo_notification(info_text, false, !(p->current_panel == p->view3D));
        return;
    }
    else if (objects.empty() || (obj_idx < 0) || (obj_idx >= objects.size()) ||
        objects[obj_idx]->volumes.empty() ||// hack to avoid crash when deleting the last object on the bed
        (selection.is_single_full_object() && objects[obj_idx]->instances.size()> 1) ||
        !(selection.is_single_full_instance() || selection.is_single_volume()))
    {
        notify_manager->bbl_close_objectsinfo_notification();
        return;
    }
    const ModelObject* model_object = objects[obj_idx];
    int inst_idx = selection.get_instance_idx();
    if ((inst_idx < 0) || (inst_idx >= model_object->instances.size()))
    {
        notify_manager->bbl_close_objectsinfo_notification();
        return;
    }
    bool imperial_units = wxGetApp().app_config->get("use_inches") == "1";
    double koef = imperial_units ? GizmoObjectManipulation::mm_to_in : 1.0f;
    ModelVolume* vol = nullptr;
    Transform3d t;
    int face_count;
    Vec3d size;
    if (selection.is_single_volume()) {
        std::vector<int> obj_idxs, vol_idxs;
        wxGetApp().obj_list()->get_selection_indexes(obj_idxs, vol_idxs);
        if (vol_idxs.size() != 1)
        {
            //corner case when merge/split/remove
            return;
        }
        vol = model_object->volumes[vol_idxs[0]];
        t = model_object->instances[inst_idx]->get_matrix() * vol->get_matrix();
        info_text += (boost::format(_utf8(L("Part name: %1%\n"))) % vol->name).str();
        face_count = static_cast<int>(vol->mesh().facets_count());
        size = vol->get_convex_hull().transformed_bounding_box(t).size();
    }
    else {
        //int obj_idx, vol_idx;
        //wxGetApp().obj_list()->get_selected_item_indexes(obj_idx, vol_idx);
        //if (obj_idx < 0) {
        //    //corner case when merge/split/remove
        //    return;
        //}
        info_text += (boost::format(_utf8(L("Object name: %1%\n"))) % model_object->name).str();
        face_count = static_cast<int>(model_object->facets_count());
        size = model_object->instance_convex_hull_bounding_box(inst_idx).size();
    }
    //Vec3d size = vol ? vol->mesh().transformed_bounding_box(t).size() : model_object->instance_bounding_box(inst_idx).size();
    if (imperial_units)
        info_text += (boost::format(_utf8(L("Size: %1% x %2% x %3% in\n"))) %(size(0)*koef) %(size(1)*koef) %(size(2)*koef)).str();
    else
        info_text += (boost::format(_utf8(L("Size: %1% x %2% x %3% mm\n"))) %size(0) %size(1) %size(2)).str();
    const TriangleMeshStats& stats = vol ? vol->mesh().stats() : model_object->get_object_stl_stats();
    double volume_val = stats.volume;
    if (vol)
        volume_val *= std::fabs(t.matrix().block(0, 0, 3, 3).determinant());
    volume_val = volume_val * pow(koef,3);
    if (imperial_units)
        info_text += (boost::format(_utf8(L("Volume: %1% in\n"))) %volume_val).str();
    else
        info_text += (boost::format(_utf8(L("Volume: %1% mm\n"))) %volume_val).str();
    info_text += (boost::format(_utf8(L("Triangles: %1%\n"))) %face_count).str();
    wxString info_manifold;
    int non_manifold_edges = 0;
    auto mesh_errors = p->sidebar->obj_list()->get_mesh_errors_info(&info_manifold, &non_manifold_edges);
    #ifndef __WINDOWS__
    if (non_manifold_edges > 0) {
        info_manifold += into_u8("\n" + _L("Tips:") + "\n" +_L("\"Fix Model\" feature is currently only on Windows. Please repair the model on Orca Slicer(windows) or CAD softwares."));
    }
    #endif //APPLE & LINUX
    info_manifold = "<Error>" + info_manifold + "</Error>";
    info_text += into_u8(info_manifold);
    notify_manager->bbl_show_objectsinfo_notification(info_text, is_windows10()&&(non_manifold_edges > 0), !(p->current_panel == p->view3D));
}
References _L, _utf8, Slic3r::GUI::NotificationManager::bbl_close_objectsinfo_notification(), Slic3r::GUI::NotificationManager::bbl_show_objectsinfo_notification(), Slic3r::ModelObject::facets_count(), Slic3r::TriangleMesh::facets_count(), Slic3r::GUI::Selection::get_content(), Slic3r::ModelVolume::get_convex_hull(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::ModelVolume::get_matrix(), Slic3r::GUI::Selection::get_mode(), get_notification_manager(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::ModelObject::get_object_stl_stats(), get_selection(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::Instance, Slic3r::ModelObject::instance_convex_hull_bounding_box(), Slic3r::ModelObject::instances, Slic3r::GUI::into_u8(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_volume(), Slic3r::is_windows10(), L, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::ModelVolume::mesh(), Slic3r::GUI::GizmoObjectManipulation::mm_to_in, model(), Slic3r::ModelObject::name, Slic3r::ModelVolume::name, Slic3r::Model::objects, p, Slic3r::BoundingBox3Base< PointClass >::size(), size, Slic3r::TriangleMesh::stats(), Slic3r::TriangleMesh::transformed_bounding_box(), Slic3r::TriangleMeshStats::volume, Slic3r::GUI::Selection::Volume, and Slic3r::ModelObject::volumes.
show_publish_dialog()
bool Slic3r::GUI::Plater::show_publish_dialog (bool show = true)
{
    return p->show_publish_dlg(show);
}
References p.
show_status_message()
void Slic3r::GUI::Plater::show_status_message (std::string s)
{
    BOOST_LOG_TRIVIAL(trace) << "show_status_message:" << s;
}
References Slic3r::trace().
show_view3D_labels()
void Slic3r::GUI::Plater::show_view3D_labels (bool show)
{ p->show_view3D_labels(show); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_default_menu().
show_view3D_overhang()
void Slic3r::GUI::Plater::show_view3D_overhang (bool show)
{  p->show_view3D_overhang(show); }
References p.
sidebar()
Sidebar & Slic3r::GUI::Plater::sidebar ()
{ return *p->sidebar; }
References p.
Referenced by _calib_pa_pattern(), Slic3r::GUI::Plater::priv::can_decrease_instances(), Slic3r::GUI::Plater::priv::can_fix_through_netfabb(), Slic3r::GUI::Plater::priv::can_increase_instances(), Slic3r::GUI::Plater::priv::can_mirror(), Slic3r::GUI::Plater::priv::can_reload_from_disk(), Slic3r::GUI::Plater::priv::can_replace_with_stl(), Slic3r::GUI::Plater::priv::can_split(), Slic3r::GUI::Plater::priv::collapse_sidebar(), decrease_instances(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::ObjectList::fix_through_netfabb(), increase_instances(), Slic3r::GUI::Plater::priv::load_files(), on_bed_type_change(), on_filaments_change(), Slic3r::GUI::Plater::priv::on_plate_selected(), Slic3r::GUI::Plater::priv::on_process_completed(), Slic3r::GUI::Plater::priv::on_select_preset(), Slic3r::GUI::Plater::priv::PopupObjectTable(), Slic3r::GUI::Plater::priv::remove(), Slic3r::GUI::Plater::priv::remove_curr_plate_all(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::reset(), Slic3r::GUI::Plater::priv::select_all(), Slic3r::GUI::Plater::priv::select_curr_plate_all(), Slic3r::GUI::Plater::priv::set_current_panel(), Slic3r::GUI::GUI_App::sidebar(), Slic3r::GUI::Plater::priv::take_snapshot(), Slic3r::GUI::Plater::priv::undo_redo_to(), Slic3r::GUI::Plater::priv::update(), and Slic3r::GUI::Plater::priv::update_ui_from_settings().
single_snapshots_enter()
void Slic3r::GUI::Plater::single_snapshots_enter (SingleSnapshot * single) private
{
    p->single_snapshots_enter(single);
}
References p.
Referenced by Slic3r::GUI::Plater::SingleSnapshot::SingleSnapshot().
single_snapshots_leave()
void Slic3r::GUI::Plater::single_snapshots_leave (SingleSnapshot * single) private
{
    p->single_snapshots_leave(single);
}
References p.
Referenced by Slic3r::GUI::Plater::SingleSnapshot::~SingleSnapshot().
sla_object_menu()
wxMenu * Slic3r::GUI::Plater::sla_object_menu ()
{ return p->menus.sla_object_menu();        }
References p.
Referenced by Slic3r::GUI::ObjectList::show_context_menu().
sla_print() [1/2]
SLAPrint & Slic3r::GUI::Plater::sla_print ()
{ return p->sla_print; }
References p.
sla_print() [2/2]
const SLAPrint & Slic3r::GUI::Plater::sla_print () const
{ return p->sla_print; }
References p.
Referenced by Slic3r::GUI::SLAImportJob::finalize(), and Slic3r::GUI::SLAImportJob::reset().
split_object()
void Slic3r::GUI::Plater::split_object ()
{ p->split_object(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_bbl_part_menu(), Slic3r::GUI::MenuFactory::create_extra_object_menu(), Slic3r::GUI::MenuFactory::create_object_menu(), Slic3r::GUI::MenuFactory::create_sla_object_menu(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::MenuFactory::multi_selection_menu(), and Slic3r::GUI::Plater::priv::on_action_split_objects().
split_volume()
void Slic3r::GUI::Plater::split_volume ()
{ p->split_volume(); }
References p.
Referenced by Slic3r::GUI::MenuFactory::create_bbl_part_menu(), Slic3r::GUI::MenuFactory::create_extra_object_menu(), Slic3r::GUI::MenuFactory::create_object_menu(), Slic3r::GUI::MenuFactory::create_part_menu(), Slic3r::GUI::MenuFactory::multi_selection_menu(), and Slic3r::GUI::Plater::priv::on_action_split_volumes().
start_next_slice()
int Slic3r::GUI::Plater::start_next_slice () private
{
    // Stop arrange and (or) optimize rotation tasks.
    //this->stop_jobs();
    //FIXME Don't reslice if export of G-code or sending to OctoPrint is running.
    // bitmask of UpdateBackgroundProcessReturnState
    unsigned int state = this->p->update_background_process(true, false, false);
    if (state & priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE)
        this->p->view3D->reload_scene(false);
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": update_background_process returns %1%")%state;
    if (p->partplate_list.get_curr_plate()->is_apply_result_invalid()) {
        p->process_completed_with_error = p->partplate_list.get_curr_plate_index();
        BOOST_LOG_TRIVIAL(warning) << __FUNCTION__ << boost::format(": found invalidated apply in update_background_process.");
        return -1;
    }
    // Only restarts if the state is valid.
    bool result = this->p->restart_background_process(state | priv::UPDATE_BACKGROUND_PROCESS_FORCE_RESTART);
    if (!result)
    {
        //slice next
        SlicingProcessCompletedEvent evt(EVT_PROCESS_COMPLETED, 0,
                SlicingProcessCompletedEvent::Finished, nullptr);
        // Post the "complete" callback message, so that it will slice the next plate soon
        wxQueueEvent(this, evt.Clone());
    }
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": restart_background_process returns %1%")%result;
    return 0;
}
References Slic3r::SlicingProcessCompletedEvent::Clone(), Slic3r::SlicingProcessCompletedEvent::Finished, p, Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_FORCE_RESTART, and Slic3r::GUI::Plater::priv::UPDATE_BACKGROUND_PROCESS_REFRESH_SCENE.
stop_jobs()
void Slic3r::GUI::Plater::stop_jobs ()
{ p->m_ui_jobs.stop_all(); }
References p.
Referenced by reslice().
suppress_background_process()
void Slic3r::GUI::Plater::suppress_background_process (const bool stop_background_process)
{
    if (stop_background_process)
        this->p->background_process_timer.Stop();
    this->p->suppressed_backround_processing_update = true;
}
References p.
suppress_snapshots()
void Slic3r::GUI::Plater::suppress_snapshots () private
{ p->suppress_snapshots(); }
References p.
Referenced by Slic3r::GUI::Plater::SuppressSnapshots::SuppressSnapshots(), Slic3r::GUI::Plater::TakeSnapshot::TakeSnapshot(), and Slic3r::GUI::Plater::TakeSnapshot::TakeSnapshot().
sys_color_changed()
void Slic3r::GUI::Plater::sys_color_changed ()
{
    p->preview->sys_color_changed();
    p->sidebar->sys_color_changed();
    p->menus.sys_color_changed();
    if (p->m_select_machine_dlg) p->m_select_machine_dlg->sys_color_changed();
    Layout();
    GetParent()->Layout();
}
References p.
take_snapshot() [1/2]
void Slic3r::GUI::Plater::take_snapshot (const std::string & snapshot_name)
{ p->take_snapshot(snapshot_name); }
References p.
Referenced by Slic3r::GUI::Plater::TakeSnapshot::TakeSnapshot(), Slic3r::GUI::Plater::TakeSnapshot::TakeSnapshot(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), delete_plate(), Slic3r::GUI::Plater::priv::enter_gizmos_stack(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::Plater::priv::on_action_add_plate(), Slic3r::GUI::PartPlateList::select_plate(), select_plate(), select_plate_by_hover_id(), and Slic3r::GUI::take_snapshot().
take_snapshot() [2/2]
void Slic3r::GUI::Plater::take_snapshot (const std::string & snapshot_name, UndoRedo::SnapshotType snapshot_type)
{ p->take_snapshot(snapshot_name, snapshot_type); }
References p.
toggle_render_statistic_dialog()
void Slic3r::GUI::Plater::toggle_render_statistic_dialog ()
{
    p->show_render_statistic_dialog = !p->show_render_statistic_dialog;
}
References p.
toggle_show_wireframe()
void Slic3r::GUI::Plater::toggle_show_wireframe ()
{
    p->show_wireframe = !p->show_wireframe;
}
References p.
trigger_restore_project()
void Slic3r::GUI::Plater::trigger_restore_project (int skip_confirm = 0)
{
    auto evt = new wxCommandEvent(EVT_RESTORE_PROJECT, this->GetId());
    evt->SetInt(skip_confirm);
    wxQueueEvent(this, evt);
    //wxPostEvent(this, *evt);
}
Referenced by Slic3r::GUI::GUI_App::post_init(), and Slic3r::GUI::GUI_App::recreate_GUI().
unbind_canvas_event_handlers()
void Slic3r::GUI::Plater::unbind_canvas_event_handlers ()
{
    p->unbind_canvas_event_handlers();
}
References p.
undo()
void Slic3r::GUI::Plater::undo ()
{ p->undo(); }
References p.
Referenced by BBLTopbar::OnUndo().
undo_redo_stack_main()
const UndoRedo::Stack & Slic3r::GUI::Plater::undo_redo_stack_main () const
{ return p->undo_redo_stack_main(); }
References p.
Referenced by Slic3r::GUI::Plater::priv::up_to_date().
undo_redo_string_getter()
bool Slic3r::GUI::Plater::undo_redo_string_getter (const bool is_undo, int idx, const char ** out_text)
{
    const std::vector<UndoRedo::Snapshot>& ss_stack = p->undo_redo_stack().snapshots();
    const int idx_in_ss_stack = p->get_active_snapshot_index() + (is_undo ? -(++idx) : idx);
    if (0 < idx_in_ss_stack && (size_t)idx_in_ss_stack < ss_stack.size() - 1) {
        *out_text = ss_stack[idx_in_ss_stack].name.c_str();
        return true;
    }
    return false;
}
References p.
undo_redo_topmost_string_getter()
void Slic3r::GUI::Plater::undo_redo_topmost_string_getter (const bool is_undo, std::string & out_text)
{
    const std::vector<UndoRedo::Snapshot>& ss_stack = p->undo_redo_stack().snapshots();
    const int idx_in_ss_stack = p->get_active_snapshot_index() + (is_undo ? -1 : 0);
    if (0 < idx_in_ss_stack && (size_t)idx_in_ss_stack < ss_stack.size() - 1) {
        out_text = ss_stack[idx_in_ss_stack].name;
        return;
    }
    out_text = "";
}
References p.
undo_to()
void Slic3r::GUI::Plater::undo_to (int selection)
{
    if (selection == 0) {
        p->undo();
        return;
    }
    const int idx = p->get_active_snapshot_index() - selection - 1;
    p->undo_redo_to(p->undo_redo_stack().snapshots()[idx].timestamp);
}
References p.
up_to_date()
bool Slic3r::GUI::Plater::up_to_date (bool saved, bool backup)
{
    if (saved) {
        Slic3r::clear_other_changes(backup);
        return p->up_to_date(saved, backup);
    }
    return p->model.objects.empty() || (p->up_to_date(saved, backup) &&
                                        !Slic3r::has_other_changes(backup));
}
References Slic3r::clear_other_changes(), Slic3r::has_other_changes(), and p.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), load_project(), new_project(), Slic3r::GUI::GUI_App::post_init(), and save_project().
update()
void Slic3r::GUI::Plater::update (bool conside_update_flag = false)
{
    if (conside_update_flag) {
        if (need_update()) {
            p->update();
            p->set_need_update(false);
        }
    }
    else
        p->update();
}
References need_update(), and p.
Referenced by changed_mesh(), cut(), Slic3r::GUI::Plater::priv::delete_all_objects_from_model(), Slic3r::GUI::Plater::priv::delete_object_from_model(), delete_plate(), Slic3r::GUI::GLGizmoText::delete_temp_preview_text_volume(), edit_text(), Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), force_filament_colors_update(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::Plater::priv::on_action_add_plate(), on_config_change(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::Plater::priv::remove(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::Plater::priv::reset(), select_plate_by_hover_id(), Slic3r::GUI::Plater::priv::undo_redo_to(), and Slic3r::GUI::Plater::priv::update_after_undo_redo().
update_all_plate_thumbnails()
void Slic3r::GUI::Plater::update_all_plate_thumbnails (bool force_update = false)
{
    for (int i = 0; i < get_partplate_list().get_plate_count(); i++) {
        PartPlate* plate = get_partplate_list().get_plate(i);
        ThumbnailsParams thumbnail_params = { {}, false, true, true, true, i};
        if (force_update || !plate->thumbnail_data.is_valid()) {
            get_view3D_canvas3D()->render_thumbnail(plate->thumbnail_data, plate->plate_thumbnail_width, plate->plate_thumbnail_height, thumbnail_params, Camera::EType::Ortho);
        }
    }
}
References get_partplate_list(), Slic3r::GUI::PartPlateList::get_plate(), Slic3r::GUI::PartPlateList::get_plate_count(), get_view3D_canvas3D(), Slic3r::ThumbnailData::is_valid(), Slic3r::GUI::Camera::Ortho, Slic3r::GUI::PartPlate::plate_thumbnail_height, Slic3r::GUI::PartPlate::plate_thumbnail_width, Slic3r::GUI::GLCanvas3D::render_thumbnail(), and Slic3r::GUI::PartPlate::thumbnail_data.
Referenced by force_update_all_plate_thumbnails().
update_filament_colors_in_full_config()
bool Slic3r::GUI::Plater::update_filament_colors_in_full_config ()
{
    DynamicPrintConfig& project_config = wxGetApp().preset_bundle->project_config;
    ConfigOptionStrings* color_opt = project_config.option<ConfigOptionStrings>("filament_colour");
    p->config->option<ConfigOptionStrings>("filament_colour")->values = color_opt->values;
    return true;
}
References Slic3r::ConfigBase::option(), p, and Slic3r::ConfigOptionVector< T >::values.
Referenced by on_config_change(), and on_filaments_change().
update_menus()
void Slic3r::GUI::Plater::update_menus ()
{ p->menus.update(); }
References p.
update_preview_bottom_toolbar()
void Slic3r::GUI::Plater::update_preview_bottom_toolbar ()
{
    p->update_preview_bottom_toolbar();
}
References p.
update_preview_moves_slider()
void Slic3r::GUI::Plater::update_preview_moves_slider ()
update_project_dirty_from_presets()
void Slic3r::GUI::Plater::update_project_dirty_from_presets ()
{ p->update_project_dirty_from_presets(); }
References p.
Referenced by load_project(), new_project(), and select_plate_by_hover_id().
update_slicing_context_to_current_partplate()
void Slic3r::GUI::Plater::update_slicing_context_to_current_partplate ()
{
    p->partplate_list.update_slice_context_to_current_plate(p->background_process);
    p->preview->update_gcode_result(p->partplate_list.get_current_slice_result());
}
References p.
Referenced by Slic3r::GUI::ArrangeJob::finalize().
update_ui_from_settings()
void Slic3r::GUI::Plater::update_ui_from_settings ()
{ p->update_ui_from_settings(); }
References p.
using_exported_file()
bool Slic3r::GUI::Plater::using_exported_file () inline
{ return m_exported_file; }
References m_exported_file.
Referenced by export_3mf(), force_update_all_plate_thumbnails(), invalid_all_plate_thumbnails(), and load_project().
validate_current_plate()
void Slic3r::GUI::Plater::validate_current_plate (bool & model_fits, bool & validate_error)
{
    model_fits = p->view3D->get_canvas3d()->check_volumes_outside_state() != ModelInstancePVS_Partly_Outside;
    validate_error = false;
    if (p->printer_technology == ptFFF) {
        std::string plater_text = _u8L("An object is laid over the boundary of plate or exceeds the height limit.\n"
                    "Please solve the problem by moving it totally on or off the plate, and confirming that the height is within the build volume.");;
        StringObjectException warning;
        Polygons polygons;
        std::vector<std::pair<Polygon, float>> height_polygons;
        StringObjectException err = p->background_process.validate(&warning, &polygons, &height_polygons);
        // update string by type
        post_process_string_object_exception(err);
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": validate err=%1%, warning=%2%, model_fits %3%")%err.string%warning.string %model_fits;
        if (err.string.empty()) {
            p->partplate_list.get_curr_plate()->update_apply_result_invalid(false);
            p->notification_manager->set_all_slicing_errors_gray(true);
            p->notification_manager->close_notification_of_type(NotificationType::ValidateError);
            // Pass a warning from validation and either show a notification,
            // or hide the old one.
            p->process_validation_warning(warning);
            p->view3D->get_canvas3d()->reset_sequential_print_clearance();
            p->view3D->get_canvas3d()->set_as_dirty();
            p->view3D->get_canvas3d()->request_extra_frame();
        }
        else {
            // The print is not valid.
            p->partplate_list.get_curr_plate()->update_apply_result_invalid(true);
            // Show error as notification.
            p->notification_manager->push_validate_error_notification(err);
            p->process_validation_warning(warning);
            //model_fits = false;
            validate_error = true;
            p->view3D->get_canvas3d()->set_sequential_print_clearance_visible(true);
            p->view3D->get_canvas3d()->set_sequential_print_clearance_render_fill(true);
            p->view3D->get_canvas3d()->set_sequential_print_clearance_polygons(polygons, height_polygons);
        }
        if (!model_fits) {
            p->notification_manager->push_plater_error_notification(plater_text);
        }
        else {
            p->notification_manager->close_plater_error_notification(plater_text);
        }
    }
    PartPlate* part_plate = p->partplate_list.get_curr_plate();
    part_plate->update_slice_ready_status(model_fits);
    return;
}
References _u8L, Slic3r::ModelInstancePVS_Partly_Outside, p, post_process_string_object_exception(), Slic3r::ptFFF, Slic3r::StringObjectException::string, Slic3r::GUI::PartPlate::update_slice_ready_status(), and Slic3r::GUI::ValidateError.
Referenced by select_plate(), and select_plate_by_hover_id().
Friends And Related Symbol Documentation
SuppressBackgroundProcessingUpdate
friend class SuppressBackgroundProcessingUpdate friend
Member Data Documentation
m_arrange_running
std::atomic<bool> Slic3r::GUI::Plater::m_arrange_running {false}
Referenced by Slic3r::GUI::ArrangeJob::finalize(), and last_arrange_job_is_finished().
m_exported_file
bool Slic3r::GUI::Plater::m_exported_file { false } private
Referenced by Slic3r::GUI::Plater::priv::load_files(), load_files(), load_project(), new_project(), set_using_exported_file(), and using_exported_file().
m_last_loaded_gcode
wxString Slic3r::GUI::Plater::m_last_loaded_gcode private
Referenced by get_last_loaded_gcode(), load_gcode(), reload_gcode_from_disk(), and reset_last_loaded_gcode().
m_loading_project
bool Slic3r::GUI::Plater::m_loading_project {false } private
Referenced by load_project(), and new_project().
m_only_gcode
bool Slic3r::GUI::Plater::m_only_gcode { false } private
Referenced by load_files(), load_gcode(), load_project(), new_project(), only_gcode_mode(), and set_only_gcode().
m_preview_only_filename
std::string Slic3r::GUI::Plater::m_preview_only_filename private
Referenced by get_preview_only_filename().
m_tracking_popup_menu
bool Slic3r::GUI::Plater::m_tracking_popup_menu = false private
Referenced by PopupMenu().
m_tracking_popup_menu_error_message
wxString Slic3r::GUI::Plater::m_tracking_popup_menu_error_message private
Referenced by PopupMenu().
m_valid_plates_count
int Slic3r::GUI::Plater::m_valid_plates_count { 0 } private
p
std::unique_ptr<priv> Slic3r::GUI::Plater::p private
Referenced by _calib_pa_pattern(), _calib_pa_select_added_objects(), add_model(), allow_snapshots(), apply_background_progress(), are_view3D_labels_shown(), arrange(), bring_instance_forward(), build_volume(), calib_max_vol_speed(), calib_pa(), calib_retraction(), calib_temp(), calib_VFA(), can_add_plate(), can_arrange(), can_copy_to_clipboard(), can_decrease_instances(), can_delete(), can_delete_all(), can_delete_plate(), can_edit_text(), can_fillcolor(), can_fix_through_netfabb(), can_increase_instances(), can_layers_editing(), can_mirror(), can_paste_from_clipboard(), can_redo(), can_reload_from_disk(), can_replace_with_stl(), can_set_instance_to_object(), can_simplify(), can_split(), can_split_to_objects(), can_split_to_volumes(), can_undo(), canvas3D(), canvas3D(), center_selection(), changed_mesh(), changed_object(), changed_objects(), clear_undo_redo_stack_main(), clone_selection(), collapse_sidebar(), config(), convert_unit(), copy_selection_to_clipboard(), cut(), cut_selection_to_clipboard(), decrease_instances(), default_menu(), delete_all_objects_from_model(), delete_object_from_model(), delete_plate(), deselect_all(), eject_drive(), enable_collapse_toolbar(), enable_wireframe(), enter_gizmos_stack(), export_3mf(), export_config_3mf(), export_core_3mf(), export_gcode(), export_gcode_3mf(), export_stl(), export_toolpaths_to_obj(), fff_print(), fff_print(), fill_bed_with_instances(), fill_color(), find_new_position(), force_filament_colors_update(), force_print_bed_update(), get_assmeble_canvas3D(), get_build_volume_type(), get_camera(), get_camera(), get_collapse_toolbar(), get_collapse_toolbar(), get_colors_for_color_print(), get_current_canvas3D(), get_export_gcode_filename(), get_mouse3d_controller(), get_mouse3d_controller(), get_notification_manager(), get_notification_manager(), get_partplate_list(), get_prepare_state(), get_preview_canvas3D(), get_print_job_data(), get_project_filename(), get_project_name(), get_selected_object_idx(), get_selection(), get_view3D_canvas3D(), GetPlateIndexByRightMenuInLeftUI(), has_assmeble_view(), has_toolpaths_to_export(), import_model_id(), import_sl1_archive(), increase_instances(), init_collapse_toolbar(), init_notification_manager(), inside_snapshot_capture(), instance_menu(), is_any_job_running(), is_background_process_slicing(), is_background_process_update_scheduled(), is_export_gcode_scheduled(), is_presets_dirty(), is_preview_loaded(), is_preview_shown(), is_project_dirty(), is_render_statistic_dialog_visible(), is_selection_empty(), is_show_wireframe(), is_sidebar_collapsed(), is_single_full_object_selection(), is_view3D_overhang_shown(), is_view3D_shown(), is_wireframe_enabled(), layer_menu(), leave_gizmos_stack(), load_files(), load_gcode(), load_project(), merge(), mirror(), model(), model(), msw_rescale(), multi_selection_menu(), need_update(), new_project(), object_list_changed(), object_menu(), on_activate(), on_config_change(), optimize_rotation(), orient(), part_menu(), paste_from_clipboard(), plate_menu(), PopupObjectTable(), PopupObjectTableBySelection(), print_job_finished(), printer_technology(), publish_job_finished(), redo(), redo_to(), refresh_print(), reload_all_from_disk(), reload_from_disk(), remove(), remove_curr_plate_all(), remove_selected(), replace_with_stl(), reset(), reset_canvas_volumes(), reset_gcode_toolpaths(), reset_project_dirty_after_save(), reset_project_dirty_initial_presets(), reset_with_confirm(), reslice(), reslice_SLA_until_step(), save_project(), save_project_if_dirty(), scale_selection_to_fit_print_volume(), schedule_background_process(), search(), search_string_getter(), segment(), select_all(), select_curr_plate_all(), select_plate(), select_plate_by_hover_id(), select_sliced_plate(), select_view(), select_view_3D(), send_gcode(), send_gcode_finish(), send_gcode_legacy(), send_job_finished(), send_to_printer(), set_bed_position(), set_bed_shape(), set_bed_shape(), Slic3r::GUI::Sidebar::set_btn_label(), set_current_canvas_as_dirty(), Slic3r::GUI::Plater::priv::set_current_panel(), set_need_update(), set_number_of_copies(), set_plater_dirty(), set_prepare_state(), set_printer_technology(), set_project_filename(), set_selected_visible(), SetPlateIndexByRightMenuInLeftUI(), show_object_info(), show_publish_dialog(), show_view3D_labels(), show_view3D_overhang(), sidebar(), single_snapshots_enter(), single_snapshots_leave(), sla_object_menu(), sla_print(), sla_print(), split_object(), split_volume(), start_next_slice(), stop_jobs(), suppress_background_process(), suppress_snapshots(), sys_color_changed(), take_snapshot(), take_snapshot(), toggle_render_statistic_dialog(), toggle_show_wireframe(), unbind_canvas_event_handlers(), undo(), undo_redo_stack_main(), undo_redo_string_getter(), undo_redo_topmost_string_getter(), undo_to(), up_to_date(), update(), update_filament_colors_in_full_config(), update_menus(), update_preview_bottom_toolbar(), update_project_dirty_from_presets(), update_slicing_context_to_current_partplate(), update_ui_from_settings(), and validate_current_plate().
skip_thumbnail_invalid
bool Slic3r::GUI::Plater::skip_thumbnail_invalid { false } private
Referenced by force_update_all_plate_thumbnails(), and invalid_all_plate_thumbnails().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Plater.hpp
src/slic3r/GUI/Plater.cpp