OrcaSlicer: thread_pool Class Reference
thread_pool Class Reference
#include <src/mcut/include/mcut/internal/tpool.h>
Public Member Functions
thread_pool (uint32_t nthreads, uint32_t used_cores)
~thread_pool ()
void wakeup_and_shutdown ()
template<typename FunctionType >
std::future< typename std::result_of< FunctionType()>::type > submit (uint32_t worker_thread_id, FunctionType f)
size_t get_num_threads () const
uint32_t get_num_hardware_threads ()
Private Member Functions
void worker_thread (int thread_id)
Private Attributes
std::atomic< bool > m_done
std::vector< thread_safe_queue< function_wrapper > > work_queues
std::vector< std::thread > threads
join_threads joiner
uint32_t machine_thread_count
Detailed Description
Constructor & Destructor Documentation
thread_pool()
thread_pool::thread_pool (uint32_t nthreads, uint32_t used_cores) inline
        :  m_done(false),
        joiner(threads)
        , machine_thread_count(0)
    {
        log_msg("[MCUT] Create threadpool " << this);
        machine_thread_count = (uint32_t)std::thread::hardware_concurrency();
        uint32_t const pool_thread_count = std::min(
            nthreads,
            // prevents over-subscription given that "N=used_cores" API threads are already in use
            machine_thread_count - used_cores);
        try {
            work_queues = std::vector<thread_safe_queue<function_wrapper>>(pool_thread_count);
            for (unsigned i = 0; i < pool_thread_count; ++i) {
                work_queues[i].set_done_ptr(&m_done);
                threads.push_back(std::thread(&thread_pool::worker_thread, this, i));
            }
        } catch (...) {
            m_done.store(true);
            wakeup_and_shutdown();
            throw;
        }
    }
References log_msg, m_done, machine_thread_count, threads, wakeup_and_shutdown(), work_queues, and worker_thread().
~thread_pool()
thread_pool::~thread_pool () inline
    {
        log_msg("[MCUT] Destroy threadpool " << this);
        m_done.store(true);
        wakeup_and_shutdown();
    }
References log_msg, m_done, and wakeup_and_shutdown().
Member Function Documentation
get_num_hardware_threads()
uint32_t thread_pool::get_num_hardware_threads () inline
    {
        return machine_thread_count;
    }
References machine_thread_count.
get_num_threads()
size_t thread_pool::get_num_threads () const inline
    {
        return threads.size();
    }
References threads.
Referenced by parallel_find(), parallel_find_if(), parallel_find_in_map_by_key(), parallel_for(), parallel_for(), parallel_partial_sum(), and wakeup_and_shutdown().
submit()
template<typename FunctionType > std::future< typename std::result_of< FunctionType()>::type > thread_pool::submit (uint32_t worker_thread_id, FunctionType f) inline
    {
        typedef typename std::result_of<FunctionType()>::type result_type;
        std::packaged_task<result_type()> task(std::move(f));
        std::future<result_type> res(task.get_future());
        work_queues[worker_thread_id].push(std::move(task));
        return res;
    }
References work_queues.
Referenced by parallel_find(), parallel_find_if(), parallel_find_in_map_by_key(), parallel_for(), parallel_for(), and parallel_partial_sum().
wakeup_and_shutdown()
void thread_pool::wakeup_and_shutdown () inline
    {
        for (unsigned i = 0; i < get_num_threads(); ++i) {
            work_queues[i].disrupt_wait_for_data();
        }
    }
References get_num_threads(), and work_queues.
Referenced by thread_pool(), and ~thread_pool().
worker_thread()
void thread_pool::worker_thread (int thread_id) inline private
    {
        log_msg("[MCUT] Launch helper thread " << std::this_thread::get_id() << " (" << thread_id << ")");
        do {
            function_wrapper task;
            if (!(work_queues[thread_id].try_pop(task))) {
                work_queues[thread_id].wait_and_pop(task);
            }
            if (m_done) {
                break; // finished (i.e. MCUT context was destroyed)
            }
            task(); // run the task
        } while (true);
        log_msg("[MCUT] Shutdown helper thread " << std::this_thread::get_id() << " (" << thread_id << ")");
    }
References log_msg, m_done, and work_queues.
Referenced by thread_pool().
Member Data Documentation
joiner
join_threads thread_pool::joiner private
m_done
std::atomic<bool> thread_pool::m_done private
Referenced by thread_pool(), ~thread_pool(), and worker_thread().
machine_thread_count
uint32_t thread_pool::machine_thread_count private
Referenced by thread_pool(), and get_num_hardware_threads().
threads
std::vector<std::thread> thread_pool::threads private
Referenced by thread_pool(), and get_num_threads().
work_queues
std::vector<thread_safe_queue<function_wrapper> > thread_pool::work_queues private
Referenced by thread_pool(), submit(), wakeup_and_shutdown(), and worker_thread().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/tpool.h