OrcaSlicer: Slic3r::ClipperUtils Namespace Reference
Slic3r::ClipperUtils Namespace Reference
Classes
class EmptyPathsProvider
struct ExPolygonProvider
struct ExPolygonsProvider
class MultiPointsProvider
class PathsProvider
class PathsProviderIteratorBase
class SinglePathProvider
struct SurfacesProvider
struct SurfacesPtrProvider
Typedefs
using PolygonsProvider = MultiPointsProvider< Polygon >
using PolylinesProvider = MultiPointsProvider< Polyline >
using ZPoint = Vec3i32
using ZPoints = std::vector< Vec3i32 >
Functions
template<typename PointType >
void clip_clipper_polygon_with_subject_bbox_templ (const std::vector< PointType > &src, const BoundingBox &bbox, std::vector< PointType > &out, const bool get_entire_polygons=false)
void clip_clipper_polygon_with_subject_bbox (const Points &src, const BoundingBox &bbox, Points &out, const bool get_entire_polygons)
void clip_clipper_polygon_with_subject_bbox (const ZPoints &src, const BoundingBox &bbox, ZPoints &out)
template<typename PointType >
std::vector< PointType > clip_clipper_polygon_with_subject_bbox_templ (const std::vector< PointType > &src, const BoundingBox &bbox)
Points clip_clipper_polygon_with_subject_bbox (const Points &src, const BoundingBox &bbox)
ZPoints clip_clipper_polygon_with_subject_bbox (const ZPoints &src, const BoundingBox &bbox)
void clip_clipper_polygon_with_subject_bbox (const Polygon &src, const BoundingBox &bbox, Polygon &out)
Polygon clip_clipper_polygon_with_subject_bbox (const Polygon &src, const BoundingBox &bbox, const bool get_entire_polygons)
Polygons clip_clipper_polygons_with_subject_bbox (const Polygons &src, const BoundingBox &bbox)
Polygons clip_clipper_polygons_with_subject_bbox (const ExPolygon &src, const BoundingBox &bbox, const bool get_entire_polygons)
Polygons clip_clipper_polygons_with_subject_bbox (const ExPolygons &src, const BoundingBox &bbox, const bool get_entire_polygons)
Typedef Documentation
PolygonsProvider
using Slic3r::ClipperUtils::PolygonsProvider = typedef MultiPointsProvider<Polygon>
PolylinesProvider
using Slic3r::ClipperUtils::PolylinesProvider = typedef MultiPointsProvider<Polyline>
ZPoint
using Slic3r::ClipperUtils::ZPoint = typedef Vec3i32
ZPoints
using Slic3r::ClipperUtils::ZPoints = typedef std::vector<Vec3i32>
Function Documentation
clip_clipper_polygon_with_subject_bbox() [1/6]
Points Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const Points & src, const BoundingBox & bbox)
{ return clip_clipper_polygon_with_subject_bbox_templ(src, bbox); }
References clip_clipper_polygon_with_subject_bbox_templ().
clip_clipper_polygon_with_subject_bbox() [2/6]
void Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const Points & src, const BoundingBox & bbox, Points & out, const bool get_entire_polygons)
{ clip_clipper_polygon_with_subject_bbox_templ(src, bbox, out, get_entire_polygons); }
References clip_clipper_polygon_with_subject_bbox_templ(), and out.
Referenced by clip_clipper_polygon_with_subject_bbox(), clip_clipper_polygon_with_subject_bbox(), clip_clipper_polygon_with_subject_bbox_templ(), clip_clipper_polygons_with_subject_bbox(), clip_clipper_polygons_with_subject_bbox(), and Slic3r::traverse_extrusions().
clip_clipper_polygon_with_subject_bbox() [3/6]
Polygon Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const Polygon & src, const BoundingBox & bbox, const bool get_entire_polygons)
{
    Polygon out;
    clip_clipper_polygon_with_subject_bbox(src.points, bbox, out.points, get_entire_polygons);
    return out;
}
References clip_clipper_polygon_with_subject_bbox(), out, and Slic3r::MultiPoint::points.
clip_clipper_polygon_with_subject_bbox() [4/6]
void Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const Polygon & src, const BoundingBox & bbox, Polygon & out)
{
    clip_clipper_polygon_with_subject_bbox(src.points, bbox, out.points);
}
References clip_clipper_polygon_with_subject_bbox(), out, and Slic3r::MultiPoint::points.
clip_clipper_polygon_with_subject_bbox() [5/6]
ZPoints Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const ZPoints & src, const BoundingBox & bbox)
{ return clip_clipper_polygon_with_subject_bbox_templ(src, bbox); }
References clip_clipper_polygon_with_subject_bbox_templ().
clip_clipper_polygon_with_subject_bbox() [6/6]
void Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox (const ZPoints & src, const BoundingBox & bbox, ZPoints & out)
{ clip_clipper_polygon_with_subject_bbox_templ(src, bbox, out); }
References clip_clipper_polygon_with_subject_bbox_templ(), and out.
clip_clipper_polygon_with_subject_bbox_templ() [1/2]
template<typename PointType > std::vector< PointType > Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox_templ (const std::vector< PointType > & src, const BoundingBox & bbox)
{
    std::vector<PointType> out;
    clip_clipper_polygon_with_subject_bbox(src, bbox, out);
    return out;
}
References clip_clipper_polygon_with_subject_bbox(), and out.
clip_clipper_polygon_with_subject_bbox_templ() [2/2]
template<typename PointType > void Slic3r::ClipperUtils::clip_clipper_polygon_with_subject_bbox_templ (const std::vector< PointType > & src, const BoundingBox & bbox, std::vector< PointType > & out, const bool get_entire_polygons = false) inline
{
    out.clear();
    const size_t cnt = src.size();
    if (cnt < 3) return;
    enum class Side { Left = 1, Right = 2, Top = 4, Bottom = 8 };
    auto sides = [bbox](const PointType &p) {
        return int(p.x() < bbox.min.x()) * int(Side::Left) + int(p.x() > bbox.max.x()) * int(Side::Right) + int(p.y() < bbox.min.y()) * int(Side::Bottom) +
               int(p.y() > bbox.max.y()) * int(Side::Top);
    };
    int          sides_prev = sides(src.back());
    int          sides_this = sides(src.front());
    const size_t last       = cnt - 1;
    for (size_t i = 0; i < last; ++i) {
        int sides_next = sides(src[i + 1]);
        if ( // This point is inside. Take it.
            sides_this == 0 ||
            // Either this point is outside and previous or next is inside, or
            // the edge possibly cuts corner of the bounding box.
            (sides_prev & sides_this & sides_next) == 0) {
            out.emplace_back(src[i]);
            sides_prev = sides_this;
        } else {
            // All the three points (this, prev, next) are outside at the same side.
            // Ignore this point.
        }
        sides_this = sides_next;
    }
    // Never produce just a single point output polygon.
    if (!out.empty())
        if(get_entire_polygons){
            out=src;
        }else{
            if (int sides_next = sides(out.front());
            // The last point is inside. Take it.
            sides_this == 0 ||
            // Either this point is outside and previous or next is inside, or
            // the edge possibly cuts corner of the bounding box.
            (sides_prev & sides_this & sides_next) == 0)
            out.emplace_back(src.back());
        }
}
References int, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, and out.
Referenced by clip_clipper_polygon_with_subject_bbox(), clip_clipper_polygon_with_subject_bbox(), clip_clipper_polygon_with_subject_bbox(), and clip_clipper_polygon_with_subject_bbox().
clip_clipper_polygons_with_subject_bbox() [1/3]
Polygons Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox (const ExPolygon & src, const BoundingBox & bbox, const bool get_entire_polygons)
{
    Polygons out;
    out.reserve(src.num_contours());
    out.emplace_back(clip_clipper_polygon_with_subject_bbox(src.contour, bbox, get_entire_polygons));
    for (const Polygon &p : src.holes) out.emplace_back(clip_clipper_polygon_with_subject_bbox(p, bbox, get_entire_polygons));
    out.erase(std::remove_if(out.begin(), out.end(), [](const Polygon &polygon) { return polygon.empty(); }), out.end());
    return out;
}
References clip_clipper_polygon_with_subject_bbox(), Slic3r::ExPolygon::contour, Slic3r::ExPolygon::holes, Slic3r::ExPolygon::num_contours(), and out.
clip_clipper_polygons_with_subject_bbox() [2/3]
Polygons Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox (const ExPolygons & src, const BoundingBox & bbox, const bool get_entire_polygons)
{
    Polygons out;
    out.reserve(number_polygons(src));
    for (const ExPolygon &p : src) {
        Polygons temp = clip_clipper_polygons_with_subject_bbox(p, bbox, get_entire_polygons);
        out.insert(out.end(), temp.begin(), temp.end());
    }
    out.erase(std::remove_if(out.begin(), out.end(), [](const Polygon &polygon) {return polygon.empty(); }), out.end());
    return out;
}
References clip_clipper_polygons_with_subject_bbox(), Slic3r::number_polygons(), and out.
clip_clipper_polygons_with_subject_bbox() [3/3]
Polygons Slic3r::ClipperUtils::clip_clipper_polygons_with_subject_bbox (const Polygons & src, const BoundingBox & bbox)
{
    Polygons out;
    out.reserve(src.size());
    for (const Polygon &p : src) out.emplace_back(clip_clipper_polygon_with_subject_bbox(p, bbox));
    out.erase(std::remove_if(out.begin(), out.end(), [](const Polygon &polygon) { return polygon.empty(); }), out.end());
    return out;
}
References clip_clipper_polygon_with_subject_bbox(), and out.
Referenced by clip_clipper_polygons_with_subject_bbox(), Slic3r::PerimeterGenerator::split_top_surfaces(), Slic3r::RetractWhenCrossingPerimeters::travel_inside_internal_regions(), Slic3r::traverse_extrusions(), and Slic3r::traverse_loops().