OrcaSlicer: Slic3r::GUI::GridCellIconRenderer Class Reference
Slic3r::GUI::GridCellIconRenderer Class Reference
#include <src/slic3r/GUI/GUI_ObjectTable.hpp>
Public Member Functions
virtual void Draw (wxGrid &grid, wxGridCellAttr &attr, wxDC &dc, const wxRect &rect, int row, int col, bool isSelected) wxOVERRIDE
virtual wxSize GetBestSize (wxGrid &WXUNUSED(grid), wxGridCellAttr &attr, wxDC &dc, int WXUNUSED(row), int WXUNUSED(col)) wxOVERRIDE
virtual GridCellIconRenderer * Clone () const wxOVERRIDE
Detailed Description
Member Function Documentation
Clone()
GridCellIconRenderer * Slic3r::GUI::GridCellIconRenderer::Clone () const virtual
{
    return new GridCellIconRenderer();
}
Draw()
void Slic3r::GUI::GridCellIconRenderer::Draw (wxGrid & grid, wxGridCellAttr & attr, wxDC & dc, const wxRect & rect, int row, int col, bool isSelected) virtual
{
    ObjectGridTable *table = dynamic_cast<ObjectGridTable *>(grid.GetTable());
    wxGridCellRenderer::Draw(grid, attr, dc, rect, row, col, isSelected);
    if (table) {
        ObjectGridTable::ObjectGridCol* grid_col = table->get_grid_col(col);
        if (!grid_col || !grid_col->b_icon) {
            BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format(": cell (%1%, %2%) not icon type") %row %col;
            return;
        }
        ObjectGridTable::ObjectGridRow* grid_row = table->get_grid_row(row - 1);
        ConfigOption& orig_option = (*grid_row)[(ObjectGridTable::GridColType)col];
        ConfigOption& cur_option = (*grid_row)[(ObjectGridTable::GridColType)(col-1)];
        if (cur_option == orig_option) {
            //not changed
            return;
        }
        //if (!table->m_icon_col_width) {
            table->m_icon_row_height = grid.GetRowSize(row);
            table->m_icon_col_width = grid.GetColSize(col);
        //}
        wxBitmap& bitmap = table->get_undo_bitmap();
        int bitmap_width = bitmap.GetWidth();
        int bitmap_height = bitmap.GetHeight();
        int offset_x = (table->m_icon_col_width - bitmap_width)/2;
        int offset_y = (table->m_icon_row_height - bitmap_height)/2;
    #ifdef __WXOSX_COCOA__
        auto lock_pos = wxPoint(rect.x + offset_x, rect.y + offset_y);
        auto left     = (28 - 12) / 2;
        auto top      = (32 - 12) / 2;
        lock_pos.x += left;
        lock_pos.y += top;
        dc.DrawBitmap(bitmap, lock_pos);
    #else
        dc.DrawBitmap(bitmap, wxPoint(rect.x + offset_x, rect.y + offset_y));
    #endif
        //dc.SetPen(*wxGREEN_PEN);
        //dc.SetBrush(*wxTRANSPARENT_BRUSH);
        //dc.DrawEllipse(rect);
    }
    else {
        //should not happen
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ": no table found, should not happen" << std::endl;
    }
}
References Slic3r::GUI::ObjectGridTable::ObjectGridCol::b_icon, col(), error, Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), Slic3r::GUI::ObjectGridTable::get_undo_bitmap(), Slic3r::grid(), Slic3r::GUI::ObjectGridTable::m_icon_col_width, Slic3r::GUI::ObjectGridTable::m_icon_row_height, and row().
GetBestSize()
wxSize Slic3r::GUI::GridCellIconRenderer::GetBestSize (wxGrid & WXUNUSEDgrid, wxGridCellAttr & attr, wxDC & dc, int WXUNUSEDrow, int WXUNUSEDcol) virtual
{
    wxSize size{32, 30};
    return size;
}
References size.
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTable.hpp
src/slic3r/GUI/GUI_ObjectTable.cpp