OrcaSlicer: Slic3r::GUI::SavePresetDialog Class Reference
Slic3r::GUI::SavePresetDialog Class Reference
#include <src/slic3r/GUI/SavePresetDialog.hpp>
Classes
class Item
Public Member Functions
SavePresetDialog (wxWindow *parent, Preset::Type type, std::string suffix="")
SavePresetDialog (wxWindow *parent, std::vector< Preset::Type > types, std::string suffix="")
~SavePresetDialog ()
void AddItem (Preset::Type type, const std::string &suffix)
std::string get_name ()
std::string get_name (Preset::Type type)
void input_name_from_other (std::string new_preset_name)
void confirm_from_other ()
bool enable_ok_btn () const
void add_info_for_edit_ph_printer (wxBoxSizer *sizer)
void update_info_for_edit_ph_printer (const std::string &preset_name)
void layout ()
bool get_save_to_project_selection (Preset::Type type)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
void on_sys_color_changed () override
Private Types
enum ActionType { ChangePreset , AddPreset , Switch , UndefAction }
Private Member Functions
void build (std::vector< Preset::Type > types, std::string suffix="")
void on_select_cancel (wxCommandEvent &event)
void update_physical_printers (const std::string &preset_name)
void accept (wxCommandEvent &event)
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
std::vector< Item * > m_items
Button * m_confirm {nullptr}
Button * m_cancel {nullptr}
wxBoxSizer * m_presets_sizer {nullptr}
wxStaticText * m_label {nullptr}
wxBoxSizer * m_radio_sizer {nullptr}
ActionType m_action {UndefAction}
std::string m_ph_printer_name
std::string m_old_preset_name
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Member Enumeration Documentation
ActionType
enum Slic3r::GUI::SavePresetDialog::ActionType private
Enumerator
ChangePreset
AddPreset
Switch
UndefAction
    {
        ChangePreset,
        AddPreset,
        Switch,
        UndefAction
    };
Constructor & Destructor Documentation
SavePresetDialog() [1/2]
Slic3r::GUI::SavePresetDialog::SavePresetDialog (wxWindow * parent, Preset::Type type, std::string suffix = "")
    : DPIDialog(parent, wxID_ANY, _L("Save preset"), wxDefaultPosition, wxDefaultSize, wxCAPTION | wxCLOSE_BOX)
{
    build(std::vector<Preset::Type>{type}, suffix);
    wxGetApp().UpdateDlgDarkUI(this);
}
References build().
SavePresetDialog() [2/2]
Slic3r::GUI::SavePresetDialog::SavePresetDialog (wxWindow * parent, std::vector< Preset::Type > types, std::string suffix = "")
    : DPIDialog(parent, wxID_ANY, _L("Save preset"), wxDefaultPosition, wxDefaultSize, wxCAPTION | wxCLOSE_BOX)
{
    build(types, suffix);
    wxGetApp().UpdateDlgDarkUI(this);
}
References build().
~SavePresetDialog()
Slic3r::GUI::SavePresetDialog::~SavePresetDialog ()
{
    for (auto item : m_items) { delete item; }
}
References m_items.
Member Function Documentation
accept()
void Slic3r::GUI::SavePresetDialog::accept (wxCommandEvent & event) private
{
    for (Item *item : m_items) {
        item->accept();
        if (item->type() == Preset::TYPE_PRINTER) update_physical_printers(item->preset_name());
    }
    EndModal(wxID_OK);
}
References m_items, Slic3r::Preset::TYPE_PRINTER, and update_physical_printers().
Referenced by build().
add_info_for_edit_ph_printer()
void Slic3r::GUI::SavePresetDialog::add_info_for_edit_ph_printer (wxBoxSizer * sizer)
{
    PhysicalPrinterCollection &printers = wxGetApp().preset_bundle->physical_printers;
    m_ph_printer_name                   = printers.get_selected_printer_name();
    m_old_preset_name                   = printers.get_selected_printer_preset_name();
    wxString msg_text = from_u8((boost::format(_u8L("Printer \"%1%\" is selected with preset \"%2%\"")) %
                                 m_ph_printer_name % m_old_preset_name)
                                    .str());
    m_label           = new wxStaticText(this, wxID_ANY, msg_text);
    m_label->SetFont(wxGetApp().bold_font());
    m_action      = ChangePreset;
    m_radio_sizer = new wxBoxSizer(wxHORIZONTAL);
    wxStaticBox *action_stb = new wxStaticBox(this, wxID_ANY, "");
    if (!wxOSX) action_stb->SetBackgroundStyle(wxBG_STYLE_PAINT);
    action_stb->SetFont(wxGetApp().bold_font());
    wxStaticBoxSizer *stb_sizer = new wxStaticBoxSizer(action_stb, wxVERTICAL);
    for (int id = 0; id < 3; id++) {
        wxRadioButton *btn = new wxRadioButton(this, wxID_ANY, "", wxDefaultPosition, wxDefaultSize, id == 0 ? wxRB_GROUP : 0);
        btn->SetValue(id == int(ChangePreset));
        btn->Bind(wxEVT_RADIOBUTTON, [this, id](wxCommandEvent &) { m_action = (ActionType) id; });
        stb_sizer->Add(btn, 0, wxEXPAND | wxTOP, 5);
    }
    m_radio_sizer->Add(stb_sizer, 1, wxEXPAND | wxTOP, 2 * BORDER_W);
    sizer->Add(m_label, 0, wxEXPAND | wxLEFT | wxTOP, 3 * BORDER_W);
    sizer->Add(m_radio_sizer, 1, wxEXPAND | wxLEFT, 3 * BORDER_W);
}
References _u8L, BORDER_W, ChangePreset, Slic3r::GUI::from_u8(), Slic3r::PhysicalPrinterCollection::get_selected_printer_name(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), m_action, m_label, m_old_preset_name, m_ph_printer_name, m_radio_sizer, wxOSX, and wxStaticText.
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item().
AddItem()
void Slic3r::GUI::SavePresetDialog::AddItem (Preset::Type type, const std::string & suffix)
{ m_items.emplace_back(new Item{type, suffix, m_presets_sizer, this}); }
References m_items, and m_presets_sizer.
Referenced by build().
build()
void Slic3r::GUI::SavePresetDialog::build (std::vector< Preset::Type > types, std::string suffix = "") private
{
    // def setting
    SetBackgroundColour(SAVE_PRESET_DIALOG_DEF_COLOUR);
    SetFont(wxGetApp().normal_font());
    // icon
    std::string icon_path = (boost::format("%1%/images/OrcaSlicerTitle.ico") % resources_dir()).str();
    SetIcon(wxIcon(encode_path(icon_path.c_str()), wxBITMAP_TYPE_ICO));
    if (suffix.empty()) suffix = _CTX_utf8(L_CONTEXT("Copy", "PresetName"), "PresetName");
    wxBoxSizer *m_Sizer_main = new wxBoxSizer(wxVERTICAL);
    m_presets_sizer = new wxBoxSizer(wxVERTICAL);
    // Add first item
    for (Preset::Type type : types) AddItem(type, suffix);
    wxBoxSizer *btns;
    btns = new wxBoxSizer(wxHORIZONTAL);
    btns->Add(0, 0, 1, wxEXPAND, 5);
    m_confirm = new Button(this, _L("OK"));
    StateColor btn_bg_green(std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed),
                            std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
                            std::pair<wxColour, int>(wxColour(0, 150, 136), StateColor::Normal));
    m_confirm->SetBackgroundColor(btn_bg_green);
    m_confirm->SetBorderColor(wxColour(0, 150, 136));
    m_confirm->SetTextColor(wxColour("#FFFFFE"));
    m_confirm->SetMinSize(SAVE_PRESET_DIALOG_BUTTON_SIZE);
    m_confirm->SetCornerRadius(FromDIP(12));
    m_confirm->Bind(wxEVT_BUTTON, &SavePresetDialog::accept, this);
    btns->Add(m_confirm, 0, wxEXPAND, 0);
    auto block_middle = new wxWindow(this, -1);
    block_middle->SetBackgroundColour(SAVE_PRESET_DIALOG_DEF_COLOUR);
    btns->Add(block_middle, 0, wxRIGHT, 10);
    m_cancel = new Button(this, _L("Cancel"));
    m_cancel->SetMinSize(SAVE_PRESET_DIALOG_BUTTON_SIZE);
    m_cancel->SetCornerRadius(FromDIP(12));
    m_cancel->Bind(wxEVT_BUTTON, &SavePresetDialog::on_select_cancel, this);
    btns->Add(m_cancel, 0, wxEXPAND, 0);
    auto block_right = new wxWindow(this, -1);
    block_right->SetBackgroundColour(SAVE_PRESET_DIALOG_DEF_COLOUR);
    btns->Add(block_right, 0, wxRIGHT, 40);
    auto m_line = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, 1), wxTAB_TRAVERSAL);
    m_line->SetBackgroundColour(wxColour(166, 169, 170));
    m_Sizer_main->Add( m_line, 0, wxEXPAND, 0 );
    m_Sizer_main->Add(m_presets_sizer, 0, wxEXPAND | wxALL, BORDER_W);
    m_Sizer_main->Add(btns, 0, wxEXPAND | wxBOTTOM, BORDER_W + 7);
    SetSizer(m_Sizer_main);
    m_Sizer_main->SetSizeHints(this);
    this->Centre(wxBOTH);
}
References _CTX_utf8, _L, accept(), AddItem(), BORDER_W, Slic3r::encode_path(), StateColor::Hovered, L_CONTEXT, m_cancel, m_confirm, m_presets_sizer, StateColor::Normal, Slic3r::GUI::DPIAware< P >::normal_font(), on_select_cancel(), StateColor::Pressed, Slic3r::resources_dir(), SAVE_PRESET_DIALOG_BUTTON_SIZE, SAVE_PRESET_DIALOG_DEF_COLOUR, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetMinSize(), Button::SetTextColor(), and wxEVT_BUTTON.
Referenced by SavePresetDialog(), and SavePresetDialog().
confirm_from_other()
void Slic3r::GUI::SavePresetDialog::confirm_from_other ()
{
    for (Item *item : m_items) {
        item->accept();
        if (item->type() == Preset::TYPE_PRINTER) update_physical_printers(item->preset_name());
    }
}
References m_items, Slic3r::Preset::TYPE_PRINTER, and update_physical_printers().
Referenced by Slic3r::GUI::Tab::save_preset().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
enable_ok_btn()
bool Slic3r::GUI::SavePresetDialog::enable_ok_btn () const
{
    for (const Item *item : m_items)
        if (!item->is_valid()) return false;
    return true;
}
References m_items.
get_name() [1/2]
std::string Slic3r::GUI::SavePresetDialog::get_name ()
{ return m_items.front()->preset_name(); }
References m_items.
Referenced by Slic3r::GUI::UnsavedChangesDialog::save(), and Slic3r::GUI::Tab::save_preset().
get_name() [2/2]
std::string Slic3r::GUI::SavePresetDialog::get_name (Preset::Type type)
{
    for (const Item *item : m_items)
        if (item->type() == type) return item->preset_name();
    return "";
}
References m_items.
get_save_to_project_selection()
bool Slic3r::GUI::SavePresetDialog::get_save_to_project_selection (Preset::Type type)
{
    for (const Item *item : m_items)
        if (item->type() == type) return item->save_to_project();
    return false;
}
References m_items.
Referenced by Slic3r::GUI::UnsavedChangesDialog::save(), and Slic3r::GUI::Tab::save_preset().
input_name_from_other()
void Slic3r::GUI::SavePresetDialog::input_name_from_other (std::string new_preset_name)
{
    //only work for one-item
    Item* curr_item = m_items[0];
    curr_item->m_input_ctrl->GetTextCtrl()->SetValue(new_preset_name);
}
References TextInput::GetTextCtrl(), Slic3r::GUI::SavePresetDialog::Item::m_input_ctrl, and m_items.
Referenced by Slic3r::GUI::Tab::save_preset().
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
layout()
void Slic3r::GUI::SavePresetDialog::layout ()
{
    this->Layout();
    this->Fit();
}
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_dpi_changed()
void Slic3r::GUI::SavePresetDialog::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    const int &em = em_unit();
    msw_buttons_rescale(this, em, {wxID_OK, wxID_CANCEL});
    //for (Item *item : m_items) item->update_valid_bmp();
    // const wxSize& size = wxSize(45 * em, 35 * em);
    //SetMinSize(/*size*/ wxSize(100, 50));
    m_confirm->SetMinSize(SAVE_PRESET_DIALOG_BUTTON_SIZE);
    m_cancel->SetMinSize(SAVE_PRESET_DIALOG_BUTTON_SIZE);
    Fit();
    Refresh();
}
References Slic3r::GUI::DPIAware< P >::em_unit(), m_cancel, m_confirm, msw_buttons_rescale(), SAVE_PRESET_DIALOG_BUTTON_SIZE, and Button::SetMinSize().
on_select_cancel()
void Slic3r::GUI::SavePresetDialog::on_select_cancel (wxCommandEvent & event) private
{
    EndModal(wxID_CANCEL);
}
Referenced by build().
on_sys_color_changed()
void Slic3r::GUI::SavePresetDialog::on_sys_color_changed () inline override protected virtual
Reimplemented from Slic3r::GUI::DPIAware< P >.
{}
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
update_info_for_edit_ph_printer()
void Slic3r::GUI::SavePresetDialog::update_info_for_edit_ph_printer (const std::string & preset_name)
{
    bool show = wxGetApp().preset_bundle->physical_printers.has_selection() && m_old_preset_name != preset_name;
    m_label->Show(show);
    m_radio_sizer->ShowItems(show);
    if (!show) {
        this->SetMinSize(wxSize(100, 50));
        return;
    }
    if (wxSizerItem *sizer_item = m_radio_sizer->GetItem(size_t(0))) {
        if (wxStaticBoxSizer *stb_sizer = static_cast<wxStaticBoxSizer *>(sizer_item->GetSizer())) {
            wxString msg_text = format_wxstr(_L("Please choose an action with \"%1%\" preset after saving."), preset_name);
            stb_sizer->GetStaticBox()->SetLabel(msg_text);
            wxString choices[] = {format_wxstr(_L("For \"%1%\", change \"%2%\" to \"%3%\" "), m_ph_printer_name, m_old_preset_name, preset_name),
                                  format_wxstr(_L("For \"%1%\", add \"%2%\" as a new preset"), m_ph_printer_name, preset_name),
                                  format_wxstr(_L("Simply switch to \"%1%\""), preset_name)};
            size_t n = 0;
            for (const wxString &label : choices) stb_sizer->GetItem(n++)->GetWindow()->SetLabel(label);
        }
        Refresh();
    }
}
References _L, Slic3r::GUI::format_wxstr(), m_label, m_old_preset_name, m_ph_printer_name, m_radio_sizer, and n.
update_physical_printers()
void Slic3r::GUI::SavePresetDialog::update_physical_printers (const std::string & preset_name) private
{
    if (m_action == UndefAction) return;
    PhysicalPrinterCollection &physical_printers = wxGetApp().preset_bundle->physical_printers;
    if (!physical_printers.has_selection()) return;
    std::string printer_preset_name = physical_printers.get_selected_printer_preset_name();
    if (m_action == Switch)
        // unselect physical printer, if it was selected
        physical_printers.unselect_printer();
    else {
        PhysicalPrinter printer = physical_printers.get_selected_printer();
        if (m_action == ChangePreset) printer.delete_preset(printer_preset_name);
        if (printer.add_preset(preset_name)) physical_printers.save_printer(printer);
        physical_printers.select_printer(printer.get_full_name(preset_name));
    }
}
References Slic3r::PhysicalPrinter::add_preset(), ChangePreset, Slic3r::PhysicalPrinter::delete_preset(), Slic3r::PhysicalPrinter::get_full_name(), Slic3r::PhysicalPrinterCollection::get_selected_printer(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), Slic3r::PhysicalPrinterCollection::has_selection(), m_action, Slic3r::PhysicalPrinterCollection::save_printer(), Slic3r::PhysicalPrinterCollection::select_printer(), Switch, UndefAction, and Slic3r::PhysicalPrinterCollection::unselect_printer().
Referenced by accept(), and confirm_from_other().
Member Data Documentation
m_action
ActionType Slic3r::GUI::SavePresetDialog::m_action {UndefAction} private
Referenced by add_info_for_edit_ph_printer(), and update_physical_printers().
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_cancel
Button* Slic3r::GUI::SavePresetDialog::m_cancel {nullptr} private
Referenced by build(), and on_dpi_changed().
m_confirm
Button* Slic3r::GUI::SavePresetDialog::m_confirm {nullptr} private
Referenced by build(), and on_dpi_changed().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_items
std::vector<Item*> Slic3r::GUI::SavePresetDialog::m_items private
Referenced by ~SavePresetDialog(), accept(), AddItem(), confirm_from_other(), enable_ok_btn(), get_name(), get_name(), get_save_to_project_selection(), and input_name_from_other().
m_label
wxStaticText* Slic3r::GUI::SavePresetDialog::m_label {nullptr} private
Referenced by add_info_for_edit_ph_printer(), and update_info_for_edit_ph_printer().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_old_preset_name
std::string Slic3r::GUI::SavePresetDialog::m_old_preset_name private
Referenced by add_info_for_edit_ph_printer(), and update_info_for_edit_ph_printer().
m_ph_printer_name
std::string Slic3r::GUI::SavePresetDialog::m_ph_printer_name private
Referenced by add_info_for_edit_ph_printer(), and update_info_for_edit_ph_printer().
m_presets_sizer
wxBoxSizer* Slic3r::GUI::SavePresetDialog::m_presets_sizer {nullptr} private
Referenced by AddItem(), and build().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_radio_sizer
wxBoxSizer* Slic3r::GUI::SavePresetDialog::m_radio_sizer {nullptr} private
Referenced by add_info_for_edit_ph_printer(), and update_info_for_edit_ph_printer().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
The documentation for this class was generated from the following files:
src/slic3r/GUI/SavePresetDialog.hpp
src/slic3r/GUI/SavePresetDialog.cpp