OrcaSlicer: Slic3r::ModelVolume Class Reference
Slic3r::ModelVolume Class Reference final
#include <src/libslic3r/Model.hpp>
Classes
struct CutInfo
struct Source
Public Types
using Timestamp = uint64_t
Public Member Functions
bool is_cut_connector () const
void invalidate_cut_info ()
const TriangleMesh & mesh () const
const TriangleMesh * mesh_ptr () const
void set_mesh (const TriangleMesh &mesh)
void set_mesh (TriangleMesh &&mesh)
void set_mesh (const indexed_triangle_set &mesh)
void set_mesh (indexed_triangle_set &&mesh)
void set_mesh (std::shared_ptr< const TriangleMesh > &mesh)
void set_mesh (std::unique_ptr< const TriangleMesh > &&mesh)
void reset_mesh ()
ModelObject * get_object () const
ModelVolumeType type () const
void set_type (const ModelVolumeType t)
bool is_model_part () const
bool is_negative_volume () const
bool is_modifier () const
bool is_support_enforcer () const
bool is_support_blocker () const
bool is_support_modifier () const
t_model_material_id material_id () const
void set_material_id (t_model_material_id material_id)
ModelMaterial * material () const
void set_material (t_model_material_id material_id, const ModelMaterial &material)
int extruder_id () const
bool is_splittable () const
void apply_tolerance ()
std::vector< int > get_extruders () const
void update_extruder_count (size_t extruder_count)
size_t split (unsigned int max_extruders)
void translate (double x, double y, double z)
void translate (const Vec3d &displacement)
void scale (const Vec3d &scaling_factors)
void scale (double x, double y, double z)
void scale (double s)
void rotate (double angle, Axis axis)
void rotate (double angle, const Vec3d &axis)
void mirror (Axis axis)
void scale_geometry_after_creation (const Vec3f &versor)
void scale_geometry_after_creation (const float scale)
void center_geometry_after_creation (bool update_source_offset=true)
void calculate_convex_hull ()
const TriangleMesh & get_convex_hull () const
const std::shared_ptr< const TriangleMesh > & get_convex_hull_shared_ptr () const
const Polygon & get_convex_hull_2d (const Transform3d &trafo_instance) const
void invalidate_convex_hull_2d ()
int get_repaired_errors_count () const
const Geometry::Transformation & get_transformation () const
void set_transformation (const Geometry::Transformation &transformation)
void set_transformation (const Transform3d &trafo)
const Vec3d & get_offset () const
double get_offset (Axis axis) const
void set_offset (const Vec3d &offset)
void set_offset (Axis axis, double offset)
const Vec3d & get_rotation () const
double get_rotation (Axis axis) const
void set_rotation (const Vec3d &rotation)
void set_rotation (Axis axis, double rotation)
Vec3d get_scaling_factor () const
double get_scaling_factor (Axis axis) const
void set_scaling_factor (const Vec3d &scaling_factor)
void set_scaling_factor (Axis axis, double scaling_factor)
const Vec3d & get_mirror () const
double get_mirror (Axis axis) const
bool is_left_handed () const
void set_mirror (const Vec3d &mirror)
void set_mirror (Axis axis, double mirror)
void convert_from_imperial_units ()
void convert_from_meters ()
void set_text_info (const TextInfo &text_info)
const TextInfo & get_text_info () const
const Transform3d & get_matrix (bool dont_translate=false, bool dont_rotate=false, bool dont_scale=false, bool dont_mirror=false) const
void set_new_unique_id ()
bool is_fdm_support_painted () const
bool is_seam_painted () const
bool is_mm_painted () const
ObjectID id () const
virtual Timestamp timestamp () const
Static Public Member Functions
static ModelVolumeType type_from_string (const std::string &s)
static std::string type_to_string (const ModelVolumeType t)
Public Attributes
std::string name
Source source
CutInfo cut_info
ModelConfigObject config
FacetsAnnotation supported_facets
FacetsAnnotation seam_facets
FacetsAnnotation mmu_segmentation_facets
std::vector< int > mmuseg_extruders
Timestamp mmuseg_ts
FacetsAnnotation exterior_facets
Protected Member Functions
ModelVolume (const ModelVolume &rhs)=default
void set_model_object (ModelObject *model_object)
void assign_new_unique_ids_recursive () override
void transform_this_mesh (const Transform3d &t, bool fix_left_handed)
void transform_this_mesh (const Matrix3d &m, bool fix_left_handed)
void set_invalid_id ()
void copy_id (const ObjectBase &rhs)
Private Member Functions
void calculate_convex_hull_2d (const Geometry::Transformation &transformation) const
ModelVolume (ModelObject *object, const TriangleMesh &mesh, ModelVolumeType type=ModelVolumeType::MODEL_PART)
ModelVolume (ModelObject *object, const std::shared_ptr< const TriangleMesh > &mesh, ModelVolumeType type=ModelVolumeType::MODEL_PART)
ModelVolume (ModelObject *object, TriangleMesh &&mesh, TriangleMesh &&convex_hull, ModelVolumeType type=ModelVolumeType::MODEL_PART)
ModelVolume (ModelObject *object, const ModelVolume &other)
ModelVolume (ModelObject *object, const ModelVolume &other, const TriangleMesh &&mesh)
ModelVolume & operator= (ModelVolume &rhs)=delete
ModelVolume ()
template<class Archive >
void load (Archive &ar)
template<class Archive >
void save (Archive &ar) const
template<class Archive >
void serialize (Archive &ar)
Static Private Member Functions
static ObjectID generate_new_id ()
template<class Archive >
static void load_and_construct (Archive &ar, cereal::construct< ObjectBase > &construct)
Private Attributes
ModelObject * object
std::shared_ptr< const TriangleMesh > m_mesh
ModelVolumeType m_type
t_model_material_id m_material_id
std::shared_ptr< const TriangleMesh > m_convex_hull
Polygon m_convex_hull_2d
Transform3d m_cached_trans_matrix
Polygon m_cached_2d_polygon
Geometry::Transformation m_transformation
TextInfo m_text_info
int m_is_splittable { -1 }
ObjectID m_id
Static Private Attributes
static size_t s_last_id = 0
Friends
class Print
class SLAPrint
class Model
class ModelObject
class cereal::access
class UndoRedo::StackImpl
void model_volume_list_update_supports (ModelObject &model_object_dst, const ModelObject &model_object_new)
Detailed Description
Member Typedef Documentation
Timestamp
using Slic3r::ObjectBase::Timestamp = uint64_t inherited
Constructor & Destructor Documentation
ModelVolume() [1/7]
Slic3r::ModelVolume::ModelVolume (const ModelVolume & rhs) explicit protected default
ModelVolume() [2/7]
Slic3r::ModelVolume::ModelVolume (ModelObject * object, const TriangleMesh & mesh, ModelVolumeType type = ModelVolumeType::MODEL_PART) inline private
                                                                                                               : m_mesh(new TriangleMesh(mesh)), m_type(type), object(object)
    {
    assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->supported_facets.id().valid());
        assert(this->seam_facets.id().valid());
        assert(this->mmu_segmentation_facets.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->supported_facets.id());
        assert(this->id() != this->seam_facets.id());
        assert(this->id() != this->mmu_segmentation_facets.id());
        if (mesh.facets_count() > 1)
            calculate_convex_hull();
    }
References calculate_convex_hull(), Slic3r::TriangleMesh::facets_count(), Slic3r::ObjectBase::id(), mesh(), and Slic3r::ObjectID::valid().
ModelVolume() [3/7]
Slic3r::ModelVolume::ModelVolume (ModelObject * object, const std::shared_ptr< const TriangleMesh > & mesh, ModelVolumeType type = ModelVolumeType::MODEL_PART) inline private
                                                                                                                                      : m_mesh(mesh), m_type(type), object(object)
    {
    assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->supported_facets.id().valid());
        assert(this->seam_facets.id().valid());
        assert(this->mmu_segmentation_facets.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->supported_facets.id());
        assert(this->id() != this->seam_facets.id());
        assert(this->id() != this->mmu_segmentation_facets.id());
    }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectID::valid().
ModelVolume() [4/7]
Slic3r::ModelVolume::ModelVolume (ModelObject * object, TriangleMesh && mesh, TriangleMesh && convex_hull, ModelVolumeType type = ModelVolumeType::MODEL_PART) inline private
                                                                                                                                        :
    m_mesh(new TriangleMesh(std::move(mesh))), m_convex_hull(new TriangleMesh(std::move(convex_hull))), m_type(type), object(object) {
    assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->supported_facets.id().valid());
        assert(this->seam_facets.id().valid());
        assert(this->mmu_segmentation_facets.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->supported_facets.id());
        assert(this->id() != this->seam_facets.id());
        assert(this->id() != this->mmu_segmentation_facets.id());
  }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectID::valid().
ModelVolume() [5/7]
Slic3r::ModelVolume::ModelVolume (ModelObject * object, const ModelVolume & other) inline private
                                                               :
        ObjectBase(other),
        name(other.name), source(other.source), m_mesh(other.m_mesh), m_convex_hull(other.m_convex_hull),
        config(other.config), m_type(other.m_type), object(object), m_transformation(other.m_transformation),
        supported_facets(other.supported_facets), seam_facets(other.seam_facets), mmu_segmentation_facets(other.mmu_segmentation_facets),
        m_text_info(other.m_text_info)
    {
    assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->supported_facets.id().valid());
        assert(this->seam_facets.id().valid());
        assert(this->mmu_segmentation_facets.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->supported_facets.id());
        assert(this->id() != this->seam_facets.id());
        assert(this->id() != this->mmu_segmentation_facets.id());
    assert(this->id() == other.id());
        assert(this->config.id() == other.config.id());
        assert(this->supported_facets.id() == other.supported_facets.id());
        assert(this->seam_facets.id() == other.seam_facets.id());
        assert(this->mmu_segmentation_facets.id() == other.mmu_segmentation_facets.id());
        this->set_material_id(other.material_id());
    }
References config, Slic3r::ObjectBase::id(), material_id(), mmu_segmentation_facets, seam_facets, set_material_id(), supported_facets, and Slic3r::ObjectID::valid().
ModelVolume() [6/7]
Slic3r::ModelVolume::ModelVolume (ModelObject * object, const ModelVolume & other, const TriangleMesh && mesh) inline private
                                                                                          :
        name(other.name), source(other.source), m_mesh(new TriangleMesh(std::move(mesh))), config(other.config), m_type(other.m_type), object(object), m_transformation(other.m_transformation)
    {
    assert(this->id().valid());
        assert(this->config.id().valid());
        assert(this->supported_facets.id().valid());
        assert(this->seam_facets.id().valid());
        assert(this->mmu_segmentation_facets.id().valid());
        assert(this->id() != this->config.id());
        assert(this->id() != this->supported_facets.id());
        assert(this->id() != this->seam_facets.id());
        assert(this->id() != this->mmu_segmentation_facets.id());
    assert(this->id() != other.id());
        assert(this->config.id() == other.config.id());
        this->set_material_id(other.material_id());
        this->config.set_new_unique_id();
        if (mesh.facets_count() > 1)
            calculate_convex_hull();
    assert(this->config.id().valid());
        assert(this->config.id() != other.config.id());
        assert(this->supported_facets.id() != other.supported_facets.id());
        assert(this->seam_facets.id() != other.seam_facets.id());
        assert(this->mmu_segmentation_facets.id() != other.mmu_segmentation_facets.id());
        assert(this->id() != this->config.id());
        assert(this->supported_facets.empty());
        assert(this->seam_facets.empty());
        assert(this->mmu_segmentation_facets.empty());
    }
References calculate_convex_hull(), config, Slic3r::FacetsAnnotation::empty(), Slic3r::TriangleMesh::facets_count(), Slic3r::ObjectBase::id(), material_id(), mesh(), mmu_segmentation_facets, seam_facets, set_material_id(), Slic3r::ObjectBase::set_new_unique_id(), supported_facets, and Slic3r::ObjectID::valid().
ModelVolume() [7/7]
Slic3r::ModelVolume::ModelVolume () inline private
                : ObjectBase(-1), config(-1), supported_facets(-1), seam_facets(-1), mmu_segmentation_facets(-1), object(nullptr) {
    assert(this->id().invalid());
        assert(this->config.id().invalid());
        assert(this->supported_facets.id().invalid());
        assert(this->seam_facets.id().invalid());
        assert(this->mmu_segmentation_facets.id().invalid());
  }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectID::invalid().
Member Function Documentation
apply_tolerance()
void Slic3r::ModelVolume::apply_tolerance ()
{
    assert(cut_info.is_connector);
    if (!cut_info.is_processed)
        return;
    Vec3d sf = get_scaling_factor();
    // make a "hole" wider
    double size_scale = 1.f;
    if (abs(cut_info.radius - 0) < EPSILON) // For compatibility with old files
        size_scale = 1.f + double(cut_info.radius_tolerance);
    else
        size_scale = (double(cut_info.radius) + double(cut_info.radius_tolerance)) / double(cut_info.radius);
    sf[X] *= size_scale;
    sf[Y] *= size_scale;
    // make a "hole" dipper
    double height_scale = 1.f;
    if (abs(cut_info.height - 0) < EPSILON)  // For compatibility with old files
        height_scale = 1.f + double(cut_info.height_tolerance);
    else
        height_scale = (double(cut_info.height) + double(cut_info.height_tolerance)) / double(cut_info.height);
    sf[Z] *= height_scale;
    set_scaling_factor(sf);
}
References cut_info, EPSILON, get_scaling_factor(), Slic3r::ModelVolume::CutInfo::height, Slic3r::ModelVolume::CutInfo::height_tolerance, Slic3r::ModelVolume::CutInfo::is_connector, Slic3r::ModelVolume::CutInfo::is_processed, Slic3r::ModelVolume::CutInfo::radius, Slic3r::ModelVolume::CutInfo::radius_tolerance, set_scaling_factor(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by Slic3r::ModelObject::process_connector_cut().
assign_new_unique_ids_recursive()
void Slic3r::ModelVolume::assign_new_unique_ids_recursive () override protected virtual
Reimplemented from Slic3r::ObjectBase.
{
    ObjectBase::set_new_unique_id();
    config.set_new_unique_id();
    supported_facets.set_new_unique_id();
    seam_facets.set_new_unique_id();
    mmu_segmentation_facets.set_new_unique_id();
}
References config, mmu_segmentation_facets, seam_facets, Slic3r::ObjectBase::set_new_unique_id(), and supported_facets.
calculate_convex_hull()
void Slic3r::ModelVolume::calculate_convex_hull ()
{
    m_convex_hull = std::make_shared<TriangleMesh>(this->mesh().convex_hull_3d());
    assert(m_convex_hull.get());
}
References m_convex_hull, and mesh().
Referenced by ModelVolume(), ModelVolume(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::AMFParserContext::endElement(), load(), scale_geometry_after_creation(), and split().
calculate_convex_hull_2d()
void Slic3r::ModelVolume::calculate_convex_hull_2d (const Geometry::Transformation & transformation) const private
{
    const indexed_triangle_set &its = m_convex_hull->its;
  if (its.vertices.empty())
        return;
    Points pts;
    Vec3d rotation = transformation.get_rotation();
    Vec3d mirror = transformation.get_mirror();
    Vec3d scale = transformation.get_scaling_factor();
    //rotation(2) = 0.f;
    Transform3d new_matrix = Geometry::assemble_transform(Vec3d::Zero(), rotation, scale, mirror);
    pts.reserve(its.vertices.size());
    // Using the shared vertices should be a bit quicker than using the STL faces.
    for (size_t i = 0; i < its.vertices.size(); ++ i) {
        Vec3d p = new_matrix * its.vertices[i].cast<double>();
        pts.emplace_back(coord_t(scale_(p.x())), coord_t(scale_(p.y())));
    }
    //TODO, do we need to remove the duplicate points before convex_hull?
    m_cached_2d_polygon = Slic3r::Geometry::convex_hull(pts);
    m_convex_hull_2d = m_cached_2d_polygon;
    m_convex_hull_2d.translate(scale_(transformation.get_offset(X)), scale_(transformation.get_offset(Y)));
    //int size = m_cached_2d_polygon.size();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": size %1%, offset {%2%, %3%}")% size% transformation.get_offset(X)% transformation.get_offset(Y);
    //for (int i = 0; i < size; i++)
    //    BOOST_LOG_TRIVIAL(info) << boost::format(": point %1%, position {%2%, %3%}")% i% m_cached_2d_polygon[i].x()% m_cached_2d_polygon[i].y();
  //m_convex_hull_2d.rotate(transformation.get_rotation(Z));
    //m_convex_hull_2d.scale(transformation.get_scaling_factor(X), transformation.get_scaling_factor(Y));
}
References Slic3r::Geometry::assemble_transform(), Slic3r::Geometry::convex_hull(), Slic3r::Geometry::Transformation::get_mirror(), Slic3r::Geometry::Transformation::get_offset(), Slic3r::Geometry::Transformation::get_rotation(), Slic3r::Geometry::Transformation::get_scaling_factor(), m_cached_2d_polygon, m_convex_hull, m_convex_hull_2d, mirror(), scale(), scale_, Slic3r::MultiPoint::translate(), indexed_triangle_set::vertices, Slic3r::X, and Slic3r::Y.
Referenced by get_convex_hull_2d().
center_geometry_after_creation()
void Slic3r::ModelVolume::center_geometry_after_creation (bool update_source_offset = true)
{
    Vec3d shift = this->mesh().bounding_box().center();
    if (!shift.isApprox(Vec3d::Zero()))
    {
        if (m_mesh) {
            const_cast<TriangleMesh*>(m_mesh.get())->translate(-(float)shift(0), -(float)shift(1), -(float)shift(2));
            const_cast<TriangleMesh*>(m_mesh.get())->set_init_shift(shift);
        }
        if (m_convex_hull)
      const_cast<TriangleMesh*>(m_convex_hull.get())->translate(-(float)shift(0), -(float)shift(1), -(float)shift(2));
        translate(shift);
    }
    if (update_source_offset)
        source.mesh_offset = shift;
}
References Slic3r::TriangleMesh::bounding_box(), Slic3r::BoundingBox3Base< PointClass >::center(), m_convex_hull, m_mesh, mesh(), Slic3r::ModelVolume::Source::mesh_offset, source, and translate().
Referenced by Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::add_volume(), and Slic3r::AMFParserContext::endElement().
convert_from_imperial_units()
void Slic3r::ModelVolume::convert_from_imperial_units ()
{
    assert(! this->source.is_converted_from_meters);
    this->scale_geometry_after_creation(25.4f);
    this->set_offset(Vec3d(0, 0, 0));
    this->source.is_converted_from_inches = true;
}
References Slic3r::ModelVolume::Source::is_converted_from_inches, Slic3r::ModelVolume::Source::is_converted_from_meters, scale_geometry_after_creation(), set_offset(), and source.
Referenced by Slic3r::GUI::Plater::priv::replace_volume_with_stl().
convert_from_meters()
void Slic3r::ModelVolume::convert_from_meters ()
{
    assert(! this->source.is_converted_from_inches);
    this->scale_geometry_after_creation(1000.f);
    this->set_offset(Vec3d(0, 0, 0));
    this->source.is_converted_from_meters = true;
}
References Slic3r::ModelVolume::Source::is_converted_from_inches, Slic3r::ModelVolume::Source::is_converted_from_meters, scale_geometry_after_creation(), set_offset(), and source.
Referenced by Slic3r::GUI::Plater::priv::replace_volume_with_stl().
copy_id()
void Slic3r::ObjectBase::copy_id (const ObjectBase & rhs) inline protected inherited
{ m_id = rhs.id(); }
References Slic3r::ObjectBase::id(), and Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::copy().
extruder_id()
int Slic3r::ModelVolume::extruder_id () const
{
    int extruder_id = -1;
    //if (this->is_model_part())
    {
        const ConfigOption *opt = this->config.option("extruder");
        if ((opt == nullptr) || (opt->getInt() == 0))
            opt = this->object->config.option("extruder");
        extruder_id = (opt == nullptr) ? 1 : opt->getInt();
    }
    return extruder_id;
}
References config, extruder_id(), Slic3r::ConfigOption::getInt(), and Slic3r::ModelConfig::option().
Referenced by extruder_id(), get_extruders(), Slic3r::Model::getThermalLength(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolume::render(), Slic3r::GLVolume::simple_render(), split(), and update_extruder_count().
generate_new_id()
static ObjectID Slic3r::ObjectBase::generate_new_id () inline static private inherited
{ return ObjectID(++ s_last_id); }
References Slic3r::ObjectBase::s_last_id.
Referenced by Slic3r::ObjectBase::set_new_unique_id().
get_convex_hull()
const TriangleMesh & Slic3r::ModelVolume::get_convex_hull () const
{
    return *m_convex_hull.get();
}
References m_convex_hull.
Referenced by Slic3r::GUI::get_volume_min_z(), Slic3r::GUI::Plater::show_object_info(), transform_this_mesh(), and transform_this_mesh().
get_convex_hull_2d()
const Polygon & Slic3r::ModelVolume::get_convex_hull_2d (const Transform3d & trafo_instance) const
{
    Transform3d  new_matrix;
    new_matrix = trafo_instance * m_transformation.get_matrix();
    auto need_recompute = [](Geometry::Transformation& old_transform, Geometry::Transformation& new_transform)->bool {
            //double old_rot_x = old_transform.get_rotation(X);
            //double old_rot_y = old_transform.get_rotation(Y);
            //double new_rot_x = new_transform.get_rotation(X);
            //double new_rot_y = new_transform.get_rotation(Y);
            const Vec3d &old_rotation = old_transform.get_rotation();
            const Vec3d &new_rotation = new_transform.get_rotation();
            const Vec3d &old_mirror = old_transform.get_mirror();
            const Vec3d &new_mirror = new_transform.get_mirror();
            const Vec3d &old_scaling = old_transform.get_scaling_factor();
            const Vec3d &new_scaling = new_transform.get_scaling_factor();
            if ((old_scaling != new_scaling) || (old_rotation != new_rotation) || (old_mirror != new_mirror))
                return true;
            else
                return false;
        };
    if ((new_matrix.matrix() != m_cached_trans_matrix.matrix()) || !m_convex_hull_2d.is_valid())
    {
        Geometry::Transformation new_trans(new_matrix), old_trans(m_cached_trans_matrix);
        if (need_recompute(old_trans, new_trans) || !m_convex_hull_2d.is_valid())
        {
            //need to update
            calculate_convex_hull_2d(new_trans);
        }
        else
        {
            m_convex_hull_2d = m_cached_2d_polygon;
            m_convex_hull_2d.translate(scale_(new_trans.get_offset(X)), scale_(new_trans.get_offset(Y)));
            //m_convex_hull_2d.rotate(new_trans.get_rotation(Z));
            //m_convex_hull_2d.scale(new_trans.get_scaling_factor(X), new_trans.get_scaling_factor(Y));
            //int size = m_cached_2d_polygon.size();
            //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format(": use previous cached, size %1%, offset {%2%, %3%}")% size% new_trans.get_offset(X)% new_trans.get_offset(Y);
            //for (int i = 0; i < size; i++)
            //    BOOST_LOG_TRIVIAL(info) << boost::format(": point %1%, position {%2%, %3%}")% i% m_cached_2d_polygon[i].x()% m_cached_2d_polygon[i].y();
        }
        m_cached_trans_matrix = new_matrix;
    }
    return m_convex_hull_2d;
}
References calculate_convex_hull_2d(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::Geometry::Transformation::get_mirror(), Slic3r::Geometry::Transformation::get_rotation(), Slic3r::Geometry::Transformation::get_scaling_factor(), Slic3r::Polygon::is_valid(), m_cached_2d_polygon, m_cached_trans_matrix, m_convex_hull_2d, m_transformation, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), scale_, Slic3r::MultiPoint::translate(), Slic3r::X, and Slic3r::Y.
get_convex_hull_shared_ptr()
const std::shared_ptr< const TriangleMesh > & Slic3r::ModelVolume::get_convex_hull_shared_ptr () const inline
{ return m_convex_hull; }
References m_convex_hull.
Referenced by Slic3r::GLVolumeCollection::load_object_volume().
get_extruders()
std::vector< int > Slic3r::ModelVolume::get_extruders () const
{
    if (m_type == ModelVolumeType::INVALID
        || m_type == ModelVolumeType::NEGATIVE_VOLUME
        || m_type == ModelVolumeType::SUPPORT_BLOCKER
        || m_type == ModelVolumeType::SUPPORT_ENFORCER)
        return std::vector<int>();
    if (mmu_segmentation_facets.timestamp() != mmuseg_ts) {
        std::vector<indexed_triangle_set> its_per_type;
        mmuseg_extruders.clear();
        mmuseg_ts = mmu_segmentation_facets.timestamp();
        mmu_segmentation_facets.get_facets(*this, its_per_type);
        for (int idx = 1; idx < its_per_type.size(); idx++) {
            indexed_triangle_set& its = its_per_type[idx];
            if (its.indices.empty())
                continue;
            mmuseg_extruders.push_back(idx);
        }
    }
    std::vector<int> volume_extruders = mmuseg_extruders;
    int volume_extruder_id = this->extruder_id();
    if (volume_extruder_id > 0)
        volume_extruders.push_back(volume_extruder_id);
    return volume_extruders;
}
References extruder_id(), Slic3r::FacetsAnnotation::get_facets(), indexed_triangle_set::indices, Slic3r::INVALID, m_type, mmu_segmentation_facets, mmuseg_extruders, mmuseg_ts, Slic3r::NEGATIVE_VOLUME, Slic3r::SUPPORT_BLOCKER, Slic3r::SUPPORT_ENFORCER, and Slic3r::ObjectWithTimestamp::timestamp().
Referenced by update_extruder_count().
get_matrix()
const Transform3d & Slic3r::ModelVolume::get_matrix (bool dont_translate = false, bool dont_rotate = false, bool dont_scale = false, bool dont_mirror = false) const inline
{ return m_transformation.get_matrix(dont_translate, dont_rotate, dont_scale, dont_mirror); }
References Slic3r::Geometry::Transformation::get_matrix(), and m_transformation.
Referenced by Slic3r::configBrimWidthByVolumes(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_volume_list_changed(), Slic3r::GUI::Plater::show_object_info(), and Slic3r::GUI::GLGizmoText::update_text_positions().
get_mirror() [1/2]
const Vec3d & Slic3r::ModelVolume::get_mirror () const inline
{ return m_transformation.get_mirror(); }
References Slic3r::Geometry::Transformation::get_mirror(), and m_transformation.
Referenced by mirror().
get_mirror() [2/2]
double Slic3r::ModelVolume::get_mirror (Axis axis) const inline
{ return m_transformation.get_mirror(axis); }
References Slic3r::Geometry::Transformation::get_mirror(), and m_transformation.
get_object()
ModelObject * Slic3r::ModelVolume::get_object () const inline
{ return this->object; }
References object.
Referenced by Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::configBrimWidthByVolumes(), and Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
get_offset() [1/2]
const Vec3d & Slic3r::ModelVolume::get_offset () const inline
{ return m_transformation.get_offset(); }
References Slic3r::Geometry::Transformation::get_offset(), and m_transformation.
Referenced by Slic3r::ModelObject::split(), split(), and translate().
get_offset() [2/2]
double Slic3r::ModelVolume::get_offset (Axis axis) const inline
{ return m_transformation.get_offset(axis); }
References Slic3r::Geometry::Transformation::get_offset(), and m_transformation.
get_repaired_errors_count()
int Slic3r::ModelVolume::get_repaired_errors_count () const
{
    const RepairedMeshErrors &stats = this->mesh().stats().repaired_errors;
    return  stats.degenerate_facets + stats.edges_fixed     + stats.facets_removed +
            stats.facets_reversed + stats.backwards_edges;
}
References Slic3r::RepairedMeshErrors::backwards_edges, Slic3r::RepairedMeshErrors::degenerate_facets, Slic3r::RepairedMeshErrors::edges_fixed, Slic3r::RepairedMeshErrors::facets_removed, Slic3r::RepairedMeshErrors::facets_reversed, mesh(), Slic3r::TriangleMeshStats::repaired_errors, and Slic3r::TriangleMesh::stats().
get_rotation() [1/2]
const Vec3d & Slic3r::ModelVolume::get_rotation () const inline
{ return m_transformation.get_rotation(); }
References Slic3r::Geometry::Transformation::get_rotation(), and m_transformation.
Referenced by rotate().
get_rotation() [2/2]
double Slic3r::ModelVolume::get_rotation (Axis axis) const inline
{ return m_transformation.get_rotation(axis); }
References Slic3r::Geometry::Transformation::get_rotation(), and m_transformation.
get_scaling_factor() [1/2]
Vec3d Slic3r::ModelVolume::get_scaling_factor () const inline
{ return m_transformation.get_scaling_factor(); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and m_transformation.
Referenced by apply_tolerance(), and scale().
get_scaling_factor() [2/2]
double Slic3r::ModelVolume::get_scaling_factor (Axis axis) const inline
{ return m_transformation.get_scaling_factor(axis); }
References Slic3r::Geometry::Transformation::get_scaling_factor(), and m_transformation.
get_text_info()
const TextInfo & Slic3r::ModelVolume::get_text_info () const inline
{ return m_text_info; }
References m_text_info.
Referenced by Slic3r::GUI::Plater::priv::can_edit_text(), Slic3r::GUI::GLGizmoText::on_is_activable(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_input_window(), and Slic3r::GUI::GLGizmoText::on_set_state().
get_transformation()
const Geometry::Transformation & Slic3r::ModelVolume::get_transformation () const inline
{ return m_transformation; }
References m_transformation.
Referenced by Slic3r::ModelObject::delete_volume(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::Print::process(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
id()
ObjectID Slic3r::ObjectBase::id () const inline inherited
{ return m_id; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::Model::Model(), Slic3r::ModelInstance::ModelInstance(), Slic3r::ModelMaterial::ModelMaterial(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), Slic3r::ModelObject::ModelObject(), ModelVolume(), ModelVolume(), ModelVolume(), ModelVolume(), ModelVolume(), ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_config_file_to_archive(), Slic3r::_BBS_3MF_Exporter::_add_slice_info_config_file_to_archive(), Slic3r::GUI::Plater::priv::actualize_slicing_warnings(), Slic3r::ModelObjectStatusDB::add(), Slic3r::ModelObjectStatusDB::add_if_new(), Slic3r::Model::add_object(), Slic3r::append_and_translate(), Slic3r::Print::apply(), Slic3r::SLAPrint::apply(), Slic3r::ModelObject::apply_cut_attributes(), Slic3r::check_model_ids_equal(), Slic3r::Model::collect_reusable_objects(), Slic3r::ModelObject::convert_units(), Slic3r::ObjectBase::copy_id(), Slic3r::PrintObjectStatusDB::count(), Slic3r::Model::delete_object(), Slic3r::GUI::PartPlate::duplicate_all_instance(), Slic3r::Print::export_cached_data(), Slic3r::GUI::Plater::export_stl(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::ModelObjectStatusDB::get(), Slic3r::Model::get_backup_path(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLCanvas3D::get_empty_cells(), Slic3r::ModelInstance::get_labeled_id(), Slic3r::PrintObjectStatusDB::get_range(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::CutObjectBase::has_same_id(), Slic3r::UndoRedo::StackImpl::immutable_object_id_impl(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::ModelObject::is_cut(), Slic3r::CutObjectBase::is_equal(), Slic3r::ModelObject::load(), Slic3r::ObjectBase::load_and_construct(), Slic3r::Print::load_cached_data(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GCodeViewer::load_shells(), Slic3r::UndoRedo::StackImpl::load_snapshot(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::ModelConfigObject::object_id_and_timestamp_match(), Slic3r::ObjectWithTimestamp::object_id_and_timestamp_match(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::CommonGizmosDataObjects::HollowedMesh::on_update(), Slic3r::GUI::CommonGizmosDataObjects::SupportsClipper::on_update(), Slic3r::CutObjectBase::operator<(), Slic3r::Model::operator=(), Slic3r::ModelObject::operator=(), Slic3r::ModelObject::operator=(), Slic3r::CutObjectBase::operator==(), Slic3r::GUI::Plater::priv::process_validation_warning(), Slic3r::GUI::NotificationManager::push_slicing_warning_notification(), Slic3r::GUI::NotificationManager::push_validate_error_notification(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::_BBS_Backup_Manager::remove_backup(), Slic3r::Model::remove_backup_path_if_exist(), Slic3r::CLI::run(), Slic3r::ModelObject::segment(), Slic3r::GUI::GLCanvas3D::LayersEditing::select_object(), Slic3r::ModelMaterial::serialize(), Slic3r::Model::set_backup_path(), Slic3r::GUI::PartPlate::set_hover_id(), Slic3r::PrintObject::set_id(), Slic3r::SLAPrintObject::SliceRecord::set_model_slice_idx(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::SLAPrintObject::SliceRecord::set_support_slice_idx(), Slic3r::slices_to_regions(), Slic3r::sort_object_instances_by_model_order(), Slic3r::ModelObject::split(), Slic3r::UndoRedo::StackImpl::take_snapshot(), Slic3r::GUI::GLGizmoCut::update_contours(), and Slic3r::GUI::GLGizmoPainterBase::update_contours().
invalidate_convex_hull_2d()
void Slic3r::ModelVolume::invalidate_convex_hull_2d () inline
    {
        m_convex_hull_2d.clear();
    }
References Slic3r::MultiPoint::clear(), and m_convex_hull_2d.
Referenced by Slic3r::GUI::GLGizmoSimplify::apply_simplify(), and split().
invalidate_cut_info()
void Slic3r::ModelVolume::invalidate_cut_info () inline
{ cut_info.invalidate(); }
References cut_info, and Slic3r::ModelVolume::CutInfo::invalidate().
is_cut_connector()
bool Slic3r::ModelVolume::is_cut_connector () const inline
{ return cut_info.is_processed && cut_info.is_connector; }
References cut_info, Slic3r::ModelVolume::CutInfo::is_connector, and Slic3r::ModelVolume::CutInfo::is_processed.
is_fdm_support_painted()
bool Slic3r::ModelVolume::is_fdm_support_painted () const inline
{ return !this->supported_facets.empty(); }
References Slic3r::FacetsAnnotation::empty().
is_left_handed()
bool Slic3r::ModelVolume::is_left_handed () const inline
{ return m_transformation.is_left_handed(); }
References Slic3r::Geometry::Transformation::is_left_handed(), and m_transformation.
is_mm_painted()
bool Slic3r::ModelVolume::is_mm_painted () const inline
{ return !this->mmu_segmentation_facets.empty(); }
References Slic3r::FacetsAnnotation::empty().
is_model_part()
bool Slic3r::ModelVolume::is_model_part () const inline
{ return m_type == ModelVolumeType::MODEL_PART; }
References m_type, and Slic3r::MODEL_PART.
Referenced by Slic3r::configBrimWidthByVolumes(), Slic3r::find_modifier_volume_extents(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GLCanvas3D::reload_scene(), Slic3r::slices_to_regions(), Slic3r::GUI::GLGizmoText::update_text_positions(), and Slic3r::verify_update_print_object_regions().
is_modifier()
bool Slic3r::ModelVolume::is_modifier () const inline
{ return m_type == ModelVolumeType::PARAMETER_MODIFIER; }
References m_type, and Slic3r::PARAMETER_MODIFIER.
Referenced by Slic3r::color_from_model_volume(), Slic3r::slices_to_regions(), and Slic3r::verify_update_print_object_regions().
is_negative_volume()
bool Slic3r::ModelVolume::is_negative_volume () const inline
{ return m_type == ModelVolumeType::NEGATIVE_VOLUME; }
References m_type, and Slic3r::NEGATIVE_VOLUME.
Referenced by Slic3r::color_from_model_volume(), and Slic3r::slices_to_regions().
is_seam_painted()
bool Slic3r::ModelVolume::is_seam_painted () const inline
{ return !this->seam_facets.empty(); }
References Slic3r::FacetsAnnotation::empty().
is_splittable()
bool Slic3r::ModelVolume::is_splittable () const
{
    // the call mesh.is_splittable() is expensive, so cache the value to calculate it only once
    if (m_is_splittable == -1)
        m_is_splittable = its_is_splittable(this->mesh().its);
    return m_is_splittable == 1;
}
References Slic3r::its_is_splittable(), m_is_splittable, and mesh().
is_support_blocker()
bool Slic3r::ModelVolume::is_support_blocker () const inline
{ return m_type == ModelVolumeType::SUPPORT_BLOCKER; }
References m_type, and Slic3r::SUPPORT_BLOCKER.
Referenced by Slic3r::color_from_model_volume().
is_support_enforcer()
bool Slic3r::ModelVolume::is_support_enforcer () const inline
{ return m_type == ModelVolumeType::SUPPORT_ENFORCER; }
References m_type, and Slic3r::SUPPORT_ENFORCER.
Referenced by Slic3r::color_from_model_volume().
is_support_modifier()
bool Slic3r::ModelVolume::is_support_modifier () const inline
{ return m_type == ModelVolumeType::SUPPORT_BLOCKER || m_type == ModelVolumeType::SUPPORT_ENFORCER; }
References m_type, Slic3r::SUPPORT_BLOCKER, and Slic3r::SUPPORT_ENFORCER.
load()
template<class Archive > void Slic3r::ModelVolume::load (Archive & ar) inline private
{
    bool has_convex_hull;
        // BBS: add backup, check modify
        bool mesh_changed = false;
        auto tr = m_transformation;
        ar(name, source, m_mesh, m_type, m_material_id, m_transformation, m_is_splittable, has_convex_hull, m_text_info, cut_info);
        mesh_changed |= !(tr == m_transformation);
        if (mesh_changed) m_transformation.get_matrix(true, true, true, true); // force dirty
        auto t = supported_facets.timestamp();
        cereal::load_by_value(ar, supported_facets);
        mesh_changed |= t != supported_facets.timestamp();
        t = seam_facets.timestamp();
        cereal::load_by_value(ar, seam_facets);
        mesh_changed |= t != seam_facets.timestamp();
        t = mmu_segmentation_facets.timestamp();
        cereal::load_by_value(ar, mmu_segmentation_facets);
        mesh_changed |= t != mmu_segmentation_facets.timestamp();
        cereal::load_by_value(ar, config);
    assert(m_mesh);
    if (has_convex_hull) {
      cereal::load_optional(ar, m_convex_hull);
      if (! m_convex_hull && ! m_mesh->empty())
        // The convex hull was released from the Undo / Redo stack to conserve memory. Recalculate it.
        this->calculate_convex_hull();
    } else
      m_convex_hull.reset();
        if (mesh_changed && object)
            Slic3r::save_object_mesh(*object);
  }
References calculate_convex_hull(), config, cut_info, Slic3r::Geometry::Transformation::get_matrix(), cereal::load_by_value(), cereal::load_optional(), m_convex_hull, m_is_splittable, m_material_id, m_mesh, m_text_info, m_transformation, m_type, mmu_segmentation_facets, name, Slic3r::save_object_mesh(), seam_facets, source, supported_facets, and Slic3r::ObjectWithTimestamp::timestamp().
load_and_construct()
template<class Archive > static void Slic3r::ObjectBase::load_and_construct (Archive & ar, cereal::construct< ObjectBase > & construct) inline static private inherited
{ ObjectID id; ar(id); construct(id); }
References Slic3r::ObjectBase::id().
material()
ModelMaterial * Slic3r::ModelVolume::material () const
{
    return this->object->get_model()->get_material(m_material_id);
}
References Slic3r::Model::get_material(), Slic3r::ModelMaterial::get_model(), and m_material_id.
Referenced by set_material().
material_id()
t_model_material_id Slic3r::ModelVolume::material_id () const inline
{ return m_material_id; }
References m_material_id.
Referenced by ModelVolume(), ModelVolume(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), set_material(), and set_material_id().
mesh()
const TriangleMesh & Slic3r::ModelVolume::mesh () const inline
{ return *m_mesh.get(); }
References m_mesh.
Referenced by ModelVolume(), ModelVolume(), calculate_convex_hull(), center_geometry_after_creation(), Slic3r::configBrimWidthByVolumes(), Slic3r::FacetsAnnotation::get_facets(), Slic3r::FacetsAnnotation::get_facets(), Slic3r::FacetsAnnotation::get_facets_strict(), get_repaired_errors_count(), is_splittable(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::GUI::GLGizmoSimplify::process(), Slic3r::FacetsAnnotation::set_enforcer_block_type_limit(), set_mesh(), set_mesh(), set_mesh(), set_mesh(), set_mesh(), set_mesh(), Slic3r::GUI::Plater::show_object_info(), split(), transform_this_mesh(), transform_this_mesh(), and Slic3r::GUI::GLGizmoText::update_text_positions().
mesh_ptr()
const TriangleMesh * Slic3r::ModelVolume::mesh_ptr () const inline
{ return m_mesh.get(); }
References m_mesh.
Referenced by Slic3r::Print::process().
mirror()
void Slic3r::ModelVolume::mirror (Axis axis)
{
    Vec3d mirror = get_mirror();
    switch (axis)
    {
    case X: { mirror(0) *= -1.0; break; }
    case Y: { mirror(1) *= -1.0; break; }
    case Z: { mirror(2) *= -1.0; break; }
    default: break;
    }
    set_mirror(mirror);
}
References get_mirror(), mirror(), set_mirror(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by calculate_convex_hull_2d(), mirror(), set_mirror(), and set_mirror().
operator=()
ModelVolume & Slic3r::ModelVolume::operator= (ModelVolume & rhs) private delete
reset_mesh()
void Slic3r::ModelVolume::reset_mesh () inline
{ m_mesh = std::make_shared<const TriangleMesh>(); }
References m_mesh.
rotate() [1/2]
void Slic3r::ModelVolume::rotate (double angle, Axis axis)
{
    switch (axis)
    {
    case X: { rotate(angle, Vec3d::UnitX()); break; }
    case Y: { rotate(angle, Vec3d::UnitY()); break; }
    case Z: { rotate(angle, Vec3d::UnitZ()); break; }
    default: break;
    }
}
References Slic3r::angle(), rotate(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by rotate().
rotate() [2/2]
void Slic3r::ModelVolume::rotate (double angle, const Vec3d & axis)
{
    set_rotation(get_rotation() + Geometry::extract_euler_angles(Eigen::Quaterniond(Eigen::AngleAxisd(angle, axis)).toRotationMatrix()));
}
References Slic3r::angle(), Slic3r::Geometry::extract_euler_angles(), get_rotation(), and set_rotation().
save()
template<class Archive > void Slic3r::ModelVolume::save (Archive & ar) const inline private
{
    bool has_convex_hull = m_convex_hull.get() != nullptr;
        ar(name, source, m_mesh, m_type, m_material_id, m_transformation, m_is_splittable, has_convex_hull, m_text_info, cut_info);
        cereal::save_by_value(ar, supported_facets);
        cereal::save_by_value(ar, seam_facets);
        cereal::save_by_value(ar, mmu_segmentation_facets);
        cereal::save_by_value(ar, config);
    if (has_convex_hull)
      cereal::save_optional(ar, m_convex_hull);
  }
References config, cut_info, m_convex_hull, m_is_splittable, m_material_id, m_mesh, m_text_info, m_transformation, m_type, mmu_segmentation_facets, name, cereal::save_by_value(), cereal::save_optional(), seam_facets, source, and supported_facets.
scale() [1/3]
void Slic3r::ModelVolume::scale (const Vec3d & scaling_factors)
{
    set_scaling_factor(get_scaling_factor().cwiseProduct(scaling_factors));
}
References get_scaling_factor(), and set_scaling_factor().
Referenced by calculate_convex_hull_2d(), scale_geometry_after_creation(), and scale_geometry_after_creation().
scale() [2/3]
void Slic3r::ModelVolume::scale (double s) inline
{ scale(Vec3d(s, s, s)); }
References scale().
Referenced by scale().
scale() [3/3]
void Slic3r::ModelVolume::scale (double x, double y, double z) inline
{ scale(Vec3d(x, y, z)); }
References scale().
Referenced by scale().
scale_geometry_after_creation() [1/2]
void Slic3r::ModelVolume::scale_geometry_after_creation (const float scale) inline
{ this->scale_geometry_after_creation(Vec3f(scale, scale, scale)); }
References scale(), and scale_geometry_after_creation().
Referenced by scale_geometry_after_creation().
scale_geometry_after_creation() [2/2]
void Slic3r::ModelVolume::scale_geometry_after_creation (const Vec3f & versor)
{
  const_cast<TriangleMesh*>(m_mesh.get())->scale(versor);
    if (m_convex_hull->empty())
        //BBS: recompute the convex hull if it is null for previous too small
        this->calculate_convex_hull();
    else
        const_cast<TriangleMesh*>(m_convex_hull.get())->scale(versor);
}
References calculate_convex_hull(), m_convex_hull, m_mesh, and scale().
Referenced by convert_from_imperial_units(), convert_from_meters(), and Slic3r::ModelObject::convert_units().
serialize()
template<class Archive > void Slic3r::ObjectBase::serialize (Archive & ar) inline private inherited
{ ar(m_id); }
References Slic3r::ObjectBase::m_id.
set_invalid_id()
void Slic3r::ObjectBase::set_invalid_id () inline protected inherited
{ m_id = 0; }
References Slic3r::ObjectBase::m_id.
Referenced by Slic3r::CutObjectBase::invalidate().
set_material()
void Slic3r::ModelVolume::set_material (t_model_material_id material_id, const ModelMaterial & material)
{
    m_material_id = material_id;
    if (! material_id.empty())
        this->object->get_model()->add_material(material_id, material);
}
References m_material_id, material(), and material_id().
Referenced by Slic3r::ModelObject::convert_units(), and Slic3r::ModelObject::segment().
set_material_id()
void Slic3r::ModelVolume::set_material_id (t_model_material_id material_id)
{
    m_material_id = material_id;
    // ensure m_material_id references an existing material
    if (! material_id.empty())
        this->object->get_model()->add_material(material_id);
}
References m_material_id, and material_id().
Referenced by ModelVolume(), ModelVolume(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
set_mesh() [1/6]
void Slic3r::ModelVolume::set_mesh (const indexed_triangle_set & mesh) inline
{ m_mesh = std::make_shared<const TriangleMesh>(mesh); }
References m_mesh, and mesh().
set_mesh() [2/6]
void Slic3r::ModelVolume::set_mesh (const TriangleMesh & mesh) inline
{ m_mesh = std::make_shared<const TriangleMesh>(mesh); }
References m_mesh, and mesh().
Referenced by Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::AMFParserContext::endElement(), split(), transform_this_mesh(), and transform_this_mesh().
set_mesh() [3/6]
void Slic3r::ModelVolume::set_mesh (indexed_triangle_set && mesh) inline
{ m_mesh = std::make_shared<const TriangleMesh>(std::move(mesh)); }
References m_mesh, and mesh().
set_mesh() [4/6]
void Slic3r::ModelVolume::set_mesh (std::shared_ptr< const TriangleMesh > & mesh) inline
{ m_mesh = mesh; }
References m_mesh, and mesh().
set_mesh() [5/6]
void Slic3r::ModelVolume::set_mesh (std::unique_ptr< const TriangleMesh > && mesh) inline
{ m_mesh = std::move(mesh); }
References m_mesh, and mesh().
set_mesh() [6/6]
void Slic3r::ModelVolume::set_mesh (TriangleMesh && mesh) inline
{ m_mesh = std::make_shared<const TriangleMesh>(std::move(mesh)); }
References m_mesh, and mesh().
set_mirror() [1/2]
void Slic3r::ModelVolume::set_mirror (Axis axis, double mirror) inline
{ m_transformation.set_mirror(axis, mirror); }
References m_transformation, mirror(), and Slic3r::Geometry::Transformation::set_mirror().
set_mirror() [2/2]
void Slic3r::ModelVolume::set_mirror (const Vec3d & mirror) inline
{ m_transformation.set_mirror(mirror); }
References m_transformation, mirror(), and Slic3r::Geometry::Transformation::set_mirror().
Referenced by mirror().
set_model_object()
void Slic3r::ModelVolume::set_model_object (ModelObject * model_object) inline protected
{ object = model_object; }
set_new_unique_id()
void Slic3r::ModelVolume::set_new_unique_id () inline
{
        ObjectBase::set_new_unique_id();
        this->config.set_new_unique_id();
        this->supported_facets.set_new_unique_id();
        this->seam_facets.set_new_unique_id();
        this->mmu_segmentation_facets.set_new_unique_id();
    }
References Slic3r::ObjectBase::set_new_unique_id().
Referenced by Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::Selection::copy_to_clipboard(), Slic3r::ModelObject::delete_volume(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::Selection::paste_volumes_from_clipboard(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), split(), transform_this_mesh(), and transform_this_mesh().
set_offset() [1/2]
void Slic3r::ModelVolume::set_offset (Axis axis, double offset) inline
{ m_transformation.set_offset(axis, offset); }
References m_transformation, Slic3r::offset(), and Slic3r::Geometry::Transformation::set_offset().
set_offset() [2/2]
void Slic3r::ModelVolume::set_offset (const Vec3d & offset) inline
{ m_transformation.set_offset(offset); }
References m_transformation, Slic3r::offset(), and Slic3r::Geometry::Transformation::set_offset().
Referenced by convert_from_imperial_units(), convert_from_meters(), Slic3r::ModelObject::convert_units(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::ModelObject::process_connector_cut(), Slic3r::ModelObject::split(), and translate().
set_rotation() [1/2]
void Slic3r::ModelVolume::set_rotation (Axis axis, double rotation) inline
{ m_transformation.set_rotation(axis, rotation); }
References m_transformation, and Slic3r::Geometry::Transformation::set_rotation().
set_rotation() [2/2]
void Slic3r::ModelVolume::set_rotation (const Vec3d & rotation) inline
{ m_transformation.set_rotation(rotation); }
References m_transformation, and Slic3r::Geometry::Transformation::set_rotation().
Referenced by Slic3r::ModelObject::process_connector_cut(), and rotate().
set_scaling_factor() [1/2]
void Slic3r::ModelVolume::set_scaling_factor (Axis axis, double scaling_factor) inline
{ m_transformation.set_scaling_factor(axis, scaling_factor); }
References m_transformation, and Slic3r::Geometry::Transformation::set_scaling_factor().
set_scaling_factor() [2/2]
void Slic3r::ModelVolume::set_scaling_factor (const Vec3d & scaling_factor) inline
{ m_transformation.set_scaling_factor(scaling_factor); }
References m_transformation, and Slic3r::Geometry::Transformation::set_scaling_factor().
Referenced by apply_tolerance(), and scale().
set_text_info()
void Slic3r::ModelVolume::set_text_info (const TextInfo & text_info) inline
{ m_text_info = text_info; }
References m_text_info.
Referenced by Slic3r::GUI::GLGizmoText::generate_text_volume(), and Slic3r::GUI::ObjectList::load_mesh_part().
set_transformation() [1/2]
void Slic3r::ModelVolume::set_transformation (const Geometry::Transformation & transformation) inline
{ m_transformation = transformation; }
References m_transformation.
Referenced by Slic3r::ModelObject::apply_cut_connectors(), Slic3r::ModelObject::delete_volume(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::merge(), Slic3r::ModelObject::process_connector_cut(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
set_transformation() [2/2]
void Slic3r::ModelVolume::set_transformation (const Transform3d & trafo) inline
{ m_transformation.set_from_transform(trafo); }
References m_transformation, and Slic3r::Geometry::Transformation::set_from_transform().
set_type()
void Slic3r::ModelVolume::set_type (const ModelVolumeType t) inline
{ m_type = t; }
References m_type.
Referenced by Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::add_volume_with_shared_mesh(), Slic3r::ModelObject::convert_units(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::ModelObject::process_connector_cut(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
split()
size_t Slic3r::ModelVolume::split (unsigned int max_extruders)
{
    std::vector<TriangleMesh> meshes = this->mesh().split();
    if (meshes.size() <= 1)
        return 1;
    size_t idx = 0;
    size_t ivolume = std::find(this->object->volumes.begin(), this->object->volumes.end(), this) - this->object->volumes.begin();
    const std::string name = this->name;
    unsigned int extruder_counter = 0;
    const Vec3d offset = this->get_offset();
    for (TriangleMesh &mesh : meshes) {
        if (mesh.empty())
            // Repair may have removed unconnected triangles, thus emptying the mesh.
            continue;
        if (idx == 0) {
            this->set_mesh(std::move(mesh));
            this->calculate_convex_hull();
            this->invalidate_convex_hull_2d();
            // Assign a new unique ID, so that a new GLVolume will be generated.
            this->set_new_unique_id();
            // reset the source to disable reload from disk
            this->source = ModelVolume::Source();
            // BBS: reset facet annotations
            this->mmu_segmentation_facets.reset();
            this->exterior_facets.reset();
            this->supported_facets.reset();
            this->seam_facets.reset();
        }
        else
            this->object->volumes.insert(this->object->volumes.begin() + (++ivolume), new ModelVolume(object, *this, std::move(mesh)));
        this->object->volumes[ivolume]->set_offset(Vec3d::Zero());
        this->object->volumes[ivolume]->center_geometry_after_creation();
        this->object->volumes[ivolume]->translate(offset);
        this->object->volumes[ivolume]->name = name + "_" + std::to_string(idx + 1);
        //BBS: always set the extruder id the same as original
        this->object->volumes[ivolume]->config.set("extruder", this->extruder_id());
        //this->object->volumes[ivolume]->config.set("extruder", auto_extruder_id(max_extruders, extruder_counter));
        this->object->volumes[ivolume]->m_is_splittable = 0;
        ++ idx;
    }
    // discard volumes for which the convex hull was not generated or is degenerate
    size_t i = 0;
    while (i < this->object->volumes.size()) {
        const std::shared_ptr<const TriangleMesh> &hull = this->object->volumes[i]->get_convex_hull_shared_ptr();
        if (hull == nullptr || hull->its.vertices.empty() || hull->its.indices.empty()) {
            this->object->delete_volume(i);
            --idx;
            --i;
        }
        ++i;
    }
    return idx;
}
References calculate_convex_hull(), Slic3r::TriangleMesh::empty(), exterior_facets, extruder_id(), get_offset(), invalidate_convex_hull_2d(), mesh(), mmu_segmentation_facets, name, object, Slic3r::offset(), Slic3r::FacetsAnnotation::reset(), seam_facets, set_mesh(), set_new_unique_id(), source, Slic3r::TriangleMesh::split(), supported_facets, and Slic3r::ModelObject::volumes.
timestamp()
virtual Timestamp Slic3r::ObjectBase::timestamp () const inline virtual inherited
Reimplemented in Slic3r::ModelConfigObject, and Slic3r::ObjectWithTimestamp.
{ return 0; }
transform_this_mesh() [1/2]
void Slic3r::ModelVolume::transform_this_mesh (const Matrix3d & m, bool fix_left_handed) protected
{
  TriangleMesh mesh = this->mesh();
  mesh.transform(matrix, fix_left_handed);
  this->set_mesh(std::move(mesh));
    TriangleMesh convex_hull = this->get_convex_hull();
    convex_hull.transform(matrix, fix_left_handed);
    m_convex_hull = std::make_shared<TriangleMesh>(std::move(convex_hull));
    // Let the rest of the application know that the geometry changed, so the meshes have to be reloaded.
    this->set_new_unique_id();
}
References get_convex_hull(), m_convex_hull, mesh(), set_mesh(), set_new_unique_id(), and Slic3r::TriangleMesh::transform().
transform_this_mesh() [2/2]
void Slic3r::ModelVolume::transform_this_mesh (const Transform3d & t, bool fix_left_handed) protected
{
  TriangleMesh mesh = this->mesh();
  mesh.transform(mesh_trafo, fix_left_handed);
  this->set_mesh(std::move(mesh));
    TriangleMesh convex_hull = this->get_convex_hull();
    convex_hull.transform(mesh_trafo, fix_left_handed);
    m_convex_hull = std::make_shared<TriangleMesh>(std::move(convex_hull));
    // Let the rest of the application know that the geometry changed, so the meshes have to be reloaded.
    this->set_new_unique_id();
}
References get_convex_hull(), m_convex_hull, mesh(), set_mesh(), set_new_unique_id(), and Slic3r::TriangleMesh::transform().
translate() [1/2]
void Slic3r::ModelVolume::translate (const Vec3d & displacement)
{
    set_offset(get_offset() + displacement);
}
References get_offset(), and set_offset().
translate() [2/2]
void Slic3r::ModelVolume::translate (double x, double y, double z) inline
{ translate(Vec3d(x, y, z)); }
References translate().
Referenced by center_geometry_after_creation(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), and translate().
type()
ModelVolumeType Slic3r::ModelVolume::type () const inline
{ return m_type; }
References m_type.
Referenced by Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::add_volume_with_shared_mesh(), Slic3r::AMFParserContext::endElement(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::model_property_changed(), Slic3r::model_volume_list_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::model_volume_needs_slicing(), Slic3r::model_volume_solid_or_modifier(), Slic3r::Print::process(), and Slic3r::GUI::Plater::priv::replace_volume_with_stl().
type_from_string()
ModelVolumeType Slic3r::ModelVolume::type_from_string (const std::string & s) static
{
    // New type (supporting the support enforcers & blockers)
    if (s == "normal_part")
    return ModelVolumeType::MODEL_PART;
    if (s == "negative_part")
        return ModelVolumeType::NEGATIVE_VOLUME;
    if (s == "modifier_part")
    return ModelVolumeType::PARAMETER_MODIFIER;
    if (s == "support_enforcer")
    return ModelVolumeType::SUPPORT_ENFORCER;
    if (s == "support_blocker")
    return ModelVolumeType::SUPPORT_BLOCKER;
    //assert(s == "0");
    // Default value if invalud type string received.
  return ModelVolumeType::MODEL_PART;
}
References Slic3r::MODEL_PART, Slic3r::NEGATIVE_VOLUME, Slic3r::PARAMETER_MODIFIER, Slic3r::SUPPORT_BLOCKER, and Slic3r::SUPPORT_ENFORCER.
type_to_string()
std::string Slic3r::ModelVolume::type_to_string (const ModelVolumeType t) static
{
    switch (t) {
  case ModelVolumeType::MODEL_PART:         return "normal_part";
    case ModelVolumeType::NEGATIVE_VOLUME:    return "negative_part";
  case ModelVolumeType::PARAMETER_MODIFIER: return "modifier_part";
  case ModelVolumeType::SUPPORT_ENFORCER:   return "support_enforcer";
  case ModelVolumeType::SUPPORT_BLOCKER:    return "support_blocker";
    default:
        assert(false);
        return "normal_part";
    }
}
References Slic3r::MODEL_PART, Slic3r::NEGATIVE_VOLUME, Slic3r::PARAMETER_MODIFIER, Slic3r::SUPPORT_BLOCKER, and Slic3r::SUPPORT_ENFORCER.
update_extruder_count()
void Slic3r::ModelVolume::update_extruder_count (size_t extruder_count)
{
    std::vector<int> used_extruders = get_extruders();
    for (int extruder_id : used_extruders) {
        if (extruder_id > extruder_count) {
            mmu_segmentation_facets.set_enforcer_block_type_limit(*this, (EnforcerBlockerType)extruder_count);
            break;
        }
    }
}
References extruder_id(), get_extruders(), mmu_segmentation_facets, and Slic3r::FacetsAnnotation::set_enforcer_block_type_limit().
Referenced by Slic3r::GUI::GLCanvas3D::reload_scene().
Friends And Related Symbol Documentation
cereal::access
friend class cereal::access friend
Model
friend class Model friend
model_volume_list_update_supports
void model_volume_list_update_supports (ModelObject & model_object_dst, const ModelObject & model_object_new) friend
{
    typedef std::pair<const ModelVolume*, bool> ModelVolumeWithStatus;
    std::vector<ModelVolumeWithStatus> old_volumes;
    old_volumes.reserve(model_object_dst.volumes.size());
    for (const ModelVolume *model_volume : model_object_dst.volumes)
        old_volumes.emplace_back(ModelVolumeWithStatus(model_volume, false));
    auto model_volume_lower = [](const ModelVolumeWithStatus &mv1, const ModelVolumeWithStatus &mv2){ return mv1.first->id() <  mv2.first->id(); };
    auto model_volume_equal = [](const ModelVolumeWithStatus &mv1, const ModelVolumeWithStatus &mv2){ return mv1.first->id() == mv2.first->id(); };
    std::sort(old_volumes.begin(), old_volumes.end(), model_volume_lower);
    model_object_dst.volumes.clear();
    model_object_dst.volumes.reserve(model_object_new.volumes.size());
    for (const ModelVolume *model_volume_src : model_object_new.volumes) {
        ModelVolumeWithStatus key(model_volume_src, false);
        auto it = std::lower_bound(old_volumes.begin(), old_volumes.end(), key, model_volume_lower);
        if (it != old_volumes.end() && model_volume_equal(*it, key)) {
            // The volume was found in the old list. Just copy it.
            assert(! it->second); // not consumed yet
            it->second = true;
            ModelVolume *model_volume_dst = const_cast<ModelVolume*>(it->first);
            // For support modifiers, the type may have been switched from blocker to enforcer and vice versa.
            assert((model_volume_dst->is_support_modifier() && model_volume_src->is_support_modifier()) || model_volume_dst->type() == model_volume_src->type());
            model_object_dst.volumes.emplace_back(model_volume_dst);
            if (model_volume_dst->is_support_modifier()) {
                // For support modifiers, the type may have been switched from blocker to enforcer and vice versa.
                model_volume_dst->set_type(model_volume_src->type());
                model_volume_dst->set_transformation(model_volume_src->get_transformation());
            }
            assert(model_volume_dst->get_matrix().isApprox(model_volume_src->get_matrix()));
        } else {
            // The volume was not found in the old list. Create a new copy.
            assert(model_volume_src->is_support_modifier());
            model_object_dst.volumes.emplace_back(new ModelVolume(*model_volume_src));
            model_object_dst.volumes.back()->set_model_object(&model_object_dst);
        }
    }
    // Release the non-consumed old volumes (those were deleted from the new list).
    for (ModelVolumeWithStatus &mv_with_status : old_volumes)
        if (! mv_with_status.second)
            delete mv_with_status.first;
}
ModelObject
friend class ModelObject friend
Print
friend class Print friend
SLAPrint
friend class SLAPrint friend
UndoRedo::StackImpl
friend class UndoRedo::StackImpl friend
Member Data Documentation
config
ModelConfigObject Slic3r::ModelVolume::config
Referenced by ModelVolume(), ModelVolume(), assign_new_unique_ids_recursive(), Slic3r::ModelObject::convert_units(), extruder_id(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), load(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GUI::ObjectList::merge(), Slic3r::ModelObject::merge_volumes(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::ObjectList::object_config_options_changed(), Slic3r::Print::process(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::CLI::run(), save(), Slic3r::ModelObject::segment(), and Slic3r::ModelObject::split().
cut_info
CutInfo Slic3r::ModelVolume::cut_info
Referenced by Slic3r::ModelObject::add_volume(), Slic3r::ModelObject::apply_cut_connectors(), apply_tolerance(), invalidate_cut_info(), is_cut_connector(), load(), and save().
exterior_facets
FacetsAnnotation Slic3r::ModelVolume::exterior_facets
Referenced by split().
m_cached_2d_polygon
Polygon Slic3r::ModelVolume::m_cached_2d_polygon mutable private
Referenced by calculate_convex_hull_2d(), and get_convex_hull_2d().
m_cached_trans_matrix
Transform3d Slic3r::ModelVolume::m_cached_trans_matrix mutable private
Referenced by get_convex_hull_2d().
m_convex_hull
std::shared_ptr<const TriangleMesh> Slic3r::ModelVolume::m_convex_hull private
Referenced by calculate_convex_hull(), calculate_convex_hull_2d(), center_geometry_after_creation(), get_convex_hull(), get_convex_hull_shared_ptr(), load(), save(), scale_geometry_after_creation(), transform_this_mesh(), and transform_this_mesh().
m_convex_hull_2d
Polygon Slic3r::ModelVolume::m_convex_hull_2d mutable private
Referenced by calculate_convex_hull_2d(), get_convex_hull_2d(), and invalidate_convex_hull_2d().
m_id
ObjectID Slic3r::ObjectBase::m_id private inherited
Referenced by Slic3r::ObjectBase::copy_id(), Slic3r::ObjectBase::id(), Slic3r::ObjectBase::serialize(), Slic3r::ObjectBase::set_invalid_id(), and Slic3r::ObjectBase::set_new_unique_id().
m_is_splittable
int Slic3r::ModelVolume::m_is_splittable { -1 } mutable private
Referenced by is_splittable(), load(), and save().
m_material_id
t_model_material_id Slic3r::ModelVolume::m_material_id private
Referenced by load(), material(), material_id(), save(), set_material(), and set_material_id().
m_mesh
std::shared_ptr<const TriangleMesh> Slic3r::ModelVolume::m_mesh private
Referenced by Slic3r::ModelObject::add_volume_with_shared_mesh(), center_geometry_after_creation(), load(), mesh(), mesh_ptr(), reset_mesh(), save(), scale_geometry_after_creation(), set_mesh(), set_mesh(), set_mesh(), set_mesh(), set_mesh(), and set_mesh().
m_text_info
TextInfo Slic3r::ModelVolume::m_text_info private
Referenced by get_text_info(), load(), save(), and set_text_info().
m_transformation
Geometry::Transformation Slic3r::ModelVolume::m_transformation private
Referenced by get_convex_hull_2d(), get_matrix(), get_mirror(), get_mirror(), get_offset(), get_offset(), get_rotation(), get_rotation(), get_scaling_factor(), get_scaling_factor(), get_transformation(), is_left_handed(), load(), save(), set_mirror(), set_mirror(), set_offset(), set_offset(), set_rotation(), set_rotation(), set_scaling_factor(), set_scaling_factor(), set_transformation(), and set_transformation().
m_type
ModelVolumeType Slic3r::ModelVolume::m_type private
Referenced by get_extruders(), is_model_part(), is_modifier(), is_negative_volume(), is_support_blocker(), is_support_enforcer(), is_support_modifier(), load(), save(), set_type(), and type().
mmu_segmentation_facets
FacetsAnnotation Slic3r::ModelVolume::mmu_segmentation_facets
Referenced by ModelVolume(), ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_file_to_archive(), assign_new_unique_ids_recursive(), Slic3r::ModelObject::convert_units(), get_extruders(), load(), Slic3r::GUI::ObjectList::merge(), Slic3r::model_mmu_segmentation_data_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::Print::process(), Slic3r::GLVolume::render(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), save(), Slic3r::GLVolume::simple_render(), Slic3r::ModelObject::split(), split(), and update_extruder_count().
mmuseg_extruders
std::vector<int> Slic3r::ModelVolume::mmuseg_extruders mutable
Referenced by get_extruders().
mmuseg_ts
Timestamp Slic3r::ModelVolume::mmuseg_ts mutable
Referenced by get_extruders().
name
std::string Slic3r::ModelVolume::name
Referenced by Slic3r::Model::add_object(), Slic3r::Model::add_object(), Slic3r::ModelObject::apply_cut_connectors(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::ModelObject::convert_units(), Slic3r::AMFParserContext::endElement(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), load(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_mesh_object(), Slic3r::GUI::ObjectList::load_mesh_part(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::load_svg(), Slic3r::ModelObject::make_boolean(), Slic3r::ModelObject::merge_volumes(), Slic3r::model_volume_list_copy_configs(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), save(), Slic3r::ModelObject::segment(), Slic3r::GUI::Plater::show_object_info(), split(), and Slic3r::GUI::ObjectDataViewModel::UpdateItemNames().
object
ModelObject* Slic3r::ModelVolume::object private
Referenced by get_object(), and split().
s_last_id
size_t Slic3r::ObjectBase::s_last_id = 0 static private inherited
Referenced by Slic3r::ObjectBase::generate_new_id().
seam_facets
FacetsAnnotation Slic3r::ModelVolume::seam_facets
Referenced by ModelVolume(), ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_file_to_archive(), assign_new_unique_ids_recursive(), Slic3r::ModelObject::convert_units(), load(), Slic3r::model_custom_seam_data_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::Print::process(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), save(), and split().
source
Source Slic3r::ModelVolume::source
Referenced by Slic3r::Model::add_object(), Slic3r::Model::add_object(), center_geometry_after_creation(), convert_from_imperial_units(), convert_from_meters(), Slic3r::ModelObject::convert_units(), Slic3r::AMFParserContext::endElement(), load(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::ObjectList::load_modifier(), Slic3r::load_svg(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), save(), Slic3r::ModelObject::split(), and split().
supported_facets
FacetsAnnotation Slic3r::ModelVolume::supported_facets
Referenced by ModelVolume(), ModelVolume(), Slic3r::_BBS_3MF_Exporter::_add_model_file_to_archive(), assign_new_unique_ids_recursive(), Slic3r::ModelObject::convert_units(), load(), Slic3r::model_custom_supports_data_changed(), Slic3r::model_volume_list_copy_configs(), Slic3r::Print::process(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), save(), and split().
The documentation for this class was generated from the following files:
src/libslic3r/Model.hpp
src/libslic3r/Model.cpp