OrcaSlicer: Slic3r::GUI::AmsTutorialPopup Class Reference
Slic3r::GUI::AmsTutorialPopup Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
AmsTutorialPopup (wxWindow *parent)
~AmsTutorialPopup ()
void paintEvent (wxPaintEvent &evt)
virtual void OnDismiss () wxOVERRIDE
virtual bool ProcessLeftDown (wxMouseEvent &event) wxOVERRIDE
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Public Attributes
Label * text_title
wxStaticBitmap * img_top
wxStaticBitmap * arrows_top
wxStaticText * tip_top
wxStaticBitmap * arrows_bottom
wxStaticText * tip_bottom
wxStaticBitmap * img_middle
wxStaticText * tip_middle
wxStaticBitmap * img_botton
Detailed Description
Constructor & Destructor Documentation
AmsTutorialPopup()
Slic3r::GUI::AmsTutorialPopup::AmsTutorialPopup (wxWindow * parent)
:PopupWindow(parent, wxBORDER_NONE)
{
    Bind(wxEVT_PAINT, &AmsTutorialPopup::paintEvent, this);
    SetBackgroundColour(*wxWHITE);
    wxBoxSizer* sizer_main;
    sizer_main = new wxBoxSizer(wxVERTICAL);
    text_title = new Label(this, Label::Head_14, _L("Config which AMS slot should be used for a filament used in the print job"));
    text_title->SetSize(wxSize(FromDIP(350), -1));
    text_title->Wrap(FromDIP(350));
    sizer_main->Add(text_title, 0, wxALIGN_CENTER | wxTOP, 18);
    sizer_main->Add(0, 0, 0, wxTOP, 30);
    wxBoxSizer* sizer_top;
    sizer_top = new wxBoxSizer(wxHORIZONTAL);
    img_top = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("ams_item_examples", this, 30), wxDefaultPosition, wxSize(FromDIP(50), FromDIP(30)), 0);
    sizer_top->Add(img_top, 0, wxALIGN_CENTER, 0);
    sizer_top->Add(0, 0, 0, wxLEFT, 10);
    wxBoxSizer* sizer_top_tips = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer* sizer_tip_top = new wxBoxSizer(wxHORIZONTAL);
    arrows_top = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("ams_arrow", this, 8), wxDefaultPosition, wxSize(FromDIP(24), FromDIP(8)), 0);
    sizer_tip_top->Add(arrows_top, 0, wxALIGN_CENTER, 0);
    tip_top = new wxStaticText(this, wxID_ANY, _L("Filament used in this print job"), wxDefaultPosition, wxDefaultSize, 0);
    tip_top->SetForegroundColour(wxColour("#686868"));
    sizer_tip_top->Add(tip_top, 0, wxALL, 0);
    sizer_top_tips->Add(sizer_tip_top, 0, wxEXPAND, 0);
    sizer_top_tips->Add(0, 0, 0, wxTOP, 6);
    wxBoxSizer* sizer_tip_bottom = new wxBoxSizer(wxHORIZONTAL);
    arrows_bottom = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("ams_arrow", this, 8), wxDefaultPosition, wxSize(FromDIP(24), FromDIP(8)), 0);
    tip_bottom = new wxStaticText(this, wxID_ANY, _L("AMS slot used for this filament"), wxDefaultPosition, wxDefaultSize, 0);
    tip_bottom->SetForegroundColour(wxColour("#686868"));
    sizer_tip_bottom->Add(arrows_bottom, 0, wxALIGN_CENTER, 0);
    sizer_tip_bottom->Add(tip_bottom, 0, wxALL, 0);
    sizer_top_tips->Add(sizer_tip_bottom, 0, wxEXPAND, 0);
    sizer_top->Add(sizer_top_tips, 0, wxALIGN_CENTER, 0);
    wxBoxSizer* sizer_middle = new wxBoxSizer(wxHORIZONTAL);
    img_middle= new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("ams_item_examples", this, 30), wxDefaultPosition, wxSize(FromDIP(50), FromDIP(30)), 0);
    sizer_middle->Add(img_middle, 0, wxALIGN_CENTER, 0);
    tip_middle = new wxStaticText(this, wxID_ANY, _L("Click to select AMS slot manually"), wxDefaultPosition, wxDefaultSize, 0);
    tip_middle->SetForegroundColour(wxColour("#686868"));
    sizer_middle->Add(0, 0, 0,wxLEFT, 15);
    sizer_middle->Add(tip_middle, 0, wxALIGN_CENTER, 0);
    sizer_main->Add(sizer_top, 0, wxLEFT, 40);
    sizer_main->Add(0, 0, 0, wxTOP, 10);
    sizer_main->Add(sizer_middle, 0, wxLEFT, 40);
    sizer_main->Add(0, 0, 0, wxTOP, 10);
    img_botton = new wxStaticBitmap(this, wxID_ANY, create_scaled_bitmap("ams_mapping_examples", this, 87), wxDefaultPosition, wxDefaultSize, 0);
    sizer_main->Add(img_botton, 0, wxLEFT | wxRIGHT, 40);
    sizer_main->Add(0, 0, 0, wxTOP, 12);
    SetSizer(sizer_main);
    Layout();
    Fit();
}
References _L, arrows_bottom, arrows_top, create_scaled_bitmap(), Label::Head_14, img_botton, img_middle, img_top, paintEvent(), text_title, tip_bottom, tip_middle, tip_top, Label::Wrap(), and wxStaticText.
~AmsTutorialPopup()
Slic3r::GUI::AmsTutorialPopup::~AmsTutorialPopup () inline
{};
Member Function Documentation
Create()
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and DropDown::Create().
OnDismiss()
void Slic3r::GUI::AmsTutorialPopup::OnDismiss () virtual
{}
paintEvent()
void Slic3r::GUI::AmsTutorialPopup::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    dc.SetPen(wxColour(0xAC, 0xAC, 0xAC));
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    dc.DrawRoundedRectangle(0, 0, GetSize().x, GetSize().y, 0);
}
Referenced by AmsTutorialPopup().
ProcessLeftDown()
bool Slic3r::GUI::AmsTutorialPopup::ProcessLeftDown (wxMouseEvent & event) virtual
{
    return PopupWindow::ProcessLeftDown(event);
}
Member Data Documentation
arrows_bottom
wxStaticBitmap* Slic3r::GUI::AmsTutorialPopup::arrows_bottom
Referenced by AmsTutorialPopup().
arrows_top
wxStaticBitmap* Slic3r::GUI::AmsTutorialPopup::arrows_top
Referenced by AmsTutorialPopup().
img_botton
wxStaticBitmap* Slic3r::GUI::AmsTutorialPopup::img_botton
Referenced by AmsTutorialPopup().
img_middle
wxStaticBitmap* Slic3r::GUI::AmsTutorialPopup::img_middle
Referenced by AmsTutorialPopup().
img_top
wxStaticBitmap* Slic3r::GUI::AmsTutorialPopup::img_top
Referenced by AmsTutorialPopup().
text_title
Label* Slic3r::GUI::AmsTutorialPopup::text_title
Referenced by AmsTutorialPopup().
tip_bottom
wxStaticText* Slic3r::GUI::AmsTutorialPopup::tip_bottom
Referenced by AmsTutorialPopup().
tip_middle
wxStaticText* Slic3r::GUI::AmsTutorialPopup::tip_middle
Referenced by AmsTutorialPopup().
tip_top
wxStaticText* Slic3r::GUI::AmsTutorialPopup::tip_top
Referenced by AmsTutorialPopup().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp