OrcaSlicer: Slic3r::GUI::GCodeViewer::SequentialView::Marker Class Reference
Slic3r::GUI::GCodeViewer::SequentialView::Marker Class Reference
#include <src/slic3r/GUI/GCodeViewer.hpp>
Public Member Functions
void init (std::string filename)
const BoundingBoxf3 & get_bounding_box () const
void set_world_position (const Vec3f &position)
void set_world_offset (const Vec3f &offset)
bool is_visible () const
void set_visible (bool visible)
void render (int canvas_width, int canvas_height, const EViewType &view_type) const
void on_change_color_mode (bool is_dark)
void update_curr_move (const GCodeProcessorResult::MoveVertex move)
Public Attributes
float m_scale = 1.0f
Private Attributes
GLModel m_model
Vec3f m_world_position
Transform3f m_world_transform
Vec3f m_world_offset
float m_z_offset { 0.5f }
GCodeProcessorResult::MoveVertex m_curr_move
bool m_visible { true }
bool m_is_dark = false
Detailed Description
Member Function Documentation
get_bounding_box()
const BoundingBoxf3 & Slic3r::GUI::GCodeViewer::SequentialView::Marker::get_bounding_box () const inline
{ return m_model.get_bounding_box(); }
References Slic3r::GUI::GLModel::get_bounding_box(), and m_model.
Referenced by Slic3r::GUI::GCodeViewer::load_toolpaths().
init()
void Slic3r::GUI::GCodeViewer::SequentialView::Marker::init (std::string filename)
{
    if (filename.empty()) {
        //m_model.init_from(stilized_arrow(16, 1.5f, 3.0f, 0.8f, 3.0f));
    } else {
        m_model.init_from_file(filename);
    }
    m_model.set_color(-1, {1.0f, 1.0f, 1.0f, 0.5f});
}
Referenced by Slic3r::GUI::GCodeViewer::init().
is_visible()
bool Slic3r::GUI::GCodeViewer::SequentialView::Marker::is_visible () const inline
{ return m_visible; }
References m_visible.
Referenced by Slic3r::GUI::GCodeViewer::get_options_visibility_flags().
on_change_color_mode()
void Slic3r::GUI::GCodeViewer::SequentialView::Marker::on_change_color_mode (bool is_dark) inline
{ m_is_dark = is_dark; }
References m_is_dark.
Referenced by Slic3r::GUI::GCodeViewer::on_change_color_mode().
render()
void Slic3r::GUI::GCodeViewer::SequentialView::Marker::render (int canvas_width, int canvas_height, const EViewType & view_type) const
{
    if (!m_visible)
        return;
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    shader->start_using();
    shader->set_uniform("emission_factor", 0.0f);
    glsafe(::glPushMatrix());
    glsafe(::glMultMatrixf(m_world_transform.data()));
    m_model.render();
    glsafe(::glPopMatrix());
    shader->stop_using();
    glsafe(::glDisable(GL_BLEND));
    static float last_window_width = 0.0f;
    size_t text_line = 0;
    static size_t last_text_line = 0;
    const ImU32 text_name_clr = m_is_dark ? IM_COL32(255, 255, 255, 0.88 * 255) : IM_COL32(38, 46, 48, 255);
    const ImU32 text_value_clr = m_is_dark ? IM_COL32(255, 255, 255, 0.4 * 255) : IM_COL32(144, 144, 144, 255);
    ImGuiWrapper& imgui = *wxGetApp().imgui();
    //BBS: GUI refactor: add canvas size from parameters
    imgui.set_next_window_pos(0.5f * static_cast<float>(canvas_width), static_cast<float>(canvas_height), ImGuiCond_Always, 0.5f, 1.0f);
    imgui.push_toolbar_style(m_scale);
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0, 4.0 * m_scale));
    ImGui::PushStyleVar(ImGuiStyleVar_WindowPadding, ImVec2(20.0 * m_scale, 6.0 * m_scale));
    ImGui::PushStyleColor(ImGuiCol_ButtonHovered, text_name_clr);
    ImGui::PushStyleColor(ImGuiCol_Text, text_value_clr);
    imgui.begin(std::string("ExtruderPosition"), ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoDecoration | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoTitleBar);
    ImGui::AlignTextToFramePadding();
    //BBS: minus the plate offset when show tool position
    PartPlateList& partplate_list = wxGetApp().plater()->get_partplate_list();
    PartPlate* plate = partplate_list.get_curr_plate();
    const Vec3f position = m_world_position + m_world_offset;
    std::string x = ImGui::ColorMarkerStart + std::string("X: ") + ImGui::ColorMarkerEnd;
    std::string y = ImGui::ColorMarkerStart + std::string("Y: ") + ImGui::ColorMarkerEnd;
    std::string z = ImGui::ColorMarkerStart + std::string("Z: ") + ImGui::ColorMarkerEnd;
    std::string height = ImGui::ColorMarkerStart + _u8L("Height: ") + ImGui::ColorMarkerEnd;
    std::string width = ImGui::ColorMarkerStart + _u8L("Width: ") + ImGui::ColorMarkerEnd;
    std::string speed = ImGui::ColorMarkerStart + _u8L("Speed: ") + ImGui::ColorMarkerEnd;
    std::string flow = ImGui::ColorMarkerStart + _u8L("Flow: ") + ImGui::ColorMarkerEnd;
    std::string layer_time = ImGui::ColorMarkerStart + _u8L("Layer Time: ") + ImGui::ColorMarkerEnd;
    std::string fanspeed = ImGui::ColorMarkerStart + _u8L("Fan Speed: ") + ImGui::ColorMarkerEnd;
    std::string temperature = ImGui::ColorMarkerStart + _u8L("Temperature: ") + ImGui::ColorMarkerEnd;
    const float item_size = imgui.calc_text_size("X: 000.000  ").x;
    const float item_spacing = imgui.get_item_spacing().x;
    const float window_padding = ImGui::GetStyle().WindowPadding.x;
    char buf[1024];
    if (view_type == EViewType::Height ||
        view_type == EViewType::Width ||
        view_type == EViewType::Feedrate ||
        view_type == EViewType::VolumetricRate ||
        view_type == EViewType::LayerTime ||
        view_type == EViewType::LayerTimeLog ||
        view_type == EViewType::FanSpeed ||
        view_type == EViewType::Temperature)
    {
        sprintf(buf, "%s%.3f", x.c_str(), position.x() - plate->get_origin().x());
        ImGui::PushItemWidth(item_size);
        imgui.text(buf);
        ImGui::SameLine(window_padding + item_size + item_spacing);
        sprintf(buf, "%s%.3f", y.c_str(), position.y() - plate->get_origin().y());
        ImGui::PushItemWidth(item_size);
        imgui.text(buf);
        sprintf(buf, "%s%.3f", z.c_str(), position.z());
        ImGui::PushItemWidth(item_size);
        imgui.text(buf);
        switch (view_type) {
        case EViewType::Height: {
            ImGui::SameLine(window_padding + item_size + item_spacing);
            sprintf(buf, "%s%.2f", height.c_str(), m_curr_move.height);
            ImGui::PushItemWidth(item_size);
            imgui.text(buf);
            break;
        }
        case EViewType::Width: {
            ImGui::SameLine(window_padding + item_size + item_spacing);
            sprintf(buf, "%s%.2f", width.c_str(), m_curr_move.width);
            ImGui::PushItemWidth(item_size);
            imgui.text(buf);
            break;
        }
        case EViewType::Feedrate: {
            ImGui::SameLine(window_padding + item_size + item_spacing);
            sprintf(buf, "%s%.0f", speed.c_str(), m_curr_move.feedrate);
            ImGui::PushItemWidth(item_size);
            imgui.text(buf);
            break;
        }
        case EViewType::VolumetricRate: {
            ImGui::SameLine(window_padding + item_size + item_spacing);
            sprintf(buf, "%s%.2f", flow.c_str(), m_curr_move.volumetric_rate());
            ImGui::PushItemWidth(item_size);
            imgui.text(buf);
            break;
        }
        case EViewType::FanSpeed: {
            ImGui::SameLine(window_padding + item_size + item_spacing);
            sprintf(buf, "%s%.0f", fanspeed.c_str(), m_curr_move.fan_speed);
            ImGui::PushItemWidth(item_size);
            imgui.text(buf);
            break;
        }
        case EViewType::Temperature: {
            ImGui::SameLine(window_padding + item_size + item_spacing);
            sprintf(buf, "%s%.0f", temperature.c_str(), m_curr_move.temperature);
            ImGui::PushItemWidth(item_size);
            imgui.text(buf);
            break;
        }
        case EViewType::LayerTime:
        case EViewType::LayerTimeLog: {
            ImGui::SameLine(window_padding + item_size + item_spacing);
            sprintf(buf, "%s%.1f", layer_time.c_str(), m_curr_move.layer_duration);
            ImGui::PushItemWidth(item_size);
            imgui.text(buf);
            break;
        }
        default:
            break;
        }
        text_line = 2;
    }
    else {
        sprintf(buf, "%s%.3f", x.c_str(), position.x() - plate->get_origin().x());
        ImGui::PushItemWidth(item_size);
        imgui.text(buf);
        ImGui::SameLine(window_padding + item_size + item_spacing);
        sprintf(buf, "%s%.3f", y.c_str(), position.y() - plate->get_origin().y());
        ImGui::PushItemWidth(item_size);
        imgui.text(buf);
        sprintf(buf, "%s%.3f", z.c_str(), position.z());
        ImGui::PushItemWidth(item_size);
        imgui.text(buf);
        ImGui::SameLine(window_padding + item_size + item_spacing);
        sprintf(buf, "%s%.0f", speed.c_str(), m_curr_move.feedrate);
        ImGui::PushItemWidth(item_size);
        imgui.text(buf);
        text_line = 1;
    }
    // force extra frame to automatically update window size
    float window_width = ImGui::GetWindowWidth();
    if (window_width != last_window_width || text_line != last_text_line) {
        last_window_width = window_width;
        last_text_line = text_line;
#if ENABLE_ENHANCED_IMGUI_SLIDER_FLOAT
        imgui.set_requires_extra_frame();
#else
        wxGetApp().plater()->get_current_canvas3D()->set_as_dirty();
        wxGetApp().plater()->get_current_canvas3D()->request_extra_frame();
#endif // ENABLE_ENHANCED_IMGUI_SLIDER_FLOAT
    }
    imgui.end();
    ImGui::PopStyleVar(2);
    ImGui::PopStyleColor(2);
    imgui.pop_toolbar_style();
}
References _u8L, ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), ImGui::ColorMarkerEnd, ImGui::ColorMarkerStart, Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GCodeViewer::FanSpeed, Slic3r::GUI::GCodeViewer::Feedrate, Slic3r::GUI::PartPlateList::get_curr_plate(), Slic3r::GUI::ImGuiWrapper::get_item_spacing(), Slic3r::GUI::PartPlate::get_origin(), ImGui::GetStyle(), ImGui::GetWindowWidth(), glsafe, Slic3r::GUI::GCodeViewer::Height, IM_COL32, ImGuiCol_ButtonHovered, ImGuiCol_Text, ImGuiCond_Always, ImGuiStyleVar_ItemSpacing, ImGuiStyleVar_WindowPadding, ImGuiWindowFlags_NoDecoration, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoTitleBar, Slic3r::GUI::GCodeViewer::LayerTime, Slic3r::GUI::GCodeViewer::LayerTimeLog, Slic3r::GUI::GCodeViewer::m_is_dark, Slic3r::GUI::GCodeViewer::m_scale, Slic3r::GUI::ImGuiWrapper::pop_toolbar_style(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), Slic3r::GUI::ImGuiWrapper::push_toolbar_style(), ImGui::PushItemWidth(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GLShaderProgram::set_uniform(), Slic3r::GLShaderProgram::start_using(), Slic3r::GLShaderProgram::stop_using(), Slic3r::GUI::GCodeViewer::Temperature, Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::GCodeViewer::VolumetricRate, Slic3r::GUI::GCodeViewer::Width, ImGuiStyle::WindowPadding, and ImVec2::x.
set_visible()
void Slic3r::GUI::GCodeViewer::SequentialView::Marker::set_visible (bool visible) inline
{ m_visible = visible; }
References m_visible.
Referenced by Slic3r::GUI::GCodeViewer::set_options_visibility_from_flags().
set_world_offset()
void Slic3r::GUI::GCodeViewer::SequentialView::Marker::set_world_offset (const Vec3f & offset) inline
{ m_world_offset = offset; }
References m_world_offset, and Slic3r::offset().
Referenced by Slic3r::GUI::GCodeViewer::render().
set_world_position()
void Slic3r::GUI::GCodeViewer::SequentialView::Marker::set_world_position (const Vec3f & position)
{
    m_world_position = position;
    m_world_transform = (Geometry::assemble_transform((position + m_z_offset * Vec3f::UnitZ()).cast<double>()) * Geometry::assemble_transform(m_model.get_bounding_box().size().z() * Vec3d::UnitZ(), { M_PI, 0.0, 0.0 })).cast<float>();
}
References Slic3r::Geometry::assemble_transform().
Referenced by Slic3r::GUI::GCodeViewer::render().
update_curr_move()
void Slic3r::GUI::GCodeViewer::SequentialView::Marker::update_curr_move (const GCodeProcessorResult::MoveVertex move)
{
    m_curr_move = move;
}
Referenced by Slic3r::GUI::GCodeViewer::update_marker_curr_move().
Member Data Documentation
m_curr_move
GCodeProcessorResult::MoveVertex Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_curr_move private
m_is_dark
bool Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_is_dark = false private
Referenced by on_change_color_mode().
m_model
GLModel Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_model private
Referenced by get_bounding_box().
m_scale
float Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_scale = 1.0f
Referenced by Slic3r::GUI::GCodeViewer::set_scale().
m_visible
bool Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_visible { true } private
Referenced by is_visible(), and set_visible().
m_world_offset
Vec3f Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_world_offset private
Referenced by set_world_offset().
m_world_position
Vec3f Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_world_position private
m_world_transform
Transform3f Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_world_transform private
m_z_offset
float Slic3r::GUI::GCodeViewer::SequentialView::Marker::m_z_offset { 0.5f } private
The documentation for this class was generated from the following files:
src/slic3r/GUI/GCodeViewer.hpp
src/slic3r/GUI/GCodeViewer.cpp