OrcaSlicer: Slic3r::GUI::AMSSetting Class Reference
Slic3r::GUI::AMSSetting Class Reference
#include <src/slic3r/GUI/AMSSetting.hpp>
Public Member Functions
AMSSetting (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE)
~AMSSetting ()
void create ()
void update_insert_material_read_mode (bool selected)
void update_starting_read_mode (bool selected)
void update_remain_mode (bool selected)
void update_switch_filament (bool selected)
void on_select_ok (wxMouseEvent &event)
void on_insert_material_read (wxCommandEvent &event)
void on_starting_read (wxCommandEvent &event)
void on_remain (wxCommandEvent &event)
void on_switch_filament (wxCommandEvent &event)
wxString append_title (wxString text)
wxStaticText * append_text (wxString text)
float scale_factor () const
float prev_scale_factor () const
int em_unit () const
const wxFont & normal_font () const
void enable_force_rescale ()
int ShowModal ()
Public Attributes
MachineObject * obj {nullptr}
bool ams_support_remain {false}
int ams_id { 0 }
Protected Member Functions
void on_dpi_changed (const wxRect &suggested_rect) override
virtual void on_sys_color_changed ()
Protected Attributes
wxPanel * m_panel_body
CheckBox * m_checkbox_Insert_material_auto_read
wxStaticText * m_title_Insert_material_auto_read
Label * m_tip_Insert_material_line1
Label * m_tip_Insert_material_line2
Label * m_tip_Insert_material_line3
CheckBox * m_checkbox_starting_auto_read
wxStaticText * m_title_starting_auto_read
Label * m_tip_starting_line1
Label * m_tip_starting_line2
CheckBox * m_checkbox_remain
wxStaticText * m_title_remain
Label * m_tip_remain_line1
CheckBox * m_checkbox_switch_filament
wxStaticText * m_title_switch_filament
Label * m_tip_switch_filament_line1
wxStaticText * m_tip_ams_img
Button * m_button_auto_demarcate
wxBoxSizer * m_sizer_Insert_material_tip_inline
wxBoxSizer * m_sizer_starting_tip_inline
wxBoxSizer * m_sizer_remain_inline
wxBoxSizer * m_sizer_switch_filament_inline
wxBoxSizer * m_sizer_remain_block
Private Member Functions
bool is_new_scale_factor () const
void scale_win_font (wxWindow *window, const int font_point_size)
void scale_controls_fonts (wxWindow *window, const int font_point_size)
void rescale (const wxRect &suggested_rect)
Private Attributes
float m_scale_factor
int m_em_unit
wxFont m_normal_font
float m_prev_scale_factor
bool m_can_rescale { true }
bool m_force_rescale { false }
int m_new_font_point_size
Detailed Description
Constructor & Destructor Documentation
AMSSetting()
Slic3r::GUI::AMSSetting::AMSSetting (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE)
    : DPIDialog(parent, id, wxEmptyString, pos, size, style)
{
    create();
    wxGetApp().UpdateDlgDarkUI(this);
}
References create().
~AMSSetting()
Slic3r::GUI::AMSSetting::~AMSSetting ()
{}
Member Function Documentation
append_text()
wxStaticText * Slic3r::GUI::AMSSetting::append_text (wxString text)
{
    auto *widget = new wxStaticText(m_panel_body, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    widget->Wrap(250);
    widget->SetMinSize(wxSize(250, -1));
    return widget;
}
References m_panel_body, and wxStaticText.
append_title()
wxString Slic3r::GUI::AMSSetting::append_title (wxString text)
{
    wxString lab;
    auto *   widget = new wxStaticText(m_panel_body, wxID_ANY, text, wxDefaultPosition, wxDefaultSize, wxALIGN_LEFT);
    widget->SetForegroundColour(*wxBLACK);
    widget->Wrap(AMS_SETTING_BODY_WIDTH);
    widget->SetMinSize(wxSize(AMS_SETTING_BODY_WIDTH, -1));
    lab = widget->GetLabel();
    widget->Destroy();
    return lab;
}
References AMS_SETTING_BODY_WIDTH, m_panel_body, and wxStaticText.
create()
void Slic3r::GUI::AMSSetting::create ()
{
    wxBoxSizer *m_sizer_main;
    m_sizer_main = new wxBoxSizer(wxVERTICAL);
    SetBackgroundColour(*wxWHITE);
    auto m_static_ams_settings = new wxStaticText(this, wxID_ANY, _L("AMS Settings"), wxDefaultPosition, wxDefaultSize, 0);
    m_static_ams_settings->SetFont(::Label::Head_14);
    m_static_ams_settings->SetForegroundColour(AMS_SETTING_GREY800);
    m_sizer_main->Add(0,0,0,wxTOP,FromDIP(10));
    m_sizer_main->Add(m_static_ams_settings, 0, wxEXPAND | wxLEFT | wxRIGHT, FromDIP(24));
    m_panel_body = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxSize(-1, -1), wxTAB_TRAVERSAL);
    m_panel_body->SetBackgroundColour(*wxWHITE);
    wxBoxSizer *m_sizerl_body = new wxBoxSizer(wxVERTICAL);
    // checkbox area 1
    wxBoxSizer *m_sizer_Insert_material  = new wxBoxSizer(wxHORIZONTAL);
    m_checkbox_Insert_material_auto_read = new ::CheckBox(m_panel_body);
    m_checkbox_Insert_material_auto_read->Bind(wxEVT_TOGGLEBUTTON, &AMSSetting::on_insert_material_read, this);
    m_sizer_Insert_material->Add(m_checkbox_Insert_material_auto_read, 0, wxTOP, 1);
    m_sizer_Insert_material->Add(0, 0, 0, wxLEFT, 12);
    m_title_Insert_material_auto_read = new wxStaticText(m_panel_body, wxID_ANY, _L("Insertion update"),
                                                         wxDefaultPosition, wxDefaultSize, 0);
    m_title_Insert_material_auto_read->SetFont(::Label::Head_13);
    m_title_Insert_material_auto_read->SetForegroundColour(AMS_SETTING_GREY800);
    m_title_Insert_material_auto_read->Wrap(AMS_SETTING_BODY_WIDTH);
    m_sizer_Insert_material->Add(m_title_Insert_material_auto_read, 1, wxALL | wxEXPAND, 0);
    wxBoxSizer *m_sizer_Insert_material_tip = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_Insert_material_tip_inline      = new wxBoxSizer(wxVERTICAL);
    m_sizer_Insert_material_tip->Add(0, 0, 0, wxLEFT, 10);
    // tip line1
    m_tip_Insert_material_line1 = new Label(m_panel_body,
        _L("The AMS will automatically read the filament information when inserting a new Bambu Lab filament. This takes about 20 seconds.")
    );
    m_tip_Insert_material_line1->SetFont(::Label::Body_13);
    m_tip_Insert_material_line1->SetForegroundColour(AMS_SETTING_GREY700);
    m_tip_Insert_material_line1->SetSize(wxSize(AMS_SETTING_BODY_WIDTH, -1));
    m_tip_Insert_material_line1->Wrap(AMS_SETTING_BODY_WIDTH);
    m_tip_Insert_material_line1->Hide();
    m_sizer_Insert_material_tip_inline->Add(m_tip_Insert_material_line1, 0, wxEXPAND, 0);
    // tip line2
    m_tip_Insert_material_line2 = new Label(m_panel_body,
        _L("Note: if new filament is inserted during  printing, the AMS will not automatically read any information until printing is completed.")
    );
    m_tip_Insert_material_line2->SetFont(::Label::Body_13);
    m_tip_Insert_material_line2->SetForegroundColour(AMS_SETTING_GREY700);
    m_tip_Insert_material_line2->SetSize(wxSize(AMS_SETTING_BODY_WIDTH, -1));
    m_tip_Insert_material_line2->Wrap(AMS_SETTING_BODY_WIDTH);
    m_tip_Insert_material_line2->Hide();
    m_sizer_Insert_material_tip_inline->Add(m_tip_Insert_material_line2, 0, wxEXPAND | wxTOP, 8);
    // tip line2
    m_tip_Insert_material_line3 = new Label(m_panel_body,
        _L("When inserting a new filament, the AMS will not automatically read its information, leaving it blank for you to enter manually.")
    );
    m_tip_Insert_material_line3->SetFont(::Label::Body_13);
    m_tip_Insert_material_line3->SetForegroundColour(AMS_SETTING_GREY700);
    m_tip_Insert_material_line3->SetSize(wxSize(AMS_SETTING_BODY_WIDTH, -1));
    m_tip_Insert_material_line3->Wrap(AMS_SETTING_BODY_WIDTH);
    m_tip_Insert_material_line3->Hide();
    m_sizer_Insert_material_tip_inline->Add(m_tip_Insert_material_line3, 0, wxEXPAND, 0);
    m_sizer_Insert_material_tip->Add(m_sizer_Insert_material_tip_inline, 1, wxALIGN_CENTER, 0);
    // checkbox area 2
    wxBoxSizer *m_sizer_starting = new wxBoxSizer(wxHORIZONTAL);
    m_checkbox_starting_auto_read = new ::CheckBox(m_panel_body);
    m_checkbox_starting_auto_read->Bind(wxEVT_TOGGLEBUTTON, &AMSSetting::on_starting_read, this);
    m_sizer_starting->Add(m_checkbox_starting_auto_read, 0, wxTOP, 1);
    m_sizer_starting->Add(0, 0, 0, wxLEFT, 12);
    m_title_starting_auto_read = new wxStaticText(m_panel_body, wxID_ANY, _L("Power on update"), wxDefaultPosition,wxDefaultSize, 0);
    m_title_starting_auto_read->SetFont(::Label::Head_13);
    m_title_starting_auto_read->SetForegroundColour(AMS_SETTING_GREY800);
    m_title_starting_auto_read->Wrap(AMS_SETTING_BODY_WIDTH);
    m_sizer_starting->Add(m_title_starting_auto_read, 1, wxEXPAND, 0);
    wxBoxSizer *m_sizer_starting_tip = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_starting_tip->Add(0, 0, 0, wxLEFT, 10);
    // tip line
    m_sizer_starting_tip_inline = new wxBoxSizer(wxVERTICAL);
    m_tip_starting_line1 = new Label(m_panel_body,
        _L("The AMS will automatically read the information of inserted filament on start-up. It will take about 1 minute.The reading process will roll filament spools.")
    );
    m_tip_starting_line1->SetFont(::Label::Body_13);
    m_tip_starting_line1->SetForegroundColour(AMS_SETTING_GREY700);
    m_tip_starting_line1->SetSize(wxSize(AMS_SETTING_BODY_WIDTH, -1));
    m_tip_starting_line1->Wrap(AMS_SETTING_BODY_WIDTH);
    m_sizer_starting_tip_inline->Add(m_tip_starting_line1, 0, wxEXPAND, 0);
    m_tip_starting_line2 = new Label(m_panel_body,
        _L("The AMS will not automatically read information from inserted filament during startup and will continue to use the information recorded before the last shutdown.")
    );
    m_tip_starting_line2->SetFont(::Label::Body_13);
    m_tip_starting_line2->SetForegroundColour(AMS_SETTING_GREY700);
    m_tip_starting_line2->SetSize(wxSize(AMS_SETTING_BODY_WIDTH, -1));
    m_tip_starting_line2->Wrap(AMS_SETTING_BODY_WIDTH);
    m_sizer_starting_tip_inline->Add(m_tip_starting_line2, 0, wxEXPAND,0);
    m_sizer_starting_tip->Add(m_sizer_starting_tip_inline, 1, wxALIGN_CENTER, 0);
    // checkbox area 3
    wxBoxSizer* m_sizer_remain = new wxBoxSizer(wxHORIZONTAL);
    m_checkbox_remain = new ::CheckBox(m_panel_body);
    m_checkbox_remain->Bind(wxEVT_TOGGLEBUTTON, &AMSSetting::on_remain, this);
    m_sizer_remain->Add(m_checkbox_remain, 0, wxTOP, 1);
    m_sizer_remain->Add(0, 0, 0, wxLEFT, 12);
    m_title_remain = new wxStaticText(m_panel_body, wxID_ANY, _L("Update remaining capacity"), wxDefaultPosition, wxDefaultSize, 0);
    m_title_remain->SetFont(::Label::Head_13);
    m_title_remain->SetForegroundColour(AMS_SETTING_GREY800);
    m_title_remain->Wrap(AMS_SETTING_BODY_WIDTH);
    m_sizer_remain->Add(m_title_remain, 1, wxEXPAND, 0);
    wxBoxSizer* m_sizer_remain_tip = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_remain_tip->Add(0, 0, 0, wxLEFT, 10);
    // tip line
    m_sizer_remain_inline = new wxBoxSizer(wxVERTICAL);
    m_tip_remain_line1 = new Label(m_panel_body,
        _L("The AMS will estimate Bambu filament's remaining capacity after the filament info is updated. During printing, remaining capacity will be updated automatically.")
    );
    m_tip_remain_line1->SetFont(::Label::Body_13);
    m_tip_remain_line1->SetForegroundColour(AMS_SETTING_GREY700);
    m_tip_remain_line1->SetSize(wxSize(AMS_SETTING_BODY_WIDTH, -1));
    m_tip_remain_line1->Wrap(AMS_SETTING_BODY_WIDTH);
    m_sizer_remain_inline->Add(m_tip_remain_line1, 0, wxEXPAND, 0);
    m_sizer_remain_tip->Add(m_sizer_remain_inline, 1, wxALIGN_CENTER, 0);
    // checkbox area 4
    wxBoxSizer* m_sizer_switch_filament = new wxBoxSizer(wxHORIZONTAL);
    m_checkbox_switch_filament = new ::CheckBox(m_panel_body);
    m_checkbox_switch_filament->Bind(wxEVT_TOGGLEBUTTON, &AMSSetting::on_switch_filament, this);
    m_sizer_switch_filament->Add(m_checkbox_switch_filament, 0, wxTOP, 1);
    m_sizer_switch_filament->Add(0, 0, 0, wxLEFT, 12);
    m_title_switch_filament = new wxStaticText(m_panel_body, wxID_ANY, _L("AMS filament backup"), wxDefaultPosition, wxDefaultSize, 0);
    m_title_switch_filament->SetFont(::Label::Head_13);
    m_title_switch_filament->SetForegroundColour(AMS_SETTING_GREY800);
    m_title_switch_filament->Wrap(AMS_SETTING_BODY_WIDTH);
    m_sizer_switch_filament->Add(m_title_switch_filament, 1, wxEXPAND, 0);
    wxBoxSizer* m_sizer_switch_filament_tip = new wxBoxSizer(wxHORIZONTAL);
    m_sizer_switch_filament_tip->Add(0, 0, 0, wxLEFT, 10);
    // tip line
    m_sizer_switch_filament_inline = new wxBoxSizer(wxVERTICAL);
    m_tip_switch_filament_line1 = new Label(m_panel_body,
        _L("AMS will continue to another spool with the same properties of filament automatically when current filament runs out")
    );
    m_tip_switch_filament_line1->SetFont(::Label::Body_13);
    m_tip_switch_filament_line1->SetForegroundColour(AMS_SETTING_GREY700);
    m_tip_switch_filament_line1->SetSize(wxSize(AMS_SETTING_BODY_WIDTH, -1));
    m_tip_switch_filament_line1->Wrap(AMS_SETTING_BODY_WIDTH);
    m_sizer_switch_filament_inline->Add(m_tip_switch_filament_line1, 0, wxEXPAND, 0);
    m_sizer_switch_filament_tip->Add(m_sizer_switch_filament_inline, 1, wxALIGN_CENTER, 0);
    // panel img
    wxPanel* m_panel_img = new wxPanel(m_panel_body, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    m_panel_img->SetBackgroundColour(AMS_SETTING_GREY200);
    wxBoxSizer *m_sizer_img = new wxBoxSizer(wxVERTICAL);
    auto img = new wxStaticBitmap(m_panel_img, wxID_ANY, create_scaled_bitmap("ams_icon", nullptr, 126), wxDefaultPosition, wxDefaultSize);
    m_sizer_img->Add(img, 0, wxALIGN_CENTER | wxTOP, 26);
    m_sizer_img->Add(0, 0, 0, wxTOP, 18);
    m_panel_img->SetSizer(m_sizer_img);
    m_panel_img->Layout();
    m_sizer_img->Fit(m_panel_img);
    m_sizer_remain_block = new wxBoxSizer(wxVERTICAL);
    m_sizer_remain_block->Add(m_sizer_remain, 0, wxEXPAND | wxTOP, FromDIP(8));
    m_sizer_remain_block->Add(0, 0, 0, wxTOP, 8);
    m_sizer_remain_block->Add(m_sizer_remain_tip, 0, wxLEFT, 18);
    m_sizer_remain_block->Add(0, 0, 0, wxTOP, 15);
    m_sizerl_body->Add(m_sizer_Insert_material, 0, wxEXPAND, 0);
    m_sizerl_body->Add(0, 0, 0, wxTOP, 8);
    m_sizerl_body->Add(m_sizer_Insert_material_tip, 0, wxEXPAND | wxLEFT, 18);
    m_sizerl_body->Add(0, 0, 0, wxTOP, 15);
    m_sizerl_body->Add(m_sizer_starting, 0, wxEXPAND | wxTOP, FromDIP(8));
    m_sizerl_body->Add(0, 0, 0, wxTOP, 8);
    m_sizerl_body->Add(m_sizer_starting_tip, 0, wxLEFT, 18);
    m_sizerl_body->Add(0, 0, 0, wxTOP, 15);
    m_sizerl_body->Add(m_sizer_remain_block, 0, wxEXPAND, 0);
    m_sizerl_body->Add(m_sizer_switch_filament, 0, wxEXPAND | wxTOP, FromDIP(8));
    m_sizerl_body->Add(0, 0, 0, wxTOP, 8);
    m_sizerl_body->Add(m_sizer_switch_filament_tip, 0, wxLEFT, 18);
    m_sizerl_body->Add(0, 0, 0, wxTOP, 6);
    m_sizerl_body->Add(0, 0, 0, wxTOP, FromDIP(5));
    m_sizerl_body->Add(m_panel_img, 1, wxEXPAND | wxALL, FromDIP(5));
    m_panel_body->SetSizer(m_sizerl_body);
    m_panel_body->Layout();
    m_sizerl_body->Fit(m_panel_body);
    m_sizer_main->Add(m_panel_body, 1, wxALL | wxEXPAND, FromDIP(24));
    this->SetSizer(m_sizer_main);
    this->Layout();
    m_sizer_main->Fit(this);
    this->Centre(wxBOTH);
    wxGetApp().UpdateDlgDarkUI(this);
    Bind(wxEVT_SHOW, [this](auto& e) {
        if (this->IsShown()) {
            if (ams_support_remain) {
                m_sizer_remain_block->Show(true);
            }
            else {
                m_sizer_remain_block->Show(false);
            }
        }
    });
}
References _L, AMS_SETTING_BODY_WIDTH, AMS_SETTING_GREY200, AMS_SETTING_GREY700, AMS_SETTING_GREY800, ams_support_remain, Label::Body_13, create_scaled_bitmap(), Label::Head_13, Label::Head_14, m_checkbox_Insert_material_auto_read, m_checkbox_remain, m_checkbox_starting_auto_read, m_checkbox_switch_filament, m_panel_body, m_sizer_Insert_material_tip_inline, m_sizer_remain_block, m_sizer_remain_inline, m_sizer_starting_tip_inline, m_sizer_switch_filament_inline, m_tip_Insert_material_line1, m_tip_Insert_material_line2, m_tip_Insert_material_line3, m_tip_remain_line1, m_tip_starting_line1, m_tip_starting_line2, m_tip_switch_filament_line1, m_title_Insert_material_auto_read, m_title_remain, m_title_starting_auto_read, m_title_switch_filament, on_insert_material_read(), on_remain(), on_starting_read(), on_switch_filament(), Label::Wrap(), and wxStaticText.
Referenced by AMSSetting().
em_unit()
template<class P > int Slic3r::GUI::DPIAware< P >::em_unit () const inline inherited
{ return m_em_unit; }
References Slic3r::GUI::DPIAware< P >::m_em_unit.
Referenced by Slic3r::GUI::AuxiliaryDialog::AuxiliaryDialog(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::DiffPresetDialog::DiffPresetDialog(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::MsgNoUpdates::MsgNoUpdates(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::MsgUpdateForced::MsgUpdateForced(), Slic3r::GUI::PageMaterials::PageMaterials(), Slic3r::GUI::ParamsDialog::ParamsDialog(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), em_unit(), Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::AuxiliaryDialog::on_dpi_changed(), Slic3r::GUI::BedShapeDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::ObjectTableDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SettingsDialog::on_dpi_changed(), Slic3r::GUI::ParamsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), Slic3r::GUI::DiffPresetDialog::on_dpi_changed(), and Slic3r::GUI::GUI_App::update_fonts().
enable_force_rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::enable_force_rescale () inline inherited
{ m_force_rescale = true; }
References Slic3r::GUI::DPIAware< P >::m_force_rescale.
is_new_scale_factor()
template<class P > bool Slic3r::GUI::DPIAware< P >::is_new_scale_factor () const inline private inherited
{ return fabs(m_scale_factor - m_prev_scale_factor) > 0.001; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, and Slic3r::GUI::DPIAware< P >::m_scale_factor.
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
normal_font()
template<class P > const wxFont & Slic3r::GUI::DPIAware< P >::normal_font () const inline inherited
{ return m_normal_font; }
References Slic3r::GUI::DPIAware< P >::m_normal_font.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::ConfigWizard::ConfigWizard(), Slic3r::GUI::CopyrightsDialog::CopyrightsDialog(), Slic3r::GUI::KBShortcutsDialog::KBShortcutsDialog(), Slic3r::GUI::MsgDialog::MsgDialog(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::SelectMachineDialog::SelectMachineDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SettingsDialog::SettingsDialog(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), Slic3r::GUI::SavePresetDialog::build(), Slic3r::GUI::BedShapeDialog::build_dialog(), and Slic3r::GUI::PhysicalPrinterDialog::build_printhost_settings().
on_dpi_changed()
void Slic3r::GUI::AMSSetting::on_dpi_changed (const wxRect & suggested_rect) override protected virtual
Implements Slic3r::GUI::DPIAware< P >.
{
    //m_button_auto_demarcate->SetMinSize(AMS_SETTING_BUTTON_SIZE);
}
on_insert_material_read()
void Slic3r::GUI::AMSSetting::on_insert_material_read (wxCommandEvent & event)
{
    // send command
    if (m_checkbox_Insert_material_auto_read->GetValue()) {
        // checked
        m_tip_Insert_material_line1->Show();
        m_tip_Insert_material_line2->Show();
        m_tip_Insert_material_line3->Hide();
    } else {
        // unchecked
        m_tip_Insert_material_line1->Hide();
        m_tip_Insert_material_line2->Hide();
        m_tip_Insert_material_line3->Show();
    }
    m_checkbox_Insert_material_auto_read->SetValue(event.GetInt());
    bool start_read_opt = m_checkbox_starting_auto_read->GetValue();
    bool tray_read_opt = m_checkbox_Insert_material_auto_read->GetValue();
    bool remain_opt = m_checkbox_remain->GetValue();
    obj->command_ams_user_settings(ams_id, start_read_opt, tray_read_opt, remain_opt);
    m_sizer_Insert_material_tip_inline->Layout();
    Layout();
    Fit();
    event.Skip();
}
References ams_id, Slic3r::MachineObject::command_ams_user_settings(), m_checkbox_Insert_material_auto_read, m_checkbox_remain, m_checkbox_starting_auto_read, m_sizer_Insert_material_tip_inline, m_tip_Insert_material_line1, m_tip_Insert_material_line2, m_tip_Insert_material_line3, and obj.
Referenced by create().
on_remain()
void Slic3r::GUI::AMSSetting::on_remain (wxCommandEvent & event)
{
    bool start_read_opt = m_checkbox_starting_auto_read->GetValue();
    bool tray_read_opt = m_checkbox_Insert_material_auto_read->GetValue();
    bool remain_opt = m_checkbox_remain->GetValue();
    obj->command_ams_user_settings(ams_id, start_read_opt, tray_read_opt, remain_opt);
    event.Skip();
}
References ams_id, Slic3r::MachineObject::command_ams_user_settings(), m_checkbox_Insert_material_auto_read, m_checkbox_remain, m_checkbox_starting_auto_read, and obj.
Referenced by create().
on_select_ok()
void Slic3r::GUI::AMSSetting::on_select_ok (wxMouseEvent & event)
{
    if (obj) {
        obj->command_ams_calibrate(ams_id);
    }
}
References ams_id, Slic3r::MachineObject::command_ams_calibrate(), and obj.
on_starting_read()
void Slic3r::GUI::AMSSetting::on_starting_read (wxCommandEvent & event)
{
    if (m_checkbox_starting_auto_read->GetValue()) {
        // checked
        m_tip_starting_line1->Show();
        m_tip_starting_line2->Hide();
    } else {
        // unchecked
        m_tip_starting_line1->Hide();
        m_tip_starting_line2->Show();
    }
    m_checkbox_starting_auto_read->SetValue(event.GetInt());
    bool start_read_opt = m_checkbox_starting_auto_read->GetValue();
    bool tray_read_opt  = m_checkbox_Insert_material_auto_read->GetValue();
    bool remain_opt = m_checkbox_remain->GetValue();
    obj->command_ams_user_settings(ams_id, start_read_opt, tray_read_opt, remain_opt);
    m_sizer_starting_tip_inline->Layout();
    Layout();
    Fit();
    event.Skip();
}
References ams_id, Slic3r::MachineObject::command_ams_user_settings(), m_checkbox_Insert_material_auto_read, m_checkbox_remain, m_checkbox_starting_auto_read, m_sizer_starting_tip_inline, m_tip_starting_line1, m_tip_starting_line2, and obj.
Referenced by create().
on_switch_filament()
void Slic3r::GUI::AMSSetting::on_switch_filament (wxCommandEvent & event)
{
    bool switch_filament = m_checkbox_switch_filament->GetValue();
    obj->command_ams_switch_filament(switch_filament);
    event.Skip();
}
References Slic3r::MachineObject::command_ams_switch_filament(), m_checkbox_switch_filament, and obj.
Referenced by create().
on_sys_color_changed()
template<class P > virtual void Slic3r::GUI::DPIAware< P >::on_sys_color_changed () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ConfigWizard, Slic3r::GUI::ObjectTableDialog, Slic3r::GUI::MainFrame, Slic3r::GUI::PhysicalPrinterDialog, Slic3r::GUI::PrintHostQueueDialog, Slic3r::GUI::SavePresetDialog, Slic3r::GUI::UnsavedChangesDialog, and Slic3r::GUI::DiffPresetDialog.
{};
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
prev_scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::prev_scale_factor () const inline inherited
{ return m_prev_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_prev_scale_factor.
rescale()
template<class P > void Slic3r::GUI::DPIAware< P >::rescale (const wxRect & suggested_rect) inline private inherited
    {
        this->Freeze();
        m_force_rescale = false;
#if !wxVERSION_EQUAL_OR_GREATER_THAN(3,1,3)
        // rescale fonts of all controls
        scale_controls_fonts(this, m_new_font_point_size);
        // rescale current window font
        scale_win_font(this, m_new_font_point_size);
#endif // wxVERSION_EQUAL_OR_GREATER_THAN
        // set normal application font as a current window font
        m_normal_font = this->GetFont();
        // update em_unit value for new window font
        m_em_unit = std::max<int>(10, 10.0f * m_scale_factor);
        // rescale missed controls sizes and images
        on_dpi_changed(suggested_rect);
        this->Layout();
        this->Thaw();
        // reset previous scale factor from current scale factor value
        m_prev_scale_factor = m_scale_factor;
    }
References Slic3r::GUI::DPIAware< P >::m_em_unit, Slic3r::GUI::DPIAware< P >::m_force_rescale, Slic3r::GUI::DPIAware< P >::m_new_font_point_size, Slic3r::GUI::DPIAware< P >::m_normal_font, Slic3r::GUI::DPIAware< P >::m_prev_scale_factor, Slic3r::GUI::DPIAware< P >::m_scale_factor, Slic3r::GUI::DPIAware< P >::on_dpi_changed(), Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
scale_controls_fonts()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_controls_fonts (wxWindow * window, const int font_point_size) inline private inherited
    {
        auto children = window->GetChildren();
        for (auto child : children) {
            scale_controls_fonts(child, font_point_size);
            scale_win_font(child, font_point_size);
        }
        window->Layout();
    }
References Slic3r::GUI::DPIAware< P >::scale_controls_fonts(), and Slic3r::GUI::DPIAware< P >::scale_win_font().
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
scale_factor()
template<class P > float Slic3r::GUI::DPIAware< P >::scale_factor () const inline inherited
{ return m_scale_factor; }
References Slic3r::GUI::DPIAware< P >::m_scale_factor.
scale_win_font()
template<class P > void Slic3r::GUI::DPIAware< P >::scale_win_font (wxWindow * window, const int font_point_size) inline private inherited
    {
        wxFont new_font(window->GetFont());
        new_font.SetPointSize(font_point_size);
        window->SetFont(new_font);
    }
Referenced by Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_controls_fonts().
ShowModal()
template<class P > int Slic3r::GUI::DPIAware< P >::ShowModal () inline inherited
    {
        dialogStack.push_front(this);
        int r = wxDialog::ShowModal();
        dialogStack.pop_front();
        return r;
    }
References Slic3r::GUI::dialogStack.
Referenced by Slic3r::GUI::MainFrame::MainFrame(), Slic3r::GUI::PrintHostSendDialog::PrintHostSendDialog(), Slic3r::GUI::SendSystemInfoDialog::SendSystemInfoDialog(), Slic3r::GUI::Sidebar::Sidebar(), Slic3r::GUI::Temp_Calibration_Dlg::Temp_Calibration_Dlg(), WipingPanel::WipingPanel(), Slic3r::GUI::about(), Slic3r::GUI::GLGizmoSlaSupports::ask_about_changes_call_after(), Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::ConfigWizard::priv::check_and_install_missing_materials(), Slic3r::GUI::ConfigManipulation::check_bed_temperature_difference(), Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::GUI_App::check_print_host_queue(), Slic3r::GUI::GUI_App::check_updates(), Slic3r::GUI::Plater::close_with_confirm(), Slic3r::PresetUpdater::config_update(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::PreferencesDialog::create_debug_page(), Slic3r::GUI::PreferencesDialog::create_item_language_combobox(), Slic3r::GUI::PreferencesDialog::create_item_region_combobox(), Slic3r::GUI::ObjectList::del_from_cut_object(), Slic3r::GUI::Plater::priv::delete_object_from_model(), Slic3r::GUI::ImageGrid::DoAction(), Slic3r::GUI::MainFrame::export_config(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::Field::get_value_by_opt_type(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::GUI_App::keyboard_shortcuts(), Slic3r::GUI::MainFrame::load_config_file(), Slic3r::GUI::Plater::priv::load_files(), Slic3r::GUI::Plater::load_gcode(), Slic3r::GUI::ObjectList::load_generic_subobject(), Slic3r::GUI::Plater::priv::load_model_objects(), Slic3r::GUI::StatusPanel::on_ams_filament_backup(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::BindMachineDialog::on_bind_success(), Slic3r::GUI::ExtrusionCalibration::on_click_save(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::GUI_App::on_http_error(), Slic3r::GUI::SelectMachineDialog::on_rename_enter(), Slic3r::GUI::SendToPrinterDialog::on_rename_enter(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::MainFrame::on_select_default_preset(), Slic3r::GUI::AMSMaterialsSetting::on_select_ok(), Slic3r::GUI::AMSMaterialsSetting::on_select_reset(), Slic3r::GUI::SelectMachineDialog::on_selection_changed(), Slic3r::GUI::PrivacyUpdateDialog::on_show(), Slic3r::GUI::ConfirmBeforeSendDialog::on_show(), Slic3r::GUI::StatusPanel::on_show_print_options(), Slic3r::GUI::MachineInfoPanel::on_show_release_note(), Slic3r::GUI::PA_Calibration_Dlg::on_start(), Slic3r::GUI::Temp_Calibration_Dlg::on_start(), Slic3r::GUI::MaxVolumetricSpeed_Test_Dlg::on_start(), Slic3r::GUI::VFA_Test_Dlg::on_start(), Slic3r::GUI::Retraction_Test_Dlg::on_start(), Slic3r::GUI::StatusPanel::on_start_calibration(), Slic3r::PresetUpdater::on_update_notification_confirm(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::AboutDialog::onCopyrightBtn(), Slic3r::GUI::Plater::open_3mf_file(), Slic3r::GUI::GUI_App::open_preferences(), Slic3r::GUI::MainFrame::open_recent_project(), Slic3r::GUI::ExtrusionCalibration::Popup(), Slic3r::GUI::ObjectTableDialog::Popup(), Slic3r::GUI::AMSMaterialsSetting::Popup(), Slic3r::GUI::SelectMachineDialog::popup_filament_backup(), Slic3r::GUI::Plater::priv::replace_volume_with_stl(), Slic3r::GUI::Plater::priv::replace_with_stl(), Slic3r::GUI::GuideFrame::run(), Slic3r::GUI::ConfigWizard::run(), Slic3r::GUI::UnsavedChangesDialog::save(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Plater::save_project(), Slic3r::GUI::Plater::priv::save_project_if_dirty(), Slic3r::GUI::ConfigWizard::priv::select_default_materials_for_printer_models(), Slic3r::GUI::Plater::select_plate_by_hover_id(), Slic3r::GUI::Plater::send_gcode_legacy(), Slic3r::GUI::MachineObjectPanel::show_bind_dialog(), Slic3r::GUI::show_error(), Slic3r::GUI::show_info(), Slic3r::GUI::GUI_App::show_modal_ip_address_enter_dialog(), Slic3r::GUI::StatusPanel::show_recenter_dialog(), Slic3r::GUI::show_send_system_info_dialog_if_needed(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::show_substitutions_info(), Slic3r::GUI::Tab::show_timelapse_warning_dialog(), Slic3r::GUI::GUI_App::ShowDownNetPluginDlg(), Slic3r::GUI::ObjectList::switch_to_object_process(), Slic3r::GUI::Sidebar::sync_ams_list(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::MediaPlayCtrl::ToggleStream(), Slic3r::GUI::StatusPanel::update(), Slic3r::GUI::SelectMachinePopup::update_other_devices(), Slic3r::GUI::Plater::priv::update_plugin_when_launch(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), Slic3r::GUI::ConfigManipulation::update_print_sla_config(), Slic3r::GUI::GUI_App::updating_bambu_networking(), Slic3r::GUI::Tab::validate_custom_gcode(), Slic3r::GUI::warning_catcher(), and Slic3r::GUI::Plater::priv::warnings_dialog().
update_insert_material_read_mode()
void Slic3r::GUI::AMSSetting::update_insert_material_read_mode (bool selected)
{
    m_checkbox_Insert_material_auto_read->SetValue(selected);
    if (selected) {
        m_tip_Insert_material_line1->Show();
        m_tip_Insert_material_line2->Show();
        m_tip_Insert_material_line3->Hide();
    } else {
        m_tip_Insert_material_line1->Hide();
        m_tip_Insert_material_line2->Hide();
        m_tip_Insert_material_line3->Show();
    }
    m_sizer_Insert_material_tip_inline->Layout();
    Layout();
    Fit();
}
References m_checkbox_Insert_material_auto_read, m_sizer_Insert_material_tip_inline, m_tip_Insert_material_line1, m_tip_Insert_material_line2, and m_tip_Insert_material_line3.
Referenced by Slic3r::GUI::StatusPanel::on_ams_setting_click(), and Slic3r::GUI::StatusPanel::update_ams().
update_remain_mode()
void Slic3r::GUI::AMSSetting::update_remain_mode (bool selected)
{
    m_checkbox_remain->SetValue(selected);
}
References m_checkbox_remain.
Referenced by Slic3r::GUI::StatusPanel::update_ams().
update_starting_read_mode()
void Slic3r::GUI::AMSSetting::update_starting_read_mode (bool selected)
{
    m_checkbox_starting_auto_read->SetValue(selected);
    if (selected) { // selected
        m_tip_starting_line1->Show();
        m_tip_starting_line2->Hide();
    } else { // unselected
        m_tip_starting_line1->Hide();
        m_tip_starting_line2->Show();
    }
    m_sizer_starting_tip_inline->Layout();
    Layout();
    Fit();
}
References m_checkbox_starting_auto_read, m_sizer_starting_tip_inline, m_tip_starting_line1, and m_tip_starting_line2.
Referenced by Slic3r::GUI::StatusPanel::on_ams_setting_click(), and Slic3r::GUI::StatusPanel::update_ams().
update_switch_filament()
void Slic3r::GUI::AMSSetting::update_switch_filament (bool selected)
{
    if (obj->is_function_supported(PrinterFunction::FUNC_AUTO_SWITCH_FILAMENT)) {
        m_checkbox_switch_filament->Show();
        m_title_switch_filament->Show();
        m_tip_switch_filament_line1->Show();
        Layout();
    } else {
        m_checkbox_switch_filament->Hide();
        m_title_switch_filament->Hide();
        m_tip_switch_filament_line1->Hide();
        Layout();
    }
    m_checkbox_switch_filament->SetValue(selected);
}
References Slic3r::FUNC_AUTO_SWITCH_FILAMENT, Slic3r::MachineObject::is_function_supported(), m_checkbox_switch_filament, m_tip_switch_filament_line1, m_title_switch_filament, and obj.
Referenced by Slic3r::GUI::StatusPanel::update_ams().
Member Data Documentation
ams_id
int Slic3r::GUI::AMSSetting::ams_id { 0 }
Referenced by Slic3r::GUI::StatusPanel::on_ams_setting_click(), on_insert_material_read(), on_remain(), on_select_ok(), and on_starting_read().
ams_support_remain
bool Slic3r::GUI::AMSSetting::ams_support_remain {false}
Referenced by create(), and Slic3r::GUI::StatusPanel::on_ams_setting_click().
m_button_auto_demarcate
Button* Slic3r::GUI::AMSSetting::m_button_auto_demarcate protected
m_can_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_can_rescale { true } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware().
m_checkbox_Insert_material_auto_read
CheckBox* Slic3r::GUI::AMSSetting::m_checkbox_Insert_material_auto_read protected
Referenced by create(), on_insert_material_read(), on_remain(), on_starting_read(), and update_insert_material_read_mode().
m_checkbox_remain
CheckBox* Slic3r::GUI::AMSSetting::m_checkbox_remain protected
Referenced by create(), on_insert_material_read(), on_remain(), on_starting_read(), and update_remain_mode().
m_checkbox_starting_auto_read
CheckBox* Slic3r::GUI::AMSSetting::m_checkbox_starting_auto_read protected
Referenced by create(), on_insert_material_read(), on_remain(), on_starting_read(), and update_starting_read_mode().
m_checkbox_switch_filament
CheckBox* Slic3r::GUI::AMSSetting::m_checkbox_switch_filament protected
Referenced by create(), on_switch_filament(), and update_switch_filament().
m_em_unit
template<class P > int Slic3r::GUI::DPIAware< P >::m_em_unit private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::DPIAware< P >::rescale().
m_force_rescale
template<class P > bool Slic3r::GUI::DPIAware< P >::m_force_rescale { false } private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::enable_force_rescale(), and Slic3r::GUI::DPIAware< P >::rescale().
m_new_font_point_size
template<class P > int Slic3r::GUI::DPIAware< P >::m_new_font_point_size private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), and Slic3r::GUI::DPIAware< P >::rescale().
m_normal_font
template<class P > wxFont Slic3r::GUI::DPIAware< P >::m_normal_font private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::normal_font(), and Slic3r::GUI::DPIAware< P >::rescale().
m_panel_body
wxPanel* Slic3r::GUI::AMSSetting::m_panel_body protected
Referenced by append_text(), append_title(), and create().
m_prev_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_prev_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::prev_scale_factor(), and Slic3r::GUI::DPIAware< P >::rescale().
m_scale_factor
template<class P > float Slic3r::GUI::DPIAware< P >::m_scale_factor private inherited
Referenced by Slic3r::GUI::DPIAware< P >::DPIAware(), Slic3r::GUI::DPIAware< P >::is_new_scale_factor(), Slic3r::GUI::DPIAware< P >::rescale(), and Slic3r::GUI::DPIAware< P >::scale_factor().
m_sizer_Insert_material_tip_inline
wxBoxSizer* Slic3r::GUI::AMSSetting::m_sizer_Insert_material_tip_inline protected
Referenced by create(), on_insert_material_read(), and update_insert_material_read_mode().
m_sizer_remain_block
wxBoxSizer* Slic3r::GUI::AMSSetting::m_sizer_remain_block protected
Referenced by create().
m_sizer_remain_inline
wxBoxSizer* Slic3r::GUI::AMSSetting::m_sizer_remain_inline protected
Referenced by create().
m_sizer_starting_tip_inline
wxBoxSizer* Slic3r::GUI::AMSSetting::m_sizer_starting_tip_inline protected
Referenced by create(), on_starting_read(), and update_starting_read_mode().
m_sizer_switch_filament_inline
wxBoxSizer* Slic3r::GUI::AMSSetting::m_sizer_switch_filament_inline protected
Referenced by create().
m_tip_ams_img
wxStaticText* Slic3r::GUI::AMSSetting::m_tip_ams_img protected
m_tip_Insert_material_line1
Label* Slic3r::GUI::AMSSetting::m_tip_Insert_material_line1 protected
Referenced by create(), on_insert_material_read(), and update_insert_material_read_mode().
m_tip_Insert_material_line2
Label* Slic3r::GUI::AMSSetting::m_tip_Insert_material_line2 protected
Referenced by create(), on_insert_material_read(), and update_insert_material_read_mode().
m_tip_Insert_material_line3
Label* Slic3r::GUI::AMSSetting::m_tip_Insert_material_line3 protected
Referenced by create(), on_insert_material_read(), and update_insert_material_read_mode().
m_tip_remain_line1
Label* Slic3r::GUI::AMSSetting::m_tip_remain_line1 protected
Referenced by create().
m_tip_starting_line1
Label* Slic3r::GUI::AMSSetting::m_tip_starting_line1 protected
Referenced by create(), on_starting_read(), and update_starting_read_mode().
m_tip_starting_line2
Label* Slic3r::GUI::AMSSetting::m_tip_starting_line2 protected
Referenced by create(), on_starting_read(), and update_starting_read_mode().
m_tip_switch_filament_line1
Label* Slic3r::GUI::AMSSetting::m_tip_switch_filament_line1 protected
Referenced by create(), and update_switch_filament().
m_title_Insert_material_auto_read
wxStaticText* Slic3r::GUI::AMSSetting::m_title_Insert_material_auto_read protected
Referenced by create().
m_title_remain
wxStaticText* Slic3r::GUI::AMSSetting::m_title_remain protected
Referenced by create().
m_title_starting_auto_read
wxStaticText* Slic3r::GUI::AMSSetting::m_title_starting_auto_read protected
Referenced by create().
m_title_switch_filament
wxStaticText* Slic3r::GUI::AMSSetting::m_title_switch_filament protected
Referenced by create(), and update_switch_filament().
obj
MachineObject* Slic3r::GUI::AMSSetting::obj {nullptr}
Referenced by on_insert_material_read(), on_remain(), on_select_ok(), on_starting_read(), on_switch_filament(), Slic3r::GUI::StatusPanel::update_ams(), and update_switch_filament().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AMSSetting.hpp
src/slic3r/GUI/AMSSetting.cpp