OrcaSlicer: DropDown Class Reference
DropDown Class Reference
#include <src/slic3r/GUI/Widgets/DropDown.hpp>
Public Member Functions
DropDown (std::vector< wxString > &texts, std::vector< wxBitmap > &icons)
DropDown (wxWindow *parent, std::vector< wxString > &texts, std::vector< wxBitmap > &icons, long style=0)
void Create (wxWindow *parent, long style=0)
void Invalidate (bool clear=false)
int GetSelection () const
void SetSelection (int n)
wxString GetValue () const
void SetValue (const wxString &value)
void SetCornerRadius (double radius)
void SetBorderColor (StateColor const &color)
void SetSelectorBorderColor (StateColor const &color)
void SetTextColor (StateColor const &color)
void SetSelectorBackgroundColor (StateColor const &color)
void SetUseContentWidth (bool use)
void SetAlignIcon (bool align)
void Rescale ()
bool HasDismissLongTime ()
bool Create (wxWindow *parent, int flags=wxBORDER_NONE)
Protected Member Functions
void OnDismiss () override
Private Member Functions
void paintEvent (wxPaintEvent &evt)
void paintNow ()
void render (wxDC &dc)
void messureSize ()
void autoPosition ()
void mouseDown (wxMouseEvent &event)
void mouseReleased (wxMouseEvent &event)
void mouseCaptureLost (wxMouseCaptureLostEvent &event)
void mouseMove (wxMouseEvent &event)
void mouseWheelMoved (wxMouseEvent &event)
void sendDropDownEvent ()
Private Attributes
std::vector< wxString > & texts
std::vector< wxBitmap > & icons
bool need_sync = false
int selection = -1
int hover_item = -1
double radius = 0
bool use_content_width = false
bool align_icon = false
bool text_off = false
wxSize textSize
wxSize iconSize
wxSize rowSize
StateHandler state_handler
StateColor text_color
StateColor border_color
StateColor selector_border_color
StateColor selector_background_color
ScalableBitmap check_bitmap
bool pressedDown = false
boost::posix_time::ptime dismissTime
wxPoint offset
wxPoint dragStart
Friends
class ComboBox
Detailed Description
Constructor & Destructor Documentation
DropDown() [1/2]
DropDown::DropDown (std::vector< wxString > & texts, std::vector< wxBitmap > & icons)
    : texts(texts)
    , icons(icons)
    , state_handler(this)
    , border_color(0xDBDBDB)
    , text_color(0x363636)
    , selector_border_color(std::make_pair(0x009688, (int) StateColor::Hovered),
        std::make_pair(*wxWHITE, (int) StateColor::Normal))
    , selector_background_color(std::make_pair(0xEDFAF2, (int) StateColor::Checked),
        std::make_pair(*wxWHITE, (int) StateColor::Normal))
{
}
DropDown() [2/2]
DropDown::DropDown (wxWindow * parent, std::vector< wxString > & texts, std::vector< wxBitmap > & icons, long style = 0)
    : DropDown(texts, icons)
{
    Create(parent, style);
}
References Create(), and style.
Member Function Documentation
autoPosition()
void DropDown::autoPosition () private
{
    messureSize();
    wxPoint pos = GetParent()->ClientToScreen(wxPoint(0, -6));
    wxPoint old = GetPosition();
    wxSize size = GetSize();
    Position(pos, {0, GetParent()->GetSize().y + 12});
    if (old != GetPosition()) {
        size = rowSize;
        size.y *= std::min((size_t)15, texts.size());
        size.y += texts.size() > 15 ? rowSize.y / 2 : 0;
        if (size != GetSize()) {
            wxWindow::SetSize(size);
            offset = wxPoint();
            Position(pos, {0, GetParent()->GetSize().y + 12});
        }
    }
    if (GetPosition().y > pos.y) {
        // may exceed
        auto drect = wxDisplay(GetParent()).GetGeometry();
        if (GetPosition().y + size.y + 10 > drect.GetBottom()) {
            if (use_content_width && texts.size() <= 15) size.x += 6;
            size.y = drect.GetBottom() - GetPosition().y - 10;
            wxWindow::SetSize(size);
            if (selection >= 0) {
                if (offset.y + rowSize.y * (selection + 1) > size.y)
                    offset.y = size.y - rowSize.y * (selection + 1);
                else if (offset.y + rowSize.y * selection < 0)
                    offset.y = -rowSize.y * selection;
            }
        }
    }
}
References messureSize(), offset, rowSize, selection, size, texts, and use_content_width.
Referenced by ComboBox::keyDown(), and ComboBox::mouseDown().
Create() [1/2]
bool PopupWindow::Create (wxWindow * parent, int flags = wxBORDER_NONE) inherited
{
    if (!wxPopupTransientWindow::Create(parent, style))
        return false;
#ifdef __WXGTK__
    GetTopParent(parent)->Bind(wxEVT_ACTIVATE, &PopupWindow::topWindowActiavate, this);
#endif
    return true;
}
References GetTopParent(), and style.
Referenced by PopupWindow::PopupWindow(), and Create().
Create() [2/2]
void DropDown::Create (wxWindow * parent, long style = 0)
{
    PopupWindow::Create(parent, wxPU_CONTAINS_CONTROLS);
    SetBackgroundStyle(wxBG_STYLE_PAINT);
    SetBackgroundColour(*wxWHITE);
    state_handler.attach({&border_color, &text_color, &selector_border_color, &selector_background_color});
    state_handler.update_binds();
    if ((style & DD_NO_CHECK_ICON) == 0)
        check_bitmap = ScalableBitmap(this, "checked", 16);
    text_off = style & DD_NO_TEXT;
    // BBS set default font
    SetFont(Label::Body_14);
#ifdef __WXOSX__
    // PopupWindow releases mouse on idle, which may cause various problems,
    //  such as losting mouse move, and dismissing soon on first LEFT_DOWN event.
    Bind(wxEVT_IDLE, [] (wxIdleEvent & evt) {});
#endif
}
References StateHandler::attach(), Label::Body_14, border_color, check_bitmap, PopupWindow::Create(), DD_NO_CHECK_ICON, DD_NO_TEXT, selector_background_color, selector_border_color, state_handler, style, text_color, text_off, and StateHandler::update_binds().
Referenced by DropDown().
GetSelection()
int DropDown::GetSelection () const inline
{ return selection; }
References selection.
Referenced by ComboBox::GetSelection(), ComboBox::GetValue(), ComboBox::sendComboBoxEvent(), and ComboBox::SetString().
GetValue()
wxString DropDown::GetValue () const
{
    return selection >= 0 ? texts[selection] : wxString();
}
References selection, and texts.
Referenced by ComboBox::GetValue(), ComboBox::sendComboBoxEvent(), sendDropDownEvent(), and ComboBox::SetSelection().
HasDismissLongTime()
bool DropDown::HasDismissLongTime ()
{
    auto now = boost::posix_time::microsec_clock::universal_time();
    return !IsShown() &&
        (now - dismissTime).total_milliseconds() >= 20;
}
References dismissTime.
Referenced by ComboBox::keyDown(), and ComboBox::mouseDown().
Invalidate()
void DropDown::Invalidate (bool clear = false)
{
    if (clear) {
        selection = hover_item = -1;
        offset = wxPoint();
    }
    assert(selection < (int) texts.size());
    need_sync = true;
}
References hover_item, need_sync, offset, selection, and texts.
Referenced by ComboBox::Append(), ComboBox::DoClear(), ComboBox::DoDeleteOneItem(), ComboBox::DoInsertItems(), ComboBox::SetItemBitmap(), and ComboBox::SetString().
messureSize()
void DropDown::messureSize () private
{
    if (!need_sync) return;
    textSize = wxSize();
    iconSize = wxSize();
    wxClientDC dc(GetParent() ? GetParent() : this);
    for (size_t i = 0; i < texts.size(); ++i) {
        wxSize size1 = text_off ? wxSize() : dc.GetMultiLineTextExtent(texts[i]);
        if (icons[i].IsOk()) {
            wxSize size2 = GetBmpSize(icons[i]);
            if (size2.x > iconSize.x) iconSize = size2;
            if (!align_icon) {
                size1.x += size2.x + (text_off ? 0 : 5);
            }
        }
        if (size1.x > textSize.x) textSize = size1;
    }
    if (!align_icon) iconSize.x = 0;
    wxSize szContent = textSize;
    szContent.x += 10;
    if (check_bitmap.bmp().IsOk()) {
        auto szBmp = check_bitmap.GetBmpSize();
        szContent.x += szBmp.x + 5;
    }
    if (iconSize.x > 0) szContent.x += iconSize.x + (text_off ? 0 : 5);
    if (iconSize.y > szContent.y) szContent.y = iconSize.y;
    szContent.y += 10;
    if (texts.size() > 15) szContent.x += 6;
    if (GetParent()) {
        auto x = GetParent()->GetSize().x;
        if (!use_content_width || x > szContent.x)
            szContent.x = x;
    }
    rowSize = szContent;
    szContent.y *= std::min((size_t)15, texts.size());
    szContent.y += texts.size() > 15 ? rowSize.y / 2 : 0;
    wxWindow::SetSize(szContent);
#ifdef __WXGTK__
    // Gtk has a wrapper window for popup widget
    gtk_window_resize (GTK_WINDOW (m_widget), szContent.x, szContent.y);
#endif
    need_sync = false;
}
References align_icon, ScalableBitmap::bmp(), check_bitmap, ScalableBitmap::GetBmpSize(), GetBmpSize(), icons, iconSize, need_sync, rowSize, text_off, texts, textSize, and use_content_width.
Referenced by autoPosition(), and SetUseContentWidth().
mouseCaptureLost()
void DropDown::mouseCaptureLost (wxMouseCaptureLostEvent & event) private
{
    wxMouseEvent evt;
    mouseReleased(evt);
}
References mouseReleased().
mouseDown()
void DropDown::mouseDown (wxMouseEvent & event) private
{
    // Receivce unexcepted LEFT_DOWN on Mac after OnDismiss
    if (!IsShown())
        return;
    // force calc hover item again
    mouseMove(event);
    pressedDown = true;
    CaptureMouse();
    dragStart   = event.GetPosition();
}
References dragStart, mouseMove(), and pressedDown.
mouseMove()
void DropDown::mouseMove (wxMouseEvent & event) private
{
    wxPoint pt  = event.GetPosition();
    if (pressedDown) {
        wxPoint pt2 = offset + pt - dragStart;
        wxSize  size = GetSize();
        dragStart    = pt;
        if (pt2.y > 0)
            pt2.y = 0;
        else if (pt2.y + rowSize.y * int(texts.size()) < size.y)
            pt2.y = size.y - rowSize.y * int(texts.size());
        if (pt2.y != offset.y) {
            offset = pt2;
            hover_item = -1; // moved
        } else {
            return;
        }
    }
    if (!pressedDown || hover_item >= 0) {
        int hover = (pt.y - offset.y) / rowSize.y;
        if (hover >= (int) texts.size()) hover = -1;
        if (hover == hover_item) return;
        hover_item = hover;
        if (hover >= 0)
            SetToolTip(texts[hover]);
    }
    paintNow();
}
References dragStart, hover_item, int, offset, paintNow(), pressedDown, rowSize, size, and texts.
Referenced by mouseDown().
mouseReleased()
void DropDown::mouseReleased (wxMouseEvent & event) private
{
    if (pressedDown) {
        dragStart = wxPoint();
        pressedDown = false;
        if (HasCapture())
            ReleaseMouse();
        if (hover_item >= 0) { // not moved
            sendDropDownEvent();
            DismissAndNotify();
        }
    }
}
References dragStart, hover_item, pressedDown, and sendDropDownEvent().
Referenced by mouseCaptureLost().
mouseWheelMoved()
void DropDown::mouseWheelMoved (wxMouseEvent & event) private
{
    auto delta = event.GetWheelRotation();
    wxSize  size  = GetSize();
    wxPoint pt2   = offset + wxPoint{0, delta};
    if (pt2.y > 0)
        pt2.y = 0;
    else if (pt2.y + rowSize.y * int(texts.size()) < size.y)
        pt2.y = size.y - rowSize.y * int(texts.size());
    if (pt2.y != offset.y) {
        offset = pt2;
    } else {
        return;
    }
    int hover = (event.GetPosition().y - offset.y) / rowSize.y;
    if (hover >= (int) texts.size()) hover = -1;
    if (hover != hover_item) {
        hover_item = hover;
        if (hover >= 0) SetToolTip(texts[hover]);
    }
    paintNow();
}
References hover_item, int, offset, paintNow(), rowSize, size, and texts.
OnDismiss()
void DropDown::OnDismiss () override protected
{
    dismissTime = boost::posix_time::microsec_clock::universal_time();
    hover_item  = -1;
    wxCommandEvent e(EVT_DISMISS);
    GetEventHandler()->ProcessEvent(e);
}
References dismissTime, and hover_item.
paintEvent()
void DropDown::paintEvent (wxPaintEvent & evt) private
{
    // depending on your system you may need to look at double-buffered dcs
    wxBufferedPaintDC dc(this);
    render(dc);
}
References render().
paintNow()
void DropDown::paintNow () private
{
    // depending on your system you may need to look at double-buffered dcs
    //wxClientDC dc(this);
    //render(dc);
    Refresh();
}
Referenced by mouseMove(), mouseWheelMoved(), SetBorderColor(), SetCornerRadius(), SetSelection(), SetSelectorBackgroundColor(), SetSelectorBorderColor(), and SetTextColor().
render()
void DropDown::render (wxDC & dc) private
{
    if (texts.size() == 0) return;
    int states = state_handler.states();
    dc.SetPen(wxPen(border_color.colorForStates(states)));
    dc.SetBrush(wxBrush(StateColor::darkModeColorFor(GetBackgroundColour())));
    // if (GetWindowStyle() & wxBORDER_NONE)
    //    dc.SetPen(wxNullPen);
    // draw background
    wxSize size = GetSize();
    if (radius == 0)
        dc.DrawRectangle(0, 0, size.x, size.y);
    else
        dc.DrawRoundedRectangle(0, 0, size.x, size.y, radius);
    // draw hover rectangle
    wxRect rcContent = {{0, offset.y}, rowSize};
    if (hover_item >= 0 && (states & StateColor::Hovered)) {
        rcContent.y += rowSize.y * hover_item;
        if (rcContent.GetBottom() > 0 && rcContent.y < size.y) {
            if (selection == hover_item)
                dc.SetBrush(wxBrush(selector_background_color.colorForStates(states | StateColor::Checked)));
            dc.SetPen(wxPen(selector_border_color.colorForStates(states)));
            rcContent.Deflate(4, 1);
            dc.DrawRectangle(rcContent);
            rcContent.Inflate(4, 1);
        }
        rcContent.y = offset.y;
    }
    // draw checked rectangle
    if (selection >= 0 && (selection != hover_item || (states & StateColor::Hovered) == 0)) {
        rcContent.y += rowSize.y * selection;
        if (rcContent.GetBottom() > 0 && rcContent.y < size.y) {
            dc.SetBrush(wxBrush(selector_background_color.colorForStates(states | StateColor::Checked)));
            dc.SetPen(wxPen(selector_background_color.colorForStates(states)));
            rcContent.Deflate(4, 1);
            dc.DrawRectangle(rcContent);
            rcContent.Inflate(4, 1);
        }
        rcContent.y = offset.y;
    }
    dc.SetBrush(*wxTRANSPARENT_BRUSH);
    {
        wxSize offset = (rowSize - textSize) / 2;
        rcContent.Deflate(0, offset.y);
    }
    // draw position bar
    if (rowSize.y * texts.size() > size.y) {
        int    height = rowSize.y * texts.size();
        wxRect rect = {size.x - 6, -offset.y * size.y / height, 4,
                       size.y * size.y / height};
        dc.SetPen(wxPen(border_color.defaultColor()));
        dc.SetBrush(wxBrush(*wxLIGHT_GREY));
        dc.DrawRoundedRectangle(rect, 2);
        rcContent.width -= 6;
    }
    // draw check icon
    rcContent.x += 5;
    rcContent.width -= 5;
    if (check_bitmap.bmp().IsOk()) {
        auto szBmp = check_bitmap.GetBmpSize();
        if (selection >= 0) {
            wxPoint pt = rcContent.GetLeftTop();
            pt.y += (rcContent.height - szBmp.y) / 2;
            pt.y += rowSize.y * selection;
            if (pt.y + szBmp.y > 0 && pt.y < size.y)
                dc.DrawBitmap(check_bitmap.bmp(), pt);
        }
        rcContent.x += szBmp.x + 5;
        rcContent.width -= szBmp.x + 5;
    }
    // draw texts & icons
    dc.SetTextForeground(text_color.colorForStates(states));
    for (int i = 0; i < texts.size(); ++i) {
        if (rcContent.GetBottom() < 0) {
            rcContent.y += rowSize.y;
            continue;
        }
        if (rcContent.y > size.y) break;
        wxPoint pt   = rcContent.GetLeftTop();
        auto & icon = icons[i];
        auto size2 = GetBmpSize(icon);
        if (iconSize.x > 0) {
            if (icon.IsOk()) {
                pt.y += (rcContent.height - size2.y) / 2;
                dc.DrawBitmap(icon, pt);
            }
            pt.x += iconSize.x + 5;
            pt.y = rcContent.y;
        } else if (icon.IsOk()) {
            pt.y += (rcContent.height - size2.y) / 2;
            dc.DrawBitmap(icon, pt);
            pt.x += size2.x + 5;
            pt.y = rcContent.y;
        }
        auto text = texts[i];
        if (!text_off && !text.IsEmpty()) {
            wxSize tSize = dc.GetMultiLineTextExtent(text);
            if (pt.x + tSize.x > rcContent.GetRight()) {
                text = wxControl::Ellipsize(text, dc, wxELLIPSIZE_END,
                                            rcContent.GetRight() - pt.x);
            }
            pt.y += (rcContent.height - textSize.y) / 2;
            dc.SetFont(GetFont());
            dc.DrawText(text, pt);
        }
        rcContent.y += rowSize.y;
    }
}
References ScalableBitmap::bmp(), border_color, check_bitmap, StateColor::Checked, StateColor::colorForStates(), StateColor::darkModeColorFor(), StateColor::defaultColor(), ScalableBitmap::GetBmpSize(), GetBmpSize(), hover_item, StateColor::Hovered, icons, iconSize, offset, radius, rowSize, selection, selector_background_color, selector_border_color, size, state_handler, StateHandler::states(), text_color, text_off, texts, and textSize.
Referenced by paintEvent().
Rescale()
void DropDown::Rescale ()
{
    need_sync = true;
}
References need_sync.
Referenced by ComboBox::Rescale().
sendDropDownEvent()
void DropDown::sendDropDownEvent () private
{
    selection = hover_item;
    wxCommandEvent event(wxEVT_COMBOBOX, GetId());
    event.SetEventObject(this);
    event.SetInt(selection);
    event.SetString(GetValue());
    GetEventHandler()->ProcessEvent(event);
}
References GetValue(), hover_item, and selection.
Referenced by mouseReleased().
SetAlignIcon()
void DropDown::SetAlignIcon (bool align)
{ align_icon = align; }
References align_icon.
SetBorderColor()
void DropDown::SetBorderColor (StateColor const & color)
{
    border_color = color;
    state_handler.update_binds();
    paintNow();
}
References border_color, paintNow(), state_handler, and StateHandler::update_binds().
SetCornerRadius()
void DropDown::SetCornerRadius (double radius)
{
    this->radius = radius;
    paintNow();
}
References paintNow(), and radius.
SetSelection()
void DropDown::SetSelection (int n)
{
    assert(n < (int) texts.size());
    if (n >= (int) texts.size())
        n = -1;
    if (selection == n) return;
    selection = n;
    paintNow();
}
References n, paintNow(), selection, and texts.
Referenced by ComboBox::SetSelection().
SetSelectorBackgroundColor()
void DropDown::SetSelectorBackgroundColor (StateColor const & color)
{
    selector_background_color = color;
    state_handler.update_binds();
    paintNow();
}
References paintNow(), selector_background_color, state_handler, and StateHandler::update_binds().
SetSelectorBorderColor()
void DropDown::SetSelectorBorderColor (StateColor const & color)
{
    selector_border_color = color;
    state_handler.update_binds();
    paintNow();
}
References paintNow(), selector_border_color, state_handler, and StateHandler::update_binds().
SetTextColor()
void DropDown::SetTextColor (StateColor const & color)
{
    text_color = color;
    state_handler.update_binds();
    paintNow();
}
References paintNow(), state_handler, text_color, and StateHandler::update_binds().
SetUseContentWidth()
void DropDown::SetUseContentWidth (bool use)
{
    if (use_content_width == use)
        return;
    use_content_width = use;
    need_sync = true;
    messureSize();
}
References messureSize(), need_sync, and use_content_width.
Referenced by Slic3r::GUI::PlaterPresetComboBox::PlaterPresetComboBox(), Slic3r::GUI::Choice::BUILD(), and BitmapChoiceRenderer::CreateEditorCtrl().
SetValue()
void DropDown::SetValue (const wxString & value)
{
    auto i = std::find(texts.begin(), texts.end(), value);
    selection = i == texts.end() ? -1 : std::distance(texts.begin(), i);
}
References std::distance(), selection, and texts.
Referenced by ComboBox::SetValue().
Friends And Related Symbol Documentation
ComboBox
friend class ComboBox friend
Member Data Documentation
align_icon
bool DropDown::align_icon = false private
Referenced by messureSize(), and SetAlignIcon().
border_color
StateColor DropDown::border_color private
Referenced by Create(), render(), and SetBorderColor().
check_bitmap
ScalableBitmap DropDown::check_bitmap private
Referenced by Create(), messureSize(), and render().
dismissTime
boost::posix_time::ptime DropDown::dismissTime private
Referenced by HasDismissLongTime(), and OnDismiss().
dragStart
wxPoint DropDown::dragStart private
Referenced by mouseDown(), mouseMove(), and mouseReleased().
hover_item
int DropDown::hover_item = -1 private
Referenced by Invalidate(), mouseMove(), mouseReleased(), mouseWheelMoved(), OnDismiss(), render(), and sendDropDownEvent().
icons
std::vector<wxBitmap>& DropDown::icons private
Referenced by messureSize(), and render().
iconSize
wxSize DropDown::iconSize private
Referenced by messureSize(), and render().
need_sync
bool DropDown::need_sync = false private
Referenced by Invalidate(), messureSize(), Rescale(), and SetUseContentWidth().
offset
wxPoint DropDown::offset private
Referenced by autoPosition(), Invalidate(), mouseMove(), mouseWheelMoved(), and render().
pressedDown
bool DropDown::pressedDown = false private
Referenced by mouseDown(), mouseMove(), and mouseReleased().
radius
double DropDown::radius = 0 private
Referenced by render(), and SetCornerRadius().
rowSize
wxSize DropDown::rowSize private
Referenced by autoPosition(), messureSize(), mouseMove(), mouseWheelMoved(), and render().
selection
int DropDown::selection = -1 private
Referenced by autoPosition(), GetSelection(), GetValue(), Invalidate(), render(), sendDropDownEvent(), SetSelection(), ComboBox::SetSelection(), ComboBox::SetValue(), and SetValue().
selector_background_color
StateColor DropDown::selector_background_color private
Referenced by Create(), render(), and SetSelectorBackgroundColor().
selector_border_color
StateColor DropDown::selector_border_color private
Referenced by Create(), render(), and SetSelectorBorderColor().
state_handler
StateHandler DropDown::state_handler private
Referenced by Create(), render(), SetBorderColor(), SetSelectorBackgroundColor(), SetSelectorBorderColor(), and SetTextColor().
text_color
StateColor DropDown::text_color private
Referenced by Create(), render(), and SetTextColor().
text_off
bool DropDown::text_off = false private
Referenced by Create(), messureSize(), and render().
texts
std::vector<wxString>& DropDown::texts private
Referenced by autoPosition(), GetValue(), Invalidate(), messureSize(), mouseMove(), mouseWheelMoved(), render(), SetSelection(), and SetValue().
textSize
wxSize DropDown::textSize private
Referenced by messureSize(), and render().
use_content_width
bool DropDown::use_content_width = false private
Referenced by autoPosition(), messureSize(), and SetUseContentWidth().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/DropDown.hpp
src/slic3r/GUI/Widgets/DropDown.cpp