OrcaSlicer: src/Shiny/ShinyNode.h File Reference
ShinyNode.h File Reference
#include "ShinyData.h"
#include "ShinyTools.h"
Classes
struct _ShinyNode
Typedefs
typedef struct _ShinyNode ShinyNode
Functions
SHINY_INLINE void ShinyNode_addChild (ShinyNode *self, ShinyNode *a_child)
SHINY_INLINE void ShinyNode_init (ShinyNode *self, ShinyNode *a_parent, struct _ShinyZone *a_zone, ShinyNodeCache *a_cache)
SHINY_API void ShinyNode_updateTree (ShinyNode *self, float a_damping)
SHINY_API void ShinyNode_updateTreeClean (ShinyNode *self)
SHINY_INLINE void ShinyNode_destroy (ShinyNode *self)
SHINY_INLINE void ShinyNode_appendTicks (ShinyNode *self, shinytick_t a_elapsedTicks)
SHINY_INLINE void ShinyNode_beginEntry (ShinyNode *self)
SHINY_INLINE int ShinyNode_isRoot (ShinyNode *self)
SHINY_INLINE int ShinyNode_isDummy (ShinyNode *self)
SHINY_INLINE int ShinyNode_isEqual (ShinyNode *self, const ShinyNode *a_parent, const struct _ShinyZone *a_zone)
SHINY_API const ShinyNode * ShinyNode_findNextInTree (const ShinyNode *self)
SHINY_API void ShinyNode_clear (ShinyNode *self)
SHINY_API void ShinyNode_enumerateNodes (const ShinyNode *a_node, void(*a_func)(const ShinyNode *))
Variables
ShinyNode _ShinyNode_dummy
Class Documentation
_ShinyNode
struct _ShinyNode
Class Members
ShinyNodeCache * _cache
ShinyLastData _last
uint32_t childCount
ShinyData data
uint32_t entryLevel
struct _ShinyNode * firstChild
struct _ShinyNode * lastChild
struct _ShinyNode * nextSibling
struct _ShinyNode * parent
struct _ShinyZone * zone
Typedef Documentation
ShinyNode
typedef struct _ShinyNode ShinyNode
Function Documentation
ShinyNode_addChild()
SHINY_INLINE void ShinyNode_addChild (ShinyNode * self, ShinyNode * a_child)
{
  if (self->childCount++) {
    self->lastChild->nextSibling = a_child;
    self->lastChild = a_child;
  } else {
    self->lastChild = a_child;
    self->firstChild = a_child;
  }
}
References _ShinyNode::childCount, _ShinyNode::firstChild, _ShinyNode::lastChild, and _ShinyNode::nextSibling.
Referenced by ShinyNode_init().
ShinyNode_appendTicks()
SHINY_INLINE void ShinyNode_appendTicks (ShinyNode * self, shinytick_t a_elapsedTicks)
{
  self->_last.selfTicks += a_elapsedTicks;
}
References _ShinyNode::_last, and ShinyLastData::selfTicks.
Referenced by _ShinyManager_appendTicksToCurNode().
ShinyNode_beginEntry()
SHINY_INLINE void ShinyNode_beginEntry (ShinyNode * self)
{
  self->_last.entryCount++;
}
References _ShinyNode::_last, and ShinyLastData::entryCount.
Referenced by ShinyManager_beginNode().
ShinyNode_clear()
SHINY_API void ShinyNode_clear (ShinyNode * self)
Referenced by _ShinyManager_uninit().
ShinyNode_destroy()
SHINY_INLINE void ShinyNode_destroy (ShinyNode * self)
{
  *(self->_cache) = &_ShinyNode_dummy;
}
References _ShinyNode::_cache, and _ShinyNode_dummy.
ShinyNode_enumerateNodes()
SHINY_API void ShinyNode_enumerateNodes (const ShinyNode * a_node, void(*)(const ShinyNode *) a_func)
Referenced by ShinyManager_enumerateNodes().
ShinyNode_findNextInTree()
SHINY_API const ShinyNode * ShinyNode_findNextInTree (const ShinyNode * self)
ShinyNode_init()
SHINY_INLINE void ShinyNode_init (ShinyNode * self, ShinyNode * a_parent, struct _ShinyZone * a_zone, ShinyNodeCache * a_cache)
{
  /* NOTE: all member variables are assumed to be zero when allocated */
  self->zone = a_zone;
  self->parent = a_parent;
  self->entryLevel = a_parent->entryLevel + 1;
  ShinyNode_addChild(a_parent, self);
  self->_cache = a_cache;
}
References _ShinyNode::_cache, _ShinyNode::entryLevel, _ShinyNode::parent, ShinyNode_addChild(), and _ShinyNode::zone.
ShinyNode_isDummy()
SHINY_INLINE int ShinyNode_isDummy (ShinyNode * self)
{
  return (self == &_ShinyNode_dummy);
}
References _ShinyNode_dummy.
ShinyNode_isEqual()
SHINY_INLINE int ShinyNode_isEqual (ShinyNode * self, const ShinyNode * a_parent, const struct _ShinyZone * a_zone)
{
  return (self->parent == a_parent && self->zone == a_zone);
}
References _ShinyNode::parent, and _ShinyNode::zone.
ShinyNode_isRoot()
SHINY_INLINE int ShinyNode_isRoot (ShinyNode * self)
{
  return (self->entryLevel == 0);
}
References _ShinyNode::entryLevel.
ShinyNode_updateTree()
SHINY_API void ShinyNode_updateTree (ShinyNode * self, float a_damping)
ShinyNode_updateTreeClean()
SHINY_API void ShinyNode_updateTreeClean (ShinyNode * self)
Variable Documentation
_ShinyNode_dummy
ShinyNode _ShinyNode_dummy extern
Referenced by ShinyNode_destroy(), and ShinyNode_isDummy().