OrcaSlicer: Clipper2Lib::PolyPath64 Class Reference
Clipper2Lib::PolyPath64 Class Reference
#include <src/clipper2/Clipper2Lib/include/clipper2/clipper.engine.h>
Public Member Functions
PolyPath64 (PolyPath64 *parent=nullptr)
PolyPath64 * operator[] (size_t index)
pp64_itor begin () const
pp64_itor end () const
PolyPath64 * AddChild (const Path64 &path) override
void Clear () override
size_t Count () const override
const Path64 & Polygon () const
double Area () const
unsigned Level () const
const PolyPath * Parent () const
bool IsHole () const
Protected Attributes
PolyPath * parent_
Private Types
typedef std::vector< PolyPath64 * >::const_iterator pp64_itor
Private Attributes
std::vector< PolyPath64 * > childs_
Path64 polygon_
Friends
std::ostream & operator<< (std::ostream &outstream, const PolyPath64 &polypath)
Detailed Description
Member Typedef Documentation
pp64_itor
typedef std::vector<PolyPath64*>::const_iterator Clipper2Lib::PolyPath64::pp64_itor private
Constructor & Destructor Documentation
PolyPath64()
Clipper2Lib::PolyPath64::PolyPath64 (PolyPath64 * parent = nullptr) inline
: PolyPath(parent) {}
Member Function Documentation
AddChild()
PolyPath64 * Clipper2Lib::PolyPath64::AddChild (const Path64 & path) inline override virtual
Implements Clipper2Lib::PolyPath.
    {
      PolyPath64* result = new PolyPath64(this);
      childs_.push_back(result);
      result->polygon_ = path;
      return result;
    }
References childs_, and polygon_.
Area()
double Clipper2Lib::PolyPath64::Area () const inline
    {
      double result = Clipper2Lib::Area<int64_t>(polygon_);
      for (const PolyPath64* child : childs_)
        result += child->Area();
      return result;
    }
References childs_, and polygon_.
begin()
pp64_itor Clipper2Lib::PolyPath64::begin () const inline
{ return childs_.cbegin(); }
References childs_.
Clear()
void Clipper2Lib::PolyPath64::Clear () inline override virtual
Reimplemented from Clipper2Lib::PolyPath.
    {
      for (const PolyPath64* child : childs_) delete child;
      childs_.resize(0);
    }
References childs_.
Referenced by Clipper2Lib::Clipper64::BuildTree64(), and Clipper2Lib::Clipper64::Execute().
Count()
size_t Clipper2Lib::PolyPath64::Count () const inline override virtual
Reimplemented from Clipper2Lib::PolyPath.
    {
      return childs_.size();
    }
References childs_.
Referenced by Clipper2Lib::CreateCPolyTree64(), Clipper2Lib::CreateCPolyTreeD(), Clipper2Lib::InitCPolyPath64(), Clipper2Lib::InitCPolyPathD(), and Clipper2Lib::details::PolyPath64ContainsChildren().
end()
pp64_itor Clipper2Lib::PolyPath64::end () const inline
{ return childs_.cend(); }
References childs_.
IsHole()
bool Clipper2Lib::PolyPath::IsHole () const inline inherited
    {
      const PolyPath* pp = parent_;
      bool is_hole = pp;
      while (pp) {
        is_hole = !is_hole;
        pp = pp->parent_;
      }
      return is_hole;
    }
References Clipper2Lib::PolyPath::parent_.
Level()
unsigned Clipper2Lib::PolyPath::Level () const inline inherited
    {
      unsigned result = 0;
      const PolyPath* p = parent_;
      while (p) { ++result; p = p->parent_; }
      return result;
    }
References Clipper2Lib::PolyPath::parent_.
operator[]()
PolyPath64 * Clipper2Lib::PolyPath64::operator[] (size_t index) inline
{ return static_cast<PolyPath64*>(childs_[index]); }
References childs_.
Parent()
const PolyPath * Clipper2Lib::PolyPath::Parent () const inline inherited
{ return parent_; }
References Clipper2Lib::PolyPath::parent_.
Polygon()
const Path64 & Clipper2Lib::PolyPath64::Polygon () const inline
{ return polygon_; };
References polygon_.
Referenced by Clipper2Lib::InitCPolyPath64(), Clipper2Lib::InitCPolyPathD(), Clipper2Lib::details::PolyPath64ContainsChildren(), and Clipper2Lib::details::PolyPathToPaths64().
Friends And Related Symbol Documentation
operator<<
std::ostream & operator<< (std::ostream & outstream, const PolyPath64 & polypath) friend
    {
      const size_t level_indent = 4;
      const size_t coords_per_line = 4;
      const size_t last_on_line = coords_per_line - 1;
      unsigned level = polypath.Level();
      if (level > 0)
      {
        std::string level_padding;
        level_padding.insert(0, (level - 1) * level_indent, ' ');
        std::string caption = polypath.IsHole() ? "Hole " : "Outer Polygon ";
        std::string childs = polypath.Count() == 1 ? " child" : " children";
        outstream << level_padding.c_str() << caption << "with " << polypath.Count() << childs << std::endl;
        outstream << level_padding;
        size_t i = 0, highI = polypath.Polygon().size() - 1;
        for (; i < highI; ++i)
        {
          outstream << polypath.Polygon()[i] << ' ';
          if ((i % coords_per_line) == last_on_line)
            outstream << std::endl << level_padding;
        }
        if (highI > 0) outstream << polypath.Polygon()[i];
        outstream << std::endl;
      }
      for (auto child : polypath)
        outstream << *child;
      return outstream;
    }
Member Data Documentation
childs_
std::vector<PolyPath64*> Clipper2Lib::PolyPath64::childs_ private
Referenced by AddChild(), Area(), begin(), Clear(), Count(), end(), and operator[]().
parent_
PolyPath* Clipper2Lib::PolyPath::parent_ protected inherited
Referenced by Clipper2Lib::PolyPath::IsHole(), Clipper2Lib::PolyPath::Level(), and Clipper2Lib::PolyPath::Parent().
polygon_
Path64 Clipper2Lib::PolyPath64::polygon_ private
Referenced by AddChild(), Area(), and Polygon().
The documentation for this class was generated from the following file:
src/clipper2/Clipper2Lib/include/clipper2/clipper.engine.h