OrcaSlicer: src/qhull/src/libqhull/mem.c File Reference
mem.c File Reference
#include "user.h"
#include "mem.h"
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
Typedefs
typedef struct ridgeT ridgeT
typedef struct facetT facetT
Functions
void qh_errexit (int exitcode, facetT *, ridgeT *)
void qh_exit (int exitcode)
void qh_fprintf (FILE *fp, int msgcode, const char *fmt,...)
void qh_fprintf_stderr (int msgcode, const char *fmt,...)
void qh_free (void *mem)
void * qh_malloc (size_t size)
static int qh_intcompare (const void *i, const void *j)
void * qh_memalloc (int insize)
void qh_memcheck (void)
void qh_memfree (void *object, int insize)
void qh_memfreeshort (int *curlong, int *totlong)
void qh_meminit (FILE *ferr)
void qh_meminitbuffers (int tracelevel, int alignment, int numsizes, int bufsize, int bufinit)
void qh_memsetup (void)
void qh_memsize (int size)
void qh_memstatistics (FILE *fp)
void qh_memtotal (int *totlong, int *curlong, int *totshort, int *curshort, int *maxlong, int *totbuffer)
Variables
qhmemT qhmem
Typedef Documentation
facetT
typedef struct facetT facetT
ridgeT
typedef struct ridgeT ridgeT
Function Documentation
qh_errexit()
void qh_errexit (int exitcode, facetT * facet, ridgeT * ridge)
{
  if (qh ERREXITcalled) {
    qh_fprintf(qh ferr, 8126, "\nqhull error while processing previous error.  Exit program\n");
    qh_exit(qh_ERRqhull);
  }
  qh ERREXITcalled= True;
  if (!qh QHULLfinished)
    qh hulltime= qh_CPUclock - qh hulltime;
  qh_errprint("ERRONEOUS", facet, NULL, ridge, NULL);
  qh_fprintf(qh ferr, 8127, "\nWhile executing: %s | %s\n", qh rbox_command, qh qhull_command);
  qh_fprintf(qh ferr, 8128, "Options selected for Qhull %s:\n%s\n", qh_version, qh qhull_options);
  if (qh furthest_id >= 0) {
    qh_fprintf(qh ferr, 8129, "Last point added to hull was p%d.", qh furthest_id);
    if (zzval_(Ztotmerge))
      qh_fprintf(qh ferr, 8130, "  Last merge was #%d.", zzval_(Ztotmerge));
    if (qh QHULLfinished)
      qh_fprintf(qh ferr, 8131, "\nQhull has finished constructing the hull.");
    else if (qh POSTmerging)
      qh_fprintf(qh ferr, 8132, "\nQhull has started post-merging.");
    qh_fprintf(qh ferr, 8133, "\n");
  }
  if (qh FORCEoutput && (qh QHULLfinished || (!facet && !ridge)))
    qh_produce_output();
  else if (exitcode != qh_ERRinput) {
    if (exitcode != qh_ERRsingular && zzval_(Zsetplane) > qh hull_dim+1) {
      qh_fprintf(qh ferr, 8134, "\nAt error exit:\n");
      qh_printsummary(qh ferr);
      if (qh PRINTstatistics) {
        qh_collectstatistics();
        qh_printstatistics(qh ferr, "at error exit");
        qh_memstatistics(qh ferr);
      }
    }
    if (qh PRINTprecision)
      qh_printstats(qh ferr, qhstat precision, NULL);
  }
  if (!exitcode)
    exitcode= qh_ERRqhull;
  else if (exitcode == qh_ERRsingular)
    qh_printhelp_singular(qh ferr);
  else if (exitcode == qh_ERRprec && !qh PREmerge)
    qh_printhelp_degenerate(qh ferr);
  if (qh NOerrexit) {
    qh_fprintf(qh ferr, 6187, "qhull error while ending program, or qh->NOerrexit not cleared after setjmp(). Exit program with error.\n");
    qh_exit(qh_ERRqhull);
  }
  qh ERREXITcalled= False;
  qh NOerrexit= True;
  qh ALLOWrestart= False;  /* longjmp will undo qh_build_withrestart */
  longjmp(qh errexit, exitcode);
} /* errexit */
Referenced by qh_memalloc(), qh_memcheck(), qh_meminitbuffers(), qh_memsetup(), and qh_memsize().
qh_exit()
void qh_exit (int exitcode)
{
    exit(exitcode);
} /* exit */
Referenced by qh_memcheck(), and qh_meminit().
qh_fprintf()
void qh_fprintf (FILE * fp, int msgcode, const char * fmt, ...)
{
    va_list args;
    if (!fp) {
        /* could use qhmem.ferr, but probably better to be cautious */
        qh_fprintf_stderr(6232, "Qhull internal error (userprintf.c): fp is 0.  Wrong qh_fprintf called.\n");
        qh_errexit(6232, NULL, NULL);
    }
    va_start(args, fmt);
#if qh_QHpointer
    if (qh_qh && qh ANNOTATEoutput) {
#else
    if (qh ANNOTATEoutput) {
#endif
      fprintf(fp, "[QH%.4d]", msgcode);
    }else if (msgcode >= MSG_ERROR && msgcode < MSG_STDERR ) {
      fprintf(fp, "QH%.4d ", msgcode);
    }
    vfprintf(fp, fmt, args);
    va_end(args);
    /* Place debugging traps here. Use with option 'Tn' */
} /* qh_fprintf */
Referenced by qh_memalloc(), qh_memcheck(), qh_memfree(), qh_meminit(), qh_meminitbuffers(), qh_memsetup(), qh_memsize(), and qh_memstatistics().
qh_fprintf_stderr()
void qh_fprintf_stderr (int msgcode, const char * fmt, ...)
{
    va_list args;
    va_start(args, fmt);
    if(msgcode)
      fprintf(stderr, "QH%.4d ", msgcode);
    vfprintf(stderr, fmt, args);
    va_end(args);
} /* fprintf_stderr */
Referenced by qh_memcheck().
qh_free()
void qh_free (void * mem)
{
    free(mem);
} /* free */
Referenced by qh_memfree(), and qh_memfreeshort().
qh_intcompare()
static int qh_intcompare (const void * i, const void * j) static
{
  return(*((const int *)i) - *((const int *)j));
} /* intcompare */
Referenced by qh_memsetup().
qh_malloc()
void * qh_malloc (size_t size)
{
    return malloc(size);
} /* malloc */
Referenced by qh_memalloc(), and qh_memsetup().
qh_memalloc()
void * qh_memalloc (int insize)
{
  void **freelistp, *newbuffer;
  int idx, size, n;
  int outsize, bufsize;
  void *object;
  if (insize<0) {
      qh_fprintf(qhmem.ferr, 6235, "qhull error (qh_memalloc): negative request size (%d).  Did int overflow due to high-D?\n", insize); /* WARN64 */
      qh_errexit(qhmem_ERRmem, NULL, NULL);
  }
  if (insize>=0 && insize <= qhmem.LASTsize) {
    idx= qhmem.indextable[insize];
    outsize= qhmem.sizetable[idx];
    qhmem.totshort += outsize;
    freelistp= qhmem.freelists+idx;
    if ((object= *freelistp)) {
      qhmem.cntquick++;
      qhmem.totfree -= outsize;
      *freelistp= *((void **)*freelistp);  /* replace freelist with next object */
#ifdef qh_TRACEshort
      n= qhmem.cntshort+qhmem.cntquick+qhmem.freeshort;
      if (qhmem.IStracing >= 5)
          qh_fprintf(qhmem.ferr, 8141, "qh_mem %p n %8d alloc quick: %d bytes (tot %d cnt %d)\n", object, n, outsize, qhmem.totshort, qhmem.cntshort+qhmem.cntquick-qhmem.freeshort);
#endif
      return(object);
    }else {
      qhmem.cntshort++;
      if (outsize > qhmem.freesize) {
        qhmem.totdropped += qhmem.freesize;
        if (!qhmem.curbuffer)
          bufsize= qhmem.BUFinit;
        else
          bufsize= qhmem.BUFsize;
        if (!(newbuffer= qh_malloc((size_t)bufsize))) {
          qh_fprintf(qhmem.ferr, 6080, "qhull error (qh_memalloc): insufficient memory to allocate short memory buffer (%d bytes)\n", bufsize);
          qh_errexit(qhmem_ERRmem, NULL, NULL);
        }
        *((void **)newbuffer)= qhmem.curbuffer;  /* prepend newbuffer to curbuffer
                                                    list.  newbuffer!=0 by QH6080 */
        qhmem.curbuffer= newbuffer;
        size= (sizeof(void **) + qhmem.ALIGNmask) & ~qhmem.ALIGNmask;
        qhmem.freemem= (void *)((char *)newbuffer+size);
        qhmem.freesize= bufsize - size;
        qhmem.totbuffer += bufsize - size; /* easier to check */
        /* Periodically test totbuffer.  It matches at beginning and exit of every call */
        n = qhmem.totshort + qhmem.totfree + qhmem.totdropped + qhmem.freesize - outsize;
        if (qhmem.totbuffer != n) {
            qh_fprintf(qhmem.ferr, 6212, "qh_memalloc internal error: short totbuffer %d != totshort+totfree... %d\n", qhmem.totbuffer, n);
            qh_errexit(qhmem_ERRmem, NULL, NULL);
        }
      }
      object= qhmem.freemem;
      qhmem.freemem= (void *)((char *)qhmem.freemem + outsize);
      qhmem.freesize -= outsize;
      qhmem.totunused += outsize - insize;
#ifdef qh_TRACEshort
      n= qhmem.cntshort+qhmem.cntquick+qhmem.freeshort;
      if (qhmem.IStracing >= 5)
          qh_fprintf(qhmem.ferr, 8140, "qh_mem %p n %8d alloc short: %d bytes (tot %d cnt %d)\n", object, n, outsize, qhmem.totshort, qhmem.cntshort+qhmem.cntquick-qhmem.freeshort);
#endif
      return object;
    }
  }else {                     /* long allocation */
    if (!qhmem.indextable) {
      qh_fprintf(qhmem.ferr, 6081, "qhull internal error (qh_memalloc): qhmem has not been initialized.\n");
      qh_errexit(qhmem_ERRqhull, NULL, NULL);
    }
    outsize= insize;
    qhmem.cntlong++;
    qhmem.totlong += outsize;
    if (qhmem.maxlong < qhmem.totlong)
      qhmem.maxlong= qhmem.totlong;
    if (!(object= qh_malloc((size_t)outsize))) {
      qh_fprintf(qhmem.ferr, 6082, "qhull error (qh_memalloc): insufficient memory to allocate %d bytes\n", outsize);
      qh_errexit(qhmem_ERRmem, NULL, NULL);
    }
    if (qhmem.IStracing >= 5)
      qh_fprintf(qhmem.ferr, 8057, "qh_mem %p n %8d alloc long: %d bytes (tot %d cnt %d)\n", object, qhmem.cntlong+qhmem.freelong, outsize, qhmem.totlong, qhmem.cntlong-qhmem.freelong);
  }
  return(object);
} /* memalloc */
References qhmemT::ALIGNmask, qhmemT::BUFinit, qhmemT::BUFsize, qhmemT::cntlong, qhmemT::cntquick, qhmemT::cntshort, qhmemT::curbuffer, qhmemT::ferr, qhmemT::freelists, qhmemT::freelong, qhmemT::freemem, qhmemT::freeshort, qhmemT::freesize, qhmemT::indextable, qhmemT::IStracing, qhmemT::LASTsize, qhmemT::maxlong, n, NULL, qh_errexit(), qh_fprintf(), qh_malloc(), qhmem, qhmem_ERRmem, qhmem_ERRqhull, size, qhmemT::sizetable, qhmemT::totbuffer, qhmemT::totdropped, qhmemT::totfree, qhmemT::totlong, qhmemT::totshort, and qhmemT::totunused.
Referenced by qh_getcenter(), qh_getcenter(), qh_initqhull_buffers(), qh_initqhull_buffers(), qh_newvertex(), qh_newvertex(), qh_printafacet(), qh_printafacet(), qh_projectinput(), qh_projectinput(), qh_setduplicate(), qh_setduplicate(), qh_setnew(), qh_setnew(), qh_sharpnewfacets(), qh_sharpnewfacets(), qh_triangulate_facet(), qh_triangulate_facet(), qh_voronoi_center(), and qh_voronoi_center().
qh_memcheck()
void qh_memcheck (void)
                       {
  int i, count, totfree= 0;
  void *object;
  if (qhmem.ferr == 0 || qhmem.IStracing < 0 || qhmem.IStracing > 10 || (((qhmem.ALIGNmask+1) & qhmem.ALIGNmask) != 0)) {
    qh_fprintf_stderr(6244, "qh_memcheck error: either qhmem is overwritten or qhmem is not initialized.  Call qh_meminit() or qh_new_qhull() before calling qh_mem routines.  ferr 0x%x IsTracing %d ALIGNmask 0x%x", qhmem.ferr, qhmem.IStracing, qhmem.ALIGNmask);
    qh_exit(qhmem_ERRqhull);  /* can not use qh_errexit() */
  }
  if (qhmem.IStracing != 0)
    qh_fprintf(qhmem.ferr, 8143, "qh_memcheck: check size of freelists on qhmem\nqh_memcheck: A segmentation fault indicates an overwrite of qhmem\n");
  for (i=0; i < qhmem.TABLEsize; i++) {
    count=0;
    for (object= qhmem.freelists[i]; object; object= *((void **)object))
      count++;
    totfree += qhmem.sizetable[i] * count;
  }
  if (totfree != qhmem.totfree) {
    qh_fprintf(qhmem.ferr, 6211, "Qhull internal error (qh_memcheck): totfree %d not equal to freelist total %d\n", qhmem.totfree, totfree);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  if (qhmem.IStracing != 0)
    qh_fprintf(qhmem.ferr, 8144, "qh_memcheck: total size of freelists totfree is the same as qhmem.totfree\n", totfree);
} /* memcheck */
References qhmemT::ALIGNmask, count, qhmemT::ferr, qhmemT::freelists, qhmemT::IStracing, NULL, qh_errexit(), qh_exit(), qh_fprintf(), qh_fprintf_stderr(), qhmem, qhmem_ERRqhull, qhmemT::sizetable, qhmemT::TABLEsize, and qhmemT::totfree.
Referenced by orgQhull::QhullQh::checkAndFreeQhullMemory(), qh_meminit(), qh_meminit(), qh_memstatistics(), qh_memstatistics(), qh_new_qhull(), and qh_new_qhull().
qh_memfree()
void qh_memfree (void * object, int insize)
{
  void **freelistp;
  int idx, outsize;
  if (!object)
    return;
  if (insize <= qhmem.LASTsize) {
    qhmem.freeshort++;
    idx= qhmem.indextable[insize];
    outsize= qhmem.sizetable[idx];
    qhmem.totfree += outsize;
    qhmem.totshort -= outsize;
    freelistp= qhmem.freelists + idx;
    *((void **)object)= *freelistp;
    *freelistp= object;
#ifdef qh_TRACEshort
    idx= qhmem.cntshort+qhmem.cntquick+qhmem.freeshort;
    if (qhmem.IStracing >= 5)
        qh_fprintf(qhmem.ferr, 8142, "qh_mem %p n %8d free short: %d bytes (tot %d cnt %d)\n", object, idx, outsize, qhmem.totshort, qhmem.cntshort+qhmem.cntquick-qhmem.freeshort);
#endif
  }else {
    qhmem.freelong++;
    qhmem.totlong -= insize;
    if (qhmem.IStracing >= 5)
      qh_fprintf(qhmem.ferr, 8058, "qh_mem %p n %8d free long: %d bytes (tot %d cnt %d)\n", object, qhmem.cntlong+qhmem.freelong, insize, qhmem.totlong, qhmem.cntlong-qhmem.freelong);
    qh_free(object);
  }
} /* memfree */
References qhmemT::cntlong, qhmemT::cntquick, qhmemT::cntshort, qhmemT::ferr, qhmemT::freelists, qhmemT::freelong, qhmemT::freeshort, qhmemT::indextable, qhmemT::IStracing, qhmemT::LASTsize, qh_fprintf(), qh_free(), qhmem, qhmemT::sizetable, qhmemT::totfree, qhmemT::totlong, and qhmemT::totshort.
Referenced by qh_attachnewfacets(), qh_attachnewfacets(), qh_checkconvex(), qh_checkconvex(), qh_clearcenters(), qh_clearcenters(), qh_delvertex(), qh_delvertex(), qh_facetarea(), qh_facetarea(), qh_flippedmerges(), qh_flippedmerges(), qh_forcedmerges(), qh_forcedmerges(), qh_freebuffers(), qh_freebuffers(), qh_freebuild(), qh_freebuild(), qh_getcentrum(), qh_getcentrum(), qh_makenew_nonsimplicial(), qh_makenew_nonsimplicial(), qh_merge_degenredundant(), qh_merge_degenredundant(), qh_mergecycle_facets(), qh_mergecycle_facets(), qh_mergesimplex(), qh_mergesimplex(), qh_newvertex(), qh_newvertex(), qh_printafacet(), qh_printafacet(), qh_printcentrum(), qh_printcentrum(), qh_printfacet2geom(), qh_printfacet2geom(), qh_printfacet2geom_points(), qh_printfacet2geom_points(), qh_printfacet2math(), qh_printfacet2math(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_points(), qh_printfacet3geom_points(), qh_printfacet3math(), qh_printfacet3math(), qh_printfacet4geom_nonsimplicial(), qh_printfacet4geom_nonsimplicial(), qh_printfacets(), qh_printfacets(), qh_projectinput(), qh_projectinput(), qh_setfree(), qh_setfree(), qh_setfree2(), qh_setfree2(), qh_setfreelong(), qh_setfreelong(), qh_sharpnewfacets(), qh_sharpnewfacets(), qh_triangulate(), qh_triangulate(), qh_updatetested(), qh_updatetested(), qh_voronoi_center(), and qh_voronoi_center().
qh_memfreeshort()
void qh_memfreeshort (int * curlong, int * totlong)
{
  void *buffer, *nextbuffer;
  FILE *ferr;
  *curlong= qhmem.cntlong - qhmem.freelong;
  *totlong= qhmem.totlong;
  for (buffer= qhmem.curbuffer; buffer; buffer= nextbuffer) {
    nextbuffer= *((void **) buffer);
    qh_free(buffer);
  }
  qhmem.curbuffer= NULL;
  if (qhmem.LASTsize) {
    qh_free(qhmem.indextable);
    qh_free(qhmem.freelists);
    qh_free(qhmem.sizetable);
  }
  ferr= qhmem.ferr;
  memset((char *)&qhmem, 0, sizeof(qhmem));  /* every field is 0, FALSE, NULL */
  qhmem.ferr= ferr;
} /* memfreeshort */
References buffer, qhmemT::cntlong, qhmemT::curbuffer, qhmemT::ferr, qhmemT::freelists, qhmemT::freelong, qhmemT::indextable, qhmemT::LASTsize, memset, NULL, qh_free(), qhmem, qhmemT::sizetable, and qhmemT::totlong.
Referenced by orgQhull::QhullQh::checkAndFreeQhullMemory(), main(), and main().
qh_meminit()
void qh_meminit (FILE * ferr)
{
  memset((char *)&qhmem, 0, sizeof(qhmem));  /* every field is 0, FALSE, NULL */
  if (ferr)
    qhmem.ferr= ferr;
  else
    qhmem.ferr= stderr;
  if (sizeof(void*) < sizeof(int)) {
    qh_fprintf(qhmem.ferr, 6083, "qhull internal error (qh_meminit): sizeof(void*) %d < sizeof(int) %d.  qset.c will not work\n", (int)sizeof(void*), (int)sizeof(int));
    qh_exit(qhmem_ERRqhull);  /* can not use qh_errexit() */
  }
  if (sizeof(void*) > sizeof(ptr_intT)) {
      qh_fprintf(qhmem.ferr, 6084, "qhull internal error (qh_meminit): sizeof(void*) %d > sizeof(ptr_intT) %d. Change ptr_intT in mem.h to 'long long'\n", (int)sizeof(void*), (int)sizeof(ptr_intT));
      qh_exit(qhmem_ERRqhull);  /* can not use qh_errexit() */
  }
  qh_memcheck();
} /* meminit */
References qhmemT::ferr, memset, qh_exit(), qh_fprintf(), qh_memcheck(), qhmem, and qhmem_ERRqhull.
Referenced by orgQhull::QhullQh::QhullQh(), qh_init_A(), qh_init_A(), qh_new_qhull(), qh_new_qhull(), qh_zero(), setupMemory(), and setupMemory().
qh_meminitbuffers()
void qh_meminitbuffers (int tracelevel, int alignment, int numsizes, int bufsize, int bufinit)
{
  qhmem.IStracing= tracelevel;
  qhmem.NUMsizes= numsizes;
  qhmem.BUFsize= bufsize;
  qhmem.BUFinit= bufinit;
  qhmem.ALIGNmask= alignment-1;
  if (qhmem.ALIGNmask & ~qhmem.ALIGNmask) {
    qh_fprintf(qhmem.ferr, 6085, "qhull internal error (qh_meminit): memory alignment %d is not a power of 2\n", alignment);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  qhmem.sizetable= (int *) calloc((size_t)numsizes, sizeof(int));
  qhmem.freelists= (void **) calloc((size_t)numsizes, sizeof(void *));
  if (!qhmem.sizetable || !qhmem.freelists) {
    qh_fprintf(qhmem.ferr, 6086, "qhull error (qh_meminit): insufficient memory\n");
    qh_errexit(qhmem_ERRmem, NULL, NULL);
  }
  if (qhmem.IStracing >= 1)
    qh_fprintf(qhmem.ferr, 8059, "qh_meminitbuffers: memory initialized with alignment %d\n", alignment);
} /* meminitbuffers */
References qhmemT::ALIGNmask, qhmemT::BUFinit, qhmemT::BUFsize, qhmemT::ferr, qhmemT::freelists, int, qhmemT::IStracing, NULL, qhmemT::NUMsizes, qh_errexit(), qh_fprintf(), qhmem, qhmem_ERRmem, qhmem_ERRqhull, and qhmemT::sizetable.
Referenced by qh_initqhull_mem(), qh_initqhull_mem(), setupMemory(), and setupMemory().
qh_memsetup()
void qh_memsetup (void)
                       {
  int k,i;
  qsort(qhmem.sizetable, (size_t)qhmem.TABLEsize, sizeof(int), qh_intcompare);
  qhmem.LASTsize= qhmem.sizetable[qhmem.TABLEsize-1];
  if (qhmem.LASTsize >= qhmem.BUFsize || qhmem.LASTsize >= qhmem.BUFinit) {
    qh_fprintf(qhmem.ferr, 6087, "qhull error (qh_memsetup): largest mem size %d is >= buffer size %d or initial buffer size %d\n",
            qhmem.LASTsize, qhmem.BUFsize, qhmem.BUFinit);
    qh_errexit(qhmem_ERRmem, NULL, NULL);
  }
  if (!(qhmem.indextable= (int *)qh_malloc((qhmem.LASTsize+1) * sizeof(int)))) {
    qh_fprintf(qhmem.ferr, 6088, "qhull error (qh_memsetup): insufficient memory\n");
    qh_errexit(qhmem_ERRmem, NULL, NULL);
  }
  for (k=qhmem.LASTsize+1; k--; )
    qhmem.indextable[k]= k;
  i= 0;
  for (k=0; k <= qhmem.LASTsize; k++) {
    if (qhmem.indextable[k] <= qhmem.sizetable[i])
      qhmem.indextable[k]= i;
    else
      qhmem.indextable[k]= ++i;
  }
} /* memsetup */
References qhmemT::BUFinit, qhmemT::BUFsize, qhmemT::ferr, qhmemT::indextable, qhmemT::LASTsize, NULL, qh_errexit(), qh_fprintf(), qh_intcompare(), qh_malloc(), qhmem, qhmem_ERRmem, qhmemT::sizetable, and qhmemT::TABLEsize.
Referenced by qh_initqhull_mem(), qh_initqhull_mem(), setupMemory(), and setupMemory().
qh_memsize()
void qh_memsize (int size)
{
  int k;
  if (qhmem.LASTsize) {
    qh_fprintf(qhmem.ferr, 6089, "qhull error (qh_memsize): called after qhmem_setup\n");
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  size= (size + qhmem.ALIGNmask) & ~qhmem.ALIGNmask;
  for (k=qhmem.TABLEsize; k--; ) {
    if (qhmem.sizetable[k] == size)
      return;
  }
  if (qhmem.TABLEsize < qhmem.NUMsizes)
    qhmem.sizetable[qhmem.TABLEsize++]= size;
  else
    qh_fprintf(qhmem.ferr, 7060, "qhull warning (memsize): free list table has room for only %d sizes\n", qhmem.NUMsizes);
} /* memsize */
References qhmemT::ALIGNmask, qhmemT::ferr, qhmemT::LASTsize, NULL, qhmemT::NUMsizes, qh_errexit(), qh_fprintf(), qhmem, qhmem_ERRqhull, size, qhmemT::sizetable, and qhmemT::TABLEsize.
Referenced by qh_initqhull_mem(), qh_initqhull_mem(), setupMemory(), and setupMemory().
qh_memstatistics()
void qh_memstatistics (FILE * fp)
{
  int i;
  int count;
  void *object;
  qh_memcheck();
  qh_fprintf(fp, 9278, "\nmemory statistics:\n\
%7d quick allocations\n\
%7d short allocations\n\
%7d long allocations\n\
%7d short frees\n\
%7d long frees\n\
%7d bytes of short memory in use\n\
%7d bytes of short memory in freelists\n\
%7d bytes of dropped short memory\n\
%7d bytes of unused short memory (estimated)\n\
%7d bytes of long memory allocated (max, except for input)\n\
%7d bytes of long memory in use (in %d pieces)\n\
%7d bytes of short memory buffers (minus links)\n\
%7d bytes per short memory buffer (initially %d bytes)\n",
           qhmem.cntquick, qhmem.cntshort, qhmem.cntlong,
           qhmem.freeshort, qhmem.freelong,
           qhmem.totshort, qhmem.totfree,
           qhmem.totdropped + qhmem.freesize, qhmem.totunused,
           qhmem.maxlong, qhmem.totlong, qhmem.cntlong - qhmem.freelong,
           qhmem.totbuffer, qhmem.BUFsize, qhmem.BUFinit);
  if (qhmem.cntlarger) {
    qh_fprintf(fp, 9279, "%7d calls to qh_setlarger\n%7.2g     average copy size\n",
           qhmem.cntlarger, ((float)qhmem.totlarger)/(float)qhmem.cntlarger);
    qh_fprintf(fp, 9280, "  freelists(bytes->count):");
  }
  for (i=0; i < qhmem.TABLEsize; i++) {
    count=0;
    for (object= qhmem.freelists[i]; object; object= *((void **)object))
      count++;
    qh_fprintf(fp, 9281, " %d->%d", qhmem.sizetable[i], count);
  }
  qh_fprintf(fp, 9282, "\n\n");
} /* memstatistics */
References qhmemT::BUFinit, qhmemT::BUFsize, qhmemT::cntlarger, qhmemT::cntlong, qhmemT::cntquick, qhmemT::cntshort, count, qhmemT::freelists, qhmemT::freelong, qhmemT::freeshort, qhmemT::freesize, qhmemT::maxlong, qh_fprintf(), qh_memcheck(), qhmem, qhmemT::sizetable, qhmemT::TABLEsize, qhmemT::totbuffer, qhmemT::totdropped, qhmemT::totfree, qhmemT::totlarger, qhmemT::totlong, qhmemT::totshort, and qhmemT::totunused.
Referenced by main(), qh_errexit(), qh_errexit(), qh_produce_output2(), and qh_produce_output2().
qh_memtotal()
void qh_memtotal (int * totlong, int * curlong, int * totshort, int * curshort, int * maxlong, int * totbuffer)
{
    *totlong= qhmem.totlong;
    *curlong= qhmem.cntlong - qhmem.freelong;
    *totshort= qhmem.totshort;
    *curshort= qhmem.cntshort + qhmem.cntquick - qhmem.freeshort;
    *maxlong= qhmem.maxlong;
    *totbuffer= qhmem.totbuffer;
} /* memtotlong */
References qhmemT::cntlong, qhmemT::cntquick, qhmemT::cntshort, qhmemT::freelong, qhmemT::freeshort, qhmemT::maxlong, qhmem, qhmemT::totbuffer, qhmemT::totlong, and qhmemT::totshort.
Variable Documentation
qhmem
qhmemT qhmem
Initial value:
= {0,0,0,0,0,0,0,0,0,0,0,
               0,0,0,0,0,0,0,0,0,0,0,
               0,0,0,0,0,0,0}
Referenced by qh_build_withrestart(), qh_buildtracing(), qh_flippedmerges(), qh_forcedmerges(), qh_init_B(), qh_initflags(), qh_initqhull_buffers(), qh_initstatistics(), qh_memalloc(), qh_memalloc(), qh_memcheck(), qh_memfree(), qh_memfree(), qh_memfreeshort(), qh_meminit(), qh_meminitbuffers(), qh_memsetup(), qh_memsize(), qh_memstatistics(), qh_memtotal(), qh_merge_degenredundant(), qh_merge_nonconvex(), qh_mergecycle(), qh_newhashtable(), qh_produce_output(), qh_produce_output2(), qh_qhull(), qh_setaddnth(), qh_setcheck(), qh_setdelnth(), qh_setdelnthsorted(), qh_setfree(), qh_setfree(), qh_setfreelong(), qh_setlarger(), qh_setnew(), qh_setnew(), qh_setnew_delnthsorted(), qh_setreplace(), qh_setsize(), qh_settemp(), qh_settempfree(), qh_settempfree_all(), qh_settemppop(), qh_settemppush(), qh_settruncate(), and qh_setzero().