OrcaSlicer: thread_safe_queue< T > Class Template Reference
thread_safe_queue< T > Class Template Reference
#include <src/mcut/include/mcut/internal/tpool.h>
Classes
struct node
Public Member Functions
thread_safe_queue ()
thread_safe_queue (const thread_safe_queue &other)=delete
thread_safe_queue & operator= (const thread_safe_queue &other)=delete
void set_done_ptr (std::atomic< bool > *done)
void disrupt_wait_for_data ()
void notify_one ()
void push (T new_value)
void wait_and_pop (T &value)
bool try_pop (T &value)
bool empty ()
Private Member Functions
std::unique_ptr< node > try_pop_head (T &value)
node * get_tail ()
std::unique_ptr< node > pop_head ()
std::unique_lock< std::mutex > wait_for_data ()
std::unique_ptr< node > wait_pop_head (T &value)
Private Attributes
std::atomic< bool > * m_done
std::mutex head_mutex
std::unique_ptr< node > head
std::mutex tail_mutex
node * tail
std::condition_variable data_cond
Detailed Description
template<typename T>
class thread_safe_queue< T >
Class Documentation
thread_safe_queue::node
struct thread_safe_queue::node
template<typename T>
struct thread_safe_queue< T >::node
Class Members
shared_ptr< T > data
unique_ptr< node > next
Constructor & Destructor Documentation
thread_safe_queue() [1/2]
template<typename T > thread_safe_queue< T >::thread_safe_queue () inline
        :  head(new node)
        , tail(head.get()) /*, can_wait_for_data(true)*/
    {
    }
thread_safe_queue() [2/2]
template<typename T > thread_safe_queue< T >::thread_safe_queue (const thread_safe_queue< T > & other) delete
Member Function Documentation
disrupt_wait_for_data()
template<typename T > void thread_safe_queue< T >::disrupt_wait_for_data () inline
    {
        // https://stackoverflow.com/questions/60658842/condition-variable-doesnt-get-notified-to-wake-up-even-with-a-predicate
        //
        // Need to this to prevent data race, which can happen when user-app thread
        // is too slow to reach this function i.e. that an API/context/device thread
        // waits on the condition variable AFTER the client thread calls notify_one()
        std::unique_lock<std::mutex> lock(head_mutex);
        data_cond.notify_one();
    }
References thread_safe_queue< T >::data_cond, and thread_safe_queue< T >::head_mutex.
empty()
template<typename T > bool thread_safe_queue< T >::empty () inline
    {
        std::lock_guard<std::mutex> head_lock(head_mutex);
        return (head.get() == get_tail());
    }
References thread_safe_queue< T >::get_tail(), thread_safe_queue< T >::head, and thread_safe_queue< T >::head_mutex.
get_tail()
template<typename T > node * thread_safe_queue< T >::get_tail () inline private
    {
        std::lock_guard<std::mutex> tail_lock(tail_mutex);
        return tail;
    }
References thread_safe_queue< T >::tail, and thread_safe_queue< T >::tail_mutex.
Referenced by thread_safe_queue< T >::empty(), thread_safe_queue< T >::try_pop_head(), and thread_safe_queue< T >::wait_for_data().
notify_one()
template<typename T > void thread_safe_queue< T >::notify_one () inline
    {
        data_cond.notify_one();
    }
References thread_safe_queue< T >::data_cond.
operator=()
template<typename T > thread_safe_queue & thread_safe_queue< T >::operator= (const thread_safe_queue< T > & other) delete
pop_head()
template<typename T > std::unique_ptr< node > thread_safe_queue< T >::pop_head () inline private
    {
        std::unique_ptr<node> old_head = std::move(head);
        head = std::move(old_head->next);
        return (old_head);
    }
References thread_safe_queue< T >::head.
Referenced by thread_safe_queue< T >::try_pop_head(), and thread_safe_queue< T >::wait_pop_head().
push()
template<typename T > void thread_safe_queue< T >::push (T new_value) inline
    {
        std::shared_ptr<T> new_data(std::make_shared<T>(std::move(new_value)));
        std::unique_ptr<node> p(new node);
        {
            std::lock_guard<std::mutex> tail_lock(tail_mutex);
            tail->data = new_data;
            node* const new_tail = p.get();
            tail->next = std::move(p);
            tail = new_tail;
        }
        data_cond.notify_one();
    }
References thread_safe_queue< T >::node::data, thread_safe_queue< T >::data_cond, thread_safe_queue< T >::node::next, thread_safe_queue< T >::tail, and thread_safe_queue< T >::tail_mutex.
set_done_ptr()
template<typename T > void thread_safe_queue< T >::set_done_ptr (std::atomic< bool > * done) inline
    {
        m_done = done;
    }
References thread_safe_queue< T >::m_done.
try_pop()
template<typename T > bool thread_safe_queue< T >::try_pop (T & value) inline
    {
        std::unique_ptr<node> const old_head = try_pop_head(value);
        return !(!(old_head)); // https://stackoverflow.com/questions/30521849/error-on-implicit-cast-from-stdunique-ptr-to-bool
    }
References thread_safe_queue< T >::try_pop_head().
try_pop_head()
template<typename T > std::unique_ptr< node > thread_safe_queue< T >::try_pop_head (T & value) inline private
    {
        std::lock_guard<std::mutex> head_lock(head_mutex);
        if (head.get() == get_tail()) {
            return std::unique_ptr<node>(nullptr);
        }
        value = std::move(*head->data);
        return pop_head();
    }
References thread_safe_queue< T >::get_tail(), thread_safe_queue< T >::head, thread_safe_queue< T >::head_mutex, and thread_safe_queue< T >::pop_head().
Referenced by thread_safe_queue< T >::try_pop().
wait_and_pop()
template<typename T > void thread_safe_queue< T >::wait_and_pop (T & value) inline
    {
        std::unique_ptr<node> const old_head = wait_pop_head(value);
    }
References thread_safe_queue< T >::wait_pop_head().
wait_for_data()
template<typename T > std::unique_lock< std::mutex > thread_safe_queue< T >::wait_for_data () inline private
    {
        std::unique_lock<std::mutex> head_lock(head_mutex);
        auto until = [&]() { return m_done->load() || head.get() != get_tail(); };
        data_cond.wait(head_lock, until);
        return head_lock;
    }
References thread_safe_queue< T >::data_cond, thread_safe_queue< T >::get_tail(), thread_safe_queue< T >::head, thread_safe_queue< T >::head_mutex, and thread_safe_queue< T >::m_done.
Referenced by thread_safe_queue< T >::wait_pop_head().
wait_pop_head()
template<typename T > std::unique_ptr< node > thread_safe_queue< T >::wait_pop_head (T & value) inline private
    {
        std::unique_lock<std::mutex> head_lock(wait_for_data());
        if (m_done->load() == false) {
            value = std::move(*head->data);
            return pop_head();
        } else {
            return std::unique_ptr<node>(nullptr);
        }
    }
References thread_safe_queue< T >::head, thread_safe_queue< T >::m_done, thread_safe_queue< T >::pop_head(), and thread_safe_queue< T >::wait_for_data().
Referenced by thread_safe_queue< T >::wait_and_pop().
Member Data Documentation
data_cond
template<typename T > std::condition_variable thread_safe_queue< T >::data_cond private
Referenced by thread_safe_queue< T >::disrupt_wait_for_data(), thread_safe_queue< T >::notify_one(), thread_safe_queue< T >::push(), and thread_safe_queue< T >::wait_for_data().
head
template<typename T > std::unique_ptr<node> thread_safe_queue< T >::head private
Referenced by thread_safe_queue< T >::empty(), thread_safe_queue< T >::pop_head(), thread_safe_queue< T >::try_pop_head(), thread_safe_queue< T >::wait_for_data(), and thread_safe_queue< T >::wait_pop_head().
head_mutex
template<typename T > std::mutex thread_safe_queue< T >::head_mutex private
Referenced by thread_safe_queue< T >::disrupt_wait_for_data(), thread_safe_queue< T >::empty(), thread_safe_queue< T >::try_pop_head(), and thread_safe_queue< T >::wait_for_data().
m_done
template<typename T > std::atomic<bool>* thread_safe_queue< T >::m_done private
Referenced by thread_safe_queue< T >::set_done_ptr(), thread_safe_queue< T >::wait_for_data(), and thread_safe_queue< T >::wait_pop_head().
tail
template<typename T > node* thread_safe_queue< T >::tail private
Referenced by thread_safe_queue< T >::get_tail(), and thread_safe_queue< T >::push().
tail_mutex
template<typename T > std::mutex thread_safe_queue< T >::tail_mutex private
Referenced by thread_safe_queue< T >::get_tail(), and thread_safe_queue< T >::push().
The documentation for this class was generated from the following file:
src/mcut/include/mcut/internal/tpool.h