OrcaSlicer: Slic3r::GUI::GizmoObjectManipulation Class Reference
Slic3r::GUI::GizmoObjectManipulation Class Reference
#include <src/slic3r/GUI/Gizmos/GizmoObjectManipulation.hpp>
Classes
struct Cache
Public Member Functions
GizmoObjectManipulation (GLCanvas3D &glcanvas)
~GizmoObjectManipulation ()
bool IsShown ()
void UpdateAndShow (const bool show)
void update_ui_from_settings ()
void set_dirty ()
void update_if_dirty ()
void set_uniform_scaling (const bool uniform_scale)
bool get_uniform_scaling () const
void set_world_coordinates (const bool world_coordinates)
bool get_world_coordinates () const
void reset_cache ()
void on_change (const std::string &opt_key, int axis, double new_value)
void do_render_move_window (ImGuiWrapper *imgui_wrapper, std::string window_name, float x, float y, float bottom_limit)
void do_render_rotate_window (ImGuiWrapper *imgui_wrapper, std::string window_name, float x, float y, float bottom_limit)
void do_render_scale_input_window (ImGuiWrapper *imgui_wrapper, std::string window_name, float x, float y, float bottom_limit)
float max_unit_size (int number, Vec3d &vec1, Vec3d &vec2, std::string str)
bool reset_button (ImGuiWrapper *imgui_wrapper, float caption_max, float unit_size, float space_size, float end_text_size)
Public Attributes
Cache m_cache
bool m_imperial_units { false }
bool m_dirty = false
std::string m_new_title_string
std::string m_new_move_label_string
std::string m_new_rotate_label_string
std::string m_new_scale_label_string
std::string m_new_unit_string
Vec3d m_new_position
Vec3d m_new_rotation
Vec3d m_new_scale
Vec3d m_new_size
Vec3d m_buffered_position
Vec3d m_buffered_rotation
Vec3d m_buffered_scale
Vec3d m_buffered_size
bool m_new_enabled {true}
bool m_uniform_scale {true}
bool m_world_coordinates = true
bool m_show_clear_rotation { false }
bool m_show_clear_scale { false }
bool m_show_drop_to_bed { false }
Static Public Attributes
static const double in_to_mm = 25.4
static const double mm_to_in = 0.0393700787
static const double g_to_oz = 0.035274
static const double oz_to_g = 28.34952
Protected Attributes
float last_move_input_window_width = 0.0f
float last_rotate_input_window_width = 0.0f
float last_scale_input_window_width = 0.0f
Private Member Functions
void reset_settings_value ()
void update_settings_value (const Selection &selection)
void update_buffered_value ()
void update_reset_buttons_visibility ()
void change_position_value (int axis, double value)
void change_rotation_value (int axis, double value)
void change_scale_value (int axis, double value)
void change_size_value (int axis, double value)
void do_scale (int axis, const Vec3d &scale) const
void reset_position_value ()
void reset_rotation_value ()
void reset_scale_value ()
Private Attributes
GLCanvas3D & m_glcanvas
unsigned int m_last_active_item { 0 }
Detailed Description
Constructor & Destructor Documentation
GizmoObjectManipulation()
Slic3r::GUI::GizmoObjectManipulation::GizmoObjectManipulation (GLCanvas3D & glcanvas)
    : m_glcanvas(glcanvas)
{
    m_imperial_units = wxGetApp().app_config->get("use_inches") == "1";
    m_new_unit_string = m_imperial_units ? L("in") : L("mm");
}
References L, m_imperial_units, and m_new_unit_string.
~GizmoObjectManipulation()
Slic3r::GUI::GizmoObjectManipulation::~GizmoObjectManipulation () inline
{}
Member Function Documentation
change_position_value()
void Slic3r::GUI::GizmoObjectManipulation::change_position_value (int axis, double value) private
{
    if (std::abs(m_cache.position_rounded(axis) - value) < EPSILON)
        return;
    Vec3d position = m_cache.position;
    position(axis) = value;
    Selection& selection = m_glcanvas.get_selection();
    selection.start_dragging();
    selection.translate(position - m_cache.position, selection.requires_local_axes());
    m_glcanvas.do_move(L("Set Position"));
    m_cache.position = position;
  m_cache.position_rounded(axis) = DBL_MAX;
    this->UpdateAndShow(true);
}
References Slic3r::GUI::GLCanvas3D::do_move(), EPSILON, Slic3r::GUI::GLCanvas3D::get_selection(), L, m_cache, m_glcanvas, Slic3r::GUI::GizmoObjectManipulation::Cache::position, Slic3r::GUI::GizmoObjectManipulation::Cache::position_rounded, Slic3r::GUI::Selection::requires_local_axes(), Slic3r::GUI::Selection::start_dragging(), Slic3r::GUI::Selection::translate(), and UpdateAndShow().
Referenced by on_change().
change_rotation_value()
void Slic3r::GUI::GizmoObjectManipulation::change_rotation_value (int axis, double value) private
{
    if (std::abs(m_cache.rotation_rounded(axis) - value) < EPSILON)
        return;
    Vec3d rotation = m_cache.rotation;
    rotation(axis) = value;
    Selection& selection = m_glcanvas.get_selection();
    TransformationType transformation_type(TransformationType::World_Relative_Joint);
    if (selection.is_single_full_instance() || selection.requires_local_axes())
    transformation_type.set_independent();
  if (selection.is_single_full_instance() && ! m_world_coordinates) {
        //FIXME Selection::rotate() does not process absoulte rotations correctly: It does not recognize the axis index, which was changed.
    // transformation_type.set_absolute();
    transformation_type.set_local();
  }
    selection.start_dragging();
  selection.rotate(
    (M_PI / 180.0) * (transformation_type.absolute() ? rotation : rotation - m_cache.rotation),
    transformation_type);
    m_glcanvas.do_rotate(L("Set Orientation"));
    m_cache.rotation = rotation;
  m_cache.rotation_rounded(axis) = DBL_MAX;
    this->UpdateAndShow(true);
}
References Slic3r::GUI::TransformationType::absolute(), Slic3r::GUI::GLCanvas3D::do_rotate(), EPSILON, Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_single_full_instance(), L, m_cache, m_glcanvas, M_PI, m_world_coordinates, Slic3r::GUI::Selection::requires_local_axes(), Slic3r::GUI::Selection::rotate(), Slic3r::GUI::GizmoObjectManipulation::Cache::rotation, Slic3r::GUI::GizmoObjectManipulation::Cache::rotation_rounded, Slic3r::GUI::TransformationType::set_independent(), Slic3r::GUI::TransformationType::set_local(), Slic3r::GUI::Selection::start_dragging(), UpdateAndShow(), and Slic3r::GUI::TransformationType::World_Relative_Joint.
Referenced by on_change().
change_scale_value()
void Slic3r::GUI::GizmoObjectManipulation::change_scale_value (int axis, double value) private
{
    if (std::abs(m_cache.scale_rounded(axis) - value) < EPSILON)
        return;
    Vec3d scale = m_cache.scale;
    if (scale[axis] != 0 && std::abs(m_cache.size[axis] * value / scale[axis]) > MAX_NUM) {
        scale[axis] *= MAX_NUM / m_cache.size[axis];
    }
    else {
        scale(axis) = value;
    }
    this->do_scale(axis, scale);
    m_cache.scale = scale;
  m_cache.scale_rounded(axis) = DBL_MAX;
  this->UpdateAndShow(true);
}
References do_scale(), EPSILON, m_cache, MAX_NUM, Slic3r::GUI::GizmoObjectManipulation::Cache::scale, scale(), Slic3r::GUI::GizmoObjectManipulation::Cache::scale_rounded, Slic3r::GUI::GizmoObjectManipulation::Cache::size, and UpdateAndShow().
Referenced by on_change(), and reset_scale_value().
change_size_value()
void Slic3r::GUI::GizmoObjectManipulation::change_size_value (int axis, double value) private
{
    if (std::abs(m_cache.size_rounded(axis) - value) < EPSILON)
        return;
    Vec3d size = m_cache.size;
    size(axis) = value;
    const Selection& selection = m_glcanvas.get_selection();
    Vec3d ref_size = m_cache.size;
    if (selection.is_single_volume() || selection.is_single_modifier()) {
        Vec3d instance_scale = wxGetApp().model().objects[selection.get_volume(*selection.get_volume_idxs().begin())->object_idx()]->instances[0]->get_transformation().get_scaling_factor();
        ref_size = selection.get_volume(*selection.get_volume_idxs().begin())->bounding_box().size();
        ref_size = Vec3d(instance_scale[0] * ref_size[0], instance_scale[1] * ref_size[1], instance_scale[2] * ref_size[2]);
    }
    else if (selection.is_single_full_instance())
    ref_size = m_world_coordinates ?
            selection.get_unscaled_instance_bounding_box().size() :
            wxGetApp().model().objects[selection.get_volume(*selection.get_volume_idxs().begin())->object_idx()]->raw_mesh_bounding_box().size();
    this->do_scale(axis, 100. * Vec3d(size(0) / ref_size(0), size(1) / ref_size(1), size(2) / ref_size(2)));
    m_cache.size = size;
  m_cache.size_rounded(axis) = DBL_MAX;
  this->UpdateAndShow(true);
}
References Slic3r::GLVolume::bounding_box(), do_scale(), EPSILON, Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_unscaled_instance_bounding_box(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_modifier(), Slic3r::GUI::Selection::is_single_volume(), m_cache, m_glcanvas, m_world_coordinates, Slic3r::GLVolume::object_idx(), Slic3r::BoundingBox3Base< PointClass >::size(), size, Slic3r::GUI::GizmoObjectManipulation::Cache::size, Slic3r::GUI::GizmoObjectManipulation::Cache::size_rounded, and UpdateAndShow().
Referenced by on_change().
do_render_move_window()
void Slic3r::GUI::GizmoObjectManipulation::do_render_move_window (ImGuiWrapper * imgui_wrapper, std::string window_name, float x, float y, float bottom_limit)
{
    // BBS: GUI refactor: move gizmo to the right
    if (abs(last_move_input_window_width) > 0.01f) {
        if (x + last_move_input_window_width > m_glcanvas.get_canvas_size().get_width()) {
            if (last_move_input_window_width > m_glcanvas.get_canvas_size().get_width())
                x = 0;
            else
                x = m_glcanvas.get_canvas_size().get_width() - last_move_input_window_width;
        }
    }
#if BBS_TOOLBAR_ON_TOP
    imgui_wrapper->set_next_window_pos(x, y, ImGuiCond_Always, 0.f, 0.0f);
#else
    imgui_wrapper->set_next_window_pos(x, y, ImGuiCond_Always, 1.0f, 0.0f);
#endif
    // BBS
    ImGuiWrapper::push_toolbar_style(m_glcanvas.get_scale());
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0, 6.0));
    std::string name = this->m_new_title_string + "##" + window_name;
    imgui_wrapper->begin(_L(name), ImGuiWrapper::TOOLBAR_WINDOW_FLAGS);
    auto update = [this](unsigned int active_id, std::string opt_key, Vec3d original_value, Vec3d new_value) -> int {
        for (int i = 0; i < 3; i++) {
            if (original_value[i] != new_value[i]) {
                if (active_id != m_last_active_item) {
                    on_change(opt_key, i, new_value[i]);
                    return i;
                }
            }
        }
        return -1;
    };
    float space_size    = imgui_wrapper->get_style_scaling() * 8;
    float position_size = imgui_wrapper->calc_text_size(_L("Position")).x + space_size;
    float World_size    = imgui_wrapper->calc_text_size(_L("World coordinates")).x + space_size;
    float caption_max   = std::max(position_size, World_size) + 2 * space_size;
    float end_text_size = imgui_wrapper->calc_text_size(this->m_new_unit_string).x;
    // position
    Vec3d original_position;
    if (this->m_imperial_units)
        original_position = this->m_new_position * this->mm_to_in;
    else
        original_position = this->m_new_position;
    Vec3d display_position = m_buffered_position;
    // Rotation
    Vec3d rotation   = this->m_buffered_rotation;
    float unit_size = imgui_wrapper->calc_text_size(MAX_SIZE).x + space_size;
    int   index      = 1;
    int   index_unit = 1;
    ImGui::AlignTextToFramePadding();
    unsigned int current_active_id = ImGui::GetActiveID();
    ImGui::PushItemWidth(caption_max);
    imgui_wrapper->text(_L("World coordinates"));
    ImGui::SameLine(caption_max + index * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("X");
    ImGui::SameLine(caption_max + unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("Y");
    ImGui::SameLine(caption_max + (++index_unit) * unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("Z");
    index      = 1;
    index_unit = 1;
    ImGui::AlignTextToFramePadding();
    imgui_wrapper->text(_L("Position"));
    ImGui::SameLine(caption_max + index * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_values[0][0], &display_position[0], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_values[0][1], &display_position[1], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + (++index_unit) * unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_values[0][2], &display_position[2], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + (++index_unit) * unit_size + (++index) * space_size);
    imgui_wrapper->text(this->m_new_unit_string);
    for (int i = 0;i<display_position.size();i++)
    {
        if (display_position[i] > MAX_NUM)display_position[i] = MAX_NUM;
        if (display_position[i] < -MAX_NUM)display_position[i] = -MAX_NUM;
    }
    m_buffered_position = display_position;
    update(current_active_id, "position", original_position, m_buffered_position);
    // the init position values are not zero, won't add reset button
    // send focus to m_glcanvas
    bool focued_on_text = false;
    for (int j = 0; j < 3; j++) {
        unsigned int id = ImGui::GetID(label_values[0][j]);
        if (current_active_id == id) {
            m_glcanvas.handle_sidebar_focus_event(label_values[0][j] + 2, true);
            focued_on_text = true;
            break;
        }
    }
    if (!focued_on_text) m_glcanvas.handle_sidebar_focus_event("", false);
    m_last_active_item = current_active_id;
    last_move_input_window_width = ImGui::GetWindowWidth();
    imgui_wrapper->end();
    ImGui::PopStyleVar(1);
    ImGuiWrapper::pop_toolbar_style();
}
References _L, ImGui::AlignTextToFramePadding(), ImGui::BBLInputDouble(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::GLCanvas3D::get_scale(), Slic3r::GUI::ImGuiWrapper::get_style_scaling(), Slic3r::GUI::Size::get_width(), ImGui::GetActiveID(), ImGui::GetID(), ImGui::GetWindowWidth(), Slic3r::GUI::GLCanvas3D::handle_sidebar_focus_event(), ImGuiCond_Always, ImGuiStyleVar_ItemSpacing, Slic3r::GUI::label_values, last_move_input_window_width, m_buffered_position, m_buffered_rotation, m_glcanvas, m_imperial_units, m_last_active_item, m_new_position, m_new_title_string, m_new_unit_string, MAX_NUM, MAX_SIZE, mm_to_in, on_change(), Slic3r::GUI::ImGuiWrapper::pop_toolbar_style(), ImGui::PopStyleVar(), Slic3r::GUI::ImGuiWrapper::push_toolbar_style(), ImGui::PushItemWidth(), ImGui::PushStyleVar(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::ImGuiWrapper::text(), ImGui::TextAlignCenter(), Slic3r::GUI::ImGuiWrapper::TOOLBAR_WINDOW_FLAGS, and ImVec2::x.
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render_input_window().
do_render_rotate_window()
void Slic3r::GUI::GizmoObjectManipulation::do_render_rotate_window (ImGuiWrapper * imgui_wrapper, std::string window_name, float x, float y, float bottom_limit)
{
    // BBS: GUI refactor: move gizmo to the right
    if (abs(last_rotate_input_window_width) > 0.01f) {
        if (x + last_rotate_input_window_width > m_glcanvas.get_canvas_size().get_width()) {
            if (last_rotate_input_window_width > m_glcanvas.get_canvas_size().get_width())
                x = 0;
            else
                x = m_glcanvas.get_canvas_size().get_width() - last_rotate_input_window_width;
        }
    }
#if BBS_TOOLBAR_ON_TOP
    imgui_wrapper->set_next_window_pos(x, y, ImGuiCond_Always, 0.f, 0.0f);
#else
    imgui_wrapper->set_next_window_pos(x, y, ImGuiCond_Always, 1.0f, 0.0f);
#endif
    // BBS
    ImGuiWrapper::push_toolbar_style(m_glcanvas.get_scale());
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0, 6.0));
    std::string name = this->m_new_title_string + "##" + window_name;
    imgui_wrapper->begin(_L(name), ImGuiWrapper::TOOLBAR_WINDOW_FLAGS);
    auto update = [this](unsigned int active_id, std::string opt_key, Vec3d original_value, Vec3d new_value) -> int {
        for (int i = 0; i < 3; i++) {
            if (original_value[i] != new_value[i]) {
                if (active_id != m_last_active_item) {
                    on_change(opt_key, i, new_value[i]);
                    return i;
                }
            }
        }
        return -1;
    };
    float space_size    = imgui_wrapper->get_style_scaling() * 8;
    float position_size = imgui_wrapper->calc_text_size(_L("Rotation")).x + space_size;
    float World_size    = imgui_wrapper->calc_text_size(_L("World coordinates")).x + space_size;
    float caption_max   = std::max(position_size, World_size) + 2 * space_size;
    float end_text_size = imgui_wrapper->calc_text_size(this->m_new_unit_string).x;
    // position
    Vec3d original_position;
    if (this->m_imperial_units)
        original_position = this->m_new_position * this->mm_to_in;
    else
        original_position = this->m_new_position;
    Vec3d display_position = m_buffered_position;
    // Rotation
    Vec3d rotation   = this->m_buffered_rotation;
    float unit_size = imgui_wrapper->calc_text_size(MAX_SIZE).x + space_size;
    int   index      = 1;
    int   index_unit = 1;
    ImGui::AlignTextToFramePadding();
    unsigned int current_active_id = ImGui::GetActiveID();
    ImGui::PushItemWidth(caption_max);
    imgui_wrapper->text(_L("World coordinates"));
    ImGui::SameLine(caption_max + index * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("X");
    ImGui::SameLine(caption_max + unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("Y");
    ImGui::SameLine(caption_max + (++index_unit) * unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("Z");
    index      = 1;
    index_unit = 1;
    // ImGui::PushItemWidth(unit_size * 2);
    ImGui::AlignTextToFramePadding();
    imgui_wrapper->text(_L("Rotation"));
    ImGui::SameLine(caption_max + index * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_values[1][0], &rotation[0], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_values[1][1], &rotation[1], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + (++index_unit) * unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_values[1][2], &rotation[2], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + (++index_unit) * unit_size + (++index) * space_size);
    imgui_wrapper->text(_L(""));
    m_buffered_rotation = rotation;
    update(current_active_id, "rotation", this->m_new_rotation, m_buffered_rotation);
    if (m_show_clear_rotation) {
        ImGui::SameLine(caption_max + 3 * unit_size + 4 * space_size + end_text_size);
        if (reset_button(imgui_wrapper, caption_max, unit_size, space_size, end_text_size)) { reset_rotation_value(); }
    } else {
        ImGui::SameLine(caption_max + 3 * unit_size + 5 * space_size + end_text_size);
        ImGui::InvisibleButton("", ImVec2(ImGui::GetFontSize(), ImGui::GetFontSize()));
    }
    // send focus to m_glcanvas
    bool focued_on_text = false;
    for (int j = 0; j < 3; j++) {
        unsigned int id = ImGui::GetID(label_values[1][j]);
        if (current_active_id == id) {
            m_glcanvas.handle_sidebar_focus_event(label_values[1][j] + 2, true);
            focued_on_text = true;
            break;
        }
    }
    if (!focued_on_text) m_glcanvas.handle_sidebar_focus_event("", false);
    m_last_active_item = current_active_id;
    last_rotate_input_window_width = ImGui::GetWindowWidth();
    imgui_wrapper->end();
    // BBS
    ImGui::PopStyleVar(1);
    ImGuiWrapper::pop_toolbar_style();
}
References _L, ImGui::AlignTextToFramePadding(), ImGui::BBLInputDouble(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::GLCanvas3D::get_scale(), Slic3r::GUI::ImGuiWrapper::get_style_scaling(), Slic3r::GUI::Size::get_width(), ImGui::GetActiveID(), ImGui::GetFontSize(), ImGui::GetID(), ImGui::GetWindowWidth(), Slic3r::GUI::GLCanvas3D::handle_sidebar_focus_event(), ImGuiCond_Always, ImGuiStyleVar_ItemSpacing, ImGui::InvisibleButton(), Slic3r::GUI::label_values, last_rotate_input_window_width, m_buffered_position, m_buffered_rotation, m_glcanvas, m_imperial_units, m_last_active_item, m_new_position, m_new_rotation, m_new_title_string, m_new_unit_string, m_show_clear_rotation, MAX_SIZE, mm_to_in, on_change(), Slic3r::GUI::ImGuiWrapper::pop_toolbar_style(), ImGui::PopStyleVar(), Slic3r::GUI::ImGuiWrapper::push_toolbar_style(), ImGui::PushItemWidth(), ImGui::PushStyleVar(), reset_button(), reset_rotation_value(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), Slic3r::GUI::ImGuiWrapper::text(), ImGui::TextAlignCenter(), Slic3r::GUI::ImGuiWrapper::TOOLBAR_WINDOW_FLAGS, and ImVec2::x.
Referenced by Slic3r::GUI::GLGizmoRotate3D::on_render_input_window().
do_render_scale_input_window()
void Slic3r::GUI::GizmoObjectManipulation::do_render_scale_input_window (ImGuiWrapper * imgui_wrapper, std::string window_name, float x, float y, float bottom_limit)
{
    //BBS: GUI refactor: move gizmo to the right
    if (abs(last_scale_input_window_width) > 0.01f) {
        if (x + last_scale_input_window_width > m_glcanvas.get_canvas_size().get_width()) {
            if (last_scale_input_window_width > m_glcanvas.get_canvas_size().get_width())
                x = 0;
            else
                x = m_glcanvas.get_canvas_size().get_width() - last_scale_input_window_width;
        }
    }
#if BBS_TOOLBAR_ON_TOP
    imgui_wrapper->set_next_window_pos(x, y, ImGuiCond_Always, 0.f, 0.0f);
#else
    imgui_wrapper->set_next_window_pos(x, y, ImGuiCond_Always, 1.0f, 0.0f);
#endif
    //BBS
    ImGuiWrapper::push_toolbar_style(m_glcanvas.get_scale());
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(0.0, 6.0));
    std::string name = this->m_new_title_string + "##" + window_name;
    imgui_wrapper->begin(_L(name), ImGuiWrapper::TOOLBAR_WINDOW_FLAGS);
    auto update = [this](unsigned int active_id, std::string opt_key, Vec3d original_value, Vec3d new_value)->int {
        for (int i = 0; i < 3; i++)
        {
            if (original_value[i] != new_value[i])
            {
                if (active_id != m_last_active_item)
                {
                    on_change(opt_key, i, new_value[i]);
                    return i;
                }
            }
        }
        return -1;
    };
    float space_size = imgui_wrapper->get_style_scaling() * 8;
    float scale_size = imgui_wrapper->calc_text_size(_L("Scale")).x + space_size;
    float size_len = imgui_wrapper->calc_text_size(_L("Size")).x + space_size;
    float caption_max = std::max(scale_size, size_len) + 2 * space_size;
    float end_text_size = imgui_wrapper->calc_text_size(this->m_new_unit_string).x;
    ImGui::AlignTextToFramePadding();
    unsigned int current_active_id = ImGui::GetActiveID();
    Vec3d scale = m_buffered_scale;
    Vec3d display_size = m_buffered_size;
    Vec3d display_position = m_buffered_position;
    float unit_size = imgui_wrapper->calc_text_size(MAX_SIZE).x + space_size;
    bool imperial_units = this->m_imperial_units;
    int index      = 2;
    int index_unit = 1;
    ImGui::PushItemWidth(caption_max);
    ImGui::Dummy(ImVec2(caption_max, -1));
    //imgui_wrapper->text(_L(" "));
    //ImGui::PushItemWidth(unit_size * 1.5);
    ImGui::SameLine(caption_max + space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("X");
    ImGui::SameLine(caption_max + unit_size + index * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("Y");
    ImGui::SameLine(caption_max + (++index_unit) * unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("Z");
    index      = 2;
    index_unit = 1;
    //ImGui::PushItemWidth(unit_size * 2);
    ImGui::AlignTextToFramePadding();
    imgui_wrapper->text(_L("Scale"));
    ImGui::SameLine(caption_max + space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_scale_values[0][0], &scale[0], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + unit_size + index * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_scale_values[0][1], &scale[1], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + (++index_unit) *unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_scale_values[0][2], &scale[2], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + (++index_unit) *unit_size + (++index) * space_size);
    imgui_wrapper->text(_L("%"));
    m_buffered_scale = scale;
    if (m_show_clear_scale) {
        ImGui::SameLine(caption_max + 3 * unit_size + 4 * space_size + end_text_size);
        if (reset_button(imgui_wrapper, caption_max, unit_size, space_size, end_text_size))
            reset_scale_value();
    } else {
        ImGui::SameLine(caption_max + 3 * unit_size + 5 * space_size + end_text_size);
        ImGui::InvisibleButton("", ImVec2(ImGui::GetFontSize(), ImGui::GetFontSize()));
    }
    //Size
    Vec3d original_size;
    if (this->m_imperial_units)
        original_size = this->m_new_size * this->mm_to_in;
    else
        original_size = this->m_new_size;
    index              = 2;
    index_unit         = 1;
    //ImGui::PushItemWidth(unit_size * 2);
    ImGui::AlignTextToFramePadding();
    imgui_wrapper->text(_L("Size"));
    ImGui::SameLine(caption_max + space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_scale_values[1][0], &display_size[0], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + unit_size + index * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_scale_values[1][1], &display_size[1], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + (++index_unit) *unit_size + (++index) * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble(label_scale_values[1][2], &display_size[2], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_max + (++index_unit) *unit_size + (++index) * space_size);
    imgui_wrapper->text(this->m_new_unit_string);
    for (int i = 0;i<display_size.size();i++)
    {
        if (std::abs(display_size[i]) > MAX_NUM) display_size[i] = MAX_NUM;
    }
    m_buffered_size = display_size;
    int size_sel = update(current_active_id, "size", original_size, m_buffered_size);
    ImGui::PopStyleVar(1);
    ImGui::Separator();
    bool uniform_scale = this->m_uniform_scale;
    // BBS: when select multiple objects, uniform scale can be deselected
    //const Selection &selection = m_glcanvas.get_selection();
    //bool uniform_scale_only    = selection.is_multiple_full_object() || selection.is_multiple_full_instance() || selection.is_mixed() || selection.is_multiple_volume() ||
    //                          selection.is_multiple_modifier();
    //if (uniform_scale_only) {
    //    imgui_wrapper->disabled_begin(true);
    //    imgui_wrapper->bbl_checkbox(_L("uniform scale"), uniform_scale_only);
    //    imgui_wrapper->disabled_end();
    //} else {
        imgui_wrapper->bbl_checkbox(_L("uniform scale"), uniform_scale);
    //}
    if (uniform_scale != this->m_uniform_scale) { this->set_uniform_scaling(uniform_scale); }
     // for (int index = 0; index < 3; index++)
    //    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ",before_index="<<index <<boost::format(",scale %1%, buffered %2%, original_id %3%, new_id %4%\n") %
    //    this->m_new_scale[index] % m_buffered_scale[index] % m_last_active_item % current_active_id;
    int scale_sel = update(current_active_id, "scale", this->m_new_scale, m_buffered_scale);
    if ((scale_sel >= 0)) {
        // for (int index = 0; index < 3; index++)
        //    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ",after_index="<<index <<boost::format(",scale %1%, buffered %2%, original_id %3%, new_id %4%\n") %
        //    this->m_new_scale[index] % m_buffered_scale[index] % m_last_active_item % current_active_id;
        for (int i = 0; i < 3; ++i) {
            if (i != scale_sel) ImGui::ClearInputTextInitialData(label_scale_values[0][i], m_buffered_scale[i]);
            ImGui::ClearInputTextInitialData(label_scale_values[1][i], m_buffered_size[i]);
        }
    }
    if ((size_sel >= 0)) {
        // for (int index = 0; index < 3; index++)
        //    BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << ",after_index="<<index <<boost::format(",scale %1%, buffered %2%, original_id %3%, new_id %4%\n") %
        //    this->m_new_scale[index] % m_buffered_scale[index] % m_last_active_item % current_active_id;
        for (int i = 0; i < 3; ++i) {
            ImGui::ClearInputTextInitialData(label_scale_values[0][i], m_buffered_scale[i]);
            if (i != size_sel) ImGui::ClearInputTextInitialData(label_scale_values[1][i], m_buffered_size[i]);
        }
    }
    //send focus to m_glcanvas
    bool focued_on_text = false;
    for (int i = 0; i < 2; i++)
        for (int j = 0; j < 3; j++)
        {
            unsigned int id = ImGui::GetID(label_scale_values[i][j]);
            if (current_active_id == id)
            {
                m_glcanvas.handle_sidebar_focus_event(label_scale_values[i][j] + 2, true);
                focued_on_text = true;
                break;
            }
        }
    if (!focued_on_text)
        m_glcanvas.handle_sidebar_focus_event("", false);
    m_last_active_item = current_active_id;
    last_scale_input_window_width = ImGui::GetWindowWidth();
    imgui_wrapper->end();
    //BBS
    ImGuiWrapper::pop_toolbar_style();
}
References _L, ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::bbl_checkbox(), ImGui::BBLInputDouble(), Slic3r::GUI::ImGuiWrapper::begin(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), ImGui::ClearInputTextInitialData(), ImGui::Dummy(), Slic3r::GUI::ImGuiWrapper::end(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::GLCanvas3D::get_scale(), Slic3r::GUI::ImGuiWrapper::get_style_scaling(), Slic3r::GUI::Size::get_width(), ImGui::GetActiveID(), ImGui::GetFontSize(), ImGui::GetID(), ImGui::GetWindowWidth(), Slic3r::GUI::GLCanvas3D::handle_sidebar_focus_event(), ImGuiCond_Always, ImGuiStyleVar_ItemSpacing, ImGui::InvisibleButton(), Slic3r::GUI::label_scale_values, last_scale_input_window_width, m_buffered_position, m_buffered_scale, m_buffered_size, m_glcanvas, m_imperial_units, m_last_active_item, m_new_scale, m_new_size, m_new_title_string, m_new_unit_string, m_show_clear_scale, m_uniform_scale, MAX_NUM, MAX_SIZE, mm_to_in, on_change(), Slic3r::GUI::ImGuiWrapper::pop_toolbar_style(), ImGui::PopStyleVar(), Slic3r::GUI::ImGuiWrapper::push_toolbar_style(), ImGui::PushItemWidth(), ImGui::PushStyleVar(), reset_button(), reset_scale_value(), ImGui::SameLine(), scale(), ImGui::Separator(), Slic3r::GUI::ImGuiWrapper::set_next_window_pos(), set_uniform_scaling(), Slic3r::GUI::ImGuiWrapper::text(), ImGui::TextAlignCenter(), Slic3r::GUI::ImGuiWrapper::TOOLBAR_WINDOW_FLAGS, and ImVec2::x.
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render_input_window().
do_scale()
void Slic3r::GUI::GizmoObjectManipulation::do_scale (int axis, const Vec3d & scale) const private
{
    Selection& selection = m_glcanvas.get_selection();
    Vec3d scaling_factor = scale;
    TransformationType transformation_type(TransformationType::World_Relative_Joint);
    if (selection.is_single_full_instance()) {
        transformation_type.set_absolute();
        if (! m_world_coordinates)
            transformation_type.set_local();
    }
    // BBS: when select multiple objects, uniform scale can be deselected
    if (m_uniform_scale/* || selection.requires_uniform_scale()*/)
        scaling_factor = scale(axis) * Vec3d::Ones();
    selection.start_dragging();
    selection.scale(scaling_factor * 0.01, transformation_type);
    m_glcanvas.do_scale(L("Set Scale"));
}
References Slic3r::GUI::GLCanvas3D::do_scale(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_single_full_instance(), L, m_glcanvas, m_uniform_scale, m_world_coordinates, scale(), Slic3r::GUI::Selection::scale(), Slic3r::GUI::TransformationType::set_absolute(), Slic3r::GUI::TransformationType::set_local(), Slic3r::GUI::Selection::start_dragging(), and Slic3r::GUI::TransformationType::World_Relative_Joint.
Referenced by change_scale_value(), and change_size_value().
get_uniform_scaling()
bool Slic3r::GUI::GizmoObjectManipulation::get_uniform_scaling () const inline
{ return m_uniform_scale; }
References m_uniform_scale.
Referenced by Slic3r::GUI::GLGizmosManager::get_uniform_scaling().
get_world_coordinates()
bool Slic3r::GUI::GizmoObjectManipulation::get_world_coordinates () const inline
{ return m_world_coordinates; }
References m_world_coordinates.
IsShown()
bool Slic3r::GUI::GizmoObjectManipulation::IsShown ()
max_unit_size()
float Slic3r::GUI::GizmoObjectManipulation::max_unit_size (int number, Vec3d & vec1, Vec3d & vec2, std::string str)
 {
     if (number <= 1) return -1;
     Vec3d vec[2] = {vec1, vec2};
     float nuit_max[4] = {0};
     float vec_max = 0, unit_size = 0;
     for (int i = 0; i < number; i++)
     {
         char buf[3][64] = {0};
         float buf_size[3] = {0};
         for (int j = 0; j < 3; j++) {
             ImGui::DataTypeFormatString(buf[j], IM_ARRAYSIZE(buf[j]), ImGuiDataType_Double, (void *) &vec[i][j], "%.2f");
             buf_size[j]  = ImGui::CalcTextSize(buf[j]).x;
             vec_max = std::max(buf_size[j], vec_max);
             nuit_max[i]  = vec_max;
         }
         unit_size = std::max(nuit_max[i], unit_size);
     }
     return unit_size + 8.0;
 }
References ImGui::CalcTextSize(), ImGui::DataTypeFormatString(), IM_ARRAYSIZE, ImGuiDataType_Double, and ImVec2::x.
on_change()
void Slic3r::GUI::GizmoObjectManipulation::on_change (const std::string & opt_key, int axis, double new_value)
{
    if (!m_cache.is_valid())
        return;
    if (m_imperial_units && (opt_key == "position" || opt_key == "size"))
        new_value *= in_to_mm;
    if (opt_key == "position")
        change_position_value(axis, new_value);
    else if (opt_key == "rotation")
        change_rotation_value(axis, new_value);
    else if (opt_key == "scale")
        change_scale_value(axis, new_value);
    else if (opt_key == "size")
        change_size_value(axis, new_value);
}
References change_position_value(), change_rotation_value(), change_scale_value(), change_size_value(), in_to_mm, Slic3r::GUI::GizmoObjectManipulation::Cache::is_valid(), m_cache, and m_imperial_units.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), do_render_move_window(), do_render_rotate_window(), and do_render_scale_input_window().
reset_button()
bool Slic3r::GUI::GizmoObjectManipulation::reset_button (ImGuiWrapper * imgui_wrapper, float caption_max, float unit_size, float space_size, float end_text_size)
{
    bool        pressed   = false;
    ImTextureID normal_id = m_glcanvas.get_gizmos_manager().get_icon_texture_id(GLGizmosManager::MENU_ICON_NAME::IC_TOOLBAR_RESET);
    ImTextureID hover_id  = m_glcanvas.get_gizmos_manager().get_icon_texture_id(GLGizmosManager::MENU_ICON_NAME::IC_TOOLBAR_RESET_HOVER);
    float font_size = ImGui::GetFontSize();
    ImVec2 button_size = ImVec2(font_size, font_size);
    ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 0.0f);
    pressed = ImGui::ImageButton3(normal_id, hover_id, button_size);
    ImGui::PopStyleVar(1);
    return pressed;
}
References Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmosManager::get_icon_texture_id(), ImGui::GetFontSize(), Slic3r::GUI::GLGizmosManager::IC_TOOLBAR_RESET, Slic3r::GUI::GLGizmosManager::IC_TOOLBAR_RESET_HOVER, ImGui::ImageButton3(), ImGuiStyleVar_FrameBorderSize, m_glcanvas, ImGui::PopStyleVar(), and ImGui::PushStyleVar().
Referenced by do_render_rotate_window(), and do_render_scale_input_window().
reset_cache()
void Slic3r::GUI::GizmoObjectManipulation::reset_cache () inline
{ m_cache.reset(); }
References Slic3r::GUI::GizmoObjectManipulation::Cache::reset().
reset_position_value()
void Slic3r::GUI::GizmoObjectManipulation::reset_position_value () private
{
    Selection& selection = m_glcanvas.get_selection();
    if (selection.is_single_volume() || selection.is_single_modifier()) {
        GLVolume* volume = const_cast<GLVolume*>(selection.get_volume(*selection.get_volume_idxs().begin()));
        volume->set_volume_offset(Vec3d::Zero());
    }
    else if (selection.is_single_full_instance()) {
        for (unsigned int idx : selection.get_volume_idxs()) {
            GLVolume* volume = const_cast<GLVolume*>(selection.get_volume(idx));
            volume->set_instance_offset(Vec3d::Zero());
        }
    }
    else
        return;
    // Copy position values from GLVolumes into Model (ModelInstance / ModelVolume), trigger background processing.
    m_glcanvas.do_move(L("Reset Position"));
    UpdateAndShow(true);
}
References Slic3r::GUI::GLCanvas3D::do_move(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_modifier(), Slic3r::GUI::Selection::is_single_volume(), L, m_glcanvas, and UpdateAndShow().
reset_rotation_value()
void Slic3r::GUI::GizmoObjectManipulation::reset_rotation_value () private
{
    Selection& selection = m_glcanvas.get_selection();
    if (selection.is_single_volume() || selection.is_single_modifier()) {
        GLVolume* volume = const_cast<GLVolume*>(selection.get_volume(*selection.get_volume_idxs().begin()));
        volume->set_volume_rotation(Vec3d::Zero());
    }
    else if (selection.is_single_full_instance()) {
        for (unsigned int idx : selection.get_volume_idxs()) {
            GLVolume* volume = const_cast<GLVolume*>(selection.get_volume(idx));
            volume->set_instance_rotation(Vec3d::Zero());
        }
    }
    else
        return;
    // Update rotation at the GLVolumes.
    selection.synchronize_unselected_instances(Selection::SYNC_ROTATION_GENERAL);
    selection.synchronize_unselected_volumes();
    // Copy rotation values from GLVolumes into Model (ModelInstance / ModelVolume), trigger background processing.
    m_glcanvas.do_rotate(L("Reset Rotation"));
    UpdateAndShow(true);
}
References Slic3r::GUI::GLCanvas3D::do_rotate(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_modifier(), Slic3r::GUI::Selection::is_single_volume(), L, m_glcanvas, Slic3r::GUI::Selection::SYNC_ROTATION_GENERAL, Slic3r::GUI::Selection::synchronize_unselected_instances(), Slic3r::GUI::Selection::synchronize_unselected_volumes(), and UpdateAndShow().
Referenced by do_render_rotate_window().
reset_scale_value()
void Slic3r::GUI::GizmoObjectManipulation::reset_scale_value () private
{
    Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Reset scale");
    change_scale_value(0, 100.);
    change_scale_value(1, 100.);
    change_scale_value(2, 100.);
}
References change_scale_value(), and Slic3r::GUI::plater().
Referenced by do_render_scale_input_window().
reset_settings_value()
void Slic3r::GUI::GizmoObjectManipulation::reset_settings_value () private
{
    m_new_position = Vec3d::Zero();
    m_new_rotation = Vec3d::Zero();
    m_new_scale = Vec3d::Ones() * 100.;
    m_new_size = Vec3d::Zero();
    m_new_enabled = false;
    // no need to set the dirty flag here as this method is called from update_settings_value(),
    // which is called from update_if_dirty(), which resets the dirty flag anyways.
//    m_dirty = true;
}
References m_new_enabled, m_new_position, m_new_rotation, m_new_scale, and m_new_size.
Referenced by update_settings_value().
set_dirty()
void Slic3r::GUI::GizmoObjectManipulation::set_dirty () inline
{ m_dirty = true; }
References m_dirty.
Referenced by UpdateAndShow().
set_uniform_scaling()
void Slic3r::GUI::GizmoObjectManipulation::set_uniform_scaling (const bool uniform_scale)
{
    const Selection &selection = m_glcanvas.get_selection();
  if (selection.is_single_full_instance() && m_world_coordinates && !new_value) {
        // Verify whether the instance rotation is multiples of 90 degrees, so that the scaling in world coordinates is possible.
        // all volumes in the selection belongs to the same instance, any of them contains the needed instance data, so we take the first one
        const GLVolume* volume = selection.get_volume(*selection.get_volume_idxs().begin());
        // Is the angle close to a multiple of 90 degrees?
    if (! Geometry::is_rotation_ninety_degrees(volume->get_instance_rotation())) {
            // Cannot apply scaling in the world coordinate system.
            // BBS: remove tilt prompt dialog
            // Bake the rotation into the meshes of the object.
            wxGetApp().model().objects[volume->composite_id.object_id]->bake_xy_rotation_into_meshes(volume->composite_id.instance_id);
            // Update the 3D scene, selections etc.
            wxGetApp().plater()->update();
            // Recalculate cached values at this panel, refresh the screen.
            this->UpdateAndShow(true);
        }
    }
    m_uniform_scale = new_value;
}
References Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::Geometry::is_rotation_ninety_degrees(), Slic3r::GUI::Selection::is_single_full_instance(), m_glcanvas, m_uniform_scale, m_world_coordinates, and UpdateAndShow().
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), and do_render_scale_input_window().
set_world_coordinates()
void Slic3r::GUI::GizmoObjectManipulation::set_world_coordinates (const bool world_coordinates) inline
{ m_world_coordinates = world_coordinates; this->UpdateAndShow(true); }
References m_world_coordinates, and UpdateAndShow().
update_buffered_value()
void Slic3r::GUI::GizmoObjectManipulation::update_buffered_value () private
{
    if (this->m_imperial_units)
        m_buffered_position = this->m_new_position * this->mm_to_in;
    else
        m_buffered_position = this->m_new_position;
    m_buffered_rotation = this->m_new_rotation;
    m_buffered_scale = this->m_new_scale;
    if (this->m_imperial_units)
        m_buffered_size = this->m_new_size * this->mm_to_in;
    else
        m_buffered_size = this->m_new_size;
}
References m_buffered_position, m_buffered_rotation, m_buffered_scale, m_buffered_size, m_imperial_units, m_new_position, m_new_rotation, m_new_scale, m_new_size, and mm_to_in.
Referenced by update_if_dirty(), and update_ui_from_settings().
update_if_dirty()
void Slic3r::GUI::GizmoObjectManipulation::update_if_dirty ()
{
    if (! m_dirty)
        return;
    const Selection &selection = m_glcanvas.get_selection();
    this->update_settings_value(selection);
    this->update_buffered_value();
    auto update_label = [](wxString &label_cache, const std::string &new_label) {
        wxString new_label_localized = _(new_label) + ":";
        if (label_cache != new_label_localized) {
            label_cache = new_label_localized;
        }
    };
    update_label(m_cache.move_label_string,   m_new_move_label_string);
    update_label(m_cache.rotate_label_string, m_new_rotate_label_string);
    update_label(m_cache.scale_label_string,  m_new_scale_label_string);
    enum ManipulationEditorKey
    {
        mePosition = 0,
        meRotation,
        meScale,
        meSize
    };
    for (int i = 0; i < 3; ++ i) {
        auto update = [this, i](Vec3d &cached, Vec3d &cached_rounded,  const Vec3d &new_value) {
      //wxString new_text = double_to_string(new_value(i), 2);
      double new_rounded = round(new_value(i)*100)/100.0;
      //new_text.ToDouble(&new_rounded);
      if (std::abs(cached_rounded(i) - new_rounded) > EPSILON) {
        cached_rounded(i) = new_rounded;
                //const int id = key_id*3+i;
                //if (m_imperial_units && (key_id == mePosition || key_id == meSize))
                //    new_text = double_to_string(new_value(i)*mm_to_in, 2);
                //if (id >= 0) m_editors[id]->set_value(new_text);
            }
      cached(i) = new_value(i);
    };
        update(m_cache.position, m_cache.position_rounded,  m_new_position);
        update(m_cache.scale,    m_cache.scale_rounded,     m_new_scale);
        update(m_cache.size,     m_cache.size_rounded,      m_new_size);
        update(m_cache.rotation, m_cache.rotation_rounded,  m_new_rotation);
    }
    update_reset_buttons_visibility();
    //update_mirror_buttons_visibility();
    m_dirty = false;
}
References _, EPSILON, Slic3r::GUI::GLCanvas3D::get_selection(), m_cache, m_dirty, m_glcanvas, m_new_move_label_string, m_new_position, m_new_rotate_label_string, m_new_rotation, m_new_scale, m_new_scale_label_string, m_new_size, Slic3r::GUI::GizmoObjectManipulation::Cache::move_label_string, Slic3r::GUI::GizmoObjectManipulation::Cache::position, Slic3r::GUI::GizmoObjectManipulation::Cache::position_rounded, Slic3r::GUI::GizmoObjectManipulation::Cache::rotate_label_string, Slic3r::GUI::GizmoObjectManipulation::Cache::rotation, Slic3r::GUI::GizmoObjectManipulation::Cache::rotation_rounded, round(), Slic3r::GUI::GizmoObjectManipulation::Cache::scale, Slic3r::GUI::GizmoObjectManipulation::Cache::scale_label_string, Slic3r::GUI::GizmoObjectManipulation::Cache::scale_rounded, Slic3r::GUI::GizmoObjectManipulation::Cache::size, Slic3r::GUI::GizmoObjectManipulation::Cache::size_rounded, update_buffered_value(), update_reset_buttons_visibility(), and update_settings_value().
Referenced by UpdateAndShow().
update_reset_buttons_visibility()
void Slic3r::GUI::GizmoObjectManipulation::update_reset_buttons_visibility () private
{
    const Selection& selection = m_glcanvas.get_selection();
    if (selection.is_single_full_instance() || selection.is_single_modifier() || selection.is_single_volume()) {
        const GLVolume* volume = selection.get_volume(*selection.get_volume_idxs().begin());
        Vec3d rotation;
        Vec3d scale;
        double min_z = 0.;
        if (selection.is_single_full_instance()) {
            rotation = volume->get_instance_rotation();
            scale = volume->get_instance_scaling_factor();
        }
        else {
            rotation = volume->get_volume_rotation();
            scale = volume->get_volume_scaling_factor();
            min_z = get_volume_min_z(volume);
        }
        m_show_clear_rotation = !rotation.isApprox(Vec3d::Zero());
        m_show_clear_scale = !scale.isApprox(Vec3d::Ones(), EPSILON);
        m_show_drop_to_bed = (std::abs(min_z) > EPSILON);
    }
}
References EPSILON, Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::get_volume_min_z(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_modifier(), Slic3r::GUI::Selection::is_single_volume(), m_glcanvas, m_show_clear_rotation, m_show_clear_scale, m_show_drop_to_bed, and scale().
Referenced by update_if_dirty().
update_settings_value()
void Slic3r::GUI::GizmoObjectManipulation::update_settings_value (const Selection & selection) private
{
  m_new_move_label_string   = L("Position");
    m_new_rotate_label_string = L("Rotation");
    m_new_scale_label_string  = L("Scale ratios");
    m_world_coordinates = true;
    ObjectList* obj_list = wxGetApp().obj_list();
    if (selection.is_single_full_instance()) {
        // all volumes in the selection belongs to the same instance, any of them contains the needed instance data, so we take the first one
        const GLVolume* volume = selection.get_volume(*selection.get_volume_idxs().begin());
        m_new_position = volume->get_instance_offset();
        if (m_world_coordinates) {
      m_new_rotate_label_string = L("Rotate");
            m_new_rotation = volume->get_instance_rotation() * (180. / M_PI);
      m_new_size     = selection.get_scaled_instance_bounding_box().size();
      m_new_scale    = m_new_size.cwiseProduct(selection.get_unscaled_instance_bounding_box().size().cwiseInverse()) * 100.;
    }
        else {
      m_new_rotation = volume->get_instance_rotation() * (180. / M_PI);
      m_new_size     = volume->get_instance_transformation().get_scaling_factor().cwiseProduct(wxGetApp().model().objects[volume->object_idx()]->raw_mesh_bounding_box().size());
      m_new_scale    = volume->get_instance_scaling_factor() * 100.;
    }
        m_new_enabled  = true;
        // BBS: change "Instance Operations" to "Object Operations"
        m_new_title_string = L("Object Operations");
    }
    else if (selection.is_single_full_object() && obj_list->is_selected(itObject)) {
        const BoundingBoxf3& box = selection.get_bounding_box();
        m_new_position = box.center();
        m_new_rotation = Vec3d::Zero();
        m_new_scale    = Vec3d(100., 100., 100.);
        m_new_size     = box.size();
        m_new_rotate_label_string = L("Rotate");
    m_new_scale_label_string  = L("Scale");
        m_new_enabled  = true;
        m_new_title_string = L("Object Operations");
    }
    else if (selection.is_single_modifier() || selection.is_single_volume()) {
        // the selection contains a single volume
        const GLVolume* volume = selection.get_volume(*selection.get_volume_idxs().begin());
        m_new_position = volume->get_volume_offset();
        m_new_rotation = volume->get_volume_rotation() * (180. / M_PI);
        m_new_scale    = volume->get_volume_scaling_factor() * 100.;
        m_new_size     = volume->get_instance_transformation().get_scaling_factor().cwiseProduct(volume->get_volume_transformation().get_scaling_factor().cwiseProduct(volume->bounding_box().size()));
        m_new_enabled = true;
        m_new_title_string = L("Volume Operations");
    }
    else if (obj_list->multiple_selection() || obj_list->is_selected(itInstanceRoot)) {
        reset_settings_value();
    m_new_move_label_string   = L("Translate");
    m_new_rotate_label_string = L("Rotate");
    m_new_scale_label_string  = L("Scale");
        m_new_size = selection.get_bounding_box().size();
        m_new_enabled  = true;
        m_new_title_string = L("Group Operations");
    }
  else {
        // No selection, reset the cache.
//    assert(selection.is_empty());
    reset_settings_value();
  }
}
References Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::Selection::get_scaled_instance_bounding_box(), Slic3r::GUI::Selection::get_unscaled_instance_bounding_box(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::ObjectList::is_selected(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_single_full_object(), Slic3r::GUI::Selection::is_single_modifier(), Slic3r::GUI::Selection::is_single_volume(), Slic3r::GUI::itInstanceRoot, Slic3r::GUI::itObject, L, m_new_enabled, m_new_move_label_string, m_new_position, m_new_rotate_label_string, m_new_rotation, m_new_scale, m_new_scale_label_string, m_new_size, m_new_title_string, M_PI, m_world_coordinates, Slic3r::GUI::ObjectList::multiple_selection(), Slic3r::GUI::obj_list(), reset_settings_value(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by update_if_dirty().
update_ui_from_settings()
void Slic3r::GUI::GizmoObjectManipulation::update_ui_from_settings ()
{
    if (m_imperial_units != (wxGetApp().app_config->get("use_inches") == "1")) {
        m_imperial_units = wxGetApp().app_config->get("use_inches") == "1";
        m_new_unit_string = m_imperial_units ? L("in") : L("mm");
        update_buffered_value();
    }
}
References L, m_imperial_units, m_new_unit_string, and update_buffered_value().
UpdateAndShow()
void Slic3r::GUI::GizmoObjectManipulation::UpdateAndShow (const bool show)
{
  if (show) {
        this->set_dirty();
    this->update_if_dirty();
  }
}
References set_dirty(), and update_if_dirty().
Referenced by change_position_value(), change_rotation_value(), change_scale_value(), change_size_value(), reset_position_value(), reset_rotation_value(), set_uniform_scaling(), and set_world_coordinates().
Member Data Documentation
g_to_oz
const double Slic3r::GUI::GizmoObjectManipulation::g_to_oz = 0.035274 static
in_to_mm
const double Slic3r::GUI::GizmoObjectManipulation::in_to_mm = 25.4 static
Referenced by on_change(), Slic3r::GUI::GCodeViewer::render_all_plates_stats(), and Slic3r::GUI::GCodeViewer::render_legend().
last_move_input_window_width
float Slic3r::GUI::GizmoObjectManipulation::last_move_input_window_width = 0.0f protected
Referenced by do_render_move_window().
last_rotate_input_window_width
float Slic3r::GUI::GizmoObjectManipulation::last_rotate_input_window_width = 0.0f protected
Referenced by do_render_rotate_window().
last_scale_input_window_width
float Slic3r::GUI::GizmoObjectManipulation::last_scale_input_window_width = 0.0f protected
Referenced by do_render_scale_input_window().
m_buffered_position
Vec3d Slic3r::GUI::GizmoObjectManipulation::m_buffered_position
Referenced by do_render_move_window(), do_render_rotate_window(), do_render_scale_input_window(), and update_buffered_value().
m_buffered_rotation
Vec3d Slic3r::GUI::GizmoObjectManipulation::m_buffered_rotation
Referenced by do_render_move_window(), do_render_rotate_window(), and update_buffered_value().
m_buffered_scale
Vec3d Slic3r::GUI::GizmoObjectManipulation::m_buffered_scale
Referenced by do_render_scale_input_window(), and update_buffered_value().
m_buffered_size
Vec3d Slic3r::GUI::GizmoObjectManipulation::m_buffered_size
Referenced by do_render_scale_input_window(), and update_buffered_value().
m_cache
Cache Slic3r::GUI::GizmoObjectManipulation::m_cache
Referenced by change_position_value(), change_rotation_value(), change_scale_value(), change_size_value(), on_change(), and update_if_dirty().
m_dirty
bool Slic3r::GUI::GizmoObjectManipulation::m_dirty = false
Referenced by set_dirty(), and update_if_dirty().
m_glcanvas
GLCanvas3D& Slic3r::GUI::GizmoObjectManipulation::m_glcanvas private
Referenced by change_position_value(), change_rotation_value(), change_size_value(), do_render_move_window(), do_render_rotate_window(), do_render_scale_input_window(), do_scale(), reset_button(), reset_position_value(), reset_rotation_value(), set_uniform_scaling(), update_if_dirty(), and update_reset_buttons_visibility().
m_imperial_units
bool Slic3r::GUI::GizmoObjectManipulation::m_imperial_units { false }
Referenced by GizmoObjectManipulation(), do_render_move_window(), do_render_rotate_window(), do_render_scale_input_window(), on_change(), update_buffered_value(), and update_ui_from_settings().
m_last_active_item
unsigned int Slic3r::GUI::GizmoObjectManipulation::m_last_active_item { 0 } private
Referenced by do_render_move_window(), do_render_rotate_window(), and do_render_scale_input_window().
m_new_enabled
bool Slic3r::GUI::GizmoObjectManipulation::m_new_enabled {true}
Referenced by reset_settings_value(), and update_settings_value().
m_new_move_label_string
std::string Slic3r::GUI::GizmoObjectManipulation::m_new_move_label_string
Referenced by update_if_dirty(), and update_settings_value().
m_new_position
Vec3d Slic3r::GUI::GizmoObjectManipulation::m_new_position
Referenced by do_render_move_window(), do_render_rotate_window(), reset_settings_value(), update_buffered_value(), update_if_dirty(), and update_settings_value().
m_new_rotate_label_string
std::string Slic3r::GUI::GizmoObjectManipulation::m_new_rotate_label_string
Referenced by update_if_dirty(), and update_settings_value().
m_new_rotation
Vec3d Slic3r::GUI::GizmoObjectManipulation::m_new_rotation
Referenced by do_render_rotate_window(), reset_settings_value(), update_buffered_value(), update_if_dirty(), and update_settings_value().
m_new_scale
Vec3d Slic3r::GUI::GizmoObjectManipulation::m_new_scale
Referenced by do_render_scale_input_window(), reset_settings_value(), update_buffered_value(), update_if_dirty(), and update_settings_value().
m_new_scale_label_string
std::string Slic3r::GUI::GizmoObjectManipulation::m_new_scale_label_string
Referenced by update_if_dirty(), and update_settings_value().
m_new_size
Vec3d Slic3r::GUI::GizmoObjectManipulation::m_new_size
Referenced by do_render_scale_input_window(), reset_settings_value(), update_buffered_value(), update_if_dirty(), and update_settings_value().
m_new_title_string
std::string Slic3r::GUI::GizmoObjectManipulation::m_new_title_string
Referenced by do_render_move_window(), do_render_rotate_window(), do_render_scale_input_window(), and update_settings_value().
m_new_unit_string
std::string Slic3r::GUI::GizmoObjectManipulation::m_new_unit_string
Referenced by GizmoObjectManipulation(), do_render_move_window(), do_render_rotate_window(), do_render_scale_input_window(), and update_ui_from_settings().
m_show_clear_rotation
bool Slic3r::GUI::GizmoObjectManipulation::m_show_clear_rotation { false }
Referenced by do_render_rotate_window(), and update_reset_buttons_visibility().
m_show_clear_scale
bool Slic3r::GUI::GizmoObjectManipulation::m_show_clear_scale { false }
Referenced by do_render_scale_input_window(), and update_reset_buttons_visibility().
m_show_drop_to_bed
bool Slic3r::GUI::GizmoObjectManipulation::m_show_drop_to_bed { false }
Referenced by update_reset_buttons_visibility().
m_uniform_scale
bool Slic3r::GUI::GizmoObjectManipulation::m_uniform_scale {true}
Referenced by do_render_scale_input_window(), do_scale(), get_uniform_scaling(), and set_uniform_scaling().
m_world_coordinates
bool Slic3r::GUI::GizmoObjectManipulation::m_world_coordinates = true
Referenced by change_rotation_value(), change_size_value(), do_scale(), get_world_coordinates(), set_uniform_scaling(), set_world_coordinates(), and update_settings_value().
mm_to_in
const double Slic3r::GUI::GizmoObjectManipulation::mm_to_in = 0.0393700787 static
Referenced by do_render_move_window(), do_render_rotate_window(), do_render_scale_input_window(), Slic3r::GUI::Plater::show_object_info(), and update_buffered_value().
oz_to_g
const double Slic3r::GUI::GizmoObjectManipulation::oz_to_g = 28.34952 static
Referenced by Slic3r::GUI::GCodeViewer::render_legend().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GizmoObjectManipulation.hpp
src/slic3r/GUI/Gizmos/GizmoObjectManipulation.cpp