OrcaSlicer: Slic3r::GCodeProcessor::UsedFilaments Struct Reference
Slic3r::GCodeProcessor::UsedFilaments Struct Reference
Public Member Functions
void reset ()
void increase_caches (double extruded_volume)
void process_color_change_cache ()
void process_extruder_cache (GCodeProcessor *processor)
void update_flush_per_filament (size_t extrude_id, float flush_length)
void process_role_cache (GCodeProcessor *processor)
void process_caches (GCodeProcessor *processor)
Public Attributes
double color_change_cache
std::vector< double > volumes_per_color_change
double tool_change_cache
std::map< size_t, double > volumes_per_extruder
std::map< size_t, double > flush_per_filament
double role_cache
std::map< ExtrusionRole, std::pair< double, double > > filaments_per_role
Friends
class GCodeProcessor
Detailed Description
Member Function Documentation
increase_caches()
void Slic3r::GCodeProcessor::UsedFilaments::increase_caches (double extruded_volume)
{
    color_change_cache += extruded_volume;
    tool_change_cache += extruded_volume;
    role_cache += extruded_volume;
}
Referenced by Slic3r::GCodeProcessor::process_G1(), and Slic3r::GCodeProcessor::process_G2_G3().
process_caches()
void Slic3r::GCodeProcessor::UsedFilaments::process_caches (GCodeProcessor * processor)
{
    process_color_change_cache();
    process_extruder_cache(processor);
    process_role_cache(processor);
}
References processor.
Referenced by Slic3r::GCodeProcessor::finalize().
process_color_change_cache()
void Slic3r::GCodeProcessor::UsedFilaments::process_color_change_cache ()
{
    if (color_change_cache != 0.0f) {
        volumes_per_color_change.push_back(color_change_cache);
        color_change_cache = 0.0f;
    }
}
Referenced by Slic3r::GCodeProcessor::process_filaments().
process_extruder_cache()
void Slic3r::GCodeProcessor::UsedFilaments::process_extruder_cache (GCodeProcessor * processor)
{
    size_t active_extruder_id = processor->m_extruder_id;
    if (tool_change_cache != 0.0f) {
        if (volumes_per_extruder.find(active_extruder_id) != volumes_per_extruder.end())
            volumes_per_extruder[active_extruder_id] += tool_change_cache;
        else
            volumes_per_extruder[active_extruder_id] = tool_change_cache;
        tool_change_cache = 0.0f;
    }
}
References processor.
Referenced by Slic3r::GCodeProcessor::process_filaments().
process_role_cache()
void Slic3r::GCodeProcessor::UsedFilaments::process_role_cache (GCodeProcessor * processor)
{
    if (role_cache != 0.0f) {
        std::pair<double, double> filament = { 0.0f, 0.0f };
        double s = PI * sqr(0.5 * processor->m_result.filament_diameters[processor->m_extruder_id]);
        filament.first = role_cache / s * 0.001;
        filament.second = role_cache * processor->m_result.filament_densities[processor->m_extruder_id] * 0.001;
        ExtrusionRole active_role = processor->m_extrusion_role;
        if (filaments_per_role.find(active_role) != filaments_per_role.end()) {
            filaments_per_role[active_role].first += filament.first;
            filaments_per_role[active_role].second += filament.second;
        }
        else
            filaments_per_role[active_role] = filament;
        role_cache = 0.0f;
    }
}
References PI, processor, and Slic3r::sqr().
Referenced by Slic3r::GCodeProcessor::set_extrusion_role().
reset()
void Slic3r::GCodeProcessor::UsedFilaments::reset ()
{
    color_change_cache = 0.0f;
    volumes_per_color_change = std::vector<double>();
    tool_change_cache = 0.0f;
    volumes_per_extruder.clear();
    flush_per_filament.clear();
    role_cache = 0.0f;
    filaments_per_role.clear();
}
Referenced by Slic3r::GCodeProcessor::reset().
update_flush_per_filament()
void Slic3r::GCodeProcessor::UsedFilaments::update_flush_per_filament (size_t extrude_id, float flush_length)
{
    if (flush_per_filament.find(extrude_id) != flush_per_filament.end())
        flush_per_filament[extrude_id] += flush_volume;
    else
        flush_per_filament[extrude_id] = flush_volume;
}
Referenced by Slic3r::GCodeProcessor::process_G1().
Friends And Related Symbol Documentation
GCodeProcessor
friend class GCodeProcessor friend
Member Data Documentation
color_change_cache
double Slic3r::GCodeProcessor::UsedFilaments::color_change_cache
filaments_per_role
std::map<ExtrusionRole, std::pair<double, double> > Slic3r::GCodeProcessor::UsedFilaments::filaments_per_role
Referenced by Slic3r::GCodeProcessor::update_estimated_times_stats().
flush_per_filament
std::map<size_t, double> Slic3r::GCodeProcessor::UsedFilaments::flush_per_filament
Referenced by Slic3r::GCodeProcessor::update_estimated_times_stats().
role_cache
double Slic3r::GCodeProcessor::UsedFilaments::role_cache
tool_change_cache
double Slic3r::GCodeProcessor::UsedFilaments::tool_change_cache
volumes_per_color_change
std::vector<double> Slic3r::GCodeProcessor::UsedFilaments::volumes_per_color_change
Referenced by Slic3r::GCodeProcessor::update_estimated_times_stats().
volumes_per_extruder
std::map<size_t, double> Slic3r::GCodeProcessor::UsedFilaments::volumes_per_extruder
Referenced by Slic3r::GCodeProcessor::update_estimated_times_stats(), and Slic3r::GCodeProcessor::update_slice_warnings().
The documentation for this struct was generated from the following files:
src/libslic3r/GCode/GCodeProcessor.hpp
src/libslic3r/GCode/GCodeProcessor.cpp