OrcaSlicer: ScalableBitmap Class Reference
ScalableBitmap Class Reference
#include <src/slic3r/GUI/wxExtensions.hpp>
Public Member Functions
ScalableBitmap ()
ScalableBitmap (wxWindow *parent, const std::string &icon_name="", const int px_cnt=16, const bool grayscale=false, const bool resize=false)
~ScalableBitmap ()
wxSize GetBmpSize () const
int GetBmpWidth () const
int GetBmpHeight () const
void msw_rescale ()
const wxBitmap & bmp () const
wxBitmap & bmp ()
const std::string & name () const
int px_cnt () const
Private Attributes
wxWindow * m_parent { nullptr }
wxBitmap m_bmp = wxBitmap()
std::string m_icon_name = ""
int m_px_cnt {16}
bool m_grayscale { false }
bool m_resize { false }
Detailed Description
Constructor & Destructor Documentation
ScalableBitmap() [1/2]
ScalableBitmap::ScalableBitmap () inline
{};
ScalableBitmap() [2/2]
ScalableBitmap::ScalableBitmap (wxWindow * parent, const std::string & icon_name = "", const int px_cnt = 16, const bool grayscale = false, const bool resize = false)
                                                   :
    m_parent(parent), m_icon_name(icon_name),
    m_px_cnt(px_cnt), m_grayscale(grayscale), m_resize(resize) // BBS: support resize by fill border
{
    m_bmp = create_scaled_bitmap(icon_name, parent, px_cnt, m_grayscale, std::string(), false, resize);
    if (px_cnt == 0) {
        m_px_cnt = m_bmp.GetHeight(); // scale
        unsigned int height = (unsigned int) (parent->FromDIP(m_px_cnt) + 0.5f);
        if (height != GetBmpHeight())
            msw_rescale();
    }
}
References create_scaled_bitmap(), GetBmpHeight(), int, m_bmp, m_grayscale, m_px_cnt, msw_rescale(), and px_cnt().
~ScalableBitmap()
ScalableBitmap::~ScalableBitmap () inline
{}
Member Function Documentation
bmp() [1/2]
wxBitmap & ScalableBitmap::bmp () inline
{ return m_bmp; }
References m_bmp.
bmp() [2/2]
const wxBitmap & ScalableBitmap::bmp () const inline
{ return m_bmp; }
References m_bmp.
Referenced by Slic3r::GUI::AboutDialog::AboutDialog(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AuFile::AuFile(), Slic3r::GUI::FanControl::FanControl(), LockButton::LockButton(), ScalableButton::ScalableButton(), Slic3r::GUI::SysInfoDialog::SysInfoDialog(), BlinkingBitmap::activate(), BlinkingBitmap::blink(), Slic3r::GUI::Choice::BUILD(), Slic3r::GUI::StatusBasePanel::create_project_task_page(), Slic3r::GUI::MaterialItem::doRender(), Slic3r::GUI::CameraItem::doRender(), Slic3r::GUI::MachineObjectPanel::doRender(), Slic3r::GUI::AMSextruderImage::doRender(), Slic3r::GUI::AMSRoad::doRender(), Slic3r::GUI::Fan::doRender(), Slic3r::GUI::FanOperate::doRender(), Slic3r::GUI::SideTools::doRender(), StepCtrl::doRender(), StepIndicator::doRender(), SideButton::dorender(), TempInput::DoSetSize(), TextInput::DoSetSize(), BlinkingBitmap::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::Search::SearchListModel::GetValueByRow(), Slic3r::GUI::ConfigWizardIndex::item_height(), TempInput::messureMiniSize(), Button::messureSize(), DropDown::messureSize(), SideButton::messureSize(), StaticLine::messureSize(), TempInput::messureSize(), Slic3r::GUI::AuFile::msw_rescale(), Slic3r::GUI::AMSControl::msw_rescale(), Slic3r::GUI::Choice::msw_rescale(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizardIndex::on_paint(), Slic3r::GUI::FanControl::on_swith_fan(), Slic3r::GUI::FanControl::on_swith_fan(), Slic3r::GUI::StatusPanel::on_webrequest_state(), Slic3r::GUI::AboutDialogLogo::onRepaint(), Slic3r::GUI::AuFile::PaintBackground(), Slic3r::GUI::AMSrefresh::paintEvent(), Slic3r::GUI::AuFile::PaintForeground(), Slic3r::GUI::ImageGrid::render(), Slic3r::GUI::RecenterDialog::render(), AxisCtrlButton::render(), Button::render(), DropDown::render(), ImageSwitchButton::render(), FanSwitchButton::render(), StaticLine::render(), TempInput::render(), TextInput::render(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::render(), Button::Rescale(), SideButton::Rescale(), StaticLine::Rescale(), TempInput::Rescale(), Slic3r::GUI::StatusPanel::rescale_camera_icons(), Slic3r::GUI::StatusPanel::reset_printing_values(), ScalableButton::SetBitmap_(), ScalableButton::SetBitmapDisabled_(), LockButton::update_button_bitmaps(), Slic3r::GUI::StatusPanel::update_camera_state(), Slic3r::GUI::StatusPanel::update_sdcard_subtask(), Slic3r::GUI::ObjectSettings::update_settings_list(), and Slic3r::GUI::ObjectTableSettings::update_settings_list().
GetBmpHeight()
int ScalableBitmap::GetBmpHeight () const
{
#ifdef __APPLE__
    return m_bmp.GetScaledHeight();
#else
    return m_bmp.GetHeight();
#endif
}
References m_bmp.
Referenced by ScalableBitmap(), StepCtrl::StepCtrl(), StepIndicator::StepIndicator(), Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::AboutDialogLogo::onRepaint(), Slic3r::GUI::AuFile::PaintBackground(), AxisCtrlButton::render(), ImageSwitchButton::render(), FanSwitchButton::render(), StaticLine::render(), StepCtrl::Rescale(), and StepIndicator::Rescale().
GetBmpSize()
wxSize ScalableBitmap::GetBmpSize () const
{
#ifdef __APPLE__
    return m_bmp.GetScaledSize();
#else
    return m_bmp.GetSize();
#endif
}
References m_bmp.
Referenced by Slic3r::GUI::AboutDialogLogo::AboutDialogLogo(), CheckBox::CheckBox(), Slic3r::GUI::RadioBox::RadioBox(), Slic3r::GUI::Fan::create(), Slic3r::GUI::MaterialItem::doRender(), Slic3r::GUI::CameraItem::doRender(), Slic3r::GUI::MachineObjectPanel::doRender(), Slic3r::GUI::AMSextruderImage::doRender(), Slic3r::GUI::AMSRoad::doRender(), Slic3r::GUI::FanOperate::doRender(), Slic3r::GUI::SideTools::doRender(), StepCtrl::doRender(), StepIndicator::doRender(), SideButton::dorender(), TempInput::DoSetSize(), TextInput::DoSetSize(), TempInput::messureMiniSize(), Button::messureSize(), DropDown::messureSize(), SideButton::messureSize(), StaticLine::messureSize(), TempInput::messureSize(), StepCtrl::mouseDown(), BlinkingBitmap::msw_rescale(), Slic3r::GUI::AMSLib::on_left_down(), Slic3r::GUI::AuFile::on_mouse_left_up(), Slic3r::GUI::MachineObjectPanel::on_mouse_left_up(), Slic3r::GUI::AMSrefresh::paintEvent(), Slic3r::GUI::AuFile::PaintForeground(), Slic3r::GUI::ImageGrid::render(), Button::render(), DropDown::render(), TempInput::render(), TextInput::render(), CheckBox::Rescale(), Slic3r::GUI::RadioBox::Rescale(), and SwitchButton::Rescale().
GetBmpWidth()
int ScalableBitmap::GetBmpWidth () const
{
#ifdef __APPLE__
    return m_bmp.GetScaledWidth();
#else
    return m_bmp.GetWidth();
#endif
}
References m_bmp.
Referenced by Slic3r::GUI::PresetComboBox::fill_width_height(), Slic3r::GUI::AboutDialogLogo::onRepaint(), Slic3r::GUI::AuFile::PaintBackground(), Slic3r::GUI::RecenterDialog::render(), AxisCtrlButton::render(), ImageSwitchButton::render(), FanSwitchButton::render(), and StaticLine::render().
msw_rescale()
void ScalableBitmap::msw_rescale ()
{
    // BBS: support resize by fill border
    m_bmp = create_scaled_bitmap(m_icon_name, m_parent, m_px_cnt, m_grayscale, std::string(), false, m_resize);
}
References create_scaled_bitmap(), m_bmp, m_grayscale, m_icon_name, m_parent, m_px_cnt, and m_resize.
Referenced by ScalableBitmap(), Slic3r::GUI::CameraItem::msw_rescale(), Slic3r::GUI::ConfigWizardIndex::msw_rescale(), Slic3r::GUI::ObjectSettings::msw_rescale(), Slic3r::GUI::PresetComboBox::msw_rescale(), Slic3r::GUI::StatusPanel::msw_rescale(), Slic3r::GUI::AMSControl::msw_rescale(), Slic3r::GUI::Fan::msw_rescale(), LockButton::msw_rescale(), BlinkingBitmap::msw_rescale(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::StatusPanel::on_sys_color_changed(), Slic3r::GUI::MediaFilePanel::Rescale(), Button::Rescale(), CheckBox::Rescale(), Slic3r::GUI::RadioBox::Rescale(), SideButton::Rescale(), StaticLine::Rescale(), StepCtrl::Rescale(), StepIndicator::Rescale(), SwitchButton::Rescale(), TempInput::Rescale(), and TextInput::Rescale().
name()
const std::string & ScalableBitmap::name () const inline
{ return m_icon_name; }
References m_icon_name.
Referenced by Slic3r::GUI::Tab::create_preset_tab(), TextInput::Rescale(), ScalableButton::SetBitmap_(), and ScalableButton::SetBitmapDisabled_().
px_cnt()
int ScalableBitmap::px_cnt () const inline
{return m_px_cnt;}
References m_px_cnt.
Referenced by ScalableBitmap().
Member Data Documentation
m_bmp
wxBitmap ScalableBitmap::m_bmp = wxBitmap() private
Referenced by ScalableBitmap(), bmp(), bmp(), GetBmpHeight(), GetBmpSize(), GetBmpWidth(), and msw_rescale().
m_grayscale
bool ScalableBitmap::m_grayscale { false } private
Referenced by ScalableBitmap(), and msw_rescale().
m_icon_name
std::string ScalableBitmap::m_icon_name = "" private
Referenced by msw_rescale(), and name().
m_parent
wxWindow* ScalableBitmap::m_parent { nullptr } private
Referenced by msw_rescale().
m_px_cnt
int ScalableBitmap::m_px_cnt {16} private
Referenced by ScalableBitmap(), msw_rescale(), and px_cnt().
m_resize
bool ScalableBitmap::m_resize { false } private
Referenced by msw_rescale().
The documentation for this class was generated from the following files:
src/slic3r/GUI/wxExtensions.hpp
src/slic3r/GUI/wxExtensions.cpp