OrcaSlicer: src/mcut/include/mcut/internal/hmesh.h File Reference
hmesh.h File Reference
#include "mcut/internal/math.h"
#include "mcut/internal/utils.h"
#include <algorithm>
#include <limits>
#include <map>
#include <memory>
#include <vector>
#include <cstdint>
Classes
class descriptor_t_< T >
class halfedge_descriptor_t
class edge_descriptor_t
class face_descriptor_t
class vertex_descriptor_t
struct id_< T >
struct halfedge_data_t
struct edge_data_t
struct face_data_t
struct vertex_data_t
class hmesh_t
class array_iterator_t< V >
struct std::hash< vertex_descriptor_t >
struct std::hash< edge_descriptor_t >
struct std::hash< halfedge_descriptor_t >
struct std::hash< face_descriptor_t >
Namespaces
namespace std
STL namespace.
Typedefs
typedef std::vector< vertex_data_t > vertex_array_t
typedef std::vector< edge_data_t > edge_array_t
typedef std::vector< halfedge_data_t > halfedge_array_t
typedef std::vector< face_data_t > face_array_t
typedef array_iterator_t< face_array_t > face_array_iterator_t
typedef array_iterator_t< vertex_array_t > vertex_array_iterator_t
typedef array_iterator_t< edge_array_t > edge_array_iterator_t
typedef array_iterator_t< halfedge_array_t > halfedge_array_iterator_t
typedef vertex_descriptor_t vd_t
typedef halfedge_descriptor_t hd_t
typedef edge_descriptor_t ed_t
typedef face_descriptor_t fd_t
Functions
void write_off (const char *fpath, const hmesh_t &mesh)
void read_off (hmesh_t &mesh, const char *fpath)
template<>
edge_array_iterator_t::difference_type std::distance (edge_array_iterator_t first, edge_array_iterator_t last)
Class Documentation
id_
struct id_
template<typename T>
struct id_< T >
Class Members
typedef T type
Typedef Documentation
ed_t
typedef edge_descriptor_t ed_t
edge_array_iterator_t
typedef array_iterator_t<edge_array_t> edge_array_iterator_t
edge_array_t
typedef std::vector<edge_data_t> edge_array_t
face_array_iterator_t
typedef array_iterator_t<face_array_t> face_array_iterator_t
face_array_t
typedef std::vector<face_data_t> face_array_t
fd_t
typedef face_descriptor_t fd_t
halfedge_array_iterator_t
typedef array_iterator_t<halfedge_array_t> halfedge_array_iterator_t
halfedge_array_t
typedef std::vector<halfedge_data_t> halfedge_array_t
hd_t
typedef halfedge_descriptor_t hd_t
vd_t
typedef vertex_descriptor_t vd_t
vertex_array_iterator_t
typedef array_iterator_t<vertex_array_t> vertex_array_iterator_t
vertex_array_t
typedef std::vector<vertex_data_t> vertex_array_t
Function Documentation
read_off()
void read_off (hmesh_t & mesh, const char * fpath)
{
    auto next_line = [&](std::ifstream& f, std::string& s) -> bool {
        while (getline(f, s)) {
            if (s.length() > 1 && s[0] != '#') {
                return true;
            }
        }
        return false;
    };
    std::ifstream infile(fpath);
    if (!infile.is_open()) {
        printf("error: could not open file: %s\n", fpath);
        std::exit(1);
    }
    //
    // file header
    //
    std::string header;
    if (!next_line(infile, header)) {
        printf("error: .off file header not found\n");
        std::exit(1);
    }
    if (header != "OFF") {
        printf("error: unrecognised .off file header\n");
        std::exit(1);
    }
    //
    // #vertices, #faces, #edges
    //
    std::string info;
    if (!next_line(infile, info)) {
        printf("error: .off element count not found\n");
        std::exit(1);
    }
    std::istringstream info_stream;
    info_stream.str(info);
    int nvertices;
    int nfaces;
    int nedges;
    info_stream >> nvertices >> nfaces >> nedges;
    //
    // vertices
    //
    std::map<int, vd_t> vmap;
    for (int i = 0; i < nvertices; ++i) {
        if (!next_line(infile, info)) {
            printf("error: .off vertex not found\n");
            std::exit(1);
        }
        std::istringstream vtx_line_stream(info);
        double x;
        double y;
        double z;
        vtx_line_stream >> x >> y >> z;
        vmap[i] = mesh.add_vertex(x, y, z);
    }
    //
    // edges
    //
    for (int i = 0; i < nedges; ++i) {
        // TODO
    }
    //
    // faces
    //
    for (auto i = 0; i < nfaces; ++i) {
        if (!next_line(infile, info)) {
            printf("error: .off file face not found\n");
            std::exit(1);
        }
        std::istringstream face_line_stream(info);
        int n; // number of vertices in face
        int index;
        face_line_stream >> n;
        if (n < 3) {
            printf("error: invalid polygon vertex count in file (%d)\n", n);
            std::exit(1);
        }
        typename std::vector<vd_t> face;
        face.resize(n);
        for (int j = 0; j < n; ++j) {
            info_stream >> index;
            face[j] = vmap[index];
        }
        mesh.add_face(face);
    }
    infile.close();
}
References hmesh_t::add_face(), hmesh_t::add_vertex(), and n.
write_off()
void write_off (const char * fpath, const hmesh_t & mesh)
{
    std::ofstream outfile(fpath);
    if (!outfile.is_open()) {
        printf("error: could not open file: %s\n", fpath);
        std::exit(1);
    }
    //
    // file header
    //
    outfile << "OFF\n";
    //
    // #vertices, #faces, #edges
    //
    outfile << mesh.number_of_vertices() << " " << mesh.number_of_faces() << " " << 0 /*mesh.number_of_edges()*/ << "\n";
    //
    // vertices
    //
    for (vertex_array_iterator_t iter = mesh.vertices_begin(); iter != mesh.vertices_end(); ++iter) {
        // const vertex_data_t& vdata = iter.second;
        const vec3& point = mesh.vertex(*iter);
        outfile << (double)point.x() << " " << (double)point.y() << " " << (double)point.z() << "\n";
    }
    //
    // edges
    //
#if 0
    for (typename hmesh_t::edge_iterator_t iter = mesh.edges_begin(); iter != mesh.edges_end(); ++iter) {
        const hmesh_t::edge_descriptor_t ed = iter.first;
        const hmesh_t::vertex_descriptor_t& v0 = vertex(ed, 0);
        const hmesh_t::vertex_descriptor_t& v1 = vertex(ed, 1);
        // TODO
    }
#endif
    //
    // faces
    //
    for (face_array_iterator_t iter = mesh.faces_begin(); iter != mesh.faces_end(); ++iter) {
        // const typename hmesh_t::face_descriptor_t& fd = iter.first;
        const std::vector<vertex_descriptor_t> vertices_around_face = mesh.get_vertices_around_face(*iter);
        MCUT_ASSERT(!vertices_around_face.empty());
        outfile << vertices_around_face.size() << " ";
        for (std::vector<vertex_descriptor_t>::const_iterator i = vertices_around_face.cbegin(); i != vertices_around_face.cend(); ++i) {
            outfile << (*i) << " ";
        }
        outfile << " \n";
    }
    outfile.close();
}
References hmesh_t::edges_begin(), hmesh_t::edges_end(), hmesh_t::faces_begin(), hmesh_t::faces_end(), hmesh_t::get_vertices_around_face(), MCUT_ASSERT, hmesh_t::number_of_faces(), hmesh_t::number_of_vertices(), hmesh_t::vertex(), hmesh_t::vertices_begin(), hmesh_t::vertices_end(), vec2_< T >::x(), vec2_< T >::y(), and vec3_< T >::z().
Referenced by ImGuiTextBuffer::append(), ImGuiTextBuffer::appendfv(), and dump_mesh().