OrcaSlicer: Slic3r::GUI::GridCellSupportRenderer Class Reference
Slic3r::GUI::GridCellSupportRenderer Class Reference
#include <src/slic3r/GUI/GUI_ObjectTable.hpp>
Public Member Functions
virtual void Draw (wxGrid &grid, wxGridCellAttr &attr, wxDC &dc, const wxRect &rect, int row, int col, bool isSelected) wxOVERRIDE
virtual wxSize GetBestSize (wxGrid &WXUNUSED(grid), wxGridCellAttr &attr, wxDC &dc, int WXUNUSED(row), int WXUNUSED(col)) wxOVERRIDE
virtual GridCellSupportRenderer * Clone () const wxOVERRIDE
Detailed Description
Member Function Documentation
Clone()
GridCellSupportRenderer * Slic3r::GUI::GridCellSupportRenderer::Clone () const virtual
{
    return new GridCellSupportRenderer();
}
Draw()
void Slic3r::GUI::GridCellSupportRenderer::Draw (wxGrid & grid, wxGridCellAttr & attr, wxDC & dc, const wxRect & rect, int row, int col, bool isSelected) virtual
{
    /*ObjectGridTable *table = dynamic_cast<ObjectGridTable *>(grid.GetTable());
    wxRect text_rect = rect;
    if (table) {
        ObjectGridTable::ObjectGridCol* grid_col = table->get_grid_col(col);
        ObjectGridTable::ObjectGridRow* grid_row = table->get_grid_row(row - 1);
        ConfigOptionBool& cur_option = dynamic_cast<ConfigOptionBool&>((*grid_row)[(ObjectGridTable::GridColType)col]);
        wxString support_text;
        if (cur_option.value)
            support_text = L("Support Enabled");
        else
            support_text = L("Support Disabled");
        int text_width, text_height;
        grid.GetTextExtent(L("Support Disabled"), &text_width, &text_height, NULL, NULL, &Label::Body_10);
        int offset_x = grid_cell_border_width;
        int offset_y = (rect.height > text_height)?(rect.height - text_height)/2 : grid_cell_border_height;
        //dc.SetPen(*wxTRANSPARENT_PEN);
        //dc.SetBrush(wxBrush(attr.GetBackgroundColour()));
        //dc.DrawRectangle(rect);
        wxGridCellRenderer::Draw(grid, attr, dc, rect, row, col, isSelected);
        wxColour text_back_colour;
        wxColour text_fore_colour;
        if ( isSelected )
        {
            text_back_colour = grid.GetSelectionBackground();
            text_fore_colour = grid.GetSelectionForeground();
        }
        else
        {
            text_back_colour = attr.GetBackgroundColour();
            text_fore_colour = attr.GetTextColour();
        }
        dc.SetTextBackground(text_back_colour);
        dc.SetTextForeground(text_fore_colour);
        dc.DrawText(support_text, wxPoint(rect.x + offset_x, rect.y + offset_y));
        text_rect.x += text_width + grid_cell_border_width *2;
        text_rect.width -= (text_width + grid_cell_border_width *2);
        text_rect.y += offset_y;
        text_rect.height = grid_cell_checkbox_size;// + grid_cell_border_width *2;
        int flags = wxCONTROL_CELL;
        if (cur_option.value)
            flags |= wxCONTROL_CHECKED;
        wxRendererNative::Get().DrawCheckBox( &grid, dc, text_rect, flags );
    }*/
    //wxGridCellBoolRenderer::Draw(grid, attr, dc, rect, row, col, isSelected);
    ObjectGridTable *               table      = dynamic_cast<ObjectGridTable *>(grid.GetTable());
    ObjectGridTable::ObjectGridCol *grid_col   = table->get_grid_col(col);
    ObjectGridTable::ObjectGridRow *grid_row   = table->get_grid_row(row - 1);
    ConfigOptionBool &              cur_option = dynamic_cast<ConfigOptionBool &>((*grid_row)[(ObjectGridTable::GridColType) col]);
    auto height = grid.GetRowSize(row);
    auto width  = grid.GetColSize(col);
    wxGridCellRenderer::Draw(grid, attr, dc, rect, row, col, isSelected);
    if (cur_option.value) {
        auto check_on = create_scaled_bitmap("check_on", nullptr, 18);
        dc.SetPen(*wxTRANSPARENT_PEN);
        auto offsetx = 0;
        auto offsety = 0;
        #ifdef  __WXOSX_MAC__
        offsetx = (width - 18) / 2;
        offsety = (height - 18) / 2;
        #else
        offsetx = (width - check_on.GetSize().x) / 2;
        offsety = (height - check_on.GetSize().y) / 2;
        #endif //  __WXOSX_MAC__
        dc.DrawBitmap(check_on, rect.x + offsetx, rect.y + offsety);
    } else {
        auto check_off = create_scaled_bitmap("check_off_focused", nullptr, 18);
        dc.SetPen(*wxTRANSPARENT_PEN);
        auto offsetx = 0;
        auto offsety = 0;
        #ifdef __WXOSX_MAC__
        offsetx = (width - 18) / 2;
        offsety = (height - 18) / 2;
        #else
        offsetx = (width - check_off.GetSize().x) / 2;
        offsety = (height - check_off.GetSize().y) / 2;
        #endif //  __WXOSX_MAC__
        dc.DrawBitmap(check_off, rect.x + offsetx, rect.y + offsety);
    }
}
References col(), create_scaled_bitmap(), Slic3r::GUI::ObjectGridTable::get_grid_col(), Slic3r::GUI::ObjectGridTable::get_grid_row(), Slic3r::grid(), row(), and Slic3r::ConfigOptionSingle< T >::value.
GetBestSize()
wxSize Slic3r::GUI::GridCellSupportRenderer::GetBestSize (wxGrid & WXUNUSEDgrid, wxGridCellAttr & attr, wxDC & dc, int WXUNUSEDrow, int WXUNUSEDcol) virtual
{
/*
    int text_width, text_height, width;
    grid.GetTextExtent(L("Support Disabled"), &text_width, &text_height, NULL, NULL, &Label::Body_10);
    width = text_width + 3*grid_cell_border_width + grid_cell_checkbox_size;
    wxSize size{width, 20};
*/
    wxSize size{32, 20};
    return size;
}
References size.
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTable.hpp
src/slic3r/GUI/GUI_ObjectTable.cpp