OrcaSlicer: Slic3r::GUI::TabFilament Class Reference
Slic3r::GUI::TabFilament Class Reference
#include <src/slic3r/GUI/Tab.hpp>
Public Member Functions
TabFilament (ParamsPanel *parent)
~TabFilament ()
void build () override
void reload_config () override
void update_description_lines () override
void toggle_options () override
void update () override
void clear_pages () override
bool supports_printer_technology (const PrinterTechnology tech) const override
wxWindow * parent () const
wxString title () const
std::string name () const
Preset::Type type () const
bool completed () const
void create_preset_tab ()
void add_scaled_button (wxWindow *parent, ScalableButton **btn, const std::string &icon_name, const wxString &label=wxEmptyString, long style=wxBU_EXACTFIT|wxNO_BORDER)
void add_scaled_bitmap (wxWindow *parent, ScalableBitmap &btn, const std::string &icon_name)
void update_ui_items_related_on_parent_preset (const Preset *selected_preset_parent)
void load_current_preset ()
void reactive_preset_combo_box ()
void rebuild_page_tree ()
void update_btns_enabling ()
void update_preset_choice ()
bool select_preset (std::string preset_name="", bool delete_current=false, const std::string &last_selected_ph_printer_name="", bool force_select=false)
bool may_discard_current_dirty_preset (PresetCollection *presets=nullptr, const std::string &new_printer_name="", bool no_transfer=false)
virtual void activate_selected_page (std::function< void()> throw_if_canceled)
void OnTreeSelChange (wxCommandEvent &event)
void OnKeyDown (wxKeyEvent &event)
void compare_preset ()
void save_preset (std::string name=std::string(), bool detach=false, bool save_to_project=false, bool from_input=false, std::string input_name="")
void delete_preset ()
void toggle_show_hide_incompatible ()
void update_show_hide_incompatible_button ()
void update_ui_from_settings ()
void update_label_colours ()
void decorate ()
void update_changed_ui ()
void get_sys_and_mod_flags (const std::string &opt_key, bool &sys_page, bool &modified_page)
void update_changed_tree_ui ()
void update_undo_buttons ()
void on_roll_back_value (const bool to_sys=false)
PageShp add_options_page (const wxString &title, const std::string &icon, bool is_extruder_pages=false)
virtual void OnActivate ()
virtual void on_preset_loaded ()
virtual void init_options_list ()
virtual void update_custom_dirty ()
void load_initial_data ()
void update_dirty ()
void update_tab_ui (bool update_plater_presets=false)
void load_config (const DynamicPrintConfig &config)
void update_mode ()
void update_visibility ()
virtual void msw_rescale ()
virtual void sys_color_changed ()
Field * get_field (const t_config_option_key &opt_key, int opt_index=-1) const
Field * get_field (const t_config_option_key &opt_key, Page **selected_page, int opt_index=-1)
std::pair< OG_CustomCtrl *, bool * > get_custom_ctrl_with_blinking_ptr (const t_config_option_key &opt_key, int opt_index=-1)
void toggle_option (const std::string &opt_key, bool toggle, int opt_index=-1)
void toggle_line (const std::string &opt_key, bool toggle)
wxSizer * description_line_widget (wxWindow *parent, ogStaticText **StaticText, wxString text=wxEmptyString)
bool current_preset_is_dirty () const
bool saved_preset_is_dirty () const
void update_saved_preset_from_current_preset ()
DynamicPrintConfig * get_config ()
PresetCollection * get_presets ()
TabPresetComboBox * get_combo_box ()
virtual void on_value_change (const std::string &opt_key, const boost::any &value)
void update_wiping_button_visibility ()
void activate_option (const std::string &opt_key, const wxString &category)
void apply_searcher ()
void cache_config_diff (const std::vector< std::string > &selected_options)
void apply_config_from_cache ()
void show_timelapse_warning_dialog ()
const std::map< wxString, std::string > & get_category_icon_map ()
bool update_current_page_in_background (int &item)
void unselect_tree_item ()
void set_expanded (bool value)
void restore_last_select_item ()
bool validate_custom_gcodes ()
Static Public Member Functions
static wxString translate_category (const wxString &title, Preset::Type preset_type)
static bool validate_custom_gcode (const wxString &title, const std::string &gcode)
Public Attributes
PresetBundle * m_preset_bundle
bool m_show_btn_incompatible_presets = false
PresetCollection * m_presets = nullptr
DynamicPrintConfig * m_config
ogStaticText * m_parent_preset_description_line = nullptr
ScalableButton * m_detach_preset_btn = nullptr
std::map< std::string, wxColour > m_colored_Label_colors
int m_update_cnt = 0
SwitchButton * m_mode_view = nullptr
bool validate_custom_gcodes_was_shown { false }
Protected Types
enum OptStatus { osSystemValue = 1 , osInitValue = 2 }
Protected Member Functions
void set_type ()
void create_line_with_widget (ConfigOptionsGroup *optgroup, const std::string &opt_key, const std::string &path, widget_t widget)
wxSizer * compatible_widget_create (wxWindow *parent, PresetDependencies &deps)
void compatible_widget_reload (PresetDependencies &deps)
void load_key_value (const std::string &opt_key, const boost::any &value, bool saved_value=false)
bool tree_sel_change_delayed (wxCommandEvent &event)
void on_presets_changed ()
void build_preset_description_line (ConfigOptionsGroup *optgroup)
void update_preset_description_line ()
void update_frequently_changed_parameters ()
void set_tooltips_text ()
ConfigManipulation get_config_manipulation ()
Protected Attributes
ParamsPanel * m_parent
Preset::Type m_type
std::string m_name
const wxString m_title
TabPresetComboBox * m_presets_choice { nullptr }
wxPanel * m_top_panel
wxStaticText * m_static_title
wxBoxSizer * m_main_sizer
wxBoxSizer * m_top_sizer
wxBoxSizer * m_top_left_sizer
wxGridSizer * m_top_right_sizer
wxBoxSizer * m_select_sizer
wxBoxSizer * m_tree_sizer
ScalableButton * m_btn_compare_preset
ScalableButton * m_btn_save_preset
ScalableButton * m_btn_delete_preset
TabCtrl * m_tabctrl
wxImageList * m_icons
wxScrolledWindow * m_page_view {nullptr}
PresetDependencies m_compatible_printers
PresetDependencies m_compatible_prints
bool m_is_default_preset {false}
ScalableButton * m_undo_btn
ScalableButton * m_undo_to_sys_btn
ScalableButton * m_btn_search
StaticBox * m_search_item
TextInput * m_search_input
ScalableBitmap m_bmp_show_incompatible_presets
ScalableBitmap m_bmp_hide_incompatible_presets
ScalableBitmap m_bmp_value_lock
ScalableBitmap m_bmp_value_unlock
ScalableBitmap m_bmp_white_bullet
ScalableBitmap * m_bmp_non_system
ScalableBitmap m_bmp_value_revert
std::vector< ScalableButton * > m_scaled_buttons = {}
std::vector< ScalableBitmap * > m_scaled_bitmaps = {}
std::vector< ScalableBitmap > m_scaled_icons_list = {}
wxColour m_sys_label_clr
wxColour m_modified_label_clr
wxColour m_default_text_clr
wxString m_ttg_value_lock
wxString m_ttg_value_unlock
wxString m_ttg_white_bullet_ns
wxString * m_ttg_non_system
wxString m_ttg_white_bullet
wxString m_ttg_value_revert
wxString m_tt_value_lock
wxString m_tt_value_unlock
wxString * m_tt_non_system
wxString m_tt_white_bullet
wxString m_tt_value_revert
int m_icon_count
std::map< std::string, size_t > m_icon_index
std::map< wxString, std::string > m_category_icon
std::vector< PageShp > m_pages
Page * m_active_page {nullptr}
bool m_disable_tree_sel_changed_event {false}
bool m_show_incompatible_presets
int m_last_select_item = -1
std::vector< Preset::Type > m_dependent_tabs
std::map< std::string, int > m_options_list
int m_opt_status_value = 0
bool m_is_modified_values { false }
bool m_is_nonsys_values { true }
bool m_postpone_update_ui {false}
int m_em_unit
bool m_completed { false }
ConfigOptionMode m_mode = comAdvanced
struct Slic3r::GUI::Tab::Highlighter m_highlighter
DynamicPrintConfig m_cache_config
bool m_page_switch_running = false
bool m_page_switch_planned = false
bool m_is_timelapse_wipe_tower_already_prompted = false
ConfigManipulation m_config_manipulation
Private Member Functions
void add_filament_overrides_page ()
void update_filament_overrides_page ()
void update_volumetric_flow_preset_hints ()
Private Attributes
ogStaticText * m_volumetric_speed_description_line {nullptr}
ogStaticText * m_cooling_description_line {nullptr}
std::map< std::string, wxCheckBox * > m_overrides_options
Detailed Description
Member Enumeration Documentation
OptStatus
enum Slic3r::GUI::Tab::OptStatus protected inherited
Enumerator
osSystemValue
osInitValue
{ osSystemValue = 1, osInitValue = 2 };
Constructor & Destructor Documentation
TabFilament()
Slic3r::GUI::TabFilament::TabFilament (ParamsPanel * parent) inline
                                   :
    Tab(parent, _(L("Filament")), Slic3r::Preset::TYPE_FILAMENT) {}
~TabFilament()
Slic3r::GUI::TabFilament::~TabFilament () inline
{}
Member Function Documentation
activate_option()
void Slic3r::GUI::Tab::activate_option (const std::string & opt_key, const wxString & category) inherited
{
    wxString page_title = translate_category(category, m_type);
    auto cur_item = m_tabctrl->GetFirstVisibleItem();
    if (cur_item < 0)
        return;
    // We should to activate a tab with searched option, if it doesn't.
    // And do it before finding of the cur_item to avoid a case when Tab isn't activated jet and all treeItems are invisible
    //BBS: GUI refactor
    //wxGetApp().mainframe->select_tab(this);
    wxGetApp().mainframe->select_tab((wxPanel*)m_parent);
    while (cur_item >= 0) {
        if (page_title.empty()) {
            bool has = false;
            for (auto &g : m_pages[cur_item]->m_optgroups) {
                for (auto &l : g->get_lines()) {
                    for (auto &o : l.get_options()) { if (o.opt.opt_key == opt_key) { has = true; break; } }
                    if (has) break;
                }
                if (has) break;
            }
            if (!has) {
                cur_item = m_tabctrl->GetNextVisible(cur_item);
                continue;
            }
        } else {
            auto title = m_tabctrl->GetItemText(cur_item);
            if (page_title != title) {
                cur_item = m_tabctrl->GetNextVisible(cur_item);
                continue;
            }
        }
        m_tabctrl->SelectItem(cur_item);
        break;
    }
    auto set_focus = [](wxWindow* win) {
        win->SetFocus();
#ifdef WIN32
        if (wxTextCtrl* text = dynamic_cast<wxTextCtrl*>(win))
            text->SetSelection(-1, -1);
        else if (wxSpinCtrl* spin = dynamic_cast<wxSpinCtrl*>(win))
            spin->SetSelection(-1, -1);
#endif // WIN32
    };
    Field* field = get_field(opt_key);
    // focused selected field
    if (field) {
        set_focus(field->getWindow());
        if (!field->getWindow()->HasFocus()) {
            wxScrollEvent evt(wxEVT_SCROLL_CHANGED);
            evt.SetEventObject(field->getWindow());
            wxPostEvent(m_page_view, evt);
        }
    }
    //else if (category == "Single extruder MM setup") {
    //    // When we show and hide "Single extruder MM setup" page,
    //    // related options are still in the search list
    //    // So, let's hightlighte a "single_extruder_multi_material" option,
    //    // as a "way" to show hidden page again
    //    field = get_field("single_extruder_multi_material");
    //    if (field)
    //        set_focus(field->getWindow());
    //}
    m_highlighter.init(get_custom_ctrl_with_blinking_ptr(opt_key));
}
References Slic3r::GUI::Field::getWindow().
Referenced by Slic3r::GUI::Sidebar::jump_to_option().
activate_selected_page()
void Slic3r::GUI::Tab::activate_selected_page (std::function< void()> throw_if_canceled) virtual inherited
Reimplemented in Slic3r::GUI::TabPrintModel, and Slic3r::GUI::TabPrinter.
{
    if (!m_active_page)
        return;
    m_active_page->activate(m_mode, throw_if_canceled);
    update_changed_ui();
    update_description_lines();
    toggle_options();
    m_active_page->update_visibility(m_mode, true); // for taggle line
}
References Slic3r::GUI::Page::activate(), Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Tab::m_mode, Slic3r::GUI::Tab::toggle_options(), Slic3r::GUI::Tab::update_changed_ui(), Slic3r::GUI::Tab::update_description_lines(), and Slic3r::GUI::Page::update_visibility().
Referenced by Slic3r::GUI::TabPrintModel::activate_selected_page(), Slic3r::GUI::TabPrinter::activate_selected_page(), and Slic3r::GUI::Tab::tree_sel_change_delayed().
add_filament_overrides_page()
void Slic3r::GUI::TabFilament::add_filament_overrides_page () private
{
    //BBS
    PageShp page = add_options_page(L("Setting Overrides"), "empty");
    ConfigOptionsGroupShp optgroup = page->new_optgroup(L("Retraction"), L"param_retraction");
    auto append_single_option_line = [optgroup, this](const std::string& opt_key, int opt_index)
    {
        Line line {"",""};
        //BBS
        line = optgroup->create_single_option_line(optgroup->get_option(opt_key));
        line.near_label_widget = [this, optgroup, opt_key, opt_index](wxWindow* parent) {
            wxCheckBox* check_box = new wxCheckBox(parent, wxID_ANY, "");
            check_box->Bind(wxEVT_CHECKBOX, [optgroup, opt_key, opt_index](wxCommandEvent& evt) {
                const bool is_checked = evt.IsChecked();
                Field* field = optgroup->get_fieldc(opt_key, opt_index);
                if (field != nullptr) {
                    field->toggle(is_checked);
                    if (is_checked)
                        field->set_last_meaningful_value();
                    else
                        field->set_na_value();
                }
            }, check_box->GetId());
            m_overrides_options[opt_key] = check_box;
            return check_box;
        };
        optgroup->append_line(line);
    };
    const int extruder_idx = 0; // #ys_FIXME
    for (const std::string opt_key : {  "filament_retraction_length",
                                        "filament_z_hop",
                                        "filament_z_hop_types",
                                        "filament_retract_lift_above",
                                        "filament_retract_lift_below",
                                        "filament_retract_lift_enforce",
                                        "filament_retraction_speed",
                                        "filament_deretraction_speed",
                                        "filament_retract_restart_extra",
                                        "filament_retraction_minimum_travel",
                                        "filament_retract_when_changing_layer",
                                        "filament_wipe",
                                        //BBS
                                        "filament_wipe_distance",
                                        "filament_retract_before_wipe",
                                        //SoftFever
                                        // "filament_seam_gap"
                                     })
        append_single_option_line(opt_key, extruder_idx);
}
References Slic3r::GUI::Tab::add_options_page(), L, m_overrides_options, Slic3r::GUI::Line::near_label_widget, Slic3r::GUI::Tab::parent(), Slic3r::GUI::Field::set_last_meaningful_value(), Slic3r::GUI::Field::set_na_value(), and Slic3r::GUI::Field::toggle().
Referenced by build().
add_options_page()
Slic3r::GUI::PageShp Slic3r::GUI::Tab::add_options_page (const wxString & title, const std::string & icon, bool is_extruder_pages = false) inherited
{
    // Index of icon in an icon list $self->{icons}.
    auto icon_idx = 0;
    if (!icon.empty()) {
        icon_idx = (m_icon_index.find(icon) == m_icon_index.end()) ? -1 : m_icon_index.at(icon);
        if (icon_idx == -1) {
            // Add a new icon to the icon list.
            m_scaled_icons_list.push_back(ScalableBitmap(this, icon, 32, false, true));
            //m_icons->Add(m_scaled_icons_list.back().bmp());
            icon_idx = ++m_icon_count;
            m_icon_index[icon] = icon_idx;
        }
        if (m_category_icon.find(title) == m_category_icon.end()) {
            // Add new category to the category_to_icon list.
            m_category_icon[title] = icon;
        }
    }
    // Initialize the page.
    //BBS: GUI refactor
    PageShp page(new Page(m_page_view, title, icon_idx, this));
//  page->SetBackgroundStyle(wxBG_STYLE_SYSTEM);
#ifdef __WINDOWS__
//  page->SetDoubleBuffered(true);
#endif //__WINDOWS__
    if (dynamic_cast<TabPrint*>(this)) {
        page->m_split_multi_line = true;
        page->m_option_label_at_right = true;
    }
    if (!is_extruder_pages)
        m_pages.push_back(page);
    page->set_config(m_config);
    return page;
}
Referenced by add_filament_overrides_page(), Slic3r::GUI::TabPrintModel::build(), build(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::TabPrinter::build_kinematics_page(), and Slic3r::GUI::TabPrinter::build_unregular_pages().
add_scaled_bitmap()
void Slic3r::GUI::Tab::add_scaled_bitmap (wxWindow * parent, ScalableBitmap & btn, const std::string & icon_name) inherited
{
    bmp = ScalableBitmap(parent, icon_name);
    m_scaled_bitmaps.push_back(&bmp);
}
Referenced by Slic3r::GUI::Tab::create_preset_tab().
add_scaled_button()
void Slic3r::GUI::Tab::add_scaled_button (wxWindow * parent, ScalableButton ** btn, const std::string & icon_name, const wxString & label = wxEmptyString, long style = wxBU_EXACTFIT | wxNO_BORDER) inherited
{
    *btn = new ScalableButton(parent, wxID_ANY, icon_name, label, wxDefaultSize, wxDefaultPosition, style, true);
    (*btn)->SetBackgroundColour(parent->GetBackgroundColour());
    m_scaled_buttons.push_back(*btn);
}
References style.
Referenced by Slic3r::GUI::Tab::create_preset_tab().
apply_config_from_cache()
void Slic3r::GUI::Tab::apply_config_from_cache () inherited
{
    bool was_applied = false;
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(": enter");
    // check and apply extruders count for printer preset
    if (m_type == Preset::TYPE_PRINTER)
        was_applied = static_cast<TabPrinter*>(this)->apply_extruder_cnt_from_cache();
    if (!m_cache_config.empty()) {
        m_presets->get_edited_preset().config.apply(m_cache_config);
        m_cache_config.clear();
        was_applied = true;
    }
    if (was_applied)
        update_dirty();
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(": exit, was_applied=%1%")%was_applied;
}
References Slic3r::Preset::TYPE_PRINTER.
Referenced by Slic3r::GUI::Tab::on_presets_changed(), and Slic3r::GUI::Tab::select_preset().
apply_searcher()
void Slic3r::GUI::Tab::apply_searcher () inherited
{
    wxGetApp().sidebar().get_searcher().apply(m_config, m_type, m_mode);
}
Referenced by Slic3r::GUI::TabPrinter::build_unregular_pages().
build()
void Slic3r::GUI::TabFilament::build () override virtual
Implements Slic3r::GUI::Tab.
{
    m_presets = &m_preset_bundle->filaments;
    load_initial_data();
    auto page = add_options_page(L("Filament"), "spool");
        //BBS
        auto optgroup = page->new_optgroup(L("Basic information"), L"param_information");
        // Set size as all another fields for a better alignment
        Option option = optgroup->get_option("filament_type");
        option.opt.width = Field::def_width();
        optgroup->append_single_option_line(option);
        optgroup->append_single_option_line("filament_soluble");
        // BBS
        optgroup->append_single_option_line("filament_is_support");
        //optgroup->append_single_option_line("filament_colour");
        optgroup->append_single_option_line("required_nozzle_HRC");
        optgroup->append_single_option_line("default_filament_colour");
        optgroup->append_single_option_line("filament_diameter");
        optgroup->append_single_option_line("filament_flow_ratio");
        optgroup->append_single_option_line("enable_pressure_advance");
        optgroup->append_single_option_line("pressure_advance");
        optgroup->append_single_option_line("filament_density");
        optgroup->append_single_option_line("filament_shrink");
        optgroup->append_single_option_line("filament_cost");
        //BBS
        optgroup->append_single_option_line("temperature_vitrification");
        Line line = { L("Recommended nozzle temperature"), L("Recommended nozzle temperature range of this filament. 0 means no set") };
        line.append_option(optgroup->get_option("nozzle_temperature_range_low"));
        line.append_option(optgroup->get_option("nozzle_temperature_range_high"));
        optgroup->append_line(line);
        optgroup = page->new_optgroup(L("Recommended temperature range"), L"param_temperature");
        optgroup->append_single_option_line("bed_temperature_difference");
        optgroup = page->new_optgroup(L("Print temperature"), L"param_temperature");
        optgroup->append_single_option_line("chamber_temperature");
        optgroup->append_separator();
        line = { L("Nozzle"), L("Nozzle temperature when printing") };
        line.append_option(optgroup->get_option("nozzle_temperature_initial_layer"));
        line.append_option(optgroup->get_option("nozzle_temperature"));
        optgroup->append_line(line);
        line = { L("Cool plate"), L("Bed temperature when cool plate is installed. Value 0 means the filament does not support to print on the Cool Plate") };
        line.append_option(optgroup->get_option("cool_plate_temp_initial_layer"));
        line.append_option(optgroup->get_option("cool_plate_temp"));
        optgroup->append_line(line);
        line = { L("Engineering plate"), L("Bed temperature when engineering plate is installed. Value 0 means the filament does not support to print on the Engineering Plate") };
        line.append_option(optgroup->get_option("eng_plate_temp_initial_layer"));
        line.append_option(optgroup->get_option("eng_plate_temp"));
        optgroup->append_line(line);
        line = { L("High Temp Plate"), L("Bed temperature when high temperature plate is installed. Value 0 means the filament does not support to print on the High Temp Plate") };
        line.append_option(optgroup->get_option("hot_plate_temp_initial_layer"));
        line.append_option(optgroup->get_option("hot_plate_temp"));
        optgroup->append_line(line);
        line = {L("Textured PEI Plate"), L("Bed temperature when Textured PEI Plate is installed. Value 0 means the filament does not support to print on the Textured PEI Plate")};
        line.append_option(optgroup->get_option("textured_plate_temp_initial_layer"));
        line.append_option(optgroup->get_option("textured_plate_temp"));
        optgroup->append_line(line);
        optgroup->m_on_change = [this, optgroup](t_config_option_key opt_key, boost::any value)
        {
            DynamicPrintConfig& filament_config = wxGetApp().preset_bundle->filaments.get_edited_preset().config;
            update_dirty();
            /*if (opt_key == "cool_plate_temp" || opt_key == "cool_plate_temp_initial_layer") {
                m_config_manipulation.check_bed_temperature_difference(BedType::btPC, &filament_config);
            }
            else if (opt_key == "eng_plate_temp" || opt_key == "eng_plate_temp_initial_layer") {
                m_config_manipulation.check_bed_temperature_difference(BedType::btEP, &filament_config);
            }
            else if (opt_key == "hot_plate_temp" || opt_key == "hot_plate_temp_initial_layer") {
                m_config_manipulation.check_bed_temperature_difference(BedType::btPEI, &filament_config);
            }
            else if (opt_key == "textured_plate_temp" || opt_key == "textured_plate_temp_initial_layer") {
                m_config_manipulation.check_bed_temperature_difference(BedType::btPTE, &filament_config);
            }
            else */if (opt_key == "nozzle_temperature") {
                m_config_manipulation.check_nozzle_temperature_range(&filament_config);
            }
            else if (opt_key == "nozzle_temperature_initial_layer") {
                m_config_manipulation.check_nozzle_temperature_initial_layer_range(&filament_config);
            }
            on_value_change(opt_key, value);
        };
        //BBS
        optgroup = page->new_optgroup(L("Volumetric speed limitation"), L"param_volumetric_speed");
        optgroup->append_single_option_line("filament_max_volumetric_speed");
        //line = { "", "" };
        //line.full_width = 1;
        //line.widget = [this](wxWindow* parent) {
        //    return description_line_widget(parent, &m_volumetric_speed_description_line);
        //};
        //optgroup->append_line(line);
    page = add_options_page(L("Cooling"), "empty");
        //line = { "", "" };
        //line.full_width = 1;
        //line.widget = [this](wxWindow* parent) {
        //    return description_line_widget(parent, &m_cooling_description_line);
        //};
        //optgroup->append_line(line);
        optgroup = page->new_optgroup(L("Cooling for specific layer"), L"param_cooling");
        optgroup->append_single_option_line("close_fan_the_first_x_layers", "auto-cooling");
        optgroup->append_single_option_line("full_fan_speed_layer");
        optgroup = page->new_optgroup(L("Part cooling fan"), L"param_cooling_fan");
        line = { L("Min fan speed threshold"), L("Part cooling fan speed will start to run at min speed when the estimated layer time is no longer than the layer time in setting. When layer time is shorter than threshold, fan speed is interpolated between the minimum and maximum fan speed according to layer printing time") };
        line.label_path = "auto-cooling";
        line.append_option(optgroup->get_option("fan_min_speed"));
        line.append_option(optgroup->get_option("fan_cooling_layer_time"));
        optgroup->append_line(line);
        line = { L("Max fan speed threshold"), L("Part cooling fan speed will be max when the estimated layer time is shorter than the setting value") };
        line.label_path = "auto-cooling";
        line.append_option(optgroup->get_option("fan_max_speed"));
        line.append_option(optgroup->get_option("slow_down_layer_time"));
        optgroup->append_line(line);
        optgroup->append_single_option_line("reduce_fan_stop_start_freq");
        optgroup->append_single_option_line("slow_down_for_layer_cooling", "auto-cooling");
        optgroup->append_single_option_line("slow_down_min_speed");
        optgroup->append_single_option_line("enable_overhang_bridge_fan", "auto-cooling");
        optgroup->append_single_option_line("overhang_fan_threshold", "auto-cooling");
        optgroup->append_single_option_line("overhang_fan_speed", "auto-cooling");
        optgroup->append_single_option_line("support_material_interface_fan_speed");
        optgroup = page->new_optgroup(L("Auxiliary part cooling fan"), L"param_cooling_fan");
        optgroup->append_single_option_line("additional_cooling_fan_speed");
        //BBS
        add_filament_overrides_page();
#if 0
    //page = add_options_page(L("Advanced"), "advanced");
    //    optgroup = page->new_optgroup(L("Wipe tower parameters"));
    //    optgroup->append_single_option_line("filament_minimal_purge_on_wipe_tower");
#endif
        const int gcode_field_height = 15; // 150
    page = add_options_page(L("Advanced"), "advanced");
        optgroup = page->new_optgroup(L("Filament start G-code"), L"param_gcode", 0);
        optgroup->m_on_change = [this, optgroup](const t_config_option_key& opt_key, const boost::any& value) {
            validate_custom_gcode_cb(this, optgroup, opt_key, value);
        };
        option = optgroup->get_option("filament_start_gcode");
        option.opt.full_width = true;
        option.opt.is_code = true;
        option.opt.height = gcode_field_height;// 150;
        optgroup->append_single_option_line(option);
        optgroup = page->new_optgroup(L("Filament end G-code"), L"param_gcode", 0);
        optgroup->m_on_change = [this, optgroup](const t_config_option_key& opt_key, const boost::any& value) {
            validate_custom_gcode_cb(this, optgroup, opt_key, value);
        };
        option = optgroup->get_option("filament_end_gcode");
        option.opt.full_width = true;
        option.opt.is_code = true;
        option.opt.height = gcode_field_height;// 150;
        optgroup->append_single_option_line(option);
        //BBS
#if 0
    //page = add_options_page(L("Dependencies"), "advanced");
    //    optgroup = page->new_optgroup(L("Profile dependencies"));
    //    create_line_with_widget(optgroup.get(), "compatible_printers", "", [this](wxWindow* parent) {
    //        return compatible_widget_create(parent, m_compatible_printers);
    //    });
    //    option = optgroup->get_option("compatible_printers_condition");
    //    option.opt.full_width = true;
    //    optgroup->append_single_option_line(option);
    //    create_line_with_widget(optgroup.get(), "compatible_prints", "", [this](wxWindow* parent) {
    //        return compatible_widget_create(parent, m_compatible_prints);
    //    });
    //    option = optgroup->get_option("compatible_prints_condition");
    //    option.opt.full_width = true;
    //    optgroup->append_single_option_line(option);
    //    build_preset_description_line(optgroup.get());
#endif
}
References add_filament_overrides_page(), Slic3r::GUI::Tab::add_options_page(), Slic3r::GUI::Line::append_option(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_initial_layer_range(), Slic3r::GUI::ConfigManipulation::check_nozzle_temperature_range(), Slic3r::GUI::Field::def_width(), Slic3r::PresetBundle::filaments, Slic3r::ConfigOptionDef::full_width, Slic3r::ConfigOptionDef::height, Slic3r::ConfigOptionDef::is_code, L, Slic3r::GUI::Line::label_path, Slic3r::GUI::Tab::load_initial_data(), Slic3r::GUI::Tab::m_config_manipulation, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::GUI::Tab::m_presets, Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::Option::opt, Slic3r::GUI::Tab::update_dirty(), Slic3r::GUI::validate_custom_gcode_cb(), and Slic3r::ConfigOptionDef::width.
build_preset_description_line()
void Slic3r::GUI::Tab::build_preset_description_line (ConfigOptionsGroup * optgroup) protected inherited
{
    auto description_line = [this](wxWindow* parent) {
        return description_line_widget(parent, &m_parent_preset_description_line);
    };
    auto detach_preset_btn = [this](wxWindow* parent) {
        m_detach_preset_btn = new ScalableButton(parent, wxID_ANY, "lock_normal_sys", "",
                                                 wxDefaultSize, wxDefaultPosition, wxBU_LEFT | wxBU_EXACTFIT, true);
        ScalableButton* btn = m_detach_preset_btn;
        btn->SetFont(Slic3r::GUI::wxGetApp().normal_font());
        auto sizer = new wxBoxSizer(wxHORIZONTAL);
        sizer->Add(btn);
        //btn->Bind(wxEVT_BUTTON, [this, parent](wxCommandEvent&)
        //{
        //  bool system = m_presets->get_edited_preset().is_system;
        //  bool dirty  = m_presets->get_edited_preset().is_dirty;
        //    wxString msg_text = system ?
        //      _(L("A copy of the current system preset will be created, which will be detached from the system preset.")) :
        //        _(L("The current custom preset will be detached from the parent system preset."));
        //    if (dirty) {
         //     msg_text += "\n\n";
        //      msg_text += _(L("Modifications to the current profile will be saved."));
        //    }
        //    msg_text += "\n\n";
        //    msg_text += _(L("This action is not revertible.\nDo you want to proceed?"));
        //    //wxMessageDialog dialog(parent, msg_text, _(L("Detach preset")), wxICON_WARNING | wxYES_NO | wxCANCEL);
        //    MessageDialog dialog(parent, msg_text, _(L("Detach preset")), wxICON_WARNING | wxYES_NO | wxCANCEL);
        //    if (dialog.ShowModal() == wxID_YES)
        //        save_preset(m_presets->get_edited_preset().is_system ? std::string() : m_presets->get_edited_preset().name, true);
        //});
        btn->Hide();
        return sizer;
    };
    Line line = Line{ "", "" };
    line.full_width = 1;
    line.append_widget(description_line);
    line.append_widget(detach_preset_btn);
    optgroup->append_line(line);
}
References Slic3r::GUI::OptionsGroup::append_line(), Slic3r::GUI::Line::append_widget(), and Slic3r::GUI::Line::full_width.
cache_config_diff()
void Slic3r::GUI::Tab::cache_config_diff (const std::vector< std::string > & selected_options) inherited
{
    m_cache_config.apply_only(m_presets->get_edited_preset().config, selected_options);
}
Referenced by Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), and Slic3r::GUI::Tab::may_discard_current_dirty_preset().
clear_pages()
void Slic3r::GUI::TabFilament::clear_pages () override virtual
Reimplemented from Slic3r::GUI::Tab.
{
    Tab::clear_pages();
    m_volumetric_speed_description_line = nullptr;
  m_cooling_description_line = nullptr;
    //BBS: GUI refactor
    m_overrides_options.clear();
}
References Slic3r::GUI::Tab::clear_pages(), m_cooling_description_line, m_overrides_options, and m_volumetric_speed_description_line.
compare_preset()
void Slic3r::GUI::Tab::compare_preset () inherited
{
    wxGetApp().mainframe->diff_dialog.show(m_type);
}
References Slic3r::GUI::Tab::m_type.
compatible_widget_create()
wxSizer * Slic3r::GUI::Tab::compatible_widget_create (wxWindow * parent, PresetDependencies & deps) protected inherited
{
    deps.checkbox = new wxCheckBox(parent, wxID_ANY, _(L("All")));
    deps.checkbox->SetFont(Slic3r::GUI::wxGetApp().normal_font());
    wxGetApp().UpdateDarkUI(deps.checkbox, false, true);
    deps.btn = new ScalableButton(parent, wxID_ANY, "printer", from_u8((boost::format(" %s %s") % _utf8(L("Set")) % std::string(dots.ToUTF8())).str()),
                                  wxDefaultSize, wxDefaultPosition, wxBU_LEFT | wxBU_EXACTFIT, true);
    deps.btn->SetFont(Slic3r::GUI::wxGetApp().normal_font());
    deps.btn->SetSize(deps.btn->GetBestSize());
    auto sizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add((deps.checkbox), 0, wxALIGN_CENTER_VERTICAL);
    sizer->Add((deps.btn), 0, wxALIGN_CENTER_VERTICAL);
    deps.checkbox->Bind(wxEVT_CHECKBOX, ([this, &deps](wxCommandEvent e)
    {
        deps.btn->Enable(! deps.checkbox->GetValue());
        // All printers have been made compatible with this preset.
        if (deps.checkbox->GetValue())
            this->load_key_value(deps.key_list, std::vector<std::string> {});
        this->get_field(deps.key_condition)->toggle(deps.checkbox->GetValue());
        this->update_changed_ui();
    }) );
    deps.btn->Bind(wxEVT_BUTTON, ([this, parent, &deps](wxCommandEvent e)
    {
        // Collect names of non-default non-external profiles.
        PrinterTechnology printer_technology = m_preset_bundle->printers.get_edited_preset().printer_technology();
        PresetCollection &depending_presets  = (deps.type == Preset::TYPE_PRINTER) ? m_preset_bundle->printers :
                (printer_technology == ptFFF) ? m_preset_bundle->prints : m_preset_bundle->sla_prints;
        wxArrayString presets;
        for (size_t idx = 0; idx < depending_presets.size(); ++ idx)
        {
            Preset& preset = depending_presets.preset(idx);
            //BBS: add project embedded preset logic and refine is_external
            bool add = ! preset.is_default;
            //bool add = ! preset.is_default && ! preset.is_external;
            if (add && deps.type == Preset::TYPE_PRINTER)
                // Only add printers with the same technology as the active printer.
                add &= preset.printer_technology() == printer_technology;
            if (add)
                presets.Add(from_u8(preset.name));
        }
        wxMultiChoiceDialog dlg(parent, deps.dialog_title, deps.dialog_label, presets);
        wxGetApp().UpdateDlgDarkUI(&dlg);
        // Collect and set indices of depending_presets marked as compatible.
        wxArrayInt selections;
        auto *compatible_printers = dynamic_cast<const ConfigOptionStrings*>(m_config->option(deps.key_list));
        if (compatible_printers != nullptr || !compatible_printers->values.empty())
            for (auto preset_name : compatible_printers->values)
                for (size_t idx = 0; idx < presets.GetCount(); ++idx)
                    if (presets[idx] == preset_name) {
                        selections.Add(idx);
                        break;
                    }
        dlg.SetSelections(selections);
        std::vector<std::string> value;
        // Show the dialog.
        if (dlg.ShowModal() == wxID_OK) {
            selections.Clear();
            selections = dlg.GetSelections();
            for (auto idx : selections)
                value.push_back(presets[idx].ToUTF8().data());
            if (value.empty()) {
                deps.checkbox->SetValue(1);
                deps.btn->Disable();
            }
            // All depending_presets have been made compatible with this preset.
            this->load_key_value(deps.key_list, value);
            this->update_changed_ui();
        }
    }));
    return sizer;
}
References _, _utf8, Slic3r::GUI::Tab::PresetDependencies::btn, Slic3r::GUI::Tab::PresetDependencies::checkbox, Slic3r::GUI::Tab::PresetDependencies::dialog_label, Slic3r::GUI::Tab::PresetDependencies::dialog_title, Slic3r::GUI::dots(), Slic3r::GUI::from_u8(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::Tab::get_field(), Slic3r::Preset::is_default, Slic3r::GUI::Tab::PresetDependencies::key_condition, Slic3r::GUI::Tab::PresetDependencies::key_list, L, Slic3r::GUI::Tab::load_key_value(), Slic3r::GUI::Tab::m_config, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::Preset::name, Slic3r::ConfigBase::option(), Slic3r::GUI::Tab::parent(), Slic3r::PresetCollection::preset(), Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::PresetBundle::prints, Slic3r::ptFFF, Slic3r::PresetCollection::size(), Slic3r::PresetBundle::sla_prints, Slic3r::GUI::Field::toggle(), Slic3r::GUI::Tab::PresetDependencies::type, Slic3r::Preset::TYPE_PRINTER, Slic3r::GUI::Tab::update_changed_ui(), and wxEVT_BUTTON.
compatible_widget_reload()
void Slic3r::GUI::Tab::compatible_widget_reload (PresetDependencies & deps) protected inherited
{
    Field* field = this->get_field(deps.key_condition);
    if (!field)
        return;
    bool has_any = ! m_config->option<ConfigOptionStrings>(deps.key_list)->values.empty();
    has_any ? deps.btn->Enable() : deps.btn->Disable();
    deps.checkbox->SetValue(! has_any);
    field->toggle(! has_any);
}
References Slic3r::GUI::Tab::PresetDependencies::btn, Slic3r::GUI::Tab::PresetDependencies::checkbox, Slic3r::ConfigOptionVector< T >::empty(), Slic3r::GUI::Tab::get_field(), Slic3r::GUI::Tab::PresetDependencies::key_condition, Slic3r::GUI::Tab::PresetDependencies::key_list, Slic3r::GUI::Tab::m_config, Slic3r::ConfigBase::option(), and Slic3r::GUI::Field::toggle().
Referenced by reload_config(), Slic3r::GUI::TabSLAMaterial::reload_config(), and Slic3r::GUI::TabSLAPrint::reload_config().
completed()
bool Slic3r::GUI::Tab::completed () const inline inherited
{ return m_completed; }
References Slic3r::GUI::Tab::m_completed.
Referenced by Slic3r::GUI::GUI_App::get_tab().
create_line_with_widget()
void Slic3r::GUI::Tab::create_line_with_widget (ConfigOptionsGroup * optgroup, const std::string & opt_key, const std::string & path, widget_t widget) protected inherited
{
    Line line = optgroup->create_single_option_line(opt_key);
    line.widget = widget;
    line.label_path = path;
    m_colored_Label_colors[opt_key] = m_default_text_clr;
    line.full_Label_color = &m_colored_Label_colors[opt_key];
    optgroup->append_line(line);
}
References Slic3r::GUI::OptionsGroup::append_line(), Slic3r::GUI::ConfigOptionsGroup::create_single_option_line(), Slic3r::GUI::Line::full_Label_color, Slic3r::GUI::Line::label_path, Slic3r::GUI::Tab::m_colored_Label_colors, Slic3r::GUI::Tab::m_default_text_clr, and Slic3r::GUI::Line::widget.
Referenced by Slic3r::GUI::TabPrinter::build_fff().
create_preset_tab()
void Slic3r::GUI::Tab::create_preset_tab () inherited
{
//move to ParamsPanel
/*#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__*/
    auto panel = this;
    m_preset_bundle = wxGetApp().preset_bundle;
    // Vertical sizer to hold the choice menu and the rest of the page.
/*#ifdef __WXOSX__
    auto  *main_sizer = new wxBoxSizer(wxVERTICAL);
    main_sizer->SetSizeHints(this);
    this->SetSizer(main_sizer);
    // Create additional panel to Fit() it from OnActivate()
    // It's needed for tooltip showing on OSX
    m_tmp_panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBK_LEFT | wxTAB_TRAVERSAL);
    auto panel = m_tmp_panel;
    auto  sizer = new wxBoxSizer(wxVERTICAL);
    m_tmp_panel->SetSizer(sizer);
    m_tmp_panel->Layout();
    main_sizer->Add(m_tmp_panel, 1, wxEXPAND | wxALL, 0);
#else
    Tab *panel = this;
    auto  *sizer = new wxBoxSizer(wxVERTICAL);
    sizer->SetSizeHints(panel);
    panel->SetSizer(sizer);
#endif //__WXOSX__*/
    // BBS: model config
    if (m_type < Preset::TYPE_COUNT) {
        // preset chooser
        m_presets_choice = new TabPresetComboBox(panel, m_type);
        // m_presets_choice->SetFont(Label::Body_10); // BBS
        m_presets_choice->set_selection_changed_function([this](int selection) {
            if (!m_presets_choice->selection_is_changed_according_to_physical_printers())
            {
                if (m_type == Preset::TYPE_PRINTER && !m_presets_choice->is_selected_physical_printer())
                    m_preset_bundle->physical_printers.unselect_printer();
                // select preset
                std::string preset_name = m_presets_choice->GetString(selection).ToUTF8().data();
                select_preset(Preset::remove_suffix_modified(preset_name));
            }
        });
    }
    auto color = wxSystemSettings::GetColour(wxSYS_COLOUR_WINDOW);
    //buttons
    m_scaled_buttons.reserve(6);
    m_scaled_bitmaps.reserve(4);
    m_top_panel = new wxPanel(this, wxID_ANY, wxDefaultPosition, wxDefaultSize);
    // BBS: open this tab by select first
    m_top_panel->SetBackgroundColour(*wxWHITE);
    m_top_panel->Bind(wxEVT_LEFT_UP, [this](auto & e) {
        restore_last_select_item();
    });
    //add_scaled_button(panel, &m_btn_compare_preset, "compare");
    add_scaled_button(m_top_panel, &m_btn_save_preset, "save");
    add_scaled_button(m_top_panel, &m_btn_delete_preset, "cross");
    //if (m_type == Preset::Type::TYPE_PRINTER)
    //    add_scaled_button(panel, &m_btn_edit_ph_printer, "cog");
    m_show_incompatible_presets = false;
    add_scaled_bitmap(this, m_bmp_show_incompatible_presets, "flag_red");
    add_scaled_bitmap(this, m_bmp_hide_incompatible_presets, "flag_green");
    //add_scaled_button(panel, &m_btn_hide_incompatible_presets, m_bmp_hide_incompatible_presets.name());
    //m_btn_compare_preset->SetToolTip(_L("Compare presets"));
    // TRN "Save current Settings"
    m_btn_save_preset->SetToolTip(wxString::Format(_L("Save current %s"), m_title));
    m_btn_delete_preset->SetToolTip(_(L("Delete this preset")));
    m_btn_delete_preset->Hide();
    /*add_scaled_button(panel, &m_question_btn, "question");
    m_question_btn->SetToolTip(_(L("Hover the cursor over buttons to find more information \n"
                                   "or click this button.")));
    add_scaled_button(panel, &m_search_btn, "search");
    m_search_btn->SetToolTip(format_wxstr(_L("Search in settings [%1%]"), "Ctrl+F"));*/
    // Bitmaps to be shown on the "Revert to system" aka "Lock to system" button next to each input field.
    add_scaled_bitmap(this, m_bmp_value_lock  , "unlock_normal");
    add_scaled_bitmap(this, m_bmp_value_unlock, "lock_normal");
    m_bmp_non_system = &m_bmp_white_bullet;
    // Bitmaps to be shown on the "Undo user changes" button next to each input field.
    add_scaled_bitmap(this, m_bmp_value_revert, "undo");
    add_scaled_bitmap(this, m_bmp_white_bullet, "dot");
    set_tooltips_text();
    add_scaled_button(m_top_panel, &m_undo_btn,        m_bmp_white_bullet.name());
    add_scaled_button(m_top_panel, &m_undo_to_sys_btn, m_bmp_white_bullet.name());
    add_scaled_button(m_top_panel, &m_btn_search,      "search");
    m_btn_search->SetToolTip(_L("Search in preset"));
    //search input
    m_search_item = new StaticBox(m_top_panel);
    StateColor box_colour(std::pair<wxColour, int>(*wxWHITE, StateColor::Normal));
    StateColor box_border_colour(std::pair<wxColour, int>(wxColour(238, 238, 238), StateColor::Normal));
    m_search_item->SetBackgroundColor(box_colour);
    m_search_item->SetBorderColor(box_border_colour);
    m_search_item->SetCornerRadius(5);
    //StateColor::darkModeColorFor(wxColour(238, 238, 238)), wxDefaultPosition, wxSize(m_top_panel->GetSize().GetWidth(), 3 * wxGetApp().em_unit()), 8);
    auto search_sizer = new wxBoxSizer(wxHORIZONTAL);
    m_search_input = new TextInput(m_search_item, wxEmptyString, wxEmptyString, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 | wxBORDER_NONE);
    m_search_input->SetBackgroundColour(wxColour(238, 238, 238));
    m_search_input->SetForegroundColour(wxColour(43, 52, 54));
    m_search_input->SetFont(wxGetApp().bold_font());
    search_sizer->Add(new wxWindow(m_search_item, wxID_ANY, wxDefaultPosition, wxSize(0, 0)), 0, wxEXPAND|wxLEFT|wxRIGHT, FromDIP(6));
    search_sizer->Add(m_search_input, 1, wxEXPAND | wxALL, FromDIP(2));
    //bbl for linux
    //search_sizer->Add(new wxWindow(m_search_input, wxID_ANY, wxDefaultPosition, wxSize(0, 0)), 0, wxEXPAND | wxLEFT, 16);
     m_search_item->Bind(wxEVT_LEFT_DOWN, [this](wxMouseEvent &e) {
        m_search_input->SetFocus();
    });
    m_search_input->Bind(wxCUSTOMEVT_EXIT_SEARCH, [this](wxCommandEvent &) {
         Freeze();
        if (m_presets_choice) m_presets_choice->Show();
        m_btn_save_preset->Show();
        m_btn_search->Show();
        m_search_item->Hide();
        m_search_item->Refresh();
        m_search_item->Update();
        m_search_item->Layout();
        this->GetParent()->Refresh();
        this->GetParent()->Update();
        this->GetParent()->Layout();
        Thaw();
    });
    m_search_item->SetSizer(search_sizer);
    m_search_item->Layout();
    search_sizer->Fit(m_search_item);
    m_search_item->Hide();
    //m_btn_search->SetId(wxID_FIND_PROCESS);
    m_btn_search->Bind(
        wxEVT_BUTTON,
        [this](wxCommandEvent &) {
         Freeze();
         if (m_presets_choice)
             m_presets_choice->Hide();
         m_btn_save_preset->Hide();
         m_btn_search->Hide();
         m_search_item->Show();
         this->GetParent()->Refresh();
         this->GetParent()->Update();
         this->GetParent()->Layout();
         wxGetApp().plater()->search(false, m_type, m_top_panel->GetParent(), m_search_input, m_btn_search);
         Thaw();
        });
    m_undo_btn->Bind(wxEVT_BUTTON, ([this](wxCommandEvent) { on_roll_back_value(); }));
    m_undo_to_sys_btn->Bind(wxEVT_BUTTON, ([this](wxCommandEvent) { on_roll_back_value(true); }));
    /* m_search_btn->Bind(wxEVT_BUTTON, [](wxCommandEvent) { wxGetApp().plater()->search(false); });*/
    // Colors for ui "decoration"
    m_sys_label_clr     = wxGetApp().get_label_clr_sys();
    m_modified_label_clr  = wxGetApp().get_label_clr_modified();
    m_default_text_clr      = wxGetApp().get_label_clr_default();
    m_main_sizer = new wxBoxSizer( wxVERTICAL );
    m_top_sizer = new wxBoxSizer( wxHORIZONTAL );
    // BBS: model config
    if (m_presets_choice) {
        m_presets_choice->Reparent(m_top_panel);
        m_top_sizer->Add(m_presets_choice, 1, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL, 10);
    } else {
        m_top_sizer->AddSpacer(10);
        m_top_sizer->AddStretchSpacer(1);
    }
    const float scale_factor = /*wxGetApp().*/em_unit(this)*0.1;// GetContentScaleFactor();
#ifndef DISABLE_UNDO_SYS
    m_top_sizer->Add( m_undo_to_sys_btn, 0, wxALIGN_CENTER_VERTICAL);
    m_top_sizer->AddSpacer(8);
#endif
    m_top_sizer->Add( m_undo_btn, 0, wxALIGN_CENTER_VERTICAL);
    m_top_sizer->Add( m_btn_save_preset, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, 8  );
    m_top_sizer->Add( m_btn_delete_preset, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, 8 );
    m_top_sizer->Add( m_btn_search, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, 8 );
    m_top_sizer->Add( m_search_item, 1, wxALIGN_CENTER_VERTICAL | wxRIGHT , 8 );
    if (dynamic_cast<TabPrint*>(this) == nullptr) {
        m_static_title = new Label(m_top_panel, Label::Body_12, _L("Advance"));
        m_static_title->Wrap( -1 );
        // BBS: open this tab by select first
        m_static_title->Bind(wxEVT_LEFT_UP, [this](auto& e) {
            restore_last_select_item();
        });
        m_top_sizer->Add( m_static_title, 0, wxALIGN_CENTER_VERTICAL | wxLEFT, 8 );
        m_mode_view = new SwitchButton(m_top_panel, wxID_ABOUT);
        m_top_sizer->AddSpacer(4);
        m_top_sizer->Add( m_mode_view, 0, wxALIGN_CENTER_VERTICAL);
    }
    m_top_sizer->AddSpacer(10);
    m_top_sizer->SetMinSize(-1, 3 * m_em_unit);
    m_top_panel->SetSizer(m_top_sizer);
    if (m_presets_choice)
        m_main_sizer->Add(m_top_panel, 0, wxEXPAND | wxUP | wxDOWN, m_em_unit);
    else
        m_top_panel->Hide();
#if 0
#ifdef _MSW_DARK_MODE
    // Sizer with buttons for mode changing
    if (wxGetApp().tabs_as_menu())
#endif
        m_mode_sizer = new ModeSizer(panel, int (0.5*em_unit(this)));
    const float scale_factor = /*wxGetApp().*/em_unit(this)*0.1;// GetContentScaleFactor();
    m_hsizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add(m_hsizer, 0, wxEXPAND | wxBOTTOM, 3);
    m_hsizer->Add(m_presets_choice, 0, wxLEFT | wxRIGHT | wxTOP | wxALIGN_CENTER_VERTICAL, 3);
    m_hsizer->AddSpacer(int(4*scale_factor));
    m_hsizer->Add(m_btn_save_preset, 0, wxALIGN_CENTER_VERTICAL);
    m_hsizer->AddSpacer(int(4 * scale_factor));
    m_hsizer->Add(m_btn_delete_preset, 0, wxALIGN_CENTER_VERTICAL);
    if (m_btn_edit_ph_printer) {
        m_hsizer->AddSpacer(int(4 * scale_factor));
        m_hsizer->Add(m_btn_edit_ph_printer, 0, wxALIGN_CENTER_VERTICAL);
    }
    m_hsizer->AddSpacer(int(/*16*/8 * scale_factor));
    m_hsizer->Add(m_btn_hide_incompatible_presets, 0, wxALIGN_CENTER_VERTICAL);
    m_hsizer->AddSpacer(int(8 * scale_factor));
    m_hsizer->Add(m_question_btn, 0, wxALIGN_CENTER_VERTICAL);
    m_hsizer->AddSpacer(int(32 * scale_factor));
    m_hsizer->Add(m_undo_to_sys_btn, 0, wxALIGN_CENTER_VERTICAL);
    m_hsizer->Add(m_undo_btn, 0, wxALIGN_CENTER_VERTICAL);
    m_hsizer->AddSpacer(int(32 * scale_factor));
    m_hsizer->Add(m_search_btn, 0, wxALIGN_CENTER_VERTICAL);
    m_hsizer->AddSpacer(int(8*scale_factor));
    m_hsizer->Add(m_btn_compare_preset, 0, wxALIGN_CENTER_VERTICAL);
    m_hsizer->AddSpacer(int(16*scale_factor));
    // m_hsizer->AddStretchSpacer(32);
    // StretchSpacer has a strange behavior under OSX, so
    // There is used just additional sizer for m_mode_sizer with right alignment
    if (m_mode_sizer) {
        auto mode_sizer = new wxBoxSizer(wxVERTICAL);
        // Don't set the 2nd parameter to 1, making the sizer rubbery scalable in Y axis may lead
        // to wrong vertical size assigned to wxBitmapComboBoxes, see GH issue #7176.
        mode_sizer->Add(m_mode_sizer, 0, wxALIGN_RIGHT);
        m_hsizer->Add(mode_sizer, 1, wxALIGN_CENTER_VERTICAL | wxRIGHT, wxOSX ? 15 : 10);
    }
    //Horizontal sizer to hold the tree and the selected page.
    m_hsizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add(m_hsizer, 1, wxEXPAND, 0);
    //left vertical sizer
    m_left_sizer = new wxBoxSizer(wxVERTICAL);
    m_hsizer->Add(m_left_sizer, 0, wxEXPAND | wxLEFT | wxTOP | wxBOTTOM, 3);
#endif
    // tree
    m_tabctrl = new TabCtrl(panel, wxID_ANY, wxDefaultPosition, wxSize(20 * m_em_unit, -1),
        wxTR_NO_BUTTONS | wxTR_HIDE_ROOT | wxTR_SINGLE | wxTR_NO_LINES | wxBORDER_NONE | wxWANTS_CHARS | wxTR_FULL_ROW_HIGHLIGHT);
    m_tabctrl->Bind(wxEVT_RIGHT_DOWN, [this](auto &e) {}); // disable right select
    m_tabctrl->SetFont(Label::Body_14);
    //m_left_sizer->Add(m_tabctrl, 1, wxEXPAND);
    const int img_sz = int(32 * scale_factor + 0.5f);
    m_icons = new wxImageList(img_sz, img_sz, false, 1);
    // Index of the last icon inserted into $self->{icons}.
    m_icon_count = -1;
    m_tabctrl->AssignImageList(m_icons);
    wxGetApp().UpdateDarkUI(m_tabctrl);
    // Delay processing of the following handler until the message queue is flushed.
    // This helps to process all the cursor key events on Windows in the tree control,
    // so that the cursor jumps to the last item.
    // BBS: bold selection
    m_tabctrl->Bind(wxEVT_TAB_SEL_CHANGING, [this](wxCommandEvent& event) {
        if (m_disable_tree_sel_changed_event)
            return;
        const auto sel_item = m_tabctrl->GetSelection();
        //OutputDebugStringA("wxEVT_TAB_SEL_CHANGING ");
        //OutputDebugStringA(m_title.c_str());
        //const auto selection = sel_item >= 0 ? m_tabctrl->GetItemText(sel_item) : "";
        //OutputDebugString(selection);
        //OutputDebugStringA("\n");
        m_tabctrl->SetItemBold(sel_item, false);
        });
    m_tabctrl->Bind(wxEVT_TAB_SEL_CHANGED, [this](wxCommandEvent& event) {
#ifdef __linux__
        // Events queue is opposite On Linux. wxEVT_SET_FOCUS invokes after wxEVT_TAB_SEL_CHANGED,
        // and a result wxEVT_KILL_FOCUS doesn't invoke for the TextCtrls.
        // So, call SetFocus explicitly for this control before changing of the selection
        m_tabctrl->SetFocus();
#endif
            if (!m_disable_tree_sel_changed_event && !m_pages.empty()) {
                if (m_page_switch_running)
                    m_page_switch_planned = true;
                else {
                    m_page_switch_running = true;
                    do {
                        m_page_switch_planned = false;
                        m_tabctrl->Update();
                    } while (this->tree_sel_change_delayed(event));
                    m_page_switch_running = false;
                }
            }
        });
    m_tabctrl->Bind(wxEVT_KEY_DOWN, &Tab::OnKeyDown, this);
    m_main_sizer->Add(m_tabctrl, 1, wxEXPAND | wxALL, 0 );
    this->SetSizer(m_main_sizer);
    //this->Layout();
    m_page_view = m_parent->get_paged_view();
    // Initialize the page.
/*#ifdef __WXOSX__
    auto page_parent = m_tmp_panel;
#else
    auto page_parent = this;
#endif
    m_page_view = new wxScrolledWindow(page_parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL);
    m_page_sizer = new wxBoxSizer(wxVERTICAL);
    m_page_view->SetSizer(m_page_sizer);
    m_page_view->SetScrollbars(1, 20, 1, 2);
    m_hsizer->Add(m_page_view, 1, wxEXPAND | wxLEFT, 5);*/
    //m_btn_compare_preset->Bind(wxEVT_BUTTON, ([this](wxCommandEvent e) { compare_preset(); }));
    m_btn_save_preset->Bind(wxEVT_BUTTON, ([this](wxCommandEvent e) { save_preset(); }));
    m_btn_delete_preset->Bind(wxEVT_BUTTON, ([this](wxCommandEvent e) { delete_preset(); }));
    /*m_btn_hide_incompatible_presets->Bind(wxEVT_BUTTON, ([this](wxCommandEvent e) {
        toggle_show_hide_incompatible();
    }));
    if (m_btn_edit_ph_printer)
        m_btn_edit_ph_printer->Bind(wxEVT_BUTTON, [this](wxCommandEvent e) {
            if (m_preset_bundle->physical_printers.has_selection())
                m_presets_choice->edit_physical_printer();
            else
                m_presets_choice->add_physical_printer();
        });*/
    // Initialize the DynamicPrintConfig by default keys/values.
    build();
    // ys_FIXME: Following should not be needed, the function will be called later
    // (update_mode->update_visibility->rebuild_page_tree). This does not work, during the
    // second call of rebuild_page_tree m_tabctrl->GetFirstVisibleItem(); returns zero
    // for some unknown reason (and the page is not refreshed until user does a selection).
    rebuild_page_tree();
    m_completed = true;
}
References _, _L, Slic3r::GUI::Tab::add_scaled_bitmap(), Slic3r::GUI::Tab::add_scaled_button(), TabCtrl::AssignImageList(), Label::Body_12, Label::Body_14, em_unit(), TabCtrl::GetSelection(), int, L, Slic3r::GUI::Tab::m_bmp_hide_incompatible_presets, Slic3r::GUI::Tab::m_bmp_non_system, Slic3r::GUI::Tab::m_bmp_show_incompatible_presets, Slic3r::GUI::Tab::m_bmp_value_lock, Slic3r::GUI::Tab::m_bmp_value_revert, Slic3r::GUI::Tab::m_bmp_value_unlock, Slic3r::GUI::Tab::m_bmp_white_bullet, Slic3r::GUI::Tab::m_btn_compare_preset, Slic3r::GUI::Tab::m_btn_delete_preset, Slic3r::GUI::Tab::m_btn_save_preset, Slic3r::GUI::Tab::m_btn_search, Slic3r::GUI::Tab::m_default_text_clr, Slic3r::GUI::Tab::m_disable_tree_sel_changed_event, Slic3r::GUI::Tab::m_em_unit, Slic3r::GUI::Tab::m_icon_count, Slic3r::GUI::Tab::m_icons, Slic3r::GUI::Tab::m_main_sizer, Slic3r::GUI::Tab::m_mode_view, Slic3r::GUI::Tab::m_modified_label_clr, Slic3r::GUI::Tab::m_pages, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::GUI::Tab::m_presets_choice, Slic3r::GUI::Tab::m_scaled_bitmaps, Slic3r::GUI::Tab::m_scaled_buttons, Slic3r::GUI::Tab::m_search_input, Slic3r::GUI::Tab::m_search_item, Slic3r::GUI::Tab::m_show_incompatible_presets, Slic3r::GUI::Tab::m_static_title, Slic3r::GUI::Tab::m_sys_label_clr, Slic3r::GUI::Tab::m_tabctrl, Slic3r::GUI::Tab::m_title, Slic3r::GUI::Tab::m_top_panel, Slic3r::GUI::Tab::m_top_sizer, Slic3r::GUI::Tab::m_type, Slic3r::GUI::Tab::m_undo_btn, Slic3r::GUI::Tab::m_undo_to_sys_btn, ScalableBitmap::name(), StateColor::Normal, Slic3r::GUI::Tab::on_roll_back_value(), Slic3r::GUI::Tab::restore_last_select_item(), Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers(), Slic3r::GUI::PresetComboBox::set_selection_changed_function(), Slic3r::GUI::Tab::set_tooltips_text(), StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), TabCtrl::SetFont(), TabCtrl::SetItemBold(), Slic3r::Preset::TYPE_COUNT, wxEVT_BUTTON, Slic3r::GUI::wxMouseEvent, and wxOSX.
Referenced by Slic3r::GUI::MainFrame::add_created_tab().
current_preset_is_dirty()
bool Slic3r::GUI::Tab::current_preset_is_dirty () const inherited
{ return m_presets->current_is_dirty(); }
References Slic3r::PresetCollection::current_is_dirty(), and Slic3r::GUI::Tab::m_presets.
decorate()
void Slic3r::GUI::Tab::decorate () inherited
{
    for (const auto& opt : m_options_list)
    {
        Field*      field = nullptr;
        wxColour*   colored_label_clr = nullptr;
        if (opt.first == "printable_area" ||
            opt.first == "compatible_prints" || opt.first == "compatible_printers")
            colored_label_clr = (m_colored_Label_colors.find(opt.first) == m_colored_Label_colors.end()) ? nullptr : &m_colored_Label_colors.at(opt.first);
        if (!colored_label_clr) {
            field = get_field(opt.first);
            if (!field)
                continue;
        }
        bool is_nonsys_value = false;
        bool is_modified_value = true;
        const ScalableBitmap* sys_icon  = &m_bmp_value_lock;
        const ScalableBitmap* icon      = &m_bmp_value_revert;
        const wxColour* color = m_is_default_preset ? &m_default_text_clr : &m_sys_label_clr;
        const wxString* sys_tt  = &m_tt_value_lock;
        const wxString* tt      = &m_tt_value_revert;
        // value isn't equal to system value
        if ((opt.second & osSystemValue) == 0) {
            is_nonsys_value = true;
            sys_icon = m_bmp_non_system;
            sys_tt = m_tt_non_system;
            // value is equal to last saved
            if ((opt.second & osInitValue) != 0)
                color = &m_default_text_clr;
            // value is modified
            else
                color = &m_modified_label_clr;
        }
        if ((opt.second & osInitValue) != 0)
        {
            is_modified_value = false;
            icon = &m_bmp_white_bullet;
            tt = &m_tt_white_bullet;
        }
        if (colored_label_clr) {
            *colored_label_clr = *color;
            continue;
        }
        field->m_is_nonsys_value = is_nonsys_value;
        field->m_is_modified_value = is_modified_value;
        field->set_undo_bitmap(icon);
        //BBS: GUI refactor
        field->set_undo_to_sys_bitmap(sys_icon);
        field->set_undo_tooltip(tt);
        field->set_undo_to_sys_tooltip(sys_tt);
        field->set_label_colour(color);
    }
    if (m_active_page)
        m_active_page->refresh();
}
References Slic3r::GUI::Field::m_is_modified_value, Slic3r::GUI::Field::m_is_nonsys_value, Slic3r::GUI::Field::set_label_colour(), Slic3r::GUI::Field::set_undo_bitmap(), Slic3r::GUI::Field::set_undo_to_sys_bitmap(), Slic3r::GUI::Field::set_undo_to_sys_tooltip(), and Slic3r::GUI::Field::set_undo_tooltip().
delete_preset()
void Slic3r::GUI::Tab::delete_preset () inherited
{
    auto current_preset = m_presets->get_selected_preset();
    // Don't let the user delete the ' - default - ' configuration.
    //BBS: add project embedded preset logic and refine is_external
    std::string action =  _utf8(L("Delete"));
    //std::string action = current_preset.is_external ? _utf8(L("remove")) : _utf8(L("delete"));
    // TRN  remove/delete
    BOOST_LOG_TRIVIAL(info) << boost::format("delete preset %1%, setting_id %2%, user_id %3%, base_id %4%, sync_info %5%, type %6%")
        %current_preset.name%current_preset.setting_id%current_preset.user_id%current_preset.base_id%current_preset.sync_info
        %Preset::get_type_string(m_type);
    PhysicalPrinterCollection& physical_printers = m_preset_bundle->physical_printers;
    wxString msg;
    if (m_type == Preset::TYPE_PRINTER && !physical_printers.empty())
    {
        // Check preset for delete in physical printers
        // Ask a customer about next action, if there is a printer with just one preset and this preset is equal to delete
        std::vector<std::string> ph_printers        = physical_printers.get_printers_with_preset(current_preset.name);
        std::vector<std::string> ph_printers_only   = physical_printers.get_printers_with_only_preset(current_preset.name);
        //if (!ph_printers.empty()) {
        //    msg += _L_PLURAL("The physical printer below is based on the preset, you are going to delete.",
        //                        "The physical printers below are based on the preset, you are going to delete.", ph_printers.size());
        //    for (const std::string& printer : ph_printers)
        //        msg += "\n    \"" + from_u8(printer) + "\",";
        //    msg.RemoveLast();
        //    msg += "\n" + _L_PLURAL("Note, that the selected preset will be deleted from this printer too.",
        //                            "Note, that the selected preset will be deleted from these printers too.", ph_printers.size()) + "\n\n";
        //}
        //if (!ph_printers_only.empty()) {
        //    msg += _L_PLURAL("The physical printer below is based only on the preset, you are going to delete.",
        //                        "The physical printers below are based only on the preset, you are going to delete.", ph_printers_only.size());
        //    for (const std::string& printer : ph_printers_only)
        //        msg += "\n    \"" + from_u8(printer) + "\",";
        //    msg.RemoveLast();
        //    msg += "\n" + _L_PLURAL("Note, that this printer will be deleted after deleting the selected preset.",
        //                            "Note, that these printers will be deleted after deleting the selected preset.", ph_printers_only.size()) + "\n\n";
        //}
        if (!ph_printers.empty() || !ph_printers_only.empty()) {
            msg += _L_PLURAL("Following preset will be deleted too.", "Following presets will be deleted too.", ph_printers.size() + ph_printers_only.size());
            for (const std::string &printer : ph_printers) msg += "\n    \"" + from_u8(printer) + "\",";
            for (const std::string &printer : ph_printers_only) msg += "\n    \"" + from_u8(printer) + "\",";
            msg.RemoveLast();
            // msg += "\n" + _L_PLURAL("Note, that the selected preset will be deleted from this printer too.",
            //                        "Note, that the selected preset will be deleted from these printers too.", ph_printers.size()) + "\n\n";
        }
    }
    msg += from_u8((boost::format(_u8L("Are you sure to %1% the selected preset?")) % action).str());
    //BBS: add project embedded preset logic and refine is_external
    action =  _utf8(L("Delete"));
    //action = current_preset.is_external ? _utf8(L("Remove")) : _utf8(L("Delete"));
    // TRN  Remove/Delete
    wxString title = from_u8((boost::format(_utf8(L("%1% Preset"))) % action).str());  //action + _(L(" Preset"));
    if (current_preset.is_default ||
        //wxID_YES != wxMessageDialog(parent(), msg, title, wxYES_NO | wxNO_DEFAULT | wxICON_QUESTION).ShowModal())
        wxID_YES != MessageDialog(parent(), msg, title, wxYES_NO | wxNO_DEFAULT | wxICON_QUESTION).ShowModal())
        return;
    // if we just delete preset from the physical printer
    if (m_presets_choice->is_selected_physical_printer()) {
        PhysicalPrinter& printer = physical_printers.get_selected_printer();
        // just delete this preset from the current physical printer
        printer.delete_preset(m_presets->get_edited_preset().name);
        // select first from the possible presets for this printer
        physical_printers.select_printer(printer);
        this->select_preset(physical_printers.get_selected_printer_preset_name());
        return;
    }
    // delete selected preset from printers and printer, if it's needed
    if (m_type == Preset::TYPE_PRINTER && !physical_printers.empty())
        physical_printers.delete_preset_from_printers(current_preset.name);
    // Select will handle of the preset dependencies, of saving & closing the depending profiles, and
    // finally of deleting the preset.
    this->select_preset("", true);
    BOOST_LOG_TRIVIAL(info) << boost::format("delete preset finished");
}
References _L_PLURAL, _u8L, _utf8, Slic3r::PhysicalPrinter::delete_preset(), Slic3r::PhysicalPrinterCollection::delete_preset_from_printers(), Slic3r::PhysicalPrinterCollection::empty(), Slic3r::GUI::from_u8(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PhysicalPrinterCollection::get_printers_with_only_preset(), Slic3r::PhysicalPrinterCollection::get_printers_with_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PhysicalPrinterCollection::get_selected_printer(), Slic3r::PhysicalPrinterCollection::get_selected_printer_preset_name(), Slic3r::Preset::get_type_string(), Slic3r::GUI::PresetComboBox::is_selected_physical_printer(), L, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::GUI::Tab::m_presets, Slic3r::GUI::Tab::m_presets_choice, Slic3r::GUI::Tab::m_type, Slic3r::Preset::name, Slic3r::GUI::Tab::parent(), Slic3r::PresetBundle::physical_printers, Slic3r::GUI::Tab::select_preset(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::GUI::Tab::title(), and Slic3r::Preset::TYPE_PRINTER.
description_line_widget()
wxSizer * Slic3r::GUI::Tab::description_line_widget (wxWindow * parent, ogStaticText ** StaticText, wxString text = wxEmptyString) inherited
{
    *StaticText = new ogStaticText(parent, text);
//  auto font = (new wxSystemSettings)->GetFont(wxSYS_DEFAULT_GUI_FONT);
    (*StaticText)->SetFont(wxGetApp().normal_font());
    auto sizer = new wxBoxSizer(wxHORIZONTAL);
    sizer->Add(*StaticText, 1, wxEXPAND|wxALL, 0);
    return sizer;
}
References Slic3r::GUI::Tab::parent().
get_category_icon_map()
const std::map< wxString, std::string > & Slic3r::GUI::Tab::get_category_icon_map () inline inherited
{ return m_category_icon; }
References Slic3r::GUI::Tab::m_category_icon.
get_combo_box()
TabPresetComboBox * Slic3r::GUI::Tab::get_combo_box () inline inherited
{ return m_presets_choice; }
References Slic3r::GUI::Tab::m_presets_choice.
Referenced by Slic3r::GUI::Sidebar::update_presets().
get_config()
DynamicPrintConfig * Slic3r::GUI::Tab::get_config () inline inherited
{ return m_config; }
References Slic3r::GUI::Tab::m_config.
Referenced by Slic3r::GUI::ObjectList::add_settings_item(), Slic3r::GUI::TabPrintLayer::notify_changed(), and Slic3r::GUI::TabPrintLayer::update_custom_dirty().
get_config_manipulation()
ConfigManipulation Slic3r::GUI::Tab::get_config_manipulation () protected inherited
{
    auto load_config = [this]()
    {
        update_dirty();
        // Initialize UI components with the config values.
        reload_config();
        update();
    };
    auto cb_toggle_field = [this](const t_config_option_key& opt_key, bool toggle, int opt_index) {
        return toggle_option(opt_key, toggle, opt_index);
    };
    auto cb_toggle_line = [this](const t_config_option_key& opt_key, bool toggle) {
        return toggle_line(opt_key, toggle);
    };
    auto cb_value_change = [this](const std::string& opt_key, const boost::any& value) {
        return on_value_change(opt_key, value);
    };
    return ConfigManipulation(load_config, cb_toggle_field, cb_toggle_line, cb_value_change, nullptr, this);
}
References Slic3r::GUI::Tab::load_config(), Slic3r::GUI::Tab::on_value_change(), Slic3r::GUI::Tab::reload_config(), Slic3r::GUI::Tab::toggle_line(), Slic3r::GUI::Tab::toggle_option(), Slic3r::GUI::Tab::update(), and Slic3r::GUI::Tab::update_dirty().
Referenced by Slic3r::GUI::Tab::Tab().
get_custom_ctrl_with_blinking_ptr()
std::pair< OG_CustomCtrl *, bool * > Slic3r::GUI::Tab::get_custom_ctrl_with_blinking_ptr (const t_config_option_key & opt_key, int opt_index = -1) inherited
{
    if (!m_active_page)
        return {nullptr, nullptr};
    std::pair<OG_CustomCtrl*, bool*> ret = {nullptr, nullptr};
    for (auto opt_group : m_active_page->m_optgroups) {
        ret = opt_group->get_custom_ctrl_with_blinking_ptr(opt_key, opt_index);
        if (ret.first && ret.second)
            break;
    }
    return ret;
}
get_field() [1/2]
Field * Slic3r::GUI::Tab::get_field (const t_config_option_key & opt_key, int opt_index = -1) const inherited
{
    return m_active_page ? m_active_page->get_field(opt_key, opt_index) : nullptr;
}
Referenced by Slic3r::GUI::Tab::compatible_widget_create(), and Slic3r::GUI::Tab::compatible_widget_reload().
get_field() [2/2]
Field * Slic3r::GUI::Tab::get_field (const t_config_option_key & opt_key, Page ** selected_page, int opt_index = -1) inherited
{
    Field* field = nullptr;
    for (auto page : m_pages) {
        field = page->get_field(opt_key, opt_index);
        if (field != nullptr) {
            *selected_page = page.get();
            return field;
        }
    }
    return field;
}
get_presets()
PresetCollection * Slic3r::GUI::Tab::get_presets () inline inherited
{ return m_presets; }
References Slic3r::GUI::Tab::m_presets.
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item(), and Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog().
get_sys_and_mod_flags()
void Slic3r::GUI::Tab::get_sys_and_mod_flags (const std::string & opt_key, bool & sys_page, bool & modified_page) inherited
{
    auto opt = m_options_list.find(opt_key);
    if (opt == m_options_list.end())
        return;
    if (sys_page) sys_page = (opt->second & osSystemValue) != 0;
    modified_page |= (opt->second & osInitValue) == 0;
}
init_options_list()
void Slic3r::GUI::Tab::init_options_list () virtual inherited
Reimplemented in Slic3r::GUI::TabPrinter, and Slic3r::GUI::TabSLAMaterial.
{
    if (!m_options_list.empty())
        m_options_list.clear();
    for (const std::string& opt_key : m_config->keys())
        m_options_list.emplace(opt_key, m_opt_status_value);
}
Referenced by Slic3r::GUI::TabPrintModel::build(), and Slic3r::GUI::Tab::load_current_preset().
load_config()
void Slic3r::GUI::Tab::load_config (const DynamicPrintConfig & config) inherited
{
    bool modified = 0;
    for(auto opt_key : m_config->diff(config)) {
        m_config->set_key_value(opt_key, config.option(opt_key)->clone());
        modified = 1;
    }
    if (modified) {
        update_dirty();
        //# Initialize UI components with the config values.
        reload_config();
        update();
    }
}
References Slic3r::ConfigOption::clone(), and Slic3r::ConfigBase::option().
Referenced by Slic3r::GUI::Tab::get_config_manipulation(), and Slic3r::GUI::TabPrinter::toggle_options().
load_current_preset()
void Slic3r::GUI::Tab::load_current_preset () inherited
{
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(": enter");
    const Preset& preset = m_presets->get_edited_preset();
    update_btns_enabling();
    update();
    if (m_type == Slic3r::Preset::TYPE_PRINTER) {
        // For the printer profile, generate the extruder pages.
        if (preset.printer_technology() == ptFFF)
            on_preset_loaded();
        else
            wxGetApp().obj_list()->update_objects_list_filament_column(1);
    }
    // Reload preset pages with the new configuration values.
    reload_config();
    update_ui_items_related_on_parent_preset(m_presets->get_selected_preset_parent());
//  m_undo_to_sys_btn->Enable(!preset.is_default);
#if 0
    // use CallAfter because some field triggers schedule on_change calls using CallAfter,
    // and we don't want them to be called after this update_dirty() as they would mark the
    // preset dirty again
    // (not sure this is true anymore now that update_dirty is idempotent)
    wxTheApp->CallAfter([this]
#endif
    {
        // checking out if this Tab exists till this moment
        if (!wxGetApp().checked_tab(this))
            return;
        update_tab_ui();
        // update show/hide tabs
        if (m_type == Slic3r::Preset::TYPE_PRINTER) {
            const PrinterTechnology printer_technology = m_presets->get_edited_preset().printer_technology();
            if (printer_technology != static_cast<TabPrinter*>(this)->m_printer_technology)
            {
                // The change of the technology requires to remove some of unrelated Tabs
                // During this action, wxNoteBook::RemovePage invoke wxEVT_NOTEBOOK_PAGE_CHANGED
                // and as a result a function select_active_page() is called fron Tab::OnActive()
                // But we don't need it. So, to avoid activation of the page, set m_active_page to NULL
                // till unusable Tabs will be deleted
                Page* tmp_page = m_active_page;
                m_active_page = nullptr;
                for (auto tab : wxGetApp().tabs_list) {
                    if (tab->type() == Preset::TYPE_PRINTER) { // Printer tab is shown every time
                        int cur_selection = wxGetApp().tab_panel()->GetSelection();
                        if (cur_selection != 0)
                            wxGetApp().tab_panel()->SetSelection(wxGetApp().tab_panel()->GetPageCount() - 1);
                        continue;
                    }
                    if (tab->supports_printer_technology(printer_technology))
                    {
#ifdef _MSW_DARK_MODE
                        if (!wxGetApp().tabs_as_menu()) {
                            std::string bmp_name = tab->type() == Slic3r::Preset::TYPE_FILAMENT      ? "spool" :
                                                   tab->type() == Slic3r::Preset::TYPE_SLA_MATERIAL  ? "" : "cog";
                            tab->Hide(); // #ys_WORKAROUND : Hide tab before inserting to avoid unwanted rendering of the tab
                            dynamic_cast<Notebook*>(wxGetApp().tab_panel())->InsertPage(wxGetApp().tab_panel()->FindPage(this), tab, tab->title(), bmp_name);
                        }
                        else
#endif
                            wxGetApp().tab_panel()->InsertPage(wxGetApp().tab_panel()->FindPage(this), tab, tab->title(), "");
                        #ifdef __linux__ // the tabs apparently need to be explicitly shown on Linux (pull request #1563)
                            int page_id = wxGetApp().tab_panel()->FindPage(tab);
                            wxGetApp().tab_panel()->GetPage(page_id)->Show(true);
                        #endif // __linux__
                    }
                    else {
                        int page_id = wxGetApp().tab_panel()->FindPage(tab);
                        wxGetApp().tab_panel()->GetPage(page_id)->Show(false);
                        wxGetApp().tab_panel()->RemovePage(page_id);
                    }
                }
                static_cast<TabPrinter*>(this)->m_printer_technology = printer_technology;
                m_active_page = tmp_page;
#ifdef _MSW_DARK_MODE
                if (!wxGetApp().tabs_as_menu())
                    dynamic_cast<Notebook*>(wxGetApp().tab_panel())->SetPageImage(wxGetApp().tab_panel()->FindPage(this), printer_technology == ptFFF ? "printer" : "sla_printer");
#endif
            }
            on_presets_changed();
            if (printer_technology == ptFFF) {
                static_cast<TabPrinter*>(this)->m_initial_extruders_count = static_cast<const ConfigOptionFloats*>(m_presets->get_selected_preset().config.option("nozzle_diameter"))->values.size(); //static_cast<TabPrinter*>(this)->m_extruders_count;
                const Preset* parent_preset = m_presets->get_selected_preset_parent();
                static_cast<TabPrinter*>(this)->m_sys_extruders_count = parent_preset == nullptr ? 0 :
                    static_cast<const ConfigOptionFloats*>(parent_preset->config.option("nozzle_diameter"))->values.size();
            }
        }
        else {
            on_presets_changed();
            if (m_type == Preset::TYPE_SLA_PRINT || m_type == Preset::TYPE_PRINT)
                update_frequently_changed_parameters();
        }
        m_opt_status_value = (m_presets->get_selected_preset_parent() ? osSystemValue : 0) | osInitValue;
        init_options_list();
        update_visibility();
        update_changed_ui();
    }
#if 0
    );
#endif
    BOOST_LOG_TRIVIAL(info) << __FUNCTION__<<boost::format(": exit");
}
References Slic3r::Preset::config, Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::GUI::Tab::init_options_list(), Notebook::InsertPage(), Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Tab::m_opt_status_value, Slic3r::GUI::Tab::m_presets, Slic3r::GUI::Tab::m_type, Slic3r::GUI::Tab::on_preset_loaded(), Slic3r::GUI::Tab::on_presets_changed(), Slic3r::ConfigBase::option(), Slic3r::GUI::Tab::osInitValue, Slic3r::GUI::Tab::osSystemValue, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::ptFFF, Slic3r::GUI::Tab::reload_config(), Slic3r::ConfigOptionVector< T >::size(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::Preset::TYPE_SLA_PRINT, Slic3r::GUI::Tab::update(), Slic3r::GUI::Tab::update_btns_enabling(), Slic3r::GUI::Tab::update_changed_ui(), Slic3r::GUI::Tab::update_frequently_changed_parameters(), Slic3r::GUI::Tab::update_tab_ui(), Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset(), and Slic3r::GUI::Tab::update_visibility().
Referenced by Slic3r::GUI::Tab::on_presets_changed(), and Slic3r::GUI::Tab::select_preset().
load_initial_data()
void Slic3r::GUI::Tab::load_initial_data () inherited
{
    m_config = &m_presets->get_edited_preset().config;
    bool has_parent = m_presets->get_selected_preset_parent() != nullptr;
    m_bmp_non_system = has_parent ? &m_bmp_value_unlock : &m_bmp_white_bullet;
    m_ttg_non_system = has_parent ? &m_ttg_value_unlock : &m_ttg_white_bullet_ns;
    m_tt_non_system  = has_parent ? &m_tt_value_unlock  : &m_ttg_white_bullet_ns;
}
Referenced by build(), Slic3r::GUI::TabPrinter::build(), and Slic3r::GUI::TabSLAPrint::build().
load_key_value()
void Slic3r::GUI::Tab::load_key_value (const std::string & opt_key, const boost::any & value, bool saved_value = false) protected inherited
{
    if (!saved_value) change_opt_value(*m_config, opt_key, value);
    // Mark the print & filament enabled if they are compatible with the currently selected preset.
    if (opt_key == "compatible_printers" || opt_key == "compatible_prints") {
        // Don't select another profile if this profile happens to become incompatible.
        m_preset_bundle->update_compatible(PresetSelectCompatibleType::Never);
    }
    if (m_presets_choice)
        m_presets_choice->update_dirty();
    on_presets_changed();
    update();
}
References Slic3r::GUI::change_opt_value(), and Slic3r::Never.
Referenced by Slic3r::GUI::Tab::compatible_widget_create(), and Slic3r::GUI::TabPrinter::create_bed_shape_widget().
may_discard_current_dirty_preset()
bool Slic3r::GUI::Tab::may_discard_current_dirty_preset (PresetCollection * presets = nullptr, const std::string & new_printer_name = "", bool no_transfer = false) inherited
{
    if (presets == nullptr) presets = m_presets;
    UnsavedChangesDialog dlg(m_type, presets, new_printer_name, no_transfer);
    if (dlg.ShowModal() == wxID_CANCEL)
        return false;
    if (dlg.save_preset())  // save selected changes
    {
        const std::vector<std::string>& unselected_options = dlg.get_unselected_options(presets->type());
        const std::string& name = dlg.get_preset_name();
        //BBS: add project embedded preset relate logic
        bool save_to_project = dlg.get_save_to_project_option();
        if (m_type == presets->type()) // save changes for the current preset from this tab
        {
            // revert unselected options to the old values
            presets->get_edited_preset().config.apply_only(presets->get_selected_preset().config, unselected_options);
            //BBS: add project embedded preset relate logic
            save_preset(name, false, save_to_project);
            //save_preset(name);
        }
        else
        {
            //BBS: add project embedded preset relate logic
            m_preset_bundle->save_changes_for_preset(name, presets->type(), unselected_options, save_to_project);
            //m_preset_bundle->save_changes_for_preset(name, presets->type(), unselected_options);
            // If filament preset is saved for multi-material printer preset,
            // there are cases when filament comboboxs are updated for old (non-modified) colors,
            // but in full_config a filament_colors option aren't.
            if (presets->type() == Preset::TYPE_FILAMENT && wxGetApp().extruders_edited_cnt() > 1)
                wxGetApp().plater()->force_filament_colors_update();
        }
    }
    else if (dlg.transfer_changes()) // move selected changes
    {
        std::vector<std::string> selected_options = dlg.get_selected_options();
        if (m_type == presets->type()) // move changes for the current preset from this tab
        {
            if (m_type == Preset::TYPE_PRINTER) {
                auto it = std::find(selected_options.begin(), selected_options.end(), "extruders_count");
                if (it != selected_options.end()) {
                    // erase "extruders_count" option from the list
                    selected_options.erase(it);
                    // cache the extruders count
                    static_cast<TabPrinter*>(this)->cache_extruder_cnt();
                }
            }
            // copy selected options to the cache from edited preset
            cache_config_diff(selected_options);
        }
        else
            wxGetApp().get_tab(presets->type())->cache_config_diff(selected_options);
    }
    return true;
}
References Slic3r::ConfigBase::apply_only(), Slic3r::GUI::Tab::cache_config_diff(), Slic3r::Preset::config, Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::UnsavedChangesDialog::get_preset_name(), Slic3r::GUI::UnsavedChangesDialog::get_save_to_project_option(), Slic3r::GUI::UnsavedChangesDialog::get_selected_options(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::GUI::UnsavedChangesDialog::get_unselected_options(), Slic3r::GUI::Tab::m_preset_bundle, Slic3r::GUI::Tab::m_presets, Slic3r::GUI::Tab::m_type, Slic3r::GUI::Tab::name(), Slic3r::PresetBundle::save_changes_for_preset(), Slic3r::GUI::UnsavedChangesDialog::save_preset(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::UnsavedChangesDialog::ShowModal(), Slic3r::GUI::UnsavedChangesDialog::transfer_changes(), Slic3r::PresetCollection::type(), Slic3r::Preset::TYPE_FILAMENT, and Slic3r::Preset::TYPE_PRINTER.
Referenced by Slic3r::GUI::ParamsDialog::ParamsDialog(), and Slic3r::GUI::Tab::select_preset().
msw_rescale()
void Slic3r::GUI::Tab::msw_rescale () virtual inherited
Reimplemented in Slic3r::GUI::TabPrinter.
{
    m_em_unit = em_unit(m_parent);
    m_top_sizer->SetMinSize(-1, 3 * m_em_unit);
    //BBS: GUI refactor
    //if (m_mode_sizer)
    //    m_mode_sizer->msw_rescale();
    if (m_presets_choice)
        m_presets_choice->msw_rescale();
    m_tabctrl->SetMinSize(wxSize(20 * m_em_unit, -1));
    // rescale buttons and cached bitmaps
    for (const auto btn : m_scaled_buttons)
        btn->msw_rescale();
    for (const auto bmp : m_scaled_bitmaps)
        bmp->msw_rescale();
    if (m_mode_view)
        m_mode_view->Rescale();
    if (m_detach_preset_btn)
        m_detach_preset_btn->msw_rescale();
    // rescale icons for tree_ctrl
    for (ScalableBitmap& bmp : m_scaled_icons_list)
        bmp.msw_rescale();
    // recreate and set new ImageList for tree_ctrl
    m_icons->RemoveAll();
    m_icons = new wxImageList(m_scaled_icons_list.front().bmp().GetWidth(), m_scaled_icons_list.front().bmp().GetHeight(), false);
    for (ScalableBitmap& bmp : m_scaled_icons_list)
        //m_icons->Add(bmp.bmp());
    m_tabctrl->AssignImageList(m_icons);
    // rescale options_groups
    if (m_active_page)
        m_active_page->msw_rescale();
    m_tabctrl->Rescale();
    //BBS: GUI refactor
    //Layout();
    m_parent->Layout();
}
References em_unit().
Referenced by Slic3r::GUI::TabPrinter::msw_rescale().
name()
std::string Slic3r::GUI::Tab::name () const inline inherited
{ return m_presets->name(); }
References Slic3r::GUI::Tab::m_presets, and Slic3r::PresetCollection::name().
Referenced by Slic3r::GUI::Tab::may_discard_current_dirty_preset(), and Slic3r::GUI::Tab::save_preset().
on_preset_loaded()
virtual void Slic3r::GUI::Tab::on_preset_loaded () inline virtual inherited
Reimplemented in Slic3r::GUI::TabPrinter.
{}
Referenced by Slic3r::GUI::Tab::load_current_preset().
on_presets_changed()
void Slic3r::GUI::Tab::on_presets_changed () protected inherited
{
    if (wxGetApp().plater() == nullptr)
        return;
    // Instead of PostEvent (EVT_TAB_PRESETS_CHANGED) just call update_presets
    wxGetApp().plater()->sidebar().update_presets(m_type);
    bool has_lidar = wxGetApp().preset_bundle->printers.get_edited_preset().has_lidar(wxGetApp().preset_bundle);
    auto& printer_cfg = wxGetApp().preset_bundle->printers.get_edited_preset().config;
    if (has_lidar)
        wxGetApp().plater()->get_partplate_list().set_render_option(
            !printer_cfg.option<ConfigOptionBool>("bbl_calib_mark_logo")->value, true);
    else
        wxGetApp().plater()->get_partplate_list().set_render_option(false, true);
    // Printer selected at the Printer tab, update "compatible" marks at the print and filament selectors.
    for (auto t: m_dependent_tabs)
    {
        Tab* tab = wxGetApp().get_tab(t);
        // If the printer tells us that the print or filament/sla_material preset has been switched or invalidated,
        // refresh the print or filament/sla_material tab page.
        // But if there are options, moved from the previously selected preset, update them to edited preset
        tab->apply_config_from_cache();
        tab->load_current_preset();
    }
    // clear m_dependent_tabs after first update from select_preset()
    // to avoid needless preset loading from update() function
    m_dependent_tabs.clear();
    wxGetApp().plater()->update_project_dirty_from_presets();
}
References Slic3r::GUI::Tab::apply_config_from_cache(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::plater(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::Tab::save_preset(), and Slic3r::GUI::Tab::select_preset().
on_roll_back_value()
void Slic3r::GUI::Tab::on_roll_back_value (const bool to_sys = false) inherited
{
    // BBS: restore all pages in preset
    // if (!m_active_page) return;
    int os;
    if (to_sys) {
        if (!m_is_nonsys_values) return;
        os = osSystemValue;
    }
    else {
        // BBS: restore all pages in preset
        if (!m_presets->get_edited_preset().is_dirty) return;
        os = osInitValue;
    }
    m_postpone_update_ui = true;
    // BBS: restore all preset
    for (auto page : m_pages)
    for (auto group : page->m_optgroups) {
        if (group->title == "Capabilities") {
            if ((m_options_list["extruders_count"] & os) == 0)
                to_sys ? group->back_to_sys_value("extruders_count") : group->back_to_initial_value("extruders_count");
        }
        if (group->title == "Size and coordinates") {
            if ((m_options_list["printable_area"] & os) == 0) {
                to_sys ? group->back_to_sys_value("printable_area") : group->back_to_initial_value("printable_area");
                load_key_value("printable_area", true/*some value*/, true);
            }
        }
        //if (group->title == "Profile dependencies") {
        //    // "compatible_printers" option doesn't exists in Printer Settimgs Tab
        //    if (m_type != Preset::TYPE_PRINTER && (m_options_list["compatible_printers"] & os) == 0) {
        //        to_sys ? group->back_to_sys_value("compatible_printers") : group->back_to_initial_value("compatible_printers");
        //        load_key_value("compatible_printers", true/*some value*/, true);
        //        bool is_empty = m_config->option<ConfigOptionStrings>("compatible_printers")->values.empty();
        //        m_compatible_printers.checkbox->SetValue(is_empty);
        //        is_empty ? m_compatible_printers.btn->Disable() : m_compatible_printers.btn->Enable();
        //    }
        //    // "compatible_prints" option exists only in Filament Settimgs and Materials Tabs
        //    if ((m_type == Preset::TYPE_FILAMENT || m_type == Preset::TYPE_SLA_MATERIAL) && (m_options_list["compatible_prints"] & os) == 0) {
        //        to_sys ? group->back_to_sys_value("compatible_prints") : group->back_to_initial_value("compatible_prints");
        //        load_key_value("compatible_prints", true/*some value*/, true);
        //        bool is_empty = m_config->option<ConfigOptionStrings>("compatible_prints")->values.empty();
        //        m_compatible_prints.checkbox->SetValue(is_empty);
        //        is_empty ? m_compatible_prints.btn->Disable() : m_compatible_prints.btn->Enable();
        //    }
        //}
        for (const auto &kvp : group->opt_map()) {
            const std::string& opt_key = kvp.first;
            if ((m_options_list[opt_key] & os) == 0)
                to_sys ? group->back_to_sys_value(opt_key) : group->back_to_initial_value(opt_key);
        }
    }
    // BBS: restore all pages in preset
    m_presets->discard_current_changes();
    m_postpone_update_ui = false;
    // When all values are rolled, then we hane to update whole tab in respect to the reverted values
    update();
    // BBS: restore all pages in preset, update_dirty also update combobox
    update_dirty();
}
Referenced by Slic3r::GUI::Tab::create_preset_tab().
on_value_change()
void Slic3r::GUI::Tab::on_value_change (const std::string & opt_key, const boost::any & value) virtual inherited
!!! ysFIXME ????
Reimplemented in Slic3r::GUI::TabPrintModel.
{
    if (wxGetApp().plater() == nullptr) {
        return;
    }
    const bool is_fff = supports_printer_technology(ptFFF);
    ConfigOptionsGroup* og_freq_chng_params = wxGetApp().sidebar().og_freq_chng_params(is_fff);
    //BBS: GUI refactor
    if (og_freq_chng_params) {
        if (opt_key == "sparse_infill_density" || opt_key == "pad_enable")
        {
            boost::any val = og_freq_chng_params->get_config_value(*m_config, opt_key);
            og_freq_chng_params->set_value(opt_key, val);
        }
        if (opt_key == "pad_around_object") {
            for (PageShp& pg : m_pages) {
                Field* fld = pg->get_field(opt_key);
                if (fld) fld->set_value(value, false);
            }
        }
        if (is_fff ?
            (opt_key == "enable_support" || opt_key == "support_type" || opt_key == "support_on_build_plate_only") :
            (opt_key == "supports_enable" || opt_key == "support_buildplate_only"))
            og_freq_chng_params->set_value("support", support_combo_value_for_config(*m_config, is_fff));
        if (!is_fff && (opt_key == "pad_enable" || opt_key == "pad_around_object"))
            og_freq_chng_params->set_value("pad", pad_combo_value_for_config(*m_config));
        if (opt_key == "brim_width")
        {
            bool val = m_config->opt_float("brim_width") > 0.0 ? true : false;
            og_freq_chng_params->set_value("brim", val);
        }
    }
    if (opt_key == "single_extruder_multi_material" || opt_key == "extruders_count" )
        update_wiping_button_visibility();
    if (opt_key == "enable_prime_tower") {
        auto timelapse_type = m_config->option<ConfigOptionEnum<TimelapseType>>("timelapse_type");
        bool timelapse_enabled = timelapse_type->value == TimelapseType::tlSmooth;
        if (!boost::any_cast<bool>(value) && timelapse_enabled) {
            MessageDialog dlg(wxGetApp().plater(), _L("Prime tower is required for smooth timeplase. There may be flaws on the model without prime tower. Are you sure you want to disable prime tower?"),
                              _L("Warning"), wxICON_WARNING | wxYES | wxNO);
            if (dlg.ShowModal() == wxID_NO) {
                DynamicPrintConfig new_conf = *m_config;
                new_conf.set_key_value("enable_prime_tower", new ConfigOptionBool(true));
                m_config_manipulation.apply(m_config, &new_conf);
            }
            wxGetApp().plater()->update();
        }
        update_wiping_button_visibility();
    }
    // reload scene to update timelapse wipe tower
    if (opt_key == "timelapse_type") {
        bool wipe_tower_enabled = m_config->option<ConfigOptionBool>("enable_prime_tower")->value;
        if (!wipe_tower_enabled && boost::any_cast<int>(value) == (int)TimelapseType::tlSmooth) {
            MessageDialog dlg(wxGetApp().plater(), _L("Prime tower is required for smooth timelapse. There may be flaws on the model without prime tower. Do you want to enable prime tower?"),
                              _L("Warning"), wxICON_WARNING | wxYES | wxNO);
            if (dlg.ShowModal() == wxID_YES) {
                DynamicPrintConfig new_conf = *m_config;
                new_conf.set_key_value("enable_prime_tower", new ConfigOptionBool(true));
                m_config_manipulation.apply(m_config, &new_conf);
                wxGetApp().plater()->update();
            }
        } else {
            wxGetApp().plater()->update();
        }
    }
    // BBS set support style to default when support type changes
    if (opt_key == "support_type") {
        DynamicPrintConfig new_conf = *m_config;
        new_conf.set_key_value("support_style", new ConfigOptionEnum<SupportMaterialStyle>(smsDefault));
        m_config_manipulation.apply(m_config, &new_conf);
    }
    // BBS popup a message to ask the user to set optimum parameters for tree support
    if (opt_key == "support_type" || opt_key == "support_style") {
        if (is_tree_slim(m_config->opt_enum<SupportType>("support_type"), m_config->opt_enum<SupportMaterialStyle>("support_style")) &&
            !(m_config->opt_float("support_top_z_distance") == 0 && m_config->opt_int("support_interface_top_layers") == 0 && m_config->opt_int("tree_support_wall_count") == 2)) {
            wxString msg_text = _L("We have added an experimental style \"Tree Slim\" that features smaller support volume but weaker strength.\n"
                                    "We recommend using it with: 0 interface layers, 0 top distance, 2 walls.");
            msg_text += "\n\n" + _L("Change these settings automatically? \n"
                                    "Yes - Change these settings automatically\n"
                                    "No  - Do not change these settings for me");
            MessageDialog      dialog(wxGetApp().plater(), msg_text, "Suggestion", wxICON_WARNING | wxYES | wxNO);
            DynamicPrintConfig new_conf = *m_config;
            if (dialog.ShowModal() == wxID_YES) {
                new_conf.set_key_value("support_top_z_distance", new ConfigOptionFloat(0));
                new_conf.set_key_value("support_interface_top_layers", new ConfigOptionInt(0));
                new_conf.set_key_value("tree_support_wall_count", new ConfigOptionInt(2));
                m_config_manipulation.apply(m_config, &new_conf);
            }
            wxGetApp().plater()->update();
        } else if ((m_config->opt_enum<SupportType>("support_type")==stTreeAuto && (m_config->opt_enum<SupportMaterialStyle>("support_style")==smsTreeStrong || m_config->opt_enum<SupportMaterialStyle>("support_style") == smsTreeHybrid)) &&
                   !((m_config->opt_float("support_top_z_distance") >=0.1 || is_support_filament(m_config->opt_int("support_interface_filament") - 1))
                       && m_config->opt_int("support_interface_top_layers") >1) ) {
            wxString msg_text = _L("For \"Tree Strong\" and \"Tree Hybrid\" styles, we recommend the following settings: at least 2 interface layers, at least 0.1mm top z distance or using support materials on interface.");
            msg_text += "\n\n" + _L("Change these settings automatically? \n"
                                    "Yes - Change these settings automatically\n"
                                    "No  - Do not change these settings for me");
            MessageDialog      dialog(wxGetApp().plater(), msg_text, "Suggestion", wxICON_WARNING | wxYES | wxNO);
            DynamicPrintConfig new_conf = *m_config;
            if (dialog.ShowModal() == wxID_YES) {
                if (!is_support_filament(m_config->opt_int("support_interface_filament") - 1) && m_config->opt_float("support_top_z_distance") < 0.1)
                    new_conf.set_key_value("support_top_z_distance", new ConfigOptionFloat(0.2));
                new_conf.set_key_value("support_interface_top_layers", new ConfigOptionInt(2));
                m_config_manipulation.apply(m_config, &new_conf);
            }
            wxGetApp().plater()->update();
        }
    }
    // BBS popup a message to ask the user to set optimum parameters for support interface if support materials are used
    if (opt_key == "support_interface_filament") {
        int interface_filament_id = m_config->opt_int("support_interface_filament") - 1; // the displayed id is based from 1, while internal id is based from 0
        if (is_support_filament(interface_filament_id) && !(m_config->opt_float("support_top_z_distance") == 0 && m_config->opt_float("support_interface_spacing") == 0 &&
                                                            m_config->opt_enum<SupportMaterialInterfacePattern>("support_interface_pattern") == SupportMaterialInterfacePattern::smipConcentric)) {
            wxString msg_text = _L("When using support material for the support interface, We recommend the following settings:\n"
                                   "0 top z distance, 0 interface spacing, concentric pattern and disable independent support layer height");
            msg_text += "\n\n" + _L("Change these settings automatically? \n"
                                    "Yes - Change these settings automatically\n"
                                    "No  - Do not change these settings for me");
            MessageDialog      dialog(wxGetApp().plater(), msg_text, "Suggestion", wxICON_WARNING | wxYES | wxNO);
            DynamicPrintConfig new_conf = *m_config;
            if (dialog.ShowModal() == wxID_YES) {
                new_conf.set_key_value("support_top_z_distance", new ConfigOptionFloat(0));
                new_conf.set_key_value("support_interface_spacing", new ConfigOptionFloat(0));
                new_conf.set_key_value("support_interface_pattern", new ConfigOptionEnum<SupportMaterialInterfacePattern>(SupportMaterialInterfacePattern::smipConcentric));
                new_conf.set_key_value("independent_support_layer_height", new ConfigOptionBool(false));
                m_config_manipulation.apply(m_config, &new_conf);
            }
            wxGetApp().plater()->update();
        }
    }
    // BBS
#if 0
    if (opt_key == "extruders_count")
        wxGetApp().plater()->on_extruders_change(boost::any_cast<size_t>(value));
#endif
    if (m_postpone_update_ui) {
        // It means that not all values are rolled to the system/last saved values jet.
        // And call of the update() can causes a redundant check of the config values,
        return;
    }
    update();
    m_active_page->update_visibility(m_mode, true);
    m_page_view->GetParent()->Layout();
}
References _L, Slic3r::GUI::ConfigOptionsGroup::get_config_value(), int, Slic3r::GUI::is_support_filament(), Slic3r::is_tree_slim(), Slic3r::GUI::pad_combo_value_for_config(), Slic3r::GUI::plater(), Slic3r::ptFFF, Slic3r::DynamicConfig::set_key_value(), Slic3r::GUI::Field::set_value(), Slic3r::GUI::OptionsGroup::set_value(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::smipConcentric, Slic3r::smsDefault, Slic3r::smsTreeHybrid, Slic3r::smsTreeStrong, Slic3r::stTreeAuto, Slic3r::GUI::support_combo_value_for_config(), Slic3r::tlSmooth, and Slic3r::ConfigOptionSingle< T >::value.
Referenced by build(), Slic3r::GUI::TabPrinter::extruders_count_changed(), Slic3r::GUI::Tab::get_config_manipulation(), Slic3r::GUI::TabPrintModel::on_value_change(), Slic3r::GUI::TabPrinter::update_pages(), and Slic3r::GUI::validate_custom_gcode_cb().
OnActivate()
void Slic3r::GUI::Tab::OnActivate () virtual inherited
{
    //BBS: GUI refactor
    //noUpdates seems not working
    //wxWindowUpdateLocker noUpdates(this);
/*#ifdef __WXOSX__
//    wxWindowUpdateLocker noUpdates(this);
    auto size = GetSizer()->GetSize();
    m_tmp_panel->GetSizer()->SetMinSize(size.x + m_size_move, size.y);
    Fit();
    m_size_move *= -1;
#endif // __WXOSX__*/
#ifdef __WXMSW__
    // Workaround for tooltips over Tree Controls displayed over excessively long
    // tree control items, stealing the window focus.
    //
    // In case the Tab was reparented from the MainFrame to the floating dialog,
    // the tooltip created by the Tree Control before reparenting is not reparented,
    // but it still points to the MainFrame. If the tooltip pops up, the MainFrame
    // is incorrectly focussed, stealing focus from the floating dialog.
    //
    // The workaround is to delete the tooltip control.
    // Vojtech tried to reparent the tooltip control, but it did not work,
    // and if the Tab was later reparented back to MainFrame, the tooltip was displayed
    // at an incorrect position, therefore it is safer to just discard the tooltip control
    // altogether.
    HWND hwnd_tt = TreeView_GetToolTips(m_tabctrl->GetHandle());
    if (hwnd_tt) {
      HWND hwnd_toplevel  = find_toplevel_parent(m_tabctrl)->GetHandle();
      HWND hwnd_parent  = ::GetParent(hwnd_tt);
      if (hwnd_parent != hwnd_toplevel) {
        ::DestroyWindow(hwnd_tt);
      TreeView_SetToolTips(m_tabctrl->GetHandle(), nullptr);
      }
    }
#endif
    // BBS: select on first active
    if (!m_active_page)
        restore_last_select_item();
    //BBS: GUI refactor
    m_page_view->Freeze();
    // create controls on active page
    activate_selected_page([](){});
    //BBS: GUI refactor
    //m_main_sizer->Layout();
    m_parent->Layout();
#ifdef _MSW_DARK_MODE
    // Because of DarkMode we use our own Notebook (inherited from wxSiplebook) instead of wxNotebook
    // And it looks like first Layout of the page doesn't update a size of the m_presets_choice
    // So we have to set correct size explicitely
   /* if (wxSize ok_sz = wxSize(35 * m_em_unit, m_presets_choice->GetBestSize().y);
        ok_sz != m_presets_choice->GetSize()) {
        m_presets_choice->SetMinSize(ok_sz);
        m_presets_choice->SetSize(ok_sz);
        GetSizer()->GetItem(size_t(0))->GetSizer()->Layout();
        if (wxGetApp().tabs_as_menu())
            m_presets_choice->update();
    }*/
#endif // _MSW_DARK_MODE
    Refresh();
    //BBS: GUI refactor
    m_page_view->Thaw();
}
References Slic3r::GUI::find_toplevel_parent().
Referenced by Slic3r::GUI::ParamsPanel::OnActivate(), Slic3r::GUI::MainFrame::select_tab(), and Slic3r::GUI::Tab::tree_sel_change_delayed().
OnKeyDown()
void Slic3r::GUI::Tab::OnKeyDown (wxKeyEvent & event) inherited
{
    if (event.GetKeyCode() == WXK_TAB)
        m_tabctrl->Navigate(event.ShiftDown() ? wxNavigationKeyEvent::IsBackward : wxNavigationKeyEvent::IsForward);
    else
        event.Skip();
}
References Slic3r::GUI::Tab::m_tabctrl.
OnTreeSelChange()
void Slic3r::GUI::Tab::OnTreeSelChange (wxCommandEvent & event) inherited
parent()
wxWindow * Slic3r::GUI::Tab::parent () const inline inherited
{ return m_parent; }
References Slic3r::GUI::Tab::m_parent.
Referenced by Slic3r::GUI::Tab::Tab(), add_filament_overrides_page(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::Tab::delete_preset(), Slic3r::GUI::Tab::description_line_widget(), and Slic3r::GUI::TabPrinter::toggle_options().
reactive_preset_combo_box()
void Slic3r::GUI::Tab::reactive_preset_combo_box () inherited
{
    if (!m_presets_choice) return;
    //BBS: add workaround to fix the issue caused by wxwidget 3.15 upgrading
    m_presets_choice->Enable(false);
    m_presets_choice->Enable(true);
}
References Slic3r::GUI::Tab::m_presets_choice.
rebuild_page_tree()
void Slic3r::GUI::Tab::rebuild_page_tree () inherited
{
    // get label of the currently selected item
    auto sel_item = m_tabctrl->GetSelection();
    // BBS: fix new layout, record last select
    if (sel_item < 0)
        sel_item = m_last_select_item;
    const auto selected = sel_item >= 0 ? m_tabctrl->GetItemText(sel_item) : "";
    int item = -1;
    // Delete/Append events invoke wxEVT_TAB_SEL_CHANGED event.
    // To avoid redundant clear/activate functions call
    // suppress activate page before page_tree rebuilding
    m_disable_tree_sel_changed_event = true;
    m_tabctrl->DeleteAllItems();
    for (auto p : m_pages)
    {
        if (!p->get_show())
            continue;
        auto itemId = m_tabctrl->AppendItem(translate_category(p->title(), m_type), p->iconID());
        m_tabctrl->SetItemTextColour(itemId, p->get_item_colour() == m_modified_label_clr ? p->get_item_colour() : StateColor(
                        std::make_pair(0x6B6B6C, (int) StateColor::NotChecked),
                        std::make_pair(p->get_item_colour(), (int) StateColor::Normal)));
        if (translate_category(p->title(), m_type) == selected)
            item = itemId;
    }
    // BBS: on mac, root is selected, this fix it
    m_tabctrl->Unselect();
    // BBS: not select on hide tab
    if (item == -1 && m_parent->is_active_and_shown_tab(this)) {
        // this is triggered on first load, so we don't disable the sel change event
        item = m_tabctrl->GetFirstVisibleItem();
    }
    // BBS: fix new layout, record last select
    if (sel_item == m_last_select_item)
        m_last_select_item = item;
    else
        m_last_select_item = NULL;
    // allow activate page before selection of a page_tree item
    m_disable_tree_sel_changed_event = false;
    //BBS: GUI refactor
    if (item >= 0)
    {
        bool ret = update_current_page_in_background(item);
        //if m_active_page is changed in update_current_page_in_background
        //will just update the selected item of the treectrl
         if (m_parent->is_active_and_shown_tab(this)) // FIX: modify state not update
            m_tabctrl->SelectItem(item);
    }
}
References TabCtrl::AppendItem(), TabCtrl::DeleteAllItems(), TabCtrl::GetFirstVisibleItem(), TabCtrl::GetItemText(), TabCtrl::GetSelection(), Slic3r::GUI::ParamsPanel::is_active_and_shown_tab(), Slic3r::GUI::Tab::m_disable_tree_sel_changed_event, Slic3r::GUI::Tab::m_last_select_item, Slic3r::GUI::Tab::m_modified_label_clr, Slic3r::GUI::Tab::m_pages, Slic3r::GUI::Tab::m_parent, Slic3r::GUI::Tab::m_tabctrl, Slic3r::GUI::Tab::m_type, StateColor::Normal, StateColor::NotChecked, NULL, TabCtrl::SelectItem(), TabCtrl::SetItemTextColour(), Slic3r::GUI::Tab::translate_category(), TabCtrl::Unselect(), and Slic3r::GUI::Tab::update_current_page_in_background().
Referenced by Slic3r::GUI::TabPrinter::build_unregular_pages(), and Slic3r::GUI::TabPrinter::update_pages().
reload_config()
void Slic3r::GUI::TabFilament::reload_config () override virtual
Reimplemented from Slic3r::GUI::Tab.
{
    this->compatible_widget_reload(m_compatible_printers);
    this->compatible_widget_reload(m_compatible_prints);
    Tab::reload_config();
}
References Slic3r::GUI::Tab::compatible_widget_reload(), Slic3r::GUI::Tab::m_compatible_printers, Slic3r::GUI::Tab::m_compatible_prints, and Slic3r::GUI::Tab::reload_config().
restore_last_select_item()
void Slic3r::GUI::Tab::restore_last_select_item () inherited
{
    auto item = m_last_select_item;
    if (item == -1)
        item = m_tabctrl->GetFirstVisibleItem();
    m_tabctrl->SelectItem(item);
}
References TabCtrl::GetFirstVisibleItem(), Slic3r::GUI::Tab::m_last_select_item, Slic3r::GUI::Tab::m_tabctrl, and TabCtrl::SelectItem().
Referenced by Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::ParamsPanel::set_active_tab(), and Slic3r::GUI::PlaterPresetComboBox::switch_to_tab().
save_preset()
void Slic3r::GUI::Tab::save_preset (std::string name = std::string(), bool detach = false, bool save_to_project = false, bool from_input = false, std::string input_name = "") inherited
m_tabctrl->OnSetFocus();
{
    // since buttons(and choices too) don't get focus on Mac, we set focus manually
    // to the treectrl so that the EVT_* events are fired for the input field having
    // focus currently.is there anything better than this ?
    if (from_input) {
        SavePresetDialog dlg(m_parent, m_type, detach ? _u8L("Detached") : "");
        dlg.Show(false);
        dlg.input_name_from_other(input_name);
        wxCommandEvent evt(wxEVT_TEXT, GetId());
        dlg.GetEventHandler()->ProcessEvent(evt);
        dlg.confirm_from_other();
        name = input_name;
    }
    if (name.empty()) {
        SavePresetDialog dlg(m_parent, m_type, detach ? _u8L("Detached") : "");
        if (dlg.ShowModal() != wxID_OK)
            return;
        name = dlg.get_name();
        //BBS: add project embedded preset relate logic
        save_to_project = dlg.get_save_to_project_selection(m_type);
    }
    //BBS record current preset name
    std::string curr_preset_name = m_presets->get_edited_preset().name;
    bool exist_preset = false;
    Preset* new_preset = m_presets->find_preset(name, false);
    if (new_preset) {
        exist_preset = true;
    }
    // Save the preset into Slic3r::data_dir / presets / section_name / preset_name.ini
    m_presets->save_current_preset(name, detach, save_to_project);
    //BBS create new settings
    new_preset = m_presets->find_preset(name, false, true);
    //Preset* preset = &m_presets.preset(it - m_presets.begin(), true);
    if (!new_preset) {
        BOOST_LOG_TRIVIAL(info) << "create new preset failed";
        return;
    }
    // set sync_info for sync service
    if (exist_preset) {
        new_preset->sync_info = "update";
        BOOST_LOG_TRIVIAL(info) << "sync_preset: update preset = " << new_preset->name;
    }
    else {
        new_preset->sync_info = "create";
        if (wxGetApp().is_user_login())
            new_preset->user_id = wxGetApp().getAgent()->get_user_id();
        BOOST_LOG_TRIVIAL(info) << "sync_preset: create preset = " << new_preset->name;
    }
    new_preset->save_info();
    // Mark the print & filament enabled if they are compatible with the currently selected preset.
    // If saving the preset changes compatibility with other presets, keep the now incompatible dependent presets selected, however with a "red flag" icon showing that they are no more compatible.
    m_preset_bundle->update_compatible(PresetSelectCompatibleType::Never);
    // Add the new item into the UI component, remove dirty flags and activate the saved item.
    update_tab_ui();
    // Update the selection boxes at the plater.
    on_presets_changed();
    //BBS if create a new prset name, preset changed from preset name to new preset name
    if (!exist_preset) {
        wxGetApp().plater()->sidebar().update_presets_from_to(m_type, curr_preset_name, new_preset->name);
    }
    // If current profile is saved, "delete preset" button have to be enabled
    m_btn_delete_preset->Show();
    m_btn_delete_preset->GetParent()->Layout();
    if (m_type == Preset::TYPE_PRINTER)
        static_cast<TabPrinter*>(this)->m_initial_extruders_count = static_cast<TabPrinter*>(this)->m_extruders_count;
    // Parent preset is "default" after detaching, so we should to update UI values, related on parent preset
    if (detach)
        update_ui_items_related_on_parent_preset(m_presets->get_selected_preset_parent());
    update_changed_ui();
    /* If filament preset is saved for multi-material printer preset,
     * there are cases when filament comboboxs are updated for old (non-modified) colors,
     * but in full_config a filament_colors option aren't.*/
    if (m_type == Preset::TYPE_FILAMENT && wxGetApp().extruders_edited_cnt() > 1)
        wxGetApp().plater()->force_filament_colors_update();
    {
        // Profile compatiblity is updated first when the profile is saved.
        // Update profile selection combo boxes at the depending tabs to reflect modifications in profile compatibility.
        std::vector<Preset::Type> dependent;
        switch (m_type) {
        case Preset::TYPE_PRINT:
            dependent = { Preset::TYPE_FILAMENT };
            break;
        case Preset::TYPE_SLA_PRINT:
            dependent = { Preset::TYPE_SLA_MATERIAL };
            break;
        case Preset::TYPE_PRINTER:
            if (static_cast<const TabPrinter*>(this)->m_printer_technology == ptFFF)
                dependent = { Preset::TYPE_PRINT, Preset::TYPE_FILAMENT };
            else
                dependent = { Preset::TYPE_SLA_PRINT, Preset::TYPE_SLA_MATERIAL };
            break;
        default:
            break;
        }
        for (Preset::Type preset_type : dependent)
            wxGetApp().get_tab(preset_type)->update_tab_ui();
    }
    // update preset comboboxes in DiffPresetDlg
    wxGetApp().mainframe->diff_dialog.update_presets(m_type);
}
References _u8L, Slic3r::GUI::SavePresetDialog::confirm_from_other(), Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::SavePresetDialog::get_name(), Slic3r::GUI::SavePresetDialog::get_save_to_project_selection(), Slic3r::PresetCollection::get_selected_preset_parent(), Slic3r::GUI::SavePresetDialog::input_name_from_other(), Slic3r::GUI::Tab::m_btn_delete_preset, Slic3r::GUI::TabPrinter::m_extruders_count, Slic3r::GUI::Tab::m_parent, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::GUI::Tab::m_presets, Slic3r::GUI::Tab::m_type, Slic3r::Preset::name, Slic3r::GUI::Tab::name(), Slic3r::Never, Slic3r::GUI::Tab::on_presets_changed(), Slic3r::ptFFF, Slic3r::PresetCollection::save_current_preset(), Slic3r::Preset::save_info(), Slic3r::GUI::DPIAware< P >::ShowModal(), Slic3r::Preset::sync_info, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::Preset::TYPE_SLA_PRINT, Slic3r::GUI::Tab::update_changed_ui(), Slic3r::PresetBundle::update_compatible(), Slic3r::GUI::Tab::update_tab_ui(), Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset(), and Slic3r::Preset::user_id.
Referenced by Slic3r::GUI::Tab::may_discard_current_dirty_preset().
saved_preset_is_dirty()
bool Slic3r::GUI::Tab::saved_preset_is_dirty () const inherited
{ return m_presets->saved_is_dirty(); }
References Slic3r::GUI::Tab::m_presets, and Slic3r::PresetCollection::saved_is_dirty().
select_preset()
bool Slic3r::GUI::Tab::select_preset (std::string preset_name = "", bool delete_current = false, const std::string & last_selected_ph_printer_name = "", bool force_select = false) inherited
{
    BOOST_LOG_TRIVIAL(info) << boost::format("select preset, name %1%, delete_current %2%")
        %preset_name %delete_current;
    if (preset_name.empty()) {
        if (delete_current) {
            // Find an alternate preset to be selected after the current preset is deleted.
            const std::deque<Preset> &presets     = m_presets->get_presets();
            size_t              idx_current   = m_presets->get_idx_selected();
            // Find the next visible preset.
            size_t              idx_new       = idx_current + 1;
            if (idx_new < presets.size())
                for (; idx_new < presets.size() && ! presets[idx_new].is_visible; ++ idx_new) ;
            if (idx_new == presets.size())
                for (idx_new = idx_current - 1; idx_new > 0 && ! presets[idx_new].is_visible; -- idx_new);
            preset_name = presets[idx_new].name;
            BOOST_LOG_TRIVIAL(info) << boost::format("cause by delete current ,choose the next visible, idx %1%, name %2%")
                                        %idx_new %preset_name;
        } else {
            //BBS select first visible item first
            const std::deque<Preset> &presets     = this->m_presets->get_presets();
            size_t              idx_new = 0;
            if (idx_new < presets.size())
                for (; idx_new < presets.size() && ! presets[idx_new].is_visible; ++ idx_new) ;
            preset_name = presets[idx_new].name;
            if (idx_new == presets.size()) {
                // If no name is provided, select the "-- default --" preset.
                preset_name = m_presets->default_preset().name;
            }
            BOOST_LOG_TRIVIAL(info) << boost::format("not cause by delete current ,choose the first visible, idx %1%, name %2%")
                                        %idx_new %preset_name;
        }
    }
    //BBS: add project embedded preset logic and refine is_external
    assert(! delete_current || (m_presets->get_edited_preset().name != preset_name && (m_presets->get_edited_preset().is_user() || m_presets->get_edited_preset().is_project_embedded)));
    //assert(! delete_current || (m_presets->get_edited_preset().name != preset_name && m_presets->get_edited_preset().is_user()));
    bool current_dirty = ! delete_current && m_presets->current_is_dirty();
    bool print_tab     = m_presets->type() == Preset::TYPE_PRINT || m_presets->type() == Preset::TYPE_SLA_PRINT;
    bool printer_tab   = m_presets->type() == Preset::TYPE_PRINTER;
    bool canceled      = false;
    bool no_transfer = false;
    bool technology_changed = false;
    m_dependent_tabs.clear();
    if ((m_presets->type() == Preset::TYPE_FILAMENT) && !preset_name.empty())
    {
        Preset *to_be_selected = m_presets->find_preset(preset_name, false, true);
        if (to_be_selected) {
            std::string current_type, to_select_type;
            ConfigOptionStrings* cur_opt = dynamic_cast <ConfigOptionStrings *>(m_presets->get_edited_preset().config.option("filament_type"));
            ConfigOptionStrings* to_select_opt = dynamic_cast <ConfigOptionStrings *>(to_be_selected->config.option("filament_type"));
            if (cur_opt && (cur_opt->values.size() > 0)) {
                current_type =  cur_opt->values[0];
            }
            if (to_select_opt && (to_select_opt->values.size() > 0)) {
                to_select_type =  to_select_opt->values[0];
            }
            if (current_type != to_select_type)
                no_transfer = true;
        }
    }
    else if (printer_tab)
        no_transfer = true;
    if (current_dirty && ! may_discard_current_dirty_preset(nullptr, preset_name, no_transfer) && !force_select) {
        canceled = true;
        BOOST_LOG_TRIVIAL(info) << boost::format("current dirty and cancelled");
    } else if (print_tab) {
        // Before switching the print profile to a new one, verify, whether the currently active filament or SLA material
        // are compatible with the new print.
        // If it is not compatible and the current filament or SLA material are dirty, let user decide
        // whether to discard the changes or keep the current print selection.
        PresetWithVendorProfile printer_profile = m_preset_bundle->printers.get_edited_preset_with_vendor_profile();
        PrinterTechnology  printer_technology = printer_profile.preset.printer_technology();
        PresetCollection  &dependent = (printer_technology == ptFFF) ? m_preset_bundle->filaments : m_preset_bundle->sla_materials;
        bool         old_preset_dirty = dependent.current_is_dirty();
        bool         new_preset_compatible = is_compatible_with_print(dependent.get_edited_preset_with_vendor_profile(),
          m_presets->get_preset_with_vendor_profile(*m_presets->find_preset(preset_name, true)), printer_profile);
        if (! canceled)
            canceled = old_preset_dirty && ! new_preset_compatible && ! may_discard_current_dirty_preset(&dependent, preset_name) && !force_select;
        if (! canceled) {
            // The preset will be switched to a different, compatible preset, or the '-- default --'.
            m_dependent_tabs.emplace_back((printer_technology == ptFFF) ? Preset::Type::TYPE_FILAMENT : Preset::Type::TYPE_SLA_MATERIAL);
            if (old_preset_dirty && ! new_preset_compatible)
                dependent.discard_current_changes();
        }
        BOOST_LOG_TRIVIAL(info) << boost::format("select process, new_preset_compatible %1%, old_preset_dirty %2%, cancelled %3%")
            %new_preset_compatible %old_preset_dirty % canceled;
    } else if (printer_tab) {
        // Before switching the printer to a new one, verify, whether the currently active print and filament
        // are compatible with the new printer.
        // If they are not compatible and the current print or filament are dirty, let user decide
        // whether to discard the changes or keep the current printer selection.
        //
        // With the introduction of the SLA printer types, we need to support switching between
        // the FFF and SLA printers.
        const Preset    &new_printer_preset     = *m_presets->find_preset(preset_name, true);
    const PresetWithVendorProfile new_printer_preset_with_vendor_profile = m_presets->get_preset_with_vendor_profile(new_printer_preset);
        PrinterTechnology    old_printer_technology = m_presets->get_edited_preset().printer_technology();
        PrinterTechnology    new_printer_technology = new_printer_preset.printer_technology();
        if (new_printer_technology == ptSLA && old_printer_technology == ptFFF && !wxGetApp().may_switch_to_SLA_preset(_omitL("New printer preset selected")))
            canceled = true;
        else {
            struct PresetUpdate {
                Preset::Type         tab_type;
                PresetCollection  *presets;
                PrinterTechnology    technology;
                bool               old_preset_dirty;
                bool               new_preset_compatible;
            };
            std::vector<PresetUpdate> updates = {
                { Preset::Type::TYPE_PRINT,         &m_preset_bundle->prints,       ptFFF },
                //{ Preset::Type::TYPE_SLA_PRINT,     &m_preset_bundle->sla_prints,   ptSLA },
                { Preset::Type::TYPE_FILAMENT,      &m_preset_bundle->filaments,    ptFFF },
                //{ Preset::Type::TYPE_SLA_MATERIAL,  &m_preset_bundle->sla_materials,ptSLA }
            };
            for (PresetUpdate &pu : updates) {
                pu.old_preset_dirty = (old_printer_technology == pu.technology) && pu.presets->current_is_dirty();
                pu.new_preset_compatible = (new_printer_technology == pu.technology) && is_compatible_with_printer(pu.presets->get_edited_preset_with_vendor_profile(), new_printer_preset_with_vendor_profile);
                if (!canceled)
                    canceled = pu.old_preset_dirty && !pu.new_preset_compatible && !may_discard_current_dirty_preset(pu.presets, preset_name) && !force_select;
            }
            if (!canceled) {
                for (PresetUpdate &pu : updates) {
                    // The preset will be switched to a different, compatible preset, or the '-- default --'.
                    if (pu.technology == new_printer_technology)
                        m_dependent_tabs.emplace_back(pu.tab_type);
                    if (pu.old_preset_dirty && !pu.new_preset_compatible)
                        pu.presets->discard_current_changes();
                }
            }
        }
        if (! canceled)
          technology_changed = old_printer_technology != new_printer_technology;
        BOOST_LOG_TRIVIAL(info) << boost::format("select machine, technology_changed %1%, canceled %2%")
                %technology_changed  % canceled;
    }
    BOOST_LOG_TRIVIAL(info) << boost::format("before delete action, canceled %1%, delete_current %2%") %canceled %delete_current;
    if (! canceled && delete_current) {
        // Delete the file and select some other reasonable preset.
        // It does not matter which preset will be made active as the preset will be re-selected from the preset_name variable.
        // The 'external' presets will only be removed from the preset list, their files will not be deleted.
        try {
            //BBS delete preset
            Preset &current_preset = m_presets->get_selected_preset();
            if (!current_preset.setting_id.empty()) {
                BOOST_LOG_TRIVIAL(info) << "delete preset = " << current_preset.name << ", setting_id = " << current_preset.setting_id;
                m_presets->set_sync_info_and_save(current_preset.name, current_preset.setting_id, "delete");
                wxGetApp().delete_preset_from_cloud(current_preset.setting_id);
            }
            BOOST_LOG_TRIVIAL(info) << boost::format("will delete current preset...");
            m_presets->delete_current_preset();
        } catch (const std::exception & ex) {
            //FIXME add some error reporting!
            canceled = true;
            BOOST_LOG_TRIVIAL(info) << boost::format("found exception when delete: %1%") %ex.what();
        }
    }
    if (canceled) {
        BOOST_LOG_TRIVIAL(info) << boost::format("canceled delete, update ui...");
        if (m_type == Preset::TYPE_PRINTER) {
            if (!last_selected_ph_printer_name.empty() &&
                m_presets->get_edited_preset().name == PhysicalPrinter::get_preset_name(last_selected_ph_printer_name)) {
                // If preset selection was canceled and previously was selected physical printer, we should select it back
                m_preset_bundle->physical_printers.select_printer(last_selected_ph_printer_name);
            }
            if (m_preset_bundle->physical_printers.has_selection()) {
                // If preset selection was canceled and physical printer was selected
                // we must disable selection marker for the physical printers
                m_preset_bundle->physical_printers.unselect_printer();
            }
        }
        update_tab_ui();
        // Trigger the on_presets_changed event so that we also restore the previous value in the plater selector,
        // if this action was initiated from the plater.
        on_presets_changed();
    } else {
        BOOST_LOG_TRIVIAL(info) << boost::format("successfully delete, will update compatibility");
        if (current_dirty)
            m_presets->discard_current_changes();
        const bool is_selected = m_presets->select_preset_by_name(preset_name, false) || delete_current;
        assert(m_presets->get_edited_preset().name == preset_name || ! is_selected);
        // Mark the print & filament enabled if they are compatible with the currently selected preset.
        // The following method should not discard changes of current print or filament presets on change of a printer profile,
        // if they are compatible with the current printer.
        auto update_compatible_type = [delete_current](bool technology_changed, bool on_page, bool show_incompatible_presets) {
          return (delete_current || technology_changed) ? PresetSelectCompatibleType::Always :
                 on_page                                ? PresetSelectCompatibleType::Never  :
                 show_incompatible_presets              ? PresetSelectCompatibleType::OnlyIfWasCompatible : PresetSelectCompatibleType::Always;
        };
        if (current_dirty || delete_current || print_tab || printer_tab)
            m_preset_bundle->update_compatible(
              update_compatible_type(technology_changed, print_tab,   (print_tab ? this : wxGetApp().get_tab(Preset::TYPE_PRINT))->m_show_incompatible_presets),
              update_compatible_type(technology_changed, false,     wxGetApp().get_tab(Preset::TYPE_FILAMENT)->m_show_incompatible_presets));
        // Initialize the UI from the current preset.
        if (printer_tab)
            static_cast<TabPrinter*>(this)->update_pages();
        if (! is_selected && printer_tab)
        {
            /* There is a case, when :
             * after Config Wizard applying we try to select previously selected preset, but
             * in a current configuration this one:
             *  1. doesn't exist now,
             *  2. have another printer_technology
             * So, it is necessary to update list of dependent tabs
             * to the corresponding printer_technology
             */
            const PrinterTechnology printer_technology = m_presets->get_edited_preset().printer_technology();
            if (printer_technology == ptFFF && m_dependent_tabs.front() != Preset::Type::TYPE_PRINT)
                m_dependent_tabs = { Preset::Type::TYPE_PRINT, Preset::Type::TYPE_FILAMENT };
            else if (printer_technology == ptSLA && m_dependent_tabs.front() != Preset::Type::TYPE_SLA_PRINT)
                m_dependent_tabs = { Preset::Type::TYPE_SLA_PRINT, Preset::Type::TYPE_SLA_MATERIAL };
        }
        // check if there is something in the cache to move to the new selected preset
        apply_config_from_cache();
        // Orca: update presets for the selected printer
        if (m_type == Preset::TYPE_PRINTER) {
          m_preset_bundle->update_selections(*wxGetApp().app_config);
          wxGetApp().plater()->sidebar().on_filaments_change(m_preset_bundle->filament_presets.size());
        }
        load_current_preset();
    }
    if (technology_changed)
        wxGetApp().mainframe->technology_changed();
    BOOST_LOG_TRIVIAL(info) << boost::format("select preset, exit");
    return !canceled;
}
References _omitL, Slic3r::Always, Slic3r::GUI::Tab::apply_config_from_cache(), Slic3r::Preset::config, Slic3r::PresetCollection::current_is_dirty(), Slic3r::PresetCollection::default_preset(), Slic3r::PresetCollection::delete_current_preset(), Slic3r::PresetCollection::discard_current_changes(), Slic3r::PresetBundle::filament_presets, Slic3r::PresetBundle::filaments, Slic3r::PresetCollection::find_preset(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::PresetCollection::get_edited_preset_with_vendor_profile(), Slic3r::PresetCollection::get_idx_selected(), Slic3r::PhysicalPrinter::get_preset_name(), Slic3r::PresetCollection::get_preset_with_vendor_profile(), Slic3r::PresetCollection::get_presets(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::is_compatible_with_print(), Slic3r::is_compatible_with_printer(), Slic3r::Preset::is_project_embedded, Slic3r::Preset::is_user(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::Tab::m_dependent_tabs, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::GUI::Tab::m_presets, Slic3r::GUI::Tab::m_show_incompatible_presets, Slic3r::GUI::Tab::m_type, Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::Preset::name, Slic3r::Never, Slic3r::GUI::Tab::on_presets_changed(), Slic3r::OnlyIfWasCompatible, Slic3r::ConfigBase::option(), Slic3r::PresetBundle::physical_printers, Slic3r::PresetWithVendorProfile::preset, Slic3r::GUI::printer_technology(), Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::PresetBundle::prints, Slic3r::ptFFF, Slic3r::ptSLA, Slic3r::PresetCollection::select_preset_by_name(), Slic3r::PhysicalPrinterCollection::select_printer(), Slic3r::PresetCollection::set_sync_info_and_save(), Slic3r::Preset::setting_id, Slic3r::PresetBundle::sla_materials, Slic3r::PresetCollection::type(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, Slic3r::Preset::TYPE_SLA_PRINT, Slic3r::PhysicalPrinterCollection::unselect_printer(), Slic3r::PresetBundle::update_compatible(), Slic3r::PresetBundle::update_selections(), Slic3r::GUI::Tab::update_tab_ui(), and Slic3r::ConfigOptionVector< T >::values.
Referenced by Slic3r::GUI::Tab::delete_preset(), and Slic3r::GUI::PresetComboBox::selection_is_changed_according_to_physical_printers().
set_expanded()
void Slic3r::GUI::Tab::set_expanded (bool value) inherited
{
    if (value) {
        if (m_presets_choice)
            m_main_sizer->Show(m_presets_choice);
        m_main_sizer->Show(m_tabctrl);
    }
    else {
        m_active_page = NULL;
        if (m_presets_choice)
            m_main_sizer->Hide(m_presets_choice);
        m_main_sizer->Hide(m_tabctrl);
    }
}
References Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Tab::m_main_sizer, Slic3r::GUI::Tab::m_presets_choice, Slic3r::GUI::Tab::m_tabctrl, and NULL.
set_tooltips_text()
void Slic3r::GUI::Tab::set_tooltips_text () protected inherited
{
    // --- Tooltip text for reset buttons (for whole options group)
    // Text to be shown on the "Revert to system" aka "Lock to system" button next to each input field.
    //m_ttg_value_lock =    _(L("LOCKED LOCK icon indicates that the settings are the same as the system (or default) values "
    //                            "for the current option group"));
    //m_ttg_value_unlock =  _(L("UNLOCKED LOCK icon indicates that some settings were changed and are not equal "
    //                            "to the system (or default) values for the current option group.\n"
    //                            "Click to reset all settings for current option group to the system (or default) values."));
    //m_ttg_white_bullet_ns = _(L("WHITE BULLET icon indicates a non system (or non default) preset."));
    //m_ttg_non_system =    &m_ttg_white_bullet_ns;
    // Text to be shown on the "Undo user changes" button next to each input field.
    //m_ttg_white_bullet =  _(L("WHITE BULLET icon indicates that the settings are the same as in the last saved "
    //                            "preset for the current option group."));
    //m_ttg_value_revert =  _(L("BACK ARROW icon indicates that the settings were changed and are not equal to "
    //                            "the last saved preset for the current option group.\n"
    //                            "Click to reset all settings for the current option group to the last saved preset."));
    // --- Tooltip text for reset buttons (for each option in group)
    // Text to be shown on the "Revert to system" aka "Lock to system" button next to each input field.
    //m_tt_value_lock =   _(L("LOCKED LOCK icon indicates that the value is the same as the system (or default) value."));
    m_tt_value_unlock =   _(L("Click to reset current value and attach to the global value."));
    //  m_tt_white_bullet_ns= _(L("WHITE BULLET icon indicates a non system preset."));
    //m_tt_non_system =   &m_ttg_white_bullet_ns;
    // Text to be shown on the "Undo user changes" button next to each input field.
    //m_tt_white_bullet =   _(L("WHITE BULLET icon indicates that the value is the same as in the last saved preset."));
    m_tt_value_revert =   _(L("Click to drop current modify and reset to saved value."));
}
References _, L, Slic3r::GUI::Tab::m_tt_value_revert, and Slic3r::GUI::Tab::m_tt_value_unlock.
Referenced by Slic3r::GUI::Tab::create_preset_tab().
set_type()
void Slic3r::GUI::Tab::set_type () protected inherited
{
    if (m_name == PRESET_PRINT_NAME)              { m_type = Slic3r::Preset::TYPE_PRINT; }
    else if (m_name == "sla_print")     { m_type = Slic3r::Preset::TYPE_SLA_PRINT; }
    else if (m_name == PRESET_FILAMENT_NAME)      { m_type = Slic3r::Preset::TYPE_FILAMENT; }
    else if (m_name == "sla_material")  { m_type = Slic3r::Preset::TYPE_SLA_MATERIAL; }
    else if (m_name == PRESET_PRINTER_NAME)       { m_type = Slic3r::Preset::TYPE_PRINTER; }
    else                                { m_type = Slic3r::Preset::TYPE_INVALID; assert(false); }
}
References Slic3r::GUI::Tab::m_name, Slic3r::GUI::Tab::m_type, PRESET_FILAMENT_NAME, PRESET_PRINT_NAME, PRESET_PRINTER_NAME, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_INVALID, Slic3r::Preset::TYPE_PRINT, Slic3r::Preset::TYPE_PRINTER, Slic3r::Preset::TYPE_SLA_MATERIAL, and Slic3r::Preset::TYPE_SLA_PRINT.
show_timelapse_warning_dialog()
void Slic3r::GUI::Tab::show_timelapse_warning_dialog () inherited
{
    if (!m_is_timelapse_wipe_tower_already_prompted) {
        wxString      msg_text = _(L("When recording timelapse without toolhead, it is recommended to add a \"Timelapse Wipe Tower\" \n"
                                "by right-click the empty position of build plate and choose \"Add Primitive\"->\"Timelapse Wipe Tower\"."));
        msg_text += "\n";
        MessageDialog dialog(nullptr, msg_text, "", wxICON_WARNING | wxOK);
        dialog.ShowModal();
        m_is_timelapse_wipe_tower_already_prompted = true;
    }
}
References _, L, and Slic3r::GUI::DPIAware< P >::ShowModal().
supports_printer_technology()
bool Slic3r::GUI::TabFilament::supports_printer_technology (const PrinterTechnology tech) const inline override virtual
Implements Slic3r::GUI::Tab.
{ return tech == ptFFF; }
References Slic3r::ptFFF.
sys_color_changed()
void Slic3r::GUI::Tab::sys_color_changed () virtual inherited
{
    if (m_presets_choice)
        m_presets_choice->sys_color_changed();
    // update buttons and cached bitmaps
    for (const auto btn : m_scaled_buttons)
        btn->msw_rescale();
    for (const auto bmp : m_scaled_bitmaps)
        bmp->msw_rescale();
    if (m_detach_preset_btn)
        m_detach_preset_btn->msw_rescale();
    // update icons for tree_ctrl
    for (ScalableBitmap& bmp : m_scaled_icons_list)
        bmp.msw_rescale();
    // recreate and set new ImageList for tree_ctrl
    m_icons->RemoveAll();
    m_icons = new wxImageList(m_scaled_icons_list.front().bmp().GetWidth(), m_scaled_icons_list.front().bmp().GetHeight(), false);
    for (ScalableBitmap& bmp : m_scaled_icons_list)
        //m_icons->Add(bmp.bmp());
    m_tabctrl->AssignImageList(m_icons);
    // Colors for ui "decoration"
    update_label_colours();
#ifdef _WIN32
    wxWindowUpdateLocker noUpdates(this);
    //BBS: GUI refactor
    //if (m_mode_sizer)
    //    m_mode_sizer->msw_rescale();
    wxGetApp().UpdateDarkUI(this);
    wxGetApp().UpdateDarkUI(m_tabctrl);
#endif
    update_changed_tree_ui();
    // update options_groups
    if (m_active_page)
        m_active_page->sys_color_changed();
    //BBS: GUI refactor
    //Layout();
    m_parent->Layout();
}
title()
wxString Slic3r::GUI::Tab::title () const inline inherited
{ return m_title; }
References Slic3r::GUI::Tab::m_title.
Referenced by Slic3r::GUI::SavePresetDialog::Item::Item(), Slic3r::GUI::PhysicalPrinterDialog::PhysicalPrinterDialog(), Slic3r::GUI::TabPrinter::build_unregular_pages(), Slic3r::GUI::Tab::delete_preset(), and Slic3r::GUI::Tab::validate_custom_gcode().
toggle_line()
void Slic3r::GUI::Tab::toggle_line (const std::string & opt_key, bool toggle) inherited
{
    if (!m_active_page) return;
    Line *line = m_active_page->get_line(opt_key);
    if (line) line->toggle_visible = toggle;
};
References Slic3r::GUI::Line::toggle_visible.
Referenced by Slic3r::GUI::Tab::get_config_manipulation(), Slic3r::GUI::ParamsPanel::set_active_tab(), toggle_options(), and Slic3r::GUI::TabPrinter::toggle_options().
toggle_option()
void Slic3r::GUI::Tab::toggle_option (const std::string & opt_key, bool toggle, int opt_index = -1) inherited
{
    if (!m_active_page)
        return;
    Field* field = m_active_page->get_field(opt_key, opt_index);
    if (field)
        field->toggle(toggle);
}
References Slic3r::GUI::Field::toggle().
Referenced by Slic3r::GUI::Tab::get_config_manipulation(), toggle_options(), and Slic3r::GUI::TabPrinter::toggle_options().
toggle_options()
void Slic3r::GUI::TabFilament::toggle_options () override virtual
Implements Slic3r::GUI::Tab.
{
    if (!m_active_page)
        return;
    bool is_BBL_printer = false;
    if (m_preset_bundle) {
      is_BBL_printer =
          m_preset_bundle->printers.get_edited_preset().has_lidar(
              m_preset_bundle);
    }
    if (m_active_page->title() == "Cooling") {
      bool cooling = m_config->opt_bool("slow_down_for_layer_cooling", 0);
      toggle_option("slow_down_min_speed", cooling);
      bool has_enable_overhang_bridge_fan = m_config->opt_bool("enable_overhang_bridge_fan", 0);
      for (auto el : {"overhang_fan_speed", "overhang_fan_threshold"})
            toggle_option(el, has_enable_overhang_bridge_fan);
      toggle_option(
          "additional_cooling_fan_speed",
          m_preset_bundle->printers.get_edited_preset().config.option<ConfigOptionBool>("auxiliary_fan")->value);
    }
    if (m_active_page->title() == "Filament")
    {
        bool pa = m_config->opt_bool("enable_pressure_advance", 0);
        toggle_option("pressure_advance", pa);
        toggle_line("cool_plate_temp_initial_layer", is_BBL_printer);
        toggle_line("eng_plate_temp_initial_layer", is_BBL_printer);
        toggle_line("textured_plate_temp_initial_layer", is_BBL_printer);
        toggle_option("chamber_temperature", !is_BBL_printer);
    }
    if (m_active_page->title() == "Setting Overrides")
        update_filament_overrides_page();
}
References Slic3r::Preset::config, Slic3r::PresetCollection::get_edited_preset(), Slic3r::Preset::has_lidar(), Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Tab::m_config, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::DynamicConfig::opt_bool(), Slic3r::ConfigBase::option(), Slic3r::PresetBundle::printers, Slic3r::GUI::Page::title(), Slic3r::GUI::Tab::toggle_line(), Slic3r::GUI::Tab::toggle_option(), update_filament_overrides_page(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by update().
toggle_show_hide_incompatible()
void Slic3r::GUI::Tab::toggle_show_hide_incompatible () inherited
{
    m_show_incompatible_presets = !m_show_incompatible_presets;
    if (m_presets_choice)
        m_presets_choice->set_show_incompatible_presets(m_show_incompatible_presets);
    update_show_hide_incompatible_button();
    update_tab_ui();
}
References Slic3r::GUI::Tab::m_presets_choice, Slic3r::GUI::Tab::m_show_incompatible_presets, Slic3r::GUI::TabPresetComboBox::set_show_incompatible_presets(), Slic3r::GUI::Tab::update_show_hide_incompatible_button(), and Slic3r::GUI::Tab::update_tab_ui().
translate_category()
wxString Slic3r::GUI::Tab::translate_category (const wxString & title, Preset::Type preset_type) static inherited
{
    if (preset_type == Preset::TYPE_PRINTER && title.Contains("Extruder ")) {
        return _("Extruder") + title.SubString(8, title.Last());
    }
    return _(title);
}
References _, and Slic3r::Preset::TYPE_PRINTER.
Referenced by Slic3r::Search::OptionsSearcher::append_options(), Slic3r::Search::create_option(), Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::update_current_page_in_background().
tree_sel_change_delayed()
bool Slic3r::GUI::Tab::tree_sel_change_delayed (wxCommandEvent & event) protected inherited
{
    // The issue apparently manifests when Show()ing a window with overlay scrollbars while the UI is frozen. For this reason,
    // we will Thaw the UI prematurely on Linux. This means destroing the no_updates object prematurely.
#ifdef __linux__
    std::unique_ptr<wxWindowUpdateLocker> no_updates(new wxWindowUpdateLocker(this));
#else
    /* On Windows we use DoubleBuffering during rendering,
     * so on Window is no needed to call a Freeze/Thaw functions.
     * But under OSX (builds compiled with MacOSX10.14.sdk) wxStaticBitmap rendering is broken without Freeze/Thaw call.
     */
//#ifdef __WXOSX__  // Use Freeze/Thaw to avoid flickering during clear/activate new page
//    wxWindowUpdateLocker noUpdates(this);
//#endif
#endif
    //BBS: GUI refactor
    Page* page = nullptr;
    const auto sel_item = m_tabctrl->GetSelection();
    // BBS: bold selection
    //OutputDebugStringA("tree_sel_change_delayed ");
    //OutputDebugStringA(m_title.c_str());
    m_tabctrl->SetItemBold(sel_item, true);
    const auto selection = sel_item >= 0 ? m_tabctrl->GetItemText(sel_item) : "";
    //OutputDebugString(selection);
    //OutputDebugStringA("\n");
    for (auto p : m_pages)
        if (translate_category(p->title(), m_type) == selection)
        {
            page = p.get();
            m_is_nonsys_values = page->m_is_nonsys_values;
            m_is_modified_values = page->m_is_modified_values;
            break;
        }
    //BBS: GUI refactor
    if (page == nullptr)
    {
        BOOST_LOG_TRIVIAL(error) << __FUNCTION__ << boost::format("can not find page with current selection %1%\n") % selection;
        return false;
    }
    void* item_data = m_tabctrl->GetItemData(sel_item);
    if (item_data)
    {
        //from update_current_page_in_background in not active tab
        m_tabctrl->SetItemData(sel_item, NULL);
        return false;
    }
    if (!m_parent->is_active_and_shown_tab((wxPanel*)this))
    {
        Tab* current_tab = dynamic_cast<Tab*>(m_parent->get_current_tab());
        m_page_view->Freeze();
        if (current_tab)
        {
            current_tab->clear_pages();
            current_tab->unselect_tree_item();
        }
        m_active_page = page;
        // BBS: not changed
        // update_undo_buttons();
        this->OnActivate();
        m_parent->set_active_tab(this);
        m_page_view->Thaw();
        return false;
    }
    //process logic in the same tab when select treeCtrlItem
    if (m_active_page == page)
        return false;
    m_active_page = page;
    auto throw_if_canceled = std::function<void()>([this](){
#ifdef WIN32
            //BBS: GUI refactor
            //TODO: remove this call currently, after refactor, there is Paint event in the queue
            //this call will cause OnPaint immediately, which will cause crash
            //wxCheckForInterrupt(m_tabctrl);
            if (m_page_switch_planned)
                throw UIBuildCanceled();
#else // WIN32
            (void)this; // silence warning
#endif
        });
    try {
        m_page_view->Freeze();
        // clear pages from the controls
        clear_pages();
        throw_if_canceled();
        //BBS: GUI refactor
        if (wxGetApp().mainframe!=nullptr && wxGetApp().mainframe->is_active_and_shown_tab(m_parent))
            activate_selected_page(throw_if_canceled);
        #ifdef __linux__
            no_updates.reset(nullptr);
        #endif
        // BBS: not changed
        // update_undo_buttons();
        throw_if_canceled();
        //BBS: GUI refactor
        //m_hsizer->Layout();
        m_parent->Layout();
        throw_if_canceled();
        // Refresh();
        m_page_view->Thaw();
    } catch (const UIBuildCanceled&) {
      if (m_active_page)
        m_active_page->clear();
        m_page_view->Thaw();
        return true;
    }
    return false;
}
References Slic3r::GUI::Tab::activate_selected_page(), Slic3r::GUI::Page::clear(), Slic3r::GUI::Tab::clear_pages(), error, Slic3r::GUI::ParamsPanel::get_current_tab(), TabCtrl::GetItemData(), TabCtrl::GetItemText(), TabCtrl::GetSelection(), Slic3r::GUI::ParamsPanel::is_active_and_shown_tab(), Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Page::m_is_modified_values, Slic3r::GUI::Tab::m_is_modified_values, Slic3r::GUI::Page::m_is_nonsys_values, Slic3r::GUI::Tab::m_is_nonsys_values, Slic3r::GUI::Tab::m_page_switch_planned, Slic3r::GUI::Tab::m_page_view, Slic3r::GUI::Tab::m_pages, Slic3r::GUI::Tab::m_parent, Slic3r::GUI::Tab::m_tabctrl, Slic3r::GUI::Tab::m_type, NULL, Slic3r::GUI::Tab::OnActivate(), Slic3r::GUI::ParamsPanel::set_active_tab(), TabCtrl::SetItemBold(), TabCtrl::SetItemData(), Slic3r::GUI::Tab::translate_category(), Slic3r::GUI::Tab::unselect_tree_item(), and void().
type()
Preset::Type Slic3r::GUI::Tab::type () const inline inherited
{ return m_type; }
References Slic3r::GUI::Tab::m_type.
Referenced by Slic3r::GUI::MainFrame::add_created_tab(), and Slic3r::GUI::ParamsPanel::set_active_tab().
unselect_tree_item()
void Slic3r::GUI::Tab::unselect_tree_item () inherited
{
    // BBS: bold selection
    const auto sel_item = m_tabctrl->GetSelection();
    m_last_select_item = sel_item;
    m_tabctrl->SetItemBold(sel_item, false);
    m_tabctrl->Unselect();
    m_active_page = nullptr;
}
References TabCtrl::GetSelection(), Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Tab::m_last_select_item, Slic3r::GUI::Tab::m_tabctrl, TabCtrl::SetItemBold(), and TabCtrl::Unselect().
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed().
update()
void Slic3r::GUI::TabFilament::update () override virtual
Implements Slic3r::GUI::Tab.
{
    if (m_preset_bundle->printers.get_selected_preset().printer_technology() == ptSLA)
        return; // ys_FIXME
    m_config_manipulation.check_filament_max_volumetric_speed(m_config);
    m_update_cnt++;
    update_description_lines();
    //BBS: GUI refactor
    //Layout();
    m_parent->Layout();
    toggle_options();
    m_update_cnt--;
    if (m_update_cnt == 0)
        wxGetApp().mainframe->on_config_changed(m_config);
}
References Slic3r::GUI::ConfigManipulation::check_filament_max_volumetric_speed(), Slic3r::PresetCollection::get_selected_preset(), Slic3r::GUI::Tab::m_config, Slic3r::GUI::Tab::m_config_manipulation, Slic3r::GUI::Tab::m_parent, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::GUI::Tab::m_update_cnt, Slic3r::Preset::printer_technology(), Slic3r::PresetBundle::printers, Slic3r::ptSLA, toggle_options(), and update_description_lines().
update_btns_enabling()
void Slic3r::GUI::Tab::update_btns_enabling () inherited
{
    // we can delete any preset from the physical printer
    // and any user preset
    const Preset& preset = m_presets->get_edited_preset();
    m_btn_delete_preset->Show((m_type == Preset::TYPE_PRINTER && m_preset_bundle->physical_printers.has_selection())
                              || (!preset.is_default && !preset.is_system));
    //if (m_btn_edit_ph_printer)
    //    m_btn_edit_ph_printer->SetToolTip( m_preset_bundle->physical_printers.has_selection() ?
    //                                       _L("Edit physical printer") : _L("Add physical printer"));
}
References Slic3r::PresetCollection::get_edited_preset(), Slic3r::PhysicalPrinterCollection::has_selection(), Slic3r::Preset::is_default, Slic3r::Preset::is_system, Slic3r::GUI::Tab::m_btn_delete_preset, Slic3r::GUI::Tab::m_preset_bundle, Slic3r::GUI::Tab::m_presets, Slic3r::GUI::Tab::m_type, Slic3r::PresetBundle::physical_printers, and Slic3r::Preset::TYPE_PRINTER.
Referenced by Slic3r::GUI::Tab::load_current_preset(), and Slic3r::GUI::Tab::update_preset_choice().
update_changed_tree_ui()
void Slic3r::GUI::Tab::update_changed_tree_ui () inherited
{
    if (m_options_list.empty())
        return;
    auto cur_item = m_tabctrl->GetFirstVisibleItem();
    if (cur_item < 0 || !m_tabctrl->IsVisible(cur_item))
        return;
    auto selected_item = m_tabctrl->GetSelection();
    auto selection = selected_item >= 0 ? m_tabctrl->GetItemText(selected_item) : "";
    while (cur_item >= 0) {
        auto title = m_tabctrl->GetItemText(cur_item);
        for (auto page : m_pages)
        {
            if (translate_category(page->title(), m_type) != title)
                continue;
            bool sys_page = true;
            bool modified_page = false;
            if (page->title() == "General") {
                std::initializer_list<const char*> optional_keys{ "extruders_count", "printable_area" };
                for (auto &opt_key : optional_keys) {
                    get_sys_and_mod_flags(opt_key, sys_page, modified_page);
                }
            }
            if (page->title() == "Dependencies") {
                if (m_type == Slic3r::Preset::TYPE_PRINTER) {
                    sys_page = m_presets->get_selected_preset_parent() != nullptr;
                    modified_page = false;
                } else {
                    if (m_type == Slic3r::Preset::TYPE_FILAMENT || m_type == Slic3r::Preset::TYPE_SLA_MATERIAL)
                        get_sys_and_mod_flags("compatible_prints", sys_page, modified_page);
                    get_sys_and_mod_flags("compatible_printers", sys_page, modified_page);
                }
            }
            for (auto group : page->m_optgroups)
            {
                if (!sys_page && modified_page)
                    break;
                for (const auto &kvp : group->opt_map()) {
                    const std::string& opt_key = kvp.first;
                    get_sys_and_mod_flags(opt_key, sys_page, modified_page);
                }
            }
            const wxColor *clr = sys_page ? (m_is_default_preset ? &m_default_text_clr : &m_sys_label_clr) :
                                 (modified_page || m_type >= Preset::TYPE_COUNT) ? &m_modified_label_clr : &m_default_text_clr;
            if (page->set_item_colour(clr))
                m_tabctrl->SetItemTextColour(cur_item, clr == &m_modified_label_clr ? *clr : StateColor(
                        std::make_pair(0x6B6B6C, (int) StateColor::NotChecked),
                        std::make_pair(*clr, (int) StateColor::Normal)));
            page->m_is_nonsys_values = !sys_page;
            page->m_is_modified_values = modified_page;
            if (selection == title) {
                m_is_nonsys_values = page->m_is_nonsys_values;
                m_is_modified_values = page->m_is_modified_values;
            }
            break;
        }
        auto next_item = m_tabctrl->GetNextVisible(cur_item);
        cur_item = next_item;
    }
}
References StateColor::Normal, StateColor::NotChecked, Slic3r::optional_keys, Slic3r::Preset::TYPE_COUNT, Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, and Slic3r::Preset::TYPE_SLA_MATERIAL.
update_changed_ui()
void Slic3r::GUI::Tab::update_changed_ui () inherited
{
    if (m_postpone_update_ui)
        return;
    const bool deep_compare = (m_type == Slic3r::Preset::TYPE_PRINTER || m_type == Slic3r::Preset::TYPE_SLA_MATERIAL);
    auto dirty_options = m_presets->current_dirty_options(deep_compare);
    auto nonsys_options = m_presets->current_different_from_parent_options(deep_compare);
    if (m_type == Preset::TYPE_PRINTER && static_cast<TabPrinter*>(this)->m_printer_technology == ptFFF) {
        TabPrinter* tab = static_cast<TabPrinter*>(this);
        if (tab->m_initial_extruders_count != tab->m_extruders_count)
            dirty_options.emplace_back("extruders_count");
        if (tab->m_sys_extruders_count != tab->m_extruders_count)
            nonsys_options.emplace_back("extruders_count");
    }
    for (auto& it : m_options_list)
        it.second = m_opt_status_value;
    for (auto opt_key : dirty_options)  m_options_list[opt_key] &= ~osInitValue;
    for (auto opt_key : nonsys_options) m_options_list[opt_key] &= ~osSystemValue;
    update_custom_dirty();
    decorate();
    wxTheApp->CallAfter([this]() {
        if (parent()) //To avoid a crash, parent should be exist for a moment of a tree updating
            update_changed_tree_ui();
    });
    // BBS:
    update_undo_buttons();
}
References Slic3r::GUI::TabPrinter::m_extruders_count, Slic3r::GUI::TabPrinter::m_initial_extruders_count, Slic3r::GUI::TabPrinter::m_printer_technology, Slic3r::GUI::TabPrinter::m_sys_extruders_count, Slic3r::ptFFF, Slic3r::Preset::TYPE_PRINTER, and Slic3r::Preset::TYPE_SLA_MATERIAL.
Referenced by Slic3r::GUI::Tab::activate_selected_page(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::Tab::load_current_preset(), and Slic3r::GUI::Tab::save_preset().
update_current_page_in_background()
bool Slic3r::GUI::Tab::update_current_page_in_background (int & item) inherited
{
    Page* page = nullptr;
    const auto selection = item >= 0 ? m_tabctrl->GetItemText(item) : "";
    for (auto p : m_pages)
        if (translate_category(p->title(), m_type) == selection)
        {
            page = p.get();
            break;
        }
    if (page == nullptr || m_active_page == page)
        return false;
    bool active_tab = false;
    if (wxGetApp().mainframe != nullptr && wxGetApp().mainframe->is_active_and_shown_tab(m_parent))
        active_tab = true;
    if (!active_tab || (!m_parent->is_active_and_shown_tab((wxPanel*)this)))
    {
        m_is_nonsys_values = page->m_is_nonsys_values;
        m_is_modified_values = page->m_is_modified_values;
        // BBS: not need active
        // m_active_page = page;
        // invalidated highlighter, if any exists
        m_highlighter.invalidate();
        // clear pages from the controlls
        // BBS: fix after new layout, clear page in backgroud
        if (m_parent->is_active_and_shown_tab((wxPanel*)this))
            m_parent->clear_page();
        for (auto p : m_pages)
            p->clear();
        update_undo_buttons();
        // BBS: this is not used, because we not SelectItem in background
        //todo: update selected item of tree_ctrl
        // wxTreeItemData item_data;
        // m_tabctrl->SetItemData(item, &item_data);
        return false;
    }
    return true;
}
References Slic3r::GUI::ParamsPanel::clear_page(), TabCtrl::GetItemText(), Slic3r::GUI::Tab::Highlighter::invalidate(), Slic3r::GUI::ParamsPanel::is_active_and_shown_tab(), Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Tab::m_highlighter, Slic3r::GUI::Page::m_is_modified_values, Slic3r::GUI::Tab::m_is_modified_values, Slic3r::GUI::Page::m_is_nonsys_values, Slic3r::GUI::Tab::m_is_nonsys_values, Slic3r::GUI::Tab::m_pages, Slic3r::GUI::Tab::m_parent, Slic3r::GUI::Tab::m_tabctrl, Slic3r::GUI::Tab::m_type, Slic3r::GUI::Tab::translate_category(), and Slic3r::GUI::Tab::update_undo_buttons().
Referenced by Slic3r::GUI::Tab::rebuild_page_tree().
update_custom_dirty()
virtual void Slic3r::GUI::Tab::update_custom_dirty () inline virtual inherited
Reimplemented in Slic3r::GUI::TabPrintModel, and Slic3r::GUI::TabPrintLayer.
{}
update_description_lines()
void Slic3r::GUI::TabFilament::update_description_lines () override virtual
Reimplemented from Slic3r::GUI::Tab.
{
    Tab::update_description_lines();
    if (!m_active_page)
        return;
    if (m_active_page->title() == "Cooling" && m_cooling_description_line)
        m_cooling_description_line->SetText(from_u8(PresetHints::cooling_description(m_presets->get_edited_preset())));
    //BBS
    //if (m_active_page->title() == "Filament" && m_volumetric_speed_description_line)
    //    this->update_volumetric_flow_preset_hints();
}
References Slic3r::PresetHints::cooling_description(), Slic3r::GUI::from_u8(), Slic3r::PresetCollection::get_edited_preset(), Slic3r::GUI::Tab::m_active_page, m_cooling_description_line, Slic3r::GUI::Tab::m_presets, Slic3r::GUI::ogStaticText::SetText(), Slic3r::GUI::Page::title(), and Slic3r::GUI::Tab::update_description_lines().
Referenced by update().
update_dirty()
void Slic3r::GUI::Tab::update_dirty () inherited
{
    if (m_postpone_update_ui)
        return;
    if (m_presets_choice) {
        m_presets_choice->update_dirty();
        on_presets_changed();
    } else {
        m_presets->update_dirty();
    }
    update_changed_ui();
}
Referenced by build(), Slic3r::GUI::TabPrinter::build_unregular_pages(), Slic3r::GUI::Tab::get_config_manipulation(), Slic3r::GUI::TabPrintModel::update_model_config(), and Slic3r::GUI::validate_custom_gcode_cb().
update_filament_overrides_page()
void Slic3r::GUI::TabFilament::update_filament_overrides_page () private
{
    if (!m_active_page || m_active_page->title() != "Setting Overrides")
        return;
    //BBS: GUI refactor
    if (m_overrides_options.size() <= 0)
        return;
    Page* page = m_active_page;
    const auto og_it = std::find_if(page->m_optgroups.begin(), page->m_optgroups.end(), [](const ConfigOptionsGroupShp og) { return og->title == "Retraction"; });
    if (og_it == page->m_optgroups.end())
        return;
    ConfigOptionsGroupShp optgroup = *og_it;
    std::vector<std::string> opt_keys = {   "filament_retraction_length",
                                            "filament_z_hop",
                                            "filament_z_hop_types",
                                            "filament_retract_lift_above",
                                            "filament_retract_lift_below",
                                            "filament_retract_lift_enforce",
                                            "filament_retraction_speed",
                                            "filament_deretraction_speed",
                                            "filament_retract_restart_extra",
                                            "filament_retraction_minimum_travel",
                                            "filament_retract_when_changing_layer",
                                            "filament_wipe",
                                            //BBS
                                            "filament_wipe_distance",
                                            "filament_retract_before_wipe",
                                            //SoftFever
                                            // "filament_seam_gap"
                                        };
    const int extruder_idx = 0; // #ys_FIXME
    const bool have_retract_length = m_config->option("filament_retraction_length")->is_nil() ||
                                     m_config->opt_float("filament_retraction_length", extruder_idx) > 0;
    for (const std::string& opt_key : opt_keys)
    {
        bool is_checked = opt_key=="filament_retraction_length" ? true : have_retract_length;
        m_overrides_options[opt_key]->Enable(is_checked);
        is_checked &= !m_config->option(opt_key)->is_nil();
        m_overrides_options[opt_key]->SetValue(is_checked);
        Field* field = optgroup->get_fieldc(opt_key, extruder_idx);
        if (field != nullptr)
            field->toggle(is_checked);
    }
}
References Slic3r::ConfigOption::is_nil(), Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Tab::m_config, Slic3r::GUI::Page::m_optgroups, m_overrides_options, Slic3r::DynamicConfig::opt_float(), Slic3r::ConfigBase::option(), Slic3r::GUI::Page::title(), and Slic3r::GUI::Field::toggle().
Referenced by toggle_options().
update_frequently_changed_parameters()
void Slic3r::GUI::Tab::update_frequently_changed_parameters () protected inherited
{
    const bool is_fff = supports_printer_technology(ptFFF);
    auto og_freq_chng_params = wxGetApp().sidebar().og_freq_chng_params(is_fff);
    if (!og_freq_chng_params) return;
    og_freq_chng_params->set_value("support", support_combo_value_for_config(*m_config, is_fff));
    if (! is_fff)
        og_freq_chng_params->set_value("pad", pad_combo_value_for_config(*m_config));
    const std::string updated_value_key = is_fff ? "sparse_infill_density" : "pad_enable";
    const boost::any val = og_freq_chng_params->get_config_value(*m_config, updated_value_key);
    og_freq_chng_params->set_value(updated_value_key, val);
    if (is_fff)
    {
        og_freq_chng_params->set_value("brim", bool(m_config->opt_float("brim_width") > 0.0));
        update_wiping_button_visibility();
    }
}
References Slic3r::GUI::pad_combo_value_for_config(), Slic3r::ptFFF, and Slic3r::GUI::support_combo_value_for_config().
Referenced by Slic3r::GUI::Tab::load_current_preset().
update_label_colours()
void Slic3r::GUI::Tab::update_label_colours () inherited
{
    m_default_text_clr = wxGetApp().get_label_clr_default();
    if (m_sys_label_clr == wxGetApp().get_label_clr_sys() && m_modified_label_clr == wxGetApp().get_label_clr_modified())
        return;
    m_sys_label_clr = wxGetApp().get_label_clr_sys();
    m_modified_label_clr = wxGetApp().get_label_clr_modified();
    //update options "decoration"
    for (const auto& opt : m_options_list)
    {
        const wxColour *color = &m_sys_label_clr;
        // value isn't equal to system value
        if ((opt.second & osSystemValue) == 0) {
            // value is equal to last saved
            if ((opt.second & osInitValue) != 0)
                color = &m_default_text_clr;
            // value is modified
            else
                color = &m_modified_label_clr;
        }
        if (opt.first == "printable_area"            ||
            opt.first == "compatible_prints"    || opt.first == "compatible_printers"           ) {
            if (m_colored_Label_colors.find(opt.first) != m_colored_Label_colors.end())
                m_colored_Label_colors.at(opt.first) = *color;
            continue;
        }
        Field* field = get_field(opt.first);
        if (field == nullptr) continue;
        field->set_label_colour(color);
    }
    auto cur_item = m_tabctrl->GetFirstVisibleItem();
    if (cur_item < 0 || !m_tabctrl->IsVisible(cur_item))
        return;
    while (cur_item >= 0) {
        auto title = m_tabctrl->GetItemText(cur_item);
        for (auto page : m_pages)
        {
            if (translate_category(page->title(), m_type) != title)
                continue;
            const wxColor *clr = !page->m_is_nonsys_values ? &m_sys_label_clr :
                page->m_is_modified_values ? &m_modified_label_clr :
                (m_type < Preset::TYPE_COUNT ? &m_default_text_clr : &m_modified_label_clr);
            m_tabctrl->SetItemTextColour(cur_item, clr == &m_modified_label_clr ? *clr : StateColor(
                        std::make_pair(0x6B6B6C, (int) StateColor::NotChecked),
                        std::make_pair(*clr, (int) StateColor::Normal)));
            break;
        }
        cur_item = m_tabctrl->GetNextVisible(cur_item);
    }
    decorate();
}
References StateColor::Normal, StateColor::NotChecked, Slic3r::GUI::Field::set_label_colour(), and Slic3r::Preset::TYPE_COUNT.
update_mode()
void Slic3r::GUI::Tab::update_mode () inherited
{
    m_mode = wxGetApp().get_mode();
    //BBS: GUI refactor
    // update mode for ModeSizer
    //if (m_mode_sizer)
    //    m_mode_sizer->SetMode(m_mode);
    update_visibility();
    update_changed_tree_ui();
}
update_preset_choice()
void Slic3r::GUI::Tab::update_preset_choice () inherited
{
    if (m_presets_choice)
        m_presets_choice->update();
    update_btns_enabling();
}
References Slic3r::GUI::Tab::m_presets_choice, Slic3r::GUI::TabPresetComboBox::update(), and Slic3r::GUI::Tab::update_btns_enabling().
update_preset_description_line()
void Slic3r::GUI::Tab::update_preset_description_line () protected inherited
{
    const Preset* parent = m_presets->get_selected_preset_parent();
    const Preset& preset = m_presets->get_edited_preset();
    wxString description_line;
    //if (preset.is_default) {
    //    description_line = _(L("This is a default preset."));
    //} else if (preset.is_system) {
    //    description_line = _(L("This is a system preset."));
    //} else if (parent == nullptr) {
    //    description_line = _(L("Current preset is inherited from the default preset."));
    //} else {
    //    std::string name = parent->name;
    //    boost::replace_all(name, "&", "&&");
    //    description_line = _(L("Current preset is inherited from")) + ":\n\t" + from_u8(name);
    //}
    //if (preset.is_default || preset.is_system)
    //    description_line += "\n\t" + _(L("It can't be deleted or modified.")) +
    //                        "\n\t" + _(L("Any modifications should be saved as a new preset inherited from this one.")) +
    //                        "\n\t" + _(L("To do that please specify a new name for the preset."));
    //if (parent && parent->vendor)
    //{
    //    description_line += "\n\n" + _(L("Additional information:")) + "\n";
    //    description_line += "\t" + _(L("vendor")) + ": " + (m_type == Slic3r::Preset::TYPE_PRINTER ? "\n\t\t" : "") + parent->vendor->name +
    //                        ", ver: " + parent->vendor->config_version.to_string();
    //    if (m_type == Slic3r::Preset::TYPE_PRINTER) {
    //        const std::string &printer_model = preset.config.opt_string("printer_model");
    //        if (! printer_model.empty())
    //            description_line += "\n\n\t" + _(L("printer model")) + ": \n\t\t" + printer_model;
    //        switch (preset.printer_technology()) {
    //        case ptFFF:
    //        {
    //            //FIXME add prefered_sla_material_profile for SLA
    //            const std::string              &default_print_profile = preset.config.opt_string("default_print_profile");
    //            const std::vector<std::string> &default_filament_profiles = preset.config.option<ConfigOptionStrings>("default_filament_profile")->values;
    //            if (!default_print_profile.empty())
    //                description_line += "\n\n\t" + _(L("default print profile")) + ": \n\t\t" + default_print_profile;
    //            if (!default_filament_profiles.empty())
    //            {
    //                description_line += "\n\n\t" + _(L("default filament profile")) + ": \n\t\t";
    //                for (auto& profile : default_filament_profiles) {
    //                    if (&profile != &*default_filament_profiles.begin())
    //                        description_line += ", ";
    //                    description_line += profile;
    //                }
    //            }
    //            break;
    //        }
    //        case ptSLA:
    //        {
    //            //FIXME add prefered_sla_material_profile for SLA
    //            const std::string &default_sla_material_profile = preset.config.opt_string("default_sla_material_profile");
    //            if (!default_sla_material_profile.empty())
    //                description_line += "\n\n\t" + _(L("default SLA material profile")) + ": \n\t\t" + default_sla_material_profile;
    //            const std::string &default_sla_print_profile = preset.config.opt_string("default_sla_print_profile");
    //            if (!default_sla_print_profile.empty())
    //                description_line += "\n\n\t" + _(L("default SLA print profile")) + ": \n\t\t" + default_sla_print_profile;
    //            break;
    //        }
    //        default: break;
    //        }
    //    }
    //    else if (!preset.alias.empty())
    //    {
    //        description_line += "\n\n\t" + _(L("full profile name"))     + ": \n\t\t" + preset.name;
    //        description_line += "\n\t"   + _(L("symbolic profile name")) + ": \n\t\t" + preset.alias;
    //    }
    //}
    m_parent_preset_description_line->SetText(description_line, false);
    if (m_detach_preset_btn)
        m_detach_preset_btn->Show(parent && parent->is_system && !preset.is_default);
    //BBS: GUI refactor
    //Layout();
    m_parent->Layout();
}
References Slic3r::Preset::is_default, and Slic3r::Preset::is_system.
Referenced by Slic3r::GUI::Tab::update_description_lines().
update_saved_preset_from_current_preset()
void Slic3r::GUI::Tab::update_saved_preset_from_current_preset () inherited
{ m_presets->update_saved_preset_from_current_preset(); }
References Slic3r::GUI::Tab::m_presets, and Slic3r::PresetCollection::update_saved_preset_from_current_preset().
update_show_hide_incompatible_button()
void Slic3r::GUI::Tab::update_show_hide_incompatible_button () inherited
{
    //BBS: GUI refactor
    /*m_btn_hide_incompatible_presets->SetBitmap_(m_show_incompatible_presets ?
        m_bmp_show_incompatible_presets : m_bmp_hide_incompatible_presets);
    m_btn_hide_incompatible_presets->SetToolTip(m_show_incompatible_presets ?
        "Both compatible an incompatible presets are shown. Click to hide presets not compatible with the current printer." :
        "Only compatible presets are shown. Click to show both the presets compatible and not compatible with the current printer.");*/
}
Referenced by Slic3r::GUI::Tab::toggle_show_hide_incompatible(), and Slic3r::GUI::Tab::update_ui_from_settings().
update_tab_ui()
void Slic3r::GUI::Tab::update_tab_ui (bool update_plater_presets = false) inherited
{
    if (m_presets_choice) {
        m_presets_choice->update();
        if (update_plater_presets)
            on_presets_changed();
    }
}
Referenced by Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::Tab::toggle_show_hide_incompatible(), and Slic3r::GUI::Tab::update_ui_from_settings().
update_ui_from_settings()
void Slic3r::GUI::Tab::update_ui_from_settings () inherited
{
    // Show the 'show / hide presets' button only for the print and filament tabs, and only if enabled
    // in application preferences.
    m_show_btn_incompatible_presets = true;
    bool show = m_show_btn_incompatible_presets && m_type != Slic3r::Preset::TYPE_PRINTER;
    //BBS: GUI refactor
    //Layout();
    m_parent->Layout();
    //show ? m_btn_hide_incompatible_presets->Show() :  m_btn_hide_incompatible_presets->Hide();
    // If the 'show / hide presets' button is hidden, hide the incompatible presets.
    if (show) {
        update_show_hide_incompatible_button();
    }
    else {
        if (m_show_incompatible_presets) {
            m_show_incompatible_presets = false;
            update_tab_ui();
        }
    }
}
References Slic3r::GUI::Tab::m_parent, Slic3r::GUI::Tab::m_show_btn_incompatible_presets, Slic3r::GUI::Tab::m_show_incompatible_presets, Slic3r::GUI::Tab::m_type, Slic3r::Preset::TYPE_PRINTER, Slic3r::GUI::Tab::update_show_hide_incompatible_button(), and Slic3r::GUI::Tab::update_tab_ui().
update_ui_items_related_on_parent_preset()
void Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset (const Preset * selected_preset_parent) inherited
{
    m_is_default_preset = selected_preset_parent != nullptr && selected_preset_parent->is_default;
    m_bmp_non_system = selected_preset_parent ? &m_bmp_value_unlock : &m_bmp_white_bullet;
    m_ttg_non_system = selected_preset_parent ? &m_ttg_value_unlock : &m_ttg_white_bullet_ns;
    m_tt_non_system  = selected_preset_parent ? &m_tt_value_unlock  : &m_ttg_white_bullet_ns;
}
References Slic3r::Preset::is_default, Slic3r::GUI::Tab::m_bmp_non_system, Slic3r::GUI::Tab::m_bmp_value_unlock, Slic3r::GUI::Tab::m_bmp_white_bullet, Slic3r::GUI::Tab::m_is_default_preset, Slic3r::GUI::Tab::m_tt_non_system, Slic3r::GUI::Tab::m_tt_value_unlock, Slic3r::GUI::Tab::m_ttg_non_system, Slic3r::GUI::Tab::m_ttg_value_unlock, and Slic3r::GUI::Tab::m_ttg_white_bullet_ns.
Referenced by Slic3r::GUI::Tab::load_current_preset(), and Slic3r::GUI::Tab::save_preset().
update_undo_buttons()
void Slic3r::GUI::Tab::update_undo_buttons () inherited
{
    // BBS: restore all pages in preset
    m_undo_btn->        SetBitmap_(m_presets->get_edited_preset().is_dirty ? m_bmp_value_revert: m_bmp_white_bullet);
    m_undo_to_sys_btn-> SetBitmap_(m_is_nonsys_values   ? *m_bmp_non_system : m_bmp_value_lock);
    m_undo_btn->SetToolTip(m_presets->get_edited_preset().is_dirty ? _L("Click to reset all settings to the last saved preset.") : m_ttg_white_bullet);
    m_undo_to_sys_btn->SetToolTip(m_is_nonsys_values ? *m_ttg_non_system : m_ttg_value_lock);
}
References _L.
Referenced by Slic3r::GUI::Tab::update_current_page_in_background().
update_visibility()
void Slic3r::GUI::Tab::update_visibility () inherited
{
    Freeze(); // There is needed Freeze/Thaw to avoid a flashing after Show/Layout
    for (auto page : m_pages)
        page->update_visibility(m_mode, page.get() == m_active_page);
    rebuild_page_tree();
    if (m_type == Preset::TYPE_SLA_PRINT)
        update_description_lines();
    //BBS: GUI refactor
    //Layout();
    m_parent->Layout();
    Thaw();
}
References Slic3r::Preset::TYPE_SLA_PRINT.
Referenced by Slic3r::GUI::Tab::load_current_preset().
update_volumetric_flow_preset_hints()
void Slic3r::GUI::TabFilament::update_volumetric_flow_preset_hints () private
update_wiping_button_visibility()
void Slic3r::GUI::Tab::update_wiping_button_visibility () inherited
{
    if (m_preset_bundle->printers.get_selected_preset().printer_technology() == ptSLA)
        return; // ys_FIXME
    bool wipe_tower_enabled = dynamic_cast<ConfigOptionBool*>(  (m_preset_bundle->prints.get_edited_preset().config  ).option("enable_prime_tower"))->value;
    bool multiple_extruders = dynamic_cast<ConfigOptionFloats*>((m_preset_bundle->printers.get_edited_preset().config).option("nozzle_diameter"))->values.size() > 1;
    auto wiping_dialog_button = wxGetApp().sidebar().get_wiping_dialog_button();
    if (wiping_dialog_button) {
        wiping_dialog_button->Show(wipe_tower_enabled && multiple_extruders);
        wiping_dialog_button->GetParent()->Layout();
    }
}
References Slic3r::ptSLA, and Slic3r::ConfigOptionVector< T >::size().
validate_custom_gcode()
bool Slic3r::GUI::Tab::validate_custom_gcode (const wxString & title, const std::string & gcode) static inherited
{
    std::vector<std::string> tags;
    bool invalid = GCodeProcessor::contains_reserved_tags(gcode, 5, tags);
    if (invalid) {
        std::string lines = ":\n";
        for (const std::string& keyword : tags)
            lines += ";" + keyword + "\n";
        wxString reports = format_wxstr(
            _L_PLURAL("Following line %s contains reserved keywords.\nPlease remove it, or will beat G-code visualization and printing time estimation.",
                      "Following lines %s contain reserved keywords.\nPlease remove them, or will beat G-code visualization and printing time estimation.",
                      tags.size()),
            lines);
        //wxMessageDialog dialog(wxGetApp().mainframe, reports, _L("Found reserved keywords in") + " " + _(title), wxICON_WARNING | wxOK);
        MessageDialog dialog(wxGetApp().mainframe, reports, _L("Reserved keywords found") + " " + _(title), wxICON_WARNING | wxOK);
        dialog.ShowModal();
    }
    return !invalid;
}
References _, _L, _L_PLURAL, Slic3r::GCodeProcessor::contains_reserved_tags(), Slic3r::GUI::format_wxstr(), Slic3r::GUI::gcode(), Slic3r::GUI::DPIAware< P >::ShowModal(), and Slic3r::GUI::Tab::title().
Referenced by Slic3r::GUI::validate_custom_gcode_cb(), and Slic3r::GUI::Tab::validate_custom_gcodes().
validate_custom_gcodes()
bool Slic3r::GUI::Tab::validate_custom_gcodes () inherited
{
    if (m_type != Preset::TYPE_FILAMENT &&
        (m_type != Preset::TYPE_PRINTER || static_cast<TabPrinter*>(this)->m_printer_technology != ptFFF))
        return true;
    if (m_active_page->title() != L("Custom G-code"))
        return true;
    // When we switch Settings tab after editing of the custom g-code, then warning message could ba already shown after KillFocus event
    // and then it's no need to show it again
    if (validate_custom_gcodes_was_shown) {
        validate_custom_gcodes_was_shown = false;
        return true;
    }
    bool valid = true;
    for (auto opt_group : m_active_page->m_optgroups) {
        assert(opt_group->opt_map().size() == 1);
        if (!opt_group->is_activated())
            break;
        std::string key = opt_group->opt_map().begin()->first;
        valid &= validate_custom_gcode(opt_group->title, boost::any_cast<std::string>(opt_group->get_value(key)));
        if (!valid)
            break;
    }
    return valid;
}
References L, Slic3r::GUI::Tab::m_active_page, Slic3r::GUI::Page::m_optgroups, Slic3r::GUI::Tab::m_type, Slic3r::ptFFF, Slic3r::GUI::Page::title(), Slic3r::Preset::TYPE_FILAMENT, Slic3r::Preset::TYPE_PRINTER, Slic3r::GUI::Tab::validate_custom_gcode(), and Slic3r::GUI::Tab::validate_custom_gcodes_was_shown.
Member Data Documentation
m_active_page
Page* Slic3r::GUI::Tab::m_active_page {nullptr} protected inherited
Referenced by Slic3r::GUI::Tab::activate_selected_page(), Slic3r::GUI::TabPrintModel::activate_selected_page(), Slic3r::GUI::TabPrinter::activate_selected_page(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::TabPrinter::reload_config(), Slic3r::GUI::Tab::set_expanded(), toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::TabSLAPrint::toggle_options(), Slic3r::GUI::Tab::tree_sel_change_delayed(), Slic3r::GUI::Tab::unselect_tree_item(), Slic3r::GUI::Tab::update_current_page_in_background(), Slic3r::GUI::Tab::update_description_lines(), update_description_lines(), update_filament_overrides_page(), Slic3r::GUI::TabPrintModel::update_model_config(), and Slic3r::GUI::Tab::validate_custom_gcodes().
m_bmp_hide_incompatible_presets
ScalableBitmap Slic3r::GUI::Tab::m_bmp_hide_incompatible_presets protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_bmp_non_system
ScalableBitmap* Slic3r::GUI::Tab::m_bmp_non_system protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_bmp_show_incompatible_presets
ScalableBitmap Slic3r::GUI::Tab::m_bmp_show_incompatible_presets protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_bmp_value_lock
ScalableBitmap Slic3r::GUI::Tab::m_bmp_value_lock protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_bmp_value_revert
ScalableBitmap Slic3r::GUI::Tab::m_bmp_value_revert protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_bmp_value_unlock
ScalableBitmap Slic3r::GUI::Tab::m_bmp_value_unlock protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_bmp_white_bullet
ScalableBitmap Slic3r::GUI::Tab::m_bmp_white_bullet protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_btn_compare_preset
ScalableButton* Slic3r::GUI::Tab::m_btn_compare_preset protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_btn_delete_preset
ScalableButton* Slic3r::GUI::Tab::m_btn_delete_preset protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::Tab::save_preset(), and Slic3r::GUI::Tab::update_btns_enabling().
m_btn_save_preset
ScalableButton* Slic3r::GUI::Tab::m_btn_save_preset protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_btn_search
ScalableButton* Slic3r::GUI::Tab::m_btn_search protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_cache_config
DynamicPrintConfig Slic3r::GUI::Tab::m_cache_config protected inherited
m_category_icon
std::map<wxString, std::string> Slic3r::GUI::Tab::m_category_icon protected inherited
Referenced by Slic3r::GUI::Tab::get_category_icon_map().
m_colored_Label_colors
std::map<std::string, wxColour> Slic3r::GUI::Tab::m_colored_Label_colors inherited
Referenced by Slic3r::GUI::Tab::create_line_with_widget().
m_compatible_printers
PresetDependencies Slic3r::GUI::Tab::m_compatible_printers protected inherited
Referenced by Slic3r::GUI::Tab::Tab(), Slic3r::GUI::Tab::clear_pages(), reload_config(), Slic3r::GUI::TabSLAMaterial::reload_config(), and Slic3r::GUI::TabSLAPrint::reload_config().
m_compatible_prints
PresetDependencies Slic3r::GUI::Tab::m_compatible_prints protected inherited
Referenced by Slic3r::GUI::Tab::Tab(), Slic3r::GUI::Tab::clear_pages(), reload_config(), and Slic3r::GUI::TabSLAMaterial::reload_config().
m_completed
bool Slic3r::GUI::Tab::m_completed { false } protected inherited
Referenced by Slic3r::GUI::Tab::completed().
m_config
DynamicPrintConfig* Slic3r::GUI::Tab::m_config inherited
Referenced by Slic3r::GUI::add_correct_opts_to_options_list(), Slic3r::GUI::TabPrinter::build(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::TabPrinter::build_unregular_pages(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::Tab::compatible_widget_reload(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::Tab::get_config(), Slic3r::GUI::TabPrinter::on_preset_loaded(), Slic3r::GUI::TabPrintModel::on_value_change(), Slic3r::GUI::TabPrintModel::reset_model_config(), Slic3r::GUI::TabPrintModel::set_model_config(), toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::TabSLAPrint::toggle_options(), update(), Slic3r::GUI::TabPrinter::update(), Slic3r::GUI::TabSLAMaterial::update(), Slic3r::GUI::TabSLAPrint::update(), Slic3r::GUI::TabPrinter::update_fff(), update_filament_overrides_page(), and Slic3r::GUI::TabPrintModel::update_model_config().
m_config_manipulation
ConfigManipulation Slic3r::GUI::Tab::m_config_manipulation protected inherited
Referenced by Slic3r::GUI::Tab::Tab(), build(), Slic3r::GUI::TabPrintModel::on_value_change(), Slic3r::GUI::TabSLAMaterial::toggle_options(), Slic3r::GUI::TabSLAPrint::toggle_options(), update(), Slic3r::GUI::TabSLAPrint::update(), and Slic3r::GUI::TabPrintModel::update_model_config().
m_cooling_description_line
ogStaticText* Slic3r::GUI::TabFilament::m_cooling_description_line {nullptr} private
Referenced by clear_pages(), and update_description_lines().
m_default_text_clr
wxColour Slic3r::GUI::Tab::m_default_text_clr protected inherited
Referenced by Slic3r::GUI::Tab::create_line_with_widget(), and Slic3r::GUI::Tab::create_preset_tab().
m_dependent_tabs
std::vector<Preset::Type> Slic3r::GUI::Tab::m_dependent_tabs protected inherited
Referenced by Slic3r::GUI::Tab::select_preset().
m_detach_preset_btn
ScalableButton* Slic3r::GUI::Tab::m_detach_preset_btn = nullptr inherited
Referenced by Slic3r::GUI::Tab::clear_pages().
m_disable_tree_sel_changed_event
bool Slic3r::GUI::Tab::m_disable_tree_sel_changed_event {false} protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Tab::rebuild_page_tree().
m_em_unit
int Slic3r::GUI::Tab::m_em_unit protected inherited
Referenced by Slic3r::GUI::Tab::Tab(), and Slic3r::GUI::Tab::create_preset_tab().
m_highlighter
struct Slic3r::GUI::Tab::Highlighter Slic3r::GUI::Tab::m_highlighter protected inherited
Referenced by Slic3r::GUI::Tab::Tab(), Slic3r::GUI::Tab::clear_pages(), and Slic3r::GUI::Tab::update_current_page_in_background().
m_icon_count
int Slic3r::GUI::Tab::m_icon_count protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_icon_index
std::map<std::string, size_t> Slic3r::GUI::Tab::m_icon_index protected inherited
m_icons
wxImageList* Slic3r::GUI::Tab::m_icons protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_is_default_preset
bool Slic3r::GUI::Tab::m_is_default_preset {false} protected inherited
Referenced by Slic3r::GUI::TabPrintModel::TabPrintModel(), and Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_is_modified_values
bool Slic3r::GUI::Tab::m_is_modified_values { false } protected inherited
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::update_current_page_in_background().
m_is_nonsys_values
bool Slic3r::GUI::Tab::m_is_nonsys_values { true } protected inherited
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed(), and Slic3r::GUI::Tab::update_current_page_in_background().
m_is_timelapse_wipe_tower_already_prompted
bool Slic3r::GUI::Tab::m_is_timelapse_wipe_tower_already_prompted = false protected inherited
m_last_select_item
int Slic3r::GUI::Tab::m_last_select_item = -1 protected inherited
Referenced by Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::restore_last_select_item(), and Slic3r::GUI::Tab::unselect_tree_item().
m_main_sizer
wxBoxSizer* Slic3r::GUI::Tab::m_main_sizer protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Tab::set_expanded().
m_mode
ConfigOptionMode Slic3r::GUI::Tab::m_mode = comAdvanced protected inherited
Referenced by Slic3r::GUI::Tab::activate_selected_page(), and Slic3r::GUI::TabPrintModel::update_model_config().
m_mode_view
SwitchButton* Slic3r::GUI::Tab::m_mode_view = nullptr inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_modified_label_clr
wxColour Slic3r::GUI::Tab::m_modified_label_clr protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Tab::rebuild_page_tree().
m_name
std::string Slic3r::GUI::Tab::m_name protected inherited
Referenced by Slic3r::GUI::Tab::set_type().
m_opt_status_value
int Slic3r::GUI::Tab::m_opt_status_value = 0 protected inherited
Referenced by Slic3r::GUI::TabPrintModel::TabPrintModel(), and Slic3r::GUI::Tab::load_current_preset().
m_options_list
std::map<std::string, int> Slic3r::GUI::Tab::m_options_list protected inherited
Referenced by Slic3r::GUI::TabPrintLayer::update_custom_dirty().
m_overrides_options
std::map<std::string, wxCheckBox*> Slic3r::GUI::TabFilament::m_overrides_options private
Referenced by add_filament_overrides_page(), clear_pages(), and update_filament_overrides_page().
m_page_switch_planned
bool Slic3r::GUI::Tab::m_page_switch_planned = false protected inherited
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed().
m_page_switch_running
bool Slic3r::GUI::Tab::m_page_switch_running = false protected inherited
m_page_view
wxScrolledWindow* Slic3r::GUI::Tab::m_page_view {nullptr} protected inherited
Referenced by Slic3r::GUI::Tab::tree_sel_change_delayed().
m_pages
std::vector<PageShp> Slic3r::GUI::Tab::m_pages protected inherited
Referenced by Slic3r::GUI::TabPrintModel::build(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::TabPrinter::build_unregular_pages(), Slic3r::GUI::Tab::clear_pages(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::tree_sel_change_delayed(), Slic3r::GUI::Tab::update_current_page_in_background(), and Slic3r::GUI::TabPrinter::update_pages().
m_parent
ParamsPanel* Slic3r::GUI::Tab::m_parent protected inherited
Referenced by Slic3r::GUI::Tab::Tab(), Slic3r::GUI::Tab::clear_pages(), Slic3r::GUI::Tab::parent(), Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Tab::tree_sel_change_delayed(), update(), Slic3r::GUI::TabPrinter::update(), Slic3r::GUI::TabSLAPrint::update(), Slic3r::GUI::Tab::update_current_page_in_background(), and Slic3r::GUI::Tab::update_ui_from_settings().
m_parent_preset_description_line
ogStaticText* Slic3r::GUI::Tab::m_parent_preset_description_line = nullptr inherited
Referenced by Slic3r::GUI::Tab::clear_pages(), and Slic3r::GUI::Tab::update_description_lines().
m_postpone_update_ui
bool Slic3r::GUI::Tab::m_postpone_update_ui {false} protected inherited
m_preset_bundle
PresetBundle* Slic3r::GUI::Tab::m_preset_bundle inherited
Referenced by build(), Slic3r::GUI::TabPrinter::build(), Slic3r::GUI::TabSLAPrint::build(), Slic3r::GUI::Tab::compatible_widget_create(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::Tab::delete_preset(), Slic3r::GUI::TabPrinter::extruders_count_changed(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Tab::select_preset(), toggle_options(), Slic3r::GUI::TabPrinter::toggle_options(), update(), Slic3r::GUI::TabSLAMaterial::update(), Slic3r::GUI::TabSLAPrint::update(), Slic3r::GUI::Tab::update_btns_enabling(), and Slic3r::GUI::TabPrinter::update_pages().
m_presets
PresetCollection* Slic3r::GUI::Tab::m_presets = nullptr inherited
Referenced by Slic3r::GUI::TabPrinter::apply_extruder_cnt_from_cache(), Slic3r::GUI::TabPrintModel::build(), build(), Slic3r::GUI::TabPrinter::build(), Slic3r::GUI::TabSLAPrint::build(), Slic3r::GUI::TabPrinter::build_fff(), Slic3r::GUI::TabPrinter::cache_extruder_cnt(), Slic3r::GUI::GUI_App::check_and_keep_current_preset_changes(), Slic3r::GUI::Tab::current_preset_is_dirty(), Slic3r::GUI::Tab::delete_preset(), Slic3r::GUI::Tab::get_presets(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::GUI::Tab::name(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Tab::saved_preset_is_dirty(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::TabPrinter::toggle_options(), Slic3r::GUI::TabPrinter::update(), Slic3r::GUI::Tab::update_btns_enabling(), update_description_lines(), Slic3r::GUI::TabPrinter::update_pages(), and Slic3r::GUI::Tab::update_saved_preset_from_current_preset().
m_presets_choice
TabPresetComboBox* Slic3r::GUI::Tab::m_presets_choice { nullptr } protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::Tab::delete_preset(), Slic3r::GUI::Tab::get_combo_box(), Slic3r::GUI::Tab::reactive_preset_combo_box(), Slic3r::GUI::Tab::set_expanded(), Slic3r::GUI::Tab::toggle_show_hide_incompatible(), and Slic3r::GUI::Tab::update_preset_choice().
m_scaled_bitmaps
std::vector<ScalableBitmap*> Slic3r::GUI::Tab::m_scaled_bitmaps = {} protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_scaled_buttons
std::vector<ScalableButton*> Slic3r::GUI::Tab::m_scaled_buttons = {} protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_scaled_icons_list
std::vector<ScalableBitmap> Slic3r::GUI::Tab::m_scaled_icons_list = {} protected inherited
m_search_input
TextInput* Slic3r::GUI::Tab::m_search_input protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_search_item
StaticBox* Slic3r::GUI::Tab::m_search_item protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_select_sizer
wxBoxSizer* Slic3r::GUI::Tab::m_select_sizer protected inherited
m_show_btn_incompatible_presets
bool Slic3r::GUI::Tab::m_show_btn_incompatible_presets = false inherited
Referenced by Slic3r::GUI::Tab::update_ui_from_settings().
m_show_incompatible_presets
bool Slic3r::GUI::Tab::m_show_incompatible_presets protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::Tab::toggle_show_hide_incompatible(), and Slic3r::GUI::Tab::update_ui_from_settings().
m_static_title
wxStaticText* Slic3r::GUI::Tab::m_static_title protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_sys_label_clr
wxColour Slic3r::GUI::Tab::m_sys_label_clr protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_tabctrl
TabCtrl* Slic3r::GUI::Tab::m_tabctrl protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::Tab::OnKeyDown(), Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::restore_last_select_item(), Slic3r::GUI::Tab::set_expanded(), Slic3r::GUI::Tab::tree_sel_change_delayed(), Slic3r::GUI::Tab::unselect_tree_item(), and Slic3r::GUI::Tab::update_current_page_in_background().
m_title
const wxString Slic3r::GUI::Tab::m_title protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab(), and Slic3r::GUI::Tab::title().
m_top_left_sizer
wxBoxSizer* Slic3r::GUI::Tab::m_top_left_sizer protected inherited
m_top_panel
wxPanel* Slic3r::GUI::Tab::m_top_panel protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_top_right_sizer
wxGridSizer* Slic3r::GUI::Tab::m_top_right_sizer protected inherited
m_top_sizer
wxBoxSizer* Slic3r::GUI::Tab::m_top_sizer protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_tree_sizer
wxBoxSizer* Slic3r::GUI::Tab::m_tree_sizer protected inherited
m_tt_non_system
wxString* Slic3r::GUI::Tab::m_tt_non_system protected inherited
Referenced by Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_tt_value_lock
wxString Slic3r::GUI::Tab::m_tt_value_lock protected inherited
m_tt_value_revert
wxString Slic3r::GUI::Tab::m_tt_value_revert protected inherited
Referenced by Slic3r::GUI::Tab::set_tooltips_text().
m_tt_value_unlock
wxString Slic3r::GUI::Tab::m_tt_value_unlock protected inherited
Referenced by Slic3r::GUI::Tab::set_tooltips_text(), and Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_tt_white_bullet
wxString Slic3r::GUI::Tab::m_tt_white_bullet protected inherited
m_ttg_non_system
wxString* Slic3r::GUI::Tab::m_ttg_non_system protected inherited
Referenced by Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_ttg_value_lock
wxString Slic3r::GUI::Tab::m_ttg_value_lock protected inherited
m_ttg_value_revert
wxString Slic3r::GUI::Tab::m_ttg_value_revert protected inherited
m_ttg_value_unlock
wxString Slic3r::GUI::Tab::m_ttg_value_unlock protected inherited
Referenced by Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_ttg_white_bullet
wxString Slic3r::GUI::Tab::m_ttg_white_bullet protected inherited
m_ttg_white_bullet_ns
wxString Slic3r::GUI::Tab::m_ttg_white_bullet_ns protected inherited
Referenced by Slic3r::GUI::Tab::update_ui_items_related_on_parent_preset().
m_type
Preset::Type Slic3r::GUI::Tab::m_type protected inherited
Referenced by Slic3r::GUI::Tab::compare_preset(), Slic3r::GUI::TabPrinter::create_bed_shape_widget(), Slic3r::GUI::Tab::create_preset_tab(), Slic3r::GUI::Tab::delete_preset(), Slic3r::GUI::Tab::load_current_preset(), Slic3r::GUI::Tab::may_discard_current_dirty_preset(), Slic3r::GUI::Tab::rebuild_page_tree(), Slic3r::GUI::Tab::save_preset(), Slic3r::GUI::Tab::select_preset(), Slic3r::GUI::Tab::set_type(), Slic3r::GUI::Tab::tree_sel_change_delayed(), Slic3r::GUI::Tab::type(), Slic3r::GUI::Tab::update_btns_enabling(), Slic3r::GUI::Tab::update_current_page_in_background(), Slic3r::GUI::Tab::update_ui_from_settings(), and Slic3r::GUI::Tab::validate_custom_gcodes().
m_undo_btn
ScalableButton* Slic3r::GUI::Tab::m_undo_btn protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_undo_to_sys_btn
ScalableButton* Slic3r::GUI::Tab::m_undo_to_sys_btn protected inherited
Referenced by Slic3r::GUI::Tab::create_preset_tab().
m_update_cnt
int Slic3r::GUI::Tab::m_update_cnt = 0 inherited
Referenced by update(), Slic3r::GUI::TabPrinter::update(), and Slic3r::GUI::TabSLAPrint::update().
m_volumetric_speed_description_line
ogStaticText* Slic3r::GUI::TabFilament::m_volumetric_speed_description_line {nullptr} private
Referenced by clear_pages().
validate_custom_gcodes_was_shown
bool Slic3r::GUI::Tab::validate_custom_gcodes_was_shown { false } inherited
Referenced by Slic3r::GUI::validate_custom_gcode_cb(), and Slic3r::GUI::Tab::validate_custom_gcodes().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Tab.hpp
src/slic3r/GUI/Tab.cpp