OrcaSlicer: BBLTopbar Class Reference
BBLTopbar Class Reference
#include <src/slic3r/GUI/BBLTopbar.hpp>
Public Member Functions
BBLTopbar (wxWindow *pwin, wxFrame *parent)
BBLTopbar (wxFrame *parent)
void Init (wxFrame *parent)
~BBLTopbar ()
void show_publish_button (bool show)
void UpdateToolbarWidth (int width)
void Rescale ()
void OnIconize (wxAuiToolBarEvent &event)
void OnFullScreen (wxAuiToolBarEvent &event)
void OnCloseFrame (wxAuiToolBarEvent &event)
void OnFileToolItem (wxAuiToolBarEvent &evt)
void OnDropdownToolItem (wxAuiToolBarEvent &evt)
void OnCalibToolItem (wxAuiToolBarEvent &evt)
void OnMouseLeftDClock (wxMouseEvent &mouse)
void OnMouseLeftDown (wxMouseEvent &event)
void OnMouseLeftUp (wxMouseEvent &event)
void OnMouseMotion (wxMouseEvent &event)
void OnMouseCaptureLost (wxMouseCaptureLostEvent &event)
void OnMenuClose (wxMenuEvent &event)
void OnOpenProject (wxAuiToolBarEvent &event)
void OnSaveProject (wxAuiToolBarEvent &event)
void OnUndo (wxAuiToolBarEvent &event)
void OnRedo (wxAuiToolBarEvent &event)
void OnModelStoreClicked (wxAuiToolBarEvent &event)
void OnPublishClicked (wxAuiToolBarEvent &event)
wxAuiToolBarItem * FindToolByCurrentPosition ()
void SetFileMenu (wxMenu *file_menu)
void AddDropDownSubMenu (wxMenu *sub_menu, const wxString &title)
void AddDropDownMenuItem (wxMenuItem *menu_item)
wxMenu * GetTopMenu ()
wxMenu * GetCalibMenu ()
void SetTitle (wxString title)
void SetMaximizedSize ()
void SetWindowSize ()
void Enable3DEditorItems ()
void Disable3DEditorItems ()
void SaveNormalRect ()
Private Attributes
wxFrame * m_frame
wxAuiToolBarItem * m_file_menu_item
wxAuiToolBarItem * m_dropdown_menu_item
wxRect m_normalRect
wxPoint m_delta
wxMenu m_top_menu
wxMenu * m_file_menu
wxMenu m_calib_menu
wxAuiToolBarItem * m_title_item
wxAuiToolBarItem * m_account_item
wxAuiToolBarItem * m_model_store_item
wxAuiToolBarItem * m_publish_item
wxAuiToolBarItem * m_undo_item
wxAuiToolBarItem * m_redo_item
wxAuiToolBarItem * m_calib_item
wxAuiToolBarItem * maximize_btn
wxBitmap m_publish_bitmap
wxBitmap m_publish_disable_bitmap
wxBitmap maximize_bitmap
wxBitmap window_bitmap
int m_toolbar_h
bool m_skip_popup_file_menu
bool m_skip_popup_dropdown_menu
bool m_skip_popup_calib_menu
Detailed Description
Constructor & Destructor Documentation
BBLTopbar() [1/2]
BBLTopbar::BBLTopbar (wxWindow * pwin, wxFrame * parent)
    : wxAuiToolBar(pwin, ID_TOOL_BAR, wxDefaultPosition, wxDefaultSize, wxAUI_TB_TEXT | wxAUI_TB_HORZ_TEXT)
{
    Init(parent);
}
References Init().
BBLTopbar() [2/2]
BBLTopbar::BBLTopbar (wxFrame * parent)
    : wxAuiToolBar(parent, ID_TOOL_BAR, wxDefaultPosition, wxDefaultSize, wxAUI_TB_TEXT | wxAUI_TB_HORZ_TEXT)
{
    Init(parent);
}
References Init().
~BBLTopbar()
BBLTopbar::~BBLTopbar ()
{
    m_file_menu_item = nullptr;
    m_dropdown_menu_item = nullptr;
    m_file_menu = nullptr;
}
References m_dropdown_menu_item, m_file_menu, and m_file_menu_item.
Member Function Documentation
AddDropDownMenuItem()
void BBLTopbar::AddDropDownMenuItem (wxMenuItem * menu_item)
{
    m_top_menu.Append(menu_item);
}
References m_top_menu.
AddDropDownSubMenu()
void BBLTopbar::AddDropDownSubMenu (wxMenu * sub_menu, const wxString & title)
{
    m_top_menu.AppendSubMenu(sub_menu, title);
}
References m_top_menu.
Disable3DEditorItems()
void BBLTopbar::Disable3DEditorItems ()
{
    this->EnableTool(m_undo_item->GetId(), false);
    this->EnableTool(m_redo_item->GetId(), false);
    this->EnableTool(m_calib_item->GetId(), false);
    Refresh();
}
References m_calib_item, m_redo_item, and m_undo_item.
Enable3DEditorItems()
void BBLTopbar::Enable3DEditorItems ()
{
    this->EnableTool(m_undo_item->GetId(), true);
    this->EnableTool(m_redo_item->GetId(), true);
    this->EnableTool(m_calib_item->GetId(), true);
    Refresh();
}
References m_calib_item, m_redo_item, and m_undo_item.
FindToolByCurrentPosition()
wxAuiToolBarItem * BBLTopbar::FindToolByCurrentPosition ()
{
    wxPoint mouse_pos = ::wxGetMousePosition();
    wxPoint client_pos = this->ScreenToClient(mouse_pos);
    return this->FindToolByPosition(client_pos.x, client_pos.y);
}
Referenced by OnMenuClose(), OnMouseLeftDClock(), and OnMouseLeftDown().
GetCalibMenu()
wxMenu * BBLTopbar::GetCalibMenu ()
{
    return &m_calib_menu;
}
References m_calib_menu.
GetTopMenu()
wxMenu * BBLTopbar::GetTopMenu ()
{
    return &m_top_menu;
}
References m_top_menu.
Init()
void BBLTopbar::Init (wxFrame * parent)
{
    SetArtProvider(new BBLTopbarArt());
    m_frame = parent;
    m_skip_popup_file_menu = false;
    m_skip_popup_dropdown_menu = false;
    m_skip_popup_calib_menu = false;
    wxInitAllImageHandlers();
    this->AddSpacer(5);
    /*wxBitmap logo_bitmap = create_scaled_bitmap("topbar_logo", nullptr, TOPBAR_ICON_SIZE);
    wxAuiToolBarItem* logo_item = this->AddTool(ID_LOGO, "", logo_bitmap);
    logo_item->SetHoverBitmap(logo_bitmap);
    logo_item->SetActive(false);*/
    wxBitmap file_bitmap = create_scaled_bitmap("topbar_file", nullptr, TOPBAR_ICON_SIZE);
    m_file_menu_item = this->AddTool(ID_TOP_FILE_MENU, _L("File"), file_bitmap, wxEmptyString, wxITEM_NORMAL);
    this->SetForegroundColour(wxSystemSettings::GetColour(wxSYS_COLOUR_HIGHLIGHTTEXT));
    this->AddSpacer(FromDIP(5));
    wxBitmap dropdown_bitmap = create_scaled_bitmap("topbar_dropdown", nullptr, TOPBAR_ICON_SIZE);
    m_dropdown_menu_item = this->AddTool(ID_TOP_DROPDOWN_MENU, "",
        dropdown_bitmap, wxEmptyString);
    this->AddSpacer(FromDIP(5));
    this->AddSeparator();
    this->AddSpacer(FromDIP(5));
    //wxBitmap open_bitmap = create_scaled_bitmap("topbar_open", nullptr, TOPBAR_ICON_SIZE);
    //wxAuiToolBarItem* tool_item = this->AddTool(wxID_OPEN, "", open_bitmap);
    this->AddSpacer(FromDIP(10));
    wxBitmap save_bitmap = create_scaled_bitmap("topbar_save", nullptr, TOPBAR_ICON_SIZE);
    wxAuiToolBarItem* save_btn = this->AddTool(wxID_SAVE, "", save_bitmap);
    this->AddSpacer(FromDIP(10));
    wxBitmap undo_bitmap = create_scaled_bitmap("topbar_undo", nullptr, TOPBAR_ICON_SIZE);
    m_undo_item = this->AddTool(wxID_UNDO, "", undo_bitmap);
    wxBitmap undo_inactive_bitmap = create_scaled_bitmap("topbar_undo_inactive", nullptr, TOPBAR_ICON_SIZE);
    m_undo_item->SetDisabledBitmap(undo_inactive_bitmap);
    this->AddSpacer(FromDIP(10));
    wxBitmap redo_bitmap = create_scaled_bitmap("topbar_redo", nullptr, TOPBAR_ICON_SIZE);
    m_redo_item = this->AddTool(wxID_REDO, "", redo_bitmap);
    wxBitmap redo_inactive_bitmap = create_scaled_bitmap("topbar_redo_inactive", nullptr, TOPBAR_ICON_SIZE);
    m_redo_item->SetDisabledBitmap(redo_inactive_bitmap);
    this->AddSpacer(FromDIP(10));
    wxBitmap calib_bitmap = create_scaled_bitmap("calib_sf", nullptr, TOPBAR_ICON_SIZE);
    wxBitmap calib_bitmap_inactive = create_scaled_bitmap("calib_sf_inactive", nullptr, TOPBAR_ICON_SIZE);
    m_calib_item = this->AddTool(ID_CALIB, _L("Calibration"), calib_bitmap);
    m_calib_item->SetDisabledBitmap(calib_bitmap_inactive);
    this->AddSpacer(FromDIP(10));
    this->AddStretchSpacer(1);
    m_title_item = this->AddLabel(ID_TITLE, "", FromDIP(TOPBAR_TITLE_WIDTH));
    m_title_item->SetAlignment(wxALIGN_CENTRE);
    this->AddSpacer(FromDIP(10));
    this->AddStretchSpacer(1);
    m_publish_bitmap = create_scaled_bitmap("topbar_publish", nullptr, TOPBAR_ICON_SIZE);
    m_publish_item = this->AddTool(ID_PUBLISH, "", m_publish_bitmap);
    m_publish_disable_bitmap = create_scaled_bitmap("topbar_publish_disable", nullptr, TOPBAR_ICON_SIZE);
    m_publish_item->SetDisabledBitmap(m_publish_disable_bitmap);
    this->EnableTool(m_publish_item->GetId(), false);
    this->AddSpacer(FromDIP(4));
    /*wxBitmap model_store_bitmap = create_scaled_bitmap("topbar_store", nullptr, TOPBAR_ICON_SIZE);
    m_model_store_item = this->AddTool(ID_MODEL_STORE, "", model_store_bitmap);
    this->AddSpacer(12);
    */
    //this->AddSeparator();
    this->AddSpacer(FromDIP(4));
    wxBitmap iconize_bitmap = create_scaled_bitmap("topbar_min", nullptr, TOPBAR_ICON_SIZE);
    wxAuiToolBarItem* iconize_btn = this->AddTool(wxID_ICONIZE_FRAME, "", iconize_bitmap);
    this->AddSpacer(FromDIP(4));
    maximize_bitmap = create_scaled_bitmap("topbar_max", nullptr, TOPBAR_ICON_SIZE);
    window_bitmap = create_scaled_bitmap("topbar_win", nullptr, TOPBAR_ICON_SIZE);
    if (m_frame->IsMaximized()) {
        maximize_btn = this->AddTool(wxID_MAXIMIZE_FRAME, "", window_bitmap);
    }
    else {
        maximize_btn = this->AddTool(wxID_MAXIMIZE_FRAME, "", maximize_bitmap);
    }
    this->AddSpacer(FromDIP(4));
    wxBitmap close_bitmap = create_scaled_bitmap("topbar_close", nullptr, TOPBAR_ICON_SIZE);
    wxAuiToolBarItem* close_btn = this->AddTool(wxID_CLOSE_FRAME, "", close_bitmap);
    Realize();
    // m_toolbar_h = this->GetSize().GetHeight();
    m_toolbar_h = FromDIP(30);
    int client_w = parent->GetClientSize().GetWidth();
    this->SetSize(client_w, m_toolbar_h);
    this->Bind(wxEVT_MOTION, &BBLTopbar::OnMouseMotion, this);
    this->Bind(wxEVT_MOUSE_CAPTURE_LOST, &BBLTopbar::OnMouseCaptureLost, this);
    this->Bind(wxEVT_MENU_CLOSE, &BBLTopbar::OnMenuClose, this);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnFileToolItem, this, ID_TOP_FILE_MENU);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnDropdownToolItem, this, ID_TOP_DROPDOWN_MENU);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnCalibToolItem, this, ID_CALIB);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnIconize, this, wxID_ICONIZE_FRAME);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnFullScreen, this, wxID_MAXIMIZE_FRAME);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnCloseFrame, this, wxID_CLOSE_FRAME);
    this->Bind(wxEVT_LEFT_DCLICK, &BBLTopbar::OnMouseLeftDClock, this);
    this->Bind(wxEVT_LEFT_DOWN, &BBLTopbar::OnMouseLeftDown, this);
    this->Bind(wxEVT_LEFT_UP, &BBLTopbar::OnMouseLeftUp, this);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnOpenProject, this, wxID_OPEN);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnSaveProject, this, wxID_SAVE);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnRedo, this, wxID_REDO);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnUndo, this, wxID_UNDO);
    //this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnModelStoreClicked, this, ID_MODEL_STORE);
    this->Bind(wxEVT_AUITOOLBAR_TOOL_DROPDOWN, &BBLTopbar::OnPublishClicked, this, ID_PUBLISH);
}
References _L, create_scaled_bitmap(), ID_CALIB, ID_PUBLISH, ID_TITLE, ID_TOP_DROPDOWN_MENU, ID_TOP_FILE_MENU, m_calib_item, m_dropdown_menu_item, m_file_menu_item, m_frame, m_publish_bitmap, m_publish_disable_bitmap, m_publish_item, m_redo_item, m_skip_popup_calib_menu, m_skip_popup_dropdown_menu, m_skip_popup_file_menu, m_title_item, m_toolbar_h, m_undo_item, maximize_bitmap, maximize_btn, OnCalibToolItem(), OnCloseFrame(), OnDropdownToolItem(), OnFileToolItem(), OnFullScreen(), OnIconize(), OnMenuClose(), OnMouseCaptureLost(), OnMouseLeftDClock(), OnMouseLeftDown(), OnMouseLeftUp(), OnMouseMotion(), OnOpenProject(), OnPublishClicked(), OnRedo(), OnSaveProject(), OnUndo(), TOPBAR_ICON_SIZE, TOPBAR_TITLE_WIDTH, and window_bitmap.
Referenced by BBLTopbar(), and BBLTopbar().
OnCalibToolItem()
void BBLTopbar::OnCalibToolItem (wxAuiToolBarEvent & evt)
{
    wxAuiToolBar* tb = static_cast<wxAuiToolBar*>(evt.GetEventObject());
    tb->SetToolSticky(evt.GetId(), true);
    if (!m_skip_popup_calib_menu) {
        auto rec = this->GetToolRect(ID_CALIB);
        PopupMenu(&m_calib_menu, wxPoint(rec.GetLeft(), this->GetSize().GetHeight() - 2));
    }
    else {
        m_skip_popup_calib_menu = false;
    }
    // make sure the button is "un-stuck"
    tb->SetToolSticky(evt.GetId(), false);
}
References ID_CALIB, m_calib_menu, and m_skip_popup_calib_menu.
Referenced by Init().
OnCloseFrame()
void BBLTopbar::OnCloseFrame (wxAuiToolBarEvent & event)
{
    m_frame->Close();
}
References m_frame.
Referenced by Init().
OnDropdownToolItem()
void BBLTopbar::OnDropdownToolItem (wxAuiToolBarEvent & evt)
{
    wxAuiToolBar* tb = static_cast<wxAuiToolBar*>(evt.GetEventObject());
    tb->SetToolSticky(evt.GetId(), true);
    if (!m_skip_popup_dropdown_menu) {
        PopupMenu(&m_top_menu, wxPoint(FromDIP(1), this->GetSize().GetHeight() - 2));
    }
    else {
        m_skip_popup_dropdown_menu = false;
    }
    // make sure the button is "un-stuck"
    tb->SetToolSticky(evt.GetId(), false);
}
References m_skip_popup_dropdown_menu, and m_top_menu.
Referenced by Init().
OnFileToolItem()
void BBLTopbar::OnFileToolItem (wxAuiToolBarEvent & evt)
{
    wxAuiToolBar* tb = static_cast<wxAuiToolBar*>(evt.GetEventObject());
    tb->SetToolSticky(evt.GetId(), true);
    if (!m_skip_popup_file_menu) {
        this->PopupMenu(m_file_menu, wxPoint(FromDIP(1), this->GetSize().GetHeight() - 2));
    }
    else {
        m_skip_popup_file_menu = false;
    }
    // make sure the button is "un-stuck"
    tb->SetToolSticky(evt.GetId(), false);
}
References m_file_menu, and m_skip_popup_file_menu.
Referenced by Init().
OnFullScreen()
void BBLTopbar::OnFullScreen (wxAuiToolBarEvent & event)
{
    if (m_frame->IsMaximized()) {
        m_frame->Restore();
    }
    else {
        wxDisplay display(this);
        auto      size = display.GetClientArea().GetSize();
#ifdef __WXMSW__
        HWND hWnd = m_frame->GetHandle();
        RECT      borderThickness;
        SetRectEmpty(&borderThickness);
        AdjustWindowRectEx(&borderThickness, GetWindowLongPtr(hWnd, GWL_STYLE), FALSE, 0);
        m_frame->SetMaxSize(size + wxSize{-borderThickness.left + borderThickness.right, -borderThickness.top + borderThickness.bottom});
#endif //  __WXMSW__
        m_normalRect = m_frame->GetRect();
        m_frame->Maximize();
    }
}
References FALSE, m_frame, m_normalRect, and size.
Referenced by Init(), and OnMouseLeftDClock().
OnIconize()
void BBLTopbar::OnIconize (wxAuiToolBarEvent & event)
{
    m_frame->Iconize();
}
References m_frame.
Referenced by Init().
OnMenuClose()
void BBLTopbar::OnMenuClose (wxMenuEvent & event)
{
    wxAuiToolBarItem* item = this->FindToolByCurrentPosition();
    if (item == m_file_menu_item) {
        m_skip_popup_file_menu = true;
    }
    else if (item == m_dropdown_menu_item) {
        m_skip_popup_dropdown_menu = true;
    }
}
References FindToolByCurrentPosition(), m_dropdown_menu_item, m_file_menu_item, m_skip_popup_dropdown_menu, and m_skip_popup_file_menu.
Referenced by Init().
OnModelStoreClicked()
void BBLTopbar::OnModelStoreClicked (wxAuiToolBarEvent & event)
{
    //GUI::wxGetApp().load_url(wxString(wxGetApp().app_config->get_web_host_url() + MODEL_STORE_URL));
}
OnMouseCaptureLost()
void BBLTopbar::OnMouseCaptureLost (wxMouseCaptureLostEvent & event)
{
}
Referenced by Init().
OnMouseLeftDClock()
void BBLTopbar::OnMouseLeftDClock (wxMouseEvent & mouse)
{
    wxPoint mouse_pos = ::wxGetMousePosition();
    // check whether mouse is not on any tool item
    if (this->FindToolByCurrentPosition() != NULL &&
        this->FindToolByCurrentPosition() != m_title_item) {
        mouse.Skip();
        return;
    }
#ifdef __W1XMSW__
    ::PostMessage((HWND) m_frame->GetHandle(), WM_NCLBUTTONDBLCLK, HTCAPTION, MAKELPARAM(mouse_pos.x, mouse_pos.y));
    return;
#endif //  __WXMSW__
    wxAuiToolBarEvent evt;
    OnFullScreen(evt);
}
References FindToolByCurrentPosition(), m_frame, m_title_item, NULL, and OnFullScreen().
Referenced by Init().
OnMouseLeftDown()
void BBLTopbar::OnMouseLeftDown (wxMouseEvent & event)
{
    wxPoint mouse_pos = ::wxGetMousePosition();
    wxPoint frame_pos = m_frame->GetScreenPosition();
    m_delta = mouse_pos - frame_pos;
    if (FindToolByCurrentPosition() == NULL
        || this->FindToolByCurrentPosition() == m_title_item)
    {
        CaptureMouse();
#ifdef __WXMSW__
        ReleaseMouse();
        ::PostMessage((HWND) m_frame->GetHandle(), WM_NCLBUTTONDOWN, HTCAPTION, MAKELPARAM(mouse_pos.x, mouse_pos.y));
        return;
#endif //  __WXMSW__
    }
    event.Skip();
}
References FindToolByCurrentPosition(), m_delta, m_frame, m_title_item, and NULL.
Referenced by Init().
OnMouseLeftUp()
void BBLTopbar::OnMouseLeftUp (wxMouseEvent & event)
{
    wxPoint mouse_pos = ::wxGetMousePosition();
    if (HasCapture())
    {
        ReleaseMouse();
    }
    event.Skip();
}
Referenced by Init().
OnMouseMotion()
void BBLTopbar::OnMouseMotion (wxMouseEvent & event)
{
    wxPoint mouse_pos = ::wxGetMousePosition();
    if (!HasCapture()) {
        //m_frame->OnMouseMotion(event);
        event.Skip();
        return;
    }
    if (event.Dragging() && event.LeftIsDown())
    {
        // leave max state and adjust position
        if (m_frame->IsMaximized()) {
            wxRect rect = m_frame->GetRect();
            // Filter unexcept mouse move
            if (m_delta + rect.GetLeftTop() != mouse_pos) {
                m_delta = mouse_pos - rect.GetLeftTop();
                m_delta.x = m_delta.x * m_normalRect.width / rect.width;
                m_delta.y = m_delta.y * m_normalRect.height / rect.height;
                m_frame->Restore();
            }
        }
        m_frame->Move(mouse_pos - m_delta);
    }
    event.Skip();
}
References m_delta, m_frame, and m_normalRect.
Referenced by Init().
OnOpenProject()
void BBLTopbar::OnOpenProject (wxAuiToolBarEvent & event)
{
    MainFrame* main_frame = dynamic_cast<MainFrame*>(m_frame);
    Plater* plater = main_frame->plater();
    plater->load_project();
}
References Slic3r::GUI::Plater::load_project(), m_frame, Slic3r::GUI::plater(), and Slic3r::GUI::MainFrame::plater().
Referenced by Init().
OnPublishClicked()
void BBLTopbar::OnPublishClicked (wxAuiToolBarEvent & event)
{
    if (!wxGetApp().getAgent()) {
        BOOST_LOG_TRIVIAL(info) << "publish: no agent";
        return;
    }
    //no more check
    //if (GUI::wxGetApp().plater()->model().objects.empty()) return;
    if (!wxGetApp().check_login())
        return;
#ifdef ENABLE_PUBLISHING
    wxGetApp().plater()->show_publish_dialog();
#endif
    wxGetApp().open_publish_page_dialog();
}
Referenced by Init().
OnRedo()
void BBLTopbar::OnRedo (wxAuiToolBarEvent & event)
{
    MainFrame* main_frame = dynamic_cast<MainFrame*>(m_frame);
    Plater* plater = main_frame->plater();
    plater->redo();
}
References m_frame, Slic3r::GUI::plater(), Slic3r::GUI::MainFrame::plater(), and Slic3r::GUI::Plater::redo().
Referenced by Init().
OnSaveProject()
void BBLTopbar::OnSaveProject (wxAuiToolBarEvent & event)
{
    MainFrame* main_frame = dynamic_cast<MainFrame*>(m_frame);
    Plater* plater = main_frame->plater();
    plater->save_project();
}
References m_frame, Slic3r::GUI::plater(), Slic3r::GUI::MainFrame::plater(), and Slic3r::GUI::Plater::save_project().
Referenced by Init().
OnUndo()
void BBLTopbar::OnUndo (wxAuiToolBarEvent & event)
{
    MainFrame* main_frame = dynamic_cast<MainFrame*>(m_frame);
    Plater* plater = main_frame->plater();
    plater->undo();
}
References m_frame, Slic3r::GUI::plater(), Slic3r::GUI::MainFrame::plater(), and Slic3r::GUI::Plater::undo().
Referenced by Init().
Rescale()
void BBLTopbar::Rescale ()
{
    int em = em_unit(this);
    wxAuiToolBarItem* item;
    /*item = this->FindTool(ID_LOGO);
    item->SetBitmap(create_scaled_bitmap("topbar_logo", nullptr, TOPBAR_ICON_SIZE));*/
    item = this->FindTool(ID_TOP_FILE_MENU);
    item->SetBitmap(create_scaled_bitmap("topbar_file", this, TOPBAR_ICON_SIZE));
    item = this->FindTool(ID_TOP_DROPDOWN_MENU);
    item->SetBitmap(create_scaled_bitmap("topbar_dropdown", this, TOPBAR_ICON_SIZE));
    //item = this->FindTool(wxID_OPEN);
    //item->SetBitmap(create_scaled_bitmap("topbar_open", nullptr, TOPBAR_ICON_SIZE));
    item = this->FindTool(wxID_SAVE);
    item->SetBitmap(create_scaled_bitmap("topbar_save", this, TOPBAR_ICON_SIZE));
    item = this->FindTool(wxID_UNDO);
    item->SetBitmap(create_scaled_bitmap("topbar_undo", this, TOPBAR_ICON_SIZE));
    item->SetDisabledBitmap(create_scaled_bitmap("topbar_undo_inactive", nullptr, TOPBAR_ICON_SIZE));
    item = this->FindTool(wxID_REDO);
    item->SetBitmap(create_scaled_bitmap("topbar_redo", this, TOPBAR_ICON_SIZE));
    item->SetDisabledBitmap(create_scaled_bitmap("topbar_redo_inactive", nullptr, TOPBAR_ICON_SIZE));
    item = this->FindTool(ID_CALIB);
    item->SetBitmap(create_scaled_bitmap("calib_sf", nullptr, TOPBAR_ICON_SIZE));
    item->SetDisabledBitmap(create_scaled_bitmap("calib_sf_inactive", nullptr, TOPBAR_ICON_SIZE));
    item = this->FindTool(ID_TITLE);
    /*item = this->FindTool(ID_PUBLISH);
    item->SetBitmap(create_scaled_bitmap("topbar_publish", this, TOPBAR_ICON_SIZE));
    item->SetDisabledBitmap(create_scaled_bitmap("topbar_publish_disable", nullptr, TOPBAR_ICON_SIZE));*/
    /*item = this->FindTool(ID_MODEL_STORE);
    item->SetBitmap(create_scaled_bitmap("topbar_store", this, TOPBAR_ICON_SIZE));
    */
    item = this->FindTool(wxID_ICONIZE_FRAME);
    item->SetBitmap(create_scaled_bitmap("topbar_min", this, TOPBAR_ICON_SIZE));
    item = this->FindTool(wxID_MAXIMIZE_FRAME);
    maximize_bitmap = create_scaled_bitmap("topbar_max", this, TOPBAR_ICON_SIZE);
    window_bitmap   = create_scaled_bitmap("topbar_win", this, TOPBAR_ICON_SIZE);
    if (m_frame->IsMaximized()) {
        item->SetBitmap(window_bitmap);
    }
    else {
        item->SetBitmap(maximize_bitmap);
    }
    item = this->FindTool(wxID_CLOSE_FRAME);
    item->SetBitmap(create_scaled_bitmap("topbar_close", this, TOPBAR_ICON_SIZE));
    Realize();
}
References create_scaled_bitmap(), em_unit(), ID_CALIB, ID_TITLE, ID_TOP_DROPDOWN_MENU, ID_TOP_FILE_MENU, m_frame, maximize_bitmap, TOPBAR_ICON_SIZE, and window_bitmap.
SaveNormalRect()
void BBLTopbar::SaveNormalRect ()
{
    m_normalRect = m_frame->GetRect();
}
References m_frame, and m_normalRect.
SetFileMenu()
void BBLTopbar::SetFileMenu (wxMenu * file_menu)
{
    m_file_menu = file_menu;
}
References m_file_menu.
SetMaximizedSize()
void BBLTopbar::SetMaximizedSize ()
{
    maximize_btn->SetBitmap(maximize_bitmap);
}
References maximize_bitmap, and maximize_btn.
Referenced by Slic3r::GUI::MainFrame::MainFrame().
SetTitle()
void BBLTopbar::SetTitle (wxString title)
{
    wxGCDC dc(this);
    title = wxControl::Ellipsize(title, dc, wxELLIPSIZE_END, FromDIP(TOPBAR_TITLE_WIDTH));
    m_title_item->SetLabel(title);
    m_title_item->SetAlignment(wxALIGN_CENTRE);
    this->Refresh();
}
References m_title_item, and TOPBAR_TITLE_WIDTH.
SetWindowSize()
void BBLTopbar::SetWindowSize ()
{
    maximize_btn->SetBitmap(window_bitmap);
}
References maximize_btn, and window_bitmap.
Referenced by Slic3r::GUI::MainFrame::MainFrame().
show_publish_button()
void BBLTopbar::show_publish_button (bool show)
{
    this->EnableTool(m_publish_item->GetId(), show);
    Refresh();
}
References m_publish_item.
Referenced by Slic3r::GUI::GUI_App::on_user_login_handle(), and Slic3r::GUI::GUI_App::recreate_GUI().
UpdateToolbarWidth()
void BBLTopbar::UpdateToolbarWidth (int width)
{
    this->SetSize(width, m_toolbar_h);
}
References m_toolbar_h.
Member Data Documentation
m_account_item
wxAuiToolBarItem* BBLTopbar::m_account_item private
m_calib_item
wxAuiToolBarItem* BBLTopbar::m_calib_item private
Referenced by Disable3DEditorItems(), Enable3DEditorItems(), and Init().
m_calib_menu
wxMenu BBLTopbar::m_calib_menu private
Referenced by GetCalibMenu(), and OnCalibToolItem().
m_delta
wxPoint BBLTopbar::m_delta private
Referenced by OnMouseLeftDown(), and OnMouseMotion().
m_dropdown_menu_item
wxAuiToolBarItem* BBLTopbar::m_dropdown_menu_item private
Referenced by ~BBLTopbar(), Init(), and OnMenuClose().
m_file_menu
wxMenu* BBLTopbar::m_file_menu private
Referenced by ~BBLTopbar(), OnFileToolItem(), and SetFileMenu().
m_file_menu_item
wxAuiToolBarItem* BBLTopbar::m_file_menu_item private
Referenced by ~BBLTopbar(), Init(), and OnMenuClose().
m_frame
wxFrame* BBLTopbar::m_frame private
Referenced by Init(), OnCloseFrame(), OnFullScreen(), OnIconize(), OnMouseLeftDClock(), OnMouseLeftDown(), OnMouseMotion(), OnOpenProject(), OnRedo(), OnSaveProject(), OnUndo(), Rescale(), and SaveNormalRect().
m_model_store_item
wxAuiToolBarItem* BBLTopbar::m_model_store_item private
m_normalRect
wxRect BBLTopbar::m_normalRect private
Referenced by OnFullScreen(), OnMouseMotion(), and SaveNormalRect().
m_publish_bitmap
wxBitmap BBLTopbar::m_publish_bitmap private
Referenced by Init().
m_publish_disable_bitmap
wxBitmap BBLTopbar::m_publish_disable_bitmap private
Referenced by Init().
m_publish_item
wxAuiToolBarItem* BBLTopbar::m_publish_item private
Referenced by Init(), and show_publish_button().
m_redo_item
wxAuiToolBarItem* BBLTopbar::m_redo_item private
Referenced by Disable3DEditorItems(), Enable3DEditorItems(), and Init().
m_skip_popup_calib_menu
bool BBLTopbar::m_skip_popup_calib_menu private
Referenced by Init(), and OnCalibToolItem().
m_skip_popup_dropdown_menu
bool BBLTopbar::m_skip_popup_dropdown_menu private
Referenced by Init(), OnDropdownToolItem(), and OnMenuClose().
m_skip_popup_file_menu
bool BBLTopbar::m_skip_popup_file_menu private
Referenced by Init(), OnFileToolItem(), and OnMenuClose().
m_title_item
wxAuiToolBarItem* BBLTopbar::m_title_item private
Referenced by Init(), OnMouseLeftDClock(), OnMouseLeftDown(), and SetTitle().
m_toolbar_h
int BBLTopbar::m_toolbar_h private
Referenced by Init(), and UpdateToolbarWidth().
m_top_menu
wxMenu BBLTopbar::m_top_menu private
Referenced by AddDropDownMenuItem(), AddDropDownSubMenu(), GetTopMenu(), and OnDropdownToolItem().
m_undo_item
wxAuiToolBarItem* BBLTopbar::m_undo_item private
Referenced by Disable3DEditorItems(), Enable3DEditorItems(), and Init().
maximize_bitmap
wxBitmap BBLTopbar::maximize_bitmap private
Referenced by Init(), Rescale(), and SetMaximizedSize().
maximize_btn
wxAuiToolBarItem* BBLTopbar::maximize_btn private
Referenced by Init(), SetMaximizedSize(), and SetWindowSize().
window_bitmap
wxBitmap BBLTopbar::window_bitmap private
Referenced by Init(), Rescale(), and SetWindowSize().
The documentation for this class was generated from the following files:
src/slic3r/GUI/BBLTopbar.hpp
src/slic3r/GUI/BBLTopbar.cpp