OrcaSlicer: Slic3r::GUI::IMTexture Class Reference
Slic3r::GUI::IMTexture Class Reference
#include <src/slic3r/GUI/ImGuiWrapper.hpp>
Static Public Member Functions
static bool load_from_svg_file (const std::string &filename, unsigned width, unsigned height, ImTextureID &texture_id)
Detailed Description
Member Function Documentation
load_from_svg_file()
bool Slic3r::GUI::IMTexture::load_from_svg_file (const std::string & filename, unsigned width, unsigned height, ImTextureID & texture_id) static
{
    NSVGimage* image = nsvgParseFromFile(filename.c_str(), "px", 96.0f);
    if (image == nullptr) {
        return false;
    }
    float scale = (float)width / std::max(image->width, image->height);
    int n_pixels = width * height;
    if (n_pixels <= 0) {
        nsvgDelete(image);
        return false;
    }
    NSVGrasterizer* rast = nsvgCreateRasterizer();
    if (rast == nullptr) {
        nsvgDelete(image);
        return false;
    }
    std::vector<unsigned char> data(n_pixels * 4, 0);
    nsvgRasterize(rast, image, 0, 0, scale, data.data(), width, height, width * 4);
    bool compress = false;
    GLint last_texture;
    unsigned m_image_texture{ 0 };
    unsigned char* pixels = (unsigned char*)(&data[0]);
    glsafe(::glGetIntegerv(GL_TEXTURE_BINDING_2D, &last_texture));
    glsafe(::glGenTextures(1, &m_image_texture));
    glsafe(::glBindTexture(GL_TEXTURE_2D, m_image_texture));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR));
    glsafe(::glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR));
    glsafe(::glPixelStorei(GL_UNPACK_ROW_LENGTH, 0));
    glsafe(::glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, pixels));
    // Store our identifier
    texture_id = (ImTextureID)(intptr_t)m_image_texture;
    // Restore state
    glsafe(::glBindTexture(GL_TEXTURE_2D, last_texture));
    nsvgDeleteRasterizer(rast);
    nsvgDelete(image);
    return true;
}
References compress, glsafe, NSVGimage::height, nsvgCreateRasterizer(), nsvgDelete(), nsvgDeleteRasterizer(), nsvgParseFromFile(), nsvgRasterize(), scale(), and NSVGimage::width.
Referenced by Slic3r::GUI::IMSlider::init_texture().
The documentation for this class was generated from the following files:
src/slic3r/GUI/ImGuiWrapper.hpp
src/slic3r/GUI/ImGuiWrapper.cpp