OrcaSlicer: src/qhull/src/libqhull/stat.h File Reference
stat.h File Reference
#include "libqhull.h"
Classes
union intrealT
struct qhstatT
Macros
#define MAYdebugx
#define zzdef_(stype, name, string, cnt)
#define zdef_(type, name, doc, count)
#define zzinc_(id) {MAYdebugx; qhstat stats[id].i++;}
#define zinc_(id) {}
#define zzadd_(id, val) {MAYdebugx; qhstat stats[id].i += (val);}
#define wwadd_(id, val) {MAYdebugx; qhstat stats[id].r += (val);}
#define zadd_(id, val) {}
#define wadd_(id, val) {}
#define zzval_(id) ((qhstat stats[id]).i)
#define wwval_(id) ((qhstat stats[id]).r)
#define zval_(id) qhstat tempi
#define wval_(id) qhstat tempr
#define wwmax_(id, val) {MAYdebugx; maximize_(qhstat stats[id].r,(val));}
#define zmax_(id, val) {}
#define wmax_(id, val) {}
#define zmin_(id, val) {}
#define wmin_(id, val) {}
#define qhstat qh_qhstat.
Typedefs
typedef union intrealT intrealT
Enumerations
enum qh_statistics {
Zback0 , Zbestdist , Zcentrumtests , Zcheckpart ,
Zconcaveridges , Zcoplanarhorizon , Zcoplanarpart , Zcoplanarridges ,
Zcyclefacettot , Zcyclehorizon , Zdelvertextot , Zdistcheck ,
Zdistconvex , Zdistzero , Zdoc1 , Zdoc2 ,
Zdoc3 , Zdoc11 , Zflippedfacets , Zgauss0 ,
Zminnorm , Zmultiridge , Znearlysingular , Wnewvertexmax ,
Znumvisibility , Zpartcoplanar , Zpartition , Zpartitionall ,
Zprocessed , Zretry , Zridge , Wridge ,
Wridgemax , Zridge0 , Wridge0 , Wridge0max ,
Zridgemid , Wridgemid , Wridgemidmax , Zridgeok ,
Wridgeok , Wridgeokmax , Zsetplane , Ztotcheck ,
Ztotmerge , ZEND
}
enum ztypes {
zdoc , zinc , zadd , zmax ,
zmin , ZTYPEreal , wadd , wmax ,
wmin , ZTYPEend
}
Functions
void qh_allstatA (void)
void qh_allstatB (void)
void qh_allstatC (void)
void qh_allstatD (void)
void qh_allstatE (void)
void qh_allstatE2 (void)
void qh_allstatF (void)
void qh_allstatG (void)
void qh_allstatH (void)
void qh_allstatI (void)
void qh_allstatistics (void)
void qh_collectstatistics (void)
void qh_freestatistics (void)
void qh_initstatistics (void)
boolT qh_newstats (int idx, int *nextindex)
boolT qh_nostatistic (int i)
void qh_printallstatistics (FILE *fp, const char *string)
void qh_printstatistics (FILE *fp, const char *string)
void qh_printstatlevel (FILE *fp, int id)
void qh_printstats (FILE *fp, int idx, int *nextindex)
realT qh_stddev (int num, realT tot, realT tot2, realT *ave)
Variables
qhstatT qh_qhstat
Class Documentation
intrealT
union intrealT
Class Members
int i
realT r
Macro Definition Documentation
MAYdebugx
#define MAYdebugx
qhstat
#define qhstat qh_qhstat.
wadd_
#define wadd_ (id, val) {}
wmax_
#define wmax_ (id, val) {}
wmin_
#define wmin_ (id, val) {}
wval_
#define wval_ (id) qhstat tempr
wwadd_
#define wwadd_ (id, val) {MAYdebugx; qhstat stats[id].r += (val);}
wwmax_
#define wwmax_ (id, val) {MAYdebugx; maximize_(qhstat stats[id].r,(val));}
wwval_
#define wwval_ (id) ((qhstat stats[id]).r)
zadd_
#define zadd_ (id, val) {}
zdef_
#define zdef_ (type, name, doc, count)
zinc_
#define zinc_ (id) {}
zmax_
#define zmax_ (id, val) {}
zmin_
#define zmin_ (id, val) {}
zval_
#define zval_ (id) qhstat tempi
zzadd_
#define zzadd_ (id, val) {MAYdebugx; qhstat stats[id].i += (val);}
zzdef_
#define zzdef_ (stype, name, string, cnt)
Value:
   qhstat id[qhstat next++]=name; \
   qhstat doc[name]= string; qhstat count[name]= cnt; qhstat type[name]= stype
zzinc_
#define zzinc_ (id) {MAYdebugx; qhstat stats[id].i++;}
zzval_
#define zzval_ (id) ((qhstat stats[id]).i)
Typedef Documentation
intrealT
typedef union intrealT intrealT
Enumeration Type Documentation
qh_statistics
enum qh_statistics
Enumerator
Zback0
Zbestdist
Zcentrumtests
Zcheckpart
Zconcaveridges
Zcoplanarhorizon
Zcoplanarpart
Zcoplanarridges
Zcyclefacettot
Zcyclehorizon
Zdelvertextot
Zdistcheck
Zdistconvex
Zdistzero
Zdoc1
Zdoc2
Zdoc3
Zdoc11
Zflippedfacets
Zgauss0
Zminnorm
Zmultiridge
Znearlysingular
Wnewvertexmax
Znumvisibility
Zpartcoplanar
Zpartition
Zpartitionall
Zprocessed
Zretry
Zridge
Wridge
Wridgemax
Zridge0
Wridge0
Wridge0max
Zridgemid
Wridgemid
Wridgemidmax
Zridgeok
Wridgeok
Wridgeokmax
Zsetplane
Ztotcheck
Ztotmerge
ZEND
                   {     /* for zzdef etc. macros */
  Zback0,
  Zbestdist,
  Zcentrumtests,
  Zcheckpart,
  Zconcaveridges,
  Zcoplanarhorizon,
  Zcoplanarpart,
  Zcoplanarridges,
  Zcyclefacettot,
  Zcyclehorizon,
  Zdelvertextot,
  Zdistcheck,
  Zdistconvex,
  Zdistzero,
  Zdoc1,
  Zdoc2,
  Zdoc3,
  Zdoc11,
  Zflippedfacets,
  Zgauss0,
  Zminnorm,
  Zmultiridge,
  Znearlysingular,
  Wnewvertexmax,
  Znumvisibility,
  Zpartcoplanar,
  Zpartition,
  Zpartitionall,
  Zprocessed,
  Zretry,
  Zridge,
  Wridge,
  Wridgemax,
  Zridge0,
  Wridge0,
  Wridge0max,
  Zridgemid,
  Wridgemid,
  Wridgemidmax,
  Zridgeok,
  Wridgeok,
  Wridgeokmax,
  Zsetplane,
  Ztotcheck,
  Ztotmerge,
    ZEND};
ztypes
enum ztypes
Enumerator
zdoc
zinc
zadd
zmax
zmin
ZTYPEreal
wadd
wmax
wmin
ZTYPEend
{zdoc,zinc,zadd,zmax,zmin,ZTYPEreal,wadd,wmax,wmin,ZTYPEend};
Function Documentation
qh_allstatA()
void qh_allstatA (void)
                       {
   /* zdef_(type,name,doc,average) */
  zzdef_(zdoc, Zdoc2, "precision statistics", -1);
  zdef_(zinc, Znewvertex, NULL, -1);
  zdef_(wadd, Wnewvertex, "ave. distance of a new vertex to a facet(!0s)", Znewvertex);
  zzdef_(wmax, Wnewvertexmax, "max. distance of a new vertex to a facet", -1);
  zdef_(wmax, Wvertexmax, "max. distance of an output vertex to a facet", -1);
  zdef_(wmin, Wvertexmin, "min. distance of an output vertex to a facet", -1);
  zdef_(wmin, Wmindenom, "min. denominator in hyperplane computation", -1);
  qhstat precision= qhstat next;  /* call qh_precision for each of these */
  zzdef_(zdoc, Zdoc3, "precision problems (corrected unless 'Q0' or an error)", -1);
  zzdef_(zinc, Zcoplanarridges, "coplanar half ridges in output", -1);
  zzdef_(zinc, Zconcaveridges, "concave half ridges in output", -1);
  zzdef_(zinc, Zflippedfacets, "flipped facets", -1);
  zzdef_(zinc, Zcoplanarhorizon, "coplanar horizon facets for new vertices", -1);
  zzdef_(zinc, Zcoplanarpart, "coplanar points during partitioning", -1);
  zzdef_(zinc, Zminnorm, "degenerate hyperplanes recomputed with gaussian elimination", -1);
  zzdef_(zinc, Znearlysingular, "nearly singular or axis-parallel hyperplanes", -1);
  zzdef_(zinc, Zback0, "zero divisors during back substitute", -1);
  zzdef_(zinc, Zgauss0, "zero divisors during gaussian elimination", -1);
  zzdef_(zinc, Zmultiridge, "ridges with multiple neighbors", -1);
}
Referenced by qh_initstatistics().
qh_allstatB()
void qh_allstatB (void)
                       {
  zzdef_(zdoc, Zdoc1, "summary information", -1);
  zdef_(zinc, Zvertices, "number of vertices in output", -1);
  zdef_(zinc, Znumfacets, "number of facets in output", -1);
  zdef_(zinc, Znonsimplicial, "number of non-simplicial facets in output", -1);
  zdef_(zinc, Znowsimplicial, "number of simplicial facets that were merged", -1);
  zdef_(zinc, Znumridges, "number of ridges in output", -1);
  zdef_(zadd, Znumridges, "average number of ridges per facet", Znumfacets);
  zdef_(zmax, Zmaxridges, "maximum number of ridges", -1);
  zdef_(zadd, Znumneighbors, "average number of neighbors per facet", Znumfacets);
  zdef_(zmax, Zmaxneighbors, "maximum number of neighbors", -1);
  zdef_(zadd, Znumvertices, "average number of vertices per facet", Znumfacets);
  zdef_(zmax, Zmaxvertices, "maximum number of vertices", -1);
  zdef_(zadd, Znumvneighbors, "average number of neighbors per vertex", Zvertices);
  zdef_(zmax, Zmaxvneighbors, "maximum number of neighbors", -1);
  zdef_(wadd, Wcpu, "cpu seconds for qhull after input", -1);
  zdef_(zinc, Ztotvertices, "vertices created altogether", -1);
  zzdef_(zinc, Zsetplane, "facets created altogether", -1);
  zdef_(zinc, Ztotridges, "ridges created altogether", -1);
  zdef_(zinc, Zpostfacets, "facets before post merge", -1);
  zdef_(zadd, Znummergetot, "average merges per facet(at most 511)", Znumfacets);
  zdef_(zmax, Znummergemax, "  maximum merges for a facet(at most 511)", -1);
  zdef_(zinc, Zangle, NULL, -1);
  zdef_(wadd, Wangle, "average angle(cosine) of facet normals for all ridges", Zangle);
  zdef_(wmax, Wanglemax, "  maximum angle(cosine) of facet normals across a ridge", -1);
  zdef_(wmin, Wanglemin, "  minimum angle(cosine) of facet normals across a ridge", -1);
  zdef_(wadd, Wareatot, "total area of facets", -1);
  zdef_(wmax, Wareamax, "  maximum facet area", -1);
  zdef_(wmin, Wareamin, "  minimum facet area", -1);
}
Referenced by qh_initstatistics().
qh_allstatC()
void qh_allstatC (void)
                       {
  zdef_(zdoc, Zdoc9, "build hull statistics", -1);
  zzdef_(zinc, Zprocessed, "points processed", -1);
  zzdef_(zinc, Zretry, "retries due to precision problems", -1);
  zdef_(wmax, Wretrymax, "  max. random joggle", -1);
  zdef_(zmax, Zmaxvertex, "max. vertices at any one time", -1);
  zdef_(zinc, Ztotvisible, "ave. visible facets per iteration", Zprocessed);
  zdef_(zinc, Zinsidevisible, "  ave. visible facets without an horizon neighbor", Zprocessed);
  zdef_(zadd, Zvisfacettot,  "  ave. facets deleted per iteration", Zprocessed);
  zdef_(zmax, Zvisfacetmax,  "    maximum", -1);
  zdef_(zadd, Zvisvertextot, "ave. visible vertices per iteration", Zprocessed);
  zdef_(zmax, Zvisvertexmax, "    maximum", -1);
  zdef_(zinc, Ztothorizon, "ave. horizon facets per iteration", Zprocessed);
  zdef_(zadd, Znewfacettot,  "ave. new or merged facets per iteration", Zprocessed);
  zdef_(zmax, Znewfacetmax,  "    maximum(includes initial simplex)", -1);
  zdef_(wadd, Wnewbalance, "average new facet balance", Zprocessed);
  zdef_(wadd, Wnewbalance2, "  standard deviation", -1);
  zdef_(wadd, Wpbalance, "average partition balance", Zpbalance);
  zdef_(wadd, Wpbalance2, "  standard deviation", -1);
  zdef_(zinc, Zpbalance, "  number of trials", -1);
  zdef_(zinc, Zsearchpoints, "searches of all points for initial simplex", -1);
  zdef_(zinc, Zdetsimplex, "determinants computed(area & initial hull)", -1);
  zdef_(zinc, Znoarea, "determinants not computed because vertex too low", -1);
  zdef_(zinc, Znotmax, "points ignored(!above max_outside)", -1);
  zdef_(zinc, Znotgood, "points ignored(!above a good facet)", -1);
  zdef_(zinc, Znotgoodnew, "points ignored(didn't create a good new facet)", -1);
  zdef_(zinc, Zgoodfacet, "good facets found", -1);
  zzdef_(zinc, Znumvisibility, "distance tests for facet visibility", -1);
  zdef_(zinc, Zdistvertex, "distance tests to report minimum vertex", -1);
  zzdef_(zinc, Ztotcheck, "points checked for facets' outer planes", -1);
  zzdef_(zinc, Zcheckpart, "  ave. distance tests per check", Ztotcheck);
}
Referenced by qh_initstatistics().
qh_allstatD()
void qh_allstatD (void)
                       {
  zdef_(zinc, Zvisit, "resets of visit_id", -1);
  zdef_(zinc, Zvvisit, "  resets of vertex_visit", -1);
  zdef_(zmax, Zvisit2max, "  max visit_id/2", -1);
  zdef_(zmax, Zvvisit2max, "  max vertex_visit/2", -1);
  zdef_(zdoc, Zdoc4, "partitioning statistics(see previous for outer planes)", -1);
  zzdef_(zadd, Zdelvertextot, "total vertices deleted", -1);
  zdef_(zmax, Zdelvertexmax, "    maximum vertices deleted per iteration", -1);
  zdef_(zinc, Zfindbest, "calls to findbest", -1);
  zdef_(zadd, Zfindbesttot, " ave. facets tested", Zfindbest);
  zdef_(zmax, Zfindbestmax, " max. facets tested", -1);
  zdef_(zadd, Zfindcoplanar, " ave. coplanar search", Zfindbest);
  zdef_(zinc, Zfindnew, "calls to findbestnew", -1);
  zdef_(zadd, Zfindnewtot, " ave. facets tested", Zfindnew);
  zdef_(zmax, Zfindnewmax, " max. facets tested", -1);
  zdef_(zinc, Zfindnewjump, " ave. clearly better", Zfindnew);
  zdef_(zinc, Zfindnewsharp, " calls due to qh_sharpnewfacets", -1);
  zdef_(zinc, Zfindhorizon, "calls to findhorizon", -1);
  zdef_(zadd, Zfindhorizontot, " ave. facets tested", Zfindhorizon);
  zdef_(zmax, Zfindhorizonmax, " max. facets tested", -1);
  zdef_(zinc, Zfindjump,       " ave. clearly better", Zfindhorizon);
  zdef_(zinc, Zparthorizon, " horizon facets better than bestfacet", -1);
  zdef_(zinc, Zpartangle, "angle tests for repartitioned coplanar points", -1);
  zdef_(zinc, Zpartflip, "  repartitioned coplanar points for flipped orientation", -1);
}
Referenced by qh_initstatistics().
qh_allstatE()
void qh_allstatE (void)
                       {
  zdef_(zinc, Zpartinside, "inside points", -1);
  zdef_(zinc, Zpartnear, "  inside points kept with a facet", -1);
  zdef_(zinc, Zcoplanarinside, "  inside points that were coplanar with a facet", -1);
  zdef_(zinc, Zbestlower, "calls to findbestlower", -1);
  zdef_(zinc, Zbestlowerv, "  with search of vertex neighbors", -1);
  zdef_(zinc, Zbestlowerall, "  with rare search of all facets", -1);
  zdef_(zmax, Zbestloweralln, "  facets per search of all facets", -1);
  zdef_(wadd, Wmaxout, "difference in max_outside at final check", -1);
  zzdef_(zinc, Zpartitionall, "distance tests for initial partition", -1);
  zdef_(zinc, Ztotpartition, "partitions of a point", -1);
  zzdef_(zinc, Zpartition, "distance tests for partitioning", -1);
  zzdef_(zinc, Zdistcheck, "distance tests for checking flipped facets", -1);
  zzdef_(zinc, Zdistconvex, "distance tests for checking convexity", -1);
  zdef_(zinc, Zdistgood, "distance tests for checking good point", -1);
  zdef_(zinc, Zdistio, "distance tests for output", -1);
  zdef_(zinc, Zdiststat, "distance tests for statistics", -1);
  zdef_(zinc, Zdistplane, "total number of distance tests", -1);
  zdef_(zinc, Ztotpartcoplanar, "partitions of coplanar points or deleted vertices", -1);
  zzdef_(zinc, Zpartcoplanar, "   distance tests for these partitions", -1);
  zdef_(zinc, Zcomputefurthest, "distance tests for computing furthest", -1);
}
Referenced by qh_initstatistics().
qh_allstatE2()
void qh_allstatE2 (void)
{
  zdef_(zdoc, Zdoc5, "statistics for matching ridges", -1);
  zdef_(zinc, Zhashlookup, "total lookups for matching ridges of new facets", -1);
  zdef_(zinc, Zhashtests, "average number of tests to match a ridge", Zhashlookup);
  zdef_(zinc, Zhashridge, "total lookups of subridges(duplicates and boundary)", -1);
  zdef_(zinc, Zhashridgetest, "average number of tests per subridge", Zhashridge);
  zdef_(zinc, Zdupsame, "duplicated ridges in same merge cycle", -1);
  zdef_(zinc, Zdupflip, "duplicated ridges with flipped facets", -1);
  zdef_(zdoc, Zdoc6, "statistics for determining merges", -1);
  zdef_(zinc, Zangletests, "angles computed for ridge convexity", -1);
  zdef_(zinc, Zbestcentrum, "best merges used centrum instead of vertices",-1);
  zzdef_(zinc, Zbestdist, "distance tests for best merge", -1);
  zzdef_(zinc, Zcentrumtests, "distance tests for centrum convexity", -1);
  zzdef_(zinc, Zdistzero, "distance tests for checking simplicial convexity", -1);
  zdef_(zinc, Zcoplanarangle, "coplanar angles in getmergeset", -1);
  zdef_(zinc, Zcoplanarcentrum, "coplanar centrums in getmergeset", -1);
  zdef_(zinc, Zconcaveridge, "concave ridges in getmergeset", -1);
}
Referenced by qh_initstatistics().
qh_allstatF()
void qh_allstatF (void)
                       {
  zdef_(zdoc, Zdoc7, "statistics for merging", -1);
  zdef_(zinc, Zpremergetot, "merge iterations", -1);
  zdef_(zadd, Zmergeinittot, "ave. initial non-convex ridges per iteration", Zpremergetot);
  zdef_(zadd, Zmergeinitmax, "  maximum", -1);
  zdef_(zadd, Zmergesettot, "  ave. additional non-convex ridges per iteration", Zpremergetot);
  zdef_(zadd, Zmergesetmax, "  maximum additional in one pass", -1);
  zdef_(zadd, Zmergeinittot2, "initial non-convex ridges for post merging", -1);
  zdef_(zadd, Zmergesettot2, "  additional non-convex ridges", -1);
  zdef_(wmax, Wmaxoutside, "max distance of vertex or coplanar point above facet(w/roundoff)", -1);
  zdef_(wmin, Wminvertex, "max distance of merged vertex below facet(or roundoff)", -1);
  zdef_(zinc, Zwidefacet, "centrums frozen due to a wide merge", -1);
  zdef_(zinc, Zwidevertices, "centrums frozen due to extra vertices", -1);
  zzdef_(zinc, Ztotmerge, "total number of facets or cycles of facets merged", -1);
  zdef_(zinc, Zmergesimplex, "merged a simplex", -1);
  zdef_(zinc, Zonehorizon, "simplices merged into coplanar horizon", -1);
  zzdef_(zinc, Zcyclehorizon, "cycles of facets merged into coplanar horizon", -1);
  zzdef_(zadd, Zcyclefacettot, "  ave. facets per cycle", Zcyclehorizon);
  zdef_(zmax, Zcyclefacetmax, "  max. facets", -1);
  zdef_(zinc, Zmergeintohorizon, "new facets merged into horizon", -1);
  zdef_(zinc, Zmergenew, "new facets merged", -1);
  zdef_(zinc, Zmergehorizon, "horizon facets merged into new facets", -1);
  zdef_(zinc, Zmergevertex, "vertices deleted by merging", -1);
  zdef_(zinc, Zcyclevertex, "vertices deleted by merging into coplanar horizon", -1);
  zdef_(zinc, Zdegenvertex, "vertices deleted by degenerate facet", -1);
  zdef_(zinc, Zmergeflipdup, "merges due to flipped facets in duplicated ridge", -1);
  zdef_(zinc, Zneighbor, "merges due to redundant neighbors", -1);
  zdef_(zadd, Ztestvneighbor, "non-convex vertex neighbors", -1);
}
Referenced by qh_initstatistics().
qh_allstatG()
void qh_allstatG (void)
                       {
  zdef_(zinc, Zacoplanar, "merges due to angle coplanar facets", -1);
  zdef_(wadd, Wacoplanartot, "  average merge distance", Zacoplanar);
  zdef_(wmax, Wacoplanarmax, "  maximum merge distance", -1);
  zdef_(zinc, Zcoplanar, "merges due to coplanar facets", -1);
  zdef_(wadd, Wcoplanartot, "  average merge distance", Zcoplanar);
  zdef_(wmax, Wcoplanarmax, "  maximum merge distance", -1);
  zdef_(zinc, Zconcave, "merges due to concave facets", -1);
  zdef_(wadd, Wconcavetot, "  average merge distance", Zconcave);
  zdef_(wmax, Wconcavemax, "  maximum merge distance", -1);
  zdef_(zinc, Zavoidold, "coplanar/concave merges due to avoiding old merge", -1);
  zdef_(wadd, Wavoidoldtot, "  average merge distance", Zavoidold);
  zdef_(wmax, Wavoidoldmax, "  maximum merge distance", -1);
  zdef_(zinc, Zdegen, "merges due to degenerate facets", -1);
  zdef_(wadd, Wdegentot, "  average merge distance", Zdegen);
  zdef_(wmax, Wdegenmax, "  maximum merge distance", -1);
  zdef_(zinc, Zflipped, "merges due to removing flipped facets", -1);
  zdef_(wadd, Wflippedtot, "  average merge distance", Zflipped);
  zdef_(wmax, Wflippedmax, "  maximum merge distance", -1);
  zdef_(zinc, Zduplicate, "merges due to duplicated ridges", -1);
  zdef_(wadd, Wduplicatetot, "  average merge distance", Zduplicate);
  zdef_(wmax, Wduplicatemax, "  maximum merge distance", -1);
}
Referenced by qh_initstatistics().
qh_allstatH()
void qh_allstatH (void)
                       {
  zdef_(zdoc, Zdoc8, "renamed vertex statistics", -1);
  zdef_(zinc, Zrenameshare, "renamed vertices shared by two facets", -1);
  zdef_(zinc, Zrenamepinch, "renamed vertices in a pinched facet", -1);
  zdef_(zinc, Zrenameall, "renamed vertices shared by multiple facets", -1);
  zdef_(zinc, Zfindfail, "rename failures due to duplicated ridges", -1);
  zdef_(zinc, Zdupridge, "  duplicate ridges detected", -1);
  zdef_(zinc, Zdelridge, "deleted ridges due to renamed vertices", -1);
  zdef_(zinc, Zdropneighbor, "dropped neighbors due to renamed vertices", -1);
  zdef_(zinc, Zdropdegen, "degenerate facets due to dropped neighbors", -1);
  zdef_(zinc, Zdelfacetdup, "  facets deleted because of no neighbors", -1);
  zdef_(zinc, Zremvertex, "vertices removed from facets due to no ridges", -1);
  zdef_(zinc, Zremvertexdel, "  deleted", -1);
  zdef_(zinc, Zintersectnum, "vertex intersections for locating redundant vertices", -1);
  zdef_(zinc, Zintersectfail, "intersections failed to find a redundant vertex", -1);
  zdef_(zinc, Zintersect, "intersections found redundant vertices", -1);
  zdef_(zadd, Zintersecttot, "   ave. number found per vertex", Zintersect);
  zdef_(zmax, Zintersectmax, "   max. found for a vertex", -1);
  zdef_(zinc, Zvertexridge, NULL, -1);
  zdef_(zadd, Zvertexridgetot, "  ave. number of ridges per tested vertex", Zvertexridge);
  zdef_(zmax, Zvertexridgemax, "  max. number of ridges per tested vertex", -1);
  zdef_(zdoc, Zdoc10, "memory usage statistics(in bytes)", -1);
  zdef_(zadd, Zmemfacets, "for facets and their normals, neighbor and vertex sets", -1);
  zdef_(zadd, Zmemvertices, "for vertices and their neighbor sets", -1);
  zdef_(zadd, Zmempoints, "for input points and outside and coplanar sets",-1);
  zdef_(zadd, Zmemridges, "for ridges and their vertex sets", -1);
} /* allstat */
Referenced by qh_initstatistics().
qh_allstatI()
void qh_allstatI (void)
                       {
  qhstat vridges= qhstat next;
  zzdef_(zdoc, Zdoc11, "Voronoi ridge statistics", -1);
  zzdef_(zinc, Zridge, "non-simplicial Voronoi vertices for all ridges", -1);
  zzdef_(wadd, Wridge, "  ave. distance to ridge", Zridge);
  zzdef_(wmax, Wridgemax, "  max. distance to ridge", -1);
  zzdef_(zinc, Zridgemid, "bounded ridges", -1);
  zzdef_(wadd, Wridgemid, "  ave. distance of midpoint to ridge", Zridgemid);
  zzdef_(wmax, Wridgemidmax, "  max. distance of midpoint to ridge", -1);
  zzdef_(zinc, Zridgeok, "bounded ridges with ok normal", -1);
  zzdef_(wadd, Wridgeok, "  ave. angle to ridge", Zridgeok);
  zzdef_(wmax, Wridgeokmax, "  max. angle to ridge", -1);
  zzdef_(zinc, Zridge0, "bounded ridges with near-zero normal", -1);
  zzdef_(wadd, Wridge0, "  ave. angle to ridge", Zridge0);
  zzdef_(wmax, Wridge0max, "  max. angle to ridge", -1);
  zdef_(zdoc, Zdoc12, "Triangulation statistics(Qt)", -1);
  zdef_(zinc, Ztricoplanar, "non-simplicial facets triangulated", -1);
  zdef_(zadd, Ztricoplanartot, "  ave. new facets created(may be deleted)", Ztricoplanar);
  zdef_(zmax, Ztricoplanarmax, "  max. new facets created", -1);
  zdef_(zinc, Ztrinull, "null new facets deleted(duplicated vertex)", -1);
  zdef_(zinc, Ztrimirror, "mirrored pairs of new facets deleted(same vertices)", -1);
  zdef_(zinc, Ztridegen, "degenerate new facets in output(same ridge)", -1);
} /* allstat */
References qhstat, wadd, wmax, Wridge, Wridge0, Wridge0max, Wridgemax, Wridgemid, Wridgemidmax, Wridgeok, Wridgeokmax, zadd, zdef_, zdoc, Zdoc11, zinc, zmax, Zridge, Zridge0, Zridgemid, Zridgeok, and zzdef_.
Referenced by qh_initstatistics(), and qh_initstatistics().
qh_allstatistics()
void qh_allstatistics (void)
{
  int i;
  for(i=ZEND; i--; )
    qhstat printed[i]= False;
} /* allstatistics */
References False, qhstat, and ZEND.
Referenced by qh_produce_output2(), and qh_produce_output2().
qh_collectstatistics()
void qh_collectstatistics (void)
{}
qh_freestatistics()
void qh_freestatistics (void)
{
#if qh_QHpointer
  qh_free(qh_qhstat);
  qh_qhstat= NULL;
#endif
} /* freestatistics */
References NULL, qh_free(), and qh_qhstat.
Referenced by qh_freeqhull2().
qh_initstatistics()
void qh_initstatistics (void)
{
  int i;
  realT realx;
  int intx;
#if qh_QHpointer
  if(qh_qhstat){  /* qh_initstatistics may be called from Qhull::resetStatistics() */
      qh_free(qh_qhstat);
      qh_qhstat= 0;
  }
  if (!(qh_qhstat= (qhstatT *)qh_malloc(sizeof(qhstatT)))) {
    qh_fprintf_stderr(6183, "qhull error (qh_initstatistics): insufficient memory\n");
    qh_exit(qh_ERRmem);  /* can not use qh_errexit() */
  }
#endif
  qhstat next= 0;
  qh_allstatA();
  qh_allstatB();
  qh_allstatC();
  qh_allstatD();
  qh_allstatE();
  qh_allstatE2();
  qh_allstatF();
  qh_allstatG();
  qh_allstatH();
  qh_allstatI();
  if (qhstat next > (int)sizeof(qhstat id)) {
    qh_fprintf(qhmem.ferr, 6184, "qhull error (qh_initstatistics): increase size of qhstat.id[].\n\
      qhstat.next %d should be <= sizeof(qhstat id) %d\n", qhstat next, (int)sizeof(qhstat id));
#if 0 /* for locating error, Znumridges should be duplicated */
    for(i=0; i < ZEND; i++) {
      int j;
      for(j=i+1; j < ZEND; j++) {
        if (qhstat id[i] == qhstat id[j]) {
          qh_fprintf(qhmem.ferr, 6185, "qhull error (qh_initstatistics): duplicated statistic %d at indices %d and %d\n",
              qhstat id[i], i, j);
        }
      }
    }
#endif
    qh_exit(qh_ERRqhull);  /* can not use qh_errexit() */
  }
  qhstat init[zinc].i= 0;
  qhstat init[zadd].i= 0;
  qhstat init[zmin].i= INT_MAX;
  qhstat init[zmax].i= INT_MIN;
  qhstat init[wadd].r= 0;
  qhstat init[wmin].r= REALmax;
  qhstat init[wmax].r= -REALmax;
  for(i=0; i < ZEND; i++) {
    if (qhstat type[i] > ZTYPEreal) {
      realx= qhstat init[(unsigned char)(qhstat type[i])].r;
      qhstat stats[i].r= realx;
    }else if (qhstat type[i] != zdoc) {
      intx= qhstat init[(unsigned char)(qhstat type[i])].i;
      qhstat stats[i].i= intx;
    }
  }
} /* initstatistics */
References qhmemT::ferr, qh_allstatA(), qh_allstatB(), qh_allstatC(), qh_allstatD(), qh_allstatE(), qh_allstatE2(), qh_allstatF(), qh_allstatG(), qh_allstatH(), qh_allstatI(), qh_ERRmem, qh_ERRqhull, qh_exit(), qh_fprintf(), qh_fprintf_stderr(), qh_free(), qh_malloc(), qh_qhstat, qhmem, qhstat, REALmax, realT, wadd, wmax, wmin, zadd, zdoc, ZEND, zinc, zmax, zmin, and ZTYPEreal.
Referenced by orgQhull::QhullQh::QhullQh(), qh_initqhull_start(), and qh_initqhull_start().
qh_newstats()
boolT qh_newstats (int idx, int * nextindex)
{
  boolT isnew= False;
  int start, i;
  if (qhstat type[qhstat id[idx]] == zdoc)
    start= idx+1;
  else
    start= idx;
  for(i= start; i < qhstat next && qhstat type[qhstat id[i]] != zdoc; i++) {
    if (!qh_nostatistic(qhstat id[i]) && !qhstat printed[qhstat id[i]])
        isnew= True;
  }
  *nextindex= i;
  return isnew;
} /* newstats */
References boolT, False, qh_nostatistic(), qhstat, start, True, and zdoc.
Referenced by qh_check_output(), qh_check_output(), and qh_printstats().
qh_nostatistic()
boolT qh_nostatistic (int i)
{
  if ((qhstat type[i] > ZTYPEreal
       &&qhstat stats[i].r == qhstat init[(unsigned char)(qhstat type[i])].r)
      || (qhstat type[i] < ZTYPEreal
          &&qhstat stats[i].i == qhstat init[(unsigned char)(qhstat type[i])].i))
    return True;
  return False;
} /* nostatistic */
References False, qhstat, True, and ZTYPEreal.
Referenced by qh_newstats(), and qh_printstatlevel().
qh_printallstatistics()
void qh_printallstatistics (FILE * fp, const char * string)
qh_printstatistics()
void qh_printstatistics (FILE * fp, const char * string)
qh_printstatlevel()
void qh_printstatlevel (FILE * fp, int id)
{
#define NULLfield "       "
  if (id >= ZEND || qhstat printed[id])
    return;
  if (qhstat type[id] == zdoc) {
    qh_fprintf(fp, 9360, "%s\n", qhstat doc[id]);
    return;
  }
  if (qh_nostatistic(id) || !qhstat doc[id])
    return;
  qhstat printed[id]= True;
  if (qhstat count[id] != -1
      && qhstat stats[(unsigned char)(qhstat count[id])].i == 0)
    qh_fprintf(fp, 9361, " *0 cnt*");
  else if (qhstat type[id] >= ZTYPEreal && qhstat count[id] == -1)
    qh_fprintf(fp, 9362, "%7.2g", qhstat stats[id].r);
  else if (qhstat type[id] >= ZTYPEreal && qhstat count[id] != -1)
    qh_fprintf(fp, 9363, "%7.2g", qhstat stats[id].r/ qhstat stats[(unsigned char)(qhstat count[id])].i);
  else if (qhstat type[id] < ZTYPEreal && qhstat count[id] == -1)
    qh_fprintf(fp, 9364, "%7d", qhstat stats[id].i);
  else if (qhstat type[id] < ZTYPEreal && qhstat count[id] != -1)
    qh_fprintf(fp, 9365, "%7.3g", (realT) qhstat stats[id].i / qhstat stats[(unsigned char)(qhstat count[id])].i);
  qh_fprintf(fp, 9366, " %s\n", qhstat doc[id]);
} /* printstatlevel */
References count, qh_fprintf(), qh_nostatistic(), qhstat, realT, True, zdoc, ZEND, and ZTYPEreal.
Referenced by qh_printstats().
qh_printstats()
void qh_printstats (FILE * fp, int idx, int * nextindex)
{
  int j, nexti;
  if (qh_newstats(idx, &nexti)) {
    qh_fprintf(fp, 9367, "\n");
    for (j=idx; j<nexti; j++)
      qh_printstatlevel(fp, qhstat id[j]);
  }
  if (nextindex)
    *nextindex= nexti;
} /* printstats */
References qh_fprintf(), qh_newstats(), qh_printstatlevel(), and qhstat.
Referenced by qh_errexit(), qh_errexit(), qh_produce_output2(), and qh_produce_output2().
qh_stddev()
realT qh_stddev (int num, realT tot, realT tot2, realT * ave)
Referenced by qh_printsummary(), and qh_printsummary().
Variable Documentation
qh_qhstat
qhstatT qh_qhstat extern
Referenced by qh_freestatistics(), and qh_initstatistics().