OrcaSlicer: orgQhull::QhullFacetList_test Class Reference
orgQhull::QhullFacetList_test Class Reference
Public Member Functions
Helper
void recordFailedTest ()
Static Public Member Functions
Class functions
static void deleteTests ()
static int runTests (QStringList arguments)
Static Protected Attributes
Class globals
static QList< RoadTest * > s_testcases
static int s_test_count = 0
! List of testcases to execute. Initialized via add_...()
static int s_test_fail = 0
! Total number of tests executed
static QStringList s_failed_tests
! Number of failed tests
Private Slots
Test slots
void cleanup ()
void t_construct_qh ()
void t_construct_q ()
void t_convert ()
void t_readonly ()
Spot check properties and read-only. See QhullLinkedList_test.
void t_foreach ()
void t_io ()
Detailed Description
Member Function Documentation
cleanup
void orgQhull::QhullFacetList_test::cleanup () private slot
{
    RoadTest::cleanup();
}
References orgQhull::RoadTest::cleanup().
deleteTests()
void orgQhull::RoadTest::deleteTests () static inherited
{
    foreach(RoadTest *testcase, s_testcases){
        delete testcase;
    }
    s_failed_tests.clear();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
recordFailedTest()
void orgQhull::RoadTest::recordFailedTest () inherited
{
    s_test_fail++;
    QString className= metaObject()->className();
    s_failed_tests << className + "::" + QTest::currentTestFunction();
}
References orgQhull::RoadTest::s_failed_tests, and orgQhull::RoadTest::s_test_fail.
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
runTests()
int orgQhull::RoadTest::runTests (QStringList arguments) static inherited
{
    int result= 0; // assume success
    foreach(RoadTest *testcase, s_testcases){
        try{
            result += QTest::qExec(testcase, arguments);
        }catch(const std::exception &e){
            cout << "FAIL!  : Threw error ";
            cout << e.what() << endl;
    s_test_count++;
            testcase->recordFailedTest();
            // Qt 4.5.2 OK.  In Qt 4.3.3, qtestcase did not clear currentTestObject
        }
    }
    if(s_test_fail){
        cout << "Failed " << s_test_fail << " of " << s_test_count << " tests.\n";
        cout << s_failed_tests.join("\n").toLocal8Bit().constData() << std::endl;
    }else{
        cout << "Passed " << s_test_count << " tests.\n";
    }
    return result;
}//runTests
References orgQhull::RoadTest::recordFailedTest(), orgQhull::RoadTest::s_failed_tests, orgQhull::RoadTest::s_test_count, orgQhull::RoadTest::s_test_fail, and orgQhull::RoadTest::s_testcases.
Referenced by orgQhull::main().
t_construct_q
void orgQhull::QhullFacetList_test::t_construct_q () private slot
{
    RboxPoints rcube("c");
    Qhull q(rcube,"QR0");  // rotated unit cube
    QhullFacetList fs2= q.facetList();
    QVERIFY(!fs2.isEmpty());
    QCOMPARE(fs2.count(),6);
    QhullFacetList fs3(q.endFacet(), q.endFacet());
    QVERIFY(fs3.isEmpty());
    QhullFacetList fs4(q.endFacet().previous(), q.endFacet());
    QCOMPARE(fs4.count(), 1);
    QhullFacetList fs5(q.beginFacet(), q.endFacet());
    QCOMPARE(fs2.count(), fs5.count());
    QVERIFY(fs2==fs5);
    QhullFacetList fs6= fs2; // copy constructor
    QVERIFY(fs6==fs2);
    std::vector<QhullFacet> fv= fs2.toStdVector();
    QCOMPARE(fv.size(), 6u);
}//t_construct_q
References orgQhull::Qhull::beginFacet(), orgQhull::QhullFacetList::count(), orgQhull::Qhull::endFacet(), orgQhull::Qhull::facetList(), orgQhull::QhullLinkedList< T >::isEmpty(), orgQhull::QhullFacet::previous(), and orgQhull::QhullFacetList::toStdVector().
t_construct_qh
void orgQhull::QhullFacetList_test::t_construct_qh () private slot
{
    RboxPoints rcube("c");
    Qhull q(rcube,"QR0");  // rotated unit cube
    QhullFacetList fs2= q.facetList();
    QVERIFY(!fs2.isEmpty());
    QCOMPARE(fs2.count(),6);
    QhullFacetList fs3(q.endFacet(), q.endFacet());
    QVERIFY(fs3.isEmpty());
    QhullFacetList fs4(q.endFacet().previous(), q.endFacet());
    QCOMPARE(fs4.count(), 1);
    QhullFacetList fs5(q.beginFacet(), q.endFacet());
    QCOMPARE(fs2.count(), fs5.count());
    QVERIFY(fs2==fs5);
    QhullFacetList fs6= fs2; // copy constructor
    QVERIFY(fs6==fs2);
    std::vector<QhullFacet> fv= fs2.toStdVector();
    QCOMPARE(fv.size(), 6u);
}//t_construct_qh
References orgQhull::Qhull::beginFacet(), orgQhull::QhullFacetList::count(), orgQhull::Qhull::endFacet(), orgQhull::Qhull::facetList(), orgQhull::QhullLinkedList< T >::isEmpty(), orgQhull::QhullFacet::previous(), and orgQhull::QhullFacetList::toStdVector().
t_convert
void orgQhull::QhullFacetList_test::t_convert () private slot
{
    RboxPoints rcube("c");
    Qhull q(rcube,"QR0 QV2");  // rotated unit cube
    QhullFacetList fs2= q.facetList();
    QVERIFY(!fs2.isSelectAll());
    QVERIFY(!fs2.isEmpty());
    QCOMPARE(fs2.count(),3);
    std::vector<QhullFacet> fv= fs2.toStdVector();
    QCOMPARE(fv.size(), 3u);
    QList<QhullFacet> fv2= fs2.toQList();
    QCOMPARE(fv2.size(), 3);
    std::vector<QhullVertex> fv5= fs2.vertices_toStdVector();
    QCOMPARE(fv5.size(), 7u);
    QList<QhullVertex> fv6= fs2.vertices_toQList();
    QCOMPARE(fv6.size(), 7);
    fs2.selectAll();
    QVERIFY(fs2.isSelectAll());
    std::vector<QhullFacet> fv3= fs2.toStdVector();
    QCOMPARE(fv3.size(), 6u);
    QList<QhullFacet> fv4= fs2.toQList();
    QCOMPARE(fv4.size(), 6);
    std::vector<QhullVertex> fv7= fs2.vertices_toStdVector();
    QCOMPARE(fv7.size(), 8u);
    QList<QhullVertex> fv8= fs2.vertices_toQList();
    QCOMPARE(fv8.size(), 8);
}//t_convert
References orgQhull::QhullFacetList::count(), orgQhull::Qhull::facetList(), orgQhull::QhullLinkedList< T >::isEmpty(), orgQhull::QhullFacetList::isSelectAll(), orgQhull::QhullFacetList::selectAll(), orgQhull::QhullFacetList::toStdVector(), and orgQhull::QhullFacetList::vertices_toStdVector().
t_foreach
void orgQhull::QhullFacetList_test::t_foreach () private slot
{
    RboxPoints rcube("c");
    // Spot check predicates and accessors.  See QhullLinkedList_test
    Qhull q(rcube,"Qt QR0");  // triangulation of rotated unit cube
    QhullFacetList fs= q.facetList();
    QVERIFY(fs.contains(q.firstFacet()));
    QhullFacet f= q.firstFacet().next();
    QVERIFY(fs.contains(f));
    QCOMPARE(fs.first(), *fs.begin());
    QCOMPARE(*(fs.end()-1), fs.last());
    QCOMPARE(fs.first(), q.firstFacet());
    QCOMPARE(*fs.begin(), q.beginFacet());
    QCOMPARE(*fs.end(), q.endFacet());
}//t_foreach
References orgQhull::Qhull::beginFacet(), orgQhull::Qhull::endFacet(), orgQhull::Qhull::facetList(), orgQhull::Qhull::firstFacet(), and orgQhull::QhullFacet::next().
t_io
void orgQhull::QhullFacetList_test::t_io () private slot
{
    RboxPoints rcube("c");
    {
        Qhull q(rcube,"QR0 QV0");   // good facets are adjacent to point 0
        QhullFacetList fs= q.facetList();
        ostringstream os;
        os << fs.print("Show all of FacetList\n");
        os << "\nFacets only\n" << fs;
        os << "\nVertices only\n" << fs.printVertices();
        cout << os.str();
        QString facets= QString::fromStdString(os.str());
        QCOMPARE(facets.count("(v"), 2*7+12*3*2);
        QCOMPARE(facets.count(QRegExp("f\\d")), 2*3*7 + 13*3*2);
    }
}//t_io
References orgQhull::Qhull::facetList().
t_readonly
void orgQhull::QhullFacetList_test::t_readonly () private slot
Spot check properties and read-only. See QhullLinkedList_test.
{
    RboxPoints rcube("c");
    Qhull q(rcube,"QV0");  // good facets are adjacent to point 0
    QhullFacetList fs= q.facetList();
    QVERIFY(!fs.isSelectAll());
    QCOMPARE(fs.count(), 3);
    QCOMPARE(fs.first(), q.firstFacet());
    fs.selectAll();
    QVERIFY(fs.isSelectAll());
    QCOMPARE(fs.count(), 6);
    fs.selectGood();
    QVERIFY(!fs.isSelectAll());
    QCOMPARE(fs.count(), 3);
    fs.selectAll();
    QVERIFY(fs.isSelectAll());
    QCOMPARE(fs.count(), 6);
    QhullFacet f= fs.first();
    QhullFacet f2= fs.last();
    fs.selectAll();
    QVERIFY(fs.contains(f));
    QVERIFY(fs.contains(f2));
    QVERIFY(f.isGood());
    QVERIFY(!f2.isGood());
    fs.selectGood();
    QVERIFY(fs.contains(f));
    QVERIFY(!fs.contains(f2));
}//t_readonly
References orgQhull::Qhull::facetList(), orgQhull::Qhull::firstFacet(), and orgQhull::QhullFacet::isGood().
Member Data Documentation
s_failed_tests
QStringList orgQhull::RoadTest::s_failed_tests static protected inherited
! Number of failed tests
Referenced by orgQhull::RoadTest::deleteTests(), orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_test_count
int orgQhull::RoadTest::s_test_count = 0 static protected inherited
! List of testcases to execute. Initialized via add_...()
Referenced by orgQhull::RoadTest::cleanup(), and orgQhull::RoadTest::runTests().
s_test_fail
int orgQhull::RoadTest::s_test_fail = 0 static protected inherited
! Total number of tests executed
Referenced by orgQhull::RoadTest::recordFailedTest(), and orgQhull::RoadTest::runTests().
s_testcases
QList< RoadTest * > orgQhull::RoadTest::s_testcases static protected inherited
Referenced by orgQhull::RoadTest::RoadTest(), orgQhull::RoadTest::deleteTests(), and orgQhull::RoadTest::runTests().
The documentation for this class was generated from the following file:
src/qhull/src/qhulltest/QhullFacetList_test.cpp