OrcaSlicer: ImDrawDataBuilder Struct Reference
ImDrawDataBuilder Struct Reference
#include <src/imgui/imgui_internal.h>
Public Member Functions
void Clear ()
void ClearFreeMemory ()
int GetDrawListCount () const
IMGUI_API void FlattenIntoSingleLayer ()
Public Attributes
ImVector< ImDrawList * > Layers [2]
Detailed Description
Member Function Documentation
Clear()
void ImDrawDataBuilder::Clear () inline
{ for (int n = 0; n < IM_ARRAYSIZE(Layers); n++) Layers[n].resize(0); }
References IM_ARRAYSIZE, Layers, and n.
Referenced by ImGui::Render().
ClearFreeMemory()
void ImDrawDataBuilder::ClearFreeMemory () inline
{ for (int n = 0; n < IM_ARRAYSIZE(Layers); n++) Layers[n].clear(); }
References IM_ARRAYSIZE, Layers, and n.
FlattenIntoSingleLayer()
void ImDrawDataBuilder::FlattenIntoSingleLayer ()
{
    int n = Layers[0].Size;
    int size = n;
    for (int i = 1; i < IM_ARRAYSIZE(Layers); i++)
        size += Layers[i].Size;
    Layers[0].resize(size);
    for (int layer_n = 1; layer_n < IM_ARRAYSIZE(Layers); layer_n++)
    {
        ImVector<ImDrawList*>& layer = Layers[layer_n];
        if (layer.empty())
            continue;
        memcpy(&Layers[0][n], &layer[0], layer.Size * sizeof(ImDrawList*));
        n += layer.Size;
        layer.resize(0);
    }
}
References ImVector< T >::empty(), IM_ARRAYSIZE, Layers, memcpy, n, ImVector< T >::resize(), ImVector< T >::Size, and size.
Referenced by ImGui::Render().
GetDrawListCount()
int ImDrawDataBuilder::GetDrawListCount () const inline
{ int count = 0; for (int n = 0; n < IM_ARRAYSIZE(Layers); n++) count += Layers[n].Size; return count; }
References count, IM_ARRAYSIZE, Layers, and n.
Member Data Documentation
Layers
ImVector<ImDrawList*> ImDrawDataBuilder::Layers[2]
Referenced by AddWindowToDrawData(), Clear(), ClearFreeMemory(), ImGui::DebugNodeViewport(), FlattenIntoSingleLayer(), GetDrawListCount(), ImGui::Render(), and ImGui::ShowMetricsWindow().
The documentation for this struct was generated from the following files:
src/imgui/imgui_internal.h
src/imgui/imgui.cpp