OrcaSlicer: Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector > Class Template Reference
Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector > Class Template Reference
Public Member Functions
_AroundPadSkeleton (const ExPolygons &support_blueprint, const ExPolygons &model_blueprint, const PadConfig &cfg, ThrowOnCancel thr)
Public Attributes
ExPolygons inner
ExPolygons outer
Private Member Functions
void add_supports_to_index (const ExPolygons &supp_bp)
ExPolygons wafflized_concave_hull (const ExPolygons &supp_bp, const ExPolygons &model_bp, const PadConfig &cfg, ThrowOnCancel thr)
void remove_redundant_parts (ExPolygons &parts)
Private Attributes
_Intersector m_intersector
Detailed Description
template<class _Intersector>
class Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >
Constructor & Destructor Documentation
_AroundPadSkeleton()
template<class _Intersector > Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::_AroundPadSkeleton (const ExPolygons & support_blueprint, const ExPolygons & model_blueprint, const PadConfig & cfg, ThrowOnCancel thr) inline
    {
        // We need to merge the support and the model contours in a special
        // way in which the model contours have to be substracted from the
        // support contours. The pad has to have a hole in which the model can
        // fit perfectly (thus the substraction -- diff_ex). Also, the pad has
        // to be eliminated from areas where there is no need for a pad, due
        // to missing supports.
        add_supports_to_index(support_blueprint);
        auto model_bp_offs =
            offset_ex(model_blueprint,
                      scaled<float>(cfg.embed_object.object_gap_mm),
                      ClipperLib::jtMiter, 1);
        ExPolygons fullcvh =
            wafflized_concave_hull(support_blueprint, model_bp_offs, cfg, thr);
        auto model_bp_sticks =
            breakstick_holes(model_bp_offs, cfg.embed_object.object_gap_mm,
                             cfg.embed_object.stick_stride_mm,
                             cfg.embed_object.stick_width_mm,
                             cfg.embed_object.stick_penetration_mm);
        ExPolygons fullpad = diff_ex(fullcvh, model_bp_sticks);
        PadSkeleton divided = divide_blueprint(fullpad);
        remove_redundant_parts(divided.outer);
        remove_redundant_parts(divided.inner);
        outer = std::move(divided.outer);
        inner = std::move(divided.inner);
    }
References Slic3r::sla::anonymous_namespace{Pad.cpp}::breakstick_holes(), Slic3r::diff_ex(), Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint(), Slic3r::sla::PadConfig::embed_object, Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::inner, ClipperLib::jtMiter, Slic3r::sla::PadConfig::EmbedObject::object_gap_mm, Slic3r::offset_ex(), Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::outer, Slic3r::sla::PadConfig::EmbedObject::stick_penetration_mm, Slic3r::sla::PadConfig::EmbedObject::stick_stride_mm, and Slic3r::sla::PadConfig::EmbedObject::stick_width_mm.
Member Function Documentation
add_supports_to_index()
template<class _Intersector > void Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::add_supports_to_index (const ExPolygons & supp_bp) inline private
    {
        for (auto &ep : supp_bp) m_intersector.add(ep);
    }
remove_redundant_parts()
template<class _Intersector > void Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::remove_redundant_parts (ExPolygons & parts) inline private
    {
        auto endit = std::remove_if(parts.begin(), parts.end(),
                                    [this](const ExPolygon &p) {
                                        return !m_intersector.intersects(p);
                                    });
        parts.erase(endit, parts.end());
    }
wafflized_concave_hull()
template<class _Intersector > ExPolygons Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::wafflized_concave_hull (const ExPolygons & supp_bp, const ExPolygons & model_bp, const PadConfig & cfg, ThrowOnCancel thr) inline private
    {
        auto allin = reserve_vector<ExPolygon>(supp_bp.size() + model_bp.size());
        for (auto &ep : supp_bp) allin.emplace_back(ep.contour);
        for (auto &ep : model_bp) allin.emplace_back(ep.contour);
        ConcaveHull cchull{allin, get_merge_distance(cfg), thr};
        return offset_waffle_style_ex(cchull, get_waffle_offset(cfg));
    }
References Slic3r::sla::anonymous_namespace{Pad.cpp}::get_merge_distance(), Slic3r::sla::anonymous_namespace{Pad.cpp}::get_waffle_offset(), and Slic3r::sla::offset_waffle_style_ex().
Member Data Documentation
inner
ExPolygons Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::inner inherited
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::_AroundPadSkeleton(), Slic3r::sla::anonymous_namespace{Pad.cpp}::create_pad_geometry(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint().
m_intersector
template<class _Intersector > _Intersector Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::m_intersector private
outer
ExPolygons Slic3r::sla::anonymous_namespace{Pad.cpp}::PadSkeleton::outer inherited
Referenced by Slic3r::sla::anonymous_namespace{Pad.cpp}::_AroundPadSkeleton< _Intersector >::_AroundPadSkeleton(), Slic3r::sla::anonymous_namespace{Pad.cpp}::create_pad_geometry(), and Slic3r::sla::anonymous_namespace{Pad.cpp}::divide_blueprint().
The documentation for this class was generated from the following file:
src/libslic3r/SLA/Pad.cpp