OrcaSlicer: Slic3r::ExPolygonCollection Class Reference
Slic3r::ExPolygonCollection Class Reference
#include <src/libslic3r/ExPolygonCollection.hpp>
Public Member Functions
ExPolygonCollection ()
ExPolygonCollection (const ExPolygon &expolygon)
ExPolygonCollection (const ExPolygons &expolygons)
operator Points () const
operator Polygons () const
operator ExPolygons & ()
void scale (double factor)
void translate (double x, double y)
void rotate (double angle, const Point &center)
template<class T >
bool contains (const T &item) const
bool contains_b (const Point &point) const
void simplify (double tolerance)
Polygon convex_hull () const
Lines lines () const
Polygons contours () const
void append (const ExPolygons &expolygons)
Public Attributes
ExPolygons expolygons
Detailed Description
Constructor & Destructor Documentation
ExPolygonCollection() [1/3]
Slic3r::ExPolygonCollection::ExPolygonCollection () inline
{}
ExPolygonCollection() [2/3]
Slic3r::ExPolygonCollection::ExPolygonCollection (const ExPolygon & expolygon) explicit
{
    this->expolygons.push_back(expolygon);
}
References expolygons.
ExPolygonCollection() [3/3]
Slic3r::ExPolygonCollection::ExPolygonCollection (const ExPolygons & expolygons) inline explicit
: expolygons(expolygons) {}
Member Function Documentation
append()
void Slic3r::ExPolygonCollection::append (const ExPolygons & expolygons)
{
    this->expolygons.insert(this->expolygons.end(), expp.begin(), expp.end());
}
References expolygons.
contains()
template<class T > template bool Slic3r::ExPolygonCollection::contains< Polyline > (const T & item) const
{
    for (const ExPolygon &poly : this->expolygons)
        if (poly.contains(item))
            return true;
    return false;
}
References expolygons.
contains_b()
bool Slic3r::ExPolygonCollection::contains_b (const Point & point) const
{
    for (ExPolygons::const_iterator it = this->expolygons.begin(); it != this->expolygons.end(); ++it) {
        if (it->contains_b(point)) return true;
    }
    return false;
}
References expolygons.
contours()
Polygons Slic3r::ExPolygonCollection::contours () const
{
    Polygons contours;
    contours.reserve(this->expolygons.size());
    for (ExPolygons::const_iterator it = this->expolygons.begin(); it != this->expolygons.end(); ++it)
        contours.push_back(it->contour);
    return contours;
}
References contours(), and expolygons.
Referenced by contours().
convex_hull()
Polygon Slic3r::ExPolygonCollection::convex_hull () const
{
    Points pp;
    for (ExPolygons::const_iterator it = this->expolygons.begin(); it != this->expolygons.end(); ++it)
        pp.insert(pp.end(), it->contour.points.begin(), it->contour.points.end());
    return Slic3r::Geometry::convex_hull(pp);
}
References Slic3r::Geometry::convex_hull(), and expolygons.
lines()
Lines Slic3r::ExPolygonCollection::lines () const
{
    Lines lines;
    for (ExPolygons::const_iterator it = this->expolygons.begin(); it != this->expolygons.end(); ++it) {
        Lines ex_lines = it->lines();
        lines.insert(lines.end(), ex_lines.begin(), ex_lines.end());
    }
    return lines;
}
References expolygons, and lines().
Referenced by lines().
operator ExPolygons &()
Slic3r::ExPolygonCollection::operator ExPolygons & () explicit
{
    return this->expolygons;
}
operator Points()
Slic3r::ExPolygonCollection::operator Points () const explicit
{
    Points points;
    Polygons pp = (Polygons)*this;
    for (Polygons::const_iterator poly = pp.begin(); poly != pp.end(); ++poly) {
        for (Points::const_iterator point = poly->points.begin(); point != poly->points.end(); ++point)
            points.push_back(*point);
    }
    return points;
}
operator Polygons()
Slic3r::ExPolygonCollection::operator Polygons () const explicit
{
    Polygons polygons;
    for (ExPolygons::const_iterator it = this->expolygons.begin(); it != this->expolygons.end(); ++it) {
        polygons.push_back(it->contour);
        for (Polygons::const_iterator ith = it->holes.begin(); ith != it->holes.end(); ++ith) {
            polygons.push_back(*ith);
        }
    }
    return polygons;
}
rotate()
void Slic3r::ExPolygonCollection::rotate (double angle, const Point & center)
{
    for (ExPolygons::iterator it = expolygons.begin(); it != expolygons.end(); ++it) {
        (*it).rotate(angle, center);
    }
}
References Slic3r::angle(), and expolygons.
scale()
void Slic3r::ExPolygonCollection::scale (double factor)
{
    for (ExPolygons::iterator it = expolygons.begin(); it != expolygons.end(); ++it) {
        (*it).scale(factor);
    }
}
References expolygons.
simplify()
void Slic3r::ExPolygonCollection::simplify (double tolerance)
{
    ExPolygons expp;
    for (ExPolygons::const_iterator it = this->expolygons.begin(); it != this->expolygons.end(); ++it) {
        it->simplify(tolerance, &expp);
    }
    this->expolygons = expp;
}
References expolygons.
translate()
void Slic3r::ExPolygonCollection::translate (double x, double y)
{
   for (ExPolygons::iterator it = expolygons.begin(); it != expolygons.end(); ++it) {
        (*it).translate(x, y);
    }
}
References expolygons.
Member Data Documentation
expolygons
ExPolygons Slic3r::ExPolygonCollection::expolygons
Referenced by ExPolygonCollection(), append(), contains(), contains_b(), contours(), convex_hull(), Slic3r::get_extents(), lines(), rotate(), scale(), simplify(), and translate().
The documentation for this class was generated from the following files:
src/libslic3r/ExPolygonCollection.hpp
src/libslic3r/ExPolygonCollection.cpp