OrcaSlicer: orgQhull::QhullPoint Class Reference
orgQhull::QhullPoint Class Reference
A QhullPoint is a dimension and an array of coordinates. With Qhull/QhullQh, a QhullPoint has an identifier. Point equality is relative to qh.distanceEpsilon.
#include <src/qhull/src/libqhullcpp/QhullPoint.h>
Classes
struct PrintPoint
Public Types
Iterators
typedef coordT * base_type
typedef const coordT * iterator
typedef const coordT * const_iterator
typedef QhullPoint::iterator Iterator
typedef QhullPoint::const_iterator ConstIterator
Public Member Functions
Constructors
QhullPoint, PointCoordinates, and QhullPoints have similar constructors If Qhull/QhullQh is not initialized, then QhullPoint.dimension() is zero unless explicitly set Cannot define QhullPoints(int pointDimension) since it is ambiguous with QhullPoints(QhullQh *qqh)
QhullPoint ()
QhullPoint (int pointDimension, coordT *c)
QhullPoint (const Qhull &q)
QhullPoint (const Qhull &q, coordT *c)
QhullPoint (const Qhull &q, Coordinates &c)
QhullPoint of Coordinates with point_dimension==c.count()
QhullPoint (const Qhull &q, int pointDimension, coordT *c)
QhullPoint (QhullQh *qqh)
QhullPoint (QhullQh *qqh, coordT *c)
QhullPoint (QhullQh *qqh, Coordinates &c)
QhullPoint (QhullQh *qqh, int pointDimension, coordT *c)
QhullPoint (const QhullPoint &other)
Creates an alias. Does not make a deep copy of the point. Needed for return by value and parameter passing.
QhullPoint & operator= (const QhullPoint &other)
Creates an alias. Does not make a deep copy of the point. Needed for vector<QhullPoint>
~QhullPoint ()
Conversions
std::vector< coordT > toStdVector () const
GetSet
const coordT * coordinates () const
0 if undefined
coordT * coordinates ()
0 if undefined
void defineAs (coordT *c)
void defineAs (int pointDimension, coordT *c)
void defineAs (QhullPoint &other)
int dimension () const
coordT * getBaseT () const
countT id () const
bool isValid () const
bool operator== (const QhullPoint &other) const
QhullPoint is equal if it has the same address and dimension If !qh_qh, returns true if dimension and coordinates are equal If qh_qh, returns true if the distance between points is less than qh_qh->distanceEpsilon()
bool operator!= (const QhullPoint &other) const
const coordT & operator[] (int idx) const
0 to hull_dim-1
coordT & operator[] (int idx)
0 to hull_dim-1
QhullQh * qh ()
void setCoordinates (coordT *c)
void setDimension (int pointDimension)
foreach
iterator begin ()
const_iterator begin () const
const_iterator constBegin () const
const_iterator constEnd () const
int count ()
iterator end ()
const_iterator end () const
size_t size ()
Methods
void advancePoint (countT idx)
double distance (const QhullPoint &p) const
Return distance between two points.
IO
PrintPoint print (const char *message) const
PrintPoint printWithIdentifier (const char *message) const
Protected Attributes
Fields
coordT * point_coordinates
Pointer to first coordinate, 0 if undefined.
QhullQh * qh_qh
qhT for this instance of Qhull. 0 if undefined. operator==() returns true if points within sqrt(qh_qh->distanceEpsilon()) If !qh_qh, id() is -3, and operator==() requires equal coordinates
int point_dimension
Default dimension is qh_qh->hull_dim.
Detailed Description
A QhullPoint is a dimension and an array of coordinates. With Qhull/QhullQh, a QhullPoint has an identifier. Point equality is relative to qh.distanceEpsilon.
Member Typedef Documentation
base_type
typedef coordT* orgQhull::QhullPoint::base_type
const_iterator
typedef const coordT* orgQhull::QhullPoint::const_iterator
ConstIterator
typedef QhullPoint::const_iterator orgQhull::QhullPoint::ConstIterator
iterator
typedef const coordT* orgQhull::QhullPoint::iterator
Iterator
typedef QhullPoint::iterator orgQhull::QhullPoint::Iterator
Constructor & Destructor Documentation
QhullPoint() [1/11]
orgQhull::QhullPoint::QhullPoint () inline
: point_coordinates(0), qh_qh(0), point_dimension(0) {}
QhullPoint() [2/11]
orgQhull::QhullPoint::QhullPoint (int pointDimension, coordT * c) inline
: point_coordinates(c), qh_qh(0), point_dimension(pointDimension) { QHULL_ASSERT(pointDimension>0); }
References QHULL_ASSERT.
QhullPoint() [3/11]
orgQhull::QhullPoint::QhullPoint (const Qhull & q) explicit
: point_coordinates(0)
, qh_qh(q.qh())
, point_dimension(q.hullDimension())
{
}//QhullPoint
QhullPoint() [4/11]
orgQhull::QhullPoint::QhullPoint (const Qhull & q, coordT * c)
: point_coordinates(c)
, qh_qh(q.qh())
, point_dimension(q.hullDimension())
{
    QHULL_ASSERT(q.hullDimension()>0);
}//QhullPoint dim, coordT
References orgQhull::Qhull::hullDimension(), and QHULL_ASSERT.
QhullPoint() [5/11]
orgQhull::QhullPoint::QhullPoint (const Qhull & q, Coordinates & c)
QhullPoint of Coordinates with point_dimension==c.count()
: point_coordinates(c.data())
, qh_qh(q.qh())
, point_dimension(c.count())
{
}//QhullPoint Coordinates
QhullPoint() [6/11]
orgQhull::QhullPoint::QhullPoint (const Qhull & q, int pointDimension, coordT * c)
: point_coordinates(c)
, qh_qh(q.qh())
, point_dimension(pointDimension)
{
}//QhullPoint dim, coordT
QhullPoint() [7/11]
orgQhull::QhullPoint::QhullPoint (QhullQh * qqh) inline explicit
: point_coordinates(0), qh_qh(qqh), point_dimension(qqh->hull_dim) {}
QhullPoint() [8/11]
orgQhull::QhullPoint::QhullPoint (QhullQh * qqh, coordT * c) inline
: point_coordinates(c), qh_qh(qqh), point_dimension(qqh->hull_dim) { QHULL_ASSERT(qqh->hull_dim>0); }
References qhT::hull_dim, and QHULL_ASSERT.
QhullPoint() [9/11]
orgQhull::QhullPoint::QhullPoint (QhullQh * qqh, Coordinates & c) inline
: point_coordinates(c.data()), qh_qh(qqh), point_dimension(c.count()) {}
QhullPoint() [10/11]
orgQhull::QhullPoint::QhullPoint (QhullQh * qqh, int pointDimension, coordT * c) inline
: point_coordinates(c), qh_qh(qqh), point_dimension(pointDimension) {}
QhullPoint() [11/11]
orgQhull::QhullPoint::QhullPoint (const QhullPoint & other) inline
Creates an alias. Does not make a deep copy of the point. Needed for return by value and parameter passing.
: point_coordinates(other.point_coordinates), qh_qh(other.qh_qh), point_dimension(other.point_dimension) {}
~QhullPoint()
orgQhull::QhullPoint::~QhullPoint () inline
{}
Member Function Documentation
advancePoint()
void orgQhull::QhullPoint::advancePoint (countT idx) inline
{ if(point_coordinates) { point_coordinates += idx*point_dimension; } }
References point_coordinates, and point_dimension.
Referenced by orgQhull::QhullPoints::iterator::operator++(), orgQhull::QhullPoints::const_iterator::operator++(), orgQhull::QhullPoints::iterator::operator+=(), orgQhull::QhullPoints::const_iterator::operator+=(), orgQhull::QhullPoints::iterator::operator--(), orgQhull::QhullPoints::const_iterator::operator--(), orgQhull::QhullPoints::iterator::operator-=(), orgQhull::QhullPoints::const_iterator::operator-=(), orgQhull::QhullPoints::iterator::operator[](), and orgQhull::QhullPoint_test::t_define().
begin() [1/2]
iterator orgQhull::QhullPoint::begin () inline
{ return point_coordinates; }
References point_coordinates.
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), and orgQhull::QhullPoint_test::t_iterator().
begin() [2/2]
const_iterator orgQhull::QhullPoint::begin () const inline
{ return point_coordinates; }
References point_coordinates.
constBegin()
const_iterator orgQhull::QhullPoint::constBegin () const inline
{ return point_coordinates; }
References point_coordinates.
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), and orgQhull::QhullPoint_test::t_construct().
constEnd()
const_iterator orgQhull::QhullPoint::constEnd () const inline
{ return (point_coordinates ? point_coordinates+point_dimension : 0); }
References point_coordinates, and point_dimension.
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), and orgQhull::QhullPoint_test::t_construct().
coordinates() [1/2]
coordT * orgQhull::QhullPoint::coordinates () inline
0 if undefined
References point_coordinates.
coordinates() [2/2]
const coordT * orgQhull::QhullPoint::coordinates () const inline
0 if undefined
References point_coordinates.
Referenced by orgQhull::PointCoordinates::append(), orgQhull::QhullHyperplane::distance(), operator<<(), operator<<(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullPoints_test::t_iterator(), orgQhull::QhullPoint_test::t_operator(), and orgQhull::QhullPoint_test::t_readonly().
count()
int orgQhull::QhullPoint::count () inline
{ return (point_coordinates ? point_dimension : 0); }
References point_coordinates, and point_dimension.
defineAs() [1/3]
void orgQhull::QhullPoint::defineAs (coordT * c) inline
{ QHULL_ASSERT(point_dimension>0); point_coordinates= c; }
References point_coordinates, point_dimension, and QHULL_ASSERT.
Referenced by orgQhull::QhullPoints::const_iterator::operator=(), orgQhull::QhullPoints::iterator::operator=(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullPoints_test::t_search(), orgQhull::QhullPoints::value(), and orgQhull::QhullPoints::value().
defineAs() [2/3]
void orgQhull::QhullPoint::defineAs (int pointDimension, coordT * c) inline
{ QHULL_ASSERT(pointDimension>=0); point_coordinates= c; point_dimension= pointDimension; }
References point_coordinates, point_dimension, and QHULL_ASSERT.
defineAs() [3/3]
void orgQhull::QhullPoint::defineAs (QhullPoint & other) inline
{ point_coordinates= other.point_coordinates; qh_qh= other.qh_qh; point_dimension= other.point_dimension; }
References point_coordinates, point_dimension, and qh_qh.
dimension()
int orgQhull::QhullPoint::dimension () const inline
{ return point_dimension; }
References point_dimension.
Referenced by orgQhull::PointCoordinates::append(), orgQhull::QhullHyperplane::distance(), operator<<(), operator<<(), orgQhull::QhullPoints_test::t_const_iterator(), orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullPoint_test::t_define(), orgQhull::QhullPoints_test::t_element(), orgQhull::QhullPointSet_test::t_element(), orgQhull::Qhull_test::t_getSet(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullPoints_test::t_iterator(), orgQhull::QhullPointSet_test::t_iterator(), orgQhull::QhullPoint_test::t_operator(), orgQhull::QhullPoint_test::t_qhullpoint_iterator(), and orgQhull::QhullPoint_test::t_readonly().
distance()
double orgQhull::QhullPoint::distance (const QhullPoint & p) const
Return distance between two points.
{
    const coordT *c= point_coordinates;
    const coordT *c2= p.point_coordinates;
    int dim= point_dimension;
    if(dim!=p.point_dimension){
        throw QhullError(10075, "QhullPoint error: Expecting dimension %d for distance().  Got %d", dim, p.point_dimension);
    }
    if(!c || !c2){
        throw QhullError(10076, "QhullPoint error: Cannot compute distance() for undefined point");
    }
    double dist;
    switch(dim){
  case 2:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]);
      break;
  case 3:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]);
      break;
  case 4:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]);
      break;
  case 5:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]) + (c[4]-c2[4])*(c[4]-c2[4]);
      break;
  case 6:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]) + (c[4]-c2[4])*(c[4]-c2[4]) + (c[5]-c2[5])*(c[5]-c2[5]);
      break;
  case 7:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]) + (c[4]-c2[4])*(c[4]-c2[4]) + (c[5]-c2[5])*(c[5]-c2[5]) + (c[6]-c2[6])*(c[6]-c2[6]);
      break;
  case 8:
      dist= (c[0]-c2[0])*(c[0]-c2[0]) + (c[1]-c2[1])*(c[1]-c2[1]) + (c[2]-c2[2])*(c[2]-c2[2]) + (c[3]-c2[3])*(c[3]-c2[3]) + (c[4]-c2[4])*(c[4]-c2[4]) + (c[5]-c2[5])*(c[5]-c2[5]) + (c[6]-c2[6])*(c[6]-c2[6]) + (c[7]-c2[7])*(c[7]-c2[7]);
      break;
  default:
      dist= 0.0;
      for(int k=dim; k--; ){
          dist += (*c - *c2) * (*c - *c2);
          ++c;
          ++c2;
      }
      break;
    }
    return sqrt(dist);
}//distance
References coordT, point_coordinates, point_dimension, and sqrt().
Referenced by orgQhull::QhullPoint_test::t_method().
end() [1/2]
iterator orgQhull::QhullPoint::end () inline
{ return (point_coordinates ? point_coordinates+point_dimension : 0); }
References point_coordinates, and point_dimension.
Referenced by orgQhull::QhullPoint_test::t_const_iterator(), orgQhull::QhullPoint_test::t_construct(), and orgQhull::QhullPoint_test::t_iterator().
end() [2/2]
const_iterator orgQhull::QhullPoint::end () const inline
{ return (point_coordinates ? point_coordinates+point_dimension : 0); }
References point_coordinates, and point_dimension.
getBaseT()
coordT * orgQhull::QhullPoint::getBaseT () const inline
{ return point_coordinates; } // for QhullPointSet
References point_coordinates.
id()
countT orgQhull::QhullPoint::id () const inline
{ return qh_pointid(qh_qh, point_coordinates); } // NOerrors
References point_coordinates, qh_pointid(), and qh_qh.
Referenced by operator<<(), operator<<(), operator<<(), operator<<(), operator<<(), orgQhull::QhullPoint_test::t_construct(), orgQhull::QhullVertex_test::t_getSet(), and orgQhull::QhullPoint_test::t_readonly().
isValid()
bool orgQhull::QhullPoint::isValid () const inline
{ return (point_coordinates!=0 && point_dimension>0); };
References point_coordinates, and point_dimension.
Referenced by orgQhull::QhullPoint_test::t_construct(), and orgQhull::QhullPoint_test::t_readonly().
operator!=()
bool orgQhull::QhullPoint::operator!= (const QhullPoint & other) const inline
{ return ! operator==(other); }
References operator==().
operator=()
QhullPoint & orgQhull::QhullPoint::operator= (const QhullPoint & other) inline
Creates an alias. Does not make a deep copy of the point. Needed for vector<QhullPoint>
{ point_coordinates= other.point_coordinates; qh_qh= other.qh_qh; point_dimension= other.point_dimension; return *this; }
References point_coordinates, point_dimension, and qh_qh.
operator==()
bool orgQhull::QhullPoint::operator== (const QhullPoint & other) const
QhullPoint is equal if it has the same address and dimension If !qh_qh, returns true if dimension and coordinates are equal If qh_qh, returns true if the distance between points is less than qh_qh->distanceEpsilon()
{
    if(point_dimension!=other.point_dimension){
        return false;
    }
    const coordT *c= point_coordinates;
    const coordT *c2= other.point_coordinates;
    if(c==c2){
        return true;
    }
    if(!c || !c2){
        return false;
    }
    if(!qh_qh || qh_qh->hull_dim==0){
        for(int k= point_dimension; k--; ){
            if(*c++ != *c2++){
                return false;
            }
        }
        return true;
    }
    double dist2= 0.0;
    for(int k= point_dimension; k--; ){
        double diff= *c++ - *c2++;
        dist2 += diff*diff;
    }
    dist2= sqrt(dist2);
    return (dist2 < qh_qh->distanceEpsilon());
}//operator==
References coordT, qhT::hull_dim, point_coordinates, point_dimension, qh_qh, and sqrt().
Referenced by operator!=().
operator[]() [1/2]
coordT & orgQhull::QhullPoint::operator[] (int idx) inline
0 to hull_dim-1
References point_coordinates, point_dimension, and QHULL_ASSERT.
operator[]() [2/2]
const coordT & orgQhull::QhullPoint::operator[] (int idx) const inline
0 to hull_dim-1
References point_coordinates, point_dimension, and QHULL_ASSERT.
print()
PrintPoint orgQhull::QhullPoint::print (const char * message) const inline
{ return PrintPoint(message, false, *this); }
Referenced by operator<<(), operator<<(), operator<<(), orgQhull::QhullFacet_test::t_getSet(), and orgQhull::QhullPoint_test::t_io().
printWithIdentifier()
PrintPoint orgQhull::QhullPoint::printWithIdentifier (const char * message) const inline
{ return PrintPoint(message, true, *this); }
Referenced by operator<<(), and orgQhull::QhullPoint_test::t_io().
qh()
QhullQh * orgQhull::QhullPoint::qh () inline
{ return qh_qh; }
References qh_qh.
Referenced by orgQhull::QhullPoint_test::t_construct(), and orgQhull::QhullPoint_test::t_readonly().
setCoordinates()
void orgQhull::QhullPoint::setCoordinates (coordT * c) inline
{ point_coordinates= c; }
References point_coordinates.
Referenced by orgQhull::QhullPoint_test::t_define().
setDimension()
void orgQhull::QhullPoint::setDimension (int pointDimension) inline
{ point_dimension= pointDimension; }
References point_dimension.
Referenced by orgQhull::Qhull::inputOrigin(), and orgQhull::QhullPoint_test::t_define().
size()
size_t orgQhull::QhullPoint::size () inline
{ return (size_t)(point_coordinates ? point_dimension : 0); }
References point_coordinates, and point_dimension.
toStdVector()
std::vector< coordT > orgQhull::QhullPoint::toStdVector () const
{
    QhullPointIterator i(*this);
    std::vector<coordT> vs;
    while(i.hasNext()){
        vs.push_back(i.next());
    }
    return vs;
}//toStdVector
Referenced by orgQhull::QhullPoint_test::t_convert().
Member Data Documentation
point_coordinates
coordT* orgQhull::QhullPoint::point_coordinates protected
Pointer to first coordinate, 0 if undefined.
Referenced by advancePoint(), begin(), begin(), constBegin(), constEnd(), coordinates(), coordinates(), count(), defineAs(), defineAs(), defineAs(), distance(), end(), end(), getBaseT(), id(), isValid(), orgQhull::QhullPoints::const_iterator::operator-(), orgQhull::QhullPoints::iterator::operator-(), orgQhull::QhullPoints::const_iterator::operator<(), orgQhull::QhullPoints::iterator::operator<(), orgQhull::QhullPoints::const_iterator::operator<=(), orgQhull::QhullPoints::iterator::operator<=(), operator=(), orgQhull::QhullPoints::const_iterator::operator==(), orgQhull::QhullPoints::iterator::operator==(), operator==(), orgQhull::QhullPoints::iterator::operator==(), orgQhull::QhullPoints::const_iterator::operator>(), orgQhull::QhullPoints::iterator::operator>(), orgQhull::QhullPoints::iterator::operator>(), orgQhull::QhullPoints::const_iterator::operator>=(), orgQhull::QhullPoints::iterator::operator>=(), orgQhull::QhullPoints::iterator::operator>=(), operator[](), operator[](), setCoordinates(), and size().
point_dimension
int orgQhull::QhullPoint::point_dimension protected
Default dimension is qh_qh->hull_dim.
Referenced by advancePoint(), constEnd(), count(), defineAs(), defineAs(), defineAs(), dimension(), distance(), end(), end(), isValid(), orgQhull::QhullPoints::const_iterator::operator-(), orgQhull::QhullPoints::iterator::operator-(), operator=(), orgQhull::QhullPoints::const_iterator::operator==(), orgQhull::QhullPoints::iterator::operator==(), operator==(), orgQhull::QhullPoints::iterator::operator==(), operator[](), operator[](), setDimension(), and size().
qh_qh
QhullQh* orgQhull::QhullPoint::qh_qh protected
qhT for this instance of Qhull. 0 if undefined. operator==() returns true if points within sqrt(qh_qh->distanceEpsilon()) If !qh_qh, id() is -3, and operator==() requires equal coordinates
Referenced by defineAs(), id(), orgQhull::QhullPoints::const_iterator::operator-(), orgQhull::QhullPoints::iterator::operator-(), orgQhull::QhullPoints::const_iterator::operator<(), orgQhull::QhullPoints::iterator::operator<(), orgQhull::QhullPoints::iterator::operator<(), orgQhull::QhullPoints::const_iterator::operator<=(), orgQhull::QhullPoints::iterator::operator<=(), orgQhull::QhullPoints::iterator::operator<=(), operator=(), orgQhull::QhullPoints::const_iterator::operator==(), orgQhull::QhullPoints::iterator::operator==(), operator==(), orgQhull::QhullPoints::iterator::operator==(), orgQhull::QhullPoints::const_iterator::operator>(), orgQhull::QhullPoints::iterator::operator>(), orgQhull::QhullPoints::iterator::operator>(), orgQhull::QhullPoints::const_iterator::operator>=(), orgQhull::QhullPoints::iterator::operator>=(), orgQhull::QhullPoints::iterator::operator>=(), and qh().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullPoint.h
src/qhull/src/libqhullcpp/QhullPoint.cpp