OrcaSlicer: Slic3r::GUI::GLGizmoPainterBase Class Reference
Slic3r::GUI::GLGizmoPainterBase Class Reference abstract
#include <src/slic3r/GUI/Gizmos/GLGizmoPainterBase.hpp>
Classes
struct ClippingPlaneDataWrapper
struct CutContours
struct ProjectedHeightRange
struct ProjectedMousePosition
struct RaycastResult
Public Types
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoPainterBase (GLCanvas3D &parent, const std::string &icon_filename, unsigned int sprite_id)
~GLGizmoPainterBase () override=default
virtual void set_painter_gizmo_data (const Selection &selection)
virtual bool gizmo_event (SLAGizmoEventType action, const Vec2d &mouse_position, bool shift_down, bool alt_down, bool control_down)
virtual void render_painter_gizmo () const =0
virtual const float get_cursor_radius_min () const
virtual const float get_cursor_radius_max () const
virtual const float get_cursor_radius_step () const
virtual const float get_cursor_height_min () const
virtual const float get_cursor_height_max () const
virtual const float get_cursor_height_step () const
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
int get_group_id () const
void set_group_id (int id)
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
void set_icon_filename (const std::string &filename)
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
virtual std::string get_gizmo_entering_text () const
virtual std::string get_gizmo_leaving_text () const
virtual std::string get_action_snapshot_name ()
void set_common_data_pool (CommonGizmosDataPool *ptr)
virtual bool apply_clipping_plane ()
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
void set_highlight_color (const std::array< float, 4 > &color)
void enable_grabber (unsigned int id)
void disable_grabber (unsigned int id)
void start_dragging ()
void stop_dragging ()
bool is_dragging () const
void update (const UpdateData &data)
bool update_items_state ()
void render ()
void render_for_picking ()
void render_input_window (float x, float y, float bottom_limit)
virtual void on_change_color_mode (bool is_dark)
virtual std::string get_tooltip () const
int get_count ()
std::string get_gizmo_name ()
Static Public Member Functions
static void update_render_colors ()
static void load_render_colors ()
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static float INV_ZOOM = 1.0f
static std::array< float, 4 > DEFAULT_BASE_COLOR = { 0.625f, 0.625f, 0.625f, 1.0f }
static std::array< float, 4 > DEFAULT_DRAG_COLOR = { 1.0f, 1.0f, 1.0f, 1.0f }
static std::array< float, 4 > DEFAULT_HIGHLIGHT_COLOR = { 1.0f, 0.38f, 0.0f, 1.0f }
static std::array< std::array< float, 4 >, 3 > AXES_COLOR
static std::array< std::array< float, 4 >, 3 > AXES_HOVER_COLOR
static std::array< float, 4 > CONSTRAINED_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f }
static std::array< float, 4 > FLATTEN_COLOR = { 0.96f, 0.93f, 0.93f, 0.5f }
static std::array< float, 4 > FLATTEN_HOVER_COLOR = { 1.0f, 1.0f, 1.0f, 0.75f }
static std::array< float, 4 > GRABBER_NORMAL_COL = {1.0f, 1.0f, 1.0f, 1.0f}
static std::array< float, 4 > GRABBER_HOVER_COL = {0.863f, 0.125f, 0.063f, 1.0f}
static std::array< float, 4 > GRABBER_UNIFORM_COL = {0, 1.0, 1.0, 1.0f}
static std::array< float, 4 > GRABBER_UNIFORM_HOVER_COL = {0, 0.7, 0.7, 1.0f}
Protected Types
enum class ToolType { BRUSH , BUCKET_FILL , SMART_FILL , GAP_FILL }
enum class Button { None , Left , Right }
Protected Member Functions
virtual void render_triangles (const Selection &selection) const
void render_cursor () const
void render_cursor_circle () const
void render_cursor_sphere (const Transform3d &trafo) const
void render_cursor_height_range (const Transform3d &trafo) const
virtual void update_model_object ()=0
virtual void update_from_model_object (bool first_update)=0
virtual std::array< float, 4 > get_cursor_sphere_left_button_color () const
virtual std::array< float, 4 > get_cursor_sphere_right_button_color () const
virtual std::array< float, 4 > get_cursor_hover_color () const
virtual EnforcerBlockerType get_left_button_state_type () const
virtual EnforcerBlockerType get_right_button_state_type () const
ClippingPlaneDataWrapper get_clipping_plane_data () const
TriangleSelector::ClippingPlane get_clipping_plane_in_volume_coordinates (const Transform3d &trafo) const
void on_set_state () override
void on_start_dragging () override
void on_stop_dragging () override
virtual void on_opening ()=0
virtual void on_shutdown ()=0
virtual PainterGizmoType get_painter_type () const =0
bool on_is_activable () const override
bool on_is_selectable () const override
void on_load (cereal::BinaryInputArchive &ar) override
void on_save (cereal::BinaryOutputArchive &ar) const override
CommonGizmosDataID on_get_requirements () const override
bool wants_enter_leave_snapshots () const override
virtual wxString handle_snapshot_action_name (bool shift_down, Button button_down) const =0
virtual bool on_init ()=0
virtual std::string on_get_name () const =0
virtual void on_set_hover_id ()
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
virtual void on_update (const UpdateData &data)
virtual void on_render_input_window (float x, float y, float bottom_limit)
bool GizmoImguiBegin (const std::string &name, int flags)
void GizmoImguiEnd ()
void GizmoImguiSetNextWIndowPos (float &x, float y, int flag, float pivot_x=0.0f, float pivot_y=0.0f)
std::array< float, 4 > picking_color_component (unsigned int id) const
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers_for_picking (const BoundingBoxf3 &box) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
Protected Attributes
float m_cursor_radius = 1.f
float m_cursor_height = 0.2f
std::vector< std::unique_ptr< TriangleSelectorGUI > > m_triangle_selectors
TriangleSelector::CursorType m_cursor_type = TriangleSelector::SPHERE
bool m_triangle_splitting_enabled = true
ToolType m_tool_type = ToolType::BRUSH
float m_smart_fill_angle = 30.f
bool m_paint_on_overhangs_only = false
float m_highlight_by_angle_threshold_deg = 0.f
int m_seed_fill_last_mesh_id = -1
GLCanvas3D & m_parent
int m_group_id
EState m_state
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id
bool m_dragging
std::array< float, 4 > m_base_color
std::array< float, 4 > m_drag_color
std::array< float, 4 > m_highlight_color
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render
std::string m_tooltip
CommonGizmosDataPool * m_c
GLModel m_cone
GLModel m_cylinder
GLModel m_sphere
bool m_is_dark_mode = false
float last_input_window_width = 0
Static Protected Attributes
static constexpr float CursorRadiusMin = 0.4f
static constexpr float CursorRadiusMax = 8.f
static constexpr float CursorRadiusStep = 0.2f
static constexpr float CursorHeightMin = 0.1f
static constexpr float CursorHeightMax = 8.f
static constexpr float CursorHeightStep = 0.2f
static constexpr float SmartFillAngleMin = 0.0f
static constexpr float SmartFillAngleMax = 90.f
static constexpr float SmartFillAngleStep = 1.f
Private Member Functions
void on_render () override
void on_render_for_picking () override
std::vector< std::vector< ProjectedMousePosition > > get_projected_mouse_positions (const Vec2d &mouse_position, double resolution, const std::vector< Transform3d > &trafo_matrices) const
std::vector< ProjectedHeightRange > get_projected_height_range (const Vec2d &mouse_position, double resolution, const std::vector< const ModelVolume * > &part_volumes, const std::vector< Transform3d > &trafo_matrices) const
bool is_mesh_point_clipped (const Vec3d &point, const Transform3d &trafo) const
void update_raycast_cache (const Vec2d &mouse_position, const Camera &camera, const std::vector< Transform3d > &trafo_matrices) const
BoundingBoxf3 bounding_box () const
void update_contours (const TriangleMesh &vol_mesh, float cursor_z, float max_z, float min_z) const
Private Attributes
ObjectID m_old_mo_id
size_t m_old_volumes_size = 0
GLIndexedVertexArray m_vbo_sphere
bool m_internal_stack_active = false
bool m_schedule_update = false
Vec2d m_last_mouse_click = Vec2d::Zero()
Button m_button_down = Button::None
EState m_old_state = Off
RaycastResult m_rr
CutContours m_cut_contours
bool m_dirty
int count = 0
Friends
class ::Slic3r::GUI::GLGizmoMmuSegmentation
Detailed Description
Class Documentation
Slic3r::GUI::GLGizmoPainterBase::ClippingPlaneDataWrapper
struct Slic3r::GUI::GLGizmoPainterBase::ClippingPlaneDataWrapper
Class Members
array< float, 4 > clp_dataf
array< float, 2 > z_range
Slic3r::GUI::GLGizmoPainterBase::CutContours
struct Slic3r::GUI::GLGizmoPainterBase::CutContours
Class Members
GLModel contours
double cut_z { 0.0 }
int instance_idx { -1 }
TriangleMesh mesh
ObjectID object_id
Vec3d position { Vec3d::Zero() }
Vec3d shift { Vec3d::Zero() }
Slic3r::GUI::GLGizmoPainterBase::ProjectedHeightRange
struct Slic3r::GUI::GLGizmoPainterBase::ProjectedHeightRange
Class Members
size_t first_facet_idx
int mesh_idx
float z_world
Slic3r::GUI::GLGizmoPainterBase::ProjectedMousePosition
struct Slic3r::GUI::GLGizmoPainterBase::ProjectedMousePosition
Class Members
size_t facet_idx
Vec3f mesh_hit
int mesh_idx
Slic3r::GUI::GLGizmoPainterBase::RaycastResult
struct Slic3r::GUI::GLGizmoPainterBase::RaycastResult
Class Members
size_t facet
Vec3f hit
int mesh_id
Vec2d mouse_position
Member Enumeration Documentation
Button
enum class Slic3r::GUI::GLGizmoPainterBase::Button strong protected
Enumerator
None
Left
Right
                      {
        None,
        Left,
        Right
    };
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
ToolType
enum class Slic3r::GUI::GLGizmoPainterBase::ToolType strong protected
Enumerator
BRUSH
BUCKET_FILL
SMART_FILL
GAP_FILL
{
        BRUSH,
        BUCKET_FILL,
        SMART_FILL,
        // BBS
        GAP_FILL,
    };
Constructor & Destructor Documentation
GLGizmoPainterBase()
Slic3r::GUI::GLGizmoPainterBase::GLGizmoPainterBase (GLCanvas3D & parent, const std::string & icon_filename, unsigned int sprite_id)
    : GLGizmoBase(parent, icon_filename, sprite_id)
{
    // Make sphere and save it into a vertex buffer.
    m_vbo_sphere.load_its_flat_shading(its_make_sphere(1., (2*M_PI)/24.));
    m_vbo_sphere.finalize_geometry(true);
}
References Slic3r::GLIndexedVertexArray::finalize_geometry(), Slic3r::its_make_sphere(), Slic3r::GLIndexedVertexArray::load_its_flat_shading(), M_PI, and m_vbo_sphere.
~GLGizmoPainterBase()
Slic3r::GUI::GLGizmoPainterBase::~GLGizmoPainterBase () override default
Member Function Documentation
apply_clipping_plane()
virtual bool Slic3r::GUI::GLGizmoBase::apply_clipping_plane () inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut.
{ return true; }
Referenced by Slic3r::GUI::GLCanvas3D::_render_objects().
bounding_box()
BoundingBoxf3 Slic3r::GUI::GLGizmoPainterBase::bounding_box () const private
{
    BoundingBoxf3 ret;
    const Selection& selection = m_parent.get_selection();
    const Selection::IndicesList& idxs = selection.get_volume_idxs();
    for (unsigned int i : idxs) {
        const GLVolume* volume = selection.get_volume(i);
        if (!volume->is_modifier)
            ret.merge(volume->transformed_convex_hull_bounding_box());
    }
    return ret;
}
References Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::BoundingBox3Base< PointClass >::merge().
Referenced by render_cursor_height_range().
disable_grabber()
void Slic3r::GUI::GLGizmoBase::disable_grabber (unsigned int id) inherited
{
    if (id < m_grabbers.size())
        m_grabbers[id].enabled = false;
    on_disable_grabber(id);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_disable_grabber().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_disable_grabber().
enable_grabber()
void Slic3r::GUI::GLGizmoBase::enable_grabber (unsigned int id) inherited
{
    if (id < m_grabbers.size())
        m_grabbers[id].enabled = true;
    on_enable_grabber(id);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_enable_grabber().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_enable_grabber().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), and Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
get_action_snapshot_name()
virtual std::string Slic3r::GUI::GLGizmoBase::get_action_snapshot_name () inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{ return "Gizmo action"; }
Referenced by Slic3r::GUI::Plater::priv::take_snapshot().
get_clipping_plane_data()
GLGizmoPainterBase::ClippingPlaneDataWrapper Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data () const protected
{
    ClippingPlaneDataWrapper clp_data_out{{0.f, 0.f, 1.f, FLT_MAX}, {-FLT_MAX, FLT_MAX}};
    // Take care of the clipping plane. The normal of the clipping plane is
    // saved with opposite sign than we need to pass to OpenGL (FIXME)
    if (bool clipping_plane_active = m_c->object_clipper()->get_position() != 0.; clipping_plane_active) {
        const ClippingPlane *clp = m_c->object_clipper()->get_clipping_plane();
        for (size_t i = 0; i < 3; ++i)
            clp_data_out.clp_dataf[i] = -1.f * float(clp->get_data()[i]);
        clp_data_out.clp_dataf[3] = float(clp->get_data()[3]);
    }
    // z_range is calculated in the same way as in GLCanvas3D::_render_objects(GLVolumeCollection::ERenderType type)
    if (m_c->get_canvas()->get_use_clipping_planes()) {
        const std::array<ClippingPlane, 2> &clps = m_c->get_canvas()->get_clipping_planes();
        clp_data_out.z_range                     = {float(-clps[0].get_data()[3]), float(clps[1].get_data()[3])};
    }
    return clp_data_out;
}
References Slic3r::GUI::CommonGizmosDataPool::get_canvas(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::GLCanvas3D::get_clipping_planes(), Slic3r::GUI::ClippingPlane::get_data(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::GLCanvas3D::get_use_clipping_planes(), Slic3r::GUI::GLGizmoBase::m_c, and Slic3r::GUI::CommonGizmosDataPool::object_clipper().
Referenced by render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), and Slic3r::GUI::GLGizmoSeam::render_triangles().
get_clipping_plane_in_volume_coordinates()
TriangleSelector::ClippingPlane Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates (const Transform3d & trafo) const protected
{
    const ::Slic3r::GUI::ClippingPlane *const clipping_plane = m_c->object_clipper()->get_clipping_plane();
    if (clipping_plane == nullptr || !clipping_plane->is_active())
        return {};
    const Vec3d  clp_normal = clipping_plane->get_normal();
    const double clp_offset = clipping_plane->get_offset();
    const Transform3d trafo_normal = Transform3d(trafo.linear().transpose());
    const Transform3d trafo_inv    = trafo.inverse();
    Vec3d point_on_plane             = clp_normal * clp_offset;
    Vec3d point_on_plane_transformed = trafo_inv * point_on_plane;
    Vec3d normal_transformed         = trafo_normal * clp_normal;
    auto offset_transformed          = float(point_on_plane_transformed.dot(normal_transformed));
    return TriangleSelector::ClippingPlane({float(normal_transformed.x()), float(normal_transformed.y()), float(normal_transformed.z()), offset_transformed});
}
References Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::linear(), Slic3r::GUI::GLGizmoBase::m_c, and Slic3r::GUI::CommonGizmosDataPool::object_clipper().
Referenced by gizmo_event().
get_count()
int Slic3r::GUI::GLGizmoBase::get_count () inline inherited
{ return ++count; }
References Slic3r::GUI::GLGizmoBase::count.
get_cursor_height_max()
virtual const float Slic3r::GUI::GLGizmoPainterBase::get_cursor_height_max () const inline virtual
{ return CursorHeightMax; }
References CursorHeightMax.
Referenced by gizmo_event().
get_cursor_height_min()
virtual const float Slic3r::GUI::GLGizmoPainterBase::get_cursor_height_min () const inline virtual
{ return CursorHeightMin; }
References CursorHeightMin.
Referenced by gizmo_event().
get_cursor_height_step()
virtual const float Slic3r::GUI::GLGizmoPainterBase::get_cursor_height_step () const inline virtual
{ return CursorHeightStep; }
References CursorHeightStep.
Referenced by gizmo_event().
get_cursor_hover_color()
virtual std::array< float, 4 > Slic3r::GUI::GLGizmoPainterBase::get_cursor_hover_color () const inline protected virtual
Reimplemented in Slic3r::GUI::GLGizmoMmuSegmentation.
{ return { 0.f, 0.f, 0.f, 0.25f }; }
Referenced by render_cursor_circle(), and render_cursor_sphere().
get_cursor_radius_max()
virtual const float Slic3r::GUI::GLGizmoPainterBase::get_cursor_radius_max () const inline virtual
{ return CursorRadiusMax; }
References CursorRadiusMax.
Referenced by gizmo_event().
get_cursor_radius_min()
virtual const float Slic3r::GUI::GLGizmoPainterBase::get_cursor_radius_min () const inline virtual
Reimplemented in Slic3r::GUI::GLGizmoMmuSegmentation.
{ return CursorRadiusMin; }
References CursorRadiusMin.
Referenced by gizmo_event().
get_cursor_radius_step()
virtual const float Slic3r::GUI::GLGizmoPainterBase::get_cursor_radius_step () const inline virtual
{ return CursorRadiusStep; }
References CursorRadiusStep.
Referenced by gizmo_event().
get_cursor_sphere_left_button_color()
virtual std::array< float, 4 > Slic3r::GUI::GLGizmoPainterBase::get_cursor_sphere_left_button_color () const inline protected virtual
{ return {0.f, 0.f, 1.f, 0.25f}; }
Referenced by render_cursor_circle(), and render_cursor_sphere().
get_cursor_sphere_right_button_color()
virtual std::array< float, 4 > Slic3r::GUI::GLGizmoPainterBase::get_cursor_sphere_right_button_color () const inline protected virtual
{ return {1.f, 0.f, 0.f, 0.25f}; }
Referenced by render_cursor_circle(), and render_cursor_sphere().
get_gizmo_entering_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_entering_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
get_gizmo_leaving_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_leaving_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
get_gizmo_name()
std::string Slic3r::GUI::GLGizmoBase::get_gizmo_name () inline inherited
{ return on_get_name(); }
References Slic3r::GUI::GLGizmoBase::on_get_name().
get_group_id()
int Slic3r::GUI::GLGizmoBase::get_group_id () const inline inherited
{ return m_group_id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), and Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers().
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmoText::gizmo_event().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_left_button_state_type()
virtual EnforcerBlockerType Slic3r::GUI::GLGizmoPainterBase::get_left_button_state_type () const inline protected virtual
Reimplemented in Slic3r::GUI::GLGizmoMmuSegmentation.
{ return EnforcerBlockerType::ENFORCER; }
References Slic3r::ENFORCER.
Referenced by gizmo_event().
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    int key = get_shortcut_key();
    std::string out = on_get_name();
    if (include_shortcut && key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z)
        out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::on_get_name(), and out.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), and Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window().
get_painter_type()
virtual PainterGizmoType Slic3r::GUI::GLGizmoPainterBase::get_painter_type () const protected pure virtual
Implemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
get_projected_height_range()
std::vector< GLGizmoPainterBase::ProjectedHeightRange > Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range (const Vec2d & mouse_position, double resolution, const std::vector< const ModelVolume * > & part_volumes, const std::vector< Transform3d > & trafo_matrices) const private
{
    std::vector<GLGizmoPainterBase::ProjectedHeightRange> hit_triangles_by_mesh;
    const Camera& camera = wxGetApp().plater()->get_camera();
    // In mesh_hit_points only the last item could have mesh_id == -1, any other items mustn't.
    update_raycast_cache(mouse_position, camera, trafo_matrices);
    if (m_rr.mesh_id == -1)
        return hit_triangles_by_mesh;
    ProjectedMousePosition mesh_hit_point = { m_rr.hit, m_rr.mesh_id, m_rr.facet };
    float z_bot_world= (trafo_matrices[m_rr.mesh_id] * Vec3d(m_rr.hit(0), m_rr.hit(1), m_rr.hit(2))).z();
    float z_top_world = z_bot_world+ m_cursor_height;
    hit_triangles_by_mesh.push_back({ z_bot_world, m_rr.mesh_id, size_t(m_rr.facet) });
    const Selection& selection = m_parent.get_selection();
    const ModelObject* mo = m_c->selection_info()->model_object();
    const ModelInstance* mi = mo->instances[selection.get_instance_idx()];
    const Transform3d   instance_trafo = m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
        mi->get_assemble_transformation().get_matrix() :
        mi->get_transformation().get_matrix();
    const Transform3d   instance_trafo_not_translate = m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
        mi->get_assemble_transformation().get_matrix(true) :
        mi->get_transformation().get_matrix(true);
    for (int mesh_idx = 0; mesh_idx < part_volumes.size(); mesh_idx++) {
        if (mesh_idx == m_rr.mesh_id)
            continue;
        const Transform3d& trafo = trafo_matrices[mesh_idx];
        const indexed_triangle_set& its = part_volumes[mesh_idx]->mesh().its;
        int first_hit_facet_idx = -1;
        for (int facet_idx = 0; facet_idx < its.indices.size(); facet_idx++) {
            stl_vertex v0 = its.vertices[its.indices[facet_idx].x()];
            stl_vertex v1 = its.vertices[its.indices[facet_idx].y()];
            stl_vertex v2 = its.vertices[its.indices[facet_idx].z()];
            float v0_z = (trafo * Vec3d(v0(0), v0(1), v0(2))).z();
            float v1_z = (trafo * Vec3d(v1(0), v1(1), v1(2))).z();
            float v2_z = (trafo * Vec3d(v2(0), v2(1), v2(2))).z();
            bool outside_range = (v0_z < z_bot_world&& v1_z < z_bot_world&& v2_z < z_bot_world) ||
                                 (v0_z > z_top_world && v1_z > z_top_world && v2_z > z_top_world);
            if (!outside_range) {
                first_hit_facet_idx = facet_idx;
                break;
            }
        }
        if (first_hit_facet_idx != -1) {
            hit_triangles_by_mesh.push_back({ z_bot_world, mesh_idx, (size_t)first_hit_facet_idx });
        }
    }
    return hit_triangles_by_mesh;
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::facet, Slic3r::ModelInstance::get_assemble_transformation(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::ModelInstance::get_transformation(), Slic3r::GUI::GLGizmoPainterBase::RaycastResult::hit, indexed_triangle_set::indices, Slic3r::ModelObject::instances, Slic3r::GUI::GLGizmoBase::m_c, m_cursor_height, Slic3r::GUI::GLGizmoBase::m_parent, m_rr, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::mesh_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), update_raycast_cache(), and indexed_triangle_set::vertices.
Referenced by gizmo_event().
get_projected_mouse_positions()
std::vector< std::vector< GLGizmoPainterBase::ProjectedMousePosition > > Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions (const Vec2d & mouse_position, double resolution, const std::vector< Transform3d > & trafo_matrices) const private
{
    // List of mouse positions that will be used as seeds for painting.
    std::vector<Vec2d> mouse_positions{mouse_position};
    if (m_last_mouse_click != Vec2d::Zero()) {
        // In case current mouse position is far from the last one,
        // add several positions from between into the list, so there
        // are no gaps in the painted region.
        if (size_t patches_in_between = size_t((mouse_position - m_last_mouse_click).norm() / resolution); patches_in_between > 0) {
            const Vec2d diff = (m_last_mouse_click - mouse_position) / (patches_in_between + 1);
            for (size_t patch_idx = 1; patch_idx <= patches_in_between; ++patch_idx)
                mouse_positions.emplace_back(mouse_position + patch_idx * diff);
            mouse_positions.emplace_back(m_last_mouse_click);
        }
    }
    const Camera                       &camera = wxGetApp().plater()->get_camera();
    std::vector<ProjectedMousePosition> mesh_hit_points;
    mesh_hit_points.reserve(mouse_positions.size());
    // In mesh_hit_points only the last item could have mesh_id == -1, any other items mustn't.
    for (const Vec2d &mp : mouse_positions) {
        update_raycast_cache(mp, camera, trafo_matrices);
        mesh_hit_points.push_back({m_rr.hit, m_rr.mesh_id, m_rr.facet});
        if (m_rr.mesh_id == -1)
            break;
    }
    // Divide mesh_hit_points into groups with the same mesh_idx. It may contain multiple groups with the same mesh_idx.
    std::vector<std::vector<ProjectedMousePosition>> mesh_hit_points_by_mesh;
    for (size_t prev_mesh_hit_point = 0, curr_mesh_hit_point = 0; curr_mesh_hit_point < mesh_hit_points.size(); ++curr_mesh_hit_point) {
        size_t next_mesh_hit_point = curr_mesh_hit_point + 1;
        if (next_mesh_hit_point >= mesh_hit_points.size() || mesh_hit_points[curr_mesh_hit_point].mesh_idx != mesh_hit_points[next_mesh_hit_point].mesh_idx) {
            mesh_hit_points_by_mesh.emplace_back();
            mesh_hit_points_by_mesh.back().insert(mesh_hit_points_by_mesh.back().end(), mesh_hit_points.begin() + int(prev_mesh_hit_point), mesh_hit_points.begin() + int(next_mesh_hit_point));
            prev_mesh_hit_point = next_mesh_hit_point;
        }
    }
    auto on_same_facet = [](std::vector<ProjectedMousePosition> &hit_points) -> bool {
        for (const ProjectedMousePosition &mesh_hit_point : hit_points)
            if (mesh_hit_point.facet_idx != hit_points.front().facet_idx)
                return false;
        return true;
    };
    struct Plane
    {
        Vec3d origin;
        Vec3d first_axis;
        Vec3d second_axis;
    };
    auto find_plane = [](std::vector<ProjectedMousePosition> &hit_points) -> std::optional<Plane> {
        assert(hit_points.size() >= 3);
        for (size_t third_idx = 2; third_idx < hit_points.size(); ++third_idx) {
            const Vec3d &first_point  = hit_points[third_idx - 2].mesh_hit.cast<double>();
            const Vec3d &second_point = hit_points[third_idx - 1].mesh_hit.cast<double>();
            const Vec3d &third_point  = hit_points[third_idx].mesh_hit.cast<double>();
            const Vec3d  first_vec    = first_point - second_point;
            const Vec3d  second_vec   = third_point - second_point;
            // If three points aren't collinear, then there exists only one plane going through all points.
            if (first_vec.cross(second_vec).squaredNorm() > sqr(EPSILON)) {
                const Vec3d first_axis_vec_n = first_vec.normalized();
                // Make second_vec perpendicular to first_axis_vec_n using GramSchmidt orthogonalization process
                const Vec3d second_axis_vec_n = (second_vec - (first_vec.dot(second_vec) / first_vec.dot(first_vec)) * first_vec).normalized();
                return Plane{second_point, first_axis_vec_n, second_axis_vec_n};
            }
        }
        return std::nullopt;
    };
    for(std::vector<ProjectedMousePosition> &hit_points : mesh_hit_points_by_mesh) {
        assert(!hit_points.empty());
        if (hit_points.back().mesh_idx == -1)
            break;
        if (hit_points.size() <= 2)
            continue;
        if (on_same_facet(hit_points)) {
            hit_points = {hit_points.front(), hit_points.back()};
        } else if (std::optional<Plane> plane = find_plane(hit_points); plane) {
            Polyline polyline;
            polyline.points.reserve(hit_points.size());
            // Project hit_points into its plane to simplified them in the next step.
            for (auto &hit_point : hit_points) {
                const Vec3d &point  = hit_point.mesh_hit.cast<double>();
                const double x_cord = plane->first_axis.dot(point - plane->origin);
                const double y_cord = plane->second_axis.dot(point - plane->origin);
                polyline.points.emplace_back(scale_(x_cord), scale_(y_cord));
            }
            polyline.simplify(scale_(m_cursor_radius) / 10.);
            const int                           mesh_idx = hit_points.front().mesh_idx;
            std::vector<ProjectedMousePosition> new_hit_points;
            new_hit_points.reserve(polyline.points.size());
            // Project 2D simplified hit_points beck to 3D.
            for (const Point &point : polyline.points) {
                const double x_cord        = unscale<double>(point.x());
                const double y_cord        = unscale<double>(point.y());
                const Vec3d  new_hit_point = plane->origin + x_cord * plane->first_axis + y_cord * plane->second_axis;
                const int    facet_idx     = m_c->raycaster()->raycasters()[mesh_idx]->get_closest_facet(new_hit_point.cast<float>());
                new_hit_points.push_back({new_hit_point.cast<float>(), mesh_idx, size_t(facet_idx)});
            }
            hit_points = new_hit_points;
        } else {
            hit_points = {hit_points.front(), hit_points.back()};
        }
    }
    return mesh_hit_points_by_mesh;
}
References Slic3r::diff(), EPSILON, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::facet, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::hit, Slic3r::GUI::GLGizmoBase::m_c, m_cursor_radius, m_last_mouse_click, m_rr, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::mesh_id, Slic3r::MultiPoint::points, Slic3r::GUI::CommonGizmosDataPool::raycaster(), Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycasters(), scale_, Slic3r::Polyline::simplify(), Slic3r::sqr(), and update_raycast_cache().
Referenced by gizmo_event().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_right_button_state_type()
virtual EnforcerBlockerType Slic3r::GUI::GLGizmoPainterBase::get_right_button_state_type () const inline protected virtual
Reimplemented in Slic3r::GUI::GLGizmoMmuSegmentation.
{ return EnforcerBlockerType::BLOCKER; }
References Slic3r::BLOCKER.
Referenced by gizmo_event().
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_state(), Slic3r::GUI::GLGizmoCut::on_set_state(), Slic3r::GUI::GLGizmoFaceDetector::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), and Slic3r::GUI::GLGizmoSeam::on_set_state().
get_tooltip()
virtual std::string Slic3r::GUI::GLGizmoBase::get_tooltip () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoScale3D.
{ return ""; }
gizmo_event()
bool Slic3r::GUI::GLGizmoPainterBase::gizmo_event (SLAGizmoEventType action, const Vec2d & mouse_position, bool shift_down, bool alt_down, bool control_down) virtual
{
    if (action == SLAGizmoEventType::MouseWheelUp
     || action == SLAGizmoEventType::MouseWheelDown) {
        if (control_down) {
            //BBS
            if (m_tool_type == ToolType::BRUSH && m_cursor_type == TriangleSelector::CursorType::HEIGHT_RANGE) {
                m_cursor_height = action == SLAGizmoEventType::MouseWheelDown ? std::max(m_cursor_height - this->get_cursor_height_step(), this->get_cursor_height_min()) :
                                                                                std::min(m_cursor_height + this->get_cursor_height_step(), this->get_cursor_height_max());
                m_parent.set_as_dirty();
                return true;
            }
            if (m_tool_type == ToolType::BRUSH && (m_cursor_type == TriangleSelector::CursorType::SPHERE || m_cursor_type == TriangleSelector::CursorType::CIRCLE)) {
                m_cursor_radius = action == SLAGizmoEventType::MouseWheelDown ? std::max(m_cursor_radius - this->get_cursor_radius_step(), this->get_cursor_radius_min()) :
                                                                                std::min(m_cursor_radius + this->get_cursor_radius_step(), this->get_cursor_radius_max());
                m_parent.set_as_dirty();
                return true;
            }
            if (m_tool_type == ToolType::BUCKET_FILL || m_tool_type == ToolType::SMART_FILL) {
                m_smart_fill_angle = action == SLAGizmoEventType::MouseWheelDown ? std::max(m_smart_fill_angle - SmartFillAngleStep, SmartFillAngleMin)
                                                                                : std::min(m_smart_fill_angle + SmartFillAngleStep, SmartFillAngleMax);
                m_parent.set_as_dirty();
                if (m_rr.mesh_id != -1) {
                    const Selection     &selection                 = m_parent.get_selection();
                    const ModelObject   *mo                        = m_c->selection_info()->model_object();
                    const ModelInstance *mi                        = mo->instances[selection.get_instance_idx()];
                    const Transform3d   trafo_matrix_not_translate = m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
                        mi->get_assemble_transformation().get_matrix(true) * mo->volumes[m_rr.mesh_id]->get_matrix(true) :
                        mi->get_transformation().get_matrix(true) * mo->volumes[m_rr.mesh_id]->get_matrix(true);
                    const Transform3d   trafo_matrix = m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
                        mi->get_assemble_transformation().get_matrix() * mo->volumes[m_rr.mesh_id]->get_matrix() :
                        mi->get_transformation().get_matrix() * mo->volumes[m_rr.mesh_id]->get_matrix();
                    m_triangle_selectors[m_rr.mesh_id]->seed_fill_select_triangles(m_rr.hit, int(m_rr.facet), trafo_matrix_not_translate, this->get_clipping_plane_in_volume_coordinates(trafo_matrix), m_smart_fill_angle,
                                                                                   m_paint_on_overhangs_only ? m_highlight_by_angle_threshold_deg : 0.f, true);
                    m_triangle_selectors[m_rr.mesh_id]->request_update_render_data();
                    m_seed_fill_last_mesh_id = m_rr.mesh_id;
                }
                return true;
            }
            if (m_tool_type == ToolType::GAP_FILL) {
                TriangleSelectorPatch::gap_area = action == SLAGizmoEventType::MouseWheelDown ?
                    std::max(TriangleSelectorPatch::gap_area - TriangleSelectorPatch::GapAreaStep, TriangleSelectorPatch::GapAreaMin) :
                    std::min(TriangleSelectorPatch::gap_area + TriangleSelectorPatch::GapAreaStep, TriangleSelectorPatch::GapAreaMax);
                m_parent.set_as_dirty();
                return true;
            }
        }
        else if (alt_down) {
            // BBS
            double pos = m_c->object_clipper()->get_position();
            pos = action == SLAGizmoEventType::MouseWheelDown
                      ? std::max(0., pos - 0.01)
                      : std::min(1., pos + 0.01);
            m_c->object_clipper()->set_position(pos, true);
            return true;
        }
    }
    if (action == SLAGizmoEventType::ResetClippingPlane) {
        m_c->object_clipper()->set_position(-1., false);
        return true;
    }
    if (action == SLAGizmoEventType::LeftDown
     || action == SLAGizmoEventType::RightDown
    || (action == SLAGizmoEventType::Dragging && m_button_down != Button::None)) {
        if (m_triangle_selectors.empty())
            return false;
        EnforcerBlockerType new_state = EnforcerBlockerType::NONE;
        // BBS
        if (action == SLAGizmoEventType::Dragging) {
            if (m_button_down == Button::Right && this->get_right_button_state_type() == EnforcerBlockerType(-1))
                return false;
        }
        else {
            if (action == SLAGizmoEventType::RightDown && this->get_right_button_state_type() == EnforcerBlockerType(-1))
                return false;
        }
        if (! shift_down) {
            if (action == SLAGizmoEventType::Dragging)
                new_state = m_button_down == Button::Left ? this->get_left_button_state_type() : this->get_right_button_state_type();
            else
                new_state = action == SLAGizmoEventType::LeftDown ? this->get_left_button_state_type() : this->get_right_button_state_type();
        }
        const Camera        &camera                      = wxGetApp().plater()->get_camera();
        const Selection     &selection                   = m_parent.get_selection();
        const ModelObject   *mo                          = m_c->selection_info()->model_object();
        const ModelInstance *mi                          = mo->instances[selection.get_instance_idx()];
        Transform3d   instance_trafo = m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
            mi->get_assemble_transformation().get_matrix() :
            mi->get_transformation().get_matrix();
        Transform3d   instance_trafo_not_translate = m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
            mi->get_assemble_transformation().get_matrix(true) :
            mi->get_transformation().get_matrix(true);
        std::vector<const ModelVolume*> part_volumes;
        // Precalculate transformations of individual meshes.
        std::vector<Transform3d> trafo_matrices;
        std::vector<Transform3d> trafo_matrices_not_translate;
        for (const ModelVolume *mv : mo->volumes)
            if (mv->is_model_part()) {
                if (m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView) {
                    Transform3d temp = instance_trafo * mv->get_matrix();
                    temp.translate(mv->get_transformation().get_offset() * (GLVolume::explosion_ratio - 1.0) + mi->get_offset_to_assembly() * (GLVolume::explosion_ratio - 1.0));
                    trafo_matrices.emplace_back(temp);
                }
                else {
                    trafo_matrices.emplace_back(instance_trafo* mv->get_matrix());
                }
                trafo_matrices_not_translate.emplace_back(instance_trafo_not_translate * mv->get_matrix(true));
                part_volumes.push_back(mv);
            }
        // BBS
        if (m_tool_type == ToolType::BRUSH && m_cursor_type == TriangleSelector::CursorType::HEIGHT_RANGE)
        {
            std::vector<ProjectedHeightRange> projected_height_range_by_mesh = get_projected_height_range(mouse_position, 1., part_volumes, trafo_matrices);
            m_last_mouse_click = Vec2d::Zero();
            for (int i = 0; i < projected_height_range_by_mesh.size(); i++) {
                const ProjectedHeightRange& phr = projected_height_range_by_mesh[i];
                int mesh_idx = phr.mesh_idx;
                // The mouse button click detection is enabled when there is a valid hit.
                // Missing the object entirely
                // shall not capture the mouse.
                const bool dragging_while_painting = (action == SLAGizmoEventType::Dragging && m_button_down != Button::None);
                if (mesh_idx != -1 && m_button_down == Button::None)
                    m_button_down = ((action == SLAGizmoEventType::LeftDown) ? Button::Left : Button::Right);
                const Transform3d& trafo_matrix = trafo_matrices[mesh_idx];
                const Transform3d& trafo_matrix_not_translate = trafo_matrices_not_translate[mesh_idx];
                // Calculate direction from camera to the hit (in mesh coords):
                Vec3f camera_pos = (trafo_matrix.inverse() * camera.get_position()).cast<float>();
                const TriangleSelector::ClippingPlane& clp = this->get_clipping_plane_in_volume_coordinates(trafo_matrix);
                std::unique_ptr<TriangleSelector::Cursor> cursor = TriangleSelector::SinglePointCursor::cursor_factory(phr.z_world,
                    camera_pos, m_cursor_height, trafo_matrix, clp);
                m_triangle_selectors[mesh_idx]->select_patch(int(phr.first_facet_idx), std::move(cursor), new_state, trafo_matrix_not_translate,
                    m_triangle_splitting_enabled, m_paint_on_overhangs_only ? m_highlight_by_angle_threshold_deg : 0.f);
                m_triangle_selectors[mesh_idx]->request_update_render_data(true);
                m_last_mouse_click = mouse_position;
            }
            return true;
        }
        std::vector<std::vector<ProjectedMousePosition>> projected_mouse_positions_by_mesh = get_projected_mouse_positions(mouse_position, 1., trafo_matrices);
        m_last_mouse_click = Vec2d::Zero(); // only actual hits should be saved
        for (const std::vector<ProjectedMousePosition> &projected_mouse_positions : projected_mouse_positions_by_mesh) {
            assert(!projected_mouse_positions.empty());
            const int  mesh_idx                = projected_mouse_positions.front().mesh_idx;
            const bool dragging_while_painting = (action == SLAGizmoEventType::Dragging && m_button_down != Button::None);
            // The mouse button click detection is enabled when there is a valid hit.
            // Missing the object entirely
            // shall not capture the mouse.
            if (mesh_idx != -1)
                if (m_button_down == Button::None)
                    m_button_down = ((action == SLAGizmoEventType::LeftDown) ? Button::Left : Button::Right);
            // In case we have no valid hit, we can return. The event will be stopped when
            // dragging while painting (to prevent scene rotations and moving the object)
            if (mesh_idx == -1)
                return dragging_while_painting;
            const Transform3d &trafo_matrix               = trafo_matrices[mesh_idx];
            const Transform3d &trafo_matrix_not_translate = trafo_matrices_not_translate[mesh_idx];
            // Calculate direction from camera to the hit (in mesh coords):
            Vec3f camera_pos = (trafo_matrix.inverse() * camera.get_position()).cast<float>();
            assert(mesh_idx < int(m_triangle_selectors.size()));
            const TriangleSelector::ClippingPlane &clp = this->get_clipping_plane_in_volume_coordinates(trafo_matrix);
            if (m_tool_type == ToolType::SMART_FILL || m_tool_type == ToolType::BUCKET_FILL || (m_tool_type == ToolType::BRUSH && m_cursor_type == TriangleSelector::CursorType::POINTER)) {
                for(const ProjectedMousePosition &projected_mouse_position : projected_mouse_positions) {
                    assert(projected_mouse_position.mesh_idx == mesh_idx);
                    const Vec3f mesh_hit = projected_mouse_position.mesh_hit;
                    const int facet_idx = int(projected_mouse_position.facet_idx);
                    m_triangle_selectors[mesh_idx]->seed_fill_apply_on_triangles(new_state);
                    if (m_tool_type == ToolType::SMART_FILL)
                        m_triangle_selectors[mesh_idx]->seed_fill_select_triangles(mesh_hit, facet_idx, trafo_matrix_not_translate, clp, m_smart_fill_angle,
                                                                                       m_paint_on_overhangs_only ? m_highlight_by_angle_threshold_deg : 0.f, true);
                    else if (m_tool_type == ToolType::BRUSH && m_cursor_type == TriangleSelector::CursorType::POINTER)
                        // BBS: add infill_angle parameter
                        m_triangle_selectors[mesh_idx]->bucket_fill_select_triangles(mesh_hit, facet_idx, clp, -1.f, false, true);
                    else if (m_tool_type == ToolType::BUCKET_FILL)
                        // BBS: add infill_angle parameter
                        m_triangle_selectors[mesh_idx]->bucket_fill_select_triangles(mesh_hit, facet_idx, clp, m_smart_fill_angle, true, true);
                    m_seed_fill_last_mesh_id = -1;
                }
            } else if (m_tool_type == ToolType::BRUSH) {
                assert(m_cursor_type == TriangleSelector::CursorType::CIRCLE || m_cursor_type == TriangleSelector::CursorType::SPHERE);
                if (projected_mouse_positions.size() == 1) {
                    const ProjectedMousePosition& first_position = projected_mouse_positions.front();
                    std::unique_ptr<TriangleSelector::Cursor> cursor = TriangleSelector::SinglePointCursor::cursor_factory(first_position.mesh_hit,
                        camera_pos, m_cursor_radius,
                        m_cursor_type, trafo_matrix, clp);
                    m_triangle_selectors[mesh_idx]->select_patch(int(first_position.facet_idx), std::move(cursor), new_state, trafo_matrix_not_translate,
                        m_triangle_splitting_enabled, m_paint_on_overhangs_only ? m_highlight_by_angle_threshold_deg : 0.f);
                }
                else {
                    for (auto first_position_it = projected_mouse_positions.cbegin(); first_position_it != projected_mouse_positions.cend() - 1; ++first_position_it) {
                        auto second_position_it = first_position_it + 1;
                        std::unique_ptr<TriangleSelector::Cursor> cursor = TriangleSelector::DoublePointCursor::cursor_factory(first_position_it->mesh_hit, second_position_it->mesh_hit, camera_pos, m_cursor_radius, m_cursor_type, trafo_matrix, clp);
                        m_triangle_selectors[mesh_idx]->select_patch(int(first_position_it->facet_idx), std::move(cursor), new_state, trafo_matrix_not_translate, m_triangle_splitting_enabled, m_paint_on_overhangs_only ? m_highlight_by_angle_threshold_deg : 0.f);
                    }
                }
            }
            m_triangle_selectors[mesh_idx]->request_update_render_data(true);
            m_last_mouse_click = mouse_position;
        }
        return true;
    }
    if (action == SLAGizmoEventType::Moving && (m_tool_type == ToolType::SMART_FILL || m_tool_type == ToolType::BUCKET_FILL || (m_tool_type == ToolType::BRUSH && m_cursor_type == TriangleSelector::CursorType::POINTER))) {
        if (m_triangle_selectors.empty())
            return false;
        const Camera        &camera                       = wxGetApp().plater()->get_camera();
        const Selection     &selection                    = m_parent.get_selection();
        const ModelObject   *mo                           = m_c->selection_info()->model_object();
        const ModelInstance *mi                           = mo->instances[selection.get_instance_idx()];
        const Transform3d    instance_trafo = m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
            mi->get_assemble_transformation().get_matrix() :
            mi->get_transformation().get_matrix();
        const Transform3d    instance_trafo_not_translate = m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView ?
            mi->get_assemble_transformation().get_matrix(true) :
            mi->get_transformation().get_matrix(true);
        // Precalculate transformations of individual meshes.
        std::vector<Transform3d> trafo_matrices;
        std::vector<Transform3d> trafo_matrices_not_translate;
        for (const ModelVolume *mv : mo->volumes)
            if (mv->is_model_part()) {
                if (m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView) {
                    Transform3d temp = instance_trafo * mv->get_matrix();
                    temp.translate(mv->get_transformation().get_offset() * (GLVolume::explosion_ratio - 1.0) + mi->get_offset_to_assembly() * (GLVolume::explosion_ratio - 1.0));
                    trafo_matrices.emplace_back(temp);
                }
                else {
                    trafo_matrices.emplace_back(instance_trafo * mv->get_matrix());
                }
                trafo_matrices_not_translate.emplace_back(instance_trafo_not_translate * mv->get_matrix(true));
            }
        // Now "click" into all the prepared points and spill paint around them.
        update_raycast_cache(mouse_position, camera, trafo_matrices);
        auto seed_fill_unselect_all = [this]() {
            for (auto &triangle_selector : m_triangle_selectors) {
                triangle_selector->seed_fill_unselect_all_triangles();
                triangle_selector->request_update_render_data();
            }
        };
        if (m_rr.mesh_id == -1) {
            // Clean selected by seed fill for all triangles in all meshes when a mouse isn't pointing on any mesh.
            seed_fill_unselect_all();
            m_seed_fill_last_mesh_id = -1;
            // In case we have no valid hit, we can return.
            return false;
        }
        // The mouse moved from one object's volume to another one. So it is needed to unselect all triangles selected by seed fill.
        if(m_rr.mesh_id != m_seed_fill_last_mesh_id)
            seed_fill_unselect_all();
        const Transform3d &trafo_matrix = trafo_matrices[m_rr.mesh_id];
        const Transform3d &trafo_matrix_not_translate = trafo_matrices_not_translate[m_rr.mesh_id];
        assert(m_rr.mesh_id < int(m_triangle_selectors.size()));
        const TriangleSelector::ClippingPlane &clp = this->get_clipping_plane_in_volume_coordinates(trafo_matrix);
        if (m_tool_type == ToolType::SMART_FILL)
            m_triangle_selectors[m_rr.mesh_id]->seed_fill_select_triangles(m_rr.hit, int(m_rr.facet), trafo_matrix_not_translate, clp, m_smart_fill_angle,
                                                                           m_paint_on_overhangs_only ? m_highlight_by_angle_threshold_deg : 0.f);
        else if (m_tool_type == ToolType::BRUSH && m_cursor_type == TriangleSelector::CursorType::POINTER)
            // BBS: add infill_angle parameter
            m_triangle_selectors[m_rr.mesh_id]->bucket_fill_select_triangles(m_rr.hit, int(m_rr.facet), clp, -1.f, false);
        else if (m_tool_type == ToolType::BUCKET_FILL)
            // BBS: add infill_angle parameter
            m_triangle_selectors[m_rr.mesh_id]->bucket_fill_select_triangles(m_rr.hit, int(m_rr.facet), clp, m_smart_fill_angle, true);
        m_triangle_selectors[m_rr.mesh_id]->request_update_render_data();
        m_seed_fill_last_mesh_id = m_rr.mesh_id;
        return true;
    }
    if ((action == SLAGizmoEventType::LeftUp || action == SLAGizmoEventType::RightUp)
      && m_button_down != Button::None) {
        // Take snapshot and update ModelVolume data.
        wxString action_name = this->handle_snapshot_action_name(shift_down, m_button_down);
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), std::string(action_name.ToUTF8().data()), UndoRedo::SnapshotType::GizmoAction);
        update_model_object();
        m_button_down = Button::None;
        m_last_mouse_click = Vec2d::Zero();
        return true;
    }
    return false;
}
References BRUSH, BUCKET_FILL, Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::TriangleSelector::CIRCLE, Slic3r::TriangleSelector::SinglePointCursor::cursor_factory(), Slic3r::TriangleSelector::DoublePointCursor::cursor_factory(), Slic3r::GUI::Dragging, Slic3r::GLVolume::explosion_ratio, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::facet, Slic3r::GUI::GLGizmoPainterBase::ProjectedMousePosition::facet_idx, Slic3r::GUI::GLGizmoPainterBase::ProjectedHeightRange::first_facet_idx, Slic3r::GUI::TriangleSelectorPatch::gap_area, GAP_FILL, Slic3r::GUI::TriangleSelectorPatch::GapAreaMax, Slic3r::GUI::TriangleSelectorPatch::GapAreaMin, Slic3r::GUI::TriangleSelectorPatch::GapAreaStep, Slic3r::ModelInstance::get_assemble_transformation(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), get_clipping_plane_in_volume_coordinates(), get_cursor_height_max(), get_cursor_height_min(), get_cursor_height_step(), get_cursor_radius_max(), get_cursor_radius_min(), get_cursor_radius_step(), Slic3r::GUI::Selection::get_instance_idx(), get_left_button_state_type(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::ModelInstance::get_offset_to_assembly(), Slic3r::GUI::Camera::get_position(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), get_projected_height_range(), get_projected_mouse_positions(), get_right_button_state_type(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::ModelInstance::get_transformation(), Slic3r::UndoRedo::GizmoAction, handle_snapshot_action_name(), Slic3r::TriangleSelector::HEIGHT_RANGE, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::hit, Slic3r::ModelObject::instances, int, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Left, Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, m_button_down, Slic3r::GUI::GLGizmoBase::m_c, m_cursor_height, m_cursor_radius, m_cursor_type, m_highlight_by_angle_threshold_deg, m_last_mouse_click, m_paint_on_overhangs_only, Slic3r::GUI::GLGizmoBase::m_parent, m_rr, m_seed_fill_last_mesh_id, m_smart_fill_angle, m_tool_type, m_triangle_selectors, m_triangle_splitting_enabled, Slic3r::GUI::GLGizmoPainterBase::ProjectedMousePosition::mesh_hit, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::mesh_id, Slic3r::GUI::GLGizmoPainterBase::ProjectedHeightRange::mesh_idx, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::MouseWheelDown, Slic3r::GUI::MouseWheelUp, Slic3r::GUI::Moving, Slic3r::NONE, None, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::plater(), Slic3r::TriangleSelector::POINTER, Slic3r::GUI::ResetClippingPlane, Right, Slic3r::GUI::RightDown, Slic3r::GUI::RightUp, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_position(), SMART_FILL, SmartFillAngleMax, SmartFillAngleMin, SmartFillAngleStep, Slic3r::TriangleSelector::SPHERE, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), update_model_object(), update_raycast_cache(), Slic3r::ModelObject::volumes, and Slic3r::GUI::GLGizmoPainterBase::ProjectedHeightRange::z_world.
GizmoImguiBegin()
bool Slic3r::GUI::GLGizmoBase::GizmoImguiBegin (const std::string & name, int flags) protected inherited
{
    return m_imgui->begin(name, flags);
}
References Slic3r::GUI::ImGuiWrapper::begin(), and Slic3r::GUI::GLGizmoBase::m_imgui.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
GizmoImguiEnd()
void Slic3r::GUI::GLGizmoBase::GizmoImguiEnd () protected inherited
{
    last_input_window_width = ImGui::GetWindowWidth();
    m_imgui->end();
}
References Slic3r::GUI::ImGuiWrapper::end(), ImGui::GetWindowWidth(), Slic3r::GUI::GLGizmoBase::last_input_window_width, and Slic3r::GUI::GLGizmoBase::m_imgui.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
GizmoImguiSetNextWIndowPos()
void Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos (float & x, float y, int flag, float pivot_x = 0.0f, float pivot_y = 0.0f) protected inherited
{
    if (abs(last_input_window_width) > 0.01f) {
        if (x + last_input_window_width > m_parent.get_canvas_size().get_width()) {
            if (last_input_window_width > m_parent.get_canvas_size().get_width()) {
                x = 0;
            } else {
                x = m_parent.get_canvas_size().get_width() - last_input_window_width;
            }
        }
    }
    m_imgui->set_next_window_pos(x, y, flag, pivot_x, pivot_y);
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLGizmoBase::last_input_window_width, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::GUI::ImGuiWrapper::set_next_window_pos().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
handle_snapshot_action_name()
virtual wxString Slic3r::GUI::GLGizmoPainterBase::handle_snapshot_action_name (bool shift_down, Button button_down) const protected pure virtual
Implemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
Referenced by gizmo_event().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
is_mesh_point_clipped()
bool Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped (const Vec3d & point, const Transform3d & trafo) const private
{
    if (m_c->object_clipper()->get_position() == 0.)
        return false;
    auto sel_info = m_c->selection_info();
    Vec3d transformed_point =  trafo * point;
    transformed_point(2) += sel_info->get_sla_shift();
    return m_c->object_clipper()->get_clipping_plane()->is_point_clipped(transformed_point);
}
References Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_position(), Slic3r::GUI::ClippingPlane::is_point_clipped(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by update_raycast_cache().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
load_render_colors()
void Slic3r::GUI::GLGizmoBase::load_render_colors () static inherited
{
    RenderColor::colors[RenderCol_Grabber_X] = IMColor(GLGizmoBase::AXES_COLOR[0]);
    RenderColor::colors[RenderCol_Grabber_Y] = IMColor(GLGizmoBase::AXES_COLOR[1]);
    RenderColor::colors[RenderCol_Grabber_Z] = IMColor(GLGizmoBase::AXES_COLOR[2]);
    RenderColor::colors[RenderCol_Flatten_Plane] = IMColor(GLGizmoBase::FLATTEN_COLOR);
    RenderColor::colors[RenderCol_Flatten_Plane_Hover] = IMColor(GLGizmoBase::FLATTEN_HOVER_COLOR);
}
References Slic3r::GUI::GLGizmoBase::AXES_COLOR, Slic3r::RenderColor::colors, Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR, Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR, Slic3r::IMColor(), RenderCol_Flatten_Plane, RenderCol_Flatten_Plane_Hover, RenderCol_Grabber_X, RenderCol_Grabber_Y, and RenderCol_Grabber_Z.
Referenced by Slic3r::GUI::GLCanvas3D::init().
on_change_color_mode()
virtual void Slic3r::GUI::GLGizmoBase::on_change_color_mode (bool is_dark) inline virtual inherited
{  m_is_dark_mode = is_dark; }
References Slic3r::GUI::GLGizmoBase::m_is_dark_mode.
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_disable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, and Slic3r::GUI::GLGizmoRotate3D.
{}
Referenced by Slic3r::GUI::GLGizmoBase::disable_grabber().
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoBase::on_enable_grabber (unsigned int id) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, and Slic3r::GUI::GLGizmoRotate3D.
{}
Referenced by Slic3r::GUI::GLGizmoBase::enable_grabber().
on_get_name()
virtual std::string Slic3r::GUI::GLGizmoBase::on_get_name () const protected pure virtual inherited
Implemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoFaceDetector, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeshBoolean, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, Slic3r::GUI::GLGizmoSeam, Slic3r::GUI::GLGizmoSimplify, Slic3r::GUI::GLGizmoSlaSupports, and Slic3r::GUI::GLGizmoText.
Referenced by Slic3r::GUI::GLGizmoBase::get_gizmo_name(), and Slic3r::GUI::GLGizmoBase::get_name().
on_get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoPainterBase::on_get_requirements () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return CommonGizmosDataID(
                int(CommonGizmosDataID::SelectionInfo)
              | int(CommonGizmosDataID::InstancesHider)
              | int(CommonGizmosDataID::Raycaster)
              | int(CommonGizmosDataID::ObjectClipper));
}
References Slic3r::GUI::InstancesHider, Slic3r::GUI::ObjectClipper, Slic3r::GUI::Raycaster, and Slic3r::GUI::SelectionInfo.
on_init()
virtual bool Slic3r::GUI::GLGizmoBase::on_init () protected pure virtual inherited
Implemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoFaceDetector, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoFlatten, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMeshBoolean, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, Slic3r::GUI::GLGizmoSeam, Slic3r::GUI::GLGizmoSimplify, Slic3r::GUI::GLGizmoSlaSupports, and Slic3r::GUI::GLGizmoText.
Referenced by Slic3r::GUI::GLGizmoBase::init().
on_is_activable()
bool Slic3r::GUI::GLGizmoPainterBase::on_is_activable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
    if (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() != ptFFF
        || !selection.is_single_full_instance()/* || wxGetApp().get_mode() == comSimple*/)
        return false;
    // BBS
#if 0
    // Check that none of the selected volumes is outside. Only SLA auxiliaries (supports) are allowed outside.
    const Selection::IndicesList& list = selection.get_volume_idxs();
    return std::all_of(list.cbegin(), list.cend(), [&selection](unsigned int idx) { return !selection.get_volume(idx)->is_outside; });
#else
    return true;
#endif
}
References Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::ptFFF.
Referenced by Slic3r::GUI::GLGizmoMmuSegmentation::on_is_activable().
on_is_selectable()
bool Slic3r::GUI::GLGizmoPainterBase::on_is_selectable () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    //BBS
    /*return (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptFFF
         && wxGetApp().get_mode() != comSimple );*/
    return (wxGetApp().preset_bundle->printers.get_edited_preset().printer_technology() == ptFFF);
}
References Slic3r::ptFFF.
on_load()
void Slic3r::GUI::GLGizmoPainterBase::on_load (cereal::BinaryInputArchive & ar) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    // We should update the gizmo from current ModelObject, but it is not
    // possible at this point. That would require having updated selection and
    // common gizmos data, which is not done at this point. Instead, save
    // a flag to do the update in set_painter_gizmo_data, which will be called
    // soon after.
    m_schedule_update = true;
}
References m_schedule_update.
on_opening()
virtual void Slic3r::GUI::GLGizmoPainterBase::on_opening () protected pure virtual
Implemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
Referenced by on_set_state().
on_render()
void Slic3r::GUI::GLGizmoPainterBase::on_render () inline override private virtual
Implements Slic3r::GUI::GLGizmoBase.
{}
on_render_for_picking()
void Slic3r::GUI::GLGizmoPainterBase::on_render_for_picking () inline override private virtual
Implements Slic3r::GUI::GLGizmoBase.
{}
on_render_input_window()
virtual void Slic3r::GUI::GLGizmoBase::on_render_input_window (float x, float y, float bottom_limit) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoMeshBoolean, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoScale3D, Slic3r::GUI::GLGizmoText, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoFaceDetector, Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoSeam, Slic3r::GUI::GLGizmoSimplify, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
on_save()
void Slic3r::GUI::GLGizmoPainterBase::on_save (cereal::BinaryOutputArchive & ar) const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{}
on_set_hover_id()
virtual void Slic3r::GUI::GLGizmoBase::on_set_hover_id () inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoRotate3D, and Slic3r::GUI::GLGizmoSlaSupports.
{}
Referenced by Slic3r::GUI::GLGizmoBase::set_hover_id().
on_set_state()
void Slic3r::GUI::GLGizmoPainterBase::on_set_state () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
Reimplemented in Slic3r::GUI::GLGizmoSeam.
{
    if (m_state == m_old_state)
        return;
    if (m_state == On && m_old_state != On) { // the gizmo was just turned on
        on_opening();
        const Selection& selection = m_parent.get_selection();
        //Camera& camera = wxGetApp().plater()->get_camera();
        //Vec3d rotate_target = selection.get_bounding_box().center();
        //rotate_target(2) = 0.f;
        //Vec3d position = camera.get_position();
        //camera.set_target(rotate_target);
        //camera.look_at(position, rotate_target, Vec3d::UnitZ());
    }
    if (m_state == Off && m_old_state != Off) { // the gizmo was just turned Off
        // we are actually shutting down
        on_shutdown();
        m_old_mo_id = -1;
        //m_iva.release_geometry();
        m_triangle_selectors.clear();
        //Camera& camera = wxGetApp().plater()->get_camera();
        //camera.look_at(camera.get_position(), m_previous_target, Vec3d::UnitZ());
        //camera.set_target(m_previous_target);
        //camera.recover_from_free_camera();
    }
    m_old_state = m_state;
}
References Slic3r::GUI::GLCanvas3D::get_selection(), m_old_mo_id, m_old_state, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::m_state, m_triangle_selectors, Slic3r::GUI::GLGizmoBase::Off, Slic3r::GUI::GLGizmoBase::On, on_opening(), and on_shutdown().
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), and Slic3r::GUI::GLGizmoSeam::on_set_state().
on_shutdown()
virtual void Slic3r::GUI::GLGizmoPainterBase::on_shutdown () protected pure virtual
Implemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
Referenced by on_set_state().
on_start_dragging()
void Slic3r::GUI::GLGizmoPainterBase::on_start_dragging () inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{}
on_stop_dragging()
void Slic3r::GUI::GLGizmoPainterBase::on_stop_dragging () inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{}
on_update()
virtual void Slic3r::GUI::GLGizmoBase::on_update (const UpdateData & data) inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoAdvancedCut, Slic3r::GUI::GLGizmoCut, Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMove3D, Slic3r::GUI::GLGizmoRotate, Slic3r::GUI::GLGizmoRotate3D, Slic3r::GUI::GLGizmoScale3D, Slic3r::GUI::GLGizmoSlaSupports, and Slic3r::GUI::GLGizmoText.
{}
Referenced by Slic3r::GUI::GLGizmoBase::update().
picking_color_component()
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::picking_color_component (unsigned int id) const protected inherited
{
    static const float INV_255 = 1.0f / 255.0f;
    id = BASE_ID - id;
    if (m_group_id > -1)
        id -= m_group_id;
    // color components are encoded to match the calculation of volume_id made into GLCanvas3D::_picking_pass()
    return std::array<float, 4> {
    float((id >> 0) & 0xff) * INV_255, // red
    float((id >> 8) & 0xff) * INV_255, // green
    float((id >> 16) & 0xff) * INV_255, // blue
    float(picking_checksum_alpha_channel(id & 0xff, (id >> 8) & 0xff, (id >> 16) & 0xff))* INV_255 // checksum for validating against unwanted alpha blending and multi sampling
  };
}
References Slic3r::GUI::GLGizmoBase::BASE_ID, Slic3r::GUI::GLGizmoBase::m_group_id, and Slic3r::GUI::picking_checksum_alpha_channel().
Referenced by Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking(), Slic3r::GUI::GLGizmoHollow::render_points(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ m_tooltip.clear(); on_render(); }
References Slic3r::GUI::GLGizmoBase::m_tooltip, and Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render(), and Slic3r::GUI::GLGizmoBase::Grabber::render_for_picking().
render_cursor()
void Slic3r::GUI::GLGizmoPainterBase::render_cursor () const protected
{
    // First check that the mouse pointer is on an object.
    const ModelObject* mo = m_c->selection_info()->model_object();
    const Selection& selection = m_parent.get_selection();
    const ModelInstance* mi = mo->instances[selection.get_instance_idx()];
    const Camera& camera = wxGetApp().plater()->get_camera();
    // Precalculate transformations of individual meshes.
    std::vector<Transform3d> trafo_matrices;
    for (const ModelVolume* mv : mo->volumes) {
        if (mv->is_model_part())
        {
            if (m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView) {
                Transform3d temp = mi->get_assemble_transformation().get_matrix() * mv->get_matrix();
                temp.translate(mv->get_transformation().get_offset() * (GLVolume::explosion_ratio - 1.0) + mi->get_offset_to_assembly() * (GLVolume::explosion_ratio - 1.0));
                trafo_matrices.emplace_back(temp);
            }
            else {
                trafo_matrices.emplace_back(mi->get_transformation().get_matrix() * mv->get_matrix());
            }
        }
    }
    // Raycast and return if there's no hit.
    update_raycast_cache(m_parent.get_local_mouse_position(), camera, trafo_matrices);
    if (m_rr.mesh_id == -1)
        return;
    if (m_tool_type == ToolType::BRUSH) {
        if (m_cursor_type == TriangleSelector::SPHERE)
            render_cursor_sphere(trafo_matrices[m_rr.mesh_id]);
        else if (m_cursor_type == TriangleSelector::CIRCLE)
            render_cursor_circle();
        else if (m_cursor_type == TriangleSelector::HEIGHT_RANGE)
            render_cursor_height_range(trafo_matrices[m_rr.mesh_id]);
    }
}
References BRUSH, Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::TriangleSelector::CIRCLE, Slic3r::GLVolume::explosion_ratio, Slic3r::ModelInstance::get_assemble_transformation(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::GLCanvas3D::get_local_mouse_position(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::ModelInstance::get_offset_to_assembly(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::ModelInstance::get_transformation(), Slic3r::TriangleSelector::HEIGHT_RANGE, Slic3r::ModelObject::instances, Slic3r::GUI::GLGizmoBase::m_c, m_cursor_type, Slic3r::GUI::GLGizmoBase::m_parent, m_rr, m_tool_type, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::mesh_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), render_cursor_circle(), render_cursor_height_range(), render_cursor_sphere(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::TriangleSelector::SPHERE, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), update_raycast_cache(), and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), and Slic3r::GUI::GLGizmoSeam::render_painter_gizmo().
render_cursor_circle()
void Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle () const protected
{
    const Camera &camera   = wxGetApp().plater()->get_camera();
    auto          zoom     = (float) camera.get_zoom();
    float         inv_zoom = (zoom != 0.0f) ? 1.0f / zoom : 0.0f;
    Size  cnv_size        = m_parent.get_canvas_size();
    float cnv_half_width  = 0.5f * (float) cnv_size.get_width();
    float cnv_half_height = 0.5f * (float) cnv_size.get_height();
    if ((cnv_half_width == 0.0f) || (cnv_half_height == 0.0f))
        return;
    Vec2d mouse_pos(m_parent.get_local_mouse_position()(0), m_parent.get_local_mouse_position()(1));
    Vec2d center(mouse_pos(0) - cnv_half_width, cnv_half_height - mouse_pos(1));
    center = center * inv_zoom;
    glsafe(::glLineWidth(1.5f));
    // BBS
    std::array<float, 4> render_color = this->get_cursor_hover_color();
    if (m_button_down == Button::Left)
        render_color = this->get_cursor_sphere_left_button_color();
    else if (m_button_down == Button::Right)
        render_color = this->get_cursor_sphere_right_button_color();
    glsafe(::glColor4fv(render_color.data()));
    glsafe(::glDisable(GL_DEPTH_TEST));
    glsafe(::glPushMatrix());
    glsafe(::glLoadIdentity());
    // ensure that the circle is renderered inside the frustrum
    glsafe(::glTranslated(0.0, 0.0, -(camera.get_near_z() + 0.5)));
    // ensure that the overlay fits the frustrum near z plane
    double gui_scale = camera.get_gui_scale();
    glsafe(::glScaled(gui_scale, gui_scale, 1.0));
    glsafe(::glPushAttrib(GL_ENABLE_BIT));
    glsafe(::glLineStipple(4, 0xAAAA));
    glsafe(::glEnable(GL_LINE_STIPPLE));
    ::glBegin(GL_LINE_LOOP);
    for (double angle=0; angle<2*M_PI; angle+=M_PI/20.)
        ::glVertex2f(GLfloat(center.x()+m_cursor_radius*cos(angle)), GLfloat(center.y()+m_cursor_radius*sin(angle)));
    glsafe(::glEnd());
    glsafe(::glPopAttrib());
    glsafe(::glPopMatrix());
    glsafe(::glEnable(GL_DEPTH_TEST));
}
References Slic3r::angle(), cos(), Slic3r::GUI::GLCanvas3D::get_canvas_size(), get_cursor_hover_color(), get_cursor_sphere_left_button_color(), get_cursor_sphere_right_button_color(), Slic3r::GUI::Camera::get_gui_scale(), Slic3r::GUI::Size::get_height(), Slic3r::GUI::GLCanvas3D::get_local_mouse_position(), Slic3r::GUI::Camera::get_near_z(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::Camera::get_zoom(), GL_LINE_LOOP, glsafe, Left, m_button_down, m_cursor_radius, Slic3r::GUI::GLGizmoBase::m_parent, M_PI, Right, and sin().
Referenced by render_cursor().
render_cursor_height_range()
void Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range (const Transform3d & trafo) const protected
{
    const BoundingBoxf3 box = bounding_box();
    Vec3d hit_world = trafo * Vec3d(m_rr.hit(0), m_rr.hit(1), m_rr.hit(2));
    float max_z = (float)box.max.z();
    float min_z = (float)box.min.z();
    float cursor_z = std::clamp((float)hit_world.z(), min_z, max_z);
    std::array<float, 2> zs = { cursor_z, std::clamp(cursor_z + m_cursor_height, min_z, max_z) };
    const Selection& selection = m_parent.get_selection();
    const ModelObject* model_object = wxGetApp().model().objects[selection.get_object_idx()];
    const ModelInstance* mi = model_object->instances[selection.get_instance_idx()];
    for (const ModelVolume* mv : model_object->volumes) {
        TriangleMesh vol_mesh = mv->mesh();
        if (m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView) {
            Transform3d temp = mi->get_assemble_transformation().get_matrix() * mv->get_matrix();
            temp.translate(mv->get_transformation().get_offset() * (GLVolume::explosion_ratio - 1.0) + mi->get_offset_to_assembly() * (GLVolume::explosion_ratio - 1.0));
            vol_mesh.transform(temp);
        }
        else {
            vol_mesh.transform(mi->get_transformation().get_matrix() * mv->get_matrix());
        }
        for (int i = 0; i < zs.size(); i++) {
            update_contours(vol_mesh, zs[i], max_z, min_z);
            glsafe(::glPushMatrix());
            glsafe(::glTranslated(m_cut_contours.shift.x(), m_cut_contours.shift.y(), m_cut_contours.shift.z()));
            glsafe(::glLineWidth(2.0f));
            m_cut_contours.contours.render();
            glsafe(::glPopMatrix());
        }
    }
}
References bounding_box(), Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::GUI::GLGizmoPainterBase::CutContours::contours, Slic3r::GLVolume::explosion_ratio, Slic3r::ModelInstance::get_assemble_transformation(), Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::Selection::get_instance_idx(), Slic3r::Geometry::Transformation::get_matrix(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::ModelInstance::get_offset_to_assembly(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::ModelInstance::get_transformation(), glsafe, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::hit, Slic3r::ModelObject::instances, m_cursor_height, m_cut_contours, Slic3r::GUI::GLGizmoBase::m_parent, m_rr, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLGizmoPainterBase::CutContours::shift, Slic3r::TriangleMesh::transform(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), update_contours(), and Slic3r::ModelObject::volumes.
Referenced by render_cursor().
render_cursor_sphere()
void Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere (const Transform3d & trafo) const protected
{
    const Transform3d complete_scaling_matrix_inverse = Geometry::Transformation(trafo).get_matrix(true, true, false, true).inverse();
    const bool is_left_handed = Geometry::Transformation(trafo).is_left_handed();
    glsafe(::glPushMatrix());
    glsafe(::glMultMatrixd(trafo.data()));
    // Inverse matrix of the instance scaling is applied so that the mark does not scale with the object.
    glsafe(::glTranslatef(m_rr.hit(0), m_rr.hit(1), m_rr.hit(2)));
    glsafe(::glMultMatrixd(complete_scaling_matrix_inverse.data()));
    glsafe(::glScaled(m_cursor_radius, m_cursor_radius, m_cursor_radius));
    if (is_left_handed)
        glFrontFace(GL_CW);
    // BBS
    std::array<float, 4> render_color = this->get_cursor_hover_color();
    if (m_button_down == Button::Left)
        render_color = this->get_cursor_sphere_left_button_color();
    else if (m_button_down == Button::Right)
        render_color = this->get_cursor_sphere_right_button_color();
    glsafe(::glColor4fv(render_color.data()));
    m_vbo_sphere.render();
    if (is_left_handed)
        glFrontFace(GL_CCW);
    glsafe(::glPopMatrix());
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), get_cursor_hover_color(), get_cursor_sphere_left_button_color(), get_cursor_sphere_right_button_color(), Slic3r::Geometry::Transformation::get_matrix(), glsafe, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::hit, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::inverse(), Slic3r::Geometry::Transformation::is_left_handed(), Left, m_button_down, m_cursor_radius, m_rr, m_vbo_sphere, Slic3r::GLIndexedVertexArray::render(), and Right.
Referenced by render_cursor().
render_for_picking()
void Slic3r::GUI::GLGizmoBase::render_for_picking () inline inherited
{ on_render_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_render_for_picking().
render_grabbers() [1/2]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
#if ENABLE_FIXED_GRABBER
    render_grabbers((float)(GLGizmoBase::Grabber::FixedGrabberSize));
#else
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
#endif
}
References Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/2]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    for (int i = 0; i < (int)m_grabbers.size(); ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(m_hover_id == i, size);
    }
    shader->stop_using();
}
References int, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), size, Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking (const BoundingBoxf3 & box) const protected inherited
{
#if ENABLE_FIXED_GRABBER
    float mean_size = (float)(GLGizmoBase::Grabber::FixedGrabberSize);
#else
    float mean_size = (float)((box.size().x() + box.size().y() + box.size().z()) / 3.0);
#endif
    for (unsigned int i = 0; i < (unsigned int)m_grabbers.size(); ++i) {
        if (m_grabbers[i].enabled) {
            std::array<float, 4> color = picking_color_component(i);
            m_grabbers[i].color = color;
            m_grabbers[i].render_for_picking(mean_size);
        }
    }
}
References Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, int, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::picking_color_component(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), and Slic3r::GUI::GLGizmoScale3D::on_render_for_picking().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // for some reason, the imgui dialogs are not shown on screen in the 1st frame where they are rendered, but show up only with the 2nd rendered frame
        // so, we forces another frame rendering the first time the imgui window is shown
        m_parent.set_as_dirty();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
render_painter_gizmo()
virtual void Slic3r::GUI::GLGizmoPainterBase::render_painter_gizmo () const pure virtual
Implemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
render_triangles()
void Slic3r::GUI::GLGizmoPainterBase::render_triangles (const Selection & selection) const protected virtual
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{
    auto* shader = wxGetApp().get_shader("gouraud");
    if (! shader)
        return;
    shader->start_using();
    shader->set_uniform("slope.actived", false);
    shader->set_uniform("print_volume.type", 0);
    shader->set_uniform("clipping_plane", this->get_clipping_plane_data().clp_dataf);
    ScopeGuard guard([shader]() { if (shader) shader->stop_using(); });
    const ModelObject *mo      = m_c->selection_info()->model_object();
    int                mesh_id = -1;
    for (const ModelVolume* mv : mo->volumes) {
        if (! mv->is_model_part())
            continue;
        ++mesh_id;
        Transform3d trafo_matrix;
        if (m_parent.get_canvas_type() == GLCanvas3D::CanvasAssembleView) {
            trafo_matrix = mo->instances[selection.get_instance_idx()]->get_assemble_transformation().get_matrix() * mv->get_matrix();
            trafo_matrix.translate(mv->get_transformation().get_offset() * (GLVolume::explosion_ratio - 1.0) + mo->instances[selection.get_instance_idx()]->get_offset_to_assembly() * (GLVolume::explosion_ratio - 1.0));
        }
        else {
            trafo_matrix = mo->instances[selection.get_instance_idx()]->get_transformation().get_matrix()* mv->get_matrix();
        }
        bool is_left_handed = trafo_matrix.matrix().determinant() < 0.;
        if (is_left_handed)
            glsafe(::glFrontFace(GL_CW));
        glsafe(::glPushMatrix());
        glsafe(::glMultMatrixd(trafo_matrix.data()));
        // For printers with multiple extruders, it is necessary to pass trafo_matrix
        // to the shader input variable print_box.volume_world_matrix before
        // rendering the painted triangles. When this matrix is not set, the
        // wrong transformation matrix is used for "Clipping of view".
        shader->set_uniform("volume_world_matrix", trafo_matrix);
        m_triangle_selectors[mesh_id]->render(m_imgui);
        glsafe(::glPopMatrix());
        if (is_left_handed)
            glsafe(::glFrontFace(GL_CCW));
    }
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), Slic3r::GLVolume::explosion_ratio, Slic3r::GUI::GLCanvas3D::get_canvas_type(), get_clipping_plane_data(), Slic3r::GUI::Selection::get_instance_idx(), glsafe, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoBase::m_parent, m_triangle_selectors, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c, and ptr.
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::process_cut_line(), and Slic3r::GUI::GLGizmoSimplify::request_rerender().
set_group_id()
void Slic3r::GUI::GLGizmoBase::set_group_id (int id) inline inherited
{ m_group_id = id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::GLGizmoAdvancedCut().
set_highlight_color()
void Slic3r::GUI::GLGizmoBase::set_highlight_color (const std::array< float, 4 > & color) inherited
{
    m_highlight_color = color;
}
References Slic3r::GUI::GLGizmoBase::m_highlight_color.
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    if (m_grabbers.empty() || (id < (int)m_grabbers.size()))
    {
        m_hover_id = id;
        on_set_hover_id();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_icon_filename()
void Slic3r::GUI::GLGizmoBase::set_icon_filename (const std::string & filename) inherited
{
    m_icon_filename = filename;
}
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
set_painter_gizmo_data()
void Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data (const Selection & selection) virtual
Reimplemented in Slic3r::GUI::GLGizmoMmuSegmentation.
{
    if (m_state != On)
        return;
    const ModelObject* mo = m_c->selection_info() ? m_c->selection_info()->model_object() : nullptr;
    if (mo && selection.is_from_single_instance()
     && (m_schedule_update || mo->id() != m_old_mo_id || mo->volumes.size() != m_old_volumes_size))
    {
        //BBS: add logic to distinguish the first_time_update and later_update
        update_from_model_object(!m_schedule_update);
        m_old_mo_id = mo->id();
        m_old_volumes_size = mo->volumes.size();
        m_schedule_update = false;
    }
}
References Slic3r::ObjectBase::id(), Slic3r::GUI::Selection::is_from_single_instance(), Slic3r::GUI::GLGizmoBase::m_c, m_old_mo_id, m_old_volumes_size, m_schedule_update, Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::CommonGizmosDataPool::selection_info(), update_from_model_object(), and Slic3r::ModelObject::volumes.
Referenced by Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data().
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
start_dragging()
void Slic3r::GUI::GLGizmoBase::start_dragging () inherited
{
    m_dragging = true;
    for (int i = 0; i < (int)m_grabbers.size(); ++i)
    {
        m_grabbers[i].dragging = (m_hover_id == i);
    }
    on_start_dragging();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("this %1%, m_hover_id=%2%\n")%this %m_hover_id;
}
References int, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_start_dragging().
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), and Slic3r::GUI::GLGizmoText::gizmo_event().
stop_dragging()
void Slic3r::GUI::GLGizmoBase::stop_dragging () inherited
{
    m_dragging = false;
    for (int i = 0; i < (int)m_grabbers.size(); ++i)
    {
        m_grabbers[i].dragging = false;
    }
    on_stop_dragging();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("this %1%, m_hover_id=%2%\n")%this %m_hover_id;
}
References int, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_stop_dragging().
update()
void Slic3r::GUI::GLGizmoBase::update (const UpdateData & data) inherited
{
    if (m_hover_id != -1)
        on_update(data);
}
References Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_update().
update_contours()
void Slic3r::GUI::GLGizmoPainterBase::update_contours (const TriangleMesh & vol_mesh, float cursor_z, float max_z, float min_z) const private
{
    const Selection& selection = m_parent.get_selection();
    const GLVolume* first_glvolume = selection.get_volume(*selection.get_volume_idxs().begin());
    const BoundingBoxf3& box = first_glvolume->transformed_convex_hull_bounding_box();
    const ModelObject* model_object = wxGetApp().model().objects[selection.get_object_idx()];
    const int instance_idx = selection.get_instance_idx();
        if (min_z < cursor_z && cursor_z < max_z) {
            if (m_cut_contours.cut_z != cursor_z || m_cut_contours.object_id != model_object->id() || m_cut_contours.instance_idx != instance_idx) {
                m_cut_contours.cut_z = cursor_z;
                m_cut_contours.mesh = vol_mesh;
                m_cut_contours.position = box.center();
                m_cut_contours.shift = Vec3d::Zero();
                m_cut_contours.object_id = model_object->id();
                m_cut_contours.instance_idx = instance_idx;
                m_cut_contours.contours.reset();
                MeshSlicingParams slicing_params;
                slicing_params.trafo = Transform3d::Identity().matrix();
                const Polygons polys = slice_mesh(m_cut_contours.mesh.its, cursor_z, slicing_params);
                if (!polys.empty()) {
                    m_cut_contours.contours.init_from(polys, static_cast<float>(cursor_z));
                    m_cut_contours.contours.set_color(-1, { 1.0f, 1.0f, 1.0f, 1.0f });
                }
            }
            else if (box.center() != m_cut_contours.position) {
                m_cut_contours.shift = box.center() - m_cut_contours.position;
            }
        }
        else
            m_cut_contours.contours.reset();
}
References Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::GUI::GLGizmoPainterBase::CutContours::contours, Slic3r::GUI::GLGizmoPainterBase::CutContours::cut_z, Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_object_idx(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::ObjectBase::id(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::GLModel::init_from(), Slic3r::GUI::GLGizmoPainterBase::CutContours::instance_idx, Slic3r::TriangleMesh::its, m_cut_contours, Slic3r::GUI::GLGizmoBase::m_parent, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::GLGizmoPainterBase::CutContours::mesh, Slic3r::GUI::GLGizmoPainterBase::CutContours::object_id, Slic3r::GUI::GLGizmoPainterBase::CutContours::position, Slic3r::GUI::GLModel::reset(), Slic3r::GUI::GLModel::set_color(), Slic3r::GUI::GLGizmoPainterBase::CutContours::shift, Slic3r::slice_mesh(), Slic3r::MeshSlicingParams::trafo, and Slic3r::GLVolume::transformed_convex_hull_bounding_box().
Referenced by render_cursor_height_range().
update_from_model_object()
virtual void Slic3r::GUI::GLGizmoPainterBase::update_from_model_object (bool first_update) protected pure virtual
Implemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
Referenced by set_painter_gizmo_data().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
};
References Slic3r::GUI::GLGizmoBase::m_dirty.
update_model_object()
virtual void Slic3r::GUI::GLGizmoPainterBase::update_model_object () protected pure virtual
Implemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
Referenced by gizmo_event().
update_raycast_cache()
void Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache (const Vec2d & mouse_position, const Camera & camera, const std::vector< Transform3d > & trafo_matrices) const private
{
    if (m_rr.mouse_position == mouse_position) {
        // Same query as last time - the answer is already in the cache.
        return;
    }
    Vec3f normal =  Vec3f::Zero();
    Vec3f hit = Vec3f::Zero();
    size_t facet = 0;
    Vec3f closest_hit = Vec3f::Zero();
    double closest_hit_squared_distance = std::numeric_limits<double>::max();
    size_t closest_facet = 0;
    int closest_hit_mesh_id = -1;
    // Cast a ray on all meshes, pick the closest hit and save it for the respective mesh
    for (int mesh_id = 0; mesh_id < int(trafo_matrices.size()); ++mesh_id) {
        if (m_c->raycaster()->raycasters()[mesh_id]->unproject_on_mesh(
                   mouse_position,
                   trafo_matrices[mesh_id],
                   camera,
                   hit,
                   normal,
                   m_c->object_clipper()->get_clipping_plane(),
                   &facet,
                   m_parent.get_canvas_type() != GLCanvas3D::CanvasAssembleView))
        {
            // In case this hit is clipped, skip it.
            if (is_mesh_point_clipped(hit.cast<double>(), trafo_matrices[mesh_id]))
                continue;
            // Is this hit the closest to the camera so far?
            double hit_squared_distance = (camera.get_position()-trafo_matrices[mesh_id]*hit.cast<double>()).squaredNorm();
            if (hit_squared_distance < closest_hit_squared_distance) {
                closest_hit_squared_distance = hit_squared_distance;
                closest_facet = facet;
                closest_hit_mesh_id = mesh_id;
                closest_hit = hit;
            }
        }
    }
    m_rr = {mouse_position, closest_hit_mesh_id, closest_hit, closest_facet};
}
References Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::GUI::GLCanvas3D::get_canvas_type(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::Camera::get_position(), int, is_mesh_point_clipped(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_parent, m_rr, Slic3r::GUI::GLGizmoPainterBase::RaycastResult::mouse_position, Slic3r::normal(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::raycaster(), and Slic3r::GUI::CommonGizmosDataObjects::Raycaster::raycasters().
Referenced by get_projected_height_range(), get_projected_mouse_positions(), gizmo_event(), and render_cursor().
update_render_colors()
void Slic3r::GUI::GLGizmoBase::update_render_colors () static inherited
{
    GLGizmoBase::AXES_COLOR = { {
                                GLColor(RenderColor::colors[RenderCol_Grabber_X]),
                                GLColor(RenderColor::colors[RenderCol_Grabber_Y]),
                                GLColor(RenderColor::colors[RenderCol_Grabber_Z])
                                } };
    GLGizmoBase::FLATTEN_COLOR = GLColor(RenderColor::colors[RenderCol_Flatten_Plane]);
    GLGizmoBase::FLATTEN_HOVER_COLOR = GLColor(RenderColor::colors[RenderCol_Flatten_Plane_Hover]);
}
References Slic3r::GUI::GLGizmoBase::AXES_COLOR, Slic3r::RenderColor::colors, Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR, Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR, Slic3r::GLColor(), RenderCol_Flatten_Plane, RenderCol_Flatten_Plane_Hover, RenderCol_Grabber_X, RenderCol_Grabber_Y, and RenderCol_Grabber_Z.
Referenced by Slic3r::GUI::GLCanvas3D::_render_style_editor().
wants_enter_leave_snapshots()
bool Slic3r::GUI::GLGizmoPainterBase::wants_enter_leave_snapshots () const inline override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return true; }
Friends And Related Symbol Documentation
::Slic3r::GUI::GLGizmoMmuSegmentation
friend class ::Slic3r::GUI::GLGizmoMmuSegmentation friend
Member Data Documentation
AXES_COLOR
std::array< std::array< float, 4 >, 3 > Slic3r::GUI::GLGizmoBase::AXES_COLOR static inherited
Initial value:
= { {
                                                                { 1.0, 0.0f, 0.0f, 1.0f },
                                                                { 0.0f, 1.0f, 0.0f, 1.0f },
                                                                { 0.0f, 0.0f, 1.0f, 1.0f }
                                                                }}
Referenced by Slic3r::GUI::get_color(), Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
AXES_HOVER_COLOR
std::array< std::array< float, 4 >, 3 > Slic3r::GUI::GLGizmoBase::AXES_HOVER_COLOR static inherited
Initial value:
= {{
                                                                { 0.7f, 0.0f, 0.0f, 1.0f },
                                                                { 0.0f, 0.7f, 0.0f, 1.0f },
                                                                { 0.0f, 0.0f, 0.7f, 1.0f }
                                                                }}
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), and Slic3r::GUI::GLGizmoRotate::render_grabber().
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::GLGizmoBase::picking_color_component().
CONSTRAINED_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::CONSTRAINED_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f } static inherited
count
int Slic3r::GUI::GLGizmoBase::count = 0 private inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_count().
CursorHeightMax
constexpr float Slic3r::GUI::GLGizmoPainterBase::CursorHeightMax = 8.f static constexpr protected
Referenced by get_cursor_height_max(), and Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window().
CursorHeightMin
constexpr float Slic3r::GUI::GLGizmoPainterBase::CursorHeightMin = 0.1f static constexpr protected
Referenced by get_cursor_height_min(), and Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window().
CursorHeightStep
constexpr float Slic3r::GUI::GLGizmoPainterBase::CursorHeightStep = 0.2f static constexpr protected
Referenced by get_cursor_height_step().
CursorRadiusMax
constexpr float Slic3r::GUI::GLGizmoPainterBase::CursorRadiusMax = 8.f static constexpr protected
Referenced by get_cursor_radius_max(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
CursorRadiusMin
constexpr float Slic3r::GUI::GLGizmoPainterBase::CursorRadiusMin = 0.4f static constexpr protected
Referenced by get_cursor_radius_min(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
CursorRadiusStep
constexpr float Slic3r::GUI::GLGizmoPainterBase::CursorRadiusStep = 0.2f static constexpr protected
Referenced by get_cursor_radius_step().
DEFAULT_BASE_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_BASE_COLOR = { 0.625f, 0.625f, 0.625f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
DEFAULT_DRAG_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_DRAG_COLOR = { 1.0f, 1.0f, 1.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
DEFAULT_HIGHLIGHT_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_HIGHLIGHT_COLOR = { 1.0f, 0.38f, 0.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
FLATTEN_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR = { 0.96f, 0.93f, 0.93f, 0.5f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoFlatten::on_render(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
FLATTEN_HOVER_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR = { 1.0f, 1.0f, 1.0f, 0.75f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoFlatten::on_render(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
GRABBER_HOVER_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_HOVER_COL = {0.863f, 0.125f, 0.063f, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::Grabber().
GRABBER_NORMAL_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_NORMAL_COL = {1.0f, 1.0f, 1.0f, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::Grabber().
GRABBER_UNIFORM_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_UNIFORM_COL = {0, 1.0, 1.0, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
GRABBER_UNIFORM_HOVER_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_UNIFORM_HOVER_COL = {0, 0.7, 0.7, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
INV_ZOOM
float Slic3r::GUI::GLGizmoBase::INV_ZOOM = 1.0f static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_render_current_gizmo(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoBase::Grabber::render(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), and Slic3r::GUI::GLGizmoRotate::render_grabber_extension().
last_input_window_width
float Slic3r::GUI::GLGizmoBase::last_input_window_width = 0 protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), and Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos().
m_base_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_base_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
m_button_down
Button Slic3r::GUI::GLGizmoPainterBase::m_button_down = Button::None private
Referenced by gizmo_event(), render_cursor_circle(), and render_cursor_sphere().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c protected inherited
Referenced by Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), Slic3r::GUI::GLGizmoAdvancedCut::check_conflict_for_all_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::delete_selected_connectors(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), get_clipping_plane_data(), get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), get_projected_height_range(), get_projected_mouse_positions(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoHollow::hollow_mesh(), Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), is_mesh_point_clipped(), Slic3r::GUI::GLGizmoText::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoAdvancedCut::is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::GUI::GLGizmoMeshBoolean::on_load(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), Slic3r::GUI::GLGizmoSeam::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), Slic3r::GUI::GLGizmoHollow::on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::GLGizmoFaceDetector::perform_recognition(), Slic3r::GUI::GLGizmoAdvancedCut::process_cut_line(), Slic3r::GUI::GLGizmoAdvancedCut::put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), Slic3r::GUI::GLGizmoAdvancedCut::render_clipper_cut(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), render_cursor(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoAdvancedCut::reset_connectors(), Slic3r::GUI::GLGizmoSlaSupports::reslice_SLA_supports(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), set_painter_gizmo_data(), Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoAdvancedCut::unproject_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoAdvancedCut::update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoText::update_raycast_cache(), update_raycast_cache(), and Slic3r::GUI::GLGizmoText::update_text_positions().
m_cone
GLModel Slic3r::GUI::GLGizmoBase::m_cone protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_cursor_height
float Slic3r::GUI::GLGizmoPainterBase::m_cursor_height = 0.2f protected
Referenced by get_projected_height_range(), gizmo_event(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and render_cursor_height_range().
m_cursor_radius
float Slic3r::GUI::GLGizmoPainterBase::m_cursor_radius = 1.f protected
Referenced by get_projected_mouse_positions(), gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), render_cursor_circle(), and render_cursor_sphere().
m_cursor_type
TriangleSelector::CursorType Slic3r::GUI::GLGizmoPainterBase::m_cursor_type = TriangleSelector::SPHERE protected
Referenced by Slic3r::GUI::GLGizmoFdmSupports::GLGizmoFdmSupports(), gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), and render_cursor().
m_cut_contours
CutContours Slic3r::GUI::GLGizmoPainterBase::m_cut_contours mutable private
Referenced by render_cursor_height_range(), and update_contours().
m_cylinder
GLModel Slic3r::GUI::GLGizmoBase::m_cylinder protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_drag_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_drag_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::on_render(), and Slic3r::GUI::GLGizmoRotate::render_grabber().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::stop_dragging().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::disable_grabber(), Slic3r::GUI::GLGizmoBase::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoText::on_init(), Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::stop_dragging().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_group_id(), Slic3r::GUI::GLGizmoBase::picking_color_component(), and Slic3r::GUI::GLGizmoBase::set_group_id().
m_highlight_by_angle_threshold_deg
float Slic3r::GUI::GLGizmoPainterBase::m_highlight_by_angle_threshold_deg = 0.f protected
Referenced by gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), and Slic3r::GUI::GLGizmoSeam::render_triangles().
m_highlight_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_highlight_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::set_highlight_color().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id protected inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::calc_ratio(), Slic3r::GUI::GLGizmoScale3D::do_scale_along_axis(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoAdvancedCut::is_selection_changed(), Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoCut::on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_stop_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), Slic3r::GUI::GLGizmoAdvancedCut::on_update(), Slic3r::GUI::GLGizmoCut::on_update(), Slic3r::GUI::GLGizmoHollow::on_update(), Slic3r::GUI::GLGizmoMove3D::on_update(), Slic3r::GUI::GLGizmoScale3D::on_update(), Slic3r::GUI::GLGizmoSlaSupports::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::update().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename(), and Slic3r::GUI::GLGizmoBase::set_icon_filename().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), Slic3r::GUI::GLGizmoBase::GizmoImguiBegin(), Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data(), Slic3r::GUI::GLGizmoText::on_init(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoMove3D::on_render_input_window(), Slic3r::GUI::GLGizmoScale3D::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_combo(), Slic3r::GUI::GLGizmoAdvancedCut::render_connect_type_radio_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoAdvancedCut::render_input_window_warning(), Slic3r::GUI::GLGizmoAdvancedCut::render_reset_button(), Slic3r::GUI::GLGizmoAdvancedCut::render_slider_double_input(), render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::update_font_texture().
m_internal_stack_active
bool Slic3r::GUI::GLGizmoPainterBase::m_internal_stack_active = false private
m_is_dark_mode
bool Slic3r::GUI::GLGizmoBase::m_is_dark_mode = false protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::on_change_color_mode(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoText::push_button_style(), and Slic3r::GUI::GLGizmoText::push_combo_style().
m_last_mouse_click
Vec2d Slic3r::GUI::GLGizmoPainterBase::m_last_mouse_click = Vec2d::Zero() private
Referenced by get_projected_mouse_positions(), and gizmo_event().
m_old_mo_id
ObjectID Slic3r::GUI::GLGizmoPainterBase::m_old_mo_id private
Referenced by on_set_state(), and set_painter_gizmo_data().
m_old_state
EState Slic3r::GUI::GLGizmoPainterBase::m_old_state = Off private
Referenced by on_set_state().
m_old_volumes_size
size_t Slic3r::GUI::GLGizmoPainterBase::m_old_volumes_size = 0 private
Referenced by set_painter_gizmo_data().
m_paint_on_overhangs_only
bool Slic3r::GUI::GLGizmoPainterBase::m_paint_on_overhangs_only = false protected
Referenced by gizmo_event(), and Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by Slic3r::GUI::GLGizmoAdvancedCut::add_connector(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), Slic3r::GUI::GLGizmoAdvancedCut::bounding_box(), Slic3r::GUI::GLGizmoCut::bounding_box(), bounding_box(), Slic3r::GUI::GLGizmoText::bounding_box(), Slic3r::GUI::GLGizmoSimplify::close(), Slic3r::GUI::GLGizmoAdvancedCut::delete_selected_connectors(), Slic3r::GUI::GLGizmoText::delete_temp_preview_text_volume(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoAdvancedCut::get_plane_points_world_coord(), get_projected_height_range(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoText::get_text_mesh(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::GUI::GLGizmoAdvancedCut::on_is_activable(), Slic3r::GUI::GLGizmoCut::on_is_activable(), Slic3r::GUI::GLGizmoFaceDetector::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeshBoolean::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoText::on_is_activable(), Slic3r::GUI::GLGizmoAdvancedCut::on_load(), Slic3r::GUI::GLGizmoFdmSupports::on_opening(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoHollow::on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_render_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoText::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window(), render_cursor(), render_cursor_circle(), render_cursor_height_range(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), Slic3r::GUI::GLGizmoAdvancedCut::reset_cut_plane(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut::update_contours(), update_contours(), Slic3r::GUI::GLGizmoText::update_font_texture(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), update_raycast_cache(), and Slic3r::GUI::GLGizmoText::update_text_positions().
m_rr
RaycastResult Slic3r::GUI::GLGizmoPainterBase::m_rr mutable private
Referenced by get_projected_height_range(), get_projected_mouse_positions(), gizmo_event(), render_cursor(), render_cursor_height_range(), render_cursor_sphere(), and update_raycast_cache().
m_schedule_update
bool Slic3r::GUI::GLGizmoPainterBase::m_schedule_update = false private
Referenced by on_load(), and set_painter_gizmo_data().
m_seed_fill_last_mesh_id
int Slic3r::GUI::GLGizmoPainterBase::m_seed_fill_last_mesh_id = -1 protected
Referenced by gizmo_event().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoAdvancedCut::on_init(), Slic3r::GUI::GLGizmoCut::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), Slic3r::GUI::GLGizmoHollow::on_init(), Slic3r::GUI::GLGizmoMeshBoolean::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), Slic3r::GUI::GLGizmoSlaSupports::on_init(), and Slic3r::GUI::GLGizmoText::on_init().
m_smart_fill_angle
float Slic3r::GUI::GLGizmoPainterBase::m_smart_fill_angle = 30.f protected
Referenced by gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), and Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window().
m_sphere
GLModel Slic3r::GUI::GLGizmoBase::m_sphere protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_state
EState Slic3r::GUI::GLGizmoBase::m_state protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoBase::load(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeshBoolean::on_set_state(), on_set_state(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoText::on_set_state(), set_painter_gizmo_data(), Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::GUI::GLGizmoBase::set_state(), and Slic3r::GUI::GLGizmoSimplify::worker_finished().
m_tool_type
ToolType Slic3r::GUI::GLGizmoPainterBase::m_tool_type = ToolType::BRUSH protected
Referenced by Slic3r::GUI::GLGizmoFdmSupports::GLGizmoFdmSupports(), gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), render_cursor(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), and Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information().
m_tooltip
std::string Slic3r::GUI::GLGizmoBase::m_tooltip mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render().
m_triangle_selectors
std::vector<std::unique_ptr<TriangleSelectorGUI> > Slic3r::GUI::GLGizmoPainterBase::m_triangle_selectors protected
Referenced by gizmo_event(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), on_set_state(), render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoFdmSupports::tool_changed(), Slic3r::GUI::GLGizmoMmuSegmentation::tool_changed(), Slic3r::GUI::GLGizmoSeam::tool_changed(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), and Slic3r::GUI::GLGizmoMmuSegmentation::update_triangle_selectors_colors().
m_triangle_splitting_enabled
bool Slic3r::GUI::GLGizmoPainterBase::m_triangle_splitting_enabled = true protected
Referenced by gizmo_event().
m_vbo_sphere
GLIndexedVertexArray Slic3r::GUI::GLGizmoPainterBase::m_vbo_sphere private
Referenced by GLGizmoPainterBase(), and render_cursor_sphere().
SmartFillAngleMax
constexpr float Slic3r::GUI::GLGizmoPainterBase::SmartFillAngleMax = 90.f static constexpr protected
Referenced by gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), and Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window().
SmartFillAngleMin
constexpr float Slic3r::GUI::GLGizmoPainterBase::SmartFillAngleMin = 0.0f static constexpr protected
Referenced by gizmo_event(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), and Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window().
SmartFillAngleStep
constexpr float Slic3r::GUI::GLGizmoPainterBase::SmartFillAngleStep = 1.f static constexpr protected
Referenced by gizmo_event().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoPainterBase.hpp
src/slic3r/GUI/Gizmos/GLGizmoPainterBase.cpp