OrcaSlicer: Slic3r::GUI::Fan Class Reference
Slic3r::GUI::Fan Class Reference
#include <src/slic3r/GUI/Widgets/FanControl.hpp>
Public Member Functions
Fan (wxWindow *parent, wxWindowID id, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
~Fan ()
void post_event (wxCommandEvent &&event)
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
void msw_rescale ()
void create (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size)
void set_fan_speeds (int g)
Protected Member Functions
virtual void DoSetSize (int x, int y, int width, int height, int sizeFlags=wxSIZE_AUTO)
Protected Attributes
std::vector< wxPoint > m_scale_pos_array
ScalableBitmap m_bitmap_bk
ScalableBitmap m_bitmap_scale_0
ScalableBitmap m_bitmap_scale_1
ScalableBitmap m_bitmap_scale_2
ScalableBitmap m_bitmap_scale_3
ScalableBitmap m_bitmap_scale_4
ScalableBitmap m_bitmap_scale_5
ScalableBitmap m_bitmap_scale_6
ScalableBitmap m_bitmap_scale_7
ScalableBitmap m_bitmap_scale_8
ScalableBitmap m_bitmap_scale_9
ScalableBitmap m_bitmap_scale_10
std::vector< ScalableBitmap > m_bitmap_scales
wxImage m_img_pointer
Private Attributes
int m_current_speeds
std::vector< RotateOffSet > m_rotate_offsets
Detailed Description
Constructor & Destructor Documentation
Fan()
Slic3r::GUI::Fan::Fan (wxWindow * parent, wxWindowID id, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
{
    create(parent, id, pos, size);
}
References create(), and size.
~Fan()
Slic3r::GUI::Fan::~Fan () inline
{};
Member Function Documentation
create()
void Slic3r::GUI::Fan::create (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size)
{
    m_current_speeds  = 0;
    wxWindow::Create(parent, id, pos, size, wxBORDER_NONE);
    SetBackgroundColour(*wxWHITE);
    m_rotate_offsets.push_back(RotateOffSet{ 2.5, wxPoint(-FromDIP(16), FromDIP(11)) });
    m_rotate_offsets.push_back(RotateOffSet{ 2.2, wxPoint(-FromDIP(20), FromDIP(11)) });
    m_rotate_offsets.push_back(RotateOffSet{ 1.7, wxPoint(-FromDIP(24), FromDIP(12)) });
    m_rotate_offsets.push_back(RotateOffSet{ 1.2, wxPoint(-FromDIP(22), FromDIP(4)) });
    m_rotate_offsets.push_back(RotateOffSet{ 0.7, wxPoint(-FromDIP(17), -FromDIP(6)) });
    m_rotate_offsets.push_back(RotateOffSet{ 0.3, wxPoint(-FromDIP(8), -FromDIP(11)) });
    m_rotate_offsets.push_back(RotateOffSet{ 6.1, wxPoint(-FromDIP(0), -FromDIP(9)) });
    m_rotate_offsets.push_back(RotateOffSet{ 5.5, wxPoint(-FromDIP(4), -FromDIP(2)) });
    m_rotate_offsets.push_back(RotateOffSet{ 5.1, wxPoint(-FromDIP(3), FromDIP(5)) });
    m_rotate_offsets.push_back(RotateOffSet{ 4.6, wxPoint(-FromDIP(3), FromDIP(14)) });
    m_rotate_offsets.push_back(RotateOffSet{ 4.0, wxPoint(-FromDIP(2), FromDIP(11)) });
    //auto m_bitmap_pointer  = ScalableBitmap(this, "fan_pointer", FromDIP(25));
    //m_img_pointer     = m_bitmap_pointer.bmp().ConvertToImage();
    m_bitmap_bk  = ScalableBitmap(this, "fan_dash_bk", FromDIP(80));
    for (auto i = 0; i <= 10; i++) {
#ifdef __APPLE__
        auto m_bitmap_scale  = ScalableBitmap(this, wxString::Format("fan_scale_%d", i).ToStdString(), FromDIP(60));
        m_bitmap_scales.push_back(m_bitmap_scale);
#else
        auto m_bitmap_scale  = ScalableBitmap(this, wxString::Format("fan_scale_%d", i).ToStdString(), FromDIP(46));
        m_bitmap_scales.push_back(m_bitmap_scale);
#endif
    }
//#ifdef __APPLE__
//    SetMinSize(wxSize(FromDIP(100), FromDIP(100) + FromDIP(6)));
//    SetMaxSize(wxSize(FromDIP(100), FromDIP(100) + FromDIP(6)));
//#else
    SetMinSize(wxSize(m_bitmap_bk.GetBmpSize().x, m_bitmap_bk.GetBmpSize().y + FromDIP(6)));
    SetMaxSize(wxSize(m_bitmap_bk.GetBmpSize().x, m_bitmap_bk.GetBmpSize().y + FromDIP(6)));
//#endif // __APPLE__
    Bind(wxEVT_PAINT, &Fan::paintEvent, this);
}
References ScalableBitmap::GetBmpSize(), m_bitmap_bk, m_bitmap_scales, m_current_speeds, m_rotate_offsets, paintEvent(), and size.
Referenced by Fan().
doRender()
void Slic3r::GUI::Fan::doRender (wxDC & dc)
{
    auto rpm = wxT("rpm");
    wxSize size = GetSize();
    dc.DrawBitmap(m_bitmap_bk.bmp(), wxPoint(0,0));
    //fan scale
    /*auto central_point = wxPoint(size.x / 2, size.y / 2 + FromDIP(15));
    dc.DrawBitmap(m_bitmap_scale_0.bmp(), central_point.x - FromDIP(38), central_point.y);
    dc.DrawBitmap(m_bitmap_scale_1.bmp(), central_point.x - FromDIP(40), central_point.y - FromDIP(17));
    dc.DrawBitmap(m_bitmap_scale_2.bmp(), central_point.x - FromDIP(40), central_point.y - FromDIP(36));
    dc.DrawBitmap(m_bitmap_scale_3.bmp(), central_point.x - FromDIP(32), central_point.y - FromDIP(48));
    dc.DrawBitmap(m_bitmap_scale_4.bmp(), central_point.x - FromDIP(18), central_point.y - FromDIP(53));
    dc.DrawBitmap(m_bitmap_scale_5.bmp(), central_point.x - FromDIP(0),  central_point.y  - FromDIP(53));
    dc.DrawBitmap(m_bitmap_scale_6.bmp(), central_point.x + FromDIP(18), central_point.y - FromDIP(48));
    dc.DrawBitmap(m_bitmap_scale_7.bmp(), central_point.x + FromDIP(31), central_point.y - FromDIP(36));
    dc.DrawBitmap(m_bitmap_scale_8.bmp(), central_point.x + FromDIP(36), central_point.y - FromDIP(17));
    dc.DrawBitmap(m_bitmap_scale_9.bmp(), central_point.x + FromDIP(28), central_point.y);*/
    //fan pointer
    //auto pointer_central_point = wxPoint((size.x - m_img_pointer.GetSize().x) / 2, (size.y - m_img_pointer.GetSize().y) / 2);
    //auto bmp = m_img_pointer.Rotate(m_rotate_offsets[m_current_speeds].rotate, wxPoint(size.x / 2,size.y / 2));
    auto central_point = wxPoint((size.x  - m_bitmap_scales[m_current_speeds].GetBmpSize().x) / 2, (size.y  - m_bitmap_scales[m_current_speeds].GetBmpSize().y) / 2 - FromDIP(4));
    dc.DrawBitmap(m_bitmap_scales[m_current_speeds].bmp(), central_point.x, central_point.y);
    //fan val
    dc.SetTextForeground(DRAW_TEXT_COLOUR);
    dc.SetFont(::Label::Head_13);
    auto speeds = wxString::Format("%d%%", m_current_speeds * 10);
    dc.DrawText(speeds, (size.x - dc.GetTextExtent(speeds).x) / 2 + FromDIP(2), size.y - dc.GetTextExtent(speeds).y - FromDIP(5));
    //rpm
    //dc.SetFont(::Label::Body_13);
    //dc.DrawText(rpm, (size.x - dc.GetTextExtent(rpm).x) / 2, size.y - dc.GetTextExtent(rpm).y);
}
References ScalableBitmap::bmp(), DRAW_TEXT_COLOUR, Label::Head_13, m_bitmap_bk, m_bitmap_scales, m_current_speeds, and size.
Referenced by render().
DoSetSize()
void Slic3r::GUI::Fan::DoSetSize (int x, int y, int width, int height, int sizeFlags = wxSIZE_AUTO) protected virtual
{
    wxWindow::DoSetSize(x, y, width, height, sizeFlags);
}
msw_rescale()
void Slic3r::GUI::Fan::msw_rescale ()
                      {
   m_bitmap_bk.msw_rescale();
}
References m_bitmap_bk, and ScalableBitmap::msw_rescale().
paintEvent()
void Slic3r::GUI::Fan::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by create().
post_event()
void Slic3r::GUI::Fan::post_event (wxCommandEvent && event)
{
    /*event.SetString(m_info.can_id);
    event.SetEventObject(m_parent);
    wxPostEvent(m_parent, event);
    event.Skip();*/
}
render()
void Slic3r::GUI::Fan::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
set_fan_speeds()
void Slic3r::GUI::Fan::set_fan_speeds (int g)
{
    m_current_speeds = g;
    Refresh();
}
References m_current_speeds.
Referenced by Slic3r::GUI::FanControl::FanControl(), and Slic3r::GUI::FanControl::set_fan_speed().
Member Data Documentation
m_bitmap_bk
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_bk protected
Referenced by create(), doRender(), and msw_rescale().
m_bitmap_scale_0
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_0 protected
m_bitmap_scale_1
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_1 protected
m_bitmap_scale_10
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_10 protected
m_bitmap_scale_2
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_2 protected
m_bitmap_scale_3
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_3 protected
m_bitmap_scale_4
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_4 protected
m_bitmap_scale_5
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_5 protected
m_bitmap_scale_6
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_6 protected
m_bitmap_scale_7
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_7 protected
m_bitmap_scale_8
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_8 protected
m_bitmap_scale_9
ScalableBitmap Slic3r::GUI::Fan::m_bitmap_scale_9 protected
m_bitmap_scales
std::vector<ScalableBitmap> Slic3r::GUI::Fan::m_bitmap_scales protected
Referenced by create(), and doRender().
m_current_speeds
int Slic3r::GUI::Fan::m_current_speeds private
Referenced by create(), doRender(), and set_fan_speeds().
m_img_pointer
wxImage Slic3r::GUI::Fan::m_img_pointer protected
m_rotate_offsets
std::vector<RotateOffSet> Slic3r::GUI::Fan::m_rotate_offsets private
Referenced by create().
m_scale_pos_array
std::vector<wxPoint> Slic3r::GUI::Fan::m_scale_pos_array protected
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/FanControl.hpp
src/slic3r/GUI/Widgets/FanControl.cpp