OrcaSlicer: Slic3r::GUI::UpgradeNetworkJob Class Reference
Slic3r::GUI::UpgradeNetworkJob Class Reference
#include <src/slic3r/GUI/Jobs/UpgradeNetworkJob.hpp>
Public Types
enum JobPrepareState { PREPARE_STATE_DEFAULT = 0 , PREPARE_STATE_MENU = 1 }
Public Member Functions
UpgradeNetworkJob (std::shared_ptr< ProgressIndicator > pri)
int status_range () const override
bool is_finished ()
void on_success (std::function< void()> success)
void update_status (int st, const wxString &msg)
void process () override
void finalize () override
void set_event_handle (wxWindow *hanle)
bool is_finalized () const
void start ()
bool join (int timeout_ms=0)
bool is_running () const
void cancel ()
Protected Member Functions
void on_exception (const std::exception_ptr &) override
void update_percent_finish ()
void show_networking_test (wxString msg)
bool was_canceled () const
virtual void prepare ()
Protected Attributes
std::string name
std::string package_name
Private Member Functions
void run (std::exception_ptr &)
Private Attributes
wxWindow * m_event_handle {nullptr}
std::function< void()> m_success_fun {nullptr}
bool m_job_finished { false }
int m_print_job_completed_id = 0
InstallProgressFn pro_fn { nullptr }
int m_range = 100
int m_thread_evt_id = wxID_ANY
boost::thread m_thread
std::atomic< bool > m_running {false}
std::atomic< bool > m_canceled {false}
bool m_finalized = false
bool m_finalizing = false
std::shared_ptr< ProgressIndicator > m_progress
std::exception_ptr m_worker_error = nullptr
Detailed Description
Member Enumeration Documentation
JobPrepareState
enum Slic3r::GUI::Job::JobPrepareState inherited
Enumerator
PREPARE_STATE_DEFAULT
PREPARE_STATE_MENU
{
        PREPARE_STATE_DEFAULT = 0,
        PREPARE_STATE_MENU = 1,
    };
Constructor & Destructor Documentation
UpgradeNetworkJob()
Slic3r::GUI::UpgradeNetworkJob::UpgradeNetworkJob (std::shared_ptr< ProgressIndicator > pri)
    : Job{std::move(pri)}
{
    name         = "plugins";
    package_name = "networking_plugins.zip";
}
References name, and package_name.
Member Function Documentation
cancel()
void Slic3r::GUI::Job::cancel () inline inherited
{ m_canceled.store(true); }
References Slic3r::GUI::Job::m_canceled.
Referenced by process().
finalize()
void Slic3r::GUI::UpgradeNetworkJob::finalize () override virtual
Reimplemented from Slic3r::GUI::Job.
{
    if (was_canceled()) return;
    Job::finalize();
}
References Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::was_canceled().
is_finalized()
bool Slic3r::GUI::Job::is_finalized () const inline inherited
{ return m_finalized; }
References Slic3r::GUI::Job::m_finalized.
is_finished()
bool Slic3r::GUI::UpgradeNetworkJob::is_finished () inline
{ return m_job_finished;  }
References m_job_finished.
is_running()
bool Slic3r::GUI::Job::is_running () const inline inherited
{ return m_running.load(); }
References Slic3r::GUI::Job::m_running.
join()
bool Slic3r::GUI::Job::join (int timeout_ms = 0) inherited
{
    if (!m_thread.joinable()) return true;
    if (timeout_ms <= 0)
        m_thread.join();
    else if (!m_thread.try_join_for(boost::chrono::milliseconds(timeout_ms)))
        return false;
    return true;
}
on_exception()
void Slic3r::GUI::UpgradeNetworkJob::on_exception (const std::exception_ptr & eptr) override protected virtual
Reimplemented from Slic3r::GUI::Job.
{
    try {
        if (eptr)
            std::rethrow_exception(eptr);
    } catch (std::exception &e) {
        UpgradeNetworkJob::on_exception(eptr);
    }
}
References on_exception().
Referenced by on_exception().
on_success()
void Slic3r::GUI::UpgradeNetworkJob::on_success (std::function< void()> success)
{
    m_success_fun = success;
}
References m_success_fun.
prepare()
virtual void Slic3r::GUI::Job::prepare () inline protected virtual inherited
Reimplemented in Slic3r::GUI::ArrangeJob, Slic3r::GUI::FillBedJob, Slic3r::GUI::OrientJob, Slic3r::GUI::PrintJob, Slic3r::GUI::RotoptimizeJob, Slic3r::GUI::SendJob, and Slic3r::GUI::SLAImportJob.
{}
process()
void Slic3r::GUI::UpgradeNetworkJob::process () override virtual
Implements Slic3r::GUI::Job.
{
    // downloading
    int result = 0;
    AppConfig* app_config = wxGetApp().app_config;
    if (!app_config)
        return;
    BOOST_LOG_TRIVIAL(info) << "[UpgradeNetworkJob process]: enter";
    // get temp path
    fs::path target_file_path = (fs::temp_directory_path() / package_name);
    fs::path tmp_path = target_file_path;
    auto path_str = tmp_path.string() + wxString::Format(".%d%s", get_current_pid(), ".tmp").ToStdString();
    tmp_path = fs::path(path_str);
    BOOST_LOG_TRIVIAL(info) << "UpgradeNetworkJob: save netowrk_plugin to " << tmp_path.string();
    auto cancel_fn = [this]() {
        return was_canceled();
    };
    int curr_percent = 0;
    result = wxGetApp().download_plugin(name, package_name,
        [this, &curr_percent](int state, int percent, bool &cancel) {
            if (state == InstallStatusNormal) {
                update_status(percent, _L("Downloading"));
            } else if (state == InstallStatusDownloadFailed) {
                update_status(percent, _L("Download failed"));
            } else {
                update_status(percent, _L("Downloading"));
            }
            curr_percent = percent;
        }, cancel_fn);
    if (was_canceled()) {
        update_status(0, _L("Cancelled"));
        wxCommandEvent event(wxEVT_CLOSE_WINDOW);
        event.SetEventObject(m_event_handle);
        wxPostEvent(m_event_handle, event);
        return;
    }
    if (result < 0) {
        update_status(0, _L("Download failed"));
        wxCommandEvent event(EVT_DOWNLOAD_NETWORK_FAILED);
        event.SetEventObject(m_event_handle);
        wxPostEvent(m_event_handle, event);
        return;
    }
    result = wxGetApp().install_plugin(
        name, package_name,
        [this](int state, int percent, bool &cancel) {
        if (state == InstallStatusInstallCompleted) {
            update_status(percent, _L("Install successfully."));
        } else {
            update_status(percent, _L("Installing"));
        }
        }, cancel_fn);
    if (was_canceled()) {
        update_status(0, _L("Cancelled"));
        wxCommandEvent event(wxEVT_CLOSE_WINDOW);
        event.SetEventObject(m_event_handle);
        wxPostEvent(m_event_handle, event);
        return;
    }
    if (result != 0) {
        update_status(0, _L("Install failed"));
        wxCommandEvent event(EVT_INSTALL_NETWORK_FAILED);
        event.SetEventObject(m_event_handle);
        wxPostEvent(m_event_handle, event);
        return;
    }
    wxCommandEvent event(EVT_UPGRADE_NETWORK_SUCCESS);
    event.SetEventObject(m_event_handle);
    wxPostEvent(m_event_handle, event);
    BOOST_LOG_TRIVIAL(info) << "[UpgradeNetworkJob process]: exit";
    return;
}
References _L, Slic3r::GUI::Job::cancel(), Slic3r::get_current_pid(), Slic3r::GUI::InstallStatusDownloadFailed, Slic3r::GUI::InstallStatusInstallCompleted, Slic3r::GUI::InstallStatusNormal, m_event_handle, name, package_name, update_status(), and Slic3r::GUI::Job::was_canceled().
run()
void Slic3r::GUI::Job::run (std::exception_ptr & eptr) private inherited
{
    m_running.store(true);
    try {
        process();
    } catch (...) {
        eptr = std::current_exception();
    }
    m_running.store(false);
    // ensure to call the last status to finalize the job
    update_status(status_range(), "");
}
References Slic3r::GUI::Job::m_running, Slic3r::GUI::Job::process(), Slic3r::GUI::Job::status_range(), and Slic3r::GUI::Job::update_status().
set_event_handle()
void Slic3r::GUI::UpgradeNetworkJob::set_event_handle (wxWindow * hanle)
{
    m_event_handle = hanle;
}
References m_event_handle.
show_networking_test()
void Slic3r::GUI::Job::show_networking_test (wxString msg) protected inherited
{
    m_progress->show_networking_test(msg);
}
Referenced by Slic3r::GUI::PrintJob::process().
start()
void Slic3r::GUI::Job::start () inherited
{ // Start the job. No effect if the job is already running
    if (!m_running.load()) {
        prepare();
        // Save the current status indicatior range and push the new one
        m_range = m_progress->get_range();
        m_progress->set_range(status_range());
        // init cancellation flag and set the cancel callback
        m_canceled.store(false);
        m_progress->set_cancel_callback(
                    [this]() { m_canceled.store(true); });
        m_finalized  = false;
        m_finalizing = false;
        // Changing cursor to busy
        wxBeginBusyCursor();
        try { // Execute the job
            m_worker_error = nullptr;
            m_thread = create_thread([this] { this->run(m_worker_error); });
        } catch (std::exception &) {
            update_status(status_range(),
                          _(L("Error! Unable to create thread!")));
        }
        // The state changes will be undone when the process hits the
        // last status value, in the status update handler (see ctor)
    }
}
References _, Slic3r::create_thread(), and L.
Referenced by Slic3r::GUI::OrientJob::process().
status_range()
int Slic3r::GUI::UpgradeNetworkJob::status_range () const inline override virtual
Reimplemented from Slic3r::GUI::Job.
    {
        return 100;
    }
update_percent_finish()
void Slic3r::GUI::Job::update_percent_finish () protected inherited
{
    m_progress->clear_percent();
}
Referenced by Slic3r::GUI::PrintJob::process().
update_status()
void Slic3r::GUI::UpgradeNetworkJob::update_status (int st, const wxString & msg)
{
    BOOST_LOG_TRIVIAL(info) << "UpgradeNetworkJob: percent = " << st << "msg = " << msg;
    GUI::Job::update_status(st, msg);
    wxCommandEvent event(EVT_UPGRADE_UPDATE_MESSAGE);
    event.SetString(msg);
    event.SetEventObject(m_event_handle);
    wxPostEvent(m_event_handle, event);
}
References m_event_handle, and Slic3r::GUI::Job::update_status().
Referenced by process().
was_canceled()
bool Slic3r::GUI::Job::was_canceled () const inline protected inherited
{ return m_canceled.load(); }
References Slic3r::GUI::Job::m_canceled.
Referenced by Slic3r::GUI::ArrangeJob::finalize(), Slic3r::GUI::BindJob::finalize(), Slic3r::GUI::FillBedJob::finalize(), Slic3r::GUI::OrientJob::finalize(), Slic3r::GUI::PrintJob::finalize(), Slic3r::GUI::RotoptimizeJob::finalize(), Slic3r::GUI::SendJob::finalize(), Slic3r::GUI::SLAImportJob::finalize(), finalize(), Slic3r::GUI::ArrangeJob::process(), Slic3r::GUI::FillBedJob::process(), Slic3r::GUI::OrientJob::process(), Slic3r::GUI::PrintJob::process(), Slic3r::GUI::RotoptimizeJob::process(), Slic3r::GUI::SendJob::process(), Slic3r::GUI::SLAImportJob::process(), and process().
Member Data Documentation
m_canceled
std::atomic<bool> Slic3r::GUI::Job::m_canceled {false} private inherited
Referenced by Slic3r::GUI::Job::cancel(), and Slic3r::GUI::Job::was_canceled().
m_event_handle
wxWindow* Slic3r::GUI::UpgradeNetworkJob::m_event_handle {nullptr} private
Referenced by process(), set_event_handle(), and update_status().
m_finalized
bool Slic3r::GUI::Job::m_finalized = false private inherited
Referenced by Slic3r::GUI::Job::Job(), Slic3r::GUI::Job::finalize(), and Slic3r::GUI::Job::is_finalized().
m_finalizing
bool Slic3r::GUI::Job::m_finalizing = false private inherited
Referenced by Slic3r::GUI::Job::Job().
m_job_finished
bool Slic3r::GUI::UpgradeNetworkJob::m_job_finished { false } private
Referenced by is_finished().
m_print_job_completed_id
int Slic3r::GUI::UpgradeNetworkJob::m_print_job_completed_id = 0 private
m_progress
std::shared_ptr<ProgressIndicator> Slic3r::GUI::Job::m_progress private inherited
Referenced by Slic3r::GUI::Job::Job().
m_range
int Slic3r::GUI::Job::m_range = 100 private inherited
Referenced by Slic3r::GUI::Job::Job().
m_running
std::atomic<bool> Slic3r::GUI::Job::m_running {false} private inherited
Referenced by Slic3r::GUI::Job::is_running(), and Slic3r::GUI::Job::run().
m_success_fun
std::function<void()> Slic3r::GUI::UpgradeNetworkJob::m_success_fun {nullptr} private
Referenced by on_success().
m_thread
boost::thread Slic3r::GUI::Job::m_thread private inherited
m_thread_evt_id
int Slic3r::GUI::Job::m_thread_evt_id = wxID_ANY private inherited
Referenced by Slic3r::GUI::Job::Job().
m_worker_error
std::exception_ptr Slic3r::GUI::Job::m_worker_error = nullptr private inherited
Referenced by Slic3r::GUI::Job::Job().
name
std::string Slic3r::GUI::UpgradeNetworkJob::name protected
Referenced by UpgradeNetworkJob(), and process().
package_name
std::string Slic3r::GUI::UpgradeNetworkJob::package_name protected
Referenced by UpgradeNetworkJob(), and process().
pro_fn
InstallProgressFn Slic3r::GUI::UpgradeNetworkJob::pro_fn { nullptr } private
The documentation for this class was generated from the following files:
src/slic3r/GUI/Jobs/UpgradeNetworkJob.hpp
src/slic3r/GUI/Jobs/UpgradeNetworkJob.cpp