OrcaSlicer: Slic3r::GUI::GLCanvas3D::SequentialPrintClearance Class Reference
Slic3r::GUI::GLCanvas3D::SequentialPrintClearance Class Reference
#include <src/slic3r/GUI/GLCanvas3D.hpp>
Public Member Functions
void set_polygons (const Polygons &polygons, const std::vector< std::pair< Polygon, float > > &height_polygons)
void set_render_fill (bool render_fill)
void set_visible (bool visible)
void render ()
Private Attributes
GLModel m_height_limit
GLModel m_fill
GLModel m_perimeter
bool m_render_fill { true }
bool m_visible { false }
std::vector< Pointf3s > m_hull_2d_cache
Friends
class GLCanvas3D
Detailed Description
Member Function Documentation
render()
void Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::render ()
{
    std::array<float, 4> FILL_COLOR = { 0.7f, 0.7f, 1.0f, 0.5f };
    std::array<float, 4> NO_FILL_COLOR = { 0.75f, 0.75f, 0.75f, 0.75f };
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glDisable(GL_CULL_FACE));
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    m_perimeter.set_color(-1, m_render_fill ? FILL_COLOR : NO_FILL_COLOR);
    m_perimeter.render();
    m_fill.render();
    //BBS: add height limit
    m_height_limit.set_color(-1, m_render_fill ? FILL_COLOR : NO_FILL_COLOR);
    m_height_limit.render();
    glsafe(::glDisable(GL_BLEND));
    glsafe(::glEnable(GL_CULL_FACE));
    glsafe(::glDisable(GL_DEPTH_TEST));
    shader->stop_using();
}
References glsafe, Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by Slic3r::GUI::GLCanvas3D::_render_sequential_clearance().
set_polygons()
void Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_polygons (const Polygons & polygons, const std::vector< std::pair< Polygon, float > > & height_polygons)
{
    //BBS: add height limit logic
    m_height_limit.reset();
    m_perimeter.reset();
    m_fill.reset();
    if (!polygons.empty()) {
        size_t triangles_count = 0;
        for (const Polygon &poly : polygons) { triangles_count += poly.points.size() - 2; }
        const size_t vertices_count = 3 * triangles_count;
        if (m_render_fill) {
            GLModel::InitializationData         fill_data;
            GLModel::InitializationData::Entity entity;
            entity.type  = GLModel::PrimitiveType::Triangles;
            entity.color = {0.8f, 0.8f, 1.0f, 0.5f};
            entity.positions.reserve(vertices_count);
            entity.normals.reserve(vertices_count);
            entity.indices.reserve(vertices_count);
            const ExPolygons polygons_union = union_ex(polygons);
            for (const ExPolygon &poly : polygons_union) {
                const std::vector<Vec3d> triangulation = triangulate_expolygon_3d(poly);
                for (const Vec3d &v : triangulation) {
                    entity.positions.emplace_back(v.cast<float>() + Vec3f(0.0f, 0.0f, 0.0125f)); // add a small positive z to avoid z-fighting
                    entity.normals.emplace_back(Vec3f::UnitZ());
                    const size_t positions_count = entity.positions.size();
                    if (positions_count % 3 == 0) {
                        entity.indices.emplace_back(positions_count - 3);
                        entity.indices.emplace_back(positions_count - 2);
                        entity.indices.emplace_back(positions_count - 1);
                    }
                }
            }
            fill_data.entities.emplace_back(entity);
            m_fill.init_from(fill_data);
        }
        GLModel::InitializationData perimeter_data;
        for (const Polygon &poly : polygons) {
            GLModel::InitializationData::Entity ent;
            ent.type = GLModel::PrimitiveType::LineLoop;
            ent.positions.reserve(poly.points.size());
            ent.indices.reserve(poly.points.size());
            unsigned int id_count = 0;
            for (const Point &p : poly.points) {
                ent.positions.emplace_back(unscale<float>(p.x()), unscale<float>(p.y()), 0.025f); // add a small positive z to avoid z-fighting
                ent.normals.emplace_back(Vec3f::UnitZ());
                ent.indices.emplace_back(id_count++);
            }
            perimeter_data.entities.emplace_back(ent);
        }
        m_perimeter.init_from(perimeter_data);
    }
    //BBS: add the height limit compute logic
    if (!height_polygons.empty()) {
        size_t height_triangles_count = 0;
        for (const auto &poly : height_polygons) { height_triangles_count += poly.first.points.size() - 2; }
        const size_t height_vertices_count = 3 * height_triangles_count;
        GLModel::InitializationData         height_fill_data;
        GLModel::InitializationData::Entity height_entity;
        height_entity.type  = GLModel::PrimitiveType::Triangles;
        height_entity.color = {0.8f, 0.8f, 1.0f, 0.5f};
        height_entity.positions.reserve(height_vertices_count);
        height_entity.normals.reserve(height_vertices_count);
        height_entity.indices.reserve(height_vertices_count);
        for (const auto &poly : height_polygons) {
            ExPolygon                ex_poly(poly.first);
            const std::vector<Vec3d> height_triangulation = triangulate_expolygon_3d(ex_poly);
            for (const Vec3d &v : height_triangulation) {
                Vec3d point{v.x(), v.y(), poly.second};
                height_entity.positions.emplace_back(point.cast<float>());
                height_entity.normals.emplace_back(Vec3f::UnitZ());
                const size_t height_positions_count = height_entity.positions.size();
                if (height_positions_count % 3 == 0) {
                    height_entity.indices.emplace_back(height_positions_count - 3);
                    height_entity.indices.emplace_back(height_positions_count - 2);
                    height_entity.indices.emplace_back(height_positions_count - 1);
                }
            }
        }
        height_fill_data.entities.emplace_back(height_entity);
        m_height_limit.init_from(height_fill_data);
    }
}
References Slic3r::GUI::GLModel::InitializationData::Entity::color, Slic3r::GUI::GLModel::InitializationData::entities, Slic3r::GUI::GLModel::InitializationData::Entity::indices, Slic3r::GUI::GLModel::LineLoop, Slic3r::GUI::GLModel::InitializationData::Entity::normals, Slic3r::GUI::GLModel::InitializationData::Entity::positions, Slic3r::GUI::GLModel::Triangles, Slic3r::triangulate_expolygon_3d(), Slic3r::GUI::GLModel::InitializationData::Entity::type, and Slic3r::union_ex().
Referenced by Slic3r::GUI::GLCanvas3D::reset_sequential_print_clearance(), and Slic3r::GUI::GLCanvas3D::set_sequential_print_clearance_polygons().
set_render_fill()
void Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_render_fill (bool render_fill) inline
{ m_render_fill = render_fill; }
References m_render_fill.
Referenced by Slic3r::GUI::GLCanvas3D::reset_sequential_print_clearance(), and Slic3r::GUI::GLCanvas3D::set_sequential_print_clearance_render_fill().
set_visible()
void Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::set_visible (bool visible) inline
{ m_visible = visible; }
References m_visible.
Referenced by Slic3r::GUI::GLCanvas3D::reset_sequential_print_clearance(), and Slic3r::GUI::GLCanvas3D::set_sequential_print_clearance_visible().
Friends And Related Symbol Documentation
GLCanvas3D
friend class GLCanvas3D friend
Member Data Documentation
m_fill
GLModel Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_fill private
m_height_limit
GLModel Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_height_limit private
m_hull_2d_cache
std::vector<Pointf3s> Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_hull_2d_cache private
Referenced by Slic3r::GUI::GLCanvas3D::update_sequential_clearance().
m_perimeter
GLModel Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_perimeter private
m_render_fill
bool Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_render_fill { true } private
Referenced by set_render_fill().
m_visible
bool Slic3r::GUI::GLCanvas3D::SequentialPrintClearance::m_visible { false } private
Referenced by set_visible().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp