OrcaSlicer: src/expat/xmltok_impl.inc File Reference
xmltok_impl.inc File Reference
Variables
</" */ static int PTRCALL PREFIX(scanEndTag)(const ENCODING *enc, const char *ptr, const char *end, const char **nextTokPtr) { REQUIRE_CHAR(enc, ptr, end); switch (BYTE_TYPE(enc, ptr)) { CHECK_NMSTRT_CASES(enc, ptr, end, nextTokPtr) default: *nextTokPtr = ptr; return XML_TOK_INVALID; } while (HAS_CHAR(enc, ptr, end)) { switch (BYTE_TYPE(enc, ptr)) { CHECK_NAME_CASES(enc, ptr, end, nextTokPtr) case BT_S: case BT_CR: case BT_LF: for (ptr += MINBPC(enc); HAS_CHAR(enc, ptr, end); ptr += MINBPC(enc)) { switch (BYTE_TYPE(enc, ptr)) { case BT_S: case BT_CR: case BT_LF: break; case BT_GT: *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_END_TAG; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } return XML_TOK_PARTIAL; #ifdef XML_NS case BT_COLON: ptr += MINBPC(enc); break; #endif case BT_GT: *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_END_TAG; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } return XML_TOK_PARTIAL; } static int PTRCALL PREFIX(scanHexCharRef)(const ENCODING *enc, const char *ptr, const char *end, const char **nextTokPtr) { if (HAS_CHAR(enc, ptr, end)) { switch (BYTE_TYPE(enc, ptr)) { case BT_DIGIT: case BT_HEX: break; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } for (ptr += MINBPC(enc); HAS_CHAR(enc, ptr, end); ptr += MINBPC(enc)) { switch (BYTE_TYPE(enc, ptr)) { case BT_DIGIT: case BT_HEX: break; case BT_SEMI: *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_CHAR_REF; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } } return XML_TOK_PARTIAL; } static int PTRCALL PREFIX(scanCharRef)(const ENCODING *enc, const char *ptr, const char *end, const char **nextTokPtr) { if (HAS_CHAR(enc, ptr, end)) { if (CHAR_MATCHES(enc, ptr, ASCII_x)) return PREFIX(scanHexCharRef)(enc, ptr + MINBPC(enc), end, nextTokPtr); switch (BYTE_TYPE(enc, ptr)) { case BT_DIGIT: break; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } for (ptr += MINBPC(enc); HAS_CHAR(enc, ptr, end); ptr += MINBPC(enc)) { switch (BYTE_TYPE(enc, ptr)) { case BT_DIGIT: break; case BT_SEMI: *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_CHAR_REF; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } } return XML_TOK_PARTIAL; } static int PTRCALL PREFIX(scanRef)(const ENCODING *enc, const char *ptr, const char *end, const char **nextTokPtr) { REQUIRE_CHAR(enc, ptr, end); switch (BYTE_TYPE(enc, ptr)) { CHECK_NMSTRT_CASES(enc, ptr, end, nextTokPtr) case BT_NUM: return PREFIX(scanCharRef)(enc, ptr + MINBPC(enc), end, nextTokPtr); default: *nextTokPtr = ptr; return XML_TOK_INVALID; } while (HAS_CHAR(enc, ptr, end)) { switch (BYTE_TYPE(enc, ptr)) { CHECK_NAME_CASES(enc, ptr, end, nextTokPtr) case BT_SEMI: *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_ENTITY_REF; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } return XML_TOK_PARTIAL; } static int PTRCALL PREFIX(scanAtts)(const ENCODING *enc, const char *ptr, const char *end, const char **nextTokPtr) { #ifdef XML_NS int hadColon = 0; #endif while (HAS_CHAR(enc, ptr, end)) { switch (BYTE_TYPE(enc, ptr)) { CHECK_NAME_CASES(enc, ptr, end, nextTokPtr) #ifdef XML_NS case BT_COLON: if (hadColon) { *nextTokPtr = ptr; return XML_TOK_INVALID; } hadColon = 1; ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); switch (BYTE_TYPE(enc, ptr)) { CHECK_NMSTRT_CASES(enc, ptr, end, nextTokPtr) default: *nextTokPtr = ptr; return XML_TOK_INVALID; } break; #endif case BT_S: case BT_CR: case BT_LF: for (;;) { int t; ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); t = BYTE_TYPE(enc, ptr); if (t == BT_EQUALS) break; switch (t) { case BT_S: case BT_LF: case BT_CR: break; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } case BT_EQUALS: { int open; #ifdef XML_NS hadColon = 0; #endif for (;;) { ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); open = BYTE_TYPE(enc, ptr); if (open == BT_QUOT || open == BT_APOS) break; switch (open) { case BT_S: case BT_LF: case BT_CR: break; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } ptr += MINBPC(enc); for (;;) { int t; REQUIRE_CHAR(enc, ptr, end); t = BYTE_TYPE(enc, ptr); if (t == open) break; switch (t) { INVALID_CASES(ptr, nextTokPtr) case BT_AMP: { int tok = PREFIX(scanRef)(enc, ptr + MINBPC(enc), end, &ptr); if (tok <= 0) { if (tok == XML_TOK_INVALID) *nextTokPtr = ptr; return tok; } break; } case BT_LT: *nextTokPtr = ptr; return XML_TOK_INVALID; default: ptr += MINBPC(enc); break; } } ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); switch (BYTE_TYPE(enc, ptr)) { case BT_S: case BT_CR: case BT_LF: break; case BT_SOL: goto sol; case BT_GT: goto gt; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } for (;;) { ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); switch (BYTE_TYPE(enc, ptr)) { CHECK_NMSTRT_CASES(enc, ptr, end, nextTokPtr) case BT_S: case BT_CR: case BT_LF: continue; case BT_GT: gt: *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_START_TAG_WITH_ATTS; case BT_SOL: sol: ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); if (!CHAR_MATCHES(enc, ptr, ASCII_GT)) { *nextTokPtr = ptr; return XML_TOK_INVALID; } *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_EMPTY_ELEMENT_WITH_ATTS; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } break; } break; } default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } return XML_TOK_PARTIAL; } static int PTRCALL PREFIX(scanLt)(const ENCODING *enc, const char *ptr, const char *end, const char **nextTokPtr) { #ifdef XML_NS int hadColon; #endif REQUIRE_CHAR(enc, ptr, end); switch (BYTE_TYPE(enc, ptr)) { CHECK_NMSTRT_CASES(enc, ptr, end, nextTokPtr) case BT_EXCL: ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); switch (BYTE_TYPE(enc, ptr)) { case BT_MINUS: return PREFIX(scanComment)(enc, ptr + MINBPC(enc), end, nextTokPtr); case BT_LSQB: return PREFIX(scanCdataSection)(enc, ptr + MINBPC(enc), end, nextTokPtr); } *nextTokPtr = ptr; return XML_TOK_INVALID; case BT_QUEST: return PREFIX(scanPi)(enc, ptr + MINBPC(enc), end, nextTokPtr); case BT_SOL: return PREFIX(scanEndTag)(enc, ptr + MINBPC(enc), end, nextTokPtr); default: *nextTokPtr = ptr; return XML_TOK_INVALID; } #ifdef XML_NS hadColon = 0; #endif while (HAS_CHAR(enc, ptr, end)) { switch (BYTE_TYPE(enc, ptr)) { CHECK_NAME_CASES(enc, ptr, end, nextTokPtr) #ifdef XML_NS case BT_COLON: if (hadColon) { *nextTokPtr = ptr; return XML_TOK_INVALID; } hadColon = 1; ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); switch (BYTE_TYPE(enc, ptr)) { CHECK_NMSTRT_CASES(enc, ptr, end, nextTokPtr) default: *nextTokPtr = ptr; return XML_TOK_INVALID; } break; #endif case BT_S: case BT_CR: case BT_LF: { ptr += MINBPC(enc); while (HAS_CHAR(enc, ptr, end)) { switch (BYTE_TYPE(enc, ptr)) { CHECK_NMSTRT_CASES(enc, ptr, end, nextTokPtr) case BT_GT: goto gt; case BT_SOL: goto sol; case BT_S: case BT_CR: case BT_LF: ptr += MINBPC(enc); continue; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } return PREFIX(scanAtts)(enc, ptr, end, nextTokPtr); } return XML_TOK_PARTIAL; } case BT_GT: gt: *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_START_TAG_NO_ATTS; case BT_SOL: sol: ptr += MINBPC(enc); REQUIRE_CHAR(enc, ptr, end); if (!CHAR_MATCHES(enc, ptr, ASCII_GT)) { *nextTokPtr = ptr; return XML_TOK_INVALID; } *nextTokPtr = ptr + MINBPC(enc); return XML_TOK_EMPTY_ELEMENT_NO_ATTS; default: *nextTokPtr = ptr; return XML_TOK_INVALID; } } return XML_TOK_PARTIAL; } static int PTRCALL PREFIX(contentTok)(const ENCODING *enc, const char *ptr, const char *end, const char **nextTokPtr) { if (ptr > if (MINBPC(enc) > 1) switch (BYTE_TYPE(enc, ptr)) while* (HAS_CHAR(enc, ptr, end)) nextTokPtr = ptr
return XML_TOK_DATA_CHARS
static int PTRCALL PREFIX(scanPercent)(const ENCODING *enc const char * ptr
static int PTRCALL PREFIX(scanPercent)(const ENCODING *enc const char const char * end = MINBPC(enc)
switch(BYTE_TYPE(enc, ptr)) while(HAS_CHAR(enc, ptr, end)) return XML_TOK_PARTIAL
switch(BYTE_TYPE(enc, ptr)) while(HAS_CHAR(enc, ptr, end)) return XML_TOK_POUND_NAME
static int PTRCALL PREFIX(scanLit)(int open const ENCODING * enc
if(MINBPC(enc) > 1) switch(BYTE_TYPE(enc, ptr)) while(HAS_CHAR(enc, ptr, end)) return tok
start = ptr
static int PTRCALL PREFIX(isPublicId)(const ENCODING *enc const char const char const char ** badPtr
for(;HAS_CHAR(enc, ptr, end);ptr+=MINBPC(enc)) return
static int PTRCALL PREFIX(getAtts)(const ENCODING *enc const char int attsMax
static int PTRCALL PREFIX(getAtts)(const ENCODING *enc const char int ATTRIBUTE * atts
int nAtts = 0
int open = 0
if(CHAR_MATCHES(enc, ptr, ASCII_x)) else
static int PTRCALL PREFIX(sameName)(const ENCODING *enc const char * ptr1
Variable Documentation
atts
int PTRCALL PREFIX (getAtts)(const ENCODING *enc const char int ATTRIBUTE* atts
Initial value:
{
  enum { other, inName, inValue } state = inName
attsMax
int PTRCALL PREFIX (getAtts)(const ENCODING *enc const char int attsMax
badPtr
int PTRCALL PREFIX (isPublicId)(const ENCODING *enc const char const char const char** badPtr
Initial value:
{
  ptr += MINBPC(enc)
Referenced by doParseXmlDecl().
else
if (CHAR_MATCHES(enc, ptr, ASCII_x)) else
Initial value:
{
    for (; !CHAR_MATCHES(enc, ptr, ASCII_SEMI); ptr += MINBPC(enc)) {
      int c = BYTE_TO_ASCII(enc, ptr);
      result *= 10;
      result += (c - ASCII_0);
      if (result >= 0x110000)
        return -1;
    }
  }
  return checkCharRefNumber(result)
enc
int PTRCALL PREFIX (scanLit)(int open const ENCODING* enc
Referenced by appendAttributeValue(), attlist2(), attlist8(), condSect0(), doCdataSection(), doContent(), doctype1(), doIgnoreSection(), doParseXmlDecl(), doProlog(), element1(), element2(), entity2(), entity5(), entity7(), entityValueProcessor(), externalSubset0(), externalSubset1(), getAttributeId(), getElementType(), handleUnknownEncoding(), initScan(), internalSubset(), notation1(), parsePseudoAttribute(), poolAppend(), poolStoreString(), prolog0(), prolog1(), reportComment(), reportDefault(), reportProcessingInstruction(), storeAttributeValue(), storeAtts(), storeEntityValue(), toAscii(), unknown_isInvalid(), unknown_isName(), unknown_isNmstrt(), unknown_toUtf16(), unknown_toUtf8(), utf8_toUtf16(), and XmlInitUnknownEncodingNS().
end
int PTRCALL PREFIX (predefinedEntityName)(const ENCODING *UNUSED_P(enc) const char const char* end = MINBPC(enc)
Referenced by Slic3r::ArcSegment\ArcSegment(), Slic3r::BoundingBox3Base< PointClass >\BoundingBox3Base(), Slic3r::BoundingBoxBase< PointClass >\BoundingBoxBase(), Slic3r::OpenPolyline\OpenPolyline(), Eigen::PermutationMatrix< SizeAtCompileTime, MaxSizeAtCompileTime, _StorageIndex >\PermutationMatrix(), Eigen::RandomSetter< SparseMatrixType, MapTraits, OuterPacketBits >\~RandomSetter(), Slic3r::_BBS_Backup_Manager::timer\~timer(), Slic3r::_BBS_3MF_Exporter\_add_file_to_archive(), Slic3r::_BBS_3MF_Importer\_load_model_from_file(), igl\adjacency_list(), igl\adjacency_list(), appendAttributeValue(), Slic3r::GCodeProcessor\apply_config_simplify3d(), Slic3r::CoolingBuffer\apply_layer_cooldown(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >\applyThisOnTheLeft(), Slic3r::Arachne::SkeletalTrapezoidation\applyTransitions(), agg::path_base< VertexContainer >\arrange_polygon_orientation(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\at(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\at(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >\atInRange(), attlist2(), attlist8(), Slic3r\avoid_perimeters(), Slic3r\avoid_perimeters_inner(), Slic3r::GUI::BundleMap\bbl_bundle(), agg\binary_search_pos(), ImGui\CalcListClipping(), cdataSectionProcessor(), Slic3r\chain_monotonic_regions(), Slic3r\chain_open_polylines_close_gaps(), Slic3r\chain_open_polylines_exact(), Slic3r\chain_segments_greedy_constrained_reversals2_(), Slic3r\change_axis_value(), Slic3r\clip_extrusion(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >\coeff(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\coeff(), Eigen::SparseMapBase< Derived, WriteAccessors >\coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\coeffRef(), igl::geodesic::GeodesicAlgorithmExact\compute_propagated_parameters(), Eigen::internal\computeFromTridiagonal_impl(), condSect0(), cdt::triangulator_t< T, TNearPointLocator >\conform_to_edge(), Slic3r\connect_brim_lines(), Slic3r\connect_segment_intersections_by_contours(), nlohmann::detail::external_constructor< value_t::array >\construct(), nlohmann::detail::external_constructor< value_t::object >\construct(), contentProcessor(), boost::nowide::basic_stackstring< CharOut, CharIn, BufferSize >\convert(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\count(), hmesh_t\count_removed_elements_in_range(), nlohmann::detail::container_input_adapter_factory_impl::container_input_adapter_factory< ContainerType, void_t< decltype(begin(std::declval< ContainerType >()), end(std::declval< ContainerType >()))> >\create(), Slic3r::EdgeGrid::Grid\create(), Slic3r::EdgeGrid::Grid\create(), Slic3r::EdgeGrid::Grid\create_from_m_contours(), Slic3r::LinesBucket\curRange(), Slic3r::DnsName\decode(), Slic3r::Arachne::SkeletalTrapezoidation\discretize(), doCdataSection(), doContent(), doctype1(), doIgnoreSection(), doParseXmlDecl(), doProlog(), Slic3r::TreeSupport\drop_nodes(), element1(), element2(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\emplace(), Eigen\end(), libnest2d::shapelike\end(), libnest2d::shapelike\end(), libnest2d::shapelike\end(), Eigen\end(), Slic3r\end_of_vertical_run(), entity2(), entity5(), entity7(), entityValueInitProcessor(), entityValueProcessor(), epilogProcessor(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\erase(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\erase(), Slic3r::GUI::TickCodeInfo\erase_all_ticks_with_code(), Slic3r::GUI::PartPlate\estimate_wipe_tower_size(), Slic3r\extend_for_closest_lines(), externalEntityContentProcessor(), externalEntityInitProcessor(), externalEntityInitProcessor2(), externalEntityInitProcessor3(), externalParEntInitProcessor(), externalParEntProcessor(), externalSubset0(), externalSubset1(), igl::copyleft::cgal\extract_cells(), igl::copyleft::cgal\extract_cells_single_component(), igl\face_occurrences(), Slic3r::FillGrid\fill_surface(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\find(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\find(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >\find(), igl::geodesic::Interval\find_closest_point(), find_element(), find_element_with_pred(), find_map_element_by_key(), QuadricEdgeCollapse\find_triangle_index1(), Slic3r\fold_to_ascii(), nlohmann::detail\from_json_array_impl(), nlohmann::detail\from_json_array_impl(), Slic3r\generate_montonous_regions(), get_device_string(), Slic3r::GCodeProcessor\get_last_z_from_gcode(), Slic3r::FacetsAnnotation\get_triangle_as_string(), Slic3r::TreeSupport\get_trim_support_regions(), getAttributeId(), getElementType(), Slic3r::Model\getThermalLength(), igl::opengl\gliReadTGA(), PrinterFileSystem\HandleResponse(), Slic3r::Layer\idx_higher_or_equal(), Slic3r\idx_lower_or_equal(), ignoreSectionProcessor(), initScan(), initUpdatePosition(), Slic3r::GUI::BitmapCache\insert(), nlohmann::ordered_map< Key, T, IgnoredLess, Allocator >\insert(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\insert(), Slic3r::DnsSDMap\insert_srv(), Slic3r::DnsSDMap\insert_txt(), internalEntityProcessor(), internalSubset(), agg::path_base< VertexContainer >\invert_polygon(), agg::path_base< VertexContainer >\invert_polygon(), Slic3r\is_point_inside_triangle(), libnest2d::shapelike\isConvex(), Slic3r::GUI::InputIpAddressDialog\isIp(), Slic3r::Print\layers_sorted_for_object(), Slic3r\left_overlap(), Slic3r::UndoRedo::MutableObjectHistory< T >\load(), Slic3r::ConfigBase\load_from_gcode_string_legacy(), igl::geodesic::Interval\max_distance(), mz_zip_reader_sort_central_dir_offsets_by_filename(), boost::nowide\narrow(), Slic3r::GCode\needs_retraction(), ImChunkStream< T >\next_chunk(), Eigen::BlockImpl< XprType, BlockRows, BlockCols, true, Sparse >\nonZeros(), notation1(), Slic3r\offset_expolygon_inner(), ImChunkStream< T >\offset_from_ptr(), Slic3r::GUI::Temp_Calibration_Dlg\on_filament_type_changed(), Slic3r::GUI::Temp_Calibration_Dlg\on_start(), Slic3r::Arachne::PolygonsPointIndexSegmentLocator\operator()(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >\operator=(), Slic3r\overlap_bottom(), Slic3r\overlap_top(), parallel_partial_sum(), Slic3r::GCodeReader\parse_buffer(), Slic3r::GCodeReader\parse_file_internal(), Slic3r::GCodeReader\parse_file_raw(), Slic3r::CoolingBuffer\parse_layer_gcode(), Slic3r::GCodeReader\parse_line(), Slic3r::GCodeReader\parse_line_internal(), Slic3r::GUI\parse_params(), Slic3r::GUI\parse_semver_from_ini(), parsePseudoAttribute(), agg::path_base< VertexContainer >\perceive_polygon_orientation(), Slic3r\pinch_contours_insert_phony_outer_intersections(), Slic3r::WipeTower\plan_tower(), poolAppend(), poolStoreString(), Slic3r::PrintObject\process_external_surfaces(), Slic3r::GCodeProcessor\process_file(), Slic3r\process_macro(), Slic3r::Arachne::SquareGrid\processLineCells(), prolog0(), prolog1(), prologInitProcessor(), prologProcessor(), Slic3r::Model\propose_export_file_name_and_path(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\prune(), libnest2d::shapelike\rbegin(), Clipper2Lib\RDP(), Slic3r::UndoRedo::StackImpl\release_snapshots(), Slic3r\remove_eols(), Slic3r::GUI::GLSelectionRectangle\render(), Slic3r::GUI::ImageGrid\render(), Slic3r::GUI::OG_CustomCtrl::CtrlLine\render_separator(), Slic3r::GUI::Bed_2D\repaint(), reportComment(), reportDefault(), reportProcessingInstruction(), Slic3r::OpenPolyline\reverse(), Slic3r\right_overlap(), Slic3r::GUI::Config\right_trim(), Eigen::internal::smart_copy_helper< T, true >\run(), Eigen::internal::smart_copy_helper< T, false >\run(), Eigen::internal::smart_memmove_helper< T, true >\run(), Eigen::internal::smart_memmove_helper< T, false >\run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >\run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >\run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >\run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >\run(), Eigen::internal::unaligned_dense_assignment_loop< false >\run(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >\searchLowerIndex(), Slic3r::GCodeReader::GCodeLine\set(), Eigen::internal\set_from_triplets(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >\setBounds(), Eigen::BlockSparseMatrix< _Scalar, _BlockAtCompileTime, _Options, _StorageIndex >\setFromTriplets(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\setFromTriplets(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\setFromTriplets(), Slic3r::GUI::IMSlider\SetTicksValues(), ShowDemoWindowWidgets(), Slic3r\skip_whitespaces(), Slic3r::sla::SupportTree\slice(), Eigen::internal\smart_copy(), Eigen::internal\smart_memmove(), Slic3r\smooth_height_profile(), storeAttributeValue(), igl::copyleft::cgal\subdivide_segments(), Slic3r::GUI::TickCodeInfo\switch_code(), toAscii(), PrinterFileSystem\ToggleSelect(), orgQhull::QhullSet< T >\toStdVector(), Slic3r::AvoidCrossingPerimeters\travel_to(), triangulate_face(), Eigen::internal\tridiagonal_qr_step(), Slic3r::PrintObjectSupportMaterial\trim_support_layers_by_object(), Slic3r::GUI::Config\unquote_value(), Slic3r::GUI::Config\unquote_version_comment(), Slic3r::GUI::GLGizmoAdvancedCut\update_clipper(), Slic3r::GUI::UnsavedChangesDialog\update_list(), PrinterFileSystem\UpdateFocusThumbnail(), Slic3r::Print\validate(), boost::nowide\widen(), XML_Parse(), XML_SetCdataSectionHandler(), XML_SetDoctypeDeclHandler(), XML_SetElementHandler(), XML_SetEndCdataSectionHandler(), XML_SetEndDoctypeDeclHandler(), XML_SetEndElementHandler(), XML_SetEndNamespaceDeclHandler(), and XML_SetNamespaceDeclHandler().
nAtts
int nAtts = 0
nextTokPtr
int PTRCALL PREFIX (ignoreSectionTok)(const ENCODING *enc const char const char const char** nextTokPtr = ptr
Referenced by initScan(), and parsePseudoAttribute().
open
int open = 0
Referenced by MyDocument\MyDocument(), Slic3r::SVG\SVG(), Slic3r::SVG\SVG(), Slic3r::SVG\SVG(), Slic3r::SVG\SVG(), Slic3r::EdgeGrid::Grid\create(), Slic3r::EdgeGrid::Grid\create(), ImGui\DebugNodeTabBar(), ImGui\DebugNodeTable(), ImGui\DebugNodeWindow(), Slic3r::instance_check_internal\get_lock(), hid_open_path(), Slic3r::SVG\open(), Slic3r::SVG\open(), parsePseudoAttribute(), ImGui\SetNextTreeNodeOpen(), ShowDemoWindowColumns(), ShowDemoWindowLayout(), ShowDemoWindowTables(), ShowDemoWindowWidgets(), and ImGui\TabBarTabListPopupButton().
ptr
int PTRCALL PREFIX (predefinedEntityName)(const ENCODING *UNUSED_P(enc) const char* ptr
Initial value:
{
  int result = 0
Referenced by ImGuiPtrOrIndex\ImGuiPtrOrIndex(), agg::rasterizer_cells_aa< Cell >\~rasterizer_cells_aa(), __lzo_align_gap(), __lzo_ptr_linear(), Slic3r::_3MF_Exporter\_add_mesh_to_object_stream(), Slic3r::_BBS_3MF_Exporter\_add_mesh_to_object_stream(), agg::pod_bvector< T, S >\add_array(), Eigen::internal\aligned_delete(), Eigen::internal\aligned_free(), Eigen::internal\aligned_realloc(), agg::block_allocator\allocate(), Slic3r::ExtrusionEntityCollection\append(), Slic3r::GUI::DataList< T, D >\append(), Slic3r::GUI::DataList< T, D >\append(), appendAttributeValue(), igl::ply\ascii_get_element(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\at(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\at(), attlist2(), attlist8(), igl::ply\binary_get_element(), Eigen::Map< PlainObjectType, MapOptions, StrideType >\cast_to_pointer_type(), Slic3r::ExtrusionEntityCollection\chained_path_from(), Eigen::internal\conditional_aligned_delete(), Eigen::internal\conditional_aligned_delete_auto(), Eigen::internal\conditional_aligned_free(), Eigen::internal\conditional_aligned_free< false >(), Eigen::internal\conditional_aligned_realloc(), Eigen::internal\conditional_aligned_realloc< false >(), condSect0(), Eigen::internal\const_cast_ptr(), Eigen::internal\construct_elements_of_array(), nlohmann::json_pointer< BasicJsonType >\contains(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\contains(), Slic3r\custom_gcode_sets_temperature(), agg::obj_allocator< T >\deallocate(), agg::pod_allocator< T >\deallocate(), Slic3r::DnsName\decode(), agg::pod_bvector< T, S >\deserialize(), agg::pod_bvector< T, S >\deserialize(), igl::serialization\deserialize(), igl::serialization\deserialize(), agg::pod_bvector< T, S >\deserialize(), agg::pod_bvector< T, S >\deserialize(), Eigen::internal\destruct_elements_of_array(), doctype1(), doParseXmlDecl(), Eigen::internal\eigen_pastix(), Eigen::internal\eigen_pastix(), Eigen::internal\eigen_pastix(), Eigen::internal\eigen_pastix(), element1(), element2(), entity2(), entity5(), entity7(), Slic3r::ExtrusionSimulator\evaluate_accumulator(), externalSubset0(), externalSubset1(), FreeWrapper(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\from_bson(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\from_cbor(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\from_msgpack(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\from_ubjson(), Slic3r\generate_layer_height_texture(), Slic3r::GUI::GLCanvas3D\get_arrange_settings(), igl::ply\get_binary_item(), nlohmann::json_pointer< BasicJsonType >\get_checked(), nlohmann::json_pointer< BasicJsonType >\get_checked(), get_connected_component_data_impl_detail(), get_event_info_impl(), Slic3r::GUI::ObjectGridTable\get_object_config_value(), Slic3r::GUI::GLCanvas3D\get_orient_settings(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\get_ref_impl(), igl::ply\get_stored_item(), nlohmann::json_pointer< BasicJsonType >\get_unchecked(), nlohmann::json_pointer< BasicJsonType >\get_unchecked(), Slic3r::GUI::ObjectGridTable\get_volume_config_value(), igl::ply\get_words(), getElementType(), ImGuiWindow\GetID(), ImGuiWindow\GetIDNoKeepAlive(), Eigen::internal\handmade_aligned_free(), Eigen::internal\handmade_aligned_realloc(), Slic3r::UndoRedo::StackImpl\immutable_object_id_impl(), initScan(), initUpdatePosition(), nlohmann::detail\input_adapter(), internalSubset(), cereal\load(), cereal\load(), cereal\load(), cereal\load_optional(), ImGui\MemFree(), igl::ply\my_alloc(), mz_adler32(), mz_crc32(), notation1(), Slic3r::ExtrusionEntityCollection\operator ExtrusionPaths(), operator new(), Slic3r::MeshBoolean::cgal::CGALMeshDeleter\operator()(), Slic3r::sla::PNGRasterEncoder\operator()(), Slic3r::sla::PPMRasterEncoder\operator()(), Slic3r::MeshBoolean::mcut::McutMeshDeleter\operator()(), nlohmann::json_pointer< BasicJsonType >\operator/=(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\operator[](), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\operator[](), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >\packet(), Slic3r::GCodeReader\parse_buffer(), fast_float::detail\parse_infnan(), Slic3r::GCodeReader\parse_line(), Slic3r::GCodeReader\parse_line_internal(), parsePseudoAttribute(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\patch(), poolAppend(), poolStoreString(), prolog0(), prolog1(), register_error(), Slic3r::UndoRedo::StackImpl\release_least_recently_used(), Slic3r\remove_nulls(), Slic3r::ExtrusionEntityCollection\reverse(), cereal\save(), cereal\save(), cereal\save(), cereal\save_optional(), Slic3r::EdgeGrid::Contour\segment_end(), igl::serialization\serialize(), igl::serialization\serialize(), agg::pod_vector< T >\serialize(), agg::pod_bvector< T, S >\serialize(), Slic3r::GUI::GLGizmoBase\set_common_data_pool(), Slic3r::ConfigOptionDef\set_default_value(), set_user_event_status_impl(), storeAttributeValue(), Slic3r::GluTessWrapper\tessVertex(), tinfl_decompress(), Slic3r::FaceHash\to_chars(), toAscii(), Slic3r::I18N\translate(), u2p(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\value(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >\value(), Eigen::internal::mapbase_evaluator< Derived, PlainObjectType >\writePacket(), XML_MemFree(), and XML_MemRealloc().
ptr1
int PTRCALL PREFIX (sameName)(const ENCODING *enc const char* ptr1
return
for (;HAS_CHAR(enc, ptr, end);ptr+=MINBPC(enc)) return
Referenced by internal\colamd_set_defaults(), Eigen::SparseLU< _MatrixType, _OrderingType >\factorize(), Slic3r::GUI::ObjectList\rename_item(), Slic3r::GUI::Bed_2D\repaint(), Slic3r::GUI::ImGuiWrapper\search_list(), CBaseException\ShowExceptionResoult(), and Slic3r::GUI::BedShapePanel\update_shape().
start
start = ptr
Referenced by Slic3r::_BBS_Backup_Manager::timer\~timer(), Eigen::HouseholderSequence< VectorsType, CoeffsType, Side >\applyThisOnTheLeft(), Slic3r::GUI::Plater::priv::Jobs\arrange(), agg::path_base< VertexContainer >\arrange_orientations(), agg::path_base< VertexContainer >\arrange_orientations_all_paths(), agg::path_base< VertexContainer >\arrange_polygon_orientation(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >\atInRange(), Slic3r\avoid_perimeters(), Slic3r\avoid_perimeters_inner(), igl\boundary_loop(), ImGui\CalcListClipping(), cdataSectionProcessor(), Slic3r\chain_lines(), Slic3r\chain_open_polylines_close_gaps(), Slic3r\chain_open_polylines_exact(), Slic3r::DeviceManager\check_pushing(), Slic3r\clip_extrusion(), Eigen::SparseMapBase< Derived, ReadOnlyAccessors >\coeff(), Eigen::SparseMapBase< Derived, WriteAccessors >\coeffRef(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\coeffRef(), Eigen::internal::BandMatrixBase< Derived >\col(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\collapseDuplicates(), Eigen::internal\computeFromTridiagonal_impl(), cdt::triangulator_t< T, TNearPointLocator >\conform_to_edge(), Eigen::SparseMatrix< _Scalar, _Options, _StorageIndex >\conservativeResize(), contentProcessor(), hmesh_t\count_removed_elements_in_range(), Eigen::BDCSVD< _MatrixType >\deflation43(), agg::pod_bvector< T, S >\deserialize(), agg::pod_bvector< T, S >\deserialize(), Slic3r::Arachne::SkeletalTrapezoidation\discretize(), StaticBox\doRender(), Slic3r::GUI\draw_title(), Slic3r\end_of_vertical_run(), Slic3r\end_of_vertical_run(), Slic3r\end_of_vertical_run_raw(), entityValueInitProcessor(), entityValueProcessor(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, Side >\essentialVector(), Eigen::internal::hseq_side_dependent_impl< VectorsType, CoeffsType, OnTheRight >\essentialVector(), Slic3r\extend_for_closest_lines(), externalEntityContentProcessor(), externalEntityInitProcessor(), externalEntityInitProcessor2(), externalEntityInitProcessor3(), Slic3r::GUI::Plater::priv::Jobs\fill_bed(), Eigen::internal::evaluator< SparseCompressedBase< Derived > >\find(), internal\find_ordering(), igl::MeshCutter< DerivedV, DerivedF, DerivedM, DerivedO >\FloodFill(), Slic3r::BBLStatusBarSend\format_text(), internal\garbage_collection(), Slic3r\generate_montonous_regions(), Slic3r::GUI::GLCanvas3D\get_empty_cells(), Slic3r::GUI\get_utf8_sub_strings(), getAttributeId(), CurvatureCalculator\getKRing(), CurvatureCalculator\getSphere(), igl::opengl\gliReadTGA(), Slic3r\grid(), Slic3r::FillAdaptive\has_no_collinear_lines(), ignoreSectionProcessor(), Slic3r::GUI::Plater::priv::Jobs\import_sla_arch(), internal\init_scoring(), agg::path_base< VertexContainer >\invert_polygon(), agg::path_base< VertexContainer >\invert_polygon(), Slic3r::Print\layers_sorted_for_object(), Slic3r\left_overlap(), Slic3r\linspace_array(), Slic3r\linspace_vector(), Slic3r::ConfigBase\load_from_gcode_string_legacy(), Slic3r\minimum_crossover_cost(), mz_zip_reader_sort_central_dir_offsets_by_filename(), Slic3r::GUI::Temp_Calibration_Dlg\on_filament_type_changed(), Slic3r::GUI::Temp_Calibration_Dlg\on_start(), Slic3r::Arachne::PolygonsPointIndexSegmentLocator\operator()(), Eigen::internal::sparse_matrix_block_impl< SparseMatrixType, BlockRows, BlockCols >\operator=(), Slic3r::GUI::Plater::priv::Jobs\optimize_rotation(), Slic3r::GUI::Plater::priv::Jobs\orient(), Slic3r\overlap_bottom(), Slic3r\overlap_top(), Slic3r::CoolingBuffer\parse_layer_gcode(), fast_float\parse_number_string(), Slic3r::GUI\parse_params(), Slic3r::GUI\parse_semver_from_ini(), agg::path_base< VertexContainer >\perceive_polygon_orientation(), Clipper2Lib\PointInPolygon(), Slic3r::GUI::Plater::priv::Jobs\print(), Slic3r::SLAPrint\process(), Slic3r::Arachne::SquareGrid\processLineCells(), qh_initflags(), qh_initflags(), qh_newstats(), qh_newstats(), agg\qsort_cells(), Slic3r::GUI::GLSelectionRectangle\render(), Slic3r::GUI::GCodeViewer::SequentialView::GCodeWindow\render(), Slic3r::GUI::ImageGrid\render(), reportComment(), reportProcessingInstruction(), Slic3r::OpenPolyline\reverse(), Slic3r\right_overlap(), Slic3r::GUI::Config\right_trim(), Eigen::internal::smart_copy_helper< T, true >\run(), Eigen::internal::smart_copy_helper< T, false >\run(), Eigen::internal::smart_memmove_helper< T, true >\run(), Eigen::internal::smart_memmove_helper< T, false >\run(), Eigen::internal::product_triangular_matrix_matrix< Scalar, Index, Mode, true, LhsStorageOrder, ConjugateLhs, RhsStorageOrder, ConjugateRhs, ColMajor, Version >\run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, RowMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >\run(), Eigen::internal::general_matrix_vector_product< Index, LhsScalar, LhsMapper, ColMajor, ConjugateLhs, RhsScalar, RhsMapper, ConjugateRhs, Version >\run(), Eigen::internal::triangular_solve_matrix< Scalar, Index, OnTheLeft, Mode, Conjugate, TriStorageOrder, ColMajor >\run(), Eigen::internal::unaligned_dense_assignment_loop< false >\run(), Eigen::internal::CompressedStorage< _Scalar, _StorageIndex >\searchLowerIndex(), segment(), segment(), segment(), Eigen::internal::AmbiVector< _Scalar, _StorageIndex >\setBounds(), PrinterFileSystem\SetFocusRange(), MyScrollbar\SetViewStart(), Eigen::internal\smart_copy(), Eigen::internal\smart_memmove(), agg::rasterizer_cells_aa< Cell >\sort_cells(), nlohmann::json_pointer< BasicJsonType >\split(), Slic3r::GUI::AuxiliaryPanel\Split(), Slic3r::GUI::PreferencesDialog\Split(), Label\split_lines(), libnest2d::placers::_BottomLeftPlacer< RawShape >\toWallPoly(), Slic3r::AvoidCrossingPerimeters\travel_to(), triangulate_face(), Eigen::internal\tridiagonal_qr_step(), igl\uniformly_sample_two_manifold(), PrinterFileSystem\UpdateFocusThumbnail(), Slic3r\vertical_run_bottom(), Slic3r\vertical_run_bottom(), Slic3r\vertical_run_top(), Slic3r\vertical_run_top(), Slic3r::Geometry::rotcalip\visit_antipodals(), XML_ParseBuffer(), XML_SetCdataSectionHandler(), XML_SetDoctypeDeclHandler(), XML_SetElementHandler(), XML_SetNamespaceDeclHandler(), XML_SetStartCdataSectionHandler(), XML_SetStartDoctypeDeclHandler(), XML_SetStartElementHandler(), and XML_SetStartNamespaceDeclHandler().
tok
if(MINBPC(enc) > 1) switch(BYTE_TYPE(enc, ptr)) while (HAS_CHAR(enc, ptr, end)) return tok
Referenced by appendAttributeValue(), attlist0(), attlist1(), attlist2(), attlist3(), attlist4(), attlist5(), attlist6(), attlist7(), attlist8(), attlist9(), common(), condSect0(), condSect1(), condSect2(), declClose(), doCdataSection(), doContent(), doctype0(), doctype1(), doctype2(), doctype3(), doctype4(), doctype5(), doIgnoreSection(), doProlog(), element0(), element1(), element2(), element3(), element4(), element5(), element6(), element7(), entity0(), entity1(), entity10(), entity2(), entity3(), entity4(), entity5(), entity6(), entity7(), entity8(), entity9(), entityValueInitProcessor(), entityValueProcessor(), epilogProcessor(), externalEntityInitProcessor2(), externalEntityInitProcessor3(), externalParEntProcessor(), externalSubset0(), externalSubset1(), internalEntityProcessor(), internalSubset(), notation0(), notation1(), notation2(), notation3(), notation4(), processInternalEntity(), prolog0(), prolog1(), prolog2(), prologProcessor(), and storeEntityValue().
XML_TOK_DATA_CHARS
return XML_TOK_DATA_CHARS
XML_TOK_PARTIAL
if(MINBPC(enc) > 1) while (HAS_CHAR(enc, ptr, end)) return XML_TOK_PARTIAL
XML_TOK_POUND_NAME
switch(BYTE_TYPE(enc, ptr)) while (HAS_CHAR(enc, ptr, end)) return XML_TOK_POUND_NAME