OrcaSlicer: Slic3r::CalibPressureAdvancePattern Class Reference
Slic3r::CalibPressureAdvancePattern Class Reference
#include <src/libslic3r/calib.hpp>
Classes
struct DrawBoxOptArgs
struct DrawLineOptArgs
Public Member Functions
CalibPressureAdvancePattern (const Calib_Params &params, const DynamicPrintConfig &config, bool is_bbl_machine, Model &model, const Vec3d &origin)
double handle_xy_size () const
double handle_spacing () const
double print_size_x () const
double print_size_y () const
double max_layer_z () const
void generate_custom_gcodes (const DynamicPrintConfig &config, bool is_bbl_machine, Model &model, const Vec3d &origin)
Static Public Member Functions
static float find_optimal_PA_speed (const DynamicPrintConfig &config, double line_width, double layer_height, int filament_idx=0)
Protected Types
enum class DrawDigitMode { Left_To_Right , Bottom_To_Top }
Protected Member Functions
double speed_first_layer () const
double speed_perimeter () const
double line_width_first_layer () const
double line_width () const
int wall_count () const
void delta_scale_bed_ext (BoundingBoxf &bed_ext) const
std::string move_to (Vec2d pt, GCodeWriter &writer, std::string comment=std::string())
double e_per_mm (double line_width, double layer_height, float nozzle_diameter, float filament_diameter, float print_flow_ratio) const
double speed_adjust (int speed) const
std::string convert_number_to_string (double num) const
double number_spacing () const
std::string draw_digit (double startx, double starty, char c, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, GCodeWriter &writer)
std::string draw_number (double startx, double starty, double value, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, double speed, GCodeWriter &writer)
Protected Attributes
Vec3d m_last_pos
DrawDigitMode m_draw_digit_mode {DrawDigitMode::Left_To_Right}
const double m_digit_segment_len {2}
const double m_digit_gap_len {1}
const std::string::size_type m_max_number_len {5}
Private Member Functions
void refresh_setup (const DynamicPrintConfig &config, bool is_bbl_machine, const Model &model, const Vec3d &origin)
void _refresh_starting_point (const Model &model)
void _refresh_writer (bool is_bbl_machine, const Model &model, const Vec3d &origin)
double height_first_layer () const
double height_layer () const
const int get_num_patterns () const
std::string draw_line (Vec2d to_pt, DrawLineOptArgs opt_args)
std::string draw_box (double min_x, double min_y, double size_x, double size_y, DrawBoxOptArgs opt_args)
double to_radians (double degrees) const
double get_distance (Vec2d from, Vec2d to) const
double line_spacing () const
double line_spacing_first_layer () const
double line_spacing_angle () const
double object_size_x () const
double object_size_y () const
double frame_size_y () const
double glyph_start_x (int pattern_i=0) const
double glyph_length_x () const
double glyph_tab_max_x () const
double max_numbering_height () const
double pattern_shift () const
Private Attributes
const Calib_Params & m_params
DynamicPrintConfig m_config
GCodeWriter m_writer
bool m_is_delta
Vec3d m_starting_point
const double m_handle_xy_size {5}
const double m_handle_spacing {2}
const int m_num_layers {4}
const double m_wall_side_length {30.0}
const int m_corner_angle {90}
const int m_pattern_spacing {2}
const double m_encroachment {1. / 3.}
const double m_glyph_padding_horizontal {1}
const double m_glyph_padding_vertical {1}
Friends
struct DrawLineOptArgs
struct DrawBoxOptArgs
Detailed Description
Member Enumeration Documentation
DrawDigitMode
enum class Slic3r::CalibPressureAdvance::DrawDigitMode strong protected inherited
Enumerator
Left_To_Right
Bottom_To_Top
{
        Left_To_Right,
        Bottom_To_Top
    };
Constructor & Destructor Documentation
CalibPressureAdvancePattern()
Slic3r::CalibPressureAdvancePattern::CalibPressureAdvancePattern (const Calib_Params & params, const DynamicPrintConfig & config, bool is_bbl_machine, Model & model, const Vec3d & origin)
  :
    m_params(params)
{
    this->m_draw_digit_mode = DrawDigitMode::Bottom_To_Top;
    refresh_setup(config, is_bbl_machine, model, origin);
};
References Slic3r::CalibPressureAdvance::Bottom_To_Top, Slic3r::CalibPressureAdvance::m_draw_digit_mode, and refresh_setup().
Member Function Documentation
_refresh_starting_point()
void Slic3r::CalibPressureAdvancePattern::_refresh_starting_point (const Model & model) private
{
    ModelObject* obj = model.objects.front();
    BoundingBoxf3 bbox =
        obj->instance_bounding_box(
            *obj->instances.front(),
            false
        )
    ;
    m_starting_point = Vec3d(bbox.min.x(), bbox.max.y(), 0);
    m_starting_point.y() += m_handle_spacing;
    if (m_is_delta) {
        m_starting_point.x() *= -1;
        m_starting_point.y() -= (frame_size_y() / 2);
    }
}
References frame_size_y(), Slic3r::ModelObject::instance_bounding_box(), Slic3r::ModelObject::instances, m_handle_spacing, m_is_delta, m_starting_point, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::BoundingBoxBase< PointClass >::min, and Slic3r::Model::objects.
Referenced by refresh_setup().
_refresh_writer()
void Slic3r::CalibPressureAdvancePattern::_refresh_writer (bool is_bbl_machine, const Model & model, const Vec3d & origin) private
{
    PrintConfig print_config;
    print_config.apply(m_config, true);
    m_writer.apply_print_config(print_config);
    m_writer.set_xy_offset(origin(0), origin(1));
    m_writer.set_is_bbl_machine(is_bbl_machine);
    const unsigned int extruder_id = model.objects.front()->volumes.front()->extruder_id();
    m_writer.set_extruders({ extruder_id });
    m_writer.set_extruder(extruder_id);
}
References Slic3r::GCodeWriter::apply_print_config(), m_config, m_writer, Slic3r::Model::objects, Slic3r::GCodeWriter::set_extruder(), Slic3r::GCodeWriter::set_extruders(), Slic3r::GCodeWriter::set_is_bbl_machine(), and Slic3r::GCodeWriter::set_xy_offset().
Referenced by refresh_setup().
convert_number_to_string()
std::string Slic3r::CalibPressureAdvance::convert_number_to_string (double num) const protected inherited
{
    auto sNumber = std::to_string(num);
    sNumber.erase(sNumber.find_last_not_of('0') + 1, std::string::npos);
    sNumber.erase(sNumber.find_last_not_of('.') + 1, std::string::npos);
    return sNumber;
}
Referenced by Slic3r::CalibPressureAdvance::draw_number(), and max_numbering_height().
delta_scale_bed_ext()
void Slic3r::CalibPressureAdvance::delta_scale_bed_ext (BoundingBoxf & bed_ext) const inline protected inherited
{ bed_ext.scale(1.0f / 1.41421f); }
References Slic3r::BoundingBoxBase< PointClass >::scale().
Referenced by Slic3r::CalibPressureAdvanceLine::generate_test().
draw_box()
std::string Slic3r::CalibPressureAdvancePattern::draw_box (double min_x, double min_y, double size_x, double size_y, DrawBoxOptArgs opt_args) private
{
    std::stringstream gcode;
    double x = min_x;
    double y = min_y;
    const double max_x = min_x + size_x;
    const double max_y = min_y + size_y;
    const double spacing = opt_args.line_width - opt_args.height * (1 - M_PI / 4);
    // if number of perims exceeds size of box, reduce it to max
    const int max_perimeters =
        std::min(
            // this is the equivalent of number of perims for concentric fill
            std::floor(size_x * std::sin(to_radians(45))) / (spacing / std::sin(to_radians(45))),
            std::floor(size_y * std::sin(to_radians(45))) / (spacing / std::sin(to_radians(45)))
        )
    ;
    opt_args.num_perimeters = std::min(opt_args.num_perimeters, max_perimeters);
    gcode << move_to(Vec2d(min_x, min_y), m_writer, "Move to box start");
    DrawLineOptArgs line_opt_args(*this);
    line_opt_args.height = opt_args.height;
    line_opt_args.line_width = opt_args.line_width;
    line_opt_args.speed = opt_args.speed;
    for (int i = 0; i < opt_args.num_perimeters; ++i) {
        if (i != 0) { // after first perimeter, step inwards to start next perimeter
            x += spacing;
            y += spacing;
            gcode << move_to(Vec2d(x, y), m_writer, "Step inwards to print next perimeter");
        }
        y += size_y - i * spacing * 2;
        line_opt_args.comment = "Draw perimeter (up)";
        gcode << draw_line(Vec2d(x, y), line_opt_args);
        x += size_x - i * spacing * 2;
        line_opt_args.comment = "Draw perimeter (right)";
        gcode << draw_line(Vec2d(x, y), line_opt_args);
        y -= size_y - i * spacing * 2;
        line_opt_args.comment = "Draw perimeter (down)";
        gcode << draw_line(Vec2d(x, y), line_opt_args);
        x -= size_x - i * spacing * 2;
        line_opt_args.comment = "Draw perimeter (left)";
        gcode << draw_line(Vec2d(x, y), line_opt_args);
    }
    if (!opt_args.is_filled) {
        return gcode.str();
    }
    // create box infill
    const double spacing_45 = spacing / std::sin(to_radians(45));
    const double bound_modifier =
        (spacing * (opt_args.num_perimeters - 1)) +
        (opt_args.line_width * (1 - m_encroachment))
    ;
    const double x_min_bound = min_x + bound_modifier;
    const double x_max_bound = max_x - bound_modifier;
    const double y_min_bound = min_y + bound_modifier;
    const double y_max_bound = max_y - bound_modifier;
    const int x_count = std::floor((x_max_bound - x_min_bound) / spacing_45);
    const int y_count = std::floor((y_max_bound - y_min_bound) / spacing_45);
    double x_remainder = std::fmod((x_max_bound - x_min_bound), spacing_45);
    double y_remainder = std::fmod((y_max_bound - y_min_bound), spacing_45);
    x = x_min_bound;
    y = y_min_bound;
    gcode << move_to(Vec2d(x, y), m_writer, "Move to fill start");
    for (int i = 0; i < x_count + y_count + (x_remainder + y_remainder >= spacing_45 ? 1 : 0); ++i) { // this isn't the most robust way, but less expensive than finding line intersections
        if (i < std::min(x_count, y_count)) {
            if (i % 2 == 0) {
                x += spacing_45;
                y = y_min_bound;
                gcode << move_to(Vec2d(x, y), m_writer, "Fill: Step right");
                y += x - x_min_bound;
                x = x_min_bound;
                line_opt_args.comment = "Fill: Print up/left";
                gcode << draw_line(Vec2d(x, y), line_opt_args);
            } else {
                y += spacing_45;
                x = x_min_bound;
                gcode << move_to(Vec2d(x, y), m_writer, "Fill: Step up");
                x += y - y_min_bound;
                y = y_min_bound;
                line_opt_args.comment = "Fill: Print down/right";
                gcode << draw_line(Vec2d(x, y), line_opt_args);
            }
        } else if (i < std::max(x_count, y_count)) {
            if (x_count > y_count) {
                // box is wider than tall
                if (i % 2 == 0) {
                    x += spacing_45;
                    y = y_min_bound;
                    gcode << move_to(Vec2d(x, y), m_writer, "Fill: Step right");
                    x -= y_max_bound - y_min_bound;
                    y = y_max_bound;
                    line_opt_args.comment = "Fill: Print up/left";
                    gcode << draw_line(Vec2d(x, y), line_opt_args);
                } else {
                    if (i == y_count) {
                        x += spacing_45 - y_remainder;
                        y_remainder = 0;
                    } else {
                        x += spacing_45;
                    }
                    y = y_max_bound;
                    gcode << move_to(Vec2d(x, y), m_writer, "Fill: Step right");
                    x += y_max_bound - y_min_bound;
                    y = y_min_bound;
                    line_opt_args.comment = "Fill: Print down/right";
                    gcode << draw_line(Vec2d(x, y), line_opt_args);
                }
            } else {
                // box is taller than wide
                if (i % 2 == 0) {
                    x = x_max_bound;
                    if (i == x_count) {
                        y += spacing_45 - x_remainder;
                        x_remainder = 0;
                    } else {
                        y += spacing_45;
                    }
                    gcode << move_to(Vec2d(x, y), m_writer, "Fill: Step up");
                    x = x_min_bound;
                    y += x_max_bound - x_min_bound;
                    line_opt_args.comment = "Fill: Print up/left";
                    gcode << draw_line(Vec2d(x, y), line_opt_args);
                } else {
                    x = x_min_bound;
                    y += spacing_45;
                    gcode << move_to(Vec2d(x, y), m_writer, "Fill: Step up");
                    x = x_max_bound;
                    y -= x_max_bound - x_min_bound;
                    line_opt_args.comment = "Fill: Print down/right";
                    gcode << draw_line(Vec2d(x, y), line_opt_args);
                }
            }
        } else {
            if (i % 2 == 0) {
                x = x_max_bound;
                if (i == x_count) {
                    y += spacing_45 - x_remainder;
                } else {
                    y += spacing_45;
                }
                gcode << move_to(Vec2d(x, y), m_writer, "Fill: Step up");
                x -= y_max_bound - y;
                y = y_max_bound;
                line_opt_args.comment = "Fill: Print up/left";
                gcode << draw_line(Vec2d(x, y), line_opt_args);
            } else {
                if (i == y_count) {
                    x += spacing_45 - y_remainder;
                } else {
                    x += spacing_45;
                }
                y = y_max_bound;
                gcode << move_to(Vec2d(x, y), m_writer, "Fill: Step right");
                y -= x_max_bound - x;
                x = x_max_bound;
                line_opt_args.comment = "Fill: Print down/right";
                gcode << draw_line(Vec2d(x, y), line_opt_args);
            }
        }
    }
    return gcode.str();
}
References Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::comment, draw_line(), Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::height, Slic3r::CalibPressureAdvancePattern::DrawBoxOptArgs::height, Slic3r::CalibPressureAdvancePattern::DrawBoxOptArgs::is_filled, Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::line_width, Slic3r::CalibPressureAdvancePattern::DrawBoxOptArgs::line_width, m_encroachment, M_PI, m_writer, Slic3r::CalibPressureAdvance::move_to(), Slic3r::CalibPressureAdvancePattern::DrawBoxOptArgs::num_perimeters, Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::speed, Slic3r::CalibPressureAdvancePattern::DrawBoxOptArgs::speed, and to_radians().
Referenced by generate_custom_gcodes().
draw_digit()
std::string Slic3r::CalibPressureAdvance::draw_digit (double startx, double starty, char c, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, GCodeWriter & writer) protected inherited
{
    const double len = m_digit_segment_len;
    const double gap = line_width / 2.0;
    const auto dE = e_per_mm * len;
    const auto two_dE = dE * 2;
    Vec2d p0, p1, p2, p3, p4, p5;
    Vec2d p0_5, p4_5;
    Vec2d gap_p0_toward_p3, gap_p2_toward_p3;
    Vec2d dot_direction;
    if (mode == CalibPressureAdvance::DrawDigitMode::Bottom_To_Top) {
        //  1-------2-------5
        //  |       |       |
        //  |       |       |
        //  0-------3-------4
        p0 = Vec2d(startx, starty);
        p0_5 = Vec2d(startx, starty + len / 2);
        p1 = Vec2d(startx, starty + len);
        p2 = Vec2d(startx + len, starty + len);
        p3 = Vec2d(startx + len, starty);
        p4 = Vec2d(startx + len * 2, starty);
        p4_5 = Vec2d(startx + len * 2, starty + len / 2);
        p5 = Vec2d(startx + len * 2, starty + len);
        gap_p0_toward_p3 = p0 + Vec2d(gap, 0);
        gap_p2_toward_p3 = p2 + Vec2d(0, gap);
        dot_direction = Vec2d(-len / 2, 0);
    } else {
        //  0-------1
        //  |       |
        //  3-------2
        //  |       |
        //  4-------5
        p0 = Vec2d(startx, starty);
        p0_5 = Vec2d(startx + len / 2, starty);
        p1 = Vec2d(startx + len, starty);
        p2 = Vec2d(startx + len, starty - len);
        p3 = Vec2d(startx, starty - len);
        p4 = Vec2d(startx, starty - len * 2);
        p4_5 = Vec2d(startx + len / 2, starty - len * 2);
        p5 = Vec2d(startx + len, starty - len * 2);
        gap_p0_toward_p3 = p0 - Vec2d(0, gap);
        gap_p2_toward_p3 = p2 - Vec2d(gap, 0);
        dot_direction = Vec2d(0, len / 2);
    }
    std::stringstream gcode;
    switch (c) {
    case '0':
        gcode << move_to(p0, writer, "Glyph: 0");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(gap_p0_toward_p3, two_dE);
        break;
    case '1':
        gcode << move_to(p0_5, writer, "Glyph: 1");
        gcode << writer.extrude_to_xy(p4_5, two_dE);
        break;
    case '2':
        gcode << move_to(p0, writer, "Glyph: 2");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        break;
    case '3':
        gcode << move_to(p0, writer, "Glyph: 3");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << move_to(gap_p2_toward_p3, writer);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '4':
        gcode << move_to(p0, writer, "Glyph: 4");
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << move_to(p1, writer);
        gcode << writer.extrude_to_xy(p5, two_dE);
        break;
    case '5':
        gcode << move_to(p1, writer, "Glyph: 5");
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        break;
    case '6':
        gcode << move_to(p1, writer, "Glyph: 6");
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p4, two_dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '7':
        gcode << move_to(p0, writer, "Glyph: 7");
        gcode << writer.extrude_to_xy(p1, dE);
        gcode << writer.extrude_to_xy(p5, two_dE);
        break;
    case '8':
        gcode << move_to(p2, writer, "Glyph: 8");
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p4, dE);
        gcode << writer.extrude_to_xy(p5, dE);
        gcode << writer.extrude_to_xy(p1, two_dE);
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        break;
    case '9':
        gcode << move_to(p5, writer, "Glyph: 9");
        gcode << writer.extrude_to_xy(p1, two_dE);
        gcode << writer.extrude_to_xy(p0, dE);
        gcode << writer.extrude_to_xy(p3, dE);
        gcode << writer.extrude_to_xy(p2, dE);
        break;
    case '.':
        gcode << move_to(p4_5, writer, "Glyph: .");
        gcode << writer.extrude_to_xy(p4_5 + dot_direction, dE);
        break;
    default:
        break;
    }
    return gcode.str();
}
References Slic3r::CalibPressureAdvance::Bottom_To_Top, Slic3r::CalibPressureAdvance::e_per_mm(), Slic3r::GCodeWriter::extrude_to_xy(), Slic3r::CalibPressureAdvance::m_digit_segment_len, and Slic3r::CalibPressureAdvance::move_to().
Referenced by Slic3r::CalibPressureAdvance::draw_number().
draw_line()
std::string Slic3r::CalibPressureAdvancePattern::draw_line (Vec2d to_pt, DrawLineOptArgs opt_args) private
{
    const double e_per_mm = CalibPressureAdvance::e_per_mm(
        opt_args.line_width,
        opt_args.height,
        m_config.option<ConfigOptionFloats>("nozzle_diameter")->get_at(0),
        m_config.option<ConfigOptionFloats>("filament_diameter")->get_at(0),
        m_config.option<ConfigOptionFloats>("filament_flow_ratio")->get_at(0)
    );
    const double length = get_distance(Vec2d(m_last_pos.x(), m_last_pos.y()), to_pt);
    auto dE = e_per_mm * length;
    std::stringstream gcode;
    gcode << m_writer.set_speed(opt_args.speed);
    gcode << m_writer.extrude_to_xy(to_pt, dE, opt_args.comment);
    m_last_pos = Vec3d(to_pt.x(), to_pt.y(), 0);
    return gcode.str();
}
References Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::comment, Slic3r::CalibPressureAdvance::e_per_mm(), Slic3r::GCodeWriter::extrude_to_xy(), Slic3r::ConfigOptionVector< T >::get_at(), get_distance(), Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::height, Slic3r::length(), Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::line_width, m_config, Slic3r::CalibPressureAdvance::m_last_pos, m_writer, Slic3r::ConfigBase::option(), Slic3r::GCodeWriter::set_speed(), and Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::speed.
Referenced by draw_box(), and generate_custom_gcodes().
draw_number()
std::string Slic3r::CalibPressureAdvance::draw_number (double startx, double starty, double value, CalibPressureAdvance::DrawDigitMode mode, double line_width, double e_per_mm, double speed, GCodeWriter & writer) protected inherited
{
    auto sNumber = convert_number_to_string(value);
    std::stringstream gcode;
    gcode << writer.set_speed(speed);
    for (std::string::size_type i = 0; i < sNumber.length(); ++i) {
        if (i > m_max_number_len) {
            break;
        }
        switch (mode) {
            case DrawDigitMode::Bottom_To_Top:
                gcode << draw_digit(
                    startx,
                    starty + i * number_spacing(),
                    sNumber[i],
                    mode,
                    line_width,
                    e_per_mm,
                    writer
                );
                break;
            default:
                gcode << draw_digit(
                    startx + i * number_spacing(),
                    starty,
                    sNumber[i],
                    mode,
                    line_width,
                    e_per_mm,
                    writer
                );
        }
    }
    return gcode.str();
}
References Slic3r::CalibPressureAdvance::Bottom_To_Top, Slic3r::CalibPressureAdvance::convert_number_to_string(), Slic3r::CalibPressureAdvance::draw_digit(), Slic3r::CalibPressureAdvance::e_per_mm(), Slic3r::CalibPressureAdvance::m_max_number_len, Slic3r::CalibPressureAdvance::number_spacing(), and Slic3r::GCodeWriter::set_speed().
Referenced by generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
e_per_mm()
double Slic3r::CalibPressureAdvance::e_per_mm (double line_width, double layer_height, float nozzle_diameter, float filament_diameter, float print_flow_ratio) const protected inherited
{
    const Flow line_flow = Flow(line_width, layer_height, nozzle_diameter);
    const double filament_area = M_PI * std::pow(filament_diameter / 2, 2);
    return line_flow.mm3_per_mm() / filament_area * print_flow_ratio;
}
References Slic3r::layer_height(), M_PI, and Slic3r::Flow::mm3_per_mm().
Referenced by Slic3r::CalibPressureAdvance::draw_digit(), draw_line(), Slic3r::CalibPressureAdvance::draw_number(), generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
find_optimal_PA_speed()
float Slic3r::CalibPressureAdvance::find_optimal_PA_speed (const DynamicPrintConfig & config, double line_width, double layer_height, int filament_idx = 0) static inherited
{
    const double general_suggested_min_speed = 100.0;
    double filament_max_volumetric_speed = config.option<ConfigOptionFloats>("filament_max_volumetric_speed")->get_at(0);
    Flow pattern_line = Flow(line_width, layer_height, config.option<ConfigOptionFloats>("nozzle_diameter")->get_at(0));
    auto pa_speed = std::min(std::max(general_suggested_min_speed,config.option<ConfigOptionFloat>("outer_wall_speed")->value), filament_max_volumetric_speed / pattern_line.mm3_per_mm());
    return std::floor(pa_speed);
}
References Slic3r::ConfigOptionVector< T >::get_at(), Slic3r::layer_height(), Slic3r::Flow::mm3_per_mm(), Slic3r::ConfigBase::option(), and Slic3r::ConfigOptionSingle< T >::value.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), Slic3r::GUI::Plater::_calib_pa_tower(), and Slic3r::GCode::_do_export().
frame_size_y()
double Slic3r::CalibPressureAdvancePattern::frame_size_y () const inline private
{ return std::sin(to_radians(double(m_corner_angle) / 2)) * m_wall_side_length * 2; };
References m_corner_angle, m_wall_side_length, and to_radians().
Referenced by _refresh_starting_point(), and generate_custom_gcodes().
generate_custom_gcodes()
void Slic3r::CalibPressureAdvancePattern::generate_custom_gcodes (const DynamicPrintConfig & config, bool is_bbl_machine, Model & model, const Vec3d & origin)
{
    std::stringstream gcode;
    gcode << "; start pressure advance pattern for layer\n";
    refresh_setup(config, is_bbl_machine, model, origin);
    gcode << move_to(Vec2d(m_starting_point.x(), m_starting_point.y()), m_writer, "Move to start XY position");
    gcode << m_writer.travel_to_z(height_first_layer(), "Move to start Z position");
    gcode << m_writer.set_pressure_advance(m_params.start);
    const DrawBoxOptArgs default_box_opt_args(*this);
    // create anchoring frame
    gcode << draw_box(
        m_starting_point.x(),
        m_starting_point.y(),
        print_size_x(),
        frame_size_y(),
        default_box_opt_args
    );
    // create tab for numbers
    DrawBoxOptArgs draw_box_opt_args = default_box_opt_args;
    draw_box_opt_args.is_filled = true;
    draw_box_opt_args.num_perimeters = wall_count();
    gcode << draw_box(
        m_starting_point.x(),
        m_starting_point.y() + frame_size_y() + line_spacing_first_layer(),
        glyph_tab_max_x() - m_starting_point.x(),
        max_numbering_height() + line_spacing_first_layer() + m_glyph_padding_vertical * 2,
        draw_box_opt_args
    );
    std::vector<CustomGCode::Item> gcode_items;
    const DrawLineOptArgs default_line_opt_args(*this);
    const int num_patterns = get_num_patterns(); // "cache" for use in loops
    // draw pressure advance pattern
    for (int i = 0; i < m_num_layers; ++i) {
        if (i > 0) {
            gcode << "; end pressure advance pattern for layer\n";
            CustomGCode::Item item;
            item.print_z = height_first_layer() + (i - 1) * height_layer();
            item.type = CustomGCode::Type::Custom;
            item.extra = gcode.str();
            gcode_items.push_back(item);
            gcode = std::stringstream(); // reset for next layer contents
            gcode << "; start pressure advance pattern for layer\n";
            const double layer_height = height_first_layer() + (i * height_layer());
            gcode << m_writer.travel_to_z(layer_height, "Move to layer height");
        }
        // line numbering
        if (i == 1) {
            gcode << m_writer.set_pressure_advance(m_params.start);
            double number_e_per_mm = e_per_mm(
                line_width(),
                height_layer(),
                m_config.option<ConfigOptionFloats>("nozzle_diameter")->get_at(0),
                m_config.option<ConfigOptionFloats>("filament_diameter")->get_at(0),
                m_config.option<ConfigOptionFloats>("filament_flow_ratio")->get_at(0)
            );
            // glyph on every other line
            for (int j = 0; j < num_patterns; j += 2) {
                gcode << draw_number(
                    glyph_start_x(j),
                    m_starting_point.y() + frame_size_y() + m_glyph_padding_vertical + line_width(),
                    m_params.start + (j * m_params.step),
                    m_draw_digit_mode,
                    line_width(),
                    number_e_per_mm,
                    speed_first_layer(),
                    m_writer
                );
            }
        }
        DrawLineOptArgs draw_line_opt_args = default_line_opt_args;
        double to_x = m_starting_point.x() + pattern_shift();
        double to_y = m_starting_point.y();
        double side_length = m_wall_side_length;
        // shrink first layer to fit inside frame
        if (i == 0) {
            double shrink =
                (
                    line_spacing_first_layer() * (wall_count() - 1) +
                    (line_width_first_layer() * (1 - m_encroachment))
                ) / std::sin(to_radians(m_corner_angle) / 2)
            ;
            side_length = m_wall_side_length - shrink;
            to_x += shrink * std::sin(to_radians(90) - to_radians(m_corner_angle) / 2);
            to_y +=
                line_spacing_first_layer() * (wall_count() - 1) +
                (line_width_first_layer() * (1 - m_encroachment))
            ;
        }
        double initial_x = to_x;
        double initial_y = to_y;
        gcode << move_to(Vec2d(to_x, to_y), m_writer, "Move to pattern start");
        for (int j = 0; j < num_patterns; ++j) {
            // increment pressure advance
            gcode << m_writer.set_pressure_advance(m_params.start + (j * m_params.step));
            for (int k = 0; k < wall_count(); ++k) {
                to_x += std::cos(to_radians(m_corner_angle) / 2) * side_length;
                to_y += std::sin(to_radians(m_corner_angle) / 2) * side_length;
                draw_line_opt_args = default_line_opt_args;
                draw_line_opt_args.height       = i == 0 ? height_first_layer()                 : height_layer();
                draw_line_opt_args.line_width   = line_width(); // don't use line_width_first_layer so results are consistent across all layers
                draw_line_opt_args.speed        = i == 0 ? speed_adjust(speed_first_layer())    : speed_adjust(speed_perimeter());
                draw_line_opt_args.comment = "Print pattern wall";
                gcode << draw_line(Vec2d(to_x, to_y), draw_line_opt_args);
                to_x -= std::cos(to_radians(m_corner_angle) / 2) * side_length;
                to_y += std::sin(to_radians(m_corner_angle) / 2) * side_length;
                gcode << draw_line(Vec2d(to_x, to_y), draw_line_opt_args);
                to_y = initial_y;
                if (k != wall_count() - 1) {
                    // perimeters not done yet. move to next perimeter
                    to_x += line_spacing_angle();
                    gcode << move_to(Vec2d(to_x, to_y), m_writer, "Move to start next pattern wall");
                } else if (j != num_patterns - 1) {
                    // patterns not done yet. move to next pattern
                    to_x += m_pattern_spacing + line_width();
                    gcode << move_to(Vec2d(to_x, to_y), m_writer, "Move to next pattern");
                } else if (i != m_num_layers - 1) {
                    // layers not done yet. move back to start
                    to_x = initial_x;
                    gcode << move_to(Vec2d(to_x, to_y), m_writer, "Move back to start position");
                } else {
                    // everything done
                }
            }
        }
    }
    gcode << m_writer.set_pressure_advance(m_params.start);
    gcode << "; end pressure advance pattern for layer\n";
    CustomGCode::Item item;
    item.print_z = max_layer_z();
    item.type = CustomGCode::Type::Custom;
    item.extra = gcode.str();
    gcode_items.push_back(item);
    CustomGCode::Info info;
    info.mode = CustomGCode::Mode::SingleExtruder;
    info.gcodes = gcode_items;
    model.plates_custom_gcodes[model.curr_plate_index] = info;
}
References Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::comment, Slic3r::Model::curr_plate_index, Slic3r::CustomGCode::Custom, draw_box(), draw_line(), Slic3r::CalibPressureAdvance::draw_number(), Slic3r::CalibPressureAdvance::e_per_mm(), Slic3r::CustomGCode::Item::extra, frame_size_y(), Slic3r::CustomGCode::Info::gcodes, Slic3r::ConfigOptionVector< T >::get_at(), get_num_patterns(), glyph_start_x(), glyph_tab_max_x(), Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::height, height_first_layer(), height_layer(), Slic3r::CalibPressureAdvancePattern::DrawBoxOptArgs::is_filled, Slic3r::layer_height(), line_spacing_angle(), line_spacing_first_layer(), line_width(), Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::line_width, line_width_first_layer(), m_config, m_corner_angle, Slic3r::CalibPressureAdvance::m_draw_digit_mode, m_encroachment, m_glyph_padding_vertical, m_num_layers, m_params, m_pattern_spacing, m_starting_point, m_wall_side_length, m_writer, max_layer_z(), max_numbering_height(), Slic3r::CustomGCode::Info::mode, Slic3r::CalibPressureAdvance::move_to(), Slic3r::CalibPressureAdvancePattern::DrawBoxOptArgs::num_perimeters, Slic3r::ConfigBase::option(), pattern_shift(), Slic3r::Model::plates_custom_gcodes, print_size_x(), Slic3r::CustomGCode::Item::print_z, refresh_setup(), Slic3r::GCodeWriter::set_pressure_advance(), Slic3r::shrink(), Slic3r::CustomGCode::SingleExtruder, Slic3r::CalibPressureAdvancePattern::DrawLineOptArgs::speed, Slic3r::CalibPressureAdvance::speed_adjust(), speed_first_layer(), speed_perimeter(), Slic3r::Calib_Params::start, Slic3r::Calib_Params::step, to_radians(), Slic3r::GCodeWriter::travel_to_z(), Slic3r::CustomGCode::Item::type, and wall_count().
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern().
get_distance()
double Slic3r::CalibPressureAdvancePattern::get_distance (Vec2d from, Vec2d to) const private
{
    return std::hypot((to.x() - from.x()), (to.y() - from.y()));
}
Referenced by draw_line().
get_num_patterns()
const int Slic3r::CalibPressureAdvancePattern::get_num_patterns () const inline private
    {
        return std::ceil((m_params.end - m_params.start) / m_params.step + 1);
    }
References Slic3r::Calib_Params::end, m_params, Slic3r::Calib_Params::start, and Slic3r::Calib_Params::step.
Referenced by generate_custom_gcodes(), glyph_tab_max_x(), max_numbering_height(), and object_size_x().
glyph_length_x()
double Slic3r::CalibPressureAdvancePattern::glyph_length_x () const private
{
    // half of line_width sticks out on each side
    return line_width() + (2 * m_digit_segment_len);
}
References line_width(), and Slic3r::CalibPressureAdvance::m_digit_segment_len.
Referenced by glyph_start_x(), and glyph_tab_max_x().
glyph_start_x()
double Slic3r::CalibPressureAdvancePattern::glyph_start_x (int pattern_i = 0) const private
{
    // note that pattern_i is zero-based!
    // align glyph's start with first perimeter of specified pattern
    double x =
        // starting offset
        m_starting_point.x() +
        pattern_shift() +
        // width of pattern extrusions
        pattern_i * (wall_count() - 1) * line_spacing_angle() + // center to center distance of extrusions
        pattern_i * line_width() + // endcaps. center to end on either side = 1 line width
        // space between each pattern
        pattern_i * m_pattern_spacing
    ;
    // align to middle of pattern walls
    x += wall_count() * line_spacing_angle() / 2;
    // shift so glyph is centered on pattern
    // m_digit_segment_len = half of X length of glyph
    x -= (glyph_length_x() / 2);
    return x;
}
References glyph_length_x(), line_spacing_angle(), line_width(), m_pattern_spacing, m_starting_point, pattern_shift(), and wall_count().
Referenced by generate_custom_gcodes(), and glyph_tab_max_x().
glyph_tab_max_x()
double Slic3r::CalibPressureAdvancePattern::glyph_tab_max_x () const private
{
    // only every other glyph is shown, starting with 1
    int num = get_num_patterns();
    int max_num =
        (num % 2 == 0)
        ? num - 1
        : num
    ;
    // padding at end should be same as padding at start
    double padding = glyph_start_x(0) - m_starting_point.x();
    return
        glyph_start_x(max_num - 1) + // glyph_start_x is zero-based
        (glyph_length_x() - line_width() / 2) +
        padding
    ;
}
References get_num_patterns(), glyph_length_x(), glyph_start_x(), line_width(), and m_starting_point.
Referenced by generate_custom_gcodes().
handle_spacing()
double Slic3r::CalibPressureAdvancePattern::handle_spacing () const inline
{ return m_handle_spacing; };
References m_handle_spacing.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern().
handle_xy_size()
double Slic3r::CalibPressureAdvancePattern::handle_xy_size () const inline
{ return m_handle_xy_size; };
References m_handle_xy_size.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern().
height_first_layer()
double Slic3r::CalibPressureAdvancePattern::height_first_layer () const inline private
{ return m_config.option<ConfigOptionFloat>("initial_layer_print_height")->value; };
References m_config, and Slic3r::ConfigBase::option().
Referenced by generate_custom_gcodes(), line_spacing_first_layer(), and max_layer_z().
height_layer()
double Slic3r::CalibPressureAdvancePattern::height_layer () const inline private
{ return m_config.option<ConfigOptionFloat>("layer_height")->value; };
References m_config, and Slic3r::ConfigBase::option().
Referenced by generate_custom_gcodes(), line_spacing(), and max_layer_z().
line_spacing()
double Slic3r::CalibPressureAdvancePattern::line_spacing () const inline private
{ return line_width() - height_layer() * (1 - M_PI / 4); };
References height_layer(), line_width(), and M_PI.
Referenced by line_spacing_angle().
line_spacing_angle()
double Slic3r::CalibPressureAdvancePattern::line_spacing_angle () const inline private
{ return line_spacing() / std::sin(to_radians(m_corner_angle) / 2); };
References line_spacing(), m_corner_angle, and to_radians().
Referenced by generate_custom_gcodes(), glyph_start_x(), and object_size_x().
line_spacing_first_layer()
double Slic3r::CalibPressureAdvancePattern::line_spacing_first_layer () const inline private
{ return line_width_first_layer() - height_first_layer() * (1 - M_PI / 4); };
References height_first_layer(), line_width_first_layer(), and M_PI.
Referenced by generate_custom_gcodes(), object_size_x(), and pattern_shift().
line_width()
double Slic3r::CalibPressureAdvancePattern::line_width () const inline protected
{ return m_config.get_abs_value("line_width"); };
References Slic3r::ConfigBase::get_abs_value(), and m_config.
Referenced by generate_custom_gcodes(), glyph_length_x(), glyph_start_x(), glyph_tab_max_x(), line_spacing(), and object_size_x().
line_width_first_layer()
double Slic3r::CalibPressureAdvancePattern::line_width_first_layer () const inline protected
{ return m_config.get_abs_value("initial_layer_line_width"); };
References Slic3r::ConfigBase::get_abs_value(), and m_config.
Referenced by generate_custom_gcodes(), line_spacing_first_layer(), object_size_y(), and pattern_shift().
max_layer_z()
double Slic3r::CalibPressureAdvancePattern::max_layer_z () const inline
{ return height_first_layer() + ((m_num_layers - 1) * height_layer()); };
References height_first_layer(), height_layer(), and m_num_layers.
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), and generate_custom_gcodes().
max_numbering_height()
double Slic3r::CalibPressureAdvancePattern::max_numbering_height () const private
{
    std::string::size_type most_characters = 0;
    const int num_patterns = get_num_patterns();
    // note: only every other number is printed
    for (std::string::size_type i = 0; i < num_patterns; i += 2) {
        std::string sNumber = convert_number_to_string(m_params.start + (i * m_params.step));
        if (sNumber.length() > most_characters) {
            most_characters = sNumber.length();
        }
    }
    most_characters = std::min(most_characters, m_max_number_len);
    return (most_characters * m_digit_segment_len) + ((most_characters - 1) * m_digit_gap_len);
}
References Slic3r::CalibPressureAdvance::convert_number_to_string(), get_num_patterns(), Slic3r::CalibPressureAdvance::m_digit_gap_len, Slic3r::CalibPressureAdvance::m_digit_segment_len, Slic3r::CalibPressureAdvance::m_max_number_len, m_params, Slic3r::Calib_Params::start, and Slic3r::Calib_Params::step.
Referenced by generate_custom_gcodes(), and object_size_y().
move_to()
std::string Slic3r::CalibPressureAdvance::move_to (Vec2d pt, GCodeWriter & writer, std::string comment = std::string()) protected inherited
{
    std::stringstream gcode;
    gcode << writer.retract();
    gcode << writer.travel_to_xy(pt, comment);
    gcode << writer.unretract();
    m_last_pos = Vec3d(pt.x(), pt.y(), 0);
    return gcode.str();
}
References Slic3r::CalibPressureAdvance::m_last_pos, Slic3r::GCodeWriter::retract(), Slic3r::GCodeWriter::travel_to_xy(), and Slic3r::GCodeWriter::unretract().
Referenced by draw_box(), Slic3r::CalibPressureAdvance::draw_digit(), generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
number_spacing()
double Slic3r::CalibPressureAdvance::number_spacing () const inline protected inherited
{ return m_digit_segment_len + m_digit_gap_len; };
References Slic3r::CalibPressureAdvance::m_digit_gap_len, and Slic3r::CalibPressureAdvance::m_digit_segment_len.
Referenced by Slic3r::CalibPressureAdvance::draw_number().
object_size_x()
double Slic3r::CalibPressureAdvancePattern::object_size_x () const private
{
    return get_num_patterns() * ((wall_count() - 1) * line_spacing_angle()) +
        (get_num_patterns() - 1) * (m_pattern_spacing + line_width()) +
        std::cos(to_radians(m_corner_angle) / 2) * m_wall_side_length +
        line_spacing_first_layer() * wall_count()
    ;
}
References get_num_patterns(), line_spacing_angle(), line_spacing_first_layer(), line_width(), m_corner_angle, m_pattern_spacing, m_wall_side_length, to_radians(), and wall_count().
Referenced by print_size_x().
object_size_y()
double Slic3r::CalibPressureAdvancePattern::object_size_y () const private
{
    return 2 * (std::sin(to_radians(m_corner_angle) / 2) * m_wall_side_length) +
        max_numbering_height() +
        m_glyph_padding_vertical * 2 +
        line_width_first_layer();
}
References line_width_first_layer(), m_corner_angle, m_glyph_padding_vertical, m_wall_side_length, max_numbering_height(), and to_radians().
Referenced by print_size_y().
pattern_shift()
double Slic3r::CalibPressureAdvancePattern::pattern_shift () const private
{
    return
        (wall_count() - 1) * line_spacing_first_layer() +
        line_width_first_layer() +
        m_glyph_padding_horizontal
    ;
}
References line_spacing_first_layer(), line_width_first_layer(), m_glyph_padding_horizontal, and wall_count().
Referenced by generate_custom_gcodes(), glyph_start_x(), and print_size_x().
print_size_x()
double Slic3r::CalibPressureAdvancePattern::print_size_x () const inline
{ return object_size_x() + pattern_shift(); };
References object_size_x(), and pattern_shift().
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern(), and generate_custom_gcodes().
print_size_y()
double Slic3r::CalibPressureAdvancePattern::print_size_y () const inline
{ return object_size_y(); };
References object_size_y().
Referenced by Slic3r::GUI::Plater::_calib_pa_pattern().
refresh_setup()
void Slic3r::CalibPressureAdvancePattern::refresh_setup (const DynamicPrintConfig & config, bool is_bbl_machine, const Model & model, const Vec3d & origin) private
{
    m_config = config;
    m_config.apply(model.objects.front()->config.get(), true);
    m_config.apply(model.objects.front()->volumes.front()->config.get(), true);
    m_is_delta = (m_config.option<ConfigOptionPoints>("printable_area")->values.size() > 4);
    _refresh_starting_point(model);
    _refresh_writer(is_bbl_machine, model, origin);
}
References _refresh_starting_point(), _refresh_writer(), Slic3r::ConfigBase::apply(), m_config, m_is_delta, Slic3r::Model::objects, Slic3r::ConfigBase::option(), and Slic3r::ConfigOptionVector< T >::size().
Referenced by CalibPressureAdvancePattern(), and generate_custom_gcodes().
speed_adjust()
double Slic3r::CalibPressureAdvance::speed_adjust (int speed) const inline protected inherited
{ return speed * 60; };
Referenced by generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
speed_first_layer()
double Slic3r::CalibPressureAdvancePattern::speed_first_layer () const inline protected
{ return m_config.option<ConfigOptionFloat>("initial_layer_speed")->value; };
References m_config, and Slic3r::ConfigBase::option().
Referenced by generate_custom_gcodes().
speed_perimeter()
double Slic3r::CalibPressureAdvancePattern::speed_perimeter () const inline protected
{ return m_config.option<ConfigOptionFloat>("outer_wall_speed")->value; };
References m_config, and Slic3r::ConfigBase::option().
Referenced by generate_custom_gcodes().
to_radians()
double Slic3r::CalibPressureAdvancePattern::to_radians (double degrees) const inline private
{ return degrees * M_PI / 180; };
References M_PI.
Referenced by draw_box(), frame_size_y(), generate_custom_gcodes(), line_spacing_angle(), object_size_x(), and object_size_y().
wall_count()
int Slic3r::CalibPressureAdvancePattern::wall_count () const inline protected
{ return m_config.option<ConfigOptionInt>("wall_loops")->value; };
References m_config, and Slic3r::ConfigBase::option().
Referenced by generate_custom_gcodes(), glyph_start_x(), object_size_x(), and pattern_shift().
Friends And Related Symbol Documentation
DrawBoxOptArgs
friend struct DrawBoxOptArgs friend
DrawLineOptArgs
friend struct DrawLineOptArgs friend
Member Data Documentation
m_config
DynamicPrintConfig Slic3r::CalibPressureAdvancePattern::m_config private
Referenced by _refresh_writer(), draw_line(), generate_custom_gcodes(), height_first_layer(), height_layer(), line_width(), line_width_first_layer(), refresh_setup(), speed_first_layer(), speed_perimeter(), and wall_count().
m_corner_angle
const int Slic3r::CalibPressureAdvancePattern::m_corner_angle {90} private
Referenced by frame_size_y(), generate_custom_gcodes(), line_spacing_angle(), object_size_x(), and object_size_y().
m_digit_gap_len
const double Slic3r::CalibPressureAdvance::m_digit_gap_len {1} protected inherited
Referenced by max_numbering_height(), and Slic3r::CalibPressureAdvance::number_spacing().
m_digit_segment_len
const double Slic3r::CalibPressureAdvance::m_digit_segment_len {2} protected inherited
Referenced by Slic3r::CalibPressureAdvance::draw_digit(), glyph_length_x(), max_numbering_height(), and Slic3r::CalibPressureAdvance::number_spacing().
m_draw_digit_mode
DrawDigitMode Slic3r::CalibPressureAdvance::m_draw_digit_mode {DrawDigitMode::Left_To_Right} protected inherited
Referenced by CalibPressureAdvancePattern(), generate_custom_gcodes(), and Slic3r::CalibPressureAdvanceLine::print_pa_lines().
m_encroachment
const double Slic3r::CalibPressureAdvancePattern::m_encroachment {1. / 3.} private
Referenced by draw_box(), and generate_custom_gcodes().
m_glyph_padding_horizontal
const double Slic3r::CalibPressureAdvancePattern::m_glyph_padding_horizontal {1} private
Referenced by pattern_shift().
m_glyph_padding_vertical
const double Slic3r::CalibPressureAdvancePattern::m_glyph_padding_vertical {1} private
Referenced by generate_custom_gcodes(), and object_size_y().
m_handle_spacing
const double Slic3r::CalibPressureAdvancePattern::m_handle_spacing {2} private
Referenced by _refresh_starting_point(), and handle_spacing().
m_handle_xy_size
const double Slic3r::CalibPressureAdvancePattern::m_handle_xy_size {5} private
Referenced by handle_xy_size().
m_is_delta
bool Slic3r::CalibPressureAdvancePattern::m_is_delta private
Referenced by _refresh_starting_point(), and refresh_setup().
m_last_pos
Vec3d Slic3r::CalibPressureAdvance::m_last_pos protected inherited
Referenced by draw_line(), and Slic3r::CalibPressureAdvance::move_to().
m_max_number_len
const std::string::size_type Slic3r::CalibPressureAdvance::m_max_number_len {5} protected inherited
Referenced by Slic3r::CalibPressureAdvance::draw_number(), and max_numbering_height().
m_num_layers
const int Slic3r::CalibPressureAdvancePattern::m_num_layers {4} private
Referenced by generate_custom_gcodes(), and max_layer_z().
m_params
const Calib_Params& Slic3r::CalibPressureAdvancePattern::m_params private
Referenced by generate_custom_gcodes(), get_num_patterns(), and max_numbering_height().
m_pattern_spacing
const int Slic3r::CalibPressureAdvancePattern::m_pattern_spacing {2} private
Referenced by generate_custom_gcodes(), glyph_start_x(), and object_size_x().
m_starting_point
Vec3d Slic3r::CalibPressureAdvancePattern::m_starting_point private
Referenced by _refresh_starting_point(), generate_custom_gcodes(), glyph_start_x(), and glyph_tab_max_x().
m_wall_side_length
const double Slic3r::CalibPressureAdvancePattern::m_wall_side_length {30.0} private
Referenced by frame_size_y(), generate_custom_gcodes(), object_size_x(), and object_size_y().
m_writer
GCodeWriter Slic3r::CalibPressureAdvancePattern::m_writer private
Referenced by _refresh_writer(), draw_box(), draw_line(), and generate_custom_gcodes().
The documentation for this class was generated from the following files:
src/libslic3r/calib.hpp
src/libslic3r/calib.cpp