OrcaSlicer: src/slic3r/GUI/wxExtensions.hpp File Reference
wxExtensions.hpp File Reference
#include <wx/checklst.h>
#include <wx/combo.h>
#include <wx/dataview.h>
#include <wx/button.h>
#include <wx/sizer.h>
#include <wx/menu.h>
#include <wx/bmpcbox.h>
#include <wx/statbmp.h>
#include <wx/popupwin.h>
#include <wx/spinctrl.h>
#include <wx/artprov.h>
#include <vector>
#include <functional>
#include "Widgets/PopupWindow.hpp"
Classes
class wxCheckListBoxComboPopup
class wxDataViewTreeCtrlComboPopup
class ScalableBitmap
class LockButton
class ScalableButton
class ModeButton
class ModeSizer
class MenuWithSeparators
class BlinkingBitmap
class ImageTransientPopup
Namespaces
namespace Slic3r
namespace Slic3r::GUI
Functions
void msw_rescale_menu (wxMenu *)
wxMenuItem * append_menu_item (wxMenu *menu, int id, const wxString &string, const wxString &description, std::function< void(wxCommandEvent &event)> cb, const wxBitmap &icon, wxEvtHandler *event_handler=nullptr, std::function< bool()> const cb_condition=[]() { return true;}, wxWindow *parent=nullptr, int insert_pos=wxNOT_FOUND)
wxMenuItem * append_menu_item (wxMenu *menu, int id, const wxString &string, const wxString &description, std::function< void(wxCommandEvent &event)> cb, const std::string &icon="", wxEvtHandler *event_handler=nullptr, std::function< bool()> const cb_condition=[]() { return true;}, wxWindow *parent=nullptr, int insert_pos=wxNOT_FOUND)
wxMenuItem * append_submenu (wxMenu *menu, wxMenu *sub_menu, int id, const wxString &string, const wxString &description, const std::string &icon="", std::function< bool()> const cb_condition=[]() { return true;}, wxWindow *parent=nullptr)
wxMenuItem * append_menu_radio_item (wxMenu *menu, int id, const wxString &string, const wxString &description, std::function< void(wxCommandEvent &event)> cb, wxEvtHandler *event_handler)
wxMenuItem * append_menu_check_item (wxMenu *menu, int id, const wxString &string, const wxString &description, std::function< void(wxCommandEvent &event)> cb, wxEvtHandler *event_handler, std::function< bool()> const enable_condition=[]() { return true;}, std::function< bool()> const check_condition=[]() { return true;}, wxWindow *parent=nullptr)
void enable_menu_item (wxUpdateUIEvent &evt, std::function< bool()> const cb_condition, wxMenuItem *item, wxWindow *win)
void edit_tooltip (wxString &tooltip)
void msw_buttons_rescale (wxDialog *dlg, const int em_unit, const std::vector< int > &btn_ids)
int em_unit (wxWindow *win)
int mode_icon_px_size ()
wxBitmap create_menu_bitmap (const std::string &bmp_name)
wxBitmap create_scaled_bitmap (const std::string &bmp_name, wxWindow *win=nullptr, const int px_cnt=16, const bool grayscale=false, const std::string &new_color=std::string(), const bool menu_bitmap=false, const bool resize=false)
wxBitmap * get_default_extruder_color_icon (bool thin_icon=false)
std::vector< wxBitmap * > get_extruder_color_icons (bool thin_icon=false)
void apply_extruder_selector (Slic3r::GUI::BitmapComboBox **ctrl, wxWindow *parent, const std::string &first_item="", wxPoint pos=wxDefaultPosition, wxSize size=wxDefaultSize, bool use_thin_icon=false)
Function Documentation
append_menu_check_item()
wxMenuItem * append_menu_check_item (wxMenu * menu, int id, const wxString & string, const wxString & description, std::function< void(wxCommandEvent &event)> cb, wxEvtHandler * event_handler, std::function< bool()> const enable_condition = []() { return true;}, std::function< bool()> const check_condition = []() { return true;}, wxWindow * parent = nullptr)
{
    if (id == wxID_ANY)
        id = wxNewId();
    wxMenuItem* item = menu->AppendCheckItem(id, string, description);
#ifdef __WXMSW__
    if (event_handler != nullptr && event_handler != menu)
        event_handler->Bind(wxEVT_MENU, cb, id);
    else
#endif // __WXMSW__
        menu->Bind(wxEVT_MENU, cb, id);
    if (parent)
        parent->Bind(wxEVT_UPDATE_UI, [enable_condition, check_condition](wxUpdateUIEvent& evt)
            {
                evt.Enable(enable_condition());
                evt.Check(check_condition());
            }, id);
    return item;
}
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_printable(), Slic3r::GUI::MenuFactory::append_menu_items_flush_options(), Slic3r::GUI::MenuFactory::create_default_menu(), and Slic3r::GUI::MainFrame::init_menubar_as_editor().
append_menu_item() [1/2]
wxMenuItem * append_menu_item (wxMenu * menu, int id, const wxString & string, const wxString & description, std::function< void(wxCommandEvent &event)> cb, const std::string & icon = "", wxEvtHandler * event_handler = nullptr, std::function< bool()> const cb_condition = []() { return true;}, wxWindow * parent = nullptr, int insert_pos = wxNOT_FOUND)
{
    if (id == wxID_ANY)
        id = wxNewId();
    const wxBitmap& bmp = !icon.empty() ? create_menu_bitmap(icon) : wxNullBitmap;   // FIXME: pass window ptr
//#ifdef __WXMSW__
#ifndef __WXGTK__
    if (bmp.IsOk())
        msw_menuitem_bitmaps[id] = icon;
#endif /* __WXMSW__ */
    return append_menu_item(menu, id, string, description, cb, bmp, event_handler, cb_condition, parent, insert_pos);
}
References append_menu_item(), create_menu_bitmap(), and msw_menuitem_bitmaps.
append_menu_item() [2/2]
wxMenuItem * append_menu_item (wxMenu * menu, int id, const wxString & string, const wxString & description, std::function< void(wxCommandEvent &event)> cb, const wxBitmap & icon, wxEvtHandler * event_handler = nullptr, std::function< bool()> const cb_condition = []() { return true;}, wxWindow * parent = nullptr, int insert_pos = wxNOT_FOUND)
{
    if (id == wxID_ANY)
        id = wxNewId();
    auto *item = new wxMenuItem(menu, id, string, description);
    if (icon.IsOk()) {
        item->SetBitmap(icon);
    }
    if (insert_pos == wxNOT_FOUND)
        menu->Append(item);
    else
        menu->Insert(insert_pos, item);
#ifdef __WXMSW__
    if (event_handler != nullptr && event_handler != menu)
        event_handler->Bind(wxEVT_MENU, cb, id);
    else
#endif // __WXMSW__
        menu->Bind(wxEVT_MENU, cb, id);
    if (parent) {
        parent->Bind(wxEVT_UPDATE_UI, [cb_condition, item, parent](wxUpdateUIEvent& evt) {
            enable_menu_item(evt, cb_condition, item, parent); }, id);
    }
    return item;
}
References enable_menu_item().
Referenced by Slic3r::GUI::add_common_publish_menu_items(), Slic3r::GUI::add_common_view_menu_items(), append_menu_item(), Slic3r::GUI::MenuFactory::append_menu_item_center(), Slic3r::GUI::MenuFactory::append_menu_item_change_extruder(), Slic3r::GUI::MenuFactory::append_menu_item_change_filament(), Slic3r::GUI::MenuFactory::append_menu_item_change_type(), Slic3r::GUI::MenuFactory::append_menu_item_clone(), Slic3r::GUI::MenuFactory::append_menu_item_delete(), Slic3r::GUI::MenuFactory::append_menu_item_edit_text(), Slic3r::GUI::MenuFactory::append_menu_item_export_stl(), Slic3r::GUI::MenuFactory::append_menu_item_fill_bed(), Slic3r::GUI::MenuFactory::append_menu_item_fix_through_netfabb(), Slic3r::GUI::MenuFactory::append_menu_item_instance_to_object(), Slic3r::GUI::MenuFactory::append_menu_item_invalidate_cut_info(), Slic3r::GUI::MenuFactory::append_menu_item_layers_editing(), Slic3r::GUI::MenuFactory::append_menu_item_locked(), Slic3r::GUI::MenuFactory::append_menu_item_merge_parts_to_single_part(), Slic3r::GUI::MenuFactory::append_menu_item_merge_to_multipart_object(), Slic3r::GUI::MenuFactory::append_menu_item_merge_to_single_object(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_process(), Slic3r::GUI::MenuFactory::append_menu_item_per_object_settings(), Slic3r::GUI::MenuFactory::append_menu_item_reload_from_disk(), Slic3r::GUI::MenuFactory::append_menu_item_rename(), Slic3r::GUI::MenuFactory::append_menu_item_replace_with_stl(), Slic3r::GUI::MenuFactory::append_menu_item_scale_selection_to_fit_print_volume(), Slic3r::GUI::MenuFactory::append_menu_item_set_printable(), Slic3r::GUI::MenuFactory::append_menu_item_set_visible(), Slic3r::GUI::MenuFactory::append_menu_item_simplify(), Slic3r::GUI::MenuFactory::append_menu_items_convert_unit(), Slic3r::GUI::MenuFactory::append_menu_items_mirror(), Slic3r::GUI::MenuFactory::append_submenu_add_generic(), Slic3r::GUI::MenuFactory::create_bbl_part_menu(), Slic3r::GUI::MenuFactory::create_extra_object_menu(), Slic3r::GUI::create_freq_settings_popupmenu(), Slic3r::GUI::MenuFactory::create_object_menu(), Slic3r::GUI::MenuFactory::create_part_menu(), Slic3r::GUI::MenuFactory::create_plate_menu(), Slic3r::GUI::create_settings_popupmenu(), Slic3r::GUI::MenuFactory::create_sla_object_menu(), Slic3r::GUI::generate_help_menu(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), Slic3r::GUI::MainFrame::init_menubar_as_gcodeviewer(), Slic3r::GUI::MenuFactory::multi_selection_menu(), AuxiliaryList::on_context_menu(), Slic3r::GUI::PlaterPresetComboBox::show_add_menu(), and Slic3r::GUI::PlaterPresetComboBox::show_edit_menu().
append_menu_radio_item()
wxMenuItem * append_menu_radio_item (wxMenu * menu, int id, const wxString & string, const wxString & description, std::function< void(wxCommandEvent &event)> cb, wxEvtHandler * event_handler)
{
    if (id == wxID_ANY)
        id = wxNewId();
    wxMenuItem* item = menu->AppendRadioItem(id, string, description);
#ifdef __WXMSW__
    if (event_handler != nullptr && event_handler != menu)
        event_handler->Bind(wxEVT_MENU, cb, id);
    else
#endif // __WXMSW__
        menu->Bind(wxEVT_MENU, cb, id);
    return item;
}
Referenced by Slic3r::GUI::MainFrame::init_menubar_as_editor().
append_submenu()
wxMenuItem * append_submenu (wxMenu * menu, wxMenu * sub_menu, int id, const wxString & string, const wxString & description, const std::string & icon = "", std::function< bool()> const cb_condition = []() { return true;}, wxWindow * parent = nullptr)
{
    if (id == wxID_ANY)
        id = wxNewId();
    wxMenuItem* item = new wxMenuItem(menu, id, string, description, wxITEM_NORMAL, sub_menu);
    if (!icon.empty()) {
        item->SetBitmap(create_menu_bitmap(icon));    // FIXME: pass window ptr
//#ifdef __WXMSW__
#ifndef __WXGTK__
        msw_menuitem_bitmaps[id] = icon;
#endif /* __WXMSW__ */
    }
    menu->Append(item);
    if (parent) {
        parent->Bind(wxEVT_UPDATE_UI, [cb_condition, item, parent](wxUpdateUIEvent& evt) {
            enable_menu_item(evt, cb_condition, item, parent); }, id);
    }
    return item;
}
References create_menu_bitmap(), enable_menu_item(), and msw_menuitem_bitmaps.
Referenced by Slic3r::GUI::MenuFactory::append_menu_items_add_volume(), Slic3r::GUI::MenuFactory::append_menu_items_mirror(), Slic3r::GUI::MenuFactory::create_bbl_part_menu(), Slic3r::GUI::MenuFactory::create_default_menu(), Slic3r::GUI::MenuFactory::create_extra_object_menu(), Slic3r::GUI::MenuFactory::create_object_menu(), Slic3r::GUI::MenuFactory::create_plate_menu(), Slic3r::GUI::MainFrame::init_menubar_as_editor(), and Slic3r::GUI::MenuFactory::multi_selection_menu().
apply_extruder_selector()
void apply_extruder_selector (Slic3r::GUI::BitmapComboBox ** ctrl, wxWindow * parent, const std::string & first_item = "", wxPoint pos = wxDefaultPosition, wxSize size = wxDefaultSize, bool use_thin_icon = false)
{
    std::vector<wxBitmap*> icons = get_extruder_color_icons(use_thin_icon);
    if (!*ctrl) {
        *ctrl = new Slic3r::GUI::BitmapComboBox(parent, wxID_ANY, wxEmptyString, pos, size, 0, nullptr, wxCB_READONLY);
        Slic3r::GUI::wxGetApp().UpdateDarkUI(*ctrl);
    }
    else
    {
        (*ctrl)->SetPosition(pos);
        (*ctrl)->SetMinSize(size);
        (*ctrl)->SetSize(size);
        (*ctrl)->Clear();
    }
    if (first_item.empty())
        (*ctrl)->Hide();    // to avoid unwanted rendering before layout (ExtruderSequenceDialog)
    if (icons.empty() && !first_item.empty()) {
        (*ctrl)->Append(_(first_item), wxNullBitmap);
        return;
    }
    // For ObjectList we use short extruder name (just a number)
    const bool use_full_item_name = dynamic_cast<Slic3r::GUI::ObjectList*>(parent) == nullptr;
    int i = 0;
    wxString str = _(L("Extruder"));
    for (wxBitmap* bmp : icons) {
        if (i == 0) {
            if (!first_item.empty())
                (*ctrl)->Append(_(first_item), *bmp);
            ++i;
        }
        (*ctrl)->Append(use_full_item_name
                        ? Slic3r::GUI::from_u8((boost::format("%1% %2%") % str % i).str())
                        : wxString::Format("%d", i), *bmp);
        ++i;
    }
    (*ctrl)->SetSelection(0);
}
References _, Slic3r::GUI::from_u8(), get_extruder_color_icons(), L, and size.
Referenced by Slic3r::GUI::ObjectList::extruder_editing().
create_menu_bitmap()
wxBitmap create_menu_bitmap (const std::string & bmp_name)
{
    return create_scaled_bitmap(bmp_name, nullptr, 16, false, "", true);
}
References create_scaled_bitmap().
Referenced by append_menu_item(), and append_submenu().
create_scaled_bitmap()
wxBitmap create_scaled_bitmap (const std::string & bmp_name, wxWindow * win = nullptr, const int px_cnt = 16, const bool grayscale = false, const std::string & new_color = std::string(), const bool menu_bitmap = false, const bool resize = false)
{
    static Slic3r::GUI::BitmapCache cache;
    unsigned int width = 0;
    unsigned int height = (unsigned int) (win->FromDIP(px_cnt) + 0.5f);
    std::string bmp_name = bmp_name_in;
    boost::replace_last(bmp_name, ".png", "");
    bool dark_mode =
#ifdef _WIN32
    menu_bitmap ? Slic3r::GUI::check_dark_mode() :
#endif
    Slic3r::GUI::wxGetApp().dark_mode();
    // Try loading an SVG first, then PNG if SVG is not found:
    wxBitmap *bmp = cache.load_svg(bmp_name, width, height, grayscale, dark_mode, new_color, resize ? em_unit(win) * 0.1f : 0.f);
    if (bmp == nullptr) {
        bmp = cache.load_png(bmp_name, width, height, grayscale, resize ? em_unit(win) * 0.1f : 0.f);
    }
    if (bmp == nullptr) {
        // Neither SVG nor PNG has been found, raise error
        throw Slic3r::RuntimeError("Could not load bitmap: " + bmp_name);
    }
    return *bmp;
}
References Slic3r::GUI::check_dark_mode(), em_unit(), int, Slic3r::GUI::BitmapCache::load_png(), and Slic3r::GUI::BitmapCache::load_svg().
Referenced by Slic3r::GUI::AddMachinePanel::AddMachinePanel(), Slic3r::GUI::AMSControl::AMSControl(), Slic3r::GUI::AmsHumidityTipPopup::AmsHumidityTipPopup(), Slic3r::GUI::AmsIntroducePopup::AmsIntroducePopup(), Slic3r::GUI::AmsMapingTipPopup::AmsMapingTipPopup(), Slic3r::GUI::AmsPanel::AmsPanel(), Slic3r::GUI::AmsTutorialPopup::AmsTutorialPopup(), Slic3r::GUI::AuFile::AuFile(), AuxiliaryList::AuxiliaryList(), Slic3r::GUI::BindMachineDialog::BindMachineDialog(), Slic3r::GUI::ColorPicker::ColorPicker(), Slic3r::GUI::ErrorDialog::ErrorDialog(), Slic3r::GUI::ExtensionPanel::ExtensionPanel(), Slic3r::GUI::InputIpAddressDialog::InputIpAddressDialog(), Slic3r::GUI::MappingContainer::MappingContainer(), Slic3r::GUI::MsgUpdateConfig::MsgUpdateConfig(), Slic3r::GUI::ObjectDataViewModel::ObjectDataViewModel(), Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode(), Slic3r::GUI::ObjectDataViewModelNode::ObjectDataViewModelNode(), Slic3r::GUI::OG_CustomCtrl::OG_CustomCtrl(), Slic3r::GUI::ReleaseNoteDialog::ReleaseNoteDialog(), ScalableBitmap::ScalableBitmap(), ScalableButton::ScalableButton(), Slic3r::GUI::SendToPrinterDialog::SendToPrinterDialog(), Slic3r::GUI::SliceInfoPopup::SliceInfoPopup(), Slic3r::GUI::UnBindMachineDialog::UnBindMachineDialog(), Slic3r::GUI::UpdatePluginDialog::UpdatePluginDialog(), Slic3r::GUI::UpdateVersionDialog::UpdateVersionDialog(), Slic3r::GUI::MenuFactory::append_menu_item_settings(), Slic3r::GUI::MsgDialog::apply_style(), Slic3r::GUI::AMSSetting::create(), Slic3r::GUI::SelectMachineDialog::create_ams_checkbox(), create_menu_bitmap(), Slic3r::GUI::AMSMaterialsSetting::create_panel_normal(), Slic3r::GUI::GridCellSupportRenderer::Draw(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::draw_blinking_bmp(), enable_menu_item(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::PresetComboBox::get_bmp(), Slic3r::GUI::SettingsFactory::get_category_bitmap(), Slic3r::GUI::MenuFactory::get_volume_bitmaps(), BBLTopbar::Init(), Slic3r::GUI::ConnectPrinterDialog::init_bitmap(), Slic3r::GUI::ObjectTablePanel::init_bitmap(), Slic3r::GUI::MonitorPanel::init_bitmap(), Slic3r::GUI::ExtrusionCalibration::init_bitmaps(), Slic3r::GUI::HMSNotifyItem::init_bitmaps(), Slic3r::GUI::StatusBasePanel::init_bitmaps(), Slic3r::GUI::MachineInfoPanel::init_bitmaps(), Slic3r::GUI::ColorPicker::msw_rescale(), Slic3r::GUI::ObjectDataViewModelNode::msw_rescale(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::msw_rescale(), Slic3r::GUI::OG_CustomCtrl::msw_rescale(), ScalableBitmap::msw_rescale(), ScalableButton::msw_rescale(), Slic3r::GUI::BindMachineDialog::on_show(), Slic3r::GUI::UnBindMachineDialog::on_show(), Slic3r::GUI::ExtrusionCalibration::open_bitmap(), BBLTopbar::Rescale(), Slic3r::GUI::ObjectDataViewModel::Rescale(), Slic3r::GUI::ObjectDataViewModelNode::set_action_icon(), Slic3r::GUI::ObjectDataViewModelNode::set_color_icon(), Slic3r::GUI::ObjectDataViewModelNode::set_printable_icon(), Slic3r::GUI::ObjectDataViewModelNode::set_sinking_icon(), Slic3r::GUI::ObjectDataViewModelNode::set_support_icon(), ScalableButton::SetBitmap_(), Slic3r::GUI::MachineInfoPanel::Update_printer_img(), Slic3r::GUI::SavePresetDialog::Item::update_valid_bmp(), Slic3r::GUI::ModelNode::UpdateIcons(), and ScalableButton::UseDefaultBitmapDisabled().
edit_tooltip()
void edit_tooltip (wxString & tooltip)
{
    tooltip.Replace("Slic3r", SLIC3R_APP_KEY, true);
}
Referenced by Slic3r::GUI::OptionsGroup::create_single_option_line(), and Slic3r::GUI::Field::get_tooltip_text().
em_unit()
int em_unit (wxWindow * win)
{
    if (win)
    {
        wxTopLevelWindow *toplevel = Slic3r::GUI::find_toplevel_parent(win);
        Slic3r::GUI::DPIDialog* dlg = dynamic_cast<Slic3r::GUI::DPIDialog*>(toplevel);
        if (dlg)
            return dlg->em_unit();
        Slic3r::GUI::DPIFrame* frame = dynamic_cast<Slic3r::GUI::DPIFrame*>(toplevel);
        if (frame)
            return frame->em_unit();
    }
    return Slic3r::GUI::wxGetApp().em_unit();
}
References Slic3r::GUI::DPIAware< P >::em_unit(), and Slic3r::GUI::find_toplevel_parent().
Referenced by ButtonsListCtrl::ButtonsListCtrl(), Slic3r::GUI::DiamTextCtrl::DiamTextCtrl(), Slic3r::GUI::MediaFilePanel::MediaFilePanel(), Slic3r::GUI::ObjectLayers::ObjectLayers(), Slic3r::GUI::OG_CustomCtrl::OG_CustomCtrl(), Slic3r::GUI::ogStaticText::ogStaticText(), Slic3r::GUI::ParamsPanel::ParamsPanel(), ScalableButton::ScalableButton(), Slic3r::GUI::Tab::Tab(), TabButtonsListCtrl::TabButtonsListCtrl(), Slic3r::GUI::GLCanvas3D::_render_paint_toolbar(), Slic3r::GUI::OptionsGroup::activate_line(), Slic3r::GUI::BedShapePanel::build_panel(), Slic3r::GUI::Sidebar::change_top_border_for_mode_sizer(), Slic3r::GUI::ObjectLayers::create_layer(), Slic3r::GUI::ObjectLayers::create_layers_list(), Slic3r::GUI::ParamsPanel::create_layout(), Slic3r::GUI::Tab::create_preset_tab(), create_scaled_bitmap(), Slic3r::GUI::MainFrame::create_side_tools(), Slic3r::GUI::ModelNode::get_bitmap(), Slic3r::GUI::ObjectDataViewModel::GetVolumeIcon(), TabButtonsListCtrl::InsertPage(), ButtonsListCtrl::InsertPage(), msw_buttons_rescale(), Slic3r::GUI::Field::msw_rescale(), Slic3r::GUI::LayerRangeEditor::msw_rescale(), Slic3r::GUI::ObjectLayers::msw_rescale(), Slic3r::GUI::OG_CustomCtrl::msw_rescale(), Slic3r::GUI::ParamsPanel::msw_rescale(), Slic3r::GUI::Sidebar::msw_rescale(), Slic3r::GUI::PresetComboBox::msw_rescale(), Slic3r::GUI::Tab::msw_rescale(), ScalableButton::msw_rescale(), ModeSizer::msw_rescale(), Slic3r::GUI::StatusPanel::on_switch_speed(), Slic3r::GUI::Field::PostInitialize(), BBLTopbar::Rescale(), Slic3r::GUI::ImageGrid::Rescale(), Slic3r::GUI::MediaFilePanel::Rescale(), ButtonsListCtrl::Rescale(), TabButtonsListCtrl::Rescale(), Slic3r::GUI::ObjectList::set_min_height(), Slic3r::GUI::ObjectList::set_tooltip_for_item(), Slic3r::GUI::ogStaticText::SetText(), Slic3r::GUI::ObjectList::update_name_column_width(), Slic3r::GUI::ObjectDataViewModelNode::update_settings_digest_bitmaps(), Slic3r::GUI::MainFrame::update_side_button_style(), Slic3r::GUI::ImageGrid::UpdateFileSystem(), and Slic3r::GUI::ImageGrid::UpdateLayout().
enable_menu_item()
void enable_menu_item (wxUpdateUIEvent & evt, std::function< bool()> const cb_condition, wxMenuItem * item, wxWindow * win)
{
    const bool enable = cb_condition();
    evt.Enable(enable);
#ifdef __WXOSX__
    const auto it = msw_menuitem_bitmaps.find(item->GetId());
    if (it != msw_menuitem_bitmaps.end())
    {
        const wxBitmap& item_icon = create_scaled_bitmap(it->second, win, 16, !enable);
        if (item_icon.IsOk())
            item->SetBitmap(item_icon);
    }
#endif // __WXOSX__
}
References create_scaled_bitmap(), and msw_menuitem_bitmaps.
Referenced by append_menu_item(), and append_submenu().
get_default_extruder_color_icon()
wxBitmap * get_default_extruder_color_icon (bool thin_icon = false)
{
    static Slic3r::GUI::BitmapCache bmp_cache;
    const double em = Slic3r::GUI::wxGetApp().em_unit();
    const int icon_width = lround((thin_icon ? 2 : 4.5) * em);
    const int icon_height = lround(2 * em);
    bool dark_mode = Slic3r::GUI::wxGetApp().dark_mode();
    wxClientDC cdc((wxWindow*)Slic3r::GUI::wxGetApp().mainframe);
    wxMemoryDC dc(&cdc);
    dc.SetFont(::Label::Body_12);
    wxString label = _L("default");
    std::string bitmap_key = std::string("default_color") + "-h" + std::to_string(icon_height) + "-w" + std::to_string(icon_width)
        + "-i" + label.ToStdString();
    wxBitmap* bitmap = bmp_cache.find(bitmap_key);
    if (bitmap == nullptr) {
        // Paint the color icon.
            //Slic3r::GUI::BitmapCache::parse_color(color, rgb);
            // there is no neede to scale created solid bitmap
        wxColor clr(255, 255, 255, 0);
        bitmap = bmp_cache.insert(bitmap_key, wxBitmap(icon_width, icon_height));
        dc.SelectObject(*bitmap);
        dc.SetBackground(wxBrush(clr));
        dc.Clear();
        dc.SetBrush(wxBrush(clr));
        dc.SetPen(*wxGREY_PEN);
        auto size = dc.GetTextExtent(wxString(label));
        dc.SetTextForeground(clr.GetLuminance() < 0.51 ? *wxWHITE : *wxBLACK);
        dc.DrawText(label, (icon_width - size.x) / 2, (icon_height - size.y) / 2);
        dc.SelectObject(wxNullBitmap);
    }
    return bitmap;
}
References _L, Label::Body_12, Slic3r::GUI::BitmapCache::find(), Slic3r::GUI::BitmapCache::insert(), and size.
Referenced by BitmapChoiceRenderer::CreateEditorCtrl(), and Slic3r::GUI::ObjectDataViewModelNode::UpdateExtruderAndColorIcon().
get_extruder_color_icons()
std::vector< wxBitmap * > get_extruder_color_icons (bool thin_icon = false)
{
    static Slic3r::GUI::BitmapCache bmp_cache;
    // Create the bitmap with color bars.
    std::vector<wxBitmap*> bmps;
    std::vector<std::string> colors = Slic3r::GUI::wxGetApp().plater()->get_extruder_colors_from_plater_config();
    if (colors.empty())
        return bmps;
    unsigned char rgb[3];
    /* It's supposed that standard size of an icon is 36px*16px for 100% scaled display.
     * So set sizes for solid_colored icons used for filament preset
     * and scale them in respect to em_unit value
     */
    const double em = Slic3r::GUI::wxGetApp().em_unit();
    const int icon_width = lround((thin_icon ? 2 : 4.5) * em);
    const int icon_height = lround(2 * em);
    bool dark_mode = Slic3r::GUI::wxGetApp().dark_mode();
    int index = 0;
    wxClientDC cdc((wxWindow*)Slic3r::GUI::wxGetApp().mainframe);
    wxMemoryDC dc(&cdc);
    dc.SetFont(::Label::Body_12);
    for (const std::string &color : colors)
    {
        auto label = std::to_string(++index);
        std::string bitmap_key = color + "-h" + std::to_string(icon_height) + "-w" + std::to_string(icon_width)
                + "-i" + label;
        wxBitmap* bitmap = bmp_cache.find(bitmap_key);
        if (bitmap == nullptr) {
            // Paint the color icon.
            //Slic3r::GUI::BitmapCache::parse_color(color, rgb);
            // there is no neede to scale created solid bitmap
            wxColor clr(color);
            bitmap = bmp_cache.insert(bitmap_key, wxBitmap(icon_width, icon_height));
            dc.SelectObject(*bitmap);
            dc.SetBackground(wxBrush(clr));
            dc.Clear();
            if (clr.Red() > 224 && clr.Blue() > 224 && clr.Green() > 224) {
                dc.SetBrush(wxBrush(clr));
                dc.SetPen(*wxGREY_PEN);
                dc.DrawRectangle(0, 0, icon_width, icon_height);
            }
            auto size = dc.GetTextExtent(wxString(label));
            dc.SetTextForeground(clr.GetLuminance() < 0.51 ? *wxWHITE : *wxBLACK);
            dc.DrawText(label, (icon_width - size.x) / 2, (icon_height - size.y) / 2);
            dc.SelectObject(wxNullBitmap);
        }
        bmps.emplace_back(bitmap);
    }
    return bmps;
}
References Label::Body_12, Slic3r::GUI::BitmapCache::find(), Slic3r::GUI::BitmapCache::insert(), and size.
Referenced by Slic3r::GUI::MenuFactory::append_menu_item_change_extruder(), Slic3r::GUI::MenuFactory::append_menu_item_change_filament(), apply_extruder_selector(), BitmapChoiceRenderer::CreateEditorCtrl(), Slic3r::GUI::ObjectTablePanel::init_bitmap(), Slic3r::GUI::DynamicFilamentList::update(), and Slic3r::GUI::ObjectDataViewModelNode::UpdateExtruderAndColorIcon().
mode_icon_px_size()
int mode_icon_px_size ()
{
#ifdef __APPLE__
    return 10;
#else
    return 12;
#endif
}
Referenced by ModeSizer::ModeSizer().
msw_buttons_rescale()
void msw_buttons_rescale (wxDialog * dlg, const int em_unit, const std::vector< int > & btn_ids)
{
    const wxSize& btn_size = wxSize(-1, int(2.5f * em_unit + 0.5f));
    for (int btn_id : btn_ids) {
        // There is a case [FirmwareDialog], when we have wxControl instead of wxButton
        // so let casting everything to the wxControl
        wxControl* btn = static_cast<wxControl*>(dlg->FindWindowById(btn_id, dlg));
        if (btn)
            btn->SetMinSize(btn_size);
    }
}
References em_unit().
Referenced by Slic3r::GUI::SendSystemInfoDialog::on_dpi_changed(), Slic3r::GUI::CopyrightsDialog::on_dpi_changed(), Slic3r::GUI::AboutDialog::on_dpi_changed(), Slic3r::GUI::ConfigWizard::on_dpi_changed(), Slic3r::GUI::KBShortcutsDialog::on_dpi_changed(), Slic3r::GUI::PhysicalPrinterDialog::on_dpi_changed(), Slic3r::GUI::PrintHostQueueDialog::on_dpi_changed(), Slic3r::GUI::SavePresetDialog::on_dpi_changed(), Slic3r::GUI::SysInfoDialog::on_dpi_changed(), Slic3r::GUI::UnsavedChangesDialog::on_dpi_changed(), and Slic3r::GUI::DiffPresetDialog::on_dpi_changed().
msw_rescale_menu()
void msw_rescale_menu (wxMenu *) inline
{}
Referenced by Slic3r::GUI::MenuFactory::msw_rescale(), Slic3r::GUI::MainFrame::on_dpi_changed(), Slic3r::GUI::MenuFactory::sys_color_changed(), and Slic3r::GUI::MenuFactory::sys_color_changed().