OrcaSlicer: TabButtonsListCtrl Class Reference
TabButtonsListCtrl Class Reference
#include <src/slic3r/GUI/Tabbook.hpp>
Public Member Functions
TabButtonsListCtrl (wxWindow *parent, wxBoxSizer *side_tools=NULL)
~TabButtonsListCtrl ()
void OnPaint (wxPaintEvent &)
void SetSelection (int sel)
void Rescale ()
bool InsertPage (size_t n, const wxString &text, bool bSelect=false, const std::string &bmp_name="")
void RemovePage (size_t n)
bool SetPageImage (size_t n, const std::string &bmp_name) const
void SetPageText (size_t n, const wxString &strText)
wxString GetPageText (size_t n) const
Private Attributes
wxWindow * m_parent
wxFlexGridSizer * m_buttons_sizer
wxBoxSizer * m_sizer
ScalableBitmap m_arrow_img
std::vector< TabButton * > m_pageButtons
int m_selection {-1}
int m_btn_margin
int m_line_margin
Detailed Description
Constructor & Destructor Documentation
TabButtonsListCtrl()
TabButtonsListCtrl::TabButtonsListCtrl (wxWindow * parent, wxBoxSizer * side_tools = NULL)
                                                                               :
    wxControl(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE | wxTAB_TRAVERSAL)
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    SetBackgroundColour(TAB_BUTTON_BG);
    int em = em_unit(this);
    // BBS: no gap
    m_btn_margin = 0;
    m_line_margin = std::lround(0.1 * em);
    m_arrow_img = ScalableBitmap(this, "monitor_arrow", 14);
    m_sizer = new wxBoxSizer(wxVERTICAL);
    this->SetSizer(m_sizer);
    if (side_tools != NULL) {
        for (size_t idx = 0; idx < side_tools->GetItemCount(); idx++) {
            wxSizerItem *item     = side_tools->GetItem(idx);
            wxWindow *   item_win = item->GetWindow();
            if (item_win) { item_win->Reparent(this); }
        }
        m_sizer->Add(side_tools, 0, wxEXPAND | wxLEFT | wxTOP, m_btn_margin);
    }
    m_buttons_sizer = new wxFlexGridSizer(1, m_btn_margin, m_btn_margin);
    m_sizer->Add(m_buttons_sizer, 0, wxLEFT | wxTOP, m_btn_margin);
    m_sizer->AddStretchSpacer(1);
}
References em_unit(), m_arrow_img, m_btn_margin, m_buttons_sizer, m_line_margin, m_sizer, NULL, and TAB_BUTTON_BG.
~TabButtonsListCtrl()
TabButtonsListCtrl::~TabButtonsListCtrl () inline
{}
Member Function Documentation
GetPageText()
wxString TabButtonsListCtrl::GetPageText (size_t n) const
{
    TabButton *btn = m_pageButtons[n];
    return btn->GetLabel();
}
References m_pageButtons, and n.
Referenced by Tabbook::GetPageText().
InsertPage()
bool TabButtonsListCtrl::InsertPage (size_t n, const wxString & text, bool bSelect = false, const std::string & bmp_name = "")
{
    TabButton *btn = new TabButton(this, text, m_arrow_img, wxNO_BORDER);
    btn->SetCornerRadius(0);
    int em = em_unit(this);
    btn->SetMinSize({BUTTON_DEF_WIDTH * em / 10, BUTTON_DEF_HEIGHT * em / 10});
    btn->SetBackgroundColor(TAB_BUTTON_BG);
    btn->SetTextColor(*wxBLACK);
    btn->Bind(wxEVT_BUTTON, [this, btn](wxCommandEvent& event) {
        if (auto it = std::find(m_pageButtons.begin(), m_pageButtons.end(), btn); it != m_pageButtons.end()) {
            auto sel = it - m_pageButtons.begin();
            SetSelection(sel);
            wxCommandEvent evt = wxCommandEvent(wxCUSTOMEVT_TABBOOK_SEL_CHANGED);
            evt.SetId(sel);
            wxPostEvent(this->GetParent(), evt);
        }
    });
    Slic3r::GUI::wxGetApp().UpdateDarkUI(btn);
    m_pageButtons.insert(m_pageButtons.begin() + n, btn);
    m_buttons_sizer->Insert(n, new wxSizerItem(btn));
    m_buttons_sizer->SetRows(m_pageButtons.size() + 1);
    m_sizer->Layout();
    return true;
}
References BUTTON_DEF_HEIGHT, BUTTON_DEF_WIDTH, em_unit(), m_arrow_img, m_buttons_sizer, m_pageButtons, m_sizer, n, StaticBox::SetBackgroundColor(), StaticBox::SetCornerRadius(), TabButton::SetMinSize(), SetSelection(), TabButton::SetTextColor(), TAB_BUTTON_BG, and wxEVT_BUTTON.
Referenced by Tabbook::InsertNewPage(), and Tabbook::InsertPage().
OnPaint()
void TabButtonsListCtrl::OnPaint (wxPaintEvent &)
{
    Slic3r::GUI::wxGetApp().UpdateDarkUI(this);
    const wxSize sz = GetSize();
    wxPaintDC dc(this);
    if (m_selection < 0 || m_selection >= (int)m_pageButtons.size())
        return;
    const wxColour& btn_marker_color = Slic3r::GUI::wxGetApp().get_color_hovered_btn_label();
    // highlight selected notebook button
    for (int idx = 0; idx < int(m_pageButtons.size()); idx++) {
        TabButton *btn = m_pageButtons[idx];
        btn->SetBackgroundColor(idx == m_selection ? TAB_BUTTON_SEL : TAB_BUTTON_BG);
        wxPoint pos = btn->GetPosition();
        wxSize size = btn->GetSize();
        const wxColour &clr  = StateColor::darkModeColorFor(idx == m_selection ? btn_marker_color : TAB_BUTTON_BG);
        dc.SetPen(clr);
        dc.SetBrush(clr);
        dc.DrawRectangle(pos.x, pos.y + size.y, size.x, sz.y - size.y);
    }
    dc.SetPen(btn_marker_color);
    dc.SetBrush(btn_marker_color);
    dc.DrawRectangle(1, sz.y - m_line_margin, sz.x, m_line_margin);
}
References StateColor::darkModeColorFor(), int, m_line_margin, m_pageButtons, m_selection, StaticBox::SetBackgroundColor(), size, TAB_BUTTON_BG, and TAB_BUTTON_SEL.
RemovePage()
void TabButtonsListCtrl::RemovePage (size_t n)
{
    if (n >= m_pageButtons.size()) return;
    TabButton *btn = m_pageButtons[n];
    m_pageButtons.erase(m_pageButtons.begin() + n);
    m_buttons_sizer->Remove(n);
    btn->Reparent(nullptr);
    btn->Destroy();
    m_sizer->Layout();
}
References m_buttons_sizer, m_pageButtons, m_sizer, and n.
Referenced by Tabbook::DoRemovePage().
Rescale()
void TabButtonsListCtrl::Rescale ()
{
    m_arrow_img = ScalableBitmap(this, "monitor_arrow", 14);
    int em = em_unit(this);
    for (TabButton *btn : m_pageButtons) {
        btn->SetMinSize({BUTTON_DEF_WIDTH * em / 10, BUTTON_DEF_HEIGHT * em / 10});
        btn->SetBitmap(m_arrow_img);
        btn->Rescale();
    }
    m_sizer->Layout();
}
References BUTTON_DEF_HEIGHT, BUTTON_DEF_WIDTH, em_unit(), m_arrow_img, m_pageButtons, and m_sizer.
Referenced by Tabbook::Rescale().
SetPageImage()
bool TabButtonsListCtrl::SetPageImage (size_t n, const std::string & bmp_name) const
{
    if (n >= m_pageButtons.size())
        return false;
    ScalableBitmap bitmap(NULL, bmp_name);
    return true;
}
References m_pageButtons, n, and NULL.
Referenced by Tabbook::SetPageImage().
SetPageText()
void TabButtonsListCtrl::SetPageText (size_t n, const wxString & strText)
{
    TabButton *btn = m_pageButtons[n];
    btn->SetLabel(strText);
}
References m_pageButtons, n, and TabButton::SetLabel().
Referenced by Tabbook::SetPageText().
SetSelection()
void TabButtonsListCtrl::SetSelection (int sel)
{
    if (m_selection == sel)
        return;
    if (m_selection >= 0) {
        m_pageButtons[m_selection]->SetBackgroundColor(TAB_BUTTON_BG);
        m_pageButtons[m_selection]->SetFont(TAB_BUTTON_FONT);
    }
    m_selection = sel;
    m_pageButtons[m_selection]->SetBackgroundColor(TAB_BUTTON_SEL);
    m_pageButtons[m_selection]->SetFont(TAB_BUTTON_FONT_SEL);
    Refresh();
}
References m_pageButtons, m_selection, TAB_BUTTON_BG, TAB_BUTTON_FONT, TAB_BUTTON_FONT_SEL, and TAB_BUTTON_SEL.
Referenced by Tabbook::ChangeSelection(), InsertPage(), and Tabbook::SetSelection().
Member Data Documentation
m_arrow_img
ScalableBitmap TabButtonsListCtrl::m_arrow_img private
Referenced by TabButtonsListCtrl(), InsertPage(), and Rescale().
m_btn_margin
int TabButtonsListCtrl::m_btn_margin private
Referenced by TabButtonsListCtrl().
m_buttons_sizer
wxFlexGridSizer* TabButtonsListCtrl::m_buttons_sizer private
Referenced by TabButtonsListCtrl(), InsertPage(), and RemovePage().
m_line_margin
int TabButtonsListCtrl::m_line_margin private
Referenced by TabButtonsListCtrl(), and OnPaint().
m_pageButtons
std::vector<TabButton*> TabButtonsListCtrl::m_pageButtons private
Referenced by GetPageText(), InsertPage(), OnPaint(), RemovePage(), Rescale(), SetPageImage(), SetPageText(), and SetSelection().
m_parent
wxWindow* TabButtonsListCtrl::m_parent private
m_selection
int TabButtonsListCtrl::m_selection {-1} private
Referenced by OnPaint(), and SetSelection().
m_sizer
wxBoxSizer* TabButtonsListCtrl::m_sizer private
Referenced by TabButtonsListCtrl(), InsertPage(), RemovePage(), and Rescale().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Tabbook.hpp
src/slic3r/GUI/Tabbook.cpp