OrcaSlicer: Slic3r::GUI::AssembleView Class Reference
Slic3r::GUI::AssembleView Class Reference
#include <src/slic3r/GUI/GUI_Preview.hpp>
Public Member Functions
AssembleView (wxWindow *parent, Bed3D &bed, Model *model, DynamicPrintConfig *config, BackgroundSlicingProcess *process)
~AssembleView ()
wxGLCanvas * get_wxglcanvas ()
GLCanvas3D * get_canvas3d ()
void set_as_dirty ()
void render ()
bool is_reload_delayed () const
void reload_scene (bool refresh_immediately, bool force_full_scene_refresh=false)
void select_view (const std::string &direction)
Private Member Functions
bool init (wxWindow *parent, Bed3D &bed, Model *model, DynamicPrintConfig *config, BackgroundSlicingProcess *process)
Private Attributes
wxGLCanvas * m_canvas_widget { nullptr }
GLCanvas3D * m_canvas { nullptr }
Detailed Description
Constructor & Destructor Documentation
AssembleView()
Slic3r::GUI::AssembleView::AssembleView (wxWindow * parent, Bed3D & bed, Model * model, DynamicPrintConfig * config, BackgroundSlicingProcess * process)
    : m_canvas_widget(nullptr)
    , m_canvas(nullptr)
{
    init(parent, bed, model, config, process);
}
References init().
~AssembleView()
Slic3r::GUI::AssembleView::~AssembleView ()
{
    delete m_canvas;
    delete m_canvas_widget;
}
References m_canvas, and m_canvas_widget.
Member Function Documentation
get_canvas3d()
GLCanvas3D * Slic3r::GUI::AssembleView::get_canvas3d () inline
{ return m_canvas; }
References m_canvas.
get_wxglcanvas()
wxGLCanvas * Slic3r::GUI::AssembleView::get_wxglcanvas () inline
{ return m_canvas_widget; }
References m_canvas_widget.
init()
bool Slic3r::GUI::AssembleView::init (wxWindow * parent, Bed3D & bed, Model * model, DynamicPrintConfig * config, BackgroundSlicingProcess * process) private
{
    if (!Create(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize, 0 /* disable wxTAB_TRAVERSAL */))
        return false;
    m_canvas_widget = OpenGLManager::create_wxglcanvas(*this);
    if (m_canvas_widget == nullptr)
        return false;
    m_canvas = new GLCanvas3D(m_canvas_widget, bed);
    m_canvas->set_context(wxGetApp().init_glcontext(*m_canvas_widget));
    m_canvas->allow_multisample(OpenGLManager::can_multisample());
    // XXX: If have OpenGL
    m_canvas->enable_picking(true);
    m_canvas->enable_moving(true);
    // XXX: more config from 3D.pm
    m_canvas->set_model(model);
    m_canvas->set_process(process);
    m_canvas->set_type(GLCanvas3D::ECanvasType::CanvasAssembleView);
    m_canvas->set_config(config);
    m_canvas->enable_gizmos(true);
    m_canvas->enable_selection(true);
    m_canvas->enable_main_toolbar(false);
    m_canvas->enable_labels(false);
    m_canvas->enable_slope(false);
    //BBS: GUI refactor: GLToolbar
    m_canvas->enable_assemble_view_toolbar(false);
    m_canvas->enable_return_toolbar(true);
    m_canvas->enable_separator_toolbar(false);
    // BBS: set volume_selection_mode to Volume
    m_canvas->get_selection().set_volume_selection_mode(Selection::Volume);
    m_canvas->get_selection().lock_volume_selection_mode();
    wxBoxSizer* main_sizer = new wxBoxSizer(wxVERTICAL);
    main_sizer->Add(m_canvas_widget, 1, wxALL | wxEXPAND, 0);
    SetSizer(main_sizer);
    SetMinSize(GetSize());
    GetSizer()->SetSizeHints(this);
    return true;
}
References Slic3r::GUI::GLCanvas3D::allow_multisample(), Slic3r::GUI::OpenGLManager::can_multisample(), Slic3r::GUI::GLCanvas3D::CanvasAssembleView, Slic3r::GUI::OpenGLManager::create_wxglcanvas(), Slic3r::GUI::GLCanvas3D::enable_assemble_view_toolbar(), Slic3r::GUI::GLCanvas3D::enable_gizmos(), Slic3r::GUI::GLCanvas3D::enable_labels(), Slic3r::GUI::GLCanvas3D::enable_main_toolbar(), Slic3r::GUI::GLCanvas3D::enable_moving(), Slic3r::GUI::GLCanvas3D::enable_picking(), Slic3r::GUI::GLCanvas3D::enable_return_toolbar(), Slic3r::GUI::GLCanvas3D::enable_selection(), Slic3r::GUI::GLCanvas3D::enable_separator_toolbar(), Slic3r::GUI::GLCanvas3D::enable_slope(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::lock_volume_selection_mode(), m_canvas, m_canvas_widget, Slic3r::GUI::GLCanvas3D::set_config(), Slic3r::GUI::GLCanvas3D::set_context(), Slic3r::GUI::GLCanvas3D::set_model(), Slic3r::GUI::GLCanvas3D::set_process(), Slic3r::GUI::GLCanvas3D::set_type(), Slic3r::GUI::Selection::set_volume_selection_mode(), and Slic3r::GUI::Selection::Volume.
Referenced by AssembleView().
is_reload_delayed()
bool Slic3r::GUI::AssembleView::is_reload_delayed () const
{
    return (m_canvas != nullptr) ? m_canvas->is_reload_delayed() : false;
}
References Slic3r::GUI::GLCanvas3D::is_reload_delayed(), and m_canvas.
reload_scene()
void Slic3r::GUI::AssembleView::reload_scene (bool refresh_immediately, bool force_full_scene_refresh = false)
{
    if (m_canvas != nullptr) {
        if (!m_canvas->is_initialized()) {
            m_canvas->render(true);
        }
        m_canvas->reload_scene(refresh_immediately, force_full_scene_refresh);
    }
}
References Slic3r::GUI::GLCanvas3D::is_initialized(), m_canvas, Slic3r::GUI::GLCanvas3D::reload_scene(), and Slic3r::GUI::GLCanvas3D::render().
render()
void Slic3r::GUI::AssembleView::render ()
{
    if (m_canvas != nullptr)
        m_canvas->set_as_dirty();
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::set_as_dirty().
select_view()
void Slic3r::GUI::AssembleView::select_view (const std::string & direction)
{
    if (m_canvas != nullptr)
        m_canvas->select_view(direction);
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::select_view().
set_as_dirty()
void Slic3r::GUI::AssembleView::set_as_dirty ()
{
    if (m_canvas != nullptr)
        m_canvas->set_as_dirty();
}
References m_canvas, and Slic3r::GUI::GLCanvas3D::set_as_dirty().
Member Data Documentation
m_canvas
GLCanvas3D* Slic3r::GUI::AssembleView::m_canvas { nullptr } private
Referenced by ~AssembleView(), get_canvas3d(), init(), is_reload_delayed(), reload_scene(), render(), select_view(), and set_as_dirty().
m_canvas_widget
wxGLCanvas* Slic3r::GUI::AssembleView::m_canvas_widget { nullptr } private
Referenced by ~AssembleView(), get_wxglcanvas(), and init().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_Preview.hpp
src/slic3r/GUI/GUI_Preview.cpp