OrcaSlicer: orgQhull::QhullFacet Class Reference
orgQhull::QhullFacet Class Reference
A QhullFacet is the C++ equivalent to Qhull's facetT*.
#include <src/qhull/src/libqhullcpp/QhullFacet.h>
Classes
struct PrintCenter
struct PrintFacet
struct PrintFlags
struct PrintHeader
struct PrintRidges
Public Types
Defined here
typedef facetT * base_type
Public Member Functions
Constructors
QhullFacet ()
QhullFacet (const Qhull &q)
QhullFacet (const Qhull &q, facetT *f)
QhullFacet (QhullQh *qqh)
QhullFacet (QhullQh *qqh, facetT *f)
QhullFacet (const QhullFacet &other)
QhullFacet & operator= (const QhullFacet &other)
~QhullFacet ()
GetSet
int dimension () const
QhullPoint getCenter ()
QhullPoint getCenter (qh_PRINT printFormat)
Return voronoi center or facet centrum. Derived from qh_printcenter [io_r.c] if printFormat=qh_PRINTtriangles and qh.DELAUNAY, returns centrum of a Delaunay facet Sets center if needed Code duplicated for PrintCenter and getCenter Returns QhullPoint() if none or qh_INFINITE.
facetT * getBaseT () const
For QhullSet<QhullFacet>
facetT * getFacetT () const
QhullHyperplane hyperplane () const
countT id () const
QhullHyperplane innerplane () const
Return innerplane clearly below the vertices from io_r.c[qh_PRINTinner].
bool isValid () const
bool isGood () const
bool isSimplicial () const
bool isTopOrient () const
bool isTriCoplanar () const
bool isUpperDelaunay () const
QhullFacet next () const
bool operator== (const QhullFacet &other) const
bool operator!= (const QhullFacet &other) const
QhullHyperplane outerplane () const
Return outerplane clearly above all points from io_r.c[qh_PRINTouter].
QhullFacet previous () const
QhullQh * qh () const
QhullFacet tricoplanarOwner () const
Set by qh_triangulate for option 'Qt'. Errors if tricoplanar and facetArea() or qh_getarea() called first.
QhullPoint voronoiVertex ()
value
Undefined if c.size() != dimension()
double distance (const Coordinates &c) const
double distance (const pointT *p) const
double distance (const QhullPoint &p) const
double facetArea ()
Disables tricoplanarOwner()
foreach
QhullPointSet coplanarPoints () const
QhullFacetSet neighborFacets () const
QhullPointSet outsidePoints () const
QhullRidgeSet ridges () const
QhullVertexSet vertices () const
IO
PrintCenter printCenter (qh_PRINT printFormat, const char *message)
PrintFacet print (const char *message)
PrintFlags printFlags (const char *message) const
PrintHeader printHeader ()
PrintRidges printRidges ()
Private Attributes
Fields – no additions (QhullFacetSet of facetT*)
facetT * qh_facet
Corresponding facetT, may be 0 for corner cases (e.g., *facetSet.end()==0) and tricoplanarOwner()
QhullQh * qh_qh
QhullQh/qhT for facetT, may be 0.
Static Private Attributes
Class objects
static facetT s_empty_facet
Detailed Description
A QhullFacet is the C++ equivalent to Qhull's facetT*.
Member Typedef Documentation
base_type
typedef facetT* orgQhull::QhullFacet::base_type
Constructor & Destructor Documentation
QhullFacet() [1/6]
orgQhull::QhullFacet::QhullFacet () inline
: qh_facet(&s_empty_facet), qh_qh(0) {}
Referenced by next(), previous(), and tricoplanarOwner().
QhullFacet() [2/6]
orgQhull::QhullFacet::QhullFacet (const Qhull & q) explicit
: qh_facet(&s_empty_facet)
, qh_qh(q.qh())
{
}
QhullFacet() [3/6]
orgQhull::QhullFacet::QhullFacet (const Qhull & q, facetT * f)
: qh_facet(f ? f : &s_empty_facet)
, qh_qh(q.qh())
{
}
QhullFacet() [4/6]
orgQhull::QhullFacet::QhullFacet (QhullQh * qqh) inline explicit
: qh_facet(&s_empty_facet), qh_qh(qqh) {}
QhullFacet() [5/6]
orgQhull::QhullFacet::QhullFacet (QhullQh * qqh, facetT * f) inline
: qh_facet(f ? f : &s_empty_facet), qh_qh(qqh) {}
QhullFacet() [6/6]
orgQhull::QhullFacet::QhullFacet (const QhullFacet & other) inline
: qh_facet(other.qh_facet ? other.qh_facet : &s_empty_facet), qh_qh(other.qh_qh) {}
~QhullFacet()
orgQhull::QhullFacet::~QhullFacet () inline
{}
Member Function Documentation
coplanarPoints()
QhullPointSet orgQhull::QhullFacet::coplanarPoints () const
{
    return QhullPointSet(qh_qh, qh_facet->coplanarset);
}//coplanarPoints
References facetT::coplanarset, qh_facet, and qh_qh.
Referenced by operator<<(), orgQhull::QhullPointSet_test::t_const_iterator(), orgQhull::QhullPointSet_test::t_convert(), orgQhull::QhullPointSet_test::t_element(), orgQhull::QhullFacet_test::t_foreach(), orgQhull::QhullPointSet_test::t_io(), orgQhull::QhullPointSet_test::t_iterator(), orgQhull::QhullPointSet_test::t_pointset_iterator(), and orgQhull::QhullPointSet_test::t_search().
dimension()
int orgQhull::QhullFacet::dimension () const inline
{ return (qh_qh ? qh_qh->hull_dim : 0); }
References qhT::hull_dim, and qh_qh.
Referenced by hyperplane(), operator<<(), orgQhull::QhullFacet_test::t_construct_qh(), orgQhull::QhullFacet_test::t_constructConvert(), and orgQhull::QhullFacet_test::t_getSet().
distance() [1/3]
double orgQhull::QhullFacet::distance (const Coordinates & c) const inline
{ return distance(c.data()); }
References distance().
Referenced by distance(), operator<<(), orgQhull::QhullFacet_test::t_getSet(), and orgQhull::QhullFacet_test::t_value().
distance() [2/3]
double orgQhull::QhullFacet::distance (const pointT * p) const inline
{ return distance(QhullPoint(qh_qh, const_cast<coordT *>(p))); }
References coordT, distance(), and qh_qh.
Referenced by distance().
distance() [3/3]
double orgQhull::QhullFacet::distance (const QhullPoint & p) const inline
{ return hyperplane().distance(p); }
References orgQhull::QhullHyperplane::distance(), and hyperplane().
facetArea()
double orgQhull::QhullFacet::facetArea ()
Disables tricoplanarOwner()
{
    if(qh_qh && !qh_facet->isarea){
        QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
            qh_facet->f.area= qh_facetarea(qh_qh, qh_facet);
            qh_facet->isarea= True;
        }
        qh_qh->NOerrexit= true;
        qh_qh->maybeThrowQhullMessage(QH_TRY_status);
    }
    return qh_facet->f.area;
}//facetArea
References facetT::f, facetT::isarea, orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, qh_facet, qh_facetarea(), qh_qh, QH_TRY_, and True.
Referenced by orgQhull::QhullFacet_test::t_value().
getBaseT()
facetT * orgQhull::QhullFacet::getBaseT () const inline
For QhullSet<QhullFacet>
References getFacetT().
Referenced by orgQhull::QhullFacet_test::t_constructConvert().
getCenter() [1/2]
QhullPoint orgQhull::QhullFacet::getCenter () inline
{ return getCenter(qh_PRINTpoints); }
References getCenter(), and qh_PRINTpoints.
Referenced by getCenter(), orgQhull::QhullFacet_test::t_getSet(), and voronoiVertex().
getCenter() [2/2]
QhullPoint orgQhull::QhullFacet::getCenter (qh_PRINT printFormat)
Return voronoi center or facet centrum. Derived from qh_printcenter [io_r.c] if printFormat=qh_PRINTtriangles and qh.DELAUNAY, returns centrum of a Delaunay facet Sets center if needed Code duplicated for PrintCenter and getCenter Returns QhullPoint() if none or qh_INFINITE.
{
    if(!qh_qh){
        // returns QhullPoint()
    }else if(qh_qh->CENTERtype==qh_ASvoronoi){
        if(!qh_facet->normal || !qh_facet->upperdelaunay || !qh_qh->ATinfinity){
            if(!qh_facet->center){
                QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
                    qh_facet->center= qh_facetcenter(qh_qh, qh_facet->vertices);
                }
                qh_qh->NOerrexit= true;
                qh_qh->maybeThrowQhullMessage(QH_TRY_status);
            }
            return QhullPoint(qh_qh, qh_qh->hull_dim-1, qh_facet->center);
        }
    }else if(qh_qh->CENTERtype==qh_AScentrum){
        volatile int numCoords= qh_qh->hull_dim;
        if(printFormat==qh_PRINTtriangles && qh_qh->DELAUNAY){
            numCoords--;
        }
        if(!qh_facet->center){
            QH_TRY_(qh_qh){ // no object creation -- destructors skipped on longjmp()
                qh_facet->center= qh_getcentrum(qh_qh, getFacetT());
            }
            qh_qh->NOerrexit= true;
            qh_qh->maybeThrowQhullMessage(QH_TRY_status);
        }
        return QhullPoint(qh_qh, numCoords, qh_facet->center);
    }
    return QhullPoint();
 }//getCenter
References qhT::ATinfinity, facetT::center, qhT::CENTERtype, qhT::DELAUNAY, getFacetT(), qhT::hull_dim, orgQhull::QhullQh::maybeThrowQhullMessage(), qhT::NOerrexit, facetT::normal, qh_AScentrum, qh_ASvoronoi, qh_facet, qh_facetcenter(), qh_getcentrum(), qh_PRINTtriangles, qh_qh, QH_TRY_, facetT::upperdelaunay, and facetT::vertices.
getFacetT()
facetT * orgQhull::QhullFacet::getFacetT () const inline
{ return qh_facet; }
References qh_facet.
Referenced by getBaseT(), getCenter(), orgQhull::QhullRidge::hasNextRidge3d(), innerplane(), orgQhull::QhullRidge::nextRidge3d(), operator<<(), operator<<(), operator<<(), operator<<(), orgQhull::QhullRidge::otherFacet(), outerplane(), orgQhull::QhullPointSet_test::t_construct(), orgQhull::QhullFacet_test::t_constructConvert(), and orgQhull::QhullFacet_test::t_value().
hyperplane()
QhullHyperplane orgQhull::QhullFacet::hyperplane () const inline
{ return QhullHyperplane(qh_qh, dimension(), qh_facet->normal, qh_facet->offset); }
References dimension(), facetT::normal, facetT::offset, qh_facet, and qh_qh.
Referenced by distance(), innerplane(), operator<<(), outerplane(), orgQhull::QhullHyperplane_test::t_const_iterator(), orgQhull::QhullHyperplane_test::t_construct(), orgQhull::QhullHyperplane_test::t_construct_qh(), orgQhull::QhullHyperplane_test::t_convert(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullHyperplane_test::t_io(), orgQhull::QhullHyperplane_test::t_iterator(), orgQhull::QhullHyperplane_test::t_operator(), orgQhull::QhullHyperplane_test::t_qhullHyperplane_iterator(), orgQhull::QhullHyperplane_test::t_readonly(), and orgQhull::QhullHyperplane_test::t_value().
id()
countT orgQhull::QhullFacet::id () const inline
{ return (qh_facet ? qh_facet->id : (int)qh_IDunknown); }
References facetT::id, int, qh_facet, and qh_IDunknown.
Referenced by orgQhull::QhullRidge::nextRidge3d(), operator<<(), operator<<(), operator<<(), operator<<(), orgQhull::QhullSet_test::t_const_iterator(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullSet_test::t_iterator(), and orgQhull::QhullHyperplane_test::t_readonly().
innerplane()
QhullHyperplane orgQhull::QhullFacet::innerplane () const
Return innerplane clearly below the vertices from io_r.c[qh_PRINTinner].
                  {
    QhullHyperplane h;
    if(qh_qh){
        realT inner;
        // Does not error, TRY_QHULL_ not needed
        qh_outerinner(qh_qh, const_cast<facetT *>(getFacetT()), NULL, &inner);
        h= hyperplane();
        h.setOffset(h.offset()-inner); //inner is negative
    }
    return h;
}//innerplane
References getFacetT(), hyperplane(), NULL, orgQhull::QhullHyperplane::offset(), qh_outerinner(), qh_qh, realT, and orgQhull::QhullHyperplane::setOffset().
Referenced by orgQhull::QhullFacet_test::t_getSet().
isGood()
bool orgQhull::QhullFacet::isGood () const inline
{ return qh_facet && qh_facet->good; }
References facetT::good, and qh_facet.
Referenced by orgQhull::QhullFacetList::contains(), orgQhull::QhullFacetSet::contains(), orgQhull::QhullFacetSet::count(), orgQhull::QhullFacetList::count(), orgQhull::QhullFacetSet::count(), operator<<(), operator<<(), operator<<(), orgQhull::QhullFacet_test::t_getSet(), orgQhull::QhullFacetList_test::t_readonly(), orgQhull::QhullFacetSet_test::t_readonly(), orgQhull::QhullFacetList::toStdVector(), and orgQhull::QhullFacetSet::toStdVector().
isSimplicial()
bool orgQhull::QhullFacet::isSimplicial () const inline
{ return qh_facet && qh_facet->simplicial; }
References qh_facet, and facetT::simplicial.
isTopOrient()
bool orgQhull::QhullFacet::isTopOrient () const inline
{ return qh_facet && qh_facet->toporient; }
References qh_facet, and facetT::toporient.
isTriCoplanar()
bool orgQhull::QhullFacet::isTriCoplanar () const inline
{ return qh_facet && qh_facet->tricoplanar; }
References qh_facet, and facetT::tricoplanar.
isUpperDelaunay()
bool orgQhull::QhullFacet::isUpperDelaunay () const inline
{ return qh_facet && qh_facet->upperdelaunay; }
References qh_facet, and facetT::upperdelaunay.
isValid()
bool orgQhull::QhullFacet::isValid () const inline
{ return qh_qh && qh_facet && qh_facet != &s_empty_facet; }
References qh_facet, qh_qh, and s_empty_facet.
Referenced by orgQhull::QhullFacet_test::t_construct_qh(), orgQhull::QhullFacet_test::t_constructConvert(), orgQhull::QhullSet_test::t_element(), and orgQhull::QhullFacet_test::t_getSet().
neighborFacets()
QhullFacetSet orgQhull::QhullFacet::neighborFacets () const
{
    return QhullFacetSet(qh_qh, qh_facet->neighbors);
}//neighborFacets
References facetT::neighbors, qh_facet, and qh_qh.
Referenced by operator<<(), operator<<(), orgQhull::QhullSet_test::t_const_iterator(), orgQhull::QhullFacetSet_test::t_construct(), orgQhull::QhullFacetSet_test::t_convert(), orgQhull::QhullSet_test::t_convert(), orgQhull::QhullSet_test::t_element(), orgQhull::QhullFacet_test::t_foreach(), orgQhull::QhullFacetSet_test::t_foreach(), orgQhull::QhullFacetSet_test::t_io(), orgQhull::QhullSet_test::t_io(), orgQhull::QhullSet_test::t_iterator(), orgQhull::QhullSet_test::t_qhullset_iterator(), orgQhull::QhullSet_test::t_qhullsetbase(), orgQhull::QhullFacetSet_test::t_readonly(), orgQhull::QhullSet_test::t_search(), and orgQhull::QhullHyperplane_test::t_value().
next()
QhullFacet orgQhull::QhullFacet::next () const inline
{ return QhullFacet(qh_qh, qh_facet->next); }
References QhullFacet(), facetT::next, qh_facet, and qh_qh.
Referenced by operator<<(), orgQhull::QhullSet_test::t_convert(), orgQhull::QhullFacetList_test::t_foreach(), orgQhull::QhullFacetSet_test::t_foreach(), and orgQhull::QhullFacet_test::t_getSet().
operator!=()
bool orgQhull::QhullFacet::operator!= (const QhullFacet & other) const inline
{ return !operator==(other); }
References operator==().
operator=()
QhullFacet & orgQhull::QhullFacet::operator= (const QhullFacet & other) inline
{ qh_facet= other.qh_facet ? other.qh_facet : &s_empty_facet; qh_qh= other.qh_qh; return *this; }
References qh_facet, qh_qh, and s_empty_facet.
operator==()
bool orgQhull::QhullFacet::operator== (const QhullFacet & other) const inline
{ return qh_facet==other.qh_facet; }
References qh_facet.
Referenced by operator!=().
outerplane()
QhullHyperplane orgQhull::QhullFacet::outerplane () const
Return outerplane clearly above all points from io_r.c[qh_PRINTouter].
                  {
    QhullHyperplane h;
    if(qh_qh){
        realT outer;
        // Does not error, TRY_QHULL_ not needed
        qh_outerinner(qh_qh, const_cast<facetT *>(getFacetT()), &outer, NULL);
        h= hyperplane();
        h.setOffset(h.offset()-outer); //outer is positive
    }
    return h;
}//outerplane
References getFacetT(), hyperplane(), NULL, orgQhull::QhullHyperplane::offset(), qh_outerinner(), qh_qh, realT, and orgQhull::QhullHyperplane::setOffset().
Referenced by orgQhull::QhullFacet_test::t_getSet().
outsidePoints()
QhullPointSet orgQhull::QhullFacet::outsidePoints () const
{
    return QhullPointSet(qh_qh, qh_facet->outsideset);
}//outsidePoints
References facetT::outsideset, qh_facet, and qh_qh.
Referenced by operator<<(), orgQhull::QhullFacet_test::t_foreach(), and orgQhull::QhullPointSet_test::t_pointset_iterator().
previous()
QhullFacet orgQhull::QhullFacet::previous () const inline
{ return QhullFacet(qh_qh, qh_facet->previous); }
References QhullFacet(), facetT::previous, qh_facet, and qh_qh.
Referenced by orgQhull::QhullFacetList_test::t_construct_q(), and orgQhull::QhullFacetList_test::t_construct_qh().
print()
PrintFacet orgQhull::QhullFacet::print (const char * message) inline
{ return PrintFacet(*this, message); }
Referenced by operator<<(), operator<<(), and orgQhull::QhullFacet_test::t_io().
printCenter()
PrintCenter orgQhull::QhullFacet::printCenter (qh_PRINT printFormat, const char * message) inline
{ return PrintCenter(*this, printFormat, message); }
Referenced by operator<<(), and orgQhull::QhullFacet_test::t_io().
printFlags()
PrintFlags orgQhull::QhullFacet::printFlags (const char * message) const inline
{ return PrintFlags(*this, message); }
Referenced by operator<<(), and orgQhull::QhullFacet_test::t_io().
printHeader()
PrintHeader orgQhull::QhullFacet::printHeader () inline
{ return PrintHeader(*this); }
Referenced by operator<<(), and orgQhull::QhullFacet_test::t_io().
printRidges()
PrintRidges orgQhull::QhullFacet::printRidges () inline
{ return PrintRidges(*this); }
Referenced by operator<<(), and orgQhull::QhullFacet_test::t_io().
qh()
QhullQh * orgQhull::QhullFacet::qh () const inline
{ return qh_qh; }
References qh_qh.
Referenced by orgQhull::QhullFacetList::qh().
ridges()
QhullRidgeSet orgQhull::QhullFacet::ridges () const
{
    return QhullRidgeSet(qh_qh, qh_facet->ridges);
}//ridges
References qh_facet, qh_qh, and facetT::ridges.
Referenced by operator<<(), operator<<(), orgQhull::QhullRidge_test::t_construct(), orgQhull::QhullSet_test::t_convert(), orgQhull::QhullFacet_test::t_foreach(), orgQhull::QhullRidge_test::t_foreach(), orgQhull::QhullRidge_test::t_getSet(), orgQhull::QhullRidge_test::t_io(), orgQhull::QhullSet_test::t_io(), and orgQhull::QhullSet_test::t_qhullsetbase().
tricoplanarOwner()
QhullFacet orgQhull::QhullFacet::tricoplanarOwner () const
Set by qh_triangulate for option 'Qt'. Errors if tricoplanar and facetArea() or qh_getarea() called first.
{
    if(qh_facet->tricoplanar){
        if(qh_facet->isarea){
            throw QhullError(10018, "Qhull error: facetArea() or qh_getarea() previously called.  triCoplanarOwner() is not available.");
        }
        return QhullFacet(qh_qh, qh_facet->f.triowner);
    }
    return QhullFacet(qh_qh);
}//tricoplanarOwner
References QhullFacet(), facetT::f, facetT::isarea, qh_facet, qh_qh, and facetT::tricoplanar.
Referenced by orgQhull::QhullFacet_test::t_getSet().
vertices()
QhullVertexSet orgQhull::QhullFacet::vertices () const
{
    return QhullVertexSet(qh_qh, qh_facet->vertices);
}//vertices
References qh_facet, qh_qh, and facetT::vertices.
Referenced by operator<<(), orgQhull::QhullVertexSet_test::t_construct(), orgQhull::QhullVertexSet_test::t_convert(), orgQhull::QhullFacet_test::t_foreach(), orgQhull::QhullRidge_test::t_foreach(), orgQhull::QhullVertex_test::t_foreach(), orgQhull::QhullVertexSet_test::t_foreach(), orgQhull::QhullVertex_test::t_io(), orgQhull::QhullVertexSet_test::t_io(), and orgQhull::QhullVertexSet_test::t_readonly().
voronoiVertex()
QhullPoint orgQhull::QhullFacet::voronoiVertex ()
{
    if(qh_qh && qh_qh->CENTERtype!=qh_ASvoronoi){
          throw QhullError(10052, "Error: QhullFacet.voronoiVertex() requires option 'v' (qh_ASvoronoi)");
    }
    return getCenter();
}//voronoiVertex
References qhT::CENTERtype, getCenter(), qh_ASvoronoi, and qh_qh.
Referenced by orgQhull::QhullFacet_test::t_getSet().
Member Data Documentation
qh_facet
facetT* orgQhull::QhullFacet::qh_facet private
Corresponding facetT, may be 0 for corner cases (e.g., *facetSet.end()==0) and tricoplanarOwner()
Referenced by coplanarPoints(), facetArea(), getCenter(), getFacetT(), hyperplane(), id(), isGood(), isSimplicial(), isTopOrient(), isTriCoplanar(), isUpperDelaunay(), isValid(), neighborFacets(), next(), operator=(), operator==(), outsidePoints(), previous(), ridges(), tricoplanarOwner(), and vertices().
qh_qh
QhullQh* orgQhull::QhullFacet::qh_qh private
QhullQh/qhT for facetT, may be 0.
Referenced by coplanarPoints(), dimension(), distance(), facetArea(), getCenter(), hyperplane(), innerplane(), isValid(), neighborFacets(), next(), operator=(), outerplane(), outsidePoints(), previous(), qh(), ridges(), tricoplanarOwner(), vertices(), and voronoiVertex().
s_empty_facet
facetT orgQhull::QhullFacet::s_empty_facet static private
Initial value:
= {0,0,0,0,{0},
        0,0,0,0,0,
        0,0,0,0,0,
        0,0,0,0,0,
        0,0,0,0,0,
        0,0,0,0,0,
        0,0,0,0,0,
        0,0,0,0}
Referenced by isValid(), and operator=().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullFacet.h
src/qhull/src/libqhullcpp/QhullFacet.cpp