OrcaSlicer: Slic3r::LayerRanges Class Reference
Slic3r::LayerRanges Class Reference
Classes
struct LayerRange
Public Member Functions
LayerRanges ()=default
LayerRanges (const t_layer_config_ranges &in)
void assign (const t_layer_config_ranges &in)
const DynamicPrintConfig * config (const t_layer_height_range &range) const
std::vector< LayerRange >::const_iterator begin () const
std::vector< LayerRange >::const_iterator end () const
size_t size () const
Private Attributes
std::vector< LayerRange > m_ranges
Detailed Description
Constructor & Destructor Documentation
LayerRanges() [1/2]
Slic3r::LayerRanges::LayerRanges () default
LayerRanges() [2/2]
Slic3r::LayerRanges::LayerRanges (const t_layer_config_ranges & in) inline
{ this->assign(in); }
References assign().
Member Function Documentation
assign()
void Slic3r::LayerRanges::assign (const t_layer_config_ranges & in) inline
{
        m_ranges.clear();
        m_ranges.reserve(in.size());
        // Input ranges are sorted lexicographically. First range trims the other ranges.
        coordf_t last_z = 0;
        for (const std::pair<const t_layer_height_range, ModelConfig> &range : in)
            if (range.first.second > last_z) {
                coordf_t min_z = std::max(range.first.first, 0.);
                if (min_z > last_z + EPSILON) {
                    m_ranges.push_back({ t_layer_height_range(last_z, min_z) });
                    last_z = min_z;
                }
                if (range.first.second > last_z + EPSILON) {
                    const DynamicPrintConfig *cfg = &range.second.get();
                    m_ranges.push_back({ t_layer_height_range(last_z, range.first.second), cfg });
                    last_z = range.first.second;
                }
            }
        if (m_ranges.empty())
            m_ranges.push_back({ t_layer_height_range(0, DBL_MAX) });
        else if (m_ranges.back().config == nullptr)
            m_ranges.back().layer_height_range.second = DBL_MAX;
        else
            m_ranges.push_back({ t_layer_height_range(m_ranges.back().layer_height_range.second, DBL_MAX) });
    }
References EPSILON, in, m_ranges, and Slic3r::range().
Referenced by LayerRanges().
begin()
std::vector< LayerRange >::const_iterator Slic3r::LayerRanges::begin () const inline
{ return m_ranges.cbegin(); }
Referenced by Slic3r::generate_print_object_regions().
config()
const DynamicPrintConfig * Slic3r::LayerRanges::config (const t_layer_height_range & range) const inline
{
        auto it = std::lower_bound(m_ranges.begin(), m_ranges.end(), LayerRange{ { range.first - EPSILON, range.second - EPSILON } });
        // #ys_FIXME_COLOR
        // assert(it != m_ranges.end());
        // assert(it == m_ranges.end() || std::abs(it->first.first  - range.first ) < EPSILON);
        // assert(it == m_ranges.end() || std::abs(it->first.second - range.second) < EPSILON);
        if (it == m_ranges.end() ||
            std::abs(it->layer_height_range.first - range.first) > EPSILON ||
            std::abs(it->layer_height_range.second - range.second) > EPSILON )
            return nullptr; // desired range doesn't found
        return it == m_ranges.end() ? nullptr : it->config;
    }
end()
std::vector< LayerRange >::const_iterator Slic3r::LayerRanges::end () const inline
{ return m_ranges.cend(); }
size()
size_t Slic3r::LayerRanges::size () const inline
{ return m_ranges.size(); }
Referenced by Slic3r::generate_print_object_regions().
Member Data Documentation
m_ranges
std::vector<LayerRange> Slic3r::LayerRanges::m_ranges private
Referenced by assign().
The documentation for this class was generated from the following file:
src/libslic3r/PrintApply.cpp