OrcaSlicer: Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper Class Reference
Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp>
Public Member Functions
ModelObjectsClipper (AssembleViewDataPool *cgdp)
AssembleViewDataID get_dependencies () const override
void set_position (double pos, bool keep_normal)
double get_position () const
ClippingPlane * get_clipping_plane () const
void render_cut () const
void update ()
void release ()
bool is_valid () const
Protected Member Functions
void on_update () override
void on_release () override
AssembleViewDataPool * get_pool () const
Private Attributes
std::vector< const TriangleMesh * > m_old_meshes
std::vector< std::unique_ptr< MeshClipper > > m_clippers
std::unique_ptr< ClippingPlane > m_clp
double m_clp_ratio = 0.
double m_active_inst_bb_radius = 0.
bool m_is_valid = false
AssembleViewDataPool * m_common = nullptr
Detailed Description
Constructor & Destructor Documentation
ModelObjectsClipper()
Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::ModelObjectsClipper (AssembleViewDataPool * cgdp) inline explicit
        : AssembleViewDataBase(cgdp) {}
Member Function Documentation
get_clipping_plane()
ClippingPlane * Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::get_clipping_plane () const inline
{ return m_clp.get(); }
References m_clp.
get_dependencies()
AssembleViewDataID Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::get_dependencies () const inline override virtual
Reimplemented from Slic3r::GUI::AssembleViewDataBase.
{ return AssembleViewDataID::ModelObjectsInfo; }
References Slic3r::GUI::ModelObjectsInfo.
get_pool()
AssembleViewDataPool * Slic3r::GUI::AssembleViewDataBase::get_pool () const inline protected inherited
{ return m_common; }
References Slic3r::GUI::AssembleViewDataBase::m_common.
Referenced by Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::on_update(), on_update(), render_cut(), and set_position().
get_position()
double Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::get_position () const inline
{ return m_clp_ratio; }
References m_clp_ratio.
is_valid()
bool Slic3r::GUI::AssembleViewDataBase::is_valid () const inline inherited
{ return m_is_valid; }
References Slic3r::GUI::AssembleViewDataBase::m_is_valid.
Referenced by Slic3r::GUI::AssembleViewDataPool::model_objects_clipper(), and Slic3r::GUI::AssembleViewDataPool::model_objects_info().
on_release()
void Slic3r::GUI::ModelObjectsClipper::on_release () override protected virtual
Implements Slic3r::GUI::AssembleViewDataBase.
{
    m_clippers.clear();
    m_old_meshes.clear();
    m_clp.reset();
    m_clp_ratio = 0.;
}
References m_clippers, m_clp, m_clp_ratio, and m_old_meshes.
on_update()
void Slic3r::GUI::ModelObjectsClipper::on_update () override protected virtual
Implements Slic3r::GUI::AssembleViewDataBase.
{
    const ModelObjectPtrs model_objects = get_pool()->model_objects_info()->model_objects();
    if (model_objects.empty())
        return;
    // which mesh should be cut?
    std::vector<const TriangleMesh*> meshes;
    if (meshes.empty())
        for (auto mo : model_objects) {
            for (const ModelVolume* mv : mo->volumes)
                meshes.push_back(&mv->mesh());
        }
    if (meshes != m_old_meshes) {
        m_clippers.clear();
        for (const TriangleMesh* mesh : meshes) {
            m_clippers.emplace_back(new MeshClipper);
            m_clippers.back()->set_mesh(*mesh);
        }
        m_old_meshes = meshes;
        m_active_inst_bb_radius = get_pool()->get_canvas()->volumes_bounding_box().radius();
    }
}
References Slic3r::GUI::AssembleViewDataPool::get_canvas(), Slic3r::GUI::AssembleViewDataBase::get_pool(), m_active_inst_bb_radius, m_clippers, m_old_meshes, Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::model_objects(), Slic3r::GUI::AssembleViewDataPool::model_objects_info(), Slic3r::BoundingBox3Base< PointClass >::radius(), and Slic3r::GUI::GLCanvas3D::volumes_bounding_box().
release()
void Slic3r::GUI::AssembleViewDataBase::release () inline inherited
{ on_release(); m_is_valid = false; }
References Slic3r::GUI::AssembleViewDataBase::m_is_valid, and Slic3r::GUI::AssembleViewDataBase::on_release().
render_cut()
void Slic3r::GUI::ModelObjectsClipper::render_cut () const
{
    if (m_clp_ratio == 0.)
        return;
    const ModelObjectPtrs model_objects = get_pool()->model_objects_info()->model_objects();
    size_t clipper_id = 0;
    for (const ModelObject* mo : model_objects) {
        Geometry::Transformation assemble_objects_trafo = mo->instances[0]->get_assemble_transformation();
        auto offset_to_assembly = mo->instances[0]->get_offset_to_assembly();
        for (const ModelVolume* mv : mo->volumes) {
            Geometry::Transformation vol_trafo = mv->get_transformation();
            Geometry::Transformation trafo = assemble_objects_trafo * vol_trafo;
            trafo.set_offset(trafo.get_offset() + vol_trafo.get_offset() * (GLVolume::explosion_ratio - 1.0) + offset_to_assembly * (GLVolume::explosion_ratio - 1.0));
            auto& clipper = m_clippers[clipper_id];
            clipper->set_plane(*m_clp);
            clipper->set_transformation(trafo);
            glsafe(::glPushMatrix());
            // BBS
            glsafe(::glColor3f(0.25f, 0.25f, 0.25f));
            clipper->render_cut();
            glsafe(::glPopMatrix());
            ++clipper_id;
        }
    }
}
References Slic3r::GLVolume::explosion_ratio, Slic3r::Geometry::Transformation::get_offset(), Slic3r::GUI::AssembleViewDataBase::get_pool(), glsafe, m_clippers, m_clp, m_clp_ratio, Slic3r::GUI::AssembleViewDataObjects::ModelObjectsInfo::model_objects(), Slic3r::GUI::AssembleViewDataPool::model_objects_info(), and Slic3r::Geometry::Transformation::set_offset().
set_position()
void Slic3r::GUI::ModelObjectsClipper::set_position (double pos, bool keep_normal)
{
    Vec3d normal = (keep_normal && m_clp) ? m_clp->get_normal() : -wxGetApp().plater()->get_camera().get_dir_forward();
    const Vec3d& center = get_pool()->get_canvas()->volumes_bounding_box().center();
    float dist = normal.dot(center);
    if (pos < 0.)
        pos = m_clp_ratio;
    m_clp_ratio = pos;
    m_clp.reset(new ClippingPlane(normal, (dist - (-m_active_inst_bb_radius * GLVolume::explosion_ratio) - m_clp_ratio * 2 * m_active_inst_bb_radius * GLVolume::explosion_ratio)));
    get_pool()->get_canvas()->set_as_dirty();
}
References Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::GLVolume::explosion_ratio, Slic3r::GUI::AssembleViewDataPool::get_canvas(), Slic3r::GUI::AssembleViewDataBase::get_pool(), m_active_inst_bb_radius, m_clp, m_clp_ratio, Slic3r::normal(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), and Slic3r::GUI::GLCanvas3D::volumes_bounding_box().
update()
void Slic3r::GUI::AssembleViewDataBase::update () inline inherited
{ on_update(); m_is_valid = true; }
References Slic3r::GUI::AssembleViewDataBase::m_is_valid, and Slic3r::GUI::AssembleViewDataBase::on_update().
Member Data Documentation
m_active_inst_bb_radius
double Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::m_active_inst_bb_radius = 0. private
Referenced by on_update(), and set_position().
m_clippers
std::vector<std::unique_ptr<MeshClipper> > Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::m_clippers private
Referenced by on_release(), on_update(), and render_cut().
m_clp
std::unique_ptr<ClippingPlane> Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::m_clp private
Referenced by get_clipping_plane(), on_release(), render_cut(), and set_position().
m_clp_ratio
double Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::m_clp_ratio = 0. private
Referenced by get_position(), on_release(), render_cut(), and set_position().
m_common
AssembleViewDataPool* Slic3r::GUI::AssembleViewDataBase::m_common = nullptr private inherited
Referenced by Slic3r::GUI::AssembleViewDataBase::get_pool().
m_is_valid
bool Slic3r::GUI::AssembleViewDataBase::m_is_valid = false private inherited
Referenced by Slic3r::GUI::AssembleViewDataBase::is_valid(), Slic3r::GUI::AssembleViewDataBase::release(), and Slic3r::GUI::AssembleViewDataBase::update().
m_old_meshes
std::vector<const TriangleMesh*> Slic3r::GUI::AssembleViewDataObjects::ModelObjectsClipper::m_old_meshes private
Referenced by on_release(), and on_update().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmosCommon.hpp
src/slic3r/GUI/Gizmos/GLGizmosCommon.cpp