OrcaSlicer: Slic3r::CurvatureEstimator Class Reference
Slic3r::CurvatureEstimator Class Reference
#include <src/libslic3r/GCode/ExtrusionProcessor.hpp>
Public Member Functions
void add_point (float distance, float angle)
float get_curvature ()
void reset ()
Private Attributes
SlidingWindowCurvatureAccumulator sliders [sliders_count] = {{1.0},{4.0}, {10.0}}
Static Private Attributes
static const size_t sliders_count = 3
Detailed Description
Member Function Documentation
add_point()
void Slic3r::CurvatureEstimator::add_point (float distance, float angle) inline
    {
        if (distance < EPSILON)
            return;
        for (SlidingWindowCurvatureAccumulator &slider : sliders) {
            slider.add_point(distance, angle);
        }
    }
References Slic3r::angle(), EPSILON, and sliders.
Referenced by Slic3r::estimate_points_properties().
get_curvature()
float Slic3r::CurvatureEstimator::get_curvature () inline
    {
        float max_curvature = 0.0f;
        for (const SlidingWindowCurvatureAccumulator &slider : sliders) {
            if (abs(slider.get_curvature()) > abs(max_curvature)) {
                max_curvature = slider.get_curvature();
            }
        }
        return max_curvature;
    }
References sliders.
Referenced by Slic3r::estimate_points_properties().
reset()
void Slic3r::CurvatureEstimator::reset () inline
    {
        for (SlidingWindowCurvatureAccumulator &slider : sliders) {
            slider.reset();
        }
    }
References sliders.
Member Data Documentation
sliders
SlidingWindowCurvatureAccumulator Slic3r::CurvatureEstimator::sliders[sliders_count] = {{1.0},{4.0}, {10.0}} private
Referenced by add_point(), get_curvature(), and reset().
sliders_count
const size_t Slic3r::CurvatureEstimator::sliders_count = 3 static private
The documentation for this class was generated from the following file:
src/libslic3r/GCode/ExtrusionProcessor.hpp