OrcaSlicer: Clipper2Lib::details Namespace Reference
Clipper2Lib::details Namespace Reference
Functions
void PolyPathToPaths64 (const PolyPath64 &polypath, Paths64 &paths)
void PolyPathToPathsD (const PolyPathD &polypath, PathsD &paths)
bool PolyPath64ContainsChildren (const PolyPath64 &pp)
bool GetInt (std::string::const_iterator &iter, const std::string::const_iterator &end_iter, int64_t &val)
bool GetFloat (std::string::const_iterator &iter, const std::string::const_iterator &end_iter, double &val)
void SkipWhiteSpace (std::string::const_iterator &iter, const std::string::const_iterator &end_iter)
void SkipSpacesWithOptionalComma (std::string::const_iterator &iter, const std::string::const_iterator &end_iter)
bool has_one_match (const char c, char *chrs)
void SkipUserDefinedChars (std::string::const_iterator &iter, const std::string::const_iterator &end_iter, const std::string &skip_chars)
Function Documentation
GetFloat()
bool Clipper2Lib::details::GetFloat (std::string::const_iterator & iter, const std::string::const_iterator & end_iter, double & val) inline
    {
      val = 0;
      bool is_neg = *iter == '-';
      if (is_neg) ++iter;
      int dec_pos = 1;
      const std::string::const_iterator start_iter = iter;
      while (iter != end_iter && (*iter == '.' ||
        ((*iter >= '0') && (*iter <= '9'))))
      {
        if (*iter == '.')
        {
          if (dec_pos != 1) break;
          dec_pos = 0;
          ++iter;
          continue;
        }
        if (dec_pos != 1) --dec_pos;
        val = val * 10 + ((int64_t)(*iter++) - '0');
      }
      if (iter == start_iter || dec_pos == 0) return false;
      if (dec_pos < 0)
        val *= std::pow(10, dec_pos);
      if (is_neg)
        val *= -1;
      return true;
    }
Referenced by Clipper2Lib::MakePathD().
GetInt()
bool Clipper2Lib::details::GetInt (std::string::const_iterator & iter, const std::string::const_iterator & end_iter, int64_t & val) inline
    {
      val = 0;
      bool is_neg = *iter == '-';
      if (is_neg) ++iter;
      std::string::const_iterator start_iter = iter;
      while (iter != end_iter &&
        ((*iter >= '0') && (*iter <= '9')))
      {
        val = val * 10 + (static_cast<int64_t>(*iter++) - '0');
      }
      if (is_neg) val = -val;
      return (iter != start_iter);
    }
Referenced by Clipper2Lib::MakePath().
has_one_match()
bool Clipper2Lib::details::has_one_match (const char c, char * chrs) inline
    {
      while (*chrs > 0 && c != *chrs) ++chrs;
      if (!*chrs) return false;
      *chrs = ' '; // only match once per char
      return true;
    }
Referenced by SkipUserDefinedChars().
PolyPath64ContainsChildren()
bool Clipper2Lib::details::PolyPath64ContainsChildren (const PolyPath64 & pp) inline
    {
      for (auto ch : pp)
      {
        PolyPath64* child = (PolyPath64*)ch;
        for (const Point64& pt : child->Polygon())
          if (PointInPolygon(pt, pp.Polygon()) == PointInPolygonResult::IsOutside)
            return false;
        if (child->Count() > 0 && !PolyPath64ContainsChildren(*child))
          return false;
      }
      return true;
    }
References Clipper2Lib::PolyPath64::Count(), Clipper2Lib::IsOutside, Clipper2Lib::PointInPolygon(), Clipper2Lib::PolyPath64::Polygon(), and PolyPath64ContainsChildren().
Referenced by Clipper2Lib::CheckPolytreeFullyContainsChildren(), and PolyPath64ContainsChildren().
PolyPathToPaths64()
void Clipper2Lib::details::PolyPathToPaths64 (const PolyPath64 & polypath, Paths64 & paths) inline
    {
      paths.push_back(polypath.Polygon());
      for (const PolyPath* child : polypath)
        PolyPathToPaths64(*(PolyPath64*)(child), paths);
    }
References Clipper2Lib::PolyPath64::Polygon(), and PolyPathToPaths64().
Referenced by PolyPathToPaths64(), and Clipper2Lib::PolyTreeToPaths64().
PolyPathToPathsD()
void Clipper2Lib::details::PolyPathToPathsD (const PolyPathD & polypath, PathsD & paths) inline
    {
      paths.push_back(polypath.Polygon());
      for (const PolyPath* child : polypath)
        PolyPathToPathsD(*(PolyPathD*)(child), paths);
    }
References Clipper2Lib::PolyPathD::Polygon(), and PolyPathToPathsD().
Referenced by PolyPathToPathsD(), and Clipper2Lib::PolyTreeToPathsD().
SkipSpacesWithOptionalComma()
void Clipper2Lib::details::SkipSpacesWithOptionalComma (std::string::const_iterator & iter, const std::string::const_iterator & end_iter) inline
    {
      bool comma_seen = false;
      while (iter != end_iter)
      {
        if (*iter == ' ') ++iter;
        else if (*iter == ',')
        {
          if (comma_seen) return; // don't skip 2 commas!
          comma_seen = true;
          ++iter;
        }
        else return;
      }
    }
Referenced by Clipper2Lib::MakePath(), and Clipper2Lib::MakePathD().
SkipUserDefinedChars()
void Clipper2Lib::details::SkipUserDefinedChars (std::string::const_iterator & iter, const std::string::const_iterator & end_iter, const std::string & skip_chars) inline
    {
      const size_t MAX_CHARS = 16;
      char buff[MAX_CHARS] = {0};
      std::copy(skip_chars.cbegin(), skip_chars.cend(), &buff[0]);
      while (iter != end_iter &&
        (*iter <= ' ' || has_one_match(*iter, buff))) ++iter;
      return;
    }
References has_one_match().
Referenced by Clipper2Lib::MakePath(), and Clipper2Lib::MakePathD().
SkipWhiteSpace()
void Clipper2Lib::details::SkipWhiteSpace (std::string::const_iterator & iter, const std::string::const_iterator & end_iter) inline
    {
      while (iter != end_iter && *iter <= ' ') ++iter;
    }