OrcaSlicer: Slic3r::GUI::OG_CustomCtrl Class Reference
Slic3r::GUI::OG_CustomCtrl Class Reference
#include <src/slic3r/GUI/OG_CustomCtrl.hpp>
Classes
struct CtrlLine
Public Member Functions
OG_CustomCtrl (wxWindow *parent, OptionsGroup *og, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, const wxValidator &val=wxDefaultValidator, const wxString &name=wxEmptyString)
~OG_CustomCtrl ()
void OnPaint (wxPaintEvent &)
void OnMotion (wxMouseEvent &event)
void OnLeftDown (wxMouseEvent &event)
void OnLeaveWin (wxMouseEvent &event)
void init_ctrl_lines ()
bool update_visibility (ConfigOptionMode mode)
void correct_window_position (wxWindow *win, const Line &line, Field *field=nullptr)
void correct_widgets_position (wxSizer *widget, const Line &line, Field *field=nullptr)
void init_max_win_width ()
void set_max_win_width (int max_win_width)
int get_max_win_width ()
int get_title_width ()
void fixup_items_positions ()
void msw_rescale ()
void sys_color_changed ()
wxPoint get_pos (const Line &line, Field *field=nullptr)
int get_height (const Line &line)
Public Attributes
OptionsGroup * opt_group
Private Attributes
wxFont m_font
int m_v_gap
int m_v_gap2
int m_h_gap
int m_em_unit
wxSize m_bmp_mode_sz
wxSize m_bmp_blinking_sz
int m_max_win_width {0}
std::vector< CtrlLine > ctrl_lines
Detailed Description
Constructor & Destructor Documentation
OG_CustomCtrl()
Slic3r::GUI::OG_CustomCtrl::OG_CustomCtrl (wxWindow * parent, OptionsGroup * og, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, const wxValidator & val = wxDefaultValidator, const wxString & name = wxEmptyString)
                                                            :
    wxPanel(parent, wxID_ANY, pos, size, /*wxWANTS_CHARS |*/ wxBORDER_NONE | wxTAB_TRAVERSAL),
    opt_group(og)
{
    if (!wxOSX)
        SetDoubleBuffered(true);// SetDoubleBuffered exists on Win and Linux/GTK, but is missing on OSX
    SetBackgroundColour(parent->GetBackgroundColour());
    // BBS: new font
    m_font = Label::Body_14;
    SetFont(m_font);
    m_em_unit   = em_unit(m_parent);
    m_v_gap   = lround(1.2 * m_em_unit);
    m_v_gap2  = lround(0.8 * m_em_unit);
    m_h_gap   = lround(0.2 * m_em_unit);
    //m_bmp_mode_sz       = get_bitmap_size(create_scaled_bitmap("mode_simple", this, wxOSX ? 10 : 12));
    m_bmp_blinking_sz   = get_bitmap_size(create_scaled_bitmap("blank_16", this));
    init_ctrl_lines();// from og.lines()
    this->Bind(wxEVT_PAINT,     &OG_CustomCtrl::OnPaint, this);
    this->Bind(wxEVT_MOTION,    &OG_CustomCtrl::OnMotion, this);
    this->Bind(wxEVT_LEFT_DOWN, &OG_CustomCtrl::OnLeftDown, this);
    this->Bind(wxEVT_LEAVE_WINDOW, &OG_CustomCtrl::OnLeaveWin, this);
}
References Label::Body_14, create_scaled_bitmap(), em_unit(), Slic3r::GUI::get_bitmap_size(), init_ctrl_lines(), m_bmp_blinking_sz, m_em_unit, m_font, m_h_gap, m_v_gap, m_v_gap2, OnLeaveWin(), OnLeftDown(), OnMotion(), OnPaint(), and wxOSX.
~OG_CustomCtrl()
Slic3r::GUI::OG_CustomCtrl::~OG_CustomCtrl () inline
{}
Member Function Documentation
correct_widgets_position()
void Slic3r::GUI::OG_CustomCtrl::correct_widgets_position (wxSizer * widget, const Line & line, Field * field = nullptr)
{
    auto children = widget->GetChildren();
    wxPoint line_pos = get_pos(line, field);
    int line_height = get_height(line);
    for (auto child : children)
        if (child->IsWindow()) {
            wxPoint pos = line_pos;
            wxSize  sz = child->GetWindow()->GetSize();
            pos.y += std::max(0, int(0.5 * (line_height - sz.y)));
            if (line.extra_widget_sizer && widget == line.extra_widget_sizer)
                pos.x += m_h_gap;
            child->GetWindow()->SetPosition(pos);
            line_pos.x += sz.x + m_h_gap;
        }
};
References Slic3r::GUI::Line::extra_widget_sizer, get_height(), get_pos(), and m_h_gap.
correct_window_position()
void Slic3r::GUI::OG_CustomCtrl::correct_window_position (wxWindow * win, const Line & line, Field * field = nullptr)
{
    wxPoint pos = get_pos(line, field);
    int line_height = get_height(line);
    if (opt_group->split_multi_line) { // BBS
        if (line.get_options().size() > 1)
            line_height = (line_height - m_v_gap + m_v_gap2) / line.get_options().size();
    }
    pos.y += std::max(0, int(0.5 * (line_height - win->GetSize().y)));
    win->SetPosition(pos);
};
References get_height(), Slic3r::GUI::Line::get_options(), get_pos(), m_v_gap, m_v_gap2, opt_group, and Slic3r::GUI::OptionsGroup::split_multi_line.
fixup_items_positions()
void Slic3r::GUI::OG_CustomCtrl::fixup_items_positions ()
{
    if (GetParent() == nullptr || GetPosition().y < GetParent()->GetSize().y)
        return;
    for (CtrlLine& line : ctrl_lines) {
        line.correct_items_positions();
    }
}
References ctrl_lines.
get_height()
int Slic3r::GUI::OG_CustomCtrl::get_height (const Line & line)
{
    for (auto ctrl_line : ctrl_lines)
        if (&ctrl_line.og_line == &line)
            return ctrl_line.height;
    return 0;
}
References ctrl_lines.
Referenced by correct_widgets_position(), and correct_window_position().
get_max_win_width()
int Slic3r::GUI::OG_CustomCtrl::get_max_win_width () inline
{ return m_max_win_width; }
References m_max_win_width.
get_pos()
wxPoint Slic3r::GUI::OG_CustomCtrl::get_pos (const Line & line, Field * field = nullptr)
To correct translation by context have to use wxGETTEXT_IN_CONTEXT macro from wxWidget 3.1.1
istead of (opt != option_set.back())
{
    // BBS: new layout
    wxCoord v_pos = 0;
    wxCoord h_pos = get_title_width() * m_em_unit;
    auto correct_line_height = [](int& line_height, wxWindow* win)
    {
        int win_height = win->GetSize().GetHeight();
        if (line_height < win_height)
            line_height = win_height;
    };
    auto correct_horiz_pos = [this](int& h_pos, Field* field) {
        if (m_max_win_width > 0 && field->getWindow()) {
            int win_width = field->getWindow()->GetSize().GetWidth();
            if (dynamic_cast<CheckBox*>(field))
                win_width *= 0.5;
            h_pos += m_max_win_width - win_width;
        }
    };
    auto add_label_width = [&h_pos, this](CtrlLine &ctrl_line, wxString const & label, int label_width) {
        wxClientDC dc(this);
        dc.SetFont(m_font);
        wxString multiline_text;
        auto size = Label::split_lines(dc, label_width, label, multiline_text);
        if (label_width > 0) size.x = label_width;
        h_pos += size.x + m_h_gap;
        if (ctrl_line.height < size.y)
            ctrl_line.height = size.y;
    };
    auto add_buttons_width = [&h_pos, this] (int blinking_button_width) {
#ifndef DISABLE_BLINKING
#  ifndef DISABLE_UNDO_SYS
        h_pos += 3 * blinking_button_width;
#  else
        h_pos += 2 * blinking_button_width;
#  endif
#else
#  ifndef DISABLE_UNDO_SYS
        h_pos += 2 * blinking_button_width;
#  else
        h_pos += 1 * blinking_button_width;
#  endif
#endif
    };
    for (CtrlLine& ctrl_line : ctrl_lines) {
        if (&ctrl_line.og_line == &line)
        {
            // BBS: new layout
            // h_pos = m_bmp_mode_sz.GetWidth() + m_h_gap;
            if (line.near_label_widget_win) {
                wxSize near_label_widget_sz = line.near_label_widget_win->GetSize();
                if (field_in)
                    h_pos += near_label_widget_sz.GetWidth() + m_h_gap;
                else
                    break;
            }
            wxString label = line.label;
            if (opt_group->label_width != 0)
                add_label_width(ctrl_line, label, opt_group->label_width * m_em_unit);
            int blinking_button_width = m_bmp_blinking_sz.GetWidth() + m_h_gap;
            if (line.widget) {
#ifndef DISABLE_BLINKING
                h_pos += blinking_button_width;
#endif
                for (auto child : line.widget_sizer->GetChildren())
                    if (child->IsWindow())
                        correct_line_height(ctrl_line.height, child->GetWindow());
                break;
            }
            if (opt_group->option_label_at_right) // BBS: position buttons at right
                add_buttons_width(blinking_button_width);
            // If we have a single option with no sidetext
            const std::vector<Option>& option_set = line.get_options();
            if (option_set.size() == 1 && option_set.front().opt.sidetext.size() == 0 &&
                option_set.front().side_widget == nullptr && line.get_extra_widgets().size() == 0)
            {
                // BBS: new layout
                // h_pos += 3 * blinking_button_width;
                Field* field = opt_group->get_field(option_set.front().opt_id);
                correct_line_height(ctrl_line.height, field->getWindow());
                correct_horiz_pos(h_pos, field);
                break;
            }
            bool is_multioption_line = option_set.size() > 1;
            for (auto opt : option_set) {
                Field* field = opt_group->get_field(opt.opt_id);
                correct_line_height(ctrl_line.height, field->getWindow());
                if (!opt_group->option_label_at_right) { // BBS: position option label at right
                    ConfigOptionDef option = opt.opt;
                    // add label if any
                    if (is_multioption_line && !option.label.empty()) {
                        auto label = (option.label == L_CONTEXT("Top", "Layers") || option.label == L_CONTEXT("Bottom", "Layers")) ? _CTX(option.label, "Layers") :
                                                                                                                                     _(option.label);
                        // BBS
                        // label += ":";
                        add_label_width(ctrl_line, label, opt_group->sublabel_width * m_em_unit);
                        h_pos += 8;
                    }
                }
                if (field == field_in) {
                    correct_horiz_pos(h_pos, field);
                    break;
                }
                if (opt_group->split_multi_line) {// BBS
                    v_pos += (ctrl_line.height - m_v_gap + m_v_gap2) / option_set.size();
                } else {
                    // BBS: new layout
                    h_pos += field->getWindow()->GetSize().x;
                    add_buttons_width(blinking_button_width);
                    if (option_set.size() == 1 && option_set.front().opt.full_width)
                        break;
                    // add sidetext if any
                    if (!field->combine_side_text() && (!opt.opt.sidetext.empty() || opt_group->sidetext_width > 0))
                        h_pos += opt_group->sidetext_width * m_em_unit + m_h_gap;
                    if (opt.opt_id != option_set.back().opt_id)
                        h_pos += lround(0.6 * m_em_unit);
                }
            }
            break;
        }
        if (ctrl_line.is_visible)
            v_pos += ctrl_line.height;
    }
    return wxPoint(h_pos, v_pos);
}
References _, _CTX, Slic3r::GUI::Field::combine_side_text(), ctrl_lines, Slic3r::GUI::Line::get_extra_widgets(), Slic3r::GUI::OptionsGroup::get_field(), Slic3r::GUI::Line::get_options(), get_title_width(), Slic3r::GUI::Field::getWindow(), L_CONTEXT, Slic3r::ConfigOptionDef::label, Slic3r::GUI::Line::label, Slic3r::GUI::OptionsGroup::label_width, m_bmp_blinking_sz, m_em_unit, m_font, m_h_gap, m_max_win_width, m_v_gap, m_v_gap2, Slic3r::GUI::Line::near_label_widget_win, opt_group, Slic3r::GUI::OptionsGroup::option_label_at_right, Slic3r::GUI::OptionsGroup::sidetext_width, size, Label::split_lines(), Slic3r::GUI::OptionsGroup::split_multi_line, Slic3r::GUI::OptionsGroup::sublabel_width, Slic3r::GUI::Line::widget, and Slic3r::GUI::Line::widget_sizer.
Referenced by correct_widgets_position(), and correct_window_position().
get_title_width()
int Slic3r::GUI::OG_CustomCtrl::get_title_width ()
{
    if (!GetLabel().IsEmpty())
        return titleWidth;
    else
        return 2;
}
References Slic3r::GUI::titleWidth.
Referenced by get_pos(), msw_rescale(), OnPaint(), and update_visibility().
init_ctrl_lines()
void Slic3r::GUI::OG_CustomCtrl::init_ctrl_lines ()
{
    const std::vector<Line>& og_lines = opt_group->get_lines();
    for (const Line& line : og_lines)
    {
        if (line.is_separator()) {
            ctrl_lines.emplace_back(CtrlLine(3, this, line));
            continue;
        }
        if (line.full_width && (
            // description line
            line.widget != nullptr ||
            // description line with widget (button)
            !line.get_extra_widgets().empty())
            )
            continue;
        const std::vector<Option>& option_set = line.get_options();
        wxCoord height;
        // if we have a single option with no label, no sidetext just add it directly to sizer
        if (option_set.size() == 1 && opt_group->label_width == 0 && option_set.front().opt.full_width &&
            option_set.front().opt.sidetext.size() == 0 && option_set.front().side_widget == nullptr &&
            line.get_extra_widgets().size() == 0)
        {
            height = m_bmp_blinking_sz.GetHeight() + m_v_gap;
            ctrl_lines.emplace_back(CtrlLine(height, this, line, true));
        }
        else if (opt_group->label_width != 0 && (!line.label.IsEmpty() || option_set.front().opt.gui_type == ConfigOptionDef::GUIType::legend) )
        {
            wxSize label_sz = GetTextExtent(line.label);
            if (opt_group->split_multi_line) {
                if (option_set.size() > 1) // BBS
                    height = (label_sz.y + m_v_gap2) * option_set.size() + m_v_gap - m_v_gap2;
                else
                    height = label_sz.y * (label_sz.GetWidth() > int(opt_group->label_width * m_em_unit) ? 2 : 1) + m_v_gap;
            } else {
                height = label_sz.y * (label_sz.GetWidth() > int(opt_group->label_width * m_em_unit) ? 2 : 1) + m_v_gap;
            }
            ctrl_lines.emplace_back(CtrlLine(height, this, line, false, opt_group->staticbox));
        }
        else
            assert(false);
    }
}
References ctrl_lines, Slic3r::GUI::OptionsGroup::get_lines(), int, Slic3r::GUI::OptionsGroup::label_width, Slic3r::ConfigOptionDef::legend, m_bmp_blinking_sz, m_em_unit, m_v_gap, m_v_gap2, opt_group, Slic3r::GUI::OptionsGroup::split_multi_line, and Slic3r::GUI::OptionsGroup::staticbox.
Referenced by OG_CustomCtrl().
init_max_win_width()
void Slic3r::GUI::OG_CustomCtrl::init_max_win_width ()
{
    if (opt_group->ctrl_horiz_alignment == wxALIGN_RIGHT && m_max_win_width == 0)
        for (CtrlLine& line : ctrl_lines) {
            if (int max_win_width = line.get_max_win_width();
                m_max_win_width < max_win_width)
                m_max_win_width = max_win_width;
        }
}
References Slic3r::GUI::OptionsGroup::ctrl_horiz_alignment, ctrl_lines, m_max_win_width, and opt_group.
Referenced by Slic3r::GUI::OptionsGroup::activate().
msw_rescale()
void Slic3r::GUI::OG_CustomCtrl::msw_rescale ()
{
#ifdef __WXOSX__
    return;
#endif
    // BBS: new font
    m_font = Label::Body_14;
    SetFont(m_font);
    m_em_unit   = em_unit(m_parent);
    m_v_gap     = lround(1.2 * m_em_unit);
    m_v_gap2     = lround(0.8 * m_em_unit);
    m_h_gap     = lround(0.2 * m_em_unit);
    //m_bmp_mode_sz = create_scaled_bitmap("mode_simple", this, wxOSX ? 10 : 12).GetSize();
    m_bmp_blinking_sz = create_scaled_bitmap("blank_16", this).GetSize();
    m_max_win_width = 0;
    wxCoord    h_pos = (ctrlWidth + get_title_width() - titleWidth) * m_em_unit;
    wxCoord    h_pos2 = get_title_width() * m_em_unit;
    wxCoord    v_pos = 0;
    for (CtrlLine& line : ctrl_lines) {
        line.msw_rescale();
        if (line.is_visible)
            v_pos += (wxCoord)line.height;
    }
    // BBS: multi-line title
    SetFont(Label::Head_16);
    wxSize label_sz = GetTextExtent(GetLabel());
    SetFont(m_font);
    auto lineHeight = label_sz.y;
    while (label_sz.x > h_pos2) {
        label_sz.x -= h_pos2;
        label_sz.y += lineHeight;
    }
    if (v_pos < label_sz.y) v_pos = label_sz.y;
    // BBS: new layout
    this->SetMinSize(wxSize(h_pos, v_pos));
    GetParent()->Layout();
}
References Label::Body_14, create_scaled_bitmap(), ctrl_lines, Slic3r::GUI::ctrlWidth, em_unit(), get_title_width(), Label::Head_16, m_bmp_blinking_sz, m_em_unit, m_font, m_h_gap, m_max_win_width, m_v_gap, m_v_gap2, and Slic3r::GUI::titleWidth.
Referenced by Slic3r::GUI::ConfigOptionsGroup::msw_rescale().
OnLeaveWin()
void Slic3r::GUI::OG_CustomCtrl::OnLeaveWin (wxMouseEvent & event)
{
    for (CtrlLine& line : ctrl_lines)
        line.is_focused = false;
    // BBS: markdown tip
    MarkdownTip::ShowTip("", "", {});
    Refresh();
    Update();
    event.Skip();
}
References ctrl_lines, and Slic3r::GUI::MarkdownTip::ShowTip().
Referenced by OG_CustomCtrl().
OnLeftDown()
void Slic3r::GUI::OG_CustomCtrl::OnLeftDown (wxMouseEvent & event)
{
    const wxPoint pos = event.GetLogicalPosition(wxClientDC(this));
    for (const CtrlLine& line : ctrl_lines) {
        if (!line.is_visible) continue;
        if (line.launch_browser())
            return;
        for (size_t opt_idx = 0; opt_idx < line.rects_undo_icon.size(); opt_idx++)
            if (is_point_in_rect(pos, line.rects_undo_icon[opt_idx])) {
                const std::vector<Option>& option_set = line.og_line.get_options();
                Field* field = opt_group->get_field(option_set[opt_idx].opt_id);
                if (field)
                    field->on_back_to_initial_value();
                event.Skip();
                return;
            }
        for (size_t opt_idx = 0; opt_idx < line.rects_undo_to_sys_icon.size(); opt_idx++)
            if (is_point_in_rect(pos, line.rects_undo_to_sys_icon[opt_idx])) {
                const std::vector<Option>& option_set = line.og_line.get_options();
                Field* field = opt_group->get_field(option_set[opt_idx].opt_id);
                if (field)
                    field->on_back_to_sys_value();
                event.Skip();
                return;
            }
    }
    SetFocusIgnoringChildren();
}
References ctrl_lines, Slic3r::GUI::OptionsGroup::get_field(), Slic3r::GUI::is_point_in_rect(), Slic3r::GUI::Field::on_back_to_initial_value(), Slic3r::GUI::Field::on_back_to_sys_value(), and opt_group.
Referenced by OG_CustomCtrl().
OnMotion()
void Slic3r::GUI::OG_CustomCtrl::OnMotion (wxMouseEvent & event)
{
    const wxPoint pos = event.GetLogicalPosition(wxClientDC(this));
    wxString tooltip;
    std::string markdowntip;
    wxString language = wxGetApp().app_config->get("language");
    // BBS: markdown tip
    CtrlLine* focusedLine = nullptr;
    // BBS
    bool suppress_hyperlinks = false;
    for (CtrlLine& line : ctrl_lines) {
        if (!line.is_visible) continue;
        line.is_focused = is_point_in_rect(pos, line.rect_label);
        if (line.is_focused) {
            if (!suppress_hyperlinks && !line.og_line.label_path.empty())
                tooltip = OptionsGroup::get_url(line.og_line.label_path) + "\n\n";
            tooltip += line.og_line.label_tooltip;
            // BBS: markdown tip
            focusedLine = &line;
            markdowntip = line.og_line.label.empty()
                ? line.og_line.get_options().front().opt_id : into_u8(line.og_line.label);
            markdowntip.erase(0, markdowntip.find_last_of('#') + 1);
            // BBS
            break;
        }
        for (size_t opt_idx = 0; opt_idx < line.rects_undo_icon.size(); opt_idx++)
            if (is_point_in_rect(pos, line.rects_undo_icon[opt_idx])) {
                const std::vector<Option>& option_set = line.og_line.get_options();
                Field* field = opt_group->get_field(option_set[opt_idx].opt_id);
                if (field)
                    tooltip = *field->undo_tooltip();
                break;
            }
        for (size_t opt_idx = 0; opt_idx < line.rects_undo_to_sys_icon.size(); opt_idx++)
            if (is_point_in_rect(pos, line.rects_undo_to_sys_icon[opt_idx])) {
                const std::vector<Option>& option_set = line.og_line.get_options();
                Field* field = opt_group->get_field(option_set[opt_idx].opt_id);
                if (field)
                    tooltip = *field->undo_to_sys_tooltip();
                break;
            }
        if (!tooltip.IsEmpty())
            break;
    }
    // Set tooltips with information for each icon
    // BBS: markdown tip
    if (!markdowntip.empty()) {
        wxWindow* window = GetGrandParent();
        assert(focusedLine);
        wxPoint pos2 = { 250, focusedLine->rect_label.y };
        pos2 = ClientToScreen(pos2);
        if (MarkdownTip::ShowTip(markdowntip, into_u8(tooltip), pos2)) {
            tooltip.clear();
        }
    }
    else {
        MarkdownTip::ShowTip(markdowntip, "", {tooltip.empty() ? 0 : 1, 0});
    }
    if (GetToolTipText() != tooltip)
        this->SetToolTip(tooltip);
    // BBS
    Refresh();
    Update();
    event.Skip();
}
References ctrl_lines, Slic3r::GUI::OptionsGroup::get_field(), Slic3r::GUI::OptionsGroup::get_url(), Slic3r::GUI::into_u8(), Slic3r::GUI::OG_CustomCtrl::CtrlLine::is_focused, Slic3r::GUI::is_point_in_rect(), Slic3r::GUI::Line::label, Slic3r::GUI::OG_CustomCtrl::CtrlLine::og_line, opt_group, Slic3r::GUI::OG_CustomCtrl::CtrlLine::rect_label, Slic3r::GUI::MarkdownTip::ShowTip(), Slic3r::GUI::Field::undo_to_sys_tooltip(), and Slic3r::GUI::Field::undo_tooltip().
Referenced by OG_CustomCtrl().
OnPaint()
void Slic3r::GUI::OG_CustomCtrl::OnPaint (wxPaintEvent &)
{
    // case, when custom controll is destroyed but doesn't deleted from the evet loop
    if(!this->opt_group->custom_ctrl)
        return;
    wxPaintDC dc(this);
    wxCoord h_pos = get_title_width() * m_em_unit;
    wxCoord v_pos = 0;
    // BBS: new layout
    if (!GetLabel().IsEmpty()) {
        dc.SetFont(Label::Head_16);
        wxColour color = StateColor::darkModeColorFor("#283436");
        draw_title(dc, {0, v_pos}, GetLabel(), &color, h_pos);
        dc.SetFont(m_font);
    }
    for (CtrlLine& line : ctrl_lines) {
        if (!line.is_visible)
            continue;
        line.render(dc, h_pos, v_pos);
        v_pos += line.height;
    }
}
References ctrl_lines, Slic3r::GUI::OptionsGroup::custom_ctrl, StateColor::darkModeColorFor(), Slic3r::GUI::draw_title(), get_title_width(), Label::Head_16, m_em_unit, m_font, and opt_group.
Referenced by OG_CustomCtrl().
set_max_win_width()
void Slic3r::GUI::OG_CustomCtrl::set_max_win_width (int max_win_width)
{
    if (m_max_win_width == max_win_width)
        return;
    m_max_win_width = max_win_width;
    for (CtrlLine& line : ctrl_lines)
        line.correct_items_positions();
    GetParent()->Layout();
}
References ctrl_lines, and m_max_win_width.
Referenced by Slic3r::GUI::OptionsGroup::set_max_win_width().
sys_color_changed()
void Slic3r::GUI::OG_CustomCtrl::sys_color_changed ()
{
}
update_visibility()
bool Slic3r::GUI::OG_CustomCtrl::update_visibility (ConfigOptionMode mode)
{
    // BBS: new layout
    wxCoord    h_pos = (ctrlWidth + get_title_width() - titleWidth) * m_em_unit;
    wxCoord    h_pos2 = get_title_width() * m_em_unit;
    wxCoord    v_pos = 0;
    size_t invisible_lines = 0;
    for (CtrlLine& line : ctrl_lines) {
        line.update_visibility(mode);
        if (line.is_visible)
            v_pos += (wxCoord)line.height;
        else
            invisible_lines++;
    }
    // BBS: multi-line title
    SetFont(Label::Head_16);
    wxSize label_sz = GetTextExtent(GetLabel());
    SetFont(m_font);
    auto lineHeight = label_sz.y;
    while (label_sz.x > h_pos2) {
        label_sz.x -= h_pos2;
        label_sz.y += lineHeight;
    }
    if (v_pos < label_sz.y) v_pos = label_sz.y;
    this->SetMinSize(wxSize(h_pos, v_pos));
    return invisible_lines != ctrl_lines.size();
}
References ctrl_lines, Slic3r::GUI::ctrlWidth, get_title_width(), Label::Head_16, m_em_unit, m_font, and Slic3r::GUI::titleWidth.
Referenced by Slic3r::GUI::ConfigOptionsGroup::update_visibility().
Member Data Documentation
ctrl_lines
std::vector<CtrlLine> Slic3r::GUI::OG_CustomCtrl::ctrl_lines private
Referenced by fixup_items_positions(), get_height(), get_pos(), init_ctrl_lines(), init_max_win_width(), msw_rescale(), OnLeaveWin(), OnLeftDown(), OnMotion(), OnPaint(), set_max_win_width(), and update_visibility().
m_bmp_blinking_sz
wxSize Slic3r::GUI::OG_CustomCtrl::m_bmp_blinking_sz private
Referenced by OG_CustomCtrl(), get_pos(), init_ctrl_lines(), and msw_rescale().
m_bmp_mode_sz
wxSize Slic3r::GUI::OG_CustomCtrl::m_bmp_mode_sz private
m_em_unit
int Slic3r::GUI::OG_CustomCtrl::m_em_unit private
Referenced by OG_CustomCtrl(), get_pos(), init_ctrl_lines(), msw_rescale(), OnPaint(), and update_visibility().
m_font
wxFont Slic3r::GUI::OG_CustomCtrl::m_font private
Referenced by OG_CustomCtrl(), get_pos(), msw_rescale(), OnPaint(), and update_visibility().
m_h_gap
int Slic3r::GUI::OG_CustomCtrl::m_h_gap private
Referenced by OG_CustomCtrl(), correct_widgets_position(), get_pos(), and msw_rescale().
m_max_win_width
int Slic3r::GUI::OG_CustomCtrl::m_max_win_width {0} private
Referenced by get_max_win_width(), get_pos(), init_max_win_width(), msw_rescale(), and set_max_win_width().
m_v_gap
int Slic3r::GUI::OG_CustomCtrl::m_v_gap private
Referenced by OG_CustomCtrl(), correct_window_position(), get_pos(), init_ctrl_lines(), and msw_rescale().
m_v_gap2
int Slic3r::GUI::OG_CustomCtrl::m_v_gap2 private
Referenced by OG_CustomCtrl(), correct_window_position(), get_pos(), init_ctrl_lines(), and msw_rescale().
opt_group
OptionsGroup* Slic3r::GUI::OG_CustomCtrl::opt_group
Referenced by correct_window_position(), get_pos(), init_ctrl_lines(), init_max_win_width(), OnLeftDown(), OnMotion(), and OnPaint().
The documentation for this class was generated from the following files:
src/slic3r/GUI/OG_CustomCtrl.hpp
src/slic3r/GUI/OG_CustomCtrl.cpp