OrcaSlicer: src/qhull/src/libqhullcpp/QhullFacet.cpp File Reference
QhullFacet.cpp File Reference
#include "libqhullcpp/QhullFacet.h"
#include "libqhullcpp/QhullError.h"
#include "libqhullcpp/Qhull.h"
#include "libqhullcpp/QhullSet.h"
#include "libqhullcpp/QhullPoint.h"
#include "libqhullcpp/QhullPointSet.h"
#include "libqhullcpp/QhullRidge.h"
#include "libqhullcpp/QhullFacetSet.h"
#include "libqhullcpp/QhullVertex.h"
#include <ostream>
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
operator<<
ostream & operator<< (ostream &os, const QhullFacet::PrintFacet &pr)
ostream & operator<< (ostream &os, const QhullFacet::PrintCenter &pr)
Print Voronoi center or facet centrum to stream. Same as qh_printcenter [_r.] Code duplicated for PrintCenter and getCenter Sets center if needed.
ostream & operator<< (ostream &os, const QhullFacet::PrintFlags &p)
Print flags for facet to stream. Space prefix. From qh_printfacetheader [io_r.c].
ostream & operator<< (ostream &os, const QhullFacet::PrintHeader &pr)
Print header for facet to stream. Space prefix. From qh_printfacetheader [io_r.c].
ostream & operator<< (ostream &os, const QhullFacet::PrintRidges &pr)
Print ridges of facet to stream. Same as qh_printfacetridges [io_r.c].
ostream & operator<< (ostream &os, QhullFacet &f)
Function Documentation
operator<<() [1/6]
ostream & operator<< (ostream & os, const QhullFacet::PrintCenter & pr)
Print Voronoi center or facet centrum to stream. Same as qh_printcenter [_r.] Code duplicated for PrintCenter and getCenter Sets center if needed.
{
    facetT *f= pr.facet->getFacetT();
    if(pr.facet->qh()->CENTERtype!=qh_ASvoronoi && pr.facet->qh()->CENTERtype!=qh_AScentrum){
        return os;
    }
    if (pr.message){
        os << pr.message;
    }
    int numCoords;
    if(pr.facet->qh()->CENTERtype==qh_ASvoronoi){
        numCoords= pr.facet->qh()->hull_dim-1;
        if(!f->normal || !f->upperdelaunay || !pr.facet->qh()->ATinfinity){
            if(!f->center){
                f->center= qh_facetcenter(pr.facet->qh(), f->vertices);
            }
            for(int k=0; k<numCoords; k++){
                os << f->center[k] << " "; // FIXUP QH11010 qh_REAL_1
            }
        }else{
            for(int k=0; k<numCoords; k++){
                os << qh_INFINITE << " "; // FIXUP QH11010 qh_REAL_1
            }
        }
    }else{ // qh CENTERtype==qh_AScentrum
        numCoords= pr.facet->qh()->hull_dim;
        if(pr.print_format==qh_PRINTtriangles && pr.facet->qh()->DELAUNAY){
            numCoords--;
        }
        if(!f->center){
            f->center= qh_getcentrum(pr.facet->qh(), f);
        }
        for(int k=0; k<numCoords; k++){
            os << f->center[k] << " "; // FIXUP QH11010 qh_REAL_1
        }
    }
    if(pr.print_format==qh_PRINTgeom && numCoords==2){
        os << " 0";
    }
    os << endl;
    return os;
}//operator<< PrintCenter
References facetT::center, facetT::normal, qh_AScentrum, qh_ASvoronoi, qh_facetcenter(), qh_getcentrum(), qh_INFINITE, qh_PRINTgeom, qh_PRINTtriangles, facetT::upperdelaunay, and facetT::vertices.
operator<<() [2/6]
ostream & operator<< (ostream & os, const QhullFacet::PrintFacet & pr)
{
    os << pr.message;
    QhullFacet f= *pr.facet;
    if(f.getFacetT()==0){ // Special values from set iterator
        os << " NULLfacet" << endl;
        return os;
    }
    if(f.getFacetT()==qh_MERGEridge){
        os << " MERGEridge" << endl;
        return os;
    }
    if(f.getFacetT()==qh_DUPLICATEridge){
        os << " DUPLICATEridge" << endl;
        return os;
    }
    os << f.printHeader();
    if(!f.ridges().isEmpty()){
        os << f.printRidges();
    }
    return os;
}//operator<< PrintFacet
References orgQhull::QhullFacet::getFacetT(), orgQhull::QhullSet< T >::isEmpty(), orgQhull::QhullFacet::printHeader(), orgQhull::QhullFacet::printRidges(), qh_DUPLICATEridge, qh_MERGEridge, and orgQhull::QhullFacet::ridges().
operator<<() [3/6]
ostream & operator<< (ostream & os, const QhullFacet::PrintFlags & p)
Print flags for facet to stream. Space prefix. From qh_printfacetheader [io_r.c].
{
    const facetT *f= p.facet->getFacetT();
    if(p.message){
        os << p.message;
    }
    os << (p.facet->isTopOrient() ? " top" : " bottom");
    if(p.facet->isSimplicial()){
        os << " simplicial";
    }
    if(p.facet->isTriCoplanar()){
        os << " tricoplanar";
    }
    if(p.facet->isUpperDelaunay()){
        os << " upperDelaunay";
    }
    if(f->visible){
        os << " visible";
    }
    if(f->newfacet){
        os << " new";
    }
    if(f->tested){
        os << " tested";
    }
    if(!f->good){
        os << " notG";
    }
    if(f->seen){
        os << " seen";
    }
    if(f->coplanar){
        os << " coplanar";
    }
    if(f->mergehorizon){
        os << " mergehorizon";
    }
    if(f->keepcentrum){
        os << " keepcentrum";
    }
    if(f->dupridge){
        os << " dupridge";
    }
    if(f->mergeridge && !f->mergeridge2){
        os << " mergeridge1";
    }
    if(f->mergeridge2){
        os << " mergeridge2";
    }
    if(f->newmerge){
        os << " newmerge";
    }
    if(f->flipped){
        os << " flipped";
    }
    if(f->notfurthest){
        os << " notfurthest";
    }
    if(f->degenerate){
        os << " degenerate";
    }
    if(f->redundant){
        os << " redundant";
    }
    os << endl;
    return os;
}//operator<< PrintFlags
References facetT::coplanar, facetT::degenerate, facetT::dupridge, facetT::flipped, facetT::good, facetT::keepcentrum, facetT::mergehorizon, facetT::mergeridge, facetT::mergeridge2, facetT::newfacet, facetT::newmerge, facetT::notfurthest, facetT::redundant, facetT::seen, facetT::tested, and facetT::visible.
operator<<() [4/6]
ostream & operator<< (ostream & os, const QhullFacet::PrintHeader & pr)
Print header for facet to stream. Space prefix. From qh_printfacetheader [io_r.c].
{
    QhullFacet facet= *pr.facet;
    facetT *f= facet.getFacetT();
    os << "- f" << facet.id() << endl;
    os << facet.printFlags("    - flags:");
    if(f->isarea){
        os << "    - area: " << f->f.area << endl; //FIXUP QH11010 2.2g
    }else if(pr.facet->qh()->NEWfacets && f->visible && f->f.replace){
        os << "    - replacement: f" << f->f.replace->id << endl;
    }else if(f->newfacet){
        if(f->f.samecycle && f->f.samecycle != f){
            os << "    - shares same visible/horizon as f" << f->f.samecycle->id << endl;
        }
    }else if(f->tricoplanar /* !isarea */){
        if(f->f.triowner){
            os << "    - owner of normal & centrum is facet f" << f->f.triowner->id << endl;
        }
    }else if(f->f.newcycle){
        os << "    - was horizon to f" << f->f.newcycle->id << endl;
    }
    if(f->nummerge){
        os << "    - merges: " << f->nummerge << endl;
    }
    os << facet.hyperplane().print("    - normal: ", "\n    - offset: "); // FIXUP QH11010 %10.7g
    if(pr.facet->qh()->CENTERtype==qh_ASvoronoi || f->center){
        os << facet.printCenter(qh_PRINTfacets, "    - center: ");
    }
#if qh_MAXoutside
    if(f->maxoutside > pr.facet->qh()->DISTround){
        os << "    - maxoutside: " << f->maxoutside << endl; //FIXUP QH11010 %10.7g
    }
#endif
    QhullPointSet ps= facet.outsidePoints();
    if(!ps.isEmpty()){
        QhullPoint furthest= ps.last();
        if (ps.size() < 6) {
            os << "    - outside set(furthest p" << furthest.id() << "):" << endl;
            for(QhullPointSet::iterator i=ps.begin(); i!=ps.end(); ++i){
                QhullPoint p= *i;
                os << p.print("     ");
            }
        }else if(ps.size()<21){
            os << ps.print("    - outside set:");
        }else{
            os << "    - outside set:  " << ps.size() << " points.";
            os << furthest.print("  Furthest");
        }
#if !qh_COMPUTEfurthest
        os << "    - furthest distance= " << f->furthestdist << endl; //FIXUP QH11010 %2.2g
#endif
    }
    QhullPointSet cs= facet.coplanarPoints();
    if(!cs.isEmpty()){
        QhullPoint furthest= cs.last();
        if (cs.size() < 6) {
            os << "    - coplanar set(furthest p" << furthest.id() << "):" << endl;
            for(QhullPointSet::iterator i=cs.begin(); i!=cs.end(); ++i){
                QhullPoint p= *i;
                os << p.print("     ");
            }
        }else if(cs.size()<21){
            os << cs.print("    - coplanar set:");
        }else{
            os << "    - coplanar set:  " << cs.size() << " points.";
            os << furthest.print("  Furthest");
        }
        // FIXUP QH11027 Can/should zinc_(Zdistio) be called from C++ interface
        double d= facet.distance(furthest);
        os << "      furthest distance= " << d << endl; //FIXUP QH11010 %2.2g
    }
    QhullVertexSet vs= facet.vertices();
    if(!vs.isEmpty()){
        os << vs.print("    - vertices:");
    }
    QhullFacetSet fs= facet.neighborFacets();
    fs.selectAll();
    if(!fs.isEmpty()){
        os << fs.printIdentifiers("    - neighboring facets:");
    }
    return os;
}//operator<< PrintHeader
References orgQhull::QhullSet< T >::begin(), facetT::center, orgQhull::QhullFacet::coplanarPoints(), orgQhull::QhullFacet::distance(), orgQhull::QhullSet< T >::end(), facetT::f, facetT::furthestdist, orgQhull::QhullFacet::getFacetT(), orgQhull::QhullFacet::hyperplane(), facetT::id, orgQhull::QhullFacet::id(), orgQhull::QhullPoint::id(), facetT::isarea, orgQhull::QhullSet< T >::isEmpty(), orgQhull::QhullSet< T >::last(), orgQhull::QhullFacet::neighborFacets(), facetT::newfacet, facetT::nummerge, orgQhull::QhullFacet::outsidePoints(), orgQhull::QhullHyperplane::print(), orgQhull::QhullPoint::print(), orgQhull::QhullPointSet::print(), orgQhull::QhullVertexSet::print(), orgQhull::QhullFacet::printCenter(), orgQhull::QhullFacet::printFlags(), qh_ASvoronoi, qh_PRINTfacets, orgQhull::QhullSetBase::size(), facetT::tricoplanar, orgQhull::QhullFacet::vertices(), and facetT::visible.
operator<<() [5/6]
ostream & operator<< (ostream & os, const QhullFacet::PrintRidges & pr)
Print ridges of facet to stream. Same as qh_printfacetridges [io_r.c].
{
    const QhullFacet facet= *pr.facet;
    facetT *f= facet.getFacetT();
    QhullRidgeSet rs= facet.ridges();
    if(!rs.isEmpty()){
        if(f->visible && pr.facet->qh()->NEWfacets){
            os << "    - ridges(ids may be garbage):";
            for(QhullRidgeSet::iterator i=rs.begin(); i!=rs.end(); ++i){
                QhullRidge r= *i;
                os << " r" << r.id();
            }
            os << endl;
        }else{
            os << "    - ridges:" << endl;
        }
        // Keep track of printed ridges
        for(QhullRidgeSet::iterator i=rs.begin(); i!=rs.end(); ++i){
            QhullRidge r= *i;
            r.getRidgeT()->seen= false;
        }
        int ridgeCount= 0;
        if(facet.dimension()==3){
            for(QhullRidge r= rs.first(); !r.getRidgeT()->seen; r= r.nextRidge3d(facet)){
                r.getRidgeT()->seen= true;
                os << r.print("");
                ++ridgeCount;
                if(!r.hasNextRidge3d(facet)){
                    break;
                }
            }
        }else {
            QhullFacetSet ns(facet.neighborFacets());
            for(QhullFacetSet::iterator i=ns.begin(); i!=ns.end(); ++i){
                QhullFacet neighbor= *i;
                QhullRidgeSet nrs(neighbor.ridges());
                for(QhullRidgeSet::iterator j=nrs.begin(); j!=nrs.end(); ++j){
                    QhullRidge r= *j;
                    if(r.otherFacet(neighbor)==facet){
                        r.getRidgeT()->seen= true;
                        os << r.print("");
                        ridgeCount++;
                    }
                }
            }
        }
        if(ridgeCount!=rs.count()){
            os << "     - all ridges:";
            for(QhullRidgeSet::iterator i=rs.begin(); i!=rs.end(); ++i){
                QhullRidge r= *i;
                os << " r" << r.id();
            }
            os << endl;
        }
        for(QhullRidgeSet::iterator i=rs.begin(); i!=rs.end(); ++i){
            QhullRidge r= *i;
            if(!r.getRidgeT()->seen){
                os << r.print("");
            }
        }
    }
    return os;
}//operator<< PrintRidges
References orgQhull::QhullFacet::dimension(), orgQhull::QhullFacet::getFacetT(), orgQhull::QhullRidge::getRidgeT(), orgQhull::QhullRidge::id(), orgQhull::QhullFacet::neighborFacets(), ns, orgQhull::QhullRidge::otherFacet(), orgQhull::QhullRidge::print(), orgQhull::QhullFacet::ridges(), ridgeT::seen, and facetT::visible.
operator<<() [6/6]
ostream & operator<< (ostream & os, QhullFacet & f)
{
    os << f.print("");
    return os;
}//<< QhullFacet
References orgQhull::QhullFacet::print().