OrcaSlicer: src/slic3r/GUI/Widgets/StateColor.cpp File Reference
StateColor.cpp File Reference
#include "StateColor.hpp"
Functions
static bool operator< (wxColour const &l, wxColour const &r)
wxColour darkModeColorFor2 (wxColour const &color)
std::map< wxColour, wxColour > revert (std::map< wxColour, wxColour > const &map)
Variables
static bool gDarkMode = false
static std::map< wxColour, wxColour > gDarkColors
Function Documentation
darkModeColorFor2()
wxColour darkModeColorFor2 (wxColour const & color) inline
{
    if (!gDarkMode)
        return color;
    auto iter = gDarkColors.find(color);
    wxASSERT(iter != gDarkColors.end());
    if (iter != gDarkColors.end()) return iter->second;
    return color;
}
References gDarkColors, and gDarkMode.
Referenced by StateColor::colorForStates(), and StateColor::darkModeColorFor().
operator<()
static bool operator< (wxColour const & l, wxColour const & r) static
{ return l.GetRGBA() < r.GetRGBA(); }
Referenced by Slic3r::SLAPrint::apply(), and Slic3r::Layer::make_ironing().
revert()
std::map< wxColour, wxColour > revert (std::map< wxColour, wxColour > const & map)
{
    std::map<wxColour, wxColour> map2;
    for (auto &p : map) map2.emplace(p.second, p.first);
    return map2;
}
Referenced by StateColor::lightModeColorFor(), and Slic3r::GUI::GLGizmoAdvancedCut::render_reset_button().
Variable Documentation
gDarkColors
std::map<wxColour, wxColour> gDarkColors static
Referenced by darkModeColorFor2(), StateColor::GetDarkMap(), and StateColor::lightModeColorFor().
gDarkMode
bool gDarkMode = false static
Referenced by darkModeColorFor2(), and StateColor::SetDarkMode().