OrcaSlicer: Slic3r::GUI::GLGizmoAdvancedCut Class Reference
Slic3r::GUI::GLGizmoAdvancedCut Class Reference
#include <src/slic3r/GUI/Gizmos/GLGizmoAdvancedCut.hpp>
Classes
struct InvalidConnectorsStatistics
struct Rotate_data
Public Types
enum EState { Off , On , Num_States }
Public Member Functions
GLGizmoAdvancedCut (GLCanvas3D &parent, const std::string &icon_filename, unsigned int sprite_id)
bool gizmo_event (SLAGizmoEventType action, const Vec2d &mouse_position, bool shift_down, bool alt_down, bool control_down)
bool on_key (wxKeyEvent &evt)
double get_movement () const
void set_movement (double movement) const
void finish_rotation ()
std::string get_tooltip () const override
BoundingBoxf3 bounding_box () const
bool is_looking_forward () const
bool unproject_on_cut_plane (const Vec2d &mouse_pos, Vec3d &pos, Vec3d &pos_world)
virtual bool apply_clipping_plane ()
Vec3d get_rotation () const
void set_rotation (const Vec3d &rotation)
void set_center (const Vec3d &point)
bool init ()
void load (cereal::BinaryInputArchive &ar)
void save (cereal::BinaryOutputArchive &ar) const
std::string get_name (bool include_shortcut=true) const
int get_group_id () const
void set_group_id (int id)
EState get_state () const
void set_state (EState state)
int get_shortcut_key () const
const std::string & get_icon_filename () const
void set_icon_filename (const std::string &filename)
bool is_activable () const
bool is_selectable () const
CommonGizmosDataID get_requirements () const
virtual bool wants_enter_leave_snapshots () const
virtual std::string get_gizmo_entering_text () const
virtual std::string get_gizmo_leaving_text () const
virtual std::string get_action_snapshot_name ()
void set_common_data_pool (CommonGizmosDataPool *ptr)
unsigned int get_sprite_id () const
int get_hover_id () const
void set_hover_id (int id)
void set_highlight_color (const std::array< float, 4 > &color)
void enable_grabber (unsigned int id)
void disable_grabber (unsigned int id)
void start_dragging ()
void stop_dragging ()
bool is_dragging () const
void update (const UpdateData &data)
bool update_items_state ()
void render ()
void render_for_picking ()
void render_input_window (float x, float y, float bottom_limit)
virtual void on_change_color_mode (bool is_dark)
int get_count ()
std::string get_gizmo_name ()
Static Public Member Functions
static void update_render_colors ()
static void load_render_colors ()
Static Public Attributes
static const unsigned int BASE_ID = 255 * 255 * 254
static float INV_ZOOM = 1.0f
static std::array< float, 4 > DEFAULT_BASE_COLOR = { 0.625f, 0.625f, 0.625f, 1.0f }
static std::array< float, 4 > DEFAULT_DRAG_COLOR = { 1.0f, 1.0f, 1.0f, 1.0f }
static std::array< float, 4 > DEFAULT_HIGHLIGHT_COLOR = { 1.0f, 0.38f, 0.0f, 1.0f }
static std::array< std::array< float, 4 >, 3 > AXES_COLOR
static std::array< std::array< float, 4 >, 3 > AXES_HOVER_COLOR
static std::array< float, 4 > CONSTRAINED_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f }
static std::array< float, 4 > FLATTEN_COLOR = { 0.96f, 0.93f, 0.93f, 0.5f }
static std::array< float, 4 > FLATTEN_HOVER_COLOR = { 1.0f, 1.0f, 1.0f, 0.75f }
static std::array< float, 4 > GRABBER_NORMAL_COL = {1.0f, 1.0f, 1.0f, 1.0f}
static std::array< float, 4 > GRABBER_HOVER_COL = {0.863f, 0.125f, 0.063f, 1.0f}
static std::array< float, 4 > GRABBER_UNIFORM_COL = {0, 1.0, 1.0, 1.0f}
static std::array< float, 4 > GRABBER_UNIFORM_HOVER_COL = {0, 0.7, 0.7, 1.0f}
Protected Member Functions
virtual bool on_init ()
virtual void on_load (cereal::BinaryInputArchive &ar) override
virtual void on_save (cereal::BinaryOutputArchive &ar) const override
virtual std::string on_get_name () const
virtual void on_set_state ()
virtual bool on_is_activable () const
virtual CommonGizmosDataID on_get_requirements () const override
virtual void on_start_dragging () override
virtual void on_stop_dragging () override
virtual void on_update (const UpdateData &data)
virtual void on_render ()
virtual void on_render_for_picking ()
virtual void on_render_input_window (float x, float y, float bottom_limit)
void show_tooltip_information (float x, float y)
virtual void on_enable_grabber (unsigned int id)
virtual void on_disable_grabber (unsigned int id)
virtual void on_set_hover_id ()
virtual bool on_is_selectable () const
bool GizmoImguiBegin (const std::string &name, int flags)
void GizmoImguiEnd ()
void GizmoImguiSetNextWIndowPos (float &x, float y, int flag, float pivot_x=0.0f, float pivot_y=0.0f)
std::array< float, 4 > picking_color_component (unsigned int id) const
void render_grabbers (const BoundingBoxf3 &box) const
void render_grabbers (float size) const
void render_grabbers_for_picking (const BoundingBoxf3 &box) const
std::string format (float value, unsigned int decimals) const
void set_dirty ()
Protected Attributes
std::vector< GLGizmoRotate > m_gizmos
GizmoObjectManipulation * m_object_manipulation
GLCanvas3D & m_parent
int m_group_id
EState m_state
int m_shortcut_key
std::string m_icon_filename
unsigned int m_sprite_id
int m_hover_id
bool m_dragging
std::array< float, 4 > m_base_color
std::array< float, 4 > m_drag_color
std::array< float, 4 > m_highlight_color
std::vector< Grabber > m_grabbers
ImGuiWrapper * m_imgui
bool m_first_input_window_render
std::string m_tooltip
CommonGizmosDataPool * m_c
GLModel m_cone
GLModel m_cylinder
GLModel m_sphere
bool m_is_dark_mode = false
float last_input_window_width = 0
Private Member Functions
void perform_cut (const Selection &selection)
bool can_perform_cut () const
void apply_connectors_in_model (ModelObject *mo, bool &create_dowels_as_separate_object)
bool is_selection_changed (bool alt_down, bool shift_down)
void select_connector (int idx, bool select)
double calc_projection (const Linef3 &mouse_ray) const
Vec3d calc_plane_normal (const std::array< Vec3d, 4 > &plane_points) const
Vec3d calc_plane_center (const std::array< Vec3d, 4 > &plane_points) const
Vec3d get_plane_normal () const
Vec3d get_plane_center () const
void update_plane_points ()
std::array< Vec3d, 4 > get_plane_points () const
std::array< Vec3d, 4 > get_plane_points_world_coord () const
void reset_cut_plane ()
void reset_all ()
void put_connectors_on_cut_plane (const Vec3d &cp_normal, double cp_offset)
void update_clipper ()
void render_cut_plane_and_grabbers ()
void render_connectors ()
void render_clipper_cut ()
void render_cut_line ()
void render_connector_model (GLModel &model, const std::array< float, 4 > &color, Transform3d view_model_matrix, bool for_picking=false)
void clear_selection ()
void init_connector_shapes ()
void set_connectors_editing (bool connectors_editing)
void reset_connectors ()
void update_connector_shape ()
void apply_selected_connectors (std::function< void(size_t idx)> apply_fn)
void select_all_connectors ()
void unselect_all_connectors ()
void validate_connector_settings ()
bool add_connector (CutConnectors &connectors, const Vec2d &mouse_position)
bool delete_selected_connectors ()
bool is_outside_of_cut_contour (size_t idx, const CutConnectors &connectors, const Vec3d cur_pos)
bool is_conflict_for_connector (size_t idx, const CutConnectors &connectors, const Vec3d cur_pos)
void check_conflict_for_all_connectors ()
void render_cut_plane_input_window (float x, float y, float bottom_limit)
void init_connectors_input_window_data ()
void render_connectors_input_window (float x, float y, float bottom_limit)
void render_input_window_warning () const
bool render_reset_button (const std::string &label_id, const std::string &tooltip) const
bool render_connect_type_radio_button (CutConnectorType type)
bool render_combo (const std::string &label, const std::vector< std::string > &lines, size_t &selection_idx)
bool render_slider_double_input (const std::string &label, float &value_in, float &tolerance_in)
bool cut_line_processing () const
void discard_cut_line_processing ()
bool process_cut_line (SLAGizmoEventType action, const Vec2d &mouse_position)
void load_rotoptimize_state ()
Private Attributes
double m_movement
double m_height
double m_height_delta
double m_start_movement
double m_start_height
Vec3d m_rotation
std::vector< Rotate_data > m_rotate_cmds
Vec3d m_buffered_rotation
double m_buffered_movement
double m_buffered_height
Vec3d m_drag_pos
bool m_keep_upper
bool m_keep_lower
bool m_cut_to_parts
bool m_place_on_cut_upper {true}
bool m_place_on_cut_lower {false}
bool m_rotate_upper {false}
bool m_rotate_lower {false}
bool m_do_segment
double m_segment_smoothing_alpha
int m_segment_number
std::array< Vec3d, 4 > m_cut_plane_points
Grabber m_move_grabber
unsigned int m_last_active_id
bool m_connectors_editing {false}
bool m_show_shortcuts {false}
std::vector< std::pair< wxString, wxString > > m_shortcuts
double m_label_width {150.0}
double m_control_width { 200.0 }
double m_editing_window_width
CutConnectorType m_connector_type
size_t m_connector_style
size_t m_connector_shape_id
float m_connector_depth_ratio {3.f}
float m_connector_depth_ratio_tolerance {0.1f}
float m_connector_size {2.5f}
float m_connector_size_tolerance {0.f}
TriangleMesh m_connector_mesh
bool m_has_invalid_connector {false}
std::vector< bool > m_selected
int m_selected_count {0}
Vec3d m_cut_plane_center {Vec3d::Zero()}
Vec3d m_cut_plane_normal {Vec3d::UnitZ()}
Vec3d m_cut_line_begin {Vec3d::Zero()}
Vec3d m_cut_line_end {Vec3d::Zero()}
Transform3d m_rotate_matrix {Transform3d::Identity()}
std::map< CutConnectorAttributes, GLModel > m_shapes
struct Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics m_info_stats
RotoptimzeWindow::State m_rotoptimizewin_state = {}
bool m_dirty
int count = 0
Static Private Attributes
static const double Offset = 10.0
static const double Margin = 20.0
static const std::array< float, 4 > GrabberColor = { 1.0, 1.0, 0.0, 1.0 }
static const std::array< float, 4 > GrabberHoverColor = { 0.7, 0.7, 0.0, 1.0}
Detailed Description
Member Enumeration Documentation
EState
enum Slic3r::GUI::GLGizmoBase::EState inherited
Enumerator
Off
On
Num_States
    {
        Off,
        On,
        Num_States
    };
Constructor & Destructor Documentation
GLGizmoAdvancedCut()
Slic3r::GUI::GLGizmoAdvancedCut::GLGizmoAdvancedCut (GLCanvas3D & parent, const std::string & icon_filename, unsigned int sprite_id)
    : GLGizmoRotate3D(parent, icon_filename, sprite_id, nullptr)
    , m_movement(0.0)
    , m_buffered_movement(0.0)
    , m_last_active_id(0)
    , m_keep_upper(true)
    , m_keep_lower(true)
    , m_cut_to_parts(false)
    , m_do_segment(false)
    , m_segment_smoothing_alpha(0.5)
    , m_segment_number(5)
    , m_connector_type(CutConnectorType::Plug)
    , m_connector_style(size_t(CutConnectorStyle::Prizm))
    , m_connector_shape_id(size_t(CutConnectorShape::Circle))
{
    for (int i = 0; i < 4; i++)
        m_cut_plane_points[i] = { 0., 0., 0. };
    set_group_id(m_gizmos.size());
    m_rotation.setZero();
    //m_current_base_rotation.setZero();
    m_rotate_cmds.clear();
    m_buffered_rotation.setZero();
}
References m_buffered_rotation, m_cut_plane_points, Slic3r::GUI::GLGizmoRotate3D::m_gizmos, m_rotate_cmds, m_rotation, Slic3r::GUI::GLGizmoBase::set_group_id(), and Eigen::PlainObjectBase< Derived >::setZero().
Member Function Documentation
add_connector()
bool Slic3r::GUI::GLGizmoAdvancedCut::add_connector (CutConnectors & connectors, const Vec2d & mouse_position) private
{
    if (!m_connectors_editing)
        return false;
    Vec3d pos;
    Vec3d pos_world;
    if (unproject_on_cut_plane(mouse_position.cast<double>(), pos, pos_world)) {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Add connector");
        unselect_all_connectors();
        connectors.emplace_back(pos, m_rotate_matrix, m_connector_size * 0.5f, m_connector_depth_ratio, m_connector_size_tolerance, m_connector_depth_ratio_tolerance,
                                CutConnectorAttributes(CutConnectorType(m_connector_type), CutConnectorStyle(m_connector_style), CutConnectorShape(m_connector_shape_id)));
        m_selected.push_back(true);
        m_selected_count = 1;
        assert(m_selected.size() == connectors.size());
        m_parent.set_as_dirty();
        return true;
    }
    return false;
}
References m_connector_depth_ratio, m_connector_depth_ratio_tolerance, m_connector_shape_id, m_connector_size, m_connector_size_tolerance, m_connector_style, m_connector_type, m_connectors_editing, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_matrix, m_selected, m_selected_count, Slic3r::GUI::plater(), Slic3r::GUI::GLCanvas3D::set_as_dirty(), unproject_on_cut_plane(), and unselect_all_connectors().
Referenced by gizmo_event().
apply_clipping_plane()
virtual bool Slic3r::GUI::GLGizmoAdvancedCut::apply_clipping_plane () inline virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{ return m_connectors_editing; }
References m_connectors_editing.
apply_connectors_in_model()
void Slic3r::GUI::GLGizmoAdvancedCut::apply_connectors_in_model (ModelObject * mo, bool & create_dowels_as_separate_object) private
{
    clear_selection();
    for (CutConnector &connector : mo->cut_connectors) {
        connector.rotation_m = m_rotate_matrix;
        if (connector.attribs.type == CutConnectorType::Dowel) {
            if (connector.attribs.style == CutConnectorStyle::Prizm) connector.height *= 2;
            create_dowels_as_separate_object = true;
        } else {
            // culculate shift of the connector center regarding to the position on the cut plane
            Vec3d shifted_center = m_cut_plane_center + Vec3d::UnitZ();
            shifted_center       = rotate_vec3d_around_vec3d_with_rotate_matrix(shifted_center, m_cut_plane_center, m_rotate_matrix);
            Vec3d norm           = (shifted_center - m_cut_plane_center).normalized();
            connector.pos += norm * 0.5 * double(connector.height);
        }
    }
    mo->apply_cut_connectors(_u8L("Connector"));
}
References _u8L, Slic3r::ModelObject::apply_cut_connectors(), clear_selection(), Slic3r::ModelObject::cut_connectors, Slic3r::Dowel, m_cut_plane_center, m_rotate_matrix, Slic3r::Prizm, and Slic3r::GUI::rotate_vec3d_around_vec3d_with_rotate_matrix().
Referenced by perform_cut().
apply_selected_connectors()
void Slic3r::GUI::GLGizmoAdvancedCut::apply_selected_connectors (std::function< void(size_t idx)> apply_fn) private
{
    for (size_t idx = 0; idx < m_selected.size(); idx++)
        if (m_selected[idx])
            apply_fn(idx);
}
References m_selected.
Referenced by render_connectors_input_window().
bounding_box()
BoundingBoxf3 Slic3r::GUI::GLGizmoAdvancedCut::bounding_box () const
{
    BoundingBoxf3                 ret;
    const Selection &             selection = m_parent.get_selection();
    const Selection::IndicesList &idxs      = selection.get_volume_idxs();
    for (unsigned int i : idxs) {
        const GLVolume *volume = selection.get_volume(i);
        // respect just to the solid parts for FFF and ignore pad and supports for SLA
        if (!volume->is_modifier && !volume->is_sla_pad() && !volume->is_sla_support()) ret.merge(volume->transformed_convex_hull_bounding_box());
    }
    return ret;
}
References Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::BoundingBox3Base< PointClass >::merge().
Referenced by is_conflict_for_connector(), render_slider_double_input(), and update_clipper().
calc_plane_center()
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::calc_plane_center (const std::array< Vec3d, 4 > & plane_points) const private
{
    Vec3d plane_center;
    plane_center.setZero();
    for (const Vec3d& point : plane_points)
        plane_center = plane_center + point;
    return plane_center / (float)m_cut_plane_points.size();
}
References m_cut_plane_points, and Eigen::PlainObjectBase< Derived >::setZero().
Referenced by get_plane_center(), and render_cut_plane_and_grabbers().
calc_plane_normal()
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::calc_plane_normal (const std::array< Vec3d, 4 > & plane_points) const private
{
    Vec3d v01 = plane_points[1] - plane_points[0];
    Vec3d v12 = plane_points[2] - plane_points[1];
    Vec3d plane_normal = v01.cross(v12);
    plane_normal.normalize();
    return plane_normal;
}
Referenced by get_plane_normal(), render_cut_plane_and_grabbers(), and update_plane_points().
calc_projection()
double Slic3r::GUI::GLGizmoAdvancedCut::calc_projection (const Linef3 & mouse_ray) const private
{
    Vec3d mouse_dir = mouse_ray.unit_vector();
    Vec3d inters = mouse_ray.a + (m_drag_pos - mouse_ray.a).dot(mouse_dir) / mouse_dir.squaredNorm() * mouse_dir;
    Vec3d inters_vec = inters - m_drag_pos;
    Vec3d plane_normal = get_plane_normal();
    return inters_vec.dot(plane_normal);
}
References Slic3r::Linef3::a, Slic3r::dot(), get_plane_normal(), m_drag_pos, and Slic3r::Linef3::unit_vector().
Referenced by on_update().
can_perform_cut()
bool Slic3r::GUI::GLGizmoAdvancedCut::can_perform_cut () const private
{
    if (m_has_invalid_connector || (!m_keep_upper && !m_keep_lower) || m_connectors_editing)
        return false;
    return true;
    //const auto clipper = m_c->object_clipper();
    //return clipper && clipper->has_valid_contour();
}
References m_connectors_editing, m_has_invalid_connector, m_keep_lower, and m_keep_upper.
Referenced by perform_cut(), and render_cut_plane_input_window().
check_conflict_for_all_connectors()
void Slic3r::GUI::GLGizmoAdvancedCut::check_conflict_for_all_connectors () private
{
    const ModelObject *mo      = m_c->selection_info()->model_object();
    auto               inst_id = m_c->selection_info()->get_active_instance();
    if (inst_id < 0)
        return;
    const CutConnectors &connectors      = mo->cut_connectors;
    const ModelInstance *mi              = mo->instances[inst_id];
    const Vec3d &        instance_offset = mi->get_offset();
    const double         sla_shift       = double(m_c->selection_info()->get_sla_shift());
    m_has_invalid_connector = false;
    m_info_stats.invalidate();
    for (size_t i = 0; i < connectors.size(); ++i) {
        const CutConnector &connector = connectors[i];
        Vec3d pos = connector.pos + instance_offset + sla_shift * Vec3d::UnitZ();
        // First decide about the color of the point.
        const bool conflict_connector = is_conflict_for_connector(i, connectors, pos);
        if (conflict_connector) {
            m_has_invalid_connector = true;
        }
    }
}
References Slic3r::ModelObject::cut_connectors, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::ModelInstance::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::ModelObject::instances, Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics::invalidate(), is_conflict_for_connector(), Slic3r::GUI::GLGizmoBase::m_c, m_has_invalid_connector, m_info_stats, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::CutConnector::pos, and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by on_render().
clear_selection()
void Slic3r::GUI::GLGizmoAdvancedCut::clear_selection () private
{
    m_selected.clear();
    m_selected_count = 0;
}
References m_selected, and m_selected_count.
Referenced by apply_connectors_in_model(), on_set_state(), render_connectors(), and reset_connectors().
cut_line_processing()
bool Slic3r::GUI::GLGizmoAdvancedCut::cut_line_processing () const private
{
    return m_cut_line_begin != Vec3d::Zero();
}
References m_cut_line_begin.
Referenced by process_cut_line(), and render_cut_line().
delete_selected_connectors()
bool Slic3r::GUI::GLGizmoAdvancedCut::delete_selected_connectors () private
{
    CutConnectors &connectors = m_c->selection_info()->model_object()->cut_connectors;
    if (connectors.empty())
        return false;
    Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Delete connector");
    // remove  connectors
    for (int i = int(connectors.size()) - 1; i >= 0; i--)
        if (m_selected[i]) connectors.erase(connectors.begin() + i);
    // remove selections
    m_selected.erase(std::remove_if(m_selected.begin(), m_selected.end(),
        [](const auto &selected) {
            return selected;}),
        m_selected.end());
    m_selected_count = 0;
    assert(m_selected.size() == connectors.size());
    m_parent.set_as_dirty();
    return true;
}
References Slic3r::ModelObject::cut_connectors, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::GLGizmoBase::m_parent, m_selected, m_selected_count, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::plater(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
Referenced by gizmo_event(), and on_key().
disable_grabber()
void Slic3r::GUI::GLGizmoBase::disable_grabber (unsigned int id) inherited
{
    if (id < m_grabbers.size())
        m_grabbers[id].enabled = false;
    on_disable_grabber(id);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_disable_grabber().
Referenced by on_disable_grabber().
discard_cut_line_processing()
void Slic3r::GUI::GLGizmoAdvancedCut::discard_cut_line_processing () private
{
    m_cut_line_begin = m_cut_line_end = Vec3d::Zero();
}
References m_cut_line_begin, and m_cut_line_end.
Referenced by process_cut_line().
enable_grabber()
void Slic3r::GUI::GLGizmoBase::enable_grabber (unsigned int id) inherited
{
    if (id < m_grabbers.size())
        m_grabbers[id].enabled = true;
    on_enable_grabber(id);
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_enable_grabber().
Referenced by on_enable_grabber().
finish_rotation()
void Slic3r::GUI::GLGizmoAdvancedCut::finish_rotation ()
{
    for (int i = 0; i < 3; i++) {
        m_gizmos[i].set_angle(0.);
    }
    update_plane_points();
}
References Slic3r::GUI::GLGizmoRotate3D::m_gizmos, and update_plane_points().
format()
std::string Slic3r::GUI::GLGizmoBase::format (float value, unsigned int decimals) const protected inherited
{
    return Slic3r::string_printf("%.*f", decimals, value);
}
References Slic3r::string_printf().
Referenced by Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), and Slic3r::GUI::GLGizmoSimplify::on_render_input_window().
get_action_snapshot_name()
virtual std::string Slic3r::GUI::GLGizmoBase::get_action_snapshot_name () inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, and Slic3r::GUI::GLGizmoSeam.
{ return "Gizmo action"; }
Referenced by Slic3r::GUI::Plater::priv::take_snapshot().
get_count()
int Slic3r::GUI::GLGizmoBase::get_count () inline inherited
{ return ++count; }
References Slic3r::GUI::GLGizmoBase::count.
get_gizmo_entering_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_entering_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
get_gizmo_leaving_text()
virtual std::string Slic3r::GUI::GLGizmoBase::get_gizmo_leaving_text () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoFdmSupports, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoSeam, and Slic3r::GUI::GLGizmoSlaSupports.
{ assert(false); return ""; }
get_gizmo_name()
std::string Slic3r::GUI::GLGizmoBase::get_gizmo_name () inline inherited
{ return on_get_name(); }
References Slic3r::GUI::GLGizmoBase::on_get_name().
get_group_id()
int Slic3r::GUI::GLGizmoBase::get_group_id () const inline inherited
{ return m_group_id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by on_start_dragging(), on_update(), and render_cut_plane_and_grabbers().
get_hover_id()
int Slic3r::GUI::GLGizmoBase::get_hover_id () const inline inherited
{ return m_hover_id; }
References Slic3r::GUI::GLGizmoBase::m_hover_id.
Referenced by Slic3r::GUI::GLGizmoText::gizmo_event().
get_icon_filename()
const std::string & Slic3r::GUI::GLGizmoBase::get_icon_filename () const inline inherited
{ return m_icon_filename; }
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
get_movement()
double Slic3r::GUI::GLGizmoAdvancedCut::get_movement () const inline
{ return m_movement; }
References m_movement.
get_name()
std::string Slic3r::GUI::GLGizmoBase::get_name (bool include_shortcut = true) const inherited
{
    int key = get_shortcut_key();
    std::string out = on_get_name();
    if (include_shortcut && key >= WXK_CONTROL_A && key <= WXK_CONTROL_Z)
        out += std::string(" [") + char(int('A') + key - int(WXK_CONTROL_A)) + "]";
    return out;
}
References Slic3r::GUI::GLGizmoBase::get_shortcut_key(), Slic3r::GUI::GLGizmoBase::on_get_name(), and out.
Referenced by Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), and Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window().
get_plane_center()
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::get_plane_center () const private
{
    return calc_plane_center(m_cut_plane_points);
}
References calc_plane_center(), and m_cut_plane_points.
Referenced by process_cut_line(), render_cut_plane_and_grabbers(), and update_plane_points().
get_plane_normal()
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::get_plane_normal () const private
{
    return calc_plane_normal(m_cut_plane_points);
}
References calc_plane_normal(), and m_cut_plane_points.
Referenced by calc_projection(), on_update(), and render_cut_plane_input_window().
get_plane_points()
std::array< Vec3d, 4 > Slic3r::GUI::GLGizmoAdvancedCut::get_plane_points () const private
{
    return m_cut_plane_points;
}
References m_cut_plane_points.
get_plane_points_world_coord()
std::array< Vec3d, 4 > Slic3r::GUI::GLGizmoAdvancedCut::get_plane_points_world_coord () const private
{
    std::array<Vec3d, 4> plane_world_coord = m_cut_plane_points;
    const Selection& selection = m_parent.get_selection();
    const BoundingBoxf3& box = selection.get_bounding_box();
    Vec3d object_offset = box.center();
    for (Vec3d& point : plane_world_coord) {
        point += object_offset;
    }
    return plane_world_coord;
}
References Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::GLCanvas3D::get_selection(), m_cut_plane_points, and Slic3r::GUI::GLGizmoBase::m_parent.
Referenced by perform_cut().
get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoBase::get_requirements () const inline inherited
{ return on_get_requirements(); }
References Slic3r::GUI::GLGizmoBase::on_get_requirements().
get_rotation()
Vec3d Slic3r::GUI::GLGizmoRotate3D::get_rotation () const inline inherited
{ return Vec3d(m_gizmos[X].get_angle(), m_gizmos[Y].get_angle(), m_gizmos[Z].get_angle()); }
References Slic3r::GUI::GLGizmoRotate3D::m_gizmos, Slic3r::X, Slic3r::Y, and Slic3r::Z.
get_shortcut_key()
int Slic3r::GUI::GLGizmoBase::get_shortcut_key () const inline inherited
{ return m_shortcut_key; }
References Slic3r::GUI::GLGizmoBase::m_shortcut_key.
Referenced by Slic3r::GUI::GLGizmoBase::get_name().
get_sprite_id()
unsigned int Slic3r::GUI::GLGizmoBase::get_sprite_id () const inline inherited
{ return m_sprite_id; }
References Slic3r::GUI::GLGizmoBase::m_sprite_id.
get_state()
EState Slic3r::GUI::GLGizmoBase::get_state () const inline inherited
{ return m_state; }
References Slic3r::GUI::GLGizmoBase::m_state.
Referenced by Slic3r::GUI::GLCanvas3D::on_mouse(), on_set_state(), Slic3r::GUI::GLGizmoCut::on_set_state(), Slic3r::GUI::GLGizmoFaceDetector::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), and Slic3r::GUI::GLGizmoSeam::on_set_state().
get_tooltip()
std::string Slic3r::GUI::GLGizmoAdvancedCut::get_tooltip () const override virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return "";
}
gizmo_event()
bool Slic3r::GUI::GLGizmoAdvancedCut::gizmo_event (SLAGizmoEventType action, const Vec2d & mouse_position, bool shift_down, bool alt_down, bool control_down)
{
    CutConnectors &connectors = m_c->selection_info()->model_object()->cut_connectors;
    if (shift_down && !m_connectors_editing &&
        (action == SLAGizmoEventType::LeftDown || action == SLAGizmoEventType::LeftUp || action == SLAGizmoEventType::Dragging)) {
        process_cut_line(action, mouse_position);
        return true;
    }
    if (action == SLAGizmoEventType::LeftDown) {
        if (!m_connectors_editing)
            return false;
        if (m_hover_id != -1) {
            start_dragging();
            return true;
        }
        if (shift_down || alt_down) {
            // left down with shift - show the selection rectangle:
            //if (m_hover_id == -1)
            //    m_selection_rectangle.start_dragging(mouse_position, shift_down ? GLSelectionRectangle::EState::Select : GLSelectionRectangle::EState::Deselect);
        } else {
            // If there is no selection and no hovering, add new point
            if (m_hover_id == -1 && !shift_down && !alt_down)
                add_connector(connectors, mouse_position);
                    //m_ldown_mouse_position = mouse_position;
        }
        return true;
    }
    else if (action == SLAGizmoEventType::LeftUp) {
        if (m_hover_id == -1 && !shift_down && !alt_down)
            unselect_all_connectors();
        is_selection_changed(alt_down, shift_down);
        return true;
    }
    else if (action == SLAGizmoEventType::RightDown) {
        if (m_hover_id < c_connectors_group_id)
            return false;
        unselect_all_connectors();
        select_connector(m_hover_id - c_connectors_group_id, true);
        return delete_selected_connectors();
    }
    else if (action == SLAGizmoEventType::RightUp) {
        // catch right click event
        return true;
    }
    return false;
}
References add_connector(), Slic3r::GUI::c_connectors_group_id, Slic3r::ModelObject::cut_connectors, delete_selected_connectors(), Slic3r::GUI::Dragging, is_selection_changed(), Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), process_cut_line(), Slic3r::GUI::RightDown, Slic3r::GUI::RightUp, select_connector(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLGizmoBase::start_dragging(), and unselect_all_connectors().
GizmoImguiBegin()
bool Slic3r::GUI::GLGizmoBase::GizmoImguiBegin (const std::string & name, int flags) protected inherited
{
    return m_imgui->begin(name, flags);
}
References Slic3r::GUI::ImGuiWrapper::begin(), and Slic3r::GUI::GLGizmoBase::m_imgui.
Referenced by on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
GizmoImguiEnd()
void Slic3r::GUI::GLGizmoBase::GizmoImguiEnd () protected inherited
{
    last_input_window_width = ImGui::GetWindowWidth();
    m_imgui->end();
}
References Slic3r::GUI::ImGuiWrapper::end(), ImGui::GetWindowWidth(), Slic3r::GUI::GLGizmoBase::last_input_window_width, and Slic3r::GUI::GLGizmoBase::m_imgui.
Referenced by on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
GizmoImguiSetNextWIndowPos()
void Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos (float & x, float y, int flag, float pivot_x = 0.0f, float pivot_y = 0.0f) protected inherited
{
    if (abs(last_input_window_width) > 0.01f) {
        if (x + last_input_window_width > m_parent.get_canvas_size().get_width()) {
            if (last_input_window_width > m_parent.get_canvas_size().get_width()) {
                x = 0;
            } else {
                x = m_parent.get_canvas_size().get_width() - last_input_window_width;
            }
        }
    }
    m_imgui->set_next_window_pos(x, y, flag, pivot_x, pivot_y);
}
References Slic3r::GUI::GLCanvas3D::get_canvas_size(), Slic3r::GUI::Size::get_width(), Slic3r::GUI::GLGizmoBase::last_input_window_width, Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoBase::m_parent, and Slic3r::GUI::ImGuiWrapper::set_next_window_pos().
Referenced by on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), and Slic3r::GUI::GLGizmoSeam::on_render_input_window().
init()
bool Slic3r::GUI::GLGizmoBase::init () inline inherited
{ return on_init(); }
References Slic3r::GUI::GLGizmoBase::on_init().
init_connector_shapes()
void Slic3r::GUI::GLGizmoAdvancedCut::init_connector_shapes () private
{
    for (const CutConnectorType &type : {CutConnectorType::Dowel, CutConnectorType::Plug})
        for (const CutConnectorStyle &style : {CutConnectorStyle::Frustum, CutConnectorStyle::Prizm})
            for (const CutConnectorShape &shape : {CutConnectorShape::Circle, CutConnectorShape::Hexagon, CutConnectorShape::Square, CutConnectorShape::Triangle}) {
                const CutConnectorAttributes attribs = {type, style, shape};
                const indexed_triangle_set   its     = ModelObject::get_connector_mesh(attribs);
                m_shapes[attribs].init_from(its);
            }
}
References Slic3r::Circle, Slic3r::Dowel, Slic3r::Frustum, Slic3r::ModelObject::get_connector_mesh(), Slic3r::Hexagon, m_shapes, Slic3r::Plug, Slic3r::Prizm, Slic3r::Square, style, and Slic3r::Triangle.
Referenced by on_init().
init_connectors_input_window_data()
void Slic3r::GUI::GLGizmoAdvancedCut::init_connectors_input_window_data () private
{
    CutConnectors &connectors = m_c->selection_info()->model_object()->cut_connectors;
    float connectors_cap    = m_imgui->calc_text_size(_L("Connectors")).x;
    float type_cap          = m_imgui->calc_text_size(_L("Type")).x;
    float style_cap         = m_imgui->calc_text_size(_L("Style")).x;
    float shape_cap         = m_imgui->calc_text_size(_L("Shape")).x;
    float depth_ratio_cap   = m_imgui->calc_text_size(_L("Depth ratio")).x;
    float size_cap          = m_imgui->calc_text_size(_L("Size")).x;
    float max_lable_size = std::max(std::max(std::max(connectors_cap, type_cap), std::max(style_cap, shape_cap)), std::max(depth_ratio_cap, size_cap));
    m_label_width   = double(max_lable_size + 3 + ImGui::GetStyle().WindowPadding.x);
    m_control_width  = m_imgui->get_font_size() * 9.f;
    m_editing_window_width = 1.45 * m_control_width + 11;
    if (m_connectors_editing && m_selected_count > 0) {
        float             depth_ratio           {UndefFloat};
        float             depth_ratio_tolerance {UndefFloat};
        float             radius                {UndefFloat};
        float             radius_tolerance      {UndefFloat};
        CutConnectorType  type{CutConnectorType::Undef};
        CutConnectorStyle style{CutConnectorStyle::Undef};
        CutConnectorShape shape{CutConnectorShape::Undef};
        bool is_init = false;
        for (size_t idx = 0; idx < m_selected.size(); idx++)
            if (m_selected[idx]) {
                const CutConnector &connector = connectors[idx];
                if (!is_init) {
                    depth_ratio           = connector.height;
                    depth_ratio_tolerance = connector.height_tolerance;
                    radius                = connector.radius;
                    radius_tolerance      = connector.radius_tolerance;
                    type                  = connector.attribs.type;
                    style                 = connector.attribs.style;
                    shape                 = connector.attribs.shape;
                    if (m_selected_count == 1) break;
                    is_init = true;
                } else {
                    if (!is_approx(depth_ratio, connector.height))
                        depth_ratio = UndefFloat;
                    if (!is_approx(depth_ratio_tolerance, connector.height_tolerance))
                        depth_ratio_tolerance = UndefFloat;
                    if (!is_approx(radius, connector.radius))
                        radius = UndefFloat;
                    if (!is_approx(radius_tolerance, connector.radius_tolerance))
                        radius_tolerance = UndefFloat;
                    if (type != connector.attribs.type)
                        type = CutConnectorType::Undef;
                    if (style != connector.attribs.style)
                        style = CutConnectorStyle::Undef;
                    if (shape != connector.attribs.shape)
                        shape = CutConnectorShape::Undef;
                }
            }
        m_connector_depth_ratio           = depth_ratio;
        m_connector_depth_ratio_tolerance = depth_ratio_tolerance;
        m_connector_size                  = 2.f * radius;
        m_connector_size_tolerance        = radius_tolerance;
        m_connector_type                  = type;
        m_connector_style                 = size_t(style);
        m_connector_shape_id              = size_t(shape);
    }
}
References _L, Slic3r::CutConnector::attribs, Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::ModelObject::cut_connectors, Slic3r::GUI::ImGuiWrapper::get_font_size(), ImGui::GetStyle(), Slic3r::CutConnector::height, Slic3r::CutConnector::height_tolerance, Slic3r::is_approx(), Slic3r::GUI::GLGizmoBase::m_c, m_connector_depth_ratio, m_connector_depth_ratio_tolerance, m_connector_shape_id, m_connector_size, m_connector_size_tolerance, m_connector_style, m_connector_type, m_connectors_editing, m_control_width, m_editing_window_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_label_width, m_selected, m_selected_count, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::CutConnector::radius, Slic3r::CutConnector::radius_tolerance, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::CutConnectorAttributes::shape, Slic3r::CutConnectorAttributes::style, style, Slic3r::CutConnectorAttributes::type, Slic3r::Undef, Slic3r::GUI::UndefFloat, and ImVec2::x.
Referenced by on_render_input_window().
is_activable()
bool Slic3r::GUI::GLGizmoBase::is_activable () const inline inherited
{ return on_is_activable(); }
References Slic3r::GUI::GLGizmoBase::on_is_activable().
is_conflict_for_connector()
bool Slic3r::GUI::GLGizmoAdvancedCut::is_conflict_for_connector (size_t idx, const CutConnectors & connectors, const Vec3d cur_pos) private
{
    if (is_outside_of_cut_contour(idx, connectors, cur_pos))
        return true;
    const CutConnector &cur_connector = connectors[idx];
    Transform3d translate_tf = Transform3d::Identity();
    translate_tf.translate(cur_pos);
    Transform3d scale_tf = Transform3d::Identity();
    scale_tf.scale(Vec3f(cur_connector.radius, cur_connector.radius, cur_connector.height).cast<double>());
    const Transform3d   matrix  = translate_tf * m_rotate_matrix * scale_tf;
    const BoundingBoxf3 cur_tbb = m_shapes[cur_connector.attribs].get_bounding_box().transformed(matrix);
    // check if connector's bounding box is inside the object's bounding box
    if (!bounding_box().contains(cur_tbb)) {
        m_info_stats.outside_bb++;
        return true;
    }
    // check if connectors are overlapping
    for (size_t i = 0; i < connectors.size(); ++i) {
        if (i == idx) continue;
        const CutConnector &connector = connectors[i];
        if ((connector.pos - cur_connector.pos).norm() < double(connector.radius + cur_connector.radius)) {
            m_info_stats.is_overlap = true;
            return true;
        }
    }
    return false;
}
References Slic3r::CutConnector::attribs, bounding_box(), Slic3r::contains(), Slic3r::CutConnector::height, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics::is_overlap, m_info_stats, m_rotate_matrix, m_shapes, Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics::outside_bb, Slic3r::CutConnector::pos, Slic3r::CutConnector::radius, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale(), and Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate().
Referenced by check_conflict_for_all_connectors(), and render_connectors().
is_dragging()
bool Slic3r::GUI::GLGizmoBase::is_dragging () const inline inherited
{ return m_dragging; }
References Slic3r::GUI::GLGizmoBase::m_dragging.
is_looking_forward()
bool Slic3r::GUI::GLGizmoAdvancedCut::is_looking_forward () const
{
    const Camera &camera = wxGetApp().plater()->get_camera();
    const double  dot    = camera.get_dir_forward().dot(m_cut_plane_normal);
    return dot < 0.05;
}
References Slic3r::dot(), Slic3r::GUI::Camera::get_dir_forward(), and m_cut_plane_normal.
Referenced by on_render_for_picking(), render_connectors(), and update_clipper().
is_outside_of_cut_contour()
bool Slic3r::GUI::GLGizmoAdvancedCut::is_outside_of_cut_contour (size_t idx, const CutConnectors & connectors, const Vec3d cur_pos) private
{
    // check if connector pos is out of clipping plane
    if (m_c->object_clipper() && !m_c->object_clipper()->is_projection_inside_cut(cur_pos)) {
        m_info_stats.outside_cut_contour++;
        return true;
    }
    // check if connector bottom contour is out of clipping plane
    const CutConnector &    cur_connector = connectors[idx];
    const CutConnectorShape shape         = CutConnectorShape(cur_connector.attribs.shape);
    const int   sectorCount = shape == CutConnectorShape::Triangle  ? 3 :
                              shape == CutConnectorShape::Square    ? 4 :
                              shape == CutConnectorShape::Circle    ? 60: // supposably, 60 points are enough for conflict detection
                              shape == CutConnectorShape::Hexagon   ? 6 : 1 ;
    indexed_triangle_set mesh;
    auto &               vertices = mesh.vertices;
    vertices.reserve(sectorCount + 1);
    float fa  = 2 * PI / sectorCount;
    auto  vec = Eigen::Vector2f(0, cur_connector.radius);
    for (float angle = 0; angle < 2.f * PI; angle += fa) {
        Vec2f p = Eigen::Rotation2Df(angle) * vec;
        vertices.emplace_back(Vec3f(p(0), p(1), 0.f));
    }
    Transform3d transform = Transform3d::Identity();
    transform.translate(cur_pos);
    its_transform(mesh, transform * m_rotate_matrix);
    for (auto vertex : vertices) {
        if (m_c->object_clipper() && !m_c->object_clipper()->is_projection_inside_cut(vertex.cast<double>())) {
            m_info_stats.outside_cut_contour++;
            return true;
        }
    }
    return false;
}
References Slic3r::angle(), Slic3r::CutConnector::attribs, Slic3r::Circle, Slic3r::Hexagon, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::is_projection_inside_cut(), its_transform(), Slic3r::GUI::GLGizmoBase::m_c, m_info_stats, m_rotate_matrix, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics::outside_cut_contour, Slic3r::GUI::PI, Slic3r::CutConnector::radius, Slic3r::CutConnectorAttributes::shape, Slic3r::Square, Slic3r::transform(), Slic3r::Triangle, and indexed_triangle_set::vertices.
Referenced by is_conflict_for_connector().
is_selectable()
bool Slic3r::GUI::GLGizmoBase::is_selectable () const inline inherited
{ return on_is_selectable(); }
References Slic3r::GUI::GLGizmoBase::on_is_selectable().
is_selection_changed()
bool Slic3r::GUI::GLGizmoAdvancedCut::is_selection_changed (bool alt_down, bool shift_down) private
{
    if (m_hover_id >= c_connectors_group_id) {
        if (alt_down)
            select_connector(m_hover_id - c_connectors_group_id, false);
        else {
            if (!shift_down) unselect_all_connectors();
            select_connector(m_hover_id - c_connectors_group_id, true);
        }
        return true;
    }
    return false;
}
References Slic3r::GUI::c_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, select_connector(), and unselect_all_connectors().
Referenced by gizmo_event().
load()
void Slic3r::GUI::GLGizmoBase::load (cereal::BinaryInputArchive & ar) inline inherited
{ m_state = On; on_load(ar); }
References Slic3r::GUI::GLGizmoBase::m_state, Slic3r::GUI::GLGizmoBase::On, and Slic3r::GUI::GLGizmoBase::on_load().
load_render_colors()
void Slic3r::GUI::GLGizmoBase::load_render_colors () static inherited
{
    RenderColor::colors[RenderCol_Grabber_X] = IMColor(GLGizmoBase::AXES_COLOR[0]);
    RenderColor::colors[RenderCol_Grabber_Y] = IMColor(GLGizmoBase::AXES_COLOR[1]);
    RenderColor::colors[RenderCol_Grabber_Z] = IMColor(GLGizmoBase::AXES_COLOR[2]);
    RenderColor::colors[RenderCol_Flatten_Plane] = IMColor(GLGizmoBase::FLATTEN_COLOR);
    RenderColor::colors[RenderCol_Flatten_Plane_Hover] = IMColor(GLGizmoBase::FLATTEN_HOVER_COLOR);
}
References Slic3r::GUI::GLGizmoBase::AXES_COLOR, Slic3r::RenderColor::colors, Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR, Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR, Slic3r::IMColor(), RenderCol_Flatten_Plane, RenderCol_Flatten_Plane_Hover, RenderCol_Grabber_X, RenderCol_Grabber_Y, and RenderCol_Grabber_Z.
Referenced by Slic3r::GUI::GLCanvas3D::init().
load_rotoptimize_state()
void Slic3r::GUI::GLGizmoRotate3D::load_rotoptimize_state () private inherited
{
    std::string accuracy_str =
        wxGetApp().app_config->get("sla_auto_rotate", "accuracy");
    std::string method_str =
        wxGetApp().app_config->get("sla_auto_rotate", "method_id");
    if (!accuracy_str.empty()) {
        float accuracy = std::stof(accuracy_str);
        accuracy = std::max(0.f, std::min(accuracy, 1.f));
        m_rotoptimizewin_state.accuracy = accuracy;
    }
    if (!method_str.empty()) {
        int method_id = std::stoi(method_str);
        if (method_id < int(RotoptimizeJob::get_methods_count()))
            m_rotoptimizewin_state.method_id = method_id;
    }
}
References Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::State::accuracy, Slic3r::GUI::RotoptimizeJob::get_methods_count(), Slic3r::GUI::GLGizmoRotate3D::m_rotoptimizewin_state, and Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::State::method_id.
Referenced by Slic3r::GUI::GLGizmoRotate3D::GLGizmoRotate3D().
on_change_color_mode()
virtual void Slic3r::GUI::GLGizmoBase::on_change_color_mode (bool is_dark) inline virtual inherited
{  m_is_dark_mode = is_dark; }
References Slic3r::GUI::GLGizmoBase::m_is_dark_mode.
on_disable_grabber()
virtual void Slic3r::GUI::GLGizmoAdvancedCut::on_disable_grabber (unsigned int id) inline protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
    {
        if (id < 3)
            m_gizmos[id].disable_grabber(0);
        else if (id == 3)
            this->disable_grabber(0);
    }
References Slic3r::GUI::GLGizmoBase::disable_grabber(), and Slic3r::GUI::GLGizmoRotate3D::m_gizmos.
on_enable_grabber()
virtual void Slic3r::GUI::GLGizmoAdvancedCut::on_enable_grabber (unsigned int id) inline protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
    {
        if (id < 3)
            m_gizmos[id].enable_grabber(0);
        else if (id == 3)
            this->enable_grabber(0);
    }
References Slic3r::GUI::GLGizmoBase::enable_grabber(), and Slic3r::GUI::GLGizmoRotate3D::m_gizmos.
on_get_name()
std::string Slic3r::GUI::GLGizmoAdvancedCut::on_get_name () const protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    return (_(L("Cut"))).ToUTF8().data();
}
References _, and L.
Referenced by on_render_input_window().
on_get_requirements()
CommonGizmosDataID Slic3r::GUI::GLGizmoAdvancedCut::on_get_requirements () const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    return CommonGizmosDataID(int(CommonGizmosDataID::SelectionInfo)
        | int(CommonGizmosDataID::InstancesHider)
        | int(CommonGizmosDataID::Raycaster)
        | int(CommonGizmosDataID::ObjectClipper));
}
References Slic3r::GUI::InstancesHider, Slic3r::GUI::ObjectClipper, Slic3r::GUI::Raycaster, and Slic3r::GUI::SelectionInfo.
on_init()
bool Slic3r::GUI::GLGizmoAdvancedCut::on_init () protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    if (!GLGizmoRotate3D::on_init())
        return false;
    m_shortcut_key = WXK_CONTROL_C;
    // initiate info shortcuts
    const wxString ctrl  = GUI::shortkey_ctrl_prefix();
    const wxString alt   = GUI::shortkey_alt_prefix();
    const wxString shift = "Shift+";
    m_shortcuts.push_back(std::make_pair(_L("Left click"), _L("Add connector")));
    m_shortcuts.push_back(std::make_pair(_L("Right click"), _L("Remove connector")));
    m_shortcuts.push_back(std::make_pair(_L("Drag"), _L("Move connector")));
    m_shortcuts.push_back(std::make_pair(shift + _L("Left click"), _L("Add connector to selection")));
    m_shortcuts.push_back(std::make_pair(alt + _L("Left click"), _L("Remove connector from selection")));
    m_shortcuts.push_back(std::make_pair(ctrl + "A", _L("Select all connectors")));
    init_connector_shapes();
    return true;
}
References _L, Slic3r::GUI::ctrl, init_connector_shapes(), Slic3r::GUI::GLGizmoBase::m_shortcut_key, m_shortcuts, Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::shortkey_alt_prefix(), and Slic3r::GUI::shortkey_ctrl_prefix().
on_is_activable()
bool Slic3r::GUI::GLGizmoAdvancedCut::on_is_activable () const protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    const Selection& selection = m_parent.get_selection();
    return selection.is_single_full_instance() && !selection.is_wipe_tower();
}
References Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::Selection::is_single_full_instance(), Slic3r::GUI::Selection::is_wipe_tower(), and Slic3r::GUI::GLGizmoBase::m_parent.
on_is_selectable()
virtual bool Slic3r::GUI::GLGizmoBase::on_is_selectable () const inline protected virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoHollow, Slic3r::GUI::GLGizmoMmuSegmentation, Slic3r::GUI::GLGizmoPainterBase, Slic3r::GUI::GLGizmoSimplify, and Slic3r::GUI::GLGizmoSlaSupports.
{ return true; }
Referenced by Slic3r::GUI::GLGizmoBase::is_selectable().
on_key()
bool Slic3r::GUI::GLGizmoAdvancedCut::on_key (wxKeyEvent & evt)
{
    bool ctrl_down = evt.GetModifiers() & wxMOD_CONTROL;
    if (evt.GetKeyCode() == WXK_DELETE) {
        return delete_selected_connectors();
    }
    else if (ctrl_down
        && (evt.GetKeyCode() == 'A' || evt.GetKeyCode() == 'a'))
    {
        select_all_connectors();
        return true;
    }
    return false;
}
References delete_selected_connectors(), and select_all_connectors().
on_load()
void Slic3r::GUI::GLGizmoAdvancedCut::on_load (cereal::BinaryInputArchive & ar) override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar(m_keep_upper, m_keep_lower, m_rotate_lower, m_rotate_upper, m_connectors_editing,
        m_cut_plane_points[0], m_cut_plane_points[1], m_cut_plane_points[2], m_cut_plane_points[3]);
    m_parent.request_extra_frame();
}
References m_connectors_editing, m_cut_plane_points, m_keep_lower, m_keep_upper, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_lower, m_rotate_upper, and Slic3r::GUI::GLCanvas3D::request_extra_frame().
on_render()
void Slic3r::GUI::GLGizmoAdvancedCut::on_render () protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    update_clipper();
    if (m_connectors_editing) {
        render_connectors();
    }
    // render_clipper_cut for get the cut plane result
    render_clipper_cut();
    if(!m_connectors_editing) {
        check_conflict_for_all_connectors();
        render_cut_plane_and_grabbers();
    }
    render_cut_line();
}
References check_conflict_for_all_connectors(), m_connectors_editing, render_clipper_cut(), render_connectors(), render_cut_line(), render_cut_plane_and_grabbers(), and update_clipper().
Referenced by set_connectors_editing().
on_render_for_picking()
void Slic3r::GUI::GLGizmoAdvancedCut::on_render_for_picking () protected virtual
Implements Slic3r::GUI::GLGizmoBase.
{
    GLGizmoRotate3D::on_render_for_picking();
    glsafe(::glDisable(GL_DEPTH_TEST));
    BoundingBoxf3 box = m_parent.get_selection().get_bounding_box();
#if ENABLE_FIXED_GRABBER
    float mean_size = (float)(GLGizmoBase::Grabber::FixedGrabberSize);
#else
    float mean_size = (float)((box.size().x() + box.size().y() + box.size().z()) / 3.0);
#endif
    std::array<float, 4> color = picking_color_component(0);
    m_move_grabber.color[0] = color[0];
    m_move_grabber.color[1] = color[1];
    m_move_grabber.color[2] = color[2];
    m_move_grabber.color[3] = color[3];
    m_move_grabber.render_for_picking(mean_size);
    glsafe(::glEnable(GL_DEPTH_TEST));
    auto inst_id = m_c->selection_info()->get_active_instance();
    if (inst_id < 0)
        return;
    const ModelObject *mo      = m_c->selection_info()->model_object();
    const ModelInstance *mi              = mo->instances[inst_id];
    const Vec3d &        instance_offset = mi->get_offset();
    const double         sla_shift       = double(m_c->selection_info()->get_sla_shift());
    const CutConnectors &connectors = mo->cut_connectors;
    for (int i = 0; i < connectors.size(); ++i) {
        CutConnector connector = connectors[i];
        Vec3d pos = connector.pos + instance_offset + sla_shift * Vec3d::UnitZ();
        float height = connector.height;
        const Camera &camera = wxGetApp().plater()->get_camera();
        if (connector.attribs.type == CutConnectorType::Dowel && connector.attribs.style == CutConnectorStyle::Prizm) {
            pos -= height * m_cut_plane_normal;
            height *= 2;
        } else if (!is_looking_forward())
            pos -= 0.05 * m_cut_plane_normal;
        Transform3d translate_tf = Transform3d::Identity();
        translate_tf.translate(pos);
        Transform3d scale_tf = Transform3d::Identity();
        scale_tf.scale(Vec3f(connector.radius, connector.radius, height).cast<double>());
        const Transform3d view_model_matrix = translate_tf * m_rotate_matrix * scale_tf;
        std::array<float, 4> color = picking_color_component(i+1);
        render_connector_model(m_shapes[connectors[i].attribs], color, view_model_matrix, true);
    }
}
References Slic3r::CutConnector::attribs, Slic3r::GUI::GLGizmoBase::Grabber::color, Slic3r::ModelObject::cut_connectors, Slic3r::Dowel, Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::Selection::get_bounding_box(), Slic3r::ModelInstance::get_offset(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), glsafe, Slic3r::CutConnector::height, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::ModelObject::instances, is_looking_forward(), Slic3r::GUI::GLGizmoBase::m_c, m_cut_plane_normal, m_move_grabber, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_matrix, m_shapes, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLGizmoRotate3D::on_render_for_picking(), Slic3r::GUI::GLGizmoBase::picking_color_component(), Slic3r::CutConnector::pos, Slic3r::Prizm, Slic3r::CutConnector::radius, render_connector_model(), Slic3r::GUI::GLGizmoBase::Grabber::render_for_picking(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::BoundingBox3Base< PointClass >::size(), Slic3r::CutConnectorAttributes::style, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), and Slic3r::CutConnectorAttributes::type.
on_render_input_window()
void Slic3r::GUI::GLGizmoAdvancedCut::on_render_input_window (float x, float y, float bottom_limit) protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    GizmoImguiSetNextWIndowPos(x, y, ImGuiCond_Always, 0.0f, 0.0f);
    ImGuiWrapper::push_toolbar_style(m_parent.get_scale());
    GizmoImguiBegin(on_get_name(),
                    ImGuiWindowFlags_AlwaysAutoResize | ImGuiWindowFlags_NoMove | ImGuiWindowFlags_NoResize | ImGuiWindowFlags_NoCollapse | ImGuiWindowFlags_NoTitleBar);
    if (m_connectors_editing) {
        init_connectors_input_window_data();
        render_connectors_input_window(x, y, bottom_limit);
    }
    else
        render_cut_plane_input_window(x, y, bottom_limit);
    render_input_window_warning();
    GizmoImguiEnd();
    ImGuiWrapper::pop_toolbar_style();
}
References Slic3r::GUI::GLCanvas3D::get_scale(), Slic3r::GUI::GLGizmoBase::GizmoImguiBegin(), Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), ImGuiCond_Always, ImGuiWindowFlags_AlwaysAutoResize, ImGuiWindowFlags_NoCollapse, ImGuiWindowFlags_NoMove, ImGuiWindowFlags_NoResize, ImGuiWindowFlags_NoTitleBar, init_connectors_input_window_data(), m_connectors_editing, Slic3r::GUI::GLGizmoBase::m_parent, on_get_name(), Slic3r::GUI::ImGuiWrapper::pop_toolbar_style(), Slic3r::GUI::ImGuiWrapper::push_toolbar_style(), render_connectors_input_window(), render_cut_plane_input_window(), and render_input_window_warning().
on_save()
void Slic3r::GUI::GLGizmoAdvancedCut::on_save (cereal::BinaryOutputArchive & ar) const override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    ar(m_keep_upper, m_keep_lower, m_rotate_lower, m_rotate_upper, m_connectors_editing,
        m_cut_plane_points[0], m_cut_plane_points[1], m_cut_plane_points[2], m_cut_plane_points[3]);
}
References m_connectors_editing, m_cut_plane_points, m_keep_lower, m_keep_upper, m_rotate_lower, and m_rotate_upper.
on_set_hover_id()
virtual void Slic3r::GUI::GLGizmoAdvancedCut::on_set_hover_id () inline protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
    {
        for (int i = 0; i < 3; ++i)
            m_gizmos[i].set_hover_id((m_hover_id == i) ? 0 : -1);
    }
References Slic3r::GUI::GLGizmoRotate3D::m_gizmos, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::set_hover_id().
on_set_state()
void Slic3r::GUI::GLGizmoAdvancedCut::on_set_state () protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    GLGizmoRotate3D::on_set_state();
    // Reset m_cut_z on gizmo activation
    if (get_state() == On) {
        m_connectors_editing = false;
        reset_cut_plane();
    }
    else if (get_state() == Off) {
        clear_selection();
        m_c->object_clipper()->release();
    }
}
References clear_selection(), Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::GLGizmoBase::Off, Slic3r::GUI::GLGizmoBase::On, Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::CommonGizmosDataBase::release(), and reset_cut_plane().
on_start_dragging()
void Slic3r::GUI::GLGizmoAdvancedCut::on_start_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    for (auto gizmo : m_gizmos) {
        if (m_hover_id == gizmo.get_group_id()) {
            gizmo.start_dragging();
            return;
        }
    }
    if (m_hover_id != get_group_id())
        return;
    const Selection& selection = m_parent.get_selection();
    const BoundingBoxf3& box = selection.get_bounding_box();
    m_start_movement = m_movement;
    m_start_height = m_height;
    m_drag_pos = m_move_grabber.center;
    if (m_hover_id >= c_connectors_group_id)
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Move connector");
}
References Slic3r::GUI::c_connectors_group_id, Slic3r::GUI::GLGizmoBase::Grabber::center, Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::GLGizmoBase::get_group_id(), Slic3r::GUI::GLCanvas3D::get_selection(), m_drag_pos, Slic3r::GUI::GLGizmoRotate3D::m_gizmos, m_height, Slic3r::GUI::GLGizmoBase::m_hover_id, m_move_grabber, m_movement, Slic3r::GUI::GLGizmoBase::m_parent, m_start_height, m_start_movement, and Slic3r::GUI::plater().
on_stop_dragging()
void Slic3r::GUI::GLGizmoAdvancedCut::on_stop_dragging () override protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    if (m_hover_id == X || m_hover_id == Y || m_hover_id == Z) {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Rotate cut plane");
    } else if (m_hover_id == c_connectors_group_id - 1) {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Move cut plane");
    }
}
References Slic3r::GUI::c_connectors_group_id, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GUI::plater(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
on_update()
void Slic3r::GUI::GLGizmoAdvancedCut::on_update (const UpdateData & data) protected virtual
Reimplemented from Slic3r::GUI::GLGizmoBase.
{
    GLGizmoRotate3D::on_update(data);
    Vec3d rotation;
    for (int i = 0; i < 3; i++)
    {
        rotation(i) = m_gizmos[i].get_angle();
        if (rotation(i) < 0)
            rotation(i) = 2*PI + rotation(i);
    }
    m_rotation = rotation;
    //m_move_grabber.angles = m_current_base_rotation + m_rotation;
    if (m_hover_id == get_group_id()) {
        double move = calc_projection(data.mouse_ray);
        set_movement(m_start_movement + move);
        Vec3d plane_normal = get_plane_normal();
        m_height = m_start_height + plane_normal(2) * move;
    }
    // dragging connectors
    if (m_connectors_editing && m_hover_id >= c_connectors_group_id) {
        CutConnectors &connectors = m_c->selection_info()->model_object()->cut_connectors;
        Vec3d          pos;
        Vec3d          pos_world;
        if (unproject_on_cut_plane(data.mouse_pos.cast<double>(), pos, pos_world)) {
            connectors[m_hover_id - c_connectors_group_id].pos = pos;
        }
    }
}
References Slic3r::GUI::c_connectors_group_id, calc_projection(), Slic3r::ModelObject::cut_connectors, Slic3r::GUI::GLGizmoBase::get_group_id(), get_plane_normal(), Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, Slic3r::GUI::GLGizmoRotate3D::m_gizmos, m_height, Slic3r::GUI::GLGizmoBase::m_hover_id, m_rotation, m_start_height, m_start_movement, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::GLGizmoBase::UpdateData::mouse_pos, Slic3r::GUI::GLGizmoBase::UpdateData::mouse_ray, Slic3r::GUI::GLGizmoRotate3D::on_update(), Slic3r::GUI::PI, Slic3r::GUI::CommonGizmosDataPool::selection_info(), set_movement(), and unproject_on_cut_plane().
perform_cut()
void Slic3r::GUI::GLGizmoAdvancedCut::perform_cut (const Selection & selection) private
{
    if (!can_perform_cut())
        return;
    const int instance_idx = selection.get_instance_idx();
    const int object_idx = selection.get_object_idx();
    wxCHECK_RET(instance_idx >= 0 && object_idx >= 0, "GLGizmoAdvancedCut: Invalid object selection");
    // m_cut_z is the distance from the bed. Subtract possible SLA elevation.
    const GLVolume* first_glvolume = selection.get_volume(*selection.get_volume_idxs().begin());
    // perform cut
    {
        Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Cut by Plane");
        ModelObject *mo = wxGetApp().plater()->model().objects[object_idx];
        const bool has_connectors = !mo->cut_connectors.empty();
        bool create_dowels_as_separate_object = false;
        // update connectors pos as offset of its center before cut performing
        apply_connectors_in_model(mo, create_dowels_as_separate_object);
        // BBS: do segment
        if (m_do_segment) {
            wxGetApp().plater()->segment(object_idx, instance_idx, m_segment_smoothing_alpha, m_segment_number);
        } else {
            wxGetApp().plater()->cut(object_idx, instance_idx, get_plane_points_world_coord(),
                                     only_if(m_keep_upper, ModelObjectCutAttribute::KeepUpper) |
                                     only_if(m_keep_lower, ModelObjectCutAttribute::KeepLower) |
                                     only_if(m_cut_to_parts, ModelObjectCutAttribute::CutToParts) |
                                     only_if(m_place_on_cut_upper, ModelObjectCutAttribute::PlaceOnCutUpper) |
                                     only_if(m_place_on_cut_lower, ModelObjectCutAttribute::PlaceOnCutLower) |
                                     only_if(m_rotate_upper, ModelObjectCutAttribute::FlipUpper) |
                                     only_if(m_rotate_lower, ModelObjectCutAttribute::FlipLower) |
                                     only_if(create_dowels_as_separate_object, ModelObjectCutAttribute::CreateDowels) |
                                     only_if(!has_connectors, ModelObjectCutAttribute::InvalidateCutInfo));
        }
    }
}
References apply_connectors_in_model(), can_perform_cut(), Slic3r::CreateDowels, Slic3r::ModelObject::cut_connectors, Slic3r::CutToParts, Slic3r::FlipLower, Slic3r::FlipUpper, Slic3r::GUI::Selection::get_instance_idx(), Slic3r::GUI::Selection::get_object_idx(), get_plane_points_world_coord(), Slic3r::GUI::Selection::get_volume(), Slic3r::GUI::Selection::get_volume_idxs(), Slic3r::InvalidateCutInfo, Slic3r::KeepLower, Slic3r::KeepUpper, m_cut_to_parts, m_do_segment, m_keep_lower, m_keep_upper, m_place_on_cut_lower, m_place_on_cut_upper, m_rotate_lower, m_rotate_upper, m_segment_number, m_segment_smoothing_alpha, Slic3r::only_if(), Slic3r::PlaceOnCutLower, Slic3r::PlaceOnCutUpper, and Slic3r::GUI::plater().
Referenced by render_cut_plane_input_window().
picking_color_component()
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::picking_color_component (unsigned int id) const protected inherited
{
    static const float INV_255 = 1.0f / 255.0f;
    id = BASE_ID - id;
    if (m_group_id > -1)
        id -= m_group_id;
    // color components are encoded to match the calculation of volume_id made into GLCanvas3D::_picking_pass()
    return std::array<float, 4> {
    float((id >> 0) & 0xff) * INV_255, // red
    float((id >> 8) & 0xff) * INV_255, // green
    float((id >> 16) & 0xff) * INV_255, // blue
    float(picking_checksum_alpha_channel(id & 0xff, (id >> 8) & 0xff, (id >> 16) & 0xff))* INV_255 // checksum for validating against unwanted alpha blending and multi sampling
  };
}
References Slic3r::GUI::GLGizmoBase::BASE_ID, Slic3r::GUI::GLGizmoBase::m_group_id, and Slic3r::GUI::picking_checksum_alpha_channel().
Referenced by Slic3r::GUI::GLGizmoText::on_render(), on_render_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking(), Slic3r::GUI::GLGizmoHollow::render_points(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
process_cut_line()
bool Slic3r::GUI::GLGizmoAdvancedCut::process_cut_line (SLAGizmoEventType action, const Vec2d & mouse_position) private
{
    const Camera &camera = wxGetApp().plater()->get_camera();
    Vec3d pt;
    Vec3d dir;
    MeshRaycaster::line_from_mouse_pos_static(mouse_position, Transform3d::Identity(), camera, pt, dir);
    dir.normalize();
    pt += dir; // Move the pt along dir so it is not clipped.
    if (action == SLAGizmoEventType::LeftDown && !cut_line_processing()) {
        m_cut_line_begin = pt;
        m_cut_line_end = pt;
        return true;
    }
    if (cut_line_processing()) {
        m_cut_line_end = pt;
        if (action == SLAGizmoEventType::LeftDown || action == SLAGizmoEventType::LeftUp) {
            Vec3d line_dir = m_cut_line_end - m_cut_line_begin;
            if (line_dir.norm() < 3.0)
                return true;
            Plater::TakeSnapshot snapshot(wxGetApp().plater(), "Cut by line");
            Vec3d              cross_dir = line_dir.cross(dir).normalized();
            Eigen::Quaterniond q;
            Transform3d        m         = Transform3d::Identity();
            m.matrix().block(0, 0, 3, 3) = q.setFromTwoVectors(m_cut_plane_normal, cross_dir).toRotationMatrix();
            m_rotate_matrix = m;
            const ModelObject *  mo = m_c->selection_info()->model_object();
            const ModelInstance *mi = mo->instances[m_c->selection_info()->get_active_instance()];
            Vec3d plane_center = get_plane_center();
            auto update_plane_after_line_cut = [this](const Vec3d &deta_plane_center, const Transform3d& rotate_matrix) {
                Vec3d plane_center = get_plane_center();
                std::array<Vec3d, 4> plane_points_rot;
                for (int i = 0; i < plane_points_rot.size(); i++) {
                    plane_points_rot[i] = m_cut_plane_points[i] - plane_center;
                }
                for (uint32_t i = 0; i < plane_points_rot.size(); ++i) {
                    plane_points_rot[i] = rotate_matrix * plane_points_rot[i];
                }
                for (int i = 0; i < plane_points_rot.size(); i++) {
                    m_cut_plane_points[i] = plane_points_rot[i] + plane_center + deta_plane_center;
                }
            };
            update_plane_after_line_cut(cross_dir * (cross_dir.dot(pt - m_cut_plane_center)), m_rotate_matrix);
            discard_cut_line_processing();
        } else if (action == SLAGizmoEventType::Dragging)
            this->set_dirty();
        return true;
    }
    return false;
}
References cut_line_processing(), discard_cut_line_processing(), Slic3r::GUI::Dragging, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), get_plane_center(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::ModelObject::instances, Slic3r::GUI::LeftDown, Slic3r::GUI::LeftUp, Slic3r::GUI::MeshRaycaster::line_from_mouse_pos_static(), Slic3r::GUI::GLGizmoBase::m_c, m_cut_line_begin, m_cut_line_end, m_cut_plane_center, m_cut_plane_normal, m_cut_plane_points, m_rotate_matrix, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::matrix(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::plater(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::GUI::GLGizmoBase::set_dirty(), and Eigen::QuaternionBase< Derived >::setFromTwoVectors().
Referenced by gizmo_event().
put_connectors_on_cut_plane()
void Slic3r::GUI::GLGizmoAdvancedCut::put_connectors_on_cut_plane (const Vec3d & cp_normal, double cp_offset) private
{
    ModelObject *mo = m_c->selection_info()->model_object();
    if (CutConnectors &connectors = mo->cut_connectors; !connectors.empty()) {
        const float  sla_shift       = m_c->selection_info()->get_sla_shift();
        const Vec3d &instance_offset = mo->instances[m_c->selection_info()->get_active_instance()]->get_offset();
        for (auto &connector : connectors) {
            // convert connetor pos to the world coordinates
            Vec3d pos = connector.pos + instance_offset;
            pos[Z] += sla_shift;
            // scalar distance from point to plane along the normal
            double distance = -cp_normal.dot(pos) + cp_offset;
            // move connector
            connector.pos += distance * cp_normal;
        }
    }
}
References Slic3r::ModelObject::cut_connectors, std::distance(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::ModelObject::instances, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::Z.
Referenced by update_clipper().
render()
void Slic3r::GUI::GLGizmoBase::render () inline inherited
{ m_tooltip.clear(); on_render(); }
References Slic3r::GUI::GLGizmoBase::m_tooltip, and Slic3r::GUI::GLGizmoBase::on_render().
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::render(), and Slic3r::GUI::GLGizmoBase::Grabber::render_for_picking().
render_clipper_cut()
void Slic3r::GUI::GLGizmoAdvancedCut::render_clipper_cut () private
{
    glsafe(::glEnable(GL_DEPTH_TEST));
    m_c->object_clipper()->render_cut();
    glsafe(::glDisable(GL_DEPTH_TEST));
}
References glsafe, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataPool::object_clipper(), and Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::render_cut().
Referenced by on_render().
render_combo()
bool Slic3r::GUI::GLGizmoAdvancedCut::render_combo (const std::string & label, const std::vector< std::string > & lines, size_t & selection_idx) private
{
    ImGui::AlignTextToFramePadding();
    m_imgui->text(label);
    ImGui::SameLine(m_label_width);
    ImGui::PushItemWidth(m_editing_window_width);
    size_t selection_out = selection_idx;
    if (ImGui::BBLBeginCombo(("##" + label).c_str(), lines[selection_idx].c_str(), 0)) {
        for (size_t line_idx = 0; line_idx < lines.size(); ++line_idx) {
            ImGui::PushID(int(line_idx));
            if (ImGui::Selectable("", line_idx == selection_idx))
                selection_out = line_idx;
            ImGui::SameLine();
            ImGui::Text("%s", lines[line_idx].c_str());
            ImGui::PopID();
        }
        ImGui::EndCombo();
    }
    bool is_changed = selection_idx != selection_out;
    selection_idx   = selection_out;
    if (is_changed) update_connector_shape();
    return is_changed;
}
References ImGui::AlignTextToFramePadding(), ImGui::BBLBeginCombo(), ImGui::EndCombo(), m_editing_window_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_label_width, ImGui::PopID(), ImGui::PushID(), ImGui::PushItemWidth(), ImGui::SameLine(), ImGui::Selectable(), ImGui::Text(), Slic3r::GUI::ImGuiWrapper::text(), and update_connector_shape().
Referenced by render_connectors_input_window().
render_connect_type_radio_button()
bool Slic3r::GUI::GLGizmoAdvancedCut::render_connect_type_radio_button (CutConnectorType type) private
{
    ImGui::SameLine(type == CutConnectorType::Plug ? m_label_width : 2 * m_label_width);
    ImGui::PushItemWidth(m_control_width);
    wxString radio_name;
    switch (type) {
    case CutConnectorType::Plug:
        radio_name = _L("Plug");
        break;
    case CutConnectorType::Dowel:
        radio_name = _L("Dowel");
        break;
    default:
        break;
    }
    if (m_imgui->radio_button(radio_name, m_connector_type == type)) {
        m_connector_type = type;
        update_connector_shape();
        return true;
    }
    return false;
}
References _L, Slic3r::Dowel, m_connector_type, m_control_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_label_width, Slic3r::Plug, ImGui::PushItemWidth(), Slic3r::GUI::ImGuiWrapper::radio_button(), ImGui::SameLine(), and update_connector_shape().
Referenced by render_connectors_input_window().
render_connector_model()
void Slic3r::GUI::GLGizmoAdvancedCut::render_connector_model (GLModel & model, const std::array< float, 4 > & color, Transform3d view_model_matrix, bool for_picking = false) private
{
    glPushMatrix();
    GLShaderProgram *shader = nullptr;
    if (for_picking)
        shader = wxGetApp().get_shader("cali");
    else
        shader = wxGetApp().get_shader("gouraud_light");
    if (shader) {
        shader->start_using();
        glsafe(::glMultMatrixd(view_model_matrix.data()));
        model.set_color(-1, color);
        model.render();
        shader->stop_using();
    }
    glPopMatrix();
}
References Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), glsafe, Slic3r::GUI::GLModel::render(), Slic3r::GUI::GLModel::set_color(), Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
Referenced by on_render_for_picking(), and render_connectors().
render_connectors()
void Slic3r::GUI::GLGizmoAdvancedCut::render_connectors () private
{
    ::glEnable(GL_DEPTH_TEST);
    const ModelObject *mo      = m_c->selection_info()->model_object();
    auto               inst_id = m_c->selection_info()->get_active_instance();
    if (inst_id < 0)
        return;
    const CutConnectors &connectors = mo->cut_connectors;
    if (connectors.size() != m_selected.size()) {
        clear_selection();
        m_selected.resize(connectors.size(), false);
    }
    const ModelInstance *mi              = mo->instances[inst_id];
    const Vec3d &        instance_offset = mi->get_offset();
    const double         sla_shift       = double(m_c->selection_info()->get_sla_shift());
    m_has_invalid_connector = false;
    m_info_stats.invalidate();
    ColorRGBA render_color = CONNECTOR_DEF_COLOR;
    for (size_t i = 0; i < connectors.size(); ++i) {
        const CutConnector &connector = connectors[i];
        float height = connector.height;
        // recalculate connector position to world position
        Vec3d pos = connector.pos + instance_offset + sla_shift * Vec3d::UnitZ();
        // First decide about the color of the point.
        const bool conflict_connector = is_conflict_for_connector(i, connectors, pos);
        if (conflict_connector) {
            m_has_invalid_connector = true;
            render_color            = CONNECTOR_ERR_COLOR;
        } else // default connector color
            render_color = connector.attribs.type == CutConnectorType::Dowel ? DOWEL_COLOR : PLAG_COLOR;
        if (!m_connectors_editing)
            render_color = CONNECTOR_ERR_COLOR;
        else if (size_t(m_hover_id - 4) == i)
            render_color = conflict_connector ? HOVERED_ERR_COLOR : connector.attribs.type == CutConnectorType::Dowel ? HOVERED_DOWEL_COLOR : HOVERED_PLAG_COLOR;
        else if (m_selected[i])
            render_color = connector.attribs.type == CutConnectorType::Dowel ? SELECTED_DOWEL_COLOR : SELECTED_PLAG_COLOR;
        const Camera &camera = wxGetApp().plater()->get_camera();
        if (connector.attribs.type == CutConnectorType::Dowel && connector.attribs.style == CutConnectorStyle::Prizm) {
            pos -= height * m_cut_plane_normal;
            height *= 2;
        } else if (!is_looking_forward())
            pos -= 0.05 * m_cut_plane_normal;
        Transform3d translate_tf = Transform3d::Identity();
        translate_tf.translate(pos);
        Transform3d scale_tf = Transform3d::Identity();
        scale_tf.scale(Vec3f(connector.radius, connector.radius, height).cast<double>());
        const Transform3d view_model_matrix = translate_tf * m_rotate_matrix * scale_tf;
        render_connector_model(m_shapes[connector.attribs], render_color, view_model_matrix);
    }
}
References Slic3r::CutConnector::attribs, clear_selection(), Slic3r::GUI::CONNECTOR_DEF_COLOR, Slic3r::GUI::CONNECTOR_ERR_COLOR, Slic3r::ModelObject::cut_connectors, Slic3r::Dowel, Slic3r::GUI::DOWEL_COLOR, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::ModelInstance::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Slic3r::CutConnector::height, Slic3r::GUI::HOVERED_DOWEL_COLOR, Slic3r::GUI::HOVERED_ERR_COLOR, Slic3r::GUI::HOVERED_PLAG_COLOR, Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::ModelObject::instances, Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics::invalidate(), is_conflict_for_connector(), is_looking_forward(), Slic3r::GUI::GLGizmoBase::m_c, m_connectors_editing, m_cut_plane_normal, m_has_invalid_connector, Slic3r::GUI::GLGizmoBase::m_hover_id, m_info_stats, m_rotate_matrix, m_selected, m_shapes, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::GUI::PLAG_COLOR, Slic3r::CutConnector::pos, Slic3r::Prizm, Slic3r::CutConnector::radius, render_connector_model(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::scale(), Slic3r::GUI::SELECTED_DOWEL_COLOR, Slic3r::GUI::SELECTED_PLAG_COLOR, Slic3r::GUI::CommonGizmosDataPool::selection_info(), Slic3r::CutConnectorAttributes::style, Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::translate(), and Slic3r::CutConnectorAttributes::type.
Referenced by on_render().
render_connectors_input_window()
void Slic3r::GUI::GLGizmoAdvancedCut::render_connectors_input_window (float x, float y, float bottom_limit) private
{
    CutConnectors &connectors = m_c->selection_info()->model_object()->cut_connectors;
    // update when change input window
    m_imgui->set_requires_extra_frame();
    ImGui::AlignTextToFramePadding();
    m_imgui->text_colored(ImGuiWrapper::COL_ORANGE_LIGHT, _L("Connectors"));
    m_imgui->disabled_begin(connectors.empty());
    ImGui::SameLine(m_label_width);
    if (render_reset_button("connectors", _u8L("Remove connectors")))
        reset_connectors();
    m_imgui->disabled_end();
    m_imgui->text(_L("Type"));
    ImGui::PushStyleColor(ImGuiCol_CheckMark, ImVec4(0.00f, 0.00f, 0.00f, 1.00f));
    bool type_changed = render_connect_type_radio_button(CutConnectorType::Plug);
    type_changed |= render_connect_type_radio_button(CutConnectorType::Dowel);
    if (type_changed)
        apply_selected_connectors([this, &connectors](size_t idx) { connectors[idx].attribs.type = CutConnectorType(m_connector_type); });
    ImGui::PopStyleColor(1);
    std::vector<std::string> connector_styles = {_u8L("Prizm"), _u8L("Frustum")};
    std::vector<std::string> connector_shapes = { _u8L("Triangle"), _u8L("Square"), _u8L("Hexagon"), _u8L("Circle") };
    m_imgui->disabled_begin(m_connector_type == CutConnectorType::Dowel);
    if (type_changed && m_connector_type == CutConnectorType::Dowel) {
        m_connector_style = size_t(CutConnectorStyle::Prizm);
        apply_selected_connectors([this, &connectors](size_t idx) { connectors[idx].attribs.style = CutConnectorStyle(m_connector_style); });
    }
    ImGuiWrapper::push_combo_style(m_parent.get_scale());
    if (render_combo(_u8L("Style"), connector_styles, m_connector_style))
        apply_selected_connectors([this, &connectors](size_t idx) { connectors[idx].attribs.style = CutConnectorStyle(m_connector_style); });
    m_imgui->disabled_end();
    ImGuiWrapper::pop_combo_style();
    ImGuiWrapper::push_combo_style(m_parent.get_scale());
    if (render_combo(_u8L("Shape"), connector_shapes, m_connector_shape_id))
        apply_selected_connectors([this, &connectors](size_t idx) { connectors[idx].attribs.shape = CutConnectorShape(m_connector_shape_id); });
    ImGuiWrapper::pop_combo_style();
    if (render_slider_double_input(_u8L("Depth ratio"), m_connector_depth_ratio, m_connector_depth_ratio_tolerance))
        apply_selected_connectors([this, &connectors](size_t idx) {
            if (m_connector_depth_ratio > 0)
                connectors[idx].height = m_connector_depth_ratio;
            if (m_connector_depth_ratio_tolerance >= 0)
                connectors[idx].height_tolerance = m_connector_depth_ratio_tolerance;
        });
    if (render_slider_double_input(_u8L("Size"), m_connector_size, m_connector_size_tolerance))
        apply_selected_connectors([this, &connectors](size_t idx) {
            if (m_connector_size > 0)
                connectors[idx].radius = 0.5f * m_connector_size;
            if (m_connector_size_tolerance >= 0)
                connectors[idx].radius_tolerance = m_connector_size_tolerance;
        });
    ImGui::Separator();
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(6.0f, 10.0f));
    float get_cur_y = ImGui::GetContentRegionMax().y + ImGui::GetFrameHeight() + y;
    show_tooltip_information(x, get_cur_y);
    float f_scale = m_parent.get_gizmos_manager().get_layout_scale();
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, ImVec2(6.0f, 4.0f * f_scale));
    ImGui::SameLine();
    if (m_imgui->button(_L("Confirm connectors"))) {
        unselect_all_connectors();
        set_connectors_editing(false);
    }
    ImGui::SameLine(m_label_width + m_editing_window_width - m_imgui->calc_text_size(_L("Cancel")).x - m_imgui->get_style_scaling() * 8);
    if (m_imgui->button(_L("Cancel"))) {
        reset_connectors();
        set_connectors_editing(false);
    }
    ImGui::PopStyleVar(2);
}
References _L, _u8L, ImGui::AlignTextToFramePadding(), apply_selected_connectors(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::COL_ORANGE_LIGHT, Slic3r::ModelObject::cut_connectors, Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), Slic3r::Dowel, Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmosManager::get_layout_scale(), Slic3r::GUI::GLCanvas3D::get_scale(), Slic3r::GUI::ImGuiWrapper::get_style_scaling(), ImGui::GetContentRegionMax(), ImGui::GetFrameHeight(), ImGuiCol_CheckMark, ImGuiStyleVar_FramePadding, ImGuiStyleVar_ItemSpacing, Slic3r::GUI::GLGizmoBase::m_c, m_connector_depth_ratio, m_connector_depth_ratio_tolerance, m_connector_shape_id, m_connector_size, m_connector_size_tolerance, m_connector_style, m_connector_type, m_editing_window_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_label_width, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::Plug, Slic3r::GUI::ImGuiWrapper::pop_combo_style(), ImGui::PopStyleColor(), ImGui::PopStyleVar(), Slic3r::Prizm, Slic3r::GUI::ImGuiWrapper::push_combo_style(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), render_combo(), render_connect_type_radio_button(), render_reset_button(), render_slider_double_input(), reset_connectors(), ImGui::SameLine(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), ImGui::Separator(), set_connectors_editing(), show_tooltip_information(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::ImGuiWrapper::text_colored(), unselect_all_connectors(), and ImVec2::y.
Referenced by on_render_input_window().
render_cut_line()
void Slic3r::GUI::GLGizmoAdvancedCut::render_cut_line () private
{
    if (!cut_line_processing() || m_cut_line_end == Vec3d::Zero())
        return;
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glClear(GL_DEPTH_BUFFER_BIT));
    glsafe(::glColor3f(0.0, 1.0, 0.0));
    glEnable(GL_LINE_STIPPLE);
    ::glBegin(GL_LINES);
    ::glVertex3dv(m_cut_line_begin.data());
    ::glVertex3dv(m_cut_line_end.data());
    glsafe(::glEnd());
    glDisable(GL_LINE_STIPPLE);
}
References cut_line_processing(), Eigen::PlainObjectBase< Derived >::data(), glsafe, m_cut_line_begin, and m_cut_line_end.
Referenced by on_render().
render_cut_plane_and_grabbers()
void Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_and_grabbers () private
{
    const Selection &    selection = m_parent.get_selection();
    const BoundingBoxf3 &box       = selection.get_bounding_box();
    // box center is the coord of object in the world coordinate
    Vec3d object_offset = box.center();
    // plane points is in object coordinate
    Vec3d plane_center = get_plane_center();
    m_cut_plane_center = object_offset + plane_center;
    // rotate plane
    std::array<Vec3d, 4> plane_points_rot;
    {
        for (int i = 0; i < plane_points_rot.size(); i++) {
            plane_points_rot[i] = m_cut_plane_points[i] - plane_center;
        }
        if (m_rotation(0) > EPSILON)
            rotate_x_3d(plane_points_rot, m_rotation(0));
        if (m_rotation(1) > EPSILON)
            rotate_y_3d(plane_points_rot, m_rotation(1));
        if (m_rotation(2) > EPSILON)
            rotate_z_3d(plane_points_rot, m_rotation(2));
        for (int i = 0; i < plane_points_rot.size(); i++) {
            plane_points_rot[i] += plane_center;
        }
    }
    // move plane
    Vec3d plane_normal_rot = calc_plane_normal(plane_points_rot);
    m_cut_plane_normal     = plane_normal_rot;
    for (int i = 0; i < plane_points_rot.size(); i++) {
        plane_points_rot[i] += plane_normal_rot * m_movement;
    }
    // transfer from object coordindate to the world coordinate
    for (Vec3d& point : plane_points_rot) {
        point += object_offset;
    }
    // draw plane
    glsafe(::glEnable(GL_DEPTH_TEST));
    glsafe(::glDisable(GL_CULL_FACE));
    glsafe(::glEnable(GL_BLEND));
    glsafe(::glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA));
    ::glBegin(GL_QUADS);
    ::glColor4f(0.8f, 0.8f, 0.8f, 0.5f);
    for (const Vec3d& point : plane_points_rot) {
        ::glVertex3f(point(0), point(1), point(2));
    }
    glsafe(::glEnd());
    glsafe(::glEnable(GL_CULL_FACE));
    glsafe(::glDisable(GL_BLEND));
    // Draw the grabber and the connecting line
    Vec3d plane_center_rot = calc_plane_center(plane_points_rot);
    m_move_grabber.center = plane_center_rot + plane_normal_rot * Offset;
    // m_move_grabber.angles = m_current_base_rotation + m_rotation;
    glsafe(::glDisable(GL_DEPTH_TEST));
    glsafe(::glLineWidth(m_hover_id != -1 ? 2.0f : 1.5f));
    glsafe(::glColor3f(1.0, 1.0, 0.0));
    glLineStipple(1, 0x0FFF);
    glEnable(GL_LINE_STIPPLE);
    ::glBegin(GL_LINES);
    ::glVertex3dv(plane_center_rot.data());
    ::glVertex3dv(m_move_grabber.center.data());
    glsafe(::glEnd());
    glDisable(GL_LINE_STIPPLE);
    // std::copy(std::begin(GrabberColor), std::end(GrabberColor), m_move_grabber.color);
    // m_move_grabber.color = GrabberColor;
    // m_move_grabber.hover_color = GrabberHoverColor;
    // m_move_grabber.render(m_hover_id == get_group_id(), (float)((box.size()(0) + box.size()(1) + box.size()(2)) / 3.0));
    bool hover = (m_hover_id == get_group_id());
    std::array<float, 4> render_color;
    if (hover) {
        render_color = GrabberHoverColor;
    }
    else
        render_color = GrabberColor;
    const GLModel &cube = m_move_grabber.get_cube();
    // BBS set to fixed size grabber
    // float fullsize = 2 * (dragging ? get_dragging_half_size(size) : get_half_size(size));
    float fullsize = 8.0f;
    if (GLGizmoBase::INV_ZOOM > 0) {
        fullsize = m_move_grabber.FixedGrabberSize * GLGizmoBase::INV_ZOOM;
    }
    const_cast<GLModel*>(&cube)->set_color(-1, render_color);
    glsafe(::glPushMatrix());
    glsafe(::glTranslated(m_move_grabber.center.x(), m_move_grabber.center.y(), m_move_grabber.center.z()));
    glsafe(::glMultMatrixd(m_rotate_matrix.data()));
    glsafe(::glScaled(fullsize, fullsize, fullsize));
    cube.render();
    glsafe(::glPopMatrix());
    // Should be placed at last, because GLGizmoRotate3D clears depth buffer
    set_center(m_cut_plane_center);
    GLGizmoRotate3D::on_render();
}
References calc_plane_center(), calc_plane_normal(), Slic3r::BoundingBox3Base< PointClass >::center(), Slic3r::GUI::GLGizmoBase::Grabber::center, cube(), Eigen::PlainObjectBase< Derived >::data(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::data(), EPSILON, Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::GLGizmoBase::Grabber::get_cube(), Slic3r::GUI::GLGizmoBase::get_group_id(), get_plane_center(), Slic3r::GUI::GLCanvas3D::get_selection(), glsafe, GrabberColor, GrabberHoverColor, Slic3r::GUI::GLGizmoBase::INV_ZOOM, m_cut_plane_center, m_cut_plane_normal, m_cut_plane_points, Slic3r::GUI::GLGizmoBase::m_hover_id, m_move_grabber, m_movement, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_matrix, m_rotation, Offset, Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::rotate_x_3d(), Slic3r::GUI::rotate_y_3d(), Slic3r::GUI::rotate_z_3d(), and Slic3r::GUI::GLGizmoRotate3D::set_center().
Referenced by on_render().
render_cut_plane_input_window()
void Slic3r::GUI::GLGizmoAdvancedCut::render_cut_plane_input_window (float x, float y, float bottom_limit) private
{
    // float unit_size = m_imgui->get_style_scaling() * 48.0f;
    float        space_size        = m_imgui->get_style_scaling() * 8;
    float        movement_cap      = m_imgui->calc_text_size(_L("Movement:")).x;
    float        rotate_cap        = m_imgui->calc_text_size(_L("Rotate")).x;
    float        caption_size      = std::max(movement_cap, rotate_cap) + 2 * space_size;
    bool         imperial_units    = wxGetApp().app_config->get("use_inches") == "1";
    unsigned int current_active_id = ImGui::GetActiveID();
    Vec3d rotation = {Geometry::rad2deg(m_buffered_rotation(0)), Geometry::rad2deg(m_buffered_rotation(1)), Geometry::rad2deg(m_buffered_rotation(2))};
    char  buf[3][64];
    float buf_size[3];
    float vec_max = 0, unit_size = 0;
    for (int i = 0; i < 3; i++) {
        ImGui::DataTypeFormatString(buf[i], IM_ARRAYSIZE(buf[i]), ImGuiDataType_Double, (void *) &rotation[i], "%.2f");
        buf_size[i] = ImGui::CalcTextSize(buf[i]).x;
        vec_max     = std::max(buf_size[i], vec_max);
    }
    float buf_size_max = ImGui::CalcTextSize("-100.00").x;
    if (vec_max < buf_size_max) {
        unit_size = buf_size_max + ImGui::GetStyle().FramePadding.x * 2.0f;
    } else {
        unit_size = vec_max + ImGui::GetStyle().FramePadding.x * 2.0f;
    }
    ImGui::PushItemWidth(caption_size);
    ImGui::Dummy(ImVec2(caption_size, -1));
    ImGui::SameLine(caption_size + 1 * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("X");
    ImGui::SameLine(caption_size + 1 * unit_size + 2 * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("Y");
    ImGui::SameLine(caption_size + 2 * unit_size + 3 * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::TextAlignCenter("Z");
    ImGui::AlignTextToFramePadding();
    // Rotation input box
    ImGui::PushItemWidth(caption_size);
    m_imgui->text(_L("Rotation") + " ");
    ImGui::SameLine(caption_size + 1 * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble("##cut_rotation_x", &rotation[0], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_size + 1 * unit_size + 2 * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble("##cut_rotation_y", &rotation[1], 0.0f, 0.0f, "%.2f");
    ImGui::SameLine(caption_size + 2 * unit_size + 3 * space_size);
    ImGui::PushItemWidth(unit_size);
    ImGui::BBLInputDouble("##cut_rotation_z", &rotation[2], 0.0f, 0.0f, "%.2f");
    if (current_active_id != m_last_active_id) {
        if (std::abs(Geometry::rad2deg(m_rotation(0)) - m_buffered_rotation(0)) > EPSILON || std::abs(Geometry::rad2deg(m_rotation(1)) - m_buffered_rotation(1)) > EPSILON ||
            std::abs(Geometry::rad2deg(m_rotation(2)) - m_buffered_rotation(2)) > EPSILON) {
            m_rotation = m_buffered_rotation;
            m_buffered_rotation.setZero();
            update_plane_points();
            m_parent.post_event(SimpleEvent(wxEVT_PAINT));
        }
    } else {
        m_buffered_rotation(0) = Geometry::deg2rad(rotation(0));
        m_buffered_rotation(1) = Geometry::deg2rad(rotation(1));
        m_buffered_rotation(2) = Geometry::deg2rad(rotation(2));
    }
    ImGui::Separator();
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, ImVec2(4.0f, 10.0f));
    // Movement input box
    double movement = m_movement;
    ImGui::PushItemWidth(caption_size);
    ImGui::AlignTextToFramePadding();
    m_imgui->text(_L("Movement") + " ");
    ImGui::SameLine(caption_size + 1 * space_size);
    ImGui::PushItemWidth(3 * unit_size + 2 * space_size);
    ImGui::BBLInputDouble("##cut_movement", &movement, 0.0f, 0.0f, "%.2f");
    if (current_active_id != m_last_active_id) {
        if (std::abs(m_buffered_movement - m_movement) > EPSILON) {
            m_movement          = m_buffered_movement;
            m_buffered_movement = 0.0;
            // update absolute height
            Vec3d plane_normal = get_plane_normal();
            m_height_delta     = plane_normal(2) * m_movement;
            m_height += m_height_delta;
            m_buffered_height = m_height;
            update_plane_points();
            m_parent.post_event(SimpleEvent(wxEVT_PAINT));
        }
    } else {
        m_buffered_movement = movement;
    }
    // height input box
    double height = m_height;
    ImGui::PushItemWidth(caption_size);
    ImGui::AlignTextToFramePadding();
    // only allow setting height when cut plane is horizontal
    Vec3d plane_normal = get_plane_normal();
    m_imgui->disabled_begin(std::abs(plane_normal(0)) > EPSILON || std::abs(plane_normal(1)) > EPSILON);
    m_imgui->text(_L("Height") + " ");
    ImGui::SameLine(caption_size + 1 * space_size);
    ImGui::PushItemWidth(3 * unit_size + 2 * space_size);
    ImGui::BBLInputDouble("##cut_height", &height, 0.0f, 0.0f, "%.2f");
    if (current_active_id != m_last_active_id) {
        if (std::abs(m_buffered_height - m_height) > EPSILON) {
            m_height_delta = m_buffered_height - m_height;
            m_height       = m_buffered_height;
            update_plane_points();
            m_parent.post_event(SimpleEvent(wxEVT_PAINT));
        }
    } else {
        m_buffered_height = height;
    }
    ImGui::PopStyleVar(1);
    m_imgui->disabled_end();
    CutConnectors &connectors     = m_c->selection_info()->model_object()->cut_connectors;
    const bool     has_connectors = !connectors.empty();
    m_imgui->disabled_begin(!m_keep_upper || !m_keep_lower || m_cut_to_parts);
    if (m_imgui->button(has_connectors ? _L("Edit connectors") : _L("Add connectors"))) set_connectors_editing(true);
    m_imgui->disabled_end();
    ImGui::Separator();
    float label_width = 0;
    for (const wxString& label : {_L("Upper part"), _L("Lower part")}) {
        const float width = m_imgui->calc_text_size(label).x + m_imgui->scaled(1.5f);
        if (label_width < width)
            label_width = width;
    }
    auto render_part_action_line = [this, label_width, &connectors](const wxString &label, const wxString &suffix, bool &keep_part, bool &place_on_cut_part, bool &rotate_part) {
        bool keep = true;
        ImGui::AlignTextToFramePadding();
        m_imgui->text(label);
        ImGui::SameLine(label_width);
        m_imgui->disabled_begin(!connectors.empty() || m_cut_to_parts);
        m_imgui->bbl_checkbox(_L("Keep") + suffix, connectors.empty() ? keep_part : keep);
        m_imgui->disabled_end();
        ImGui::SameLine();
        m_imgui->disabled_begin(!keep_part || m_cut_to_parts);
        if (m_imgui->bbl_checkbox(_L("Place on cut") + suffix, place_on_cut_part))
            rotate_part = false;
        ImGui::SameLine();
        if (m_imgui->bbl_checkbox(_L("Flip") + suffix, rotate_part))
            place_on_cut_part = false;
        m_imgui->disabled_end();
    };
    m_imgui->text(_L("After cut") + ": ");
    render_part_action_line( _L("Upper part"), "##upper", m_keep_upper, m_place_on_cut_upper, m_rotate_upper);
    render_part_action_line( _L("Lower part"), "##lower", m_keep_lower, m_place_on_cut_lower, m_rotate_lower);
    m_imgui->disabled_begin(has_connectors);
    m_imgui->bbl_checkbox(_L("Cut to parts"), m_cut_to_parts);
    if (m_cut_to_parts) {
        m_keep_upper = true;
        m_keep_lower = true;
    }
    m_imgui->disabled_end();
#if 0
    // Auto segment input
    ImGui::PushItemWidth(m_imgui->get_style_scaling() * 150.0);
    m_imgui->checkbox(_L("Auto Segment"), m_do_segment);
    m_imgui->disabled_begin(!m_do_segment);
    ImGui::InputDouble("smoothing_alpha", &m_segment_smoothing_alpha, 0.0f, 0.0f, "%.2f");
    m_segment_smoothing_alpha = std::max(0.1, std::min(100.0, m_segment_smoothing_alpha));
    ImGui::InputInt("segment number", &m_segment_number);
    m_segment_number = std::max(1, m_segment_number);
    m_imgui->disabled_end();
    ImGui::Separator();
#endif
    // Cut button
    m_imgui->disabled_begin(!can_perform_cut());
    if (m_imgui->button(_L("Perform cut")))
        perform_cut(m_parent.get_selection());
    m_imgui->disabled_end();
    ImGui::SameLine();
    const bool reset_clicked = m_imgui->button(_L("Reset"));
    if (reset_clicked) { reset_all(); }
    m_last_active_id = current_active_id;
}
References _L, ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::bbl_checkbox(), ImGui::BBLInputDouble(), Slic3r::GUI::ImGuiWrapper::button(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), ImGui::CalcTextSize(), can_perform_cut(), Slic3r::GUI::ImGuiWrapper::checkbox(), Slic3r::ModelObject::cut_connectors, ImGui::DataTypeFormatString(), Slic3r::Geometry::deg2rad(), Slic3r::GUI::ImGuiWrapper::disabled_begin(), Slic3r::GUI::ImGuiWrapper::disabled_end(), ImGui::Dummy(), EPSILON, ImGuiStyle::FramePadding, get_plane_normal(), Slic3r::GUI::GLCanvas3D::get_selection(), Slic3r::GUI::ImGuiWrapper::get_style_scaling(), ImGui::GetActiveID(), ImGui::GetStyle(), IM_ARRAYSIZE, ImGuiDataType_Double, ImGuiStyleVar_ItemSpacing, ImGui::InputDouble(), ImGui::InputInt(), m_buffered_height, m_buffered_movement, m_buffered_rotation, Slic3r::GUI::GLGizmoBase::m_c, m_cut_to_parts, m_do_segment, m_height, m_height_delta, Slic3r::GUI::GLGizmoBase::m_imgui, m_keep_lower, m_keep_upper, m_last_active_id, m_movement, Slic3r::GUI::GLGizmoBase::m_parent, m_place_on_cut_lower, m_place_on_cut_upper, m_rotate_lower, m_rotate_upper, m_rotation, m_segment_number, m_segment_smoothing_alpha, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), perform_cut(), ImGui::PopStyleVar(), Slic3r::GUI::GLCanvas3D::post_event(), ImGui::PushItemWidth(), ImGui::PushStyleVar(), Slic3r::Geometry::rad2deg(), reset_all(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::scaled(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), ImGui::Separator(), set_connectors_editing(), Eigen::PlainObjectBase< Derived >::setZero(), Slic3r::GUI::ImGuiWrapper::text(), ImGui::TextAlignCenter(), update_plane_points(), and ImVec2::x.
Referenced by on_render_input_window().
render_for_picking()
void Slic3r::GUI::GLGizmoBase::render_for_picking () inline inherited
{ on_render_for_picking(); }
References Slic3r::GUI::GLGizmoBase::on_render_for_picking().
render_grabbers() [1/2]
void Slic3r::GUI::GLGizmoBase::render_grabbers (const BoundingBoxf3 & box) const protected inherited
{
#if ENABLE_FIXED_GRABBER
    render_grabbers((float)(GLGizmoBase::Grabber::FixedGrabberSize));
#else
    render_grabbers((float)((box.size().x() + box.size().y() + box.size().z()) / 3.0));
#endif
}
References Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, Slic3r::GUI::GLGizmoBase::render_grabbers(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::render_grabbers().
render_grabbers() [2/2]
void Slic3r::GUI::GLGizmoBase::render_grabbers (float size) const protected inherited
{
    GLShaderProgram* shader = wxGetApp().get_shader("gouraud_light");
    if (shader == nullptr)
        return;
    shader->start_using();
    shader->set_uniform("emission_factor", 0.1f);
    for (int i = 0; i < (int)m_grabbers.size(); ++i) {
        if (m_grabbers[i].enabled)
            m_grabbers[i].render(m_hover_id == i, size);
    }
    shader->stop_using();
}
References int, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, Slic3r::GLShaderProgram::set_uniform(), size, Slic3r::GLShaderProgram::start_using(), and Slic3r::GLShaderProgram::stop_using().
render_grabbers_for_picking()
void Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking (const BoundingBoxf3 & box) const protected inherited
{
#if ENABLE_FIXED_GRABBER
    float mean_size = (float)(GLGizmoBase::Grabber::FixedGrabberSize);
#else
    float mean_size = (float)((box.size().x() + box.size().y() + box.size().z()) / 3.0);
#endif
    for (unsigned int i = 0; i < (unsigned int)m_grabbers.size(); ++i) {
        if (m_grabbers[i].enabled) {
            std::array<float, 4> color = picking_color_component(i);
            m_grabbers[i].color = color;
            m_grabbers[i].render_for_picking(mean_size);
        }
    }
}
References Slic3r::GUI::GLGizmoBase::Grabber::FixedGrabberSize, int, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::picking_color_component(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), and Slic3r::GUI::GLGizmoScale3D::on_render_for_picking().
render_input_window()
void Slic3r::GUI::GLGizmoBase::render_input_window (float x, float y, float bottom_limit) inherited
{
    on_render_input_window(x, y, bottom_limit);
    if (m_first_input_window_render) {
        // for some reason, the imgui dialogs are not shown on screen in the 1st frame where they are rendered, but show up only with the 2nd rendered frame
        // so, we forces another frame rendering the first time the imgui window is shown
        m_parent.set_as_dirty();
        m_first_input_window_render = false;
    }
}
References Slic3r::GUI::GLGizmoBase::m_first_input_window_render, Slic3r::GUI::GLGizmoBase::m_parent, Slic3r::GUI::GLGizmoBase::on_render_input_window(), and Slic3r::GUI::GLCanvas3D::set_as_dirty().
render_input_window_warning()
void Slic3r::GUI::GLGizmoAdvancedCut::render_input_window_warning () const private
{
    if (m_has_invalid_connector) {
        wxString out = /*wxString(ImGui::WarningMarkerSmall)*/ _L("Warning") + ": " + _L("Invalid connectors detected") + ":";
        if (m_info_stats.outside_cut_contour > size_t(0))
            out += "\n - " + std::to_string(m_info_stats.outside_cut_contour) +
                   (m_info_stats.outside_cut_contour == 1 ? _L("connector is out of cut contour") : _L("connectors are out of cut contour"));
        if (m_info_stats.outside_bb > size_t(0))
            out += "\n - " + std::to_string(m_info_stats.outside_bb) +
                   (m_info_stats.outside_bb == 1 ? _L("connector is out of object") : _L("connectors is out of object"));
        if (m_info_stats.is_overlap)
            out += "\n - " + _L("Some connectors are overlapped");
        m_imgui->text(out);
    }
    if (!m_keep_upper && !m_keep_lower) m_imgui->text(/*wxString(ImGui::WarningMarkerSmall)*/_L("Warning") + ": " + _L("Invalid state. \nNo one part is selected for keep after cut"));
}
References _L, Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics::is_overlap, m_has_invalid_connector, Slic3r::GUI::GLGizmoBase::m_imgui, m_info_stats, m_keep_lower, m_keep_upper, out, Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics::outside_bb, Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics::outside_cut_contour, and Slic3r::GUI::ImGuiWrapper::text().
Referenced by on_render_input_window().
render_reset_button()
bool Slic3r::GUI::GLGizmoAdvancedCut::render_reset_button (const std::string & label_id, const std::string & tooltip) const private
{
    const ImGuiStyle &style = ImGui::GetStyle();
    ImGui::PushStyleVar(ImGuiStyleVar_ItemSpacing, {1, style.ItemSpacing.y});
    ImGui::PushStyleColor(ImGuiCol_Button, {0.25f, 0.25f, 0.25f, 0.0f});
    ImGui::PushStyleColor(ImGuiCol_ButtonHovered, {0.4f, 0.4f, 0.4f, 1.0f});
    ImGui::PushStyleColor(ImGuiCol_ButtonActive, {0.4f, 0.4f, 0.4f, 1.0f});
    bool revert = m_imgui->button(wxString(ImGui::RevertBtn));
    ImGui::PopStyleColor(3);
    if (ImGui::IsItemHovered())
        m_imgui->tooltip(tooltip.c_str(), ImGui::GetFontSize() * 20.0f);
    ImGui::PopStyleVar();
    return revert;
}
References Slic3r::GUI::ImGuiWrapper::button(), ImGui::GetFontSize(), ImGui::GetStyle(), ImGuiCol_Button, ImGuiCol_ButtonActive, ImGuiCol_ButtonHovered, ImGuiStyleVar_ItemSpacing, ImGui::IsItemHovered(), Slic3r::GUI::GLGizmoBase::m_imgui, ImGui::PopStyleColor(), ImGui::PopStyleVar(), ImGui::PushStyleColor(), ImGui::PushStyleVar(), revert(), ImGui::RevertBtn, style, and Slic3r::GUI::ImGuiWrapper::tooltip().
Referenced by render_connectors_input_window().
render_slider_double_input()
bool Slic3r::GUI::GLGizmoAdvancedCut::render_slider_double_input (const std::string & label, float & value_in, float & tolerance_in) private
{
    // -------- [ ] -------- [ ]
    // slider_with + item_in_gap + first_input_width + item_out_gap + slider_with + item_in_gap + second_input_width
    double slider_with          = 0.24 * m_editing_window_width; // m_control_width * 0.35;
    double item_in_gap          = 0.01 * m_editing_window_width;
    double item_out_gap         = 0.01 * m_editing_window_width;
    double first_input_width    = 0.29  * m_editing_window_width;
    double second_input_width   = 0.29  * m_editing_window_width;
    ImGui::AlignTextToFramePadding();
    m_imgui->text(label);
    ImGui::SameLine(m_label_width);
    ImGui::PushItemWidth(slider_with);
    double left_width = m_label_width + slider_with + item_in_gap;
    bool m_imperial_units = false;
    float value = value_in;
    if (m_imperial_units) value *= float(units_mm_to_in);
    float old_val = value;
    constexpr float UndefMinVal = -0.1f;
    const BoundingBoxf3 bbox      = bounding_box();
    float               mean_size = float((bbox.size().x() + bbox.size().y() + bbox.size().z()) / 9.0);
    float               min_size  = value_in < 0.f ? UndefMinVal : 2.f;
    if (m_imperial_units) {
        mean_size *= float(units_mm_to_in);
        min_size *= float(units_mm_to_in);
    }
    std::string format = value_in < 0.f ? " " : m_imperial_units ? "%.4f  " + _u8L("in") : "%.2f  " + _u8L("mm");
    m_imgui->bbl_slider_float_style(("##" + label).c_str(), &value, min_size, mean_size, format.c_str());
    ImGui::SameLine(left_width);
    ImGui::PushItemWidth(first_input_width);
    ImGui::BBLDragFloat(("##input_" + label).c_str(), &value, 0.05f, min_size, mean_size, format.c_str());
    value_in = value * float(m_imperial_units ? units_in_to_mm : 1.0);
    left_width += (first_input_width + item_out_gap);
    ImGui::SameLine(left_width);
    ImGui::PushItemWidth(slider_with);
    float tolerance = tolerance_in;
    if (m_imperial_units)
        tolerance *= float(units_mm_to_in);
    float old_tolerance = tolerance;
    //std::string format_t      = tolerance_in < 0.f ? " " : "%.f %%";
    float       min_tolerance = tolerance_in < 0.f ? UndefMinVal : 0.f;
    m_imgui->bbl_slider_float_style(("##tolerance_" + label).c_str(), &tolerance, min_tolerance, 2.f, format.c_str(), 1.f, true, _L("Tolerance"));
    left_width += (slider_with + item_in_gap);
    ImGui::SameLine(left_width);
    ImGui::PushItemWidth(second_input_width);
    ImGui::BBLDragFloat(("##tolerance_input_" + label).c_str(), &tolerance, 0.05f, min_tolerance, 2.f, format.c_str());
    tolerance_in = tolerance * float(m_imperial_units ? units_in_to_mm : 1.0);
    return !is_approx(old_val, value) || !is_approx(old_tolerance, tolerance);
}
References _L, _u8L, ImGui::AlignTextToFramePadding(), Slic3r::GUI::ImGuiWrapper::bbl_slider_float_style(), ImGui::BBLDragFloat(), bounding_box(), Slic3r::GUI::format(), Slic3r::is_approx(), m_editing_window_width, Slic3r::GUI::GLGizmoBase::m_imgui, m_label_width, ImGui::PushItemWidth(), ImGui::SameLine(), Slic3r::BoundingBox3Base< PointClass >::size(), Slic3r::GUI::ImGuiWrapper::text(), Slic3r::GUI::units_in_to_mm, and Slic3r::GUI::units_mm_to_in.
Referenced by render_connectors_input_window().
reset_all()
void Slic3r::GUI::GLGizmoAdvancedCut::reset_all () private
{
    reset_cut_plane();
    m_keep_upper = true;
    m_keep_lower = true;
    m_cut_to_parts = false;
    m_place_on_cut_upper = true;
    m_place_on_cut_lower = false;
    m_rotate_upper = false;
    m_rotate_lower = false;
}
References m_cut_to_parts, m_keep_lower, m_keep_upper, m_place_on_cut_lower, m_place_on_cut_upper, m_rotate_lower, m_rotate_upper, and reset_cut_plane().
Referenced by render_cut_plane_input_window().
reset_connectors()
void Slic3r::GUI::GLGizmoAdvancedCut::reset_connectors () private
{
    m_c->selection_info()->model_object()->cut_connectors.clear();
    clear_selection();
}
References clear_selection(), Slic3r::ModelObject::cut_connectors, Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), and Slic3r::GUI::CommonGizmosDataPool::selection_info().
Referenced by render_connectors_input_window().
reset_cut_plane()
void Slic3r::GUI::GLGizmoAdvancedCut::reset_cut_plane () private
{
    const Selection& selection = m_parent.get_selection();
    const BoundingBoxf3& box = selection.get_bounding_box();
    const float max_x = box.size()(0) / 2.0 + Margin;
    const float min_x = -max_x;
    const float max_y = box.size()(1) / 2.0 + Margin;
    const float min_y = -max_y;
    m_cut_plane_points[0] = { min_x, min_y, 0 };
    m_cut_plane_points[1] = { max_x, min_y, 0 };
    m_cut_plane_points[2] = { max_x, max_y, 0 };
    m_cut_plane_points[3] = { min_x, max_y, 0 };
    m_movement = 0.0;
    m_height = box.size()[2] / 2.0;
    m_height_delta = 0;
    m_rotation.setZero();
    //m_current_base_rotation.setZero();
    m_rotate_cmds.clear();
    m_buffered_movement = 0.0;
    m_buffered_height = m_height;
    m_buffered_rotation.setZero();
}
References Slic3r::GUI::Selection::get_bounding_box(), Slic3r::GUI::GLCanvas3D::get_selection(), m_buffered_height, m_buffered_movement, m_buffered_rotation, m_cut_plane_points, m_height, m_height_delta, m_movement, Slic3r::GUI::GLGizmoBase::m_parent, m_rotate_cmds, m_rotation, Margin, Eigen::PlainObjectBase< Derived >::setZero(), and Slic3r::BoundingBox3Base< PointClass >::size().
Referenced by on_set_state(), and reset_all().
save()
void Slic3r::GUI::GLGizmoBase::save (cereal::BinaryOutputArchive & ar) const inline inherited
{ on_save(ar); }
References Slic3r::GUI::GLGizmoBase::on_save().
select_all_connectors()
void Slic3r::GUI::GLGizmoAdvancedCut::select_all_connectors () private
{
    std::fill(m_selected.begin(), m_selected.end(), true);
    m_selected_count = int(m_selected.size());
}
References int, m_selected, and m_selected_count.
Referenced by on_key().
select_connector()
void Slic3r::GUI::GLGizmoAdvancedCut::select_connector (int idx, bool select) private
{
    m_selected[idx] = select;
    if (select)
        ++m_selected_count;
    else
        --m_selected_count;
}
References m_selected, and m_selected_count.
Referenced by gizmo_event(), and is_selection_changed().
set_center()
void Slic3r::GUI::GLGizmoRotate3D::set_center (const Vec3d & point) inline inherited
    {
        m_gizmos[X].set_center(point);
        m_gizmos[Y].set_center(point);
        m_gizmos[Z].set_center(point);
    }
References Slic3r::GUI::GLGizmoRotate3D::m_gizmos, Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by render_cut_plane_and_grabbers().
set_common_data_pool()
void Slic3r::GUI::GLGizmoBase::set_common_data_pool (CommonGizmosDataPool * ptr) inline inherited
{ m_c = ptr; }
References Slic3r::GUI::GLGizmoBase::m_c, and ptr.
set_connectors_editing()
void Slic3r::GUI::GLGizmoAdvancedCut::set_connectors_editing (bool connectors_editing) private
{
    m_connectors_editing = connectors_editing;
    // todo: zhimin need a better method
    // after change render mode, need update for scene
    on_render();
}
References m_connectors_editing, and on_render().
Referenced by render_connectors_input_window(), and render_cut_plane_input_window().
set_dirty()
void Slic3r::GUI::GLGizmoBase::set_dirty () protected inherited
{
    m_dirty = true;
}
References Slic3r::GUI::GLGizmoBase::m_dirty.
Referenced by process_cut_line(), and Slic3r::GUI::GLGizmoSimplify::request_rerender().
set_group_id()
void Slic3r::GUI::GLGizmoBase::set_group_id (int id) inline inherited
{ m_group_id = id; }
References Slic3r::GUI::GLGizmoBase::m_group_id.
Referenced by GLGizmoAdvancedCut().
set_highlight_color()
void Slic3r::GUI::GLGizmoBase::set_highlight_color (const std::array< float, 4 > & color) inherited
{
    m_highlight_color = color;
}
References Slic3r::GUI::GLGizmoBase::m_highlight_color.
set_hover_id()
void Slic3r::GUI::GLGizmoBase::set_hover_id (int id) inherited
{
    if (m_grabbers.empty() || (id < (int)m_grabbers.size()))
    {
        m_hover_id = id;
        on_set_hover_id();
    }
}
References Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_set_hover_id().
Referenced by on_set_hover_id(), and Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id().
set_icon_filename()
void Slic3r::GUI::GLGizmoBase::set_icon_filename (const std::string & filename) inherited
{
    m_icon_filename = filename;
}
References Slic3r::GUI::GLGizmoBase::m_icon_filename.
set_movement()
void Slic3r::GUI::GLGizmoAdvancedCut::set_movement (double movement) const
{
    m_movement = movement;
}
References m_movement.
Referenced by on_update().
set_rotation()
void Slic3r::GUI::GLGizmoRotate3D::set_rotation (const Vec3d & rotation) inline inherited
{ m_gizmos[X].set_angle(rotation(0)); m_gizmos[Y].set_angle(rotation(1)); m_gizmos[Z].set_angle(rotation(2)); }
References Slic3r::GUI::GLGizmoRotate3D::m_gizmos, Slic3r::X, Slic3r::Y, and Slic3r::Z.
set_state()
void Slic3r::GUI::GLGizmoBase::set_state (EState state) inline inherited
{ m_state = state; on_set_state(); }
References Slic3r::GUI::GLGizmoBase::m_state, and Slic3r::GUI::GLGizmoBase::on_set_state().
show_tooltip_information()
void Slic3r::GUI::GLGizmoAdvancedCut::show_tooltip_information (float x, float y) protected
{
    float                      caption_max = 0.f;
    for (const auto& short_cut : m_shortcuts) {
        caption_max = std::max(caption_max, m_imgui->calc_text_size(short_cut.first).x);
    }
    ImTextureID normal_id = m_parent.get_gizmos_manager().get_icon_texture_id(GLGizmosManager::MENU_ICON_NAME::IC_TOOLBAR_TOOLTIP);
    ImTextureID hover_id  = m_parent.get_gizmos_manager().get_icon_texture_id(GLGizmosManager::MENU_ICON_NAME::IC_TOOLBAR_TOOLTIP_HOVER);
    caption_max += m_imgui->calc_text_size(": ").x + 35.f;
    float  font_size   = ImGui::GetFontSize();
    ImVec2 button_size = ImVec2(font_size * 1.8, font_size * 1.3);
    ImGui::PushStyleVar(ImGuiStyleVar_FrameBorderSize, 0.0f);
    ImGui::PushStyleVar(ImGuiStyleVar_FramePadding, {0, ImGui::GetStyle().FramePadding.y});
    ImGui::ImageButton3(normal_id, hover_id, button_size);
    if (ImGui::IsItemHovered()) {
        ImGui::BeginTooltip2(ImVec2(x, y));
        auto draw_text_with_caption = [this, &caption_max](const wxString &caption, const wxString &text) {
            m_imgui->text_colored(ImGuiWrapper::COL_ACTIVE, caption);
            ImGui::SameLine(caption_max);
            m_imgui->text_colored(ImGuiWrapper::COL_WINDOW_BG, text);
        };
        for (const auto& short_cut : m_shortcuts)
            draw_text_with_caption(short_cut.first + ": ", short_cut.second);
        ImGui::EndTooltip();
    }
    ImGui::PopStyleVar(2);
}
References ImGui::BeginTooltip2(), Slic3r::GUI::ImGuiWrapper::calc_text_size(), Slic3r::GUI::ImGuiWrapper::COL_ACTIVE, Slic3r::GUI::ImGuiWrapper::COL_WINDOW_BG, ImGui::EndTooltip(), ImGuiStyle::FramePadding, Slic3r::GUI::GLCanvas3D::get_gizmos_manager(), Slic3r::GUI::GLGizmosManager::get_icon_texture_id(), ImGui::GetFontSize(), ImGui::GetStyle(), Slic3r::GUI::GLGizmosManager::IC_TOOLBAR_TOOLTIP, Slic3r::GUI::GLGizmosManager::IC_TOOLBAR_TOOLTIP_HOVER, ImGui::ImageButton3(), ImGuiStyleVar_FrameBorderSize, ImGuiStyleVar_FramePadding, ImGui::IsItemHovered(), Slic3r::GUI::GLGizmoBase::m_imgui, Slic3r::GUI::GLGizmoBase::m_parent, m_shortcuts, ImGui::PopStyleVar(), ImGui::PushStyleVar(), ImGui::SameLine(), Slic3r::GUI::ImGuiWrapper::text_colored(), ImVec2::x, and ImVec2::y.
Referenced by render_connectors_input_window().
start_dragging()
void Slic3r::GUI::GLGizmoBase::start_dragging () inherited
{
    m_dragging = true;
    for (int i = 0; i < (int)m_grabbers.size(); ++i)
    {
        m_grabbers[i].dragging = (m_hover_id == i);
    }
    on_start_dragging();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("this %1%, m_hover_id=%2%\n")%this %m_hover_id;
}
References int, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_start_dragging().
Referenced by gizmo_event(), and Slic3r::GUI::GLGizmoText::gizmo_event().
stop_dragging()
void Slic3r::GUI::GLGizmoBase::stop_dragging () inherited
{
    m_dragging = false;
    for (int i = 0; i < (int)m_grabbers.size(); ++i)
    {
        m_grabbers[i].dragging = false;
    }
    on_stop_dragging();
    //BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << boost::format("this %1%, m_hover_id=%2%\n")%this %m_hover_id;
}
References int, Slic3r::GUI::GLGizmoBase::m_dragging, Slic3r::GUI::GLGizmoBase::m_grabbers, and Slic3r::GUI::GLGizmoBase::on_stop_dragging().
unproject_on_cut_plane()
bool Slic3r::GUI::GLGizmoAdvancedCut::unproject_on_cut_plane (const Vec2d & mouse_pos, Vec3d & pos, Vec3d & pos_world)
{
    const float sla_shift = m_c->selection_info()->get_sla_shift();
    const ModelObject *  mo     = m_c->selection_info()->model_object();
    const ModelInstance *mi     = mo->instances[m_c->selection_info()->get_active_instance()];
    const Camera &       camera = wxGetApp().plater()->get_camera();
    // Calculate intersection with the clipping plane.
    const ClippingPlane *cp = m_c->object_clipper()->get_clipping_plane();
    Vec3d                point;
    Vec3d                direction;
    Vec3d                hit;
    MeshRaycaster::line_from_mouse_pos_static(mouse_pos, Transform3d::Identity(), camera, point, direction);
    Vec3d  normal = -cp->get_normal().cast<double>();
    double den    = normal.dot(direction);
    if (den != 0.) {
        double t = (-cp->get_offset() - normal.dot(point)) / den;
        hit      = (point + t * direction);
    } else
        return false;
    if (!m_c->object_clipper()->is_projection_inside_cut(hit))
        return false;
    // recalculate hit to object's local position
    Vec3d hit_d = hit;
    hit_d -= mi->get_offset();
    hit_d[Z] -= sla_shift;
    // Return both the point and the facet normal.
    pos       = hit_d;
    pos_world = hit;
    return true;
}
References Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_active_instance(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::get_clipping_plane(), Slic3r::GUI::ClippingPlane::get_normal(), Slic3r::ModelInstance::get_offset(), Slic3r::GUI::ClippingPlane::get_offset(), Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::get_sla_shift(), Eigen::Transform< double, 3, Eigen::Affine, Eigen::DontAlign >::Identity(), Slic3r::ModelObject::instances, Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::is_projection_inside_cut(), Slic3r::GUI::MeshRaycaster::line_from_mouse_pos_static(), Slic3r::GUI::GLGizmoBase::m_c, Slic3r::GUI::CommonGizmosDataObjects::SelectionInfo::model_object(), Slic3r::normal(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::GUI::CommonGizmosDataPool::selection_info(), and Slic3r::Z.
Referenced by add_connector(), and on_update().
unselect_all_connectors()
void Slic3r::GUI::GLGizmoAdvancedCut::unselect_all_connectors () private
{
    std::fill(m_selected.begin(), m_selected.end(), false);
    m_selected_count = 0;
    validate_connector_settings();
}
References m_selected, m_selected_count, and validate_connector_settings().
Referenced by add_connector(), gizmo_event(), is_selection_changed(), and render_connectors_input_window().
update()
void Slic3r::GUI::GLGizmoBase::update (const UpdateData & data) inherited
{
    if (m_hover_id != -1)
        on_update(data);
}
References Slic3r::GUI::GLGizmoBase::m_hover_id, and Slic3r::GUI::GLGizmoBase::on_update().
update_clipper()
void Slic3r::GUI::GLGizmoAdvancedCut::update_clipper () private
{
    BoundingBoxf3 box = bounding_box();
    double        radius = box.radius();
    Vec3d         plane_center = m_cut_plane_center;
    Vec3d begin, end = begin = plane_center;
    begin[Z] = box.center().z() - radius;
    end[Z] = box.center().z() + radius;
    double   phi;
    Vec3d    rotation_axis;
    Matrix3d rotation_matrix;
    Geometry::rotation_from_two_vectors(Vec3d::UnitZ(), m_cut_plane_normal, rotation_axis, phi, &rotation_matrix);
    m_rotate_matrix.setIdentity();
    m_rotate_matrix = rotation_matrix * m_rotate_matrix;
    begin = rotate_vec3d_around_vec3d_with_rotate_matrix(begin, plane_center, m_rotate_matrix);
    end   = rotate_vec3d_around_vec3d_with_rotate_matrix(end, plane_center, m_rotate_matrix);
    Vec3d normal = end - begin;
    if (!is_looking_forward()) {
        end = begin = plane_center;
        begin[Z]    = box.center().z() + radius;
        end[Z]      = box.center().z() - radius;
        begin = rotate_vec3d_around_vec3d_with_rotate_matrix(begin, plane_center, m_rotate_matrix);
        end   = rotate_vec3d_around_vec3d_with_rotate_matrix(end, plane_center, m_rotate_matrix);
        // recalculate normal for clipping plane, if camera is looking downward to cut plane
        normal = end - begin;
        if (normal == Vec3d::Zero())
            return;
    }
    // calculate normal and offset for clipping plane
    double dist = (plane_center - begin).norm();
    dist        = std::clamp(dist, 0.0001, normal.norm());
    normal.normalize();
    const double offset = normal.dot(begin) + dist;
    m_c->object_clipper()->set_range_and_pos(normal, offset, dist);
    put_connectors_on_cut_plane(normal, offset);
}
References bounding_box(), Slic3r::BoundingBox3Base< PointClass >::center(), end, is_looking_forward(), Slic3r::GUI::GLGizmoBase::m_c, m_cut_plane_center, m_cut_plane_normal, m_rotate_matrix, Slic3r::normal(), Slic3r::GUI::CommonGizmosDataPool::object_clipper(), Slic3r::offset(), put_connectors_on_cut_plane(), Slic3r::BoundingBox3Base< PointClass >::radius(), Slic3r::GUI::rotate_vec3d_around_vec3d_with_rotate_matrix(), Slic3r::Geometry::rotation_from_two_vectors(), Slic3r::GUI::CommonGizmosDataObjects::ObjectClipper::set_range_and_pos(), Eigen::Transform< _Scalar, _Dim, _Mode, _Options >::setIdentity(), and Slic3r::Z.
Referenced by on_render().
update_connector_shape()
void Slic3r::GUI::GLGizmoAdvancedCut::update_connector_shape () private
{
    CutConnectorAttributes attribs = {m_connector_type, CutConnectorStyle(m_connector_style), CutConnectorShape(m_connector_shape_id)};
    const indexed_triangle_set its = ModelObject::get_connector_mesh(attribs);
    m_connector_mesh.clear();
    m_connector_mesh = TriangleMesh(its);
}
References Slic3r::TriangleMesh::clear(), Slic3r::ModelObject::get_connector_mesh(), m_connector_mesh, m_connector_shape_id, m_connector_style, and m_connector_type.
Referenced by render_combo(), and render_connect_type_radio_button().
update_items_state()
bool Slic3r::GUI::GLGizmoBase::update_items_state () inherited
{
    bool res = m_dirty;
    m_dirty  = false;
    return res;
};
References Slic3r::GUI::GLGizmoBase::m_dirty.
update_plane_points()
void Slic3r::GUI::GLGizmoAdvancedCut::update_plane_points () private
{
    Vec3d plane_center = get_plane_center();
    std::array<Vec3d, 4> plane_points_rot;
    for (int i = 0; i < plane_points_rot.size(); i++) {
        plane_points_rot[i] = m_cut_plane_points[i] - plane_center;
    }
    if (m_rotation(0) > EPSILON) {
        rotate_x_3d(plane_points_rot, m_rotation(0));
        m_rotate_cmds.emplace(m_rotate_cmds.begin(), m_rotation(0), X);
    }
    if (m_rotation(1) > EPSILON) {
        rotate_y_3d(plane_points_rot, m_rotation(1));
        m_rotate_cmds.emplace(m_rotate_cmds.begin(), m_rotation(1), Y);
    }
    if (m_rotation(2) > EPSILON) {
        rotate_z_3d(plane_points_rot, m_rotation(2));
        m_rotate_cmds.emplace(m_rotate_cmds.begin(), m_rotation(2), Z);
    }
    Vec3d plane_normal = calc_plane_normal(plane_points_rot);
    if (m_movement == 0 && m_height_delta != 0)
        m_movement = plane_normal(2) * m_height_delta;// plane_normal.dot(Vec3d(0, 0, m_height_delta))
    for (int i = 0; i < plane_points_rot.size(); i++) {
        m_cut_plane_points[i] = plane_points_rot[i] + plane_center + plane_normal * m_movement;
    }
    //m_current_base_rotation += m_rotation;
    m_rotation.setZero();
    m_movement = 0.0;
    m_height_delta = 0;
}
References calc_plane_normal(), EPSILON, get_plane_center(), m_cut_plane_points, m_height_delta, m_movement, m_rotate_cmds, m_rotation, Slic3r::GUI::rotate_x_3d(), Slic3r::GUI::rotate_y_3d(), Slic3r::GUI::rotate_z_3d(), Eigen::PlainObjectBase< Derived >::setZero(), Slic3r::X, Slic3r::Y, and Slic3r::Z.
Referenced by finish_rotation(), and render_cut_plane_input_window().
update_render_colors()
void Slic3r::GUI::GLGizmoBase::update_render_colors () static inherited
{
    GLGizmoBase::AXES_COLOR = { {
                                GLColor(RenderColor::colors[RenderCol_Grabber_X]),
                                GLColor(RenderColor::colors[RenderCol_Grabber_Y]),
                                GLColor(RenderColor::colors[RenderCol_Grabber_Z])
                                } };
    GLGizmoBase::FLATTEN_COLOR = GLColor(RenderColor::colors[RenderCol_Flatten_Plane]);
    GLGizmoBase::FLATTEN_HOVER_COLOR = GLColor(RenderColor::colors[RenderCol_Flatten_Plane_Hover]);
}
References Slic3r::GUI::GLGizmoBase::AXES_COLOR, Slic3r::RenderColor::colors, Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR, Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR, Slic3r::GLColor(), RenderCol_Flatten_Plane, RenderCol_Flatten_Plane_Hover, RenderCol_Grabber_X, RenderCol_Grabber_Y, and RenderCol_Grabber_Z.
Referenced by Slic3r::GUI::GLCanvas3D::_render_style_editor().
validate_connector_settings()
void Slic3r::GUI::GLGizmoAdvancedCut::validate_connector_settings () private
{
    if (m_connector_depth_ratio < 0.f)
        m_connector_depth_ratio = 3.f;
    if (m_connector_depth_ratio_tolerance < 0.f)
        m_connector_depth_ratio_tolerance = 0.1f;
    if (m_connector_size < 0.f)
        m_connector_size = 2.5f;
    if (m_connector_size_tolerance < 0.f)
        m_connector_size_tolerance = 0.f;
    if (m_connector_type == CutConnectorType::Undef)
        m_connector_type = CutConnectorType::Plug;
    if (m_connector_style == size_t(CutConnectorStyle::Undef))
        m_connector_style = size_t(CutConnectorStyle::Prizm);
    if (m_connector_shape_id == size_t(CutConnectorShape::Undef))
        m_connector_shape_id = size_t(CutConnectorShape::Circle);
}
References Slic3r::Circle, m_connector_depth_ratio, m_connector_depth_ratio_tolerance, m_connector_shape_id, m_connector_size, m_connector_size_tolerance, m_connector_style, m_connector_type, Slic3r::Plug, Slic3r::Prizm, and Slic3r::Undef.
Referenced by unselect_all_connectors().
wants_enter_leave_snapshots()
virtual bool Slic3r::GUI::GLGizmoBase::wants_enter_leave_snapshots () const inline virtual inherited
Reimplemented in Slic3r::GUI::GLGizmoPainterBase, and Slic3r::GUI::GLGizmoSlaSupports.
{ return false; }
Member Data Documentation
AXES_COLOR
std::array< std::array< float, 4 >, 3 > Slic3r::GUI::GLGizmoBase::AXES_COLOR static inherited
Initial value:
= { {
                                                                { 1.0, 0.0f, 0.0f, 1.0f },
                                                                { 0.0f, 1.0f, 0.0f, 1.0f },
                                                                { 0.0f, 0.0f, 1.0f, 1.0f }
                                                                }}
Referenced by Slic3r::GUI::get_color(), Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
AXES_HOVER_COLOR
std::array< std::array< float, 4 >, 3 > Slic3r::GUI::GLGizmoBase::AXES_HOVER_COLOR static inherited
Initial value:
= {{
                                                                { 0.7f, 0.0f, 0.0f, 1.0f },
                                                                { 0.0f, 0.7f, 0.0f, 1.0f },
                                                                { 0.0f, 0.0f, 0.7f, 1.0f }
                                                                }}
Referenced by Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), and Slic3r::GUI::GLGizmoRotate::render_grabber().
BASE_ID
const unsigned int Slic3r::GUI::GLGizmoBase::BASE_ID = 255 * 255 * 254 static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_picking_pass(), and Slic3r::GUI::GLGizmoBase::picking_color_component().
CONSTRAINED_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::CONSTRAINED_COLOR = { 0.5f, 0.5f, 0.5f, 1.0f } static inherited
count
int Slic3r::GUI::GLGizmoBase::count = 0 private inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_count().
DEFAULT_BASE_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_BASE_COLOR = { 0.625f, 0.625f, 0.625f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
DEFAULT_DRAG_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_DRAG_COLOR = { 1.0f, 1.0f, 1.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
DEFAULT_HIGHLIGHT_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::DEFAULT_HIGHLIGHT_COLOR = { 1.0f, 0.38f, 0.0f, 1.0f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
FLATTEN_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::FLATTEN_COLOR = { 0.96f, 0.93f, 0.93f, 0.5f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoFlatten::on_render(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
FLATTEN_HOVER_COLOR
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::FLATTEN_HOVER_COLOR = { 1.0f, 1.0f, 1.0f, 0.75f } static inherited
Referenced by Slic3r::GUI::GLGizmoBase::load_render_colors(), Slic3r::GUI::GLGizmoFlatten::on_render(), and Slic3r::GUI::GLGizmoBase::update_render_colors().
GRABBER_HOVER_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_HOVER_COL = {0.863f, 0.125f, 0.063f, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::Grabber().
GRABBER_NORMAL_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_NORMAL_COL = {1.0f, 1.0f, 1.0f, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoBase::Grabber::Grabber().
GRABBER_UNIFORM_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_UNIFORM_COL = {0, 1.0, 1.0, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
GRABBER_UNIFORM_HOVER_COL
std::array< float, 4 > Slic3r::GUI::GLGizmoBase::GRABBER_UNIFORM_HOVER_COL = {0, 0.7, 0.7, 1.0f} static inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::on_render().
GrabberColor
const std::array< float, 4 > Slic3r::GUI::GLGizmoAdvancedCut::GrabberColor = { 1.0, 1.0, 0.0, 1.0 } static private
Referenced by render_cut_plane_and_grabbers().
GrabberHoverColor
const std::array< float, 4 > Slic3r::GUI::GLGizmoAdvancedCut::GrabberHoverColor = { 0.7, 0.7, 0.0, 1.0} static private
Referenced by render_cut_plane_and_grabbers().
INV_ZOOM
float Slic3r::GUI::GLGizmoBase::INV_ZOOM = 1.0f static inherited
Referenced by Slic3r::GUI::GLCanvas3D::_render_current_gizmo(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoBase::Grabber::render(), render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), and Slic3r::GUI::GLGizmoRotate::render_grabber_extension().
last_input_window_width
float Slic3r::GUI::GLGizmoBase::last_input_window_width = 0 protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), and Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos().
m_base_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_base_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase().
m_buffered_height
double Slic3r::GUI::GLGizmoAdvancedCut::m_buffered_height private
Referenced by render_cut_plane_input_window(), and reset_cut_plane().
m_buffered_movement
double Slic3r::GUI::GLGizmoAdvancedCut::m_buffered_movement private
Referenced by render_cut_plane_input_window(), and reset_cut_plane().
m_buffered_rotation
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::m_buffered_rotation private
Referenced by GLGizmoAdvancedCut(), render_cut_plane_input_window(), and reset_cut_plane().
m_c
CommonGizmosDataPool* Slic3r::GUI::GLGizmoBase::m_c protected inherited
Referenced by Slic3r::GUI::GLGizmoSlaSupports::auto_generate(), check_conflict_for_all_connectors(), delete_selected_connectors(), Slic3r::GUI::GLGizmoHollow::delete_selected_points(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoSlaSupports::editing_mode_apply_changes(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_data(), Slic3r::GUI::GLGizmoPainterBase::get_clipping_plane_in_volume_coordinates(), Slic3r::GUI::GLGizmoHollow::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_config_options(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoPainterBase::get_projected_mouse_positions(), Slic3r::GUI::GLGizmoFdmSupports::get_selection_support_threshold_angle(), gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoHollow::hollow_mesh(), init_connectors_input_window_data(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoMmuSegmentation::init_model_triangle_selectors(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), Slic3r::GUI::GLGizmoHollow::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoSlaSupports::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoPainterBase::is_mesh_point_clipped(), Slic3r::GUI::GLGizmoText::is_mesh_point_clipped(), is_outside_of_cut_contour(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoFdmSupports::need_regenerate_support_volumes(), Slic3r::GUI::GLGizmoMeshBoolean::on_load(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), Slic3r::GUI::GLGizmoSeam::on_set_state(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), on_update(), Slic3r::GUI::GLGizmoHollow::on_update(), Slic3r::GUI::GLGizmoText::on_update(), Slic3r::GUI::GLGizmoFaceDetector::perform_recognition(), process_cut_line(), put_connectors_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::reload_cache(), Slic3r::GUI::GLGizmoSlaSupports::reload_cache(), render_clipper_cut(), render_connectors(), render_connectors_input_window(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), render_cut_plane_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), reset_connectors(), Slic3r::GUI::GLGizmoSlaSupports::reslice_SLA_supports(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoHollow::select_point(), Slic3r::GUI::GLGizmoBase::set_common_data_pool(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), unproject_on_cut_plane(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), update_clipper(), Slic3r::GUI::GLGizmoFdmSupports::update_from_model_object(), Slic3r::GUI::GLGizmoSeam::update_from_model_object(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoFlatten::update_planes(), Slic3r::GUI::GLGizmoText::update_raycast_cache(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), and Slic3r::GUI::GLGizmoText::update_text_positions().
m_cone
GLModel Slic3r::GUI::GLGizmoBase::m_cone protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_connector_depth_ratio
float Slic3r::GUI::GLGizmoAdvancedCut::m_connector_depth_ratio {3.f} private
Referenced by add_connector(), init_connectors_input_window_data(), render_connectors_input_window(), and validate_connector_settings().
m_connector_depth_ratio_tolerance
float Slic3r::GUI::GLGizmoAdvancedCut::m_connector_depth_ratio_tolerance {0.1f} private
Referenced by add_connector(), init_connectors_input_window_data(), render_connectors_input_window(), and validate_connector_settings().
m_connector_mesh
TriangleMesh Slic3r::GUI::GLGizmoAdvancedCut::m_connector_mesh private
Referenced by update_connector_shape().
m_connector_shape_id
size_t Slic3r::GUI::GLGizmoAdvancedCut::m_connector_shape_id private
Referenced by add_connector(), init_connectors_input_window_data(), render_connectors_input_window(), update_connector_shape(), and validate_connector_settings().
m_connector_size
float Slic3r::GUI::GLGizmoAdvancedCut::m_connector_size {2.5f} private
Referenced by add_connector(), init_connectors_input_window_data(), render_connectors_input_window(), and validate_connector_settings().
m_connector_size_tolerance
float Slic3r::GUI::GLGizmoAdvancedCut::m_connector_size_tolerance {0.f} private
Referenced by add_connector(), init_connectors_input_window_data(), render_connectors_input_window(), and validate_connector_settings().
m_connector_style
size_t Slic3r::GUI::GLGizmoAdvancedCut::m_connector_style private
Referenced by add_connector(), init_connectors_input_window_data(), render_connectors_input_window(), update_connector_shape(), and validate_connector_settings().
m_connector_type
CutConnectorType Slic3r::GUI::GLGizmoAdvancedCut::m_connector_type private
Referenced by add_connector(), init_connectors_input_window_data(), render_connect_type_radio_button(), render_connectors_input_window(), update_connector_shape(), and validate_connector_settings().
m_connectors_editing
bool Slic3r::GUI::GLGizmoAdvancedCut::m_connectors_editing {false} private
Referenced by add_connector(), apply_clipping_plane(), can_perform_cut(), gizmo_event(), init_connectors_input_window_data(), on_load(), on_render(), on_render_input_window(), on_save(), on_set_state(), on_update(), render_connectors(), and set_connectors_editing().
m_control_width
double Slic3r::GUI::GLGizmoAdvancedCut::m_control_width { 200.0 } private
Referenced by init_connectors_input_window_data(), and render_connect_type_radio_button().
m_cut_line_begin
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::m_cut_line_begin {Vec3d::Zero()} private
Referenced by cut_line_processing(), discard_cut_line_processing(), process_cut_line(), and render_cut_line().
m_cut_line_end
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::m_cut_line_end {Vec3d::Zero()} private
Referenced by discard_cut_line_processing(), process_cut_line(), and render_cut_line().
m_cut_plane_center
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::m_cut_plane_center {Vec3d::Zero()} private
Referenced by apply_connectors_in_model(), process_cut_line(), render_cut_plane_and_grabbers(), and update_clipper().
m_cut_plane_normal
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::m_cut_plane_normal {Vec3d::UnitZ()} private
Referenced by is_looking_forward(), on_render_for_picking(), process_cut_line(), render_connectors(), render_cut_plane_and_grabbers(), and update_clipper().
m_cut_plane_points
std::array<Vec3d, 4> Slic3r::GUI::GLGizmoAdvancedCut::m_cut_plane_points private
Referenced by GLGizmoAdvancedCut(), calc_plane_center(), get_plane_center(), get_plane_normal(), get_plane_points(), get_plane_points_world_coord(), on_load(), on_save(), process_cut_line(), render_cut_plane_and_grabbers(), reset_cut_plane(), and update_plane_points().
m_cut_to_parts
bool Slic3r::GUI::GLGizmoAdvancedCut::m_cut_to_parts private
Referenced by perform_cut(), render_cut_plane_input_window(), and reset_all().
m_cylinder
GLModel Slic3r::GUI::GLGizmoBase::m_cylinder protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_dirty
bool Slic3r::GUI::GLGizmoBase::m_dirty private inherited
Referenced by Slic3r::GUI::GLGizmoBase::set_dirty(), and Slic3r::GUI::GLGizmoBase::update_items_state().
m_do_segment
bool Slic3r::GUI::GLGizmoAdvancedCut::m_do_segment private
Referenced by perform_cut(), and render_cut_plane_input_window().
m_drag_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_drag_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::on_render(), and Slic3r::GUI::GLGizmoRotate::render_grabber().
m_drag_pos
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::m_drag_pos private
Referenced by calc_projection(), and on_start_dragging().
m_dragging
bool Slic3r::GUI::GLGizmoBase::m_dragging protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::is_dragging(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::stop_dragging().
m_editing_window_width
double Slic3r::GUI::GLGizmoAdvancedCut::m_editing_window_width private
Referenced by init_connectors_input_window_data(), render_combo(), render_connectors_input_window(), and render_slider_double_input().
m_first_input_window_render
bool Slic3r::GUI::GLGizmoBase::m_first_input_window_render protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render_input_window().
m_gizmos
std::vector<GLGizmoRotate> Slic3r::GUI::GLGizmoRotate3D::m_gizmos protected inherited
Referenced by GLGizmoAdvancedCut(), Slic3r::GUI::GLGizmoRotate3D::GLGizmoRotate3D(), finish_rotation(), Slic3r::GUI::GLGizmoRotate3D::get_rotation(), Slic3r::GUI::GLGizmoRotate3D::get_tooltip(), on_disable_grabber(), Slic3r::GUI::GLGizmoRotate3D::on_disable_grabber(), on_enable_grabber(), Slic3r::GUI::GLGizmoRotate3D::on_enable_grabber(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render_for_picking(), on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), on_update(), Slic3r::GUI::GLGizmoRotate3D::on_update(), Slic3r::GUI::GLGizmoRotate3D::set_center(), and Slic3r::GUI::GLGizmoRotate3D::set_rotation().
m_grabbers
std::vector<Grabber> Slic3r::GUI::GLGizmoBase::m_grabbers mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::disable_grabber(), Slic3r::GUI::GLGizmoBase::enable_grabber(), Slic3r::GUI::GLGizmoScale3D::enable_ununiversal_scale(), Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoCut::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoText::on_init(), Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoScale3D::render_grabbers_connection(), Slic3r::GUI::GLGizmoBase::render_grabbers_for_picking(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::stop_dragging().
m_group_id
int Slic3r::GUI::GLGizmoBase::m_group_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_group_id(), Slic3r::GUI::GLGizmoBase::picking_color_component(), and Slic3r::GUI::GLGizmoBase::set_group_id().
m_has_invalid_connector
bool Slic3r::GUI::GLGizmoAdvancedCut::m_has_invalid_connector {false} private
Referenced by can_perform_cut(), check_conflict_for_all_connectors(), render_connectors(), and render_input_window_warning().
m_height
double Slic3r::GUI::GLGizmoAdvancedCut::m_height mutable private
Referenced by on_start_dragging(), on_update(), render_cut_plane_input_window(), and reset_cut_plane().
m_height_delta
double Slic3r::GUI::GLGizmoAdvancedCut::m_height_delta mutable private
Referenced by render_cut_plane_input_window(), reset_cut_plane(), and update_plane_points().
m_highlight_color
std::array<float, 4> Slic3r::GUI::GLGizmoBase::m_highlight_color protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate::render_grabber(), and Slic3r::GUI::GLGizmoBase::set_highlight_color().
m_hover_id
int Slic3r::GUI::GLGizmoBase::m_hover_id protected inherited
Referenced by Slic3r::GUI::GLGizmoScale3D::calc_ratio(), Slic3r::GUI::GLGizmoScale3D::do_scale_along_axis(), Slic3r::GUI::GLGizmoBase::get_hover_id(), Slic3r::GUI::GLGizmoCut::get_tooltip(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoRotate::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), gizmo_event(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), is_selection_changed(), Slic3r::GUI::GLGizmoCut::on_render(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoRotate3D::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), on_set_hover_id(), Slic3r::GUI::GLGizmoHollow::on_set_hover_id(), Slic3r::GUI::GLGizmoRotate3D::on_set_hover_id(), Slic3r::GUI::GLGizmoSlaSupports::on_set_hover_id(), on_start_dragging(), Slic3r::GUI::GLGizmoCut::on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), Slic3r::GUI::GLGizmoHollow::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_start_dragging(), on_stop_dragging(), Slic3r::GUI::GLGizmoHollow::on_stop_dragging(), Slic3r::GUI::GLGizmoRotate3D::on_stop_dragging(), Slic3r::GUI::GLGizmoSlaSupports::on_stop_dragging(), on_update(), Slic3r::GUI::GLGizmoCut::on_update(), Slic3r::GUI::GLGizmoHollow::on_update(), Slic3r::GUI::GLGizmoMove3D::on_update(), Slic3r::GUI::GLGizmoScale3D::on_update(), Slic3r::GUI::GLGizmoSlaSupports::on_update(), render_connectors(), render_cut_plane_and_grabbers(), Slic3r::GUI::GLGizmoRotate::render_grabber(), Slic3r::GUI::GLGizmoMove3D::render_grabber_extension(), Slic3r::GUI::GLGizmoRotate::render_grabber_extension(), Slic3r::GUI::GLGizmoBase::render_grabbers(), Slic3r::GUI::GLGizmoHollow::render_points(), Slic3r::GUI::GLGizmoSlaSupports::render_points(), Slic3r::GUI::GLGizmoBase::set_hover_id(), Slic3r::GUI::GLGizmoBase::start_dragging(), and Slic3r::GUI::GLGizmoBase::update().
m_icon_filename
std::string Slic3r::GUI::GLGizmoBase::m_icon_filename protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_icon_filename(), and Slic3r::GUI::GLGizmoBase::set_icon_filename().
m_imgui
ImGuiWrapper* Slic3r::GUI::GLGizmoBase::m_imgui protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::RotoptimzeWindow::~RotoptimzeWindow(), Slic3r::GUI::GLGizmoSimplify::create_gui_cfg(), Slic3r::GUI::GLGizmoBase::GizmoImguiBegin(), Slic3r::GUI::GLGizmoBase::GizmoImguiEnd(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), init_connectors_input_window_data(), Slic3r::GUI::GLGizmoText::on_init(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoMove3D::on_render_input_window(), Slic3r::GUI::GLGizmoScale3D::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoRotate3D::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), render_combo(), render_connect_type_radio_button(), render_connectors_input_window(), render_cut_plane_input_window(), render_input_window_warning(), render_reset_button(), render_slider_double_input(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), and Slic3r::GUI::GLGizmoText::update_font_texture().
m_info_stats
struct Slic3r::GUI::GLGizmoAdvancedCut::InvalidConnectorsStatistics Slic3r::GUI::GLGizmoAdvancedCut::m_info_stats private
Referenced by check_conflict_for_all_connectors(), is_conflict_for_connector(), is_outside_of_cut_contour(), render_connectors(), and render_input_window_warning().
m_is_dark_mode
bool Slic3r::GUI::GLGizmoBase::m_is_dark_mode = false protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::on_change_color_mode(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoText::push_button_style(), and Slic3r::GUI::GLGizmoText::push_combo_style().
m_keep_lower
bool Slic3r::GUI::GLGizmoAdvancedCut::m_keep_lower private
Referenced by can_perform_cut(), on_load(), on_save(), perform_cut(), render_cut_plane_input_window(), render_input_window_warning(), and reset_all().
m_keep_upper
bool Slic3r::GUI::GLGizmoAdvancedCut::m_keep_upper private
Referenced by can_perform_cut(), on_load(), on_save(), perform_cut(), render_cut_plane_input_window(), render_input_window_warning(), and reset_all().
m_label_width
double Slic3r::GUI::GLGizmoAdvancedCut::m_label_width {150.0} private
Referenced by init_connectors_input_window_data(), render_combo(), render_connect_type_radio_button(), render_connectors_input_window(), and render_slider_double_input().
m_last_active_id
unsigned int Slic3r::GUI::GLGizmoAdvancedCut::m_last_active_id private
Referenced by render_cut_plane_input_window().
m_move_grabber
Grabber Slic3r::GUI::GLGizmoAdvancedCut::m_move_grabber mutable private
Referenced by on_render_for_picking(), on_start_dragging(), and render_cut_plane_and_grabbers().
m_movement
double Slic3r::GUI::GLGizmoAdvancedCut::m_movement mutable private
Referenced by get_movement(), on_start_dragging(), render_cut_plane_and_grabbers(), render_cut_plane_input_window(), reset_cut_plane(), set_movement(), and update_plane_points().
m_object_manipulation
GizmoObjectManipulation* Slic3r::GUI::GLGizmoRotate3D::m_object_manipulation protected inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::on_render_input_window().
m_parent
GLCanvas3D& Slic3r::GUI::GLGizmoBase::m_parent protected inherited
Referenced by add_connector(), Slic3r::GUI::GLGizmoSimplify::apply_simplify(), bounding_box(), Slic3r::GUI::GLGizmoCut::bounding_box(), Slic3r::GUI::GLGizmoPainterBase::bounding_box(), Slic3r::GUI::GLGizmoText::bounding_box(), Slic3r::GUI::GLGizmoSimplify::close(), delete_selected_connectors(), Slic3r::GUI::GLGizmoText::delete_temp_preview_text_volume(), Slic3r::GUI::GLGizmoSlaSupports::disable_editing_mode(), Slic3r::GUI::GLGizmoMeshBoolean::generate_new_volume(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::GUI::GLGizmoText::generate_text_volume(), Slic3r::GUI::GLGizmoSlaSupports::get_data_from_backend(), get_plane_points_world_coord(), Slic3r::GUI::GLGizmoPainterBase::get_projected_height_range(), Slic3r::GUI::GLGizmoText::get_selected_single_volume(), Slic3r::GUI::GLGizmoText::get_text_mesh(), Slic3r::GUI::GLGizmoMove3D::get_tooltip(), Slic3r::GUI::GLGizmoScale3D::get_tooltip(), Slic3r::GUI::GLGizmoHollow::gizmo_event(), Slic3r::GUI::GLGizmoMeshBoolean::gizmo_event(), Slic3r::GUI::GLGizmoPainterBase::gizmo_event(), Slic3r::GUI::GLGizmoSlaSupports::gizmo_event(), Slic3r::GUI::GLGizmoText::gizmo_event(), Slic3r::GUI::GLGizmoBase::GizmoImguiSetNextWIndowPos(), Slic3r::GUI::GLGizmoSlaSupports::has_backend_supports(), Slic3r::GUI::GLGizmoSimplify::init_model(), Slic3r::GUI::GLGizmoFdmSupports::init_print_instance(), on_is_activable(), Slic3r::GUI::GLGizmoCut::on_is_activable(), Slic3r::GUI::GLGizmoFaceDetector::on_is_activable(), Slic3r::GUI::GLGizmoFlatten::on_is_activable(), Slic3r::GUI::GLGizmoHollow::on_is_activable(), Slic3r::GUI::GLGizmoMeshBoolean::on_is_activable(), Slic3r::GUI::GLGizmoMove3D::on_is_activable(), Slic3r::GUI::GLGizmoPainterBase::on_is_activable(), Slic3r::GUI::GLGizmoRotate3D::on_is_activable(), Slic3r::GUI::GLGizmoScale3D::on_is_activable(), Slic3r::GUI::GLGizmoSimplify::on_is_activable(), Slic3r::GUI::GLGizmoSlaSupports::on_is_activable(), Slic3r::GUI::GLGizmoText::on_is_activable(), on_load(), Slic3r::GUI::GLGizmoFdmSupports::on_opening(), Slic3r::GUI::GLGizmoFlatten::on_render(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoMeshBoolean::on_render(), Slic3r::GUI::GLGizmoMove3D::on_render(), Slic3r::GUI::GLGizmoRotate::on_render(), Slic3r::GUI::GLGizmoScale3D::on_render(), Slic3r::GUI::GLGizmoSimplify::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoText::on_render(), on_render_for_picking(), Slic3r::GUI::GLGizmoCut::on_render_for_picking(), Slic3r::GUI::GLGizmoFlatten::on_render_for_picking(), Slic3r::GUI::GLGizmoHollow::on_render_for_picking(), Slic3r::GUI::GLGizmoMove3D::on_render_for_picking(), Slic3r::GUI::GLGizmoRotate::on_render_for_picking(), Slic3r::GUI::GLGizmoScale3D::on_render_for_picking(), Slic3r::GUI::GLGizmoSlaSupports::on_render_for_picking(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), on_render_input_window(), Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window(), Slic3r::GUI::GLGizmoText::on_render_input_window(), Slic3r::GUI::GLGizmoCut::on_render_input_window(), Slic3r::GUI::GLGizmoFaceDetector::on_render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_render_input_window(), Slic3r::GUI::GLGizmoMmuSegmentation::on_render_input_window(), Slic3r::GUI::GLGizmoSeam::on_render_input_window(), Slic3r::GUI::GLGizmoSimplify::on_render_input_window(), Slic3r::GUI::GLGizmoSlaSupports::on_render_input_window(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMmuSegmentation::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoText::on_set_state(), Slic3r::GUI::GLGizmoFdmSupports::on_shutdown(), Slic3r::GUI::GLGizmoMmuSegmentation::on_shutdown(), Slic3r::GUI::GLGizmoSeam::on_shutdown(), on_start_dragging(), Slic3r::GUI::GLGizmoFlatten::on_start_dragging(), Slic3r::GUI::GLGizmoMove3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_start_dragging(), Slic3r::GUI::GLGizmoScale3D::on_start_dragging(), Slic3r::GUI::GLGizmoRotate::on_update(), Slic3r::GUI::GLGizmoText::on_update(), render_connectors_input_window(), Slic3r::GUI::GLGizmoPainterBase::render_cursor(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_circle(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_height_range(), render_cut_plane_and_grabbers(), render_cut_plane_input_window(), Slic3r::GUI::GLGizmoBase::render_input_window(), Slic3r::GUI::GLGizmoFdmSupports::render_painter_gizmo(), Slic3r::GUI::GLGizmoMmuSegmentation::render_painter_gizmo(), Slic3r::GUI::GLGizmoSeam::render_painter_gizmo(), Slic3r::GUI::GLGizmoPainterBase::render_triangles(), Slic3r::GUI::GLGizmoFdmSupports::render_triangles(), Slic3r::GUI::GLGizmoMmuSegmentation::render_triangles(), Slic3r::GUI::GLGizmoSeam::render_triangles(), Slic3r::GUI::GLGizmoSimplify::request_rerender(), reset_cut_plane(), Slic3r::GUI::GLGizmoFdmSupports::run_thread(), Slic3r::GUI::GLGizmoFdmSupports::select_facets_by_angle(), Slic3r::GUI::GLGizmoFdmSupports::show_tooltip_information(), Slic3r::GUI::GLGizmoMmuSegmentation::show_tooltip_information(), Slic3r::GUI::GLGizmoSeam::show_tooltip_information(), show_tooltip_information(), Slic3r::GUI::GLGizmoText::show_tooltip_information(), Slic3r::GUI::GLGizmoSlaSupports::switch_to_editing_mode(), Slic3r::GUI::GLGizmoHollow::unproject_on_mesh(), Slic3r::GUI::GLGizmoSlaSupports::unproject_on_mesh(), Slic3r::GUI::GLGizmoCut::update_contours(), Slic3r::GUI::GLGizmoPainterBase::update_contours(), Slic3r::GUI::GLGizmoText::update_font_texture(), Slic3r::GUI::GLGizmoFdmSupports::update_model_object(), Slic3r::GUI::GLGizmoMmuSegmentation::update_model_object(), Slic3r::GUI::GLGizmoSeam::update_model_object(), Slic3r::GUI::GLGizmoPainterBase::update_raycast_cache(), and Slic3r::GUI::GLGizmoText::update_text_positions().
m_place_on_cut_lower
bool Slic3r::GUI::GLGizmoAdvancedCut::m_place_on_cut_lower {false} private
Referenced by perform_cut(), render_cut_plane_input_window(), and reset_all().
m_place_on_cut_upper
bool Slic3r::GUI::GLGizmoAdvancedCut::m_place_on_cut_upper {true} private
Referenced by perform_cut(), render_cut_plane_input_window(), and reset_all().
m_rotate_cmds
std::vector<Rotate_data> Slic3r::GUI::GLGizmoAdvancedCut::m_rotate_cmds private
Referenced by GLGizmoAdvancedCut(), reset_cut_plane(), and update_plane_points().
m_rotate_lower
bool Slic3r::GUI::GLGizmoAdvancedCut::m_rotate_lower {false} private
Referenced by on_load(), on_save(), perform_cut(), render_cut_plane_input_window(), and reset_all().
m_rotate_matrix
Transform3d Slic3r::GUI::GLGizmoAdvancedCut::m_rotate_matrix {Transform3d::Identity()} private
Referenced by add_connector(), apply_connectors_in_model(), is_conflict_for_connector(), is_outside_of_cut_contour(), on_render_for_picking(), process_cut_line(), render_connectors(), render_cut_plane_and_grabbers(), and update_clipper().
m_rotate_upper
bool Slic3r::GUI::GLGizmoAdvancedCut::m_rotate_upper {false} private
Referenced by on_load(), on_save(), perform_cut(), render_cut_plane_input_window(), and reset_all().
m_rotation
Vec3d Slic3r::GUI::GLGizmoAdvancedCut::m_rotation private
Referenced by GLGizmoAdvancedCut(), on_update(), render_cut_plane_and_grabbers(), render_cut_plane_input_window(), reset_cut_plane(), and update_plane_points().
m_rotoptimizewin_state
RotoptimzeWindow::State Slic3r::GUI::GLGizmoRotate3D::m_rotoptimizewin_state = {} private inherited
Referenced by Slic3r::GUI::GLGizmoRotate3D::load_rotoptimize_state().
m_segment_number
int Slic3r::GUI::GLGizmoAdvancedCut::m_segment_number private
Referenced by perform_cut(), and render_cut_plane_input_window().
m_segment_smoothing_alpha
double Slic3r::GUI::GLGizmoAdvancedCut::m_segment_smoothing_alpha private
Referenced by perform_cut(), and render_cut_plane_input_window().
m_selected
std::vector<bool> Slic3r::GUI::GLGizmoAdvancedCut::m_selected mutable private
Referenced by add_connector(), apply_selected_connectors(), clear_selection(), delete_selected_connectors(), init_connectors_input_window_data(), render_connectors(), select_all_connectors(), select_connector(), and unselect_all_connectors().
m_selected_count
int Slic3r::GUI::GLGizmoAdvancedCut::m_selected_count {0} private
Referenced by add_connector(), clear_selection(), delete_selected_connectors(), init_connectors_input_window_data(), select_all_connectors(), select_connector(), and unselect_all_connectors().
m_shapes
std::map<CutConnectorAttributes, GLModel> Slic3r::GUI::GLGizmoAdvancedCut::m_shapes private
Referenced by init_connector_shapes(), is_conflict_for_connector(), on_render_for_picking(), and render_connectors().
m_shortcut_key
int Slic3r::GUI::GLGizmoBase::m_shortcut_key protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_shortcut_key(), on_init(), Slic3r::GUI::GLGizmoCut::on_init(), Slic3r::GUI::GLGizmoFdmSupports::on_init(), Slic3r::GUI::GLGizmoFlatten::on_init(), Slic3r::GUI::GLGizmoHollow::on_init(), Slic3r::GUI::GLGizmoMeshBoolean::on_init(), Slic3r::GUI::GLGizmoMmuSegmentation::on_init(), Slic3r::GUI::GLGizmoMove3D::on_init(), Slic3r::GUI::GLGizmoRotate3D::on_init(), Slic3r::GUI::GLGizmoScale3D::on_init(), Slic3r::GUI::GLGizmoSeam::on_init(), Slic3r::GUI::GLGizmoSlaSupports::on_init(), and Slic3r::GUI::GLGizmoText::on_init().
m_shortcuts
std::vector<std::pair<wxString, wxString> > Slic3r::GUI::GLGizmoAdvancedCut::m_shortcuts private
Referenced by on_init(), and show_tooltip_information().
m_show_shortcuts
bool Slic3r::GUI::GLGizmoAdvancedCut::m_show_shortcuts {false} private
m_sphere
GLModel Slic3r::GUI::GLGizmoBase::m_sphere protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::GLGizmoBase(), and Slic3r::GUI::GLGizmoSlaSupports::render_points().
m_sprite_id
unsigned int Slic3r::GUI::GLGizmoBase::m_sprite_id protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_sprite_id().
m_start_height
double Slic3r::GUI::GLGizmoAdvancedCut::m_start_height private
Referenced by on_start_dragging(), and on_update().
m_start_movement
double Slic3r::GUI::GLGizmoAdvancedCut::m_start_movement private
Referenced by on_start_dragging(), and on_update().
m_state
EState Slic3r::GUI::GLGizmoBase::m_state protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::get_state(), Slic3r::GUI::GLGizmoFlatten::is_plane_update_necessary(), Slic3r::GUI::GLGizmoBase::load(), Slic3r::GUI::GLGizmoHollow::on_render(), Slic3r::GUI::GLGizmoSlaSupports::on_render(), Slic3r::GUI::GLGizmoHollow::on_set_state(), Slic3r::GUI::GLGizmoMeshBoolean::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::on_set_state(), Slic3r::GUI::GLGizmoRotate3D::on_set_state(), Slic3r::GUI::GLGizmoSimplify::on_set_state(), Slic3r::GUI::GLGizmoSlaSupports::on_set_state(), Slic3r::GUI::GLGizmoText::on_set_state(), Slic3r::GUI::GLGizmoPainterBase::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoMmuSegmentation::set_painter_gizmo_data(), Slic3r::GUI::GLGizmoHollow::set_sla_support_data(), Slic3r::GUI::GLGizmoSlaSupports::set_sla_support_data(), Slic3r::GUI::GLGizmoBase::set_state(), and Slic3r::GUI::GLGizmoSimplify::worker_finished().
m_tooltip
std::string Slic3r::GUI::GLGizmoBase::m_tooltip mutable protected inherited
Referenced by Slic3r::GUI::GLGizmoBase::render().
Margin
const double Slic3r::GUI::GLGizmoAdvancedCut::Margin = 20.0 static private
Referenced by reset_cut_plane().
Offset
const double Slic3r::GUI::GLGizmoAdvancedCut::Offset = 10.0 static private
Referenced by render_cut_plane_and_grabbers().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Gizmos/GLGizmoAdvancedCut.hpp
src/slic3r/GUI/Gizmos/GLGizmoAdvancedCut.cpp