OrcaSlicer: Slic3r::GUI::MappingItem Class Reference
Slic3r::GUI::MappingItem Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
MappingItem (wxWindow *parent)
~MappingItem ()
void update_data (TrayData data)
void send_event (int fliament_id)
void set_tray_index (wxString t_index)
void msw_rescale ()
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void set_data (wxColour colour, wxString name, TrayData data, bool unmatch=false)
void doRender (wxDC &dc)
Public Attributes
wxString m_tray_index
wxColour m_coloul
wxString m_name
TrayData m_tray_data
bool m_unmatch {false}
Detailed Description
Constructor & Destructor Documentation
MappingItem()
Slic3r::GUI::MappingItem::MappingItem (wxWindow * parent)
 : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize)
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    SetBackgroundColour(StateColor::darkModeColorFor(*wxWHITE));
    Bind(wxEVT_PAINT, &MappingItem::paintEvent, this);
}
References StateColor::darkModeColorFor(), and paintEvent().
~MappingItem()
Slic3r::GUI::MappingItem::~MappingItem ()
{
}
Member Function Documentation
doRender()
void Slic3r::GUI::MappingItem::doRender (wxDC & dc)
{
    dc.SetPen(m_coloul);
    dc.SetBrush(wxBrush(m_coloul));
    dc.DrawRectangle(0, (GetSize().y - MAPPING_ITEM_REAL_SIZE.y) / 2, MAPPING_ITEM_REAL_SIZE.x, MAPPING_ITEM_REAL_SIZE.y);
//    if (m_coloul == *wxWHITE) {
//        dc.SetPen(wxPen(wxColour(0xAC, 0xAC, 0xAC), 1));
//#ifdef __APPLE__
//        dc.DrawRectangle(1, 1, GetSize().x - 1, GetSize().y - 1);
//#else
//        dc.DrawRectangle(0, 0, tray_size.x, tray_size.y);
//#endif // __APPLE__
//    }
    wxColour side_colour = wxColour(0xE4E4E4);
    dc.SetPen(side_colour);
    dc.SetBrush(wxBrush(side_colour));
#ifdef __APPLE__
    dc.DrawRectangle(0, 0, FromDIP(4), GetSize().y);
    dc.DrawRectangle(GetSize().x - FromDIP(4), 0, FromDIP(4), GetSize().y);
#else
    dc.DrawRectangle(0, 0, FromDIP(4), GetSize().y);
    dc.DrawRectangle(GetSize().x - FromDIP(4), 0, FromDIP(4), GetSize().y);
#endif // __APPLE__
}
References m_coloul, and MAPPING_ITEM_REAL_SIZE.
Referenced by render().
msw_rescale()
void Slic3r::GUI::MappingItem::msw_rescale ()
{
}
paintEvent()
void Slic3r::GUI::MappingItem::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
    // PrepareDC(buffdc);
    // PrepareDC(dc);
}
References render().
Referenced by MappingItem().
render()
void Slic3r::GUI::MappingItem::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({0, 0}, size, &dc, {0, 0});
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
    // materials name
    dc.SetFont(::Label::Head_13);
    auto txt_colour = m_coloul.GetLuminance() < 0.5 ? *wxWHITE : wxColour(0x26, 0x2E, 0x30);
    txt_colour      = m_unmatch ? wxColour(0xCE, 0xCE, 0xCE) : txt_colour;
    dc.SetTextForeground(txt_colour);
    /*if (dc.GetTextExtent(m_name).x > GetSize().x - 10) {
        dc.SetFont(::Label::Body_10);
        m_name = m_name.substr(0, 3) + "." + m_name.substr(m_name.length() - 1);
    }*/
    auto txt_size = dc.GetTextExtent(m_tray_index);
    auto top = (GetSize().y - MAPPING_ITEM_REAL_SIZE.y) / 2 + FromDIP(8);
    dc.DrawText(m_tray_index, wxPoint((GetSize().x - txt_size.x) / 2, top));
    top += txt_size.y + FromDIP(7);
    dc.SetFont(::Label::Body_12);
    txt_size = dc.GetTextExtent(m_name);
    dc.DrawText(m_name, wxPoint((GetSize().x - txt_size.x) / 2, top));
}
References Label::Body_12, doRender(), Label::Head_13, m_coloul, m_name, m_tray_index, m_unmatch, MAPPING_ITEM_REAL_SIZE, and size.
Referenced by paintEvent().
send_event()
void Slic3r::GUI::MappingItem::send_event (int fliament_id)
{
    auto number = wxGetApp().transition_tridid(m_tray_data.id);
    wxCommandEvent event(EVT_SET_FINISH_MAPPING);
    event.SetInt(m_tray_data.id);
    wxString param = wxString::Format("%d|%d|%d|%s|%d", m_coloul.Red(), m_coloul.Green(), m_coloul.Blue(), number, fliament_id);
    event.SetString(param);
    event.SetEventObject(this->GetParent()->GetParent());
    wxPostEvent(this->GetParent()->GetParent()->GetParent(), event);
}
References Slic3r::GUI::TrayData::id, m_coloul, and m_tray_data.
Referenced by Slic3r::GUI::AmsMapingPopup::add_ams_mapping().
set_data()
void Slic3r::GUI::MappingItem::set_data (wxColour colour, wxString name, TrayData data, bool unmatch = false)
{
    m_unmatch = unmatch;
    m_tray_data = data;
    if (m_coloul != colour || m_name != name) {
        m_coloul = colour;
        m_name   = name;
        Refresh();
    }
}
References m_coloul, m_name, m_tray_data, and m_unmatch.
Referenced by Slic3r::GUI::AmsMapingPopup::add_ams_mapping().
set_tray_index()
void Slic3r::GUI::MappingItem::set_tray_index (wxString t_index) inline
{m_tray_index = t_index;};
References m_tray_index.
Referenced by Slic3r::GUI::AmsMapingPopup::add_ams_mapping().
update_data()
void Slic3r::GUI::MappingItem::update_data (TrayData data)
Member Data Documentation
m_coloul
wxColour Slic3r::GUI::MappingItem::m_coloul
Referenced by doRender(), render(), send_event(), and set_data().
m_name
wxString Slic3r::GUI::MappingItem::m_name
Referenced by render(), and set_data().
m_tray_data
TrayData Slic3r::GUI::MappingItem::m_tray_data
Referenced by send_event(), and set_data().
m_tray_index
wxString Slic3r::GUI::MappingItem::m_tray_index
Referenced by render(), and set_tray_index().
m_unmatch
bool Slic3r::GUI::MappingItem::m_unmatch {false}
Referenced by render(), and set_data().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp