OrcaSlicer: Slic3r::Bonjour::priv Struct Reference
Slic3r::Bonjour::priv Struct Reference
Public Member Functions
priv (std::string &&service)
std::string strip_service_dn (const std::string &service_name) const
void udp_receive (udp::endpoint from, size_t bytes)
void lookup_perform ()
Public Attributes
const std::string service
std::string protocol
std::string service_dn
TxtKeys txt_keys
unsigned timeout
unsigned retries
std::vector< char > buffer
std::thread io_thread
Bonjour::ReplyFn replyfn
Bonjour::CompleteFn completefn
Detailed Description
Constructor & Destructor Documentation
priv()
Slic3r::Bonjour::priv::priv (std::string && service)
  : service(std::move(service))
  , protocol("tcp")
  , timeout(10)
  , retries(1)
{
  buffer.resize(DnsMessage::MAX_SIZE);
}
References buffer, and Slic3r::DnsMessage::MAX_SIZE.
Member Function Documentation
lookup_perform()
void Slic3r::Bonjour::priv::lookup_perform ()
{
  service_dn = (boost::format("_%1%._%2%.local") % service % protocol).str();
  const auto brq = BonjourRequest::make(service, protocol);
  if (!brq) {
    return;
  }
  auto self = this;
  try {
    boost::asio::io_service io_service;
    udp::socket socket(io_service);
    socket.open(udp::v4());
    socket.set_option(udp::socket::reuse_address(true));
    udp::endpoint mcast(BonjourRequest::MCAST_IP4, BonjourRequest::MCAST_PORT);
    socket.send_to(asio::buffer(brq->data), mcast);
    bool expired = false;
    bool retry = false;
    asio::deadline_timer timer(io_service);
    retries--;
    std::function<void(const error_code &)> timer_handler = [&](const error_code &error) {
      if (retries == 0 || error) {
        expired = true;
        if (self->completefn) {
          self->completefn();
        }
      } else {
        retry = true;
        retries--;
        timer.expires_from_now(boost::posix_time::seconds(timeout));
        timer.async_wait(timer_handler);
      }
    };
    timer.expires_from_now(boost::posix_time::seconds(timeout));
    timer.async_wait(timer_handler);
    udp::endpoint recv_from;
    const auto recv_handler = [&](const error_code &error, size_t bytes) {
      if (!error) { self->udp_receive(recv_from, bytes); }
    };
    socket.async_receive_from(asio::buffer(buffer, buffer.size()), recv_from, recv_handler);
    while (io_service.run_one()) {
      if (expired) {
        socket.cancel();
      } else if (retry) {
        retry = false;
        socket.send_to(asio::buffer(brq->data), mcast);
      } else {
        buffer.resize(DnsMessage::MAX_SIZE);
        socket.async_receive_from(asio::buffer(buffer, buffer.size()), recv_from, recv_handler);
      }
    }
  } catch (std::exception& /* e */) {
  }
}
References buffer, error, Slic3r::BonjourRequest::make(), Slic3r::DnsMessage::MAX_SIZE, Slic3r::BonjourRequest::MCAST_IP4, Slic3r::BonjourRequest::MCAST_PORT, and void().
strip_service_dn()
std::string Slic3r::Bonjour::priv::strip_service_dn (const std::string & service_name) const
{
  if (service_name.size() <= service_dn.size()) {
    return service_name;
  }
  auto needle = service_name.rfind(service_dn);
  if (needle == service_name.size() - service_dn.size()) {
    return service_name.substr(0, needle - 1);
  } else {
    return service_name;
  }
}
udp_receive()
void Slic3r::Bonjour::priv::udp_receive (udp::endpoint from, size_t bytes)
{
  if (bytes == 0 || !replyfn) {
    return;
  }
  buffer.resize(bytes);
  auto dns_msg = DnsMessage::decode(buffer, txt_keys);
  if (dns_msg) {
    asio::ip::address ip = from.address();
    if (dns_msg->rr_a) { ip = dns_msg->rr_a->ip; }
    else if (dns_msg->rr_aaaa) { ip = dns_msg->rr_aaaa->ip; }
    for (auto &sdpair : dns_msg->sdmap) {
      if (! sdpair.second.srv) {
        continue;
      }
      const auto &srv = *sdpair.second.srv;
      auto service_name = strip_service_dn(sdpair.first);
      std::string path;
      std::string version;
      BonjourReply::TxtData txt_data;
      if (sdpair.second.txt) {
        txt_data = std::move(sdpair.second.txt->data);
      }
      BonjourReply reply(ip, srv.port, std::move(service_name), srv.hostname, std::move(txt_data));
      replyfn(std::move(reply));
    }
  }
}
References buffer, and Slic3r::DnsMessage::decode().
Member Data Documentation
buffer
std::vector<char> Slic3r::Bonjour::priv::buffer
Referenced by priv().
completefn
Bonjour::CompleteFn Slic3r::Bonjour::priv::completefn
io_thread
std::thread Slic3r::Bonjour::priv::io_thread
protocol
std::string Slic3r::Bonjour::priv::protocol
replyfn
Bonjour::ReplyFn Slic3r::Bonjour::priv::replyfn
retries
unsigned Slic3r::Bonjour::priv::retries
service
const std::string Slic3r::Bonjour::priv::service
service_dn
std::string Slic3r::Bonjour::priv::service_dn
timeout
unsigned Slic3r::Bonjour::priv::timeout
txt_keys
TxtKeys Slic3r::Bonjour::priv::txt_keys
The documentation for this struct was generated from the following file:
src/slic3r/Utils/Bonjour.cpp