OrcaSlicer: Slic3r::RaycastResult Struct Reference
Slic3r::RaycastResult Struct Reference
#include <src/libslic3r/Model.hpp>
Public Member Functions
template<typename Archive >
void serialize (Archive &ar)
Public Attributes
Vec2d mouse_position = Vec2d::Zero()
int mesh_id = -1
Vec3f hit = Vec3f::Zero()
Vec3f normal = Vec3f::Zero()
Detailed Description
Member Function Documentation
serialize()
template<typename Archive > void Slic3r::RaycastResult::serialize (Archive & ar) inline
{ ar(mouse_position, mesh_id, hit, normal); }
References hit, mesh_id, mouse_position, and normal.
Member Data Documentation
hit
Vec3f Slic3r::RaycastResult::hit = Vec3f::Zero()
Referenced by Slic3r::_add_text_info_to_archive(), Slic3r::_BBS_3MF_Importer::_handle_start_text_info_item(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), serialize(), and Slic3r::GUI::GLGizmoText::update_text_positions().
mesh_id
int Slic3r::RaycastResult::mesh_id = -1
Referenced by Slic3r::_add_text_info_to_archive(), Slic3r::_BBS_3MF_Importer::_handle_start_text_info_item(), Slic3r::GUI::GLGizmoText::on_render(), Slic3r::GUI::GLGizmoText::on_render_for_picking(), serialize(), and Slic3r::GUI::GLGizmoText::update_text_positions().
mouse_position
Vec2d Slic3r::RaycastResult::mouse_position = Vec2d::Zero()
Referenced by Slic3r::GUI::GLGizmoText::on_render(), serialize(), and Slic3r::GUI::GLGizmoText::update_raycast_cache().
normal
Vec3f Slic3r::RaycastResult::normal = Vec3f::Zero()
Referenced by Slic3r::_add_text_info_to_archive(), Slic3r::_BBS_3MF_Importer::_handle_start_text_info_item(), serialize(), and Slic3r::GUI::GLGizmoText::update_text_positions().
The documentation for this struct was generated from the following file:
src/libslic3r/Model.hpp