OrcaSlicer: Slic3r::GUI::GLCanvas3D::WipeTowerInfo Class Reference
Slic3r::GUI::GLCanvas3D::WipeTowerInfo Class Reference
#include <src/slic3r/GUI/GLCanvas3D.hpp>
Public Member Functions
operator bool () const
const Vec2d & pos () const
double rotation () const
const Vec2d bb_size () const
void apply_wipe_tower () const
Protected Attributes
Vec2d m_pos = {std::nan(""), std::nan("")}
double m_rotation = 0.
BoundingBoxf m_bb
int m_plate_idx = -1
Friends
class GLCanvas3D
Detailed Description
Member Function Documentation
apply_wipe_tower()
void Slic3r::GUI::GLCanvas3D::WipeTowerInfo::apply_wipe_tower () const
{
    // BBS: add partplate logic
    DynamicConfig& proj_cfg = wxGetApp().preset_bundle->project_config;
    Vec3d plate_origin = wxGetApp().plater()->get_partplate_list().get_plate(m_plate_idx)->get_origin();
    ConfigOptionFloat wipe_tower_x(m_pos(X) - plate_origin(0));
    ConfigOptionFloat wipe_tower_y(m_pos(Y) - plate_origin(1));
    ConfigOptionFloats* wipe_tower_x_opt = proj_cfg.option<ConfigOptionFloats>("wipe_tower_x", true);
    ConfigOptionFloats* wipe_tower_y_opt = proj_cfg.option<ConfigOptionFloats>("wipe_tower_y", true);
    wipe_tower_x_opt->set_at(&wipe_tower_x, m_plate_idx, 0);
    wipe_tower_y_opt->set_at(&wipe_tower_y, m_plate_idx, 0);
    //q->update();
}
References Slic3r::ConfigBase::option(), Slic3r::ConfigOptionVector< T >::set_at(), Slic3r::wipe_tower_y(), Slic3r::X, and Slic3r::Y.
Referenced by Slic3r::GUI::WipeTower::apply_arrange_result().
bb_size()
const Vec2d Slic3r::GUI::GLCanvas3D::WipeTowerInfo::bb_size () const inline
{ return m_bb.size(); }
References m_bb, and Slic3r::BoundingBoxBase< PointClass >::size().
operator bool()
Slic3r::GUI::GLCanvas3D::WipeTowerInfo::operator bool () const inline
{
            return !std::isnan(m_pos.x()) && !std::isnan(m_pos.y());
        }
References m_pos.
pos()
const Vec2d & Slic3r::GUI::GLCanvas3D::WipeTowerInfo::pos () const inline
{ return m_pos; }
References m_pos.
rotation()
double Slic3r::GUI::GLCanvas3D::WipeTowerInfo::rotation () const inline
{ return m_rotation; }
References m_rotation.
Referenced by Slic3r::GUI::WipeTower::apply_arrange_result().
Friends And Related Symbol Documentation
GLCanvas3D
friend class GLCanvas3D friend
Member Data Documentation
m_bb
BoundingBoxf Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_bb protected
Referenced by bb_size(), Slic3r::GUI::WipeTower::get_arrange_polygon(), and Slic3r::GUI::GLCanvas3D::get_wipe_tower_info().
m_plate_idx
int Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_plate_idx = -1 protected
Referenced by Slic3r::GUI::GLCanvas3D::get_wipe_tower_info().
m_pos
Vec2d Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_pos = {std::nan(""), std::nan("")} protected
Referenced by Slic3r::GUI::WipeTower::apply_arrange_result(), Slic3r::GUI::WipeTower::get_arrange_polygon(), Slic3r::GUI::GLCanvas3D::get_wipe_tower_info(), operator bool(), and pos().
m_rotation
double Slic3r::GUI::GLCanvas3D::WipeTowerInfo::m_rotation = 0. protected
Referenced by Slic3r::GUI::WipeTower::apply_arrange_result(), Slic3r::GUI::WipeTower::get_arrange_polygon(), and rotation().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GLCanvas3D.hpp
src/slic3r/GUI/GLCanvas3D.cpp