OrcaSlicer: Slic3r::GUI::ObjectTableSettings Class Reference
Slic3r::GUI::ObjectTableSettings Class Reference
#include <src/slic3r/GUI/GUI_ObjectTableSettings.hpp>
Public Member Functions
ObjectTableSettings (wxWindow *parent, ObjectGridTable *table)
~ObjectTableSettings ()
bool update_settings_list (bool is_object, bool is_multiple_selection, ModelObject *object, ModelConfig *config, const std::string &category)
bool add_missed_options (ModelConfig *config_to, const DynamicPrintConfig &config_from)
int update_extra_column_visible_status (ConfigOptionsGroup *option_group, const std::vector< SimpleSettingData > &option_keys, ModelConfig *config)
void update_config_values (bool is_object, ModelObject *object, ModelConfig *config, const std::string &category)
void UpdateAndShow (int row, const bool show, bool is_object, bool is_multiple_selection, ModelObject *object, ModelConfig *config, const std::string &category)
void ValueChanged (int row, bool is_object, ModelObject *object, ModelConfig *config, const std::string &category, const std::string &key)
void resetAllValues (int row, bool is_object, ModelObject *object, ModelConfig *config, const std::string &category)
void msw_rescale ()
virtual bool IsShown ()
virtual void Show (const bool show)
virtual void Hide ()
virtual void UpdateAndShow (const bool show)
virtual wxSizer * get_sizer ()
ConfigOptionsGroup * get_og ()
wxWindow * parent () const
Protected Attributes
std::shared_ptr< ConfigOptionsGroup > m_og
wxWindow * m_parent
Private Attributes
wxBoxSizer * m_settings_list_sizer { nullptr }
std::vector< std::shared_ptr< ConfigOptionsGroup > > m_og_settings
DynamicPrintConfig m_current_config
DynamicPrintConfig m_origin_config
ScalableBitmap m_bmp_reset
ScalableBitmap m_bmp_reset_focus
ScalableBitmap m_bmp_reset_disable
ObjectGridTable * m_table { nullptr }
int m_current_row { 0 }
std::string m_current_category
int m_current_different { 0 }
std::map< std::string, int > m_different_map
Detailed Description
Constructor & Destructor Documentation
ObjectTableSettings()
Slic3r::GUI::ObjectTableSettings::ObjectTableSettings (wxWindow * parent, ObjectGridTable * table)
                                                                                 :
    OTG_Settings(parent, true), m_table(table)
{
    m_og->activate();
    //m_og->set_name(_(L("Per-Object Settings")));
    m_settings_list_sizer = new wxBoxSizer(wxVERTICAL);
    m_og->sizer->Add(m_settings_list_sizer, 1, wxEXPAND | wxLEFT, 5);
    m_bmp_reset = ScalableBitmap(parent, "lock_normal");
    m_bmp_reset_focus = ScalableBitmap(parent, "lock_normal");
    //TODO, adjust later
    m_bmp_reset_disable = ScalableBitmap(parent, "dot");
}
References m_bmp_reset, m_bmp_reset_disable, m_bmp_reset_focus, Slic3r::GUI::OTG_Settings::m_og, m_settings_list_sizer, and Slic3r::GUI::OTG_Settings::parent().
~ObjectTableSettings()
Slic3r::GUI::ObjectTableSettings::~ObjectTableSettings () inline
    {
        m_different_map.clear();
    }
References m_different_map.
Member Function Documentation
add_missed_options()
bool Slic3r::GUI::ObjectTableSettings::add_missed_options (ModelConfig * config_to, const DynamicPrintConfig & config_from)
{
    bool is_added = false;
    if (wxGetApp().plater()->printer_technology() == ptFFF)
    {
        if (config_to->has("sparse_infill_density") && !config_to->has("sparse_infill_pattern"))
        {
            if (config_from.option<ConfigOptionPercent>("sparse_infill_density")->value == 100) {
                config_to->set_key_value("sparse_infill_pattern", config_from.option("sparse_infill_pattern")->clone());
                is_added = true;
            }
        }
    }
    return is_added;
}
References Slic3r::ConfigOption::clone(), Slic3r::ModelConfig::has(), Slic3r::ConfigBase::option(), Slic3r::GUI::plater(), Slic3r::GUI::printer_technology(), Slic3r::ptFFF, Slic3r::ModelConfig::set_key_value(), and Slic3r::ConfigOptionSingle< T >::value.
get_og()
ConfigOptionsGroup * Slic3r::GUI::OTG_Settings::get_og () inline inherited
{ return m_og.get(); }
References Slic3r::GUI::OTG_Settings::m_og.
get_sizer()
wxSizer * Slic3r::GUI::OTG_Settings::get_sizer () virtual inherited
{
    return m_og->sizer;
}
References Slic3r::GUI::OTG_Settings::m_og.
Hide()
void Slic3r::GUI::OTG_Settings::Hide () virtual inherited
{
    Show(false);
}
References Slic3r::GUI::OTG_Settings::Show().
IsShown()
bool Slic3r::GUI::OTG_Settings::IsShown () virtual inherited
{
    return m_og->sizer->IsEmpty() ? false : m_og->sizer->IsShown(size_t(0));
}
References Slic3r::GUI::OTG_Settings::m_og.
msw_rescale()
void Slic3r::GUI::ObjectTableSettings::msw_rescale ()
{
    for (auto group : m_og_settings)
        group->msw_rescale();
}
References m_og_settings.
parent()
wxWindow * Slic3r::GUI::OTG_Settings::parent () const inline inherited
{return m_parent; }
References Slic3r::GUI::OTG_Settings::m_parent.
Referenced by ObjectTableSettings(), Slic3r::GUI::OTG_Settings::OTG_Settings(), and update_settings_list().
resetAllValues()
void Slic3r::GUI::ObjectTableSettings::resetAllValues (int row, bool is_object, ModelObject * object, ModelConfig * config, const std::string & category)
{
    if ((row != m_current_row) || (category != m_current_category))
        return;
    if (category == ObjectGridTable::category_all) {
        std::map<std::string, std::vector<SimpleSettingData>> cat_options;
        //get the category and settings
        cat_options = SettingsFactory::get_all_visible_options(!is_object);
        std::map<std::string, std::vector<SimpleSettingData>>::iterator it1 = cat_options.begin();
        while (it1 != cat_options.end())
        {
            std::vector<SimpleSettingData>& settings = it1->second;
            std::vector<SimpleSettingData>::iterator it2 = settings.begin();
            while ( it2 != settings.end() )
            {
                config->erase(it2->name);
                it2++;
            }
            it1++;
        }
    }
    else {
        // Initialize UI components with the config values.
        std::vector<SimpleSettingData> category_settings = SettingsFactory::get_visible_options(category, !is_object);
        for (auto& opt : category_settings)
        {
            config->erase(opt.name);
        }
    }
    m_current_config = m_origin_config;
    m_current_config.apply(config->get(), true);
    update_config_values(is_object, object, config, category);
}
References Slic3r::ConfigBase::apply(), Slic3r::GUI::ObjectGridTable::category_all, Slic3r::ModelConfig::erase(), Slic3r::ModelConfig::get(), Slic3r::GUI::SettingsFactory::get_all_visible_options(), Slic3r::GUI::SettingsFactory::get_visible_options(), m_current_category, m_current_config, m_current_row, m_origin_config, row(), and update_config_values().
Referenced by Slic3r::GUI::ObjectTablePanel::resetAllValuesInSideWindow().
Show()
void Slic3r::GUI::OTG_Settings::Show (const bool show) virtual inherited
{
    m_og->Show(show);
}
References Slic3r::GUI::OTG_Settings::m_og.
Referenced by Slic3r::GUI::OTG_Settings::Hide(), update_settings_list(), and Slic3r::GUI::OTG_Settings::UpdateAndShow().
update_config_values()
void Slic3r::GUI::ObjectTableSettings::update_config_values (bool is_object, ModelObject * object, ModelConfig * config, const std::string & category)
{
    int different_count = 0;
    const auto printer_technology   = wxGetApp().plater()->printer_technology();
    if (!object || !config)
        return;
    // update config values according to configuration hierarchy
    DynamicPrintConfig  &main_config   = m_current_config;
    auto toggle_field = [this](const t_config_option_key & opt_key, bool toggle, int opt_index)
    {
        Field* field = nullptr;
        for (auto og : m_og_settings) {
            field = og->get_fieldc(opt_key, opt_index);
            if (field != nullptr)
                break;
        }
        if (field)
            field->toggle(toggle);
    };
    ConfigManipulation config_manipulation(nullptr, toggle_field, nullptr, nullptr, &m_current_config);
    printer_technology == ptFFF  ?  config_manipulation.update_print_fff_config(&main_config) :
                                    config_manipulation.update_print_sla_config(&main_config) ;
    printer_technology == ptFFF  ?  config_manipulation.toggle_print_fff_options(&main_config) :
                                    config_manipulation.toggle_print_sla_options(&main_config) ;
    t_config_option_keys diff_keys;
    for (const t_config_option_key &opt_key : main_config.keys()) {
        const ConfigOption *this_opt  = main_config.option(opt_key);
        const ConfigOption *other_opt = m_origin_config.option(opt_key);
        if (this_opt != nullptr && (other_opt == nullptr || *this_opt != *other_opt))
            diff_keys.emplace_back(opt_key);
    }
    // load checked values from main_config to config
    config->reset();
    config->apply_only(main_config, diff_keys, true);
    // Initialize UI components with the config values.
    std::vector<SimpleSettingData> category_settings = SettingsFactory::get_visible_options(category, !is_object);
    std::string current_category;
    for (auto og : m_og_settings)
    {
        current_category = GUI::into_u8(og->config_category());
        og->reload_config();
        if (category == ObjectGridTable::category_all) {
            category_settings = SettingsFactory::get_visible_options(current_category, !is_object);
            different_count = update_extra_column_visible_status(og.get(), category_settings, config);
            if (different_count > 0)
                m_different_map[current_category] = different_count;
            else
                m_different_map.erase(current_category);
        }
        else if (category == current_category){
            different_count = update_extra_column_visible_status(og.get(), category_settings, config);
            if (different_count > 0)
                m_different_map[current_category] = different_count;
            else
                m_different_map.erase(current_category);
        }
    }
    if (m_different_map.size() > 0)
        m_table->enable_reset_all_button(true);
    else
        m_table->enable_reset_all_button(false);
    //update the table and volume settings
    m_table->reload_cell_data(m_current_row, category);
}
References Slic3r::ModelConfig::apply_only(), Slic3r::GUI::ObjectGridTable::category_all, Slic3r::GUI::ObjectGridTable::enable_reset_all_button(), Slic3r::GUI::SettingsFactory::get_visible_options(), Slic3r::GUI::into_u8(), Slic3r::DynamicConfig::keys(), m_current_config, m_current_row, m_different_map, m_og_settings, m_origin_config, m_table, Slic3r::ConfigBase::option(), Slic3r::GUI::printer_technology(), Slic3r::ptFFF, Slic3r::GUI::ObjectGridTable::reload_cell_data(), Slic3r::ModelConfig::reset(), Slic3r::GUI::Field::toggle(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::ConfigManipulation::toggle_print_sla_options(), update_extra_column_visible_status(), Slic3r::GUI::ConfigManipulation::update_print_fff_config(), and Slic3r::GUI::ConfigManipulation::update_print_sla_config().
Referenced by resetAllValues(), update_settings_list(), and ValueChanged().
update_extra_column_visible_status()
int Slic3r::GUI::ObjectTableSettings::update_extra_column_visible_status (ConfigOptionsGroup * option_group, const std::vector< SimpleSettingData > & option_keys, ModelConfig * config)
{
    int count = 0;
    for (auto& opt : option_keys)
    {
        auto line = option_group->get_line(opt.name);
        Field* field = option_group->get_fieldc(opt.name, -1);
        wxWindow *reset_window = field?field->getWindow():nullptr;
        if (line) {
            if ((config->has(opt.name)) && reset_window&&reset_window->IsEnabled()) {
                line->extra_widget_win->Enable();
                #ifdef __WXOSX_MAC__
                wxCommandEvent event(EVT_LOCK_ENABLE);
                event.SetEventObject(line->extra_widget_win);
                wxPostEvent(line->extra_widget_win, event);
                #endif
                count++;
            } else {
                line->extra_widget_win->Disable();
                #ifdef __WXOSX_MAC__
                wxCommandEvent event(EVT_LOCK_DISABLE);
                event.SetEventObject(line->extra_widget_win);
                wxPostEvent(line->extra_widget_win, event);
                #endif
            }
        }
    }
    wxGridSizer* grid_sizer = option_group->get_grid_sizer();
    grid_sizer->Layout();
    return count;
}
References count, Slic3r::GUI::ConfigOptionsGroup::get_fieldc(), Slic3r::GUI::OptionsGroup::get_grid_sizer(), Slic3r::GUI::OptionsGroup::get_line(), Slic3r::GUI::Field::getWindow(), and Slic3r::ModelConfig::has().
Referenced by update_config_values(), and update_settings_list().
update_settings_list()
bool Slic3r::GUI::ObjectTableSettings::update_settings_list (bool is_object, bool is_multiple_selection, ModelObject * object, ModelConfig * config, const std::string & category)
{
    std::string group_category;
    int different_count = 0;
    m_settings_list_sizer->Clear(true);
    m_og_settings.resize(0);
    Show(true);
    if (!config || is_multiple_selection || !object)
        return false;
    const auto printer_technology   = wxGetApp().plater()->printer_technology();
    // update config values according to configuration hierarchy
    m_current_config   = printer_technology == ptFFF ?
                                        wxGetApp().preset_bundle->prints.get_edited_preset().config :
                                        wxGetApp().preset_bundle->sla_prints.get_edited_preset().config;
    //ConfigManipulation config_manipulation(load_config, toggle_field, nullptr, config);
    if (!is_object)
    {
        m_current_config.apply(object->config.get(), true);
    }
    m_origin_config = m_current_config;
    m_current_config.apply(config->get(), true);
    //SettingsFactory::Bundle cat_options = SettingsFactory::get_bundle(&config->get(), is_object);
    std::map<std::string, std::vector<SimpleSettingData>> cat_options;
    std::vector<SimpleSettingData> category_settings = SettingsFactory::get_visible_options(category, !is_object);
    bool display_multiple = false;
    auto is_option_modified = [this](std::string key) {
        ConfigOption* config_option1 = m_origin_config.option(key);
        ConfigOption* config_option2 = m_current_config.option(key);
        if (!config_option1 && config_option2)
            return true;
        else if (config_option1 && config_option2 && (*config_option1 != *config_option2))
            return true;
        return false;
    };
    //get the category and settings
    if (category_settings.size() == 0) {
        BOOST_LOG_TRIVIAL(info) << __FUNCTION__ << "can not find settings for category " <<category <<", display all the modified settings instead!!!" << std::endl;
        //return false;
        cat_options = SettingsFactory::get_all_visible_options(!is_object);
        std::map<std::string, std::vector<SimpleSettingData>>::iterator it1 = cat_options.begin();
        while (it1 != cat_options.end())
        {
            std::vector<SimpleSettingData>& settings = it1->second;
            std::vector<SimpleSettingData>::iterator it2 = settings.begin();
            while ( it2 != settings.end() )
            {
                if (!is_option_modified(it2->name)) {
                    it2 = settings.erase(it2);
                }
                else {
                    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__ << boost::format(" category %1% , keep option %2%")%it1->first % it2->name;
                    it2++;
                }
            }
            if (settings.size() > 0)
                it1++;
            else
                it1 = cat_options.erase(it1);
        }
        display_multiple = true;
    }
    else {
        cat_options.emplace(category, category_settings);
    }
    std::vector<std::string> categories;
    categories.reserve(cat_options.size());
    for (auto& cat : cat_options)
    {
        categories.push_back(cat.first);
        group_category = cat.first;
        auto extra_column = [this, is_object, object, config, group_category](wxWindow* parent, const Line& line)
        {
            auto opt_key = (line.get_options())[0].opt_id;  //we assume that we have one option per line
            auto btn = new ScalableButton(parent, wxID_ANY, m_bmp_reset);
            btn->SetToolTip(_(L("Reset parameter")));
            #ifdef __WINDOWS__
            btn->SetBackgroundColour(parent->GetBackgroundColour());
            #endif // DEBUG
            btn->SetBitmapFocus(m_bmp_reset_focus.bmp());
            btn->SetBitmapHover(m_bmp_reset_focus.bmp());
            #ifdef __WINDOWS__
            btn->SetBitmapDisabled(m_bmp_reset_disable.bmp());
            #endif
            #ifdef __WXOSX_MAC__
            btn->Bind(EVT_LOCK_DISABLE, [this, btn](auto &e) { btn->SetBitmap(m_bmp_reset_disable.bmp()); });
            btn->Bind(EVT_LOCK_ENABLE, [this, btn](auto &e) { btn->SetBitmap(m_bmp_reset_focus.bmp()); });
            #endif
            btn->Bind(wxEVT_BUTTON, [btn, opt_key, this, is_object, object, config, group_category](wxEvent &event) {
                //wxGetApp().plater()->take_snapshot(from_u8((boost::format(_utf8(L("Reset Option %s"))) % opt_key).str()));
                config->erase(opt_key);
                //btn->Hide();
                wxGetApp().obj_list()->changed_object();
                /*wxTheApp->CallAfter([this, is_object, object, config, category]() {
                    wxWindowUpdateLocker noUpdates(m_parent);
                    update_settings_list(is_object, false, object, config, category);
                });*/
                this->m_parent->Freeze();
                /* Check overriden options list after deleting.
                 * Some options couldn't be deleted because of another one.
                 * Like, we couldn't delete fill pattern, if fill density is set to 100%
                 */
                m_current_config = m_origin_config;
                m_current_config.apply(config->get(), true);
                update_config_values(is_object, object, config, group_category);
                this->m_parent->Thaw();
                #ifdef __WXOSX_MAC__
                if (!btn->IsEnabled()) {
                    btn->SetBitmap(m_bmp_reset_disable.bmp());
                } else {
                    btn->SetBitmap(m_bmp_reset_focus.bmp());
                }
                #endif
            });
            (const_cast<Line&>(line)).extra_widget_win = btn;
            return btn;
        };
        auto optgroup = std::make_shared<ConfigOptionsGroup>(m_og->ctrl_parent(), _(cat.first), &m_current_config, false, extra_column);
        optgroup->label_width = 15;
        optgroup->sidetext_width = 5;
        optgroup->set_config_category_and_type(GUI::from_u8(group_category), Preset::TYPE_PRINT);
        std::weak_ptr weak_optgroup(optgroup);
        optgroup->m_on_change = [this, is_object, object, config, group_category](const t_config_option_key &opt_id, const boost::any &value) {
                                    this->m_parent->Freeze();
                                    this->update_config_values(is_object, object, config, group_category);
                                    wxGetApp().obj_list()->changed_object();
                                    this->m_parent->Thaw();
                                    //update_extra_column_visible_status(optgroup.get(), cat.second, config);
                                };
        // call back for rescaling of the extracolumn control
        optgroup->rescale_extra_column_item = [this](wxWindow* win) {
            auto *ctrl = dynamic_cast<ScalableButton*>(win);
            if (ctrl == nullptr)
                return;
            ctrl->SetBitmap_(m_bmp_reset);
            ctrl->SetBitmapFocus(m_bmp_reset_focus.bmp());
            ctrl->SetBitmapHover(m_bmp_reset_focus.bmp());
            #ifdef __WINDOWS__
            ctrl->SetBitmapDisabled(m_bmp_reset_disable.bmp());
            #endif
        };
        const bool is_extruders_cat = cat.first == "Extruders";
        for (auto& opt : cat.second)
        {
            Option option = optgroup->get_option(opt.name);
            option.opt.width = 18;
            if (is_extruders_cat)
                option.opt.max = wxGetApp().extruders_edited_cnt();
            optgroup->append_single_option_line(option);
            if (!opt.label.empty()) {
                auto line = optgroup->get_line(opt.name);
                if (line)
                    line->label = GUI::from_u8(opt.label);
            }
        }
        optgroup->activate();
        for (auto& opt : cat.second)
            optgroup->get_field(opt.name)->m_on_change = [weak_optgroup](const std::string& opt_id, const boost::any& value) {
                // first of all take a snapshot and then change value in configuration
                wxGetApp().plater()->take_snapshot((boost::format("Change Option %s") % opt_id).str());
                weak_optgroup.lock()->on_change_OG(opt_id, value);
            };
        optgroup->reload_config();
        different_count = update_extra_column_visible_status(optgroup.get(), cat.second, config);
        m_current_different += different_count;
        if (different_count > 0)
            m_different_map[group_category] = different_count;
        /*for (auto& opt : cat.second)
        {
            auto line = optgroup->get_line(opt);
            if (line) {
                if (config->has(opt))
                    line->extra_widget_win->Show(true);
                else
                    line->extra_widget_win->Hide();
            }
        }*/
        m_settings_list_sizer->Add(optgroup->sizer, 0, wxEXPAND | wxALL, 0);
        m_og_settings.push_back(optgroup);
        auto toggle_field = [this, optgroup](const t_config_option_key & opt_key, bool toggle, int opt_index)
        {
            Field* field = optgroup->get_fieldc(opt_key, opt_index);;
            if (field)
                field->toggle(toggle);
        };
        ConfigManipulation config_manipulation(nullptr, toggle_field, nullptr, nullptr, &m_current_config);
        printer_technology == ptFFF  ?  config_manipulation.toggle_print_fff_options(&m_current_config) :
                                        config_manipulation.toggle_print_sla_options(&m_current_config) ;
    }
    //if (!categories.empty()) {
    //    update_config_values(is_object, object, config, category);
    //}
    if (m_current_different > 0)
        m_table->enable_reset_all_button(true);
    else
        m_table->enable_reset_all_button(false);
    return true;
}
References _, Slic3r::ConfigBase::apply(), ScalableBitmap::bmp(), Slic3r::GUI::ctrl, Slic3r::GUI::ObjectGridTable::enable_reset_all_button(), Slic3r::GUI::from_u8(), Slic3r::ModelConfig::get(), Slic3r::GUI::SettingsFactory::get_all_visible_options(), Slic3r::GUI::SettingsFactory::get_visible_options(), L, m_bmp_reset, m_bmp_reset_disable, m_bmp_reset_focus, m_current_config, m_current_different, m_different_map, Slic3r::GUI::OTG_Settings::m_og, m_og_settings, m_origin_config, Slic3r::GUI::OTG_Settings::m_parent, m_settings_list_sizer, m_table, Slic3r::ConfigOptionDef::max, Slic3r::GUI::Option::opt, Slic3r::ConfigBase::option(), Slic3r::GUI::OTG_Settings::parent(), Slic3r::GUI::printer_technology(), Slic3r::ptFFF, Slic3r::GUI::OTG_Settings::Show(), Slic3r::GUI::Field::toggle(), Slic3r::GUI::ConfigManipulation::toggle_print_fff_options(), Slic3r::GUI::ConfigManipulation::toggle_print_sla_options(), Slic3r::Preset::TYPE_PRINT, update_config_values(), update_extra_column_visible_status(), Slic3r::ConfigOptionDef::width, and wxEVT_BUTTON.
Referenced by UpdateAndShow().
UpdateAndShow() [1/2]
void Slic3r::GUI::OTG_Settings::UpdateAndShow (const bool show) virtual inherited
{
    Show(show);
//    m_parent->Layout();
}
References Slic3r::GUI::OTG_Settings::Show().
Referenced by UpdateAndShow().
UpdateAndShow() [2/2]
void Slic3r::GUI::ObjectTableSettings::UpdateAndShow (int row, const bool show, bool is_object, bool is_multiple_selection, ModelObject * object, ModelConfig * config, const std::string & category)
{
    m_current_row = row;
    m_current_category = category;
    m_current_different = 0;
    m_different_map.clear();
    //OTG_Settings::UpdateAndShow(show ? update_settings_list(is_object, is_multiple_selection, object, config, category) : false);
    if (show) {
        update_settings_list(is_object, is_multiple_selection, object, config, category);
    }
    else
        OTG_Settings::UpdateAndShow(false);
}
References m_current_category, m_current_different, m_current_row, m_different_map, row(), update_settings_list(), and Slic3r::GUI::OTG_Settings::UpdateAndShow().
Referenced by Slic3r::GUI::ObjectGridTable::OnSelectCell().
ValueChanged()
void Slic3r::GUI::ObjectTableSettings::ValueChanged (int row, bool is_object, ModelObject * object, ModelConfig * config, const std::string & category, const std::string & key)
{
    if ((row != m_current_row)
        || ((category != m_current_category) && (m_current_category != ObjectGridTable::category_all)))
        return;
    ConfigOption *my_opt = m_current_config.option(key, true);
    if (config->has(key)) {
        my_opt->set(config->option(key));
    }
    else {
        ConfigOption* config_option = m_origin_config.option(key);
        if (config_option)
            my_opt->set(config_option);
        else
            m_current_config.erase(key);
    }
    update_config_values(is_object, object, config, category);
}
References Slic3r::GUI::ObjectGridTable::category_all, Slic3r::DynamicConfig::erase(), Slic3r::ModelConfig::has(), m_current_category, m_current_config, m_current_row, m_origin_config, Slic3r::ModelConfig::option(), Slic3r::ConfigBase::option(), row(), Slic3r::ConfigOption::set(), and update_config_values().
Referenced by Slic3r::GUI::ObjectGridTable::OnCellLeftClick(), and Slic3r::GUI::ObjectGridTable::OnCellValueChanged().
Member Data Documentation
m_bmp_reset
ScalableBitmap Slic3r::GUI::ObjectTableSettings::m_bmp_reset private
Referenced by ObjectTableSettings(), and update_settings_list().
m_bmp_reset_disable
ScalableBitmap Slic3r::GUI::ObjectTableSettings::m_bmp_reset_disable private
Referenced by ObjectTableSettings(), and update_settings_list().
m_bmp_reset_focus
ScalableBitmap Slic3r::GUI::ObjectTableSettings::m_bmp_reset_focus private
Referenced by ObjectTableSettings(), and update_settings_list().
m_current_category
std::string Slic3r::GUI::ObjectTableSettings::m_current_category private
Referenced by resetAllValues(), UpdateAndShow(), and ValueChanged().
m_current_config
DynamicPrintConfig Slic3r::GUI::ObjectTableSettings::m_current_config private
Referenced by resetAllValues(), update_config_values(), update_settings_list(), and ValueChanged().
m_current_different
int Slic3r::GUI::ObjectTableSettings::m_current_different { 0 } private
Referenced by update_settings_list(), and UpdateAndShow().
m_current_row
int Slic3r::GUI::ObjectTableSettings::m_current_row { 0 } private
Referenced by resetAllValues(), update_config_values(), UpdateAndShow(), and ValueChanged().
m_different_map
std::map<std::string, int> Slic3r::GUI::ObjectTableSettings::m_different_map private
Referenced by ~ObjectTableSettings(), update_config_values(), update_settings_list(), and UpdateAndShow().
m_og
std::shared_ptr<ConfigOptionsGroup> Slic3r::GUI::OTG_Settings::m_og protected inherited
Referenced by ObjectTableSettings(), Slic3r::GUI::OTG_Settings::OTG_Settings(), Slic3r::GUI::OTG_Settings::get_og(), Slic3r::GUI::OTG_Settings::get_sizer(), Slic3r::GUI::OTG_Settings::IsShown(), Slic3r::GUI::OTG_Settings::Show(), and update_settings_list().
m_og_settings
std::vector<std::shared_ptr<ConfigOptionsGroup> > Slic3r::GUI::ObjectTableSettings::m_og_settings private
Referenced by msw_rescale(), update_config_values(), and update_settings_list().
m_origin_config
DynamicPrintConfig Slic3r::GUI::ObjectTableSettings::m_origin_config private
Referenced by resetAllValues(), update_config_values(), update_settings_list(), and ValueChanged().
m_parent
wxWindow* Slic3r::GUI::OTG_Settings::m_parent protected inherited
Referenced by Slic3r::GUI::OTG_Settings::parent(), and update_settings_list().
m_settings_list_sizer
wxBoxSizer* Slic3r::GUI::ObjectTableSettings::m_settings_list_sizer { nullptr } private
Referenced by ObjectTableSettings(), and update_settings_list().
m_table
ObjectGridTable* Slic3r::GUI::ObjectTableSettings::m_table { nullptr } private
Referenced by update_config_values(), and update_settings_list().
The documentation for this class was generated from the following files:
src/slic3r/GUI/GUI_ObjectTableSettings.hpp
src/slic3r/GUI/GUI_ObjectTableSettings.cpp