OrcaSlicer: Slic3r::GUI::OpenGLManager::GLInfo Class Reference
Slic3r::GUI::OpenGLManager::GLInfo Class Reference
#include <src/slic3r/GUI/OpenGLManager.hpp>
Public Member Functions
GLInfo ()=default
const std::string & get_version () const
const std::string & get_glsl_version () const
const std::string & get_vendor () const
const std::string & get_renderer () const
int get_max_tex_size () const
float get_max_anisotropy () const
bool is_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
bool is_glsl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
std::string to_string (bool for_github) const
Private Member Functions
void detect () const
Private Attributes
bool m_detected { false }
int m_max_tex_size { 0 }
float m_max_anisotropy { 0.0f }
std::string m_version
std::string m_glsl_version
std::string m_vendor
std::string m_renderer
Detailed Description
Constructor & Destructor Documentation
GLInfo()
Slic3r::GUI::OpenGLManager::GLInfo::GLInfo () default
Member Function Documentation
detect()
void Slic3r::GUI::OpenGLManager::GLInfo::detect () const private
{
    *const_cast<std::string*>(&m_version) = gl_get_string_safe(GL_VERSION, "N/A");
    *const_cast<std::string*>(&m_glsl_version) = gl_get_string_safe(GL_SHADING_LANGUAGE_VERSION, "N/A");
    *const_cast<std::string*>(&m_vendor) = gl_get_string_safe(GL_VENDOR, "N/A");
    *const_cast<std::string*>(&m_renderer) = gl_get_string_safe(GL_RENDERER, "N/A");
    BOOST_LOG_TRIVIAL(info) << boost::format("got opengl version %1%, glsl version %2%, vendor %3%")%m_version %m_glsl_version %m_vendor<< std::endl;
    int* max_tex_size = const_cast<int*>(&m_max_tex_size);
    glsafe(::glGetIntegerv(GL_MAX_TEXTURE_SIZE, max_tex_size));
    *max_tex_size /= 2;
    if (Slic3r::total_physical_memory() / (1024 * 1024 * 1024) < 6)
        *max_tex_size /= 2;
    if (GLEW_EXT_texture_filter_anisotropic) {
        float* max_anisotropy = const_cast<float*>(&m_max_anisotropy);
        glsafe(::glGetFloatv(GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT, max_anisotropy));
    }
    *const_cast<bool*>(&m_detected) = true;
}
References Slic3r::GUI::gl_get_string_safe(), glsafe, and Slic3r::total_physical_memory().
Referenced by get_version().
get_glsl_version()
const std::string & Slic3r::GUI::OpenGLManager::GLInfo::get_glsl_version () const
{
    if (!m_detected)
        detect();
    return m_glsl_version;
}
Referenced by Slic3r::GUI::generate_system_info_json().
get_max_anisotropy()
float Slic3r::GUI::OpenGLManager::GLInfo::get_max_anisotropy () const
{
    if (!m_detected)
        detect();
    return m_max_anisotropy;
}
Referenced by Slic3r::GUI::GLTexture::load_from_png(), Slic3r::GUI::GLTexture::load_from_raw_data(), and Slic3r::GUI::GLTexture::load_from_svg().
get_max_tex_size()
int Slic3r::GUI::OpenGLManager::GLInfo::get_max_tex_size () const
{
    if (!m_detected)
        detect();
    // clamp to avoid the texture generation become too slow and use too much GPU memory
#ifdef __APPLE__
    // and use smaller texture for non retina systems
    return (Slic3r::GUI::mac_max_scaling_factor() > 1.0) ? std::min(m_max_tex_size, 8192) : std::min(m_max_tex_size / 2, 4096);
#else
    // and use smaller texture for older OpenGL versions
    return is_version_greater_or_equal_to(3, 0) ? std::min(m_max_tex_size, 8192) : std::min(m_max_tex_size / 2, 4096);
#endif // __APPLE__
}
References Slic3r::GUI::mac_max_scaling_factor().
Referenced by Slic3r::GUI::PartPlateList::generate_icon_textures(), Slic3r::GUI::PartPlateList::load_bedtype_textures(), Slic3r::GUI::PartPlateList::load_cali_textures(), and Slic3r::GUI::PartPlate::render_logo().
get_renderer()
const std::string & Slic3r::GUI::OpenGLManager::GLInfo::get_renderer () const
{
    if (!m_detected)
        detect();
    return m_renderer;
}
Referenced by Slic3r::GUI::generate_system_info_json().
get_vendor()
const std::string & Slic3r::GUI::OpenGLManager::GLInfo::get_vendor () const
{
    if (!m_detected)
        detect();
    return m_vendor;
}
Referenced by Slic3r::GUI::generate_system_info_json().
get_version()
const std::string & Slic3r::GUI::OpenGLManager::GLInfo::get_version () const
{
    if (!m_detected)
        detect();
    return m_version;
}
References detect(), m_detected, and m_version.
Referenced by Slic3r::GUI::generate_system_info_json().
is_glsl_version_greater_or_equal_to()
bool Slic3r::GUI::OpenGLManager::GLInfo::is_glsl_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
{
    if (!m_detected)
        detect();
    return version_greater_or_equal_to(m_glsl_version, major, minor);
}
References Slic3r::GUI::version_greater_or_equal_to().
Referenced by Slic3r::GUI::GUI_App::is_glsl_version_greater_or_equal_to().
is_version_greater_or_equal_to()
bool Slic3r::GUI::OpenGLManager::GLInfo::is_version_greater_or_equal_to (unsigned int major, unsigned int minor) const
{
    if (!m_detected)
        detect();
    return version_greater_or_equal_to(m_version, major, minor);
}
References Slic3r::GUI::version_greater_or_equal_to().
Referenced by Slic3r::GUI::OpenGLManager::init_gl(), and Slic3r::GUI::GUI_App::is_gl_version_greater_or_equal_to().
to_string()
std::string Slic3r::GUI::OpenGLManager::GLInfo::to_string (bool for_github) const
{
    if (!m_detected)
        detect();
    std::stringstream out;
    const bool format_as_html = ! for_github;
    std::string h2_start = format_as_html ? "<b>" : "";
    std::string h2_end = format_as_html ? "</b>" : "";
    std::string b_start = format_as_html ? "<b>" : "";
    std::string b_end = format_as_html ? "</b>" : "";
    std::string line_end = format_as_html ? "<br>" : "\n";
    out << h2_start << "OpenGL installation" << h2_end << line_end;
    out << b_start << "GL version:   " << b_end << m_version << line_end;
    out << b_start << "Vendor:       " << b_end << m_vendor << line_end;
    out << b_start << "Renderer:     " << b_end << m_renderer << line_end;
    out << b_start << "GLSL version: " << b_end << m_glsl_version << line_end;
    {
        std::vector<std::string> extensions_list;
        std::string extensions_str = gl_get_string_safe(GL_EXTENSIONS, "");
        boost::split(extensions_list, extensions_str, boost::is_any_of(" "), boost::token_compress_on);
        if (!extensions_list.empty()) {
            if (for_github)
                out << "<details>\n<summary>Installed extensions:</summary>\n";
            else
                out << h2_start << "Installed extensions:" << h2_end << line_end;
            std::sort(extensions_list.begin(), extensions_list.end());
            for (const std::string& ext : extensions_list)
                if (! ext.empty())
                    out << ext << line_end;
            if (for_github)
                out << "</details>\n";
        }
    }
    return out.str();
}
References Slic3r::GUI::gl_get_string_safe(), and out.
Referenced by Slic3r::GUI::GUI_App::get_gl_info().
Member Data Documentation
m_detected
bool Slic3r::GUI::OpenGLManager::GLInfo::m_detected { false } private
Referenced by get_version().
m_glsl_version
std::string Slic3r::GUI::OpenGLManager::GLInfo::m_glsl_version private
m_max_anisotropy
float Slic3r::GUI::OpenGLManager::GLInfo::m_max_anisotropy { 0.0f } private
m_max_tex_size
int Slic3r::GUI::OpenGLManager::GLInfo::m_max_tex_size { 0 } private
m_renderer
std::string Slic3r::GUI::OpenGLManager::GLInfo::m_renderer private
m_vendor
std::string Slic3r::GUI::OpenGLManager::GLInfo::m_vendor private
m_version
std::string Slic3r::GUI::OpenGLManager::GLInfo::m_version private
Referenced by get_version().
The documentation for this class was generated from the following files:
src/slic3r/GUI/OpenGLManager.hpp
src/slic3r/GUI/OpenGLManager.cpp