OrcaSlicer: src/qhull/src/libqhull/qset.h File Reference
qset.h File Reference
#include <stdio.h>
Classes
union setelemT
struct setT
Macros
#define DEFsetT 1
#define SETelemsize ((int)sizeof(setelemT))
#define FOREACHsetelement_(type, set, variable)
#define FOREACHsetelement_i_(type, set, variable)
#define FOREACHsetelementreverse_(type, set, variable)
#define FOREACHsetelementreverse12_(type, set, variable)
#define FOREACHelem_(set) FOREACHsetelement_(void, set, elem)
#define FOREACHset_(sets) FOREACHsetelement_(setT, sets, set)
#define SETindex_(set, elem) ((int)((void **)elem##p - (void **)&(set)->e[1].p))
#define SETref_(elem) (elem##p[-1])
#define SETelem_(set, n) ((set)->e[n].p)
#define SETelemt_(set, n, type) ((type*)((set)->e[n].p))
#define SETelemaddr_(set, n, type) ((type **)(&((set)->e[n].p)))
#define SETfirst_(set) ((set)->e[0].p)
#define SETfirstt_(set, type) ((type*)((set)->e[0].p))
#define SETsecond_(set) ((set)->e[1].p)
#define SETsecondt_(set, type) ((type*)((set)->e[1].p))
#define SETaddr_(set, type) ((type **)(&((set)->e[0].p)))
#define SETreturnsize_(set, size) (((size)= ((set)->e[(set)->maxsize].i))?(--(size)):((size)= (set)->maxsize))
#define SETempty_(set) (!set || (SETfirst_(set) ? 0 : 1))
#define SETsizeaddr_(set) (&((set)->e[(set)->maxsize]))
#define SETtruncate_(set, size)
Typedefs
typedef struct setT setT
typedef union setelemT setelemT
Functions
void qh_setaddsorted (setT **setp, void *elem)
void qh_setaddnth (setT **setp, int nth, void *newelem)
void qh_setappend (setT **setp, void *elem)
void qh_setappend_set (setT **setp, setT *setA)
void qh_setappend2ndlast (setT **setp, void *elem)
void qh_setcheck (setT *set, const char *tname, unsigned id)
void qh_setcompact (setT *set)
setT * qh_setcopy (setT *set, int extra)
void * qh_setdel (setT *set, void *elem)
void * qh_setdellast (setT *set)
void * qh_setdelnth (setT *set, int nth)
void * qh_setdelnthsorted (setT *set, int nth)
void * qh_setdelsorted (setT *set, void *newelem)
setT * qh_setduplicate (setT *set, int elemsize)
void ** qh_setendpointer (setT *set)
int qh_setequal (setT *setA, setT *setB)
int qh_setequal_except (setT *setA, void *skipelemA, setT *setB, void *skipelemB)
int qh_setequal_skip (setT *setA, int skipA, setT *setB, int skipB)
void qh_setfree (setT **set)
void qh_setfree2 (setT **setp, int elemsize)
void qh_setfreelong (setT **set)
int qh_setin (setT *set, void *setelem)
int qh_setindex (setT *set, void *setelem)
void qh_setlarger (setT **setp)
void * qh_setlast (setT *set)
setT * qh_setnew (int size)
setT * qh_setnew_delnthsorted (setT *set, int size, int nth, int prepend)
void qh_setprint (FILE *fp, const char *string, setT *set)
void qh_setreplace (setT *set, void *oldelem, void *newelem)
int qh_setsize (setT *set)
setT * qh_settemp (int setsize)
void qh_settempfree (setT **set)
void qh_settempfree_all (void)
setT * qh_settemppop (void)
void qh_settemppush (setT *set)
void qh_settruncate (setT *set, int size)
int qh_setunique (setT **set, void *elem)
void qh_setzero (setT *set, int idx, int size)
Class Documentation
setelemT
union setelemT
Class Members
int i
void * p
setT
struct setT
Class Members
setelemT e[1]
int maxsize
Macro Definition Documentation
DEFsetT
#define DEFsetT 1
FOREACHelem_
#define FOREACHelem_ (set) FOREACHsetelement_(void, set, elem)
FOREACHset_
#define FOREACHset_ (sets) FOREACHsetelement_(setT, sets, set)
FOREACHsetelement_
#define FOREACHsetelement_ (type, set, variable)
Value:
        if (((variable= NULL), set)) for (\
          variable##p= (type **)&((set)->e[0].p); \
          (variable= *variable##p++);)
FOREACHsetelement_i_
#define FOREACHsetelement_i_ (type, set, variable)
Value:
        if (((variable= NULL), set)) for (\
          variable##_i= 0, variable= (type *)((set)->e[0].p), \
                   variable##_n= qh_setsize(set);\
          variable##_i < variable##_n;\
          variable= (type *)((set)->e[++variable##_i].p) )
FOREACHsetelementreverse12_
#define FOREACHsetelementreverse12_ (type, set, variable)
Value:
        if (((variable= NULL), set)) for (\
          variable##p= (type **)&((set)->e[1].p); \
          (variable= *variable##p); \
          variable##p == ((type **)&((set)->e[0].p))?variable##p += 2: \
              (variable##p == ((type **)&((set)->e[1].p))?variable##p--:variable##p++))
FOREACHsetelementreverse_
#define FOREACHsetelementreverse_ (type, set, variable)
Value:
        if (((variable= NULL), set)) for (\
           variable##temp= qh_setsize(set)-1, variable= qh_setlast(set);\
           variable; variable= \
           ((--variable##temp >= 0) ? SETelemt_(set, variable##temp, type) : NULL))
SETaddr_
#define SETaddr_ (set, type) ((type **)(&((set)->e[0].p)))
SETelem_
#define SETelem_ (set, n) ((set)->e[n].p)
SETelemaddr_
#define SETelemaddr_ (set, n, type) ((type **)(&((set)->e[n].p)))
SETelemsize
#define SETelemsize ((int)sizeof(setelemT))
SETelemt_
#define SETelemt_ (set, n, type) ((type*)((set)->e[n].p))
SETempty_
#define SETempty_ (set) (!set || (SETfirst_(set) ? 0 : 1))
SETfirst_
#define SETfirst_ (set) ((set)->e[0].p)
SETfirstt_
#define SETfirstt_ (set, type) ((type*)((set)->e[0].p))
SETindex_
#define SETindex_ (set, elem) ((int)((void **)elem##p - (void **)&(set)->e[1].p))
SETref_
#define SETref_ (elem) (elem##p[-1])
SETreturnsize_
#define SETreturnsize_ (set, size) (((size)= ((set)->e[(set)->maxsize].i))?(--(size)):((size)= (set)->maxsize))
SETsecond_
#define SETsecond_ (set) ((set)->e[1].p)
SETsecondt_
#define SETsecondt_ (set, type) ((type*)((set)->e[1].p))
SETsizeaddr_
#define SETsizeaddr_ (set) (&((set)->e[(set)->maxsize]))
SETtruncate_
#define SETtruncate_ (set, size)
Value:
      {set->e[set->maxsize].i= size+1; /* maybe overwritten */ \
      set->e[size].p= NULL;}
Typedef Documentation
setelemT
typedef union setelemT setelemT
setT
typedef struct setT setT
Function Documentation
qh_setaddnth()
void qh_setaddnth (setT ** setp, int nth, void * newelem)
{
  int oldsize, i;
  setelemT *sizep;          /* avoid strict aliasing */
  setelemT *oldp, *newp;
  if (!*setp || (sizep= SETsizeaddr_(*setp))->i==0) {
    qh_setlarger(setp);
    sizep= SETsizeaddr_(*setp);
  }
  oldsize= sizep->i - 1;
  if (nth < 0 || nth > oldsize) {
    qh_fprintf(qhmem.ferr, 6171, "qhull internal error (qh_setaddnth): nth %d is out-of-bounds for set:\n", nth);
    qh_setprint(qhmem.ferr, "", *setp);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  sizep->i++;
  oldp= (setelemT *)SETelemaddr_(*setp, oldsize, void);   /* NULL */
  newp= oldp+1;
  for (i=oldsize-nth+1; i--; )  /* move at least NULL  */
    (newp--)->p= (oldp--)->p;       /* may overwrite *sizep */
  newp->p= newelem;
} /* setaddnth */
References qhmemT::ferr, setelemT::i, NULL, setelemT::p, qh_errexit(), qh_fprintf(), qh_setlarger(), qh_setprint(), qhmem, qhmem_ERRqhull, SETelemaddr_, and SETsizeaddr_.
Referenced by qh_appendmergeset(), qh_appendmergeset(), qh_facet3vertex(), qh_facet3vertex(), qh_initialvertices(), qh_initialvertices(), qh_mergecycle(), qh_mergecycle(), qh_mergesimplex(), qh_mergesimplex(), qh_renameridgevertex(), qh_renameridgevertex(), qh_setaddsorted(), testSetdelSetadd(), and testSetdelSetadd().
qh_setaddsorted()
void qh_setaddsorted (setT ** setp, void * elem)
{
  int newindex=0;
  void *elem, **elemp;
  FOREACHelem_(*setp) {          /* could use binary search instead */
    if (elem < newelem)
      newindex++;
    else if (elem == newelem)
      return;
    else
      break;
  }
  qh_setaddnth(setp, newindex, newelem);
} /* setaddsorted */
References FOREACHelem_, and qh_setaddnth().
Referenced by testSetdelsortedEtc(), and testSetdelsortedEtc().
qh_setappend()
void qh_setappend (setT ** setp, void * elem)
{
  setelemT *sizep;  /* Avoid strict aliasing.  Writing to *endp may overwrite *sizep */
  setelemT *endp;
  int count;
  if (!newelem)
    return;
  if (!*setp || (sizep= SETsizeaddr_(*setp))->i==0) {
    qh_setlarger(setp);
    sizep= SETsizeaddr_(*setp);
  }
  count= (sizep->i)++ - 1;
  endp= (setelemT *)SETelemaddr_(*setp, count, void);
  (endp++)->p= newelem;
  endp->p= NULL;
} /* setappend */
References count, setelemT::i, NULL, setelemT::p, qh_setlarger(), SETelemaddr_, and SETsizeaddr_.
Referenced by qh_addpoint(), qh_addpoint(), qh_appendmergeset(), qh_appendmergeset(), qh_attachnewfacets(), qh_attachnewfacets(), qh_basevertices(), qh_basevertices(), qh_createsimplex(), qh_createsimplex(), qh_detvnorm(), qh_detvnorm(), qh_detvridge(), qh_detvridge(), qh_detvridge3(), qh_detvridge3(), qh_facet3vertex(), qh_facet3vertex(), qh_facetcenter(), qh_facetcenter(), qh_facetvertices(), qh_facetvertices(), qh_findbesthorizon(), qh_findbesthorizon(), qh_flippedmerges(), qh_flippedmerges(), qh_forcedmerges(), qh_forcedmerges(), qh_furthestout(), qh_furthestout(), qh_initialvertices(), qh_initialvertices(), qh_makenew_nonsimplicial(), qh_makenew_nonsimplicial(), qh_makenewfacet(), qh_makenewfacet(), qh_makeridges(), qh_makeridges(), qh_mark_dupridges(), qh_mark_dupridges(), qh_markkeep(), qh_markkeep(), qh_maxmin(), qh_maxmin(), qh_maxsimplex(), qh_maxsimplex(), qh_merge_degenredundant(), qh_merge_degenredundant(), qh_mergecycle_neighbors(), qh_mergecycle_neighbors(), qh_mergecycle_ridges(), qh_mergecycle_ridges(), qh_mergecycle_vneighbors(), qh_mergecycle_vneighbors(), qh_mergeneighbors(), qh_mergeneighbors(), qh_mergeridges(), qh_mergeridges(), qh_mergesimplex(), qh_mergesimplex(), qh_mergevertex_del(), qh_mergevertex_del(), qh_mergevertices(), qh_mergevertices(), qh_nearvertex(), qh_nearvertex(), qh_order_vertexneighbors(), qh_order_vertexneighbors(), qh_partitionall(), qh_partitionall(), qh_partitioncoplanar(), qh_partitioncoplanar(), qh_partitionpoint(), qh_partitionpoint(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_points(), qh_printfacet3geom_points(), qh_printfacet3geom_simplicial(), qh_printfacet3geom_simplicial(), qh_printfacet3math(), qh_printfacet3math(), qh_printneighborhood(), qh_printneighborhood(), qh_remove_extravertices(), qh_remove_extravertices(), qh_renamevertex(), qh_renamevertex(), qh_setduplicate(), qh_settemp(), qh_settemppush(), qh_setunique(), qh_updatevertices(), qh_updatevertices(), qh_vertexintersect_new(), qh_vertexintersect_new(), qh_vertexneighbors(), qh_vertexneighbors(), qh_vertexridges_facet(), qh_vertexridges_facet(), testSetappendSet(), testSetappendSet(), testSetappendSettruncate(), testSetappendSettruncate(), testSetcompactCopy(), testSetcompactCopy(), testSetdelSetadd(), testSetdelSetadd(), testSetequalInEtc(), testSetequalInEtc(), testSettemp(), and testSettemp().
qh_setappend2ndlast()
void qh_setappend2ndlast (setT ** setp, void * elem)
{
    setelemT *sizep;  /* Avoid strict aliasing.  Writing to *endp may overwrite *sizep */
    setelemT *endp, *lastp;
    int count;
    if (!*setp || (sizep= SETsizeaddr_(*setp))->i==0) {
        qh_setlarger(setp);
        sizep= SETsizeaddr_(*setp);
    }
    count= (sizep->i)++ - 1;
    endp= (setelemT *)SETelemaddr_(*setp, count, void); /* NULL */
    lastp= endp-1;
    *(endp++)= *lastp;
    endp->p= NULL;    /* may overwrite *sizep */
    lastp->p= newelem;
} /* setappend2ndlast */
References count, setelemT::i, NULL, setelemT::p, qh_setlarger(), SETelemaddr_, and SETsizeaddr_.
Referenced by qh_partitioncoplanar(), qh_partitioncoplanar(), qh_partitionpoint(), qh_partitionpoint(), testSetappendSettruncate(), and testSetappendSettruncate().
qh_setappend_set()
void qh_setappend_set (setT ** setp, setT * setA)
{
  int sizeA, size;
  setT *oldset;
  setelemT *sizep;
  if (!setA)
    return;
  SETreturnsize_(setA, sizeA);
  if (!*setp)
    *setp= qh_setnew(sizeA);
  sizep= SETsizeaddr_(*setp);
  if (!(size= sizep->i))
    size= (*setp)->maxsize;
  else
    size--;
  if (size + sizeA > (*setp)->maxsize) {
    oldset= *setp;
    *setp= qh_setcopy(oldset, sizeA);
    qh_setfree(&oldset);
    sizep= SETsizeaddr_(*setp);
  }
  if (sizeA > 0) {
    sizep->i= size+sizeA+1;   /* memcpy may overwrite */
    memcpy((char *)&((*setp)->e[size].p), (char *)&(setA->e[0].p), (size_t)(sizeA+1) * SETelemsize);
  }
} /* setappend_set */
References setT::e, setelemT::i, memcpy, setelemT::p, qh_setcopy(), qh_setfree(), qh_setnew(), SETelemsize, SETreturnsize_, SETsizeaddr_, and size.
Referenced by qh_makenew_nonsimplicial(), qh_makenew_nonsimplicial(), testSetappendSet(), and testSetappendSet().
qh_setcheck()
void qh_setcheck (setT * set, const char * tname, unsigned id)
{
  int maxsize, size;
  int waserr= 0;
  if (!set)
    return;
  SETreturnsize_(set, size);
  maxsize= set->maxsize;
  if (size > maxsize || !maxsize) {
    qh_fprintf(qhmem.ferr, 6172, "qhull internal error (qh_setcheck): actual size %d of %s%d is greater than max size %d\n",
             size, tname, id, maxsize);
    waserr= 1;
  }else if (set->e[size].p) {
    qh_fprintf(qhmem.ferr, 6173, "qhull internal error (qh_setcheck): %s%d(size %d max %d) is not null terminated.\n",
             tname, id, size-1, maxsize);
    waserr= 1;
  }
  if (waserr) {
    qh_setprint(qhmem.ferr, "ERRONEOUS", set);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
} /* setcheck */
References setT::e, qhmemT::ferr, setT::maxsize, NULL, setelemT::p, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem, qhmem_ERRqhull, SETreturnsize_, and size.
Referenced by checkSetContents(), checkSetContents(), qh_checkfacet(), qh_checkfacet(), qh_checkpolygon(), and qh_checkpolygon().
qh_setcompact()
void qh_setcompact (setT * set)
{
  int size;
  void **destp, **elemp, **endp, **firstp;
  if (!set)
    return;
  SETreturnsize_(set, size);
  destp= elemp= firstp= SETaddr_(set, void);
  endp= destp + size;
  while (1) {
    if (!(*destp++ = *elemp++)) {
      destp--;
      if (elemp > endp)
        break;
    }
  }
  qh_settruncate(set, (int)(destp-firstp));   /* WARN64 */
} /* setcompact */
References qh_settruncate(), SETaddr_, SETreturnsize_, and size.
Referenced by qh_mergecycle_neighbors(), qh_mergecycle_neighbors(), qh_mergecycle_ridges(), qh_mergecycle_ridges(), qh_mergecycle_vneighbors(), qh_mergecycle_vneighbors(), qh_nearcoplanar(), qh_nearcoplanar(), qh_updatevertices(), qh_updatevertices(), testSetcompactCopy(), testSetcompactCopy(), testSetdelsortedEtc(), testSetdelsortedEtc(), testSetlastEtc(), and testSetlastEtc().
qh_setcopy()
setT * qh_setcopy (setT * set, int extra)
{
  setT *newset;
  int size;
  if (extra < 0)
    extra= 0;
  SETreturnsize_(set, size);
  newset= qh_setnew(size+extra);
  SETsizeaddr_(newset)->i= size+1;    /* memcpy may overwrite */
  memcpy((char *)&(newset->e[0].p), (char *)&(set->e[0].p), (size_t)(size+1) * SETelemsize);
  return(newset);
} /* setcopy */
References setT::e, memcpy, setelemT::p, qh_setnew(), SETelemsize, SETreturnsize_, SETsizeaddr_, and size.
Referenced by qh_neighbor_intersections(), qh_neighbor_intersections(), qh_setappend_set(), testSetcompactCopy(), testSetcompactCopy(), testSetdelsortedEtc(), testSetdelsortedEtc(), testSetequalInEtc(), and testSetequalInEtc().
qh_setdel()
void * qh_setdel (setT * set, void * elem)
{
  setelemT *sizep;
  setelemT *elemp;
  setelemT *lastp;
  if (!set)
    return NULL;
  elemp= (setelemT *)SETaddr_(set, void);
  while (elemp->p != oldelem && elemp->p)
    elemp++;
  if (elemp->p) {
    sizep= SETsizeaddr_(set);
    if (!(sizep->i)--)         /*  if was a full set */
      sizep->i= set->maxsize;  /*     *sizep= (maxsize-1)+ 1 */
    lastp= (setelemT *)SETelemaddr_(set, sizep->i-1, void);
    elemp->p= lastp->p;      /* may overwrite itself */
    lastp->p= NULL;
    return oldelem;
  }
  return NULL;
} /* setdel */
qh_setdellast()
void * qh_setdellast (setT * set)
{
  int setsize;  /* actually, actual_size + 1 */
  int maxsize;
  setelemT *sizep;
  void *returnvalue;
  if (!set || !(set->e[0].p))
    return NULL;
  sizep= SETsizeaddr_(set);
  if ((setsize= sizep->i)) {
    returnvalue= set->e[setsize - 2].p;
    set->e[setsize - 2].p= NULL;
    sizep->i--;
  }else {
    maxsize= set->maxsize;
    returnvalue= set->e[maxsize - 1].p;
    set->e[maxsize - 1].p= NULL;
    sizep->i= maxsize;
  }
  return returnvalue;
} /* setdellast */
qh_setdelnth()
void * qh_setdelnth (setT * set, int nth)
{
  void *elem;
  setelemT *sizep;
  setelemT *elemp, *lastp;
  sizep= SETsizeaddr_(set);
  if ((sizep->i--)==0)         /*  if was a full set */
      sizep->i= set->maxsize;  /*     *sizep= (maxsize-1)+ 1 */
  if (nth < 0 || nth >= sizep->i) {
    qh_fprintf(qhmem.ferr, 6174, "qhull internal error (qh_setdelnth): nth %d is out-of-bounds for set:\n", nth);
    qh_setprint(qhmem.ferr, "", set);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  elemp= (setelemT *)SETelemaddr_(set, nth, void); /* nth valid by QH6174 */
  lastp= (setelemT *)SETelemaddr_(set, sizep->i-1, void);
  elem= elemp->p;
  elemp->p= lastp->p;      /* may overwrite itself */
  lastp->p= NULL;
  return elem;
} /* setdelnth */
References qhmemT::ferr, setelemT::i, setT::maxsize, NULL, setelemT::p, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem, qhmem_ERRqhull, SETelemaddr_, and SETsizeaddr_.
Referenced by qh_attachnewfacets(), qh_attachnewfacets(), qh_detvnorm(), qh_detvnorm(), qh_find_newvertex(), qh_find_newvertex(), qh_nextfurthest(), qh_nextfurthest(), testSetequalInEtc(), and testSetequalInEtc().
qh_setdelnthsorted()
void * qh_setdelnthsorted (setT * set, int nth)
{
  void *elem;
  setelemT *sizep;
  setelemT *newp, *oldp;
  sizep= SETsizeaddr_(set);
  if (nth < 0 || (sizep->i && nth >= sizep->i-1) || nth >= set->maxsize) {
    qh_fprintf(qhmem.ferr, 6175, "qhull internal error (qh_setdelnthsorted): nth %d is out-of-bounds for set:\n", nth);
    qh_setprint(qhmem.ferr, "", set);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  newp= (setelemT *)SETelemaddr_(set, nth, void);
  elem= newp->p;
  oldp= newp+1;
  while (((newp++)->p= (oldp++)->p))
    ; /* copy remaining elements and NULL */
  if ((sizep->i--)==0)         /*  if was a full set */
    sizep->i= set->maxsize;  /*     *sizep= (max size-1)+ 1 */
  return elem;
} /* setdelnthsorted */
References qhmemT::ferr, setelemT::i, setT::maxsize, NULL, setelemT::p, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem, qhmem_ERRqhull, SETelemaddr_, and SETsizeaddr_.
Referenced by qh_renameridgevertex(), qh_renameridgevertex(), testSetdelSetadd(), testSetdelSetadd(), testSetdelsortedEtc(), testSetdelsortedEtc(), testSetlastEtc(), and testSetlastEtc().
qh_setdelsorted()
void * qh_setdelsorted (setT * set, void * newelem)
{
  setelemT *sizep;
  setelemT *newp, *oldp;
  if (!set)
    return NULL;
  newp= (setelemT *)SETaddr_(set, void);
  while(newp->p != oldelem && newp->p)
    newp++;
  if (newp->p) {
    oldp= newp+1;
    while (((newp++)->p= (oldp++)->p))
      ; /* copy remaining elements */
    sizep= SETsizeaddr_(set);
    if ((sizep->i--)==0)    /*  if was a full set */
      sizep->i= set->maxsize;  /*     *sizep= (max size-1)+ 1 */
    return oldelem;
  }
  return NULL;
} /* setdelsorted */
qh_setduplicate()
setT * qh_setduplicate (setT * set, int elemsize)
{
  void          *elem, **elemp, *newElem;
  setT          *newSet;
  int           size;
  if (!(size= qh_setsize(set)))
    return NULL;
  newSet= qh_setnew(size);
  FOREACHelem_(set) {
    newElem= qh_memalloc(elemsize);
    memcpy(newElem, elem, (size_t)elemsize);
    qh_setappend(&newSet, newElem);
  }
  return newSet;
} /* setduplicate */
References FOREACHelem_, memcpy, NULL, qh_memalloc(), qh_setappend(), qh_setnew(), qh_setsize(), and size.
qh_setendpointer()
void ** qh_setendpointer (setT * set)
{
  setelemT *sizep= SETsizeaddr_(set);
  int n= sizep->i;
  return (n ? &set->e[n-1].p : &sizep->p);
} /* qh_setendpointer */
qh_setequal()
int qh_setequal (setT * setA, setT * setB)
{
  void **elemAp, **elemBp;
  int sizeA= 0, sizeB= 0;
  if (setA) {
    SETreturnsize_(setA, sizeA);
  }
  if (setB) {
    SETreturnsize_(setB, sizeB);
  }
  if (sizeA != sizeB)
    return 0;
  if (!sizeA)
    return 1;
  elemAp= SETaddr_(setA, void);
  elemBp= SETaddr_(setB, void);
  if (!memcmp((char *)elemAp, (char *)elemBp, sizeA*SETelemsize))
    return 1;
  return 0;
} /* setequal */
qh_setequal_except()
int qh_setequal_except (setT * setA, void * skipelemA, setT * setB, void * skipelemB)
{
  void **elemA, **elemB;
  int skip=0;
  elemA= SETaddr_(setA, void);
  elemB= SETaddr_(setB, void);
  while (1) {
    if (*elemA == skipelemA) {
      skip++;
      elemA++;
    }
    if (skipelemB) {
      if (*elemB == skipelemB) {
        skip++;
        elemB++;
      }
    }else if (*elemA != *elemB) {
      skip++;
      if (!(skipelemB= *elemB++))
        return 0;
    }
    if (!*elemA)
      break;
    if (*elemA++ != *elemB++)
      return 0;
  }
  if (skip != 2 || *elemB)
    return 0;
  return 1;
} /* setequal_except */
qh_setequal_skip()
int qh_setequal_skip (setT * setA, int skipA, setT * setB, int skipB)
{
  void **elemA, **elemB, **skipAp, **skipBp;
  elemA= SETaddr_(setA, void);
  elemB= SETaddr_(setB, void);
  skipAp= SETelemaddr_(setA, skipA, void);
  skipBp= SETelemaddr_(setB, skipB, void);
  while (1) {
    if (elemA == skipAp)
      elemA++;
    if (elemB == skipBp)
      elemB++;
    if (!*elemA)
      break;
    if (*elemA++ != *elemB++)
      return 0;
  }
  if (*elemB)
    return 0;
  return 1;
} /* setequal_skip */
qh_setfree()
void qh_setfree (setT ** set)
{
  int size;
  void **freelistp;  /* used if !qh_NOmem by qh_memfree_() */
  if (*setp) {
    size= sizeof(setT) + ((*setp)->maxsize)*SETelemsize;
    if (size <= qhmem.LASTsize) {
      qh_memfree_(*setp, size, freelistp);
    }else
      qh_memfree(*setp, size);
    *setp= NULL;
  }
} /* setfree */
References qhmemT::LASTsize, NULL, qh_memfree(), qh_memfree_, qhmem, SETelemsize, and size.
Referenced by qh_attachnewfacets(), qh_attachnewfacets(), qh_delfacet(), qh_delfacet(), qh_delridge(), qh_delridge(), qh_delvertex(), qh_delvertex(), qh_find_newvertex(), qh_find_newvertex(), qh_freebuffers(), qh_freebuffers(), qh_freebuild(), qh_freebuild(), qh_makenew_nonsimplicial(), qh_makenew_nonsimplicial(), qh_matchnewfacets(), qh_matchnewfacets(), qh_mergecycle_ridges(), qh_mergecycle_ridges(), qh_mergesimplex(), qh_mergesimplex(), qh_mergevertices(), qh_mergevertices(), qh_nearcoplanar(), qh_nearcoplanar(), qh_nextfurthest(), qh_nextfurthest(), qh_order_vertexneighbors(), qh_order_vertexneighbors(), qh_outcoplanar(), qh_outcoplanar(), qh_partitionall(), qh_partitionall(), qh_printfacet3geom_simplicial(), qh_printfacet3geom_simplicial(), qh_printfacet4geom_simplicial(), qh_printfacet4geom_simplicial(), qh_setappend_set(), qh_setfree2(), qh_setlarger(), qh_settempfree(), qh_settempfree_all(), qh_triangulate(), qh_triangulate(), testSetappendSet(), testSetappendSet(), testSetappendSettruncate(), testSetappendSettruncate(), testSetcompactCopy(), testSetcompactCopy(), testSetdelSetadd(), testSetdelSetadd(), testSetdelsortedEtc(), testSetdelsortedEtc(), testSetequalInEtc(), testSetequalInEtc(), testSetlastEtc(), testSetlastEtc(), testSettemp(), and testSettemp().
qh_setfree2()
void qh_setfree2 (setT ** setp, int elemsize)
{
  void          *elem, **elemp;
  FOREACHelem_(*setp)
    qh_memfree(elem, elemsize);
  qh_setfree(setp);
} /* setfree2 */
References FOREACHelem_, qh_memfree(), and qh_setfree().
qh_setfreelong()
void qh_setfreelong (setT ** set)
{
  int size;
  if (*setp) {
    size= sizeof(setT) + ((*setp)->maxsize)*SETelemsize;
    if (size > qhmem.LASTsize) {
      qh_memfree(*setp, size);
      *setp= NULL;
    }
  }
} /* setfreelong */
References qhmemT::LASTsize, NULL, qh_memfree(), qhmem, SETelemsize, and size.
Referenced by qh_freebuild(), qh_freebuild(), testSetdelsortedEtc(), testSetdelsortedEtc(), testSetequalInEtc(), testSetequalInEtc(), testSetlastEtc(), testSetlastEtc(), testSettemp(), and testSettemp().
qh_setin()
int qh_setin (setT * set, void * setelem)
{
  void *elem, **elemp;
  FOREACHelem_(set) {
    if (elem == setelem)
      return 1;
  }
  return 0;
} /* setin */
qh_setindex()
int qh_setindex (setT * set, void * setelem)
{
  void **elem;
  int size, i;
  if (!set)
    return -1;
  SETreturnsize_(set, size);
  if (size > set->maxsize)
    return -1;
  elem= SETaddr_(set, void);
  for (i=0; i < size; i++) {
    if (*elem++ == atelem)
      return i;
  }
  return -1;
} /* setindex */
qh_setlarger()
void qh_setlarger (setT ** setp)
{
  int size= 1;
  setT *newset, *set, **setp, *oldset;
  setelemT *sizep;
  setelemT *newp, *oldp;
  if (*oldsetp) {
    oldset= *oldsetp;
    SETreturnsize_(oldset, size);
    qhmem.cntlarger++;
    qhmem.totlarger += size+1;
    newset= qh_setnew(2 * size);
    oldp= (setelemT *)SETaddr_(oldset, void);
    newp= (setelemT *)SETaddr_(newset, void);
    memcpy((char *)newp, (char *)oldp, (size_t)(size+1) * SETelemsize);
    sizep= SETsizeaddr_(newset);
    sizep->i= size+1;
    FOREACHset_((setT *)qhmem.tempstack) {
      if (set == oldset)
        *(setp-1)= newset;
    }
    qh_setfree(oldsetp);
  }else
    newset= qh_setnew(3);
  *oldsetp= newset;
} /* setlarger */
References qhmemT::cntlarger, FOREACHset_, setelemT::i, memcpy, qh_setfree(), qh_setnew(), qhmem, SETaddr_, SETelemsize, SETreturnsize_, SETsizeaddr_, size, qhmemT::tempstack, and qhmemT::totlarger.
Referenced by qh_setaddnth(), qh_setappend(), qh_setappend2ndlast(), testSetequalInEtc(), and testSetequalInEtc().
qh_setlast()
void * qh_setlast (setT * set)
{
  int size;
  if (set) {
    size= SETsizeaddr_(set)->i;
    if (!size)
      return SETelem_(set, set->maxsize - 1);
    else if (size > 1)
      return SETelem_(set, size - 2);
  }
  return NULL;
} /* setlast */
qh_setnew()
setT * qh_setnew (int size)
{
  setT *set;
  int sizereceived; /* used if !qh_NOmem */
  int size;
  void **freelistp; /* used if !qh_NOmem by qh_memalloc_() */
  if (!setsize)
    setsize++;
  size= sizeof(setT) + setsize * SETelemsize;
  if (size>0 && size <= qhmem.LASTsize) {
    qh_memalloc_(size, freelistp, set, setT);
#ifndef qh_NOmem
    sizereceived= qhmem.sizetable[ qhmem.indextable[size]];
    if (sizereceived > size)
      setsize += (sizereceived - size)/SETelemsize;
#endif
  }else
    set= (setT*)qh_memalloc(size);
  set->maxsize= setsize;
  set->e[setsize].i= 1;
  set->e[0].p= NULL;
  return(set);
} /* setnew */
References setT::e, setelemT::i, qhmemT::indextable, qhmemT::LASTsize, setT::maxsize, NULL, setelemT::p, qh_memalloc(), qh_memalloc_, qhmem, SETelemsize, size, and qhmemT::sizetable.
Referenced by qh_initqhull_buffers(), qh_initqhull_buffers(), qh_makenew_nonsimplicial(), qh_makenew_nonsimplicial(), qh_newfacet(), qh_newfacet(), qh_newhashtable(), qh_newhashtable(), qh_partitionall(), qh_partitionall(), qh_setappend_set(), qh_setcopy(), qh_setduplicate(), qh_setlarger(), qh_setnew_delnthsorted(), qh_settemp(), qh_vertexintersect_new(), qh_vertexintersect_new(), qh_vertexneighbors(), qh_vertexneighbors(), testSetappendSet(), testSetappendSet(), testSetappendSettruncate(), testSetappendSettruncate(), testSetcompactCopy(), testSetcompactCopy(), testSetdelSetadd(), testSetdelSetadd(), testSetdelsortedEtc(), and testSetdelsortedEtc().
qh_setnew_delnthsorted()
setT * qh_setnew_delnthsorted (setT * set, int size, int nth, int prepend)
{
  setT *newset;
  void **oldp, **newp;
  int tailsize= size - nth -1, newsize;
  if (tailsize < 0) {
    qh_fprintf(qhmem.ferr, 6176, "qhull internal error (qh_setnew_delnthsorted): nth %d is out-of-bounds for set:\n", nth);
    qh_setprint(qhmem.ferr, "", set);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  newsize= size-1 + prepend;
  newset= qh_setnew(newsize);
  newset->e[newset->maxsize].i= newsize+1;  /* may be overwritten */
  oldp= SETaddr_(set, void);
  newp= SETaddr_(newset, void) + prepend;
  switch (nth) {
  case 0:
    break;
  case 1:
    *(newp++)= *oldp++;
    break;
  case 2:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  case 3:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  case 4:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  default:
    memcpy((char *)newp, (char *)oldp, (size_t)nth * SETelemsize);
    newp += nth;
    oldp += nth;
    break;
  }
  oldp++;
  switch (tailsize) {
  case 0:
    break;
  case 1:
    *(newp++)= *oldp++;
    break;
  case 2:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  case 3:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  case 4:
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    *(newp++)= *oldp++;
    break;
  default:
    memcpy((char *)newp, (char *)oldp, (size_t)tailsize * SETelemsize);
    newp += tailsize;
  }
  *newp= NULL;
  return(newset);
} /* setnew_delnthsorted */
References setT::e, qhmemT::ferr, setelemT::i, setT::maxsize, memcpy, NULL, qh_errexit(), qh_fprintf(), qh_setnew(), qh_setprint(), qhmem, qhmem_ERRqhull, SETaddr_, SETelemsize, and size.
Referenced by qh_createsimplex(), qh_createsimplex(), qh_facetintersect(), qh_facetintersect(), qh_makeridges(), qh_makeridges(), qh_mergecycle_ridges(), qh_mergecycle_ridges(), qh_printfacet3geom_simplicial(), qh_printfacet3geom_simplicial(), qh_printfacet4geom_simplicial(), qh_printfacet4geom_simplicial(), testSetlastEtc(), and testSetlastEtc().
qh_setprint()
void qh_setprint (FILE * fp, const char * string, setT * set)
{
  int size, k;
  if (!set)
    qh_fprintf(fp, 9346, "%s set is null\n", string);
  else {
    SETreturnsize_(set, size);
    qh_fprintf(fp, 9347, "%s set=%p maxsize=%d size=%d elems=",
             string, set, set->maxsize, size);
    if (size > set->maxsize)
      size= set->maxsize+1;
    for (k=0; k < size; k++)
      qh_fprintf(fp, 9348, " %p", set->e[k].p);
    qh_fprintf(fp, 9349, "\n");
  }
} /* setprint */
References setT::e, setT::maxsize, setelemT::p, qh_fprintf(), SETreturnsize_, and size.
Referenced by qh_checkfacet(), qh_checkfacet(), qh_setaddnth(), qh_setcheck(), qh_setdelnth(), qh_setdelnthsorted(), qh_setnew_delnthsorted(), qh_setreplace(), qh_setsize(), qh_settruncate(), and qh_setzero().
qh_setreplace()
void qh_setreplace (setT * set, void * oldelem, void * newelem)
{
  void **elemp;
  elemp= SETaddr_(set, void);
  while (*elemp != oldelem && *elemp)
    elemp++;
  if (*elemp)
    *elemp= newelem;
  else {
    qh_fprintf(qhmem.ferr, 6177, "qhull internal error (qh_setreplace): elem %p not found in set\n",
       oldelem);
    qh_setprint(qhmem.ferr, "", set);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
} /* setreplace */
References qhmemT::ferr, NULL, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem, qhmem_ERRqhull, and SETaddr_.
Referenced by qh_attachnewfacets(), qh_attachnewfacets(), qh_makenew_nonsimplicial(), qh_makenew_nonsimplicial(), qh_mergecycle_neighbors(), qh_mergecycle_neighbors(), qh_mergefacet2d(), qh_mergefacet2d(), qh_mergeneighbors(), qh_mergeneighbors(), qh_mergesimplex(), qh_mergesimplex(), qh_mergevertex_neighbors(), qh_mergevertex_neighbors(), qh_triangulate_link(), qh_triangulate_link(), testSetequalInEtc(), and testSetequalInEtc().
qh_setsize()
int qh_setsize (setT * set)
{
  int size;
  setelemT *sizep;
  if (!set)
    return(0);
  sizep= SETsizeaddr_(set);
  if ((size= sizep->i)) {
    size--;
    if (size > set->maxsize) {
      qh_fprintf(qhmem.ferr, 6178, "qhull internal error (qh_setsize): current set size %d is greater than maximum size %d\n",
               size, set->maxsize);
      qh_setprint(qhmem.ferr, "set: ", set);
      qh_errexit(qhmem_ERRqhull, NULL, NULL);
    }
  }else
    size= set->maxsize;
  return size;
} /* setsize */
References qhmemT::ferr, setelemT::i, setT::maxsize, NULL, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem, qhmem_ERRqhull, SETsizeaddr_, and size.
Referenced by addDelaunay(), addDelaunay(), addhalf(), addhalf(), checkSetContents(), checkSetContents(), qh_all_merges(), qh_all_merges(), qh_basevertices(), qh_basevertices(), qh_check_bestdist(), qh_check_bestdist(), qh_checkfacet(), qh_checkfacet(), qh_checkpolygon(), qh_checkpolygon(), qh_checkvertex(), qh_checkvertex(), qh_countfacets(), qh_countfacets(), qh_degen_redundant_facet(), qh_degen_redundant_facet(), qh_degen_redundant_neighbors(), qh_degen_redundant_neighbors(), qh_deletevisible(), qh_deletevisible(), qh_detvridge(), qh_detvridge(), qh_facet3vertex(), qh_facet3vertex(), qh_facetcenter(), qh_facetcenter(), qh_find_newvertex(), qh_find_newvertex(), qh_findbestneighbor(), qh_findbestneighbor(), qh_getcenter(), qh_getcenter(), qh_getcentrum(), qh_getcentrum(), qh_getmergeset(), qh_getmergeset(), qh_getmergeset_initial(), qh_getmergeset_initial(), qh_initialvertices(), qh_initialvertices(), qh_markkeep(), qh_markkeep(), qh_matchnewfacets(), qh_matchnewfacets(), qh_maxsimplex(), qh_maxsimplex(), qh_maydropneighbor(), qh_maydropneighbor(), qh_merge_degenredundant(), qh_merge_degenredundant(), qh_mergecycle_facets(), qh_mergecycle_facets(), qh_mergefacet(), qh_mergefacet(), qh_mergevertices(), qh_mergevertices(), qh_neighbor_intersections(), qh_neighbor_intersections(), qh_nextfurthest(), qh_nextfurthest(), qh_order_vertexneighbors(), qh_order_vertexneighbors(), qh_partitionvisible(), qh_partitionvisible(), qh_point(), qh_point(), qh_pointfacet(), qh_pointfacet(), qh_pointvertex(), qh_pointvertex(), qh_printafacet(), qh_printafacet(), qh_printbegin(), qh_printbegin(), qh_printextremes(), qh_printextremes(), qh_printextremes_2d(), qh_printextremes_2d(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_points(), qh_printfacet3geom_points(), qh_printfacet3math(), qh_printfacet3math(), qh_printfacet3vertex(), qh_printfacet3vertex(), qh_printfacetheader(), qh_printfacetheader(), qh_printfacetNvertex_simplicial(), qh_printfacetNvertex_simplicial(), qh_printfacetridges(), qh_printfacetridges(), qh_printfacets(), qh_printfacets(), qh_printhyperplaneintersection(), qh_printhyperplaneintersection(), qh_printneighborhood(), qh_printneighborhood(), qh_printpoints_out(), qh_printpoints_out(), qh_printsummary(), qh_printsummary(), qh_printvneighbors(), qh_printvneighbors(), qh_printvoronoi(), qh_printvoronoi(), qh_printvridge(), qh_printvridge(), qh_produce_output(), qh_produce_output(), qh_produce_output2(), qh_produce_output2(), qh_qhull(), qh_qhull(), qh_remove_extravertices(), qh_remove_extravertices(), qh_rename_sharedvertex(), qh_rename_sharedvertex(), qh_renamevertex(), qh_renamevertex(), qh_setduplicate(), qh_settemp(), qh_settempfree(), qh_settemppop(), qh_settemppush(), qh_tracemerging(), qh_tracemerging(), qh_triangulate(), qh_triangulate(), qh_updatetested(), qh_updatetested(), qh_vertexridges(), qh_vertexridges(), qh_voronoi_center(), qh_voronoi_center(), testSetappendSet(), testSetappendSet(), testSetcompactCopy(), testSetcompactCopy(), testSetdelSetadd(), testSetdelSetadd(), testSetdelsortedEtc(), testSetdelsortedEtc(), testSetequalInEtc(), testSetequalInEtc(), testSetlastEtc(), testSetlastEtc(), testSettemp(), and testSettemp().
qh_settemp()
setT * qh_settemp (int setsize)
{
  setT *newset;
  newset= qh_setnew(setsize);
  qh_setappend(&qhmem.tempstack, newset);
  if (qhmem.IStracing >= 5)
    qh_fprintf(qhmem.ferr, 8123, "qh_settemp: temp set %p of %d elements, depth %d\n",
       newset, newset->maxsize, qh_setsize(qhmem.tempstack));
  return newset;
} /* settemp */
References qhmemT::ferr, qhmemT::IStracing, setT::maxsize, qh_fprintf(), qh_setappend(), qh_setnew(), qh_setsize(), qhmem, and qhmemT::tempstack.
Referenced by qh_basevertices(), qh_basevertices(), qh_createsimplex(), qh_createsimplex(), qh_detvnorm(), qh_detvnorm(), qh_detvridge(), qh_detvridge(), qh_detvridge3(), qh_detvridge3(), qh_eachvoronoi(), qh_eachvoronoi(), qh_facet3vertex(), qh_facet3vertex(), qh_facetcenter(), qh_facetcenter(), qh_facetvertices(), qh_facetvertices(), qh_flippedmerges(), qh_flippedmerges(), qh_forcedmerges(), qh_forcedmerges(), qh_initialvertices(), qh_initialvertices(), qh_markkeep(), qh_markkeep(), qh_maxmin(), qh_maxmin(), qh_mergevertices(), qh_mergevertices(), qh_nearvertex(), qh_nearvertex(), qh_order_vertexneighbors(), qh_order_vertexneighbors(), qh_partitionall(), qh_partitionall(), qh_pointfacet(), qh_pointfacet(), qh_pointvertex(), qh_pointvertex(), qh_postmerge(), qh_postmerge(), qh_premerge(), qh_premerge(), qh_printextremes(), qh_printextremes(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_points(), qh_printfacet3geom_points(), qh_printfacet3geom_simplicial(), qh_printfacet3geom_simplicial(), qh_printfacet3math(), qh_printfacet3math(), qh_printneighborhood(), qh_printneighborhood(), qh_printpoints_out(), qh_printpoints_out(), qh_printvneighbors(), qh_printvneighbors(), qh_rename_sharedvertex(), qh_rename_sharedvertex(), qh_triangulate(), qh_triangulate(), qh_vertexridges(), qh_vertexridges(), qh_voronoi_center(), qh_voronoi_center(), testSettemp(), and testSettemp().
qh_settempfree()
void qh_settempfree (setT ** set)
{
  setT *stackedset;
  if (!*set)
    return;
  stackedset= qh_settemppop();
  if (stackedset != *set) {
    qh_settemppush(stackedset);
    qh_fprintf(qhmem.ferr, 6179, "qhull internal error (qh_settempfree): set %p(size %d) was not last temporary allocated(depth %d, set %p, size %d)\n",
             *set, qh_setsize(*set), qh_setsize(qhmem.tempstack)+1,
             stackedset, qh_setsize(stackedset));
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  qh_setfree(set);
} /* settempfree */
References qhmemT::ferr, NULL, qh_errexit(), qh_fprintf(), qh_setfree(), qh_setsize(), qh_settemppop(), qh_settemppush(), qhmem, qhmem_ERRqhull, and qhmemT::tempstack.
Referenced by orgQhull::QhullVertexSet::freeQhSetTemp(), qh_check_bestdist(), qh_check_bestdist(), qh_check_maxout(), qh_check_maxout(), qh_checkfacet(), qh_checkfacet(), qh_createsimplex(), qh_createsimplex(), qh_detvnorm(), qh_detvnorm(), qh_detvridge(), qh_detvridge(), qh_detvridge3(), qh_detvridge3(), qh_eachvoronoi(), qh_eachvoronoi(), qh_facetcenter(), qh_facetcenter(), qh_find_newvertex(), qh_find_newvertex(), qh_flippedmerges(), qh_flippedmerges(), qh_forcedmerges(), qh_forcedmerges(), qh_initbuild(), qh_initbuild(), qh_initialvertices(), qh_initialvertices(), qh_markkeep(), qh_markkeep(), qh_mergecycle_vneighbors(), qh_mergecycle_vneighbors(), qh_nearvertex(), qh_nearvertex(), qh_neighbor_intersections(), qh_neighbor_intersections(), qh_partitionall(), qh_partitionall(), qh_postmerge(), qh_postmerge(), qh_premerge(), qh_premerge(), qh_printbegin(), qh_printbegin(), qh_printextremes(), qh_printextremes(), qh_printextremes_2d(), qh_printextremes_2d(), qh_printextremes_d(), qh_printextremes_d(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_nonsimplicial(), qh_printfacet3geom_points(), qh_printfacet3geom_points(), qh_printfacet3geom_simplicial(), qh_printfacet3geom_simplicial(), qh_printfacet3math(), qh_printfacet3math(), qh_printfacet3vertex(), qh_printfacet3vertex(), qh_printfacets(), qh_printfacets(), qh_printneighborhood(), qh_printneighborhood(), qh_printpoints_out(), qh_printpoints_out(), qh_printvdiagram(), qh_printvdiagram(), qh_printvertexlist(), qh_printvertexlist(), qh_printvneighbors(), qh_printvneighbors(), qh_printvoronoi(), qh_printvoronoi(), qh_redundant_vertex(), qh_redundant_vertex(), qh_rename_sharedvertex(), qh_rename_sharedvertex(), qh_triangulate(), qh_triangulate(), qh_vertexintersect(), qh_vertexintersect(), qh_voronoi_center(), qh_voronoi_center(), testSettemp(), and testSettemp().
qh_settempfree_all()
void qh_settempfree_all (void)
{
  setT *set, **setp;
  FOREACHset_(qhmem.tempstack)
    qh_setfree(&set);
  qh_setfree(&qhmem.tempstack);
} /* settempfree_all */
References FOREACHset_, qh_setfree(), qhmem, and qhmemT::tempstack.
Referenced by qh_freebuild(), qh_freebuild(), testSettemp(), and testSettemp().
qh_settemppop()
setT * qh_settemppop (void)
{
  setT *stackedset;
  stackedset= (setT*)qh_setdellast(qhmem.tempstack);
  if (!stackedset) {
    qh_fprintf(qhmem.ferr, 6180, "qhull internal error (qh_settemppop): pop from empty temporary stack\n");
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  if (qhmem.IStracing >= 5)
    qh_fprintf(qhmem.ferr, 8124, "qh_settemppop: depth %d temp set %p of %d elements\n",
       qh_setsize(qhmem.tempstack)+1, stackedset, qh_setsize(stackedset));
  return stackedset;
} /* settemppop */
References qhmemT::ferr, qhmemT::IStracing, NULL, qh_errexit(), qh_fprintf(), qh_setdellast(), qh_setsize(), qhmem, qhmem_ERRqhull, and qhmemT::tempstack.
Referenced by qh_flippedmerges(), qh_flippedmerges(), qh_forcedmerges(), qh_forcedmerges(), qh_mergevertices(), qh_mergevertices(), qh_order_vertexneighbors(), qh_order_vertexneighbors(), qh_settempfree(), qh_settempfree(), testSettemp(), and testSettemp().
qh_settemppush()
void qh_settemppush (setT * set)
{
  if (!set) {
    qh_fprintf(qhmem.ferr, 6267, "qhull error (qh_settemppush): can not push a NULL temp\n");
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  qh_setappend(&qhmem.tempstack, set);
  if (qhmem.IStracing >= 5)
    qh_fprintf(qhmem.ferr, 8125, "qh_settemppush: depth %d temp set %p of %d elements\n",
      qh_setsize(qhmem.tempstack), set, qh_setsize(set));
} /* settemppush */
References qhmemT::ferr, qhmemT::IStracing, NULL, qh_errexit(), qh_fprintf(), qh_setappend(), qh_setsize(), qhmem, qhmem_ERRqhull, and qhmemT::tempstack.
Referenced by qh_checkfacet(), qh_checkfacet(), qh_flippedmerges(), qh_flippedmerges(), qh_forcedmerges(), qh_forcedmerges(), qh_neighbor_intersections(), qh_neighbor_intersections(), qh_rename_sharedvertex(), qh_rename_sharedvertex(), qh_settempfree(), qh_vertexintersect(), qh_vertexintersect(), testSettemp(), and testSettemp().
qh_settruncate()
void qh_settruncate (setT * set, int size)
{
  if (size < 0 || size > set->maxsize) {
    qh_fprintf(qhmem.ferr, 6181, "qhull internal error (qh_settruncate): size %d out of bounds for set:\n", size);
    qh_setprint(qhmem.ferr, "", set);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  set->e[set->maxsize].i= size+1;   /* maybe overwritten */
  set->e[size].p= NULL;
} /* settruncate */
References setT::e, qhmemT::ferr, setelemT::i, setT::maxsize, NULL, setelemT::p, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem, qhmem_ERRqhull, and size.
Referenced by qh_createsimplex(), qh_createsimplex(), qh_deletevisible(), qh_deletevisible(), qh_eachvoronoi(), qh_eachvoronoi(), qh_freebuild(), qh_freebuild(), qh_mergecycle_ridges(), qh_mergecycle_ridges(), qh_partitionall(), qh_partitionall(), qh_setcompact(), testSetappendSet(), testSetappendSet(), testSetappendSettruncate(), and testSetappendSettruncate().
qh_setunique()
int qh_setunique (setT ** set, void * elem)
{
  if (!qh_setin(*set, elem)) {
    qh_setappend(set, elem);
    return 1;
  }
  return 0;
} /* setunique */
References qh_setappend(), and qh_setin().
Referenced by qh_detvridge(), qh_detvridge(), qh_detvridge3(), qh_detvridge3(), qh_eachvoronoi(), qh_eachvoronoi(), qh_maxsimplex(), qh_maxsimplex(), testSetlastEtc(), and testSetlastEtc().
qh_setzero()
void qh_setzero (setT * set, int idx, int size)
{
  int count;
  if (idx < 0 || idx >= size || size > set->maxsize) {
    qh_fprintf(qhmem.ferr, 6182, "qhull internal error (qh_setzero): index %d or size %d out of bounds for set:\n", idx, size);
    qh_setprint(qhmem.ferr, "", set);
    qh_errexit(qhmem_ERRqhull, NULL, NULL);
  }
  set->e[set->maxsize].i=  size+1;  /* may be overwritten */
  count= size - idx + 1;   /* +1 for NULL terminator */
  memset((char *)SETelemaddr_(set, idx, void), 0, (size_t)count * SETelemsize);
} /* setzero */
References count, setT::e, qhmemT::ferr, setelemT::i, setT::maxsize, memset, NULL, qh_errexit(), qh_fprintf(), qh_setprint(), qhmem, qhmem_ERRqhull, SETelemaddr_, SETelemsize, and size.
Referenced by qh_newhashtable(), qh_newhashtable(), qh_pointfacet(), qh_pointfacet(), qh_pointvertex(), qh_pointvertex(), qh_printextremes(), qh_printextremes(), qh_printpoints_out(), qh_printpoints_out(), qh_printvneighbors(), qh_printvneighbors(), testSetlastEtc(), and testSetlastEtc().