OrcaSlicer: Slic3r::GUI::HttpServer Class Reference
Slic3r::GUI::HttpServer Class Reference
#include <src/slic3r/GUI/HttpServer.hpp>
Public Member Functions
HttpServer ()
bool is_started ()
void start ()
void stop ()
Public Attributes
boost::thread m_http_server_thread
bool start_http_server = false
Detailed Description
Constructor & Destructor Documentation
HttpServer()
Slic3r::GUI::HttpServer::HttpServer ()
{
    ;
}
Member Function Documentation
is_started()
bool Slic3r::GUI::HttpServer::is_started () inline
{ return start_http_server; }
Referenced by Slic3r::GUI::GUI_App::start_http_server().
start()
void Slic3r::GUI::HttpServer::start ()
{
    BOOST_LOG_TRIVIAL(info) << "start_http_service...";
    start_http_server = true;
    m_http_server_thread = Slic3r::create_thread(
        [this] {
            boost::asio::io_service io_service;
            boost::asio::ip::tcp::endpoint endpoint{ boost::asio::ip::tcp::v4(), LOCALHOST_PORT};
            boost::asio::ip::tcp::acceptor acceptor { io_service, endpoint};
            acceptor.listen();
            accept_and_run(acceptor, io_service);
            while (start_http_server) {
                io_service.run();
            }
        });
}
References Slic3r::GUI::accept_and_run(), Slic3r::create_thread(), and LOCALHOST_PORT.
Referenced by Slic3r::GUI::GUI_App::start_http_server().
stop()
void Slic3r::GUI::HttpServer::stop ()
{
    start_http_server = false;
    if (m_http_server_thread.joinable())
        m_http_server_thread.join();
}
Referenced by Slic3r::GUI::GUI_App::stop_http_server().
Member Data Documentation
m_http_server_thread
boost::thread Slic3r::GUI::HttpServer::m_http_server_thread
start_http_server
bool Slic3r::GUI::HttpServer::start_http_server = false
The documentation for this class was generated from the following files:
src/slic3r/GUI/HttpServer.hpp
src/slic3r/GUI/HttpServer.cpp