OrcaSlicer: Slic3r::opt Namespace Reference
Slic3r::opt Namespace Reference
Namespaces
namespace detail
Classes
struct always_false
class Bound
class Optimizer
class Optimizer< AlgBruteForce >
class Optimizer< M, detail::NLoptOnly< M > >
struct Result
struct ScoreGradient
class StopCriteria
Typedefs
using AlgBruteForce = detail::AlgBurteForce
using AlgNLoptGenetic = detail::NLoptAlgComb< NLOPT_GN_ESCH >
using AlgNLoptSubplex = detail::NLoptAlg< NLOPT_LN_SBPLX >
using AlgNLoptSimplex = detail::NLoptAlg< NLOPT_LN_NELDERMEAD >
using AlgNLoptDIRECT = detail::NLoptAlg< NLOPT_GN_DIRECT >
using AlgNLoptMLSL = detail::NLoptAlg< NLOPT_GN_MLSL >
template<size_t N>
using Input = std::array< double, N >
template<size_t N>
using Bounds = std::array< Bound, N >
Functions
template<size_t N>
Bounds< N > bounds (const Bound(&b)[N])
template<size_t N>
Input< N > initvals (const double(&a)[N])
template<size_t N>
auto score_gradient (double s, const double(&grad)[N])
Class Documentation
Slic3r::opt::Result
struct Slic3r::opt::Result
template<size_t N>
struct Slic3r::opt::Result< N >
Class Members
array< double, N > optimum
int resultcode
double score
Typedef Documentation
AlgBruteForce
using Slic3r::opt::AlgBruteForce = typedef detail::AlgBurteForce
AlgNLoptDIRECT
using Slic3r::opt::AlgNLoptDIRECT = typedef detail::NLoptAlg<NLOPT_GN_DIRECT>
AlgNLoptGenetic
using Slic3r::opt::AlgNLoptGenetic = typedef detail::NLoptAlgComb<NLOPT_GN_ESCH>
AlgNLoptMLSL
using Slic3r::opt::AlgNLoptMLSL = typedef detail::NLoptAlg<NLOPT_GN_MLSL>
AlgNLoptSimplex
using Slic3r::opt::AlgNLoptSimplex = typedef detail::NLoptAlg<NLOPT_LN_NELDERMEAD>
AlgNLoptSubplex
using Slic3r::opt::AlgNLoptSubplex = typedef detail::NLoptAlg<NLOPT_LN_SBPLX>
Bounds
template<size_t N> using Slic3r::opt::Bounds = typedef std::array<Bound, N>
Input
template<size_t N> using Slic3r::opt::Input = typedef std::array<double, N>
Function Documentation
bounds()
template<size_t N> Bounds< N > Slic3r::opt::bounds (const Bound(&) b[N])
{ return detail::to_arr(b); }
References bounds(), and Slic3r::opt::detail::to_arr().
Referenced by bounds(), Slic3r::sla::find_best_misalignment_rotation(), Slic3r::sla::find_least_supports_rotation(), Slic3r::opt::detail::NLoptOpt< NLoptAlgComb< glob, loc > >::optimize(), Slic3r::opt::detail::AlgBurteForce::optimize(), Slic3r::opt::Optimizer< AlgBruteForce >::optimize(), Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::optimize(), Slic3r::opt::Optimizer< M, detail::NLoptOnly< M > >::optimize(), Slic3r::opt::detail::AlgBurteForce::run(), and Slic3r::opt::detail::NLoptOpt< NLoptAlg< alg > >::set_up().
initvals()
template<size_t N> Input< N > Slic3r::opt::initvals (const double(&) a[N])
{ return detail::to_arr(a); }
References Slic3r::opt::detail::to_arr().
Referenced by Slic3r::sla::find_best_misalignment_rotation(), and Slic3r::sla::find_least_supports_rotation().
score_gradient()
template<size_t N> auto Slic3r::opt::score_gradient (double s, const double(&) grad[N])
{
    return ScoreGradient<N>(s, detail::to_arr(grad));
}
References Slic3r::opt::detail::to_arr().