OrcaSlicer: nlohmann::detail::parse_error Class Reference
nlohmann::detail::parse_error Class Reference
exception indicating a parse error
#include <src/nlohmann/detail/exceptions.hpp>
Public Member Functions
const char * what () const noexcept override
returns the explanatory string
Static Public Member Functions
template<typename BasicJsonType >
static parse_error create (int id_, const position_t &pos, const std::string &what_arg, const BasicJsonType &context)
create a parse error exception
template<typename BasicJsonType >
static parse_error create (int id_, std::size_t byte_, const std::string &what_arg, const BasicJsonType &context)
Public Attributes
const std::size_t byte
byte index of the parse error
const int id
the id of the exception
Static Protected Member Functions
static std::string name (const std::string &ename, int id_)
template<typename BasicJsonType >
static std::string diagnostics (const BasicJsonType &leaf_element)
Private Member Functions
parse_error (int id_, std::size_t byte_, const char *what_arg)
Static Private Member Functions
static std::string position_string (const position_t &pos)
Private Attributes
std::runtime_error m
an exception object as storage for error messages
Detailed Description
exception indicating a parse error
This exception is thrown by the library when a parse error occurs. Parse errors can occur during the deserialization of JSON text, CBOR, MessagePack, as well as when using JSON Patch.
Member byte holds the byte index of the last read character in the input file.
Exceptions have ids 1xx.
name / id example message description
json.exception.parse_error.101 parse error at 2: unexpected end of input; expected string literal This error indicates a syntax error while deserializing a JSON text. The error message describes that an unexpected token (character) was encountered, and the member byte indicates the error position.
json.exception.parse_error.102 parse error at 14: missing or wrong low surrogate JSON uses the \uxxxx format to describe Unicode characters. Code points above above 0xFFFF are split into two \uxxxx entries ("surrogate pairs"). This error indicates that the surrogate pair is incomplete or contains an invalid code point.
json.exception.parse_error.103 parse error: code points above 0x10FFFF are invalid Unicode supports code points up to 0x10FFFF. Code points above 0x10FFFF are invalid.
json.exception.parse_error.104 parse error: JSON patch must be an array of objects RFC 6902 requires a JSON Patch document to be a JSON document that represents an array of objects.
json.exception.parse_error.105 parse error: operation must have string member 'op' An operation of a JSON Patch document must contain exactly one "op" member, whose value indicates the operation to perform. Its value must be one of "add", "remove", "replace", "move", "copy", or "test"; other values are errors.
json.exception.parse_error.106 parse error: array index '01' must not begin with '0' An array index in a JSON Pointer (RFC 6901) may be 0 or any number without a leading 0.
json.exception.parse_error.107 parse error: JSON pointer must be empty or begin with '/' - was: 'foo' A JSON Pointer must be a Unicode string containing a sequence of zero or more reference tokens, each prefixed by a / character.
json.exception.parse_error.108 parse error: escape character '~' must be followed with '0' or '1' In a JSON Pointer, only ~0 and ~1 are valid escape sequences.
json.exception.parse_error.109 parse error: array index 'one' is not a number A JSON Pointer array index must be a number.
json.exception.parse_error.110 parse error at 1: cannot read 2 bytes from vector When parsing CBOR or MessagePack, the byte vector ends before the complete value has been read.
json.exception.parse_error.112 parse error at 1: error reading CBOR; last byte: 0xF8 Not all types of CBOR or MessagePack are supported. This exception occurs if an unsupported byte was read.
json.exception.parse_error.113 parse error at 2: expected a CBOR string; last byte: 0x98 While parsing a map key, a value that is not a string has been read.
json.exception.parse_error.114 parse error: Unsupported BSON record type 0x0F The parsing of the corresponding BSON record type is not implemented (yet).
json.exception.parse_error.115 parse error at byte 5: syntax error while parsing UBJSON high-precision number: invalid number text: 1A A UBJSON high-precision number could not be parsed.
Note
For an input with n bytes, 1 is the index of the first character and n+1 is the index of the terminating null byte or the end of file. This also holds true when reading a byte vector (CBOR or MessagePack).
@liveexample{The following code shows how a parse_error exception can be caught.,parse_error}
See also
- exception for the base class of the library exceptions
- invalid_iterator for exceptions indicating errors with iterators
- type_error for exceptions indicating executing a member function with a wrong type
- out_of_range for exceptions indicating access out of the defined range
- other_error for exceptions indicating other library errors
Since
version 3.0.0
Constructor & Destructor Documentation
parse_error()
nlohmann::detail::parse_error::parse_error (int id_, std::size_t byte_, const char * what_arg) inline private
        : exception(id_, what_arg), byte(byte_) {}
Member Function Documentation
create() [1/2]
template<typename BasicJsonType > static parse_error nlohmann::detail::parse_error::create (int id_, const position_t & pos, const std::string & what_arg, const BasicJsonType & context) inline static
create a parse error exception
Parameters
[in] id_ the id of the exception
[in] pos the position where the error occurred (or with chars_read_total=0 if the position cannot be determined)
[in] what_arg the explanatory string
Returns
parse_error object
    {
        std::string w = exception::name("parse_error", id_) + "parse error" +
                        position_string(pos) + ": " + exception::diagnostics(context) + what_arg;
        return parse_error(id_, pos.chars_read_total, w.c_str());
    }
References nlohmann::detail::exception::diagnostics(), nlohmann::detail::exception::name(), and position_string().
Referenced by nlohmann::json_pointer< BasicJsonType >::array_index(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_bson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_binary(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_cbor_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_msgpack_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_high_precision_number(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_type(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_size_value(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_string(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::get_ubjson_value(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::parse(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_bson_element_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_cbor_internal(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::parse_msgpack_internal(), nlohmann::basic_json< ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType >::patch(), nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::sax_parse(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse(), nlohmann::detail::parser< BasicJsonType, InputAdapterType >::sax_parse_internal(), nlohmann::json_pointer< BasicJsonType >::split(), and nlohmann::detail::binary_reader< BasicJsonType, InputAdapterType, SAX >::unexpect_eof().
create() [2/2]
template<typename BasicJsonType > static parse_error nlohmann::detail::parse_error::create (int id_, std::size_t byte_, const std::string & what_arg, const BasicJsonType & context) inline static
    {
        std::string w = exception::name("parse_error", id_) + "parse error" +
                        (byte_ != 0 ? (" at byte " + std::to_string(byte_)) : "") +
                        ": " + exception::diagnostics(context) + what_arg;
        return parse_error(id_, byte_, w.c_str());
    }
References nlohmann::detail::exception::diagnostics(), and nlohmann::detail::exception::name().
diagnostics()
template<typename BasicJsonType > static std::string nlohmann::detail::exception::diagnostics (const BasicJsonType & leaf_element) inline static protected inherited
    {
#if JSON_DIAGNOSTICS
        std::vector<std::string> tokens;
        for (const auto* current = &leaf_element; current->m_parent != nullptr; current = current->m_parent)
        {
            switch (current->m_parent->type())
            {
                case value_t::array:
                {
                    for (std::size_t i = 0; i < current->m_parent->m_value.array->size(); ++i)
                    {
                        if (&current->m_parent->m_value.array->operator[](i) == current)
{
                            tokens.emplace_back(std::to_string(i));
                            break;
                        }
                    }
                    break;
                }
                case value_t::object:
                {
                    for (const auto& element : *current->m_parent->m_value.object)
                    {
                        if (&element.second == current)
{
                            tokens.emplace_back(element.first.c_str());
                            break;
                        }
                    }
                    break;
                }
                case value_t::null: // LCOV_EXCL_LINE
                case value_t::string: // LCOV_EXCL_LINE
                case value_t::boolean: // LCOV_EXCL_LINE
                case value_t::number_integer: // LCOV_EXCL_LINE
                case value_t::number_unsigned: // LCOV_EXCL_LINE
                case value_t::number_float: // LCOV_EXCL_LINE
                case value_t::binary: // LCOV_EXCL_LINE
                case value_t::discarded: // LCOV_EXCL_LINE
                default:   // LCOV_EXCL_LINE
                    break; // LCOV_EXCL_LINE
            }
        }
        if (tokens.empty())
        {
            return "";
        }
        return "(" + std::accumulate(tokens.rbegin(), tokens.rend(), std::string{},
                                     [](const std::string & a, const std::string & b)
        {
            return a + "/" + detail::escape(b);
        }) + ") ";
#else
        static_cast<void>(leaf_element);
        return "";
#endif
    }
References nlohmann::detail::array, nlohmann::detail::binary, nlohmann::detail::boolean, nlohmann::detail::discarded, nlohmann::detail::null, nlohmann::detail::number_float, nlohmann::detail::number_integer, nlohmann::detail::number_unsigned, nlohmann::detail::object, and nlohmann::detail::string.
Referenced by create(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::type_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::other_error::create(), and create().
name()
static std::string nlohmann::detail::exception::name (const std::string & ename, int id_) inline static protected inherited
    {
        return "[json.exception." + ename + "." + std::to_string(id_) + "] ";
    }
Referenced by create(), nlohmann::detail::invalid_iterator::create(), nlohmann::detail::type_error::create(), nlohmann::detail::out_of_range::create(), nlohmann::detail::other_error::create(), and create().
position_string()
static std::string nlohmann::detail::parse_error::position_string (const position_t & pos) inline static private
    {
        return " at line " + std::to_string(pos.lines_read + 1) +
               ", column " + std::to_string(pos.chars_read_current_line);
    }
Referenced by create().
what()
const char * nlohmann::detail::exception::what () const inline override noexcept inherited
returns the explanatory string
    {
        return m.what();
    }
References nlohmann::detail::exception::m.
Referenced by Slic3r::PresetUpdater::priv::get_cached_plugins_version(), Slic3r::get_values_from_json(), Slic3r::get_version_from_json(), Slic3r::GUI::GuideFrame::GetFilamentInfo(), Slic3r::AppConfig::load(), Slic3r::PresetBundle::load_vendor_configs_from_json(), Slic3r::GUI::GuideFrame::LoadProfileFamily(), and Slic3r::GUI::UpdatePluginDialog::update_info().
Member Data Documentation
byte
const std::size_t nlohmann::detail::parse_error::byte
byte index of the parse error
The byte index of the last read character in the input file.
Note
For an input with n bytes, 1 is the index of the first character and n+1 is the index of the terminating null byte or the end of file. This also holds true when reading a byte vector (CBOR or MessagePack).
id
const int nlohmann::detail::exception::id inherited
the id of the exception
m
std::runtime_error nlohmann::detail::exception::m private inherited
an exception object as storage for error messages
Referenced by nlohmann::detail::exception::what().
The documentation for this class was generated from the following file:
src/nlohmann/detail/exceptions.hpp