OrcaSlicer: Slic3r::GUI::AMSControl Class Reference
Slic3r::GUI::AMSControl Class Reference
#include <src/slic3r/GUI/Widgets/AMSControl.hpp>
Public Member Functions
AMSControl (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
void init_scaled_buttons ()
std::string GetCurentAms ()
std::string GetCurentShowAms ()
std::string GetCurrentCan (std::string amsid)
wxColour GetCanColour (std::string amsid, std::string canid)
void SetActionState (bool button_status[])
void EnterNoneAMSMode (bool support_vt_load=false)
void ExitNoneAMSMode ()
void EnterCalibrationMode (bool read_to_calibration)
void ExitcClibrationMode ()
void SetClibrationpercent (int percent)
void SetClibrationLink (wxString link)
void PlayRridLoading (wxString amsid, wxString canid)
void StopRridLoading (wxString amsid, wxString canid)
void SetFilamentStep (int item_idx, FilamentStepType f_type, bool is_extrusion_exist=false)
void ShowFilamentTip (bool hasams=true)
void SetHumidity (std::string amsid, int humidity)
void UpdateStepCtrl (bool is_extrusion_exist)
void CreateAms ()
void UpdateAms (std::vector< AMSinfo > info, bool keep_selection=true, bool has_extrusion_cali=true, bool is_reset=false)
void AddAms (AMSinfo info, bool refresh=true)
void SetExtruder (bool on_off, bool is_vams, wxColour col)
void SetAmsStep (std::string ams_id, std::string canid, AMSPassRoadType type, AMSPassRoadSTEP step)
void SwitchAms (std::string ams_id)
void msw_rescale ()
void on_filament_load (wxCommandEvent &event)
void on_filament_unload (wxCommandEvent &event)
void on_ams_setting_click (wxMouseEvent &event)
void on_extrusion_cali (wxCommandEvent &event)
void on_ams_setting_click (wxCommandEvent &event)
void on_clibration_again_click (wxMouseEvent &event)
void on_clibration_cancel_click (wxMouseEvent &event)
void Reset ()
void show_noams_mode (bool show, bool support_virtual_tray, bool support_extrustion_cali, bool support_vt_load=false)
void show_vams (bool show)
void show_vams_kn_value (bool show)
void update_vams_kn_value (AmsTray tray, MachineObject *obj)
void show_filament_backup (bool show)
void reset_vams ()
void post_event (wxEvent &&event)
virtual bool Enable (bool enable=true)
Public Attributes
bool m_is_none_ams_mode {false}
std::string m_current_senect
Protected Attributes
int m_ams_count = {0}
std::map< std::string, int > m_ams_selection
std::vector< AMSinfo > m_ams_info
std::string m_current_ams
std::string m_current_show_ams
AmsItemsHash m_ams_item_list
AmsCansHash m_ams_cans_list
AMSextruder * m_extruder = {nullptr}
AmsIntroducePopup m_ams_introduce_popup
wxSimplebook * m_simplebook_right = {nullptr}
wxSimplebook * m_simplebook_calibration = {nullptr}
wxSimplebook * m_simplebook_amsitems = {nullptr}
wxSimplebook * m_simplebook_ams = {nullptr}
wxSimplebook * m_simplebook_cans = {nullptr}
wxSimplebook * m_simplebook_bottom = {nullptr}
wxStaticText * m_tip_right_top = {nullptr}
wxStaticText * m_tip_load_info = {nullptr}
wxStaticText * m_text_calibration_percent = {nullptr}
wxWindow * m_none_ams_panel = {nullptr}
wxWindow * m_panel_top = {nullptr}
wxWindow * m_amswin = {nullptr}
wxBoxSizer * m_vams_sizer = {nullptr}
wxBoxSizer * m_sizer_vams_tips = {nullptr}
Caninfo m_vams_info
StaticBox * m_panel_virtual = {nullptr}
AMSLib * m_vams_lib = {nullptr}
AMSRoad * m_vams_road = {nullptr}
AMSVirtualRoad * m_vams_extra_road = {nullptr}
StaticBox * m_panel_can = {nullptr}
wxBoxSizer * m_sizer_top = {nullptr}
wxBoxSizer * m_sizer_cans = {nullptr}
wxBoxSizer * m_sizer_right_tip = {nullptr}
wxBoxSizer * m_sizer_ams_tips = {nullptr}
::StepIndicator * m_filament_load_step = {nullptr}
::StepIndicator * m_filament_unload_step = {nullptr}
::StepIndicator * m_filament_vt_load_step = {nullptr}
Button * m_button_extruder_feed = {nullptr}
Button * m_button_extruder_back = {nullptr}
wxStaticBitmap * m_button_ams_setting = {nullptr}
ScalableBitmap m_button_ams_setting_normal
ScalableBitmap m_button_ams_setting_hover
ScalableBitmap m_button_ams_setting_press
Button * m_button_extrusion_cali = {nullptr}
Button * m_button_guide = {nullptr}
Button * m_button_retry = {nullptr}
wxWindow * m_button_area = {nullptr}
wxHyperlinkCtrl * m_hyperlink = {nullptr}
AmsHumidityTipPopup m_Humidity_tip_popup
std::string m_last_ams_id
std::string m_last_tray_id
Detailed Description
Constructor & Destructor Documentation
AMSControl()
Slic3r::GUI::AMSControl::AMSControl (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
    : wxSimplebook(parent, wxID_ANY, pos, size)
    , m_Humidity_tip_popup(AmsHumidityTipPopup(this))
    , m_ams_introduce_popup(AmsIntroducePopup(this))
{
    SetBackgroundColour(*wxWHITE);
    // normal mode
    //Freeze();
    wxBoxSizer *m_sizer_body = new wxBoxSizer(wxVERTICAL);
    m_amswin                 = new wxWindow(this, wxID_ANY, wxDefaultPosition, wxSize(-1, AMS_CAN_ITEM_HEIGHT_SIZE));
    m_amswin->SetBackgroundColour(*wxWHITE);
    // top - ams tag
    m_simplebook_amsitems = new wxSimplebook(m_amswin, wxID_ANY);
    m_simplebook_amsitems->SetSize(wxSize(-1, AMS_CAN_ITEM_HEIGHT_SIZE));
    m_simplebook_amsitems->SetMinSize(wxSize(-1, AMS_CAN_ITEM_HEIGHT_SIZE));
    auto m_sizer_amsitems = new wxBoxSizer(wxHORIZONTAL);
    m_simplebook_amsitems->SetSizer(m_sizer_amsitems);
    m_simplebook_amsitems->Layout();
    m_sizer_amsitems->Fit(m_simplebook_amsitems);
    m_panel_top = new wxPanel(m_simplebook_amsitems, wxID_ANY, wxDefaultPosition, wxSize(-1, AMS_CAN_ITEM_HEIGHT_SIZE));
    m_sizer_top = new wxBoxSizer(wxHORIZONTAL);
    m_panel_top->SetSizer(m_sizer_top);
    m_panel_top->Layout();
    m_sizer_top->Fit(m_panel_top);
    auto m_panel_top_empty = new wxPanel(m_simplebook_amsitems, wxID_ANY, wxDefaultPosition, wxSize(-1, AMS_CAN_ITEM_HEIGHT_SIZE));
    auto m_sizer_top_empty = new wxBoxSizer(wxHORIZONTAL);
    m_panel_top_empty->SetSizer(m_sizer_top_empty);
    m_panel_top_empty->Layout();
    m_sizer_top_empty->Fit(m_panel_top_empty);
    m_simplebook_amsitems->AddPage(m_panel_top, wxEmptyString, false);
    m_simplebook_amsitems->AddPage(m_panel_top_empty, wxEmptyString, false);
    wxBoxSizer *m_sizer_bottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *m_sizer_left   = new wxBoxSizer(wxVERTICAL);
    //ams tip
    m_sizer_ams_tips = new wxBoxSizer(wxHORIZONTAL);
    auto m_ams_tip = new Label(m_amswin, _L("AMS"));
    m_ams_tip->SetFont(::Label::Body_12);
    m_ams_tip->SetBackgroundColour(*wxWHITE);
    auto img_amsmapping_tip = new wxStaticBitmap(m_amswin, wxID_ANY, create_scaled_bitmap("enable_ams", this, 16), wxDefaultPosition, wxSize(FromDIP(16), FromDIP(16)), 0);
    img_amsmapping_tip->SetBackgroundColour(*wxWHITE);
    m_sizer_ams_tips->Add(m_ams_tip, 0, wxTOP, FromDIP(5));
    m_sizer_ams_tips->Add(img_amsmapping_tip, 0, wxALL, FromDIP(3));
    img_amsmapping_tip->Bind(wxEVT_ENTER_WINDOW, [this, img_amsmapping_tip](auto& e) {
         wxPoint img_pos = img_amsmapping_tip->ClientToScreen(wxPoint(0, 0));
         wxPoint popup_pos(img_pos.x, img_pos.y + img_amsmapping_tip->GetRect().height);
         m_ams_introduce_popup.set_mode(true);
         m_ams_introduce_popup.Position(popup_pos, wxSize(0, 0));
         m_ams_introduce_popup.Popup();
#ifdef __WXMSW__
         wxCommandEvent close_event(EVT_CLEAR_SPEED_CONTROL);
         wxPostEvent(this, close_event);
#endif // __WXMSW__
    });
    img_amsmapping_tip->Bind(wxEVT_LEAVE_WINDOW, [this](auto& e) {
         m_ams_introduce_popup.Dismiss();
    });
    //backup tips
#ifdef FILAMENT_BACKUP
    auto m_ams_backup_tip = new Label(m_amswin, _L("Ams filament backup"));
    m_ams_backup_tip->SetFont(::Label::Head_12);
    m_ams_backup_tip->SetForegroundColour(wxColour(0x00AE42));
    m_ams_backup_tip->SetBackgroundColour(*wxWHITE);
    auto m_img_ams_backup = new wxStaticBitmap(m_amswin, wxID_ANY, create_scaled_bitmap("automatic_material_renewal", this, 16), wxDefaultPosition, wxSize(FromDIP(16), FromDIP(16)), 0);
    m_img_ams_backup->SetBackgroundColour(*wxWHITE);
    m_sizer_ams_tips->Add(0, 0, 1, wxEXPAND, 0);
    m_sizer_ams_tips->Add(m_img_ams_backup, 0, wxALL, FromDIP(3));
    m_sizer_ams_tips->Add(m_ams_backup_tip, 0, wxTOP, FromDIP(5));
    m_ams_backup_tip->Bind(wxEVT_ENTER_WINDOW, [this, img_amsmapping_tip](auto& e) {SetCursor(wxCURSOR_HAND); });
    m_img_ams_backup->Bind(wxEVT_ENTER_WINDOW, [this, img_amsmapping_tip](auto& e) {SetCursor(wxCURSOR_HAND); });
    m_ams_backup_tip->Bind(wxEVT_LEAVE_WINDOW, [this](auto& e) {SetCursor(wxCURSOR_ARROW); });
    m_img_ams_backup->Bind(wxEVT_LEAVE_WINDOW, [this](auto& e) {SetCursor(wxCURSOR_ARROW); });
    m_ams_backup_tip->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {post_event(SimpleEvent(EVT_AMS_FILAMENT_BACKUP)); });
    m_img_ams_backup->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {post_event(SimpleEvent(EVT_AMS_FILAMENT_BACKUP)); });
#endif // FILAMENT_BACKUP
    //ams cans
    m_panel_can = new StaticBox(m_amswin, wxID_ANY, wxDefaultPosition, AMS_CANS_SIZE, wxBORDER_NONE);
    m_panel_can->SetMinSize(AMS_CANS_SIZE);
    m_panel_can->SetCornerRadius(FromDIP(10));
    m_panel_can->SetBackgroundColor(StateColor(std::pair<wxColour, int>(AMS_CONTROL_DEF_BLOCK_BK_COLOUR, StateColor::Normal)));
    m_sizer_cans = new wxBoxSizer(wxHORIZONTAL);
    m_simplebook_ams = new wxSimplebook(m_panel_can, wxID_ANY, wxDefaultPosition, AMS_CANS_WINDOW_SIZE, 0);
    m_simplebook_ams->SetBackgroundColour(AMS_CONTROL_DEF_BLOCK_BK_COLOUR);
    m_sizer_cans->Add(m_simplebook_ams, 0, wxLEFT | wxLEFT, FromDIP(10));
    // ams mode
    m_simplebook_cans = new wxSimplebook(m_simplebook_ams, wxID_ANY, wxDefaultPosition, AMS_CANS_WINDOW_SIZE, 0);
    m_simplebook_cans->SetBackgroundColour(AMS_CONTROL_DEF_BLOCK_BK_COLOUR);
    // none ams mode
    m_none_ams_panel = new wxPanel(m_simplebook_ams, wxID_ANY, wxDefaultPosition, AMS_CANS_WINDOW_SIZE, 0);
    m_none_ams_panel->SetBackgroundColour(AMS_CONTROL_DEF_BLOCK_BK_COLOUR);
    //m_none_ams_panel->SetDoubleBuffered(true);
    auto m_tip_none_ams = new wxStaticText(m_none_ams_panel, wxID_ANY, _L("AMS not connected"), wxDefaultPosition, wxDefaultSize, wxALIGN_CENTER_HORIZONTAL);
    m_tip_none_ams->SetMinSize(wxSize(AMS_CANS_SIZE.x - FromDIP(20), -1));
    m_tip_none_ams->SetFont(::Label::Head_16);
    m_tip_none_ams->SetForegroundColour(AMS_CONTROL_DISABLE_COLOUR);
    wxBoxSizer *sizer_ams_panel_v = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *sizer_ams_panel_h = new wxBoxSizer(wxHORIZONTAL);
    sizer_ams_panel_v->Add(m_tip_none_ams, 0, wxALIGN_CENTER, 0);
    sizer_ams_panel_h->Add(sizer_ams_panel_v, 0, wxALIGN_CENTER, 0);
    m_none_ams_panel->SetSizer(sizer_ams_panel_h);
    m_none_ams_panel->Layout();
    m_simplebook_ams->AddPage(m_simplebook_cans, wxEmptyString, true);
    m_simplebook_ams->AddPage(m_none_ams_panel, wxEmptyString, false);
    m_panel_can->SetSizer(m_sizer_cans);
    m_panel_can->Layout();
    m_sizer_cans->Fit(m_panel_can);
    m_sizer_left->Add(m_sizer_ams_tips, 0, wxEXPAND, 0);
    m_sizer_left->Add(m_panel_can, 1, wxEXPAND, 0);
    wxBoxSizer *m_sizer_left_bottom = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *sizer_sextruder     = new wxBoxSizer(wxVERTICAL);
    auto extruder_pane = new wxPanel(m_amswin, wxID_ANY, wxDefaultPosition, AMS_EXTRUDER_SIZE);
    extruder_pane->SetSizer(sizer_sextruder);
    extruder_pane->Layout();
    m_extruder = new AMSextruder(extruder_pane, wxID_ANY, wxDefaultPosition, AMS_EXTRUDER_SIZE);
    sizer_sextruder->Add(m_extruder, 0, wxALIGN_CENTER, 0);
    m_sizer_left_bottom->Add(extruder_pane, 0, wxALL,0);
    //m_sizer_left_bottom->Add(0, 0, 0, wxEXPAND, 0);
    StateColor btn_bg_green(std::pair<wxColour, int>(AMS_CONTROL_DISABLE_COLOUR, StateColor::Disabled),
                            std::pair<wxColour, int>(wxColour(0, 137, 123), StateColor::Pressed),
                            std::pair<wxColour, int>(wxColour(38, 166, 154), StateColor::Hovered),
                            std::pair<wxColour, int>(AMS_CONTROL_BRAND_COLOUR, StateColor::Normal));
    StateColor btn_bg_white(std::pair<wxColour, int>(AMS_CONTROL_DISABLE_COLOUR, StateColor::Disabled),
                            std::pair<wxColour, int>(AMS_CONTROL_DISABLE_COLOUR, StateColor::Pressed),
                            std::pair<wxColour, int>(AMS_CONTROL_DEF_BLOCK_BK_COLOUR, StateColor::Hovered),
                            std::pair<wxColour, int>(AMS_CONTROL_WHITE_COLOUR, StateColor::Normal));
    StateColor btn_bd_green(std::pair<wxColour, int>(wxColour(255,255,254), StateColor::Disabled),
                            std::pair<wxColour, int>(AMS_CONTROL_BRAND_COLOUR, StateColor::Enabled));
    StateColor btn_bd_white(std::pair<wxColour, int>(wxColour(255,255,254), StateColor::Disabled),
                            std::pair<wxColour, int>(wxColour(38, 46, 48), StateColor::Enabled));
    StateColor btn_text_green(std::pair<wxColour, int>(wxColour(255,255,254), StateColor::Disabled),
                              std::pair<wxColour, int>(wxColour(255,255,254), StateColor::Enabled));
    StateColor btn_text_white(std::pair<wxColour, int>(wxColour(255, 255, 254), StateColor::Disabled),
                              std::pair<wxColour, int>(wxColour(38, 46, 48), StateColor::Enabled));
    m_button_area = new wxWindow(m_amswin, wxID_ANY);
    m_button_area->SetBackgroundColour(m_amswin->GetBackgroundColour());
    wxBoxSizer *m_sizer_button = new wxBoxSizer(wxVERTICAL);
    wxBoxSizer *m_sizer_button_area = new wxBoxSizer(wxHORIZONTAL);
    m_button_extrusion_cali = new Button(m_button_area, _L("Cali"));
    m_button_extrusion_cali->SetToolTip(_L("Calibration of extrusion"));
    m_button_extrusion_cali->SetBackgroundColor(btn_bg_green);
    m_button_extrusion_cali->SetBorderColor(btn_bd_green);
    m_button_extrusion_cali->SetTextColor(btn_text_green);
    m_button_extrusion_cali->SetFont(Label::Body_13);
    m_button_extruder_feed = new Button(m_button_area, _L("Load Filament"));
    m_button_extruder_feed->SetBackgroundColor(btn_bg_green);
    m_button_extruder_feed->SetBorderColor(btn_bd_green);
    m_button_extruder_feed->SetTextColor(btn_text_green);
    m_button_extruder_feed->SetFont(Label::Body_13);
    m_button_extruder_back = new Button(m_button_area, _L("Unload Filament"));
    m_button_extruder_back->SetBackgroundColor(btn_bg_white);
    m_button_extruder_back->SetBorderColor(btn_bd_white);
    m_button_extruder_back->SetTextColor(btn_text_white);
    m_button_extruder_back->SetFont(Label::Body_13);
    m_sizer_button_area->Add(0, 0, 1, wxEXPAND, 0);
    m_sizer_button_area->Add(m_button_extrusion_cali, 0, wxLEFT, FromDIP(5));
    m_sizer_button_area->Add(m_button_extruder_back, 0, wxLEFT, FromDIP(6));
    m_sizer_button_area->Add(m_button_extruder_feed, 0, wxLEFT, FromDIP(6));
    m_sizer_button->Add(m_sizer_button_area, 0, 1, wxEXPAND, 0);
    m_button_area->SetSizer(m_sizer_button);
    m_button_area->Layout();
    m_button_area->Fit();
    m_sizer_left_bottom->Add(0, 0, 1, wxEXPAND, 0);
    m_sizer_left_bottom->Add(m_button_area, 0, wxEXPAND | wxTOP, FromDIP(18));
    m_sizer_left->Add(m_sizer_left_bottom, 0, wxEXPAND, 0);
    //virtual ams
    m_panel_virtual = new StaticBox(m_amswin, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxBORDER_NONE);
    m_panel_virtual->SetBackgroundColor(StateColor(std::pair<wxColour, int>(AMS_CONTROL_DEF_BLOCK_BK_COLOUR, StateColor::Normal)));
    m_panel_virtual->SetMinSize(wxSize(AMS_CAN_LIB_SIZE.x + FromDIP(16), AMS_CANS_SIZE.y));
    m_panel_virtual->SetMaxSize(wxSize(AMS_CAN_LIB_SIZE.x + FromDIP(16), AMS_CANS_SIZE.y));
    m_vams_info.material_state = AMSCanType::AMS_CAN_TYPE_VIRTUAL;
    m_vams_info.can_id = wxString::Format("%d", VIRTUAL_TRAY_ID).ToStdString();
    auto vams_panel = new wxWindow(m_panel_virtual, wxID_ANY);
    vams_panel->SetBackgroundColour(AMS_CONTROL_DEF_BLOCK_BK_COLOUR);
    m_vams_lib = new AMSLib(vams_panel, wxID_ANY, m_vams_info);
    m_vams_road = new AMSRoad(vams_panel, wxID_ANY, m_vams_info, -1, -1, wxDefaultPosition, AMS_CAN_ROAD_SIZE);
    m_vams_lib->Bind(wxEVT_LEFT_DOWN, [this](auto& e) {
        //clear all selected
        m_current_ams = m_vams_info.can_id;
        m_vams_lib->OnSelected();
        SwitchAms(m_current_ams);
        for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
            AmsCansWindow* cans = m_ams_cans_list[i];
            cans->amsCans->SelectCan(m_current_ams);
        }
        e.Skip();
        });
    Bind(EVT_AMS_UNSELETED_VAMS, [this](wxCommandEvent& e) {
        if (m_current_ams == e.GetString().ToStdString()) {
            return;
        }
        m_current_ams = e.GetString().ToStdString();
        SwitchAms(m_current_ams);
        m_vams_lib->UnSelected();
        e.Skip();
    });
    wxBoxSizer* m_vams_top_sizer = new wxBoxSizer(wxVERTICAL);
    m_vams_top_sizer->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(14));
    m_vams_top_sizer->Add(0, 0, 0, wxEXPAND | wxTOP, FromDIP(2) + AMS_REFRESH_SIZE.y);
    m_vams_top_sizer->Add(m_vams_lib, 1, wxEXPAND | wxTOP | wxLEFT | wxRIGHT, FromDIP(4));
    m_vams_top_sizer->Add(m_vams_road, 0, wxALL, 0);
    //extra road
    vams_panel->SetSizer(m_vams_top_sizer);
    vams_panel->Layout();
    vams_panel->Fit();
    wxBoxSizer* m_sizer_vams_panel = new wxBoxSizer(wxVERTICAL);
    m_sizer_vams_panel->Add(vams_panel, 0, wxALIGN_CENTER_HORIZONTAL, 0);
    m_panel_virtual->SetSizer(m_sizer_vams_panel);
    m_panel_virtual->Layout();
    m_panel_virtual->Fit();
    m_vams_sizer =  new wxBoxSizer(wxVERTICAL);
    m_sizer_vams_tips = new wxBoxSizer(wxHORIZONTAL);
    auto m_vams_tip = new wxStaticText(m_amswin, wxID_ANY, _L("Ext Spool"));
    m_vams_tip->SetFont(::Label::Body_12);
    m_vams_tip->SetBackgroundColour(*wxWHITE);
    auto img_vams_tip = new wxStaticBitmap(m_amswin, wxID_ANY, create_scaled_bitmap("enable_ams", this, 16), wxDefaultPosition, wxSize(FromDIP(16), FromDIP(16)), 0);
    img_vams_tip->SetBackgroundColour(*wxWHITE);
    img_vams_tip->Bind(wxEVT_ENTER_WINDOW, [this, img_vams_tip](auto& e) {
        wxPoint img_pos = img_vams_tip->ClientToScreen(wxPoint(0, 0));
        wxPoint popup_pos(img_pos.x, img_pos.y + img_vams_tip->GetRect().height);
        m_ams_introduce_popup.set_mode(false);
        m_ams_introduce_popup.Position(popup_pos, wxSize(0, 0));
        m_ams_introduce_popup.Popup();
#ifdef __WXMSW__
        wxCommandEvent close_event(EVT_CLEAR_SPEED_CONTROL);
        wxPostEvent(this, close_event);
#endif // __WXMSW__
    });
    img_vams_tip->Bind(wxEVT_LEAVE_WINDOW, [this](wxMouseEvent& e) {
        m_ams_introduce_popup.Dismiss();
    });
    m_sizer_vams_tips->Add(m_vams_tip, 0, wxTOP, FromDIP(5));
    m_sizer_vams_tips->Add(img_vams_tip, 0, wxALL, FromDIP(3));
    m_vams_extra_road = new AMSVirtualRoad(m_amswin, wxID_ANY);
    m_vams_extra_road->SetMinSize(wxSize(m_panel_virtual->GetSize().x + FromDIP(16), -1));
    m_vams_sizer->Add(m_sizer_vams_tips, 0, wxALIGN_CENTER, 0);
    m_vams_sizer->Add(m_panel_virtual, 0, wxALIGN_CENTER, 0);
    m_vams_sizer->Add(m_vams_extra_road, 1, wxEXPAND, 0);
    //Right
    wxBoxSizer *m_sizer_right = new wxBoxSizer(wxVERTICAL);
    m_simplebook_right        = new wxSimplebook(m_amswin, wxID_ANY);
    m_simplebook_right->SetMinSize(wxSize(AMS_STEP_SIZE.x, AMS_STEP_SIZE.y + FromDIP(19)));
    m_simplebook_right->SetMaxSize(wxSize(AMS_STEP_SIZE.x, AMS_STEP_SIZE.y + FromDIP(19)));
    m_simplebook_right->SetBackgroundColour(*wxWHITE);
    m_sizer_right->Add(m_simplebook_right, 0, wxALL, 0);
    auto tip_right    = new wxPanel(m_simplebook_right, wxID_ANY, wxDefaultPosition, AMS_STEP_SIZE, wxTAB_TRAVERSAL);
    m_sizer_right_tip = new wxBoxSizer(wxVERTICAL);
    m_tip_right_top   = new wxStaticText(tip_right, wxID_ANY, _L("Tips"), wxDefaultPosition, wxDefaultSize, 0);
    m_tip_right_top->SetFont(::Label::Head_13);
    m_tip_right_top->SetForegroundColour(AMS_CONTROL_BRAND_COLOUR);
    m_tip_right_top->Wrap(AMS_STEP_SIZE.x);
    m_tip_load_info = new wxStaticText(tip_right, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0);
    m_tip_load_info->SetFont(::Label::Body_13);
    m_tip_load_info->SetForegroundColour(AMS_CONTROL_GRAY700);
    m_sizer_right_tip->Add(m_tip_right_top, 0, 0, 0);
    m_sizer_right_tip->Add(0, 0, 0, wxEXPAND, FromDIP(10));
    m_sizer_right_tip->Add(m_tip_load_info, 0, 0, 0);
    tip_right->SetSizer(m_sizer_right_tip);
    tip_right->Layout();
    m_filament_load_step = new ::StepIndicator(m_simplebook_right, wxID_ANY);
    m_filament_load_step->SetMinSize(AMS_STEP_SIZE);
    m_filament_load_step->SetMaxSize(AMS_STEP_SIZE);
    m_filament_load_step->SetBackgroundColour(*wxWHITE);
    m_filament_unload_step = new ::StepIndicator(m_simplebook_right, wxID_ANY);
    m_filament_unload_step->SetMinSize(AMS_STEP_SIZE);
    m_filament_unload_step->SetMaxSize(AMS_STEP_SIZE);
    m_filament_unload_step->SetBackgroundColour(*wxWHITE);
    m_filament_vt_load_step = new ::StepIndicator(m_simplebook_right, wxID_ANY);
    m_filament_vt_load_step->SetMinSize(AMS_STEP_SIZE);
    m_filament_vt_load_step->SetMaxSize(AMS_STEP_SIZE);
    m_filament_vt_load_step->SetBackgroundColour(*wxWHITE);
    m_simplebook_right->AddPage(tip_right, wxEmptyString, false);
    m_simplebook_right->AddPage(m_filament_load_step, wxEmptyString, false);
    m_simplebook_right->AddPage(m_filament_unload_step, wxEmptyString, false);
    m_simplebook_right->AddPage(m_filament_vt_load_step, wxEmptyString, false);
    m_button_ams_setting_normal = ScalableBitmap(this, "ams_setting_normal", 24);
    m_button_ams_setting_hover = ScalableBitmap(this, "ams_setting_hover", 24);
    m_button_ams_setting_press = ScalableBitmap(this, "ams_setting_press", 24);
    wxBoxSizer *m_sizer_right_bottom = new wxBoxSizer(wxHORIZONTAL);
    m_button_ams_setting = new wxStaticBitmap(m_amswin, wxID_ANY, m_button_ams_setting_normal.bmp(), wxDefaultPosition, wxSize(FromDIP(24), FromDIP(24)));
    m_button_ams_setting->SetBackgroundColour(m_amswin->GetBackgroundColour());
    m_button_guide = new Button(m_amswin, _L("Guide"));
    m_button_guide->SetFont(Label::Body_13);
    m_button_guide->SetCornerRadius(FromDIP(12));
    m_button_guide->SetBorderColor(btn_bd_white);
    m_button_guide->SetTextColor(btn_text_white);
    m_button_guide->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_guide->SetBackgroundColor(btn_bg_white);
    m_button_retry = new Button(m_amswin, _L("Retry"));
    m_button_retry->SetFont(Label::Body_13);
    m_button_retry->SetCornerRadius(FromDIP(12));
    m_button_retry->SetBorderColor(btn_bd_white);
    m_button_retry->SetTextColor(btn_text_white);
    m_button_retry->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_retry->SetBackgroundColor(btn_bg_white);
    m_sizer_right_bottom->Add(m_button_ams_setting, 0);
    m_sizer_right_bottom->Add(m_button_guide, 0, wxLEFT, FromDIP(10));
    m_sizer_right_bottom->Add(m_button_retry, 0, wxLEFT, FromDIP(10));
    m_sizer_right->Add(m_sizer_right_bottom, 0, wxEXPAND | wxTOP, FromDIP(20));
    m_sizer_bottom->Add(m_vams_sizer, 0, wxEXPAND, 0);
    m_sizer_bottom->Add(m_sizer_left, 0, wxEXPAND, 0);
    m_sizer_bottom->Add(0, 0, 0, wxLEFT, FromDIP(15));
    m_sizer_bottom->Add(m_sizer_right, 0, wxEXPAND, FromDIP(0));
    m_sizer_body->Add(m_simplebook_amsitems, 0, wxEXPAND, 0);
    m_sizer_body->Add(0, 0, 1, wxEXPAND | wxTOP, FromDIP(18));
    m_sizer_body->Add(m_sizer_bottom, 0, wxEXPAND | wxLEFT, FromDIP(6));
    init_scaled_buttons();
    m_amswin->SetSizer(m_sizer_body);
    m_amswin->Layout();
    m_amswin->Fit();
    //Thaw();
    SetSize(m_amswin->GetSize());
    SetMinSize(m_amswin->GetSize());
    // calibration mode
    m_simplebook_calibration = new wxSimplebook(this, wxID_ANY, wxDefaultPosition, m_amswin->GetSize(), wxTAB_TRAVERSAL);
    auto m_in_calibration_panel = new wxWindow(m_simplebook_calibration, wxID_ANY, wxDefaultPosition, m_amswin->GetSize(), wxTAB_TRAVERSAL);
    m_in_calibration_panel->SetBackgroundColour(AMS_CONTROL_WHITE_COLOUR);
    wxBoxSizer *sizer_calibration_h = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *sizer_calibration_v = new wxBoxSizer(wxVERTICAL);
    auto        thumbnail           = new wxStaticBitmap(m_in_calibration_panel, wxID_ANY, create_scaled_bitmap("ams_icon", nullptr, 126), wxDefaultPosition, wxDefaultSize);
    m_text_calibration_percent      = new wxStaticText(m_in_calibration_panel, wxID_ANY, wxT("0%"), wxDefaultPosition, wxDefaultSize, 0);
    m_text_calibration_percent->SetFont(::Label::Head_16);
    m_text_calibration_percent->SetForegroundColour(AMS_CONTROL_BRAND_COLOUR);
    auto m_text_calibration_tip = new wxStaticText(m_in_calibration_panel, wxID_ANY, _L("Calibrating AMS..."), wxDefaultPosition, wxDefaultSize, 0);
    m_text_calibration_tip->SetFont(::Label::Body_14);
    m_text_calibration_tip->SetForegroundColour(AMS_CONTROL_GRAY700);
    sizer_calibration_v->Add(thumbnail, 0, wxALIGN_CENTER, 0);
    sizer_calibration_v->Add(0, 0, 0, wxTOP, FromDIP(16));
    sizer_calibration_v->Add(m_text_calibration_percent, 0, wxALIGN_CENTER, 0);
    sizer_calibration_v->Add(0, 0, 0, wxTOP, FromDIP(8));
    sizer_calibration_v->Add(m_text_calibration_tip, 0, wxALIGN_CENTER, 0);
    sizer_calibration_h->Add(sizer_calibration_v, 1, wxALIGN_CENTER, 0);
    m_in_calibration_panel->SetSizer(sizer_calibration_h);
    m_in_calibration_panel->Layout();
    auto m_calibration_err_panel = new wxWindow(m_simplebook_calibration, wxID_ANY, wxDefaultPosition, m_amswin->GetSize(), wxTAB_TRAVERSAL);
    m_calibration_err_panel->SetBackgroundColour(AMS_CONTROL_WHITE_COLOUR);
    wxBoxSizer *sizer_err_calibration_h = new wxBoxSizer(wxHORIZONTAL);
    wxBoxSizer *sizer_err_calibration_v = new wxBoxSizer(wxVERTICAL);
    m_hyperlink = new wxHyperlinkCtrl(m_calibration_err_panel, wxID_ANY, wxEmptyString, wxEmptyString, wxDefaultPosition, wxDefaultSize, wxHL_DEFAULT_STYLE);
    m_hyperlink->SetVisitedColour(wxColour(31, 142, 234));
    auto m_tip_calibration_err = new wxStaticText(m_calibration_err_panel, wxID_ANY, _L("A problem occured during calibration. Click to view the solution."), wxDefaultPosition,
                                                  wxDefaultSize, 0);
    m_tip_calibration_err->SetFont(::Label::Body_14);
    m_tip_calibration_err->SetForegroundColour(AMS_CONTROL_GRAY700);
    wxBoxSizer *sizer_button = new wxBoxSizer(wxHORIZONTAL);
    auto m_button_calibration_again = new Button(m_calibration_err_panel, _L("Calibrate again"));
    m_button_calibration_again->SetBackgroundColor(btn_bg_green);
    m_button_calibration_again->SetBorderColor(AMS_CONTROL_BRAND_COLOUR);
    m_button_calibration_again->SetTextColor(AMS_CONTROL_WHITE_COLOUR);
    m_button_calibration_again->SetMinSize(AMS_CONTRO_CALIBRATION_BUTTON_SIZE);
    m_button_calibration_again->SetCornerRadius(FromDIP(12));
    m_button_calibration_again->Bind(wxEVT_LEFT_DOWN, &AMSControl::on_clibration_again_click, this);
    sizer_button->Add(m_button_calibration_again, 0, wxALL, 5);
    auto       m_button_calibration_cancel = new Button(m_calibration_err_panel, _L("Cancel calibration"));
    m_button_calibration_cancel->SetBackgroundColor(btn_bg_white);
    m_button_calibration_cancel->SetBorderColor(AMS_CONTROL_GRAY700);
    m_button_calibration_cancel->SetTextColor(AMS_CONTROL_GRAY800);
    m_button_calibration_cancel->SetMinSize(AMS_CONTRO_CALIBRATION_BUTTON_SIZE);
    m_button_calibration_cancel->SetCornerRadius(FromDIP(12));
    m_button_calibration_cancel->Bind(wxEVT_LEFT_DOWN, &AMSControl::on_clibration_cancel_click, this);
    sizer_button->Add(m_button_calibration_cancel, 0, wxALL, 5);
    sizer_err_calibration_v->Add(m_hyperlink, 0, wxALIGN_CENTER, 0);
    sizer_err_calibration_v->Add(0, 0, 0, wxTOP, FromDIP(6));
    sizer_err_calibration_v->Add(m_tip_calibration_err, 0, wxALIGN_CENTER, 0);
    sizer_err_calibration_v->Add(0, 0, 0, wxTOP, FromDIP(8));
    sizer_err_calibration_v->Add(sizer_button, 0, wxALIGN_CENTER | wxTOP, FromDIP(18));
    sizer_err_calibration_h->Add(sizer_err_calibration_v, 1, wxALIGN_CENTER, 0);
    m_calibration_err_panel->SetSizer(sizer_err_calibration_h);
    m_calibration_err_panel->Layout();
    m_simplebook_calibration->AddPage(m_in_calibration_panel, wxEmptyString, false);
    m_simplebook_calibration->AddPage(m_calibration_err_panel, wxEmptyString, false);
    AddPage(m_amswin, wxEmptyString, false);
    AddPage(m_simplebook_calibration, wxEmptyString, false);
    UpdateStepCtrl(false);
    m_button_extrusion_cali->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AMSControl::on_extrusion_cali), NULL, this);
    m_button_extruder_feed->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AMSControl::on_filament_load), NULL, this);
    m_button_extruder_back->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AMSControl::on_filament_unload), NULL, this);
    m_button_ams_setting->Bind(wxEVT_ENTER_WINDOW, [this](wxMouseEvent& e) {
        m_button_ams_setting->SetBitmap(m_button_ams_setting_hover.bmp());
        e.Skip();
    });
    m_button_ams_setting->Bind(wxEVT_LEFT_DOWN, [this](wxMouseEvent& e) {
        m_button_ams_setting->SetBitmap(m_button_ams_setting_press.bmp());
        on_ams_setting_click(e);
        e.Skip();
    });
    m_button_ams_setting->Bind(wxEVT_LEAVE_WINDOW, [this](wxMouseEvent& e) {
        m_button_ams_setting->SetBitmap(m_button_ams_setting_normal.bmp());
        e.Skip();
    });
    Bind(EVT_AMS_SHOW_HUMIDITY_TIPS, [this](wxCommandEvent& evt) {
        wxPoint img_pos = ClientToScreen(wxPoint(0, 0));
        wxPoint popup_pos(img_pos.x - m_Humidity_tip_popup.GetSize().GetWidth() + FromDIP(150), img_pos.y);
        m_Humidity_tip_popup.Position(popup_pos, wxSize(0, 0));
        m_Humidity_tip_popup.Popup();
    });
    m_button_guide->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e) {
        post_event(wxCommandEvent(EVT_AMS_GUIDE_WIKI));
        });
    m_button_retry->Bind(wxEVT_BUTTON, [this](wxCommandEvent& e) {
        post_event(wxCommandEvent(EVT_AMS_RETRY));
        });
    CreateAms();
    SetSelection(0);
    EnterNoneAMSMode();
}
References _L, AMS_CAN_ITEM_HEIGHT_SIZE, AMS_CAN_LIB_SIZE, AMS_CAN_ROAD_SIZE, Slic3r::GUI::AMS_CAN_TYPE_VIRTUAL, AMS_CANS_SIZE, AMS_CANS_WINDOW_SIZE, AMS_CONTRO_CALIBRATION_BUTTON_SIZE, AMS_CONTROL_BRAND_COLOUR, AMS_CONTROL_DEF_BLOCK_BK_COLOUR, AMS_CONTROL_DISABLE_COLOUR, AMS_CONTROL_GRAY700, AMS_CONTROL_GRAY800, AMS_CONTROL_WHITE_COLOUR, AMS_EXTRUDER_SIZE, AMS_REFRESH_SIZE, AMS_STEP_SIZE, Slic3r::GUI::AmsCansWindow::amsCans, ScalableBitmap::bmp(), Label::Body_12, Label::Body_13, Label::Body_14, Slic3r::GUI::Caninfo::can_id, create_scaled_bitmap(), CreateAms(), StateColor::Disabled, StateColor::Enabled, EnterNoneAMSMode(), Label::Head_12, Label::Head_13, Label::Head_16, StateColor::Hovered, init_scaled_buttons(), m_ams_cans_list, m_ams_introduce_popup, m_amswin, m_button_ams_setting, m_button_ams_setting_hover, m_button_ams_setting_normal, m_button_ams_setting_press, m_button_area, m_button_extruder_back, m_button_extruder_feed, m_button_extrusion_cali, m_button_guide, m_button_retry, m_current_ams, m_extruder, m_filament_load_step, m_filament_unload_step, m_filament_vt_load_step, m_Humidity_tip_popup, m_hyperlink, m_none_ams_panel, m_panel_can, m_panel_top, m_panel_virtual, m_simplebook_ams, m_simplebook_amsitems, m_simplebook_calibration, m_simplebook_cans, m_simplebook_right, m_sizer_ams_tips, m_sizer_cans, m_sizer_right_tip, m_sizer_top, m_sizer_vams_tips, m_text_calibration_percent, m_tip_load_info, m_tip_right_top, m_vams_extra_road, m_vams_info, m_vams_lib, m_vams_road, m_vams_sizer, Slic3r::GUI::Caninfo::material_state, StateColor::Normal, NULL, on_ams_setting_click(), on_clibration_again_click(), on_clibration_cancel_click(), on_extrusion_cali(), on_filament_load(), on_filament_unload(), Slic3r::GUI::AMSLib::OnSelected(), post_event(), StateColor::Pressed, Slic3r::GUI::AmsCans::SelectCan(), Slic3r::GUI::AmsIntroducePopup::set_mode(), StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetFont(), Button::SetMinSize(), Button::SetTextColor(), SwitchAms(), Slic3r::GUI::AMSLib::UnSelected(), UpdateStepCtrl(), VIRTUAL_TRAY_ID, wxEVT_BUTTON, Slic3r::GUI::wxMouseEvent, and wxStaticText.
Member Function Documentation
AddAms()
void Slic3r::GUI::AMSControl::AddAms (AMSinfo info, bool refresh = true)
{
    if (m_ams_count >= AMS_CONTROL_MAX_COUNT) return;
    // item
    auto amsitem = new AMSItem(m_panel_top, wxID_ANY, info);
    amsitem->Bind(wxEVT_LEFT_DOWN, [this, amsitem](wxMouseEvent &e) {
        SwitchAms(amsitem->m_amsinfo.ams_id);
        e.Skip();
    });
    AmsItems *item = new AmsItems();
    item->amsIndex = info.ams_id;
    item->amsItem  = amsitem;
    m_ams_item_list.Add(item);
    m_sizer_top->Add(amsitem, 0, wxALIGN_CENTER|wxRIGHT, 6);
    AmsCansWindow *canswin = new AmsCansWindow();
    auto           amscans = new AmsCans(m_simplebook_cans, wxID_ANY, info);
    canswin->amsIndex = info.ams_id;
    canswin->amsCans  = amscans;
    m_ams_cans_list.Add(canswin);
    m_simplebook_cans->AddPage(amscans, wxEmptyString, false);
    amscans->m_selection = m_simplebook_cans->GetPageCount() - 1;
    if (refresh) { m_sizer_top->Layout(); }
    m_ams_count++;
    m_ams_info.push_back(info);
}
References AMS_CONTROL_MAX_COUNT, Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::AmsCansWindow::amsCans, Slic3r::GUI::AmsCansWindow::amsIndex, Slic3r::GUI::AmsItems::amsIndex, Slic3r::GUI::AmsItems::amsItem, m_ams_cans_list, m_ams_count, m_ams_info, m_ams_item_list, m_panel_top, m_simplebook_cans, m_sizer_top, SwitchAms(), and Slic3r::GUI::wxMouseEvent.
Referenced by CreateAms().
CreateAms()
void Slic3r::GUI::AMSControl::CreateAms ()
{
    auto caninfo0_0 = Caninfo{"def_can_0", (""), *wxWHITE, AMSCanType::AMS_CAN_TYPE_NONE};
    auto caninfo0_1 = Caninfo{"def_can_1", (""), *wxWHITE, AMSCanType::AMS_CAN_TYPE_NONE};
    auto caninfo0_2 = Caninfo{"def_can_2", (""), *wxWHITE, AMSCanType::AMS_CAN_TYPE_NONE};
    auto caninfo0_3 = Caninfo{"def_can_3", (""), *wxWHITE, AMSCanType::AMS_CAN_TYPE_NONE};
    AMSinfo                        ams1 = AMSinfo{"0", std::vector<Caninfo>{caninfo0_0, caninfo0_1, caninfo0_2, caninfo0_3}};
    AMSinfo                        ams2 = AMSinfo{"1", std::vector<Caninfo>{caninfo0_0, caninfo0_1, caninfo0_2, caninfo0_3}};
    AMSinfo                        ams3 = AMSinfo{"2", std::vector<Caninfo>{caninfo0_0, caninfo0_1, caninfo0_2, caninfo0_3}};
    AMSinfo                        ams4 = AMSinfo{"3", std::vector<Caninfo>{caninfo0_0, caninfo0_1, caninfo0_2, caninfo0_3}};
    std::vector<AMSinfo>           ams_info{ams1, ams2, ams3, ams4};
    std::vector<AMSinfo>::iterator it;
    Freeze();
    for (it = ams_info.begin(); it != ams_info.end(); it++) { AddAms(*it, true); }
    m_sizer_top->Layout();
    Thaw();
}
References AddAms(), Slic3r::GUI::AMS_CAN_TYPE_NONE, and m_sizer_top.
Referenced by AMSControl().
Enable()
bool Slic3r::GUI::AMSControl::Enable (bool enable = true) virtual
{
    for (auto i = 0; i < m_ams_item_list.GetCount(); i++) {
        AmsItems *item = m_ams_item_list[i];
        item->amsItem->Enable(enable);
    }
    for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
        AmsCansWindow *cans = m_ams_cans_list[i];
        cans->amsCans->Enable(enable);
    }
    m_button_extrusion_cali->Enable(enable);
    m_button_extruder_feed->Enable(enable);
    m_button_extruder_back->Enable(enable);
    m_button_ams_setting->Enable(enable);
    m_filament_load_step->Enable(enable);
    return wxWindow::Enable(enable);
}
References Slic3r::GUI::AmsCansWindow::amsCans, Slic3r::GUI::AmsItems::amsItem, Slic3r::GUI::AMSItem::Enable(), Button::Enable(), m_ams_cans_list, m_ams_item_list, m_button_ams_setting, m_button_extruder_back, m_button_extruder_feed, m_button_extrusion_cali, and m_filament_load_step.
EnterCalibrationMode()
void Slic3r::GUI::AMSControl::EnterCalibrationMode (bool read_to_calibration)
{
    SetSelection(1);
    if (read_to_calibration)
        m_simplebook_calibration->SetSelection(0);
    else
        m_simplebook_calibration->SetSelection(1);
}
References m_simplebook_calibration.
EnterNoneAMSMode()
void Slic3r::GUI::AMSControl::EnterNoneAMSMode (bool support_vt_load = false)
{
    m_simplebook_amsitems->Hide();
    m_panel_top->Hide();
    m_simplebook_amsitems->SetSelection(1);
    m_simplebook_ams->SetSelection(1);
    m_extruder->no_ams_mode(true);
    m_button_ams_setting->Hide();
    m_button_guide->Hide();
    m_button_retry->Hide();
    if (support_vt_load) {
        m_button_extruder_feed->Show();
        m_button_extruder_back->Show();
    } else {
        m_button_extruder_feed->Hide();
        m_button_extruder_back->Hide();
    }
    ShowFilamentTip(false);
    m_amswin->Layout();
    m_amswin->Fit();
    Layout();
    m_is_none_ams_mode = true;
}
References m_amswin, m_button_ams_setting, m_button_extruder_back, m_button_extruder_feed, m_button_guide, m_button_retry, m_extruder, m_is_none_ams_mode, m_panel_top, m_simplebook_ams, m_simplebook_amsitems, Slic3r::GUI::AMSextruder::no_ams_mode(), and ShowFilamentTip().
Referenced by AMSControl(), and show_noams_mode().
ExitcClibrationMode()
void Slic3r::GUI::AMSControl::ExitcClibrationMode ()
{ SetSelection(0); }
ExitNoneAMSMode()
void Slic3r::GUI::AMSControl::ExitNoneAMSMode ()
{
    m_simplebook_amsitems->Show();
    m_panel_top->Show();
    m_simplebook_ams->SetSelection(0);
    m_simplebook_amsitems->SetSelection(0);
    m_extruder->no_ams_mode(false);
    m_button_ams_setting->Show();
    m_button_guide->Show();
    m_button_retry->Show();
    m_button_extruder_feed->Show();
    m_button_extruder_back->Show();
    ShowFilamentTip(true);
    m_amswin->Layout();
    m_amswin->Fit();
    Layout();
    m_is_none_ams_mode = false;
}
References m_amswin, m_button_ams_setting, m_button_extruder_back, m_button_extruder_feed, m_button_guide, m_button_retry, m_extruder, m_is_none_ams_mode, m_panel_top, m_simplebook_ams, m_simplebook_amsitems, Slic3r::GUI::AMSextruder::no_ams_mode(), and ShowFilamentTip().
Referenced by show_noams_mode().
GetCanColour()
wxColour Slic3r::GUI::AMSControl::GetCanColour (std::string amsid, std::string canid)
{
    wxColour col = *wxWHITE;
    for (auto i = 0; i < m_ams_info.size(); i++) {
        if (m_ams_info[i].ams_id == amsid) {
            for (auto o = 0; o < m_ams_info[i].cans.size(); o++) {
                if (m_ams_info[i].cans[o].can_id == canid) {
                    col = m_ams_info[i].cans[o].material_colour;
                }
            }
        }
    }
    return col;
}
References col(), and m_ams_info.
Referenced by SwitchAms(), and Slic3r::GUI::StatusPanel::update_ams().
GetCurentAms()
std::string Slic3r::GUI::AMSControl::GetCurentAms ()
{ return m_current_ams; }
References m_current_ams.
Referenced by Slic3r::GUI::StatusPanel::on_ams_load_curr(), Slic3r::GUI::StatusPanel::on_ams_refresh_rfid(), Slic3r::GUI::StatusPanel::on_ams_selected(), Slic3r::GUI::StatusPanel::on_filament_edit(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::StatusPanel::update_ams(), and UpdateAms().
GetCurentShowAms()
std::string Slic3r::GUI::AMSControl::GetCurentShowAms ()
{ return m_current_show_ams; }
References m_current_show_ams.
Referenced by Slic3r::GUI::StatusPanel::on_ams_setting_click().
GetCurrentCan()
std::string Slic3r::GUI::AMSControl::GetCurrentCan (std::string amsid)
{
    std::string current_can;
    for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
        AmsCansWindow *ams = m_ams_cans_list[i];
        if (ams->amsCans->m_info.ams_id == amsid) {
            current_can = ams->amsCans->GetCurrentCan();
            return current_can;
        }
    }
    return current_can;
}
References Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::AmsCansWindow::amsCans, Slic3r::GUI::AmsCans::GetCurrentCan(), m_ams_cans_list, and Slic3r::GUI::AmsCans::m_info.
Referenced by Slic3r::GUI::StatusPanel::on_ams_load_curr(), Slic3r::GUI::StatusPanel::on_filament_extrusion_cali(), Slic3r::GUI::StatusPanel::update_ams(), and UpdateAms().
init_scaled_buttons()
void Slic3r::GUI::AMSControl::init_scaled_buttons ()
{
    m_button_extrusion_cali->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_extrusion_cali->SetCornerRadius(FromDIP(12));
    m_button_extruder_feed->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_extruder_feed->SetCornerRadius(FromDIP(12));
    m_button_extruder_back->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_extruder_back->SetCornerRadius(FromDIP(12));
}
References m_button_extruder_back, m_button_extruder_feed, m_button_extrusion_cali, StaticBox::SetCornerRadius(), and Button::SetMinSize().
Referenced by AMSControl().
msw_rescale()
void Slic3r::GUI::AMSControl::msw_rescale ()
{
    m_button_ams_setting_normal.msw_rescale();
    m_button_ams_setting_hover.msw_rescale();
    m_button_ams_setting_press.msw_rescale();
    m_button_ams_setting->SetBitmap(m_button_ams_setting_normal.bmp());
    m_extruder->msw_rescale();
    m_vams_extra_road->msw_rescale();
    m_button_extrusion_cali->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_extruder_feed->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_extruder_back->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_ams_setting->SetMinSize(wxSize(FromDIP(25), FromDIP(24)));
    m_button_guide->SetMinSize(wxSize(-1, FromDIP(24)));
    m_button_retry->SetMinSize(wxSize(-1, FromDIP(24)));
    for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
        AmsCansWindow *cans = m_ams_cans_list[i];
        cans->amsCans->msw_rescale();
    }
    Layout();
    Refresh();
}
References Slic3r::GUI::AmsCansWindow::amsCans, ScalableBitmap::bmp(), m_ams_cans_list, m_button_ams_setting, m_button_ams_setting_hover, m_button_ams_setting_normal, m_button_ams_setting_press, m_button_extruder_back, m_button_extruder_feed, m_button_extrusion_cali, m_button_guide, m_button_retry, m_extruder, m_vams_extra_road, Slic3r::GUI::AMSextruder::msw_rescale(), Slic3r::GUI::AMSVirtualRoad::msw_rescale(), Slic3r::GUI::AmsCans::msw_rescale(), ScalableBitmap::msw_rescale(), and Button::SetMinSize().
Referenced by Slic3r::GUI::StatusPanel::msw_rescale(), and Slic3r::GUI::StatusPanel::on_sys_color_changed().
on_ams_setting_click() [1/2]
void Slic3r::GUI::AMSControl::on_ams_setting_click (wxCommandEvent & event)
on_ams_setting_click() [2/2]
void Slic3r::GUI::AMSControl::on_ams_setting_click (wxMouseEvent & event)
{
    for (auto i = 0; i < m_ams_info.size(); i++) {
        if (m_ams_info[i].ams_id == m_current_ams) { m_ams_info[i].current_action = AMSAction::AMS_ACTION_CALI; }
    }
    post_event(SimpleEvent(EVT_AMS_SETTINGS));
}
References Slic3r::GUI::AMS_ACTION_CALI, m_ams_info, m_current_ams, and post_event().
Referenced by AMSControl().
on_clibration_again_click()
void Slic3r::GUI::AMSControl::on_clibration_again_click (wxMouseEvent & event)
{ post_event(SimpleEvent(EVT_AMS_CLIBRATION_AGAIN)); }
References post_event().
Referenced by AMSControl().
on_clibration_cancel_click()
void Slic3r::GUI::AMSControl::on_clibration_cancel_click (wxMouseEvent & event)
{ post_event(SimpleEvent(EVT_AMS_CLIBRATION_CANCEL)); }
References post_event().
Referenced by AMSControl().
on_extrusion_cali()
void Slic3r::GUI::AMSControl::on_extrusion_cali (wxCommandEvent & event)
{
    for (auto i = 0; i < m_ams_info.size(); i++) {
        if (m_ams_info[i].ams_id == m_current_ams) { m_ams_info[i].current_action = AMSAction::AMS_ACTION_CALI; }
    }
    post_event(SimpleEvent(EVT_AMS_EXTRUSION_CALI));
}
References Slic3r::GUI::AMS_ACTION_CALI, m_ams_info, m_current_ams, and post_event().
Referenced by AMSControl().
on_filament_load()
void Slic3r::GUI::AMSControl::on_filament_load (wxCommandEvent & event)
{
    m_button_extruder_back->Disable();
    for (auto i = 0; i < m_ams_info.size(); i++) {
        if (m_ams_info[i].ams_id == m_current_ams) { m_ams_info[i].current_action = AMSAction::AMS_ACTION_LOAD; }
    }
    post_event(SimpleEvent(EVT_AMS_LOAD));
}
References Slic3r::GUI::AMS_ACTION_LOAD, m_ams_info, m_button_extruder_back, m_current_ams, and post_event().
Referenced by AMSControl().
on_filament_unload()
void Slic3r::GUI::AMSControl::on_filament_unload (wxCommandEvent & event)
{
    m_button_extruder_feed->Disable();
    for (auto i = 0; i < m_ams_info.size(); i++) {
        if (m_ams_info[i].ams_id == m_current_ams) { m_ams_info[i].current_action = AMSAction::AMS_ACTION_UNLOAD; }
    }
    post_event(SimpleEvent(EVT_AMS_UNLOAD));
}
References Slic3r::GUI::AMS_ACTION_UNLOAD, m_ams_info, m_button_extruder_feed, m_current_ams, and post_event().
Referenced by AMSControl().
PlayRridLoading()
void Slic3r::GUI::AMSControl::PlayRridLoading (wxString amsid, wxString canid)
{
    AmsCansHash::iterator iter             = m_ams_cans_list.begin();
    auto                  count_item_index = 0;
    for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
        AmsCansWindow *cans = m_ams_cans_list[i];
        if (cans->amsCans->m_info.ams_id == amsid) { cans->amsCans->PlayRridLoading(canid); }
        iter++;
    }
}
References Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::AmsCansWindow::amsCans, m_ams_cans_list, Slic3r::GUI::AmsCans::m_info, and Slic3r::GUI::AmsCans::PlayRridLoading().
Referenced by Slic3r::GUI::StatusPanel::update_ams().
post_event()
void Slic3r::GUI::AMSControl::post_event (wxEvent && event)
{
    event.SetEventObject(m_parent);
    wxPostEvent(m_parent, event);
}
Referenced by AMSControl(), on_ams_setting_click(), on_clibration_again_click(), on_clibration_cancel_click(), on_extrusion_cali(), on_filament_load(), and on_filament_unload().
Reset()
void Slic3r::GUI::AMSControl::Reset ()
{
    auto caninfo0_0 = Caninfo{"0", "", *wxWHITE, AMSCanType::AMS_CAN_TYPE_NONE};
    auto caninfo0_1 = Caninfo{"1", "", *wxWHITE, AMSCanType::AMS_CAN_TYPE_NONE};
    auto caninfo0_2 = Caninfo{"2", "", *wxWHITE, AMSCanType::AMS_CAN_TYPE_NONE};
    auto caninfo0_3 = Caninfo{"3", "", *wxWHITE, AMSCanType::AMS_CAN_TYPE_NONE};
    AMSinfo ams1 = AMSinfo{"0", std::vector<Caninfo>{caninfo0_0, caninfo0_1, caninfo0_2, caninfo0_3}};
    AMSinfo ams2 = AMSinfo{"1", std::vector<Caninfo>{caninfo0_0, caninfo0_1, caninfo0_2, caninfo0_3}};
    AMSinfo ams3 = AMSinfo{"2", std::vector<Caninfo>{caninfo0_0, caninfo0_1, caninfo0_2, caninfo0_3}};
    AMSinfo ams4 = AMSinfo{"3", std::vector<Caninfo>{caninfo0_0, caninfo0_1, caninfo0_2, caninfo0_3}};
    std::vector<AMSinfo>           ams_info{ams1, ams2, ams3, ams4};
    std::vector<AMSinfo>::iterator it;
    UpdateAms(ams_info, false, false, true);
    m_current_show_ams  = "";
    m_current_ams       = "";
    m_current_senect    = "";
}
References Slic3r::GUI::AMS_CAN_TYPE_NONE, m_current_ams, m_current_senect, m_current_show_ams, and UpdateAms().
Referenced by Slic3r::GUI::StatusPanel::set_default().
reset_vams()
void Slic3r::GUI::AMSControl::reset_vams ()
{
    m_vams_lib->m_info.k = 0;
    m_vams_lib->m_info.n = 0;
    m_vams_lib->m_info.material_name = wxEmptyString;
    m_vams_lib->m_info.material_colour = AMS_CONTROL_WHITE_COLOUR;
    m_vams_info.material_name = wxEmptyString;
    m_vams_info.material_colour = AMS_CONTROL_WHITE_COLOUR;
    m_vams_lib->Refresh();
}
References AMS_CONTROL_WHITE_COLOUR, Slic3r::GUI::Caninfo::k, Slic3r::GUI::AMSLib::m_info, m_vams_info, m_vams_lib, Slic3r::GUI::Caninfo::material_colour, Slic3r::GUI::Caninfo::material_name, and Slic3r::GUI::Caninfo::n.
SetActionState()
void Slic3r::GUI::AMSControl::SetActionState (bool button_status[])
{
    if (button_status[ActionButton::ACTION_BTN_CALI]) m_button_extrusion_cali->Enable();
    else m_button_extrusion_cali->Disable();
    if (button_status[ActionButton::ACTION_BTN_LOAD]) m_button_extruder_feed->Enable();
    else m_button_extruder_feed->Disable();
    if (button_status[ActionButton::ACTION_BTN_UNLOAD]) m_button_extruder_back->Enable();
    else m_button_extruder_back->Disable();
}
References Slic3r::GUI::ACTION_BTN_CALI, Slic3r::GUI::ACTION_BTN_LOAD, Slic3r::GUI::ACTION_BTN_UNLOAD, Button::Enable(), m_button_extruder_back, m_button_extruder_feed, and m_button_extrusion_cali.
Referenced by Slic3r::GUI::StatusPanel::update_ams_control_state().
SetAmsStep()
void Slic3r::GUI::AMSControl::SetAmsStep (std::string ams_id, std::string canid, AMSPassRoadType type, AMSPassRoadSTEP step)
{
    AmsCansWindow *cans     = nullptr;
    bool           notfound = true;
    for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
        cans = m_ams_cans_list[i];
        if (cans->amsCans->m_info.ams_id == ams_id) {
            notfound = false;
            break;
        }
    }
    if (ams_id != m_last_ams_id || m_last_tray_id != canid) {
        SetAmsStep(m_last_ams_id, m_last_tray_id, AMSPassRoadType::AMS_ROAD_TYPE_UNLOAD, AMSPassRoadSTEP::AMS_ROAD_STEP_NONE);
        m_vams_extra_road->OnVamsLoading(false);
        m_extruder->OnVamsLoading(false);
        m_vams_road->OnVamsLoading(false);
    }
    if (notfound) return;
    if (cans == nullptr) return;
    m_last_ams_id = ams_id;
    m_last_tray_id = canid;
    if (step == AMSPassRoadSTEP::AMS_ROAD_STEP_NONE) {
        cans->amsCans->SetAmsStep(canid, type, AMSPassRoadSTEP::AMS_ROAD_STEP_NONE);
        m_extruder->OnAmsLoading(false);
    }
    if (step == AMSPassRoadSTEP::AMS_ROAD_STEP_COMBO_LOAD_STEP1) {
        cans->amsCans->SetAmsStep(canid, type, AMSPassRoadSTEP::AMS_ROAD_STEP_1);
        m_extruder->OnAmsLoading(false);
    }
    if (step == AMSPassRoadSTEP::AMS_ROAD_STEP_COMBO_LOAD_STEP2) {
        cans->amsCans->SetAmsStep(canid, type, AMSPassRoadSTEP::AMS_ROAD_STEP_1);
        cans->amsCans->SetAmsStep(canid, type, AMSPassRoadSTEP::AMS_ROAD_STEP_2);
        if (m_current_show_ams == ams_id) {
            m_extruder->OnAmsLoading(true, cans->amsCans->GetTagColr(canid));
        }
    }
    if (step == AMSPassRoadSTEP::AMS_ROAD_STEP_COMBO_LOAD_STEP3) {
        cans->amsCans->SetAmsStep(canid, type, AMSPassRoadSTEP::AMS_ROAD_STEP_1);
        cans->amsCans->SetAmsStep(canid, type, AMSPassRoadSTEP::AMS_ROAD_STEP_2);
        cans->amsCans->SetAmsStep(canid, type, AMSPassRoadSTEP::AMS_ROAD_STEP_3);
        m_extruder->OnAmsLoading(true, cans->amsCans->GetTagColr(canid));
    }
    for (auto i = 0; i < m_ams_info.size(); i++) {
        if (m_ams_info[i].ams_id == ams_id) {
            m_ams_info[i].current_step   = step;
            m_ams_info[i].current_can_id = canid;
        }
    }
}
References Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::AMS_ROAD_STEP_1, Slic3r::GUI::AMS_ROAD_STEP_2, Slic3r::GUI::AMS_ROAD_STEP_3, Slic3r::GUI::AMS_ROAD_STEP_COMBO_LOAD_STEP1, Slic3r::GUI::AMS_ROAD_STEP_COMBO_LOAD_STEP2, Slic3r::GUI::AMS_ROAD_STEP_COMBO_LOAD_STEP3, Slic3r::GUI::AMS_ROAD_STEP_NONE, Slic3r::GUI::AMS_ROAD_TYPE_UNLOAD, Slic3r::GUI::AmsCansWindow::amsCans, Slic3r::GUI::AmsCans::GetTagColr(), m_ams_cans_list, m_ams_info, m_current_show_ams, m_extruder, Slic3r::GUI::AmsCans::m_info, m_last_ams_id, m_last_tray_id, m_vams_extra_road, m_vams_road, Slic3r::GUI::AMSextruder::OnAmsLoading(), Slic3r::GUI::AMSextruder::OnVamsLoading(), Slic3r::GUI::AMSVirtualRoad::OnVamsLoading(), Slic3r::GUI::AMSRoad::OnVamsLoading(), SetAmsStep(), and Slic3r::GUI::AmsCans::SetAmsStep().
Referenced by SetAmsStep(), and Slic3r::GUI::StatusPanel::update_ams().
SetClibrationLink()
void Slic3r::GUI::AMSControl::SetClibrationLink (wxString link)
{
    m_hyperlink->SetLabel(link);
    m_hyperlink->SetURL(link);
    m_hyperlink->Refresh();
    m_hyperlink->Update();
}
References m_hyperlink.
SetClibrationpercent()
void Slic3r::GUI::AMSControl::SetClibrationpercent (int percent)
{ m_text_calibration_percent->SetLabelText(wxString::Format("%d%%", percent)); }
References m_text_calibration_percent.
SetExtruder()
void Slic3r::GUI::AMSControl::SetExtruder (bool on_off, bool is_vams, wxColour col)
{
    if (!on_off) {
        m_extruder->TurnOff();
        m_vams_extra_road->OnVamsLoading(false);
        m_extruder->OnVamsLoading(false);
        m_vams_road->OnVamsLoading(false);
    } else {
        m_extruder->TurnOn(col);
        m_extruder->OnAmsLoading(true, col);
    }
    if (is_vams && on_off) {
        m_extruder->OnAmsLoading(false, col);
        m_vams_extra_road->OnVamsLoading(true, col);
        m_extruder->OnVamsLoading(true, col);
        m_vams_road->OnVamsLoading(true, col);
    }
    else {
        m_vams_extra_road->OnVamsLoading(false, col);
        m_extruder->OnVamsLoading(false, col);
        m_vams_road->OnVamsLoading(false, col);
    }
}
References col(), m_extruder, m_vams_extra_road, m_vams_road, Slic3r::GUI::AMSextruder::OnAmsLoading(), Slic3r::GUI::AMSextruder::OnVamsLoading(), Slic3r::GUI::AMSVirtualRoad::OnVamsLoading(), Slic3r::GUI::AMSRoad::OnVamsLoading(), Slic3r::GUI::AMSextruder::TurnOff(), and Slic3r::GUI::AMSextruder::TurnOn().
Referenced by Slic3r::GUI::StatusPanel::update_ams().
SetFilamentStep()
void Slic3r::GUI::AMSControl::SetFilamentStep (int item_idx, FilamentStepType f_type, bool is_extrusion_exist = false)
{
    if (item_idx == FilamentStep::STEP_IDLE) {
        m_simplebook_right->SetSelection(0);
        m_filament_load_step->Idle();
        m_filament_unload_step->Idle();
        m_filament_vt_load_step->Idle();
        return;
    }
    if (f_type == FilamentStepType::STEP_TYPE_LOAD) {
        if (item_idx > 0 && item_idx < FilamentStep::STEP_COUNT) {
            m_simplebook_right->SetSelection(1);
            m_filament_load_step->SelectItem(item_idx - 1);
        } else {
            m_filament_load_step->Idle();
        }
    } else if (f_type == FilamentStepType::STEP_TYPE_UNLOAD) {
        if (item_idx > 0 && item_idx < FilamentStep::STEP_COUNT) {
            m_simplebook_right->SetSelection(2);
            m_filament_unload_step->SelectItem(item_idx - 1);
        }
        else {
            m_filament_unload_step->Idle();
        }
    } else if (f_type == FilamentStepType::STEP_TYPE_VT_LOAD) {
        m_simplebook_right->SetSelection(3);
        if (item_idx == STEP_HEAT_NOZZLE) {
            m_filament_vt_load_step->SelectItem(0);
        }
        else if (item_idx == STEP_FEED_FILAMENT) {
            m_filament_vt_load_step->SelectItem(1);
        }
        else if (item_idx == STEP_CONFIRM_EXTRUDED) {
            m_filament_vt_load_step->SelectItem(2);
        }
        else if (item_idx == STEP_PURGE_OLD_FILAMENT) {
            m_filament_vt_load_step->SelectItem(3);
        }
        else {
            m_filament_vt_load_step->Idle();
        }
    } else {
        if (item_idx > 0 && item_idx < FilamentStep::STEP_COUNT) {
            m_simplebook_right->SetSelection(1);
            m_filament_load_step->SelectItem(item_idx - 1);
        }
        else {
            m_filament_load_step->Idle();
        }
    }
}
References StepCtrlBase::Idle(), m_filament_load_step, m_filament_unload_step, m_filament_vt_load_step, m_simplebook_right, StepCtrlBase::SelectItem(), Slic3r::GUI::STEP_CONFIRM_EXTRUDED, Slic3r::GUI::STEP_COUNT, Slic3r::GUI::STEP_FEED_FILAMENT, Slic3r::GUI::STEP_HEAT_NOZZLE, Slic3r::GUI::STEP_IDLE, Slic3r::GUI::STEP_PURGE_OLD_FILAMENT, Slic3r::GUI::STEP_TYPE_LOAD, Slic3r::GUI::STEP_TYPE_UNLOAD, and Slic3r::GUI::STEP_TYPE_VT_LOAD.
Referenced by Slic3r::GUI::StatusPanel::update_ams().
SetHumidity()
void Slic3r::GUI::AMSControl::SetHumidity (std::string amsid, int humidity)
{
    for (auto i = 0; i < m_ams_item_list.GetCount(); i++) {
        AmsItems *item = m_ams_item_list[i];
        if (amsid == item->amsItem->m_amsinfo.ams_id) { item->amsItem->SetHumidity(humidity); }
    }
}
References Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::AmsItems::amsItem, m_ams_item_list, Slic3r::GUI::AMSItem::m_amsinfo, and Slic3r::GUI::AMSItem::SetHumidity().
show_filament_backup()
void Slic3r::GUI::AMSControl::show_filament_backup (bool show)
{
}
Referenced by Slic3r::GUI::StatusPanel::update_ams().
show_noams_mode()
void Slic3r::GUI::AMSControl::show_noams_mode (bool show, bool support_virtual_tray, bool support_extrustion_cali, bool support_vt_load = false)
{
    show_vams(support_virtual_tray);
    m_sizer_ams_tips->Show(support_virtual_tray);
    if (!support_extrustion_cali)
        m_button_extrusion_cali->Hide();
    else {
        m_button_extrusion_cali->Show();
    }
    show?ExitNoneAMSMode() : EnterNoneAMSMode(support_vt_load);
}
References EnterNoneAMSMode(), ExitNoneAMSMode(), m_button_extrusion_cali, m_sizer_ams_tips, and show_vams().
Referenced by Slic3r::GUI::StatusBasePanel::show_ams_group().
show_vams()
void Slic3r::GUI::AMSControl::show_vams (bool show)
{
    m_panel_virtual->Show(show);
    m_vams_sizer->Show(show);
    m_vams_extra_road->Show(show);
    m_extruder->has_ams(show);
    show_vams_kn_value(show);
    Layout();
    if (show && m_is_none_ams_mode) {
        if (m_current_ams == "") {
            wxMouseEvent event(wxEVT_LEFT_DOWN);
            event.SetEventObject(m_vams_lib);
            wxPostEvent(m_vams_lib, event);
        }
    }
}
References Slic3r::GUI::AMSextruder::has_ams(), m_current_ams, m_extruder, m_is_none_ams_mode, m_panel_virtual, m_vams_extra_road, m_vams_lib, m_vams_sizer, show_vams_kn_value(), and Slic3r::GUI::wxMouseEvent.
Referenced by show_noams_mode().
show_vams_kn_value()
void Slic3r::GUI::AMSControl::show_vams_kn_value (bool show)
{
    m_vams_lib->show_kn_value(show);
}
References m_vams_lib, and Slic3r::GUI::AMSLib::show_kn_value().
Referenced by show_vams().
ShowFilamentTip()
void Slic3r::GUI::AMSControl::ShowFilamentTip (bool hasams = true)
{
    m_simplebook_right->SetSelection(0);
    if (hasams) {
        m_tip_right_top->Show();
        m_tip_load_info->SetLabelText(_L("Choose an AMS slot then press \"Load\" or \"Unload\" button to automatically load or unload filiament."));
    } else {
        // m_tip_load_info->SetLabelText(_L("Before loading, please make sure the filament is pushed into toolhead."));
        m_tip_right_top->Hide();
        m_tip_load_info->SetLabelText(wxEmptyString);
    }
    m_sizer_right_tip->Layout();
    m_tip_load_info->Wrap(AMS_STEP_SIZE.x);
    m_tip_load_info->SetMinSize(AMS_STEP_SIZE);
}
References _L, AMS_STEP_SIZE, m_simplebook_right, m_sizer_right_tip, m_tip_load_info, and m_tip_right_top.
Referenced by EnterNoneAMSMode(), and ExitNoneAMSMode().
StopRridLoading()
void Slic3r::GUI::AMSControl::StopRridLoading (wxString amsid, wxString canid)
{
    AmsCansHash::iterator iter             = m_ams_cans_list.begin();
    auto                  count_item_index = 0;
    for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
        AmsCansWindow *cans = m_ams_cans_list[i];
        if (cans->amsCans->m_info.ams_id == amsid) { cans->amsCans->StopRridLoading(canid); }
        iter++;
    }
}
References Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::AmsCansWindow::amsCans, m_ams_cans_list, Slic3r::GUI::AmsCans::m_info, and Slic3r::GUI::AmsCans::StopRridLoading().
Referenced by Slic3r::GUI::StatusPanel::update_ams().
SwitchAms()
void Slic3r::GUI::AMSControl::SwitchAms (std::string ams_id)
{
    if (ams_id != std::to_string(VIRTUAL_TRAY_ID)) {
        if (m_current_show_ams != ams_id) {
            m_current_show_ams = ams_id;
            m_extruder->OnAmsLoading(false);
        }
    }
    for (auto i = 0; i < m_ams_item_list.GetCount(); i++) {
        AmsItems *item = m_ams_item_list[i];
        if (item->amsItem->m_amsinfo.ams_id == m_current_show_ams) {
            item->amsItem->OnSelected();
            m_current_senect = ams_id;
            for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
                AmsCansWindow* ams = m_ams_cans_list[i];
                if (ams->amsCans->m_info.ams_id == ams_id) {
                    ams->amsCans->SetDefSelectCan();
                    m_vams_lib->UnSelected();
                }
            }
        } else {
            item->amsItem->UnSelected();
            //item->amsItem->HideHumidity();
        }
        m_sizer_top->Layout();
        m_panel_top->Fit();
    }
    for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
        AmsCansWindow *cans = m_ams_cans_list[i];
        if (cans->amsCans->m_info.ams_id == ams_id) {
            m_simplebook_cans->SetSelection(cans->amsCans->m_selection);
        }
    }
    m_current_ams = ams_id;
     // update extruder
    //m_extruder->OnAmsLoading(false);
    for (auto i = 0; i < m_ams_info.size(); i++) {
        if (m_ams_info[i].ams_id == m_current_ams) {
            switch (m_ams_info[i].current_step) {
            case AMSPassRoadSTEP::AMS_ROAD_STEP_NONE: m_extruder->TurnOff(); break;
            case AMSPassRoadSTEP::AMS_ROAD_STEP_COMBO_LOAD_STEP1: m_extruder->TurnOff(); break;
            case AMSPassRoadSTEP::AMS_ROAD_STEP_COMBO_LOAD_STEP2: m_extruder->TurnOn(GetCanColour(m_current_ams, m_ams_info[i].current_can_id)); break;
            case AMSPassRoadSTEP::AMS_ROAD_STEP_COMBO_LOAD_STEP3: m_extruder->TurnOn(GetCanColour(m_current_ams, m_ams_info[i].current_can_id)); break;
            }
        }
    }
}
References Slic3r::GUI::AMSinfo::ams_id, Slic3r::GUI::AMS_ROAD_STEP_COMBO_LOAD_STEP1, Slic3r::GUI::AMS_ROAD_STEP_COMBO_LOAD_STEP2, Slic3r::GUI::AMS_ROAD_STEP_COMBO_LOAD_STEP3, Slic3r::GUI::AMS_ROAD_STEP_NONE, Slic3r::GUI::AmsCansWindow::amsCans, Slic3r::GUI::AmsItems::amsItem, GetCanColour(), m_ams_cans_list, m_ams_info, m_ams_item_list, Slic3r::GUI::AMSItem::m_amsinfo, m_current_ams, m_current_senect, m_current_show_ams, m_extruder, Slic3r::GUI::AmsCans::m_info, m_panel_top, Slic3r::GUI::AmsCans::m_selection, m_simplebook_cans, m_sizer_top, m_vams_lib, Slic3r::GUI::AMSextruder::OnAmsLoading(), Slic3r::GUI::AMSItem::OnSelected(), Slic3r::GUI::AmsCans::SetDefSelectCan(), Slic3r::GUI::AMSextruder::TurnOff(), Slic3r::GUI::AMSextruder::TurnOn(), Slic3r::GUI::AMSLib::UnSelected(), Slic3r::GUI::AMSItem::UnSelected(), and VIRTUAL_TRAY_ID.
Referenced by AMSControl(), AddAms(), and UpdateAms().
update_vams_kn_value()
void Slic3r::GUI::AMSControl::update_vams_kn_value (AmsTray tray, MachineObject * obj)
{
    m_vams_lib->m_obj = obj;
    m_vams_info.k = tray.k;
    m_vams_info.n = tray.n;
    m_vams_lib->m_info.k = tray.k;
    m_vams_lib->m_info.n = tray.n;
    m_vams_info.material_name = tray.get_display_filament_type();
    m_vams_info.material_colour = tray.get_color();
    m_vams_lib->m_info.material_name = tray.get_display_filament_type();
    m_vams_lib->m_info.material_colour = tray.get_color();
    m_vams_lib->Refresh();
}
References Slic3r::AmsTray::get_color(), Slic3r::AmsTray::get_display_filament_type(), Slic3r::AmsTray::k, Slic3r::GUI::Caninfo::k, Slic3r::GUI::AMSLib::m_info, Slic3r::GUI::AMSLib::m_obj, m_vams_info, m_vams_lib, Slic3r::GUI::Caninfo::material_colour, Slic3r::GUI::Caninfo::material_name, Slic3r::AmsTray::n, and Slic3r::GUI::Caninfo::n.
Referenced by Slic3r::GUI::StatusPanel::update_ams().
UpdateAms()
void Slic3r::GUI::AMSControl::UpdateAms (std::vector< AMSinfo > info, bool keep_selection = true, bool has_extrusion_cali = true, bool is_reset = false)
{
    std::string curr_ams_id = GetCurentAms();
    std::string curr_can_id = GetCurrentCan(curr_ams_id);
    m_button_area->Layout();
    m_button_area->Fit();
    // update item
    m_ams_info = info;
    if (info.size() > 1) {
        m_simplebook_amsitems->Show();
        m_amswin->Layout();
        m_amswin->Fit();
        SetSize(m_amswin->GetSize());
        SetMinSize(m_amswin->GetSize());
    } else {
        m_simplebook_amsitems->Hide();
        m_amswin->Layout();
        m_amswin->Fit();
        SetSize(m_amswin->GetSize());
        SetMinSize(m_amswin->GetSize());
    }
    for (auto i = 0; i < m_ams_item_list.GetCount(); i++) {
        AmsItems *item = m_ams_item_list[i];
        if (i < info.size() && info.size() > 1) {
            item->amsItem->Update(m_ams_info[i]);
            item->amsItem->Open();
        } else {
            item->amsItem->Close();
        }
    }
    // update cans
    for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
        AmsCansWindow *cans = m_ams_cans_list[i];
        for (auto ifo : m_ams_info) {
            if (ifo.ams_id == cans->amsIndex) {
                cans->amsCans->m_info = ifo;
                cans->amsCans->Update(ifo);
                cans->amsCans->show_sn_value(has_extrusion_cali);
            }
        }
    }
    /*if (m_current_senect.empty() && info.size() > 0) {
        if (curr_ams_id.empty()) {
            SwitchAms(info[0].ams_id);
            return;
        }
        if (keep_selection) {
            SwitchAms(curr_ams_id);
            for (auto i = 0; i < m_ams_cans_list.GetCount(); i++) {
                AmsCansWindow *cans = m_ams_cans_list[i];
                if (i < info.size()) { cans->amsCans->SelectCan(curr_can_id); }
            }
            return;
        }
    }*/
    if ( m_current_show_ams.empty() && !is_reset ) {
        if (info.size() > 0) {
            SwitchAms(info[0].ams_id);
        }
    }
}
References Slic3r::GUI::AmsCansWindow::amsCans, Slic3r::GUI::AmsCansWindow::amsIndex, Slic3r::GUI::AmsItems::amsItem, Slic3r::GUI::AMSItem::Close(), GetCurentAms(), GetCurrentCan(), m_ams_cans_list, m_ams_info, m_ams_item_list, m_amswin, m_button_area, m_current_show_ams, Slic3r::GUI::AmsCans::m_info, m_simplebook_amsitems, Slic3r::GUI::AMSItem::Open(), Slic3r::GUI::AmsCans::show_sn_value(), SwitchAms(), Slic3r::GUI::AMSItem::Update(), and Slic3r::GUI::AmsCans::Update().
Referenced by Reset(), and Slic3r::GUI::StatusPanel::update_ams().
UpdateStepCtrl()
void Slic3r::GUI::AMSControl::UpdateStepCtrl (bool is_extrusion_exist)
{
    m_filament_load_step->DeleteAllItems();
    m_filament_unload_step->DeleteAllItems();
    m_filament_vt_load_step->DeleteAllItems();
    if(is_extrusion){
        wxString FILAMENT_LOAD_STEP_STRING[LOAD_STEP_COUNT] = {
            _L("Heat the nozzle"),
            _L("Cut filament"),
            _L("Pull back current filament"),
            _L("Push new filament into extruder"),
            _L("Purge old filament"),
        };
        for (int i = 0; i < LOAD_STEP_COUNT; i++) {
            m_filament_load_step->AppendItem(FILAMENT_LOAD_STEP_STRING[i]);
        }
    }else{
        wxString FILAMENT_LOAD_STEP_STRING[LOAD_WITH_TEMP_STEP_COUNT] = {
            _L("Heat the nozzle"),
            _L("Push new filament into extruder"),
            _L("Purge old filament"),
        };
        for (int i = 0; i < LOAD_WITH_TEMP_STEP_COUNT; i++) {
            m_filament_load_step->AppendItem(FILAMENT_LOAD_STEP_STRING[i]);
        }
    }
    wxString VT_TRAY_LOAD_STEP_STRING[VT_LOAD_STEP_COUNT] = {
        _L("Heat the nozzle"),
        _L("Feed new filament from external spool"),
        _L("Confirm whether the filament has been extruded"),
        _L("Purge old filament"),
    };
    wxString FILAMENT_UNLOAD_STEP_STRING[UNLOAD_STEP_COUNT] = {
        _L("Heat the nozzle"),
        _L("Cut filament"),
        _L("Pull back current filament")
    };
//    for (int i = 0; i < LOAD_STEP_COUNT; i++) {
//        m_filament_load_step->AppendItem(FILAMENT_LOAD_STEP_STRING[i]);
//    }
    for (int i = 0; i < UNLOAD_STEP_COUNT; i++) {
        m_filament_unload_step->AppendItem(FILAMENT_UNLOAD_STEP_STRING[i]);
    }
    for (int i = 0; i < VT_LOAD_STEP_COUNT; i++) {
        m_filament_vt_load_step->AppendItem(VT_TRAY_LOAD_STEP_STRING[i]);
    }
}
References _L, StepCtrlBase::AppendItem(), StepCtrlBase::DeleteAllItems(), Slic3r::GUI::LOAD_STEP_COUNT, Slic3r::GUI::LOAD_WITH_TEMP_STEP_COUNT, m_filament_load_step, m_filament_unload_step, m_filament_vt_load_step, Slic3r::GUI::UNLOAD_STEP_COUNT, and Slic3r::GUI::VT_LOAD_STEP_COUNT.
Referenced by AMSControl(), and Slic3r::GUI::StatusPanel::on_ams_load_curr().
Member Data Documentation
m_ams_cans_list
AmsCansHash Slic3r::GUI::AMSControl::m_ams_cans_list protected
Referenced by AMSControl(), AddAms(), Enable(), GetCurrentCan(), msw_rescale(), PlayRridLoading(), SetAmsStep(), StopRridLoading(), SwitchAms(), and UpdateAms().
m_ams_count
int Slic3r::GUI::AMSControl::m_ams_count = {0} protected
Referenced by AddAms().
m_ams_info
std::vector<AMSinfo> Slic3r::GUI::AMSControl::m_ams_info protected
Referenced by AddAms(), GetCanColour(), on_ams_setting_click(), on_extrusion_cali(), on_filament_load(), on_filament_unload(), SetAmsStep(), SwitchAms(), and UpdateAms().
m_ams_introduce_popup
AmsIntroducePopup Slic3r::GUI::AMSControl::m_ams_introduce_popup protected
Referenced by AMSControl().
m_ams_item_list
AmsItemsHash Slic3r::GUI::AMSControl::m_ams_item_list protected
Referenced by AddAms(), Enable(), SetHumidity(), SwitchAms(), and UpdateAms().
m_ams_selection
std::map<std::string, int> Slic3r::GUI::AMSControl::m_ams_selection protected
m_amswin
wxWindow* Slic3r::GUI::AMSControl::m_amswin = {nullptr} protected
Referenced by AMSControl(), EnterNoneAMSMode(), ExitNoneAMSMode(), and UpdateAms().
m_button_ams_setting
wxStaticBitmap* Slic3r::GUI::AMSControl::m_button_ams_setting = {nullptr} protected
Referenced by AMSControl(), Enable(), EnterNoneAMSMode(), ExitNoneAMSMode(), and msw_rescale().
m_button_ams_setting_hover
ScalableBitmap Slic3r::GUI::AMSControl::m_button_ams_setting_hover protected
Referenced by AMSControl(), and msw_rescale().
m_button_ams_setting_normal
ScalableBitmap Slic3r::GUI::AMSControl::m_button_ams_setting_normal protected
Referenced by AMSControl(), and msw_rescale().
m_button_ams_setting_press
ScalableBitmap Slic3r::GUI::AMSControl::m_button_ams_setting_press protected
Referenced by AMSControl(), and msw_rescale().
m_button_area
wxWindow* Slic3r::GUI::AMSControl::m_button_area = {nullptr} protected
Referenced by AMSControl(), and UpdateAms().
m_button_extruder_back
Button* Slic3r::GUI::AMSControl::m_button_extruder_back = {nullptr} protected
Referenced by AMSControl(), Enable(), EnterNoneAMSMode(), ExitNoneAMSMode(), init_scaled_buttons(), msw_rescale(), on_filament_load(), and SetActionState().
m_button_extruder_feed
Button* Slic3r::GUI::AMSControl::m_button_extruder_feed = {nullptr} protected
Referenced by AMSControl(), Enable(), EnterNoneAMSMode(), ExitNoneAMSMode(), init_scaled_buttons(), msw_rescale(), on_filament_unload(), and SetActionState().
m_button_extrusion_cali
Button* Slic3r::GUI::AMSControl::m_button_extrusion_cali = {nullptr} protected
Referenced by AMSControl(), Enable(), init_scaled_buttons(), msw_rescale(), SetActionState(), and show_noams_mode().
m_button_guide
Button* Slic3r::GUI::AMSControl::m_button_guide = {nullptr} protected
Referenced by AMSControl(), EnterNoneAMSMode(), ExitNoneAMSMode(), and msw_rescale().
m_button_retry
Button* Slic3r::GUI::AMSControl::m_button_retry = {nullptr} protected
Referenced by AMSControl(), EnterNoneAMSMode(), ExitNoneAMSMode(), and msw_rescale().
m_current_ams
std::string Slic3r::GUI::AMSControl::m_current_ams protected
Referenced by AMSControl(), GetCurentAms(), on_ams_setting_click(), on_extrusion_cali(), on_filament_load(), on_filament_unload(), Reset(), show_vams(), and SwitchAms().
m_current_senect
std::string Slic3r::GUI::AMSControl::m_current_senect
Referenced by Reset(), and SwitchAms().
m_current_show_ams
std::string Slic3r::GUI::AMSControl::m_current_show_ams protected
Referenced by GetCurentShowAms(), Reset(), SetAmsStep(), SwitchAms(), and UpdateAms().
m_extruder
AMSextruder* Slic3r::GUI::AMSControl::m_extruder = {nullptr} protected
Referenced by AMSControl(), EnterNoneAMSMode(), ExitNoneAMSMode(), msw_rescale(), SetAmsStep(), SetExtruder(), show_vams(), and SwitchAms().
m_filament_load_step
::StepIndicator* Slic3r::GUI::AMSControl::m_filament_load_step = {nullptr} protected
Referenced by AMSControl(), Enable(), SetFilamentStep(), and UpdateStepCtrl().
m_filament_unload_step
::StepIndicator* Slic3r::GUI::AMSControl::m_filament_unload_step = {nullptr} protected
Referenced by AMSControl(), SetFilamentStep(), and UpdateStepCtrl().
m_filament_vt_load_step
::StepIndicator* Slic3r::GUI::AMSControl::m_filament_vt_load_step = {nullptr} protected
Referenced by AMSControl(), SetFilamentStep(), and UpdateStepCtrl().
m_Humidity_tip_popup
AmsHumidityTipPopup Slic3r::GUI::AMSControl::m_Humidity_tip_popup protected
Referenced by AMSControl().
m_hyperlink
wxHyperlinkCtrl* Slic3r::GUI::AMSControl::m_hyperlink = {nullptr} protected
Referenced by AMSControl(), and SetClibrationLink().
m_is_none_ams_mode
bool Slic3r::GUI::AMSControl::m_is_none_ams_mode {false}
Referenced by EnterNoneAMSMode(), ExitNoneAMSMode(), and show_vams().
m_last_ams_id
std::string Slic3r::GUI::AMSControl::m_last_ams_id protected
Referenced by SetAmsStep().
m_last_tray_id
std::string Slic3r::GUI::AMSControl::m_last_tray_id protected
Referenced by SetAmsStep().
m_none_ams_panel
wxWindow* Slic3r::GUI::AMSControl::m_none_ams_panel = {nullptr} protected
Referenced by AMSControl().
m_panel_can
StaticBox* Slic3r::GUI::AMSControl::m_panel_can = {nullptr} protected
Referenced by AMSControl().
m_panel_top
wxWindow* Slic3r::GUI::AMSControl::m_panel_top = {nullptr} protected
Referenced by AMSControl(), AddAms(), EnterNoneAMSMode(), ExitNoneAMSMode(), and SwitchAms().
m_panel_virtual
StaticBox* Slic3r::GUI::AMSControl::m_panel_virtual = {nullptr} protected
Referenced by AMSControl(), and show_vams().
m_simplebook_ams
wxSimplebook* Slic3r::GUI::AMSControl::m_simplebook_ams = {nullptr} protected
Referenced by AMSControl(), EnterNoneAMSMode(), and ExitNoneAMSMode().
m_simplebook_amsitems
wxSimplebook* Slic3r::GUI::AMSControl::m_simplebook_amsitems = {nullptr} protected
Referenced by AMSControl(), EnterNoneAMSMode(), ExitNoneAMSMode(), and UpdateAms().
m_simplebook_bottom
wxSimplebook* Slic3r::GUI::AMSControl::m_simplebook_bottom = {nullptr} protected
m_simplebook_calibration
wxSimplebook* Slic3r::GUI::AMSControl::m_simplebook_calibration = {nullptr} protected
Referenced by AMSControl(), and EnterCalibrationMode().
m_simplebook_cans
wxSimplebook* Slic3r::GUI::AMSControl::m_simplebook_cans = {nullptr} protected
Referenced by AMSControl(), AddAms(), and SwitchAms().
m_simplebook_right
wxSimplebook* Slic3r::GUI::AMSControl::m_simplebook_right = {nullptr} protected
Referenced by AMSControl(), SetFilamentStep(), and ShowFilamentTip().
m_sizer_ams_tips
wxBoxSizer* Slic3r::GUI::AMSControl::m_sizer_ams_tips = {nullptr} protected
Referenced by AMSControl(), and show_noams_mode().
m_sizer_cans
wxBoxSizer* Slic3r::GUI::AMSControl::m_sizer_cans = {nullptr} protected
Referenced by AMSControl().
m_sizer_right_tip
wxBoxSizer* Slic3r::GUI::AMSControl::m_sizer_right_tip = {nullptr} protected
Referenced by AMSControl(), and ShowFilamentTip().
m_sizer_top
wxBoxSizer* Slic3r::GUI::AMSControl::m_sizer_top = {nullptr} protected
Referenced by AMSControl(), AddAms(), CreateAms(), and SwitchAms().
m_sizer_vams_tips
wxBoxSizer* Slic3r::GUI::AMSControl::m_sizer_vams_tips = {nullptr} protected
Referenced by AMSControl().
m_text_calibration_percent
wxStaticText* Slic3r::GUI::AMSControl::m_text_calibration_percent = {nullptr} protected
Referenced by AMSControl(), and SetClibrationpercent().
m_tip_load_info
wxStaticText* Slic3r::GUI::AMSControl::m_tip_load_info = {nullptr} protected
Referenced by AMSControl(), and ShowFilamentTip().
m_tip_right_top
wxStaticText* Slic3r::GUI::AMSControl::m_tip_right_top = {nullptr} protected
Referenced by AMSControl(), and ShowFilamentTip().
m_vams_extra_road
AMSVirtualRoad* Slic3r::GUI::AMSControl::m_vams_extra_road = {nullptr} protected
Referenced by AMSControl(), msw_rescale(), SetAmsStep(), SetExtruder(), and show_vams().
m_vams_info
Caninfo Slic3r::GUI::AMSControl::m_vams_info protected
Referenced by AMSControl(), reset_vams(), and update_vams_kn_value().
m_vams_lib
AMSLib* Slic3r::GUI::AMSControl::m_vams_lib = {nullptr} protected
Referenced by AMSControl(), reset_vams(), show_vams(), show_vams_kn_value(), SwitchAms(), and update_vams_kn_value().
m_vams_road
AMSRoad* Slic3r::GUI::AMSControl::m_vams_road = {nullptr} protected
Referenced by AMSControl(), SetAmsStep(), and SetExtruder().
m_vams_sizer
wxBoxSizer* Slic3r::GUI::AMSControl::m_vams_sizer = {nullptr} protected
Referenced by AMSControl(), and show_vams().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Widgets/AMSControl.hpp
src/slic3r/GUI/Widgets/AMSControl.cpp