OrcaSlicer: Slic3r::MeshBoolean::mcut Namespace Reference
Slic3r::MeshBoolean::mcut Namespace Reference
Classes
struct McutMesh
struct McutMeshDeleter
Typedefs
using McutMeshPtr = std::unique_ptr< McutMesh, McutMeshDeleter >
Functions
bool empty (const McutMesh &mesh)
void triangle_mesh_to_mcut (const TriangleMesh &src_mesh, McutMesh &srcMesh, const Transform3d &src_nm=Transform3d::Identity())
McutMeshPtr triangle_mesh_to_mcut (const indexed_triangle_set &M)
TriangleMesh mcut_to_triangle_mesh (const McutMesh &mcutmesh)
void merge_mcut_meshes (McutMesh &src, const McutMesh &cut)
MCAPI_ATTR void MCAPI_CALL mcDebugOutput (McDebugSource source, McDebugType type, unsigned int id, McDebugSeverity severity, size_t length, const char *message, const void *userParam)
void do_boolean (McutMesh &srcMesh, const McutMesh &cutMesh, const std::string &boolean_opts)
std::vector< TriangleMesh > make_boolean (const McutMesh &srcMesh, const McutMesh &cutMesh, const std::string &boolean_opts)
void make_boolean (const TriangleMesh &src_mesh, const TriangleMesh &cut_mesh, std::vector< TriangleMesh > &dst_mesh, const std::string &boolean_opts)
Class Documentation
Slic3r::MeshBoolean::mcut::McutMesh
struct Slic3r::MeshBoolean::mcut::McutMesh
Class Members
vector< uint32_t > faceIndicesArray
vector< uint32_t > faceSizesArray
vector< double > vertexCoordsArray
Typedef Documentation
McutMeshPtr
using Slic3r::MeshBoolean::mcut::McutMeshPtr = typedef std::unique_ptr<McutMesh, McutMeshDeleter>
Function Documentation
do_boolean()
void Slic3r::MeshBoolean::mcut::do_boolean (McutMesh & srcMesh, const McutMesh & cutMesh, const std::string & boolean_opts)
{
    // create context
    McContext context = MC_NULL_HANDLE;
    McResult  err     = mcCreateContext(&context, 0);
    // add debug callback according to https://cutdigital.github.io/mcut.site/tutorials/debugging/
    mcDebugMessageCallback(context, mcDebugOutput, nullptr);
    mcDebugMessageControl(
        context,
        MC_DEBUG_SOURCE_ALL,
        MC_DEBUG_TYPE_ERROR,
        MC_DEBUG_SEVERITY_MEDIUM,
        true);
    // We can either let MCUT compute all possible meshes (including patches etc.), or we can
    // constrain the library to compute exactly the boolean op mesh we want. This 'constrained' case
    // is done with the following flags.
    // NOTE#1: you can extend these flags by bitwise ORing with additional flags (see `McDispatchFlags' in mcut.h)
    // NOTE#2: below order of columns MATTERS
    const std::map<std::string, McFlags> booleanOpts = {
        {"A_NOT_B", MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE | MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE},
        {"B_NOT_A", MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE | MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW},
        {"UNION", MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE | MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE},
        {"INTERSECTION", MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE | MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW},
    };
    std::map<std::string, McFlags>::const_iterator it          = booleanOpts.find(boolean_opts);
    McFlags                                        boolOpFlags = it->second;
    if (srcMesh.vertexCoordsArray.empty() && (boolean_opts == "UNION" || boolean_opts == "B_NOT_A")) {
        srcMesh = cutMesh;
        mcReleaseContext(context);
        return;
    }
    err = mcDispatch(context,
                     MC_DISPATCH_VERTEX_ARRAY_DOUBLE |          // vertices are in array of doubles
                         MC_DISPATCH_ENFORCE_GENERAL_POSITION | // perturb if necessary
                         boolOpFlags,                           // filter flags which specify the type of output we want
                     // source mesh
                     reinterpret_cast<const void *>(srcMesh.vertexCoordsArray.data()), reinterpret_cast<const uint32_t *>(srcMesh.faceIndicesArray.data()),
                     srcMesh.faceSizesArray.data(), static_cast<uint32_t>(srcMesh.vertexCoordsArray.size() / 3), static_cast<uint32_t>(srcMesh.faceSizesArray.size()),
                     // cut mesh
                     reinterpret_cast<const void *>(cutMesh.vertexCoordsArray.data()), cutMesh.faceIndicesArray.data(), cutMesh.faceSizesArray.data(),
                     static_cast<uint32_t>(cutMesh.vertexCoordsArray.size() / 3), static_cast<uint32_t>(cutMesh.faceSizesArray.size()));
    if (err != MC_NO_ERROR) {
        BOOST_LOG_TRIVIAL(debug) << "MCUT mcDispatch fails! err=" << err;
        mcReleaseContext(context);
        if (boolean_opts == "UNION") {
            merge_mcut_meshes(srcMesh, cutMesh);
        }
        else {
            // when src mesh has multiple connected components, mcut refuses to work.
            // But we can force it to work by spliting the src mesh into disconnected components,
            // and do booleans seperately, then merge all the results.
            indexed_triangle_set all_its;
            TriangleMesh tri_src = mcut_to_triangle_mesh(srcMesh);
            std::vector<indexed_triangle_set> src_parts = its_split(tri_src.its);
            if (src_parts.size() == 1)
            {
                //can not split, return error directly
                BOOST_LOG_TRIVIAL(error) << boost::format("bool operation %1% failed, also can not split")%boolean_opts;
                return;
            }
            for (size_t i = 0; i < src_parts.size(); i++)
            {
                auto part = triangle_mesh_to_mcut(src_parts[i]);
                do_boolean(*part, cutMesh, boolean_opts);
                TriangleMesh tri_part = mcut_to_triangle_mesh(*part);
                its_merge(all_its, tri_part.its);
            }
            srcMesh = *triangle_mesh_to_mcut(all_its);
        }
        return;
    }
    // query the number of available connected component
    uint32_t numConnComps;
    err = mcGetConnectedComponents(context, MC_CONNECTED_COMPONENT_TYPE_FRAGMENT, 0, NULL, &numConnComps);
    if (err != MC_NO_ERROR || numConnComps==0) {
        BOOST_LOG_TRIVIAL(debug) << "MCUT mcGetConnectedComponents fails! err=" << err << ", numConnComps" << numConnComps;
        mcReleaseContext(context);
        if (numConnComps == 0 && boolean_opts == "UNION") {
            merge_mcut_meshes(srcMesh, cutMesh);
        }
        return;
    }
    std::vector<McConnectedComponent> connectedComponents(numConnComps, MC_NULL_HANDLE);
    err = mcGetConnectedComponents(context, MC_CONNECTED_COMPONENT_TYPE_FRAGMENT, (uint32_t) connectedComponents.size(), connectedComponents.data(), NULL);
    McutMesh outMesh;
    int N_vertices = 0;
    // traversal of all connected components
    for (int n = 0; n < numConnComps; ++n) {
        // query the data of each connected component from MCUT
        McConnectedComponent connComp = connectedComponents[n];
        // query the vertices
        McSize numBytes                  = 0;
        err                               = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, 0, NULL, &numBytes);
        uint32_t            ccVertexCount = (uint32_t) (numBytes / (sizeof(double) * 3));
        std::vector<double> ccVertices((uint64_t) ccVertexCount * 3u, 0);
        err = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, numBytes, (void *) ccVertices.data(), NULL);
        // query the faces
        numBytes = 0;
        err      = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION, 0, NULL, &numBytes);
        std::vector<uint32_t> ccFaceIndices(numBytes / sizeof(uint32_t), 0);
        err = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION, numBytes, ccFaceIndices.data(), NULL);
        std::vector<uint32_t> faceSizes(ccFaceIndices.size() / 3, 3);
        const uint32_t ccFaceCount = static_cast<uint32_t>(faceSizes.size());
        // Here we show, how to know when connected components, pertain particular boolean operations.
        McPatchLocation patchLocation = (McPatchLocation) 0;
        err                           = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_PATCH_LOCATION, sizeof(McPatchLocation), &patchLocation, NULL);
        McFragmentLocation fragmentLocation = (McFragmentLocation) 0;
        err = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_FRAGMENT_LOCATION, sizeof(McFragmentLocation), &fragmentLocation, NULL);
        outMesh.vertexCoordsArray.insert(outMesh.vertexCoordsArray.end(), ccVertices.begin(), ccVertices.end());
        // add offset to face index
        for (size_t i = 0; i < ccFaceIndices.size(); i++) {
            ccFaceIndices[i] += N_vertices;
        }
        int faceVertexOffsetBase = 0;
        // for each face in CC
        std::vector<Vec3i> faces(ccFaceCount);
        for (uint32_t f = 0; f < ccFaceCount; ++f) {
            bool reverseWindingOrder = (fragmentLocation == MC_FRAGMENT_LOCATION_BELOW) && (patchLocation == MC_PATCH_LOCATION_OUTSIDE);
            int  faceSize            = faceSizes.at(f);
            if (reverseWindingOrder) {
                std::vector<uint32_t> faceIndex(faceSize);
                // for each vertex in face
                for (int v = faceSize - 1; v >= 0; v--) { faceIndex[v] = ccFaceIndices[(uint64_t) faceVertexOffsetBase + v]; }
                std::copy(faceIndex.begin(), faceIndex.end(), ccFaceIndices.begin() + faceVertexOffsetBase);
            }
            faceVertexOffsetBase += faceSize;
        }
        outMesh.faceIndicesArray.insert(outMesh.faceIndicesArray.end(), ccFaceIndices.begin(), ccFaceIndices.end());
        outMesh.faceSizesArray.insert(outMesh.faceSizesArray.end(), faceSizes.begin(), faceSizes.end());
        N_vertices += ccVertexCount;
    }
    // free connected component data
    err = mcReleaseConnectedComponents(context, 0, NULL);
    // destroy context
    err = mcReleaseContext(context);
    srcMesh = outMesh;
}
References do_boolean(), error, Slic3r::MeshBoolean::mcut::McutMesh::faceIndicesArray, Slic3r::MeshBoolean::mcut::McutMesh::faceSizesArray, Slic3r::TriangleMesh::its, Slic3r::its_merge(), Slic3r::its_split(), MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION, MC_CONNECTED_COMPONENT_DATA_FRAGMENT_LOCATION, MC_CONNECTED_COMPONENT_DATA_PATCH_LOCATION, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, MC_CONNECTED_COMPONENT_TYPE_FRAGMENT, MC_DEBUG_SEVERITY_MEDIUM, MC_DEBUG_SOURCE_ALL, MC_DEBUG_TYPE_ERROR, MC_DISPATCH_ENFORCE_GENERAL_POSITION, MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE, MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW, MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE, MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE, MC_DISPATCH_VERTEX_ARRAY_DOUBLE, MC_FRAGMENT_LOCATION_BELOW, MC_NO_ERROR, MC_NULL_HANDLE, MC_PATCH_LOCATION_OUTSIDE, mcCreateContext(), mcDebugMessageCallback(), mcDebugMessageControl(), mcDebugOutput(), mcDispatch(), mcGetConnectedComponentData(), mcGetConnectedComponents(), mcReleaseConnectedComponents(), mcReleaseContext(), mcut_to_triangle_mesh(), merge_mcut_meshes(), n, NULL, triangle_mesh_to_mcut(), and Slic3r::MeshBoolean::mcut::McutMesh::vertexCoordsArray.
Referenced by do_boolean(), make_boolean(), and Slic3r::csg::detail_mcut::perform_csg().
empty()
bool Slic3r::MeshBoolean::mcut::empty (const McutMesh & mesh)
{ return mesh.vertexCoordsArray.empty() || mesh.faceIndicesArray.empty(); }
References Slic3r::empty(), Slic3r::MeshBoolean::mcut::McutMesh::faceIndicesArray, and Slic3r::MeshBoolean::mcut::McutMesh::vertexCoordsArray.
Referenced by Slic3r::csg::check_csgmesh_booleans().
make_boolean() [1/2]
std::vector< TriangleMesh > Slic3r::MeshBoolean::mcut::make_boolean (const McutMesh & srcMesh, const McutMesh & cutMesh, const std::string & boolean_opts)
{
    // create context
    McContext context = MC_NULL_HANDLE;
    McResult  err     = mcCreateContext(&context, 0);
    // add debug callback according to https://cutdigital.github.io/mcut.site/tutorials/debugging/
    mcDebugMessageCallback(context, mcDebugOutput, nullptr);
    mcDebugMessageControl(
        context,
        MC_DEBUG_SOURCE_ALL,
        MC_DEBUG_TYPE_ERROR,
        MC_DEBUG_SEVERITY_MEDIUM,
        true);
    // We can either let MCUT compute all possible meshes (including patches etc.), or we can
    // constrain the library to compute exactly the boolean op mesh we want. This 'constrained' case
    // is done with the following flags.
    // NOTE#1: you can extend these flags by bitwise ORing with additional flags (see `McDispatchFlags' in mcut.h)
    // NOTE#2: below order of columns MATTERS
    const std::map<std::string, McFlags> booleanOpts = {
        {"A_NOT_B", MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE | MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE},
        {"B_NOT_A", MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE | MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW},
        {"UNION", MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE | MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE},
        {"INTERSECTION", MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE | MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW},
    };
    std::map<std::string, McFlags>::const_iterator it          = booleanOpts.find(boolean_opts);
    McFlags                                        boolOpFlags = it->second;
    err = mcDispatch(context,
                     MC_DISPATCH_VERTEX_ARRAY_DOUBLE |          // vertices are in array of doubles
                         MC_DISPATCH_ENFORCE_GENERAL_POSITION | // perturb if necessary
                         boolOpFlags,                           // filter flags which specify the type of output we want
                     // source mesh
                     reinterpret_cast<const void *>(srcMesh.vertexCoordsArray.data()), reinterpret_cast<const uint32_t *>(srcMesh.faceIndicesArray.data()),
                     srcMesh.faceSizesArray.data(), static_cast<uint32_t>(srcMesh.vertexCoordsArray.size() / 3), static_cast<uint32_t>(srcMesh.faceSizesArray.size()),
                     // cut mesh
                     reinterpret_cast<const void *>(cutMesh.vertexCoordsArray.data()), cutMesh.faceIndicesArray.data(), cutMesh.faceSizesArray.data(),
                     static_cast<uint32_t>(cutMesh.vertexCoordsArray.size() / 3), static_cast<uint32_t>(cutMesh.faceSizesArray.size()));
    // query the number of available connected component
    uint32_t numConnComps;
    err = mcGetConnectedComponents(context, MC_CONNECTED_COMPONENT_TYPE_FRAGMENT, 0, NULL, &numConnComps);
    std::vector<McConnectedComponent> connectedComponents(numConnComps, MC_NULL_HANDLE);
    err = mcGetConnectedComponents(context, MC_CONNECTED_COMPONENT_TYPE_FRAGMENT, (uint32_t) connectedComponents.size(), connectedComponents.data(), NULL);
    std::vector<TriangleMesh> outs;
    // traversal of all connected components
    for (int n = 0; n < numConnComps; ++n) {
        // query the data of each connected component from MCUT
        McConnectedComponent connComp = connectedComponents[n];
        // query the vertices
        McSize numBytes                   = 0;
        err                               = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, 0, NULL, &numBytes);
        uint32_t            ccVertexCount = (uint32_t) (numBytes / (sizeof(double) * 3));
        std::vector<double> ccVertices((uint64_t) ccVertexCount * 3u, 0);
        err = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, numBytes, (void *) ccVertices.data(), NULL);
        // query the faces
        numBytes = 0;
        err      = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION, 0, NULL, &numBytes);
        std::vector<uint32_t> ccFaceIndices(numBytes / sizeof(uint32_t), 0);
        err = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION, numBytes, ccFaceIndices.data(), NULL);
        std::vector<uint32_t> faceSizes(ccFaceIndices.size() / 3, 3);
        const uint32_t ccFaceCount = static_cast<uint32_t>(faceSizes.size());
        // Here we show, how to know when connected components, pertain particular boolean operations.
        McPatchLocation patchLocation = (McPatchLocation) 0;
        err                           = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_PATCH_LOCATION, sizeof(McPatchLocation), &patchLocation, NULL);
        McFragmentLocation fragmentLocation = (McFragmentLocation) 0;
        err = mcGetConnectedComponentData(context, connComp, MC_CONNECTED_COMPONENT_DATA_FRAGMENT_LOCATION, sizeof(McFragmentLocation), &fragmentLocation, NULL);
        // rearrange vertices/faces and save into result mesh
        std::vector<Vec3f> vertices(ccVertexCount);
        for (uint32_t i = 0; i < ccVertexCount; ++i) {
            vertices[i][0] = (float) ccVertices[(uint64_t) i * 3 + 0];
            vertices[i][1] = (float) ccVertices[(uint64_t) i * 3 + 1];
            vertices[i][2] = (float) ccVertices[(uint64_t) i * 3 + 2];
        }
        // output faces
        int faceVertexOffsetBase = 0;
        // for each face in CC
        std::vector<Vec3i> faces(ccFaceCount);
        for (uint32_t f = 0; f < ccFaceCount; ++f) {
            bool reverseWindingOrder = (fragmentLocation == MC_FRAGMENT_LOCATION_BELOW) && (patchLocation == MC_PATCH_LOCATION_OUTSIDE);
            int  faceSize            = faceSizes.at(f);
            // for each vertex in face
            for (int v = (reverseWindingOrder ? (faceSize - 1) : 0); (reverseWindingOrder ? (v >= 0) : (v < faceSize)); v += (reverseWindingOrder ? -1 : 1)) {
                faces[f][v] = ccFaceIndices[(uint64_t) faceVertexOffsetBase + v];
            }
            faceVertexOffsetBase += faceSize;
        }
        TriangleMesh out(vertices, faces);
        outs.emplace_back(out);
    }
    // free connected component data
    err = mcReleaseConnectedComponents(context, (uint32_t) connectedComponents.size(), connectedComponents.data());
    // destroy context
    err = mcReleaseContext(context);
    return outs;
}
References Slic3r::MeshBoolean::mcut::McutMesh::faceIndicesArray, Slic3r::MeshBoolean::mcut::McutMesh::faceSizesArray, make_boolean(), MC_CONNECTED_COMPONENT_DATA_FACE_TRIANGULATION, MC_CONNECTED_COMPONENT_DATA_FRAGMENT_LOCATION, MC_CONNECTED_COMPONENT_DATA_PATCH_LOCATION, MC_CONNECTED_COMPONENT_DATA_VERTEX_DOUBLE, MC_CONNECTED_COMPONENT_TYPE_FRAGMENT, MC_DEBUG_SEVERITY_MEDIUM, MC_DEBUG_SOURCE_ALL, MC_DEBUG_TYPE_ERROR, MC_DISPATCH_ENFORCE_GENERAL_POSITION, MC_DISPATCH_FILTER_FRAGMENT_LOCATION_ABOVE, MC_DISPATCH_FILTER_FRAGMENT_LOCATION_BELOW, MC_DISPATCH_FILTER_FRAGMENT_SEALING_INSIDE, MC_DISPATCH_FILTER_FRAGMENT_SEALING_OUTSIDE, MC_DISPATCH_VERTEX_ARRAY_DOUBLE, MC_FRAGMENT_LOCATION_BELOW, MC_NULL_HANDLE, MC_PATCH_LOCATION_OUTSIDE, mcCreateContext(), mcDebugMessageCallback(), mcDebugMessageControl(), mcDebugOutput(), mcDispatch(), mcGetConnectedComponentData(), mcGetConnectedComponents(), mcReleaseConnectedComponents(), mcReleaseContext(), n, NULL, out, and Slic3r::MeshBoolean::mcut::McutMesh::vertexCoordsArray.
Referenced by make_boolean(), make_boolean(), Slic3r::ModelObject::make_boolean(), and Slic3r::GUI::GLGizmoMeshBoolean::on_render_input_window().
make_boolean() [2/2]
void Slic3r::MeshBoolean::mcut::make_boolean (const TriangleMesh & src_mesh, const TriangleMesh & cut_mesh, std::vector< TriangleMesh > & dst_mesh, const std::string & boolean_opts)
{
    McutMesh srcMesh, cutMesh;
    triangle_mesh_to_mcut(src_mesh, srcMesh);
    triangle_mesh_to_mcut(cut_mesh, cutMesh);
    //dst_mesh = make_boolean(srcMesh, cutMesh, boolean_opts);
    do_boolean(srcMesh, cutMesh, boolean_opts);
    dst_mesh.push_back(mcut_to_triangle_mesh(srcMesh));
}
References do_boolean(), make_boolean(), mcut_to_triangle_mesh(), and triangle_mesh_to_mcut().
mcDebugOutput()
MCAPI_ATTR void MCAPI_CALL Slic3r::MeshBoolean::mcut::mcDebugOutput (McDebugSource source, McDebugType type, unsigned int id, McDebugSeverity severity, size_t length, const char * message, const void * userParam)
{
    BOOST_LOG_TRIVIAL(debug)<<Slic3r::format("mcut mcDebugOutput message ( %d ): %s ", id, message);
    switch (source) {
        case MC_DEBUG_SOURCE_API:
            BOOST_LOG_TRIVIAL(debug)<<("Source: API");
            break;
        case MC_DEBUG_SOURCE_KERNEL:
            BOOST_LOG_TRIVIAL(debug)<<("Source: Kernel");
            break;
        }
    switch (type) {
        case MC_DEBUG_TYPE_ERROR:
            BOOST_LOG_TRIVIAL(debug)<<("Type: Error");
            break;
        case MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR:
            BOOST_LOG_TRIVIAL(debug)<<("Type: Deprecated Behaviour");
            break;
        case MC_DEBUG_TYPE_OTHER:
            BOOST_LOG_TRIVIAL(debug)<<("Type: Other");
            break;
        }
    switch (severity) {
        case MC_DEBUG_SEVERITY_HIGH:
            BOOST_LOG_TRIVIAL(debug)<<("Severity: high");
            break;
        case MC_DEBUG_SEVERITY_MEDIUM:
            BOOST_LOG_TRIVIAL(debug)<<("Severity: medium");
            break;
        case MC_DEBUG_SEVERITY_LOW:
            BOOST_LOG_TRIVIAL(debug)<<("Severity: low");
            break;
        case MC_DEBUG_SEVERITY_NOTIFICATION:
            BOOST_LOG_TRIVIAL(debug)<<("Severity: notification");
            break;
        }
}
References Slic3r::format(), MC_DEBUG_SEVERITY_HIGH, MC_DEBUG_SEVERITY_LOW, MC_DEBUG_SEVERITY_MEDIUM, MC_DEBUG_SEVERITY_NOTIFICATION, MC_DEBUG_SOURCE_API, MC_DEBUG_SOURCE_KERNEL, MC_DEBUG_TYPE_DEPRECATED_BEHAVIOR, MC_DEBUG_TYPE_ERROR, MC_DEBUG_TYPE_OTHER, and mcDebugOutput().
Referenced by do_boolean(), make_boolean(), and mcDebugOutput().
mcut_to_triangle_mesh()
TriangleMesh Slic3r::MeshBoolean::mcut::mcut_to_triangle_mesh (const McutMesh & mcutmesh)
{
    uint32_t ccVertexCount = mcutmesh.vertexCoordsArray.size() / 3;
    auto    &ccVertices    = mcutmesh.vertexCoordsArray;
    auto    &ccFaceIndices = mcutmesh.faceIndicesArray;
    auto    &faceSizes     = mcutmesh.faceSizesArray;
    uint32_t ccFaceCount   = faceSizes.size();
    // rearrange vertices/faces and save into result mesh
    std::vector<Vec3f> vertices(ccVertexCount);
    for (uint32_t i = 0; i < ccVertexCount; i++) {
        vertices[i][0] = (float) ccVertices[(uint64_t) i * 3 + 0];
        vertices[i][1] = (float) ccVertices[(uint64_t) i * 3 + 1];
        vertices[i][2] = (float) ccVertices[(uint64_t) i * 3 + 2];
    }
    // output faces
    int faceVertexOffsetBase = 0;
    // for each face in CC
    std::vector<Vec3i> faces(ccFaceCount);
    for (uint32_t f = 0; f < ccFaceCount; ++f) {
        int faceSize = faceSizes.at(f);
        // for each vertex in face
        for (int v = 0; v < faceSize; v++) { faces[f][v] = ccFaceIndices[(uint64_t) faceVertexOffsetBase + v]; }
        faceVertexOffsetBase += faceSize;
    }
    TriangleMesh out(vertices, faces);
    return out;
}
References Slic3r::MeshBoolean::mcut::McutMesh::faceIndicesArray, Slic3r::MeshBoolean::mcut::McutMesh::faceSizesArray, mcut_to_triangle_mesh(), out, and Slic3r::MeshBoolean::mcut::McutMesh::vertexCoordsArray.
Referenced by Slic3r::GUI::Plater::combine_mesh_fff(), do_boolean(), make_boolean(), mcut_to_triangle_mesh(), and merge_mcut_meshes().
merge_mcut_meshes()
void Slic3r::MeshBoolean::mcut::merge_mcut_meshes (McutMesh & src, const McutMesh & cut)
{
    indexed_triangle_set all_its;
    TriangleMesh tri_src = mcut_to_triangle_mesh(src);
    TriangleMesh tri_cut = mcut_to_triangle_mesh(cut);
    its_merge(all_its, tri_src.its);
    its_merge(all_its, tri_cut.its);
    src = *triangle_mesh_to_mcut(all_its);
    }
References Slic3r::TriangleMesh::its, Slic3r::its_merge(), mcut_to_triangle_mesh(), merge_mcut_meshes(), and triangle_mesh_to_mcut().
Referenced by do_boolean(), and merge_mcut_meshes().
triangle_mesh_to_mcut() [1/2]
McutMeshPtr Slic3r::MeshBoolean::mcut::triangle_mesh_to_mcut (const indexed_triangle_set & M)
{
    std::unique_ptr<McutMesh, McutMeshDeleter> out(new McutMesh{});
    TriangleMesh                               trimesh(M);
    triangle_mesh_to_mcut(trimesh, *out.get());
    return out;
}
References out, and triangle_mesh_to_mcut().
triangle_mesh_to_mcut() [2/2]
void Slic3r::MeshBoolean::mcut::triangle_mesh_to_mcut (const TriangleMesh & src_mesh, McutMesh & srcMesh, const Transform3d & src_nm = Transform3d::Identity())
{
    // vertices precision convention and copy
    srcMesh.vertexCoordsArray.reserve(src_mesh.its.vertices.size() * 3);
    for (int i = 0; i < src_mesh.its.vertices.size(); ++i) {
        const Vec3d v = src_nm * src_mesh.its.vertices[i].cast<double>();
        srcMesh.vertexCoordsArray.push_back(v[0]);
        srcMesh.vertexCoordsArray.push_back(v[1]);
        srcMesh.vertexCoordsArray.push_back(v[2]);
    }
    // faces copy
    srcMesh.faceIndicesArray.reserve(src_mesh.its.indices.size() * 3);
    srcMesh.faceSizesArray.reserve(src_mesh.its.indices.size());
    for (int i = 0; i < src_mesh.its.indices.size(); ++i) {
        const int &f0 = src_mesh.its.indices[i][0];
        const int &f1 = src_mesh.its.indices[i][1];
        const int &f2 = src_mesh.its.indices[i][2];
        srcMesh.faceIndicesArray.push_back(f0);
        srcMesh.faceIndicesArray.push_back(f1);
        srcMesh.faceIndicesArray.push_back(f2);
        srcMesh.faceSizesArray.push_back((uint32_t) 3);
    }
}
References Slic3r::MeshBoolean::mcut::McutMesh::faceIndicesArray, Slic3r::MeshBoolean::mcut::McutMesh::faceSizesArray, indexed_triangle_set::indices, Slic3r::TriangleMesh::its, triangle_mesh_to_mcut(), Slic3r::MeshBoolean::mcut::McutMesh::vertexCoordsArray, and indexed_triangle_set::vertices.
Referenced by Slic3r::csg::check_csgmesh_booleans(), do_boolean(), Slic3r::csg::get_mcutmesh(), make_boolean(), merge_mcut_meshes(), Slic3r::csg::perform_csgmesh_booleans_mcut(), triangle_mesh_to_mcut(), and triangle_mesh_to_mcut().