OrcaSlicer: Slic3r::GUI::MappingContainer Class Reference
Slic3r::GUI::MappingContainer Class Reference
#include <src/slic3r/GUI/AmsMappingPopup.hpp>
Public Member Functions
MappingContainer (wxWindow *parent)
~MappingContainer ()
void paintEvent (wxPaintEvent &evt)
void render (wxDC &dc)
void doRender (wxDC &dc)
Public Attributes
wxBitmap ams_mapping_item_container
Detailed Description
Constructor & Destructor Documentation
MappingContainer()
Slic3r::GUI::MappingContainer::MappingContainer (wxWindow * parent)
    : wxPanel(parent, wxID_ANY, wxDefaultPosition, wxDefaultSize)
{
#ifdef __WINDOWS__
    SetDoubleBuffered(true);
#endif //__WINDOWS__
    SetBackgroundColour(StateColor::darkModeColorFor(*wxWHITE));
    Bind(wxEVT_PAINT, &MappingContainer::paintEvent, this);
    ams_mapping_item_container = create_scaled_bitmap("ams_mapping_container", this, 78);
    SetMinSize(wxSize(FromDIP(230), FromDIP(78)));
    SetMaxSize(wxSize(FromDIP(230), FromDIP(78)));
}
References ams_mapping_item_container, create_scaled_bitmap(), StateColor::darkModeColorFor(), and paintEvent().
~MappingContainer()
Slic3r::GUI::MappingContainer::~MappingContainer ()
{
}
Member Function Documentation
doRender()
void Slic3r::GUI::MappingContainer::doRender (wxDC & dc)
{
    dc.DrawBitmap(ams_mapping_item_container, 0, 0);
}
References ams_mapping_item_container.
Referenced by render().
paintEvent()
void Slic3r::GUI::MappingContainer::paintEvent (wxPaintEvent & evt)
{
    wxPaintDC dc(this);
    render(dc);
}
References render().
Referenced by MappingContainer().
render()
void Slic3r::GUI::MappingContainer::render (wxDC & dc)
{
#ifdef __WXMSW__
    wxSize     size = GetSize();
    wxMemoryDC memdc;
    wxBitmap   bmp(size.x, size.y);
    memdc.SelectObject(bmp);
    memdc.Blit({ 0, 0 }, size, &dc, { 0, 0 });
    {
        wxGCDC dc2(memdc);
        doRender(dc2);
    }
    memdc.SelectObject(wxNullBitmap);
    dc.DrawBitmap(bmp, 0, 0);
#else
    doRender(dc);
#endif
}
References doRender(), and size.
Referenced by paintEvent().
Member Data Documentation
ams_mapping_item_container
wxBitmap Slic3r::GUI::MappingContainer::ams_mapping_item_container
Referenced by MappingContainer(), and doRender().
The documentation for this class was generated from the following files:
src/slic3r/GUI/AmsMappingPopup.hpp
src/slic3r/GUI/AmsMappingPopup.cpp