OrcaSlicer: Slic3r::FaceDetector Class Reference
Slic3r::FaceDetector Class Reference
#include <src/libslic3r/FaceDetector.hpp>
Public Member Functions
FaceDetector (std::vector< TriangleMesh > &tms, std::vector< Transform3d > &transfos, double sample_interval)
void detect_exterior_face ()
Private Attributes
std::vector< TriangleMesh > & m_meshes
std::vector< Transform3d > & m_transfos
double m_sample_interval
Detailed Description
Constructor & Destructor Documentation
FaceDetector()
Slic3r::FaceDetector::FaceDetector (std::vector< TriangleMesh > & tms, std::vector< Transform3d > & transfos, double sample_interval) inline
    : m_meshes(tms), m_transfos(transfos), m_sample_interval(sample_interval) {}
Member Function Documentation
detect_exterior_face()
void Slic3r::FaceDetector::detect_exterior_face ()
{
    struct MeshFacetRange {
        MeshFacetRange(TriangleMesh* tm, uint32_t facet_begin, uint32_t facet_end) :
            tm(tm), facet_begin(facet_begin), facet_end(facet_end) {}
        MeshFacetRange() : tm(nullptr), facet_begin(0), facet_end(0) {}
        TriangleMesh* tm;
        uint32_t facet_begin;
        uint32_t facet_end;
    };
    TriangleMesh object_mesh;
    std::vector<MeshFacetRange> volume_facet_ranges;
    for (int i = 0; i < m_meshes.size(); i++) {
        TriangleMesh vol_mesh = m_meshes[i];
        volume_facet_ranges.emplace_back(&m_meshes[i], object_mesh.stats().number_of_facets, object_mesh.stats().number_of_facets + vol_mesh.stats().number_of_facets);
        vol_mesh.transform(m_transfos[i]);
        object_mesh.merge(std::move(vol_mesh));
    }
    sla::IndexedMesh indexed_mesh(object_mesh);
    BoundingBoxf3 bbox = object_mesh.bounding_box();
    bbox.offset(BBOX_OFFSET);
    std::unordered_set<size_t> hit_face_indices;
    // x-axis rays
    for (double y = bbox.min.y(); y < bbox.max.y(); y += m_sample_interval) {
        for (double z = bbox.min.z(); z < bbox.max.z(); z += m_sample_interval) {
            auto hit_result = indexed_mesh.query_ray_hit({ bbox.min.x(), y, z }, { 1.0, 0.0, 0.0 });
            if (hit_result.is_hit())
                hit_face_indices.insert(hit_result.face());
            hit_result = indexed_mesh.query_ray_hit({ bbox.max.x(), y, z }, { -1.0, 0.0, 0.0 });
            if (hit_result.is_hit())
                hit_face_indices.insert(hit_result.face());
        }
    }
    // y-axis rays
    for (double x = bbox.min.x(); x < bbox.max.x(); x += m_sample_interval) {
        for (double z = bbox.min.z(); z < bbox.max.z(); z += m_sample_interval) {
            auto hit_result = indexed_mesh.query_ray_hit({ x, bbox.min.y(), z }, { 0.0, 1.0, 0.0 });
            if (hit_result.is_hit())
                hit_face_indices.insert(hit_result.face());
            hit_result = indexed_mesh.query_ray_hit({ x, bbox.max.y(), z }, { 0.0, -1.0, 0.0 });
            if (hit_result.is_hit())
                hit_face_indices.insert(hit_result.face());
        }
    }
    // z-axis rays
    for (double x = bbox.min.x(); x < bbox.max.x(); x += m_sample_interval) {
        for (double y = bbox.min.y(); y < bbox.max.y(); y += m_sample_interval) {
            auto hit_result = indexed_mesh.query_ray_hit({ x, y, bbox.min.z() }, { 0.0, 0.0, 1.0 });
            if (hit_result.is_hit())
                hit_face_indices.insert(hit_result.face());
            hit_result = indexed_mesh.query_ray_hit({ x, y, bbox.max.z() }, { 0.0, 0.0, -1.0 });
            if (hit_result.is_hit())
                hit_face_indices.insert(hit_result.face());
        }
    }
    for (size_t facet_idx : hit_face_indices) {
        TriangleMesh* tm = nullptr;
        uint32_t vol_facet_idx = 0;
        for (auto range : volume_facet_ranges) {
            if (facet_idx >= range.facet_begin && facet_idx < range.facet_end) {
                tm = range.tm;
                vol_facet_idx = facet_idx - range.facet_begin;
                break;
            }
        }
        tm->its.get_property(vol_facet_idx).type = EnumFaceTypes::eExteriorAppearance;
    }
}
References Slic3r::BBOX_OFFSET, Slic3r::TriangleMesh::bounding_box(), eExteriorAppearance, indexed_triangle_set::get_property(), Slic3r::TriangleMesh::its, m_meshes, m_sample_interval, m_transfos, Slic3r::BoundingBoxBase< PointClass >::max, Slic3r::TriangleMesh::merge(), Slic3r::BoundingBoxBase< PointClass >::min, Slic3r::TriangleMeshStats::number_of_facets, Slic3r::BoundingBox3Base< PointClass >::offset(), Slic3r::sla::IndexedMesh::query_ray_hit(), Slic3r::range(), Slic3r::TriangleMesh::stats(), Slic3r::TriangleMesh::transform(), and FaceProperty::type.
Referenced by Slic3r::ModelObject::split().
Member Data Documentation
m_meshes
std::vector<TriangleMesh>& Slic3r::FaceDetector::m_meshes private
Referenced by detect_exterior_face().
m_sample_interval
double Slic3r::FaceDetector::m_sample_interval private
Referenced by detect_exterior_face().
m_transfos
std::vector<Transform3d>& Slic3r::FaceDetector::m_transfos private
Referenced by detect_exterior_face().
The documentation for this class was generated from the following files:
src/libslic3r/FaceDetector.hpp
src/libslic3r/FaceDetector.cpp