OrcaSlicer: Slic3r::GUI::AddMachinePanel Class Reference
Slic3r::GUI::AddMachinePanel Class Reference
#include <src/slic3r/GUI/Monitor.hpp>
Public Member Functions
AddMachinePanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL, const wxString &name=wxEmptyString)
~AddMachinePanel ()
void msw_rescale ()
Protected Member Functions
void on_add_machine (wxCommandEvent &event)
Protected Attributes
Button * m_button_add_machine
wxStaticText * m_staticText_add_machine
wxStaticBitmap * m_bitmap_empty
Detailed Description
Constructor & Destructor Documentation
AddMachinePanel()
Slic3r::GUI::AddMachinePanel::AddMachinePanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL, const wxString & name = wxEmptyString)
    : wxPanel(parent, id, pos, size, style)
{
    this->SetBackgroundColour(0xEEEEEE);
    wxBoxSizer* topsizer = new wxBoxSizer(wxVERTICAL);
    topsizer->AddStretchSpacer();
    m_bitmap_empty = new wxStaticBitmap(this, wxID_ANY, wxNullBitmap, wxDefaultPosition, wxDefaultSize, 0);
    m_bitmap_empty->SetBitmap(create_scaled_bitmap("monitor_status_empty", nullptr, 250));
    topsizer->Add(m_bitmap_empty, 0, wxALL | wxALIGN_CENTER_HORIZONTAL, 0);
    topsizer->AddSpacer(46);
    wxBoxSizer* horiz_sizer = new wxBoxSizer(wxHORIZONTAL);
    horiz_sizer->Add(0, 0, 538, 0, 0);
    wxBoxSizer* btn_sizer = new wxBoxSizer(wxVERTICAL);
    m_button_add_machine = new Button(this, "", "monitor_add_machine", FromDIP(24));
    m_button_add_machine->SetCornerRadius(FromDIP(12));
    StateColor button_bg(
        std::pair<wxColour, int>(0xCECECE, StateColor::Pressed),
        std::pair<wxColour, int>(0xCECECE, StateColor::Hovered),
        std::pair<wxColour, int>(this->GetBackgroundColour(), StateColor::Normal)
    );
    m_button_add_machine->SetBackgroundColor(button_bg);
    m_button_add_machine->SetBorderColor(0x909090);
    m_button_add_machine->SetMinSize(wxSize(96, 39));
    btn_sizer->Add(m_button_add_machine, 0, wxALL | wxALIGN_CENTER_HORIZONTAL, 5);
    m_staticText_add_machine = new wxStaticText(this, wxID_ANY, wxT("click to add machine"), wxDefaultPosition, wxDefaultSize, 0);
    m_staticText_add_machine->Wrap(-1);
    m_staticText_add_machine->SetForegroundColour(0x909090);
    btn_sizer->Add(m_staticText_add_machine, 0, wxALL | wxALIGN_CENTER_HORIZONTAL, 5);
    horiz_sizer->Add(btn_sizer);
    horiz_sizer->Add(0, 0, 624, 0, 0);
    topsizer->Add(horiz_sizer, 0, wxEXPAND, 0);
    topsizer->AddStretchSpacer();
    this->SetSizer(topsizer);
    this->Layout();
    // Connect Events
    m_button_add_machine->Connect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AddMachinePanel::on_add_machine), NULL, this);
}
References create_scaled_bitmap(), StateColor::Hovered, m_bitmap_empty, m_button_add_machine, m_staticText_add_machine, StateColor::Normal, NULL, on_add_machine(), StateColor::Pressed, StaticBox::SetBackgroundColor(), StaticBox::SetBorderColor(), StaticBox::SetCornerRadius(), Button::SetMinSize(), and wxStaticText.
~AddMachinePanel()
Slic3r::GUI::AddMachinePanel::~AddMachinePanel ()
{
    m_button_add_machine->Disconnect(wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(AddMachinePanel::on_add_machine), NULL, this);
}
References m_button_add_machine, NULL, and on_add_machine().
Member Function Documentation
msw_rescale()
void Slic3r::GUI::AddMachinePanel::msw_rescale ()
{
}
on_add_machine()
void Slic3r::GUI::AddMachinePanel::on_add_machine (wxCommandEvent & event) protected
{
    // load a url
}
Referenced by AddMachinePanel(), and ~AddMachinePanel().
Member Data Documentation
m_bitmap_empty
wxStaticBitmap* Slic3r::GUI::AddMachinePanel::m_bitmap_empty protected
Referenced by AddMachinePanel().
m_button_add_machine
Button* Slic3r::GUI::AddMachinePanel::m_button_add_machine protected
Referenced by AddMachinePanel(), and ~AddMachinePanel().
m_staticText_add_machine
wxStaticText* Slic3r::GUI::AddMachinePanel::m_staticText_add_machine protected
Referenced by AddMachinePanel().
The documentation for this class was generated from the following files:
src/slic3r/GUI/Monitor.hpp
src/slic3r/GUI/Monitor.cpp