OrcaSlicer: Slic3r::arrangement::AutoArranger< TBin > Class Template Reference
Slic3r::arrangement::AutoArranger< TBin > Class Template Reference
Public Types
using Placer = typename placers::_NofitPolyPlacer< ExPolygon, TBin >
using Selector = selections::_FirstFitSelection< ExPolygon >
using Packer = _Nester< Placer, Selector >
using PConfig = typename Packer::PlacementConfig
using Distance = TCoord< PointImpl >
Public Member Functions
AutoArranger (const TBin &bin, const ArrangeParams &params, std::function< void(unsigned, std::string)> progressind, std::function< bool(void)> stopcond)
template<class It >
void operator() (It from, It to)
PConfig & config ()
const PConfig & config () const
void preload (std::vector< Item > &fixeditems)
Public Attributes
std::vector< Item > m_excluded_items_in_each_plate
Protected Member Functions
template<class T >
ArithmeticOnly< T, double > norm (T val)
double dist_for_BOTTOM_LEFT (Box ibb, const ClipperLib::IntPoint &origin_pack)
std::tuple< double, Box > objfunc (const Item &item, const ClipperLib::IntPoint &origin_pack)
std::function< double(const Item &, const ItemGroup &)> get_objfn ()
std::function< double(const Item &, const ItemGroup &)> get_objfn ()
std::function< double(const Item &, const ItemGroup &)> get_objfn ()
std::function< double(const Item &, const ItemGroup &)> get_objfn ()
Protected Attributes
Packer m_pck
PConfig m_pconf
TBin m_bin
double m_bin_area
SpatIndex m_rtree
SpatIndex m_smallsrtree
double m_norm
MultiPolygon m_merged_pile
Box m_pilebb
ItemGroup m_remaining
ItemGroup m_items
std::vector< Box > m_excluded_and_extruCali_regions
size_t m_item_count = 0
ArrangeParams params
Detailed Description
template<class TBin>
class Slic3r::arrangement::AutoArranger< TBin >
Member Typedef Documentation
Distance
template<class TBin > using Slic3r::arrangement::AutoArranger< TBin >::Distance = TCoord<PointImpl>
Packer
template<class TBin > using Slic3r::arrangement::AutoArranger< TBin >::Packer = _Nester<Placer, Selector>
PConfig
template<class TBin > using Slic3r::arrangement::AutoArranger< TBin >::PConfig = typename Packer::PlacementConfig
Placer
template<class TBin > using Slic3r::arrangement::AutoArranger< TBin >::Placer = typename placers::_NofitPolyPlacer<ExPolygon, TBin>
Selector
template<class TBin > using Slic3r::arrangement::AutoArranger< TBin >::Selector = selections::_FirstFitSelection<ExPolygon>
Constructor & Destructor Documentation
AutoArranger()
template<class TBin > Slic3r::arrangement::AutoArranger< TBin >::AutoArranger (const TBin & bin, const ArrangeParams & params, std::function< void(unsigned, std::string)> progressind, std::function< bool(void)> stopcond) inline
        : m_pck(bin, params.min_obj_distance)
        , m_bin(bin)
    {
        m_bin_area = abs(sl::area(bin));  // due to clockwise or anti-clockwise, the result of sl::area may be negative
        m_norm = std::sqrt(m_bin_area);
        fill_config(m_pconf, params);
        this->params = params;
        for (auto& region : m_pconf.m_excluded_regions) {
            Box  bb = region.boundingBox();
            m_excluded_and_extruCali_regions.emplace_back(bb);
        }
        for (auto& region : m_pconf.m_nonprefered_regions) {
            Box  bb = region.boundingBox();
            m_excluded_and_extruCali_regions.emplace_back(bb);
        }
        // Set up a callback that is called just before arranging starts
        // This functionality is provided by the Nester class (m_pack).
        m_pconf.before_packing =
        [this](const MultiPolygon& merged_pile,            // merged pile
               const ItemGroup& items,             // packed items
               const ItemGroup& remaining)         // future items to be packed
        {
            m_items = items;
            m_merged_pile = merged_pile;
            m_remaining = remaining;
            m_pilebb.defined = false;
            if (!merged_pile.empty())
            {
                m_pilebb = sl::boundingBox(merged_pile);
                m_pilebb.defined = true;
            }
            m_rtree.clear();
            m_smallsrtree.clear();
            // We will treat big items (compared to the print bed) differently
            auto isBig = [this](double a) {
                return a / m_bin_area > BIG_ITEM_TRESHOLD ;
            };
            for(unsigned idx = 0; idx < items.size(); ++idx) {
                Item& itm = items[idx];
                if (itm.is_virt_object) continue;
                if(isBig(itm.area())) m_rtree.insert({itm.boundingBox(), idx});
                m_smallsrtree.insert({itm.boundingBox(), idx});
            }
        };
        m_pconf.object_function = get_objfn();
        // preload fixed items (and excluded regions) on plate
        m_pconf.on_preload = [this](const ItemGroup &items, PConfig &cfg) {
            if (items.empty()) return;
            auto binbb = sl::boundingBox(m_bin);
            auto starting_point = cfg.starting_point == PConfig::Alignment::BOTTOM_LEFT ? binbb.minCorner() : binbb.center();
            // if we have wipe tower, items should be arranged around wipe tower
            for (Item itm : items) {
                if (itm.is_wipe_tower) {
                    starting_point = itm.boundingBox().center();
                    break;
                }
            }
            cfg.object_function = [this, binbb, starting_point](const Item &item, const ItemGroup &packed_items) {
                return fixed_overfit(objfunc(item, starting_point), binbb);
            };
        };
        auto on_packed = params.on_packed;
        if (progressind || on_packed)
            m_pck.progressIndicator(
                [this, progressind, on_packed](unsigned num_finished) {
                    int last_bed = m_pck.lastPackedBinId();
                    if (last_bed >= 0) {
                        Item& last_packed = m_pck.lastResult()[last_bed].back();
                        ArrangePolygon ap;
                        ap.bed_idx = last_packed.binId();
                        ap.priority = last_packed.priority();
                        if (progressind) progressind(num_finished, last_packed.name);
                        if (on_packed)
                            on_packed(ap);
                        BOOST_LOG_TRIVIAL(debug) << "arrange " + last_packed.name + " succeed!"
                            << ", plate id=" << ap.bed_idx;
                    }
                });
        if (progressind) {
            m_pck.unfitIndicator([this, progressind](std::string name) {
                BOOST_LOG_TRIVIAL(debug) << "arrange not fit: " + name;
                });
        }
        if (stopcond) m_pck.stopCondition(stopcond);
        m_pconf.sortfunc= [&params](Item& i1, Item& i2) {
            int p1 = i1.priority(), p2 = i2.priority();
            if (p1 != p2)
                return p1 > p2;
            if (params.is_seq_print) {
                return i1.bed_temp != i2.bed_temp ? (i1.bed_temp > i2.bed_temp) :
                        (i1.height != i2.height ? (i1.height < i2.height) : (i1.area() > i2.area()));
            }
            else {
                return i1.bed_temp != i2.bed_temp ? (i1.bed_temp > i2.bed_temp) :
                    (i1.extrude_ids != i2.extrude_ids ? (i1.extrude_ids.front() < i2.extrude_ids.front()) : (i1.area() > i2.area()));
            }
        };
        m_pck.configure(m_pconf);
    }
References libnest2d::_Item< RawShape >::area(), libnest2d::shapelike::area(), Slic3r::arrangement::BIG_ITEM_TRESHOLD, libnest2d::_Item< RawShape >::boundingBox(), libnest2d::shapelike::boundingBox(), libnest2d::_Box< P >::defined, Slic3r::arrangement::fill_config(), libnest2d::_Item< RawShape >::is_virt_object, Slic3r::arrangement::AutoArranger< TBin >::m_bin_area, Slic3r::arrangement::AutoArranger< TBin >::m_excluded_and_extruCali_regions, Slic3r::arrangement::AutoArranger< TBin >::m_items, Slic3r::arrangement::AutoArranger< TBin >::m_merged_pile, Slic3r::arrangement::AutoArranger< TBin >::m_norm, Slic3r::arrangement::AutoArranger< TBin >::m_pconf, Slic3r::arrangement::AutoArranger< TBin >::m_pilebb, Slic3r::arrangement::AutoArranger< TBin >::m_remaining, Slic3r::arrangement::AutoArranger< TBin >::m_rtree, Slic3r::arrangement::AutoArranger< TBin >::m_smallsrtree, and Slic3r::arrangement::AutoArranger< TBin >::params.
Member Function Documentation
config() [1/2]
template<class TBin > PConfig & Slic3r::arrangement::AutoArranger< TBin >::config () inline
{ return m_pconf; }
config() [2/2]
template<class TBin > const PConfig & Slic3r::arrangement::AutoArranger< TBin >::config () const inline
{ return m_pconf; }
dist_for_BOTTOM_LEFT()
template<class TBin > double Slic3r::arrangement::AutoArranger< TBin >::dist_for_BOTTOM_LEFT (Box ibb, const ClipperLib::IntPoint & origin_pack) inline protected
    {
        double dist_corner_y = ibb.minCorner().y() - origin_pack.y();
        double dist_corner_x = ibb.minCorner().x() - origin_pack.x();
        // occupy as few rows as possible if we have rotations
        double bindist       = double(ibb.maxCorner().y() - ibb.minCorner().y());
        if (dist_corner_x >= 0 && dist_corner_y >= 0)
            bindist += dist_corner_y + 1 * dist_corner_x;
        else {
            if (dist_corner_x < 0) bindist += 10 * (-dist_corner_x);
            if (dist_corner_y < 0) bindist += 10 * (-dist_corner_y);
            }
        bindist = norm(bindist);
        return bindist;
    }
References libnest2d::_Box< P >::maxCorner(), libnest2d::_Box< P >::minCorner(), and Slic3r::arrangement::AutoArranger< TBin >::norm().
Referenced by Slic3r::arrangement::AutoArranger< TBin >::objfunc().
get_objfn() [1/4]
template<class TBin > std::function< double(const Item &, const ItemGroup &)> Slic3r::arrangement::AutoArranger< TBin >::get_objfn () protected
get_objfn() [2/4]
std::function< double(const Item &, const ItemGroup &)> Slic3r::arrangement::AutoArranger< Box >::get_objfn () protected
{
    auto origin_pack = m_pconf.starting_point == PConfig::Alignment::CENTER ? m_bin.center() : m_bin.minCorner();
    return [this, origin_pack](const Item &itm, const ItemGroup&) {
        auto result = objfunc(itm, origin_pack);
        double score = std::get<0>(result);
        auto& fullbb = std::get<1>(result);
        //if (m_pconf.starting_point == PConfig::Alignment::BOTTOM_LEFT)
        //{
        //    if (!sl::isInside(fullbb, m_bin))
        //        score += LARGE_COST_TO_REJECT;
        //}
        //else
        {
            double miss = Placer::overfit(fullbb, m_bin);
            miss = miss > 0 ? miss : 0;
            score += miss * miss;
            if (score > LARGE_COST_TO_REJECT)
                score = 1.5 * LARGE_COST_TO_REJECT;
        }
        return score;
    };
}
References LARGE_COST_TO_REJECT.
get_objfn() [3/4]
std::function< double(const Item &, const ItemGroup &)> Slic3r::arrangement::AutoArranger< Circle >::get_objfn () protected
{
    auto bb = sl::boundingBox(m_bin);
    auto origin_pack = m_pconf.starting_point == PConfig::Alignment::CENTER ? bb.center() : bb.minCorner();
    return [this, origin_pack](const Item &item, const ItemGroup&) {
        auto result = objfunc(item, origin_pack);
        double score = std::get<0>(result);
        auto isBig = [this](const Item& itm) {
            return itm.area() / m_bin_area > BIG_ITEM_TRESHOLD ;
        };
        if(isBig(item)) {
            auto mp = m_merged_pile;
            mp.push_back(item.transformedShape());
            auto chull = sl::convexHull(mp);
            double miss = Placer::overfit(chull, m_bin);
            if(miss < 0) miss = 0;
            score += miss*miss;
        }
        return score;
    };
}
References Slic3r::arrangement::BIG_ITEM_TRESHOLD, and libnest2d::_Item< RawShape >::transformedShape().
get_objfn() [4/4]
std::function< double(const Item &, const ItemGroup &)> Slic3r::arrangement::AutoArranger< ExPolygon >::get_objfn () protected
{
    auto bb = sl::boundingBox(m_bin);
    auto origin_pack = m_pconf.starting_point == PConfig::Alignment::CENTER ? bb.center() : bb.minCorner();
    return [this, origin_pack](const Item &itm, const ItemGroup&) {
        auto result = objfunc(itm, origin_pack);
        double score = std::get<0>(result);
        auto mp = m_merged_pile;
        mp.emplace_back(itm.transformedShape());
        auto chull = sl::convexHull(mp);
        if (m_pconf.starting_point == PConfig::Alignment::BOTTOM_LEFT)
        {
            if (!sl::isInside(chull, m_bin))
                score += LARGE_COST_TO_REJECT;
        }
        else
        {
            double miss = Placer::overfit(chull, m_bin);
            miss = miss > 0 ? miss : 0;
            score += miss * miss;
        }
        return score;
    };
}
References LARGE_COST_TO_REJECT, and libnest2d::_Item< RawShape >::transformedShape().
norm()
template<class TBin > template<class T > ArithmeticOnly< T, double > Slic3r::arrangement::AutoArranger< TBin >::norm (T val) inline protected
    {
        return double(val) / m_norm;
    }
References Slic3r::arrangement::AutoArranger< TBin >::m_norm.
Referenced by Slic3r::arrangement::AutoArranger< TBin >::dist_for_BOTTOM_LEFT(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
objfunc()
template<class TBin > std::tuple< double, Box > Slic3r::arrangement::AutoArranger< TBin >::objfunc (const Item & item, const ClipperLib::IntPoint & origin_pack) inline protected
    {
        const double bin_area = m_bin_area;
        const SpatIndex& spatindex = m_rtree;
        const SpatIndex& smalls_spatindex = m_smallsrtree;
        // We will treat big items (compared to the print bed) differently
        auto isBig = [bin_area](double a) {
            return a/bin_area > BIG_ITEM_TRESHOLD ;
        };
        // Candidate item bounding box
        auto ibb = item.boundingBox();
        // Calculate the full bounding box of the pile with the candidate item
        auto fullbb = sl::boundingBox(m_pilebb, ibb);
        // The bounding box of the big items (they will accumulate in the center
        // of the pile
        Box bigbb;
        if(spatindex.empty()) bigbb = fullbb;
        else {
            auto boostbb = spatindex.bounds();
            boost::geometry::convert(boostbb, bigbb);
        }
        // Will hold the resulting score
        double score = 0;
        // Density is the pack density: how big is the arranged pile
        double density = 0;
        // Distinction of cases for the arrangement scene
        enum e_cases {
            // This branch is for big items in a mixed (big and small) scene
            // OR for all items in a small-only scene.
            BIG_ITEM,
            // This branch is for the last big item in a mixed scene
            LAST_BIG_ITEM,
            // For small items in a mixed scene.
            SMALL_ITEM
        } compute_case;
        bool bigitems = isBig(item.area()) || spatindex.empty();
        if(!params.is_seq_print && bigitems && !m_remaining.empty()) compute_case = BIG_ITEM;  // do not use so complicated logic for sequential printing
        else if (bigitems && m_remaining.empty()) compute_case = LAST_BIG_ITEM;
        else compute_case = SMALL_ITEM;
        switch (compute_case) {
        case BIG_ITEM: {
            const Point& minc = ibb.minCorner(); // bottom left corner
            const Point& maxc = ibb.maxCorner(); // top right corner
            // top left and bottom right corners
            Point top_left{getX(minc), getY(maxc)};
            Point bottom_right{getX(maxc), getY(minc)};
            // Now the distance of the gravity center will be calculated to the
            // five anchor points and the smallest will be chosen.
            std::array<double, 5> dists;
            auto cc = fullbb.center(); // The gravity center
            dists[0] = pl::distance(minc, cc);
            dists[1] = pl::distance(maxc, cc);
            dists[2] = pl::distance(ibb.center(), cc);
            dists[3] = pl::distance(top_left, cc);
            dists[4] = pl::distance(bottom_right, cc);
            // The smalles distance from the arranged pile center:
            double dist = norm(*(std::min_element(dists.begin(), dists.end())));
            if (m_pconf.starting_point == PConfig::Alignment::BOTTOM_LEFT) {
                double bindist = dist_for_BOTTOM_LEFT(ibb, origin_pack);
                score = 0.2 * dist + 0.8 * bindist;
            }
            else {
                double bindist = norm(pl::distance(ibb.center(), origin_pack));
                dist = 0.8 * dist + 0.2 * bindist;
                // Prepare a variable for the alignment score.
                // This will indicate: how well is the candidate item
                // aligned with its neighbors. We will check the alignment
                // with all neighbors and return the score for the best
                // alignment. So it is enough for the candidate to be
                // aligned with only one item.
                auto alignment_score = 1.0;
                auto query = bgi::intersects(ibb);
                auto& index = isBig(item.area()) ? spatindex : smalls_spatindex;
                // Query the spatial index for the neighbors
                std::vector<SpatElement> result;
                result.reserve(index.size());
                index.query(query, std::back_inserter(result));
                // now get the score for the best alignment
                for (auto& e : result) {
                    auto idx = e.second;
                    Item& p = m_items[idx];
                    auto parea = p.area();
                    if (std::abs(1.0 - parea / item.area()) < 1e-6) {
                        auto bb = sl::boundingBox(p.boundingBox(), ibb);
                        auto bbarea = bb.area();
                        auto ascore = 1.0 - (item.area() + parea) / bbarea;
                        if (ascore < alignment_score) alignment_score = ascore;
                        }
                    }
                density = std::sqrt(norm(fullbb.width()) * norm(fullbb.height()));
                double R = double(m_remaining.size()) / m_item_count;
                // The final mix of the score is the balance between the
                // distance from the full pile center, the pack density and
                // the alignment with the neighbors
                if (result.empty())
                    score = 0.50 * dist + 0.50 * density;
                else
                    // Let the density matter more when fewer objects remain
                    score = 0.50 * dist + (1.0 - R) * 0.20 * density +
                    0.30 * alignment_score;
            }
            break;
        }
        case LAST_BIG_ITEM: {
            if (m_pconf.starting_point == PConfig::Alignment::BOTTOM_LEFT) {
                score = dist_for_BOTTOM_LEFT(ibb, origin_pack);
            }
            else {
                if (m_pilebb.defined)
                    score = 0.5 * norm(pl::distance(ibb.center(), m_pilebb.center()));
                else
                    score = 0.5 * norm(pl::distance(ibb.center(), origin_pack));
            }
            break;
        }
        case SMALL_ITEM: {
            // Here there are the small items that should be placed around the
            // already processed bigger items.
            // No need to play around with the anchor points, the center will be
            // just fine for small items
            if (m_pconf.starting_point == PConfig::Alignment::BOTTOM_LEFT)
                score = dist_for_BOTTOM_LEFT(ibb, origin_pack);
            else {
                // Align mainly around existing items
                score = 0.8 * norm(pl::distance(ibb.center(), bigbb.center()))+ 0.2*norm(pl::distance(ibb.center(), origin_pack));
                // Align to 135 degree line {calc distance to the line x+y-(xc+yc)=0}
                //auto ic = ibb.center(), bigbbc = origin_pack;// bigbb.center();
                //score = norm(std::abs(ic.x() + ic.y() - bigbbc.x() - bigbbc.y()));
            }
            break;
        }
        }
        if (params.is_seq_print) {
            double clearance_height_to_lid = params.clearance_height_to_lid;
            double clearance_height_to_rod = params.clearance_height_to_rod;
            bool hasRowHeightConflict = false;
            bool hasLidHeightConflict = false;
            auto iy1 = item.boundingBox().minCorner().y();
            auto iy2 = item.boundingBox().maxCorner().y();
            auto ix1 = item.boundingBox().minCorner().x();
            for (int i = 0; i < m_items.size(); i++) {
                Item& p = m_items[i];
                if (p.is_virt_object) continue;
                auto px1 = p.boundingBox().minCorner().x();
                auto py1 = p.boundingBox().minCorner().y();
                auto py2 = p.boundingBox().maxCorner().y();
                auto inter_min = std::max(iy1, py1); // min y of intersection
                auto inter_max = std::min(iy2, py2); // max y of intersection. length=max_y-min_y>0 means intersection exists
                // if this item is lower than existing ones, this item will be printed first, so should not exceed height_to_rod
                if (iy2 < py1) { hasRowHeightConflict |= (item.height > clearance_height_to_rod); }
                else if (inter_max - inter_min > 0) {
                    // if they inter, the one on the left will be printed first
                    double h = ix1 < px1 ? item.height : p.height;
                    hasRowHeightConflict |= (h > clearance_height_to_rod);
                }
                // only last item can be heigher than clearance_height_to_lid, so if the existing items are higher than clearance_height_to_lid, there is height conflict
                hasLidHeightConflict |= (p.height > clearance_height_to_lid);
            }
            double lambda3 = LARGE_COST_TO_REJECT*1.1;
            double lambda4 = LARGE_COST_TO_REJECT*1.2;
            for (int i = 0; i < m_items.size(); i++) {
                Item& p = m_items[i];
                if (p.is_virt_object) continue;
                score += lambda3 * (item.bed_temp - p.vitrify_temp > VITRIFY_TEMP_DIFF_THRSH);
            }
            score += lambda3 * (item.bed_temp - item.vitrify_temp > VITRIFY_TEMP_DIFF_THRSH);
            score += lambda4 * hasRowHeightConflict + lambda4 * hasLidHeightConflict;
        }
        else {
            for (int i = 0; i < m_items.size(); i++) {
                Item& p = m_items[i];
                if (p.is_virt_object) {
                    // Better not put items above wipe tower
                    if (p.is_wipe_tower) {
                        if (ibb.maxCorner().y() > p.boundingBox().maxCorner().y())
                            score += 1;
                        else if(m_pilebb.defined)
                            score += norm(pl::distance(ibb.center(), m_pilebb.center()));
                    }
                    else
                        continue;
                } else {
                    //
                    score += (1- std::abs(item.height - p.height) / params.printable_height)
                        * norm(pl::distance(ibb.center(), p.boundingBox().center()));
                    score += LARGE_COST_TO_REJECT * (item.bed_temp - p.bed_temp != 0);
                }
            }
        }
        std::set<int> extruder_ids;
        for (int i = 0; i < m_items.size(); i++) {
            Item& p = m_items[i];
            if (p.is_virt_object) continue;
            extruder_ids.insert(p.extrude_ids.begin(),p.extrude_ids.end());
        }
        // add a large cost if not multi materials on same plate is not allowed
        if (!params.allow_multi_materials_on_same_plate) {
            // it's the first object, which can be multi-color
            bool first_object                 = extruder_ids.empty();
            // the two objects (previously packed items and the current item) are considered having same color if either one's colors are a subset of the other
            std::set<int> item_extruder_ids(item.extrude_ids.begin(), item.extrude_ids.end());
            bool same_color_with_previous_items = std::includes(item_extruder_ids.begin(), item_extruder_ids.end(), extruder_ids.begin(), extruder_ids.end())
                || std::includes(extruder_ids.begin(), extruder_ids.end(), item_extruder_ids.begin(), item_extruder_ids.end());
            if (!(first_object || same_color_with_previous_items)) score += LARGE_COST_TO_REJECT * 1.3;
        }
        // for layered printing, we want extruder change as few as possible
        // this has very weak effect, CAN NOT use a large weight
        extruder_ids.insert(item.extrude_ids.begin(), item.extrude_ids.end());
        if (!params.is_seq_print) {
            score += 1 * std::max(0, ((int) extruder_ids.size() - 1));
        }
        return std::make_tuple(score, fullbb);
    }
References Slic3r::arrangement::ArrangeParams::allow_multi_materials_on_same_plate, libnest2d::_Item< RawShape >::area(), libnest2d::_Item< RawShape >::bed_temp, Slic3r::arrangement::BIG_ITEM_TRESHOLD, libnest2d::_Item< RawShape >::boundingBox(), libnest2d::shapelike::boundingBox(), libnest2d::_Box< P >::center(), Slic3r::arrangement::ArrangeParams::clearance_height_to_lid, Slic3r::arrangement::ArrangeParams::clearance_height_to_rod, libnest2d::_Box< P >::defined, Slic3r::arrangement::AutoArranger< TBin >::dist_for_BOTTOM_LEFT(), libnest2d::pointlike::distance(), libnest2d::_Item< RawShape >::extrude_ids, libnest2d::getX(), libnest2d::getY(), libnest2d::_Item< RawShape >::height, Slic3r::arrangement::ArrangeParams::is_seq_print, libnest2d::_Item< RawShape >::is_virt_object, libnest2d::_Item< RawShape >::is_wipe_tower, LARGE_COST_TO_REJECT, Slic3r::arrangement::AutoArranger< TBin >::m_bin_area, Slic3r::arrangement::AutoArranger< TBin >::m_item_count, Slic3r::arrangement::AutoArranger< TBin >::m_items, Slic3r::arrangement::AutoArranger< TBin >::m_pconf, Slic3r::arrangement::AutoArranger< TBin >::m_pilebb, Slic3r::arrangement::AutoArranger< TBin >::m_remaining, Slic3r::arrangement::AutoArranger< TBin >::m_rtree, Slic3r::arrangement::AutoArranger< TBin >::m_smallsrtree, libnest2d::_Box< P >::maxCorner(), libnest2d::_Box< P >::minCorner(), Slic3r::arrangement::AutoArranger< TBin >::norm(), Slic3r::arrangement::AutoArranger< TBin >::params, Slic3r::arrangement::ArrangeParams::printable_height, libnest2d::_Item< RawShape >::vitrify_temp, and VITRIFY_TEMP_DIFF_THRSH.
operator()()
template<class TBin > template<class It > void Slic3r::arrangement::AutoArranger< TBin >::operator() (It from, It to) inline
{
        m_rtree.clear();
        m_item_count += size_t(to - from);
        m_pck.execute(from, to);
        m_item_count = 0;
    }
References libnest2d::_Nester< PlacementStrategy, SelectionStrategy >::execute().
preload()
template<class TBin > void Slic3r::arrangement::AutoArranger< TBin >::preload (std::vector< Item > & fixeditems) inline
{
        for(unsigned idx = 0; idx < fixeditems.size(); ++idx) {
            Item& itm = fixeditems[idx];
            itm.markAsFixedInBin(itm.binId());
        }
        m_item_count += fixeditems.size();
    }
References libnest2d::_Item< RawShape >::binId(), and libnest2d::_Item< RawShape >::markAsFixedInBin().
Member Data Documentation
m_bin
template<class TBin > TBin Slic3r::arrangement::AutoArranger< TBin >::m_bin protected
m_bin_area
template<class TBin > double Slic3r::arrangement::AutoArranger< TBin >::m_bin_area protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
m_excluded_and_extruCali_regions
template<class TBin > std::vector<Box> Slic3r::arrangement::AutoArranger< TBin >::m_excluded_and_extruCali_regions protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger().
m_excluded_items_in_each_plate
template<class TBin > std::vector<Item> Slic3r::arrangement::AutoArranger< TBin >::m_excluded_items_in_each_plate
m_item_count
template<class TBin > size_t Slic3r::arrangement::AutoArranger< TBin >::m_item_count = 0 protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::objfunc().
m_items
template<class TBin > ItemGroup Slic3r::arrangement::AutoArranger< TBin >::m_items protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
m_merged_pile
template<class TBin > MultiPolygon Slic3r::arrangement::AutoArranger< TBin >::m_merged_pile protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger().
m_norm
template<class TBin > double Slic3r::arrangement::AutoArranger< TBin >::m_norm protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::norm().
m_pck
template<class TBin > Packer Slic3r::arrangement::AutoArranger< TBin >::m_pck protected
m_pconf
template<class TBin > PConfig Slic3r::arrangement::AutoArranger< TBin >::m_pconf protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
m_pilebb
template<class TBin > Box Slic3r::arrangement::AutoArranger< TBin >::m_pilebb protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
m_remaining
template<class TBin > ItemGroup Slic3r::arrangement::AutoArranger< TBin >::m_remaining protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
m_rtree
template<class TBin > SpatIndex Slic3r::arrangement::AutoArranger< TBin >::m_rtree protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
m_smallsrtree
template<class TBin > SpatIndex Slic3r::arrangement::AutoArranger< TBin >::m_smallsrtree protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
params
template<class TBin > ArrangeParams Slic3r::arrangement::AutoArranger< TBin >::params protected
Referenced by Slic3r::arrangement::AutoArranger< TBin >::AutoArranger(), and Slic3r::arrangement::AutoArranger< TBin >::objfunc().
The documentation for this class was generated from the following file:
src/libslic3r/Arrange.cpp