OrcaSlicer: orgQhull Namespace Reference
orgQhull Namespace Reference
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Classes
class AbsoluteSumOf
Absolute sum of the elements in a container.
class Coordinates
class Coordinates_test
class CoordinatesIterator
class MutableCoordinatesIterator
class PointCoordinates
class PointCoordinates_test
class PointCoordinatesIterator
class Qhull
Interface to Qhull from C++.
class Qhull_test
Test C++ interface to Qhull See eg/q_test for tests of Qhull commands.
class QhullError
class QhullFacet
A QhullFacet is the C++ equivalent to Qhull's facetT*.
class QhullFacet_test
class QhullFacetList
class QhullFacetList_test
class QhullFacetSet
class QhullFacetSet_test
class QhullHyperplane
class QhullHyperplane_test
class QhullLinkedList
class QhullLinkedList_test
class QhullLinkedListIterator
class QhullPoint
A QhullPoint is a dimension and an array of coordinates. With Qhull/QhullQh, a QhullPoint has an identifier. Point equality is relative to qh.distanceEpsilon.
class QhullPoint_test
class QhullPoints
Java-style iterator.
class QhullPoints_test
class QhullPointSet
class QhullPointSet_test
class QhullPointsIterator
class QhullQh
POD type equivalent to qhT. No virtual members.
class QhullRidge
class QhullRidge_test
class QhullSet
QhullSet<T> – A read-only wrapper to Qhull's collection class, setT. QhullSet is similar to STL's <vector> and Qt's QVector QhullSet is unrelated to STL and Qt's set and map types (e.g., QSet and QMap) T is a Qhull type that defines 'base_type' and getBaseT() (e.g., QhullFacet with base_type 'facetT *' A QhullSet does not own its contents – erase(), clear(), removeFirst(), removeLast(), pop_back(), pop_front(), fromStdList() not defined QhullSetIterator is faster than STL-style iterator/const_iterator Qhull's FOREACHelement_() [qset_r.h] maybe more efficient than QhullSet. It uses a NULL terminator instead of an end pointer. STL requires an end pointer. Derived from QhullLinkedList.h and Qt/core/tools/qlist.h w/o QT_STRICT_ITERATORS.
class QhullSet_test
class QhullSetBase
Base class for QhullSet<T> QhullSet<T> defined below QhullSetIterator<T> defined below.
class QhullSetIterator
Faster then interator/const_iterator due to T::base_type.
class QhullStat
class QhullVertex
class QhullVertex_test
class QhullVertexSet
class QhullVertexSet_test
class RboxPoints
class RboxPoints_test
Test C++ interface to Rbox See eg/q_test for tests of rbox commands.
class RoadError
struct RoadLogEvent
union RoadLogEvent.__unnamed700__
Float argument (f, for logging)
class RoadTest
class SumOf
Sum of the elements in a container.
class SumSquaresOf
Sum of squares of the elements in a container.
Typedefs
Defined here
typedef QhullSet< QhullRidge > QhullRidgeSet
typedef QhullLinkedListIterator< QhullFacet > QhullFacetListIterator
QhullFacetListIterator – if(f.isGood()){ ... }.
typedef QhullSetIterator< QhullFacet > QhullFacetSetIterator
typedef QhullSetIterator< QhullPoint > QhullPointSetIterator
typedef QhullSetIterator< QhullRidge > QhullRidgeSetIterator
typedef QhullLinkedList< QhullVertex > QhullVertexList
typedef QhullLinkedListIterator< QhullVertex > QhullVertexListIterator
typedef QhullSetIterator< QhullVertex > QhullVertexSetIterator
Functions
void add_Coordinates_test ()
void add_PointCoordinates_test ()
void add_Qhull_test ()
void add_QhullFacet_test ()
void add_QhullFacetList_test ()
void add_QhullFacetSet_test ()
void add_QhullHyperplane_test ()
void add_QhullLinkedList_test ()
void add_QhullPoint_test ()
void add_QhullPoints_test ()
void add_QhullPointSet_test ()
void add_QhullRidge_test ()
void add_QhullSet_test ()
void addQhullTests (QStringList &args)
int main (int argc, char *argv[])
void add_QhullVertex_test ()
void add_QhullVertexSet_test ()
void add_RboxPoints_test ()
Variables
Global variables
const char s_unsupported_options [] =" Fd TI "
const char s_not_output_options [] = " Fd TI A C d E H P Qb QbB Qbb Qc Qf Qg Qi Qm QJ Qr QR Qs Qt Qv Qx Qz Q0 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 Q10 Q11 R Tc TC TM TP TR Tv TV TW U v V W "
Detailed Description
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
QhullVertex – Qhull's vertex structure, vertexT, as a C++ class.
QhullSet – Qhull's set structure, setT, as a C++ class.
Class Documentation
orgQhull::RoadLogEvent.__unnamed700__
union orgQhull::RoadLogEvent.__unnamed700__
Float argument (f, for logging)
Class Members
const char * cstr_1 One additional argument (for logging)
double double_1 signed int64 (i). Ambiguous if unsigned is also defined.
long long int64_1 Void* argument (x) – Use upper-case codes for object types.
const void * void_1 Cstr argument (s) – type checked at construct-time.
Typedef Documentation
QhullFacetListIterator
typedef QhullLinkedListIterator<QhullFacet> orgQhull::QhullFacetListIterator
QhullFacetListIterator – if(f.isGood()){ ... }.
QhullFacetSetIterator
typedef QhullSetIterator<QhullFacet> orgQhull::QhullFacetSetIterator
QhullPointSetIterator
typedef QhullSetIterator<QhullPoint> orgQhull::QhullPointSetIterator
QhullRidgeSet
typedef QhullSet< QhullRidge > orgQhull::QhullRidgeSet
QhullRidgeSetIterator
typedef QhullSetIterator< QhullRidge > orgQhull::QhullRidgeSetIterator
QhullVertexList
typedef QhullLinkedList<QhullVertex> orgQhull::QhullVertexList
QhullVertexListIterator
typedef QhullLinkedListIterator<QhullVertex> orgQhull::QhullVertexListIterator
QhullVertexSetIterator
typedef QhullSetIterator<QhullVertex> orgQhull::QhullVertexSetIterator
Function Documentation
add_Coordinates_test()
void orgQhull::add_Coordinates_test ()
{
    new Coordinates_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_PointCoordinates_test()
void orgQhull::add_PointCoordinates_test ()
{
    new PointCoordinates_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_Qhull_test()
void orgQhull::add_Qhull_test ()
{
    new Qhull_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullFacet_test()
void orgQhull::add_QhullFacet_test ()
{
    new QhullFacet_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullFacetList_test()
void orgQhull::add_QhullFacetList_test ()
{
    new QhullFacetList_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullFacetSet_test()
void orgQhull::add_QhullFacetSet_test ()
{
    new QhullFacetSet_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullHyperplane_test()
void orgQhull::add_QhullHyperplane_test ()
{
    new QhullHyperplane_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullLinkedList_test()
void orgQhull::add_QhullLinkedList_test ()
{
    new QhullLinkedList_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullPoint_test()
void orgQhull::add_QhullPoint_test ()
{
    new QhullPoint_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullPoints_test()
void orgQhull::add_QhullPoints_test ()
{
    new QhullPoints_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullPointSet_test()
void orgQhull::add_QhullPointSet_test ()
{
    new QhullPointSet_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullRidge_test()
void orgQhull::add_QhullRidge_test ()
{
    new QhullRidge_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullSet_test()
void orgQhull::add_QhullSet_test ()
{
    new QhullSet_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullVertex_test()
void orgQhull::add_QhullVertex_test ()
{
    new QhullVertex_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_QhullVertexSet_test()
void orgQhull::add_QhullVertexSet_test ()
{
    new QhullVertexSet_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
add_RboxPoints_test()
void orgQhull::add_RboxPoints_test ()
{
    new RboxPoints_test();  // RoadTest::s_testcases
}
Referenced by addQhullTests().
addQhullTests()
void orgQhull::addQhullTests (QStringList & args)
{
    TESTadd_(add_Qhull_test);
    if(args.contains("--all")){
        args.removeAll("--all");
        // up-to-date
        TESTadd_(add_Coordinates_test);
        TESTadd_(add_PointCoordinates_test);
        TESTadd_(add_QhullFacet_test);
        TESTadd_(add_QhullFacetList_test);
        TESTadd_(add_QhullFacetSet_test);
        TESTadd_(add_QhullHyperplane_test);
        TESTadd_(add_QhullLinkedList_test);
        TESTadd_(add_QhullPoint_test);
        TESTadd_(add_QhullPoints_test);
        TESTadd_(add_QhullPointSet_test);
        TESTadd_(add_QhullRidge_test);
        TESTadd_(add_QhullSet_test);
        TESTadd_(add_QhullVertex_test);
        TESTadd_(add_QhullVertexSet_test);
        TESTadd_(add_RboxPoints_test);
        // qhullStat
        TESTadd_(add_Qhull_test);
    }//--all
}//addQhullTests
References add_Coordinates_test(), add_PointCoordinates_test(), add_Qhull_test(), add_QhullFacet_test(), add_QhullFacetList_test(), add_QhullFacetSet_test(), add_QhullHyperplane_test(), add_QhullLinkedList_test(), add_QhullPoint_test(), add_QhullPoints_test(), add_QhullPointSet_test(), add_QhullRidge_test(), add_QhullSet_test(), add_QhullVertex_test(), add_QhullVertexSet_test(), add_RboxPoints_test(), and TESTadd_.
Referenced by main().
main()
int orgQhull::main (int argc, char * argv[])
{
    QCoreApplication app(argc, argv);
    QStringList args= app.arguments();
    bool isAll= args.contains("--all");
    QHULL_LIB_CHECK /* Check for compatible library */
    addQhullTests(args);
    int status=1010;
    try{
        status= RoadTest::runTests(args);
    }catch(const std::exception &e){
        cout << "FAIL!  : runTests() did not catch error\n";
        cout << e.what() << endl;
        if(!RoadError::emptyGlobalLog()){
            cout << RoadError::stringGlobalLog() << endl;
            RoadError::clearGlobalLog();
        }
    }
    if(!RoadError::emptyGlobalLog()){
        cout << RoadError::stringGlobalLog() << endl;
        RoadError::clearGlobalLog();
    }
    if(isAll){
        cout << "Finished test of libqhullcpp.  Test libqhull_r with eg/q_test after building libqhull_r/Makefile" << endl;
    }else{
        cout << "Finished test of one class.  Test all classes with 'qhulltest --all'" << endl;
    }
    RoadTest::deleteTests();
    return status;
}
References addQhullTests(), orgQhull::RoadError::clearGlobalLog(), orgQhull::RoadTest::deleteTests(), orgQhull::RoadError::emptyGlobalLog(), QHULL_LIB_CHECK, orgQhull::RoadTest::runTests(), and orgQhull::RoadError::stringGlobalLog().
Referenced by main().
Variable Documentation
s_not_output_options
const char orgQhull::s_not_output_options[] = " Fd TI A C d E H P Qb QbB Qbb Qc Qf Qg Qi Qm QJ Qr QR Qs Qt Qv Qx Qz Q0 Q1 Q2 Q3 Q4 Q5 Q6 Q7 Q8 Q9 Q10 Q11 R Tc TC TM TP TR Tv TV TW U v V W "
Referenced by orgQhull::Qhull::outputQhull().
s_unsupported_options
const char orgQhull::s_unsupported_options[] =" Fd TI "
Referenced by orgQhull::Qhull::runQhull().