OrcaSlicer: orgQhull::QhullFacetSet Class Reference
orgQhull::QhullFacetSet Class Reference
#include <src/qhull/src/libqhullcpp/QhullFacetSet.h>
Classes
struct PrintFacetSet
struct PrintIdentifiers
Public Types
Defined here
typedef facetT * base_type
Defined here
Workaround for no setT allocator. Used if setT* is NULL
typedef QhullSet< QhullFacet >::iterator Iterator
typedef QhullSet< QhullFacet >::const_iterator ConstIterator
Public Member Functions
Conversion
std::vector< QhullFacet > toStdVector () const
GetSet
Filtered by facet.isGood(). May be 0 when !isEmpty().
countT count () const
bool contains (const QhullFacet &f) const
countT count (const QhullFacet &f) const
bool isSelectAll () const
void selectAll ()
operator==() does not depend on isGood()
void selectGood ()
IO
const PrintFacetSet print (const char *message) const
PrintIdentifiers printIdentifiers (const char *message) const
Element access
const QhullFacet at (countT idx) const
const QhullFacet back () const
QhullFacet back ()
const T::base_type * constData () const
end element is NULL
T::base_type * data ()
const T::base_type * data () const
T::base_type * endData ()
const T::base_type * endData () const
const QhullFacet first () const
QhullFacet first ()
const QhullFacet front () const
QhullFacet front ()
const QhullFacet last () const
QhullFacet last ()
const QhullFacet operator[] (countT idx) const
QhullFacet operator[] (countT idx)
const QhullFacet second () const
QhullFacet second ()
QhullFacet value (countT idx) const
QhullFacet value (countT idx, const QhullFacet &defaultValue) const
iterator
iterator begin ()
const_iterator begin () const
const_iterator constBegin () const
const_iterator constEnd () const
iterator end ()
const_iterator end () const
Search
bool contains (const QhullFacet &t) const
countT count (const QhullFacet &t) const
countT indexOf (const QhullFacet &t) const
countT lastIndexOf (const QhullFacet &t) const
GetSet
void defineAs (setT *s)
Not type-safe since setT may contain any type.
void forceEmpty ()
setT * getSetT () const
QhullQh * qh () const
setT ** referenceSetT ()
size_t size () const
Protected Member Functions
Element
void ** beginPointer () const
void ** elementPointer (countT idx) const
void ** endPointer () const
Always points to 0.
Private Attributes
Fields
bool select_all
Fields –
setT * qh_set
QhullQh * qh_qh
Static Private Attributes
Class objects
static setT s_empty_set
Constructor
True if include bad facets. Default is false.
QhullFacetSet (const Qhull &q, setT *s)
QhullFacetSet (QhullQh *qqh, setT *s)
QhullFacetSet (const QhullFacetSet &other)
Copy constructor copies pointers but not contents. Needed for return by value and parameter passing.
QhullFacetSet & operator= (const QhullFacetSet &other)
Assignment copies pointers but not contents.
QhullFacetSet ()
Disable default constructor. See QhullSetBase.
GetSet – see QhullSetBase for count(), empty(), isEmpty(), size()
bool operator== (const QhullSet< QhullFacet > &other) const
bool operator!= (const QhullSet< QhullFacet > &other) const
bool isEmpty () const
static countT count (const setT *set)
static bool isEmpty (const setT *s)
Detailed Description
Member Typedef Documentation
base_type
typedef facetT* orgQhull::QhullFacetSet::base_type
ConstIterator
typedef QhullSet<QhullFacet >::const_iterator orgQhull::QhullSet< QhullFacet >::ConstIterator inherited
Iterator
typedef QhullSet<QhullFacet >::iterator orgQhull::QhullSet< QhullFacet >::Iterator inherited
Constructor & Destructor Documentation
QhullFacetSet() [1/4]
orgQhull::QhullFacetSet::QhullFacetSet (const Qhull & q, setT * s) inline
: QhullSet<QhullFacet>(q, s), select_all(false) {}
QhullFacetSet() [2/4]
orgQhull::QhullFacetSet::QhullFacetSet (QhullQh * qqh, setT * s) inline
: QhullSet<QhullFacet>(qqh, s), select_all(false) {}
QhullFacetSet() [3/4]
orgQhull::QhullFacetSet::QhullFacetSet (const QhullFacetSet & other) inline
Copy constructor copies pointers but not contents. Needed for return by value and parameter passing.
: QhullSet<QhullFacet>(other), select_all(other.select_all) {}
QhullFacetSet() [4/4]
orgQhull::QhullFacetSet::QhullFacetSet () private
Disable default constructor. See QhullSetBase.
Member Function Documentation
at()
const QhullFacet orgQhull::QhullSet< QhullFacet >::at (countT idx) const inline inherited
{ return operator[](idx); }
back() [1/2]
QhullFacet orgQhull::QhullSet< QhullFacet >::back () inline inherited
{ return last(); }
back() [2/2]
const QhullFacet orgQhull::QhullSet< QhullFacet >::back () const inline inherited
{ return last(); }
begin() [1/2]
iterator orgQhull::QhullSet< QhullFacet >::begin () inline inherited
{ return iterator(qh(), reinterpret_cast<typename T::base_type *>(beginPointer())); }
begin() [2/2]
const_iterator orgQhull::QhullSet< QhullFacet >::begin () const inline inherited
{ return const_iterator(qh(), data()); }
beginPointer()
void ** orgQhull::QhullSetBase::beginPointer () const inline protected inherited
{ return &qh_set->e[0].p; }
References setT::e, setelemT::p, and orgQhull::QhullSetBase::qh_set.
Referenced by orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::constData(), orgQhull::QhullSet< T >::data(), and orgQhull::QhullSet< T >::data().
constBegin()
const_iterator orgQhull::QhullSet< QhullFacet >::constBegin () const inline inherited
{ return const_iterator(qh(), data()); }
constData()
const T::base_type * orgQhull::QhullSet< QhullFacet >::constData () const inline inherited
end element is NULL
{ return reinterpret_cast<const typename T::base_type *>(beginPointer()); }
constEnd()
const_iterator orgQhull::QhullSet< QhullFacet >::constEnd () const inline inherited
{ return const_iterator(qh(), endData()); }
contains() [1/2]
bool orgQhull::QhullFacetSet::contains (const QhullFacet & f) const
{
    if(isSelectAll()){
        return QhullSet<QhullFacet>::contains(facet);
    }
    for(QhullFacetSet::const_iterator i=begin(); i != end(); ++i){
        QhullFacet f= *i;
        if(f==facet && f.isGood()){
            return true;
        }
    }
    return false;
}//contains
References orgQhull::QhullSet< QhullFacet >::begin(), orgQhull::QhullSet< T >::contains(), orgQhull::QhullSet< QhullFacet >::end(), orgQhull::QhullFacet::isGood(), and isSelectAll().
contains() [2/2]
bool orgQhull::QhullSet< QhullFacet >::contains (const QhullFacet & t) const inherited
{
    setT *s= getSetT();
    void *p= t.getBaseT();  // contains() is not inline for better error reporting
    int result= qh_setin(s, p);
    return result!=0;
}//contains
count() [1/4]
int orgQhull::QhullFacetSet::count () const
{
    if(isSelectAll()){
        return QhullSet<QhullFacet>::count();
    }
    int counter= 0;
    for(QhullFacetSet::const_iterator i=begin(); i != end(); ++i){
        QhullFacet f= *i;
        if(f.isGood()){
            counter++;
        }
    }
    return counter;
}//count
References orgQhull::QhullSet< QhullFacet >::begin(), orgQhull::QhullSet< T >::count(), orgQhull::QhullSet< QhullFacet >::end(), orgQhull::QhullFacet::isGood(), and isSelectAll().
Referenced by orgQhull::QhullFacetSet_test::t_construct(), orgQhull::QhullFacetSet_test::t_convert(), orgQhull::QhullFacet_test::t_foreach(), orgQhull::QhullSet_test::t_qhullset_iterator(), and orgQhull::QhullSet_test::t_qhullsetbase().
count() [2/4]
int orgQhull::QhullFacetSet::count (const QhullFacet & f) const
{
    if(isSelectAll()){
        return QhullSet<QhullFacet>::count(facet);
    }
    int counter= 0;
    for(QhullFacetSet::const_iterator i=begin(); i != end(); ++i){
        QhullFacet f= *i;
        if(f==facet && f.isGood()){
            counter++;
        }
    }
    return counter;
}//count
References orgQhull::QhullSet< QhullFacet >::begin(), orgQhull::QhullSet< T >::count(), orgQhull::QhullSet< QhullFacet >::end(), orgQhull::QhullFacet::isGood(), and isSelectAll().
count() [3/4]
countT orgQhull::QhullSet< QhullFacet >::count (const QhullFacet & t) const inherited
{
    countT n= 0;
    const typename T::base_type *i= data();
    const typename T::base_type *e= endData();
    typename T::base_type p= t.getBaseT();
    while(i<e){
        if(*i==p){
            n++;
        }
        i++;
    }
    return n;
}//count
count() [4/4]
countT orgQhull::QhullSetBase::count (const setT * set) static inherited
{
    countT size;
    const setelemT *sizep;
    if (!set){
        return(0);
    }
    sizep= SETsizeaddr_(set);
    if ((size= sizep->i)) {
        size--;
        if (size > set->maxsize) {
            // FIXUP QH11022 How to add additional output to a error? -- qh_setprint(qhmem.ferr, "set: ", set);
            throw QhullError(10032, "QhullSet internal error: current set size %d is greater than maximum size %d\n",
                size, set->maxsize);
        }
    }else{
        size= set->maxsize;
    }
    return size;
}//count
data() [1/2]
T::base_type * orgQhull::QhullSet< QhullFacet >::data () inline inherited
{ return reinterpret_cast<typename T::base_type *>(beginPointer()); }
data() [2/2]
const T::base_type * orgQhull::QhullSet< QhullFacet >::data () const inline inherited
{ return reinterpret_cast<const typename T::base_type *>(beginPointer()); }
defineAs()
void orgQhull::QhullSetBase::defineAs (setT * s) inline inherited
Not type-safe since setT may contain any type.
References orgQhull::QhullSetBase::qh_set, and orgQhull::QhullSetBase::s_empty_set.
Referenced by orgQhull::QhullVertexSet::QhullVertexSet(), and orgQhull::QhullVertexSet::QhullVertexSet().
elementPointer()
void ** orgQhull::QhullSetBase::elementPointer (countT idx) const inline protected inherited
{ QHULL_ASSERT(idx>=0 && idx<qh_set->maxsize); return &SETelem_(qh_set, idx); }
References orgQhull::QhullSetBase::qh_set, QHULL_ASSERT, and SETelem_.
Referenced by orgQhull::QhullSet< T >::operator[](), and orgQhull::QhullSet< T >::operator[]().
end() [1/2]
iterator orgQhull::QhullSet< QhullFacet >::end () inline inherited
{ return iterator(qh(), endData()); }
end() [2/2]
const_iterator orgQhull::QhullSet< QhullFacet >::end () const inline inherited
{ return const_iterator(qh(), endData()); }
endData() [1/2]
T::base_type * orgQhull::QhullSet< QhullFacet >::endData () inline inherited
{ return reinterpret_cast<typename T::base_type *>(endPointer()); }
endData() [2/2]
const T::base_type * orgQhull::QhullSet< QhullFacet >::endData () const inline inherited
{ return reinterpret_cast<const typename T::base_type *>(endPointer()); }
endPointer()
void ** orgQhull::QhullSetBase::endPointer () const inline protected inherited
Always points to 0.
{ return qh_setendpointer(qh_set); }
References orgQhull::QhullSetBase::qh_set, and qh_setendpointer().
Referenced by orgQhull::QhullSet< T >::endData(), and orgQhull::QhullSet< T >::endData().
first() [1/2]
QhullFacet orgQhull::QhullSet< QhullFacet >::first () inline inherited
{ QHULL_ASSERT(!isEmpty()); return T(qh(), *data()); }
first() [2/2]
const QhullFacet orgQhull::QhullSet< QhullFacet >::first () const inline inherited
{ QHULL_ASSERT(!isEmpty()); return T(qh(), *data()); }
forceEmpty()
void orgQhull::QhullSetBase::forceEmpty () inline inherited
{ qh_set= &s_empty_set; }
References orgQhull::QhullSetBase::qh_set, and orgQhull::QhullSetBase::s_empty_set.
front() [1/2]
QhullFacet orgQhull::QhullSet< QhullFacet >::front () inline inherited
{ return first(); }
front() [2/2]
const QhullFacet orgQhull::QhullSet< QhullFacet >::front () const inline inherited
{ return first(); }
getSetT()
setT * orgQhull::QhullSetBase::getSetT () const inline inherited
{ return qh_set; }
References orgQhull::QhullSetBase::qh_set.
Referenced by orgQhull::QhullSet< T >::indexOf(), orgQhull::QhullSet< T >::operator==(), and orgQhull::QhullSet_test::t_qhullsetbase().
indexOf()
countT orgQhull::QhullSet< QhullFacet >::indexOf (const QhullFacet & t) const inline inherited
{ /* no qh_qh */ return qh_setindex(getSetT(), t.getBaseT()); }
isEmpty() [1/2]
bool orgQhull::QhullSetBase::isEmpty () const inline inherited
{ return SETempty_(qh_set); }
isEmpty() [2/2]
static bool orgQhull::QhullSetBase::isEmpty (const setT * s) inline static inherited
{ return SETempty_(s); }
isSelectAll()
bool orgQhull::QhullFacetSet::isSelectAll () const inline
{ return select_all; }
References select_all.
Referenced by contains(), count(), count(), orgQhull::QhullFacetSet_test::t_convert(), and toStdVector().
last() [1/2]
QhullFacet orgQhull::QhullSet< QhullFacet >::last () inline inherited
{ QHULL_ASSERT(!isEmpty()); return T(qh(), *(endData()-1)); }
last() [2/2]
const QhullFacet orgQhull::QhullSet< QhullFacet >::last () const inline inherited
{ QHULL_ASSERT(!isEmpty()); return T(qh(), *(endData()-1)); }
lastIndexOf()
countT orgQhull::QhullSet< QhullFacet >::lastIndexOf (const QhullFacet & t) const inherited
{
    const typename T::base_type *b= data();
    const typename T::base_type *i= endData();
    typename T::base_type p= t.getBaseT();
    while(--i>=b){
        if(*i==p){
            break;
        }
    }
    return (countT)(i-b); // WARN64
}//lastIndexOf
operator!=()
bool orgQhull::QhullSet< QhullFacet >::operator!= (const QhullSet< QhullFacet > & other) const inline inherited
{ return !operator==(other); }
operator=()
QhullFacetSet & orgQhull::QhullFacetSet::operator= (const QhullFacetSet & other) inline
Assignment copies pointers but not contents.
{ QhullSet<QhullFacet>::operator=(other); select_all= other.select_all; return *this; }
References orgQhull::QhullSet< T >::operator=(), and select_all.
operator==()
bool orgQhull::QhullSet< QhullFacet >::operator== (const QhullSet< QhullFacet > & other) const inline inherited
{ return qh_setequal(getSetT(), other.getSetT()); }
operator[]() [1/2]
QhullFacet orgQhull::QhullSet< QhullFacet >::operator[] (countT idx) inline inherited
{ typename T::base_type *p= reinterpret_cast<typename T::base_type *>(elementPointer(idx)); QHULL_ASSERT(idx>=0 && p < endData()); return T(qh(), *p); }
operator[]() [2/2]
const QhullFacet orgQhull::QhullSet< QhullFacet >::operator[] (countT idx) const inline inherited
{ const typename T::base_type *p= reinterpret_cast<typename T::base_type *>(elementPointer(idx)); QHULL_ASSERT(idx>=0 && p < endData()); return T(qh(), *p); }
print()
const PrintFacetSet orgQhull::QhullFacetSet::print (const char * message) const inline
{ return PrintFacetSet(message, this); }
printIdentifiers()
PrintIdentifiers orgQhull::QhullFacetSet::printIdentifiers (const char * message) const inline
{ return PrintIdentifiers(message, this); }
qh()
QhullQh * orgQhull::QhullSetBase::qh () const inline inherited
{ return qh_qh; }
References orgQhull::QhullSetBase::qh_qh.
Referenced by orgQhull::QhullVertexSet::QhullVertexSet(), orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::begin(), orgQhull::QhullSet< T >::constBegin(), orgQhull::QhullSet< T >::constEnd(), orgQhull::QhullSet< T >::end(), orgQhull::QhullSet< T >::end(), orgQhull::QhullSet< T >::first(), orgQhull::QhullSet< T >::first(), orgQhull::QhullVertexSet::freeQhSetTemp(), orgQhull::QhullSet< T >::last(), orgQhull::QhullSet< T >::last(), operator<<(), orgQhull::QhullSet< T >::operator[](), and orgQhull::QhullSet< T >::operator[]().
referenceSetT()
setT ** orgQhull::QhullSetBase::referenceSetT () inline inherited
{ return &qh_set; }
References orgQhull::QhullSetBase::qh_set.
Referenced by orgQhull::QhullVertexSet::freeQhSetTemp().
second() [1/2]
QhullFacet orgQhull::QhullSet< QhullFacet >::second () inline inherited
{ return operator[](1); }
second() [2/2]
const QhullFacet orgQhull::QhullSet< QhullFacet >::second () const inline inherited
{ return operator[](1); }
selectAll()
void orgQhull::QhullFacetSet::selectAll () inline
operator==() does not depend on isGood()
{ select_all= true; }
References select_all.
Referenced by orgQhull::QhullFacetSet_test::t_convert().
selectGood()
void orgQhull::QhullFacetSet::selectGood () inline
{ select_all= false; }
References select_all.
size()
size_t orgQhull::QhullSetBase::size () const inline inherited
{ return QhullSetBase::count(qh_set); }
References orgQhull::QhullSetBase::count(), and orgQhull::QhullSetBase::qh_set.
Referenced by orgQhull::QhullSetBase::count(), operator<<(), orgQhull::QhullPointSet_test::t_construct(), orgQhull::QhullPointSet_test::t_convert(), and orgQhull::QhullSet_test::t_qhullsetbase().
toStdVector()
std::vector< QhullFacet > orgQhull::QhullFacetSet::toStdVector () const
{
    QhullSetIterator<QhullFacet> i(*this);
    std::vector<QhullFacet> vs;
    while(i.hasNext()){
        QhullFacet f= i.next();
        if(isSelectAll() || f.isGood()){
            vs.push_back(f);
        }
    }
    return vs;
}//toStdVector
References orgQhull::QhullSetIterator< T >::hasNext(), orgQhull::QhullFacet::isGood(), isSelectAll(), and orgQhull::QhullSetIterator< T >::next().
Referenced by orgQhull::QhullFacetSet_test::t_convert().
value() [1/2]
QhullFacet orgQhull::QhullSet< QhullFacet >::value (countT idx) const inherited
{
    // Avoid call to qh_setsize() and assert in elementPointer()
    const typename T::base_type *p= reinterpret_cast<const typename T::base_type *>(&SETelem_(getSetT(), idx));
    return (idx>=0 && p<endData()) ? T(qh(), *p) : T(qh());
}//value
value() [2/2]
QhullFacet orgQhull::QhullSet< QhullFacet >::value (countT idx, const QhullFacet & defaultValue) const inherited
{
    // Avoid call to qh_setsize() and assert in elementPointer()
    const typename T::base_type *p= reinterpret_cast<const typename T::base_type *>(&SETelem_(getSetT(), idx));
    return (idx>=0 && p<endData() ? T(qh(), *p) : defaultValue);
}//value
Member Data Documentation
qh_qh
QhullQh* orgQhull::QhullSetBase::qh_qh private inherited
Referenced by orgQhull::QhullSetBase::operator=(), and orgQhull::QhullSetBase::qh().
qh_set
setT* orgQhull::QhullSetBase::qh_set private inherited
Referenced by orgQhull::QhullSetBase::beginPointer(), orgQhull::QhullSetBase::count(), orgQhull::QhullSetBase::defineAs(), orgQhull::QhullSetBase::elementPointer(), orgQhull::QhullSetBase::endPointer(), orgQhull::QhullSetBase::forceEmpty(), orgQhull::QhullSetBase::getSetT(), orgQhull::QhullSetBase::isEmpty(), orgQhull::QhullSetBase::operator=(), orgQhull::QhullSetBase::referenceSetT(), and orgQhull::QhullSetBase::size().
s_empty_set
setT orgQhull::QhullSet< QhullFacet >::s_empty_set static private inherited
select_all
bool orgQhull::QhullFacetSet::select_all private
Referenced by isSelectAll(), operator=(), selectAll(), and selectGood().
The documentation for this class was generated from the following files:
src/qhull/src/libqhullcpp/QhullFacetSet.h
src/qhull/src/libqhullcpp/QhullFacetSet.cpp