OrcaSlicer: src/qhull/src/libqhullcpp/QhullPoints.cpp File Reference
QhullPoints.cpp File Reference
#include "libqhullcpp/QhullPoints.h"
#include "libqhullcpp/Qhull.h"
#include <iostream>
#include <vector>
Namespaces
namespace orgQhull
QhullRidge – Qhull's ridge structure, ridgeT, as a C++ class.
Functions
Global functions
ostream & operator<< (ostream &os, const QhullPoints &p)
ostream & operator<< (ostream &os, const QhullPoints::PrintPoints &pr)
Function Documentation
operator<<() [1/2]
ostream & operator<< (ostream & os, const QhullPoints & p)
{
    QhullPointsIterator i(p);
    while(i.hasNext()){
        os << i.next();
    }
    return os;
}//operator<<QhullPoints
References orgQhull::QhullPointsIterator::hasNext(), and orgQhull::QhullPointsIterator::next().
operator<<() [2/2]
ostream & operator<< (ostream & os, const QhullPoints::PrintPoints & pr)
{
    os << pr.point_message;
    QhullPoints ps= *pr.points;
    for(QhullPoints::iterator i=ps.begin(); i!=ps.end(); ++i){
        QhullPoint p= *i;
        if(pr.with_identifier){
            os << p.printWithIdentifier("");
        }else{
            os << p.print("");
        }
    }
    return os;
}//<<PrintPoints
References orgQhull::QhullPoints::begin(), orgQhull::QhullPoints::end(), orgQhull::QhullPoint::print(), and orgQhull::QhullPoint::printWithIdentifier().