OrcaSlicer: Slic3r::GLIndexedVertexArray Class Reference
Slic3r::GLIndexedVertexArray Class Reference
#include <src/slic3r/GUI/3DScene.hpp>
Public Types
using BoundingBox = Eigen::AlignedBox< float, 3 >
Public Member Functions
GLIndexedVertexArray ()
GLIndexedVertexArray (const GLIndexedVertexArray &rhs)
GLIndexedVertexArray (GLIndexedVertexArray &&rhs)
~GLIndexedVertexArray ()
GLIndexedVertexArray & operator= (const GLIndexedVertexArray &rhs)
GLIndexedVertexArray & operator= (GLIndexedVertexArray &&rhs)
void load_mesh_full_shading (const TriangleMesh &mesh)
void load_mesh (const TriangleMesh &mesh)
void load_its_flat_shading (const indexed_triangle_set &its)
bool has_VBOs () const
void reserve (size_t sz)
void push_geometry (float x, float y, float z, float nx, float ny, float nz)
void push_geometry (double x, double y, double z, double nx, double ny, double nz)
template<typename Derived , typename Derived2 >
void push_geometry (const Eigen::MatrixBase< Derived > &p, const Eigen::MatrixBase< Derived2 > &n)
void push_triangle (int idx1, int idx2, int idx3)
void push_quad (int idx1, int idx2, int idx3, int idx4)
void finalize_geometry (bool opengl_initialized)
void release_geometry ()
void render () const
void render (const std::pair< size_t, size_t > &tverts_range, const std::pair< size_t, size_t > &qverts_range) const
bool empty () const
void clear ()
void shrink_to_fit ()
const BoundingBox & bounding_box () const
size_t cpu_memory_used () const
size_t gpu_memory_used () const
size_t total_memory_used () const
Public Attributes
std::vector< float > vertices_and_normals_interleaved
std::vector< int > triangle_indices
std::vector< int > quad_indices
size_t vertices_and_normals_interleaved_size { 0 }
size_t triangle_indices_size { 0 }
size_t quad_indices_size { 0 }
unsigned int vertices_and_normals_interleaved_VBO_id { 0 }
unsigned int triangle_indices_VBO_id { 0 }
unsigned int quad_indices_VBO_id { 0 }
Private Attributes
BoundingBox m_bounding_box
Detailed Description
Member Typedef Documentation
BoundingBox
using Slic3r::GLIndexedVertexArray::BoundingBox = Eigen::AlignedBox<float, 3>
Constructor & Destructor Documentation
GLIndexedVertexArray() [1/3]
Slic3r::GLIndexedVertexArray::GLIndexedVertexArray () inline
{ m_bounding_box.setEmpty(); }
References m_bounding_box, and Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty().
GLIndexedVertexArray() [2/3]
Slic3r::GLIndexedVertexArray::GLIndexedVertexArray (const GLIndexedVertexArray & rhs) inline
                                                          :
        vertices_and_normals_interleaved(rhs.vertices_and_normals_interleaved),
        triangle_indices(rhs.triangle_indices),
        quad_indices(rhs.quad_indices),
        m_bounding_box(rhs.m_bounding_box)
        { assert(!rhs.has_VBOs()); m_bounding_box.setEmpty(); }
References has_VBOs(), m_bounding_box, and Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty().
GLIndexedVertexArray() [3/3]
Slic3r::GLIndexedVertexArray::GLIndexedVertexArray (GLIndexedVertexArray && rhs) inline
                                                     :
        vertices_and_normals_interleaved(std::move(rhs.vertices_and_normals_interleaved)),
        triangle_indices(std::move(rhs.triangle_indices)),
        quad_indices(std::move(rhs.quad_indices)),
        m_bounding_box(rhs.m_bounding_box)
        { assert(! rhs.has_VBOs()); }
~GLIndexedVertexArray()
Slic3r::GLIndexedVertexArray::~GLIndexedVertexArray () inline
{ release_geometry(); }
References release_geometry().
Member Function Documentation
bounding_box()
const BoundingBox & Slic3r::GLIndexedVertexArray::bounding_box () const inline
{ return m_bounding_box; }
References m_bounding_box.
Referenced by Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), and Slic3r::GLVolume::bounding_box().
clear()
void Slic3r::GLIndexedVertexArray::clear () inline
                 {
        this->vertices_and_normals_interleaved.clear();
        this->triangle_indices.clear();
        this->quad_indices.clear();
        vertices_and_normals_interleaved_size = 0;
        triangle_indices_size = 0;
        quad_indices_size = 0;
        m_bounding_box.setEmpty();
    }
References m_bounding_box, quad_indices_size, Eigen::AlignedBox< _Scalar, _AmbientDim >::setEmpty(), triangle_indices_size, and vertices_and_normals_interleaved_size.
Referenced by release_geometry(), and Slic3r::GUI::reserve_new_volume_finalize_old_volume().
cpu_memory_used()
size_t Slic3r::GLIndexedVertexArray::cpu_memory_used () const inline
{ return sizeof(*this) + vertices_and_normals_interleaved.capacity() * sizeof(float) + triangle_indices.capacity() * sizeof(int) + quad_indices.capacity() * sizeof(int); }
References int, quad_indices, triangle_indices, and vertices_and_normals_interleaved.
Referenced by Slic3r::GLVolume::cpu_memory_used(), and total_memory_used().
empty()
bool Slic3r::GLIndexedVertexArray::empty () const inline
{ return vertices_and_normals_interleaved_size == 0; }
References vertices_and_normals_interleaved_size.
Referenced by Slic3r::GLVolume::empty().
finalize_geometry()
void Slic3r::GLIndexedVertexArray::finalize_geometry (bool opengl_initialized)
{
    assert(this->vertices_and_normals_interleaved_VBO_id == 0);
    assert(this->triangle_indices_VBO_id == 0);
    assert(this->quad_indices_VBO_id == 0);
  if (! opengl_initialized) {
    // Shrink the data vectors to conserve memory in case the data cannot be transfered to the OpenGL driver yet.
    this->shrink_to_fit();
    return;
  }
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__<< boost::format(", this %1% ") %this;
    if (! this->vertices_and_normals_interleaved.empty()) {
        glsafe(::glGenBuffers(1, &this->vertices_and_normals_interleaved_VBO_id));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, this->vertices_and_normals_interleaved_VBO_id));
        glsafe(::glBufferData(GL_ARRAY_BUFFER, this->vertices_and_normals_interleaved.size() * 4, this->vertices_and_normals_interleaved.data(), GL_STATIC_DRAW));
        glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
        this->vertices_and_normals_interleaved.clear();
    }
    if (! this->triangle_indices.empty()) {
        glsafe(::glGenBuffers(1, &this->triangle_indices_VBO_id));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->triangle_indices_VBO_id));
        glsafe(::glBufferData(GL_ELEMENT_ARRAY_BUFFER, this->triangle_indices.size() * 4, this->triangle_indices.data(), GL_STATIC_DRAW));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
        this->triangle_indices.clear();
    }
    if (! this->quad_indices.empty()) {
        glsafe(::glGenBuffers(1, &this->quad_indices_VBO_id));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->quad_indices_VBO_id));
        glsafe(::glBufferData(GL_ELEMENT_ARRAY_BUFFER, this->quad_indices.size() * 4, this->quad_indices.data(), GL_STATIC_DRAW));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
        this->quad_indices.clear();
    }
}
References glsafe, quad_indices, quad_indices_VBO_id, shrink_to_fit(), triangle_indices, triangle_indices_VBO_id, vertices_and_normals_interleaved, and vertices_and_normals_interleaved_VBO_id.
Referenced by Slic3r::GUI::GLGizmoPainterBase::GLGizmoPainterBase(), Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), Slic3r::GUI::GLGizmoFaceDetector::display_exterior_face(), Slic3r::GLVolume::finalize_geometry(), Slic3r::GUI::GLGizmoFdmSupports::generate_support_volume(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), Slic3r::GLVolumeCollection::load_wipe_tower_preview(), and Slic3r::GUI::MeshClipper::recalculate_triangles().
gpu_memory_used()
size_t Slic3r::GLIndexedVertexArray::gpu_memory_used () const inline
    {
      size_t memsize = 0;
      if (this->vertices_and_normals_interleaved_VBO_id != 0)
        memsize += this->vertices_and_normals_interleaved_size * 4;
      if (this->triangle_indices_VBO_id != 0)
        memsize += this->triangle_indices_size * 4;
      if (this->quad_indices_VBO_id != 0)
        memsize += this->quad_indices_size * 4;
      return memsize;
    }
References quad_indices_size, quad_indices_VBO_id, triangle_indices_size, triangle_indices_VBO_id, vertices_and_normals_interleaved_size, and vertices_and_normals_interleaved_VBO_id.
Referenced by Slic3r::GLVolume::gpu_memory_used(), and total_memory_used().
has_VBOs()
bool Slic3r::GLIndexedVertexArray::has_VBOs () const inline
{ return vertices_and_normals_interleaved_VBO_id != 0; }
References vertices_and_normals_interleaved_VBO_id.
Referenced by GLIndexedVertexArray(), Slic3r::GUI::GLGizmoFaceDetector::on_render(), and Slic3r::GUI::MeshClipper::render_cut().
load_its_flat_shading()
void Slic3r::GLIndexedVertexArray::load_its_flat_shading (const indexed_triangle_set & its)
{
    this->vertices_and_normals_interleaved.reserve(this->vertices_and_normals_interleaved.size() + 3 * 3 * 2 * its.indices.size());
    unsigned int vertices_count = 0;
    for (int i = 0; i < int(its.indices.size()); ++ i) {
        stl_triangle_vertex_indices face        = its.indices[i];
        stl_vertex                  vertex[3]   = { its.vertices[face[0]], its.vertices[face[1]], its.vertices[face[2]] };
        stl_vertex                  n           = face_normal_normalized(vertex);
        for (int j = 0; j < 3; ++j)
            this->push_geometry(vertex[j](0), vertex[j](1), vertex[j](2), n(0), n(1), n(2));
        this->push_triangle(vertices_count, vertices_count + 1, vertices_count + 2);
        vertices_count += 3;
    }
    BOOST_LOG_TRIVIAL(debug) << __FUNCTION__<< boost::format(", this %1%, indices size %2%, vertices %3%, triangles %4% ")
            %this %its.indices.size() %this->vertices_and_normals_interleaved.size() %this->triangle_indices.size() ;
}
References Slic3r::face_normal_normalized(), indexed_triangle_set::indices, int, n, push_geometry(), push_triangle(), triangle_indices, indexed_triangle_set::vertices, and vertices_and_normals_interleaved.
Referenced by Slic3r::GUI::GLGizmoPainterBase::GLGizmoPainterBase().
load_mesh()
void Slic3r::GLIndexedVertexArray::load_mesh (const TriangleMesh & mesh) inline
{ this->load_mesh_full_shading(mesh); }
References load_mesh_full_shading().
Referenced by Slic3r::GUI::GLCanvas3D::_load_sla_shells(), Slic3r::GLVolumeCollection::load_object_auxiliary(), Slic3r::GLVolumeCollection::load_object_volume(), and Slic3r::GLVolumeCollection::load_wipe_tower_preview().
load_mesh_full_shading()
void Slic3r::GLIndexedVertexArray::load_mesh_full_shading (const TriangleMesh & mesh)
{
    assert(triangle_indices.empty() && vertices_and_normals_interleaved_size == 0);
    assert(quad_indices.empty() && triangle_indices_size == 0);
    assert(vertices_and_normals_interleaved.size() % 6 == 0 && quad_indices_size == vertices_and_normals_interleaved.size());
#if ENABLE_SMOOTH_NORMALS
    if (smooth_normals) {
        TriangleMesh new_mesh(mesh);
        std::vector<stl_normal> normals;
        smooth_normals_corner(new_mesh, normals);
//        smooth_normals_vertex(new_mesh, normals);
        this->vertices_and_normals_interleaved.reserve(this->vertices_and_normals_interleaved.size() + 3 * 2 * new_mesh.its.vertices.size());
        for (size_t i = 0; i < new_mesh.its.vertices.size(); ++i) {
            const stl_vertex& v = new_mesh.its.vertices[i];
            const stl_normal& n = normals[i];
            this->push_geometry(v(0), v(1), v(2), n(0), n(1), n(2));
        }
        for (size_t i = 0; i < new_mesh.its.indices.size(); ++i) {
            const stl_triangle_vertex_indices& idx = new_mesh.its.indices[i];
            this->push_triangle(idx(0), idx(1), idx(2));
        }
    }
    else {
#endif // ENABLE_SMOOTH_NORMALS
        this->load_its_flat_shading(mesh.its);
#if ENABLE_SMOOTH_NORMALS
    }
#endif // ENABLE_SMOOTH_NORMALS
}
References indexed_triangle_set::indices, Slic3r::TriangleMesh::its, n, and indexed_triangle_set::vertices.
Referenced by load_mesh().
operator=() [1/2]
GLIndexedVertexArray & Slic3r::GLIndexedVertexArray::operator= (const GLIndexedVertexArray & rhs) inline
    {
        assert(vertices_and_normals_interleaved_VBO_id == 0);
        assert(triangle_indices_VBO_id == 0);
        assert(quad_indices_VBO_id == 0);
        assert(rhs.vertices_and_normals_interleaved_VBO_id == 0);
        assert(rhs.triangle_indices_VBO_id == 0);
        assert(rhs.quad_indices_VBO_id == 0);
        this->vertices_and_normals_interleaved     = rhs.vertices_and_normals_interleaved;
        this->triangle_indices                     = rhs.triangle_indices;
        this->quad_indices                         = rhs.quad_indices;
        this->m_bounding_box                       = rhs.m_bounding_box;
        this->vertices_and_normals_interleaved_size  = rhs.vertices_and_normals_interleaved_size;
        this->triangle_indices_size                  = rhs.triangle_indices_size;
        this->quad_indices_size                      = rhs.quad_indices_size;
        return *this;
    }
References m_bounding_box, quad_indices, quad_indices_size, quad_indices_VBO_id, triangle_indices, triangle_indices_size, triangle_indices_VBO_id, vertices_and_normals_interleaved, vertices_and_normals_interleaved_size, and vertices_and_normals_interleaved_VBO_id.
operator=() [2/2]
GLIndexedVertexArray & Slic3r::GLIndexedVertexArray::operator= (GLIndexedVertexArray && rhs) inline
    {
        assert(vertices_and_normals_interleaved_VBO_id == 0);
        assert(triangle_indices_VBO_id == 0);
        assert(quad_indices_VBO_id == 0);
        assert(rhs.vertices_and_normals_interleaved_VBO_id == 0);
        assert(rhs.triangle_indices_VBO_id == 0);
        assert(rhs.quad_indices_VBO_id == 0);
        this->vertices_and_normals_interleaved     = std::move(rhs.vertices_and_normals_interleaved);
        this->triangle_indices                     = std::move(rhs.triangle_indices);
        this->quad_indices                         = std::move(rhs.quad_indices);
        this->m_bounding_box                       = rhs.m_bounding_box;
        this->vertices_and_normals_interleaved_size  = rhs.vertices_and_normals_interleaved_size;
        this->triangle_indices_size                  = rhs.triangle_indices_size;
        this->quad_indices_size                      = rhs.quad_indices_size;
        return *this;
    }
References m_bounding_box, quad_indices, quad_indices_size, quad_indices_VBO_id, triangle_indices, triangle_indices_size, triangle_indices_VBO_id, vertices_and_normals_interleaved, vertices_and_normals_interleaved_size, and vertices_and_normals_interleaved_VBO_id.
push_geometry() [1/3]
template<typename Derived , typename Derived2 > void Slic3r::GLIndexedVertexArray::push_geometry (const Eigen::MatrixBase< Derived > & p, const Eigen::MatrixBase< Derived2 > & n) inline
{
        push_geometry(float(p(0)), float(p(1)), float(p(2)), float(n(0)), float(n(1)), float(n(2)));
    }
References n, and push_geometry().
push_geometry() [2/3]
void Slic3r::GLIndexedVertexArray::push_geometry (double x, double y, double z, double nx, double ny, double nz) inline
{
        push_geometry(float(x), float(y), float(z), float(nx), float(ny), float(nz));
    }
References push_geometry().
push_geometry() [3/3]
void Slic3r::GLIndexedVertexArray::push_geometry (float x, float y, float z, float nx, float ny, float nz) inline
{
        assert(this->vertices_and_normals_interleaved_VBO_id == 0);
        if (this->vertices_and_normals_interleaved_VBO_id != 0)
            return;
        if (this->vertices_and_normals_interleaved.size() + 6 > this->vertices_and_normals_interleaved.capacity())
            this->vertices_and_normals_interleaved.reserve(next_highest_power_of_2(this->vertices_and_normals_interleaved.size() + 6));
        this->vertices_and_normals_interleaved.emplace_back(nx);
        this->vertices_and_normals_interleaved.emplace_back(ny);
        this->vertices_and_normals_interleaved.emplace_back(nz);
        this->vertices_and_normals_interleaved.emplace_back(x);
        this->vertices_and_normals_interleaved.emplace_back(y);
        this->vertices_and_normals_interleaved.emplace_back(z);
        this->vertices_and_normals_interleaved_size = this->vertices_and_normals_interleaved.size();
        m_bounding_box.extend(Vec3f(x, y, z));
    };
References Eigen::AlignedBox< _Scalar, _AmbientDim >::extend(), m_bounding_box, Slic3r::next_highest_power_of_2(), vertices_and_normals_interleaved_size, and vertices_and_normals_interleaved_VBO_id.
Referenced by Slic3r::GUI::GLGizmoFaceDetector::display_exterior_face(), load_its_flat_shading(), push_geometry(), push_geometry(), Slic3r::GUI::MeshClipper::recalculate_triangles(), and Slic3r::GUI::TriangleSelectorGUI::update_render_data().
push_quad()
void Slic3r::GLIndexedVertexArray::push_quad (int idx1, int idx2, int idx3, int idx4) inline
{
        assert(this->vertices_and_normals_interleaved_VBO_id == 0);
        if (this->vertices_and_normals_interleaved_VBO_id != 0)
            return;
        if (this->quad_indices.size() + 4 > this->vertices_and_normals_interleaved.capacity())
            this->quad_indices.reserve(next_highest_power_of_2(this->quad_indices.size() + 4));
        this->quad_indices.emplace_back(idx1);
        this->quad_indices.emplace_back(idx2);
        this->quad_indices.emplace_back(idx3);
        this->quad_indices.emplace_back(idx4);
        this->quad_indices_size = this->quad_indices.size();
    };
References Slic3r::next_highest_power_of_2(), quad_indices_size, and vertices_and_normals_interleaved_VBO_id.
push_triangle()
void Slic3r::GLIndexedVertexArray::push_triangle (int idx1, int idx2, int idx3) inline
{
        assert(this->vertices_and_normals_interleaved_VBO_id == 0);
        if (this->vertices_and_normals_interleaved_VBO_id != 0)
            return;
        if (this->triangle_indices.size() + 3 > this->vertices_and_normals_interleaved.capacity())
            this->triangle_indices.reserve(next_highest_power_of_2(this->triangle_indices.size() + 3));
        this->triangle_indices.emplace_back(idx1);
        this->triangle_indices.emplace_back(idx2);
        this->triangle_indices.emplace_back(idx3);
        this->triangle_indices_size = this->triangle_indices.size();
    };
References Slic3r::next_highest_power_of_2(), triangle_indices_size, and vertices_and_normals_interleaved_VBO_id.
Referenced by Slic3r::GUI::GLGizmoFaceDetector::display_exterior_face(), load_its_flat_shading(), Slic3r::GUI::MeshClipper::recalculate_triangles(), and Slic3r::GUI::TriangleSelectorGUI::update_render_data().
release_geometry()
void Slic3r::GLIndexedVertexArray::release_geometry ()
{
    if (this->vertices_and_normals_interleaved_VBO_id) {
        glsafe(::glDeleteBuffers(1, &this->vertices_and_normals_interleaved_VBO_id));
        this->vertices_and_normals_interleaved_VBO_id = 0;
    }
    if (this->triangle_indices_VBO_id) {
        glsafe(::glDeleteBuffers(1, &this->triangle_indices_VBO_id));
        this->triangle_indices_VBO_id = 0;
    }
    if (this->quad_indices_VBO_id) {
        glsafe(::glDeleteBuffers(1, &this->quad_indices_VBO_id));
        this->quad_indices_VBO_id = 0;
    }
    this->clear();
}
References clear(), glsafe, quad_indices_VBO_id, triangle_indices_VBO_id, and vertices_and_normals_interleaved_VBO_id.
Referenced by ~GLIndexedVertexArray(), Slic3r::GUI::GLGizmoFaceDetector::display_exterior_face(), Slic3r::GUI::GLGizmoFaceDetector::on_set_state(), Slic3r::GUI::MeshClipper::recalculate_triangles(), and Slic3r::GLVolume::release_geometry().
render() [1/2]
void Slic3r::GLIndexedVertexArray::render () const
{
    assert(this->vertices_and_normals_interleaved_VBO_id != 0);
    assert(this->triangle_indices_VBO_id != 0 || this->quad_indices_VBO_id != 0);
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, this->vertices_and_normals_interleaved_VBO_id));
    glsafe(::glVertexPointer(3, GL_FLOAT, 6 * sizeof(float), (const void*)(3 * sizeof(float))));
    glsafe(::glNormalPointer(GL_FLOAT, 6 * sizeof(float), nullptr));
    glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
    glsafe(::glEnableClientState(GL_NORMAL_ARRAY));
    // Render using the Vertex Buffer Objects.
    if (this->triangle_indices_size > 0) {
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->triangle_indices_VBO_id));
        glsafe(::glDrawElements(GL_TRIANGLES, GLsizei(this->triangle_indices_size), GL_UNSIGNED_INT, nullptr));
        glsafe(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
    }
    if (this->quad_indices_size > 0) {
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->quad_indices_VBO_id));
        glsafe(::glDrawElements(GL_QUADS, GLsizei(this->quad_indices_size), GL_UNSIGNED_INT, nullptr));
        glsafe(glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
    }
    glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
    glsafe(::glDisableClientState(GL_NORMAL_ARRAY));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
}
References GL_TRIANGLES, glsafe, quad_indices_size, quad_indices_VBO_id, triangle_indices_size, triangle_indices_VBO_id, and vertices_and_normals_interleaved_VBO_id.
Referenced by Slic3r::GUI::GLGizmoFaceDetector::on_render(), Slic3r::GLVolume::render(), Slic3r::GUI::GLGizmoPainterBase::render_cursor_sphere(), Slic3r::GUI::MeshClipper::render_cut(), and Slic3r::GLVolume::simple_render().
render() [2/2]
void Slic3r::GLIndexedVertexArray::render (const std::pair< size_t, size_t > & tverts_range, const std::pair< size_t, size_t > & qverts_range) const
{
    // this method has been called before calling finalize() ?
    if (this->vertices_and_normals_interleaved_VBO_id == 0 && !this->vertices_and_normals_interleaved.empty())
        return;
    assert(this->vertices_and_normals_interleaved_VBO_id != 0);
    assert(this->triangle_indices_VBO_id != 0 || this->quad_indices_VBO_id != 0);
    // Render using the Vertex Buffer Objects.
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, this->vertices_and_normals_interleaved_VBO_id));
    glsafe(::glVertexPointer(3, GL_FLOAT, 6 * sizeof(float), (const void*)(3 * sizeof(float))));
    glsafe(::glNormalPointer(GL_FLOAT, 6 * sizeof(float), nullptr));
    glsafe(::glEnableClientState(GL_VERTEX_ARRAY));
    glsafe(::glEnableClientState(GL_NORMAL_ARRAY));
    if (this->triangle_indices_size > 0) {
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->triangle_indices_VBO_id));
        glsafe(::glDrawElements(GL_TRIANGLES, GLsizei(std::min(this->triangle_indices_size, tverts_range.second - tverts_range.first)), GL_UNSIGNED_INT, (const void*)(tverts_range.first * 4)));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
    }
    if (this->quad_indices_size > 0) {
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, this->quad_indices_VBO_id));
        glsafe(::glDrawElements(GL_QUADS, GLsizei(std::min(this->quad_indices_size, qverts_range.second - qverts_range.first)), GL_UNSIGNED_INT, (const void*)(qverts_range.first * 4)));
        glsafe(::glBindBuffer(GL_ELEMENT_ARRAY_BUFFER, 0));
    }
    glsafe(::glDisableClientState(GL_VERTEX_ARRAY));
    glsafe(::glDisableClientState(GL_NORMAL_ARRAY));
    glsafe(::glBindBuffer(GL_ARRAY_BUFFER, 0));
}
References GL_TRIANGLES, glsafe, quad_indices_size, quad_indices_VBO_id, triangle_indices_size, triangle_indices_VBO_id, vertices_and_normals_interleaved, and vertices_and_normals_interleaved_VBO_id.
reserve()
void Slic3r::GLIndexedVertexArray::reserve (size_t sz) inline
{
        this->vertices_and_normals_interleaved.reserve(sz * 6);
        this->triangle_indices.reserve(sz * 3);
        this->quad_indices.reserve(sz * 4);
    }
Referenced by Slic3r::GUI::reserve_new_volume_finalize_old_volume().
shrink_to_fit()
void Slic3r::GLIndexedVertexArray::shrink_to_fit () inline
{
        this->vertices_and_normals_interleaved.shrink_to_fit();
        this->triangle_indices.shrink_to_fit();
        this->quad_indices.shrink_to_fit();
    }
Referenced by finalize_geometry().
total_memory_used()
size_t Slic3r::GLIndexedVertexArray::total_memory_used () const inline
{ return this->cpu_memory_used() + this->gpu_memory_used(); }
References cpu_memory_used(), and gpu_memory_used().
Member Data Documentation
m_bounding_box
BoundingBox Slic3r::GLIndexedVertexArray::m_bounding_box private
Referenced by GLIndexedVertexArray(), GLIndexedVertexArray(), bounding_box(), clear(), operator=(), operator=(), and push_geometry().
quad_indices
std::vector<int> Slic3r::GLIndexedVertexArray::quad_indices
Referenced by Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), cpu_memory_used(), finalize_geometry(), operator=(), and operator=().
quad_indices_size
size_t Slic3r::GLIndexedVertexArray::quad_indices_size { 0 }
Referenced by clear(), gpu_memory_used(), operator=(), operator=(), push_quad(), render(), Slic3r::GLVolume::render(), render(), Slic3r::GLVolume::set_range(), and Slic3r::GLVolume::simple_render().
quad_indices_VBO_id
unsigned int Slic3r::GLIndexedVertexArray::quad_indices_VBO_id { 0 }
Referenced by finalize_geometry(), gpu_memory_used(), operator=(), operator=(), release_geometry(), render(), and render().
triangle_indices
std::vector<int> Slic3r::GLIndexedVertexArray::triangle_indices
Referenced by Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), cpu_memory_used(), finalize_geometry(), load_its_flat_shading(), operator=(), and operator=().
triangle_indices_size
size_t Slic3r::GLIndexedVertexArray::triangle_indices_size { 0 }
Referenced by clear(), gpu_memory_used(), operator=(), operator=(), push_triangle(), render(), Slic3r::GLVolume::render(), render(), Slic3r::GLVolume::set_range(), and Slic3r::GLVolume::simple_render().
triangle_indices_VBO_id
unsigned int Slic3r::GLIndexedVertexArray::triangle_indices_VBO_id { 0 }
Referenced by finalize_geometry(), gpu_memory_used(), operator=(), operator=(), release_geometry(), render(), and render().
vertices_and_normals_interleaved
std::vector<float> Slic3r::GLIndexedVertexArray::vertices_and_normals_interleaved
Referenced by Slic3r::GUI::GLCanvas3D::_load_print_object_toolpaths(), Slic3r::GUI::GLCanvas3D::_load_wipe_tower_toolpaths(), cpu_memory_used(), finalize_geometry(), load_its_flat_shading(), operator=(), operator=(), and render().
vertices_and_normals_interleaved_size
size_t Slic3r::GLIndexedVertexArray::vertices_and_normals_interleaved_size { 0 }
Referenced by clear(), empty(), gpu_memory_used(), operator=(), operator=(), and push_geometry().
vertices_and_normals_interleaved_VBO_id
unsigned int Slic3r::GLIndexedVertexArray::vertices_and_normals_interleaved_VBO_id { 0 }
Referenced by finalize_geometry(), gpu_memory_used(), has_VBOs(), operator=(), operator=(), push_geometry(), push_quad(), push_triangle(), release_geometry(), render(), and render().
The documentation for this class was generated from the following files:
src/slic3r/GUI/3DScene.hpp
src/slic3r/GUI/3DScene.cpp